### ISSUE TITLE
Pages: change message when there aren't any draft or trashed pages

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#10]
Visiting the 'Drafts' page or 'Trash' page when there are no draft pages or trashed pages, shows the following message (even when there are published pages):

"You haven't published any pages yet. Would you like to publish your first page?"

This is quite confusing when the user *does* have published pages. Can we reword these messages on these screens?

<img width="671" alt="drafts_page" src="https://cloud.githubusercontent.com/assets/128826/11201044/53bf802c-8d26-11e5-89fa-cac6c9d34810.png">

<img width="687" alt="trashed_page" src="https://cloud.githubusercontent.com/assets/128826/11201047/5d1ab77c-8d26-11e5-99f4-34a1323b0191.png">

**Comment by montogeek** [comment]
This was fixed, at this moment it shows the correct messages:
![screen shot 2016-01-26 at 17 32 34](https://cloud.githubusercontent.com/assets/1002461/12597367/d33d1d06-c452-11e5-89e4-0b81682b9148.png)
![screen shot 2016-01-26 at 17 32 26](https://cloud.githubusercontent.com/assets/1002461/12597366/d33bb7b8-c452-11e5-8b1e-1fc295464b07.png)

**Comment by alisterscott** [comment]
Retested and LGTM :+1:
