### ISSUE TITLE
Framework: spaces and braces break the build / hot-reload

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#100]
We noticed today that spaces in the path break the build system. This compounds with another issue using braces (`{` and `}`).

* If there's a space in the path ("` `") then the build fails entirely
* If there are braces in the path ("`{`" and "`}`") then the build succeeds, but hot-reload doesn't work.

These are likely two independent issues, because the second never worked, but the first stopped working in the latest few days (even just this morning? -- 06Nov2015).

Note that while this is a relatively minor problem right now, with the open-sourcing it could cause setup issues, because by default the hard drive on Macs is called `/Volumes/Macintosh HD`, containing a space, thus will likely fail or require a longer tutorial.

`make run` worked for me on a freshly pulled `master` branch yesterday. Today it stopped working (06Nov15)

I've also tried `npm install`, `npm update`, and `make distclean`. Nothing worked.

I did try to check out a very old branch, so old it had to "unbuild" a few things. That branch would `make run` just fine.

After some debugging in slack, we found out that if I rename my harddrive from `Macintosh HD` to just `Macintosh` (no space), it works just fine. 

Partial fix: if we change in `Makefile`:

```
export NODE_PATH := server:shared:$(THIS_DIR)
```

to

```
export NODE_PATH := server:shared:.
```

* Fixes the build issue.
* Doesn't fix hot-reload. :P 

Further info:

- If I `make run` from this path, it works: `~/git/wp-calypso`
- If I `make run` from this path, it breaks: `/Volumes/Macintosh HD/Users/username/git/wp-calypso`

Since Coda insists upon expanding any symlinks (BAD CODA!) it would be so nice if the build process could take spaces into account.

**Comment by klimeryk** [comment]
I've tested this with newest `master` - it seems that in "the meantime" this issue fixed itself. 
I've tested `make run` on Linux with the path `~/workspace/wp calypso` and it worked as it should. Let me know if you can reproduce the behavior reported in this issue.

**Comment by folletto** [comment]
I ran a test and the problem is still present. 

With a path such as: `wp-calypso {git}` HotReload doesn't work.

**Comment by klimeryk** [comment]
Ah, sorry, I missed the part about braces :bow: Either way, I've created #3583 to address any issues with special characters in the path - please test it and let me know if it helped.

**Comment by folletto** [comment]
I did a round of tests:

* `/repo/wp-calypso {git}` builds but hot-reload doesn't work (as [discussed](https://github.com/Automattic/wp-calypso/pull/3583#issuecomment-189266206), we can't do much)
* `/repo/wp-calypso git` builds and hot-reload works
* `/repo/wp-calypso-git` builds and hot-reload works

Weirdly the first time I tried with both spaces and `{` it crashed on `gyp`, but was just the first try. After that it worked. 

:+1:

**Comment by klimeryk** [comment]
Thanks for the extra testing - at least spaces don't break hot reloading... Do you think we should keep this issue open (it was autoclosed by the merge of my PR just now) or leave it closed since it's most likely something that has to be fixed upstream?

**Comment by folletto** [comment]
Yeah... I haven't reopened it exactly for that reason. It's not really dependent on us, even if it's a shame the build tools don't work properly in a modern filesystem. :)
