### ISSUE TITLE
Reader: Strange Ellipses Behavior

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#10009]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ (Reader > Followed Sites)
2. Find post with preview ending in generated ellipses.
3. Resize the window.

#### What I expected
Ellipses should move as if they are part of preview text.

#### What happened instead
Ellipses will not move in coordination with text.

#### Browser / OS version
Chrome 55.0.2883.87, macOS Sierra 10.12.1 (16B2657)

#### Screenshot / Video
https://cldup.com/odJhrxB4Sh.mov (look for ellipses at end of post preview)

#dogfooding

**Comment by blowery** [comment]
@chrisfromthelc that cloudup link is 404ing for me..

**Comment by chrisfromthelc** [comment]
Weird. It works for me. Here's a direct video link: https://cldup.com/odJhrxB4Sh.mov

**Comment by blowery** [comment]
that is bizarre. :D

**Comment by jancavan** [comment]
Closing this. It looks like this was happening with the old cards before Reader Refresh.

This is what I'm seeing now on Chrome 55, Mac OS Sierra:

<img width="792" alt="screenshot 2017-07-19 20 38 32" src="https://user-images.githubusercontent.com/4924246/28399513-5a8ba3d6-6cc2-11e7-86f8-ef63ed4bfd27.png">
