### ISSUE TITLE
Photo cards: Try moving background image with scroll

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10010]
This is just an idea that came up while @blowery and I were chatting. Something to try.

The problem: Our photo cards are so very horizontal, lots of image gets cut off at the top and bottom.

One possible solution: Move the background position of the image as you scroll.

I'm sure this technique has a name (parallax?). Basically the idea is, when the card is at the bottom of the page, the photo would be bottom-aligned with the bounding box (so the bottom of the image is shown). Then, as it scrolls to the top of the page, the photo position moves slowly from the bottom to the top of the page. The result is that the user would see more of the image as they scroll. By the time the image gets to the top of the page, the photo would be top-aligned. So the bounding box is like a window with the photo moving behind it. Could be a cool, and functional, effect.

Something to try? Does this make sense? (cc @jancavan)

**Comment by fraying** [comment]
Appreciate the hustle, @jancavan, @bluefuton, and @samouri. I gave the referenced pr a try and, while the effect is lovely for streams with only an occasional photo card, it gets visually confusing when there's a whole stream of photo cards. Plus, scrolling gets very laggy. So I think we should close this out. It was good to try, but probably not something we can release. (Unless anyone vehemently disagrees.)

**Comment by samouri** [comment]
@fraying I was actually surprised by how much I enjoyed it with the occasional photo.  I thought I would hate it all around!

I agree with closing
