### ISSUE TITLE
Reader: New styles for the stream gap indicator

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#10012]
<img width="931" alt="following_ _reader_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/14350/21153781/f7003e82-c139-11e6-815e-52de1533cb90.png">

Should probably re-style this now that we have a white background. 

To see it, 
1. load http://wpcalypso.wordpress.com/?at=2016-11-01
2. wait for the "new posts" pill to appear. click that pill!
3. scroll down 40 posts and see the indicator

**Comment by blowery** [comment]
An alternative solution would be to kill the indicator entirely and start filling gaps automatically.

**Comment by fraying** [comment]
I'd suggest something like this. Note that it'll need a grey line at the bottom, so that the post below it has its normal line.

![lmp](https://cloud.githubusercontent.com/assets/24388/21156298/35a415ce-c12a-11e6-9e5e-b2917efc2f7a.png)

**Comment by fraying** [comment]
@jancavan could you take a look at this?
