### ISSUE TITLE
Editor: pin Visual/HTML tabs on scroll

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1001]
Raised by @kriskarkoski 

When scrolling down in WP Admin the Visual/HTML tabs remain pinned, but not in Calypso. On a long post, this requires scrolling to the top to change between modes. I don't think pinning makes sense on mobile to save real estate, but would on desktop.

Here's WP Admin for reference:

<img width="788" alt="screen shot 2015-09-17 at 9 35 10 pm" src="https://cloud.githubusercontent.com/assets/1900444/9950098/a60a1dbe-5d84-11e5-92b2-62d558e4aff8.png">

Because they're not visible, you also lose your place in the post when you scroll up to toggle, whereas if the tabs were always accessible we could keep the same section of the post visible.

Also reported in [comment-98](https://horizonfeedback.wordpress.com/2015/09/14/call-for-testing-editor/comment-page-1/#comment-98) on the +horizonfeedback editor call for testing post.

**Comment by lancewillett** [comment]
Another request: https://github.com/Automattic/wp-desktop/issues/166 with a video: https://cloudup.com/cgh-6xZBSaE

**Comment by jblz** [comment]
I was about to create this issue if it didn't already exist.

This is especially bothersome now that my editor selection is maintained between modes. 

When the "Advanced" editing mode is enabled, there seems to be ample room to dock the `Visual` / `HTML` toggler when the ribbon gets pinned:

<img width="714" alt="screen shot 2017-10-16 at 4 35 46 pm" src="https://user-images.githubusercontent.com/1587282/31634287-063d26b4-b291-11e7-8f74-d235459f8517.png">

**Comment by nylen** [comment]
One thing to watch out for here:  the height of the content above the toolbar can change, which makes pinning calculations tricky.  See https://github.com/Automattic/wp-calypso/issues/4907 for some details.

**Comment by folletto** [comment]
FWIW it was a decision made on purpose at the time. This doesn't mean we can't change the decision. For reference the rationale was:

1. The need to switch between the two isn't major.
2. The vertical space gained by not having it is 1-2 lines, which is good.
3. Position isn't preserved, so you'd still be back at the top (I'm aware this isn't true anymore).
4. We are going to remove it regardless in the future once we are able to switch to a better editor design. ;)

**Comment by lancewillett** [comment]
I vote we try for an intermediate solution: sticking the buttons, but not spending more than 1-2 days on it. Otherwise, let's punt it.

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Re-tested and found that both the visual and HTML toolbars are now pinned on scrolling.

<strong>Video:</strong> [17s](https://cloudup.com/cTljVRNB2iG)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/11441 using Firefox 57.0.3 on macOS 10.13.2.</sup>

**Comment by jblz** [comment]
@designsimply as in your video, I'm seeing toolbars pinned with most functionality present (which is awesome!), but I'm not able to see the `Visual | HTML` switching option, so I don't think this is fully solved as it's still not possible to change modes without scrolling back to the top.

**Comment by alisterscott** [comment]
The formatting toolbar doesn't remain when scrolling on mobile as it does on desktop. Raised here: https://github.com/Automattic/wp-calypso/issues/22275

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
