### ISSUE TITLE
Reader: tiled gallery emoji issues in IE11

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#10028]
Native emoji and twemoji images do not appear as expected in IE11 inside a tiled gallery.

Check out the following post: https://wpcalypso.wordpress.com/read/feeds/25801/posts/1050231304

### Chrome

Native emoji:

<img width="537" alt="screen shot 2016-12-14 at 15 17 23" src="https://cloud.githubusercontent.com/assets/17325/21167328/b4241f02-c210-11e6-8676-d626b94e9568.png">

Twemoji image:
<img width="354" alt="screen shot 2016-12-14 at 15 17 32" src="https://cloud.githubusercontent.com/assets/17325/21167329/b42a7d66-c210-11e6-8c0d-1ad3a1dfcf32.png">

### IE11

Native emoji:
<img width="366" alt="screen shot 2016-12-14 at 15 19 43" src="https://cloud.githubusercontent.com/assets/17325/21167355/d80ae112-c210-11e6-888a-5f5b987aea2e.png">

Twemoji image:
<img width="301" alt="screen shot 2016-12-14 at 15 19 37" src="https://cloud.githubusercontent.com/assets/17325/21167354/d805652a-c210-11e6-955c-49952b89b01c.png">

**Comment by raoulwegat** [comment]
@bluefuton: was these errors on Win7?

**Comment by bluefuton** [comment]
> @bluefuton: were these errors on Win7?

@raoulwegat yep! It was on the IE11/Win7 modern.ie virtual machine.
