### ISSUE TITLE
Media: unresponsive when uploading lots of items

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1002]
Raised by @nylen 

I noticed high CPU usage and the Calypso page became unresponsive (~7 second lag in responding to click events) while uploading lots of media items at once:

![media-library-hanging](https://cloud.githubusercontent.com/assets/227022/9508895/add64a52-4c1f-11e5-8894-2708c1e0e89b.gif)

Per discussion with @aduth this means we are doing too many render cycles and we can use [`PureRenderMixin`](https://facebook.github.io/react/docs/pure-render-mixin.html) on components that don't accept complex props.

How can I help identify these components, or otherwise figure out what's causing this slowness?

---

Side note - The upload did eventually complete, and everything looks OK except for one media item:

<img width="283" alt="partial media item" src="https://cloud.githubusercontent.com/assets/227022/9508956/23ff2e92-4c20-11e5-8044-0e9685595d55.png">

---

So, it is occasionally relevant that I'm using Chromium, and a slightly older version than the current release of Chrome.  I've talked to a couple of other people and haven't been able to reproduce this, but we have at least established that it's not due to high numbers of rerenders (see #10682).

Some performance metrics:

<img width="1427" alt="media library renders printinclusive" src="https://cloud.githubusercontent.com/assets/227022/10111740/9713e62e-639b-11e5-8468-af471261084b.png">
<img width="1422" alt="media library renders printexclusive" src="https://cloud.githubusercontent.com/assets/227022/10111738/971237c0-639b-11e5-8afc-c58bd0582134.png">
<img width="1428" alt="media library renders printwasted" src="https://cloud.githubusercontent.com/assets/227022/10111739/9713eb9c-639b-11e5-9b3c-6c8cb1293969.png">

Video with `render-visualizer` enabled (long; you'll want to skip through): https://cloudup.com/cSQqUOcWbL2

**Comment by nylen** [comment]
I've since switched to Chrome stable, and I'm still able to reproduce this issue:

![media-library-hanging-2](https://cloud.githubusercontent.com/assets/227022/11702944/7d34e1d2-9ea0-11e5-816f-65fcbca17d5b.gif)

I think implementing something like https://github.com/Automattic/wp-calypso/issues/1003 would probably help to fix it.

**Comment by coderkevin** [comment]
I also just experienced this issue while uploading 20 pictures to a self-hosted site via calypso. Also, 7 out of the 20 images failed. I was puzzled by why this process was pegging all 4 CPUs as well. Shouldn't it be a data-bound, low CPU usage process?

![screen shot 2016-02-02 at 8 53 52 am](https://cloud.githubusercontent.com/assets/945228/12753026/cf227c6a-c98a-11e5-8e90-f09deb82936d.png)

**Comment by aduth** [comment]
@coderkevin : Can you reproduce failings for any one specific image, or does this only occur when you upload in bulk? If you upload only the single failing image, does it display a more useful error message?

**Comment by coderkevin** [comment]
I uploaded the failed images individually afterward and they each uploaded without issue.

**Comment by aduth** [comment]
FYI the responsiveness may be improved slightly from #6268 due to use of `PureComponent` in rendering spinners (i.e. won't re-render itself) and _possibly_ by #5164 (render SVG using React instead of `dangerouslySetInnerHTML`)

**Comment by nylen** [comment]
This appears to be fixed.  No more high CPU usage, no more stuttering.
