### ISSUE TITLE
Too much space at the top of the stream

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10027]
There's a lot of space above the first card. It looks okay at wider widths ...

![screen shot 2016-12-13 at 3 10 26 pm](https://cloud.githubusercontent.com/assets/24388/21167178/7eed079c-c15f-11e6-94b9-2c881507c5f2.png)

... but could we reduce it to the usual 20px when the sidebar goes away?

So this: 
![screen shot 2016-12-13 at 3 10 22 pm](https://cloud.githubusercontent.com/assets/24388/21167180/7f082a40-c15f-11e6-8529-1687c8c29302.png)

Would be this:
![screen shot 2016-12-13 at 3 10 22 pm copy](https://cloud.githubusercontent.com/assets/24388/21167317/98c9c866-c160-11e6-8f22-1ebb7b162a13.png)

**Comment by bluefuton** [comment]
Did a little testing - curiously this does not affect Chrome but I see it in Safari and IE (Edge).
