### ISSUE TITLE
Reader: investigate performance impact of changes to canonical image picker

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#10026]
In #9284, we made some changes to the way images are picked for display in the Reader.

@alisterscott noted in https://github.com/Automattic/wp-calypso/pull/9284#issuecomment-266906223 that this may have carried some performance impact, as images are now slower to load in the e2e test suite.

We should investigate to make sure that the changes haven't had a negative impact on image load times in the Reader.

**Comment by alisterscott** [comment]
I left a [detailed comment](https://github.com/Automattic/wp-calypso/pull/9284#issuecomment-266926429) on the PR, but it seems the new image loading placeholders were causing the e2e tests to wait for the images which exceeds the 20 second timeout. I've updated the e2e tests to not wait until the images are loaded to stop this timeout being hit.
