### ISSUE TITLE
.org Plans: renewal failure emails are WordPress.com Plan emails

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#10034]
If you subscribe for a Jetpack Plan (Professional Monthly in my case), and then let the plan try to renew, you'll eventually get this email if the renewal fails:

![screen shot 2016-12-14 at 11 57 20](https://cloud.githubusercontent.com/assets/426388/21179466/8a0e170c-c1f4-11e6-932d-153e85cceb3f.png)

> This upgrade includes custom design features, no ads, as well as a free domain.

It would be nice to update those emails to include information that's relevant to the plan mentioned in the email.

**Comment by lancewillett** [comment]
+1 — similar to #10122 which improves the Jetpack specific features in the Plans tables, emails should also reflect the product offerings.

**Comment by jeherve** [comment]
Not an issue anymore, emails are now different.
