### ISSUE TITLE
Posts that end prematurely

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10045]
Something off about how we're showing this feed: https://wordpress.com/read/feeds/57039512

The cards are variable width. They should be as wide as the column.

![screen shot 2016-12-14 at 8 12 58 am](https://cloud.githubusercontent.com/assets/24388/21189984/348ff314-c1d5-11e6-887f-3e10bffbdb2d.png)

cc @jancavan, @bluefuton

**Comment by blowery** [comment]
Working on this. Appears to be because we're `flex: 0 auto` for the details container, which makes them shrink, but now grow. Trying `flex: 1 auto` instead.
