### ISSUE TITLE
Cards: Move Share icon 1-2 px down

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10049]
<img width="827" alt="screen shot 2016-12-14 at 11 31 46 am" src="https://cloud.githubusercontent.com/assets/24388/21191282/787d318c-c1d9-11e6-8ec5-5813465063fe.png">

Thanks for the report, @mattmiklic.

**Comment by blowery** [comment]
Fun, it's perfect in Chrome...
