### ISSUE TITLE
Editor: long tags are cutoff and the X to delete is pushed offscreen

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1004]
Raised by @kriskarkoski 

I entered a long tag that stretched beyond the space provided and noticed a few issues. First, the tag is cutoff without indication and the X to delete is pushed offscreen (it can still be removed by clicking in the tag area and using delete):

<img width="257" alt="screen shot 2015-08-27 at 10 01 35 pm" src="https://cloud.githubusercontent.com/assets/1900444/9537529/71670c30-4d07-11e5-8cd7-35b8e02b1669.png">

Compare this to WP Admin:

<img width="294" alt="screen shot 2015-08-27 at 9 44 04 pm" src="https://cloud.githubusercontent.com/assets/1900444/9537533/8c12bb4c-4d07-11e5-8b9f-28d6141f185f.png">

I'm not sure there's an easy way to make the whole tag visible without stretching it across multiple lines, but since core doesn't seem too concerned about that and a tag this long does seem like a bit of an edge case I think we could add an ellipsis (...) to the tag or blur at the cutoff point and leave enough space to still display the delete X on the right edge.

Also, with a long tag in the suggestions a horizontal scrollbar appears on the tag box:

<img width="252" alt="screen shot 2015-08-27 at 10 01 44 pm" src="https://cloud.githubusercontent.com/assets/1900444/9537580/2c522ffc-4d08-11e5-95ad-55ce84c59462.png">

This was reported by a user in 2426892-t

**Comment by lancewillett** [comment]
See also #918

**Comment by lancewillett** [comment]
Should be fixed with #1669

<img width="391" alt="screen shot 2016-04-26 at 1 51 12 pm" src="https://cloud.githubusercontent.com/assets/66797/14833837/ffa56592-0bb5-11e6-9103-6760ddfefac0.png">
