### ISSUE TITLE
NUX: Support setting a custom domain via a URL parameter

### ISSUE THREAD

**Issue by mattm** [Automattic/wp-calypso#10058]
WordPress.com's old sign up flow supports passing in a URL parameter which prefills the domain search field: 

http://signup.wordpress.com/signup?new=CoolSuacePod.com

![screen shot 2016-12-14 at 2 59 27 pm](https://cloud.githubusercontent.com/assets/44436/21198595/f0259a24-c20d-11e6-9a8c-837e22763787.png)

We still link to the old sign up in one of Automattic's other products, Lean Domain Search:

http://www.leandomainsearch.com/search?q=SuacePod (click on any result)

![screen shot 2016-12-14 at 2 59 53 pm](https://cloud.githubusercontent.com/assets/44436/21198613/fd969654-c20d-11e6-8e05-3914a9e89f66.png)

If Calypso NUX supported passing a custom domain as a URL parameter, we could update Lean Domain Search and other links to point to Calypso instead of the old NUX, improving the user experience and likely earning us additional revenue.

**Comment by bisko** [comment]
Calypso supports domain searches with the same parameter - `new`. 

For example: `https://wordpress.com/start?new=myawesomedomain.com`. This will start Signup and pre-fill the domain search box with the provided domain. 

A small issue I see there is that it should be thought-out what the proper Signup flow should be to accommodate the `Register now and create a blog on WordPress.com`:
* If the registration happens outside of `WordPress.com` we will need to make some minor changes to directly pass the domain as a `mapped` domain. 
* If the domain registration will happen inside `WordPress.com` then no changes will be needed.

**Comment by lsinger** [comment]
@mattm can confirm that what @bisko describes works. Is this OK to close, or is there anything we'd need from the Calypso side of things?

**Comment by mattm** [comment]
We're all good here. 

I updated Lean Domain search accordingly so it points to the new NUX URL.

Thank you both for the responses!

**Comment by lsinger** [comment]
Great, thanks @mattm!
