### ISSUE TITLE
Custom headers for HTTP requests

### ISSUE THREAD

**Issue by mweichert** [Automattic/wp-calypso#10056]
Hi there,

We're looking into how to use the Calypso API to expose a UI for a popular WP plugin that doesn't do some of today's norms like use the media library or custom post types. Although we'd like to adjust the plugin to follow WP standards, at this time, we're trying to access how to use Calypso as a UI for the plugin as it is written now.

One way might be using the media library to add media, which will generate the appropriate REST API requests behind the scenes to the WP instance, and then intercept them so that the data isn't actually added to the media library, but using the data constructs that the plugin provides.

But to do that, we need the ability to identify which requests to intercept. Is it possible to add custom headers to the HTTP requests that Calypso generates? If not, that would be a great addition.

Thanks,
Mike.

**Comment by nylen** [comment]
Mocking HTTP calls doesn't sound like the right layer at which to achieve this.  For example, I'd rather see a hook into the media library that lets you add extra content or call a custom function instead of uploading media.

Can you give more details about what you're trying to do with the media library?

**Comment by designsimply** [comment]
Hi again, mweichert! I'm looping back to this to see if you'd like to share more info about which plugin you are working on and what you are trying to do with the media library?

**Comment by designsimply** [comment]
I found that this was regarding the NextGEN Gallery plugin. 

Closing for now with a note to re-open later if needed!
