### ISSUE TITLE
Framework: sidebar overlaps when loading admin pages after selecting a site (as opposed to opening directly)

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#1005]
This is similar to #900. When you load a site from wordpress.com/domains, the correct styling isn't applied so the sidebar can overlap the content when the browser window shrinks. 

Steps to reproduce:

1. Visit wordpress.com/domains

2. Select a site

3. You'll notice that the `domain-management-list` div is pushed to the left rather than being centered:

<img width="1280" alt="screen shot 2015-11-29 at 4 50 41 pm" src="https://cloud.githubusercontent.com/assets/7240478/11461060/5b549182-96b9-11e5-89ce-ed0e78c3c027.png">

If you shrink the browser, the content will overlap:

<img width="1011" alt="screen shot 2015-11-29 at 4 51 00 pm" src="https://cloud.githubusercontent.com/assets/7240478/11461062/6c4a1a70-96b9-11e5-959f-a915fa633f54.png">

The same formatting applies if you click on Posts or Pages on the sidebar. This does not happen if you load a specific domain page (like https://wordpress.com/domains/manage/example.com) directly presumably because it's loading the page with the sidebar in mind. 

h/t Martin in 2438474-t

**Comment by designsimply** [comment]
I noticed this happens for any admin page if you go through the "Please Select a Site" step first, inclugin:

https://wordpress.com/plans
https://wordpress.com/menus
https://wordpress.com/sharing
https://wordpress.com/people/team
https://wordpress.com/settings/general

**Comment by aduth** [comment]
Appears that this was fixed by #1029 (cc @mtias )

**Comment by mtias** [comment]
Yes, @jeremeylduvall could you please confirm?

**Comment by jeremeylduvall** [comment]
@mtias it is fixed, but the transition looks a bit jumpy because the sidebar is loaded first it seems with the site selector before the main content. Here's a GIF:

![gif](https://cloud.githubusercontent.com/assets/7240478/11479909/cd8eca0e-9751-11e5-8e19-03abfc400c74.gif)

Here's a screenshot of the temporary page with the sidebar loaded and the main page still on the site selector:

<img width="1279" alt="screen shot 2015-11-30 at 11 00 46 am" src="https://cloud.githubusercontent.com/assets/7240478/11479923/e452e018-9751-11e5-93b7-87c08ea34843.png">

Could this be cleaned up?

**Comment by mtias** [comment]
I believe this is how it's supposed to be, but paging @shaunandrews who added the transitions.

**Comment by shaunandrews** [comment]
The transition on the sidebar is intentional. There are no transitions between the screen's content as it changes—in this case the sites grid and domains—and I'm not sure that it'd be easy to add some. But, if we could, a simple fade in/out would probably help.

**Comment by mtias** [comment]
Ok, going to close this and we can open any refinements to the transitions separately.
