### ISSUE TITLE
Reader: Must hit Escape key more than once on Full Post view after expanding Notifications

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#10057]
#### Steps to reproduce
1. Visit the Reader
2. Expand to a Full Post View by clicking an article (or hitting enter while one is selected with keyboard shortcuts)
3. Open the Notifications dropdown by clicking on the icon (or hitting the `n` key)
4. Close the Notifications dropdown by clicking on the icon (or hitting the `esc` key, or clicking outside the dropdown)
5. Hit the `esc` key to try and exit the Full Post view

#### What I expected
To be returned to the list view

#### What happened instead
I have to hit `esc` an additional time to return to the list view

#### Browser / OS version
Chrome stable (55.0.2883.95 64-bit)

#dogfooding #manual-testing

**Comment by blowery** [comment]
Caused by #9301
