### ISSUE TITLE
Fullpost: Missing space under images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10054]
There's not enough space below images on the fullpost view. I think this is only for RSS feeds.

This:

![this](https://cloud.githubusercontent.com/assets/24388/21196299/013f5ace-c1ec-11e6-98be-ed3b39795324.png)

Should be this (~15px down):

![shouldbe](https://cloud.githubusercontent.com/assets/24388/21196304/04680976-c1ec-11e6-9217-ddc7ef46e714.png)

The idea is that there's the same amount of whitespace below the image as above it.

**Comment by blowery** [comment]
What's the URL tot that post?

**Comment by fraying** [comment]
@blowery https://wordpress.com/read/feeds/10080096/posts/1260487444

(Sorry)
