### ISSUE TITLE
Reader Discover: byline should show author of source post where available

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#10060]
On http://calypso.localhost:3000/discover:

> For card header, show the original poster info, not Discover poster. Use date stamp of discover post date, so they appear in order, and link date to the original external URL as usual. Include main tag (links to tag page as usual)

**Comment by fraying** [comment]
(This one's most important.)

Note also that, once we do this, we can unhide the follow link from the top right of the card and ellipsis menu.

**Comment by bluefuton** [comment]
> Note also that, once we do this, we can unhide the follow link from the top right of the card and ellipsis menu.

Cool. I've added that one in - #10066.

**Comment by bluefuton** [comment]
Closing this out in favour of #10169. We'll stick with the original byline, and add 'Follow site name' to the post card instead.
