### ISSUE TITLE
Reader Discover: All “Photo” posts get the Photo card layout and omit the title

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#10064]
On http://calypso.localhost:3000/discover, all “Photo” posts should get the Photo card layout and omit the title.

**Comment by samouri** [comment]
I'm confused as to what this is referring.
Is there a special kind of Photo card that we need to make for Discover?

**Comment by bluefuton** [comment]
@samouri some background here: https://github.com/Automattic/wp-calypso/issues/9096#issuecomment-261145352

Basically, if the Discover post format (from `discover_fp_post_formats`) is _photo_, then always show a photo card (regardless of what the post normalizer would normally classify the post as).

**Comment by jhnstn** [comment]
I just moved this over to the Expanded Discover Tab project
