### ISSUE TITLE
i18n: Placeholder for site selector headline is not translatable

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#10072]
#### Steps to reproduce
1. Switch your admin UI to Japanese
2. Go to https://wordpress.com/stats/insights on an account with multiple sites
3. "Stats Insight" is not translated, and the string doesn't exist on translate.wordpress.com

<img width="387" alt="site-selector" src="https://cloud.githubusercontent.com/assets/34067/21214689/bc426d04-c2df-11e6-8a96-48e48e0848cd.png">

(the problem also exists on https://wordpress.com/stats/domains)

Code: https://github.com/Automattic/wp-calypso/blob/8dc2e5b29fbfb27570d66bfee0ce3ab661cc807d/client/my-sites/sites/sites.jsx#L68

**Comment by lancewillett** [comment]
Related PR #10078 fixes this partially — needs author reply.
