### ISSUE TITLE
Jetpack Plugins: plugin search results load indefinitely on refresh

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#10074]
#### Steps to reproduce
1. Starting at URL:  https://wordpress.com/plugins/browse/examplejetpacksite.com?s=Automattic
2. Type in search - make sure search results shown
3. Refresh browser or revisit page

#### What I expected

Search results shown

#### What happened instead

Results don't load - shows pending indefinitely

#### Browser / OS version

Chrome OSX latest

#### Screenshot / Video

![plugin browser](https://cloud.githubusercontent.com/assets/128826/21215376/89b75554-c2ec-11e6-872a-d4c1a1e7c843.gif)

**Comment by lancewillett** [comment]
I can repeat the nothing loading after a page refresh — but I'm not certain it's worth addressing. I noticed the workaround in the e2e is to clear the search and try again, which works in manual testing as well. That's likely what someone would do if they encountered the blank results.

Closing as works-for-me; feel free to re-open if you think it needs a fix.
