### ISSUE TITLE
Me: About Me should not escape an ampersand

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1008]
Related to #977

An ampersand in Me > My Profile > About Me shouldn't be escaped, at https://wordpress.com/me :

![3ca5da38-36e3-11e5-80b8-243c4ccc79ed](https://cloud.githubusercontent.com/assets/11487924/11462027/0bbb5aa2-96dc-11e5-93c0-be90ab353a8b.png)

The same issue happens with Gravatar at http://en.gravatar.com/profiles/edit/#about-you :

![97024e08-36e3-11e5-989b-6a767e5a9390](https://cloud.githubusercontent.com/assets/11487924/11462029/154934ae-96dc-11e5-8019-f90b362a7b62.png)

However, the ampersand appears as expected in WP Admin > Users > My Profile at https://example.wordpress.com/wp-admin/users.php?page=grofiles-editor :

![7037309a-36e3-11e5-93db-53b7a8f40daf](https://cloud.githubusercontent.com/assets/11487924/11462037/3c19e038-96dc-11e5-9d90-71cf4723c58e.png)

**Comment by ebinnion** [comment]
This should be handled in #841.
