### ISSUE TITLE
Jetpack Connect: Help button positioning needs work

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#10088]
I noticed this earlier today while testing.

![screen shot 2016-12-15 at 11 33 32 am](https://cloud.githubusercontent.com/assets/1126811/21234980/7b48cbb0-c2ba-11e6-8f9e-5211df50b46a.png)

Note, how the help button is not centered properly. I'm not sure if we should remove this button or if we need to give it some custom styles so it's positioned better.

To repro:

- Go to `/jetpack/connect/authorize` without the necessary get properties

**Comment by rickybanister** [comment]
It appears that help button is left-aligned, similar to situations when there are more than one footer button.

Instead we should position it more like the 'back' button in the Jetpack Connect flow (which is centered)

cc @johnHackworth @tyxla

**Comment by tyxla** [comment]
Thanks for reporting this, @ebinnion 🙇
