### ISSUE TITLE
Reader: square gallery images look distorted in Reader full post view

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#10091]
Steps to reproduce:

1. Create an publish a new post including a gallery of images set to use the "Square Tiles" layout.
1. Find the site in the Reader (you can tap the ellipsis in the bottom-right menu and then click on the "View Site in the Reader" link).
1. Click on the post title so that you are viewing the full post in the Reader.
1. Check to see whether the images look normal or squished.

<strong>Result:</strong> images from a square gallery look distorted in the Reader full post view.

<img width="1280" alt="screen shot 2016-12-15 at thu dec 15 11 45 57 am" src="https://cloud.githubusercontent.com/assets/1119271/21237992/7836daa8-c2be-11e6-87d5-40d9377bcd9c.png">
<sup>Seen at https://wordpress.com/read/feeds/42873943/posts/1262017714 using Firefox 50.0.2 on Mac OS X 10.12</sup>

/hat tip pellymade for the report at https://en.forums.wordpress.com/topic/new-reader-look?replies=4#post-2816708

**Comment by blowery** [comment]
Likely related to the content_width we're now passing down when rendering content server-side. Need to investigate using the responsive js that the actual tiled galleries use.

**Comment by designsimply** [comment]
Oops, circle galleries are affected too:

Reader full post view: 

<img width="1280" alt="screen shot 2016-12-15 at thu dec 15 1 10 08 pm" src="https://cloud.githubusercontent.com/assets/1119271/21240374/4940766e-c2c8-11e6-8d9f-06c997a27fd6.png">
<sup>Seen at https://wordpress.com/read/feeds/42873943/posts/1262048733 using Firefox 50.0.2 on Mac OS X 10.12</sup>

Direct post view:

<img width="1280" alt="screen shot 2016-12-15 at thu dec 15 1 12 53 pm" src="https://cloud.githubusercontent.com/assets/1119271/21240412/6a0b2092-c2c8-11e6-964f-2adef11f3e4d.png">
<sup>Seen at https://design5279.wordpress.com/2016/12/16/circle-gallery-test/ using Firefox 50.0.2 on Mac OS X 10.12</sup>
