### ISSUE TITLE
Site View: Clicking whitespace around Site Title links to site

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10092]
For example: https://wordpress.com/read/feeds/10080096

Clicking in the whitespace right below the "BACK" link sends you to the site. This shouldn't be happening - too much potential for accidental clicks. Only the text itself should be linked.

(In Safari)

**Comment by jancavan** [comment]
Tried to fix this, but it's more complicated than I thought. 

We're currently using the `Site` component. My initial fix was to make `<a class="site__content">` only take up the container that it needs, but this only works if the Site Titles are short:

![screenshot 2016-12-15 14 29 49](https://cloud.githubusercontent.com/assets/4924246/21244815/29028160-c2d4-11e6-9fee-bc0b2f172a29.png)

But if they're long, this makes `<a>` expand again and create a lot of clickable whitespace around the Site Icon.
![screenshot 2016-12-15 14 30 57](https://cloud.githubusercontent.com/assets/4924246/21244850/5102b892-c2d4-11e6-87fb-35cbf333f593.png)

As discussed in Slack, this would probably need to be re-implemented. /cc @blowery @bluefuton

**Comment by fraying** [comment]
Bummer.

How big of a project is re-implementing this?

**Comment by jancavan** [comment]
Not sure, @blowery ? I've added this card to the "Needs Evaluation" column for now.

**Comment by samouri** [comment]
Fixing this here: https://github.com/Automattic/wp-calypso/pull/14138
