### ISSUE TITLE
Reader Post-Refresh: Clean up the excerpts in rule-create-better-excerpts

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#10109]
We are no longer using any of the excerpts with `_no_html_` except for in search-cards which we need to delete anyway.

This issue can be closed when we've cleaned up the rule.

Started from: https://github.com/Automattic/wp-calypso/pull/10080

**Comment by samouri** [comment]
Note from @blowery: we probably still use excerpts for character counts in `classifyPost`

**Comment by hoverduck** [comment]
Is this issue the reason that the [Refresh Cards](https://wpcalypso.wordpress.com/devdocs/blocks/refresh-cards) on DevDocs are no longer showing the body of the post?

![screen shot 2016-12-16 at 9 55 50 am](https://cloud.githubusercontent.com/assets/7233112/21266859/dc50320c-c375-11e6-84e6-1da7fa129c4d.png)

(The placekitten.com images are failing to load in that screenshot, but that's unrelated)
