### ISSUE TITLE
FollowButton shows extra padding at mobile width as a Block vs Component

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#10125]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks
2. Resize browser to mobile width and observe the right-padding on the buttons

#### What I expected
The icon to be centered

#### What happened instead
There's extra padding on the right side of the button:

![screen shot 2016-12-16 at 10 14 01 am](https://cloud.githubusercontent.com/assets/7233112/21267461/66b59b24-c378-11e6-95a7-f386ab340055.png)

I believe this is due to PR #9836 moving the code from Components to Blocks...specifically due to the re-ordering of the component imports causing the CSS for the Button component to take precedence over the FollowButton, so [this rule](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/follow-button/style.scss#L19) isn't taking effect:

![screen shot 2016-12-16 at 10 07 55 am](https://cloud.githubusercontent.com/assets/7233112/21267362/f4a268b4-c377-11e6-832f-7d3f288dc13c.png)

cc: @bluefuton 

#### Browser / OS version
Seen here in OSX Firefox

#### Context / Source
#automated-testing

**Comment by bluefuton** [comment]
Nice spot @hoverduck! I'll investigate.
