### ISSUE TITLE
`article_opened` Tracks event property `ui_algo` is for current page, not previous

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#10136]
### Background:
When a post is opened, the `calypso_reader_article_opened` Tracks event is fired. The event property `ui_algo` specifies what page this event occurred.

### Problem:
All `calypso_reader_article_opened` events have the `ui_algo=single_post`.

### Expectation:
When a post is opened, the `calypso_reader_article_opened` should have the event property `ui_algo` of the page where the article is opened. 

Example: If a search stream is loaded and an article is opened, then we expect the event `calypso_reader_article_opened` to have the event property `ui_algo=search`.

**Comment by blowery** [comment]
That sounds like we may need a new event, `calypso_reader_article_opening`, which is fired as part of the event that initiates the open. `calypso_reader_article_opened` doesn't have the context to know how it was opened. 

We could also try to find a way to pass the opener source through to full post, but that gets complicated given how we route.

What are you trying to capture? Could you derive that data a different way?

**Comment by aaronyan** [comment]
>What are you trying to capture?
Trying to differentiate where like, comment, and follow are being performed. For example, measuring what percent of follow stream views generate a like vs percent of full post views generate a like.

>Could you derive that data a different way?
I think we could use train tracks and algorithms to figure out where these actions are performed.  Having a `calypso_reader_article_opening` event would be quite nice for future funnels.
