### ISSUE TITLE
Themes: Fix Premium Squared

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#10135]
As discussed on Slack with @mendezcode and @davidakennedy, we need to fix Premium Squared. 
We'll need to do this [here](https://github.com/Automattic/wp-calypso/blob/2e749139b3932b2d3a1f4ba07cc3931d842b5708/client/my-sites/themes/themes-selection.jsx#L144-L153) by adding another check that sees if the user's current plan is the premium plan, and if the theme's author is either Automattic or Woo.

(We should also make those lines into a selector of its own, something like `isPremiumThemeAvailable` or so, since it's also used elsewhere, most notably in `theme-options`.)

**Comment by mendezcode** [comment]
It's worth mentioning that Calypso determines if a theme can be activated on a given site, if the following conditions are met:

1) The theme has been purchased
2) The site has the `UNLIMITED_PREMIUM_THEMES` bundle (e.g. Business)

This can be seen in the code @ockham pointed [above](https://github.com/Automattic/wp-calypso/blob/2e749139b3932b2d3a1f4ba07cc3931d842b5708/client/my-sites/themes/themes-selection.jsx#L144-L153).

With the introduction of Premium Squared (Woo/A8C themes in the Premium Plan), this needs to change and these themes must be able to be activated. I like the `isPremiumThemeAvailable` selector.

Also have in mind that we had an experiment going on before,  I have seen some sites (can't get them off the top of my head) that have something like "All themes in Premium Plan", that needs to be  addressed too.

**Comment by ockham** [comment]
Closed by #11112
