### ISSUE TITLE
Reader: Pages don't load in lower version of Safari

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#10134]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com
2. Visit Reader

#### What I expected
For pages in Reader to at least load even in older browsers like Safari 7

#### What happened instead
Stuck at preloading state

#### Browser / OS version
Safari 7.0 / OS X 10.9

#### Screenshot / Video
![screen shot 2016-12-16 at 3 13 59 pm](https://cloud.githubusercontent.com/assets/4924246/21281569/cd9b4e7c-c3a2-11e6-8c48-945e28232804.png)

![screen shot 2016-12-16 at 3 14 05 pm](https://cloud.githubusercontent.com/assets/4924246/21281570/cd9e513a-c3a2-11e6-81e8-c5e5ca7c6393.png)

The above screenshots are just of the Following and Search pages, but this actually happens to every single page in Reader.

/cc @blowery

**Comment by bluefuton** [comment]
Safari 7 isn't officially supported, as per:

> We support the latest two versions of all major browsers, except IE, where we currently only support 11 and Edge. 

...but I would expect to either be told the browser isn't supported, or for the basic functionality to work, as you suggested.

**Comment by blowery** [comment]
Tried this out in Browserstack and it worked alright in Safari 7.1 and Safari 6. Hrm.
