### ISSUE TITLE
Me/Security: confirmation should be required when changing the account recovery email address

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#10146]
#### Steps to reproduce
1. Start at URL: https://wordpress.com/me/security/checkup
2. Enter any email address (even one that does not exist)

#### What I expected
I expected to receive a confirmation email in case I had entered the address incorrectly.

#### What happened instead
"Successfully updated recovery email address."

#### Browser / OS version
Chrome and Desktop app in Mac

#### Screenshot / Video
https://cloudup.com/c2aM99uSKRF

#### Context / Source
https://twitter.com/user/status/810298957356093440

**Comment by lancewillett** [comment]
@supernovia I couldn't repeat this one.

I followed the same steps, and was prompted to confirm the new email address.

> Please verify your recovery email address. Check your inbox for a confirmation link.

<img width="1113" alt="screen shot 2017-01-16 at 15 21 57" src="https://cloud.githubusercontent.com/assets/66797/22001016/b65bda2c-dbff-11e6-8256-8941f0c311f6.png">

<img width="717" alt="screen shot 2017-01-16 at 15 22 10" src="https://cloud.githubusercontent.com/assets/66797/22001018/b8fa6b40-dbff-11e6-986a-8a1794fd097e.png">

<img width="1101" alt="screen shot 2017-01-16 at 15 22 14" src="https://cloud.githubusercontent.com/assets/66797/22001019/bb840696-dbff-11e6-9a6b-57030f68b7db.png">

If I try a nonsense email, I also get the warning in my site owner email inbox:

> We noticed a recent change to the account settings for your WordPress.com account, ____
> The recovery email address on file was changed to ____.
> If you did not request this change, please respond to this email immediately.

I think this process is working as expected.

Did you find something different in testing it out?

**Comment by supernovia** [comment]
Does the new address get a confirmation email?

**Comment by lancewillett** [comment]
> Does the new address get a confirmation email?

Yes. In my testing I got the new address confirmation when I used an email I control. When I used a nonsense email, well — that's obviously not coming to me. :)
