### ISSUE TITLE
Inter-Registrant Transfer: make "Transfer Domain" button clickable immediately

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/wp-calypso#10158]
When visiting the "Transfer Domain To Another User" page, the "Transfer Domain" button is unclickable until the page is refreshed.

#### Steps to reproduce
1. Starting from WordPress.com or stats/insights, navigate to the "Transfer Domain To Another User" page. (My Site > Domains > (domain) > Transfer Domain > Transfer to another user).
2. Try to click on the "Transfer Domain" button.

#### What I expected
Clicking the "Transfer Domain" button should bring up the "Confirm Transfer" box.

#### What happened instead
Instead, nothing happens, as the button isn't clickable.
The button is light blue instead of the normal blue (looks greyed out), and doesn't animate or initiate an action when clicked.

#### Browser / OS version
Chrome (55.0.2883.95), iOS 10.12.2. Also confirmed with Chrome on Windows 10 and Firefox (49.0.2) and Safari (10.0.2) on iOS 10.12.2.
If the page has been viewed recently, the button is clickable.
If not (or after clearing cache), button isn't clickable.

Viewing Inspect element in this state reveals
`.button.is-primary[disabled], .editor-drawer-well__placeholder[disabled] .is-primary.editor-drawer-well__button, .button.is-primary:disabled`

#### Screenshot / Video
<img width="751" alt="screen shot 2016-12-19 at 2 36 46 pm" src="https://cloud.githubusercontent.com/assets/15107387/21315808/28a84b14-c5fe-11e6-8f71-45b7f15fecf9.png">

Refreshing the page makes the button clickable again.

#### Context / Source
We've had two users complain they can't click on this button, so I looked on a test site and saw the same. 2962155-t and 2962112-t 

#user-report

Related to the new Inter-Registrant Transfer: https://github.com/Automattic/wp-calypso/pull/9863

**Comment by kriskarkoski** [comment]
Another case of this in 564301-chat, moved to 2977095-t
