### ISSUE TITLE
Reader Refresh: recommended posts allow pictures 200+px wide

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#10166]
As discussed with ∇ { @fraying,  @gibrown }: wp-calypso and elasticsearch have different width requirements for featured-images in Recommended Posts.

Client: 350px wide and area 30000px [source](https://github.com/Automattic/wp-calypso/blob/8ecc3d6f885638b42fc99c9b163331da340cc1a7/client/lib/post-normalizer/utils.js#L148)
ES: 200px wide

**Comment by fraying** [comment]
I think the status is: Currently the backend says a post has an image if it's over 200px, but the frontend won't display it unless it's over 350px. As a result, we're showing some recs without images. Let's change the frontend to match the backend. Make sense?

**Comment by samouri** [comment]
@fraying nailed it

**Comment by samouri** [comment]
@blowery @bluefuton: do you know of an easy way to accomplish this? 
This needs to be done at post-normalization time and I'm not sure if there is a way to differentiate rp from regular posts.

The only idea I had was to do a check in the feed-post-store for if it is an relatedposts store and then pass an extra param to `normalizePost`.  I don't like this solution though
