### ISSUE TITLE
Domains: Display a subdomain-specific success message after mapping a subdomain

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#10162]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains
2. Add a new subdomain of a domain you own, to map it to the site
3. Finish the checkout process to purchase the domain mapping
4. Look closely at the success message after finishing the purchase

#### What I expected

I expected a message specific to mapping a subdomain, such as this:

```
Finish setting up your subdomain
The subdomain [subdomain].[rootdomain].com still has to be configured to work with WordPress.com.
You will need to log into your registrar's site and add the following CNAME record:
[subdomain].[rootdomain].com. IN CNAME [mysite].wordpress.com.
Once you make the change, just wait a few hours and the domain should start loading your site automatically.
```

Ideally, we could also detect if the domain was already mapped to WordPress.com, in which case no DNS changes need to be made.

The Learn More button could link to this support doc:

https://en.support.wordpress.com/map-subdomain/

#### What happened instead

The message is written for mapping a root domain, instead of a subdomain:

```
Finish setting up your domain
The domain [subdomain].[rootdomain].com still has to be configured to work with WordPress.com.
You will need to log into your registrar's site and change the "Name Servers" to:
ns1.wordpress.com
ns2.wordpress.com
ns3.wordpress.com
Once you make the change, just wait a few hours and the domain should start loading your site automatically.
```

The "Learn More" button then links to this support doc:

https://en.support.wordpress.com/map-existing-domain/

#### Browser / OS version

Tested on Mac OSX 10.12.2, WP Desktop app version 2.1.0-beta2 and Chrome 55.0.2883.95

#### Screenshot / Video

![screen shot 2016-12-11 at 11 21 57 am](https://cloud.githubusercontent.com/assets/8658164/21324046/0434f4d4-c618-11e6-81e2-0c21819dee7f.png)

#### Context / Source
#dogfooding
Also related: https://github.com/Automattic/wp-calypso/issues/8997

**Comment by umurkontaci** [comment]
I think this was partially handled by #10208. I know it's not the ideal message as we don't detect the current NS records, I think it's too much effort for a little gain.

Closing this, but feel free to reopen if I'm missing something.

**Comment by rachelmcr** [comment]
The issue I saw was separate from the one handled by #10208. I'm not concerned about detecting the current records on the domain. Rather, I'm concerned that we give instructions for mapping a root domain instead of mapping a subdomain.

If someone is mapping a subdomain (not a root domain), would it be reasonable to give general instructions for mapping a subdomain instead of mapping a root domain (i.e. instructions to add a CNAME record instead of changing name servers)? We could do this regardless of the current NS records and it would still be more accurate/less confusing for this case.
