### ISSUE TITLE
Media: add link to clear selected items

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1016]
Raised by @nylen 

It would be nice to have a link to clear selected media items.  For example, this would help a lot with usability in the following case:
- Upload a bunch of media items from the modal (this is pretty common for me because I have lots of pictures that are not very well-organized)
- Do (???) to clear the selection (currently a bit difficult)
- Select 3 or 4 media items to insert into a gallery.

I don't know how to use any of the design prototyping tools so I spent a few minutes coding up a non-functional prototype and pushed the results to a `try/media/clear-selection` branch [in calypso-pre-oss] as a starting point.  Here's what that looks like:

<img width="962" alt="media library clear selected" src="https://cloud.githubusercontent.com/assets/227022/9529232/bd03782a-4cbe-11e5-81f2-90dfd2697deb.png">

There are at least a couple more things to think through here:
- Design for mobile?
- What should happen if there are selected media items that are hidden by the current search or filter?

**Comment by brbrr** [comment]
Will close this due to inactivity.
