### ISSUE TITLE
Media: detailed view with more than one item is not clear it works as a slideshow

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1017]
Raised by @mtias 

I selected a couple items and clicked "view", I was confused to see the first item, and it took me a bit to remember I could browse them as a slideshow.

![image](https://cloud.githubusercontent.com/assets/548849/9580696/3590ab0c-4ffb-11e5-909e-e9790a94a9aa.png)

Wonder if we can try some things:

1) Add a count if you have more than one item selected.
![image](https://cloud.githubusercontent.com/assets/548849/9580747/8a38e6ce-4ffb-11e5-8514-192299935b43.png)

Ideally with this style treatment:

![image](https://cloud.githubusercontent.com/assets/548849/9580778/c216a6d0-4ffb-11e5-9e86-b56f6bf45a5b.png)

2) Add a `viewing 1 of 2` to the right in:

![image](https://cloud.githubusercontent.com/assets/548849/9580776/b7967118-4ffb-11e5-9748-a54b62b6d8b0.png)

3) Default to the last selected item when you click view.

cc @kellychoffman @aduth 

Notes from @aduth 

> @kellychoffman, what are your thoughts here? Related to #1016, I've wanted some selected item count indicator. The change to "View" (now "Edit") here seems nice, but the choice between showing it on "Edit", "Delete", or separately seems like a non-obvious one to make. Also, where would we fit the "Viewing 1 of 2" suggestion noted in the original message?

Notes from @kellychoffman 

> I had originally designed this UI in mobile galleries:
> 
> ![gallery-flow1](https://cloud.githubusercontent.com/assets/5835847/10076414/0c43e38c-62a1-11e5-9909-1c85c6cd2d96.gif)
> 
> I took a step back to see how it could apply in both galleries and non on both large and small screens for both the edit and initial gallery views.
> 
> Gallery view:
> 
> ![screen shot 2015-09-24 at 9 37 35 am](https://cloud.githubusercontent.com/assets/5835847/10077376/ae0c507e-62a5-11e5-930c-a9e3d1003747.png)
> 
> Edit view:
> 
> ![screen shot 2015-09-24 at 9 37 23 am](https://cloud.githubusercontent.com/assets/5835847/10077377/ae0eb620-62a5-11e5-82e8-68285770524b.png)

**Comment by designsimply** [comment]
It may not fit with the new modal design, but I have always really loved the previous/next navigation at the top right of the WP Admin media library browser because it's easy to spot and always in the same location on the screen.

![screen shot 2015-11-30 at 00 36 52](https://cloud.githubusercontent.com/assets/1119271/11464243/b1cfebba-96fa-11e5-8c2f-fcf2043e9fea.png)

**Comment by brbrr** [comment]
The design is changed, so this is not relevant anymore.
