### ISSUE TITLE
Unable to map .co and .biz subdomains

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#10176]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/yourdomain.com
2. Add any .co or .biz subdomain, for example. m.testing.co

#### What I expected

It should've shown me a message that you can 'map it', similar to the one that's shown for other TLDs that we can register, like .com. Screenshot:

![subdomain-cant-add](https://cloud.githubusercontent.com/assets/6505293/21349724/53e1ba54-c6d5-11e6-9caa-44b69dc38160.jpg)

Even if it doesn't show the message above, the "map" option at the end of suggestions should allow me to map it.

#### What happened instead

Got this message:
![subdomain-cant-add2](https://cloud.githubusercontent.com/assets/6505293/21349763/7c5dbdca-c6d5-11e6-85cc-2f1189c6e547.jpg)

Clicking "Already own a domain?" at the end of suggestions isn't ideal, but still should allow me to map it.

But, going that route leads to another error:

![subdomain-cant-add3](https://cloud.githubusercontent.com/assets/6505293/21349795/b16526fc-c6d5-11e6-9361-b5c403603328.jpg)

#### Browser / OS version
Chrome 55, W10

#### Context / Source
 #manual-testing
Not possible to add any subdomain of a registered .co or .biz domain. I tested other TLDs that we offer but others seemed fine.

There's an open issue #8997 that talks about improving messaging when adding a subdomain, but that's not directly related to this.

**Comment by klimeryk** [comment]
Fixed in `D3817-code` 🎉

**Comment by ehti** [comment]
Thanks!! 💃
