### ISSUE TITLE
Plans: translate name for "Free" plan in sidebar menu context

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#10187]
#### Steps to reproduce
1. Starting at URL: wordpress.com/me/account
2. Change your user account setting to non-English (US) language
3. Go to My Sites, find a site with a free plan
4. View sidebar under "Plan" (first link under Stats)

#### What I expected
For "Free" label to be translated to the language in my account settings (I tested with Spanish and French).

#### What happened instead
Free is still in English.

#### Code context

https://github.com/Automattic/wp-calypso/blob/1ea1c3e6c578cd3e0e1f15695820693351cb5387/client/my-sites/sidebar/sidebar.jsx#L369 — I'm pretty sure we don't translate things like "Business" and "Premium" as they are brand names, but "Free" should be translated, in my opinion.

#### Screenshot / Video
<img width="387" alt="screen shot 2016-12-20 at 12 01 30" src="https://cloud.githubusercontent.com/assets/66797/21363986/29eccb22-c6ac-11e6-8990-7a1ee2adafc2.png">

#### Context / Source
Found via #dogfooding #manual-testing

**Comment by rodrigoi** [comment]
@lancewillett is this issue still current?

**Comment by lancewillett** [comment]
I re-tested just now with a Spanish language user setting — it looks fixed! Yay.

![screen shot 2017-08-30 at 08 58 24](https://user-images.githubusercontent.com/66797/29882319-811c9838-8d61-11e7-9765-98f231909a70.png)
