### ISSUE TITLE
Editor: design UX for local and remote autosaves

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1018]
Raised by gcorne in Jul

Now that we have started storing autosaves, we need to design the UX. To set the stage, an autosave is separate version of the post stored as a special type of revision. The primary use case is to make sure that edits to a published post don't get lost if the user accidentally forgets to publish them or closes there browser window. The local autosaves are needed for cases where a user loses their internet connection.
1. What should happen when the user loads a post that has an autosave that was modified after the post?

In WP Admin, a notice is used:
![image](https://cloud.githubusercontent.com/assets/266036/8696674/a3332482-2aee-11e5-9f65-61a2e2f14828.png)

My first thought is that a modal might be better as it makes sure that the user knows that there is an autosave. Another idea is to just load the autosave and then add some sort of UI element that makes it easy for the user to revert to the saved version.
1. How do we indicate to the user that the autosave has happened and when the last autosave occurred?

One quirk of autosaves is that as currently implemented only the content and the title are autosaved. This matches up with how core works, but I am open to perhaps changing it slightly to store the other data as serialized data in post meta that hangs off the autosave. This would be backwards compatible with how core works, but would open the door to storing the other data. There also is a core issue around modifying how revisions work to support post meta, which would also help a little.

WP Admin shows the autosave status in a bar at the bottom of the editor:

![image](https://cloud.githubusercontent.com/assets/266036/8696813/228b1fea-2af0-11e5-815e-7f39429148e5.png)
1. Should the autosave somehow be indicated in the list view?

WP Admin does do anything in this case. I think that there is an opportunity here, especially for local drafts, which might become more important as we start to think about making offline a priority, especially for the desktop app.

cc @mtias @kellychoffman @folletto 

Note from @designsimply

> Remote autosaves were added in Sep:
> 
> ![screen shot 2015-11-29 at 13 44 39](https://cloud.githubusercontent.com/assets/1119271/11459207/5b1edd90-969f-11e5-9cfb-e466cd9ee7a2.png)
> <sup>Seen at https://wordpress.com/post/watchingstormsrollby.me/4947</sup>

Note from @codebykat 

> There is no local autosave yet and we should add one.

**Comment by folletto** [comment]
> There is no local autosave yet and we should add one.

I'd note that, depending on effort and priority, this bit could be part of the work to make Calypso work offline as a whole. :)

**Comment by designsimply** [comment]
I am going to close this issue in favor of #542 and note that the questions here are still valid for the next time the revisions feature is reviewed.
