### ISSUE TITLE
Gallery Card repeating first image

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10184]
This post ... https://wordpress.com/read/feeds/34575/posts/1267951350 ... when viewed in Reader shows the first image twice.

![screen shot 2016-12-20 at 10 06 15 am](https://cloud.githubusercontent.com/assets/24388/21362174/18052e82-c69c-11e6-95d9-8248b8b76fbf.png)

**Comment by samouri** [comment]
both have the same src url so this should be easy to fix.  we just need to apply the same dedupe logic as full-post (`canonical_in_content`)

**Comment by fraying** [comment]
This is a good site to see Gallery cards with double images: https://wordpress.com/read/feeds/6705117

![screen shot 2016-12-23 at 9 19 31 am](https://cloud.githubusercontent.com/assets/24388/21459185/f42d3c1e-c8f0-11e6-8a44-c2af42fa332e.png)
