### ISSUE TITLE
Site showing Default cards instead of Photo cards

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10189]
This site is showing Default cards when they should be Photo cards: https://wordpress.com/read/blogs/24969815

![screen shot 2016-12-20 at 11 58 48 am](https://cloud.githubusercontent.com/assets/24388/21365778/b2b485a4-c6ab-11e6-8e52-5bcf93571573.png)

**Comment by bluefuton** [comment]
@fraying unfortunately the images are really small, and don't meet the minimum width requirement for photo cards (480px). For example:

https://sanslartigue.files.wordpress.com/2016/02/img_0393b.jpg?w=460&h=345

...is just shy of the minimum (460 × 345 pixels).

**Comment by fraying** [comment]
Actually, the images are huge, they're just sized in the URL:

https://sanslartigue.files.wordpress.com/2016/02/img_0393b.jpg

Can we ignore that URL sizing and use the actual image dimensions?

**Comment by bluefuton** [comment]
Yep, we receive them in the feed content with those resize dimensions:

https://sanslartigue.wordpress.com/feed/

We could potentially add a rule in post normalizer to strip those off for known Photon images, though 👍

**Comment by fraying** [comment]
@bluefuton Would that ("add a rule in post normalizer to strip those off for known Photon images") fix this particular site?

**Comment by bluefuton** [comment]
> Would that ("add a rule in post normalizer to strip those off for known Photon images") fix this particular site?

Yes! Not a trivial fix, though.

**Comment by fraying** [comment]
Estimate?

**Comment by bluefuton** [comment]
A day or so to build and test. We'd need to:
- identify images we know were generated by Photon
- choose a maximum image size to try and fetch
- manipulate the query string to grab the image with those larger dimensions

**Comment by fraying** [comment]
@bluefuton Gotcha. Thank you!

So, should we close this issue and open another about that ^ ? I'd want to understand if there'd be any other follow-on effects.

**Comment by jancavan** [comment]
This one is also being displayed as a default card instead of a photo card:
https://wordpress.com/read/blogs/45243654

![screenshot 2016-12-27 10 59 52](https://cloud.githubusercontent.com/assets/4924246/21506268/a3581f4e-cc23-11e6-84c6-0ee51089f9d4.png)

**Comment by samouri** [comment]
As I wrote in #10283, I believe this was introduced as a byproduct of https://github.com/Automattic/wp-calypso/pull/10096

**Comment by bluefuton** [comment]
Looks like #10310 took care of this.

Photo cards all the way in https://wordpress.com/read/blogs/24969815 now:

<img width="837" alt="screen shot 2017-01-10 at 17 04 41" src="https://cloud.githubusercontent.com/assets/17325/21800081/f404b7ca-d756-11e6-85fe-594c5afaed93.png">

And now gallery view for the post @jancavan highlighted above in https://wordpress.com/read/blogs/45243654:

<img width="890" alt="screen shot 2017-01-10 at 17 05 40" src="https://cloud.githubusercontent.com/assets/17325/21800101/08aa8f42-d757-11e6-98fe-5f498364e9b7.png">
