### ISSUE TITLE
Site Picker loading placeholder mis-styled

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#10197]
When you hit a URL that requires a site for context, you're prompted to pick a site before continuing. If your site list isn't loaded yet (e.g. cleared browser cache), then you'll see some loading placeholders. The one in the search box is weird/mis-styled.

#### Steps to reproduce
1. Starting at URL: In Incognito, or anywhere with a cleared cache, try to go directly to something like [stats](https://wordpress.com/stats/insights/)
2. You will land on a page asking you to select a site
3. Observe the loading state (especially notable if you have a lot of sites, which takes longer to load)

#### What I expected
I expected the loading state, especially for the Search box at the top, to not have weird shading :)

#### What happened instead
It had weird shading

#### Browser / OS version
Chrome/MacOS

#### Screenshot / Video
![screen shot 2016-12-20 at 6 26 09 pm](https://cloud.githubusercontent.com/assets/108942/21374297/fa8049fe-c6e2-11e6-849b-f607b2aa19b1.png)

**Comment by lancewillett** [comment]
This is most likely a minor, janitorial style design fix for anyone who wants to grab it.
