### ISSUE TITLE
Editor: generate auto-draft when starting a new draft

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1019]
Raised by @gcorne 

In order to have a post ID that we can use for attachments and other purposes as soon as possible, we should create an auto-draft and update the `post-edit-store` when starting a new draft.

**Comment by designsimply** [comment]
Would this allow us to generate a shortlink pre-publish?

**Comment by supernovia** [comment]
We've got a request for a pre-publish shortlink:
http://en.forums.wordpress.com/topic/adding-shortlink-on-new-wordpress-platform

Preferably one that would redirect even if the user updates the slug, if that's possible (like if these work on postID)

**Comment by designsimply** [comment]
We now create a post ID as soon as a new post is saved, however, a shortlink is not exposed right away like it is in wp-admin. Images do appear to be attached correctly though.

Video: [1m15s](https://cloudup.com/ctBdZQJFqXJ)
<sup>Tested with Firefox 58.0.1 on macOS 10.13.3.</sup>

Moved the shortlink request to https://github.com/Automattic/wp-calypso/issues/22367
