### ISSUE TITLE
Notifications: Time headings do not use existing translations

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#102]
Timestamps/time headings in notifications remain in English even if the account is set to a language other than English, and corresponding translations exist in GlotPress. Expected: use and show corresponding translations for timestamps.

Example for Russian ("[Today](https://translate.wordpress.com/projects/wpcom/ru/default?filters[status]=either&filters[original_id]=1128&filters[translation_id]=147289)" and "[Yesterday](https://translate.wordpress.com/projects/wpcom/ru/default?filters[status]=either&filters[original_id]=1129&filters[translation_id]=147290)" are translated in GlotPress):

<img src="https://cloud.githubusercontent.com/assets/8658164/11246841/5fa4e0d0-8e11-11e5-9e26-a0ded67a7339.png" width="50%" />

Example for German ("<a href="https://translate.wordpress.com/projects/wpcom/de/default?filters[status]=either&filters[original_id]=147845&filters[translation_id]=4206754">Older than a month</a>" is translated in GlotPress):

<img src="https://cloud.githubusercontent.com/assets/8658164/11246537/fa4dc964-8e0f-11e5-98fb-60d62a99eb87.png" width="50%" />

**Comment by akirk** [comment]
Fix will be deployed on WordPress.com soon.

**Comment by jenial** [comment]
:+1:

**Comment by jenial** [comment]
@akirk: checked today, still seeing the timestamps in English.

**Comment by akirk** [comment]
I pinged @dmsnell yesterday, he is still on his way back from WCUS, he will deploy it after that.

**Comment by lancewillett** [comment]
This looks fixed, testing with https://wordpress.com/ and test user `testerlance` with ES interface language.

<img width="399" alt="screen shot 2016-03-11 at 15 21 45" src="https://cloud.githubusercontent.com/assets/66797/13717167/faacc7d4-e79c-11e5-8b86-4f43c6a247e7.png">
