### ISSUE TITLE
Photo Cards: Set a max width and center

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10219]
Idea: Set a max width for the photos in Photo Cards of 600px. So that, when the browser is narrow, they behave as they do now, flexibly taking up as much space as they have in the column. But, when the photo hits 600px wide, it stops, and instead centers in the card.

So, for example, a photo card in a narrow browser looks the same as now.

![600](https://cloud.githubusercontent.com/assets/24388/21413702/207111a4-c7ae-11e6-82c8-bb90ba35c686.png)

But when the browser gets wider, the photo stops at 600px and centers.

![over600](https://cloud.githubusercontent.com/assets/24388/21413714/2d45ab10-c7ae-11e6-9ae1-f7905fdbbfd9.png)

Why do this? Because the wider the photo gets, the more extreme the crop is. By keeping the photos from getting too wide, we're avoiding some of the more contentious cropping.

Thoughts?

**Comment by samouri** [comment]
@fraying I think that this issue is at odds with https://github.com/Automattic/wp-calypso/pull/10503

I would vote we close this and follow through with 10503

**Comment by fraying** [comment]
@samouri Agreed!
