### ISSUE TITLE
Editor: add keyboard shortcut that triggers save (meta+s/ctrl+s)

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1021]
Raised by gcorne

We probably should have a keyboard shortcut for saving…

**Comment by lancewillett** [comment]
I would vote against this one — it conflicts with "Save" menu in browsers, and with auto-saves isn't needed.

**Comment by designsimply** [comment]
Closing because auto-save seems to be working well and I haven't seen any additional requests for a keyboard shortcut for saving.
