### ISSUE TITLE
Editor: cannot preview updates to an existing post on a Jetpack site

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1022]
Steps to reproduce:
1. Open an existing post at https://wordpress.com/post for a Jetpack site
2. Make some changes to the post content
3. Check to see if an autosave happens
4. Try to find a way to preview the updates

<strong>Result:</strong> updates don't appear to be autosaved and there is no way to preview updates made to an already-published post on a Jetpack site. ([18s](https://cloudup.com/cF-2oYeGHCI))

<img width="1280" alt="screen shot 2015-11-30 at mon nov 30 1 41 00 am" src="https://cloud.githubusercontent.com/assets/1119271/11465182/91abc408-9704-11e5-90c4-d234528b4c56.png">
<sup>Seen at https://wordpress.com/post/disambiguously.com/111 using Chrome 46.0.2490.86 on Mac OS X 10.10.5</sup>

/hat tip @aheckler for the original report

> When I publish a post [on a Jetpack site], then go back and make changes, there's no way to preview it. I can only click View (to see the post as it was published originally) or Update (to push my changes to the live post).
> 
> I should be able to preview them before publishing.

**Comment by lancewillett** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/904

**Comment by lancewillett** [comment]
This is actually different from #904 and the same as #5607.
