### ISSUE TITLE
Editor: in Safari, modules on the left are missing a scrollbar when expanded

### ISSUE THREAD

**Issue by dennishhong** [Automattic/wp-calypso#10224]
When editing a post or a page, each of the modules on the left (Publish, Categories & Tags, etc.) can be expanded. When they are expanded past the height of browser window, a scroll bar appears, so that you can scroll up and down to see all the modules.

This works fine on Chrome and Firefox, but the scrollbar does not appear on Safari. Here's what Chrome and Firefox look like (notice the scrollbar):

![screen shot 2016-12-21 at 10 10 16 pm](https://cloud.githubusercontent.com/assets/9184015/21416762/517be7bc-c7ca-11e6-82ed-422c9b67fc89.png)

And here's what Safari looks like (notice the lack of scrollbar):

![screen shot 2016-12-21 at 10 02 03 pm](https://cloud.githubusercontent.com/assets/9184015/21416776/681c89ea-c7ca-11e6-8824-7d9c97c4ac6f.png)

In fact, if the module is particularly long, and/or your browser window is on the smaller side, it's possible to get "stuck" after you expand a module, as the button to close it shifts off the screen, and you can't scroll back up to it:

![screen shot 2016-12-21 at 10 13 41 pm](https://cloud.githubusercontent.com/assets/9184015/21416812/c456702c-c7ca-11e6-85be-7eae936234dc.png)

In this case, the only way to close the module or save/update the post is to drag the browser window bigger. So while the issue is fixable if you get "stuck," it's not immediately obvious what you have to do.

This bug was reported by a user in chat: 561262-chat

**Comment by SiobhyB** [comment]
This also came up in 562071-chat. Following up with the user in 2971820-t.

**Comment by lancewillett** [comment]
I wasn't able to repeat this in testing with Safari 10.0.2 on OS X 10.12.2

When I open all the sidebar panels, and use my mouse to scroll, a scrollbar appears for the entire sidebar.

Feel free to re-open if you are still seeing the behavior.
