### ISSUE TITLE
Devdocs: internal doc links on contributing page broken

### ISSUE THREAD

**Issue by iseulde** [Automattic/wp-calypso#10227]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/.github/CONTRIBUTING.md
2. Links that should point to internal doc pages point to non existent pages. It looks like `/devdocs` is missing from the path.

#### Browser / OS version

n/a

#### Screenshot / Video

n/a

#### Context / Source

Related: #5037.

**Comment by lancewillett** [comment]
Thanks for the bug report @iseulde :)
