### ISSUE TITLE
Gallery: editing screen doesn't have auto scroll

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#10237]
#### Steps to reproduce
1. Create a new post
2. Create a new gallery and select at least 10 images
3. Resize the browser's window to a small size (then the 10 images will be enough to test)
4. Go on the Edit tab
5. Try to drag and drop the last image to the top

#### What I expected
Once you try to drag the image to the first spot the screen would auto scroll to the top to be able to drop it on the first spot.

#### What happened instead
The screen doesn't auto scroll, you have to drop the image on a new line, scroll to the top, drag the image again, drop on another line and so on.

#### Browser / OS version
Chrome v.55 / OS X 10.11.6

#### Screenshot / Video
![sortinggalleryimages](https://cloud.githubusercontent.com/assets/16104522/21437118/3413f828-c869-11e6-86b7-6103d647c73e.gif)

#user-report

**Comment by hoverduck** [comment]
I've labeled it a bug, but I'll leave it to the developers' discretion if they want to re-label it as an Enhancement.  I'm not sure what the workload is on the Media stuff right now.

**Comment by lancewillett** [comment]
More details from #10418 (closed as a duplicate).

Images can be drag-and-dropped to change their location with a post, but only if it doesn't require scrolling.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/$site
2. Add media, insert several images using the "Individual Images option"
3. Select an image further down the post and attempt to drag-and-drop it at the top of the post
4. Notice you cannot drag the image any further than the amount of post that is available, the post will not scroll up.

#### What I expected

As I drag the image up and down the post, the scroll bar should scroll up/down and allow me to drag the image to any location on the post and drop it

#### What happened instead

I can drag the post and drop it within the amount of space I can see without scrolling, but not scrolling will happen.

#### Browser / OS version
Replicated on Chrome/macOS and Firefox/macOS

#### Screenshot / Video
https://cloudup.com/cykdRowCxJA

#### Context / Source

This may not break the editor as a whole, but can certainly break some folks' workflows. In 570825-chat a user would drag-and-drop in this manner previously but seems to not be available anymore.

In the context of a photographer with 100 images in a post, trying to tell a story, they may want to drag and test out the images in a variety spots in a way that cut+paste would be cumbersome.

**Comment by alexjgustafson** [comment]
Commenting/subscribing as user from 570825-chat will want to be notified if a fix becomes available.
