### ISSUE TITLE
Calypso Preview: Unable to preview sites with mapped domains

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#10236]
I'm unable to preview a site in Calypso when a mapped domain is set as the primary domain.

#### Steps to reproduce
1. Navigate to My Sites in the top left of WordPress.com. 
2. Select any site that has a mapped domain set as its primary domain from the site picker.
3. Preview the site by clicking on the site title.

#### What I expected

I expected to see a preview of what the site looks like.

#### What happened instead

A blank page loaded in place of a preview of the site.

Possibly related to #8949, but I'm able to replicate on my test site with a variety of different themes.

Also reported in p4k3M4-1pk-p2

#### Browser / OS version

Chrome 55.0.2883.95 / macOS Sierra

#### Screenshot / Video

<img width="1226" alt="screen shot 2016-12-22 at 18 57 39" src="https://cloud.githubusercontent.com/assets/2998162/21436877/920873be-c878-11e6-975c-1bb944a6f925.png">

#### Context / Source

Reported in 562157-chat

#manual-testing #user-report

**Comment by hoverduck** [comment]
@SiobhyB I can't reproduce this on my own test site, and the site referenced in the support chat is no longer configured with the mapped domain as primary.  Can you re-test it on your domain and see if it's still not working?  And if not, can you check to see if there are any errors reported in the browser console?

Also, does the preview break on individual posts, or only the full site?

**Comment by SiobhyB** [comment]
@hoverduck: I've re-tested on my own site but am no longer able to replicate at all. It looks like this was fixed somewhere along the line! :) Closing this issue.
