### ISSUE TITLE
Photo Card: Fade too tall

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10247]
In a Photo Card, when the background is white, you can really tell that the fade is too tall.

![screen shot 2016-12-22 at 4 51 54 pm](https://cloud.githubusercontent.com/assets/24388/21444852/0aa5cd06-c867-11e6-893e-625be39ad994.png)

The fade should begin much lower down - at least half that height.

**Comment by thepelkus-too** [comment]
How do you feel about (before):
![screen shot 2016-12-27 at 3 22 22 pm](https://cloud.githubusercontent.com/assets/21962388/21510459/81a46fea-cc48-11e6-8629-f3a4ee01086a.png)

versus (after):
![screen shot 2016-12-27 at 3 23 11 pm](https://cloud.githubusercontent.com/assets/21962388/21510463/8fe4a39a-cc48-11e6-88f2-ff409e97c589.png)

The latter starts the fade 66% of the way down and still goes to black at the bottom.

**Comment by fraying** [comment]
Here's a link to the site with lots of white background photo cards. 

https://wordpress.com/read/feeds/212927

The fade still needs to be about half of what it is now (or less).

cc @jancavan
