### ISSUE TITLE
Purchases: Fix Javascript error when accessing page for removed purchase

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#1025]
We should fix an `Uncaught TypeError: Cannot read property 'productSlug' of undefined` error raised when users try to access the `Manage Purchase` page (or any page below) when the purchase has been removed and as such isn't available:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11467824/28d46088-974b-11e5-8530-295383659855.png)

More specifically, this is because the purchase object is undefined in the [`recordPageView()`](https://github.com/Automattic/wp-calypso/blob/329b40bb9e4a80976f4825e1135bce7eb16d46b9/client/me/purchases/utils.js#L47).

As an aside, we should probably redirect users on the `Manage Purchase` page with an error message explaining that they were trying to access an invalid page in that case.

**Comment by gziolo** [comment]
I started working on it in #1153 as a part of another issue :)

**Comment by fabianapsimoes** [comment]
Fixed by #1025.
