### ISSUE TITLE
Theme Sheets: Add Tracks Events

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#10262]
As an ongoing team project, Cerberus has been working to make themes docs easier to use. 

As part of our latest effort, we want to have Tracks events added to monitor the button clicks in the support area of the new theme showcase. 

We'd like to track the name of the theme, any clicks to generate tickets or chats, and any clicks to the support forums.

Example:
![theme-showcase-items-to-track](https://cloud.githubusercontent.com/assets/3505172/21459863/e4c18674-c907-11e6-98af-3cced697db57.jpg)

**Comment by jeremeylduvall** [comment]
Closed via #10430.
