### ISSUE TITLE
Text Cards with 1-line excerpts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10267]
This post: https://wordpress.com/read/feeds/2810194/posts/1272558364

Is creating this card: 
![screen shot 2016-12-24 at 9 40 57 am](https://cloud.githubusercontent.com/assets/24388/21468263/45af32f0-c9bd-11e6-82db-076573cd7922.png)

The excerpt is only 1 line, but it should be 2. Does it have something to do with the small photo?

**Comment by samouri** [comment]
Interesting.  I believe there is a `<br />` at the start of the content that is being counted.  we may want to trim all of the `\n`s and `<br />`s that occur before the first text.

**Comment by samouri** [comment]
Just realized this is a dupe of https://github.com/Automattic/wp-calypso/issues/10271.
I'm closing this and will fix in other thread
