### ISSUE TITLE
Editor: Date picker doesn't pick

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#10297]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Try to pick a new date - notice the date picker doesn't close when you click a date
3. Publish the post today
4. Edit it again - still doesn't choose a different date

With enough clicking around, you can sometimes get a date change, but very very inconsistently.

You also cannot change the time - text input doesn't alter anything.

No console errors to note.

#### What I expected
To be able to choose a new publish date with a click

#### What happened instead
Nothing

#### Browser / OS version
Mac 10.12.2/Chrome/FF/Desktop/Safari

#### Screenshot
![2016brokencalendar](https://cloud.githubusercontent.com/assets/8921630/21528985/55456d66-cceb-11e6-8540-913198a9e3f1.gif)

#### Context / Source
#user-report #live-chat

**Comment by starxedsteph** [comment]
I encountered this while demonstrating how to edit the date in a business concierge screenshare.  I did find that if you click out of the calendar and update the post, it saves the date change.  However, you never see any indication this worked until doing that.

**Comment by timmyc** [comment]
> I did find that if you click out of the calendar and update the post, it saves the date change.

Indeed that would fix the issue since the edited date would then be in both flux and redux after a save action.
