### ISSUE TITLE
Reader Discover: Create quote card

### ISSUE THREAD

**Issue by jhnstn** [Automattic/wp-calypso#10302]
Create a component for quote type posts:

![quote card comp](https://cldup.com/9SfX_xVbck.png)

**Comment by alisterscott** [comment]
I'd like to see this in the Reader generally.

A quote post type shows in Reader stream (https://wordpress.com/read/feeds/58316853) as:

![Uploading Screen Shot 2017-12-06 at 8.54.06 am.png…]()

But full post view shows the quote formatted (https://wordpress.com/read/feeds/58316853/posts/1689279268)

![Uploading Screen Shot 2017-12-06 at 8.54.50 am.png…]()

It would be nice to see the blockquote in the stream view

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

Is this issue still applicable today?

If not, the proposal is to close this issue with an appropriate label denoting reason for closure.
