### ISSUE TITLE
Editor: Back link doesn't remember what tab you were on

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#1032]
If you go to My sites > Blog posts > Scheduled tab and then edit a post, the "All Posts" back link doesn't take you to the Scheduled tab. You land on the default Published tab instead.

**Comment by designsimply** [comment]
I was testing this at the same time! Here are my testing steps:

1. Start at https://wordpress.com/posts and select your site if prompted
1. Click the "Drafts" link at the top
1. Click on any post title to edit
1. Click the "← All Posts" link at the top of the sidebar
1. Check to see if you are back on the drafts page

<strong>Result:</strong> the "← All Posts" link always goes to the Published list eve if you were looking at a different list such as Drafts, Scheduled, or Trashed before. ([18s](https://cloudup.com/c2Si2OqrRNs))

/hat tip m for the original report

**Comment by timmyc** [comment]
I just tested this flow out again and could not re-create the issue.  If I am on the drafts view, click through to a post, then click "All Posts" again, I'm returned to the draft listing.

Closing out.
