### ISSUE TITLE
OSS: OnBoarding: terminal messages + welcome + sidebar

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#1034]
I did a test run on the current repository onboarding process. From the M1 design we are missing a few pieces:

1. **✓ DONE** —Terminal: No startup message. Not a big deal, but would be nice to show something. ([design](https://cloud.githubusercontent.com/assets/4389/11472337/b2477aa4-9763-11e5-8d24-1c2d8e5a555b.png))
2. **✓ DONE** — Terminal: No wait message. This is rather important since in the test it was causing some confusion. ([design](https://cloud.githubusercontent.com/assets/4389/11472391/1f309c40-9764-11e5-8e61-847f99932b2b.png))
3. Calypso: Welcome message not showing on first run. The screen is in place and ready to be used (at `/devdocs/welcome`).
4. Docs Sidebar: The current active section isn't highlighting (this is correct for the Welcome screen, but not for the others).
5. Docs Main: the content doesn't fill properly the available space. Should be more edge-to-edge. ([screenshot](https://cloud.githubusercontent.com/assets/4389/11472521/22103f5a-9765-11e5-8d72-790d58ff4f2e.png))
6. Calypso / Loader: we should swap the text-only message with the styled one. ([current](https://cloud.githubusercontent.com/assets/4389/11476337/1a500de4-977a-11e5-8af3-0d2dcd942a74.png) | [design](https://cloud.githubusercontent.com/assets/4389/11476350/2fe09a20-977a-11e5-89c8-303f30232517.png))

At least 2 and 3 are rather relevant. I did a single issue to make sure it's all tracked as a single flow. We can break it down in multiple PRs / tickets as needed.

Related to: #474 (Welcome), #482 (Sidebar), #513 (Login/Register flows). 

/cc @nb @mtias @apeatling

**Comment by mtias** [comment]
I thought we had updated three for the flow.

**Comment by folletto** [comment]
I did a test and didn't show. Where is it memorized so I can double-check it?

**Comment by mtias** [comment]
It's declared here: https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows.js#L139

**Comment by folletto** [comment]
Aha yes, thanks. 
That's for the registration flow however, not everyone goes through that, and some might be already logged in as well. The test run as logged in didn't trigger it. :) 

To summarize, there are three possibilities:

1. Already logged in
2. Not logged in, does login
3. Not logged in, registers

The flow above accounts only for 3. The flow for 2 is covered by the login redirect, but we aren't covering 1.

**Comment by folletto** [comment]
Aside, I found a bug on the login message, it's off-centered:

![screen shot 2015-11-30 at 14 35 01](https://cloud.githubusercontent.com/assets/4389/11474387/c4f251d6-976f-11e5-8537-5ba244073eec.png)

**Comment by mtias** [comment]
For the last bug, mind checking #1038?

**Comment by folletto** [comment]
Fixed in #1039:

* 1. Terminal: No startup message. Not a big deal, but would be nice to show something.
* 2. Terminal: No wait message. This is rather important since in the test it was causing some confusion.

Fixed in #1038:

* Off-centered bug
