### ISSUE TITLE
Stats: Add Likes Details to Summary Page

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10348]
From pKdGS-1mh-p2

A possible enhancement for the Post Stats Summary page is inclusion of likes data for the given post.  We currently show like totals in the post list card:

![blog_posts_ _the_wordpress_com_blog_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/21572371/30f3a8e4-ce8d-11e6-832e-9f806bc8602b.png)

The user suggestion was to display gravatars of the post likers ( likees ? ).  Perhaps we could also show the number of comments on the post too.

**Comment by karmatosed** [comment]
Just so I'm clear, clicking this is suggested to go to a section to show likes? Or is it just to be a visible stat no link? I can see wanting to link would be good.

**Comment by timmyc** [comment]
Currently the eyeball gridicon links to the stats page for that post, so I guess with the addition of Likes data to that page in #10362, we could also link the star/like count to the same stat page.
