### ISSUE TITLE
Stats: Add sparkline next to Stats Menu Item

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10341]
In the "My Sites" drop down when viewing a site, the sparkline visualization is shown next to the Stats menu item:

![trout_bummin_ _somewhere_on_a_river_ _in_person_or_in_our_minds](https://cloud.githubusercontent.com/assets/22080/21570705/80af4e52-ce7d-11e6-9509-828d48b07103.png)

Looking at the code, I see comments where it says to suppress the sparkline in calypso flows, /cc @apeatling for any background there.  But since the sparkline has been removed from the masterbar, it is an often requested feature from long-time users, and would be quite easy to add the image in calypso too.

**Comment by timmyc** [comment]
More feedback pKdGS-1l9-p2 - based on some of that feedback, perhaps the sparkline could be added elsewhere.

**Comment by lancewillett** [comment]
I think we should close this as it's on the WP.com side (not in Calypso).
