### ISSUE TITLE
Editor: the scheduling calendar doesn't show posts on days that aren't in the current month

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1035]
Steps to reproduce:
1. Start a new post at https://wordpress.com/post 
2. Schedule the post for the first of next month
3. Start another new post at https://wordpress.com/post
4. Check to see if the date for the post you just scheduled shows up as circled on the calendar

<strong>Result:</strong> dates with scheduled posts for the next month aren't shown unless you switch months in the calendar picker.

![screen shot 2015-11-30 at mon nov 30 8 29 10 am](https://cloud.githubusercontent.com/assets/1119271/11472806/f7ffe0b2-973c-11e5-906d-cff047d66da4.png)
<sup>Seen at https://wordpress.com/post/watchingstormsrollby.me/4998 using Safari 9.0.1 on Mac OS X 10.10.5</sup>

/hat tip m for the original report

**Comment by lancewillett** [comment]
I think could be somewhat expected in that you aren't in the next month yet... but would be a nice-to-have feature.

I was able to repeat, in Mac-n-Chrome — with one extra note. When you are editing the post the is scheduled for the 1st of the next month (viewing the schedule calendar for **this** post), it is highlighted correctly.

<img width="831" alt="screen shot 2016-03-11 at 14 02 17" src="https://cloud.githubusercontent.com/assets/66797/13715455/0ed430cc-e792-11e5-881b-463e5d79eb13.png">

<img width="760" alt="screen shot 2016-03-11 at 14 02 21" src="https://cloud.githubusercontent.com/assets/66797/13715457/1138880e-e792-11e5-80d6-b79c44a2be1c.png">

**Comment by designsimply** [comment]
Noting this is still an issue.

![screen shot 2016-05-12 at 13 39 08](https://cloud.githubusercontent.com/assets/1119271/15228014/37fe3d2c-1847-11e6-81fb-8cc87a5e6047.png)
<sup>Seen at https://wordpress.com/post/watchingstormsrollby.me using Firefox 46.0.1 on Mac OS X 10.11.4</sup>

**Comment by rachelmcr** [comment]
I tested and confirmed that posts in a future month still aren't shown unless you switch months in the date picker.

In this screenshot, there is a post scheduled for November 2 that doesn't appear on the October calendar view:

![screen shot 2017-10-04 at 6 25 23 pm](https://user-images.githubusercontent.com/8658164/31189922-7f1f3afe-a931-11e7-9355-abc99ea1ee58.png)

**Comment by alisterscott** [comment]
Confirming this is still an issue

#bug-scrub #pre-gutenburg-bug-purge
