### ISSUE TITLE
Editor: warn about links when changing post date

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#10358]
When you change the date for a post, you have the potential to break existing links to that post. We should at least warn people about this. This was particularly bothersome when coupled with this issue where posts get the wrong post date. https://github.com/Automattic/wp-calypso/issues/9014

**Comment by iamtakashi** [comment]
We need a copy from the experts.

**Comment by iamtakashi** [comment]
And let go with `is-warning` notice.

![5](https://cloud.githubusercontent.com/assets/908665/22837017/b43c706a-efb6-11e6-92ba-edbb93f52503.jpg)

**Comment by iamtakashi** [comment]
>We need a copy from the experts.

I've added the label, but just in case, I'm pinging the pros. @Automattic/editorial Thanks in advance!

**Comment by gwwar** [comment]
@iamtakashi could you clarify where in the editor we'd like the notice to appear? Under the masterbar here?
<img width="775" alt="screen shot 2017-02-10 at 10 54 55 am" src="https://cloud.githubusercontent.com/assets/1270189/22839697/67e192f4-ef7f-11e6-8dfc-bcb75ed8b7fc.png">

**Comment by benhuberman** [comment]
How about:

> Are you sure about that? If you change the date, existing links to your post will stop working.
