### ISSUE TITLE
Editor: screen blanks out after selecting and attempting to copy a word

### ISSUE THREAD

**Issue by blessingmpofu** [Automattic/wp-calypso#10355]
#### Steps to reproduce
1. Starting at URL: http://blessing.im

#### What I expected

See video: https://cldup.com/Aqfgq_gcl0.mov 

#### Browser / OS version
MacBook Pro (13-inch, Mid 2012)
Processor: 2,5 GHz Intel Core i5
Memory: 16 GB 1600 MHz DDR3
macOS Sierra 10.12.2

#### Screenshot / Video
https://cloud.githubusercontent.com/assets/4680162/21581170/d3f34238-d02d-11e6-9ee8-6dabd4e44745.png

See screencast: https://cldup.com/Aqfgq_gcl0.mov

**Comment by lancewillett** [comment]
This might be related to only [the WordPress macOS desktop app](https://github.com/Automattic/wp-desktop), not the in-browser Calypso itself (wordpress.com).

**Comment by lancewillett** [comment]
Feel free to open in desktop repo if it continues to happen.
