### ISSUE TITLE
Editor: Post type label not centered

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10368]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Select a site
3. Change author (also usually evident in transitioning between placeholder Author selector and loaded state)

#### What I expected

Post type label should remain centered (i.e. "New Post")

#### What happened instead

Post type label adjusts left and right depending on width of author element.

#### Browser / OS version

macOS Sierra Version 10.12.2
Chrome Version 55.0.2883.95 (64-bit)

#### Screenshot / Video

![push](https://cloud.githubusercontent.com/assets/1779930/21596002/ae573ae0-d102-11e6-9b4d-72df0138be13.gif)

#### Context / Source

Suspect related to #5987 (likely need to adjust some flex properties to avoid shrink/grow), cc @DanReyLop @alisterscott @folletto

**Comment by lancewillett** [comment]
I couldn't repeat this today, testing with macOS 10.12.2 latest Chrome (Safari 10.0.2 also worked OK).

Feel free to re-open if you see it again.

**Comment by aduth** [comment]
The issue still persists for me as of today.

![offset](https://cloud.githubusercontent.com/assets/1779930/22004686/acaf98ac-dc2b-11e6-917e-7bcf936fe056.gif)

**Comment by lancewillett** [comment]
Oh—I noticed in re-testing that all 3 of my authors, on my test site, have the same length of name. :) You clearly triggered it easier by switching from "Andrew Duthie" (long) to `aduth` (short).

**Comment by aduth** [comment]
Yeah, seems most noticeable on those extremes. It appears the text _pushes_ the centered label to make room.
