### ISSUE TITLE
Site Settings: Redirect private sites to legacy site icon behavior

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10363]
The image editor does not currently support private sites because the media requires authentication and does not serve CORS headers (required by the image editor). Therefore, we should not display the site icon media modal flow for these sites. Instead, they should be directed to legacy behavior which at the current time is wp-admin's General settings screen. This will likely change to display the Customizer instead in the near future (at least staying within the Calypso context).

**Comment by nylen** [comment]
> the media requires authentication and does not serve CORS headers (required by the image editor)

Can we fix this by adding appropriate CORS headers?
