### ISSUE TITLE
Settings: Related Posts: make the setting binary with a single toggle

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#10391]
Currently we use a radio button with two different and opposite labels to control related posts:

**Before:**
<img width="724" alt="screen shot 2017-01-03 at 4 25 00 pm" src="https://cloud.githubusercontent.com/assets/437258/21623717/d4a5aefa-d1d1-11e6-8b6b-d941482cd869.png">

This isn't the most efficient way to display this setting. The user has to fully read both options to understand which choice they want to make. 

Additionally we are not hiding the preview or the sub-options when this feature is turned off. They simply have reduced opacity and can still be interacted with (you can toggle on/off options even if you have related posts disabled on your site, that's a bug). 

Let's use a single toggle instead.

**After:**
![off](https://cloud.githubusercontent.com/assets/437258/21623771/0f257588-d1d2-11e6-8ff9-ac7eda9766ec.jpg)
![on](https://cloud.githubusercontent.com/assets/437258/21623770/0f235028-d1d2-11e6-8a90-06e26ab72bc3.jpg)

Let's hide the sub options and preview if the feature is turned off.

cc @MichaelArestad @oskosk @johnHackworth 

h/t @ashleighaxios for doing the mockups

Also see the corresponding Jetpack issue: https://github.com/Automattic/jetpack/issues/6037

**Comment by tyxla** [comment]
Thanks for the awesome suggestion! This is being addressed in https://github.com/Automattic/wp-calypso/pull/10423.
