### ISSUE TITLE
Framework: toTitleCase butchers German UTF-8

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#104]
Example: https://wordpress.com/tag/fahrrader shows the string as `Fahrr Der`

The UTF-8 character ä is not considered as a part of the word, it should be `Fahrräder`.

Another example is https://wordpress.com/tag/strase:
![image](https://cloud.githubusercontent.com/assets/7233112/11247224/18c438aa-8de9-11e5-99c1-9c68b2b47694.png)

A solution would be to use CSS: `text-transform: capitalize;` though this wouldn't work for the page title.

**Comment by lancewillett** [comment]
Re-testing this 3 months later: it's been solved by changes to force lowercase in tag titles (see Reader Tag and List management changes).

<img width="827" alt="screen shot 2016-03-11 at 09 00 05" src="https://cloud.githubusercontent.com/assets/66797/13707613/bd6c23d6-e767-11e5-92d3-34fd9ef13e61.png">
