### ISSUE TITLE
Editor: images disappear and reload when upload completes

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1040]
Raised by @apeatling 

If you upload a[n] image to the editor, then continue with changes, [when the image re-renders] the image will disappear and be reloaded in place. This is quite disorienting, it took a couple of seconds for the image to load in place again.

<strong>Video:</strong> [1m4s](https://cloudup.com/cLcyjL6PJEN)

Notes from @aduth 

> When uploading an image to the media library, we show a temporary copy of that image, which is replaced with the persisted copy once the image has finished uploading. Instead of swapping the image source immediately upon receiving the persisted copy (which causes a blank square to appear briefly), we should preload the persisted image in the background, only to be swapped out once the load has completed
>
> __Pseudo-code:__
>
> ```
> var image = new Image();
> image.src = persistedImageSource;
> image.onload = swapTemporaryImage;
> ```

**Comment by folletto** [comment]
+1

This makes for a rather jarring experience.

**Comment by codebykat** [comment]
We talked about this a bit in Slack; it's a relatively minor issue and pretty hard to fix, so it's not a priority at the moment.

@aduth's thoughts:

> we’d have to do some similar hackery to what we did with https://github.com/Automattic/wp-calypso/tree/master/client/components/tinymce/plugins/media/restrict-size
> or totally rethink how images are rendered in the editor, like creating a custom wp-view class for it
> which we probably ​_should_​ do, but is no small feat
> creating a wpview for images would open up a lot of possibilities though
> basically the entire idea behind wpview is “show something different than what’s actually saved to the post”, which is what we need and have been hacking around for images
> only needing to hack around because wpview lacks some basic functionality like custom toolbar items

@timmyc:
> or show a placeholder until it is uploaded - but that would still create a flicker/jump and not be very elegant

**Comment by apeatling** [comment]
I would argue that this isn't as minor as it seems. It's quite disorienting when you upload an image and it disappears, and it erodes trust in the tool. Generally it's quite a jarring and unexpected experience for something so fundamental to the editor -- something many people are going to do every time they use it.
