### ISSUE TITLE
Jetpack requirements message

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#10405]
We need to implement a messaging letting the user know an update is required to keep using Calypso.

#### Proposed solution

As @rickybanister mentioned, we have done something like this in the past:

![image](https://cloud.githubusercontent.com/assets/1123119/21653201/352ccb64-d26d-11e6-99b6-92435924128f.png)

It would show up everywhere on the Jetpack site views in Calypso (I think). I'm not sure what to do with views themselves. We could just replace all the views with the same update message removing access to settings or we could treat it more like a modal where it covers the settings/views.

#### Copy 

Maybe something like this:

> `<SectionHeader>Jetpack update required</SectionHeader>`

> Your Jetpack needs to be updated in order to use WordPress.com. Jetpack now has tighter integration with WordPress.com and, without the update, many things don't work as expected. We're super sorry for the interruption, but all you have to do is click the big blue update button and your WordPress.com dashboard will be back in action!

> `<Button>Update Jetpack</Button>`

#### Bonus experience

And maybe after they've hit update, we update the block to say something like:

> `<SectionHeader>Autoupdate available</SectionHeader>`

> Awesome! You're good to go, but if you never want to see this message again, you should turn on autoupdates for Jetpack. They'll make sure you're always on the latest, fastest, bestest version of Jetpack.

> `<Button borderless>Skip</Button><Button primary>Autoupdate Jetpack</Button>`

**Comment by rickybanister** [comment]
Those suggestions sound pretty good—I wonder if we might be able to offer that same experience in a single step? We could invite the user to click an 'Update Automatically' button that would attempt to get them up to date and enable future auto-updates. (We could explain how that would work in the copy above not to surprise anyone.) Only if the update failed would we need any further intervention—instructions on updating Jetpack manually. 

If we are successful in updating Jetpack, we can just give them a nice satisfying success message.

**Comment by rickybanister** [comment]
To append my previous comment, we could offer them an alternative to Autoupdate in the body copy—we could mention 'if you are not interested in updating automatically you can perform a manual update' and link them to instructions.

**Comment by MichaelArestad** [comment]
@rickybanister I was thinking something similar, but my instinct was to break it into two steps. One: fix the problem. Two: fix it forever cause that was annoying.

Comboing them into just one step seems good and if it feels off we can break it up later. Maybe something like this:

> `<SectionHeader>Jetpack update required</SectionHeader>`

> Your Jetpack needs to be updated in order to use WordPress.com. Jetpack now has tighter integration with WordPress.com and, without the update, many things don't work as expected. All we need you to do is update Jetpack and your WordPress.com dashboard will be back in action! If you enable autoupdates for Jetpack (the big blue button), you won't see this message again. We're super sorry for the interruption.

> `<Button borderless>Update Jetpack</Button><Button primary>Autoupdate Jetpack</Button>`
