### ISSUE TITLE
Sites: Adding a new domain doesn't change the slug everywhere

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#10402]
1. Start with a WordPress.com site with two mapped domains
2. Switch the primary from one mapped domain to the other
3. Notice the selected site's domain in the sidebar does not update
4. Click on Settings for the current domain
5. Notice a bunch of errors in the console like `index.jsx:179 Uncaught TypeError: Cannot read property 'jetpack' of undefined`

**Comment by blowery** [comment]
[Video on Cloudup](https://cloudup.com/cFjRIijfhRm)

**Comment by umurkontaci** [comment]
Related: #9890 and #3067
