### ISSUE TITLE
Customizer: images don't load on Safari iOS in Customizer Preview

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#10417]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize/ in Safari on iOS
2. Tap "Preview"

#### What I expected

See site images

#### What happened instead

No site images, the edit icons (direct manipulation) look non-retina/blurry

Console errors:

`Unable to post message to https://eatkibbeling.wordpress.com. Recipient has origin https://wordpress.com.
`
(same error for sites with mapped domains)

#### Browser / OS version

iOS Safari 10.2

#### Screenshot / Video

![ios - 1](https://cloud.githubusercontent.com/assets/128826/21666002/c2d9dccc-d33a-11e6-844f-d86949dcbc0b.jpg)

**Comment by lancewillett** [comment]
Moved to 143-gh-customization
