### ISSUE TITLE
Reader full post: 'More on...' recommendation blocks smush together in IE11 at certain widths

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#10419]
In Reader full post on IE11/Win7, two adjacent recommendation blocks in 'More on...' have their content mixed both under 400px wide:
<img width="405" alt="screen shot 2017-01-05 at 15 53 06" src="https://cloud.githubusercontent.com/assets/17325/21669439/ee41f4f6-d35f-11e6-95fc-c4246bcb85ce.png">

... and also between around 490px and 530px wide:

<img width="548" alt="screen shot 2017-01-05 at 15 53 48" src="https://cloud.githubusercontent.com/assets/17325/21669443/f3973cae-d35f-11e6-850b-70ab0ab2caf2.png">

'Super long post' and 'Comment test' are two separate posts, and normally appear like this:

<img width="748" alt="screen shot 2017-01-05 at 16 00 39" src="https://cloud.githubusercontent.com/assets/17325/21669474/290d9f18-d360-11e6-8bf0-f9fefd35f328.png">

#### Steps to reproduce
1. Starting at URL: any full post with recommendation blocks, e.g. https://wpcalypso.wordpress.com/read/feeds/40474296/posts/1282650679
2. Reduce size of viewport to <400px or 490-530px
3. Smushing occurs

**Comment by raoulwegat** [comment]
At a quick glance, this bug is kicking in right where the `.reader-related-card-v2__list` media query changes `flex-direction` from `row` to `column` and IE11 is borking it.
