### ISSUE TITLE
Site Icon: making changes to site settings then adding site icon makes form change potentially lost

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#10412]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/general/
2. Make some changes to general settings - don't click Save
3. Upload a new site icon
4. Navigate away from form without clicking Save

#### What I expected

Prompt saying there are unsaved changes

#### What happened instead

No prompt - changes are lost

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

![loses changes](https://cloud.githubusercontent.com/assets/128826/21662658/cad1d16e-d326-11e6-94f6-1030a1559430.gif)

**Comment by aduth** [comment]
cc @youknowriad re: #9085. I think we'll need to differentiate after a save has succeeded whether that save originated as part of changes to the form. This condition here:

https://github.com/Automattic/wp-calypso/blob/8ef8bc3/client/my-sites/site-settings/form-general.jsx#L139-L146

Specifically, maybe we should save state after triggering the save from the form and only mark as cleared if that state flag is present? Or otherwise identify the request that had been issued (might lead into a larger question/problem of tracking individual requests in Redux).

**Comment by youknowriad** [comment]
Yeah! not an easy problem to solve. For this particular use-case we could flag the state (seems the simplest solution), but it seems hacky.
As you said, maybe we should consider adding an optional `uid` to track specific requests statuses when calling `saveSiteSettings` action creator. I think my preference goes to the second solution even if it's more code. Do you have any other suggestion?

**Comment by aduth** [comment]
@youknowriad An alternative idea to consider: What if we never explicitly call `clearDirtyFields` from the form itself in response to the settings save, but rather compare against an incoming settings prop to see if what we consider to be dirty to now be the latest value for the site? In other words, "dirty" comes to mean when there are differences between what we know to be the latest value and what is currently in the form.

**Comment by youknowriad** [comment]
@aduth What if the props changes (from a sub component action maybe) but we did not persist these state changes on the server. I'm just wondering if this is something possible.

**Comment by aduth** [comment]
@youknowriad As in if a component were to call `updateSiteSettings` but only optimistically, not actually saving? That's a good point. We could create a separate reducer for tracking what we know to be the saved settings, or conversely, if we want to avoid duplication, maybe treat it like posts state where `edits` are managed as the unpersisted changes to be applied. That way dirty checking could be as simple as `Object.keys( edits ) > 0`. Question then would be if it still makes sense for `getSiteSettings` to be canonicalized as `merge( {}, savedSettings, edits )`

**Comment by youknowriad** [comment]
@aduth I don't know how I feel about this. I think I'd rather use the optional id approach for the sake of simplicity. But I could be wrong.
