### ISSUE TITLE
Reader: Show a list of people who have liked a post

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#1042]
We currently only show the number of likes a post has, but we can do better. Here's a quick idea that shows a `<Popover />` on :hover

![stream](https://cloud.githubusercontent.com/assets/191598/11477521/6227f4fc-9756-11e5-91d9-eeb718219976.png)

![full post](https://cloud.githubusercontent.com/assets/191598/11477533/6f1169fa-9756-11e5-96fd-8ecfcc1c3439.png)

**Comment by blowery** [comment]
How would this work on touch interfaces?

**Comment by shaunandrews** [comment]
> How would this work on touch interfaces?

Maybe tap-and-hold the like button to show the list?

**Comment by designsimply** [comment]
@shaunandrews, does this supersede #745?

**Comment by shaunandrews** [comment]
No sure if it supersede's or compliments. I'll give it some thought.

**Comment by designsimply** [comment]
Note: would like to also explore a design option for showing likes at the bottom of the post, see https://github.com/Automattic/wp-calypso/issues/4183#issuecomment-203671974

**Comment by jancavan** [comment]
Closing. We have new mockups for this that don't use the popover.
