### ISSUE TITLE
Editor: Obey taxonomy show_ui flag.

### ISSUE THREAD

**Issue by pento** [Automattic/wp-calypso#10428]
#### Steps to reproduce

1. Register a custom taxonomy with the `show_ui` flag set to false
2. Visit the editor, observe that the custom taxonomy is showing in the sidebar

#### What I expected

The custom taxonomy box should be hidden, same as if you visit the wp-admin editor for the same site.

**Comment by lancewillett** [comment]
This could be a duplicate of #8757

See also #701 and #700
