### ISSUE TITLE
Editor: Embeds show for YT videos with embedding disabled

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#10439]
1. Find a YouTube video that disallows embedding, e.g. https://www.youtube.com/watch?v=J8AisTXgAGA
2. Paste the URL into a new post editor.
3. Watch as the editor transforms it into an embed, as if it will play just fine.
4. Publish the post.
5. Darnit:

<img width="844" alt="screen shot 2017-01-05 at 3 12 20 pm" src="https://cloud.githubusercontent.com/assets/5512652/21695835/608432f6-d359-11e6-8f4f-bb7b52a9ae42.png">

Maybe we can detect this and display some sort of "This won't work" warning?

**Comment by lancewillett** [comment]
This should probably be in core WordPress — or port our fix once we have one.

**Comment by rachelmcr** [comment]
This will be resolved in Gutenberg, which displays this message in the YouTube block:

> Sorry, we could not embed that content.

#bug-scrub #pre-gutenburg-bug-purge
