### ISSUE TITLE
Reader: Photo cards and card images need to be resized

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#10433]
Poke at https://wordpress.com/read/feeds/52296202

The photo cards are loading images that are nearly 4K pixels in width. We should be limiting them to around 1400 max (700px viewable * 2 for high dpi). 

Featured images on normal cards appear to be limited to 1440 already, but we could probably shrink that down when the viewport is narrow. This gets a bit more complicated, as we show a wide version for certain viewport widths.

**Comment by blowery** [comment]
Looks to fixed by #10310

**Comment by bluefuton** [comment]
Can confirm that photo cards are now limited to 1440px width on `master` (using the example blog above).
