### ISSUE TITLE
Framework: Safari OSX Dropdowns show missing image tick

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#10444]
Originally reported by @lancewillett 

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design
2. Choose a dropdown control

#### What I expected

A tick next to selected option (this is as per the [standards page](http://www.w3schools.com/TagS/tryit.asp?filename=tryhtml_select))

<img width="160" alt="screen shot 2017-01-06 at 9 27 26 am" src="https://cloud.githubusercontent.com/assets/128826/21701612/5ce24dce-d3f2-11e6-92d5-96ff552db91e.png">

#### What happened instead

A missing image tick next to selected option (this happens throughout the Calypso UI not just on dev docs page)

<img width="659" alt="screen shot 2017-01-06 at 9 23 18 am" src="https://cloud.githubusercontent.com/assets/128826/21701617/6e141c76-d3f2-11e6-8010-e1e9d4d8cd7a.png">

#### Browser / OS version

Safari  10.0.2 on OSX 10.12.2

#### Screenshot / Video

See above and

<img width="716" alt="screen shot 2017-01-06 at 9 25 54 am" src="https://cloud.githubusercontent.com/assets/128826/21701637/995943e8-d3f2-11e6-9368-c852699a44fe.png">

**Comment by alisterscott** [comment]
I've attempted a fix in #10445 but waiting on some design feedback

**Comment by lancewillett** [comment]
Thanks for the fix, @alisterscott ! Dropped vizrec on the pull request for the after (based on Live Branch testing).
