### ISSUE TITLE
Site Settings: Site icon can sporadically revert back to previous setting

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10450]
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/settings
2. (Prerequisite) If not already assigned, assign a Site Icon
3. Click Remove below Site Icon
4. Navigate around the application

#### What I expected

The site icon has been reset to the default value in all `<Site />` components.

#### What happened instead

Occasionally the site icon may revert back to its previous setting.

#### Context / Source

Quite possibly an issue with the selected site from `sites-list` being received into Redux state with stale data after revisiting the site settings page, since the removal of site icon is not internally reflected by `sites-list` (managed only in Redux state).

See also: https://github.com/Automattic/wp-calypso/projects/3

cc @rachelmcr

**Comment by obenland** [comment]
I was testing #10569 when I encountered similarly weird behavior where on `/settings/general/:site:` I'd see the Site Icon flash and disappear. It looks like `SITE_RECEIVE` correctly sets the site icon there but it gets removed later on with an erroneous payload in `SITE_SETTINGS_RECEIVE`

<img width="885" alt="screen shot 2017-01-13 at 3 10 27 pm" src="https://cloud.githubusercontent.com/assets/1398304/21949026/e3323d2e-d9a3-11e6-9098-5fe46e612eae.png">

Could this be related?

**Comment by aduth** [comment]
@obenland In your case, I think it's problematic that `media_id` (i.e. the `site_icon` option) is set to `0`. I've seen this a couple times in the past and have had a hard time tracking it down.

Based on API logic of `is_falsy`, I'd have expected that attempts to set a `media_id` of `0` (numeric or string) would result in the option being deleted, not set to zero:

- https://github.com/Automattic/jetpack/blob/d5e5dad/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php#L455-L468
- https://github.com/Automattic/jetpack/blob/764a699/class.json-api.php#L67-L76
