### ISSUE TITLE
Cannot find module 'webpack.config'

### ISSUE THREAD

**Issue by zhenyulin** [Automattic/wp-calypso#1045]
Can't start the local server when execute "make run", get the error message "Cannot find module 'webpack.config'"

**Comment by lancewillett** [comment]
Hi zhenyulin, what's your system setup?

**Comment by lancewillett** [comment]
We have a few troubleshooting tips here: https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md
