### ISSUE TITLE
Purchases: HTML in error message

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#1046]
If privacy is attached to a domain but that domain doesn't have privacy in the WHOIS, the user will see this message:

<img width="636" alt="screenshot 2015-11-30 17 11 40" src="https://cloud.githubusercontent.com/assets/275961/11478532/830f05be-9785-11e5-9550-b3f0dbb0dac2.png">

We need to strip the HTML from this and replace the link. We could use this approach:

https://github.com/Automattic/wp-calypso/blob/a7478174b0441760c332fcb4b8c454f5b8d73dfc/client/my-sites/upgrades/checkout/transaction-steps-mixin.jsx#L54

**Comment by stephanethomas** [comment]
Apparently this message is displayed when users try to cancel a private registration purchase whereas private registration isn't actually enabled in the system of our third-party provider. This is probably an edge case but on the other hand I think we can remove this check (and error message) from the API and simply remove the corresponding subscription.
