### ISSUE TITLE
Plans: Clarify Discount is for First Year

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#10467]
Let's clarify that one-time discounts on the http://calypso:3000/plans page are meant for the first year only. 

When a discount is visible, let's update the text from `per month, billed yearly` to something like: `per month for the first year, billed yearly`

To reproduce:
- Login to Calypso
- Buy a personal plan for the site
- Visit the plans page http://calypso.localhost:3000/plans/:site:

<img width="889" alt="plans" src="https://cloud.githubusercontent.com/assets/1270189/21731253/4f5f2bde-d408-11e6-86c2-b28be369be46.png">

See also: p3fqKv-44c-p2 ( #comment-8024 )

**Comment by sararosso** [comment]
Copy suggestion to tighten it up:

per month for one year, billed yearly.
