### ISSUE TITLE
Question: would like to contribute - how to choose an issue to solve?

### ISSUE THREAD

**Issue by velesin** [Automattic/wp-calypso#1047]
I'd like to help by contributing some code. I don't have any "personal favourites" among issues - I'm open to code anything that'd be useful for you / community. Therefore, I have 2 questions:

1. Is there any way to prioritize issues? (any combination of labels / milestones that would filter the issues you'd prefer do be done first?) Or should I just pick at random?

2. Is there a way to distinguish issues "accepted" by the core team form the ones just "proposed" by the community? (I see there are many new features and changes proposed - I don't know if they all are valid? I'd like to avoid working on something that may later turn out to be an undesired change).

**Comment by lancewillett** [comment]
Hi velesin! Welcome.

> 1. Is there any way to prioritize issues? (any combination of labels / milestones that would filter the issues you'd prefer do be done first?) Or should I just pick at random?

We have a label called [Calypstarter](https://github.com/Automattic/wp-calypso/labels/%5BType%5D%20Calypstarter) that could be a great place to start.

> 2. Is there a way to distinguish issues "accepted" by the core team form the ones just "proposed" by the community?

Not yet. We're working on this.

Thanks for your interest!
