### ISSUE TITLE
Purchases: `ConfirmCancelPurchase` never loads for purchases with no purchase method

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1048]
![screen shot 2015-11-30 at 9 56 45 am](https://cloud.githubusercontent.com/assets/1130674/11479859/04d5bf30-9749-11e5-9b16-345fc31f4aa6.png)

This also results in [an error](https://cloudup.com/cL20Pjmg66H) being logged in the console.

**Comment by fabianapsimoes** [comment]
@drewblaisdell how can we reproduce this? Is using credits enough?

**Comment by drewblaisdell** [comment]
@fabianapsimoes Good question. I believe using the internal admin tool to add the purchase is how I noticed this.

**Comment by scruffian** [comment]
Closing this now it's fixed.
