### ISSUE TITLE
Checkout: Add warning about cancelations and refunds for extra G Suite licenses

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/wp-calypso#10499]
Google does not allow the cancelation and refund of additional/extra licenses for G Suite post-purchase, but we frequently have users who buy it and then change their minds later. 

Some users buy additional licenses thinking that their original purchase didn't go through, so it would be great if we could add a warning or note *before* purchase that they are purchasing an "extra" license to an existing Google account and that it can't be canceled/refunded. Maybe add something about how they can contact support if they have questions.

For example, Squarespace has a warning/alert for users buying G Suite during checkout:

![screen_shot_2017-01-05_at_4_26_56_pm2](https://cloud.githubusercontent.com/assets/6569475/21771400/d196bd10-d64c-11e6-9986-4a0d0ff12106.jpg)

Note: The *original* license purchased can be canceled and refunded within 30 days after the purchase date, but not extra licenses. If a user wanted to cancel any extra licenses, they will have to unassign that license (i.e., leave it without a user) during the plan year. When it comes up for renewal the next year, the plan renews with the total # of active licenses and all licenses without a user will be automatically removed. 

/cc @chad1008 @klimeryk @dzver

**Comment by Lochlaer** [comment]
Previously referenced in #2502.

**Comment by umurkontaci** [comment]
Is there a reason to have two issues of the same thing?

**Comment by Lochlaer** [comment]
@umurkontaci To get more eyes on it? ;-)

Seriously, I tried searching for a similar/same issue before posting but didn't find it. Of course, I found it *after* I posted this one, so I linked to it, not sure of whether or not to delete the original (because it has screenshots, albeit of the old checkout flow, and discussions possibly relevant). Happy to delete this one and defer to that one, but I really wanted to see if we could possibly implement this change sooner rather than later. We've had a not-insignificant uptick in users buying multiple licenses (sometimes more than 2+), either thinking that their original one didn't work or because they thought they wanted it but then changed their minds after.

**@dzver says he has a diff awaiting approval that would disallow users from purchasing an extra license for the *same* username as the original (to address the problem of users buying extra licenses because they thought the original purchase didn't go through), so yay!** But if it's not too much trouble, it would be awesome if we could have some kind of alert or warning at checkout clarifying the refund/cancelation issue.

**Comment by umurkontaci** [comment]
Fair play :) I don't mind which, but I think we should have one issue per "issue". We can bump the priority and ask @klimeryk or @aidvu if they are willing to take it on.

**Comment by Lochlaer** [comment]
Thank you, @umurkontaci! I forgot to mention that I also didn't know exactly how to *properly delete* a Github issue. There's "delete" and then there's "delete," so I defer to your expertise and experience to let me know how to go about doing that. :-D

**Comment by umurkontaci** [comment]
We can just close this, no need to delete :)

**Comment by Lochlaer** [comment]
Closing this issue since it's already referenced/opened in #2502.
