### ISSUE TITLE
DNS Editor: Add a warning when TXT records are non-ascii

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#10500]
When the text records include non-ascii characters. We should a warning / notice to indicate that, but not prevent.

This is important for cases where the user pastes a text with quotes and the quote strings are converted from `"` to `“` and `”` by text editor, mail apps.

Related: pMz3w-6eZ-p2

**Comment by aidvu** [comment]
Fixed by #10571
