### ISSUE TITLE
Media: Include option to copy item's URL

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#1051]
There is currently no easy way for a user to copy a media item's URL. A workaround for images is to either right-click and copy an image's URL from the context menu, or to press the Add Link button with an image selected (the URL field is populated with the image's original URL). However, it is not so easy to copy the URL for a non-image URL (audio, video).

We should consider adding a URL field with copy button to either the media modal details view, or to a media edit modal (yet to be introduced to the editor).

Ref: 2439988-t

**Comment by codebykat** [comment]
Also requested: 2441283-t

> I can no longer find the URLs for files uploaded to my Media Library in order to paste those
> links into images on my site. What happened to the URLs? Now, I have to do this
> in a very clunky fashion: insert the media file into my site, copy the URL from
> the link, and then undo this.

> For example, I have a graphic of a PDF file that is replicated in many rows of a table in my site. I use those images to link to different files, as you guessed.

> Without that ability, WP has become much more difficult to use to host and administer my sites. Hope this functionality comes back; advanced image editing won't solve it obviously; it's a more basic matter of needing the actual URLs for my media files. Otherwise all that would appear in my site is the link rather than being able to embed the link within a graphic.
