### ISSUE TITLE
AT: Can't change sites when viewing eligibility

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#10511]
If you switch sites while viewing `/eligibility` in plugins, the page will become blank when you switch sites.

**To Reproduce**
1. Visit `/plugins` on a .com site and attempt to install a new one.
2. When you see the eligibility warnings, switch the site.
3. Observe that the page is now blank:

<img width="1076" alt="screen shot 2017-01-09 at 4 14 48 pm" src="https://cloud.githubusercontent.com/assets/789137/21789002/c587211a-d686-11e6-9c9d-527986c40bc1.png">

I suppose if the site is switched, we should just kick them back to `/plugins`?

**Comment by vindl** [comment]
Resolved in https://github.com/Automattic/wp-calypso/pull/10666.
