### ISSUE TITLE
Notifications: Jetpack comment moderation unreliable

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#10529]
#### Steps to reproduce
1. Starting at URL: WordPress.com
2. Admin bar
3. Notifications (far right)
4. Any comment awaiting moderation from a Jetpack site

This has been an issue for >6 months, finally writing this to bring more attention to it! Please see the video to see how frustrating it is, haha.

#### What I expected

To be able to moderate comments consistently from WordPress.com for Jetpack-powered sites.

#### What happened instead

I was not able to, comment status changes and only sometimes works.

#### Browser / OS version

Chrome, appleOS Sierra

#### Screenshot / Video

https://www.dropbox.com/home/Misc?preview=calypso-jetpack-moderation.mov

#### Context / Source

I use WordPress.com and I have a few WP sites hosted elsewhere that use Jetpack -- favorite feature of WordPress.com is being able to update plugins and do stuff like moderation from one place. Anything that breaks this flow makes me a sad camper. Sad christmas.

Peace and a8c 4ever

**Comment by lancewillett** [comment]
Thanks for the report, Isaac. (Team Santa 4ever!)

**Comment by isaackeyet** [comment]
🎅

**Comment by lancewillett** [comment]
Triage note: this needs investigation, could be fixed with recent reworking of notifications client. CC @kwight

**Comment by kwight** [comment]
This is fixed for any non-admins having problems moderating comments on their own posts, as of now for WP.com (r163946-wpcom), and v5.5 for Jetpack (Nov 7, 2017 release date, see https://github.com/Automattic/jetpack/pull/7980).

**Comment by kwight** [comment]
Closing, let's address any further problems in new issues.
