### ISSUE TITLE
Post Schedule: Add more info to clarify timezone setting

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#10522]
We’ve had feedback saying the timezone info is confusing specially when it comes to schedule a post #7253, and this keeps coming up. I suppose this is largely because many users have never changed their site timezone setting and have left it default, UTC+0.

Let’s say, if I’m in Madrid (UTC+1), and I’m one of those new users who isn’t aware of the setting, I’ll see this:

<img width="320" alt="screen shot 2017-01-10 at 13 25 40" src="https://cloud.githubusercontent.com/assets/908665/21809017/cc2a2ece-d73d-11e6-8a02-31beae0f77e9.png">

The info currently focuses on the delta which is helpful, and it’s clean and minimal. However, I wonder if we can afford to be a more verbose to clarify and make users aware of the setting at the same time. Also, we could clarify which timezone will be used for scheduling/publishing. This is another feedback we’ve had from our users.

I’ll leave the exact copy with someone else, but I was wondering if something like this would be helpful.

<img width="294" alt="screen shot 2017-01-10 at 14 15 33" src="https://cloud.githubusercontent.com/assets/908665/21809032/df21c7e4-d73d-11e6-8813-3e9703a777c4.png">

We could add more info and a nudge into the popover rather than the current value of your site timezone.

<img width="421" alt="screen shot 2017-01-10 at 14 19 34" src="https://cloud.githubusercontent.com/assets/908665/21809049/efaffe3c-d73d-11e6-886e-77f7dfedef3f.png">

cc @rralian @meremagee

**Comment by retrofox** [comment]
> We could add more info and a nudge into the popover rather than the current value of your site timezone.
> <img width="421" alt="screen shot 2017-01-10 at 14 19 34" src="https://cloud.githubusercontent.com/assets/908665/21809049/efaffe3c-d73d-11e6-886e-77f7dfedef3f.png">

Now we are showing the current timezone of the site. could be useful keep it on this new design?

<img src="https://cloud.githubusercontent.com/assets/77539/21865142/9d50475a-d823-11e6-9037-e3a1b20eb78c.png" width="350px" />

**Comment by retrofox** [comment]
<img src="https://cloud.githubusercontent.com/assets/77539/21869819/2a827422-d838-11e6-9bf8-42a0d4221bcd.png" width="400px" />

**Comment by iamtakashi** [comment]
👍  Good idea. It's even more clearer.

**Comment by folletto** [comment]
I was about to suggest the same change. I recall we tried to design it to be minimal, but I'm ok in being more verbose for clarity (even if I'd appreciate if we can find a shorter version). 

One thing is being even more clear in stating the timezone. "Europe/Madrid" doesn't tell me much, "+01:00" tells me a lot more, both is the actual best scenario. Let's keep both. :) 

Also small change in copy:

> This site timezone is +Xh from your local timezone.

And:

> This site timezone (Europe/Madrid +XX:00) will be used for publishing. You can change it in General Settings.
