### ISSUE TITLE
Blinky gravatars in Search

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10543]
In Safari (10.0.2), the gravatars in Search blink with every load. Sometimes multiple times. The blinking also happens in Recs on the search default.

https://cloudup.com/cLEBT8UUc5R

**Comment by raoulwegat** [comment]
Also in 10.0.3. Safari on macOS only.

![gravitar-blink](https://cloud.githubusercontent.com/assets/2627210/22580681/83b1accc-ea2e-11e6-84e3-96e373ef9ed4.gif)

**Comment by raoulwegat** [comment]
![screen shot 2017-02-08 at 11 13 11 pm](https://cloud.githubusercontent.com/assets/2627210/22736809/3fa51878-ee54-11e6-9263-77e7702299d4.png)

Disabling Adblock Safari plugin stops the problem. My JS chops aren't up to scratch to figure out why it is occurring.

**Comment by fraying** [comment]
Pinging @samouri and @aaronyan because we were talking about this just now. 

FWIW, I am using Adblock, but I have all of wordpress.com whitelisted, so it shouldn't matter (but maybe it still does).

**Comment by fraying** [comment]
Confirmed! I tested this page with all of my Safari Extensions disabled and the blinking stopped. Then I tested adding them back one at a time, and both AdBlock and Ghostery caused the gravatar blinking.

I'd still love to know what it is about these extensions that causes this behavior, but since it's limited to people with these extensions enabled, maybe it's not worth our time.

**Comment by blowery** [comment]
@fraying ah ha, I see! we don't load gravatars from wordpress.com. 

We load them from gravatar.com 

Try whitelisting that in addition to wordpress.com? Might also whitelist wp.com.

**Comment by fraying** [comment]
Weirdly, whitelisting doesn't help. The mere presence of the extensions causes the blinky gravatars. 

What I don't understand is, why is this only happening in Search, and nowhere else in Reader? What's different about Search?

**Comment by raoulwegat** [comment]
@fraying I'm no longer seeing this. Same Safari/macOS version.

**Comment by fraying** [comment]
Huh! Me, either. Yay!

**Comment by samouri** [comment]
This seems to be a known issue with adblock + safari.  Definitely unsure of why it would start working all of a sudden.

https://help.getadblock.com/support/solutions/articles/6000152080-images-flash-blink-flicker-or-lag-in-safari-with-adblock-on
