### ISSUE TITLE
Editor: page with high amount of images is not editable (can't click on content)

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#10552]
#### Steps to reproduce
1. Starting at URL:https://wordpress.com/page/burfordmedia.wordpress.com/42555
2. The text is not editable. You cannot click on this page content to select a text or insert anything 
3. You can, however, edit it from Wp-admin editor, here 
https://burfordmedia.wordpress.com/wp-admin/post.php?post=42555&action=edit

#### What I expected
I expected to be able to edit this page content

#### What happened instead
You are not able

#### Browser / OS version
Reproduced in Safari and Chrome

#### Context / Source
This page has an unusually high amount of pictures and text on it.

**Comment by lancewillett** [comment]
Hi @rantoncuadrado — do you remember seeing any JS errors in the console? Any other details you can provide would be helpful.

**Comment by rantoncuadrado** [comment]
HI @lancewillett 
I can't remember any JS message to be honest but... could it be related to this: https://github.com/Automattic/wp-calypso/issues/9170 ?

**Comment by lancewillett** [comment]
Yes, possibly related. It's hard to proceed without more information on the error, though. Trying to repeat is difficult.

**Comment by rantoncuadrado** [comment]
@lancewillett If you check the other issue, it is said I get to reproduce the problem by copy and paste the post to my test blog. Anyway, I agree with you.
