### ISSUE TITLE
Posts: drafts sidebar doesn't show for 1 draft on Jetpack

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#10550]
#### Steps to reproduce
1. have a Jetpack site with a few published posts and a single draft post
2. set your browser width to "desktop" size, i.e. e.g. 1400px wide
3. go to URL: /posts/SITE

#### What I expected

I expected the list of drafts to be shown on the right OR a tab on the top that would link to my drafts.

#### What happened instead

I got neither and wasn't able to get to my drafts without resizing. 

#### Browser / OS version

Safari Tech Preview Release 20, macOS Sierra 10.12.2.

#### Screenshot / Video

![drafts-not-showing](https://cloud.githubusercontent.com/assets/23619/21844338/766ed9a6-d7ee-11e6-9040-5d3bf2307b4d.gif)

#### Context

Maybe related to #9871?

**Comment by lancewillett** [comment]
See also #1806

**Comment by lancewillett** [comment]
@jobthomas You mentioned you'd seen this recently. Could you add a few notes on how to repeat it? Rebecca C also said she wasn't able to see drafts without going to the URL directly `https://wordpress.com/posts/drafts/example.wordpressc.com`

CC @rachelmcr in case you have more steps to repeat, or further anecdotes if you've experienced it.

**Comment by jobthomas** [comment]
@lancewillett it's not a problem for me at the moment - so difficult to add some notes, but i'll try my best:

* "Drafts" was not a tab option on P2 listed sites
* When using full-width on a large screen it wasn't displaying on the right, like it is now, when looking at posts: ![http://cld.wthms.co/7hZp/5OsZ1Ovm](http://cld.wthms.co/7hZp/5OsZ1Ovm+)

**Comment by rachelmcr** [comment]
I have experienced this with private, multi-user WordPress.com sites (on *.wordpress.com subdomains). I currently still see it with at least a couple sites. However, I have only seen it happen in the WordPress.com desktop app — the same sites where this is a problem in the desktop app show the "Latest drafts" sidebar as expected on the web.

It also isn't consistent for me: it happens on some sites and not others, and the same site may or may not have the problem over time. I feel like it could relate to how many drafts there are and who authored them, but I haven't been able to identify the pattern so far.

**Comment by mtias** [comment]
Drafts has been updated and the filterbar always shows.
