### ISSUE TITLE
External RSS feeds don't display ampersands in the byline

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#10574]
A user reported that external RSS feeds with ampersands in the byline show their numerical character reference in the reader:

<img width="958" alt="screen shot 2017-01-11 at 5 07 24 pm" src="https://cloud.githubusercontent.com/assets/8698879/21870157/a77c4e0c-d820-11e6-914e-a75b3131c8d5.png">

The same doesn't appear to happen with WordPress.com sites: 

<img width="1045" alt="screen shot 2017-01-11 at 5 11 03 pm" src="https://cloud.githubusercontent.com/assets/8698879/21870244/f9312b78-d820-11e6-8c85-0c251916d90e.png">

Reported by a user during live chat.

**Comment by fraying** [comment]
Thanks, @eurello

**Comment by bluefuton** [comment]
The feed in question is https://wpcalypso.wordpress.com/read/feeds/62384476.

**Comment by bluefuton** [comment]
Entities in this particular feed were double-encoded. Fixed in r152765-wpcom (h/t @blowery).
