### ISSUE TITLE
Publicize: radio buttons are invisible when selecting the site to connect

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#10575]
Steps to reproduce:

1. Go to https://wpcalypso.wordpress.com/sharing and select a site if prompted.
1. Click the "Connect" button next to any option (disconnect first if needed).
1. Click "Allow" button.
1. When prompted to confirm the account, check to see if the radio button is visible or not.

<strong>Result:</strong> the radio button for selecting a site is invisible. ([17s](https://cloudup.com/c9KGcbY9xJy))

![screen shot 2017-01-11 at wed jan 11 4 48 23 pm](https://cloud.githubusercontent.com/assets/1119271/21871251/31713b5c-d81e-11e6-90c2-2e73869c8134.png)
<sup>Seen at https://wpcalypso.wordpress.com/sharing/design5279.wordpress.com using Firefox 50.1.0 on Mac OS X 10.12</sup>

Also tested and confirmed using Safari 10.0 on Mac OS X 10.12.

**Comment by lancewillett** [comment]
I believe this is intentional when there is only one account. Feel free to re-open if you think it's a mistake.

Code ref: https://github.com/Automattic/wp-calypso/blob/dc97c60f1465bf56222c0fd61710a35179cefd1d/client/my-sites/sharing/connections/account-dialog-account.scss#L23
