### ISSUE TITLE
.org Plans: setup notice displayed after cancelling Premium

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#10592]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/my-plan/ with a site using a Jetpack Premium Plan.
2. Remove the plan from your site.
3. After confirming the cancellation of your plan, the WordPress.com site switcher includes the following notice:

![screen shot 2017-01-12 at 18 43 57](https://cloud.githubusercontent.com/assets/426388/21901309/7531014a-d8f7-11e6-9adb-9b476f97c866.png)

**Comment by lancewillett** [comment]
Good catch.

**Comment by jeherve** [comment]
I can't seem to reproduce this anymore. Closing.
