### ISSUE TITLE
Image Editor: Clicking outside dialog inconsistent with other modal views

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10594]
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/post
2. Select a site
3. Click Add Media in editor toolbar
4. Select an image
5. Click Edit in dialog toolbar
6. Click Edit Image in preview
7. Click outside editing dialog

#### What I expected

It should close the modal like other views, or at the very least cancel out of the editing experience (see context section below).

#### What happened instead

Nothing.

#### Browser / OS version

Chrome Version 55.0.2883.95 (64-bit)
macOS Sierra Version 10.12.2 (16C67)

#### Context / Source

#8084 is related (cc @retrofox) and perhaps makes the opposite point. While Escape in the context of editing an image might be considered especially destructive in contrast with other modal views, I'd at least expect clicking outside the modal to do _something_, even if it's merely returning to the previous screen (the cancel behavior).

**Comment by retrofox** [comment]
pick up this one. Thanks @aduth.

**Comment by gwwar** [comment]
How does this feel in mobile? I would probably be upset if I lost changes from a bad tap

**Comment by aduth** [comment]
@gwwar There are no outside tappable areas on small viewports; the modal takes up full width and height of the screen.

![Mobile](https://cloud.githubusercontent.com/assets/1779930/22612283/ac4d555a-ea3d-11e6-97ed-7e536ee2d108.png)

**Comment by gwwar** [comment]
Thanks @aduth. We'll give it a shot.

**Comment by iamtakashi** [comment]
I've gone through the steps, and clicking outside of the dark modal closes all modal(s) now. This matches with my expectation.

**Comment by aduth** [comment]
Can confirm appears to be fixed now.

@gwwar @retrofox If you recall which pull request this was fixed, would be good to cross-link for posterity.

**Comment by gwwar** [comment]
Thanks @aduth. @retrofox do you mind linking when you have the chance? I don't recall which PR it was
