### ISSUE TITLE
SEO Settings for Jetpack: link to enable SEO Tools always uses HTTPS

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#10606]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/seo/ and select a Jetpack site using HTTP, where you've purchased a Professional plan
2. You'll see the following notice at the top of the page:

![screen shot 2017-01-13 at 11 27 26](https://cloud.githubusercontent.com/assets/426388/21926721/4c03e544-d983-11e6-8189-0e26d99e14ad.png)

3. The notice redirects you to your site's dashboard, but uses HTTPS instead of HTTP.
4. Same problem with the notice to enable Site Verification Tools, a bit downer on that page.

**Comment by jeherve** [comment]
Same problem for the new Google Analytics module.

**Comment by beaulebens** [comment]
@rodrigoi I'm adding you to this, since it's the same issue that's happening on the Google Analytics module, so would be great to get them both fixed at the same time.
