### ISSUE TITLE
SEO Settings: Front Page Meta Settings are not saved 

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#10607]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/seo/ and pick a Jetpack site using the Professional plan and where you have enabled the SEO module.
2. Enter a custom Front Page Meta Description.
3. Hit the save button. You'll receive a confirmation that your settings were saved.
4. Refresh the page; the custom description you've entered is gone.

This happens regardless of the version of Jetpack you use. It doesn't trigger any warnings or errors on the Jetpack site.

**Comment by vindl** [comment]
Fixed in D3950-code

**Comment by vindl** [comment]
Deployed in r149169-wpcom.
