### ISSUE TITLE
Jetpack Ads: add "Ads" to the Plans Page

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#10605]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/
2. Select a Jetpack site running Jetpack 4.5
3. Plans should include "Ads" as a feature

![screen shot 2017-01-13 at 10 49 26](https://cloud.githubusercontent.com/assets/426388/21925500/04f9aca6-d97e-11e6-8d98-fba6755fdd06.png)

This will also allow [this link](https://github.com/Automattic/jetpack/blob/master/_inc/client/pro-status/index.jsx#L113) to work.

cc @dbspringer

**Comment by dbspringer** [comment]
@richardmuscat @jeffgolenski Any thoughts on what the copy should say? Maybe `monetize your site`?

**Comment by richardmuscat** [comment]
@dbspringer and @jeherve: this is already being taken care of here: https://github.com/Automattic/wp-calypso/pull/10122
