### ISSUE TITLE
Menus broken - "Sorry, this menu item is unsupported and I can't edit it."

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#10614]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/menus/{sitename}
2. Try and add a new menu, then items to it. OR, in an existing menu, add items to a sub-menu/child

#### What I expected

To be able to add items to a submenu, either at the same level as the sub-menu item OR child of the sub-menu item.

OR, be able to add items to a brand new menu.

#### What happened instead

You get an en error message: "**Sorry, this menu item is unsupported and I can't edit it.**" Asking you to visit wp-admin instead.

#### Browser / OS version
Win10, Chrome latest (55).

#### Screenshot / Video
**Screenshot:**

![image](https://cloud.githubusercontent.com/assets/6505293/21931184/e058643a-d9bb-11e6-8b3d-4b943f65dbe8.png)

**GIF, when adding items to sub-menu items:**
![2](https://cloud.githubusercontent.com/assets/6505293/21931197/f5b6adfa-d9bb-11e6-9c50-0fd8b65b0ee0.gif)

**GIF, when adding items to a newly-created menu:**
![1](https://cloud.githubusercontent.com/assets/6505293/21931238/3bb460e0-d9bc-11e6-8772-62de137b448e.gif)

#### Context / Source
Several user reports today, it's a major issue.

#manual-testing, #user-report

**Comment by jerrysarcastic** [comment]
Just a note here that #10615 does not seem to fix the issue for me.  I had a user in chat that was attempting to create a new menu in Calypso, and saw the following:

<img width="754" alt="screen shot 2017-01-20 at 1 44 59 pm" src="https://cloud.githubusercontent.com/assets/1967448/22170388/f191dad2-df20-11e6-83d8-a14fad710015.png">

I SU'd to confirm the behavior, and saw the same message when trying to add tabs to a new menu, and confirmed this in a few test sites as well.  Note that this only seems to affect new menus, as I was able to add tabs to existing menus without issue.

**Comment by youknowriad** [comment]
Should be fixed by #10838
