### ISSUE TITLE
Themes: Proceeding to editor from site-specific theme search results breaks

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10628]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com
2. Navigate to My Sites
3. Click Themes for the selected site
4. Enter a search term
5. In master bar, click "Write"
6. Select a site

#### What I expected

Editor to load correctly.

#### What happened instead

Editor loads, but sidebar is still My Sites sidebar, not the editor sidebar. There's also an error in the console:

>Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

After a few moments the sidebar fixes itself, but trying to click Back or otherwise return to the themes screen breaks the entire application (only master bar shown, no page contents).

#### Browser / OS version

Google Chrome Version 55.0.2883.95 (64-bit)
macOS Sierra Version 10.12.2 (16C67)

#### Screenshot / Video

https://cloudup.com/crUJW2xPnL0

#### Context / Source

p1484335310004985-slack-hyperion

**Comment by folletto** [comment]
I tested on Chrome, bug confirmed.

**Comment by ockham** [comment]
My hunch is that this has to do with single-tree vs multi-tree rendered sections. (`/design` is single-tree, editor is multi-tree).

**Comment by budzanowski** [comment]
Offending commit:
```# first bad commit: [8dc2e5b29fbfb27570d66bfee0ce3ab661cc807d] Add keyboard controls for SiteSelector (#5808)```

**Comment by budzanowski** [comment]
I have pinpointed which change is responsible: https://github.com/Automattic/wp-calypso/pull/5808/commits/c5f6c34e59d0ee37013943e6edc43ff1c060fde8#diff-e29382b074221786efbfb6a76ea07a0fL185

Previously site selection triggered `href` in `<Site>` component. With new implementation redirection goes through `page` here https://github.com/Automattic/wp-calypso/pull/5808/commits/c5f6c34e59d0ee37013943e6edc43ff1c060fde8#diff-e29382b074221786efbfb6a76ea07a0fR151

This should not make much difference.
