### ISSUE TITLE
Stats: Investigate new way to load Google Geoviz

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10623]
From #10476 we had some discussion around key warnings from Google.  @jblz investigated a bit and [noted](https://github.com/Automattic/wp-calypso/pull/10476#issuecomment-272339514) the following:

Interesting. From https://developers.google.com/chart/interactive/docs/basic_load_libs#limitations:

> There are a couple minor but important limitations with how you load Google Charts in versions prior to 45:
> ...
> * For Geochart and Map Chart, you must load both the old library loader and the new library loader.

```
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
```

__Task__
Explore changing how we load the geo viz to match the current standards, and see if we need a key or not.  @aduth has some experience in this area with updating the key logic for contact widgets.

**Comment by aduth** [comment]
>see if we need a key or not. @aduth has some experience in this area with updating the key logic for contact widgets.

It probably depends on whether we'd used the specific API on WordPress.com host previously.

See also: https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

**Comment by timmyc** [comment]
This particular visualization/api has been in use in production since Nov 2015

**Comment by aduth** [comment]
If the API call works, without a key and without any warnings in console, I imagine it should be fine.

**Comment by timmyc** [comment]
Well at times I **do** see key warnings, but many other times I do not see them.

**Comment by aduth** [comment]
>Well at times I do see key warnings, but many other times I do not see them.

Is this always in the same environment? I imagine warnings could crop up for e.g. `calypso.localhost` or `wpcalypso.wordpress.com` hostnames.
