### ISSUE TITLE
Search: Safari is not handling search url links

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1062]
Search urls are supposed to be portable. So you can copy your URL and give it to someone else and it will open search for them. This is not working correctly for me in safari. If I click on this link:

https://wordpress.com/posts/my?s=test

In chrome, it will correctly show the search bar open with the search term and display the correct results.

But in safari, it will initially (for a fraction of a second) show the search bar open with the search term (and conduct the correct request), but then it will immediately re-render without the search open and display the results as if the search was not run.

Steps to repeat:

1. Open Safari, log in to WordPress.com and go to wpcalypso.wordpress.com
2. Go to My Sites, click "All My Sites" at the top of the left-hand navigation, then select Posts
3. At top right, click the Search icon.
4. Type in "test" and hit Enter to search. Note the results.
5. Copy the URL from the address bar.
6. Close the tab, open a new one.
7. Paste in the URL.
8. Safari doesn't show the same result.
9. Try pasting the URL in Chrome or Firefox to compare: it loads the same search results correctly.

**Comment by alisterscott** [comment]
This has been fixed.

![screen shot 2016-04-29 at 10 08 20 am](https://cloud.githubusercontent.com/assets/128826/14905266/728001f6-0df2-11e6-9a5f-335deb89c37d.png)
