### ISSUE TITLE
Stats: Migrate Video Plays to Redux

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10630]
This task involves moving the Videos module data from `stats-list` to `state/stats/lists`.

![stats_ _trout_bummin_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/21943492/4d9eff9e-d986-11e6-98fc-67a29c5bcb9e.png)

__Tasks__
- [x] Create normalizer for referrer data based off the old [stats-parser](https://github.com/Automattic/wp-calypso/blob/master/client/lib/stats/stats-list/stats-parser.js#L551-L580)
- [x] Update the Site Stats component to use `QuerySiteStats` for the `statsVideoPlays` API call

**Comment by youknowriad** [comment]
closed by #10976
