### ISSUE TITLE
General: Migrate common abbreviations to new capitalization guideline

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1065]
In 4306-gh-calypso-pre-oss, a new guideline was added to enforce camel-case variable naming even in cases where abbreviations are used. There's a significant amount of code which does not align with this new guideline, and the common cases can be converted in a semi-automated mass-search replacement.

These include:
- [ ] `URL` -> `Url`
- [ ] `ID` -> `Id`
- [ ] `HTTP` -> `Http`

Others can be added here as they're discovered. The general recommendation for other abbreviations is to gradually update them as changes are made moving forward.

**Comment by blowery** [comment]
The transforms will have to be very careful not to alter fields that are coming from API responses.
