### ISSUE TITLE
Menu item does not reappear after dragging

### ISSUE THREAD

**Issue by andreabadgley** [Automattic/wp-calypso#10655]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/menus/{sitename}
2. Drag a menu item to another place in the menu and drop it in place.

#### What I expected
I expected the menu item display to appear again after dragging and dropping.

#### What happened instead
The menu item remained a grey-blue box and never repopulated.

#### Browser / OS version
Firefox and Chrome in OS X El Capitan 10.11.6.

#### Screenshot / Video
![drag dropped menu item](https://cloud.githubusercontent.com/assets/9036382/21983678/6d53911a-dbc0-11e6-807c-c75de218a8fc.jpg)

#### Context / Source
I noticed this while was #dogfooding over the weekend, and also had a #user-report of it in 3002296-t (if I'm interpreting the customer's question correctly).

**Comment by folletto** [comment]
I can replicate.

**Comment by jeremeylduvall** [comment]
Closed via #10931.
