### ISSUE TITLE
Editor: Cannot scroll in preview in iOS

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#1066]
Reported in 271879-chat (iOS 9.1, Safari 9) and confirmed in iOS Simulator (iPad on iOS 8.2):

![ios-cannot-scroll-preview](https://cloud.githubusercontent.com/assets/227022/11484050/a1b5efaa-9771-11e5-932b-aa13027cb62f.gif)

**Comment by designsimply** [comment]
Thank you for reporting this! Closing as a duplicate of #312.
