### ISSUE TITLE
General: alert dialogs and saving changes

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#10671]
This came up in some user testing.

#### Steps to reproduce
1. Write a post in the editor
2. leave post
3. notice the alert dialog

#### What I expected

User expected that clicking OK would save the changes and navigate away from the page. She did not read the alert thoroughly.

We should change the alert buttons to be more clear. Because this seems to be an alert we use in many places, I suggest we do something generic like:

[Cancel] [Discard] 

For reference here is what we do for trashing, it's more clear

![screen shot 2017-01-16 at 12 48 04 pm](https://cloud.githubusercontent.com/assets/618551/21995596/5e29cfe4-dbeb-11e6-82e8-a5497c491420.png)

#### What happened instead

OK **discards** the change and navigates away from the page.

#### Screenshot / Video

This same dialog is used in Settings and the Editor:

![screen shot 2017-01-16 at 12 47 43 pm](https://cloud.githubusercontent.com/assets/618551/21995508/ed68cc10-dbea-11e6-95bd-182faf6dba96.png)

**Comment by folletto** [comment]
I'm not 100% sure but I think that's a browser dialog and we have no control on it as it's `window.confirm` ([ref](https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=%22you+have+unsaved+changes%22)). That doesn't allow renaming the buttons. 

We can just be more clever on the text copy.

---

Aside:

> [Cancel] [Discard]

`Cancel` on a negative operation can be very ambiguous, especially in languages where "Cancel" and "Discard" can have similar semantics. Italian can have such a problem.

In general, good labels are structured as `Action + Noun`: "Delete post", "Change color", etc, and this rule should be ignored only when it's not possible for any reason (space available, genericness of the label, etc).

As you mention the "Delete" dialog is clearer as it (partially) follows the rules above.

**Comment by drw158** [comment]
Since it's impossible to change the alert buttons, I think this issue can be closed.
