### ISSUE TITLE
Fullpost: More on WP: Spacing issues

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10674]
On the fullpost page, in the More on WP block, when one item has 2-line meta info, and the other has just one line, the spacing is off.

For example:

<img width="1082" alt="screen shot 2017-01-16 at 1 07 02 pm" src="https://cloud.githubusercontent.com/assets/24388/21999039/f0586154-dbec-11e6-9341-cbc0d0a0c698.png">

And:

<img width="1088" alt="screen shot 2017-01-16 at 1 09 39 pm" src="https://cloud.githubusercontent.com/assets/24388/21999068/14c520ae-dbed-11e6-8091-9e39f111f9e6.png">

Note how the story with the 2-line meta info pushes the image down by a few pixels. This happens in both Safari and Chrome. 

What should happen: The images should start at the same place no matter what. This is important because is keeps the text in both sections aligned.

**Comment by fraying** [comment]
@raoulwegat Could you look into this?

**Comment by raoulwegat** [comment]
@fraying I'm on it!
