### ISSUE TITLE
Settings: setting toggle not saved when navigating away

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#10670]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/discussion
2. toggle one of the settings
3. navigate away (click on General)
4. Go back to Discussion tab
5. Setting was not saved, and there was no alert to warn me

#### What I expected

For the setting to be saved, or an alert window warning me that it would not be saved

#### Screenshot / Video

![screen shot 2017-01-16 at 12 27 21 pm](https://cloud.githubusercontent.com/assets/618551/21994836/58ed566c-dbe7-11e6-88b6-a12270e8515b.png)

@tyxla

**Comment by lancewillett** [comment]
Are you suggesting an "are you sure" for unsaved changes? Makes sense to me.

**Comment by tyxla** [comment]
Thank you for the ping, @drw158! I've suggested a solution for this in #10690.

**Comment by drw158** [comment]
Yep, previously there was an "are you sure" dialog. Since the toggle PR, the dialog is no longer present. Thanks for fixing!
