### ISSUE TITLE
Flow: Switching from a dot com site's domains page to a jetpack site's plugins page should not require an intermediary step

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#107]
If you wanted to go from the domains page for a dot com site to the plugins page for a jetpack site you must visit some other section first to facilitate switching sites. This is disruptive to the flow and highly confusing (I only understood what was going on because I work here)

To reproduce:
* visit /domains/some-dot-com-site
* select a jetpack site from the site-picker
* you are redirected to select a different site from the site-selection screen (with no indication why)
* select a dot come site from the list
* you are still at /domains
* switch to /posts or /pages or some other shared section
* switch to your jetpack site
* select /plugins from the sidebar

I think the solution here is to show a Drake image when switching to a jetpack site while viewing /domains. That is what currently happens when you are viewing /plugins and switch to a dot come site. It allows you to switch sections in the sidebar or switch sites (and you aren't confronted with the doorslam of the site selection screen).

**Comment by breezyskies** [comment]
You should see the following when switching to a jetpack site from `/domains/some-dot-com-site`:

![screen shot 2015-12-30 at 8 56 29 am](https://cloud.githubusercontent.com/assets/3011211/12053982/579537ea-aed3-11e5-8bf3-48e4161a76f0.png)

It's been this way for some time, so guessing this issue just never got closed. 

Closing for now (reopen if I misunderstood something).
