### ISSUE TITLE
Spacing issues with click-to-expand photo cards

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10717]
Recent changes have bonked the click-to-expand photo cards. (Problems verified in Safari and Chrome.)

Before expanding, there's not enough space between the end of the photo and the action links. In the screenshot below, the gallery card is correct, the photo card is not.

<img width="849" alt="screen shot 2017-01-17 at 2 42 26 pm" src="https://cloud.githubusercontent.com/assets/24388/22043163/3218a366-dcc3-11e6-8021-db689b19c5fc.png">

After expanding, there should be more space all around. (The usual 20px between photo and action links, 20px between action links and line.) This is what we've got now:

<img width="847" alt="screen shot 2017-01-17 at 2 39 51 pm" src="https://cloud.githubusercontent.com/assets/24388/22043198/66a06ba0-dcc3-11e6-8332-a638989a8e42.png">

Also note that the action links should NOT move for narrow images. They should always be in the same place, no matter the width of the photo.

<img width="864" alt="screen shot 2017-01-17 at 2 44 53 pm" src="https://cloud.githubusercontent.com/assets/24388/22043226/89b70590-dcc3-11e6-95ed-e4c180df9e33.png">

**Comment by blowery** [comment]
cc @jhnstn @samouri @bluefuton
