### ISSUE TITLE
SEO: Google SERP Preview Overrun

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#10723]
#### Steps to reproduce
1. Edit Page.
2. Assign page very long URL
3. Click Preview.
4. Click the SEO tab > Google Search

#### What happened instead

![screen shot 2017-01-17 at 6 50 17 pm](https://cloud.githubusercontent.com/assets/8002138/22047806/617ba338-dce6-11e6-83ee-44cb6ca579f5.png)

The URL is 79 characters (not including https://).

**Comment by dmsnell** [comment]
Thanks @chrisfromthelc for the report. By the way, what is SERP?

**Comment by chrisfromthelc** [comment]
Search Engine Result Page.

**Comment by drw158** [comment]
So the character limit is 79, and currently it can go longer than that in our preview?

**Comment by chrisfromthelc** [comment]
[It looks like we allow up to 196 (not counting domain)](https://chriswsmithbusinesstest.blog/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-phasellus-et-diam-sollicitudin-velit-interdum-pretium-commodo-et-dolor-nunc-aliquet-quam-et-sapien-dapibus-accumsan-a-non-magna-duis-varius-d/). That ends up looking like this in the previewer:

![pwqs6c7sa5](https://cloud.githubusercontent.com/assets/8002138/25551030/fc982ffc-2c33-11e7-8754-b03e71423d71.png)

It looks like Google truncates anything roughly longer than 79 characters (they use pixel width):

![screen shot 2017-04-28 at 5 02 37 pm](https://cloud.githubusercontent.com/assets/8002138/25551081/85954cb8-2c34-11e7-8e97-c4a20f70b60f.png)

Although that original URL was 79 characters, we were not truncating it by pixel width, which seems to be the difference here. I'm unable to find any information on what their max pixel width for URLs specifically is.
