### ISSUE TITLE
Media Section: Add an appropriate icon to the menu item in sidebar

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#10747]
Note: media section is not enabled on prod.

Currently the icon is the default, and we need to add an appropriate icon for the section.

<img width="273" alt="screen shot 2017-01-18 at 17 19 13" src="https://cloud.githubusercontent.com/assets/908665/22075018/4e9f3dda-dda2-11e6-8718-28c00dc50343.png">

There was an idea of porting Dashicons Media to Gridicons (#8619). However, since we decided to use a variation of the "Image" icon for "Add Media" button (https://github.com/Automattic/gridicons/issues/45), we could use the "Image" icon for the sake of consistency, and for the similar reason as "Add Media" icon — image would be the majority of uploaded medias, therefore it sufficiently represents "Media".

<img width="377" alt="screen shot 2017-01-18 at 17 34 29" src="https://cloud.githubusercontent.com/assets/908665/22075628/ba154fee-dda4-11e6-8c62-fbbcc54925a0.png">

<img width="273" alt="media-menu" src="https://cloud.githubusercontent.com/assets/908665/22076788/786561ba-dda9-11e6-929f-6b549c6aa7bd.jpg">

**Comment by drw158** [comment]
I think this is a perfect choice for the media icon. 👍 from me.

**Comment by folletto** [comment]
Design wise: 👍

**Comment by lancewillett** [comment]
👍  Woot, let's get this one in.
