### ISSUE TITLE
Posts: vanishing and appearing featured images

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#10744]
I experienced featured images whilst being set not showing until page refresh. Here is a video to show the problem:

https://cloudup.com/clhW3bkxbSX

This was on Chrome and using a new user site.

**Comment by rachelmcr** [comment]
#bug-scrub

I can no longer reproduce this issue, following the same steps as in the screencast above. I'm closing the issue but please reopen if you still encounter this.
