### ISSUE TITLE
Post Schedule: Inconsistent Time Formats in Post Scheduler

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#10762]
<img width="258" alt="screen shot 2017-01-18 at 22 31 51" src="https://cloud.githubusercontent.com/assets/908665/22086285/fa6bb846-ddcf-11e6-9a39-140ca7a873d8.png">

Initially this issues was raised in #7253 with amongst other issues.

When we have Date and Time format settings in Calypso #10441, we should improve this.

**Comment by retrofox** [comment]
- [ ] add redux selectors to get date and time format
- [ ] Show format time according to the current site setting

**Comment by iamtakashi** [comment]
First attempt:

![4](https://cloud.githubusercontent.com/assets/908665/22836372/092bf58a-efb4-11e6-9da5-4b56735f381b.jpg)

Note: The AM/PM selector should only appear the time setting value has AM/PM
