### ISSUE TITLE
Reader: Slideshow not working in FullPost

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#10763]
<img width="1388" alt="slideshow_in_fullpost_broken" src="https://cloud.githubusercontent.com/assets/4505888/22087061/b6d1eed2-dd90-11e6-82d9-05f6cca8b836.png">

The slideshow in Full Post is not working. Here is a sample 

https://wordpress.com/read/blogs/24738444/posts/8461.

This might be related to [issues/766](https://github.com/Automattic/wp-calypso/issues/766).

**Comment by lancewillett** [comment]
See also #10778

**Comment by lancewillett** [comment]
This should be working again. Props @aduth for sleuthing the cause and proposing the solution.

Deployed on the WP.com side with r149947-wpcom

> There's a few places in Calypso where we've hard-coded a reference to the now-removed jquery.cycle.js:
> 
> Reader: https://github.com/Automattic/wp-calypso/blob/4b9697a/client/components/embed-container/index.jsx#L32
> 
> Editor slideshow gallery: https://github.com/Automattic/wp-calypso/blob/fcf789e/client/components/gallery-shortcode/index.jsx#L68
> 
> At least in the case of the editor, the intent was to allow galleries to work for Jetpack site previews without loading the script from the Jetpack site (because HTTPS mixed content).
> 
> It's fine enough to update those links, but in the meantime, do you think we should temporarily restore the file (even the minified version)?

**Comment by lancewillett** [comment]
<img width="1162" alt="screen shot 2017-01-27 at 09 39 21" src="https://cloud.githubusercontent.com/assets/66797/22378921/800eef18-e474-11e6-8c06-3bfcfd3a7f1d.png">

Confirmed working in Safari on macOS.
