### ISSUE TITLE
Themes: Current Theme Bar and Theme Sheet Broken for Retired Theme

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#10760]
First reported by @meremagee in Slack a while ago for a site that uses a retired theme:

![current-theme-bar-broken](https://cloud.githubusercontent.com/assets/96308/22085877/50d3a940-ddd6-11e6-881c-c35fe69f751f.png)

This is a regression stemming from our Redux arch refactor (#8785). We're now always fetching theme data from the generic wpcom themes endpoint (as opposed to the site specific one) in order to not store what are largely identical sets of theme data for each individual site of a user, but that list doesn't include retired themes.

I can see two possible strategies to fix this:
1. Merge data received from the active-theme endpoint into our `themes` Redux tree. That endpoint however doesn't currently include all attributes, so we cannot obtain all data needed e.g. for the theme sheet. We could however extend it to return that data (maybe with a separate `?extended=true` flag or whatever the convention here is).
2. Do a separate per-site query in case `wpcom` doesn't have any data. I wonder where we'd store that one theme then -- I don't think it can go to a site specific Redux subtree, since all other (non-retired) themes will still live in the `wpcom` subtree. So it'd have to go there, too.

Seems like retired theme info should live in the `wpcom` subtree either way then.

I think I'm leaning towards strategy no 1 right now.

**Comment by ryanboren** [comment]
I experienced this with Ecto.

![screen shot 2017-01-06 at 2 36 19 pm 31227b0b55d145f3a51fa941d89c0650](https://cloud.githubusercontent.com/assets/2047747/22114197/29d45abc-de2e-11e6-8efd-1b05d08cd283.png)

Related: Finding a theme to replace Ecto was work, work that I didn't want to do. This message could make some theme suggestions.

<img width="634" alt="screen shot 2017-01-06 at 3 49 27 pm 39039ece046740d78a94906c00799c38" src="https://cloud.githubusercontent.com/assets/2047747/22114252/6afa5f50-de2e-11e6-8b5a-8f185eda46fd.png">

**Comment by ockham** [comment]
I wonder if instead of what I'm suggesting above 😉  we should really change our `QueryTheme` component and `requestTheme` action to use the `siteId` instead of `wpcom` for wpcom sites. We'd want information still to be stored in the `wpcom` Redux subtree, but there shouldn't be any harm in _fetching_ it from the actual site -- this should give us retired themes in the QueryManager's `items` (where theme sheets, and the current theme bar can find them), but not in its `queries`, so they won't show up in the themes list.

(We might want to strip the `active` and `purchased` attrs off in normalization.)

FYI and RFC @seear and @budzanowski

**Comment by seear** [comment]
Regardless of site ID, all retired themes were removed from the v1.2 endpoint in r135057-wpcom, so we're going to have to change the endpoint or use a different one.

**Comment by ockham** [comment]
Hmm, right. So actually, it should be enough to use the theme details endpoint (so we have that information available for theme sheets), and I think there's no harm in having it return information for retired themes.

And for the Current Theme Bar, maybe we can just use the _active theme_ endpoint and [`patch`](https://github.com/Automattic/wp-calypso/tree/9d8979b83ea094d9dfc653c5947fd62b17f13475/client/lib/query-manager#usage) the corresponding theme item.

**Comment by seear** [comment]
> and I think there's no harm in having it return information for retired themes.

Yes, I agree.

**Comment by ockham** [comment]
Right now, it 404s for a retired theme BTW.
@folletto Any reason to not change the theme details endpoint to return theme info for retired themes? As outlined above, they won't show up in themes lists -- the user needs to know the theme ID in order to be able to look them up.

**Comment by folletto** [comment]
> Any reason to not change the theme details endpoint to return theme info for retired themes?

I can't think of any reason to not do that.

**Comment by ockham** [comment]
Cool, I'll pursue this route then.
