### ISSUE TITLE
Happychat: Update "WP.com" heading to "Support Chat"

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#10768]
The heading at the top of Happychat currently says "WP.com" but this shorthand is not something we normally use in a user-facing way. Instead, we should update this text to "Support Chat," which is also more generic to cover future uses of Happychat in Calypso outside of WordPress.com support.

It looks like this text can be found [here](https://github.com/Automattic/wp-calypso/blob/9e618041868aa4a2b8f5028b469769855f8fab06/client/components/happychat/index.jsx#L65).

Thanks to @andrewspittle for bringing this up. I've assigned this to myself to try to fix this week :)

**Comment by andreabadgley** [comment]
How about "Chat with a Happiness Engineer" or something that plays into our cool title?

**Comment by kriskarkoski** [comment]
> How about "Chat with a Happiness Engineer" or something that plays into our cool title?

@jasmussen has some ideas for how to that in in an intro message I think we'll be adding soon.
