### ISSUE TITLE
Happychat: "Ask a question..." prompt is too specific

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#10767]
After starting a chat with WordPress.com support the chat text prompt is "Ask a question..." but this is too specific since the user may be asking a question, answering a question from support, or just making a statement. We should update this placeholder to be more generic to cover the varying situations.

I haven't put much thought to what to replace it with yet, but will see what I can come up with or +1 other suggestions if someone beats me to it.

cc @andrewspittle who reported this in Slack

**Comment by andrewspittle** [comment]
If we start with "Ask a question..." we could then switch to something relatively basic like "Type and press Enter..."

**Comment by kriskarkoski** [comment]
Since we're already asking them to write the question on the contact form we could probably mimic the HUD with something like "Type a message..." (I removed Enter since there's also a send button to send the message. Here's what the HUD message looks like: 

![screen shot 2017-01-19 at 11 49 05 am](https://cloud.githubusercontent.com/assets/1900444/22116092/6af73154-de3d-11e6-9f58-5e51060742f9.png)

**Comment by andrewspittle** [comment]
That seems fine to me.
