### ISSUE TITLE
Sharing: Warning when adding second connection obscured

### ISSUE THREAD

**Issue by joendotcom** [Automattic/wp-calypso#10769]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing
2. Add a Facebook connection
3. Try to add another Facebook connection

#### What I expected

Warning with icon shows saying:
"The connection marked {{icon/}} will be replaced with your selection"
Via @aduth, from here:
https://github.com/Automattic/wp-calypso/blob/5912817/client/my-sites/sharing/connections/account-dialog.jsx#L156

#### What happened instead

A warning icon is partially visible, no warning text visible.

#### Browser / OS version
Chrome Version 55.0.2883.95 (64-bit) / OS X 10.11.6

#### Screenshot / Video
https://cloudup.com/cfILAnQr7qh
(Note: icons and names removed, partial warning left intact)

https://cloudup.com/ccxfC5amitG
Another account with some relevant HTML + showing broken images.

#### Context / Source
We'd also love to know how you found the bug: #manual-testing

**Comment by alisterscott** [comment]
I noticed this same visual issue today:

<img width="529" alt="visual issue" src="https://cloud.githubusercontent.com/assets/128826/24983111/59578df4-2028-11e7-9036-02e94db03268.png">
