### ISSUE TITLE
Comments: add a block with recent comments on the stats page

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#10779]
Improves viewing and engaging with your site visitors via comments.

At the moment we show comments in posts list and in Reader stream for your site, but there is no central place to see all the latest comments across your posts.

Task is to create a block that displays all recent comments across your posts in the Stats landing page.

**Comment by drw158** [comment]
Insights seems to be the most logical place for this. There is a comments block at the bottom.

![screen shot 2017-02-17 at 10 41 23 am](https://cloud.githubusercontent.com/assets/618551/23074202/bc88ed42-f4fd-11e6-9a06-687e82006d3a.png)

**Comment by pixelhandler** [comment]
@lancewillett @drw158 perhaps the dropdown which is already present in the Site -> Stats -> Insights -> Comments block should have a default choice of "Recent". Recent comments from both posts and pages, in descending order, could be listed below the dropdown (limit to 10 items, only include comments, and exclude ping types of comments). 

I'm curious if a "read more" link below the (limited) list of recent comments should link to the blog's comments admin page, e.g. "https://<blog-name>.wordpress.com/wp-admin/edit-comments.php?user_id=<user-id>"

<img width="473" alt="stats-most-recent-comments" src="https://cloud.githubusercontent.com/assets/17178/23584263/d7bbe604-0110-11e7-80ab-fa34ebf7ff63.png">

**Comment by pixelhandler** [comment]
@roundhill @rodrigoi I have a few questions about working on this update. I reviewed the client app code and created a branch [update/blog-stats-recent-comments] with some `TODO REVIEW` comments. 

My initial throughts are… add a new filter for `recent-comments` in the state, `StatsComments.state.activeFilter` as default:  'recent-comments'. And, update the `normalizers.statsComments` to support the recent comments data. I could start with the test for `client/state/stats/lists/test/utils.js` for `statsComments()`. My best guess is that the `sites/name/comments` API is already in use; no new request to setup. However, I'll need to figure out how to configure the API request.
  	
In looking over the code I noted these questions…

1. Is this the API to use: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/comments/ ?
1. Update data in: client/state/stats/lists/utils.js - `statsComments( data, query, siteId, site )` ?
1. Add a new style for a "mange comments link": my-sites/stats/stats-comments/style.scss `.stats-comments__tab-content {}` ?
1. Add new test for recent comments in: client/state/stats/lists/test/utils.js `describe( 'statsComments()', () => {` ?
1. Normalizer finds `statsComments` using `getSiteStatsNormalizedData`, Should the devdocs have info ? http://calypso.localhost:3000/devdocs/selectors?search=getSiteStatsNormalizedData
1. Page to update: `client/my-sites/stats/index.js` and `client/my-sites/stats/stats-comments/index.jsx` ?
1. Is there a test for `stats-comments` block?
1. How do I use i18n to add a "Recent Comments on Posts & Pages" dropdown option?

[update/blog-stats-recent-comments]: https://github.com/Automattic/wp-calypso/compare/master...pixelhandler:update/blog-stats-recent-comments

**Comment by drw158** [comment]
Here is a rough sketch of what I'm thinking:

![fullsizerender 3](https://cloud.githubusercontent.com/assets/618551/23630477/7d866092-0278-11e7-9175-d1b6fec9f0ec.jpg)

The Comments block will display a list of recent comments of the entire blog by default. A segmented control allows the user to see the existing data, "Comments by authors" and "Comments by Posts & Pages".

The caret icon at the top would go to a non-existant page that would list all comments in greater detail, and allow for moderation.

It is strange that Comments have no value in terms of stats, and this would break that convention on this Insights page. Every other section has some sort of quantifiable metric.

I do think this page will become a sort of dashboard, so maybe this is the first step.

**Comment by pixelhandler** [comment]
@drw158 ah yeah that layout does make much more sense, showing the comments vs list of posts and comment counts. I agree it's less "stats" oriented but the block does the job of surfacing the recent comments.

**Comment by drw158** [comment]
I think there is value in adding a block to Insights, but comments are readily accessible via the sidebar menu. Until we create a dashboard like page, I'll keep this closed.
