### ISSUE TITLE
Framework: Logged out views without sidebar off-center

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#1077]
#302 was meant to fix some layout issues that were caused by the docked sidebar. But, it looks like that PR didn't address logged out views, specifically in the `/start` and `/accept-invite` sections.

cc @shaunandrews 

![screen shot 1](https://cloud.githubusercontent.com/assets/1126811/11488136/e6d9fe2e-9789-11e5-8fd9-e0f4d3539a58.png)

![screen shot](https://cloud.githubusercontent.com/assets/1126811/11488118/cd129adc-9789-11e5-963f-007f4786765d.png)

**Comment by scruffian** [comment]
Connected to https://github.com/Automattic/wp-calypso/issues/901
