### ISSUE TITLE
Comments: show comments for a single post in the stats permalink for a post

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#10780]
Show `<Comments>` for a single post in the stats permalink for a post.

**Comment by drw158** [comment]
Current single post in stats

![screen shot 2017-02-17 at 10 37 44 am](https://cloud.githubusercontent.com/assets/618551/23074031/2a302ee2-f4fd-11e6-83d4-eae8994035d5.png)

**Comment by drw158** [comment]
We decided to implement comments in a single post view in /Comments. I don't see much reason to do it in Stats now.
