### ISSUE TITLE
Reader: support additional styling tags (feature-request)

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#10790]
As @kristastevens said in https://github.com/Automattic/wp-calypso/pull/10784#issuecomment-273859492, it would be pretty cool if Reader allowed for emphasis and bold tags.

Has this already been discussed elsewhere? Good idea / Bad idea?

**Comment by fraying** [comment]
These were left out of the refresh on purpose. The design already has to wrestle with lots of voices and lots of variety. Allowing bold and italics would increase noise and open us up to gamers who bold their entire posts. Strongly against this.
