### ISSUE TITLE
Don't allow a break before or after text in excerpts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10791]
Here's a gallery card for a post where the excerpt starts with a break. (I thought we were preventing this already, but this one slipped through?)

<img width="847" alt="screen shot 2017-01-19 at 11 43 39 am" src="https://cloud.githubusercontent.com/assets/24388/22122475/ff033ace-de3c-11e6-91ef-74c8d427f79d.png">

URL: https://wordpress.com/read/feeds/1792967

**Comment by fraying** [comment]
See also: 

<img width="838" alt="screen shot 2017-01-19 at 12 03 52 pm" src="https://cloud.githubusercontent.com/assets/24388/22123146/65db68c8-de3f-11e6-9d54-6e3e8542eee6.png">

We shouldn't allow breaks when there's nothing after them, either.

https://wordpress.com/read/feeds/22973954

**Comment by fraying** [comment]
First example is fixed now. Second is still broken.

**Comment by raoulwegat** [comment]
FWIW, there's no break in the second example – just a `<p></p>` around the excerpt.

![screen shot 2017-02-09 at 12 30 21 pm](https://cloud.githubusercontent.com/assets/2627210/22767399/19c599e0-eecf-11e6-93c5-8862355333d9.png)
