### ISSUE TITLE
Stats: Navigation component complaining of invalid prop type on empty sites cache

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#108]
Minor thing, but it looks like the `site` prop is coming through as a `boolean` at least sometimes (always does for me when loading stats with a clean localStorage).

> Warning: Failed propType: Invalid prop `site` of type `boolean` supplied to `exports`, expected `object`. Check the render method of `StatsSite`.

If this is expected, the `propTypes` should declare so like:
```
diff --git a/client/my-sites/stats/stats-navigation.jsx b/client/my-sites/stats/stats-navigation.jsx
index b4b8e0e..9dea455 100644
--- a/client/my-sites/stats/stats-navigation.jsx
+++ b/client/my-sites/stats/stats-navigation.jsx
@@ -14,7 +14,10 @@ var SectionNav = require( 'components/section-nav' ),
 module.exports = React.createClass( {
        propTypes: {
                section: React.PropTypes.string.isRequired,
-               site: React.PropTypes.object
+               site: React.PropTypes.oneOfType( [
+                       React.PropTypes.object,
+                       React.PropTypes.bool
+               ] )
        },
 ```

If it's not expected, we should prevent passing in a non-object :)

This seems to be happening in other scopes:

```
Warning: Failed propType: Invalid prop `sites` of type `array` supplied to `AllSitesIcon`, expected `object`. Check the render method of `AllSites`.
```

When loading /stats/day/`site-name` and clean localStorage.

**Comment by designsimply** [comment]
Tested clearing localStorage and viewing /stats/day/`site-name` and was unable to see the "Failed propType" warning. 

Checked the code and it appears the `propTypes` are now being declared as you recommended, see https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/stats-navigation/index.jsx#L17-L20 

Looks like it was fixed in `039b1d6` props @jblz @timmyc
