### ISSUE TITLE
Media Section: Make action bar look pretty

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#10805]
Raised by @folletto, Media Section currently uses the same header design as the media modal, and it's inconsistent with other sections in Calypso.

Smaller issues to make before completing this:
- https://github.com/Automattic/wp-calypso/pull/11560

Let's add the action bar shown (2nd row) in the mocks. See #11508 for the storage component.
Related #11056

- Drop down for Add New, also contains "Add Via URL"
- Clicking on "Add Via URL" update the action bar to this state:
![actionbar](https://cloud.githubusercontent.com/assets/1270189/23223677/8868b33a-f8e0-11e6-98f9-3ef8fde8a247.png)
- Selecting an item, makes the edit/delete button appear
- Clicking on edit takes us to the details view

https://github.com/Automattic/wp-calypso/issues/10805#issuecomment-276094743

**Section (No-selection)**

![section-default](https://cloud.githubusercontent.com/assets/908665/22428967/e675dcec-e700-11e6-8776-6cb208e09eae.jpg)

**Section (Selected)**

![section-selected](https://cloud.githubusercontent.com/assets/908665/22429023/19147e7e-e701-11e6-8972-fbed091a1168.jpg)

**Section (When you scroll the page. `StickyPanel` component)**

![desktop](https://cloud.githubusercontent.com/assets/908665/23168705/fae79264-f840-11e6-98d0-6c4ef77d23f9.jpg)

**Modal (No-selection)**

![modal-default](https://cloud.githubusercontent.com/assets/908665/22429041/2bf2633a-e701-11e6-94b3-a9add1b78622.jpg)

**Modal (Selected)**

![modal-selected](https://cloud.githubusercontent.com/assets/908665/22429049/3b9f004a-e701-11e6-9b2e-774f8c5764ff.jpg)

**Small Screens**

![9a5dfde4-e890-11e6-80d2-b7a48b8b83b7](https://cloud.githubusercontent.com/assets/908665/22536037/d3d8e2b2-e8f6-11e6-82c6-8986d5460cb3.jpg)

**Comment by iamtakashi** [comment]
A small correction: The buttons "Add ~" should be grouped buttons rather than two separate ones. And "Add New" should come first.

<img width="163" alt="screen shot 2017-01-20 at 22 45 01" src="https://cloud.githubusercontent.com/assets/908665/22168517/0bc57532-df65-11e6-87fc-424dacba474f.png">

**Comment by iamtakashi** [comment]
Mobile:

![media-section-mobile](https://cloud.githubusercontent.com/assets/908665/22168576/7474c5f6-df65-11e6-9ea6-93f11e03c63c.jpg)

**Comment by folletto** [comment]
> A small correction: The buttons "Add ~" should use ButtonGroup rather than two separate buttons. And "Add New" should come first.

Good solid suggestions.

I'd even say: can we use the "mobile" compact version on desktop too? I'm not sure if we have data, but I'd expect for "add with URL" to be less used, as well as generally troublesome for copyright reasons.

**Comment by iamtakashi** [comment]
> I'd expect for "add with URL" to be less used, as well as generally troublesome for copyright reasons.

My expectation is the same. And good point on the potential abuse. I'll see if there is any usage data to consider to retire.

**Comment by iamtakashi** [comment]
@folletto 

I guess you only suggested to use the mobile version with a chevron, not to retire :facepalm: 

Anyway, the usage is 6% of all uploads which isn't large so it's safe to use the mobile version as default.

I've noticed we use icons in "add" buttons in both People and Plugins sections. Would you say we should follow the pattern here?

![add-button](https://cloud.githubusercontent.com/assets/908665/22270199/6c87b5be-e286-11e6-81cd-96e6a0ba50bb.jpg)

**Comment by folletto** [comment]
> I've noticed we use icons in "add" buttons in both People and Plugins sections. Would you say we should follow the pattern here?

Yes. With two notes:

1. I'd try to use the same icon we use in the Editor to open the media panel, as even if it's in a different location, it has the same semantics of "Add Media".
2. I'd keep the label at least on desktop size, as icon+label is always the clearest.

**Comment by iamtakashi** [comment]
I've spent some time to explore other header designs for the section as well as the Media modal. 

The focuses are:
* To have an action bar that allows you to (bulk) edit / delete at the top of the section.
* To display a plan storage.
* To have some consistencies in actions between the section and the modal.
**Section (default, pre-select)**

![section-default](https://cloud.githubusercontent.com/assets/908665/22303129/c1718fa2-e329-11e6-955d-eb97619f8ae2.jpg)

**Section (Once some media is selected, the edit/delete buttons will be enabled)**

![section-selected](https://cloud.githubusercontent.com/assets/908665/22303147/d694b95e-e329-11e6-8c8b-c08f2ad2c50b.jpg)

**Modal (default, pre-select)**

![modal-default](https://cloud.githubusercontent.com/assets/908665/22304607/07cfa050-e330-11e6-8eb5-c8becc547771.jpg)

**Modal (Once some media is selected, the title and "Add New" button will be hidden, and action buttons appear)**

![modal-selected](https://cloud.githubusercontent.com/assets/908665/22304778/c4b87f98-e330-11e6-861f-514cee2a4400.jpg)

Related discussion #9136

**Comment by melchoyce** [comment]
The floating filter bar/plan info feels really weird. What's the reason behind floating vs. combining into one solid background?

**Comment by drw158** [comment]
Nice, this is much better. I'll just comment on the original image in the issue. 

I'd rather see the counter applied to the filter bar.

![screen shot 2017-01-25 at 1 28 38 pm](https://cloud.githubusercontent.com/assets/618551/22305735/435799d0-e302-11e6-9cb2-c03a80fe3b26.png)

This would allow the add buttons to be relocated to that space. Traditional we have aligned buttons to the far right in the section headers, but I think in this case it should break that pattern, because the add buttons are so important.

**Comment by iamtakashi** [comment]
> What's the reason behind floating vs. combining into one solid background?

@melchoyce, That would be cleaner, but I'm worried that that would make the PlanStorage less clickable and would devalue the purpose.

> I'd rather see the counter applied to the filter bar. This would allow the add buttons to be relocated to that space.

@drw158, Yes that's precisely why I took this approach on the latest design. I kept "Add Media" buttons on the right though. It's tricky to coordinate action button locations because the most important button would be different in the Section, Modal, and its state.

**Comment by folletto** [comment]
Excellent exploration! I think it's heading in the right direction.

The only thing I think has to be reviewed for sure is what Mel pointed out above: the "detached" bar feels very outside Calypso patterns. I understand completely why you did that, let's find a way to balance off the two. :)

More granular feedback at a lower priority:

1. Yes to the counters on the filter bar. They can be very useful. I reckon we don't have the API yet for that, but it's something that has to be done as it's a Calypso pattern to show the counters there.
2. Yes to the add new with icon and dropdown. That feels both solid and scalable.
3. I think we can drop the "Media Library" title everywhere. It's really redundant as it's already obvious what's open.
4. The plan storage button afaik is used only there, and we can refactor it. If we for example remove the border and add an icon (for example `(i)`) it would provide the same functionality and linkage to Plans. Actually, with an icon, might even be more explicit. Can be even a small button stating "Add more" on the side. Regardless, I think we can refactor `<PlanStorage>` as it's unique.
5. Delete could be just the trash icon, as it's a relatively secondary action, the icon is fairly universal, and we don't want to click that by accident.
6. I'd rather hide the controls when unused than show them disabled. Making them appear will make also more evident they have appeared.
7. Calypso modals have all the "actions" to dismiss at the bottom. I'm not sure how to solve that.

Idea/Brainstorming building up from your mockups: it seems to me we have these "semantic" areas:

1. Media item controls (Add, Edit, Delete)
2. Size controls
3. Modal controls (Insert, Cancel)

We could do:

Page + No Selection:
```
[ Add | \/ ]                       [ –size slider– ]                             
```

Page + Selection:
```
[ Add | \/ ] [ Edit ] [ Del ]      [ –size slider– ]                             
```

Modal + No Selection:
```
[ Add | \/ ]                       [ –size slider– ]           [ cancel ] [ insert ]
```

Modal + Selection:
```
[ Add | \/ ] [ Edit ] [ Del ]      [ –size slider– ]           [ cancel ] [ insert ]
```

With something like this we show the controls only if something is selected together with the existing media item control add, and everything else is always in the same position.

**Comment by folletto** [comment]
_While writing I also had an idea to solve the modal pattern point 7 above:_

With this semantic split, then seems to me (if I haven't missed anything) that the modal controls (Cancel, Insert) show up only on Modal. Which is good, as it means we can show the bottom bar only on modal! :) 

Page + No Selection:
```
[ Add | \/ ]                                                        [ –size slider– ]
```

Page + Selection:
```
[ Add | \/ ] [ Edit ] [ Del ]                                       [ –size slider– ]
```

Modal + No Selection:
```
[ Add | \/ ]                                                        [ –size slider– ]
```
```
                                                                [ cancel ] [ insert ]
```

Modal + Selection:
```
[ Add | \/ ] [ Edit ] [ Del ]                                       [ –size slider– ]
```
```
                                                                [ cancel ] [ insert ]
```

**Comment by iamtakashi** [comment]
Excellent feedback as always. Thanks @folletto.

Good to know that we can refactor the PlanStorage style. Let’s do that. When we combine all at the top, the order would be like this, wouldn’t it?

`[Filters]   [planstorage]   [Search]`

Also removing the “Media Library” title is a great idea. This opens up more ideas for the buttons’ locations such as your suggestion, which I agree with.

We’re nearly there.

**Comment by folletto** [comment]
I'm glad it's helpful! 👯 

> When we combine all at the top, the order would be like this, wouldn’t it?

That seems a good approach, let's see how it works. :)

**Comment by iamtakashi** [comment]
Some ideas for PlanStorage. Any feedback at this point?

<img width="491" alt="screen shot 2017-01-27 at 01 03 06" src="https://cloud.githubusercontent.com/assets/908665/22356887/759f227a-e42c-11e6-8c01-96b9bd887730.png">

**Comment by folletto** [comment]
I like cog/arrow as they take less vertical space (i.e. I'm imagining fitting in our default height white bar).

However, "Manage" is far clearer imho. So I'd go with manage's design. :) 
Have you thought changing "Manage" to "Upgrade", as that's in practice what it's about?

**Comment by iamtakashi** [comment]
You've described exactly the dilemma I had :) It's going to be tight but the third one is the most clear.

Yes, I've considered "Upgrade", but I thought we can use "Manage" universally across all the plans including the top, Business plan when you don't have something to upgrade.... We could just hide it in that case though. I'm open to any wording we think the best.

**Comment by folletto** [comment]
> We could just hide it in that case though.

I agree here, I would hide it because the space is "Unlimited" so I wouldn't show the badge at all. Also because you can't really manage anything once you're at Business. :D

**Comment by iamtakashi** [comment]
> I would hide it because the space is "Unlimited"

A good point. Let's go for "Upgrade", and hide it all together for Business plan.

**Comment by iamtakashi** [comment]
A or B?

![screen-shot-2017-01-27-at-22 45 19](https://cloud.githubusercontent.com/assets/908665/22390538/882762ec-e4e3-11e6-91a0-48260a7f27d8.jpg)

**Comment by melchoyce** [comment]
B

**Comment by iamtakashi** [comment]
Here are the updated design.

**Section (No selection)**

![media-section](https://cloud.githubusercontent.com/assets/908665/22393770/125b31e2-e506-11e6-8583-41441d7ea1ce.jpg)

**Section (Selection)**

![media-section-selected](https://cloud.githubusercontent.com/assets/908665/22393778/1fe0dab0-e506-11e6-9152-d62594bae0d7.jpg)

**Modal (No selection)**

![media-modal](https://cloud.githubusercontent.com/assets/908665/22393782/386f2848-e506-11e6-9a9a-29c6cd0346e2.jpg)

**Modal (Selection)**

![media-modal-selected](https://cloud.githubusercontent.com/assets/908665/22393783/3eb4b164-e506-11e6-92e1-3f1756f1924e.jpg)

Note & Question: The "Add New" button changes to a secondary button once you select some media because "Edit" (or "Insert") is likely the action you'd take. Also it'd avoid two primary buttons sit next to each other. I haven't seen this kind of behaviour in Calypso yet. Should the button stay as  a primary all the time?

**Comment by folletto** [comment]
I think that's a winner. Let's do this. 💯 

> The "Add New" button changes to a secondary button once you select some media because "Edit" (or "Insert") is likely the action you'd take. Also it'd avoid two primary buttons sit next to each other. I haven't seen this kind of behaviour in Calypso yet. Should the button stay as a primary all the time?

I agree. My first approach there would be:

On Section:

* "Add new" is never primary (white)
* "Edit" is primary (blue)

On Modal:

* "Add new" is never primary (white)
* "Edit" is never primary (white)
* "Insert" is primary (blue)

This is probably not perfect, but matches the idea of having only one single primary action on each page.

**Comment by iamtakashi** [comment]
> My first approach there would be: [...] but matches the idea of having only one single primary action on each page.

OK, this avoids changing the rank of "Add New" button and enforce the idea of having one primary button on a page. Users have already clicked "+" to come to the modal anyway.

> So we could take it [Plan's name] out and put "size + Upgrade" on the same line. What do you think?

Good idea!

So, here is what we have and it's likely to be ready to be built 🎉 

I'll make a separate task for updating the modal.

**Section (No-selection)**

![section-default](https://cloud.githubusercontent.com/assets/908665/22428967/e675dcec-e700-11e6-8776-6cb208e09eae.jpg)

**Section (Selected)**

![section-selected](https://cloud.githubusercontent.com/assets/908665/22429023/19147e7e-e701-11e6-8972-fbed091a1168.jpg)

**Modal (No-selection)**

![modal-default](https://cloud.githubusercontent.com/assets/908665/22429041/2bf2633a-e701-11e6-94b3-a9add1b78622.jpg)

**Modal (Selected)**

![modal-selected](https://cloud.githubusercontent.com/assets/908665/22429049/3b9f004a-e701-11e6-9b2e-774f8c5764ff.jpg)

**Comment by folletto** [comment]
Amazing. Works great for me. 💯  💘

**Comment by iamtakashi** [comment]
> Now: mobile? :D

:) A quick mockup with questions.

* I'm slightly concerned the compact buttons on small screens because they might be too small for tap. We don't seem to change compact buttons to be larger on any other places but I was wondering if there were past discussions on the topic.

* We currently hide the Plan Storage on the modal for small screens. Should we continue to hide it? I'm having a hard time to find a reasonable spot for this. 

![mobile](https://cloud.githubusercontent.com/assets/908665/22475229/33e2fcbe-e7d6-11e6-926d-225509d3a546.jpg)

**Comment by folletto** [comment]
> I'm slightly concerned the compact buttons on small screens because they might be too small for tap. 

Give it a try on _My Sites → People_. The combination of size+padding make the button big enough to work well even when it's just an icon. :)

> We currently hide the Plan Storage on the modal for small screens.

I'm ok in keeping it hidden. Space is very important on mobile, and it won't be a regression either.

👍  👍  on all of the above then, let's go for it!

**Comment by iamtakashi** [comment]
W00t. Thanks a lot for your help!!

**Comment by iamtakashi** [comment]
I've realised I forgot to mention what would happen when you scroll the section. 

The action bar will be sticky once it reaches the master bar. It's a `StickyPanel` component. Although it seems to be broken at the moment, we can see it's been used in Themes.

![desktop-scroll](https://cloud.githubusercontent.com/assets/908665/22571721/dec53ae8-e998-11e6-9602-438752ee42d1.jpg)

**Comment by rralian** [comment]
Do you think it would be helpful to retain the category selection when a user scrolls down? Right now we leave the action buttons, but the category selections scrolls out of view. Maybe we could show that as a dropdown in the action bar when it gets to that point?

**Comment by folletto** [comment]
It's a good point. I don't feel it's overly important as it's likely someone starts searching before triggering the selections, but it's surely something we can review once this is live. :)

**Comment by iamtakashi** [comment]
That's a good question. If we want to keep the categories visible all the time, we probably would want to keep the entire `SectionNav` with the search, so that keep "navigation" and "action" two separate things just like the modal. I initially concerned about the vertical space left for media since we would have 3 sticky elements including the master bar, but it might just be fine as the media modal does already. 

![desktop2](https://cloud.githubusercontent.com/assets/908665/23168750/28d6ace6-f841-11e6-9242-efc5ef5d583e.jpg)

**Comment by iamtakashi** [comment]
I wish I could see real time updates for comments here :)

**Comment by folletto** [comment]
I think two bars always visible while scrolling is a bit too much. The modal can do that because it's a modal, so it's a different pattern. Even if that wasn't the case, the modal isn't taller as it doesn't have the masterbar, so the vertical space is still equivalent of two bars (a little more on non-mobile screens).

![screen shot 2017-02-21 at 14 50 17](https://cloud.githubusercontent.com/assets/4389/23169834/2216e912-f845-11e6-9da8-145351434d0e.png)

**Comment by iamtakashi** [comment]
I was thinking to make the bars unstick smaller than 660px. For mid ~ large screens, one thing to note is that we don't have the bottom action bar in the section, and that would make the vertical space available roughly the same.

![image](https://cloud.githubusercontent.com/assets/908665/23170508/46c7c946-f847-11e6-8a45-741fe9b90ffb.png)

However, I'm open to the idea of launching the section with one sticky (the action bar) and revisiting later to see we need to make the section nav sticky.

**Comment by folletto** [comment]
That's true, good point. :y:

**Comment by gwwar** [comment]
We might need to break this into smaller technical issues.
