### ISSUE TITLE
Sharing: Add tooltip for disabled Share button on Posts page

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#10807]
#10332 got partially fixed by graying out Share button when Publicize is completely turned off on Jetpack Sites with #10772.

![screen shot 2017-01-19 at 10 54 14](https://cloud.githubusercontent.com/assets/699132/22102023/241ef3c2-de36-11e6-9e4a-c30879df8faa.png)

@beaulebens suggested also to:

>  I’d expect to maybe have a panel slide down that tells me I need to enable Publicize to use this feature (bonus points; allow me to enable it right there).

Another solution would be to use`<InforPopover />` component to display information why this button is disabled and maybe toggle which would allow to enabled Publicize again. It was also proposed by @beaulebens in one of the previous comments. See https://github.com/Automattic/wp-calypso/pull/10331#issuecomment-269987746.

![screen shot 2017-01-20 at 10 01 28](https://cloud.githubusercontent.com/assets/699132/22142699/88fef708-def7-11e6-9237-28eb1e0c4847.png)

**Comment by alisterscott** [comment]
The share button doesn't appear at all any more for Jetpack sites with publicize disabled, so closing this issue:

<img width="772" alt="screen shot 2017-12-21 at 9 27 11 am" src="https://user-images.githubusercontent.com/128826/34233451-31c91f3a-e631-11e7-82a7-5654e9c1adff.png">
