### ISSUE TITLE
Sites List: SiteIndicator for "updates available" doesn't show on active site

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#10832]
If you have a Jetpack site with updates available (e.g. plugin updates), then we "badge" the site in the sites list, like this (yellow circle indicator):

![screen shot 2017-01-20 at 2 38 38 pm](https://cloud.githubusercontent.com/assets/108942/22166522/ad7ae0de-df1e-11e6-94eb-e0fc825d7e3a.png)

Ironically, if you have that same site active, then we don't expose that information:

![screen shot 2017-01-20 at 2 38 33 pm](https://cloud.githubusercontent.com/assets/108942/22166526/b1a17ea2-df1e-11e6-8104-d4b499b060ca.png)

I think we used to, and that we probably should.

**Comment by beaulebens** [comment]
Definitely a regression. I noticed while testing [this PR](https://github.com/Automattic/wp-calypso/pull/10570) that the indicator _does_ appear there.

**Comment by alisterscott** [comment]
I can confirm this has been fixed now:

<img width="296" alt="screen shot 2017-07-31 at 2 07 58 pm" src="https://user-images.githubusercontent.com/128826/28762418-b3b68cd8-75f9-11e7-9744-e52c368a7626.png">
