### ISSUE TITLE
Reader: full post view, image inside a reblogged post is misaligned

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#10831]
Reported by @eliorivero in Slack: p1484944115004854-slack-calypso

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/27083162/posts/1266004208

#### What I expected
Image not to be aligned over text in the Reader single post, full view.

#### What happened instead
The image inside a reblog is off. This is like this in Calypso desktop app as well. It looks ok in iOS app though.

#### Screenshot

<img width="305" alt="misalignment_720" src="https://cloud.githubusercontent.com/assets/66797/22165386/bc7fe6e8-df18-11e6-81f5-64c1a5313714.png">

#### Browsers
Chrome 55.0.2883.95 in El Capitan
WordPress 2.10-beta3

The link to the site is https://stephencwinter.com/2016/12/19/faith-and-fantasy-tolkien-the-catholic-the-lord-of-the-rings-and-peter-jacksons-film-trilogy/

**Comment by gwwar** [comment]
Investigating further the misbehaving image has a Calypso only class on it `media-library__list-item-centered`.
![screen shot 2017-01-20 at 1 23 43 pm](https://cloud.githubusercontent.com/assets/1270189/22166357/88f122a4-df15-11e6-9630-7c0409bf990b.png)

We should investigate to see if it is currently possible to create post content from the Calypso editor.

See also https://www.tinymce.com/docs/configure/content-filtering/#extended_valid_elements if we need to whitelist attributes.

**Comment by eliorivero** [comment]
Looks ok now as can be seen in the image below.

<img width="802" alt="captura de pantalla 2018-01-11 a la s 14 51 29" src="https://user-images.githubusercontent.com/1041600/34839018-f23d9b0c-f6de-11e7-981a-47540f782bca.png">

Closing.
