### ISSUE TITLE
Import: Console warning when starting import

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#10845]
#### Steps to reproduce
1. Starting at URL: `/settings/import/` on a dev build of Calypso
2. Click on `Start import` for WordPress importer
3. Upload a test export file
4. Click on `Start import again`
5. Notice the warning message in console 

#### What I expected

No warning messages in console.

#### What happened instead

![560b64e4-de2a-11e6-88b6-d3b436c2f924](https://cloud.githubusercontent.com/assets/1182160/22200986/f109b736-e161-11e6-8f0a-6887d3f070e5.png)

**Comment by lancewillett** [comment]
I couldn't repeat this, testing with the same steps in Mac-n-Chrome and a WP.com Simple site.

![screen shot 2017-09-06 at 09 54 14](https://user-images.githubusercontent.com/66797/30124240-68307406-92e9-11e7-8ff6-d0e4bce9f400.png)
