### ISSUE TITLE
Media Section: Can't select more than one media (2 Points)

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#10851]
Partial task to make sure we can select more than one item in the list view of the media section.

One of the main use cases of the section is to maintain and organise all media on a site. With this in mind, users should be able to bulk edit and delete. However, not like the media modal, you can't select more than one media in the section at the moment.

![untitled](https://cloud.githubusercontent.com/assets/908665/22210240/0aad53b8-e181-11e6-943b-7ce976af9d9f.gif)

Although we're still trying to figure out the best place for "Edit" and "Delete" buttons in the section ([ref.](https://github.com/Automattic/wp-calypso/issues/9136#issuecomment-273955347)), users should be able to select more than one media.

**Comment by iamtakashi** [comment]
Noting the checkmark needs to be replaced with a number like the modal.

<img width="265" alt="screen shot 2017-01-23 at 15 33 40" src="https://cloud.githubusercontent.com/assets/908665/22210397/a002450e-e181-11e6-80d5-b8a67db93b5d.png">

**Comment by gwwar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test A Link](https://trello.com/c/6FJwT3Yc/1-test-a-link)
