### ISSUE TITLE
Media: Preview image is hidden or tiny when you edit it on small screens

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#10859]
This seems to be an intermittent issue, and I wasn't able to figure out when exactly this happen. In some cases, the preview image is really tiny or hidden when you edit it in small screens.

<img width="382" alt="screen shot 2017-01-23 at 17 57 36" src="https://cloud.githubusercontent.com/assets/908665/22216193/fe7816f4-e195-11e6-923d-07ebca35cfdc.png">

With a quick css inspect, I can see `flex-basis` is set to `0%` for `.editor-media-modal-detail__preview-wrapper` (The last value in `flex` shorthand), and that's probably why it's collapsed sometime.

The previous/next arrow only appears when you're editing more than one image, but regardless, the wrapper should always be more than the height of the arrow (46px).

**Comment by iamtakashi** [comment]
I can constantly replicate this issue on my iPhone (Safari, Chrome) and the emulator in Chrome dev tools.

**Comment by retrofox** [comment]
I could replicate the issue using chrome inspector as well.

**chrome - mobile mode: iphone 6**
<img src="https://cloud.githubusercontent.com/assets/77539/22509959/ebb1ef38-e86e-11e6-9f78-874c8133649f.png" width="200px" />

It doesn't happen if the viewport is narrowed, though.

**chrome - viewport width: 335px**
<img src="https://cloud.githubusercontent.com/assets/77539/22509949/e519ba98-e86e-11e6-92a6-52f24986dd55.png" width="200px" />

**Comment by iamtakashi** [comment]
@retrofox Thanks for the sanity check.

> It doesn't happen if the viewport is narrowed, though.

I assume your browser height was quite tall when you tested. How about if you make the browser height shorter, say 700px. Would the preview start shrinking and result tiny image?

**Comment by iamtakashi** [comment]
This is how it appears with 370(w) x 700(h) viewport (Chrome)

<img width="377" alt="screen shot 2017-02-01 at 21 55 10" src="https://cloud.githubusercontent.com/assets/908665/22528085/a89547c6-e8c9-11e6-90fd-39713db00d53.png">

I'm almost sure we need to give some default height for the wrapper with `flex-basis` for small screens. I'll make a patch :)
