### ISSUE TITLE
Question: Are there any docs for building a custom theme on top of Calypso? 

### ISSUE THREAD

**Issue by zsawaf** [Automattic/wp-calypso#10869]
Hey guys,

I just came across Calypso, awesome work! 

I've been reading about Calypso and looking over the source code for the past couple hours, and I tried finding docs with regards on how to build a custom theme on top of Calypso, but I couldn't find much. 

Can anyone point me in the right direction? 

Thanks in advance!

**Comment by lancewillett** [comment]
Hi @zsawaf — could you share more details? What do you mean by a custom theme: skinning Calypso to your own style, or something else (like a WordPress theme)?

Our [CSS guidelines](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md) explain a bit of the process for adding your own styles, but we haven't considered or made a documented step-by-step guide to changing the design entirely.

**Comment by zsawaf** [comment]
Hi @lancewillett, thank you for getting back to me. 

Apologies my question was vague. I meant developing a wordpress theme that can be used by calypso, not customizing calypso itself.

**Comment by lancewillett** [comment]
Calypso is a replacement for wp-admin UI. It doesn't change the front-end of a WordPress site.
