### ISSUE TITLE
Editor: no embed preview for Polldaddy polls

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#10866]
#### Steps to reproduce
1. go to the editor, visual tab
2. copy/paste http://polldaddy.com/poll/9645082/ into the editor

notice this is the only thing that appears:

![screen shot 2017-01-23 at 3 04 33 pm](https://cloud.githubusercontent.com/assets/618551/22222698/6ae4e4d4-e17d-11e6-83fc-d9773ef2d2b1.png)

#### What I expected

If you do the same steps in the wp-admin editor, you can see the embed:

![screen shot 2017-01-23 at 3 06 26 pm](https://cloud.githubusercontent.com/assets/618551/22222731/8ad245a2-e17d-11e6-8b40-30cffd164fc8.png)

#### Context / Source

#1505 is the same problem I think

also #1640 

Safari and Chrome latest

**Comment by lancewillett** [comment]
Ran into this broken flow today — I was adding a few polls to an internal a8c P2 post, and couldn't get them to preview in the visual. Was frustrating because I wanted to see the layout without continuously opening the post in an overlay or external preview tab.

**Comment by Copons** [comment]
This is currently working for me:

![mar-27-2017 16-42-30](https://cloud.githubusercontent.com/assets/2070010/24365003/6a917590-130c-11e7-8e6e-d8fb1d134fe7.gif)

The in-editor preview doesn't work when pasting the shortcode (that on Polldaddy is actually the WordPress.com recommended method), though.

**Comment by drw158** [comment]
That's strange @Copons, when I follow the steps in my post, I'm still getting the same bug. I even tried the URL that you show in your gif. 

I wonder why it works for you?

**Comment by lancewillett** [comment]
See also #1729

**Comment by alisterscott** [comment]
I couldn't insert and see the Polldaddy preview:

![polldaddy](https://user-images.githubusercontent.com/128826/36135359-5edf1a9a-10d6-11e8-848b-c2fd6810febd.gif)

#bug-scrub #pre-gutenburg-bug-purge

**Comment by lancewillett** [comment]
Closing as the embed behavior will change in the upcoming Gutenberg editor experience.
