### ISSUE TITLE
Stats: Refactor StatsDetailMonths to Accept Different Data Sources

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10871]
`<StatsDetailMonths/>` is used currently on Post detail pages to render the "Months and Years" and "Average per Day" tables:

![wordpress_com](https://cloud.githubusercontent.com/assets/22080/22224223/c6dba68e-e172-11e6-844c-ae45646f815c.png)

The logic currently relies on an old `stats-list` implementation, but more importantly, it is very much tied to the concept of displaying Views for a post from both the data source and the (i) info bubbles.

The same table formats are used in Atlas and Old Stats to show the total number of visitors by month, and average visitors by month:

![my_stats_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/22224576/fa629534-e173-11e6-8807-2856349484f0.png)

It would be nice if we could simplify `<StatsDetailMonths/>` to just accept an array of data to render in the month/year format so we can utilize for both use cases.

**Comment by youknowriad** [comment]
I don't think the post View Data are normalized, so it won't be that easy to use this for other stats. But do you think of a page where we could add one of these?

**Comment by timmyc** [comment]
Correct I don't think we normalize the data currently.  Perhaps we could create some selectors to parse the data correctly into a format like:

```
{
  2015: {
    1: 0,
    2: 2,
    ...
  }, 
  2016: {
    1: 0,
    2: 2,
    ...
  },
}
```

**Comment by youknowriad** [comment]
@timmyc Do you think of a particular usecase for this? What stats would you like to show like this? Refactoring would be easier with a usecase :) ?
