### ISSUE TITLE
ERROR in ./client/... and Module build failed

### ISSUE THREAD

**Issue by praneethkumarpidugu** [Automattic/wp-calypso#1087]
Hi All After I run the $make run command

I got the following traceback whenever I try to tweak the development server which is http://calpyso.localhost:3000

ERROR in ./shared/lib/formatting/decode-entities/browser.js
Module build failed: Error: EMFILE, open '/var/folders/rm/9gk6btjs0q5dpzm8vtf6z6qh0000gn/T/50d5c37616bd0d456409da7266d304bd2b744154.json.gzip'
 @ ./shared/lib/formatting/index.js 14:13-41

ERROR in ./shared/lib/wpcom-undocumented/lib/site.js
Module build failed: Error: EMFILE, open '/var/folders/rm/9gk6btjs0q5dpzm8vtf6z6qh0000gn/T/6de7bb933447db4f6a509c45043ff66989f2aa87.json.gzip'
 @ ./shared/lib/wpcom-undocumented/lib/undocumented.js 21:11-28

ERROR in ./client/components/domains/register-domain-step/index.jsx
Module build failed: Error: EMFILE, open '/var/folders/rm/9gk6btjs0q5dpzm8vtf6z6qh0000gn/T/b48d2656bd01cb6638ade230b86748bfa8d2d978.json.gzip'
 @ ./client/my-sites/upgrades/domain-search/domain-search.jsx 18:25-75

ERROR in ./client/components/site-icon/site-icon.jsx

Module build failed: Error: EMFILE, open '/var/folders/rm/9gk6btjs0q5dpzm8vtf6z6qh0000gn/T/d9d1f8e73ea1af3dbfb3360b076e162b2401e373.json.gzip'
 @ ./client/reader/full-post/index.jsx 35:15-46

ERROR in ./client/lib/store-transactions/index.js
Module build failed: Error: EMFILE, open '/var/folders/rm/9gk6btjs0q5dpzm8vtf6z6qh0000gn/T/f71165ff587619c38f665dbcd29dc4927b3936bf.json.gzip'
 @ ./client/my-sites/upgrades/checkout/checkout.jsx 19:23-56

Do I need to install any additional modules other than git, node, nodejs ?

**Comment by aduth** [comment]
Hi @praneethkumarpidugu !

Two things to check:

- Ensure that you have correct permissions for the directory to which you've cloned the project
- This may be related to an issue where the number of files opened by the build process exceeds the system maximum, which is [described in our troubleshooting guide](https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md#emfile---too-many-open-files). You may need to do a search for the steps to increase this if you are not using Mac OSX.

**Comment by praneethkumarpidugu** [comment]
I have checked my directory I have right permissions. sorry if I'm going off the point, but I just check my hosts file it has the two local hosts i,e 
```shell
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
127.0.0.1 calypso.localhost
```
I normally use 127.0.0.1 localhost for one of my django projects. Would you recommend to delete the first localhost ?

**Comment by aduth** [comment]
@praneethkumarpidugu : No, you should be able to leave both entries in your hosts file.

Are you running OSX? If so, can you try entering `ulimit -n 3072` in your Terminal and try again? If that helps, you can make the fix permanent by adding the line to your `~/.bash_profile` file.

**Comment by praneethkumarpidugu** [comment]
Yes I'm using OSX. The Problem has not yet been solved. I have all dependency packages installed, edited hosts file, did the ulimit command but still just have logo appearing in the front.

**Comment by aduth** [comment]
@praneethkumarpidugu : Looks like progress! Two more items to check:

- Can you ensure that you're logged in to [WordPress.com](https://wordpress.com), then refresh the local Calypso page?
- If the above doesn't help, can you confirm whether there are errors in your browser's developer tools console?

**Comment by praneethkumarpidugu** [comment]
Yes I did logged in the wordpress. Now this time I'm unable to see even the MySites, Reader icon, new post, display picture, notification icon. Also I got like a 1553 lines of traceback in the terminal.
http://dpaste.com/10ZASN7

**Comment by aduth** [comment]
Hey @praneethkumarpidugu , glad to hear that you were able to get it working. From the first pastebin in your latest message, it still appears to be the "Too many files" error I had noted above from our troubleshooting guide:

https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md#emfile---too-many-open-files

If you hit the error again, I'd recommend looking through the guide above and perhaps following the permanent steps if `ulimit` is not working for you:

http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/#Mac-OS-X

**Comment by praneethkumarpidugu** [comment]
sorry for the confusion that traceback was few hours before I re-installed node, npm etc. Now I dont have that traceback :)
