### ISSUE TITLE
Drafts written in mobile are synced, but not reflected in Calypso UI

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#10875]
#### Steps to reproduce
This was noticed with a Jetpack site.
1. load `https://wordpress.com/posts/%your.blog%` in desktop browser (I used Chrome)
2. compose a post in the mobile app (I used iOS)
3. in app, go to Options > Status and set as Draft.
4. go back and Save

#### What I expected
<img width="448" alt="captura de pantalla 2017-01-23 a las 22 58 12" src="https://cloud.githubusercontent.com/assets/1041600/22230983/8c279a8c-e1bf-11e6-8084-c16d407a2348.png">
In Calypso in desktop browser, I expected the nav bar tabs in Publish > Blog Posts to be updated to show `Drafts ( 1 )` so that I could switch to it and continue composing my post in the browser.

#### What happened instead
<img width="381" alt="captura de pantalla 2017-01-23 a las 22 58 24" src="https://cloud.githubusercontent.com/assets/1041600/22230989/91682b06-e1bf-11e6-8ac7-1cdb42373bcc.png">
The nav bar was never updated. I can't access the drafts through the UI.

## Update 02-25
Turns out it seems to be some bug with the Drafts sidebar not showing up when it should:
![missingdrafts](https://cloud.githubusercontent.com/assets/1041600/22315574/48064686-e346-11e6-96b1-a236201be841.gif)
If you create a draft inside the web version, the drafts sidebar shows up. But when you do it from the mobile app, it doesn't.

#### Observations
- It's worth noticing that the data is synced: if I go to `https://wordpress.com/posts/drafts/%your.blog%` I can see the draft and the nav bar looks like the screenshot in the **What I expected** section.
- After editing the entry in Calypso in web browser, I don't see the changes in the mobile app. I have an outdated draft without the latest changes made in Calypso web.
- The desktop app displays the drafts in the nav bar correctly.

#### Browser / OS version
Chrome 55 / El Capitan
WordPress.com app / iOS 10.2

#### Context / Source

#dogfooding #workflow #painpoint

**Comment by rachelmcr** [comment]
#bug-scrub

I retested this issue with the steps above and can no longer reproduce. The drafts section appears in the nav bar on a site with no drafts, and after saving a draft in the app I can open that drafts section in the browser to see the saved draft immediately.
