### ISSUE TITLE
Stats: Display Sparkline Data on Insights

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10888]
In #10370 the sparkline was added to the Calypso sidebar - which shows a small visualization of traffic over the last 48 hours for a given site.  Historically, users could mouse over this visualization ( then in the masterbar ), and the highest number of visitors per hour was displayed.

The current image does give a brief glimpse at traffic to a site, but it provides no context about the quantity - which is a bit frustrating to users ( 824423-f ).

Ideally, it would be nice if we could display this data within stats in a manner that would allow users to evaluate the traffic easier.  This could re-use our existing chart, or could possibly be a table as well.  We would need to consider the sad panda nature of this chart for sites that do not get much traffic.

At this time there isn't an API endpoint to return hourly data, so we would need to extend the visits endpoint, or possibly add an array to the base `/stats` endpoint to return the hourly data.

**Comment by jamiepalatnik** [comment]
Hourly data requested in 2077706-zen.
