### ISSUE TITLE
Reader: Edit List heading is too close to the nav

### ISSUE THREAD

**Issue by Kuzmanov** [Automattic/wp-calypso#1089]
"Edit List" should have more padding on top, so it can be in line with the sidebar content.

https://wordpress.com/read/list/{user}/{slug}/edit

![edit list](https://cloud.githubusercontent.com/assets/359845/11497650/a83863d6-981a-11e5-91bf-fa1588c441d8.png)
Spotted on all browsers.

**Comment by Tug** [comment]
Thanks for reporting this @Kuzmanov!
This screen is not in Calypso yet though so i guess it will be fixed when it is added ;)

**Comment by Kuzmanov** [comment]
Yes, I've noticed that when I tried to find it in the code, but it turns out I was redirected to WP.com :)

**Comment by lancewillett** [comment]
Closing since this will be addressed in the future.
