### ISSUE TITLE
Editor: The Sticky Panel is overlapping the nav

### ISSUE THREAD

**Issue by Kuzmanov** [Automattic/wp-calypso#1090]
Steps to reproduce:
1. Go to Editor
2. Resize to 660px - 960px
3. Scroll
4. The sticky panel is going over the nav bar

![sticky-panel-over-nav](https://cloud.githubusercontent.com/assets/359845/11498191/2e81a940-981e-11e5-9f5e-1a3baf7a003c.png)

I'm guessing this is added so the text below the panel will not be visible when scrolling.

**Comment by Tug** [comment]
@Kuzmanov: Can you add the browser you used?

I was not able to reproduce on Chrome and Firefox.

**Comment by Kuzmanov** [comment]
@Tug Chrome 46.0.2490.86 (64-bit) on OS X 10.11.1

**Comment by Tug** [comment]
Oh my mistake! I can reproduce.
