### ISSUE TITLE
Photo Cards with long titles go too wide

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10901]
When a photo card has a very long title, the card gets too wide.

For example: https://wordpress.com/read/feeds/44233981

![sdfgsdf](https://cloud.githubusercontent.com/assets/24388/22267428/9620c3aa-e238-11e6-9779-4a8677dfc6a1.png)

Note where the action links stop. That's where the photo card is supposed to stop.

I know we fixed this before, but it's back.

@bluefuton @samouri: Do you remember how we fixed this before?

**Comment by jancavan** [comment]
I'm unable to repro this, but I found a different issue and addressed it here: https://github.com/Automattic/wp-calypso/pull/12891

**Comment by fraying** [comment]
Fixed!

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/12891
