### ISSUE TITLE
Stats: Add Last Updated Time Stats

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#10911]
From pKdGS-181-p2 - In old stats, a timestamp at the top of the page denoted the time that the stats displayed on the page were last updated.  At one point early in Calypso Stats, we attempted to re-create a similar timestamp on stats pages, but due to the various stats-lists and dozens of `render()`s on a stats page, it proved difficult.

We currently do not track the time each `state/stats/list` tree was last updated, but perhaps we could implement some tracking in the state tree level, or maybe track changes of the data in a state variable in `connected-list`?

@youknowriad any thoughts on the best way to track this?

Some of the user requests are specifically around the chart data, so perhaps we could start there.

**Comment by youknowriad** [comment]
Yep, we could definitely track the last requested date on the state tree by stat query I guess. 
But sometimes there are different components (Queries) on the same page, that would make it a bit difficult to show a timestamp by page.

**Comment by youknowriad** [comment]
Maybe we could add a "time" icon with a hover showing this date for each component instead of at the top of each page?

**Comment by timmyc** [comment]
> Maybe we could add a "time" icon with a hover showing this date for each component instead of at the top of each page?

I was kind of thinking the same thing.  And yes since the data can update independently, per module it is kind of a difficult design task.
