### ISSUE TITLE
Help: items should have external link icon and target

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#1092]
The first two items in the help section should use the "external-link" component, or add the external gridicon and target blank:

![image](https://cloud.githubusercontent.com/assets/548849/11498320/2125297e-981f-11e5-9497-76d6248d7a92.png)

It's more important for the desktop app, but we have been trying to signal all items that lead to non-Calypso areas with it.

cc @nprasath002 @dllh

**Comment by dllh** [comment]
Merged the fix.
