### ISSUE TITLE
People: Show a "Back to Settings" button on email followers page

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#10948]
We've introduced a "View Your Email Followers" link, in site settings for Discussion.
Clicking that brings you to `/people/email-followers/$site`

As a small enhancement, we should include a back button on that page to take us back to settings.

**Comment by rickybanister** [comment]
There is no 'back' arrow or header 'cake' on the Email Followers page so in this case I think we should let users rely on the browser's back button. 

I'm going to close this issue, sorry Rocco!
