### ISSUE TITLE
Stream Pixels for v0 of Attention Metrics

### ISSUE THREAD

**Issue by xyu** [Automattic/wp-calypso#10946]
We want to be able to Track attention minutes so that we can do things like read time computations and engagement tracking. This has been an idea kicked around for a while by @timmyc, @blowery, and many others on the Data team.

As a first step we're going to try and build a stream processor in the backend to do the state tracking needed for computing something like this at a meetup in early Feb. In order to have some data to process we will need a PR that contains something that will send heartbeat pixels for us to process.

After chatting with @blowery it seems like we will need a component that when mounted will request `//pixel.wp.com/s.gif` on a timer. This pixel should probably have a `user_id` or unique identifier and a `blog_id` / `post_id` / `feed_id`. For this initial component valid post / feed ids are probably not strictly necessary.

**Comment by xyu** [comment]
@blowery let me know if you need more info or if I failed to capture anything.

**Comment by timmyc** [comment]
Will the attention metric / component also be usable for front-end page views?  That is likely the most critical place to gather this data.  

Not sure if it is possible, but would there be any option to obtain an "active users on site" metric from this system?

**Comment by xyu** [comment]
> Will the attention metric / component also be usable for front-end page views?

This is something we will need in the future for sure, even for something like just read time would require us to put this in the Reader, front-end pages, archive pages, etc. I'm not sure what Ben had in mind about the initial component. Right now we (Structure) would be satisfied with anything that will send heartbeat pixels when loaded on a page.

> Not sure if it is possible, but would there be any option to obtain an "active users on site" metric from this system?

That's a great idea! The general gist of the backend right now is that these heartbeat pixels gets streamed / sent to Kafka and we then have Spark Streaming apps that read these messages to do the state tracking and then produce another stream of results. So we can easily add another independent Spark Streaming app that reads from the same Kafka stream to produce counts of active users every say minute and output that in addition to attention minutes.

**Comment by blowery** [comment]
@xyu any idea where we might fit this in over 2018? still want to do it?

**Comment by blowery** [comment]
Closing for now.
