### ISSUE TITLE
Unable to map domains by clicking "map it"

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#10947]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/sitename.com
2. Try to map any domain or subdomain and click "map it".

#### What I expected

To be taken to the next page and finish the mapping.

#### What happened instead

Nothing happens -- nothing in the console either.

#### Browser / OS version

Win10, Chrome latest. Tested by others, too.

#### Screenshot / Video

![bug](https://cloud.githubusercontent.com/assets/6505293/22304334/cb32e110-e358-11e6-890d-c63d957e8de3.png)

#### Context / Source
#manual-testing

Mapping functionality is currently broken, unless you choose the last option that appears in the suggestions list, to "Map" a domain.

**Comment by lancewillett** [comment]
Good find – could you try to capture JavaScript console errors as well?

**Comment by ehti** [comment]
@lancewillett @jeremeylduvall looks like it's been worked on in #10902 as well, by @umurkontaci .

> could you try to capture JavaScript console errors as well

Nothing there for me.

**Comment by jeremeylduvall** [comment]
Ah good catch @ehti. I think we can probably leave this one open, but I'll assign @umurkontaci as it looks like his changes will address this issue. That way, he can close it when the PR is merged.

**Comment by lancewillett** [comment]
Fixed with https://github.com/Automattic/wp-calypso/commit/c45fcb98710b4f3ab516470e19789c1530d51695

**Comment by umurkontaci** [comment]
@lancewillett Thanks, I forgot to track this one down
