### ISSUE TITLE
Site Settings: Be specific when saving Jetpack settings

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#10950]
In testing out new work that is currently happening for Jetpack site settings, I came across a strange experience.

In 'Discussion' settings, I tried clicking "Save Settings" in the "Subscriptions" tab, and received this error message:
"There was a problem saving your changes. Please try again."

In digging deeper, I found this in the response from the remote site:
"Error: Options not updated: social_notifications_like, wpcom_publish_comments_with_markdown. Extra info for social_notifications_like: The requested Jetpack module is inactive.. Extra info for wpcom_publish_comments_with_markdown: The requested Jetpack module is inactive"

I went to wp-admin for my site, and enabled all the modules mentioned and the error message, returned to calypso and clicked "Save Settings" again, and it worked as expected.

In a slack conversation with @tyxla , I learned that this because `wrapSettingsForm` saves all settings, not just the ones you've changed, and that the remote site will throw an error if we are changing settings for non-active modules.

Ultimately, I'd expect that when i change my subscription settings, and click "Save Settings", an error message thrown by other modules would not interupt the process.

To replicate:
1. go to calypso.localhost:3000/settings/discussion/$site, where $site is a connected Jetpack site running the latest master
2. make sure the "Likes" module for that $site is deactivated
3. Change your "Subscription" settings in calypso, and click "Save Settings"
4. Note the error message

**Comment by tyxla** [comment]
Thanks for reporting this @roccotrip.

I've suggested a fix for this in #10971, I'd appreciate a review and testing, thank you!
