### ISSUE TITLE
Editor: GitHub Gists are not displayed in visual mode

### ISSUE THREAD

**Issue by mattm** [Automattic/wp-calypso#1095]
If you paste in a Github Gist URL such as this one:

https://gist.github.com/mattm/e56e6456d54563294028

Then in visual mode it only displays half of a caret:

<img width="263" alt="screen shot 2015-12-01 at 6 27 53 am" src="https://cloud.githubusercontent.com/assets/44436/11499549/ce1af490-97f4-11e5-824f-3e3f0cf27dc2.png">
 
HTML mode does include the URL:

<img width="719" alt="screen shot 2015-12-01 at 6 29 03 am" src="https://cloud.githubusercontent.com/assets/44436/11499561/dabb7206-97f4-11e5-8772-a897e53b8af5.png">

**Comment by lancewillett** [comment]
This is *sort of* fixed and working and *sort of* not perfect UX.

I can add the gist to Visual post editor textarea, and as reported — just the caret shows.

If I save and publish or preview, it shows up correctly.

If I switch to HTML mode and back to Visual it shows up correctly.

Screencast:
![gist-visual](https://cloud.githubusercontent.com/assets/66797/14360827/089ae31a-fcad-11e5-9249-74feffef2ec7.gif)

Final post is here: https://testerlance.wordpress.com/2016/04/07/test-post/ — it the gist looks good there.

**Change needed**: make the visual embed work immediately after pasting it into the textarea.

**Comment by lancewillett** [comment]
Closing in favor of #1640
