### ISSUE TITLE
Reader shortcut 'j' and 'k' skip over in-stream recommendations

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#10960]
The keyboard shortcuts 'j' and 'k' skip over the in-stream recommendations in the Follow stream. Is this intended?

![reader_keyboard_shortcuts_recommendations_skip](https://cloud.githubusercontent.com/assets/4505888/22314979/fcdacb32-e318-11e6-9000-fbb2327dda7f.gif)

**Comment by fraying** [comment]
For now, yes, it's intended.
