### ISSUE TITLE
Media: Make delete prompt scarier

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10982]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/post
2. Select a site, if prompted
3. Click Add Media in the editor toolbar
4. Select one or more media items
5. Click Delete

#### What I expected

Indication that the media I'm deleting will be removed from all existing content on the site.

#### What happened instead

A confirmation prompt is shown, but it's not particularly scary. And while it warns that the media is being deleted permanently, I might not realize this affects existing posts and pages.

#### Screenshot / Video

![image](https://cloud.githubusercontent.com/assets/1779930/22352755/749c0640-e3eb-11e6-9d9e-3f52e7acd925.png)

#### Context / Source

p2UL9c-3dH-p2

Summary: update prompt to look like:
![image](https://cloud.githubusercontent.com/assets/908665/23162248/19ab2c54-f825-11e6-90c3-fa8cf18a312b.png)

**Comment by iamtakashi** [comment]
I'd love to hear suggestions from the experts :)

**Comment by designsimply** [comment]
Question: can we add a trash bin similar to what we have for posts so that the first step for deleting media is not permanent?

**Comment by designsimply** [comment]
Dang. I think getting the copy right on this one is harder than it looks. I don't think it's quite right yet, but here is a first pass:

> Are you sure you want to permanently delete these items? If the items are referenced online, deleting them here will cause broken image references elsewhere.

**Comment by aduth** [comment]
>Question: can we add a trash bin similar to what we have for posts so that the first step for deleting media is not permanent?

TIL there is such thing as media trashing, but [it is disabled by default](https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/default-constants.php#L98-L99). Not something we can control from the Calypso side of things. Would be curious to check the current behavior when this constant is active, though I expect it'd be rare to expect a user to have gone through the trouble of enabling it.

**Comment by iamtakashi** [comment]
> I'd love to hear suggestions from the experts :)

I've added the label, but just in case, I'm pinging the pros. @Automattic/editorial Thanks in advance!

**Comment by benhuberman** [comment]
Thanks for the ping @iamtakashi -- for some reason the label hasn't sent us a notification as expected.

Here's another stab at the copy here:

> Are you sure you want to delete this item [these items]? It [They] will be permanently removed from all other posts and pages that currently use them.

^^ I'm assuming we can tweak the copy as indicated based on whether it's one item or multiple ones. Let me know if that's not the case and I might make some tweaks.

**Comment by iamtakashi** [comment]
Thank you, @benhuberman. I like it!

> [...] from all other posts and pages [...]

The only thing is that since we have custom post types, maybe it's safer to use something post type name agnostic term rather than "posts" and "pages". I'm not sure what's best. We have a similar conversation in #10466 and "item" was suggested there, but that wouldn't work here, unless we change the term used in the previous line to "media". Do you think that would work?

**Comment by benhuberman** [comment]
That's a good point, thanks @iamtakashi. 

What if we keep **items** for whatever the user is in the process of deleting, but use **locations** to be more agnostic re: content type(s)? In other words...

> Are you sure you want to delete this item [these items]? It [They] will be permanently removed from all other locations where it [they] currently appears [appear].

Personally, I'd avoid "media" here if possible, or make it into "media file" for more clarity (though that might also get a bit long).

**Comment by iamtakashi** [comment]
> What if we keep **items** for whatever the user is in the process of deleting, but use **locations** to be more agnostic re: content type(s)?

This is much better than my suggestion :) Thanks @benchilcote!

**Comment by benchilcote** [comment]
I think you meant @benhuberman :)  ☝️ ☝️ ☝️ So many Bens.

**Comment by iamtakashi** [comment]
Oops, sorry about that!

**Comment by rralian** [comment]
@iamtakashi Is this just a straight wording change, or are we using different buttons or colors?

**Comment by iamtakashi** [comment]
Good point! We could use `is-scary` buttons that says "Delete". With the suggested copy, the dialog would look like this.

![image](https://cloud.githubusercontent.com/assets/908665/23162248/19ab2c54-f825-11e6-90c3-fa8cf18a312b.png)

**Comment by beaulebens** [comment]
I think we should explicitly mention that they will be removed from all posts and pages where they may have been inserted. If they are associated with a specific post, we could even list that in the prompt.

**Comment by iamtakashi** [comment]
> we should explicitly mention that they will be removed from all posts and pages where they may have been inserted.

As we discussed above, we've intentionally avoided using the terms like "posts" and "pages" because of CPTs and Custom Header. We've also considered other terms like "entries" or "items", but at the moment "locations" would sound best to me.

> If they are associated with a specific post, we could even list that in the prompt.

I've thought providing more context like your suggestion, but it will be tricky to list every possibilities of the use of the image, such as Custom Header.

**Comment by supernovia** [comment]
Re @aduth's note on media trashing, could we maybe enable it by default for everyone? And if they want to disable it they can go to wp-admin?

**Comment by thehenrybyrd** [comment]
> I've thought providing more context like your suggestion, but it will be tricky to list every possibilities of the use of the image, such as Custom Header.
Listing each use would definitely be prohibitive, especially if users are deleting a large number of items (such as images).
However, "locations where they appear" may not alert most users to the danger of deletion. I do think mentioning posts/pages, or putting this more plain language, would be helpful to our users.

Maybe something like: 
> Are you sure you want to delete this item [these items]? It [They] will disappear forever from posts and pages, and anywhere else it [they] currently appears [appear].

I'm not sure that's the _best_ wording, but I want to make sure we cater to our user's understanding of the world of the internet. It's easy to assume that the Media section is like the 'desktop' area on a computer, and it needs to be cleaned up once in a while. Users often don't realize that this is like deleting the 'All my files' folder.

I also really like the idea of media trashing as mentioned by @aduth and @supernovia - that might be an even better option or addition.

**Comment by supernovia** [comment]
For what it's worth, I've run into just a few cases lately where someone cleared their media library months ago, and is just now realizing their older images are gone. So the trash would help many folks but it won't fix everything.  I still think we should enable it, since even with a scary message people will click through anyway assuming it's un-doable.

**Comment by designsimply** [comment]
<blockquote>For what it's worth, I've run into just a few cases lately where someone cleared their media library months ago, and is just now realizing their older images are gone.</blockquote>

I've run into this with users lots of times too. I think it's a more common problem for users than is apparent. Caching is a complicating factor because it's possible to delete an image and still have it show up in content for a while.

Users delete images and then wonder why images have broken in content ALL the time. Huge +1 for enabling trash for media.

**Comment by alexjgustafson** [comment]
Had a ticket that shed some interesting light on how a user might be thinking when the idea strikes them to clear out their media library: 3223000-t

In most of this discussion it seems like we assume that users 1) want more media space 2) think deleting it from the media library will keep them in the posts.

In this case, the user thought it had a different message entirely: deleting the image from the media library would remove it from all posts, but still let the image be available for moving around/adding into other posts/pages. Like a confusion between the picking of an image vs. the storing of it.

**Comment by supernovia** [comment]
Hey folks, any luck on this? I still run into issues now and then. Could we update the messaging for now?

I'll throw my own scary-error into the hat:

> All deleted media will stop functioning on your website. Are you sure you want to delete these items?  This cannot be undone.

**Comment by dllh** [comment]
It's not really on my team's radar, but if reports keep coming up, please add them to the issue so that the triage crew can help prioritize it alongside other things.

**Comment by thehenrybyrd** [comment]
> All deleted media will stop functioning on your website. Are you sure you want to delete these items? This cannot be undone.
I really like this phrasing - it's scary and clear, without being long or hard to read.

**Comment by alexjgustafson** [comment]
> if reports keep coming up, please add them to the issue so that the triage crew can help prioritize it alongside other things

Did a quick scan of systemsrequests, as folks deleting their whole media libraries often ends up being a request to restore from backup. Can these all count as votes?

https://systemsrequests.wordpress.com/2017/06/05/can-we-restore-a-backup-for-jamiemacmillanphotos-com/
https://systemsrequests.wordpress.com/2017/05/22/restore-from-backup-request-lelaoswald-wordpress-com/
https://systemsrequests.wordpress.com/2017/04/26/site-restore/
https://systemsrequests.wordpress.com/2017/03/20/site-restore-for-vanessabratschi-wordpress-com-123432975/
https://systemsrequests.wordpress.com/2017/03/08/site-restore-for-sonntagimpark-wordpress-com-42380559/
https://systemsrequests.wordpress.com/2017/02/24/blog-restore-from-backup-katgotyourtongueblog-wordpress-com/
https://systemsrequests.wordpress.com/2017/01/18/hi-one-of-our-users/

**Comment by designsimply** [comment]
> Can these all count as votes?

It certainly wouldn't hurt to add some numbers about that here to give the issue some extra context.

**Comment by supernovia** [comment]
I've run into two in the past two days.
https://twitter.com/lolaaskar/status/876097374543859713

**Comment by supernovia** [comment]
Glad you like that phrasing, @thehenrybyrd .  If we could even just change the phrasing for now and save even one user per day from the headache of having to re-upload everything, I think that'd make WP.com a much more encouraging experience.

**Comment by cecoates** [comment]
Another one via ticket: t-3270490

Definitely happens fairly regularly.

**Comment by alexjgustafson** [comment]
3270759-t

**Comment by SiobhyB** [comment]
This came up again in 3315234-t.

**Comment by rralian** [comment]
I should have un-assigned myself a long time ago, my apologies. I had tried to address this several months ago in #11629 before learning that my approach didn't work in production and had to be reverted in #11919. I realized I needed to do this completely differently and haven't had the time since to circle back and address it. Best to un-assign myself so it's clear I'm not actively working on this so someone else could possibly pick it up.

**Comment by donpark** [comment]
OK. I'll pickup this hairball as far as making the Delete button scary. I have a PR being reviewed that extends `lib/accept`, used by the Media Library for confirmation, to accept an optional `options` (?!?) parameter. One of thousands (actually just one) of options is `isScary`, a boolean. Once it's merged, we can change the Media Library to use the option, hopefully before next Halloween.

As to the copy, just let me now what it should be with ultimate final end-of-the-world seal of approval from the crowd.

**Comment by rralian** [comment]
I think you can take the wording here as canonical TRUTH. https://github.com/Automattic/wp-calypso/issues/10982#issuecomment-281312057

**Comment by donpark** [comment]
Everyone still watching this issue in suspense, please review PR #17195 that should resolve this issue. Thx.

**Comment by donpark** [comment]
PR #17195 has been merged and deployed. Closing.
