### ISSUE TITLE
Purchases: Remove legacy /purchases page at /my-upgrades

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#1098]
Now that /purchases has been deployed for a week without any major issues, we should remove the legacy page at /my-upgrades.

First step should just be to forward /my-upgrades --> /purchases. Then when we have more traffic using the new flow we can remove the old one after fixing any other issues that surface.

**Comment by drewblaisdell** [comment]
We should assert that the link to renew in renewal emails doesn't still redirect users back to `/my-upgrades`. I believe @peterbutler said this would happen soon - it might already have changed, I'm not sure.

**Comment by fabianapsimoes** [comment]
Moved to T351-code since it's a back-end issue.
