### ISSUE TITLE
Editor: tap targets are a bit small for the "Link to existing content" section on an Android device

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#10987]
Steps to reproduce:

1. Start by using an Android phone.
1. Go to https://wpcalypso.wordpress.com/post and select a site if prompted.
1. Tap the HTML tab.
1. Tap the link quicktag.
1. Tap to select a post or page in the "Link to existing content" section.
1. Tap to select a different post and note whether it's easy to tap through each list item or not.

<strong>Result:</strong> I felt the target for the PostSelector is pretty small, but it might be okay for most people (??!, could use a 2nd opinion).

<img alt="screenshot_20170126-173441" src="https://cloud.githubusercontent.com/assets/1119271/22356404/5e87dca0-e3ee-11e6-959e-7f6a6023bd94.png" width="300" />
<sup>Seen at https://wpcalypso.wordpress.com/post using Pixel, Android 7.1.1</sup>

**Comment by Copons** [comment]
To be exact, the issue is related to the **[PostSelector](https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/post-selector)** block, also testable in the [devdocs](https://wpcalypso.wordpress.com/devdocs/blocks/post-selector).
