### ISSUE TITLE
Reader Reduxification!

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#10984]
The time has come for the Reader team to get rid of Flux once and for all.

I thought it might be helpful to create a master issue keeping track of all the major components that need reduxification:

1. [x] PostStore:
   - [x] redux storage + ui connections: https://github.com/Automattic/wp-calypso/pull/22101
   - [x] data fetching
   - [x] delete flux code 🎉  https://github.com/Automattic/wp-calypso/pull/22458
1. [x] Teams:
   -  [x] redux plumbing + connecting https://github.com/Automattic/wp-calypso/pull/10764
   - [x] serialization + schema: https://github.com/Automattic/wp-calypso/pull/11083
   - [ ] ~~api validation in middleware~~: 
   - [ ] ~~remove the isRequesting subreducer in favor of incorporating that logic into middleware: https://github.com/Automattic/wp-calypso/pull/11069~~
   - [x] make middleware test confirm next() was called https://github.com/Automattic/wp-calypso/pull/12786
   - [x] delete old flux code 🎉  https://github.com/Automattic/wp-calypso/pull/11066
2. [x] Streams:
   -  [x] redux + data-layer plumbing https://github.com/Automattic/wp-calypso/pull/10710, https://github.com/Automattic/wp-calypso/pull/19591
   - [x] redux + data-layer detail handling
   - [x] delete old flux code 🎉 https://github.com/Automattic/wp-calypso/pull/24800
3. [x] Subscriptions/Follows: 
   - [x] redux plumbing https://github.com/Automattic/wp-calypso/pull/10777
   - [x] ~~connecting~~ - this is being done as part of Search on Manage
   - [x] follow/unfollow data-layer/redux: https://github.com/Automattic/wp-calypso/pull/13434
   - [x] redux bound follow button: https://github.com/Automattic/wp-calypso/pull/13239
   - [x] delete old flux code: https://github.com/Automattic/wp-calypso/pull/14710
   - [ ] fix x-post filtering: https://github.com/Automattic/wp-calypso/issues/14722
4. [x] LikesStore: 
   - [x] data layer: https://github.com/Automattic/wp-calypso/issues/22013
   - [x] reducers: https://github.com/Automattic/wp-calypso/issues/22013
   - [x] delete old flux code: https://github.com/Automattic/wp-calypso/pull/23570 🎉 
5. [x] Email Subscriptions: https://github.com/Automattic/wp-calypso/pull/12703
6. [x] Lists: 
   - [x] review remaining usage of readerListsStore.get in reader/sidebar and switch to Redux
   - [x] delete codez 🎉 
7. [x] SiteBlocks: 
   -  [x] redux plumbing: https://github.com/Automattic/wp-calypso/pull/10649
   -  [x] connecting: https://github.com/Automattic/wp-calypso/pull/10944
8. [x] ReaderSidebar batchfetching:
   -  [x] delete all the codez 🎉 
9. [x] SiteStore:
   - [x] connect components.  redux plumbing already in place
10. [x] TagsStore
    - [x] actions
    - [x] middleware for current following
    - [x] middleware for new follows
    - [x] middleware for unfollowing
    - [x] api validation and potential transformation (`fromApi`)
    - [x] reducer
    - [x] hook up to ui
    - [x] delete old flux code

**Comment by danny-wieser** [comment]
It appears that there is code in lib/reader-lists (lists.js and subscriptions.js) that is largely migrated to redux, with just a single usage in the reader sidebar component.  I've added a checkbox above to review remaining usage in sidebar prior to removal.

**Comment by samouri** [comment]
DONE!

**Comment by bluefuton** [comment]
![dancing goat](https://media.giphy.com/media/3oEdv36dXkKSqfzjzy/giphy.gif)
