### ISSUE TITLE
Jetpack Connect: Clarify Site Address is the location of WordPress and not the Home URL

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#10980]
#### Steps to reproduce
First create a self-hosted WordPress site with WordPress installed in a subdirectory. 
https://example.com/wp -- site URL
https://example.com -- home URL

1. Starting at URL: https://wordpress.com/jetpack/connect
2. Enter the Home URL/Site Address for the site, ie example.com 
3. Notice the error "This is not a WordPress site"

![screenshot_26-01-2017-13 16 30](https://cloud.githubusercontent.com/assets/150348/22351137/6e351df2-e3cb-11e6-80c2-6b437ccb4496.png)

4. Enter example.com/wp and be shown the install screen:
![screenshot_26-01-2017-13 29 51](https://cloud.githubusercontent.com/assets/150348/22351174/9660cd4e-e3cb-11e6-9687-f4959cbc2a3c.png)

The install URL did work once I entered the Site URL

#### What I expected
For the home URL to find WordPress instead of reporting back WordPress was not found.

#### What happened instead
Was given a message my site was not a WordPress site.

As the above is an improvement on the related #6085 and #6088 I'll close those in favor of this one.

**Comment by beaulebens** [comment]
At least part of the fix for this should probably be actually accepting the home URL, and then checking the meta data in the page to figure out the site URL dynamically. You can get it from the `pingback`, `EditURI`, or `wlwmanifest` header tags in the source of the document. They're not always available though, so maybe tweaking the wording can help here as well.

**Comment by rickybanister** [comment]
`That url doesn't seem to be a WordPress site` would be more accommodating. It would also be good to give a follow-up option. Perhaps a support doc outlining common connection problems or an explicit path to get help.
