### ISSUE TITLE
Jetpack Connect: Detect when site already has plan for VaultPress register

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10985]
#### Steps to reproduce

Prerequisite: Have a site with Jetpack Personal Plan but which has not configured the bundled plugins (VaultPress, Akismet). I ran into this because I granted the Personal plan to my Jetpack site directly, though I assume the same issue would occur if a user purchased the plan through WordPress.com but did not follow-through with the steps to "Configure Plan".

1. Start at: wp-admin Jetpack Dashboard
2. Confused that I see a notice for "Register" VaultPress despite having purchased the Premium plan, I click "Register"
3. On the VaultPress settings screen, it's clear that VaultPress is not set up because I'm asked to "Compare Plans" or enter a registration key. So I click Compare Plans.
4. I'm led to the VaultPress site's "Get Jetpack Personal" screen
5. I click to Get Jetpack Personal
6. I'm led to the Calypso Jetpack Connect screen, so I enter my site's address

#### What I expected

At many points along this process (2, 3, 6), I should have seen some recognition that my site is already on the Personal Plan, and an option to configure the plan if that's what was necessary.

#### What happened instead

After step 6 I'm sent to Checkout for Personal Plan.... even though my site is already on the Personal Plan.

Eventually after removing the plan and starting over, I realized that after completing the purchase for Jetpack Personal plan, the confirmation screen has me "Configure Plans". Once I clicked this, it was smooth sailing and everything installed nicely.

#### Context / Source

Continued dogfooding from #10981

**Comment by johnHackworth** [comment]
This brings up several good points.. thank you @aduth ! 

@rickybanister  @ryelle I think we need to make it the system a little smarter so we don't prompt the user to "register vaultpress", but offer them an auto-setup link when we know they are in a plan that includes it

**Comment by rickybanister** [comment]
I'd also like to schedule a guides appointment or something if someone 'gets' a plan by any means and is not set up 24 hours later. We can send an email that takes them into the config flow.

Now that the config flow is so tied to the thank you page after payment, we may need to create a separate page of some kind though.

cc @ebinnion
