### ISSUE TITLE
Plugins: Add a intermediate "updating" state

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#1099]
As @rickybanister states at https://github.com/Automattic/wp-calypso/pull/1031, when you are in your plugins list, filtering by 'updates available', and click in the "update all" button, immediately you are shown the "everything is up to date" drake screen, even if the plugins are still being updated.

That happens because as soon as we launch a plugin update, we mark that plugin as updated. So if you have 8 plugins waiting for updates, for example, and click in "update all", the 8 of them gets marked as "updated" as soon as you click the button, but the updates are being done serially, not in parallel, so it can get a little confusing for the user.

I think we should add an intermediate state that marks a plugin as "updating". Maybe showing it in the list, but with opacity: 0.5 and all the interaction disabled, or something similar to that.

![image](https://cloud.githubusercontent.com/assets/1554855/11500744/5a1c6e1c-982f-11e5-8263-d0cbf87f6fe6.png)

**Comment by enejb** [comment]
This has been fixed. Will close this for now.
