### ISSUE TITLE
Framework: do not attach sites popover to svg element

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#1100]
```
Popover is attached to a svg element (nodeType 1).  This causes problems in IE11 - see 12168-gh-calypso-pre-oss.
```
![image](https://cloud.githubusercontent.com/assets/77539/11501089/4478d2ae-9810-11e5-9229-71448331d781.png)

**Comment by gwwar** [comment]
@retrofox do you recall what page you were on? I did a quick audit in the code and couldn't find any popovers attached to an SVG element.

**Comment by retrofox** [comment]
@gwwar It was when user clicked in sites popover. It was fixed because it isn't injected into `<svg />` anymore.
![image](https://cloud.githubusercontent.com/assets/77539/11602915/d0e2e672-9abc-11e5-91f1-4273b50701ea.png)

**Comment by gwwar** [comment]
:+1:
