### ISSUE TITLE
Editor: Changing category during auto-save is discarded

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#11000]
To repro (easier with a Jetpack site since saving takes longer) :
1. Starting at URL: `https://wordpress.com/post/{your_site}`
2. Make sure you have >1 category to test with.
3. Type a title and some content.
4. Hover your mouse over a category checkbox. Prepare to click.
5. Immediately after the editor begins auto-saving, check or uncheck a category.

I expected: my category changes to be kept/saved

What happened: when auto-save is finished, my checks/unchecks are reverted.

It's possible that this happens on WP.com sites as well, but they finish saving so quickly that I'm not entirely sure I'm clicking the checkbox fast enough to trigger the bug.

Using latest Mac and Chrome.

**Comment by aheckler** [comment]
Note: this bug doesn't seem to exist with other things, e.g. Post Format. I'm not sure if those changes are truly saved, or if perhaps they are reverted but the checkbox state isn't changed.

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue. Category changes while the post is autosaving are saved on the post.

#bug-scrub #pre-gutenburg-bug-purge
