### ISSUE TITLE
Editor: Rename the "Overwrite" button on the 'copy a post' feature

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#11013]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/example.wordpress.com
2. Expand the "More Options" panel on the sidebar, scroll to the bottom
3. Click the "SELECT A POST TO COPY" button
4. Observe the button labelled "Overwrite"
5. Be afraid

At first glance I'm not entirely sure what's going to happen when I click that button.  Did I misunderstand the feature?  Is it going to overwrite the selected post with what I've written here in this draft (which may be nothing)?  Thinking it through I know that doesn't make sense, but I'm still uncomfortable.  I had to switch to a test blog to try it just to make extra sure I wasn't going to lose an old post by mistake.  This is especially a problem if I'm copying somebody else's post.

I'd much rather see the button labeled "Copy", and have a confirmation prompt warning me that it will overwrite what I've already written (and ideally I wouldn't get that prompt if the destination post was empty)

#### Screenshot / Video
![image](https://cloud.githubusercontent.com/assets/7233112/22386571/b31f91a6-e4a5-11e6-866a-38874a34e881.png)

#### Context / Source
#anxiety #dogfooding

**Comment by rachelmcr** [comment]
Confirmed issue is still valid; I agree that the "Overwrite" button is scary!

#bug-scrub #pre-gutenburg-bug-purge

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

I quickly checked how posts are copied now, and it appears that calypso now uses a hamburger menu:
![Screen Shot 2021-01-29 at 14 24 37](https://user-images.githubusercontent.com/6549265/106333667-04071700-623e-11eb-9bd2-0473d5d411b2.png)

I am proposing to close this issue with an appropriate label denoting reason for closure if no work is scoped for the near term.
