### ISSUE TITLE
Editor: post changes disappear during draft autosave

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#11014]
#### Steps to reproduce
1. Start a new post (note: I am editing a Jetpack site)
2. Enter a title and start typing in the body
3. Any text entered between when a draft starts saving and finishes saving disappears

#### What I expected

Text I typed doesn't disappear.

#### What happened instead

Text I typed disappeared.

#### Browser / OS version

Firefox 51, OS X Sierra 10.12.3

I wasn't able to reproduce on Chrome.

#### Screenshot / Video

https://cloudup.com/c6uPzdELpik

**Comment by lancewillett** [comment]
I've noticed this a lot recently as well. Haven't narrowed it down to a certain type of site (will pay more attention if I see it again.)

**Comment by rachelmcr** [comment]
I retested in Firefox, Safari, and Chrome and can no longer reproduce this issue. Text entered while the post is autosaving is saved as expected.

#bug-scrub #pre-gutenburg-bug-purge
