### ISSUE TITLE
Themes: Twenty Sixteen not highlighted when active on Jetpack site

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#11020]
To repro:
1. Starting at URL: `https://wordpress.com/design/{your_site}`
2. Notice that your currently active theme card is blue.
3. Activate Twenty Sixteen.

#### What I expected

Twenty Sixteen card to turn blue.

#### What happened instead

It didn't.

#### Browser / OS version

Mac n' Chrome.

#### Screenshot / Video

https://d.pr/v/EAIR/7hiFhjH5

**Comment by folletto** [comment]
Can you check if Twenty Sixteen is shown as active in the "WordPress·com themes" list below?

_Also updated the title to clarify it's Jetpack only._

**Comment by aheckler** [comment]
> Can you check if Twenty Sixteen is shown as active in the "WordPress·com themes" list below?

It is not.

**Comment by folletto** [comment]
Ok thanks! A fix is upcoming in #11087.
