### ISSUE TITLE
People: Invites: Update style and message of welcome notice

### ISSUE THREAD

**Issue by lezama** [Automattic/wp-calypso#1102]
Current message after https://github.com/Automattic/wp-calypso/pull/636#discussion_r46165904 :
![image](https://cloud.githubusercontent.com/assets/104869/11501523/8cb441ea-9813-11e5-9f2b-bd50292b02ef.png)

https://github.com/Automattic/wp-calypso/pull/636/files#r46165904

Use the `Welcome` component. https://wpcalypso.wordpress.com/devdocs/client/my-sites/welcome/README.md?term=welcome

cc @rickybanister

**Comment by rickybanister** [comment]
I think this works just fine. The previous version (gray-light) was a bit easy to miss. The green clearly indicates success. 

Notices still use noticons, but that's an issue for another PR.

**Comment by ebinnion** [comment]
Closing per @rickybanister's comment that this works fine.
