### ISSUE TITLE
Media Section: Missing action buttons in edit modal

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#11024]
We don't have any action buttons in the modal you see when you edit a media in the section.

![screen-shot-2017-01-28-at-11 41 41](https://cloud.githubusercontent.com/assets/908665/22396392/95abc5e4-e550-11e6-999a-123fcb7d695f.jpg)

(@gwwar updated) 
Since we lack a primary action in the media section. Users should be able to "Delete" and "Close" (Close the modal).
-- Double check for copy of "Close" vs "Done"

![screen shot 2017-02-27 at 9 32 09 am](https://cloud.githubusercontent.com/assets/1270189/23372265/c3ab29e4-fccf-11e6-8890-0c900aedf557.png)

Note that we should keep the "Cancel" text in the media modal flow, since there is a primary action there.

**Comment by iamtakashi** [comment]
Once the "Cancel" button is added, we also should remove the "Back" button at the top of the modal because it's not necessary and does the same thing as "Cancel" button. (Discussion #11133)

**Comment by gwwar** [comment]
Needs more discussion if cancel makes sense in the details view, since this doesn't cancel form changes.

**Comment by iamtakashi** [comment]
We've discussed about this a little, and we agreed that the term "cancel" won't work here because the button won't cancel what you add/edit in the details column since they are auto-saved.

"Done" as a primary button is probably good here because it can be both "close without/with changes". Having a primary button is nice and I prefer a primary button to be "done' rather than "close".

![image](https://cloud.githubusercontent.com/assets/908665/23469149/be607bca-fe9a-11e6-9ab4-5ba1fd11995d.png)
