### ISSUE TITLE
Themes: welcome message modal for Jetpack has wrong links

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#11046]
![lmohjmr9f1](https://cloud.githubusercontent.com/assets/4389/22428253/3d093aca-e6fe-11e6-832d-ad3a927d5965.png)

Let's update the welcome modal for Jetpack users:

1. The “awesome theme” link takes me to https://wordpress.com/themes/orvis/ rather than https://wordpress.com/theme/orvis or https://wordpress.com/theme/orvis/www.richardmuscatistestingthings.com as other “Info” links around the UI do
2. The phrasing of the first bullet point seems off for. Suggest: “[Learn more](#) about this theme.” or “[Learn more](#) about your new active theme.”
The “contact theme author” link simply drops me at https://wordpress.com/themes/ which feels incorrect

/ht @richardmuscat

**Comment by ockham** [comment]
@folletto I think we can unify a few separate cases in the thanks modal's code. I have a specific question: Right now, the wording is a bit different for themes on a wpcom site, and themes on a Jetpack site:

* Jetpack (see above): [Learn more about this awesome theme.](https://github.com/Automattic/wp-calypso/blob/0b6cb3eacc421c915e8ed998b29b26a68228cf11/client/my-sites/themes/thanks-modal.jsx#L99)
* WP.com: ["Discover this theme's awesome features.](https://github.com/Automattic/wp-calypso/blob/0b6cb3eacc421c915e8ed998b29b26a68228cf11/client/my-sites/themes/thanks-modal.jsx#L66)

Do we want to keep them separate, or can we use the same wording for both?

**Comment by folletto** [comment]
We can use the same wording.

**Comment by ockham** [comment]
Cool! Err, which one then? 😄

**Comment by folletto** [comment]
> “Learn more about this theme.” 

With the link on "Learn more". :)
