### ISSUE TITLE
Themes: no-result searches should be smarter on double lists (Jetpack)

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#11045]
When searches don't return values the two lists should wrap:

1. If one list is empty and the other is not, the empty list should not show.
2. If both lists are empty, it should show only a single "Sorry, no themes found."message.

![screen shot 2017-01-30 at 15 00 51](https://cloud.githubusercontent.com/assets/4389/22428042/71e412a2-e6fd-11e6-8302-2bed11b9e31d.png)

**Comment by seear** [comment]
Possible approach:
* a list should hide itself if it is empty.
* show drake if no lists
* Upload button: take it out of the list and position it with CSS
