### ISSUE TITLE
Themes: active Jetpack themes ••• links wrong

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#11047]
<img width="644" alt="6hptha-8ux" src="https://cloud.githubusercontent.com/assets/4389/22428541/5916504e-e6ff-11e6-9ff4-8b3fbaff91bc.png">

To reproduce have a Jetpack site and activate .com theme.

Issues:

1. It is missing the “Support” item
2. The “Info” link is pointing me to https://wordpress.com/theme/ixion-wpcom/example.com rather than https://wordpress.com/theme/ixion/example.com (this would be fine except that the `-wpcom` version is broken

/ht @richardmuscat

**Comment by seear** [comment]
Fixed by #11171
