### ISSUE TITLE
G Suite: Needs message for users who already have G Suite for mapped domains

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/wp-calypso#11055]
Users with a mapped domain and who have already purchased G Suite from Google should see a message directing them to instructions on how to set up their MX records to properly set up their email. 

Right now, if a user with a domain mapped to WordPress.com clicks on the *Email* tab in /domains, they get this message:

![screen shot 2017-01-30 at 9 51 58 am](https://cloud.githubusercontent.com/assets/6569475/22429870/c963c274-e6d1-11e6-8e73-d5d2ef56e126.png)

There's no further direction here for the user to follow. 

Could we add messaging along the lines of:

<blockquote>Already have a G Suite account for this domain? Click [here](https://en.support.wordpress.com/add-email-through-g-suite/) for instructions on how to set it up.</blockquote>

Note: For users without G Suite on their mapped domains, there is already an existing PR [here](https://github.com/Automattic/wp-calypso/pull/10843). 

/cc @cecoates 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains
2. Select site associated with the mapped domain.
3. Click on the mapped domain listed on the next page. https://wordpress.com/domains/manage/example.blog
4. Click on the EMAIL tab on the next page.

**Comment by klimeryk** [comment]
Closing this, since we support G Suite on mapped domains now.
