### ISSUE TITLE
Unable to map .ie and certain other TLDs

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#11051]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/
2. Type any registered .ie domain (or subdomain if you want to)

#### What I expected

To be able to map any registered, valid, .ie, id, .pk, some other domains. For example, mydomain.ie, tracker.ie, news.ie

#### What happened instead

It asks me to: "You can register it elsewhere first and then add it here." But, it's already registered! :)

#### Browser / OS version

Chrome, latest, Win10.

#### Screenshot / Video

![mapping-ie](https://cloud.githubusercontent.com/assets/6505293/22429012/f8b308ba-e72a-11e6-89c4-28fff1a63e1a.jpg)

And if you choose the last option to map it anyway, still won't let you map:

![mapping-ie2](https://cloud.githubusercontent.com/assets/6505293/22429024/037dabe2-e72b-11e6-8d85-a8dc81f3aae2.jpg)

#### Context / Source
It seems like there are multiple mapping issues present in the flow. #8998 was related but fixed. Not sure if I should've re-opened that. There's #10176 which also deals with mapping but not directly related with .ie.

#user-report , #manual-testing

**Comment by ehti** [comment]
OK.

It looks like it affects all the TLDs in [get_unsupported_tlds()](url) - `D3294`, not just .ie.

Edited the title to reflect that.

**Comment by ehti** [comment]
Cannot map .gov.uk domains OR subdomains either.

![image](https://cloud.githubusercontent.com/assets/6505293/22730477/f02a919c-ee08-11e6-95d1-838f6530b384.png)

**Comment by lizkarkoski** [comment]
I have a user in the forums trying to map purplehare.ie to their account. 
http://en.forums.wordpress.com/topic/cant-add-a-domain-1

Each time they go to My Sites > Domains > Map and enter purplehare.ie they get the same blue error as above. 

I've replicated this process and here is a screen shot. 
![screen shot 2017-02-10 at 3 47 47 pm](https://cloud.githubusercontent.com/assets/16867830/22844056/47a6cc5e-efaa-11e6-9bc9-4f5b4fa5cf3b.png)

I had to add the subscriptions manually for the mapping to succeed.

**Comment by katinthehatsite** [comment]
I had a user you could not map the domain with this extension -  ekkotherapies.ie.

I did not take a screenshot in time, but the bug looks exactly like on lizkarkoski's screenshot. The user gets the same blue error as above. 

User also cleared their browser's cache before mapping. 

Transcript of the chat: https://mc.a8c.com/support-stats/happychat/transcript.php?id=160728

**Comment by ehti** [comment]
@klimeryk - there's .art TLD as well, which is not mappable, but with a different error message:

![image](https://cloud.githubusercontent.com/assets/6505293/23151503/fbae378a-f81c-11e6-8d56-95750faab25f.png)

This bug appears to come from a different availability check (found 2 instances). Wasn't sure if I should open a new issue - leaving it here.

#user-report in #1479960-t

**Comment by klimeryk** [comment]
It should be a different issue - it's not a TLD we recognize. I'll look into it too - thanks for reporting it!

**Comment by klimeryk** [comment]
Patch up for review: https://github.com/Automattic/wp-calypso/pull/11511. I'm addressing `.art`'s availability in a separate, backend patch: `D4459-code`.

**Comment by chaitanyamsv** [comment]
A user reported this issue with fifty4.ie in this [HappyChat](https://mc.a8c.com/support-stats/happychat/transcript.php?id=210662).

#210662-hc

**Comment by thehenrybyrd** [comment]
Another report here for charliegracebooks.ie - resolved by adding mapping manually, but we saw the same errors. #212418-hc

**Comment by klimeryk** [comment]
Thanks for the reports - patch is ready at https://github.com/Automattic/wp-calypso/issues/11691. Should be merged on Monday (since tomorrow is Friday + I'm flying whole day 😅).
