### ISSUE TITLE
Photo Cards that should be Default Cards

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11062]
This site ... https://wordpress.com/read/feeds/55911728 ... has two posts that are appearing as Photo Cards when they should be default cards. 

This one ... https://wordpress.com/read/feeds/55911728/posts/1316692633 ... has 230 characters in the post.

<img width="845" alt="screen shot 2017-01-30 at 11 20 52 am" src="https://cloud.githubusercontent.com/assets/24388/22437787/3ea37a82-e6de-11e6-8db7-28cde3f174f6.png">

And this one ... https://wordpress.com/read/feeds/55911728/posts/1316692644 ... has 180 characters in the post.

<img width="827" alt="screen shot 2017-01-30 at 11 21 00 am" src="https://cloud.githubusercontent.com/assets/24388/22437789/439ecd0c-e6de-11e6-8393-bdafc3843851.png">

In both cases, they should appear as Default Cards like all the others, but they're appearing as Photo Cards.

@blowery mentioned that it has something to do with the poetry format and only considering first three paragraphs and asked @samouri "any idea why we’re using better_excerpt?"

**Comment by samouri** [comment]
no recollection on the my front ⚡️
