### ISSUE TITLE
Themes Upload: Unable to upload from Windows

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#11060]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/design/JETPACKSITEURL
2. Click Upload Theme
3. Either drag/drop a theme zip file, or click and choose one

#### What I expected
To see an upload occur

#### What happened instead
I'm given an error notice saying "Please drop a single zip file".  There's nothing in the Javascript console

#### Browser / OS version
Seen in Windows 10 and Windows 7, - Edge, IE11, Chrome, Firefox

#### Screenshot / Video
![screen shot 2017-01-30 at 1 37 34 pm](https://cloud.githubusercontent.com/assets/7233112/22436234/4b98cf7c-e6f1-11e6-9005-21cc7b30223d.png)

#### Context / Source
#manual-testing

**Comment by folletto** [comment]
> Either drag/drop a theme zip file, or click and choose one

Just to be clear, the error appears in both scenarios?
And in the case of click, it appears after the file is picked from the file browser?

**Comment by hoverduck** [comment]
Correct on both points
