### ISSUE TITLE
Plugins: single plugin page should have a link to plugin settings

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#11061]
![screen shot 2017-01-30 at 12 48 44 pm](https://cloud.githubusercontent.com/assets/618551/22436633/830e0294-e6ea-11e6-82b1-512445c1e05c.png)

For the plugins that have a Settings link specified, we should include this link in the single plugin page in Calypso. wordpress.com/plugins/jetpack/[siteurl]

We need to find out if this is possible, and why Jetpack hasn't include this before.

Example: `Edit plugin settings in WP Admin       -->`

For plugins without any Settings link, we should at least link to wp-admin/plugin.php so users can get at least have a starting point for finding those settings.

![screen shot 2017-01-30 at 12 53 00 pm](https://cloud.githubusercontent.com/assets/618551/22436792/2225e270-e6eb-11e6-9b29-0f9cec993377.png)

**Comment by lancewillett** [comment]
This might be a duplicate of https://github.com/Automattic/wp-calypso/issues/82

**Comment by drw158** [comment]
closing in favor of #82
