### ISSUE TITLE
Plugins: What stats do we need prior to AT launch?

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#11063]
Our currently available Jetpack plugin stats can be seen in MC.

Do the current stats account for plugins that are not in the .org repo?

Which other ones do we need in order to measure success, or inform future design decisions better?

Examples: 
- individual plugin page views
- clicks on future setting link #11061 

cc @roundhill

**Comment by roundhill** [comment]
I've analyzed the code for existing stats, and everything is covered except for the settings links that haven't been added yet.

I added a note to #82 to add the stat, so I'll close this and track it there.
