### ISSUE TITLE
DevDocs: Various components/blocks not showing correct title

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#11079]
#### Steps to reproduce
Open https://wpcalypso.wordpress.com/devdocs/design & https://wpcalypso.wordpress.com/devdocs/blocks

#### What I expected
To see all components / blocks with appropriate tiltes

#### What happened instead
The following components have seemingly random single-character titles:

Banner - https://wpcalypso.wordpress.com/devdocs/design/u
Tooltip / Popover - https://wpcalypso.wordpress.com/devdocs/design/t (both point to the same URL)
Reader Post Card - https://wpcalypso.wordpress.com/devdocs/blocks/c

I'm only seeing this on wpcalypso, if I run the current master branch locally (or via calypso.live) everything looks fine

#### Browser / OS version
All

#### Screenshot / Video
![screen shot 2017-01-31 at 9 54 52 am](https://cloud.githubusercontent.com/assets/7233112/22469848/552c22e6-e79b-11e6-9b65-ff5e0fcc49e3.png)

#### Context / Source
#automated-testing #visdiff

**Comment by hoverduck** [comment]
I've added a workaround to the visdiff tests to use the `?debug=true` flag to prevent the JS code from being minimized (which is the cause of the problem) - https://github.com/Automattic/wp-e2e-tests/pull/379

@blowery - I know a few folks discussed this in Slack yesterday, but was there a consensus on the best fix?

**Comment by alisterscott** [comment]
It looks like "Banner" is now fixed, but the others don't seem to be. Was something done to Banner to make it work?

**Comment by wilsonpage** [comment]
Currently the name is derived from the from the 'example' component's `displayName` property. If this isn't defined then it falls back to `name` ([source](https://github.com/Automattic/wp-calypso/blob/master/client/devdocs/docs-example/util.js#L25)), which is just the native name of the class. Class names will be compressed during minification, but strings will not.

Banner was fixed ([commit](https://github.com/Automattic/wp-calypso/commit/9edc59e4b56019fedabfbf897f464e307a054862)), but there are still some component examples that haven't (eg. [tooltip](https://github.com/Automattic/wp-calypso/blob/master/client/components/tooltip/docs/example.jsx)).

To fixed this all example components must have a `displayName` property, or we find a smarter way to extract the name that isn't so subject to human error.

**Comment by tofumatt** [comment]
Looks like we can solve this by adding: `'react/display-name': [ 2, { ignoreTranspilerName: true } ],` to our `.eslintrc`'s `rules`; we're already including `eslint-plugin-react` which gives us this rule.

I count a large number of components that error when this rule is added, but a fair number are very "internal" components used inside folder like `/client/layout/guided-tours/` and `/client/extensions/woocommerce/` that I'm not sure need `displayName` class properties. Adding an `// eslint-disable-next-line react/display-name` to these files makes more sense as it won't add an unneeded prop/string to the built file for a property that shouldn't ever be used.

I've got a branch in-progress on this but I need to run out for dinner so I'll likely push it for review sometime tomorrow.

**Comment by tofumatt** [comment]
I think surfacing the names in non-development builds is useful for those who want to look at the production site as documentation. My *feeling* is that it's good to show those in production because it makes the documentation seem well-rounded and thorough. But I suppose it's a question of numbers: how many people actually use https://wpcalypso.wordpress.com/devdocs/design versus looking at it locally?

Because of the minification issue I'd imagine there isn't really a semantic way to extract the component name without an explicit property. An eslint rule to make sure everything matching `example/**.jsx` has a `displayName` property might do the trick. Making every component in the app have a `displayName` is way overkill and also a **lot** of changes 😆

**Comment by hoverduck** [comment]
For what it's worth, the original driver behind this was that we were using the devdocs pages to run visual difference tests against Calypso components, but that's no longer the case - p6fDka-nu-p2

I can't say whether it should or shouldn't be fixed, but I'm no longer personally invested :grin:
