### ISSUE TITLE
Themes: uploading existing theme should point to the theme details

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#11077]
<img width="1131" alt="blvdlsbjrz" src="https://cloud.githubusercontent.com/assets/4389/22467055/f715ac98-e7ba-11e6-9f9c-98e89af98e82.png">

If a user uploads a theme **already uploaded** we should either:

1. Forward the user to the theme sheet
2. Ask if the user wants to overwrite

Ideally I think the second would be better, or at least an option asking between these two options above. In the meantime however would be nice if we could just:

1. Show a yellow message saying "The theme already exist [ show details ]" and the show details button leads to the theme sheet.
2. Just redirect to the theme sheet (maybe too abrupt?)

In the future we should show a message (either dialog or in-page) asking the user if they mean to over-write the theme, or just see the details.

/cc @rickybanister

**Comment by folletto** [comment]
Still an important UX improvement.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

For reference, this is how the UI currently looks like:
![Screen Shot 2021-02-02 at 5 02 51 PM](https://user-images.githubusercontent.com/6549265/106683059-a3971300-6578-11eb-9398-5e233c537317.png)

With that said, as there as not been any activity on this issue in 3 years, I am proposing that this issue be closed until work is tabled and scoped.
