### ISSUE TITLE
Editor: When a theme supports one post format the post format component is not rendered.

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#1107]
The `Dyad` theme currently supports one post format of `image`. When attempting to create a new post using this theme the post format meta box is not being rendered. 

It looks to be an issue in the accordion component - it returns `null` when only one post format is found:

https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/editor-post-formats/accordion.jsx#L64

The API response for `Dyad` theme is here:

![screen shot 2015-12-01 at 13 55 39](https://cloud.githubusercontent.com/assets/411945/11503514/eecc6f4a-9838-11e5-9f45-717921157598.png)

I imagine this check is in place to catch themes that only support the standard post type but `standard` is not being added to `this.props.postFormats` in the accordion component.

**Comment by sarahmonster** [comment]
I have another bug report for this same issue with The Morning After, which also only declares support for a single post format.

**Comment by carinapilar** [comment]
I guess it will happen in all themes with only one post format support... On Dyad, if it's not set up as Image post format, the post is different from the theme page...

**Comment by jeremeylduvall** [comment]
This should be all fixed up now. Tested on Dyad, and it seems to be working. Feel free to reopen if not!

**Comment by scottsweb** [comment]
Thank you @jeremeylduvall :+1:
