### ISSUE TITLE
Google Analytics: support link should lead to Jetpack support docs on Jetpack sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#11088]
#### Steps to reproduce
0. Start from a Jetpack site using the Professional plan and Jetpack 4.6.
1. Starting at URL: https://wpcalypso.wordpress.com/settings/analytics/jp.wpne.ws
2. At the bottom of the Analytics menu, a support link directs me to the WordPress.com support docs.
3. Since the requirements and set up are different in Jetpack, maybe that link should point to `http://jetpack.com/support/google-analytics/` instead.

**Comment by tyxla** [comment]
This one is being addressed in #12866.
