### ISSUE TITLE
Media: Move image title field to sidebar in media modal 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#11093]
Raised in an internal test.

I can understand why it's currently there, but it's not obvious that the title is actually editable, especially on touch devices with no hover. Adding a persistent border wouldn't look great, and tweaking the colour wouldn't help much either.

<img width="1280" alt="screen shot 2017-02-01 at 00 20 04" src="https://cloud.githubusercontent.com/assets/908665/22490833/5b83bb00-e817-11e6-83cc-facd6033de63.png">

In order to make it clear it's editable, it's probably best to move it to the sidebar with other editable details.

<img width="1280" alt="screen shot 2017-02-01 at 00 19 27" src="https://cloud.githubusercontent.com/assets/908665/22490852/8613f024-e817-11e6-930a-395c85f11cf0.png">

--------
Pull requests

**Review and merge in order**

- [ ] Media Modal: <DetailFields /> component janitorial #12032
- [ ] MediaModal: move `title` to fields section #12033

--------

_`updated 2017-03-10` by @retrofox_

**Comment by iamtakashi** [comment]
On small screens:

![screen-shot-2017-02-01-at-23 51 07](https://cloud.githubusercontent.com/assets/908665/22531684/663e9eac-e8da-11e6-8744-08ee6664374c.jpg)

Bonus point: Without the title, we wouldn't need to hide the text from the back button :)

**Comment by folletto** [comment]
Good change. It was hard to get the title was editable :)
