### ISSUE TITLE
Stats: Add Breakpoint on Period Pages to flow to 3 Columns

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#11094]
With the increased width of the stat pages - there is a large amount of whitespace now between stat list items and values.  On the Period pages ( Day, Week, Month, Year ) this task is to create a breakpoint that flows the lower stat modules ( below the chart ) from 2 to 3 columns.

Here are pixel measurements:

- Original calypso stats layout, `.main` had a `max-width: 720px`.  Stats modules were `352px` wide at "full screen" ( 50% of `.main` width - `0.5em`/8px )
- Stats layout with `.is-wide-layout` has a `max-width: 1040px`.  At full screen, modules are `512px` wide.
- Placing 3 columns in the existing `max-width: 1040px` breakpoint would result in stat modules `338px` wide
- Atlas stats modules were `468px` wide

__Questions__
Could we explore bumping out the max-width: 1040px further?  I think having a try branch with the 3 column layout would be a great way to explore this.

/cc @folletto

**Comment by folletto** [comment]
Note: max-width exists to avoid having line-lengths to get too long, can be extended keeping in mind however that we should try to use as few breakpoints as sensible possible. An alternative would be no threshold at all: Themes are already without any width limit.

No threshold is particularly effective for same sized cards (which maximise the use of CSS `flex`)... but this layout is mansonrly (variable height) so might be challenging.

While `flex` is the ideal solution here (or even CSS `columns`?) I'd just go for the simplest structure to build that allows extending the number of columns as suggested, we'll review later different approaches.

---

That said I tried checking the `338px` size, and seems ok to me. 
So I think it can proceed with that without reviewing too much code at this point.

![screen shot 2017-02-01 at 14 01 43](https://cloud.githubusercontent.com/assets/4389/22509689/0574e796-e887-11e6-9500-bda40793f604.png)

**Comment by timmyc** [comment]
> Themes are already without any width limit.

Very interesting!  That might be something to explore during the next stats re-design.  I will work within the existing 1040px constraints for now.
