### ISSUE TITLE
Publicize: Can't re enable connections when checking & unchecking them when editing / saving a post

### ISSUE THREAD

**Issue by elibud** [Automattic/wp-calypso#11099]
#### Steps to reproduce
1. Create a new post.
2. In the Share section disable a Connection by unchecking the box next to it.
3. Save the post.
4. Re-enable the connection disabled on 2 by checking the box.
5. Save the post.

#### What I expected
The connection to be enabled with the checkbox checked "on".

#### What happened instead
The connection is disabled, with the checkbox unchecked after saving. Once a Connection is disabled it can't be re enabled.

#### Browser / OS version
Safari (10.0.3) - Chrome (55.0.2883.95)
macOS (10.12.3)

#### Extra information
I worked on the implementation of this feature for iOS. To re enable a connection the iOS client sends the following metadata changing the value of the skip from 1 to 0:
```
[{
    id = 484;
    key = "_wpas_skip_16550289";
    operation = update;
    value = 0;
}]
```
The metadata is updated and the connection re enabled properly.

On Calypso, to re enable a connection a POST that tries to delete the skip is sent:

`metadata[0][key]=_wpas_skip_16550289&metadata[0][operation]=delete`

This does not work, however if we issue:

`metadata[0][key]=_wpas_skip_16550289&metadata[0][operation]=update&metadata[0][id]=490&metadata[0][value]=0`

The connection is properly re-enabled.

**Comment by lancewillett** [comment]
Thanks for the report.

**Comment by lancewillett** [comment]
I tried to repeat the steps, but couldn't find the bug. When I disconnected a Sharing connection (Twitter), saved a draft post, then reconnected Twitter, going back to edit the post — the connection seems active again.

**Comment by elibud** [comment]
@lancewillett that is so odd, it happens to me every time. You can ping me on slack @elibud and we can do screen sharing if that helps.

**Comment by lancewillett** [comment]
For now could you maybe share a video here? I might just be missing a key step.

**Comment by elibud** [comment]
Here you go:
https://dl.dropboxusercontent.com/u/25043869/publicizeBug.mov
Let me know if you have further questions.
Thx

**Comment by lancewillett** [comment]
Thank you @elibud — that was very helpful. I edited the original report to include the checking of the checkboxes (I thought disabling meant in the Sharing settings screen).

Based on the video I was able to repeat the issue now.
