### ISSUE TITLE
New post button changes when searching in page for "p" or "n"

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#111]
Steps to reproduce:

1. Go to https://wordpress.com/stats
2. Click CTRL+F to search for a keyword. Start typing "plugins" (I assume it's the 'p').
3. Close the search field (esc).
4. "new post" button now appears as seen below:

![image](https://cloud.githubusercontent.com/assets/7233112/11248533/949e5c84-8def-11e5-8b68-9cab187b4922.png)

This happens in both Chrome 44.0.2403.107 and Safari 8.0.7 on Yosemite. Firefox 39 is unaffected.

**Comment by lancewillett** [comment]
I couldn't reproduce this, testing on https://wordpress.com/stats with a test user `lancetest35` in Mac-n-Chrome. No trouble in Safari 9.0.3 either (on OS X 10.11.3).
