### ISSUE TITLE
Sites: show WP Admin link in sidebar for Jetpack users

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11108]
Previously discussed here: https://github.com/Automattic/wp-calypso/pull/9764

@folletto says:

> The rationale is correct, a Jetpack user using Calypso opted in to Calypso, so it's not a problem. However, Jetpack has right now two big differences from users registered before Sep 7, 2015:
> 
> - The front-end navigation won't link Calypso, so flows inbound are cut.
> - Jetpack sites are very likely with more plugins installed, and as of today no plugin is accessible from Calypso (we're still working on that).
> 
> So, I'd lean for now to add the wp-admin link to all Jetpack users, and review that decision once we have navigation for plugins.

@rickybanister says

> This is tricky as we're in a sort of liminal phase of supporting Jetpack sites on WordPress.com. The wp-admin link could be helpful in the near term, but I do agree that it can simply end up fracturing the experience.

> I think once we have a masterbar in Jetpack the loop is better closed. For now I think it's fine to continue to omit the wp-admin link. I think our larger struggle is getting folks to use Calypso, rather than users finding it difficult to get back to wp-admin.

Context — a WP.com toolbar for front-end navigation (aka masterbar) is coming soon to Jetpack sites, replacing the core WordPress toolbar. Having a link in Calypso sidebar helps close that loop.

**Comment by enejb** [comment]
There are a lot of flows that you start in the wp-admin side (such as buying a plan) and end up in calypso ( a lot of these flows are calypso only ) with not a very intuitive way to get back. As some one that has gone though them they it always feels weird. To end up on screen with no way to get back. I think a lot of these things need to be fixed. But having a wp-admin link would help for now.

Also I don't think I agree with the statement
> The rationale is correct, a Jetpack user using Calypso opted in to Calypso, so it's not a problem. 
You can't do a lot of thing in wp-admin that you need to do to manage your Jetpack site. Try setting your plugins to autoupdate for example on the wp-admin.

**Comment by mtias** [comment]
> But having a wp-admin link would help for now.

I prefer if we just link the things Calypso can't do to wp-admin instead of a catch-all top level sidebar item which confuses more people.

**Comment by enejb** [comment]
I would say most of the time we are already doing that. The one big place
where we are not doing that is when it comes to custom admin pages of
plugins. Including our own Jetpack, woo, akismet etc admin pages.

Having a button wp-admin button would create consistency between .com and
Jetpack sites which is something that is also needed by the AT sites.

**Comment by lancewillett** [comment]
Closing this as "wonfix" — front-end navigation now exists for Jetpack sites, and we've made progress on plugin management within Calypso, so people will have less of a need to visit wp-admin.

**Comment by lancewillett** [comment]
Re-opening based on decision today to put in the WP Admin link for AT sites (regardless of signup date). CC @rralian
