### ISSUE TITLE
Themes: installing a .com child theme should install also the parent

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#11104]
Currently installing a child theme "succeeds" on Calypso end because the theme uploads, but the site is actually missing the parent theme, so it breaks the site completely.

/ht @beaulebens

**Comment by seear** [comment]
* This should not be a problem on AT sites because the symlinking takes care of the parent theme
(@lamosty is that correct?)
* For jetpack sites, we can add the `template` field to the v1.2 themes apis and use it, at installation time, to determine whether parent theme also needs to be installed

**Comment by lamosty** [comment]
> This should not be a problem on AT sites because the symlinking takes care of the parent theme
(@lamosty is that correct?)

Correct.
