### ISSUE TITLE
People: add ability for Jetpack sites to add or invite a new person

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11107]
Right now this feature links to wp-admin for a Jetpack site rather than a Calypso flow such as WP.com sites have for inviting a new user to a site.

Anecdote:
> I’d like to invite a new author to my site. I have a WP.com site, too, and it’s easy there: I just click “People” and “Add” and it sends the user an email with instructions to log in. When I try to do that for my Jetpack site, I end up in wp-admin which is confusing, and it doesn’t send a nice invitation email.

See also:
- https://github.com/Automattic/jetpack/issues/875

**Comment by rralian** [comment]
@lancewillett I think we can close this, as it was addressed in https://github.com/Automattic/jetpack/issues/875. If there's some part we're missing, feel free to re-open.

**Comment by lancewillett** [comment]
See https://github.com/Automattic/wp-calypso/pull/15357
