### ISSUE TITLE
Customizer: audit entry points and URLs for accessing Customizer from Calypso and use canonical URL for everything

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11109]
This is more a task than a bug or enhancement. Would welcome feedback from Gravity folks in case I'm missing something obvious.

**What I expected to happen**
Clicking any Customize link in Calypso — for both WP.com and Jetpack sites — will open a Customizer session "within" Calypso. Meaning the URL changes to `/customize/example.com` and doesn't redirect to a URL with `wp-admin/customize.php`. Visually keeping site authors within the Calypso context. Returning to Calypso when done editing.

**What actually happens**
1. Sometimes when you access the Customizer in Calypso views — such as via the three-dot menu for the currently active theme on `/design` — you enter the wp-admin URL and not the `/customize/` URL as expected.

Would be nice to streamline all these cases for a consistent experience and one canonical URL.

**Comment by melchoyce** [comment]
All ways in/out of the Customizer are documented in p6nuNy-OZ-p2, for reference.

**Comment by folletto** [comment]
> This is more a task than a bug or enhancement.

Note: we need to make sure that it works with self-hosted, as the `/customize/` route is really an `iframe` and that might get blocked.

**Comment by designsimply** [comment]
Also see #15301.

**Comment by lancewillett** [comment]
I ran into something related today — found a wrong exit flow after entering AMP settings with a Jetpack site: https://github.com/Automattic/wp-calypso/issues/15327
