### ISSUE TITLE
Purchases: Users and sites purchases not loaded correctly

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#1111]
When loading a site's purchases before a user's purchases, the collections aren't properly merged meaning that both appear in the list:

<img width="758" alt="screenshot 2015-12-01 15 25 40" src="https://cloud.githubusercontent.com/assets/275961/11504967/cd234056-983f-11e5-8d49-76d85c359170.png">

We need to ensure that they are properly merged together to prevent this happening.

**Comment by fabianapsimoes** [comment]
@scruffian when would this happen? Do we have steps to reproduce?

**Comment by scruffian** [comment]
This situation doesn't seem to happen any more; the bug has mutated. It now works like this:

If I have an account with purchases for more than one site, when I visit `/purchases` directly I see this:
<img width="545" alt="screen shot 2016-03-21 at 09 38 23" src="https://cloud.githubusercontent.com/assets/275961/13914824/de232c4e-ef48-11e5-8011-6fed1ab55e2d.png">

However if I next navigate to `/settings/general/:site`, for one of the sites with purchases, (you have to navigate, not go there directly) and then return to `/purchases`, I see this:
<img width="545" alt="screen shot 2016-03-21 at 09 38 00" src="https://cloud.githubusercontent.com/assets/275961/13914844/fdf7f284-ef48-11e5-9ddf-b9d81ada0c9e.png">

Now if I visit `/settings/general/:site`, directly and then navigate to to `/purchases` I see this:
<img width="547" alt="screen shot 2016-03-21 at 09 38 42" src="https://cloud.githubusercontent.com/assets/275961/13914851/101f3b5c-ef49-11e5-9689-6ef61c62bade.png">

The issue is that on both `/purchases` and `/settings/general/:site` we fetch a list of purchases, but they aren't the same list, so we need to handle these cases better.

**Comment by kriskarkoski** [comment]
I recently encountered this on a user's site (multiple domain subs instead of one, no cancel option on the main domain card) and noticed that once auto renewal was disabled from SA the issue went away. Re-enabling auto renew did not allow the issue to happen again so disable auto renew once "fixed" whatever was causing them to be split and have the cancel option missing.
