### ISSUE TITLE
Jetpack Plans: Autoconfig: We are still trying to install Polldaddy

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#11117]
I tried to set up a Professional Plan today and despite our having removed Polldaddy from that offering, we still appear to be trying to install the plugin (at least representing it in the UI). It ultimately caused an error:

<img width="809" alt="screen shot 2017-02-01 at 4 11 18 pm" src="https://cloud.githubusercontent.com/assets/437258/22527114/ed51192c-e89b-11e6-8782-6cba93637659.png">

We need to remove that from the UI and get rid of any code referencing it or trying to install it. 

cc @johnHackworth @lezama @ryelle @richardmuscat

**Comment by ryelle** [comment]
Looks like Polldaddy is still mentioned in the "I signed up and paid. What’s next?" FAQ:

> Our premium features are powered by a few of our other plugins. After purchasing you will need to install the Akismet and VaultPress plugins. If you purchase a Professional subscription, you will also need to install the Polldaddy plugin. Just follow the guide after you complete your purchase.

If Polldaddy is totally gone from the plan, should this also be removed?

**Comment by beaulebens** [comment]
> If Polldaddy is totally gone from the plan, should this also be removed?

Yep, we need to go through and remove it from everywhere.
