### ISSUE TITLE
People: "email followers" list doesn't show email subscribers 

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11116]
Raised by @alisterscott found during Automated Transfer testing. This isn't specific to AT as it affects any Jetpack site.

> I subscribed to posts via email on my Jetpack site and got an email confirmation:

> <img width="914" alt="screen shot 2017-01-23 at 3 57 53 pm" src="https://cloud.githubusercontent.com/assets/128826/22193070/d29d6720-e184-11e6-8575-14dd62350b1e.png">

> But the email followers screen is blank:

> <img width="965" alt="screen shot 2017-01-23 at 3 59 32 pm" src="https://cloud.githubusercontent.com/assets/128826/22193107/f4cfbc76-e184-11e6-9b9b-66b22b5e0ffb.png">

Example URL such as https://wpcalypso.wordpress.com/people/email-followers/example.wordpress.com to see the followers.

**Comment by rantoncuadrado** [comment]
I edited the title because I found another case in a non AT site


I have tried to subscribe to jesuslightworker.com site with one of my email accounts not linked to WordPress.com and confirmed the subscription email sent to raulanton@gmail.com (Image attached) but this new follower is not being shown in the people>email subscribers list at calypso (https://wordpress.com/people/email-followers/jesuslightworker.com).
If I try to subscribe with raul@automattic.com it works however and I appear on https://wordpress.com/people/followers/jesuslightworker.com

**Comment by rantoncuadrado** [comment]
![blogs i follow - wordpress com 2017-06-05 08-31-23](https://cloud.githubusercontent.com/assets/6404071/26790447/051dc1de-4a14-11e7-9838-8c147f2442ca.png)

**Comment by designsimply** [comment]
@rantoncuadrado can you please describe your steps for subscribing?

I tested with the following steps but was unable to reproduce the problem for a WordPress.com blog:

1. Start with a blog that has the Follow Blog widget active.
1. Log out of https://wordpress.com/
1. Go to a blog and subscribe using an email address not already associated with WordPress.com.
1. While still logged out of WordPress.com, check email and click the "Confirm Follow" button to confirm your subscription.
1. Check https://subscribe.wordpress.com/ and confirm the subscription there as well.
1. Log in to the blog as the blog owner.
1. Go to https://wordpress.com/people/email-followers
1. Check to see if the test email used in step 3 is listed in People > Email Followers.

<strong>Result:</strong> the email I used to subscribe and confirm following test blog design5279.wordpress.com by email was accepted and shows up properly on the People > Email Followers page.

![screen shot 2017-06-05 at mon jun 5 10 58 13 am](https://cloud.githubusercontent.com/assets/1119271/26794454/f14d479a-49de-11e7-94c9-d59240b4dce7.png)
<sup>Seen at https://wordpress.com/people/email-followers/design5279.wordpress.com using Firefox 53.0.3 on Mac OS X 10.12.5.</sup>

**Comment by rantoncuadrado** [comment]
Sure, @designsimply Thanks for the reminder.

1.- I open jesuslightworker.com in Vivaldi browser (this is to assure I have no opened session in WordPress.com)
2.- I use my email raulanton@gmail.com to subscribe as shown in the picture.
![jesus lightworker 153 fish 2017-06-05 22-01-25](https://cloud.githubusercontent.com/assets/6404071/26800733/a9b7f176-4a3a-11e7-88e9-b60e84e62e14.png)
raulanton@gmail.com has no WordPress.com accounts (https://wordpress.com/wp-admin/network/users.php?s=raulanton%40gmail.com)
3.- I receive an email to confirm my subscription. I hit on 'Confirm Follow' button.
![confirm your subscription for jesus lightworker - raulanton gmail com - gmail 2017-06-05 22-03-45](https://cloud.githubusercontent.com/assets/6404071/26800825/f4371d26-4a3a-11e7-91e8-5eae951779f3.png)
4.- A window is opened with the message 'You successfully updated your subscription!'
![blogs i follow wordpress com 2017-06-05 22-04-55](https://cloud.githubusercontent.com/assets/6404071/26800879/25c3f936-4a3b-11e7-90e4-a1f3264b5356.png)
5.- I opened a SU session to see what the user see at https://wordpress.com/people/email-followers/jesuslightworker.com (I made this in 2 different browsers to discard a cache issue) and raulanton@gmail.com is not there. 
![people jesus lightworker wordpress com 2017-06-05 22-10-27](https://cloud.githubusercontent.com/assets/6404071/26801036/d12b1e6c-4a3b-11e7-8043-53225bf067fa.png)

 Hope is clearer now and could help us better to identify the issue

**Comment by rantoncuadrado** [comment]
Update: The user says -in the ticket- they received an email with the new subscription but I can't see it on the email followers list

**Comment by rantoncuadrado** [comment]
Update: the user pinged us again on a ticket:

"Hi, I'm still not getting notifications to my email when someone subscribes. I did turn off notifications from Wordpress for likes and comments, but i'd like to be notified of subscribers and to be sure they show up on my list. I got a new subscriber, who showed up on my list -- (Wordpress member) -- but for whom I did not receive a notification.Thanks.  "

**Comment by SiobhyB** [comment]
Also came up in 3325450-t.

**Comment by ersatzpenguin** [comment]
This has also come up in 2151219-zen. Same deal, someone subscribes via email, and we can see that the email is subscribed through subscriptions admin, but it doesn't show on the blogs list of email subscribers.

**Comment by ahmadbaig1** [comment]
Same issue in 2987380-zen. I have followed them via email but it doesn't show up on the Email Followers list.

**Comment by susanjanec** [comment]
Had a chat reporting the same issue - 25277431-hc

I confirmed the email they provided is subscribed to the blog via subscription admin, but the email address isn't listed under Email Followers, the email they provided is not a WordPress.com user.

**Comment by supernovia** [comment]
I found an instance of this, I think, here:
https://wordpress.com/forums/topic/list-of-subscribers-to-blog/

Some email followers are showing and some are not.

**Comment by supernovia** [comment]
Here is another case where some email followers are not showing on the list:
https://wordpress.com/forums/topic/problems-with-subscriber-registrations/

**Comment by andres-blanco** [comment]
I managed to reproduce this issue. When a user follows a post comment with only email (non wp.com user) you wont see the email here

1. Follow a post comments with email (without being logged in) 
![image](https://user-images.githubusercontent.com/375980/128396290-f7e158f3-07a3-444b-95e2-9485a8565625.png)

1. Confirm follow through email 
![image](https://user-images.githubusercontent.com/375980/128395305-be1af193-eee8-404d-af12-3ab21820ba6e.png)

## Expected
View the follower email here: https://wordpress.com/people/email-followers/MY_SITE

## What happened
I don't see the email on the list

**Comment by Nic-Sevic** [comment]
another case here: 29988221-hc

**Comment by csabarakasz** [comment]
It seems like this 5203998-zd-woothemes is the same case. Although when I tested it, I could subscribe to the blog and I showed up as an email follower. So not sure.

**Comment by formosattic** [comment]
I did a quick test:

* Simple site, no option to see the subscribers email address
* Atomic site, the Users page in Classic View will display the email address

Flagged this as featured request for PA/PQA to review.

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO

- **Could not replicate the original issue on any test site**. 

There are quite a few different scenarios described in the comments on this report. There may still be something to uncover that might be interrupting the process, but that may be a symptom of another issue - perhaps a Jetpack sync issue or something. The original issue of email followers not appearing in the Email Followers area seems to be working as expected. See test results below.

### Steps taken for all Sites tested:

- Created a page on the site with the Jetpack Subscribe block
- Signed up to subscribe using one gmail account, not associated with any WordPress.com accounts
- In a separate browser, opened the email and confirmed my subscription for the site
- Confirmed I am following the site on the `subscribe.wordpress.com` page

![Markup on 2022-06-28 at 10:05:39](https://user-images.githubusercontent.com/27249804/176241619-4e9b0b04-c9e3-4c2b-ad81-032542e6044e.png)

### Simple Site:

Under `Users > Email Followers`, I see my new email follower:

![Markup on 2022-06-28 at 10:01:03](https://user-images.githubusercontent.com/27249804/176239891-727c9fac-a805-4e3b-869a-9522e205e628.png)

### AT Site:

Under `Users > Email Followers`, I see my new email follower:

![Markup on 2022-06-28 at 10:01:49](https://user-images.githubusercontent.com/27249804/176240227-25cb92d9-2c20-4437-9fa0-20d8b43ff372.png)

### Self-Hosted Site:

Under `Jetpack > Settings > Discussion > View your Email Followers`, I see my new email follower:

![Markup on 2022-06-28 at 10:03:11](https://user-images.githubusercontent.com/27249804/176241099-23d48ea4-b7da-4359-9308-e7c7e3ef2e42.png)

![Markup on 2022-06-28 at 10:03:57](https://user-images.githubusercontent.com/27249804/176241155-bb993ef9-6dd1-47c4-bd57-3f8e0021504d.png)

### Subscribing via Comment Form

Also tested the process @andres-blanco mentioned - subscribing through the comment form. For this test, I left a comment on a new AT site, and checked the box **Notify me of new posts via email** - the option to subscribe to the blog itself.

![Markup on 2022-06-28 at 10:16:28](https://user-images.githubusercontent.com/27249804/176243927-65521ebe-0e98-4101-8891-4666da9f00eb.png)

I confirmed the subscription in the email, and saw it appear in the `subscribe.wordpress.com` page.

Back on the AT site, the new email follower appears as expected under `Users > Email Followers`

![Markup on 2022-06-28 at 10:18:38](https://user-images.githubusercontent.com/27249804/176243912-99e471eb-3dcb-462a-b5b1-8aec1facb2ab.png)

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - Given these tests, it seems likely that the cases where an email follower is missing on a user's site has more details than just the email follower process not working as intended.  If someone finds a detail that uncovers why an email follower might not appear here and can replicate it on a test site, I suggest opening a new report with that particular set of instructions to replicate the issue. Thanks!
