### ISSUE TITLE
Redux: Move current search string state to global state

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#1112]
I'm talking about this:
![Search](https://cldup.com/JcVCIgeMJH-3000x3000.png)
# Search term for posts / pages

Currently it is held in:
- state of Search component
- controller of my-sites/posts.
- Current url `?s=searchterm`

This is a problem when switching sites, so I made this workaround:
https://github.com/Automattic/wp-calypso/pull/1091/files#r46399468

But I think it would be best if:
- search term was in Redux store
- changing url dispatched a redux action (or the other way around? we need 2-way binding here)
- components would just read from the store

Currently, all of this feels kinda hack-y

**Comment by lancewillett** [comment]
@artpi Do you suggest adding a new label for Redux work? Or maybe a new milestone?

**Comment by artpi** [comment]
I got sucked into hangouts, but I promise to describe in detail :) Problem I see right now is that search string is held in URL / component - I will describe when I find a moment

**Comment by artpi** [comment]
Also:
In the whole component tree above, siteID is either boolean or string.
Need to clean up this prop.

**Comment by lancewillett** [comment]
See also #453
