### ISSUE TITLE
Media Section: Consider replacing back button with close button for edit modal.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#11133]
This has been raised in internal testing. 

Currently the button in the modal in the section is identical to the one in the modal in the editor. However, the button behaves differently in the section — it closes the modal, therefore it should be X like the one in Post Preview. It's minor, but the logic makes sense.

![screen-shot-2017-02-02-at-16 23 57-b_02](https://cloud.githubusercontent.com/assets/908665/22571885/a1bd99d2-e999-11e6-89bb-03b8824eb48a.jpg)

![screen-shot-2017-02-02-at-16 23 57_02](https://cloud.githubusercontent.com/assets/908665/22559293/917fb43c-e968-11e6-9674-4515728ff107.jpg)

Any thoughts?

**Comment by folletto** [comment]
> Any thoughts?

In general, I'm ok with the idea. Even if I'd note that currently it's made to match the Reader, which uses the same pattern, even if it's full screen.

However, I'd note that our modals don't use top controls to close it: they either have a way to close by clicking outside, or with a button in the bottom-right corner.

> This has been raised in internal testing.

I'd consider this question: has been raised as in "I don't know how to close this dialog" or raised as in "I think an X is clearer"? ;)

**Comment by iamtakashi** [comment]
The "back" button in the reader does makes sense because it's full screen, not a dialog / modal like this.

> However, I'd note that our modals don't use top controls to close it: they either have a way to close by clicking outside, or with a button in the bottom-right corner.

A good point. I've actually suggested to add a cancel button to the modal in #11024.

 > I'd consider this question: has been raised as in "I don't know how to close this dialog" or raised as in "I think an X is clearer"? ;)

I guess it was based on this mental model:

* "Back" makes sense if the size of the "window" is the same between current and previous.
* "Close" makes sense if the "window" is smaller and feels like a part of the page.

It's kinda hard to put in words, but I hope it makes sense somehow.

Anyway, once we have the "Cancel" button, can we get rid of the control as we don't really need it?

**Comment by folletto** [comment]
> Anyway, once we have the "Cancel" button, can we get rid of the control as we don't really need it?

Yep. :)

**Comment by iamtakashi** [comment]
Thanks. I'm closing this in favour of #11024.
