### ISSUE TITLE
Contact Form: Automated Emails in wrong language

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#11141]
#### Steps to reproduce
1. Set account to Spanish or Portuguese
2. Go to Contact Form: https://wordpress.com/help/contact
3. Send an email

#### What I expected
'Your WordPress.com Support Question' email should arrive in Spanish or Portuguese

#### What happened instead
In both cases (ES and PT-BR) the automated email arrived in English

#### Browser / OS version
Firefox 51.0.1 / macOS Sierra 10.12.3

#### Screenshot / Video
<img width="689" alt="screen shot 2017-02-02 at 3 20 11 pm" src="https://cloud.githubusercontent.com/assets/25516017/22570523/abd5e486-e969-11e6-9fb2-ad80d13d9258.png">

#### Context / Source
I tested it manually in Spanish, and asked @liviopv to help me out by testing it in Portuguese. 

#manual-testing

**Comment by dllh** [comment]
Addressed in p2UL9c-3eP-p2. Translations'll need to be added for the strings that will soon be newly available for translation. Once the strings are translated and the fix confirmed working, we can close this.
