### ISSUE TITLE
Jetpack error: Pill notice is wordy and awkward

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#11177]
#### Screenshot / Video

![screen shot 2017-02-03 at 4 24 00 pm](https://cloud.githubusercontent.com/assets/618551/22610928/8f4872c4-ea2d-11e6-976b-ec2e19575eea.png)

I think adding actions to pill notices are a recent addition. We should make sure that these buttons are 2 words at most, or perhaps consider using a different type of notice.

#### Suggestion

`Update Jetpack`

cc @rickybanister

**Comment by rickybanister** [comment]
cc @johnHackworth let's discuss where this is coming from.

Agreed, if you can't retrieve settings without updating Jetpack, this should say `We can't retrieve your settings | Update Jetpack` with no dismiss button.
