### ISSUE TITLE
Image Editor: editing image before editing for site icon

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#11174]
![screen shot 2017-02-03 at 3 44 29 pm](https://cloud.githubusercontent.com/assets/618551/22609657/aefc49e8-ea27-11e6-8f7d-3bb03e2503f9.png)

#### Steps to reproduce
1. Click change
2. Click on pencil icon
3. Click edit image, make edits
4. Click Done
5. Click Continue
6. I'm editing it again??

#### What I expected

To pick an image, click continue, Crop it to a square, Done

#### What happened instead

I was somehow able to make edits to images before selecting an image to be used as the site icon. Also found it weird that I could edit caption and everything for just selecting a site icon image.

#### Screenshot / Video

![feb-03-2017 15-52-39](https://cloud.githubusercontent.com/assets/618551/22610194/e6dd4702-ea29-11e6-8acb-273d7e7b40ef.gif)

#### Suggestion

To disable the pencil icon shown on hover

cc @gwwar

**Comment by gwwar** [comment]
At the moment image editing in the media modal is only enabled in dev/wpcalypso, so the site icon flow should be ok for now. We'll want to fix this before the image editor feature flag is switched on. 

cc @aduth

**Comment by aduth** [comment]
Hmm. Part of me says there's no need to restrict a user from being able to edit image details if they so choose, but a point could be made for providing only the paths toward their current objective of assigning a site icon.

I don't really see it being a blocker to our launch of site icon. It's two distinct flows, but confusion arises since they're colocated (as you've discovered, easy to edit then proceed with icon flow).

**Comment by drw158** [comment]
Yep, exactly, it's superfluous and could raise questions. It would be a better experience if the pencil icon were disabled.

**Comment by iamtakashi** [comment]
I agree. The pencil icon makes the flow confusing. 

The pencil icon has been an issue for some other cases too, and I've [suggested to remove](https://github.com/Automattic/wp-calypso/issues/9136#issuecomment-277302605) it entirely.

**Comment by iamtakashi** [comment]
It's better now because the pencil edit's gone, but it'd be even better if we can disable the "edit" and "delete" from the action bar for this flow.

![image](https://cloud.githubusercontent.com/assets/908665/24048346/771048bc-0b20-11e7-819f-bab21ac96923.png)
