### ISSUE TITLE
Jetpack Connect: User-only connections should redirect back to wp-admin

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#11179]
Currently, if you connect a secondary user within a site to a WP.com account, you are dropped in Calypso after completing the connection. You should be dropped back in wp-admin.

- Install/configure/connect a new Jetpack site
- Add a second user to the site. Log out and log back in as that user.
- Go to the Jetpack screen within wp-admin, and see the prompt to connect your account (or try to configure Settings > Sharing (Publicize)).
- Log into a WP.com account and authorize the connection
- End up in Calypso (on the My Plan page).

The last step should ideally redirect you back to where you started that flow, in this case, the Jetpack dashboard within wp-admin on the remote site.

**Comment by beaulebens** [comment]
I've just confirmed that this is still an issue. Here a few screenshots that show the flow that I see as a secondary Admin on an already-connected site.;

![screen shot 2018-03-30 at 11 15 38 am](https://user-images.githubusercontent.com/108942/38146712-5bd77730-340c-11e8-9ddf-c4419b791483.png)
![screen shot 2018-03-30 at 11 15 45 am](https://user-images.githubusercontent.com/108942/38146715-5f707f72-340c-11e8-9e44-aa47b525bdfa.png)
![screen shot 2018-03-30 at 11 16 00 am](https://user-images.githubusercontent.com/108942/38146716-61dd1220-340c-11e8-85a2-15a83c854585.png)
![screen shot 2018-03-30 at 11 16 40 am](https://user-images.githubusercontent.com/108942/38146717-63e20288-340c-11e8-9abd-2bda54b8b52c.png)
![screen shot 2018-03-30 at 11 16 58 am](https://user-images.githubusercontent.com/108942/38146719-67421e86-340c-11e8-8944-61469eee92d5.png)

**Comment by johnHackworth** [comment]
I've just tested and this is not an issue anymore (connecting an editor I was not shown the plans page and was redirected correctly to wp-admin after finishing)
