### ISSUE TITLE
Menu Items Limit 

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#11187]
Currently, if you try to add more than 7 menu items through wordpress/menus (Calypso), the menu items are not displayed properly. In some cases:
- some of the menu items disappear;
- the new items are simply not added;
- the menu items are not displayed in the proper order.

Adding more than 7 menu items works properly through wp-admin or https://wordpress.com/customize. 

Tested with two themes - Affinity and Twelve Eleven - it did not work for either of them through wordpress/menus.

**Comment by mcsf** [comment]
I wasn't able to reproduce the issue, could you provide more details? For instance:

> some of the menu items disappear

Do they disappear from the Menus UI? Does this happen at random times, or when adding a new item, or when saving? Or do they disappear from the front-end?

The same questions apply for the following:

> some simply not added

> not displayed in the proper order

Is it the order in the Menus UI or the front-end? Are items not added after saving? etc.

**Comment by mcsf** [comment]
Also, more details on the initial conditions might be useful, e.g. were the edits made to an existing menu (e.g. "Menu 1" in "Primary Location"), and was that menu empty or populated? Or were the edits made on a blank Menus configuration (i.e., on top of "Default Menu"?

**Comment by lancewillett** [comment]
Have discussed previously with the original poster and explained already that we are dropping Menus support in Calypso in favor of the Customizer menus. See https://github.com/Automattic/wp-calypso/issues/4610 for context.
