### ISSUE TITLE
Checkout: Fix wrong page displayed at the end of domain-only signup flow

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#11199]
This problem was spotted in https://github.com/Automattic/wp-calypso/pull/11146 and https://github.com/Automattic/wp-calypso/pull/11183.

#### Steps to reproduce
 
1. Run `git checkout master` and start your server, or open a [live branch](https://calypso.live/?branch=master)
2. Open the new [`Signup` page](http://calypso.localhost:3000/start/domain-first) in incognito mode
3. Proceed to the `Contact Information` page
4. Use administration tools to add free credits to the new user account
5. Proceed and purchase the domain with the credits

#### What I expected

I was expecting to be redirected to the [`Domain Management` page](http://calypso.localhost:3000/domains/manage/:domain) with this content:

<img width="633" alt="screenshot" src="https://cloud.githubusercontent.com/assets/594356/22658918/14c7437e-ec9c-11e6-9495-b762bcf3bc0c.png">

#### What happened instead

Most of the time I was redirected to the `Domain Management` page but with this content:

<img width="633" alt="problem" src="https://cloud.githubusercontent.com/assets/594356/22659149/d335e978-ec9c-11e6-9749-c5cdc515a6a6.png">

One time I was redirected to the [`Thank You` page](http://calypso.localhost:3000/checkout/thank-you/features):

<img width="633" alt="bigproblem" src="https://cloud.githubusercontent.com/assets/594356/22659217/1ec4df48-ec9d-11e6-839c-4db5e9c3e465.png">

#### Browser / OS version

Chrome latest.

#### Context / Source

As mentioned [here](https://github.com/Automattic/wp-calypso/pull/11183#issuecomment-277751112), this seems to be the result of race conditions. I suspect that since [we perform the redirection asynchronously](https://github.com/Automattic/wp-calypso/blob/68272ef5e754d9c6dc76453dd073e5e2caa53411/client/my-sites/upgrades/checkout/checkout.jsx#L286-L288) there might be a moment where the shopping cart is empty (when the transaction succeed but we are still fetching the user and the list of sites). [In that case](https://github.com/Automattic/wp-calypso/blob/68272ef5e754d9c6dc76453dd073e5e2caa53411/client/my-sites/upgrades/checkout/checkout.jsx#L141-L165), [we push a route to `/domains/add/:domain`](https://github.com/Automattic/wp-calypso/blob/68272ef5e754d9c6dc76453dd073e5e2caa53411/client/lib/checkout/index.js#L17) which is [not allowed for `domain-only` sites](https://github.com/Automattic/wp-calypso/blob/68272ef5e754d9c6dc76453dd073e5e2caa53411/client/my-sites/controller.js#L132-L141), thus resulting in rendering this `This feature is not available for domains` message.

**Comment by aidvu** [comment]
Fixed a while ago.
