### ISSUE TITLE
Cart: annual subscription appears on one time purchase items

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#11197]
A user reached out in the forums to clarify if a premium theme would be renewed annually: 
http://en.forums.wordpress.com/topic/pricing-structurebuying-a-theme

They noted an "annual subscription" message on the right hand side of the cart. 

After adding a premium theme to a test site I also saw the "annual subscription" message on the right side of my screen. This message also appears with a  Guided Transfer purchase. 

Support Details:
![screen shot 2017-02-06 at 11 56 01 am](https://cloud.githubusercontent.com/assets/16867830/22657169/881825b6-ec63-11e6-945c-af56ada0fe5c.png)

Cart with "annual subscription" message:
![screen_shot_2017-02-06_at_11_41_58_am](https://cloud.githubusercontent.com/assets/16867830/22657271/ebd16176-ec63-11e6-8ac6-9e038ab25509.jpg)
![screen shot 2017-02-06 at 11 45 05 am](https://cloud.githubusercontent.com/assets/16867830/22657272/ebd30616-ec63-11e6-8ba8-5374d17d60e3.png)

**Comment by KokkieH** [comment]
Another report in 831168-f

**Comment by menakas** [comment]
Another report in #231986-chat

**Comment by nunyvega** [comment]
Another report in 3147526-t

**Comment by rachelmcr** [comment]
I tested and can no longer reproduce the issue for premium themes — the cart now correctly describes it as "never expires":

![screenshot 2017-12-13 14 48 40](https://user-images.githubusercontent.com/8658164/33944751-ee6f16da-e014-11e7-9bc1-a3292d6d76db.png)

However, Guided Transfers still show up as an annual subscription:

![screenshot 2017-12-13 14 49 27](https://user-images.githubusercontent.com/8658164/33944770-fb0b7c1c-e014-11e7-9db8-1a3ec0720edd.png)

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
This is fixed in the new Checkout. Closing.
