### ISSUE TITLE
Billing History: Product name strings don't show existing translations

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#112]
Product names aren't translatable in `/me/billing`, in both the transactions table and the receipts:

![screen shot 2015-11-18 at 5 23 45 pm](https://cloud.githubusercontent.com/assets/8658164/11248562/a82fc876-8e19-11e5-9d73-cea0f4388c68.png)

![screen shot 2015-11-18 at 5 22 10 pm](https://cloud.githubusercontent.com/assets/8658164/11248567/ab6a9afc-8e19-11e5-9e85-b65a50e692e6.png)

WordPress.com Premium, for example, does have <a href="https://translate.wordpress.com/projects/wpcom/ja/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=61882&filters%5Btranslation_id%5D=1841605">a translation</a> in GlotPress.

Receipts for new purchases show the phrase `(new purchase)` next to the product name, but I could not find a corresponding string in GlotPress. Refund receipts show the word `(refund)` next to the product name, and that string shows in English on receipts, even though it <a href="https://translate.wordpress.com/projects/wpcom/ja/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=44337&filters%5Btranslation_id%5D=1438785">has a translation available in GlotPress</a>.

**Comment by kwight** [comment]
This is still an issue 😱

![screen shot 2018-02-14 at 12 32 46 pm](https://user-images.githubusercontent.com/349751/36226671-57a368f0-1183-11e8-8ddf-738f297bcf4c.png)

**Comment by kwight** [comment]
d10289-code in progress.

All copy for these products come translated from the server-side on the `/me/billing-history` endpoint. The above patch will add more fine-grained handling for our variey of products, covering a greater percentage of receipt items viewed in Calypso.
