### ISSUE TITLE
Site Icon: return to original location where you started changing the icon

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11207]
When I click to change my site icon in Calypso, I want to be brought back to Calypso when I’m done. Right now I’m dropped back at https://wordpress.com/, not back to where I was when I clicked “Change”.

Notes from @beaulebens 

> I just dug into this, and I think maybe we’re double-encoding or something on the return parameter that we pass when linking to the Customizer on Jetpack sites.
> 
> e.g. ?return=https%253A%252F%252Fwordpress.com%252Fsettings%252Fgeneral%252Fdentedreality.com.au

**Comment by lancewillett** [comment]
Possibly related: #10431

**Comment by aduth** [comment]
While it primarily affects site icon, the issue is specific to the selector for generating a customizer URL. Likely at this point:

https://github.com/Automattic/wp-calypso/blob/e0d5cf9/client/state/sites/selectors.js#L979-L982

**Comment by aduth** [comment]
Might be that we don't need the `encodeURIComponent` at the line if we proceed to pass it through to the `addQueryArgs` utility.

**Comment by lancewillett** [comment]
Will be fixed once changes in #11210 are merged, props @aduth .
