### ISSUE TITLE
Domains: improve domain privacy messaging to allow authors to edit contact information without contacting support

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11208]
Raised by @cecoates 

When trying to edit my Domain Contact Information, it informs me that I need to contact support:

![screen-shot-2017-01-29-at-01-09-11](https://cloud.githubusercontent.com/assets/66797/22664139/8aa26fae-ec6c-11e6-8b0e-1d1d5424ffba.png)

With this workflow, I need to contact support, have them disable privacy, edit my contact information, then ask support to re-enable privacy, even if all I want to do is correct a typo in my email address so I can verify my domain.

However, if I click on the transfer tab instead, I may realize that I can disable privacy myself by unlocking the domain:

![screen-shot-2017-01-29-at-01-09-27](https://cloud.githubusercontent.com/assets/66797/22664151/96cfedd8-ec6c-11e6-8ae9-5a93f05b6ab3.png)

After which I can then edit my domain contact information, after which I can then re-lock the domain and re-enable privacy. There should be a more intuitive way for me to disable privacy myself at the contact information area, or all disabling of privacy and domain unlocking should be support only, not a mixture of both.

**Comment by lancewillett** [comment]
See also https://github.com/Automattic/wp-calypso/issues/2478

**Comment by umurkontaci** [comment]
Historically, toggling privacy on and off has been a huge problem as it doesn't work as reliably as we expect at WWD. That's the reason we didn't put an option to disable privacy and you can't the change contact information when privacy is enabled (again, not our requirement).

Things are a little bit better with HRS/SRS, you can change the contact information while privacy is enabled, but you still cannot toggle privacy except in transfer-flow.

I guess we can allow privacy toggling for HRS/SRS domains; but I'm not sure if it's a high priority at this point.

**Comment by lancewillett** [comment]
Here's a much longer anecdote (on a private Automattic site) in case anyone wants a bit of context: p4k3M4-2gQ-p2.

**Comment by lancewillett** [comment]
Umur updated me on this: since we're using HRS/SRS for new domains from now on — and in those cases you can update contact information when privacy is enabled — I think we should close this as "worksforme". Not worth the effort to update for older domains, and they'll be migrated soon also.
