### ISSUE TITLE
Posts: add ability to edit a comment, either my own — or any comment on a site I manage — in the context where I see the comment

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11209]
Right now in Calypso it's not easy to edit a comment. This task would add contextual comment editing.

**Comment by drw158** [comment]
Here are some design for moderation/editing. Theoretically, this could be applied to the Comment component, so you could moderate anywhere.

Mockups are done in My Sites > Posts. I imagine these moderation controls could show up in the Reader, but not shown pending, spam, etc. comments.

These are quick mockups, I didn't use the correct icons.

Segmented control to filter. Moderation actions are shown inline with Like and Reply:

![artboard](https://cloud.githubusercontent.com/assets/618551/23086690/28d3c0b8-f534-11e6-9bab-96df2021ed03.png)

If the viewport is too narrow:

![artboard copy](https://cloud.githubusercontent.com/assets/618551/23086722/6a74de58-f534-11e6-968b-9b07b16ce280.png)

Pending comment alongside approved comments:

![artboard copy 2](https://cloud.githubusercontent.com/assets/618551/23086773/b8e2d202-f534-11e6-930e-b90169ac58ec.png)

Deleting a comment:

![artboard copy 3](https://cloud.githubusercontent.com/assets/618551/23086783/cc44fd52-f534-11e6-90d0-2326d247f534.png)

Interestingly, the All filter does not show trashed comments. This is true in wp-admin.

**Comment by alisterscott** [comment]
Is there any reason we can't see comments on pages in the Calypso UI as well? It seems to be missing completely.

**Comment by alisterscott** [comment]
Update, we now have a comments link on each post which takes us directly into /comments which I think closes this issue:

![comments](https://user-images.githubusercontent.com/128826/34233569-e6366342-e631-11e7-8704-644429a6f4d9.gif)
