### ISSUE TITLE
Toggles: flex layout bug on plugin page

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#11212]
I noticed the plugin toggles are displaying improperly when in the 'active' position on plugin pages:

<img width="762" alt="screen shot 2017-02-06 at 4 08 54 pm" src="https://cloud.githubusercontent.com/assets/437258/22666481/b57601c2-ec86-11e6-9e1b-cc005cdaeaad.png">

Could this be related to making the labels clickable in our  /settings work? 

cc @tyxla @johnHackworth @MichaelArestad

**Comment by tyxla** [comment]
@rickybanister this appears be related with #11158 where we changed labels toggle the toggle fields. The plugin page appears to have some additional styling on the form toggle that should be removed. I'll prepare a PR.
