### ISSUE TITLE
Holiday Snow settings: add site and user option

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#1123]
It's December 1st! Snow is back on WordPress.com and Jetpack sites, and will fall until January 4th.

There are 2 settings related to that feature:
1. A site setting, available under Settings > General in wp-admin. I didn't find that option in the API when looking at the `sites/%ID` endpoint.
2. A user setting, that used to be available in the account settings, but that wasn't ported to Calypso. It allows WordPress.com users to disable snow for all WordPress.com blogs, when they're logged in. The option is available in the API, via the `/me/settings/` endpoint (option name is `holidaysun`).

It would be nice if both options were made available in Calypso.

**Comment by lancewillett** [comment]
User setting added in PR: #1138 

Site setting is pending a PR

**Comment by Viper007Bond** [comment]
Oops.
