### ISSUE TITLE
My Site: preview no longer works, home icon link goes to new tab/window

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11238]
Reported by @mtias 

This is a significant regression. Need to track down when it broke, and fix it.

Should also consider a [smoke test](https://github.com/Automattic/wp-e2e-tests) for it.

#### Steps to reproduce
1. Starting at My Site(s).
2. Hover over the site title (home icon) at the top of the sidebar, and click.

#### What I expected
The site link should show up in a preview with an overlay.

#### What happened instead
The site link opens in a new tab or window.

![new-window](https://cloud.githubusercontent.com/assets/66797/22701716/aca0af3a-ed1b-11e6-8b71-9f8a231b1a9f.gif)

**Comment by mcsf** [comment]
@lancewillett @matias thanks to `git-bisect` I've tracked this down to @ockham 's 1ca3a6115be66a5b1f888b705d9cdbc38e571082 (#7724) and its changes to `Site`:

```diff
diff --git a/client/blocks/site/index.jsx b/client/blocks/site/index.jsx
index e9bd9fe..570a6f1 100644
--- a/client/blocks/site/index.jsx
+++ b/client/blocks/site/index.jsx
@@ -19,7 +19,6 @@ export default React.createClass( {
                return {
                        // onSelect callback
                        onSelect: noop,
-                       onClick: noop,
                        // mouse event callbacks
                        onMouseEnter: noop,
                        onMouseLeave: noop,
@@ -48,7 +47,6 @@ export default React.createClass( {
                isSelected: React.PropTypes.bool,
                isHighlighted: React.PropTypes.bool,
                site: React.PropTypes.object.isRequired,
-               onClick: React.PropTypes.func,
                homeLink: React.PropTypes.bool,
                showHomeIcon: React.PropTypes.bool
        },
@@ -98,8 +96,7 @@ export default React.createClass( {
                                                ? this.translate( 'View this site' )
                                                : this.translate( 'Select this site' )
                                        }
-                                       onTouchTap={ this.onSelect }
-                                       onClick={ this.props.onClick }
+                                       onClick={ this.onSelect }
                                        onMouseEnter={ this.onMouseEnter }
                                        onMouseLeave={ this.onMouseLeave }
                                        aria-label={ this.props.homeLink && site.is_previewable
```

Right now the preview isn't triggered because of the following bail, in that same component:

```js
onSelect( event ) {
	if ( this.props.homeLink ) { // <---- this here
		return;
	}

	this.props.onSelect( event, this.props.site.slug );
	event.preventDefault();
},
```

That particular check was introduced by @aduth in 8063301c88556c064b2cfe8abf559ca55e8e8320. Is there a compelling reason to keep it?

**Comment by aduth** [comment]
>Is there a compelling reason to keep it?

We'll want to check against regressions for #1881

Based on 8063301 and 1ca3a61, I'm guessing `event.preventDefault` is important to ensuring that the overlay is shown.

**Comment by aduth** [comment]
From https://github.com/Automattic/wp-calypso/issues/1881#issuecomment-166413470 :

>I think we need to bypass the [`onSelect` logic](https://github.com/Automattic/wp-calypso/blob/e7693c5/client/my-sites/site/index.jsx#L55-L58) when `this.props.homeLink` is true, since this handler is used for the `onTapTouch` event in preventing the normal link behavior.

**Comment by ockham** [comment]
> I've tracked this down to @ockham 's 1ca3a6115be66a5b1f888b705d9cdbc38e571082 (#7724) and its changes to `Site`:

Uh, bummer 😞
