### ISSUE TITLE
Free Trials: A/B Test: Alternative Thank You page design

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1124]
The no-cc Free Trials will launch with a minimally modified version of our current thank you page. However, the thank you page will be one of several important points in the No-cc Free trial flow where it's important to encourage engagement. So we want to quickly try to beat the performance of that design.

#### Business version
![thanks-page-business-v3](https://cloud.githubusercontent.com/assets/12596797/9966350/607ede0c-5e0a-11e5-8045-ec1af7076e70.png)

#### Premium version
![thanks-page-premium-v3](https://cloud.githubusercontent.com/assets/12596797/9966351/60800d40-5e0a-11e5-9a01-b9580b618af1.png)

#### Business version
<img width="987" alt="xe9mjk7h8s-3000x3000" src="https://cloud.githubusercontent.com/assets/3011211/9550612/308ccb6e-4d61-11e5-91a9-960994a81555.png">

#### Premium version
<img width="991" alt="ymxp2zml-0-3000x3000" src="https://cloud.githubusercontent.com/assets/3011211/9550613/30910b2a-4d61-11e5-84bf-e147d4e08ed6.png">

**Comment by mikeshelton1503** [comment]
Mobile version:

### Mobile
![thanks-page-premium-v3-mobile](https://cloud.githubusercontent.com/assets/12596797/9966352/6081dd0a-5e0a-11e5-917b-81f50e1dd087.png)

**Comment by designsimply** [comment]
Moved to https://github.com/Automattic/wp-calypso/issues/2484

**Comment by fabianapsimoes** [comment]
A few notes:

- We need to update this copy to take into consideration the removal of eCommerce plugins.
- What does the top banner look like for plan purchases vs activating a trial?
- I talked to @Jstachurski about the "Start a Chat" button in the Business plan version. Chat is currently available from 7 to 19 EST, so depending on when the user sign up they won't actually be able to start a chat. Should we keep the copy of the button like in Premium? (Ask a question)
- Do we have copy for domains products (mapping, registration, registration with privacy, Google Apps, site redirects)?

**Comment by fabianapsimoes** [comment]
Closing this in favor of 2484, since we agreed to merge the new design without testing it.
