### ISSUE TITLE
Image Editor: needs to work on jetpack

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#11241]
this is a blocker level issue

**Comment by aduth** [comment]
Is there context for this? We use the image editor for Jetpack sites in the site icon flow without issue. The only gotcha is that it requires Photon to be enabled on the site. In some discussion with @gwwar, I pointed out that we may not need to be considering this at all (i.e. can't imagine why it wouldn't work with Photon disabled).

**Comment by gwwar** [comment]
The media modal uses a new edit endpoint ( edit vs copy workflow). We need to spin up a Jetpack PR to get back to parity.

**Comment by aduth** [comment]
Oh right, sorry, forgot about the separate endpoint revisions. (This doesn't affect site icon because we upload new media, not replace existing)

**Comment by rralian** [comment]
This has been addressed, I've tested using my own Jetpack test site and I'm successfully able to edit images.
