### ISSUE TITLE
Me: My Profile: Profile Links "Add" actions should be separate 

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#1127]
The Me → My Profile → Profile Links list currently has a design pattern that doesn't match existing flows, and tried to do too much inline instead of leading to a separate "Add" action.

Current UI demo:

![licecap-](https://cloud.githubusercontent.com/assets/4389/11508405/9ff5ca70-9850-11e5-95ce-b8a735dd4f65.gif)

This needs a redesign, but as a starting point a good exploration could begin with:
1. Having just one "Add" button.
2. A UI with consolidated sites choice and custom URL, either by swap (tabs?) or smart search.
3. That UI should be on a separate page (to be accessible with a direct URL) or dialog.

From a discussion on #808.

/cc @mtias @alternatekev

**Comment by alternatekev** [comment]
That sounds pretty good to me. The animated gif there made it really hard to read what you wrote though, I had to make my browser shorter in order to hide it :)
