### ISSUE TITLE
Plans: Tracks failing when a plan is added to cart

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#11288]
#### Steps to reproduce

- In staging or on local host, select one of your sites
- Navigate to plans page `/plans/$site`
- Open your javascript error console
- Click 'Upgrade'
- See this error:

![screen shot 2017-02-08 at 9 32 39 pm](https://cloud.githubusercontent.com/assets/2694219/22767515/a7dbb402-ee49-11e6-906d-45077e6fb7cf.png)

**Comment by jeremeylduvall** [comment]
@roccotripaldi Did a bit of bug scrubbing. I'm no longer experiencing this through the steps described above. Can you confirm?

**Comment by roccotripaldi** [comment]
Confirmed! Thanks for the follow-up. Closing issue.
