### ISSUE TITLE
Framework: include file with default config values

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1128]
We have few config values, which are the same in all environments:

```
[ 'api_transport',
  'i18n_default_locale_slug',
  'rtl',
  'paygate_keys',
  'languages',
  'analytics_event_whitelist',
  'analytics_property_whitelist' ]
```

Some of them are long and copy/testing seems tedious and error-prone. Also, adding a new config key often means adding it to all configs, which is slightly annoying.

Do you think this is a problem? If yes, what’s the best solution?

My first reaction is to have a `common.json`, which is loaded in all environments.

I'd like to rework how we handle the configs so that we can build a single bundle and then process that bundle to remove dead code and minify when creating the builds for `production` and `stage`. This would remove `client/config/regenerate.js` and simplify the build process.

**Comment by gziolo** [comment]
https://github.com/Automattic/wp-calypso/pull/876 tries to solve the same issue.
