### ISSUE TITLE
Medium import: Image URLs are not updated

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#11291]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/
2. Upload the Medium export archive and wait for the import to finish.
3. Inspect the image URLs of your imported posts.
4. Notice that they are pointing to Medium CDNs.

#### What I expected

During the import process the images should be downloaded to media library, and their URLs in posts should be updated so they don't point to Medium anymore.

**Comment by vindl** [comment]
Resolved in D4336-code.

cc @hoverduck

**Comment by alisterscott** [comment]
Thanks for the quick fix, is this live now?

I just tried a new import (to the same test site) but the new post still has Medium CDN urls and I can't see any of the media in my library.

Test post: https://mttestmediumsite.wordpress.com/2017/02/09/a-story-here-about-bush-walking/

**Comment by vindl** [comment]
@alisterscott Sorry about that, the above-mentioned diff is not yet deployed.

**Comment by vindl** [comment]
Fix deployed.
