### ISSUE TITLE
People: API endpoint for creating a new invite

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#113]
For WPCOM, users must be added to a site via invite.

For .org sites, the process is much different. For single sites, there is no invitation process. For multisite, users can either be invited or directly added.

POST /sites/$site/invites/new

For m7, let's go ahead and focus on creating invites for WP.com sites.

**Comment by ebinnion** [comment]
This was committed by @roccotripaldi in r130117-wpcom
