### ISSUE TITLE
Framework: Design and document an improved approach to data flow and data module design - Flux

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1130]
We've learned a lot about React and various approaches to data flow in JavaScript apps that use React for the view layer. It is time to take what we have learned to refine our approach.

1. Must be simple and easy to understand. The existing approach fulfills this goal. Any changes must also be simple and easy to understand. For example, notification of data changes should continue to be simple. The `change` event has served us well. 

2. It should be obvious where to put code of a certain purpose. If it is obvious where something goes, we're more likely for there to be consistency.

3. Separate data from the logic that operates on the data so that when appropriate we can use immutable data structures or pseudo-immutable data structures. React components have a notion of previous and next props/state that crave immutable data. When there is a change to a particular piece of data, we should be able to compare the next and previous states to determine if something actually changed.

4. AJAX calls should be easily separated from the data and other logic, and there should be a clear way for an AJAX response to update multiple data stores.

5. Errors and initialization should be addressed.

6. Realtime and polling should fit naturally into the solution.

7. Caching in localStorage should be optional but available (ideally with an abstraction) and handling the cached vs. uncached should require as little thought as possible since it is such a common cause of bugs.
 
To get a sense of the various flux implementations out there, it might be worth looking at: https://github.com/voronianski/flux-comparison

I am kind of curious about https://github.com/yahoo/fluxible and how it is using React.withContext after looking at this.

Further discussion at 3279-gh-calypso-pre-oss

**Comment by rralian** [comment]
Looks like we can close this issue and its milestone considering we have [our approach to data](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md) now, right @hoverduck?

**Comment by hoverduck** [comment]
Sounds good to me.  Pinging @gcorne as well since he was the author of the original issue in the pre-OSS repo

**Comment by rralian** [comment]
@gcorne is welcome to chime in, would be nice to hear from him again (he's at hubspot now). But I don't think we need to wait to close this out. :-)

**Comment by gcorne** [comment]
Redux is cool with me. :smile:
