### ISSUE TITLE
Jetpack: followers api endpoint requires enabled stats module

### ISSUE THREAD

**Issue by annezazuu** [Automattic/wp-calypso#11308]
#### Steps to reproduce
1. Disable Jetpack stats under Jetpack > Settings > Engagement
2. Head to WordPress.com > People

You'll then see this error:

<img width="811" alt="screen shot 2017-02-09 at 3 29 28 pm" src="https://cloud.githubusercontent.com/assets/11266471/22807594/a4671b3e-eedc-11e6-879f-e51d16dccaeb.png">

Speaking to @lezama  about this he said the problem is that we need to reimplement this module so that it doesn’t rely on stats being enabled.

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/jetpack/issues/237

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/email-subscription-function-not-working-2/

**Comment by ebinnion** [comment]
Patch for API side: D4339. We'll need to follow up with a Calypso patch afterwards.
