### ISSUE TITLE
Site settings: settings saved are not cleared and risk being applied to other sites

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#11317]
Step 1: Successfully edit one of my sites title (site A) 
Step 2: Picking another site in the switcher (site B),

**Problem**: the new site title from site A appears in place of the site title of site B. The settings appear modified, and clicking save will actually commit the new site A title to site B.

[Demo video of bug](https://cloudup.com/cLQ8LrvyyVu)

**Comment by lsinger** [comment]
Worth noting that merely selecting another site does not save the new settings for it. It's just the form fields that are populated. Of course if you hit save then, you'll overwrite the other site's settings with the original site's.

Not saying this isn't serious. Just trying to clarify a bit more what is happening.
