### ISSUE TITLE
Framework: MySitesSidebar missing :focus on links

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1131]
Currently the sidebar is missing focus on links. This is really noticeable on mobile browsers when you tap on a link and you wonder if you actually clicked on it.

I think adding a focus state to links in the sidebar would fix this.

Having focus styles is good for usability, accessibility, and a general best practice. Not just for mobile users, but especially for any touch use case. Fully agree on this improvement.

I noticed the `current-section` navigation anchor — to go back to the previous screen, does have a hover style of sorts, which is helpful. A white background color change, at least, though it's pretty subtle.

![image](https://cloud.githubusercontent.com/assets/7233112/11509351/a4ece402-982b-11e5-809c-ee76c6f33714.png)

**Comment by klimeryk** [comment]
Fixed in #2173.
