### ISSUE TITLE
Site Settings: can't set locale options for Jetpack sites

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#11316]
Site locale and timezone settings are not available for Jetpack sites.

![screen shot 2017-02-10 at 10 26 55](https://cloud.githubusercontent.com/assets/844866/22819617/9485c5c2-ef7b-11e6-90c3-4793946d9a5e.png)

**Comment by tyxla** [comment]
That's a rather important one and I'm happy to jump into it soon.

**Comment by lancewillett** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/10441 possibly.

**Comment by lancewillett** [comment]
Hi @tyxla -- checking in on this one, is it still on your radar to fix?

**Comment by tyxla** [comment]
Oops, that one seems to have fallen through the cracks. Our team is not planning to work on any new Settings work for now. Anyway I'm happy to help with reviews, testing and any support I can provide to the team that's going to work on this one.

**Comment by alisterscott** [comment]
I went looking for timezone settings in calypso today and couldn't find it for a pressable site.
