### ISSUE TITLE
Billing History: Mapping and Registration Appear as Separate Charges

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#11339]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/billing/
2. Click View Receipt on a receipt including a domain registration
3. Note the mapping and registration appear as separate items and prices, rather one one combined item.

#### What I expected
Only Domain Registration to appear with the combined price of the registration and mapping. 

#### What happened instead
Registration and mapping appear separately.

#### Browser / OS version
Chrome 56, OS X 10.11.6

#### Screenshot / Video
![screen shot 2017-02-10 at 2 26 11 pm](https://cloud.githubusercontent.com/assets/1900444/22841068/0e3aa6fe-ef9e-11e6-8915-bca989c4f860.png)

#### Context / Source
A recent receipt issue where emailed receipts excluded the Domain Registration (I believe) cost prompted me to send users to the Calypso receipt where the total was appearing correctly and there I noticed the separated items.

**Comment by melanieharari** [comment]
This is already noted in: https://github.com/Automattic/wp-calypso/issues/2524
Closing this in favor of that issue.
