### ISSUE TITLE
Posts: add a condensed card view, with a toggle to switch between big and small cards

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11345]
Proposal via @mtias 

![pasted image at 2017_02_10 20_53](https://cloud.githubusercontent.com/assets/66797/22842033/04ef0890-ef91-11e6-8339-a867fe070d8b.png)

![pasted image at 2017_02_10 20_55](https://cloud.githubusercontent.com/assets/66797/22842036/064d55d4-ef91-11e6-961d-e384f6e1636e.png)

Add a toggle in posts list to switch from big cards to smaller cards.

Allows higher density of content, quickly scan the list. More clearly shows comments and likes as well.

Note: this would apply to pages and CPTs also.

**Comment by mtias** [comment]
A component with a slightly different design already exists at https://wpcalypso.wordpress.com/devdocs/blocks/post-item

So it'd be improving that component and using it. (I think we should move the image back to the left and with the rectangular proportion like the screenshot you have.)

**Comment by lancewillett** [comment]
Closing this in favor of the bulk edit work Link + Tanooki are working on (CC @mattsherman @shaunandrews).

We're going in the direction of a condensed list by default, no toggle. If authors would like a rich visual view of their posts, they can open Reader or the Site Preview that's significantly improved now.
