### ISSUE TITLE
Posts: "View" link should open in-app instead of a new window

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11344]
Props @mtias for this report.

#### Steps to reproduce
1. Starting at URL: `/posts/my/example.wordpress.com`
2. Click "View" under the post.

#### What I expected
To open the web-preview inside Calypso.

#### What happened instead
The preview opens in a new tab or window.

#### Screenshot / Video
<img width="811" alt="screen shot 2017-02-10 at 12 59 22" src="https://cloud.githubusercontent.com/assets/66797/22841961/c9324f4c-ef90-11e6-9eee-f086081c1649.png">

Note: this would apply to pages and CPTs also.

**Comment by jeremeylduvall** [comment]
Closed in #11459.
