### ISSUE TITLE
Posts: show post like avatar images in a popover on the post cards instead of linking to stats page

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11343]
#### Steps

1. Start on a post card (single view) at `/posts/my/example.wordpress.com`
2. Click the star like icon.

<img width="757" alt="screen shot 2017-05-01 at 10 20 36" src="https://cloud.githubusercontent.com/assets/66797/25587245/027076a2-2e58-11e7-86d2-b2772161b53d.png">

#### What I expected to happen

Show the avatars of users who clicked "Like" here inline, without a page change or navigating to a different URL.

#### What happened instead

I was taken to `/stats/post/1234/example.wordpress.com` for the post stats, which does show the gravatars.

Would be a nice improvement to render this inline and not navigate away, unless you click the stats link next to it.

Important note: This would also apply to pages and CPT views.

Props @mtias

**Comment by lancewillett** [comment]
Hmm: I need to add screenshots for #visox (visual oxygen).

**Comment by mattsherman** [comment]
Tanooki will be addressing this as part of the Condensed Post List project.

**Comment by bsessions85** [comment]
This is done as part of Condensed Post project.
