### ISSUE TITLE
Framework: Create 404 page for both use on both the server and the client with partially correct routes

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1135]
We need to have some sort 404 for use on both the client and the server when a route is only partially matched. For example, right now if you go to https://wordpress.com/stats123 you get an empty Calypso page, which isn't a great UX.

If you the non-existent page happens to start with an existing route (like /stats or /posts) then you get the blank Calypso page.  If it's completely wrong (like https://wordpress.com/gibberish), then the "Page not found" page is returned.

**Comment by ockham** [comment]
As for the Calypso side, I think this should be fixed by #4632 (try https://wpcalypso.wordpress.com/stats123). For this to work on wordpress.com, I think we'll have to update some routes in our nginx config (i.e. outside Calypso).

**Comment by gwwar** [comment]
See related p3btAN-IW-p2. We should apply the new 404 page consistently across Calypso.
