### ISSUE TITLE
AT: Uploaded Themes shows a confusing empty message

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#11397]
<img width="976" alt="screen shot 2017-02-14 at 12 57 00 pm" src="https://cloud.githubusercontent.com/assets/1464705/22950476/97905f24-f2ba-11e6-98cb-10de2770358d.png">

This should say "You haven't uploaded any themes" or something to that degree, and definitely not take up this much space.

**Comment by folletto** [comment]
Duplicate of #11045.
