### ISSUE TITLE
AT: Changing primary domain screen takes ages, and loading indicator missing

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#11395]
<img width="749" alt="screen shot 2017-02-14 at 12 45 58 pm" src="https://cloud.githubusercontent.com/assets/1464705/22950346/23d242be-f2ba-11e6-9b87-4826c99c4b09.png">

When I go through the AT flow, and set my primary domain the screen hangs for a long time. This is annoying, but even worse is that there is no loading indicator anywhere after this action is taken. The screen basically hangs, lets add some sort of indication something is happening.

**Comment by retrofox** [comment]
Related with 65-gh-automated-transfer issue.

**Comment by rralian** [comment]
I actually wouldn't consider this an Automated Transfer bug per-se. And we're addressing it with an approach that should make this interaction unnecessary. We should keep it open for its own sake however. /cc @schwuk

**Comment by klimeryk** [comment]
FYI, we have two flows for updating the primary domain. This is the old one, while a new one was introduced in https://github.com/Automattic/wp-calypso/pull/3931. We were supposed to remove the old one after analyzing the adoption of the new approach, but it seems we never got to it. cc @umurkontaci & @breezyskies - do you think we could remove the old button for changing the primary domain?

**Comment by breezyskies** [comment]
Yes, the original intent was for the newer UI to replace this one, not supplement it. The newer version gives the context of the primary domain in relation to the other domains a site may have, which is not as clear in the older interface.

**Comment by umurkontaci** [comment]
FWIW, the older interface is slower because it's making a couple more requests to ensure we don't break the state of Calypso. I think the newer interface skips them, and we should add them.

Changing primary domain requires a lot of HTTP requests in Calypso, particularly related to SitesList, and the only way to ensure the user doesn't land somewhere broken is to make those requests. 

If you don't have hundreds of sites it's not that slow, but it's still very slow.

**Comment by apeatling** [comment]
FWIW I only had one site when testing this.

**Comment by lancewillett** [comment]
Closing as this screen has been updated since the original report (see https://github.com/Automattic/wp-calypso/pull/3931).
