### ISSUE TITLE
Plugins: Plugin screen truncation leaves plugins description sparse

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#11396]
<img width="825" alt="screen shot 2017-02-14 at 12 48 43 pm" src="https://cloud.githubusercontent.com/assets/1464705/22950414/61596e50-f2ba-11e6-8fa8-159ed357761d.png">

If a plugin has spaced out their description then the read more option cuts off very early. Would it make sense to increase the amount of text that can show before read more kicks in?

**Comment by drw158** [comment]
@vindl Would it be reasonable to expand the description just for this view (pre-AT), and keep it collapsed in the Jetpack single plugin view (post-AT)?

**Comment by apeatling** [comment]
We could even get rid of the read more setting in this view.

**Comment by vindl** [comment]
@drw158 Yes, as far as I remember that should be doable. I'll update it when I get a chance.
