### ISSUE TITLE
People: Implement add new user page

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#114]
In the following mockup, there is an "Add User" button:

<img width="747" alt="0737f8de-4126-11e5-8cc9-2131c48c18af" src="https://cloud.githubusercontent.com/assets/11487924/11248944/edaa538a-8df1-11e5-8cb7-7d7b8fb7e43b.png">

On WPCOM, this requires in the invite process, which we're going to focus on in a later milestone (#113). We could go ahead and implement this for self-hosted sites though.

Here's a screenshot of the "Add New User" page in WP admin.

![](https://cloud.githubusercontent.com/assets/1126811/9239936/68b0e918-4126-11e5-86e7-5ddb56b9b85e.png)

I believe that we could mostly reuse the profile page design for this as well:

![2](https://cloud.githubusercontent.com/assets/11487924/11249023/752e1490-8df2-11e5-9b61-7a9a1a88e986.png)

That was the idea with the profile design. We could incorporate the bare minimum form elements needed.

Heads up for whoever implements this: The data handling for adding new users through WP admin is taken care of in the wp-admin/user-new.php file. This means that the emails for sending out confirmation email and invites is buried beneath code that expects $_POST and $_REQUEST. We may need to look at refactoring this code in core.

**Comment by ebinnion** [comment]
I believe we are moving towards using the WordPress.com invite flow for adding new users. Because of that, I'm going to go ahead and close this.

cc @rickybanister just in case I am wrong and we need to re-open.

**Comment by rickybanister** [comment]
Yes, at least our first passes will be to enforce SSO and thus the users will create .com accounts.
