### ISSUE TITLE
SEO settings: hide editor sidebar SEO Description menu for non-indexed sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11406]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/example.wordpress.com/1234 — where the site is not public (private or hidden from search engines).
2. Look in the editor sidebar for SEO Description.

#### What I expected
Not to see this for a private or non-indexed site. 

#### What happened instead
It's confusing why this menu shows up here in this context. I also feel a bit anxious because maybe my site is open by mistake.

#### Screenshot / Video
<img width="287" alt="screen shot 2017-02-15 at 07 51 33" src="https://cloud.githubusercontent.com/assets/66797/22979531/f6964a58-f353-11e6-9d5b-f2f0c0173a05.png">

#### Context / Source

#context #reallife #flowsharing #anxiety #stresscase

Found via #reallife use.

**Comment by jeremeylduvall** [comment]
This should've been closed by #11579 and #12164.
