### ISSUE TITLE
Post Schedule: Clock time input field freezes once you input an erroneous number to it

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#11409]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/post/[site_url].
2. Open the calendar for scheduling.
3. Input an erroneous number such as `60` for minuets.

#### What I expected
I expected to be able to input a number as long as it's acceptable number.

#### What happened instead
Both input fields, hour and minutes freeze and it doesn't take any number

#### Browser / OS version
Mac Chrome

#### Screenshot / Video
I typed into mins field `30`, `40`, `50`, and `60`. After `60` both fields stoped taking _any_ numbers.

![untitled](https://cloud.githubusercontent.com/assets/908665/22985311/f9ad3f8e-f39f-11e6-8cd8-32eba27de0c8.gif)

**Comment by rachelmcr** [comment]
I retested this issue and I'm no longer able to put an invalid number in the time fields. Typing or pasting an invalid number resulted in an acceptable number in the field (e.g. entering `60` resulted in `00`). Closing as this seems resolved.
