### ISSUE TITLE
Offline, small screen the "offline" icon needs design love

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11428]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Use a small screen device, I tested with Nexus 6P and Chrome browser.
3. Go offline or access wordpress.com from a slow or bad connection ( #reallife )
4. Look at the icon at the top of the page, what we call "masterbar" navigation.

#### What I expected
To see a nice layout and blue "Offline" badge.

#### What happened instead
The badge has a white background and looks broken a bit.

#### Screenshot / Video
<img src="https://cloud.githubusercontent.com/assets/66797/23024823/05410e2e-f419-11e6-80cc-963449e58e5c.png" width="480" />

#### Context / Source

Found the bug via #reallife use.

**Comment by folletto** [comment]
For reference, the current fix here is to completely cover the add button.

There's also an alternative design that slips the lightning icon on the right side, not yet implemented, but I'd go there if possible:

![calypso-offline-indicator-i3](https://cloud.githubusercontent.com/assets/4389/23128507/1b406fe2-f777-11e6-8ac2-3b1556a3a958.png)

**Comment by folletto** [comment]
We still don't have full offline support, and the above design might still be useful for future work.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

I tested by putting my iPhone in offline mode, then attempting to refresh the Reader tab:
<img width="375" alt="PNGイメージ" src="https://user-images.githubusercontent.com/6549265/106333165-f43b0300-623c-11eb-83d0-cd69b5a817c0.png">

I am proposing that this issue be closed if no work is scoped in the near future.
