### ISSUE TITLE
Purchases: Use the flash pattern for the cancelation notices in `/purchases`

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1142]
Suggested by @gziolo [here](https://github.com/Automattic/wp-calypso/pull/914/files#r46119000). Switching to global notices will allow us to change the to the behavior described by @mikeshelton1503 [here](https://github.com/Automattic/wp-calypso/pull/914#issuecomment-160971898):

> As I understand it, when you click through from the email a notice is displayed at the top but then disappears when you navigate to another page. Is that correct?

> For a successful notice, there is no problem with it disappearing on a new page, however for the error notice, it should persist until dismissed or fixed.

**Comment by scruffian** [comment]
I think we did this already in https://github.com/Automattic/wp-calypso/pull/4540

**Comment by fabianapsimoes** [comment]
I've discussed this with @gziolo and it's indeed fixed. We do need to do some cleanup on that code, since we no longer use emails / links for cancellations. He'll open a new issue for that.

**Comment by gziolo** [comment]
Only `listNotice` path and controller needsto be removed.

All other work was already done :)
