### ISSUE TITLE
Editor: Use app-friendly `u` tag for underlining

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#11423]
In the Calypso editor, when you underline text with the toolbar button it gets an inline style like this:

`<span style="text-decoration: underline;">underlined text</span>`

However, the new Aztec editors (coming to the mobile apps) don't have CSS support built-in, and it isn't known if they will have that support. Instead, Aztec uses the `u` tags for underlined text:

`<u>underlined text</u>`

As a result, underlined text created in the Calypso editor doesn't get an underlined style in the Aztec editor. Related issues:

- https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/278
- https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/259

I'm aware that HTML5 uses the `u` tag for other purposes ([reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u)) but would we consider using it for underlined text in Calypso for the purpose of a seamless experience across the web and app editors?

#### Context / Source
#manual-testing

**Comment by iseulde** [comment]
Note that underline has been removed from WordPress Core: https://core.trac.wordpress.org/changeset/38932

**Comment by mtias** [comment]
Let's remove here as well for now.

**Comment by rachelmcr** [comment]
Closing since underlining is removed in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
