### ISSUE TITLE
Domains: tweaks to featuregate for domain-only sites

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#11430]
The featuregate added in #11098 causes some unexpected behaviors. 

1. When using the site-switcher to switch from a regular site to a domain-only site, Calypso tries to keep you on the same screen. Unless you were already on the Domains screen, the featuregate is triggered. 
2. The featuregate screen hides the My Sites menu by default. If you click on My Sites, the sidebar is revealed, but you are also immediately switched to the Manage Domain screen. If you click on the "Back" link in the Manage Domain screen, you are taken to the regular domain-only site screen, not the featuregate screen.
3. If you're on the featuregate screen and you use the site switcher to switch to a regular site, Calypso will keep you on the same page, which is the Domains screen. If you switch between regular and domain-only sites, you will always end up on the Domains screen.

There are a small few fixes and improvements we can make here:

- Don't show the featuregate when using the site switcher to switch to a domain-only site while on a non-Domains screen. Showing the regular domain-only screen here is fine (the one "example.com is not set up yet", not the one that says "Add a site to use this").
- Show the My Sites menu on the featuregate screen, like other similar screens in Calypso. 
- Don't change to the Manage Domain screen when interacting with the My Sites menu. Though anyway, this sounds more like a bug than something intentional.

To make the overall Calypso experience more seamless when switching between regular and domain-only sites, we should avoid diverting users to the Domains screen when they switch to a domain-only site. It may be good to "remember" the last screen users were on when they were last using a regular site, and return them to that same screen when they switch from a domain-only site to a regular site.

**Comment by breezyskies** [comment]
> Don't show the featuregate when using the site switcher to switch to a domain-only site while on a non-Domains screen. Showing the regular domain-only screen here is fine (the one "example.com is not set up yet", not the one that says "Add a site to use this").

Agree, landing on the feature gate (particularly without the sidebar) is pretty confusing here. 

Having said that, probably not a blocker given that you would have to have a domain-only site and other sites to end up in this state, which will be pretty edge case for at least the near future.

**Comment by stephanethomas** [comment]
I think this was raised before but what about keeping the list of options in the sidebar and dimming all except the one that leads to the `Domain Management` page ?

<img width="633" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/594356/23225149/2e77ea66-f931-11e6-8dda-93c007e3845c.png">

<img width="633" alt="screenshot" src="https://cloud.githubusercontent.com/assets/594356/23225153/322a0e96-f931-11e6-8a1b-e72aeaaf2cac.png">

This would solve nicely this problem that happens when switching from a regular to a domain-only site.

**Comment by ranh** [comment]
After chatting about this some more, I think this is good to close.

> Don't show the featuregate when using the site switcher to switch to a domain-only site while on a non-Domains screen. Showing the regular domain-only screen here is fine (the one "example.com is not set up yet", not the one that says "Add a site to use this").

This would be a complicated change to implement, so probably not worth considering. This was intended as a quick fix to get domain-only sites to behave well within Calypso navigation, without making any big changes. It defeats the purpose if it's not quick and it requires big changes. 

I don't think there's need to leave this around to keep track of this particular issue, and we will be keeping an eye on the overall question of domain-only sites within Calypso anyway. 

> Show the My Sites menu on the featuregate screen, like other similar screens in Calypso.

This was fixed in #11539.

> Don't change to the Manage Domain screen when interacting with the My Sites menu. Though anyway, this sounds more like a bug than something intentional.

There is reported separately in #11443.
