### ISSUE TITLE
Domains: Illustration on "site or domain" selection doesn't make sense

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#11439]
When testing the domain-only flow we have illustrations on Step 2 for each choice. The illustration for "Just buy the domain" doesn't make sense here. I think these are a hold-over from an early prototype/mockup that never got updated.

<img width="790" alt="screen shot 2017-02-16 at 14 08 47" src="https://cloud.githubusercontent.com/assets/448298/23040308/d9da4c3c-f45e-11e6-98cf-111dcda8491b.png">

We should update it to something that makes more sense, perhaps showing a placeholder for the parking page design.

![artboard](https://cloud.githubusercontent.com/assets/448298/23040421/3ef9ffd6-f45f-11e6-9596-2e65ff7a2db3.png)

#### Steps to reproduce
1. Checkout Calypso locally and open http://calypso.localhost:3000/start/domain-first.
2. Search and select a domain
3. On the next step it asks if you want to start a site or just buy the domain

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed: in the site or domain step during signup, the "Just buy a domain" graphic doesn't represent what a domain actually is.

![screen shot 2017-02-23 at thu feb 23 1 10 13 pm](https://cloud.githubusercontent.com/assets/1119271/23280870/21dece9e-f9d8-11e6-9187-746f7e8da2ee.png)
<sup>Seen at http://calypso.localhost:3000/start/domain-first/site-or-domain running Calypso `3c1d783`</sup>

My own feedback: for a "Just buy a domain" option, I would want to see plain text and not an image of any kind (i.e. example.com).
