### ISSUE TITLE
AT: Domains: G Suite

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#11446]
When managing an AT site, at a minimum we should allow modifying existing G Suite configurations.

Currently, you cannot buy G Suite with a Jetpack site, but maybe we can change that as well.

@beaulebens @dzver  Can we add G Suite to AT sites? G Suite works over DNS so I don't suppose we'd have any problems.

**Comment by dzver** [comment]
There should be no problem to add G Suite in case we control the DNS.

**Comment by jhnstn** [comment]
Fixed in D4498-code
