### ISSUE TITLE
AT: Domains: DNS: Show Handled by WordPress.com message for AT IPs

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#11449]
We should recognize the IP addresses for Pressable and treat them the same as WPCOM IP addresses in the UI. 

IPs: p1487196695007848-slack-faster-transfers

It should look like this:

![image](https://cloud.githubusercontent.com/assets/991022/23047309/dce5de64-f463-11e6-8562-331f197abc6a.png)

**Comment by jhnstn** [comment]
fixed in D4470-code

**Comment by jhnstn** [comment]
D4470-code broke AT  :(

**Comment by jhnstn** [comment]
New approach in D4523-code.
