### ISSUE TITLE
Domains: My Sites links to advanced domain settings view

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#11443]
#### Steps to reproduce
1. Starting at URL: http://wpcalypso.wordpress.com/start/domain-first (logged out / incognito)
2. Purchase a domain and choose not to set up a site yet.
3. After checkout, click on My Sites. You are taking to the domain's advanced settings view rather than the simple domain-only (default) view.

Links to: | Should link to:
------------ | -------------
<img width="1438" alt="screen shot 2017-02-16 at 3 59 27 pm" src="https://cloud.githubusercontent.com/assets/3011211/23046870/f4d814b8-f460-11e6-875e-1682252317e9.png"> | <img width="1439" alt="screen shot 2017-02-16 at 3 59 38 pm" src="https://cloud.githubusercontent.com/assets/3011211/23046871/f4d86620-f460-11e6-9334-de13027ba0ad.png">

cc: @drewblaisdell

**Comment by ranh** [comment]
See also #11430.

**Comment by stephanethomas** [comment]
This is going to be fixed by https://github.com/Automattic/wp-calypso/issues/11539.
