### ISSUE TITLE
AT: Domains: Email Forwarding

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#11445]
When managing a domain for an AT site, the users should be able to set up email forwarding.

Currently, when you are setting up email forwarding and click on the verification link, redirects to a link like `domain.com/wp-admin/something.php` that doesn't exist in AT sites so forwarding fails.

To fix it, we probably need to create an endpoint to set up email forwarding in Calypso.

@rralian do we need this for v1?

**Comment by rralian** [comment]
I'd probably do this last, but yes I think we need it.

**Comment by klimeryk** [comment]
Related issue: https://github.com/Automattic/wp-calypso/issues/7692.

**Comment by klimeryk** [comment]
Should be resolved by `D6056-code` 🎉
