### ISSUE TITLE
Domains: Update notices and warnings for domain-only domains

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#11441]
We show a couple of warning notices for newly registered domains (see attachments). We still need these but we should improve on them.

![image](https://cloud.githubusercontent.com/assets/448298/23043712/2fb1b828-f46b-11e6-961f-2ab0bd614545.png)
![image](https://cloud.githubusercontent.com/assets/448298/23043716/35f3d478-f46b-11e6-9fc8-25e14fd61183.png)

We should treat these notices as part of the flow. Otherwise it's like you always end the flow in an error state.

Summary from chats on Slack about the problems with current implementation for domain-only users:

* The information in the notices could be incorporated in thank you screen and email, so we don't have to rely on these notices for new users.
* The sidebar notice about verifying the contact information doesn’t have to be shown from day 0, we can start to show it later. Users will still get notified about this by email, more than once.
* The "primary domain" part of the yellow notice doesn't apply to domain-only sites.
* The “72 hours” part of the yellow notice can perhaps be reimagined as a less intrusive “domain changes pending” indicator. We don't know if a user can see their domain or not when we show this notice, and this notice makes a normal delay seem like an error.

#### Proposed solutions:

* Let's only show the sidebar notice about verifying email address after a day.
* Let's completely remove the yellow notice for domain-only sites.
* Let's add the information about new domain delay to the default screen, and only show it for the first six hours:
![image](https://cloud.githubusercontent.com/assets/448298/23043740/5a294652-f46b-11e6-8cd0-69e839ada5ee.png)

**Comment by umurkontaci** [comment]
> Let's only show the sidebar notice about verifying email address after a day.

We should totally improve this experience (previous works: #9546), though I'm a bit hesitant on removing the notice completely for the first six hours as this is the prime time for user's attention to get the email verified.

I'm worried that people will play with their sites (without actually verifying) for a while, then leave and don't come back for a week. In this case, the domain will be suspended – we want to avoid that.

Can we find a solution that would allow us to make the onboarding smoother (with a better copy etc), without hiding the fact that they need to take an action to keep the domain?

**Comment by ranh** [comment]
> I'm a bit hesitant on removing the notice completely for the first six hours as this is the prime time for user's attention to get the email verified

@umurkontaci Do we have any data about how users interact with this notice? Since the action is taken on the email and not in Calypso, it seems that this notice may not be necessary, at least at first. 

But of course we want to make sure users are aware of this and don't miss out on verifying their details.

**Comment by breezyskies** [comment]
> Do we have any data about how users interact with this notice? Since the action is taken on the email and not in Calypso, it seems that this notice may not be necessary, at least at first.

+1 for looking at this.

The concern is mostly that someone has just bought a domain and we immediately show them warnings, which is a bit of a bummer after you just paid for something (and you probably haven't even seen the email yet). Anything we can do to make this a more positive experience is a win.

**Comment by umurkontaci** [comment]
I don't have any data for this, we'd have to A/B test the notice and compare the verification rates for the first 6 hours. I don't think it's going to be very easy to test it.

I agree with the sentiment about the problems in showing notices right after purchasing something, but I don't want to risk people getting their domains suspended because of it.

Can we change the copy to be more friendly ("One last to step to get your domain in order" etc.), or do something else to catch their attention? If we can find an alternative, we can hide this for the first X hours without any risks.

**Comment by breezyskies** [comment]
> I don't have any data for this, we'd have to A/B test the notice and compare the verification rates for the first 6 hours. I don't think it's going to be very easy to test it.

Agree, I wouldn't necessarily test this -- but aside from this specific discussion, it would be good to be tracking how often that notice is shown vs. clicked (and for example, how long after registration, on average, it is clicked). If we start regularly tracking notices like these, we can make more informed decisions when issues like this come up.

> Can we change the copy to be more friendly ("One last to step to get your domain in order" etc.), or do something else to catch their attention?

While in general I agree it could be more friendly, the problem we've run into with that notice is that we don't have a lot of room for copy. 

What if we hide it for a shorter period of time -- maybe the first 5-10 minutes? Ultimately this isn't a blocker for v1, but could be a nice UX improvement for all domains.

**Comment by umurkontaci** [comment]
> Agree, I wouldn't necessarily test this -- but aside from this specific discussion, it would be good to be tracking how often that notice is shown vs. clicked (and for example, how long after registration, on average, it is clicked). If we start regularly tracking notices like these, we can make more informed decisions when issues like this come up.

:+1:


> While in general I agree it could be more friendly, the problem we've run into with that notice is that we don't have a lot of room for copy.

Is there a place where we can show the message somewhere outside sidebar? 

> What if we hide it for a shorter period of time -- maybe the first 5-10 minutes? Ultimately this isn't a blocker for v1, but could be a nice UX improvement for all domains.

I'm not sure how I feel about this, @folletto ? I'm not disagreeing though, could be quick win.

**Comment by ranh** [comment]
> I don't have any data for this, we'd have to A/B test the notice and compare the verification rates for the first 6 hours. I don't think it's going to be very easy to test it.

@umurkontaci I don't think we need to A/B test this. If there's an event for hitting the FIX link, we can see how many people who verified their contacts have used it, vs. just verifying through the email directly without acting on the notice.

> Is there a place where we can show the message somewhere outside sidebar?

@breezyskies For domain-only sites, we can include this notice in the default screen, along with the note about the potential delay:

> Please verify your contact information in the email we sent you to mail@example.com. [Resend email](#) 

This way it looks like just another part of the process, rather than like something that went wrong. 

This doesn't apply to regular sites though, since there is no equivalent screen to show this notice on.

**Comment by umurkontaci** [comment]
> If there's an event for hitting the FIX link, we can see how many people who verified their contacts have used it, vs. just verifying through the email directly without acting on the notice.

Apparently we don't have an event for that; we should be able to add one easily if we want to go that route.

**Comment by lucasartoni** [comment]
what is a good indicator that the notice is working right now? Let’s kill it, and measure if that indicator shows it was a bad decision and in case we revert.

**Comment by breezyskies** [comment]
> what is a good indicator that the notice is working right now? Let’s kill it, and measure if that indicator shows it was a bad decision and in case we revert.

cc: @umurkontaci 

I would move to update the notices as @danhauk mentioned above and keep an eye on the higher level verification metrics.

**Comment by umurkontaci** [comment]
@lucasartoni how can we to track the success or the lack of it by removing it?

**Comment by umurkontaci** [comment]
@danhauk @breezyskies  If you can change the checkout page to include the messages about email verification and unreliability, I'll remove the notice for the first 24 hours.

**Comment by breezyskies** [comment]
@umurkontaci Do we have anything that tells us what % of domains are verified (even better if it's within x days)? How have we known in the past that this was a problem (which I assume led to the notices being added)? cc: @lucasartoni

**Comment by umurkontaci** [comment]
If a domain is not verified in 7 days, it is suspended. I don't think we have a detailed stat for that though /cc: @aidvu @dzver 

When email verification policy began to be enforced people who didn't verify their domains were losing them. So we put the notice to reduce the number. IIRC this reduced lost domains (guessing from the support volume), but I'm not sure to what extent.

**Comment by aidvu** [comment]
No tracking afaik. We can get number of suspended domains tho.

**Comment by umurkontaci** [comment]
> No tracking afaik. We can get number of suspended domains tho.

Then we probably can calculate suspended/registered for domains registered throughout a week.

**Comment by aidvu** [comment]
Can use the logs for this @umurkontaci.

**Comment by ranh** [comment]
> If you can change the checkout page to include the messages about email verification and unreliability, I'll remove the notice for the first 24 hours.

![ranimac3 screenshot 2017-04-19 at 17 53 10](https://cloud.githubusercontent.com/assets/426518/25187675/6bd6ed86-252c-11e7-9f02-9660045f8080.png)

@umurkontaci Strictly speaking, the checkout page already includes this information, in the ToS section before the payment button. It's probably true that few users would read it (but that can be said about any notice). 

We can add more information specifically about domains:

> Most new domains start working immediately, but may be unreliable for the first few hours. Check your email at mail@example.com to verify your details within 14 days, or your domain will be suspended. 

In general though, I don't like the idea of warning users in advance about issues they may not otherwise even notice, or issues that we should be better protecting them from in the first place. 

It seems completely backwards that we added this notice to help us reverse some perceived negative trend, but there is no indication that a negative trend ever existed, or that it has since been reversed. Since there doesn't seem to be any reason to keep the notice, I think it should be safe it to at least hide it in the first 24 hours.

**Comment by ranh** [comment]
> When email verification policy began to be enforced people who didn't verify their domains were losing them. So we put the notice to reduce the number. IIRC this reduced lost domains (guessing from the support volume), but I'm not sure to what extent.

PS @umurkontaci do you have any more details about this? AFAIK domains stop working when they are suspended, but owners still own them and can verify them after they are suspended. What would have to happen for a domain owner to lose a domain from not verifying it?

**Comment by umurkontaci** [comment]
> It seems completely backwards that we added this notice to help us reverse some perceived negative trend, but there is no indication that a negative trend ever existed, or that it has since been reversed.

The indication was the amount of support requests about suspended domains. 


> @umurkontaci Strictly speaking, the checkout page already includes this information, in the ToS section before the payment button. It's probably true that few users would read it (but that can be said about any notice).

I don't see it? It mentions recurring charges.
Removing it and putting a text to ToS block has the same effect.

> do you have any more details about this? AFAIK domains stop working when they are suspended, but owners still own them and can verify them after they are suspended.

That's true, the domains are not lost.

**Comment by breezyskies** [comment]
> In general though, I don't like the idea of warning users in advance about issues they may not otherwise even notice, or issues that we should be better protecting them from in the first place.

Agree with @ranh here. This breaks the "just in time" rule -- not only do users have to read the notice we show (which also could affect checkout itself), but they have to then remember that information for a later point where it may or may not become relevant. 

According to @aidvu [here](https://github.com/Automattic/wp-calypso/issues/11441#issuecomment-290406810), it sounds like we can kill the notice and keep an eye on the suspended domains. While this isn't a blocker or super high-priority issue, I would recommend prioritizing it alongside other enhancements being worked on. Moving this to the dev milestone.
