### ISSUE TITLE
Domains: No confirmation after domain-only purchase

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#11452]
Purchasing only a domain lands you here, with no confirmation the purchase went through. 

<img width="1439" alt="screen shot 2017-02-16 at 4 37 11 pm" src="https://cloud.githubusercontent.com/assets/3011211/23047764/b907f448-f466-11e6-9e5f-b36d76f7ebde.png">

The “xyz.live is not set up yet” which could be confusing in this context since you didn't get any feedback about the purchase. 

Some options:
1) Add the green "thank you" notice after checkout, with a CTA to proceed to manage the domain (vs. "view site"). 
2) Add some confirmation text or notice on the current page the user lands on.

cc: @ranh @danhauk @josemarques @scruffian

**Comment by ranh** [comment]
There is already an issue for adding some more copy on this screen, to explain the new domain delay: https://github.com/Automattic/wp-calypso/issues/11441

We can also improve the "not set up" copy in the title, which is not very useful. For example:

> example.com: Temporary page

**Comment by danhauk** [comment]
I like the idea of a dedicated confirmation screen to make it more obvious and reduce any confusion with the "not set up" information and sad-looking illustration being so prominent.

![image](https://cloud.githubusercontent.com/assets/448298/23319690/a87a5e46-faa5-11e6-91f5-acc1e965dca6.png)

Alternatively, to get something pushed out more quickly, if we do the confirmation notice on the existing screen:

![domain-purchase-confirm](https://cloud.githubusercontent.com/assets/448298/23319621/5705e062-faa5-11e6-8215-3e710fd0dc65.png)

cc @ranh for copy review on both of those

**Comment by ranh** [comment]
The copy looks good, but the button should probably say something like "go to your domain" or something. "manage domain" is already used in a different context.

**Comment by fabianapsimoes** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/11702
