### ISSUE TITLE
Redux state: Unexpected keys error message

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#11455]
The JavaScript console at various times shows an error message such as ```Unexpected keys "items", "isRequestingRecommendations", found in previous state received by the reducer.```

![developer_tools_-_http___calypso_localhost_3000_hello-dolly](https://cloud.githubusercontent.com/assets/945228/23058263/cbba35d0-f4b9-11e6-9740-77a7deb8c043.png)

#### Steps to reproduce
A. Run an old version of Calypso with reducers we don't use anymore. Update to a new one, but allow browser to restore from persistence cache.
B. Sometimes just happens, watch your JavaScript console. Especially on initial page load or refresh.

This error message is coming from the redux `combineReducers()` functionality, and the cause of it is a side effect of persisting the redux store data.

While the error message probably isn't actually that applicable to Calypso, and we could easily implement our own `combineReducers()` function to remove it, this does raise some questions:

If we have some reducer key that doesn't line up with a currently installed reducer, where did it come from? Here are the possibilities I see:

1. An old reducer that we're not using anymore. (data should be removed from state?)
2. A reducer's name has changed?
3. A reducer hasn't been loaded yet? (Not so valid for top-level reducers, but sub-level ones?)
4. A reducer that belongs to an extension that dynamically comes and goes. (This doesn't happen right now, but it will after we merge #11347 or something like it.

**Comment by samouri** [comment]
I've noticed this happening a lot more recently!
