### ISSUE TITLE
SEO: Pinterest Site Verification link update required

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#11478]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Go to Settings > SEO
3. Click the link for "Pinterest Site Verification"
4. Observe a 404.

![screen shot 2017-02-19 at 6 54 31 pm](https://cloud.githubusercontent.com/assets/108942/23109298/20218372-f6d5-11e6-85c9-6d67971c1d6f.png)

It looks like Pinterest has changed something around, and the best URL to point to now is probably `https://www.pinterest.com/settings`.

**Comment by dereksmart** [comment]
@beaulebens I think Pinterest might have fixed it.  `https://pinterest.com/website/verify/` is linking fine for me now

**Comment by eliorivero** [comment]
I can confirm that the Pinterest link was throwing a 404 before (earlier today) but it's working fine now.

**Comment by beaulebens** [comment]
Huh, weird. It's still throwing an error for me. Maybe because I already have a verified URL?

I see this:

![screen shot 2017-02-20 at 9 12 13 pm](https://cloud.githubusercontent.com/assets/108942/23150524/44a22a44-f7b1-11e6-906d-aba50ea3593f.png)

Note that I'm also redirected to `https://www.pinterest.com/website/confirm/`

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed that the Settings > SEO >  Pinterest Site Verification link leads to a "Something went wrong!" error page if you click on that link after you have verified a Pinterest site. Video: [5m9s](https://cloudup.com/cTfc-3g2Vy7).

It's a bit of an odd bug. Note sure it's worth changing as it seems to kinda sorta be an issue on the Pinterest side but also something very unlikely for a WordPress.com user to encounter in a normal flow where they have already verified a Pinterest site in their SEO settings.

**Comment by gravityrail** [comment]
Pinterest is now working for me.
