### ISSUE TITLE
Editor: preview does not display post format changes when editing a published post

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#11477]
Post Formats do not show in Calypso in "Preview" Option. I tested with Twenty Thirteen, Twenty Ten and Libretto themes.

After, I replicated the issue in WP-Admin (replication process described below). The post formats were displayed in "Preview Changes" mode.

These instructions are for the theme Twenty Thirteen:

In the Twenty Thirteen Theme, the blog post formats are expected to have different colours as in the theme demo: https://twentythirteendemo.wordpress.com/

So, the audio post format will have one color and the gallery post format will have another color.

However, when I change the post format, and click "Preview", the colours are not shown. When I click "Update", the colors are saved and displayed. So, in the "Preview" mode users are not able to see the post formats (in this theme, also the colours for these post formats).

How to replicate the problem:

1. Create at least 2 blog posts and set them to Standard Post Format and save everything.
2. Go to Blog Posts, choose one of the posts, click "Edit".
3. In the Post Formats, change, for example, for Gallery.
4. Click Preview Button - ​https://cloudup.com/czpX2s5L-W3
5. Here, the colour remains white in the Preview mode. The post formats are not shown.
6. Exit "Preview" Mode
7. Click "Update"
8. Click "View Post" in the green bar that appears.
9. The colour of the post format changed to yellow so the post format was saved and activated - ​https://cloudup.com/cXZJXAbAsKK 

The post format did not appear in the "Preview" mode when the Post Format was changed but not saved. After saving, the post format was  applied to the post.

Replication in WP-Admin:
1. Chose Twenty Thirteen theme. Set all posts to standard format.
2. Switched to WP Admin.
3. Chose one of the posts. Changed the post format in WP Admin from Standard to Gallery.
4. Clicked "Preview Changes" in WP Admin. As the result, the colours changed in the Preview for Post Formats - ​https://cloudup.com/clUvskpNvHN
5. Followed the same procedure and tested with themes Twenty Ten and Libretto. The Post Formats "Preview" button did not work in Calypso. The Post Formats "Preview" button worked through WP.

**Comment by designsimply** [comment]
@katinthehatsite, this is excellent! Thank you so much for the detailed report.

In my testing, I found that the post format preview was only wrong when updating an already published post. Video: [6m3s](https://cloudup.com/cBVlaK73z8l).

Aside: #5607 looks similar-ish.
