### ISSUE TITLE
Purchases: Some tracks events are not recorded because of nested properties

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#11474]
It appears that some tracks events are not firing because of nested data properties. I'm unsure if these events were ever tracked properly.

## To Reproduce:
- Navigate to http://calypso.localhost:3000/start/design-type
- Pick a theme
- Pick a domain (Optional pay for a .blog domain)
- Make sure dev console is open
- Complete checkout with a paid plan
- We then see the following errors:

![screen shot 2017-02-17 at 9 51 09 am](https://cloud.githubusercontent.com/assets/1270189/23087666/d2e26a78-f52a-11e6-9bd3-49a373e0486b.png)

**Comment by aidvu** [comment]
Fixed.
