### ISSUE TITLE
AT: update eligibility screen design

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#11486]
As discussed in #11394, we need to update the eligibility error page design.

## Current:

<img width="811" alt="screen shot 2017-02-14 at 12 45 17 pm" src="https://cloud.githubusercontent.com/assets/1464705/22949959/d14a042e-f2b8-11e6-8cae-a6602012b2a0.png">

## After:

![at-eligibility-i4b copy 3](https://cloud.githubusercontent.com/assets/618551/23141943/df606cb8-f77e-11e6-85da-b1452216b9f7.png)

https://github.com/Automattic/wp-calypso/issues/11394#issuecomment-280146123

cc @vindl

**Comment by drw158** [comment]
More explanation:

I think this could be done it 2 separate PRs.
1. Update styling, no functional changes
2. Update Business gating behavior, explained below

## New business gating behavior

Currently if you do not have business or a custom domain, then this shows up as an error:

![screen shot 2017-02-20 at 3 25 07 pm](https://cloud.githubusercontent.com/assets/618551/23142278/c80c5c3c-f780-11e6-848b-f952cca3da87.png)

Unfortunately this is problematic because the user could buy a domain first, without knowing that you get one free with business. Also, the red errors make this _positive_ thing into a scary thing.

We should treat the business error and domain error separately. In this case, the user has no business plan and no domain:

![at-eligibility-i4b copy](https://cloud.githubusercontent.com/assets/618551/23142356/2118818e-f781-11e6-841a-fb349a0e897a.png)

If they get business without setting their free domain, we should show them this once they try AT again:

![at-eligibility-i4b copy 2](https://cloud.githubusercontent.com/assets/618551/23142380/4754d154-f781-11e6-97d2-08210ff2d58a.png)

**Comment by folletto** [comment]
An implementation note: the text in the Banner:

> Please update to install this plugin

Might be necessary to be either an external parameter or changed to be generic as we use it in both Plugins and Themes. :)

**Comment by drw158** [comment]
Recently learned that if a user buys a domain, then upgrades to business, they get a discount on the business plan. So, they wouldn't waste money if they bought the domain first, then the plan.

Might still be worth implementing the flow in the mockups though.

**Comment by Copons** [comment]
Closed after #11575 merge.
