### ISSUE TITLE
People: Accepting invite logged redirects to /posts incorrectly

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#1148]
After a user accepts an invite, the user should end up on a site specific route. Probably, `/posts/$site. From memory, I believe this is what we're trying to do.

But, when I try to accept a logged in invite, I get redirected to `/posts`. My guess is that we are attempting to send the user to `/posts/$site` and then the user is getting redirected to `/posts` because Calypso isn't aware that the user has access to `$site`.

So, perhaps we can clear the sites list and re-fetch or come up with another workaround?

**Comment by lezama** [comment]
On the logged out flow the user gets redirected to `/posts/$site` without any issues, going to fix the logged in one.

**Comment by lezama** [comment]
Fixed in #1753
