### ISSUE TITLE
Plugins: getting plugins error and showing install again after success

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#11488]
I went through the install process correctly, got the success message (I definitely saw the green success message). But I left the page open, and eventually it triggered an error message, and then the page updated to show me the install button again.

![plugins error and install button](https://cloudup.com/cA1pGoeGXvP+)

Then if I refresh the page it appears correctly.

![appears correct now](https://cloudup.com/cAeBv5y4BiU+)

/cc @apeatling @roundhill @drw158

**Comment by lamosty** [comment]
I believe this is caused due to the fact that wp.com can't communicate with the Jetpack site while it is getting the cert (or at least very related): https://github.com/Automattic/automated-transfer/issues/78. I'll remove the setting up of A record for the domain of the transferred site this week and we'll see if it helps.

**Comment by apeatling** [comment]
@roundhill Any thoughts on who could look at this one? Is it related to your guys work on AT so far?

**Comment by lamosty** [comment]
@apeatling please have a look at the referenced issue. I'm just working on that and we'll see (early next week) whether it helped with this issue or not.

**Comment by roundhill** [comment]
> Is it related to your guys work on AT so far?

This looks like it is well after the fact after `initiate`, but we can certainly have a look if @lamosty's patch doesn't fix this.

**Comment by lamosty** [comment]
> This looks like it is well after the initiate flow, but we can certainly have a look if @lamosty's patch doesn't fix this.

I don't have a fully working patch yet. But should be up early next week.

**Comment by lamosty** [comment]
> This looks like it is well after the initiate flow, but we can certainly have a look if @lamosty's patch doesn't fix this.

Short news: my patch unfortunately doesn't fix it and I'm still getting occasional `Error fetching plugins on <site>` errors after installing a plugin in Calypso (=> doing an AT).

**Comment by roundhill** [comment]
> my patch unfortunately doesn't fix it and I'm still getting occasional Error fetching plugins on <site>

Yeah, I'm seeing the same. Sometimes it works fine, sometimes not and I see the error and it takes a good while for it to start working with any API request. Anecdotally, it seems to happen more frequently when a site has a lot of content.

**Comment by rralian** [comment]
@artpi Do you think you could look into what's happening here? Dan says he's seeing a 400 response in the network tab when this is happening.

**Comment by roundhill** [comment]
> Dan says he's seeing a 400 response in the network tab when this is happening.

Here's the error:
```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"jetpack_error","message":"The Jetpack site is inaccessible or returned an error: server error. requested method jetpack.jsonAPI does not exist. [-32601]"}}
```

I think I just came across the same issue with a theme upload, so I don't think this is isolated to just the plugin flow.

**Comment by rralian** [comment]
@artpi Both @roundhill and I have been able to recreate these errors. I believe the 400 errors indicate that the Jetpack connection has not fully been established somehow. In both cases, the transfer was interrupted before [wpadmin-auto-login](https://github.com/Automattic/wp-calypso/tree/master/client/components/wpadmin-auto-login) was able to take effect. In one of Dan's cases it seemed that a sites-list operation interrupted the transfer process. In the second one it did not (not sure what happened there). But in my transfer it was definitely interrupted because jetpack-sync was stalled. It was then kicked off manually, but I was no longer in the tab that had started it. In each of these cases visiting `wp-admin` for the affected site seemed to resolve the 400 errors we were getting in Calypso.

**Comment by alisterscott** [comment]
I saw this error on a fresh AT site transfer test. The plugin did seem to install, but the site didn't get an AT complete sticker, so it's not labelled as an AT site in RC.

**Comment by lamosty** [comment]
This is already fixed long time ago. :)
