### ISSUE TITLE
Domains: copy review for post-purchase site-add flow

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#11480]
Some copy updates to the new site flow for domain-only sites.

### Progress indicator

The add site flow includes two stages, choosing a theme and choosing a plan. However, users may also consider the checkout screen as part of the flow. 

Should we display the first stages as `Step n of 3`? 

Since this flow is pretty short, should we just hide the progress indicator? 

### Theme selection

On the theme selection, let's change the title to add more context. 

Currently:

> Let's get started

Change: 

> Choose a theme for your new site.

![ranimac3 screenshot 2017-02-20 at 10 18 19](https://cloud.githubusercontent.com/assets/426518/23116937/ebe24052-f755-11e6-923b-3a5f8e8d6b8e.png)

### Plan selection

We offer a discount on the price of the plan, but don't currently indicate this anywhere on the plan selection screen.

We already have this design in use in Calypso, when adding a plan to a regular site with a domain:

<img width="1063" alt="screen shot 2017-02-20 at 07 30 45 am" src="https://cloud.githubusercontent.com/assets/426518/23117038/687bfd42-f756-11e6-9fc1-d2bd572427cf.png">

We can reuse this here, and add the following copy for context:

> You're getting a discount because you already paid for the domain. 

![artboard](https://cloud.githubusercontent.com/assets/426518/23136424/59d6e9b0-f7a5-11e6-9971-a49ac960e10e.png)

### Checkout

We currently show this notice below the cart details to indicate the discount:

> You're saving $20! Your recent domain purchase is deducted from the price ($35.88), since the plan includes a free domain.

This is not actually right, since the discount is not related to the price of the domain. The actual details of how the discount is applied are a bit too complicated to go over in this notice. For consistency, probably best to just repeat the same message from the plan selection screen.

Also worth covering the renewal price here, to save any unpleasant surprises down the road.

> You're getting a $888 discount off the regular price of the plan ($888), because you already paid for the domain. 
> 
> The plan and the domain can be renewed together for $888 / year. 

<img width="267" alt="screen shot 2017-02-20 at 19 59 34 pm" src="https://cloud.githubusercontent.com/assets/426518/23136811/22b811dc-f7a7-11e6-848e-fdb9bfb09f2a.png">

**Comment by gziolo** [comment]
All issues addressed :)
