### ISSUE TITLE
Media: Remove pencil edit icon

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#11498]
[After the new design of the section and the modal](https://github.com/Automattic/wp-calypso/issues/10805#issuecomment-276094743) is implemented, we should remove the pencil edit button entirely. Some users will probably miss the convenience of the button (contextual and single click to edit), but the issue like #9136, and the one with touch devices outweigh the convenience, thus we're going to change the edit flow with the sticky action bar introduced in the new design.

Discussion & more context: #9136

![image](https://cloud.githubusercontent.com/assets/908665/23161445/0a0ade5a-f822-11e6-9185-baa4d678252b.png)

**Comment by gwwar** [comment]
Please remove any dead code related to this
