### ISSUE TITLE
Free Trials: Post sign-up email stream

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1149]
After sign-up we will send free trial users a series of emails. Here is the schedule for those emails:

- Day 0
- Day 7
- Day 11
- Day 13
- Day 14 (after expiration)
- Day 16

### Designs & subject lines

[Timeline view](https://cloudup.com/cqRNB9vro_s)

#### Day 0
Subject line: Your free trial has been activated

![day-0-v4](https://cloud.githubusercontent.com/assets/12596797/11871188/e5e4039c-a49b-11e5-96ef-13700992b15d.png)

#### Day 7
Subject line: How can we help?

![day-7-v4](https://cloud.githubusercontent.com/assets/12596797/11871255/59fe69e8-a49c-11e5-95e5-5e2a33a7186b.png)

#### Day 11
Subject line: Your free trial expires in 3 days

![day-11-v4](https://cloud.githubusercontent.com/assets/12596797/11871260/607b565a-a49c-11e5-8efc-74c7e0ec2909.png)

#### Day 13
Subject line: Your free trial expires in 24 hours

![day-13-v4](https://cloud.githubusercontent.com/assets/12596797/11871265/677027ba-a49c-11e5-80e7-1f7523bb84dd.png)

#### Day 14
Subject line: Your free trial has ended

![day-14-v4](https://cloud.githubusercontent.com/assets/12596797/11871267/6d552338-a49c-11e5-8328-eb30d04a9845.png)

#### Day 16
Subject line: Your free trial will be removed in 24 hours

![day-16-v1](https://cloud.githubusercontent.com/assets/12596797/11903488/9845d0b0-a587-11e5-98f4-47ca56173b39.png)

The timer will be an animated gif with the seconds counting from `59` to `00`

**Comment by mikeshelton1503** [comment]
The above designs have the copy for the Premium emails. I'll provide copy for the Business emails soon in Google doc (along with the Premium copy so we can copy and paste).

**Comment by mikeshelton1503** [comment]
Also just a note, which may seem obvious, but if a user upgrades, the email stream should cease.

**Comment by mikeshelton1503** [comment]
Also noting that for the Day 14 email, a survey needs to created to link to for the "tell us why" link. I'll work on this, presumably using a Polldaddy survey.

**Comment by mikeshelton1503** [comment]
The email copy will need to be update for these emails now that we are going to include domains in the free trials.

**Comment by mikeshelton1503** [comment]
Note: Change all `Upgrade Now` CTAs to `Purchase Now`

**Comment by spncrb** [comment]
Re: Day 13 email - "uploaded videos will disappear" makes it sounds like we will delete the videos - but in reality we will keep any uploaded videos on their site - is there a less destructive way to warm this up?  Maybe "the ability to upload new videos will disappear" or "the video upload will disappear" ?

**Comment by mikeshelton1503** [comment]
> Re: Day 13 email - "uploaded videos will disappear" makes it sounds like we will delete the videos - but in reality we will keep any uploaded videos on their site - can we warm up this messaging?

That was an oversight. "The ability to upload new videos will disappear" sounds good to me. Thanks @spncrb!

**Comment by scruffian** [comment]
We started working on implementing this in on WPCOM, but I'm moving it back to the backlog until I am ready to work on it again.

**Comment by mikeshelton1503** [comment]
I've written copy for both the Premium and Business versions of these emails.

Premium: https://docs.google.com/a/a8c.com/document/d/10wmItmBvV7NDzQOa_wAhy5U5FNOelaUdrzJDv48Ab84/edit?usp=sharing

Business: https://docs.google.com/a/a8c.com/document/d/1XTmP25kPi5fOGkKSZeWT2FZ_ZMMYq13yovyH-Llr7dw/edit?usp=sharing

cc @breezyskies for review

**Comment by breezyskies** [comment]
@mikeshelton1503 Looks great! Made a few small comments in the Premium doc (on copy that is used in for both plans).

**Comment by mikeshelton1503** [comment]
@scruffian Here is the HTML template:
[free-trial-template.zip](https://github.com/Automattic/wp-calypso/files/70429/free-trial-template.zip)

I have tested in all email clients using Litmus and is work great everywhere. Gmail App for Android has a few inconsistencies but overall presents fine. Once you're done I'll be happy to run it back through and fix any further issues.

A few notes about the template:
 - I tried to include examples of all of the necessary components used in all of the emails.
 - All images have been created and are already saved in the appropriate folder
 - For the buttons, to ensure they render consistently in Outlook I am using `[if mso]`conditional code. When editing the code for buttons, it's important that any edits be made to both the conditional code and `<a>` including the button copy.
 - I have included a preheader text section at the top, just inside `<body`. However, copy hasn't been written for that yet. I'll add that to the copy docs.

**Comment by drewblaisdell** [comment]
@mikeshelton1503 Which URL should be used for the 'Read More Frequently Asked Questions' link in the day 11 email?

**Comment by mikeshelton1503** [comment]
That is suppose to go to a to be created FAQ support page. I'll work on creating that however in the meantime lets just remove the link.

**Comment by fabianapsimoes** [comment]
@drewblaisdell what's the current status of this task?

**Comment by drewblaisdell** [comment]
We're tracking this issue elsewhere now: p6qnuF-ji-p2
