### ISSUE TITLE
People: Create new user endpoint

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#115]
As part of people management, we will need the ability to create new users on self-hosted sites.

`POST /sites/$site/users/new`

Here's a screenshot of the "Add New User" interface in WP Admin:

<img width="1012" alt="screen shot" src="https://cloud.githubusercontent.com/assets/1126811/9239936/68b0e918-4126-11e5-86e7-5ddb56b9b85e.png">

Heads up for whoever implements this: The data handling for adding new users through WP admin is taken care of in the [wp-admin/user-new.php](https://github.com/WordPress/WordPress/blob/d92795db13f862e7d82fc74029cb1bdc5293aa5e/wp-admin/user-new.php) file. This means that the emails for sending out confirmation email and invites is buried beneath code that expects `$_POST` and `$_REQUEST`. We may need to look at refactoring this code in core.

Related to #114 - which is for creating the page/UI for adding a new user.

**Comment by ebinnion** [comment]
For m7, we will just be creating invitations for WP.com sites. So, I'm going to go ahead and remove the milestone for now.
