### ISSUE TITLE
Editor: Drag/drop overlay not extending over the whole screen while in Editor

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#11509]
#### Steps to reproduce
1. Start writing a new post 
2. Try to drag/drop an image onto the editor to add it to the post

#### What I expected
The Drag & Drop overlay to cover the whole editor screen.

#### What happened instead
The overlay only covers part of the screen in height.

It seems the Editor isn't expanding to full page height, which makes the popup only cover the part of the page that the Editor itself covers.

#### Browser / OS version
Version 56.0.2924.87 (64-bit) / macOS 10.12.3

#### Screenshot / Video

With an empty editor:

![shrunk](https://cloud.githubusercontent.com/assets/184938/23174602/982fc734-f865-11e6-8001-b1d80b57db3a.png)

With text in the editor:

![extended](https://cloud.githubusercontent.com/assets/184938/23174636/ba365708-f865-11e6-842c-a971ce1005f1.png)

#dogfooding #manual-testing

**Comment by jeremeylduvall** [comment]
I thought I could reproduce this at first, but it's now working correctly both in prod and locally. Can you still reproduce?

![dragdrop](https://cloud.githubusercontent.com/assets/7240478/23305520/70a6cfc0-fa5c-11e6-812d-2537e0961f6a.png)

I tried various setups with/without content in the editor and title field.

**Comment by bisko** [comment]
Yes, I can't seem to be able to reproduce it at the moment. I will close it for now and reopen it in the future if the same problem appears again.
