### ISSUE TITLE
Media upload: Image "flickers" when uploaded through Drag and Drop

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#11507]
#### Steps to reproduce
1. Go to the editor, either editing or creating a new post
2. Drag and drop an image to upload

#### What I expected
The image was shown outright, without any further obstructions.

#### What happened instead
The image flickered for a moment

#### Browser / OS version
Version 56.0.2924.87 (64-bit) / macOS 10.12.3

#### Screenshot / Video
 
![out](https://cloud.githubusercontent.com/assets/184938/23173942/7e299510-f863-11e6-9bee-94ac97187bc3.gif)

#### More details

I think this is happening because the image ( first showing the local copy ) is replaced with the CDN version when the upload finishes. This replacement should happen only after we've successfully loaded the image back.

This is very visible if you try to throttle your connection speed with Chrome's development tools and upload a big image.

#dogfooding #manual-testing

**Comment by lancewillett** [comment]
Nice find.

**Comment by bisko** [comment]
Hey, hey Stale bot! Thanks for reminding us of that issue! It has already been fixed in #14950 . There are still some improvements left to do, but they will hopefully be covered by the migration to Gutenberg in the future.
