### ISSUE TITLE
Media Section: Update Storage Component (5 Points)

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#11508]
Update styling for the https://wpcalypso.wordpress.com/devdocs/blocks/plan-storage component to match mocks. Make sure that the media modal in post/page editor looks ok too. Ping @iamtakashi if we need further design help

Related #11056

**Current:**
<img width="245" alt="screen shot 2017-02-22 at 12 48 30" src="https://cloud.githubusercontent.com/assets/908665/23212148/487929c2-f8fd-11e6-9b18-1f79a20243e4.png">

**New:**
<img width="186" alt="screen shot 2017-02-22 at 12 46 55" src="https://cloud.githubusercontent.com/assets/908665/23212106/0fb3214c-f8fd-11e6-9672-9c4519c8b6c2.png">

Primary Tasks
- [x] Move component into `blocks/` place
- [x] rewrite component using `class`
- [x] It's no longer like a button.
- [x] No plan name.
- [x] It has an explicit link "Upgrade" that takes you to `/plans`
- [x] Clicking on other parts of the component, no longer take you to `/plans`
- [x] We don't show it at all for Business plan because there is no upgrade and the storage is unlimited.

**Examples**
(In Media Section:)
![section-default](https://cloud.githubusercontent.com/assets/908665/22428967/e675dcec-e700-11e6-8776-6cb208e09eae.jpg)

(In Media Modal:)
![modal-default](https://cloud.githubusercontent.com/assets/908665/22429041/2bf2633a-e701-11e6-94b3-a9add1b78622.jpg)

Related #10805

PR: https://github.com/Automattic/wp-calypso/pull/11574

-----

`updated: 2017-02-23` by @retrofox

**Comment by retrofox** [comment]
@iamtakashi do you have at hand style values of this?
![image](https://cloud.githubusercontent.com/assets/77539/23278996/52fd62be-f9f2-11e6-8c13-98738394024f.png)

I think `color` and `font-size`

**Comment by iamtakashi** [comment]
We might need to adjust it but I used the following for the mockup.

> 61.2% of ....

`color: $gray-dark`
`font-weight: 500`
`font-size: 11px`

>Upgrade

`color: $blue-wordpress`
`font-weight: normal`
`font-size: 11px`

There is no change on the accent colours.
