### ISSUE TITLE
AT: Domains: Disable user-to-user transfer

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#11517]
We should disable user to user transfers as they will transfer domains to somewhere impossible to recover. Related: #11448 and p1487710106008183-slack-faster-transfers

**Comment by jhnstn** [comment]
@umurkontaci #11584 covers the user to user transfers on the frontend. 
Not sure if we want to do a server side check as well.

**Comment by umurkontaci** [comment]
Thanks! Normally I think we must do a backend check for this particular case because transferring a domain puts it in a state that's almost impossible to recover.

**Comment by jhnstn** [comment]
I figured, I can start on server bits now

**Comment by jhnstn** [comment]
D4544-code : Server side check

**Comment by jhnstn** [comment]
D4544-code 📦
