### ISSUE TITLE
Editor and Site Settings: remove Markdown setting as it's not fully supported in Calypso

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11510]
I think we should remove the setting to turn on Markdown in Calypso.

For the short-term, hiding the Calypso setting won't don’t disrupt current users who’ve enabled Markdown in wp-admin or Calypso previously. Any existing posts still work, you can still paste in Markdown and it’ll save.

However, Markdown isn't fully supported for everyone yet — and the API needs a bit more work, see #2373.

Until that time let's hide the setting and anyone wanting to turn it on can still access it via wp-admin.

Long-term we'd like to support it on all sites by default, which means the setting won't make sense then here either.

<img width="790" alt="screen shot 2017-02-21 at 09 42 50" src="https://cloud.githubusercontent.com/assets/66797/23175239/fbb3bf6c-f81b-11e6-9965-76c516506c7d.png">

**Comment by lancewillett** [comment]
Project note: we should also hide the wp-admin equivalent for full feature parity:

<img width="1101" alt="writing_settings_ _lancetest35_really_long_title_ _wordpress" src="https://user-images.githubusercontent.com/66797/28931552-5b647fc0-782b-11e7-83e0-bbc373ba7fc7.png">

Hat tip: @MichaelArestad

**Comment by alisterscott** [comment]
@lancewillett if we hide this setting in wp-admin I think we should switch off support for it completely and remove the associated support page: https://en.support.wordpress.com/markdown/

It's very frustrating using markdown to create footnotes as they don't work: `p2-p4k3M4-2uO`
