### ISSUE TITLE
Help page locale (es): two links needs to be replaced with the Spanish version

### ISSUE THREAD

**Issue by nellofn** [Automattic/wp-calypso#11520]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/account
2. Switch UI to: es - Español
3. Save the changes
4. Click on the ? help icon or go to this URL: https://wordpress.com/help

#### What I expected
_"Empieza ya"_ and _"Todos los artículos de ayuda"_ links should open the translated Spanish support docs.

#### What happened instead
_"Empieza ya"_ and _"Todos los artículos de ayuda"_ links points to the English support documentation

#### Spanish Links to be added

**Empieza ya:** https://es.support.wordpress.com/inicio/
**Todos los artículos de ayuda:** https://es.support.wordpress.com/

#### Screenshots

- "Empieza ya"

<img width="792" alt="empieza ya" src="https://cloud.githubusercontent.com/assets/17755234/23192498/21ce8d4a-f87a-11e6-95b3-c80572a5bc88.png">

- "Todos los artículos de ayuda"

<img width="870" alt="articulos de ayuda" src="https://cloud.githubusercontent.com/assets/17755234/23192500/271f0eb4-f87a-11e6-911b-75d9e8f046e4.png">

#### Browser / OS version
Chrome Version 56.0.2924.87 (64-bit) / macOS Sierra 10.12.3

#### Context / Source
Test is part of a support rotation.

#i18n, #manual-testing, #support #rotation #spanish_support

**Comment by nellofn** [comment]
Could it be possible to have these links changed?

**Comment by ramonjd** [comment]
Hi! I've created a quick fix #22370

As mentioned, it's not ideal. I can take a look behind the scenes to see if it's feasible to do server side redirects.
