### ISSUE TITLE
Reader: Tags shows a non-translated string if locale (es - Spanish) is set

### ISSUE THREAD

**Issue by nellofn** [Automattic/wp-calypso#11522]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/account
2. Switch UI to: es - Español
3. Save the changes
4. Click on Lector -> Etiquetas

#### What I expected
- String _"Find relevant posts by adding a tag."_ translated in Spanish

#### What happened instead
- String _"Find relevant posts by adding a tag."_ doesn't have a Spanish Translation

#### Screenshots

![image](https://cloud.githubusercontent.com/assets/17755234/23193422/51f04f40-f87f-11e6-9023-67bc426fad5b.png)

#### Browser / OS version
Chrome Version 56.0.2924.87 (64-bit) / macOS Sierra 10.12.3

#### Context / Source
Test is part of a support rotation. 

- I'd suggest to either add the string to the repository, or use this proposed Translation: _"Encuentra entradas relevantes añadiendo una etiqueta."_

#i18n, #manual-testing, #support #rotation #spanish_support

**Comment by akirk** [comment]
@bluefuton This line has been originally created by you. Could you please remove the `\xa0` from the string and use a CSS or JS no-widows? Thanks!
