### ISSUE TITLE
Notifications: Typing @ in comment notification reply causes lost characters

### ISSUE THREAD

**Issue by astralbodies** [Automattic/wp-calypso#11526]
#### Steps to reproduce
1. Find a comment notification.
2. Click reply.
3. Type some text. Hit enter. Type `@` followed by a username or random text to simulate @-pinging someone.

#### What I expected
Either username completion is presented like on wpcom or no username completion but still able to type characters.

#### What happened instead
Characters are sometimes blocked from appearing in the text box after the @ symbol.

#### Browser / OS version
Safari 10.0.3

#### Screenshot / Video
https://cl.ly/2f2R282Q3y1m

#### Context / Source
#dogfooding

**Comment by designsimply** [comment]
Maybe related: https://github.com/Automattic/wp-calypso/issues/11567

**Comment by designsimply** [comment]
Closed https://github.com/Automattic/wp-desktop/issues/296 as a duplicate.

**Comment by designsimply** [comment]
Tested and confirmed using Safari 10.1 on Mac OS X 10.12.4 and the following steps to reproduce:

1. Log in to https://wordpress.com/
1. Click the bell icon at top right to open the Notifications panel.
1. Type "@" followed by any characters.

<strong>Result:</strong> text after "@" doesn't stay in place and the following console error appears for each key press:

> ReferenceError: Can't find variable: React
> bootstrap 24ac0fc7363f3594681c:13

![screen shot 2017-05-02 at tue may 2 1 40 23 pm](https://cloud.githubusercontent.com/assets/1119271/25636172/d5da07ac-2f3d-11e7-921d-b74afcfbf5b0.png)
<sup>Seen at https://wordpress.com using Safari 10.1 on Mac OS X 10.12.4.</sup>

**Comment by kwight** [comment]
This is no longer reproducible; I'm fairly certain it was solved by @rodrigoi in https://github.com/Automattic/notifications-panel/pull/204.
