### ISSUE TITLE
Jetpack SEO settings: Conflicting notices/banners when on Free plan

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#11538]
#### Steps to reproduce
Connect a Jetpack site with the `free` plan.
Navigate to https://wordpress.com/settings/seo/%site%

#### What I expected
I expected to only see the banner prompting to upgrade

#### What happened instead
<img width="817" alt="screen shot 2017-02-22 at 2 14 27 pm" src="https://cloud.githubusercontent.com/assets/7129409/23228071/40666e64-f909-11e6-88db-642224bed401.png">

Clicking `enable` takes me to `/wp-admin/admin.php?page=jetpack#/engagement`, which also prompts me to upgrade.

**Comment by tyxla** [comment]
I'm closing this one, because this issue no longer occurs; we now have only the upgrade banner:

![](https://cldup.com/p4Iaz4Mar7.png)

Feel free to reopen if you encounter it again.
