### ISSUE TITLE
Sharing: "Other Connections" perpetually loads for Jetpack sites

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#11542]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/sharing
2. Select a Jetpack site

#### What I expected

"Other Connections" group should display connections or disappear after connections have been loaded. It's clear that connections eventually load because the "Publicize Your Posts" connections populate (see Facebook "Disconnect" in screenshot).

#### What happened instead

"Other Connections" shows as loading forever.

#### Browser / OS version

Google Chrome Version 56.0.2924.87 (64-bit)
macOS Sierra Version 10.12.3 (16D32)

#### Screenshot / Video

![image](https://cloud.githubusercontent.com/assets/1779930/23229609/dee5e740-f90e-11e6-81a0-830b9e9dee10.png)

#### Context / Source

@obenland : Might this be related to recent refactoring of this screen?

**Comment by obenland** [comment]
> Might this be related to recent refactoring of this screen?

Yes, that is likely. I came across that while working on #8991 and added a fix for it there. I wasn't aware it happened even when using ConnectionsList. I'll have a PR up shortly
