### ISSUE TITLE
Site picker chokes when path does not include registered route

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#11543]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sites/yoursite.com (must be one of your sites)
2. Try to click to view any of your sites

#### What I expected
I expected to be taken to `https://wordpress.com/stats/insights/whateverSiteYouClicked.com`

I run into this sometimes when I instinctively try to navigate directly to `https://wordpress.com/sites/mysite.com`.  I expect at least the site picker to work at that point.  

#### What happened instead
Nothing.  No console errors. Seems like `addSiteFragment()` fails silently when passed an unregistered path.  

#### Screenshot / Video
![sitepicker](https://cloud.githubusercontent.com/assets/7129409/23230152/d69d74e8-f910-11e6-81ef-add931e004ab.gif)

**Comment by alisterscott** [comment]
I can confirm this is still an issue with that route/site picker

**Comment by alisterscott** [comment]
Should also work for `/settings`, see: #15011

**Comment by mariovalney** [comment]
I guess it was solved by this PR: #25785

**Comment by alisterscott** [comment]
Confirmed fixed vy #25785
