### ISSUE TITLE
Editor: Border of Featured Image Bleeds in HTML mode

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#11553]
When editing a post in HTML mode that has a featured image set, the bottom border of the featured image is visible when scrolling down the page:

<img width="990" alt="edit_post_ _trout_bummin_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/23235467/7507ba50-f90a-11e6-93ff-7d0be633e0fe.png">

**Comment by rachelmcr** [comment]
Closing as this will be resolved with the block-level visual/HTML modes in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
