### ISSUE TITLE
Editor: Autosave reverts content typed while autosaving

### ISSUE THREAD

**Issue by notnownikki** [Automattic/wp-calypso#11567]
#### Steps to reproduce
1. Go to your WordPress site
2. Click the "Write" button in the top toolbar
3. Start to type a title. Type a character every half second or so.
4. Wait for autosave to kick in
5. Keep typing while autosave is autosaving
6. Wonder where your title went

#### What I expected

I expected that autosave would keep the content I was typing when autosave was running

#### What happened instead

The title reverts to the state it was in when autosave started.

We've had reports this happens on tags and the post body too, but for some reason it's harder to reproduce there.

#### Browser / OS version

Chrome/Firefox, Windows/Mac/Linux

#### Screenshot / Video

https://cloudup.com/ctBtqSg67o9

#### Context / Source

#intense-frustration #data-loss #user-report

**Comment by lancewillett** [comment]
I've run into this quite a few times in recent weeks. Most are with the post title — I'll start typing a few words, when auto-save kicks in, the last word and a few letters are deleted from the title.

**Comment by designsimply** [comment]
I've seen this happen too! The steps to reproduce are perfect. And props @notnownikki for the screencast!

**Comment by mtias** [comment]
Could be related to #8814.

**Comment by alanpugh** [comment]
I have a ticket that looks like it could be related to this.  
https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3083069
>I spent today writing an article, which as I clicked publish just now loaded up
the first thing I wrote this morning, wiping an entire day's work.

**Comment by timmyc** [comment]
PR was reverted, re-opening this issue for now.
