### ISSUE TITLE
Media: Search is broken, gets stuck in flickering loop

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#11566]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Click the Add Media icon
3. Search for media, eventually the search will break and be stuck in a flickering loop.

#### What I expected
To be able to search my media library

#### What happened instead
Search does not work and gets stuck in a flickering pattern

#### Browser / OS version
Chrome 56, OS X 10.11.6

#### Screenshot / Video
![calypso add media flicker](https://cloud.githubusercontent.com/assets/1900444/23266034/96623fb8-f9b4-11e6-8d6a-6494508578be.gif)

**Comment by kriskarkoski** [comment]
@gwwar Does this seem related to Image Editing launching?

**Comment by aduth** [comment]
FWIW, tried on my own site and search worked well (same OS, browser). Could be specific to the count/types of media on the site?

**Comment by kriskarkoski** [comment]
I reproduced it on my normal site (kriskarkoski.com) with a few dozed images and the test site in the screencast above (k2testblog2.wordpress.com) has just one image on it.

**Comment by gwwar** [comment]
> Does this seem related to Image Editing launching?

It's probably unlikely. The integration is basically an extra edit button on the details view + upload flow.

Maybe a placeholder/query bug?

**Comment by jeremeylduvall** [comment]
I was able to reproduce this pretty reliably. Whenever I reproduced and then closed the media modal, I received this error in my console:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the MediaLibrary component.

**Comment by kriskarkoski** [comment]
I saw a similar issue on the search at /design, but couldn't reproduce it as reliably as the Media one. Are they a shared component where the issue might be from the same cause? 

With /design the search should have returned 2 themes, but flickered and the result count kept incrementing (it eventually.exceeded the number of themes we have)

**Comment by jeremeylduvall** [comment]
I was just able to reproduce on /design as well. There's not a real pattern to reproducing that I've found. They both eventually use the same [`Search`](https://github.com/Automattic/wp-calypso/blob/master/client/components/search/index.jsx) component. I wonder if this is just a timing issue where we're trying to call `setState`, but the component isn't ready yet in some instances.

**Comment by gwwar** [comment]
Noticed this while testing other items. Without looking at the code it's likely a bad redirect loop of both the search updating the url, and the url setting state for the search bar. 

The gif here shows the flickering behavior still going on forever after I stopped typing.
![redirectloop](https://cloud.githubusercontent.com/assets/1270189/23318446/49872522-fa87-11e6-87ea-70a1d05dba42.gif)

**Comment by fhaps** [comment]
I was also able to reproduce this error as well. In my case, I noticed it happens when searching for a word that is in at least one of the media files... was able to reproduce in two different sites. But the flickering behavior did not happen when searching for a word that did not throw any results.

**Comment by jeremeylduvall** [comment]
Had a chat about this in 206753-chat. Same thing happening in the search on the posts page.

**Comment by kriskarkoski** [comment]
@gwwar This still seems to be happening on the Themes search at least. Here's a video:

http://d.pr/i/Mppp

**Comment by gwwar** [comment]
@kriskarkoski This looks like a different issue as the # of items in results is increasing. Do you mind opening a new issue with steps for Hyperion?

**Comment by kriskarkoski** [comment]
Sure thing, the items increasing is what was happening from the begging on the themes page at least. I will close this once I open the new issue.

**Comment by kriskarkoski** [comment]
Closing this issue as I am no longer able to reproduce the theme search issue.
