### ISSUE TITLE
Themes: Retired Currents theme can be purchased/activated from /design

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#11568]
#### Steps to reproduce
1. Starting at URL: wordpress.com/design
2. Search for the Currents theme
3. Activate it if on a Premium/Business plan, or purchase it if you do not have access to free premium themes
4. Theme is activated despite being retired

#### What I expected
The retired Currents theme to not show as available in Calypso

#### What happened instead
On a brand new user account with no upgrades the Currents theme can be searched for and purchased like any active theme

#### Browser / OS version
Chrome 56, OS X 10.11.6

#### Screenshot / Video
![screen shot 2017-02-23 at 11 38 47 am](https://cloud.githubusercontent.com/assets/1900444/23269215/cf53290a-f9bd-11e6-8581-37f53fa2a9bd.png)

**Comment by kriskarkoski** [comment]
I checked all of the Premium themes included in the Premium plan and Currents seems to be the only retired one appearing in Calypso

**Comment by folletto** [comment]
This was fixed by @laurelfulford: the retirement of the theme had a missing step. Now it's properly retired, and it's not showing up anymore.

**Comment by seear** [comment]
Thanks @laurelfulford! For future reference, do you know which step had been missed?

**Comment by folletto** [comment]
> For future reference, do you know which step had been missed?

The theme wasn't "unpublished" from wp-admin (i.e. set back to "Draft").
