### ISSUE TITLE
Domains: Create a flow for restoring a parked domain

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#11577]
#### Context / Source
#manual-testing

Right now if you cancel some domains, they get parked at a8c - since they cannot be revoked/cancelled.

We already block other users from purchasing this domain for a couple weeks, per the warning about the domain being recently mapped by another user.

For the user who did previously own the parked domain, I'd like to suggest a flow that allows them to restore the domain to their account. 

This would do the same thing as the Restore option, which HEs can use, but without an HE being needed.

**Comment by umurkontaci** [comment]
I think it's a sound improvement, @spncrb do you have an idea about how much volume restoring domain tickets generate?

**Comment by spncrb** [comment]
I would say anecdotally that I see a couple a week, max, so not urgent but definitely an improvement to be made when resources allow.
