### ISSUE TITLE
Media section: abstract away `post-editor/media-modal` and `my-sites/media/main`

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#11592]
This is a part of #11589.

`post-editor/media-modal` and `my-sites/media/main` have much common functionality now.
Because `MediaLibrary` component was not designed so well in the area of data flow, bunch of callbacks are passed as props and the machanism for selecting 
Media Modal and Media section do a very similar thing, but because components are sliced this way and not the other, a lot of methods are duplicated.

After a proper abstraction has been made here, following tasks can be done:
- Reduxify
- ES6-ify
- Get rid of sites list

**Comment by artpi** [comment]
Also, solve issue noticed by @gwwar :

> In the media section select a number of items, click edit, page to some position other than the first item. Click "<- Media Library". Click Edit again. We start at position 0. (The media modal in the post editor remembers which item you had open).

**Comment by rralian** [comment]
I'm not sure I agree with the idea of abstracting these two pieces into a single component. I find that the flow of how you get into editing images has a big impact on the use (inserting images into a post versus grooming existing images), and it's easy to conflate the two. I think abstracting the two into a single component would make us less likely to treat each flow individually.

**Comment by artpi** [comment]
I am not arguing one way or the other, its just the code right now is a copy-pasted mess.
But I dont have strong opinions here

**Comment by rralian** [comment]
Right, I'm not arguing against making the code better. I'm just being careful about making sure we tailor the treatment to the individual flow, because otherwise I think we're likely to make changes for the "insert" flow without thinking about how it impacts the "grooming" flow or vice-versa.

**Comment by rralian** [comment]
I'm going to close this. Let's refactor as part of work we do on the feature if/when it feels necessary. But I strongly argue against trying to combine media-modal and media/main into one component. The use cases and form factors are very different, and I think that will lead to us optimizing for one use case while causing problems for the other.
