### ISSUE TITLE
Editor: Too easy to Publish when wanting to Save

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#11597]
Working with a user who finds the current setup of Publish/Update button versus the save option too heavily focused on Publish. Their explanation being that when working quickly, you may not be reading the buttons and it's very easy to aim for the prominent Publish button. Those with a habit of clicking save very often can lead to unintentionally publishing.

Could be a good idea to keep in mind for future design enhancement.

#### Steps to reproduce
1. Create a new post and add some content
2. The post auto-saves in the background
3. Create an urge within yourself to "want to save" the post urgently
4. There's a big blue button! Let's hit that and get back to work.

Post gets published on accident.

#### What I expected

At all times before the post is initially published, make a clearer distinction between saving and publishing. Allow me to click a button to save (even if autosaved) if only for the catharsis.

#### What happened instead

Publish is such a strong call to action it can easily someone who only wants to save.

#### Context / Source

Discussion with user in 3077621-t

**Comment by alisterscott** [comment]
Could this issue be solved with a "Are you sure?" or an "Undo Publish" feature similar to GMail?

Raised previously here: https://github.com/Automattic/wp-calypso/issues/4562

**Comment by mcsf** [comment]
I too would love a mechanism (whether undo or confirm) for added peace of mind when editing posts.

**Comment by alisterscott** [comment]
I raised this undo publish suggestion a while ago as #4562 - similar to how GMail offers an undo send.

I also noticed this comment on the Editor redesign launch post:

> I’m going to be honest, the position and size of the publish and schedule button is completely wrong. It is even more difficult not to accidentally hit publish when you are trying to set up a schedule...

[link](https://en.blog.wordpress.com/2017/03/13/a-distraction-free-writing-space-at-wordpress-com/#comment-232802)

**Comment by alexjgustafson** [comment]
Is there anywhere else  in calypso that we have made improvements to avoid unintended actions? If so perhaps that approach might help here as well?

**Comment by folletto** [comment]
In general, I'd always go for "Undo" vs "Are you sure", because it matches my intent and doesn't feel the UI is being annoying.

This is true in this case too. Adding a small grace period before sharing / emailing as well as an Undo would do great.

**Comment by rachelmcr** [comment]
I believe this is resolved with the new publish confirmation step that appears after selecting Publish, which gives users a moment to confirm they want to publish the moment:

![screen shot 2017-10-04 at 6 39 18 pm](https://user-images.githubusercontent.com/8658164/31190563-5980c388-a933-11e7-97ee-6fff58d255bd.png)

We also still have #4562 if we want to explore an "undo" feature, but I'm closing this issue since accidental publish is less likely now. Please feel free to reopen if you don't think it's fully addressed yet. :)
