### ISSUE TITLE
Settings: convert group titles and labels to sentence case

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#11616]
Right now some are title case and some are sentence case. After a discussion in slack, we should be using sentence case for most things.

Example: "Related Posts" should be "Related posts"

**Comment by tyxla** [comment]
@MichaelArestad: the example you've provided is super crystal clear, but perhaps we should then alter the issue name to "**Settings: convert group titles and labels to sentence case**"?

Also a quick question: should this apply to all titles and labels in Settings? Or perhaps there will be some exceptions (other than names like "**Jetpack Protect**" / "**Google Analytics**")?

**Comment by MichaelArestad** [comment]
> the example you've provided is super crystal clear, but perhaps we should then alter the issue name to "Settings: convert group titles and labels to sentence case"?
@tyxla ha! Thought I already did that. Changed.

> Also a quick question: should this apply to all titles and labels in Settings? 

The only exceptions are proper names (like Google Analytics). Jetpack protect shouldn't be capitalized and should actually be changed to "Prevent brute force login attacks" for now.

**Comment by rickybanister** [comment]
I'm closing this—we've mostly completed this scrub, if any further issues like this exist we can open a specific issue or PR to fix.
