### ISSUE TITLE
Devdocs: title and intro for /devdocs/design

### ISSUE THREAD

**Issue by nb** [Automattic/wp-calypso#1162]
Landing on `/devdocs/design` doesn’t tell us where we are or what is the purpose of the page:

![screen shot 2015-12-01 at 17 43 50](https://cloud.githubusercontent.com/assets/27954/11516732/2b0bb10e-9853-11e5-8b03-00bc81386531.png)

**Comment by lancewillett** [comment]
App Components needs this, too: https://wpcalypso.wordpress.com/devdocs/app-components

**Comment by lancewillett** [comment]
See notes in #3993 as arguments **against** adding this.

**Comment by folletto** [comment]
Note that in practice this _was_ a problem when this issue was opened since the sidebar highlight wasn't working, but it was merged, thanks to an external contributor, a couple of weeks ago, in #3652.  :)
