### ISSUE TITLE
New user setup: I want to add the items i'm selling (Add products)

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#11646]
Success criteria: If adding manually, user will have added a product in 5 clicks. If importing, 2 clicks.

Master Sketch file: https://www.dropbox.com/s/5gspfg0886qh3yw/add%20product.sketch?dl=0

**Comment by jameskoster** [comment]
Notes from our call on Tuesday;

- Testing the step-by-step flow, iterating on it. This flow is good for;
- - First time user who only has a few items to sell
- - When you are adding a product or two to your inventory
- - Those who are uncomfortable / new to the whole selling on line and just like how this flow walks them through adding a product. They might stay with this until comfortable and graduate to another flow
- Has an escape hatch where you can view everything at once in a 'detail mode' and add all product info on a single page.

Another story: I want to add a bunch of products at once;
- 2 entry points for the 'Import' button; Dashboard, Products list, 
- - CSV import
- - - Allow user to upload their own .csv. They can download a sample .csv to use if required. 
- - - Explore the idea of offering a 'spreadsheet tool' bypassing the need to use excel or equivalent software. This would also provide bulk editing capabilities
- - Migration
- - - Specify which service to migrate from
- - - Authorize
- - - Import
- - If the store is empty offer to import demo products

**Comment by jameskoster** [comment]
We chatted quickly today and concluded that we'd probably leave the built-in spreadsheet tool and bulk editing out of v1 because they're features aimed more at power users.

To begin with uploading a .csv manually is probably fine.

**Comment by kellychoffman** [comment]
Designs for adding a product using the full view only:

1. From Store new user dashboard: Click 'Add a Product'
![02-dashboard](https://cloud.githubusercontent.com/assets/5835847/23624647/b2893522-0263-11e7-9138-6353687ca9f3.png)

2. You click 'skip directly to detailed product editing':
![add product title](https://cloud.githubusercontent.com/assets/5835847/23624798/3bb1ddae-0264-11e7-9f4f-0f6c85eff52f.png)

3. This brings you to:

4. You fill all the information in:
![detailed view](https://cloud.githubusercontent.com/assets/5835847/23624871/79f8fae8-0264-11e7-8acb-27ae37b3c6e3.png)

5. You click 'save':

cc: @justinshreve

**Comment by jameskoster** [comment]
Quick note; that detailed view is a little confusing as it has variation types filled in. The default state look would look like this;

![variation-types](https://cldup.com/hjjtR-sWnw-3000x3000.png)

**Comment by justinshreve** [comment]
@kellychoffman @jameskoster 

How does https://cloud.githubusercontent.com/assets/5835847/23624871/79f8fae8-0264-11e7-8acb-27ae37b3c6e3.png change as more complex variations are added?

**Comment by kellychoffman** [comment]
@justinshreve: Here's an example of a shirt with sizes and colors:

<img width="436" alt="screen shot 2017-03-07 at 9 25 08 pm" src="https://cloud.githubusercontent.com/assets/5835847/23690190/ebdf001c-037c-11e7-92d0-010567b9e4c4.png">

**Comment by jameskoster** [comment]
Example @justinshreve ?

IMO the fields in that table should be kept as simple as possible. Advanced variation data is accessed via the 'advanced details' link beneath the variation name;

![advanced](https://cldup.com/lYLhETv6kT-3000x3000.png)

Clicking that link reveals a modal that looks something like this;

![edit-variation](https://cldup.com/zoaJYK4mHJ-1200x1200.png)

**Comment by justinshreve** [comment]
I was looking for what Kelly posted, but those mockups are helpful too :)

(I was looking for what we would display if we had multiple options on a product i.e. displaying a shirt that has color & size).

**Comment by jameskoster** [comment]
Ah yeah, that's my bad for using 'weight' as an attribute in the granola product. Wasn't sure if you were referring to that or the dimensions etc.
