### ISSUE TITLE
Media: Secondary actions still present when filtered

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#11665]
This appears on both new media section and media modal as well

![zrzut ekranu 2017-03-01 o 11 34 33](https://cloud.githubusercontent.com/assets/3775068/23456326/4ae4a5ee-fe73-11e6-9b05-5d095c9aacfc.png)

## Reproduction steps

1. Select few media items
1. Secondary actions appear
1. Change view to "Documents"
1. The elements are filtered but secondary actions still there.

CC @gwwar @iamtakashi 

Create a selection list for each filter.

**Comment by iamtakashi** [comment]
I've tried to reproduce this but I haven't been able to see the "edit" button so far. I do see "delete" in my testing.

Anyway, I agree that it feels weird the action buttons being there when you don't see any selected items on the current tab, and so is "continue" button. The context is lost there when you go to different tabs. 

One thing to approach is that we show selected items always in a small size somewhere.

**Comment by gwwar** [comment]
👍 Looks similar to the action bar bug I pointed out in the other PR. We probably just need to clear the selection when changing filter tabs. Or apply the filter on the current selection.

**Comment by gwwar** [comment]
Adding to backlog to keep track of this one.

**Comment by iamtakashi** [comment]
With the new design, the buttons only appear if something is selected. So, the easiest solution is hide those buttons if nothing is selected in the current tab.

**Comment by iamtakashi** [comment]
I personally don't like the idea of clearing selection when they go to different tab. The action button should be visible only when you have selected items on the current tab, and the buttons should be effective to the item on the current tab, so that it has a clear context.
