### ISSUE TITLE
Domains: Site Switcher doesn't show after second domain-only purchase

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#11668]
Seems the list of sites isn't updated after domain-only purchases, so the Site Switcher doesn't show when you go from having one to having two sites.

Steps to reproduce:

- Purchase a domain via `/start/domain-first`, using an account with no sites. You'll land in `/domains/manage/:name` after checkout.
- Notice that there's no Site Switcher in the sidebar, since you only have one site.
- Go through `/start/domain-first` again, and purchase a second domain.
- Notice that when you land on `/domains/manage/:name` the Site Switcher is still not visible in the sidebar, even though you now have two sites.
- Refresh the page, and notice that the Site Switcher is now visible in the sidebar.

**Comment by aidvu** [comment]
Did you test it with a fresh user? Sometimes it takes a while for `/sites` to load.
