### ISSUE TITLE
Free Trials: Remove checkout from flow/Add confirmation page

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1169]
Currently the free trials are using credits and a modified checkout page. Ideally we do not want to take users to the checkout page for free trials. The user isn't paying for anything so having a cart on the left is odd for a user. Also using checkout will cause issues when there is already an item in the user's cart.

We do still want to have a page or modal as a confirmation of starting the trial, replacing checkout in the flow.

**Comment by mikeshelton1503** [comment]
I'll provide designs the confirmation screen.

**Comment by mikeshelton1503** [comment]
On a related note: Free trials should not show in the Purchases list since it hasn't been "purchased".

**Comment by mikeshelton1503** [comment]
Now that we are not including domains in free trials, we should use the confirmation screen to inform the user that the domain is not included as part of the trial.

**Comment by mikeshelton1503** [comment]
@fabianapsimoes why was this moved to v2? I feel that this should be a requirement for v1.

**Comment by fabianapsimoes** [comment]
We'll likely drop the confirmation page altogether in the future, considering the high drop-off rate at this step (p6qnuF-1vk-p2). Closing.
