### ISSUE TITLE
Reader: Embedded Google Maps not rendering in full post view

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#11703]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Create a new post and embed a [Google Map](https://en.support.wordpress.com/google-maps/) (Regular embed vs custom map does not matter)
3. Publish post, and view in Reader

#### What I expected
For the Google Map to be visible, as it is when viewing the front end of the site.

#### What happened instead
A blank space appears where the map is supposed to be.

#### Browser / OS version
Confirmed in Firefox 51.0.1, Chrome 56, and Safari 10.0.3

#### Screenshot / Video
Front end:

![google_maps_test_ _kokkiestrialtestsite](https://cloud.githubusercontent.com/assets/11873759/23505411/494b3d86-ff4c-11e6-9eac-4f4298a0283f.png)

Reader: 

![google_maps_test_ _kokkiestrialtestsite_ _reader_ _wordpress_com](https://cloud.githubusercontent.com/assets/11873759/23505456/799e2b7e-ff4c-11e6-9496-b4709f7afcec.png)

#### Additional Note:
The code to show the map is visible if one looks in the browser inspector:

![google_maps_test_ _kokkiestrialtestsite_ _reader_ _wordpress_com](https://cloud.githubusercontent.com/assets/11873759/23505583/ec00f4da-ff4c-11e6-906d-7fc8b67d353a.png)

Test post at https://wordpress.com/read/blogs/100341607/posts/1408

#### Context / Source

Reported via the public forums in 836943-f

**Comment by blowery** [comment]
Thanks, just need to whitelist google for iframes. On it.

**Comment by blowery** [comment]
@KokkieH fixed, should be on prod in a couple minutes

**Comment by KokkieH** [comment]
Thanks, @blowery. Just saw the review request as well.
