### ISSUE TITLE
SEO Tools: Title format editor fields incorrectly disabled

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#11720]
On some WordPress.com sites that have a business plan `Page Title Structure
` fields in SEO section are incorrectly disabled (e.g. meideo.com).

cc @kriskarkoski @chrisfromthelc

**Comment by andreabadgley** [comment]
The user has come back asking about this. Follow up is in 3087374-t.

**Comment by vindl** [comment]
@dmsnell do you have any idea what might be causing this? It's not reproducible on any of my test sites, I can only reproduce it on `meideo.com` (via SU). For some reason `isRefreshingSiteData` remains always true for this one, which causes the Title editor fields to remain disabled: 
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/seo-settings/form.jsx#L163

@andreabadgley if it helps, while we figure what's going on, I could set the SEO title formats for this user manually, if they would be willing to forward their desired settings to us.

**Comment by dmsnell** [comment]
> For some reason isRefreshingSiteData remains always true for this one

this sounds like the important lead to follow. that's all stuff related to `SitesList` which is a mess. Here are a few questions I can think of: do they have lots of users logged in all the time? Is there something odd about their settings? Can we watch the network calls bring in their site settings? Is there anything odd in the response body of those network calls?

**Comment by andreabadgley** [comment]
@vindl That would be awesome! I'll check with the user.

**Comment by andreabadgley** [comment]
@vindl It turns out the user wants Sitelinks, which are handled by Google ([support page](https://support.google.com/webmasters/answer/47334?hl=en)). They gave stratasys as an example:

https://cloudup.com/cynhyvM6w4M

I told them our tools can't do that, and explained how to set page meta descriptions. I also pointed them to the Custom Title Formats section of the SEO tools and asked if there are specific settings they want there.

**Comment by brezocordero** [comment]
@vindl We talked about this issue and I am adding the ticket here for the record.
Business site with SEO settings disabled for editing when front page displays latests posts
Follow up here: 3108332-t
