### ISSUE TITLE
"xyz.com is not set up yet" copy is confusing

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#11741]
While reviewing the Tortuga flow at with Team Cobalt, it was noted that the "xyz.com is not set up yet" is confusing, particularly right after purchase. The "thank you page" from https://github.com/Automattic/wp-calypso/pull/11702 helps with this, but the copy is still a bit unclear. 

As a secondary issue, I'm not sure if we're currently updating the copy here if the user sets name servers / DNS via advanced settings, but we probably should

cc: @ranh @Automattic/cerulean

**Comment by ranh** [comment]
> the "xyz.com is not set up yet" is confusing

There was some copy proposed for this #11452

> **example.com: Temporary page**

We can try this with a bit more personality perhaps:

> example.com is ready when you are

We can also add some supporting copy here, as a subtitle, like we do on the featuregate screen:

> Visitors to example.com will see a temporary page. Start your new site on example.com now. 

Would love to develop this further if you have any thoughts.

**Comment by breezyskies** [comment]
> example.com is ready when you are

Love this direction. 👍 

I'm not as sure about the "temporary page" phrasing, although it's definitely a step in the right direction. My primary issue with it is that it's pretty ambiguous. I guess one option would be to make the parked page actually say "coming soon" or something like that, but might open up a can of worms.

**Comment by danhauk** [comment]
> As a secondary issue, I'm not sure if we're currently updating the copy here if the user sets name servers / DNS via advanced settings, but we probably should

I agree. Just wondering, if a domain has custom name servers and they create a site for that domain, do we pull the DNS records when we switch name servers back to `wordpress.com`?

**Comment by breezyskies** [comment]
> Just wondering, if a domain has custom name servers and they create a site for that domain, do we pull the DNS records when we switch name servers back to wordpress.com?

Yes, and we'd probably want to warn them as well. cc: @fabianapsimoes
