### ISSUE TITLE
Jetpack Plans: can't activate plugin that is already installed on multisite

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#11759]
#### Steps to reproduce
1. Starting from a sub-site, part of a multisite network, as an admin with permissions to admin that subsite and no other. VaultPress should already be installed on the multisite network, but not activated on the sub site. In the Multisite settings, admins should be allowed to access the plugins menu and thus activate or deactivate plugins available in the network.
2. Connect Jetpack to WordPress.com and purchase a plan during the connection process.
3. Go back to Jetpack > Settings and click on the "Set up" button in the VaultPress card to install VaultPress.
4. You'll get the following error:

![screen shot 2017-03-03 at 19 09 38](https://cloud.githubusercontent.com/assets/426388/23566604/f51c2f88-0052-11e7-80b4-cc8ffe83f3ae.png)

In this situation, the site owner has the necessary permissions to activate the plugin, so we should do it for them instead of returning an error.

**Comment by sirreal** [comment]
The UI appears to have been updated, now we wind up here for multi-site:

![manual-setup](https://cloud.githubusercontent.com/assets/841763/25396272/486480fe-29e4-11e7-9019-b5a2cb225d2e.png)

**Comment by sirreal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/Automattic/wp-calypso/issues/11759](https://trello.com/c/bXMNHk8u/67-https-githubcom-automattic-wp-calypso-issues-11759)

**Comment by beaulebens** [comment]
Note that in this case, our auto-config should ideally be more resilient/intelligent and detect that it doesn't need to install the plugin (it's already there), so then it should just try to activate and configure it (which seems like it _should_ work in this scenario).

**Comment by sirreal** [comment]
I've done a significant amount of exploration around this issue, much of which can be observed in #23168 and #23174.

This was much too big for hack week. Considering this issue outside of hack week, there's still a large amount of work required to lay the foundations for a fix like this (#23174). These are major changes just to get things in a state where the relevant improvements could be made. I suspect there are an extremely small number of users who would be affected by an improvement like this, given the requirements:

- Multi-site
- Administrator of a site which is not the main site
- Plugins enabled for the network
- Akismet (it's pretty likely this will be installed as it ships with WordPress.org) and VaultPress (less likely this will be installed).

I think there is valuable refactor work in #23174 which was inspired by this issue, but I think dedicating the amount of time required to fix this particular now would be better spent focusing on other work.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
