### ISSUE TITLE
Accessing `/mailing-lists/unsubscribe` without valid query params renders a broken page

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#11756]
#### Steps to reproduce
1. Go to https://wordpress.com/mailing-lists/unsubscribe

#### What I expected

To see an error message, since I didn't provide valid query parameters stating what mailing list I was unsubscribing from.

#### What happened instead

I was shown a broken page.

![screencapture at fri mar 3 14 36 27 est 2017](https://cloud.githubusercontent.com/assets/2098816/23566175/d34fd62c-001e-11e7-899d-202e887f0348.png)

**Comment by lancewillett** [comment]
Interesting... how would one get to that URL without typing it in directly?

I wasn't aware we had any subscription management in Calypso yet, other than in Reader -> Followed Sites -> Manage.

**Comment by mattsherman** [comment]
There is no direct link to that URL, so a user would have to type it in/manually go up the URL path looking to find something. As such, it isn't a high priority issue, but still something that should be cleaned up.

This unsubscribe is for mailing lists, as can be managed from https://wordpress.com/me/notifications/updates
