### ISSUE TITLE
My Sites or Reader: persist last viewed screen instead of stats as default landing page

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#11755]
Part 1: When you log in to WordPress.com, you end up at the Reader. Not everyone wants to go there each time — especially if they want to edit their site or settings.

Part 2: In the same way, clicking on My Sites you always end up in Stats. Not everyone wants to see stats as their first landing point in My Sites.

A few example stories:

> When I sign in to WordPress.com, I want to see my site dashboard, not the Reader. As a new user, I don’t understand what a Reader is and why I’m seeing that first thing when I want to start working on my site.

> As a new user, and especially on my first time in WordPress.com before any site visitor stats exist, don’t drop me on the stats page. It’s empty! It can be demoralizing to see nothing there. Instead maybe send me to a welcome page, or somewhere to start publishing and sharing so I can work on my “homepage” [aka website, blog] before I draw visitors to my site.

It'd be nice to do this without a user setting or asking someone to choose. Instead base it from their behavior.

What are your ideas to fix this?

For Part 1 — remember my Reader / My Sites habit:
- We could save a state value for either **My Sites** or **Reader** based on the entry point to WordPress.com — if someone clicks "My Sites" immediately after login, and doesn't use the Reader. - The next time the log in, take them straight to My Sites.

For Part 2 — remember my My Sites habit:
- If a blog has very little traffic, or is new (first week or first 30 days) go to Blog Posts instead of Stats.
- Or, just go to the last known view inside My Sites (not anything — but a whitelist of Pages, Posts, and such.)

**Comment by lsinger** [comment]
corrected "go to Blog Posts instead of Drafts." to "go to Blog Posts instead of Stats." (correct me if correction was wrong)

**Comment by lancewillett** [comment]
Shipped with https://github.com/Automattic/wp-calypso/pull/14070
