### ISSUE TITLE
Plans: Loading placeholder for plans should be presented until required data is loaded

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#1176]
Steps to reproduce:
1. Go to http://calypso.localhost:3000/plans
2. Select site. When data loads for the first time, user can see loading placeholder.
3. When users go to the same page again and data is stored in cache, they see this:
![plans-loadin-placeholder](https://cloud.githubusercontent.com/assets/699132/11529304/6d6be5ac-98ec-11e5-898b-a0d4ca50a10d.gif)

It would be great to see all elements of the page rendered at the same time, or we should at least provide some loading indicator in the places where buttons are going to show up.

Page design is okey. This is sth with the software that records gifs.

**Comment by lancewillett** [comment]
This is working as expected now.

Mac-n-Chrome with wpcalypso:

![plans](https://cloud.githubusercontent.com/assets/66797/14366411/7a1a51a0-fcc7-11e5-947b-037b91c32820.gif)
