### ISSUE TITLE
Jetpack Plugins: Manual installation link is unhelpful

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#11776]
#### Steps to reproduce
1. Go through the Jetpack installation process from https://wordpress.com/jetpack/connect/install
2. Have VaultPress and/or Akismet fail to install (I'm not sure exactly how this happens).

#### What I expected

The failure notice should link either to a plugin installation page in Calypso or wp-admin, or to a page that fully explains how to install VP/AK manually.

#### What happened instead

The "Manual installation" link apparently (p1488791750894753-slack-jpop-growth) goes to https://jetpack.com/support/ which has no relevant information.

#### Browser / OS version
Chrome / MacOS Sierra

#### Screenshot / Video

I only have a French screenshot as it was reported by a French user:

![image](https://cloud.githubusercontent.com/assets/1990037/23604161/d649a01e-024f-11e7-9bed-9a2caa04c71b.png)

**Comment by johnHackworth** [comment]
I'm going to add the design label to this, so we can talk about what to do, @rickybanister

**Comment by rickybanister** [comment]
We are swapping out this flow entirely (very soon) for the new Thank You page that includes the auto-config flow. 

If it fails we will provide them a link to https://en.support.wordpress.com/setting-up-premium-services/

Which is exactly what you're suggesting I believe. 

So once the new flow is ready this issue will be closed. 

#12483 

https://github.com/Automattic/wp-calypso/pull/12483#issuecomment-291632429
