### ISSUE TITLE
Inconsistant at post & page management

### ISSUE THREAD

**Issue by ossvn** [Automattic/wp-calypso#1178]
If you have published a post but as scheduled or draft one, on post management won't show the filter bar but it show like this: https://www.wpwiseguys.com/wp-content/uploads/2015/12/wordpress-calypso-small-bug.png instead.

I have written a detailed it here: https://www.wpwiseguys.com/45-wordpress-calypso/ (not PR at all). Moderator: can you please look at "Inconsistant at post & page management" section and tell me if it's a bug?, then you can delete the link.

**Comment by aduth** [comment]
By default, non-published posts from Jetpack sites are not synced to WordPress.com, which explains why they won't appear in the Calypso posts list. There's an upcoming opt-in setting to include these types of posts in a sync, but it is not currently enabled in the production environment.

https://github.com/Automattic/wp-calypso/blob/41c6f0f/config/production.json#L38

The setting will be visible if you run Calypso locally, though be aware that the development environment may not be quite as stable as the production dashboard.

For more specific feature-flag enabling, I'm closing this in favor of #1272.
