### ISSUE TITLE
CPT: Allow users to change CPT Authors

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#11797]
#### Steps to reproduce
1. Edit a Portfolio project in Calypso.
2. Note the absence of the ability to change the Project author to someone other than the original author.

#### What I expected

I expected to be able to switch the Project author as I would for any other Post or Page, using the drop-down toggle on the author's name in the upper left.

#### What happened instead

No ability to click on the author's name, and no drop-down of all available authors on the site. Making the experience consistent between Posts, Pages, and other CPTs would be ideal for reducing user confusion.

#manual-testing #stresscase

**Comment by aduth** [comment]
There are two problems here:

- The `portfolio` type does not have `author` post type supports ([source](https://github.com/Automattic/jetpack/blob/f6495ede1c9510178a41e64d529e20b0c093812b/modules/custom-post-types/portfolios.php#L247-L255))
- Our logic for determining whether to display the editor author field is fairly naive, checking only `edit_others_%(postType)s` capability ([source](https://github.com/Automattic/wp-calypso/blob/1fa3465fbfb4172483ef6170935b8d0fa86ea8cb/client/post-editor/editor-author/index.jsx#L75-L79)). This should be changed to a combination of ensuring post type supports and pulling the `capabilities.edit_others_posts` from the `/sites/%s/post-types` response entry as the capability to check ([docs](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/post-types/))

**Comment by aduth** [comment]
Oof, `author` is right there in the linked source. Let me check if this is the same on WordPress.com, because it's definitely coming across the REST API as not having support.

**Comment by aduth** [comment]
Yeah, appears that https://github.com/Automattic/jetpack/commit/5448754d99426bbf975d26c878db5ca84f7fb8c7 was never synced to WordPress.com (cc @eliorivero).

**Comment by sixhours** [comment]
Thanks Andrew!

I was told to commit the patch for author support, since I was told it would probably be a while before they could merge it back. I ran into a couple pre-commit check failures, though, so I'm working on those.

Does this mean once that patch is live on WP.com, author support will be available in Calypso?

**Comment by aduth** [comment]
>Does this mean once that patch is live on WP.com, author support will be available in Calypso?

I don't think so, because it's checking for a `edit_other_jetpack_portfolios` capability on the REST API site response which does not exist. We'll need to change the component rendering logic per the second of my points noted above in https://github.com/Automattic/wp-calypso/issues/11797#issuecomment-284498100.
