### ISSUE TITLE
Media: tweaks in gallery search styles

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#11804]
After clicking on add to url in the media section, I'm thinking we should either get rid of the extra margin/padding or also have a white background

url open:
<img width="695" alt="screen shot 2017-03-06 at 1 31 34 pm" src="https://cloud.githubusercontent.com/assets/1270189/23630883/82550256-0271-11e7-953e-aca3b174c7d9.png">

initial state:
<img width="711" alt="screen shot 2017-03-06 at 1 35 02 pm" src="https://cloud.githubusercontent.com/assets/1270189/23630947/c3e937f0-0271-11e7-87f0-7785189a7d67.png">

-------
### Pull requests (merge in order)

- [x] Media Library: upload-url janitorial #11828
- [ ] Media Library: improve uploading by URL section #11830

-----

_`updated 2017-03-07` by @retrofox_

**Comment by retrofox** [comment]
I think we should keep the card (background white + boder) when the URL block is shown. cc @iamtakashi

**Comment by iamtakashi** [comment]
Agreed!
