### ISSUE TITLE
Reader: native browser 'find' function is not great

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#1180]
If you use the browsers 'find' function it can get very confused because of the overlayed nature of Calypso pages. This is because the find searches through all HTML, even if it's not visible. If you are looking at a single post in the Reader then the Reader itself is still in the HTML, and the find function searches there even though it's not visible to the user.

Example:

I am in the Reader and search for 'and' - it finds 21 occurrences on the page. Repeatedly pressing the find shortcut cycles through these with an orange highlight. Everything is working as I would expect.

![in_browser](https://cloud.githubusercontent.com/assets/1277682/11531177/d11ded56-98f2-11e5-90a1-81d1e2f77abd.jpg)

If I click on the post and then search for 'and' again I get the same number of results - 21 - even though only 3 are visible.

![in_browser_after](https://cloud.githubusercontent.com/assets/1277682/11531203/02e23342-98f3-11e5-980d-0d76f6fefbcf.jpg)

Repeatedly pressing the find shortcut does nothing other than change the `1 of 21` number in the find box. This is because it is highlighting search terms in the main Reader, which is not visible.

Overall this isn't a major problem - the terms are still highlighted - and it's going to be pretty difficult to fix.

It causes more of a problem in the desktop app as there is no built-in find function and we need to use `window.find`. This does not highlight all the terms, but highlights individual terms each time it is called. In the case of the single post it just doesn't work well.

Note: I've only tried this in Chrome, which is what the desktop app is using.

**Comment by blowery** [comment]
Hmmm... What happens if you make the underlying stream `visibility:hidden` while the overlay is in place?

**Comment by johngodley** [comment]
> What happens if you make the underlying stream visibility:hidden while the overlay is in place?

That's a great suggestion! And it does the trick too. In Chrome the number of occurrences reflects what is just on screen, and in Electron it steps through the ones on screen and then wraps round.

In terms of the Reader, are there any downsides to setting the visibility to hidden? It's a small change  but I'm not sure of the greater impact it may have.

**Comment by blowery** [comment]
I don't _think_ it has any downsides, but we'll have to see. Might affect the way we scroll the underlying list when moving to the next article.
