### ISSUE TITLE
Media: Fix weird visual issue in search icon when scrolling

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#11805]
When the media page is scrolling up the search icon produces a weird visual behavior.

<img src="https://cloud.githubusercontent.com/assets/77539/23630900/79be4f06-029b-11e7-9718-fb15ea8289c6.gif" width="400px" />

<img src="https://cloud.githubusercontent.com/assets/77539/23632972/ab7625e4-02a2-11e7-9b35-4c07b7446b30.gif" width="400px" />

**Comment by iamtakashi** [comment]
I believe this has been fixed already, right?

**Comment by retrofox** [comment]
It's already fixed. Thanks Takashi!
