### ISSUE TITLE
Domains: Remove references to primary domain for domain-only sites

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#11813]
References to a "primary domain" are irrelevant for domain-only sites. cc @ranh 

![screen shot 2017-03-06 at 4 23 37 pm](https://cloud.githubusercontent.com/assets/1130674/23636302/6cc97652-0289-11e7-841c-62a8d9031859.png)

**Comment by ranh** [comment]
The part of the yellow notice related to primary domains should be addressed by the suggestions in #11441 

For the green badge that indicates that the domain is primary, can we just hide it for domain-only sites?
