### ISSUE TITLE
Purchases: issues with notices after purchase cancellation

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#1181]
We have two unaddressed issues with the notices added in #914:

From @mikeshelton1503:

> As I understand it, when you click through from the email a notice is displayed at the top but then disappears when you navigate to another page. Is that correct?

> For a successful notice, there is no problem with it disappearing on a new page, however for the error notice, it should persist until dismissed or fixed.

From me:

> I checked the notices in the links you provided, and noticed there's no dismiss button in them.

cc @drewblaisdell

**Comment by drewblaisdell** [comment]
I think we should use #1142 to track this, because this change will likely accompany a switch to global notices. I updated that issue with Mike's comment and am closing this issue – let me know if I'm doing so in error.
