### ISSUE TITLE
Pages: Incorrect page marked as homepage after using "Set as Homepage"

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#11815]
#### Steps to reproduce
1. Go to Pages screen for a single site.
2. Using the "Set as Homepage" option in the ellipsis popover menu, set a page as the homepage.

#### What I expected

The page I set as the homepage to be marked as the homepage.

#### What happened instead

The incorrect page is often marked as the homepage. See video below.

#### Browser / OS version

Reproduced in Safari and Chrome. Appears to not be browser specific.

#### Screenshot / Video

![pages screen setting homepage issue](https://cloud.githubusercontent.com/assets/2098816/23639399/8b918fda-02b5-11e7-8eb6-1e97bcff4ff0.gif)

**Comment by jeremeylduvall** [comment]
Closed via #13143.
