### ISSUE TITLE
Redirects: Sites that act as redirect show UI that allows them to create Posts

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#11863]
Currently is a site is marked as a redirect still shows the user a UI in Calypso that invites them to manage the site. ( Edit posts, pages etc... ) 

I think this can create confusion for the user. Should we simplified this experience? 

Some related reading p7rcWF-gm-p2

cc: @rickybanister

**Comment by rickybanister** [comment]
I think we should essentially 'brick' all of their content in Calypso—perhaps using something like the functionality we have for TOS violations. They should get a popover if they try to visit any content section other than Domains telling them: `this site is currently acting as a redirect, to add content they must remove the redirect` or similar. 

cc @keoshi 

And @dllh could you remind me if the TOS violation blockage stuff has been implemented fully?

**Comment by dllh** [comment]
I know of no TOS violation blockage stuff. There was I believe a request to offer a better block experience within Calypso, but iirc it was never super well defined or implemented (and isn't on my radar).
