### ISSUE TITLE
Post Schedule: Add `cancel` button

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#1188]
Add the red cross (`gridicons-cross-small.svg`) to the post scheduler to enable the user to cancel:

![image](https://cloud.githubusercontent.com/assets/7233112/11536009/7b33d7ce-98e4-11e5-9949-d9231849bfcc.png)

**Comment by iamtakashi** [comment]
Although we don't have the border and the icon, I'm happy with the red cross button for cancelling, let's go with that.

**Comment by rachelmcr** [comment]
I tested and we now have a "Publish Immediately" option that appears above the calendar. This allows users to cancel scheduling and publish the post immediately instead:

![screen shot 2017-10-04 at 6 15 38 pm](https://user-images.githubusercontent.com/8658164/31189995-b15f66b0-a931-11e7-9aa3-d902f8458ded.png)

Closing as resolved.
