### ISSUE TITLE
Domains: contact form during purchase jumps around when typing on iPad mini

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#11888]
The contact form shown when purchasing a domain is very hard to use on an iPad mini, because the cart listing jumps around while typing.

![calypso-screen-jumps-when-typing](https://cloud.githubusercontent.com/assets/426518/23705212/7c20441c-0411-11e7-9dfd-577f7f2d0e93.gif)

#### Steps to reproduce

I tested this with an iPad mini version 10.2.1. In the capture above I'm on the NUX flow, but it's the same contact-form-in-cart screen if you add a domain to an existing site.

1. Start adding a domain to a WordPress.com site.
2. Reach the contact form.
3. Choose a field and start entering details.
4. The screen jumps around as you type.

**Comment by alisterscott** [comment]
I am seeing this issue on iOS iPhone (switching between standard and numeric keyboards) and also on Android devices.
