### ISSUE TITLE
Settings: Jetpack: move 'migrate followers' link to Subscriptions card

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#11892]
Currently we have a 'migrate followers' link on the General tab in settings. 

Now that we have the Subscriptions card and are using the clickable card pattern for external links, can we move the 'migrate followers' link to there?

It would look like this:

<img width="561" alt="screen shot 2017-03-08 at 10 37 08 am" src="https://cloud.githubusercontent.com/assets/437258/23710646/72fe9b84-03eb-11e7-83cf-d5fa4c7b31ff.png">

cc @tyxla @MichaelArestad

**Comment by beaulebens** [comment]
Note, this link current lives at the bottom of the Settings > General > Jetpack card.

**Comment by rickybanister** [comment]
Yes, I mentioned that in Slack and in the ticket above as well.

**Comment by beaulebens** [comment]
LOL I totally missed that when I read it. Carry on.

**Comment by tyxla** [comment]
This one is being addressed in #12010.
