### ISSUE TITLE
Reader: Subscription List Item formatting needs improvement at mobile width

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#11890]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/reader-subscription-list-item?debug=true (debug flag required due to https://github.com/Automattic/wp-calypso/issues/11079)
2. Resize the browser to a mobile width

#### What I expected
For everything to be lined up all pretty

#### What happened instead
<img src="https://cloud.githubusercontent.com/assets/7233112/23707873/f1897960-03e1-11e7-8759-85352d54361b.png" width=350>

It would look a lot cleaner if the time statement in the green box appeared on a separate line, and if the icons in the red box lined up with each other.

This may be due to DevDocs formatting funkiness that disappears in real life usage, but I wanted to make sure it was noticed.  cc: @samouri 

#### Browser / OS version
Seen here in OSX Chrome, but also observed in Firefox and Safari

#### Context / Source
#automated-testing #visdiff

**Comment by samouri** [comment]
@hoverduck, I intentionally landed this early without having all the UI bits perfected (especially at all widths) so that I could start using the component early.  Its not incorporated anywhere on the live site just yet.

We can use this issue though to track the improvements!
