### ISSUE TITLE
Editor: Project Types: allow editing/deleting of project types

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#11928]
There's currently only the ability to add project types but not delete or edit these.

<img width="266" alt="screen shot 2017-03-09 at 9 49 14 am" src="https://cloud.githubusercontent.com/assets/128826/23729516/042c352c-04ae-11e7-96b8-ccc9a7384e7e.png">

Raised in user chat

**Comment by timmyc** [comment]
This holds true for any custom taxonomy on CPTs.  With how the taxonomy manager is built in Site Settings, <famous last words>this should be fairly easy to implement</famous last words>
