### ISSUE TITLE
Purchases: It is possible to delete a site with active subscriptions

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#1192]
When a user deletes a site we should remove the purchases that are associated with it. Right now we prevent users from deleting a site when there are purchases on it, but there are ways to circumvent this in the API, which could leave users in a strange state.

**Comment by drewblaisdell** [comment]
Unless we plan on changing the site deletion UX, I think we should just fix the error that allows users to delete a site with active subscriptions. One reason for this is that we can't simply delete active subscriptions for domain registrations without asking the user explicitly if the want to cancel/transfer (props to @wensco for that clarification).

I'm going to update this issue to track preventing users from deleting a site with active subscriptions, which the current desired behavior in Calypso. I opened a PR for this here: #1246

**Comment by drewblaisdell** [comment]
Actually, we have an issue for that already: #1110. I'm going to close this and use the other issue to track. Please reopen if you think that we should change the way site deletion works to make it possible to delete a site with active subscriptions. :)
