### ISSUE TITLE
Editor: confusing icon in image edit menu

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#11921]
#### Steps to reproduce
1. Start editing a post
2. Add an image
3. Click the image to pop up the image edit menu
4. There's an X icon - click it

#### What I expected

Closes the menu

#### What happened instead

Deletes the image

#### Browser / OS version

All

#### Screenshot / Video

<img width="795" alt="close-or-delete" src="https://cloud.githubusercontent.com/assets/51896/23724688/8148de54-0402-11e7-902a-7b8e3475700c.png">

#### Context / Source

I think this icon should be a trash can instead of an X, which I expected to close the menu (or which is, at best, ambiguous)

**Comment by drw158** [comment]
I agree

**Comment by lancewillett** [comment]
Thanks for the report — Delta team is working on a new version of this image editing toolbar. Coming soon!
