### ISSUE TITLE
Plugin installation doesn't work in IE Edge

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/wp-calypso#11935]
#### Steps to reproduce
Try to install a new plugin onto a site through Calypso whilst using IE Edge

#### What I expected
To be able to install that plugin

#### What happened instead
![plugin-with-highlight](https://cloud.githubusercontent.com/assets/574752/23736234/332cd946-0448-11e7-80e3-406cf7a5634f.PNG)
![pushpress-wtf](https://cloud.githubusercontent.com/assets/574752/23736235/3340567e-0448-11e7-87e6-746b2e89789c.gif)

#### Browser / OS version
Windows 10, IE Edge  (Works fine in IE 11)

#### Context / Source
#manual-testing

**Comment by georgestephanis** [comment]
(technically it's Edge browser, not IE Edge.  It's the successor to IE, not some nightly release version)
