### ISSUE TITLE
Combined Cards: Omit breaks in excerpts?

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11934]
Okay, so, I know that we have been over this a time or two in the refresh, but please allow me to open the can of worms one more time.

For excerpts in Combined Cards, could we omit breaks? Here's a good reason why:

<img width="840" alt="screen shot 2017-03-08 at 6 47 57 pm" src="https://cloud.githubusercontent.com/assets/24388/23733872/168d2146-0430-11e7-9cf0-a34700e839fb.png">

Since excerpts in Combined Cards only have one line, if the first line is one word, the excerpt is pointless.

Easy/hard?

cc @blowery @samouri

**Comment by blowery** [comment]
I was wondering why my floor was covered in worms.

**Comment by fraying** [comment]
@blowery Heh. Sorry about that. But ... where is this on the easy/hard scale? Days/weeks?

**Comment by samouri** [comment]
day

**Comment by fraying** [comment]
Worth doing then, IMHO. Not a blocker for launch, but worth doing.
