### ISSUE TITLE
Domain Only: Error message shown when purchasing a domain if user has credits

### ISSUE THREAD

**Issue by aidvu** [Automattic/wp-calypso#11940]
#### Steps to reproduce
1. Give user some credits
2. Starting at URL: http://calypso.localhost:3000/start/domain-first?new=random-test-domain.com
3. Just buy a domain
4. Ignore message go to checkout
5. Pay

#### What I expected
3.1 Contact information screen w/o any error messages
5.1 The transaction to go through

#### What happened instead
3.2 Error message shown, that I cannot add product of this type to cart.
5.2 Same error message returned and transaction fails

#### Screenshot / Video
![cannot add product](https://cloud.githubusercontent.com/assets/1103398/23750359/cc74b770-04cc-11e7-91c4-15cdc8c95f2c.png)

![credits errro](https://cloud.githubusercontent.com/assets/1103398/23750519/a409827e-04cd-11e7-8ec8-e874ca01aad9.png)

**Comment by umurkontaci** [comment]
Fixed by #11819 /cc @aidvu @yurynix
