### ISSUE TITLE
AT: Update eligibility screen copy

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#11946]
https://github.com/Automattic/wp-calypso/pull/11575 is now merged and we can start thinking of updating the copy of the AT Eligibility holds and the warnings (see also: https://github.com/Automattic/wp-calypso/issues/11394).

To put it in context, this is how it looks like right now:
<img width="686" alt="b4747f9e-fdcd-11e6-98e2-513a4d4077a5" src="https://cloud.githubusercontent.com/assets/2070010/23751473/7439e830-04c9-11e7-8361-fdbece837393.png">

There are three distinct parts that could use a copy update:
- The **holds** shown as banners.
- The **holds** shown as list.
- The **warnings**, only shown as list.

## Holds (banner)

See: https://github.com/Automattic/wp-calypso/blob/master/client/blocks/eligibility-warnings/index.jsx#L56-L80

The hold banners should come in two versions, one for the "install plugin" context and one for the "upload theme" one.

| Title | Description |
| --- | --- |
| Business plan required | Please upgrade to install this plugin. |
| To upload themes, upgrade to Business Plan | Unlimited themes, advanced customization, no ads, live chat support, and more! |
| Custom domain required  | Add a free custom domain to install this plugin. |
| _**[THEME VERSION MISSING]**_<br>Custom domain required | Add a free custom domain to upload this theme. | 

## Holds (list)

See: https://github.com/Automattic/wp-calypso/blob/master/client/blocks/eligibility-warnings/hold-list.jsx#L25-L84

Currently, these holds only come in a single generic version ("feature" instead of "install plugin"/"upload theme").

I've included the URLs because most of them are clearly placeholders.

There are two holds marked as "taken care by the banner".
The reason they're still here is to avoid conflicts with other people adding items to the list.
They could also be helpful for the copy they use, which is different than the one used in the banners.

| Title | Description | URL |
| --- | --- | --- |
| Installation in progress | Another installation is already in progress. | https://wordpress.com/help |
| _**[TAKEN CARE BY THE BANNER]**_<br>Business plan required | This feature is only allowed on sites with a business plan. | https://support.wordpress.com/ |
| Jetpack site | This feature is not supported on Jetpack sites. | https://wordpress.com/help |
| VIP site | This feature is not supported on VIP sites. | https://wordpress.com/help |
| Private site | This feature is not supported on private sites. | https://support.wordpress.com/ |
| Flagged site | This feature is not supported on sites that are not in good standing. | https://wordpress.com/help |
| Admin access required | Only site administrators are allowed to use this feature. | https://support.wordpress.com/user-roles/ |
| _**[TAKEN CARE BY THE BANNER]**_<br>No custom domain | Your site must use a custom domain to use this feature. | https://support.wordpress.com/register-domain/ |
| Not a custom domain owner | You must be the owner of the primary domain subscription to use this feature. | https://support.wordpress.com/domains/ |
| No WordPress.com name servers | Your custom domain must point to WordPress.com name servers. | https://support.wordpress.com/domain-helper/ |
| Primary domain not pointing to WordPress.com servers | Your primary domain must point to WordPress.com servers. | https://support.wordpress.com/domain-helper/ |
| Primary domain does not have a valid SSL certificate | You will be able to proceed once we finish setting up some security settings for the site. | https://wordpress.com/help |

## Warnings (list)

Warnings refers to widgets and plugins that won't be AT-ed.
These are generated server-side and are basically a list of:
> **Widget/Plugin name:** Widget/Plugin description.

So it's likely not worth changing, unless we want to customize every single description, but I'd say it's better to keep them as they are in order to clearly explain to the users _what_ they're going to lose (arguably more important than _why_) in the process.

## Other copy

These are other strings in the eligibility screen that might need a look.

| Text | Comment |
| --- | --- |
| This site is eligible to install plugins and upload themes. | Indicates that there aren't conflicts anymore. |
| You must resolve the errors above before proceeding. | This is placed right before "Have questions? etc.", only when there are holds. |
| If you proceed you will no longer be able to use these features. | This is placed right before "Have questions?", only when there are warnings but no holds. |
| Have questions? Please {{a}}contact support{{/a}}. | Always visible, with or without conflicts. |
| Please resolve this issue:<br>Please resolve these issues: | Header for the hold list. |
| By proceeding you'll lose %d feature:<br>By proceeding you'll lose these %d features: | Header for the warning list. |

---

Now, since I'm ESL and can't do copy if my life depended on it, I come to you for suggestions and advices.

Also, it might be worth moving the more common holds out of the list and into the banners, as I'd say they look to me more urgent and less scary at the same time.

cc @folletto @drw158 @vindl @roundhill @apeatling

**Comment by folletto** [comment]
## Holds (banner)

| Title | Description |
| --- | --- |
| To install plugins, upgrade to Business Plan | Get also unlimited themes, advanced customization, no ads, live chat support, and more! |
| To upload themes, upgrade to Business Plan | Get also unlimited themes, advanced customization, no ads, live chat support, and more! |
| Custom domain required  | To install this plugin, add a free custom domain. |
| Custom domain required | To upload themes, add a free custom domain. | 

Why these changes? I think we need to show all the benefits, not just the specific thing they are trying to do. I also tried to make clear the cause-consequence on the custom domain, but I'm ok with any consistent change there.

**Comment by folletto** [comment]
## Holds (list)

| Title | Description | URL |
| --- | --- | --- |
| Installation in progress | please wait for the other installation to complete, then try again. | https://wordpress.com/help |
| Jetpack not supported | try opening a different site. | (no button) |
| VIP site not supported | try opening a different site. | (no button) |
| Private site not supported | to resolve make your site public. | https://en.support.wordpress.com/settings/privacy-settings/ |
| Flagged site not supported | to resolve contact us to review the site standing. | https://en.support.wordpress.com/suspended-blogs/ |
| Admin access required | only site administrators are allowed to use this feature. | https://support.wordpress.com/user-roles/ |
| Not a custom domain owner | you must be the owner of the primary domain subscription to use this feature. | https://support.wordpress.com/domains/ |
| No WordPress.com name servers | to resolve use WordPress.com name servers on your custom domain. | https://support.wordpress.com/domain-helper/ |
| Primary domain not pointing to WordPress.com servers | to resolve point your primary domain to WordPress.com servers. | https://support.wordpress.com/domain-helper/ |
| Primary domain does not have a valid SSL certificate | Please try again in a few minutes: you will be able to proceed once we finish setting up some security settings. | (no button) |

What I did:

1. I tried to rephrase the first part as the problem
2. I tried to rephrase the second part as a brief explanation on how to fix it
3. I added all the support URLs I felt were a good match. Later we might want to have a few of them ad-hoc.
4. Note that given the button says "Resolve" I also removed the button in a few instances as "Resolve" would be misleading.

**Comment by folletto** [comment]
## Warnings (list)

Ok. We can review later if the need arise.

**Comment by folletto** [comment]
## Other copy

| Text | Comment |
| --- | --- |
| This site is eligible to install plugins and upload themes. | Indicates that there aren't conflicts anymore. |
| If you proceed you will no longer be able to use these features. | This is placed right before the next one ("Have questions?"), only when there are conflicts. |
| Have questions? Please {{a}}contact support{{/a}}. | Always visible, with or without conflicts. |
| Please resolve this issue:<br>Please resolve these issues: | Header for the hold list. |
| By proceeding you'll lose %d feature:<br>By proceeding you'll lose these %d features: | Header for the warning list. |

No changes here, these look good to me.

I'm not sure where the second one ("If you proceed you will...") is used... is it in place of "You must resolve the errors above before proceeding." that is missing from the list, but shown it its place only when there are no errors, just warnings?

**Comment by Copons** [comment]
@folletto You're right, I've missed one version.
I've updated the issue and this is what changed:

| Text | Comment |
| --- | --- |
| You must resolve the errors above before proceeding. | This is placed right before "Have questions? etc.", only when there are holds. |
| If you proceed you will no longer be able to use these features. | This is placed right before "Have questions?", only when there are warnings but no holds. |
| Have questions? Please {{a}}contact support{{/a}}. | Always visible, with or without conflicts. |

**Comment by folletto** [comment]
Looks good 👍

**Comment by Copons** [comment]
> Note that given the button says "Resolve" I also removed the button in a few instances as "Resolve" would be misleading.

On this note: I feel that even linking it to a support page would be misleading, wouldn't it?

For example: I try to AT a private site, and I get the "Private site not supported" hold.
I click on the Resolve button expecting to get to the page where I'll be able to change my privacy settings (`https://wordpress.com/settings/general/{siteSlug}`), but instead I'm directed to the privacy support page (https://en.support.wordpress.com/settings/privacy-settings/).

Maybe it makes more sense to have _two_ URLs, one for the Resolve button (where applicable), and one for a shiny new Help button (like the ❓ icon in the warning list)?

**Comment by apeatling** [comment]
Just hit the "resolve" button on the "Primary domain does not have a valid SSL certificate" error. It felt useless hitting that and ending up being stranded in /help. Can we instead say "please wait a few minutes for this to finish setting up"? Then just remove the button.

**Comment by apeatling** [comment]
Also, another bug is refreshing the eligibility screen results in a blank page.

**Comment by folletto** [comment]
> On this note: I feel that even linking it to a support page would be misleading, wouldn't it?

Yes and no... if it's the specific page on how to resolve it, I think it works very well. The problem now is that we have a mix of things, and I think we can't add more support pages until AT launches.

I would avoid two URLs: the user wants to FIX it. That's the only thing we need to do there 🌟 

The approach here imho is: let's replace the links with better suited ones that already exist, and once AT launches we add new support pages as necessary to be even more accurate.


> Just hit the "resolve" button on the "Primary domain does not have a valid SSL certificate" error. It felt useless hitting that and ending up being stranded in /help. Can we instead say "please wait a few minutes for this to finish setting up"? Then just remove the button.

That's exactly what I wrote above 👍 

> Also, another bug is refreshing the eligibility screen results in a blank page.

Can you please open a separate PR? This is exclusively about copy. Thanks!

**Comment by apeatling** [comment]
Opened here https://github.com/Automattic/wp-calypso/issues/12086

**Comment by drw158** [comment]
In #11394 we used more clear text in the mockups for the warnings.

![screen shot 2017-03-14 at 12 14 12 pm](https://cloud.githubusercontent.com/assets/618551/23913092/e19ed036-08af-11e7-8494-c45714158adb.png)


I think it would be worth being more direct with the warnings like, "This widget will be removed" instead of describing what the widget is. The more direct section header does help, but I still think this would be an improvement.

it would solve this issue:

> For example in the screenshot, it says that "Contact Info" is an unsupported widget, but what happens if I proceed? It doesn't say anything like "You will no longer be able to use this widget".

**Comment by Copons** [comment]
@drw158 Just for information, the warnings are handled server-side (and I can't find a shorthand to link to that part of code) so, even if it makes sense to discuss them here, they won't be changed in a Calypso PR.

**Comment by drw158** [comment]
Ok, gotcha, I have a link to that text via our p2. I'll review the other text asap!

**Comment by drw158** [comment]
## Holds (banner)

| Title | Description |
| --- | --- |
| Business plan required | Also get unlimited themes, advanced customization, no ads, live chat support, and more! |
| Business plan required | Also get unlimited themes, advanced customization, no ads, live chat support, and more! |
| Custom domain required  | To install this plugin, add a free custom domain. |
| Custom domain required | To upload themes, add a free custom domain. | 

changes:

- I think 'To install plugins, upgrade to Business Plan' is a bit too long for a title.
- I don't think plan should be capitalized.
- 'get' and 'also' are switched

**Comment by drw158** [comment]
## Holds (list)

| Title | Description | URL |
| --- | --- | --- |
| Installation in progress | please wait for the other installation to complete, then try again. | https://wordpress.com/help |
| Jetpack not supported | try using a different site. | (no button) |
| VIP site not supported | try using a different site. | (no button) |
| Private site not supported | make your site public to resolve. | https://en.support.wordpress.com/settings/privacy-settings/ |
| Flagged site not supported | contact us to review your site's standing to resolve. | https://en.support.wordpress.com/suspended-blogs/ |
| Admin access required | only site administrators are allowed to use this feature. | https://support.wordpress.com/user-roles/ |
| Not a custom domain owner | you must be the owner of the primary domain subscription to use this feature. | https://support.wordpress.com/domains/ |
| No WordPress.com name servers | use WordPress.com name servers on your custom domain to resolve. | https://support.wordpress.com/domain-helper/ |
| Primary domain not pointing to WordPress.com servers | point your primary domain to WordPress.com servers to resolve. | https://support.wordpress.com/domain-helper/ |
| Primary domain doesn't have a valid SSL certificate | please try again in a few minutes: you will be able to proceed once we finish setting up your security settings. | (no button) |

Changes:

- minor grammatical tweaks
- moved "to resolve" to the end of the sentence

**Comment by markarms** [comment]
## Holds (banner)

| Title | Description |
| --- | --- |
| Business plan required | Also get unlimited themes, advanced customization, no ads, live chat support, and more. |
| Business plan required | Also get unlimited themes, advanced customization, no ads, live chat support, and more. |
| Custom domain required  | To install this plugin, add a free custom domain. |
| Custom domain required | To upload themes, add a free custom domain. | 

Changes: 

- Removed exclamation marks. I think we want to go more understated here.
