### ISSUE TITLE
NUX: After mapping a domain the free plan shouldn't be selectable

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#11948]
When I sign up to create new site with a mapped domain,

![screen shot 2017-03-09 at 12 30 18](https://cloud.githubusercontent.com/assets/203408/23748545/5554e91a-04c4-11e7-83e8-fe6116ccd4eb.png)

the plans page allows the selection of the Free plan but domain mapping isn't available on that plan, so it shouldn't be a choice.

![screen shot 2017-03-09 at 11 05 36](https://cloud.githubusercontent.com/assets/203408/23745460/95a87420-04b8-11e7-8eba-3f4de9983ee0.png)

When I continue with the Free plan I am asked to purchase a Premium plan after signing up which matches the behavior when mapping a domain from a free account, so that's fine.

refs #11937

**Comment by alisterscott** [comment]
Confirmed this is still an issue:

<img width="1150" alt="screen shot 2017-07-18 at 12 40 53 pm" src="https://user-images.githubusercontent.com/128826/28298390-5c63bbb0-6bb6-11e7-831c-ca9fd46344e1.png">

**Comment by ramonjd** [comment]
Fixed in #22430
