### ISSUE TITLE
Refactor hardcoded product TLDs

### ISSUE THREAD

**Issue by yurynix** [Automattic/wp-calypso#11950]
In #11530 we introduced a [products domain list](https://github.com/Automattic/wp-calypso/pull/11530/files#diff-f8ac2dcf393a745e9b7a19af6848b427R20) that contains TLDs, they are hardcoded,
So when we'd add new tld on the server, we'd have to come to that code an

It'll be good refactoring the hardcoded list to be loaded from the server,
and for the domain product (product that has `is_domain_registration: true`), the product object will contain a `tlds` array.
as discussed here https://github.com/Automattic/wp-calypso/pull/11530#discussion_r104321793

**Comment by klimeryk** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/16428 🎉
