### ISSUE TITLE
Recommended Posts: Design Tweak for Line Alignment

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11956]
There are cases where we show a recommendation with an image beside one without an image. In these cases, the text alignment is off like so:

<img width="800" alt="screen shot 2017-03-09 at 10 09 06 am" src="https://cloud.githubusercontent.com/assets/24388/23763924/751bb044-04b0-11e7-8144-c0262ce6abe0.png">

I propose making the images in recommendations 10px taller. This should result in the text aligning like so:

<img width="798" alt="screen shot 2017-03-09 at 10 10 53 am" src="https://cloud.githubusercontent.com/assets/24388/23763999/b99c7820-04b0-11e7-828a-8ad0ad5bf7d2.png">

Note that I have also scooted the image up by a few pixels, so the top of the image is aligned with the top of the headline in the other card. That's the change requested in #11356, so it might be good to attack both these issues in one PR.

**Comment by fraying** [comment]
This bug is back.

<img width="831" alt="screen shot 2017-04-10 at 3 07 44 pm" src="https://cloud.githubusercontent.com/assets/24388/24884852/3febf8ac-1e00-11e7-8c58-12f5364d2b1f.png">

@jancavan could you look into it?

**Comment by jancavan** [comment]
@fraying Yes, I'll look into it.

**Comment by fraying** [comment]
Thanks, @jancavan!

I also noticed that in the image above, the Follow link on the right is too far down. (At least, in Safari.)

<img width="824" alt="screen shot 2017-04-10 at 3 18 43 pm" src="https://cloud.githubusercontent.com/assets/24388/24885046/36bcfa00-1e01-11e7-8d6d-e91d7963dc13.png">

**Comment by fraying** [comment]
Fixed now!
