### ISSUE TITLE
Combined Cards: Site Title Inconsistent

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11962]
So here we have two posts from this site (https://wordpress.com/read/feeds/19850964) in normal Reader. Note that the site title is "UPROXX".

<img width="824" alt="screen shot 2017-03-09 at 11 52 58 am" src="https://cloud.githubusercontent.com/assets/24388/23767929/30e667e8-04bf-11e7-984d-400d6304f96a.png">

On wpcalypso, when they're combined into a Combined Card, the Site Title becomes "Real Stories – UPROXX".

<img width="835" alt="screen shot 2017-03-09 at 11 52 40 am" src="https://cloud.githubusercontent.com/assets/24388/23767987/5b644184-04bf-11e7-9a51-11a8da851aaa.png">

That's incorrect. The Site Title should match what's displayed normally: "UPROXX".

cc @bluefuton

**Comment by bluefuton** [comment]
Good spot!

`Real Stories - UPROXX` is coming off the first post. We don't have a `site` in that combined card to look up the proper site name. I think we need to try and fetch the site if we have a blog_ID on the feed object.

**Comment by fraying** [comment]
Fixed in #11968, nice work @bluefuton!
