### ISSUE TITLE
Combined Cards: Include Blavatar

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11971]
In Combined Cards, in the card header, if the site has a blavatar or site icon, it should be displayed. (Went with gravatar here because the posts could be from different authors.) Like so:

<img width="187" alt="screen shot 2017-03-08 at 2 23 37 pm" src="https://cloud.githubusercontent.com/assets/24388/23726899/d69e940e-040a-11e7-8f06-af64e0236366.png">

**Comment by bluefuton** [comment]
This should have been fixed by https://github.com/Automattic/wp-calypso/pull/11953, which displays a feed icon if we have one available 👍 

I'm not seeing a site icon for Gizmodo, but there doesn't seem to be one elsewhere in their feed either:

https://wpcalypso.wordpress.com/read/feeds/10080096

**Comment by fraying** [comment]
Great! Closing this.
