### ISSUE TITLE
Combined Cards: Add Timespan

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#11973]
In Combined Cards, in the header, the timespan of the posts in the card should be listed after "X posts." As in: "X posts in X minutes" (or hours or days). Like so:

<img width="187" alt="screen shot 2017-03-08 at 2 23 37 pm" src="https://cloud.githubusercontent.com/assets/24388/23726899/d69e940e-040a-11e7-8f06-af64e0236366.png">

This helps explain to the user why these posts have been grouped together.

**Comment by blowery** [comment]
What's the plan if they're all from 1 minute in particular?

**Comment by fraying** [comment]
"X posts in 1 minute"

**Comment by fraying** [comment]
After testing this out we decided it was more confusing than helpful.
