### ISSUE TITLE
Signup: Strange behavior in the post-domain-first flow

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#11987]
~~It might be specific to #11876 only. I'm still trying to confirm it.~~ It happens also on master.

I'm encountering strange behavior in the flow on a rare occasion. I manage to record a screencast to present what happens:

![create-site-from-domain-only](https://cloud.githubusercontent.com/assets/699132/23744866/3ad186f6-04b6-11e7-95e6-723c55947e52.gif)

I see the following error message on the console:
> Current step is invalid, cannot redirect to it. 

![screen shot 2017-03-09 at 10 51 37](https://cloud.githubusercontent.com/assets/699132/23744901/656296ee-04b6-11e7-8902-479031a0b83b.png)

### Steps to reproduce
1. Complete signup through /start/domain-first?new=DOMAIN where DOMAIN is a valid, available domain name like example-one-two-three.live.
2. Click on `My Sites` button.
3. Click on `Create Site` button.
4. Pick a theme.
5. Pick a plan.
6. If you see checkout page remove plan from the cart.
7. Try to repeat steps 3-6 until you see error on your console.

**Comment by aidvu** [comment]
@gziolo Cannot reproduce this one anymore. Mind giving it one more run?

**Comment by gziolo** [comment]
We got rid of Sites List recently so that might be no longer relevant. If you can't reproduce than feel free to close it :)

**Comment by aidvu** [comment]
My thoughts exactly. :) :+1:
