### ISSUE TITLE
Editor: Various improvements to the new editor

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-calypso#11996]
A visual refresh to the post/page editor was just merged:

![new-sidebar-open](https://cloud.githubusercontent.com/assets/1204802/23794832/8c0b5524-0592-11e7-87ed-9be29d36fb01.png)

The new editor allows the sidebar to be toggled, and has permanently visible preview and publish buttons. 

Some smallish issues have popped up, which we should address. Please add to this list if you find any:

- [ ] labels on preview and post settings disappear between the 660 and 960 breakpoint, even though they don't need to. We should consdier a new 720 breakpoint, and hide them under that.
- [x] horizontal scrollbar appears in sidebar when all metaboxes are open, on the between 660 and 960 breakpoints
- [x] word count doesn't have a correct right margin between the 660 and 960 breakpoint
- [x] bottom left status indicator gets cut off sometimes with long documents
- [x] between the 660 and 960 breakpoints, with the sidebar closed, the TinyMCE toolbar lacks left and right borders
- [x] prior to adding content into a draft the preview button is disabled, but it's still clickable and opens a new tab with a post-editor
- [x] fix missing RTL button in editor, tracked separately here https://github.com/Automattic/wp-calypso/issues/12061

See also https://github.com/Automattic/wp-calypso/pull/11536

**Comment by jasmussen** [comment]
We should also make improvements to the save indicator. Specifically it can be confusing that after publish, the "Save" button stops appearing, even though in the background, the autosave revision system still works. 

One solution would be to decide whether we trust the autosave or not, and if we do, remove the Save button entirely. Then it's simply an indicator.

**Comment by Copons** [comment]
A couple of other things you might want to add to the checklist:

- Between ~720 and ~920px of width, the toolbar in both modes loses its left and right borders. 
<img width="722" alt="screen shot 2017-03-10 at 13 01 31" src="https://cloud.githubusercontent.com/assets/2070010/23796241/db5faa2c-0591-11e7-86a9-9a2139069b0d.png">
<img width="719" alt="screen shot 2017-03-10 at 13 01 38" src="https://cloud.githubusercontent.com/assets/2070010/23796242/db61c5a0-0591-11e7-9006-9cd6896a4d9a.png">

- The "published" indicator, while covered by TinyMCE in Visual mode, in HTML mode does not have a background (like the word count on the opposite side; see second screen), and it looks weird with the post content overlapping it.
<img width="219" alt="screen shot 2017-03-10 at 13 02 05" src="https://cloud.githubusercontent.com/assets/2070010/23796270/f80d4044-0591-11e7-9872-2007bc42cb92.png">
<img width="100" alt="screen shot 2017-03-10 at 13 04 08" src="https://cloud.githubusercontent.com/assets/2070010/23796282/1237f860-0592-11e7-8898-1527b3e4671c.png">

**Comment by jasmussen** [comment]
<img width="360" alt="screen_shot_2017-03-10_at_8 22 00_am_720" src="https://cloud.githubusercontent.com/assets/1204802/23797006/1105d3ac-059e-11e7-846d-5cf4186bb44c.png">

Only does this in the HTML tab.

**Comment by Copons** [comment]
> Only does this in the HTML tab.

Damn!
Coming up with a fix right now.

**Comment by rralian** [comment]
Added an issue to the list about the preview button behavior on an empty draft.

**Comment by jasmussen** [comment]
We should think about, perhaps not as part of this ticket, adding a confirm on the publish dialog. The behavior is technically unchanged since the old editor, but there are some ideas here worth maybe exploring:
https://github.com/Automattic/wp-calypso/pull/11536#issuecomment-283608918

![01427f64-ff37-11e6-8392-5ba1b8259e96](https://cloud.githubusercontent.com/assets/1204802/23863776/ea65e8a2-0810-11e7-8439-be7cd2e20258.png)

**Comment by jasmussen** [comment]
A couple of things to look into also:

- https://en.blog.wordpress.com/2017/03/13/a-distraction-free-writing-space-at-wordpress-com/#comment-232843
- https://en.blog.wordpress.com/2017/03/13/a-distraction-free-writing-space-at-wordpress-com/#comment-232834
- https://en.blog.wordpress.com/2017/03/13/a-distraction-free-writing-space-at-wordpress-com/#comment-232846

**Comment by jasmussen** [comment]
From Mark, and this isn't a regression in the new editor, but posting here regardless as we should improve it:

> it's literally impossible to cut and paste text into [captions] in the calypso editor. this has been a bug forever

Here's a video demonstrating the problem https://cloudup.com/cyEsK88iYGU

**Comment by jasmussen** [comment]
Reporting here, even though it's not a regression from the new editor. Don't want it to fall off the map. 

Bug: The visual editor doesn't stick the scrollbar to the bottom when you press enter, only when you type:

Video: https://cloudup.com/cnHrvlx-_4P

**Comment by jasmussen** [comment]
Another one that is not a regression in the new editor. 

Bug: If you write a long long text, then transform one of the paragraphs to a `pre` preformatted tag, you can no longer scroll to the bottom by selecting text:

![pre-selection scrolling](https://cloud.githubusercontent.com/assets/1204802/23911334/c8fa0168-08dc-11e7-86df-46131a9e6f70.gif)

**Comment by drw158** [comment]
I think the pre loader could be added to this list. Currently, the loader is using the old design.

**Comment by lancewillett** [comment]
For the remaining items — need more eyes to test, or want to split into new issues if not urgent to fix?

**Comment by jasmussen** [comment]
Thanks for chiming in @lancewillett! Turns out two of the remaining issues have since been fixed. 

The remaining label is more of a discussion point:

> labels on preview and post settings disappear between the 660 and 960 breakpoint, even though they don't need to. We should consider a new 720 breakpoint, and hide them under that.

I feel like it's not worth keeping this ticket open for just that, so I'm going to close it. We will be revisiting the editor regardless, and in particular the whole area around preview | post settings | Publish (see <a href="https://cloudup.com/cJH5dD8s1ZA">mockups</a> that are likely to inform this), and so the issue is likely to become vestigial or change.
