### ISSUE TITLE
Domain Search: Fix copy difficult to read because of background images

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#11999]
We should make sure that the text displayed on the new [`Domain Search` page](https://wordpress.com/domains) is easy to read: right now it is difficult to distinguish the text from some parts of the background images:

<img width="862" alt="screenshot" src="https://cloud.githubusercontent.com/assets/594356/23797351/b2043fae-059f-11e7-8814-e6085807c0fe.png">

#### Steps to reproduce
1. Open the [`Domain Search` page](https://wordpress.com/domains) in an incognito window
2. Scroll down to the section mentioned in the screenshot above

**Comment by fabianapsimoes** [comment]
Moved to T493-code.
