### ISSUE TITLE
Editor: Disabled preview button still handles clicks

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#11992]
After merging #11536, I noticed this bug we have.

#### Steps to reproduce
1. Starting at URL: /post
2. Don't type anything and notice how the "Preview" button is disabled
3. Click the disabled button

#### What I expected

I expected nothing to happen. Just like when I click the disabled publish button.

#### What happened instead

Preview opened and has on content. I don't mean empty post, I literally mean `about:blank` is loaded in the iframe.

#### Browser / OS version

macOS Chrome

#### Screenshot / Video

<img width="401" alt="screen shot 2017-03-10 at 12 05 09" src="https://cloud.githubusercontent.com/assets/156676/23793158/369187a6-058a-11e7-872d-bf96951c72b7.png">

<img width="911" alt="screen shot 2017-03-10 at 12 08 12" src="https://cloud.githubusercontent.com/assets/156676/23793181/42d69510-058a-11e7-8db7-5a207554da60.png">

#### Context / Source

#dogfooding

**Comment by mtias** [comment]
I noticed this as well, we should fix it.
