### ISSUE TITLE
Pages: allow setting a page as the front page from the popup menu

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#12]
From the popup menu on the list of pages, allow an option to set a selected page as the front page.

![screen shot 2016-06-03 at 9 16 53 am](https://cloud.githubusercontent.com/assets/128826/15764138/f5605b86-296b-11e6-855a-ac9a41987b2e.png)

**Comment by alisterscott** [comment]
Added a screenshot for context

**Comment by lamosty** [comment]
Note to myself (or anybody who grabs this before me): there is a setting in state at `sites.items.[siteId].options.page_on_front` which equals to the front page's `id`. However, you also need to set `show_on_front` at the same place to `"page"` for it to work (probably, not tested yet).

**Comment by lancewillett** [comment]
Internal discussion to get this going again: p2-p3Ex-1wx

**Comment by mattsherman** [comment]
This has been implemented (`development` env only current, while we work on related features in the epic). See https://github.com/Automattic/wp-calypso/pull/8617.

**Comment by lancewillett** [comment]
Re-tested this today, works great in wpcalypso. Let's push it out to everyone. 🚢

**Comment by mattsherman** [comment]
This has been in production since November 2016 (https://github.com/Automattic/wp-calypso/pull/9477), so this issue should have been closed then. Closing it now.
