### ISSUE TITLE
Domain Search: Fix domain suggestions still displayed when input field is emptied

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#12002]
We should collapse the list of domain suggestions on the new [`Domain Search` page](https://wordpress.com/domains) whenever the user clears the search input field:

<img width="586" alt="screenshot" src="https://cloud.githubusercontent.com/assets/594356/23797668/3c5815f8-05a1-11e7-9fcf-414224df56be.png">

#### Steps to reproduce
1. Open the [`Domain Search` page](https://wordpress.com/domains) in an incognito window
2. Enter some search terms
3. Use for example <kbd>backspace</kbd> to clear the search field
4. Assert that you still see a list of domain suggestions

**Comment by fabianapsimoes** [comment]
Moved to #27-a8c-domain-search.
