### ISSUE TITLE
Jetpack: Should we remove the installation section for installed plugins?

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#12008]
We show installation instructions for currently-installed plugins. Should we remove that? The question came up around Automated Transfer, but it's how all plugins are displayed in Calypso for Jetpack sites. So I think if we remove it, we should do so for all installed plugins. I don't feel strongly about this one personally. /cc @rickybanister @beaulebens 

![plugin installation](https://cloudup.com/cPkmnsqEG6L+)

**Comment by rickybanister** [comment]
Good catch—I think a good short-term solution is simply to provide a success notice within the installation card that says 'this plugin is installed' or similar. I think there's a larger debate to be had about how the design might want to be a slightly larger departure from the 'pre-installed' plugin view once a plugin has been installed—for instance once we calypso-ify plugins, would we provide space here for their settings interfaces and so on.

**Comment by johnHackworth** [comment]
I think the installation section, sometimes, also includes info that is not just "how to install" (things like login to your account in whatever service it provides, etc). For example, akismet instructs you to enter your key:

![image](https://cloud.githubusercontent.com/assets/1554855/24801060/f542e478-1ba2-11e7-82cc-0dff8542b7a9.png)

**Comment by johnHackworth** [comment]
Or this other one from us:

![image](https://cloud.githubusercontent.com/assets/1554855/24801085/0bd53128-1ba3-11e7-87fb-fbb2258e5b15.png)

**Comment by rickybanister** [comment]
@rralian I think it's safe to go ahead and suppress the installation tab for installed plugins.
