### ISSUE TITLE
Domain Search: Fix last keyword suggestion not correctly faded

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#12003]
We should fix a display issue with the list of ideas displayed below the search input field on the new [`Domain Search` page](https://wordpress.com/domains). Depending on the width of the viewport and keywords displayed it is indeed possible to notice this tiny glitch:

<img width="487" alt="screenshot" src="https://cloud.githubusercontent.com/assets/594356/23797857/237901f4-05a2-11e7-94ce-952fa3fbb31e.png">

#### Steps to reproduce
1. Open the [`Domain Search` page](https://wordpress.com/domains) in an incognito window
2. Enter some search terms
3. Resize the width of your browser

#### Browser / OS version

Chrome latest on Windows 10 Pro.

**Comment by stephanethomas** [comment]
I have the feeling this bug happens around breakpoints.

**Comment by fabianapsimoes** [comment]
Moved to #26-a8c-domain-search.
