### ISSUE TITLE
Jetpack: infinite loop while trying to connect to site that no longer exists

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#12016]
Calypso goes into an infinite loop trying to connect to an non-existing site when “Blog Posts” is clicked on the sidebar. It either shows thousands of error notices, or freezes up the tab. Using Chrome.

<img width="1577" alt="screen shot 2017-03-10 at 15 13 19" src="https://cloud.githubusercontent.com/assets/390760/23804298/4b7aebfe-05b1-11e7-8f02-4d329d5cf046.png">

![pasted image at 2017_03_10 16_26](https://cloud.githubusercontent.com/assets/390760/23804428/be8ef2f2-05b1-11e7-8084-c3f86a83839a.png)

#### Steps to reproduce
1. Open https://wordpress.com/stats/day/labrabbit.org
2. Click Blog Posts

Related issue that tries to solve this higher up in the chain: https://github.com/Automattic/wp-calypso/issues/11861

**Comment by johnHackworth** [comment]
I'm not totally sure if I follow how to reproduce this ... When you say "a site that no longer exists" you mean one that isn't connected anymore and calypso is not aware of it? Or a site that is unreachable but still connected?

**Comment by keoshi** [comment]
In this case specifically, a site that was connected through JP, but has since moved away from WP altogether without a proper disconnection. Might be applicable in other cases too.
