### ISSUE TITLE
New Write: Preview: SEO: Reader preview needs updating

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12024]
In the new writing experience, when previewing SEO for Reader, it's currently busted.

<img width="914" alt="screen shot 2017-03-10 at 11 04 45 am" src="https://cloud.githubusercontent.com/assets/24388/23810042/c995ae98-0584-11e7-8906-89521a576a6c.png">

Looks like it uses our old class names and structure. It should match current Reader styles, like this:

![seo-fixed](https://cloud.githubusercontent.com/assets/24388/23810062/d9d7a248-0584-11e7-9cb3-37739bfafff7.png)

This might help? https://github.com/Automattic/wp-calypso/blob/master/client/blocks/reader-post-card/index.jsx

ccing @blowery & @bluefuton for Reader context
ccing @roundhill & @dmsnell because I think they're working on this?

**Comment by roundhill** [comment]
Ah, yes I thought this would happen someday. I think we were waiting on `reader-post-card` to be created but forgot to check back on it.

**Comment by dmsnell** [comment]
@gwwar did the updates in related work and mentioned that she planned on back-porting to here

**Comment by roundhill** [comment]
Thanks, so far it doesn't seem _too bad_ to port this over to use the `reader-post-card`. It needs a few properties added to the post object to get it looking right.

**Comment by gwwar** [comment]
> did the updates in related work and mentioned that she planned on back-porting to here

Oh Stark is currently working on social media shares, but not any reader views. I think the glitch here is that the excerpt isn't stripping markup

**Comment by fraying** [comment]
@blowery - can you offer any assistance here?

**Comment by roundhill** [comment]
I started fixing this yesterday, I think it's looking pretty good. Will start a PR soon: https://github.com/Automattic/wp-calypso/tree/fix/12024-seo-reader-preview
