### ISSUE TITLE
Improve user experience on Menus

### ISSUE THREAD

**Issue by rizqinizamil** [Automattic/wp-calypso#12035]
Hi there,

For users who have experience using WordPress, they will know how to create menu (with/without sub-menu) on their website. But for new users I'm not sure they will know how to do it, especially how to create sub-menu. Thus I have suggestion to improve user experience on it, by changing cursor type (`cursor: move`) and add another interaction while cursor over menu item, eg: add border or change background color.

![Image of Menus](https://cldup.com/hE41sKKS-O.jpeg)

What do you think guys?

Thank you,
Rizqi

**Comment by mcsf** [comment]
Hi, Rizqi, thanks for your suggestion. Indeed, Calypso Menus has some known UX problems and would need some work. However, per #4610, the plan is to remove Calypso's native Menus section in favor of the WordPress Customizer's menus tool. Thus Calypso Menus will not be subject to further improvements.

**Comment by rizqinizamil** [comment]
Noted. I'm sorry I didn't know that the thread is exist.

**Comment by mcsf** [comment]
Not at all; you had no way of knowing. :)
