### ISSUE TITLE
Plan Storage: Consider making the whole component clickable

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#12044]
Raised by @folletto in #11822 

> I'd leave the final decision to @iamtakashi, but I think the whole area should be clickable, not just "Upgrade", and it should also have a hover effect to signify it's all clickable (i.e. the whole block gets a slight gray background and the text gets colored).

![image](https://cloud.githubusercontent.com/assets/908665/23836594/baaef778-0772-11e7-9d02-a3690e1457aa.png)

I don't strongly feel this is necessary because the "upgrade" link is clearly a link, but I can understand that a larger clickable area is helpful and won't harm anything.

**Comment by folletto** [comment]
I added a priority low here. ;)
