### ISSUE TITLE
Media: Remove "<- Media Library" link from image detail modal.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#12043]
**Update**: This is the final design.

Image detail modal in the section:

![image](https://cloud.githubusercontent.com/assets/908665/23994043/00bf4dce-0a3b-11e7-85e3-19585d85f642.png)

Image detail modal in the editor: (Note: "Back" Button that takes you back to the previous modal)

![image](https://cloud.githubusercontent.com/assets/908665/23994106/47ead51a-0a3b-11e7-982b-b66471fe74f2.png)

---

Previously discussed in #11133, #11024, and #11822. The "back to Media Library" link feels redundant and it's safe to remove.

![image](https://cloud.githubusercontent.com/assets/908665/23836559/212c45b0-0772-11e7-95e2-e0752cfe01bd.png)

From @folletto in #11822

> I'd also add a "Cancel" / "Close" button. I was on the edge when we discussed this with @iamtakashi, but now seeing it live, the top arrow to go back doesn't seem very intuitive, I'd even remove it leaving just the buttons. This for two reasons:

> 1. The primary button, and the attention, is down there already.
> 2. (minor) Follows our dialog patterns.

The term "Cancel" has an issue because it doesn't actually cancel your changes in the auto-saved image details (ex.description etc.)

"Close" button feels redundant because the primary "Done" button does the exactly the same.

My vote is just removing the link and no additional button.

**Comment by iamtakashi** [comment]
We're moving the title to field section in #12033, and when we remove the back link, this is how the modal going to look.

![image](https://cloud.githubusercontent.com/assets/908665/23837477/f1f5bbd2-0780-11e7-9332-71d0b9eed532.png)

**Comment by folletto** [comment]
> My vote is just removing the link and no additional button.

Makes sense, thanks for the clear outline and analysis. 👍

**Comment by iamtakashi** [comment]
@folletto, just to make sure, we're removing the link only from the modal in the media section, right? Because the one in the editor still makes sense to be there.

**Comment by folletto** [comment]
> just to make sure, we're removing the link only from the modal in the media section, right? 
> Because the one in the editor still makes sense to be there.

The comment was related only to that, yes.

However after your comment I checked, and I'm not sure it's needed: if we have a "Cancel" button in the media modal, then it could just go back instead of closing, removing the need of a "Back" button in a different location...

But maybe I'm missing some piece...

**Comment by iamtakashi** [comment]
> [...] if we have a "Cancel" button in the media modal, then it could just go back instead of closing [...]

Make sense. If we're changing the behaviour of the cancel button _in the image detail modal_ , then we can remove the back link safely. I think I prefer that. Because the context for the cancel button there is "Cancel to edit the images".

**Comment by iamtakashi** [comment]
![image](https://cloud.githubusercontent.com/assets/908665/23912498/b4aeffba-08d7-11e7-8578-e661cfc89979.png)

Actually... I was looking at the image detail modal in the editor once again, and I started to feel the "cancel" button has the same issue as what I said before:

> The term "Cancel" has an issue because it doesn't actually cancel your changes in the auto-saved image details (ex.description etc.)

The tricky thing is that the context for the "cancel" button can actually have two different things.
1. Cancel inserting — because it's next to "insert" button.
2. Cancel editing — because you're here by clicking "edit" button.

Currently the button works as for the context 1, but it does not cancel the details you've edited. This was the reason we removed it from the modal in Media section.

![image](https://cloud.githubusercontent.com/assets/908665/23912886/1ca8e2f6-08d9-11e7-9a42-7bcda9d0eb81.png)

The simplest way would be to change "cancel" to "close" and keep the back link, but I'm not sure if I like it very much because we want to remove the back link if possible (to be consistent to the modal in the section).

**Comment by folletto** [comment]
I think what you highlight there shows a UI ambiguity that translates to user confusion, so if we solve this with a button combination, we would solve it for users too. 

What would be the problem in removing the `←` button, and just having an extra "Close" or "Back" button near the primary blue button?

**Comment by iamtakashi** [comment]
Thanks @folletto.

> I think what you highlight there shows a UI ambiguity that translates to user confusion, so if we solve this with a button combination, we would solve it for users too.

Exactly. That's what I'd like to do.

> What would be the problem in removing the ← button, and just having an extra "Close" or "Back" button near the primary blue button?

There isn't any problem with the method (buttons only) at all. Silly me, I think I've misunderstood your suggestion. I was so stack with the idea — we need to provide both ways to "Back (to media library)" and "Close (the modal)".

But I now think it's going to be just fine to have only one button that takes you back to the media modal. At least desktop users can close the modal(s) entirely by clicking outside of it. And I think I'm leaning towards "Back" rather than "Close".

**Comment by folletto** [comment]
> But I now think it's going to be just fine to have only one button that takes you back to the media modal. At least desktop users can close the modal(s) entirely by clicking outside of it. And I think I'm leaning towards "Back" rather than "Close".

👍  👍
