### ISSUE TITLE
Scheduled date shown in post list is not useful

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#12052]
If you schedule posts over a month in the future the posts list shows the date as something like 'in a month'. This isn't useful.

<img width="163" alt="schedule_dates" src="https://cloud.githubusercontent.com/assets/1277682/23849855/042428da-07d5-11e7-9512-7ff7486f600d.png">

#### What I expected

When you schedule something you schedule it on an exact date. I would like to know this exact date when looking through my list of posts. If I have 10 scheduled posts for next month then 'in a month' serves no purpose. To work out when the post is going to be published I have to edit the post and click on the calendar button, which isn't optimal.

Regarding scheduled dates shown less than a month in the future. I'm somewhat ambivalent about it showing 'in 22 days' - it's more useful than 'in a month', but it requires me to mentally calculate the publish date. It seems better just to show the date in all cases.

**Comment by alisterscott** [comment]
Confirmed this is still an issue:

<img width="286" alt="screen shot 2017-12-21 at 9 29 08 am" src="https://user-images.githubusercontent.com/128826/34233490-756d46a8-e631-11e7-8445-7bfa50d41aca.png">

**Comment by mattsherman** [comment]
@Automattic/tanooki will look into

**Comment by kathrynwp** [comment]
A WordPress.com also mentioned that the relative dates for scheduled posts is not useful. 

> The old interface used to let me see which days I had posts assigned.  Now it just says in XX days....   That's a very non visual way to look at it

15511167-hc

**Comment by KokkieH** [comment]
We've had a complaint about this via [Twitter](https://twitter.com/PagePlacePlate/status/1221549923595902981)

**Comment by Aurorum** [comment]
PR in #40779 for this issue. :)

<img width="579" alt="Screenshot 2020-04-03 at 21 43 37" src="https://user-images.githubusercontent.com/43215253/78403424-3a5f1000-75f4-11ea-84ef-40b425bd0e23.png">
