### ISSUE TITLE
Reader: Edit Following: add box is confusing

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#12051]
When [managing your followed sites](https://wordpress.com/following/edit) you are presented with this view. What seems to be the search box on the top is in fact not a search box. 

![screen shot 2017-03-13 at 09 09 20](https://cloud.githubusercontent.com/assets/203408/23847376/509be5c0-07d2-11e7-9839-124da94a4e5a.png)

With many sites followed I often fall for the trap that I enter a search term for my already followed pages but nothing happens. Only then I realize I need to use to magnifying glass on the far right.

Can't we combine these functions and have the box on top be an instant search box?

![screen shot 2017-03-13 at 09 44 32](https://cloud.githubusercontent.com/assets/203408/23847379/54207bfc-07d2-11e7-934d-75034e500cb7.png)

Instead of having the result of the adding be attached to the textfield, it could be part of the search results from where you'd be able to add a site just as you are now.

**Comment by blowery** [comment]
Thanks for the report @akirk. There's some ongoing work in #11549 to address just this issue. Would the proposed solution there work for you?

**Comment by akirk** [comment]
Thanks for the pointer. It actually doesn't because it just expands the area the textbox + results occupies. My focus going to the page is to enable/disable following settings for sites I follow. I might be in the minority here so I guess finding new sites trumps adjusting sites I already follow :(

**Comment by blowery** [comment]
cc @fraying

**Comment by fraying** [comment]
Thanks for the feedback. This page is currently undergoing a big overhaul and we're going to take this feedback into consideration. Stay tuned.
