### ISSUE TITLE
Domain Search: doesn't work for uncommon TLDs?

### ISSUE THREAD

**Issue by ChrisHardie** [Automattic/wp-calypso#12062]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/
2. Enter a domain with an uncommon TLD (e.g. bobbyjojo1234.army or ma.tt)
3. See results that don't indicate whether or not the domain name is actually available

#### What I expected

If the TLD is supported, information about whether or not the domain can be registered.
If the TLD isn't supported, a notice saying that and providing further instructions.

#### What happened instead

There's no information about the TLD or the domain being searched. It could give the appearance that the search is broken.

#### Browser / OS version

Chrome 56.0.2924.87 on OS X 10.11.6.

**Comment by fabianapsimoes** [comment]
Moved to #39-gh-a8c-domain-search
