### ISSUE TITLE
Clicking bell in top right of WordPress.com does nothing

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#12065]
#### Steps to reproduce
1. Starting at URL: WordPress.com
2. Click bell in top right

#### What I expected

Notifications panel to open

#### What happened instead

Nothing happened.  On page load there were some JS errors

<img width="537" alt="screen shot 2017-03-13 at 12 56 17 pm" src="https://cloud.githubusercontent.com/assets/6817400/23865633/ae90d5f4-07ec-11e7-8ae1-4abd7ef5cdb1.png">

#### Browser / OS version

Firefox, Chrome, and Chrome Canary

**Comment by lancewillett** [comment]
I think this was a temporary outage. Fixed now.
