### ISSUE TITLE
Text Direction button (RTL LTR) missing from editor

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#12061]
A Text Direction button is not displayed in the Calypso editor, for users with a RTL UI language.

#### Steps to reproduce

Go to https://wordpress.com/me/account and change the interface language to Hebrew.

1. Go to Posts and click Add
2. In Visual mode there is no Text Direction button

![new-editor-dir](https://cloud.githubusercontent.com/assets/11627765/23860875/225e0fac-0800-11e7-98ab-7859c00f7a35.jpg)

1. Go to the WP Admin dashboard
2. Click Posts and Add New
3. In Visual mode the Text Direction button is visible

![wp-admin-dir](https://cloud.githubusercontent.com/assets/11627765/23860924/5383dfa8-0800-11e7-9a05-cb616f77ecc8.jpg)

#### Context / Source

#user-report #manual-testing

**Comment by jasmussen** [comment]
Screenshot of Calypso editor missing the button:

![screen shot 2017-03-22 at 11 19 49](https://cloud.githubusercontent.com/assets/1204802/24193213/c84e1f04-0ef1-11e7-9ea9-514e7f36d232.png)
