### ISSUE TITLE
Domain Search: Keyword suggestions faded out without scroll

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12066]
When searching, when there are more keyword suggestions than there is room for there is a fade to indicate such but their isn't a way to scroll to view more.

![image](https://cloud.githubusercontent.com/assets/12596797/23866877/944b0864-07f0-11e7-85d9-91fccc845a72.png)

Except on small screens I don't think we even need to fade, just show the number of suggestions that fit.

**Comment by mikeshelton1503** [comment]
Duplicate https://github.com/Automattic/a8c-domain-search/issues/26

**Comment by mikeshelton1503** [comment]
Related to https://github.com/Automattic/a8c-domain-search/issues/26

**Comment by fabianapsimoes** [comment]
Moved to #40-gh-a8c-domain-search.
