### ISSUE TITLE
Landing Page: Punctuation inconsistencies

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12071]
On the /domains landing page, punctuation is is used inconsistently. All headlines should not have punctuation.

Two instances that need to fixed:

![image](https://cloud.githubusercontent.com/assets/12596797/23868732/e715c29a-07f6-11e7-979d-39cfa73ec3ef.png)

![image](https://cloud.githubusercontent.com/assets/12596797/23868736/ed6cdcfa-07f6-11e7-8569-5e07aeb439ae.png)

**Comment by fabianapsimoes** [comment]
Moved to T499-code.
