### ISSUE TITLE
Reader: in Manage Followed Sites, search should indicate if all subscriptions haven't loaded yet

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#1207]
When a user has a large number of subscriptions, it can take a little while to load them all in on Manage Followed Sites. If the user performs a search whilst subscriptions are still being loaded, they can get incomplete results.

We should indicate to the user that the subscription loading is still in progress, so they're not confused by subscriptions missing from the search.

<img width="765" alt="screen shot 2015-12-03 at 09 20 20" src="https://cloud.githubusercontent.com/assets/17325/11546075/1b4bb492-999f-11e5-9a4a-776ed70fa979.png">

**Comment by blowery** [comment]
This was fixed a while back
