### ISSUE TITLE
Domain Search: translated strings when language set to english 

### ISSUE THREAD

**Issue by josemarques** [Automattic/wp-calypso#12073]
I’m seeing some translated strings in /domains even though I have WordPress.com set to English:
![screen shot 2017-03-13 at 17 44 36](https://cloud.githubusercontent.com/assets/57050/23868581/d5bf0b84-0817-11e7-80dc-ee8130f40e73.png)

I realized I could only replicate this in Chrome Canary, so I looked at the language settings where Portuguese comes first: 
![screen shot 2017-03-13 at 18 11 48](https://cloud.githubusercontent.com/assets/57050/23868797/b9ccefee-0818-11e7-9d15-5fe01f5478c8.png)

In my regular Chrome installation everything is fine because English is set as as the default: 
![screen shot 2017-03-13 at 18 07 30](https://cloud.githubusercontent.com/assets/57050/23868836/d5cdd096-0818-11e7-889e-524fe77f8275.png)

![screen shot 2017-03-13 at 18 12 15](https://cloud.githubusercontent.com/assets/57050/23868849/e303b4f6-0818-11e7-8e78-c6c772e1a2c4.png)

**Steps to reproduce:** 

1. Set the browser language to another language different from English.
2. Open https://wordpress.com/domains and notice that some strings will be translated to that language.

**Comment by fabianapsimoes** [comment]
Moved to #38-a8c-domain-search.
