### ISSUE TITLE
Plugins: Long delay after successful transfer

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#12085]
After doing a successful automated transfer to a site, there is a long delay between when you see the plugin install message and the plugin activating.

Probably a few options here:
* Verify that the `COMPLETE` transfer status is coming back at the right moment. Do we need to wait a bit longer?
* Could we manually refresh the plugin detail page after the success message appears for a few seconds?
* A band-aid method would be to add more text to the success message, like "Successfully installed Contact Form 7! Wait a moment while we activate it."

You can see the delay in this video: https://cloudup.com/ccZLLn5dICE

@Copons any thoughts on this one?

Related to #12070

**Comment by Copons** [comment]
During the delay, what is the _plugin_ status?
I mean: is it actually disabled or it is enabled but the front-end doesn't know about it yet?

In the first case we could show the plugin info along with the "complete" message.

In the second, maybe we could add yet another AT status that comes after `COMPLETE` (something like `ACTIVATION`) that could be like `atat.status === 'COMPLETE' && plugin.status !== 'ACTIVE'`, but then we would definitely be increasing the complexity of everything.
So maybe the band-aid method is not so bad after all.

**Comment by roundhill** [comment]
I'm not sure what the status is. After the 10 seconds or so, the UI refreshes for the plugin and you see the Jetpack-y things like the `activate` slider. I'm assuming that it's probably a delay between when Jetpack is activated on the Pressable side and when API calls start to work?

**Comment by roundhill** [comment]
Here's an idea for the band-aid solution for now until we can figure out something better:

<img width="727" alt="screen shot 2017-03-16 at 9 14 57 am" src="https://cloud.githubusercontent.com/assets/789137/24006451/1031f3ae-0a29-11e7-81cf-958850a668ea.png">

@drw158 any thoughts?

**Comment by drw158** [comment]
From a user pov, it would make sense to just continue the blue "Installing WP Super Cache..." notice until the plugin is activated, but I'm sure it's not so simple at that.

I think the copy looks good! I would prefer the spinning arrow icon to be present in this green message as well, just to get the point across. I think most ppl will glance over the text.

**Comment by roundhill** [comment]
I like that idea, maybe we'll just keep it blue with the spinning arrow for the complete state, with the text `Activating (plugin name)`?

**Comment by roundhill** [comment]
Here's a video of it with the new concept, I think I like it better: https://cloudup.com/cb59DURDDMP

**Comment by drw158** [comment]
👍  looks good
