### ISSUE TITLE
Combined Cards: Video thumbnails not appearing for Vimeo

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12088]
Just noticed this Combined Card for Laughing Squid is missing an image.

<img width="825" alt="screen shot 2017-03-13 at 3 27 56 pm" src="https://cloud.githubusercontent.com/assets/24388/23877908/d768030c-0801-11e7-8495-b8c38ce9ab5c.png">

The post missing the image is https://wpcalypso.wordpress.com/read/feeds/12098/posts/1375517207 which has a Vimeo video.

cc @bluefuton

**Comment by samouri** [comment]
I don't think this is for all vimeo videos and I also don't think this is technically related to combined cards.

If you go to the stream for laughingsquid, the thumbnail/video card is missing there as well.

When digging into the issue, it looks like the way that we normally glean the thumbnail url does not always work but I'm not sure why yet.  We usually look for a json file located here: `https://vimeo.com/api/v2/video/{videoId}.json` 

In this case it is: https://vimeo.com/api/v2/video/614847322.json which returns a 500 (could vimeo be having issues?).  Other urls are still working like this vim video: https://vimeo.com/api/v2/video/6999927.json.

I may have found a better solution though, going straight to vimeo's cdn like so:
- templateUrl: `https://i.vimeocdn.com/video/{ id }.webp`
- https://i.vimeocdn.com/video/6999927.webp

**Comment by blowery** [comment]
just be careful if that's really webp: http://caniuse.com/#feat=webp

we might be able to wrap it in photon and have photon return a jpeg for non-webp browsers? maybe?

**Comment by blowery** [comment]
hmm though replacing `.webp` in those urls with `.jpg` appears to work...

**Comment by fraying** [comment]
Ah, my mistake! I thought this was just related to Combined Cards. Excellent sleuthing!
