### ISSUE TITLE
Posts: Long title in Latest Drafts pushes Published posts out of frame.

### ISSUE THREAD

**Issue by menakas** [Automattic/wp-calypso#12099]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/ for a test site
2. Create a draft with a long title (Around 100 characters if you are on desktop). Save but do not publish. 
3. Go back to https://wordpress.com/posts/

#### What I expected
I expected to see the Published posts panel on the left and the Latest Drafts panel on the right

#### What happened instead
The Latest Drafts panel occupies the whole frame and pushes the Published Posts Panel out of the frame.

#### Browser / OS version
Firefox/Windows

#### Screenshot / Video
![mydrafts](https://cloud.githubusercontent.com/assets/6427897/23892587/3a84e530-08c1-11e7-8e92-b7ee157b5207.png)

#### Context / Source

How I found the bug: #user-report Based on **242214-hc**

![h](https://cloud.githubusercontent.com/assets/128826/23894434/cf009c6e-08ed-11e7-8892-24f6ed0abbbb.png)

I tried reproducing the bug. I thought it might be because of the title being a url (no spaces in between) in the user's site. But with/without spaces in the title, the bug can be seen.

Possibly related to issue [https://github.com/Automattic/wp-calypso/issues/8490](https://github.com/Automattic/wp-calypso/issues/8490)

**Comment by designsimply** [comment]
I tried reproducing this a few times and haven't been able to reproduce the problem yet. 

My testing steps:

1. Go to https://wordpress.com/posts/ and switch to a test site.
1. Create a post with a title that is longer than 100 characters.
1. Save but do not publish.
1. Click "←" to go back to the Blog Posts list.

<strong>Result:</strong> I can see a list of drafts in a dropdown menu next to the Write button and the draft list is a normal size.

![screen shot 2017-03-15 at wed mar 15 3 17 33 pm](https://cloud.githubusercontent.com/assets/1119271/23971200/96652d84-0992-11e7-8279-291aa080f2b7.png)
<sup>Seen at https://wordpress.com/posts/design5279.wordpress.com using Firefox 50.0.1 on Mac OS X 10.12.3.</sup>

Sample title (111 chars): 

> JabberwockyTwasbrilligandtheslithytovesDidgyreandgimbleinthewabeAllmimsyweretheborogovesAndthemomerathsoutgrabe

**Comment by designsimply** [comment]
Also tested with Firefox 52 on Windows 10 via BrowserStack and the drafts list on the Blog Posts page looks good to me there as well!

![bs_win10_firefox_52 0](https://cloud.githubusercontent.com/assets/1119271/23971514/e7e858ec-0993-11e7-8c8e-cca8434a4077.jpg)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using Firefox 52.0 on Windows 10 via BrowserStack.</sup>

**Comment by designsimply** [comment]
(Internal ref: also see 104307-hc)

**Comment by menakas** [comment]
Hi @designsimply,
Thanks for testing that out. From the screenshots, I see that you are looking at the dropdown next to he Write button. What I am referring to is the panel that comes up by default.

It looks like this when the drafts have short titles (normal behaviour)
![latestdrafts1](https://cloud.githubusercontent.com/assets/6427897/23976423/92c37912-0a0d-11e7-8df2-eddeb7bd97cb.png)

It looks like this when the draft titles are long. I have clicked on the dropdown next to Write as well in this screenshot, which overlays on the panel.
![latestdrafts2](https://cloud.githubusercontent.com/assets/6427897/23976459/d7b25976-0a0d-11e7-9bc8-3bf9cfc94833.png)

**Comment by menakas** [comment]
Internal reference: 104307-hc and 242214-hc (#userreport based on which I logged this issue) are of same user.

**Comment by designsimply** [comment]
@menakas thank you for the extra info—I tested again and was able to see the problem this time! I found that it only happens if the browser width is large enough (i.e. >1346px).

![screen shot 2017-03-16 at thu mar 16 11 52 50 am](https://cloud.githubusercontent.com/assets/1119271/24011114/721b9d48-0a3f-11e7-92ad-ac2a4635c9fe.png)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using IE11 on Win8.1 with BrowserStack.</sup>

![screen shot 2017-03-16 at thu mar 16 11 54 05 am](https://cloud.githubusercontent.com/assets/1119271/24011118/7475c05a-0a3f-11e7-97a3-af8ac9c643ce.png)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using Safari 10.0.3 on Mac OS X 10.12.3</sup>

![screen shot 2017-03-16 at thu mar 16 11 54 51 am](https://cloud.githubusercontent.com/assets/1119271/24011121/7700b7f8-0a3f-11e7-955d-7a534273a8f3.png)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using Firefox 52.0 on Mac OS X 10.12.3</sup>

**Comment by designsimply** [comment]
Example with spaces in the titles:

![screen shot 2017-03-16 at thu mar 16 12 06 52 pm](https://cloud.githubusercontent.com/assets/1119271/24011742/3ed1f7dc-0a41-11e7-8d64-0c5f5950f40d.png)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using Firefox 52.0 on Mac OS X 10.12.3.</sup>

**Comment by alexjgustafson** [comment]
3120282-t

**Comment by simplysaru** [comment]
Another user had this issue  earlier today. 47056-hc

**Comment by jeremeylduvall** [comment]
This should be fixed in #12414.
