### ISSUE TITLE
Combined Cards: Unlinked Site Title

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12090]
On this page: https://wpcalypso.wordpress.com/tag/gardening

There's this Combined Card: 

<img width="838" alt="screen shot 2017-03-13 at 4 13 58 pm" src="https://cloud.githubusercontent.com/assets/24388/23879065/259fcdec-0808-11e7-8abd-53fa13919a31.png">

There's no link on the site title in the card header. (There is in the regular cards: wordpress.com/tag/gardening )

This is the site feed: https://wordpress.com/read/feeds/34220269

**Comment by bluefuton** [comment]
Good spot @fraying. Looks like we're failing to grab the `site` or `feed` for combined cards on tag streams only:

<img width="538" alt="screen shot 2017-03-14 at 18 09 45" src="https://cloud.githubusercontent.com/assets/17325/23915588/78a59e16-08e1-11e7-9a4f-b5bdb91516e9.png">

cc @blowery

**Comment by designsimply** [comment]
Fwiw, I see the site title linked in the tag stream for some blogs and not others:

![screen shot 2017-03-14 at tue mar 14 1 54 34 pm](https://cloud.githubusercontent.com/assets/1119271/23919782/d5cfae16-08bd-11e7-8771-897346242b71.png)
<sup>Seen at https://wpcalypso.wordpress.com/tag/kiteboarding using Chrome 56.0.2924.87 on Mac OS X 10.12.3 where "KukulKite" leads to https://wpcalypso.wordpress.com/read/blogs/95035288.</sup>

**Comment by designsimply** [comment]
I also saw a case where the site title in the main stream was not linked:

![bs_win8 1_ie_11 0](https://cloud.githubusercontent.com/assets/1119271/23919860/1ea97d4c-08be-11e7-97d8-b997892e4431.jpg)
<sup>Seen at https://wpcalypso.wordpress.com/ using IE11 on Win8.1 via BrowserStack.</sup>
