### ISSUE TITLE
Purchases: Cancellation: Cancel Purchase screen layout responsive issues

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#121]
The "Have questions?" box gets a little too narrow on certain screen sizes:

![image](https://cloud.githubusercontent.com/assets/12596797/11250282/c77b9bc6-8df9-11e5-809f-13bffad87892.png)

Also <480px screens the "Have questions?" box should probably be ordered last instead of first to keep the hierarchy of the page accurate at all screen sizes.

![image](https://cloud.githubusercontent.com/assets/12596797/11250376/3f154b32-8dfa-11e5-9ea3-f8b0d75baec9.png)

**Comment by scruffian** [comment]
Closing this since we have a new design for this page.
