### ISSUE TITLE
Tortuga: Clicking "Create Site" after purchasing just a domain and then a plan leads to a loop and getting stuck

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#12103]
Originally reported by @designsimply in #31-a8c-domain-search:

Steps to reproduce:

1. Purchase just a domain for a site on WordPress.com.
1. Click the "Create Site" button on the My Sites > Settings page.
1. Select a theme.
1. Click the "Upgrade" button in the Personal column.
1. Submit payment—note that instead of a thank you page you still see the notice about there only being a temporary page (landing page) and the "Create Site" and "Manage Domain" options are all you can see on the main screen.
1. Refresh the blog front end to see whether the landing page is still there. (It's not.)
1. Click the "Create Site" button on the My Sites > Settings page again.
1. Select a theme again.
1. Click the "Upgrade" button in the Personal column again.

<strong>Result:</strong> if you try to use the "Create Site" option after purchasing just a domain and then adding a plan, you get stuck in a loop and eventually stuck at the "Awesome!" screen. ([2m50s](https://cloudup.com/cUtHg21uLNC))

![screen shot 2017-03-13 at mon mar 13 7 57 27 pm](https://cloud.githubusercontent.com/assets/1119271/23882637/990e6562-0827-11e7-9367-106188449016.png)
<sup>Seen at https://wordpress.com/checkout/thank-you/tellthislikeitis.blog using Safari 10.0.3 on Mac OS X 10.12.3.</sup>

**Comment by fabianapsimoes** [comment]
@aidvu I'd guess this one might be related to https://github.com/Automattic/wp-calypso/issues/11668. What do you think?

**Comment by aidvu** [comment]
Not sure. The other one is more sites-list, while this is site-options from the looks of it. :) Should leave both for investigation.

**Comment by designsimply** [comment]
Re-tested and confirmed the problem is still happening: <em>right after</em> clicking the "Pay $15.88" button when adding a plan for a domain only purchase, I can see new options in the left panel but the main page still shows the "Create Site" and "Manage Domain" options and I can get stuck in a loop if I click "Create Site" again.

Video: [2m14s](https://cloudup.com/c5EnvGiB_d5)

![screen shot 2017-03-28 at tue mar 28 12 29 25 pm](https://cloud.githubusercontent.com/assets/1119271/24421083/482c90c4-13b2-11e7-9894-a7fac54f38b7.png)
<sup>Seen at https://wordpress.com/checkout/thank-you/thegamewereplaying.com/22764837 using Chrome 57.0.2987.98 on Mac OS X 10.12.3</sup>

**Comment by designsimply** [comment]
Aha. I was missing a crucial piece. This problem only happens if you buy "just a domain" when already logged in as an existing user. Sorry I didn't catch that earlier! ([3m3s](https://cloudup.com/chDz5JisEuJ))

**Comment by fabianapsimoes** [comment]
@designsimply Andrija and I are having a really hard time reproducing this consistently. I can reproduce it with one of my testing accounts, but Andrija can't using the same one. Then I tried with a brand new account and was unable to trigger the error. 

Can you try and tell us a bit more about this? Does it happen all the time, with any accounts you use? Is it happening on all browsers? Did you use a credit card, credits or some other payment method?

**Comment by designsimply** [comment]
Re-tested and confirmed fixed. 😆  Video: [37s](https://cloudup.com/cZ9C6W7ZcV2)
