### ISSUE TITLE
Media Section: Selected images in media section remain selected in media modal in editor.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#12109]
Steps to reproduce:

1. Go to `/media`.
2. Select some images.
3. Click "add" to create a post. (You can navigate to anywhere before you click "add" button in Blog Posts.)
4. Open the media modal.
5. You see the same images are already selected.

I don't think this is a feature... The context is different in the section and the modal, and it can be confusing that some images are already selected when you create a new post if you've forgotten that you've selected some images in the section a while ago.

![untitled2](https://cloud.githubusercontent.com/assets/908665/23900232/4a4a9f52-08b0-11e7-8940-13d9c31d7beb.gif)

**Comment by jeremeylduvall** [comment]
This should be fixed up by #12296.
