### ISSUE TITLE
Signup: steps are skipped when attempting to re-do them

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#12118]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains
2. Fill out the search field and choose a domain name
3. Select "Start a new site", choose a theme, etc.  Stop at the plan selection page 
4. Navigate Back to the start (either manually or visit /domains in the URL bar again)
5. Fill out the search field and choose a domain name

#### What I expected
To be able to choose again whether to start a new site or just a domain, or at least to choose a new theme

#### What happened instead
The choice between "start a site" and "domain only" displays briefly, but is then immediately skipped and I'm dumped back at the plan selection page.

#### Browser / OS version
OSX Chrome v57

#### Screenshot / Video
![tortuga-skipping-steps](https://cloud.githubusercontent.com/assets/7233112/23908906/a8c09294-08ab-11e7-9eec-54b5f30208a5.gif)

#### Context / Source
#manual-testing

**Comment by klimeryk** [comment]
From my experience, this is not specific to Tortuga and has been in NUX for some time.

**Comment by designsimply** [comment]
Also reported at p1490627959510744-triage.
