### ISSUE TITLE
Plugins: add an Add Plugin button to the plugins SectionHeader

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#1212]
The button will link to the plugin browser. It will look like this:

<img width="685" alt="screen shot 2015-12-02 at 5 35 07 pm" src="https://cloud.githubusercontent.com/assets/437258/11546397/0f10d8a8-991b-11e5-9ccd-7e6dcfdd13bb.png">

**Comment by johnHackworth** [comment]
done!
