### ISSUE TITLE
Tortuga: IE11 create site / domain options missing labels

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#12125]
#### Steps to reproduce
1. Using IE11 - Starting at URL: https://wordpress.com/domains
2. Input a domain name and select to purchase it

#### What I expected
To be prompted to start a new site or buy a domain only

#### What happened instead
![screen shot 2017-03-14 at 2 23 06 pm](https://cloud.githubusercontent.com/assets/7233112/23916319/1f78cdc8-08c2-11e7-90f7-0d8c10016629.png)

The buttons still work, but don't have any identification

#### Browser / OS version
IE11, Windows 7

#### Context / Source
#manual-testing

**Comment by aidvu** [comment]
@hoverduck do we close it, or try to reproduce, as you said you couldn't do it on second test?

**Comment by designsimply** [comment]
Tested and confirmed I cannot see the "Start a new site" or "Just buy a domain" labels below the thumbnail options in step 1 of 3 after starting at https://wordpress.com/domains 

![bs_win8 1_ie_11 0 7](https://cloud.githubusercontent.com/assets/1119271/23923633/fa110464-08cc-11e7-94c5-972b06ccd67a.jpg)
<sup>Seen at https://wordpress.com/start/domain-first/site-or-domain?new=testingallthetime.com using IE11 on Win8.1 via BrowserStack.</sup>

In comparison, I can see the labels for the options when testing with Safari on a Mac:

![screen shot 2017-03-14 at tue mar 14 3 44 41 pm](https://cloud.githubusercontent.com/assets/1119271/23923756/8e4fc20a-08cd-11e7-89c5-b7bec1f5db7f.png)
<sup>Seen at https://wordpress.com/start/domain-first/site-or-domain?new=testingallthetime.com using Safari 10.0.3 on Mac OS X 10.12.3.</sup>

**Comment by designsimply** [comment]
Works fine on IE14 Win10 via BrowserStack: 

![bs_win10_edge_14 0](https://cloud.githubusercontent.com/assets/1119271/23924639/0b1c4c10-08d1-11e7-9ba3-d3fdab9e6c59.jpg)
<sup>Seen at https://wordpress.com/start/domain-first/site-or-domain?new=testingallthetime.com using IE14 Win10 via BrowserStack.</sup>

**Comment by aidvu** [comment]
Amazing, thanks @designsimply!
