### ISSUE TITLE
Blavatar Weirdness

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12136]
Did something change with the way blavatars are created/handled?

I've been seeing a lot of this image ...

https://s2.wp.com/i/buttonw-com.png?w=240

... coming through as blavatars.

<img width="158" alt="screen shot 2017-03-14 at 1 34 41 pm" src="https://cloud.githubusercontent.com/assets/24388/23921210/016f822e-08bb-11e7-897b-85af4150fcba.png"><img width="182" alt="screen shot 2017-03-14 at 1 34 34 pm" src="https://cloud.githubusercontent.com/assets/24388/23921211/01751de2-08bb-11e7-9aa4-4d144bf173a2.png">

https://wordpress.com/read/blogs/46616724/posts/35584
https://wordpress.com/read/blogs/90341190/posts/6077

Any ideas?

**Comment by blowery** [comment]
hmmmm...

we may have "fixed" how we pick up favicons from feeds.... @bluefuton @samouri thoughts?

**Comment by blowery** [comment]
yeah, it's coming from the feed... somehow we're detecting that as a favicon?
