### ISSUE TITLE
Plugins: disable bulk edit action when not permitted (and explain why)

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#1213]
Currently, if you attempted to perform a bulk edit action on a site that's under version control or on a sub-site in a multi-site install it would fail. Since you don't have permission to perform such an action it would throw an error. We can do better than that and disable any illegal options. We can do even better by explaining why those options are disabled.

Here's a rendering:

<img width="690" alt="screen shot 2015-12-02 at 5 42 31 pm" src="https://cloud.githubusercontent.com/assets/437258/11546560/199c4e28-991c-11e5-994a-2f63e7e09016.png">

We'll need to work through the messaging a bit, the copy in the screenshot is for placement only.

**Comment by johnHackworth** [comment]
uhm, a question about this, @rickybanister : Since most of the buttons are disabled by default (until you select some plugins, and some of them could be even disabled after that depending on the state of the plugin)... wouldn't this popup could be missleading?

**Comment by rickybanister** [comment]
You know what, you're right—for some reason I wasn't considering the fact that the individual plugin actions for each plugin should include respective `InfoPopover`s if a certain action is disabled. 

Let's go ahead and close this as redundant and confusing.
