### ISSUE TITLE
Editor: 'Saving' Difficult to see 

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#12140]
#### Steps to reproduce
1. Edit a post  
2. Select Update 

#### What I expected
When I select Update to see something indicating it was updating. 

#### What happened instead
My connection was slow, it took a few seconds to update. At first, I didn't think anything happened when I selected update, so I clicked it a few more times. Then I noticed the "Saving" text. It was difficult to see the  text to the far left, in light grey. 

#### Browser / OS version
Safari Mac 10.12.03

#### Screenshot / Video
http://cld.wthms.co/njK9

#### Context / Source

I'd suggest revising the indicator that the post is saving. It's too far from where a user's attention would be when selecting Update. 

#perspective #dogfooding, #manual-testing

**Comment by folletto** [comment]
Here a couple of options on a codepen: http://codepen.io/folletto/pen/ZeXzVM?editors=1100

Specifically this one is probably ideal as it reuses the same concept as the progress bar:

![cap-](https://cloud.githubusercontent.com/assets/4389/23946398/29b96bd4-0972-11e7-911f-f6cea91c0e03.gif)

**Comment by folletto** [comment]
PR #12161 introduced the "loader" `is-busy` styling to be used in the Editor. :)
