### ISSUE TITLE
Plugins: Add wp-admin link for plugins that don't have any action links

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#12141]
https://github.com/Automattic/wp-calypso/pull/11718 has been helpful for getting users to the plugin settings in wp-admin for plugins that provide action links. Many plugins don't use action links, however and may do something else like add a menu item to the sidebar. For these plugins that have no action links, let's inject an action link that will take them to wp-admin for the site.

Concept (cc @drw158 was this what you were thinking?):
<img width="689" alt="screen shot 2017-03-14 at 2 54 36 pm" src="https://cloud.githubusercontent.com/assets/789137/23923991/2ea21026-08c6-11e7-8035-4e39c9309740.png">

**Comment by drw158** [comment]
I was struggling to come up with what to call it. It could be "Manage Plugin" or something like that. But WP Admin is probably the best way to go.

I would change it to `WP Admin` because that is what we do in the sidebar.
