### ISSUE TITLE
Editor: Link to change site timezone is invalid

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#12157]
#### Steps to reproduce
1. Set your site's timezone to anything other than your OS timezone
2. Edit a post, then pop open the schedule datepicker
3. Click the information icon beside the message about the timezone difference.
4. The **General Settings** link url is `https://wordpress.com/settings/general/null`
5. Clicking the link puts the editor in a weird state

![screen_shot_2017-03-15_at_3_58_13_pm](https://cloud.githubusercontent.com/assets/416133/23935572/4d55c81e-0998-11e7-8d26-03053155c32c.png)

#### Browser / OS version
Chrome 57/MacOS

#### Screenshot / Video
![screenflow](https://cloud.githubusercontent.com/assets/416133/23935677/e86d3bb6-0998-11e7-804a-31aaa45b2021.gif)

#### Context / Source
Found while reviewing #11528

**Comment by rachelmcr** [comment]
There's no longer a link from the editor's date picker to the site's general settings, so I'm closing this issue as it no longer applies.

Current screenshot:

![screen shot 2017-10-04 at 5 54 22 pm](https://user-images.githubusercontent.com/8658164/31188685-9f725024-a92d-11e7-8dc3-8cd70c0ecd8d.png)
