### ISSUE TITLE
Reader Combined Cards: handle Discover posts

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#12159]
In Combined Cards, we need to either:
- exclude Discover posts from combined cards
- plan how to reuse the Discover-specific code in `ReaderPostCardAdapter` for combined cards

**Comment by fraying** [comment]
I think the simplest thing would be to exclude Discover posts from Combined Cards.

**Comment by bluefuton** [comment]
Fixed in #12242.
