### ISSUE TITLE
Combined Cards: Possible to limit to 24 hours?

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12151]
Forgive me for another Combined Cards question:

Would it be possible to limit Combined Cards to posts within 24 hours of each other?

Why: The intent behind Combined Cards was to turn down the volume on high frequency sites. But if you only follow a handful of sites, and they don't update that often, you could wind up with Combined Cards that include posts from days apart. This could be confusing. 

Additionally, if you only follow one site (like your own), currently you'll get one giant Combined Card with all your posts in it. This, again, wasn't really the intent.

So, a possible solution would be to limit Combined Cards to a 24 hour period. That way, if you follow only one site, and it posts once a day, you'd never see a Combined Card. And if you follow a handful of sites, and they only post once a day, again, you'd never see a Combined Card. You'd only see a Combined Card if you then decided to follow time.com or a similar high frequency site (which was the intent with the feature).

Where does this fall on the Hours/Days/Weeks scale?

cc @bluefuton @samouri @blowery

**Comment by fraying** [comment]
Here's a good example: Ignore that this is IFTTT spam and look at https://wpcalypso.wordpress.com/tag/ted-blog

That's a single Combined Card with 45 posts, most of which are from different days. That's not really what Combined Cards were meant for.

(Thanks to @designsimply for pointing that one out.)

**Comment by samouri** [comment]
Implemented in #12192, thanks @fraying for the excellent test tag
