### ISSUE TITLE
Tortuga: Better support for arbitrary domain configurations

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#12166]
We should make sure the post-purchase experience for domain-only sites has proper support for different domain configurations other than the default for new domains (for example, using non-wpcom name servers, email only, etc.)

All screens we designed for Tortuga so far were specifically for domains that still have the default settings we configured during purchase. When users make changes, we should adapt the copy and available actions to the new configuration.

Similar to what we did with Delphin, I think we should consider different domain "states" and address each one separately

### Default (no changes since purchase)

This is the default state we worked on so far. 

The key message is that the domain is ready for starting a new site.

The primary action is to start a new wpcom site. 

### Non-wpcom name servers

Users may change the name servers, to use the domain with a different host. 

The key message is that the domain is pointing to another host and not using wpcom services.

There is no primary action.

The secondary action is to go to the domain management screen.

ATM, we have no special provisions in Calypso domain management for domains that don't user wpcom name servers. There is no indication that the domain is not pointing to wpcom (unless you open the DNS screen specifically), and the email flow is available as usual. 

We also don't warn users that changing name servers will interfere with any active configurations they already made, for example email forwarding. 

### Custom DNS records

Users may set custom DNS records (without changing name servers) to use the domain with a different host. This points specific services away from wpcom, but still leaves the domain under our management.

The key message is that the domain is using a custom or "advanced" configuration. If we can identify specific records, we can show a better message, for example to say that the domain is pointing to a Tumblr blog. 

If the main A record is unchanged from the default settings, we can keep the primary action for adding a wpcom site. Otherwise, there is no primary action.

The secondary action is to go the domain management screen.

As mentioned for non-wpcom name servers, it doesn't look like we have any warnings or protections in place to keep people from messing up existing configurations. 

### Email forwarding

As long as the domain is on our name servers, users can add email forwarding with any of the other configurations. 

If the domain has email forwarding only (no site or other customizations), the key message is that the domain is only used for email, and ready for starting a new site.

The primary action is to start a new wpcom site.

The secondary action is to go to the domain management screen. Though we may consider adding a dedicated button for managing email specifically.

### G Suite

Similarly to email forwarding, G Suite can be set up alongside other configurations.

The key message for G Suite only is that the domain is only used for G Suite, and ready for starting a new site.

The primary action is to start a new wpcom site.

The secondary action is to go to the domain management screen, but here too, we may consider adding a dedicated button for managing email specifically.

**Comment by danhauk** [comment]
@ranh Do you think this would mostly just be copy changes? I'm not sure we need to do much other than update copy and maybe remove the `Create Site` button in some cases (like Non-wpcom name servers).

Also noting here: We will need some kind of warning when the user decides to change name servers with custom DNS records (or start a site if their name servers are not currently set to wordpress.com).

**Comment by ranh** [comment]
@danhauk I think the user-facing changes will be mostly in the copy. The question of protecting users from unwittingly breaking their sites by changing things here is not unique to domain-only sites, it applies to any WordPress.com site, and we may already have things in place to handle this. I'll look into this more and add more details before removing the In Progress label, probably today or tomorrow.
