### ISSUE TITLE
Settings > General: Move Import & Export to a 'Site Tools' section

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12169]
Currently Import and Export are their own tabs in the Settings navigation. For Jetpack sites they are still external links.

Since Import and Export are infrequently used during the lifespan of a site and relate somewhat closely to the 'Start Over' and 'Delete Site' options, I would like to propose we move them into the General tab of settings as 'site tools'.

For Jetpack sites:

(This new block would go at the bottom of the General tab. While import and export are not supported for Jetpack sites we may want to use an external link icon instead of the caret, but I'm indifferent.)

<img width="752" alt="screen shot 2017-03-15 at 11 26 31 am" src="https://cloud.githubusercontent.com/assets/437258/23956260/9ad7a560-0972-11e7-809f-0348c4343903.png">

For WordPress.com sites:

<img width="748" alt="screen shot 2017-03-15 at 11 32 54 am" src="https://cloud.githubusercontent.com/assets/437258/23956492/2b8c7ae0-0973-11e7-9f1c-39afdb03efa4.png">

**Comment by oskosk** [comment]
We will be losing a couple of URL routes with this change. `/settings/export` and `/settings/import`. I don't recall if it has been discussed how to handle the removed URLs

**Comment by drw158** [comment]
Looks good! I imagined import and export would go to a Tools tab, along with Google Analytics, but this makes sense.

**Comment by rickybanister** [comment]
@drw158 Google Analytics used to kind of float around by itself, but now that we have other 'Traffic' offerings it seems nicely at home there. 

The old 'tools' tab was kind of a grab bag of other things that didn't fit anywhere, so I'm hoping to keep things related to starting up or shutting down a site together here.

**Comment by rickybanister** [comment]
One additional note, let's make the delete and disconnection cards red:

![image](https://cloud.githubusercontent.com/assets/437258/24726042/f3b8f6cc-1a1e-11e7-9b91-f749322b6148.png)

Some wordpress.com sites, perhaps based on theme also have another option that says 'make your site look like the theme preview' so that should be included here if applicable.

**Comment by rickybanister** [comment]
@seear can you update this issue or close it? It's marked in-progress, but seems like you merged everything to shut it down. 

Thanks!

**Comment by seear** [comment]
Yeah this is now done 🎉
