### ISSUE TITLE
Tortuga: unify default/settings/featuregate screens

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#12162]
We should make sure the post-purchase experience for domain-only sites has clear and consistent messaging about actions available to new domain-only site owners.

![ranimac3 screenshot 2017-03-15 at 13 14 44](https://cloud.githubusercontent.com/assets/426518/23948240/d65f5cf0-098a-11e7-92c7-589c15580682.png)

(I refer to this as the "default" screen, I don't know if that's how everyone else is thinking about it. Could also be the "Settings" screen I guess)

This screen was initially conceived as the default view for My Sites for domain-only sites. At some point we also added a "[feature gate](https://github.com/Automattic/wp-calypso/pull/10840)" screen, to show when users try to visit a path for a feature that is not available on domain-only sites. The two screens are very similar, with only small differences in the title and subtitle copy. 

The distinction between these two screens was never entirely clear, and in practice, because of how Calypso works, the featuregate is being shown in many cases for which the default screen would be a better fit. See some more about this in https://github.com/Automattic/wp-calypso/issues/11430

I suggest we remove the distinction between these two screens and keep just one default screen for domain-only sites, to be used in all cases. This should help avoid any confusion and extra work for us, and make for a smoother Calypso experience for users.

Suggested copy for the new screen:

> example.com is ready when you are.
>
> Start a site now to unlock everything WordPress.com can offer.

(Removing the part about email etc. to keep the message focused and clear)

**Comment by designsimply** [comment]
Part of me wants this to go straight to the domain settings with an explainer at the top. As a user, I just want the software to get me to what I need fast. Might be worth asking so I will ask: is a default page really really needed for domains-only?

**Comment by breezyskies** [comment]
> As a user, I just want the software to get me to what I need fast. Might be worth asking so I will ask: is a default page really really needed for domains-only?

The goals for the v1 of /domains is to focus on it as an acquisition channel. If a user reaches this state, we're assuming (pending data) that they are in the "not ready to create a site yet" category. We are optimizing for this type of user. 

The domain settings, for changing name servers or DNS to point to another host, for example, are currently considered the edge case. We are not strategically focusing on these users for the v1. We may improve flows for these users at a later point, but they are currently lower priority.

More details on the v1 goals in p6qnuF-3SA-p2.

**Comment by ranh** [comment]
> As a user, I just want the software to get me to what I need fast

This is exactly the motivation behind this screen. We believe the best next action for most users is going to be to start a new WordPress.com site, so we have a very easy path to achieve that result. Getting anything done on the regular Calypso domain management screen, with its many advanced options, requires plenty of guidance (or plenty of previous experience). Landing directly there would be overwhelming.

**Comment by designsimply** [comment]
I love that the design decisions were explained here. Thank you!
