### ISSUE TITLE
Settings > Writing: move cpt descriptions into the label-content

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12176]
Currently the label descriptions are outside of the `form-toggle__label-content` element, causing them to be 'outdented'. 

The should look like the top example below, *not* the bottom element below. Moving `form-setting-explanation` into `form-toggle__label-content` fixes this.

<img width="740" alt="screen shot 2017-03-15 at 12 02 35 pm" src="https://cloud.githubusercontent.com/assets/437258/23958143/8563edb0-0977-11e7-8027-83af25ca02c6.png">

cc @MichaelArestad @ashleighaxios

**Comment by oskosk** [comment]
This is being handled in #12199

**Comment by tyxla** [comment]
As Oscar has taken care of this in #12199, I'm unassigning me and Rocco from this one.
