### ISSUE TITLE
Settings > General: setting block for enabling the Jetpack masterbar

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12171]
In the next version of Jetpack we will be introducing the WordPress.com masterbar for Jetpack sites. We need a settings block for it, probably in the General tab. It may want to be grouped together with `WordPress.com sign in` in a sort of 'use WordPress.com to manage your site' block.

Here's how it looks in wp-admin:

![image](https://cloud.githubusercontent.com/assets/437258/24726087/26b8b6ac-1a1f-11e7-9c1d-84cb55b6c0c5.png)

It's there in the writing tab because there is not currently a general tab in wp-admin

**Comment by tyxla** [comment]
@rickybanister the toolbar in Jetpack 4.8 is beautiful, I'd love to add this card to Calypso too.

I have a couple of questions though: where should this go in the General tab? Or if it's to be grouped with the **WordPress.com sign in** card, can we have a quick mockup of how that would become?

**Comment by rickybanister** [comment]
@tyxla sorry, my issue above was very vague. 

I think we should mirror Jetpack's implementation for now and consider a larger rethink to align with a future Jetpack release. Does that work for you? It will be easy enough to move that card later on.

**Comment by tyxla** [comment]
I've addressed that one in #12946.
