### ISSUE TITLE
Settings: Underline links in sentences

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#12175]
Underline links within sentence structures for descriptions and body text.

Before:
<img width="732" alt="screen shot 2017-03-15 at 12 01 36 pm" src="https://cloud.githubusercontent.com/assets/22752103/23958023/37b2acf0-0977-11e7-8081-4e324b7e1f39.png">

After:
<img width="746" alt="screen shot 2017-03-15 at 12 01 26 pm" src="https://cloud.githubusercontent.com/assets/22752103/23958028/3d1ce3c2-0977-11e7-827b-f9fce23fc390.png">

Do not underline all links, we'd like stand-alone links to stay as is. IE:
<img width="737" alt="screen shot 2017-03-15 at 12 03 45 pm" src="https://cloud.githubusercontent.com/assets/22752103/23958132/7ddb2b9e-0977-11e7-9503-2bbee8577919.png">

<img width="737" alt="screen shot 2017-03-15 at 12 04 26 pm" src="https://cloud.githubusercontent.com/assets/22752103/23958165/925d8e2c-0977-11e7-9c19-8842ef598af2.png">

**Comment by ashleighaxios** [comment]
Cc @rickybanister @MichaelArestad

**Comment by tyxla** [comment]
This is being addressed in #12221, so unassigning Rocco and Osk from this one.
