### ISSUE TITLE
Settings > Discussion: new label for Comments setting

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12177]
Current text:
`Use Jetpack Comments. Readers will be able to use their WordPress.com, Twitter, Facebook, or Google+ accounts to leave comments.`

New text:
`Allow readers to leave comments using their WordPress.com, Twitter, Facebook, or Google+ accounts`

<img width="745" alt="screen shot 2017-03-15 at 12 10 56 pm" src="https://cloud.githubusercontent.com/assets/437258/23958430/7c565914-0978-11e7-806b-c169b3f841c1.png">

cc @MichaelArestad @ashleighaxios

**Comment by MichaelArestad** [comment]
Other than that widow, I dig.

**Comment by rickybanister** [comment]
Widows should be handled systematically somehow. There's no telling what will happen once it's translated, etc.

**Comment by MichaelArestad** [comment]
@rickybanister There's a bug with doing it systematically on small screens (I have tried a few). We just have to live with it.

**Comment by tyxla** [comment]
This one is addressed in #12220, so unassigning Osk and Rocco from this one.
