### ISSUE TITLE
Settings > Writing: use radio options for infinite scroll

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12174]
See https://github.com/Automattic/jetpack/issues/6218 for discussion.

The toggle options for infinite scroll leave too much ambiguity. We reworked the language in the Jetpack plugin to make the options mutually exclusive with radio buttons:

```
( ) Load more posts using the default theme behavior
( ) Load more posts with a button
( ) Automatically load more posts as the reader scrolls down
```

cc @MichaelArestad @ashleighaxios

**Comment by tyxla** [comment]
I'm keeping an eye closely on what happens with this one in Jetpack, and once the necessary changes are done there, we can address them here too.

**Comment by MichaelArestad** [comment]
Perfect. Right now we have the same proposal for both.

**Comment by tyxla** [comment]
@eliorivero has addressed this in https://github.com/Automattic/jetpack/pull/6692, we can follow a similar approach for implementing it here in Calypso.

**Comment by rickybanister** [comment]
Here is the finished Jetpack implementation:

![image](https://cloud.githubusercontent.com/assets/437258/24726160/5bc57772-1a1f-11e7-9145-12356a4a6d53.png)

One final note, we don't need the save button for this, we can save onchange.

**Comment by oskosk** [comment]
@eliorivero is addressing this in #13257

**Comment by tyxla** [comment]
Oops, I just submitted a PR for that. Totally missed #13257 😞
