### ISSUE TITLE
Settings > Discussion > Subscriptions block punctuation tweaks

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12179]
* Remove 'Save Settings' button and make the subscriptions settings auto-save
* Remove periods from the end of each toggle item (the first and third toggle)
* Change capitalization from "View your Email Followers" to "View your email followers"

Before:

<img width="750" alt="screen shot 2017-03-15 at 12 20 36 pm" src="https://cloud.githubusercontent.com/assets/437258/23958871/d9482de0-0979-11e7-96fb-03a2f16ab597.png">

cc @MichaelArestad @ashleighaxios

**Comment by oskosk** [comment]
Casing and capitalization changes are being handled in #12191.

Removing of save settings button has already been introduced by #11939.

**Comment by tyxla** [comment]
Unassigning myself and Rocco as @oskosk took care of this one in #12191 and #11939.
