### ISSUE TITLE
Settings > Writing: remove periods from labels

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12172]
<img width="758" alt="screen shot 2017-03-15 at 11 45 41 am" src="https://cloud.githubusercontent.com/assets/437258/23957143/09ad7364-0975-11e7-8178-8c15fc2c8cfa.png">

Periods are still at the end of the labels for:

* `Enable Testimonial custom content types.`
* `Enable Portfolio custom content types.`
* The infinite scroll settings will be replaced with three radio options as per https://github.com/Automattic/jetpack/issues/6218#issuecomment-285215270 so that label will change anyway (wp-calypso issue coming soon)
* `Optimize your site with a mobile-friendly theme for tablets and phones.`
* `Publish posts by sending an email.`

**Comment by designsimply** [comment]
Should there be a period if it is a full sentence? (just checking)

**Comment by ashleighaxios** [comment]
@designsimply Not for labels — even if they complete as a sentence would. Yes for longer descriptions and areas where there is a supporting sentence or two.

**Comment by rickybanister** [comment]
We confirmed with @michelleweber that as long as we aim to write the labels as directly as possible in 'action' form it's best to drop the punctuation. Many labels are very short fragments, it just so happens that some of the Jetpack settings are longer.

**Comment by oskosk** [comment]
This is handled by #12200 (labels from Theme enhancements and Publishing Tools) and #12199 (labels from Custom Content Types).

**Comment by tyxla** [comment]
Assigning @oskosk here, as he took care of this one in #12200 and #12199.
