### ISSUE TITLE
Editor: copying and pasting bullets should not indent the bullet

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1218]
Raised by @gibrown 

I was trying to move a bullet from a list I have further up the list. I did a cut and paste. My cursor was at the start of a previous bullet and I expected the bullet I was pasting to be inserted above the current bullet.

<strong>Video:</strong> https://cloudup.com/cck_3pjohqp

Note: this only seems to happen in webkit browsers.

**Comment by brbrr** [comment]
Unable to reproduce it in Chrome & Safari
