### ISSUE TITLE
Settings > Security: backups block with API key field

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12181]
Here's a somewhat rough mockup for the backups block with a space for the API key:

<img width="752" alt="screen shot 2017-03-15 at 12 32 36 pm" src="https://cloud.githubusercontent.com/assets/437258/23959469/a95aed8c-097b-11e7-9fc5-bd0d0cef5ab7.png">

cc @MichaelArestad @ashleighaxios

**Comment by rickybanister** [comment]
One last detail, it would be very nice to add a green checkmark gridicon to the left of the 'your site is backed up...' text since this feature does not have a toggle.

**Comment by rickybanister** [comment]
@dereksmart can we have a quick conversation about this ticket—it may not be necessary to build this interface in Calypso if rewind is ready with its own settings.

**Comment by oskosk** [comment]
Closing as it's super old
