### ISSUE TITLE
Editor: Cannot see publish button with long site names

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#12187]
<img width="961" alt="new_post_ _aaaa_best_blog_would_blog_again_and_again_and_again_and_again_and_again_and_again_and_again_and_again_and_again_and_again_and_again_and_again_and_again_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/14350/23964761/f3428472-098b-11e7-83bb-128898498c9d.png">

as seen at https://wordpress.com/post/b19ytest.wordpress.com which has a site name of `AAAA BEST BLOG WOULD BLOG AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN AND AGAIN`

**Comment by folletto** [comment]
There are a few options, but a first approach would be that the Site component, especially when `is-compact` should trim (with the fade out) the title at roughly the same length as the sidebar width (plus or minus).

**Comment by timmyc** [comment]
I'm totally going to follow your test blog @blowery

**Comment by blowery** [comment]
@timmyc i can't really publish to it till this gets fixed, so it's gonna be pretty boring. ;)

**Comment by alisterscott** [comment]
This is a pretty serious bug, luckily there's a workaround in place:

1. Command-Option-J
2. Paste `document.getElementsByClassName('editor-publish-button')[0].click();` and press enter
3. ~~Profit~~ Publish

or you could just make your browser window narrow and publish it then

**Comment by blowery** [comment]
@alisterscott or reallllllllllllllllly wide. That fixed it too. I need a longer test name.
