### ISSUE TITLE
Themes: magic search blocks typing on IE11 bug

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#12186]
![cap-](https://cloud.githubusercontent.com/assets/4389/23964108/432c5070-09ab-11e7-83f3-8334a26c174b.gif)

When typing on IE11, the input receive just a few keystrokes only if typed really really fast.
It's not very evident from the GIF, you should see characters appearing and getting instantly deleted.

### To reproduce

1. In IE11, open `/design` in development environment (with magic search enabled)
2. Try to type in the search box: keys will be eaten.

**Comment by designsimply** [comment]
Tested and confirmed using IE11 Win7 via BrowserStack while logged out: [47s](https://cloudup.com/cvRYO5HSi5i).
