### ISSUE TITLE
Happychat: shows no indication there is a problem when the happychat connection goes down

### ISSUE THREAD

**Issue by beaucollins** [Automattic/wp-calypso#12183]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/help/contact
2. Open a chat with happychat
3. Turn off network connection

#### What I expected

Feedback of some kind that something was wrong with my chat.

#### What happened instead

It appeared as though nothing was wrong until I tried to type a message and it just disappeared.

**Comment by jordwest** [comment]
A PR to solve this is ready for review: #12219

**Comment by mattwondra** [comment]
This has been fixed by https://github.com/Automattic/wp-calypso/issues/12706 and https://github.com/Automattic/wp-calypso/issues/12754. Closing.
