### ISSUE TITLE
Settings > Security: Spam filtering

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#12195]
Convert spam filtering card to have foldable card and an api field.

![jp_calypso_security_spam_filtering3](https://cloud.githubusercontent.com/assets/22752103/23966871/508e091a-0993-11e7-9160-15024e3ec5e7.jpg)

* remove the current comment count option in favor of just turning it on for everyone
* API key should be filled in by default
* If the field is updated, the user will need to select the 'Save Settings' button to save their changes
* By default this card should be collapsed; See the Jetpack plugin Security tab "Prevent brute force login attacks" for a functioning version of the foldable card. (Reference: https://github.com/Automattic/wp-calypso/pull/12105)
* Inside the (i) tooltip: Learn more about spam filtering (link to https://akismet.com)

Cc @MichaelArestad @rickybanister

**Comment by MichaelArestad** [comment]
Related to https://github.com/Automattic/jetpack/issues/6500

**Comment by tyxla** [comment]
This task is being addressed in #12205 by Oscar, so I'm unassigning me and Rocco from this one.
