### ISSUE TITLE
Stats: Variable content in sectionTitle of DatePicker is not localized

### ISSUE THREAD

**Issue by iqatrophie** [Automattic/wp-calypso#12194]
#### Steps to reproduce
1. Go to <a href="https://wordpress.com/me/account">https://wordpress.com/me/account</a> and select "de - Deutsch" for Interface Language.
2. Click the "Save Account Settings" button.
3. Go to https://wordpress.com/stats/day and select a site.
4. Find the "Statistiken für" title and check to see whether the date on the same time is localized.

_(copied from designsimply below)_

#### What I expected
I expected the variable content in the sectionTitle (https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/stats-date-picker/index.jsx#L128) to be localized in the same language as the beginning of the string ("Stats for")

#### What happened instead
The sectionTitle is only partly localized. The first part is localized correctly and reads "_Statistiken für_" in german while the variable content is still in english. 
(see https://translate.wordpress.com/projects/wpcom/de/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=144462&filters%5Btranslation_id%5D=4060121)
Not only are the month names still in english but the date also doesn't follow the usual PHP date format for german. (j. F Y)

#### Browser / OS version
Firefox 52.0 / Ubuntu 16.04.2 LTS

#### Screenshot / Video
![stats-title-date](https://cloud.githubusercontent.com/assets/16153257/23967123/0b8efefc-09be-11e7-8d30-cd58be285285.png)

**Comment by designsimply** [comment]
Tested and confirmed with the following steps:

1. Go to https://wordpress.com/me/account and select "de - Deutsch" for Interface Language.
1. Click the "Save Account Settings" button.
1. Go to https://wordpress.com/stats/day and select a site.
1. Find the "Statistiken für" title and check to see whether the date on the same time is localized.

<strong>Result:</strong>the title on the stats page says "Statistiken für March 15, 2017" which is only partially localized.

![screen shot 2017-03-15 at wed mar 15 4 01 00 pm](https://cloud.githubusercontent.com/assets/1119271/23972764/b8ab965c-0998-11e7-80bd-8dc0c9df2485.png)
<sup>Seen at https://wordpress.com/stats/day/design5279.wordpress.com using Firefox 50.0.1 on Mac OS X 10.12.3.</sup>
