### ISSUE TITLE
People: Allow user to change own role

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#1220]
Currently, when a user views his/her own user information at `/people/edit/$user/$site`, the user does not have the option to change his/her own role.

![screen shot 2](https://cloud.githubusercontent.com/assets/1126811/11548137/01ca3122-991f-11e5-9e3d-aa7ca2e644e5.png)

A user should be able to change his/her own role, as long as it doesn't compromise the site. Ex. - Only admin on site changes role to non-admin. :scream: 

This will also require a change in the endpoint which currently returns an error if a user attempts to change his/her own role. 

__Note:__ After looking at the endpoint for updating a user, we return an error when a user attempts to update his/her own role for WP.com sites, but it looks like that change didn't make it to Jetpack. Let's get that fixed as well. Here's the [method in Jetpack](https://github.com/Automattic/jetpack/blob/master/json-endpoints/class.wpcom-json-api-site-user-endpoint.php#L72) for reference: https://github.com/Automattic/jetpack/blob/master/json-endpoints/class.wpcom-json-api-site-user-endpoint.php#L72

**Comment by beaulebens** [comment]
Similar concept for removing yourself from a blog. As long as it doesn't compromise the site, we should let you remove yourself from a site if you want.

**Comment by Viper007Bond** [comment]
FWIW, WordPress's normal wp-admin area does **not** allow you to change your own role. You have to do it from a different account.

I could see the advantage in being able to demote yourself if you wanted to but we're going to have to unit test the hell out of this on the REST API side of things. I could see a race condition happening for example that allowed two people to de-admin themselves leaving a site with no admins.

**Comment by beaulebens** [comment]
I was going to say that on the list view of users in wp-admin you can change your role, but it looks like it actually catches that after you submit it, and throws an error about "The current user’s role must have user editing capabilities."

**Comment by ebinnion** [comment]
I did notice that a user couldn't change his/her in wp-admin, but @beaulebens pointed out that he could use the bulk edit to change his role.

**Comment by beaulebens** [comment]
@ebinnion note my correction of myself just above. Turns out you can't do it if you're not a super-admin or something. I think for this one, we could just address the issue of being able to remove yourself from a blog (again, only if there's another Admin).

**Comment by ebinnion** [comment]
It looks like core functionality doesn't allow a user to remove their self. It doesn't expose the UI, and when I try to use the bulk selection tool, I see this:

![screen shot 3](https://cloud.githubusercontent.com/assets/1126811/11549717/385a587a-992e-11e5-89c1-bbeac152aaa9.png)

**Comment by beaulebens** [comment]
That definitely makes sense on a single-site, but on somewhere like WP.com (or any other multi-site), I'd think you should be able to.

**Comment by ebinnion** [comment]
That screenshot is from a multisite. The option to remove users is for multisite, while single sites allow deletion.

**Comment by ebinnion** [comment]
I'm going to go ahead and close this as it looks like `wp-admin` doesn't currently allow this functionality. @beaulebens - feel free to re-open if we still need to address this.
