### ISSUE TITLE
Settings: Create "Sharing" tab

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#12214]
**Closed (comp):**
_Defaults closed_
![jp_calypso_sharing_closed](https://cloud.githubusercontent.com/assets/22752103/23974725/285e565a-09b3-11e7-896c-9e06a1727416.jpg)

**Open (comp):**
![jp_calypso_sharing_open](https://cloud.githubusercontent.com/assets/22752103/23974726/2dcaa210-09b3-11e7-9e48-3a4c16b95bc4.jpg)

- Add the content of both blocks from the existing 'Sharing' right-side Calypso menu to a new 'Sharing' tab in 'Settings'
- Keep the 'Publicize' card as a card in the move, place at the top
- Adjust the padding of the foldable card arrow padding in the 'Publicize' card so that the arrows line up with those across the rest of 'Settings'
- Combine both 'Sharing Buttons' cards into one, with one save button and foldable areas, to match comps
_- Remove 'Sharing' right-side Calypso menu item_

Before & after 'Publicize' arrow:
<img width="72" alt="screen shot 2017-03-15 at 7 16 06 pm" src="https://cloud.githubusercontent.com/assets/22752103/23974877/102cef14-09b4-11e7-9671-eab1f52e92b2.png">
<img width="73" alt="screen shot 2017-03-15 at 7 16 20 pm" src="https://cloud.githubusercontent.com/assets/22752103/23974880/144c9d9c-09b4-11e7-959b-e0cad6981617.png">

Cc @MichaelArestad @rickybanister

**Comment by MichaelArestad** [comment]
Previous proposal for reference (same thing) https://github.com/Automattic/wp-calypso/issues/11023

I wouldn't put any of the button options in foldable cards since those are definitely options we want to encourage our users to mess with.

**Comment by ashleighaxios** [comment]
@MichaelArestad 
Oh! I was under the impression this part wasn't worked up already. I'm cool with keeping it open if that's a priority feature to highlight.

The functionality in that area(s) is great, but visually hard to navigate. That's mostly something to be worked out another time, but my baby step to improving that area without doing a complete rework was to have the "Show share buttons" be an option before styling them, changing the order. My  order-of-operations would be to have a simple choice of choosing which areas to display them and then going more granular with appearance options.

Seems like we both agree on one button to save both of those options moving forward (it's two right now).

**Comment by oskosk** [comment]
Closing as it's super old
