### ISSUE TITLE
Themes: Upload not working on Win 7

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#12226]
![at-zip-drop-single](https://cloud.githubusercontent.com/assets/7767559/23993716/92f8265e-0a39-11e7-8dc7-b5d7b9be4144.jpg)

Likely the mime type on Win 7 is not in the [whitelist](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/themes/theme-upload/index.jsx#L159).

To reproduce:
* Windows 7, Chrome, go to wordpress.com/design
* Select a jetpack site
* Click _Upload Theme_
* Drop a theme zip in the box

h/t @ehti

**Comment by ehti** [comment]
Found a similar issue in #11060 which was apparently fixed in #11125 .

I'm still getting this error though - any way to check what MIME type the browser could be sending? I checked via Python, but not sure if this is the accurate way to simulate browser behavior:

>python -m mimetypes oblique.1.02.zip
>**type: application/x-zip-compressed encoding: None**

**Comment by ehti** [comment]
@hoverduck if you have access to a Windows machine, can you try uploading again?

**Comment by seear** [comment]
@ehti use this link to test with https://calypso.live/?branch=fix/themes-upload-win7

You should see the mime type in your browser's JS console when you drop the zip:
`mime type: application/zip`

**Comment by hoverduck** [comment]
I confirmed, using the above Calypso.live link that I was able to upload a theme using Chrome or IE11 on Windows

**Comment by seear** [comment]
Thanks @hoverduck! @ehti If you get a mime type output for your failing case, paste it here.

**Comment by ehti** [comment]
@seear This is odd, but I'm getting an empty output for `mime type:`:

I tried on a different Win7 + Windows 10 machine this time, disabled all extensions and restarted, cleared cache. Chrome:

![at2](https://cloud.githubusercontent.com/assets/6505293/23999979/c60b487c-0a7b-11e7-8893-16403e9f3e18.gif)

**Comment by seear** [comment]
Interesting. Files picked in @ehti's browser have an empty `type`:
![pasted image at 2017_03_16 07_39 pm](https://cloud.githubusercontent.com/assets/7767559/24003356/2029f3c4-0a5b-11e7-810c-262df29efa50.png)

**Comment by seear** [comment]
Interesting. Files picked in @ehti's browser have an empty type:
![pasted image at 2017_03_16 07_39 pm](https://cloud.githubusercontent.com/assets/7767559/24040524/80c031e8-0b01-11e7-9a9e-2c827ace1e69.png)
