### ISSUE TITLE
Editor: lost blog post content

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#12246]
Note that quite a few WordPress.com users have reported cases of lost content over time, and it is difficult to reproduce this problem reliably. Because lost content is a severe pain point for any user, I am raising this issue as high priority.

(Internal refs: p2EDhh-dN-p2 /hat tip @SiobhyB and p4TIVU-3GA=p2 /hat tip @alisterscott)

Steps to reproduce:

1. Go to https://wordpress.com/posts and switch to a site if prompted.
1. Click Edit for an existing post with an unsaved change.
1. Click the "Don't restore" button.
1. _Before_ the post finishes loading, go to Post Settings > Categories & Tags, add a category, and click the "Update" button.
1. Click the "View Post" link and check to see if the content is still present.
1. Refresh the post in the Editor and check to see if the content is still present.
1. Check Post Settings > Status > Revisions to see what the latest revision shows and whether the post content is still available in a previous revision.

<strong>Result:</strong> the post content has disappeared but is available in recent revisions.

<strong>Video:</strong> [1m6s](https://cloudup.com/cgxShFUYqW0)

![screen shot 2017-03-16 at thu mar 16 1 09 44 pm](https://cloud.githubusercontent.com/assets/1119271/24015427/0ea5d62a-0a4e-11e7-9685-75ee5e5a4546.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/revision.php?revision=10582 using Firefox 52.0 on Mac OS X 10.12.3 logged in as design5279 unproxied.</sup>

Maybe we could prevent this problem by ignoring saving a completely blank revision for a post with previously existing content? This would err on the side of saving content even in cases where a user may intend to save a blank page (which I think would be more rare anyway).

#manual-testing #user-report #anxiety #stresscase #painpoint

**Comment by timmyc** [comment]
Curious, could this bug be prevented by disabling the UPDATE button while the post is still loading?  Regardless, we shouldn't allow an UPDATE operation if the latest version of the post isn't loaded from the API.

**Comment by timmyc** [comment]
Previous fix #6058

**Comment by timmyc** [comment]
Looking at the logic, it appears the UPDATE button should be disabled while the post is still loading.
