### ISSUE TITLE
Posts: "Loading Posts…" font color match with background > can't read

### ISSUE THREAD

**Issue by ossvn** [Automattic/wp-calypso#1225]
Today when I use Calypso at slow wifi, I noticed this

https://drive.google.com/file/d/0B8UOXVuC3IIeV0Y0T2ZPbWJGSWc/view?usp=drivesdk

The notice is showing but match with background color so I can't read it, I have to select all (Cmd + A) to see it.

Just a small bug, but I think it should be fixed!

**Comment by designsimply** [comment]
Adding the image inline for reference:

![screen shot 2015-12-03 at 4 29 10 pm](https://cloud.githubusercontent.com/assets/1119271/11560842/5fc3e9b8-9991-11e5-9cb6-4c66d1063bcb.png)

**Comment by montogeek** [comment]
Hi! How should it look?

When removing 2 CSS styles it looks like this:
![screen shot 2016-01-26 at 19 58 14](https://cloud.githubusercontent.com/assets/1002461/12600420/a29f4b64-c467-11e5-8db6-611e5b1303f9.png)

Either is possible to remove the placeholder text leaving only the grid boxes or change the styles to show the text.

I can help with that :)

**Comment by sendilkumarn** [comment]
#4727

**Comment by designsimply** [comment]
Closing because the loading posts text is not meant to be visible.

Thank you for raising the issue to check though!
