### ISSUE TITLE
Site Settings: SEO banners don't immediately consider site visibility

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#12264]
As @roccotripaldi reported in https://github.com/Automattic/wp-calypso/pull/11788#pullrequestreview-26841065, the SEO settings are not immediately aware of changes in site visibility. Here is the original report:

> When testing the Traffic tab, I forgot that my site was "Private", and I was prompted to make it "Public" before using SEO settings, which linked to General Settings tab. But after changing it to "Public", the Traffic tab did not become aware of the change until I refreshed the page.

**Comment by vindl** [comment]
@tyxla I've tested this while working on https://github.com/Automattic/wp-calypso/issues/13049 and couldn't reproduce it.

**Comment by tyxla** [comment]
@vindl I've just tested, and couldn't reproduce either. 

@roccotripaldi could you quickly try to reproduce it again? If you are unable to, I'd suggest that we close this one.
