### ISSUE TITLE
Plugin Browser header color

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#1226]
After the change of the background color, the section headers of the plugin browser are now kind of merged with the background.

This is how it used to look:
![image](https://cloud.githubusercontent.com/assets/1554855/11557207/d29c6bbc-99ab-11e5-9c2c-8450666aba0b.png)

And this is how it looks now:
![image](https://cloud.githubusercontent.com/assets/1554855/11557198/c870e384-99ab-11e5-8f41-ef59f7005045.png)

**Comment by mtias** [comment]
Should use `SectionHeader` :)
