### ISSUE TITLE
Site Settings: Add redirects for legacy SEO and Analytics routes?

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#12263]
In https://github.com/Automattic/wp-calypso/pull/11788 we introduced the Traffic tab, which removed the SEO and Analytics tab from Settings. The new tab can be found at `/settings/traffic`, while the old ones (`/settings/seo` and `settings/analytics` will no longer work).

There was a discussion in https://github.com/Automattic/wp-calypso/pull/11788 about whether we should add redirects to support the old routes. 

It's worth to mention that the support documents that contained the legacy links have already been updated - see p2rHU0-Av-p2 for more information.

My opinion is that we don't need these redirects, and I think @dmsnell and @MichaelArestad align with that, while @oskosk might have a different opinion on this. 

Let's continue that discussion here, cc @rickybanister @ashleighaxios too

**Comment by oskosk** [comment]
Nope. I have the same opinion as everyone else :P. Thanks for your work on this

**Comment by tyxla** [comment]
Thanks for confirming @oskosk. Does anyone disagree that we don't need redirects to support the old routes?

**Comment by beaulebens** [comment]
Unless it's really difficult for some reason, I don't know why we _wouldn't_ have redirects.

**Comment by kriskarkoski** [comment]
I agree with Beau, unless there is a technical reason not to do it I think we need these anytime we change a URL structure as we often link directly to these settings for users that they may reference indefinitely and now suddenly no longer work.

**Comment by dougaitken** [comment]
In addition to Kris' comment, currently the `settings/seo` page draws a blank, no reason what has happened for the user. 

I don't think this is intuitive, the user has to think to click on "My Sites" then go back to Settings, then realise that `Traffic` is now the combined page.

**Comment by tyxla** [comment]
Thanks for the opinions y'all, I've addressed this in #12309 - feel free to test and review it.

**Comment by tyxla** [comment]
Also, I've open a PR to update those in Jetpack - https://github.com/Automattic/jetpack/pull/6692.
