### ISSUE TITLE
Site Settings: Analytics upgrade banner and analytics settings are displayed together

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#12265]
As @MichaelArestad mentioned in https://github.com/Automattic/wp-calypso/pull/11788#issuecomment-287114151, there are cases when both the upgrade banner and the Analytics settings appear at the same time, which doesn't make much sense. 

Two things might be happening here:
1. The upgrade banner is not obtaining real-time the data about the user's plan
2. The Analytics settings card is not obtaining real-time the data about the user's plan, or we should just hide the settings if the plan does not support them.

Thoughts?

**Comment by MichaelArestad** [comment]
@tyxla The Google Analytics section currently looks like this in JP":
![image](https://cloud.githubusercontent.com/assets/1123119/24271743/ea865700-0fdf-11e7-9200-ccc682f65301.png)

Which means we shouldn't show the settings unless the plan supports the feature. We should, however, keep the section header above the banner.

**Comment by tyxla** [comment]
This one is being addressed in #13050.
