### ISSUE TITLE
Editor: Not able to edit passwords on password protected posts

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#12276]
It's not possible to edit passwords on password protected posts.

#### Steps to reproduce

1. Starting at: https://wordpress.com/post/
2. Publish a new post and, under the editor's Status module, edit the post's visibility so that it's password protected.
3. Navigate back to the editor for your newly published post.
4. Attempt to backspace over/edit the post's password.

#### What I expected

I expected to be able to edit the password after clicking/typing into the password field.

#### What happened instead

It wasn't possible to edit the password after typing straight into the field. 

I needed to toggle to "Public" and then back to "Password Protected" in order to be able to edit/change the password:

#### Browser / OS version

Chrome / macOS Sierra 10.12.3

#### Screenshot / Video

![password](https://cloud.githubusercontent.com/assets/2998162/24048546/1dbe6ab8-0b21-11e7-8482-4924015a342b.gif)

#### Context / Source

Reported in 249921-hc

#user-report #reallife

**Comment by SiobhyB** [comment]
This was also raised in wp.me/p7DVsv-1Z2-p2.

**Comment by timmyc** [comment]
Seems that setting a password is broken all together.  I can not set a password on a new post myself.

**Comment by timmyc** [comment]
Definitely looking like a regression from the work done in #11536 - the password field is grabbing its value from the `savedPost` prop, which only contains the last password persisted to the API - not any local edits.  The `post` prop is the edits from the redux state tree, but updating the password is currently setting the value in the old flux post-edit-store.

Thinking the best thing to do at this point is move the password tracking to redux.

**Comment by alisterscott** [comment]
> Seems that setting a password is broken all together. I can not set a password on a new post myself.

What do you mean by this @timmyc? We have e2e tests that create password protected posts which are passing. I was able to create a new password protected post just now, but couldn't edit the password as per this report:

![password post](https://cloud.githubusercontent.com/assets/128826/24086004/bb1aeb50-0d52-11e7-8d84-c8b16fb048aa.gif)

**Comment by timmyc** [comment]
@alisterscott - the flow that was ( is ) broken until the above PR is merged is if you add a password, and a save happens - then you can no longer edit the password.  So sorry about the miscommunication above, but it still to me felt like I couldn't properly set the password prior to publishing.
