### ISSUE TITLE
Settings: Move AMP from General to Traffic settings

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#12273]
As p6TEKc-HQ-p2 specifies, the AMP card is shown in the Traffic section. However, I also recall that there was some discussion about completely removing the AMP card. 

Let's discuss what we're to do with it: should we move it to the Traffic tab or completely remove it?

/cc @rickybanister @MichaelArestad @ashleighaxios

**Comment by MichaelArestad** [comment]
@tyxla I wasn't aware of the discussion to remove it. What were the main reason to remove it?

**Comment by rickybanister** [comment]
You mean for .com sites? 

It'd be lovely to some day get AMP into Jetpack.

**Comment by tyxla** [comment]
That's the problem - I don't recall where I saw the discussion about removing AMP. I might have had a dream about it - who knows 😆 

And yes @rickybanister, that's only for .com sites.

If we're not removing it, I suppose we'll be moving it to the Traffic tab, as suggested in p6TEKc-HQ-p2? Can anyone confirm that's the case, and I'll spin up a PR for that.

**Comment by rickybanister** [comment]
I can confirm, let's move it to /traffic.

For Jetpack sites (on a longer timeline maybe we can advertise the AMP plugin from there? cc @beaulebens 

And on a longer longer timeline maybe someone will get AMP into Jetpack.

**Comment by beaulebens** [comment]
Yes, some version of AMP still needs to be ported into Jetpack, and I imagine we'd either advertise, or offer control for it from the same place.

**Comment by ashleighaxios** [comment]
After chatting with @rickybanister briefly, I think the MVP for now idea is not to have the AMP card in Calypso, just for Jetpack sites right now. 

Comp:
<img width="735" alt="screen shot 2017-03-20 at 2 19 39 pm" src="https://cloud.githubusercontent.com/assets/22752103/24117756/6f48595c-0d79-11e7-8fb6-00bdb47c4dc7.png">

It will link folks over to https://wordpress.com/plugins/amp

**Comment by tyxla** [comment]
@ashleighaxios @rickybanister I'm a little confused. Let's see if I've understood correctly about what we need to do in Calypso:

* For WordPress.com sites, we'll move the AMP card to the Traffic tab, below the "Related Posts" card.
* For Jetpack sites, show an AMP card that looks like what @ashleighaxios has posted.

Is that correct?

**Comment by rickybanister** [comment]
@tyxla exactly.

Unfortunately we can't integrate AMP into Jetpack at this time, so the first step for users is to go get the AMP plugin. With this design we can at least give them a pathway to getting the same functionality.

**Comment by tyxla** [comment]
Cool, I've opened a new issue for separately tracking the addition of an AMP card for Jetpack sites - #12367. Let's keep this one for moving the WordPress.com-only card to the Traffic section.
