### ISSUE TITLE
Settings: Create Site Stats card under Traffic

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#12272]
As p6TEKc-HQ-p2 specifies, we still need to create a new card for Site Stats in the Traffic section, right under the top SEO card.

**Comment by tyxla** [comment]
cc @MichaelArestad @ashleighaxios @rickybanister to share any thoughts outside what's outlined in p6TEKc-HQ-p2

**Comment by MichaelArestad** [comment]
I think it's going to look something like this: https://github.com/Automattic/jetpack/pull/6691

**Comment by MichaelArestad** [comment]
Currently, it looks like that in JP, but without the section header.

**Comment by tyxla** [comment]
This one is being addressed in #12361.
