### ISSUE TITLE
Site Settings: Make the InfoPopovers Tooltip, not wrap whitespace and use proper alignment according to LTR/RTL. 

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#12278]
Alignment of Popover, and its arrow is failing in some cases

RTL is not being taken in account specifically either. ~In some cases, the auto positioning of the ToolTip works fine but not for all cases, depending on its inner content and the space around it~ (EDIT: the last sentence was inaccurate). 

#### we should: 

1. Replace `position={ 'left' }` statements for `position="left"`
1. Should assign position `left` or `right` properly according to RTL/LTR.
1. Should add CSS rule `white-space: nowrap` for the `InfoPopover` instances (props to @retrofox for this tip). 

##### Incorrect white-space wrapping causing bad positioning

![image](https://cloud.githubusercontent.com/assets/746152/24052155/387dca6e-0b13-11e7-969a-ef528780dcc1.png)

##### Positioning failing for RTL language

![image](https://cloud.githubusercontent.com/assets/746152/24052504/76a6cb32-0b14-11e7-958a-05e54c979c9c.png)

**Comment by sirreal** [comment]
I'd like to break this into several issues. I'll open new issues for the popover positioning and RTL support, and I'd like to propose a fix for the style questions and close this. The RTL and positioning changes are significant enough to be on their own.

OK @oskosk?

**Comment by oskosk** [comment]
Perfect @sirreal ! Thank you.
