### ISSUE TITLE
Reader: Invalidate Feed After Following/Unfollowing

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12285]
Currently, when you follow or unfollow a site, the change is not immediately made to your Followed Sites Stream.

Following or unfollowing a site should invalidate the feed and reload your Reader stream so you can see the change immediately.

**Comment by blowery** [comment]
The trick here is that we remember where you were in the stream by index. If we just invalidate the entire following stream, we'll lose your spot. Maybe that's fine, but it feels a little weird.

**Comment by blowery** [comment]
Cases to consider:

1. You follow or unfollow a site from any stream other than the following stream. We should probably invalidate the following stream and let it rebuild?
2. You follow or unfollow a site from the full post view. If the backing stream is any stream other than the following stream, see 1. If the backing stream _is_ the following stream, see 3.
3. You unfollow a site from the following stream. We should probably treat this like a block and change the cards for that site to a "you unfollowed $unfollowedSite. Undo?" card. When you leave the following stream, we'd remove them from the stream entirely. Maybe have a "yup, i meant to do that" type link too that would remove the cards immediately. 

Where this gets tricky is when you go off splelunking. Suppose the following (heh) path:
1. Start on following. Scroll down a few pages.
2. Open interesting post from followed site
3. Scroll down, see interesting related post from another site
4. Open interesting related post, it's good, hit follow
5. Hit back twice to get back to the following stream

Where should we be now in the folllowing stream? I would assume where you left off in 1, not back at the beginning. Posts from the new interesting site would fill into the stream, but you'd be at the same basic position as when you left.

**Comment by fraying** [comment]
RE: Cases to consider: Totally with you. Want me to mock up a "you unfollowed a site" box/card/thing?

RE: The tricky case. Again, totally with you - that's what _should_ happen. But ... it sounds complicated. If it becomes too hairy, I'd suggest just dropping the user back off at the top of their stream with the newly followed site's posts included in the stream. Why? I just think that's less confusing that dropping the user off in the right place but without the newly followed site's posts included. Make sense?

ALTERNATIVELY: We could consider what I know we've talked about before: using a post to remember where you were instead of pixel position, which would make multiple things better. Thoughts?
