### ISSUE TITLE
Widget: Instagram widget Authorization leads to blank screen

### ISSUE THREAD

**Issue by menakas** [Automattic/wp-calypso#12292]
#### Steps to reproduce
0. Please do this in an incognito window or ensure that you are not already logged into Instagram
1. Starting at URL: https://wordpress.com/customize/ for a test site 
2. Go to Widgets->Sidebar
3. If the Instagram widget is not already present then, Add Instagram Widget, Save and Publish. 
4. Click on Authorize Instagram Access 

#### What I expected
I expected the Instagram login interface to appear

#### What happened instead
I got a blank screen

#### Browser / OS version
Firefox/Windows 10
Chrome/Windows 10

#### Screenshot / Video
![instagram](https://cloud.githubusercontent.com/assets/6427897/24068987/67ba136e-0bc2-11e7-80fa-0968cf37817d.gif)

#### Context / Source
This issue does not appear to be theme-specific, I tried on Obsidian, Penscratch and Edin. Same effect.
Issue appears only if the user is not already logged in into Instagram.

Workaround is to first click on "Try logging into the correct account" link, logging in and then click on Authorize Instagram Access. But it is not intuitive for the user to do this first.

#user-report  (Internal reference: **249807-hc** )

( Internal reference:  Possibily related to trac ticket **6959-wpcom**, **370208-chat** and **370222-chat** )

**Comment by hoverduck** [comment]
Note that this doesn't happen if you use the `/wp-admin/customize.php` link to open the customizer.

**Comment by lancewillett** [comment]
This isn't related to Calypso. Closing.

**Comment by designsimply** [comment]
Moved to 7853-wpcom.

**Comment by designsimply** [comment]
Closed 7853-wpcom as a duplicate. (<em>I think</em>) gh-customization-94 is the proper and most current issue for this.

**Comment by sirbrillig** [comment]
IMO this is actually a Calypso issue since Calypso needs to intercept the button and move the link to be outside the customizer iframe. I created #14137 because the customization repo is no longer maintained.

**Comment by sirbrillig** [comment]
Should be fixed now.
