### ISSUE TITLE
Site Settings: Remove or move down the SEO card

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#12308]
After introducing the new Traffic section, the SEO card doesn't look right where it is, because there are various other non-SEO cards on that section. A discussion started in #12271 about what should be done with it - we can either move it down, or remove it.

Let's continue that discussion here.

cc @rickybanister @MichaelArestad @ashleighaxios

**Comment by tyxla** [comment]
My two cents: I'd totally move that card to the bottom, above the Page Title Structure card.

**Comment by rickybanister** [comment]
The SEO card is meant to be a pre-amble for the SEO settings block (if you don't have a professional plan, you see the SEO upgrade nudge instead). 

I'd agree that for now it's best to simply move that card down above Page Title. If the user does not have a pro plan we can attach the SEO upgrade nudge to that card.

**Comment by tyxla** [comment]
This one is being addressed in #12365.
