### ISSUE TITLE
Framework: Find a way to make moment.js dependency smaller

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#12313]
This is a known issue with moment.js and Webpack builds in different OSS projects. See related issue in Webpack repository: https://github.com/webpack/webpack/issues/3128

Late loading timezones and locales would help immensely.

**Comment by dmsnell** [comment]
I would like to explore extorting some of our libraries and I wonder if we could do this from within `i18n-calypso` so that moment gets [loaded by a `<script>` tag](https://github.com/webpack/webpack/issues/3128#issuecomment-282255947).

loading via the external `<script>` would also improve our cross-app code-sharing (here's looking at you, lodash…)

**Comment by gziolo** [comment]
When I last checked `i18n-calypso` dependencies I noticed that it depends on `moment-timezone` library. It loads 176kb of configuration data: https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json. On the other hand `wp-calypso` depends on `moment` which loads all possible translations.

**Comment by dmsnell** [comment]
also `moment-timezone` [depends on moment](https://github.com/moment/moment-timezone/blob/de5d1f8d17074af873366b2453b442552ddd35e4/package.json#L30) itself.

maybe one of these webpack loaders could help us out by pruning those extra languages and then if/when we initialize `i18n` we could fetch the rest of the files if a non-english language is needed. a first step could be possibly English and no external files or any other language and the full bundle, refining down the line to spilt those bundles out

**Comment by Tug** [comment]
@dmsnell 👍  In Delphin we opted for the webpack solution using the `ContextReplacementPlugin`:  https://github.com/Automattic/delphin/blob/master/webpack.base.config.js#L67
We could bring this easily to wp-calypso I guess.

**Comment by gziolo** [comment]
This list is a way much longer for Calypso. We don't load translations for the default English locale in Calypso. If user changes locale we reload the page because we embed all translations in HTML code. Example: https://widgets.wp.com/languages/calypso/de.js. I'm wondering if we could exclude all moment.js translations at all using Webpack, but load user's actual locale in HTML in a similar fashion. This is how we consume Calypso translations in boot file: https://github.com/Automattic/wp-calypso/blob/master/client/boot/index.js#L67.

**Comment by gziolo** [comment]
@blowery did you fix the way `moment` is handled, can we close it?

**Comment by blowery** [comment]
Yup!
