### ISSUE TITLE
LiveChat: JS error for undefined object

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#12336]
I'm seeing an error on my test account, verified on a "normal" user account, with no special circumstances that I can think of. The only unique thing about this test account is that it has a single site (which is a Jetpack one). Here's what I see:

<img width="421" alt="screen shot 2017-03-20 at 1 36 10 pm" src="https://cloud.githubusercontent.com/assets/108942/24118164/75646c06-0d72-11e7-85ef-3eb5921582b2.png">

It's mentioning "chatbox" and "length of undefined", so my random guess is that there's something trying to look at a list of sites, and it's not finding a list because there's only one site? That is a guess though.

**Comment by mtias** [comment]
This is a known error with olark that's been there for a few weeks. The HG team has said they are removing it soon.

**Comment by designsimply** [comment]
(internal ref: p4TIVU-645-p2) cc @omarjackman
