### ISSUE TITLE
Search: Photo Card: Click to expand, immediately contracts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12333]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/search?q=botany
2. Scroll until you see a Photo Card
3. Pay very close attention and then click the Photo Card

#### What I expected

The Photo Card should expand in place, as usual.

#### What happened instead

The Photo Card expands and then goes back to the default, contracted state in a blink. I tried to capture it in a screen recording but it happens too fast. Even if you don't notice it, you'll notice that you have to click twice to get the Photo Card to expand.

#### Browser / OS version

Both Safari and Chrome, latest.

Note that it does not happen in the Main Following Stream or on Tag pages, only in Search Results. What's different about Search Results?

cc @samouri

**Comment by samouri** [comment]
Investigating.

**Comment by samouri** [comment]
[Fix](https://github.com/Automattic/wp-calypso/issues/12339) should be live now in production.

**Comment by fraying** [comment]
🎉
