### ISSUE TITLE
Editor: Long Site Titles Obscure Notification Options

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#12347]
When publishing a post ( or updating an existing one ) for a site that has a very long name, in a smaller viewport, the notification options are obscured by the sidebar:

<img width="896" alt="edit_post_ _testing_timmmmmmmmmmmmmmmmmmmmmmmmmmmaaaaaaaaaaaaaaaaayaaaaaayyyyyyyyyyaayyyy_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/24127544/aad54f16-0d92-11e7-847b-da062ee63a7d.png">

Because of this, I can not see the option to "View Post" or close the notification.

**Comment by lancewillett** [comment]
Possibly related: https://github.com/Automattic/wp-calypso/issues/12099

**Comment by mtias** [comment]
If someone has the bandwidth, we should try global notices for these.
