### ISSUE TITLE
Editor: @ mentions not showing same results as P2 editor

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#12350]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post (Calypso @ mentions aren't enabled in Production or Staging yet)
2. Start typing "ali" for @alisterscott
3. Clear search and start typing "jord" for @jordwest

#### What I expected

To see @alisterscott and @jordwest (same as P2 editor)

#### What happened instead

Neither results showed until more characters enterered

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

**Calypso:**

![calypso](https://cloud.githubusercontent.com/assets/128826/24134862/b44446d6-0e52-11e7-902c-d699167a44b0.gif)

**P2**

![p2](https://cloud.githubusercontent.com/assets/128826/24134868/ba55b7a8-0e52-11e7-96e2-535223c6089e.gif)

#### Context / Source
 #dogfooding

**Comment by alisterscott** [comment]
@donnapep: I saw you worked on this implementation in #10321, do you know if this is expected behaviour? Do you know when editor mentions will be available in all environments by removing the feature toggle?

**Comment by donnapep** [comment]
@alisterscott Yup, I did. Which P2 is your demo from? If the screenshots are from the same Calypso site and P2 then I would expect them to be the same.

I'm not too sure of the process for deciding when to ship to Production and Staging. How does that usually work?

**Comment by donnapep** [comment]
@alisterscott Actually, I don't see any reason not to enable it for all. The PR is [here](https://github.com/Automattic/wp-calypso/pull/12431).

**Comment by alisterscott** [comment]
> Which P2 is your demo from? If the screenshots are from the same Calypso site and P2 then I would expect them to be the same.

Yes, same P2, different results - it's `softwaretesting`

**Comment by alisterscott** [comment]
One other issue with @ notifications is they didn't trigger emails as they normally would on P2 post editors. 

@donnapep: would you like this raised as a separate issue?

**Comment by donnapep** [comment]
@alisterscott Yes, if notifications aren't sending then that's likely something on the server-side of things. So I'm not sure if that should be logged in Calypso or not?

**Comment by alisterscott** [comment]
@donnapep I retested notifications and they seem to be working from calypso post, so nevermind about that and thanks.

**Comment by donnapep** [comment]
@alisterscott Well that's a relief. :) Thx!
