### ISSUE TITLE
Sharing: post likes setting for Jetpack sites

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12386]
@beaulebens was doing some testing and noticed he could not enable post likes for a Jetpack site in the sharing settings.

WordPress.com site:

![image](https://cloud.githubusercontent.com/assets/437258/24165463/d5c589a2-0e46-11e7-948a-42c40f9576be.png)

Jetpack site:

![image](https://cloud.githubusercontent.com/assets/437258/24165489/e764a116-0e46-11e7-8422-b6d68199c206.png)

For Jetpack sites it should just mention Likes, not reblogs.

related to #12214

**Comment by tyxla** [comment]
A quick research shows that this can happen for Jetpack sites only if the **Likes** module is disabled. Which will happen often, because the Likes module is not activated by default.
Maybe we want to auto-activate it? @jeherve @eliorivero @zinigor.

@beaulebens can you please check if that is the case with your Jetpack site?

**Comment by beaulebens** [comment]
Ah yes, this issue should probably be clarified/re-worded.

The real thing here is that we want to present this UI, _whether the Likes module is active or not_ . If it is _not_ active, and the user checks the box/toggle (indicates they want to show Likes), then we need to activate it, and then save that setting to actually display them.

**Comment by tyxla** [comment]
> The real thing here is that we want to present this UI, whether the Likes module is active or not . If it is not active, and the user checks the box/toggle (indicates they want to show Likes), then we need to activate it, and then save that setting to actually display them.

Sounds good, I'd be happy to work on a solution for that. Perhaps @rickybanister can sketch a quick mockup?

**Comment by rickybanister** [comment]
Can we just use the same design for .com sites and have checking the box activate the module? I don't really see a reason to add another piece of UI to turn on the module prior to allowing likes.

**Comment by beaulebens** [comment]
Yep, agree with Rick, we can just use the existing UI for now. Eventually it should probably be a toggle to be consistent, but checkbox is OK for now.

The only other difference is that for Jetpack sites, there's no "Reblog", so the title should just be "Like" I think, and there would just be the single checkbox, labeled "Show like button"

**Comment by rickybanister** [comment]
Once we get sharing moved over to /settings we can do a second pass on the UI since this is quite old, but I'd rather get everything consolidated nowish.

**Comment by beaulebens** [comment]
#12787 for just the "Reblogs" mention.

**Comment by rickybanister** [comment]
This issue needs a proper mockup of exactly what we want before any dev work happens, hold off until I've updated it.

**Comment by tyxla** [comment]
@rickybanister I'm anxious to get this one done. Could you please let me know if the approach we discussed above (activating the likes module upon enabling the Likes checkbox, no real UI changes except for what @beaulebens suggested for the title for Jetpack sites) is the one we should go with?

**Comment by tyxla** [comment]
In the meantime, I've open #16501 to handle the title change for Jetpack sites - I believe this one is clear enough, cc @beaulebens.

**Comment by tyxla** [comment]
Also #16502 handles an improvement to the preview placeholder, see #9816.

**Comment by tyxla** [comment]
Finally, I've started #16539 to implement auto-activation of the Likes module for Jetpack sites whenever the user enables the setting. @rickybanister @beaulebens - that one could use your feedback as well.

**Comment by rickybanister** [comment]
That approach makes sense to me. When we get around to 'v2' I'll update the design to be a toggle and live with the rest of settings.
