### ISSUE TITLE
Invites: typing an @ symbol should not cause an error

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12394]
When inviting a user to a WordPress.com site you should be able to type an @ symbol before the username (that's how mentions in the editor work. Instead it gives you an invalid email error:

![image](https://cloud.githubusercontent.com/assets/437258/24169657/b360a852-0e54-11e7-9da4-4a3a5d75ce7b.png)

cc @ashleighaxios

**Comment by ebinnion** [comment]
We could change the validation to make this work. That being said, mentions in the editor is an a8c-only feature, right?

**Comment by rickybanister** [comment]
Yes, but Facebook and just about every other service encourage users to type an `@` before typing a username and we're failing all of those users that attempt to follow that behavior.

**Comment by ashleighaxios** [comment]
Behavior wise, I think that we still want the error seen in the screenshot in the instance where anything is directly before the @ symbol, but there is no domain extension (IE: abc@something, 12@gmail). While having it check for a username if it starts with the @ symbol and follows with characters (IE: @namehere, @123) or if it doesn't have the @ symbol or domain extension at all (IE: namehere, 1234).

**Comment by rickybanister** [comment]
The field accepts usernames or emails, so I think in this case we would simply ignore a leading @ symbol and assume it's a username then check to see that that username exists. For email addresses we are only checking their validity as emails, not wether they are connected to existing users (at least not at the moment the form is submitted)
