### ISSUE TITLE
Search: Problem with multi word searches

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12399]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/search
2. Paying close attention to when the results come in, start typing words with spaces in between. I used "one two three" but it can be whatever. Just not gibberish.

#### What I expected

I expected to be able to keep typing while the results changed below.

#### What happened instead

The last few characters of the search term keep disappearing. So when I got to "one two t" and results came in, suddenly the text changed to "one t". If I didn't notice right away and was still typing, it became confused. The more I tried to change the text, the more the page reloads, the more jumbled it becomes.

#### Browser / OS version

Safari and Chrome, Latest macOS.

#### Screenshot / Video

https://cloudup.com/c_vqSUcbX4g

cc @blowery @samouri @gibrown

**Comment by designsimply** [comment]
Other, possibly-related reports of lost characters while typing:

* https://github.com/Automattic/wp-calypso/issues/11526
* https://github.com/Automattic/wp-calypso/issues/11567
