### ISSUE TITLE
Editor: Improve linebreak/typewriter behavior when writing text between paragraphs

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-calypso#12406]
Changes were just deployed to the editor, to change the behavior of what happens when you are writing long posts. Previous behavior would have you often typing very close to the bottom of the screen, and in some cases typing below the screen. 

In the new behavior, the scrollbar hugs the bottom of the screen so long as you are typing near the bottom. It also adds padding near the bottom, so you aren't quite as close to the edge.

An improvement should be made to how we handle linebreaks, and writing text between paragraphs. Here's a video demonstrating the issue:

https://cloudup.com/cTUR3CVAXYu

The behavior should probably be similar to how it works when you're typing near the end. That is:

- always have some bottom padding
- linebreaks should scroll the editor too

Any improvements should be tested against inserting tall media items, like big galleries too.

See also: 

- https://github.com/Automattic/wp-calypso/issues/11996
- https://github.com/Automattic/wp-calypso/pull/12346#issuecomment-288336053

**Comment by jasmussen** [comment]
Something to look at, perhaps in relation to this, or in relation to #11996, there's some iffiness with galleries that are far down on the page. Here's a video:

https://cloudup.com/c5O-rEiJOQh

Specifically, when clicking the space after a gallery, you get scrolled to the top.

**Comment by timmyc** [comment]
Overall scrolling after media is inserted causes unexpected outcomes at times.  I think it is worth giving @aduth's [approach](https://github.com/Automattic/wp-calypso/pull/12346/commits/eae453bfb7713114198f05502fb1bb0fd765bb6b) in the original PR a bit more time to try and figure the flicker issues seen in Safari and the IE11 bug that would cause the scroll to top.

In my testing, his approach handled gallery and image insertion quite well - along with typing in the middle of the document.
