### ISSUE TITLE
Layout problem with Photo Cards in Search Results

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12477]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/search?q=wordless%20wednesday&sort=date
2. Scroll until a Photo Card passes behind the search box

#### What I expected

The photo to end cleanly at the line.

#### What happened instead

<img width="886" alt="screen shot 2017-03-23 at 12 58 56 pm" src="https://cloud.githubusercontent.com/assets/24388/24267947/330edb62-0fc9-11e7-8104-03abaca3cb21.png">

(Note the right side.)

**Comment by samouri** [comment]
fixing in: https://github.com/Automattic/wp-calypso/pull/12478
