### ISSUE TITLE
Receipt date and product name are not translatable in Italian

### ISSUE THREAD

**Issue by StefMattana** [Automattic/wp-calypso#12499]
Following my i18n rotation (Italian) , I found that the receipt confirmation emails for the Plan and domain purchase is partially translated, creating an unprofessional mix of Italian and English: 

<img width="660" alt="8 id receipt half italian half english" src="https://cloud.githubusercontent.com/assets/11662998/24297767/cfb7a854-109b-11e7-8dbd-2901478fee29.png">

@naokomc and I were wondering whether it'd be possible to translate the English text that's not in Italian yet. 

#context #translation #email #payment 
#manual-testing

**Comment by designsimply** [comment]
Similar-ish: #12194
