### ISSUE TITLE
JPC: Add routes for monthly plans

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#12497]
We’d like routes that we can use to automatically add a monthly plan to cart instead of the yearly plans:

- https://wordpress.com/jetpack/connect/personal/monthly
- https://wordpress.com/jetpack/connect/premium/monthly
- https://wordpress.com/jetpack/connect/pro/monthly

These routes should look and work just like the ones _without_ the `monthly` suffix but instead of adding the _yearly_ plan to the user's cart, they should add the respective _monthly_ plan.

cc @bubel

**Comment by sirreal** [comment]
Closing, I believe these routes are implemented.
