### ISSUE TITLE
Reader: Site View: Feeds link to RSS instead of site URL

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12509]
If the Site View page is for a feed, the link on the main title links to the RSS file.

For Example, click on the main title at the top of the page on these pages:
https://wordpress.com/read/feeds/34127595
https://wordpress.com/read/feeds/5055404

I'm pretty sure these used to link to the correct place (the site's main URL). Is this a regression? 

cc @blowery

**Comment by fraying** [comment]
@blowery Is this a new bug, or has this always been the case?

**Comment by blowery** [comment]
Poking at this. I think we're just using the wrong URL.

**Comment by samouri** [comment]
@blowery: do you know where this got introduced/if its a regression? doesn't look like the code changed anytime recently

**Comment by blowery** [comment]
@samouri i think it was pretty old. it just gets swamped for most sites that are jetpack connected as we prefer the site info to the feed info.
