### ISSUE TITLE
Visibility icons not translated in Italian

### ISSUE THREAD

**Issue by StefMattana** [Automattic/wp-calypso#12500]
Following my i18n rotation, I found that on the Visibility option (Page Settings>Status>Visibility), the text are in Italian but the icons are still in English: 

<img width="256" alt="10 visibility icons in english" src="https://cloud.githubusercontent.com/assets/11662998/24298031/b36aef16-109c-11e7-9101-6c02e25c888b.png">

@naokomc suggests it's a bug as according to her All “Private” strings are already translated.

#context #translation #editor #manual-testing

**Comment by rachelmcr** [comment]
#bug-scrub

I confirmed that the post and page editor now displays a visibility dropdown menu with translated options:

![screenshot 2017-11-27 18 40 17](https://user-images.githubusercontent.com/8658164/33283075-a22052ea-d3a2-11e7-9807-a739b7e2b148.png)

Closing as resolved.
