### ISSUE TITLE
“Select background image” (Seleziona l’immagine di sfondo) Customizer display typo

### ISSUE THREAD

**Issue by StefMattana** [Automattic/wp-calypso#12502]
Following my i18n rotation day, I found that when changing the background in the Customizer and selecting an image from the Media Library interface, the pop up window has a typo in it:
<img width="899" alt="11 media library pop up typo" src="https://cloud.githubusercontent.com/assets/11662998/24298339/9c8eea9e-109d-11e7-99c7-81c2de951683.png">
#context #translation #media-library #manual-testing #typo

**Comment by ramonjd** [comment]
The output comes from [esc_js](https://developer.wordpress.org/reference/functions/esc_js/), so I think we have to escape single quotes. I've done this on [translate.wordpress.com](https://translate.wordpress.com/projects/wpcom/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8996&filters%5Btranslation_id%5D=720697).

I'll keep an eye on deployment and let you know when/if we can close this issue. 👍

**Comment by akirk** [comment]
Sorry @ramonjd, I [reverted your change on translate.wordpress.com](https://translate.wordpress.com/projects/wpcom/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8996&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc) and fixed the output escaping.

This is now fixed:
![screen shot 2017-12-19 at 13 54 36](https://user-images.githubusercontent.com/203408/34158071-5592a01c-e4c4-11e7-8db1-8202236a6f98.png)
