### ISSUE TITLE
Editor: spell checker seems to look at user language instead of site language

### ISSUE THREAD

**Issue by koke** [Automattic/wp-calypso#12510]
#### Steps to reproduce
1. Open the editor on an English site, with your account set to Spanish
2. Type some text in English
3. Tap the spell check button

#### What I expected

To spell check in English

#### What happened instead

I guess it spell checked in Spanish

#### Browser / OS version

Safari, macOS 10.12.3

#### Screenshot / Video

![screen shot 2017-03-24 at 17 06 47](https://cloud.githubusercontent.com/assets/8739/24302928/93b3d8be-10b4-11e7-8922-7cacaedf2dbe.png)

#### Context / Source

#dogfooding

**Comment by lancewillett** [comment]
What's the locale set in your desktop OS? Does that make a difference?

**Comment by koke** [comment]
My OS language was set to English
