### ISSUE TITLE
Site settings: Warn users when deleting a site with premium themes

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#1251]
We currently allow users to delete a site with premium themes; we should warn users with premium themes before they delete their site.

cc @folletto

**Comment by kriskarkoski** [comment]
A warning was added when deleting a site with a premium theme, but blocks the cancellation flow without support help. I've created a new issue at #17012 to allow deleting again and included showing a proper warning within it. Closing this issue.
