### ISSUE TITLE
Editor: Settings in sidebar are not fully visible

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#12529]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post or wordpress.com/page
2. Select cog wheel to open post/page settings.
3. Open "Status" to see words running out of screen.

#### What I expected
Settings content to fit in the slideout sidebar.

#### What happened instead
Settings content is only partially visible.

#### Browser / OS version
Originally reported by user on Android/Chrome.
Replicated on iPhone 6S Plus 10.2.1 with Safari and Chrome.

#### Screenshot
![iphone_chrome_pagesettings](https://cloud.githubusercontent.com/assets/11635760/24318243/00395a58-113d-11e7-80f6-f402f926ee64.PNG)

#user-report

**Comment by jasmussen** [comment]
This issue should be fixed as of this morning, in https://github.com/Automattic/wp-calypso/pull/12408/commits/b4398e59756f0a041315d6864e47648157cddbaf. Thanks Jeremy and Victoria!
