### ISSUE TITLE
Reader: comments aren't showing for readers

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#12540]
Comments aren't showing on Reader posts for readers who don't belong to the site.

It looks like this is a regression from #12295 

#### Steps to reproduce
1. Open this WordPress.com blog post as a non-a8c account (https://wordpress.com/read/feeds/24643651/posts/1390350957)
2. Click the comments icom

#### What I expected

To see comments and be able to add comment

#### What happened instead

Cannot see nor add comments

#### Browser / OS version

Safari/Firefox/Chrome OSX

#### Screenshot / Video

![comments](https://cloud.githubusercontent.com/assets/128826/24342908/16debfb6-1307-11e7-910a-cc269f5152d1.gif)

#### Context / Source
#dogfooding

**Comment by drw158** [comment]
Luckily this was behind a feature flag, so no harm should have been done.

**Comment by alisterscott** [comment]
> Luckily this was behind a feature flag, so no harm should have been done.

You would have thought so, but this leaked out and affected all reader users, I think because the components are shared.

More feedback on this happening on the new PR here: #12551
