### ISSUE TITLE
Fullpost View: Galleries: Link to Carousel?

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12558]
When a fullpost includes a gallery, currently, we link each image to its permalink page.

For example, this post includes a gallery: https://wordpress.com/read/feeds/35242705/posts/1392083041

And clicking an image in the gallery goes to the image's permalink page, like this: https://perfectlyirregular.wordpress.com/2017/03/25/my-hk-family/img_1376/

Could we instead link to the lightbox Carousel view, like the original post does? Like this:
https://perfectlyirregular.wordpress.com/2017/03/25/my-hk-family/#jp-carousel-3060

(If we do, we should probably open it in a new tab, too.)

cc @blowery @bluefuton

**Comment by blowery** [comment]
Just to be clear, you want to link to the carousel on the original site, not implement the carousel in the Reader?

**Comment by fraying** [comment]
@blowery Yup! Possible?

**Comment by blowery** [comment]
There's nothing on the HTML of the post that exposes that link. We can go peek at the Jetpack Carousel implementation to see how they're building it...

**Comment by blowery** [comment]
Found it. Should be able to do it.

**Comment by fraying** [comment]
@blowery Sweet! Thanks!
