### ISSUE TITLE
Checkout UI: JavaScript error when special characters used in contact information

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#12559]
Hey, Calypso Team!

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checkout
2. Register a domain.
3. Include a special character in the contact info form for the domain (eg. ä).
4. JavaScript error appears, which makes other fields inaccessible.

#### What happened instead
1. When **State** is filled out with a special character, in this case "ä", there will be a double error to it: 
![checkout-ui-issue-1](https://cloud.githubusercontent.com/assets/12064241/24366999/af35d4ae-1323-11e7-86bb-94a4772d6380.png)
The second one is _rogue_, which should b removed.
2. The double error has a wrapper, which covers all the fields:
![checkout-ui-issu-2](https://cloud.githubusercontent.com/assets/12064241/24367009/b8e5d454-1323-11e7-9ad4-1c5e0013376d.png)

#### Browser / OS version
Google Chrome 57.0 / Windows 10 Pro

#### Screenshot / Video
Screenshots are above in the steps.

#### Context / Source
#reallife #manual-testing

**Comment by klimeryk** [comment]
@kriskorn Thanks for the report - I see the problem too. I'll have a look at it this week 👍 
But please host the images on GitHub directly, so that everyone can see them :) (and won't get deleted when/if that site gets deleted/removed/etc.)

**Comment by kriskorn** [comment]
@klimeryk Thank you very much for the tips. All should be good now. I have replaced the images and added some clarifying steps.
