### ISSUE TITLE
Add "-webkit-font-smoothing: antialiased;" to Reader Stream CSS

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12563]
Now that we've switched to Noto Serif, I was looking into why fonts appear so much thicker/bolder in the Stream than on Fullpost. I think it's because Fullpost includes "-webkit-font-smoothing: antialiased;" and the stream does not.

Let's add "-webkit-font-smoothing: antialiased;" to the Reader Stream as well.

**Comment by blowery** [comment]
Interesting. What's the rest of Calypso use? Should this be a Calypso-wide change?

**Comment by fraying** [comment]
@blowery Perhaps. But let's start with the Reader Stream?

**Comment by blowery** [comment]
sure sure
