### ISSUE TITLE
Reader: Weird Results in Search 

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12576]
I'm seeing results like this in search when sorted by date (https://wordpress.com/read/search?q=news&sort=date):

<img width="788" alt="screen shot 2017-03-27 at 6 19 52 pm" src="https://cloud.githubusercontent.com/assets/24388/24384856/9e805dda-131b-11e7-86f9-7249b7b801da.png">

These are the posts in the screenshot:
https://wordpress.com/read/blogs/87782110/posts/633497
https://wordpress.com/read/blogs/87782236/posts/387677
https://wordpress.com/read/blogs/87805141/posts/22692

Is there anything we can do to omit results like this?

Weirdly, they don't even resolve anywhere: 
https://heraldsunatnewscorpau.wordpress.com/uncategorized/%seo_title%/4a76548e1e246a9f3a6e45771726a133/

cc @blowery @gibrown

**Comment by fraying** [comment]
Here's a handy search to find results like this: https://wordpress.com/read/search?q=contentType&sort=date

Anything we can do about this, @blowery @gibrown?

**Comment by blowery** [comment]
I get the feeling those are newscorp... yeah right in the URL. Newscorp is ... weird. I think @gibrown knows more about how they're weird. We may want to just elide those sites from the index.

**Comment by fraying** [comment]
@gibrown What do you think of that idea? ^ https://github.com/Automattic/wp-calypso/issues/12576#issuecomment-298105076

**Comment by gibrown** [comment]
I think these have now all been resolved.
