### ISSUE TITLE
Purchases: Billing History: Duplicate credit cards

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#126]
In the manage credit cards section under Billing History I have four duplicate credit cards. All four are the same card number, name, and expiration date.

Deleting the cards only deletes the individual card, and the duplicates remain.

![image](https://cloud.githubusercontent.com/assets/448298/11250889/b5fe40ee-8dfc-11e5-8509-82d5cb111068.png)

(The last card in the screenshot has the same expiration date but it's not the same card number)

**Comment by breezyskies** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/126

**Comment by breezyskies** [comment]
Never mind, this is specifically for purchases so reopening.

**Comment by gziolo** [comment]
In my opinion it should be closed in favor of #2394, which covers the same issue, plus checkout flow.
