### ISSUE TITLE
Posts: sites don't show image preview in posts list when posting from Aztec editor in mobile apps

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#12609]
This seems to be a regression of #9720 (fixed with #11359). For posts published since a month ago (2-3 weeks?) it seems to have stopped working now.

#### Steps to reproduce
1. With a Jetpack or WP.com site, make sure you have published posts with at least one image (featured image, image in post content).
2. View the posts list at https://wordpress.com/posts/example.com

#### What I expected

For the posts list to show an image for each post.

#### What happened instead

No image. :( This makes it both harder to scan and also seems broken since it doesn't match other environments.

Note: featured images *do* work just fine — this bug report is for posts without a featured image.

#### Screenshot / Video
<img width="1235" alt="screen shot 2017-03-27 at 22 41 19" src="https://cloud.githubusercontent.com/assets/66797/24430384/1b43558e-13cb-11e7-98e1-4bc603e10a59.png">

**Comment by blowery** [comment]
@lancewillett could you add myself and @samouri to lance.blog?

**Comment by blowery** [comment]
@lancewillett i gave myself access. It appears that the images in your posts do not have any size information on them when pulled via the API. No width and height attributes, no data-orig-size attribute, and the images are not attachments on the post. 

How are you making those posts?

**Comment by lancewillett** [comment]
WP Android app.

**Comment by lancewillett** [comment]
@blowery I confirmed on a few other sites that other posting methods do work as expected — so this isn't as bad of a regression as I had thought. Posting from wpcalypso via the editor seems to work just like it was before.

Want me to close as an edge case, or keep it open to find a solution for the Android app flow?

**Comment by lancewillett** [comment]
A bit more details on the app version: using WordPress for Android version alpha-45 with the Aztec editor enabled.

**Comment by blowery** [comment]
Leave it open. There's some hijinks we might be able to pull server side.

**Comment by lancewillett** [comment]
It's possible it's related to the Aztec editor in the Android app: when I switched to "Visual" editor, things worked as expected.

<img width="850" alt="screen shot 2017-03-30 at 15 02 59" src="https://cloud.githubusercontent.com/assets/66797/24528110/fc22cab4-1559-11e7-8877-f32bf44eaa50.png">

<img src="https://cloud.githubusercontent.com/assets/66797/24528129/121de42a-155a-11e7-8432-b96ce561d647.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/24528130/121e561c-155a-11e7-8991-b26cd68b2d93.png" width="480" />

**Comment by lancewillett** [comment]
This seems to be working much better in Calypso's Reader.

<img width="1274" alt="screen shot 2017-07-26 at 09 15 50" src="https://user-images.githubusercontent.com/66797/28631720-0f4a412c-71e3-11e7-944d-f2379b25890a.png">

<img width="1268" alt="screen shot 2017-07-26 at 09 16 01" src="https://user-images.githubusercontent.com/66797/28631726-13badb0e-71e3-11e7-8328-7d73d8caa734.png">

Might still need tracking in Android native app Reader, though:

<img src="https://user-images.githubusercontent.com/66797/28631737-1b8f34c4-71e3-11e7-9ea8-4e97e6b6b7de.png" width="480" />

<img src="https://user-images.githubusercontent.com/66797/28631738-1b9ea67a-71e3-11e7-83a9-07b191fb5d9b.png" width="480" />

**Comment by lancewillett** [comment]
Ah! Closed prematurely. It's not Reader — but the /posts list in question.

**Comment by lancewillett** [comment]
A few more notes, from iOS native app (version 8.1.0.20170724)

- Posts list: images are missing when they appear to be posted via the Aztec editor
- Reader: images are missing (same case)

**Comment by lancewillett** [comment]
Adding another data point, CC @blowery 

**Reader: "image" posts published from WP iOS app are missing images in the Reader stream**

#### Steps to reproduce

1. Starting at this URL: https://paolo.blog/2017/11/27/good-morning-2/
2. Follow the site
3. View the site in Reader, something like this feed: https://wordpress.com/read/feeds/52421555

#### What I expected

After following the blog, and seeing new posts come into Reader, I expected to see an image preview of the photo post.

Especially since this is a photo blog (and I knew he was posting photos from the `#photomattchallenge` project).

#### What happened instead

No images appear in the Reader stream.

Desktop:
![screen shot 2017-11-27 at 14 18 01](https://user-images.githubusercontent.com/66797/33289753-d03b505a-d37d-11e7-938d-1d11dbfd4d52.png)

Mobile:
<img src="https://user-images.githubusercontent.com/66797/33289857-19661d0a-d37e-11e7-971b-dbb479ad6136.PNG" width="480" />

#### Workflow notes

I asked Paolo about his workflow to publish the image posts.

Here are the steps he takes:

1. New post (the + button in the center of the toolbar).
2. Write title
3. Tap in content area, tap + to add media, select photo.
4. Tap "Insert 1"
5. Tap "..." on top right, select "Options"
6. Tap categories, remove "stuff" (default) and set "photos"
7. Back to options
8. Tap tags, select tags
9. Back to options
10. Tap post format, select "image"
11. Back to editor
12. Tap "Publish" (edited)

#### Browser / OS version

Viewing Calypso Reader with Safari 11.0.1 and latest Chrome on OS X 10.13.1

WordPress for iOS app is version 8.9 (latest beta) and using the "Editor: Visual 2.0" setting (which I believe is "Aztec" editor).

Found via real-world usage, following Paolo's blog on my phone and in desktop (both Safari).

#### Mobile issues

See also https://github.com/wordpress-mobile/WordPress-iOS/issues/7613 (now closed).

**Comment by lancewillett** [comment]
Follow-up on the above report from Paolo — turns out it was an RSS setting, not a bug in our image capturing algorithm.

> My RSS feed was indeed set to "summary only". I switched it to "full content" now. My latest post after the RSS settings change shows the photo in the Reader.
