### ISSUE TITLE
Broken Recs Design on Search

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12601]
On Reader Search: https://wordpress.com/read/search

The suggestions that load before you do a search are broken visually. The text is cut off too soon (clipping descenders) and the fade is too high.

<img width="407" alt="screen shot 2017-03-28 at 12 25 36 pm" src="https://cloud.githubusercontent.com/assets/24388/24423477/edbc084a-13b1-11e7-8d08-793ed4e416cd.png">

(Note the fade starting at the right halfway up the first line of the excerpt.)

**Comment by samouri** [comment]
One way of solving this could be to use the same component for both in-stream recs + empty-search-recs.  Should help reduce bugs like this creeping up in the future

**Comment by fraying** [comment]
@samouri I like that idea! One functional difference: The ones in stream have dismiss links, and the ones on Search do not.
