### ISSUE TITLE
Design: Dropdown design, move cursor, saved settings bar inconsistent

### ISSUE THREAD

**Issue by ossvn** [Automattic/wp-calypso#1260]
- Currently, Calypso still use default dropdown corrensponding to each OS (MAC now), I think we should have the design for the dropdown.

Attached Image:
<img width="1440" alt="screen shot 2015-12-04 at 7 52 13 am" src="https://cloud.githubusercontent.com/assets/9199446/11579049/3e1f8be2-9a5d-11e5-9d45-9e218f867cab.png">

- On the menus, the when we hover on each item, we still see the move as pointer, it should be move arrow.

Attached image: <img width="1440" alt="screen shot 2015-12-04 at 7 52 26 am" src="https://cloud.githubusercontent.com/assets/9199446/11579066/673b2716-9a5d-11e5-9edf-94f372421f53.png">

- Also, width of items on menu is not equal to background

On the Settings, when we saved the settings, GREEN BAR appeared but with inconsistant between scrolled down and not scrolled down. Its HEIGHT is not equal to left height of site name and url

Scrolled down: 
<img width="1440" alt="1" src="https://cloud.githubusercontent.com/assets/9199446/11579385/370342d8-9a60-11e5-88f8-34af2688037d.png">

Not scrolled down: 
<img width="1440" alt="2" src="https://cloud.githubusercontent.com/assets/9199446/11579390/3fc91f00-9a60-11e5-9fb2-327ffb9737b7.png">

**Comment by lancewillett** [comment]
Thanks for the feedback, ossvn. 

I think this item: 

> On the menus, the when we hover on each item, we still see the move as pointer, it should be move arrow

is the main actionable item here: can you open a new issue for that one? Label: Menus, Type: Enhancement.
