### ISSUE TITLE
Framework: running make distclean creates deletes public/directly.css in git

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#12618]
I noticed if you run `make distclean` git then shows that `public/directly.css` is deleted.

Running `make dashboard` (or `run`) will resolve this issue.

What is this file for?

<img width="476" alt="screen shot 2017-03-29 at 5 17 37 pm" src="https://cloud.githubusercontent.com/assets/128826/24442921/a831f18e-14a3-11e7-9f95-00d2df0513a4.png">

Also noticed by @markryall

**Comment by alisterscott** [comment]
Should this file not be checked in and ignored maybe?

**Comment by DanReyLop** [comment]
> Should this file not be checked in and ignored maybe?

Correct. The file is generated by the build process and _should_ be ignored. If you are switching branches, have you checked if you have the file ignored in `.gitignore`? It's ignored in `master`: https://github.com/Automattic/wp-calypso/blob/master/.gitignore#L36

**Comment by alisterscott** [comment]
@DanReyLop: it looks like it's checked in https://github.com/Automattic/wp-calypso/blob/master/public/directly.css when it sounds like it shouldn't be

**Comment by alisterscott** [comment]
Being fixed by #12638

**Comment by mattwondra** [comment]
#12638 has been merged & deployed — this issue should be fixed.
