### ISSUE TITLE
Domains: NUX: No back button to the /domains search results from NUX step

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12629]
On the start site or buy domain NUX step there is no way to return to the search results.

This was observed in a recent usability test. The video can be found in p8hwqp-qF-p2

We should add a "back" button.

**Comment by designsimply** [comment]
#user-testing

**Comment by designsimply** [comment]
Screenshot for reference:

<img width="368" alt="screen shot 2017-03-29 at wed mar 29 1 22 25 pm" src="https://cloud.githubusercontent.com/assets/1119271/24472447/f06e9a4a-1482-11e7-8a42-c850db8de0ce.png">
