### ISSUE TITLE
Domains: No indication of "yearly" price in checkout on mobile

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12626]
In a recent usability test on mobile, some users in checkout were confused about the total cost because there is no indication within checkout that the price is yearly. 

![image](https://cloud.githubusercontent.com/assets/12596797/24459966/e1a10e66-146a-11e7-8194-015aebe7b5fa.png)

On >=660 screens this information is communicated in the "cart" sidebar: 
![image](https://cloud.githubusercontent.com/assets/12596797/24460053/1c12ea6a-146b-11e7-8d3d-d58a289b414d.png)

**Comment by designsimply** [comment]
#user-testing
