### ISSUE TITLE
Domains: Green checkmark confused as "selected" in Privacy Protection modal

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12632]
Inside the privacy protection overlay, the green checkmark can be confused to mean "selected". This was observed in a recent usability test. The issue was noticed on a mobile device.

The video can be found in p8hwqp-qF-p2

**Comment by designsimply** [comment]
#user-testing

**Comment by designsimply** [comment]
Screenshot for reference:

<img width="400" alt="screen shot 2017-03-29 at wed mar 29 11 33 33 am" src="https://cloud.githubusercontent.com/assets/1119271/24467950/c02fd09c-1473-11e7-92d5-9a2ecb0d5139.png">

**Comment by danhauk** [comment]
Closing because we don't have this modal anymore.
