### ISSUE TITLE
Question: Can I use calypso interface without using Wordpress.com account

### ISSUE THREAD

**Issue by PrachiThengane** [Automattic/wp-calypso#1263]
I wish to have Calypso admin view for my self hosted site but do not want to use Wordpress.com as middleware.
Can't I directly authenticate my self hosted site?

Could you please provide me Calypso development guide if you have so that I can refer it and make changes?

Thanks.

**Comment by lancewillett** [comment]
Hello there!

Calypso can be used with self-hosted sites by activating the Jetpack plugin and connecting it to WordPress.com. More details here: https://developer.wordpress.com/calypso/

Development guide is here in the code, look for README.md or view all the docs in a web browser with https://github.com/Automattic/wp-calypso/tree/master/docs.

**Comment by coollorenzo** [comment]
Would also love to see a 100% self hosted version of calypso.

**Comment by stucampbell** [comment]
+1 for self-hosted Calypso. We wanted to use self-hosted Wordpress for our internal company blogs - mainly because Calypso provides a very nice blog editing experience. Now I realise that we can't use it because it's not possible for us to have these blogs internet-facing. Nor can we have shadow copies of our private blogs on wordpress.com.

**Comment by josec89** [comment]
I'm a bit confused too, I cloned the repository and I was expecting a single self-hosted site to be there, but I'm asked to create a hosted site in wordpress, which it's not what I intended :/

**Comment by bbertucc** [comment]
@lancewillett - any new plans to support single and multisites that don't use Jetpack? 

If not, perhaps we should fork Calypso to develop a version powered by single or multisites REST API.

**Comment by lancewillett** [comment]
Hi @bbertucc — No changes on the horizon... to use Calypso still requires an active WP.com account and a Jetpack connection.
