### ISSUE TITLE
Reader: Placeholders gone missing

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12642]
It looks like placeholders stopped working. Now, when I click the "New Posts" pill, when the new posts are loading, instead of seeing the nice placeholder state, I see the blank card with "(no title)" at the top. 

Here's a screencap: https://cloudup.com/cxSM8tGeE7J

I've seen this in both Safari and Chrome. I'm pretty sure something changed here in the last 24 hours.

**Comment by blowery** [comment]
@samouri maybe we're missing something in the new fancy post lifecycle?

**Comment by samouri** [comment]
nailed it @blowery! 
deletion of these lines was the issue:
```
 if ( ! post || postState === 'minimal' ) {
    postState = 'pending';
}
```
