### ISSUE TITLE
Editor: Intercept clicks in the white just outside the textarea

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-calypso#1265]
I find that when an editor textarea doesn’t have visually explicit borders, I’m always ever so slightly confused **where** I can click to set focus on the textarea. My brain tells me it’s the whole white area extending to where the first borders appear, but in practice it’s just a column in the middle. In the end I have to hunt with my mouse cursor until it becomes a text caret cursor. 

It would be nice if we could intercept clicks on any part of the larger extended white area around the textarea, and use those to set focus actual textarea. It would be a tiny usability boost that would make it just a millisecond easier to get started typing. 

To clarify: I wish the red areas in this mockup were clickable, and set focus on the green area:

![clickable](https://cloud.githubusercontent.com/assets/1204802/11589943/e4f989de-9a8c-11e5-9c42-0301040adc0b.png)

**Comment by timmyc** [comment]
I poked around a bit at this issue and in-lieu of fixing currently I think it might best be tackled with the move to app-style in the editor.  The current red space above is the `48px` padding applied to the `.editor` wrapper.  So if we add a click listener on that container, it would also pick up clicks in the white space around the title area too.

Somewhat related to this - being able to un`focus` tinymce by clicking on whitespace in the header area would fix a host of issues on mobile safari.

**Comment by brbrr** [comment]
This already fixed.
