### ISSUE TITLE
Sharing: share counts disappear when the domain for a site is changed

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#12652]
Steps to reproduce:

1. Start with a test site using a *.wordpress.com domain.
1. Go to My Sites > Sharing > Sharing Buttons.
1. Add several sharing buttons.
1. Create and publish a post if you don't already have published posts.
1. Open a post on the front end of the site and share it to a few social media services (you may want to use test social media accounts for this).
1. Note the number of share counts showing on the share buttons at the bottom of the post.
1. Add a custom domain to the site.
1. Check the same post again to see if the share counts are still there.

<strong>Result:</strong> share counts disappear when the domain is changed.

![screen shot 2017-03-29 at wed mar 29 6 40 09 pm](https://cloud.githubusercontent.com/assets/1119271/24482549/45cb2a5e-14af-11e7-9445-9d152ba3ac37.png)
<sup>Seen at https://ashevdo.com/2017/03/05/uncomfortable-public-speaking-5tips/ using Safari 10.0.3 on Mac OS X 10.12.3.</sup>

Would it be possible to update sharing counts for a site after the domain has been changed?

Related article: https://www.kayakonlinemarketing.com/blog/preserving-sharing-counts-when-migrating-to-https-or-another-domain

/hat tip @sageBrownell for the #user-report (internal ref: 275200-hc)

**Comment by aduth** [comment]
This is expected and documented behavior:

>If you migrate your content from one URL to another, likes and shares won't automatically migrate.

https://developers.facebook.com/docs/sharing/webmasters/crawler#updating

There are a few workarounds listed which boil down to tricking Facebook's crawler into thinking that the URL hasn't change. Especially in the case of `og:url` meta this can have negative consequences that the updated URL is not respected by other clients or crawlers.

Explicitly targeting Facebook's crawler in an effort to serve the old URL is hack we've attempted before in the case of HTTP -> HTTPS transitions, but in the case of changed domain it's less obvious how to to maintain these shares across potentially multiple domain changes.

For now we've concluded this is a wontfix and would instead delegate responsibility of honoring redirects to Facebook.

Related: https://github.com/Automattic/jetpack/issues/2536
