### ISSUE TITLE
Refactor OAuth login in `client/auth`

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#12668]
https://github.com/Automattic/wp-calypso/pull/12594 has introduced a new native login component (native in the sense that it now lives in calypso rather than served by wpcom). We named it `wp-login` as to not conflict it with the oauth component at `client/oauth/login.jsx`.

Given that we wanted to reuse the `/login` route without introducing too many changes in a single PR, it is necessary to have a follow up PR which will refactor `client/auth`. As stated on the PR, we should:

- Mount the OAuth route on something else than `/login`
- Move the current `client/auth/login` component to another place (section?) or merge it with our new component.
- Test that it doesn't introduce breaking changes on `wp-desktop` which uses this oauth component as its splash screen.

**Comment by scruffian** [comment]
I think we should use a different section as it makes it easier to make exceptions for the OAuth one, which we have a few of...
