### ISSUE TITLE
Themes: can't install themes from WordPress.com on a multisite network

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#12660]
#### Steps to reproduce
0. Start with a mulitisite network where the primary site in the network is connected to WordPress.com, by one of the superadmins on the network.
1. Starting at URL: https://wordpress.com/design/
2. Pick the primary site of the network in the site picker.
3. No WordPress.com themes are available for installation.

#### What I expected

Since my user is a super admin and is allowed to install new themes on the network, I expected to be able to to install WordPress.com themes from the theme selector.

Reported here:
https://jetpack.com/2017/03/16/165-beautiful-free-themes/#comment-21119

**Comment by folletto** [comment]
We currently don't support multi-site installations unfortunately, see #11499.

I guess the bug is that we still show the site in the All Sites list, is that correct?

**Comment by jeherve** [comment]
> I guess the bug is that we still show the site in the All Sites list, is that correct?

No, I think the site should remain the site picker since you can manage other aspects of your Jetpack site on WordPress.com.

I can think of 4 ways to solve this issue:

1. Allow super admins to upload and install themes to the main site of their multisite network install. They are allowed to do that in wp-admin/network/themes.php
2. Allow user admins to upload and install themes to each one of the sites of the network, as long as they have super admin access.
3. We could display the WordPress.com Themes to super admins, but replace the "activate" buttons by the Download option, so folks can still get the themes and upload them manually in wp-admin later on.
4. Maybe we could display a little notice on `design/yoursite.com`, below the list of themes currently installed on the site, like the one we show on `design/yoursite.com/upload`, explaining that WordPress.com themes are not available for Multisite yet?

**Comment by folletto** [comment]
> No, I think the site should remain the site picker since you can manage other aspects of your Jetpack site on WordPress.com.

Yes sorry, I meant the site picker for themes, the dialog that appears on All Sites → Themes when any site action is performed. :) 

> I can think of 4 ways to solve this issue

All sensible solutions. I think the ideal one if there was enough time is to match the access controls and provide the level of functionality they can access. 

> User report: "I have a network install. If I go to the “All Sites” part of the menu I get the ability to access the extra themes but when I try to activate them it gives me a dropdown with only one of the subsites on it and **the activate button does nothing**."

The bug there is that the sites shouldn't show up as we don't support the feature yet. 

The solution however is along the lines you outlined.

It's currently not in the roadmap for themes tho.

**Comment by roccotripaldi** [comment]
699768-zen and 686842-zen are multi-site customers that have shown interest in installing premium themes.

**Comment by jeherve** [comment]
Also reported in #17566

**Comment by rachelmcr** [comment]
Testing and confirmed this is still an issue. This point from #17566 seems particularly important here:

> At the time this restriction was introduced we were only installing free themes so it was kind of harmless, now that premium themes are part of the Professional plan offer, users should be able to use the premium themes in a multisite.

**Comment by folletto** [comment]
For clarity: can anyone check what actually shows up for Multi-Site? 

Because as noted before, if it's just to provide the feature, then it's as it was built, and it's a **Feature Request**. 

If instead it's not showing any message whatsoever and the user is surprised with an error message on multi-sites, then it's a **Bug**, as there should be guidance there (as per #11499).

**Comment by rachelmcr** [comment]
There's currently no message whatsoever. The only themes a user sees are ones installed on the self-hosted site, and there's no explanation why the user can't access/install WordPress.com themes (including the premium themes included in the Jetpack plan) on the multisite:

![screenshot 2018-08-31 12 29 06](https://user-images.githubusercontent.com/8658164/44910063-b0650c00-ad19-11e8-857d-08bc75cc5e77.png)

If I see the Small Business banner at the top of that page, and follow the "See the theme" button, I can open the theme details for that theme. Attempting to activate that theme results in a surprise error message:

![screenshot 2018-08-31 12 30 33](https://user-images.githubusercontent.com/8658164/44910117-e609f500-ad19-11e8-9f07-b188ee26e2fa.png)

**Comment by rachelmcr** [comment]
The only place I do see an appropriate message is if I access https://wordpress.com/themes/upload/ directly and select my multisite (or visit the theme upload screen on another site that supports uploads, and then switching to my multisite). In that case, I see this message:

![screenshot 2018-08-31 12 33 14](https://user-images.githubusercontent.com/8658164/44910219-45680500-ad1a-11e8-9b94-2c9b0cbb5288.png)

However, there's no similar messaging at https://wordpress.com/themes/ for my multisite.

**Comment by folletto** [comment]
Ok thank you for the analysis.

I'd say that in terms of "bug" then this is:

> If I see the Small Business banner at the top of that page, and follow the "See the theme" button, I can open the theme details for that theme. Attempting to activate that theme results in a surprise error message:

The rest is part of implementing the feature. I'd then probably not spit this issue until someone gets to work on it — either way.

**Comment by worldomonation** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. **Report anew**: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. **Reopen**: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
