### ISSUE TITLE
Media: sometimes thumbnails don't appear when images have extra parameters (such as Photon)

### ISSUE THREAD

**Issue by dartiss** [Automattic/wp-calypso#12665]
A VIP client has reported that when viewing media it is not showing thumbnails for JPG images, only PNG images. They are seeing this behaviour in the desktop app, although I can also recreate it in Calypso. The thumbnails appear fine in WP Admin.

In all cases, the JPG images have Photon parameters appended to the end and I believe it is this that is causing the thumbnails to not display.

![e514a9f6-f825-11e6-9152-eb80412da22a](https://cloud.githubusercontent.com/assets/14928971/24510704/de6bf4e8-1561-11e7-9435-0deae584ab41.png)

Here's one that works - https://cnnespanol2.files.wordpress.com/2017/03/170323185759-cnnee-biclicleta-mas-ligera-del-mercado-full-169.png

Here's one that doesn't - https://cnnespanol2.files.wordpress.com/2017/03/170323191305-cnnee-showbiz-diego-verdaguer-full-169.jpg?quality=90&strip=all

Ticket is #62793-z

**Comment by lancewillett** [comment]
CC @ethitter in case you have a second to look at this one.

**Comment by pkevan** [comment]
The issue is with the data being return from the public-api, not Calypso.
