### ISSUE TITLE
Purchases: not able to update / add payment method to purchases that weren't paid with credit card.

### ISSUE THREAD

**Issue by SiR-DanieL** [Automattic/wp-calypso#1266]
Is it normal that I'm not able to edit my payment method for a purchase made using free credits?

The box says "None" but there's no "Edit" link.

**Comment by fabianapsimoes** [comment]
Right now, that's not possible. We plan to revisit that on future iterations on that section.

**Comment by fabianapsimoes** [comment]
This is an issue for all purchases where the Payment Method section displays None. A few cases that come to mind:

- upgrades added manually by staff
- upgrades purchases using credits
- upgrades that for whatever reason do not have a payment method

Another case is allowing users on PayPal to update their payment method to credit card.

**Comment by spncrb** [comment]
Note: PayPal doesn't allow the creation of a subscription without making a payment at the same time.  For this reason, there isn't a plan to allow edit payment method or add payment method to use PayPal.  It will only be an option when renewing now or adding a new purchase.

**Comment by fabianapsimoes** [comment]
This has been fixed in #2169.
