### ISSUE TITLE
Editor: extra alignment classes on images with captions

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#12676]
When adding a left or right aligned image with a caption, the `alignleft`/`alignright` class gets added to both the `<img>` tag, and the `<div>` container.

On themes like Twenty Eleven, this can cause alignment issues, as the caption has a `:before` psuedoelement that moves out of position.

#### Steps to reproduce
1. Starting at URL: WordPress.com/post or WordPress.com/page
2. Click on the **+** to add an image
3. Select and inert the image
4. Click on the image, align it to the  left or right and then add a caption
5. Publish the post and inspect the element - you'll find the alignment class on both the `<img>` and it's container `<div>`
6. Repeat this process using WP Admin instead - only the container `<div>` is given the alignment class

#### What I expected
The containing `<div>` should get the alignment class, but not the image itself (this is the result when adding an image with a caption from WP Admin)

#### What happened instead

Both elements got the class, which can cause floating issues on some themes

#### Screenshot / Video

From Calypso (double alignment tag)
![screen shot 2017-03-30 at 1 43 07 pm](https://cloud.githubusercontent.com/assets/13856531/24518326/8a7e679c-154f-11e7-9887-da4eecb33274.png)

From WP Admin (single alignment tag)
![screen shot 2017-03-30 at 1 46 04 pm](https://cloud.githubusercontent.com/assets/13856531/24518368/b8f3af4c-154f-11e7-9390-c57948ba1e1b.png)

Impact on a site running Twenty Eleven:

![screen shot 2017-03-30 at 1 50 34 pm](https://cloud.githubusercontent.com/assets/13856531/24518502/3214b9d4-1550-11e7-8af8-50849f6e0c7e.png)

#### Context / Source

Original report in the WordPress.com forums:
https://en.forums.wordpress.com/topic/image-caption-glitch

Reporting  user's site:
https://dorchesterindustrialschoolforgirls.wordpress.com/blog/mary-sophia-shaw-dauble/

**Comment by rachelmcr** [comment]
Closing as this behavior will be replaced with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
