### ISSUE TITLE
Magic Login: Integrate with General Login Flow

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#12677]
Native Login landed in dev in #12594. Magic Login landed behind a manually set flag in #12020.
We should work to integrate ML with the general login's components, styling, routes, and data flow, etc.

- [x] Move components to a shared directory
- [x] Initiate state changes via Redux actions.
- [x] Consolidate into the `/login` route (instead of `login/send-me-a-link`, `login/link-was-sent`, etc.) & rely on global state to determine appropriate blocks
- [x] Use "proper" styling for the web app (vs. current styling which appears closer to the desktop app.
- [x] Consider moving the auth `POST` functionality to `wpcom-undocumented` & coordinate with the general auth remote call code to provide the best abstraction.
- [ ] Handle subsequent email clicks when a user is already logged in (If `emailAddress` belongs to `currentUser`, just redirect to `/` (noted [here](https://github.com/Automattic/wp-calypso/pull/12020/files/a62cb2931e9d56f3baa8bc25140b0aa258241545#r108766639))
- [x] Provide a simple mechanism to initiate the ML flow from the login form (e.g. a link at the bottom of the form) -- done in #12678
- [x] Finalize copy -- for example, `Request Email` is confusing [#](https://github.com/Automattic/wp-calypso/pull/12020/files#r108395364) & [#](https://github.com/Automattic/wp-calypso/commit/9d8b03886e04d27f56b7864fa1dc23faa8d32425#commitcomment-21661800). We should probably change that text to `Send Link` as is shown in the mockup below.
- [x] Explore a login flow more inline with the mobile app:
  - Only display the `Username or Email` input on the first step:
    <img width="340" alt="ml-flow0" src="https://cloud.githubusercontent.com/assets/1587282/24519080/033078f4-1552-11e7-845a-d1c1dcf92556.png">
  - Then give the option to request a magic login email vs. entering a password:
    <img width="340" alt="ml-flow1" src="https://cloud.githubusercontent.com/assets/1587282/24519093/0a9b4484-1552-11e7-8648-4f0ddbee650a.png">

**Comment by jblz** [comment]
> Use "proper" styling for the web app (vs. current styling which appears closer to the desktop app.

It turns out we got the background styling for free with the addition of `auth/wp-login/style.scss`, nice!

**Comment by scruffian** [comment]
> It turns out we got the background styling for free with the addition of auth/wp-login/style.scss, nice!

Glad you guys are keeping synced with this work :)

**Comment by scruffian** [comment]
FYI: https://github.com/Automattic/wp-calypso/pull/12690

**Comment by jblz** [comment]
Closing in favor of more discrete issues now that this has moved along a bit.
