### ISSUE TITLE
Editor: tab width in html view

### ISSUE THREAD

**Issue by iqatrophie** [Automattic/wp-calypso#1268]
Hi guys,

I don't know if this has been the same way before Calypso, but I recently noticed that the tab width in *html view* of the editor is **8 space chars** long. This makes reading and creating correctly indented html code very difficult. See my screenshot for further details.

![calypso_editor-htmlview](https://cloud.githubusercontent.com/assets/16153257/11591962/fd417876-9a9b-11e5-8d7e-c9f7154325e2.png)

Since the maximum width for the editor (column) is already very narrow and doesn't make use of the available screen width, I've asked myself if it would be possible to set a tab width of **2 space chars** for better readability?

Something similar has been discussed in issue #558 but within Github context.

**Comment by lancewillett** [comment]
Thanks for sharing this suggestion. I don't have any thoughts to add — but will leave it open in case other folks want to comment.
