### ISSUE TITLE
Purchases: Cancellation email is not translated

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#12699]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Change your profile language to Japanese
3. Go to https://wordpress.com/plans/ and purchase a plan using a credit or debit card
4. Go to https://wordpress.com/me/purchases and cancel the plan you purchased

#### What I expected
To receive a refund email in Japanese.

#### What happened instead
Received the email in English.
When I tried the step 3 using store credit, I didn't receive any email at all.

#### Browser / OS version
Chrome 56.0.2924.87
OS X 10.11.6

#### Screenshot / Video
![image](https://cloud.githubusercontent.com/assets/34067/24560984/041e6af2-1613-11e7-9cc4-2693915e832b.png)

The strings are fully translated since May 2016.
https://translate.wordpress.com/projects/wpcom/ja/default?filters%5Bterm%5D=store-subscription-cancelled.php&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by kriskarkoski** [comment]
A translated email is sent now:

<img width="620" alt="Screen Shot 2020-06-10 at 10 25 19 PM" src="https://user-images.githubusercontent.com/1900444/84338138-4eca0680-ab69-11ea-8800-17d08c663357.png">

Closing.
