### ISSUE TITLE
Reader: <br> tags showing in excerpts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12705]
Many of Upworthy's posts show break tags.

https://wordpress.com/read/feeds/10328216

<img width="848" alt="screen shot 2017-03-31 at 12 01 46 pm" src="https://cloud.githubusercontent.com/assets/24388/24565416/fd9f0140-1609-11e7-8f38-4e020bed1c1a.png">

@blowery, can this be avoided?

cc  @martinremy

**Comment by blowery** [comment]
@fraying they're in the content in the feed, encoded, so ... not really? At least not without something custom just for them.

**Comment by blowery** [comment]
see http://feeds.feedburner.com/upworthy

**Comment by blowery** [comment]
let them know https://twitter.com/blowery/status/847896549078204416

**Comment by fraying** [comment]
Cool, thanks.
