### ISSUE TITLE
Purchase: Duration in the success message is incorrect

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#12701]
#### Steps to reproduce
1. Starting URL: https://wordpress.com/plans
2. Purchase a plan
3. Go to https://wordpress.com/me/purchases and add another year of upgrade

#### What I expected
See a message saying "Success! You renewed XYZ for **a year**, until **March** 31, 2019..."

#### What happened instead
The message said "Success! You renewed XYZ for **a few seconds**, until **Mar** 31, 2019..."

#### Browser / OS version
Chrome 56.0.2924.87
OS X 10.11.6

#### Screenshot / Video
![image](https://cloud.githubusercontent.com/assets/34067/24561613/64a14190-1615-11e7-9adb-122b1a647b96.png)

#### Context / Source
https://github.com/Automattic/wp-calypso/blob/7b93ca870daca2880e1af91928e87b90f6d6403c/client/my-sites/upgrades/checkout/checkout.jsx#L267

**Comment by jeremeylduvall** [comment]
Should be fixed in #13183.
