### ISSUE TITLE
VE Toolbar Scroll not as obvious on Mac

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#12710]
#### Steps to reproduce
1. Go to the calypso editor on Mac and PC
2. Resize screen until toolbars collapse into a scrollable field
3. On PC, you will see a scrollbar
https://cloudup.com/c0yXma7zSi5
![image](https://cloud.githubusercontent.com/assets/16580129/24581491/74549ad0-16ea-11e7-8e1b-d25d085300ee.png)

4. On Mac, you won't unless you hover over

#### What I expected
This feature can be obvious to discover since it presents itself on Macs as soon as the user scrolls over, but I still had a user today who thought their editor was broken because the toggle button was missing.

#### What happened instead
The user could not figure out that the toolbar was scrollable on her Mac since the scroll bar doesn't appear as readily as on PC

#### Browser / OS version
 Screen Resolution: 1280x800
 Browser Size: 953x716
 User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12

#### Screenshot / Video
User sent me this:

![image](https://cloud.githubusercontent.com/assets/16580129/24581487/5fc81704-16ea-11e7-86a7-1caa27353d54.png)
Highlight is mine (user is look for toggle icon)

The toolbar is working as expected, but there doesn't seem to be an initial indicator that it has collapsed into a scrollbar

#### Context / Source
280855-chat
#painpoint #user-report

#### Feature Request
If we could add a scroll bar under the toolbar that gives the user a visual indicator that the toolbar has been consolidated into a scrollable area, this could avoid these fringe cases where the user thinks the toolbar is broken. The editor works like this on PC, it should also do the same for Mac

**Comment by folletto** [comment]
> On Mac, you won't unless you hover over

Small clarification: on Macs with no mouse attached, or with scrollbars set to invisible. Otherwise it works as PCs:

![screen shot 2017-04-03 at 16 10 47](https://cloud.githubusercontent.com/assets/4389/24616154/32a49ec4-1888-11e7-867b-a0e33c6912ab.png)

**Comment by rachelmcr** [comment]
Closing this issue as the TinyMCE toolbar will be replaced with the Gutenberg contextual toolbar.

#bug-scrub #pre-gutenburg-bug-purge
