### ISSUE TITLE
Master bar: Menus automatically expanded if site language is RTL in IE11

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#12726]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/{site URL}. 
2. Set the site language to an RTL language like Hebrew or Arabic
3. View the front end of the site in IE11

#### What I expected
For the master bar to appear as on any other site, i.e. with the different Calypso menus collapsed until clicked.

#### What happened instead
The My Site, Reader, Profile and Notification menus all appeared on the screen at once, obscuring the site underneath. Clicking on the links in the master bar causes the menus to shift left and right, but there appears to be no way to dismiss them. The menus are also not appearing in the correct position.

#### Browser / OS version
Confirmed in IE11 on Windows 7. Does not happen in Chrome or Firefox - there the menus are collapsed as they're supposed to be.

#### Screenshot / Video
![capture](https://cloud.githubusercontent.com/assets/11873759/24605939/34122532-186b-11e7-9281-e14656f901c8.PNG)

This is all that appears in the Console while loading the site:

![capture](https://cloud.githubusercontent.com/assets/11873759/24606454/6afce7ba-186d-11e7-8aa3-1ddbe3a79286.PNG)

#### Context / Source

Reported via the dotcom forums in 846342-f

**Comment by KokkieH** [comment]
User replied again today asking for an update.

**Comment by KokkieH** [comment]
User posted again in 870844-f asking for an update on this.

**Comment by yoavf** [comment]
This should be fixed with D6712-code (needs testing)

**Comment by yoavf** [comment]
Should be fixed. @KokkieH can you please confirm with the user?

**Comment by KokkieH** [comment]
Works for me now in IE11 on Win 7. I asked the user to confirm as well.
