### ISSUE TITLE
Perfect the ReaderSubscriptionListItem Component

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#12752]
The new [Search on Manage](https://github.com/Automattic/wp-calypso/issues/11549) page, and the new Site Results In Search results are both going to use the new component `ReaderSubscriptionListItem`.  It needs to be fairly flexible and support:

- showing/hiding the settings icon/popout depending on which screen you are on
- looking great at all widths
- blavatar/avatar/novatar madness. (if no avatar then still line up the text with the other lines that do have an avatar like we are doing for CombinedCards)
- super long titles/descriptions & lack of any of them

**Site Results in Search:**
![results-w-sites-wide](https://cloud.githubusercontent.com/assets/4656974/24630515/fecd636c-188a-11e7-8b54-04aa90547d57.png)

**Manage Following:**
![manage-following- desktop](https://cloud.githubusercontent.com/assets/4924246/24918661/fd3a6c50-1e95-11e7-936e-433dfaa90c9a.jpg)

**Searching Feeds:**
![manage-following- desktop -keyword](https://cloud.githubusercontent.com/assets/4924246/24918686/10352b60-1e96-11e7-81f4-c2326a38bf88.jpg)

**Comment by samouri** [comment]
I'm running into two issues with what avatar to show in the `SubscriptionListItem:
1. For sites with many authors we may want to not actually show the gravatar.  E.g. Uproxx.  The site owner technically _does_ have a gravatar, but do we want to display that instead of their more iconic blavatar?
2. The `has_avatar` flag has a different status depending on whether we are grabbing it from a post or a site.  e.g. "Math with bad drawings".  The individual post author has no avatar, but the site owner does, whereas in reality both don't.  cc @bluefuton.

Image for demonstration:
![](https://cldup.com/I1CZ6yL6yK.png)

**Comment by fraying** [comment]
@samouri Yeah, it makes sense to show the blavatar if the site has multiple authors. Are we able to determine that here? 

One other note: In the display above, the blog title should be limited to one line (with the usual fade on the right before the Follow link) and the description should be limited to 2 or 3 lines. "By First Last" has moved to the last line, after the description.

**Comment by blowery** [comment]
i think we can use the `single_user_site` property on the site object to determine if there are multiple authors. It's technically all the users, not just those with author rights, but for most things I think that's OK?

**Comment by jancavan** [comment]
> One other note: In the display above, the blog title should be limited to one line (with the usual fade on the right before the Follow link) and the description should be limited to 2 or 3 lines. "By First Last" has moved to the last line, after the description.

I'm working on this in a separate PR: https://github.com/Automattic/wp-calypso/pull/13011

**Comment by samouri** [comment]
The bulk of this is done.  Closing now in favor of specific targeted PRs
