### ISSUE TITLE
Media Library: inconsistent styles for Add button

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#12755]
Some styles are inconsistent with the other Add buttons, because the Media Add button is a form element, not a link element.

Media differences and inconsistencies:

Sidebar item hover style: 
- Button text is light gray
- Button background is light gray

Sidebar button hove style:
- Button has darken border
- no cursor on button **text**

#### Screenshot / Video

![apr-03-2017 15-33-34](https://cloud.githubusercontent.com/assets/618551/24630663/213dbc7e-1883-11e7-87ef-a05dce967bfb.gif)

**Comment by iamtakashi** [comment]
Thanks for the report @drw158! I'll work on a patch shortly.
