### ISSUE TITLE
Reader: displaying HTML entities incorrectly in post titles

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#12774]
When going to https://wordpress.com/read/feeds/23244865/posts/1405185854 the title looks off.
Reader: `Bj&ouml;rk Has Released...`
Actual: `Björk Has Released...`

Reader: 
<img width="1065" alt="screen shot 2017-04-04 at 11 22 44 am" src="https://cloud.githubusercontent.com/assets/4656974/24664602/1b069b2c-1929-11e7-84fe-735724a72b75.png">

Actual site:
<img width="847" alt="screen shot 2017-04-04 at 11 23 25 am" src="https://cloud.githubusercontent.com/assets/4656974/24664615/23ec759a-1929-11e7-9d80-a5de0a64dd98.png">

**Comment by bluefuton** [comment]
We do decode HTML entities in the post title, so I suspect these are double-encoded.
