### ISSUE TITLE
Traffic Settings: GA nudge needs to use new component.

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#12773]
You can see in the screenshot that the nudge at the bottom uses the new component with the purple color, and the GA nudge uses an old component.

#### Screenshot / Video

![screen shot 2017-04-04 at 10 17 31 am](https://cloud.githubusercontent.com/assets/618551/24664353/0f9aab74-1920-11e7-8fe1-ede512601fe3.png)

**Comment by tyxla** [comment]
This one is being handled in #12799.
