### ISSUE TITLE
Editor: notice causing horizontal scroll

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#12778]
Might be because of the new editor

#### Steps to reproduce
1. Starting at URL:wordpress.com/page/[site]
2. Make a new page and hit publish
3. See the green success notice
4. viewport should now have horizontal scrollbars

#### Browser / OS version

Safari Version 10.0.3 

#### Screenshot / Video

![screen shot 2017-04-04 at 11 25 24 am](https://cloud.githubusercontent.com/assets/618551/24667648/cfe6f924-1929-11e7-923a-e6a310cddeb4.png)

**Comment by jasmussen** [comment]
Fixed this in the 👆 PR.
