### ISSUE TITLE
Sharing: Jetpack Pro plan users prompted to downgrade in order to re-Publicize

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#12784]
From 188-gh-jpop-issues

Setting high priority since JP Pro is our highest-paying plan.

Got the prompt when trying to re-share a post, I had to "upgrade" to Premium, despite having a Professional plan. 

![blog_posts_ _amzsuite_blog_ _wordpress_com](https://cloud.githubusercontent.com/assets/2814452/24626440/ebefc5a0-1876-11e7-9aa0-e7b90b1ba257.png)

I verified it on my own test site that has the Professional upgrade - which means this feature is broken for all users with a Professional plan. 

Let me know if you need more information!

cc @csonnek @jeherve

**Comment by lschuyler** [comment]
Two more cases:
3150851-t & 3150919-t

**Comment by csonnek** [comment]
Another: 3156433-t

**Comment by csonnek** [comment]
@artpi - any update on this? This affects every single Jetpack Professional plan user.

**Comment by rickybanister** [comment]
While we're at it, can we make that banner use the appropriate premium plan icon and colors?

**Comment by roccotripaldi** [comment]
I'll be looking into this over the next couple of days.

**Comment by csonnek** [comment]
Replied to all the tickets in this issue letting them know it's been fixed. Thanks!
