### ISSUE TITLE
Site card: show explicit 'visit' button instead of vague hover state

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12781]
Now that the masterbar is available for Jetpack sites it has highlighted the potential difficulty for a Jetpack user running the masterbar on the frontend of their site to navigate in a circular fashion between Calypso and their site. 

The site card as the link to 'get back' to the frontend only has a visual affordance on hover. 

What if we move to using an explicit button that matched the rest of the sidebar:

![](https://cloud.githubusercontent.com/assets/426388/24625531/947ab40e-18af-11e7-8907-aae04ef5566c.png)

This was first proposed in https://github.com/Automattic/jetpack/issues/6877

cc @mtias @shaunandrews

**Comment by drw158** [comment]
Interesting and not as elegant, but much more obvious. I like the idea of using the sidebar button. 

Ideally we wouldn't have to include the view button. I like the simplicity of the user seeing their site name and url, and instinctively knowing to click on it to see the front end. Could probably be helped with some user testing.

**Comment by rickybanister** [comment]
I like that conceptual simplicity too—I worked with @mtias on the current solution. But the reality is no one knows you click that to get to the front-end of their site. It comes up fairly often.

**Comment by drw158** [comment]
Perhaps just the eye icon or external icon? I think translation here will be problematic.

**Comment by drw158** [comment]
Sorry just saw the discussion on the other issue about translation. Still think maybe just an icon would be better.

**Comment by folletto** [comment]
For context: in the original v1 design, it was an explicit item in the sidebar. I think that was the best scenario for visibility. I agree the above could be challenging to translate (i.e. in Italian would be "Visualizza" or "Apri", but the second is "Open"). Adding an icon doesn't seem to me _that_ more explicit than the current situation.

I know @shaunandrews was doing some good explorations... would be interesting of others had ideas to throw in, as this is still one of the hardest bits of the navigation as we currently have.

**Comment by rickybanister** [comment]
Yah, all of these points are well-taken. Let's just use this issue to debate other possible solutions since the current implementation is 'sub-optimal'

**Comment by mtias** [comment]
Can we use the "home" icon inside the button instead of the text "visit" for i18n?

**Comment by sirreal** [comment]
I've created PR #12962 to get the ball rolling.

Note that literally reusing the sidebar button isn't an option as-is, because that would nest `<a>` elements.

**Comment by michaeldcain** [comment]
I don't want to derail any momentum, and think that [Dave's suggestion in #13176](https://github.com/Automattic/wp-calypso/pull/13176#issuecomment-294889962) is a great compromise for an immediate fix, but since @shaunandrews is on vacation, I wanted to note that Delta might be working on some of his suggestions as a v2 to this work, and an iteration to Calypso's site preview, in the nearish future.

![site-preview](https://cloud.githubusercontent.com/assets/942359/25140813/7ca3e28e-242f-11e7-9b16-98cf8ffc945f.gif)

Ref: p3Ex-2fF-p2
