### ISSUE TITLE
Contingency design needed: Feature Gate

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#128]
In Calypso, there comes a time when a user needs to take an action on their personal site, that we are not allowed to take on their behalf, in order to use upgraded functionality.

Case in point: People management will require Jetpack 3.7 in order to function in a complete and proper way. Until such time as the user updates their Jetpack plugin, we need to display a nag UI to prompt them to take the required action.

More examples: "In order to use most of these Jetpack manage features, you need to enable Jetpack manage"

Here's a rough mockup @alternatekev did using components that more or less exist today, with the exception of that fade:

Here's a rough mockup for when we have actual data:

<img width="1080" alt="28ea788a-517a-11e5-8c7c-5c65dd391f7e" src="https://cloud.githubusercontent.com/assets/11487924/11250988/283c3936-8dfd-11e5-91a8-e342c132aa99.png">

Here's another for when we don't have any data to work with yet:

![43b89b8e-5160-11e5-9073-558c590dffe6](https://cloud.githubusercontent.com/assets/11487924/11251054/7fa9611c-8dfd-11e5-95c2-e833ca238646.png)

**Some design discussion**:
Here's the problem as @alternatekev sees it:

- We have a case where we have actual data, but not much, and you can't do anything with it
- We have a case where we have no actual data yet, and want to show a preview of what it looks like when you do

We can use one component for both of these cases if:

- We decide to not show any data for this at all, using basically the "no posts" view
- We decide on one or the other: stacked vs. layered. If we go with layered, we just understand that we are obscuring data that someone may want to actually see. Layered works best for no-data and stacked works best for real-data so we'd be giving up some design quality on one or the other.

Here's some suggested code. You'd write the component something like this:

```jsx
<FeatureGate
        image="/url/to/image.svg"
        h1="My new stuff"
        h2="Is the best"
        >

        <ButtonBar>
                <Button isPrimary={ false } label="My Cool Button" />
                <Button label="My Cool Button" />
        </ButtonBar>

        <GateClip alignTop>
            <MyComponentsGoHere />
        </GateClip>

</FeatureGate>
```

That gateclip component is what will handle the overlay over whatever components you need to display inside.

and the component itself (which needs some logic to check if the props exist yet) looks like this:

```jsx
var React = require( 'react' );

var FeatureGate = React.createClass( {

    getDefaultProps: function() {
        return {
            h1: 'No results',
            h2: 'Yeah we really don\'t have anything for you here',
            image: false,
            alignCenter: false,
            alignTop: true,
        };
    },

    render: function() {
        return (
            <div className="feature-gate">
                <img src={ this.props.image } />
                <h1>{ this.props.h1 }</h1>
                <h2>{ this.props.h2 }</h2>
                { this.props.children }
            </div>
        );
    }
} );

module.exports = FeatureGate;
```

We need this built to accommodate the Calypso-side of the "Jetpack Manage is Not Enabled" flow for Plugins, Menus, and Themes. It's had other uses in the past but those use cases have since been mostly eradicated.

Some design suggestions:
- @MichaelArestad: In your mockup with the gradient, you only show one user. Why not show the author's info there, do the gradient, and show no live data other than the Author's name, etc?
- @rickybanister: I feel like the aesthetic of the page can be the same whether we have mock or real data, but we show 'what we have' behind the overlay.
  - For /stats that would be a fake graph (possibly an image, but perhaps created with mock data and real components) and for /people it can be a real users list. Regarding the length of the list, we can put a max-height: 100vh on the container of the people list or something?
- @rickybanister: We should scope this for proper contrast too. The stats one is kinda hard to read.

**Comment by johnHackworth** [comment]
I'm starting building the backbone of this, using the orginal @alternatekev design. If there's any change over it, I will integrate it in the development

**Comment by rickybanister** [comment]
@johnHackworth implemented this for plugins so any future work should piggy-back on that.

Individual issues can be created for other sections controlled by Jetpack Manage (themes, sharing, etc.)
