### ISSUE TITLE
DevDocs: Reader Related Card no longer showing images

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#12807]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/related-post-cardv2

#### What I expected
To see images like this:
<img width="541" alt="screen shot 2017-04-05 at 8 20 55 am" src="https://cloud.githubusercontent.com/assets/7233112/24705215/ec8c8a9e-19d8-11e7-812e-66cdcf0e05df.png">

#### What happened instead
No images:
<img width="556" alt="screen shot 2017-04-05 at 8 21 04 am" src="https://cloud.githubusercontent.com/assets/7233112/24705224/f303900c-19d8-11e7-871e-8d17f670bc5a.png">

cc: @samouri - https://github.com/Automattic/wp-calypso/pull/12700

#### Browser / OS version
Various

#### Context / Source
#automated-testing

**Comment by samouri** [comment]
this does seem suspicious.  investigating

**Comment by samouri** [comment]
Yep, I changed the RelatedPost to pay attention to canonical_media instead of canonical_image and didn't update the doc which is missing that in its dummy data.  fix will be up shortly
