### ISSUE TITLE
Editor: View Post link on post with unsaved changes link acts as preview

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#12829]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Publish a post
3. View published post link is shown, clicking this and choosing open in new tab shows published post - leave this message visible
4. Make some changes to the post but don't click update
5. Click view published post link again - unpublished changes are shown
6. Open published post in new window
7. A preview of the changes is shown rather than the published post

#### What I expected

If I am using the view post link from publishing a post I expect only to see published changes, not a preview of unpublished changes

#### What happened instead

View post acts as preview post

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

<img width="1110" alt="screen shot 2017-04-05 at 2 13 52 pm" src="https://cloud.githubusercontent.com/assets/128826/24720150/2157de8c-1a0a-11e7-9ebd-c32c9cfbad5c.png">

**Comment by aduth** [comment]
>- View published post link is shown, clicking this and choosing open in new tab shows published post - leave this message visible
>- Make some changes to the post but don't click update

General question: At this point would it make sense for the notice to be auto-dismissed?

cc @jeremeylduvall

**Comment by alisterscott** [comment]
> General question: At this point would it make sense for the notice to be auto-dismissed?

I think it would

**Comment by jeremeylduvall** [comment]
I also think auto-dismissing the notice would be awesome. I generally expect notices to go away after a few seconds anyway. It looks like we might be moving to global notices in the editor soon ([mentioned here and a few other places](https://github.com/Automattic/wp-calypso/issues/12347#issuecomment-288032150)). If so, it might make the most sense to add an auto-dismiss option to the global notice component and use that in the Editor.

**Comment by jeremeylduvall** [comment]
Closed in #13001.
