### ISSUE TITLE
Reader: Thumbnails in Rec Posts don't show up in narrow viewports

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#12822]
Thumbnails aren't displayed and layout is borked:

![screenshot 2017-04-05 09 12 38](https://cloud.githubusercontent.com/assets/4924246/24715401/06f34510-19e0-11e7-9362-029794890cb7.png)

**Comment by fraying** [comment]
I can't reproduce this bug. Search loaded fine for me in Safari and Chrome at minimum width.

**Comment by jancavan** [comment]
@fraying I was able to repro in viewports where there isn't a sidebar. Steps:

1. Visit Reader.
2. Click "Followed Sites" at the top.
3. Click Search.

**Comment by fraying** [comment]
Oh! Confirmed. 

Note: This isn't search RESULTS - those are fine. This is the default Search page with the post recs (https://wordpress.com/read/search).

![screen shot 2017-04-05 at 2 26 41 pm](https://cloud.githubusercontent.com/assets/24388/24727712/e9a5ffbc-1a0b-11e7-901d-b09a92e515e4.png)

**Comment by fraying** [comment]
Oh, lordy. This also hits the More links on Fullpost.

<img width="477" alt="screen shot 2017-04-05 at 2 30 41 pm" src="https://cloud.githubusercontent.com/assets/24388/24727887/87ca6ba6-1a0c-11e7-91e9-f88e4527d404.png">

**Comment by jancavan** [comment]
This is fixed in: https://github.com/Automattic/wp-calypso/pull/12847
