### ISSUE TITLE
Free Trials: Expired trial domain state in domain manager

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#1282]
If we're going to include the domain credit in the free trials, we need to properly handle the state of the domain after the free trial ends in the case the user does _not_ upgrade (we've discussed allowing the domain to be purchased on it's own for a period of time after the free trial ends). 

One place we should look at is how to display the domain in the Domain Manager in this state.

**Comment by breezyskies** [comment]
Proposed design:

![screen shot 2015-12-07 at 8 28 50 am](https://cloud.githubusercontent.com/assets/3011211/11632622/b14536f6-9cbc-11e5-9714-9d76ec9c2e87.png)

- Domain is shown in "disabled" state, does not click through to management details
- Show "free trial ended" error flag on the domain
- Add "purchase" primary button

Note: This design also moves the flags to their own line in domains, similar to what we are doing in Purchases.

cc: @mikeshelton1503

**Comment by fabianapsimoes** [comment]
Should we have the same state in `/purchases`?

**Comment by breezyskies** [comment]
> Should we have the same state in `/purchases`?

@mikeshelton1503 and I have discussed it and we're leaning towards not showing free trials in Purchases. The user hasn't paid for anything yet, so it's not a "purchase" in the standard sense, and none of the functionality there makes sense for a free trial (which would be managed at the "free trial hub" -- see https://github.com/Automattic/wp-calypso/issues/1151#issuecomment-162624443).

**Comment by fabianapsimoes** [comment]
Closing this as we won't offer domains in free trials (p6qnuF-129-p2).
