### ISSUE TITLE
Reader: Card Headers: Grav/Blav spacing differences

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#12825]
In Reader, in card headers, in the main avatar spot, we show a gravatar if we've got one. If we don't, we show a blavatar. 

Looks like there's a 4px spacing inconsistency between the two. When we're showing a Blavatar, the text beside it (byline/timestamp) needs to scoot to the right by about 4px to be in line with the cards with gravatars.

For example:

<img width="537" alt="screen shot 2017-04-05 at 10 21 00 am" src="https://cloud.githubusercontent.com/assets/24388/24718224/1fb86c24-19ea-11e7-9aa2-b7c6cdb5d055.png">

cc @jancavan

**Comment by jancavan** [comment]
@fraying I'm unable to reproduce... or does this only happen if the card with the blav isn't a combined card?

![screenshot 2017-04-06 16 51 45](https://cloud.githubusercontent.com/assets/4924246/24780085/6d4ce474-1ae9-11e7-8e36-748636a98ca7.png)

![screenshot 2017-04-06 16 52 01](https://cloud.githubusercontent.com/assets/4924246/24780093/7c427cbe-1ae9-11e7-9cd8-376ff3e82019.png)

**Comment by fraying** [comment]
@jancavan This bug only affects normal cards (not Combined) that have blavatars. The Combined Cards are correct.
