### ISSUE TITLE
Reader: Filter tab covers long search term

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#12821]
Because these tabs are absolutely positioned, in narrow screens, they sit on top of the search term and I'm unable to see what I'm typing:

![screenshot 2017-03-29 16 00 49](https://cloud.githubusercontent.com/assets/4924246/24715170/659a09b0-19df-11e7-985c-34b0835fed42.png)

**Comment by fraying** [comment]
That seems to be the Calypso-wide way of doing things. Though it would be better if we put a fade there on the right before the toggle.

**Comment by jancavan** [comment]
The same component in Themes: https://cloudup.com/cYlKe_1AsMD

In Reader Search, the tabs are covering what I'm typing (note: I'm still typing until the video ends): https://cloudup.com/c_f5kXbD_IJ

**Comment by fraying** [comment]
Yup. This is probably because we reversed the order of the toggle and the "X" close icon, which we did for a good reason – because the toggle doesn't show up until results show up – but it probably has this bad side effect.

**Comment by jancavan** [comment]
This is still an issue, but I haven't gotten to it yet. Let's keep this open.

**Comment by bluefuton** [comment]
@andfinally suggested in #23069

> The search input's a bit cramped on a 375px viewport - could moving the sort tabs below the input be an option?

![37557942-fa51f2d6-2a03-11e8-90f6-bc9f7e70aa84](https://user-images.githubusercontent.com/17325/43119543-e9e94efe-8f6a-11e8-9cfc-2287698c3b0e.png)

**Comment by Robertght** [comment]
This is still happening.
