### ISSUE TITLE
Masterbar: mobile masterbar doesn't stick when scrolling

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#1283]
In a small viewport, or mobile device, scrolling content also scrolls background content leading to the following behavior:

![scroll](https://cloud.githubusercontent.com/assets/1270189/11599945/831b4f80-9a7e-11e5-86f4-eb36d7a43b83.gif)

To reproduce navigate to:
1. http://calypso.localhost:3000/stats
2. Select a site if prompted
3. Click on the back to your site (you want to see left pane content).
4. Scroll down and continue to scroll until you see the behavior above.
Expected: Header sticks. Ideally background content does not scroll.
Actual: Background content scrolls, and the content behind the pane displays.

cc @rralian can we squeeze this into Iteration 17?

**Comment by rralian** [comment]
> cc @rralian can we squeeze this into Iteration 17?

absolutely

**Comment by rickybanister** [comment]
cc @shaunandrews I close my other report of this as a duplicate.

**Comment by folletto** [comment]
From the other thread: this might be fixed automatically once the masterbar refactoring lands, see #631.
