### ISSUE TITLE
Extensions: WooCommerce: Add support for WooCommerce Product Add-Ons

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#12838]
#### Context / Source

For sites with WooCommerce and WooCommerce Product Add-Ons active, allow the user (merchant) to manage global product add-ons (add, edit, delete) as well as add-ons for individual products (add, edit, delete) and to review buyer-selected add-ons for products in orders.

#### Schedule (Updated 4/17

<img width="1030" alt="screen shot 2017-04-17 at 3 20 52 pm" src="https://cloud.githubusercontent.com/assets/1595739/25106991/8991069c-2381-11e7-9161-5dffde8906a2.png">

^^ cc @toddwilkens @mattyza @kellychoffman @tiagonoronha

**Comment by kellychoffman** [comment]
Going to close all product add-on issues until we have a solid extension plan. We can re-open later.
