### ISSUE TITLE
Settings: Traffic: Stats: show an indicator that stats is active

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12840]
Several modules no longer have an on/off toggle, but it would be nice to show an indicator that they are currently functioning. Stats is one of those.

Let's make it look like this:

![image](https://cloud.githubusercontent.com/assets/437258/24726595/fb1b66c8-1a20-11e7-9974-d387d07f20a6.png)

We can just stick a gridicon in there, make it green, and add `margin-right: 4px;`

**Comment by tyxla** [comment]
This one is being addressed in #12867.
