### ISSUE TITLE
Settings: Traffic: Ads: move ads settings to a new card

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12842]
Currently Ads has its own sidebar item. We would like to split apart the 'earnings' bit, which is more like stats, and the settings bit, which belongs in settings (especially now that we would like to unify WordPress.com and Jetpack settings). 

The ads settings card will go on the Traffic tab and look like this for a Jetpack site:

![image](https://cloud.githubusercontent.com/assets/437258/24726761/8393a6d2-1a21-11e7-89a2-a012379cbfdb.png)

For a WordPress.com site that has applied to WordAds it will look like the above, but may need a few additional options:

![image](https://cloud.githubusercontent.com/assets/437258/24727011/6a5c163a-1a22-11e7-8c9a-535e6e9b0f19.png)

Perhaps @dbspringer can fill me in on the difference between the Jetpack and .com ads settings. 

context: p6TEKc-15K

**Comment by rickybanister** [comment]
cc @ashleighaxios who did the mockup

**Comment by rickybanister** [comment]
- [ ] Also we need to display the correct upgrade banner for Jetpack sites not on the premium or higher plan.

**Comment by tyxla** [comment]
I have a question here @rickybanister @ashleighaxios. As we move ads earnings to Stats and ads settings to Traffic, where do we place the WordAds activation toggle and the approval flow?

**Comment by rickybanister** [comment]
I was imagining the main 'show an ad' toggle would be the activation toggle—Jetpack sites are auto-approved. For WordPress.com sites, this will be the first time they have a flow within Calypso to activate ads. 

I sort of assumed that we would return an error if the person failed to complete the whole form. We can also show a notice to them if they've activated the feature and are waiting approval. 

I think you're asking if instead we should provide an experience more like the 'one-way-activation' here and have folks click a single button to apply for WordAds, then while their application is being processed show a 'we are reviewing your application' message. That makes sense to me and I think we can cobble that together using the non-plan `banner` and a card. 

I can help mock something up.

**Comment by tyxla** [comment]
Yeah, a mockup in the context of the new location of the Ads earnings and settings would be very helpful, thanks. Previously, the activation process was blocking the other screens, while now it will have to be different as we split the settings from the earnings.

**Comment by rickybanister** [comment]
I think we can use something like this:

![unnamed](https://cloud.githubusercontent.com/assets/437258/26367732/9046260e-3fbd-11e7-9eba-157f723645e4.png)

We just need to change the copy. 

We also need a state for a site that has been turned down in the application process—we shouldn't show them the banner taunting them to apply forever. Perhaps we just send them an email letting them know they have been turned down and then hide the banner forever for that site. 

The copy could be something like `Earn money by displaying ads on your site. _Learn more._ [Apply]`

**Comment by ashleighaxios** [comment]
As far as comps, is this what's still missing?

- WordPress.com (non-Jetpack sites) apply for ads screen
- WordPress.com (non-Jetpack sites) awaiting approval screen "Your application is under review"
- WordPress.com (non-Jetpack sites) your application was turned down msg, apply for ads screen

Note that the last one also has the option to reapply for ads. I can't imagine that because a site was once turned down, we would block the site from applying again in the future. (Correct me if I'm wrong) In this case, we might be able to provide some standard context to guide them on a better benchmark for reapplying. IE: "Once your site traffic has reached X, consider reapplying for the opportunity to earn money from the ads on your site." Better yet UX-wise, but not technically, we could remove the section as Rick mentioned and have it appear after that metric has been met with a more simple message "Consider reapplying for the opportunity to earn money from the ads on your site." Not knowing the numbers of applications we reject, I would guess that would be more technically complex than may be worthwhile.

**Comment by tyxla** [comment]
I'd suggest opening multiple issues in this same milestone for tackling all the various changes. This one was supposed to be about moving the ads settings to Traffic settings, but it also includes a bunch of more changes. Creating separate issues for each of the UI/design/functionality/copy changes will also help to avoid missing anything. Does that sound good @rickybanister @ashleighaxios?

**Comment by ashleighaxios** [comment]
@tyxla That works for me – I defer to you on the smoothest development process. I would like to get the outstanding needs clarified. Shall we discuss elsewhere or here?

**Comment by tyxla** [comment]
@ashleighaxios :+1: I think the best way to go here is to create separate issues here in the same milestone for the separate changes, and then we can discuss and address them separately. So, I'd appreciate if you start creating all of the outstanding tasks as separate issues - this really helps organize the development into smaller and more concentrated PRs.

**Comment by beaulebens** [comment]
Just to refresh on the current situation:

There's an "Ads" sidebar item, which has a "Settings" sub-nav, leading to these options:
![screen shot 2018-04-03 at 11 04 52 am](https://user-images.githubusercontent.com/108942/38264097-3b203344-372f-11e8-97a0-a85bf6ab1cf0.png)

Under the top-level "Settings" item, there's a "Traffic" sub-nav, with an "Ads" section that looks like this:
![screen shot 2018-04-03 at 11 04 45 am](https://user-images.githubusercontent.com/108942/38264121-4c27a5be-372f-11e8-96cb-015714e59c1f.png)

**Comment by rickybanister** [comment]
@rclations weren't you taking a look at this? I'm happy to help with any design updates to get all the settings into `/settings` so we can deprecate that Ads sidebar item.
