### ISSUE TITLE
Reader Tags: Wrong event when follow/unfollow tag from Tag page

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#12843]
When clicking "Follow Tag" on the Tag page, the `calypso_reader_reader_tag_unfollowed` is triggered. The opposite should happen. Instead the `calypso_reader_reader_tag_followed` event should be triggered.

The same is true for unfollowing a tag.

Example of unfollowing a tag:

Before: Following a tag, then click Unfollow

<img width="1503" alt="follow_tag_before" src="https://cloud.githubusercontent.com/assets/4505888/24727952/d35f2a02-1a0c-11e7-8ade-4181f3ccbbfd.png">

After: Unfollowed tag but the `tag_followed` event is triggered.

<img width="1503" alt="follow_tag_after" src="https://cloud.githubusercontent.com/assets/4505888/24727954/d6ad7420-1a0c-11e7-9450-5985100951e5.png">

I checked the sidebar tag following, and that works as expected.

**Comment by blowery** [comment]
Oh noooooooooo

**Comment by fraying** [comment]
Facepalming so hard right now.

Thanks for finding this, @aaronyan.
