### ISSUE TITLE
Checkout: Errors when removing item from sidebar cart

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#1286]
> Uncaught TypeError: Cannot read property 'product_name' of undefined

To reproduce:

1. Add an upgrade to your cart for a new site or an existing one. e.g.: visit the plans page for an existing site (https://wordpress.com/plans/example.wordpress.com) and click "Upgrade Now".
2. Click the "x" next to the upgrade in the Checkout page sidebar.
3. The page hangs on a loading screen and errors appear in the console.
4. The error persists upon reloading the Checkout page.

In screenshots:
<img width="802" alt="screen shot 2015-12-04 at 5 50 08 pm" src="https://cloud.githubusercontent.com/assets/2036909/11603456/cd75025c-9aaf-11e5-9b69-40cde0cfdd0e.png">

<img width="1035" alt="screen shot 2015-12-04 at 5 51 14 pm" src="https://cloud.githubusercontent.com/assets/2036909/11603458/d0e09d34-9aaf-11e5-92d5-cf14d91ed25a.png">

<img width="1072" alt="screen shot 2015-12-04 at 5 51 52 pm" src="https://cloud.githubusercontent.com/assets/2036909/11603460/d39dad14-9aaf-11e5-9732-2a25114a5349.png">

**Comment by gziolo** [comment]
I was able to reproduce this one only when I had free credits on my account.
