### ISSUE TITLE
Reader: Long, multiple tags get cropped out in <480px

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#12878]
If there are multiple tags and some of the tags are long, this happens:

![screenshot 2017-04-06 10 06 37](https://cloud.githubusercontent.com/assets/4924246/24766593/c3f18e3a-1ab0-11e7-8fbf-1cd321e12bde.png)

Example:
https://wpcalypso.wordpress.com/read/search?q=landscape

**Comment by fraying** [comment]
Nice catch, @jancavan - thanks.

**Comment by jancavan** [comment]
Could no longer repro. I think this got fixed in an old PR.
