### ISSUE TITLE
Reader: Follow button isn't green for feeds you're already following

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#12886]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Find a post card that comes from an external feed
3. Click on the ellipsis
4. Follow button should be green (Following) since you're already following this site, but it is gray instead (Follow)

![screenshot 2017-04-06 13 39 43](https://cloud.githubusercontent.com/assets/4924246/24774956/ce956752-1acf-11e7-8278-3b299610066a.png)

**Comment by fraying** [comment]
@samouri @bluefuton @blowery - Is this a result of recent redux work?

**Comment by blowery** [comment]
@fraying I don't think so, but it's possible.

**Comment by samouri** [comment]
fixed in https://github.com/Automattic/wp-calypso/pull/12914
