### ISSUE TITLE
Site Settings: Descriptions under toggles should not be clickable

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#12893]
In Site Settings we have several toggles that have descriptions.

![](https://cldup.com/OcnpJUX35A.png)

As @rickybanister noticed yesterday (see https://github.com/Automattic/wp-calypso/pull/12812#issuecomment-292278133 for more info), these descriptions are also clickable, and trigger the toggle. It appears that this has happened because to indent these descriptions we've inserted them in the toggle labels.

**Comment by tyxla** [comment]
This one is being addressed in #12894.

**Comment by rickybanister** [comment]
Thanks for opening a separate issue!
