### ISSUE TITLE
Sharing: Refactor connections data library

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#129]
The current connections data library, found at `client/lib/connections-list`, manages both Keyring and Publicize connections and is modeled using the now-defunct emitter-style data module format. We should seek to refactor this module with the following considerations:
- Keyring and Publicize connections, while very much related, should be managed separately for both data fetching and storing
- The module should be implemented in our current Flux pattern recommendation

It's proposed that the module be split to two separate modules, likely to be found at `client/lib/publicize-connections` and `client/lib/keyring-connections`.

**Comment by danny-wieser** [comment]
@aduth: Trying to get a handle on the overall state of Flux stores in the client/lib folder and this issue came up, but the referenced code no longer exists in master.  I'm guessing this can be closed?

**Comment by aduth** [comment]
@danny-wieser Yep, looks like this is no longer relevant as of #8991.
