### ISSUE TITLE
Reader: Posts with no excerpts but have images should use a Photo card

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#12917]
This post doesn't have an excerpt, but has an image so it should be using a Photo card instead of a Regular card:

![screenshot 2017-04-07 13 37 35](https://cloud.githubusercontent.com/assets/4924246/24819013/b12ba942-1b97-11e7-8caf-5fd3e73961ab.png)

https://wordpress.com/read/blogs/18366195/posts/3312

/cc @bluefuton @samouri

**Comment by blowery** [comment]
hmmm, that images is only 357px wide... I think we cut off at photo only at 440px wide.

**Comment by designsimply** [comment]
https://en.support.wordpress.com/reader/ says:

> Why isn’t my photo being shown?
> Images must be over 350 pixels wide to be usable. If the image on the post is less than 350 pixels, it'll be skipped.

It doesn't say anything specifically about photo cards. Should it?
