### ISSUE TITLE
Settings: Traffic: Stats: add a clickable card that links to /stats?

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#12911]
Many of the 'on all the time' Jetpack modules no longer need a toggle. Stats is one of them. There are a few sub-settings to configure, but it basically just works. To make the settings card for stats more useful it might be nice to follow the pattern of having a clickable card attached to the bottom of the stats card that takes the user to /stats.

Like this:

![image](https://cloud.githubusercontent.com/assets/437258/24812875/d57a648a-1b99-11e7-9e34-d8fe5f535527.png)

I don't want to gunk up /settings, but there are already a handful where we link to other places (view your email followers, view your ads earnings, etc)

Thoughts: @MichaelArestad @mtias @drw158 @beaulebens @johnHackworth @tyxla

**Comment by tyxla** [comment]
That would make total sense for me - that card currently looks a little empty when collapsed anyway. And it would be a good way to direct users to our stats.

**Comment by rickybanister** [comment]
Sounds good @tyxla let's make it so.

**Comment by mtias** [comment]
It'd be interesting to reuse the stat sparkline that is used in the sidebar in the card.

**Comment by rickybanister** [comment]
That could be interesting and something we tossed around, but let's start with baby steps here.

**Comment by mtias** [comment]
Hopefully it's already a drop in component :)

**Comment by tyxla** [comment]
This one is being addressed in #13407.
