### ISSUE TITLE
Notifications: Comments with Ratings Display Polldaddy JS Link

### ISSUE THREAD

**Issue by kevmarsden** [Automattic/wp-calypso#1292]
When comment ratings are enabled (WP Admin > Settings > Ratings > Comments), this link is displayed in comments displayed in the Notification panel.  

https://polldaddy.com/js/rating/rating.js

Here's an example:

![screen shot 2015-12-04 at 4 43 48 pm](https://cloud.githubusercontent.com/assets/2282189/11604865/3e85a09a-9aa7-11e5-965e-b2648426e5bc.png)

Reported in 275738-chat

**Comment by kevmarsden** [comment]
Reported by another WP.com user isn live chat 279837

**Comment by dmsnell** [comment]
cc: @alexjgustafson

**Comment by dmsnell** [comment]
For the record, here is an example of the offending text:

```
<div class="pd-rating" id="pd_rating_holder_[redacted]_comm_33"></div>

<script type="text/javascript" charset="UTF-8">
<!--//--><![CDATA[//><!--
PDRTJS_settings_[redacted]_comm_33={
	"id": [redacted],
	"unique_id": "wp-comment-33",
	"title": "this is a really sweet test comment....",
	"permalink": "[redacted]/#comment-33",
	"item_id": "_comm_33"
};
//--><!]]></script>

<script type="text/javascript" charset="UTF-8" src="https://polldaddy.com/js/rating/rating.js">
</script>

<p>this is a really sweet test comment.</p>

```

**Comment by alexjgustafson** [comment]
Reported by another WP.com user in #2580929-t

**Comment by dmsnell** [comment]
Reported again in #718715-f

**Comment by lancewillett** [comment]
Maybe related to #8491 where JS shows up in post preview for Jetpack sites.

**Comment by catkit** [comment]
Yet another report 497231-c

**Comment by Lostineu** [comment]
Now I've got the same problem on my Wordpress blog, any fix?

**Comment by kwight** [comment]
This was cleaned up at some point; I can comment on a post with Ratings enabled and not see the script in the notification.

<img width="477" alt="Screen Shot 2021-03-19 at 10 47 03 AM" src="https://user-images.githubusercontent.com/349751/111822100-9f148880-88a0-11eb-896c-9d1ffcef9d61.png">
