### ISSUE TITLE
Domains: Email forwarding option appears inconsistently

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#12932]
Currently, the email forwarding experience isn't consistent between various domains pages in Calypso. For example, if you're on a site with a custom domain and you go through the following flow:

**Domains -> (Select Domain) -> Email**

You will wind up on this page:

https://wordpress.com/domains/manage/example.com/email/example.com

You'll see the email forwarding option: 

<img width="964" alt="screen shot 2017-04-08 at 2 57 50 pm" src="https://cloud.githubusercontent.com/assets/7240478/24831998/c20979cc-1c6b-11e7-89cd-eaff3468c1a3.png">

However, if you go through this flow instead:

**Plan -> Email (top menu)** 

You'll wind up on this page:

https://wordpress.com/domains/manage/email/example.com

<img width="957" alt="screen shot 2017-04-08 at 3 01 54 pm" src="https://cloud.githubusercontent.com/assets/7240478/24832016/54b9d9e2-1c6c-11e7-8dcc-41b85f206018.png">

That page only shows the G Suite option (presumably because we don't know which domain you want to add the forwarding to). This feels a bit weird and inconsistent. It seems like the experience should be the same for both flows.

h/t to @melchoyce for bringing this up in Slack (p1491602234103691-slack-automattic)

**Comment by jeremeylduvall** [comment]
This is still an issue IMO and was surfaced again in #19222.

**Comment by klimeryk** [comment]
The Email tab has been removed (around the time we revamped the Domain Management probably). We've also improved the visibility of these options. So this is no longer an issue.
