### ISSUE TITLE
i18n: define process for localizing extensions

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#12935]
Extensions need to be translated separately from the main calypso codebase:
- Most strings already exist in the wp-admin version of the extension
- Extension strings are often specific and require more context and knowledge for translators.
- Just adding all strings to our main string file regardless of if they're being used will create bloat.

Imagining the best solution possible, we'd probably want extensions to define their translate.wordpress.org URL, and download the translations directly from there, without using any wpcom infrastructure. Our translation functions syntax is different from WP's in a few areas, but nothing that can't be normalized in the transfer.

TODOs:

- [x] Disable extensions strings from being added to `calypso-strings.pot`
- [ ] Figure out a process for reusing translations from translate.wordpress.org

**Comment by yoavf** [comment]
Pinging a few people who might have thoughts on this @allendav @ockham @mtias 
It'd be great if we can figure out a plan before we launch popular extensions.

**Comment by allendav** [comment]
cc @gedex

**Comment by DanReyLop** [comment]
@Automattic/store Bump! Since we're going to open Store internationally soon, we should figure out how to translate extensions.

Since all the current extensions are our own and are part of the `wp-calypso` codebase, what about including the `/extensions` folder again for translations? So it follows the same process as the rest of Calypso.

**Comment by yoavf** [comment]
@DanReyLop We could - but that wouldn't solve the points from this issue, which are still painful.
@Automattic/i18n is going to work on this. Eventually, we'd want to have:
- A separate project per extension on translate.wordpress.com
- Automatic import of existing translations (including placeholder substitution) from respective existing wp-admin translations (i.e, import any matching translations from https://translate.wordpress.org/projects/wp-plugins/woocommerce for the store extension)

**Comment by akirk** [comment]
As a first step, for the WooCommerce store extension, I've created https://translate.wordpress.com/projects/wpcom/calypso-extensions/woocommerce/ and imported several projects from translate.wordpress.org (as per the plugins listed on https://github.com/Automattic/wp-calypso/blob/master/client/extensions/woocommerce/README.md) :
- https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev
- https://translate.wordpress.org/projects/wp-plugins/woocommerce-services/dev
- https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe/dev
- https://translate.wordpress.org/projects/wp-plugins/taxjar-simplified-taxes-for-woocommerce/dev

Which gives us already a nice translated percentage. After we have translated them, we should be able to share them back to translate.wordpress.org.
