### ISSUE TITLE
Reader Manage Following: allow ordering of existing subscriptions by name or date

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#12959]
Using a dropdown, allow ordering of existing subscriptions by name or date.

![sort-by-date](https://cloud.githubusercontent.com/assets/4924246/24885971/74767498-1e06-11e7-9465-0e34862af401.jpg)

**Comment by gibrown** [comment]
Assuming we switch to doing this sorting with an ES query, we could also sort these by how recently they posted.

**Comment by jancavan** [comment]
@bluefuton I think this is currently using a regular `<select>` tag. I vaguely remember a GH issue where it was suggested that we use the `SelectDropdown` component.

**Comment by samouri** [comment]
https://github.com/Automattic/wp-calypso/pull/13469

**Comment by samouri** [comment]
this can be closed now
