### ISSUE TITLE
Editor: Trouble previewing images with query parameters

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#12957]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Try inserting the following image: https://fred.stlouisfed.org/graph/fredgraph.png?g=dhOg
3. Even if we use the HTML editor to add an image tag with that as its source, the editor won't display the image, though the image will display in the published post.

#### What I expected
I'd expect to see the image.  I've confirmed the same image works in wp-admin's editor.

#### What happened instead
We see a broken image indicator

#### Browser / OS version
Doesn't matter

#### Screenshot / Video
https://cloudup.com/cvjPR6j1Jm9

#### Context / Source
Support

**Comment by aduth** [comment]
Related: #11239
