### ISSUE TITLE
Reader Manage Following: manage email subscriptions via popout

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#12954]
Email subscriptions are currently managed via a show/hide panel, which is frequently missed in user testing. The refreshed Manage Following has a popout to perform the same functions:

![popover](https://cloud.githubusercontent.com/assets/4924246/24885925/1814f012-1e06-11e7-8c11-04db30274a37.jpg)

**Comment by jancavan** [comment]
The Settings button should not be displayed for:

1. Users that have blocked all email updates in `/me/notifications/subscriptions`
2. RSS feeds

We will no longer display any kind of messaging like we currently do.

/cc @bluefuton @samouri
