### ISSUE TITLE
Reader Manage Following: add recommendations

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#12952]
When the user has not entered a search term, two site recommendations should be shown:

**Wider viewports:**
![manage-following- desktop](https://cloud.githubusercontent.com/assets/4924246/24885804/6162248e-1e05-11e7-9e3b-7cd97a242eb5.jpg)

**Narrow viewports:**
![manage-following- mobile](https://cloud.githubusercontent.com/assets/4924246/24885806/663c489a-1e05-11e7-8f18-adb014e82bda.jpg)

Recommendations should be formatted just like in-stream recommendations. Clicking Follow or Dismiss causes that site to disappear and a new one to appear.

**Comment by fraying** [comment]
Note: @jancavan has an updated design for this.

**Comment by jancavan** [comment]
Working on the mockup for wider screens. I'll update the description shortly.

**Comment by samouri** [comment]
What should happen when you search your already subbed items?
do the recs stay?

**Comment by fraying** [comment]
When you filter your followed sites, the recs should stay in place, as they're connected to the "follow something new" form above.

**Comment by samouri** [comment]
Currently three PRs open that will complete this:
1. https://github.com/Automattic/wp-calypso/pull/13394
2. https://github.com/Automattic/wp-calypso/pull/13472 
3. https://github.com/Automattic/wp-calypso/pull/13396
