### ISSUE TITLE
Reader Manage Following: follow by URL

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#12950]
As part of Manage Following's refresh, we're improving the experience of following by URL.

**Default state (Desktop/wider screens):**
![manage-following- desktop](https://cloud.githubusercontent.com/assets/4924246/24885678/b4f0b512-1e04-11e7-8312-a5d61949d0db.jpg)

**Default state (Mobile):**
![manage-following- mobile](https://cloud.githubusercontent.com/assets/4924246/24883956/17d9ce1a-1dfc-11e7-9c3a-c824b295f495.jpg)

**If a user enters a URL:**
![manage-following- desktop -url](https://cloud.githubusercontent.com/assets/4924246/24885782/48354c84-1e05-11e7-9cdd-75fcd1c7777a.jpg)

- When text is entered, the recommendations disappear.
- There may be a brief state when the user is entering text before they get to “.com” (or any other TLD) where text search results are displayed. That’s okay!
- When the form detects a valid URL, the user can hit return or click the link to follow the site.
- Unfollowable URLs produce the red error box as now.
- Clicking the “X” clears the form and the recommendations return.

**Comment by blowery** [comment]
I think it would be better to show the search results and put the direct follow link above them perhaps? If I put in `gawker.com`, it's nice to be able to see the search results, in addition to the single follow button which may not work...

**Comment by fraying** [comment]
If you searched for "gawker.com," how are these three results helpful?

<img width="758" alt="screen shot 2017-05-05 at 10 05 17 am" src="https://cloud.githubusercontent.com/assets/24388/25756117/7399c12e-317a-11e7-8fd8-f681263be4a2.png">

**Comment by blowery** [comment]
obviously the search needs to be better. :)

**Comment by fraying** [comment]
Obvs. ;-)

I'm open to exploring it, design-wise, but for v1 I'd like to stick to the spec.
