### ISSUE TITLE
Plugins: Settings link for Jetpack should not point to wp-admin

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#12968]
On a Jetpack site, go to the Plugins view, then click through to the Jetpack plugin itself. We recently added the functionality that Calypso understands links which the plugin adds within wp-admin, and it exposes them on this page:

![jetpack_by_wordpress_com_plugin_ _dented_reality_ _wordpress_com](https://cloud.githubusercontent.com/assets/108942/24879603/ab86d49e-1df4-11e7-8f73-bdc6c3d26596.png)

Since Jetpack now has most/all of its settings available via Calypso directly, we should change this link and point it to `/settings/general` for the current site, rather than wp-admin.

cc @rickybanister to make sure that makes sense, and @rralian RE: AT.

**Comment by rickybanister** [comment]
We'll have to add an exception for Jetpack since those are just scraped right?

@rralian is that possible?

**Comment by beaulebens** [comment]
Correct, we would have to add an exception. Going forward, plugins would ideally have a way of indicating to Calypso that they would prefer to send users to their local/Calypso-based settings UI, but for now I think we'll need to just manually make an exception.

**Comment by rralian** [comment]
> @rralian is that possible?

All things are possible my friend. :-) we already have some Jetpack and vaultpress exceptions. I think @jsnjhnstn worked on some of them. Otherwise @roundhill and Lannister can probably help.
