### ISSUE TITLE
Reader Manage Following: allow text search of existing subscriptions

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#12960]
Using a text input, allow search of existing subscriptions.
![search-following](https://cloud.githubusercontent.com/assets/4924246/24886250/1754d3c0-1e08-11e7-87ad-e0b05c791eb2.jpg)

“Search Followed Sites…” is the search box that filters the list. If a term is entered, only matching sites are displayed (as now). 

Looking glass icon has been removed so it won’t get confused with the primary search box.

**Comment by samouri** [comment]
@bluefuton: for v1, how do you think we should implement the search?

**Comment by bluefuton** [comment]
@samouri we have the option to specify a query for `/read/following/mine` with `?q=`, although from a quick play in the API console, that doesn't seem to be working as expected for me (cc @gibrown)

**Comment by samouri** [comment]
I think it may be worth ignoring endpoints entirely until we stop loading them all anyway.

**Comment by gibrown** [comment]
@bluefuton did you use the 1.2 version of the endpoint?

That used to work with one of the PRs that we had kicking around though I bet the PR itself is out of date. What is not working?

**Comment by bluefuton** [comment]
@gibrown yep, v1.2 - didn't give me any results when I provided a `q`, even if that term appeared in my list of subs. Not super urgent as it looks like we'll continue to do our filtering client-side for the moment :)

**Comment by gibrown** [comment]
OK if we're blocked by other things I'm not going to look at it for the moment, but it's probably something simple to fix when we think we do get there.
