### ISSUE TITLE
Woo Connect-Insights: Create UI elements to control segmentation and time periods

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#12974]
Introduce UI elements to control 
- [ ] Segmentation (Sales by date, Sales by Product, Sales by Category, ...etc)
- [ ] Date ranges (7day, month, ...etc)
- [ ] Custom date ranges (start, end) and relevant date pickers

![screen shot 2017-04-11 at 9 01 26 am](https://cloud.githubusercontent.com/assets/1922453/24882748/4c4a6976-1e96-11e7-9df7-2f1c0bcf414c.png)

#### Requirements
1. Update routes
2. Reflect state determined by routes

#### Notes
* If designs are not yet finalised. Place elements with no styling

**Comment by psealock** [comment]
A simple card with dropdowns

![screen shot 2017-05-02 at 1 20 49 pm](https://cloud.githubusercontent.com/assets/1922453/25600730/593af6be-2f3a-11e7-9661-15dcbdb95953.png)

**Comment by psealock** [comment]
Custom date range 

![screen shot 2017-05-02 at 2 51 04 pm](https://cloud.githubusercontent.com/assets/1922453/25602310/dc776c54-2f46-11e7-8f52-cb2b5ece875e.png)

**Comment by psealock** [comment]
@raoulwegat could you lend me a hand with these selectors?

The two comments above are my initial thoughts for selecting segment type (Sales by Date, Sales by Product, etc) and the period. This component would reside just below the top level navigation (Orders, Customers, Stock). Since we may have so many charts, perhaps it could even be a sticky component. Do you have any feedback? 

Secondly, I'm struggling with the date range selector for custom dates. The "From" and "To" buttons would use the popover component to reveal the datepicker component. You can play with the individual components at http://calypso.localhost:3000/devdocs/design.

Ideally, I would like to create a reusable date-range-selector component similar to https://www.airbnb.com that allows you to select a range in a single dropdown. I don't think our timeline will allow that. Do you have any ideas on how to elegantly present these? How might it look on mobile? 

cc @greenafrican

**Comment by psealock** [comment]
Alternatively, it may make sense for v1 to offer same periods as Site stats.

![screen shot 2017-05-03 at 12 11 01 pm](https://cloud.githubusercontent.com/assets/1922453/25644460/4cf7aed6-2ffa-11e7-9005-241dcc79189d.png)

**Comment by greenafrican** [comment]
With no period selector/s? This may just be simpler for the MVP 👍

**Comment by psealock** [comment]
>With no period selector/s? This may just be simpler for the MVP 👍

Yup, we will be following the same pattern as Site Stats. Closing...
