### ISSUE TITLE
Plugin Section Navigation on Search and Select

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#12978]
NOTE: This was copied from a different repo, submitted by @JasonSnow-Mad. /cc @roundhill @drw158 as this is plugins section related. Questions/followups should go to him.

----------------------
While searching for plugins in Calypso (https://wordpress.com/plugins/browse/), if you select a plugin from the results to review it, and then use the back button, you are taken back to the Plugin Home screen, rather than your search results. 

**Searched for 'editor':**
![cloudup-t4jwmgsxjvo](https://cloud.githubusercontent.com/assets/8810295/24830807/9b011c0e-1c52-11e7-9e7a-be631582d2cb.png)

**Selected WP Editor:**
![cloudup-x1ixylowdby](https://cloud.githubusercontent.com/assets/8810295/24830813/abff2a3c-1c52-11e7-965b-ee9e95684a2b.png)

**Selected the 'Back' link and was taken back to the main plugins page:**
![cloudup-d5sgmtdy03g](https://cloud.githubusercontent.com/assets/8810295/24830812/a98016ea-1c52-11e7-9852-62631cabe92d.png)

It would be better to return to the search results on 'Back'.

**Comment by drw158** [comment]
I've never noticed this. I agree it should go back to the search results page.
