### ISSUE TITLE
Notifications: Should Achievements have a filter?

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#1297]
One can currently view Notifications by filtering to either:
- All
- Unread
- Comments
- Follows
- Likes

However, there's no filter to find the achievements that notify you of a blogging streak, or a new record number of likes or posts. Perhaps they are elsewhere referred to as badges, or trophies, but here are some examples of the notifications I'm thinking of:

<img width="399" alt="next_steps_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/933450/11609810/be01ca94-9b5e-11e5-80a2-baf98edbc8d0.png">

I believe there are more as well, like 'your stats are booming.' 

A WordPress.com user asked in chat if they could filter down to just achievements - presumably because the achievement they wanted to look at was long enough ago that finding it in 'All ' wasn't possible.

**Comment by dmsnell** [comment]
cc: @drw158 

My guess @alexjgustafson is that the space on that filter bar is already too precious to spare. If we were to add another option we would likely have to give up another. Thoughts? Let's make a decision and either close this issue or set a new task for notifications.

**Comment by alexjgustafson** [comment]
From my recollection here's the reason why the filter may have value:

1) User gets achievement, sees it
2) Time passes, it goes way down the notification list
3) User recalls memory of the achievement, wants to take a screenshot or something to share the achievement with a friend/their audience
4) How can I find that badge since it's been so long?

If the filter isn't a reasonable thing (which it may very well not be - I'm no designer) then another approach that may have helped this user is if there was a better "share this now" signal. Because if it got shared when it first happened, there'd be little reason to look it up later.

**Comment by dmsnell** [comment]
The "share this now" idea is interesting. On the point about finding an old achievement I think that a filter would only marginally help because notifications disappear after someone has more than a hundred on their account. Achievements aren't stored around.

In the past we had a kind of "trophy case" and it would be good to consider bringing that back into Calypso.
