### ISSUE TITLE
Store management: I need to manage my product reviews

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#12989]
Sketch: https://www.dropbox.com/s/m0b1jjkw2iisibf/Reviews.sketch?dl=0

Prototype: https://automattic.invisionapp.com/share/R4BQDYYVY#/251026936_Reviews_List

When the review is approved it will stay in the Pending list (minus the pending design treatment (left-hand border)) for 1s or so, then fade out.

**Comment by justinshreve** [comment]
@jameskoster I noticed that the ability to publicly or privately reply to a review was recently added to the Sketch.

WC currently doesn't have an endpoint or way to reply privately. I'm guessing the intention is that it would just send an email? I'll probably deprioritize implementing private replies for now, at least for Q3. We can open an issue for it. Maybe we could just show the email address in the mean time?

**Comment by justinshreve** [comment]
annnd I just noticed the "order note sent" text specifically. If we send the message via order notes (for verified product owners only) then that's a bit more doable. I still want to prioritize public replies depending on time though.

**Comment by jameskoster** [comment]
@justinshreve Sorry, I totally forgot to mention that. Yeah, we can de-prioritise private replies for now. You may need to hard refresh but the prototype in the OP shouldn't have private replies - that's the design to follow :)

**Comment by kellychoffman** [comment]
All issues are addressed except for bulk management, which we don't support anywhere yet, so closing this epic out. We'll create a new one for any v2 work.
