### ISSUE TITLE
Menus: `/menus` route is still directly accessible.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#12980]
Calypso Menus have been disabled in that the Menus link in the sidebar will now direct the user to the Customizer since #12967  . However, the `/menus` route is still directly accessible by URL. 

My first thought was to just remove the section, which gives a 404, but @sirbrillig pointed out that a redirect would be better. I then considered using `page.redirect()` in `my-sites/menus/index.js`, but ultimately we don't want that section and code to be there at all. Additionally, it's not a simple redirect; it will depend on whether or not the site is a [Jetpack site or not](https://github.com/Automattic/wp-calypso/blob/2013d21b29264416405c2b9b0d1a0a70e2f7b61f/client/my-sites/sidebar/sidebar.jsx#L226).

@ockham any suggestions how best to proceed?

**Comment by ockham** [comment]
> However, the `/menus` route is still directly accessible by URL. 

Sounds like it should be handled by a server-side redirect; tho that might be complicated a bit by the site handling part (especially the JP specific routing).

>  I then considered using `page.redirect()` in `my-sites/menus/index.js`, but ultimately we don't want that section and code to be there at all.

I think the redirects should live in the section that's now responsible for handling the new routes, i.e. [`my-sites/customize`](https://github.com/Automattic/wp-calypso/blob/f6c00546fe49cd1edc593fb8dc8f2e6b298a06e0/client/my-sites/customize/index.js).

I'll file a PR we can play with.
