### ISSUE TITLE
i18n: Strings are translated, but not appearing on Calypso

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#12986]
Some strings, probably coming from another sources, are not being properly translated in Calypso even if they already have a translation. For example, in pt-br:

* "Domain contact information": links [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/checkout/domain-details-form.jsx#L438) and [here](https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bterm%5D=DOMAIN+CONTACT+INFORMATION&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=calypso&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
* "That's too short. Enter a full phone number": [link](https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bterm%5D=That%27s+too+short&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
* "Make sure this is a valid postal code": [link](https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bterm%5D=Make+sure+this+is+a+valid+postal+code&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
* "The last 5 characters of &#8220;%s&#8221; must not be a dot.": [link](https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bterm%5D=The+last+5+characters+of&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
* "You successfully canceled your purchase": [link](https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bterm%5D=You+successfully+canceled+your+purchase&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/account
2. Change UI to any other language than English (pt-br, in my case)
3. Save changes
4. Visit http://wordpress.com/domains/add
5. Follow the process until you reach the checkout page

#### What I expected

See the errors in my own language.

#### What happened instead

Saw them in English.

#### Screenshot / Video

<img width="707" alt="captura de tela 2017-04-11 as 00 37 01" src="https://cloud.githubusercontent.com/assets/1136160/24894301/1353014c-1e4f-11e7-9e46-d9071e565490.png">

It also appears when canceling a domain:

<img width="1063" alt="purchase-canceled" src="https://cloud.githubusercontent.com/assets/1136160/24894883/d3c5a17a-1e52-11e7-8486-21e54caf3850.png">

#### Context / Source

i18n rotation: #dogfooding, #manual-testing

**Comment by rachelmcr** [comment]
I tested and I'm seeing the translated error messages:

![screen shot 2017-08-14 at 7 35 54 pm](https://user-images.githubusercontent.com/8658164/29285844-de70c388-8127-11e7-9a57-601aabfbf0b9.png)

Closing as resolved, but please reopen if you see any remaining issues here!
