### ISSUE TITLE
Framework: add a specific selected-site store

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#13]
Right now `sites-list` is handling too many responsibilities. We need to start breaking it further down into actions, utilities, and separate stores where necessary. One very specific use case is the `sites.getSelectedSite()` and related functions. It's a very contained responsibility that most sections rely on, and shouldn't be part of site-list.

**Comment by ockham** [comment]
Closing, since we have that now inside `client/state/ui`, thanks to @aduth's #751.

**Comment by mtias** [comment]
Now we need to move the rest :)
