### ISSUE TITLE
People: allow users to 'follow' their email and wpcom followers

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#130]
Currently:
You must browse /stats/follows to see followers' information. On that page you can click their name to see their primary site and also follow them back in the Reader. This doesn't feel like the ideal place to access followers and is a very cramped way to display the information.

Here's what that looks like:
<small>You can find it at https://wordpress.com/stats/follows/wpcom/testsite.wordpress.com</small>

![screen shot 2015-11-18 at 2 13 38 pm](https://cloud.githubusercontent.com/assets/11487924/11251290/a36a3f08-8dfe-11e5-87ca-f0ce79bbc09c.png)

There's also the people > followers page. It looks like this:

![screen shot 2015-11-18 at 2 15 07 pm](https://cloud.githubusercontent.com/assets/11487924/11251333/cd750922-8dfe-11e5-92cf-503f54ab1efa.png)

Ideally we'd add more features to this page, specifically:
- [ ] We display the primary site next to the person's username
- [ ] Add an ellipsis menu to each person card
- [ ] Put a `follow` action in the menu
- [ ] Move the `remove` action into the men

Here's a mockup:

![056bbfa0-62e0-11e5-9f52-9efc3d85fed5](https://cloud.githubusercontent.com/assets/11487924/11251380/f572cdb0-8dfe-11e5-866e-de51dd0153bc.png)

Questions raised:
- @MichaelArestad: Should we have a menu tied with a user that's available everywhere we show a user across all views?
- @MichaelArestad: I don't think it's possible yet to follow a user
- @alternatekev suggested that we not add the subscribed date to followers because we were planning on grouping users. @ebinnion mocked this up:

<img width="727" alt="19f56a48-65fb-11e5-9e4f-6cad8df027d9" src="https://cloud.githubusercontent.com/assets/11487924/11251451/5810f15e-8dff-11e5-8e4d-c0833a7d6bca.png">
- a suggested grouping of users from @alternatekev:
  - Today
  - Yesterday
  - This Week
  - Last Week
  - This Month
  - Last Month
  - This Year
  - Last Year
  - Two Years Ago
  - Three Years Ago etc.
- Wherever we show follow, we should also show the blog's URL? If they don't have a main blog, we shouldn't show a follow button.
- idea: add a link to the user's gravatar page from their username, like this:

![screen shot 2015-11-18 at 2 22 33 pm](https://cloud.githubusercontent.com/assets/11487924/11251576/e74c96f2-8dff-11e5-9a7f-bee472936b99.png)

**Comment by MichaelArestad** [comment]
Still an issue.
