### ISSUE TITLE
Editor: update animation too subtle to be able to tell if post edits worked

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#13006]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/ or https://wordpress.com/page
2. Type a title and some content and click update.
3. Type some more content and click update again.
4. There is no clear visual reference for user to see that the Post or Page is being updated. 
(_There is a slight glare on the blue update button, but it is too subtle._)

#### What I expected
I expected for the big green bar that says "Post Updated..... View Post", would be hidden until the Page has refreshed and then shown again.

![post-update-bar](https://cloud.githubusercontent.com/assets/12064241/24918180/285e3310-1ee8-11e7-8a2d-7616f5e5e142.PNG)

#### What happened instead
The big green bar was static and did not indicate any updating. 

#### Browser / OS version
Google Chrome 57.0 / Windows 10 Pro

#dogfooding

It would be great to see your Page or Post updating process visually as well. At the moment, user may not know if the Post or Page was updated, because the animation is too subtle.

Thank you!

**Comment by folletto** [comment]
Thanks! 

We discussed this internally and so far there seem to be agreement in removing the "inline notice" (the green bar) and using instead the "global notice" (the green bubble showing up in the top-right corner). 

In this way multiple updates would stack multiple bubbles, and would become evident.

/cc @rickybanister @mtias @jasmussen to see if I missed some conversation or some details in the above direction.

**Comment by designsimply** [comment]
Also reported in 3117484-t

<blockquote>i have a suggestion though.

i often make many changes to a page as I am a designer.
so when i update, i get the green button, but if i update again,
i get the green button obviously, but i dont know if it's the previous
update or the present one.
meaning when it's done.
maybe the update button can go grey until it updates again ---- then go
green again ?

I like the new barber stripes on the button. maybe it's hooked it to that.
or is that an attempt to do this? thanks.</blockquote>

/hat tip @sageBrownell for the original report.

**Comment by rickybanister** [comment]
We implemented 'ephemerality' in Jetpack to make 'settings saved' messages go away. I guess we'd want these notices to stay and replace each other with each new update though. Is that what you're proposing @folletto? I don't think a stack of several notices would be very helpful, you can only preview the most recent update anyway.

**Comment by folletto** [comment]
I agree a stack isn't ideal, but better than being too subtle and not seeing almost any change. I just recalled a recent discussion where came out that we wanted to switch from the bar to the bubble, and that alone would have helped on this issue too. :)

I agree the stack isn't ideal, we can animate the change in that scenario. :)

**Comment by jasmussen** [comment]
+1 bubble. Agree it's good to have clear messages about what's happened, but the current notice is arguably overkill on that front.

**Comment by designsimply** [comment]
The complaint is valid, but you should also consider that stacked errors that you must manually dismiss for each update could go too far in the other direction and be considered intrusive. A larger number of users may consider the bubbles very disruptive compared to the people with the current complaint.

**Comment by folletto** [comment]
> you must manually dismiss

This specifically wouldn't be a regression, as the same issue happens currently.

> stacked errors

They aren't errors tho, they are responses to a user action, a publish action specifically which **has** to receive a proper acknowledgement. If this becomes a problem, we can review it once we get there — for example introducing 'ephemerality' as Rick pointed out.

**Comment by designsimply** [comment]
Please consider user testing. 😊  I believe it would be good to make a change but that the proposed change would cause unnecessary friction that would be hard to know about without talking to users directly.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
