### ISSUE TITLE
Domains: Remove feature flags

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#1301]
We should remove [feature flags](https://github.com/Automattic/wp-calypso/blob/master/config/development.json#L86) for the domains management section - for all environments (similarly to what we did for the purchases management section in https://github.com/Automattic/wp-calypso/issues/1028):

```
upgrades/domain-management/contacts-privacy
upgrades/domain-management/email
upgrades/domain-management/list
upgrades/domain-management/name-servers
upgrades/domain-management/site-redirect
upgrades/domain-management/transfer
```

**Comment by klimeryk** [comment]
We have to wait for #2258 before removing `upgrades/domain-management/transfer`, but the other ones can go, especially since #2523 got merged.

**Comment by umurkontaci** [comment]
FWIW, #2258 #2323 are merged now
