### ISSUE TITLE
Purchases: Renew with free credits displays buggy success notice

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#13023]
Follow up for #13013.

### Steps to reproduce

- Go to http://calypso.localhost:3000/me/purchases and try to renew a product (such as a premium plan) using free credits so it doesn't auto-renew and hits the right condition.
- You should see the message `Success! You renewed WordPress.com Premium for a few seconds, until Mar 07, 2018. We sent your receipt to <email>.`

`bill_period` is not set for the purchase, thus the `a few seconds` shows up. This shouldn't happen.

![screen shot 2017-04-11 at 4 04 49 pm](https://cloud.githubusercontent.com/assets/1270189/24934517/cf77a5ae-1ed0-11e7-83a7-ecf5f211a726.png)

**Comment by jeremeylduvall** [comment]
I'm just now seeing this @gziolo after looking at another report in #12701.

In #13183, I was able to fix this by switching from:

`i18n.moment.duration( renewalItem.bill_period, 'days' ).humanize()`

to:

`i18n.moment.duration( { days: renewalItem.bill_period } ).humanize()`

You mention that the `bill_period` is not set for the purchase, but it still logs out at 365 in my testing even when purchased with credits.

**Comment by jeremeylduvall** [comment]
I think this should be fixed in #13183. Please reopen and ping me if not.
