### ISSUE TITLE
Homepage: Create Blog or Website buttons don't link to the correct place

### ISSUE THREAD

**Issue by rizwanmujtaba** [Automattic/wp-calypso#1303]
Hi,

The buttons at the bottom of WordPress.com site are wrongly connected. The "Create blog" button leads to the site page, and the "Create site" page leads to the blog page.

Notice the address at bottom left corner. Pointer was on "create blog" button.
![1](https://cloud.githubusercontent.com/assets/11389284/11612926/62a5181e-9c2f-11e5-86e5-cf1c7bd145fd.png)

Notice the address at bottom left corner. Pointer was on "create website" button.
![3](https://cloud.githubusercontent.com/assets/11389284/11612937/d264a4a8-9c2f-11e5-9521-2f8c18447d67.png)

**Comment by lancewillett** [comment]
Thanks for the report, rizwanmujtaba.

I can confirm by either logging out or using an incognito window. Using Safari 9.0.1 on OS X 10.11.1.

![screen shot 2015-12-07 at 09 05 39](https://cloud.githubusercontent.com/assets/66797/11631941/c77669a4-9cc1-11e5-8e11-c5acac63403a.png)

**Comment by sirbrillig** [comment]
Confirmed. There was a typo in the home page code for the second buttons. Should be fixed now. Thank you for noticing!!
