### ISSUE TITLE
Fullpost: More Links aren't fading anymore.

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13037]
On fullpost, the More links aren't fading anymore. They now show the whole excerpt and end in an ellipsis. 

<img width="776" alt="screen shot 2017-04-12 at 10 00 16 am" src="https://cloud.githubusercontent.com/assets/24388/24969860/1523c0b0-1f67-11e7-9eff-64dfcdbadd9c.png">

https://wordpress.com/read/feeds/43984987/posts/1416324602

They should fade after 5 lines at the bottom, right, like they used to.

cc @jancavan

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/13063
