### ISSUE TITLE
Replace 400 and 500 Error Illustrations with Updated Illustrations

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#13038]
We need to update our 404 and 500 error illustrations to match the new WordPress.com illustration style. 

---

Current 404 Illustration: 
![404-drake](https://cloud.githubusercontent.com/assets/1202812/24969870/424f9514-1f80-11e7-88da-707bf5d02cca.jpg)

Updated 404 Illustration: 
![404](https://cloud.githubusercontent.com/assets/1202812/24969915/6e696cba-1f80-11e7-88df-4113516ac989.jpg)

---

Current 500 Illustration: 
![500-drake](https://cloud.githubusercontent.com/assets/1202812/24969871/425c2b62-1f80-11e7-85b8-fa16117c990f.jpg)

Updated 500 Illustration:
![artboard 1 4x](https://cloud.githubusercontent.com/assets/1202812/25434796/bd9adef0-2a5b-11e7-8524-012b0de4306c.png)

**Comment by drw158** [comment]
Looks like maybe the 500 could be the same as the Whoops illustration.
