### ISSUE TITLE
Traffic/SEO: Allow SEO settings (meta/title structure) to be configured on private sites.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#13049]
Many users build/work on their sites behind the Private setting, allowing them to build without exposing the partially-finished site to search engines and visitors. However, the inability to configure the site's meta/titles can be problematic, as it's possible for a search engine to crawl the site before the user can set the proper site title structure/meta info.

![SEO Settings](https://cldup.com/hml70ZR-kP.png)

While we **should** very clearly warn the user here that the site is private, we should allow for configuration so that they are able to launch a _truly_ completed site when they switch from Private to Public.

The Webmaster Tools section should probably remain disabled until the site is Public, as that configuration relies on the site being public to be successfully completed.

**Comment by roundhill** [comment]
Sounds ok to me. Any issues with this proposed change @Automattic/lannister?

**Comment by roundhill** [comment]
It's actually a really simple change:

<img width="732" alt="screen shot 2017-05-16 at 5 17 57 pm" src="https://cloud.githubusercontent.com/assets/789137/26133417/b258d24e-3a5b-11e7-94e4-afe9894752c7.png">

I'm not sure what the best message is there, right now I have `SEO settings won't be found by search engines until your site's visibility is Public.`

**Comment by gwwar** [comment]
This sounds reasonable to me 👍  I added a `Needs Copy Review` label for help with your suggested text.

**Comment by vindl** [comment]
This sounds good to me. :+1: In that case, we should also remove similar checks for post meta in editor.

**Comment by michelleweber** [comment]
Suggestion:

_SEO settings aren't recognized by search engines while your site is Private._

(I think it's a wee bit clearer to tell them what's happening based on their current settings rather than what would happen if their settings were different, and this reminds them that their site is private.)

I think it'd also be great if the shaded area to the right could specify "View privacy settings," but I understand if that's too long for the area available.

**Comment by vindl** [comment]
I've noticed that we also have similar checks for hidden sites. Maybe we should allow editing of SEO fields in that case too?

**Comment by tyxla** [comment]
> I've noticed that we also have similar checks for hidden sites. Maybe we should allow editing of SEO fields in that case too?

That would make complete sense to me :+1: I've commented about that in #14162
