### ISSUE TITLE
Update our Drake "Empty Results" illustration to new style

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#13046]
We should update our Drake "Empty Results" illustration to match the new WordPress.com illustration style.

Current:
![empty-results-drake](https://cloud.githubusercontent.com/assets/1202812/24970956/2e5638f2-1f84-11e7-8f0f-d64445711291.jpg)

New:
![empty-results](https://cloud.githubusercontent.com/assets/1202812/24970962/318ab48a-1f84-11e7-8b46-265c89354f02.jpg)

**Comment by folletto** [comment]
Note: after this gets merged, we'll re-introduce a redesigned Drake limited to the only place where was originally intended as an easter egg, themes. ;)
