### ISSUE TITLE
Update our Drake "Whoops" illustration to the new style.

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#13048]
We should to update our Drake "Whoops" illustration to match the new WordPress.com illustration style. We don't have an illustration ready for this yet, so we need to draw one. 

This is used in [a wide variety of places](https://github.com/Automattic/wp-calypso/search?utf8=✓&q=drake-whoops&type=Code), so it'll need to be generic enough to continue to be used in those places.

Current: 
![whoops-drake](https://cloud.githubusercontent.com/assets/1202812/24971240/488571c4-1f85-11e7-96f5-6df249473c08.jpg)

**Comment by drw158** [comment]
Since this is so generic, maybe we can do an emoji in the new illustration style.

😟  or 😕  or  😞  or something

**Comment by kjellr** [comment]
@drw158 Yeah, I think that could work. I initially drew this up, but I was a little weary of creating a non-human "character" in this case:

![artboard](https://cloud.githubusercontent.com/assets/1202812/26641669/55c6190c-45f9-11e7-878a-ced60b5394de.png)

Something that's more clearly an emoji could be okay though.

**Comment by kjellr** [comment]
@drw158: way overdue, but here are a few emoji-ish explorations for this:

![2artboard 1 4x](https://user-images.githubusercontent.com/1202812/28222823-0d7c7cc0-6897-11e7-8ae1-5d4c991d92fd.png)
![3artboard 1 4x](https://user-images.githubusercontent.com/1202812/28222821-0d78337c-6897-11e7-9976-811c577c96a8.png)
![artboard 1 4x](https://user-images.githubusercontent.com/1202812/28222822-0d78f168-6897-11e7-8675-a11025dac770.png)

cc @joanrho

**Comment by drw158** [comment]
These are great. 1 and 3 are better for more generic errors I suppose. 1 might be the most versatile, closer to a 😮 expression.

**Comment by kjellr** [comment]
I started swapping out some of these locally, and it struck me that while some of them work just fine...

![screen shot 2017-07-26 at 12 59 15 pm](https://user-images.githubusercontent.com/1202812/28633641-8b7c7228-7202-11e7-9471-7479c3e7b502.png)

... other ones are actually kind of weird:

![screen shot 2017-07-26 at 12 29 08 pm](https://user-images.githubusercontent.com/1202812/28633821-073b4cfe-7203-11e7-8c65-18a747cb8d30.png)
![screen shot 2017-07-26 at 12 35 05 pm](https://user-images.githubusercontent.com/1202812/28633822-0743341e-7203-11e7-8ebc-115079d209fe.png)

It seems we're using "whoops" for upsells, which seems really odd (even with the original drake whoops image). I'm thinking those illustrations should be different in general.

**Comment by joanrho** [comment]
I think in this case (something forbidden, something missing, an error, etc.) the browser “oops” makes more sense than a character since this is a technical issue. The character doesn’t feel right because it’s not a human error. Instead of a face, how about an exclamation point (commonly used) or an X?

Also, I agree that using the “whoops” for upsells doesn’t make much sense. Perhaps some sort of illustration that speaks to the feature we’re trying to upsell?

**Comment by kjellr** [comment]
> I think in this case (something forbidden, something missing, an error, etc.) the browser “oops” makes more sense than a character since this is a technical issue. The character doesn’t feel right because it’s not a human error. Instead of a face, how about an exclamation point (commonly used) or an X?

With that in mind, I tried swapping this out with our existing "itemFailed" image. I think this works pretty well. You can check it out in PR #16687

@joanrho + @drw158, mind taking a look at the PR and weighing in on the two Upgrade images too?

**Comment by kjellr** [comment]
Closed via 16687. 🎉
