### ISSUE TITLE
Update our Drake "New" illustration to new style

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#13043]
We need to update our Drake "New" illustration to match the new WordPress.com illustration style. This is used in our "Welcome to WordPress.com" page after signup. 

Current: 
![new-drake](https://cloud.githubusercontent.com/assets/1202812/24970434/4285d2e4-1f82-11e7-9df2-dff9a5e2492f.jpg)

New:
![new](https://cloud.githubusercontent.com/assets/1202812/24970437/46dbc1be-1f82-11e7-82a2-5a329feb0886.jpg)

**Comment by drw158** [comment]
Can we somehow see if this image is still being used? I just created a new site with an account that had not previously created any sites.

cc @folletto 

From the readme for the welcome message: 

> This module enables a welcome message to be shown at the top of calypso for new users who have just registered their first site. The message is persistent for users in a full-width screen and follows them from page-to-page in calypso until they dismiss it or their localStorage is cleared for whatever reason. In mobile or one-col browsers the welcome message is removed when the user dismisses it or upon navigating to any other page.

I did create the account first, then created a site. Maybe you have to create a new account and site all at once?

**Comment by folletto** [comment]
Checking the use of `NUX-Welcome` (`welcome-message`):

1. Referenced in https://github.com/Automattic/wp-calypso/blob/ef40e66e73a2bde0e0e791ebdb50b8c6f7862205/client/layout/index.jsx#L112
2. Which seems code still being used, I wonder if for some reason `this.props.nuxWelcome` isn't set anymore... as [this](https://github.com/Automattic/wp-calypso/blob/27e73c4736fdc0fe94475755eeb8102bcdb2a0c5/client/layout/nux-welcome/index.js#L23) condition seems relying on `store` uniquely.

Anyhow, I'd still replace the SVG, mostly to be available for future use. 

In regard of the component I'm not sure on the procedure to remove it if it's really not used anymore. cc: @scruffian, maybe you have any idea or advice?

**Comment by scruffian** [comment]
I don't think NUX-Welcome is currently used, but we left it in the code in case we wanted to re-enable it. No harm in updating the images for future use, as you say.
