### ISSUE TITLE
Update our Drake "All Done" illustration to the new style.

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#13047]
We should update our Drake "All Done" illustration to the new illustration style. This is currently used in [empty reader streams](https://github.com/Automattic/wp-calypso/blob/a93d1075536a0bbba28b807e1a4368fec2d072fd/client/reader/stream/empty.jsx#L32), and also in the [Magic Login flow](https://github.com/Automattic/wp-calypso/blob/b83c3afe018c0836c179d6cdef326067328faec9/client/login/magic-login/emailed-login-link-successfully.jsx#L40). We don't have a replacement illustration ready, so we'll need to draw a new one. 

Current: 
![all-done-drake](https://cloud.githubusercontent.com/assets/1202812/24971100/becd65f4-1f84-11e7-97b4-5efafd8f3d9c.jpg)

**Comment by kjellr** [comment]
This illustration is used in two very different places:

[In magic links](https://github.com/Automattic/wp-calypso/blob/b83c3afe018c0836c179d6cdef326067328faec9/client/login/magic-login/emailed-login-link-successfully.jsx#L40), this is used as a confirmation image. Since that's the case, maybe we should just replace that with our ["ok" illustration](https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/illustration-ok.svg). This is in sync with the way we use the ok image after you successfully reset your password.

[In the reader](https://github.com/Automattic/wp-calypso/blob/a93d1075536a0bbba28b807e1a4368fec2d072fd/client/reader/stream/empty.jsx#L32), we use this image when you aren't following/managing any sites. I think we're mainly using this illustration because Drake is wearing "reading" glasses, right? It might make sense to use some variation of the "person reading a book" illustration that @jancavan is drawing for #13178. 

Thoughts?

**Comment by jancavan** [comment]
> In magic links, this is used as a confirmation image. Since that's the case, maybe we should just replace that with our "ok" illustration.

Sounds good.

> In the reader, we use this image when you aren't following/managing any sites. It might make sense to use some variation of the "person reading a book" illustration that @jancavan is drawing for #13178.

Yeah, it's used as a "Welcome" illustration. I can come up with something for this @kjellr if you aren't on it already?

Adding screenshots here for completeness:
**Empty Following stream:**
![screenshot 2017-07-14 16 18 57](https://user-images.githubusercontent.com/4924246/28234038-531ade7a-68b0-11e7-9d0c-f6d0a2201d16.png)

**Empty Manage page:**
![screenshot 2017-07-14 16 18 01](https://user-images.githubusercontent.com/4924246/28234041-5acc35f6-68b0-11e7-8edb-b920cc8889a7.png)

**Comment by kjellr** [comment]
> I can come up with something for this @kjellr if you aren't on it already?

That would be awesome. Thanks @jancavan!

**Comment by cathymcbride** [comment]
I think this is long gone.
