### ISSUE TITLE
Menus: Add a Guided Tour to explain the Menus link now going to the Customizer.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#13059]
The sidebar Menus link now points to the Customizer's Menu panel, rather than the native Calypso menus manager. As brought up in #12327 , a Guided Tour could be added to better explain these changes to users.

**Comment by kwight** [comment]
As noted by @folletto , the Menus link can be entirely removed (since Menus are now available through the Customize link), with the Guided Tour offering explanation and hinting to the Customize link.

**Comment by lancewillett** [comment]
Closing as we never got to this one. Feel free to re-open if it's needed in the future.

CC @lsinger
