### ISSUE TITLE
verticalSurvey test mobile issues: Squashed header and stuck 2nd survey step

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#1305]
On small mobile screens the header will appear squashed. Here it is on iOS Chrome. Also reproduced in mobile Safari.

![](https://cldup.com/kB4wQFdZ-w.png)

Additionally, sometimes the second step of the two-step survey will not proceed to the next step (themes) after making a selection in Chrome on iOS. (This works correctly in mobile Safari.)

**Comment by sirbrillig** [comment]
Created #1310 for the "getting stuck" part of this bug.
