### ISSUE TITLE
Reader: Videos should be full-width after it's clicked

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#13051]
![screenshot 2017-04-12 09 22 40](https://cloud.githubusercontent.com/assets/4924246/24971783/01a8aa94-1f6e-11e7-8634-c274b3d9657d.png)

Unlike the screenshot, after the video thumbnail is clicked, it should expand to full-width.

@samouri It doesn't look like the size can be set in the CSS (unlike videos in full-post) or is there an `is-modifier` class for it that's missing?

**Comment by fraying** [comment]
Confirmed in Safari and Chrome. This is a regression. They used to be full width. Any ideas, @samouri? I feel like we've squashed this bug more than once.

**Comment by samouri** [comment]
> @samouri It doesn't look like the size can be set in the CSS (unlike videos in full-post) or is there an is-modifier class for it that's missing?

We set the size in js. I'll try to figure out whats going on

**Comment by jancavan** [comment]
@samouri It'd be nice to have `is-video` set for it for example. Then we can override the default properties set in its `reader-post-card__post`. `flex-direction: row;` is causing it to display 2-columns.

**Comment by samouri** [comment]
we don't really want `is-video`, we really want `is-expanded-video`.  We will be able to do that soon once I finish https://github.com/Automattic/wp-calypso/pull/12371
