### ISSUE TITLE
Domain Search: Console output shows domain 

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#13074]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains
2. Open console
3. Enter some characters

#### What I expected

No console output

#### What happened instead

Console output of characters

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

<img width="1391" alt="console output" src="https://cloud.githubusercontent.com/assets/128826/24988755/445abeda-204b-11e7-8f3e-c4b2edc3884b.png">

**Comment by aidvu** [comment]
Fixed! https://github.com/Automattic/a8c-domain-search/commit/5db1a0fdd5ed3896021e571f73ca8ec1067f2860
