### ISSUE TITLE
Site Settings: Analytics activation notice links are wrong for Jetpack >= 4.8

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#13075]
As @roccotripaldi nicely caught earlier in https://github.com/Automattic/wp-calypso/pull/13050#pullrequestreview-32537249, in the notice to activate Analytics module in the Analytics form under Traffic:

> We are linking to wp-admin/admin.php?page=jetpack#/engagement but sites on Jetpack 4.8 and above should go to wp-admin/admin.php?page=jetpack#/plans

For Jetpack < 4.7, we should still be linking to the `engagement` section.

**Comment by oskosk** [comment]
I've created a PR #13268 (for replacing this links for onCLick handlers that activate the modules.

**Comment by oskosk** [comment]
But it looks like the banners/notices are going to change... (?)

**Comment by tyxla** [comment]
@oskosk I've just merged #13050 that changes how the Analytics notice is displayed, but #13268 should still be applicable anyway.
