### ISSUE TITLE
Plans: Update back link to redirect to previous page instead of parent page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#1308]
We should update the `< Back` link located at the top of the `Compare Plans` page to redirect to the previous page instead of the parent page:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11615561/96eb0b58-9c32-11e5-9882-7aed736a874b.png)

The rational here is that we can now navigate from purchases to plans which makes this link a bit misleading. For example, you can go to the `Compare Plans` page from the `Manage Purchase` page by clicking the `View Plan Features` link. However the `< Back` link at the top of the `Compare Plans` page will redirect you on `Plans` instead of  `Manage Purchase`.

**Comment by breezyskies** [comment]
As noted in https://github.com/Automattic/wp-calypso/pull/1300#issuecomment-162906140, this needs to be addressed at a global level for the `SectionHeader` component. I'd recommend opening a components / framework issue to start the discussion.

**Comment by stephanethomas** [comment]
Gotcha. I have opened https://github.com/Automattic/wp-calypso/issues/2072 to address this issue.
