### ISSUE TITLE
People: add email for each user on the `/people/edit/` screen

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#131]
When managing users, you sometimes need to know their email address for cases such as:
- you are an admin and are helping to check if someone has been added
- you would like to contact other people on the site
- it's helpful to have a unique identifier other than the username (some people create generic username/display names)

Can the username be shown on the `/people/edit` screen?

Here's what the pages look like now:

![screen shot 2015-11-18 at 2 44 49 pm](https://cloud.githubusercontent.com/assets/11487924/11252216/f3f639fa-8e02-11e5-9580-79c4ce494f5f.png)

![screen shot 2015-11-18 at 2 43 17 pm](https://cloud.githubusercontent.com/assets/11487924/11252188/d587696c-8e02-11e5-805a-5972f567b427.png)

Questions:
- Perhaps it should be opt in? I can see maybe a case where someone doesn't want their proper name shown. That may come back to having a unique identified though rather than showing their first name/last name.

**Comment by KokkieH** [comment]
As we're now redirecting WP-Admin ->Users ->All Users to /people instead, there is now no way for an admin to view the email addresses of other users on the site unless they know how to manually go to /wp-admin/users.php

With that in mind, could we revisit this so we can get feature parity with WP-Admin?

**Comment by v18** [comment]
cc @lancewillett for feature parity discussion ^

**Comment by richardmtl** [comment]
I have a weird Jetpack ticket in 756587-zen where this would come in handy (ie, knowing the email address of people).

**Comment by lancewillett** [comment]
Let's keep it open for @Automattic/tanooki to review in upcoming People Invites UX sprint.
