### ISSUE TITLE
Pages: front page setting `page` works, setting `blog posts` doesn't work

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#13114]
Regarding the homepage settings:

* If the site has "Blog Posts" active as front page, setting any page as front page works
* If the site has any page active as front page, activating "Blog Posts" doesn't work

To reproduce:

1. Open Pages
2. Switch the homepage to any page
3. Try switching back to Blog Posts

![cap-](https://cloud.githubusercontent.com/assets/4389/25043198/04cded5c-2116-11e7-9a3a-ea3e74e76cd2.gif)

**Comment by marekhrabe** [comment]
When trying to switch the homepage to "Blog Posts", this XHR is issued:

```
POST https://public-api.wordpress.com/rest/v1.1/sites/:site_id/homepage

request:
{ is_page_on_front: true, page_on_front_id: 0 }

response:
{ is_page_on_front: true, page_on_front_id: "0", page_for_posts_id: 0 }
```

My shallow understanding is that the request should contain "is_page_on_front: false" instead so the homepage will use the blog post list instead of a page.

**Comment by marekhrabe** [comment]
Just confirmed that correct API call should be the one with `is_page_on_front: false` to set the homepage back to "Blog Posts".

<img width="764" alt="screen shot 2017-04-14 at 14 51 06" src="https://cloud.githubusercontent.com/assets/156676/25043658/d4bf55c2-2121-11e7-90bb-0cb3614ae50b.png">
<img width="375" alt="screen shot 2017-04-14 at 14 52 22" src="https://cloud.githubusercontent.com/assets/156676/25043672/ffeafe0e-2121-11e7-8fe0-fb76d0874d46.png">
