### ISSUE TITLE
Editor: Enable geo tagging for Jetpack sites

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#13127]
In the Post Editor, we don't currently allow Jetpack sites to include location information:

<img width="280" alt="screen shot 2017-04-14 at 4 08 51 pm" src="https://cloud.githubusercontent.com/assets/108942/25057397/ac2811ca-212c-11e7-8018-46be2bded2ad.png">

For WordPress.com sites we do:

<img width="282" alt="screen shot 2017-04-14 at 4 09 17 pm" src="https://cloud.githubusercontent.com/assets/108942/25057401/bafc72ea-212c-11e7-857b-0393761206af.png">

We should enable this feature for Jetpack sites. Ideally we'd ship the code in Jetpack so that locations are also shown at the end of `post_content`, but at least to start with, we could enable this piece of UI, and then any themes/plugins on Jetpack sites which leverage the standard data format could be using it.

From a quick, look, we'd need to:

- [ ] remove the conditional in `editor-drawer/index.jsx` which explicitly hides this from Jetpack sites
- [ ] add `geo-location` to the `supports` object in the response of the `post-types` endpoint (should technically ship in Jetpack, but we could probably just inject it in there from WP.com as well?)

**Comment by griffbrad** [comment]
Just chiming in to let anyone interested know that this is in the works.  This feature branch adds support for saving the geo-location fields to pages and posts in Jetpack:
https://github.com/Automattic/jetpack/tree/add/geo-location-support

At the moment, it really only works with this branch of Calypso:
https://github.com/Automattic/wp-calypso/tree/add/let-jetpack-use-geolocation

Once the Jetpack work is wrapped up and included in a release, we can adjust Calypso to check for that Jetpack version number before rendering the geo-location UI.

I'll next add support for various hooks in Jetpack to make use of the geo-location information on the frontend.  Once that's in a decent spot, I'll start up a PR.

**Comment by lynnbgriffith** [comment]
This was actually closed by Automattic/Jetpack#9573.
