### ISSUE TITLE
Themes: Increase Upload limit to account for large theme files.

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#13133]
Currently the hard upload limit in Calypso is set to 10MB. While this works for many themes with the addition of AT we're seeing more and more theme files which are larger than 10MB attempt to be uploaded. If we were able to increase this to 20MB I believe that would account for most (70-80%) of the cases. 

We of course need to consider how this will be handled for hosts with a smaller limit than whatever we set the limit to.  If it's not possible to raise the limit for all sites, perhaps we can make an AT exception since we know the hosting limit is 100MB.

Related #13128

**Comment by seear** [comment]
The 10MB limit is enforced by the .com server. We get an `UPLOAD_ERR_FORM_SIZE` error for the POSTed zip when calling the theme upload endpoint. `mu-plugins/jetpack/class.jetpack-client.php` "handles" this error by calling the Jetpack site without a file (although it does report back that the file was too big).

@seanosh, do you know what mechanism is enforcing this limit on .com? The REST API endpoint in question is  `POST /sites/%s/themes/new`, and also possibly `POST /sites/%s/automated-transfers/initiate`.

**Comment by seanosh** [comment]
@seear systems request would be best.

**Comment by seear** [comment]
Limit now changed to 20MB pMz3w-6Yi-p2
