### ISSUE TITLE
Editor: featured images with rotation EXIF metadata are not rotated correctly on Jetpack sites

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#13145]
Steps to reproduce:

1. Download a sample image from https://github.com/recurser/exif-orientation-examples
1. Go to https://wordpress.com/post and select a Jetpack site.
1. Add a featured image using an image from step 1.
1. After the featured image is set, note that the rotation is incorrect.

<strong>Result:</strong> I expected images that have the correct rotation on my computer to also have the same rotation in the featured image area.

<strong>Video:</strong> [1 min](https://cloudup.com/cg-RUgTcl3o)

![screen shot 2017-04-11 at tue apr 11 4 45 42 pm](https://cloud.githubusercontent.com/assets/1119271/24934073/b99f8d54-1ed6-11e7-8805-355314bc8fda.png)
<sup>Seen at https://wordpress.com/post/alittletestblog.com/13593 running WP 4.7.3 and Jetpack Beta (Build 1736160) c142584 using Chrome 57.0.2987.133 on Mac OS X 10.12.4.</sup>

Also see #313.

**Comment by elibud** [comment]
Reopening as I was able to replicate both in the feature image and in the post body.

**Comment by elibud** [comment]
Sample post with incorrect orientation: https://elibudtests3.wordpress.com/2019/07/26/images-and-images/, please note that both images display correctly in my computer.

**Comment by jtreanor** [comment]
I'm going to look into this issue this week. I have just done some quick tests and I can reproduce the issue on a Jetpack site, a WP.com site and a WP site without Jetpack. It's quite possible this isn't a Calypso issue but I will dig some more before making any conclusions.

**Comment by jtreanor** [comment]
It looks like a diff has just been opened to fix this in WordPress Core (see [here](https://core.trac.wordpress.org/ticket/14459#comment:71)).

**Comment by jtreanor** [comment]
Just a quick update here. The issue has been fixed for WP.com sites but is still present in Jetpack sites.

**Comment by tbradsha** [comment]
An AT site had orientation issues.

Reported here: #16003110-hc

**Comment by AtrumGeost** [comment]
Got another case here: 2411650-zen (AT Site)

This is the image in question: 

![900064_Salvador_IMG_8972](https://user-images.githubusercontent.com/3696121/67225785-6ea19400-f3f9-11e9-8dcc-077031aa06a5.jpg)

I was able to replicate on an AT site, not happening on simple sites (as mentioned above).

**Comment by designsimply** [comment]
This may help: https://core.trac.wordpress.org/changeset/46202 (planned update for WP 5.3). We should test again with self-hosted/Jetpack/AT after WP 5.3 is released.

**Comment by lancewillett** [comment]
Tested this flow today with an Atomic site, using https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_6.jpg as the side-rotated image.

Both in post content, and featured image — look correct in both the editor and after publishing.

<img width="1269" alt="Screen Shot 2020-04-15 at 15 30 40" src="https://user-images.githubusercontent.com/66797/79395270-1a9de500-7f2e-11ea-8b6d-263cf6f1b117.png">

<img width="935" alt="EXIF Rotation test – Blog Atomic (2020-04-15 15-30-48)" src="https://user-images.githubusercontent.com/66797/79395307-31dcd280-7f2e-11ea-86db-fa6e118fb4ef.png">

Confirmed fixed.

Please open new issues if you see a regression.
