### ISSUE TITLE
Domain Notices: Hide primary domain for domain-only sites

### ISSUE THREAD

**Issue by aidvu** [Automattic/wp-calypso#13151]
The message about “Primary domain”. For a domain-only account, this concept doesn’t apply, so that paragraph probably shouldn’t be there:
#### Steps to reproduce
1. Starting at URL: wordpress.com/domains
2. Register a domain
3. Look at the landing page

#### What I expected
4. Since there is no `primary domain` for domain-only sites, message shouldn't be shown.

#### What happened instead
4. See notice about `primary domain` for the site
![domains5](https://cloud.githubusercontent.com/assets/1103398/25095945/6aeab5d8-238d-11e7-83ba-5d4a0e36f8b0.jpg)

**Comment by breezyskies** [comment]
We've also discussed removing this notice entirely in https://github.com/Automattic/wp-calypso/issues/11441.
