### ISSUE TITLE
Warnings during npm install: Jade will be unpublished soon, please use pug

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#13162]
#### Steps to reproduce

Delete node_modules if it exists
npm cache clean + npm cache clear
npm install

#### What I expected

No deprecation / unpublished soon warnings

#### What happened instead

npm WARN deprecated jade-attrs@2.0.0: jade-attrs will be unpublished soon, please use pug-attrs
npm WARN deprecated jade-lexer@0.0.9: jade-lexer will be unpublished soon, please use pug-lexer
npm WARN deprecated jade-filters@1.1.0: jade-filters will be unpublished soon, please use pug-filters
npm WARN deprecated jade-load@0.0.4: jade-load will be unpublished soon, please use pug-loader
npm WARN deprecated jade-error@1.2.0: jade-error will be unpublished soon, please use pug-error
npm WARN deprecated jade-walk@0.0.3: jade-walk will be unpublished soon, please use pug-walk
npm WARN deprecated jade-code-gen@0.0.4: jade-code-gen will be unpublished soon, please use pug-code-gen
npm WARN deprecated jade-runtime@2.0.0: Replaced by pug-runtime
npm WARN deprecated jade-strip-comments@1.0.0: jade-strip-comments will be unpublished soon, please use pug-strip-comments
npm WARN deprecated jade-parser@0.0.9: jade-parser will be unpublished soon, please use pug-parser

#### Browser / OS version

MacOS Sierra 10.12.4, node v6.10.2, npm 3.10.10

#### Screenshot / Video

N/A

#### Context / Source

N/A

**Comment by ockham** [comment]
Sigh, yeah. Ideally we'd get rid of Jade/Pug entirely IMO, see #8459.

**Comment by ockham** [comment]
Replaced Jade with Pug in #19984. Pug was then removed in #22348.
