### ISSUE TITLE
Reader: highlighting text in Reader post's content area results in a click

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#1317]
If you highlight text in the Reader (for copy-pasting, etc), and your mouse stops in a Reader post, it gets registered as a click and you go the the post detail.

**Comment by lancewillett** [comment]
I can repeat this, using Mac-n-Chrome. One note, only seems to occur in the body of the Reader post content — not the post title itself.

Screencast:

![reader-highlight-click](https://cloud.githubusercontent.com/assets/66797/13717112/8c643d8e-e79c-11e5-8c5f-e04454ea3e3c.gif)

**Comment by lancewillett** [comment]
While I think we should fix this, it's low priority.

**Comment by lancewillett** [comment]
Re-testing this today: the bug seems fixed, at least in Mac-n-Chrome. Highlighting text does not click through any more.
