### ISSUE TITLE
Update the Reader's "Welcome" illustration (#11282) to new illustration style. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#13178]
Along with the rest of our [illustration rollout](https://github.com/Automattic/wp-calypso/projects/30), we'll want to update the Reader's "Welcome" illustration (introduced in #11282) to our new WP.com illustration style. 

**Original:**
![3cdc2904-efa5-11e6-9679-e9f83baaf7fc](https://cloud.githubusercontent.com/assets/1202812/25130872/cddcf712-2411-11e7-8dc4-894a21c5f8aa.jpg)

**Updated:**
TBD

**Comment by fraying** [comment]
@kjellr: I think @jancavan would like to take a crack at updating this illo to match the new style.

**Comment by kjellr** [comment]
Great! I sent her our latest styleguide and example assets. Feel free to ping with any questions, Jan!
