### ISSUE TITLE
Add action that creates new product through to merchant host endpoint

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#13188]
This is infrastructure work for WooCommerce on WordPress.com. This issue is for 1) adding an action to `extensions/woocommerce` that uploads the state in `create` branch of the extension tree, 2) adding the necessary code to wpcom undocumented to call  `/wp-json/wc/v2/products` on the merchant's host to create the product, and 3) for adding an action updates the state when the product has been created.

This issue does not include the work for adding the UI - that will be in a separate issue.

**Comment by designsimply** [comment]
@allendav would it be possible to add a bit more information to tickets like this so they are easier for others to follow?

**Comment by allendav** [comment]
@designsimply absolutely!

**Comment by coderkevin** [comment]
This code is completed in PR #13733
