### ISSUE TITLE
Reader: Add sites to search results

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#13189]
# To Do
- [x] Add feature flag for features on current pages
- [x] Create new Site result component. Hook up to redux or flux follow info?
- [ ] Add in header selector for Sites and Posts in existing search results
- [x] Redux work for managing search results
- [ ] Figure out how to switch views based on browser width. JS or CSS?
- [ ] Reporting

# Summary
![site-search004](https://cloud.githubusercontent.com/assets/4924246/25157512/bfaae740-2456-11e7-9402-f7141ef54b71.jpg)

Notes:

* New right side column for site results. If there were no site results, omit the column.
* Site results include gravatar (if none, blavatar), site title, site description/tagline, byline, URL. Basically same text as on the Site View.
* Clicking anywhere in the result takes you to the Site View for that site. Clicking the small follow link follows the site, natch.
* Scrolling the page leaves the search box and “Posts/Sites” header in place.
* Limit Site Description to 3 lines in wider screens.

When the browser gets too narrow to host both columns comfortably, switch to showing only one column with a toggle:

![results-w-sites-mobile-1](https://cloud.githubusercontent.com/assets/14350/25148107/bd31545e-2447-11e7-82f7-ced89a15dc54.png)

![site-search-mobile003](https://cloud.githubusercontent.com/assets/4924246/25157520/c7837b44-2456-11e7-8ece-52d835358fc2.jpg)

Notes:

* Defaults to Posts. User can toggle to Sites using SectionNav.
* Scrolling the page still leaves the search box and “Posts/Sites” header in place.

**Comment by blowery** [comment]
Breakpoint? I think we could handle two columns at 960px and up. (But if we remove the left side nav sidebar, we could drop that down to 660px and up. Working on that proposal now.)

Update URL? Sure! “&show=posts” and “&show=sites” or something like that?

**Comment by blowery** [comment]
> When the viewport is narrow and the list is in a tab, we can use infinite list to load in more site results. How should we do that when results are in the sidebar? Should we ever load more? How many should we load by default?

How about, to start off site results, let’s just mirror what we’re doing for post results? If that’s not possible, let’s just pull in as many site results as will fit (10? 20?) and start there.

**Comment by blowery** [comment]
(notes from previous conversations with @fraying)

**Comment by blowery** [comment]
related to https://github.com/Automattic/wp-calypso/issues/12951

**Comment by fraying** [comment]
Thanks for the copypasta, @blowery

**Comment by jancavan** [comment]
I've updated the mockups and notes in this issue to include the site URL. We're adding this back because some sites have generic titles and you won't be able to determine which one you may be looking for.

**Comment by blowery** [comment]
This landed ages ago.
