### ISSUE TITLE
Settings: Custom Content Types can't be activated from Calypso

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#13180]
Originally reported by @chaselivingston and @retrofox .

When trying to activate either Testimonials or Portfolio from Settings > Writing in Calypso on an Automated Transfer site, I'm seeing:

<img width="518" alt="screen shot on 2017-04-08 at 11-11-19" src="https://cloud.githubusercontent.com/assets/831377/24830467/38895c18-1c4c-11e7-8e83-4bb36d7a87c9.png">

In the network response for that call, the response is:
`{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"some_updated","message":"Option not updated: jetpack_portfolio."}}`

**Comment by designsimply** [comment]
I was unable to reproduce the problem using the following testing steps:

1. Go to Settings > Writing for a Jetpack site on WordPress.com.
1. Find the "Custom content types" box.
1. Toggle the settings for Testimonials and Portfolios.
1. Look for a "Settings saved!" success message.
1. Check the console for errors.
1. Check the Network tab for any 400 responses to any jetpack calls.

<strong>Result:</strong> custom content type settings were saved normally in my testing. ([1m25s](https://cloudup.com/cWhHLlEe6kx))

**Comment by chaselivingston** [comment]
@designsimply Did you test this with an AT site specifically?

**Comment by oskosk** [comment]
FWIW I've reproduced  this inconsistently in non-AT sites. And randomly among a few other sites, which were not AT either.

**Comment by designsimply** [comment]
> @designsimply Did you test this with an AT site specifically?

Yes. I couldn't reproduce the problem with AT either. See 145-gh-automated-transfer.

**Comment by retrofox** [comment]
> FWIW I've reproduced this inconsistently in non-AT sites. And randomly among a few other sites, which were not AT either.

you should be careful since if I'm not wrong we have two issues here. One is into calypso. In this case to udpating site settings is successfully for Jetpack sites. The another one is for AT sites. IN this case the option isn't updated.

**Comment by oskosk** [comment]
I should close this issue because @retrofox is right. If we cannot reproduce consistently in non-AT sites, this issue is not helping as it is right now. If this symptom arises again, we can reopen it.
