### ISSUE TITLE
Reader: Long tags get cropped in <480px

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#13192]
#### Steps to reproduce
Example URL: https://wordpress.com/read/search?q=reinhold%20staden%20photography

This also crops out the Follow button:
![screenshot 2017-04-18 13 06 53](https://cloud.githubusercontent.com/assets/4924246/25150769/e91df884-2437-11e7-9e49-8dc14fd57630.png)

**Comment by fraying** [comment]
To be clear, it's okay that they get cropped, they should just fade on the right like normal. And, of course, the follow icon shouldn't get forced off screen.
