### ISSUE TITLE
Reader Analytics: Missing calypso_traintracks_interact for Recommendations and Related Posts

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#13201]
When a user follows a site from Recommendations (in /read/ or /read/search) and Related Posts (full post view - /read/[siteid]/post[postid]), there is no calypso_traintracks_interact event with `action=site_followed`.

**Comment by fraying** [comment]
Does this mean we haven't been tracking follows from in-stream recommendations and fullpost More links since the refresh? If so, arg, what a bummer.

**Comment by aaronyan** [comment]
@fraying: we're tracking follows in Tracks! :) we trigger the `calypso_reader_site_followed` event no problem! But we're not tracking the traintracks version of follows (`calypso_traintracks_interact`). Our Tracks data is complete, but our TrainTracks data is incomplete.

**Comment by fraying** [comment]
@aaronyan Phew! Thanks for explaining (here and in Slack).

**Comment by aaronyan** [comment]
#13253 fixes this bug. 🎉
