### ISSUE TITLE
Reader: Add URL (and Last Updated) to ReaderSubscriptionListItem component

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#13207]
The `ReaderSubscriptionListItem` component needs to be updated to include the Site URL to match the updated design.

This is because some sites have generic titles and you may have a hard time determining which one you're looking for.

**Example:**
<img width="758" alt="screen shot 2017-04-18 at 9 42 46 am" src="https://cloud.githubusercontent.com/assets/4924246/25189111/18015b28-24dd-11e7-9e98-750a3d199529.png">

**Updated design:**
![manage-following- desktop 003](https://cloud.githubusercontent.com/assets/4924246/25159884/892f4b78-2467-11e7-8244-a6f7d9eb1150.jpg)

**Mobile:**
![manage-following- mobile 002](https://cloud.githubusercontent.com/assets/4924246/25159902/9e6a4010-2467-11e7-87ac-6abbb26279ca.jpg)

However, only your Following list needs to include "Last updated [ time ]". This is useful in determining dormant accounts should you need to purge your list.

**Comment by bluefuton** [comment]
We now have URL, but are waiting on last updated (which requires an API patch).

**Comment by samouri** [comment]
api patch landed.  making a branch now with last updated in it

**Comment by jancavan** [comment]
Done in: https://github.com/Automattic/wp-calypso/pull/14018
