### ISSUE TITLE
WordAds: Settings for .com sites could show a 'banner' asking users to apply

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13224]
WordAds is currently quite hidden for .com sites. I think we should mirror the Jetpack settings model and show a `banner` component in the /traffic tab of settings for all sites. WordPress.com sites would be invited to apply via the banner (even if we direct them to WordAds.co). This will keep things in sync. 

cc @dbspringer @jonathangilmoreburke

**Comment by sirreal** [comment]
What's the status of this? Is it in the discussion/proposal phase or is it ready to for implementation?

**Comment by rickybanister** [comment]
In #12842 @tyxla asked a similar question—I need to do a mockup of what this card would look like for .com sites. 

It's on my list to hit the design this week.

**Comment by rickybanister** [comment]
I just opened a duplicate ticket with a mockup in #14489 so closing this.
