### ISSUE TITLE
Domains: better feedback about "existing site" option

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#13225]
The latest iterations of the add site flow for domains include an option to connect the domain to an existing WordPress.com site. This was added in #12196 and there's a later iteration in #12635.

The concept of "existing WordPress.com site" may not be very clear to all users, making this option quite vague. Many users will be confused about whether they have an existing site all, and whether they have a WordPress.com site specifically. 

A possible quick fix would be to better explain this on the next screen, when selecting the site. We already planned to add something there in #12196, related to Jetpack sites.

This note should cover both cases:

> If your site is not on this list, we can't connect the domain automatically. You can [purchase example.com now](#) and connect it to your site later. 

The link should go to the "just domain" flow (same as going back and choosing the "just domain" option.)

**Comment by alisterscott** [comment]
I believe this has been covered and this is how it currently reads:

<img width="983" alt="screen shot 2017-07-18 at 12 50 33 pm" src="https://user-images.githubusercontent.com/128826/28299516-1c41680a-6bbd-11e7-93ea-9d59cf296d10.png">

I have raised an enhancement to the appearance of the button and some minor copy changes here: https://github.com/Automattic/wp-calypso/issues/16319
