### ISSUE TITLE
Domains: improve the flow for resending verification email

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#13231]
![image](https://cloud.githubusercontent.com/assets/426518/25189061/be9a4bfe-2530-11e7-8cac-e4156337dd5f.png)

The flow for resending the verification email is confusing. It's not clear enough that further action is required after resending the email.

* The use of color and icon in the notice is not appropriate for a first step in the flow. It looks like the flow is finished, but it's just getting started. 
* The position of the notice does not immediately suggest a direct result of user action action, so further reinforcing the feeling that hitting the button = verifying the domain.
* The button label is quite vague, something more direct cold work better: "Send link again".
* The ICANN reference in the notice text (or any other text) should be removed.

See also discussion in p2MSmN-5Y4-p2.

**Comment by klimeryk** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/2478
