### ISSUE TITLE
Settings > General: Manage your Connection page

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13232]
With our settings unification and reorganization we've been able to do some design work that cleans up the poorly-considered 'Jetpack' card block on the General tab. It contains info about 'sync', a strange link to your monitor settings and a disconnection link. Some of these items are a8c-only.

Currently:

![image](https://cloud.githubusercontent.com/assets/437258/25189117/403e9b64-24f6-11e7-9c8a-0164ae05693a.png)

**Proposed:**
_A new Site Tools card would let users access a new screen where they can manage their connection. See #12169 for "Site Tools"_

![image](https://cloud.githubusercontent.com/assets/437258/25189262/a6534e86-24f6-11e7-9424-aa884bfd3f64.png)

_Manage Connection page:_

The ‘Manage your connection’ block would take them to a subpage at `/settings/general/manage-connection` to handle settings related to their connection, obviously! This screen will include settings and read-only info regarding:

* The site owner (person that initiated the initial WordPress.com connection). In the first image below you can see how it will look for a site with multiple connected admins. The primary owner will be able to transfer ownership of the connection to another admin, as in the case of a developer setting up a site for someone. For single-user sites or if a non-owner is viewing this page they will see a read-only view of the current owner.
* Information about sync and a text-link to manually initiate a sync. Our current design (done by me) makes the ‘initiate a manual sync’ button too prominent. This isn’t something that should be necessary unless something really strange is going on. I showed the card with a manual sync in progress, just for illustration. Most of the time this will be a boring card. We could perhaps leave a note there that the sync is up-to-date, but I’m not sure how necessary that is.
* Diagnose a connection problem link—for now this can just link to the jetpack.com debug tool, but I have big hopes for this being a more robust connection fixer, clear out any weird connection cachey stuff, basically the mythical ‘cycle connection’ process we all dream of.
* And finally a disconnect from WordPress.com pathway. This will be the only place on WordPress.com you can disconnect. It will finally and adequately explain the ramifications of disconnecting (for free users and users with plans). Perhaps someday we will direct folks here from wp-admin if they wish to disconnect Jetpack. Of course they can just delete the plugin, but I’d love to be able to give them more info first.

![image](https://cloud.githubusercontent.com/assets/437258/25189321/d54cd928-24f6-11e7-8517-a37c77831da2.png)

If there is only one connected user, or the user looking at this page is not the current connection owner they would simply see a ‘read-only’ view of the site owner, like this:

![image](https://cloud.githubusercontent.com/assets/437258/25189394/05d20672-24f7-11e7-8dbe-96b0eaf75c14.png)

See p6TEKc-18b-p2 for more info

**Comment by tyxla** [comment]
The "Manage Connection" page will need some Redux functionality in order for us to be able to integrate the Site Ownership card. I've implemented it in the following PRs:

* #15599 - Introduce Jetpack user connection data to Redux
* #15600 - Introduce `isJetpackSiteConnected` selector

Once we land these, I'll start working on the "Manage Connection" page and its UI.

**Comment by tyxla** [comment]
I've started #15716 which suggests a **Manage Connection** page with a **Site Ownership** card. After we land it I'll iterate and add the rest of the cards to this page gradually in separate PRs, and at the end I'll add a link to this page in the **Site Tools** card in the **General** settings section.

**Comment by rickybanister** [comment]
I'm so excited for this! Especially after support week.

**Comment by tyxla** [comment]
@rickybanister it could use your review as well 😉

**Comment by tyxla** [comment]
@rickybanister #16353 introduces the Data Sync card, and #16354 addresses the Jetpack sync panel visual changes that are in the mockups.

**Comment by tyxla** [comment]
With regards to the Data Sync card and the stuff we're moving away from the Jetpack card in the General settings section, I have several questions @rickybanister:

- Should we also move over the API cache "Use synchronized data to boost performance" toggle too?
- Should we also move the legacy pre-JP-4.2 "Allow synchronization of Posts and Pages with non-public post statuses" toggle too?
- Should we remove the Jetpack card from the General tab entirely after introducing the Manage Connection page?

**Comment by rickybanister** [comment]
I believe I answered those in the PR—let me know if I adequately responded!

**Comment by tyxla** [comment]
You definitely did @rickybanister, thanks 👍

**Comment by tyxla** [comment]
Since we've integrated everything that was planned for the Manage Connection page for the v1, it's time to add the link to it, and remove the legacy Jetpack card from General settings. #16461 takes care of that.
