### ISSUE TITLE
Signup: Theme Picker in new customer flow can't select a site; new customers don't have sites

### ISSUE THREAD

**Issue by Essayoh** [Automattic/wp-calypso#13246]
#### Steps to reproduce
1. Open an incognito window. Starting at URL: https://wordpress.com/create-website/ OR https://wordpress.com/easy/
2. Scroll down past the featured Themes
3. Click "Browse Themes"
4. Select a Theme
5. Click "Activate this design"
6. Click the "Activate on:" arrow selector

#### What I expected
At step 4, after Theme selection, I'd be pushed to wordpress.com/start/with-theme/domains-theme-preselected with the additional references to my chosen Theme

#### What happened instead
I went through the flow for an existing customer who has a site - but since I have no site, I get an infinite spinner after step 6.

#### Browser / OS version
Chrome Version 57.0.2987.133 (64-bit)
Mac OS Sierra 10.12.4 

#### Screenshot / Video
![themebug](https://cloud.githubusercontent.com/assets/3925776/25197401/e99c6004-2511-11e7-8476-b50c9c9508b8.gif)

**Comment by folletto** [comment]
Me and @Essayoh checked this together and we found out it's highly likely still a case of #11766. 

Closing, and leaving a comment on a flow to test on the other issue.
