### ISSUE TITLE
Toggle: hovering the label should activate the toggle's hover state

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13244]
@jeherve noticed in Jetpack that hovering the label does not trigger the toggle's hover state:

https://github.com/Automattic/jetpack/issues/6878

Now that the label can activate the toggle, let's make sure hovering also triggers the hover state.

**Comment by tyxla** [comment]
Unassigning me and @oskosk as @sirreal takes care of this in #13265.
