### ISSUE TITLE
Jetpack / Traffic: do not offer to go to wp-admin to activate specific module

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#13255]
Originally reported here:
https://github.com/Automattic/jetpack/issues/7001

#### Steps to reproduce
1. Starting on a Jetpack site using a Professional plan, where both the Google Analytics module and the SEO Tools haven't been active yet.
2. When going to Jetpack > Settings in wp-admin, you get a link to Calypso to configure your SEO / GA settings.
3. In Calypso, you get a notice that the module is inactive, and a link to wp-admin to activate the module.

Since wp-admin doesn't include any UI to activate those modules anymore, we should see about removing the notices, and instead automatically enable the modules as soon as a setting is changed / saved in Calypso.

See discussion [here](https://github.com/Automattic/jetpack/pull/6544#issuecomment-284000262) for more background about this.

cc @oskosk @dereksmart

**Comment by jeremeylduvall** [comment]
This was also reported in #3184772-t. Will follow-up with the user as soon as this is closed.

**Comment by oskosk** [comment]
The fix has been waiting for review at #13268.
