### ISSUE TITLE
Billing: can't search for upcoming charges

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#13254]
1. Navigate to https://wordpress.com/me/purchases/billing
2. Scroll down to Upcoming Charges
![screen shot 2017-04-19 at 4 32 11 pm](https://cloud.githubusercontent.com/assets/1270189/25206620/055f39b8-251e-11e7-981e-8495d125afbf.png)
3. Type some text into the search box
Expected: search to filter entries
Actual: js errors are thrown
![screen shot 2017-04-19 at 4 32 23 pm](https://cloud.githubusercontent.com/assets/1270189/25206625/0c974b08-251e-11e7-82da-1236ef9ad171.png)

cc @tyxla

**Comment by tyxla** [comment]
I'm unable to reproduce @gwwar. Perhaps it happens only with a particular type of purchase, and not with the ones I have right now? Can you help tracing what purchase it occurs with, so I can reproduce and address it?

**Comment by gwwar** [comment]
Look like it's a mapping for one of my old AT sites. We can probably just bulletproof here and early exit if val is null/undefined. https://github.com/Automattic/wp-calypso/blob/master/client/me/billing-history/table-rows.js#L28
![screen shot 2017-04-20 at 11 56 14 am](https://cloud.githubusercontent.com/assets/1270189/25247766/bda75080-25c0-11e7-9d08-1be0f5ac46db.png)

**Comment by tyxla** [comment]
I've suggested a fix in #13290. It takes a different approach - filtering the `null` and `undefined` searchable objects earlier.
