### ISSUE TITLE
Masterbar: Refactor and isolate logged out functionality

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#1326]
At the moment, the Masterbar is coupled heavily to logged-in dependencies and components. This makes it both hard to reason about, and hard to server side render. 

Let’s refactor the Masterbar, so it:
- [x] Is decoupled from logged-in and logged-out scenarios
- [x] Is rid of unnecessary subcomponents
- [x] Reads better

We should get https://github.com/Automattic/wp-calypso/pull/631 in before we start.

@mtias — do you have any refactoring tasks to add here?

**Comment by ehg** [comment]
Noting we should ES6ify and normalize the name of the `StatsItem`, introduced in https://github.com/Automattic/wp-calypso/pull/1894

**Comment by ockham** [comment]
Closed by #1918+#2036
