### ISSUE TITLE
Plugins: Unable to view plugin information - Syntax error

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#13266]
#### Steps to reproduce
Tested using a Jetpack enabled site and a site with a WordPress.com business plan. 

1. Starting at URL: https://wordpress.com/plugins/browse/:site:
2. Click to view a plugin where you arrive at a URL such as https://wordpress.com/plugins/hello-dolly/:site:
3. The plugin information does not load

#### What I expected
I expected to be able to view the plugin information and choose to install it

#### What happened instead
The information never loads. In the console you get a Syntax error. 
```
SyntaxError: Unexpected token ':'. Parse error.
(anonymous function) — hello-dolly.jsonp=__jp3:1
```
From Safari

#### Browser / OS version
Tested in multiple browsers on Mac OS. Safari, Chrome, Firefox

#### Screenshot / Video
<img width="1247" alt="screen shot 2017-04-20 at 6 25 26 am" src="https://cloud.githubusercontent.com/assets/1326294/25227449/e69dccf2-259e-11e7-9a76-a1348f8cf356.png">
From Firefox

#### Context / Source
While testing something separate which involved installing a plugin discovered I couldn't through this path.

**Comment by lamosty** [comment]
Fixed in https://meta.trac.wordpress.org/changeset/5388 by @dd32
