### ISSUE TITLE
Editor: Auto-expand Featured Image meta box with drag and drop

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#13275]
When a user drag an image over the closed featured image meta box, the meta box should expand with a visible drop zone.

In #11839 we added a featured image drop zone to the editor that allows users to quickly upload and set a featured image for the post. However as it currently is, the meta box must first be expanded for the drop zone to be made visible - requiring an additional click and reducing the likelihood that a user wouldn't just click to expand and then click to upload the old way.

**Currently:**
![fi-drop-zone-currently](https://cloud.githubusercontent.com/assets/942359/25235141/48f07c02-25b2-11e7-99e9-2e1117dd142f.gif)

**Comment by michaeldcain** [comment]
Getting addressed in #13283.

**Comment by bisko** [comment]
#13283 has been merged.
