### ISSUE TITLE
Themes: Bootstrap the Redux store for `/design` when logged out

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#1328]
Given that we’re converting `/design` to Redux, we will be able to prefetch state on the server, and bootstrap the global Redux store. The goal here is to reduce the time for ‘page completeness’. If we already have one page of themes bootstrapped, we need one less client-side REST API request. 

TODO:
- [x] Complete `/design` Redux transition (https://github.com/Automattic/wp-calypso/pull/840)
- [ ] Add a way to run a function when the fetchNextPage call stacks have completed, so we wait for fetching data from the REST API on the server.
- [ ] Bootstrap the themes state
- [ ] If we’re going to add this to production, we’ll need caching. Can we use `memcache` on the `node` side for caching the `themes` data? Can we invalidate the same cache group on the PHP side, when the CPTs change?

**Comment by seear** [comment]
Closing, since we do now bootstrap theme state.
