### ISSUE TITLE
Inconsistent Button Links on Create-Website Landing Page

### ISSUE THREAD

**Issue by Essayoh** [Automattic/wp-calypso#13286]
I noticed the “Create  your website” button at the bottom of https://wordpress.com/create-website/ leads to https://wordpress.com/start/blog 

Should it should lead to https://wordpress.com/start instead since all of the other links on that page go to the bare /start URL?

**Comment by alisterscott** [comment]
Confirmed this is no longer an issue on https://wordpress.com/create-website/ at the bottom as it goes to https://wordpress.com/start
