### ISSUE TITLE
Reader Search: anything with "of" returns no results

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#13284]
On the [search](wordpress.com/read/search) page within Reader, any query containing the word "of" returns no results.

Example:
![](https://cldup.com/8VJPjpfA7d.png)

cc @gibrown

**Comment by fraying** [comment]
A good test: https://wordpress.com/read/search?q=game%20of%20thrones

**Comment by bluefuton** [comment]
@gibrown noted in Slack that it's related to https://github.com/elastic/elasticsearch/issues/22478.

**Comment by gibrown** [comment]
Fix deployed to api

**Comment by fraying** [comment]
🎉
