### ISSUE TITLE
Domains: Dates in localized formats interfere with domain warnings

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#13301]
#### Steps to reproduce
1. Have a non-English locale (for example, `it`).
2. Buy a domain.
3. Go to Domain Management after the initial 72 hours.

#### What I expected
No notices - the DNS should have propagated by now.

#### What happened instead
A notice is still shown - the localized date is not parsed correctly.

#### Context / Source
#user-report

Hattip to @dromero20 for the report!

**Comment by klimeryk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dates in localized formats interfere with domain warnings](https://trello.com/c/UNToiSV1/108-dates-in-localized-formats-interfere-with-domain-warnings)

**Comment by umurkontaci** [comment]
Probably a good idea to send ISO8601 format from the API

**Comment by klimeryk** [comment]
Good idea - checked the moment.js API and that's what they expect first (I kinda assumed that unix timestamp would be easily supported too - probably worked in PHP too often lately ;)). Thanks for the suggestion!
