### ISSUE TITLE
[Domains] SiteRedirect: Cannot purchase a site redirection if there is one already in the cart

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#13303]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/site-redirect/:siteSlug
2. Enter a domain name
3. Click go, you should be redirected to Checkout
4. Go back
5. Enter a new domain name
6. Click go, you should see the error notice "You already have Site Redirect upgrade in the Shopping Cart and can't add another one" with no option to go back to checkout or replace the site redirect product

#### What I expected
I expect to land in checkout to be able to buy my site redirection

#### What happened instead
I was shown an unhelpful error message

#### Browser / OS version
All

**Comment by rachelmcr** [comment]
Here's a screenshot of that error:

![screen shot 2017-08-14 at 7 40 39 pm](https://user-images.githubusercontent.com/8658164/29286055-90d82890-8128-11e7-8778-2fe74b0b619d.png)

If you select the "Back" option in the top left, it takes you back to the Domains search where there's a cart in the top right and you can edit the cart:

![screen shot 2017-08-14 at 7 40 51 pm](https://user-images.githubusercontent.com/8658164/29286078-a4a756a2-8128-11e7-8ba2-00236cbc5a5f.png)

Including something like that on the Site Redirect page as well could help in this case.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by klimeryk** [comment]
Marking this as wontfix, because it's rare enough to add a Site Redirect, let alone try to add two or more at once.
