### ISSUE TITLE
.org plan: Renewal date

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#13307]
from `pNPgK-2uc-p2`:

This is the first I’ve seen of this error, but my assumption is this is actually effecting all accounts possibly. This user was asking the old age old question of why the plan was renewing at 11 months. Going through their entire account, in their AK dashboard, in BD, and in SA, it shows the renewal being 1/25/18, however in their /me/purchases it shows the date being 12/25/2017. Maybe we are trying to give them an xmas present, but I have a feeling this is an error. I’ve included the react debug below:

![image](https://cloud.githubusercontent.com/assets/1554855/25280797/8067275e-26ab-11e7-80b6-57abd1b2a96b.png)

And some clarification by @janm6k : 
```
I guess this is because we apply the wpcom renewal date logic (plan renewals 1 months before expire date) to Jetpack plans, which renew on expire date.
````

**Comment by sirreal** [comment]
This page got a makeover recently and I don't see the problem now:

![plan-renew](https://cloud.githubusercontent.com/assets/841763/26008225/2300f1f4-3744-11e7-9779-ddf126f0ca80.png)

(That is the exact date displayed in SA).

@ryelle Did you come across anything like this? If this were a bug, is it likely that your changes cleaned it up?

**Comment by ryelle** [comment]
I'm not sure I ever noticed this bug, but more from lack of looking for it. however, none of my changes _should_ have done anything for it — I only extracted the existing code to a new component, I didn't change it.

**Comment by sirreal** [comment]
I've just verified that this is not fixed for this user:

![bad-date](https://cloud.githubusercontent.com/assets/841763/26008510/6a35483a-3745-11e7-9e9e-bf916f05bc1f.png)

And I can see the following relevant bits of state:

```js
{
expiryDate: "2018-01-25T00:00:00+00:00",
renewDate: "2017-12-26T00:00:00+00:00",
subscribedDate: "2017-01-25T16:54:57+00:00"
}
```

**Comment by sirreal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/Automattic/wp-calypso/issues/13307](https://trello.com/c/Qk9CC6bb/69-https-githubcom-automattic-wp-calypso-issues-13307)

**Comment by gwwar** [comment]
Maybe we could display both dates (renewal/expiry) to lessen confusion.

**Comment by vindl** [comment]
Note that this bug is no longer reproducible for the user above since their card expires before the plan, and this section is now showing the `Subscription expires on` label and date (which is correct). In order to reproduce it you'll need to sandbox the store and make a Jetpack plan purchase with a credit card whose validity expires after the plan subscription. This will allow you to see the `Subscription renews on` date.

**Comment by vindl** [comment]
Proposed fix in D10669-code.

**Comment by vindl** [comment]
Fix deployed.
