### ISSUE TITLE
Reader Analytics: following site on tag stream does not record `source` value

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#13322]
When a user follows a site in the tag stream, `source=null`; it should be `source=topic_page`.

I did a little bit of digging on this already, and I think we do not provide a `source` value because we're using the old Follow button here (from 'blocks/follow-button/button'). The manage page also uses this button and also does not have a `source` value when sites are unfollowed/followed (using the button).

Other places in Reader we use the Reader Follow button (from reader/follow-button).

Should we migrate these old Follow buttons to the new Reader follow button? or should we update the old Follow button to include `source` event properties?

**Comment by bluefuton** [comment]
@aaronyan good sleuthing! `blocks/follow-button/button` isn't the old follow button as such - `reader/follow-button` is a wrapper around that component that fires some extra stats. 

Sounds like we should be using `reader/follow-button` on the tag stream too.

**Comment by bluefuton** [comment]
@aaronyan just to clarify, is this when following a tag, or following a site on a tag stream?

**Comment by aaronyan** [comment]
Thanks @bluefuton! 

> just to clarify, is this when following a tag, or following a site on a tag stream?

Good question! This is for following a site on the tag stream.

**Comment by aaronyan** [comment]
I recorded this bug incorrectly. The `source` value is being recorded correctly.
