### ISSUE TITLE
Question: How do I push a new branch?

### ISSUE THREAD

**Issue by mknepprath** [Automattic/wp-calypso#13326]
#### Steps to reproduce
I believe I followed the directions correctly so far - got Calypso running locally, created a branch, and made a few edits. Then when I tried to push what I've committed locally, I got this: 
```
wp-calypso git:(fix/13144-galleries-without-ids) git push origin fix/13144-galleries-without-ids
remote: Permission to Automattic/wp-calypso.git denied to mknepprath.
fatal: unable to access 'https://github.com/Automattic/wp-calypso.git/': The requested URL returned error: 403
```

#### What I expected
Expected the branch to be pushed so I could create a PR. :)

Anyone run into this before? Thanks!

**Comment by yoavf** [comment]
@mknepprath You'd want to [fork the repo](https://help.github.com/articles/fork-a-repo/), make the changes on a branch of your own fork, and create a PR out of that.

**Comment by mknepprath** [comment]
@yoavf Thanks, will do!
