### ISSUE TITLE
Flow: Update WC to minimum required version

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#13334]
Story: User attempts to manage their store via Calypso, but their WC version doesn't meet the minimum requirements.

**Comment by jameskoster** [comment]
Initial thoughts are that this might just be an initial dashboard state. We'll beed to be careful though as 3.0.0 looks like being the minimum required version. We don't want to just display a big update button without explaining the significance.

**Comment by justinshreve** [comment]
See #14347
