### ISSUE TITLE
Design: use color schemes set in wp-admin/profile.php

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#1334]
`wp-admin` includes an option to set a specific color scheme for your dashboard:

![screen shot 2015-12-07 at 7 06 17 pm](https://cloud.githubusercontent.com/assets/426388/11635227/9d7a1566-9d15-11e5-9378-244068a71b97.png)

It would be nice if these options were ported to Calypso, so Calypso colors would change to match your wp-admin colors when you would switch sites in Calypso.

Suggested here:
http://halfelf.org/2015/calypso/

**Comment by alexjgustafson** [comment]
3256691-t

**Comment by lancewillett** [comment]
Internal ref: p4TIVU-75d-p2 for related Calypso color schemes project.

**Comment by lancewillett** [comment]
This project is on hold for now, closing. We might revisit in the future.
