### ISSUE TITLE
Fullpost: Justified body text

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13356]
The body text of this post is justified: https://wordpress.com/read/feeds/37525197/posts/1416671702

The original post is also justified: https://thebayougypsy.com/2017/04/12/crazy-chick-love/

Is the CSS sneaking through somehow? 

cc @blowery @jancavan

**Comment by blowery** [comment]
Hrm. Fun edge case. 

So, galleries use inline styles. Normally we strip all the styles in a post, but when we detect a gallery, we skip stripping inline styles for that post. In this case, they have a gallery, and they have the text-justify style on their `<p>` tags....

**Comment by fraying** [comment]
Aha! So that explains why not all of that site's posts are justified, just the posts with galleries.

Can we force the text-align to left in the fullpost css? Or ... some other clever workaround?

**Comment by blowery** [comment]
We might be able to restrict the style allowance to actual gallery elements.. That's probably the best tact.
