### ISSUE TITLE
Help: Make the "HEs have returned" notice dismissable

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#1337]
Repro:

1. Target a chat group with no operators available.
2. Load /help/contact.
3. Observe that the form will submit a ticket.
4. Have an operator become available and wait a moment.
5. Observe the green notice that an operator is available.

I'm thinking it might be nice if we could dismiss this notice, since if you've already scrolled down a bit, it covers some of the UI and is kind of annoying. I think maybe there is built-in dismiss UI/functionality in the notification component and that we just need to set a prop or something. Here's what it looks like at present:

![screen shot 2015-12-07 at 1 34 52 pm](https://cloud.githubusercontent.com/assets/2738252/11636000/d59615fe-9ce7-11e5-8c03-6feaac225f89.png)

**Comment by dllh** [comment]
The same is true for the "we've stepped away" notification.

**Comment by omarjackman** [comment]
this actually used to disappear after 10 seconds. I'm not sure what changed but i'll look into it
