### ISSUE TITLE
Reader: combined cards don't show post options

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#13379]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Follow a few blogs, making sure to follow a couple more prolific blogs so combined cards will be triggered. Alternatively, search a tag - this issue was reported by a user following the "programming" tag: https://wordpress.com/tag/programming

#### What I expected
To see the options menu to follow/unfollow, block and report a post on all WordPress.com posts in the stream

#### What happened instead
The options menu doesn't show for posts being displayed in combined cards. Clicking on a post opens the single view where the follow/unfollow option is at least visible, but there is no way to block the site from the Reader stream unless one scrolls far enough to spot a post from the site in its own card, and there is no way to report posts in combined cards.

#### Screenshot / Video
![programming_ _reader_ _wordpress_com](https://cloud.githubusercontent.com/assets/11873759/25397186/aa6fa35c-29e7-11e7-8ba8-e0ae108b978d.png)

#### Context / Source

Reported via the WordPress.com forums, in 852408-f

**Comment by fraying** [comment]
Thanks, @KokkieH!

I think the solution here is to add the ellipsis menu to the bottom, right corner of Combined Cards. The menu would just include Follow and Block. The other items (Edit Post, Report Post) are post-specific, so shouldn't be included because Combined Cards contain many posts. 

What do you think, @jancavan?

**Comment by jancavan** [comment]
@fraying If we add it to the bottom, visually, I think it may look like the ellipsis is only for that one particular post. But we'll have to add it to see how it feels.

**Comment by fraying** [comment]
@jancavan Yeah, let's try it. I think putting it anywhere else will feel extra weird, because then the cards would be inconsistent.

**Comment by fraying** [comment]
Update: The ellipsis menu should contain:

- Follow (or Following)
- Report Site (linking to existing https://wordpress.com/abuse/ process)
- Block Site (current process)

I'd left "Report" out before because I thought it was just for posts, but the abuse process can take site URLs too.

**Comment by jancavan** [comment]
I think we should still consider adding this so let's keep this open.
