### ISSUE TITLE
Themes: Fix Reconciliation Error

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#13376]
To repro:
* Run Calypso locally (error is hidden in production)
* In an incognito window, land at http://calypso.localhost:3000/themes
* Check the console:

![image](https://cloud.githubusercontent.com/assets/96308/25394078/8b88ebba-29dd-11e7-8060-1d33dded39eb.png)

This was probably caused by https://github.com/Automattic/wp-calypso/pull/13010

**Comment by ockham** [comment]
cc @klimeryk -- I missed this when reviewing #13010

**Comment by klimeryk** [comment]
Oh, crap, can't believe I missed it too :/ I'm not sure how to fix it, though. I can't find (in our code or on Google) a readily available substitute for `window.location` on Node 🤔 If nothing comes to mind, I'll dig deeper, just wanted to make sure I'm not missing something obvious.

**Comment by ockham** [comment]
No worries, this is a somewhat recurring and unresolved issue. There's no obvious counterpart on the server side since due to client-side routing, the user might have navigated to a different location in their browser than the request was originally served for. We might try and use Express' [`req.originalUrl`](http://expressjs.com/en/api.html#req.originalUrl) which might work well enough in a React setting.
