### ISSUE TITLE
Framework: track clicks in sidebar for future flow analysis

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#13370]
Would be useful to have explicit tracking of the clicks in the sidebar:

1. It would allow to check quickly the balance between the various entries.
2. It would allow to check for navigation explicitly instead of page views (which might come form other sources)
3. It would allow to check how many people get to a page from any mean other than sidebar (by checking the difference page views and sidebar clicks).

The even might be called: `calypso_sidebar_mysites` and have the various destination urls (or names? both?) as _properties_ so we can get them all aggregated and visualized together.

---

This idea emerged from the discussion in #13176.

**Comment by sirreal** [comment]
I started to look at this in #21760, but a lot of changes across a lot of components would be needed. This "small" change quickly became very complex. If we don't have immediate and compelling reasons to proceed here, I suggest we wait until we _do_ have immediate and compelling reasons 🙂
