### ISSUE TITLE
Longer excerpt text for Rec Posts without images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13388]
In Rec Posts (on Search default and in Following stream), when the post doesn't have an image, we should show more text so that the post is about the same height as a post with an image.

We used to do this. Not sure when it changed.

Example in Following Stream:

<img width="832" alt="screen shot 2017-04-25 at 11 59 34 am" src="https://cloud.githubusercontent.com/assets/24388/25402791/b57c4dec-29ae-11e7-89a0-1bdeddbd90ac.png">

Example on Search Default:

<img width="847" alt="screen shot 2017-04-25 at 10 16 15 am" src="https://cloud.githubusercontent.com/assets/24388/25402722/7e4a5b34-29ae-11e7-9dbe-939eeb49f7ae.png">

**Comment by fraying** [comment]
The alternative, of course, is to not show these posts.

**Comment by jancavan** [comment]
> we should show more text so that the post is about the same height as a post with an image.

I think we did this in full-post recs, but then later opted to omitting posts without images.

**Comment by jancavan** [comment]
Upon checking again, I think we're using the longer version of excerpts for those without images, so I can just readjust the max-height value for them. Should we do that instead of completely omit them?

**Comment by aaronyan** [comment]
>The alternative, of course, is to not show these posts.

**Comment by fraying** [comment]
> Upon checking again, I think we're using the longer version of excerpts for those without images, so I can just readjust the max-height value for them. Should we do that instead of completely omit them?

Oh great. Yes, please and thank you.
