### ISSUE TITLE
Help: Form validation needs improving

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#1338]
Repro:

1. Target a chat group with opers available.
2. Navigate to /help/contact and begin typing a chat message.
3. Set all operators to unavailable.
4. Observe that the yellow notification appears and the form changes into a ticket form with a subject line.
5. Observe that even with text in the main text field, the "Submit support ticket" button is disabled.

Here's what it looks like at this point:

![chat-ticket](https://cloud.githubusercontent.com/assets/2738252/11636546/a808e370-9cea-11e5-9a4b-df007894b2cd.png)

If I haven't noticed that the subject line has been added, I might be puzzled as to why the form can't be submitted (in fact, I was puzzled by this).

I'm not 100% sure what the proper fix is here, but I wondered about populating the subject line with the first N words or characters from the big text field in this case (if empty), so that there's not a moment in which the user is puzzled because of a change that occurred during typing that necessitates the filling out of a field that didn't exist before and that the user may not have seen.

**Comment by omarjackman** [comment]
@dllh I'm not 100% sure either but making it the first N words doesn't sound like a bad idea to me. Want me to just spin up a PR for this and see what works best?

**Comment by dllh** [comment]
Yep, if that's pretty simple (seems like it would be), let's give it a shot.
