### ISSUE TITLE
Default Search Page can show recommendations in results format

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13386]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/search
2. Note the top, left recommended post title
3. Do a search for any text - wait for results to load
4. Click "Search" in the sidebar

#### What I expected

Search should go back to default state - no term in box, recommendations showing, in recommendations format.

#### What happened instead

Search term remains in box. Recommendations appear, but formatted like results. Very confusing.

#### Browser / OS version

Tested in Chrome and Safari.

#### Screenshot / Video

https://cloudup.com/cOTnB-YMyKm

**Comment by fraying** [comment]
@blowery @samouri Any ideas on this one?

**Comment by samouri** [comment]
ah, sorry. I didn't see this issue earlier! This should be an easy fix.

**Comment by samouri** [comment]
nevermind, this is more complicated than i thought. working on it now
