### ISSUE TITLE
Reader Search: Post's text centered

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13384]
On this search: https://wordpress.com/read/search?q=botany

This post's text is centered: https://wordpress.com/read/blogs/43201448/posts/2248

<img width="843" alt="screen shot 2017-04-25 at 11 23 43 am" src="https://cloud.githubusercontent.com/assets/24388/25401201/edbf5582-29a9-11e7-9f4a-8cc3eb1d8fd0.png">

@blowery Is this the same problem as https://github.com/Automattic/wp-calypso/issues/13356 ?

**Comment by blowery** [comment]
Nope, looks like we're not stripping align attributes from tags other than img.
