### ISSUE TITLE
Help: UI doesn't respond to the return of chat operators

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#1339]
Repro:

1. Target a chat group with operators available.
2. Navigate to /help/contact and begin typing a chat message.
3. Set all operators to away.
4. Observe that the form pretty quickly changes into a ticket form.
5. Set an operator to available.
6. Wait for the form to resume being a chat form.

My expectation is that just as the form becomes a ticket form when operators are unavailable, it'll turn back into a chat form once operators become available again. I've tried waiting for a couple of minutes after toggling operator status back to available, and the form doesn't change back. If I reload the page, the form is a chat form. Is there any technical hurdle to turning the form back into a chat form when we have operators available? I think it would be ok to discard the subject field in this case, or possibly to add it to the snippet info we send along, if it's not empty.

**Comment by rachelmcr** [comment]
I just tested this at https://wpcalypso.wordpress.com/help/contact, with these results:
- When the operators went away, I was taken to the ticket form (and filled out a subject line)
- When the operators returned, I was taken back to a chat form (with everything I previously selected still in the form, minus the subject line)

So at least for me it worked as expected without having to reload the page. I tested in Firefox 42.0 on Mac OS X 10.11.1.

**Comment by omarjackman** [comment]
@dllh I think using the `!develop` command in olark may cause weird behavior like this. Try clearing your cookies or starting fresh from an incognito window if thats the case.

**Comment by dllh** [comment]
I didn't think I had any old `!develop` junk left over, but I've tested this in an incognito window and it works as expected, so I'm closing this.
