### ISSUE TITLE
Sidebar: CPT named "Design" broken due to conflicting CSS

### ISSUE THREAD

**Issue by hrsetyono** [Automattic/wp-calypso#13395]
#### Steps to reproduce
1. Register a post type named "design", label is "Design".
1. See the sidebar at Calypso

#### What I expected
The sidebar item looks normal

#### What happened instead
The sidebar item become misaligned like screenshotted here http://imgur.com/a/CjQ2Y

This is caused by Calypso adding ".design" class on the wrapper and that class is defined somewhere else

#### Browser / OS version
Latest Chrome / Windows 10.1

#### Screenshot / Video
http://imgur.com/a/CjQ2Y

![uebvhxsa](https://cloud.githubusercontent.com/assets/1119271/25819760/37c4a3b6-33ec-11e7-8a30-2c8180fda834.png)

#### Context / Source
I want to create CPT named "design" and noticed the broken sidebar item when accessing via Calypso.

**Comment by marekhrabe** [comment]
Hi @hrsetyono, the bug is now fixed in production on WordPress.com. Thanks a lot for your report! :)

**Comment by hrsetyono** [comment]
Thanks for the prompt fix! Now I don't need to rename my CPT
