### ISSUE TITLE
Can't access My Site in Microsoft Edge/IE11 on Windows (new single site user)

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#13398]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start on Microsoft Edge or IE11
2. Sign up for a free site
3. Once signed up, visit wordpress.com and click "My Site"

#### What I expected

Dashboard (stats)

#### What happened instead

Blank page

Console error:
`Unable to get property 'getHostNode' of undefined or null reference`

#### Browser / OS version

Microsoft Edge 38.14393.0.0 (Windows 10)
 
#### Screenshot / Video

Edge:

![edge](https://cloud.githubusercontent.com/assets/128826/25419290/09d42c66-2a95-11e7-9535-eea2d5d19c26.gif)

IE11

![ie11](https://cloud.githubusercontent.com/assets/128826/25419285/01276128-2a95-11e7-85af-e9e63ef13463.gif)

**Comment by alisterscott** [comment]
This may have been introduced in #13196

cc: @ockham

**Comment by ockham** [comment]
This is possibly not IE specific. Trying this locally from up-to-date `master` (to see more console errors), I'm getting

![image](https://cloud.githubusercontent.com/assets/96308/25433161/c31467da-2a87-11e7-9801-114c3ddf20ec.png)

@alisterscott Can you repro that?

**Comment by designsimply** [comment]
Tested with Edge 14 (Microsoft Edge 38.14393.0.0 and EdgeHTML 14.14393) on Windows 10 with an already-existing account on production and didn't find any problems. I did see several 404 errors for `.scss` files on widgets.wp.com:

![bs_win10_edge_14 0_170426](https://cloud.githubusercontent.com/assets/1119271/25442123/69cca190-2a61-11e7-81af-224dfa8abfc3.jpg)
<sup>Seen at https://wordpress.com/stats/day/madefortesting532.wordpress.com using Edge 14 on Win10.</sup>

Tested with Edge 14 (Microsoft Edge 38.14393.0.0 and EdgeHTML 14.14393) on Windows 10 for a brand new user sign up starting at https://wordpress.com/start and was also unable to reproduce the problem:

![screen shot 2017-04-26 at wed apr 26 9 18 02 am](https://cloud.githubusercontent.com/assets/1119271/25442114/63eb5b04-2a61-11e7-969f-f2f1d9098038.png)
<sup>Seen at https://wordpress.com/stats/day/madefortesting455.wordpress.com using Edge 14 on Win10.</sup>

**Comment by ockham** [comment]
Yeah, this kind of issue is quite hard to repro. I'm pretty sure now the culprit is [this line](https://github.com/Automattic/wp-calypso/blob/06d9e93ff01e4245a7e8d4549dc6eaad33384ba5/client/my-sites/sidebar/sidebar.jsx#L297), so I'll modify #13409 to guard against falsey `site`.

**Comment by seear** [comment]
I can repro with steps:
1) logged out, go to https://wordpress.com/themes
2) sign in with an existing single-site user

**Comment by alisterscott** [comment]
Thanks for the fix, retested my steps in MS Edge and can no longer reproduce this bug.
