### ISSUE TITLE
Domains: Can't manage a purchase on a domain-only site

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#13390]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Click on a domain on a domain-only site.

#### What I expected
A view that allows me manage my purchase (especially cancel it).

#### What happened instead
I got a weird-ish view of the nudge we show on domain-only sites:
<img width="1278" alt="screen shot 2017-04-25 at 22 21 10" src="https://cloud.githubusercontent.com/assets/3392497/25407735/bdd9ad1a-2a0b-11e7-85d9-fa63d002bf3b.png">

The view is slightly off (notice the `Switch Site` link is moved a bit, etc.), but there are no console errors.

#### Context / Source
#dogfooding #manual-testing

**Comment by aidvu** [comment]
Fixed https://github.com/Automattic/wp-calypso/pull/13422
