### ISSUE TITLE
Help: Ending a chat results in the "leave a message" chat box

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#1340]
Repro:

1. Target a chat group with operators available.
2. Load /help/contact.
3. Initiate a chat.
4. Navigate around a bit (away from /help/contact).
5. As an operator, end the chat. In my test, I was the only operator available, and I was at my chat limit, so when I ended, no operators were available.

I wound up seeing this after the chat ended:

![screen shot 2015-12-07 at 2 12 15 pm](https://cloud.githubusercontent.com/assets/2738252/11636988/e92aba16-9cec-11e5-9dcb-5b42ee47d1bc.png)

It's the offline message form, but there's not a way to fill it out. It seems like we'd want the chat box to behave differently in this case. It may be ok to show the "Leave a message" form (in fact, Olark may not afford us much of an alternative), but if we do, it should be submittable (note from the screen capture that there's no button and no text entry field). 

Or maybe we should just hide the box altogether when a chat ends, since by default it won't be displayed at bottom right all the time anyway once this ships.

**Comment by omarjackman** [comment]
@dllh, I'm almost certain the form used to show and I'm not sure whats blocking it. Is there an olark admin setting that your'e aware of that would be disabling the ticket form here?

**Comment by omarjackman** [comment]
I figured out that this is controlled by an olark api custom field option called `create_support_ticket` which currently is being set in a less than ideal way. It also seems to stick around via olark cookies so I'm thinking we should probably disable this and stick a link in the bottom of the widget that leads back to the contact form.

**Comment by dllh** [comment]
Hmm, we need that custom field in order for the custom ticket command to work. There's a webhook that looks for it and creates a ticket if needed. I'm not clear on why the existence of the field would affect the chat box at all; it should just send the field along with the transcript. We might need to talk this one through a bit more.

**Comment by omarjackman** [comment]
@dllh so this might be a bug/usability issue in olark. The form disappears when you invoke the `api.chat.sendNotificationToVisitor` api call in the case where your chat has ended and there are no available operators. If you refresh the window the form comes back.

**Comment by dllh** [comment]
Could we detect that case and append a message to the chat box or change the heading to "Your chat has ended" or something? Or if we're not on /help/contact and we get an end event, maybe we just hide the box?

**Comment by omarjackman** [comment]
I was thinking maybe instead of using these olark notifications we could switch to using calypso notifications. What's your thoughts on that @dllh

**Comment by dllh** [comment]
I'm game. Might need a design review sanity check, though.
