### ISSUE TITLE
2FA Reauth "Sign Out" link broken (getLogoutUrl of undefined)

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#13401]
#### Steps to reproduce

1. You must have a WordPress.com account with two-factor auth (2FA) enabled.
1. Log in to https://wordpress.com/me
1. Verify 2FA step.
1. Inspect cookies and remove the 2FA cookie from `https://public-api.wordpress.com` (named `twostep_auth`). This simulates a user who needs to validate 2FA.
1. Reload the page.
1. Click "Not you? Sign Out" in the modal which appears. Open console to see errors.
   ![re-2fa](https://cloud.githubusercontent.com/assets/841763/25424402/89c8d44e-2a68-11e7-83dc-8723f300927d.png)
1. There appears to be async bundle loading at this point, which may take a moment...
1. You should see the following error:
   > Uncaught TypeError: Cannot read property 'getLogoutUrl' of undefined

#### What I expected

To be logged out.

#### What happened instead

Nothing. Console errors:

> Uncaught TypeError: Cannot read property 'getLogoutUrl' of undefined

#### Browser / OS version

* Chrome 60 / macOS
* IE11 / Windows 7

#### Console log

```
Uncaught TypeError: Cannot read property 'getLogoutUrl' of undefined
    at logout (build.4b12e23….m.js:52)
    at build.4b12e23….m.js:60
    at Object.r (vendor.31d2695….m.js:10)
    at a (vendor.31d2695….m.js:2)
    at Object.c [as executeDispatchesInOrder] (vendor.31d2695….m.js:2)
    at l (vendor.31d2695….m.js:2)
    at M (vendor.31d2695….m.js:2)
    at Array.forEach (<anonymous>)
    at n (vendor.31d2695….m.js:10)
    at Object.processEventQueue (vendor.31d2695….m.js:2)
```

#### Additional info

The error appears to occur in `client/lib/user/utils.js`: https://github.com/Automattic/wp-calypso/blob/f10aeefd9653f8c055f0e2489c678ccc5da27ad3/client/lib/user/utils.js#L49

#dogfooding, #manual-testing

**Comment by tyxla** [comment]
Introduced in #13212 - https://github.com/Automattic/wp-calypso/pull/13212/files#diff-6da00fd50561b1fce9cc49d0d30b6464R49.
