### ISSUE TITLE
Themes: social menu filter not available

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#13429]
Steps to reproduce:

1. Go to https://wordpress.com/themes/filter/social-menu
1. Check to see if you get a filtered list of themes with the social menu available as an option.

<strong>Result:</strong> expected to see a filtered list of themes with the social menu available as an option but was redirected to https://wordpress.com/themes instead.

<strong>Note:</strong> link to https://wordpress.com/themes/filter/social-menu was found at https://en.support.wordpress.com/menus/social-links-menu/

**Comment by hoverduck** [comment]
Testing a new comment on a stale issue - Should remove the label

**Comment by hoverduck** [comment]
Testing another new comment on a stale issue

**Comment by lancewillett** [comment]
This is now working correctly: https://wordpress.com/themes/filter/social-menu

Testing with a logged-in user (both Chrome latest on macOS Catalina):

<img width="1404" alt="Screen Shot 2020-03-09 at 15 34 31" src="https://user-images.githubusercontent.com/66797/76263205-84361f80-621b-11ea-93f2-18cb8bcdf2b7.png">

Logged-out user:

<img width="1683" alt="Screen Shot 2020-03-09 at 15 35 28" src="https://user-images.githubusercontent.com/66797/76263246-a039c100-621b-11ea-98d0-cbe25b98d29d.png">
