### ISSUE TITLE
Purchases: Can't manage purchase for a disconnected Jetpack site

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#13421]
A user can purchase a Jetpack plan for a site, but then later disconnect the site. Currently the purchase still shows up under "Manage Purchases", but the user can no longer click into the purchase.

**To reproduce**

- Sign up for a Jetpack plan
- Disconnect your site
- Visit `/me/purchases`, you'll see your purchase
- You can click into other purchases, but not this one

The URL for a purchase should be `/me/purchases/$site/$receiptId`, but since we don't have a site to set in `siteSelection`, it redirects to the `allSitesPath` (`/me/purchases/$receiptId`) which doesn't exist for this section. It looks like this was introduced in the sites-list removal here https://github.com/Automattic/wp-calypso/commit/5997e0fa9f3140c5cc23a67e0e69478209abd4b7 / #13247 @mtias @gziolo

**Comment by ryelle** [comment]
@rickybanister noticed that this also affects wp.com sites — if a user who bought a purchase is removed from the site, they can't click into the purchase detail view.

**Comment by gziolo** [comment]
@fabianapsimoes something to consider to add as a maintenance task for the next sprint.

@ryelle should we allow users to navigate to the purchase when Jetpack site is disconnected or user is no longer able to manage site?

**Comment by ryelle** [comment]
@gziolo I think so — the purchase still belongs to that user, so it's useful at least to see the details. There was also [a message](https://cloudup.com/ci1qhfbwLqX) letting the user know they're not a user on the site anymore, so they could then find out how to get it back.

**Comment by rachelmcr** [comment]
This was reported again in https://github.com/Automattic/wp-calypso/issues/17008:

> To repro:
> 
> 1. Have a Jetpack site connected to WordPress.com.
> 2. Purchase a plan for it.
> 3. Disconnect the site from WordPress.com.
> 4. Try to cancel the plan. You can't.
>
> If the site is disconnected, the place where you'd cancel the plan never loads:

![image](https://user-images.githubusercontent.com/8658164/33944379-ea007e82-e013-11e7-9eec-c606af84f560.png)

> This creates support load for something that, as a user, I should be able to do for myself.

**Comment by sirreal** [comment]
Some background, it appears with #13354 this was working.

**Comment by kriskarkoski** [comment]
This should be fixed by https://github.com/Automattic/wp-calypso/pull/40285. Closing.
