### ISSUE TITLE
Combined Cards showing errant comma for "Admin" bylines

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13431]
This site (https://wordpress.com/read/blogs/118534215) has "Admin" as their author name. And we try not to show the name when that's the case. But we need to add the comma to the if/then because the "Admin" is disappearing from the Combined Card, but the comma is not, resulting in this:

<img width="810" alt="screen shot 2017-04-26 at 11 08 03 am" src="https://cloud.githubusercontent.com/assets/24388/25449704/6cbe7288-2a71-11e7-8a0b-4885acf9a6d7.png">

Screenshot from this tag page: https://wordpress.com/tag/farming

**Comment by bluefuton** [comment]
This is happening because the combined card doesn't know that the author name 'admin' is blacklisted.

I'll move the blacklist logic so the combined card can access it too 👍
