### ISSUE TITLE
Rec Posts Alignment Issues

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13437]
Spinning out of #13435, just wanted to post this image with notes.

<img width="1357" alt="screen shot 2017-04-26 at 1 51 59 pm" src="https://cloud.githubusercontent.com/assets/24388/25456463/ccc5a366-2a87-11e7-96bc-99b22324496b.png">

Notes: 
- Both Follow links on same line.
- Both gravatars on same line.
- Posts start on same line, image or not.
- Last lines in each post end on same line.

Feel free to adjust the height of the image in order to make it all line up.

Make sense, @jancavan?

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/13444
