### ISSUE TITLE
Reader Following Manage: left-align action links

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13433]
Right now, all the main action links (Follow, Following, Settings) are right aligned, so they form a ragged left edge. This is visually discordant and causes the icon to move when it changes from "Follow" to "Following".

These links should be left-aligned to a common line, like so:

<img width="1097" alt="screen shot 2017-04-26 at 11 43 07 am" src="https://cloud.githubusercontent.com/assets/24388/25450999/8ea01ede-2a75-11e7-8fa7-a1f6545151d0.png">

This way they all start from the same place in the column, and the icon doesn't move when changing from "Follow" to "Following".

This was probably on your list already, @jancavan. Just putting it here to track it.

**Comment by blowery** [comment]
We'll need to check the translated variants here too...

**Comment by bluefuton** [comment]
@jancavan is looking at this in #13787.

**Comment by blowery** [comment]
Looks to be fixed. Please re-open if not.
