### ISSUE TITLE
Site View and "Admin" bylines

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13432]
Two problems with the Site View and Admin bylines. For example: https://wordpress.com/read/blogs/118534215

<img width="816" alt="screen shot 2017-04-26 at 11 08 47 am" src="https://cloud.githubusercontent.com/assets/24388/25449898/145a8806-2a72-11e7-91a5-2da18ab9b91a.png">

1. We shouldn't show "by admin" in the header. If the name is "Admin" there, we should hide the whole byline here like we do in cards.

2. In the cards, because we're hiding "Admin" and the site name, there's a blank line at the top of every card. That blank line should be omitted. 

So it should look like this:

![sv-admin-fixed](https://cloud.githubusercontent.com/assets/24388/25450059/99026ba0-2a72-11e7-9bd0-0324f66f17bb.png)

**Comment by mknepprath** [comment]
@fraying I've created a PR for this issue if you'd like to look it over: #13546 

Thanks! :)

**Comment by fraying** [comment]
@mknepprath Woot! Thank you.
