### ISSUE TITLE
Instagram Embed not working

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#13440]
#### Steps to reproduce
1. Open an Instagram picture in a browser ([this one](https://www.instagram.com/p/BSnhPuCjLa-/?taken-by=adamjk) was used for the example).
2. Click on the three little dots on the bottom right side, and then 'Embed'. 
3. Copy Embed Code (Including caption) 
4. In WordPress.com, open a new page (or post, or widget, I tried them all) and in the HTML tab, paste the Embed code. 

#### What I expected
Seeing the Instagram post entirely.

#### What happened instead
The image is not shown, but the rest of the content of the Instagram embed shows. Also, there is a line of code underneath the embed. 

#### Browser / OS version
Firefox 53.0 / 10.12.4

#### Screenshot / Video
[Post screenshot](https://cloudup.com/c5H9DrcMshG), [page screenshot](https://cloudup.com/ck-fkW0I64q), [widget screenshot](https://cloudup.com/cKCRR8aVGut)

#### Context / Source
A user reported this in live chat. #user-report

**Comment by boostmoth** [comment]
I also have a user who reported this #user-report in live chat tonight.

**Comment by rachelmcr** [comment]
Closing as this behavior will be superseded by how Gutenberg handles embeds.

#bug-scrub #pre-gutenburg-bug-purge
