### ISSUE TITLE
Framework: Make & Run breaks if "&" is in any Directory in the path

### ISSUE THREAD

**Issue by clubdesign** [Automattic/wp-calypso#1345]
Hey Guys.

I just wanted to install wp-calypso, i had to move the installation folder because the ``make run`` breaks if i have an ``&`` within the path.

It seems to break the path at ``&``:
```
/bin/sh: *** : No such file or directory
/bin/sh:  ***/wp-calypso/node_modules/.bin/webpack: No such file or directory
```

Greets Marcus

**Comment by klimeryk** [comment]
Thanks for reporting! This has been fixed by #3583 :)
