### ISSUE TITLE
Settings: Icon displayed outside container

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#13451]
One of the popover info icons is displayed outside of its container.

#### Steps to reproduce
1. Visit https://wordpress.com/settings/traffic/:site for a Jetpack connected site
1. Open the "Site stats" foldable.
1. You should see the following:

![icon-moved](https://cloud.githubusercontent.com/assets/841763/25480019/43ce6ae6-2b47-11e7-9ab1-3f204caa639a.png)

The icon is displayed outside the container.

#### Browser / OS version

macOS / Chrome 60

**Comment by sirreal** [comment]
Removing [these lines](https://github.com/Automattic/wp-calypso/blob/3f174ff4d9d3a3d9fb2b62be3e462a524b9bc389/client/my-sites/site-settings/style.scss#L357-L360) seems to fix the problem.

@tyxla Can you have a look? (see f8109756a14edb5bcb7d40744857fb9fd34b9dac)

**Comment by tyxla** [comment]
Thanks for the ping @sirreal, that's on me 😉

**Comment by tyxla** [comment]
I've addressed it in #13453, should be easy to review. Thanks for the good find :+1:
