### ISSUE TITLE
Domains: i18n for /domains

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#13452]
To better support all users, the /domains page should include locale detection and a locale switcher.

On our homepage we switch locales automatically based on user context, so for example if your environment is set to Hebrew, you'll get redirected to `he.wordpress.com`.

We also have a locale switcher at the bottom of the page, for switching between locales manually.

Previously, we also had a locale tip to suggest relevant locales, but it is not used on the current front page. 

Since we intend to use /domains as a landing page and send users to /domains without passing through the front page, we should have at least the same i18n facilities on /domains as we do on the front page.

**Comment by aidvu** [comment]
Site picker is done in D5564-code.

Will fix the locale redirection for logged out users next, and currencies for locale.

**Comment by aidvu** [comment]
Currency detection done in D5651-code.

**Comment by aidvu** [comment]
This is done for a while now. Closing. :)
