### ISSUE TITLE
Plugins: Plugin name and install label overlap when both are too long.

### ISSUE THREAD

**Issue by lezama** [Automattic/wp-calypso#1346]
![image](https://cloud.githubusercontent.com/assets/104869/11639669/fa82658c-9d0c-11e5-98e3-49fc472998ea.png)

__How to reproduce__

* go to `http://calypso.dev:3000/plugins/gumroad/<a_jetpack_site>`

**Comment by enejb** [comment]
@lezama can you see if this is still an issue for you. I think it should be fie fixed.

**Comment by lezama** [comment]
still an issue, sorry @enejb :disappointed: 

![image](https://cloud.githubusercontent.com/assets/104869/12478414/8e04b070-c013-11e5-835a-b79589daacb3.png)

**Comment by lancewillett** [comment]
This looks fixed now—testing with both EN and ES locales in user settings, and Mac-n-Chrome.

![screen shot 2016-05-09 at 4 00 30 pm](https://cloud.githubusercontent.com/assets/66797/15130679/376b923c-15ff-11e6-9348-6a4e73db0e32.png)
