### ISSUE TITLE
Editor: Selection word count

### ISSUE THREAD

**Issue by pento** [Automattic/wp-calypso#13488]
It'd be very useful to show the word count of a selected piece of text. This is a pretty common feature in every desktop text or document editor.

For example, this is how Pages does it.

![Word count of entire document in Pages](https://cloud.githubusercontent.com/assets/352291/25516696/5dd61838-2c2f-11e7-95b2-1b3ccbf927f9.png)
![Word count of selected text in Pages](https://cloud.githubusercontent.com/assets/352291/25516697/5dd96e02-2c2f-11e7-97df-5e9279ad07ab.png)

**Comment by jeremeylduvall** [comment]
Closed via #13530.
