### ISSUE TITLE
Jetpack: Plugins should not be displayed to non-admins

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#13495]
#### Steps to reproduce
1. Starting from a Jetpack site with 2 users: an admin and an editor.
2. Connect the admin account to a WordPress.com account.
3. Log out of your Jetpack site, and log out of your WordPress.com account.
4. Log in to the Jetpack site with the editor account.
5. Go to the Jetpack menu and click on the link to link that account to a WordPress.com account.
6. After the connection, here is how Calypso will look like:

![screen shot 2017-04-28 at 14 47 53](https://cloud.githubusercontent.com/assets/426388/25529263/ae00bb00-2c21-11e7-9dc4-d8da6854027f.png)

However, since Plugins are not available for non-admins, that menu item should not be displayed at all.

**Comment by jeherve** [comment]
Still an issue.

**Comment by jeherve** [comment]
Nope, it should remain open.

**Comment by ockham** [comment]
Hmm, I can't seem to repro:

![image](https://user-images.githubusercontent.com/96308/36985516-60ae0778-208f-11e8-8753-c0af49d5e5c3.png)

One thing I noticed in your sceenshot @jeherve -- there's a 'Switch Site' option, which seems to indicate that the test user is connected to more than just one site. Could that be relevant?

**Comment by jeherve** [comment]
I can't seem to be able to reproduce anymore! Closing.
