### ISSUE TITLE
WooCommerce: Add (WooCommerce) Store to Sidebar and Store Navigation

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#13514]
#### Context / Source

Adds a Store item to the sidebar for sites which support it and, on navigation, 1) replaces the sidebar with store specific content and 2) adds a top-of-content breadcrumbs style navigation component.  Also adds additional placeholder pages for the new store routes exposed in the sidebar.

See #13466 for design

- [x] Add store-specific sidebar for when in a store route, including placeholder views
- [x] Add secondary header with breadcrumb nav for when in a store route
- [x] Add store menu item for biz plan/jetpack users on traditional calypso sidebar
- [x] Change store menu item button to "Manage" once setup has been completed
- [x] Animate store sidebar in and out to reinforce the "you're digging deeper" UX
- [ ] Add drake-no-store-for-you for no-priv or no-store for store routes

cc @kellychoffman

**Comment by jameskoster** [comment]
@allendav here's how the behaviour of the sidebar/nav should work on mobile;

![mobile-nav](https://cldup.com/UATF-kXMnD-2000x2000.png)

When clicking the 'Store' item in the main nav;

* First time users get funnelled directly into egg dash to set up their store
* Returning/existing users are sent to the store navigation.

Essentially our top bar:

![top-bar](https://cldup.com/6-kI17IZ0b-3000x3000.png)

Should shrink down to this Calypso component on mobile:

![calypso-crumb](https://cldup.com/6K28H4t5tH-3000x3000.png)
