### ISSUE TITLE
Jetpack Connect: detect users trying to connect a connected site, success message

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13529]
Currently when a user tries to connect an already connected site, we redirect them to the My Plan page with no message. This can be confusing for users. 

Instead we should keep them on the connect or 'add site' screen with a notice. It should be a success notice like this:

![image](https://cloud.githubusercontent.com/assets/437258/25580922/6ab03c58-2e52-11e7-9adb-970445c1ee78.png)

cc @johnHackworth @annezazu @tyxla @ryelle

**Comment by tyxla** [comment]
@rickybanister nice catch. It appears this was introduced in #9503 when we moved the redirection logic way above. PR coming up.

**Comment by tyxla** [comment]
#13599 addresses this one.
