### ISSUE TITLE
Sharing: Reblog button disappears if Like button is hidden

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#13525]
Even if we hide *only* Like button under Sharing > Sharing Buttons, the Reblog button disappears from Posts and Pages as well.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com > My Sites
2. Go to Sharing > Sharing Buttons
3.  Under 'Reblog & Like', check `Show reblog button` and *uncheck* `Show like button`. 

![screen shot 2017-05-01 at 3 04 46 pm](https://cloud.githubusercontent.com/assets/10125810/25576860/a5aae1dc-2e7f-11e7-8874-b3f32fe7d493.png)

4. Click Save Changes.
5. Navigate to Settings > Sharing on the WP-Admin Dashboard of the same site and notice that this setting is reflected there as well.

![screen shot 2017-05-01 at 3 09 27 pm](https://cloud.githubusercontent.com/assets/10125810/25576938/369e7212-2e80-11e7-9472-e292ccdb7885.png)

5. Navigate to any Post on the site, and notice that *both* the Like and Reblog buttons are hidden, and that the `post-likes-widget-placeholder` div is not even rendered on the page.

6. Under My Sites > Sharing > Sharing Buttons > check `Show like button`, hit Save Changes, and notice that both the Like and Reblog buttons appear on the Post, and that the `post-likes-widget-placeholder` div now renders.

#### What I expected
Since we offer individual checkboxes for both the Like and the Reblog buttons, unchecking `Show like button` should only hide the Like button.

#### What happened instead
Unchecking `Show like button` hides the Reblog button as well.

#### Follow-up
Need to follow up in 3188177-t

**Comment by jeremeylduvall** [comment]
Thanks for the report Mahangu! There's some additional discussion on this in 7550-wpcom and some previous discussion in #6136. This will require an API fix, not a fix in Calypso. I'm going to close this in favor of the internal Trac ticket.
