### ISSUE TITLE
Mobile: detect mobile app web view and avoid locking app users into calypso

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#13532]
We've had a few issues in the mobile apps where users click "view site" which opens the front-end of their site via web view, and then they click on "edit" from a post or page which takes them into the Calypso editor and effectively locks them into navigating via calypso rather than the apps.

Our mobile apps set their webview user agent string to a custom one, so we could detect these devices and treat them differently. I think the best approach is probably to detect that we are serving a web view inside an app for certain calypso pages and redirect to a deep-link. I don't think we want to modify the "edit" link on the site front-end, as that would be more intrusive than we need. But if someone thinks of a better approach, anything that addresses the problem is fine.

/cc @catehstn

**Comment by kwonye** [comment]
Can we also re-investigate this please? 

https://github.com/Automattic/wp-calypso/issues/3353

I think having the masterbar within a webview inside the app is a horrible experience.

**Comment by rachelmcr** [comment]
I'm reopening this issue as this continues to be a problem for app users. See this recent report: https://github.com/Automattic/wp-calypso/issues/22761

**Comment by elibud** [comment]
@kwonye lets look into adding all the necessary deep links to implement this. Thanks.

**Comment by kylemcph** [comment]
Another instance of this here: 10361027-hc

The "View Site" link takes the user to their other WordPress.com site.
