### ISSUE TITLE
Fullpost: More in Site (imageless) layout problems

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13539]
Using this latest Scalzi post as an example: https://wordpress.com/read/feeds/30997/posts/1442214028#comments

The More on WP section is perfect:

<img width="761" alt="screen shot 2017-05-01 at 3 56 26 pm" src="https://cloud.githubusercontent.com/assets/24388/25597963/ea9f337c-2e86-11e7-8d87-4bab74b4a7ee.png">

But the More in Site section is getting cropped weirdly, and the two sections aren't lining up.

<img width="766" alt="screen shot 2017-05-01 at 3 56 14 pm" src="https://cloud.githubusercontent.com/assets/24388/25597983/022ee604-2e87-11e7-9b74-46bb1785b35b.png">

Whatever changes we recently applied to More on WP need to also be applied to More in Site, @jancavan. (Please and thank you.)

**Comment by jancavan** [comment]
The `has-excerpt` class for the first rec in "More in site" isn't being applied causing this issue, but I think I can it to work without it.

**Comment by fraying** [comment]
@jancavan In just this example or on all Fullposts?

**Comment by jancavan** [comment]
> In just this example or on all Fullposts?

Looks like it's just in this example, not sure why.

**Comment by fraying** [comment]
@jancavan Aha! That's good to know. Thanks.

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/13444
