### ISSUE TITLE
Editor: Publish button border disappears when publishing

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#13558]
#### Steps to reproduce
1. Start at the "Write" page to create a new post: `https://wordpress.com/post/$mysite`
2. Add title/content
3. Click the _PUBLISH_ button

#### What I expected

The button keeps borders and displays the striped animation. This is how "Update" behaves for existing posts.

#### What happened instead

The button borders disappear, it looks smaller than the "calendar" icon button next to it.

#### Browser / OS version

Chrome 60 / macOS

#### Screenshot / Video

![publish-style](https://cloud.githubusercontent.com/assets/841763/25616216/b546f8c6-2f3b-11e7-856f-68ce8d6dd691.gif)

**Comment by sirreal** [comment]
Assigns jeremeylduvall: #13709

**Comment by jeremeylduvall** [comment]
Should be closed via #13709.

**Comment by sirreal** [comment]
Thanks @jeremeylduvall, looks good!
