### ISSUE TITLE
Free Trials: Domain Only Email (Post trial)

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1355]
If a user uses their domain credit during their trial but decides not to purchase the plan they will be offered the domain individually for a period of two weeks (could change). To increase conversion of those domain purchases and to ensure the users understands what happens if they don't purchase the domain, we will send two additional emails, one on day 16 and one day 27 (assuming a 2 week offer period).

**Comment by drewblaisdell** [comment]
Because a domain will only be unassociated with a plan and active for four days (17-21) we will only need to send one email here.

**Comment by fabianapsimoes** [comment]
Closing this as we won't offer domains in trials (p6qnuF-129-p2).
