### ISSUE TITLE
Social Signup: Handle the case where users block third-party cookies/data

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#13553]
Reported by @aerych:

We need to handle the case where users block third-party cookies/data. We should message to the user that they need to allow these if they want to connect their social account, instead of just silently failing.

**Comment by fabianapsimoes** [comment]
@ranh we would need copy for this as well.

**Comment by kristastevens** [comment]
Standing by @ranh, if you'd an extra set of eyes on the copy.

**Comment by ranh** [comment]
From @aerych's report, when the Chrome option "Block third-party cookies and site data" is enabled, the "Continue with Google" button becomes unresponsive and returns a console error when clicked. 

What about something like this?

> Your privacy settings are blocking us from connecting to your Google account. Please enable "third-party cookies" in your browser or operating system, or log in with an email address instead. 

We should do a bit more testing with different environments / privacy settings. Depending on the scope of this issue, perhaps we can add a support page with more information and instructions for common browsers and OSs.
