### ISSUE TITLE
Social Signup: Import name and avatar from Google when signing up

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#13550]
Reported by @josemarques:

Right now, when a user signs up using a social account, their personal info and avatar aren't pulled from it. That's a nice-to-have that we should look into post-v1. Also, as noted by @drewblaisdell, it might tricky or impossible to update a user's Gravatar.

**Comment by fabianapsimoes** [comment]
We should also try to get the user's name (or at least the user's name, if it's too tricky to update the avatar).

**Comment by scruffian** [comment]
@Tug I believe we can close this now, correct?

**Comment by Tug** [comment]
Correct 👍
