### ISSUE TITLE
Reader: Create thumbnails for youtube playlists

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#13567]
Currently we generate thumbnails for videos from:
1. VideoPress
2. Youtube
3. Vimeo

When a user posts a youtube playlist, we display a 404 video thumbnail.
Example: /read/feeds/58928981/posts/1443286617
![screen shot 2017-05-02 at 1 47 01 pm](https://cloud.githubusercontent.com/assets/4656974/25631272/de90181e-2f3d-11e7-833f-9725a0c84d5d.png)

This issue can be closed when we are generating thumbnails for youtube playlists

Implementation Notes:
- Youtube has an api where you can query for thumbnails. Details here: https://developers.google.com/youtube/v3/docs/playlists/list.  we'd want the 'snippet' part.

cc @fraying

**Comment by designsimply** [comment]
Testing to see if adding a comment and closing an issue automatically removes the `[Status] Stale` label. Please ignore!
