### ISSUE TITLE
Free Trials: Allow domain to be purchased after trial expires

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1357]
If a user used their domain credit during a trial and the trial expires we want to offer the domain for purchase for 14 days** after the trial expires.

14 days is debatable but seems like a good place to start.

Upon trial expiration:

 - Unset the domain as primary
 - Update domains page to show domain as inactive: https://github.com/Automattic/wp-calypso/issues/1282
 - Disable the redirect
 - Display a parked page or overlay when visiting the unpurchased domain.

cc @scruffian @breezyskies

**Comment by drewblaisdell** [comment]
- When users pay for a domain registered during a free trial, we shouldn't renew the domain.
- We should ensure that the domain subscription is connected to the domain transaction in this case.

**Comment by drewblaisdell** [comment]
This also means that we'll need a domain-only state for the trial hub.

**Comment by fabianapsimoes** [comment]
Closing this as we won't offer domains as part of free trials (p6qnuF-129-p2).
