### ISSUE TITLE
Jetpack: Thank You Page: Start with a progress bar

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#13585]
#### Steps to reproduce
1. Buy a plan for a Jetpack site
2. Get the new colorful thank you page
3. Wonder if anything is going on, since the progress bar takes quite a long time to start

#### What I expected

To see the progress bar in action.

#### What happened instead

The progress bar spends a looooong time with no indication that anything is going on, although the spinners down the bottom are spinning. I think we should start the progress bar out with enough "progress" to at least indicate that something is already happening.

#### Screenshot / Video

![screen shot 2017-05-02 at 11 36 34 am](https://cloud.githubusercontent.com/assets/108942/25647198/21cf4872-2f7d-11e7-8110-e083a4ccb522.png)

**Comment by rickybanister** [comment]
cc @oskosk @johnHackworth @sirreal @seear @tyxla

**Comment by oskosk** [comment]
I think this may have been already tackled, as the bar now progresses if one of the plugins fails and the other succeeds which wasn't the case before.

**Comment by rickybanister** [comment]
I think @beaulebens point is more that the progress bar should start out at say 10% or something just to give the indication of something working. Even if it shows blank for a second while the other progress meters are spinning it could be strange. 

Let's confirm one way or the other whether it has or has not been tackled, perhaps the next time you test it you could drop in a video of that part of the screen?

**Comment by oskosk** [comment]
> I think @beaulebens point is more that the progress bar should start out at say 10% or something just to give the indication of something working.

Got it!

> Let's confirm one way or the other whether it has or has not been tackled, perhaps the next time you test it you could drop in a video of that part of the screen?

Ok, I'll do. I remember that when anything failed, there was this concept of setting `progress = 0` (zero). I updated that, so a failure does not set the progress to 0. The progress mapped to what we see in that bar. I updated that.

**Comment by rickybanister** [comment]
Thanks @oskosk

**Comment by tyxla** [comment]
Removing this from the https://github.com/Automattic/wp-calypso/projects/44 project, but PR is coming soon.

**Comment by tyxla** [comment]
Quick PR that handles this: #18470.
