### ISSUE TITLE
Jetpack: Thank You Page: Misleading icons after errors

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#13586]
#### Steps to reproduce
1. Buy a plan for a Jetpack site, where the site does not allow file modifications, or any other thing that would cause the auto-config to fail
2. You should see some errors in the icons at the bottom, when certain processes fail
3. Once "complete", the icons all reset to checkmarks, indicating that things went well, when in fact most of them failed.

#### What I expected

If there are errors, then those icons should remain in an error state to indicate what failed.

#### What happened instead

Everything was converted to checkmarks at the end of the process.

#### Screenshot / Video

![screen shot 2017-05-02 at 1 28 43 pm](https://cloud.githubusercontent.com/assets/108942/25647305/2203a260-2f7e-11e7-804a-e5648f40a04a.png)
![screen shot 2017-05-02 at 1 28 59 pm](https://cloud.githubusercontent.com/assets/108942/25647306/2204094e-2f7e-11e7-8d6e-8f75c1c5cce9.png)

**Comment by lezama** [comment]
cc @ebinnion

**Comment by ebinnion** [comment]
When @enej and I were testing we ran into some interesting situtations where `canUpdateFiles` on the site object flip-flopped between `true` and `false`. When we looked into it, the issue seemed to be that when we get the site object from the site directly, `canUpdateFiles` is correct. But, when Calypso polls from WP.com, it's not correct.

In our case, we were able to fix it with a full sync. Can you try that as a debug step @beaulebens?

**Comment by rickybanister** [comment]
@beaulebens's assessment here makes sense—the expected behavior is simply that we show the alert icons and the banner above.

It makes me wonder if we might want to swap out the 'thank you' message also since it feels inappropriate since things failed. Or perhaps we just dim the thank you card to highlight the banner above it.

**Comment by ebinnion** [comment]
> It makes me wonder if we might want to swap out the 'thank you' message also since it feels inappropriate since things failed

That makes sense to change that "Thank you" language if things fail, but in this case, I think it actually succeeded, likely because Beau might have already had the plugins installed.

**Comment by rickybanister** [comment]
If that's the case then we would not want to show the failure banner or the ! alert icons. If he has the plugins we would want to say 'ooh nice you're already almost set up, starting your backups etc, great, wonderful!'

**Comment by rickybanister** [comment]
This issue will become irrelevant soon when @johnHackworth and company move the thank you page information to the my plan page. Closing for now.
