### ISSUE TITLE
WooCommerce: Persist store setting changes to merchant's host

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#13606]
Persist changes in calypso state for the merchant's stores' settings groups (general, products, tax, shipping, etc) back to the merchant's host
 
#### Context / Source
WooCommerce has many settings that need to be able to be adjusted by merchants using Calypso to manage their store(s). REST API endpoints already exist in WooCommerce 3.0 (and higher) just for this purpose, e.g. GET /wp-json/wc/v2/settings etc etc

See also #13483

**Comment by justinshreve** [comment]
This is complete.
