### ISSUE TITLE
Popover: Initial position incorrectly calculated on narrow displays

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#13602]
Migrated from #12278 

See gif:

![misposition](https://cloud.githubusercontent.com/assets/841763/25668711/c551e31a-3027-11e7-9dd0-13c6368c7a45.gif)

Notice how the Popover position is incorrectly calculated initially, then is gradually fixed as it is recalculated on scroll.

Enter `localStorage.setItem( 'debug', 'calypso:popover' )` in the browser console to see this debug info.

**Comment by sirreal** [comment]
Ping @retrofox as the last person working on this. Any idea what's going on here? At first glance it looks like it may not be able to calculate position correctly before the element is in the DOM.

**Comment by retrofox** [comment]
let me take a look

**Comment by sirreal** [comment]
Possible duplicate of #9007

**Comment by AnnaMag** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/19992
