### ISSUE TITLE
WooCommerce: Extensions: Allow extensions to add links to store nav

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#13619]
Add a means for extensions (e.g. product add-ons) to add items to the store nav/sidebar.

See also #12849 ( Global Add-Ons Settings ) as an example of an extension settings view that would need a home on the nav/sidebar.

See also #13514 for nav/sidebar work for WooCommerce itself

Design TBD

**Comment by kellychoffman** [comment]
> Global Add-Ons Setting an example of an extension settings view that would need a home on the nav/sidebar.

Not necessarily. I think we need to come up with a system for extension navigations. I know we can't truly enforce it, but we come up with a rule, and we should follow it, and suggest extension developers do the same. We don't want to make the same mistakes again and just like we've put a lot of time in redesigning the core navigation structure and we should do the same for extensions.

**Comment by allendav** [comment]
+100 @kellychoffman ! :)
