### ISSUE TITLE
WooCommerce: Settings: Add UX to manage email settings

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#13614]
Adds the UX for displaying and managing email related settings, e.g.

- setting email sender options
- setting email template options
- which emails are automatically sent, which are manually sent, and to whom
- unclear if in scope: editing content for "new order", "cancelled order" and other emails (if included, this would increase the estimate dramatically)
- etc

See also #13483 and #13606 

Design TBD. May be combined with other settings UXes. cc @kellychoffman

**Comment by kellychoffman** [comment]
Design issue: https://github.com/Automattic/wp-calypso/issues/15040
