### ISSUE TITLE
WooCommerce: Add Store Dashboard UX for "Egg" aka "Setup Mode"

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#13612]
See #13466 for design (note that both the "setup mode" design and the "ongoing maintenance mode / after setup" design are in that issue

- header component
- footer component
- products task
- shipping setup task
- payments setup task
- taxes setup task
- customizing task
- documentation links all point to correct pages on https://support.wordpress.com/
- footer buttons set a flag to have Fledgling / Momma views of the Dashboard instead
- task checkboxes reflect state of each task

**Comment by kellychoffman** [comment]
> - [ ] task checkboxes reflect state of each task

The following sections still need to be hooked up: 

- Shipping - ( @DanReyLop @marcinbot )
- Taxes ( unassigned )
- View & Customize - Checked off when user has clicked the Customize button  ( unassigned )
