### ISSUE TITLE
Reader: Manage: Error Text

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13626]
On the current Manage page, if you put in a URL you already follow, the error message is currently: 

"You're already subscribed to that site."

This is confusing because we don't use the word "subscribe" in the UI anywhere. So it should be:

"You're already following that site."

Or, if we can use variables in these messages, it'd be even better to say:

"You're already following _whateverurlyoutyped.com_."

**Comment by jancavan** [comment]
We no longer display an error message. We now just show the Follow button and URL.

![screenshot 2017-05-12 10 02 33](https://cloud.githubusercontent.com/assets/4924246/26008552/255c9876-36fa-11e7-9f30-4f066a95894c.png)
