### ISSUE TITLE
Sites: persist last 5 sites with a published post or page -- across devices and sessions

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#13632]
**Goal:** Instead of saving last 3 sites viewed in one single session — save last 5 posted to by date, across all sessions.

#### Steps to reproduce
1. Starting at URL: any Calypso view
2. Click on Write button.
3. You'll see a list of your sites; top 3 are usually the last 3 you've viewed in My Sites list.

#### What I expected

When logging into the same user account in another browser, or on a different device — and clicking the Write button, the same last 3 sites should be listed. 

Ideally we should save the top 5 sites based on the last 5 sites with a published post or page, by date.

#### What happened instead

The sites list is different, causing me to need to search through the list (seems alphabetical) for the site I just posted to in another session.

#### Browser / OS version

All.

#### Context / Source

#dogfooding and #manual-testing notes from Matt M.

**Comment by lancewillett** [comment]
This might relate only to sites over a certain minimum of sites — say 10 or 30. In testing a user account with 6 sites, the order in the Write menu is always the same, by alphabetical order.

**Comment by lancewillett** [comment]
I did some testing with my `testerlance` user account. Across 3 browsers: Safari, Firefox, Chrome on same machine. Then logged into mobile web with Nexus 6P (Chrome) and iPad Mini (Safari).

The last-published site seemed to be in the top 3 even on new devices. But, it could also be that's one of my last visited on those devices previously.

**Comment by lancewillett** [comment]
Testing more: the site with the last published post *does* seem to move to the top of the list across devices and sessions.

But the site before that one (second-last with a published post) — drops out of the top and is back in the alphabetical list again.

Posted this to lancetestballoons.wordpress.com site in Firefox:
<img width="1392" alt="screen shot 2017-05-03 at 15 50 42" src="https://cloud.githubusercontent.com/assets/66797/25684862/9221055c-3018-11e7-89da-8c224373b7c0.png">

Then reloaded same user account, in Chrome:
![screen shot 2017-05-03 at 15 50 58](https://cloud.githubusercontent.com/assets/66797/25684868/95f81864-3018-11e7-8d98-27b400cb65ed.png)

And in Safari:
![screen shot 2017-05-03 at 15 51 05](https://cloud.githubusercontent.com/assets/66797/25684890/acba9cb6-3018-11e7-9a1e-29b8580ab067.png)

Same account in mobile Chrome (Android phone):
![2017-05-03 22 51 33](https://cloud.githubusercontent.com/assets/66797/25684902/b7ffa74c-3018-11e7-9e65-9bc56e7ce74a.png)

But — the site I posted to just before lancetestballoons.wordpress.com was lancetest14.wordpress.com, and it's now back in the A-Z order of the main list.

**Comment by mtias** [comment]
What about bumping recent sites to 5 initially and seeing if that covers more ground?

**Comment by mtias** [comment]
> This might relate only to sites over a certain minimum of sites — say 10 or 30.

Recent sites are shown only if you have [more than 11 visible sites](https://github.com/Automattic/wp-calypso/blob/master/client/components/site-selector/index.jsx#L440).

> The last-published site seemed to be in the top 3 even on new devices. But, it could also be that's one of my last visited on those devices previously.

Yes, there's no concept of "last published to", but in order to publish you almost always select the site, even if not explicitly.

> But — the site I posted to just before lancetestballoons.wordpress.com was lancetest14.wordpress.com, and it's now back in the A-Z order of the main list.

To be sure, lancetest14 was at the top of the list before you published to lancetestballoons?

**Comment by lancewillett** [comment]
> To be sure, was lancetest14 at the top of the list before you published to lancetestballoons?

Yes, it was in position 3.

**Comment by mtias** [comment]
If it was position 3 then it is expected it would be pushed out by the next selected site `lancetestballoons`.

**Comment by lancewillett** [comment]
OK — gotcha. So, sounds like we could bump to 5.

>  in order to publish you almost always select the site, even if not explicitly.
What are your thoughts on making the "last" based on publishing and not on selecting? If I click Write, post, and don't visit My Sites will it be saved as the last used site?

Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/6217#issuecomment-285116927

To clarify on the technical side — chatting with Matías a bit — these settings do persist via user preferences, stored through the REST API (not localstorage and not specific just the current session).

The retrieval could sometimes fail for a given user when they log in to a new session and their account requires a fresh 2FA token (which could happen sometimes to Automatticians, for example).

Overall the sites list is designed and intended to sync across devices and sesssions, including WordPress mobile apps — they should be using the same API endpoint to sync the settings.

**Comment by mtias** [comment]
> The retrieval could sometimes fail for a given user when they log in to a new session and their account requires a fresh 2FA token (which could happen sometimes to Automatticians, for example).

A good way to check this is navigating to "Me", if you see the 2FA dialog pop up, it means recent sites won't be working properly.

**Comment by designsimply** [comment]
> If you see the 2FA dialog pop up, it means recent sites won't be working properly.

Is this the real bug then? Is it fixable?

**Comment by lancewillett** [comment]
@designsimply Yes, related to https://github.com/Automattic/wp-calypso/issues/202 and https://github.com/Automattic/wp-calypso/issues/5627.

What we need to do next:
- Bump recent sites to 5 (this issue here)
- Move non-sensitive user preferences out from 2FA protection (those linked, plus 600-gh-io maybe) — that way it won't prompt when you load /me and the 2FA token is stale

**Comment by marekhrabe** [comment]
We now persist 5 recent sites in production. Remaining issues that talk about 2FA are well tracked already, as @lancewillett mentioned. If there are still some improvements to be made, feel free to reopen this or create a more specific issue just for that.
