### ISSUE TITLE
Pages: Trash link in ellipsis menu on pages list doesn't span full width

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#13644]
Found while testing out changes in #3906

#### Steps to reproduce

1. Starting at URL: wordpress.com/pages/example.wordpress.com
2. Click the ... (ellipsis) menu next to any page in the list
3. Move your mouse down to "Trash" link

#### What I expected

For the blue highlight to span the width of the available space.

#### What happened instead

The blue link background is only half the available space.

#### Browser / OS version
Tested and saw the error in macOS with Chrome, Safari, and Firefox. Also happens in mobile Chrome on Android (I didn't test iOS mobile Safari).

#### Screenshot / Video

Other links work as expected:
<img width="271" alt="screen shot 2017-05-04 at 07 27 20" src="https://cloud.githubusercontent.com/assets/66797/25708503/87d4cbe6-309b-11e7-84ec-516c4d507ff2.png">

Broken with "Trash" link:
<img width="250" alt="screen shot 2017-05-04 at 07 27 26" src="https://cloud.githubusercontent.com/assets/66797/25708506/89cd0008-309b-11e7-9e80-0f6bf54ce0a2.png">

Mobile view, Chrome on Android:
![2017-05-04 14 32 04](https://cloud.githubusercontent.com/assets/66797/25708625/e3f4d894-309b-11e7-82ba-527db9559e4e.png)

**Comment by alejandronanez** [comment]
I'd like to work on this one guys! Can I?

**Comment by mrtnmgs** [comment]
Hi @lancewillett, I think this has been fixed.

**Comment by lancewillett** [comment]
Yes, this looks fixed now — sharing a screenshot from Safari on macOS for reference.

<img width="372" alt="screen shot 2017-06-28 at 17 42 02" src="https://user-images.githubusercontent.com/66797/27661669-27d0209c-5c29-11e7-8daa-81b0c8e1c6ff.png">
