### ISSUE TITLE
Reader: cannot open old Reader links

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#13645]
Steps to reproduce:

1. Go to https://wordpress.com/read/post/id/5276229/8772 or any Reader link using older url formatting.
1. Try to find the older post or the site in Reader.

<strong>Result:</strong> when I try to open an old format of Reader urls such as https://wordpress.com/read/post/id/5276229/8772 I see a blank screen, no left menu, no option to go to the main site, and no errors in the console. 

![screen shot 2017-05-04 at thu may 4 8 45 32 am](https://cloud.githubusercontent.com/assets/1119271/25709261/10f4dba0-30a6-11e7-8904-e4ecc4a35175.png)
<sup>Seen at https://wordpress.com/read/post/id/5276229/8772 using Safari 10.1 on Mac OS X 10.12.4 unproxied.</sup>

I understand that older content is not available (the post in the example above was published on Jul 10, 2015). Should older formatted URLs redirect to newer content?

#manual-testing (found while re-testing #747)

**Comment by bluefuton** [comment]
Thanks for this @designsimply! There should be redirects in place to catch these, but something's gone awry. Let me take a peek.
