### ISSUE TITLE
Site Settings: Make the stats settings card show that the module is inactive

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#13647]
When the stats module is inactive, we're still shown a sort of success message about stats being collected.

#### Steps to reproduce
1. Deactivate the stats module in your Jetpack site.
2. Get to http://calypso.localhost:3000/settings/traffic.
3. Choose one or your jetpack sites.
4. Confirm that you see the same message as in the screenshot.

#### What I expected

To not be shown an optimistic message about stats being working if the module is inactive

#### What happened instead

The message `Collecting valuable traffic stats and insights` still shows.

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/746152/25709778/9fc3072a-30c0-11e7-89ca-bfa4571ea446.png)

The Jetpack admin page shows this:

![image](https://cloud.githubusercontent.com/assets/746152/25710210/f48bbe4a-30c1-11e7-9751-818e47e745d7.png)

![statsinactive](https://cloud.githubusercontent.com/assets/746152/25710391/8235b8ae-30c2-11e7-82d8-88a017f7922b.gif)

**Comment by oskosk** [comment]
cc @rickybanister for recommendations on how to approach this.

**Comment by rickybanister** [comment]
I think we basically just need to implement 'activation banners' on the calypso side, like we have in the plugin. Your illustrations from the plugin should work straight up in Calypso. 

The only nitpick I might have is to use a compact button so they match the `banner` call to action pattern. 

Does that work?

**Comment by oskosk** [comment]
We have simillar behaviour with SEO, Analytics and a Site Verification Tools under the Traffic Tab. Currently if you have those modules inactive and visit Calypso's Traffic tab, you'll see the cards, but also three 3 notices (old school orange notices) with activation capabilities. 

So the options would be:
1. Don't show the stats card and show activation banner like in Jetpack Admin Page
1. Show the card, show the banner and decide what to show instead of `Collecting valuable traffic stats and insights` ?

What would you suggest ?

**Comment by rickybanister** [comment]
I think we need to go with option 1 and make the 'one-way-activation' experience unified everywhere. 

cc @MichaelArestad

**Comment by oskosk** [comment]
Alright, thanks for the reply !

**Comment by MichaelArestad** [comment]
In p6TEKc-1ca I proposed we do something like this within settings. We could do the same in the dashboard: 

![image](https://cloud.githubusercontent.com/assets/1123119/25909423/5b279492-356a-11e7-9413-5bf8fae5a035.png)

**Comment by rickybanister** [comment]
@MichaelArestad so we would replace the current non-standard banner-like thing with a `banner`?

**Comment by MichaelArestad** [comment]
@rickybanister I think so. At lest for the one way activation. I'm not sure what a good replacement for the "collecting stats" bit is yet. @jeffgolenski and I still have to work on something like that for the warm welcome. I think it could definitely be useful here as well.

**Comment by tyxla** [comment]
I've suggested a solution for this in #14108. It'll probably some design attention, @rickybanister @MichaelArestad, thanks.

**Comment by oskosk** [comment]
@rickybanister @MichaelArestad if the stats module is deactivated, apart from the suggestions being made here, what should happen with the Stats page and Stats Sidebar link in Calypso?

This is how it looks when stats is deactivated. The spinners keep rolling as if something were broken.

![stats](https://cloud.githubusercontent.com/assets/746152/26151297/8f5c884e-3ad8-11e7-8569-c039c99a7a4c.gif)

**Comment by MichaelArestad** [comment]
@oskosk good catch. We need to probably replace it with something that encourages activating stats. Let's open a separate PR for that.

**Comment by tyxla** [comment]
I've opened a separate issue so we don't lose track of this one accidentally: #14253.
