### ISSUE TITLE
Reader: Hulu embeds are not working in Reader

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#13649]
Steps to reproduce:

1. Start a new post at https://wordpress.com/post
1. Embed a Hulu video using the instructions at https://en.support.wordpress.com/videos/hulu/
1. Publish the post.
1. View the post in Reader.

<strong>Result:</strong> Hulu video embeds aren't working in Reader.

![screen shot 2017-05-04 at thu may 4 9 22 33 am](https://cloud.githubusercontent.com/assets/1119271/25711078/4c85bd42-30ab-11e7-8003-9f8730eef9e0.png)
<sup>Seen at https://design5279.wordpress.com/2017/05/05/hulu-embed-test/ and https://wordpress.com/read/feeds/42873943/posts/1445972903 using Chrome 58.0.3029.96 on Mac OS X 10.12.4.</sup>

#manual-testing (found while re-testing #747)

**Comment by cometgrrl** [comment]
Closing, since it seems Hulu doesn't allow embeds anymore.

> Hulu no longer allows embedding content.

<img width="654" alt="SCR-20230530-h2y" src="https://github.com/Automattic/wp-calypso/assets/86427589/7ffa141f-00ce-4626-888c-db8d6dc4e0b2">
