### ISSUE TITLE
WooCommerce: Add/Edit Product: Category Selection

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#13662]
Adds a product category selection box to the add/edit product form that allows the user to select multiple categories for their product.

The input should use a `TokenField` component with suggestions so a user can easily select from existing categories, or add their own.

See #11646 for design.

**Comment by coderkevin** [comment]
This is complete for adding existing categories, but work still needs to be done to add new categories.

**Comment by coderkevin** [comment]
Completed in #15483
