### ISSUE TITLE
See error for multisite when on single site installation

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#13663]
This is the error I see:

<img width="584" alt="screen shot 2017-05-04 at 12 03 53 pm" src="https://cloud.githubusercontent.com/assets/1883296/25713510/ef7ee50c-30c2-11e7-8f53-2b3fc39ae820.png">

#### Steps to reproduce
1. Start with a clean WP installation, install Jetpack
2. Install akismet but don't activate (if it isn't already)
2. Visit the comments section and click the akismet message at the top of the page
3. Follow the prompts and get a personal plan
4. See the error above

I've reused this domain in the past which had a plan (which may be a factor). The plan was cancelled and disconnected before creating a fresh site.

#### What I expected

To not get an error that doesn't apply

#### What happened instead

I got an error that doesn't apply

#### Browser / OS version

OSX / Chrome

**Comment by withinboredom** [comment]
cc: @rickybanister

**Comment by rickybanister** [comment]
@ebinnion I know you're passing off this work, but do you have any thoughts on whether this domain was associated in the past with a different site could cause this problem? I have very little insight into the problem. 

cc @johnHackworth @oskosk @tyxla @sirreal as I believe you all are picking this up.

**Comment by ebinnion** [comment]
Off of the top of my head, I couldn't say. I think we could fix this issue by not doing a pre-flight check and just trying to install/update/activate the plugins. My guess is that there's some sort of mismatch between the shadow site and remote Jetpack site options.

**Comment by sirreal** [comment]
I believe this is a duplicate of #11759.

**Comment by withinboredom** [comment]
Maybe, except that was on a multisite, I saw this on a not multi-site.

**Comment by sirreal** [comment]
> Maybe, except that was on a multisite, I saw this on a not multi-site.

@withinboredom Sorry, I missed that detail which is _in the title of the issue_. 🤦‍♂️

**Comment by sirreal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [See error for multisite when on single site installation #13663](https://trello.com/c/2tYqWoHp/70-see-error-for-multisite-when-on-single-site-installation-13663)

**Comment by tyxla** [comment]
I believe this can be closed because we're no longer using this interface for the regular flows: cc @Automattic/jetpack-voyager for confirmation

**Comment by rcanepa** [comment]
> I believe this can be closed because we're no longer using this interface for the regular flows: cc @Automattic/jetpack-voyager for confirmation

You're right @tyxla. That screen is no longer used and I haven't seen an error like that in the current interface.

**Comment by tyxla** [comment]
Thanks for confirming @rcanepa! Closing then.
