### ISSUE TITLE
WooCommerce: Add/Edit Product: Tax

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#13668]
Adds minimal tax settings to the add/edit product form. There should be a drop-down for selecting a tax class (actual rules will be edited in tax settings).

If they pick a tax class, an "applies to shipping only" checkbox should appear, unchecked by default. 

See #11646 for design.

**Comment by kriskarkoski** [comment]
@justinshreve Is this Milestone and its issues still needed? https://github.com/Automattic/wp-calypso/milestone/168

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
