### ISSUE TITLE
WooCommerce: Add/Edit Product: Shipping Settings

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#13665]
Adds a new card to the add/edit product form for managing a product's shipping settings. The card should only be displayed for non-variable products since variations contain their own settings.

The card should include an option for how shipping will occur , an input for dimensions, and an input for weight.

See #11646 for design.

**Comment by justinshreve** [comment]
@jameskoster @kellychoffman 

Is the dropdown still needed here?

<img width="488" alt="screen shot 2017-05-16 at 12 37 50 pm" src="https://cloud.githubusercontent.com/assets/689165/26124777/83482a8a-3a34-11e7-8358-d1bd511c64ac.png">

I assume that this drop-down was intended as a toggle for shipping physical items vs digital goods which we decided not to worry about for v1. Other than physical vs digital, there is no other way to mark a product for shipping vs pickup at the product level in the API.

**Comment by jameskoster** [comment]
> I assume that this drop-down was intended as a toggle for shipping physical items vs digital goods 

Correct. We can remove for now.

**Comment by justinshreve** [comment]
This has been handled in https://github.com/Automattic/wp-calypso/pull/14186
