### ISSUE TITLE
Free Trials: Ensure sites only can go through one trial of each plan

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#1369]
A site can only have one free trial of each of our plans. For example, a user can activate a Premium trial for a site, and then activate a Business trial for that same site or another Premium trial for another site. Users cannot activate another Premium trial for a site that already had one.

**Comment by scruffian** [comment]
We can do this on the server. Here is a patch: `D810-code`.

To test you need two sites, one which has started a trial before, and one which hasn't.

**Comment by scruffian** [comment]
This has been committed.
