### ISSUE TITLE
Spinner: style conflict with notifications-panel

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#13707]
`.spinner` styles are being imported from `notifications-panel` creating styles conflicts and breaking display of other spinners:

![spinner](https://cloud.githubusercontent.com/assets/841763/25742769/4be0127a-3191-11e7-9bd5-c4bc4a1e3115.gif)

**Comment by sirreal** [comment]
ping @dmsnell

**Comment by tyxla** [comment]
This will also occur in many other places where use our `<Spinner />` component.

**Comment by hoverduck** [comment]
You can also see the breakage easily on the devdocs pages (picked up by our visdiff tests):

![wp-calypso-spinner-broken](https://cloud.githubusercontent.com/assets/7233112/25749778/a8645e34-317d-11e7-8fba-e8995c4fa044.gif)

Shown here in OSX Chrome
