### ISSUE TITLE
Plans: Clarify discount message (discount v. difference)

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#13721]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans
2. Select a test site with a Premium plan.
3. Click on the (i) tooltip next to "per month, billed yearly" on the Business plan. The tooltip says: "Discount for first year"
4. Click on the Upgrade button. The checkout page includes the message: "You're saving £83! Your recent plan purchase is deducted from the price (£250)."

#### User expectations

In support, users frequently tell us that they expect a discount, on top of what they already paid for their current plan. The term "discount" or "saving" implies a reduced price, rather than paying the difference in the plan prices.

#### Suggested change

The term "difference" could be used to clarify the price being offered.

#### Screenshot / Video

![premiumtopersonal](https://cloud.githubusercontent.com/assets/8658164/25756392/88f335ac-31be-11e7-9514-1245a06839d0.png)

<img width="1280" alt="screen shot 2017-05-05 at 6 09 43 pm" src="https://cloud.githubusercontent.com/assets/8658164/25756451/b1ecc784-31be-11e7-85af-60cb50a100dd.png">

#### Context / Source

Recent example: 335537-hc
HEs hear this feedback about twice per week, per HE.

h/t to all of team Jupiter for helping compose this issue!

**Comment by gwwar** [comment]
For additional context see p5uIfZ-6Ti-p2

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

I checked the behavior of he plan annual discount popover:

![Screen Shot 2021-01-29 at 15 34 50](https://user-images.githubusercontent.com/6549265/106338299-4c2b3700-6248-11eb-9831-8a44f451f1e8.png)
![Screen Shot 2021-01-29 at 15 35 14](https://user-images.githubusercontent.com/6549265/106338293-4afa0a00-6248-11eb-81da-13d5fdb20fbf.png)

It appears changes were made from the initial post and the resulting message adds clarity.

I am proposing to close this issue with an appropriate label denoting reason for closure.
