### ISSUE TITLE
Reader: new follows are placed in Redux state, even if the feed did not exist

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#13726]
While working on #13715, I noticed that an attempted follow will end up in `state.reader.follows.items` as `is_following` even if the API responded that it was an invalid feed.

In this example, awebsiteaboutgoats.com (sadly) does not exist:

<img width="299" alt="screen shot 2017-05-05 at 19 57 53" src="https://cloud.githubusercontent.com/assets/17325/25758258/1812f786-31ce-11e7-8193-30e2ef52e0f8.png">

**Comment by blowery** [comment]
hmmm... the data-layer should have unfollowed it when the response said it didn't exist...

see https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/read/following/mine/new/index.js#L35

sounds like we're missing something.

**Comment by blowery** [comment]
Does raise the issue though, if this is a _new_ feed and it errors, we probably want to drop it from state entirely, not just mark it as is_following:false...

Maybe we need a new property on the follow items, `error` or something? And when that property is true, we stop showing the follow button, or elide the item from the list?

**Comment by bluefuton** [comment]
Fixed in #13839.
