### ISSUE TITLE
WooCommerce: Site switching breaks url structure

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#13730]
To test: 
1. Go to `http://calypso.localhost:3000/store/products/SITE-URL.wordpress.com/add`
2. Via the site picker, switch to a new site
3. See that the url is now`http://calypso.localhost:3000/store/products/add/SITE-URL`

**Comment by allendav** [comment]
Resolved with https://github.com/Automattic/wp-calypso/pull/14870
