### ISSUE TITLE
Google Sign up not working in Safari private window

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#13747]
Google Sign-In client does not work in Safari private mode.

### How to reproduce
- Open a private tab in Safari.
- Visit https://calypso.live/start/social?branch=try/google-platform-js and choose to sign up using a Google account.
- A pop-up for authentication will open. Confirm all the steps there.
- Once the pop-up closes, notice that instead of being redirected to signup's processing screen, you'll be stuck on the user step.

You might see the error `Unhandled promise rejection – {error: "popup_closed_by_user"}` in the console.

In non-private Safari and in other browsers, the issue isn't reproducible.

### Investigation
After further investigation, it seems this is probably a bug in Safari sandboxed iframe not supporting `"allow-same-origin"`.

From this debug screenshot https://cloudup.com/cwLvDPd6urp we can see that the `source` property on the `MessageEvent` is `null` and it should not be.

We should sync with Google which should update their script to use `event.origin` instead in the case where `event.source` is `null`.

/cc @p3ob7o @fabianapsimoes

**Comment by fabianapsimoes** [comment]
@Tug Are we positive this only happens in private Safari?

@p3ob7o could you connect us with someone in Google to update this? Low priority though, if it's restricted to private Safari.

**Comment by Tug** [comment]
@fabianapsimoes Yep positive

**Comment by fabianapsimoes** [comment]
More details in tr-1504 in Amber's Trello board.

**Comment by p3ob7o** [comment]
Given the much more narrow scope, I don't think that this warrants trying to fast track it through cintacts that are not directly involved with that API.

Probably better to report the bug on the Google developer site and see if it's a known issue.

**Comment by Tug** [comment]
I haven't found any public bug tracker for this API. Would still be useful to have a contact to send an email to.

**Comment by Tug** [comment]
I may have found it and opened an issue https://github.com/google/google-api-javascript-client/issues/297

**Comment by danhauk** [comment]
I got a different console error and the page crashed when trying to test in a Safari private window. Video: https://cloudup.com/cGuku4FMKUa

**Comment by Tug** [comment]
Fixed in #19788
