### ISSUE TITLE
Inconsistent Time Picking Format

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#13769]
#### Steps to reproduce
(I'm not sure what settings determine those pickers. Experienced by my wpcom user, on site https://theplate.blog/)

1. New post
2. Try those two ways of scheduling

#### What I expected

They should be same (24hr for me)

#### What happened instead

One is AM/PM, second 24hr

#### Screenshot / Video

![am-pm-24-what?](https://cloud.githubusercontent.com/assets/156676/25820464/4fe635dc-33ff-11e7-9ceb-75a090d42859.gif)

#### Context / Source

#dogfooding

**Comment by lancewillett** [comment]
I ran into this today — with an internal a8c P2 site, set to 0 UTC time zone.

When I go to schedule a post, I see two immediate problems:

- The time picker should be in UTC 0 and not my local time zone.
- The time picker should use the same time format as the blog setting (so if 24 hour, don't show AM/PM in the text.

<img width="384" alt="screen shot 2017-07-25 at 13 53 45" src="https://user-images.githubusercontent.com/66797/28593557-871279f6-7141-11e7-91c8-ea5275baa4be.png">
 
<img width="328" alt="screen shot 2017-07-25 at 13 39 54" src="https://user-images.githubusercontent.com/66797/28593572-94579ab0-7141-11e7-803a-9b37f61f8d93.png">

**Comment by lancewillett** [comment]
@catehstn Also provided a bit of anecdotal evidence to suggest the AM/PM interface isn't a great affordance to tell which is selected.

Could we change the UI a bit to use some other "on/off" visual setting instead of the darker border? Maybe a shaded background or something else with an icon?

**Comment by rachelmcr** [comment]
We now only have a single date picker in the editor. I tested and confirmed that it uses either AM/PM or 24HR time depending on the site's time format setting, so the original issues reported here no longer apply.

**Comment by lancewillett** [comment]
Thanks for the follow-up, Rachel. 👍
