### ISSUE TITLE
Jetpack Connection: correct wording on "return to site" link

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#13777]
#### Steps to reproduce
1. Starting from a brand new Jetpack site.
2. Hit the Connect button in the Jetpack dashboard to start the connection process.
3. Approve the connection on WordPress.com.
4. You'll get a link to "Return to your site", but that link actually redirects to the Plans page on WordPress.com.

It should redirect to wp-admin.

Reported here:
https://wordpress.org/support/topic/jetpack-not-connecting-despite-wordpress-com-dashboard-saying-it-has-2/

**Comment by beaulebens** [comment]
This could use some confirmation; I'm pretty sure this is not the case any more.

**Comment by jeherve** [comment]
It seems it's been fixed. Closing.
