### ISSUE TITLE
Framework: add user friendly error message for unproxied users when trying to use new login endpoints

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#13775]
Steps to reproduce:

1. Start up a local Calypso instance ([ref](https://github.com/Automattic/wp-calypso#getting-started)).
1. Go to http://calypso.localhost:3000/ while unproxied.
1. Try to log in.

<strong>Result:</strong> 

On screen error:
> Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

Console error:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://wordpress.com/wp-login.php?action=login-endpoint. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)

![screen shot 2017-05-02 at tue may 2 1 19 00 pm](https://cloud.githubusercontent.com/assets/1119271/25823168/76a28876-33f8-11e7-97b4-e490773ad3b5.png)
<sup>Seen at http://calypso.localhost:3000/login?redirect_to=http%3A%2F%2Fcalypso.localhost%3A3000%2Fdevdocs%2Fwelcome using Firefox 53.0 on Mac OS X 10.12.4 unproxied.</sup>

Request/response headers for the failed request:

![screen shot 2017-05-02 at tue may 2 1 26 17 pm](https://cloud.githubusercontent.com/assets/1119271/25823214/99df265a-33f8-11e7-80ed-9892ed2bd0ff.png)

Maybe the login was enabled on dev before it was ready?

Reported at p1493752748428662-slack-calypso and p1494269949230922-slack-calypso and p1494272244865908-slack-calypso.

From @gziolo in Slack:
> @drewblaisdell or @jblz can you add user friendly error message for unproxied users when trying to use new login endpoints? :)

**Comment by gwwar** [comment]
If login will only work while proxied in local dev, I think it fine to add a warning to https://github.com/Automattic/wp-calypso/blob/master/docs/install.md so folks won't get tripped up on this step
