### ISSUE TITLE
Free Trials: Make it possible to cancel an active free trial

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1380]
- If the user has a domain, we should give them the option to cancel the plan but keep the domain.
- Otherwise, the user should be able to simply cancel the plan.

**Comment by fabianapsimoes** [comment]
Related to #1151, since this option would live in the trial hub.

cc @mikeshelton1503

**Comment by drewblaisdell** [comment]
Pinging @mikeshelton1503 for design guidance here.

**Comment by mikeshelton1503** [comment]
Sorry for the delay here. I've been AFK. Since we're not offering domains as part of the trials I don't think we need this option for v1. We want to keep the UI as simple as possible so I want to be sure any features we add are truly needed. Sure there will cases where users just want to remove the trial before it ends but AFAIK those cases would all be edge cases with the exception of domains.

cc @breezyskies

**Comment by breezyskies** [comment]
> We want to keep the UI as simple as possible so I want to be sure any features we add are truly needed.  

Agreed, and I would consider this low priority (not a blocker for launch). 

The one scenario I could see making this a viable feature for v2 is a user who starts a trial, decides they don't want it, but still wants to purchase a domain separately.

**Comment by fabianapsimoes** [comment]
@mikeshelton1503 back in Atlantic City, we talked about needing this feature because of the 3-day extension -- since users could argue they've already made up their minds, and do not need three more days. I'm fine with postponing this to a later iteration, just making sure this isn't a concern anymore.

**Comment by mikeshelton1503** [comment]
@fabianapsimoes Right yes we should add it for the extension period. Sorry I was thinking about the 0-13 day period.

Here's a proposal for adding the remove option during the 3 day extension period: 
![image](https://cloud.githubusercontent.com/assets/12596797/12175826/50a5f504-b532-11e5-8220-4abec760dd84.png)

We will need some form of confirmation if they click "Remove now." Not sure what that should look like yet. A modal would work but modals aren't a pattern we use a lot in Calypso.

cc @breezyskies for design review.

**Comment by breezyskies** [comment]
> We will need some form of confirmation if they click "Remove now." Not sure what that should look like yet. A modal would work but modals aren't a pattern we use a lot in Calypso.

I think a modal is okay for confirmations that don't need a lot of copy. For an existing example, try to use "delete site" in settings on a site that has active purchases.

**Comment by drewblaisdell** [comment]
When we implement this, we should also add the link to cancel a plan in the [day-14 email](https://cloud.githubusercontent.com/assets/12596797/11871267/6d552338-a49c-11e5-8328-eb30d04a9845.png).

**Comment by mikeshelton1503** [comment]
I should have clarified the font-sizes to be used:

![image](https://cloud.githubusercontent.com/assets/12596797/12265287/42491b9a-b90a-11e5-8113-33bee901aecf.png)

**Comment by mikeshelton1503** [comment]
When a user clicks "Remove now." a modal should display:

![image](https://cloud.githubusercontent.com/assets/12596797/12265683/7b6c78e8-b90c-11e5-949e-aeb27b954b6d.png)

Modal Copy:
> Remove Free Trial
> Are you sure you want to end your WordPress.com Business free trial and remove it from myawesomesite.wordpress.com? You will lose any custom changes you have made.

If a user then clicks "Remove Now" the trial should be completely removed and the page should revert back to the standard /plans page and display a dismissible success notice with the following copy:

> Your WordPress.com Business free trial has been removed. Thanks for giving it a try!

**Comment by drewblaisdell** [comment]
I had some concerns in #1402 about the use of a modal (comment [here](https://github.com/Automattic/wp-calypso/issues/1402#issuecomment-171101776)) for this. I'm just noting that here to make sure that we're consistent between these implementations of subscription removal (if we decide to change anything).
