### ISSUE TITLE
UrlPreview: Fails with Jetpack site installed in a subdirectory

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#13803]
#### Steps to reproduce
1. Select one of your Jetpack sites that's installed in a subdirectory.
2. Click the Site Icon in the current site box in the sidebar to preview the site.

![](https://cldup.com/RhL6qQXCG1.png)

3. Wait for the WebPreview to load.

#### What I expected
To see a working preview of the site.

#### What happened instead
It loads a 404 page in the preview frame.

#### Context / Source
I found this while testing #13176.

#manual-testing

**Comment by sirreal** [comment]
I'm not sure whether this is related, but it seems to me that many Jetpack sites which were previously `is_previewable: true` are now `is_previewable: false`. I also noticed while looking at #13176 that sites which previously opened in preview are not (also ocurring in master).

**Comment by tyxla** [comment]
@sirreal I've provided some clarification about that here: https://github.com/Automattic/wp-calypso/pull/13805#issuecomment-300408546 - it does not seem to be related.
