### ISSUE TITLE
Make site currency editable

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#13810]
As a user I would like to edit the Currency of my site

Acceptance Criteria:

- [x] I should be able to edit the sites currency

**Comment by belcherj** [comment]
@jameskoster When I click the currency is it a drop down?  When I select a new currency from that drop down does it auto save to API?  The rest of this page has "save" action buttons

**Comment by jameskoster** [comment]
Dropdown with search, although I don't think such a component exists in Calypso currently.

It should also include the currency name, IE 'United States Dollar ($)' rather than just the symbol.

No auto-save.
