### ISSUE TITLE
Free Trials: Update the ToS for free trials

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1382]
Given the current expiration flow (#1377), @wensco raised the following concern:

> [...] it seems this is do-able from a compliance standpoint but we would likely have to create a separate TOS to make it clear that we are registering the domain on the user's behalf but all control and ownership of the domain is retained by us

cc @wensco @pesieminski

**Comment by fabianapsimoes** [comment]
We won't be including domains to free trials (p6qnuF-129-p2), so closing this issue.
