### ISSUE TITLE
Reader Following Manage: add train tracks stats for search + recs

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#13830]
we have railcars for both. we need to hook them up to render events, follow, and clicks.

TODO: fill in with details

**Comment by fraying** [comment]
Things we wanna track:

- Follow from Manage: URL Input
- Follow from Manage: Recommended Site
- Follow from Manage: Search Result

What else?

**Comment by gibrown** [comment]
I think that is all of them. render and interact events for all of them

**Comment by bluefuton** [comment]
Fixed in #14338.
