### ISSUE TITLE
Allow advanced Flat Rate configuration

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#13845]
For the MVP, we'll only allow a merchant to configure a `Flat Rate` for a Shipping Zone with a plain number. For example, `10.00`, which will be added to the cost of the items of the shipment.

WooCommerce currently allows a much more advanced configuration than that. From the configuration tooltip:
> Enter a cost (excl. tax) or sum, e.g. `10.00 * [qty]`. Use `[qty]` for the number of items, `[cost]` for the total cost of items, and `[fee percent="10" min_fee="20" max_fee=""]` for percentage based fees.

Making the merchant write an equation with pseudo-code is clearly **not** the direction we want to follow in Calypso.

We need to study which variations of the advanced configuration are the most used (my gut tells me that `number * [qty]` is pretty common), and design custom UI for those cases. That UI will eventually produce the pseudo-code equation that will be sent to the server.

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
