### ISSUE TITLE
Site indicator in drafts dropdown

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#13844]
#### Steps to reproduce
Got to any jetpack site that has updated available and has posts set as draft.

#### What I expected
To not see the site indicator.

#### What happened instead
Was the site indicator in the dropwon.
![screen shot 2017-05-09 at 16 06 26](https://cloud.githubusercontent.com/assets/115071/25876369/934992ba-34d1-11e7-97de-7bd054e65946.png)

#### Browser / OS version
Latest Crome/ Mac

cc: @mtias

**Comment by mtias** [comment]
I saw this but thought it was alright :)

**Comment by designsimply** [comment]
@enej, why did you expect to not see the upgrade indicator in the drafts site list? Per @mtias's comment, do you think it's okay for it to stay?

**Comment by rachelmcr** [comment]
#bug-scrub

Given the points raised so far, and that there's been no further discussion over the past 6 months, I'm going to go ahead and close this issue. Please reopen if you feel we should still address this. :)
