### ISSUE TITLE
Media: Add a note about maximum upload file size in Media screen.

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#13847]
Can we please add a note about maximum upload file size in the Calypso Media screen?

This is similar to how we have "Maximum upload file size: 1 GB." note in the Upload New Media screen of WP-Admin.

Thank you!

367771-hc

**Comment by lancewillett** [comment]
@chaitanyamsv If you have time, could you please include screenshots? It helps to identify and validate the issue (and provide history later). Thanks!

**Comment by chaitanyamsv** [comment]
Sure, @lancewillett. Here is the note in WP-Admin. This note is not present in Calypso at the moment.

![file size note in wp-admin](https://cloud.githubusercontent.com/assets/1519466/26464869/5a5648e0-41dd-11e7-961f-9d31f982fa4e.png)

**Comment by designsimply** [comment]
Here is a sceenshot of the same media library screen in Calypso for reference:

![screen shot 2018-02-26 at mon feb 26 11 01 40 am](https://user-images.githubusercontent.com/1119271/36686680-70dfe694-1ae4-11e8-86c2-9e7000e7566a.png)
<sup>Seen at https://wordpress.com/media/madefortesting.wordpress.com using Firefox 58.0.2 on macOS 10.13.3.</sup>

It makes sense to include the recommended 1GB maximum in context of video files especially.
