### ISSUE TITLE
Checkout: Missing i18n for domain checkout

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#13854]
#### Steps to reproduce
1. Change your UI language to Japanese
2. Go to https://wordpress.com/domains/manage/ and add a new custom domain
3. Proceed to the checkout page

#### What happened instead

Some text is missing i18n.

![_ _where_is_naoko__ _wordpress_com](https://cloud.githubusercontent.com/assets/34067/25887587/aff4e4ce-359d-11e7-9bd9-c5ad04d3fbd1.png)

#### Links to sources
- ["Learn more about..."](https://github.com/Automattic/wp-calypso/blob/c67ee054e5d46ee2b79c1d94c3248f068c6a9130/client/my-sites/upgrades/checkout/privacy-protection.jsx#L82)
- ["Domain Contact Information"](https://github.com/Automattic/wp-calypso/blob/7d2daa45afab5c993634b607a5d51e820e62adb3/client/my-sites/upgrades/checkout/domain-details-form.jsx#L438) ([GlotPress entry](https://translate.wordpress.com/projects/wpcom/ja/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=77688&filters%5Btranslation_id%5D=2162379) for this exists but it's not reflected to the site)
- ["Registering this domain..."](https://github.com/Automattic/wp-calypso/blob/7d2daa45afab5c993634b607a5d51e820e62adb3/client/my-sites/upgrades/checkout/domain-details-form.jsx#L236)

**Comment by rachelmcr** [comment]
I confirmed that "Domain Contact Information" and "Registering this domain..." have i18n now, but "Learn more about Privacy Protection" is still an issue.

**Comment by klimeryk** [comment]
Looking at the code, it should be translatable 🤔 
https://github.com/Automattic/wp-calypso/blob/8db70cf3a584cd679ed884f25337da3b2140a397/client/my-sites/checkout/checkout/privacy-protection.jsx#L86

**Comment by rachelmcr** [comment]
Well, that's weird. The string was showing up in English on the checkout page for me repeatedly until I refreshed the screen while on the checkout page, and now it's showing up as translated in each language I check. Must have been a local issue for me — I'll closed this as resolved. :)
