### ISSUE TITLE
Settings > Writing > Posts per page location

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13868]
As of #13718 the posts per page setting has been added to General settings. 

I think it would be a better fit in /writing. We have a 'composing' card block that already contains defaults for other writing and post-related items.

Could we move posts per page to there:

![image](https://cloud.githubusercontent.com/assets/437258/25905076/0539b434-356f-11e7-87c3-08135ef0a832.png)

cc @tyxla @jonathansadowski @lancewillett

**Comment by lancewillett** [comment]
Yes, I agree on the location — @tyxla could you handle? We're working on some other changes.

**Comment by rickybanister** [comment]
@lancewillett it'd be great if you or @jonathansadowski could move it—I would have offered the same advice before the original PR was merged if I'd gotten to it early enough. @tyxla also has a lot going on with the 5 other settings milestones. It should be a pretty small PR right?

**Comment by lancewillett** [comment]
It can wait, then — we're super tight on time and scope, and heading into travel for a team meetup. Can loop back if no one else gets to it.

**Comment by tyxla** [comment]
It's not a big deal, let me draft a PR for it.

**Comment by tyxla** [comment]
This one is being addressed in #13916.

It's worth to mention I found a nasty bug with settings being carried over when we switch sites, but that's taken care of in #13915.
