### ISSUE TITLE
Layout: while viewing sidebar the masterbar allows you to erroneously scroll the main content column

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#1387]
This is a bit tricky to describe, but to reproduce you can

* make your browser narrower than 480px
* hover the masterbar with your mouse
* scroll
* you will see the masterbar scroll away and the main content column scroll up

Note: this also happens if your browser is short enough to allow scrolling in the sidebar—when you hit the bottom of the sidebar you will begin scrolling the main column and the masterbar scrolls away.

<img width="393" alt="screen shot 2015-12-08 at 12 34 07 pm" src="https://cloud.githubusercontent.com/assets/437258/11664810/ce414ac4-9db1-11e5-891b-92eb75c8e58b.png">

Expected:
The masterbar should stay fixed

**Comment by folletto** [comment]
This might be fixed automatically once the masterbar refactoring lands, see #631.

**Comment by gwwar** [comment]
@rickybanister dup of https://github.com/Automattic/wp-calypso/issues/1283?
