### ISSUE TITLE
Purchases: deactivate site alerts

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#13870]
The site card in /purchases currently shows the site indicator icon—in that context it doesn't seem to make sense to take someone away from their purchases to do an update (I think)

![image](https://cloud.githubusercontent.com/assets/437258/25905803/ea88eae0-3570-11e7-9eca-b707162421b3.png)

Do others agree?

cc @beaulebens @johnHackworth @mtias

**Comment by beaulebens** [comment]
Definitely agree. I think we should limit those to the site selector, and keep this space purely for managing things related to purchases/transactions.

**Comment by ryelle** [comment]
This was a quick fix, so I've just made the PR: #13875
