### ISSUE TITLE
Reader: Following Manage site recommendations dismiss behavior

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#13897]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage.
2. On Recommended Sites, dismiss the **_first_** rec.
3. Second rec slides to the left and a new rec comes in to replace the second one.

#### What I expected
For the first rec to be replaced in the same position.

#### What happened instead
Second rec slides to the left and a new rec comes in to replace the second one.

**Comment by designsimply** [comment]
Aside: what does SoM stand for?

**Comment by jancavan** [comment]
@designsimply Search on Manage 😄

**Comment by designsimply** [comment]
<blockquote>@designsimply Search on Manage 😄</blockquote>

Bahaha, I should've guessed that, thanks!

**Comment by fraying** [comment]
Can I just say I like this behavior? It's weird because it's not what we do for recs anywhere else, but I like it. I'd like it even more if we animated the right result literally sliding over to the left position.

**Comment by bluefuton** [comment]
This behaviour hasn’t attracted any negative feedback, so closing this one for now.
