### ISSUE TITLE
Editor: location field steals focus

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#1389]
If you search a location, but do not select a result the location field seems to continually search. If you try to focus another field it seems to count that as an onChange event and refocus the location field, scrolling you back to that place in the sidebar. It's very confusing if you were just trying to click on another field to say add a category.

cc @nylen

**Comment by nylen** [comment]
Definitely something weird going on here.  Note how the focus jumps from "Slug" back to "Location" after I type a letter, but the issue goes away after I clear the text entered into "Location":

![location-steals-focus](https://cloud.githubusercontent.com/assets/227022/11676067/835a8104-9df4-11e5-8a71-edb56b576596.gif)

**Comment by nylen** [comment]
Here's the problematic line of code in the `<Search>` component: [`this.focus();`](https://github.com/Automattic/wp-calypso/blob/96ef7d9030398a7a7f6ebcc122467c2021452538/client/components/search/index.jsx#L96)
