### ISSUE TITLE
Comments: List View

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#13892]
This is an summary parent issue. We will create much smaller technical tasks out of the requirements this issue highlights. Also see: p3fqKv-4v6-p2

Users would like to be able to moderate incoming comments. To facilitate this we'll add new routes that handle 4 different views. (The routes here are just suggestions and can be modified as needed).

### Routes
 
See #13898 

#### Site specific view
`http://calypso.localhost:3000/comments/:filterName:/:siteId:`
In a site specific view we can see all comments on a given site for any post.

#### Post specific view
`http://calypso.localhost:3000/post/:postId:/comments/:filterName:/:siteId:`
In a post specific view, we can see any comments on a given post

<del> #### User specific View
`http://calypso.localhost:3000/user/:userId:/comments/:filterName:`
We see all comments from a given user.

Open Question:
- Can we filter by user comments on a given site/post too?</del>

### Filters
Beyond what comments we see on a post, site, or all sites, we can apply additional filters to the list:

- Pending - Comments that have not been approved
- Approved - Comments that are visible on the post
- Spam - Comments that have been auto marked as spam, or have been user mark
- Trash - A list of trashed comments
- All - A list of pending + approved comments

![artboard-copy-6](https://cloud.githubusercontent.com/assets/1270189/25921846/e92e5408-358b-11e7-936b-2f185b2785f5.png)

We should spin off another issue, once we know what our navigation choices look like in a small viewport, vs desktop sizes.

### Search

<del>- We can also search the related list. If text matches the user, content or title we should see the related list #13901</del>

### Actions
A comment starts off in `pending` or `spam` and may be moved to any other filter. We can also reply directly to a comment, like a comment, edit the comment to fix typos, or delete a comment permanently.

- Replying to a user immediately approves it
- Liking a comment also approves it.

See related issues.

### Bulk Actions

We must be able to perform bulk actions on many comments. The list view would be a good fit for this.

See #13896

### Detail View
We can click on a comment to go into a detail view.

See #13894 

### User View
We can click on a user avatar to display a user info modal.

See #13895

**Comment by drw158** [comment]
If you have the Pending filter selected, I think the comments in the list will need the yellow background styling. This means every comment in the list will have the yellow styling. If the users clicks approve, and we want the comment to stay around until a page refresh, then that comment will lose it's yellow styling to differentiate it. If that comment is removed instantly, then there's no problem making all comments non-yellow in the pending list. We'll have to play with it.
