### ISSUE TITLE
Help: Happiness Engineer list description is small on mobile

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#1390]
It might be best if it were a little bit bigger.

![screen shot 2015-12-08 at 8 11 08 pm](https://cloud.githubusercontent.com/assets/426388/11665459/d72b3d62-9de7-11e5-89e4-4d2fb221fb3a.png)

**Comment by dllh** [comment]
This is as designed (`11px/16px Open Sans`). Cc @mattmiklic in case you'd like to suggest an adjustment.

**Comment by mattmiklic** [comment]
Would be fine to bump that to 14px.
