### ISSUE TITLE
Comments: edit

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#13905]
This opens up a text field that allows us to make quick edits on a comment's content.

Open Question: Do we use a simple text field here or do we navigate to the post editor?

**Comment by drw158** [comment]
WP Admin: allows editing of Name, Email, URL, Comment, Timestamp. Deleting the email appears to not do anything on the frontend. Editing the name, URL, timestamp, and comment updates the frontend of the site. Navigating away from the page without saving does not produce a warning dialog.

![screen shot 2017-05-24 at 8 51 06 am](https://cloud.githubusercontent.com/assets/618551/26406938/597b3d42-405f-11e7-80e6-4476679c2fcc.png)

I don't see the value of editing the email, and changing the timestamp seems a bit dubious. Therefore, I think we should just focus on name, url, and comment.

Here are 2 options. Usertesting these options will help us decide.

![group 5](https://cloud.githubusercontent.com/assets/618551/26407084/be077672-405f-11e7-957b-7d61b6726ba8.png)
![group 6](https://cloud.githubusercontent.com/assets/618551/26407087/be59eb6e-405f-11e7-91b9-a8e97384dad4.png)

**Comment by drw158** [comment]
After some thought, I think I prefer the second mockup, except:

- compact buttons, not regular ones
- also disable the X icon

as we use it, we'll probably need to make tweaks

**Comment by gwwar** [comment]
So another detail is that the post content may contain HTML. Should we add some basic toolbar buttons, or display the escaped markup?

**Comment by drw158** [comment]
Escaped markup is fine for now I think.

--
Dave Whitley / Designer at Automattic
