### ISSUE TITLE
Use camelCase on `state.login.twoFactorAuth.`

### ISSUE THREAD

**Issue by yurynix** [Automattic/wp-calypso#13918]
Followup on @stephanethomas comment [here](https://github.com/Automattic/wp-calypso/pull/13742#discussion_r115467702)

Change redux’s state’s snake_case to camelCase on `state.login.twoFactorAuth.`

**Comment by stephanethomas** [comment]
This is was addressed in https://github.com/Automattic/wp-calypso/pull/14967/commits/b8bcce49c9a9df0a38eded5d6e94096a60bf5361.
