### ISSUE TITLE
Dashboard:  Site Preview button does not load site if custom domain is used

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#13913]
Noted this while helping a few site owners today.  If a site is using a custom domain, when clicking the Site Preview button in the dashboard, no preview of the site is loaded, just a constantly spinning load icon.

Gif:  
![nopreview](https://cloud.githubusercontent.com/assets/1967448/25930321/55b9e578-35a1-11e7-931a-f6ac78b50db4.gif)

Note: preview seems to work fine if the site is using the default sitename.wordpress.com URL as primary, so only seems to affect sites with a custom domain (mapped or registered at WordPress.com) set to the primary address.

Also tested to see if site visibility is a factor, but preview will not load for either public or private sites.

**Comment by tyxla** [comment]
It appears we were previously forcing HTTPS for the preview frame, and I appear to have broken that with #13805. Fix coming right away.

**Comment by tyxla** [comment]
I've addressed this one in #13914, it could use a review and/or testing.

**Comment by tyxla** [comment]
@jerrysarcastic we've deployed the fix for this in #13914, could you please confirm this resolved the issue for you? Thanks!

**Comment by designsimply** [comment]
I tested with an AT site using a custom domain and a free plan and site preview is working for me:

<img alt="img_1182" src="https://cloud.githubusercontent.com/assets/1119271/25961047/1c990e00-3636-11e7-8b9c-22438e6a6ca0.PNG" width="300" />
<sup>Seen at https://wordpress.com/themes/designsimply-automated-transfer-4.blog (click "Site Preview" in the W menu) using iPhone 6S Safari iOS 10.3.1 (Rebalance theme).</sup>

![screen shot 2017-05-11 at thu may 11 10 41 37 am](https://cloud.githubusercontent.com/assets/1119271/25961138/770372d6-3636-11e7-865d-9f0132855c34.png)
<sup>Seen at https://wordpress.com/themes/designsimply-automated-transfer-4.blog (click "Site Preview" in the W menu) using Safari 10.1 on Mac OS X 10.12.4 (Rebalance theme).</sup>

**Comment by jerrysarcastic** [comment]
Worked for me as well in testing a few wpcom and AT sites with custom domains.  Thanks!
