### ISSUE TITLE
Refreshed Manage: Add "Hit return to" to URL result

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13939]
Currently:

<img width="743" alt="screen shot 2017-05-11 at 9 40 19 am" src="https://cloud.githubusercontent.com/assets/24388/25961112/f84a480a-362d-11e7-8950-6f709ac3ee6e.png">

Should be:

<img width="542" alt="screen shot 2017-05-11 at 9 41 46 am" src="https://cloud.githubusercontent.com/assets/24388/25961135/131665ba-362e-11e7-9227-ccea36e6741b.png">

**Comment by bluefuton** [comment]
We previously discussed this here: https://github.com/Automattic/wp-calypso/issues/11549#issuecomment-282061766

I think the feature itself is really useful, but for accessibility reasons, I strongly recommend that we do not label it "hit return to...".

> A lot of users won't have a return key to hit. Virtual keyboards on mobile devices often have a "submit" or "search" for an input instead, and those using assistive technologies (e.g. a screen reader) might not be hitting keys at all.

**Comment by jancavan** [comment]
I started implementing this here: https://github.com/Automattic/wp-calypso/pull/14244

But made me realize that once you hit "Follow", the sentence changes to "Hit return to following [site]". It feels like they can't be in the same sentence.

![screenshot 2017-05-19 08 34 44](https://cloud.githubusercontent.com/assets/4924246/26255314/081c94e0-3c6e-11e7-9b18-1859a571d783.png)

**Comment by blowery** [comment]
> So either we remove "Hit return" completely, or if we decide to keep it, maybe it disappears once you're following the site already?

I think hiding it is the way to go, though the button is going to jump...

Maybe we suppress that button entirely if you're following the site? Let the new entry in the following section deal with it.

**Comment by jancavan** [comment]
> though the button is going to jump...

True. I think this issue can be solved through: https://github.com/Automattic/wp-calypso/issues/14294, but this itself isn't an easy fix.

Another idea for a short-term solution:
![hit-return](https://cloud.githubusercontent.com/assets/4924246/26269939/c67e715e-3cac-11e7-9ec9-94e2c461037d.png)

After following, would change to:
![you-are-now-following](https://cloud.githubusercontent.com/assets/4924246/26269945/cf9b4938-3cac-11e7-84e0-4661ec82a223.png)

There's still a little bit of jumpiness, but not as bad as if we completely dropped it. At least for the English version, I don't think this will make the user lose focus or have to re-aim their cursor:

Example: https://invis.io/78BSY4MEG#/234758586_Hit-Return

What about for i18n?

**Comment by bluefuton** [comment]
> What about for i18n?

That's a very good point. In either followed or unfollowed state, I don't think we can pass an additional word into the translation string. 

In some languages, the 'Follow'/'Following' word may come at the start of the sentence, so I don't think we can use the follow button as part of the phrase.

**Comment by jancavan** [comment]
> In some languages, the 'Follow'/'Following' word may come at the start of the sentence

Hmm, good point. I think it needs more thought, but we should probably punt this for now.
