### ISSUE TITLE
Refreshed Manage: Use same grey as Following

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13938]
Please make sure that, on Refreshed Manage, we're using the same grey as on Following for lines and boxes, and that the box is 2px.

Current Manage:

<img width="225" alt="screen shot 2017-05-11 at 9 36 39 am" src="https://cloud.githubusercontent.com/assets/24388/25961026/a7e08d48-362d-11e7-8932-0b3758cbae91.png">

Current Following:

<img width="236" alt="screen shot 2017-05-11 at 9 36 44 am" src="https://cloud.githubusercontent.com/assets/24388/25961033/ace7ee80-362d-11e7-99c8-caebd5370aff.png">

cc @jancavan @samouri

**Comment by fraying** [comment]
Note: This doesn't apply to the in-between-the-results light grey lines, which are perfect. But the search box should be 2px and the save grey as on the homepage, as well as the "More" lines.

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/14002
