### ISSUE TITLE
Reader: Following Manage email settings do not close when clicking 'Settings'

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#13937]
From https://github.com/Automattic/wp-calypso/pull/13787#issuecomment-300676610:

> One issue I noticed about the popover is clicking on the word "Settings" displays it, but clicking again doesn't make it go away (unlike the cog). Any way to fix that?

/cc @samouri

**Comment by bluefuton** [comment]
@alisterscott has documented this one in https://github.com/Automattic/wp-calypso/issues/14085, so closing this one as a duplicate.
