### ISSUE TITLE
Reader: Following an external RSS site results in two entries in Manage

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#13934]
Start at https://wpcalypso.wordpress.com/following/manage

Best to start with a fairly empty account.

Follow `http://daringfireball.net`.

Notice the entry appear in the list.

Wait.

Reload.

Notice we now have two entries.

This is happening because the feed URL changes in the response...

**Comment by samouri** [comment]
Example: ![](https://cloudup.com/cMx9FULFoJA)

**Comment by blowery** [comment]
I'm taking a look at this.
