### ISSUE TITLE
Refreshed Manage: Font differences between recs and list items (Safari)

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13943]
In Safari, the fonts in recs are heavier than the fonts in the followed sites list. 

<img width="414" alt="screen shot 2017-05-11 at 10 02 05 am" src="https://cloud.githubusercontent.com/assets/24388/25962093/5b1300aa-3631-11e7-8a70-9069c41fc520.png">

@jancavan Is this that wonky antialiased css setting?

**Comment by jancavan** [comment]
> Is this that wonky antialiased css setting?

It's the same issue as: https://github.com/Automattic/wp-calypso/pull/13537. Although this isn't a `fixed` element (it's positioned `relative`) so I'm not sure why the font is aliased. Either way, it's solved in: https://github.com/Automattic/wp-calypso/pull/14184
