### ISSUE TITLE
Reader Search on Manage: search errors maybe shouldn't be the same as other Calypso errors

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#13947]
Using the same error box for a search error as when something like a post fails to save seems a bit odd to me. This one in particular is not great given that we are sticking the whole string into the error box.

<img width="1084" alt="screen shot 2017-05-11 at 11 29 53 am" src="https://cloud.githubusercontent.com/assets/820871/25963087/5f0ce2b4-363d-11e7-8266-238b7077fac6.png">

props @designsimply

**Comment by fraying** [comment]
I suggest breaking this into two issues.

1: Limit search query size (no human needs that much text to search for a site). What should be the limit, @gibrown?

2. Error display. (I know we were talking about this elsewhere yesterday, @jancavan.) I think the plan is to display errors inline, where the results would be, in a similar format.

**Comment by jancavan** [comment]
> Error display. (I know we were talking about this elsewhere yesterday, @jancavan.) I think the plan is to display errors inline, where the results would be, in a similar format.

Yes, this is correct. 

@samouri mentioned there are 3 errors that could possibly occur:

1. no results
2. error retrieving results
3. error retrieving page X of results

We have a PR that's in progress for (1): https://github.com/Automattic/wp-calypso/pull/13834

But I'm not sure when (2) https://github.com/Automattic/wp-calypso/pull/13834#issuecomment-300612377 and (3) happen?

**Comment by samouri** [comment]
> But I'm not sure when (2) #13834 (comment) and (3) happen?

A couple reasons:
1. user loses internet connection
2. some error happens on the server

**Comment by gibrown** [comment]
> Limit search query size (no human needs that much text to search for a site). What should be the limit

On the API side we have typically been limiting it to 500 characters. There are some use cases where the user pastes in text that are good to support up to a point.

So maybe this issue is just imposing that limit with some fun messaging when searching since it looks like the other cases are getting covered. Agree that 1 and 2 should probably result in that same error bubble, but maybe we can say more about why?

**Comment by fraying** [comment]
500 seems overly generous to me

**Comment by fraying** [comment]
Would 100 characters be enough?

**Comment by gibrown** [comment]
100 is probably not high enough for at least two use cases that seem interesting.

1. German has an average word length of 11.66. Looking at our indexed German content, the 95th percentile of word count is 14 words (160 chars with no punctuation or spaces) (see this fun chart btw: http://www.ravi.io/language-word-lengths ). At 250 chars we can search for 99% of all German titles. (250 looks like it would be enough for 99% of titles in other langs too).

2. Of the 66k active feeds since the beginning of the year, there are 209 (0.3%) where the url is longer than 100 chars. I'm actually surprised that the max I see is only 193 chars. The distribution (lots of urls close to the 200 limit with a hard cut off) makes me wonder if we are applying a max of 200 and are preventing users from actually following some urls (cc @blowery ).

The above is why I chose 500 at some point. Make it fairly unlikely for a user to ever encounter it even when pasting in some text. I think this will also get interesting if we go the path of saved searches.

**Comment by blowery** [comment]
>  The distribution (lots of urls close to the 200 limit with a hard cut off) makes me wonder if we are applying a max of 200 and are preventing users from actually following some urls (cc @blowery ).

Nothing I'm aware of... But I'll look into it.

**Comment by blowery** [comment]
> Nothing I'm aware of... But I'll look into it.

AFAICT there's no limit.
