### ISSUE TITLE
Refreshed Manage: Search Results should have lines too

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13949]
Currently, in the Followed Sites list, there are lines between each site:

<img width="742" alt="screen shot 2017-05-11 at 11 23 18 am" src="https://cloud.githubusercontent.com/assets/24388/25965285/5d58e4c8-363c-11e7-8ef8-8a12ade84b85.png">

But there are no lines in between search results.

<img width="812" alt="screen shot 2017-05-11 at 11 23 10 am" src="https://cloud.githubusercontent.com/assets/24388/25965307/6b910476-363c-11e7-8709-dec5d26e6f8c.png">

It should be one way or the other. I suggest adding lines to the search results.

cc @jancavan

**Comment by jancavan** [comment]
@fraying I just felt like there were too many lines especially with the "Show More" line at the very end:

(We do eventually show the lines after you click "Show More").

<img width="738" alt="screenshot 2017-05-11 15 36 58" src="https://cloud.githubusercontent.com/assets/4924246/25974787/b00a4888-365f-11e7-8c1d-321ac42fafc5.png">

Although admittedly, no line looked better when we initially showed a few results. Lines are much more useful now that were showing more.

**Comment by fraying** [comment]
Agreed! Now that there are 10 results, lines are needed. I like the super light lines in between the results, with a slightly darker line for SHOW MORE. Gives them some hierarchy.  👍
