### ISSUE TITLE
Social Signup: Connection loop when .com email already exists

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#13954]
#### Steps to reproduce
1. Starting at URL: https://calypso.live/start/social?branch=master
2. Try signing in with a gmail email that is already connected to a WP.com account 
3. Once you see the connection error try logging in again 
4. It does not give the option to log in with a different gmail account

#### What I expected
Once I tried to connect one gmail account, I wanted to try to connect another gmail that had not yet been connected to a .com account.

#### What happened instead
I was stuck in a loop with no option to select a different account: 

#### Browser / OS version
chrome (incognito window)  57.0.2987.133

#### Screenshot / Video
<img src="http://cld.wthms.co/7YxrI+"/>

#### Context / Source
#painpoint
#manual-testing

**Comment by Tug** [comment]
This will be fixed when we implement login with Google.

Also we can't log someone out of his Google account so the only way for us to really fix this is to either display a more meaningful error message or have no error ;)

**Comment by yurynix** [comment]
I agree with Tug, I think that's a won't fix.

**Comment by fabianapsimoes** [comment]
cc @ranh for a more meaningful message.

**Comment by michelleweber** [comment]
Something like this?

_Whoops! An account with that email address already exists. To sign up with another address, please log out of this Google account and try again with the new address._

(I'm assuming this is only an issue with Google? If I'm wrong, please let me know!)

**Comment by fabianapsimoes** [comment]
For now, only with Google because it's the first service we're implementing :)

@Tug @yurynix do you anticipate this to be an issue for Facebook and other future services too? I'd think so.

**Comment by Tug** [comment]
Yes it's also an issue for Facebook.

I guess the main problem here is the fact that we cannot login if we already have an WordPress.com account with this email address. For this particular error we should tell the user to login using their credentials and then associate their account with Google/Facebook (we haven't done it yet).

The other (minor) problem is when you are already connected to a Google/Facebook account and it decides to use this one because you have already authorised WordPress.com.
That's a bit tricky in terms of UX and I'm not sure how other services handle it. As a user you have the choice between:
- Logging out of Google/Facebook (or opening a new private window or clearing your cookies)
- Going to Google/Facebook Settings and removing the authorisation for WordPress.com so you will be prompted to choose another account in the popup.

**Comment by fabianapsimoes** [comment]
Sounds like we could use some design input here cc @danhauk

**Comment by danhauk** [comment]
If I'm understanding correctly, I agree there's not much we can do on our side other than improve the messaging to the user.

Google seems a little different than Facebook in that I can be signed in to multiple accounts at once. But when I am signed into multiple accounts, the auth screen lets me choose each time I click the <kbd>Continue with Google</kbd> button. Is there a way to force [this screen](https://cloudup.com/crSRGVXViJc) on the auth popup even if I'm only logged in to one Google account?

If not, for the time being we should improve the error message we show. Once we have a way to connect an account inside `/me` (or via re-auth with email/password), we can revisit and see if this is still as much of an issue.

**Comment by ranh** [comment]
How about this? It's cumbersome, but probably good enough as a temporary solution:

> Whoops! Your email on Google (mail@example.com) is already in use WordPress.com. To use your existing WordPress.com account, log in with your email address and password. To create a new WordPress.com account, you'll have to switch to a different Google account.

**Comment by ranh** [comment]
@gziolo #14306 does not address all the concerns raised here, so I'm reopening this.

Adding the account selection screen doesn't keep users from choosing an account with a bad email. If users choose an account with an email that's already taken on WordPress.com, we show this:

![ranimac3 screenshot 2017-05-24 at 11 25 40](https://cloud.githubusercontent.com/assets/426518/26393914/f95c3b90-4073-11e7-9c23-8f4873ec8988.png)

Furthermore, the account selection screen is not available when users are logged out of Google completely. If a user logs in to Google during social signup, and the account they are logging in to has an email address already taken on WordPress.com, we show the same error as above.

I think it would be enough to just change the error message copy as suggested above.
