### ISSUE TITLE
Refreshed Manage: Recommended Sites: Don't recommend sites without avatars/descriptions

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13953]
The current implementation of Recommended Sites on Refreshed Manage looks like this:

<img width="747" alt="screen shot 2017-05-11 at 11 27 23 am" src="https://cloud.githubusercontent.com/assets/24388/25965439/d905ba10-363c-11e7-8545-f000f634de68.png">

I don't think we should be recommending sites that lack avatars or descriptions.

Check out the first recommendation. There's very little to go on for the user here - just a username (that's not a word) and a title. 

We shouldn't be putting a site in front of the user unless that site presents well and gives the user reasons to click. A site suggestion that's missing critical data like an avatar or description just doesn't give the user enough reason to be interested. We shouldn't be recommending them.

Would this be hard to change? @aaronyan

**Comment by fraying** [comment]
Also, @jancavan, shouldn't the rec posts in this format get 2-3 lines of description?

**Comment by aaronyan** [comment]
@fraying: can do! I've deployed a change that restricts site recommendations to those with avatars and site descriptions in wpcom-156054.

**Comment by jancavan** [comment]
> Also, @jancavan, shouldn't the rec posts in this format get 2-3 lines of description?

I forget which PR I fixed this, but I know it's fixed:

<img width="364" alt="screenshot 2017-05-17 09 30 35" src="https://cloud.githubusercontent.com/assets/4924246/26165051/80617bd2-3ae3-11e7-943c-bdb8f9a203b0.png">

**Comment by jancavan** [comment]
I think this is done @aaronyan? Going to close this issue.
