### ISSUE TITLE
Purchases: Domain mappings refunded in credits

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#1396]
Domain mappings cancelled from the purchases screen are refunded in credits instead of back to the original payment method.

To reproduce:
1) Purchase a domain mapping from /domains
2) Cancel and Refund via /purchases
3) See that no refund is issued in /me/billing
4) Attempt another purchase and a 13 credit discount will be offered during checkout, because credits were issued instead of an actual refund.

**Comment by fabianapsimoes** [comment]
Moved to T352-code, since it's a back-end issue.
