### ISSUE TITLE
Refreshed Manage: Try showing direct-follow URL with search results

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13969]
Currently, in Search on Manage, we have two different designs. If we determine the user is entering a URL, we show a simple "follow URL" link that matches the current UX. If the user enters text, we display the new search results.

This works for most cases. But! There are times where it would be better to show both the direct-follow URL link _and_ search results. Like:

- I want to put in a URL with lots of feeds (like "medium.com") and see suggestions for popular follows on that site.
- I want to put in a URL of a site, but not follow that exact site. I want to see things I could follow that are related to that site.
- I want to follow a site that doesn't have an autodiscoverable feed (like nytimes.com).

For all those reasons, we need a design that includes both the direct-follow URL link _and_ site results. Here's what I propose.

![som-url-plus-search](https://cloud.githubusercontent.com/assets/24388/25973308/62f6924c-3658-11e7-8a4a-66df1d14fa13.png)

What's new: the first result is centered (to show it's different). Clicking it would attempt to follow that URL (like we do now). Below it are the results as normal.

Notes:

- Hitting return in this state should do the same thing as clicking the "follow URL" link.
- This top "Follow URL" result would only show up when we can assume the user is entering a URL. So, when the user has entered "nytimes.c" it would not appear. It would only appear when they get to  "nytimes.co" because that's a valid URL.
- If the user selects that direct follow URL link and it has no feed, we'd error as now.

This change would mean that search results are always shown, no matter what the user enters. The only difference now is, if the text is also a URL, we show a follow link. Note that this means we could use the same treatment for the main Reader Search!

Thoughts?

cc @blowery, @samouri, @bluefuton, @gibrown, @jancavan 

Reminder: This isn't a prerequisite for launching the call for testing. It's an improvement we've discussed and should give a try.

**Comment by gibrown** [comment]
Seems like that would solve most of the problems we've discussed. Feels like I need to try it...

We should make sure we add good Tracks events to indicate both when we are showing the url follow and when the user clicks on it. Treat it similar to the search results with both a render and an interact event.

**Comment by fraying** [comment]
Tracks for the different kinds of results are a VERY good idea.

**Comment by chaitanyamsv** [comment]
I always see _Sorry, no sites that we could find match chaittestpress.com. Try to follow chaittestpress.com anyway?_ message for all the sites regardless of whether I am following them or not.

For a new site:
![new site](https://cloud.githubusercontent.com/assets/1519466/26481718/27acba1e-4237-11e7-8cd7-fea81d9310e0.png)

For an already following site:
![following site](https://cloud.githubusercontent.com/assets/1519466/26481694/06cf645e-4237-11e7-994e-514e901e6cb6.png)

I hope this issue addresses the above misleading message.

**Comment by jancavan** [comment]
Thanks for reporting this @chaitanyamsv. This issue is being tracked in https://github.com/Automattic/wp-calypso/issues/14294, specifically this comment: https://github.com/Automattic/wp-calypso/issues/14294#issuecomment-303868727

**Comment by bluefuton** [comment]
We launched the revamped Manage Following with this feature (showing direct-follow URL with search results) 👍
