### ISSUE TITLE
Refreshed Manage: All Site items: text should scoot right 4px

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13975]
In order to stay consistent with the cards, the text in Site Items (both followed, recs, and results) needs to move right 4px.

In the image below, the top one is from the homepage and the bottom is from Refreshed Manage. They should match.

<img width="701" alt="screen shot 2017-05-11 at 4 20 02 pm" src="https://cloud.githubusercontent.com/assets/24388/25975879/d528041a-3665-11e7-9bc8-d4f2bc4c222a.png">

cc @jancavan

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/14006.
