### ISSUE TITLE
Purchases: Domain cancellation email link directs older users to Wp-Admin

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#1397]
When a pre-sept 2014 user cancels a domain via Calypso, the email link takes them back to wp-admin once they follow the cancellation link.

To reproduce:
1) Buy a domain on a pre-2014 user (site can be brand new)
2) Cancel the domain
3) Follow the email link to wp-admin

The domain cancellation link should be updated to lead to Calypso.

**Comment by fabianapsimoes** [comment]
Moved to T353-code since it's a back-end issue.
