### ISSUE TITLE
Checkout: Exception when renewing a product

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#13971]
When attempting to renew a domain mapping product from within calypso, the following error was thrown when clicking "Renew Now":

![purchases_ _manage_purchase_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/25974020/7e2545d8-365b-11e7-96e3-56493def2655.png)

![purchases_ _manage_purchase_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/25974030/964a78ae-365b-11e7-816b-8e92d167cc5f.png)

**Comment by klimeryk** [comment]
Should be fixed by @dzver's fix here: https://github.com/Automattic/wp-calypso/pull/13984.
@timmyc, can you confirm?

**Comment by timmyc** [comment]
@klimeryk that appears to have fixed the issue - thanks!
