### ISSUE TITLE
Editor: cannot drag and drop into the featured image area when in HTML mode

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#13977]
Steps to reproduce:

1. Start a new post at https://wordpress.com/post
1. Switch to HTML mode.
1. Expand the Post Settings > Featured Image option panel.
1. Try to drag and drop an image into the featured image area.

<strong>Result:</strong> you cannot drag and drop into the featured image area when in HTML mode. The drop zone for the main HTML edit area is too big!

<strong>Video:</strong> [47s](https://cloudup.com/cbu7Pz3mBWr)

![screen shot 2017-05-11 at thu may 11 5 30 42 pm](https://cloud.githubusercontent.com/assets/1119271/25976069/9f1cfc54-366f-11e7-9e20-f5827b8335ec.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10951 using Safari 10.1 on Mac OS X 10.12.4.</sup>

#manual-testing

**Comment by rachelmcr** [comment]
Closing as I can no longer reproduce this issue; a dropzone for the featured image also appears separate from the post content dropzone, even in HTML mode.

#bug-scrub #pre-gutenburg-bug-purge
