### ISSUE TITLE
Refreshed Manage: Recommended Sites: Not showing avatars sometimes

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#13973]
We are sometimes not showing the avatar in Site Recommendations. This occurs even when we are provided with an avatar URL.

This was discovered after restricting the recommended sites to those with avatars and site descriptions (see #13953). The site meta data says there is an avatar and provides a url. We don't load the avatar though.

# Examples:

<img width="361" alt="gymternet" src="https://cloud.githubusercontent.com/assets/4505888/25975515/9412329a-3663-11e7-8ec4-93bf0fbaa25c.png">

```
Array (
    [ID] => 68324941
    [name] => Lauren
    [URL] => http://thegymter.wordpress.com
    [avatar_URL] => https://1.gravatar.com/avatar/d041fcbbae1300cc3e45e02b394c1073?s=96&d=identicon&r=G
    [profile_URL] => http://en.gravatar.com/lch3153
    [has_avatar] => 1
)
```

<img width="366" alt="pacific" src="https://cloud.githubusercontent.com/assets/4505888/25975553/cab1e034-3663-11e7-9ac0-61dba9b3ae94.png">

```
Array (
    [ID] => 86427249
    [name] => Pacific Outlier
    [URL] => http://pacificoutlier.wordpress.com
    [avatar_URL] => https://1.gravatar.com/avatar/a98ffbc0b26763daf77c64708265f02e?s=96&d=identicon&r=G
    [profile_URL] => http://en.gravatar.com/poirauckland
    [has_avatar] => 1
)

```

**Comment by fraying** [comment]
Nice catch, @aaronyan

**Comment by blowery** [comment]
@aaronyan those are both unset gravatars. see https://en.gravatar.com/poirauckland and http://en.gravatar.com/lch3153

**Comment by blowery** [comment]
i think those are just busted has_avatar flags

**Comment by blowery** [comment]
moving to backlog
