### ISSUE TITLE
Publicize: Add avatars to connected services

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#13992]
This has been brought up in #12471 — It would be helpful to show avatars along with social media icons. 

![screen-shot-2017-05-12-at-14 52 21](https://cloud.githubusercontent.com/assets/908665/26000980/cf6c9ec4-3722-11e7-8523-ce7e24753586.jpg)

I can see this will be helpful for users so I've played around it. To respect the social medias' brands, we should avoid making their logos rounded or putting their logos behind of the avatars. I've also moved the toggle to the right to make it less busy.

![artboard 1](https://cloud.githubusercontent.com/assets/908665/26000681/d32ae0b2-3721-11e7-96b9-f315848f3d57.png)

----
In a conversation with @folletto, we wondered this question.

_"Should we differentiate a Facebook profile and a Facebook page?"_

![artboard 2](https://cloud.githubusercontent.com/assets/908665/26003809/adb8d7a8-372b-11e7-95dc-c68d053a3269.png)

While I can see this could be helpful for some, I feel we're making all somewhat verbose only because of the Facebook page vs profile issue. Is it common to have both page and profile with an identical name? Don't they usually have different names when activities on the accounts matter?

What's your opinion?

**Comment by folletto** [comment]
> Is it common to have both page and profile with an identical name? Don't they usually have different names when activities on the accounts matter?

It's not common, but if you're a business and have a business page, the two names might match, ad at that point it's not just hard, it's also dangerous as they might end up posting personal content on a business channel. 
My assessment here is: _low in terms of absolute numbers, high in terms of risk._

However: it's also true that we currently don't seem to allow more than one Facebook connection, so it might not be a big issue _right now_: as I'd like to have this solved in advance, it's probably not super critical.

---

Meta consideration: the design should be identical in the Editor too, the current one is already slightly different as it uses a toggle (the Editor should use a toggle too) but this would make them diverge even further. I'd try to build the above as a component and update the Editor too:

![screen shot 2017-05-12 at 15 30 27](https://cloud.githubusercontent.com/assets/4389/26002601/14369ca8-3728-11e7-892f-e5437a33532b.png)

**Comment by drw158** [comment]
I love the first mockup you showed. The logo overlay on the avatar is nice.

 I get the concern about the FB Page, but I don't think it's critical since you can only have one FB account connected. Moving the toggles to the right is a nice touch.

Traditionally we only allow circle avatars for people. We are very consistent on that. I would try doing circle avatars instead of a square avatar.

The social logos should all have a "shape" version of all the social services, so we are good there!

**Comment by iamtakashi** [comment]
> Traditionally we only allow circle avatars for people. We are very consistent on that. I would try doing circle avatars instead of a square avatar.

A good point, but I wasn't sure if we can assume that people use their headshot as their avatars for those services? I personally do, as we can see in my mockup, but it could be a logo or something else, couldn't it?

**Comment by iamtakashi** [comment]
Oh, I probably wasn't clear on that — the avatar is fetched from the connected social media accounts, not the one used for WP.com account.

**Comment by retrofox** [comment]
> I get the concern about the FB Page, but I don't think it's critical since you can only have one FB account connected. Moving the toggles to the right is a nice touch.

do you mean to this @drw158 ?

<img src="https://cloud.githubusercontent.com/assets/77539/26007492/1b499c04-3717-11e7-8990-8211371eafb1.png" width="500px" />

_The market selection ..._

**Comment by iamtakashi** [comment]
> Meta consideration: the design should be identical in the Editor too, the current one is already slightly different as it uses a toggle (the Editor should use a toggle too) but this would make them diverge even further. I'd try to build the above as a component and update the Editor too:

cc: @shaunandrews

**Comment by drw158** [comment]
Nope no problem, it was pretty clear to me that the avatar was being fetched from the services. We have the same concern on .com though — they could use a logo for their .com identity. The idea is that things that represent "people" are in circles, sites are squares. Because twitter and fb profiles represent a person, it would be best to make them circles. 

Not sure what to do about fb pages... they should be a square, but might not be worth making an exception.

**Comment by iamtakashi** [comment]
That makes sense. Thanks for clarifying!

![artboard 1](https://cloud.githubusercontent.com/assets/908665/26025673/c7de4d52-37e4-11e7-919b-443932d0a8a8.png)
