### ISSUE TITLE
Reader: Multi author site showing with with byline and avatar (boing boing)

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#13990]
From https://wpcalypso.wordpress.com/following/manage?q=boing&showMoreResults=true

<img width="759" alt="screenshot 2017-05-12 09 39 04" src="https://cloud.githubusercontent.com/assets/14350/26000436/f31c4b70-36f6-11e7-8ed6-a022699fe3ac.png">

I expected BB to show the BB site icon, not the owner of the Jetpack connection.

**Comment by designsimply** [comment]
What it is supposed to look like instead? Should it be using the site icon and no byline if the blog has multi-author published posts?

**Comment by fraying** [comment]
>site icon and no byline if the blog has multi-author published posts?

Yup! And, if we don't have a site icon, then no icon.

**Comment by blowery** [comment]
Huh.

So BB has no site icon _and_ no feed image. In fact, their homepage advertises a blank image as the `og:image` for the site.
