### ISSUE TITLE
Following Management: after reload, subscriptions move to top of 'date followed' list when delivery settings only have been modified

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#140]
The API currently bumps the follow date on any modification to a subscription. This means that existing feeds find their way to the top of the list after you've changed email delivery settings, if you're sorting by 'Date followed'.

We should only change the subscription date on follow.

Reported by @ryanboren.

**Comment by alisterscott** [comment]
Bug scub 11 May 2017 - confirmed this is still an issue - changing email delivery option moved the item to the top of the list when sorting "By Date"

Could we just change "By Date" to "By Date Modified"?

**Comment by alisterscott** [comment]
I can confirm this was fixed by a recent API change. Thanks @blowery !!
