### ISSUE TITLE
WooCommerce: Add ability to reorder additional details (attributes)

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#14005]
As a user, I want to be able to rearrange the order in which my additional details will show up on the product page.

Came up in: https://github.com/Automattic/wp-calypso/pull/13891#issuecomment-301054584

As of writing this issue, we have decided to leave this off for V1.

cc: @justinshreve @jameskoster

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
