### ISSUE TITLE
Purchases: Domain cancellation doesn't show any message after following the cancellation link

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#1401]
Following the domain cancellation link for a domain within the refund period lands the user on /purchases without any kind of cancellation confirmation.

To reproduce:
1) Add a domain on /domains
2) Cancel the domain on /purchases
3) Click the link in the email
4) You will land on /purchases without any kind of confirmation message

<img width="668" alt="screen shot 2015-12-08 at 6 56 13 pm" src="https://cloud.githubusercontent.com/assets/8921630/11672340/b8bd7098-9ddd-11e5-83c5-533efd314ddc.png">

Here is a gif of it happening, from the pasted confirmation link:
![ezgif-2651685149](https://cloud.githubusercontent.com/assets/8921630/11672411/5ec171e2-9dde-11e5-810f-6e0cce8eb156.gif)

**Comment by fabianapsimoes** [comment]
@spncrb can you test this for an account that has other upgrades? I'm wondering if the lack of notice is related to the domain flow itself, or to the fact that this account was left empty after the cancellation.

**Comment by spncrb** [comment]
I can't reproduce this error with or without other upgrades - I don't even get a confirmation link in an email - it just cancels straight away.

**Comment by drewblaisdell** [comment]
This was broken because we were redirecting to the legacy `/my-upgrades`, which redirects to `/purchases`, instead of redirecting to `/purchases/cancel-success` after clicking the confirmation link in an email. This is fixed now.
