### ISSUE TITLE
Preserve the original order of sites, instead of sorting them alphabetically; keep primary site at the top

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#14023]
Implemented in #13997.

(This issue auto-converted from a project card originally added by @tyxla)

**Comment by mtias** [comment]
It's not just primary site at the top. The rest of the sites are not ordered alphabetically, and they should.

**Comment by tyxla** [comment]
In addition to keeping the primary site at the top, the rest of the sites have to be sorted by their name, alphabetically, non case sensitive - that'll help maintain the original order. I've left that as a note in #13997, but we can address it in a separate PR.

**Comment by mtias** [comment]
Sites are not ordered alphabetically, so we should fix that while keeping primary site at the top. cc @rodrigoi @mcsf @tyxla

**Comment by tyxla** [comment]
Thanks for spinning it up so swiftly @rodrigoi!
