### ISSUE TITLE
Login: 2FA: Validation messages for 2FA

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#14038]
There are new validation messages in https://cloudup.com/irr9H-B85fq.

We should update the inline validation messages in the 2FA screens to match these.

Raised by @fabianapsimoes in #13987

**Comment by fabianapsimoes** [comment]
@scruffian is this patter the new norm in Calypso? I haven't seen it before.

**Comment by scruffian** [comment]
This being tracked by https://github.com/Automattic/wp-calypso/issues/14090, so closing.

**Comment by fabianapsimoes** [comment]
@scruffian this is more about the styling of the validation messages than the copy. Will this be resolved in #14090 too?

**Comment by scruffian** [comment]
I talked to @danhauk about the styling and he is happy with the current implementation. However we should change the global notices to match these mockups, which I have done in https://github.com/Automattic/wp-calypso/pull/14094
