### ISSUE TITLE
Search: Search term doesn't clear when switching to Blog Posts screen

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#1403]
Entering a search term and then switching to /posts triggers a search on that screen as well. If there isn't a matching post, the "No posts match your search for ..." message appears

To reproduce:
1. Visit either /pages or /design and enter a search term
2. Without clearing the term, click on Blog Posts from the menu

The search term remains entered, and depending on the results, either matching posts or the "No posts match your search for ..." message displays

![Calypso Search](https://cldup.com/cVuAJjniZB.gif)

**Comment by lancewillett** [comment]
This looks similar to #453 (which was supposedly fixed two days ago).

**Comment by lancewillett** [comment]
Reading the change from 453 I think this is working as intended.

@chad1008 I actually can't reproduce this in wpcalypso. Clicking on Blog Posts resets the search for me in testing with Safari 9.0.1 on OS X 10.11.1 and a test blog.

**Comment by lancewillett** [comment]
Thanks Chad — will look into this more. :eyes:

**Comment by lancewillett** [comment]
This is working correctly in my testing, with wpcalypso and a test site. Clicking into /posts from /design or /pages resets the search query string as expected.
