### ISSUE TITLE
Login: Wrong title when redirected from 2FA to Login

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#14039]
Raised by @stephanethomas  in 13987

> when you access the Verification Code page with a 2FA account, if you click the Return link you are redirected back to the Login page. However the title is not updated (or said differently, it has the wrong title):

![](https://cloud.githubusercontent.com/assets/594356/26056576/43c071ba-3976-11e7-838e-1197d1c24d3c.png)

**Comment by drw158** [comment]
Not sure why the design review label. Seems like a good idea to fix this. 👍 from me.

**Comment by fabianapsimoes** [comment]
@drw158 it's the best way atm to coordinate between Amber and Cerulean things that can be fixed by the designers. I understand this can be confusing for other designers checking the label though. Suggestions welcome.

**Comment by stephanethomas** [comment]
Please consider https://github.com/Automattic/wp-calypso/issues/14430 when fixing this issue as they are related.

**Comment by scruffian** [comment]
We don't have a different title in the 2FA step, so we can close this.

**Comment by stephanethomas** [comment]
Well, we [do have a title for this page](https://github.com/Automattic/wp-calypso/blob/a0b758baa9b7af421eef110c943985892a1d0a8c/client/blocks/login/index.jsx#L146) but it is no longer displayed since https://github.com/Automattic/wp-calypso/pull/14539.

**Comment by fabianapsimoes** [comment]
Should we keep this issue open then so we remove that code?

**Comment by stephanethomas** [comment]
Yes, that was my idea when I reopened it. Either we fix the title, or we remove the code.
