### ISSUE TITLE
Editor: Contact Form Builder

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#1404]
### Contact Form Builder for Calypso's Editor

![wp-admin contact form](https://cloud.githubusercontent.com/assets/233601/11567272/ffeb4368-99c4-11e5-8971-6f1316cfcbcb.png)

The first iteration of the contact form builder was as a plugin for Cloudup's editor, implemented as a stand alone set of react components with a serialization/deserialization abstraction layer..

![cloudup](https://cloud.githubusercontent.com/assets/233601/11342905/4ea9bbae-91e8-11e5-9263-4b0487cf0695.png)

At first it was intended to be implemented, unmodified, on Calypso's editor.

![calypso](https://cloud.githubusercontent.com/assets/233601/11342943/7e4ef270-91e8-11e5-85a8-32f0c22b4adc.png)

The cloudup editor has a very contextual interface. All elements are interactive, from a simple link to the complex media gallery. Drag and drop play a very important role in the arrangement of elements inside the document and inside the elements themselves. Items can be dragged and dropped in between media elements. All edit operation are done in place.

The calypso editor has a more traditional interface. There are no drag and drop features. Elements are placed as the document flows and can be cut, copied and pasted (something not possible on the cloudup editor) and changes to those elements are managed outside the document on modal windows.

![calypso-url](https://cloud.githubusercontent.com/assets/233601/11342946/83f97f74-91e8-11e5-8177-abfd3e48018c.png)

### Brand new Implementation

- Extension of `wpcom-view` views with a `contact-form-view` component to manage form preview, edit and delete operations.
- Dialog component to host a contact form builder with standard Calypso form components.
- Serialization/Deserialization using the `shortcode` library instead of custom code.

**Comment by alisterscott** [comment]
I left a comment on #1885 that if you'd like me to raise issues raised on that PR as separate GH issues please let me know and I can do this so we can progress that PR 😀
