### ISSUE TITLE
Login: 2FA design cleanup

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#14041]
There are still some outstanding design questions from #13987

- <s>Should we use sentence case for the text, rather than headline case?</s>
- <s>Should the copy be "An Authenticator App" or "The Authenticator App"?</s>
- Should we make the lighter grey colour a global color?
- <s>Should we show the SMS entry screen even when we can't send another code via SMS?</s>

@danhauk, what do you think?

**Comment by michelleweber** [comment]
I'm assuming you're talking only about the text for the options at the bottom of the screens (code via mobile, wp.com app, etc), right? In that case:
- Use sentence case
- "An authenticator app" or "Your authenticator app"

(I think "Your authenticator app" sounds more natural.)

Let me know if there's anything else!

**Comment by scruffian** [comment]
> Should we show the SMS entry screen even when we can't send another code via SMS?

This is being handled in https://github.com/Automattic/wp-calypso/issues/14092

**Comment by drw158** [comment]
If this is the new variable, then no, I don't think we need a new variable:

```
.card.two-factor-authentication__form-action {
 	background: lighten( $gray, 34% );
```

`$gray-light` is 33%

**Comment by scruffian** [comment]
> $gray-light is 33%

@drw158 are you saying that we can use `$gray-light` in place of `lighten( $gray, 34% );`? We tried this in #13987 but @danhauk [noticed](https://github.com/Automattic/wp-calypso/pull/13987#issuecomment-301117395) that this meant that the background colour of the box matched the page's background,  so we actually need a different shade. We use `lighten( $gray, 34% );` in a few places already so I was wondering if it's worth making it part of the design patterns.

**Comment by danhauk** [comment]
@scruffian I think @drw158 makes a good point [here](https://github.com/Automattic/wp-calypso/pull/13987#issuecomment-301814944) regarding the grays. It's a super subtle difference and a 1% difference is not something most non high-end monitors can distinguish. While it looks better than using the same gray as the background, I wonder if we could update the design a bit to not rely on subtle changes. I would say lets avoid adding it as a global color variable.

**Comment by scruffian** [comment]
@danhauk good idea. Is there another color we can use?

**Comment by stephanethomas** [comment]
Pinging @danhauk for input :).

**Comment by danhauk** [comment]
I tried a couple different things with background colors, splitting the card, etc. The more I looked at it, the more I'm happy with using white for the background color on the `two-factor-actions` component. It keeps contrast up and reduces the muddiness of all the grays.

**Comment by fabianapsimoes** [comment]
@danhauk is there anything else pending here or can we close this issue?

**Comment by danhauk** [comment]
Nope this is good. Closing.
