### ISSUE TITLE
Domains: AT sites are missing ability to transfer domain to other user

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#14051]
The domain transfer functionality should normally have two options;

![transfer two options](http://cld.wthms.co/EOh1S+)

This is visible from: `https://wordpress.com/domains/manage/:site/transfer/:domain`

But for some reason on my test AT sites I only have the `Transfer to another register` option. I'm not aware of any reason we should have that limitation from being able to transfer to another user.

@umurkontaci do you recall why we might have this limitation for AT sites? I haven't dug into this, just opening the issue so we remember to look into it.

**Comment by umurkontaci** [comment]
Yeah, because the system was the user id of the AT site in wpcom, without any modification, so if you want to transfer the site to the second user in the site with ID == 2, it would attempt to transfer it to wpcom user id == 2. This is already terrible as it is but since the wpcom user id == 2 isn't actually a member, (most likely) it won't be accessible by them either, practically throwing the site into the sinkhole...

**Comment by klimeryk** [comment]
Related (duplicate?) issue: https://github.com/Automattic/wp-calypso/issues/11448

**Comment by rralian** [comment]
> Yeah, because the system was the user id of the AT site in wpcom, without any modification, so if you want to transfer the site to the second user in the site with ID == 2, it would attempt to transfer it to wpcom user id == 2. This is already terrible as it is but since the wpcom user id == 2 isn't actually a member, (most likely) it won't be accessible by them either, practically throwing the site into the sinkhole...

I see, so it sounds like we just need to make sure we transfer ownership using the wpcom user ID, right?

**Comment by designsimply** [comment]
Related: #12102 (also intentionally left out for domain-only purchases)

**Comment by kriskarkoski** [comment]
3335494-t

**Comment by rwaynick** [comment]
682709-zen

**Comment by kriskarkoski** [comment]
I just helped with an issue where a user registered a new domain on an AT site accidentally and could not transfer it. As a workaround, we can move the domain to a simple site to expose the transfer option, then put it back on the correct site once it's on the right account.

**Comment by retrofox** [comment]
Closing this one since it has been implemented today. :-D
