### ISSUE TITLE
Reader: Settings for followed Site Rec only appears after refresh

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14069]
Reported by @designsimply.

Steps to repro:
1. Go to https://wpcalypso.wordpress.com/following/manage.
2. Follow a site from Recommended Sites.
3. This site gets added to your Following list, but the Settings button only shows up after refreshing.

![screen-shot-2017-05-15-at-mon-may-15-3-24-41-pm](https://cloud.githubusercontent.com/assets/4924246/26084146/cc5d4166-398e-11e7-91a4-fc718fc482c4.png)

**Comment by bluefuton** [comment]
I think returning the new subscription from the API on successful follow could help here. I'll look into it.

**Comment by bluefuton** [comment]
I think this just needs to be using the `isFollowing` selector (same as the follow button) rather than looking at `site.is_following`/`feed.is_following`. I'll work up a PR.
