### ISSUE TITLE
Notifications/Editor: Liking a notification with unsaved changes shows "Are you sure?" browser prompt

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14071]
I'm not sure if this was introduced with the new notifications pane, I haven't noticed it before now.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Create some content and don't save
3. Open the notifications pane before auto-save and like a comment

#### What I expected

Comment to be liked

#### What happened instead

Browser warning about unsaved changes

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

![notifications](https://cloud.githubusercontent.com/assets/128826/26084646/f72baa30-3a20-11e7-8e41-b6d4dbdcbd18.gif)

#### Context / Source
#reallife #dogfooding

**Comment by roundhill** [comment]
cc @Automattic/lannister

**Comment by kwight** [comment]
I don't think this is notifications-specific; the same happens if you click the back arrow, My Sites, the Reader, the Profile button – anything that would change the URL I think.

**Comment by kwight** [comment]
Ignore that; you're right, clicking a Like shouldn't trigger this behaviour.

**Comment by kwight** [comment]
Will be fixed in Calypso by #14968 .
