### ISSUE TITLE
Purchases: Incorrect behavior when wrong site slug provided in the url

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#1407]
I haven't testes all pages, but it looks like we should handle sites on the controller side. Most likely we do it this way in Domain Management section. Those kind of errors can happen when user changes primary domain and then loads url saved in the browser history.

### Manage Purchase
Go to Manage Purchase page and change site slug in url. You are going to see this:
![screen shot 2015-12-09 at 08 19 42](https://cloud.githubusercontent.com/assets/699132/11679059/c75f9656-9e4d-11e5-814d-979e07034182.png)

### Cancel Purchase
Go to Cancel Purchase page and change site slug in url. You are going to see this:
![screen shot 2015-12-09 at 08 23 43](https://cloud.githubusercontent.com/assets/699132/11679095/2fe7ca54-9e4e-11e5-953a-855176755299.png)

and the following error on JS console:
> Uncaught TypeError: Cannot read property 'slug' of undefined

**Comment by stephanethomas** [comment]
https://github.com/Automattic/wp-calypso/issues/1870 is another use case to take into account.

**Comment by drewblaisdell** [comment]
This was fixed by #4555.
