### ISSUE TITLE
Reader: BACK button and visit site clickable areas can cause confusion on Mobile

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14078]
It looks like there's no clear differentiation between BACK and the site title area which visits the site so on numerous occasions on mobile I would inadevertently visit the site when trying to go BACK.

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage **in mobile narrow view**
2. Click on a followed site
3. Hover over BACK then move slightly towards the site title and click

#### What I expected

BACK to work separately to visit site

#### What happened instead

The visit site area is large and can cause clicks to visit the site when I am trying to click/tap BACK

#### Browser / OS version

Any mobile width - tested on Safari and iOS

#### Screenshot / Video

![back button area](https://cloud.githubusercontent.com/assets/128826/26089301/f6579ec4-3a3f-11e7-847e-508be41aaa0e.gif)

**Comment by jancavan** [comment]
@bluefuton I remember we worked on this before https://github.com/Automattic/wp-calypso/pull/9594 and it's tricky to fix. I think because of how the current HTML structure is.

**Comment by samouri** [comment]
I removed this from the milestone because its unrelated to the refresh.

That said, I'll look into fixing this now :)
