### ISSUE TITLE
Manage Following Refresh: show icons for all sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14083]
It would look nicer IMO if we showed icons for all sites, even if they are just a placeholder icon.

Previously:

<img width="758" alt="old design icons" src="https://cloud.githubusercontent.com/assets/128826/26090190/93296bbe-3a46-11e7-9e26-76b409afc609.png">

Current Refreshed Design

<img width="764" alt="new design icons" src="https://cloud.githubusercontent.com/assets/128826/26090198/a0d8a180-3a46-11e7-91bc-41d7dcc22a8b.png">

This should apply to all sites: WP.com, Jetpack, external sites with feeds

**Comment by bluefuton** [comment]
Or if we leave out the placeholder, having the indent consistent would be good I think.

**Comment by blowery** [comment]
> Or if we leave out the placeholder, having the indent consistent would be good I think.

I think that would be perfect.
