### ISSUE TITLE
Manage Following Refresh: allow reverse sort to show oldest followed sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14087]
It would be nice to have a reverse sort by follow date, since this would be useful to unfollow old sites that no longer exist or you aren't interested in any more as they were followed some time ago.

The current design only allows sorting by newest-oldest and alphabetical (A-Z)

**Comment by gibrown** [comment]
When we get to this, let's do this as a part of also sorting by what has/hasn't been updated recently.
