### ISSUE TITLE
Manage Following Refresh: site link no longer shows new window icon

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14080]
The site's link opens a in new window but no longer shows an icon to indicate.

**Previously**

<img width="763" alt="before" src="https://cloud.githubusercontent.com/assets/128826/26089536/ef7dd7f6-3a41-11e7-85ee-7e789a1cc7fa.png">

**With Refresh**

<img width="691" alt="after" src="https://cloud.githubusercontent.com/assets/128826/26089533/e8ba4454-3a41-11e7-8323-0abb5b1dce22.png">

Question: should we still show the icon? This is good to know for desktop app where the user is taken to their browser from the app.

**Comment by blowery** [comment]
Yeah, we should add it back.
