### ISSUE TITLE
Manage Following Refresh: Clicking "Settings" text in same place does not close settings

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14085]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage
2. Click the text "Settings" for an existing followed site
3. The settings are shown
4. Click the same place again

#### What I expected

Settings hidden

#### What happened instead

Nothing

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

![settings](https://cloud.githubusercontent.com/assets/128826/26090519/d8aaaffc-3a48-11e7-9fce-2e5234ec27fe.gif)

**Comment by samouri** [comment]
This one is a bit tricky.  The current `Popover` component assumes that the element you want to center around is also the exact same as the one you want for determining if you clicked outside or not.  In our case we want to center around the cog but use the word + cog for showing/hiding.

**Comment by samouri** [comment]
fix: https://github.com/Automattic/wp-calypso/pull/14127
