### ISSUE TITLE
Me: Trying to save duplicate email address returns generic error message

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#1408]
Under `/me/account`, when you try to update your email address to one that is already associated with a WordPress.com account, you get the following error:

![screen shot 2015-12-09 at 1 08 46 pm](https://cloud.githubusercontent.com/assets/10125810/11680411/16b65034-9e7e-11e5-8962-5df8866ecbc4.png)
_There was a problem saving your changes._

This error message should ideally say something like this:
_There is already a WordPress.com account associated with that email address. Please use a different one._

**Steps to Reproduce**
1) Login to WordPress.com and go to `/me/account`
2) Change your `Email Address` to one that is already associated with another WordPress.com account
3) Hit `Save Account Settings`

cc @kriskarkoski

**Comment by rachelmcr** [comment]
This issue is tracked here: https://github.com/Automattic/wp-calypso/issues/386

Closing this duplicate.
