### ISSUE TITLE
Login: improve error messages / form validation copy

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#14090]
Some new copy for login error messages, based on this list:

https://github.com/Automattic/wp-calypso/blob/2f14fe6abd2bd48aee86ee24ee7d7789ccc3ffaf/client/state/login/actions.js#L25

----
    
![ranimac3 screenshot 2017-05-16 at 09 57 38](https://cloud.githubusercontent.com/assets/426518/26095029/e868f454-3a24-11e7-882c-86a526e5562a.png)

Currently: "The username field is empty."

Change: "Enter your username or email address."

----

![ranimac3 screenshot 2017-05-16 at 09 58 40](https://cloud.githubusercontent.com/assets/426518/26095042/fb4125b0-3a24-11e7-8b49-700f9b37cbb6.png)

Currently: "The password field is empty."

Change: "Enter your password."

----

![ranimac3 screenshot 2017-05-16 at 10 28 31](https://cloud.githubusercontent.com/assets/426518/26095105/274c68ae-3a25-11e7-8525-4034ffea3d1a.png)

Currently: "Invalid password."

Change: "That's not the right password."

----

![ranimac3 screenshot 2017-05-16 at 10 33 46](https://cloud.githubusercontent.com/assets/426518/26095123/37eb995a-3a25-11e7-9439-9e4da0b73347.png)

Currently: "Invalid verification code."

Change: "That's not the right code. Make sure you enter the code before it expires."

Does this message apply only to the authenticator app code? If it also applies to recovery/backup codes, the second part ("Make sure...") should be removed.

----

There are a few messages that I'm not quite sure about:

```
	invalid_email: translate( 'Invalid email address.' ),
	invalid_username: translate( 'Invalid username' ),
	unknown: translate( 'Invalid username or password.' ),
	account_unactivated: translate( 'This account has not been activated. Please check your email for an activation link.' ),
```

How do we tell the difference between invalid username and invalid email address? Do we need dedicated errors for that? Could we reuse the "empty field" notices? 

Where do we show the combined "invalid username or password" message?

Where do we show the `unactivated` notice? AFAIK we don't require users to activate their account to log in?

**Comment by scruffian** [comment]
`invalid_email` shows when you enter an email address that we don't have in the system

`invalid_username` shows when you enter a username that we don't have in the system

The combined `'Invalid username or password.` seems to be used in the old login screen but I can't get it in the new one. I suppose this is also fall back in case things go wrong.

`unactivated` shows if you create an account through WPCC and then don't activate it. Interestingly  this notice is a global one, which we should probably also change.

**Comment by drw158** [comment]
"That's not the right password." and "That's not the right code" don't seem reassuring or positive to me. Maybe it's best to be neutral here, I'm not sure. I flagged this for copy review.

" Make sure you enter the code before it expires." seems unnecessary. I would lean towards being concise in these messages.

**Comment by michelleweber** [comment]
In the mobile apps, we've been going a bit more conversations with the messaging -- like, "Hmm, that password doesn't seem to be correct / doesn't seem to match" etc. I'm thinking that we should adopt a consistent tone for this messaging across desktop and the app, no? LMK -- I'm happy to either tweak what y'all have here a bit, or offer new options in line with what we've done for mobile.

**Comment by scruffian** [comment]
@michelleweber, I think keeping consistency with mobile would be great. What new options do you suggest?

**Comment by michelleweber** [comment]
For the screenshots above, here are a few messages in line with that we're doing on mobile:

1. Please enter a username or email address.
2. Please be sure to enter your password.
3. Oops, looks like that's not the right password. Please try again!
4. Hmm, that's not a valid verification code. Please double-check your app and try again.

For the other messages listed:
invalid_email: Oops, looks like that's not the right address. Please try again!

invalid_username: We don't seem to have an account with that name. Double-check the spelling and try again!

unknown: Hmm, we can't find a WordPress.com account with this username and password combo. Please double check your information and try again.

account_unactivated: This account hasn't been activated yet -- check your email for a message from WordPress.com and click the activation link. You'll be able to log in after that.

On the screen at https://wpcalypso.wordpress.com/log-in
- I'd suggest "Keep me logged in" in place of "Stay logged in"

**Comment by fabianapsimoes** [comment]
Looks like this has been fixed already. Closing, but feel free to reopen if I missed any items.
