### ISSUE TITLE
com.pe and com.br domains appears as taken even if they aren´t [in the Domains add screen]

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#14103]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add
2. Choose one of your sites
3. In the domain search field, write any arbitrary domain name finishing by com.pe or com.br (Don't use special characters like ñ)

#### What I expected
1.If the domain is not taken, the interface should allow to get it.

#### What happened instead
1. This message is displayed:
"jkfdsjkfsjkjfsdkjfa.com.pe is taken.
If you purchased jkfdsjkfsjkjfsdkjfa.com.pe elsewhere, you can map it for €13.00."

#### Browser / OS version
This bug is not browser dependent - chrome IOS

#### Screenshot / Video

![domain search aprehendizajes com wordpress com 2017-05-16 15-04-12](https://cloud.githubusercontent.com/assets/6404071/26113400/bc5a37c0-3a5a-11e7-8656-ecdfbe9bfc18.png)
![domain search aprehendizajes com wordpress com 2017-05-16 14-59-29](https://cloud.githubusercontent.com/assets/6404071/26113407/bfa7b9f2-3a5a-11e7-8d5a-6f12b4a6609e.png)
![domain search acgapoyoempresarial wordpress com wordpress com 2017-05-16 07-33-30](https://cloud.githubusercontent.com/assets/6404071/26113413/c1d7c712-3a5a-11e7-97f6-a6a21e4aa66b.png)

#### Context / Source
This error is not shown when using special characters like 'Ñ' in the domain name.

We'd also love to know how you found the bug:  #user-report (chat 381894-hc con gruago.com.pe)

**Comment by designsimply** [comment]
Tested and found that the same problem with any TLD not listed at https://en.support.wordpress.com/domains/#available-domains

![screen shot 2017-05-16 at tue may 16 9 26 49 am](https://cloud.githubusercontent.com/assets/1119271/26114288/164f05d0-3a1a-11e7-8510-dc6e094c48d9.png)
<sup>Seen at https://wordpress.com/domains/add/design5279.wordpress.com using Firefox 53.0.2 on Mac OS X 10.12.4 logged in as design5279 unproxied.</sup>

What happened:

* A message saying "thisisatestofaddingadomainwithadifferenttld.art is taken."

What I expected: 

* A message saying "thisisatestofaddingadomainwithadifferenttld.art is unavailable." or ".art domains are not available for sale at WordPress.com."

**Comment by klimeryk** [comment]
I think we have to change our approach here - right now we have a short list of "unsupported TLDs" on the backend, which we know we can't check the availability of (see https://github.com/Automattic/wp-calypso/issues/11051). Obviously, that list is not complete and with gTLDs being added all the time (`.art` being a recent addition), it will be hard to keep it up to date (and to account for stuff like second level TLDs, ccTLDs...).
Instead, we should whitelist the TLDs we do know we can check availability for and show this message for other (we already do for those unsupported TLDs):

<img width="750" alt="screen shot 2017-05-24 at 03 37 58" src="https://cloud.githubusercontent.com/assets/3392497/26383323/66b535da-4032-11e7-8043-fd32f027cabd.png">

@aidvu, does that sound good to you? I think you had proposed the same thing in a Slack conversation we've had about this :)

**Comment by aidvu** [comment]
Sounds good. We can do something similar to https://github.com/Automattic/wp-calypso/blob/cabaf131c7bdfd58bcf0e9798f3439e06e484b34/client/lib/domains/registration/availability-messages.js#L37.

We should probably stop doing availability checks for the ones we don't have in our offering.

**Comment by klimeryk** [comment]
This should be fixed now - patched on the backend `D5787-code`.

The way it's working now is that we're only checking the availability of the TLDs we offer (.com, .net., .blog, etc.). For others, we show this type of message:

<img width="739" alt="screen shot 2017-06-05 at 16 59 00" src="https://cloud.githubusercontent.com/assets/3392497/26789392/74f50e8a-4a10-11e7-853b-1a8dbc08b0bc.png">

**Comment by rantoncuadrado** [comment]
:) I'm glad to contribute!
