### ISSUE TITLE
Contact form : Option for "Checkbox with multiple items" not available

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#14117]
The field type - "Checkbox with multiple items" is unavailable in the contact form builder within calypso. It is available within Wp-admin. 

#### Steps to reproduce
1. Open any post or page in editor
2. Add a contact form
3. Add a new field by clicking the option to do that.
4. We find the option "Checkbox with multiple items" missing 

#### What I expected
I was expecting to find the option to add field type - "Checkbox with multiple items" . This option is available when we try to add the contact form in Wp-admin

#### What happened instead
The option to add "checkbox with multiple items" does not show up. If i add this using WP-admin and come back to calypso to edit the form, the field type shows blank. 

#### Browser / OS version
Tested on chrome-based Vivaldi Browser. I had a conversation with a user who faced this on another browser. 

#### Screenshot / Video

Option visible in Wp-admin
![image](https://cloud.githubusercontent.com/assets/4162931/26119876/7f52bf78-3a8c-11e7-9dac-0b605cde6ba9.png)

Option not visible in Calypso
![image](https://cloud.githubusercontent.com/assets/4162931/26119947/b846385a-3a8c-11e7-97e2-718c3161e2c3.png)

#user-report #manual-testing

**Comment by cecilerainon** [comment]
I'd like to report another user who had trouble with their form, so I had to help them add an extra checkbox through WP Admin. I'm not sure if it's a bug or we deliberately chose to switch to a single checkbox on Calypso, but I think it'd be a nice enhancement. :)

Here's the chat in question for context: [#269034-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=269034)

**Comment by samiff** [comment]
This really can be confusing given that the Calypso preview of the form just breaks:

![screen shot 2018-11-08 at 7 01 47 pm](https://user-images.githubusercontent.com/15803018/48238953-3c368c80-e38a-11e8-827d-2aad0f12e697.png)

Also confusing is the fact that you aren't required to add field labels when editing a form in `wp-admin`, but can't update the form via Calypso with blank field labels.

Context: 1553365-zen

**Comment by nagpai** [comment]
Closing this issue, since we now have contact form block in Gutenberg that takes care of this issue very well.
