### ISSUE TITLE
Comments: quick actions

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#14119]
User should be able to do the most common actions straight from the list.

![screen shot 2017-05-16 at 12 55 32 pm](https://cloud.githubusercontent.com/assets/618551/26120633/04b07be8-3a37-11e7-93ff-42d5d1e89771.png)

**Comment by drw158** [comment]
Higher res:
![artboard copy 25](https://user-images.githubusercontent.com/618551/28530853-b56c8950-705a-11e7-8a1e-10a370d384b4.png)

**Comment by gwwar** [comment]
Did we want hover states? These won't be available for devices that can't hover
