### ISSUE TITLE
Comments: comment sorting

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#14118]
The user should be able to chronologically sort the list of comments to accommodate their workflow.

`newest/oldest`

![screen shot 2017-05-16 at 12 52 58 pm](https://cloud.githubusercontent.com/assets/618551/26120506/9eb42e66-3a36-11e7-81da-2b44ca7b91bd.png)

**Comment by gwwar** [comment]
Doing a quick audit in wp-admin we can sort by the following:

* Author ( I think this works better as a filter)
* Comment Date - ASC/DSC
* In Response To? Not sure what this does. Post age?

So I think for m2, as a first pass adding an Newest/Oldest toggle just for comment date makes sense.

**Comment by gwwar** [comment]
cc @vindl if we'd like this in for m2, this would likely affect the comments-tree endpoint

We might be able to skip it if we choose to create a memo'd selector that respects sorting here. The endpoint limits were pretty large.

**Comment by gwwar** [comment]
This should be doable as a selector for now, but let us know if folks run into trouble.
