### ISSUE TITLE
Comments: link icons in list

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#14120]
User should be able to determine if the comment contains a link directly from the list.

![screen shot 2017-05-16 at 12 56 54 pm](https://cloud.githubusercontent.com/assets/618551/26120730/55645c12-3a37-11e7-91dc-7b05850019fb.png)

**Comment by gwwar** [comment]
Let's verify that we have enough information in the comments endpoint.

**Comment by gwwar** [comment]
Bumping up priority on this one from feedback in the last interview. Heads up @Copons

**Comment by Copons** [comment]
IIRC for this we should have a deeper look into how Notifications handle it, because creating a new endpoint to find out if our user ID is the author of any comments with a given parent ID feels a bit overkill.

**Comment by gwwar** [comment]
> we should have a deeper look into how Notifications handle it

That sounds good to me. I'll update the summary here.

**Comment by kwight** [comment]
This feels like one (or two) of those things that contribute to the confusing, messy look of comments – I can kind of see the "have I replied?" icon, but have we had specific need or feedback for the "this comment contains a link" icon?

**Comment by vindl** [comment]
@kwight we did have it in p3fqKv-63c-p2. Judging by that `this comment contains a link` seems to be more useful than `have I replied` icon. Also the feedback above was the reason for [raising the priority](https://github.com/Automattic/wp-calypso/issues/14120#issuecomment-339137024) of this issue.

**Comment by gwwar** [comment]
@vindl you beat me. You're right on the mark.

**Comment by gwwar** [comment]
If generating the `have I replied` is too complex, we can ignore it for M3 as well.

**Comment by vindl** [comment]
> If generating the have I replied is too complex, we can ignore it for M3 as well.

@gwwar It's not complex but we'll need to do some endpoint work in order to show it. I checked in notifications client and the corresponding reply comment data is generated on backend and then used in the client, for example here: https://github.com/Automattic/notifications-panel/blob/ce36f98ead01c0d3b71f9932d2777862e708c1a3/src/templates/body.jsx#L54

If you and @megsfulton agree, I'll create a separate issue for this in M4 and use this one to track just the link indicator.

**Comment by gwwar** [comment]
> I'll create a separate issue for this in M4 and use this one to track just the link indicator.

Sounds like a good plan to me! I'll also spin up a new p2 post for m4 endpoint work soon.
