### ISSUE TITLE
Business Plugins: Space missing between string and link

### ISSUE THREAD

**Issue by sirjonathan** [Automattic/wp-calypso#1414]
Noticed a missing space between an upgrade prompt and the link to learn more. See here: https://cloudup.com/ch4NTjR6iOe

I went to see if I could fix it here: https://github.com/Automattic/wp-calypso/blob/a7478174b0441760c332fcb4b8c454f5b8d73dfc/client/components/plans/plan-nudge/index.jsx

And in doing so realized that the fix wasn't obvious to me. Adding space to either string doesn't seem right as it doesn't take other translations into account. In my mind, that leaves:

* Add a space between the string and the link element
* Add space using "CSS"

Given the new environment we're in here I'm not sure which approach is right or if either is right. Happy to submit a PR with a little guidance.

**Comment by lamosty** [comment]
@sirjonathan I would go with the "add a space manually" approach because when adding a space with CSS, it might break when zooming or on very small displays.

**Comment by fabianapsimoes** [comment]
cc @drewblaisdell
