### ISSUE TITLE
Login: inconsistent terminology for recovery codes

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#14158]
Steps to reproduce:

- use `/login` to log in to an account that has 2FA enabled
- enter your username and password and click Log In
- in the next screen, click "Code via text message". you'll see this screen:

![screenshot-wpcalypso wordpress com-2017-05-17-11-39-53](https://cloud.githubusercontent.com/assets/1248436/26150329/42fb870e-3afe-11e7-956d-b0e5bcd84e75.png)

In this case, "code via text message" and "verification code" both refer to recovery codes. Recovery codes are sent to users who either have 2FA enabled or have entered their phone under Me > Security > Account Recovery > Recovery SMS Number.

Since we use the term "recovery" in the Security Settings, shouldn't we be consistent with that terminology across the login flow? That would mean:

- "Code via text message" >> "Recovery code via text message"
- "verification code" >> "recovery code".

See also: p58i-5Vx-p2

cc @ranh

**Comment by fabianapsimoes** [comment]
I realized that we also call it verification code for 2FA via SMS.

**Comment by ranh** [comment]
I'm not sure that having all this different terminology is helpful to users. In these examples, I think we can just say "code" without any other qualifications. 

Is it intentional that the green notice replicates the same copy shown above the code?

**Comment by fabianapsimoes** [comment]
We removed the recovery code from the 2FA flow, see https://github.com/Automattic/wp-calypso/issues/1416. Closing this issue.
