### ISSUE TITLE
Login: Enable SSR for Login page when `redirect_to` param provided

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14159]
SSR works when users access https://calypso.live/log-in but not for https://calypso.live/log-in?redirect_to=https%3A%2F%2Fcalypso.live%2Fdevdocs%2Fwelcome.

It's a know limitation, we need to fix it. There are two places where the existing logic needs to get updated:

https://github.com/Automattic/wp-calypso/pull/13339/files#diff-cdf8be48e336c794267be91d81a3a610L114
https://github.com/Automattic/wp-calypso/pull/13339/files#diff-b2d6784517d1151d7e75f0287d0c6478R125

According to @seear this limitation was initially introduced to avoid caching issues with Themes pages. We can relax this for pages other than Themes section.

**Comment by seear** [comment]
Also, in the render middleware, here:
https://github.com/Automattic/wp-calypso/blob/033f763d739477b305eca7b224d3573c6f64d49d/server/render/index.js#L84

and here:
https://github.com/Automattic/wp-calypso/blob/033f763d739477b305eca7b224d3573c6f64d49d/server/render/index.js#L107

I had in mind maybe to add a field to context, like `doNotSSR` that an individual route could set, which could replace the checks above.

I'm thinking that the check in [`pages/index.js`](https://github.com/Automattic/wp-calypso/pull/13339/files#diff-b2d6784517d1151d7e75f0287d0c6478R125) can simply be removed without any ill-effects.

**Comment by fabianapsimoes** [comment]
@pento @stephanethomas any idea how much work this would require, and what are the main user facing side effects? This will help me prioritize this issue.

**Comment by seear** [comment]
@fabianapsimoes I've put a PR together for this, #16133. It could do with some testing from the login angle to make sure it meets your needs.

**Comment by fabianapsimoes** [comment]
Added it to our board, so the team takes a look at it. Thank you! :cake:
