### ISSUE TITLE
Masterbar: remove labels on mobile

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#1416]
We have discussed moving towards removing the labels from the mobile version of the masterbar. They are bit hard to work with when it comes to i18n, makes the whole top area seem busier, and the prevailing notion is that we don't need text to explain them.

If we consider the masterbar in desktop, only My Sites and Reader have a label, so when it comes to Me and Notifications, we'd be already in the same place.

![image](https://cloud.githubusercontent.com/assets/548849/10693608/9e1c9858-7999-11e5-911a-c38ddcdae779.png)

A good example from the Android app:

![image](https://cloud.githubusercontent.com/assets/548849/10693569/66ec240c-7999-11e5-9793-134dc0ff6223.png)

And @shaunandrews made this mockup for Calypso:

![screen shot 2015-10-23 at 10 37 16 am](https://cloud.githubusercontent.com/assets/191598/10695526/11f4ed3e-7972-11e5-97f9-ab67871d5442.png)

**Comment by folletto** [comment]
Related: #631.

**Comment by lancewillett** [comment]
This is complete in Dec 2015.

<img width="578" alt="screen shot 2016-04-27 at 9 32 13 am" src="https://cloud.githubusercontent.com/assets/66797/14859886/fca5933a-0c5a-11e6-877c-3e924f32bddf.png">
