### ISSUE TITLE
Multiple sites, but only one site available in My Sites

### ISSUE THREAD

**Issue by joendotcom** [Automattic/wp-calypso#14166]
Discovered via 3150499-t while checking an unrelated issue. See also Slack convo: p1495024028297483-slack-jpop-support

#### Steps to reproduce
No steps yet as this is an observed issue whose cause is not yet clear.

#### What I expected
To be able to change site in My Sites

#### What happened instead
Despite "My Sites" plural name, only one site available, a dotcom site, but with a Jetpack plan?

#### Browser / OS version
Tested in latest Chrome and Safari on macOS Sierra

##### Notice it says My SiteS, yet no site selector. Offers free domain cred as for dotcom, but with Jetpack logo
<img width="270" alt="before_dotcom_site_only_notice_domain_cred" src="https://cloud.githubusercontent.com/assets/8905369/26154929/bb958d8c-3b11-11e7-986f-ac801e4ec2ee.png">

##### After fiddling with the changes here, something goes unstuck
<img width="1400" alt="status_of_hidden_sites" src="https://cloud.githubusercontent.com/assets/8905369/26154936/c7f7f632-3b11-11e7-8627-26d1a41ef9cd.png">

##### Now site selector arrow shows correctly and Jetpack plan shows up (hidden before)
<img width="271" alt="after_multiplesites_jetpack_site_shows" src="https://cloud.githubusercontent.com/assets/8905369/26154934/bfecae88-3b11-11e7-939e-8b5ac3af3a7f.png">

#### Context / Source

#manual-testing

**Comment by jeherve** [comment]
Possibly related: #6779

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

This looks like a stale issue with no solid steps to reproduce.

I am proposing to close this issue with an appropriate label denoting reason for closure.
