### ISSUE TITLE
Notice: Strange line breaks in text on wide displays

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#14164]
#### Steps to reproduce
1. Use a wide display (1600px is plenty to see the strange layout)
2. Go to http://calypso.localhost:3000/media/:site for a Jetpack site on the free plan
3. Try to upload any video file
4. You will see an error with a strange line break:
   > 1 file could not be uploaded because your site does not support video files. Upgrade to a premium plan
   > for video support.

[This rule](https://github.com/Automattic/wp-calypso/blob/master/client/components/notice/style.scss#L82-L83) is the culprit. If notices fill the container, does it make sense to constrain their text contents?

```css
.notice__text {
	max-width: 680px;
	/* ... */
}
```

#### What I expected

I expected to see this error in one line.

#### What happened instead

There is a strange line break inside the notice.

#### Browser / OS version

Chrome >60 / macOS

#### Screenshot / Video

![strange-break](https://cloud.githubusercontent.com/assets/841763/26154185/ce5ace30-3b0e-11e7-8305-745abd26f6ef.png)

**Comment by keoshi** [comment]
All notices have been updated recently and even though I'm still seeing the `max-width` rule, the notice style is fine and the text is even stretching past 680px because the `span` is defaulting to `display: inline`.

![image](https://user-images.githubusercontent.com/390760/36796814-63952e3e-1c9e-11e8-9bf9-bf0d2fe11278.png)

I'd say it's safe to close this.

**Comment by sirreal** [comment]
> I'd say it's safe to remove that line, since it's not affecting anything.

👍 It's not affecting anything at all since the notice element change. The element is now a `span` and `max-width` doesn't apply.

**Comment by sirreal** [comment]
The issue is no longer present, #22916 removes the offending and now redundant rule.
