### ISSUE TITLE
Reader Manage Following: touch targets on follow and email settings icons are too small on mobile

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#14168]
As reported by @raoulwegat.

> Follow/Unfollow + Setting are too close together and too small. Here’s my thumb (touching the screen) alongside the icons. As touch targets go, the icons are way too small.

![img_1414](https://cloud.githubusercontent.com/assets/17325/26156370/6061f716-3b16-11e7-8b77-c48008bf47aa.jpg)

**Comment by bluefuton** [comment]
Perhaps we could move '⚙️Settings' underneath the feed URL on mobile @jancavan?

**Comment by bluefuton** [comment]
Or just move the Settings cog down a little bit, and make both icons slightly bigger?

**Comment by bluefuton** [comment]
Here's a little experiment with 24px gridicons, and the current sizes underneath:

<img width="394" alt="screen shot 2017-05-22 at 15 28 19" src="https://cloud.githubusercontent.com/assets/17325/26311102/5f4ad564-3f03-11e7-8d67-031559ce174a.png">

**Comment by jancavan** [comment]
I thought of this too @bluefuton and this might be the easiest solution, at least for now. Although it doesn't really feel/look right tbh. Let me think about it more.
