### ISSUE TITLE
Login: input persists in field when switching methods

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#14160]
Steps to reproduce: 

- visit `/login` and enter username and password for an account that has 2FA via authenticator app enabled.
- click Log In, and you'll be redirected to `/login/sms`
- enter random input in the text field there
- click An Authenticator application and you'll be redirected to `/login/authenticator`
- notice that whatever you entered in the text field remains there.

You can switch as much as you want between `/sms` and `/authenticator` and the input will remain there. Is that the desired behavior?

cc @danhauk @breezyskies

**Comment by danhauk** [comment]
Given that the 2fa codes are different with each case, and you'll get a new one each time you click sms, I'd say this is not the desired behavior. The input should be cleared each time you switch methods.
