### ISSUE TITLE
Login: Make it possible to login as a different user in Calypso

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14163]
At the moment native Calypso Login page is enabled only in development envs. Most of the links got updated to use this new page when navigating inside Calypso. We couldn't change all url because we decided to redirect user from Login page when user is already logged in. However there are some flows that allow user to log in as another user like Jetpack connect flow or Accept invite flow. To make it possible to migrate all existing Calypso references we would need to provide special switch in the url which would omit aforementioned redirect and allow user to provide different login credentials.

**Comment by fabianapsimoes** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/15041
