### ISSUE TITLE
Login: Further questions about usage of notices for errors

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#14173]
Here are some questions that remained unanswered from #14094 (https://github.com/Automattic/wp-calypso/pull/14094#issuecomment-302097286):

- <s>Should we use the same kind of notice when logging users in via push notification? That is, if we decide to continue having that notice. See #14155.</s>

- <s>Should we display the notice that confirms a code has been sent when a user has 2FA via SMS enabled?</s> https://github.com/Automattic/wp-calypso/pull/16233

- <s>In the case of an account that has not yet been activated, can we clear the notice once the user clears or updates the username field?</s>  #16176

- <s>In general, is it possible to dismiss the notice after some time? I mean, if I have 2FA via the auth app enabled, then click "A code via text message" and then click "an Authenticator app" the sent message notice is still being displayed even though it's no longer relevant. Same if I clicked the Return link.</s>

- <s>Seems the invalid password error has precedence over the non-activated one. Is there a way to change that? No need to get users obsessing over getting the password right if they can't log in anyway because the account is inactive.</s> wontfix

cc @danhauk

**Comment by scruffian** [comment]
> Should we display the notice that confirms a code has been sent when a user has 2FA via SMS enabled?

Yes!

> In the case of an account that has not yet been activated, can we clear the notice once the user clears or updates the username field?

Yes!

> In general, is it possible to dismiss the notice after some time? I mean, if I have 2FA via the auth app enabled, then click "A code via text message" and then click "an Authenticator app" the sent message notice is still being displayed even though it's no longer relevant. Same if I clicked the Return link.

We should clear it when the screen changes

**Comment by scruffian** [comment]
> Seems the invalid password error has precedence over the non-activated one. Is there a way to change that? No need to get users obsessing over getting the password right if they can't log in anyway because the account is inactive.

This would be a nice change, but it would be something to do on the server. Not sure how big a change that would be.

**Comment by fabianapsimoes** [comment]
> Should we use the same kind of notice when logging users in via push notification? That is, if we decide to continue having that notice. See #14155.

This notice is now gone.

**Comment by designsimply** [comment]
<blockquote><blockquote>Should we display the notice that confirms a code has been sent when a user has 2FA via SMS enabled?</blockquote>
Yes!</blockquote>

Screenshot for reference:

![screen-shot-2017-06-05-at-mon-jun-5-5-14-37-pm](https://user-images.githubusercontent.com/1119271/27107297-943dd7fa-5054-11e7-8d6e-900d647d6579.png)

(internal ref: p6qnuF-4TV-p2#comment-6048)

**Comment by scruffian** [comment]
> Seems the invalid password error has precedence over the non-activated one. Is there a way to change that? No need to get users obsessing over getting the password right if they can't log in anyway because the account is inactive.

This is possible to change, but will involve a lot of server side changes. I don't believe its worth our time investigating, since most users are automatically activated now anyway.

**Comment by scruffian** [comment]
All these issues are closed now.
