### ISSUE TITLE
Login: Scroll to top

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#14182]
When navigating around screens in /login the page should scroll to top, so that I am given context for the page.

Steps to reproduce:
1. Go to /login
2. Log in to a 2FA account
3. Scroll down
4. Select a different 2FA option
5. You will not be scrolled back up to the top of the page

**Comment by fabianapsimoes** [comment]
I feel like we have the "scroll to the top" issue in every project we work on. Is this maybe something we should fix at a whole system level instead of just for this (again)?

**Comment by stephanethomas** [comment]
We already have [some duplication](https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=scrolltotop&type=) when it comes to scrolling the window to the top in our current code base. There is the [`scroll-to` lib](https://github.com/Automattic/wp-calypso/tree/master/client/lib/scroll-to) that we can use to mitigate this, as well as the [`scroll-into-viewport` lib](https://github.com/Automattic/wp-calypso/tree/master/client/lib/scroll-into-viewport) which is for advanced use (it allows to scroll an element into the viewport if it's not already inside it).

In Delphin we created [a middleware](https://github.com/Automattic/delphin/blob/master/client/scroll-to-top-middleware/index.js) that would scroll the viewport to the top on each url change. I'm not convinced we can apply this behavior to Calypso: for example the `Reader` page uses infinite scrolling. We could however introduce an HOC that will scroll to the top when a component is mounted, and uses it whenever needed.

Pinging @mtias that may have some valuable feedback about this.

**Comment by gziolo** [comment]
HOC seems to be the best pick here.

**Comment by scruffian** [comment]
> I feel like we have the "scroll to the top" issue in every project we work on. Is this maybe something we should fix at a whole system level instead of just for this (again)?

This was suggested a while back, but there are some cases (like the reader) when we don't want this behaviour.
