### ISSUE TITLE
Reader Manage Following: in subscription list, follow button wraps in Firefox 49.0

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#14190]
<img width="777" alt="screen shot 2017-05-17 at 20 46 59" src="https://cloud.githubusercontent.com/assets/17325/26170678/8df8e618-3b42-11e7-9dd7-d0ffb8a837fb.png">
<img width="769" alt="screen shot 2017-05-17 at 20 47 25" src="https://cloud.githubusercontent.com/assets/17325/26170679/8e1e19ec-3b42-11e7-8d0a-17b47ad4b033.png">

**Comment by jancavan** [comment]
I'm unable to repro this @bluefuton. I'm on `FF 53.0.2`. What version is this?

**Comment by bluefuton** [comment]
@jancavan I'm on v49 (and currently trying to update itself):

<img width="753" alt="screen shot 2017-05-18 at 09 41 24" src="https://cloud.githubusercontent.com/assets/17325/26191460/383bab18-3bae-11e7-929a-b27ac5b934b6.png">

**Comment by blowery** [comment]
Looks good here too. @bluefuton did firefox ever update for you?

**Comment by blowery** [comment]
bumping this to the backlog

**Comment by bluefuton** [comment]
Can confirm it's fixed in Firefox 53.0 👍 Will update the issue title.

**Comment by bluefuton** [comment]
Chalking this up as a isolated Firefox bug in that particular version. Works well in FF58.
