### ISSUE TITLE
Reader: "Daring Fireball" returns multiple results of the same site

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14195]
https://wpcalypso.wordpress.com/following/manage?q=daring%20fireball

![screenshot 2017-05-17 13 45 19](https://cloud.githubusercontent.com/assets/4924246/26175299/130c1690-3b07-11e7-9bcf-d320a224529b.png)

Needs to be merged @blowery?

**Comment by blowery** [comment]
Yup, thanks! I thought I already fixed this one...

**Comment by blowery** [comment]
Fixed!
