### ISSUE TITLE
WooCommerce: Add Store Dashboard UX for "Momma" Mode

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14205]
See #13466 for design (note that both the "setup mode" design and the "ongoing maintenance mode / after setup" design are in that issue

Includes prompts for "after the first order arrives" store tasks, i.e.:

"TODO" Tasks
- the number of new orders and revenue and prompt to process the orders
- the number of new reviews and prompt to moderate them
- inventory alert (out of stock products)

"REPORTS" tasks
- reports last 7 days (or other time period) sales statistics
- top selling products
- top referrers

"OPPORTUNITY" Tasks
- highlighted opportunities (e.g. traffic spikes, search holes, exit pages, poor converters, abandoned carts, overall traffic)

"MISC" Tasks
Additionally, the following subviews are present and can leverage "fledgling" assets
- share your store (just like on fledgling, with slightly different copy)
- learn up (like on fledgling, but half-width if extensions task is also present)
- extensions (again, like on fledgling, but half-width if learn-up task is also present)
etc

See also #13612 for "Egg" and #13613 for "Fledgling"

**Comment by allendav** [comment]
Momma mocks:

![momma](https://cloud.githubusercontent.com/assets/1595739/26182222/8d8d4ee2-3b2b-11e7-9151-aea2ad1c6431.png)

With "manage" view open:
![manage momma](https://cloud.githubusercontent.com/assets/1595739/26182229/99e8739c-3b2b-11e7-996f-4655a7431cda.png)

**Comment by allendav** [comment]
@jameskoster @kellychoffman I'm starting to build this out now and I have a few questions:

1. I assume *store owner* is supposed to be filled in with their First and Last Name?

2. TODO widgets
2.1 All TODO "widgets" are active by default, right?
2.2 If they turn off just the "Orders requiring processing" widget, the other two TODO widgets remain half-width, right?
2.3 If they turn off the "Reviews" widget - should the "Inventory" widget go full width?
2.4 If they turn off the "Low inventory" widget - should the "Reviews" widget go full width?
2.5 If they narrow their screen, the todo widgets should stack vertically, right?

3. Report widgets
3.1 Basically same questions as above, plus:
3.2 What does the "Orders" drop down do on "Top Selling Products"?
3.3 What does the "Revenue" drop down do on "Top referrers"

4. Opportunity widgets
4.1 If there are fewer than all 6 opportunity widgets selected, how should they be laid out? (e.g. if 5 are selected, 4, 3, 2 or just 1)

5. Misc widgets
5.1 Similar layout questions - if Recommended Reading is off, Extensions goes full width, right?

6. If everything gets turned off - what gets displayed? LOL

See also #13613 for related questions about components shared with the fledgling view

**Comment by jameskoster** [comment]
> I assume store owner is supposed to be filled in with their First and Last Name?
> 2.1 All TODO "widgets" are active by default, right?
> 2.2 If they turn off just the "Orders requiring processing" widget, the other two TODO widgets remain half-width, right?
> 2.5 If they narrow their screen, the todo widgets should stack vertically, right?
> 5.1 Similar layout questions - if Recommended Reading is off, Extensions goes full width, right?

Yes to all.

> 2.3 If they turn off the "Reviews" widget - should the "Inventory" widget go full width?
> 2.4 If they turn off the "Low inventory" widget - should the "Reviews" widget go full width?

Let's add a class then we can style accordingly. Probably full width yeah.

> 3.2 What does the "Orders" drop down do on "Top Selling Products"?

In this view the top selling products are displayed based on order quantity. The other option in that dropdown should be revenue.

> 3.3 What does the "Revenue" drop down do on "Top referrers"

Same as above, order quantity vs revenue

> 4.1 If there are fewer than all 6 opportunity widgets selected, how should they be laid out? (e.g. if 5 are selected, 4, 3, 2 or just 1)

They should retain their width and be consistent in display _unless_ there are two or fewer. If there's two, display in a two column layout. If one, full width.

> If everything gets turned off - what gets displayed? LOL

That's a good question xD Let's make the Orders card in the todos section permanent.

**Comment by allendav** [comment]
Thank you @jameskoster !

**Comment by allendav** [comment]
@jameskoster - what should appear at the top of "momma" after they've processed all their orders?

**Comment by allendav** [comment]
@jameskoster - what are the little up/down arrows on the manage drop down?

![little-buttons-made-of-ticky-tack](https://cloud.githubusercontent.com/assets/1595739/26225979/9552ae8e-3bde-11e7-8a25-b71ca09f3a1f.png)

**Comment by kellychoffman** [comment]
> what are the little up/down arrows on the manage drop down?

This section feels like an unnatural way to re arrange dashboard layout. I think it makes more sense to have users be able to drag and drop to reorder things. What about an edit mode they enable and they can drag cards to a certain area to show/hide them? The single column list doesn't feel right.

I think we should rework the Manage interaction and put it in v1.1 if its too dev intensive - I know we don't have anything quite like that in WP.com today.
