### ISSUE TITLE
Login: nothing happens after approving push notification

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#14210]
Steps to reproduce:

- choose an account that has 2FA via authenticator app enabled
- log in to that account in the WordPress mobile app
- visit `/log-in` and enter your username and password
- you'll be redirected to `/log-in/push` and should get a push notification in your phone
- click Approve in the notification in your phone
- note that nothing happens in your browser (expected behavior: you see a green notice and are logged in).

Seems this is a regression, since it was working yesterday when I was testing M2.

**Comment by stephanethomas** [comment]
I had a look and the login endpoint returns a success flag whenever we approve the request from the WordPress.com app. The user is then logged in, but for some reasons we don't redirect them to the `Reader` page.
