### ISSUE TITLE
Login: focus back on code field if input entered if invalid

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#14212]
In `/log-in/sms`, `log-in/authenticator` and `log-in/backup`, it'd be nice to focus back on the code field if validation returned an error after clicking Continue. That's the only field on the page, so it'd be nice to make it quicker for users to fix the problem.

**Comment by gziolo** [comment]
It would be also nice to get rid of the error message when switching between authentication types:

![log-in](https://cloud.githubusercontent.com/assets/699132/26340004/35c30098-3f8c-11e7-94cc-77f7129ae0f5.gif)

**Comment by fabianapsimoes** [comment]
Fixed in  #14363.

**Comment by stephanethomas** [comment]
Reopening because of https://github.com/Automattic/wp-calypso/pull/15829 since disabling forms until the client-side page has loaded rendered auto focusing ineffective.
