### ISSUE TITLE
Login: 2FA successful submission button state

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#14220]
When logging in with 2FA the submit button is disabled when the form is submitted, and then re-enabled before log in is complete:

<img width="439" alt="screen shot 2017-05-18 at 13 52 53" src="https://cloud.githubusercontent.com/assets/275961/26202971/54e9a044-3bd1-11e7-8a62-e63ca7ad8232.png">

The button should stay disabled until the page reloads.

**Comment by fabianapsimoes** [comment]
I can no longer replicate this. The buttons in the 2FA steps now remain disabled until the page reloads.
