### ISSUE TITLE
DevDocs: sidebar navigation should highlight the selected element

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#1422]
Raised by @rralian 

> We should have a `selected` style for the active selection in the sidebar. In this case "UI Components" should be selected.

![not selected](https://cloudup.com/cIpQcSAGZD6+)

**Comment by afsheenirani** [comment]
@lancewillett - I've submitted a PR to fix this issue.

**Comment by lancewillett** [comment]
Thank you much, @afsheenirani. :)
