### ISSUE TITLE
Editor: duplicate image in post

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#14233]
When an edited image doesn't have a caption and is updated, this creates a duplicate image in the post.

To Reproduce:
- Insert an image
- Select it, click the edit pencil on the toolbar
- Click Edit, then edit the photo
- Make some changes in the image editor
- Save the image

![edit](https://cloud.githubusercontent.com/assets/1270189/26178747/71818464-3b14-11e7-817b-21edb7c351a4.gif)

**Comment by msmithgu** [comment]
Fixed with https://github.com/Automattic/wp-calypso/pull/14328
