### ISSUE TITLE
Persisting Redux with a user-id as suffix, breaks Signup resume functionality

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#14238]
As suggested by @folletto in #13185, this discussion would benefit from being done outside of the already merged PR. I'm opening this issue to discuss the issue.

The original issue I noticed can be found [here](https://github.com/Automattic/wp-calypso/pull/13185#issuecomment-301107403).

To address a comment by @gwwar: 

> @bisko Persistence is just an enhancement. Any of our flows should work with persistence turned off, as certain browsers will not support it. (Think incognito safari) You can test this locally by DISABLE_FEATURES=persist-redux make run

That's a shortcoming of Signup's code right now, because some things are stored in `localStorage` and `Flux`, while others are stored in Redux. I would be more happy if everything was inside Redux and the resume feature just didn't work, because there was no state to resume to, but right now as the data is half-and-half, it leads to a broken state.

@seear:

> @bisko I'm not familiar with the details of how signup resume works, but we could possibly fix it by tweaking the persistence behaviour so that logged-out data is persisted again, just without a user id suffix. This would still leave complications when transitioning from logged-out to logged-in.
>
> I do think that any logged-in persisted data should continue to be keyed by user id to prevent sharing of data between accounts.

I think the original issue (#11766) that was fixed with this could have been approached in a different way.

If we don't want to cross-contaminate the state, can't we have the state reset on a log-out event? This way there won't be any cross-contamination from previous sessions and the state will always be cleared out when the user logs out. 

In a in-person discussion with @mcsf, he mentioned that it's possible to log out from outside Calypso (e.g. via front-end masterbar), which wouldn't trigger the reset. With that in mind, we could instead have Calypso's boot process compare the persisted user with the current user. If there is mismatch it would be better to just clear out everything, since this will most surely be a cross-contamination.

These are just ideas for now and I'd love some input / feedback on how can we improve this functionality.

**Comment by gwwar** [comment]
> That's a shortcoming of Signup's code right now, because some things are stored in localStorage and Flux

One thought that comes to mind is to update update the current store implementation to use `client/lib/localForage`. I would encourage folks to update this as soon as possible. It's not really ideal to use mixed persistence stores for a single flow without having some ability to throw detect/throw out bad state.

> With that in mind, we could instead have Calypso's boot process compare the persisted user with the current user.

I suppose that would mean going back to a single key vs post-fixed by user?

That can be done in https://github.com/Automattic/wp-calypso/blob/master/client/state/initial-state.js#L57

> If we don't want to cross-contaminate the state, can't we have the state reset on a log-out event? 

We can, it's just a bit trickier to make sure state has been cleared and we don't accidentally persist again, since the action is async.

I'm thinking keep a reference to the `localforage.clear()` promise, and do an early return in https://github.com/Automattic/wp-calypso/blob/master/client/state/initial-state.js#L81 if the promise hasn't yet been resolved.

**Comment by folletto** [comment]
> it's possible to log out from outside Calypso (e.g. via front-end masterbar), which wouldn't trigger the reset.

Ouch. Can we fix this? Ideally any logout should pass through the same code... (I know you know, just stating it explicitly).

> We can, it's just a bit trickier to make sure state has been cleared and we don't accidentally persist again, since the action is async.

Agreed.

Transversal consideration to build on that: using a separate key is better overall in terms of _privacy_ as it creates a clearly enforced separation, and also makes explicit when data we collected when the user weren't logged in (...did they authorize that data collection? when? how?).

If I was a user and I read that there's data about me being persisted as a logged out user – which means: I didn't accept any ToS – I would start to worry. 

Making explicit the data marge between logged out and logged in I think it's important not just from a code perspective, but also from a legal perspective (yet, I am not a lawyer, so I might be over-emphasizing this aspect).

**Comment by seear** [comment]
@bisko Can you clarify which it is that breaks the resume feature?
1) That we no longer persist data for logged-out users, or
2) That we now key persisted data by user ID
