### ISSUE TITLE
Navigation: show Sharing link in sidebar as disabled until Jetpack options are ready in the UI

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#1425]
When viewing a Jetpack site in Calyspo, and you reload the page — the "Sharing" item appears only after a delay because the sidebar needs to check if the feature exists via a network request.

Video: https://cloudup.com/isD6PpBnPDq

Possibly related to #429

> Keep the sidebar item in place and handle the checks on the actual render/controller, maybe saying why it's not working and how to enable.

How to solve this? Possibly with a better sync and storage of the active Jetpack options for a given sit.

Why (via @mtias):

The problem is we delay rendering of key interface elements (like the Sharing menu item) because we don’t have information to know whether we should show it or not: is Publicize enabled or disabled?

Which then makes the sidebar jump after a couple seconds... and is an odd interaction. If we fix the jump in some other way — such as showing "Sharing" as disabled until we have the info — that would be a big improvement.

**Comment by mtias** [comment]
Fixed by @lezama in #1700. Uruguay!
