### ISSUE TITLE
Editor: the image "jumps" (height=0px) after the upload completes

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#14252]
![cap-drop](https://cloud.githubusercontent.com/assets/4389/26244422/7d175e92-3c87-11e7-9e64-6bfdf45f11d1.gif)

1. Open the editor on any post
2. Drag'n'drop an image in the text
3. The image will appear instantly (client-side rendering) without any indication of upload in progress → _the user thinks it's already done_
4. Once upload completes, the image jumps to 0 height, then again it's loaded from the server and resizes up to the preview height.

This is an interplay of two factors:

* Primary: the image jumps to 0 height and back.
* Secondary: there's no indication of upload.

The secondary factor reinforces the first, as it makes it even more unexpected, and also creates some complications if the user, unaware, tries to browse away. 

The effect is even more evident on slower connections, as the user is likely to move on to type more text on the editor, and they get a sudden jump while they are typing, and might even result in a mis-placed scroll position. Imagine this happening on mobile...

⚠️  _Why Priority High? Because while this isn't a functional issue, it's a UX / trust breaking experience, that makes working with images on the editor frustrating._

**Comment by designsimply** [comment]
Thank you for reporting this!

Adding in some historical context, this issue has been reported in the past by @apeatling at 10718-gh-calypso-pre-oss on 2015-Aug-31 and by @aduth at 7693-gh-calypso-pre-oss on 2015-Jul-14 and was moved to #1040 on 2015-Nov-30.

**Comment by lancewillett** [comment]
Fixed with d23312a, let's re-open new issues for new or different cases.
