### ISSUE TITLE
Reader: Site recs reload when clicking Back button

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14298]
### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage.
2. Click on a site recommendation.
3. From that site's stream, click on the "Back" button.
4. Notice how new site recs are being loaded replacing the previous one you were just looking at.

As a user, I would expect it to take me back to the previous page, in the state that I last saw it in.

Copypasta from @blowery:
> The difference here is that we’re treating rec’d posts as a stream and rec’d sites as a set. We grab a random two posts from the set on component mount, and the component remounts when you hit back. If we want this to be more stable, we’ll have to either treat site recs like a stream, or stash away which two we picked in redux somewhere and update them on dismiss.

This was also reported by @deancroyal.

### Video
https://cloudup.com/iNrO0OQp9gC

**Comment by fraying** [comment]
Just to be clear, we don't want the recs to be the same every time the user visits Manage. We want them to change. Every visit is a new opportunity to tempt the user to follow something new.

I think the bug described here is a pretty edgy edge case.

**Comment by jancavan** [comment]
Could no longer repro so closing this. Site recs in Manage no longer reload after clicking the Back button.
