### ISSUE TITLE
Reader: Show only a single Follow button when following by URL

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14294]
Related: https://github.com/Automattic/wp-calypso/pull/14013

When you try to follow a URL, we are showing two follow buttons: one as a "Follow by URL", the other in the site results. I think this is confusing. At initial glance, I wouldn't know the difference between clicking one or the other.

![screenshot 2017-05-19 13 41 07](https://cloud.githubusercontent.com/assets/4924246/26266535/97aadeb0-3c9a-11e7-8216-c62479dfecf6.png)

We should only show one follow button because they are the same thing.

1. If a URL exists, omit "Follow by URL" link (and Following button below the search field):
![1](https://cloud.githubusercontent.com/assets/4924246/26265879/c09350bc-3c97-11e7-9305-532aef178150.png)

2. If URL doesn't exist:
![2](https://cloud.githubusercontent.com/assets/4924246/26265944/19213398-3c98-11e7-94d1-a0b807f53689.png)

3. If you're already following the site, omit "Follow by URL" link:
![3](https://cloud.githubusercontent.com/assets/4924246/26266023/6335194a-3c98-11e7-8de1-e96658a94254.png)

![4](https://cloud.githubusercontent.com/assets/4924246/26266078/ab0dd3ba-3c98-11e7-9388-20cc89130a63.png)

**Comment by samouri** [comment]
This isn't possible to fully solve yet for the same reason that we can't correctly set the follow button for follow by url (in many cases)

Specifically for the case where user types in a url like `daringfireball.net`, we can't know that the user actually follows it yet because it redirects to `daringfireball.net/feed` on the backend.  We can't realize that they refer to the same thing until they hit the follow button.

We do have thoughts on how to solve this percolating about, but it won't be a quick fix by any means.

**Comment by jancavan** [comment]
> 2. If URL doesn't exist:

Just wanted to expound that with (2), this is great if you aren't following the site yet. However, if you're already following it, we still show the same error. For example:

![screenshot 2017-05-24 15 18 55](https://cloud.githubusercontent.com/assets/4924246/26428021/54af16aa-4094-11e7-8206-dda82e7a3c0e.png)

This is confusing because it's practically saying, "We couldn't find a match, but really, there is and you're already following it".

Can we omit that error message if we are aware the site exists?

Related: https://github.com/Automattic/wp-calypso/issues/14281#issuecomment-303833598

**Comment by fraying** [comment]
This error message is very confusingly worded.

I tried rewriting it, but the truth is I don't think we need it at all. The user doesn't care what is or isn't in our index. If they're entering a URL, they know the site they want to follow. We need to get out of their way and just let them try to follow it. If it works, great! If it errors, then we can get wordy. But there's no need for a wordy message to tell them something isn't in our index.

**Comment by fraying** [comment]
In fact, this is not a bug:

![97aadeb0-3c9a-11e7-8216-c62479dfecf6](https://cloud.githubusercontent.com/assets/24388/26692556/f279df88-46b5-11e7-8bb5-5ca148bff0c3.png)

This is as designed. It's okay that there are two ways to follow. Some people may be looking for the special follow-by-URL link, others may be looking in the results. We want both to be there to serve both audiences.
