### ISSUE TITLE
Login: fix redundant copy after sending a text message

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#14308]
In #14100 we added a global notice on the text message code screen:

![image](https://cloud.githubusercontent.com/assets/426518/26285212/02c8a78a-3e54-11e7-88b0-35b58ef9ee1d.png)

This notice repeats the same information shown on the form. @scruffian mentioned that the global notice only shows if we just sent a text message, but users may reach this screen even if we haven't just sent them a text message (for example, to enter a code sent by text message earlier). 

Either way, since the default copy on the screen seems to be the same as the notice, it would be equally incorrect when a message was not just sent.

I'm not sure about using the global notice here. This is a part of the flow, not something that is happening in the background. And I think these globals are intended for shorter and simpler messages, for example in this case something like "Message sent"? Global notices with long messages that wrap don't look great. 

If possible, when we send a text message, I think it would be better to show the information from the global notice (with the phone number) in the caption above the text field. And the global notice can either be a simpler "message sent" or something like that, or just removed entirely.

If we need to use the global norice for this, we can at least change the copy in the form so it doesn't repeat it unnecessarily. For example, something like "Enter the code from the text message we sent you."

**Comment by fabianapsimoes** [comment]
From what I gather from #14100, seems the goal of the notice was to hint to users the phone number where they can expect to find the verification code. From @scruffian's comment on #14092, I'd guess it's not straight forward to add that code to the caption instead of the notice:

> It may be necessary to change the implementation here so that the number is shown in the notice rather than on the screen.

In that case, maybe we can just change the notice to `Message sent to the number ending in 1111`?

**Comment by ranh** [comment]
That sounds good, so we can have this in the notice:

> Message sent to phone number ending in 8888.

And this in the form:

> Enter the code from the text message we sent you.
