### ISSUE TITLE
Login: "authenticator app" should not be capitalized 

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#14314]
The word "authenticator", for example in the phrase "authenticator app", is capitalized in a few places. For example:

<img width="433" alt="ranimac3 screenshot 2017-05-22 at 10 36 10" src="https://cloud.githubusercontent.com/assets/426518/26297219/9ac98eec-3eda-11e7-988e-131aa183f0d9.png">

Since "authenticator" is not the name of a specific app, it should not be capitalized. 

On a similiar note, we should probably stick with "authenticator app", and not longer phrases like "authenticator mobile application". For example:

<img width="446" alt="ranimac3 screenshot 2017-05-22 at 10 38 23" src="https://cloud.githubusercontent.com/assets/426518/26297277/d3f55192-3eda-11e7-8dff-0e6bf3ca0ee0.png">

**Comment by aistosi** [comment]
Hi! Would like to take a look at this
