### ISSUE TITLE
Site Picker: Example text shows when loading site picker

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#14329]
#### Steps to reproduce
1. Starting at URL: WordPress.com
2. Click my sites
3. While sites are loading in site picker (say, after disconnecting a Jetpack site):
4. Mouse over blue flashing placeholder, see

<img width="260" alt="screen shot 2017-05-22 at 10 05 53 am" src="https://cloud.githubusercontent.com/assets/1883296/26315831/5faa2d02-3ee0-11e7-9d49-69832be36a64.png">

#### What I expected

Something more aesthetic ... or at least not the component's example text

#### What happened instead

The component's example text is shown

#### Browser / OS version

Any

**Comment by folletto** [comment]
I think the proper fix to this is to avoid any highlight to happen: it's loading, there's nothing to be clicked there.

**Comment by sirreal** [comment]
> I think the proper fix to this is to avoid any highlight to happen: it's loading, there's nothing to be clicked there.

@folletto Don't you think it would be good to remove the example content? "This is an example" sounds like it's coming from a design concept rather than an implementation. It seems like a loading text or icon would be more coherent.

**Comment by folletto** [comment]
Yes absolutely. I think that's mostly placeholder content that is used for the pulsating loader – but I'm not 100% sure as I should check and it loads too fast :P 

The issue there however will still be the highlight: fixing that is the main priority as would both hide text and avoid the user perception that there's anything clickable. Then we can replace the text for cleanliness. :)
