### ISSUE TITLE
Reader Following Manage: flash of empty state when loading

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#14322]
While subscriptions are loading, it's possible to get a glimpse of Drake and the "you haven't subscribed to anything yet" empty state, even if you are subscribed to lots of feeds.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

I attempted to reproduce this but could not do so.

I am proposing to close this issue with an appropriate label denoting reason for closure if no work is scoped for the near term.

**Comment by bluefuton** [comment]
Thanks @worldomonation! Happy to close it. I wasn't able to reproduce it either (even with an empty local storage and throttled connection).
