### ISSUE TITLE
Flow: I need to add a new category

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#14323]
Scenario: I need to add a "Shorts" sub-category of "Apparel".

Prototype: https://automattic.invisionapp.com/share/5DBTHTKXC#/234949702_Categories_List

Sketch file: https://www.dropbox.com/s/hwaps5owfb0ahoj/categories.sketch?dl=0

**Comment by justinshreve** [comment]
Product category management added the ability to add a new category.
