### ISSUE TITLE
Settings: The primary blog selector doesn't give enough context

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#1432]
Just worked on an issue with @csonnek where we needed to update the user's primary blog. And it seems pretty common when someone is transitioning between different sites that they may have similar (or exactly the same) titles. So in this case, there were two identical options in the dropdown. We should add some context... maybe just the url in addition to the site would be sufficient.

**Comment by lancewillett** [comment]
Visual note on this selector: when you have more a lot of sites (say more than 5) in the dropdown menu sometimes you can't reach the bottom site or two, they get cut off.

Reported by @nickmomrik in Slack today; I was able to repeat in Mac-n-Chrome.

<img width="414" alt="screen shot 2016-05-16 at 14 35 12" src="https://cloud.githubusercontent.com/assets/66797/15304651/7c276f58-1b73-11e6-83f4-da5bd6797fce.png">

This **does not** happen on the apps components page: https://wpcalypso.wordpress.com/devdocs/app-components with the "SitesDropdown" component.

<img width="820" alt="screen shot 2016-05-16 at 14 35 38" src="https://cloud.githubusercontent.com/assets/66797/15304652/7f4f552e-1b73-11e6-8c6c-215459e9def5.png">
