### ISSUE TITLE
WooCommerce: Warn the user if the site they are attempting to manage is not one of their sites

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14349]
i.e. when on `/store` routes, in lieu of the store sidebar and content, we should tell them that the site they are attempting to access is not one of their sites (if it exists at all, LOL).

Needs design
cc @kellychoffman 

See also #14347 and #14348

**Comment by jameskoster** [comment]
If the store doesn't exist:

![storenotfound](https://cldup.com/mYK9ewWh2K-3000x3000.png)

**Comment by kellychoffman** [comment]
I discovered that the default behavior for this in WP.com is just to send the user to their All Sites view. As time is a factor, we should probably do this for v1 and implement our snazzy design in v2.

**Comment by justinshreve** [comment]
Moving this to a future release. As of #16008, we redirect to all sites for v1.
