### ISSUE TITLE
WooCommerce: Warn the user if they are not authorized to manage the store

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14348]
i.e. when on `/store` routes, in lieu of the store sidebar and content, we should tell them they do not have permission to manage the store.

Needs design
cc @kellychoffman 

See also #14347 and #14349

**Comment by jameskoster** [comment]
If they don't have permission;

![permission](https://cldup.com/zkZezF-bVD-3000x3000.png)

**Comment by kellychoffman** [comment]
Mentioned this here as well, but: 

> I discovered that the default behavior for this in WP.com is just to send the user to their All Sites view. As time is a factor, we should probably do this for v1 and implement our snazzy design in v2. 

https://github.com/Automattic/wp-calypso/issues/14349#issuecomment-307084007

**Comment by kellychoffman** [comment]
Dupe
