### ISSUE TITLE
Publicize: handling publicize previews for unconnected services

### ISSUE THREAD

**Issue by jhnstn** [Automattic/wp-calypso#14356]
We are currently developing a preview modal to show how a shared post will appear on a sharing network. The modal uses post data and the service connection data such as user name and profile image. Currently however the preview modal appears blank for any unconnected service:

![preview](https://cloud.githubusercontent.com/assets/744755/26326897/21ddf06e-3ef2-11e7-9cbc-73b1429624f8.gif)

In this example we have 3 services ready for preview but only 1 is connected.

**Possible Options**

1. Only show previews for connected services. We only show the preview button when a user has at least 1 connected service so the modal will have at least 1 service to preview:
![screen shot 2017-05-22 at 1 12 25 pm](https://cloud.githubusercontent.com/assets/744755/26327066/b6682bb4-3ef2-11e7-93e5-0a5505631cbe.png) (#14355)

2. Show all available services on the modal sidebar but with a "connect to see preview" for unconnected services.
![screen shot 2017-05-22 at 2 47 41 pm](https://cloud.githubusercontent.com/assets/744755/26330485/f3694f94-3f00-11e7-8d52-29d42bb38156.png)

3. Show all available services but show stock service data for unconnected services.

**Comment by rralian** [comment]
Of these options I would go with number 2.

Is there some option where we would disable the side buttons and have some tooltip popup if you click on it with a similar message and link?

**Comment by sirbrillig** [comment]
I agree that number 2 is probably more discoverable, as long as it links to the place where you can connect the service. I assume that's what the "Settings" link would do in your image above, although I think it would be even more friendly if the action was "Connect" (bonus if it could start the connection process, but that's a nice-to-have). 

> Is there some option where we would disable the side buttons and have some tooltip popup if you click on it with a similar message and link?

I'm not sure exactly what you're envisioning, but I think that disabled buttons might be more frustrating and not as discoverable as an already-visible "please connect by clicking here!" link (assuming the first provider is not connected; otherwise it requires a click anyway).

**Comment by jhnstn** [comment]
> Is there some option where we would disable the side buttons and have some tooltip popup if you click on it with a similar message and link?

Not sure we want to end up with a modal inside a modal here. And a tooltip might not be enough information.

> I agree that number 2 is probably more discoverable

I'm not so sure we need the discoverability at this point in the workflow. The step just prior to the preview shows the connected services with a nice CTA "Add Account" button.  I actually think it might be less discoverable to find the network(s) that the user has connected. We could replicate the "Add Account" flow from the prior step if we want to let the user know there are more options to preview.

![screen shot 2017-05-22 at 3 37 28 pm](https://cloud.githubusercontent.com/assets/744755/26331265/de6fd2da-3f04-11e7-8408-0d7c6d1585a4.png)

**Comment by rralian** [comment]
I do like having a good permalink we can send people to, so I'm back to voting for your number 2 option.

**Comment by sirbrillig** [comment]
> I'm not so sure we need the discoverability at this point in the workflow. The step just prior to the preview shows the connected services with a nice CTA "Add Account" button.

Good point! In that case I guess I'd say we just don't want a user to see a blank list or a blank preview if they click preview with no services connected. It's more of a fallback for users who don't read the labels in the previous dialog. "hmm.... Preview, yes. I want that. *click* Oh! Facebook! Yes, let me see what that would look like. Oh? Why is there no preview?"

**Comment by jhnstn** [comment]
> just don't want a user to see a blank list or a blank preview if they click preview with no services connected. 

Totally agree!

We actually already account for this. Users are shown this if they click "Share" and have no connected services:
![screen shot 2017-05-22 at 3 57 22 pm](https://cloud.githubusercontent.com/assets/744755/26331802/bc1db82a-3f07-11e7-86fd-9a58967804fb.png)
The "Preview" button is only displayed if the user has at least 1 connected service.

If we want to go with the showing the user what a share _could_ look like we'd probably want to go with a combo 2+3: Show the connect the service message with some stock connection info. We can still use the post data to get a decent preview. That would probably be a v2 candidate however

**Comment by sirbrillig** [comment]
> The "Preview" button is only displayed if the user has at least 1 connected service.

TIL. Ok, in that case I'm kinda in favor of option 1 now. Commented on #14355

**Comment by artpi** [comment]
On the Hangout we decided to go with option 2 since that fosters discoverability
