### ISSUE TITLE
Email subscriptions not obeying default setting when non-Calypso follow button is used

### ISSUE THREAD

**Issue by yanirs** [Automattic/wp-calypso#14399]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/notifications/subscriptions
2. Set *Default Email Delivery* to *Send email instantly*
3. Follow a blog
4. View the newly-followed blog's subscription settings on https://wordpress.com/following/manage
5. The blog's email subscription settings are off:
![image](https://cloud.githubusercontent.com/assets/3952615/26380400/ba596b78-4061-11e7-81e9-df82eac60897.png)

#### What I expected

To be subscribed to email updates from the newly-followed blog.

#### What happened instead

I wasn't subscribed to emails from the newly-followed blog.

**Comment by jancavan** [comment]
At first I thought I was able to repro the issue, but I think what's happening here (correct me if I'm wrong @yanirs) is there's a delay. 

The settings in the popover are initially `Off`, but then immediately change to `On`: https://cloudup.com/c3kBJiKBhoN

**Comment by yanirs** [comment]
@jancavan Nope, that's not the behaviour I'm seeing. The settings are still shown as off after reloading the page. I followed a site by visiting it and clicking the Follow link.

**Comment by bluefuton** [comment]
@yanirs thanks for reporting this! I'm unable to repro with the same settings.

Can you remember what feed you were trying to follow, and how you followed it (via URL, search or recommendation)? What browser/platform were you using?

**Comment by yanirs** [comment]
@bluefuton I can consistently reproduce it by going directly to site URLs and clicking the follow link on the bottom-right corner. I just tried it on https://randomstratum.wordpress.com/ and the previous example was with https://greg.blog/.

When following the same steps as @jancavan, i.e., following a recommended site under the search box, I *do* get subscribed to emails. Subscription also works as expected when clicking on a recommendation title (i.e., from `https://wordpress.com/read/feeds/<id>`).

I'm using Firefox 53 on Ubuntu 16.04. I also reproduced the issue on Chrome 58.

Here are my Reader Subscriptions settings, if that helps:
![image](https://cloud.githubusercontent.com/assets/3952615/26400019/78262ff0-40c2-11e7-9b26-529ea55a3e96.png)

**Comment by bluefuton** [comment]
> I can consistently reproduce it by going directly to site URLs and clicking the follow link on the bottom-right corner.

Aha! Thanks for the extra detail @yanirs. That's the culprit.

The follow button that appears in the bottom right of sites works differently to the Calypso one. It doesn't fetch email subscriptions on follow, which would explain the behaviour you're seeing.

I'll have a ponder about possible solutions.

**Comment by jancavan** [comment]
@bluefuton This appears to have been resolved? I follow from the Actionbar and my email settings for that site is "on".

@yanirs Are you still experiencing this issue?

**Comment by yanirs** [comment]
@jancavan Yeah, I'm still experiencing the issue, following the same steps as above.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was able to reproduce this issue:
![Screen Shot 2021-02-11 at 11 14 04 AM](https://user-images.githubusercontent.com/6549265/107686608-4d059500-6c5a-11eb-8730-7bedf0331d33.png)

Updated steps to reproduce:

1. Starting at URL: https://wordpress.com/me/notifications/subscriptions
2. Ensure `Default Email Delivery` is set to `Send email instantly`.
3. Follow a blog.
4. View the newly-followed blog's subscription settings on https://wordpress.com/following/manage

Expected:
Followed blog > Setting > Email related options should be set to ON.

Actual:
Email notification toggles for the newly followed blogs are set to OFF.

**Comment by roo2** [comment]
I couldn't reproduce this, when I set `Default Email Delivery` to `Send email instantly` and subscribed from the actionbar, I found that the site was signed up for emails as expected. Perhaps this bug has been fixed in the meantime, I'll close if no objections @worldomonation, @yanirs.

I also tried with the sites https://gorelik.net/ and https://greg.blog/

https://user-images.githubusercontent.com/22446385/216886337-156025c9-c754-4fd0-af36-12710ef67e72.mov
