### ISSUE TITLE
Reader: follow button cropped in feed header on mobile

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#14404]
On an emulated iPhone SE, the follow button label gets cropped in the feed header:

![screen shot 2017-05-24 at 09 53 51](https://cloud.githubusercontent.com/assets/17325/26392676/b961c0fc-4067-11e7-8082-be7228c1c8a6.png)

The feed in the example is http://calypso.localhost:3000/read/feeds/5941078 and the locale is `fr`.

**Comment by bluefuton** [comment]
Perhaps we should drop the label at that screen size?

**Comment by jancavan** [comment]
I was able to repro this even with `en` set:

![img_9176](https://user-images.githubusercontent.com/4924246/27564798-111fc974-5a8f-11e7-908f-af769b612f5e.PNG)

**Comment by jancavan** [comment]
Closing since I'm no longer able to repro this.
