### ISSUE TITLE
Notice component no longer shows no-status correctly

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#14418]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/notices
2. Notice that the `I'm a notice with no status` notices appear blue, the same as the `is-info`

#### What I expected
For the "no status" notices to have a grey background

#### What happened instead
They have a blue background, since PR https://github.com/Automattic/wp-calypso/pull/14148 added a defaultProp to set status to is-info.

cc: @sirreal 

#### Browser / OS version
Seen here side by side (old and new) on OSX Firefox:

#### Screenshot / Video
<img width="1226" alt="screen shot 2017-05-24 at 10 35 12 am" src="https://cloud.githubusercontent.com/assets/7233112/26409046/746bb146-406d-11e7-880a-85ba2a86f034.png">

#### Context / Source
#automated-testing #visdiff

**Comment by sirreal** [comment]
Thanks for catching this @hoverduck!
