### ISSUE TITLE
Comments: empty state

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#14419]
Each filter should have an empty state.

I don't think adding a button to these would be very helpful and it would be unnecessary. I had a hard time finding a good reason to add a subtitle on some of these, so I went with being concise.

**Pending:**

![edit copy 2](https://cloud.githubusercontent.com/assets/618551/26409272/af599c58-4065-11e7-84f5-d1ebcd6debf9.png)

Note: They could be a new user, or just cleared their queue.

**Approved:**

```
No approved comments.
```

Note: if they have no approved comments then their site has no comments on it.

**Spam:**

```
No spam comments.
```

**Trash:**

```
No deleted comments.
```

Note: They could have never deleted a comment, or they could have deleted everything permanently.

<del>not sure about "trashed" vs "deleted"</del>

**Comment by mikedang** [comment]
Hey @drw158 — These look good to me. For the Trash filter, I would go with "No deleted comments." When I think of "trashed," I think of messy ("Great party! Sorry we trashed your place.") or intoxication ("Great party! We all got responsibly trashed!").

**Comment by drw158** [comment]
thanks for the review!

**Comment by Copons** [comment]
@drw158 What about the second line ("your queue is clear" when in pending) for approved/spam/trash/all (all could be the same as approved I guess)?

**Comment by drw158** [comment]
Well, I meant the second line to mean more like, "Good job, you've sorted through all of your pending comments". Let's keep it the way it is, but I'm open to removing it, or adding subtexts for the other filters, if it feels weird.

The illustration is not in Calypso yet, but I can either add in a PR, or you can add it in one of yours! Whatever you prefer.
