### ISSUE TITLE
Food menus: empty state displays as load state

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/wp-calypso#14413]
When opening the food menus tab, if there aren't any menu items, the empty state displayed is a load state. This makes it feel as though the page is loading indefinitely—I sat there for a while waiting until I realised it was actually finished.

![food-menus-wtf](https://cloud.githubusercontent.com/assets/376315/26402885/fa42813a-4083-11e7-8858-bf6778148f3b.gif)

Compare to the empty state for testimonials, which feels right.

#### Steps to reproduce
1. Activate any theme that uses the "food menus" CPT (Confit, Canape, etc) on a test site.
2. Navigate to the "Food Menus" tab.
3. Get confused.

#### What I expected
Expected to see an empty state more like what displays for testimonials:
<img width="1145" alt="screenshot 2017-05-24 13 24 06" src="https://cloud.githubusercontent.com/assets/376315/26402972/52664f4a-4084-11e7-993e-53ed750c640a.png">

#### What happened instead
A load state appears and never changes:
<img width="1149" alt="screenshot 2017-05-24 13 23 47" src="https://cloud.githubusercontent.com/assets/376315/26402996/682bde80-4084-11e7-80f4-6d0887064772.png">

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

Is this issue still applicable?

If not, I am proposing to close this issue with an appropriate label denoting reason for closure if no work is scoped for the near term.
