### ISSUE TITLE
Site Settings: Footer Credit link to Customizer doesn't have enough space

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#14412]
When looking at https://wordpress.com/settings/general/SITE_URL, I get this:

<img width="748" alt="screen shot 2017-05-24 at 1 53 35 pm" src="https://cloud.githubusercontent.com/assets/23619/26401987/b2824de4-4088-11e7-8622-e362fa9f6848.png">

The space between the text and the button that links to the Customizer seems like it's not enough.

**Comment by lordnino** [comment]
is this issue up for grabs ? , if it's i wanna contribute in it.

**Comment by lsinger** [comment]
@lordnino please do! be sure to check out the repo README and [CONTRIBUTING](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md).
