### ISSUE TITLE
JPC: When storage is cleared, pre-connected site is not recognized

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#14425]
#### Steps to reproduce
1. Open https://wordpress.com and clear storage (except cookies).
1. `https://wordpress.com/jetpack/connect?url=$site` where `$site` is an already connected Jetpack site on your account.
1. The connect/auth flow will complete and you will be redirected to your `$site`'s page.
1. Repeat without clearing storage and you will see the message as expected "This site is already connected!"

#### What I expected

To stop and see the message.

#### What happened instead

The connect/auth flow completed and I was redirected to the site's page.

#### Browser / OS version

Chrome >60 / macOS

#### Screenshot / Video

Here's where I expect to end up (and where I end up when storage isn't cleared):

![connected](https://cloud.githubusercontent.com/assets/841763/26413377/2000ac26-40ac-11e7-9dce-eaeb0526ed13.png)

cc:
@tyxla via #13599 (the fix when storage is not cleared)
@roccotripaldi via #14074 (maybe this is related?)

#manual-testing

**Comment by roccotripaldi** [comment]
I'm also noticing that I can no longer link additional users to a site. Perhaps it is related...

**Comment by sirreal** [comment]
@roccotripaldi Did you report that somewhere or are you still investigating?

**Comment by tyxla** [comment]
#13599 was reverted in #14523, @sirreal is this one still reproducible?

**Comment by sirreal** [comment]
@tyxla Nope, can no longer reproduce. Closing.
