### ISSUE TITLE
WooCommerce: Taxes: My store is in a state that does not have a sales tax

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14439]
This is the easy case. Merchants in certain states are NOT required to collect sales tax at all (i.e. Delaware, New Hampshire, Oregon).

We should probably have
- a really simple nux flow for them just to acknowledge that / remind them of that
- a super simplified no-taxes-for-you tax settings page

See also #14440 and #14441

**Comment by jameskoster** [comment]
In this case, the tax step in the egg-dash can be pre-checked with an explanation;

![setup-taxes](https://cldup.com/3DjTN4bLCv.png)

If they later enter the tax settings screen, they'll see a simplified UI;

![tax-settings](https://cldup.com/6_iISLFCoV-3000x3000.png)

Probably no need to display the 'prices include tax' / 'charge tax on shipping' settings if the rates are 0%. However, if they change the store location to somewhere that does charge sales tax we'll need to prompt them to fill in these settings. Maybe send them to the initial step of the 'wizard'.
