### ISSUE TITLE
Editor: Location function in Calypso does not publish the location on a post.

### ISSUE THREAD

**Issue by graciemae** [Automattic/wp-calypso#1443]
When adding a location or updating a location to a post from Calypso, the changes do not impact the published post.

This might be related in some way to these other issues with the location field: https://github.com/Automattic/wp-calypso/issues/1389

Steps to reproduce:
Open a new post in the Calypso editor, add a location from the sidebar, and publish the post.

What I expected: To view the post and see the location.

What happened: I viewed the post, and the location was not published.

When I entered the WP-Admin editor for the post, the location had been entered, so the location is being saved. When I updated the location through WP-Admin, the location then published through to the post.

Here's a screencast of the steps: 

![testing location](https://cloud.githubusercontent.com/assets/13108965/11700030/62f34c24-9e95-11e5-8e9c-19d831a29885.gif)

**Comment by lancewillett** [comment]
I was able to repeat this today — the main difference is the Calypso geolocation is saved in coordinates, not nouns like wp-admin does.

It could be less a bug with Calypso and more how the geolocation plugin outputs the location, if it's not in expected format.
