### ISSUE TITLE
WooCommerce: Taxes: My store is in a state that charges sales tax based on my business address

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14440]
Merchants in certain states are required to collect sales tax based solely on the business' address (e.g. Arizona, California, Illinois, Mississippi, Missouri, New Mexico, Ohio, Pennsylvania
Tennessee, Texas, Utah, Virginia, possibly others)

We should probably have
- a really simple nux flow for them just to acknowledge that / remind them of that
- a super simplified just-one-tax-rate-for-you tax settings page

Core does something similar during its wizard:

![screen shot 2017-05-24 at 2 25 13 pm](https://cloud.githubusercontent.com/assets/1595739/26426304/e4349f78-408c-11e7-9378-5c581cd2d983.png)

**FTW - since at this point in the flow we have the complete business address, we could actually use a service to get the rate and rate breakdown for their store and present it to them (as information only).  I see no need to allow them to edit it.**

See also #14439 and #14441

**Comment by jameskoster** [comment]
The design in the 'Master Wizard' page of the [Sketch file](https://www.dropbox.com/s/x7tqa91h6nqgwua/tax.sketch?dl=0) can be applied to this scenario with a couple of tweaks. The tax rates table will include a single rate (the store location rate):

![tax-rates](https://cldup.com/j5VSpqrWYE-3000x3000.png)

The view rates modal would also differ slightly;

![tax-rate-modal](https://cldup.com/7Lrfy7LsAP-3000x3000.png)
