### ISSUE TITLE
Settings: Primary Blog can be hidden

### ISSUE THREAD

**Issue by csonnek** [Automattic/wp-calypso#1444]
In working on narrowing down #1248 with @rralian, we found a bit of an annoyance with hidden/visible sites and the Primary Blog setting. 

If your Primary blog is set to a site, then you hide that site but leave one other site visible - meaning the `visible_site_count` is set to 1 - it still defaults to the set "Primary" site when you click the "My Blog" link. 

We should clear out their Primary site entry if they hide the blog that's set as their primary and prompt them to select a new primary site. 

@rralian let me know if I missed anything or if the above needs more explanation.

**Comment by rralian** [comment]
> We should clear out their Primary site entry if they hide the blog that's set as their primary and prompt them to select a new primary site.

Or we could just show some notice saying you cannot hide your primary blog.

There's another side to this, which is that if you set one of your hidden blogs to be your primary blog (this is possible), then we should automatically set that blog to visible.

/cc @lancewillett

**Comment by lancewillett** [comment]
I agree with Bob that the better fix would be to update the My Blogs interface on WordPress.com so you cannot hide your primary blog. And to account for setting a hidden blog as primary. Both cases would avoid this situation from the outset.

I'll take a look at improving the My Blogs functionality on WP.com and report back.

**Comment by lancewillett** [comment]
First part of the change is deployed.

"My Blogs: make it harder to set a primary blog to hidden."
* Disallow bulk editing a primary blog to hidden via "Hide Blog From Dashboard" bulk edit.
* Don't show "Hide" Ajax-driven link in the row of available actions for the primary blog.
* Check for primary blog matching blog ID being acted upon for all hide actions.

**Comment by lancewillett** [comment]
Second part of the improvements are now deployed.

"My Blogs: UX improvement for setting a hidden blog as primary"

* If you try to set one of your hidden blogs to be your primary blog, we should automatically set that blog to visible.
* Show primary blog in a different way from the rest of your blogs (background color should stand out).
* When setting a new blog as primary, refresh the page so it's shown at the top.
