### ISSUE TITLE
WooCommerce: Taxes: My store is in a state that collects sales tax based on where my orders ship to

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14441]
Merchants in most states are required to collect sales tax based on where they ship product to.

We should probably have
- a really simple nux flow for them just to acknowledge that / remind them of that
- a super simplified tax settings page that mentions that, maybe gives the overall state rate but also notes that additional taxes vary by order shipping address and will be calculated automatically

See also #14439 and #14440

**Comment by jameskoster** [comment]
The design in the 'Master Wizard' page of the [Sketch file](https://www.dropbox.com/s/x7tqa91h6nqgwua/tax.sketch?dl=0) can be applied to this scenario.
