### ISSUE TITLE
Add a flag to remove the 'long content fade' in the Section Header component

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#14454]
We're using [this component](https://github.com/Automattic/wp-calypso/tree/master/client/components/section-header) in https://github.com/Automattic/wp-calypso/pull/13956

The fade is causing descriptions to become partly illegible;

![fade](https://cldup.com/iNbmqeYK-l-2000x2000.png)

It'd be cool to have a flag to turn this style off.

**Comment by harshil562** [comment]
I am interested to pick this component and work on it.
Can I pick this issue and start working ?

**Comment by jameskoster** [comment]
Sure! Just send a PR :)
