### ISSUE TITLE
Jetpack: infinite redirect loop after opening a draft post in Editor

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#14459]
This bug was reported by a user in 3221175-t. It can be easily reproduced in SU mode. I use `example.com` domains in the following steps, in order to not expose private info.

1. Go to `https://wordpress.com/posts/example.com`. There is one post in the "Latest Draft" section on the right. The link leads to `https://wordpress.com/post/exampledotcom.wordpress.com/737`. Note that it's a different site.
2. Click on the link. Editor opens and an infinite navigation loop will start -- the page route will start cycling between `/post`, `/post/exampledotcom.wordpress.com` and `/post/example.com`.

Looking at the Redux state in devtools, it shows two sites in `sites.items`, and they have a URL collision:
```
URL: http://example.com
jetpack: false
visible: false

URL: https://example.com
jetpack: true
visible: true
```

One of the sites is connected with Jetpack, and the info in the sites list seems inconsistent or corrupted.

Issue #12016 might be related -- Jetpack site, infinite loop, `/posts` page...

**Comment by rachelmcr** [comment]
It looks like https://github.com/Automattic/wp-calypso/pull/14685 resolved this issue for the site that originally reported it. I don't have the correct setup to retest the issue, but we haven't had any further reports so I'm closing this as resolved.
