### ISSUE TITLE
Reader: sending incorrect subscription_count for all stats

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#14470]
As @bluefuton found in https://github.com/Automattic/wp-calypso/pull/14383#issuecomment-304002025, 

> Works well! One thing I noticed is that we're no longer sending along the correct `subscription_count` with the event - need to change it to look at Redux state I think:

<img width="1018" alt="screen shot 2017-05-25 at 14 46 50" src="https://cloud.githubusercontent.com/assets/17325/26450709/1d6021ec-4159-11e7-88f8-2ced25ecfd64.png">

**Comment by samouri** [comment]
In order to solve this one we are going to need to give the stats module access to the redux store

**Comment by samouri** [comment]
This should be really really easy now with the `redux-bridge` I'll look into fixing it this week.

**Comment by bluefuton** [comment]
@martinremy just rediscovered this one (#47678) - reference p5PDj3-4WA-p2.

**Comment by bluefuton** [comment]
Two options to fix this:

1. Pass the subscription count to `recordTrack` every time it's called in Reader.
2. Replace recordTrack with a Redux action and fire the pixel via Redux middleware, which would inspect the state tree and add on whatever it liked (thanks to @blowery for explaining this option).
