### ISSUE TITLE
WooCommerce header needs to stretch to 100% width.

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#14484]
The Main component, which is being used for top-level navigation components within the WooCommerce extension limits width to 720px. The header for each page needs to be contained within its respective top-level component as they're different for each page. So we will need to change the structure of our pages to exclude the header from the Main component on each one.

So far, this affects the following pages:

- [ ] app/products/product-create.js
- [ ] app/dashboard/index.js
- [ ] app/settings/payments/index.js
- [ ] app/settings/shipping/index.js
- [ ] app/stats/index.js

**Comment by kellychoffman** [comment]
Fixed
