### ISSUE TITLE
Settings: Traffic: WordPress.com site Ads settings

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#14489]
Premium Jetpack sites are auto-enrolled in the ads program, but WordPress.com sites have to apply manually and are approved based on traffic and site content. We need a flow in settings to allow WordPress.com sites to apply from there and see the status of their application.

I've worked up a quick mockup:

![image](https://cloud.githubusercontent.com/assets/437258/26470598/51d5606e-416c-11e7-94ae-774071a36309.png)

I believe the compact notices should persist until the user performs an action, but we've never had a flow for this on WordPress.com before so it's new ground. 

cc @ashleighaxios @tyxla @dbspringer (for copy and any other insights) @jonathangilmoreburke 

see #12842 for further discussion

**Comment by rickybanister** [comment]
Oh, one other note, we have `gridicons-speaker` so that should be used instead of the star—I was just using devdocs simple example for my mockup.

**Comment by dbspringer** [comment]
Thanks @rickybanister, mockups look great, though I'm not sure of a case when we'd reach that last option. Though it might not be a bad idea to provide an API response about that status/eligibility of a site; we'd then be able to provide a bit more context for that last notice.

**Comment by rickybanister** [comment]
Can you clarify what exactly we should show in that final situation? Should we hide the entire 'Ads' card from users that have applied and are denied? Should we just show a message without the option to reapply forever?

**Comment by dbspringer** [comment]
There's no reason to reapply, either they're eligible to apply, ineligible, or waiting for review. If they're ineligible we should list the reason why (generally it's because they don't have a mapped domain or aren't the site's owner), but we don't want to give the impression that multiple applications will help them in any way.

**Comment by ashleighaxios** [comment]
I see. Folks don't get turned away due to lack of traffic then?

**Comment by tyxla** [comment]
> Folks don't get turned away due to lack of traffic then?

@ashleighaxios actually, they can be - WordAds FAQ states that there is a minimum monthly traffic of thousands of pageviews - see https://wordads.co/faq/#eligibility

**Comment by ashleighaxios** [comment]
Thanks, @tyxla. I thought so. 

If they can be turned away due to lack of traffic, it means that if they get more traffic in the future and may want to reapply. We shouldn't make it a one-time application process.

**Comment by mtias** [comment]
Yes, please, it should be done in a way that doesn't force us to require this attribute for all sites:

https://github.com/Automattic/wp-calypso/pull/14862

**Comment by tyxla** [comment]
Let's stick with the `site.options.wordads` attribute for now, but once we get to building the new version, we can make it part of the settings endpoints - it's already being done for the Jetpack settings endpoint: https://github.com/Automattic/jetpack/blob/5fb4e366823a64f4b51078bf1fa855162a34a3a2/_inc/lib/class.core-rest-api-endpoints.php#L1563

**Comment by tyxla** [comment]
This could still be useful. Let's leave it open.

**Comment by worldomonation** [comment]
@tyxla In the previous instance of stale label being applied you mentioned this could be useful. Even if that were the case, is there any plan in the near future (~1 year) to work on this? 

If not, it would be preferable to close the issue for the time being, then re-open or create a new task when the time comes.

**Comment by tyxla** [comment]
Sounds totally fine by me to close it for now. Thanks for the cleanup!
