### ISSUE TITLE
Woo-Connect Insights: Add Widgets/Sparkline

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#14497]
Add either widgets or sparklines into main Orders page. Depends on https://github.com/Automattic/wp-calypso/issues/14496

<img width="175" alt="screen shot 2017-05-16 at 9 24 39 pm" src="https://cloud.githubusercontent.com/assets/1922453/26477809/55710a2e-421c-11e7-991c-de4449f6d60c.png">

Ensure proper layout across desktop and mobile

**Comment by greenafrican** [comment]
Closed in https://github.com/Automattic/wp-calypso/pull/14623
