### ISSUE TITLE
People: Changing user role on Jetpack site doesn't change Calypso role

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#14490]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/people/edit/example.com/username
2. Change a user's role
3. Login to /wp-admin with user and confirm new role is reflected
4. Check wordpress.com when logged in as user and note that the capabilities will reflect their original role on the site and are not updated or kept in sync with role changes through wordpress.com/people

If you change the role from /wp-admin/user-edit.php the new role is reflected on wordpress.com/people, but the Calypso capabilities remain unchanged from their original value. Calypso's role for the user can be found from the blog report card.

#### What I expected
Changes to the user's role from wordpress.com/people or /wp-admin/user-edit.php to also change their Calypso capabilities. 

#### What happened instead
The user's Calypso role/capabilities are stuck with their original role on the site. This results in users that have been downgraded in role seeing options they do not have permission to access or change, and users who have their role increased not seeing sections they should now have access to.

#### Browser / OS version
OS X 10.11.6/Chrome 58

#### Screenshot / Video
![screen shot 2017-05-25 at 5 31 17 pm](https://cloud.githubusercontent.com/assets/1900444/26471531/049ebe68-4170-11e7-8014-7a1b6d5906ce.png)
![screen shot 2017-05-25 at 5 31 25 pm](https://cloud.githubusercontent.com/assets/1900444/26471530/049a6b92-4170-11e7-9df2-541df2b41d0a.png)

**Comment by kriskarkoski** [comment]
To add some more details, user krisk87 was added to kriskarkoski-automated-transfer-5.blog as a contributor initially. I then changed the account to an admin, which is reflected in People and wp-admin, but Network Admin Edit Site lists the "WP.com Stats Role" as "Subscriber" versus "Administrator" for other admins on the site and the blog report card lists the role for krisk87 as contributor (the original role) rather than the new role of administrator. As the Calypso screenshot above shows the user then only has access to Blog Posts, versus all site options. 

On a live Jetpack site I did the reverse, adding a user as an admin and then downgrading them to contributor and their Calypso interface continues to show Settings, Plugins, etc. that they do not have the proper role to access.

**Comment by kriskarkoski** [comment]
cc @lezama per Bob's recommendation

**Comment by lezama** [comment]
@gititon @roccotripaldi, could you take a look at this?

**Comment by roccotripaldi** [comment]
Started a Jetpack PR to fix. Take a peek when you have a chance.
