### ISSUE TITLE
Notices: switch to Gridicons

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#145]
I've already swapped the dismiss 'X' and the arrow-link arrow for gridicons. In order to swap out the type (success, error, warning, info (and any others we want to add like update)) icon we need to add a switch or case statement to `notices/notice.jsx` that spits out the correct type into the Gridicon component. Right now we just use a before element styled off of a `.is-type` wrapping class, which will no longer do. 

Currently w/ nasty noticons:
![image](https://cloud.githubusercontent.com/assets/7233112/11254583/99791864-8e0f-11e5-9b46-9c484edc5aa8.png)

**Comment by rickybanister** [comment]
@mtias tackled this in #1368
