### ISSUE TITLE
Login: Add support to other languages to Login page

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14506]
It looks like we completely missed i18n support for all login pages.

From @yoavf's comment in #14088:

> 1. Show a locale suggestions box:
> <img width="645" alt="screen shot 2017-05-25 at 13 38 55" src="https://cloud.githubusercontent.com/assets/844866/26447276/7a6fe290-4150-11e7-92d7-01df831f5c3f.png">
> 
> 2. Use the `locale` value: there's a good example for that here: https://github.com/Automattic/wp-calypso/commit/ee18371f6d24c5f74de789a5a2fb60064b44cdb7 - the parts where the locale part is parsed and retrieved is pretty obvious, I think the actual localization happens with a middleware, but I'm not sure how this is setup. Ping @gziolo who'd probably know more about that part.
> 
> FWIW this should also be applied to `/login`

**Comment by fabianapsimoes** [comment]
OK, it seems this is mostly related to the language suggestions component, not general i18n support. I'm renaming this issue so it doesn't sound as scary as "complete lack of i18n support" :)

**Comment by gziolo** [comment]
For logged out users, we will always serve `en`. We don't support something like:
https://pl.wordpress.com/wp-login.php to display polish language.

**Comment by fabianapsimoes** [comment]
Aha! I'll re-rename the issue :P

**Comment by fabianapsimoes** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/14806.
