### ISSUE TITLE
Post Editor: Excerpt is present even if the post we copy from doesn't have one

### ISSUE THREAD

**Issue by nb** [Automattic/wp-calypso#14507]
#### Steps to reproduce
1. Find a post without an excerpt.
2. Confirm in the post editor that the Except field is empty in the Post Settings sidebar.
3. [Copy this post.](https://github.com/Automattic/wp-calypso/pull/7451) Either start a new one and click Select a Post to Copy from the sidebar or in the post list view click More and  then Copy.
4. See the value of the Excerpt field for the newly created draft.

#### What I expected

I expected the field to be empty.

#### What happened instead

The field was not empty, there was some excerpt there, probably the automatically generated one.

#### Impact

On the surface this looks almost harmless, but I’ve been copying posts for my team’s bi-weekly updates for months and I now noticed they all have the same excerpt – that of a post from late December 2016. It was just carried over and over again.

#dogfooding

Props @yoavf, cc @Copons.

**Comment by Copons** [comment]
Could reproduce (dang @yoavf, you got some crazy 👀!), working on a fix asap.

**Comment by nb** [comment]
@Copons changing the context of the request should do the trick.
