### ISSUE TITLE
Signup: Detect langague based on browser settings

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#14508]
Following up from https://github.com/Automattic/wp-calypso/pull/14088, we should show the signup flow in the language that the user has set in their browser defaults. Right now it defaults to English

#### Steps to reproduce
2. Set your browser language settings to have another language as the first preference (not English)
3. Open https://wordpress.com/start in an incognito window

#### What I expected
The signup flow should show in my selected langage

#### What happened instead
The signup flow showed in English

#### Browser / OS version
Chrome / OSX

**Comment by rachelmcr** [comment]
I reproduced this issue in Firefox 54.0.1 and Chrome 60.0.3112.90 on Mac OSX 10.12.6, with my primary browser language as Spanish (also reproduced after removing all languages other than Spanish). I do get the nudge to switch to Spanish:

![screen shot 2017-08-15 at 12 16 36 pm](https://user-images.githubusercontent.com/8658164/29314082-4abdff6a-81b4-11e7-97ff-6ad67aac22e5.png)

If I visit https://wordpress.com/ directly, I do get the homepage in Spanish and am then directed to the Spanish signup flow at https://wordpress.com/start/es?ref=homepage, but I'd expect the signup flow to be offered in my browser's primary language first and only show the nudges for secondary languages.

If the browser has multiple languages set, this may require API changes to make sure we're retaining the language weighting as set in the browser (internal ref: 7604-wpcom).

**Comment by ramonjd** [comment]
@scruffian @rachelmcr Stab at a quick win at #21138

**Comment by ramonjd** [comment]
Fixed in #21138
