### ISSUE TITLE
Jetpack Contact Form: add message to explain how to use the Contact Form feature

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#14511]
The Contact Form module is one of the Jetpack's auto-activated features. As a result, as soon as you connect the plugin to your WordPress.com account a new menu item appears in your sidebar:

![screenshot 2017-05-26 at 14 50 34](https://cloud.githubusercontent.com/assets/426388/26495173/b5bc7b9c-4222-11e7-9003-9e6ad18d5dad.png)

That menu doesn't say much though; it's empty, it's full of buttons that don't apply to you (Add, Scheduled, Draft, Add New Post), and "Contact Form" isn't mentioned anywhere.
Maybe we should display a message at the top of this page explaining how to use the feature.

Related:
- https://github.com/Automattic/jetpack/issues/7245
- #11115

**Comment by beaulebens** [comment]
An interesting flow here might be that you click that "Add New Post" button, and we use a special URL within Calypso to force trigger a 1-step Guided Tour, that would just highlight where in the UI you can find the Contact Form button, and how it works (or maybe it could walk you through creating your first one?)

**Comment by drw158** [comment]
Also noting that the "Add New Post" button doesn't make any sense to me.

**Comment by beaulebens** [comment]
I'm pretty sure this is just using the default Custom Post Type handling in Calypso, which is pretty minimal. If we want to have some feature-specific handling, we'll need to deviate from that.

**Comment by jeffgolenski** [comment]
As a start, perhaps we can begin with something like this explaining how to begin collecting feedback.

<img width="991" alt="screen shot 2018-02-28 at 1 14 23 pm" src="https://user-images.githubusercontent.com/214813/36804691-57a707ba-1c89-11e8-95b6-ffe4e67a5b20.png">


We can remove the "add new post" button and the section nav at the top. Inside the newly added text will be a link to the list of their posts, and the list of their pages. The "learn more" link would take them to the documentation. 

For a second iteration we could think about adding a guided tour that'll bring them and show them how to add a contact form

**Comment by ockham** [comment]
The tricky part here is that right now, we auto-generate pretty much the same UI for all of our supported CPTs. Adding special cases to include a different UI for the 'Feedback' CPT might be non-trivial. I'll give this some more thought.

**Comment by arunsathiya** [comment]
Related: https://github.com/Automattic/wp-calypso/pull/30799 With this PR, the feedback section on Calypso sidebar takes one to the matching wp-admin path instead.

**Comment by alaczek** [comment]
I wonder if this is still an issue, since Feedback section now links to Calypso-ified wp-admin page?

**Comment by arunsathiya** [comment]
Yup, from what I see, this issue can be closed. Another issue around feedback - https://github.com/Automattic/wp-calypso/issues/27774
