### ISSUE TITLE
API calls for posts and pages using domain instead of site id

### ISSUE THREAD

**Issue by priscillamc** [Automattic/wp-calypso#1453]
In the interface, the Blog Posts and Pages pages display  "You haven't published any posts/pages yet." even though there are public posts and pages in may site that show up in my admin dashboard. 

New posts and page created in the interface show up only in the site's admin dashboard. Here are details about the site:

* Self-hosted single installation of WordPress 4.4
* Jetpack is connected to my WordPress.com account
* Jetpack's Manage and JSON API are active

Possible Cause: 

Looking at the API calls in the WordPress.com page for Blog Posts, the ones using my domain as the site id return an error message 'unknown_blog':

https://public-api.wordpress.com/rest/v1.1/sites/priscillachapman.com/posts

The ones using the site id and the old domain work as expected:

https://public-api.wordpress.com/rest/v1.1/sites/63169444/posts
https://public-api.wordpress.com/rest/v1.1/sites/www.priscillachapman.com/posts

**Comment by lancewillett** [comment]
CC @jeherve Can you take a look?

**Comment by jeherve** [comment]
I've made some changes to your Jetpack settings on our end, and you should be all set.

In the future, if you run into such issues again, I'd recommend following these instructions:

1. Go the Jetpack menu in your dashboard
2. Click on "My Jetpack" at the top of the page.
3. Click on "Disconnect Site from WordPress.com" if your site is currently connected to WordPress.com.
4. Confirm the disconnection.
5. Click on the Connect button to connect your site to WordPress.com again.

If that doesn't fix it, you can contact us directly via [this contact form](http://jetpack.me/contact-support/) and we'll look into your Jetpack settings and fix things for you!

**Comment by priscillamc** [comment]
Thanks! Everything's working now.
