### ISSUE TITLE
Email verification action is incorrectly sent after success in data layer

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#14538]
@dmsnell I was testing some stuff, and noticed that the `EMAIL_VERIFY_REQUEST` is dispatched three times instead of once after merging in https://github.com/Automattic/wp-calypso/pull/14354

The first duplicate dispatch is due to not having an `inProgress` handler.

I couldn't see why the second incorrect dispatch happens, though - it happens after `EMAIL_VERIFY_SUCCESS` is dispatched.

You can see the erroneous behaviour by logging in as an unverified user, going to publish a new post, and using the email verification feature there:

<img width="870" alt="screen shot 2017-05-27 at 1 47 14 pm" src="https://cloud.githubusercontent.com/assets/11487924/26523316/2228f45c-42e3-11e7-98a7-90304604c395.png">

**Comment by dmsnell** [comment]
@v18 I'm not following what `onProgress` has to do with it.

Note too that we're removing `next()` from the data layer API in #14025 and #14354 and #14299 

I'm not in a good position to test at the moment. Did you inspect the `meta` on those actions? It may not all be entirely unexpected.

**Comment by v18** [comment]
This was fixed a while ago, but I never got to closing it.
