### ISSUE TITLE
Customizer: Does not work for AT sites 

### ISSUE THREAD

**Issue by htdat** [Automattic/wp-calypso#14565]
#### Steps to reproduce
1. Create an AT site. E.g: mysite.blog
2. Try to access the Customizer on Calypso https://wordpress.com/customize/mysite.blog
3. I get this error *Sorry, the customizing tools did not load correctly*
4. Check the console log, there is an error. 
```
Refused to display 'https://mysite.blog/wp-admin/customize.php?return=https%3A%2F%2Fwordpress…ypso=true&calypsoOrigin=https%3A%2F%2Fwordpress.com&frame-nonce=8167bd4396' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
mysite.blog/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fs…ypso=true&calypsoOrigin=https%3A%2F%2Fwordpress.com&frame-nonce=8167bd4396 Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
```

#### What I expected

I can see the Customizer. 

#### What happened instead

I get this error *Sorry, the customizing tools did not load correctly*

#### Browser / OS version

I am using Mac on Chrome.

#### Screenshot / Video

![screenshot_2017-05-30__15-34-33_edit](https://cloud.githubusercontent.com/assets/10045087/26576171/16e3425c-4552-11e7-8ada-f8fa254cb2c7.png)

#### Context / Source

* This is reported from an user on 414465-hc. 
* I myself and another HE can see it as well.

**Comment by designsimply** [comment]
Tested and confirmed using a Jetpack site:

1. Go to https://wordpress.com/customize
1. Select a Jetpack site.
1. Check to see if the customizer loads properly.

<strong>Result:</strong> saw the following error:

```
Sorry, the customizing tools did not load correctly
```

![screen shot 2017-06-20 at tue jun 20 4 17 12 pm](https://user-images.githubusercontent.com/1119271/27358451-efad710c-55d3-11e7-986e-5fa6f57d3844.png)
<sup>Seen at https://wordpress.com/customize/alittletestblog.com using Firefox 54.0 on Mac OS X 10.12.5

I saw a different error in the console:

```
Blocked loading mixed active content “http://alittletestblog.com/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fstats%2Falittletestblog.com&calypso=true&calypsoOrigin=https%3A%2F%2Fwordpress.com&frame-nonce=92027d099f”
vendor.eb47d1859abc6d92091d.m.js:5:943
```

Tested with Safari 10.1.1 on Mac OS X 10.12.5.

**Comment by sirbrillig** [comment]
Jetpack (and thus AT) sites should not try to load the customizer inside Calypso. The "customize" link in the Calypso sidebar should open a new window.

If you enter the customize link directly, it definitely will not load. Maybe there should be a redirect to the site's customizer in that case?

**Comment by designsimply** [comment]
> Maybe there should be a redirect to the site's customizer in that case?

@sirbrillig, I feel that makes a lot of sense for this flow:

1. Go to https://wordpress.com/customize
1. Select a Jetpack site.
1. Check to see if the customizer loads properly.

**Comment by sirbrillig** [comment]
We'd just need to add a check inside the calypso customize component for a jetpack site and add a URL redirect if that's the case. I started a PR in https://github.com/Automattic/wp-calypso/pull/15998 to try that out.

**Comment by designsimply** [comment]
Circled back to test with my Jetpack site post-merge and the redirect worked properly this time using the same steps I tested with before:

1. Go to https://wordpress.com/customize
1. Select a Jetpack site.
1. Check to see if the customizer loads properly.

Thank you! 👍
