### ISSUE TITLE
Editor: Pasting into a selection removes prepended space

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#14579]
#### Steps to reproduce
1. write a bulleted list of sentences such as:
 - I did this Sunday
 - I did this Sunday
 - I did this Sunday
2. Change the last word of the first item to Yesterday such that it reads:
 - I did this Yesterday
 - I did this Sunday
 - I did this Sunday
3. Copy "Yesterday"
4. Select a just the word "Sunday" and paste
5. End up with:
 - I did this Yesterday
 - I did thisYesterday
 - I did thisYesterday

#### What I expected
Just the word get replaced

#### What happened instead
The word plus the space gets replaced

#### Browser / OS version
Chrome on OSX

#### Screenshot / Video
![wp](https://cloud.githubusercontent.com/assets/1883296/26582764/4f8c7980-4510-11e7-9789-19c8f12adfd7.gif)

**Comment by folletto** [comment]
Confirmed.

Happens too in TinyMCE on WordPress Core Editor v4.7.5.

**Comment by rachelmcr** [comment]
Closing as this will be superseded by Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
