### ISSUE TITLE
Editor: can't open shortcuts menu with Control-Option-H as expected

### ISSUE THREAD

**Issue by DigitalDavo** [Automattic/wp-calypso#1457]
I was expecting the Keyboard Shortcuts to show when I hit Shift + ALT + h, as suggested in the actual popup that does work (via ? icon) but nothing happens.

BTW could the keyboard shortcuts be ALT + key rather than ALT + SHIFT + key ? why do we need to hold down 3 keys?

Windows Desktop v1.1.1

**Comment by lancewillett** [comment]
Thanks for the report, DigitalDavo .

**Comment by lancewillett** [comment]
Looking at this again — I don't think either the Mac or Desktop apps have keyboard shortcuts enabled yet. We'll consider it as a future improvement, though.

**Comment by DigitalDavo** [comment]
Actually almost all of the keyboard shortcuts do indeed work on both platforms, that was what motivated me to raise the bug as it looked out of place. I didn't try them all, but all the dozen I tried did.

**Comment by lancewillett** [comment]
Just to be clear, are you using desktop apps or Calypso in a web browser?

**Comment by DigitalDavo** [comment]
the windows desktop version of wordpress.com,exe  v 1.1.3 beta, and the desktop version of osx too.


[2015-12-15_12-18-00](https://cloud.githubusercontent.com/assets/3273790/11801989/3037ce14-a326-11e5-94a5-41c11b14af93.png)

**Comment by lancewillett** [comment]
Oh!! The editor keyboard shortcuts. I was confused and thinking you meant WordPress.com keyboard shortcuts as a whole.

<img width="712" alt="screen shot 2015-12-17 at 11 17 17" src="https://cloud.githubusercontent.com/assets/66797/11877956/ce73bd1a-a4af-11e5-8e41-4ca7df1c997e.png">

This is more clear now. :)

**Comment by lancewillett** [comment]
I tested all the rest of the Editor keyboard shortcuts, and found that two others are not working:

`a	Insert/edit link`
`m	Insert/edit image`

**Comment by lancewillett** [comment]
Thanks again, DigitalDavo, for this report.
