### ISSUE TITLE
DevDocs: Blocks page will always scroll to the Login block

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#14583]
Loading https://wpcalypso.wordpress.com/devdocs/blocks scrolls the user always to the `<Login />` block example, in contrary to the expected behavior (being dropped at the top of the page).

It appears that this is caused by a `window.scrollTo` in the main `Login` component. We might want to reconsider this usage - could it cause inconveniences in other cases?

/cc @stephanethomas

**Comment by fabianapsimoes** [comment]
@tyxla I can no longer reproduce this, so closing. Feel free to reopen if I'm missing anything.

**Comment by tyxla** [comment]
This appears to have been fixed by #15988. Thanks for cleaning up @fabianapsimoes!
