### ISSUE TITLE
DevDocs: CommentDetail block missing details

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#14581]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/comment-detail
2. Observe

#### What I expected
To see comment details like this (previous screenshot):

<img width="780" alt="screen shot 2017-05-30 at 9 11 14 am" src="https://cloud.githubusercontent.com/assets/7233112/26584769/fd1d4e06-4517-11e7-9536-4f4828f64dce.png">

#### What happened instead
Empty details (current screenshot):

<img width="776" alt="screen shot 2017-05-30 at 9 11 18 am" src="https://cloud.githubusercontent.com/assets/7233112/26584775/025ab87c-4518-11e7-913b-c0f97d5a8873.png">

Likely due to PR #14510, which makes it sound like it's not a functional bug but just a missing update to DevDocs - cc @Copons 

#### Browser / OS version
Seen here in OSX Firefox

#### Context / Source
#automated-testing #visdiff

**Comment by Copons** [comment]
Dang @hoverduck, great catch, I totally forgot about the docs. ☹️

**Comment by Copons** [comment]
Update: I'm temporarily removing `CommentDetail` from the docs in https://github.com/Automattic/wp-calypso/pull/14555 because we're working on a more sophisticated solution.
I'll keep this issue open for tracking purposes.
