### ISSUE TITLE
Framework: Fragile Unit Tests

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#1459]
Some tests fail from time to time on CircleCI. Examples below:

![screen shot 2015-12-04 at 11 03 08](https://cloud.githubusercontent.com/assets/699132/11709223/1e1656e2-9f16-11e5-9b93-92fbe49e7531.png)

![screen shot 2015-12-10 at 08 10 36](https://cloud.githubusercontent.com/assets/699132/11709220/162ec69e-9f16-11e5-878c-a3e42e3a9341.png)

We should make sure we add only predictable tests to the CircleCI test suite.

**Comment by lancewillett** [comment]
This seems like too broad a task for a GitHub issue. Feel free to re-open, but I think efforts to fix tests have happened since December 2015.

**Comment by gziolo** [comment]
Yes, it shouldn't be an issue anymore.
