### ISSUE TITLE
Sites: site name is clipped on My Sites page

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#146]
My site starts with a `j`, and the italicised name is slightly clipped on My Sites:

![image](https://cloud.githubusercontent.com/assets/7233112/11254751/77f3a0fa-8e10-11e5-9ada-c0de438a1ebf.png)

**Comment by lancewillett** [comment]
This should no longer be a bug — the domain in the second line isn't italicized any more.

<img width="534" alt="screen shot 2017-05-03 at 15 28 57" src="https://cloud.githubusercontent.com/assets/66797/25684283/48759470-3015-11e7-9692-9d8ab8a0a136.png">
