### ISSUE TITLE
WooCommerce: Previous product populates fields on /add after navigating away and back

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14609]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/products/:site/add
2. Give the product a name and description
3. Hit Save
4. Click on Settings in the sidebar (to go to /store/settings/:site)
5. Click on the Add button next to Products in the sidebar (to go to /store/products/:site/add ) i.e. to add another product

#### What I expected
I kinda expected the URL to update with the product ID after creating it, but I especially did not expect the previously added product's data to continue to be present in the form when i entered the "add" flow again.

#### What happened instead

The previously added product's data was still present in the form when i entered the "add" flow again

**Comment by kellychoffman** [comment]
Can confirm this is still happening. cc @coderkevin in case it will be solved with one of the currently open PRs.

**Comment by coderkevin** [comment]
This should be fixed by now. @kellychoffman or @allendav can you confirm?

**Comment by kellychoffman** [comment]
This is fixed!
