### ISSUE TITLE
How do I disable the WordPress.com redirect when Calypso is first deployed?

### ISSUE THREAD

**Issue by trentlapinski** [Automattic/wp-calypso#1460]
First and foremost, I'm a totally new to JS, so please excuse my ignorance I'm still learning how everything works. I know HTML/CSS/PHP/MySQL pretty well, but Javascript / Node.js is new to me.

Anyhow, I'm working on a solution using http://wpdocker.com to be able to deploy custom instances of Calypso using docker containers. I'm working with a team of amazing devops to be able to pull this off, so I can't take all the credit. We've got everything working on our deployment saas platform but the client automatically redirects to WordPress.com and doesn't appear to be loading locally off my docker container instance.

I'm assuming this is a config file issue, right now we're launching the app in development mode which I'm assuming is config/development.json. Around line 22 is:
"login_url": "https://wordpress.com/wp-login.php", "logout_url": "https://wordpress.com/wp-login.php?action=logout&redirect_to=https%3A%2F%2F%7Csubdomain%7Cwordpress.com",
However, the Mac app config uses:
"login_url": "/login", "logout_url": "/logout”,

I'm wondering if I just swap the login types to be the same as the Mac app config that will force the app to load the login screen locally instead of redirecting to WordPress.com? Or I am I totally off and theres some other file I'm missing that dictates this redirect?

To see this in action visit: https://ctest-trent.staging.str5.net

Any thoughts? Again the end goal here is to disable the direct, I'm sure the login process will still require some kind of authentication with WordPress.com, but I want the actual login screen to be loading off my docker instance, and not just redirecting.

P.S. My plan is most likely to turn this into a developer tool and release it for free to the WP community. I'm hoping it will enable WP devs to be able to 1-click deploy Calypso into the cloud and experiment with custom implementations. Then a developer can test their code live in their browser on an optimized cloud tech stack to our cloud plumbing and push it into a staging or production site for deployment to show it to others and get feedback. Still thinking of different use cases, but I think this could open the door to a new class of WordPress / Calypso powered SaaS apps. Could also open the door to getting Calypso working with self installed WordPress by creating a custom Calypso cloud install configured directly to a self host install.

**Comment by lancewillett** [comment]
While we'd love to see what folks come up with in the future, Calypso is a client built specifically for the WordPress.com REST API so we can't offer help or advice on other uses.
