### ISSUE TITLE
Editor: when prefilling title via the query string, title appears only after first autosave

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#14627]
When pre-filling the title in a new post from the query string, like we do from Reader Share, e.g.:

http://calypso.localhost:3000/post/1606950?title=Spotlight%3A%20Sharon%20Kendrick%20%E2%80%94%20Just%20Reviews&text=&url=https%3A%2F%2Ftillie49.wordpress.com%2F2017%2F05%2F30%2Fspotlight-sharon-kendrick%2F

...the title does not currently appear in the title input straight away. It does show up immediately after the first autosave, when the post becomes a draft.

**Comment by rachelmcr** [comment]
Confirmed this is still an issue.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by bluefuton** [comment]
Re-tested - appears to now be resolved.
