### ISSUE TITLE
Sharing: google-plus republicize shares not working

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#14632]
I've tested this in production. I have google plus connected as a sharing connection. I tried to republicize with google plus, it looked good, the endpoint responded with a success, but nothing goes out to my profile.

I've tested this using re-publicize, haven't tested regular publicize (which happens when publishing), nor have I tested other services.

**Comment by lancewillett** [comment]
Removing the High label since no action on this since May — could be a comment about Google+ or our own attention to GitHub — will not comment on that further. :)

I'll take a stab at re-testing this flow to see if it is still as described.

**Comment by lancewillett** [comment]
Closing as this feature seems to be working as expected.

![screen shot 2017-09-29 at 17 19 06](https://user-images.githubusercontent.com/66797/31040300-77a63548-a53a-11e7-8040-00ea0431f4ca.png)
<img width="790" alt="screen shot 2017-09-29 at 17 19 11" src="https://user-images.githubusercontent.com/66797/31040298-77a20996-a53a-11e7-88d4-8f98c88cad37.png">
<img width="780" alt="screen shot 2017-09-29 at 17 19 28" src="https://user-images.githubusercontent.com/66797/31040299-77a581b6-a53a-11e7-8613-3257bbb7574b.png">
<img width="500" alt="screen shot 2017-09-29 at 17 19 38" src="https://user-images.githubusercontent.com/66797/31040297-779fbf60-a53a-11e7-82df-5efda66a51e6.png">
