### ISSUE TITLE
Plans: Don't display stale data in `PlanOverview`

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1465]
Reported by @fabianapsimoes [here](https://github.com/Automattic/wp-calypso/pull/1395#issuecomment-163414012):

> - Right after signup, this first loads the regular version of plans, and then replaces it with the trial version. Can we load the trial version right away?

> ![domain](https://cloud.githubusercontent.com/assets/1248436/11700393/872f5f5e-9e97-11e5-9263-cbbbc42bd04d.gif)

> - If I remove the trial sub from the admin tools, `/plans` still displays the plan as being active (but in full subscription mode). This changes after a minute or two to the correct state. Here's an example from a Premium trial subscription removed:

> ![screenshot-calypso localhost 3000 2015-12-09 17-06-22](https://cloud.githubusercontent.com/assets/1248436/11700439/d2ae6808-9e97-11e5-9009-db5a9651e667.png)

**Comment by breezyskies** [comment]
Just a note that we should also probably change the sidebar label from "Free" to "Trial" / "Premium Trial" or similar. cc @mikeshelton1503

**Comment by mikeshelton1503** [comment]
> Just a note that we should also probably change the sidebar label from "Free" to "Trial" / "Premium Trial" or similar.

Agreed. Let's do `Trial`, it's shorter.

**Comment by drewblaisdell** [comment]
> Just a note that we should also probably change the sidebar label from "Free" to "Trial" / "Premium Trial" or similar.

I opened an issue for this: #1659
