### ISSUE TITLE
Activity Log/Rewind: First backup email

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#14666]
Once we’ve completed the first backup, we fire up user notifications: an onboarding email, WP.com notification, and mobile notification.

## Default version (credentials working)

This is a modification to a preexisting email. We should simply modify the template and let it fire off normally without changing the timing.

**Subject line:** Welcome to Jetpack Premium. Here is what you need to know.

![onboarding email](https://user-images.githubusercontent.com/1123119/32570441-5a268a48-c481-11e7-92d9-8fe569c12254.jpg)

The Tour to action button should take the user to Calypso and start the tour.

## Alternate version (credentials missing or not working)

![onboarding email - no credentials](https://user-images.githubusercontent.com/1123119/32570497-809bba2c-c481-11e7-8b5f-23897fff7eef.jpg)

The Credentials button should take the user to the credentials settings in Calypso Settings.

**Comment by bubel** [comment]
I have an initial version of this email set up and working using the copy in this mock. A few questions to flesh this out a bit further:

* Where is the CTA pointing? Where is the 'Activity Stream' link pointing?
* If someone could provide me with a screenshot of the interface filled with actual activity for use in the email, that would be good.
* If we were to send this email after the first backup is created, generally, how long will that take after purchase? We have an onboarding email campaign in place for all paid subscriptions, and ideally, we figure out where this fits within the current structure.
* Where, in code, is the first backup event triggered (i.e. where would we need to add code to schedule this email?)?

cc @MichaelArestad

**Comment by MichaelArestad** [comment]
> Where is the CTA pointing? Where is the 'Activity Stream' link pointing?

@bubel The CTA is pointing to the Activity Log within Calypso. It looks like `https://wordpress.com/stats/activity/michael.blog`

> If someone could provide me with a screenshot of the interface filled with actual activity for use in the email, that would be good.

Will definitely do as it gets finalized. There are still quite a few visual tweaks to be done

> If we were to send this email after the first backup is created, generally, how long will that take after purchase? We have an onboarding email campaign in place for all paid subscriptions, and ideally, we figure out where this fits within the current structure.

That's a good question. Unfortunately, it depends on the site. @thingalon can probably give you a better estimate of how long it takes for most sites.

> Where, in code, is the first backup event triggered (i.e. where would we need to add code to schedule this email?)?

@singerb @roccotripaldi or @dmsnell might better be able to answer this.


#### Updated mockup

![step 4 - onboard email](https://user-images.githubusercontent.com/1123119/31563607-07fbcb20-b01d-11e7-8157-8ccac71555cf.png)

**Comment by singerb** [comment]
Ideally this would be triggered by the first `backup_complete` event appearing in the AL, which would be the reliable way to do this. The first backup itself will take a bit longer since we'll need to get everything, but should still only be a couple minutes for most sites. Larger sites will get into the hour(s) range.

**Comment by MichaelArestad** [comment]
Updated the initial issue with latest mockup, copy, and subject line. I removed a screenshot for now until the dust settles a bit on the UI or until we can get the UI to the point where it matches mockups.

**Comment by MichaelArestad** [comment]
Updated to reuse a preexisting email and have an alternate for credentials. :boom:

**Comment by enejb** [comment]
@MichaelArestad Where can I find the graphic for this? That comes in the emails.

**Comment by MichaelArestad** [comment]
[SVGS](https://cloudup.com/cMvY6kgRhHn) and [PNGs](https://cloudup.com/cs0bbznnkAK)

**Comment by enejb** [comment]
Thank you

**Comment by enejb** [comment]
@MichaelArestad. I am only looking at the first screenshot email. As something we send out to the user when the initial backup is completed. Would the list of things that the user has access to be something that is dynamically generated. So when we add new items to the plan or just hard coded for each plan? Do we have the list of features of each plan somewhere already?

@singerb When would the second email be sent out?

**Comment by singerb** [comment]
@MichaelArestad are these designed to be sent at a scheduled time, or should the first one be sent once the first backup is made? If the latter, then when do we send the second one? If the former, then what's that time.

**Comment by MichaelArestad** [comment]
> As something we send out to the user when the initial backup is completed. Would the list of things that the user has access to be something that is dynamically generated. So when we add new items to the plan or just hard coded for each plan? Do we have the list of features of each plan somewhere already?

@enejb It would not be dynamically generated. This email specifically focuses on security things which are in every plan (that I'm aware of).

**Comment by MichaelArestad** [comment]
@singerb This email is an iteration on an existing email that I think goes out on day three. We are updating it's content.

**Comment by singerb** [comment]
@enejb see above re: scheduling. Sounds like we might not need the initial backup complete event then, and just query the AL at sending time to see if they have backups yet or not.

**Comment by enejb** [comment]
Just to confirm. 

We don't send out this email right after the first back up is made or in 3 days after they signed up?

**Comment by enejb** [comment]
This is done with this D8424-code.
