### ISSUE TITLE
Activity Log/Rewind: First backup notification

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#14667]
Once we’ve completed the first backup, we fire up user notifications: an onboarding email, WP.com notification, and mobile notification.

![first backup complete](https://user-images.githubusercontent.com/1123119/32862410-4504843c-ca15-11e7-9c4d-c6883d261856.jpg)

* The link to the Activity log should take the user to the Activity log and kick off the tour.

Plaintext for the lovely folks implementing this:

> Jetpack backed up The Great Mandala

> You can now roll back accidental changes or recover from data loss.

----

> Your site The Great Mandala is safe with Jetpack.

> We’ve got a full backup of your site, and will continue to create daily backups automatically.

> To see your backups, visit the Activity Stream. This is where you’ll find all of the events that have taken place on your site, and can restore it to any previous state in just a few clicks.

**Comment by MichaelArestad** [comment]
Updated mockup and copy in original issue.

**Comment by samhotchkiss** [comment]
Done
