### ISSUE TITLE
Activity Log/Rewind: Site Restored email notification

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#14670]
Once the backup is restored, we fire a new email with the good news. 

**Subject line:** <Site name> has been successfully rewound

![rewind complete](https://user-images.githubusercontent.com/1123119/32468489-ba0d9de2-c30b-11e7-8256-9d45b7d5ed2d.jpg)

**Comment by MichaelArestad** [comment]
Updated mockup and added email subject line/

**Comment by samhotchkiss** [comment]
This is done
