### ISSUE TITLE
Fullpost Visit Site Link Misaligned

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14687]
On the fullpost page, the "Visit Site" link at the top right is pushed outside the width of the page in Safari.

<img width="259" alt="screen shot 2017-06-01 at 11 33 35 am" src="https://cloud.githubusercontent.com/assets/24388/26695013/2e421b68-46be-11e7-9010-8425e5ec815b.png">

cc @jancavan

**Comment by jancavan** [comment]
Hmm, this is odd. I'm unable to repro this @fraying in Safari 10.0. What version are you using?

**Comment by fraying** [comment]
@jancavan 10.1.1 ... but now I'm not seeing it anymore. Huh. Closing....
