### ISSUE TITLE
Reader: Add main menu to go back to stream list

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14680]
As discussed in https://github.com/Automattic/wp-calypso/issues/14079#issuecomment-302523622.

/cc @fraying

**Comment by bluefuton** [comment]
@jancavan does this replacing the current `< Streams` header with a hamburger icon? 

Is this still something we want to do?

**Comment by jancavan** [comment]
@bluefuton I think we can close this for now.
