### ISSUE TITLE
Jetpack Connection: cannot connect after logging in with existing account

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#14683]
#### Steps to reproduce
1. Starting in wp-admin, on a new site where Jetpack is installed and activated. You should be logged out of WordPress.com.
2. Click on the Connect button.
3. You're redirected to the connect page on WordPress.com, with a sign up form.
4. Enter the email address linked to your WordPress.com account in the sign up form.
5. An invitation to log in appears:
![screenshot 2017-06-01 at 19 46 32](https://cloud.githubusercontent.com/assets/426388/26693020/0a09a6ea-4703-11e7-872d-2f26b7111bb2.png)
6. Click on the link. You're redirected to a log in form:
`https://wordpress.com/wp-login.php?redirect_to=https%3A%2F%2Fwordpress.com%2Fjetpack%2Fconnect%2Fauthorize&email_address=email%40example.com`
7. Log in. You're redirected to the following URL:
`https://wordpress.com/jetpack/connect/authorize?_wp_nonce=xxxxx`
8. The following message appears:

![screenshot 2017-06-01 at 19 48 51](https://cloud.githubusercontent.com/assets/426388/26693120/59c657fa-4703-11e7-9500-ad640ea2509e.png)

9. Clicking on the link redirects you to https://wordpress.com/jetpack/connect and you have to go through the process again.

Reported in p8oabR-3s-p2

**Comment by johnHackworth** [comment]
Ok, after some investigation, this is being caused by a change done a couple of weeks ago in the signup-form component:

https://github.com/Automattic/wp-calypso/commit/1cb63f8711066e080d2fd23ca2290b789b9b0ff2#diff-3438d0da23b3176f5d05d0d0650da6a3L34

Working on a fix
