### ISSUE TITLE
BoingBoing posts have double images on fullpost pages, missing videos

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14686]
BoingBoing is behaving strangely. https://wordpress.com/read/feeds/9166444/posts/1480376980

This post (https://wordpress.com/read/feeds/9166444/posts/1480376980) has the same image twice and is missing the YouTube video from the original post: http://boingboing.net/2017/06/01/watch-mind-blowing-close-up.html

Most of the other recent BB posts have the double image problem, too:
https://wordpress.com/read/feeds/9166444/posts/1480298347
https://wordpress.com/read/feeds/9166444/posts/1480292265
https://wordpress.com/read/feeds/9166444/posts/1480287956
https://wordpress.com/read/feeds/9166444/posts/1480287958

cc @blowery

**Comment by blowery** [comment]
<img width="490" alt="screenshot 2017-06-01 14 40 06" src="https://cloud.githubusercontent.com/assets/14350/26695253/3c03188c-46d8-11e7-951f-327f82ac2ca4.png">

Hrm. The featured image and the image in the content use different hosts, so we see them as different images. Will have to noodle on this one a bit. Maybe we need feed and/or site specific "show the feature" overrides.

**Comment by blowery** [comment]
The missing video is also missing from their RSS feed: https://boingboing.net/feed

Seems like they're suppressing it somehow...

**Comment by blowery** [comment]
Looks better with the shadow copy https://wordpress.com/read/blogs/87954168/posts/526942

**Comment by fraying** [comment]
@blowery Can we do whatever fix we did for the other double-image sites? I think LS?

**Comment by blowery** [comment]
Yup, same solution. Just hide the features.
