### ISSUE TITLE
Plans: Use one file for all variants of plan logos

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#1469]
We've introduced [new variants](https://github.com/Automattic/wp-calypso/tree/master/public/images/plans) of the logos of [Premium](https://github.com/Automattic/wp-calypso/blob/master/public/images/plans/plan-business.svg) and [Business](https://github.com/Automattic/wp-calypso/blob/master/public/images/plans/plan-premium.svg) plans in https://github.com/Automattic/wp-calypso/pull/1395. Right now these are [separate](https://github.com/Automattic/wp-calypso/pull/1395/files#diff-9a040973dabc7d87972026c5216f34a1) [files](https://github.com/Automattic/wp-calypso/pull/1395/files#diff-ade28dfb8b175e8eb7d50ff11411c5b6) whereas we should most certainly use only one SVG file and use CSS to control how the image should look like. This is important considering the number of variants that will have to be implemented since this will reduce the amount of data to download:

**Comment by mikeshelton1503** [comment]
This is not official but here is an example of possible variants we may use in the future: 
![image](https://cloud.githubusercontent.com/assets/12596797/11721045/db3b9688-9f2f-11e5-9afb-2f415f23bfe0.png)
