### ISSUE TITLE
Rewind: Need to be able to fetch the progress of restores

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#14693]
The VaultPress API has an endpoint that we can query via `site_get_restore_status()`, however we need to add a wpcom endpoint to access this, and a data-layer object to fetch it.  

This same endpoint will also be returning the successes/failures of the restores, so this is pretty much a blocker for making #14664 functional.

**Comment by dereksmart** [comment]
Relying on this endpoint to merge into wpcom D5890-code

**Comment by sirreal** [comment]
After chat (p1HpG7-44C-p2), this was excluded from initial MVP due to time constraints. Is that correct @dereksmart?

**Comment by sirreal** [comment]
Fixed by #15363
