### ISSUE TITLE
Search on Manage: remove unhelpful error

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14696]
<img width="771" alt="screen shot 2017-06-01 at 2 49 00 pm" src="https://cloud.githubusercontent.com/assets/24388/26702368/8b4aa6c0-46d9-11e7-9b40-1d7d5efcf01c.png">

When a user searches for a URL, and we don't have it in the index, we show this error. We shouldn't be doing that. I suggest we remove this error state.

Why: In this case, the user knows the URL of the site they want to follow. It doesn't matter if it's in our index or not. Visually, this looks like an error has occurred, but it hasn't. We just don't know about the site yet.

When the user submits the form, one of two things will happen:

1. The follow will go through successfully, in which case the user didn't need to know it wasn't in the index. The error is just a potential disruption in the flow.

2. The follow will fail, in which case we'll notify the user. That's the appropriate place to get wordy. (We may want to rewrite that error in a separate PR.)

Either way, we don't need to tell them the URL is not in our index beforehand, and doing so may actually discourage people from attempting the follow, so we should remove this error.

Make sense?

cc @jancavan

**Comment by samouri** [comment]
implemented in 13716

**Comment by fraying** [comment]
Thanks, @samouri
