### ISSUE TITLE
Manage Button

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14690]
<img width="744" alt="screen shot 2017-06-01 at 12 18 44 pm" src="https://cloud.githubusercontent.com/assets/24388/26696771/a46c8f2a-46c4-11e7-88c3-17145d08f8ba.png">

I think, back when this was at /following/edit, the "Manage" button turned blue when you were on the Manage page. (Same blue as the "you are here" blue color of the "Reader" background.)

Am I crazy, @jancavan?

**Comment by jancavan** [comment]
I also don't recall 🤔  But I do think that something changed with the button when you're on that page.

**Comment by samouri** [comment]
I went back in time to check! ![](https://cldup.com/aqFooyL0qt.png)

**Comment by fraying** [comment]
@samouri Aha! I wasn't crazy! Well, not about this, anyway.

@jancavan Check it out. Can we reimplement that?

**Comment by bluefuton** [comment]
Good spot @fraying! 

Should just involve changing the path the sidebar requires for the highlight 👍

**Comment by samouri** [comment]
implemented in #14708
