### ISSUE TITLE
Preview & Customizer: display appropriate error message when X-Frame-Options blocks

### ISSUE THREAD

**Issue by ethitter** [Automattic/wp-calypso#14704]
I set `X-Frame-Options: SAMEORIGIN` on my site's front-end (ethitter.com, erick.blog), which breaks the Customizer, preview functionality, and likely other things. The Customizer will eventually time out, but preview does not. In either case, can we detect that loading was blocked for this reason and better handle it?  

#### Steps to reproduce
1. Set `X-Frame-Options: SAMEORIGIN` on a Jetpack-connected site
2. Load the customizer, or preview a post

#### What I expected
Clearer, and more-responsive, messages about why things didn't work.

#### What happened instead
The Customizer eventually displays an error, while the preview just displays an empty frame.

**Comment by ethitter** [comment]
Prompted in part by p8FazZ-1d-p2.

**Comment by ethitter** [comment]
For example, the "Site Preview" feature crashes Calypso with X-Frame-Options set:

![screen shot 2017-06-14 at 09 15 12](https://user-images.githubusercontent.com/321503/27143136-2bc0d41e-50e2-11e7-89de-35212805b9b7.png)

**Comment by mattsherman** [comment]
Split the preview part off into it's own issue: https://github.com/Automattic/wp-calypso/issues/16640

**Comment by lancewillett** [comment]
This is no longer valid; closing.
