### ISSUE TITLE
Login: Obsolete text `Or continue to your account using` when no links

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14712]
<img width="432" alt="screen shot 2017-06-02 at 12 07 24" src="https://cloud.githubusercontent.com/assets/699132/26721445/1ad6da36-478c-11e7-82e2-ad092947e41f.png">

Steps to reproduce:

* Try to log in with an account with sms set as a verification method.
* Wait for the push notification screen.
* Click use text message link instead.
* You should `Or continue to your account using` header and no links below.

**Comment by stephanethomas** [comment]
I think that's a regression introduced in https://github.com/Automattic/wp-calypso/commit/00c1cd9521b30e0d70982eb23256e907433e7734: we should no longer check if push notifications are available [here](https://github.com/Automattic/wp-calypso/blob/42f7dc78de220550453adb2b190c5d03f35643c4/client/blocks/login/two-factor-authentication/two-factor-actions.jsx#L46).
