### ISSUE TITLE
Free Trials: Add Free Trial Hub "Expired" State

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1471]
When a free trial expires we are giving the user a 3 day grace period (up to day 17). During that time we need to adjust the Free Trial Hub to indicate that the trial plan has expired and that their features will be removed.

Here is the desktop layout: 

![image](https://cloud.githubusercontent.com/assets/12596797/11724863/92207288-9f44-11e5-882c-503435c8c7a5.png)

For reference here's what the active trial state looks like for the Free Trial Hub: https://github.com/Automattic/wp-calypso/issues/1151#issuecomment-162624443

- [x] Add expired state to `PlanStatus`
- [x] Add expired state to `PlanFeatures` #1905

cc @danhauk @breezyskies @scruffian @Tug

**Comment by breezyskies** [comment]
Looks great! 

One small copy note: `Theme changes will be lost` reads to me as "setting changes I made to my current theme will be lost" -- I might change this to `Theme will be removed` (or similar), assuming they had chosen a premium theme.

**Comment by mikeshelton1503** [comment]
Forgot to include this:

 - The `Expired today` label in the status box will change to `Expired 1 day ago` then `Expired 2 days ago.
 - The `Plan features will be removed in 3 days` copy in the status box will change to ` [...] removed in 2 days` then ` [...] removed in 1 day`

**Comment by mikeshelton1503** [comment]
> One small copy note: Theme changes will be lost reads to me as "setting changes I made to my current theme will be lost" -- I might change this to Theme will be removed (or similar), assuming they had chosen a premium theme.

My thought was that the most important warning to give the user in this case is "the custom changes will be lost" since you can't get them back. You can always get the theme back (if you pay of course).

However I do agree that also saying the theme will be removed would be helpful, though it's a bit long if we do: `Theme and custom changes will be removed`

**Comment by spncrb** [comment]
> Theme changes will be lost
Can we show no warning if they are using a free theme and a simple warning if they have a premium theme? If so, I think ```Theme will be removed``` that Brie suggested seems cleanest...

**Comment by mikeshelton1503** [comment]
>Can we show no warning if they are using a free theme and a simple warning if they have a premium theme? If so, I think Theme will be removed that Brie suggested seems cleanest...

If they're using a free theme then the `Unlimited Premium Themes` feature should show as `Not in use` so no, no warning will show in that case. However that doesn't change the concern of wanting to warn users that their custom changes to the the Premium theme will be lost.

**Comment by drewblaisdell** [comment]
As of #1820, the `PlanFeatures` are no longer `primary`, so I removed the 'expiring state' checkbox for that component because the expiring state is now the same as the active trial state.

**Comment by drewblaisdell** [comment]
@mikeshelton1503 For v1 of `PlanFeatures`, is there a way we can tweak the design so that we don't need dynamic features? I'm investigating adding that behavior now, but it would be nice to have something in case we don't implement that in the first version.

**Comment by mikeshelton1503** [comment]
> For v1 of PlanFeatures, is there a way we can tweak the design so that we don't need dynamic features?

Yea if we can't do the dynamic features then we could do something like this:

![image](https://cloud.githubusercontent.com/assets/12596797/11911348/955124e0-a5e1-11e5-89ac-1dbbdb6947a9.png)

It moves things around a bit but should be a good compromise for v1. 

cc @breezyskies

**Comment by breezyskies** [comment]
> It moves things around a bit but should be a good compromise for v1.

:+1: Looks good.
