### ISSUE TITLE
WooCommerce: Jetpack default API timeout of 5 seconds is too short for some store requests

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14726]
#### Steps to reproduce
1. Starting at URL: Use /store/products/:site/add to attempt to add a product on a slowish server (e.g. wpsandbox)
2. The product will probably create, but you will get an error on the screen and in the console:

<img width="1240" alt="5001" src="https://cloud.githubusercontent.com/assets/1595739/26732739/737f187a-476d-11e7-887f-6f08b21defd4.png">

#### What I expected

A longer timeout than 5 seconds to allow the request to complete with the remote site. Although product add shouldn't be super slow, we will have other requests that will take longer (e.g. label purchase can take 30 seconds or more.)

Let's make it so we can pass timeout in our requests to the jetpack rest-api wpcom endpoint (will require a server side change too.)

cc @kellychoffman @DanReyLop @belcherj

**Comment by designsimply** [comment]
Can requests for product add and label purchase also be improved for performance?

**Comment by DanReyLop** [comment]
I can only speak for the label purchase requests, and no, they can't be improved. There are maybe a couple of seconds that we could gain by skipping a proxy, but the label purchase itself in `EasyPost`'s end takes about 20 seconds to complete. We are already paralelizing work as much as we can.

**Comment by westi** [comment]
Patch waiting for review and test in D6218-code

**Comment by westi** [comment]
Discussion ongoing in p7bje6-x9-p2

**Comment by justinshreve** [comment]
See #15967.
