### ISSUE TITLE
WooCommerce: Update routes to calypso standards

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14729]
1. Site should always be last
2. Use singular (e.g. order not orders)

cc @ryelle

**Comment by ryelle** [comment]
Example:

```
/store/orders/:site -> List of orders
/store/orders/processing/:site -> List of processing orders
/store/order/:site -> Add a new order
/store/order/:site/:id -> Edit this order
```

And same for products. Settings should also be changed to have the siteId last, `/store/settings/tax/:site` etc.
