### ISSUE TITLE
SEO Preview Upgrade Banner

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#14735]
The current implementation of the SEO advert in the preview tab is meant to show a comparison of your current plan with the Business plan. While that is its purpose it can also create confusion since we display the Business plan's features as crossed out on your current plan. 

Before:

![image](https://cloud.githubusercontent.com/assets/437258/26741733/a23ae5dc-47a8-11e7-824d-d94ad8ec011f.png)

The plan comparison doesn't help, and requires scrolling in order to access the call to action. Instead let's swap the plans grid for a `banner`. It's simpler and much more consistent with our usage elsewhere. 

After:

![image](https://cloud.githubusercontent.com/assets/437258/26741666/55d88b22-47a8-11e7-8fa7-bf9b743248d6.png)

cc @richardmuscat @beaulebens @johnHackworth

**Comment by richardmuscat** [comment]
Love it.

Should say "Upgrade to Professional to unlock..." (ie not "Business" and
not "Plan"; if you want to use plan it should be lowercase p).
