### ISSUE TITLE
Reader: Some sites result in an error when you follow them

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14741]
Examples:

https://wordpress.com/following/manage?q=jalopnik
Feed Stream: https://wordpress.com/read/feeds/41681153
![screenshot 2017-06-02 15 53 12](https://cloud.githubusercontent.com/assets/4924246/26749641/3a4c39fa-47c4-11e7-8882-1be6e49ade66.png)

https://wordpress.com/following/manage?q=jan%20cavan
Feed Stream: https://wordpress.com/read/feeds/41681153
![screenshot 2017-06-02 15 39 34](https://cloud.githubusercontent.com/assets/4924246/26749651/69ecf154-47c4-11e7-937b-380c47906c94.png)

**Comment by fraying** [comment]
I can confirm this bug for those two sites. Is there something weird with those specific URL results, @gibrown?

**Comment by gibrown** [comment]
Not that I can tell. It also fails on the main feed page, so maybe this is a problem with that feed.

**Comment by westi** [comment]
The Japolonik one was an old outdated feed that needed updating to point to the new feed location

I can't reproduce the other one.
