### ISSUE TITLE
Unnecessary API calls when loading a logged-out view

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#14745]
It seems that when loading any logged out view (`/log-in`, `/themes`), there are always these three API calls being made, that don't really make sense:
1. `https://public-api.wordpress.com/rest/v1.1/me?http_envelope=1&meta=flags`
Response:
```
{
	"code": 403,
	"headers": [{
		"name": "Content-Type",
		"value": "application\/json"
	}],
	"body": {
		"error": "authorization_required",
		"message": "An active access token must be used to query information about the current user."
	}
}
```
2. `https://public-api.wordpress.com/rest/v1.1/products?http_envelope=1` !
Response: a loooong one, with all our products.

3. `https://public-api.wordpress.com/rest/v1.1/help/olark/mine?http_envelope=1&client=browser`
Response:
```
{
	"code": 403,
	"headers": [{
		"name": "Content-Type",
		"value": "application\/json"
	}],
	"body": {
		"error": "authorization_required",
		"message": "An active access token must be used to query information about the current user."
	}
}
```

I'm guessing this is something inherent to Calypso's boot process and how we used to not support logged-out views. Nevertheless, seems like something worth addressing :)

Couldn't find any open issues about it, hope it's not a duplicate.

**Comment by klimeryk** [comment]
@yurynix I wonder if this on Amber's radar, as part of their recent work in this area? To my surprise, all three requests are still being made - I vaguely remember reading somewhere that you were looking into skipping the products call, but can't find it anywhere now.

Seems some parts of Olark had to remain for now (see https://github.com/Automattic/wp-calypso/pull/21488), but it seems [sooner or later they will be removed](https://github.com/Automattic/wp-calypso/pull/21488#issuecomment-357315008), since we're using HappyChat now and it doesn't make sense to use an Olark endpoint to query for HC info cc @jsnajdr Anyway, the point here is that the request always fails in this context, because the user is not logged in.

**Comment by jsnajdr** [comment]
> we're using HappyChat now and it doesn't make sense to use an Olark endpoint to query for HC info

The `help/olark/mine` endpoint just has a legacy name, that's all. It answers the question whether the current user is eligible for chat support (more details in https://github.com/Automattic/wp-calypso/pull/21488#issue-162639599). The fact that the chat implementation has changed from Olark to HappyChat is orthogonal to this.

I agree that it's a bug to send this request in a logged-out session, at least at this moment. There are plans to have chat support in pre-sales situations, during user signup -- in that case, logged-out chat can start to make sense.

**Comment by yurynix** [comment]
> @yurynix I wonder if this on Amber's radar, as part of their recent work in this area? To my surprise, all three requests are still being made - I vaguely remember reading somewhere that you were looking into skipping the products call, but can't find it anywhere now.

We're currently focused on GMB exclusively, we don't have any plans for working on logged-out pages, though there is much that we can improve there.

See also: p2-p9j7e4-6m

**Comment by klimeryk** [comment]
It probably is very stale at this point, closing.
