### ISSUE TITLE
.FR extra fields form still show if .fr domain removed from cart

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#14748]
Follow-up to #14156 

1. Add a .fr domain to your cart.
2. When prompted for the G suite upgrade, click back
3. Select another non .fr domain to add to the cart
4. Continue to the WHOIS details form
5. Remove the .fr domain from the cart by clicking on the 'x' next to it in the sidebar.
6. Confirm your WHOIS details by clicking continue

You'll see: the .fr details form, which is no longer needed.

**Comment by ramonjd** [comment]
This is also the case for Canadian domains:

![nov-08-2017 11-50-37](https://user-images.githubusercontent.com/6458278/32526727-01eaeee8-c47f-11e7-9c81-26dae1ceb502.gif)

**Comment by ramonjd** [comment]
Fixed in #19663
