### ISSUE TITLE
On error, focus the field with the validation error

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#14743]
This is related to https://github.com/Automattic/wp-calypso/issues/14212, but is about the main login screen.
If you try the simplest, probably most common bad path, inputting the wrong password, the password input won't be focused. Same for wrong username.

![2rxewhcoac](https://cloud.githubusercontent.com/assets/3392497/26752921/f69b4344-485a-11e7-82cb-9c227f3aa2b4.gif)
(that's me changing the focus using `Tab`)

**Comment by fabianapsimoes** [comment]
Fixed with https://github.com/Automattic/wp-calypso/pull/16080.
