### ISSUE TITLE
WooCommerce: Newly added products with variations are defaulting to out-of-stock

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14767]
Observed while testing https://github.com/Automattic/wp-calypso/pull/14597 but not a bug in that PR

#### Steps to reproduce
1. Starting at URL: /store/products/{site}/add
2. Add a product with variations but leave "manage stock" turned OFF
3. Then, go to the site to look at the product
4. Note that it shows out of stock

Note: This doesn't happen for non-variable products.

<img width="918" alt="screen shot 2017-06-05 at 9 07 36 am" src="https://cloud.githubusercontent.com/assets/1595739/26792378/0e9404ca-49cf-11e7-8580-4af7d8f371ba.png">

**Comment by allendav** [comment]
Further note: Looks like although in this case the attribute (color red|green|blue|yellow) was created - the variations were not actually created.

**Comment by justinshreve** [comment]
@allendav I left a comment on #14597, but there is no API code to save variations yet -- which is where stock comes from for variable products. This can be done once the Action List / Product Saving code is in, so we can do it properly.

**Comment by kellychoffman** [comment]
Can confirm this is still happening.

**Comment by coderkevin** [comment]
This should be tested to see if it's still happening.

**Comment by kellychoffman** [comment]
This is still happening as of today.

**Comment by justinshreve** [comment]
I just tested this. It's not happening. @kellychoffman is it possible you didn't have a price set? A variation w/ no price is considered unavailable for purchase by WooCommerce.

**Comment by kellychoffman** [comment]
You're right. This isn't happening anymore.
