### ISSUE TITLE
WooCommerce: Default to inches and (decimal) pounds for the time being

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#14765]
We have an interesting mix of inches and grams right now in the WooCommerce on Calypso UX - let's swap out grams for (decimal) pounds for our US MVP. (Since US merchants are far more likely to use imperial than metric.)

e.g. in the products UX, variations, etc.

Eventually we can either pick up the settings from the store, or prompt and remember preferred units when they add their first product.

**Comment by justinshreve** [comment]
We need to add this to the setup README or automatically configure the settings during NUX still -- to make sure that they default to what we are using in the UI.

**Comment by kellychoffman** [comment]
This is in.
