### ISSUE TITLE
Make image order in the gallery drag/droppable

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#14760]
The user should be able to adjust the order of images displayed in the gallery by drag/dropping. That includes the large 'featured' image which is the one customers see first when visiting the product page.

**Comment by justinshreve** [comment]
Adding this to post-v1. When I talked with Kelly, we agreed to leave this out for the MVP.

**Comment by jameskoster** [comment]
Makes sense, I just wanted to make sure it was noted somewhere.

**Comment by kellychoffman** [comment]
Let's do this next quarter when we implement the media manager modal.

**Comment by timmyc** [comment]
> when we implement the media manager modal

Found this issue while looking for one about utilizing the media manager for product images. Are we tracking that somewhere or have we punted that idea?

**Comment by tbradsha** [comment]
Had a user asking about this: 8781533-hc

**Comment by timmyc** [comment]
@tbradsha this issue is specifically around changing the order of images on a product in the Store on WordPress.com feature - not in a Gutenberg gallery block.

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
