### ISSUE TITLE
Login: login_limit_exceeded on only the second login

### ISSUE THREAD

**Issue by martinremy** [Automattic/wp-calypso#14779]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/log-in
2. Log in with 2FA successfully.
3. Open new incognito window.
4. Attempt to log in again with the same account.

#### What I expected
I expected to be able to log in again the second time.  Two seems like a low limit.

#### What happened instead
<img width="437" alt="screen shot 2017-06-05 at 4 24 04 pm" src="https://cloud.githubusercontent.com/assets/723655/26805998/f797de76-4a0b-11e7-89d1-7a8a0a2919b3.png">

Incidentally, the message (with the underscores) is not very pretty.  And for the honest-but-confused user, there is no message about when I can retry, or how to recover from this state. 
 Everything worked fine when I tried again a few minutes later.

#### Browser / OS version

Chrome 58.0.3029.110 (64-bit) on macOS 10.12.5

I was #dogfooding by testing 2FA login first with SMS, and my second try was going to be with authenticator app.

**Comment by fabianapsimoes** [comment]
cc @ranh for a copy review.

**Comment by ranh** [comment]
To clarify, what is this login limit? What is being limited, and why?

**Comment by fabianapsimoes** [comment]
According to @scruffian the limit is 10. I'm guessing the reason why is to prevent brute force attacks on accounts, or similar security threats?

**Comment by kristastevens** [comment]
Hello! Popping in to answer the slack ping from the Editorial channel. I see @ranh's on the case -- standing by if you need us!

**Comment by ranh** [comment]
@martinremy Are you still able to reproduce this? Can you confirm that this issue shows up after the second attempt? 

Anyway, this message could work for a rate limit:

> Slow down, you're trying to log in too fast.

**Comment by martinremy** [comment]
@ranh I'm now getting it consistently on the 3rd attempt within a minute or so (not the 2nd attempt).  That seems fine, actually.  After a few minutes, I can log in again.

> Slow down, you're trying to log in too fast.

That sounds good to me :)
