### ISSUE TITLE
WooCommerce NUX: Add store location before egg dashboard appears

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#14775]
As discussed in Slack today with @allendav, we are going to add a step before the Egg Dashboard asking the user to confirm or add their store's location. Originally we were going to use the information they provided in the Biz plan sign up, but this won't necessarily match their physical address. It will also not work with Jetpack users, as they don't enter their location if they select a Free plan. We also want a way to smartly add units for currency, dimension, and weight before a user starts adding a product and asking for a location up front is one way to do that.

Step one: Enter or confirm address: 

![location step](https://cloud.githubusercontent.com/assets/5835847/26810527/2c1612e8-4a3a-11e7-8e5a-044d7a4a5d98.png)

Step two: See Egg dashboard with steps
![pre-setup](https://cloud.githubusercontent.com/assets/5835847/26810528/2c2879ec-4a3a-11e7-938b-de20874ce2f7.png)

**Comment by kellychoffman** [comment]
Was talking to @jeffstieler today and we might need a loading indicator here. The installation of WC and other required plugins will get kicked off once a user has pressed 'Store' in the nav. If the installation doesn't occur by the time the user fills out their address, we have a couple options: 

We use the busy button for the 'Next':
<img width="190" alt="screen shot 2017-06-08 at 8 46 13 pm" src="https://user-images.githubusercontent.com/5835847/26956434-96d7ea04-4c8b-11e7-9dd0-f8b0d0b2937f.png">

And f there's an error, we display it using a GlobalNotice with an action of 'Retry'. 

This would be fine if the plugin upload process is quick. If it takes a bit longer, it would be better to have a dedicated page that would come in between Store Location and Egg dashboard:

<img width="358" alt="screen shot 2017-06-08 at 8 39 02 pm" src="https://user-images.githubusercontent.com/5835847/26956474-f77539a2-4c8b-11e7-81b0-ea0813a383a3.png">

**Comment by allendav** [comment]
Update per @kellychoffman : 

> If a user clicks on “store” we can’t necessarily assume they will actually fill out the address form in order to get a store.  [But] as soon as they click in a field, we can assume they are filling out the form with the intent to set up a store [so] that is the point which we can load [install] the dependancies: wc, api plugin, wcs, etc. by the time they are [done] filling out the form, that will be hopefully be done or almost done. they’ll see a loading screen saying their store is being set up. at that point, the location [address] data [should be] pushed to the [newly created] site.
