### ISSUE TITLE
Reader: Unable to dismiss site recommendation in Manage

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14787]
On Manage, I'm unable to dismiss this site recommendation:

![screenshot 2017-06-05 20 06 16](https://cloud.githubusercontent.com/assets/4924246/26812098/9aaa013e-4a2a-11e7-8f55-ef4244ef50e8.png)
Site stream: https://wordpress.com/read/feeds/49460930

Refreshed the page and got the same rec. Tried dismissing it again, but still unable to do so.

**Comment by jancavan** [comment]
I ran into this again today and it doesn't look like the only issue is that particular site. I keep getting the error every time I dismiss a few site recs in Manage.

**Comment by fraying** [comment]
Re: that error. The user doesn't know they're "blocking" anything.

That error should be: "Sorry, there was a problem dismissing that recommendation."

Or, better, don't error and just disappear the rec. If the backend block doesn't work, there's no need to tell the user about it. They don't know that's happening anyway.

Should I post this as a separate issue?

**Comment by jancavan** [comment]
> Or, better, don't error and just disappear the rec.

This is the issue, the rec isn't dismissible for some reason. I think there should be some sort of feedback as to why a rec isn't disappearing no matter how many times I click it.

**Comment by fraying** [comment]
What I mean is, we can hide the div on click of the "X" even if the block errors out.

**Comment by jancavan** [comment]
> Should I post this as a separate issue?

I think that can be covered here.

> What I mean is, we can hide the div on click of the "X" even if the block errors out.

Ah, so technically it's like dismissing it but really just hiding it. I think we may run into an issue where a "dismissed" rec gets recommended again, but I'll take that vs an ambiguous error message. I _think_ we also cycle through enough recs before the dismissed one shows up again.

**Comment by fraying** [comment]
> Ah, so technically it's like dismissing it but really just hiding it. I think we may run into an issue where a "dismissed" rec gets recommended again, but I'll take that vs an ambiguous error message. I think we also cycle through enough recs before the dismissed one shows up again.

Yes! Exactly.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

This issue remains reproducible as I reproduced this error dialog on the first blog I dismissed using my account.
I was not able to pin down the reason or pattern behind the error.

Suggestions made in comment 2 is probably the best way to handle this type of situation.

If there is no intention to address this issue, it will be closed with label of `Closed - Won't Fix`. 
Please feel free to re-open this issue once work is tabled or scoped.
