### ISSUE TITLE
Reader: unexpected behaviour when adding a comment to a moderated blog

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#14781]
I was attempting to add a comment to a post in the reader. After submitting the comment it disappeared and never showed up on the site. After further investigation it appears that the site is holding all comments for moderation.

**To reproduce**
Visit this post, and add a comment. It will disappear:
https://wordpress.com/read/feeds/58308093/posts/1484761130

It'd be great if we could show some sort of message that the comment was help for moderation instead of disappearing.

**Comment by blowery** [comment]
Thanks @roundhill! cc @Automattic/lannister

**Comment by designsimply** [comment]
Tested and confirmed using the following testing steps:

1. Go to My Sites > Settings > Discussion.
1. Turn off the option for "Comments" > "Users must be registered and logged in to comment"
1. Turn on the option for "Before a comment appears" > "Comment must be manually approved."
1. Log out and log in as a user not associated with the site.
1. Go to the site, find a post allowing comments, and leave a comment.
1. Find the same post in Reader and leave another comment via the Reader UI.

<strong>Result:</strong> in Reader the comment briefly appears without any notice that the comment is being held for moderation and then it disappears.

<strong>Video:</strong> [20s](https://cloudup.com/cmkxRs9GEe4)

![screen shot 2017-06-27 at tue jun 27 11 00 44 am](https://user-images.githubusercontent.com/1119271/27600100-10342516-5b28-11e7-8bee-e73f1b7df6ba.png)
<sup>Seen at https://wordpress.com/read/blogs/5276229/posts/11177#comments using Chrome 59.0.3071.86 on Mac OS X 10.12.5.</sup>

In comparison, commenting on the same post as the same user does display a notice saying the comment is being held for moderation on the blog itself:

![screen shot 2017-06-27 at tue jun 27 10 53 03 am](https://user-images.githubusercontent.com/1119271/27600176-57fd797e-5b28-11e7-9630-624efbfbb1de.png)
<sup>Seen at https://design5279.wordpress.com/2017/06/22/link-color-test/#comment-545 using Firefox 54.0 on Mac OS X 10.12.5.</sup>

**Comment by bluefuton** [comment]
Just retested this. The submitted comment no longer disappears, but the “your comment is awaiting moderation” message does not display with the newly added comment.

**Comment by bluefuton** [comment]
I'm now able to repro the comment disappearing bug.
