### ISSUE TITLE
Framework: hasTouch() considered harmful

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#1479]
We have a ["touch detect" library](https://github.com/Automattic/wp-calypso/blob/6bd3265f782bba013ffa7e0185f05c13593b326f/client/lib/touch-detect/index.js) and use it in [a few places](https://gist.github.com/nylen/b4be15ea2ebd02e72763).  I've used it before, but I won't be anymore, and I recommend that we remove it entirely.

It's not really possible to reliably detect a touch device.  You can detect the touch events APIs, but browsers have a [history of implementing and activating these APIs](http://stackoverflow.com/a/4819886) on devices that would be considered "non-touch".

Also, there are lots of "hybrid" devices like the Surface family and other laptops that support both touch and mouse/keyboard as methods of interaction.  The user can dynamically change between these methods, which is not possible to detect ahead of time.

For a longer, but excellent, writeup: [You Can't Detect a Touchscreen](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/)

Modernizr (where we originally got our `touchDetect` code) has since changed the name of this check from `Modernizr.touch` to `Modernizr.touchevents`, and added a ton of warnings about its use:  Modernizr/Modernizr#548, [`feature-detects/touchevents.js`](https://github.com/Modernizr/Modernizr/blob/0b3cd01/feature-detects/touchevents.js).

Similarly, our own library code says:

> [This test] may not accurately detect a touch screen, but may be close enough depending on the use case.

Finally, we've had multiple issues with this in the past.  To start:
- 11908-gh-calypso-pre-oss - we decided to move away from `hasTouch` for the media modal
- 11922-gh-calypso-pre-oss - same for the editor permalink control
- #1435 / #1452 - same for toolbar pinning

**Comment by lancewillett** [comment]
Hi @nylen — cleaning up older issues in a bug scrub. Did this get traction? Do you want more opinions or discussion? If not, we'd like to close it.

**Comment by nylen** [comment]
I don't think this should be closed - it's an outstanding issue with the current codebase.

**Comment by lancewillett** [comment]
Who's going to work on it? Can we add it to a milestone? CC @mtias 

The problem with just leaving it is it'll be stale very quickly and never get addressed.

**Comment by lancewillett** [comment]
No action in 5 months still. Will close at next bug scrub if it's not addressed.

**Comment by johnHackworth** [comment]
This is very much a still standing issue :+1: 
https://github.com/Automattic/wp-calypso/pull/9977#issuecomment-266428887

**Comment by tyxla** [comment]
I've opened an issue for https://github.com/Automattic/wp-calypso/pull/9977#issuecomment-266428887: #9981

**Comment by alisterscott** [comment]
Closing as #9981 is fixed
