### ISSUE TITLE
Disconnected Jetpack Sites require sites list cleanup

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#14819]
@kellychoffman reported to me that she attempted to disconnect a Jetpack site from Calypso via the proper disconnect flow. After doing so she saw this:

![no-jp](https://user-images.githubusercontent.com/437258/26842569-4560f37c-4abb-11e7-9d3f-f526aea3dcce.gif)

I believe that is recent work done by @enejb to help us clean up inactive Jetpack sites. 

The thing is, we explicitly, without any doubt, know that Kelly's site should not appear in the sites list. 

Did recent work by Enej introduce a bug or do we not yet have a smart check to pro-actively clean up the sites list after a disconnection?

cc @beaulebens @gititon @roccotripaldi

**Comment by kellychoffman** [comment]
FWIW, when I left the site and revisited, I couldn't find the Jetpack-disconnected site in the site list.

**Comment by roccotripaldi** [comment]
I can reproduce. Not sure what triggered this regression, but i will work on a fix first thing tomorrow.

**Comment by roccotripaldi** [comment]
After some digging today, I'm finding that this is only happening with sites that are no longer accessible. Do you recall if that was the case with your site @kellychoffman ?

My current theory is that when the site is inaccessible, something goes wrong on the API where you are not immediately removed from the site.

**Comment by kellychoffman** [comment]
Yes, that was the case when I initially discovered it.

**Comment by designsimply** [comment]
(Out of curiosity) what is the expected behavior when an inaccessible Jetpack site disconnected in this flow?

**Comment by roccotripaldi** [comment]
It should just disappear when you click the button. Also, we have now have maintenance routines that should automatically remove them. So the appearance of inaccessable sites should be less frequent.

**Comment by roccotripaldi** [comment]
I'm 95% sure this is fixed. I can no longer reproduce. Let's re-open if it re-surfaces.
