### ISSUE TITLE
Intro Box Auto-Dismiss

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14824]
Currently, new users see the Intro Box at the top of Reader. It includes a link to dismiss the box.

If the user does not dismiss the box themselves, we should dismiss it for them after some period of time. I suggest two weeks after their signup date. Or, if it's possible, two weeks after the first time they saw it. But if that's too complicated, we can just do two weeks past account creation.

Why? Anything we put at the top of the stream causes engagement rates to go down. We should give the box a chance to do its thing, but if the user is ignoring it, we should remove it so that the posts have a better shot at wooing the user into engaging. 

cc @bluefuton

**Comment by bluefuton** [comment]
> if it's possible, two weeks after the first time they saw it. 

My thoughts on how to do that:

- when they first see the intro banner, store a calypso preference with the time they saw it (e.g. `reader_intro_first_view_time`)
- if the user has that preference set and `is_new_reader` = true, and the first view was two weeks ago or more, don't show the banner, trigger the removal of the is_new_reader flag, and also remove the calypso_preference.

It is fairly complicated. Thoughts @blowery? "Signed up in the last two weeks" would be a much simpler proposition.

**Comment by blowery** [comment]
I think "signed up in the last two weeks" would be sufficient. And much much simpler.
