### ISSUE TITLE
Free Trials: Update /plans/compare/ to indicate that a domain isn't included in the trial

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1482]
Since we aren't going to include domains in trials we need to be sure we indicate that a free trial of our plans does not include domains.

I suggest we add a subtle asterisk (or similar) to the /plans/compare/ page for domains and include a subtle note at the bottom of the page stating that domains are not included during the free trial period.

**Comment by breezyskies** [comment]
Proposed design for including this in the plans comparison page:

![screen shot 2015-12-17 at 8 01 15 am](https://cloud.githubusercontent.com/assets/3011211/11874437/89e70faa-a494-11e5-8099-b1d9a21f2bb6.png)
