### ISSUE TITLE
Themes:  Theme card displays WP.com theme details when a theme with the same name is uploaded

### ISSUE THREAD

**Issue by kevmarsden** [Automattic/wp-calypso#14837]
On Jetpack and AT sites, when a theme is used that matches the name of a WordPress.com theme, the WordPress.com theme details are displayed in the theme card. 

#### Steps to reproduce
1. On a Jetpack or AT site, upload a theme that has a name that matches a WordPress.com theme
2. Navigate to the Calypso themes page:  https://wordpress.com/themes/

#### What I expected
To see the correct screenshot for the theme and an Info icon with a link to the correct theme page.  

#### What happened instead
The WordPress.com theme's screenshot is displayed and the Info and Setup icons link to the WordPress.com theme pages.  

#### Screenshot / Video
Here's an example of a site using an external theme called "Entrepreneur":

![screenshot](https://user-images.githubusercontent.com/2282189/26856190-19da08f8-4ad7-11e7-9474-eb8ad07bed45.jpg)

#### Context / Source
 #user-report

**Comment by kwight** [comment]
Slugs may be involved, needs more investigation.

**Comment by markbiek** [comment]
@blackjackkent I tried this a bunch of different ways and I can't reproduce it.

I'm also not sure where the view shown in the original post is. Is it possible things have changed and this isn't an issue anymore?

![image](https://user-images.githubusercontent.com/917632/162049397-87c18588-90c8-415c-8392-a42690a782ee.png)

**Comment by blackjackkent** [comment]
Entirely possible - likely even, given that this was before we did a bunch of theme showcase updates a bit back. Feel free to close if you can't reproduce. :)
