### ISSUE TITLE
Editor: After Copy a Post, Publicize fails

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#14840]
Copy-and-pasting the original report by @KokkieH:

### Summary:

When using the copy post feature in Calypso, the new post does not trigger Publicize if the post being copied has already publicized.

### To replicate:

1. Go to https://wordpress.com/sharing and ensure the site has an active Publicize connection to any service.
2. Go to https://wordpress.com/post and create a new post. Add some content and publish it.
3. Create another new post. In Post Settings, click More Options and select Copy Post. Select the previous post.
4. Make changes to the title and content of the new post, as a user would do when using an old post as a template for a new one.
5. Under Sharing in Post Settings, make sure Publicize is enabled, and publish the post.

### What I expected:

That the second post would Publicize to the connected social media account the same as the first, as it's a new post that has never been Publicized before.

### What happened instead:

The second post was not Publicized. Looking at the site's RC it indicates that Publicize failed because it detected the post had already been Publicized, even though this was a brand new post.

As a control I also used the Copy Post feature via WP-Admin, and in that case the post did Publicize correctly.

**Comment by codebykat** [comment]
So the Publicize-specific post_meta needs to be cleared when a post is copied; @Copons maybe you can look at this?

**Comment by Copons** [comment]
Good catch you all!
I tried removing all the metadata from the info copied in the Copy Post feature and indeed that fixes Publicize.

Now, I could filter out all metadata that start with `publicize` or `_publicize`, but I fear that would only be a temporary fix until someone discovers some other feature breaking.

I'm tempted to remove all the metadata, but then we would miss some legit stuff (`geo_latitude` and `geo_longitude` are the most obvious I can see).

If I try printing the metadata array on my (free plan) test site, I see some elements that probably shouldn't be copied, and some that should. Problem is, I don't really know what most of those mean:

- `email_notification` (a seemingly "random" int?)
- `geo_latitude`
- `geo_longitude`
- `jabber_published` (another "random" int - albeit, the first several digits are the same as email_notification)
- `publicize_tumblr_url` (this I guess I could safely copy)
- `_akismet_post_guid` (maybe I shouldn't copy this)
- `_akismet_post_spam` (does this flag if the post is spam?)
- `_publicize_done_12345` (this might be this issue culprit)
- `_publicize_job_id`
- `_rest_api_client_id` ("-1"?)
- `_rest_api_published` (this flag shouldn't be copied as well)
- `_wpas_done_67890` (no idea)

At a quick glance, I might assume that I could safely filter _all_ elements starting with `_`.
But what if some plugin (or maybe even a business plan) adds other `_`-metadata that are worth copying? And what if those plugins or plans instead add non-`_`-metadata that shouldn't be copied?

**Comment by codebykat** [comment]
Yep, `_publicize_done_xxxxx` is the culprit. Also `_wpas_done_67890` (a holdover from WordPress Activity Streams - Publicize sets both, they should both be cleared).

The `publicize_job_id` needs to go.

I believe `publicize_tumblr_url` is the URL of the publicized post (so it shouldn't be copied).

`jabber_published` would mean it got posted to those notifications, probably? I haven't tested but I'm wondering if these posts are also missing from email and Jabber notifications.

I'm betting we also want to clear out those Akismet keys, though I don't know what they do.

Honestly the only meta in there that should stick around is the location stuff.
