### ISSUE TITLE
Editor: Feature Image Dropzone Visual Feedback

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#14847]
This is a design feedback that wasn't addressed in the original PR of D&D feature. Making an issue here so it's not forgotten.

![](https://cloud.githubusercontent.com/assets/184938/24872552/77104c18-1e26-11e7-8cbd-a04cbe833aa5.png)

- It's strange that the featured image text is black and the regular blue zone has white text.
- We should just use a generic Gridicon for featured image, since the star overlaying the image icon partially creates a new icon that is inconsistent with the Gridicons style.

Based on original Design Feedback here: https://github.com/Automattic/wp-calypso/pull/11839#issuecomment-293961793

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
