### ISSUE TITLE
Editor: Sharing options aren't set before draft saved

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#14853]
#### Steps to reproduce
1. Create a new Post or Page on a site with no Publicize connections
2. Before adding any content, expand the Sharing section
3. Note that the "Show Sharing/Like Buttons" options are deselected
4. Add text to the post and save a draft
5. Note that the boxes are now checked

#### What I expected
To have the checkboxes selected when I first open the editor

#### What happened instead
Their state isn't populated until a draft is saved.  This doesn't seem to be the case if the site has a Publicize connection, in that case they're correctly checked at the start.

cc: @mtias - I actually did see this when running the e2e tests against #14096 the other day, but at the time I was also able to reproduce it on `master` running locally, so I assumed it was a timing issue with my local setup or due to some other change that I wasn't able to track down.  But it showed up in production when you merged this one in.

For now I put a workaround into the e2e tests to save a draft before modifying those options. https://github.com/Automattic/wp-e2e-tests/pull/563

#### Browser / OS version
Seen here in OSX Chrome:

#### Screenshot / Video
![wp-calypso-sharing-reset](https://user-images.githubusercontent.com/7233112/26879848-8c2e637a-4b60-11e7-812e-bc8add4fdcc8.gif)

#### Context / Source
#automated-testing

**Comment by aduth** [comment]
Suspect regression of #14096, specifically for these site options:

- [`default_sharing_status`](https://github.com/Automattic/wp-calypso/blob/1817b8268db2e9bb8458d0056507ab31f533de6d/client/post-editor/editor-sharing/sharing-like-options.jsx#L33)
- [`default_likes_enabled`](https://github.com/Automattic/wp-calypso/blob/1817b8268db2e9bb8458d0056507ab31f533de6d/client/post-editor/editor-sharing/sharing-like-options.jsx#L45)
