### ISSUE TITLE
Embedded Audio does not play on Internet Explorer

### ISSUE THREAD

**Issue by charliescheer** [Automattic/wp-calypso#14869]
I was working with a user a little bit ago who was building an audio podcast.  They have embedded audio onto their site and it will not play on internet explorer.
#### Steps to reproduce
1. Starting at URL: http://thetolkienheads.com/
2.In internet explorer try to play the audio from one of the posts
3.Audio wont play

When viewing a page with audio, if you click on the play button the audio never loads.  The length of the file stays at 0:00 and never starts playing.  I tested in Internet explorer 15
![screen shot 2017-06-07 at 12 32 27 pm](https://user-images.githubusercontent.com/22015538/26895022-6cbfd560-4b7d-11e7-83e0-bb73e043f404.png)

**Comment by lancewillett** [comment]
This one should probably go into an internal bug tracker as Calypso isn't for front-end sites (just the Calypso UI).

**Comment by designsimply** [comment]
Thanks! Moved to 7897-wpcom
