### ISSUE TITLE
Sites Results in Search: Text CSS Tweaks

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14878]
Looks like all text in the right sidebar is 14px. I think it should be changed to 13px. 

And the line-height is currently 21px. I think it should be changed to 19px.

These two changes would make the text consistent with the sans serif type in the main card headers in the left column. And because space is at such a premium in the right column, it'd make it easier to read and let us squeeze in a bit more text.

cc @jancavan

**Comment by fraying** [comment]
We might even want to take the URL line down to 12px.

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/commit/5a111ffa8f59a231204d59cb465d35a70a32bebc

**Comment by samouri** [comment]
I'll close this because I think its addressed.  Feel free to reopen if parts aren't
