### ISSUE TITLE
Media: Videos and Audio tabs prompt for upgrade on already upgraded site

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#14879]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/audio/ or https://wordpress.com/media/videos/ on a site with a Premium or Business plan
2. Note that you are prompted to upgrade to upload audio or video despite having a valid plan. The All tab and WP Admin allow you to upload videos and audio as expected. 

#### What I expected
To be able to see existing audio and video uploads and add further files.

#### What happened instead
I see a prompt to upgrade.

#### Browser / OS version
Macintosh OS X 10.11.6, Chrome 58.0.3029.110

#### Screenshot / Video
![screen shot 2017-06-07 at 4 28 36 pm](https://user-images.githubusercontent.com/1900444/26900024-ecbc7996-4b9e-11e7-91c7-1471850a584f.png)
![screen shot 2017-06-07 at 4 28 39 pm](https://user-images.githubusercontent.com/1900444/26900025-ecc3db28-4b9e-11e7-8547-2bf39dc2a897.png)

#### Context / Source
#user-report

**Comment by spncrb** [comment]
If you click back to the /plan tab and then back to /media it seems to work again.
