### ISSUE TITLE
Sites Results in Search: Header CSS Tweaks

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14875]
Currently: 

<img width="881" alt="screen shot 2017-06-07 at 12 22 45 pm" src="https://user-images.githubusercontent.com/24388/26897803-99fa479e-4b7e-11e7-8227-50c1f556c31d.png">

- Lines under headers are 2px and lighter grey. Should be 1px and darker grey. 
- POSTS and SITES are too big. Should be same size as MORE headers on Fullpost. They look to be 2px too big to my eye.

So, should be:

<img width="842" alt="screen shot 2017-06-07 at 12 43 26 pm" src="https://user-images.githubusercontent.com/24388/26897923-0a3787e2-4b7f-11e7-8c38-625162d014e2.png">

cc @jancavan

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/commit/5a111ffa8f59a231204d59cb465d35a70a32bebc
