### ISSUE TITLE
Editor: WPEmoji don't follow text color

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#14887]
#### Steps to reproduce
1. Create a new post and add some text with the copyright symbol on it
2. Try to change the font color on all the content

#### What I expected
That the copyright symbol would follow the color of the rest of the text

#### What happened instead
The copyright symbol keeps showing in black, since it's an image

#### Screenshot / Video
![screen shot 2017-06-07 at 19 03 08](https://user-images.githubusercontent.com/16104522/26903522-fbe9e1d2-4bb3-11e7-8016-9b7248bcf25b.png)

#### Context / Source
User reported on live chat that this behavior was changed a couple weeks ago, he said the following:

> The challenge with this is that I'm doing this in an image post, and on my theme it changes the post background color to harmonize with a color in the image. On this particular image, that makes the text white. But this circle-c image is black.

Ticket: 3252575

cc @pento, since it looks like it's related to this issue: https://github.com/Automattic/wp-calypso/pull/14706

**Comment by pento** [comment]
Thanks for the bug report, @carinapilar! Core works around this by disabling Twemoji on characters that will never need to be replaced by images, such as the copyright symbol - I'll see if I can port this behaviour to Calypso.

Core ref: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/js/wp-emoji.js?rev=38194&marks=125-145#L125
