### ISSUE TITLE
Cannot edit post slug 

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#14884]
The ability to edit a post slug is no longer available.  When I click on the link icon next to the title, the only option is to copy the URL.  Opening the More Options panel, the post slug no longer appears above the Excerpt box.

The page slug option has disappeared under the More Options tab as well, although I can edit page slugs if I click on the link icon next to the page title.

**Steps to reproduce:**
1) Open a post to edit.
2) Click on the link icon next to the title - option to edit slug unavailable.
3) Click on the More Options tab in the Settings sidebar  - option to edit slug unavailable.

**What I expected**
To see the box to edit post slugs when opening More Options, or to click on the end of the URL to edit when clicking on the Link icon next to the post title.

**What happened instead**
The options are gone/unavailable.

**Screenshots**
![link next to title](https://user-images.githubusercontent.com/11635760/26901933-4bbc0910-4b8c-11e7-8eeb-9cb396f40e4c.png)
![more options panel](https://user-images.githubusercontent.com/11635760/26901938-521207ba-4b8c-11e7-9572-d7d4e5c592e3.png)

#user-report

**Comment by designsimply** [comment]
Tested and confirmed with the steps provided using Firefox 53.0.3 on Mac OS X 10.12.5.

Also see https://en.support.wordpress.com/slugs/

![screen shot 2017-06-07 at wed jun 7 3 37 27 pm](https://user-images.githubusercontent.com/1119271/26902676-66d07a5a-4b97-11e7-8a8f-86baffa97f23.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11070 using Firefox 53.0.3 on Mac OS X 10.12.5 unproxied.</sup>

In comparison to posts, page slugs are still editable on WordPress.com sites at the top of the page editor but the More Options section in Page Settings no longer has the Slug option:

![screen shot 2017-06-07 at wed jun 7 3 42 04 pm](https://user-images.githubusercontent.com/1119271/26902821-f2ea7f2c-4b97-11e7-9a16-9eb01079a7c4.png)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/10903 using Firefox 53.0.3 on Mac OS X 10.12.5 unproxied.</sup>

**Comment by KokkieH** [comment]
Had a few reports from users on 863404-f. Logging it here for follow-up.

**Comment by htdat** [comment]
Another report from 152995-hc.

**Comment by lucasjoyce** [comment]
Another report from 437327-hc

**Comment by simplysaru** [comment]
Another report in 325328-t

**Comment by carinapilar** [comment]
Another in 3252715-t

**Comment by Gilmoursa** [comment]
Another report in ticket 3253587

**Comment by rwaynick** [comment]
Two reports, 437637-hc and 132081-hc. I directed them to WP-Admin for now.

**Comment by aduth** [comment]
Pending fix at #14916

**Comment by maciejpilarski** [comment]
Another one 3254093-t
