### ISSUE TITLE
Imports: Import successful email links to clitools.wordpress.com

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#14883]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/
2. Initiate an import
3. When completed the "Import successful" email links to clitools.wordpress.com instead of the correct site URL. This behavior happens with the WP Admin importer as well, so it's likely an underlying issue and not specific to Calypso.

#### What I expected
The email to reference the correct site the file was imported into

#### What happened instead
clitools.wordpress.com is linked instead

#### Browser / OS version
Chrome 58.0.3029.110, Macintosh OS X 10.11.6

#### Screenshot / Video
![screen shot 2017-06-07 at 5 18 06 pm](https://user-images.githubusercontent.com/1900444/26901898-50108c20-4ba5-11e7-9677-d4d983186d2c.png)

The replyto on the email is help@wordpress.com.

**Comment by nbloomf** [comment]
Two more users have also reported this issue:

#3246068-t
#3245993-t

**Comment by htdat** [comment]
More :) 

#3245993-t
#3205717-t
#3208750-t

**Comment by alexjgustafson** [comment]
3268646-t
3267120-t

**Comment by alexjgustafson** [comment]
3266484-t

**Comment by supernovia** [comment]
Reported here:
https://en.forums.wordpress.com/topic/import-from-squarespace-9?replies=10#post-2974735

and here:
http://en.forums.wordpress.com/topic/import-notifications-to-wrong-url

I also searched my own email and found three instances of the wrong url. The oldest is May 30.

**Comment by kriskarkoski** [comment]
I'm currently doing some triage and realizing how many reports of this we're getting, including some concerned users that their import has gone wrong such as #3304179-t. It looks like something was imported into the site as there's an Italian post from a VIP user and a bunch of menu items that are making this site look extra bad.

cc @lancewillett for visibility/prioritization

**Comment by lancewillett** [comment]
Thanks @kriskarkoski , could you post on HG P2? I'm not going to be able to look before next week.

**Comment by dllh** [comment]
Heads up, I'm also not going to be able to look before next week.

**Comment by ehti** [comment]
More reports -
#641301-zen

**Comment by gemmagarner** [comment]
Another report in 874347-f

**Comment by rachelmcr** [comment]
I just saw this issue after doing an import into a private test site that I own. (I started the import from the WP Admin WordPress importer rather than Calypso, but it looks like the same underlying issue.)

**Comment by lancewillett** [comment]
I got this one today also — testing out a WP import on `https://wpcalypso.wordpress.com/settings/import/lancetest24.com`

Success pane in Calypso:
![screen shot 2017-09-06 at 10 37 04](https://user-images.githubusercontent.com/66797/30126012-5b9c8b34-92ef-11e7-8547-d00f75c4f084.png)

Email:
<img width="474" alt="screen shot 2017-09-06 at 10 37 20" src="https://user-images.githubusercontent.com/66797/30126023-62239c4a-92ef-11e7-8817-a7cab95e3e21.png">

**Comment by dllh** [comment]
This is fixed in r162387-wpcom.
