### ISSUE TITLE
Editor: opening in small window from Press This broken in recent layout design change

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#14882]
Press This (and maybe other small screen cases) seem broken now because of the recent editor refresh in #11536

#### Steps to reproduce
1. Go to Settings > Writing for your blog or site, and drag the Press This bookmarklet to your browser favorites.
2. Navigate to any website.
3. Click the bookmarklet.

#### What I expected
I expected to see the editor body content area when the Calypso editor window opened from the bookmarklet.

#### What happened instead
I see the editor settings sidebar instead.

When you launch Press This now, the post editor body is hidden to the left and all you see is the right sidebar:

![screen shot 2017-05-15 at 16 51 25](https://cloud.githubusercontent.com/assets/66797/26078833/be89ca3c-398e-11e7-8d68-8ef76bd7e5e2.png)

Here's the same window after dragging it open a bit more:
![screen shot 2017-05-15 at 16 51 36](https://user-images.githubusercontent.com/66797/26901730-bb7c176e-4b8b-11e7-8c34-b0e814e0bbb9.png)

**Comment by lancewillett** [comment]
@jblz Could you (or Samus team) take a look at this one? I was promoting the Press This to a customer today and realized it broke in the recent editor sidebar redesign. :/

**Comment by lancewillett** [comment]
One interesting note I saw in testing this again just now — if I click the "cog" icon to close Post Settings, I can see the editor pane and continue editing my post.

Then next time I click the bookmarklet, the post settings pane is closed. So, that's half-way there — but still not great for the first-time author who won't know to click that cog icon.

**Comment by jblz** [comment]
Sure -- thanks for the insight re: the cog

**Comment by lancewillett** [comment]
Sweet! #16519 run-through in Safari 10.1.1 on OS X 10.12.5

Starting at https://lance.blog/2017/07/02/hustle/ in a normal window, clicking the Press This bookmarklet. Result:

![screen shot 2017-07-25 at 10 52 03](https://user-images.githubusercontent.com/66797/28586079-60ff517c-7127-11e7-8fe9-b65dab512932.png)

Looks much better. 👍
