### ISSUE TITLE
Login: Fix React warning when signing up through social log in button

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14898]
Found when testing #14782.

> Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>. See LoginForm > form > ... > Connect(Localized(SocialLoginForm)) > Localized(SocialLoginForm) > SocialLoginForm > WpcomLoginForm > form.

### Steps to reproduce
1. Go to http://calypso.localhost/log-in.
2. Log in with a Google account that has not signed up using social button.
3. You should see this error on your JS console.

**Comment by fabianapsimoes** [comment]
I can no longer reproduce this error in the console.
