### ISSUE TITLE
Error running make install

### ISSUE THREAD

**Issue by brianyang** [Automattic/wp-calypso#14915]
#### Steps to reproduce
starting from a clean slate..
2. clone the repo
3. run `make run` 

#### What I expected
the app to build

#### What happened instead
node throws an error. here's the full log:
```
~/P/r/wp-calypso ❯❯❯ node -v                                                                                                                                                                             master
v6.10.3
~/P/r/wp-calypso ❯❯❯ npm -v                                                                                                                                                                              master
3.10.10
~/P/r/wp-calypso ❯❯❯ make run                                                                                                                                                                            master
             _
    ___ __ _| |_   _ _ __  ___  ___
   / __/ _` | | | | | '_ \/ __|/ _ \
  | (_| (_| | | |_| | |_) \__ \ (_) |
   \___\__,_|_|\__, | .__/|___/\___/
               |___/|_|

/Users/brian/Public/react-open-source/wp-calypso/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/brian/Public/react-open-source/wp-calypso/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/brian/Public/react-open-source/wp-calypso/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:570:32)
make: *** [build-server] Error 1
```

#### Browser / OS version
n/a

#### Screenshot / Video
n/a

**Comment by designsimply** [comment]
I tested with the same versions and was able to get Calypso to run locally. 

I searched for "Error: Module version mismatch. Expected 48, got 51" and found some advice at stackoverflow.com and am wondering if you can give it a try:

> `npm rebuild` -- if not helps then --- `rm -rf node_modules && npm install`

— https://stackoverflow.com/questions/42689577/npm-nodejs-package-json-module-version-mismatch-expected-48-got-51#comment72501973_42689577

Here's another one that looks similar:

> Every time you switch node versions you need to recompile the dependencies. This can be done with `npm install`, but preferably before that you need to remove the whole `node_modules` path in your project. So `rm -rf node_modules && npm install`

— https://stackoverflow.com/questions/40910642/how-do-i-find-what-versions-of-npm-and-node-my-dependencies-need#comment69033497_40910642

**Comment by designsimply** [comment]
Closing this for now! Please re-open if you find more data to add relevant to troubles with the Calypso build.
