### ISSUE TITLE
Sites Results in Search: Include sites you're already following

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14925]
Currently search results do not include sites you're already following, but they should.

(Just posting this issue for tracking. Who's on this? @samouri? @blowery?)

**Comment by blowery** [comment]
I'll take it.

Current plan is to key the searches by query + include following. Tried doing it purely with a selector, but then the counts are wrong.

**Comment by blowery** [comment]
Additionally, well need keys that include the args for #14296

**Comment by samouri** [comment]
This has already been implemented, closing
