### ISSUE TITLE
Sites Results in Search: Date sort should also sort site results

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#14926]
Currently site results are unaffected by the date sort. They should be sorted by last update.

(Just posting this issue for tracking. I believe it's on @gibrown's list.)

**Comment by blowery** [comment]
Likely piggybacks on #14925 and the ability to key queries off all args

**Comment by gibrown** [comment]
@blowery the endpoint now supports a sort param that can be set to last_updated, and it will return a next_page when using that sorting which can be sent with the next request to the page_handle param.

**Comment by blowery** [comment]
fixed
