### ISSUE TITLE
Jetpack Plans: we should only show a discount for the pro-rated upgrades

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#14934]
Currently, since we've merged pro-rated upgrade discounts we are confusingly showing two different kinds of discounts on the plans page:

<img width="1072" alt="screen shot 2017-06-08 at 2 33 09 pm" src="https://user-images.githubusercontent.com/437258/26944742-9ba47298-4c57-11e7-8978-221c34012554.png">

You'll notice that the Personal and Premium plans are displaying the total of 12x the monthly price, discounted to the yearly price.

The Professional plan is showing the yearly price discounted by the amount of credit we are giving the user due to the pro-rated price.

We should perhaps only show the indication of a discount for the plans that are more expensive than your current plan. In the screenshot above we would show the $39 and $99 prices plainly, no discount. 

cc @ashleighaxios for noticing, @richardmuscat, @tyxla, @johnHackworth, @bubel 

Let's wait to tackle this until we get some consensus.

**Comment by bubel** [comment]
I agree with you here, Rick. In this scenario, the Personal and Premium price points should be displayed without the discount concept. This way, the discount the customer is receiving due to the proration is more obvious.

**Comment by tyxla** [comment]
That totally makes sense - it did feel weird during my testing as I was working on pro-rating stuff. Would be happy to work on a solution for that once we get to a consensus about the best way to get around this.

**Comment by tyxla** [comment]
No longer valid - plans grid has been revised since. Closing.
