### ISSUE TITLE
Purchases: Domain credits missing from Personal plan

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/wp-calypso#14938]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/
2. Purchase Personal plan, complete transaction
3. Go to https://wordpress.com/domains/ to add custom domain

#### What I expected
Credits included with plan to show domain 'included with plan', payment not required for registration and mapping

#### What happened instead
Prompted to pay, credits not shown

Store Admin shows 'disconnected' in mapped URL field, clearing this and updating allows user to see credits in Calypso.

#### Browser / OS version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:53.0) Gecko/20100101 Firefox/53.0
and
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

#### Context / Source
438388-chat and 438052-chat

**Comment by stephhjacq** [comment]
Also 438862-chat and 438875-chat

**Comment by janm6k** [comment]
This was fixed by @prettyboymp, details in p7DVsv-2BL-p2
