### ISSUE TITLE
WooCommerce Payments: Update payment method settings to match design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#14940]
Re: https://github.com/Automattic/wp-calypso/pull/14932

As discussed in Slack:

For PayPal, we will only keep the Paypal email/account and the authorization setting. Updated design: 

<img width="779" alt="screen shot 2017-06-08 at 4 57 47 pm" src="https://user-images.githubusercontent.com/5835847/26950567-06790dae-4c6c-11e7-8a4b-fcb1b0df7b04.png">

**Comment by belcherj** [comment]
@kellychoffman can I close?
