### ISSUE TITLE
Reader: Reduce spacing between sites in Site Results

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14946]
In https://github.com/Automattic/wp-calypso/pull/14881, the font sizes, line-height, etc. have been made smaller. Now there is a ton of space between each site result:

![screenshot 2017-06-08 20 54 13](https://user-images.githubusercontent.com/4924246/26960492-a3195acc-4c8c-11e7-9449-370b76e05314.png)

Tried removing `padding: 15px 0;` from `reader-subscription-list-item` (didn't work and causes overlapping sites as you scroll), but from what I remember, I think padding/height is being calculated somewhere else.

/cc @samouri

**Comment by samouri** [comment]
yep! I'll take this

**Comment by samouri** [comment]
Closing. I believe this was fixed as part of: https://github.com/Automattic/wp-calypso/pull/14577/files#diff-1c7cd1d96c5bca42b29d78ef3f3fb5b1R36

**Comment by jancavan** [comment]
We temporarily removed "Last updated" and I noticed that this left extra white space when the Settings icons exists:

Comment originally posted here: https://github.com/Automattic/wp-calypso/pull/15526#issuecomment-311188910
<img width="461" alt="screenshot 2017-06-26 14 29 33" src="https://user-images.githubusercontent.com/4924246/27561419-d177e174-5a7c-11e7-98f3-446c468b4366.png">

This seems to only happen when you're already following a site then perform a search though.

**Comment by jancavan** [comment]
Closing this in favor of: https://github.com/Automattic/wp-calypso/issues/15531
