### ISSUE TITLE
WooCommerce: Display settings

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#14962]
Here's the design for display settings:

![display-settings](https://cldup.com/AFSRzyRgJw-3000x3000.png)

Notes:

* Image size input placeholders should be 'Width' & 'Height'.
* Store notice should be enabled for new stores and then disabled automatically when they click 'I'm finished setting up' on the egg dashboard.
* If the 'Apply same settings to shop categories' checkbox is unchecked another `SegmentedControl` appears [like so](https://cloudup.com/cGA1r4YuJMA).
* Lots of settings have been removed from the standard set in wp-admin. We want to use smart defaults for many of these, and hopefully remove some altogether (see https://github.com/Automattic/wp-calypso/issues/14868). You can see what we want to do with each setting in the [Sketch file](https://www.dropbox.com/s/xm496ult374o489/settings.sketch?dl=0).
* We've removed the settings sub-nav in the sidebar and replaced it with a `SectionNav` in the settings screen itself. This will need to be added to the other settings screens (cc @belcherj, @DanReyLop, @allendav).

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
