### ISSUE TITLE
Login: English version can be accessed from two different urls

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14965]
Raised by @stephanethomas in #14806:

> It's possible to access http://calypso.localhost:3000/log-in/en. I was expected to be redirected to http://calypso.localhost:3000/log-in in that case. We're duplicating content and entry points here, and that's something we should fix, although it doesn't have to be in this pull request.

I tried to fix this issue from the Locale Suggestions box, but then I broke `/start` pages and probably a couple of other pages, so I removed this fix from the original PR.

Steps to reproduce:
* Open http://calypso.localhost:3000/log-in
* Switch to a different locale
* Switch back to `en` locale
* You will see English translation, but different url. This is an issue on the Login page, because we have 2 different urls that produce the same HTML (we server render this page).

**Comment by scruffian** [comment]
This should be made redunant by https://github.com/Automattic/wp-calypso/pull/16133
