### ISSUE TITLE
Editor: Powered by TinyMCE badge

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#14963]
Seems like a very recent change. In certain viewports (wide enough/tall enough), we now show "Powered by TinyMCE" badge inside of the editor. Doesn't look intentional, as you might need to scroll, is not retina etc…

#### Steps to reproduce
1. Starting at URL: /post
2. Make window bigger, maybe scroll

#### Screenshot / Video

look at the bottom right corner of image:

<img width="723" alt="screen shot 2017-06-09 at 17 08 23" src="https://user-images.githubusercontent.com/156676/26982058-6378d748-4d37-11e7-9d13-ea264dbec6f5.png">

#### Context / Source

#dogfooding

**Comment by folletto** [comment]
Confirmed, I can reproduce.
At some resolution is not visible as it falls below the fold.

**Comment by iseulde** [comment]
See https://github.com/tinymce/tinymce/blob/4.6.3/src/themes/modern/src/main/js/ui/Branding.js

We can disable with a setting.
