### ISSUE TITLE
Reader: Search and Site Results in Search broken IE

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#14969]
**Recommended Posts:**
![screenshot 2017-06-09 11 35 28](https://user-images.githubusercontent.com/4924246/26989433-eb00cfa2-4d07-11e7-81ef-bd3bae0ad28e.png)

**Site Results:**
![screenshot 2017-06-09 11 35 40](https://user-images.githubusercontent.com/4924246/26989432-eafe0092-4d07-11e7-96e8-3cd632a591ca.png)

**Comment by samouri** [comment]
oh darn. is this IE11?

**Comment by jancavan** [comment]
Yes, the first one is fixed. Working on the second one now.

**Comment by jancavan** [comment]
> Site Results:

I think this got resolved when fixing: https://github.com/Automattic/wp-calypso/pull/14982 as I'm no longer able to repro. This is what it looks like now:
![screenshot 2017-06-19 16 57 46](https://user-images.githubusercontent.com/4924246/27310622-72c2926c-5510-11e7-9137-7103cf4f254a.png)

I found other issues in IE though that I'll create separate PRs for.
