### ISSUE TITLE
Signup: A/B test checkout after signup without the masterbar

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1497]
The user may navigate out of checkout erroneously when visiting it immediately after signing up. We should test a version of `Checkout` that is displayed after signup where the masterbar is hidden.

**Comment by fabianapsimoes** [comment]
This was done in https://github.com/Automattic/wp-calypso/pull/2635 and https://github.com/Automattic/wp-calypso/pull/3208.
