### ISSUE TITLE
Editor: Clicking Save when drafting a post prevents the preview from refreshing

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#14975]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Select a test site (if your test user has more than one)
3. Enter some content and click preview
4. Close the preview modal
5. Change the post content
6. Click the `Save` link / button:<br /><img width="207" alt="screen shot 2017-06-09 at 4 31 02 pm" src="https://user-images.githubusercontent.com/1587282/26993529-718e1d9e-4d31-11e7-9073-2438f72b3fa8.png">
7. Click preview

#### What I expected
The draft to be saved & the preview to show the updated content

#### What happened instead
The draft doesn't appear to have saved & the preview shows the previous content (it doesn't appear the iframe reloads)

#### Browser / OS version
Chrome 59, MacOS Sierra

**Comment by mattsherman** [comment]
Here's a screen cap that illustrates the issue (I too hit this today)...

![editor preview](https://user-images.githubusercontent.com/2098816/27101791-15e21e50-5051-11e7-8541-bbe1b4ec4b1d.gif)
