### ISSUE TITLE
Login: Add missing `Powered by Jetpack` footer

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#14983]
I figured out we missed newly introduced `Powered by Jetpack` footer on new Login page. See how it looks on `/wp-login.php`:

![image uploaded from ios](https://user-images.githubusercontent.com/699132/27000132-a54665aa-4daa-11e7-9c85-c51036831074.jpg)

**Comment by gziolo** [comment]
@beaulebens I guess we don't have a Calypso component for it, right?

**Comment by scruffian** [comment]
I  started this here: https://github.com/Automattic/wp-calypso/pull/14984
