### ISSUE TITLE
.FR domains: not all whois data can be edited

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#14989]
Not all whois data can be edited:

For individuals, the name, first name,date and place of birth fields cannot be edited.
For organizations: the company name, name, first name and
identifiers (employer identification number (EIN) number, brand, etc.)
cannot be edited

Source: https://www.afnic.fr/medias/documents/Documents_de_reference__techniques/Afnic_Procedure_Guide.pdf

**Comment by deBhal** [comment]
I haven't dived in yet, I'm just looking at the open issues, but the big warning in section 2.1.2 on page 7 of the AFNIC guide is saying that we can't update those fields with a _contact_ update operation.

I think we change those fields through a _domain_ update (2.2.6, page 12), which is probably considered a contact change and involving locking complications, but I think that that's largely in line with other TLDs.

Needs some proper investigation, though.

**Comment by deBhal** [comment]
> which is probably considered a contact change and involving locking complications

Now I understand the locking situation a little better, I don't think there will be any locking problems, as that's an ICANN thing not relevant to ccTLDs (except .CA).

**Comment by hewsut** [comment]
Fixed in #17378 _and_ #17387.
