### ISSUE TITLE
Comments: RTL comments management support

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#14980]
Let's make sure our comments management view makes sense with a RTL language set. 

We may want to use `components/auto-direction` to help better display comment text.

To enable testing in dev for a RTL language, open `development.json` and set `rtl` to `true` before restarting.

**Comment by Copons** [comment]
Is this by any chance fixed in https://github.com/Automattic/wp-calypso/pull/14981?

**Comment by gwwar** [comment]
@Copons this is mostly a reminder task so we test periodically in a RTL mode. 😄 14981 should help I think.

**Comment by Copons** [comment]
We might consider this closed after https://github.com/Automattic/wp-calypso/pull/17098.
Basically I asked i18n for a review of the whole section and fixed the one visual issue that was found.
