### ISSUE TITLE
Line height issue

### ISSUE THREAD

**Issue by satrya** [Automattic/wp-calypso#14986]
Hi,
There is an issue with the line height of the Editor, I am using macOS.

### Web version
![web](https://user-images.githubusercontent.com/891643/27003617-4eafdeb8-4e24-11e7-8252-088ad6396364.png)

### App version
![app](https://user-images.githubusercontent.com/891643/27003621-5ef183e4-4e24-11e7-889b-260818c5f6c0.png)

Does anyone know what causing the line height in the Desktop version looks so tight?

**Comment by designsimply** [comment]
I did a side-by-side check and found that the line height in the WordPress.com Desktop App looks the same for me compared to Chrome:

![screen shot 2017-06-12 at mon jun 12 1 24 29 pm](https://user-images.githubusercontent.com/1119271/27051275-be57b1e2-4f72-11e7-9915-79731cb5aba1.png)

![screen shot 2017-06-12 at mon jun 12 1 20 15 pm](https://user-images.githubusercontent.com/1119271/27051371-11042592-4f73-11e7-952b-a6891a79b656.png)

I tested using WPDesktop 2.5.0, WPDesktop 2.6.0-beta1, and Chrome 58.0.3029.110 on Mac OS X 10.12.5. May I please ask what WPDesktop version you are running as well as your OS type and version?

**Comment by satrya** [comment]
Pretty much the same with you, 
- WP Desktop 2.5.0 
- Version 58.0.3029.110 (64-bit)
- macOS Sierra 10.12.5

![chrome](https://user-images.githubusercontent.com/891643/27066569-49b56d1c-502f-11e7-99ac-37592a6f69a1.png)
![macos](https://user-images.githubusercontent.com/891643/27066570-49bb1708-502f-11e7-8b8b-a34cb94a099f.png)
![wpdesktop](https://user-images.githubusercontent.com/891643/27066571-49d218f4-502f-11e7-8c1a-0f6336c2339b.png)

Where I can get the 2.6.0-beta 1?

**Comment by designsimply** [comment]
I'm not sure why I can't see the line height issue in the same way you can. Would you be willing to try uninstalling and reinstalling WPDesktop as a troubleshooting step by chance?

Nice find on #14723!

> Where can I get the 2.6.0-beta 1?

You can join the beta from the Google Play Store on your device (under “Become a beta tester”).

You might also like: https://make.wordpress.org/mobile/

**Comment by satrya** [comment]
Just tried to reinstalling the issue is still there

**Comment by designsimply** [comment]
Thanks for trying that. I'm not sure how to repeat the problem on my side yet.

**Comment by designsimply** [comment]
@satrya, I just tested again using WPDesktop 2.6.0-beta2 and I still don't see any problems with line height that looks too tight in the Editor. Is there any possibility you have some underlying HTML or CSS saved in your "Pih, Positif!" post that could be causing the difference for you?

![image](https://user-images.githubusercontent.com/1119271/27358790-76d198c4-55d5-11e7-92cc-bad065036b57.png)
<sup>Tested with WPDesktop 2.6.0-beta2 on Mac OS X 10.12.5.</sup>

**Comment by lancewillett** [comment]
> Where can I get the 2.6.0-beta 1?

@satrya You can get beta versions by changing the app settings under "Release Channel":

![screen shot 2017-06-20 at 15 44 34](https://user-images.githubusercontent.com/66797/27359219-77654cc8-55cf-11e7-8ba5-e9624df404f3.png)

**Comment by satrya** [comment]
@lancewillett thanks!
@designsimply Just updated to version 2.6.0-beta2, it fixed the issue.

![fixed](https://user-images.githubusercontent.com/891643/27391708-d83ff62e-56ce-11e7-8f56-299a6153e863.png)

**Comment by designsimply** [comment]
Sweet! 🎉 Going to close this issue then. Thank you for the initial report and working through the troubleshooting steps.
