### ISSUE TITLE
Republicize: Visual bug when there isn't connections

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#14999]
![image](https://user-images.githubusercontent.com/77539/27037070-335d9ada-4f5d-11e7-8af3-18eb5698aa1d.png)

**Comment by retrofox** [comment]
@iamtakashi would you like to help with this?

**Comment by iamtakashi** [comment]
@retrofox Is the issue the squashed notice? Can we move it to the same place as other notice for Republicize?

![image](https://user-images.githubusercontent.com/908665/27038369-b4c4259c-4f82-11e7-9c4c-d35b418b8bab.png)

**Comment by retrofox** [comment]
> @retrofox Is the issue the squashed notice?

Yes, it is

> Can we move it to the same place as other notice for Republicize?

Sure.

**Comment by retrofox** [comment]
> Can we move it to the same place as other notice for Republicize?

Thinking well this warning is 100% related to connections, so should we keep it into the connections box?

**Comment by iamtakashi** [comment]
Logically, your thinking makes more sense. But with the space, even we removed the padding around the notice, it won't look good. If we have time we could design a different way to communicate the issue (tooltip or something?), but at the moment, moving it below the header seems to be the best quick fix.

**Comment by retrofox** [comment]
Just FYI, it looks nice when the viewport is tight.

![image](https://user-images.githubusercontent.com/77539/27039890-b74c4f50-4f65-11e7-910b-8f8c08862a6f.png)

**Comment by iamtakashi** [comment]
> Just FYI, it looks nice when the viewport is tight.

That's what I mean :) The current style does need a wider space. Therefore, I'm suggesting to move it to below the header. We already use the space to communicate what's happening (happened) related to Republicize. That's why there is my first choice.
