### ISSUE TITLE
"Site I need help with" is undefined

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#14997]
We've had a couple of reports that tickets and chats are coming in with the "site I need help with" info as "undefined." Something similar happened not too long ago. We should fix this and see if we can add a test to prevent it from happening again.

**Comment by unDemian** [comment]
PR: https://github.com/Automattic/wp-calypso/pull/15013

**Comment by ockham** [comment]
Is it possible that this was coincidentally fixed by https://github.com/Automattic/wp-calypso/pull/13293/files#diff-bc7120f8349b381d24b34e6e3a2daeb2R255 (~4 hrs after this issue was filed)?  /cc @mattwondra @omarjackman

**Comment by unDemian** [comment]
Unfortunately no, the issue like @mattwondra said appeared because of the missing `siteId` from `help-contact-form` which would make the site `undefined` for both happychat start and kayako submit https://github.com/Automattic/wp-calypso/pull/15013/files#diff-bfbe01f0a66b1aa6a6708379328f1d66L150

**Comment by unDemian** [comment]
I'll update the estimate for this to to `5` as there was a lot of back and forth architectural discussion and it's waiting a new round of feedback.
