### ISSUE TITLE
Plugins: Jetpack Disconnect Dialog should be more helpful

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#1499]
Currently:

<img width="575" alt="screen shot 2015-12-11 at 10 56 57 am" src="https://cloud.githubusercontent.com/assets/437258/11748466/705a3cb2-9ff6-11e5-9e60-d9c38c5b4c39.png">

I think we're missing a bunch of opportunities here to do something more helpful and custom. You don't just lose access to WordPress.com features, you literally can no longer administer your site. It will be gone. We should add a Drake image and perhaps a bulleted list of what to expect, and perhaps info about how to reconnect.

Not sure if the Drake would work on top of the fade out, but I played around with something like this:

<img width="606" alt="screen shot 2015-12-11 at 11 12 57 am" src="https://cloud.githubusercontent.com/assets/437258/11748812/328dfa2a-9ff8-11e5-8314-5a1c7ec6cbf4.png">

cc @alternatekev

**Comment by alternatekev** [comment]
@rickybanister This is great. I had added some extra text to the removal window in a PR yesterday but removed it again because it wasn't flowing very well. Your solution fixes a lot of the problems I had with it.

What if we change from "Cancel" and "OK" to "Stick Around" and "Disconnect" or something similar?

**Comment by rickybanister** [comment]
Sure, I just copied the default pattern—I should have thought more about the buttons. We should use a `scary` button as well.

**Comment by rickybanister** [comment]
We now have a whole survey for this, closing as irrelevant.
