### ISSUE TITLE
Search: clicking the x doesn't reset the results

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#1500]
When searching for something, clicking the X clears the search field, but the search results don't reset back to the original state.

Browser: Chrome Mac
Video: https://cloudup.com/cedQ2GRIGVT

Noticed it when testing https://github.com/Automattic/wp-calypso/pull/1358

**Comment by rralian** [comment]
FWIW, I am unable to recreate this bug anymore, testing the search field for posts in all-sites, wpcom, and jetpack. Also testing in chrome on the mac. Are you still seeing this?
