### ISSUE TITLE
Reader: search formatting issues on Windows at mobile breakpoint

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#15030]
On IE11 and Windows Phone 8 (Lumia 830 on Browserstack), the search box is misaligned on Reader Search at <640px width:

<img width="335" alt="screen shot 2017-06-13 at 10 33 32" src="https://user-images.githubusercontent.com/17325/27076085-1161b23c-5024-11e7-800b-dc3b090f7adf.png">
<img width="353" alt="screen shot 2017-06-13 at 10 33 58" src="https://user-images.githubusercontent.com/17325/27076084-11606224-5024-11e7-965b-b68d01148b56.png">

**Comment by jancavan** [comment]
@bluefuton Are you still seeing this issue? I think I fixed the Search box hiding behind the masterbar in this PR: https://github.com/Automattic/wp-calypso/pull/15017.

**Comment by jancavan** [comment]
Closing as I'm no longer able to repro. Feel free to reopen if still an issue. This is what I'm seeing on Lumia 930 on Browserstack. Lumia 830 isn't listed as option?

<img width="402" alt="screenshot 2017-07-19 20 21 22" src="https://user-images.githubusercontent.com/4924246/28399139-16b43ae4-6cc0-11e7-927d-0c0d45aa1bc4.png">

The cards seem to be cropped though? But that's a separate issue.
