### ISSUE TITLE
WooCommerce: Email settings

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15040]
Here's the design for email settings (some of the copy may be subject to change):

![email-settings](https://cldup.com/Ana12I7-Z1-3000x3000.png)

Notes:

* Customer invoice, customer note and reset password emails are missing from the list because they don't need an 'enable' option. There's no case that I can think of to disable the password reset email and the other two are manual anyway.
* We should set the default base color to WP blue or something neutral like #3c3c3c (this would match the email text color)
* We should probably set the default footer text setting to something other than "Store name powered by WooCommerce" too. Just "Store name"? Open to suggestions there.

**Comment by timmyc** [comment]
> We should probably set the default footer text setting to something other than "Store name powered by WooCommerce" too. Just "Store name"? Open to suggestions there.

Found this issue while searching when I was about to create a new issue :) - so here is a footer from a current order confirmation email:

![_care_for_animals__new_customer_order__418__-_october_2__2017_-_timmydcrawford_gmail_com_-_gmail](https://user-images.githubusercontent.com/22080/31094000-69c16d82-a768-11e7-933e-06fc75adfa2f.png)

It seems that sine all store users are on the Business plan, which one of the benefits is to suppress/modify the footer credit, we should just use whatever footer credit value is set on the current site.

**Comment by jameskoster** [comment]
Tbh, I'm thinking we should probably remove this credit in core. It doesn't benefit the store owner or the customer in any way.

**Comment by justinshreve** [comment]
@jameskoster Just a heads-up that Bartosz is getting started on this. Is there any adjustments we need to make to the design before he gets to working on the UI?

**Comment by jameskoster** [comment]
Nope, all good. Only difference is that the Mailchimp card will be there as well.

**Comment by justinshreve** [comment]
This is live now.
