### ISSUE TITLE
Login: Stuck on 2FA page after authentication with Google

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#15056]
Starting at URL: http://calypso.localhost:3000/log-in

This happens when you first try to log in with an account which has 2FA enabled but don't confirm and instead go back to the previous page to log in with Google. Once you have successfully authenticated to Google, the popup closes and you are redirected to the 2FA login screen

![bug-login-2fa-google-2](https://user-images.githubusercontent.com/230230/27126056-8f1df6f4-50f6-11e7-8651-be0a3371ae32.gif)

**Comment by pento** [comment]
I believe this was fixed by #17156, I'm unable to reproduce this behaviour locally.

@Tug, can you confirm that it's working for you?

**Comment by Tug** [comment]
Indeed it's fixed now
