### ISSUE TITLE
Editor: visualize embeds such as Gists in visual post editor

### ISSUE THREAD

**Issue by Clorith** [Automattic/wp-calypso#1505]
When editing a post already made in the WP admin backend on a self hosted instance, I put in a link to a gist which gets embedded (and previewed beautifully in the backend).

When editing in Calypso, I can see the URL if i go to HTML view, but in the visual mode, neither the preview nor the URL is present, making it really easy for someone to accidentally remove embedded content without being aware of it during an edit.

With some nifty cursor movements magic, you can see the embed area, it's invisible and shows as a new line, but you can get the pop-over "X" for removing it with keyboard navigation, a visual of this is in the attached screenshot.
![cloudup-nmjy3hiircd](https://cloud.githubusercontent.com/assets/468735/11751617/e662d8d0-a03a-11e5-804f-701b8451e322.png)

Version data:
Calypso (Windows build 1.1.2)
WordPress 4.4
Jetpack 3.8.1
# calypso-gaps

**Comment by lancewillett** [comment]
Thanks for mentioning this, Clorith.

**Comment by danielbachhuber** [comment]
Related #1095

**Comment by lancewillett** [comment]
See WIP on a broader solution to this in #5070. Once that lands this will need re-testing.

**Comment by kriskarkoski** [comment]
I just had a user report of this in #2985014 and after some testing can repro with an Gist URL containing a capitalized username such as https://gist.github.com/Viper007Bond/2314628, but the same URL formatted with all lowercase works (ex. https://gist.github.com/viper007bond/2314628)

My username happens to be all lowercase so it just worked, but the users was capitalized causing their Gist embed to fail and there is no indication in the Visual tab it's there, only if you switch to HTML do you see the URL.

**Comment by Copons** [comment]
I've located the issue, it's server side, working on a fix as we speak.

**Comment by rralian** [comment]
@Copons did the fix for this land?

**Comment by Copons** [comment]
@rralian Yes! Fixed in D4920-code, going to close the issue.

**Comment by rralian** [comment]
Yeah, I just tested with the problematic gist above and it worked great. Nice work!
