### ISSUE TITLE
Follow success notification?

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15062]
Currently in Reader, when the user clicks/taps a Follow button, it changes from blue "Follow" to green "Following" and that's it. I'm starting to think that's too subtle. It's possible to click/tap Follow without even noticing it. And if you did it on purpose, it's possible to wonder if it worked.

So, a suggestion: Let's add a green notice that says "You are now following _Site Name_." (If no site name, use "You are now following _URL_.")

I'm thinking the green "is-success" type notice. 

<img width="565" alt="screen shot 2017-06-13 at 11 00 06 am" src="https://user-images.githubusercontent.com/24388/27096937-7ecd281c-5027-11e7-9c28-b3d217bed3ae.png">

It would be great if it auto-dismissed, but I don't know if that's possible.

The goal here is just to celebrate that the user followed something, making it super clear that the follow worked. This should happen wherever the user can click a Follow link - basically everywhere in Reader.

Thoughts? @jancavan @blowery @bluefuton

**Comment by blowery** [comment]
Yup, notices can take a duration: https://github.com/Automattic/wp-calypso/blob/master/client/state/notices/README.md

**Comment by blowery** [comment]
This should be really easy to do.

**Comment by fraying** [comment]
@blowery Awesome! PR?

**Comment by blowery** [comment]
Working on it. :)

**Comment by blowery** [comment]
@fraying we currently flip the button state optimistically and flip it back if the follow fails. Should we fire the notice optimistically, or fire it when they're actually following the site? 

If we fire it immediately on press, when the follow fails, you end up getting two notices in quick(ish) succession. 

If we fire it when the response comes in, it feels like there's a lag, but it also serves as a proper confirmation...

Thoughts?

**Comment by blowery** [comment]
Should clicking on the notice take you anywhere?

**Comment by fraying** [comment]
@blowery My 2c: I think firing the notice optimistically would be a good move. It'd better match the button state, and the majority of the time it'd work out (since we're inviting someone to follow something that's already on the page, already in the index, etc). The double-notice thing is a bummer, but that should be a rarity, and it'd look like an error because, well, it is an error, so that seems ok. What do you think?

**Comment by fraying** [comment]
@blowery Don't think clicking the error should take you anywhere. People may click it to try and make it go away, and I worry that click taking them somewhere would be a bad surprise. Make sense?

**Comment by fraying** [comment]
@blowery Forgive me for expanding a bit, but should UNfollowing also produce a notification like this? Is there a version of this notification banner that includes an "are you sure?" or "undo?" link?

**Comment by fraying** [comment]
One more question! Can we also trigger this for following Tags? "You are now following [tagname]"?

**Comment by blowery** [comment]
> Don't think clicking the error should take you anywhere.

oh no i meant the success notice. maybe it would take you to the site stream? just spitballin.

> Forgive me for expanding a bit, but should UNfollowing also produce a notification like this? Is there a version of this notification banner that includes an "are you sure?" or "undo?" link?

I've been wanting confirmation on unfollow for a while. We _can_ stick an undo action on the notice... I feel like someone else in calypso does this..

**Comment by blowery** [comment]
https://wpcalypso.wordpress.com/devdocs/design/notices

**Comment by blowery** [comment]
> One more question! Can we also trigger this for following Tags? "You are now following [tagname]"?

Sure. Different code path but easy enough.

**Comment by fraying** [comment]
> oh no i meant the success notice. maybe it would take you to the site stream? just spitballin.

Oh right! Yeah, I thought about that, too, but I figure, in most cases, the link to the site was right next to the Follow link, so if you wanted to go to the site, there's already a convenient way to do so. I also worry that people may click the notification intending to dismiss it, so they may be surprised if it took them somewhere.

**Comment by blowery** [comment]
hmmm doing it optimistically turns out to be a fair bit more work. we need to look up the site / feed info by feed url instead of by feed id, since that's all we have. digging further.

**Comment by blowery** [comment]
> I also worry that people may click the notification intending to dismiss it, so they may be surprised if it took them somewhere.

totally makes sense

**Comment by jancavan** [comment]
Closing this. We implemented this before, but decided to remove it as it was becoming obtrusive: https://github.com/Automattic/wp-calypso/issues/21668
