### ISSUE TITLE
Reader Site Search: data tracking validation

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#15060]
This issue is to make changes to what we are tracking in Site Search. 

### Remove action parameter from Site results loaded (traintracks):

The action parameter should only be used for interact events (not render events). We will need to remove the action=search_stream_sites parameter when site results are loaded.

### Add "Site result" specific parameter:

We currently cannot differentiate actions taken on Site results versus Post results on these events:
- calypso_reader_site_followed
- calypso_traintracks_render (loading search results)

Not sure what is the best approach. Here are a few options to change parameters on all Site search result renders and interactions:
- change fetch_algo from `reader/manage/search:0` to `reader/manage/search/site:0`
- change source from `search` to `search-site`

@gibrown, did you have ideas here?

### Add missing follow_source for Site search results:

When we follow a site from the site results, we currently do not define the `follow_source` parameter. This should be `follow_source=search-results`.

### Add missing follow interacts for Post search results:

We are missing  the calypso_traintracks_interact when a user follows a site from a Post search result.

## What we have

Search Page:

- **Search page view:** `calypso_page_view` with path=/read/search
- **Search loaded**: `calypso_reader_search_loaded`

Search Performed:

- **Search page view**: `calypso_page_view` with url=/read/search?q=search_term
- **Search performed**: `calypso_reader_search_performed`
- **Site results loaded (traintracks)**: `calypso_traintracks_render` with same as above and action=search_stream_sites

Site Results Interaction:

- **Site followed**: `calypso_reader_site_followed` with _follow_source=undefined_
- **Site followed (traintracks)**: `calypso_traintracks_interact` with action=site_followed
- **Site clicked**: `calypso_reader_feed_link_clicked`
- **Site clicked (traintracks)**: `calypso_traintracks_interact` with action=feed_link_clicked
- **Blog previewed**: `calypso_reader_blog_preview`
- **Site URL clicked**: `calypso_reader_site_url_clicked`
- **Site URL clicked (traintracks)**: `calypso_traintracks_interact` with action=site_url_clicked

Post Results Interaction:
- **Site followed**: `calypso_reader_site_followed` with follow_source=search-results
- _Missing site followed traintracks interact events_
- **Blog previewed**: `calypso_reader_blog_preview`
- **Permalink clicked**: `calypso_reader_permalink_click`
- **Permalink clicked (traintracks)**: `calypso_reader_permalink_click` with action=permalink_click

**Comment by samouri** [comment]
@aaronyan, this is awesome! Thanks for looking into our events.

Can we turn this into a todo checklist? I'll start it now, but please add in any items that I may have forgotten. I'm also unsure what the status of the various parts of this are

**Comment by samouri** [comment]
TODO:
- [ ] remove action parameter from render events (specifically for site results in search-stream)
- [ ] differentiate between actions taken on site result vs. post result on follow + render events

**Comment by bluefuton** [comment]
> Remove action parameter from Site results loaded (traintracks):
> The action parameter should only be used for interact events (not render events). We will need to > remove the action=search_stream_sites parameter when site results are loaded.

Does this mean we should also drop the action from other similar stream render events like `following_manage_search` and `following_manage_subscription`?

**Comment by bluefuton** [comment]
re: 

> Does this mean we should also drop the action from other similar stream render events like following_manage_search and following_manage_subscription?

I've deduced "yes" and removed them in #15513.
