### ISSUE TITLE
Follow icons visible behind search box

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15066]
<img width="299" alt="screen shot 2017-06-13 at 12 31 58 pm" src="https://user-images.githubusercontent.com/24388/27100875-6cfb7eec-5034-11e7-9cde-00f43daae901.png">

Do a search on wpcalypso and scroll it - look at the right side.

**Comment by samouri** [comment]
I couldn't repro this in Safari.  
Is this only at a specific browser width?

**Comment by fraying** [comment]
Oh interesting. Looks like it loads correctly, but then if you change the width of the browser the bug happens.

**Comment by jancavan** [comment]
It looks like it's related to the top margin in stream issue. Should be fixed in: https://github.com/Automattic/wp-calypso/pull/14881

**Comment by fraying** [comment]
Fixed!
