### ISSUE TITLE
My Plan: Start Customizing Buttons Fails on AT Sites

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#15063]
On a site that has already gone through automated transfer, there is a link to the customizer that isn't being built correctly.

The link can be found on the Plans > My Plan page:
`https://wordpress.com/plans/my-plan/$site`

The link currently goes to 
`https://wordpress.com/customize/$site`

But this link fails on an AT site. We get around this in the Customize button next to "Themes" in the left-hand navigation by linking to customizer via wp-admin:
`https://example.com/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fplans%2Fmy-plan%2Fexample.com`

#### Steps to reproduce
1. Use an AT site, Starting at URL: https://wordpress.com/plans/my-plan/$site
2. Scroll down to the "Start Customizing" button (see screenshot)
![plans_ _site_title_ _wordpress_com](https://user-images.githubusercontent.com/933450/27097032-f8178df2-5040-11e7-9996-835394ce253e.jpg)

3. Click the button, you'll be sent to https://wordpress.com/customize/$site
4. This link fails on an AT site (see gif)
![customizer-fails](https://user-images.githubusercontent.com/933450/27097221-83677eee-5041-11e7-8e7c-d3035cf9dcec.gif)

#### What I expected

To be able to open the customizer using the "start customizing" button

#### What happened instead

I'm lead to a link that I'd expect to open the customizer, but that links always fails

#user-report 409624-hc

**Comment by vindl** [comment]
I tried reproducing this on various Atomic sites, both brand new and very old ones, and in all cases the Customizer loads correctly for me.
