### ISSUE TITLE
Posts/Sites tab should remain active in between searches

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15079]
#### Steps to reproduce
1. Starting at URL: http://wpcalypso.wordpress.com
2. Do a search and get some results.
3. Compress the browser width until you get the Posts / Sites tabs.
4. Click on the Sites tab to view the list of Site results.
5. Enter a new search term.

#### What I expected

The Sites tab to stay active and show the site results from the new search. (This would be consistent with how the Relevance/Date toggle works.)

#### What happened instead

Tab switches to Posts.

#### Browser / OS version

Latest Safari.

**Comment by samouri** [comment]
fixed in https://github.com/Automattic/wp-calypso/pull/15106
