### ISSUE TITLE
Login: Fix multiple console errors when polling push notification status

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#15084]
Steps to reproduce:

1. Start at https://wpcalypso.wordpress.com/log-in
1. Log in as a user that has a push token.
1. Land at https://wpcalypso.wordpress.com/log-in/push
1. Check the console for errors.

<strong>Result:</strong> the following error appears in the console every few seconds:

> Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400)
> https://wordpress.com/wp-login.php?action=two-step-authentication-endpoint

![screen shot 2017-06-13 at tue jun 13 4 48 03 pm](https://user-images.githubusercontent.com/1119271/27108059-9a8645d0-5058-11e7-8250-316c127867f5.png)
<sup>Seen at https://wpcalypso.wordpress.com/log-in/push using Safari 10.1.1 on Mac OS X 10.12.5.</sup>

#manual-testing

**Comment by fabianapsimoes** [comment]
I can no longer reproduce this.
