### ISSUE TITLE
Relevance/Date tab should remain active when changing Posts/Sites tab

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15083]
#### Steps to reproduce
1. Starting at URL: http://wpcalypso.wordpress.com
2. Do a search.
3. Reduce browser width until you see the Posts/Sites tabs.
4. Click Sites Tab
5. Click "Date" sort 

#### What I expected

Sites tab would stay active, results would change to date sort.

#### What happened instead

Active tab changed to Posts.

#### Browser / OS version

Latest Safari.

**Comment by samouri** [comment]
fixed in https://github.com/Automattic/wp-calypso/pull/15106
