### ISSUE TITLE
Bad formatting on sidebar on /me at mobile screen width

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#15088]
#### Steps to reproduce
1. Starting at URL: Visit https://wordpress.com/me with a mobile screen width
2. Observe the "back" button to open the sidebar

Started when https://github.com/Automattic/wp-calypso/pull/14829 was merged, despite that being a woocommerce-specific set of changes.  We must be loading those stylesheets regardless?

cc: @kellychoffman 

#### What I expected
<img width="384" alt="screen shot 2017-06-13 at 10 52 32 pm" src="https://user-images.githubusercontent.com/7233112/27113473-024e1f1c-508b-11e7-83a8-7db89c422378.png">

#### What happened instead
<img width="379" alt="screen shot 2017-06-13 at 10 50 27 pm" src="https://user-images.githubusercontent.com/7233112/27113479-04fbf1d0-508b-11e7-8e45-e4d3808cfa2e.png">

#### Browser / OS version
Seen here in OSX Chrome

#### Context / Source
#automated-testing

**Comment by kellychoffman** [comment]
It looks like `client/extensions/woocommerce/style.scss` is being pulled in. Do you know why/how?

**Comment by kellychoffman** [comment]
Chatted with Kevin about it and am working on a fix.
