### ISSUE TITLE
Help: Chat open in multiple tabs doesn't show full conversation

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#1508]
When you have the chat window open in multiple browser tabs, only the chat window in the current tab displays the full conversation. In all other browser tabs, the chat window shows the operator replies but not the user's side of the conversation.

Steps to reproduce:
- Start a chat at https://wpcalypso.wordpress.com/help/contact
- Navigate to a new browser tab (e.g. by following a link from the chat operator, which opens in a new tab, or by following a link in Calypso to a WP Admin page)
-> The chat comes with you to the new tab, so you can continue chatting there.
- Continue chatting with the operator in the new tab
- Switch back to the previous browser tab
Result: You'll see the full conversation from before you opened the new tab, but everything after the new tab was opened will only show the operator's side of the conversation.

This may be a limitation in Olark, but it feels like a bug from a user perspective. When I return to my original browser tab/window, I expect the full chat to be there for me. (If it's a limitation in Olark, is there another way we can resolve this?)

**Comment by dllh** [comment]
@rachelmcr do you think this is a terribly common use case? I'm trying to understand how we should prioritize this -- whether we should consider it a blocker for launch or something we can dig into later.

**Comment by omarjackman** [comment]
> This may be a limitation in Olark, but it feels like a bug from a user perspective. When I return to my original browser tab/window, I expect the full chat to be there for me. (If it's a limitation in Olark, is there another way we can resolve this?)

I actually contacted olark about a similar issue back in September when I was developing the feature and was told "we recommend only having one tab / window open at a time". 

Here's a snippet of my transcript:
![screen shot 2015-12-15 at 2 29 39 am](https://cloud.githubusercontent.com/assets/1854440/11804722/e9579922-a2d3-11e5-8e9d-faac35d81529.png)

I don't think there is any way around this short of raising the issue with Olark again.

**Comment by omarjackman** [comment]
@rachelmcr I think in general if you refresh the page all of the text you've typed will be there as well as in the transcript.

**Comment by dllh** [comment]
Yeah, seems like something pretty much out of our control, so closing this down. Short of figuring out some way to proxy all Olark messages back through us so that we can make the client update in any open tabs, I don't think there's much we could do, and I think that'd be a pretty big undertaking.

**Comment by rachelmcr** [comment]
I think closing this is fine if it isn't something we can really control, especially if Olark recommends only having one tab open. That said, in my testing, all the links I got from the chat operator in the chat opened in a new tab, so if we have control over that we should probably avoid having links open in a new window/tab. (We might want to sanity check that with chat operators to see if there are cases where they find the benefit of a new tab outweighs any confusion from having the chat open in multiple tabs.)
