### ISSUE TITLE
Search: Sites: "Updated" text weirdness

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15081]
The URL/updated lines are a little funny. Sometimes they don't show the whole URL:

<img width="894" alt="screen shot 2017-06-13 at 3 13 39 pm" src="https://user-images.githubusercontent.com/24388/27107029-e5b0acca-504a-11e7-8e46-6e1c393e8e1a.png">

And sometimes they're missing a space:

<img width="794" alt="screen shot 2017-06-13 at 3 13 57 pm" src="https://user-images.githubusercontent.com/24388/27107063-f5c73822-504a-11e7-9fca-36574eb9531c.png">

**Comment by jancavan** [comment]
Duplicated of: https://github.com/Automattic/wp-calypso/issues/15119
