### ISSUE TITLE
.FR: An "Individual" registration is private by default, update UI to show it

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#15092]
#### Steps to reproduce
1. Starting at URL:
2.
3.
4.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to check out a `.fr` domain and during the process noted presence of text about privacy included by default for domains where applicable. While not specifically mentioning `.fr` by name, I believe this means the behavior described in this issue has been addressed.
