### ISSUE TITLE
Login: Social Signup M3 design review

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#15101]
Compiling a list of issues found during a design and copy review of Social Signup M3.

---

1. The magic link screen at `/log-in/link` has some design inconsistencies. It's missing a title (do we need something like "Email me a login link"?). The "Enter a password instead" link extends past the container and has the wrong color.
<img width="846" alt="screen shot 2017-06-14 at 09 24 13" src="https://user-images.githubusercontent.com/448298/27135237-0408d152-50e6-11e7-8dcb-bea547a1a501.png">

2. There should be some kind of separation between the `Log In` button and `Or login with your existing social profile`. We should keep it consistent with the sign up page.
<img width="431" alt="screen shot 2017-06-13 at 09 20 17" src="https://user-images.githubusercontent.com/448298/27136071-461730aa-50e8-11e7-8ac0-909f45e14ebe.png">

3. Use a regular notice instead of global notice for existing WPCOM user when trying to login with Google.
<img width="1433" alt="screen shot 2017-06-13 at 09 21 34" src="https://user-images.githubusercontent.com/448298/27136012-1fe99738-50e8-11e7-873f-8208d8e373ae.png">

4. Clear notices when 2FA method is switched. Here, the SMS notice stays on the screen even after clicking to use authenticator app. Originally reported [here](https://github.com/Automattic/wp-calypso/issues/14173#issuecomment-302134542).
<img width="472" alt="screen shot 2017-06-13 at 09 30 02" src="https://user-images.githubusercontent.com/448298/27136191-9f45e7de-50e8-11e7-9e05-21482b3dbfed.png">

#manual-testing

**Comment by danhauk** [comment]
Related to # 4 above: We should also clear any form validation errors when the 2FA method changes. 

<img width="448" alt="screen shot 2017-06-13 at 09 30 46" src="https://user-images.githubusercontent.com/448298/27136337-1545ea74-50e9-11e7-9966-900f033b4205.png">

To reproduce this (must do these steps all within a minute to get SMS limit message):

1. Request text message code
2. Click to use Authenticator app, green sent text message notice remains on screen
3. Enter an incorrect code, invalid code form validation message appears
4. Click to request another code via text message
5. Now you have the SMS limit error and the invalid authenticator code message

**Comment by danhauk** [comment]
Proposed design for visual separation between regular log in form and social section.

<img width="458" alt="screen shot 2017-06-14 at 10 57 10" src="https://user-images.githubusercontent.com/448298/27139211-63a330bc-50f0-11e7-8eca-cd426731eaef.png">

I thought about making it consistent with our [existing sign up form](https://user-images.githubusercontent.com/448298/27139243-7990a0f8-50f0-11e7-9de1-20293bf01fa9.png), but it came back to the discussion earlier about too many subtle shades of gray in our UI. (We should probably revisit the sign up form to remove the gray background and bump up the font size)

Using a white background will keep it clean and keep the contrast up.

**Comment by scruffian** [comment]
I've started #15117 for these.

**Comment by ranh** [comment]
On Sign Up, the validation notice "This is a required field" could be improved:

<img width="427" alt="ranimac3 screenshot 2017-06-15 at 14 17 49" src="https://user-images.githubusercontent.com/426518/27179034-811be3c4-51d5-11e7-9521-61e64688777d.png">

For the email field, we can reuse the copy for invalid emails:

> Enter a working email address, so you can receive our messages.

For the username field, we can at least change the generic notice to be more specific:

> Enter a username of your choice.

**Comment by ranh** [comment]
Let's change the following validation notices for passwords.

Log in, blank password:

> Don't forget to enter your password.

(currently: Please be sure to enter your password.)

Log in, bad password:

> Oops, that’s not the right password. Please try again!

(currently: Oops, looks like that’s not the right password. Please try again!)

Sign up, blank password:

> Don't forget to enter a password.

(currently: Password must be at least 6 characters.)

Sign up, weak password:

> This password is too easy to guess. Add letters, numbers, or special characters to make it stronger.

(currently: Your password is too weak: you can improve it by adding additional uppercase letters, lowercase letters, or numbers.)

**Comment by danhauk** [comment]
The magic link page is being fixed in #15163

**Comment by ranh** [comment]
The copy above the social signup buttons is:

> Or login with your existing social profile:

It should be:

> Or log in with your existing social profile:

**Comment by ranh** [comment]
On Android, the status notice ("creating your account") after signing up with Google is at the bottom of the screen, and you have to scroll down to see it.

I didn't get a chance to take a screenshot, it goes to the next page very fast. But I tested on Android 7.0 and Chrome 58.0.3029.83

**Comment by scruffian** [comment]
>On Android, the status notice ("creating your account") after signing up with Google is at the bottom of the screen, and you have to scroll down to see it.

@ranh was this fixed by #15197?

**Comment by scruffian** [comment]
> Or log in with your existing social profile:

This is fixed by #15239

**Comment by scruffian** [comment]
I believe all the proposed changes here have now been made. @ranh, if you could confirm then we can close this...

**Comment by ranh** [comment]
@scruffian Retesting now

**Comment by ranh** [comment]
> @ranh was this fixed by #15197?

Yes, now when I return to the login screen, the view scrolls back and I get this notice:

![screenshot_20170619-151748](https://user-images.githubusercontent.com/426518/27284746-ba68c37e-5502-11e7-9b4a-b9d0e4edf99f.png)
