### ISSUE TITLE
Support: show a localized forum link for BR forums if user has `pt-BR` locale setting

### ISSUE THREAD

**Issue by gugaalves** [Automattic/wp-calypso#1510]
I'm in Brazil, so It's recommended to post new issues in BR forums. But using our app, when I click at Help > Forum, I'm beeing redirected to EN forums.

I think it's better if we have some language option in this app to set Language and use it to redirect users to to the forum on their language (if exists).

We only consistently staff the en and br forums, so other users might be better served in the en forums than their own language, so we need to think the better way to do it.

**Comment by lancewillett** [comment]
Changed to enhancement, it's not a bug but a nice improvement.

Confirmed that forum links in Brazilian locale still point to English version, seen at https://wpcalypso.wordpress.com/help in Mac-n-Chrome:

![screen shot 2016-04-07 at 11 10 29](https://cloud.githubusercontent.com/assets/66797/14361767/65fcc240-fcb1-11e5-81f6-3d0dc2b248e6.png)

**Comment by lancewillett** [comment]
CC @dllh This looks like a minor but helpful change.

**Comment by dllh** [comment]
@southp this would be a good first change for you to look at after our meetup. We can talk about it this week.
