### ISSUE TITLE
"Updated" lines showing when wide but not when narrow

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15119]
Do a search and sort it by date. Then adjust the browser width. I'm seeing the "updated" lines at wide widths when there are two columns...

<img width="622" alt="screen shot 2017-06-14 at 9 41 57 am" src="https://user-images.githubusercontent.com/24388/27144245-efa9970a-50e5-11e7-91c9-09a72468d742.png">

... but not at narrow width when there's one column.

<img width="742" alt="screen shot 2017-06-14 at 9 41 40 am" src="https://user-images.githubusercontent.com/24388/27144268-06bf1d7a-50e6-11e7-823d-979ab4654414.png">

I think we meant that to be the reverse: updated present for narrow/1-col but absent for wide/2-col.

cc @jancavan

**Comment by samouri** [comment]
solved in #15130
