### ISSUE TITLE
Super boost URL matches for site owners?

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15122]
Posting this after a conversation with @gibrown.

Because people will use search to find the sites they own, should we super boost (first result?) sites that the user owns that match a query? Maybe limit to URL queries? Needs more thought. But the goal is to avoid the "hey where's my site?" support queries.

**Comment by gibrown** [comment]
This requires some experimentation and shouldn't block launching, so marking low priority right now.

**Comment by cathymcbride** [comment]
Closing due to age.
