### ISSUE TITLE
Reader Search: date sorted sites aren't date sorted

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15121]
When sorting site results by date, they should be most recently updated to least recently updated, right? Currently they're not. 

The first result in a date sorted site search for "farm" is 11 days ago. The second is 27 minutes ago.

cc @gibrown

**Comment by samouri** [comment]
I'm assuming you were looking at the "updated X minutes ago". 
By clicking through to the underlying blogs I noticed that they are actually sorted correctly, but the times we are displaying in the search results are wrong.

Sadly they come from different data sources and I'm not sure how to reconcile the two.

@blowery ?

**Comment by gibrown** [comment]
I was wondering if anyone would actually notice. :)

We don't currently update the record every time someone publishes. So it is more pseudo date sorted. I can look into what the volume would be.

**Comment by fraying** [comment]
For example: In this date-sorted result for "Trump" the first result is a year old.

![screen shot 2017-06-26 at 9 12 10 am](https://user-images.githubusercontent.com/24388/27549053-a8ce4678-5a4f-11e7-83d9-e5ad01d667f1.png)

**Comment by gibrown** [comment]
I deployed a fix to keep RSS feeds up to date in the indexing. Keeping blogs up to date is a lot more indexing, so going to see how things perform as we launch.

**Comment by samouri** [comment]
@gibrown: whats the status of this issue?

**Comment by gibrown** [comment]
@samouri It is fixed for rss feeds, but on the back-burner because fixing it for blogs broke other things due to the volume.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I entered the search string `keyboard` in the Reader search box and sorted by `Date`.
The resulting blog posts were sorted by date as expected.
For the sites, it was not sorted by date, but the text (that was present in the original screenshot from 2017) about the last updated timestamp of the site is no longer present in the Site search results.
Therefore the site listing no longer implies (to my understanding) that site results are sorted by date.

I believe this should be sufficient to close this bug as `Closed - Not Reproducible`.
If this issue should remain open, please feel free to re-open this bug.

**Comment by worldomonation** [comment]
![Screen Shot 2021-02-22 at 1 59 43 PM](https://user-images.githubusercontent.com/6549265/108775953-96859800-7516-11eb-9ffb-466f480acb22.png)
