### ISSUE TITLE
Reader: Add back search suggestions to Search

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#15126]
Removed search suggestions from Search, but this removed it from both post recs and search results. They should only be removed from search results and should be added back to Search, right above the recs:

![screenshot 2017-06-12 14 07 45](https://user-images.githubusercontent.com/4924246/27149591-fb655eb8-50f8-11e7-90df-5cbb385cb8d5.png)

For reference: https://github.com/Automattic/wp-calypso/pull/13198#issuecomment-301113952

**Comment by marekhrabe** [comment]
Suggestion: can we activate this feature only for EN language? Those suggestions are always in english but Reader search is limited to local language of the user. For my language a lot of suggestions lead to empty results page.

**Comment by samouri** [comment]
@marekhrabe: definitely! We'll make sure to only show english suggestions to EN users

**Comment by samouri** [comment]
@marekhrabe: we  pull suggestions from two different places:
1. If there are no followed tags, we have a list: https://github.com/Automattic/wp-calypso/blob/master/client/reader/search-stream/suggestions.js
2. If there are followed tags, we use those: https://github.com/Automattic/wp-calypso/blob/master/client/reader/search-stream/suggestion-provider.jsx#L22

I just double checked and I believe number 1 is functioning properly based off of language.
I noticed that for some reason certain languages report that they are "en" when asking `i18nUtils` but I'm not sure why for now.  

What language are you using + are the suggestions by any chance tags that you follow?

**Comment by fraying** [comment]
@marekhrabe @samouri Search suggestions should not always be in English. If you've followed tags, we'e showing the tags you follow in whatever language. If you're not following tags, we have sets of suggested searches that are based on popular searches in your country. (At least, this is what I remember from when we last worked on it.) @blowery can you confirm?

**Comment by fraying** [comment]
Launched!
