### ISSUE TITLE
Data Tracking for Sites in Search

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15129]
Once we launch Sites in Search, we'll want to be able to answer this question:

When a follow occurs from a search result, was it triggered from a site result or a post result?

Will we have the data to answer that question?

And: Are there other questions we'll want answers to?

cc @martinremy @aaronyan

**Comment by aaronyan** [comment]
>Will we have the data to answer that question?

**Comment by aaronyan** [comment]
>Will we have the data to answer that question?

Not at the moment. We will want to add something to these events:

- calypso_reader_site_followed
- calypso_traintracks_render (loading search results)

I'm thinking we change the `source` property. On events that involve post results, we could have `source=search-posts`. On events that involve site results, we could have `source=search-sites`.

Not sure what is the best way to differentiate these events.

**Comment by fraying** [comment]
@blowery Any guidance here?

**Comment by aaronyan** [comment]
>And: Are there other questions we'll want answers to?

Sure! I would be curious on these questions:

- What percent of users see a post result and take any action on the result?
- What percent of users see a site result and take any action on the result?

There are two fixes that need to happen before we can answer this question:

- Differentiate the calypso_traintracks_render as mentioned in this [comment](https://github.com/Automattic/wp-calypso/issues/15129#issuecomment-308535009)
- Add the missing calypso_traintracks_interact when a user follows a Post search results

**Comment by aaronyan** [comment]
> Not at the moment. We will want to add something to these events:
> 
> calypso_reader_site_followed
> calypso_traintracks_render (loading search results)

@fraying: I made a mistake. calypso_traintracks_render is fine! We have different fetch_algos: `reader/manage/search:0` for site results and `read:search:posts/10` for post results.

The only blocker is to add the missing calypso_traintracks_interact when a user follows a Post search results

**Comment by fraying** [comment]
> What percent of users see a post result and take any action on the result?

These are tracked already, yeah?

> What percent of users see a site result and take any action on the result?

Good idea. The only actions a user can take on these, besides follow, is click to go to Site View or click to go to original site. Yeah, those would be good to track. Any interaction with the site result is a success.

**Comment by aaronyan** [comment]
> These are tracked already, yeah?

Yep, for the most part. We just need to fix the follow traintracks event here.

@blowery: would you be able to take a look at this? When a user follows a post search result, we are not firing a `calypso_traintracks_interact` event.

**Comment by aaronyan** [comment]
Created a specific issue #15139 to fix the follow bug for post search results.

**Comment by blowery** [comment]
@aaronyan @jake is going to take a look at it in the morning.

**Comment by samouri** [comment]
I think these two issues cover everything here: 

1. https://github.com/Automattic/wp-calypso/issues/15060
2. https://github.com/Automattic/wp-calypso/issues/15139

@aaronyan is this closable?
