### ISSUE TITLE
Some content breaks columns

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15124]
Check https://wpcalypso.wordpress.com/read/search?isSuggestion=1&q=chickens and play with the width. Happens in Safari and Chrome at around 1100px wide.

<img width="834" alt="screen shot 2017-06-14 at 11 22 52 am" src="https://user-images.githubusercontent.com/24388/27148096-e1d19822-50f3-11e7-870b-0ec0e5d09022.png">

@jancavan

**Comment by samouri** [comment]
I see this happening at widths between ~1200px --> ~1000px

**Comment by jancavan** [comment]
This issue has also been solved in: https://github.com/Automattic/wp-calypso/pull/15128
