### ISSUE TITLE
WooCommerce Payments: Update Stripe Settings

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#15133]
Per convo in Slack with @belcherj and @jameskoster, we are updating the ui for Stripe settings:

Live mode:
![stripe updated](https://user-images.githubusercontent.com/5835847/27151846-1c56fa90-5109-11e7-9056-cbfa4ffa95b3.png)

Test mode:
![test mode](https://user-images.githubusercontent.com/5835847/27151847-1c5aa7ee-5109-11e7-81cd-51358f57dc3f.png)

ApplePay disabled:
![apple disabled](https://user-images.githubusercontent.com/5835847/27151815-02bf9d9e-5109-11e7-9596-019afc2ea6a5.png)

**Comment by belcherj** [comment]
Can we close?
