### ISSUE TITLE
Customizer won't load for Localized Spanish (ES) users

### ISSUE THREAD

**Issue by nellofn** [Automattic/wp-calypso#15156]
Localized ES users are reporting in livechat that they are unable to load the Customizer:

Chat 1: 453162-hc
Site: https://imageoworks.wordpress.com/wp-admin/customize.php

Chat 2: 453829-hc
Site: https://wordpress.com/customize/healthyfranita.com

On a related note, another user reports that it can't also open a site's preview or a draft post in Calypso, or even the Wp-admin link as well.

Chat 3: 453636-hc
Site: https://excelsignum.wordpress.com/wp-admin/customize.php

#### Important
All users are from Spain (Madrid and Gijón), so they could be using the same ISP (Telefonica).

#### Steps to reproduce
1. Go to Themes -> Customizer
2. Customizer won't fully load

#### What happened instead
Users got the error: "Site is taking to long to load".

On a Slack convo [p1497538582297116-slack-triage](https://a8c.slack.com/archives/C02FMH4G8/p1497538582297116) Sheri B. discovered a high CPU use and JS errors for site: http://healthyfranita.com/

#### Browser / OS version
All users were using Google Chrome. Edge and a mobile device was also tested.

Note: All sites worked for me without issues. I tried with Chrome for Mac.

**Comment by correliebre** [comment]
I have another user with the same issue. They are also from Spain

- Ticket: https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3266420
- Customizer: https://imageoworks.com/wp-admin/customize.php

**Comment by yoavf** [comment]
@correliebre @nellofn can you check with a few users to see if this is still happening?

**Comment by nellofn** [comment]
@yoavf I'm replying the users and I'll post an update as soon as I have more information.

**Comment by designsimply** [comment]
Closing because some of the users have reported back that the Customizer is now loading properly for them. Please re-open if this comes up again or if an ES user returns saying they are still having trouble loading the Customizer.
