### ISSUE TITLE
Publicize Scheduling: handle disconnected services

### ISSUE THREAD

**Issue by jhnstn** [Automattic/wp-calypso#15150]
We need to update the UI to handle scheduled actions for disconnected services. We check the service connection at send time so there is no risk when a service gets disconnected but the UI is wonky:

**Pre disconnecting Facebook**
![screen shot 2017-06-14 at 8 55 33 pm](https://user-images.githubusercontent.com/744755/27164880-3502c114-5145-11e7-8365-f8009dfbc539.png)

**Post disconnecting Facebook**
![screen shot 2017-06-14 at 9 02 31 pm](https://user-images.githubusercontent.com/744755/27164890-40c0237a-5145-11e7-992c-6a06310191c7.png)

When the service is disconnected the scheduled action:
- Uses the twitter icon by default
- Loses the service handle
- Reconnecting the service **will not** fix the scheduled action.

A few options to correct the UI could be:

1. Hide any scheduled action that does not have a valid connection.  The action will be dropped silently at the time it was set to send

2. Show an error notice on the schedule action and offer the user the ability to reconnect the action.

We do get a fair amount of service reconnection events so it seems likely that a user will run into this issue

**Comment by jhnstn** [comment]
Just noticed we have the same issue with published actions:
![screen shot 2017-06-15 at 3 11 29 pm](https://user-images.githubusercontent.com/744755/27203979-51b20eb2-51dd-11e7-86c5-7d4c632ddc86.png)
The first one in the list went to facebook. In this case we also lose the external url

**Comment by iamtakashi** [comment]
If we could keep showing posts with username and icon for disconnected services, we could grey out them until it's re-connected. But if that's not possible, we should hide them. Showing broken post there seems worse than hiding. It'd be great if the hidden posts come back when you reconnected though. But if that's not possible neither, it means that scheduled posts are gone when the service is disconnected, correct?

**Comment by jhnstn** [comment]
> If we could keep showing posts with username and icon for disconnected services, we could grey out them until it's re-connected.

We should be able to determine the service and username from disconnected services. As you note we already do that with repbulicize connections.

> If we could keep showing posts with username and icon for disconnected services, we could grey out them until it's re-connected.

That's where this gets tricky. I took a quick look and we should have the required data reconnect a scheduled action. It's not trivial however and might end up being pretty hacky.

I suggest for now we treat these disconnected scheduled actions as lost and hide them from the UI.
If a user reconnects the service they will have to recreate the scheduled action.

**Comment by iamtakashi** [comment]
Got it. Thanks Jason.
