### ISSUE TITLE
WooCommerce Products: Update stock management ui

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#15165]
Demoed the add-product today and have the following changes to make to stock management. We had tested this out previously in a /try branch so hopefully the change won't be too difficult to make. 

1. Remove the manage stock toggle and always display the stock inputs. If they enter a number, its managing stock.
2. In the variations section, move the Manage Stock column to be first. Again, no toggle, just input.

**Comment by justinshreve** [comment]
Here is the existing try PR: #14343 - the difference being that we still showed the toggle. But I should still be able to borrow some of the logic there for making sure ` manage_stock` is correctly set.

I'll look at this tomorrow :).
