### ISSUE TITLE
Editor: Hyperlinking continues past item linked

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#15164]
#### Steps to reproduce
1. Add a new post
2. Hyperlink some text
3. Keep writing right after that text

#### What I expected
The hyperlinking to stop.

#### What happened instead
It hyperlinked the additional words

#### Browser / OS version
<img width="694" alt="screen shot 2017-06-15 at 12 44 49 pm" src="https://user-images.githubusercontent.com/26996883/27196624-75207614-51c8-11e7-96e6-eb2552ac147a.png">

#### Screenshot / Video

https://cloudup.com/cnsmSVoRUgy

**Comment by aduth** [comment]
Per link boundary behavior introduced in #13776 and [TinyMCE v4.6.0](https://www.tinymce.com/docs/changelog/#version460-may42017), in my testing this is working as expected. While typing within the link boundaries, the additional text is included as part of the link. Reaching the end of the link boundary (highlighted in blue) and then pressing the right arrow will move the text caret outside the link and additional text will appended adjacent the link, not part of it.

![additional-text](https://user-images.githubusercontent.com/1779930/27201120-72ed9d50-51ea-11e7-81ad-90c56d83e64d.gif)

**Comment by annezazu** [comment]
Perhaps I can't "computer" well but this change is truly driving me nuts :) I guess it's baffling me why the additional text is included as part of the link when I am hyperlinking what I want to be hyperlinked. I'll close this but thanks for explaining. Will adjust my workflow.

**Comment by lsinger** [comment]
When you select some text and then link it, I think the intention we can derive from that is that no additional text should be linked. Maybe we can move the caret out of the link boundary in those cases?
