### ISSUE TITLE
Posts: Add Pending Filter

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#1516]
Right now we have filters for Published, Draft, Scheduled, and Trash.  A user requests a Pending filter as well, as they're working with many drafts and many pending posts.

**Comment by supernovia** [comment]
https://twitter.com/user/status/675369130732756996

**Comment by KokkieH** [comment]
https://twitter.com/user/status/746863383429931008

**Comment by chaitanyamsv** [comment]
I just chatted with a user who's worried that their posts were missing. The Blog Posts page in Calypso showed no posts at all. But the posts were shown in the WP-Admin. It turned out that all their posts were pending. It would be nice if Calypso also shows the pending posts tab to avoid confusion.

**Comment by KokkieH** [comment]
Another case in 553514-chat

**Comment by ehti** [comment]
+1 to this.

Had another user who had no way of getting to the pending review post.

You can ONLY get to them if you have a draft saved, because then the drafts tab appears and the pending post shows up there.

**Comment by SiobhyB** [comment]
This caused some confusion again in 3276126-t.

**Comment by drw158** [comment]
I can see why this is causing a lot of confusion. Just to clarify, it seems you _can_ access the pending post in the Drafts tab, even if you have no other drafts. It looks like Calypso treats the pending post as a draft.

**Comment by alisterscott** [comment]
Seems like this was a bug where pending posts weren't showing in drafts.

I can confirm I am seeing pending posts in drafts now:

<img width="815" alt="screen shot 2017-12-21 at 9 39 27 am" src="https://user-images.githubusercontent.com/128826/34233772-f8696928-e632-11e7-9ffc-386a0c4c3f0d.png">
