### ISSUE TITLE
Eventbrite page template is not available even when a Sharing connection is present.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#15178]
When a user connects to Eventbrite through the Sharing page, [an Eventbrite Events page template should become available](https://en.support.wordpress.com/eventbrite/) for pages, letting the user to select which page will display their events. Currently, this page template never seems to be available.

**Comment by automattic-ian** [comment]
reported in #3277393-hc 
Workaround is to change page template in wp-admin.

**Comment by ashercantrell** [comment]
Running into this in 2701845-hc. The template doesn't appear in WP Admin either.

**Comment by ashercantrell** [comment]
Whoops, didn't mean to reopen yet.
