### ISSUE TITLE
WooCommerce Payments: Add loading indicator while methods are loading

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#15175]
The payment methods often load after the page does, but there's no loading indicators. 

Originally brought up in: https://github.com/Automattic/wp-calypso/pull/14932#issuecomment-307402017

<img width="701" alt="screen shot 2017-06-15 at 3 59 10 pm" src="https://user-images.githubusercontent.com/5835847/27203560-a19d4e54-51e3-11e7-8ec2-a1eeb9951076.png">

**Comment by belcherj** [comment]
Code merged
