### ISSUE TITLE
WooCommerce Payments: Add enable toggle to header card

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#15176]
Pull out enable toggle from the expanded card content and into the header card:

![](https://user-images.githubusercontent.com/5835847/27199697-2d1e5f96-51d4-11e7-9873-69807d69b5bf.png)

Came up in: https://github.com/Automattic/wp-calypso/pull/15125#issuecomment-308852200

**Comment by belcherj** [comment]
Done in #15258
