### ISSUE TITLE
Reader: Combined cards Site Results exceed container

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#15184]
![screen-shot-2017-06-15-at-2-01-57-pm](https://user-images.githubusercontent.com/4924246/27210607-757e60ea-5208-11e7-9d6e-f0f6dadeff66.png)

Example: https://wpcalypso.wordpress.com/read/search?q=Lance&focus=1&sort=date

Reported by @hoverduck

**Comment by jancavan** [comment]
Will have to re-open this as it caused breakage in a different post recs: https://github.com/Automattic/wp-calypso/pull/15414

**Comment by samouri** [comment]
@jancavan, this issue looks fixed to me.   Can we close?

**Comment by jancavan** [comment]
@samouri No, this was the "coachit" issue:
https://wpcalypso.wordpress.com/read/search?q=coachit&focus=1&sort=date

**Comment by jancavan** [comment]
![screenshot 2017-06-26 11 36 03](https://user-images.githubusercontent.com/4924246/27554559-a9b7f3a4-5a63-11e7-9297-5136cea7bcee.png)
