### ISSUE TITLE
Comments: HTML Entities in Post Title

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#15180]
In `/comments`, I'm seeing HTML character entities in the post title:

<img width="323" alt="screen shot 2017-06-15 at 3 42 07 pm" src="https://user-images.githubusercontent.com/789137/27204683-540a6aac-51e1-11e7-9c98-85215b9536ff.png">

**To reproduce**
Load comments that include a post with an apostrophe`'` in the title. You'll see the html entity code for it.

**Comment by drw158** [comment]
also happens in the expanded view #15020

**Comment by Copons** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/15292
