### ISSUE TITLE
Advanced SEO: Tagline not shown in the Page Title Structure preview

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#15191]
Tagline is not shown in the Page Title Structure preview. 

#### Steps to reproduce
1. Open Settings > General tab at the URL: https://wordpress.com/settings/general/chaitbiz.com
2. Add tagline for the site in the Site Tagline box.
3. Save Settings.
4. Head to Traffic tab: https://wordpress.com/settings/traffic/chaitbiz.com
5. In the Page Title Structure section, add tagline by clicking on +Tagline button.

#### What I expected
Preview under each box shows the tagline as it does for site title.

#### What happened instead
Tagline is not shown in the preview.

#### Browser / OS version
I tested in Firefox and Chrome on Mac.

#### Video
Screencast of the problem: https://cloudup.com/cv5HqD2-Uxz

#### Context / Source
#user-report in #3267455-t

**Comment by chaselivingston** [comment]
Also reported in 3267057-t.

**Comment by supernovia** [comment]
I've seen this on a user's site (Jetpack) and confirmed on a wp-com site as well.

**Comment by wpsuly** [comment]
Also reported in 646729-t.

**Comment by supernovia** [comment]
Taglines seem to be showing up now 👍 I'll close this.
