### ISSUE TITLE
Comments: `in reply to` block should include avatar, author, comment (if applicable)

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#15204]
There are a few things missing from the "in reply to" block (the row above the comment) in the expanded view. I didn't notice until recently.

<img width="755" alt="screen shot 2017-06-16 at 11 02 52 am" src="https://user-images.githubusercontent.com/618551/27235420-69bea7e6-5286-11e7-88cc-73bf6c441939.png">

- The blavatar never seems to load, only the globe icon
- The post author avatar and name are missing
- If the comment is in reply to another comment, it should display the comment, instead of the post title. I'm not sure if I made this clear with the early mockups. For example, see the above screenshot. The comment is in reply to another comment, but the original post title is displayed instead. This could be punted to m2.

<img width="661" alt="screen shot 2017-06-16 at 11 26 44 am" src="https://user-images.githubusercontent.com/618551/27235542-c99a7fb4-5286-11e7-8c1c-7b8fdc6caf4d.png">

**Comment by Copons** [comment]
@drw158 The missing blavatar and post author name are a regression caused by a slightly different structure of the real comments data.
Actually, the post author is not currently returned, and we'll see to tackle it.

About replies: coding as we speak! :)
