### ISSUE TITLE
App Prompt: Smart Banner

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#15228]
Let's have this banner display in the following sections: stats, reader, editor and notifications.

Clicking “Open in app” will trigger a small trip to the app page in Play Store or App Store if the app isn’t installed. The cool thing about the link is that if the app is already installed, the app can automatically jump to the deep-linked section where we want. This is very handy for targeted banners like these, and there is no need to detect if the app is installed or not.

Display/Dismiss behavior
* Option 1: dismissing banner x turns off banner x for one year, also turns off all other banners for one week. After one week, banner x is still off, but user would see banner y in context
* Option 2: Shows three times, then never again.
* Option 3: If a banner is dismissed it dismisses all banners for a week.

My personal vote is for 1 at the moment, but if this is too difficult to implement maybe option 2, with an interval of 1 week per dismissals. If it's dismissed 3 times we never show the banners again for that user.

![stats-reader](https://user-images.githubusercontent.com/908665/27278041-29076db0-54d8-11e7-898d-badbb2c71dd6.jpg)

![editor-notifications](https://user-images.githubusercontent.com/908665/27278053-2e4f6d4a-54d8-11e7-9550-c12aa4e211ef.jpg)

Implementation Notes:
- Add translation notes to keep this short
- Let subtext go to three lines if the translation is too long
- @iamtakashi to add the color + related assets
- For dismiss state, use one user pref for all four banners.
- Fast slide down for dismissing the banner
- Research what the open in app does.

**Comment by iamtakashi** [comment]
> The banner is dismissible by clicking “No thanks” link. @iamtakashi is this dismissed for the session, or for the user forever?

I'm not sure who decide in the end, I'd say "for the session"

Just to be clear that this design above was made in beggining and since then it has changed. Here are the latest designs.

![stats-reader](https://user-images.githubusercontent.com/908665/27278041-29076db0-54d8-11e7-898d-badbb2c71dd6.jpg)

![editor-notifications](https://user-images.githubusercontent.com/908665/27278053-2e4f6d4a-54d8-11e7-9550-c12aa4e211ef.jpg)

And this is for `/me/get-apps/` (This is an example in case you're a Mac user.)

<img width="1312" alt="screen shot 2017-06-19 at 10 11 00" src="https://user-images.githubusercontent.com/908665/27278082-40d815de-54d8-11e7-99dd-c1cceee9a91f.png">

<img width="406" alt="screen shot 2017-06-19 at 10 11 16" src="https://user-images.githubusercontent.com/908665/27278094-4763daaa-54d8-11e7-820f-5e7628e6ba5b.png">

**Comment by kwight** [comment]
> I'm not sure who decide in the end, I'd say "for the session"

That seems really aggressive to me; with it covering up to... ~20%? on smaller screens (like an iPhone 5/SE), I'd be irritated if I kept seeing it after having already dismissed it once.

**Comment by iamtakashi** [comment]
> That seems really aggressive to me;

Oh, I might be misunderstanding. I thought that was less aggressive than "for the user forever". I think it's best to ask mobile team?

**Comment by iamtakashi** [comment]
Sorry, I know now that I misunderstood the question :) 

I wonder if @rralian also has an opinion on how long it should be dismissed for.

**Comment by rralian** [comment]
I would dismiss for a long time. Either forever or for one year.

**Comment by rralian** [comment]
Another question regarding dismissal. Does dismissing one banner dismiss the functionality for all banners? Or would it be possible for me to hit all four of these in a single session? I would want to avoid getting four ads in a single session for sure. That would be certain to turn me off as a user if I didn't feel like installing the app. On the other hand if I dismiss one banner the first time I come in (before I've had a chance to even use wpcom and decide I want the app), it would be a shame to never see this again.

**Comment by gwwar** [comment]
> Does dismissing one banner dismiss the functionality for all banners? 

@rralian I would map this to a single user preference.

**Comment by dmsnell** [comment]
just going to throw this out there. also not going to bother and try to transform the mocks into landscape mode, but I'm sure that would be a provocative picture

![first](https://user-images.githubusercontent.com/5431237/27402480-13345e80-56c7-11e7-918e-c21a0f4719fe.png)

![second](https://user-images.githubusercontent.com/5431237/27402482-164c0db6-56c7-11e7-84f0-78884e14721f.png)

**Comment by rralian** [comment]
I think there has to be some middle-ground. I'd like to account for people reflexively turning these off the first time they're on the site (say before they're even bought into WordPress.com), but having another chance at it in another session... particularly to make use of the contextual content.

This is a convoluted proposal, feel free to argue it down or counter-propose;
- dismissing banner x turns off banner x for one year, also turns off all other banners for one week
- after one week, banner x is still off, but user would see banner y in context

**Comment by gwwar** [comment]
cc @catehstn for thoughts on behavior here

**Comment by kwight** [comment]
Some design details from @iamtakashi :

![pasted image at 2017_06_23 22_05](https://user-images.githubusercontent.com/349751/27501031-e2e414a0-581f-11e7-8405-8d1f40820943.png)

**Comment by gwwar** [comment]
Fancy annotations 😄 Thanks @iamtakashi !

**Comment by catehstn** [comment]
I am happy with what @rralian proposed. I think he makes a good point about reflexively dismissing. Alternate:
- Shows three times, then never again.
- If a banner is dismissed it dismisses all banners for a week.

**Comment by gwwar** [comment]
Thanks @catehstn and @rralian I'll update the summary to reflect the new behavior options

**Comment by iamtakashi** [comment]
It's probably better to hide the small text for even smaller screens to avoid the banner gets too tall.

![iphone 4](https://user-images.githubusercontent.com/908665/28109464-153f5cea-66e7-11e7-96d3-d30ddee6c81a.png)

**Comment by kwonye** [comment]
Mobile native app requirements here: https://github.com/Automattic/wp-calypso/pull/16124#issuecomment-315650955
