### ISSUE TITLE
App Prompt: redesign of /me/get-apps

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#15227]
This is a redesign of /me/get-apps. The main difference is that we promote the current OS/platform choice, vs showing all options equally.

Desktop
<img width="1312" alt="screen shot 2017-06-19 at 10 11 00" src="https://user-images.githubusercontent.com/908665/27278082-40d815de-54d8-11e7-99dd-c1cceee9a91f.png">

Mobile
<img width="406" alt="screen shot 2017-06-19 at 10 11 16" src="https://user-images.githubusercontent.com/908665/27278094-4763daaa-54d8-11e7-820f-5e7628e6ba5b.png">

For reference here's the existing page:
<img width="724" alt="screen shot 2017-06-16 at 4 51 06 pm" src="https://user-images.githubusercontent.com/1270189/27248103-15f0c396-52b4-11e7-9e2a-ed14f6070d48.png">

**Comment by gwwar** [comment]
cc @iamtakashi to add related assets

**Comment by kwight** [comment]
Building this in https://github.com/Automattic/wp-calypso/pull/15382
