### ISSUE TITLE
Theme Showcase: On mobile, Open Live Demo shows theme in iframe, causing display issues

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#15225]
When you navigate from a theme showcase page to its live demo, it appears to apply styles for a larger screen size. I think this may be because it's being loaded in an iframe.

I was able to recreate this issue with Penscratch 2, Dyad 2, Twenty Seventeen, Twenty Sixteen and Apostrophe 2.

#### Steps to reproduce
1. On a mobile device, starting at URL: https://www.wordpress.com/theme/penscratch-2
2. Click on 'Open Live Demo'

#### What I expected

I would see a preview of the theme as it looks on mobile devices.

#### What happened instead

I saw a preview of the theme better suited for larger screens.

#### Browser / OS version

Safari in iOS 10 on an iPhone 6.

#### Screenshot / Video

How the demo looks when you load https://penscratch2demo.wordpress.com:

![Image](https://cldup.com/JRI21wseoy-3000x3000.png)

How the demo looks when you click 'Open Live Demo' from https://www.wordpress.com/theme/penscratch-2:

![Image](https://cldup.com/ez2bgAa7IE-3000x3000.png)

#### Context / Source
Noticed randomly, while trying to navigate to theme demos on my iPhone.

**Comment by alisterscott** [comment]
I noticed this today also.

**Comment by lancewillett** [comment]
Closing as wontfix, minor.
