### ISSUE TITLE
Free Trials: Domain credit shouldn't be usable during the trial period.

### ISSUE THREAD

**Issue by matthusby** [Automattic/wp-calypso#1522]
D650-code has a patch that will disable the domain credit during the trial period.

Part of #1484.

Also fixes #1377.

cc @fabianapsimoes @spncrb @drewblaisdell 

- [x] Product Review
- [x] Code Review

**Comment by spncrb** [comment]
This patch breaks the /plans page (missing trial buttons):
<img width="664" alt="screen shot 2015-12-11 at 7 29 53 pm" src="https://cloud.githubusercontent.com/assets/8921630/11758790/9af7b80e-a03d-11e5-98f6-67583d7dd22a.png">

There are also internal server errors in console:
<img width="967" alt="screen shot 2015-12-11 at 7 31 17 pm" src="https://cloud.githubusercontent.com/assets/8921630/11758800/c918647c-a03d-11e5-9746-6ca79937e670.png">

Was able to verify that it was your patch by removing the patch from the sandbox (buttons re-appear) and re-applying (buttons disappear, errors return)

**Comment by spncrb** [comment]
Just managed to add a trial without the patch and re-add the patch.

The functionality intended does indeed work - no domain credits (charged for domains).

That said, it does break /plans, per above.

**Comment by matthusby** [comment]
I just updated the diff, there was a fatal error when checking a site that didn't have a plan.

**Comment by fabianapsimoes** [comment]
Looks good! Here's what I tested:

- we do not display "free with plan" in `/domains/add` to trials
- we charge trials correctly for domains
- after a trial is purchased, we do display "free with plan" in `/domains/add`
- we do not charge users who purchased a trial for the bundled domain.

Product :+1:

**Comment by scruffian** [comment]
This was deployed.
