### ISSUE TITLE
Post Preview: Sidebar shows when closing post preview on mobile

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#15231]
#### Steps to reproduce
1. Starting at URL on a mobile device: https://wordpress.com/posts/my/:slug?
2. Click view
3. Close the preview modal
4. Despair in not being able to continue without clicking the `Posts` sidebar item or reloading the page

#### What I expected
The sidebar to remain hidden

#### What happened instead
The sidebar showed

#### Browser / OS version
Brave / Android 7.1.2 / Pixel

Will attempt to reproduce on Desktop Chrome device mode later

#### Screenshot / Video
@TODO

**Comment by marekhrabe** [comment]
no calypso.live? interesting
