### ISSUE TITLE
Editor: Date picker under Status does not show scheduled posts

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#15251]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Select a site.
3. Create a schedule a post for a future date in the same month.
4. Create a new post.
5. Select the date picker next to the Publish button in the editor. Note that the date for the scheduled post is circled.
6. Open the Status section and select the date picker.

#### What I expected

I expect the date picker in the Status section to be the same as the date picker next to the Publish button.

#### What happened instead

The date picker in the Status section doesn't show scheduled posts.

#### Browser / OS version

Tested on Mac OSX 10.12.5, Chrome 58.0.3029.110

#### Screenshot / Video

Date picker showing scheduled posts:

![screen shot 2017-06-19 at 3 37 07 pm](https://user-images.githubusercontent.com/8658164/27290659-d32013d8-5505-11e7-96aa-24ef965f6f06.png)

Date picker in Status section, no scheduled posts:

![screen shot 2017-06-19 at 3 37 24 pm](https://user-images.githubusercontent.com/8658164/27290662-d4a15da2-5505-11e7-84fc-8164f595e087.png)

#### Context / Source

#user-report internal ref: 197196-h

**Comment by lancewillett** [comment]
See also #1035

**Comment by KokkieH** [comment]
Had another report via [Twitter](https://twitter.com/ReviewAlholic/status/905016437265367040). I also notice the date picker now doesn't show published posts on the calendar either.

**Comment by KokkieH** [comment]
And [another](https://twitter.com/sullybaseball/status/905173693118136320). 

With the introduction or the publish confirmation panel (#17017) the Schedule Post button has also been removed completely, with the date picker in the Status section now the only option. Most likely the reason for the increase in reports around this.

**Comment by nylen** [comment]
https://github.com/Automattic/wp-calypso/pull/17892 should fix this.

**Comment by KokkieH** [comment]
Adding 875835-f for follow up once the fix is merged.

**Comment by nylen** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/17892.
