### ISSUE TITLE
Add iOS native smart app banner to logged-in Calypso.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#15265]
The banner has already been implemented in the logged-out home page and the login screen.

![screen shot 2017-06-19 at 10 56 08 am](https://user-images.githubusercontent.com/349751/27298537-eff3240a-54dd-11e7-8b9f-546b28ae5128.png)

Do we need to add this to all pages except stats, reader, editor and notifications? Can we share the dismiss option with the other app banner? Follow up with Mobile.

**Comment by designsimply** [comment]
What is the reasoning behind wanting to limit it?

**Comment by kwight** [comment]
We have [custom banners](https://github.com/Automattic/wp-calypso/projects/34#card-3418234) we're implementing at the same time, so trying to strike the balance between the two.

**Comment by kriskarkoski** [comment]
Closing due too lack of activity
