### ISSUE TITLE
Follow/Unfollow Notifications for following Tags

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15263]
Now that we have follow/unfollow notifications for sites (#15262), we should also have them for Tags. IE: the follow/unfollow link at the top of a tag page like https://wordpress.com/tag/botany

Clicking "Follow Botany" should result in a green "You're now following Botany" notification. 

Clicking "Following Botany" should result in a grey "You're no longer following Botany" notification.

Make sense?

cc @blowery

**Comment by formosattic** [comment]
+1 from user in 613559-zd.

**Comment by jancavan** [comment]
We got rid of global notices when following sites so closing this issue.
