### ISSUE TITLE
Reader: Follow success notification in Discover shows URL instead of site name

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#15274]
Anything that I follow on Discover shows the URL even though it has a site name:

![screenshot 2017-06-19 15 11 54](https://user-images.githubusercontent.com/4924246/27308065-a52d546c-5501-11e7-8bbc-c091072842d5.png)

I was expecting to see "You are now following LotsaSmiles Photography" instead of "You are now following https://lotstasmilesphoto.com".

Other examples:
![screenshot 2017-06-19 15 14 28](https://user-images.githubusercontent.com/4924246/27308136-000c20c0-5502-11e7-9ccd-9eee1d0cc93b.png)

![screenshot 2017-06-19 15 15 28](https://user-images.githubusercontent.com/4924246/27308169-2310eed4-5502-11e7-8cfe-c100a51b4a38.png)

**Comment by fraying** [comment]
See also: #15262

**Comment by jancavan** [comment]
Thanks @fraying. I missed that issue. Will close this.
