### ISSUE TITLE
Domains: (Development) Intermittent failure to show cached Domain Contact Information

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#15279]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/stats/day/blogurl.com
2. Click "add domain"
3. Choose a domain name
4. Click through email offer
5. Open the Network panel on the Dev Tools
5. Refresh the Domain Contact Information page a few times until it comes up blank ( http://calypso.localhost:3000/checkout/blogurl.com )
6. Confirm that the `https://public-api.wordpress.com/rest/v1.1/me/domain-contact-information` api call did return some data.

#### What I expected
The form fields should be pre-filled with the cached domain contact information

#### What happened instead
The form fields were left

#### Browser / OS version
Chrome, OSX

#### Screenshot / Video
![checkout_ _julesauspremiumtest_ _wordpress_com](https://user-images.githubusercontent.com/5952255/27309659-a3eb38ac-5598-11e7-8db9-8ceca24e409b.jpg)

#### Context / Source
wordpress.com seems fine.  I see this at least a third of the time, but you might need to refresh a few times to see it.

If you don't have cached contact details, you need to try and register a domain. The details remain cached if you cancel it afterwards or the transaction fails, so feel free to do either straight away.

**Comment by hewsut** [comment]
> wordpress.com seems fine.

So to fully clarify -- the place to look for this is solely a local dev environment?  It hasn't (yet?) been observed in prod?

**Comment by deBhal** [comment]
I checked out production and did a bunch of refreshes without seeing it. You can never be sure with intermittent, but I'm pretty confident that it's in the ccTLD code behind the feature flag.

**Comment by deBhal** [comment]
This issue was fixed by #15366, so I'm going to close it.

Background: With 65c25c856d checked out, the issue occurred every time the local storage was cleared. This was a lot more obvious in the dev environment thanks to sympathy ([addSympathy()](https://github.com/Automattic/wp-calypso/blob/master/client/state/initial-state.js#L62)), but manually clearing the store works too.

Move forward to bcfcd043f4 (The #15366 merge), and there's no problem.

Looks like we were initializing the formState with empty data before the fetch completed, and then not updating it when the new data arrived.
