### ISSUE TITLE
Activity Log (Rewind): return requested timestamp with API response

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#15293]
When we make a request to restore a site to a timestamp, we will need the API to respond also with the requested timestamp so we can rely on it for further UI (progress banners)

Specifically, we'll need the VP Private API endpoint `$vp_api_client->site_queue_rewind()` to be modified, as well as our reducer

**Comment by sirreal** [comment]
We ended up handling this in #15363, which may be a better solution. It keeps redundant data off the wire.

If there are no objections or reasons to implement this, we can close. cc/ @seear
