### ISSUE TITLE
Help: Fallback to URL if site title empty

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#1529]
If the site title is empty, the dropdown under "Which site do you need help with?" is blank (the top line in the dropdown is a site):

![screen shot 2015-12-11 at 7 31 27 pm](https://cloud.githubusercontent.com/assets/7240478/11759680/cacaf582-a03d-11e5-9f1a-91e07912075e.png)

We should fallback to a site URL here just in the chance that the title field is blank.

**Comment by mtias** [comment]
This should be replaced with `SitesDropdown` which is now merged. See #451.

**Comment by omarjackman** [comment]
> This should be replaced with SitesDropdown which is now merged. See #451.

@mtias I created #1588 to use the `SitesDropdown` component but there is a visual issue that needs to be fixed before it can be completed. The last item in the list gets cut off. See:
![screen shot 2015-12-14 at 11 39 46 pm](https://cloud.githubusercontent.com/assets/1854440/11802297/4de2ea48-a2bd-11e5-8c82-aaeecaeb2446.png)

In the meantime I will just do the quick fix for the issue described here and put it in another pull request.
