### ISSUE TITLE
Stats: first week average is incorrect in the Recent Weeks post summary table

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#153]
Steps to reproduce:

1. Find a recent post that was published near the end of the week and has views for the days following
1. Go to https://wordpress.com/stats/day and select the blog
1. Click on the name of the post in the "Posts & Pages" box
1. Find the average for the first week the post was published

<strong>Result:</strong> the calculated average for a post published near the end of the week is incorrect in the Recent Weeks post summary table. It should not count the zeros at the beginning of the first week.

![screen shot 2015-11-18 at wed nov 18 6 43 33 pm](https://cloud.githubusercontent.com/assets/1119271/11258199/419e8b4a-8e25-11e5-8dc6-42e10fccd3a2.png)

I read some comments around this issue mentioning that the single post API is returning recent weeks prior to site's existence, but I'm not sure that matters depending on how the first week average is calculated (i.e. based on 7 days vs a partial week).

/hat tip @daniloercoli for the original report (p1421324435000202-slack-serenity-front)

**Comment by hoverduck** [comment]
28Apr16 Bug Scrub

Closing, it looks like this was resolved.  Now the average views is not shown for an incomplete week:

![screen shot 2016-04-28 at 1 24 08 pm](https://cloud.githubusercontent.com/assets/7233112/14895021/995ad390-0d44-11e6-82de-d4dd903d3ac8.png)
