### ISSUE TITLE
Editor: image editing not working for site with custom subdomain

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#15303]
Image editing is working well for me across several test sites in different situations (wpcom, wpcom with custom domain, jetpack site), but I have one test site where it consistently fails. I don't know for sure what it is about this site that is an issue. But this particular site has a custom subdomain (test.bobinprogress3.blog), so I wonder if that's the problem.

For some reason it seems unable to load the image within the image editor, even though I can load the image directly just fine.

![image-editor-error](http://cld.wthms.co/t3ljdt+)

You can see that the browser is unable to load the image and gets a 403 response, though I am able to open that image directly if I load that URL in a separate tab (https://bobinprogress3.files.wordpress.com/2017/06/screen-shot-2017-06-20-at-10-48-59-am.png?).

@gwwar do you have any ideas about this one?

**Comment by lsinger** [comment]
FWIW, no problem loading it with `leif.photo.blog` (wpcom):

![screen shot 2017-06-21 at 12 37 59 pm](https://user-images.githubusercontent.com/23619/27380269-c4b752b4-567e-11e7-9cf5-7783110c3bde.png)

**Comment by gwwar** [comment]
@rralian Let's see a permissions error? Is photon on for you?

**Comment by eduardozulian** [comment]
Got a wpcom user report on 3289897-t. No subdomains for them, but a mapping. Also, I see the `403` error in the console.

**Comment by lancewillett** [comment]
I ran into this today on a private Automattic P2 site.

1. Create new post
2. Try to add an image via media library...
3. Click the image you'd like to add, then click the blue "Edit" button
4. Then click "Edit Image" link at the top right of the image editor
5. "We are unable to edit this image." message 😢

**Comment by lancewillett** [comment]
^^ Actually — my experience isn't with a subdomain but with a private site, see #13625

**Comment by rachelmcr** [comment]
Closing this issue as the site mentioned in the original report is private, and we're tracking image editing for private sites here: https://github.com/Automattic/wp-calypso/issues/13625
