### ISSUE TITLE
WooCommerce: Get basic engagement and adoption stats for v1 via tracks events

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#15316]
We need to gauge engagement and adoption for our MVP. To start, we should track the following:

- number of clicks on 'store' nav item
- number who fill out the pre-egg store location (ie, click that 'next' button on the page)
- number of products added
- each button click on dashboard, including 'i'm finished setting up' button
- payment methods used
- shipping methods used

@justinshreve  and I talked about 'number of orders received' as a nice-to-have stat, but something we may not get to in time.

**Comment by justinshreve** [comment]
Done!
