### ISSUE TITLE
Editor: Colour Change for Hyperlinks

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#15328]
The color of the hyperlink can not be changed after the hyperlink was created in the editor.
You can change the color if you first change the color of the text and then create a hyperlink.

#### Steps to reproduce
1. Go to the post or page editor - go to My Sites and click on button "Add" by Posts or Pages
2. Open the editor and add some text
3. Choose a specific text and hyperlink it to a page or post
4. Try changing the color of that hyperlink by clicking on text color icon  in the editor

#### What I expected
I expected the color of the hyperlink to change to another color after hyperlink was created

#### What happened instead
The color did not change

#### Screenshot / Video

The video: https://cloudup.com/cn7SocpSu0D

If I first change the color of the text and after hyperlink it, it works that way:
https://cloudup.com/cAvu7W3w8Qs

Also, a similar issue seems to be added here: https://core.trac.wordpress.org/ticket/41033

 #user-report

**Comment by designsimply** [comment]
Thanks for the bug report! 

Noting a workaround from the core.trac ticket here:

> If you change the color of text before it's turned into a link, it remains that color.

**Comment by supernovia** [comment]
@designsimply I haven't been able to make that workaround work in Calypso, though that does work in wp-admin.

Noting another complaint here: http://en.forums.wordpress.com/topic/i-cant-change-the-text-colour-in-my-links

**Comment by supernovia** [comment]
We have another report here:
http://en.forums.wordpress.com/topic/changing-hyperlink-color-no-longer-works-properly

**Comment by sarahfg** [comment]
Another report #1186086-Zen

**Comment by kristarella** [comment]
> If you change the color of text before it's turned into a link, it remains that color

I concur with @supernovia I couldn't get this to work. In the calypso editor the color span goes outside the link element every time, which means the link color over-rides.

My test is here: https://badaboomtest.wordpress.com/2018/05/28/link-test/

**Comment by davipontesblog** [comment]
I am not able to replicate this issue in the block editor, so I am closing the issue. Feel free to reopen as needed if this can be replicated in Gutenberg.
