### ISSUE TITLE
Bug: uploading new image to media library to jetpack linked .org site fails

### ISSUE THREAD

**Issue by DigitalDavo** [Automattic/wp-calypso#1532]
Should the ability to upload new media to a jetpack linked .org site work? It fails on windows v1.1.2 and also on osx too.

Any attempt to upload an image into a post, via the media library is met with

"! The file could not be uploaded because an error occurred while uploading."

https://cloud.githubusercontent.com/assets/3273790/11765810/db37624a-a1a3-11e5-91f3-8325e68d4a00.png

**Comment by beaulebens** [comment]
Hi @DigitalDavo - are you getting any other errors in Calypso related to connections, or can you try using this tool and see if your Jetpack connection has any problems? I just tried this on a test Jetpack site and it seems to work fine for me, both from wordpress.com and from within the downloadable app (on OSX).

http://jetpack.me/support/debug/

**Comment by DigitalDavo** [comment]
The jetpack support debug URL above tells me that I don't have a DNS A record which is not true, so something else is not quite right with the jetpack connection.

I built wp-calypso locally on OSX and ran it with the chrome js console active and can see the following error

```
https://public-api.wordpress.com/rest/v1.1/sites/2921305/media/new?http_envelope=1
```

<lots of post data and headers>

```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"json_syntax","message":"Invalid response from the Jetpack site"}}
```

So that would be the problem I'm having. I can't really disable plugins one by one to see which one it could be. I don't have any of the known problem plugins or configurations. The site has vaultpress running via ssh so there is plenty of jetpack working fine on my site so far.

-----------------------
```
Request URL:https://public-api.wordpress.com/rest/v1.1/sites/2921305/media/new?http_envelope=1
Request Method:POST
Status Code:200 OK
Remote Address:192.0.78.23:443
Response Headers
access-control-allow-credentials:false
access-control-allow-origin:*
cache-control:no-cache, must-revalidate, max-age=0
content-encoding:gzip
content-type:application/json
date:Thu, 17 Dec 2015 02:16:11 GMT
expires:Wed, 11 Jan 1984 05:00:00 GMT
pragma:no-cache
server:nginx
set-cookie:wpc_wpc=account=rosacea&avatar=https%3A%2F%2F1.gravatar.com%2Favatar%2F1ae2448362001ca76f18aafda47685b4%3Fs%3D25%26amp%3Bd%3Dhttps%253A%252F%252Fs2.wp.com%252Fwp-content%252Fmu-plugins%252Fhighlander-comments%252Fimages%252Fwplogo.png&email=pascoedj%40gmail.com&link=http%3A%2F%2Frosacea.wordpress.com%2F&name=David%20Pascoe&uid=104819&access_token=5efe42636082c24513a94ca3d889da0f458aade5; path=/; domain=.wordpress.com
status:200
vary:Accept-Encoding
x-ac:2.syd _bur
x-hacker:Oh, Awesome: Opossum
Request Headers
:authority:public-api.wordpress.com
:method:POST
:path:/rest/v1.1/sites/2921305/media/new?http_envelope=1
:scheme:https
accept:application/json, text/javascript, */*; q=0.01
accept-encoding:gzip, deflate
accept-language:en-US,en;q=0.8
authorization:X-WPCOOKIE 182b5d3984ed0aa0dd6c35c4408939ce:1:http://calypso.localhost:3000
content-length:681868
content-type:multipart/form-data; boundary=----WebKitFormBoundarypyXOdPrSFL9Bg62t
cookie:wordpress_test_cookie=WP+Cookie+check; _wpndash=bf2f6e83a4d0ade64f45e398; wordpress_logged_in=rosacea%7C1538742838%7CA1xUxA1eXq6sC2GLHrk38nbEWtCj9qc8pzlK5NIsQqk%7C854b6b6f53bd32daf6a488e87126617fee876a5b0c5b270b64ce2fc4b8239fc3; __ssid=aa5c48b5-4e4e-40da-b8ad-f003546cc2da; hc_post_as=jetpack; _ga=GA1.2.2001107623.1438000778; tk_tc=1450253457569; tk_ni=104819; wordpress_eli=1; wpc_wpc=account=rosacea&avatar=https%3A%2F%2F1.gravatar.com%2Favatar%2F1ae2448362001ca76f18aafda47685b4%3Fs%3D25%26amp%3Bd%3Dhttps%253A%252F%252Fs2.wp.com%252Fwp-content%252Fmu-plugins%252Fhighlander-comments%252Fimages%252Fwplogo.png&email=pascoedj%40gmail.com&link=http%3A%2F%2Frosacea.wordpress.com%2F&name=David%20Pascoe&uid=104819&access_token=5efe42636082c24513a94ca3d889da0f458aade5; wp_api_sec=rosacea%7C1538742838%7CA1xUxA1eXq6sC2GLHrk38nbEWtCj9qc8pzlK5NIsQqk%7C6c7c280080b313bc5652cbc47214cf51b4e47bbf964e2a0a57677c71abd16998
origin:https://public-api.wordpress.com
referer:https://public-api.wordpress.com/wp-admin/rest-proxy/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.41 Safari/537.36
x-requested-with:XMLHttpRequest
Query String Parameters
 (1)
Request Payload
------WebKitFormBoundarypyXOdPrSFL9Bg62t
Content-Disposition: form-data; name="media[]"; filename="Screenshot 2015-12-02 14.31.40.png"
Content-Type: image/png


------WebKitFormBoundarypyXOdPrSFL9Bg62t--
```

**Comment by beaulebens** [comment]
When VaultPress accesses your site via SSH, it's completely bypassing any potential problems that come in via API request/response.

If you're getting a syntax error, it would definitely suggest that either one of your plugins, or your theme, is injecting something unexpected into the output of all requests, which is interfering with the API requests. Someone from our support team will be in touch shortly to see if we can get this figured out. I'll close this since I don't believe it's an issue with Calypso per se.
