### ISSUE TITLE
Login: Back link broken

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#15349]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in/es?redirect_to=https%3A%2F%2Fwordpress.com%2F
2. Click the Back to WordPress.com link in the footer

#### What I expected
To go back to the home page

#### What happened instead
The footer went weird

#### Environment
Doesn't happen in development

#### Screenshot / Video
https://cloudup.com/cg8sl6h78rv

**Comment by stephanethomas** [comment]
> Doesn't happen in development

It shouldn't happen in every environment except production actually.
