### ISSUE TITLE
Activity log: Activity item processing for UI

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#15344]
We need to know how to translate API provided activity items into complete UI elements. We talked about this in person and decided it was something that can and should be handled in the client. We'll need to build the mechanism that handles this.

[An `update_logs` method](https://github.com/Automattic/wp-calypso/blob/1480e3cf8280faf52e4365517cac42b260b9299e/client/my-sites/stats/activity-log/index.jsx#L90-L177) was migrated from _the big PR_ #10862. We may be able to reuse some of the logic, but it needs to be moved to a more appropriate location and updated to match endpoint responses. For starters, `name` is now the field we should be switching on.

A comprehensive list of the activity `name`s would be a good starting point.

@roccotripaldi @gititon @lezama - Do we have such a list?

**Comment by seear** [comment]
> We talked about this in person and decided it was something that can and should be handled in the client.

Thinking a bit more on this—there has been some talk of the mobile app doing the activity log feature soon. If this is the case, we may want to do the string i18n at the server end to avoid doing it on every client.

The wpcom API has an i18n mechanism we can use.

**Comment by lezama** [comment]
good call

**Comment by seear** [comment]
For MVP, this may just mean sending down the english strings from the API, but we need to keep in mind how we will handle translations.
