### ISSUE TITLE
Some padding issues on the Jetpack footer bar

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#15373]
**Steps to Reproduce**
1. Go to `/log-in` in Firefox or iPad Safari.
2. Note the extra padding under the Jetpack logo.

Firefox | iPad
------------ | -------------
<img width="1438" alt="screen shot 2017-06-21 at 3 57 14 pm" src="https://user-images.githubusercontent.com/3011211/27406407-56d9dbba-569a-11e7-84af-d9f8755d7a5f.png"> | <img width="485" alt="screen shot 2017-06-15 at 7 40 44 am" src="https://user-images.githubusercontent.com/3011211/27406415-6003d0c4-569a-11e7-9c3c-e1b5be94bb34.png">

**Comment by fabianapsimoes** [comment]
Also reported for Edge here: 15285
