### ISSUE TITLE
Jetpack Plugins: "Automattic" search results showing empty, with console error

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#15370]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plugins/browse/
2. Search for the string "Automattic"

#### What I expected
To see a list of plugins matching the given string

#### What happened instead
Nothing loads, leaving the placeholder elements in place.  There's an error in the console reading

```
Uncaught TypeError: e.map is not a function
    at Object.normalizePluginsList (plugins.157f94b….m.js:10)
    at plugins.157f94b….m.js:12
    at plugins.157f94b….m.js:12
    at p.callback (vendor.eb47d18….m.js:14)
    at p.<anonymous> (vendor.eb47d18….m.js:14)
    at p.n.emit (vendor.eb47d18….m.js:8)
    at XMLHttpRequest.n.onreadystatechange (vendor.eb47d18….m.js:14)
```

What's especially weird is that it only seems to happen with the word Automattic.  Searching for other terms reliably returns results.  And I can't say it happens 100% of the time with Automattic, but it's incredibly frequent.

#### Browser / OS version
Seen here in OSX Chrome

#### Screenshot / Video
<img width="1394" alt="screen shot 2017-06-21 at 4 10 23 pm" src="https://user-images.githubusercontent.com/7233112/27404785-50687f5e-569d-11e7-9b5a-c6755191d847.png">

#### Context / Source
#automated-testing

**Comment by beaulebens** [comment]
I'm no longer able to reproduce this at all (tried various search terms, tried searching "Automattic" in various upper/lower case combinations, multiple times). Closing.
