### ISSUE TITLE
Whitelist Scribd?

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15375]
@blowery Can we add scribd.com to the list of whitelisted embeds?

For example: https://wordpress.com/read/feeds/18743358/posts/1502915554

**Comment by fraying** [comment]
Ping @blowery

**Comment by blowery** [comment]
Yup!

**Comment by blowery** [comment]
@bluefuton could you take this one? :)

**Comment by bluefuton** [comment]
@blowery Sure :)
