### ISSUE TITLE
Social signup: wrong permissions requested for Google accounts

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#15391]
When using "Continue with Google" on `log-in/` to create a new WordPress.com account, we only seem to ask for access to age range and language:

![ranimac3 screenshot 2017-06-22 at 16 43 30](https://user-images.githubusercontent.com/426518/27437229-46fafe06-576a-11e7-877b-09832ddfc0ce.png)

This is for signing up with a brand new Google account, never before used on WordPress.com. 

Since we are using the `plus.login` scope, we should be asking for the same permissions as in  #12664:

![image](https://user-images.githubusercontent.com/426518/28753115-8572e5fa-7537-11e7-8e77-3f97d98f5008.png)

After connecting, when reviewing the connection on Google's end, it does appear we have those extra permissions:

<img width="716" alt="ranimac3 screenshot 2017-06-22 at 16 44 42" src="https://user-images.githubusercontent.com/426518/27437235-4d0638c4-576a-11e7-9e08-8ec458767f03.png">

Not sure which side is wrong here, or if there's something wrong with how I'm testing this. But I expect the consent screen to ask me about age range, email, and profile info. Instead, it only asks me about age range, but we still seems to get access to email and profile info without permission.

**Comment by scruffian** [comment]
We changed this once before: #12664
