### ISSUE TITLE
Social signup: Continue with Google button doesn't work on Windows Phone

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#15396]
On Windows Phone tapping the "Continue with Google" button doesn't do anything. You can see the button active state when you click and if you're scroll downed or have the keyboard open it jumps to the top of the page, so it's recognizing the tap at least.

The links and buttons on the page work fine.

Tested with Windows Phone 8.1 via BrowserStack

**Comment by pento** [comment]
Fixed by 37af8fb7f738d3741c5ba20c596bc0c814a83347.
