### ISSUE TITLE
Editor: ctrl+d on the Mac behaves differently than fn+del on "empty" lines in the visual editor

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#15410]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Draft a new post in the "visual" editor
3. Enter some "paragraph" text & hit enter
4. Enter a different type of text -- an `<h2>` for example
5. Delete all the text in the top "paragraph" line
6. Press fn + delete
7. Notice the H2 remains intact
8. Press ctrl + z to "undo" (or repeat the above)
9. Instead of fn + delete, press ctrl + d
10. Notice the H2 is removed & the text is now a "paragraph"

#### What I expected
The H2 to remain in both cases -- moreover, for ctrl+d to behave identically to fn+del

#### What happened instead
The behaviors differed, the H2 is unexpected stripped when pressing ctrl+d

#### Browser / OS version
Chrome 59 / Mac Sierra

#### Screenshot / Video
https://cloudup.com/ck7fQW0TWx6

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
