### ISSUE TITLE
WooCommerce: payment settings saving behaviour

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15415]
Currently the saving behaviour on our payments screen is inconsistent with the designs for our other settings screens and Calypso settings screens in general.

* ~The header bar is missing.~
* Save button should be in header bar.
* All changes should only be applied when that save button is clicked. Auto-saving currency switches is dangerous xD

In addition to this we'd like to switch away from foldable cards to modals for method editing. This would make Payments consistent with Shipping and allows us to move away from the weird 'setup'/'done' button which is kinda sucky atm. This change should have been surfaced in the original designs, sorry about that.

**Comment by kellychoffman** [comment]
Agree. Thanks for writing up the list. This will help with consistency across screens and help and help prevent accidental changes. 

> The header bar is missing.

This was just added in: https://github.com/Automattic/wp-calypso/pull/15407 but hasn't been merged.

**Comment by belcherj** [comment]
https://github.com/Automattic/wp-calypso/pull/15993 Moves edit to dialog

**Comment by justinshreve** [comment]
#15995 has been merged and closes this out.
