### ISSUE TITLE
Checkout: It's possible to remove "Domain Late Renewal Fee" from cart

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#1541]
It's possible to remove the Domain Late Renewal Fee from the shopping cart when checking out. This causes an issue, where the user is prompted to pay only for the domain's Private Registration.

Steps to replicate:
- Choose the option to Renew Now on the Manage Purchase page for a domain that is in redemption in order to get to checkout.
- View the cart after being taken to checkout. It will show the Domain Late Renewal Fee alongside Domain Registration and Private Registration.
- Click on the **X** next to Domain Late Renewal Fee in order to remove it from the cart.

<img width="100%" alt="screen shot 2015-12-14 at 12 57 50" src="https://cloud.githubusercontent.com/assets/2998162/11781576/c14f0558-a262-11e5-9b32-6d4e70821cb8.png">

Result:

Removing Domain Late Renewal Fee will result in only Private Registration being left in the cart. A user can then purchase Private Registration as a standalone upgrade. Purchasing Private Registration will, however, not trigger the domain's renewal.

<img width="100%" alt="screen shot 2015-12-14 at 13 01 50" src="https://cloud.githubusercontent.com/assets/2998162/11781767/0a1212c0-a264-11e5-8bc2-d989c4f53e97.png">

It should not be possible to remove Domain Late Renewal Fee from the cart, as payment of the fee is needed in order to trigger the domain's renewal.

Reported in: 2457060-t and 2457056-t.

**Comment by bikedorkjon** [comment]
@SiobhyB I just tested this and it appears to be fixed. Can you confirm before closing?

**Comment by SiobhyB** [comment]
@bikedorkjon: I tested and the option to remove the Domain Late Renewal Fee from the cart was still there.

**Comment by janm6k** [comment]
Going through old issues, closing ones that did not have any activity in long time.

Please feel free to reopen if applicable.
