### ISSUE TITLE
Checkout: Broken Styling on Secure Payment Form Placeholder

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#15417]
#### Steps to reproduce
1. Get to https://wordpress.com/checkout/<YourDomain> by adding a domain, plan or google apps product to your cart
2. Refresh the page (This is the most surefire way, you also see it pop up at other times)

#### What I expected
I was expecting a placeholder with glowing grey fields in, somewhat like the component.

#### What happened instead
We show a blank card, that looks more like a bug than a placeholder

#### Browser / OS version
Version 60.0.3112.40

#### Screenshot / Video
![checkout_ _julesauspremiumtest_ _wordpress_com](https://user-images.githubusercontent.com/5952255/27460466-5aef3f7a-57f7-11e7-851f-e17b9b79369d.jpg)

#### Context / Source
The component itself ([secure-payment-form-placeholder.jsx](https://github.com/Automattic/wp-calypso/blob/120c72cece0c86f7c22899d51eccab6deca57162/client/my-sites/upgrades/checkout/secure-payment-form-placeholder.jsx)) has plenty of fields and structure, as well as [styling](https://github.com/Automattic/wp-calypso/blob/120c72cece0c86f7c22899d51eccab6deca57162/client/my-sites/upgrades/checkout/style.scss), but it looks like it's not working as intended.

**Comment by rralian** [comment]
Calling this an enhancement, honestly it's pretty low priority so not going to get to this anytime soon.

**Comment by deBhal** [comment]
You're right, let's just close it.

I was looking at the code, where I'm pretty sure there is a logic error, but from a design perspective, this is just noise.
