### ISSUE TITLE
NUX: Broken flow when attempting to purchase plan

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#15439]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Go through the signup steps and choose a paid plan

#### What I expected
To be sent to the shopping cart to purchase the plan

#### What happened instead
After the account is created I'm sent to the login screen.  At this point I am actually logged in, but the user doesn't know that.  I put in my password and am sent directly to the Reader as a normal login.  The plan is in my shopping cart, but I have no idea where that is as a new user.

#### Browser / OS version
Seen here in OSX Chrome

#### Screenshot / Video
![wp-calypso-nux-bug](https://user-images.githubusercontent.com/7233112/27482608-1b0be82e-57f0-11e7-9e5d-0ee670955e7a.gif)

#### Context / Source
#automated-testing

**Comment by lancewillett** [comment]
Caused by backend changes: r158156-wpcom — reverted 6 hours later in r158165-wpcom

**Comment by stephanethomas** [comment]
This was fixed with a server change. Thanks for the detailed instructions!
