### ISSUE TITLE
Jetpack Invites: Unable to upgrade Contributor to Author

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#15456]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/people/new/JETPACKSITE (with Jetpack 5.0)
2. Invite a new user as a Contributor
3. From an incognito window open the e-mail and accept the invitation, creating a new account
4. Verify you can create a new post and Submit for Review, but not post directly
5. From the original browser window open the People tab and find the new user
6. Upgrade the user to Author
7. Switch back to the incognito window and refresh

#### What I expected
To now have permissions to publish a post without review

#### What happened instead
My permissions seem to be stuck at the Contributor level.  Both Calypso and wp-admin on the Jetpack site show the user as an Author.

I tried logging out and in, starting from a fresh browser, etc, but was unable to see the new permissions.

Inviting a user as an Author to start does properly allow posting without review.

Ref: #15357 cc: @lezama 

#### Browser / OS version
Seen here in OSX Chrome

#### Screenshot / Video
![screen shot 2017-06-23 at 2 45 01 pm](https://user-images.githubusercontent.com/7233112/27496089-9365a0ee-5822-11e7-9c5f-d060999ecb87.png)

#### Context / Source
#automated-testing (initial setup of Invite flows for Jetpack tests)

**Comment by lezama** [comment]
I think this should fix it: https://github.com/Automattic/jetpack/pull/7328

cc @roccotripaldi and @dereksmart

**Comment by alisterscott** [comment]
Retested and fixed 🎉
