### ISSUE TITLE
Reader Tags: keep case formatting as entered by user

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#1546]
When typing in tags, the Reader changes the case formatting to a default one already in the system, for example:
- typing "Dream" becomes "dream"
- typing "dreams" becomes "Dreams"
- typing "AUTOMATTIC" becomes "Automattic"
- typing "wordpress" becomes "WordPress"
![anim](https://cloud.githubusercontent.com/assets/15944096/11785243/cd221100-a2bb-11e5-81bd-adc8c3866a5d.gif)

Even though tags are not case sensitive (when handled by the backend), it would make a better user experience to have tags display the way users intended them to appear.

(Mentioned in 280129-chat)

**Comment by lancewillett** [comment]
See also #2551

**Comment by blowery** [comment]
We can't keep the case, as we normalize the text entered to match up with the global tag tables.

**Comment by lancewillett** [comment]
Sounds like global tag normalization wins. Closing as we won't be making the suggested changes.
