### ISSUE TITLE
Store: Localize currency symbols

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#1547]
Currently prices for domains and other products are displayed with a currency symbol, such as $ or €:

<img width="145" alt="de-euro" src="https://cloud.githubusercontent.com/assets/203408/11786220/b86f9c90-a285-11e5-968e-71225a4ddedc.png"> <img width="181" alt="en-dollar" src="https://cloud.githubusercontent.com/assets/203408/11786221/b9c64c60-a285-11e5-8b70-953043bcc74f.png">

In some countries, though, the $ sign is used for the local currency, for example for peso in Argentina. So displaying something like
<img width="190" alt="es-dollar" src="https://cloud.githubusercontent.com/assets/203408/11786245/d4d3f8e0-a285-11e5-8a24-9d8d6f062a0a.png">
can be confusing.

Therefore:
- In each country, show prices in the local currency (if available) using the usual sign for that country.
- Show every other currency than the local one using the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code.

<img width="206" alt="en-eur" src="https://cloud.githubusercontent.com/assets/203408/11786392/b32674b0-a286-11e5-8842-267824f10170.png"> <img width="218" alt="es-usd" src="https://cloud.githubusercontent.com/assets/203408/11786393/b34be844-a286-11e5-9bbe-3f5d8a72e29b.png">

What might make the implementation of the fix trickier, is that for the displayed currency there is also a geographic component (for example with English display language but location in Europe, the Euro sign is being displayed).

**Comment by lamosty** [comment]
If I'm not mistaken, #6046 solves a part of this.

**Comment by rantoncuadrado** [comment]
@lamosty not sure. As this is already using $ instead of USD and there are lots of countries using $ as their currency symbol from Liberia Dollar to Mexican Peso (Argentina, Chile...)

More info here: http://www.xe.com/symbols.php

**Comment by rantoncuadrado** [comment]
Again, another example today with user cititsolutions reporting this should be clarified :)

**Comment by rachelmcr** [comment]
This came up in another support conversation, where a user in Brazil thought the displayed price was in BRL instead of USD. (Internal ref: 197408-h) Additional clarification about the $ sign referring to USD would help in these cases.

**Comment by iamtakashi** [comment]
I'm glad this has already been looked into. We'll have more confused users with Simple Payments that has just launched.

**Comment by iamtakashi** [comment]
I've just realised how old this issue is, and I wonder if it helps to tackle this issue bit by bit  - making $ symbol always explicit including for US Dollar, that alone will go a long way.

**Comment by simison** [comment]
I merged a fix that helps a bit with some $ currencies https://github.com/Automattic/wp-calypso/pull/28380

Instead of "$" we now show "S$"for Singapore dollar etc:

    Singapore dollar SGD → S$
    Barbadian dollar BBD → Bds$
    Brunei dollar BND → B$
    Fijian dollar FJD → FJ$
    Guyanese dollar GYD → G$
    Liberian dollar LRD → L$
    Namibian dollar NAD → N$
    Solomon Islands dollar SBD → S$
    Tuvaluan dollar TVD → $T

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
At some point, the `/shopping-cart/` endpoint started returning an indicator for non-US currencies that use the $. This should be fixed in Checkout. Closing.

<img width="309" alt="Screen Shot 2020-07-19 at 10 25 39 AM" src="https://user-images.githubusercontent.com/942359/87877122-71daa800-c9aa-11ea-919b-b6eda37ad346.png">
