### ISSUE TITLE
Login: replace "SMS" with "text message"

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#15473]
The term "SMS" is used in a few Calypso strings (and elsewhere in WordPress.com), in reference to account access codes sent via SMS text message. 

However, "SMS" is not a common term in top English-speaking locales. The phrase "text message" is probably going to work much better for English readers.

For example, according to Wikipedia:

> It may simply be referred to as a "text" in North America, the United Kingdom, Australia, New Zealand and the Philippines, an "SMS" in most of mainland Europe, or an "MMS" or "SMS" in the Middle East, Africa, and Asia

For the default en_US locale (as in, the locale we use for the original strings), I suggest we replace the use of "SMS" with "text message". 

It's worth noting that we are not using the term "SMS" consistently. We also already use "text message" in different places. For this reason, I don't think we have to worry too much about doing a big copy review or anything. It would be enough to just change this gradually as we go.

For example, in [recovery-phone-validation-notice.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/me/security-account-recovery/recovery-phone-validation-notice.jsx):

Before:

> Please validate your recovery SMS number. Check your phone for a validation code.

After:

> Please validate your recovery phone number. Check for a text message with a validation code.

Before:

> Enter the code you receive via SMS:

After:

> Enter the code from the text message:

**Comment by benhuberman** [comment]
I missed the original Editorial ping, but I wholeheartedly agree -- "text message" definitely feels a lot more universally and immediately understandable. This also goes with our broader preference to avoid terms that sounds jargon-y unless we have to and/or it's a widely known term (SMS is borderline in that sense, but still -- "text message" is definitely better).
