### ISSUE TITLE
Store: Update currency position, decimal places, and separator values when the currency updates.

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#15498]
In addition to the currency code, WooCommerce also has the following settings:

* `woocommerce_currency_pos`
* `woocommerce_price_decimal_sep`
* `woocommerce_price_num_decimals`
* `woocommerce_price_thousand_sep`

In our MVP, we only support currencies with the following values: Thousands separator: `,`, decimal: `.`, number of decimals: `2`, and position: `left`.

Once we start supporting other currencies, we need to make sure to set the correct values automatically when the currency gets set.

We can get some of those values for currencies [here](https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/lib/format-currency/index.js#L6).

**Comment by alisterscott** [comment]
I don't think this is a Signup for WordPress.com issue so I've removed the label

**Comment by synora** [comment]
Closing as Store has been deprecated.
