### ISSUE TITLE
Reader: Add support for Reddit embeds

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#1549]
Reddit has a really nice WordPress.com blog—one of my favorites to read—but unfortunately Reader doesn't know what to do with the Reddit embeds that they use a lot: https://upvoted.com/2015/12/14/redditors-photoshop-ewan-mcgregor-in-front-of-a-green-screen/

In Reader, these embeds don't alway include the relevant information, but do link to the Reddit post: https://wordpress.com/read/post/feed/37856615/886109663

<img width="711" alt="screen shot 2015-12-14 at 11 30 15 am" src="https://cloud.githubusercontent.com/assets/191598/11786714/15c98cfa-a256-11e5-9ec2-4f98b5a83def.png">

I'd be great if we can make them look more like they should:

<img width="599" alt="screen shot 2015-12-14 at 11 30 22 am" src="https://cloud.githubusercontent.com/assets/191598/11786729/21f68582-a256-11e5-9d1b-2fdcf4d6fbc4.png">

**Comment by blowery** [comment]
What's weird there is that the embeds don't appear on the original post...

**Comment by shaunandrews** [comment]
> What's weird there is that the embeds don't appear on the original post...

Not sure what you mean here — I see them at the URL above.

**Comment by blowery** [comment]
> Not sure what you mean here — I see them at the URL above.

Ah, adblocker got me. 

Either way, these arn't really embeds using oEmbed, they're custom things using a script from reddit. Unsure we want to support that, though we may for twitter and facebook... hrm.

**Comment by alisterscott** [comment]
I can confirm this is still an issue.

A reddit embed in a WordPress.com post:

<img width="776" alt="screen shot 2017-05-11 at 2 08 54 pm" src="https://cloud.githubusercontent.com/assets/128826/25932091/66bbefb2-3653-11e7-8e91-17ac6ef74857.png">

In The Reader:

<img width="782" alt="screen shot 2017-05-11 at 2 09 10 pm" src="https://cloud.githubusercontent.com/assets/128826/25932125/73aa78f6-3653-11e7-9ac3-263118395aaa.png">

**Comment by blowery** [comment]
Yup, though we have a way to support this now...
