### ISSUE TITLE
Themes: when the word "free" is used in theme search, activate the free themes filter

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#155]
Reported by @MichaelArestad 

> I've witnessed a few people do something like this. Seems like an easy win to just return free themes (or a theme with "free" in the name/description/meta.

![image](https://cloud.githubusercontent.com/assets/1123119/9892170/983ec80e-5bc9-11e5-8fe2-abb7672e515a.png)

Locking the label "free" with the free filter seems like a good win here.

**Comment by folletto** [comment]
> Activating the "Free" dropdown makes sense, in the UI, also — to show what's happening.

:y:

**Comment by folletto** [comment]
We had another +1 for this feature by @sixhours

**Comment by MichaelArestad** [comment]
Still would be nice.
