### ISSUE TITLE
Reader: first post placeholder in Search appears too high up

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#15500]
Tested in IE11:

<img width="913" alt="screen shot 2017-06-26 at 11 26 58" src="https://user-images.githubusercontent.com/17325/27547827-2833da1c-5a65-11e7-95ab-40d6197664d3.png">

**Comment by fraying** [comment]
Same in Safari. 
![screen shot 2017-06-26 at 9 34 09 am](https://user-images.githubusercontent.com/24388/27549939-a0ce591a-5a52-11e7-94f9-c1cff4f5d999.png)
