### ISSUE TITLE
WooCommerce: Display Store Setup button on sidebar for sites that have not yet gone through the AT process

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#15508]
For MVP we decided to only display the store item on the calypso sidebar for sites that had completed the automated transfer process.  For v2 let's display the store item on the calypso sidebar for sites with the business plan that have not yet started the automated transfer process.

Then after they (or while they) complete filling in the business location, the first plugin (woocommerce?) could be installed to initiate the process.

cc @kellychoffman @rralian @justinshreve

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb.2021. Closing it in favor of that.
