### ISSUE TITLE
Switching between Visual & HTML views converts &lt;some_text&gt; to <some_text>, and then clears it as unmatched tag

### ISSUE THREAD

**Issue by adityabhaskar** [Automattic/wp-calypso#15506]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/\<your-test-site\>.wordpress.com/
2. Create a post in the **Visual mode**, and anywhere in the post type "`<up>`"
3. Now switch to **HTML mode**, and then switch back to visual mode.

#### What I expected
Back in the visual mode, expect to see a code section with `<up>` inside it.

#### What happened instead
Saw an empty code section - ` `
During the switch between modes, the \<up\> is parsed as a tag, and then removed (since it's an unmatched tag).

#### Browser / OS version
Chrome v59

#### Context / Source
#user-report

You can also replicate the bug by creating a post in **HTML mode**. Create a code section:
```<code>&lt;up&gt;</code>```

Now, switch to Visual mode, then back to HTML mode, and back to Visual mode. The "\<up\>" disappears again.

**Comment by rachelmcr** [comment]
Thanks for the report! I'm going to close this issue as we're tracking various issues with code being stripped out of the editor here:

https://github.com/Automattic/wp-calypso/issues/9142
