### ISSUE TITLE
Sites Results in Search: No recent posts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15505]
While testing Site Results, I've noticed many site results that lead to the "No recent posts" message.

For example, this search ... https://wpcalypso.wordpress.com/read/search?&q=powazek ... the fifth site result is for https://wpcalypso.wordpress.com/read/feeds/54377380 which shows this:

![screen shot 2017-06-26 at 9 27 21 am](https://user-images.githubusercontent.com/24388/27549696-b1c977b4-5a51-11e7-9635-f28ca88aa99e.png)

Would it be possible to omit site results if Reader has no posts to show? Results like this are a bad experience.

@gibrown

**Comment by blowery** [comment]
Weird. We should have those posts still, they're only a year old...

**Comment by fraying** [comment]
Oh, well, that may be so, but I've seen that "no posts" screen for other sites/searches.

**Comment by blowery** [comment]
> Oh, well, that may be so, but I've seen that "no posts" screen for other sites/searches.

Right, but if the criteria here is "don't show sites that we don't have posts for" and we don't have feed posts indexed, we'll have to use a heuristic like "demotes sites with posts no recent posts". That rule would likely be tied to the feedbag lifetime, which is currently 2 years, but it may not help in cases like this where the posts are missing...

Another option would be to stop linking to the feed view and instead link to the site view. The site view always has all of the posts, but it works best for wpcom sites that are not VIPs. It's unreliable for VIPs and Jetpack sites.

**Comment by gibrown** [comment]
Ya, I think these are cases of the feedbag and posts on blogs being out of sync. Linking to the blog would probably fix it, but then we might not render the content well...

**Comment by blowery** [comment]
> Linking to the blog would probably fix it, but then we might not render the content well...

I think we can sort that out if we're picky. Only link to the site feed for wpcom-hosted sites that are not vips.
