### ISSUE TITLE
Search: Sites: Wide width: Icons misaligned 

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15507]
Similar to #15080, only this time for wide widths.

The Following and Settings icons are 2px too far to the right in site results at a wide width.

<img width="990" alt="screen shot 2017-06-26 at 9 42 57 am" src="https://user-images.githubusercontent.com/24388/27550300-05ec2cb8-5a54-11e7-9a19-ffbb360fcd0d.png">

Which results in this little scoot to the right when following:

https://cloudup.com/cAdA4xtzD33

The icon should be lined up with the others, so all that changes is the color and the checkmark.

@jancavan

**Comment by jancavan** [comment]
Hmm, I thought this was fixed... 👀

**Comment by fraying** [comment]
@jancavan They're perfect at narrow width! :)
