### ISSUE TITLE
Framework: Move components from /shared back to /client

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#1551]
The scope of the first stage of server-side rendering will be limited to the [logged-out masterbar](https://github.com/Automattic/wp-calypso/issues/1327). Also, we will move to some technique for marking components safe to use server-side that does not involve the directory structure, whilst renaming `/client` to `/app` or similar.

Therefore, we can move any components not required for the logged-out master bar out of `/shared` and back to `/client`.

**Comment by ehg** [comment]
While we're doing this, let's add the `@ssr-ready` pragma to everything we know is compatible.
