### ISSUE TITLE
Reader: Follow notifs don't auto-dimiss after following more than 2 sites consecutively

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#15517]
![screenshot 2017-06-26 12 37 06](https://user-images.githubusercontent.com/4924246/27557000-c9986f9c-5a6c-11e7-88cf-393a3d3de8ad.png)

Video: https://cloudup.com/col8J7pNlwc

Happens everywhere in Reader.

**Comment by fraying** [comment]
Aha! I've experienced this, too, but couldn't figure out when it happens. Nice catch, @jancavan.

@blowery Since this is a global component, is this something we can fix?

**Comment by jancavan** [comment]
I think it's not just when you follow, but also happens when you unfollow more than two sites in a row. The third and fourth notifications don't gets dismissed automatically.

![screenshot 2017-06-26 12 51 17](https://user-images.githubusercontent.com/4924246/27557354-2bd984a6-5a6e-11e7-9ef6-7441d17ae46a.png)

**Comment by blowery** [comment]
@fraying my guess is that this is a bug in the notice component...

**Comment by jancavan** [comment]
Another thing I noticed - if you follow then unfollow immediately, the unfollow notification doesn't get auto-dismissed as well: https://cloudup.com/cEo_4JA6oSW

**Comment by blowery** [comment]
@jancavan could you try #15520? should fix all those issues.

**Comment by jancavan** [comment]
@blowery Works great now.
