### ISSUE TITLE
WooCommerce: Sidebar active states

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15528]
The following active states are missing / incorrect;

* When on the add product screen, the 'products' link should be active
* When on the add order screen, the 'orders' link should be active
* When on the Payments, Shipping or Taxes settings screens, the 'settings' link should be active.

**Comment by justinshreve** [comment]
https://github.com/Automattic/wp-calypso/pull/15254#issuecomment-311433243
