### ISSUE TITLE
Editor: should we support editor styles from the active theme?

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1553]
Raised by @gcorne  

There are arguments both for and against supporting editor styles from the active theme. Here is a brief summary (snippets) of past conversations about this topic:

From @mtias 

> Editor styles are tricky — they vary in terms of how much they change, with some themes only modifying the font and colors, and some others constraining the width (which looks really odd sometimes). They also usually don't account for responsiveness. The way they handle images is also something to consider, especially captioned ones.

From @folletto 

> I know they can be wonky, but they are the only way we have right now to make the page feel more integrated and I feel they are worth it. :)

From @kellychoffman 

> I think we should support editor styles but limit them to fonts and colors. I know we love Merriweather but an average user probably won't care and would like to see their site's look and feel come through a bit.

From @MichaelArestad 

> It's a strong no from me. I think our editor should encourage a semantic and familiar editing experience. Editor styles (even just fonts) tend to wreck the visuals, but more importantly, they don't really feel like the end result much. I think they ultimately make our editor look pretty bad and give users a false sense of confidence in how the content will look when published.

The end result of past conversation was that this is not a current priority and we should re-visit the issue in the future.

**Comment by designsimply** [comment]
Closing given the conversation. It can be revisited in the future if needed.

**Comment by kwight** [comment]
Given we now have Gutenberg in Calypso, and discussion in p7jreA-23h-p2, I'm reopening this to see what we can do about getting theme styles available to Calypso.

**Comment by kwight** [comment]
Closing again in favour of #30098; we'll continue to leave theme styles out of consideration for the regular Calypso editor, but make them available for Gutenlypso.
