### ISSUE TITLE
Social Login: Allow logging into an existing WP.com account with a Google account

### ISSUE THREAD

**Issue by pento** [Automattic/wp-calypso#15542]
When a user tries to login or signup Google account that matches the email of an existing WP.com account, we should offer to link their accounts together.

See these initial designs from @scruffian:

<img width="491" alt="screen-shot-2017-06-20-at-15-18-11" src="https://user-images.githubusercontent.com/352291/27571714-eca47d80-5b4a-11e7-861d-d94a3660d571.png">
<img width="461" alt="screen-shot-2017-06-20-at-15-22-41" src="https://user-images.githubusercontent.com/352291/27571716-f2a2a9e6-5b4a-11e7-90ae-4526b2cdfc78.png">

**Comment by ranh** [comment]
Jumping in with some new copy.

For the first screen:

> Log in to your account.
> 
> We found an existing WordPress.com account with the email address "mail@example.com". Log in to this account to connect it to your Google profile.
>
> (form)
>
> Or, choose a different Google account:
>
> (button)

Question: do we need the "keep me logged in" option here? I don't think it really applies. 

For the second screen:

> Connect to Google.
> 
> Connect your WordPress.com account to your Google profile. You will be able to use Google to log in to WordPress.com.
>
> (button)

**Comment by ranh** [comment]
PS, do we need to replace the G logo here @danhauk?

**Comment by danhauk** [comment]
@ranh I'm not completely sure, but I think it's fine to use here. We're not allowed to use it as a cloud partner (i.e. the [G Suite offer](https://github.com/Automattic/wp-calypso/pull/15499) in my domains), but we have to use it for the [log in button](https://developers.google.com/identity/branding-guidelines). This is not technically the log in button, but it is part of the log in / connect flow.

**Comment by pento** [comment]
> Question: do we need the "keep me logged in" option here? I don't think it really applies.

I think so, yes. The user is still logging in at this point, even if we're adding a bonus "connect your social account" after it.

**Comment by ranh** [comment]
This process of logging in starts when users first hit the "Continue with Google" button on the first screen. We don't have a "keep me logged in" checkbox for social login on that first screen, we keep you logged in by default. 

Adding the checkbox here makes a special case for users doing social login and connecting an account at the same time. We should either have this available to all social login users, or not at all.

**Comment by pento** [comment]
@ranh: Good point, I'll remove the checkbox. 🙂

**Comment by scruffian** [comment]
@pento I think we can close this now correct?

**Comment by pento** [comment]
Yup, fixed via ff1a7c9.
