### ISSUE TITLE
Editor: Jetpack sites don't show a correct draft count

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1555]
Steps to reproduce:

1. Go to https://wordpress.com/post for a Jetpack-connected site that has several saved draft posts
1. Click "Drafts" at the top of the sidebar
1. Compare the number next to "Drafts" with how many drafts are in the list

<strong>Result:</strong> the drafts count doesn't match the number of drafts in the draft drawer

![screen shot 2015-12-14 at 12 42 23](https://cloud.githubusercontent.com/assets/1119271/11788759/a2f835fe-a260-11e5-9cb1-a4ee17be4e96.png)

I also checked the api response for `/v1.1/sites/disambiguously.com/post-counts/post` and it returned:

```
"counts": {"all": {"publish": 4, "draft": 1, "trash": 1}, "mine": {"draft": 1, "publish": 4}}
```

/hat tip @mattwiebe for the original report

Note from @codebykat 

> Okay, this is an issue with whether we're able to access non-public Jetpack post counts, which right now we cannot.

**Comment by mtias** [comment]
Related to why we don't have counts in `/posts` for jetpack sites yet. Bumped priority because at least we should hide the incorrect number.
