### ISSUE TITLE
Editor: Publish button switching to Schedule button

### ISSUE THREAD

**Issue by ShinyRockets** [Automattic/wp-calypso#15566]
#### Steps to reproduce
1. Pages->Add
2. Add page title
3. Click on background of editor, Publish button appears, but then switches to Schedule after a few seconds.

#### What I expected
Publish button to remain.

#### Browser / OS version
Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Windows 8.1

#### Screenshot / Video
https://thecrowsnest.ca/bugs/

Posted to Support Forum: https://en.forums.wordpress.com/topic/bug-or-feature?replies=3#post-2975383

**Comment by ShinyRockets** [comment]
Just to add, when you click the now Schedule button, it acts like the Publish button.

**Comment by KokkieH** [comment]
I'm not able to replicate this. Is the site timezone setting by any chance set to something different than your computer's?

If you open Page Settings ->Status, what is shown as the publication date/time, and how does that compare with the actual date/time where you are?

**Comment by ShinyRockets** [comment]
Status showed 'Future' and was set 5 minutes ahead of computer's clock, which was slow by, ahem, 5 minutes.

I opened system's Start -> Date and time settings, and 'Set time automatically' was 'On', which seemed weird. I 'turned it off and back on again', and it jumped ahead to the correct time,

Went back to the Editor and all was well in the Universe once again. 

Good call!

**Comment by KokkieH** [comment]
Confirmed. If the computer clock is behind the actual time, the Publish button changes to Schedule the moment autosave triggers. This also happens on both posts and pages.

WP-Admin immediately publishes the post created with the computer clock synced back, even though the publication date is in the future relevant to the computer clock, so it could still be a bug that the Calypso editor doesn't do the same.

**Comment by KokkieH** [comment]
On the other hand, my previous comment on this issue shows as having posted 11 minutes from now, so maybe having the computer clock set incorrectly just causes weirdness all round 😄

**Comment by rachelmcr** [comment]
Thanks for this report! This issue is related to the editor using the system time instead of your site's timezone. I'm going to close this issue as we're tracking the system v. site timezone issue here: https://github.com/Automattic/wp-calypso/issues/18124
