### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15565]
I keep seeing broken images in Site Results.

https://wordpress.com/read/search?q=Techcrunch&focus=1&show=Sites

<img width="592" alt="screen shot 2017-06-27 at 9 47 30 am" src="https://user-images.githubusercontent.com/24388/27599509-d85858ec-5b1d-11e7-97ac-d3d60dc8ef25.png">

https://wordpress.com/read/search?q=powazek&focus=1&show=Sites

<img width="602" alt="screen shot 2017-06-27 at 9 49 17 am" src="https://user-images.githubusercontent.com/24388/27599536-e7465b60-5b1d-11e7-9f3a-4099e6c59c3c.png">

https://wordpress.com/read/search?q=waxy&focus=1&show=Sites

<img width="600" alt="screen shot 2017-06-27 at 9 49 47 am" src="https://user-images.githubusercontent.com/24388/27599553-f95e0636-5b1d-11e7-8468-3be545cdbd1f.png">

Is there any way to avoid this? This makes the whole site feel unprofessional.

**Comment by blowery** [comment]
working on this one.

**Comment by fraying** [comment]
Thanks, @blowery!
