### ISSUE TITLE
Editor: [wplink] does not remember checked "open in new window" box

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1556]
Raised by @drw158 

What I Did: Checked the "open in new window" box when adding several links.

What I Expected: For the editor to remember that I checked the box previously.

What Actually Happened: The editor did not remember that I checked the box previously (during the same writing session) so I had to check it every time I added a link.

![screen shot 2015-12-14 at mon dec 14 1 00 12 pm](https://cloud.githubusercontent.com/assets/1119271/11789252/5547ffa8-a263-11e5-8335-2895a20b6050.png)

Note from @lancewillett 

> Would keeping the link checked be intentional? It seems like a bad practice to enforce that or make it the default. Most links should open in the same window/tab per web design best practices.

Reply from @drw158 

> In the old editor, it was very convenient that it remembered my setting for the rest of the writing session, especially if I'm linking to ~10 external links on a single post. I believe that on the next writing session, it would reset, and default back to unchecked.
> 
> I **agree** that opening a link in the same window should be the default, but it would be a very nice touch/enhancement if the editor recognized that I just checked the`Open link in a new window/tab` setting for a link I just created, and automatically checked `Open link in a new window/tab` for all subsequent links that I create during that writing session.
> 
> I don't think it's a best practice issue, but more of a smart enhancement that makes it easier to write. Just to clarify, this would be bringing over a feature that already existed (I'm pretty sure) in the older editor, not creating a new feature.

Note from @designsimply

> Making the "open link in new tab/window" option sticky was also requested by thefreevolous in [#comment-146](https://horizonfeedback.wordpress.com/2015/09/14/call-for-testing-editor/comment-page-1/#comment-146) on +horizonfeedback.
> 
> Here is her explanation for wanting the sticky setting back:
> 
> > I prefer to put have all my links opening in another tab/window, so that the visitor doesn’t have to leave my page at any time. in the horizon editor, there’s always a couple of them I end up missing…
> > BUT I know that not everybody agrees with this, so that’s why the preexisting feature (having to check the box just for the first one) was so cool…
> > I mean, if there’s no plan for/way of defining that for the whole blog, of course.

Note from @pdotk

> A user in live chat also requested this feature. 
> 
> > And is there any way to make the links work as before, where once you clicked the "new page" box for a link, that was the default for all other links you add to a post? 
> > The linking issue actually bugs me far more. It's a repetitive thing, and it gets old in a hurry!

**Comment by brbrr** [comment]
I going to close this issue since there no much activity around.
