### ISSUE TITLE
Comments: login redirect is incorrect from /comments

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#15584]
Clicking on a redirect link like:
https://wordpress.com/wp-login.php?redirect_to=https%3A%2F%2Fwpcalypso.wordpress.com%2Fcomments%2F

Will add an `undefined` variable to the path. The user is unable to select a site at this point.

**Comment by kwight** [comment]
Closing, as I can no longer replicate this; with the `undefined` no longer being appended by the forward, the user is forwarded to just `/comments`, where the site selector allows them a proper destination of `comments/pending/(site selected)`. This may have been a change to the `login_redirect` filter somewhere on WordPress.com, but I didn't find an obvious patch responsible.
