### ISSUE TITLE
Editor: better tooltips (title attributes) on Visual/HTML buttons

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1560]
Raised by @nb 

What I Did: I hovered on the _Visual_ and _HTML_ buttons.

What I Expected: to find more useful information than the button labels: short explanation of the mode and the keyboard shortcut to switch between both.

What Actually Happened: found just the button labels.

![screen shot 2015-12-14 at mon dec 14 1 32 10 pm](https://cloud.githubusercontent.com/assets/1119271/11789926/322cdddc-a267-11e5-997c-b29e522de409.png)

**Comment by gyoshev** [comment]
There [don't seem](https://codex.wordpress.org/Keyboard_Shortcuts) to be any shortcuts listed for that functionality in Codex, nor are there any in [key-bindings.js](https://github.com/Automattic/wp-calypso/blob/master/client/lib/keyboard-shortcuts/key-bindings.js). Am I missing something? If not, will such shortcuts prove useful?

**Comment by aduth** [comment]
Fixed by #3883

**Comment by aduth** [comment]
>Do the mentioned shortcuts exist?

There are not any to my knowledge, no.

>If not, will such shortcuts prove useful?

Perhaps. As both keyboard shortcuts and the HTML editing mode itself are both power user features, it may prove to be a useful feature to that subset of users. I'd certainly not be opposed to such an enhancement.
