### ISSUE TITLE
Interface languages displaying the wrong day on the schedule calendar

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#15615]
#### Steps to reproduce
1. Go to Account Settings
2. Set the interface language to 'en-gb - English (UK)'
3. Click 'Save Account Settings'
4. Blog Posts > Add
5. Click 'Status' and then the date

#### What I expected

The 28th June 2017 to be marked as a Wednesday (this would be the correct day of the week).

![calendar-correct-en](https://user-images.githubusercontent.com/11627765/27642444-bad3acdc-5c16-11e7-8a03-f62eacfd1577.jpg)

#### What happened instead

The 28th June 2017 is marked as a Thursday (this is the wrong day of the week). It should be Wednesday.

![calendar-incorrect-en-gb](https://user-images.githubusercontent.com/11627765/27642451-bf6a51ce-5c16-11e7-9261-581285ce1068.jpg)

I have also been able to replicate the same issue by changing the interface language for a sample of other languages. In these languages, 28th Jun 2017 is incorrectly displayed as a Thursday:

- nl - Nederlands
- fr - français
- tr - Türkçe
- hu - Magyar
- pl - Polski
- ru - Pусский

This also happens in other calendar months and isn't limited to June 2017.

I've found one exception to far — switching the interface language to 'en - English' does display the correct day of the week.

#### Browser / OS version

All browsers.

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/MyPSVITApl/status/881860846581932032)

**Comment by KokkieH** [comment]
Appears to be a similar issue to #6138

**Comment by KokkieH** [comment]
Another report in 867701-f. Site language set to fr.

**Comment by KokkieH** [comment]
Another via [Twitter](https://twitter.com/MinieHouselook/status/882587385892089860).

**Comment by rachelmcr** [comment]
@retrofox It looks like you made the most recent changes to this date picker — do you know why this is happening?

**Comment by retrofox** [comment]
let me take a look

**Comment by iamgabrielma** [comment]
With a Spanish interface seems to be happening the same, the week in Martes (Tuesday):

- Calypso:
<img width="309" alt="screen shot 2017-07-12 at 10 26 13" src="https://user-images.githubusercontent.com/3812076/28118093-1f14d262-6710-11e7-8693-238b0cbd1226.png">

- Classic:
<img width="313" alt="screen shot 2017-07-12 at 10 23 01" src="https://user-images.githubusercontent.com/3812076/28118101-223e6642-6710-11e7-9e7a-8627405d60ee.png">

**Comment by retrofox** [comment]
> With a Spanish interface seems to be happening the same, the week starts in Martes (Tuesday):

Please check this PR: https://github.com/Automattic/wp-calypso/pull/16130

@iamgabrielma I've added you as reviewer _por comedido_ :-D

**Comment by gemmagarner** [comment]
Another report on [Twitter](https://twitter.com/365tipu/status/885200054323208192) (en-gb - English UK)
