### ISSUE TITLE
WooCommerce: Dashboard page always displays Store Location Step

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#15632]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/SITEURL
2. See that Store Location step is present, even if you've already set up your store
3. Fill it out and click Let's go! button
4. Go to any other page
5. Go back to Dashboard page and see that Store Location Step is there instead of Egg/Fleg/Mamma dashboard

#### What I expected

After Store Location step is filled out, it should display the one of the Dashboards.

#### What happened instead

Store Location displays instead.

**Comment by justinshreve** [comment]
I think this is fixed by #15651, and I don't see the behavior anymore. @kellychoffman can you confirm and close if so?

**Comment by kellychoffman** [comment]
Confirmed this is no longer happening.
