### ISSUE TITLE
Sharing: sometimes Facebook is unable to fetch post data

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#15639]
Note that this may be an issue on Facebook's side, see

* https://developers.facebook.com/bugs/1872744423048763/
* https://developers.facebook.com/bugs/1943853322556389/

Steps to reproduce:

1. Go to My Sites > Blog Posts > Add.
1. Give the post a title, add some content, add an image, set a featured image.
1. Publish the post and get the URL right away.
1. Go to https://www.facebook.com/ and log in.
1. Paste the URL from earlier into the sharing box on your Facebook timeline.
1. Check to see whether the share preview looks correct.

Example post: https://designsimply-automated-transfer-6.blog/2017/06/28/totoro-bento/

<strong>Result:</strong> some but not all of the time, sharing a link on Facebook results in just a domain listed for the title and link instead of the post title, content snippet, and featured image as expected.

<strong>Note:</strong> this happened in 1of 7 tests that I tried.

<strong>Video:</strong> <a href="https://cloudup.com/crQND2q3Kns">59s</a>

![screen shot 2017-06-28 at wed jun 28 3 04 05 pm](https://user-images.githubusercontent.com/1119271/27662983-79ff31e8-5c1d-11e7-8fa0-dc520b2ad13f.png)
<sup>Seen at https://www.facebook.com/profile.php?id=100001201815332 using Safari 10.1.1 on Mac OS X 10.12.5 after pasting https://designsimply-automated-transfer-6.blog/2017/06/28/totoro-bento/ into a new post on https://www.facebook.com</sup>

Facebook Sharing Debugger returns the following warning:

> Could Not Connect To Server
> Check that the web server is running, and that there are no firewalls blocking Facebook's crawlers.

![screen shot 2017-06-28 at wed jun 28 4 06 01 pm](https://user-images.githubusercontent.com/1119271/27662985-7cc5a6be-5c1d-11e7-9b0f-74fe78252f77.png)
<sup>Seen at https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdesignsimply-automated-transfer-6.blog%2F2017%2F06%2F28%2Ftotoro-bento%2F</sup>

Several reports about this (65+ since 18-Jun to 28-Jun) were tracked at p2EDhh-gb-p2.

**Comment by lamdayap** [comment]
Just adding a note of an effected site:

[3298420](https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3298420&highlight=--+Mixed+--&ticketsearchid=1688655#)
[https://norahcolvin.com](https://norahcolvin.com)
[FB Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fnorahcolvin.com%2F2017%2F06%2F27%2Faway-with-the-fairies%2F)

Apologies if this isn't necessary.

**Comment by codestor4** [comment]
3304591-t

pub-rc: https://mc.a8c.com/tools/reportcard/publicize/?blog_id=92397623
failed post: https://www.facebook.com/OptimusInformativo/posts/1552022771514648?sw_fnr_id=20259908&fnr_t=0

**Comment by designsimply** [comment]
@lamdayap, it's fine to report here. Thank you!

**Comment by designsimply** [comment]
Following up on the two reports from earlier. ^

3298420-t

I tested manually sharing the latest post from http://www.readilearn.com.au/ just now and it worked normally in my test ([post](http://www.readilearn.com.au/celebrating-naidoc-week/), [screenshot](https://cloudup.com/cosrJoqZr-x)).

Noting that the Publicize Event Log for that post says:

> failure_facebook | 16937563 | 2017-07-07T00:01:43+00:00 (4 days ago) | Error 403 ((#200) Feed story publishing to other users is disabled for this application)
 
Possibly related: https://stackoverflow.com/questions/14792062/posting-to-friends-wall-with-graph-api-via-feed-connection-failing-since-feb

3304591-t

I tested manually sharing two posts to a Facebook timeline and both worked as expected in my tests:

1. http://www.optimusinformativo.com/editorial/en-la-mira-mas-de-22-cuentas-publicas-de-ex-alcaldes/ ([screenshot](https://cloudup.com/cU2XqKIr3WD))
1. http://www.optimusinformativo.com/riobravo/entrega-apoyos-madres-adolescentes/ ([screenshot](https://cloudup.com/cPHxmQr2iyo))

I also noticed that recent posts at https://www.facebook.com/pg/OptimusInformativo/posts/ look normal. See [screenshot](https://cloudup.com/cxmcqon3oTJ).

**Comment by designsimply** [comment]
Closing this because Facebook replied on the related issue on their end at https://developers.facebook.com/bugs/1943853322556389/?comment_id=1957759174499137 on 25-July to say:

> This should now be resolved. Thanks for flagging this, and thanks for your patience while we addressed the issue.

And I haven't seen any new reports of the exact same issue come in since then.

**Comment by rfaile313** [comment]
This is still an issue. User having same problem reported in 6194142-hc -- same thing on the ticket hold in 1390465-z
