### ISSUE TITLE
WooCommerce: ProductVariationTypesForm key error

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#15645]
The following error is seen upon the editing of an existing product:

`warning.js:36 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ProductVariationTypesForm`. See https://fb.me/react-warning-keys for more information.
    in div (created by ProductVariationTypesForm)
    in ProductVariationTypesForm (created by ProductFormVariationsCard)
    in div (created by ProductFormVariationsCard)
    in div (created by FoldableCard)
    in div (created by Card)
    in Card (created by FoldableCard)
    in FoldableCard (created by ProductFormVariationsCard)
    in ProductFormVariationsCard (created by Localized(ProductFormVariationsCard))
    in Localized(ProductFormVariationsCard) (created by ProductForm)
    in div (created by ProductForm)
    in ProductForm (created by ProductUpdate)
    in main (created by Main)
    in Main (created by ProductUpdate)
    in ProductUpdate (created by Localized(ProductUpdate))
    in Localized(ProductUpdate) (created by Connect(Localized(ProductUpdate)))
    in Connect(Localized(ProductUpdate))
    in Provider`

To Replicate:

1. Visit store-enabled site.
2. Go to Products List
3. Select a product, it will bring up the edit page.
4. Inspect JS console and see error.

I think this has to do with a manufactured uid that is given to attributes/variation types upon creation. But these don't exist for a product received via the API.

**Comment by kellychoffman** [comment]
I don't see this happening in production. Closing.

**Comment by coderkevin** [comment]
It doesn't happen in production because warnings are turned off. Still needs to be fixed though.
