### ISSUE TITLE
i18n: App store badges are not translated.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#15642]
On `/me/get-apps`, we use the proper badges for both the App Store and Google Play. These are images in English, so we currently show the English version to users that have their interface in other languages.

Both of these guidelines docs have instructions for generating badges in other languages:
 * App Store guidelines: https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore
 * Google Play: https://play.google.com/intl/en_us/badges/

![screen shot 2017-06-28 at 4 20 09 pm](https://user-images.githubusercontent.com/349751/27664677-bc848e46-5c1d-11e7-920f-8b664fa866d6.png)

**Comment by gwwar** [comment]
Nice catch @kwight !

**Comment by ramonjd** [comment]
What's the preference here? To download and store? Or to link to a hosted file?

I can access most of Google's [app store images](https://play.google.com/intl/en_us/badges/images/generic/zh-tw_badge_web_generic.png) like this:

`http://play.google.com/intl/en_us/badges/images/generic/${item.langSlug}_badge_web_generic.png`

I ran a script using this url against WordPress.com's supported languages and got only 67 images of a possible 138 languages, though I didn't take into account variants such as `fr_CA`.

Apple's images are only available to download as a huge zip of esp/svgs with 41 variants.

Probably serving them from Calypso might be safer, so we can deliver the appropriate fallback/default images.

**Comment by akirk** [comment]
Great, I'd go for simply constructing Google's URLs like you showed.

It's quite interesting that Apple doesn't provide those images for hotlinking. So, for the App Store I'd suggest to convert and host them somewhere like s1.wp.com. Someone more familiar with Apple's TOS should probably be able to say if this is ok and standard practise. @astralbodies maybe?

**Comment by astralbodies** [comment]
An equivalent URL for Apple is: 

```<a href="https://itunes.apple.com/us/app/wordpress/id335703880?mt=8" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/assets/shared/badges/en-us/appstore-lrg.svg) no-repeat;width:135px;height:40px;background-size:contain;"></a>```

**Comment by akirk** [comment]
So respectively links like https://linkmaker.itunes.apple.com/assets/shared/badges/de-de/appstore-lrg.svg

**Comment by ramonjd** [comment]
#21028 merged
