### ISSUE TITLE
WooCommerce: Description not visible when editing existing product.

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#15646]
When editing an existing product, the description is not pre-loaded with the API data.

I've looked into this and found that a `componentWillReceiveProps` method needs to be added to the component, but when I just set the content of the editor, some strange behavior ensues (delayed edits, undoing recent edits, it's exacerbated by rapid edits back-to-back).

**Comment by justinshreve** [comment]
I wonder if the best way to fix this (for now) is to not load the TinyMCE component until the post data has properly loaded in.

Right now `value` is only used to set the initial contents. I'm guessing setting it from `componentWillReceiveProps` is probably kicking off the content change handler, which then updates the prop, which then sets the content, and so on, causing a loop.
