### ISSUE TITLE
Editor: Submit for Review/Update Button without calendar looks cut-off

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#15644]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post (as a _contributor_)
2. Enter some content
3. Note button visual appearance
4. Click submit for review - note Update button visual appearance

#### What I expected

Nice rounded buttons

#### What happened instead

Buttons look cut off

#### Browser / OS version

Chrome 58.0.3029.110  macOS 10.12.15

#### Screenshot / Video

<img width="446" alt="screen shot 2017-06-29 at 2 56 29 pm" src="https://user-images.githubusercontent.com/128826/27672039-94cb211c-5cdb-11e7-842a-c8498ba341b6.png">
<img width="355" alt="screen shot 2017-06-29 at 3 00 23 pm" src="https://user-images.githubusercontent.com/128826/27672062-b31f3e64-5cdb-11e7-9ab9-674ad7a92f05.png">

**Comment by mattsherman** [comment]
We will look into this.
