### ISSUE TITLE
WooCommerce: Product publish UX

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15648]
Couple of tweaks we can do to improve this.

The very first time a user publishes a product we should probably redirect them back to the dashboard so they can continue with the store setup process. Can we check that that's where they came from and only redirect if so? Hopefully we can still display the success message there.

Speaking of the success message, let's add two links to it;

* View product
* Add another product

**Comment by kellychoffman** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/16626.
