### ISSUE TITLE
Jetpack premium setup: Sends redundant requests

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#15653]
#### Steps to reproduce
1. Start with a Jetpack connected site on the Free plan
1. Go to `https://wordpress.com/checkout/JETPACK_SITE/premium` for your site
1. Complete checkout
1. You should land at a thank you page. Click the "Set up your plan" button (open network devtools first!)
   ![setup](https://user-images.githubusercontent.com/841763/27686447-1158a668-5cd3-11e7-83c7-4dd8d2625ce5.png)
1. VaultPress install/configure seems to send repeated redundant requests. I've seen this happen for `install`, `update` and `option` requests. It also tends to report failure (but succeed) on the first attempt, although that's not the issue I'm reporting.

I've noticed that the setup process does not end until all of these reuqests have resolved, which can cause significant delay.

#### Screenshot / Video

![vp2](https://user-images.githubusercontent.com/841763/27686971-576b8574-5cd5-11e7-9658-23cc8ca046ad.gif)

#### Context / Source

I observed this while working on 518-gh-jpop-issues

**Comment by beaulebens** [comment]
I'm not seeing remotely as many requests as in this gif, but I do see 4 requests that seem the same. So maybe this has improved with the switch to the new design/UI on this step, but doesn't appear to be completely eliminated yet.
