### ISSUE TITLE
Jetpack connect: Connect from site banner fails

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#15666]
When connecting a new Jetpack user to a site via wp-admin banner, connection fails or ends in incoherent state.

### To reproduce
1. You must have a connected Jetpack site.
1. Add and invite a new user to the site via wp-admin.
1. Accept invite and log in the site with this new user. Do not log in using WordPress.com credentials.
1. Ensure you are logged in to WordPress.com with a different user who is _not_ currently connected to the site.
1. Visit the Jetpack Dashboard, you should see a banner nudging you to link. Click "Link to WordPress.com".
   ![link banner](https://user-images.githubusercontent.com/841763/27697351-430d5a98-5cf4-11e7-998b-c77108d1ccea.png)
1. There seem to be two unsatisfactory outcomes.

### What I expected

Follow a Jetpack connection flow and be returned to a site dashboard, either in Calypso or wp-admin.

### What happened

There were two outcomes.

#### Initial attempt

Here, we're immediately presented with a "Return to site" button. Click it and we return to the site without connecting. Note this gif loops, but there are _two_ attempts here. You can see in the second attempt that "Approve" appears.

![bad-connect](https://user-images.githubusercontent.com/841763/27697452-97102e54-5cf4-11e7-8c99-83419fae9df8.gif)

It seems that some of the state may not be loaded which is causing a "Return to site" button to be shown rather than the desired "Approve" button. 

#### Subsequent attempts

If you do see "Approve" and click it, the site is connected. However the return to a connect form with a "Finishing set up…" notification. What to do, there's not obvious way ouy?

![approve-connect](https://user-images.githubusercontent.com/841763/27697726-5d7664f0-5cf5-11e7-827f-b7fd25b5b3b4.gif)

Back at the site, you _are_ connected at this point.

### Observations

There appear to be two main issues.

1. The user is shown a button to return without connecting.
1. If they wait and see the "Approve" button, the user is connected but arrives at a dead end.

Reported by @keoshi here: p1498748549590798-slack-jpop-design

**Comment by sirreal** [comment]
When I created this issue I was able to reproduce consistently. Later I attempted to reproduce again with a different site and was unable.

**Comment by zinigor** [comment]
cc @roccotripaldi who's working on the problem. I'm going to close the Jetpack issue, because it's not a Jetpack issue. Thanks!
