### ISSUE TITLE
WooCommerce Orders: Completing payment

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#15674]
Store owner should be able to mark payments as complete

- UI to update order status
- Action to save updated order

**Comment by kellychoffman** [comment]
@jameskoster and I were discussing that the only changeable status should be Payment pending. Every other status will just list the current status. (For example, fulfilling an order would auto change the status to fulfilled)

This design also puts the Save button in the header to be consistent with other screens. This is in place of add order, which we won't be supporting in v1. 

<img width="835" alt="screen shot 2017-07-03 at 10 52 52 am" src="https://user-images.githubusercontent.com/5835847/27801922-e97253ac-5fdd-11e7-801b-2551c9b451ac.png">
<img width="829" alt="screen shot 2017-07-03 at 10 53 02 am" src="https://user-images.githubusercontent.com/5835847/27801921-e96fb8ae-5fdd-11e7-83c5-d758755e86de.png">

**Comment by ryelle** [comment]
This task is finished with #15849 & #16044
