### ISSUE TITLE
2FA mobile push not working when we switch to another screen

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#15682]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/log-in
2. Log in with a 2FA account with push enabled.
3. You should be receiving a notification on your mobile phone. Do not validate yet.
4. Click on `Or continue to your account using: Code via text message` or `Your Authenticator app`.
5. Approve access from your phone
6. Notice that you are not logged in

#### What I expected
To be logged in and redirected to https://wpcalypso.wordpress.com

#### What happened instead
Nothing happened

#### Browser / OS version
All Browsers / OS

**Comment by fabianapsimoes** [comment]
I can't reproduce this anymore. When I approve the push notification after switching screens, I'm logged in and redirected to the reader.
