### ISSUE TITLE
Masterbar: Write button not in center (small screens)

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#15689]
Write button is not centered. As you can see in the screenshot bellow, the red arrow being the center.

The notifications icon is taking up less space than the other tabs for some reason.

The notifications tab is wrapped in a div with no class. Adding `flex: 1 1 auto` to that div seems to fix the problem.

I think when the div wrapper was added, the issue starting happening.

![screen shot 2017-06-29 at 1 45 19 pm](https://user-images.githubusercontent.com/618551/27704867-9d710214-5cd1-11e7-9582-76a5d5d242a6.png)

![screen shot 2017-06-29 at 1 55 15 pm](https://user-images.githubusercontent.com/618551/27705162-b8e194b8-5cd2-11e7-934e-6256b664caad.png)

cc @Automattic/lannister 

this might have been caused from our recent changes

**Comment by kwight** [comment]
I imagine this was introduced in #12653, where the iframe got removed; it's at this point where [adding the wrapping div](https://github.com/Automattic/wp-calypso/pull/12653/files#diff-7509901fc789a4555cb0f3b5bc0650caR125) means not having the `masterbar__item` class anymore (which is responsible for the `flex: 1 1 auto` on the other masterbar items).

It seems like the proper fix would be removing that outer `div`, bringing the notifs masterbar item more in line with the others CSS-wise. However, that `div`, while not needed any more for layout, is being used for the internal post linking, and also serves the React need of a single top element in `render()` methods. Rearranging markup to deal with those two needs after removing the outer `div` feels like more of a renovation than we might want to do at this point.
