### ISSUE TITLE
Editor: Sharing: custom message counter is wrong

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1568]
Steps to reproduce:
1. Go to https://wordpress.com/post
2. Open the Sharing box in the sidebar and connect Twitter if it is not already connected
3. Check the custom message counter

<strong>Result:</strong> the custom message counter says "94 characters remaining" even though no text has been added to either the post or the custom publicize message.

![screen shot 2015-12-14 at 15 07 22](https://cloud.githubusercontent.com/assets/1119271/11792589/d64c89c8-a274-11e5-9c70-b954f4805c2d.png)

Note from @codebykat 

> Right now it always deducts 23 characters for an attached image. We should only do this if we're actually sending an image.

**Comment by rachelmcr** [comment]
Confirmed that this issue still exists. There is another issue Automattic/wp-calypso#19630 open to increase the character count to 280 chars, but this will still have to be addressed.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by worldomonation** [comment]
Hi! I'm triaging some older bugs on file as part of Quality Squad's efforts to cut down on issues.

Is this still a relevant issue? It seems the Twitter share feature now opens Twitter in a new tab, so this UI is no longer present.

Would it be acceptable to close this issue with `Closed - Won't Fix`?
