### ISSUE TITLE
Editor: normalize tag keys

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1569]
Raised by @timmyc 

There is a discrepancy in how tag data is returned from the api, versus what is `set` by the editor to persist via the api.  When updating a post object we send along an array of tags to save ( i.e. `['foo','bar']`, and in turn the api returns an object ( i.e. `{ 'foo': {...}, 'bar': {...}}` )

Categories also has the same scenario and in the `post-edit-store` we normalize the returned object into `post.category_ids`.  This task is to explore doing a similar approach with tag names by creating something like `post.tag_keys` which would be a simple array of selected tags.

/cc @nylen @aduth for further input

**Comment by timmyc** [comment]
Now that we have standardized on using the `terms` object in the editor, I am going to close this issue out.
