### ISSUE TITLE
Login: new login page shows masterbar items if user already logged in

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#15698]
I'm not sure if this is by design so please just close this issue if so.

I noticed if you're already logged in to WordPress.com and you visit the new /log-in page the masterbar shows you are already logged in:

<img width="945" alt="screen shot 2017-06-30 at 11 10 44 am" src="https://user-images.githubusercontent.com/128826/27716893-ced90e1a-5d84-11e7-8824-4012ee844c17.png">

This is different to the current behaviour of /wp-login.php which doesn't show you as logged in, or the links the Reader or Post etc:

<img width="956" alt="screen shot 2017-06-30 at 11 11 32 am" src="https://user-images.githubusercontent.com/128826/27716916-f5963e9c-5d84-11e7-9cdd-996afc91b1ab.png">

**Comment by fabianapsimoes** [comment]
Thoughts @danhauk?

**Comment by fabianapsimoes** [comment]
Actually, this is by design. See: https://github.com/Automattic/wp-calypso/issues/14163
