### ISSUE TITLE
Themes: when in multisite view change action label "Purchase" to "Activate" when a site already has the theme

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#157]
Steps to reproduce:
1. Purchase a theme on a site
2. Go to the All Sites view and find the same theme that was just purchased
3. Click on the three dots for this theme and see the 'Purchase' option (as expected):
   ![all-sites-purchase-mood](https://cloud.githubusercontent.com/assets/11487924/8836278/e4d48d96-308d-11e5-8cd1-a2cdd3961036.png)
4. Click on ‘Purchase’, and see this (in this case Owl City News is the site with the theme already purchased):

![all-sites-purchase-modal](https://cloud.githubusercontent.com/assets/11487924/8836287/f116f58a-308d-11e5-84c5-e699ed4f4786.png)

For sites for which the theme has already been purchased, change the label here to "Activate on" screen instead of the "Purchase on" screen. It might looks something like this:

![activate-on-for-blogs-with-theme](https://cloud.githubusercontent.com/assets/11487924/8836388/87acdd2a-308e-11e5-868c-e10cab4b3fdc.png)

**Comment by folletto** [comment]
![theme-sitepicker-modal-purchase](https://cloud.githubusercontent.com/assets/4389/22659026/16690422-ec94-11e6-98a0-57a9d8616f25.png)

Here's an updated mock. 

Note: I added a "Owned" badge near the site to have it at a quick glance, but I don't consider the badge as MVP: I'd first pull in the button/label changes on site switch, and then add the badge for quick scanning.
