### ISSUE TITLE
Media library: delete button still active when disabled

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#15706]
The media library delete button (the red trash can icon) is still active even though it shows as disabled. 

<img width="342" alt="loading" src="https://user-images.githubusercontent.com/1277682/27482093-e21352e6-5817-11e7-8696-e53902b97950.png">

#### Steps to reproduce
1. Open media library modal
2. Drop a large file onto the modal
3. A placeholder is created while the file uploads. Notice the trash can icon is disabled
4. Click the trashcan icon - it deletes the uploading photo!

#### What I expected

The trashcan icon should be disabled when it shows as disabled.

**Comment by unDemian** [comment]
@johngodley we have a fix for this https://github.com/Automattic/wp-calypso/pull/16286 which looks good to me, if you find time for a quick look and thumbs up I'll merge and deploy it.

**Comment by johngodley** [comment]
LGTM also 👍
