### ISSUE TITLE
Dialogs should scroll when required

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15708]
Currently when using the `Dialog` component, if it's content is larger than the browser window height it remains fixed in position and un-scrollable. It's impossible to view the entire content.

Here's an example;

![example](https://cldup.com/LzGeuAkMRk.gif)

The dialog itself should scroll independently in this scenario.

Additionally, the `color` declaration on `.dialog__content` can be troublesome as it overrides all inherited color declarations of the components within. Wondering if it's necessary?

**Comment by drw158** [comment]
The color declaration was probably in the beginning when we just had text in dialogs, and we weren't thinking about components. It should probably be removed.
