### ISSUE TITLE
Login: No SMS error

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#15709]
When requesting more than one SMS per minute from /log-in, I should see an `sms_code_throttled` error. Instead I see nothing, even though I get this error from the API.

**Comment by stephanethomas** [comment]
This issue should be fixed once https://github.com/Automattic/wp-calypso/pull/15712 is merged.

**Comment by fabianapsimoes** [comment]
Fixed with https://github.com/Automattic/wp-calypso/pull/15712
