### ISSUE TITLE
Editor: converting pasted text into bullets doesn't work as expected

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1571]
Steps to reproduce:
1. Write out several paragraphs of text in a plain text editor and copy them to the clipboard
2. Start a new post at https://wordpress.com/post
3. Paste in the text copied in step 1
4. Try to select just a few of the paragraphs and turn them into a bulleted lists

<strong>Result:</strong> the entire block of pasted text is turned into a single bullet instead of making the selected paragraphs into a separate bullet list. ([42s](https://cloudup.com/c7jTJ7VUvqC))

![screen shot 2015-12-14 at 16 37 54](https://cloud.githubusercontent.com/assets/1119271/11794819/42577630-a281-11e5-8f79-ff79516b1255.png)

/hat tip @gibrown for the original report

> I often at least partially write a post in a text editor, or am copying bullet points from a text editor. Usually something that start a line with '- ' or '\* '.
> 
> It would be nice to select multiple lines and have them easily turned into bullets. Or even better to have this sort of "markdown" immediately converted to bullets (I guess with an undo if the user didn't want it).

**Comment by lancewillett** [comment]
Closing this as low priority and because the new Gutenberg editor will work better to address issues like this when pasting in formatted information — plus making it much easier to switch to/from list and other formats with the click of a button.
