### ISSUE TITLE
Editor: Media: support custom media sizes defined by site specific code

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1574]
Raised by @jkudish 

The Editor should support custom media sizes defined by sites (via `add_image_size`)

Before we can add custom thumbnail sizes in the Calypso editor, support for providing this information will need to be added to the REST API. (478-gh-io)

**Comment by designsimply** [comment]
Tested and confirmed that the Calypso Editor still does not support custom media sizes using the following steps:

1. Go to wp-admin > Settings > Media.
1. Update "Thumbnail size" to 50 x 50.
1. Go to Posts > Add New, select an image, change the size to Thumbnail in the Attachment Display Settings, and click "Insert into post."
1. Go to My Sites > Add and select (+) Add > Media in the editor toolbar.
1. Select and insert an image, click the image, and click the "-" button in the image toolbar until the image can no longer get any smaller.

<strong>Result:</strong> the image inserted using the wp-admin editor respects the custom media thumbnail size set in step 2 while the image inserted using the Calypso editor does not.

<img width="1280" alt="screen shot 2017-12-21 at thu dec 21 2 58 02 pm" src="https://user-images.githubusercontent.com/1119271/34276666-9da40ee4-e65f-11e7-8075-1aeb6c5052c5.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11665 using Firefox 57.0.1 on macOS 10.13.2.</sup>

<img width="1280" alt="screen shot 2017-12-21 at thu dec 21 2 57 49 pm" src="https://user-images.githubusercontent.com/1119271/34276668-9dbe8f80-e65f-11e7-8e9a-22afca4daec0.png">
<sup>Seen at https://design5279.wordpress.com/wp-admin/post-new.php using Firefox 57.0.1 on macOS 10.13.2.</sup>

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated,](https://github.com/Automattic/wp-calypso/milestone/309?closed=1) I don't think this issue is relevant any longer, but please feel free to re-open it if that's incorrect.
