### ISSUE TITLE
WooCommerce Stats: Switched pill doesn't always appear on main stats

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#15746]
#### Steps to reproduce
1. Starting at URL: /stats/day/{site_id}
2. Look to see switch to store stats (when enabled)
3. Find no link
4.

#### What I expected
Link to store stats on the main stats page

#### What happened instead
No Link

#### Why

My site has two copies of WooCommerce installed 2.6.14 and 3.0.x because I have been switching between the two for testing.

Calypso isn't convinced I have it active even if I do, this also shows up in other areas like the plugins view where you only see one version (and it isn't clear which because version numbers are not displayed).

**Comment by greenafrican** [comment]
Fixed in #15748
