### ISSUE TITLE
Facebook embed: Embed exceeds width of pages and posts on mobile view.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#15769]
#### Steps to reproduce
1. Start at URL: https://en.support.wordpress.com/facebook-integration/facebook-embeds/ or any page or post with an embedded Facebook post.
2. Open the page or a similar post on a mobile device or via your browser's mobile view

#### What I expected
The embed would be resized to fit within the constraints of the content area for a post or page.

#### What happened instead
The embed overflows off the edge of the screen, exceeding the content area boundary for posts and pages.

Interestingly, Twenty Ten displays the sharing embed as you'd expect, without any content overflowing. However, that appears to be the exception rather than the rule. Perhaps that's due to the right-hand sidebar widget area?

#### Browser / OS version
Debian Stretch, Chrome, Version 61.0.3141.7 (Official Build) dev (64-bit)

Nexus 5x, Android N, Firefox Nightly

#### Screenshot / Video

![selection_015](https://user-images.githubusercontent.com/10121835/27779942-855072e8-5f8b-11e7-8a95-838985251d82.png)

#### Context / Source

#user-report
Ticket 3223297-t

#manual-testing
Free themes Trac 4703-wpcom-themes

**Comment by rachelmcr** [comment]
Thanks for the report! We currently use the theme's `content_width` to determine the Facebook embed width, and it looks like that doesn't work responsively.

This isn't actually a Calypso issue (since Calypso doesn't control front-of-site issues) so I've moved this to an internal report at 7926-wpcom.
