### ISSUE TITLE
Alert the merchant when there are shipping zones without locations configured

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#15772]
A shipping zone with no locations is considered to be `Anywhere`, i.e worldwide. So, for example, if you add a zone with `postcode` filter like this: `US, ZIP 12345, Free Shipping`, then it will be saved with `Order = 1` (at the start of the list, because the `postcode` filter is the most specific), and **then** the locations will be saved. If an error happens while saving the locations, you'll basically be offering Free Shipping worldwide.

Since saving a shipping zone isn't an atomic operation (we need at least 1 step to save it and another to save the locations), there's no way to completely prevent this, but at least we should try to mitigate it in the UI.

I've added some logic in #15771 to mitigate it: If there's a zone without locations and the user saves the changes on *any* zone, the bogus zone will be pushed to the bottom of the list. But that's not ideal, since it requires that the user goes back to Calypso and saves his changes, and also it doesn't solve the main problem: the merchant would be offering Free Shipping (or whatever it's configured) for the whole world (except on the locations covered by the rest of the list).

We should at least put a big fat warning sign on the zones that have no locations (that can only happen after an error saving), and maybe put some kind of permanent notice all over the WooCommerce dashboard.

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
