### ISSUE TITLE
Stats: hits on Blog Stats widget not translating

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#15783]
#### Steps to reproduce
1. Add the Blog Stats widget on a site with more than a thousand views
2. Change the site's language to "Português do Brasil"
3. Check the Blog Stats widget on the site

#### What I expected
Thousands-separator to be a period, as it is in Portuguese.

#### What happened instead
The separator is a comma, which is the original string without translation.

#### Screenshot
![screen shot 2017-07-03 at 08 19 32](https://user-images.githubusercontent.com/16104522/27790772-60f7438a-5fc8-11e7-8baa-7a5ff52955bd.png)

#### Context / Source
User asked on ticket 3301000.

Similar issue: https://github.com/Automattic/wp-calypso/issues/10682

**Comment by gziolo** [comment]
Can you provide a screenshot with a more context?

**Comment by jeherve** [comment]
I believe that's not a Calypso issue. It refers to the widget display on the site.

This issue should probably be reported on wpcom.trac instead.

**Comment by carinapilar** [comment]
Created the wpcom.com.trac here: https://core.trac.wordpress.org/ticket/41967#ticket

**Comment by jeherve** [comment]
@carinapilar You will want to create this bug report on wpcom.trac, since it is about a WordPress.com widget. The bug tracker you used above is for WordPress.org.

This should help you: PCYsg-Kv-p2

**Comment by carinapilar** [comment]
I hope I got this right now: https://wpcom.trac.automattic.com/ticket/7941#ticket. Thanks @jeherve!
