### ISSUE TITLE
Comments: commenter URL should be linked

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#15807]
![screen shot 2017-07-03 at 5 04 25 pm](https://user-images.githubusercontent.com/618551/27809009-b88b0caa-6011-11e7-85ad-5d777d672198.png)

While we're at it, the timestamp should probably link to the front end comment of the site

**Comment by Copons** [comment]
Will tackle this after https://github.com/Automattic/wp-calypso/pull/15824 merges to avoid unnecessary rebases.
