### ISSUE TITLE
Editor: excerpt help text makes it seem like they apply to all themes when they don't

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1580]
Raised by @thatrobyn 

Descriptor of the excerpt function insinuates that it should work for all users, rather than on a by-theme basis.

```
Excerpts are optional hand-crafted summaries of your content.
```

![screen shot 2015-12-14 at mon dec 14 7 55 54 pm](https://cloud.githubusercontent.com/assets/1119271/11798867/ea2987c0-a29c-11e5-8ed2-81440cce10c9.png)

When I tried to add an excerpt, it didn't display on my blog page (theme: Balloons). This could be an annoyance to users.

Notes from @codebykat 

> Here's wp-admin, for comparison:
> 
> ![screen shot 2015-08-26 at 5 17 46 pm](https://cloud.githubusercontent.com/assets/52152/9509600/6b31452a-4c16-11e5-925f-dddbd299a56d.png)
> 
> Link goes to https://codex.wordpress.org/Excerpt

**Comment by designsimply** [comment]
Tested and verified that the current tooltip is still there:

<blockquote>Excerpts are optional hand-crafted summaries of your content.</blockquote>

Suggested change:

<blockquote>Excerpts are optional hand-crafted summaries of your content used by themes in different ways.</blockquote>

Feedback welcome for the wording change.

**Comment by andfinally** [comment]
Hi @designsimply, I've created PR https://github.com/Automattic/wp-calypso/pull/22973 for this. I kind of like the `wp-admin` wording, so I've gone with 

> Excerpts are optional hand-crafted summaries of your content that can be used in your theme.

See what you think! 🙂

**Comment by andfinally** [comment]
Hi @designsimply, we've merged https://github.com/Automattic/wp-calypso/pull/22973 with Ben Huberman's wording

>An excerpt is a short summary you can add to your posts. Some themes show excerpts alongside post titles on your site's homepage and archive pages.

Are you happy for us to close this issue and the duplicate issue https://github.com/Automattic/wp-calypso/issues/22677?

**Comment by andfinally** [comment]
I'm assuming it's safe to close this one.
