### ISSUE TITLE
Editor: Long post titles are not handled well when inserting a link

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#15809]
When attempting to insert a link in the editor, you are presented with a list of recent posts which allows you to quickly link to them. If they have long titles, then the title wraps poorly.

#### Steps to reproduce
1. Start at wordpress.com
2. Create a new post with a really long title
3. Create another post, and click the toolbar in the editor to insert a link
4. Observe the previous post in the list of posts, with its title wrapping to another line (the effect is much worse when you have many posts with long titles)

#### What I expected
The titles should either be truncated, or wrap and push down the next post in the list.

#### What happened instead
The title wrapped, but overlapped with the next post in the list.

#### Browser / OS version
Chrome/macOS.

#### Screenshot / Video
<img width="373" alt="screen shot 2017-07-02 at 12 53 50 pm" src="https://user-images.githubusercontent.com/108942/27810541-d453e162-6018-11e7-8e7f-32058fe17b78.png">

#### Context / Source
#reallife #dogfooding

**Comment by jahvi** [comment]
I was going to give this one a go but I haven't been able to reproduce, it looks fine on Chrome 59 / MacOS.

<img width="360" alt="screen shot 2017-07-04 at 11 46 04" src="https://user-images.githubusercontent.com/661330/27827290-7d0a855a-60ae-11e7-8daa-2b1b84b1d656.png">

**Comment by beaulebens** [comment]
Weird, I'm also on Chrome 59, and still seeing it.

In case it helps reproduce, the post titles I have which are overlapping are:

"Dented Reality on New Dedicated Virtual at Media Temple"
"Import posts from Jetpack/WordPress.com"
"Dabbling in Home Automation and The Internet of Things"

**Comment by jahvi** [comment]
Weird, have you checked on the latest master branch? It looks fine for me there, maybe it hasn't been deployed on WP.com yet?

**Comment by beaulebens** [comment]
Confirmed in master as well. My guess is it's some `flex-box` weirdness, but I'm not super familiar with how that works, so haven't found how to fix it yet.

**Comment by marekhrabe** [comment]
This issue should be now fixed in production. It affected Jetpack sites, not dotcom simple.

Kinda funny bug: We were caching item heights in an object and we used `post.global_ID` as a key. However, this `global_ID` was an empty string for any Jetpack (and Atomic) site post. Somebody figured out it would be a good thing to add `global_ID` for Jetpack posts too and so they did. Sadly, they only added that to an old version of the API and not to the latest one. D7504-code is my fix.
