### ISSUE TITLE
Mother Jones is full of Mystery Men

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#15800]
Is there something about Mother Jones that is messing with the gravatars? All of their posts show the mystery man, no matter the post author.

https://wordpress.com/read/feeds/67788138

![screen shot 2017-07-03 at 12 43 57 pm](https://user-images.githubusercontent.com/24388/27806073-56676c22-5fed-11e7-94a2-73a9fe5bfa47.png)

cc @blowery

**Comment by blowery** [comment]
Hmmm... Might be an effect of being a VIP. Will dig.

**Comment by blowery** [comment]
![screenshot 2017-07-05 16 54 35](https://user-images.githubusercontent.com/14350/27884507-a6dc5de6-61a2-11e7-85b5-54152398b294.png)

API thinks they have valid avatars. :/
