### ISSUE TITLE
WooCommerce: accessing /store on AT site with WC already set up to non-US or Canada gets stuck

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#15812]
#### Steps to reproduce
1. Create a new WordPress.com business site with domain
2. Install WooCommerce via Plugins page which makes the site an AT site
3. Visit wp-admin and set up WooCommerce - set location to somewhere other than US or Canada (eg. Australia)
4. Visit https://wpcalypso.wordpress.com/
5. Click Store (BETA)

#### What I expected

Not to see Store (BETA) as it isn't supported for non-US or Canada stores?

#### What happened instead

Store is shown and clicking it loads the Setting up your Store screen which just remains on that page

#### Browser / OS version

macOS Chrome

#### Screenshot / Video

<img width="769" alt="screen shot 2017-07-04 at 11 01 00 am" src="https://user-images.githubusercontent.com/128826/27815730-bcf684dc-60c9-11e7-93a7-2a12d55efe4f.png">

**Comment by belcherj** [comment]
Please retest this.  This should be fixed  @alisterscott

**Comment by justinshreve** [comment]
Regarding the address part of this: We won't be hiding the link based on WC location right now (we expect most of the initial launch to not have WooCommerce previously setup).

If they do go through the setup, they are asked to confirm/set an address to US or CA only during the setup flow once you get passed the plugin install.

**Comment by timmyc** [comment]
Closing this out as I no longer can reproduce.
