### ISSUE TITLE
Help: TypeError: Cannot read property 'ID' of null

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#15819]
From https://github.com/Automattic/wp-calypso/pull/15522#issuecomment-312697985:

![chrome_2017-07-03_18-16-31](https://user-images.githubusercontent.com/11271197/27802464-cd0024ea-601b-11e7-8658-ba5e349afe0a.png)

(This happens when landing cold at `/help/contact` when no sites have been fetched yet -- i.e. repro by clearing `IndexedDb` and hard reloading.)

cc @jorgefilipecosta -- maybe you can look into a fix?

**Comment by jorgefilipecosta** [comment]
@ockham Thank you for creating this bug report, I will try to fix this problem.

**Comment by jorgefilipecosta** [comment]
A possible fix for this problem is in PR https://github.com/Automattic/wp-calypso/pull/15845/.

**Comment by unDemian** [comment]
Temporary patch https://github.com/Automattic/wp-calypso/pull/15845 was merged we will continue the work on refactoring the component to avoid these scenarios in https://github.com/Automattic/wp-calypso/issues/15915
