### ISSUE TITLE
Editor: pressing return when editing caption adds line break to post content

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1582]
Raised by @kriskarkoski 

lPressing return while editing a caption adds a line break to the post content rather than to the caption. Note: This same issue is present in WP Admin.

Manually adding <br /> in HTML mode adds a second line to the caption that displays fine in the same way a long caption would so it seems we could support this. If we can't support adding lines by pressing return now or until core addresses the issue at least preventing the return from being applied to the post content seems preferred to the current behavior.

![return in caption adds line break](https://cloud.githubusercontent.com/assets/1900444/9477948/037c3314-4b43-11e5-912e-4c5a91aa5054.gif)

**Comment by KokkieH** [comment]
Another report of this in 751267-f

**Comment by rachelmcr** [comment]
Closing as this will be resolved in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
