### ISSUE TITLE
Themes: theme count is incorrect

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#15833]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/cool.blog
2. check the theme count 
    All
    <img width="243" alt="captura de pantalla 2017-07-04 a las 12 27 40" src="https://user-images.githubusercontent.com/1041600/27836092-5a59b1ec-60b4-11e7-85ef-e98f44fdab42.png">

    Free
    <img width="225" alt="captura de pantalla 2017-07-04 a las 12 27 51" src="https://user-images.githubusercontent.com/1041600/27836101-63121b80-60b4-11e7-901e-fc647062a6d0.png">

    Premium
    <img width="243" alt="captura de pantalla 2017-07-04 a las 12 27 57" src="https://user-images.githubusercontent.com/1041600/27836104-697787f8-60b4-11e7-901a-7e3ab692b206.png">

3. in theme filter, click Layout, select Fluid Layout
4. once filtered themes are loaded, clear filter to go back to full list
5. check count again

    All
    <img width="227" alt="captura de pantalla 2017-07-04 a las 12 28 26" src="https://user-images.githubusercontent.com/1041600/27836143-8f5f0392-60b4-11e7-84a9-860b0d274c1a.png">

    Free
    <img width="230" alt="captura de pantalla 2017-07-04 a las 12 28 31" src="https://user-images.githubusercontent.com/1041600/27836147-936c3cca-60b4-11e7-881f-a82983e54eae.png">

    Premium
    <img width="236" alt="captura de pantalla 2017-07-04 a las 12 28 38" src="https://user-images.githubusercontent.com/1041600/27836151-96ba8440-60b4-11e7-88f1-7a56460c0039.png">

#### What I expected
Theme count to be always consistent.

#### What happened instead
Theme count randomly changes.

This is just one way that makes count incorrect. I initially found this issue while I was in a Jetpack Free plan, upgraded in Store Admin to Jetpack Professional, went to Plans tab so it refreshed, and when I went back to Themes, the count was incorrect.

#### Browser / OS version
El Capitan/Chrome

**Comment by iamgabrielma** [comment]
I've been playing a little with this and seems there's some pattern, sums +20 free themes when we click on any of the three buttons, examples:
- `No feature selected: `The total count starts at Total: 370 (152 free themes + 218 premium themes), but sums **+20** when you click on All/Free/Premium/, making a 390 total.
- `Test with feature:social-menu` I get Total: 208 (65 free + 143 premium), back to All shows 228 (sums **+20**), making this time 85 free + 143 premium.
- `Test with feature:featured-image-header `I get Total: 104 (23 free + 61 premium = 84 so is wrong), back to All shows 115 (sums **+20** again to free themes), making this time 43 free + 61 premium, the initial 104.

**Comment by rachelmcr** [comment]
I confirmed that this is still happening, with a different number of themes added to the theme count depending on the filter.

If you scroll all the way down the full list of themes (so all themes load on the page), this doesn't happen — in that case, clearing the query always returns to the expected total number of themes. This is presumably because the items returned by that query are all accounted for in the original query for all themes.

**Comment by sdixon194** [comment]
Just had a case of this in 18431524-hc

The behavior was bizarre for this user on the eCommerce plan. The numbers and actual amount of themes shown varied wildly every time I SSP'd and I had trouble consistently getting the same amount of themes to show, sometimes as low as only showing 64 + the `Recommended themes`

**Comment by lancewillett** [comment]
Closed #39898 as a duplicate

**Comment by ianstewart** [comment]
We no longer surface theme counts on WP.com. See the comment below.

https://github.com/Automattic/wp-calypso/issues/39898#issuecomment-596810675

Worth turning them back on if we can get the count right?

**Comment by sixhours** [comment]
> Worth turning them back on if we can get the count right?

What's the problem we're solving by doing that?

Is it a selling point for attracting more business? Bragging rights?

It feels like a statistic that's more important to us than to end users, but I could be wrong.

**Comment by kwight** [comment]
Theme counts can vary for people between their own sites, because of various cutoffs.
