### ISSUE TITLE
Logged out design docs view is a little broken

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#15831]
I was about to share the amazing docs and decided to test logged out to be sure they could get it. Whilst they can, it doesn't look totally right.

https://wpcalypso.wordpress.com/devdocs/design

![2017-07-04 at 16 14](https://user-images.githubusercontent.com/253067/27835736-2efe526c-60d4-11e7-86e7-b114cfaf52c6.png)

I checked if an outage issue but logged in they show up fine.

**Comment by mladenplavsic** [comment]
This got to be due to "Logged-out never has a sidebar" statement at https://github.com/Automattic/wp-calypso/blob/master/client/layout/logged-out.jsx#L24

**Comment by mladenplavsic** [comment]
@karmatosed could you please assign a reviewer to my PR, thanks!

**Comment by designsimply** [comment]
Tested and confirmed by viewing https://wpcalypso.wordpress.com/devdocs/design while logged out.

@mladenplavsic thank you for the PR! I've added the `[Status] Needs Review` label—let's see if that gets it covered first.

**Comment by ockham** [comment]
Previous fix and discussion: #14812

**Comment by vindl** [comment]
Resolved in https://github.com/Automattic/wp-calypso/pull/19065.

**Comment by vindl** [comment]
Resolved in #19065.
