### ISSUE TITLE
Login: back to WordPress.com link should be localized

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#15858]
#### Steps to reproduce
1. Starting at URL: https://he.wordpress.com (or any other localized homepage)
2. Click log in
3. Click on the "Back to WordPress.com link"

#### What I expected
To return  https://he.wordpress.com

#### What happened instead
The link took me to  https://wordpress.com

#manual-testing

**Comment by iamgabrielma** [comment]
Just tested this with https://es.wordpress.com/ and https://he.wordpress.com/ in a private browser but I've been unable to replicate it. When I click on Log In and I go back to WordPress.com via the page link, it redirects me to the correct sub domain 😕

**Comment by yoavf** [comment]
I can't reproduce either, I must have imagined that. Sorry 'bout that!
