### ISSUE TITLE
.ca (and WWD domains): show notice in whois update screen about transfer being locked after editing

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#15855]
For ICANN domains registered through Tucows, we have optional transfer lock on whois update.
For other TLDs or for legacy domains from WWD, editing whois data might cause a transfer lock. We should tell our users so.

See #15602

**Comment by klimeryk** [comment]
Related to @delputnam's work in https://github.com/Automattic/wp-calypso/pull/16338 (which was put on the side for now, since we need to focus on 🔪 get.blog).

**Comment by klimeryk** [comment]
cc @mikeshelton1503 this issue is related to the trade lock we've talked about.

**Comment by klimeryk** [comment]
This is done 👍
