### ISSUE TITLE
Error when renewal link does not contain primary domain

### ISSUE THREAD

**Issue by markryall** [Automattic/wp-calypso#15854]
Renewal links do not behave correctly unless the final part of the link contains the current primary domain.

This may cause an issue if a renewal reminder email was sent to a user but they then changed the primary domain before clicking on the link.

#### Steps to reproduce

1. Create a site with a custom domain (i'll refer to them here as testsite.wordpress.com and testdomain.com)
2. Set the custom domain (testdomain.com) as primary
3. Browse to `http://wordpress.com/checkout/domain_map:testdomain.com/renew/1/testdomain.com` and you should see no error
4. Browse to `http://wordpress.com/checkout/domain_map:testdomain.com/renew/1/testsite.wordpress.com` and you will see the error 'Cannot add more than one domain for this type of cart.'

(note that `1` in these urls is the purchase id but can be left as is since it is not actually used)

#### What I expected

It should be possible to determine the correct primary domain from any domain associated with a site.

#### What happened instead

A confusing  error is displayed: 'Cannot add more than one domain for this type of cart.'

#### Browser / OS version

This would apply equally to all browsers and OS (I tried on chrome and mac os x)

#### Context / Source

I encountered this while testing a wpcom change related to automatically adding plan renewal to the cart when an attempt is made to renew a domain registration/mapping that is included in a plan.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by klimeryk** [comment]
Marking this as wontfix - unfortunately, it's a side-effect of a bad general architectural decision that is now heavily embedded within Calypso's routing. I've double-checked how it behaves now and it seems to redirect to `https://wordpress.com/me/purchases`. Which has received a new coat of paint recently and while not the smoothest experience, the user should be two clicks away from renewing anything there.
