### ISSUE TITLE
.fr: don't show additional details screen if user is of type individual

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#15857]
Personal user details for .fr registrations are no longer required. We should hide the 2nd step unless the user fills the "Organization" field.

**Comment by klimeryk** [comment]
Looks like this has been fixed:

<img width="581" alt="Screenshot 2021-02-02 at 13 47 31" src="https://user-images.githubusercontent.com/3392497/106609199-3c1f9a00-655d-11eb-8290-ed1bfb631065.png">
