### ISSUE TITLE
WooCommerce refunds: Should I be able to refund a greater quantity of products than the original order amount

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15860]
If a customer ordered one of a product, should I be able to input a number greater than one here?

![number-input](https://cldup.com/HHnt7UxYKv-3000x3000.png)

Currently it's possible, I can't think of a use case though.

**Comment by kellychoffman** [comment]
Probably not? I think this can wait until after the initial release.

**Comment by jameskoster** [comment]
TIL a `max` attribute on an `input` doesn't actually stop you typing in a greater value.

However:

![error](https://cldup.com/61Z5vrRjrR.png)

The refund can be the same as the order total as well, right?

**Comment by ryelle** [comment]
Currently it is possible to add a greater quantity, but most likely the "greater than order total" check will block the refund.

Is this issue asking for any implementation? I can enforce a max on the input if you want? (though I agree, I would've expected the browser to respect the `max` attribute)

> The refund can be the same as the order total as well, right?

Correct, that should be the case right now.

**Comment by jameskoster** [comment]
> I can enforce a max on the input if you want?

I suppose If it's just going to throw an error it's probably not worth it.

So yeah, just the error message copy needs a tweak.
