### ISSUE TITLE
Domain Search: "Domain registration is unavailable" screen shows up after entering certain keywords.

### ISSUE THREAD

**Issue by hafizrahman** [Automattic/wp-calypso#1586]
How to replicate:

1) Go to Add Domain screen: https://wordpress.com/domains/add/
2) Enter keyword `deans`
3) The screen automatically changes to the "Domain registration is unavailable" screen.

Video of issue: https://cloudup.com/csa5G3Yhg4u

It's weird because other words do work, like `test`, but others don't, like `hafiz`.

props to @snowmads for first finding the issue and @deancroyal for testing and creating the video.

**Comment by umurkontaci** [comment]
Also happens if you try to register google.com

**Comment by hafizrahman** [comment]
Another report in p2MSmN-4kL-p2.

**Comment by klimeryk** [comment]
Closing it here, as it's a backend issue and is tracked in `p2MSmN-4kL-p2`.
