### ISSUE TITLE
Reader: Related Post not showing video thumbnail

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#15878]
Thought this has been addressed here: https://github.com/Automattic/wp-calypso/pull/12700, but this is happening probably also because we don't support this particular embed (Kickstarter)?

Example: https://calypso.live/read/blogs/15283858/posts/2111
![screenshot 2017-07-05 10 22 14](https://user-images.githubusercontent.com/4924246/27876404-d944dea2-616b-11e7-89f8-0acc10b7f98b.png)

Only a post title is shown with an empty body.

/cc @samouri

**Comment by blowery** [comment]
the linked post there is https://wordpress.com/read/blogs/15283858/posts/2205

yeah, we don't currently have a way to grab a thumb from kickstarter.
