### ISSUE TITLE
Checkout: Purchase flows break for logged out users

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#15874]
Jetpack upgrade links fail to complete flow when users are logged out of WordPress.com.

### Steps to reproduce

1. Log out of WordPress.com
1. Go to a Jetpack site admin with upgrades available
1. Click one of the `! UPGRADE` links from the Jetpack admin page (for example in Backups section)
1. You’re sent to a page like `https://jetpack.com/pricing/settings-security-premium/?cta=....`
1. Click “Secure your site”
1. After log in, the flow is lost and you don’t have a way to continue the purchase

The underlying issue is that links of the format `/checkout/:domain/:plan` does not maintain checkout information if a user is logged out.

### Context

This issue was discovered when we were testing the new login page with Jetpack functionality. It appears this issue is not a regression related to the new login.

See p1499254364441499-slack-jpop

cc/ @richardmuscat @scruffian

**Comment by scruffian** [comment]
I would start by looking here: https://github.com/Automattic/wp-calypso/blob/a261ec032d606f32a64c8a6dd2fb44f45c943c40/server/pages/index.js#L222

**Comment by richardmuscat** [comment]
@sirreal is this still being looked at?

**Comment by sirreal** [comment]
> is this still being looked at?

@richardmuscat As far as I can tell, progress here would be blocked by #14159. After that, it would be great if checkout folks could investigate this. Otherwise we can add it to [Luna Guardianship](https://github.com/Automattic/wp-calypso/projects/39).

**Comment by kwight** [comment]
I can't replicate this anymore; I successfully started an upgrade from my JP sandbox admin and completed purchase of the proper plan from the Calypso checkout. Following the various threads, either #17134 made it invalid or another fix crept in the past six months.

**Comment by sirreal** [comment]
👍 Thanks for following up on this. It was likely fixed as part of [Jetpack Connect Services](https://github.com/orgs/Automattic/projects/8) work.
