### ISSUE TITLE
Store: Product Edit, back button brings back unsaved edits

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#15888]
While the edit state is cleared correctly when moving off to another page (after clicking through the dialog), if the user hits the back button, they will see their unsaved edits once more. Note that this doesn't happen if the product is selected from the list instead of using the back button.

Steps to reproduce:

1. From the product list, click on a product.
2. The edit page will appear, make some changes, but don't click save.
3. Click somewhere else to navigate away from the page.
4. Click through the dialog to abandon your changes.
5. Click the back button.
6. Observe that your unsaved changes have returned.

**Comment by coderkevin** [comment]
I can't seem to reproduce this issue anymore. It all seems to be working correctly.

**Comment by justinshreve** [comment]
@coderkevin This doesn't seem to be happening for me either.
