### ISSUE TITLE
Pages: "Blog Posts" card padding off on small screens

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#15896]
On the list of pages for a given site (wordpress.com/pages), we use the [compact card component](https://github.com/Automattic/wp-calypso/tree/master/client/components/card) to generate the list of pages. If you have a list of pages but the front page on your site is set to display your recent posts, you'll see an extra page called "Blog Posts" that's automatically generated. The padding on small screens (<480px) is slightly off (16px compared to 24px).

This is happening because the compact card has a breakpoint [here](https://github.com/Automattic/wp-calypso/blob/master/client/components/card/style.scss#L22). However, the blog posts page [has a strict 24px left/right padding](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/pages/blog-posts-page/style.scss#L4) regardless of screen size.

We could add a breakpoint there to fix this up.

#### Steps to reproduce
1. Starting at URL: wordpress.com/pages
2. Make sure you have at least one published page on your site and the front page of your site is set to display your recent posts.

#### Screenshot / Video
<img width="480" alt="screen shot 2017-07-05 at 20 49 15" src="https://user-images.githubusercontent.com/7240478/27893527-717827ea-61c3-11e7-8719-0dc037f71c03.png">

#dogfooding

**Comment by lancewillett** [comment]
Tested and confirmed the fix with #15923 — thanks @shaunandrews for the change.

Kudos @jeremeylduvall for finding it, and for ALL your recent Calypso contributions. 🥇
