### ISSUE TITLE
Comments: Sites with no comments hang on the placeholder.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#15891]
If a sites has no comments of any kind, the `/comments` UX will hang on the placeholder:

![screen shot 2017-07-05 at 4 37 35 pm](https://user-images.githubusercontent.com/349751/27889309-4fe6889c-61a0-11e7-964b-4a9ff585e4bf.png)

`showPlaceholder` always [evaluates to `true`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-list/index.jsx#L234) for a site with no comments, since `isLoading` will always be `true`, being based on `hasSiteComments()` (which [relies](https://github.com/Automattic/wp-calypso/blob/a82dd1af35ec0b211f2918326fb05e1e7e5f558c/client/state/selectors/has-site-comments.js#L17) on `comments.items`).

A fix could be having `isLoading` checking on an empty `comments.totalCommentsCount`, meaning `totalCommentsCount` should be updated to 0 on receiving the API result. `totalCommentsCount` seem broken at this point though, as it's always empty, even with a site with comments.

cc/ @Automattic/lannister

**Comment by kwight** [comment]
We're trying to avoid tracking any actual network activity (eg. `isLoading` being tied to an active API call), instead wanting to update when the contents of our state changes. Considering this, we'll need to distinguish between a site with no comments, and a site whose comments haven't loaded yet (`totalCommentsCount`, mentioned above, is a total for _all_ sites, so it's not of any use here).

Maybe we could use a boolean property `hasComments` on each comment item? It would default to `false`, and then be updated to `true` if comments are found by `COMMENTS_RECEIVE`.

**Comment by dmsnell** [comment]
We should have this ability by checking if the state is `null` or empty (such as `[]`).

The comments state isn't designed to support this but after talking with @samouri and the work he's doing I'm thinking again about making the new endpoint to gather comment ids and trees. This should solve our issue.
