### ISSUE TITLE
WooCommerce: Tax calculations are disabled by default

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15904]
I set up a new store with a US address where sales tax is not 0%. Tax calculations were disabled by default. I'm wondering if there is a reason for this?

The only reason I can think to do this is so that there's something to do on that screen when you first visit it from the Egg dashboard. I think calculations should be enabled though. If the user doesn't have to do anything that's no problem. Technically they are still doing something as they're confirming everything is correct.

**Comment by kellychoffman** [comment]
Agree this should be enabled by default.
