### ISSUE TITLE
WooCommerce: "Let's add some variations..." text should only be visible the first time you add variations

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15907]
As the title. It's weird to edit a variable product and still see that message.

**Comment by kellychoffman** [comment]
What should this say? 

FWIW, I sort of like the messaging.

**Comment by jameskoster** [comment]
If I've already created the product but come back to edit it later, seeing the message "Let's _add_ some variations" is confusing. I've already added the variations, I did that ages ago! :)

**Comment by kellychoffman** [comment]
Iiiii see you what mean. Yep, agree we should remove this on product edit.
