### ISSUE TITLE
WooCommerce: Some language tweaks

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15903]
* https://cloudup.com/c3c9dDWZvEM - "Rest of the world" is not matching core. Should be "Locations not covered by your other zones"
* "Tax nexus" isn't user friendly language. I don't think we need this label. "Store location" is adequate.
* https://cloudup.com/cBFKEB6bPuN - Probably don't need the 'store location' label here. Same on taxes.
* https://cloudup.com/cDKih8BqGJR - Stats widget on Fledgling needs re-wording. Stats aren't going to appear on the dashboard.

**Comment by justinshreve** [comment]
Closed by #15921.
