### ISSUE TITLE
WooCommerce: Tax settings save button shouldn't be disabled

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15905]
On the tax screen the Save button is disabled when there are no changes. We should make this consistent with shipping where the save button is always active and will display a success message when clicked even if nothing changes.

**Comment by kellychoffman** [comment]
One thing to add here - the success message never goes away. Can this be consistent with other screens? For example on Orders, it only appear briefly.

**Comment by justinshreve** [comment]
> We should make this consistent with shipping where the save button is always active and will display a success message when clicked even if nothing changes.

Isn't shipping the odd one out here? On products we also disable the button until edits occur.

**Comment by kellychoffman** [comment]
> On products we also disable the button until edits occur.

This one is a bit different because its a Save & Publish.

**Comment by jameskoster** [comment]
> On products we also disable the button until edits occur.

I'm thinking we should change products as well. I agree with Kelly, save buttons shouldn't be disabled. In the editor it makes more sense because you have revisions / drafts etc. So for products we could update the button label to 'save' and have it behave the same way as shipping.

**Comment by jameskoster** [comment]
@kellychoffman 

Now that tax calculations are enabled by default, I think we might need to move this to v1.

Otherwise when you click the 'review tax settings' button on egg and there's no clear way back to the dashboard. 

This goes hand in hand with https://github.com/Automattic/wp-calypso/issues/15951

**Comment by kellychoffman** [comment]
Agree. Moved it to v1.

**Comment by justinshreve** [comment]
Fixed by #15997.
