### ISSUE TITLE
Woo-Connect Insights: Product Duplicates in top-*

### ISSUE THREAD

**Issue by greenafrican** [Automattic/wp-calypso#15910]
![image](https://user-images.githubusercontent.com/1160732/27908152-bed7b6b8-624a-11e7-874f-76999f214715.png)

Same as the API response. This is likely due to product variations being differentiated on but not included in the product names.

cc @westi

**Comment by greenafrican** [comment]
Feedback from @bluefuton here - https://github.com/Automattic/wp-calypso/pull/15867#issuecomment-313363271

**Comment by westi** [comment]
These are not product variations just products with identical names.

The default woo test data we have imported has more than one product with the same name.

There are three products called 'Woo Ninja'

The API response included extra meta-data about the products like the Product ID and Image which allow for them to be differentiated - maybe we can display a small product image thumbnail?

**Comment by greenafrican** [comment]
I'm moving this to the 'Icebox for v1' as I don't foresee any changes to the MVP.

**Comment by greenafrican** [comment]
Closing this as it is not an issue.
