### ISSUE TITLE
WooCommerce: Egg dashboard conditional language tweaks

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#15920]
Having run through a test store setup again I think we can revise the content here a little. In a lot of cases there isn't actually any 'set up' for folks to do on the tax, payments and shipping screens.

<hr />

For shipping, replace "Be ready to ship by the time your first order comes in." with:

"We've set up a shipping zone that covers [your country] and enabled the free shipping method"

Button becomes: "Review shipping settings"

We can remove the "I won't be shipping" link for now. This was originally included to account for stores that only sell digital products or services which we aren't including in v1.

<hr />

For taxes, replace "Taxes. Everyone's favorite. We made it simple." with the notice from the tax settings screen. In most cases this will be; "We'll automatically calculate and charge the correct rate of tax for you each time a customer checks out."

The button can become: "Review tax settings"

<hr />

For payments, replace "Choose how you would like your customers to pay you." with "You're ready to receive payments via PayPal. You can also enable Stripe or offline payment methods".

Button becomes: "Review payment settings"

<hr />

I suppose these can be hard-coded for v1 but we'd need to tweak when we roll out to other countries.

**Comment by kellychoffman** [comment]
I think people will still have to set up these sections. We have done some smart defaults, but that doesn't mean there's additional set up and tweaking to be done.

**Comment by jameskoster** [comment]
That's why I think we should change the buttons to "Review ..." rather than "Set up..."

I think the experience feels weird if you head to a section expecting to set something up only to learn that you don't actually need to do anything. It's misleading. I think this is most relevant for tax/payments. Shipping is most likely to involve edits, but still, it feels more like fine-tuning rather than setting up from scratch.

**Comment by jameskoster** [comment]
We spoke about this in our call today. Concluded that payments probably still requires the 'set up' tone rather than 'review', as it's possible you'll want to change the Paypal address we use as the smart default.

Review / Confirm makes sense for shipping and taxes though.

**Comment by kellychoffman** [comment]
From our chat today we decided to:
- keep 'Set up' on payments
- change to 'Review' on Shipping and Taxes.

**Comment by kellychoffman** [comment]
We decided to make the description text static instead of dynamic for v1.

**Comment by justinshreve** [comment]
#15979 was merged which should take care of this for v1. I'll update the milestone for this to 1.1 so we can have more dynamic strings in the future.

**Comment by jameskoster** [comment]
This is no longer relevant after our latest updates to the checklist design.
