### ISSUE TITLE
Comments: verify if ordering is correct. 

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#15939]
New comments seem to load on the bottom of the list. We may need a new selector, or option to reverse this order. Be careful not to regress the reader.

**Comment by kwight** [comment]
With the removal of the faker, we now have comments loading oldest-first. The Reader loads comments this way also (as apparently most sites do). We can re-implement #15978 for just Comments Management then.

**Comment by gwwar** [comment]
I would say the correct ordering for comments management should be newest to oldest.
