### ISSUE TITLE
WooCommerce Shipping: Shipping Methods and Zones buttons

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#15949]
![image](https://user-images.githubusercontent.com/6817400/27930804-f1b4c4e8-6265-11e7-91d6-ddc5dc520d44.png)

Modal buttons should be `Done` or `Add` not `Save`.

**Comment by kellychoffman** [comment]
> Modal buttons should be Done or Add not Save.

Let's go with `Add`.
