### ISSUE TITLE
Jetpack: route users to WordPress.com contact form

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#15953]
Currently if a Jetpack user encounters an error during the checkout and plan autoconfig flow they are given a link to https://jetpack.com/contact-support/ which asks them to search for their issue.

The ideal flow would be to have happychat available (which I know is coming soon) and as a fall-back can we route that button to https://wordpress.com/help

In order for that to work properly we will need routing for help requests from jetpack sites to the appropriate support queues (jetpack, jetpack paid, etc).

cc @dllh

**Comment by dllh** [comment]
Putting this in our next milestone, though realistically we won't get to it then. This'll get it on the radar as I build out future milestones, though. We should probably work on this after we finish our ticket tool migration in a few weeks.

**Comment by dllh** [comment]
Not intending to solve this issue yet, I commited an API change in r160249-wpcom that probably fixes it, alongside https://github.com/Automattic/wp-calypso/pull/16891. I'm leaving this open for now in case there turns out to be more to loop back to later, but I think it may be basically done once we push one more API change on Monday morning.

**Comment by johnHackworth** [comment]
This is also no longer an issue with the new Thank You page. I'm going to preventively close the issue

**Comment by rickybanister** [comment]
In the context of the Thank You page, this is indeed dealt with, but I would still like to consider either routing folks through the WordPress.com contact form, or embedding the WordPress.com contact form experience on Jetpack.com (like WooCommerce is currently exploring) to unlock livechat there as well. Perhaps we should leave open and rescope the issue?
