### ISSUE TITLE
Expose Jetpack comments UI

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#15968]
Currently, in Jetpack, a user can change the headline above comments. Here's what the UI looks like:

![image](https://user-images.githubusercontent.com/1123119/27940564-9f83e000-6288-11e7-8b67-c13f8b23a7c4.png)

I'm thinking it would be super nice to let our WordPress.com users do the same thing. I was working with someone at a WordPress meetup in Albuquerque tonight that was looking for it. 

@rickybanister or @tyxla, if there's already an issue or PR open for this, feel free to close.

**Comment by tyxla** [comment]
@MichaelArestad we already have that one, see a screenshot from the Comments card in the Discussion settings section in Calypso:

![](https://cldup.com/oEIj83cPMb.png)

I've also tested it and it works just fine.

Or perhaps you're talking about something else?

**Comment by MichaelArestad** [comment]
Ah! I should have clarified. This would be for dotcom sites. Currently, this is what shows up in the dotcom site Discussion settings:

![image](https://user-images.githubusercontent.com/1123119/27959304-1eb46bf0-62e4-11e7-8638-03bb4f2904ca.png)

**Comment by tyxla** [comment]
Ah, thanks for clarifying. Yup, that would be a great addition, thanks for suggesting.

**Comment by tyxla** [comment]
This would still be useful for WP.com sites.
