### ISSUE TITLE
Store: Error on Product Create (5 sec timeout)

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#15967]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/store/product/<site url>
2. Enter product name
3. Click save.
4. Button goes "busy" and eventually error appears.
5. Click on "Products" in breadcrumb bar.
6. Notice that your product actually has been created, despite the red error.

#### What I expected
Product to save successfully without error.

#### What happened instead
Got an error.

#### Browser / OS version
OSX Firefox 54.0 (64-bit)

#### Screenshot / Video
![coderkevintest_ _wordpress_com](https://user-images.githubusercontent.com/945228/27942616-e2708a02-629d-11e7-9982-eb8cddda5e1a.png)

![developer_tools_-_coderkevintest_ _wordpress_com_-_https___wpcalypso_wordpress_com_store_product_coderkevintest-automated-transfer_blog](https://user-images.githubusercontent.com/945228/27942660-3a4d1740-629e-11e7-944a-ff884870f835.png)

**Comment by coderkevin** [comment]
I tried this with Chrome and it failed (5 seconds) the first time, but succeeded the second time.

Continued attempts in Firefox failed, but after making a quick change and saving again, it worked.
Also, updated didn't seem to have the same problem.

**Comment by coderkevin** [comment]
The product save code will have a problem continuing from this state. If the product create finishes, but we get an error back from Jetpack proxy, it makes the edit state inconsistent with the server state as the product or category could have been created even though we got an error back. So the edit state would still show that the product or category had not yet been created, even though it has.

The current code needs to be updated to handle this sort of situation.

**Comment by justinshreve** [comment]
Closing this thanks to Allen's hotfix.
