### ISSUE TITLE
Store: Setup, address entry tabbing skips over state drop-down.

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#15962]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/store/coderkevintest-automated-transfer.blog
2. On first page, it asks for address. Tab through each field in order.

#### What I expected
Tabbing through each field in order.

#### What happened instead
The "state" drop-down gets skipped over.

#### Browser / OS version
OSX Firefox 54.0 (64-bit)

#### Screenshot / Video
![store-address-entry](https://user-images.githubusercontent.com/945228/27935640-f3c8956e-6271-11e7-98bb-a1ff53efdaf3.gif)

**Comment by kellychoffman** [comment]
It gets skipped over because Canada is selected and they don't have states. A first pass at fixing this would be to make US selected by default: https://github.com/Automattic/wp-calypso/issues/15898

**Comment by coderkevin** [comment]
Yeah, I just noticed that, too. Should we have a province for Canada?

**Comment by justinshreve** [comment]
We do -- toggle to US and toggle back to Canada and they load in. I'll assign this to myself in the meantime, but it will be fixed by my PR. #15952.

**Comment by justinshreve** [comment]
<img width="589" alt="screen shot 2017-07-06 at 3 45 52 pm" src="https://user-images.githubusercontent.com/689165/27935822-3a80da4e-6262-11e7-9ddd-e8127d2c1fdf.png">
