### ISSUE TITLE
WooCommerce: Variations not loading correctly without refresh

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#15961]
Steps to reproduce:

1. Create a variable product with a few variations and publish it. Wait until you are redirected back to the posts list.
2. Click your new product to go to the edit screen.
3. Scroll down, and see your variation types, but a single blank variation row.
4. Refresh, and see your variations appear.

A fetch for the variations seems to not be happening at the right time. cc @coderkevin

**Comment by coderkevin** [comment]
Hmm, we shouldn't have to fetch the variations, we should get each one back from successful API create requests and store them from those. Something to look into, thanks!
