### ISSUE TITLE
Checkout: After renewing a purchase, the payment box does not disappear

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#15973]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Select a domain mapping (also tried with domain registration).
3. Renew it.

#### What I expected
After completing the purchase, I expected to be redirected back to the purchase page.

#### What happened instead
The payment box remained (but the checkout in the sidebar disappeared and the renewal seems to have gone through).

#### Screenshot / Video
<img width="1280" alt="screen shot 2017-07-07 at 13 37 15" src="https://user-images.githubusercontent.com/3392497/27956296-6fbc805c-6319-11e7-889b-9d4aa6931d13.png">

#### Context / Source
#manual-testing

cc @scruffian

**Comment by hewsut** [comment]
I've seen this once too. I thought it was something local as I couldn't get it again.

**Comment by klimeryk** [comment]
It's probably only for manual renewals so not very _high_ priority, but it still looks very broken when it happens.

**Comment by hewsut** [comment]
I'm not so sure. I don't recall my incident in a renew context. It's been awhile but IIRC I was trying to add a plan to an existing blog.

**Comment by beaulebens** [comment]
I got this today under exactly the described steps -- got an email about a domain mapping requiring renewal. Came here to renew it. Used WP.com credits. The renewal seems to have gone through, but the page just sits there with no redirect.

No apparent errors in the console, or anything else obvious. My guess would be that we're returning something unexpected (but not an error), or we're not handling the data properly to know that it worked, and then redirect.

**Comment by rachelmcr** [comment]
This was reported again in https://github.com/Automattic/wp-calypso/issues/20440 with some additional details:

> After the purchase is complete:
> 
> - The progress bar should go away.
> - I should be redirected to a new page.
> - The URL should have an actual purchase ID rather than a placeholder.
> 
> What happened instead
> 
> - Progress bar is stuck at the end.
> - No redirect.
> - Placeholder in URL.

![image](https://user-images.githubusercontent.com/8658164/33944023-c89b40d4-e012-11e7-8fce-c0605f835ea7.png)

> My account had an expired domain, rads.blog, which I was prompted to renew through an email. I logged in using the email login link.
> 
> There were no JavaScript errors in the Safari console.

**Comment by kwight** [comment]
Following the OP's instructions, I can't replicate; will try to set up another test through an email link.

**Comment by kwight** [comment]
I've tested this now with from an email, but emails now are a prompt to do it manually, and the login link is just to `https://wordpress.com`. I'm going to consider this fixed somewhere along the way, until we have another reproducible report.
