### ISSUE TITLE
Jetpack connect: Incorrect logic (bad comma)

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#15971]
There is a bad comma used [here](https://github.com/Automattic/wp-calypso/blob/94d417f915496dbadf186502a24c4c37fc7cff6d/client/jetpack-connect/auth-logged-in-form.jsx#L208).

Thanks @stephanethomas for spotting this

cc/ @seear @tyxla @oskosk @johnHackworth

**Comment by tyxla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jetpack connect: Incorrect logic (bad comma)](https://trello.com/c/O5Xjjm0p/51-jetpack-connect-incorrect-logic-bad-comma)
