### ISSUE TITLE
Reader: section shows blur when Followed Sites is active 

### ISSUE THREAD

**Issue by dougaitken** [Automattic/wp-calypso#15983]
#### Steps to reproduce
1. Starting at URL: Reader `https://wordpress.com/` Following Stream
2. `is_automattician()` should be true
3. Click on Followed Sites
4. Notice a small blur on the bottom before the Automattic `read` section

#### What I expected

Design has clean lines

#### What happened instead

A blur shows under the Followed Sites "button". 

#### Browser / OS version

Browser: `Version 59.0.3071.115 (Official Build) (64-bit)`
OS: MacOS 10.12.5 (16F73)

#### Screenshot / Video

![blur_reader](https://user-images.githubusercontent.com/52214/27958736-5f699ce6-631c-11e7-98d6-fda831b9c9da.gif)

#### Context / Source

Found purely by fluke, just saw the blur when clicking on a8c stream.

**Comment by folletto** [comment]
It seems a byproduct of the `:after` CSS to make long text to fade out nicely:

![screen shot 2017-07-07 at 14 29 08](https://user-images.githubusercontent.com/4389/27959778-b15d226c-6320-11e7-8d26-eee81f1c3c21.png)

It might be as easy as setting `top: 1px` to `.sidebar__menu a:first-child:after` as there's a `margin-top: -1px` applied to `.sidebar-streams__team` but there might be some unintended consequences, so it needs to be tested thoroughly (mobile included).
