### ISSUE TITLE
Jetpack Plans: add happychat button next to manual install instructions link

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#15996]
Related to #15964 

Can we add a 'get live help' link in the main content area next to the 'manual instructions' link if we are unable to auto-install Akismet and VaultPress? 

We have the 'ask a question' link in the support box, which is good, but if we detect that we can't perform the autoconfig and have to show the 'manual instructions' let's add another button above:

![image](https://user-images.githubusercontent.com/437258/27966076-ebf2bf46-630b-11e7-9138-03b23c580180.png)

**Comment by johnHackworth** [comment]
@rickybanister This issue gets deprecated as soon as we have the new thank you page in production, isn't it?

**Comment by johnHackworth** [comment]
I'm closing this, because I think it's not longer valid

**Comment by rickybanister** [comment]
Yes, that's right.
