### ISSUE TITLE
User Settings: Only fetch user settings data for translator when needed

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#160]
Right now, when the user interface language is set to a language other than English, we're fetching the user settings on every page load even if the data is not needed.

This is triggered by the community translator: We're checking userSettings.settings.enable_translator to know whether we should load the translator when the page loads. We could store this in `localStorage`.

It's also not urgent (in the sense that there's no point loading the translator before there's content to translate), so another option would be to push the translator loading back until after all the core stuff is loaded, although that wouldn't actually avoid loading userSettings, just delay it.

A third option would be to move that setting into user (if appropriate) since i18n loads the user before communityTranslator.init() (in boot), and we're already using the user object for locale info.

**Comment by hoverduck** [comment]
05May16 Bug Scrub

Confirmed this is still an issue, although I'm not sure that it's dependent on being configured for a language other than English (unless I'm misunderstanding the original issue).  Regardless of my language setting I see 3 or 4 calls to /me/settings on every page load:

<img width="756" alt="screen shot 2016-05-05 at 2 18 07 pm" src="https://cloud.githubusercontent.com/assets/7233112/15052608/795d3f82-12cc-11e6-9853-60f832f5ef4e.png">

**Comment by designsimply** [comment]
#bug-scrub

Are you sure the Community Translator is to blame? I tried with it on/off and with both the user interface language and the blog settings language set to English/not-English, and user settings loaded for me on every page regardless.

Tested and confirmed using the following testing steps:

1. Go to https://wordpress.com/me/account
1. Change the Interface Language to a language other than English, check the box or the Community Translator, and click the "Save Account Settings" button
1. Click My Sites
1. Click a few other items in the left menu
1. Check to see if user settings data is loaded after loading each section

<strong>Result:</strong> user settings load separately any time you browse to a new section in My Sites.

<img width="1280" alt="screen shot 2016-08-23 at tue aug 23 11 52 57 am" src="https://cloud.githubusercontent.com/assets/1119271/17904068/0ec9610e-692b-11e6-8ec3-fcc3d367ea3b.png">
<sup>Seen at https://wordpress.com/types/jetpack-portfolio/design5279.wordpress.com using Chrome 52.0.2743.116 on Mac OS X 10.11.6</sup>

**Comment by kriskarkoski** [comment]
Tested today in both en and es with and without the Community Translator enabled and I do not see any calls to /me/settings when changing sections. 

@rachelmcr would you like to re-test this and close if you find the same?

**Comment by rachelmcr** [comment]
I tested and confirmed that in both EN and ES, with and without the translator enabled, user settings are only fetched once (first /me page load). Closing as resolved.
