### ISSUE TITLE
Store Setup Flow - Address Screen Not Appearing

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#16003]
![screen shot 2017-07-07 at 2 52 45 pm](https://user-images.githubusercontent.com/6817400/27972328-f7397a76-6323-11e7-997d-6281b3104068.png)
![screen shot 2017-07-07 at 2 54 22 pm](https://user-images.githubusercontent.com/6817400/27972433-5ca1e182-6324-11e7-8b7f-c945b42e53d2.png)
![screen shot 2017-07-07 at 2 54 53 pm](https://user-images.githubusercontent.com/6817400/27972444-690beaa8-6324-11e7-9b1d-bac572fff801.png)
![screen shot 2017-07-07 at 2 55 07 pm](https://user-images.githubusercontent.com/6817400/27972447-6c4ef3a4-6324-11e7-87f3-e462d9f59b25.png)
![screen shot 2017-07-07 at 2 55 17 pm](https://user-images.githubusercontent.com/6817400/27972448-6e3f204e-6324-11e7-8655-bc854704d26c.png)

**Comment by belcherj** [comment]
This usually occurs after installing all of the plugins using the branch in #16000 I have since had trouble reproducing.  I have uninstalled and gone through the install process many times to see if it hangs. I am going to leave open for now but think it may have been because I was hitting the API pretty hard during the dev of #16000 and it started getting flaky.

**Comment by justinshreve** [comment]
> I am going to leave open for now but think it may have been because I was hitting the API pretty hard during the dev of #16000 and it started getting flaky.

Yeah, the `rest_no_route` error makes it look like `wc-api-dev` wasn't active at the time you made it to that step. Agreed we can keep it open for now and keep an eye on it to see if it happens again.

**Comment by belcherj** [comment]
This should be resolved, not able to replicate.  Closing.
