### ISSUE TITLE
Editor: Extra line breaks stripped out after switching between Visual/HTML editors

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#16012]
Extra line breaks are being stripped out of the editor after switching between the Visual and HTML editor.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Enter some sentences under the editor's Visual tab.
3. Switch to the HTML editor and follow [these steps](https://en.support.wordpress.com/advanced-html/#extra-line-breaks) to create more than one line break between your sentences.
4. Save changes and view the post. The correct amount of line breaks should display.
5. Go back to the editor and switch between the Visual and HTML editors a few times.
6. Save changes and view the post.

#### What I expected

I expected for the line breaks I manually entered into the post to be retained. I wouldn't expect them to be removed as a result of switching between editors.

#### What happened instead

The extra line breaks were stripped out.

Possibly related: 285-beep-beep-boop

#### Browser / OS version

Chrome / macOS Sierra

#### Screenshot / Video

![linebreaks](https://user-images.githubusercontent.com/2998162/27986258-d88b42e0-63f4-11e7-8d2e-6098c284095e.gif)

#### Context / Source

Found while helping a user in 3299060-t.

#reallife #dogfooding #user-report #manual-testing

**Comment by rachelmcr** [comment]
Closing this issue as the current behavior will be superseded by Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
