### ISSUE TITLE
Comments: Layout needs improving on smaller screens.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#16011]
Under 480px, the comment count is stretched full width, and has a large amount of whitespace between it and the actions.

![screen shot 2017-07-07 at 2 24 33 pm](https://user-images.githubusercontent.com/349751/27979998-211b5b10-632f-11e7-8fdd-f84a93f36df0.png)

**Comment by Copons** [comment]
Moved to m2 because it's related to bulk actions.
