### ISSUE TITLE
Support contact form: add information for non-WPCOM users seeking support

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#16016]
#### Steps to reproduce
1. Log in as an account that doesn't own any upgrades, and which only has a Jetpack-connected site
2. Visit https://wordpress.com/help/contact
3. Submit a support ticket

#### What I expected
For the support ticket to be submitted somewhere I can get help with my site

#### What happened instead
My request posted to the WordPress.com support forums where volunteers are telling me they're unable to help me and I should go post to a different forum.

#### Context / Source

Based on feedback from forum moderators and volunteers in 852573-f and 848339-f

Self-hosted site owners post in the WordPress.com forums daily seeking help with their self-hosted WordPress sites, but the volunteers there lack the knowledge, and staff lack the access needed to help them, so they are told to post in the WordPress.org forums instead. This is frustrating for forum volunteers and for the users.

Would it be feasible to add copy to the contact form forewarning self-hosted users they're in the wrong place to get help with their site? A further enhancement could even add a selector for unpaid users needing help with our other products, Jetpack and WooCommerce as well to get them to the correct support contact forms for those products.

Could possibly be addressed along with #16015 if a prompt could be triggered upon site selection.

cc @dllh and also @notnownikki in case the docs smart search could somehow be leveraged to address this.

**Comment by Aurorum** [comment]
PR with a potential solution in #35944. :)

@kokkieh, would you mind taking a look and offering your thoughts on the proposal?

**Comment by KokkieH** [comment]
@Aurorum thanks for trying to address this. A lot has changed since I first opened this issue, though. I've left more detailed thoughts on your PR :)
