### ISSUE TITLE
Settings: Manage Connection: Allow connection owner to be modified

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#16021]
As part of #13232 in #15716 we introduced a Manage Connection page with a Site Ownership card. 

The first version, though, does not allow the connection owner to be changed. We need to be able to change the connection owner. Mockups for that can be found here: #13232.

Before implementing the UI, though, we need to have the proper API endpoint that allows connection owner to be changed.

cc @rickybanister

**Comment by rickybanister** [comment]
👍

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/jetpack/issues/5024

**Comment by tyxla** [comment]
Note: we've just merged #24876 which takes care of this, but it's under a feature flag, so it's currently not enabled on staging/production environments; we'll push it to staging together with the Jetpack plan ownership change functionality; and after a testing phase, we'll push it to production too.
