### ISSUE TITLE
Search Results: Tags go too far to right

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#16049]
In Search, in Post results, the tags can go too far to the right.

<img width="861" alt="screen shot 2017-07-10 at 10 20 38 am" src="https://user-images.githubusercontent.com/24388/28030684-a0bb5cae-6559-11e7-94ab-5d8e2dd69110.png">

https://wordpress.com/read/search?isSuggestion=1&q=goats&sort=relevance

cc @jancavan

**Comment by fraying** [comment]
Also, note that that particular series of hashtags is being interpreted as one tag: https://wordpress.com/tag/ecotravel-familytravel-ecofarm-farmstay-ecuadortravel-travel-overland-agroeco-rural-farmlife

Which is a bummer.

This is the post: https://wordpress.com/read/blogs/112483816/posts/5639

cc @gibrown

**Comment by jancavan** [comment]
Hmm, I thought I had fixed this already. It seems like in the example, it's one really long tag 👀

**Comment by gibrown** [comment]
@fraying ya that is a general problem WP which only separates tags based on commas not based on whitespace in the editor. I think it is kinda a bug in the UI for WP. wp-admin is worst case, but I think Calypso has this problem a bit too.

**Comment by bluefuton** [comment]
I've created an Editor issue: https://github.com/Automattic/wp-calypso/issues/16396
