### ISSUE TITLE
Framework: Site Selector "New" dropdown hover overflows

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#1605]
<img width="390" alt="screen shot 2015-12-15 at 15 01 50" src="https://cloud.githubusercontent.com/assets/4389/11812624/42ce71b0-a33d-11e5-909f-8cf2e4888e3f.png">

The hover state of the dropdown overflows the popup, see screenshot.

**Comment by mtias** [comment]
Fixed this yesterday together with #1588.
