### ISSUE TITLE
Reader: Post recs in full post showing broken images

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#16062]
![screenshot 2017-07-10 14 38 28](https://user-images.githubusercontent.com/4924246/28041240-7a21d842-657d-11e7-832a-e60a17a12892.png)

Full post: https://wpcalypso.wordpress.com/read/blogs/51152825/posts/25304

Link to post rec: https://wpcalypso.wordpress.com/read/blogs/62136281/posts/993

Can the second image be used as a fallback? I think it's within size restrictions.

If the post contains no other image other than the broken one, then just display text?

**Comment by fraying** [comment]
I think this was a one-off because the recommended post has a broken image.
