### ISSUE TITLE
Editor: can't change author on mobile editor (portrait narrow screen)

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#16069]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/ on a mobile width viewport (or on mobile) on a blog with 2+ authors
2. Change the author

#### What I expected

The author to change

#### What happened instead

The author doesn't change in the UI (it does change on the post when published)

#### Browser / OS version

Tested Chrome and Safari, tested iOS

#### Screenshot / Video

![switching author](https://user-images.githubusercontent.com/128826/28052467-c0015fa0-664e-11e7-8671-2afe4123187f.gif)

#### Context / Source
#reallife #dogfooding

**Comment by rachelmcr** [comment]
I tested in Safari on iPhone 6 and I no longer see an author dropdown at all to change the author in portrait mode:

![2018-01-02 17 06 50](https://user-images.githubusercontent.com/8658164/34503711-90f5032c-efdf-11e7-8585-60323ad1a1b1.png)
![2018-01-02 17 06 56](https://user-images.githubusercontent.com/8658164/34503712-915a9a20-efdf-11e7-801d-9d075ffcd7d2.png)


The dropdown shows up above the post title in landscape mode:

![2018-01-02 17 07 08](https://user-images.githubusercontent.com/8658164/34503698-841ff9cc-efdf-11e7-8814-9157b2f6f9a7.png)

**Comment by alisterscott** [comment]
Thanks @rachelmcr, this looks like a regression in that it's now not showing at all

**Comment by lancewillett** [comment]
Re-testing this with the new Gutenberg editor chrome — works much better. Author dropdown changes to the selection, and it works with a large number of authors.

<img width="1392" alt="Screen Shot 2019-08-02 at 10 33 20" src="https://user-images.githubusercontent.com/66797/62388197-87449100-b511-11e9-90f5-4361095c4dcb.png">

<img width="1392" alt="Screen Shot 2019-08-02 at 10 35 46" src="https://user-images.githubusercontent.com/66797/62388199-87449100-b511-11e9-9c40-7e6adeaf54f5.png">

<img width="219" alt="Screen Shot 2019-08-02 at 10 35 48" src="https://user-images.githubusercontent.com/66797/62388200-87dd2780-b511-11e9-9ed5-2fe3fb509ab0.png">

<img width="1392" alt="Screen Shot 2019-08-02 at 10 35 51" src="https://user-images.githubusercontent.com/66797/62388201-87dd2780-b511-11e9-93fc-cdc8066c25d5.png">

Testing with responsive view in latest Chrome and macOS.
