### ISSUE TITLE
Jetpack pricing: segmented control buttons exceed table width

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#16079]
While connecting a self-hosted site to Jetpack, I noticed some elements were poking out as seen in the attached screenshot.

#### Steps to reproduce
1. Go to WP Admin on a self-hosted site (non- English)
2. Visit the Jetpack tab to connect it to a WordPress.com account
3. Go through set up wizard
4 Get redirected to https://wordpress.com/jetpack/connect/plans/domain.com where you'll see the issue

#### What I expected

The translations to adapt to the segmented control buttons

#### What happened instead

The segmented control buttons poke out of the table because they are too long

#### Browser / OS version

Chrome

#### Screenshot / Video

<img width="1301" alt="capture_d ecran_2017-07-11_a_11_54_16" src="https://user-images.githubusercontent.com/16645645/28064546-6481cdae-6635-11e7-8b6e-9e4aea12137f.png">

cc @yoavf and @fditrapani

**Comment by kriskarkoski** [comment]
Closing due to lack of further reports
