### ISSUE TITLE
Checkout: Purchase routes lost after login

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#16073]
#### Steps to reproduce
1. Log out of WordPress.com
1. Visit `https://wordpress.com/checkout/DOMAIN/personal` where `DOMAIN` is a site on your account that can purchase a Personal upgrade.
1. You will be redirected to the login page.
1. Log in.
1. You arrive at a standard WordPress.com landing page (Reader), rather than the checkout page.

#### What I expected

To continue the checkout flow after login.

#### What happened instead

I landed on Reader

**Comment by scruffian** [comment]
Is this the same as https://github.com/Automattic/wp-calypso/issues/15874?

**Comment by sirreal** [comment]
Yes it is, thanks @scruffian
