### ISSUE TITLE
Jetpack Connect: Pre-selected plan is lost when Jetpack is not activated

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#16085]
#### Steps to reproduce
1. Pick a non-connected .org site that has Jetpack installed, but it is **not activated**.
2. Go through the `/jetpack/connect/:flow` flow, for example you can use the `personal` flow.
3. Input your site URL in the JPC form.
4. You will be presented with the activation instructions.
5. Activate Jetpack.
6. Click the "Connect" button in wp-admin to initiate connection.
7. Follow along with the connection and authorization process.
8. After auth success, you are thrown to the plans page, without a pre-selected plan.

#### What I expected
To have the Jetpack Personal plan pre-selected, and therefore continue to the checkout process.

#### What happened instead
I was presented with the plans selection page

#### Context / Source
Found while testing the new calypso login form #manual-testing

**Comment by tyxla** [comment]
Related: #16084

**Comment by johnHackworth** [comment]
hmmm, I can't reproduce this, it works fine for me:

![jul 14 2017 2-38 pm](https://user-images.githubusercontent.com/1554855/28212617-84101710-68a2-11e7-9d61-1303f5840d4e.gif)

https://cloudup.com/c24BvUIkbvh

**Comment by tyxla** [comment]
Weird, I'm unable to reproduce now either. Closing, will reopen if I happen to repro again.
