### ISSUE TITLE
Store address step: Validate

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16087]
@garymurray was able to add this address when signing up for a store:

6 Devon Road
East London, OH 12345

We need to validate the address.

**Comment by justinshreve** [comment]
@kellychoffman Validate as in confirm that something is a valid/real address? I don't think this is a blocker for the initial release, and will require selecting a 3rd party API for validation like Google Maps API or UPS. It's definitely something we can do but I think we should put it in a different 'release' - is that OK? I think trusting the user to enter their real address to get things like valid tax rates is OK for now.

**Comment by kellychoffman** [comment]
Agree that this isn't a blocker for initial release and that it should go in the next one.

**Comment by allendav** [comment]
The TaxJar API might be able to help us here
