### ISSUE TITLE
Embed shortcode not supported on editor

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/wp-calypso#16091]
#### Steps to reproduce
1. Starting at URL: /post
2. Select a site
3. Switch to HTML mode
4. Write [embed] https://www.youtube.com/watch?v=izZPfGhLDxk [/embed]
4. Switch back to Visual mode

#### What I expected
- The embed link inside the shortcode embed to be properly displayed 
 - This works correctly on the wp-admin editor

#### What happened instead
 - It displays the content has it is from the HTML mode

#### Browser / OS version

masOS Siera / Safari

#### Screenshot / Video

<img width="974" alt="screen shot 2017-07-11 at 13 47 19" src="https://user-images.githubusercontent.com/651601/28068950-87d68eb6-663f-11e7-8b07-53cd248b3360.png">

#### Context / Source
#dogfooding, #media,  #manual-testing,  #user-report

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
