### ISSUE TITLE
Purchases: unsubscribed state still active after renewal

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#161]
Reported by @TheSteveK.

The unsubscribed state noticed is still displayed after renewal, for a short moment. This shouldn't happen as renewals resubscribe unsubscribed products.

Steps to reproduce:

- Go to `/purchases` and select an unsubscribed product.
- You'll see the unsubscribed state notice, prompting users to renew.
- Click Renew Now and complete checkout.
- You'll be redirected back to `Manage Purchase`. Note that the unsubscribed state notice is still there, though it disappears in a few seconds once the information about the subscription is updated.

Before:
![screenshot-wpcalypso wordpress com 2015-11-19 12-38-38](https://cloud.githubusercontent.com/assets/1248436/11270003/8c82d468-8ebb-11e5-89db-a40e8e55d1da.png)

After:
![screenshot-wpcalypso wordpress com 2015-11-19 12-38-44](https://cloud.githubusercontent.com/assets/1248436/11270005/8f87fd3c-8ebb-11e5-9363-ffea887979b5.png)

Related to 11802-gh-calypso-pre-oss (cc @andreabadgley who also noted this back then).

**Comment by drewblaisdell** [comment]
The current solution for #189 is to replace the currently saved purchase object with a new one returned by the `cancel-private-registration` endpoint, so they'll probably require separate PRs.

Unless anyone has a better one, I think a more realistic solution for v1 is just to display the entire `ManagePurchase` placeholder state until we've fetched the purchases again.
