### ISSUE TITLE
Woo Connect Insights: Week/Month/Year views display inconsistent dates

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16101]
_Weeks:_

In site stats a week view graph displays the first date of the week as the indicator (and displays data for 12 weeks):

![screen shot 2017-07-11 at 09 23 48](https://user-images.githubusercontent.com/551898/28076073-bd457924-661a-11e7-91a4-fb4ef0dbd004.png)

In store stats a week view graph still displays the first day of the week as the indicator but displays enough bars that we don't get labels on every one:

![screen shot 2017-07-11 at 09 25 21](https://user-images.githubusercontent.com/551898/28076171-0dcd4444-661b-11e7-86ac-c8d34ed33f43.png)

I _think_ this difference is because site stats _knows_ when the first data point it has is but store stats doesn't make that distinction.

_Months/Years:_

In site stats a month view graph display the short 3 letter month name as the indicator:

![screen shot 2017-07-11 at 09 27 20](https://user-images.githubusercontent.com/551898/28076235-37dc5b30-661b-11e7-8ae5-f8107f04da22.png)

In store stats a month view graph displays the last day of the month as the indicator:

![screen shot 2017-07-11 at 09 28 03](https://user-images.githubusercontent.com/551898/28076258-508120d0-661b-11e7-81cd-a020abddee18.png)

In site stats a year view graph displays the 4 digit year as the indicator:

![screen shot 2017-07-11 at 09 29 03](https://user-images.githubusercontent.com/551898/28076289-6f64effe-661b-11e7-8ce7-cecb14f23db4.png)

In store stats a year view graph displays the last day of the year as the indicator:

![screen shot 2017-07-11 at 09 29 15](https://user-images.githubusercontent.com/551898/28076311-7b3c0b1e-661b-11e7-919b-d63dca8f9f14.png)

_Todos_

- [x] Fix the Month graph to display short month names
- [x] Fix the Year graph to display 4 digit years
- [x] Fix the Month widgets to display short month names
- [x] Fix the Year widgets to display 4 digit years

_Questions_

Should we investigate limiting the number of periods returned by the API on the backend to only cover the time period we have data for - i.e. should we ensure that even if you request 20 periods if we only have data for 10 we just return 10?

**Comment by greenafrican** [comment]
> but displays enough bars that we don't get labels on every one

We can configure how many periods to return per unit.

**Comment by greenafrican** [comment]
> store stats a month view graph displays the last day of the month as the indicator
&
> 4 digit year as the indicator

I have a related issue opened for this https://github.com/Automattic/wp-calypso/issues/16072

**Comment by greenafrican** [comment]
> should we ensure that even if you request 20 periods if we only have data for 10 we just return 10

I really don't like the way site stats show 1 yr if it only has 1 yr of data as a very wide bar. I prefer keeping the scale of the periods consistent as it helps contextualise without having to readjust. My vote is that if we ask for 20 then we return 20.

**Comment by westi** [comment]
All the todos are covered by #16170
