### ISSUE TITLE
Activity Log: click day/event block to expand

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#16104]
In order to make the UI more functional, what do you think about making the entire day and event blocks/cards clickable to expand their content?

Right now, they open only if the chevron area is clicked, which is the card default behavior.

![image](https://user-images.githubusercontent.com/390760/28078449-cec45d22-665c-11e7-9455-8c022b396eee.png)

What are your thoughts on this?

**Comment by sirreal** [comment]
It certainly seems like something that could be added to `FoldableCard`. I don't see any reason why not.

**Comment by sirreal** [comment]
> It certainly seems like something that could be added to FoldableCard. I don't see any reason why not.

Turns out that exists 🙂
