### ISSUE TITLE
Jetpack plugins: Plugin listing displays incorrect/ambiguous information

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16102]
I have a site with 10 plugins installed but Calypso only shows 9 installed.

wp-admin:

![screen shot 2017-07-11 at 09 54 07](https://user-images.githubusercontent.com/551898/28077407-eafa670e-661e-11e7-9164-115ee530a1a2.png)

wpcalypso:

![screen shot 2017-07-11 at 09 51 14](https://user-images.githubusercontent.com/551898/28077384-de02a12e-661e-11e7-91ee-fd38ebbaf2fa.png)

This then leads to the following issues:

Because I have two versions of WooCommerce installed but only one active I get an upgrade prompt to upgrade to a newer version - But when I click through it says I already have the latest version installed:

![screen shot 2017-07-11 at 09 55 49](https://user-images.githubusercontent.com/551898/28077497-269a5ae4-661f-11e7-9d0c-e447aeb7751a.png)

It is impossible to tell which versions of a plugin are installed without clicking through to each one - it would seem more useful to display the version numbers in the initial listing

The changes in #15748 helped fix a problem like this elsewhere in Calypso.

**Comment by beaulebens** [comment]
@westi can you confirm how you have 2 copies of the same plugin installed? Do you just have one of them in a different directory, but it's "the same" plugin? (e.g. one is in `wp-content/plugins/woocommerce` and one is in `wp-content/plugins/woocommerce-dev` or something similar?)

**Comment by westi** [comment]
Yes two copies of the same plugin in differently named folders - so as to make it easy to switch between them for testing by deactivate/activate.

**Comment by cpapazoglou** [comment]
The default installed plugins page is WP Admin now, so that isn't relevant anymore.
