### ISSUE TITLE
Notifications: Firefox first load / hard reload doesn't open the Notification panel on first click

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#1611]
![licecap-](https://cloud.githubusercontent.com/assets/4389/11814048/0da747ca-a345-11e5-97de-28875d038772.gif)

This is a rather edge bug. To reproduce:

* Firefox (verified on v42)
* Open Calypso
* Do a hard refresh
* Click on the Notification icon. Nothing will happen, even if the icon will highlight.
* Further clicks will turn the panel off and on as usual. It's just the first click.

Notes:

1. The panel seems present (Firebug outlines it, and one can't click through) but doesn't show.
2. It's just the first click after a force refresh, not a normal refresh.
3. Checking the iframes hierarchy, it seems that it's the content that doesn't get loaded. 

<img width="428" alt="screen shot 2015-12-15 at 16 05 36" src="https://cloud.githubusercontent.com/assets/4389/11814183/b8b75074-a345-11e5-93ef-ee6f539f5732.png">

**Comment by lancewillett** [comment]
I'm not able to repeat this one — and it's edge case. :)

Tried with https://wpcalypso.wordpress.com/, https://wordpress.com/, and https://horizon.wordpress.com/ using Firefox 45.0.1 on OS X 10.11.4. A hard refresh (Ctrl-Shift-R on OS X) didn't cause the first click issue reported.
