### ISSUE TITLE
Editor: Tuesday is the first day of the week in some languages

### ISSUE THREAD

**Issue by ashercantrell** [Automattic/wp-calypso#16115]
#### Steps to reproduce
1. Set site language to French (other locales with Monday as the first day of the week may be affected too)
2. Create or edit a post or page, then click the schedule button
3. Check the days of the week at the top of the calendar.

#### What I expected

The days of the week at the top of the calendar should be LMMJVSD (Monday-Sunday)

#### What happened instead

The days of the week are MMJVSDL (Tuesday through Monday)

#### Screenshot / Video

http://cld.wthms.co/aR0SMN

#### Context / Source
I had a support request this weekend where a user noticed that his post calendar was showing the wrong date. After some troubleshooting, we figured out that the date was fine, it was showing the wrong day of the week. The user had their site set to French and the week started on Tuesday instead of Monday. So Tuesday, July 11 was showing as Wednesday, July 11 instead.

@yoavf did some looking for me and think it's related to #15437. He also mentioned that it's occurring for all locales where the first day of the week is not 0 except EN. 

#usereport

**Comment by yoavf** [comment]
@retrofox can you take a look, please?

**Comment by retrofox** [comment]
working on this now. I think it's related with #15615

**Comment by yoavf** [comment]
Yep, closing this down as a duplicate (sorry @ashercantrell !)
