### ISSUE TITLE
Editor: posts do not lock when someone else is editing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1613]
Raised by @gibrown 

Barring collaborative editing, we should probably lock the post when multiple people try to edit it.

WP Admin does this:

![screen shot 2015-12-15 at tue dec 15 10 11 48 am](https://cloud.githubusercontent.com/assets/1119271/11814370/5f05b16e-a314-11e5-81a9-ea6a74f1e8aa.png)

I assume if I edited from an existing page while someone else is doing so then bad things will happen (I haven't tried).

**Comment by folletto** [comment]
If possible I'd raise the priority of this one. Seems a very easy way to lose content.

**Comment by folletto** [comment]
Here's a concept that has the design aligned with Calypso patterns:

![screen shot 2016-01-06 at 15 31 24](https://cloud.githubusercontent.com/assets/4389/12146259/a06112fc-b48a-11e5-98cc-073896e8fdea.png)

**Comment by nylen** [comment]
One problem with this interface in wp-admin is there's no way to just view the markup of a post that someone else is editing.  I've needed this several times to fix up people's formatting, and I've gone over to the Calypso editor to view the markup :)  So we should implement some kind of read-only mode for locked posts in the Calypso editor.

**Comment by folletto** [comment]
Sure! I considered that a degree of complexity above just locking it, but if we can/want jump directly there, would be really good. ;)

**Comment by richardmtl** [comment]
Reported in 7160470-zen

**Comment by alisterscott** [comment]
Confirming this is still an issue

#bug-scrub #pre-gutenburg-bug-purge

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated,](https://github.com/Automattic/wp-calypso/milestone/309?closed=1) I don't think this issue is relevant any longer, but please feel free to re-open it if that's incorrect.
