### ISSUE TITLE
Login: disable social button

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#16132]
We should disable the social button in the same way that we disable the other form elements, until the page loads:
<img width="563" alt="screen shot 2017-07-12 at 10 28 54" src="https://user-images.githubusercontent.com/275961/28111312-fdf2cf9e-66ec-11e7-9857-cf1707a56129.png">

**Comment by stephanethomas** [comment]
See https://github.com/Automattic/wp-calypso/pull/16080 for an example of implementation.

**Comment by stephanethomas** [comment]
This was implemented in https://github.com/Automattic/wp-calypso/pull/16447.
