### ISSUE TITLE
Woo-Connect Insights: Cropped Sparklines

### ISSUE THREAD

**Issue by greenafrican** [Automattic/wp-calypso#16135]
On occasion (rarely), and seemingly unable to produce consistently, I'm seeing cropped sparklines:

![screen shot 2017-07-12 at 1 29 13 pm](https://user-images.githubusercontent.com/1160732/28115778-8fb7d140-6706-11e7-854e-679712b51254.png)

**Comment by greenafrican** [comment]
Refreshing the page fixed ^^ so it may be the max y value isn't always updating when navigating.

![screen shot 2017-07-12 at 1 55 47 pm](https://user-images.githubusercontent.com/1160732/28116591-040f56f0-670a-11e7-929c-c6313de2d8d9.png)

**Comment by westi** [comment]
I've seen this a bunch, I forgot to report it.
