### ISSUE TITLE
Editor: use the site's date format setting for date picker instead of interface language

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1614]
Raised by @SiobhyB 

What I Did:

I wanted to schedule a post for the 18th September, 2015.

What I Expected:

I expected for the date I selected to be shown in a format that was recognisable to me within the date picker.

What Actually Happened:

The date is shown in the MM/DD/YYYY format, which is generally only used in North America. This could cause confusion if a user, from a country outside of North America, tries to manually type a date into the box in the DD/MM/YYYY format or if they're just unfamiliar/unaware of why the different format is being used.

![screen shot 2015-12-15 at tue dec 15 10 18 00 am](https://cloud.githubusercontent.com/assets/1119271/11814527/30a691c0-a315-11e5-8bb6-6f6563ccd032.png)

The date format is based on the Interface Language set at https://wordpress.com/me/account

I'm based in the United Kingdom, where DD/MM/YYYY is used, and my Interface Language is set to English. There are also many other English speaking countries that use DD/MM/YYYY, such as Ireland, Australia, New Zealand etc. Some people who have English as a second language may also choose to set their Interface Language to English for learning or work purposes. In addition, someone from North America may have Spanish or French as a first language and then be shown the date format in DD/MM/YYYY, which may not be familiar to them.

I'm therefore not sure that it's best to determine preferences for date format from a person's Interface Language.

Is there any way that we can instead give users the option of choosing their date format? In WP Admin, for example, I was able to select my preferred date format under Settings > General

Notes from @rachelmcr 

> I agree that it makes more sense to use the site's Date Format setting (currently only available in WP Admin, along with other locale-related settings like timezone) than to rely on the Interface Language, given that with at least some languages such as English there isn't an exact correlation between language and locale.

**Comment by rachelmcr** [comment]
I confirmed that the date picker still uses the interface language to determine the date format.

With language set to English:

![screen shot 2017-10-04 at 6 15 38 pm](https://user-images.githubusercontent.com/8658164/31189466-3b539352-a930-11e7-867a-256ced35675f.png)

With language set to Spanish:

![screen shot 2017-10-04 at 6 15 06 pm](https://user-images.githubusercontent.com/8658164/31189473-4331bd88-a930-11e7-8200-70c927d55ad2.png)

However, I checked WP Admin and confirmed that it works in a similar way, displaying the scheduled date in the editor according to your interface language.

In English:

![screen shot 2017-10-04 at 6 18 02 pm](https://user-images.githubusercontent.com/8658164/31189578-8bafd05e-a930-11e7-82d9-9fa10d1615d5.png)

In Spanish:

![screen shot 2017-10-04 at 6 18 23 pm](https://user-images.githubusercontent.com/8658164/31189583-8e82ffc2-a930-11e7-9137-4732127edd12.png)

Leaving it as-is matches the WP Admin behavior, but perhaps the entire date picker could use the site's settings for date format and timezone, for consistency. See also: https://github.com/Automattic/wp-calypso/issues/18124

**Comment by alisterscott** [comment]
I have my browser language set to English - Australia which uses to DD/MM/YYYY format but I'm still seeing MM/DD/YYYY

<img width="315" alt="screen shot 2018-02-13 at 3 41 54 pm" src="https://user-images.githubusercontent.com/128826/36135082-73e243ce-10d4-11e8-8932-82734df20d35.png">

#bug-scrub #pre-gutenburg-bug-purge

**Comment by KokkieH** [comment]
Came to create an issue for this after I noticed it on a site where I'm publishing a large number of back-dated posts. It is really jarring to have the date displayed in this format, and I keep finding myself going back to posts to double check the date.

In WP-Admin it bothers me less, as it uses an abbreviated month name, not numeric dates.

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated,](https://github.com/Automattic/wp-calypso/milestone/309?closed=1) I don't think this issue is relevant any longer, but please feel free to re-open it if that's incorrect.
