### ISSUE TITLE
Comments: Site icons are lost on expanding comment details.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#16165]
![jul-12-2017 16-44-10](https://user-images.githubusercontent.com/349751/28144624-790216a2-6721-11e7-8240-bbe63c6004f4.gif)

A `SITE_SETTINGS_REQUEST` action gets fired that results in settings coming back without an `icon` property; this is what removes the icon. I haven't found what causes that action to fire, nor why that property would be missing.

**Comment by Copons** [comment]
The site settings are used to format date and time with the customization chosen by the users.
Unrelated, but thinking of it (cc @drw158), it might not be the best idea ever: those formats are really just presentational and used externally and might be quirky or incomplete.

About this issue: I'm afraid I could not reproduce, on both a .com and a Jetpack site.

**Comment by drw158** [comment]
I was able to reproduce with

https://wpcalypso.wordpress.com/comments/approved/horizonfeedback.wordpress.com

**Comment by Copons** [comment]
> I was able to reproduce with

Uh, yeah, I can reproduce with that site.
It looks like the site settings request overwrites site setting in the state, removing the informations about the site icon.
Not sure why it doesn't happen with my sites though.
