### ISSUE TITLE
Orders: New order notification appears in sidebar navigation

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16182]
When a new order comes in, it appears as a number in the Orders menu item in the sidebar: 

<img width="415" alt="screen shot 2017-07-13 at 2 06 50 pm" src="https://user-images.githubusercontent.com/5835847/28167748-8fd73070-67d4-11e7-8bc5-941e0031f249.png">

**Comment by ryelle** [comment]
@kellychoffman This should already be done, it was merged yesterday — #16066 / #15869. Or is this issue about making sure it automatically updates?

**Comment by kellychoffman** [comment]
My bad, ignore me.
