### ISSUE TITLE
Having a site with Jetpack version lower than 3.3 and going to posts crashes the app, instead of showing the warning

### ISSUE THREAD

**Issue by jorgefilipecosta** [Automattic/wp-calypso#16198]
While refactoring minimum jetpack version notice on plugins, I checked for other uses of this notices and I may have found a bug in posts.
To reproduce just go to https://wordpress.com/posts/{site}, where {site} is a site using jetpack with a version lower than 3.3 e.g:3.2.
Instead of displaying the notice “Jetpack 3.3 is required to take full advantage of all post editing features." The application becomes totally unresponsive and if we are lucky (tab does not crash) a big amount of notices appears with a screen saying an unexpected error happened.
Tested in the last version of Chrome and Opera.

The browser is not responsive so the gif is long but in the end it is possible to see chrome asking if I want to kill the tab I said to wait and then it is possible to see a big amount of notices.
![2017-07-13_12-38-29](https://user-images.githubusercontent.com/11271197/28178633-13ec1b1a-67f7-11e7-880b-52b5d36c3e9b.gif)
![opera_2017-07-13_16-43-33](https://user-images.githubusercontent.com/11271197/28178824-b90f7038-67f7-11e7-928f-86620063f02b.png)

This was tested against the deployed public version of wordpress.com. If for some reason I missed something and the bug I reported does not exist, it's probably my testing scenario that has something wrong. If so I’m really sorry for that and I will try to find out what was wrong.

If this in fact proves a bug I created a possible fix in PR https://github.com/Automattic/wp-calypso/pull/16201.

**Comment by sirreal** [comment]
I was trying to look at this and #16201, but I've been unable to reproduce. I checkout out and connected Jetpack 3.2.1, but I don't see this bug.

**Comment by jorgefilipecosta** [comment]
Hi @sirreal thank you for your tests 👍   And if the bug is not happening that's really good news! It means that's It's probably my environment that has something wrong and I'm sorry for that. But just for me to relax and not worry more about this problem you tried in user with mix of Jetpack and non Jetpack sites (maybe the mix of sites may have some impact) ?

**Comment by sirreal** [comment]
> And if the bug is not happening that's really good news! It means that's It's probably my environment that has something wrong and I'm sorry for that.

I didn't mean to discourage you from tracking and squashing this bug 🙂 . It's more likely that _my_ site is the one behaving strangely. It's a sandbox I've done a lot of testing with.

> you tried in user with mix of Jetpack and non Jetpack sites

Yep! This user has a lot of sites and a mix of Jetpack and non-Jetpack sites.

**Comment by jorgefilipecosta** [comment]
And locally if this change is applied if (siteId && isJetpack && false === hasMinimumJetpackVersion ) from to if (siteId ), that would make the notice being displayed in every site the problem also does not happen?
