### ISSUE TITLE
NUX: Browser refresh during signup causes broken flow

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#16199]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. At any point after completing Step 1 of the process refresh the browser
3. Attempt to complete the signup

#### What I expected
To be able to finish signing up

#### What happened instead
The flow hangs on the signup processing page after inputting account information and never completes.  If you then manually navigate to wordpress.com you find that you have an account and are logged in, but in some cases (depending on where you were in the signup process when you refreshed the browser) you have no sites created.

This is likely related to https://github.com/Automattic/wp-calypso/issues/10738 and https://github.com/Automattic/wp-calypso/issues/16156

Found by @alisterscott while testing https://github.com/Automattic/wp-e2e-tests/pull/625

#### Browser / OS version
Seen in OSX Chrome and Firefox latest

#### Context / Source
#manual-testing

**Comment by alisterscott** [comment]
Console error on processing page:

```
Uncaught Error: The dependencies [designType] were listed as provided by the design-type-with-store step but were not provided by it [ current flow: main ].
    at n.<anonymous> (signup.30f6b6a….min.js:5)
    at build.5d92245….min.js:79
    at build.5d92245….min.js:80
    at s (build.5d92245….min.js:79)
    at build.5d92245….min.js:80
    at s (build.5d92245….min.js:79)
    at s (build.5d92245….min.js:81)
    at n._assertFlowProvidedRequiredDependencies (signup.30f6b6a….min.js:5)
    at n._process (signup.30f6b6a….min.js:5)
    at Object.n.emit (vendor.6ce4abf….min.js:2)
```

**Comment by designsimply** [comment]
Tested and confirmed with the steps provided using Firefox 54.0.1 on Mac OS X 10.12.5 and I saw the same error alisterscott noted:

<strong>Video:</strong> [1m34s](https://cloudup.com/cVf6TSrQv4q)

> Error: The dependencies [designType] were listed as provided by the design-type-with-store step but were not provided by it [ current flow: main ].
> signup.30f6b6a54fea4a74f228.min.js:5:10427

![screen shot 2017-07-14 at fri jul 14 1 00 44 pm](https://user-images.githubusercontent.com/1119271/28226803-a7fe3fa2-6894-11e7-8b9c-c0322cdeea2a.png)
<sup>Seen at https://wordpress.com/start/user using Firefox 54.0.1 on Mac OS X 10.12.5.</sup>

**Comment by designsimply** [comment]
(internal reference: p6qnuF-5jb-p2)

**Comment by scruffian** [comment]
The signup flow used to save dependencies in local storage, but I believe this has been removed, so we'll need to make sure to take the user back to the first step if they reload the page.
