### ISSUE TITLE
Framework: the sidebar site picker is squished on mobile

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#1619]
![screen shot 2015-12-15 at 17 27 22](https://cloud.githubusercontent.com/assets/4389/11816534/1ccbd606-a351-11e5-8870-fb1de3a664c2.png)

Tested both in-browser and on device. 

To reproduce:

* Use the device or a window smaller than the mobile breakpoint
* Open My Sites → Site Switcher
* Huge padding on the side.

**Comment by lancewillett** [comment]
This looks fixed now. Testing with Chrome and dev tools, with wpcalypso to create small viewport.

![my-sites-switchen](https://cloud.githubusercontent.com/assets/66797/14361900/009d2d76-fcb2-11e5-944f-489701401aff.gif)
