### ISSUE TITLE
Jetpack Connect: accidental redirect to checkout

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#16195]
#### Steps to reproduce
1. Pick a self-hosted site that has a paid plan associated with it (tested with Personal and Professional).
2. Disconnect Jetpack.
3. Deactivate Jetpack.
4. Uninstall Jetpack.
5. Reinstall Jetpack through wp-admin.
6. Connect to WordPress.com.
7. Upon successful connection, I'm redirected to a checkout page with my current plan pre-selected, asking me to pay for it _again_.
8. If I dismiss the product on the checkout sidebar, the Plans view is presented, where the already existing plan is correctly identified.

#### What I expected

Not to have to pay for a plan twice.

#### What happened instead

I'm presented with a checkout page, with the already existing plan pre-selected for me to pay for it.

#### Flow

1. Connect to WordPress.com.

![screen shot 2017-07-13 at 16 43 16](https://user-images.githubusercontent.com/390760/28176063-f3d1c8ba-67ed-11e7-9ea2-1660ed2dadd6.png)

2. Upon successful connection, I'm redirected to a checkout page with my current plan pre-selected, asking me to pay for it _again_.

![screen shot 2017-07-13 at 16 43 42](https://user-images.githubusercontent.com/390760/28176049-e80bb09a-67ed-11e7-8424-e5a0fa8891b9.png)

3. If I dismiss the product on the checkout sidebar, the Plans view is presented, where the already existing plan is correctly identified.

![screen shot 2017-07-13 at 16 45 17](https://user-images.githubusercontent.com/390760/28176072-fc12d24e-67ed-11e7-9a22-a1f827a13214.png)

**Comment by sirreal** [comment]
Fixed by #16229
