### ISSUE TITLE
Greyed Area for Navigation Labels for Pages in Menus/Customizer

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#16190]
When the users are trying to add Navigation Label for pages in the Menus, in Customizer, they are confused by the greyed titles of pages that are present there and they think that these greyed titles can not be changed or typed over.

I have gotten several users with this confusion.

#### Steps to reproduce
1. Go to My Sites and click on the button Customize
2. In the Customizer, go to Menus and select any menu that you have
3. Click on "Add Items" and select Pages
4. Add to your menu one of the pages that you have created before
5. Click on the menu item for page that you just opened
6. Look at the Navigation Label - it has the greyed out title of the page typed in there

#### What I expected
- Either to be able to delete that greyed out text
- Or to have nothing in there at all

#### What happened instead
- It is confusing, because it seems that you can NOT type over that title

#### Screenshot / Video

https://cloudup.com/csGHzV-MBYm - I have circled the area that is greyed out and confusing

#### Context / Source
I had a several users that were confused by this; you can see the example of the Happychat #508804-hc
 
#user-report

**Comment by lancewillett** [comment]
Thanks for sharing this — menus aren't part of Calypso any more. We could pass this along to the core WordPress team, cc @melchoyce for future consideration.

From the user experience side of things, our goal with Customizer and other WP.com features is to match core WordPress as closely as possible. (Which is why we retired the Menus feature that was built for Calypso specifically).

**Comment by melchoyce** [comment]
Hey @katinthehatsite, great find. Would you feel comfortable submitting this bug report to https://core.trac.wordpress.org/?

**Comment by katinthehatsite** [comment]
Sure, @melchoyce will do!

**Comment by melchoyce** [comment]
Thanks!

**Comment by katinthehatsite** [comment]
I am checking this now and the area is not greyed out anymore, it must have been improved since my bug report; it looks more editable now and not greyed out so I guess this issue can be left here and be closed :) @melchoyce
