### ISSUE TITLE
Purchases: change copy in checkout button in case of renewal

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#162]
When renewing an upgrade, the button in checkout says "Purchase $XX subscription". Because this isn't a new subscription but the renewal of an existing one, this can be confusing. We should change the copy depending on either the user is paying for a new product or renewing one they already own.

![screenshot-wpcalypso wordpress com 2015-11-19 12-38-22](https://cloud.githubusercontent.com/assets/1248436/11270318/2fa5bda2-8ebe-11e5-8769-0b75a9844b91.png)

cc @mikeshelton1503 for copy advice.

**Comment by umurkontaci** [comment]
FWIW, there's a property in `cartItem.extra.purchaseType === 'renewal'` for renewals. Should be handy after we get the copy advice.

**Comment by mikeshelton1503** [comment]
Let's change the button copy for renewals to:
> Renew subscription - $XX
