### ISSUE TITLE
Comments: routing of non existent slugs/statuses doesn't change to correct URL

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#16208]
As already mentioned at https://github.com/Automattic/wp-calypso/pull/15933#issuecomment-315038301, there's an oddity happening with the Comment Management routes introduced in https://github.com/Automattic/wp-calypso/pull/16010.

Go to each of the following URLs and be sure you end up in the right place, with no interrupted rendering (component starts re-rendering, then a full page reload kicks in from a redirect).

|URL|Site Selector|Redirect/Destination|
|-----|:-----:|------|
|/comments/**status**/asdfasdf   | :white_check_mark: | /comments/**status**/**domain**|
|/comments/asdfasdf/asdfasdf || /comments/pending|

In both cases I eventually land on the site selector with the correct URL (e.g. `/comments/pending` or `/comments/{status}`).
Then, when I select a site, I briefly see the URL changing to the correct `/comments/{status}/{siteSlug}` and immediately change back to `/comments/{status}/asdfasdf` or `/comments/asdfasdf/asdfasdf`.

This flash "double change" keeps happening every time I change status list.

Here's a gif of what happens, starting from the URL `comments/spam/asdf`. Please check out how the URL changes while moving around.
For clarity, here are the actions performed (which all work as expected; I'm only talking about the URL).
When I've logged two URLs it means that the change is too quick to guess the action.

| Action | URL |
| --- | --- |
| Load `comments/spam/asdf` from scratch | `comments/spam/asdf` |
| Arrive at site selector | `comments/spam` |
| Select a site | `comments/spam/{siteSlug}` |
| Arrive at Comment Management in Spam status | `comments/spam/asdf` |
| Change to Approved status | `comments/approved/{siteSlug}`<br>`comments/spam/asdf` |
| Change to Pending status | `comments/pending/{siteSlug}`<br>`comments/spam/asdf` |
| Change to Trash status | `comments/trash/{siteSlug}`<br>`comments/spam/asdf` |

![jul-13-2017 19-43-21](https://user-images.githubusercontent.com/2070010/28182773-113f3bbe-6805-11e7-8363-6664acfd4e18.gif)

**Comment by kwight** [comment]
This was fixed at some point, I can't reproduce now.
