### ISSUE TITLE
Editor: inserting a link causes unexpected scrolling in Safari on iOS

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1621]
Steps to reproduce:
1. Open a web browser on a mobile device
2. Go to https://wordpress.com/posts and open an existing post with several paragraphs of text
3. Tap the beginning of the text to place the cursor at the top of the content
4. Scroll up to see the edit toolbar
5. Tap the link icon
6. Fill in the details and tap the "Add Link" button
7. Check to see whether the link is in view

<strong>Result:</strong> when you tap on the edit area the edit toolbar scrolls out of view and when you tap "Add Link" after linking the link is out of view. [1m4s](https://cloudup.com/c1KkaaaYRjE): tested with Safari Safari iOS 9.1 on iPhone 6.

/hat tip @kriskarkoski for the original report

> I noticed a few scrolling issues when inserting a link in Safari on iOS 9 (also noticed on iOS 8 before upgrading) on iPhone 6:
> - No matter where you insert the link, the Add Link modal appears centered within the total post area, so if you go to insert a link in the top of the post, it scrolls down to the link modal in the middle
> - After inserting the link, either as new text or apply to existing text, you are scrolled to the bottom of the post.

**Comment by lancewillett** [comment]
Re-tested this today—still happening exactly as described, key part is the post content has to be longer than the height of the available screen. When interacting with the Add Link overlay I found it jarring, it bounces around and is sometimes gone for a split second out of view.

Definitely minor but would make the UX flow better for editing links on mobile web — which is a big part of blogging and writing web pages.

**Comment by rachelmcr** [comment]
Closing this issue as this behavior will be replaced with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
