### ISSUE TITLE
Store: Display more helpful error messages on product failure

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#16218]
Right now if a product fails to create, we just display a general error message. The WooCommerce Product API does return different error messages depending on what went wrong -- for example a duplicate SKU. We should be able to show more helpful messages in certain situations.

**Comment by allendav** [comment]
e.g. duplicate sku looks like this:

<img width="1436" alt="screen shot 2018-01-23 at 5 03 48 pm" src="https://user-images.githubusercontent.com/1595739/35309611-38369dca-0062-11e8-91f9-6b52d59383cb.png">
