### ISSUE TITLE
Login: 2FA SMS code limit prevents log in.

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#16228]
When you trying to log in to a 2FA account with the SMS option, twice in a minute, you see this error
<img width="493" alt="screen shot 2017-07-14 at 12 48 35" src="https://user-images.githubusercontent.com/275961/28211179-3480a21e-6893-11e7-8cd0-8c00ab1f5104.png">

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in
2. Log in with a user that uses SMS for 2FA
3. Reload the page
2. Log in with a user that uses SMS for 2FA again
5. You should see the error in the screenshot above

**Comment by fabianapsimoes** [comment]
@scruffian how do you suggest this is fixed? To remove the limit of one SMS per minute entirely?

**Comment by stephanethomas** [comment]
Note that's a limit that is already present in the legacy page.

**Comment by scruffian** [comment]
I think we should show the 2FA page, and keep the limit. That way if they have the code they can still log in.

**Comment by stephanethomas** [comment]
I'm not entirely sold on this approach. It looks like we're going to introduce lots of complexity in our code to handle what seems to be an edge case. We have around twenty sms throttling errors per day, which is not that much in regard of some other errors such as empty or invalid nonces.

**Comment by scruffian** [comment]
> I'm not entirely sold on this approach. It looks like we're going to introduce lots of complexity in our code to handle what seems to be an edge case. We have around twenty sms throttling errors per day, which is not that much in regard of some other errors such as empty or invalid nonces.

Fair point. Closing.
