### ISSUE TITLE
Popover Menu: Hover style remains when not hovering

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#16227]
### To reproduce
1. Go to https://wpcalypso.wordpress.com/devdocs/design/ellipsis-menu
1. Open the menu
1. Hover an item (not disabled).
1. Move cursor out from the menu.
1. Observe that the focus state remains.

### Capture

![after](https://user-images.githubusercontent.com/841763/28209316-4956e5d2-6892-11e7-9168-fb9c01468f47.gif)

### Context

Noted here: https://github.com/Automattic/wp-calypso/pull/16225#issuecomment-315331457

cc/ @folletto

**Comment by shaunandrews** [comment]
It looks like this has been fixed. I'm unable to reproduce. If I'm mistaken, feel free to reopen.
