### ISSUE TITLE
Domains: After updating, the WHOIS store is not automatically updated

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#16239]
#### Steps to reproduce
1. Starting at URL: `https://wordpress.com/domains/manage/:domain/edit-contact-info/:site`
2. Make some changes to the WHOIS record.
3. Hit `Save Contact Info`.

#### What I expected
The button to become disabled, because there are no more WHOIS changes to save.

#### What happened instead
The button stayed enabled.

#### Context / Source
#manual-testing

**Comment by apeatling** [comment]
Fixed?

**Comment by klimeryk** [comment]
Soon :) Patch ready to merge in https://github.com/Automattic/wp-calypso/pull/20902

**Comment by ramonjd** [comment]
Fixed in #20902

**Comment by apeatling** [comment]
🎉
