### ISSUE TITLE
Post-publish preview: commenting flow can be confusing if you stay on the page

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#16241]
When publishing a new post, you now get an amazing preview — thank you team Tanooki. 👍 

I wanted to share a flow experience note to go along with it.

#### Steps to reproduce
1. Create a new post
2. Publish it
3. In the post-publish preview pane, make a comment
4. Click "Post Comment"

#### What I expected
For the comment to appear in the preview.

#### What happened instead
A new tab/window opens with the comment, leaving behind a incomplete comment form (not submitted).

To illustrate a bit more, two examples with two different WP.com themes:

- With a _P2 themed site_, you can add nested comments, but not more than 1 comment top-level. The main "Reply" button disappears, and so does the comment box.
- With a _non-P2 theme_ — I tested with "Luxury" — when you click the "Post Comment" button you are kicked out to a new tab, which is actually fine. But the issues is that the site preview window continues to show the comment as if it were still un-posted (the form doesn't submit in-page).

#### Screenshot / Video

![comment-in-post-preview](https://user-images.githubusercontent.com/66797/28220631-0caab874-6875-11e7-95c7-2df245b46955.gif)

Might cause #forked-flow by opening a new tab or confusing you whether you in the front-end of the site to continue commenting — or if you need to launch the front-end view in a new tab to comment.

Found the bug via #dogfooding and a bug report in Slack from @catehstn 🙇

**Comment by mattsherman** [comment]
I observed different behavior with a P2 themed site -- I was unable to post a comment in the preview.

I got:

<img width="435" alt="screencapture at thu jul 27 21 33 29 edt 2017" src="https://user-images.githubusercontent.com/2098816/28698728-4299553c-7313-11e7-9c82-64b1faaa0772.png">

**Comment by lancewillett** [comment]
Thanks for looking, Meeps. @jblz this is probably more for Samus, actually -- to investigate (not urgent, just to be aware of for the Site Preview effort).

**Comment by alisterscott** [comment]
Re-tested and confirmed this is still an issue - tested on "Luxury" theme

How often would this happen in real life though? Publishing a post and immediately adding your own comment?
