### ISSUE TITLE
Editor: drag'n'drop on an image creates a gallery

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1624]
Raised by @folletto 

![editor-drag-drop-gallery](https://cloud.githubusercontent.com/assets/4389/10043402/131523e6-61f3-11e5-8c31-7a953837b195.png)

Idea: when a user moves the mouse over an existing image, we allow them to create a new gallery straight from there.

From @aduth 

> How do we reconcile this with the drop-zone that appears over the entire editor when dragging a file?

From @folletto 

> Yep. We need to do some thinking around areas. I mentioned previously that the "land" target should be just the editor, not the full window, so in general would make sense to be more specific.
> 
> In terms of areas, here would be that "anything not the images" triggers the general upload-at-pointer, while when you're over an image, it would do the special case. :)

From @kellychoffman 

> I like this idea but agree it would require a rethink on areas, which would be a good thing. Ideally, we need to be able to drop to add a featured image, a single image in a specific place, an image to an existing gallery, and create a gallery by dropping on top of a single image.
> 
> I'm not sure what is possible within tinymce, but if we could get rid of the large drop zones, we could highlight with more precision like the cloudup editor did.
> 
> A few options, depending on what we can do with tinymce:
> 
> Simply highlighting the curser placement:
> <img width="608" alt="screen shot 2015-10-23 at 4 31 31 pm" src="https://cloud.githubusercontent.com/assets/5835847/10705451/8cd0a27e-79a3-11e5-8d4f-059c2bcb336c.png">
> 
> Adding a full bar:
> <img width="614" alt="screen shot 2015-10-23 at 4 11 07 pm" src="https://cloud.githubusercontent.com/assets/5835847/10705401/4ca6e276-79a3-11e5-81e2-6603a1ee69d2.png">
> 
> This would then open up the possibilities to do what @folletto mentioned above.
> 
> Creating a gallery:
> <img width="383" alt="screen shot 2015-10-23 at 4 30 30 pm" src="https://cloud.githubusercontent.com/assets/5835847/10705419/6c2901e2-79a3-11e5-9633-b586cb69cf25.png">
> 
> Adding a featured image: (current iteration)
> <img width="614" alt="screen shot 2015-10-23 at 4 28 37 pm" src="https://cloud.githubusercontent.com/assets/5835847/10705386/2f2a5ee4-79a3-11e5-85e1-cb2f586ff4cd.png">
> (needs text)
> 
> Adding a featured image: (planned placement)
> <img width="665" alt="screen shot 2015-10-23 at 4 24 57 pm" src="https://cloud.githubusercontent.com/assets/5835847/10705395/42e478a2-79a3-11e5-80a5-da7bea987f72.png">

From @coreh 

> We have a library on npm (`drag-element` — https://github.com/Automattic/drag-element) that can do the horizontal / vertical carets while dragging, and (re)position and split elements automatically upon drop as needed. It should work within a TinyMCE context with minimal adjustments. (The visuals can be adjusted with CSS, to match the editor styling.)
> 
> ![](https://cloudup.com/c_HZPBzkEQO+)
> 
> Here's a video of it in action:
> 
> https://cloudup.com/iUhPScVAhuy
> 
> I can help integrating it into the editor codebase. :smile: 

From @kellychoffman 

> :clap: Nice! Thanks @coreh!

**Comment by designsimply** [comment]
The following issue was raised by @kriskarkoski as a separate issue, but I think it could be something to consider while working on more specific dropzone targets so I'm just making a quick note of it here:

> While dragging-and-dropping images into a post I missed the drop zone on one of them and was navigated away from the Editor, with the browser displaying the full-size image instead. If there are unsaved changes you are prompted about leaving, but otherwise it just happens unexpectedly.

**Comment by aduth** [comment]
>While dragging-and-dropping images into a post I missed the drop zone on one of them and was navigated away from the Editor, with the browser displaying the full-size image instead. If there are unsaved changes you are prompted about leaving, but otherwise it just happens unexpectedly.

Noting that this is technically default browser behavior, though for user-experience purposes it may make sense to override to prevent the navigation. GitHub does this when trying to drop an image on any other area of the issue page aside from the text area.

**Comment by folletto** [comment]
> Noting that this is technically default browser behavior, though for user-experience purposes it may make sense to override to prevent the navigation.

Agreed. At least on the editor page, we should disable the default behaviour. It leads to SO much frustration when you fail to drop in the right area.

**Comment by rachelmcr** [comment]
Closing as Gutenberg will implement separate image and gallery blocks (and is already tracking drag-and-drop to add images to gallery blocks).

#bug-scrub #pre-gutenburg-bug-purge
