### ISSUE TITLE
Editor: Mobile: disable autocapitalization on URL field

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1626]
Raised by @kriskarkoski 

When adding a URL on iOS the URL field is autocapitalized, resulting in odd-looking URLs. It looks like we could add `autocapitalize="none"` to this field to disable it per [Apple's docs](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize)

<img alt="add-link-dialog-on-mobile" src="https://cloud.githubusercontent.com/assets/1119271/11818229/2042ce90-a327-11e5-8498-639e79c08e71.png" width="400" />

Also, on mobile at least should we prepopulate the URL field with http:// or leave that up to the user to add?

**Comment by brbrr** [comment]
This is fixed
