### ISSUE TITLE
WooCommerce Stats: Pill url and Strings

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#16272]
- [ ] When toggling between Site and Store stats, the query should persist, eg `?startDate=2017-05-31`.
- [ ] Change Store/Site to Revenue/Traffic.

**Comment by greenafrican** [comment]
My latest view on this is that we should keep 'Store' and perhaps have 'Traffic | Store' as 'Store' seems to have won out as the preferred nomenclature. 

Thoughts @kellychoffman ?

**Comment by psealock** [comment]
Closing this one. Persisting query parameters is covered in https://github.com/Automattic/wp-calypso/issues/16327.

**Comment by kellychoffman** [comment]
> My latest view on this is that we should keep 'Store' and perhaps have 'Traffic | Store' as 'Store' seems to have won out as the preferred nomenclature.

I think this makes sense for now 👍
