### ISSUE TITLE
Editor: it's difficult to select a parent page on a site that has lots of pages

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1627]
Raised by @simonwheatley 
- There is no "parent page" clearly indicated in the drop down under "Page Options" > "Parent Page"
- Searching for "VIP Go", which I know is an actual page title, does not show this page anywhere near the top… I've scrolled down many many levels and not found it

Notes from @kellychoffman 

> > There is no "parent page" clearly indicated in the drop down under "Page Options" > "Parent Page"
> 
> I see. VIP Go It _is_ selected, but it its so far down the list, that it is hidden. In a case such as this, it would  be nice if it was at the top. 
> 
> > Searching for "VIP Go", which I know is an actual page title, does not show this page anywhere near the top… I've scrolled down many many levels and not found it
> 
> I did a search and found it. Other pages have "VIP Go in them, and those were added in the results as well. 
> 
> <img width="312" alt="screen shot 2015-11-10 at 1 42 41 pm" src="https://cloud.githubusercontent.com/assets/5835847/11073590/ef9f0470-87b0-11e5-9671-e51ec7ceb02f.png">
> 
> Marking as enhancement and not bug as everything is working, but could be improved for sites with a huge amount of pages.

**Comment by designsimply** [comment]
#bug-scrub

Reviewed this and agree that it would be nice if an exact match appeared first in a search for Page > Page Settings > Page Attributes > Parent Page.

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated](https://github.com/Automattic/wp-calypso/milestone/309?closed=1), I don't think this issue is relevant any longer. But please feel free to re-open it if that's incorrect.
