### ISSUE TITLE
Store Orders: Enable filtering and pagination of the orders list

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#16288]
The store owner should be able to filter orders by order status, and view orders if there are more than 100.

Filtering was removed for v1 - @kellychoffman Do we still want to implement filtering like this?

<img width="458" alt="screen shot 2017-07-17 at 10 17 26 am" src="https://user-images.githubusercontent.com/541093/28272330-2f530262-6ad9-11e7-8cbb-75b2ad03bf71.png">

As for pagination, I think we should show 50 orders per page, and I'll use the pagination UI from the products list.

<img width="734" alt="screen shot 2017-07-17 at 10 22 47 am" src="https://user-images.githubusercontent.com/541093/28272578-e9cb49c4-6ad9-11e7-8aae-fef1ecad31e5.png">

**Comment by kellychoffman** [comment]
> Filtering was removed for v1 - @kellychoffman Do we still want to implement filtering like this?

Good question. Looking at it, it feels like we have too many statuses. I think we should [use a dropdown like in the Many Tabs example](https://wpcalypso.wordpress.com/devdocs/design/section-nav ) in dev docs. We could also consider consolidating the amount of statuses we show, but on mobile they will still have to collapse into a dropdown. 

@jameskoster - what do you think?

**Comment by kellychoffman** [comment]
> As for pagination, I think we should show 50 orders per page, and I'll use the pagination UI from the products list.

👍 I agree.

**Comment by jameskoster** [comment]
I prefer the text links to a dropdown personally. But agree there are too many.

We probably only need three filters here;

* All orders
* Orders awaiting fulfilment
* Orders awaiting payment (for offline payments primarily)

Other than that I think 90% of the time you'll be looking for a specific order, in which case you'd just search.

**Comment by ryelle** [comment]
@kellychoffman @jameskoster What should we do if there are no items of a given status (or search)? Like, no orders awaiting fulfillment? The existing EmptyContent takes over the entire page, so you can't switch back to another status. Search on products with no results does this:

![screen shot 2017-07-24 at 11 34 32 am](https://user-images.githubusercontent.com/541093/28531467-edaa419a-7064-11e7-801a-ed7c351c1e4f.png)

… and I can use that pattern for the search results, but I don't think that works for empty statuses.

**Comment by kellychoffman** [comment]
> We probably only need three filters here

Good idea. We could shrink them down slightly to say: 

- All orders
- Awaiting fulfillment
- Awaiting payment

**Comment by kellychoffman** [comment]
> What should we do if there are no items of a given status (or search)? Like, no orders awaiting fulfillment? The existing EmptyContent takes over the entire page, so you can't switch back to another status.

Could we do what we do on /pages? 

Published: 

<img width="752" alt="screen shot 2017-07-24 at 11 13 03 am" src="https://user-images.githubusercontent.com/5835847/28535307-1d935eae-7061-11e7-8040-7ff2eb370cfa.png">

Scheduled:

<img width="776" alt="screen shot 2017-07-24 at 11 12 57 am" src="https://user-images.githubusercontent.com/5835847/28535308-1d94d400-7061-11e7-88c0-7fc966c463ae.png">

The button label could read 'View all orders'. They could also go back to 'All orders' in the filter bar up top.
