### ISSUE TITLE
Store: Increase HTTP Failure Resilience

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#16296]
There are several problem scenarios for the Store application that make it vulnerable to HTTP failures, whether those failures come from a Jetpack proxy timeout, or a simple 500 error from the WooCommerce API. This task is to track each of those scenarios as we fix them.

- [ ] Product Create: Category create fails but was actually created on site (Jetpack timeout)
- [ ] Products (Array) Fetch (Jetpack timeout, see below)
- [ ] Orders (Array) Fetch (Jetpack timeout, similar to above)
- [ ] Product Create: Product create fails but was actually created on site (Jetpack timeout)
- [ ] Product Create/Update: Category GET fails and form doesn't populate.
- [ ] Shipping zone create: Shipping zone create fails but was actually created on site (Jetpack timeout)
- [ ] Shipping zone delete: Shipping zone delete fails but was actually deleted on site (Jetpack timeout)
- [ ] Shipping zone method create: Shipping zone method create fails but was actually created on site (Jetpack timeout)
- [ ] Shipping zone method delete: Shipping zone method delete fails but was actually created on site (Jetpack timeout)
- [ ] Required plugin installation and activation (added by @allendav )
- [x] General Settings Fetching (used on many screens)

To the Store on WPCOM team: Please consider areas you've worked on and add lines above.

**Comment by allendav** [comment]
As an example, this is the vague error that users see when jetpack queries time out

<img width="1473" alt="screen shot 2018-01-22 at 4 34 34 pm" src="https://user-images.githubusercontent.com/1595739/35251921-979c5276-ff92-11e7-87fa-b54f81db798a.png">

when the network log has things like this:

```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"http_request_failed","message":"cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received"}}
```

in response to requests like this (blog ID redacted)

```
https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/XXXXXXXXXX/rest-api/?http_envelope=1&path=%2Fwc%2Fv3%2Fproducts%26page%3D1%26per_page%3D10%26_envelope%26_method%3DGET&json=true
```
