### ISSUE TITLE
Store: Setup: WooCommerce: Suggest built-for-WooCommerce themes during Setup

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16294]
During store setup, if we detect that the current site theme isn't built-for-WooCommerce, let's suggest a few WC ready themes and make it easy for the user to install and activate one of them.

See also #16293

**Comment by kellychoffman** [comment]
Until we have more WP.com compatible themes, we should also have a card that displays info about Storefront if the user has a non-store compatible theme. This should appear on both fledgling and mamma.

<img width="756" alt="screen shot 2017-08-08 at 12 24 59 pm" src="https://user-images.githubusercontent.com/5835847/29089416-652f1f1c-7c39-11e7-8406-28d60cf18dd6.png">

Background: 
- all Store sites now have Storefront uploaded (symlinked). You can see this by going to My Sites > Themes and there you'll find Storefront in the Uploaded section. 

Notes on flow:
- widget uses [card with warning](https://wpcalypso.wordpress.com/devdocs/design/cards)
- the Learn More button in the theme widget will link to  `{URL}/wp-admin/customize.php?return=https%3A%2F%2Fwpcalypso.wordpress.com%2Fthemes%2Fstoreintial-launchdemo.blog&theme=storefront` which can be also found by going to: My Sites > Themes > Hovering on the `...` on Storefront in the Uploaded section > choosing Try & Customize.
- this gives the user the chance to customize before applying Storefront.

**Comment by jameskoster** [comment]
While the widget is something we can add later, the original issue here (Suggest built-for-WooCommerce themes during Setup) is being solved in https://github.com/woocommerce/wc-api-dev/pull/54

Closing this out for now.
