### ISSUE TITLE
Store: Bad error message when dispatching an undefined action or action with no type.

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#16300]
A few times when I'd be testing out freshly written code, I'd accidentally dispatch `undefined` or dispatch an action with no `type` property. In both of these cases, I get an error from the guts of `CompactTinyMCE`.  I wrote a post about it, but after some more sleuthing, I found it was in the  Store's instance. We should inspect which code is failing here and either guard from it and do nothing, or at least throw a more descriptive error.

![developer_tools_-_http___calypso_localhost_3000_store_product_coderkevin_wpsandbox_me_retry_1](https://user-images.githubusercontent.com/945228/28282995-fd5f1502-6af1-11e7-8793-ccff0070f40c.png)

To induce this error, just dispatch `undefined` or dispatch an action with no `type` property.

**Comment by timmyc** [comment]
@coderkevin doing a bug sweep/cleanup - this error is amazingly similar to the one we were tracking down in #20490 - should we keep this one open or stick with the newer issue for tracking it?

**Comment by timmyc** [comment]
I'm going to go ahead and close this out in favor of #20490 which has some solid/likely reproducible steps to hit this bug.

**Comment by coderkevin** [comment]
If you're thinking that #20490 if fixed will also fix this one, we could try it out. I think mentioning it is enough to keep it involved at this point.
