### ISSUE TITLE
Show three comments for each post

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#16316]
In Conversations, for each post, show latest three comments. They should be oldest to newest. For now, don't worry about threading. The idea is just to get the most recent three comments on the page for testing.

Mockup:

![conversations2](https://user-images.githubusercontent.com/24388/28295058-e5b72fe0-6b12-11e7-8dce-3727966420ba.png)

Open questions:

- Should each comment be limited to a few lines with a click to expand?
- Should we omit pingbacks/trackbacks?
- When a comment is held in moderation for a few days and then approved, it looks brand new but says it's days old. Is this a problem?
- How annoying is it to not have High Water Mark (and therefore see comments you've already seen)?

What other questions should we keep in mind?

**Comment by samouri** [comment]
Closing this because we did big thrust of it and splitting this into its individual nits.

> Should each comment be limited to a few lines with a click to expand?

Definitely https://github.com/Automattic/wp-calypso/issues/16918

> Should we omit pingbacks/trackbacks?
💯  --> https://github.com/Automattic/wp-calypso/issues/16920

> When a comment is held in moderation for a few days and then approved, it looks brand new but says it's days old. Is this a problem?

maybe?

**Comment by aaronyan** [comment]
Some posts are not displaying all three comments. Bug?

https://wpcalypso.wordpress.com/read/blogs/489937/posts/254547

<img width="845" alt="not_showing_three" src="https://user-images.githubusercontent.com/4505888/30879701-024464aa-a2b5-11e7-8b16-7e89eeeb5fd3.png">
