### ISSUE TITLE
i18n: locale options in Calypso and wp-admin are out of sync

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#1632]
We noticed in #1576 that Calypso holds a subset of the locale options currently available in wp-admin. We should A) update them to make sure calypso supports all possible variants. And B) add some process to make sure they don't get out of sync again.

/cc @akirk @gwwar

**Comment by akirk** [comment]
This only affects people who manage to change their wpcom UI language via wp-admin. Locale unification in general is a big topic, though out of the scope of Calypso.

**Comment by hewsut** [comment]
Calypso's language selector is exposing the discrepancies too. For example, the previously consolidated Chinese variants are viewable (albeit unsavable):

![screen shot 2016-03-08 at 12 09 37 am](https://cloud.githubusercontent.com/assets/2006764/13592644/2d6a2474-e4c2-11e5-8709-4e1d91ede360.png)
