### ISSUE TITLE
Different dialog layout for link

### ISSUE THREAD

**Issue by mikaelz** [Automattic/wp-calypso#16324]
Link editation dialog layout is different when switched into HTML mode (buttons are not fixed to bottom)
Lowering height of `.post-selector__results` would be sufficient.

#### What I expected
![screen shot 2017-07-18 at 13 30 08](https://user-images.githubusercontent.com/454800/28315495-f899aa78-6bbe-11e7-8313-8ef1397e11cb.png)

#### What happened instead
![screen shot 2017-07-18 at 13 30 28](https://user-images.githubusercontent.com/454800/28315503-02e21e8e-6bbf-11e7-9ebb-8c738f00ac73.png)

#### Browser / OS version
Google Chrome 59.0.3071.115

#### Screenshot / Video
https://youtu.be/RN93u531FOc

#### Context / Source
#user-report

**Comment by designsimply** [comment]
Nice find! Tested and confirmed using Firefox 54.0.1 on Mac OS X 10.12.5 ([30s](https://cloudup.com/caIOLIzWJvu)).

**Comment by mikaelz** [comment]
Depends on display resolution.
Wrong on 1280x800 https://i.imgur.com/8wlkwgD.png
OK on 1920x1080 https://i.imgur.com/SmHB9k8.jpg

**Comment by Avizc** [comment]
Hi! I'm taking a look at this right now. I'm hoping to have a pull request together in a few hours (this is my first time doing this!). I'll update where I'm at soon oh gosh.

**Comment by designsimply** [comment]
> This is my first time doing this!

Welcome!

**Comment by Avizc** [comment]
Oh golly thank you! I'm so excited oh my gosh. I just posted in my pull request a screenshot of my fix working. Sorry for the delay as I've had some weird issues with npm start not working! It works though oh gosh. I'm so ecstatic! It looks like someone else went ahead and fixed the width issue so hopefully if my request gets approved it should be looking cute again. Huzzah!
