### ISSUE TITLE
Woo-Connect Insights: Handle Query Period Between Year, Month, Week and Day

### ISSUE THREAD

**Issue by greenafrican** [Automattic/wp-calypso#16327]
Related to https://github.com/Automattic/wp-calypso/tree/try/persist-query-period-nav

And from https://github.com/Automattic/wp-calypso/pull/16287

Context:

>For example, when viewing a particular week, an owner may want a closer look at a selected week in the past. If they click "Days", the specified time period is lost and the owner now has to arrow back until they find the appropriate day.

**Comment by psealock** [comment]
Closing this issue. Its too edge case for Store Stats at this time. As the project evolves, it may make sense to look at which time related parameters persist on navigation. In that case, we can re-open
