### ISSUE TITLE
Store: Remove order filter bar until we add more than one filter options

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#16360]
Currently there's only one filter option; 'All orders';

![all-orders](https://cldup.com/91LZpkucDM-3000x3000.png)

This renders the filter bar a little useless xD The mobile experience is very confusing as well.

Let's just remove filtering for now and add it back when we build out the feature.

**Comment by ryelle** [comment]
I'm in the process of adding the filtering back, see #16288, #16341

**Comment by jameskoster** [comment]
@ryelle do you think it will make v1? If not we should still remove it for now.

**Comment by kellychoffman** [comment]
Let's close this since its in progress.
