### ISSUE TITLE
Editor: failed file upload doesn't tell you which file types are allowed

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1636]
Raised by @apeatling 

Tried to upload a file, I see this error message. Which file types are actually supported? I would have no idea where to look. What if they were listed in the message?

![screen shot 2015-09-25 at 12 26 21 pm](https://cloud.githubusercontent.com/assets/1464705/10110235/cf5439e6-6380-11e5-983f-6ff13c68f160.png)

**Comment by rachelmcr** [comment]
Confirmed this is still an issue.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by Aurorum** [comment]
PR in #39331 for this issue. :)

<img width="1246" alt="Screenshot 2020-02-09 at 13 23 52" src="https://user-images.githubusercontent.com/43215253/74102963-07daee80-4b40-11ea-827a-05acf7cd7d06.png">
