### ISSUE TITLE
Editor: Process shortcode reversal on-demand

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#1640]
**Steps to reproduce:**
1. Navigate to the [Calypso post editor](https://wordpress.com/post)
2. Select a site, if prompted
3. Change to the HTML tab
4. Insert embed code from a service where shortcode reversal is enabled
   - Example: [Getty Images](http://www.gettyimages.com/detail/photo/singing-labradoodle-high-res-stock-photography/573806847) (click Embed, then copy the embed code)
5. Change to the Visual tab
6. Save the post

**Expected result:**

At the very least, when viewing the saved post, it should display the embed.

**Actual result:**

The embed markup is sanitized when changing to the Visual tab, causing any `<script>` or `<iframe>` elements to be removed, very likely breaking the embed.

We should attempt to perform the shortcode reversal as soon as possible, preferably immediately after a paste that contains markup, and replace the embed markup with the shortcode equivalent if one can be determined

Ref: p3hLNG-k9-p2

**Comment by lancewillett** [comment]
See also #1095 — same bug report, but specific to GitHub Gist embeds.

**Comment by aduth** [comment]
It's a bit different than #1095. Shortcode reversals are a specific flow where a user who saves a post with embed markup from a select few services will have the markup be converted to a shortcode equivalent value (since we don't want their `<script>` and `<iframe`> markup saved to the post).

I'd say #1095 is more similar to #4583, perhaps related to same issues with script loading for embeds, though I'd need to investigate further to be sure.

**Comment by lancewillett** [comment]
See #5070 for new work to make embeds easier to add — via a menu item.

**Comment by aduth** [comment]
Ref: p1472135150000458-slack-calypso-editor

**Comment by aduth** [comment]
The reason why this is perceived to be working in wp-admin is because if the user saves the post after inserting the markup, a full reload occurs and the markup will be replaced with a shortcode in the editor content. This is because it is during the full page reload of a post save that the shortcode reversal takes effect. To my knowledge, if the user switches from HTML to Visual before saving in wp-admin, they will encounter similar issues because TinyMCE will alter the markup. 

>We should attempt to perform the shortcode reversal as soon as possible, preferably immediately after a paste that contains markup, and replace the embed markup with the shortcode equivalent if one can be determined

In addition to this proposed solution, we could also/alternatively mimic the behavior of wp-admin's full reload by replacing the content of the post editor with what's received back from the API as the saved result. This would at least correctly allow the shortcode to be preserved in the post content after a save (or autosave) as long as a user doesn't switch from HTML to Visual before the save occurs. Even if this does not resolve the issue completely, I feel it is a task we should pursue anyways, as we should trust the API result to be considered the most up-to-date representation of the post.

Related: 622-gh-io

Other embeds (e.g. Getty) are similarly affected by this due to the changes that TinyMCE makes. Because shortcode reversals expect very specific text patterns, even minor changes in markup can prevent the reversal from taking effect. On the shortcode reversal end, we could potentially update these patterns to accommodate the resulting markup after TinyMCE's transformations (15e2c-pb).

**Comment by aduth** [comment]
It is not currently documented, but we do have an embed reversal REST API endpoint which accepts a markup string and, if a reversal exists for that markup, returns the shortcode or embed URL. To achieve the "on-demand" reversal, we could detect if a pasted text appears to be HTML, and if so, issue a request to this endpoint to see whether it is indeed eligible for reversal to substitute in the post content.

**Comment by lancewillett** [comment]
#8301 has code ready for merge (or further review and testing).
