### ISSUE TITLE
Reader: Missing Recommendations link at wordpress.com

### ISSUE THREAD

**Issue by mikaelz** [Automattic/wp-calypso#16414]
At https://wordpress.tv/ the Reader has Recommendations link, but at https://wordpress.com/ it's missing.
#user-report

![ss_2017-07-20-18-03-06](https://user-images.githubusercontent.com/454800/28427648-2c57f676-6d77-11e7-8815-8cd5f08237ac.jpg)

**Comment by fraying** [comment]
It should be removed from the black masterbar version. (Recommendations have moved into the main Search screen.) cc @blowery

**Comment by designsimply** [comment]
Tested and confirmed using the following testing steps:

1. Go to https://wordpress.com/
1. Click "Reader" and look for "Recommendations" (it's missing).
1. Go to any WordPress.com website front end.
1. Click "Reader."
1. Click "Recommendations."

<strong>Result:</strong> clicking "Recommendations" on the front end masterbar redirects from https://wordpress.com/recommendations to https://wordpress.com/read/search

**Comment by blowery** [comment]
r159574-wpcom

**Comment by blowery** [comment]
Thanks for the report @mikaelz! I've removed the recommendations link from the sidebar.

**Comment by mikaelz** [comment]
Checked and it's OK
![ss_2017-07-21-16-17-05](https://user-images.githubusercontent.com/454800/28467484-5dc818bc-6e30-11e7-8b88-0cd21f873ca3.jpg)
