### ISSUE TITLE
Plugins: remove background automatic plugin updates

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#16416]
In a slack conversation with @lezama , we decided that since we've improved the autoupdate process with Jetpack sync, we no longer need to autoupdate plugins in the background of Calypso. We can simply trust the sync process.

**Comment by enejb** [comment]
Our stats show that this way of autoupdating plugins accounts for about 1% of all the autoupdates.

**Comment by enejb** [comment]
I added in internal issue https://github.com/Automattic/jpop-issues/issues/791
