### ISSUE TITLE
Store: WooCommerce: Replace Pressable flow with Atomic flow (Needs Design)

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16422]
When Store on WordPress.com goes live, this pressable flow will have to have been replaced.

Needs design.

![pressable-store-flow](https://user-images.githubusercontent.com/1595739/28433917-4e3a3d06-6d42-11e7-92ae-05e69d325c98.gif)

cc @mattyza @kellychoffman @jameskoster

**Comment by jameskoster** [comment]
This flow will be replaced with a new one once we're ready to begin marketing the Store project.
