### ISSUE TITLE
Store: WooCommerce: Sad Christmas: Installation of plugins on newly created business plan site fails: Primary domain doesn't have a valid SSL certificate

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16423]
Created new account, signed up for business plan, created site. Went to add first plugin (WooCommerce) to newly created site and got the following right out of the gate:

**Primary domain doesn't have a valid SSL certificate.**

<img width="737" alt="screen shot 2017-07-20 at 12 05 13 pm" src="https://user-images.githubusercontent.com/1595739/28434446-2b9279ec-6d44-11e7-89b1-b7f3c0bcbcbb.png">

Since we (Automattic) own this end-to-end it seems like we could either avoid this message or do something more user friendly.

Incognito, proxied, allendavstoretest2

**Comment by timmyc** [comment]
@allendav is this still an issue?
