### ISSUE TITLE
Store: WooCommerce: Stats: Scale Selector Empty on Narrow Screens

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16437]
If you embiggen the screen, you see the expected Days/Weeks/Months/Years, but on narrow screens it appears as an empty box:

<img width="766" alt="screen shot 2017-07-20 at 1 33 39 pm" src="https://user-images.githubusercontent.com/1595739/28437678-6a39f880-6d50-11e7-89a5-20ac6e716f02.png">

**Comment by kellychoffman** [comment]
cc @greenafrican @psealock

**Comment by timmyc** [comment]
This appears to no longer be an issue when testing in production today:

![stats-now](https://user-images.githubusercontent.com/22080/34272567-9ec9b2a2-e645-11e7-8642-f5901a7f111b.png)

closing this out.
