### ISSUE TITLE
Store: WooCommerce: Setup: Only show empty Address Line 2 editable field on demand

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16433]
Suggestion: During store address setup, to match how we present the address in domain registration and to reduce visual clutter (and since many if not most merchants will NOT have a second address line) instead of showing a blank address line 2, we could do a link to be consistent with domain registration, i.e.:

<img width="573" alt="screen shot 2017-07-20 at 1 11 02 pm" src="https://user-images.githubusercontent.com/1595739/28436884-72d46d7a-6d4d-11e7-8338-1fe7d0797f86.png">

**Comment by kellychoffman** [comment]
Good idea.
