### ISSUE TITLE
Store: WooCommerce: Pre-fill store location with address, if available

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16432]
Instead of a blank form during store setup:

<img width="766" alt="screen shot 2017-07-20 at 1 09 42 pm" src="https://user-images.githubusercontent.com/1595739/28436712-cc81f316-6d4c-11e7-89bd-e975e118da63.png">

We should pre-fill in the form with an address we have saved for the user:

<img width="573" alt="screen shot 2017-07-20 at 1 11 02 pm" src="https://user-images.githubusercontent.com/1595739/28436786-191382d0-6d4d-11e7-802b-643d22ffc936.png">

**Comment by kellychoffman** [comment]
Agree.

**Comment by justinshreve** [comment]
I'm going to remove this from the next immediate sprint for now. This is still something we can tackle in Q3/Release 1.1 but this is definitely an enhancement and not a top priority for the next week.
