### ISSUE TITLE
Store Orders: Add a placeholder while loading orders

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16443]
Refreshing the /store/orders/{domain} view briefly shows the "no-orders-for-you" view before showing the orders list. We should either show a placeholder or nothing instead of the no-orders-for-you view.

![no-orders-for-you-no-wait-just-kidding](https://user-images.githubusercontent.com/1595739/28439931-03d6c0ce-6d59-11e7-89d9-fd121f09155d.gif)

**Comment by ryelle** [comment]
Note (mostly to myself): part of this is already done in #16341, orders initializes with just an empty table:

<img width="778" alt="screen shot 2017-07-21 at 2 37 23 pm" src="https://user-images.githubusercontent.com/541093/28477476-2c2ad71c-6e22-11e7-997d-e5af68174023.png">

**Comment by timmyc** [comment]
+1 on this - but also the sidebar itself is missing some loading indicators on a hard refresh:

![loading-sidebar-orders](https://user-images.githubusercontent.com/22080/28882593-8697dfd2-7760-11e7-8f41-baf610c8cdb2.gif)
