### ISSUE TITLE
Store Orders: Keep orders list up to date without a page refresh

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16441]
While sitting on the sad "no orders" view, I completed an order in another window. I came back to the first window and it still said no orders. Refreshing fixed it of course.

It would be nice, when that browser tab/window is foreground again for it to auto refresh and show me new orders. The Page Visibility API could be used for this probably.

<img width="1123" alt="screen shot 2017-07-20 at 2 31 44 pm" src="https://user-images.githubusercontent.com/1595739/28439791-557da394-6d58-11e7-86f4-556147c4ab1f.png">

**Comment by timmyc** [comment]
So just noting that I experienced the same issue even when i was on a different page within calypso, and then navigated back to the orders page.  The new orders were still not shown.  See details of the flow in #16666

**Comment by kellychoffman** [comment]
I'm not getting this to happen anymore. @timmyc can you confirm?

**Comment by timmyc** [comment]
Pretty sure I had this happen earlier this week, but it was a very old tab and could have been related to proxy cutting off and/or my sandboxing of the API.

**Comment by kellychoffman** [comment]
@ryelle does this happen for you anymore or did you fix?

**Comment by ryelle** [comment]
There hasn't been an intentional fix, but maybe updates to the filtering on orders also changed how the orders are requested when the page changes. (right now) It shouldn't refresh orders if you go from one view of orders to another page and back again, but it will if you land on a different view the next time- ex searching orders, or going from "all orders" to "awaiting payment"

**Comment by kellychoffman** [comment]
Okay, thanks! I'm going to close this for now then. Reopen if you see this occurring in your travels.

**Comment by ryelle** [comment]
Re-opening this after some chat in slack– I think there was some misunderstanding above^

The goal with this issue would be to have new orders automatically show up in the orders list, and live-update the order count in the sidebar. This could be done by fetching orders with every page navigation, or maybe by continuously polling the remote site.

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.

**Comment by synora** [comment]
Closing as Store has been deprecated.
