### ISSUE TITLE
Media: Gallery: group ordering actions together

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1644]
Raised by @kellychoffman 

Media gallery modal could be organized a bit better. Especially grouping random ordering with Reorder.

Currently:
![screen shot 2015-09-28 at 3 48 08 pm](https://cloud.githubusercontent.com/assets/5835847/10148298/594c2e82-65f8-11e5-835f-f063a8cbd11f.png)

Proposed: 
![screen shot 2015-09-28 at 3 49 00 pm](https://cloud.githubusercontent.com/assets/5835847/10149276/13cd23ec-65fe-11e5-84e2-5b0222e5fe80.png)

Small screen:
![screen shot 2015-09-28 at 4 55 16 pm](https://cloud.githubusercontent.com/assets/5835847/10149835/bbc87a3a-6601-11e5-87ba-2188999ef080.png)

> Can preview and reorder be combined into one screen?

Good question. Perhaps on the large screen, the small screen view would be a bit tricky.

With the renaming of the tab from Reorder to Edit (11483-gh-calypso-pre-oss), I'm not sure it makes sense to move the random order setting. However, the lone checkbox is still odd. 

A toggle might be better since it is toggling the state of a single option.

<img width="252" alt="screen shot 2015-10-28 at 3 05 20 pm" src="https://cloud.githubusercontent.com/assets/5835847/10801425/59f4667a-7d85-11e5-9894-60703e861e08.png">

**Comment by rachelmcr** [comment]
#bug-scrub This issue is still valid as described.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

This issue does not appear to be relevant now that we have moved to block-based editor. See screenshot:

![Screen Shot 2021-01-29 at 13 31 48](https://user-images.githubusercontent.com/6549265/106329504-63612900-6236-11eb-92ce-b264d35131fd.png)

Would it be acceptable to close this issue and apply the label `Closed - Won't Fix`?

**Comment by kellychoffman** [comment]
Don't be shy to close old issues :) We can always reopen if still relevant.

**Comment by worldomonation** [comment]
> Don't be shy to close old issues :) We can always reopen if still relevant.

Thanks for the heads up! 😄
