### ISSUE TITLE
Reader Sidebar Tags spacing bug

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#16446]
The font size of the sidebar increased recently. As a result, the spacing on the followed tags list is off.

<img width="804" alt="screen shot 2017-07-20 at 3 09 23 pm" src="https://user-images.githubusercontent.com/24388/28441039-a81499c8-6d5d-11e7-9265-83e77b52a153.png">

cc @jancavan

**Comment by jancavan** [comment]
@fraying is that screenshot from Safari? They're also still misaligned on screenshots I took below, but I'm not seeing the exact same thing?

**Chrome:**
![screenshot 2017-07-20 19 01 45](https://user-images.githubusercontent.com/4924246/28446235-4a4fd7fa-6d7e-11e7-9988-0cb653350c1a.png)

**Safari:**
![screenshot 2017-07-20 19 05 16](https://user-images.githubusercontent.com/4924246/28446241-64d95402-6d7e-11e7-9629-6db03e5644c1.png)

**Mobile Safari:**
![screenshot 2017-07-20 19 05 48](https://user-images.githubusercontent.com/4924246/28446256-768b6d7a-6d7e-11e7-9805-589c4ea393b7.png)

**Comment by fraying** [comment]
@jancavan Yes, Safari. I'm still seeing it.

<img width="544" alt="screen shot 2017-07-25 at 9 27 00 am" src="https://user-images.githubusercontent.com/24388/28582761-71427dd6-711b-11e7-929f-f86cf2c79bfd.png">

**Comment by jancavan** [comment]
@fraying that's odd. What version are you on?

**Comment by fraying** [comment]
@jancavan Version 10.1.1

**Comment by fraying** [comment]
Seems to be a problem in Chrome, too.

<img width="806" alt="screen shot 2017-08-02 at 4 05 23 pm" src="https://user-images.githubusercontent.com/24388/28898735-6a460520-779c-11e7-8717-b48618207329.png">

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/22932
