### ISSUE TITLE
Themes Showcase: Incorrect Filter Results While Logged In

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#16440]
#### Steps to reproduce

1. Log into WordPress.com 
2. Starting at URL: https://wordpress.com/themes
3. Click on Premium - https://cloudup.com/c6uhx6DJPJG
4. Scroll down and you will start to see Free themes in the Premium filter. The first one I noticed was Confit - https://cloudup.com/clXevpKSyDF
5. Click on **All** to view all themes
6. Activate the Premium theme Peña and return to https://wordpress.com/themes
7. Click on **Free** to view only free themes
8. Click on **Feature**, and select **Post Slider** - https://cloudup.com/c9vOqffytMg
9. Although Peña is not free, and does not have a Post Slider, it will appear in the results - 
https://cloudup.com/cYauykn9aTQ

Note: The filters work correctly while logged out of WordPress.com.

#### What I expected

- When searching for Premium themes, I expected to only see Premium themes in the filter.
- When searching for Free themes, I expected to only see free themes in the filter.
- When searching for themes with post sliders, I expected to only see themes with post sliders.

#### What happened instead
- Themes showed up under filters they do not belong to.

#### Browser / OS version
Chrome Version 59.0.3071.115 / MacOS 10.12.5 

#### Context / Source

#user-report 3271659-t

**Comment by nicolelaine** [comment]
#### Steps to reproduce
1. Log into WordPress.com
2. Starting at URL: https://wordpress.com/themes 
3. Click on "Free" themes: https://www.screencast.com/t/kFRuy12Pum  
4. Scroll down and see some themes that are not free. https://www.screencast.com/t/U9yymF0QAh

#### What I expected
I expected to see only free themes under the "Free" toggle.

#### What happened instead
I saw some free themes and some paid themes under the "Free" toggle.

#### Browser / OS version
OSX 10.10.5
Chrome 60

#### Context / Source
Live chat: https://mc.a8c.com/support-stats/happychat/transcript.php?id=583201

**Comment by nicolelaine** [comment]
**Steps to reproduce**

1. Go to Theme Showcase
2. Choose Premium
3. Paste in the phrase "feature:wordads "

**What I expected**

To not see the Hammer theme, which does not support WordAds

**What happened instead**

Hammer is listed under this search term: http://imgur.com/a/SrS63 

**Browser / OS version**

OSX 10.10.5
Chrome 60

**Context / Source**

581676-hc

**Comment by supernovia** [comment]
I ran into this twice today. I can't consistently reproduce, but I tried searching for Singl and didn't get any results, and for Fortune (this time on a user's computer) and also didn't get results. Odd.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was not able to reproduce the issue in the Themes gallery:
![Screen Shot 2021-02-04 at 11 29 49 AM](https://user-images.githubusercontent.com/6549265/106945217-651a6900-66dc-11eb-850b-170cf212ab38.png)


As it was not reproducible, this issue is being closed with the label `Closed - Not Reproducible`.

**Comment by tbradsha** [comment]
I was able to reproduce this on free, Personal, Premium, and Business WordPress.com sites, though it's unclear what triggers it, and often a refresh fixes it. It may happen when flipping between the *All*/*Free*/*Premium* toggles.

The free themes are listed after the Premium themes, but still show.

Free plan site:
![image](https://user-images.githubusercontent.com/32492176/108850741-edd04a80-75a0-11eb-962c-eae808a30f47.png)

Premium plan site:
![image](https://user-images.githubusercontent.com/32492176/108850635-d1cca900-75a0-11eb-9c89-e5c05cc3dcd2.png)

Likewise, the free filter still shows Premium themes.

**Comment by DanielSmithMichigan** [comment]
> * Log into WordPress.com
> * Starting at URL: https://wordpress.com/themes
> * Click on Premium - https://cloudup.com/c6uhx6DJPJG
> * Scroll down and you will start to see Free themes in the Premium filter. The first one I noticed was Confit - https://cloudup.com/clXevpKSyDF

Pages 1-4 were only premium themes.

[Page 5 (Mostly premium themes, but then free themes start)](https://user-images.githubusercontent.com/10274366/126234458-f6b96037-b1ad-4cca-b812-06d7dda5a1df.png)

I don't see confit in the list, but I do see free themes. I guess it makes sense that we would ONLY want to see premium themes at this point, but I think the behavior now is not as bad as the listed behavior in 2017, since the free themes aren't interspersed.

> * Click on **All** to view all themes
> * Activate the Premium theme Peña and return to https://wordpress.com/themes
> * Click on **Free** to view only free themes
> * Click on **Feature**, and select **Post Slider** - https://cloudup.com/c9vOqffytMg
> * Although Peña is not free, and does not have a Post Slider, it will appear in the results -
>   https://cloudup.com/cYauykn9aTQ

[I do see Pena, as it's the currently active theme](https://user-images.githubusercontent.com/10274366/126234907-3bd11681-268d-4ffb-8350-cc91a8370832.png)

**Comment by mreishus** [comment]
Possibly same issue or related to [Theme Showcase: New searches cause results to be added to previous searches #54739]
