### ISSUE TITLE
Editor: better visual indication that publishing is in progress

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1645]
Raised by @akirk 

What I Did: Publish a post

What I Expected: Get the post published quickly

What Actually Happened: It takes about 5 seconds. While I understand this might be due to the API and nothing that can be immediately addressed (but to be honest, it should), I think the progress should be announced in a more visible way.

There is the small status message that says "Saving..." (just above the button) but compared to the success message that appears as a big bar when the post is finally published, it's a really tiny piece of text.

It's good that it is so small for the duration of saving revisions, but when you finally press that Publish button, there should be a big message that can't be missed that tells you that your post is on its way.

I think we should show in a similar way that the publishing is in progress and that the user needs to wait, maybe adding a spinner would be good, too.

From @mtias 

> I think we could use an info notice in the same place we put error/success notices that says "post is publishing".

From @folletto 

> Can we replace the "Publish" button with a spinner of some kind? I feel that would work well enough, and would also avoid any extra issue.
> 
> Adding a publishing banner that then turns to "Published" with the view post link would work too :)
> _(especially if we can fade a yellow banner in a green banner with a transition...)_

From @kellychoffman 

> I like the idea of replacing the "Publish" text with "Publishing" while it has a disabled style. We do that in a few other places and it works well. Either that or an in-progress message that transitioned into a success message as folletto mentioned.
> 
> A progress indicator would also be nice in this instance but I'm not sure how well it would work with the success message. 

From @folletto 

> I agree text would be better, but changing test live there might make the
> button jump, and that would be an issue :)

From @mtias 

> Also with i18n it may drop into a separate line as well.

From @kellychoffman 

> > Yeah thats the only issue, especially problematic with the split button. Lets go with
> 
> an in-progress message that transitioned into a success message

**Comment by lancewillett** [comment]
This is much improved now. Let's open new issues with specific changes needed in the current editing flow.
