### ISSUE TITLE
Stats: Referrer link opens a new tab, but redirects old one as well

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#16453]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats
2. Click on a referrer link in the Referrers panel
3. A new tab opens with the link
4. The old tab redirects as well

#### What I expected

I expected for a new tab open and the old one stay on /stats.

#### What happened instead

The /stats redirected to the Referrer URL as well, so now there are 2 tabs open with the Referrer URL.

#### Browser / OS version

Latest Google Chrome on Windows 10 Pro

#### Context / Source

#user-report 3333532-t

**Comment by unDemian** [comment]
@belcherj @gziolo I could not reproduce this https://cloudup.com/c_QkgtNxm9v

**Comment by gziolo** [comment]
It might be browser specific issue:

> Latest Google Chrome on Windows 10 Pro

Let's leave it to someone with Windows Machine.
