### ISSUE TITLE
two-step authentication login returns nonce information

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#16456]
#### Steps to reproduce
With two-factor authentication enabled
1. Starting at URL: http://calypso.localhost:3000/log-in/sms 
2. Intercept the request being sent (after inputting the code and pressing 'continue') to stop it from reaching WP (I describe how that happened "practically" for me below)
3. Reload and resend the code

#### What I expected
Reset the form to a clean state (and possibly display message to the user to repeat the action)

#### What happened instead
The code was not reset in the input box, displaying error in nonce verification
(please see the screenshot).
#### Browser / OS version
Firefox, macOS Sierra

#### Screenshot / Video
![two-factor_error](https://user-images.githubusercontent.com/13561163/28459597-fc6bc39a-6e05-11e7-8cbd-ad7de4757b49.png)

#### Context / Source
What happened for me: just as I inputted the code and pressed 'Continue', the wifi networks decided to swap. The later is non-functional at the moment, so the laptop went offline. The form froze and after reloading the page, the code was still displayed and the button was active.
Pressing the button again, gave the error displayed in the screenshot.

**Comment by tyxla** [comment]
cc @fabianapsimoes @stephanethomas @scruffian @Tug

**Comment by stephanethomas** [comment]
Thanks @AnnaMag for reporting this problem! This will be fixed by https://github.com/Automattic/wp-calypso/issues/16505.
