### ISSUE TITLE
Editor: blinking trash Icon is a bit confusing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1646]
Raised by @akirk 

What I Did: Click the trash icon

What I Expected: Clicking the icon would make it ask me if I wanted to delete the post. As it started blinking I figured I could stop the deletion by clicking it again.

What Actually Happened: It started blinking, I clicked it, but kept blinking and after a few seconds redirected me to the post overview page.

What does the blinking indicate? Does it do that until the API responds that the post has been deleted successfully? 

Maybe the text in the popover bubble could change from "Send post to the trash" into "Post is being sent to the trash"

Note from @mtias 

> > Maybe the text in the popover bubble could change from "Send post to the trash" into "Post is being sent to the trash"
> 
> Good suggestion. It should also disable the action/cursor.

**Comment by timmyc** [comment]
This functionality was changed in #11536 - The icon no longer blinks, it now has a text label which reads "Trashing" while the delete operation takes place:

![trashing](https://cloud.githubusercontent.com/assets/22080/24007042/bd199a6c-0a2a-11e7-8c9c-57734585b84b.gif)
