### ISSUE TITLE
Should we update the look of a missing Gravatar in the sidebar?

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#16467]
Should we change what we show for a missing Gravatar in the sidebar? Here's what we currently show:

<img width="576" alt="missing-gravatar" src="https://user-images.githubusercontent.com/11487924/28469198-7eb6d874-6e03-11e7-8ab4-8e339adf1834.png">

Steps to repro:
1. After running Calypso locally, go to http://calypso.localhost:3000/me
2. Find the Gravatar image using the console (should be something like `<img class="gravatar" ...`
3. Replace that element with `<span class="gravatar is-missing"></span>` (this mimics what happens when the Gravatar can't be loaded)

**Comment by v18** [comment]
@drw158 and @iamtakashi - do you have any opinions since you worked on the related `EditGravatar` feature?

**Comment by drw158** [comment]
Oh! I didn't realize we didn't show anything. To be consistent, I suppose we should show the missing person gravatar, although I personally don't like the design.
