### ISSUE TITLE
Question: How to recompile after I made my changes

### ISSUE THREAD

**Issue by mikaelz** [Automattic/wp-calypso#16483]
I'm trying to create my first PR for https://github.com/Automattic/wp-calypso/issues/2570

1. `npm start` (node 6.11.1)
2. Edited client/my-sites/post-relative-time-status/index.jsx
3. Checking on http://calypso.localhost:3000/posts/michalzuber.wordpress.com, but no change

Re-run `npm start` showed error, but how can I avoid restarting node to see changes?
Sorry, but I'm a node newbie so please be patient :)

**Comment by blowery** [comment]
What's your development environment look like? Calypso tries to watch the filesystem for changes and automatically recompile, but this won't work well (or at all) if you're using something like vagrant where the files being run are on a network file system.

**Comment by mikaelz** [comment]
No Vagrant. Just plain node install on Arch Linux.
Tried again and it really works. Sorry, my bad. Closing.
