### ISSUE TITLE
Cancellation survey not fully responsive, blocks flow on small screens

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#16498]
Originally reported by @formosattic :

A user wanting to cancel plan (ref: 1732638-t) said:

> I can’t Flick the cancel subscription button as the ‘why your are leaving’ option menu covers this and I can’t exit this menu from an iPhone SE

The “Your thoughts are needed” form pops up when when trying to remove an upgrade.

Here’s how it should look like, using iPhone 6 (375×667) as an example:
<img width="150" alt="screen-shot-2017-07-24-at-18-03-33" src="https://user-images.githubusercontent.com/8658164/28518876-6fb0733e-7061-11e7-92c0-2c4edbca2803.png">

Here’s how it looks on iPhone SE/5/5S (320×568), where it’s not possible to scroll down to the answer buttons:
<img width="150" alt="screen-shot-2017-07-24-at-18-01-32" src="https://user-images.githubusercontent.com/8658164/28518880-75614006-7061-11e7-93b9-37a692c02822.png">

#### Context / Source
#user-report
Internal ref: p4a5px-1Tl-p2

**Comment by gwwar** [comment]
<img width="323" alt="screen shot 2018-02-23 at 1 40 52 pm" src="https://user-images.githubusercontent.com/1270189/36618228-31f31ad8-189f-11e8-885d-6706e739e957.png">

I tested this in a simulated environment and it looks like the modal has been improved, and overflowed text is scrollable. I'm closing this out, but feel free to reopen if folks are having trouble on physical devices.
