### ISSUE TITLE
Media: Unable to crop images using touchscreen on IE11 / Edge

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#16506]
#### Steps to reproduce
1. Using IE11 or Edge on a touchscreen Windows device, open https://wordpress.com/media/example.wordpress.com
2. Select an image, click Edit
3. Attempt to resize the cropping selector using the touchscreen

#### What I expected
To be able to crop the image

#### What happened instead
The background of the page scrolls, but nothing happens to the cropping region.  Using a mouse to drag the corners around works fine.  The touchscreen is functional in Chrome on Windows.

#### Browser / OS version
Surface Pro 3, Windows 10 - IE11 and Edge latest

#### Context / Source
#manual-testing

**Comment by cathymcbride** [comment]
Closing since there have been no further reports and support for IE11 ends Aug 2021.
