### ISSUE TITLE
Editor: "Saving of draft failed" after 2FA redone in another tab

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1650]
Raised by @skeltoac 

While editing a draft in one tab, an admin screen in another tab asked for a 2FA code. After completing that task I returned to the editor and saw the red alert with "Saving of draft failed" at the top. I had to use my clipboard to hold the unsaved changes, reload the page, then paste the changes back in.

Whatever changed in my cookies should have been smoothed over by Calypso.

Related: #315

**Comment by rachelmcr** [comment]
I'm not able to reproduce this issue anymore. After removing my 2FA cookie and reauthorizing 2FA in another tab, I returned to the editor and had no errors saving/updating the post.

#bug-scrub #pre-gutenburg-bug-purge
