### ISSUE TITLE
Editor: URL not updated after selecting parent

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1651]
Raised by @mjangda 

What I Did:
- Adding a new Page
- Add a title ("Meals")
- See the slug populated ("meals")
- Select a Parent Page under Page Options ("Schedule")
- The permalink is not updated to reflect the new structure (should be "/schedule/meals/")

Note: this only happens with drafts.

**Comment by mtias** [comment]
This was fixed in #1583.
