### ISSUE TITLE
Reader: featured_image for jetpack when excerpts are set to true

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#16514]
When Jetpack sites have excerpts turned on and its posts have featured_images, we can drop the image.

Thats because for non-jetpack we always only allow things within the content.  But for jp w/ excerpts on, it _isn't_ in the "content" most of the time since we only have a tiny portion of it.

We can close this issue once we allow for jp sites to feature images that are not in their content when they have excerpts turned on.

Example: https://wordpress.com/read/feeds/68184498

cc @blowery @lamdayap

**Comment by codestor4** [comment]
ZD - 606191
