### ISSUE TITLE
Gravatar Upload: should Gravatars displayed be square?

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#16526]
Looking at the new Gravatar upload feature, both the Gravatar image prompt and user image is rounded:

![round square](https://user-images.githubusercontent.com/128826/28552908-27a1b674-7134-11e7-9f79-19a602b42ed8.png)

When looking at Gravatar itself the UI mainly shows square images:

![screen shot 2017-07-25 at 12 22 51 pm](https://user-images.githubusercontent.com/128826/28552919-353c64f0-7134-11e7-972a-84917e70db2d.png)

and the homepage:

![screen shot 2017-07-25 at 12 24 35 pm](https://user-images.githubusercontent.com/128826/28552933-4125467e-7134-11e7-83fb-e81bf9d485b3.png)

Should we show a square image where it says "Click to change photo" to be more representative of how a Gravatar is used by other sites?

**Comment by folletto** [comment]
I'd say no, because:

1. The canonical* WordPress·com UI is rounded, and we show it there as we show it elsewhere.
2. Gravatars however can be used anywhere, so it makes sense to show the full square. Could be nice if Gravatar could show both since rounded avatars are fairly common.

**Comment by drw158** [comment]
Agreed with @folletto. At first I thought the suggestion was to change the Gravatars on gravatar.com to round, which I would be in favor of :)

We should do what's best for our users and not let other services dictate things like this. At the moment we use round avatars for users to distinguish them from site avatars (square).
