### ISSUE TITLE
Login: improve verification code messaging

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#16534]
@johnmaeda and @lancewillett suggested a tweak for sending verification codes via text message:

> Change the notification so the first bit of text is the code, instead of leaving it to the end.

For example:

Before | After
------------ | -------------
 ```WordPress.com verification code: 0515313``` |  ```0515313 is your WordPress.com verification code.```

This is meant to optimize the code flow for the common use case of push notifications showing the contents of new messages. 

In some cases, only an excerpt from the message is shown in the notification. By leading with the code, we ensure that it doesn't get truncated.

See p58i-5Vx-p2 for more discussion.

**Comment by fabianapsimoes** [comment]
I believe these notifications also need to be localized, from what I can see in testing. Maybe it can be tackled with the same PR.

**Comment by lancewillett** [comment]
Noting the code changes are not in Calypso, but WP.com side. From what I investigated, the strings are wrapped in i18n functions already.

**Comment by stephanethomas** [comment]
I'm going to close this issue since this will be addressed by the D6999-code server patch.
