### ISSUE TITLE
Social login: Add 2FA for connecting existing accounts

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#16544]
When we merged #15543 we did so without adding support for connecting existing account that have 2FA enabled.

We need to ensure that when someone connects a Google account to an existing WPCOM account with 2FA enabled, they are prompted for the 2FA details before they are logged in and the account is created.

**Comment by pento** [comment]
I was unable to reproduce this - I successfully connected a Google account to an existing WPCOM-with-2FA account, and was correctly prompted for the 2FA code (sent via SMS) before I was shown the Connect screen, and able to connect.

**Comment by stephanethomas** [comment]
I'm gonna close that issue, feel free to reopen it if needed @scruffian.

**Comment by scruffian** [comment]
I can replicate this still with both login and signup.

**Comment by pento** [comment]
Okay, I see the difference. I thought you were referring to the process of "click Google login button -> existing account found -> existing account username/password -> existing account 2FA code -> connect -> logged in".

After following that flow, I can reproduce it as "click Google login button -> {missing 2FA prompt} -> logged in".
