### ISSUE TITLE
Themes: searching for a multi-word theme title should show it first before other results

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#16552]
#### Steps to reproduce
1. Starting at URL: wordpress.com/themes
2. Search for "Shine On"
3. See the long list of search results
4. and ooop! at the very bottom (below fold on small screens) is the 1 theme match

URL example: `wordpress.com/themes/example.wordpress.com?s=shine+on`

#### What I expected
If a theme title matches the exact search term (even without quotes), it should show up first.

#### What happened instead
The theme result was below other partial matches.

#### Screenshot / Video
<img width="912" alt="screen shot 2017-07-25 at 12 45 41" src="https://user-images.githubusercontent.com/66797/28590639-b8fc96b8-7137-11e7-97a7-9f888c5e4cd7.png">

Found via #manual-testing -- reported by @rralian

**Comment by lancewillett** [comment]
Notes:

- Adding quotes around the term fixes this (people might not know how to do that, though).
- On small screens it's very easy to miss the theme result.

**Comment by rralian** [comment]
FWIW, as a user I found the non-theme results very confusing. It wasn't immediately clear to me that I was getting results that were just categories of themes. I actually thought there was a bug and I was seeing post results. Read how the "Education" line reads across. That just looks like actual content, not a description of a "subject" of themes. The whole page looked like a bug to me.

**Comment by cometgrrl** [comment]
This is no longer reproducible.

<img width="1695" alt="SCR-20230530-gyq" src="https://github.com/Automattic/wp-calypso/assets/86427589/4ba5f833-5e44-46a7-943f-c3e73b8e2de7">
