### ISSUE TITLE
Editor: remove post format icon

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#16557]
Came up in #16521 

 https://github.com/Automattic/wp-calypso/pull/16521#issuecomment-317758193

We should remove the icon because:

- post format is already shown in the sidebar
- the format icon is next to an icon button, misleading the user to think it's also a button
- clutters the editor unnecessarily

<img width="614" alt="28545867-88297d48-70c0-11e7-8f67-af9e11544062" src="https://user-images.githubusercontent.com/618551/28592912-229c9420-7150-11e7-9ad1-cac7931b2917.png">

**Comment by lancewillett** [comment]
Sounds good, thanks for noticing and creating this issue.

**Comment by mcsf** [comment]
→ #17009

**Comment by lancewillett** [comment]
Fix confirmed, testing in Mac-n-Chrome.

Before:
<img width="1240" alt="screen shot 2017-08-08 at 18 49 09" src="https://user-images.githubusercontent.com/66797/29086398-59a53d9e-7c6a-11e7-8aea-0d90d90bfe8f.png">

After:
<img width="1242" alt="screen shot 2017-08-08 at 18 49 17" src="https://user-images.githubusercontent.com/66797/29086402-5c22f052-7c6a-11e7-85b7-d00d8289d286.png">
