### ISSUE TITLE
Editor: Mobile: Safari does not scroll down as new content is added

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1655]
Raised by @kriskarkoski 

Safari (iOS 9/iPhone 6) does not scroll down automatically to show the content that is added to a post. For comparison, Chrome on the same device does scroll down automatically once content is added (ex. return does not scroll the view down, but once anything is typed the view scrolls down to show the next text).

<strong>Video:</strong> [1m7s](https://cloudup.com/ckpWZNS4q9W)

Note from @timmyc 

> Safari (iOS 9/iPhone 6) does not scroll down automatically to show the content that is added to a post. For comparison, Chrome on the same device does scroll down automatically once content is added (ex. return does not scroll the view down, but once anything is typed the view scrolls down to show the next text).

**Comment by brbrr** [comment]
Retested on iPhone SE / iOS 11.2 - Issue still there.

**Comment by rachelmcr** [comment]
Closing as the current behavior will be superseded by how Gutenberg handles scrolling on mobile.

#bug-scrub #pre-gutenburg-bug-purge
