### ISSUE TITLE
Signup: Logging in during signup restarts the signup process

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#16561]
If you go to wordpress.com and start the signup process, at some point you'll be asked to create a user account to proceed. At that point, if you realize that you already have a WP.com account, and decide to log in, you can't do it without "breaking" your signup flow.

The only available link to log in is presented in the top-right of the screen (in the masterbar). If you click that, you go and log in, and then you're dropped back into the signup flow, but 1. you're back at the start, and 2. it's likely to look different (maybe they are different flows, or else I was seeing a test of some sort?).

Here's what I saw (indicating where I clicked each time):

![screen shot 2017-07-25 at 4 02 58 pm](https://user-images.githubusercontent.com/108942/28596842-2918e79c-7158-11e7-8594-fe9b185e2638.png)

![screen shot 2017-07-25 at 4 03 05 pm](https://user-images.githubusercontent.com/108942/28596855-3318b45c-7158-11e7-854a-0dc6aaa7baed.png)

![screen shot 2017-07-25 at 4 03 14 pm](https://user-images.githubusercontent.com/108942/28596845-2b92df8c-7158-11e7-96e6-794b4b9e2c56.png)

![screen shot 2017-07-25 at 4 03 20 pm](https://user-images.githubusercontent.com/108942/28596862-3eaf632e-7158-11e7-993d-88fc37a5f2c5.png)

![screen shot 2017-07-25 at 4 03 36 pm](https://user-images.githubusercontent.com/108942/28596865-435470cc-7158-11e7-8350-11cd3922fd00.png)

![screen shot 2017-07-25 at 4 03 40 pm](https://user-images.githubusercontent.com/108942/28596870-49b6e88c-7158-11e7-8be1-4c7bed07501b.png)

![screen shot 2017-07-25 at 4 03 45 pm](https://user-images.githubusercontent.com/108942/28596873-4b951f3e-7158-11e7-9770-7959a6394d9f.png)

![screen shot 2017-07-25 at 4 03 54 pm](https://user-images.githubusercontent.com/108942/28596886-57baa41e-7158-11e7-9505-c84cf13aba1b.png)

**Comment by rachelmcr** [comment]
Thank you for including these screenshots! I'm going to close this in favor of https://github.com/Automattic/wp-calypso/issues/10738, which has more discussion on it.
