### ISSUE TITLE
DevDocs: Comment Details block is missing its details

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#16583]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/comment-detail

#### What I expected
To see example comments

#### What happened instead
Empty comment blocks

cc: @copons PR #16415 is the likely culprit

#### Browser / OS version
Seen here in Linux Chrome, but observed across the board

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/7233112/28629603-e240669e-71f5-11e7-8f23-a61d2649939c.png)

Same screenshot from yesterday:
![image](https://user-images.githubusercontent.com/7233112/28629703-36b95e60-71f6-11e7-88a6-06512216208f.png)

#### Context / Source
#automated-testing

**Comment by Copons** [comment]
Thanks for catching this @hoverduck, and I'm deeply sorry I keep forgetting about the docs when pushing breaking changes. :(
