### ISSUE TITLE
Editor: cannot paste into caption

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1658]
Raised by @kriskarkoski 

Text cannot be pasted into an image caption. Same behavior exists in WP Admin.

![pasting into caption](https://cloud.githubusercontent.com/assets/1900444/10555158/fd395eb0-7427-11e5-8bf6-4f3ea425164b.gif)

cc @lancewillett who found while looking into 11205-gh-calypso-pre-oss

Also reported at
- https://en.blog.wordpress.com/2015/11/16/new-high-speed-editor/comment-page-2/#comment-225318
- https://en.forums.wordpress.com/topic/editor-feedback/page/21?replies=621#post-2506611

**Comment by jessefriedman** [comment]
I've experienced the same thing on my personal jetpack powered website.

**Comment by aduth** [comment]
Noting that this issue is present in the WP Admin post editor, so we should submit an upstream patch when a resolution is reached.

**Comment by lancewillett** [comment]
Confirmed fixed! Thank you @aduth. Testing with Mac-n-Chrome on local branch with URL like http://calypso.localhost:3000/post/lancetest35.com/1720

The pasted clipboard content is added directly to the caption, as expected.

<img width="1128" alt="screen shot 2016-03-11 at 11 11 03" src="https://cloud.githubusercontent.com/assets/66797/13711088/0ab56e88-e77a-11e5-87b0-7242bd7745fc.png">

**Comment by aduth** [comment]
We should keep this open 'til #3986 is merged.

(Contains "fixes" shorthand, so will be auto-closed appropriately)

**Comment by ryanboren** [comment]
I had a moment of frustration with this today.

![screen shot 2016-04-14 at 11 17 51 am](https://cloud.githubusercontent.com/assets/2047747/14538997/fff8cd3e-0243-11e6-9e2e-68da97a514cd.png)

**Comment by KokkieH** [comment]
Reported by a user in 751267-f and I also confirmed it on a test site, Firefox on Mac.

**Comment by kristarella** [comment]
Did #3986 get merged yet? Reported by user in 472845-chat. Was able to reproduce problem.

**Comment by aduth** [comment]
@kristarella : No, this issue has not yet been resolved. There was parallel effort going on in Core ([Trac #36211](https://core.trac.wordpress.org/ticket/36211)) which hasn't had much progress. We may instead try to fix it within Calypso directly and push an upstream patch proposal.

**Comment by aduth** [comment]
Closed by #13347 (cc @michaeldcain)
