### ISSUE TITLE
Store: WooCommerce: Enabled toggle in header doesn't scroll with rest of dialog content

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16599]
The enabled toggle on things like the shipping method dialog doesn't scroll with the rest of the dialog content (observed on master as well as #15718 )

![enabled-scroll-oops](https://user-images.githubusercontent.com/1595739/28638346-741ed20a-71f9-11e7-942b-8a7c91766840.gif)

**Comment by budzanowski** [comment]
#15718 has a lot of changes that were introduced after you have created this Issue that target scrolling behavior. I have tested with Chrome, FireFox, and Midori; all latest version and I have not observed the behavior shown in issue. @allendav can you confirm with the latest master?

**Comment by justinshreve** [comment]
I can confirm I am no longer seeing this in master or production.
