### ISSUE TITLE
Store: Payments section of the setup checklist is checked on fresh installs

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#16616]
![checked](https://cldup.com/mYCLn_GeBC-3000x3000.png)

This screenshot is from a 100% fresh install. All I've done is click the store menu item and input my address.

A section should only be checked after the user has visited it.

**Comment by justinshreve** [comment]
It looks like this is happening because PayPal gets auto-enabled on install :(. Just like check was. We will probably need something like this: https://github.com/woocommerce/wc-api-dev/blob/master/hotfixes/wc-api-dev-cheque-defaults.php

**Comment by justinshreve** [comment]
Patch up here: https://github.com/woocommerce/wc-api-dev/pull/39

**Comment by justinshreve** [comment]
The API patch has been merged.
