### ISSUE TITLE
Store: Remove link to wp-admin in plugin management

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#16614]
If someone were to install WooCommerce (and trigger AT) it's possible they could miss the fact they can manage their store in Calypso due to the "Settings" button which shoots them over to wp-admin

![settings](https://cldup.com/7t81-CtnW1-3000x3000.png)

Ideally we should just change the destination of that button to `/store/:site`

**Comment by kellychoffman** [comment]
Let's leave this until we have a more fully featured Store to offer.

**Comment by kellychoffman** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/19757
