### ISSUE TITLE
Store: Visiting wp-admin on a fully configured store leads to lots of notices

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16627]
If you visit wp-admin for any reason after fully configuring a store you are presented with alot of notices:

![screen shot 2017-07-26 at 14 34 14](https://user-images.githubusercontent.com/551898/28678553-eba1a0aa-72ad-11e7-88db-c181160f15b7.png)

**Comment by justinshreve** [comment]
Adding a note from our chat last week:

> Jetpack has an endpoint where you can update options that are whitelisted. Can this help with notices, like the WooCommerce setup wizard?

**Comment by timmyc** [comment]
Documenting a few different state's and their associated wp-admin notices that are shown.

Up first an existing business site on wpcom that installs a plugin, then installs store, but store setup has yet to be completed in Calypso:

<img width="1198" alt="dashboard_ _trout_bummin_ _wordpress" src="https://user-images.githubusercontent.com/22080/31580046-c4092f92-b0f9-11e7-9919-ff661251de88.png">

**Comment by timmyc** [comment]
So the last screen shot was from an AT migration that appears to have somehow gone awry and woo was never installed - take 2 - notices pre-dashboard wizard setup:

![dashboard_ _site_title_ _wordpress](https://user-images.githubusercontent.com/22080/31620285-b0494322-b24b-11e7-8737-bbe81763f9d0.png)

And after dashboard setup

![dashboard_ _site_title_ _wordpress 2](https://user-images.githubusercontent.com/22080/31620295-b7643554-b24b-11e7-8ce8-54f1067c1276.png)

**Comment by justinshreve** [comment]
Hmm. I thought the setup wizard wouldn't display anymore with this logic:

https://github.com/woocommerce/woocommerce/pull/16711/files#diff-8fe338fa3821970099766ecf56c6fa58R239

Both of these options *should* be set after our setup flow:

https://github.com/woocommerce/woocommerce/pull/16711/files#diff-8fe338fa3821970099766ecf56c6fa58R216

I guess the notice was already previously registered, and a `remove_notice` might need called.

**Comment by timmyc** [comment]
Yeah that must have just not been synched or a problem with the person taking the screenshot :) - here is the view after the dashboard wizard has been completed:

<img width="1234" alt="dashboard_ _trout_bummin_ _wordpress" src="https://user-images.githubusercontent.com/22080/31696089-b697b542-b363-11e7-8355-d372844593fa.png">

**Comment by timmyc** [comment]
Noting here that we will be able to turn off the other stripe notices when 4.0 is shipped: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/woocommerce-gateway-stripe.php

**Comment by timmyc** [comment]
Saw yet another notice today - seems like we should hide this one as well:

<img width="1088" alt="edit_plugins_ _timmy_s_flies_ _wordpress" src="https://user-images.githubusercontent.com/22080/32115544-14193c64-bafc-11e7-987f-999202f39dc4.png">

**Comment by timmyc** [comment]
In-lieu of keeping this old issue open, I'm going to close it out and since notices are moving targets - create new issues when new notices pop up.
