### ISSUE TITLE
Store: The setup-payments option in the initial flow starts pre-checked

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16625]
When you go through the initial Store setup phase the setup payments section of the list pre-checks because we pre-configure some payment options.

This feels confusing and doesn't encourage you to go in and verify things like the pre-configured Paypal payment option are set to a suitable paypal account.

**Comment by justinshreve** [comment]
@jameskoster Beat you to it 😄. Logged over at #16616.
