### ISSUE TITLE
Store: Cheque payments configuration options not fully exposed

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16629]
I enabled cheque payments on my store.

The Cart says this:

![screen shot 2017-07-27 at 09 36 05](https://user-images.githubusercontent.com/551898/28678974-090ef6f0-72af-11e7-82cb-45bb7e8e2373.png)

Looking in the Store admin I have these options for configuring Cheque payments:

![screen shot 2017-07-27 at 09 36 48](https://user-images.githubusercontent.com/551898/28679010-2285af5c-72af-11e7-8908-b44961865566.png)

In wp-admin I have these

![screen shot 2017-07-27 at 09 37 02](https://user-images.githubusercontent.com/551898/28679022-2dbcdf08-72af-11e7-8cb3-716668843445.png)

**Comment by kellychoffman** [comment]
This isn't good. We should redesign this as well. In the meantime, we should disable this payment option until its fixed.
