### ISSUE TITLE
Store: When adding products during initial setup we don't have a clear path to the next step

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16626]
When you go throught the 5 step setup process for a new store there isn't a clear route back from adding products to the setup process.

**Comment by kellychoffman** [comment]
Jay also mentioned in #15648

> The very first time a user publishes a product we should probably redirect them back to the dashboard so they can continue with the store setup process. Can we check that that's where they came from and only redirect if so? Hopefully we can still display the success message there.

**Comment by jameskoster** [comment]
I think we have two viable approaches to this issue which is, imo, a smaller issue within our entire setup process.

I've already prototyped both of these;

The first is to streamline the current checklist/setting behaviour. IE you always return to the checklist when you save something and we remove the sidebar so there's nowhere to get lost

Protoype: https://automattic.invisionapp.com/share/49CO86T7T#/244686827_Screen_Shot_2017-07-20_At_10-21-47

The second is to remove the checklist altogether. Customers are simply funnelled through each screen sequentially;

Prototype: https://automattic.invisionapp.com/share/BYCQ0HTZ3#/screens/244966568_Gather_Store_Data

A re-imagined setup flow should probably be an epic, with this issue inside it. @kellychoffman we need to discuss / prioritise this :)

**Comment by kellychoffman** [comment]
I'm thinking we need to make iterative changes here. 

> The first is to streamline the current checklist/setting behaviour. IE you always return to the checklist when you save something and we remove the sidebar so there's nowhere to get lost

This solves getting back to the dashboard bit, but is problematic for How would you view the product you just created? What if we change our success message to be always present and include a 'back to dashboard' link? We could use the design I made in https://github.com/Automattic/wp-calypso/issues/15693, and just add the extra link.

**Comment by jameskoster** [comment]
Sounds good, let's do that to begin with.

**Comment by kellychoffman** [comment]
Updated design: 

<img width="837" alt="screen shot 2017-07-28 at 10 15 17 am" src="https://user-images.githubusercontent.com/5835847/28726277-d6aab2ce-737d-11e7-833a-bf01cdb290b5.png">
