### ISSUE TITLE
Settings: WordPress.com Toolbar settings should probably go in "general"

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#16631]
I noticed the toolbar settings lives in the "writing" section of settings. This isn't specifically writing related, I think it would make more sense in "general".

![toolbar settings](http://cld.wthms.co/uBxV1m+)

**Comment by flootr** [comment]
I'd like to work on this one if that's okay for everyone already involved?

**Comment by tyxla** [comment]
Note - if we update this in WordPress.com settings, we'll need to update it in Jetpack (the plugin) too. FWIW, there's no "General" tab there right now.

cc @Automattic/jetpack

**Comment by flootr** [comment]
Ah, I see. So we should wait for feedback from the Jetpack team - on whether to introduce a new _General_ tab there - I guess?

Seems there's already an issue: https://github.com/Automattic/jetpack/issues/7312

**Comment by tyxla** [comment]
Yes, it totally makes sense to coordinate with them. Also cc @rickybanister @MichaelArestad for opinion.

**Comment by rickybanister** [comment]
There's some other work happening around settings at the moment driven by @shaunandrews. I'm working to sync up with him before making a decision about adding a general tab to the jetpack plugin. 

In general I support the idea since I'd like to see Jetpack and Calypso be exactly the same, we just need to make sure that's where we're heading.

**Comment by nielslange** [comment]
@rralian This issue seems to be resolved in the meantime. Guess this issue can be closed, right?

<img width="760" alt="screenshot 2018-12-20 at 14 35 54" src="https://user-images.githubusercontent.com/3323310/50270599-ab60cf80-0464-11e9-96f6-5fe5db0001f1.png">

**Comment by flootr** [comment]
Just checked WP.com and the original issue described still shows for me that way for a Jetpack connected site

<img width="365" alt="screenshot 2018-12-20 at 08 39 24" src="https://user-images.githubusercontent.com/9202899/50270738-dfbb9800-0432-11e9-8c64-9de9c4a6046e.png">

@nielslange your screenshot shows the _General_ section, not _Writing_.

**Comment by tyxla** [comment]
Also, I confirm it is still the case in Jetpack:

![](https://cldup.com/SxlHowL7ye.png)

and when we move settings along the settings pages, we try to keep them in sync.

**Comment by flootr** [comment]
Seems to be resolved. I couldn't find any WP.com toolbar setting in the Writing section of both WP.com and Jetpack.

**Comment by tyxla** [comment]
Reopening; it's still there for Jetpack sites under `/settings/writing/:site`:

![](https://cldup.com/DUGNe7sqfj.png)

**Comment by flootr** [comment]
> Reopening; it's still there for Jetpack sites under /settings/writing/:site:

Ah! I was looking in the plugin settings in wp-admin because when I click on `Writing` on .com for a Jetpack-connected site I'm redirected to `wp-admin/options-writing.php`. Going directly to `settings/writing` shows that setting (not for simple and AT sites though).

**Comment by halleshubham** [comment]
<img width="1293" alt="Screenshot 2022-07-01 at 12 46 30 AM" src="https://user-images.githubusercontent.com/3984908/176759752-81aea8f7-fc22-432f-9115-3e238286a209.png">



I don't see this now, should be closed? Or I've misunderstood ?

@tyxla

**Comment by tyxla** [comment]
@halleshubham thanks for asking - the section is still there, but as before - it appears only for Jetpack sites. So, still valid IMHO.

**Comment by halleshubham** [comment]
@tyxla can you tell me if there's way to simulate a Jetpack site on local calypso setup?

**Comment by halleshubham** [comment]
I was able to simulate, thanks @tyxla - will give this issue a try

**Comment by tyxla** [comment]
Thanks @halleshubham, let me know if you need anything in the meantime!

**Comment by halleshubham** [comment]
@tyxla Here is Pull Request: https://github.com/Automattic/wp-calypso/pull/65332

Is it automatically into Automattic's workflow, or do I need to do anything more to make it happen ?

**Comment by tyxla** [comment]
> Is it automatically into Automattic's workflow, or do I need to do anything more to make it happen ?

Thanks for the contribution @halleshubham - I've run the checks on your PR and taking a look now.
