### ISSUE TITLE
Store Orders: Display collected tax on order details

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16634]
It's missing presently:

<img width="749" alt="screen shot 2017-07-27 at 10 06 03 am" src="https://user-images.githubusercontent.com/1595739/28682900-7fc87c0e-72b3-11e7-8da7-c202518c1f0c.png">

Should probably also show it on a per line-item basis

**Comment by justinshreve** [comment]
Per Slack, #16635 added the bare minimum -- but we need more work here. Showing shipping tax, not displaying things when we shouldn't, etc.

**Comment by allendav** [comment]
Props @westi for noting shipping tax, e.g. non-free shipping is taxable in _some_ states (like WA).

Here's how it looks in wp-admin/WooCommerce core:

<img width="760" alt="screen shot 2017-07-27 at 10 28 37 am" src="https://user-images.githubusercontent.com/1595739/28683940-667bbec4-72b7-11e7-9fd1-dd52620f77b2.png">

The design will need to take that into account

**Comment by amandainjames** [comment]
I want to display customer information on order page. I have added this code in functions.php but the information is not displayed on order page. 
This is the code that I have seen on [WooCommerce get orders](https://www.wpblog.com/display-woocommerce-customer-order-details/) tutorial
function order_customer_information( $order ){
    global $post;
    
 $customer_user = get_post_meta( $post->ID, '_customer_user', true );
    echo '<p><strong style="display: block;">'.__('Order Customer name').':</strong> <a href="user-edit.php?user_id=' . $customer_user . '">' . get_user_meta( $customer_user, 'customername', true ) . '</a></p>';
}
