### ISSUE TITLE
Sharing: Facebook avatar broken

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#1663]
When I go to `/sharing/$site` and then toggle the Facebook sharing item, my avatar doesn't display.

<img width="744" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/1126811/11834181/942c24f6-a38f-11e5-9976-3c18c7071609.png">

After getting the source of the link, which looks something like `https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpa1/v/t1.0-1`, I get this error:

```
An error occurred while processing your request.
```

**Comment by aduth** [comment]
@ebinnion : Can you check whether this is still an issue for you?

**Comment by ebinnion** [comment]
Yes, I am still seeing the same issue. Here is the error that was in the console.

```
https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpa1/v/t1.0-1/s200x200/725…158a3fb2cb&oe=56100E54&__gda__=1443821678_a89741572bf2dfce46b8f249bb7a7fba 
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

**Comment by ebinnion** [comment]
Chatted with @aduth today in Slack. It seems that cycling the Facebook sharing connection cleared this issue up, so I'll go ahead and close.
