### ISSUE TITLE
Editor: Post Publish Preview doesn't work if X-Frame-Options: sameorigin set

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#16640]
#### Steps to reproduce
1. Create/edit a post (from https://wordpress.com) on a site with `X-Frame-Options: sameorigin` set
2. Publish/update

#### What I expected

To see preview of published post

#### What happened instead

Preview never appeared. Instead, in console:

```
Refused to display 'https://example.wordpress.com/2017/07/27/foo/?preview=true&iframe=true&revision=38&calypso_token=aaa' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
GET https://example.wordpress.com/2017/07/27/foo/?preview=true&iframe=true&revision=38&calypso_token=aaa net::ERR_BLOCKED_BY_RESPONSE
```

#### Context / Source

Note: the Preview button in the editor works properly, so something must just not be being set properly for the post publish preview case.

#dogfooding

**Comment by mattsherman** [comment]
Fixed by #16652

**Comment by kriskorn** [comment]
The same thing is happening again.
User report: 1448261-zen
More information: p1538118294000100-slack-calypso

**Comment by coder-karen** [comment]
This is also happening here: 1768242-zen.

Specifically it is with the 'View Site' option  - browser console shows `X-Frame-Options: sameorigin` set.

**Comment by GeoJunkie** [comment]
This is happening on 11589849-hc

It happens when Preview is clicked, but occurs for some users/browsers and not others. 

More information: p1553629384125600-slack-livechat

**Comment by joeboydston** [comment]
Also happening here:
2187674-zen

"View Site" in Calypso is not working for this site:
https://informa-tic.fr/

**Comment by lancewillett** [comment]
This should be fixed today, as more work has gone into the Previews in late 2019 and early 2020.

Please start a new issue if you see more reports.
