### ISSUE TITLE
Store Orders: Tax isn't included in refunds on line items

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16645]
For orders with tax collected, you can't refund the tax:

<img width="1229" alt="screen shot 2017-07-27 at 11 57 58 am" src="https://user-images.githubusercontent.com/1595739/28687315-f7f1668c-72c2-11e7-9f6a-90006ccebdae.png">

See also #16634

**Comment by ryelle** [comment]
Do you mean that tax isn't included when refunding an item by using the quantity input?
