### ISSUE TITLE
Editor: tag dropdown unclickable in Chrome & Safari

### ISSUE THREAD

**Issue by danieldanilov** [Automattic/wp-calypso#1664]
User reported having issues with selecting specific tags from the dropdown by clicking on them. They're only able to select it by scrolling down to the tag (via up/down keys) and clicking "Enter".

I've tested this and was able to reproduce it (Chrome, Safari, Mac). It works fine on Firefox.

1. Go to http://wordpress.com/post/
2. Click on the tags and open up the dropdown.
3. Try to click on one of the tags with your mouse - the dropdown closes but tags are not added.
4. Open the dropdown, and use up/down keys to scroll, and click enter - drop down closes and the tag is added.

Chrome: 47.0.2526.106 (64-bit)
Safari: 9.0.2 (11601.3.9)
Firefox: 38.0.5

**Comment by kriskarkoski** [comment]
Looks like this was fixed somewhere along the way, adding tags by mouse works fine in Chrome 49.0.2 and Safari 9.0.3 for me. Please reopen if this still happens for you.
