### ISSUE TITLE
Store: Don't auto enable check payments

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16658]
When one first visits the "Dashboard" after setting up a new Store in Calypso, the "Setup Payments" is already marked as done ( has a check in the box ).  It appears that by default PayPal is configured with the account email address ( nice! ) - but it also seems that the "Mail Check" payment method is enabled too, as it was shown as an option in checkout.

But the option is not shown in Calypso:

![payment_settings_ _care_for_animals_ _wordpress_com](https://user-images.githubusercontent.com/22080/28693981-3768e7d6-72dc-11e7-8e93-48281ce6f68e.png)

You have to visit `wp-admin` to disable/modify the payment type.

**Comment by kellychoffman** [comment]
Just noticed this while recording my demo - @justinshreve we should fix this in next week's sprint. I added it.

**Comment by kellychoffman** [comment]
This is how it looked at checkout: 

<img width="711" alt="screen shot 2017-07-27 at 3 57 27 pm" src="https://user-images.githubusercontent.com/5835847/28694269-eb09e412-72e5-11e7-9e61-d4afb7dcffa3.png">

**Comment by timmyc** [comment]
And the description of send check to store name is only editable via wp-admin as well.

**Comment by justinshreve** [comment]
@kellychoffman Agreed. When we removed checks last minute, I didn't realize that it was auto enabled :(.

Solving #16629 would solve this by adding back in the row with the enable/disable toggle. Do we need to do anything else?

**Comment by kellychoffman** [comment]
> Do we need to do anything else?

We also need the description field.

**Comment by kellychoffman** [comment]
Can we prefill the description field with the Store's address? 

"Please send a check to {Store location}"

**Comment by justinshreve** [comment]
Okay -- so there is now a PR open that adds the check payment method back in and lets you enable/disable and configure. I've updated the title of this one, so we can use it to fix the following issues:

* Prevent checks from getting auto-enabled
* Prefilling store address

**Comment by kellychoffman** [comment]
> Prefilling store address

When we do that, can we remove the placeholders and add actual this as a value entered?

**Comment by justinshreve** [comment]
This should be solved for new sites going forward per the merged `wc-api-dev` PR.
