### ISSUE TITLE
Reader: Share menu has alignment issues (if you only have one site?)

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#16655]
When testing creating a new account, I noticed that the Reader's "Share" menu has some alignment problems. If I compare to an existing account though, I don't see the problems. Hypothesis is that if you only have 1 site, then there are some padding/margin issues coming into play which you don't see if you have more than 1 site.

![screen shot 2017-07-27 at 3 35 37 pm](https://user-images.githubusercontent.com/108942/28693494-2ede47c2-72e2-11e7-906d-8cd148927156.png)

Can be seen either in the main reader stream, or from a single post. Observed with Chrome/OSX.

**Comment by fraying** [comment]
Thanks, @beaulebens! 

It's been forever since we worked on the Share menu. Anyone know this code well? @bluefuton or @blowery ?

**Comment by bluefuton** [comment]
Thanks for the report @beaulebens! I'm able to repro in Chrome with one site, but all looks good in Safari:

<img width="419" alt="screen shot 2017-07-28 at 17 00 37" src="https://user-images.githubusercontent.com/17325/28725814-8e096de2-73b6-11e7-85c1-0096774ba928.png">

@jancavan would you mind having a peek? Looks like we just need to tune the height/margin on `sites-popover__header`.

**Comment by jancavan** [comment]
This issue no longer exists as new popover style has been rolled out: https://github.com/Automattic/wp-calypso/pull/17087
