### ISSUE TITLE
Posts previews don't show up after publishing/updating them

### ISSUE THREAD

**Issue by dromero20** [Automattic/wp-calypso#16651]
paulobrien.com is having a problem with the automatic previews after editing/publishing a new post/page on Calypso. It get stuck on _One moment please - Loading your post_. However, the preview works nicely if you click on the "Preview" button right next to Update.

Here are the errors shown after taking a look at the console inspector:

<img width="1661" alt="https" src="https://user-images.githubusercontent.com/23258551/28692204-e7e951ca-731f-11e7-922f-8f0f987011c8.png">

Steps to reproduce
1. Starting at URL: paulobrien.com
2. Edit/Add a Post/Page
3. Click on "Update" or "Publish"

What I expected
A preview of the edited/published post should show up.

What happened instead
Nothing happens. A screen saying _One moment please - Loading your post_ is stuck. 

Browser / OS version
Tested on Mac OS 10.12.5. Safari, Google Chrome and Firefox.

**Comment by lancewillett** [comment]
Could you re-test @dromero20 ? I think we fixed this quite a while ago. I'm closing, but feel free to re-open if you can still repeat it.

**Comment by dromero20** [comment]
Perfect! it's working now. Sorry for bringing this up after so much time, I didn't see any report of fixing this issue. Thanks! :D
