### ISSUE TITLE
Store: Shipping Settings Visual Oddity

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16657]
While setting up a shipping method in the Store, the modal dialog has a strange grey bar to the right of the fields:

![shipping_settings_ _site_title_ _wordpress_com](https://user-images.githubusercontent.com/22080/28693839-9fe3f7b6-72db-11e7-9660-e9af0c387cf3.png)

The visual oddity does not affect functionality, it just looks _odd_.

**Comment by kellychoffman** [comment]
Agree! @jameskoster will your modal PR fix this?

**Comment by jameskoster** [comment]
Yes, although there's another issue; that sticky enable toggle;

![toggle](https://cldup.com/I1VD0exri5-3000x3000.png)

I'll fix that in the modal PR.
