### ISSUE TITLE
Store: Stripe Statement Descriptor Not Editable

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16659]
When setting up the Stripe payment option in the calypso store, the "Statement Descriptor" is not editable via the user interface:

![payment_settings_ _care_for_animals_ _wordpress_com](https://user-images.githubusercontent.com/22080/28694036-71ce39f8-72dc-11e7-8450-eea3a22a3017.png)

After placing a test order, I had assumed the "business details" from Stripe would have been used in the transaction, but the "Statement Descriptor" was still used from woo:

![payment_of__5_00_from_timmy_crawford_-_timmydcrawford_gmail_com_-_gmail](https://user-images.githubusercontent.com/22080/28694090-a8082182-72dc-11e7-969c-d79501a7dfa6.png)

In order to change this setting, I had to visit wp-admin which for a completely new user is not very intuitive.

**Comment by kellychoffman** [comment]
> After placing a test order, I had assumed the "business details" from Stripe would have been used in the transaction

Agree that we should pull these in. Adding this to next week's sprint as well.

**Comment by timmyc** [comment]
Verified changing via wp-admin had the desired outcome, correct descriptor showed in email from stripe on another order

**Comment by allendav** [comment]
@kellychoffman @timmyc - the existing extension defines no default descriptor - seems like maybe we could suggest one based on the site name?

Also note-able from stripe's docs: "Note that although we enforce a maximum of 22 characters, most banks truncate this information or display it inconsistently. Some banks may not display any descriptor information at all."

**Comment by timmyc** [comment]
I think site name and/or domain name would be ideal.  Just speaking from experience trying to remember what was purchased when looking at credit card statements.
