### ISSUE TITLE
Store Orders: Discount line can seem misleading on detail page

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#16662]
<img width="741" alt="screen shot 2017-07-27 at 6 56 36 pm" src="https://user-images.githubusercontent.com/541093/28695555-cee2bcce-72fd-11e7-9105-7b81185a6b5c.png">

In the above example, the product is originally $17.99, and was discounted $2.70 before being displayed. This isn't clear, so if you try to do the math it _looks_ like we're never applying the discount. In wp-admin, it's displayed like so:

<img width="743" alt="screen shot 2017-07-27 at 7 05 54 pm" src="https://user-images.githubusercontent.com/541093/28695678-a7af4298-72fe-11e7-80ea-e1fca222784e.png">

I know coupons are not a priority, but we are displaying discounts on the details page already, so I wanted to bring this up now (since I got myself confused 😆 ).

**Comment by kellychoffman** [comment]
Glad you brought this up, because coupons are a priority for Q3.

**Comment by ryelle** [comment]
@kellychoffman I'm thinking about how this should behave with the new order creation screen - on the mockup there's a space to edit this discount value:

<img width="168" alt="screen shot 2017-12-13 at 1 34 11 pm" src="https://user-images.githubusercontent.com/541093/33955667-532fe10e-e00a-11e7-83f9-51b7a294b736.png">

But I think this value should be read-only or hidden entirely – it's the sum of discounts applied to the order via coupons/promotions (which will be editable by applying or removing coupons). Instead we should show the discounts on each product as applicable. Would you or @jameskoster be able to make a mockup of how you think this should look?

**Comment by jameskoster** [comment]
Hmm, I think it's still worth showing the discount row as a total. Making it read only makes sense from a technical perspective but seems a shame for usability. I can imagine a store owner wanting to quickly apply a discount to an (pending payment) order and having to create a coupon to do that feels long winded...

For now, I suppose read-only is fine. But down the road we might consider having the field conditionally editable (or have some inline validation) when coupons have been applied to the order.

Do you think it's important that the user knows the discount value specifically? Or could we do something like this which feels more user-friendly;

![strike](https://cldup.com/tZGRwj1vWG-3000x3000.png)

**Comment by ryelle** [comment]
> I can imagine a store owner wanting to quickly apply a discount to an (pending payment) order and having to create a coupon to do that feels long-winded...

The problem is that the discount value is tied to the coupons, it's not something the store owner can just change. We could probably work something in so that the store owner can transparently give "negative fees" by editing the discount, then they're not creating reusable coupons but just giving that one customer some arbitrary discount... I ended up making a new issue for this: #21000 

> Do you think it's important that the user knows the discount value specifically?

No, I think that's perfect 👍 do you think it really needs the background color, though?

**Comment by jameskoster** [comment]
> do you think it really needs the background color, though?

Oh, no! I just did that in the inspector and Calypso applied style to the `ins`. We don't need the bg.
