### ISSUE TITLE
Store: Stale State on Orders Page

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16666]
#### Steps to reproduce
1. Visit `/store/orders/` at least once, and navigate away from the orders page, visit stats or something
2. Place an order
3. Note order email arrives in your inbox
4. Go back to calypso tab, navigate back to `/store/orders`, note the new order is not displayed 
5. Do a hard refresh, and the order will be shown

#### What I expected
The new order to be displayed when I visited the page.  Seems like the orders are not re-queried upon visiting the page.

#### What happened instead
The new order was not shown until I did a hard refresh.

#### Browser / OS version
Mac / Chrome

**Comment by allendav** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/16441 ?

**Comment by timmyc** [comment]
@allendav indeed it is, will add a few more comments there.
