### ISSUE TITLE
Store: Stats Period Filter Missing Value

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16667]
When viewing a store's stats on a smaller viewport, the period value ( Day, Week, Month, Year ) turns into a drop-down.  The drop-down's selected value is not displayed though:

<img width="438" alt="stats_ _care_for_animals_ _wordpress_com" src="https://user-images.githubusercontent.com/22080/28697246-4e303a92-72ef-11e7-90c8-1909c03643a2.png">

contrasted against the site stats page:

<img width="414" alt="stats_ _care_for_animals_ _wordpress_com" src="https://user-images.githubusercontent.com/22080/28697263-66c6fe42-72ef-11e7-9d02-9c3e0bbaae87.png">

**Comment by justinshreve** [comment]
cc @psealock @greenafrican
