### ISSUE TITLE
Store: Stripe: Don't make me aggree

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#16664]
Navigate to https://wordpress.com/store/settings/{site}
Click on the Setup button for Stripe
Note the spelling of agree in the Apple Pay section

<img width="660" alt="screen shot 2017-07-27 at 4 45 21 pm" src="https://user-images.githubusercontent.com/1595739/28696543-0f2e7268-72eb-11e7-9f98-e489e67e3ae0.png">

**Comment by kellychoffman** [comment]
In wp-admin, we also link to stripe and apple's TOS.
