### ISSUE TITLE
Store: Order Link in Email Goes to wp-admin

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16660]
Order emails that are sent to the store owner from a Calypso Store link the order ID to `wp-admin` and not the order management screen in Calypso:

![_care_for_animals__new_customer_order__51__-_july_27__2017_-_timmydcrawford_gmail_com_-_gmail](https://user-images.githubusercontent.com/22080/28695198-a90e86f6-72e2-11e7-9db4-01e35b9799db.png)

I expected this link to open the management screen in calypso.

**Comment by kellychoffman** [comment]
> I expected this link to open the management screen in calypso.

Agree. We shouldn't be sending anyone back to wp-admin and right now this is their only indication they have received a new order unless they log back into their dashboard. 

@justinshreve - do you think this is something we can do fairly easily? I think its high priority enough to tackle next week.

**Comment by justinshreve** [comment]
I already know it'll have to be done in an `wc-api-dev` hotfix, since those come from core WC but we should be able to either hook into the template or overwrite it -- I haven't looked to see what yet.

**Comment by justinshreve** [comment]
There is code for this in #34. I didn't get it merged into `wc-api-dev` but we splitting these types of fixes out into a separate plugin and we can merge it into there when ready.

**Comment by justinshreve** [comment]
This has been merged into the plugin in https://github.com/woocommerce/wc-api-dev/commit/de465e75be4fa6b9a8acfcf79671a3c739d2424d.
