### ISSUE TITLE
Store: Zones - After adding a state, the list of states disappears

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#16674]
* Add zone
* Select US
* Select specific state (radio)
* Choose state
* State list vanishes

It seems that when you choose the state, the country is un-selected. Here's a gif;

![state](https://cldup.com/L7tH1J1BAI.gif)

The zone still gets added when you save, with (seemingly) the correct location;

![added](https://cldup.com/JycaprK4yT-3000x3000.png)

But when you edit, the location is missing;

![no-location](https://cldup.com/IhzHpcX2yH-3000x3000.png)

**Comment by kellychoffman** [comment]
Dupe. Closing this in favor of https://github.com/Automattic/wp-calypso/issues/16661
