### ISSUE TITLE
People: use <SelectDropdown>

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#1667]
Why not use the `SelectDropdown` component for the user roles select?

![image](https://cloud.githubusercontent.com/assets/548849/11841291/96db56aa-a3fc-11e5-988a-5e45d50e741e.png)

cc @rickybanister @ebinnion

**Comment by ebinnion** [comment]
I don't believe there was a specific reason. On that note though, should we have a `FormSelect` component if we prefer `SelectDropdown` to be used?

**Comment by mtias** [comment]
I think we could get rid of `form-select`

**Comment by rickybanister** [comment]
Make it so.

Is there a `RoleSelect` or similar component? That'd be nice since we could just make them all use `SelectDropdown` in one go.

**Comment by ebinnion** [comment]
We currently have a [RoleSelect component in People](https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/people/role-select) that I could promote to `client/components and then make the changes.

**Comment by mtias** [comment]
@ebinnion I think we should have app components like this in `my-sites` (like `<Site>`).
