### ISSUE TITLE
People: delete user should use scary button

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#1668]
The "delete {user}" button should probably use one of the scary variations:

![image](https://cloud.githubusercontent.com/assets/548849/11841316/cc52c7d2-a3fc-11e5-80d4-d320eb968c12.png)

cc @alternatekev @rickybanister

**Comment by mtias** [comment]
Also the save button could be placed in `SectionHeader`.

**Comment by alternatekev** [comment]
Yeah, and Trash isn't the right icon, either.

**Comment by rickybanister** [comment]
We should just do a scary `[REMOVE]` button next to the save in the `SectionHeader`

This was never supposed to have a trash can, we don't want to put people in the trash.

@ebinnion this is an easy clean up thing if someone is looking for a small win.

**Comment by ebinnion** [comment]
@rickybanister To clarify, are you suggesting that we move the `Save` button to the `SectionHeader` and then put the delete button beside that. Maybe something like this:

![screen shot](https://cloud.githubusercontent.com/assets/1126811/11876935/dd2284ca-a4b1-11e5-8f8c-de92ec83db67.png)

**Comment by rickybanister** [comment]
@ebinnion you're right, that's not a `SectionHeader`. 

Perhaps the best half-way solution is to make `Remove User Name` (for .com sites) and `Delete User Name` (for .org sites) a borderless scary button just to the left of the save button for now. 

We can revisit the rest of the suggestions later.
