### ISSUE TITLE
Signup: better handling of form validation

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#16684]
We should rethink how form validation is being handled in Calypso — specifically the timing of when exactly are we validating the fields in the signup page: https://wordpress.com/start/account/user

When this page is loaded we autofocus on the first field (no problem there), but since we're doing validation on _all fields_ when _any click outside the form_ takes place, it leads to a barrage of errors like this:

![signup-validation-01](https://user-images.githubusercontent.com/390760/28717597-628a27f4-739a-11e7-9c30-4e9b30ca96a6.gif)

This is especially flagrant when a user already has an account and wants to click the log in link at the bottom, and sees a red sea of errors flashing while they're being redirected:

![signup-validation-02](https://user-images.githubusercontent.com/390760/28717653-9924229c-739a-11e7-9af1-763202e412eb.gif)

Thoughts @folletto @mtias ?

Good reference on validation timing: https://medium.com/@andrew.burton/form-validation-best-practices-8e3bec7d0549#2d03

**Comment by folletto** [comment]
Thanks for pointing it out!

Totally agreed. The validation UI linked on the field should only happen on two instances:

1. The user moves away from the current field, or in some instances if the field does inline validation (but these have to be evaluated by a case by case situation, as showing an error while the user is typing is bad — as the article you linked also points out).
2. The user tries to submit the form, in which case all of them show up.

The case above is a good example of something we should fix.
