### ISSUE TITLE
Store: Don't allow Stripe or Paypal to be enabled without valid credentials

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#16692]
It's currently possible to enable stripe without supplying any credentials. 

Idea: If you click the enable toggle and valid credentials aren't already present, open the Stripe modal with the relevant inputs marked as `required`.

**Comment by kellychoffman** [comment]
@jameskoster and I chatted a bit about an ideal flow for payments setup until we get our improvements to Stripe up and running. 

Flow for a brand new user setting up their store:

1. Land on Payments step page, _no_ payments have been set up or enabled

![0 - initial visit](https://user-images.githubusercontent.com/5835847/28726709-8695fd82-737f-11e7-87d7-f3a475badf11.png)
- Note that the "enabled" toggles have been removed

2. Click Set up button and fill out the required fields: 
![1- setup and enable](https://user-images.githubusercontent.com/5835847/28727794-613b98e0-7383-11e7-91e9-862b71aed480.png)
- Note that the action button mentions 'Enable'. A brand new user on WP.com setting up their payment shouldn't have to worry about the difference between setting up and enabling at this time. 

3. If they forget to fill out something, we throw an error when the press the 'Enable' button:
![error goes here if they don t fill everything out](https://user-images.githubusercontent.com/5835847/28727878-a6dcf948-7383-11e7-84f2-b828faa17ccf.png)

4. When the merchant clicks Enable Stripe and everything is filled out, the modal closes, and the enable toggle appears toggled on in the main card, so its easy to see at a glance which payments are set up. 
![2 - stripe is setup](https://user-images.githubusercontent.com/5835847/28727891-b0e3fd9c-7383-11e7-879d-7b86eab65993.png)

**Comment by justinshreve** [comment]
I really like this flow and I think it will make setting up payments a much smoother process for new store owners.

My one question is: What happens if you set enabled back to disabled for Stripe? Do they still see the toggle & Manage button, or would it go back to just a setup button?

If it goes back to setup it will take a bit of extra work because we'll need a flag or way of telling if a method has never been touched before, which we don't currently have.

**Comment by kellychoffman** [comment]
Good question. Should have added that to the design. I was thinking they would see the toggle and manage button, since we don't want to make them set everything back up again. 

> If it displays the toggle, it will take a bit of extra work because we'll need a flag or way of telling if a method has never been touched before, which we don't currently have.

If its too much work, we could make this an iterative change and do your plan first, see how it goes and then add the toggle back in later so people can keep their changes.

**Comment by jeffstieler** [comment]
Removing my assignment as I don't think this pertains to work my team is doing.

We'll need to discuss what to do on the payment gateways screen when using the auto-configured Stripe via WCS, but I think that should be tracked separately.

**Comment by justinshreve** [comment]
Unassigning you as well Kelly since the design part of this is done, and I don't want it to look like it's claimed when it hasn't been claimed by anyone yet.

**Comment by budzanowski** [comment]
@justinshreve 

> If it displays the toggle, it will take a bit of extra work because we'll need a flag or way of telling if a method has never been touched before, which we don't currently have.

Well if the publishable and secret keys are present in redux store for selected mode of operation (live or test), and I think that we fetch them from payments API, it means that we can show the toggle.
That is my thinking.

**Comment by justinshreve** [comment]
@budzanowski That could work for Stripe for sure, though the mocks made it seem like this is something we want for every payment method.

**Comment by kellychoffman** [comment]
@budzanowski: Let's do this flow for both Paypal and Stripe.

**Comment by kellychoffman** [comment]
Reopening this so we don't forget to do the same for Paypal.

**Comment by budzanowski** [comment]
@kellychoffman You have mentioned on one of the last calls that you want to take a look at this design again? I would like to start working on Paypal but I don't know if the design is OK or not :P

**Comment by kellychoffman** [comment]
This design is good to go!
