### ISSUE TITLE
Editor: location meta not included on the front end

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1672]
Geolocation meta tags are not included in the page source if you add a location and publish a post using the Calypso editor, but it works if you set the location using the WP Admin editor.

Steps to reproduce:

1. Go to https://wordpress.com/post and add a title and some content
1. Open "More Options" in the left sidebar
1. Search for a location such as a city name
1. Select the city name and publish the post
1. View the post on the front end and search the page source for geo meta

<strong>Result:</strong> geo meta tags are not included on the front end as expected. If you set a location in WP Admin, then you can see geo meta tags such as:

```
<meta name='geo.position' content='42.360082;-71.058880' />
<meta name='ICBM' content='42.360082, -71.058880' />
```

/hat tip @obenland for the original report

**Comment by aduth** [comment]
While this was opened first, going to close in favor of #1672 where more conversation has taken place.
