### ISSUE TITLE
Store: Navigation Issue When Leaving Store Stats to Non-Store Site

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16726]
#### Steps to reproduce
1. Open up a Store Stats page for a "Store Site"
2. Using the Site switcher, select a different site which is not store-enabled

#### What I expected
I expected to see the Site Stats page for the non-store site.

#### What happened instead
I am shown a Store Stats page for the site that does not have store enabled.  I anticipated Calypso to redirect me from https://wordpress.com/store/stats/orders/week/NONSTORESITE to  https://wordpress.com/stats/day/NONSTORESITE

#### Browser / OS version
Mac/Chrome

**Comment by timmyc** [comment]
Disregard - the site I was testing against was actually a JP site with Woo installed... on that note though, should Store Stats work for "classic" wc sites?

**Comment by kellychoffman** [comment]
> should Store Stats work for "classic" wc sites?

They will, but Store Stats did a soft launch, which only included Atomic sites with WC installed.
