### ISSUE TITLE
Store: Link to get back to navigation too small on mobile

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16731]
Noted by @timmyc. 

Right now, the only way to navigate to another page on mobile is to click the `<` button in the sticky header. On mobile, the target size is way too small. We should increase this to make it easier to navigate on smaller devises.

**Comment by kellychoffman** [comment]
@jameskoster - Do you want to take a look at this?

**Comment by timmyc** [comment]
I hit this issue again last night while using the store on my Nexus5... specifically when viewing an order details page and attempting to navigate back to the order list - the click target for 'Orders' is even kind of small and I ended up hitting the > target which led me to the dashboard sidebar being active.

**Comment by kellychoffman** [comment]
Ah, okay. I'll leave it open then. Thanks!

**Comment by jameskoster** [comment]
Hmm, our back arrow on the orders screen is 40px x 40px. We can probably increase it to 46x46 (the sticky header is 46px tall total). That's not going to make a _huge_ difference but should help.

**Comment by kellychoffman** [comment]
Hmm, true true. Maybe we should increase the target size to include the name of the page.

**Comment by jameskoster** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/18243
