### ISSUE TITLE
Store: Top bar should be sticky

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16733]
Noted by @timmyc: 

>  When updating the inventory for the product, I had to scroll all the way to the top of the page to hit the ‘Update’ button. Perhaps exploring having the ‘update/nav bar’ stick/pin to the top of the screen as you scroll down might be nice – kind of like the editor.

I think this would be super helpful.

**Comment by kellychoffman** [comment]
@timmyc - Is this referencing mobile/small screen only?

**Comment by timmyc** [comment]
I definitely think this is more of an issue on smaller viewports... but I think it would still be nice to have the sticky top bar much like the editor does. Thinking orders with many items or a long activity log would also benefit from this - or just the ease of navigating from an order detail page back to the listing.

**Comment by kellychoffman** [comment]
Okay cool, just wanted to confirm. It sticks above 660px width so we can just make it stick at All The Widths.
