### ISSUE TITLE
Editor: Mobile: sidebar options are out of view if you tap the Actions button in Chrome on iOS while the cursor is positioned at the bottom of the post

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1673]
Steps to reproduce:
1. Open Chrome on iOS
2. Go to https://wordpress.com/posts and open a post with a lot of content
3. Scroll to the bottom of the post and tap to position the cursor there
4. Scroll up and tap the "Actions" button
5. Look for the sidebar options

<strong>Result:</strong> when you tap the Actions button in Chrome, it opens the sidebar in the same position and it looks like the page is just blank unless you can figure out you need to scroll all the way back to the top of the sidebar to see the options. ([33s](https://cloudup.com/ctIitCd6y7U))

![screen shot 2015-12-16 at wed dec 16 10 29 22 am](https://cloud.githubusercontent.com/assets/1119271/11845055/e3ab9da4-a3df-11e5-9467-2b1792d5e23e.png)
<sup>Chrome on iOS 9.1 using an iPhone 6</sup>

/hat tip @sandymcfadden for the original report

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue. The "Actions" button was replaced with a cog icon to bring up the post options. In step 4, tapping that cog icon at the top of the editor switches you to the top of the options sidebar without any issue.

##### Tested on iPhone 6, iOS 10.3.1, Chrome app v. 58.0.3029.83
