### ISSUE TITLE
Site Picker doesn't show loading indicator when sites are loading

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#16737]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com (you may need to throttle your connection)
2. Click My Sites
3. Note that the sites aren't shown and there's no loading indicator

#### What I expected

A loading indicator

#### What happened instead

The sites suddenly appear

#### Browser / OS version

macOS 10.12.6 Chrome Version 60.0.3112.78 (Official Build) (64-bit)

#### Screenshot / Video

![picker](https://user-images.githubusercontent.com/128826/28762169-88511722-75f7-11e7-9f68-f16f3fb9f688.gif)

#### Context / Source
#dogfooding

**Comment by rachelmcr** [comment]
I've noticed this a few times recently, and found it fairly disconcerting. At least once I didn't wait for the site list to load and just started searching for the site I was looking for (while still wondering why it didn't show up in the list).

**Comment by alisterscott** [comment]
> At least once I didn't wait for the site list to load and just started searching for the site I was looking for 

I do the same actually

**Comment by toddwilkens** [comment]
It looks like this issue doesn't occur anymore.  On the initial load, there is a placeholder ("Loading my sites") for the site picker until all the sites are loaded in the background. There's no way to press "Switch Sites" until after the sites are loaded anymore. See the attached recording.

![](http://g.recordit.co/MTf0zgVtFV.gif)

@alisterscott @rachelmcr

**Comment by alisterscott** [comment]
I am now seeing the most recent sites immediately at the top of the list. But I still don't see a loading indicator for the remaining sites which suddenly appear at some point.

@toddwilkens: I'm seeing slightly different behaviour to yours, if I refresh a screen then choose "Switch Site" I now see the recent sites at the top, but the remaining are still loading without any indicator (on first visit or after refresh) - see gif below:

![sites list](https://user-images.githubusercontent.com/128826/30525428-a0a207aa-9c49-11e7-82a9-856aea58bc32.gif)

**Comment by millerf** [comment]
Hi @alisterscott @toddwilkens ,

I have been trying to fix this bug. It is a good one as I am learning React in the same process.

I narrowed down the problem on this line:
https://github.com/Automattic/wp-calypso/blob/01e09cb2b0cb6744fa4ea57da643bef855ac52a7/client/components/site-selector/index.jsx#L271

but it seems the code is fine and provides a placeholder. 

The code has been changed 2 months ago. Could you test again? It seems this issue has been fixed by [#21446](https://github.com/Automattic/wp-calypso/pull/21446)

**Comment by alisterscott** [comment]
Hi @millerf 

Thanks for taking a look, I can no longer reproduce this, so it looks like it was fixed at that point.

Closing now.

![switch](https://user-images.githubusercontent.com/128826/37005124-9fe70e82-211e-11e8-8e90-b253c44f53f0.gif)
