### ISSUE TITLE
Editor: adding a link using toolbar causes editor to jump to top

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#16741]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Add content to a new post. Make sure it's enough content so the first line scrolls off the top of the screen.
3. Towards the end of the post, highlight some text
4. Click the hyperlink button in the toolbar and add a link.

#### What I expected
For the link to be added, but to still have the editor focused on the text I'm currently editing.

#### What happened instead
The editor jumped to the top of the post, and I had to scroll down to get back to the anchor text where I'd added the link.

#### Browser / OS version
Confirmed in latest versions of Firefox and Chrome on Mac OS X.

#### Screenshot / Video
![link](https://user-images.githubusercontent.com/11873759/28773436-cfcd5254-75e9-11e7-92d1-c4d6c55f33d3.gif)

#### Context / Source

Reported in the public forums in 871246-f

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/My_ComicRelief/status/892197664569397250)

This user reports the same thing happening when adding images, and I was able to confirm that as well.

**Comment by gemmagarner** [comment]
Another report on [Twitter](https://twitter.com/semperfidem2004/status/892014501142384640). 

Issue affecting Chrome and Edge.

**Comment by lizkarkoski** [comment]
Another report in the forums: http://en.forums.wordpress.com/topic/problem-editing-links

User is on Windows 7, and has tried Firefox 54 and Chrome.

**Comment by dcoleonline** [comment]
Reported in 614267-ZD

**Adding Images Screencast:**  https://cloudup.com/cPntWQzFD_g

**Comment by KokkieH** [comment]
Closing in favour of #16873

**Comment by KokkieH** [comment]
@dcoleonline don't know if you saw but this has been fixed in the other issue, in case you want to follow up with your user.

I'll follow up on the forum thread.
