### ISSUE TITLE
Editor: fade doesn't appear on format bar when sticky

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1675]
Raised by @kellychoffman 

![no-fade](https://cloud.githubusercontent.com/assets/5835847/10469768/1ea8066a-71c5-11e5-9e11-e2e4c682793f.gif)

**Comment by brbrr** [comment]
Not sure what the problem here. @designsimply could you check it?

**Comment by designsimply** [comment]
The problem is that the fade-out on the right side of the editor toolbar is missing when the toolbar is stuck to the top:

<img width="790" alt="screen shot 2017-12-21 at thu dec 21 3 31 52 pm" src="https://user-images.githubusercontent.com/1119271/34277786-847ec18e-e664-11e7-80de-32bafcfa7434.png">

<img width="797" alt="screen shot 2017-12-21 at thu dec 21 3 31 58 pm" src="https://user-images.githubusercontent.com/1119271/34277784-84641514-e664-11e7-820e-761cc2a8dfbd.png">

However, I think this is a minor issue and will no longer be relevant when Gutenberg arrives so I agree that it should be closed.

#bug-scrub #pre-gutenburg-bug-purge
