### ISSUE TITLE
"Create a site": underscore causes error

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#16763]
I was creating a test account and added an underscore to it. This popped u.p an error saying "Sorry, there was a problem processing your request. Please try again in a few minutes." I did find that when I omitted the underscore, the error goes away and the page behaves normally.

I did check the JS console and didn't see any errors. And I also looked at the Redux actions and didn't find a smoking gun there either.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/domains
2. Type a name with an underscore
3. View the error.
4. Replace the underscore with a dash.
5. View the application behaving normally.

#### What I expected
<img width="997" alt="create_a_site_ _wordpress_com" src="https://user-images.githubusercontent.com/945228/28787289-c2a8d148-75e9-11e7-8b4e-0c6f8ff8b0a0.png">

#### What happened instead
<img width="998" alt="create_a_site_ _wordpress_com" src="https://user-images.githubusercontent.com/945228/28787271-b1377f5e-75e9-11e7-96fb-a4a660716e06.png">

#### Browser / OS version
OSX Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by iamgabrielma** [comment]
I started to dig into this but seems I haven't found the exact problem yet. Some debugging:

Inside the `<DomainRegistrationSuggestion>` component, seems that if the domain is valid we'll move onto the next signup step, if doesn't, the warning is triggered.

This seemed to be coming from the .match(regex) here: https://github.com/Automattic/wp-calypso/blob/f0b2e14d149cc7b03f9c55f5be2f8d90a7d5226b/client/components/domains/register-domain-step/index.jsx#L346

But on my testing I changed the current regular expression for a simple `/([A-Za-z])+/` and the error we get now is different.

For example the domain  `yourdomain-` worked with the original regular expression, but doesn't work now as is not valid:

> Sorry, yourdomain- does not appear to be a valid domain name.

<img width="1144" alt="screen shot 2017-09-01 at 14 50 15" src="https://user-images.githubusercontent.com/3812076/29970657-aebda488-8f25-11e7-8f86-c5b503dcb67d.png">

However the underlying error is still there, as if I change from  `yourdomain-` to `yourdomain_` , the error message changes as per the bug report:

> Sorry, there was a problem processing your request. Please try again in a few minutes.

<img width="1127" alt="screen shot 2017-09-01 at 14 56 23" src="https://user-images.githubusercontent.com/3812076/29970692-d26975b0-8f25-11e7-9853-b5d6b73e9421.png">

This comes from `getAvailabilityNotice( domain, error )` here: https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/lib/domains/registration/availability-messages.js#L14

The difference is the case:
- `case domainAvailability.INVALID:` Sorry, yourdomain- does not appear to be a valid domain name.
- `case default:` Sorry, there was a problem processing your request. Please try again in a few minutes.

**Comment by klimeryk** [comment]
Thanks for that in-depth investigation, @iamgabrielma 🙇 And especially for adding the `Domains` label - without it, no one gets pinged and this issue went by unnoticed (of course, kudos to @coderkevin, for bringing it up in the first place 😁).
I haven't tested yet, but it'd seem that we're not handling `_` properly on the backend. A quickfix would be to replace all occurrences of `_` with `-` and send that to the backend.

As for trailing `-` or `_` - `_` is of course not allowed in domains, `-` is, but only if it's not at the beginning or end.

**Comment by klimeryk** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/19503 🎉
