### ISSUE TITLE
Store: Deleting product with dirty state will prompt you before redirect to products list

### ISSUE THREAD

**Issue by gedex** [Automattic/wp-calypso#16780]
#### Steps to reproduce
1. Create a test product
2. Update it (e.g. the description), but don't save it
3. Delete the product
4. You'll get notice product is deleted but also prompted with a dialog.

#### What I expected

Not prompted with the dialog when deleting the product.

#### What happened instead

It displays the notice that my product is successfully deleted but I also get prompted with 

> You've unsaved changes. Are you sure you want to leave this page?

 which sounds confusing because I deleted the product and nothing to save.

#### Screenshot / Video

![delete-product](https://user-images.githubusercontent.com/78313/28812840-dca16376-76c0-11e7-9c08-9b4144d839a6.gif)

**Comment by msdesign21** [comment]
You don't need to change any details on a product in order for this to show up. You can just go into a product to delete and get this message. 

Although I got the same trying to edit my Site Settings (not in Store), so maybe it's a Calypso issue?
