### ISSUE TITLE
Editor: Mobile: cannot scroll within long titles in Safari on iOS

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1679]
Raised by @rachelmcr 

What I Did:

1. Created a new post and added a long title (more than one screen width):

![2015-10-14 10 27 27](https://cloud.githubusercontent.com/assets/8658164/10490493/9f925ebc-725e-11e5-8940-cdc226f422cd.png)

2. Tried to edit the end of the post title

What I Expected:

To be able to tap and drag the cursor to the end of the title, so I could edit/erase it.

What Actually Happened:

When I tapped and dragged the cursor, it didn't scroll past the part of the title that appeared on screen. Instead, the cursor moved all the way to the right edge of the screen:

![2015-10-14 10 28 00](https://cloud.githubusercontent.com/assets/8658164/10490619/5018e256-725f-11e5-96c6-899ae83db4d3.png)

Device: iPhone 6, iOS 9.0.2, Safari

Notes from @kriskarkoski 

> Just noticed something similar while testing, where I couldn't scroll back to the beginning of the title and clicking into the content area didn't reset it to the beginning right away, but rather after a little time passed
> 
> Also, I can scroll on Chrome on iOS 9, but it feels less instant than it should be, instead accelerating the scroll rate after I hold it to one edge for a moment rather than scrolling instantly

Related: #1059

**Comment by ryanboren** [comment]
https://make.wordpress.org/flow/2015/05/26/advancing-the-cursor-through-input-fields-on-ios/
https://core.trac.wordpress.org/ticket/32502
https://make.wordpress.org/flow/handbook/glossary/#boxed-input-scrolling

**Comment by ryanboren** [comment]
https://twitter.com/rboren/status/613773854373064704
