### ISSUE TITLE
StatsPostPerformance generates invalid HTML because of changes to Emojify component

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#16798]
You can see this on Stats > Insights.

```Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See StatsPostPerformance > p > ... > Emojify > div.```

It looks like this is the place it is used:
https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/my-sites/stats/post-performance/index.jsx#L108

And this is the change that caused the error:

https://github.com/Automattic/wp-calypso/commit/1bd1f9953e8994bbca0e322ee3dc8236b6a436c7#diff-2a6f98964feb14d6f72fdcbd72b7ed96L38

**Comment by pento** [comment]
This requires upgrading to React 16, so that `render()` doesn't have to return wrap everything in a div.

See also, discussion on #14505.
