### ISSUE TITLE
Format Daily Post Special Link Like Discover

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#16810]
We currently have two kinds of special links that show up in the body of post cards in Reader.

Daily Post has the "Post About ..." link. 

<img width="835" alt="screen shot 2017-08-01 at 12 31 18 pm" src="https://user-images.githubusercontent.com/24388/28843721-13bb6bc2-76b7-11e7-903c-8b0489f23c92.png">

And Discover has a special "Follow" link.

<img width="838" alt="screen shot 2017-08-01 at 12 30 28 pm" src="https://user-images.githubusercontent.com/24388/28843796-4f3f9b1e-76b7-11e7-821d-df6fad36b308.png">

Both of these links are special bonus links we're adding to cards, but they have different styles. I'd like to simplify/standardize this. I recommend changing the Daily Post link look like the Discover "Follow" link. This simpler style is more consistent with the rest of Reader.

**Comment by benhuberman** [comment]
cc'ing @Automattic/editorial for reference (note to editors on call: this **isn't** a copy request!)

**Comment by kjellr** [comment]
Great idea!
