### ISSUE TITLE
When post has no title there is a spacing issue on view posts screen

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#16826]
You see the following if a post has no title:

![2017-08-02 at 12 20](https://user-images.githubusercontent.com/253067/28871600-3c1a810e-777d-11e7-8474-3e5c4531bf8b.png)

**Comment by designsimply** [comment]
I was unable to reproduce the problem using the following testing steps:

1. Start a new post at https://wordpress.com/post
1. Do not add a title.
1. Add some content.
1. Publish the post.
1. Go to My Sites > Blog Posts and find the post in the list.

<strong>Result:</strong> a post with no title appears normally in the Sites > Blog Posts list.

![screen shot 2017-08-02 at wed aug 2 11 18 22 am](https://user-images.githubusercontent.com/1119271/28885935-da3d7e76-7774-11e7-8fda-f216be525c4e.png)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com (WordPress.com site) using Firefox 54.0.1 on Mac OS X 10.12.5.</sup>

I also tested with a Jetpack site:

![screen shot 2017-08-02 at wed aug 2 11 19 56 am](https://user-images.githubusercontent.com/1119271/28885937-dd66d764-7774-11e7-9c75-bd7e01429a7a.png)
<sup>Seen at https://wordpress.com/posts/madefortesting.com (WP 4.8, JP 5.2) using Firefox 54.0.1 on Mac OS X 10.12.5.</sup>

@karmatosed, if I've miss something in my testing steps, please re-open and let me know!

**Comment by karmatosed** [comment]
This is sooo weird. I went to test myself, my thought was it may have to only have one post to do this. But no, it isn't an issue today. Thanks for testing and sorry for an apparent false alarm on either something that was fixed or something that was a glitch.

**Comment by designsimply** [comment]
No worries at all! Thank you for reporting the issue when you saw it!
