### ISSUE TITLE
Editor: Post/Page cannot be made Public from Calypso

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#16822]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com > My Sites > Blog Posts (Or Pages)
2. Open any Post or Page
3. Make the Post or Page `Private` via Post / Page Settings > Status
4. Try and make the Post or Page `Public` using the same popup.
5. Notice that the `Public` radio button cannot be clicked.

_Screenshot_

<img width="448" alt="8tybll" src="https://user-images.githubusercontent.com/10125810/28864656-d11f435e-778a-11e7-89ff-87a98e828f88.png">

_Screencast_
![fs8ddt](https://user-images.githubusercontent.com/10125810/28864775-36b6cc82-778b-11e7-9f2a-f2adb76c8d5b.gif)

#### What I expected
The Post or Page should become Public when you click the `Public` radio button.

#### What happened instead
The `Public` radio button could not be clicked. However, the Post/Page can be made Public again via WP-Admin.

This happens for both Simple and Atomic sites.

Please let me know if you need any other info! This was reported by users in 550124-hc and 550014-hc today.

**Comment by iannuttall** [comment]
This was also reported in 551213-hc today.

**Comment by KokkieH** [comment]
Another case in 872188-f

**Comment by jeremeylduvall** [comment]
This was also reported in #16898. I think I have it fixed in #16907. Either way, I'm going to close this issue so we have one consolidated issue for it. Will ping you all in the other issue when it's closed and resolved.

**Comment by jeremeylduvall** [comment]
@KokkieH @iannuttall @mahangu this should be fixed now!

**Comment by KokkieH** [comment]
Thanks, @jeremeylduvall
