### ISSUE TITLE
Store Stats: Search Coupons Endpoint

### ISSUE THREAD

**Issue by greenafrican** [Automattic/wp-calypso#16837]
Add API endpoint to search for coupon/s by name (id?)

**Comment by timmyc** [comment]
@greenafrican - is this a feature that you still need in the API? We might consider moving this issue, along with #16836 and #16835 to `wc-api-dev` to see if we want these features included in `v3` since it is actively being worked on right now.

**Comment by timmyc** [comment]
Looks like this already exists in the API, you can search by string [#](http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-coupons) and query by ID ( but not search )
