### ISSUE TITLE
Editor: consider handling new post/page with a permalink redirect

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1683]
Raised by @folletto 
#### Extra Idea: "Instant ID Redirect"

Also, something that we could do and would be super-safe and very comforting for the user in terms of saving their data:

`/post` → `/posts/$site/$id`
`/posts/new` → `/posts/$site/$id`

This means that every "new" endpoint is a redirect that triggers a save, so at the cost of saving "empty" documents (if it's possible) we always have for the user a proper URL that has the ID in, so can be immediately referenced and saved.

**Comment by rachelmcr** [comment]
With the current autosave implementation, as soon as the user begins to enter content in the editor we autosave the post with the relevant site and post ID in the URL. I think this covers the spirit of this idea, so I'm going to close this issue.
