### ISSUE TITLE
Store Sidebar: Menu items appear with no loading indicator

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#16858]
From @timmyc here: https://github.com/Automattic/wp-calypso/issues/16443#issuecomment-319716561

> the sidebar itself is missing some loading indicators on a hard refresh:

![28882593-8697dfd2-7760-11e7-8f41-baf610c8cdb2](https://user-images.githubusercontent.com/541093/28895838-04c07d0a-77a8-11e7-98f1-1f29e0cad539.gif)

Since we do an API request to conditionally display those links, they can flash in after a delay. So we could add a loading indicator for those links, but I'm not sure a loading indicator is the right idea — since users who shouldn't see these items don't need to know they're missing something.

Maybe we only need to ping the setup API endpoint for the sidebar if we're on `/store/:site`?

**Comment by timmyc** [comment]
Thanks for opening this separate issue @ryelle.  I think the standard used in most other calypso components is to display a loading skeleton in areas that you know are likely to be populated with content, kind of like as seen here in the reader:

![loading-indicator](https://user-images.githubusercontent.com/22080/28897596-4e42eec0-7796-11e7-9ee2-17b63ac80b40.gif)

So I would almost expect some "skeleton" table rows to be shown in the order area too, and something similar in the sidebar - kind of gives a visual queue that data is still being loaded in the areas.

**Comment by ryelle** [comment]
Right - the other issue was about the orders screen, and that was fixed (the "skeleton" added) in #16548. I created this new issue to talk about the sidebar behavior.

I know we usually use skeleton frames for loading data, but I don't think we want to do that here. What's happening here is we send off an API request to say, basically, "Can this user see the other menu items?" and if they can, the menu items appear. But I don't think we want to show a loading skeleton in case the answer is no (because they're still in setup), and we _don't_ show the menu items.

**Comment by justinshreve** [comment]
> Maybe we only need to ping the setup API endpoint for the sidebar if we're on /store/:site?

Yeah I think that's the route we should go. We only hide up until the address field is completed, where they are on `/store/:site` directly.
