### ISSUE TITLE
Path /stats/day[/+undefinded] occurring thousands of times each month

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#16864]
Paths such as the following are occurring thousands of times each month as logged by internal logs of `calypso_page_view`.
```
/stats/day/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined
```
Why might this be?

**Comment by jeremysawesome** [comment]
Just ran into this myself actually. I'm not sure what is causing it but it seems to happen every time I click on the "My Sites" button at the top left.

![undefinedforalltime](https://user-images.githubusercontent.com/2500689/29627653-a1ad25a6-87e7-11e7-8433-02e7119e5197.gif)

**Comment by yanirs** [comment]
@psealock Where does this stand now? Have the changes been reverted? I think the fix may be relevant to the tracking issues @donpark has been working on.

**Comment by psealock** [comment]
Hi @yanirs I need to further investigate this comment https://github.com/Automattic/wp-calypso/pull/17583#issuecomment-325583358

I need to understand what the difference between `currentUser.visible_site_count` and 
```js
sites[ blog_id ].map( s => s.visible ).length
```
Then I will step through the code and understand why the above comment happens and how to fix it.

**Comment by psealock** [comment]
Closed via https://github.com/Automattic/wp-calypso/pull/17731
