### ISSUE TITLE
Framework: masterbar active state with Notification has glitchy transition

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#1686]
@apeatling from #631: 

> I'm noticing an issue with the highlight state when going between items when one of them is notifications. It seems to complete the highlight state transition for the previously clicked item when going to the next item from notifications:

![nav](https://cloud.githubusercontent.com/assets/1464705/11848664/699f0bd8-a3d8-11e5-8659-acb9d4b00ed7.gif)

![licecap-](https://cloud.githubusercontent.com/assets/4389/11849070/46d09e2a-a426-11e5-814c-56513b0778b7.gif)

**Comment by lancewillett** [comment]
I can't repeat this one.

**Comment by folletto** [comment]
It's still present, even if it's slighter than before.
Reproduced on both Chrome and Safari.

![cap-](https://cloud.githubusercontent.com/assets/4389/14433375/039c6d3c-0006-11e6-8551-35689cd4e8e0.gif)

**Comment by lancewillett** [comment]
I vote to re-close. But will leave it for a 3rd opinion. :)

**Comment by drw158** [comment]
I don't understand exactly. Is this with the tabs themselves, or the content of the page? There is definitely a flash of the previous page if I click on a tab after Notifications.

**Comment by designsimply** [comment]
> I don't understand exactly. Is this with the tabs themselves, or the content of the page?

Looks like both to me, but it's hard to see in that animated gif. I had to watch the latest-posted one several times to spot the problem. Here's the gist of what I see in the gif: 

1. Start from your profile page
1. Click the notifications icon
1. Click the newspaper icon

<strong>Result:</strong> the profile page icon and header flash briefly before the Reader loads

**Comment by designsimply** [comment]
I just tested and found it's different than the original report. In my test, I found that I have to tap twice to reach the section I want after tapping notifications. See [26s](https://cloudup.com/ckoht-LQ15Q).

**Comment by folletto** [comment]
> I just tested and found it's different than the original report. In my test, I found that I have to tap twice to reach the section I want after tapping notifications. See 26s.

This is new. I just tested it too and I can reproduce. 
Different bug.

> I don't understand exactly. Is this with the tabs themselves, or the content of the page? 

It's both, since they are triggered in the same way.

Keep focused on the Me icon in latest gif above when it switches back from Notifications to Reader. You'll notice for a brief moment that the Me tab flashes active, as well as its header.

**Comment by lancewillett** [comment]
Closing for now — let's loop back in the future when we look again at the toolbar and navigation.
