### ISSUE TITLE
Editor: link modal & media modal keep scrolling up to the top

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#16873]
![2017-08-03 15 34 07](https://user-images.githubusercontent.com/4389/28926995-51dd4ffa-7861-11e7-84a7-383089659c15.gif)

When the media modal opens, the page gets scrolled up to the top.

### To Reproduce

1. Open the Editor
2. Have a long post, so it's scrolled down
3. Insert an image, or do any operation opening the media modal while scrolled down (edit).

The page will scroll up as soon as the media modal opens.

I ranked this "High priority" as it's a very frustrating disruption for anyone writing a post with images.

**Comment by designsimply** [comment]
Tested and confirmed that when I am editing at the end of a long post that requires scrolling and I insert an image I am scrolled up to the top and the image is out of view.

**Video:** [20s](https://cloudup.com/c2lnu-UwdN9)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11374 using Firefox 54.0.1 on Mac OS X 10.12.6.</sup>

**Comment by designsimply** [comment]
Could this be related to #16245?

**Comment by alisterscott** [comment]
Confirmed this issue and I can confirm it's recent since the WordPress.com desktop app doesn't contain this bug. I think we should keep the `[Pri] High` label

**Comment by KokkieH** [comment]
Also reported in #16741

This happens with the Insert Link modal as well, not just media.

**Comment by KokkieH** [comment]
Several user reports in the other issue. Adding 872899-f for follow-up.

**Comment by rachelmcr** [comment]
Could this be a side effect of the work that was done in https://github.com/Automattic/wp-calypso/pull/15718 to make dialogs (modals like these) scrollable in smaller windows? cc @jameskoster

**Comment by bisko** [comment]
> Could this be a side effect of the work that was done in #15718 to make dialogs (modals like these) scrollable in smaller windows? cc @jameskoster

Reverting the changes from the the PR locally fix the issue.

**Comment by spen** [comment]
At a quick glance I don't see any changes in #15718 that would cause a change in position other than [the updated react-modal version](https://github.com/Automattic/wp-calypso/pull/15718/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) - That'd be worth exploring.

**Comment by SiobhyB** [comment]
This was also reported in 618738-zen and I was able to replicate by inserting a link at the bottom of the page editor in the latest version of Chrome/macOS Sierra.

**Comment by jameskoster** [comment]
Sorry for the late reply, I've been afk. Looks like [this](https://github.com/Automattic/wp-calypso/blob/0345ff083bb0427b49c5101da4971e7efdfc1dbb/client/components/dialog/style.scss#L114-L116) is causing the issue.

The style was added so that the content _behind_ the dialog doesn't scroll when the dialog itself is visible.

However, that class is added intermittently. Even in the latest version of `react-modal`.

For now, the safest/quickest solution would be to simply remove that style.

**Comment by mmtr** [comment]
Reopening this issue since it is still present.
