### ISSUE TITLE
Store: Introduce a static NUX screen with a CTA to start the setup process

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#16885]
Instead of going straight into the plugin install process, let's have an additional static NUX screen with a call to action that kicks off the setup process. See Ran's comment at p6q6po-9eH-p2 #comment-87748.

I talked about this with @kellychoffman and they will prioritize design/content for this.

On the dev side, I don't think we need a new `calypso-preferences` flag or anything. If `finished_initial_install_of_required_plugins` is 0 (RequiredPluginsInstallView is being displayed), we can just hide the process behind some content with a confirmation before actually starting the process.

**Comment by kellychoffman** [comment]
First draft of an initial screen: 

<img width="852" alt="screen shot 2017-08-07 at 4 23 35 pm" src="https://user-images.githubusercontent.com/5835847/29048889-407ea6f0-7b90-11e7-94ae-a41f4d7d75ff.png">

Its still being copy reviewed by marketing, but this overall page location and action button will stay the same, if dev wants to get started on it.
