### ISSUE TITLE
Fullpost: Design Tweaks to Comment Nesting Arrows

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#16883]
Just a few design tweaks to Comment Nesting Arrows being worked on in #16770.

- The left edge of the first level avatars should align with the left edge of "X COMMENTS" and "Load more comments." (Right now it's indented by ~7px.) This is just to make it more clear what's an indented reply and what's not. Like so:

<img width="166" alt="screen shot 2017-08-03 at 11 12 51 am" src="https://user-images.githubusercontent.com/24388/28936518-d84540b8-783c-11e7-808d-16ae958a2491.png">

- "> Name" and Date font CSS should match the size, color, and hover of Like and Reply at the bottom. This is to simplify the formatting so that it's not so busy and treat all secondary links the same. Like so:

![comment-nest-example](https://user-images.githubusercontent.com/24388/28936041-50cc75da-783b-11e7-9042-eed406c6e6b7.png)

- The ">" should move up by a pixel or two, so it doesn't look like a descender. Like so:

<img width="662" alt="screen shot 2017-08-03 at 11 21 22 am" src="https://user-images.githubusercontent.com/24388/28936879-ee1b6aec-783d-11e7-911d-1fd54d2a1b5c.png">

- The top of the byline should align with the top of the avatar, the baseline of the first comment line should align with the bottom of the avatar. The horizontal space between the avatar and the text should be 10px. Like so:

<img width="941" alt="screen shot 2017-08-03 at 11 04 54 am" src="https://user-images.githubusercontent.com/24388/28936167-b8c6b93e-783b-11e7-986c-2e61b5beab34.png">

- The reply icon should align with the left edge of the comment text, and the top of the reply icon should align with the top of the "R" in Reply. There should be 15px of space between the top of "Reply" and the baseline of the last line of the comment. Like so:

<img width="514" alt="screen shot 2017-08-03 at 11 08 44 am" src="https://user-images.githubusercontent.com/24388/28936368-60aebc78-783c-11e7-8d28-4f5bcaef3b2a.png">

Of course, things vary between fonts and browsers and platforms. This should just be what we're shooting for. All of these tweaks are intended to just tidy up current comment display so it's more scannable.

Make sense?

**Comment by samouri** [comment]
nits have been dealt with!
