### ISSUE TITLE
Add markdown settings in for Jetpack sites only

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#16884]
If I remember correctly, we removed markdown all across Calypso. There was an effort to remove markdown settings in Jetpack sites as well so we decided not to add markdown settings for Jetpack sites. However, this turned out to be somewhat confusing for Jetpack users.

We currently have markdown options in Jetpack and I think we should mirror them in Calypso. Perhaps we can reuse some of the work @ryelle did here: https://github.com/Automattic/wp-calypso/pull/10785

Here are what the options look like in Jetpack:
![image](https://user-images.githubusercontent.com/1123119/28937059-e15d587a-7846-11e7-8f51-0e30a39c886c.png)
![image](https://user-images.githubusercontent.com/1123119/28937068-eaafac48-7846-11e7-8a34-7cce42e78a5b.png)

I propose we do the same thing within the Calypso settings by adding the first option exactly as it is in Jetpack to the Composing settings group within the Writing settings tab. We should also add the option to use it in comments in the Comments group of the Discussion settings tab.

CC @oskosk @tyxla

**Comment by ockham** [comment]
Discussion about removing Markdown settings from Jetpack: https://github.com/Automattic/jetpack/issues/6669

**Comment by MichaelArestad** [comment]
Yep. Let's close this.

**Comment by ockham** [comment]
> Yep. Let's close this.

Whaaat? But I just got the PR ready 😅: #22999

**Comment by ockham** [comment]
(I thought since this issue's date was more recent than the discussion in #6669, it was reflecting the current state of affairs and what we'd like to do more closely.)

**Comment by MichaelArestad** [comment]
Right. I think the solution (Past Michael convinced Future Michael) is to remove the settings from Jetpack rather than to add them to Calypso. I had just forgotten completely about the past conversation.

**Comment by ockham** [comment]
JP PR to remove Markdown settings: I'll file a PR to remove Markdown settings on the JP side instead.
