### ISSUE TITLE
Blog ID is reported in sections that do not use it

### ISSUE THREAD

**Issue by yanirs** [Automattic/wp-calypso#16900]
Sections like /me (Profile Settings) and the Reader should not report the currently selected site. This may happen when a user visits a site specific page before navigating to Me or the Reader (without refreshing the page).

This is harmful for tracking because we use blog id to determine when we track general admin activity from site-specific activity.

For example, when visiting `/me` or `/read/search`, `blog_id` should always be reported as null, while it should always be reported as non-null for `/posts/:site` and `/stats/day/:site`.

This line may be of some interest: https://github.com/Automattic/wp-calypso/blob/d7b8e0a3d6e65bcd75d864f6122c9ba7ddc732cc/client/lib/analytics/super-props.js#L24

Let's make sure that the following has correct reporting:
- Reader
- Me
- Notifications

**Comment by yanirs** [comment]
Note: Based on more log queries, even when `blog_id` is set, it doesn't necessarily match the reported path.

**Comment by donpark** [comment]
Closing since suggested future direction is to *completely move away from using `selectedSite`. New issue should be created accordingly.

**Comment by yanirs** [comment]
@donpark Why close this issue? The problem still exists, and `blog_id` should still be set in a more consistent manner.

**Comment by kwight** [comment]
Noting that while looking into #23632 , I'm not able to replicate this behaviour anymore (going from a site-specific page to the Reader or `/me` strips the previously selected site and does not record a blog ID in the page view stat), nor can I find any recent examples in Impala.

**Comment by gwwar** [comment]
@kwight you can repro by clicking on my-sites, selecting a site, then (without refreshing the browser) clicking on the Reader or Profile
