### ISSUE TITLE
Fix behavior of transient google images inserted in the editor

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#16919]
Steps to reproduce:

* Connect google service.
* Open the import from google media modal and copy an image to the library.
* Quickly insert it in the editor (before it is completely uploaded).

Expected result:

* the transient image is included in the editor with the google URL and contains a class named `wp-image-media-transientid`.
* upon receiving the file from the server, the URL is updated to the one provided by the media library and the classname is updated to `wp-image-id`.
* it cannot be edited by the image editor that's opened from the bar until the file is saved in the media library.
* the post cannot be published until the image is uploaded (and the publish button is disabled).

This is how other transients behave (drag&drop or the ones uploaded with the add button). Images imported from an URL cannot be inserted in the editor until they uploading finishes, so this doesn't apply to them.

What happened instead was that the transient image allows the user to open the editor (but not loads the image - no errors shown, though) and publish the post. The URL and classname weren't updated upon uploading was finished.

## Related PRs to fix it:

- [x] https://github.com/Automattic/wp-calypso/pull/17162 Make all transients to use a transient ID
- [x] https://github.com/Automattic/wp-calypso/pull/17007 Update [deserialization transient detection mechanism](https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/media/plugin.jsx#L147) to accommodate external services.

This is fixed by the above PRs. Merge them in a local branch, and test for the expected result.

cc @johngodley

**Comment by nosolosw** [comment]
Assigned to me, as I'm already working to solve it.

**Comment by aduth** [comment]
>the transient image is included in the editor with the google URL and contains a class named `wp-media-transientid`.

Do we need this step?

**Comment by nosolosw** [comment]
> Do we need this step?

It's just how it works now, and is unrelated to the problem this PR tries to solve.

**Comment by nosolosw** [comment]
PRs to fix this have landed today.
