### ISSUE TITLE
My Sites: Tooltip on site icon not useful when focus is on site already

### ISSUE THREAD

**Issue by astralbodies** [Automattic/wp-calypso#16911]
#### Steps to reproduce
1. Select a site in Calypso.
2. Hover over the site icon with the mouse cursor.

#### What I expected
I didn't expect a tooltip at all, actually. 

#### What happened instead
Tooltip provided is "Select this site" which is misleading because a site is already selected. Not a huge deal for someone who is sighted but it is probably confusing for users with screen readers.

#### Browser / OS version
Safari 10.1.2 on macOS 10.12.6.

#### Screenshot / Video
![2017-08-04_09-11-04](https://user-images.githubusercontent.com/373903/28972405-29be4fe4-78f5-11e7-9911-8aae68281509.png)

**Comment by omidfi** [comment]
I guess this should be closed as it's fixed in #17860
