### ISSUE TITLE
Reader Conversations: Limit each comment to 3 lines

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#16918]
Original issue: https://github.com/Automattic/wp-calypso/issues/16316

Right now every comment is shown in full on initial load of conversation stream.
That can make certain super long comments overwhelm the stream.
This issue is to limit it to a few lines (but be expandable).

> Yup! Limiting comments to 3 lines with “read more” link inserted

**Example top-level comment:**
![screenshot 2017-08-04 12 21 49](https://user-images.githubusercontent.com/4924246/28983650-90df1bb2-790f-11e7-8766-f5940bcb8c8e.png)

**Example reply:**
![screenshot 2017-08-04 12 16 16](https://user-images.githubusercontent.com/4924246/28983494-e1a397e0-790e-11e7-9606-d69777700640.png)

**Comment by fraying** [comment]
Pinging @jancavan for a mockup.

**Comment by jancavan** [comment]
I updated the description. Note that if the a comment that has been read gets new replies, we limit the excerpt to a single line instead of three:

![screenshot 2017-08-04 12 16 42](https://user-images.githubusercontent.com/4924246/28983529-18656d4e-790f-11e7-8091-bbcf3ca2ef1a.png)

We do this to provide context to the conversation.

**Comment by fraying** [comment]
@jancavan Thanks!

Yeah, that 1-line version should probably be a separate issue.

**Comment by jancavan** [comment]
Maybe we'll need to resort to the fade instead of the ellipsis, but I'm taking a stab at cross-browser multi-line clamping (with an ellipsis). Going to need help expanding the comment after you click "Read more" though. /cc @samouri or @bluefuton

**Comment by samouri** [comment]
even though the exact fade and show more implementation is still in flux...i'd say we can close this since they have their own issues
