### ISSUE TITLE
Editor: Publish Date Component Does Not Update When No Saved Draft

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#16915]
#### Steps to reproduce
1. Create a new post
2. Do not type anything in title or body of post
3. Try to change the publish date in Post Settings

#### What I expected

The publish date component to update immediately to reflect the new selected date.

#### What happened instead

The publish date component did not update until title or body was entered and the initial auto saving of the draft completed.

Note: The "Publish..." button correctly changes to "Schedule..." immediately after picking a date in the future, but the publish date component does not update.

#### Screenshot / Video

![publish date component not updating until draft saved](https://user-images.githubusercontent.com/2098816/30983443-77f0c28a-a458-11e7-8940-de80979bbb2c.gif)

#### Context / Source

Found while testing a related feature.

**Comment by alisterscott** [comment]
This was raised today on `p2-p58i-6Gy`

I'll put a high priority on this as it's not a great customer experience.

I did some testing, and I also noticed this is problematic when actually saving a draft as it doesn't look like anything has happened when suddenly it has:

![schedule post](https://user-images.githubusercontent.com/128826/32033506-2f845134-ba50-11e7-92b2-dc6079cf6a90.gif)

**Comment by mattsherman** [comment]
This is on @Automattic/tanooki's backlog, and will be addressed during a future iteration focusing on publishing improvements.

After confirming with @lancewillett, I am removing the High priority label, as this issue only occurs before the initial draft is autosaved.

**Comment by alisterscott** [comment]
Confirmed this is still an issue

#bug-scrub #pre-gutenburg-bug-purge

**Comment by mattsherman** [comment]
Closing this issue in favor of #20486, which has more details on current related issues.
