### ISSUE TITLE
Reader Conversations: omit pingbacks/trackbacks

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#16920]
Original https://github.com/Automattic/wp-calypso/issues/16316

This issue can be closed when trackpacks/pingbacks are no longer in the Reader Conversations stream.

**Comment by blowery** [comment]
We'll need to drop them from the API / last_comment_date consideration too... 

@aaronyan

**Comment by fraying** [comment]
I think this is done! Safe to close, @blowery ?

**Comment by samouri** [comment]
@fraying: theres more work till this can really be closed:
1. API should skip them as well (that the cc @aaronyan bit)
2. In case for whatever reason the API borks and we get ineligible comments we should really fetch more comments so we can still display 3

**Comment by fraying** [comment]
Ok, thanks, @samouri. Leaving this open until those two things are done.

**Comment by fraying** [comment]
Still seeing the occasional trackback in Convos.

<img width="842" alt="screen shot 2017-08-28 at 2 42 32 pm" src="https://user-images.githubusercontent.com/24388/29795022-45871af4-8bff-11e7-9d4d-50b61d5097ac.png">

This is the post: https://wpcalypso.wordpress.com/read/blogs/51862805/posts/10958

cc @samouri

**Comment by samouri** [comment]
we removed trackbacks...but then they came back when we added in update acceptance.
we'll have a smarter pingback/trackback removal coming soon

**Comment by blowery** [comment]
Where's this stand @samouri, @aaronyan ?

**Comment by samouri** [comment]
@blowery:
1. api end still needs to filter it out afaik but i may not be up to date on that (@aaronyan)
2. we still need to implement selectors that can take and respect a `filterBacks`

**Comment by aaronyan** [comment]
Removed pingback/trackback from Conversations API in changeset 162790.

cc: @blowery, @samouri.

**Comment by fraying** [comment]
Thanks, @aaronyan! Nice work. 👍
