### ISSUE TITLE
Simple Payments: Editing Existing Button Fails - Upgrade Messaging Displayed

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16923]
When attempting to edit an existing simple payment button, I am shown messaging that I need to upgrade to the premium plan to use the feature:

![edit_page_ _trout_bummin_ _wordpress_com](https://user-images.githubusercontent.com/22080/28981024-ca9bb87a-7904-11e7-880c-b4c93a2d6a01.png)

I confirmed that my business plan is active through March of 2018.

/cc @jhnstn

**Comment by donpark** [comment]
From https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/simple-payments/dialog/index.jsx#L405

> 	<UpgradeNudge
>		...
>		shouldDisplay={ this.returnTrue }
>	/>

`returnTrue` function always return `true` so I'm surprised nudge is not always shown.

**Comment by donpark** [comment]
Flag `planHasSimplePaymentsFeature` is used at https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/simple-payments/dialog/index.jsx#L393

which is set from Redux store via this line:

> planHasSimplePaymentsFeature: hasFeature( state, siteId, FEATURE_SIMPLE_PAYMENTS )

**Comment by artpi** [comment]
Solution: https://github.com/Automattic/wp-calypso/pull/16966
