### ISSUE TITLE
Simple Payments: Loading Indicator / Skeleton Missing

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#16924]
When opening a page that has a Simple Payments button, especially on a slower connection, it is hard to tell if payment button exists:

![simple-payment-loading](https://user-images.githubusercontent.com/22080/28981174-92d03e1a-7905-11e7-9b5f-0409d7f6381c.gif)

Note in this scenario, I also encounter #9833 - which in my experience seems to happen more often with shortcodes.

Back to the original issue here though - it kind of seems like when a simple payment exists, there should be a loading indicator of sorts in the content area while any data is fetched to properly display the UI.

/cc @jhnstn

**Comment by lamosty** [comment]
Great idea.

@iamtakashi can you please think of a simple design for this? Maybe we could just use the standard Calypso placeholder styling with an image, title, description and button skeletons.

**Comment by iamtakashi** [comment]
@lamosty How about something like this? Colour and animation should be the same as other placeholders.

![image](https://user-images.githubusercontent.com/908665/29119947-18734a6e-7d00-11e7-85d7-9384b3425a12.png)

**Comment by alisterscott** [comment]
I tested this and found that even the text above and below the payment button didn't load and show any placeholder on a slow connection (Chrome set to slow 3G):

![payment button](https://user-images.githubusercontent.com/128826/36134507-f6dc2582-10d0-11e8-958b-f2427c8ab095.gif)

Is this an issue with payment buttons or just the editor showing a loading indicator generally?

#bug-scrub #pre-gutenburg-bug-purge
