### ISSUE TITLE
Comments: limit the entire thing to only users with that can `moderate_comments`

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#16925]
It doesn't make sense to display the /comments route to folks who cannot moderate comments.

- [ ] Make sure this doesn't display in sidebar
- [ ] Add a route check

**Comment by gwwar** [comment]
Looking through this issue again, we're already checking for the `edit_posts` capability which looks about right. Note that the new endpoint is still using an a8c check.

**Comment by gwwar** [comment]
Please reopen, if folks are still running into issues

**Comment by Copons** [comment]
@gwwar Reopening: we're checking that on the endpoint, but not in Calypso.
We need something like `canCurrentUser( state, siteId, 'moderate_comments' );` in the section controller.

**Comment by Copons** [comment]
Ok, I found something interesting.
Currently, the `sites` endpoint doesn't return _all_ the user capabilities but just a subset:
p1502044041635680-slack-lannister (internal)

I'm not sure how to proceed here. 🤔

**Comment by gwwar** [comment]
We'd whitelist the option I think. see https://github.com/Automattic/wp-calypso/pull/14096 there's a huge list of options in  `client/lib/sites-list/list.js`, `client/state/jetpack-connect/actions.js`
`client/state/sites/actions.js` that we'd need to update.

**Comment by CompChris** [comment]
May have some relevance to #21301 /// p1515190285000295-slack-triage

It may no longer be necessary for users with Contributor status to be able to view comments, if they cannot moderate them.

Recommendation for this function to only be available to Admin, Editor, and Author (limited to their posts) only.

cc: @designsimply

**Comment by gwwar** [comment]
I think https://github.com/Automattic/wp-calypso/issues/21301 is sufficient. We'll need to verify what behavior is available on wp-admin and match it.

**Comment by gwwar** [comment]
More behavior details are documented here https://github.com/Automattic/wp-calypso/issues/17687
