### ISSUE TITLE
Reader Conversations: Limit parent comment to a single line if old

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#16933]
See: https://github.com/Automattic/wp-calypso/issues/16918#issuecomment-320332466

![screenshot 2017-08-04 12 16 42](https://user-images.githubusercontent.com/4924246/28983529-18656d4e-790f-11e7-8091-bbcf3ca2ef1a.png)

Derek adds: The idea is, if one of the comments we’re showing (no matter how we decide to show it), is a reply to another comment, then show the top-level comment and limit it to 1 line. Just to set context for the reply.

**Comment by samouri** [comment]
the parent logic part hasn't been implemented yet, but the UI Component was completed in https://github.com/Automattic/wp-calypso/pull/17225

**Comment by samouri** [comment]
done as part of recent caterpillar work! closing
