### ISSUE TITLE
Office 365 email setup adding an extra underscore to SRV records

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#16959]
We have this very handy tool where users can enter just enter their Office 365 TXT verification record, and we automatically add all the MX, CNAME and SRV records for them:

![image](https://user-images.githubusercontent.com/6505293/29027816-b04b53c4-7b9b-11e7-885f-d13be24e0e72.png)

However, it appears the two SRV records get added with an extra _ (underscore). They should be like:

`_sipfederationtls._tcp`
&
`_sip._tls`

But get added like:

`_sipfederationtls.__tcp`
`_sip.__tls`

When this happens, Office 365 can't verify the SRV records.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage/{DOMAIN.COM}/name-servers/{SITE}.wordpress.com
2. Click Office 365
3. Add a dummy verification token, e.g. `MS=ms12345678`
4. Now, look up the SRV records in our zone. You can either do a `dig` lookup or view them in our internal domain information tool:

#### What I expected
Looking up the expected SRV record should've worked fine, but it doesn't. E.g.:

`dig _sipfederationtls._tcp.DOMAIN.COM SRV @ns1.wordpress.com +short`

Should return:

`100 1 5061 sipfed.online.lync.com.`

#### What happened instead

Since the record is added with an extra underscore, looking up for the correct record doesn't really return anything. And the SRV records show up like this in our domains tool:

![image](https://user-images.githubusercontent.com/6505293/29027714-50a3a264-7b9b-11e7-9a57-b6d13a7f5452.png)

#manual-testing after user reported SRV records weren't being recognized by Microsoft Office 365.

**Comment by hambai** [comment]
I've created a diff to fix that - D6719-code

**Comment by hambai** [comment]
OK - I just deployed the fix. Should work properly now.
