### ISSUE TITLE
Domains: Improve entry of international addresses

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#16956]
As a first iteration we should implement a second format of addresses that covers most of Europe. Here is Germany as an example:

![screen-shot-2017-08-07-at-12 35 12](https://user-images.githubusercontent.com/203408/29025137-9fc6bb40-7b75-11e7-9bf8-09e6d7f92711.png)

Explanation:
- State is not needed (while it exists in Germany as "Bundesland" it's not important for the address). In the background we should assign something like `N/A` or `--`.
- Postal code and City change their positions.

The two postal address entry formats (let's call them US and EU) should be switched according to a list of countries as it is used in the dropdown.

While at it, we should also remove the display of the address fields until a country was picked. This is meant to not confront international users with a "weird" address format until they have chosen the country.

![screen shot 2017-08-07 at 13 05 25 copy](https://user-images.githubusercontent.com/203408/29025223-02ee55fc-7b76-11e7-9461-5ac9f19c56a0.png)

Optionally we could display the address fields above the country dropdown so that it resembles more of an envelope address (with the phone number we already have a case of changed field above country dropdown).

For the future even more formats (e.g. UK,  `[city] [postcode] (no state)`, etc.) should be possible to implement.

**Comment by ramonjd** [comment]
I've taken a naïve stab at showing and hiding the address fieldset. 

Checking for a valid value in the country select field only works of course, yet it raises a strange UI-based race condition whereby the validation error message hangs around for a second after we make the address fieldset active:

![show-hide-address-field](https://user-images.githubusercontent.com/6458278/30952922-257e1db2-a46d-11e7-9672-872acdc028a5.gif)

So in `renderDetailsForm()` I'm checking [both the value and the existence of errors](https://github.com/Automattic/wp-calypso/blob/update/domain-entry-of-international-addresses/client/my-sites/checkout/checkout/domain-details-form.jsx#L396), which displays the address fieldset when the error is gone.

![show-hide-address-field-on-error](https://user-images.githubusercontent.com/6458278/30953126-eb0395c6-a46d-11e7-906d-5f076840fd43.gif)

Am I opening up an inherent risk here? If, for whatever reason, the select field state contains an error we'll hide the address fields regardless of whether a value is set. 

It _should_ be fine given that it's a select field with defined values — either a country is selected or it's not  — but I thought I'd throw it out there. 🙂  

Cheers!

**Comment by deBhal** [comment]
@mikeshelton1503: We've discussed that generated forms look bad, and we're dancing around that territory here, so I wanted to make sure that we don't set off down a dead-end.

We need to let designer make each format look good, so it seems like a really good idea to have an explicit css class for each address format.

With that hook in place, we could do a lot with it.

Hiding components will work better in react, but what about the re-ordering like in the first screenshot in this issue? It seems like we can make the code a lot simpler and the style only a little bit more complex by rearranging fields with CSS, but I'm worried my perspective is biased ;)

**Comment by ramonjd** [comment]
#19088 Merged
