### ISSUE TITLE
Activity log: Show expanded single-event days

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#16957]
> If there’s only one event for a given day, maybe we should just show it instead of making people expand the dropdown?

<img width="388" alt="singleevent" src="https://user-images.githubusercontent.com/841763/29025647-17de938a-7b78-11e7-9138-8803d70c636e.png">

What do you think @keoshi?

From p2JiWH-1Xb-p2 cc @aheckler

**Comment by keoshi** [comment]
It seems logical, but it could also mix elements that shouldn't be mixed. Is this easy to test with a PR? Would like to click around before I commit to saying yes.
