### ISSUE TITLE
Login: Fix password field not populated by 1Password

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#16950]
If you try to log in on calypso from safari on iOS, the password field is cleartext by default and this makes 1password very upset because it does not auto-paste passwords on cleartext fields. Only turning on the masking of the field, it starts working properly again. On desktop it’s password masked by default.

Reported by @p3ob7o.

**Comment by stephanethomas** [comment]
We only display the password in cleartext [for mobile devices](https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/components/forms/form-password-input/index.jsx#L28-L31) upon page load. That's something that was introduced a long time ago (see 11448-gh-calypso-pre-oss), and maybe we should revisit that stance.
