### ISSUE TITLE
Not entering product price does not default to $0.00

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#16974]
#### Steps to reproduce
1. Starting at URL: any WooCommerce atomic site. 
2. Add new product
3. Do not enter a price 
4. Save
5. View product page (front-end) - no way to add to cart. 

#### What I expected
If I don't enter a price, I'd expect it to be set as $0.00 as the help text suggests. 

<img src="http://cld.wthms.co/8e8S9Q+"/>

#### What happened instead
There's no way to add a product to the cart if you do not enter a price. In a couple user tests I've been on the help text had been confused with actual text that users thought would be saved. 

Should we ask: "Are you sure you want to save this product without a price?" Letting them know the product can still be published but won't be able to be purchased? And if they want the product to be free they should enter `0`? 

#### Browser / OS version
Chrome Version 60.0.3112.90, os 10.12.6

#### Screenshot / Video
Example product with no price entered: https://testingstorewoo.com/product/apple-airport-time-capsule-2tb/

#manual-testing

**Comment by allendav** [comment]
+1

**Comment by justinshreve** [comment]
This was recently fixed by #22063.
