### ISSUE TITLE
Deleting product gives "unsaved changes" notice

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#16973]
#### Steps to reproduce
1. Starting at URL: any WooCommerce atomic site with a product that can be deleted. 
2. Go to products > edit a product
3. Delete product
4. Get product successfully deleted message followed by the: "You have unsaved changes are you sure you want to leave this page?" 

#### What I expected
Deleting the product would take me back to the products overview page without the unsaved changes notice popping up. 

#### What happened instead
Video here: http://cld.wthms.co/hJXbjH

#### Browser / OS version
Chrome Version 60.0.3112.90, os 10.12.6

 #manual-testing

**Comment by justinshreve** [comment]
Closing as a duplicate of #16780.
