### ISSUE TITLE
InfiniteList: Uncaught TypeError

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#1698]
Likely due to the move to React 0.14 and the changes in how it deals with `refs`.

See hunk: https://github.com/Automattic/wp-calypso/commit/e511e6fad78e4e0acb489535edcac7ad479f6e15#diff-11efc52f9631555aac184ea102261e2eR274

### Steps to reproduce:
1. Multisite purchase
2. Single-site activate

### Stack trace from @ockham:

![stacktrace](https://cloud.githubusercontent.com/assets/150562/11853284/1bb958bc-a435-11e5-800a-d9044dfc54f5.png)

**Comment by seear** [comment]
This has been fixed by the move from infinite-list to infinite-scroll #2151
