### ISSUE TITLE
Purchases: site identification

### ISSUE THREAD

**Issue by p3ob7o** [Automattic/wp-calypso#170]
The list of sites in /purchases is confusing, only the site name is visible, which can be ambiguous as not unique.

We should add the blavatar and URL, like in the site picker.

**Comment by fabianapsimoes** [comment]
cc @mikeshelton1503

**Comment by umurkontaci** [comment]
FWIW, we also now have the `slug` property in purchases list, we might be helpful.

**Comment by mikeshelton1503** [comment]
Ok so for v1 let's just add the primary url like this:

![image](https://cloud.githubusercontent.com/assets/12596797/11503183/34b4060c-980d-11e5-9e02-fe283a88b061.png)

I'm opting not to include the blavatar for a couple reasons:
1. Not all users have one set so some users would just see the generic blavatar for each site which certainly doesn't help.
2. This would be a change to the section header component that we are using here.

I think work needs to be done on the section header component to address this concern as well as others throughout the UI so keeping that change until v2 will give us time to sort out the best next steps for that component.

**Comment by breezyskies** [comment]
@mikeshelton1503's design implemented in https://github.com/Automattic/wp-calypso/pull/2359.
