### ISSUE TITLE
Store: Add Stripe Connect flows (Design)

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#17001]
Change the Store > Settings > Payments > Stripe flows to include

- Deferred connected account creation
- OAuth grants for connecting existing accounts
- Legacy API key entry

**Comment by kellychoffman** [comment]
We need to account for three scenarios:

1. I want to use Stripe to accept payments and I don’t have a Stripe account [Clickable prototype](https://automattic.invisionapp.com/share/9HCYCRJRG#/screens/247736500_New_Account_-_1)
2. I want to use Stripe to accept payments and already have a Stripe account [Clickable prototype](https://automattic.invisionapp.com/share/KVCYD1MX5#/screens/247740450_Existing_Account_-_1)
3. I want to use Stripe to accept payments but I’m a developer or someone who has no interest in connecting my store to Stripe and want to go DIY. [Clickable prototype](https://automattic.invisionapp.com/share/YXCYD61EP#/screens/247742266_Diy_-_1)

[Sketch file with all three flows](https://www.dropbox.com/s/0oeexmvsd1b0m6g/add%20payment%20-%20stripe%20connect.sketch?dl=0)

**Comment by allendav** [comment]
@kellychoffman wrote

"someone who has no interest in connecting my store to Stripe and want to go DIY"

well, to be more precise, "someone who has no interest in connecting my store to Stripe _via the Stripe Connect WordPress.com platform_ and want to just connect directly to Stripe itself"

**Comment by kellychoffman** [comment]
Not stale, but shipped!
