### ISSUE TITLE
Site settings: Allow site with premium theme to be deleted with proper warnings

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#17012]
In adding a warning when deleting a site with a Premium theme we have blocked sites with only a Premium theme from deleting their site. The message is generic for all upgrades and advises the user to cancel the upgrade before deleting their site. However, premium themes are a one-time purchase and we do not support deleting them. 

#9639 was opened to allow premium themes to be canceled, but given the difficulty for staff to restore them in the case of accidental cancellation and potential loss of settings when this happens I think we should instead allow sites with only premium theme(s) to delete their site as they could previously, but with proper warning that the site has a premium theme and access to it will be lost.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/example.wordpress.com where example.wordpress.com has a premium theme
2. Select the "Delete your site permanently option"
3. You are shown the following warning with no way to proceed without contacting support, as Premium themes cannot be canceled by users

![screen shot 2017-07-26 at 10 34 46 am](https://user-images.githubusercontent.com/1900444/29087750-022a899a-7c45-11e7-828d-fd9dd9707d53.png)

#### What I expected
To be able to delete a site with a premium theme with proper warnings that I would lose access

#### What happened instead
The user is shown a message to cancel the upgrades that cannot be done on their own and requires support intervention

**Comment by eduardozulian** [comment]
Another report on https://br.forums.wordpress.com/topic/quero-excluir-meu-site-e-perfil-wordpress-permanentemente?replies=1 (pt-br)

**Comment by eduardozulian** [comment]
Another one on 2272156-hc

**Comment by eduardozulian** [comment]
Another report 1056399-zen

**Comment by GeoJunkie** [comment]
This happened with another site: 1077287-zen

**Comment by KokkieH** [comment]
Just noting this is now also causing issues with account closure, for example, https://en.forums.wordpress.com/topic/closing-account-58/

**Comment by KokkieH** [comment]
Another: https://en.forums.wordpress.com/topic/close-account-165

**Comment by KokkieH** [comment]
And https://en.forums.wordpress.com/topic/how-to-cancel-an-auto-renewing-theme

**Comment by KokkieH** [comment]
Thank you, @bluefuton!
