### ISSUE TITLE
Reader Conversations: Remove "Follow/Following" link from top right

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17019]
In the Conversations Tool, the top left corner of each post should be the ellipsis menu. Please remove the "Follow/Following" link.

For example:

<img width="812" alt="screen shot 2017-08-08 at 2 27 49 pm" src="https://user-images.githubusercontent.com/24388/29095490-c7923458-7c45-11e7-91fa-681f5023a70f.png">

ccing @blowery because we discussed this today.

**Comment by samouri** [comment]
solved in https://github.com/Automattic/wp-calypso/pull/17070
