### ISSUE TITLE
Editor: back button on multi-site causes glitch and fatal error

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#17022]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post (user must have more than one site.)
2. Click to choose a site from the site picker.
3. When the editor loads, click the back arrow button in the upper-left (`.editor-ground-control__back`, see video below).

This also happens when clicking the back button during the post-post preview, which is where I first saw it.

#### What I expected

To return to either the site picker or perhaps the stats page for my site.

#### What happened instead

A very strange UI glitch and a JavaScript error:

```
Uncaught TypeError: Cannot read property 'ID' of null
```

#### Browser / OS version

Mac OS Chrome 60.0.3112.90

#### Video

https://cloudup.com/cFktl-rc2ps

#### Screenshot
<img width="904" alt="screen shot 2017-08-08 at 5 35 37 pm" src="https://user-images.githubusercontent.com/2036909/29095747-04dc8cfe-7c60-11e7-97d0-9730d649c338.png">

<img width="537" alt="screen shot 2017-08-08 at 5 37 53 pm" src="https://user-images.githubusercontent.com/2036909/29095834-59d83596-7c60-11e7-980b-b26a06b4355c.png">

**Comment by rachelmcr** [comment]
I tested this again and can no longer reproduce the issue.

Note that the editor no longer has a back arrow button, so instead I clicked the Close button in the top left to exit the editor:

![screenshot 2018-08-28 11 07 36](https://user-images.githubusercontent.com/8658164/44716598-b4432500-aab2-11e8-82c5-65d83153ba80.png)

This took me back to the site picker with no console errors. I also tested using my browser's back button with the same results.

Closing as resolved.
