### ISSUE TITLE
Reader Conversations: Limit Title to one line

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17025]
In Reader Conversations, the post title in the main card should be limited to one line and fade on the right (like Combined Cards).

<img width="802" alt="screen shot 2017-08-08 at 2 57 35 pm" src="https://user-images.githubusercontent.com/24388/29096498-0f851682-7c4a-11e7-9b6d-18ffe8f40e24.png">

**Comment by samouri** [comment]
solved in https://github.com/Automattic/wp-calypso/pull/17070
