### ISSUE TITLE
Reader Conversations: Remove indentation

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17021]
In Reader Conversations, each post is indented by ~48px. They shouldn't be. The card content should be aligned with the left edge of the line.

<img width="513" alt="screen shot 2017-08-08 at 2 33 07 pm" src="https://user-images.githubusercontent.com/24388/29095708-b76e5934-7c46-11e7-8ad0-f2f767f24185.png">

**Comment by samouri** [comment]
solved in https://github.com/Automattic/wp-calypso/pull/17070
