### ISSUE TITLE
Reader Conversations: Remove tags

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17020]
In the Conversations Tool, no tags should be displayed. They're not important in this context (and space is very limited).

For example:

<img width="828" alt="screen shot 2017-08-08 at 2 30 30 pm" src="https://user-images.githubusercontent.com/24388/29095610-494b2324-7c46-11e7-98a7-56f55ec27820.png">

**Comment by samouri** [comment]
solved in https://github.com/Automattic/wp-calypso/pull/17070
