### ISSUE TITLE
Triforce: Curate homepage for people who select Welcome Page

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#1703]
Is it possible to create a "home" page and assign it as their front page for anyone who selects "A welcome page for my site" in Triforce? Would be extra great if we could also assign the theme's homepage template to that page, if it has one.

cc @kwight

**Comment by ianstewart** [comment]
We can do this with Headstart annotations. cc @michaeldcain  Something we determined would be out of scope until we saw the effect Triforce would have on signup completion. Agreed that we should be doing it. :)

**Comment by michaeldcain** [comment]
These things are possible with Headstart annotations, but would mess with the basic Triforce AB results. I think Triforce AB i2 will use all/part of Headstart functionality.

**Comment by melchoyce** [comment]
Let's slate this in for Triforce i2, then.

**Comment by designsimply** [comment]
What is Triforce? :)

**Comment by michaeldcain** [comment]
@designsimply: just a nickname for #1559. We should probably avoid those for the sake of public discussion, or just be better with our label tagging.
