### ISSUE TITLE
Store: Product Reviews: Add UI for replying to a review

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#17047]
We need an interface for replying to reviews from within Calypso. #12989 shows a view of what a reply looks like once posted. @kellychoffman do we need a design for the reply interface, or will it be nothing more then a TinyMCE instance inline there?

This should use the 'creates' edits infrastructure added in #17045 and actions in #17046 for actually saving the reply.

**Comment by kellychoffman** [comment]
@jameskoster: I think you have a flow for this.

**Comment by jameskoster** [comment]
We don't have a fully prototyped flow for replying specifically.

Here are the prototypes we have;

* [Approving a review](https://automattic.invisionapp.com/share/XJBRZWYB8#/234457653_Reviews_List)
* [Remove all reviews for a specific product using search](https://automattic.invisionapp.com/share/HDBQEJ862#/233971493_Reviews_-all-)
* [Remove all reviews for a specific product - via the edit product screen](https://automattic.invisionapp.com/share/HDBQEJ862#/234004615_Edit_Octopus_Tshirt)

Sketch file can be found [here](https://www.dropbox.com/s/m0b1jjkw2iisibf/Reviews.sketch?dl=0).

An example of a review with a reply can be seen on the 'Screens' page. It's fairly straightforward:

![review-expanded-with-reply](https://cldup.com/9PawW1-bzD-3000x3000.png)

Now that I look at it I'm wondering if we need review editing? There's no design for this currently. What do you think @kellychoffman ? Admins will probably need to be able to edit their replies at least.

**Comment by kellychoffman** [comment]
Chatted in Slack about this and we decided to keep editing out for v1. Comment moderation also won't have it in the initial launch so we will at least be consistent.

**Comment by kellychoffman** [comment]
For replying to a review, we should use the UX in Comments.

**Comment by kellychoffman** [comment]
> For replying to a review, we should use the UX in Comments.

![replying to comments](https://user-images.githubusercontent.com/5835847/29174920-eede81dc-7da4-11e7-83f9-ab6dd220a1ea.gif)
