### ISSUE TITLE
Refine store setup dashboard / flow

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17058]
Although part of a Q4 item, I wanted to create this epic to document the issue once https://github.com/Automattic/wp-calypso/issues/16626 is closed.

Our current store setup flow feels a little fragmented and can certainly be streamlined.

Some rough, initial ideas / prototypes;

> The first is to streamline the current checklist/setting behaviour. IE you always return to the checklist when you save something and we remove the sidebar so there's nowhere to get lost / drop off the flow
>
> Protoype: 
> https://automattic.invisionapp.com/share/49CO86T7T#/244686827_Screen_Shot_2017-07-20_At_10-21-47
>
> The second is to remove the checklist altogether. Customers are simply funnelled through each screen sequentially with a progress bar to visualise progression through the steps.
>
> Prototype: 
> https://automattic.invisionapp.com/share/BYCQ0HTZ3#/screens/244966568_Gather_Store_Data

This will need further discovery / research. Not to mention lining up with the overall wp.com/wc.com nux flows.

**Comment by kellychoffman** [comment]
A version of this has been shipped. Closing.
