### ISSUE TITLE
Triforce: Layout screen needs better copy

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#1705]
Right now we use "like" twice:

<img width="601" alt="screen shot 2015-12-16 at 4 56 17 pm" src="https://cloud.githubusercontent.com/assets/2846578/11855134/67cdc5cc-a416-11e5-94d5-0311214075ae.png">

Some alternate ideas:

`What do you want your homepage to look like?`
`What kind of site are you looking for?`
`What kind of homepage do you want?`
`What kind of homepage do you need?`

**Comment by michaeldcain** [comment]
Since the next step is more direct "Choose a theme/(design).", we could follow suit with something like:
`Select a homepage layout.`

**Comment by michaeldcain** [comment]
or if we want to ease users into the flow: `To start, select a homepage layout.`
