### ISSUE TITLE
Store: Design Google Analytics set up flow

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#17060]
Add code to install and allow merchants to configure http://wordpress.org/plugins/WooCommerce-Google-Analytics-integration/ on Store sites

Note: We already have a means of setting the Google Tracking ID (and that seems to be the only setting) in Calypso at https://wordpress.com/settings/traffic/{domain} under Google Analytics

Related dev task: #17105 

Clickable prototype: TBD

Sketch file: TBD

cc @allendav @mattyza @beaulebens

**Comment by allendav** [comment]
As a reference, here is the busy WooCommerce-Google-Analytics-integration setup page presently in wp-admin

<img width="1903" alt="screen shot 2017-08-10 at 10 07 07 am" src="https://user-images.githubusercontent.com/1595739/29182714-ccdd53f0-7db4-11e7-9d00-3f27f182f59a.png">

**Comment by beaulebens** [comment]
Note that the Google Analytics configuration is currently only available to Business (WP.com) or Professional (Jetpack) users.

**Comment by kellychoffman** [comment]
Closed as the design is done, dev still in progress.
