### ISSUE TITLE
Activity Log: fix vertical line height

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17065]
We should tackle the issue with the overflowing vertical line. I've tried to tweak it with CSS only, but I think we need a couple of lines of code to keep track of at least two situations:

- Last event on the month's last day.
- Expanded last event on the month's last day.

### Reference images for both scenarios

![image](https://user-images.githubusercontent.com/390760/29131888-d0e13116-7d1d-11e7-8c89-d3312521d6e7.png)

![image](https://user-images.githubusercontent.com/390760/29131912-e491ffba-7d1d-11e7-8999-2a0650cd2ca3.png)

**Comment by keoshi** [comment]
Soft ping on this @sirreal — any ideas how to go around the obvious limitations and accomplish this?

**Comment by sirreal** [comment]
Although I've been mute here, I have played with some different concepts. I do think this can be handled by improving styles and structure, but I need to dedicate some time 🙂

**Comment by keoshi** [comment]
Thank you! 🙌

**Comment by MichaelArestad** [comment]
Is this still an active problem? I'm unable to replicate. Does it only happen on the first day of the month?

**Comment by keoshi** [comment]
It is, and happens at the very bottom, on the last item on each view (first
day of the month).
-- 
-- Filipe Varela

**Comment by MichaelArestad** [comment]
Awesome. Will look into after we get some of the meatier issues taken care of.

**Comment by MichaelArestad** [comment]
Might still be an issue.

**Comment by eliorivero** [comment]
eeehh... yeah

https://github.com/Automattic/wp-calypso/issues/19342

**Comment by MichaelArestad** [comment]
Will need to fix it for discarded as well:

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1123119/32335238-006359d8-bfb2-11e7-99fe-3d342f067a89.png">
