### ISSUE TITLE
Reader Conversations: Clicking "<- Back" from FullPost changes comments shown

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#17067]
The three comments shown on a post (in Conversations tool) changes to the oldest three (instead of the newest three) after completing these steps:

1. Open Conversations tool
2. Click on a post to view the comments (view FullPost)
3. Click on the back arrow "<- Back"

After step 3, the comments will have changed from the newest three to the oldest three.

**Comment by fraying** [comment]
OMG thanks for posting this.

**Comment by fraying** [comment]
cc @blowery

**Comment by samouri** [comment]
i find that extremely strange, i'll look into it

**Comment by fraying** [comment]
@samouri Thanks!
