### ISSUE TITLE
Reader: Omit reply-to name if duplicate

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#17077]
I keep seeing this in the Conversations Tool:

![screenshot 2017-08-09 19 47 21](https://user-images.githubusercontent.com/4924246/29152373-fecd17de-7d3b-11e7-9d2a-5eb4c740fd85.png)
![screenshot 2017-08-09 19 48 49](https://user-images.githubusercontent.com/4924246/29152374-fecde8da-7d3b-11e7-977c-0e79ac5404f4.png)

I think if the user is replying to themselves, the arrow and reply-to name should be omitted.

**Comment by fraying** [comment]
I'm actually not sure I agree with this. If all the indented replies have reply-to names, except some don't, I think it'll look like an error. I know it's weird seeing "Derek > Derek" but that's what they're doing: replying to themselves. 

I suggest we live with it for a while and see if we get used to it.

**Comment by jancavan** [comment]
> I suggest we live with it for a while and see if we get used to it.

Sounds good. I'll close this for now.
