### ISSUE TITLE
Store: Add new shipping zone page layout is broken on small screens

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#17074]
![screen shot 2017-08-09 at 3 42 53 pm](https://user-images.githubusercontent.com/5835847/29145406-39d5a002-7d1a-11e7-9aca-874273ec8b67.png)

- we need to account for long breadcrumbs
- fix the spacing issue between sticky header and content

**Comment by jameskoster** [comment]
For the breadcrumb there's really only two options I can think of if we want to keep the functionality;

Wrap 'em;

![wrap](https://cldup.com/reTsRJSW91-2000x2000.png)

Or, fade 'em (perhaps with horizontal scrolling);

![fade](https://cldup.com/hoYwdiqTFX-3000x3000.png)

Neither are perfect.

There's one bonus option; the nuclear approach;

![boom](https://cldup.com/hl-YO6XeaM-3000x3000.png)

Removing the crumbs can create a bit of a rabbit-hole situation though. If you edit a zone, getting back to the main shipping screen (to edit another zone for example) is a bit of a mission. We could add a link to the success message on save to get around that...

**Comment by kellychoffman** [comment]
> Wrap 'em;

Since this is the only page it happens on right now, I think wrapping is our best bet since it shows everything and still looks nice.

**Comment by kellychoffman** [comment]
Fixed!
