### ISSUE TITLE
Jetpack Scan: improve last scanned date display when no date exists

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#171]
When there is no last scanned date, show 'Queued for scanning'. Here's what it looks like now:

![screen shot 2015-11-19 at 9 49 25 am](https://cloud.githubusercontent.com/assets/11487924/11273730/ec626f88-8ea2-11e5-83f4-e7eb5fd8c606.png)

There is no date shown at all. Here's what it looks like when there is a data to display:

![screen shot 2015-11-19 at 9 50 33 am](https://cloud.githubusercontent.com/assets/11487924/11273745/ffdfe09a-8ea2-11e5-8f02-f66cc8dcd95c.png)

**Comment by designsimply** [comment]
Closing this as it should theoretically be an edge case when no scans have happened yet, and the extra information to note that scanning is queued can probably be inferred.
