### ISSUE TITLE
Post: Visit site link on big screen is out of sight

### ISSUE THREAD

**Issue by mikaelz** [Automattic/wp-calypso#17125]
On a big screen (24" currently for me) at https://wordpress.com/read/feeds/34602574/posts/1555459826 I had search the _VISIT SITE_ link.

How about moving it closer to the article to be it in the view while eye scaning. I had to travel the whole page with my eyes :D

![ss_2017-08-11-06-33-44](https://user-images.githubusercontent.com/454800/29201612-0c1faec2-7e60-11e7-883b-dda43ed86706.jpg)
 

I expected the link by the Share and Like actions.

![ss_2017-08-11-06-33-30](https://user-images.githubusercontent.com/454800/29201587-d6dd7cf8-7e5f-11e7-9e7c-ba60458c1a46.jpg)

**Comment by fraying** [comment]
The Visit Site link is at the top, right as a standard location. It's also top, right on a mobile browser. We keep it there on large screens to be consistent. 

Note that you can also click the headline to do the same thing.
