### ISSUE TITLE
Reader Conversations: Clicking "Reply" should show the reply box

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17137]
In Conversations, each comment has a "Reply" link. Clicking it currently sends the user to the Fullpost page. But it should show the commenting interface (like on Fullpost).

<img width="833" alt="screen shot 2017-08-11 at 11 10 38 am" src="https://user-images.githubusercontent.com/24388/29226126-bb46fa16-7e85-11e7-9764-dcdab71cbe5c.png">

**Comment by samouri** [comment]
done.
