### ISSUE TITLE
Reader Conversations: Each post should end with a comment box.

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17138]
In Conversations, each post should end with a comment box. Like so:

<img width="569" alt="screen shot 2017-08-11 at 11 14 40 am" src="https://user-images.githubusercontent.com/24388/29226285-4db93f08-7e86-11e7-8a27-2b1b4c3c9de9.png">

It should behave just like on Fullpost: clicking into it expands it, submitting it replaces it with the comment.

**Comment by samouri** [comment]
full-post behavior has been replicated. closing
