### ISSUE TITLE
Reader Conversations: Remove "Show X reply" boxes

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17140]
Conversations tool is currently displaying "Show X reply" boxes in the comments, like so:

<img width="773" alt="screen shot 2017-08-11 at 11 25 01 am" src="https://user-images.githubusercontent.com/24388/29226708-d666b5dc-7e87-11e7-81c2-22c70b1a2de4.png">

I think these are just bugs. Usually the comment right after them is the reply. We should remove these (unless I'm missing something).

**Comment by blowery** [comment]
I assume these should be displayed as nested comments with the nesting arrow? Not as linear comments with no indication of their relationship?

**Comment by fraying** [comment]
@blowery Yes please.

**Comment by blowery** [comment]
Perfect. This'll get done as part of redoing how we show comments in general. 

cc @samouri

**Comment by samouri** [comment]
I'm pretty sure these are all gone...

closing.
