### ISSUE TITLE
Store: Clicking the "Settings" link in the breadcrumb takes you to the dashboard

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17167]
#### Steps to reproduce
1. Visit any settings page
2. Click "Settings" link in breadcrumb

#### What I expected
Be sent to the settings default page, in this case "Payments"

#### What happened instead
I was sent to the dashboard.

**Comment by kellychoffman** [comment]
Weird. This happens for you on every Settings page? This is only happening for me when I click the Settings link on the Taxes page.

**Comment by jameskoster** [comment]
Ah, you're right, it's not every screen. It happens on:

* Payments screen
* Taxes screen

Shipping is fine.

**Comment by dechov** [comment]
Looks like https://github.com/Automattic/wp-calypso/pull/15497 had [fixed this](https://github.com/Automattic/wp-calypso/pull/15497/files#diff-2366eac120281cf4e7befb27ac263a82R18) but scoped to Shipping screen only.
