### ISSUE TITLE
Comments: Edit comment endpoint

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#17164]
This is what WP Admin allows to edit:

<img width="946" alt="screen shot 2017-08-14 at 10 55 22" src="https://user-images.githubusercontent.com/2070010/29267096-2493a590-80df-11e7-8b61-df4ab32a922e.png">

This is what the `POST /sites/$site/comments/$comment_ID` endpoint currently allows to edit instead:

<img width="604" alt="screen shot 2017-08-14 at 10 56 44" src="https://user-images.githubusercontent.com/2070010/29267135-57db11c2-80df-11e7-9ed8-851590892b06.png">

Let alone the fact that the changing the `date` might be questionable, we are missing all the author details info.

**Comment by Copons** [comment]
Apparently it doesn't look like there's an actual limitation on what we send to the endpoint, as long as the keys are these:

```php
$keys = array( 'comment_post_ID', 'comment_content', 'comment_author', 'comment_author_email', 'comment_approved', 'comment_karma', 'comment_author_url', 'comment_date', 'comment_date_gmt', 'comment_type', 'comment_parent', 'user_id', 'comment_agent', 'comment_author_IP' );
```

**Comment by kwight** [comment]
Data accepted by the endpoint is limited by the endpoint's `request_format` shown [here](https://github.com/Automattic/jetpack/blob/master/json-endpoints.php#L1936), and it looks like the `comment_` prefix needs to be dropped, as it is handled [here](https://github.com/Automattic/jetpack/blob/master/json-endpoints/class.wpcom-json-api-update-comment-endpoint.php#L167).

**Comment by kwight** [comment]
https://github.com/Automattic/jetpack/pull/7698 has been merged, but I've noticed that the `author` object that comes back from a successful edit won't have the updated info in the case of logged-in comment authors; see https://github.com/Automattic/jetpack/pull/7707

**Comment by gwwar** [comment]
Did we still need this one @kwight ?

**Comment by kwight** [comment]
No; for our needs, https://github.com/Automattic/jetpack/pull/7698 covered it. https://github.com/Automattic/jetpack/pull/7707 is just responsible cleanup, but not used by comments at all.

**Comment by vindl** [comment]
If I'm reading the backlog correctly we can close this issue and move it to `Done`. I'm going to do that, feel free to reopen it if you think it's still necessary.
