### ISSUE TITLE
Reader: Empty state illustration for Conversations Tool

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#17184]
We need an empty state illustration for the Conversations Tool using the new style.

**Comment by fraying** [comment]
Nice work, @jancavan! I'm working on a copy revision. One note: There'll be more than one line of copy on the page empty state – assume a paragraph – so factor that in to the design.

**Comment by fraying** [comment]
@jancavan One design suggestion. On the banner, what do you think about making the illo a tad smaller so we can show the table. I think it helps the figures seem more grounded. Like....

<img width="666" alt="screen shot 2017-10-03 at 8 50 21 am" src="https://user-images.githubusercontent.com/24388/31134830-1b3eb664-a818-11e7-9f7d-36de8418b22f.png">

**Comment by fraying** [comment]
Copy iterations below.

Our challenge is to communicate that Conversations is only for WordPress posts (leaving out the .com here assuming we get jetpack comments included). We also need to communicate that the user has to like or comment on a post for it to appear. The trick is to include the detail without getting too technical.

Conversations Empty Page:

> **Welcome to Conversations**
> 
> When WordPress posts spark lively conversations, they'll appear here. To get started, like or comment on some posts.
> 
> ( Find Posts to Follow )

Conversations Intro Box:

> **Welcome to Conversations.** You can read and reply to all your conversations in one place. WordPress Posts you've liked or commented on will appear here when they have new comments.
