### ISSUE TITLE
Reader: Sites I'm already Following are showing up on my Search recommendations

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#17198]
![screenshot 2017-08-14 15 55 31](https://user-images.githubusercontent.com/4924246/29295560-dd356bd6-8109-11e7-9b2c-1b0ed59150ec.png)

These are sites I've already been following in the past.

/cc @aaronyan

**Comment by fraying** [comment]
I haven't seen this in a while. 

@aaronyan: did this get fixed?

**Comment by aaronyan** [comment]
Yep, thanks for the report @jancavan! and thank you for the reminder @fraying!

I've released a fix in changeset 162908 that prevents recommendations from suggesting posts from sites you follow.

**Comment by fraying** [comment]
🎉
