### ISSUE TITLE
Searching for a domain during signup shows warning on non-TLD search term

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#17199]
This seems to be a regression recently introduced as not reproducible on the WordPress.com desktop app.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start (https://wordpress.com/domains/add/ is OK)
2. Proceed to domains
3. Enter a search term like 'baseball'

#### What I expected

I didn't expect to see a warning that 'baseball' is taken as baseball isn't a TLD

#### What happened instead

Warning shown that baseball is taken

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

<img width="1209" alt="screen shot 2017-08-15 at 11 00 23 am" src="https://user-images.githubusercontent.com/128826/29298211-81d8e2c2-81a9-11e7-9bda-433a48a8924f.png">

**Comment by klimeryk** [comment]
Actually, `.baseball` _is_ a TLD (part of the very wide range of new TLDs...). It's not offered on wpcom yet, so like you said, this is very much a regression, so thank you very much for bringing this to our attention 🙇
I've reproduced this on Domain Search in Domain Management too - search for an unsupported TLD and then search for any keyword, you'll get some weird notice:
![ftppiavpf8](https://user-images.githubusercontent.com/3392497/29313815-d6d2c4f2-81bb-11e7-868d-768bbb1e49d2.gif)
@delputnam, is this something you could have a look at?

**Comment by delputnam** [comment]
Yep. I'll look into this today. I think I know what the issue is.

**Comment by alisterscott** [comment]
Thanks for the quick fix 🙏
