### ISSUE TITLE
Jetpack Scan: use "Jetpack" instead of "VaultPress" in SSH Key

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#172]
The generated SSH key finishes with “VaultPress”. Let's have it finish with “Jetpack” instead.

![screen shot 2015-11-19 at 9 57 03 am](https://cloud.githubusercontent.com/assets/11487924/11273912/ec3f371a-8ea3-11e5-8e6e-4cf36e3821ae.png)

**Comment by designsimply** [comment]
Tested and confirmed with the following steps:

1. Go to https://wpcalypso.wordpress.com/settings and select a Jetpack-connected site
1. Click Security in the header bar
1. Click Activate or Edit in the Jetpack Scan box
1. Click the "Get your public key string." link (bottom of the box)
1. Check to see whether "VaultPress" or "Jetpack" appears at the end of the string

<strong>Result:</strong> string ends in "VaultPress"

<img width="1280" alt="screen shot 2016-04-21 at thu apr 21 10 07 54 am" src="https://cloud.githubusercontent.com/assets/1119271/14718121/9f19a856-07a9-11e6-8cb5-fbf66bef9300.png">
<sup>Seen at https://wpcalypso.wordpress.com/settings/security/wildly.disambiguously.com using Firefox 45.0.1 on Mac OS X 10.11.13</sup>
