### ISSUE TITLE
Jetpack Plans: Expiration notice with 1 year left on plan

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#17205]
Yesterday, while testing setting up Jetpack with a Premium plan I stumbled upon an non-dismissible notice, urging me to renew my plan, because it's going to expire. The plan had just been activated and has 1 year left on it. 

It's a bit confusing to see the notice there, since I have just purchased the plan. It would be better to show the notice a few months before the plan expires, but not right after purchasing.

Note: The plan was purchased with credits.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/
2. Open a site's manage plan screen

#### What I expected
To not see a plan renewal notice, since I just purchased my plan

#### What happened instead
There's a non-dismissible notice showing that my plan will expire

#### Browser / OS version
Chrome 60.0.3112.90 on macOS Sierra 10.12.6

#### Screenshot / Video
<img width="738" alt="screen shot 2017-08-14 at 15 28 11" src="https://user-images.githubusercontent.com/184938/29307403-655bd040-81aa-11e7-894a-03a9c2a92340.png">
(added colored labels for the strings in my local language)

**Comment by rachelmcr** [comment]
There's an open issue for this message (with some additional discussion) here: https://github.com/Automattic/wp-calypso/issues/732
