### ISSUE TITLE
Publish Confirmation Step for Pages shows Posts in text

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#17203]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/page/ (ensure AB test is set to active for post publish)
2. Click "Publish..."

#### What I expected

`Almost there! You can double-check your page’s settings below. When you’re happy, use the big green button to send your page out into the world!`

or

`Almost there! You can double-check your page’s settings below. When you’re happy, use the big green button to schedule your page!`

#### What happened instead

`Almost there! You can double-check your post’s settings below. When you’re happy, use the big green button to send your post out into the world!`

or

`Almost there! You can double-check your post’s settings below. When you’re happy, use the big green button to schedule your post!`

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

<img width="966" alt="screen shot 2017-08-15 at 5 11 36 pm" src="https://user-images.githubusercontent.com/128826/29305697-55c23a88-81dd-11e7-8e62-670d0f373866.png">

**Comment by jonathansadowski** [comment]
Thanks for the report. This was fixed in #17511.
