### ISSUE TITLE
My Sites: clicking View Site with command no longer opens site in new tab

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#17212]
#### Steps to reproduce
1. Starting at URL: visit WordPress.com in a desktop browser logged into an account with at least one site
2. Click My Sites
3. Hold Command (Mac) on your keyboard and click My Sites
4. https://wordpress.com/view/example.com opens in a new tab instead of directly opening example.com

#### What I expected
example.com to open in a new tab

#### What happened instead
https://wordpress.com/view/example.com was opened in a new tab

#### Browser / OS version
Reproduced in Firefox 54.0, Safari 10.1.2, and Chrome 60.0.3112.90 on Macintosh OS X 10.11.6

#### Context / Source
#reallife #dogfooding

We'd also love to know how you found the bug: #dogfooding, #manual-testing

**Comment by lancewillett** [comment]
I was able to get this to work in Safari 10.1.2 on OS X 10.12.6 — Cmd key and single click opened the  front-end site in a new tab. "Works for me."

**Comment by kriskarkoski** [comment]
@lancewillett Can you try again from wpcalypso? I can't repro unproxied on WordPress.com, but can on wpcalypso so perhaps something that hasn't shipped fully yet.

**Comment by lancewillett** [comment]
Yes, I was on wpcalypso already — sorry I didn't add that detail.

**Comment by kriskarkoski** [comment]
I will update OS X to see if that's it. Here is a screencast of what happens to me:

![screen capture on 2017-08-16 at 14-15-23](https://user-images.githubusercontent.com/1900444/29381376-fd1dcf0e-8296-11e7-8c63-003a993064ab.gif)

**Comment by lancewillett** [comment]
OK! I can repeat that on a WordPress.com subdomain — it opens in the new tab, but with the `view` URL still in Calypso, not the front-end of the site as expected in its own URL.

Looks like in my own anecdotal testing, custom domains work as expected though — which explains why lance.blog worked OK.

@kriskarkoski Can you double check that with a custom domain?

**Comment by kriskarkoski** [comment]
I experienced the issue with all sites I tested, including simple WP.com sites with a custom domain, AT sites, and sites with just the default .wordpress.com address.

**Comment by lancewillett** [comment]
@jblz Could Samus take a look at this one please?

**Comment by jblz** [comment]
Sure thing. We should try to add a test when we fix this as well.
