### ISSUE TITLE
Comments: Comment "Edit" link in front end.

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17221]
Once we have comment editing in Calypso, how will we link `edit` actions from a user's site to the comments management route?

![screen shot 2017-08-15 at 11 21 27 am](https://user-images.githubusercontent.com/1270189/29329819-f50a3690-81ab-11e7-9f9d-6e7f3c736dcf.png)

Clicking on `Edit` above currently takes us to https://helpingcat.wpsandbox.me/wp-admin/comment.php?action=editcomment&c=122

We'll need to be able to directly link to a comment specific view with the editor open.

We'll want to add route similar to `/comments/approved/{siteId}?commentId={commentId}&action=edit`

I suppose if we click on another filter like `spam` in the UI, we'd drop the query params?

**Comment by kwight** [comment]
There is a filter `edit_comment_link` in the core `edit_comment_link()` [function](https://developer.wordpress.org/reference/functions/edit_comment_link/) that themes use to output this markup.

On the dotcom side, adding a filter for this will be simple enough; on the Jetpack side, we can add the same, maybe tied to the activation of [Calypso redirects](https://github.com/Automattic/jetpack/pull/7967).

**Comment by kwight** [comment]
Jetpack PR: https://github.com/Automattic/jetpack/pull/8069
dotcom: d8002-code
