### ISSUE TITLE
Comments: On first load, automatically switch to Approved list when there are no Pending comments (the Pending list is empty).

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17222]
We received feedback that folks were confused when looking at an empty pending view, expecting to see any comments for their site.

@Copons what's the behavior if they switch sites in pending or click into comments management without reloading the page?

**Comment by Copons** [comment]
I'm not sure I got the question right.

The confusion is that Pending is the default view.
I'd argue that in a large majority of cases (_scientifical fact_ based on my own WP sites 🙂 ) comments are simply open to everybody, without pre-approval.
In these cases, new comments can be `approved` or sent as `spam` by, say, Akismet. But they never start as `unapproved`.
Therefore, the Pending list is always empty (except for comments manually unapproved).

But even for sites with comments moderation, there can be times when one simply does not have any unapproved comment.
And it is indeed a bit odd to open the Comment section on an empty list.

**Comment by gwwar** [comment]
The use case would look like:

- I visit /comments/pending/{siteA}
- I use the site picker, which takes me to /comments/pending/{siteB}

**Comment by Copons** [comment]
Oh, got it.
It maybe should go to Approved as well?
Like treating the site picker as a full reload.

**Comment by gwwar** [comment]
If we add the the all view, this becomes unnecessary.
