### ISSUE TITLE
Editor: display loading indicator while galleries and embeds load

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1726]
Raised by @aduth 

Currently, when the preview for an embed or gallery is being loaded, an empty block is shown in the editor, and it's not obvious that it will be replaced by a preview. Instead, while loading, we should display a placeholder block, spinner, or otherwise indicate an embed block exists in the post content. ([9s](https://cloudup.com/cJNRm10K6Qe))

![embed](https://cloud.githubusercontent.com/assets/1779930/10616893/6c3b9de0-7735-11e5-8643-5b336e844782.gif)

**Comment by rachelmcr** [comment]
This will be resolved with the embed block and embed loading indicator in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
