### ISSUE TITLE
Invitations: Cannot send invitation to a user with a custom role

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#17261]
#### Steps to reproduce
0. Set up a Jetpack site with a plugin that adds custom roles (e.g. WooCommerce)
1. Go to https://wordpress.com/people/new/:site in Calypso
2. Attempt to send an invitation to a user using one of the custom roles (e.g. Shop Manager)
3. Get an error

#### What I expected
To be able to invite a user to my site using any of the available roles, or at least to be told that I can't send invitations for non-core roles perhaps.

#### What happened instead
I got an error which appears to be triggered because of the custom role: "Invitation failed to send"

#### Browser / OS version
Chrome, macOS

**Comment by elibud** [comment]
@lezama this one should be fixed by your recent changes, right?

**Comment by lezama** [comment]
right! Inviting users with a custom roles works 👌 now

See: https://github.com/Automattic/wp-calypso/pull/18363 for more details

**Comment by lezama** [comment]
(site needs to be running JP >= 5.4)
