### ISSUE TITLE
Plugins: Misaligned labels on all-sites view of single plugin

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#17260]
#### Steps to reproduce
1. Set up a Jetpack site and disable autoupdates via [setting](https://jetpack.com/support/site-management/#file-update-disabled) the `DISALLOW_FILE_MODS` constant in `wp-config`
2. Install a plugin on that site
3. Visit the plugin detail page (for all sites) for the plugin within Calypso (e.g. `/plugins/:plugin`)
4. Expand the "Installed on" card for that site
5. Observe misaligned label for "Autoupdates disabled"

#### What I expected
All labels to be lined up properly.

#### What happened instead
"Autoupdates disabled" label is missing some margin on the left.
<img width="775" alt="screen_shot_2017-08-16_at_4_56_56_pm" src="https://user-images.githubusercontent.com/108942/29388891-561b1118-82a4-11e7-875f-f41f218e8fb5.png">

#### Browser / OS version
Chrome, macOS

#### Context / Source
#reallife #dogfooding #manual-testing

**Comment by iamgabrielma** [comment]
@beaulebens  I was trying to work on this but I'm having problems reproducing this issue:

Disabled auto-updates via `define('DISALLOW_FILE_MODS, false)` in wp-config.php, also I tried leaving it undefined and `define('AUTOMATIC_UPDATER_DISABLED', true); `

I follow the rest of the process for the settings above but when I go to the plugin detail page, for example here: https://wordpress.com/plugins/hello-dolly I couldn't see your second screenshot, where the auto-updates are disabled.

<img width="670" alt="screen shot 2017-08-31 at 18 48 29" src="https://user-images.githubusercontent.com/3812076/29934862-09b73c72-8e7d-11e7-8ffb-ac2723d2b044.png">

Finally going to the debug link at the bottom of Jetpack screen I could find the individual "Manage" module in the URL > https://yourdomain.com/wp-admin/admin.php?page=jetpack_modules , and deactivate it, but still nothing changed:

<img width="631" alt="screen shot 2017-08-31 at 18 57 41" src="https://user-images.githubusercontent.com/3812076/29935215-4bfc3ca8-8e7e-11e7-94ed-f30c089c2210.png">

**Comment by beaulebens** [comment]
Note that the `DISALLOW_FILE_MODS` is a bit of a double-negative in this case, and I believe you actually want to set it to `true`. Once you've done that, you probably need to do a quick disconnect/reconnect of Jetpack to force that value to sync properly as well (or you can "initiate a sync manually" via the "Settings > Manage your connection" menu in Calypso).
