### ISSUE TITLE
Plan thank you: Exit warning leaks between plan thank yous

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#17279]
It's possible to get an erroneous "not finished" warning when exiting the plans page.

#### Steps to reproduce
1. Purchase a Jetpack that takes you to the new Thank You page.
1. Navigate away before the plan setup is finished (accept the confirm dialog).
1. Purchase a WordPress.com plan that takes you to the "Thank you" page.
1. Navigate away from the WordPress.com thank you page.
1. You will see the confirm dialog from the Jetpack thank you page.

#### What I expected

This dialog shouldn't be shown.

#### What happened instead

It is.

#### Screenshot / Video

![weird](https://user-images.githubusercontent.com/841763/29402856-cb7d87fa-8336-11e7-81e0-268a18329fbc.gif)

#### Context / Source

Discovered while testing #17245 (https://github.com/Automattic/wp-calypso/pull/17245#issuecomment-323004611).

@tyxla tracked this down to a likely problem here in `page.exit`:

https://github.com/Automattic/wp-calypso/blob/8d81eb6e9e58e2de221fb9582d6fec81241d2e4c/client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx#L130

/cc @oskosk

**Comment by gwwar** [comment]
I can't repro this, but when navigating away, I see two exit warnings appear before I'm able to leave the page.

**Comment by gwwar** [comment]
Please reopen if folks find otherwise.

Also there's a good amount of duplication between `jetpack-thank-you-card` and `jetpack-plugins-setup` did we forget to remove the thank you file?
