### ISSUE TITLE
Editor: images should respect height attribute

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1727]
Raised by @gwwar 

In the html tab of the [editor](https://wordpress.com/post) we respect set width, but not height when it is the only dimension attribute set.

When clicking back to the visual tab, the following is properly sized:

```
<img src="http://i.imgur.com/SaxpuCP.gif" width="100" />
```

But this is not:

```
<img src="http://i.imgur.com/SaxpuCP.gif" height="100" />
```

HTML tab:
<img width="734" alt="screen shot 2015-10-20 at 12 18 23 pm" src="https://cloud.githubusercontent.com/assets/1270189/10618436/b984aca6-7724-11e5-9dce-3a3a497d4cee.png">

Visual Tab
<img width="732" alt="screen shot 2015-10-20 at 12 18 32 pm" src="https://cloud.githubusercontent.com/assets/1270189/10618440/beefbcda-7724-11e5-8d5d-5ddb59282368.png">

Note from @aduth 

> Noting that this is consistent with the wp-admin treatment for the `twenty*` series of themes.

**Comment by rachelmcr** [comment]
Closing as this is not an issue in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
