### ISSUE TITLE
Editor: add embed discovery / searching

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1728]
Raised by @aduth 

Currently when adding an embed to a post, a user must know to insert a link from a supported embed service. We should seek to improve this flow by informing the user of supported services and/or offering simple mechanisms for inserting embeds from those services.

For example, in wp-admin there are a handful of options available in the media modal for adding an embed:

![11258](https://cloud.githubusercontent.com/assets/1119271/11872460/69353264-a4a3-11e5-8eb6-a8a0a8afe0da.png)

**Comment by lancewillett** [comment]
Superseded by #5070 — better way of adding embeds to a post or page.
