### ISSUE TITLE
Activity Log: hide Site/Store toggle

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17291]
We should that hide the Site/Store toggle? It’s not relevant to the AL and doesn’t filter the view at all.

Maybe in the same place we'll add the filtering options later on.

### Before

![image](https://user-images.githubusercontent.com/390760/29419368-e0f15276-8366-11e7-958e-37f747c89b61.png)

### After

![image](https://user-images.githubusercontent.com/390760/29419392-f0038f36-8366-11e7-8b0e-454c94d5d126.png)

**Comment by sirreal** [comment]
@keoshi See conversation in #17063 

The toggle is present across all stats sections if the site has a WooCommerce store. Should we keep it for consistency?

/cc @psealock

**Comment by keoshi** [comment]
That control seems relevant for some tabs (Days, Weeks, Months, Years) but not for the Activity Log or Insights. It's difficult to make a decision because the toggle is effectively the main switch for the entire page and affects navigation as well: rather than a filter it's a context changer.

The position it's in makes it very confusing and unclear because the hierarchy in navigation is not well represented. Because the entire Stats page changes when context between Site and Store does, I think this warrants a higher-level switch. This is a bad mock, but it conveys the idea I'm trying to illustrate:

![image](https://user-images.githubusercontent.com/390760/29456440-88b455e8-840d-11e7-9745-4ca32d2d3fe0.png)

Ping @folletto since you might have thought about this already.

**Comment by folletto** [comment]
> The position it's in makes it very confusing and unclear because the hierarchy in navigation is not well represented.

Yep. The IA is all over the place.

This has been a very complex solution, that keeps popping up. I feel we're at a moment where we should take a step back and have a wider discussion encompassing the IA for the stat section when we consider everything as well as how to introduce two levels in navigation bars if/when needed (and if not, what's our position on the matter).

Maybe a P2 post to start exploring this?

**Comment by keoshi** [comment]
@psealock has posted a few proposals here: p8vlZR-tM-p2
