### ISSUE TITLE
Activity Log: replace 'available' events' author

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17297]
Update available events should be shown by Jetpack or the site blavatar, not an administrator.

### Before

![image](https://user-images.githubusercontent.com/390760/29420935-6456a5f4-836b-11e7-9902-5c9acc838c71.png)

### After

![image](https://user-images.githubusercontent.com/390760/29421047-b68515ea-836b-11e7-847f-bbb8b02798ca.png)

**Comment by sirreal** [comment]
The actor is defined elsewhere, migrated to 66-gh-action-to-activity-log
