### ISSUE TITLE
Editor: add embed editing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1729]
Raised by @aduth 

We should determine if and how we want to support editing embeds present in a post's content. In wp-admin, the edit option presents a user with a dialog, allowing them to change the URL of the existing embed. This could be useful in cases where a user may want to e.g. replace the existing YouTube video with an alternate video.

![11259](https://cloud.githubusercontent.com/assets/1119271/11872741/f3bfb52a-a4a4-11e5-9374-1fa44841b73a.png)

Note from @ryanboren 

> Editing a url in the context of the media modal is crowded and confusing. The edit modal for bare link embeds need only a field for changing the url. Without an edit modal, you must flip to HTML to change the link.
> 
> Pasting these links seems to most common flow. When I paste the wrong link, I usually delete the embed via the X in the inline toolbar and then paste the correct link. I don't recall ever needing an edit modal for embeds in my flows.
> 
> Not everyone is down with copy a paste, however. I bet there are many more manual flows out there that would benefit from having an edit modal. We should avoid sending people to HTML mode.

Note from @folletto 

> I was thinking this too. URL-based embeds to me feel that are 99% of the times copy-pasted, so making sure you can remove and re-paster, and even paste-over to replace, would be a good behaviour that would cover most of the scenarios.

Note from @ryanboren 

> I just tried manually typing in embed link in core and calypso. Neither embed on return. So, bare link embeds seem entirely cut-and-paste dependent. Showing the link in the inline toolbar like the inline link toolbar does might be nice. Otherwise you have to switch to HTML mode to peep the link.
# calypso-gaps

**Comment by drw158** [comment]
Here's my suggestion:

Add an "Insert Embed Link" item to the insert media dropdown as seen in #5070

![72a65c6a-0cc2-11e6-9e43-915999e507a8](https://cloud.githubusercontent.com/assets/618551/22218060/f541468a-e16a-11e6-9b29-7ae2aeaceee7.png)

This would show a simple modal with one input field, `url`.

Once it's embedded into the post, clicking on it would show an edit icon as well as the remove icon. Edit would show the same modal, and allow users to see and replace the url for the embed.

**Comment by folletto** [comment]
Yes! Let's expand the patterns of the universal editor insert! :D 

> This would show a simple modal with one input field, url.

This is great for i1, in the future would be cool to expand a bit in that modal with a message that explains what embed links are and so on. :)

**Comment by shaunandrews** [comment]
Here's a quick flow for how you could edit embeds based on @drw158's comment above:

![embeds](https://user-images.githubusercontent.com/191598/28643491-ffbfa558-7223-11e7-8402-0bfe1437a678.gif)

That's using the standard media modal, but its a little empty. We could stray from the pattern a bit and do something like this maybe:

![embed details copy](https://user-images.githubusercontent.com/191598/28643536-23f2e318-7224-11e7-8fd1-9a889d53b594.png)

**Comment by lancewillett** [comment]
@jblz Could Samus coordinate on this with Link? Shaun's got a start here, needs someone to take it.

**Comment by jblz** [comment]
Sure -- added myself to the assignment list & will get it on our board

**Comment by iandunn** [comment]
#17152 is merged now, which lets people edit the URL without a preview:

<img src="https://user-images.githubusercontent.com/484068/31040563-a5c6da24-a53d-11e7-80cc-0e7d7c535e73.png" alt="Screenshot of editing URL without preview" />

The next step is to add a preview of the new URL in #18171.

**Comment by lancewillett** [comment]
Merged with ee273bb
