### ISSUE TITLE
Activity Log: hide ‘unknown’ type events from the UI

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17296]
Don't show post type=null.

![image](https://user-images.githubusercontent.com/390760/29420817-135d2ccc-836b-11e7-8067-2761dc9087b4.png)

**Comment by sirreal** [comment]
This would be better handled before these Activities even get to the UI. Filtering them from the UI could result in:
* Problems with event counting
* Problems with inconsistent paging

I've opened 67-gh-action-to-activity-log to hopefully correct this before these events even get to the UI.

**Comment by keoshi** [comment]
Agreed, thanks for creating that!

**Comment by sirreal** [comment]
Closed in favor of  67-gh-action-to-activity-log
