### ISSUE TITLE
Activity Log: style 0-events day blocks differently

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17294]
Style day blocks with zero events differently:

- Hide ‘rewind’ button on those.
- Remove expanding chevron.

### Before

![image](https://user-images.githubusercontent.com/390760/29420461-ed34b82c-8369-11e7-92a3-da2b3d60f4b4.png)

### After

![image](https://user-images.githubusercontent.com/390760/29420400-cde8c544-8369-11e7-8a38-55ac15f66e27.png)

**Comment by sirreal** [comment]
This seems very strange to me. Is the before screenshot from live AL?

"empty" days should be omitted. Here's the branch I'm looking at now:

![omitted](https://user-images.githubusercontent.com/841763/29457664-ae5af870-841b-11e7-8046-71a702ed9eb1.png)

Note that the 16th and 17th simply don't appear.

**Comment by sirreal** [comment]
The screenshot with included empty days probably indicates a timezone bug 😩 

For this issue, we either need to include all days in a month and add some special handling, or leave the behavior as-is.

**Comment by keoshi** [comment]
@sirreal Sorry about the confusion — I fabricated those to illustrate the point: those are purely mocks, not the real thing.

@rickybanister and I had the same conversation yesterday about hiding or showing empty days, and decided they might be useful to denote a lack of activity but still display them to show the value it provides.

I do have a reservation though: when we clean up the actions we're getting (`type=null` issue) we might get a lot of _silent days_, so that might be a good time to revaluate whether we display all days or hide empty ones.

**Comment by rickybanister** [comment]
I think there will always be some value in showing the empty days, perhaps the styles for them requires a bit more work—I notice you left the date styles the same (bold, dark) which makes it easier to read, but harder to tell it's an empty day. Perhaps empty days could take up less vertical space, or perhaps we should represent them with the entire card dulled out (as you originally mocked up) or perhaps without a card at all, just simply as the date on the background to indicate a total lack of content? Let's explore!

**Comment by sirreal** [comment]
👍  Thanks for the responses and context @rickybanister and @keoshi. I'll go ahead and get an empty day card ready.

**Comment by rickybanister** [comment]
Like this maybe @keoshi 

![image](https://user-images.githubusercontent.com/437258/29462230-a806b258-83fc-11e7-8a79-a6504c6146c4.png)

**Comment by rickybanister** [comment]
Also, my test site doesn't get that much activity, no traffic except mine, and it has events every day. I think it would require a very sedentary site to have no events (of course possible though)

**Comment by keoshi** [comment]
Hah, love that @rickybanister !!
