### ISSUE TITLE
Jetpack Scan: use 'cancel' instead of 'deactivate' to exit first-time set up

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#173]
When setting up Jetpack Scan for the first time, a user sees this screen:

![c716cd00-2967-11e5-8ac6-7ff46b685c26](https://cloud.githubusercontent.com/assets/11487924/11273994/5a33c2fe-8ea4-11e5-8ca5-7c6b0d944963.png)

If the user wanted to abandon the set up, they'd have to click the deactivate link. But, because Jetpack Scan has not yet been activated, that text isn't entirely correct and can be confusing. 

How about replacing it with a 'Cancel' link like this:

![cc9fd12c-2967-11e5-9193-ce628da903a3](https://cloud.githubusercontent.com/assets/11487924/11273995/5e8a9d00-8ea4-11e5-8d4b-84e5772cb7b4.png)

**Comment by designsimply** [comment]
@v18, what are the steps for setting up Jetpack Scan? 

I looked in Jetpack > Settings on my site and couldn't find it in a search, and I also tried searching for "Jetpack Scan" at https://jetpack.com/support/

**Comment by designsimply** [comment]
Figured it out! It's in beta and currently available for testing at https://wpcalypso.wordpress.com/

Closing this issue as a duplicate of #175
