### ISSUE TITLE
Plugins: Incompatible plugins need to be disabled for Atomic sites in "All My Sites" view

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#17305]
#### Steps to reproduce
0. Make sure you have an Atomic site on your account.
1. Starting at URL: https://wordpress.com/plugins/wp-super-cache
2. Under "Available sites" click the "Install" button on an Atomic site.
3. In the sidebar, select "Switch Site" and choose the same Atomic site.

#### What I expected

I expected that in both places, the ability to install the plugin would be blocked since it's an incompatible plugin.

#### What happened instead

There's an "Install" button next to the Atomic site on the plugin's page with the "All My Sites" view (no specific site selected). Selecting it returns the error "An error occurred while installing WP Super Cache."

Installing the plugin is blocked (as expected) when you select the Atomic site in the sidebar. Under the plugin description there, you'll see a yellow warning "Incompatible plugin: This plugin is not supported on WordPress.com." There's no option to install the plugin from there.

#### Browser / OS version

Chrome 60.0.3112.101 / Mac OSX 10.12.6

#### Screenshot / Video

"All My Sites" view:

![screen shot 2017-08-17 at 5 46 29 pm](https://user-images.githubusercontent.com/8658164/29423798-0066c722-8375-11e7-91d0-fc1c89e54f3e.png)

Atomic site selected:

![screen shot 2017-08-17 at 5 45 11 pm](https://user-images.githubusercontent.com/8658164/29423867-4c027960-8375-11e7-95b7-ea98b442d097.png)

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
I retested this issue and it's still possible to install unsupported plugins this way. However, there's no longer a generic error message.

The steps to reproduce are the same, but when you install the plugin from the All Sites view it now shows a success message:

![screenshot 2018-08-28 11 14 36](https://user-images.githubusercontent.com/8658164/44717305-91b20b80-aab4-11e8-9068-e90cc755088c.png)

When you view the installed plugin on the site, though, the plugin is disabled:

![screenshot 2018-08-28 11 15 34](https://user-images.githubusercontent.com/8658164/44717343-a4c4db80-aab4-11e8-85b8-8430848181dc.png)

I'm leaving this issue open, since the success message is inaccurate (the plugin wasn't activated) and the flow could be confusing to a user who expects the plugin to be working and doesn't notice that it's disabled.

**Comment by rachelmcr** [comment]
I also received the following email after trying to install this app on my atomic site:

> Dear User,
> 
> WP Super Cache was removed from your blog or deactivated but some files could
not be deleted.
> 
> /wpcom-134401705/wp-content/advanced-cache.php
> 
> You should delete these files manually.
> You may need to change the permissions of the files or parent directory.
> You can read more about this in the Codex at
https://codex.wordpress.org/Changing_File_Permissions#About_Chmod
> 
> Thank you.

This adds to the confusion that may be experienced after installing an unsupported app this way.

**Comment by Aurorum** [comment]
I opened #17305 which should fix this, but I'm not done with it yet. :)

<img width="876" alt="Screenshot 2020-01-22 at 19 18 02" src="https://user-images.githubusercontent.com/43215253/72926999-4d7c7680-3d4d-11ea-8cd4-f43c054e1422.png">
