### ISSUE TITLE
Editor: implement VideoPress in-editor previews

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1730]
Raised by @aduth 

We should seek to create a wpview extension for enabling previewing of VideoPress videos. Currently, when adding a VideoPress video to a post, only the shortcode text is shown in the editor post content. A user must wait until previewing the post on the front-end of their site before having an idea of how the video will appear.

There is currently no VideoPress preview offered in any editor on WordPress.com.

Related: 6413-gh-calypso-pre-oss

**Comment by lancewillett** [comment]
This needs a shepherd and development work to get the pull request #2267 in.

**Comment by lancewillett** [comment]
Tracking progress in https://github.com/Automattic/wp-calypso/pull/8342

**Comment by lancewillett** [comment]
Merged with https://github.com/Automattic/wp-calypso/commit/466e6b22d8afe6da31c6499a7c1a3e0a4627a5bc
