### ISSUE TITLE
Store: Add chevron to sidebar menu item

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#17311]
The current Store menu item in the sidebar doesn't show any indication that it's going to be replacing the sidebar. What if we added a right-pointing chevron to help indicate what's going to happen when you click it:

<img width="593" alt="screen shot 2017-08-17 at 4 00 14 pm" src="https://user-images.githubusercontent.com/191598/29431264-51d34f14-8365-11e7-894f-741821c39f2b.png">

**Comment by kellychoffman** [comment]
I dig it.

**Comment by lancewillett** [comment]
+1

**Comment by dechov** [comment]
The existing implementation looks good & works well except that the chevron itself isn't clickable despite looking like an action element and triggering the hover state.

Could be worked around more or less invasively, by either adding it directly into the `<SidebarItem>`'s `<a>` (like the "external" icon) controlled by a prop, or just styling the existing child `<Gridicon>`.

Not sure of the best solution for the latter but wrapping with this seems to work:
`<div style="position: absolute; right: 0; pointer-events: none;">`

**Comment by kellychoffman** [comment]
Good catch. 

> Not sure of the best solution for the latter but wrapping with this seems to work:

Did you want to create a new PR for this?
