### ISSUE TITLE
Editor: support audio playlists

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1731]
Raised by @aduth 

The `[playlist]` shortcode allows a user to create a playlist of audio items to display in a post:

![audio playlist](https://cloud.githubusercontent.com/assets/1779930/10637271/a41cf342-77d2-11e5-86ab-3b6c5f14e864.png)

In wp-admin, the flow is very similar to that of creating a gallery:

![11261](https://cloud.githubusercontent.com/assets/1119271/11872762/11d27df4-a4a5-11e5-845f-cab80c93faae.png)

We should decide whether we want to support creating audio playlists via the media modal, and if so, how that fits with the current media insertion flow. For example, we could assume that if multiple audio items are selected in the media modal, that the user intends to insert an audio playlist. This would be similar to how we treat multiple image selections.

Note from @folletto 

> A uniform way to deal with both looks sensible to me. :) 

Note from @Jstachurski 

> This has been requested by a user whose whole blog is built on making audio playlists. Also wanted to be able to edit the playlist from the Visual editor but now all you see are track IDs which isn't helpful if you don't know what song is what ID.

**Comment by thehenrybyrd** [comment]
Another request for this in #97317-chat.
Something to note here is that we have a few music-based Premium themes that don't use the `[playlist]` shortcode for audio. Having a built in way to create and edit a playlist would be great.

**Comment by spencerberry** [comment]
User requested again here: #8599560-hc

**Comment by scosgro** [comment]
Another request for this in #1838270-zen. Basically, the user didn't know how to create an audio playlist, because it's not available in Calypso. Had to point them to WP-Admin.

This isn't available in Gutenberg either, so wondering if a new Github needs to be made?

**Comment by scosgro** [comment]
Created a Gutenberg feature request for this here: https://github.com/WordPress/gutenberg/issues/14199

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen. We are tracking here: WordPress/gutenberg#14199
