### ISSUE TITLE
Editor: implement audio shortcode in-editor previews

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1732]
Raised by @aduth 

We should seek to create a wpview extension for enabling previewing of `audio` shortcodes. Currently, when adding an audio item to a post, only the shortcode text is shown in the editor post content. A user must wait until previewing the post on the front-end of their site before having an idea of how the audio will appear.

There is currently no `audio` shortcode preview offered in any editor on WordPress.com.

Related: 6413-gh-calypso-pre-oss

**Comment by iandunn** [comment]
#18171 adds a preview of embeds when editing their URLs, which includes audio files. Adding a new `wpcom-view` for audio is out of scope for that ticket, but seems like it'd fit in with this one.

<img width="998" alt="screen shot 2017-10-16 at 3 47 05 pm" src="https://user-images.githubusercontent.com/484068/31638594-5f9167d2-b289-11e7-9baa-4f083098ce88.png">

**Comment by alisterscott** [comment]
This should be addressed as a Gutenberg block so I'm closing this one for now.

#bug-scrub #pre-gutenburg-bug-purge
