### ISSUE TITLE
WPSC: Styling is inconsistent with JP Settings

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#17325]
Originally reported by @rachelmcr [here](https://horizonfeedback.wordpress.com/2017/08/17/call-for-testing-calypso-wp-super-cache-extension/comment-page-1/#comment-391):

> This is more of a style issue than about the functionality, but the way the extra information is styled in the WPSC settings (for example, “Compressions is disabled by default…”) is very different from how it’s styled with italics and/or the “i” popover icon in Jetpack settings.
> 
> Screenshots for comparison:

[WPSC:]

![screen shot 2017-08-17 at 6 33 24 pm](https://user-images.githubusercontent.com/96308/29457542-ea440ff8-841a-11e7-9f46-992c377ce4e0.png)

[Jetpack]:

![screen shot 2017-08-17 at 6 33 05 pm](https://user-images.githubusercontent.com/96308/29457544-edb6bf1e-841a-11e7-937b-7cf1b85e9078.png)

**Comment by MichaelArestad** [comment]
I would be happy to help advise a bit to get the settings visually aligned with the rest of Jetpack/Calypso.
