### ISSUE TITLE
Editor: update TinyMCE formatting bar icons to use gridicons

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1733]
Raised by @kellychoffman 

Currently:

![drop](https://cloud.githubusercontent.com/assets/5835847/10648986/19de07fe-7807-11e5-9485-397f06f9f378.gif)

Media is the only one updated. We should also update the `...` to be a chevron to be more consistent with other areas. (Ellipsis usually reveals a dialog when clicked/tapped)

**Comment by rachelmcr** [comment]
Closing as this is low priority and will be resolved with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
