### ISSUE TITLE
Currency Format: The dollar symbol should always be clear what Dollar is for.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#17339]
As you can see in `/client/lib/format-currency/currencies.js` the dollar symbol is used for 19(?!) different Dollars without being explicit. Since the symbol alone can mean differently for different people, I think Calypso should always print it explicitly, including USD.

What do you think?

**Comment by rachelmcr** [comment]
Definitely agree. This is being tracked in https://github.com/Automattic/wp-calypso/issues/1547 — closing this issue since I believe the other one covers it.
