### ISSUE TITLE
Store: Recently added calypso-preferences flags are missing from REST API console

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#17344]
The recently added `finished_page_setup` `created_default_shipping_zone` and `checked_tax_setup` flags are not displayed as fields in the REST API console. They should be like the others. ( POST /sites/{siteID}/calypso-preferences/woocommerce )

The fix for this issue is probably not in calypso, but calypso relies on this endpoint and but any correction to the endpoint should be tested against calypso, so opening this issue here

cc @justinshreve

**Comment by justinshreve** [comment]
I see them @allendav. I *think* the console might be caching help docs in localStorage or something. Can you try clearing things, re-authing on the console, and seeing if they are visible?

**Comment by justinshreve** [comment]
I'm going to close this I have only seen this once (after making multiple changes to the endpoint) and it was solved after clearing a few things. If we find a problem with the console in general, we can flag that on Operation API instead of here.
