### ISSUE TITLE
Comments: pingbacks and trackbacks

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17345]
This task adds the ability to moderate all comment types. Comments can be of [three types](https://codex.wordpress.org/Function_Reference/comment_type):

- comments 
- [ trackbacks ](https://en.support.wordpress.com/comments/trackbacks/)
- [ pingbacks ](https://en.support.wordpress.com/comments/pingbacks/)

I did a quick audit of wp-admin, and I believe we should be able to perform all the same actions for these types of comments, including editing the content.

### Outstanding Work

- [x] Needs an Endpoint Update for comments-tree to return these other 2 types. (We can prototype against the comments-list endpoint first). As a bonus if we return all types of comments our pager will no longer be fuzzy.
- [x] Update related comments-tree and comment-list query components
- [ ] If a site uses Jetpack, we need to do a version check to see which endpoint to hit.
- [x] Update design based on https://github.com/Automattic/wp-calypso/issues/15205

Most pingbacks and trackbacks tend to be spam, so let's try to make this into m2.

**Comment by gwwar** [comment]
cc @blowery @samouri would the reader ever need to display trackbacks/pingbacks?

**Comment by kwight** [comment]
D6974-code and https://github.com/Automattic/jetpack/pull/7671 add pingbacks and trackbacks to the comments tree endpoint for dotcom and Jetpack, respectively.

**Comment by samouri** [comment]
Reader displays them in certain view like the full-post one. [heres](https://wpcalypso.wordpress.com/read/blogs/27732138/posts/20026) an example.

**Comment by kwight** [comment]
Some questions about how to handle this:

 - Have we discussed how pingbacks/trackbacks will display to the user? I've seen #15205 , but I'm thinking about whether they are displayed in chronological order among all the other regular comments (I'm assuming yes? #15205 seems to imply that), and whether the user will be able to filter or isolate them in any way – `wp-admin` has a secondary dropdown below the segmented links for status:

<img width="817" alt="screen shot 2017-09-06 at 5 55 43 pm" src="https://user-images.githubusercontent.com/349751/30140910-b5d9c12e-932c-11e7-8f14-de5c7d37cd94.png">

 - Depending on the above, do we need or want any changes to the query components? Maybe we'd be better with replacing [this](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/sites/comments-tree/index.js#L40) with something that combines all comment types, so `state.comments.trees.siteID`s have all types? Or was the thinking to have a different tree per comment type in the store? Should we consider adding an option to the `comments-tree` endpoint that returns maybe a `combined_tree` with all types?

**Comment by gwwar** [comment]
@kwight I would say leave them inline for this m2, but we may want to be able to filter more explicitly by type in the future. 

Use your best judgement when updating the redux trees. We should be able to do it either way, and be able to create views using selectors. For flexibility I'm thinking we keep the pingbacks/trackbacks in their own tree(s), but you're welcome to go ahead with something else if there's good reasoning behind it.

**Comment by gwwar** [comment]
@Copons  @kwight  can we close this out?

**Comment by Copons** [comment]
@gwwar I'm unsure about
> If a site uses Jetpack, we need to do a version check to see which endpoint to hit.

What are we supposed to check specifically?

**Comment by kwight** [comment]
Noting that currently different types of comments have their own tree on the `comments-tree` endpoint, but [get combined into one tree](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/sites/comments-tree/index.js#L49) per site in the store.

**Comment by Copons** [comment]
@kwight Comments are sorted by ID before render.

**Comment by kwight** [comment]
> If a site uses Jetpack, we need to do a version check to see which endpoint to hit.

[If a site is a Jetpack site](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-list/index.jsx#L435), we currently use the Wp.com/Jetpack [comment list endpoint](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/comments/), which includes pingbacks and trackbacks.

Closing, nothing else to do here.

**Comment by gwwar** [comment]
All Jetpack sites are using the fallback currently, we have plans to update that in m3. The summary not is out of date.
