### ISSUE TITLE
Editor: scheduler doesn't show current time in RTL ui

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1735]
Raised by @kellychoffman 

RTL: (bug)
<img width="324" alt="screen shot 2015-10-21 at 3 36 11 pm" src="https://cloud.githubusercontent.com/assets/5835847/10649449/dd3255e6-7809-11e5-965d-da1c49fc27d3.png">

LTR: (bug free)
<img width="264" alt="screen shot 2015-10-21 at 3 37 32 pm" src="https://cloud.githubusercontent.com/assets/5835847/10649450/dd35dd06-7809-11e5-8d10-0a755369f2c4.png">

**Comment by yoavf** [comment]
WFM. It takes a second for the date to show on a new post since it depends on the new draft post object being loaded. However, the relative date isn't localized: #2731
