### ISSUE TITLE
Simple Payments. Create option to select donations.

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#17367]
Visitors to a site using the Simple Payments button are prompted to select the address where to send the item 'Delivery Address' and this could be -it is- messy in the case of donations.

![proceso de pago de paypal - revisar el pago 2017-08-19 17-49-21](https://user-images.githubusercontent.com/6404071/29488225-e69acbca-8506-11e7-8f9f-fede7b02e310.png)

Could we add a selector to choose Donations in the Simple Payments button from the Visual Editor and generate a button having into account this selection?

#user-report  641392-zen

**Comment by alisterscott** [comment]
Confirming this is still relevant and not yet implemented

#bug-scrub #pre-gutenburg-bug-purge

**Comment by rantoncuadrado** [comment]
I would say it is, even if I suppose the user could not be waiting anymore

**Comment by alisterscott** [comment]
Closing in favour of #19303
