### ISSUE TITLE
SImple Payments: PayPal buttons shown over Search Panel 

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#17363]
At least in theme Patch, when using the search button in the theme while in a 
page or post where the Simple Pay buttons are located, these buttons are still visible when the search panel covers all the browser screen.

This has been reported by a user and I have been able to reproduce it on a test site

#### Steps to reproduce
1. Create a simple payments button on a Page. Example https://lecturassumergidas.com/donaciones/ or, in my test site:  https://raulanton.wordpress.com/about/
2. Activate Patch theme
3. Open that page on a browser, then Click on the Search ICON
![about raulanton 2017-08-19 13-16-03](https://user-images.githubusercontent.com/6404071/29486204-c7fc42fa-84e0-11e7-98e1-e37371c37e40.png)
4. You will see the PayPall button over the search area
![about raulanton 2017-08-19 13-17-09](https://user-images.githubusercontent.com/6404071/29486209-da7b1820-84e0-11e7-8fef-06f9471e4613.png)
![donaciones - lecturas sumergidas 2017-08-19 13-18-41](https://user-images.githubusercontent.com/6404071/29486216-f8a8f77c-84e0-11e7-858c-b456a3b6a835.png)

#### What I expected
You expect the button to be invisible when using the search tool

#### What happened instead
You have the button there.

#### Context / Source
#user-report 641392-zen

**Comment by iamtakashi** [comment]
The theme needs to bump up the z-index value for the search panel. The button's z-index value is 200 and it's from PayPal so it's outside of Simple Payments' control.
