### ISSUE TITLE
Add via URL - gets stuck when unsupported URLs/videos entered

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#17368]
When trying to insert unsupported video formats/media OR URLs, the modal gets stuck. You can't remove the URL you entered, and  can't click "x".

This happens if you enter a URL that's ending in .mkv, .mpeg (tries these two) - but .mp4 works fine.

Same behavior if you insert a **YouTube or Vimeo** URL, it gets stuck in the same same fashion. 

Nothing is inserted, no error/information is shown to the user whether what they're doing is supported or not.

Console shows `uncaught TypeError`.

#### Steps to reproduce
1. Head over to Media > Add > Add via URL
2. Paste in a YouTube/Vimeo URL or a remote video in .mpeg, .mkv formats
3. Click "Upload"

#### What I expected

To either upload/embed the media, OR, give a warning/message that the media type or remote service is not supported. Plus, be able to remove the entered URL.

For comparison, wp-admin editor wraps the inserted YouTube URL in an embed code inserted into the post/page content.

#### What happened instead

Cannot remove the entered URL, nothing is added or embedded either.

#### Browser / OS version
Chrome latest

#### Screenshot / Video

![add-url](https://user-images.githubusercontent.com/6505293/29490966-1f093456-8566-11e7-9043-e5407d9334de.gif)

#user-report #manual-testing

**Comment by iamgabrielma** [comment]
I have been unable to reproduce this issue with Firefox or Chrome latest versions:

- Firefox: 55.0.3 (64-bit)
- Chrome: Version 60.0.3112.113 (Official Build) (64-bit)

Trying to upload via URL either a Youtube video or a .mkv file prompts me with this:
<img width="1032" alt="screen shot 2017-08-29 at 17 40 28" src="https://user-images.githubusercontent.com/3812076/29830166-cb9acc20-8ce1-11e7-98e5-900e6098f150.png">

Are you still experiencing this @ehti ?

**Comment by ehti** [comment]
@iamgabrielma hmm, not being able to reproduce it anymore - working fine!

Will close it for now.
