### ISSUE TITLE
Domains: hard to read domain management data

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#1737]
The gap between the key and the value makes it a bit hard to read:

![image](https://cloud.githubusercontent.com/assets/548849/11873144/5f703586-a4d9-11e5-8aab-6c487dc2f9e8.png)

cc @breezyskies

**Comment by klimeryk** [comment]
Pinging @breezyskies again (sorry for the noise lately, triaging domains-related bugs) - do you think this is something we can improve? I've looked at other part of Calypso and the only thing similar that comes up is putting the value just below the label, line after line, not on the same line like here. But that works for input fields, not constant values like here.
Or maybe something like alternating colours for rows (just a shade different)?

**Comment by breezyskies** [comment]
This is on our radar and we've done some [early concepts](https://cloudup.com/i5TNOlM7Os5), but it's lower priority that a few other things we're working on at the moment. Planning to loop back to this in the next couple weeks.

**Comment by klimeryk** [comment]
Roger that - great to hear it :+1:

**Comment by breezyskies** [comment]
Proposed iteration on this layout:

Primary Domain + No Privacy:
<img width="741" alt="registered_primary_noprivacy" src="https://cloud.githubusercontent.com/assets/3011211/12680596/a087a23c-c65f-11e5-8ac2-7b370836d8a6.png">

Non-Primary Domain + Privacy:
<img width="744" alt="registered_privacy_notprimary" src="https://cloud.githubusercontent.com/assets/3011211/12680601/a08b422a-c65f-11e5-9347-bf08bec21d4d.png">

Primary Domain + Privacy:
<img width="743" alt="registered_privacyandprimary" src="https://cloud.githubusercontent.com/assets/3011211/12680602/a09b06c4-c65f-11e5-89e1-4739eb9315a4.png">

Privacy Disabled for Transfer (see https://github.com/Automattic/wp-calypso/pull/2899):
<img width="742" alt="registered_midtransfer" src="https://cloud.githubusercontent.com/assets/3011211/12680599/a089aa0a-c65f-11e5-9a12-e073bfda8058.png">

Mobile:
<img width="321" alt="registerd_mobile" src="https://cloud.githubusercontent.com/assets/3011211/12680600/a08ab760-c65f-11e5-9212-2ea490d8677a.png">

Mapped Domain:
<img width="740" alt="mapped" src="https://cloud.githubusercontent.com/assets/3011211/12680597/a0879fda-c65f-11e5-85b0-578ec0ebc9fd.png">

Site Redirect:
<img width="737" alt="siteredirect" src="https://cloud.githubusercontent.com/assets/3011211/12680603/a09bcd2a-c65f-11e5-93b8-3ec8f2a641de.png">

Default *.wordpress.com Address:
<img width="740" alt="defaultaddress" src="https://cloud.githubusercontent.com/assets/3011211/12680598/a0894434-c65f-11e5-921e-2617eacce8c1.png">

**Comment by klimeryk** [comment]
@breezyskies - it's me, your favourite ping-pong player 😉 Just wanted to ping you on the status of this - are the designs above ready to implement or is something else on the horizon?
I noticed a distinctive lack of renew/expires, etc. dates on those designs - is that intentional? (I _think_ the payments page has all the necessary dates, so just wanted to confirm your intention here)

**Comment by breezyskies** [comment]
@klimeryk We don't have anything else on the horizon for domain management at the moment (although noting that these are now several months old). 

> I noticed a distinctive lack of renew/expires, etc. dates on those designs - is that intentional? (I think the payments page has all the necessary dates, so just wanted to confirm your intention here)

The date removal was intentional, since this section is focused on domain setup (and we have notices during periods when the expiration dates are relevant to the user).

**Comment by klimeryk** [comment]
Roger that - thanks for clarifying! :bow:

**Comment by klimeryk** [comment]
cc @mikeshelton1503, in case you feel like revisiting this now :) (maybe along with some other work you'll be doing for domains)

**Comment by kriskarkoski** [comment]
I don't believe this is an issue any longer with the iterations on domain management as well as changes to domain privacy
