### ISSUE TITLE
Editor: post always "dirty" in IE11

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1741]
Raised by @aduth 

This appears to affect only Internet Explorer. The steps below do not reproduce in latest versions of Chrome, Firefox, and Safari in OSX 10.11.

**Steps to reproduce:**
1. Navigate to https://wordpress.com/post
2. Select a site, if prompted
3. Click Reader in the master bar

**Expected result:**

User navigates immediately to Reader without any prompt.

**Actual result:**

User is prompted that there are unsaved changes on the page.

![screen shot 2015-12-17 at thu dec 17 12 26 05 pm](https://cloud.githubusercontent.com/assets/1119271/11876818/8716cb4c-a4b9-11e5-8fec-e140a68fc412.png)

Notes from @jkudish  

> I did some debugging on this. I think I identified the cause (or one of them at least?). It seems that the excerpt is firing an `onChange` event when it gets initially set (even if there is no excerpt in which case it's set to `''` (empty string)). This causes [`actions.edit` to fire](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/editor-drawer/index.jsx#L50) and makes the post `dirty`. 
> 
> Remove the excerpt from the editor drawer fixed the issue for me. I tried to implement a few workarounds in the `FormTextarea` component but unfortunately was unsuccessful at a full working solution for now.

**Comment by rachelmcr** [comment]
This looks like a specific case of https://github.com/Automattic/wp-calypso/issues/9833. Closing this issue as that one is being used to track various AYS alerts and has been prioritized.

#bug-scrub #pre-gutenburg-bug-purge
