### ISSUE TITLE
Editor: long page template titles are cut off unexpectedly

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1742]
/hat tip @aheckler for the original report and @lancewillett for the testing steps

Ellipsis overlaps the rest of the page title rather than a fade or whiteout as expected.

![screen shot 2015-12-17 at 12 46 29](https://cloud.githubusercontent.com/assets/1119271/11877335/a6119bd2-a4bc-11e5-8e5f-a09e319ee715.png)

Tested with Mac-n-Chrome

Steps to repeat:
1. Log into https://wordpress.com/ pick a site, and go to Pages
2. Change themes to Twenty Twelve
3. Create a new page via "Add" link
4. Look in the editor sidebar for "Page Options" section, and open it
5. In the page template dropdown menu, you'll see an option for "Full-width Page Template, No Sidebar" — which has the visual bug with the overlapping ellipsis

**Comment by lancewillett** [comment]
This is still a visual bug — testing with same steps as above in latest Chrome on OS X.

<img width="1284" alt="screen shot 2016-04-26 at 1 47 37 pm" src="https://cloud.githubusercontent.com/assets/66797/14833727/7daa2654-0bb5-11e6-86eb-fddf4457c870.png">

**Comment by joelwills** [comment]
Perhaps related to this, with a Portfolio Page Template theme (e.g Orvis on WordPress.com) in Chrome (does not occur in Firefox), it seems ... appear when the page template title is long:

<img width="242" alt="screen shot 2016-05-02 at 10 50 34 am" src="https://cloud.githubusercontent.com/assets/3228004/14962610/900d88b0-1054-11e6-902c-f81be8bc3753.png">

It's appearing over the a, t and e when it shouldn't appear at all.

Chrome 50.0.2661.86 (64-bit) OSX El Capitan 10.11.4. Does not occur in Firefox.

**Comment by lancewillett** [comment]
Yes, thanks @joelwills — I think it's the same issue.

**Comment by jeremeylduvall** [comment]
Fixed via #10456.
