### ISSUE TITLE
Editor: Sticky toolbar jumps when 'Help translate WordPress.com' notice is shown.

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#17428]
Related to #17426.

When scrolling up or down in the editor, with the 'Help translate the WordPress.com dashboard' notice present, the sticky toolbar jumps drastically.
I assume that there is a listener looking for a certain scroll position which then sticks or un-sticks the toolbar either side of that position.
This check likely doesn't account for extra content above the editor and so continues to listen for the same position as without, causing the visual jump.

![editor-translate](https://user-images.githubusercontent.com/4335450/29563764-e8270db4-8736-11e7-9e99-76a37fc784bb.gif)

**Comment by rachelmcr** [comment]
Closing as the TinyMCE toolbar will be replaced with Gutenberg, which has different behavior.

#bug-scrub #pre-gutenburg-bug-purge
