### ISSUE TITLE
Editor: more compact Share design

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1743]
Raised by @folletto 

Given yesterday's discussion, here's a more compact "Share" panel design concept:

Short:
![iconized-alt-2](https://cloud.githubusercontent.com/assets/4389/10759383/e0815ee6-7cae-11e5-920c-1ac71ac6c36f.png)

Even shorter:
![iconized-alt-short](https://cloud.githubusercontent.com/assets/4389/10759390/ea7d8ef6-7cae-11e5-9361-9181de2877b7.png)

Two considerations:
1. In the future we might show the avatar used on the service (ht @mtias)
2. The more compact version lacks an indication if "Facebook User" vs "Facebook Page". Not sure if it's super important tho, and we can compensate with a tooltip.

Note from @designsimply 

> Current:
> ![screen shot 2015-12-17 at 13 07 22](https://cloud.githubusercontent.com/assets/1119271/11877786/5f1882ba-a4bf-11e5-908f-e6ac3562798b.png)

Notes from @jkudish 

> A few notes/questions:
> - Why move the message to the top?
> - The message box lost some of it's extra UX, e.g. this:
> 
> ![screenshot from 2015-10-27 08-21-43](https://cloud.githubusercontent.com/assets/260253/10762562/cfed17b2-7c83-11e5-88ac-3f1f5c9426da.png)
> - I think "Add new connection" should remain
> - I think the colors of the official icons stand out too much in an otherwise pretty uniform Editor, I'd prefer if we used `social-logos` as originally suggested by @kellychoffman
> - I like the FB page vs FB profile indicator :+1:  -- it would require a small REST API change to accommodate as we don't currently return that info (though we have it)

Notes from @folletto 

> > Why move the message to the top?
> 
> Because it's an existing pattern (open the box, get to write), and should be aligned with user intent. My hypothesis here is that users keep the checkbox most of the time in the same configuration (so they are changed once), and they instead edit the message. Just an hypothesis tho, can be swapped if it's falsified.
> 
> _Also to note that with the exception of scheduled posts, I would find "Share" more useful post-post._
> 
> > The message box lost some of it's extra UX, e.g. this:
> 
> It's a screenshot of what I was seeing this morning. We can reintroduce the counter without problem. Also would be great if the box would auto-expand vertically, making it even better in terms of vertical space. :)
> 
> > I think "Add new connection" should remain
> 
> Whops. Sorry. That's right. It should, I removed it by error. The only suggestion of this mock is on how to handle the list, no other change.
> 
> > I think the colors of the official icons stand out too much in an otherwise pretty uniform Editor
> 
> The icons should definitely be these. On the color, I think it makes the feature inherently clearer and glance-able, which is a **huge** plus. Since it's inside an accordion, I feel color is worth there. That said, I'd be ok also without color.
> 
> > I like the FB page vs FB profile indicator
> 
> Cool! I wasn't sure about that. Thanks. :)

**Comment by rachelmcr** [comment]
The labels for each social media service are less prominent now (not bold) but otherwise the design hasn't much changed since this issue was raised. Current design:

<img width="272" alt="screenshot 2017-12-22 14 58 55" src="https://user-images.githubusercontent.com/8658164/34312300-aaa903b4-e728-11e7-89e4-efbb3abada1e.png">


#bug-scrub #pre-gutenburg-bug-purge

**Comment by worldomonation** [comment]
Hi! I'm triaging some older bugs on file as part of Quality Squad's efforts to cut down on issues.

Is this issue still applicable to `wp-calypso` as of 2021/01/29? From my brief testing I was unable to locate where this interface may be.

Would it be acceptable to close this issue with the status `[Closed] - Won't Fix`?

**Comment by folletto** [comment]
This is still an interesting enhancement that surprisingly could still work... but given the time and the fact that at this point whoever wanted to improve it would have to work reviewing all the flows before getting here, it's ok to close it.
