### ISSUE TITLE
JPO: add animation to site type tiles

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17430]
The first tiles in the step to choose the site type don't have the exit animation:

![animation](https://user-images.githubusercontent.com/1041600/29566386-15f62dc2-8720-11e7-85c9-1be1c3f86856.gif)

Other tiles, even in the same step, do have it.

**Comment by tyxla** [comment]
Noted in https://github.com/Automattic/wp-calypso/projects/55#card-6102609, closing this one.
