### ISSUE TITLE
Editor: Revisions: Visually separate paragraphs for improved readability

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#17447]
1. Go to `/post/:postId`.
2. Go to Status → Revisions from the Editor sidebar.

Assuming the following revision, made of three paragraphs:

<img width="737" alt="screen shot 2017-08-23 at 00 55 26" src="https://user-images.githubusercontent.com/150562/29592741-ecab5284-879d-11e7-864b-5fca8ddd4a71.png">

This is the rendered diff:

<img width="721" alt="screen shot 2017-08-23 at 00 56 03" src="https://user-images.githubusercontent.com/150562/29592767-14f79874-879e-11e7-9da7-da91e159e558.png">

Respecting paragraphs in the diff would bring a significant improvement in diff readability.

**Comment by jblz** [comment]
This should be fixed in #18786.  Please reopen if not!
