### ISSUE TITLE
Editor: Revisions: Remember last revision when switching from editor to revisions

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#17446]
#### Steps to reproduce
1. Starting at URL: `/post/:postId`
2. Open Revisions from Editor sidebar
3. Pick and load a revision into editor using _Load revision_ button
4. Return to Revisions

#### What I expected
To have the revision currently loaded into the editor highlighted in the list, so that I can be sure of which one I had picked last.

#### What happened instead
The latest revision is automatically highlighted.

#### Caveat
The trivial fix would be to have Revisions remember which item was last picked from the list and highlight it. However, if the user loads a revision, then changes its content, and returns to Revisions, what should they see? The Revisions feature would have to be aware of changes made in the editor and present its list accordingly.

Maybe there is a more elegant way to address this without causing confusion for the user. Or maybe this is simply a `wontfix`.

**Comment by jblz** [comment]
I agree, this is a bit unintuitive, but I think this is `wontfix` with the current behavior. We "preview" the un-rendered diff between the current & past versions of `post_content` & then "load" some old version in the editor. Once autosave kicks in (this happens relatively quickly), you're now "based" against the most recent revision.

Perhaps if / when we ever support comparing two arbitrary revisions we can have a concept of pinning the base for comparison.

What do you think, @lsinger, @lancewillett, @marekhrabe, @shaunandrews?

**Comment by lsinger** [comment]
> Once autosave kicks in (this happens relatively quickly), you're now "based" against the most recent revision.

I don't think I fully understand what is happening here — are you saying that once you load a revision to look at it autosave makes it become the latest revision? 

I do agree with the sentiment of this ticket that it would be immensely helpful to have some sort of visual indication of what revision I'm currently looking at.

**Comment by marekhrabe** [comment]
> I don't think I fully understand what is happening here — are you saying that once you load a revision to look at it autosave makes it become the latest revision?

Once you load it in the editor, yes. The editor takes any unsaved content from TinyMCE and saves it as the latest revision every few seconds. That's how the editor works and I don't see any easy way to prevent this from happening. The editor is just not meant for previewing things.

However, if you are just previewing a revision in the revisions view, nothing will, of course, get saved.

**Comment by jblz** [comment]
@mcsf @lsinger we actually ended up implementing this just as a function of the selected revision Id  being in redux. If anything, there are probably some cases where we need to forget the selected revision.

I'm going to go ahead and close this -- please feel free to reopen if need be.
