### ISSUE TITLE
Login page not redirecting to past page after successful login

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#17444]
#### Steps to reproduce
1. Navigate to [wordpress.com/me](https://wordpress.com/me) while logged out.
2. Confirm that you've been redirected to the [login](https://wordpress.com/log-in) page.
3. Enter your credentials / etc. for a successful login.
4. Confirm that you've been redirected to [wordpress.com](https://wordpress.com/)

#### What I expected

In step 4, the user would expect to be redirected to [wordpress.com/me](https://wordpress.com/me) instead of [wordpress.com](https://wordpress.com/).

#### Browser / OS version

Chrome 60 and Firefox 56 on macOS 10.12.5. 

#### Context / Source
Originally reported by @bubel on a P2 comment.

**Comment by scruffian** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/17451
