### ISSUE TITLE
Editor: add an error-input message to the natural language text input in the scheduler

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1744]
When random text is input into the natural language text field in the scheduler, use an error-input pattern:

![image](https://cloud.githubusercontent.com/assets/548849/10765581/bfeedd0a-7cd3-11e5-8454-820d9b921c83.png)

/hat tip @mtias for the suggestion

**Comment by rachelmcr** [comment]
The editor's date picker no longer has a natural language text field, so this issue is no longer valid.
