### ISSUE TITLE
Editor: add upgrade prompt when out of storage space

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1745]
Raised by @kriskarkoski 

In WP Admin, this error is displayed when you try to upload an image when you are out of space:

> Howdy!
> 
> Looks like you have used 7.7MB of your 8.0 MB upload limit (96%). Since you are close to your limit, you might want to consider purchasing a WordPress.com Premium plan.
> 
> With the upgrade, you'll also be able to upload mp3, m4a, wav, and ogg audio files (great for podcasting).

![screen shot 2015-04-08 at 11 54 18 pm](https://cloud.githubusercontent.com/assets/581008/7052220/d3fc2c76-de4a-11e4-9b6a-3821bee2ad26.png)

In the new WordPress.com, this message is displayed instead:

> The file could not be uploaded because an error occurred while uploading.

![screen shot 2015-10-23 at 2 02 06 pm](https://cloud.githubusercontent.com/assets/1900444/10701040/a0fa0aec-798f-11e5-808f-b86a5e2343a1.png)

We should update this to explain that they're out of space and link the user to upgrade to a Premium plan or Business plan depending on what they currently have.

**Comment by rachelmcr** [comment]
Closing as the media dialog now includes details about the space you have used and an upgrade nudge in the top right corner:

<img width="1086" alt="screenshot 2017-12-22 16 01 32" src="https://user-images.githubusercontent.com/8658164/34313539-75704b5e-e731-11e7-9702-f11a218f1221.png">

#bug-scrub #pre-gutenburg-bug-purge
