### ISSUE TITLE
Editor: Avoid screen jump when undo action (cmd+Z)

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#17461]
When adding a list into a long post, so scroll down is necessary to check it, using cmd+z to undo the action makes the page jump to the top.

#### Steps to reproduce

1. Starting at URL: http://wordpress.com/posts
2. Create a long post, you will need to scroll down to check the whole text
3. Add a list
4. cmd+z

#### What I expected

The screen/view to stay still

#### What happened instead

The screen/view jumped to the top, where the title is.

#### Screenshot / Video

25mb too big for GH but uploaded here: https://quiverquotes.files.wordpress.com/2017/08/cmdz-issue-quiver-quotes2.gif

#### Context / Source

I was unable to reproduce the issue, as well as @liviopv and @carinapilar 

Reported at 630628-zd

**Comment by lancewillett** [comment]
Closing as not easy to reproduce — if we receive more reports, let's try to reproduce it easily with consistent steps, and re-open this one.
