### ISSUE TITLE
Plugins: Show the sites plugin version when viewing the single site view

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#17480]
#### Steps to reproduce
Run the bleeding edge version of Jetpack. Notice that you see the version available on .org on the single site single plugin view.

#### What I expected
To see the sites current plugin version.

#### What happened instead
The version numbers don't match.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/115071/29651101-b6a4b368-8853-11e7-8050-1148193ea578.png)

#### Context / Source
#dogfooding

**Comment by beaulebens** [comment]
Just to add some further detail to this one; I have the Jetpack Beta plugin running on my site, and am running the Bleeding Edge version of Jetpack. wp-admin reports:

![screen shot 2018-02-06 at 1 30 42 pm](https://user-images.githubusercontent.com/108942/35882602-f338ae8a-0b41-11e8-910f-90e2d7ced77a.png)

while the respective view in Calypso, for the same site/plugin, shows:

![screen shot 2018-02-06 at 1 31 18 pm](https://user-images.githubusercontent.com/108942/35882622-0a47c138-0b42-11e8-8efc-2015760f972b.png)

**Comment by beaulebens** [comment]
Possibly related to how the beta plugin itself juggles versions, so might be a pretty corner case to fix for.

**Comment by gititon** [comment]
I tested this extensively and found that Calypso reported the correct plugin versions, even after modifying plugin versions on the Jetpack site via the Plugin Editor. @enejb confirmed my findings. We will address the Jetpack Beta specific inconsistencies separately. Please feel free to reopen if you find there is still an issue unrelated to Jetpack Beta.

**Comment by gititon** [comment]
@beaulebens I submitted and merged a PR for the Jetpack Beta plugin that should ensure Calypso properly reports whatever Jetpack version you're using on account of the Jetpack Beta plugin, https://github.com/Automattic/jetpack-beta/pull/56.
