### ISSUE TITLE
Store: Add a link back to the order list in the "Order updated" success notice

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17489]
When you have multiple orders to fulfil, the first thing you will want to do after fulfilling one is to move on to the next. Adding a link back to the orders list in the success notice creates a clear path back to orders that require action.

**Comment by justinshreve** [comment]
I'm reviewing our Q4 post and noticed we still need a design for this ("an improved order fulfillment flow for fulfilling multiple orders in one sitting") @jameskoster @kellychoffman. I think we have a little time here since I'll have @ryelle work on this and we still need to get edit and create an order out there, but I wanted to make sure it was on your radar.

**Comment by jameskoster** [comment]
Current info; 

We have a rough prototype [here](https://href.li/?https://automattic.invisionapp.com/share/Q3DBO9VTN#/251681334_1)

Discussion at p6riRB-2jG

There's a [PR open for core](https://github.com/woocommerce/woocommerce/pull/16700) which does something similar to Kelly's suggestions.

I'll work on the designs asap.

**Comment by jameskoster** [comment]
Updated design at p90Yrv-mX-p2

**Comment by ryelle** [comment]
Do we need this link in the success notice? The "Orders" link in the breadcrumbs are basically right there:

![screen shot 2017-12-15 at 2 27 27 pm](https://user-images.githubusercontent.com/541093/34057300-642da86a-e1a4-11e7-813b-1f7f5a8f1e03.png)

And should we create a new issue for "quick fulfillment" using the design at p90Yrv-mX-p2?

**Comment by kellychoffman** [comment]
> Do we need this link in the success notice? The "Orders" link in the breadcrumbs are basically right there:

Right. We added a link in the notice, because during testing we noticed that people weren't immediately releasing they could click on the Orders in the breadcrumbs or the sidebar to go back.

> And should we create a new issue for "quick fulfillment" using the design at p90Yrv-mX-p2?

We still have to test this to see if its the right way to go so let's hold off on it for now.
