### ISSUE TITLE
Unable to edit images in Media (private sites)

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#17493]
#### Steps to reproduce
1. Starting at URL: wordpress.com/media/{site}
2. Click an image - then the blue "edit" button
3. Once the image opens, click "Edit image"

*site should be private

#### What I expected

Image should load, allowing you to crop, rotate etc.

#### What happened instead

Image doesn't load, and this error is returned:

>Sorry, there was a problem loading the image. Please close this editor and try selecting the image again.

JavaScript console output:

> XMLHttpRequest cannot load https://merilab.files.wordpress.com/2017/04/domains-coming-soon3.jpg?. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://wordpress.com' is therefore not allowed access. The response had HTTP status code 403.

The URL will be the one for your image, in the above output.

#### Browser / OS version

Chrome latest

#### Screenshot / Video

![image-edit](https://user-images.githubusercontent.com/6505293/29667188-e646ebee-88f4-11e7-8e2c-c301be4b1356.jpg)

#### Context / Source
#manual-testing #user-report

**Comment by bperson** [comment]
Confirmed on a private site ( getting a 403 on the file even though I own the site ), working fine on public sites.

**Comment by ehti** [comment]
Thanks @bperson  - private site was the missing puzzle. Edited the description.

**Comment by ehti** [comment]
dupe - https://github.com/Automattic/wp-calypso/pull/17347
