### ISSUE TITLE
Store: Order fulfillment modal

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17496]
![fulfil](https://cldup.com/oVLC8VBvym.png)

The language in this modal leaves it open to interpretation. It's not clear that customers are emailed regardless of whether a tracking number is supplied or not. I think we should add a notice to explain that.

Suggested revision:

![suggestion](https://cldup.com/ZnoDDTFk2a.png)

The "Send tracking number to customer" checkbox is only revealed is a tracking number is inserted:

![tracking-number-entered](https://cldup.com/B619Y_8NEZ.png)

But I'm now wondering do we really need that checkbox? In what situation would you _not_ want to send the tracking number to the customer?

**Comment by kellychoffman** [comment]
Why do we send it in two different emails? Seems overkill. cc @mikejolley

**Comment by jameskoster** [comment]
I guess it's because the tracking number is an order note that can be sent at a later date. This just bundles that with the order completed mail. 

I agree it'd be nice if they could be combined though, when sent simultaneously.

**Comment by kellychoffman** [comment]
Yeah, that would be ideal. Then we could get rid of the checkbox and the second paragraph you added. Nice and smoooooth.
