### ISSUE TITLE
Conversations: Move Reply and Like up 6px

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17506]
This is to make the spacing more consistent in Conversations.

Currently there's a line-height of 25px for the comments, but the Reply and Like line gets an additional 6px of space, so they hang low. This made sense when we were displaying the whole comment. But now that we're switching to 3-line excerpts (#17449), they're adding too much space. So let's keep the line-height consistent with the comment and remove 6px of vertical space.

So this (current):

<img width="621" alt="screen shot 2017-08-24 at 11 34 56 am" src="https://user-images.githubusercontent.com/24388/29682686-ce2cd3c2-88c0-11e7-90ed-d14d95cf3af5.png">

Should be this:
<img width="445" alt="screen shot 2017-08-24 at 11 35 12 am" src="https://user-images.githubusercontent.com/24388/29682689-d1d2a9ac-88c0-11e7-80c2-406966cfe63b.png">

Make sense?

cc @jancavan

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/17540
