### ISSUE TITLE
Conversations: "Read More" links

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17508]
If it gets too tricky/messy/time consuming to position "Read More" links at the ends of comment excerpts, here's an alternate design idea.

<img width="759" alt="screen shot 2017-08-24 at 12 19 19 pm" src="https://user-images.githubusercontent.com/24388/29684343-7b3134f0-88c6-11e7-87ec-9730a2094a88.png">

Instead of trying to position the "Read More" link over the comment text (and worrying about matching line-height and long non-En languages and other loose ends), put the Read More link as the first item in the comment footer links.

Clicking it would expand the comment, as now. (Side idea: using this format, we could change it to "^ Show Less" after expanding, which would allow users to "undo" comment expansions.)

If the comment fits entirely in 3 lines, don't show the link.

It saves us from having to position it in CSS, avoids the longer text issue with non-En lauguages, and it’s in a consistent place for the user.

I left it bright blue so that it stands out from the other links, but I could see an argument for making it the same color as Reply and Like.

Just posting this idea so we don't lose track of it. I think we should try it.

cc @samouri and @jancavan

**Comment by samouri** [comment]
@fraying: what should happen when one click "Show Less"? 

Should we chase that concept in a separate issue or do you want to handle that here?

**Comment by fraying** [comment]
@samouri Let's tackle that later.

**Comment by samouri** [comment]
Ok so for now lets stick with it disappearing

**Comment by jancavan** [comment]
> Ok so for now we can stick with it disappearing

It'll probably make it jumpy since the remaining buttons will be moved to the left after "Read more" disappears. Will probably only be obvious though if there are only 1-2 lines expanded. But let's see how it feels.

**Comment by fraying** [comment]
@jancavan Yeah, since the whole line will be moving anyway (with the comment expanding), I don't think that'll be a problem. Still, as always, let's test it and see how it feels.

**Comment by samouri** [comment]
closing because this has been implemented as of: https://github.com/Automattic/wp-calypso/pull/17677
