### ISSUE TITLE
Stats: Indicate that the Stats system is powered by Jetpack

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#17503]
The entire stats offering delivered within Calypso/WP.com is powered by Jetpack, so let's indicate that in the UI somehow. Since I am not a designer, I've hacked together a few options, but please feel free to explore others.

**Option 1: Loading icon**
I'm not a huge fan of this, since it goes away really quickly, and associates Jetpack with loading/slowness, plus it doesn't actually mention Jetpack, just the logo.

![screen shot 2017-08-24 at 10 53 50 am](https://user-images.githubusercontent.com/108942/29678347-6bc4c9e2-88bb-11e7-9456-02ba02506f90.png)

**Option 2: Use the footer from the login page**
I'm not even going try to make this actually look good, just copy-pasting for visual reference.

![whitescreen shot 2017-08-24 at 11 01 15 am](https://user-images.githubusercontent.com/108942/29679396-ce65fd16-88be-11e7-9e05-fd1600baee49.png)

**Option 3: Watermark style logo**
Hacked from the previous one, might be easier to make something like this work?

![watermarkscreen shot 2017-08-24 at 11 01 15 am](https://user-images.githubusercontent.com/108942/29679841-fab45c86-88bf-11e7-8c2a-7c6c49ff1562.png)

As I said, please feel free to explore some other options as well; we just want to include a nod in here to the fact that Jetpack powers these stats for all WordPress sites.

**Comment by MichaelArestad** [comment]
> Option 1

🙅 

> Option 2

🤔 

> Option 3

💯 🥇

**Comment by MichaelArestad** [comment]
The third option seems like the best bet to me as it feels more native to the interface. It will also be fast to implement so if we need to iterate to another version we can.

**Comment by beaulebens** [comment]
Yeah, that was sort of where I ended up. Think you can get a PR together for it?
