### ISSUE TITLE
Store, Promotions: Product specific discount

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17519]
> I want to set up a $5 discount on my Octopus Tshirt product

Prototype: https://automattic.invisionapp.com/share/G6D5YB3HM#/249991169_Dash

Sketch: https://www.dropbox.com/s/5x647stas46wfqm/promotions.sketch?dl=0

**Comment by kellychoffman** [comment]
cc @coderkevin

**Comment by coderkevin** [comment]
Completed with initial release.
