### ISSUE TITLE
Editor: non-admins get a notice about not being able to manage settings

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-calypso#1751]
![screenshot from 2015-12-16 13-56-17](https://cloud.githubusercontent.com/assets/260253/11855106/0eabf3d8-a3fd-11e5-8057-4a651974148b.png)

Initially reported here: https://github.com/Automattic/wp-calypso/pull/1653#issuecomment-165264777

**Comment by aduth** [comment]
From my testing, this seems to be specific to Jetpack sites.

**Comment by jkudish** [comment]
Yes, I couldn't repro for a WP.com site. Sorry for not specifying originally.
