### ISSUE TITLE
Store, Promotions: Support store-wide promotions

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17518]
> “I want to offer a store-wide, 10% discount across my entire catalog of products.”

Prototype: https://automattic.invisionapp.com/share/HZD2GI8MK#/248965872_Dash

Sketch: https://www.dropbox.com/s/5x647stas46wfqm/promotions.sketch?dl=0

**Comment by kellychoffman** [comment]
cc @coderkevin

**Comment by coderkevin** [comment]
Pushing to v1.2 due to lack of core support for this feature.
