### ISSUE TITLE
Store, Promotions: Free shipping promotion

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17521]
> “I want to create a promotion that offers free shipping on my Octopus Tshirt on July 4th 2018.”

Prototype: https://automattic.invisionapp.com/share/QAD54ZM74#/249597307_Dash

Sketch: https://www.dropbox.com/s/5x647stas46wfqm/promotions.sketch?dl=0

**Comment by kellychoffman** [comment]
cc @coderkevin

**Comment by coderkevin** [comment]
Should we add a coupon code requirement to this feature? Or push it to v1.2 when we hopefully have this ability?

**Comment by kellychoffman** [comment]
> Should we add a coupon code requirement to this feature?

@jameskoster - what do you think? I think it could be a good interim step.

**Comment by jameskoster** [comment]
Sound good in principle, it means we'd need to tweak the design a bit though which feels a little funky. 

Essentially, if they select "Free Shipping" as the discount type we'll need to remove the coupon option in the "Conditions" card and add it to the main "Promotion" card as it is now mandatory. Something like:

![coupon](https://cldup.com/Yf6Ew8Jau0.png)

What do you think?

**Comment by kellychoffman** [comment]
Closing since we have a free shipping promo.
