### ISSUE TITLE
Store, Promotions: Sharing promotions

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17522]
> “I want to share my ‘10% off all products’ promotion with my followers on Twitter.”

Prototype: https://automattic.invisionapp.com/share/BTD553XC7#/249759967_Dash

Sketch: https://www.dropbox.com/s/5x647stas46wfqm/promotions.sketch?dl=0

We've decided that the connection is not immediately required for sharing. We could just compose a new tweet via URL.

**Comment by kellychoffman** [comment]
cc @coderkevin
