### ISSUE TITLE
Store, Promotions: Category-specific promotion

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17520]
> “I want to offer a 10% discount on all products in my ‘Apparel’ category when customers check out with the coupon ‘APPAREL’.”

Prototype: https://automattic.invisionapp.com/share/PGD32Q2TR#/249142455_Dash

Sketch: https://www.dropbox.com/s/5x647stas46wfqm/promotions.sketch?dl=0

**Comment by kellychoffman** [comment]
cc @coderkevin

**Comment by coderkevin** [comment]
Completed with initial release.
