### ISSUE TITLE
Reader Conversations: Emojis cropped and look inconsistent

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#17541]
Sometimes emojis are cropped:
![screenshot 2017-08-25 10 59 40](https://user-images.githubusercontent.com/4924246/29726551-03bbd7a8-8985-11e7-8613-3ad25bda8acf.png)

![screenshot 2017-08-25 10 59 34](https://user-images.githubusercontent.com/4924246/29726557-0c4ebd4a-8985-11e7-914f-54afca91662e.png)

But sometimes they look ok:
![screenshot 2017-08-25 11 00 38](https://user-images.githubusercontent.com/4924246/29726568-166dbc68-8985-11e7-8ca0-35462270986c.png)

In fullpost, they also sometimes look flat:
![screenshot 2017-08-25 11 05 14](https://user-images.githubusercontent.com/4924246/29726630-5434b7d6-8985-11e7-9d98-661389f18971.png)

Is there any way to make them uniform?

**Comment by fraying** [comment]
I believe the flat ones are the ones we're supposed to be using everywhere. Maybe that's why the others are cropped? 

ccing @blowery and @bluefuton even though they're AFK right now....

**Comment by fraying** [comment]
@jancavan Are they only cropped in Conversations? Or have you observed this elsewhere? And in all browsers?

**Comment by jancavan** [comment]
> Are they only cropped in Conversations? Or have you observed this elsewhere? And in all browsers?

@fraying I've only seen the cropping in convos. 

I also noticed that they're always the glossy version in convos:
![screenshot 2017-08-25 11 10 44](https://user-images.githubusercontent.com/4924246/29726826-3206b5be-8986-11e7-82bc-39379b893eb8.png)

While they could sometimes be flat in fullpost:
![screenshot 2017-08-25 11 10 51](https://user-images.githubusercontent.com/4924246/29726827-32078566-8986-11e7-888f-4dbc11b98131.png)

(Ignore the spacing in the second screenshot. Fixing that now.)

But it's also really just the smile icon that's flat. The rest are always glossy it seems like:
![screenshot 2017-08-25 11 15 43](https://user-images.githubusercontent.com/4924246/29726983-dd0663f6-8986-11e7-9416-11292c90f3f4.png)

**Comment by fraying** [comment]
@jancavan Interesting! Thanks. What's the URL of the post in that last screenshot?

**Comment by jancavan** [comment]
> What's the URL of the post in that last screenshot?

@fraying https://wpcalypso.wordpress.com/read/blogs/7554655/posts/6926

Same issue happens in Blog Posts > Comments:
![screenshot 2017-08-25 14 25 54](https://user-images.githubusercontent.com/4924246/29733384-b765b10e-89a1-11e7-92fa-7c1dfeee43f5.png)

**Comment by fraying** [comment]
Weirdly, I see those same emoji as flat (correct).

<img width="770" alt="screen shot 2017-08-25 at 2 53 32 pm" src="https://user-images.githubusercontent.com/24388/29734102-3de83ece-89a5-11e7-8032-28ddae8c8f32.png">

**Comment by jancavan** [comment]
That's weird. I'm not seeing the same thing in Safari. I'm on `10.0`:

![screenshot 2017-08-25 14 55 10](https://user-images.githubusercontent.com/4924246/29734185-a9fc6ebe-89a5-11e7-82f3-6bf8c0f4c06f.png)

**Comment by bluefuton** [comment]
I believe the flat ones are the ones we're supposed to be using everywhere. 

That's right! We aim to convert them all to the flat version across Reader using Twitter's twemoji library. Looks like we're not doing that consistently in Conversations. I'll look into it.

**Comment by fraying** [comment]
Thanks, @bluefuton! :)
