### ISSUE TITLE
Themes: Theme filters don't appear when Search field is focused

### ISSUE THREAD

**Issue by samjhamdy** [Automattic/wp-calypso#17542]
#### Steps to reproduce

1. Start in Themes panel for any site
2. Click in Search field

#### What I expected

Theme filters should appear below Search field.

#### What happened instead

Theme filters don't appear.

#### Browser / OS version

Chrome 60.0.3112.101 / OSX El Capitan 10.11.6

Reproduced by @folletto 

#### Screenshot / Video

<img width="1440" alt="screen shot 2017-08-25 at 2 06 15 pm" src="https://user-images.githubusercontent.com/9888982/29727055-500255fe-89a0-11e7-9ef7-f76d9d3d3c25.png">

#### Context / Source

Discovered during Business 1:1 with user.

**Comment by folletto** [comment]
For reference, this is the UI that isn't showing up:

![screen shot 2017-08-23 at 13 15 01](https://user-images.githubusercontent.com/4389/29727382-8a1472ec-89cb-11e7-867b-a2683c0b0a16.png)

**Comment by folletto** [comment]
PR #17543 fixes this :)

**Comment by folletto** [comment]
The fix is live. Thank you! 💯
