### ISSUE TITLE
Comments: comments-tree v1.1

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17546]
This task is to update the comments-tree endpoint to return the following response shape. This is a more compact format, which should help cut down how much data we're transmitting over the wire. We must take care to also bump version to v1.1 and also prepare a Jetpack PR.
```
{
    comments-count: 1234,
    comments-tree: {
        [ postA ]: {
            replies: [ 12, 15, 38 ],
            commentReplies: [ [ commentId, parentCommentId ], [ 20, 15 ], [ 40, 15 ] ]
        }
    },
    trackbacks_count: 0,
    trackbacks_tree: {},
    pingbacks_count: 0,
    pingbacks_tree: {}
}
```

After this change is made we can also increase query limits. At the moment we cap at 10k, which can result in a subset of comment ids returned from the endpoint.

A good example is en.blog.wordpress.com

<img width="360" alt="screen_shot_2017-08-24_at_12 16 15_pm_720" src="https://user-images.githubusercontent.com/1270189/30178748-edf55e0a-93be-11e7-96f9-ae9b271524be.png">

Here we receive no pings/trackback ids, since we have 10k comments that are newer. (pings/trackbacks were disabled back in 2014 on that site).

**Comment by kwight** [comment]
Noting a question, do pingbacks and trackbacks ever have a parent ID, is that possible? If not, we can cut out more bits by dropping `comment_parent` from those comment types.

**Comment by kwight** [comment]
Work on this in D7470-code. Can anyone see a more elegant way to do this?

**Comment by kwight** [comment]
This approach cuts more than 50% from the response for `en.blog.wordpress.com`: now 418KB down from 878KB.

**Comment by kwight** [comment]
The Jetpack side is being worked on in https://github.com/Automattic/jetpack/pull/7933.

**Comment by kwight** [comment]
I'm also now treating pingbacks and trackbacks the same with post IDs as keys, giving this updated shape:

```
{
    comments_count: 1234,
    comments_tree: {
        [ comment_post_id ]: [
            0: [ comment_id, comment_id, ... ],
            1: [
                [ comment_id, comment_parent_id ],
                [ comment_id, comment_parent_id ],
                ...
            ]
        ]
    },
    trackbacks_count: 0,
    trackbacks_tree: [
        [ comment_post_id ]: [ comment_id, comment_id, ... ],
        ...
    ],
    pingbacks_count: 0,
    pingbacks_tree: [
        [ comment_post_id ]: [ comment_id, comment_id, ... ],
        ...
    ]
}
```

**Comment by kwight** [comment]
Dotcom side was deployed in r163730-wpcom (this doesn't affect anything yet, since we're only calling the v1 endpoint at this time).

**Comment by Copons** [comment]
Jetpack side deployed as well (https://github.com/Automattic/jetpack/pull/7933).

Is Calypso ready for that (like with a JP>5.5 requirement), or can we close this issue?

**Comment by kwight** [comment]
This issue we can close, yes; I've created #19153 to track adding the version check for Jetpack sites.
