### ISSUE TITLE
Media Library: trash icon remains visible when switching tabs

### ISSUE THREAD

**Issue by mzorz** [Automattic/wp-calypso#17551]
Small screen (Chrome, Android, Google Pixel): When on the Images or All tabs in the Media Library, after selecting one image (which makes the trash icon appear) and then switching to a tab that has no items, the screen still shows and allows the trash can to be tapped, triggering the very alarming dialog “Are you sure you want to permanently delete these items?”.

#### Browser / OS version
Chrome browser on Google Pixel 

#### Screenshot / Video
![screenshot_20170815-1239271](https://user-images.githubusercontent.com/6597771/29735259-053c17c0-89ce-11e7-8ae4-7b6dda15cf88.png)

#### Context / Source
#dogfooding, #media, #manual-testing

**Comment by lancewillett** [comment]
Thanks for the report.
