### ISSUE TITLE
Editor: small screens, the formatting toolbar is not floating

### ISSUE THREAD

**Issue by mzorz** [Automattic/wp-calypso#17553]
The formatting toolbar is attached to the upper portion of the screen, so you need to scroll back and forth each time in order to format text that is way below in the post’s body. That was annoying.

#### Steps to reproduce
1. on Chrome on ANdroid, start writing a draft
2. write several paragraphs
3. try to give some of the text some formatting
4. realize you'll have to scroll all the way up to find the formatting toolbar

#### Browser / OS version
Chrome on Android 7.1.2

#### Context / Source
#dogfooding, #editor, #manual-testing

**Comment by rachelmcr** [comment]
Closing as the current TinyMCE toolbar will be replaced with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
