### ISSUE TITLE
Media Library: inserting a new item in Chrome (Android) shows ambiguous source icons

### ISSUE THREAD

**Issue by mzorz** [Automattic/wp-calypso#17552]
Inserting a new item is a bit awkward as it shows 2 possible sources named / iconed the same “Camera”. The one on the left prepares the camera to obtain a picture, while tapping on the one on the right prepares the camera for video. You can only learn by trying here.

#### Steps to reproduce
1. go to the Media Library
2. tap on the insert media icon
3. see the possible sources appear, where there are 2 repeated icons for photos or videos (both being "Camera") 

#### What I expected
A clear identification of the source for pictures or videos

#### What happened instead
2 equal "Camera" icons appear  and you can't tell which one is for pictures or videos, you have to try and fail to learn.

#### Browser / OS version
Chrome, Google Pixel on Android 7.1.2

#### Screenshot / Video
![screenshot_20170815-122329](https://user-images.githubusercontent.com/6597771/29735436-5a6b3b30-89cf-11e7-8b57-c536122c5fae.png)

#### Context / Source
#dogfooding, #media, #manual-testing

**Comment by lancewillett** [comment]
I've noticed this happen with my Nexus 6P — but I'm wondering if it's OS-level and not Calypso related. Worth investigation, either way, so thank you for reporting it.

**Comment by rachelmcr** [comment]
It's at least not Calypso-specific, as I see the same thing when uploading media in WP Admin:

![screenshot_20170828-125426](https://user-images.githubusercontent.com/8658164/29772372-6641d04a-8bf0-11e7-8db1-6c15d78fcbbd.png)

As seen on my Nexus 9, Android 7.1.1, Chrome.

**Comment by lancewillett** [comment]
OK, I think it's safe to close as it's not something we can control from the web interface.

**Comment by mzorz** [comment]
Just wanted to comment here, while this seems to be the case (i.e. a problem in the platform itself) there's still a way we could try to make a better UX; I took some screenshots from the FB mobile site as an example of it, where they offer a differentiated screen for photos or videos:

First you're presented with the option to upload photos or videos:
![screenshot_20170828-130406](https://user-images.githubusercontent.com/6597771/29787254-a98226c0-8c04-11e7-9a39-c5054d05dded.png)

Then once you choose i.e. videos, you're taken to this other screen:
![screenshot_20170828-130418](https://user-images.githubusercontent.com/6597771/29787283-c1ddd3c2-8c04-11e7-96ab-1d62995abef1.png)

And the source is not ambiguous anymore
![screenshot_20170828-130412](https://user-images.githubusercontent.com/6597771/29787288-c6f1bbda-8c04-11e7-9fda-bc557226b7e9.png)

Please feel free to re-close if you think this belongs to a different issue than the case described in this one.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
