### ISSUE TITLE
Editor: HTML editor's "Code" button generates wrong syntax

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#17564]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Note there isn't an code button in Visual. Switch to HTML.
3. Press "Code" -- it starts a code tag with non-square brackets. Add some code. Press the code button again to close.
4. Publish the post and note the code does not display properly.

#### What I expected
To be able to post source code. To do that I really ought be using square brackets.

#### What happened instead
Our editor puts in chevrons instead. If I publish the post, the code is rendered. If I click visual I run into some other odd bugs.

#### Browser / OS version
Chrome / mac in this case though I'd imagine it's not browser specific.

#### Screenshot / Video
https://cloudup.com/c7gQlvp3CH4  (The video shows some other bugs around posting source code, too)

#### Context / Source
Support request: #635590

**Comment by lancewillett** [comment]
Thanks for this report. I'm going to close as "worksforme" since we don't have plans to change the way we add code to the Visual editor right now. Gutenberg will be a big improvement!
