### ISSUE TITLE
Jetpack Plans: Take me back to Wp-admin is broken

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#17569]
#### Steps to reproduce
1. Starting at URL:
2. Disconnect Jetpack and reconnect it again

#### What I expected
I ended up on the plans page after connection on my site.
I expected to be able to click on the link 
![screen shot 2017-08-28 at 12 59 44 pm](https://user-images.githubusercontent.com/115071/29791315-53999ce2-8bf1-11e7-817a-c5caa3b0c57f.png)
To take me back to wp-admin. This is currenly not the case.

#### What happened instead
The link is broken and it doesn't go anywhere.

#### Browser / OS version
latest Chrome and on MacOS

#### Screenshot / Video
See 
![screen shot 2017-08-28 at 1 04 49 pm](https://user-images.githubusercontent.com/115071/29791381-8c99ca1c-8bf1-11e7-986b-9a637d3b4dfb.png)

#### Context / Source
#dogfooding

**Comment by tyxla** [comment]
@enejb I'm having trouble reproducing that one, could you please expand the steps to reproduce?

**Comment by jeherve** [comment]
It seems to work on my end as well. Closing. Feel free to reopen if the issue reappears.
