### ISSUE TITLE
JPO: clipped text in buttons in mobile size

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17575]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start/jetpack-onboarding/jpo-site-type
2. reduce it until mobile size

#### What I expected
No clipped characters

#### What happened instead
<img width="451" alt="captura de pantalla 2017-08-28 a la s 19 57 47" src="https://user-images.githubusercontent.com/1041600/29797100-a4993622-8c2b-11e7-960c-3faf91a185d5.png">

**Comment by tyxla** [comment]
This seems to be happening in the new implementation as well (notice the bottom of the `g`):

![](https://cldup.com/GHn8SvYQ5l.png)

Could be fixed by slightly increasing the line height of the CTA.
