### ISSUE TITLE
Jetpack: Indicate account creation is powered by Jetpack

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#17571]
When connecting a Jetpack site, you potentially need to create a WordPress.com account. Everywhere else that you log into a WP.com account, we've included a new footer on the page to indicate that it's "powered by WordPress.com":

<img width="785" alt="screen shot 2017-08-28 at 2 21 07 pm" src="https://user-images.githubusercontent.com/108942/29791969-2887f386-8bfc-11e7-9444-a1b4b0204193.png">

This same footer should be added to the form you see when you need to create an account during Jetpack connection.

1. install/activate Jetpack on a self-hosted site. Make sure you use an email address that's not already associated with a WP.com account, to avoid any matching
2. click to connect the site (from within wp-admin)
3. land on a page like below, which you will note does not have the same footer:

<img width="827" alt="screen shot 2017-08-28 at 2 23 09 pm" src="https://user-images.githubusercontent.com/108942/29792066-70128b62-8bfc-11e7-8947-3b7c4e6adfd9.png">

We should be able to use the footer directly from the other Calypso-powered log in page.

**Comment by MichaelArestad** [comment]
@beaulebens @ashleighaxios is this still the plan? If not, can we update the issue or close it?

**Comment by beaulebens** [comment]
Probably best to roll this into the work that @joanrho and Luna have been doing around "branding" these specific flows, to avoid ending up with Jetpack logos everywhere :) I think the latest design for this specific screen has a fullsize Jetpack logo at the top now.

**Comment by beaulebens** [comment]
This has all changed with the new connection flows from Luna. No longer an issue.
