### ISSUE TITLE
JPO: tile in step is not converted to those drilldown-like buttons

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17578]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start/jetpack-onboarding/jpo-contact-form

<img width="375" alt="captura de pantalla 2017-08-28 a la s 20 11 09" src="https://user-images.githubusercontent.com/1041600/29797395-353fe3e6-8c2d-11e7-9e85-c0f79cd389eb.png">

**Comment by ashleighaxios** [comment]
This is as intended. It doesn't need to be a button since it's the only thing on the screen and space isn't an issue – the user can still access, skip, without it being bumped out of the visible area on a phone.
