### ISSUE TITLE
JPO: arrow placement in drilldown-like buttons is inconsisten

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17576]
Maybe these arrows should be vertically centered.

#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start/jetpack-onboarding/jpo-site-type

<img width="456" alt="captura de pantalla 2017-08-28 a la s 20 03 25" src="https://user-images.githubusercontent.com/1041600/29797174-17de046e-8c2c-11e7-8153-a978458e8d1f.png">

<img width="457" alt="captura de pantalla 2017-08-28 a la s 20 03 15" src="https://user-images.githubusercontent.com/1041600/29797178-1a3e2c3e-8c2c-11e7-94c0-83266509c7b8.png">

**Comment by ashleighaxios** [comment]
This is as intended.

**Comment by eliorivero** [comment]
The fact that they are inconsistent from one to another looks broken as pointed in the images below. While they maybe don't have to be centered, they must be consistent regarding their positioning.

<img width="456" alt="29797174-17de046e-8c2c-11e7-8153-a978458e8d1f" src="https://user-images.githubusercontent.com/1041600/29828410-04236054-8cb3-11e7-9d24-7b02e041b15d.png">

<img width="457" alt="29797178-1a3e2c3e-8c2c-11e7-94c0-83266509c7b8" src="https://user-images.githubusercontent.com/1041600/29828411-0451c50c-8cb3-11e7-9d53-d5a59b4ac615.png">

**Comment by tyxla** [comment]
No longer relevant - we're centering those now (see #20640), cc @MichaelArestad.
