### ISSUE TITLE
JPO: tiles converted to drilldown buttons shouldn't animate downwards

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17579]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start/jetpack-onboarding/jpo-site-type

#### What I expected
Drilldown buttons to animate towards left

#### What happened instead
Animation from tiles was preserved, resulting in awkward looking drilldowns
![animation](https://user-images.githubusercontent.com/1041600/29797465-917bafa0-8c2d-11e7-85ec-539d4ac8c331.gif)
In one of them the step doesn't even animate at all, which was noted before in #17430

**Comment by tyxla** [comment]
Will be taken care as we deal with the rest of the animations work (https://github.com/Automattic/wp-calypso/projects/55#card-6102609), closing this one.
