### ISSUE TITLE
JPO: in mobile, button borders are shown when they shouldn't

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17577]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start/jetpack-onboarding/jpo-site-type

<img width="459" alt="captura de pantalla 2017-08-28 a la s 20 09 24" src="https://user-images.githubusercontent.com/1041600/29797350-efab5338-8c2c-11e7-951e-b0de226e38f3.png">

**Comment by ashleighaxios** [comment]
I made this change. Code must have been lost along the way, please recover.

**Comment by eliorivero** [comment]
Can you point where was this added so I can re-add it?

**Comment by tyxla** [comment]
This is no longer relevant in the latest implementation.
