### ISSUE TITLE
Editor: make the permalink popover full width

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1758]
Raised by @jkudish 

It strikes me as odd UX that we don't use the full width available for the permalink popover.

![screen shot 2015-12-17 at 16 47 18](https://cloud.githubusercontent.com/assets/1119271/11883007/ef031cdc-a4dd-11e5-8aed-c3404258fd52.png)

Why couldn't this extend to the end of the editor's right border?

Especially bad for a Jetpack site when there's no permalink set:

![screen shot 2015-12-17 at 16 49 56](https://cloud.githubusercontent.com/assets/1119271/11883057/49718faa-a4de-11e5-82b8-0708fb332156.png)

Note from @kellychoffman 

> That does look strange. It really shouldn't fade unless there's _actually_ no room. Also, the vertical alignment is quite off in your second screenshot.

**Comment by designsimply** [comment]
Tested and confirmed this is still an issue.

**Comment by designsimply** [comment]
May I please have a 2nd opinion from a designer about this issue?

**Comment by drw158** [comment]
I've seen some issues like this just get ignored because of Gutenberg. If there is something easy we can do in the meantime, it would be worth it.

**Comment by kellychoffman** [comment]
This feels very low priority.

**Comment by designsimply** [comment]
Cool. Moving to low priority and giving it a chance to pop up again naturally before closing. Thank you for the input!

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated](https://github.com/Automattic/wp-calypso/milestone/309?closed=1), I don't think this issue is relevant any longer. But please feel free to re-open it if that's incorrect.
