### ISSUE TITLE
JPO: tiles are huge between breakpoints

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17581]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start/jetpack-onboarding/jpo-homepage

Only visible from 499px width down to 480px.

<img width="499" alt="captura de pantalla 2017-08-28 a la s 20 25 52" src="https://user-images.githubusercontent.com/1041600/29797703-20735144-8c2f-11e7-86b3-475075934f56.png">

**Comment by tyxla** [comment]
Not relevant to the latest implementation, closing.
