### ISSUE TITLE
JPO: inconsistent explanation in drilldown buttons

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17580]
The drilldown buttons in one of the steps don't have explanations below.

#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start/jetpack-onboarding/jpo-site-type

<img width="456" alt="captura de pantalla 2017-08-28 a la s 20 03 25" src="https://user-images.githubusercontent.com/1041600/29797174-17de046e-8c2c-11e7-8153-a978458e8d1f.png">

<img width="457" alt="captura de pantalla 2017-08-28 a la s 20 03 15" src="https://user-images.githubusercontent.com/1041600/29797178-1a3e2c3e-8c2c-11e7-94c0-83266509c7b8.png">

<img width="459" alt="captura de pantalla 2017-08-28 a la s 20 09 24" src="https://user-images.githubusercontent.com/1041600/29797350-efab5338-8c2c-11e7-951e-b0de226e38f3.png">

**Comment by ashleighaxios** [comment]
This is as planned; reflected in comps and prototypes.
