### ISSUE TITLE
Editor: Dragging selected text highlights the featured image dropzone

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#17597]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Select a site to start a new post.
3. Add a title and text in the post body.
4. Select the title text and drag it.
5. Open the post URL dialog, select the post slug, and drag it.
6. In the Visual editor, select some of the text, and drag it. (Try dragging and dropping it within the post body, and then try dragging and dropping it outside the post body.)
7. Switch to HTML mode in the post body, select some of the text, and drag it.

#### What I expected

I expected to be able to drag and drop text to move it around in the editor, with no other effects.

#### What happened instead

In each case when I selected and dragged text the featured image dropzone was highlighted. Dragging the text to the dropzone had no effect.

I was only able to drag selected text to move it in the Visual editor. In HTML mode or other fields, dragging the selected text to another area didn't move it.

#### Browser / OS version

Mac OSX 10.12.6, Chrome 60

#### Screenshot / Video

![editor-dragtext-featuredimage](https://user-images.githubusercontent.com/8658164/29824164-a25ee472-8cc8-11e7-8024-62567aeaa36c.gif)

#### Context / Source

#dogfooding

**Comment by lancewillett** [comment]
CC @bisko Could you or someone on Samus take a look at this one?

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
