### ISSUE TITLE
Editor: popover permalink is misaligned

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1759]
Steps to reproduce:

1. Go to https://wordpress.com/post for a Jetpack site
1. Add a title and save
1. Click the link icon next to the title to reveal the permalink and look at the alignment

<strong>Result:</strong> the alignment should be vertically centered in the popover but it's offset.

![screen shot 2015-12-17 at 16 49 59](https://cloud.githubusercontent.com/assets/1119271/11883173/065f02e6-a4df-11e5-9915-6af47b842662.png)

/hat tip @kellychoffman for the original report

**Comment by mtias** [comment]
it seems aligned now.
