### ISSUE TITLE
Jetpack Scan: do not save password when the initial set up is cancelled

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#176]
When quitting the Jetpack Scan set up, the password that has been entered is saved, and is shown when trying to start the set up again (and the rest of the set up info is not). Here are the steps to reproduce:
1. Click on 'Activate Scan'

![activate-scan](https://cloud.githubusercontent.com/assets/11487924/8660368/89ae8356-297e-11e5-9467-a96f607bdbb1.png)
1. Enter SSH info, including username and password

![enter-info](https://cloud.githubusercontent.com/assets/11487924/8660356/7873c588-297e-11e5-9c75-45281f12fb50.png)
1. Click on 'Deactivate' to leave the settings screen

![click-on-deactivate](https://cloud.githubusercontent.com/assets/11487924/8660358/7de90244-297e-11e5-9df0-d4071a51ad6f.png)
1. Click on 'Activate Scan' again

![activate-scan](https://cloud.githubusercontent.com/assets/11487924/8660368/89ae8356-297e-11e5-9467-a96f607bdbb1.png)
1. See previously entered password

![see-password](https://cloud.githubusercontent.com/assets/11487924/8660395/b28cae7e-297e-11e5-83b9-9671148c4fd9.png)

Instead, none of the previously not-saved info should be shown.

**Comment by designsimply** [comment]
Blocked from testing by #4945 ([28s](https://cloudup.com/c6YIX11lRHr))
