### ISSUE TITLE
Jetpack Connect: Happychat prompt

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#17604]
**Currently** we have links to 'install Jetpack manually' (yuck) and 'start a new WordPress.com site' (which is not really a sensical option during this flow and gets essentially no usage). The third option is to get help (currently a link to the jetpack contact form). 

![image](https://user-images.githubusercontent.com/437258/29843995-d1fc3d16-8cdb-11e7-8e03-fd3285f7a9dd.png)

**Instead** let's get happychat implemented as the only other option on the approval screen and any other post-logged-in screens:

![image](https://user-images.githubusercontent.com/437258/29843976-c08239c8-8cdb-11e7-8a3a-180175500fb4.png)

cc @oskosk @johnHackworth @annezazu

**Comment by annezazu** [comment]
VERY much in favor of this - thank you for noting this.

**Comment by beaulebens** [comment]
Note this will only apply/be possible (currently) if the user is logged in.

**Comment by rickybanister** [comment]
We should perhaps test a version of JPC where you create the account first rather than after Jetpack is installed. But your point is taken @beaulebens

**Comment by rickybanister** [comment]
If this is created as a jpc help component it can be applied to all the open connection chat issues (I'm sure that's obvious, just noting for my own peace of mind).

**Comment by tyxla** [comment]
This one is being addressed by #18397, which also contains #18396 (which introduces a Happychat button component) and #18393 (which fixes an error).
