### ISSUE TITLE
Plans: clicking a banner should highlight the appropriate plan with a ribbon

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#17609]
Currently we highlight the Personal plan as 'new' with a primary button, regardless of the context. If I click an upgrade banner for, say, Ads which requires the premium plan or above it should highlight the plan advertised in the banner.

Currently:

![image](https://user-images.githubusercontent.com/437258/29846101-699049fe-8ce3-11e7-85a6-356e31e7bb20.png)

Proposed:

![image](https://user-images.githubusercontent.com/437258/29846168-b5ef44b2-8ce3-11e7-952e-5537b1199d62.png)

cc @johnHackworth @tyxla @gwwar @richardmuscat

**Comment by gwwar** [comment]
For context wpcom plans show "popular":

<img width="798" alt="screen shot 2017-08-29 at 3 02 03 pm" src="https://user-images.githubusercontent.com/1270189/29846301-1b16b29e-8ccb-11e7-8819-2775deceb914.png">

I think highlighting the premium plan makes sense, but we may want to avoid saying that it's "suggested" until we have a better understanding of our user needs. (For example if they come in from a survey saying they'd like to build a Business vs wanting a personal blog).

**Comment by rickybanister** [comment]
Yes, agreed totally, I'm familiar with the 'popular' ribbon. In my case I clicked through this banner:

![image](https://user-images.githubusercontent.com/437258/29846673-d5ee77a4-8ce5-11e7-8915-a18e1081c0e6.png)

Which is recommending me a Premium plan in order to unlock Ads. When I get to the plans page I see the 'monetize your site' feature highlighted because of the banner referral. That's why I suggested changing the ribbon to 'recommended' (or similar) in cases like this only.

**Comment by gwwar** [comment]
@rickybanister ah gotcha, that makes a lot of sense.

**Comment by tyxla** [comment]
That's partially related with this one: #15671

**Comment by allendav** [comment]
Also ran into this this morning myself. Got prompt for business plan but then premium plan got the emphasis:

<img width="1084" alt="screen shot 2017-09-21 at 10 00 24 am" src="https://user-images.githubusercontent.com/1595739/30708435-c6796e3e-9eb3-11e7-9683-668753253f98.png">

<img width="1089" alt="screen shot 2017-09-21 at 10 00 35 am" src="https://user-images.githubusercontent.com/1595739/30708447-cc399a42-9eb3-11e7-82b5-f10783dd22c9.png">
