### ISSUE TITLE
Editor: Issues with global notices

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#1760]
**(1)** Width is incorrect:

<img width="1275" alt="editor jetpack notice bug" src="https://cloud.githubusercontent.com/assets/227022/11883277/6801c298-a4d7-11e5-946c-e7cc0113bd59.png">

**(2)** Ground control component obscures notices (to reproduce this, scroll down until the ground control component starts to pin to the top of the page):

<img width="1279" alt="editor connection notice bug" src="https://cloud.githubusercontent.com/assets/227022/11883221/10c0faf8-a4d7-11e5-8f41-0e900d8614ae.png">

**Comment by beaulebens** [comment]
Closing this as these were fixed somewhere along the line.
