### ISSUE TITLE
Show who liked on hover

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17607]
(Putting this in the Conversations milestone, but it's really a To Do for Reader in General.)

In Reader, we display "X Likes" in many places: in the cards in streams, on comments on Fullpost, and soon in Conversations. But there's no way to tell exactly who liked it. Hovering over "X Likes" currently looks like this:

<img width="244" alt="screen shot 2017-08-29 at 10 58 03 am" src="https://user-images.githubusercontent.com/24388/29845226-e7c60a6a-8cc6-11e7-9bd5-08f83a8c0da1.png">

(Link turns blue, but nothing else.)

We should show a list of who liked the thing on hover like we do on frontend sites. Like so:

<img width="379" alt="screen shot 2017-08-29 at 10 58 34 am" src="https://user-images.githubusercontent.com/24388/29845271-078ee7b8-8cc7-11e7-974e-e985aaaf4acf.png">

I suggest we use the standard popover we're using for Share, just with names and avatars in it.

Thoughts?

cc @jancavan

**Comment by gziolo** [comment]
@fraying I'm going to teach Calypso Basics class at the company meetup. I'm looking for a small task I could code in a front of a class. This one caught my attention. Can we agree on the initial design this week so I could estimate if it would fit 2-3 hours session finished with live deploy? 😃

**Comment by gziolo** [comment]
@blowery or @samouri do you know if data nedeed for this feature is already present in Calypso or at least accessible through REST API?

**Comment by fraying** [comment]
@gziolo Oh that's fantastic!

As for design, we have a standard popover design you can use. (Click any Share link to see it.) All I'd request is that we show the avatars in circles, since that's the standard we use elsewhere.

**Comment by gziolo** [comment]
This is how it looks on WordPress.com blog at the moment:
![screen shot 2017-09-04 at 21 13 35](https://user-images.githubusercontent.com/699132/30036703-f4ef88c6-91b5-11e7-91c5-ce72b3c129f4.png)

It outputs 20 avatars, but only 18 of them are visible on large screen, on mobile it is even more limited. Should we replicate that on Reader, too?

**Comment by fraying** [comment]
@gziolo We could, but that's not what this ticket is about.

This ticket is about showing who liked a thing (a post or a comment) on hover in the stream (or wherever "X Likes" is shown.

Does that make sense?

**Comment by gziolo** [comment]
Yes, it makes perfect sense. My question is still valid, what is the max number of avatars of people who liked a given post/comment/whatever?

**Comment by fraying** [comment]
@gziolo In Reader, the Share popover is scrollable, so I don't think we need to limit it at all. 

In other places, we paginate it. Check out how the "liked" hover for comments on Daily Post (like https://dailypost.wordpress.com/2017/09/04/community-pool-232/ for example). They show all the likers and paginate like this:

<img width="328" alt="screen shot 2017-09-04 at 12 30 54 pm" src="https://user-images.githubusercontent.com/24388/30037047-146a14e4-916d-11e7-8881-e6ee97bd9502.png">

**Comment by fraying** [comment]
I did a quick mockup of what I had in mind.

![liked-by-popover](https://user-images.githubusercontent.com/24388/30038496-1cfd4db2-917a-11e7-8240-e4c28ed595de.png)

cc @jancavan

**Comment by gziolo** [comment]
Thanks for the mockup. Now it is all clear for real 😃 We will work on it together with @belcherj in the front of the class. Let's see how far we can go.

**Comment by mtias** [comment]
@gziolo there's already a post likes block. It'd be just putting it in a popover:

https://wpcalypso.wordpress.com/devdocs/blocks/post-likes

**Comment by samouri** [comment]
The current post likes block is fairly specific w/ how it renders and looks/behaves very differently  from the mock in https://github.com/Automattic/wp-calypso/issues/17607#issuecomment-327028033.  Only similarity is gravatars and likes fetching.

I'm using the PostLikes block as inspiration but rolling our own for this use case.

**Comment by jancavan** [comment]
I'm working on mockups for showing gravatars for Likers in fullpost (as well as comments in fullpost) that's not using hover. I'll be posting the prototypes soon.

**Comment by jancavan** [comment]
Closing this. We have a new design that shows Likers without using hover.

**Comment by bluefuton** [comment]
Considering this fixed by https://github.com/Automattic/wp-calypso/pull/24612.

**Comment by nylen** [comment]
@bluefuton I would have left this open until a `CommentLikesPopover` is also implemented, but it's up to y'all.

**Comment by bluefuton** [comment]
@nylen just added a new issue to our feature backlog to cover comment likes: https://github.com/Automattic/wp-calypso/issues/25465
