### ISSUE TITLE
Editor: Featured image overlaps "published" notice

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#1761]
<img width="1276" alt="editor featured image notice bug" src="https://cloud.githubusercontent.com/assets/227022/11883352/ea330bbe-a4d7-11e5-9907-8cac53c6a380.png">

Repro steps:

1. [Open the editor](http://calypso.localhost:3000/post).
2. Add a featured image to a post.
3. Publish the post.

**Comment by hoverduck** [comment]
21Apr16 Bug Scrub

Closing.  The Published banner is now below the featured image:

![image](https://cloud.githubusercontent.com/assets/7233112/14715838/6c2d85f2-07b8-11e6-81a4-545bcc746c2b.png)
