### ISSUE TITLE
Atomic: Import from Medium displays in Calypso but doesn't work

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#17631]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Check the page, you can read as follows:

```
Import
Import content from another WordPress or Medium site.
```

#### What I expected

To be able to import from Medium as can be seen in the support docs here: https://en.support.wordpress.com/import/import-from-medium/

#### What happened instead

I'm redirected to https://domain.com/wp-admin/import.php where the Medium import option is not available.

#### Screenshot / Video

<img width="644" alt="screen shot 2017-08-30 at 15 24 06" src="https://user-images.githubusercontent.com/3812076/29874697-dccbca2e-8d97-11e7-9727-f0a4bbac7d8c.png">

cc: @katinthehatsite

**Comment by lancewillett** [comment]
This is a good find — relates to an important gap with Jetpack sites: https://github.com/Automattic/wp-calypso/issues/10894

**Comment by lancewillett** [comment]
See also https://github.com/Automattic/wp-calypso/issues/17340

**Comment by katinthehatsite** [comment]
Reported by the user in #1047121-zen

**Comment by marekhrabe** [comment]
What about replacing the subtitle with something like "Import content from other platforms" or "…WordPress and other platforms" to keep the most important one? This change will also be more future proof should we port more importers from wp-admin to Calypso.

**Comment by lancewillett** [comment]
@marekhrabe That would work well, especially as we expand the importers to more over time.

**Comment by lancewillett** [comment]
@marekhrabe 👀 https://github.com/Automattic/wp-calypso/pull/23964 please?
