### ISSUE TITLE
JPO: clean up CSS classes

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17639]
All CSS classes should follow Calypso standard. There are some that do not, like

https://github.com/Automattic/wp-calypso/pull/17094/files#diff-3f01c5fdd909d9f769bafd0e12bcf0baR42

jpo__site-type-wrapper

https://github.com/Automattic/wp-calypso/pull/17094/files#diff-0459f28218ae241fe9fe4b71ba8011baR96
https://github.com/Automattic/wp-calypso/pull/17094/files#diff-5f749bfaea4ae1cdc2d76c2dfcb4d871R1

jpo__summary-wrapper

in the latter, the styles should be nested in the SCSS file

and its associated SCSS, which should be nested

**Comment by tyxla** [comment]
Not relevant with the latest implementation, closing.
