### ISSUE TITLE
JPO: adjust width of Connect form in its step

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17638]
Right now it's looking like this and it shouldn't look this wide.

<img width="1006" alt="captura de pantalla 2017-08-30 a la s 12 54 15" src="https://user-images.githubusercontent.com/1041600/29882160-979e1b88-8d82-11e7-9c7d-056dbf67a940.png">

**Comment by tyxla** [comment]
We'll be using connection flow from Jetpack Services, so this one is no longer relevant.
