### ISSUE TITLE
JPO: Step 3 back button function

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17649]
_As mentioned in project Slack July 27_

Going back from this step should take the user to their previous step (step 2b, 2c, or 2d), not step 1.
<img width="720" alt="screen shot 2017-08-30 at 1 36 58 pm" src="https://user-images.githubusercontent.com/22752103/29886586-8c95675e-8d88-11e7-9384-d934f679c550.png">

**Comment by tyxla** [comment]
Not relevant to the latest implementation, where the flow is constantly informed about the latest logic that defines the steps.

Closing.
