### ISSUE TITLE
JPO: Step 2c back button function

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17648]
_As mentioned in project Slack July 27_

Going back from this step should take the user to their previous step (step 2a or 2b), not step 1.
<img width="649" alt="screen shot 2017-08-30 at 1 34 17 pm" src="https://user-images.githubusercontent.com/22752103/29886445-140d0e90-8d88-11e7-913e-cc219ac09c55.png">

**Comment by tyxla** [comment]
Not relevant to the latest implementation, where the flow is constantly informed about the latest logic that defines the steps.

Closing.
