### ISSUE TITLE
JPO: 2B back button function

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17647]
_As mentioned in project Slack July 27_

Going back from this step should take the user to step 2(a), not step 1.
<img width="704" alt="screen shot 2017-08-30 at 1 31 30 pm" src="https://user-images.githubusercontent.com/22752103/29886313-a3e54a4c-8d87-11e7-8599-7c46252a16a5.png">

**Comment by tyxla** [comment]
Not relevant to the latest implementation, where the flow is constantly informed about the latest logic that defines the steps.

Closing.
