### ISSUE TITLE
JPO: Online Store Flow Correction

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17646]
_As mentioned in project Slack July 27_

<img width="1054" alt="screen shot 2017-08-30 at 1 24 28 pm" src="https://user-images.githubusercontent.com/22752103/29885989-a3dfda86-8d86-11e7-877a-aeacf5ec668c.png">

Selecting "online store" should take the user through to the business address form
<img width="757" alt="screen shot 2017-08-30 at 1 24 51 pm" src="https://user-images.githubusercontent.com/22752103/29886013-b0284080-8d86-11e7-9d44-92b9c8ec852d.png">
Bypassing the Personal or Business step for the user, while collecting that data as "business" for our records.
<img width="728" alt="screen shot 2017-08-30 at 1 25 36 pm" src="https://user-images.githubusercontent.com/22752103/29886049-cc1c15b4-8d86-11e7-8364-ae20eb707353.png">

**Comment by tyxla** [comment]
Not relevant to the latest implementation, closing.
