### ISSUE TITLE
Editor: optimize flow for adding categories

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1764]
Raised by @aduth 

Here is a typical user flow for a user who wants to add a new category to their site, observed in a recent UserTesting result:
1. Search their existing set of categories for the desired category
2. **Click Add New Category after observing the category doesn't exist**
3. **Click to focus the Category name field**
4. Enter the category name
5. **Click OK**

The bolded items seem to be unnecessary impediments to adding a new category. To address each:

_#__2_: A user should be able to press Enter at this point to add a new category
_#__3_: The name field should automatically be focussed when showing the Add Category dialog
_#__5_: Similar to _#__2_, a user should be able to press Enter to confirm the category without leaving the field

Video snippet: https://cloudup.com/cjaRWIpjn67

Note from @timmyc 

> All good ideas. I also think having a stand-alone category management page would be quite nice as well. Managing categories within the context of the editor, while it can be done, is not an optimal experience.

**Comment by alisterscott** [comment]
Update, only step 2 is still an issue. Steps 3 and 5 have been addressed already.

**Comment by timmyc** [comment]
I believe this was all implemented when we updated categories to use the new term management functionality this past fall.  I tested the flow and it worked as expected now.  Closing this out.
