### ISSUE TITLE
JPO: Business address form - active first field

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17654]
Make the Business Name field active and in focus on load.
<img width="544" alt="screen shot 2017-08-30 at 3 31 31 pm" src="https://user-images.githubusercontent.com/22752103/29891266-78cdcaee-8d98-11e7-9df9-7c224ec2cd76.png">

**Comment by tyxla** [comment]
Kudos for the idea, this will be addressed in #20622. Closing this one as it's no longer necessary.
