### ISSUE TITLE
Editor: implement an offline mode

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1765]
Raised by @codebykat 

With the advent of the desktop app, it would be incredibly cool to have an offline editing mode (maybe in the browser as well). With the way the editor is currently written, this seems like it will be reasonably complex (e.g. we will have to have an offline cache of taxonomies, sharing targets, all the stuff we currently make API requests to load). But a basic version could just be localstorage autosaves and more robust recovery from connectivity issues.

Related: #315, #328

**Comment by folletto** [comment]
This should probably be an offline framework that is Calypso wise, that is then used by each section, like the Editor. :)

**Comment by KokkieH** [comment]
Had a request for this in 751267-f.

**Comment by gibrown** [comment]
Also mentioned in this article: http://www.omgubuntu.co.uk/2017/05/wordpress-desktop-app-snap#comment-3300286244

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Recommend closing in favor of making a separate issue for Calypso as a whole (as recommended above). Would like a 2nd opinion. @apeatling, may I have your opinion on this one?

**Comment by apeatling** [comment]
Yes this would be encompassed by offline Calypso as a whole.
