### ISSUE TITLE
JPO: Step 1 - Title field active

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17653]
Make the Title field active and in focus on Step 1 load.
<img width="617" alt="screen shot 2017-08-30 at 3 28 32 pm" src="https://user-images.githubusercontent.com/22752103/29891104-f116cfe2-8d97-11e7-8c4b-c4b7d977c58e.png">
<img width="400" alt="screen shot 2017-08-30 at 3 29 19 pm" src="https://user-images.githubusercontent.com/22752103/29891126-03bed14e-8d98-11e7-8147-b781351c23b6.png">

**Comment by tyxla** [comment]
Kudos for the idea, this is being addressed in #20700. Closing this one as it's no longer necessary.
