### ISSUE TITLE
Editor: Nothing shown in schedule tooltip for posts without a title 

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#17665]
**Steps to reproduce**
1. Create a new post 
2. Add text to the post body, don't give the post a title
3. Select a day / time to schedule the post
4. Schedule the post
5. Open up the editor for a different post and open the date picker
6. Hover over the date for the post that was just scheduled

#### What I expected

The date picker would display the a snippet from the beginning of the post text 

#### What happened instead

The date picker displayed an empty space with nothing in it (referring to the space above "post scheduled" in the screenshot below) 

#### Browser / OS version

Chrome / Mac OS

#### Screenshot / Video

<img width="296" alt="screen shot 2017-08-30 at 11 59 26 am" src="https://user-images.githubusercontent.com/161697/29899074-1e98589a-8d9e-11e7-9640-13043ab779c6.png">

**Comment by lancewillett** [comment]
Good find! We've had a few issues with posts without a title over the years; this is another good case to catch.
