### ISSUE TITLE
JPO: Step 4 - structure improvements

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17660]
Get back the styles and structural fixes added for the contact form step (step 4) lost in this merge issues of #17463.

1) There should be a HR above the button and description text.

Like:
<img width="324" alt="screen shot 2017-08-30 at 5 16 57 pm" src="https://user-images.githubusercontent.com/22752103/29895426-0f5db470-8da7-11e7-9095-9425b03a7713.png">

Vs how it is:
<img width="368" alt="screen shot 2017-08-30 at 5 16 30 pm" src="https://user-images.githubusercontent.com/22752103/29895415-04cf7dc2-8da7-11e7-8cff-3c65177c0668.png">

2) The area near the block should not be clickable. Right now you can hover over the area and then select to the left and right of the box and functionally select the block.

**Comment by tyxla** [comment]
Not relevant with the latest implementation, closing.
