### ISSUE TITLE
Editor: add size details when changing image size from toolbar

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1766]
Raised by @kriskarkoski 

When changing image sizes between the large and full size (default) options there is no visual indication as the images generally max-out the editor width. 

We should add some size indication right where the change is happening with the +/- icons.

Here's a video of the experience (I switch to the HTML view to show the image size is actually being changed):

https://cloudup.com/cZmvjGxa8bc

**Comment by drw158** [comment]
One suggestion: a small 'label' positioned bottom right of the image. It could read 'small', 'medium', 'fullscreen', etc.

We should see how Gutenberg handles this.

**Comment by alisterscott** [comment]
I'll close this one in that images will be Gutenberg blocks so this can be done as part of Gutenberg

#bug-scrub #pre-gutenburg-bug-purge
