### ISSUE TITLE
JPO: Step 2 - Personal Site SVG change

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/wp-calypso#17661]
Some colors changed in the uploading of the SVGs. 
Comps:
<img width="673" alt="screen shot 2017-08-30 at 5 23 19 pm" src="https://user-images.githubusercontent.com/22752103/29895650-f185a182-8da7-11e7-8eb3-f43de7d24c79.png">

Current:
<img width="654" alt="screen shot 2017-08-30 at 5 23 34 pm" src="https://user-images.githubusercontent.com/22752103/29895663-f9f00e7a-8da7-11e7-9b70-5a9a6fec3aea.png">

Add the Personal Site SVG again.

**Comment by ashleighaxios** [comment]
The file were reshared in project Slack in July 27 when the issue was first pointed out.

**Comment by tyxla** [comment]
The latest illustrations are already in (see #20407), closing this one.
