### ISSUE TITLE
Domains: .fr organization field can be left blank

### ISSUE THREAD

**Issue by hewsut** [Automattic/wp-calypso#17666]
Problem:
.fr registrants can:
1. Leave the organization field empty on the main contact details page.
2. Select organization as the registration type on the secondary (.fr specific) page.
3. Checkout successfully, leading to a default firstname+lastname "org" value at registrar.

**The inaccurate org name could bite the registrant/us later when AFNIC trawls through auditing.**

Probable solution:
Display the organization field again on the secondary (.fr specific) details page and require it there before final checkout. We can either do this only when left blank or prefill it and do it always just to be consistent/put the field in context with the other related details.

<img width="757" alt="screen shot 2017-08-30 at 9 51 18 pm" src="https://user-images.githubusercontent.com/2006764/29902646-6236eccc-8dcd-11e7-84ff-50b1ebf5907e.png">

<img width="742" alt="screen shot 2017-08-30 at 9 49 57 pm" src="https://user-images.githubusercontent.com/2006764/29902627-3b4d75fe-8dcd-11e7-91fa-689e9b831e9c.png">

**Comment by deBhal** [comment]
Fixed in #20043
