### ISSUE TITLE
Conversation Caterpillar: Show all

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#17663]
![screenshot 2017-08-30 14 55 16](https://user-images.githubusercontent.com/4924246/29896803-52232100-8d93-11e7-8b39-81cb0adf75df.png)

![cat-ex-11](https://user-images.githubusercontent.com/4656974/29985371-b6e71c46-8f2c-11e7-9c3b-4b46c118d8a4.png)

Next to the caterpillar, there should be a "Show all/Hide all" link as a way to expand/collapse all comments in the caterpillar.

This is what it looks like with the "Hide all" link:
<img width="810" alt="screenshot 2017-09-08 14 20 34" src="https://user-images.githubusercontent.com/4924246/30231715-01bccf9e-94a1-11e7-8db2-2620b6a9d3d8.png">

**Comment by samouri** [comment]
Closing because the basic ui is complete as of #17717.
Pagination is the only part left of this: https://github.com/Automattic/wp-calypso/issues/17718

**Comment by jancavan** [comment]
@samouri It's supposed to change to "Hide all" when all comments are expanded.

> It becomes “Hide all” when comments are expanded, so the user can minimize conversations they don’t care about.

**Comment by jancavan** [comment]
We've removed "Show all" in: https://github.com/Automattic/wp-calypso/pull/18766 so closing this for now.
