### ISSUE TITLE
Editor: author duplicated and title uneditable in Safari if Ghostery is set to block Gravatar

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1767]
Raised by @kriskarkoski 

The Ghostery extension (https://www.ghostery.com/) optionally blocks Gravatar. When this block is enabled, the Calypso Editor is broken in Safari with the post author dropdown not working and the text being duplicated and the title field not accepting any text:

![screen shot 2015-11-02 at 4 32 11 pm](https://cloud.githubusercontent.com/assets/1900444/10894970/8d017c6c-817f-11e5-99f6-978e9de29563.png)

Found via a failed user test. I tested Ghostery with Gravatar blocking enabled in Chrome and the Editor worked normally as far as I could tell, at least these issues were not present.

From some Slack discussion it sounds like Ghostery users are pretty familiar with this happening. If we can address it on our end great, but marking as low priority.

**Comment by rachelmcr** [comment]
Closing as this is low priority and specific to a browser extension.

#bug-scrub #pre-gutenburg-bug-purge
