### ISSUE TITLE
Plugins: Install button missing from plugins page after initial AT plugin installation 

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#17686]
#### Steps to reproduce
1. On a new site with a business plan, add a plugin (ex: WooCommerce)
2. Wait while the plugin installs
3. When the "Activating plugin" message appears, navigate away from the plugins page (ex: stats) 
4. Navigate back to the plugins page by clicking "Add" 
5. Click on any other uninstalled plugin to view the plugin details 
6. The install button is not available on the plugins page 

The install button is not available on any subsequent plugins page. The only thing that brings the Install button back is a hard refresh on the page (cmd+shift+R)

#### What I expected
That the Install button would be available on any plugins page 

#### What happened instead
The install button disappears after the installation of the first plugin on a new site that just went through AT

#### Browser / OS version
Chrome / Mac OS

#### Screenshot / Video
<img width="742" alt="screen shot 2017-08-31 at 4 31 58 pm" src="https://user-images.githubusercontent.com/161697/29949491-0f4fe3ae-8e6a-11e7-86e5-f0cf3fa8c7b5.png">

**Comment by DanielSmithMichigan** [comment]
I think the steps to reproduce may be simpler than what is stated here:

1. On a new site with a business plan, add a plugin (ex: WooCommerce)
2. Wait until it's done
3. Navigate to a new plugin page
4. Install button is missing

https://user-images.githubusercontent.com/10274366/116948229-dec6e200-ac4c-11eb-87c6-26923b0600cc.mov

**Comment by allilevine** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/52807
