### ISSUE TITLE
Comments: wp-admin ignores moderate_comments

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17687]
It turns out that wp-admin does not respect moderate_comments at all. https://core.trac.wordpress.org/ticket/6907#comment:4

At a high level this means that a default Author role can moderate comments on their post in wp-admin, but cannot using our rest apis.

Unless there are security concerns, I would recommend modifying the comment endpoints to match wp-admin behavior.

To summarize:
- Visibility of edit-comments.php checks `edit_posts` instead of `moderate_comments`
- Authors in wp-admin can see all comments (pending too), but they can only moderate comments on their own blog posts. The action bar is missing from other comments
![wp-admin](https://user-images.githubusercontent.com/1270189/29987582-ca82a8a6-8f1d-11e7-81ef-f3fa97924bf3.gif)
- The API endpoints are much stricter. An author can only see approved comments, unapproved comments on their post, and cannot moderate _any_ comments.
<img width="770" alt="screen shot 2017-09-01 at 2 00 47 pm" src="https://user-images.githubusercontent.com/1270189/29987617-fab515c2-8f1d-11e7-838f-df003b700013.png">

![commentactions](https://user-images.githubusercontent.com/1270189/29987788-ac1bf286-8f1e-11e7-9c0f-c5b085890d4a.gif)

**Comment by gwwar** [comment]
Also probably related:
https://github.com/Automattic/notifications-panel/issues/180
https://github.com/Automattic/wp-calypso/issues/10529

**Comment by gwwar** [comment]
Verified that `edit-comments.php` uses `edit_posts` instead of moderate_comments

The list is also filtered by:

```php
foreach ( $comment_ids as $comment_id ) { // Check the permissions on each
		if ( !current_user_can( 'edit_comment', $comment_id ) )
			continue;
```

**Comment by kwight** [comment]
Working on this in d7553-code (approve/moderate actions) and d7548-code (view).

**Comment by kwight** [comment]
Fixed in r163946-wpcom and https://github.com/Automattic/jetpack/pull/7980 (v5.5).
