### ISSUE TITLE
Posts: Editor: propagate post deletion events

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1769]
Raised by @codebykat 

For better consistency, both the post list and the editor could listen for the event dispatched when a post gets deleted (in another tab etc) and update their state accordingly.

The drafts drawer could stand to listen for this event as well (from both the editor and the post listing).

Stemmed from discussion in 10630-gh-calypso-pre-oss.

**Comment by alisterscott** [comment]
Confirmed this is still not resolved - but we haven't had an activity on this for over 2 years so closing it for non-activity.
