### ISSUE TITLE
Conversations Caterpillar: improve interaction behavior

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#17712]
Right now clicking a caterpillar doesn't leave one with as delightful a feeling as we wish to impart.
Another potential issue is that it can be challenging to figure out exactly which comments were added to the visible set in cases with 20+ comments.

Heres a video of me interacting with a caterpillar:
![interaction-behavior](https://user-images.githubusercontent.com/4656974/29985542-7abc20da-8f2d-11e7-8814-14e281a92acb.gif)

So open questions:
1. should we have an animation? if yes what should it be?
2. should we make the recently added comments more salient?

**Comment by fraying** [comment]
Yes, we should have an animation. @jancavan expressed an interest here. 

@jancavan has also been looking into a "new!" state for comments. I'm for anything that isn't a fading yellow background.

**Comment by blowery** [comment]
> I'm for anything that isn't a fading yellow background.

😆 agreed.

**Comment by jancavan** [comment]
I have a coded up version of the prototype here: https://codepen.io/jancavan/pen/NaVMPz.

I need help triggering the animation. I'm only using `animation-delay` to chain the animations. The classnames are also temporary.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
