### ISSUE TITLE
Conversation Caterpillar: Show all

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#17711]
Caterpillars should have a section to expand all comments on the right.  Currently they look like:

<img width="897" alt="screen shot 2017-09-01 at 3 43 49 pm" src="https://user-images.githubusercontent.com/4656974/29985320-7f528a18-8f2c-11e7-8625-ffb5196166f2.png">

Whereas they should look like this (notice red arrow pointing to missing button):
![cat-ex-11](https://user-images.githubusercontent.com/4656974/29985371-b6e71c46-8f2c-11e7-9c3b-4b46c118d8a4.png)

**Comment by jancavan** [comment]
Duplicate of: https://github.com/Automattic/wp-calypso/issues/17663

**Comment by samouri** [comment]
whoops! thanks @jancavan
