### ISSUE TITLE
Conversations Caterpillar: Text hover color

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17710]
So happy to see caterpillars appear on wpcalypso! Just one note:

<img width="312" alt="screen shot 2017-09-01 at 12 07 37 pm" src="https://user-images.githubusercontent.com/24388/29984236-37004552-8f0e-11e7-9320-948a9c8ba0c2.png">

The text in a caterpillar ("JacobSHere and 7 more") should turn blue on hover. The same blue the action links turn on hover.

Thanks!

**Comment by jancavan** [comment]
This was fixed in: https://github.com/Automattic/wp-calypso/pull/17881
