### ISSUE TITLE
Editor: need better handling of publishing a private post that has no content yet

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1771]
Raised by @jkudish 

Previews don't work for private posts that aren't published yet. If you get to the last step above (create a new post, try to immediately privately publish it without any content), and it won't let you, we need to deal with disabling previews + changing the Publish button to `Privately publish` (or reverting to public?) until the post is published. Also it's unclear to me how autosaves behave/should behave in that time. In my testing, they seem to stop on their own.

I am open to keeping it as-is (and finding a solution) or having it revert to public (probably easier but potentially confusing?)

Note from @aduth 

> Tricky indeed. Given the user's intended action, I think the ideal approach is to disable Preview and change the Publish button label as you had originally suggested. One other interim solution may be to hide the Private option until the post has some content, though I'm rarely a fan of removing options under obscure circumstances.

See 11437-gh-calypso-pre-oss

**Comment by rachelmcr** [comment]
Currently, if you select "Admins and editors" for the post status (to privately publish the post) it immediately attempts to publish the post. If the post is empty when you attempt to privately publish it, you get the "You haven't written anything yet!" error:

<img width="1440" alt="screenshot 2017-12-22 15 06 14" src="https://user-images.githubusercontent.com/8658164/34312478-11484778-e72a-11e7-9b0e-dcd18385d8a3.png">

However, that selected status remains on the post and once you start adding content the Preview button is no longer disabled but the preview still doesn't work:

<img width="1440" alt="screenshot 2017-12-22 15 06 27" src="https://user-images.githubusercontent.com/8658164/34312494-317bd41a-e72a-11e7-9531-e034cb68b61b.png">

In addition, the publish confirmation step shows the wrong post status:

<img width="1440" alt="screenshot 2017-12-22 15 06 39" src="https://user-images.githubusercontent.com/8658164/34312501-3f55db30-e72a-11e7-9ed5-2ababac00093.png">

It looks like Gutenberg currently resolves this by reverting the post status to public if you try to preview the post with these steps, so I'm going to close this issue in anticipation of that. If this continues to be an issue for Calypso with Gutenberg, we can revisit.

#bug-scrub #pre-gutenburg-bug-purge
