### ISSUE TITLE
Plugins: SidebarNavigation is displayed twice when searching installed plugins

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#17738]
#### Steps to reproduce
1. Starting at URL: list of installed plugins (`/plugins` or `/plugins/manage`) for a Jetpack/Atomic site
2. Make the page less than 660px wide to trigger mobile layout
2. Start typing into the search field, make sure that there are no search results in installed plugins
3. List of suggested plugins from WP.org is displayed

#### What I expected
There's only one `SidebarNavigation` component rendered at the top

#### What happened instead
There are two `SidebarNavigation`s rendered:

<img width="512" alt="double-sidebar-nav" src="https://user-images.githubusercontent.com/664258/30025415-c144f08e-9178-11e7-9ecb-478e422ecd82.png">

#### Why it happens
The `PluginsBrowser` component is being rendered inside a `PluginsMain`, but both components render `Main` with a `SidebarNavigation`. They are intended to be used at top level, not embedded inside something else.

Discovered while working on #17537, but this issue predates our changes.

Cc: @iamtakashi @sirbrillig

**Comment by allilevine** [comment]
This was fixed at some point, possibly by the /plugins to Marketplace redesign. In any case I can't replicate it because we no longer suggest WP.org plugins that way.
