### ISSUE TITLE
Activity Log: event falsely attributed to WordPress

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17739]
Since the API update we've seen a lot of events associated with WordPress. All these instances should be attributed to Jetpack instead.

![image](https://user-images.githubusercontent.com/390760/30025420-640eb470-9170-11e7-86f7-a7976a6fc3d4.png)

![image](https://user-images.githubusercontent.com/390760/30025538-e83a0d76-9170-11e7-90b6-4a021c1a09fc.png)

Note: probably an API issue (?), in which case we should move it there.

**Comment by sirreal** [comment]
Migrated to 80-gh-action-to-activity-log
