### ISSUE TITLE
Activity Log: make compound events clearer

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17742]
Compound events such as “2 plugins have updates available” should:

- a) State all plugin names.
- b) Split them into separate events.

![image](https://user-images.githubusercontent.com/390760/30025795-08fcd718-9172-11e7-8b29-14422df6f7db.png)

It can probably sort itself out if we tackle this one: **Activity Log: send a single update notice** https://github.com/Automattic/wp-calypso/issues/17741

**Comment by sirreal** [comment]
> a) State all plugin names.

Should this happen in the Activity header? What about activity with _lots_ of plugins to update, imagine 10+. Maybe it needs to be something like:

- "Plugins a, b, and c have updates."
- "Plugin a, b, c and 5 more have updates."

Alternatively, this is a place where the header can provide good, basic information, and a nice detailed report could be in the content of the `FoldableCard`.

> b) Split them into separate events.

This would definitely not be a Calypso change, but I think I prefer `a)` as lots of these could get _really_ spammy.

**Comment by keoshi** [comment]
We should always try to group same-action events into one entry, and this is valid not only for plugins, but themes, core events, auto-updates, etc.

I don't believe we have that grouping concept working just yet though we have this compound event. Ideally we should have something like this design-wise, exactly like you describe at the end of a):

![image](https://user-images.githubusercontent.com/390760/30055568-c5aa295a-9227-11e7-89bf-1d635dbd18f1.png)

More context here: p6TEKc-1bx-p2

**Comment by sirreal** [comment]
Something like the following suggestion could be implemented soon with some fairly simple API changes:

> Plugins a, b, and c have updates.
> Plugin a, b, c and 5 more have updates.

Something like the activity grouping by type is quite a bit more complicated and will require significant changes to the API.

**Comment by sirreal** [comment]
Migrated to 83-gh-action-to-activity-log
