### ISSUE TITLE
Activity Log: send a single update notice

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#17741]
An update notice shouldn't be a recurring event, so we should only see these once per each plugin/theme/core/etc. version.

![image](https://user-images.githubusercontent.com/390760/30025592-1c5516be-9171-11e7-9bda-ef34ddb2ec18.png)

Note: probably an API issue (?), in which case we should move it there.

**Comment by sirreal** [comment]
Migrated to 79-gh-action-to-activity-log
