### ISSUE TITLE
Editor: Why is there a close button on the Actions thingy on mobile?

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1774]
Raised by @codebykat 

I am weirded out by the X here:

![11805](https://cloud.githubusercontent.com/assets/1119271/11884588/d27c5758-a4e8-11e5-9f03-9354f84bcf95.png)

It looks like I can click the X to dismiss that like it's a notification, but in fact it closes the editor entirely and goes to my posts page.

Someone explain this to me.

Note from @kriskarkoski 

> Noting that the X is not present if you switch to the Actions section.

Reply from @codebykat 

> Which makes it even weirder. Maybe it's time to rethink the way the Actions / Write / Drafts / Back (to posts list) control works on small screens; I don't think it makes a ton of sense right now.

**Comment by timmyc** [comment]
Funny I was just wondering this yesterday myself.  @mtias any input why this 'x' is here?  Should it "close" the editor and show the sidebar?

**Comment by rachelmcr** [comment]
Closing as this is no longer part of the editor design/behavior.

#bug-scrub #pre-gutenburg-bug-purge
