### ISSUE TITLE
Simple Payments - not loading

### ISSUE THREAD

**Issue by brezocordero** [Automattic/wp-calypso#17767]
#### Steps to reproduce
1. Starting at URL: On a WordPress.com site with a Premium plan.
2. Click on button "Add" next to pages.
3. Click on "Add Payment button"

#### What I expected
The buttons load.

#### What happened instead
The buttons do not load and there is a console error.

#### Screenshot / Video
![http://cld.wthms.co/O2pmQ](http://cld.wthms.co/O2pmQ+)
Link to image here: http://cld.wthms.co/O2pmQ.

![http://cld.wthms.co/USLIiM](http://cld.wthms.co/USLIiM+)
Link to image here: http://cld.wthms.co/USLIiM.

#### Context / Source
#user-report 664979-zen

I haven't been able to reproduce it on a test site with Premium or Business plan.
Seems to be related to this user only.
Maybe there is something on the button previously created

**Comment by lancewillett** [comment]
Let's re-open if you can easily reproduce on other sites with the same plan and settings. Otherwise you can ask this specific customer to remove the older buttons and start again. Maybe also on a different page or post, to test that also.

**Comment by brezocordero** [comment]
Hey @lancewillett How do they remove the buttons? The list doesn't load.

Also @iamgabrielma tried this on the user account:
```
- Click on Add payment button.
- Page is not loading.
- Click on add new.
- Add new button.
- Clicking again on Add payment button is not responsive, nothing happens.

And now the crash:
- Switch to HTML editor.
- Copy the simple payment button shortcode [simple-payment id="14057"] and duplicate it to [simple-payment id="14050"]
- Switch to visual editor.
- Calypso crashed - See screenshot 
````
![http://cld.wthms.co/TwaFdF](http://cld.wthms.co/TwaFdF+)
Link to image here: http://cld.wthms.co/TwaFdF.
