### ISSUE TITLE
Store: Payment received message & refund button shouldn't display for on-hold orders

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#17760]
![order](https://cldup.com/Pbj7pygk7N-3000x3000.png)

If an order is on-hold (paid for with offline payment method, IE check) the "payment received" and refund button message shouldn't display.

**Comment by ryelle** [comment]
Maybe instead of just hiding the card, we should say "Awaiting payment of $5.01 via Check payments"? That way it's very clear that the payment is pending. We could also switch the refund button for a "Mark paid" or "Payment received" button (which would just update the order status to "Processing", I think). What do you think?

**Comment by jameskoster** [comment]
> Maybe instead of just hiding the card, we should say "Awaiting payment of $5.01 via Check payments"?

Yeah good point, I agree.

> We could also switch the refund button for a "Mark paid" or "Payment received" button (which would just update the order status to "Processing", I think). What do you think?

Hmm, trying to think if this step is really worthwhile. Once you've received payment I think you'd probably just skip directly to fulfilling the order? So a "Fulfil" button might be adequate. If you _don't_ want to fulfil immediately then you can still update the status manually.

What do you think @kellychoffman ?

**Comment by kellychoffman** [comment]
> We could also switch the refund button for a "Mark paid" or "Payment received" button (which would just update the order status to "Processing", I think). What do you think?

Yeah, I do think having a 'Payment received' button makes sense as the action for when the payment is on hold, as they directly relate to each other.

**Comment by ryelle** [comment]
I'm about to make a PR for this, but you can see that a user can still go directly to fulfilling an order if they want, the fulfill button still shows up on pending/on-hold orders:

<img width="739" alt="screen shot 2017-09-05 at 11 08 11 am" src="https://user-images.githubusercontent.com/541093/30068132-cd546d20-922a-11e7-9248-93d38d77f1ad.png">
