### ISSUE TITLE
Customizer: Widget Visibility: not all tags load for a site with 1000+ tags

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#17774]
This is probably an edge case, but I have a user with over 1000+ tags. When the user wants to add an image widget in the Customizer and tried to limit the widget visibility based on a tag, the tag does not appear among the choices. 

#### Steps to reproduce - I will give the steps for the user:
1. They have over 1000+ unique tags attached to their posts
2. Go to My Sites - Customize
3. Select Widgets - Sidebar (or any other area)
4. Add Image Widget
5. Edit widget visibility based: select "Show If" - Tag - _search for one of the most recently added tags_

#### What I expected

The recently added tags to be on the list

#### What happened instead

The recently added tags were not among suggestions

#### Context / Source

The user reported that they can not limit their widget visibility based on a tag. For reference, #579842-hc

Similar issue reported earlier: https://github.com/Automattic/wp-calypso/issues/1367

**Comment by rachelmcr** [comment]
As a note, the current (expected) behavior limits tags/categories to 1000 for use with widget visibility rules:

https://github.com/Automattic/jetpack/blob/8440afcf9597d5396e40a4b7ebbb330a9d2f349a/modules/widget-visibility/widget-conditions.php#L73

Setting this as low priority (as with the similar report) since this only effects users with a very large number of tags. If we receive more reports we can adjust the priority accordingly.

**Comment by sandymcfadden** [comment]
Reported by a customer in internal ticket 1154843-zen

Spoke with @jeherve briefly about this and the reason it is set at a limit is for performance. Trying to pull in a large number of tags could cause out of memory errors on sites. The fix would likely require some kind of paging alternative to only pull in x number of tags as the list is scrolled pull in the next x number.

**Comment by carladoria** [comment]
Reported also by [5729931-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=5729931) User will "convert" some tags to categories in the meantime.

**Comment by jartes** [comment]
Another report on 3747225-zen. Informed the user about the limitation and suggested removing some tags or use categories.
