### ISSUE TITLE
Mention Jetpack Security Features under Plugins

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#17780]
I was setting up a new WordPress.com Business plan when I clicked on Plugins and selected "Security":

https://wordpress.com/plugins/ncreading.com?s=Security

<img width="1433" alt="screen shot 2017-09-04 at 8 52 00 pm" src="https://user-images.githubusercontent.com/26996883/30040879-ee0fa142-91b2-11e7-8d9a-e385700dada7.png">

**Problems:**
- Notice that Jetpack is quite far down the list and quietly mentions it's active without showing any value
- There's no obvious indication I have any site security in place at this point.

This seems like a great spot to help educate a user on built in site security features that Jetpack already brings. 

cc @rickybanister as design lead.

**Comment by MichaelArestad** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/21054
