### ISSUE TITLE
Async loaded chunks are downloaded in not-minified version

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#17797]
#### Steps to reproduce
1. Open the Network tab in devtools and set it up to watch loading JS scripts from `/calypso/.*js`
2. Go to https://wordpress.com
3. Calypso with Reader should be displayed
4. Click on the Me section in the masterbar

#### What I expected

All the production JavaScripts are loaded in the minified version (`chunk.hash.min.js`)

#### What happened instead

Here's how the loaded scripts look like for me:

<img width="1041" alt="scripts-loading" src="https://user-images.githubusercontent.com/664258/30064398-e51e9792-9251-11e7-9957-635539d3e5ec.png">

The ones loaded from the `index.html` page, where the URL are generated by the server, are minified. But the ones loaded async by the client use the unminified version.

@blowery @samouri Do you have any idea what's going on here? Maybe a bug in the `manifest.js` script?

**Comment by samouri** [comment]
Thanks for finding this @jsnajdr! I can confirm I'm seeing the same thing.

I've got a hunch i'm exploring.

**Comment by samouri** [comment]
I believe this is a regression from when we (I) ditched the custom async loader: https://github.com/Automattic/wp-calypso/pull/15623/files#diff-af0ff8f84f0c14d14267bd8ccd37db5fL36.

We essentially had a custom loader that monkey patched `require.ensure` and added a couple bits of functionality to it.  One of the bits overlooked was that it also renamed from `.js` --> `.m.js`.  I'm fairly sure we still don't want a loader that does all that, we should be able to get away with one that is small and just renames files.

I'm looking into implementing this now, should only be a few lines

**Comment by samouri** [comment]
just confirmed that its a regression from that PR.  before that async chunks all were loaded with `.m.js` properly.  

Problem is webpack doesn't like that we minify without its consent (we aren't using [UglifyJsPlugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin), we are doing it [externally](https://github.com/Automattic/wp-calypso/blob/master/server/bundler/bin/bundler.js#L116)).  This [pr](https://github.com/Automattic/wp-calypso/pull/16379) will resolve the issue as well but I feel uncomfortable relying upon a beta. 

Until that time where the uglifyplugin 1.0 lands, we can add in a simple plugin as described in: https://github.com/webpack/webpack/issues/803#issuecomment-219263635 which can perform a search/replace for the properfilename extension.  I figure its still hacky, but less hacky than replacing the entire internal `require.ensure` function as we had been doing.

**Comment by lancewillett** [comment]
Hi @samouri Any update on this one? It's been over a month now. OK to close?

**Comment by samouri** [comment]
Thanks for the ping @lancewillett!

Fixed the issue here: https://github.com/Automattic/wp-calypso/pull/17981
Closing
