### ISSUE TITLE
Site Settings: bring over timezone setting

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#178]
In the following thread, users were asking why the timezone setting wasn't brought over into Calypso:

https://en.forums.wordpress.com/topic/missing-a-way-to-change-time-zone?replies=9

I would have expected to find this under Settings -> General like wp-admin, but it's not there:

![image](https://cloud.githubusercontent.com/assets/7233112/11274338/4b777768-8ea6-11e5-87ab-0cac9d652923.png)

Is this going to live somewhere else or just left out for right now? 

There is a <TimezoneDropdown /> component that will facilitate adding this field to the settings screen

**Comment by lancewillett** [comment]
I think this deserves being considered a user suggestion as an enhancement to make Calypso work like wp-admin.

**Comment by rachelmcr** [comment]
The timezone setting was added in https://github.com/Automattic/wp-calypso/pull/4226. Closing as resolved.
