### ISSUE TITLE
Masterbar: "Log Out" button is cut off in JA/HE

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#1783]
The "Log Out" button doesn't have enough width to fit translated labels. So far, I've spotted issues in these two languages.

Japanese:
<img width="337" alt="logout-ja" src="https://cloud.githubusercontent.com/assets/34067/11890470/28742f82-a598-11e5-9c46-84fd1007445a.png">

Hebrew:
<img width="263" alt="logout-he" src="https://cloud.githubusercontent.com/assets/34067/11890471/28b26900-a598-11e5-8682-35fd548edfc6.png">

It's in the dropdown which shows up when I click my Gravatar on any sites.

Adding 10px to the width of the button fixes this for Japanese, while in Hebrew the button needs to be 145px wide to contain the current translation.

**Comment by lancewillett** [comment]
I moved this to WordPress.com bug tracker since the code isn't in Calypso — it's a WordPress.com admin bar plugin.

**Comment by lancewillett** [comment]
Layout is now fixed in WP.com toolbar UI.
