### ISSUE TITLE
Update account-recovery validate to use wpcom-http

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17832]
`handleValidateRequest` in `client/state/data-layer/wpcom/account-recovery/validate/index.js` uses wpcom directly instead of using wpcom-http.

Let's rewrite this using dispatchRequest and http. 

```
import { dispatchRequest } from 'state/data-layer/wpcom-http/utils';
import { http } from 'state/data-layer/wpcom-http/actions';
```

For quick debugging, we can trigger a request from console directly with:
```
dispatch( { type: 'ACCOUNT_RECOVERY_RESET_VALIDATE_REQUEST' } );
```

**Comment by nosolosw** [comment]
PR https://github.com/Automattic/wp-calypso/issues/17832 address this issue.
