### ISSUE TITLE
WordAds : Include newly released JP ad settings in /ads

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#17843]
Jetpack 5.3 just released with finer control on where WordAds appear. 

The settings on Jetpack look like this 

![image](https://user-images.githubusercontent.com/4162931/30098531-edf40628-92ff-11e7-8da7-b4318709966e.png)

Can these settings be replicated within Calypso Ad settings for WordPress.com websites? 

These settings are accessible at the moment for WordPress.com Business Sites from WP-Admin.

**Comment by cpapazoglou** [comment]
Done in https://wordpress.com/earn/ads-settings 
![CleanShot 2023-07-20 at 16 53 37@2x](https://github.com/Automattic/wp-calypso/assets/12430020/f0f400e0-743a-417f-bd99-4febbab0b3f3)
