### ISSUE TITLE
Canceling Jetpack plan without a domain shows poor error message

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#17859]
#### Steps to reproduce
1. Create/connect a Jetpack site with a non-Free plan, but no domain name
1. Open https://wordpress.com/me/purchases
2. Select the Jetpack site and Remove the plan
3. Respond to the exit questions

#### What I expected
An accurate representation of my site

#### What happened instead
The site in question has no domain name, but the message reads `The domain associated with this plan, disconnected, will not be removed. `

#### Browser / OS version
Seen here in Linux Chrome

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/7233112/30122795-c949835e-92fd-11e7-971a-eaf54d1f0b7d.png)

#### Context / Source
#manual-testing

**Comment by gwwar** [comment]
I wasn't able to reproduce this for Jetpack or a wpcom plan. Reopen this issue if folks see otherwise, internally we check an `includedDomain` prop off of the purchase object.
