### ISSUE TITLE
Editor: reduce confusion by hiding Write button in navigation when you're in the editor

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#17887]
Props @johnmaeda for this idea.

#### Steps to reproduce
1. Go to wordpress.com
2. Click "Write" at the top right of the navigation bar.
3. You'll end up on a URL such as https://wordpress.com/post/example.wordpress.com

#### Description
I'd expected to not see the competing **Write** action when I'm already writing!

It's also very close to the **Update/Publish** button, which can be confusing. Do I click **Write** when I'm done?

#### Screenshot / Video
<img width="1278" alt="screen_shot_2017-09-06_at_17_10_57" src="https://user-images.githubusercontent.com/66797/30140121-26016c46-9327-11e7-80ab-2579e919b3c0.png">

#### Context / Source
#context #empathy #perspective

Found via #user-report and #reallife "wine tasting."

**Comment by lsinger** [comment]
I like this idea. 

But then again, UIs that adjust themselves magically to the current context can also come across as confusing or inconsistent. 

To take it to the extreme: when someone is currently writing — that is, actually typing — we could hide everything except the text area. 

Maybe an alternative is to fade the button — and maybe other things as well? — into the background a bit. Make things lighter or darker or ... something else? 

In any case, I think hiding a button that is always there *could* be more confusing than helpful.

**Comment by lancewillett** [comment]
I like the idea of changing the button state to "Active" like when you click it, it goes grayscale or opaque a bit so it doesn't look clickable. When making the help videos recently JM commented he made a big red X through the button because people were confusing it with the publish button.

**Comment by ianstewart** [comment]
+1 to the idea of trying to do _a thing_ to the button rather than hiding it for the same reasons Leif is suggesting.

**Comment by shaunandrews** [comment]
> I like the idea of changing the button state to "Active" like when you click it, it goes grayscale or opaque a bit so it doesn't look clickable.

This is actually the intention behind the current design — the dark blue is the calypso masterbar's active state.

<img width="256" alt="screen shot 2017-09-08 at 11 37 31 am" src="https://user-images.githubusercontent.com/191598/30219476-207a52ce-948a-11e7-9aae-76109ddc1851.png">

> people were confusing it with the publish button

That seems like the root problem. And the Masterbar's dark-blue active state isn't helping.

We could try fading the button, but its not great:

<img width="464" alt="screen shot 2017-09-08 at 11 42 54 am" src="https://user-images.githubusercontent.com/191598/30219696-df533c88-948a-11e7-9fcb-81ee2746a49d.png">

Hiding the button is weird, but it does help keep the emphasis on the Publish/Update button:

<img width="429" alt="screen shot 2017-09-08 at 11 43 53 am" src="https://user-images.githubusercontent.com/191598/30219745-03f4bf80-948b-11e7-86fc-9914e43cee05.png">

We could replace the button with some other useful link or information, like drafts or saved status:

<img width="475" alt="screen shot 2017-09-08 at 11 42 11 am" src="https://user-images.githubusercontent.com/191598/30219789-26218a5c-948b-11e7-9d31-d2d6cf8d5f25.png">

Its also worth considering how this affects things on mobile. Removing the write button is going to look strange:

<img width="423" alt="screen shot 2017-09-08 at 11 46 00 am" src="https://user-images.githubusercontent.com/191598/30219857-5e8c93c8-948b-11e7-9fea-d0f4b9dc43a0.png">
<img width="407" alt="screen shot 2017-09-08 at 11 46 58 am" src="https://user-images.githubusercontent.com/191598/30219882-79365808-948b-11e7-904e-f20b175d0339.png">

**Comment by shaunandrews** [comment]
![write copy](https://user-images.githubusercontent.com/191598/31775856-ca6804aa-b4b7-11e7-9957-5fe23d027143.png)

We could also ditch the masterbar when writing.

**Comment by lsinger** [comment]
> We could also ditch the masterbar when writing.

I love that. 

The sidebar, too?

**Comment by nylen** [comment]
This was fixed in https://github.com/Automattic/wp-calypso/pull/20326.
