### ISSUE TITLE
Editor: cannot add categories with different case or at different levels if the category name already exists

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1788]
Steps to reproduce:

1. Start a new post at https://wordpress.com/post
1. Expand "Categories & Tags" in the sidebar
1. Click the "Add a New Category" button
1. Try to add a duplicate category with a different case (i.e. all caps)
1. Try to add a duplicate category as a subcategory two levels deep or to a different parent category

<strong>Result:</strong> I was unable to add the same category with a different case or the same category again as long as it's a subcategory of something else ([42s](https://cloudup.com/cOD4emLgK-X)). Category validation in wp-admin allows both scenarios and just appends `-n` to the tail of the slugs.

![screen shot 2015-12-18 at fri dec 18 7 59 47 am](https://cloud.githubusercontent.com/assets/1119271/11897404/74914ff2-a55d-11e5-9e61-7cab0fdc9b99.png)
<sup>Tested in Firefox 42.0 on Mac OS X 10.10.5</sup>

**Comment by youknowriad** [comment]
This was closed in this PR for the category/subcategory part of the bug https://github.com/Automattic/wp-calypso/pull/6752

About the case issue, I checked and both WPAdmin and Calypso are case insensitive. I think we should close this issue

**Comment by timmyc** [comment]
I also just tested this out and was able to add a new child category with the same name - support has changed since we redux-ed the terms in the editor
