### ISSUE TITLE
Make Card Bylines font-weight 500

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17882]
As discussed, let's try making Card bylines font-weight 500 (they're currently "normal"). This is to make them a little more visually apparent, as well as match the way we treat names in comments.

<img width="818" alt="screen shot 2017-09-06 at 3 00 07 pm" src="https://user-images.githubusercontent.com/24388/30136499-1d6c6620-9314-11e7-8d61-35ded5407fb2.png">

**Comment by jancavan** [comment]
@fraying I took care of this in: https://github.com/Automattic/wp-calypso/pull/17881

**Comment by fraying** [comment]
Woot!
