### ISSUE TITLE
Post Schedule Calendar: not indicating future scheduled posts

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#17888]
An investigation/question task:

**Is the following behaviour a regression or are the docs out of date?**

According to the [_Schedule a Post_ documentation](https://en.support.wordpress.com/schedule-a-post/):

> When looking at the calendar, the currently selected date will be indicated with a blue dot, and today’s date will have an orange circle around it.
> 
> Dates when other posts are already scheduled to be published are indicated with a light blue outline. You can move your cursor over these dates to see what post(s) are scheduled for that day.

#### Steps to reproduce
1. Create several new posts to be published in the near future
2. Create a new post
3. Open the schedule post calendar

#### What I expected
Posts scheduled to be published in step 1 above should be indicated by a light blue outline, as per the documentation, and mousing over these dates should reveal the scheduled post's information. 

![screen-shot-2015-11-11-at-10-28-04-am](https://user-images.githubusercontent.com/6458278/30140459-29b429e6-93b8-11e7-9b25-7c054959323f.png)

#### What happened instead
The scheduled post date and mouseover information are missing.
<img width="1332" alt="screen shot 2017-09-07 at 10 23 47" src="https://user-images.githubusercontent.com/6458278/30140465-2e9cda0c-93b8-11e7-8a51-9eae97ec8fe8.png">

#### Side notes

[PostSchedule](https://github.com/Automattic/wp-calypso/tree/master/client/components/post-schedule) takes an `events` prop<Array>. Looks like this isn't being passed down (?)

#user-report #manual-testing

**Comment by alisterscott** [comment]
@mjuhasz is this a possible regression/oversight with the new publish confirmation?

**Comment by nylen** [comment]
This should be fixed in https://github.com/Automattic/wp-calypso/pull/17892.
