### ISSUE TITLE
Question: The site won't run after "npm start"

### ISSUE THREAD

**Issue by aistosi** [Automattic/wp-calypso#17891]
Hi,

After cloning the repo and following instructions in contributing file, I get "This site can't be reached",  when going to http://calypso.localhost:3000/

In my console after running "npm start" the build crashes with the log info in the attached file.
[npm-debug.txt](https://github.com/Automattic/wp-calypso/files/1283247/npm-debug.txt)

Any suggestions how to proceed further?

**Comment by alisterscott** [comment]
Can you please try:

`npm run distclean`

then

`npm run dashboard`

**Comment by designsimply** [comment]
Closing since there has been no reply after a proposed solution was posted.
