### ISSUE TITLE
Domains: Ask if user wants to create a new site if current site already has a domain

### ISSUE THREAD

**Issue by amylaneio** [Automattic/wp-calypso#17895]
Users sometimes register a new domain name, when they meant to create a new site.

If a site already has a domain name on it, we should ask if they want to create a new site when they go to register another one.

If the user wants to create a new site, they should then be directed to the new site user flow.

If not, register the domain on the current site.

**Comment by klimeryk** [comment]
Thanks, @amylaneio, very interesting idea - cc @mikeshelton1503 for input. Maybe we could A/B test this? Ideally, the conversion rate should actually be the same (or hopefully slightly better?), the idea is to help with the confusion that domain = site. Alternatively, we could improve the UI to make that clearer (like stating it somewhere during the purchase flow explicitly that content of example.wordpress.com will now be shown at example.com or something like that).

**Comment by amylaneio** [comment]
Noting here that we already have a similar modal when you buy a domain directly through /domains, so we could re-use that (or at least part of it)

<img width="1411" alt="screen shot 2017-09-07 at 9 05 21 am" src="https://user-images.githubusercontent.com/6625952/30167419-f28b89de-93ab-11e7-92a1-ab874e643c2d.png">
