### ISSUE TITLE
Domains: Whois Update for .FR Organization Domains does not work

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#17890]
#### Steps to reproduce
1. Purchase a .FR domain, and choose "Organization" from the Organization/Individual checkbox
2. Check that you can see the domain on whois ( https://www.afnic.fr/en/products-and-services/services/whois/ or the command line `whois` ). This is usually immediate.
2. Update contact details for the domain. To avoid other potential issues, avoid first name, last name, organization name, or email.
3. Give the registry some time to update (I expect this will also be immediate when it works, but 24 hours is an upper bound for reasonable).
4 Check Whois again, note that the changes have not been applied.

#### Context / Source
I've done some preliminary investigation, and the change is successful on the backend, and the responses from the OpenSRS API show the changes, so it could be an issue on the backend.

I've contacted OpenSRS support about the problem, and that communication is ongoing.

**Comment by klimeryk** [comment]
Marking this as wontfix - we hope to migrate away from Tucows at some point.
