### ISSUE TITLE
Customizer not loading when SU'd

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#17913]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ (logged in as super admin)
2. SU as WordPress.com user (example username: lasegretariasumisura)
3. Go to My Site > Customize

#### What I expected

The Customizer to appear, which is what usually happens.

#### What happened instead

The Customizer doesn't load and an error message appears instead.

"Sorry, the customizing tools did not load correctly"

JS Console shows this error:

```
Refused to display 'https://segretariasumisura.wordpress.com/wp-admin/customize.php?return=https%3A%2F%2Fwpcalypso.wordpress.com%2Fstats%2Fday%2Fsegretariasumisura.com&calypso=true&calypsoOrigin=https%3A%2F%2Fwpcalypso.wordpress.com&frame-nonce=763463c113' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
vendor.2867b4f73d2054d27d5d.min.js:11
```

#### Browser / OS version

macOS Sierra 10.12.6
Chrome 60.0.3112.113
Safari 10.1.2
Firefox 55.0.3

#### Screenshot / Video

https://cloudup.com/cr3qeUYptDx

#### Context / Source

The Customizer has always worked for me when SU'd until today. Other HEs are reporting the same issue in Slack.

Found when working in this chat: `625220-hc`

**Comment by andreabadgley** [comment]
Also having this issue at the GM, as are @MindyPostoff and @katinthehatsite. Discussed [on Slack](https://a8c.slack.com/archives/C02FMH4G8/p1505144057000352) and are using WP Admin for now.

**Comment by carladoria** [comment]
It has also been reported by user at:

https://woothemes.zendesk.com/agent/tickets/679461

**Comment by mgalbritton** [comment]
Reported by user here as well 681210-zen

**Comment by carladoria** [comment]
reported here:  https://woothemes.zendesk.com/agent/tickets/689890

**Comment by nellofn** [comment]
Having this issue as well since today (Sep, 22th).

**Comment by mgalbritton** [comment]
Another report here: https://woothemes.zendesk.com/agent/tickets/686294

Error I see in the console: https://cloudup.com/cvd36fMOVG7

**Comment by rachelmcr** [comment]
Reported again by a support rotation (internal ref: p1506409846000146-slack-triage).

This should only affect us internally when using SU, not users. I'm not sure if the cases here that mention user reports are cases where we saw this error while working with the user or if the user actually had trouble with the customizer. If anyone encounters a user-facing customizer issue please open a separate issue for that or ping in Slack for help troubleshooting. Thanks!

**Comment by RealCarFax** [comment]
My trial buddies reported this issue on picturesofinfinity.net as well. We received the error "Sorry, the customizing tools did not load correctly" after waiting a while for it to load.

**Comment by RealCarFax** [comment]
Reported here as well: 698009-zen
We see the error "Sorry, the customizing tools did not load correctly"

**Comment by gemmagarner** [comment]
"Sorry, the customizing tools did not load correctly"

879524-f

**Comment by lancewillett** [comment]
Closing per notes above that this is internal-facing only.

CC @apeatling for the use case of a11ns super-user switching into different Calypso users, for support reasons (a current or upcoming Triton team focus).
