### ISSUE TITLE
Post Editor: Keep screen scroll position when switching between Visual and HTML modes.

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#17914]
With the merge of #17481 we will have a more consistent cursor persistency between the Visual and HTML modes. 

Right now we have to scroll to the top of the page, switch and then scroll back down manually, to find where we were. 

As referenced in [this comment](https://github.com/Automattic/wp-calypso/issues/8592#issuecomment-283343204) on #8592, we will have a much better and consistent experience if we offered switching between the two modes, without having to lose the context of the current thing we're looking at.

The best way to do that will be to pin the mode toggling buttons to a fixed position in the page.

Unfortunately that won't work out of the box, since the scroll position is not saved when switching between the modes. Only the selection is.

In order to be able to pin the buttons and offer a more consistent experience, we have to properly translate the scroll position between the modes. This is already partly done with the selection transfer, but will require a bit more work, since there will definitely be some edge cases that will confuse the position when switching.

**Comment by dcoleonline** [comment]
Also requested in wordpress.com support ticket 818315-zen

**Comment by rachelmcr** [comment]
Also reported here: https://github.com/Automattic/wp-calypso/issues/22761

**Comment by alisterscott** [comment]
Related #25861
