### ISSUE TITLE
Store: No Taxes - Tax Column Should Be Hidden

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#17911]
Somewhat related to #17910 - On Stores that either have the setting for "Taxes are included in Product Prices" checked "on" or, in my case, you live in a locale where no sales tax is collected and TaxJar says: "Since your store is located in Oregon, USA you're not required to collect sales tax." should we consider hiding all tax-related UI in the store admin?

It appears that in core the tax bits are hidden when no tax is collected:

![edit_order_ _care_for_animals_ _wordpress](https://user-images.githubusercontent.com/22080/30174356-a8c412ae-93af-11e7-97ce-2dac5a56c837.png)

**Comment by ryelle** [comment]
Can you screenshot an order in Calypso where you see the tax column? We should be hiding it in the totals section already.

**Comment by timmyc** [comment]
Sure thing:

![order_details_ _care_for_animals_ _wordpress_com](https://user-images.githubusercontent.com/22080/30174843-411309d8-93b1-11e7-9f10-1ab1976ec590.png)

**Comment by ryelle** [comment]
Fixed in #22019
