### ISSUE TITLE
Editor: "Saving of draft failed" when an edit toolbar button is clicked and text is not entered immediately

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1792]
Raised by @alisterscott 

What I did: opened a new calypso editor. Clicked the bold icon.

What happened: a few seconds after a message displays in red: Saving of draft failed. (no errors in console)

What I expect to happen: nothing, as I haven't entered any content (yet)

Screencast: 
![saving post failed without content](https://cloud.githubusercontent.com/assets/128826/10989887/b6e0a708-8498-11e5-9e2c-2e0dbb421991.gif)

Notes from @kriskarkoski 

> I can repro this (Chrome 46, OS X 10.11). Looks like the issue is it's inserting the bold tags so if you start typing the text would be bold, but autosave fails if you don't add text in time. Toggling to HTML clears the tags since they're empty so the error doesn't appear if you do that before the autosave happens.
> 
> I wonder if #1019 will solve this issue and others with auto save failing when content is missing (9584-gh-calypso-pre-oss is similar but with image removal)

**Comment by rachelmcr** [comment]
Closing as this issue does not occur in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
