### ISSUE TITLE
Editor: Investigate restoring `AsyncLoad` to `PostSchedule`

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#17924]
PRs related to the publish confirmation sidebar (culminating in https://github.com/Automattic/wp-calypso/pull/17655) effectively removed the `AsyncLoad` behavior from the `PostSchedule` component in the editor.

This usage of `AsyncLoad` was originally introduced in #9112 and we should consider bringing it back.  However, things have changed since then, both in terms of code structure and usage patterns, so first we should re-evaluate the chunk size savings and whether the loading delay is worth it / causes any issues.

See also related PR and discussion at https://github.com/Automattic/wp-calypso/pull/17892#discussion_r137638310.

**Comment by alisterscott** [comment]
@nylen any more thoughts on this? Do we still need it?

#bug-scrub #pre-gutenburg-bug-purge
