### ISSUE TITLE
Calypso: Editor can't switch to HTML in Safari

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#17930]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/carissastrial.com/4151
2. Click on HTML tab at the top right-corner of the editor for the page.

#### What I expected
When you click the HTML tab, the editor switches to the HTML view of the page or post.

#### What happened instead
It no longer responds to a click. It seems like this has been a very recent development, perhaps in the last day or two.

#### Browser / OS version
Safari Version 10.1.2 (12603.3.8)

#### Screenshot / Video
Hard to demonstrate the lack of response, but here's an attempt: https://cloudup.com/cD0VwYTATRF

#### Context / Source
@ashercantrell and Kateryna Kodonenko reported this issue in the livechat Slack channel, due to #user-report. Both of their users reported the issue with Safari specifically. I was able to replicate the issue in Safari with an additional bit of additional information - when I first entered the page editor, I was in HTML view already. I immediately switched to the Visual view, added some filler text, then I could not switch back to HTML.

**Comment by lancewillett** [comment]
Confirmed with Safari 10.1.2 on OS X 10.12.6

JS error in console:
`Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) https://wpcalypso.wordpress.com/calypso/keys.js.map`

<img width="1302" alt="screen shot 2017-09-07 at 15 49 14" src="https://user-images.githubusercontent.com/66797/30188606-1eaeff72-93e4-11e7-8181-deb96030a5fa.png">

<img width="978" alt="screen shot 2017-09-07 at 15 49 08" src="https://user-images.githubusercontent.com/66797/30188618-291aeb2e-93e4-11e7-9055-552f03fd8f63.png">

**Comment by lancewillett** [comment]
Related change possibly: https://github.com/Automattic/wp-calypso/pull/17481

**Comment by lancewillett** [comment]
This should be fixed now @RealCarFax @ashercantrell Kateryna Kodonenko.

Thanks for the bug report.
