### ISSUE TITLE
Domains: Third Level Domains handled incorrectly

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#17946]
#### Steps to reproduce
1. Click on add new Domains -> Add
2. Enter a third level domain name ( e.g. foo.gen.in or bar.com.au )
3. We don't offer any third level domains yet, so we correctly get a "not offered" warning
4. Notice that the warning only mentions the tld, and not the subdomain.

![domain_search_ _julesauspremiumtest_ _wordpress_com](https://user-images.githubusercontent.com/5952255/30213887-d85f09b2-94ed-11e7-87d3-21fc94e4f5e0.jpg)

We're getting the TLD through https://github.com/Automattic/wp-calypso/blob/621df1993e120073e424850ed7174cd5ceace55a/client/lib/domains/index.js#L139 which just looks at the last `.`, and it's only used in a handful of places across `client/domains` and `client/signup`.

**Comment by klimeryk** [comment]
That's a known issue. It was written this way, because it was easier this way and we did not offer any second or third level TLDs that we did not offer as first level TLDs (so, like offering `co.uk`, but not offering `uk`). I'm guessing this will become an issue for `in`?

**Comment by deBhal** [comment]
Yeah, `.in` offers several third level domains that we might want to offer.

Where are we at with subdomains? It seems like whitelisting supported third-level domains is a better option than just taking the first dot.

**Comment by klimeryk** [comment]
> Where are we at with subdomains?

In what regard? We support mapping blogs to subdomains.

> It seems like whitelisting supported third-level domains is a better option than just taking the first dot.

I'd rather not introduce a list on the frontend that needs to be maintained separately from the backend. If we need to go this route (and we probably need to at this point), let's just get the correct TLD from the backend.
