### ISSUE TITLE
Comments management: email notifications still point to wp-admin

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#17949]
When getting a new email notification for comment, pingback or trackback that requires your review, all of the action links (Approve, Trash, Mark as Spam) are still pointing to wp-admin.

![emailnotif](https://user-images.githubusercontent.com/1182160/30215158-452dd652-94af-11e7-99c7-4f259d6c3c72.png)

**Comment by Copons** [comment]
Assigned to @rodrigoi for his work on #19635

**Comment by rodrigoi** [comment]
closed in favor of #19774.
