### ISSUE TITLE
Plugins: Update disabled autoupdates UI

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#17941]
If autoupdates is disabled we should use the disabled toggle that's precisely what it is for. 

I personally think that we should add little more opacity to the disabled state, but I think that should be tackled in a separate PR.

<img width="749" alt="screen shot 2017-09-08 at 09 27 07" src="https://user-images.githubusercontent.com/908665/30202887-eaa855f4-9477-11e7-8a6f-cb2d8389a55d.png">

**Comment by jsnajdr** [comment]
> I personally think that we should add little more opacity to the disabled state, but I think that should be tackled in a separate PR.

@iamtakashi "more opacity" means making the text "Autoupdates" more black, or more white? Right now, it has such a light shade of grey that it's almost unreadable on a white background.

**Comment by iamtakashi** [comment]
Sorry, I meant higher value for the opacity, which means more darker in this case because it's currently almost unreadable as you said.
