### ISSUE TITLE
Reader Conversations: instantly expand newly posted comments

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#17957]
As @jancavan discovered:

> when I leave a top-level comment, nothing happens. My comment doesn't show up until after a refresh. I can see that it's being added to the caterpillar, but shouldn't that just show up immediately? 
Video: https://cloudup.com/c3OCR7qKgnx

This PR can be closed when we are auto-expanding newly added comments.

**Comment by samouri** [comment]
This actually isn't straightfoward because we are using the data-layer to create a new comment. the added commentId isn't available to Calypso so it cannot dispatch an action to expand the just-added-comment.

cc @dmsnell are there any workarounds that I don't know about?

**Comment by dmsnell** [comment]
cc: @rodrigoi and @copons as the comment should be available with a temporary id that gets automatically replaced when the new comment comes back from the server

**Comment by samouri** [comment]
the behavior i want is something along the lines of

```js
createNewComment()
  .then( id => {
    dispatchActionThatNeedsTheId( id );
  } )
```

**Comment by Copons** [comment]
Yeah, that's pretty much as @dmsnell says.

When we write a comment, the [data layer function](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/comments/index.js#L84) creates a [placeholder](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/comments/index.js#L84) in state with these identifier properties:
```js
{
  ID: 'placeholder-' + new Date().getTime(),
  post: { ID: postId },
  ...
}
```

Then, on success we should delete the placeholder (but apparently the `COMMENTS_DELETE` action is never dispatched? Nothing calls this [function](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/comments/index.js#L142)...) and then [add the new comment](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/comments/index.js#L118), as returned in the API response, to the state.

FYI: [replies should delete the placeholder](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/sites/comments/replies/new/index.js#L8).

In Comment Management, we have the comment tree that is updated on new comments / new replies, so they automatically appear in our list.

**Comment by Copons** [comment]
> the behavior i want is something along the lines of

@samouri you may want to incept this on success handlers: https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/comments/index.js#L118

**Comment by dmsnell** [comment]
@samouri @Copons and @rodrigoi when we think we need a sequential asynchronous process, check with the work @coderkevin has done with the [action list](https://github.com/Automattic/wp-calypso/blob/master/client/extensions/woocommerce/state/data-layer/action-list/index.js) (and don't forget to ask for a walkthrough-style README as I didn't see one! :wink:)
