### ISSUE TITLE
Editor: paragraph dropdown has scrollbar on Chrome

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1795]
Raised by @folletto 

![screen shot 2015-11-06 at 12 06 35](https://cloud.githubusercontent.com/assets/4389/10997761/925b97d2-8487-11e5-9374-88a43f9b08a5.png)

* Chrome Mac 46.0.2490.80 (64-bit)
* Doesn't happen on Safari / Firefox
* Make sure you have scrollbars visible (System Preferences > General > Show scroll bars > Always)

Also see 11824-gh-calypso-pre-oss

**Comment by youknowriad** [comment]
Seems good for me Chrome Mac Version 53.0.2785.116 (64-bit)

**Comment by folletto** [comment]
Can you double check? I see it still present on Chrome Mac 53.0.2785.143 (64-bit):

![cap-](https://cloud.githubusercontent.com/assets/4389/19080598/7582a50a-8a4f-11e6-9d7d-6e69a8a48927.gif)

**Comment by youknowriad** [comment]
What I did not see is scrollbars on the dropdown (as shown on the initial screenshot). This may be another scrolling bug.

**Comment by folletto** [comment]
Ah yes, sorry. I had the other issue in mind and I thought it was that one.

You're right, this is fixed.

I opened a separate issue for the other: #8479.
