### ISSUE TITLE
Posts: Scheduled posts are listed in reverse chronological order

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#17953]
Scheduled posts are listed in reverse chronological order (with the post that's scheduled furthest out appearing first). This isn't that convenient for site owners who want to review their upcoming scheduled posts first in the list. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/my/
2. Schedule multiple new posts for various dates in the future.
3. Navigate to the Scheduled tab to view your posts: https://wordpress.com/posts/my/scheduled/

#### What I expected

I expected the scheduled posts to be ordered chronologically, with the post that's to be published soonest at the top. This would make it more convenient and easier to review the posts that are going to be published sooner.

#### What happened instead

The scheduled posts were ordered in reverse chronological order, with the post that's scheduled to be published furthest out appearing at the top of the list.

#### Screenshot / Video

<img width="755" alt="screen shot 2017-09-08 at 16 11 22" src="https://user-images.githubusercontent.com/2998162/30218235-6b55071e-94b0-11e7-91b7-4ec3f54382a7.png">

#### Context / Source

Reported in 183773-hc and following up in 673144-z.

#perspective #perspective #user-report

**Comment by alisterscott** [comment]
I can confirm this is still an issue.

**Comment by mattsherman** [comment]
@Automattic/tanooki will look into this.
