### ISSUE TITLE
Conversations: Suppress "comments closed" notice

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#17955]
<img width="849" alt="screenshot 2017-09-08 11 36 10" src="https://user-images.githubusercontent.com/14350/30219451-0d233402-948a-11e7-91e0-c582d9840851.png">

We should suppress the "comments closed" notice on posts with closed comments.

Post in question: https://dailypost.wordpress.com/2017/07/24/fragrance/

Seen on https://wpcalypso.wordpress.com/read/conversations

**Comment by fraying** [comment]
I'm not sure I agree with this. Every other post will have a comment form at the end. It'd be weird if some posts had no comment forms but didn't say why.
