### ISSUE TITLE
Store: Shipping settings: TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#17963]
#### Steps to reproduce
1. Navigate to http://calypso.localhost:3000/store/settings/shipping/{domain}
2. Open dev console
3. Note the errors (two of them)

Poking in the stack trace suggests an exception in label handling.

**Comment by timmyc** [comment]
I haven't been able to reproduce this issue myself.

**Comment by timmyc** [comment]
![shipping_settings_ _trout_bummin_ _wordpress_com](https://user-images.githubusercontent.com/22080/31564183-c38fadea-b016-11e7-9f1a-2efee27cb4b7.png)

Actually just was able to get it on a new site. No shipping setup, then navigated to settings | shipping
