### ISSUE TITLE
Store - Promotions: Add "enabled" property to Coupons API

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#17967]
Right now, Coupons can be set to private/public in WooCommerce and they are effectively disabled when set to private. However, none of this functionality is visible to the API. The following needs to be done to add it:

1. Add "enabled" to the Coupons DataSource (linking to private/public in the default implementation)
2. Add "enabled" to the Coupons API within `wc-dev-api`
3. Test with new Store Promotions code.

**Comment by justinshreve** [comment]
I think you'll have to make the two changes separately, unless we figure out a way to start shipping the datastores with `wc-api-dev`. I don't think that's necessary for this change though.

I would focus on the `wc-api-dev` change first, updating the status directly with existing WC/WP functions, and add a TODO comment to use proper datastore methods. Then open an issue for the datastore methods in core. 

The important thing IMO is that the data-store methods are used before the endpoints are merged into core, so I think we have some time. In the meantime, I think it's OK to do it this way in our dev plugin, and it won't block promotions.

**Comment by coderkevin** [comment]
I think that sounds reasonable. I'm fine with directly coding it in as long as it doesn't make it into core that way. I'll make sure to comment it prominently.

**Comment by coderkevin** [comment]
Moving this off the v1.1 release as product sales can't be disabled either. So it doesn't make sense to implement this for one and not the other.

Most likely this would be best to do in a proper Promotions API.

**Comment by coderkevin** [comment]
Closing this, since it will be a while before we work on this code again. Hopefully we will have a proper promotions API when we do.
