### ISSUE TITLE
Analytics: block HotJar when PII is detected just like all the other 3rd party scripts

### ISSUE THREAD

**Issue by MicBosi** [Automattic/wp-calypso#17971]
We currently block third party tracking when potential PII (personally identifiable information) is detected on the URL. We need to do the same for HotJar.

Reference:
- `isPiiUrl()`: https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=isPiiUrl&type=

**Comment by jsnmoon** [comment]
I'll tackle this this week.
