### ISSUE TITLE
Editor: pre tag removed, div tag converted after publishing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1797]
Raised by @gwwar 

Published posts incorrectly decodes html entities. To reproduce:
1. Navigate to https://wordpress.com/post
2. Choose a blog
3. Start a new post
4. Type: `<div>Hello World!</div>`
5. Apply preformatted styling
6. Publish Post

Expected: Post Displays as show in visual preview
<img width="693" alt="screen shot 2015-11-06 at 4 08 45 pm" src="https://cloud.githubusercontent.com/assets/1270189/11011797/d42d6ce4-84a0-11e5-8635-e3cb29643574.png">
Actual:
<img width="796" alt="screen shot 2015-11-06 at 4 07 51 pm" src="https://cloud.githubusercontent.com/assets/1270189/11011836/2b82a52c-84a1-11e5-9eca-a682a84220d8.png">

Editing the post again (with a refresh shows the following):
<img width="699" alt="screen shot 2015-11-06 at 4 09 03 pm" src="https://cloud.githubusercontent.com/assets/1270189/11011841/38f2983e-84a1-11e5-87b1-e74b3e564db2.png">

Notes from @kriskarkoski 

> This matches the behavior of WP Admin as it is now, but it's not a great experience. 
> 
> Here's the HTML view pre-publish:
> 
> ![screen shot 2015-11-11 at 11 07 50 am](https://cloud.githubusercontent.com/assets/1900444/11095752/8f62c4b6-8864-11e5-8a55-254bec43e906.png)
> 
> After publishing the pre had been stripped and the div converted:
> 
> ![screen shot 2015-11-11 at 11 08 10 am](https://cloud.githubusercontent.com/assets/1900444/11095768/9f541618-8864-11e5-8549-988d96fe3d55.png)

**Comment by nitrajka** [comment]
Hi, 

I noticed this happens also when switching between modes - visual and html.

1. start new post
2. write `<div>hello world!</div>` in visual mode
3. switch to the html mode - at this point, user probably expects the `<div>` to be wrapped in `<code>`, but it's not. It's just ordinary `<div>` tag in html mode.
4. switch to the visual mode- user expects to see the `<div>`, but he sees only the text 'hello world'


I suggest, in [`switchEditorMode`](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/post-editor.jsx#L987) function, in the first `if` we could "prevent code injection" and wrap every tag (with it's closing tag) in `<code>`. 

Or we could add a `code` button also to the visual editor.

Or just inform the user, that if he wants to paste some code to the editor, he has to switch to the html mode. And wrap his code there to the `<code>`.

**Comment by spen** [comment]
Related: #18203

**Comment by alisterscott** [comment]
Confirming this is still an issue with the editor:

<img width="820" alt="screen shot 2018-02-13 at 3 50 57 pm" src="https://user-images.githubusercontent.com/128826/36135252-b34c9c34-10d5-11e8-8f76-6806c45e9bff.png">

#bug-scrub #pre-gutenburg-bug-purge

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
