### ISSUE TITLE
Full Screen option not working for Google Slide embeds

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#17998]
#### Steps to reproduce
1. Starting at URL: https://freetest7496.wordpress.com/testing-google-slide-embed/
2. Create and publish a Google Slide.
3. Within Google Slides, go to File > Publish To Web > Embed. Click Publish and copy the iframe code.
4. Paste the iframe into the HTML tab on a WordPress.com page or post.
5. Publish or update the page or post.
6. View the published page/post and click the full screen toggle at the bottom of the Google Slide embed.

#### What I expected
WordPress.com to convert the iframe into a shortcode with the original parameters. Clicking the full screen toggle to open the slide in a full screen.

#### What happened instead
WordPress.com removed the fullscreen parameters from the iframe when creating the shortcode. Adding the fullscreen parameters back into the shortcode has no effect. Clicking the full screen toggle has no effect. The slide remains embedded and does not open in full screen.

#### Browser / OS version
macOS Sierra 10.12.6
Chrome 61.0.3163.79
Safari 10.1.2

#### Screenshot / Video
original iframe: https://cloudup.com/cy82t3JiFiJ
shortcode created from iframe: https://cloudup.com/cd_tMLn0jIt

#### Context / Source
Users have reported this in several tickets, and I have been able to reproduce it on several test sites with a variety of themes. #user-report

**Comment by alisterscott** [comment]
This is a WordPress.com behaviour not specifically to do with Calypso as the same behaviour happens when publishing from wp-admin.

@juliaamosova would you mind please raising this in WP.com Trac? Thanks

**Comment by juliaamosova** [comment]
@juliasydnor sorry for the late ping but wanted to make sure you saw this. I think I was pinged by Alister by mistake (see his comment of December 20, 2017).
