### ISSUE TITLE
VideoPress: cannot see videos uploaded to a Jetpack site in the WordPress.com media modal if VideoPress is enabled

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1799]
Raised by @ebinnion 

I went to wp-admin of my WordPress.com site to upload videos. Videos uploaded fine, and I verified that I could view the videos on my Jetpack site.

![11958](https://cloud.githubusercontent.com/assets/1119271/11898198/13017a08-a564-11e5-943d-a4f6c9cf3d49.png)

But, when I went back to the Calypso editor, I could not see the new videos in the editor. Note the difference in number between the above screenshot and the one below.

![screen shot](https://cloud.githubusercontent.com/assets/1126811/11042634/e61565da-86dd-11e5-98a9-997443f18efc.png)

This persisted even after `localStorage.clear()`.

Note from @aduth 

> @ebinnion : After some time has passed, are you still observing that the videos have not yet appeared in the modal? I'm curious whether this is an issue with the REST API media endpoints not returning new VideoPress uploads until after they have synced or been processed.

Reply from @ebinnion 

> I still do not see the videos. I think this may be because VideoPress videos are actually stored on the WordPress.com site as opposed to the Jetpack connected site. The test videos I uploaded yesterday to manofhustle.com are not in my media library on manofhustle.wordpress.com.
> 
> Here are some docs from the Jetpack.me site that describe how to use VideoPress:
> 
> > To upload a video to your VideoPress Library, go to your WordPress.com site and Media -> Add New. You can find more information about uploading videos here.
> > 
> > Once your videos are uploaded, go to your Jetpack site and start a new post or edit an existing post. Next, click “Add Media” then click the VideoPress tab on the left side of the Media Uploader window to view and select your uploaded videos.
> 
> I'm not sure how we fix this for now. Perhaps we could add a VideoPress tab to the media uploader that would allow uploading the video to the WordPress.com site (manofhustle.wordpress.com) site and selecting videos that are uploaded to the same site?
> 
> cc @beaulebens who should have more insight into VideoPress than I do.

Reply from @beaulebens 

> I think you're right @ebinnion, this is more of a problem with how VideoPress/Jetpack work, but it's going to be an issue in the Editor, unfortunately :(
> 
> Basically, if you're using VideoPress via Jetpack, your videos are stored on "some other" WordPress.com site. That means that when you go to write a post on that Jetpack site in Calypso, and we load up your media library, you're not seeing the video because it's genuinely not there (it's in the media library of some other WordPress.com site).
> 
> Short of having some additional tab, or figuring out which WordPress.com site you're linked to and merging the 2 media libraries (in the UI), I'm not sure that there's a short-term fix for this. This sort of gap/confusion is definitely something we'll be aiming to fix in the upcoming VideoPress team/rewrite though.

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue; VideoPress videos appear in the Calypso editor media library as expected.

#bug-scrub #pre-gutenburg-bug-purge
