### ISSUE TITLE
Editor: Setting featured image via URL for AT sites results in error.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#17994]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/ or https://wordpress.com/posts/
2. Add media -> Via URL. Enter in the URL of an image.
3. A file is created in the media library with the image filename, but no image is uploaded.
4. Trying to type in the URL of the new filename manually results in error "Multisite support not enabled".

#### What I expected
A copy of the image located at a URL being uploaded to the Media Library.

#### What happened instead
A filename is created, but no image is uploaded. 

#### Browser / OS version
Firefox 47 / Debian Stretch.
Chrome 61 / Debian Stretch
Chrome / OS X.13

#### Screenshot / Video

![selection_005](https://user-images.githubusercontent.com/10121835/30352557-66c07350-97d5-11e7-9c67-95bd1523d8a1.jpg)

#### Context / Source

#user-report 
#679050-zen

**Comment by rachelmcr** [comment]
Closing as a duplicate report.
