### ISSUE TITLE
Make Combined Card Bylines font-weight 500

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#17992]
In #17882 we made card bylines font-weight 500, but it looks like the card bylines for Combined Cards weren't included. 

<img width="277" alt="screen shot 2017-09-12 at 1 40 00 pm" src="https://user-images.githubusercontent.com/24388/30347224-36d2d8c8-97c0-11e7-8428-a9672102c11e.png">

To Do: Make Combined Card Bylines font-weight 500.

cc @jancavan

**Comment by samouri** [comment]
For posterity here is an example of what it looks like w/ font-weight: 500:
<img width="841" alt="screen shot 2017-09-13 at 3 30 50 pm" src="https://user-images.githubusercontent.com/4656974/30396739-9e1bf2ac-9898-11e7-8dfe-80bf55bc7107.png">
 

We didn't get site recs either, @fraying do you think we should also increase the font-weight there?
<img width="875" alt="screen shot 2017-09-13 at 3 30 44 pm" src="https://user-images.githubusercontent.com/4656974/30396755-ab0e2a84-9898-11e7-806c-4447f535c51d.png">

**Comment by fraying** [comment]
Yes! Good call, @samouri

**Comment by samouri** [comment]
for regular postcards the format of the byline is:
```
author, site
```

for recs the format is:
```
author
site
```

should the font-weight be 500 for both site and author?

**Comment by samouri** [comment]
answered over slack:

'Both'

**Comment by fraying** [comment]
Fixed now!
