### ISSUE TITLE
Jetpack Monitor: Use mapped domains on multisite

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#180]
When Monitor is activated on a multisite with mapped domains, the alert emails use the "base" URL, rather than the mapped domain. Ideally we'd use the mapped version everywhere we showed it to a user.

<img width="622" alt="8d0907de-5240-11e5-9efb-f9ad29ecadf1" src="https://cloud.githubusercontent.com/assets/11487924/11274525/44b3aa7c-8ea7-11e5-998e-6bc26008c7b2.png">

In this example, **originaldomain.mainsite.com** is mapped via **mappeddomain.com**.

**Comment by jeherve** [comment]
I wasn't able to reproduce the issue on my end. Mapped domains on Multisite appear to be displayed properly in my Monitor emails. Here is an example:

![screen shot 2016-04-28 at 5 47 18 pm](https://cloud.githubusercontent.com/assets/426388/14892042/726e9ecc-0d69-11e6-9570-c16b3e812c84.png)

That domain is mapped to a subdomain of the network admin, but this was handled by Jetpack.

In this happens again, I'd suggest trying to disconnect Jetpack from WordPress.com, and then reconnect it to force an update of the Jetpack options, and make sure the site URL is properly synchronized.
