### ISSUE TITLE
Signup: Improve email verification notice

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#1802]
Current email verification notice:
<img width="1397" alt="13cf7ba4-a4b2-11e5-99ca-37581f21d7e7" src="https://cloud.githubusercontent.com/assets/3011211/11898581/b2b9e79a-a54d-11e5-943c-c213dec11464.png">

Some suggestions by @rickybanister from https://github.com/Automattic/wp-calypso/pull/1748:

> That thing is pretty copy-heavy, could we try something more concise?
> 
> `Whoops you haven’t verified your email yet [Resend]`
> 
> And make use of the notice action instead of a notice link?
> 
> In the long run, since so many people see the email verification notice it might be nice to use something more custom and friendly than a notice. Being unverified doesn't feel like an error to me, just a part of life. Would be nice to see a graphic there, maybe in that @adambbecker style of a stylized email inbox or something.

**Comment by lancewillett** [comment]
Raised #2650 to address a similar problem: when you first post (before verifying the email address), the post looks like it's published, when it's actually just saved as a draft.

**Comment by lancewillett** [comment]
See also #5475 for related improvements.

**Comment by alisterscott** [comment]
This is has been addressed over various PRs and no longer looks like the above, so I am closing this issue.

For reference, current message on publish button:

<img width="288" alt="screen shot 2017-07-18 at 11 52 15 am" src="https://user-images.githubusercontent.com/128826/28297174-cd9042ce-6baf-11e7-92fc-068186eafa55.png">

And more details view:

<img width="558" alt="screen shot 2017-07-18 at 11 52 40 am" src="https://user-images.githubusercontent.com/128826/28297179-d2c86ad2-6baf-11e7-93c7-71db895ddf84.png">
