### ISSUE TITLE
Editor: horizontal scrollbar appears on gallery edit view

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1803]
Raised by @kriskarkoski 

A horizontal scrollbar is appearing on the Gallery Edit view when it's not necessary. This happens with any number of columns right before the breakpoint when the view drops to displaying a smaller number of columns. 

To repro, open the Gallery edit view in a wide browser window and slowly drag to make it smaller. You will see the scrollbar appear right before the number of columns changes. Chrome 46/OS X 10.11.1

![screen shot 2015-11-10 at 10 18 31 am](https://cloud.githubusercontent.com/assets/1900444/11066146/f63e748a-8794-11e5-83bd-d1ab12d92b4a.png)

**Comment by rachelmcr** [comment]
Closing for now as this is low priority/not causing any functional issues and doesn't have any user reports.

#bug-scrub #pre-gutenburg-bug-purge
