### ISSUE TITLE
Editor: Selection lost when selecting an image with caption in HTML mode and switching to Visual

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#18043]
#### Steps to reproduce
1. Open the editor
2. Insert an image
3. Add a caption to it
4. Go to HTML mode
5. Select the `<img>` tag
6. Switch to Visual mode

#### What I expected
The image to be selected within the caption.

#### What happened instead
The selection was reset to the beginning of the editor content.

#### Screenshot / Video
![selection-lost-for-captioned-image](https://user-images.githubusercontent.com/184938/30443128-60074156-9933-11e7-8e36-c4c763a1c52e.gif)

#### Context / Source
This issue is caused by how the `[caption]` transformation happens when switching to Visual mode. The parser code rewrites the whole content of the `[caption]` tag, which means the cursor marker `<span>` is removed from the markup, which confuses the selection keeping code.

The `[caption]` parser code can be [seen here](https://github.com/Automattic/wp-calypso/blob/dba0a052ecd7d10af4cf9096a0fe66db1baa25e0/client/components/tinymce/plugins/wpeditimage/plugin.js#L101).

Two possible ways to fix the issue:
* Add support for the cursor markup in the `[caption]` parser or make it a bit more smart, to not clear out the whole content of the `[caption]` shortcode. 
* When deciding where to put the selection marker, detect if it's between the `[caption]` and `<img/>` tags and move the cursor before the `[caption]` tag.

**Comment by rachelmcr** [comment]
I retested with the steps above and confirmed this is still an issue.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
