### ISSUE TITLE
Editor: preview button still shows even when no changes are made and post is published

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1804]
Raised by @v18 

Steps to reproduce:
1. Start a new draft post on a test site
2. Publish the post 

![publish-1](https://cloud.githubusercontent.com/assets/11487924/11096684/5ef96cda-8869-11e5-8af3-d4f21ea3673f.png)

![publish-2](https://cloud.githubusercontent.com/assets/11487924/11096682/5ef803ae-8869-11e5-88cc-9d95b55824d7.png)

![publish-3](https://cloud.githubusercontent.com/assets/11487924/11096683/5ef92676-8869-11e5-9c6f-8aac212830af.png)
1. View the post, and then go back to the editing page.
2. See the 'Preview' and 'Publish' buttons. I expected to see 'View' button instead of 'Preview' since the post is already published.

![view-1](https://cloud.githubusercontent.com/assets/11487924/11096725/8a1c6502-8869-11e5-9d60-ce61412c600e.png)

Note from @kriskarkoski 

> I believe this is intentional as preview lets you preview content you've added to the post before you click update to make it live. I guess we could disable the preview button when no changes have been made, or swap it out for a view label (but maybe still use the iframe preview) until a change is made then switch to the preview label.

**Comment by lancewillett** [comment]
Closing as wontfix.
