### ISSUE TITLE
Editor: Quickly switching between Visual and HTML mode shows garbled HTML

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#18042]
Reported by @alisterscott in #17481 , adding the original comment below:

>I do notice switching back to visual from HTML mode a chunk of HTML momentarily appears in the editor then disappears. This GIF shows it:
>
>![switch modes](https://user-images.githubusercontent.com/128826/30041094-65099100-922a-11e7-986f-0f4dbdc0d9aa.gif)
>
>This is a screen grab of the HTML:
>
><img width="742" alt="html shown" src="https://user-images.githubusercontent.com/128826/30041100-7c6c2966-922a-11e7-97cb-7201a8c68000.png">

The issue appears when the user has selected some text or focused the cursor and is switching quickly between the HTML and Visual modes in the editor.

The main cause behind the issue is that the editor relies on async actions to synchronize the content when switching between modes. This creates a short delay where the code that helps mark the current selection state stays visible in the HTML mode `textarea`. 

Marking the issue as Low priority, since it's a bit rare to actually trigger it.

**Comment by supernovia** [comment]
I've seen several cases of similar issues. Noting another case at 878546-f

**Comment by bisko** [comment]
@supernovia the issue you reported is related to #18203, quoting your report there :)

**Comment by rachelmcr** [comment]
Closing as this will be superseded by Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
