### ISSUE TITLE
Editor: padding is momentarily lost on switch from HTML to Visual

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1805]
Steps to reproduce:
- Start a new post and enter some text
- Switch to HTML mode
- Switch back to visual
- Observe that the top of the content is briefly flush with the top of the content area, then jumps down
- Repeat the above with the kitchen sink open
- Observe that the top of the content is briefly underneath the toolbar, then jumps down

Video: https://cloudup.com/cN5HxluXN5p

**Comment by youknowriad** [comment]
This seems already fixed for me or I'm not able to reproduce.

**Comment by nitrajka** [comment]
Agree with @youknowriad. Whoever can close this issue, do it, please.
