### ISSUE TITLE
Scheduling a post with preview looks like post published

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18067]
I was scheduling a post on one of our p2s when I panicked thinking it actually published due to being taken to the preview view and seeing the "Now" timestamp:

<img width="1234" alt="screen shot 2017-09-14 at 11 06 11 pm" src="https://user-images.githubusercontent.com/26996883/30468737-c34716ba-99a1-11e7-9eb2-f2348830a91f.png">

I'd recommend using preview for a scheduled post and/or changing the "Now" part of the equation. I can provide a better screenshot of this if you'd like. Feel free to DM me for it as it includes internal links.

**Comment by alisterscott** [comment]
We no longer show preview for scheduled posts. Closing.

<img width="474" alt="screen shot 2017-12-21 at 10 53 10 am" src="https://user-images.githubusercontent.com/128826/34235387-2f3d2eb2-e63d-11e7-9d7e-2c4b664c6f4f.png">
