### ISSUE TITLE
External Link component icon on left alignment broken

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#18072]
Once #18031 is merged you can see this issue in the dev docs:  /devdocs/design/external-link

When the icon is on the left the margin is incorrect.

https://user-images.githubusercontent.com/1270189/30460291-d7a73fb8-996a-11e7-8c26-9462c7ec0ad5.png

**Comment by unDemian** [comment]
Accidentally pushed the fix for this issue to https://github.com/Automattic/wp-calypso/pull/18031/commits 😄 https://cloudup.com/cJB9CL0auKt

**Comment by noisysocks** [comment]
Seems OK! 

<img width="669" alt="screen shot 2017-11-28 at 11 24 49" src="https://user-images.githubusercontent.com/612155/33296279-c5ab2546-d42e-11e7-8d4c-ec29d32481b1.png">
