### ISSUE TITLE
Editor: Mobile: galleries difficult to edit around in Safari on iOS

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1808]
Raised by @aduth 

**Steps to reproduce:**

The following steps should be performed in Safari on iPhone. The issue may also affect other touch devices or browsers.
1. Go to https://wordpress.com/post
2. Select a site, if prompted
3. Click the media button in the editor toolbar
4. Select two or more images from the media library
5. Click Continue in the dialog action bar
6. Click Insert
7. ~~Click the inserted gallery to select it~~
8. Attempt to add content after the gallery

**Expected result:**

~~In step 7, the gallery should be selected and the user presented with an inline toolbar to edit or remove the gallery.~~

In step 8, the user should not have a difficult time placing the cursor after the gallery.

**Actual result:**

~~Galleries cannot be selected, and~~ it is very difficult to place the cursor after a gallery to add more content.

Note added later by @aduth 

> My testing here was performed on XCode Simulator. @timmyc notes that on a true device, galleries can be selected and edited, though it is still quite difficult to move the cursor around an inserted gallery. Updating the title to reflect these findings.

**Comment by rachelmcr** [comment]
Closing as this will be improved with the block editing in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
