### ISSUE TITLE
Server Side Rendering: Set title via React

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#181]
We're currently setting `document.title` in `client/lib/screen-title`. This won't work for server-side rendering, though.

Let's use React to set the title, or to be more precise, https://github.com/gaearon/react-document-title or https://github.com/nfl/react-helmet (the latter is also suitable for meta tags, which will be relevant for SEO).

This will probably require #179 first.

**Comment by ehg** [comment]
Closing due to #2182
