### ISSUE TITLE
Editor: it's not apparent how to caption when an image exceeds viewport height

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1810]
Raised by @dllh 

Repro:
1. Insert a portrait-oriented image into a post.
2. Click the caption UI.

Expected: It'll be obvious to me how to add the caption.

Actual: Nothing seems to happen. If I click the caption UI again, the placeholder caption disappears. If it then occurs to me to scroll down and see what's going on, the placeholder caption is gone. Say I then scroll back up and click the caption button again. The caption placeholder is outside the viewport, so it has to occur to me to click the button and then scroll to see the placeholder caption.

I've used this UI a number of times and was bitten by this today, thinking suddenly that maybe the caption button was broken. Here's a gif of it in action:

![caption](https://cloud.githubusercontent.com/assets/2738252/11146885/0c7c077e-89e0-11e5-93c3-50ed4b5ae302.gif)

I wonder if there's not some hint we could provide in the UI to let the user know that they need to scroll down to see the caption, or at least to make it apparent that something has happened (briefly glow a border around the photo or something?).

**Comment by rachelmcr** [comment]
Closing as Gutenberg displays the caption placeholder as long as the image block is selected, rather than using the caption button.

#bug-scrub #pre-gutenburg-bug-purge
