### ISSUE TITLE
Editor: Add Link: Long post titles in "Link to existing content" line wrap poorly

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/wp-calypso#18123]
I'm writing a new blog post and wanted to link to a previous post via the "Insert/edit link" button. The "Link to existing content" list styles poorly when post titles are long:

<img width="302" alt="firefox_2017-09-18_22-11-11" src="https://user-images.githubusercontent.com/406254/30576776-ea1d4a8c-9cbe-11e7-89fe-59a9dee07c6f.png">

This site is a Jetpack one (`alex.blog`).

Firefox Developer Edition 56.0b12 (64-bit) on Windows 10

**Comment by lsinger** [comment]
Things even jump around for me:

![add-link](https://user-images.githubusercontent.com/23619/30663751-0216b40a-9e4c-11e7-89e1-0098251b2b0c.gif)

(also Jetpack, `leif.me`)

Safari 10.1.2 on macOS 10.12.6

**Comment by marekhrabe** [comment]
Should be fixed in production by D7504-code :)
