### ISSUE TITLE
Editor: visibility icon and TinyMCE kitchen sink toggle don't match

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1812]
Reported by @rickybanister. Different border/padding and colors:

<img width="115" alt="screen shot 2015-11-13 at 12 52 11 pm" src="https://cloud.githubusercontent.com/assets/52152/11153381/57b0ca88-89ed-11e5-8bab-50e5594b5ddd.png">
<img width="138" alt="screen shot 2015-11-13 at 12 52 17 pm" src="https://cloud.githubusercontent.com/assets/52152/11153382/58ef9352-89ed-11e5-9f68-3b70d9125cb6.png">

**Comment by rachelmcr** [comment]
Closing as TinyMCE will be replaced with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
