### ISSUE TITLE
Posts: Drafts list returning empty when it shouldn't

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#18125]
I created a new post in wp-admin for my self-hosted site (jeremey.blog). I gave the post a title then decided I wanted to write it in Calypso. I saved it from wp-admin and opened Calypso to edit it. The Post navigation says "1" next to Drafts, but the list returns empty. What's weird is that I can search for something in the title and see the post in the search. I opened the post in Calypso (by searching for it) and edited it there, but that didn't fix the issue.

Note: I haven't been able to repro on another site other than my personal one so it's probably an edge case, but the Jetpack Debug returns fine so I'm not sure what could be causing this.

#### Steps to reproduce
1. Starting at URL: https://jeremey.blog/wp-admin
2. Create a new post draft
3. Save just the title field
4. Open https://wordpress.com/posts/drafts/
5. See "Drafts (1)" in the navigation, but no post in the list.

#### What I expected
I expected the post count next to the navigation and post list to match.

#### What happened instead
I didn't see any posts in the list

#### Browser / OS version
Chrome (latest). Mac OS.

#### Screenshot / Video
<img width="1894" alt="wvefhp" src="https://user-images.githubusercontent.com/7240478/30591922-0764e9c2-9d02-11e7-8fae-fac2f131bd8a.png">

Here's how it shows up in the search:

<img width="895" alt="screen shot 2017-09-19 at 6 18 15 am" src="https://user-images.githubusercontent.com/7240478/30592008-5753f32e-9d02-11e7-9685-4459d05134e3.png">

#dogfooding

**Comment by gwwar** [comment]
@jeremeylduvall was this specific to a Jetpack site?

**Comment by jeremeylduvall** [comment]
I"m not able to reproduce this any longer. I'll go ahead and close it. If I notice it pop up again, I'll re-open with steps to replicate!
