### ISSUE TITLE
Remove or update the Gauge component

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#18134]
I was looking at the Gauge component for possible use and noticed a few things.

1. It is not used anywhere I can find in Calypso.
2. It's history [is no longer available](https://github.com/Automattic/wp-calypso/blame/a70587157b33783ba4d5e0e4a1e136680d459d51/client/components/gauge/index.jsx) in this repo. Perhaps @apeatling or @aduth could help Sherlock its origin.
3. It is blurry on hidpi screens because...
4. It uses `canvas`. 

It might be nice to use a gauge of some sort in our framework for [a few things](https://github.com/Automattic/jetpack/issues/6293#issuecomment-330630607). I would prefer we be able to scrap it as is and use a new design without the use of canvas. If we aren't currently using it anywhere, I would like to take this approach.

If there is some reason it should stick around, it should be updated to look sharp on hidpi screens.

**Comment by aduth** [comment]
Appears it was originally added for stats, bounced around a bit, then inevitably removed from usage, leaving the component to remain. I think it would be safe ([and preferable](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)) to remove. @timmyc or @jancavan would be most familiar.

4463-gh-calypso-pre-oss
5889-gh-calypso-pre-oss
6414-gh-calypso-pre-oss

**Comment by timmyc** [comment]
It was used on the Insights page at one point - I think it would be fine to remove it.

**Comment by jancavan** [comment]
Yes, we can remove it.

**Comment by MichaelArestad** [comment]
Still an issue. Just needs to be done.
