### ISSUE TITLE
WPcom: User with deactivated sub unable to "only" renew the (formerly) associated domain

### ISSUE THREAD

**Issue by mzakariya** [Automattic/wp-calypso#18131]
#### Steps to reproduce
1. Starting at URL: Go to "Purchases" page on WPcom/Calypso
2. Click on the domain that is expiring, then click on the red "Renew Now"
3. Progress to the final checkout page, and notice that the deactivated WPcom sub added itself to the purchase
4. Attempt to delete the unwanted sub from the checkout page, and get sent back to step 1

#### What I expected
- Ability to renew my domain without paying for a WPcom plan I've previously canceled

#### What happened instead
- WPcom won't let me renew my domain without purchasing the removed plan

#### Browser / OS version
- Chrome on macOS

#### Screenshot / Video
- Specific URLs available in 679762-zen

#### Context / Source

#painpoint 
#user-report

**Comment by klimeryk** [comment]
Thanks for reporting, @mzakariya! 🙇 

A stab in the dark - @prettyboymp, do you think this is a regression related to the recent changes to how we bundle domains with plans?

**Comment by prettyboymp** [comment]
Not a regression, this was specifically implemented to prevent users from just renewing the bundled domain instead of the plan since we don't allow new purchases of domains without a plan.

Diff Ref: D6217
/cc @dzver

**Comment by klimeryk** [comment]
@mzakariya Just to be clear - was the plan _removed_ or was the autorenew just turned off?

**Comment by mzakariya** [comment]
@klimeryk The plan was completely removed. Looks like the user had a WPcom plan, registered the domain with the plan, and then we switched him over to a Jetpack plan when he switched to another host.

**Comment by klimeryk** [comment]
Hmm, that's very interesting - thanks for the clarification 👍

**Comment by klimeryk** [comment]
@dzver I forgot - did you revert the change that introduced this behaviour or are we going with it? Maybe this is worth a P2 discussion, since it will affect quite a few users when renewals come (and I'm not even sure how automatic renewals will handle this).

**Comment by dzver** [comment]
I didn't revert it and I wouldn't as it would create a way to bypass the Personal plan.

**Comment by klimeryk** [comment]
I understand that from a technical point of view, but as a user I would be confused and possibly angry that a paid plan is being re-added when I renew my domain. If we really want to go this route, we should discuss this on a P2 with all the stakeholders (Happiness and business side).

**Comment by klimeryk** [comment]
@dzver if you think this is the intended behaviour, please close this ticket 🙏 If in doubt, maybe we need a P2 post with the relevant stakeholders, so that we're sure everyone agrees? This seems like a significant change, especially from support perspective.
