### ISSUE TITLE
Follow Links are Broken

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18135]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Click any Follow link (site recs or search results or from a Tag page)

#### What I expected

The follow to work.

#### What happened instead

The follow doesn't work and I see this error:

Manage: 

<img width="885" alt="screen shot 2017-09-19 at 4 34 19 pm" src="https://user-images.githubusercontent.com/24388/30620160-6cc0643a-9d58-11e7-908f-d1b4079bfb83.png">

Tag page:

<img width="877" alt="screen shot 2017-09-19 at 4 40 44 pm" src="https://user-images.githubusercontent.com/24388/30620315-69b8b854-9d59-11e7-94f9-5d046fa78645.png">

#### Browser / OS version

Happens in Safari and Chrome.

**Comment by jancavan** [comment]
Hmm, filed a similar bug a while ago, although these are feeds in the example: https://github.com/Automattic/wp-calypso/issues/14741

**Comment by fraying** [comment]
Turns out, I accidentally got blocked from following. Fixed now.
