### ISSUE TITLE
Activity Log/Rewind: Remove restore notification after inactivity

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18136]
This notification is from testing I did a long time ago. However, the notification was still there to greet me upon logging in to do more testing:

<img width="1408" alt="screen shot 2017-09-19 at 5 29 24 pm" src="https://user-images.githubusercontent.com/26996883/30621489-401a4cfe-9d60-11e7-804b-669f997180aa.png">

We should expire these notifications after a certain amount of inactivity/time since the restore. Otherwise, this might cause some concerns from users if they go to restore their site and are greeted it already has been previously.

**Comment by samhotchkiss** [comment]
This is done!
