### ISSUE TITLE
Editor: Save gallery settings per-post

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#18147]
When adding multiple galleries to a post, I often want to use the same gallery settings (gallery type, number of columns, etc.) for all. Could we temporarily save gallery settings in the post so once you add one, the next gallery defaults to those same settings?

**Comment by alisterscott** [comment]
Confirming this is still a valid enhancement request

#bug-scrub #pre-gutenburg-bug-purge
