### ISSUE TITLE
Happychat: Add happy chat button to the "approve" page

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#18149]
Right now, there's no way of getting any help once the user is in the "approval" phase of the connection flow:

![image](https://user-images.githubusercontent.com/1554855/30684124-4cdd99b8-9eb0-11e7-8a16-903255d220d1.png)

We should add some happychat button there, probably the same one proposed in https://github.com/Automattic/wp-calypso/issues/17604

**Comment by tyxla** [comment]
This one is being addressed by #18397, which also contains #18396 (which introduces a Happychat button component) and #18393 (which fixes an error).
