### ISSUE TITLE
Reader Manage: Don't show Follow link on Error page

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18140]
When a Site View page is in the "Error fetching feed" state, don't show the follow link (or follower count).

For example: https://wordpress.com/read/feeds/44029241

<img width="672" alt="screen shot 2017-09-20 at 9 54 18 am" src="https://user-images.githubusercontent.com/24388/30656719-d7cb1f2c-9de9-11e7-8131-6dd9d778ba52.png">

**Comment by jancavan** [comment]
Should it explicitly say, "This site has been deleted" or something? The error message isn't very helpful I don't think. Why is there an error fetching the feed? And why is the follow button missing?

**Comment by fraying** [comment]
I don't know if we always know why this error occurs. If we do, sure, we should say so. But the main goal here is just to get the follow link off this state so we can avoid the "blocked following" issue that hit me yesterday.

**Comment by fraying** [comment]
Also note that we're removing the link to this page in #18139, so hopefully the only way a user gets here is via a direct URL.

**Comment by gibrown** [comment]
I think we should add on to this to double check all apis and make sure that they filter out sites that have been deleted/suspended. I can imagine tag pages, search, recos, related posts, etc.

cc @aaronyan

**Comment by blowery** [comment]
There's one confounding problem here though: when sites leave wpcom, they often delete their wpcom site. We don't always catch this and remove the association with the feed. So we can have a case where:

1) I register example.com on wpcom as examplecom.wordpress.com and subscribe to it( feed 1, blog 2 )
2) I decide to leave. Move hosting to dreamhost, delete examplecom.wordpress.com.
3) Now we have a feed entry for example.com that thinks it's backed by examplecom.wordpress.com, but it's really just moved

**Comment by bluefuton** [comment]
> I think we should add on to this to double check all apis and make sure that they filter out sites that have been deleted/suspended. I can imagine tag pages, search, recos, related posts, etc.

I've just shipped r170458-wpcom which should mean deleted sites no longer appear in search results or recommendations.

**Comment by bluefuton** [comment]
We’ve improved the error page shown when a site has been deleted, and it no longer includes the follow button.

**Comment by bluefuton** [comment]
<img width="1246" alt="screen shot 2018-02-26 at 4 07 25 pm" src="https://user-images.githubusercontent.com/17325/36654228-38e060cc-1b0f-11e8-8acc-c234fc827932.png">
