### ISSUE TITLE
Editor: clicking hides suggested tags list in Firefox

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1814]
Raised by @kriskarkoski 

The suggested tag list jumps as each new tag is added in Firefox (FF 42, OS X 10.11). The same list remains stable in Chrome and Safari, only moving down as additional tags expand the tag box.

![firefox tag list jumping](https://cloud.githubusercontent.com/assets/1900444/11158297/5c93890e-8a25-11e5-8518-2729a777ad31.gif)

After looking closer it looks like the click is what is forcing it closed, you can see this by placing your cursor over the tab box and clicking-and-holding, which should close the list and then releasing opens it again.

![firefox mouse click closes tag list](https://cloud.githubusercontent.com/assets/1900444/11158367/c451f0f8-8a25-11e5-8285-170279e984d2.gif)

Note from @designsimply 

> The same problem happens if you try to click the scrollbar (the list closes and the scrollbar is unusable).

> /hat tip heckenwicke for the report at https://en.forums.wordpress.com/topic/editor-feedback/page/20?replies=621#post-2505139

> <blockquote>When I tag (on the left, still vanishing toolbox) a list of already-used tags appears. Which is nice. Really!
> 
> But when I want to scroll down that list by touching the scrollbar it provides, the list disappears. I can only scroll it with the mousewheel.</blockquote>

**Comment by nylen** [comment]
This appears to also be an issue in IE11.  #2054 will fix it in both Firefox and IE11.
