### ISSUE TITLE
Reader Visit icons too far to the left

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18143]
In Combined Cards, the Visit icons are too far to the left. Safari and Chrome.

<img width="320" alt="screen shot 2017-09-20 at 10 45 51 am" src="https://user-images.githubusercontent.com/24388/30658904-17208b42-9df1-11e7-9db5-952fc0253c6a.png">

cc @jancavan

**Comment by fraying** [comment]
Update: It's not just combined cards, it's all cards.

<img width="738" alt="screen shot 2017-09-20 at 2 42 03 pm" src="https://user-images.githubusercontent.com/24388/30669119-ed0c33da-9e11-11e7-911f-9294365cbf10.png">

cc @jancavan

**Comment by samouri** [comment]
Fixed in #18185

**Comment by fraying** [comment]
Thanks guys!
