### ISSUE TITLE
JPC: Plans page and happychat

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#18151]
There's no way to ask any question or solve any doubt the user could have once they get to the plans selection page during JPC:

![image](https://user-images.githubusercontent.com/1554855/30684458-85132c98-9eb1-11e7-9a2a-fc9eca35d0bf.png)

We should add a way to open a happychat window somewhere in there.

**Comment by rickybanister** [comment]
Note—we're running a test right now with a 'skip' button at the bottom of this screen. We can add the get help option there as well.

**Comment by johnHackworth** [comment]
(I'm removing this from the bugs/improvements for plans projects, since it's going to be handled from the 'happychat' project)
