### ISSUE TITLE
JPC: Connection error should include a happychat link

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#18150]
Every time we are showing one of the banners telling the user there has been an error, we should be given them a way to contact us:

![image](https://user-images.githubusercontent.com/1554855/30684316-fd23dcb0-9eb0-11e7-9bec-3ce8a7200cbc.png)

Just adding a "get help" link that opens up a happychat window would get this done

**Comment by tyxla** [comment]
@Automattic/jetpack-voyager are we still using the old auth process anywhere? If not, perhaps we can close this one?

**Comment by mattgawarecki** [comment]
@tyxla Jetpack doesn't offer Happychat support anymore anyway, so I think this is safe to close. 👍

**Comment by tyxla** [comment]
Even better! Thanks for confirming. Closing.
