### ISSUE TITLE
Reader: followed site is not as visible as non-followed site

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#18164]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage?q=https%3A%2F%2Fjeremy.hu
2. I already follow this site, so it's marked as "following" right below the searchform. However, I dit not notice that message at first; since the sites listed below have a bigger height and a site icon, they are a lot more visible than the "Following" message:

![screenshot 2017-09-21 at 21 08 46](https://user-images.githubusercontent.com/426388/30713931-39213482-9f11-11e7-8988-3f3defa0776b.png)

I think it would make sense to make that message more visible, maybe by displaying the site icon on that line as well?

**Comment by fraying** [comment]
Thanks for the feedback. Alas, we don't have the site icon in this state. This is working as designed.
