### ISSUE TITLE
Reader: disconnected Jetpack sites still appear in Reader search

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#18165]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage?q=https%3A%2F%2Fjeremy.hu
2. The site I am searching for still exists, and I'm already following it. The second result on the list, however, is an old subdomain from that site, that is now disconnected from WordPress.com and redirects to the main site.

![screenshot 2017-09-21 at 21 08 46](https://user-images.githubusercontent.com/426388/30714415-f867026c-9f12-11e7-81dd-92120f79c6b9.png)

#### What I expected

Once a site is disconnected from WordPress.com, I would expect it not to appear in search results.

Blog Feed ID: 72850382
Blog ID: 54299647

**Comment by fraying** [comment]
Pinging @gibrown

**Comment by gibrown** [comment]
I think this is a Jetpack issue and we should mark sites as deleted when they disconnect. :)

**Comment by fraying** [comment]
>we should mark sites as deleted when they disconnect.

@gibrown We do now? Or we have work to do?

**Comment by gibrown** [comment]
Work to do.

**Comment by jeherve** [comment]
Related threads:
p1HpG7-2LX-p2
p58i-3BT-p2
p5PDj3-3Z5-p2

**Comment by gibrown** [comment]
@lezama I think this should go into some of the related disconnect and deleted sites work I think you have been thinking about. Probably a better discussion for a P2.

**Comment by lezama** [comment]
interesting

**Comment by blowery** [comment]
@jeherve @lezama Where did this end up? Do we have something to check to know that a site is disconnected / deleted?

**Comment by jeherve** [comment]
@lezama Could we use the `is_disconnected` blog sticker for that, maybe? Somewhat related discussion about how we define inactive sites: p7rcWF-p5-p2

**Comment by gibrown** [comment]
Adding a blog sticker to the list of ones we already exclude should be pretty easy.

**Comment by lezama** [comment]
> Adding a blog sticker to the list of ones we already exclude should be pretty easy.

let's add `is_disconnected` then :)

@enejb do all disconnected sites get this sticker at some point?

**Comment by enejb** [comment]
Yes all of them should get the sticker at some point. They only get it if they haven't been talking to us for a while. (30days)

**Comment by westi** [comment]
Patch up in D10716-code for review

**Comment by westi** [comment]
Deployed in r171319-wpcom
