### ISSUE TITLE
Reader FeedError Flash

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#18166]
When a site is deleted, but you go to the site stream, we intend to show a "Site not found" error. This behavior was reintroduced here: https://github.com/Automattic/wp-calypso/pull/18142

The problem with the current implementation is that you can experience a flash where the follow button exists and then disappears once the api comes back with the 404 we only then trigger the Feed Not Found image.

Ideally we'd have placeholder until the data has correctly loaded.

Thanks @jmdodd for pointing this out

To Test:
- open the deleted site: https://wordpress.com/read/feeds/44029241

**Comment by bluefuton** [comment]
We have the same problem with site blocks (see https://github.com/Automattic/wp-calypso/pull/23092).

**Comment by samouri** [comment]
@bluefuton: Is this still an issue? I don't temporarily see a follow button anymore so I think it may be solved

**Comment by bluefuton** [comment]
Looks suspiciously fixed to me :)
