### ISSUE TITLE
Extensions: root reducer cannot have several exports

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#18180]
When the root reducer of a `client/extension` has more than one export, we get this error at running time:

![reducer-not-a-function](https://user-images.githubusercontent.com/583546/30749539-0127b148-9fb4-11e7-99ce-2455391ba252.png)

I was refactoring Happychat and moved the [current reducer](https://github.com/Automattic/wp-calypso/blob/master/client/state/happychat/reducer.js) to `client/extensions/happychat/state`, which [will be injected dynamically in the Calypso root reducer](https://github.com/Automattic/wp-calypso/blob/master/client/state/index.js#L78) under the `extensions` key. For testing purposes, besides the default export, it has named exports for any individual reducer. Calypso gives the error above when trying to import the extension reducer.

Note that: 

* It doesn't fail if we use the `combineReducers` provided by Redux instead of the `state/util/combineReducers` one.
* This only happens with the root reducer of the extension, nested reducers can have several exports ([example](https://github.com/Automattic/wp-calypso/blob/master/client/extensions/wp-job-manager/state/setup/reducer.js)).

**Comment by coderkevin** [comment]
After an initial look at the code, I wonder if it’s because the extensions loader uses `require` instead of `import`: https://github.com/Automattic/wp-calypso/blob/master/server/bundler/extensions-loader.js#L11

Just leaving breadcrumbs here to pick up later.
