### ISSUE TITLE
Create ES2016+ bundles

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#18182]
@dmsnell brought up an interesting article in calypso chat: https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

The idea is that we can easily create an alternative slimmer build for modern browsers that don't need all the polyfilling and babel transformations.  I can see this project having a couple stages:

1. prototype creating a less-transformed build [small effort]
2. measure the difference between the es6 build and our current es5? builds.  evaluate if its worth putting in the remaining effort to productionize it [small effort]
3. if its deemed worth it, then implement the remaining bits + test thoroughly (medium-large effort)

I'm sure there are many more questions to consider.  Like what will this do to build times?

**Comment by jsnajdr** [comment]
Already in production for some time thanks to @sgomes 👍
