### ISSUE TITLE
Editor - inserting links to Existing Content

### ISSUE THREAD

**Issue by rossanafmenezes** [Automattic/wp-calypso#18188]
This only happens to blogs with a lot of content and for AT sites. I have tried on the User's blog, on my AT test blog both have problems inserting links. I have tested on Chrome and Safari. Got the same problem on both. Tested on my Premium Plan site and did not get the same issue. 

1.  Go to https://wordpress.com/posts and open an existing post with several paragraphs of text
2. Select part of the text and click on the link icon. 

#### What I expected

I expected the Window showing the Existing content to be linked to scroll up and down normally like it did on my Premium Test site

#### What happened instead

The scrolling is jamming. The links start overlapping, and the whole content starts blinking making the whole process impossible. The more posts you have on the blog the harder it gets. This happens regardless of the size of the title. Short or long, it crams up and jams. 
#### Browser / OS version

Chrome Version 61.0.3163.79 (Official Build) (64-bit)
Safari Version 11.0 (12604.1.38.1.7)

#### Screenshot / Video

https://cldup.com/eQ98_yrCbE.png
https://cloudup.com/cvDS-Bbtcax
https://cloudup.com/crkwMZetAVL

#### Context / Source

I had this issue doing a manual test after a user reported it via live chat. It simply makes it impossible to create links to existing content on your site. 

user: trustcommunicationsinc

**Comment by rachelmcr** [comment]
Thanks for the report! This issue is being tracked here: https://github.com/Automattic/wp-calypso/issues/15809
