### ISSUE TITLE
Activity Log/Rewind: Hide "Rewind to this Point" option when restore failed.

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#18196]
#### Steps to reproduce
1.  Starting at URL: https://wordpress.com/stats/activity/example.com.com
2. Attempt to Restore to a given point, 
3. When you see the error message click the three dots menu to see your options. 
4. Notice the "restore to this point" option although there's nothing that changed on the site and you were shown an error. 

#### What I expected
To be given either a link or option on how to fix the problem. Another option would be to hide the menu completely on this action

#### What happened instead
Was given the option to restore my site to a failed credentials point. 

#### Browser / OS version
Ubuntu 17.04 Firefox 55

#### Screenshot / Video
![screenshot_22-09-2017-22 48 49](https://user-images.githubusercontent.com/150348/30770589-92e90ec6-9fe9-11e7-92cf-e6be543bc463.png)

#### Context / Source
Found while manually testing

**Comment by samhotchkiss** [comment]
Done!
