### ISSUE TITLE
Editor: Tags are stripped from <pre> tag body

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#18203]
#### Screenshot / Video
![pre-component-bug](https://user-images.githubusercontent.com/4335450/30777599-e5ff326e-a072-11e7-998a-09294b88830b.gif)

#### Steps to reproduce
1. Open the editor by creating or editing a post.
2. Add a pre tag from either view.
3. Add some JSX inside the pre tag (or any tag matching `<x />` for that matter)
4. switch between the visual editor view and the html editor view, and back again.

#### What I expected
A code block containing my component code to persist between both views and ultimately show up in my published post, allowing me to blog about code.

#### What happened instead
The content of the pre tag is emptied when toggling from view to view.

#### Context / Source
Originally found while testing #17481.

#### More Screenshots
Here, I attempt to write some HTML in to a `<pre />`. Note that the content that is not part of a tag survives the cull...

<img width="848" alt="screen shot 2017-09-23 at 15 32 55" src="https://user-images.githubusercontent.com/4335450/30777682-258de112-a075-11e7-8f64-4da41d9dfc3e.png">
<img width="846" alt="screen shot 2017-09-23 at 15 33 04" src="https://user-images.githubusercontent.com/4335450/30777683-25a1355a-a075-11e7-8d23-8b2d2a6bbbff.png">
<img width="847" alt="screen shot 2017-09-23 at 15 33 09" src="https://user-images.githubusercontent.com/4335450/30777681-258d3708-a075-11e7-83f3-33b7c19d9bbf.png">

**Comment by spen** [comment]
This actually seems to be the same as or very close to #1797
Feel free to close if necessary.

**Comment by bisko** [comment]
From @supernovia on #18042:
> I've seen several cases of similar issues. Noting another case at 878546-f

**Comment by lancewillett** [comment]
Hi @spen and @jblz Checking in on this one since it's marked High priority. On your plate? If not, let's remove the priority and someone can get to it later.

**Comment by jblz** [comment]
@lancewillett Thanks for the ping.  This feels pretty broken, so I'd like to get it fixed.
You don't even need to enter a full tag for it to get stripped... Something as simple as `<x` will get stripped.

It definitely seems like a frontend issue to me. The content is present in the [`EDIT_POST` store dispatch](https://github.com/Automattic/wp-calypso/blob/cad1c9818f34645e73ec9a47969c51fd1c814a35/client/lib/posts/post-edit-store.js#L205), but missing in the next action. I haven't been able to trace it yet fully.

I moved it up on our board.

**Comment by rachelmcr** [comment]
@jblz I'm closing this issue as this will be resolved in Gutenberg and it doesn't look like an emergency. (I tested in Gutenberg and preformatted text such as `<x />` is retained when switching to HTML edit mode and back to visual edit mode.) Please feel free to reopen if you think this merits a fix before Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
