### ISSUE TITLE
Editor: Can't 'click out' below <pre> tag.

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#18204]
#### Steps to reproduce
1. Open the editor by creating or editing a post.
2. Add a pre tag, make sure to add it after any other elements.
3. Add some content to the pre tag.
4. Try clicking below the pre-tag

#### What I expected
I expected the cursor to shift to a new line, allowing me to quickly resume writing outside of the tag.

#### What happened instead
The cursor stays put, I feel unsure of how to exit the pre tag until exploring other options and finding that pressing the down arrow worked.

I feel that something similar might be the case with a touch device, though I'm yet to try this out.

Note that this is only a problem when there are no elements following the pre tag. In cases where there is something (even just a new line or two) the cursor will move down to that line.

#### Suggestion
An idea might be to listen for clicks/touches in the editor, if the position is 'after' the last element, add a new line. We might think about only doing this if the cursor is not already in a <p> tag.

**Comment by rachelmcr** [comment]
Closing since this will be resolved with block-level editing in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
