### ISSUE TITLE
Gridicons: Rename script that checks gridicons format

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#1821]
We should probably rename the script that checks gridicon sizes from `gridiconFormatChecker` to `gridicon-format-checker` or maybe `check-gridicons`. It indeed doesn't follow the kebab-case naming convention used in the [`bin` folder](https://github.com/Automattic/wp-calypso/tree/master/bin):

```
bundler
check-node-version
generate-devdocs-index
get-i18n
gridiconFormatChecker
i18nlint
list-assets
pre-commit
pre-push
record-env
run-all-tests
run-tests
update-dependency
```

/cc @johnHackworth

**Comment by johnHackworth** [comment]
good point! :+1:

**Comment by afsheenirani** [comment]
@johnHackworth - I have these changes ready. I'm currently testing them. Will submit a PR today.

**Comment by afsheenirani** [comment]
@johnHackworth - Submitted PR.
