### ISSUE TITLE
Help: Send Tracks pings for mood/severity specifiers in contact form

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#1822]
When filling out the contact form at http://calypso.localhost:3000/help/contact, you can select how you're feeling and can report the perceived severity of the issue you're contacting us about. These are the fields I'm talking about:

![screen shot 2015-12-18 at 11 22 33 am](https://cloud.githubusercontent.com/assets/2738252/11901440/a9df1de4-a579-11e5-80f3-7c847edf0d86.png)

It'd be nice to send a Tracks ping when one of these is selected, as it will help us understand more about users who're seeking support, so that we can provide better support.

**Comment by jeremeylduvall** [comment]
Should be fixed in #3151
