### ISSUE TITLE
My Sites: "Please set your Primary Site to valid site"

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#18258]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. click on My Sites
3. We don't know how to consistently repro from there, but we have several users experiencing this.  Also, in cases where we've tried to click on the profile and select a primary site, we have not consistently been able to.

#### What I expected
To be able to see stats, etc, for the primary site.

#### What happened instead
We get this error.

#### Browser / OS version
Doesn't seem to matter.

#### Screenshot / Video
https://cloudup.com/coBS_n3_ucT
Note in this case, the user's only site was no longer using Jetpack as far as I can tell. But we've seen this with Jetpack users and WordPress.com users alike.

#### Context / Source
We have several complaints in this thread:
https://en.forums.wordpress.com/topic/message-please-set-your-primary-site-to-valid-site?replies=34

**Comment by supernovia** [comment]
cc @psealock

**Comment by psealock** [comment]
Thanks @supernovia 

I can reproduce using http://gbsouthaustin.com. The state which causes the error to occur seems to be a result of a primary blog which was at one time connected via Jetpack but no longer has Jetpack enabled/acitve. More information about reproducing this state can be found in https://github.com/Automattic/wp-calypso/pull/17583#issuecomment-325715137

Using https://jetpack.com/support/debug/, we can see http://gbsouthaustin.com is not active. This would explain the inability to set a primary site.

Our error message is not helpful and sending users down the wrong path. It should ask them to enable Jetpack I think. Perhaps, "Please enable Jetpack on Primary Site" and a link to wp-admin?

@supernovia Any thoughts?

**Comment by supernovia** [comment]
People who only have WordPress.com sites are seeing it too, though, as well
as business plan users.
