### ISSUE TITLE
Jetpack: plan autoconfig didn't configure Akismet

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#18257]
I purchased a plan and autoconfig failed (I presume because plugins couldn't be configured remotely, I'm not sure). This seems to also have caused Akismet's api key to not be configured.

<img width="1363" alt="screen shot 2017-09-25 at 5 09 12 pm" src="https://user-images.githubusercontent.com/437258/30831177-83c724fa-a214-11e7-8acd-3bfb51ed4f36.png">

When this happens there is no option in the UI for 'retrying' the autoconfig process. We need a solution to try to redo the set up. 

Also the link in the description of that field invites me to visit akismet.com to get a key even though I purchased a pro plan. We need to add intelligence to detect whether I have a key for this site and change the description accordingly.

cc @johnHackworth @tyxla @sirreal @seear

**Comment by rickybanister** [comment]
A few other things after looking more closely at this—

1. I didn't notice that the field was completely disabled at first. I'm not sure why this would be. Akismet was installed, but it seems that autoconfig couldn't activate it. That might have been the issue, but we should be able to detect that and give the user very explicit instructions on what to do.
2. It would be nice if the collapsible card was open if Akismet is not configured. The card looks weird and mostly useless if collapsed.
3. when the collapsible card opens it adds an awkward top margin to the card. This can be removed.

**Comment by tyxla** [comment]
Partially related with some of your suggestions: #16793

Looking further, it seems most of these are related with the Akismet settings card, including the mechanism for "retrying", so I'm moving this to the corresponding milestone.

**Comment by tyxla** [comment]
I'm closing this, as the old auto-config process is no longer in use.
