### ISSUE TITLE
Help: Enable in the desktop app

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#1826]
At present, the /help screen is not enabled in the desktop app. When testing some time back, we discovered some weird usability issues. Once some of the dust from launch settles, we should look into enabling it on the desktop app.

In particular we'll probably want to see how it works when clicking a link out to a site from within the desktop app. That is, if you start a chat in the app and then land in production wordpress.com, does the chat follow you as expected? I'm sort of skeptical that it will without some finagling.

**Comment by mtias** [comment]
This is done.
