### ISSUE TITLE
Comments: replying appears to succeed even if API request fails

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#18275]
If you make reply to a comment and the API request fails, the comment is still inserted into the page, giving the false impression that the comment was saved successfully.

Before the comment is posted:

![screen shot 2017-09-26 at 16 01 20](https://user-images.githubusercontent.com/17325/30868301-207d0168-a2d6-11e7-8b8e-e321fb30419c.png)

After the comment is posted:

![screen shot 2017-09-26 at 16 01 37](https://user-images.githubusercontent.com/17325/30868439-8a7e8fb4-a2d6-11e7-8c77-03f31c125711.png)

There's an error notice, but the comment appears in a style that would suggest it has been successfully saved.

#### Steps to reproduce

Prerequisite: scupper your access to the API somehow. I renamed the `replies/new` endpoint to something else in the data layer.

1. Starting at URL: http://calypso.localhost:3000/read/feeds/40474296/posts/1385874605
2. Enter a new comment
3. Hit 'Send'
4. Note that you see an error notice at the top right, but also that the comment is inserted into the page, giving the impression that it has been successfully saved

#### What I expected

If the comment posting fails, the comment textbox should remain visible, preferably with an inline error message.

#### What happened instead

The comment textbox vanished and the comment appeared like the other successfully posted comments:

![screen shot 2017-09-26 at 16 18 57](https://user-images.githubusercontent.com/17325/30868397-69cd76fe-a2d6-11e7-8936-04e353460a09.png)

#### Source

Props to @martinremy for spotting this one.

**Comment by fraying** [comment]
> If the comment posting fails, the comment textbox should remain visible, preferably with an inline error message.

👍 

Note that this goes for Fullpost and Convos.

**Comment by bluefuton** [comment]
This was fixed in #18356.
