### ISSUE TITLE
Help: Contact form options don't update after adding/removing a purchase

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#1827]
Currently, users with a free site (no purchases) have the option to submit a question to the forums, while users with a purchased plan have the option to submit a ticket or chat. However, purchasing or removing a plan doesn't immediately change the options at /help/contact — you have to do a hard refresh of the page to get the new, corresponding contact options.

I began with an account with no purchases:

![screen shot 2015-12-18 at 11 31 21 am](https://cloud.githubusercontent.com/assets/8658164/11903004/9e321062-a57b-11e5-9f3d-06907fd60718.png)

As expected, when I went to /help/contact I saw the forum contact form:

![screen shot 2015-12-18 at 11 31 37 am](https://cloud.githubusercontent.com/assets/8658164/11903012/b1501a90-a57b-11e5-8e8d-a6fdec021d1c.png)

I then added a Premium plan to my site (going through the Calypso purchase flow):

![screen shot 2015-12-18 at 11 32 49 am](https://cloud.githubusercontent.com/assets/8658164/11903016/bdcb6ec8-a57b-11e5-93db-c856425f667b.png)

But when I visited the contact form again I still saw the forum contact form:

![screen shot 2015-12-18 at 11 32 55 am](https://cloud.githubusercontent.com/assets/8658164/11903028/cf9546b0-a57b-11e5-8930-7761c8000af0.png)

Only after refreshing the page did I see the expected chat contact form:

![screen shot 2015-12-18 at 11 33 00 am](https://cloud.githubusercontent.com/assets/8658164/11903044/ef95e5c8-a57b-11e5-8f3d-4317aa83d348.png)

**Comment by jeremeylduvall** [comment]
Fixed via #4649.
