### ISSUE TITLE
Reader Caterpillar: "commented" text remains after click "Show all"

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#18285]
After we click "Show all", the "commented" text remains with no caterpillar.

<img width="846" alt="show_all" src="https://user-images.githubusercontent.com/4505888/30880397-565cbd10-a2b7-11e7-95b6-bf186466a579.png">

**Comment by fraying** [comment]
Is this is when all comments are displayed? If so, "Show all" should also disappear (or become "Hide all").

**Comment by samouri** [comment]
Thanks for the find @aaronyan!
This should sort itself out as we address pagination / the Hide All component.

1. pagination: https://github.com/Automattic/wp-calypso/pull/18247 
2. hide all: https://github.com/Automattic/wp-calypso/pull/17965
