### ISSUE TITLE
Conversations: Not showing all three recent comments

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#18284]
Some posts are not displaying all three comments. Bug?

https://wpcalypso.wordpress.com/read/blogs/489937/posts/254547

<img width="845" alt="not_showing_three" src="https://user-images.githubusercontent.com/4505888/30879701-024464aa-a2b5-11e7-8b16-7e89eeeb5fd3.png">

**Comment by samouri** [comment]
@aaronyan: can you still repro this? this was an issue that existed before caterpillar pagination launched.  

I noticed/fixed the bug while working on pagination and haven't seen it since

**Comment by aaronyan** [comment]
I haven't seen this issue in awhile. Closing for now!
