### ISSUE TITLE
The search information link leads to 404

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#18290]
When I navigate to https://wordpress.com/settings/traffic/ and click on the info icon in the Search box, I get a 404 for https://jetpack.com/support/search.

**Comment by rachelmcr** [comment]
Thanks for the report, @davoraltman. Could you add a screenshot showing the info icon you're referring to? Is this specific to Jetpack sites?

**Comment by davoraltman** [comment]
@rachelmcr Sorry for missing the screenshot here. I can see that it's now fixed and the link https://jetpack.com/support/search/ doesn't 404 anymore (the page was published on September 27th hah). It previously affected only Jetpack sites.
