### ISSUE TITLE
Bug: Korean Windows IME Input Problem

### ISSUE THREAD

**Issue by youngminz** [Automattic/wp-calypso#1831]
What I expected: I typed "한국어 입력 테스트 중입니다. 이런 식으로 제대로 입력되지 않습니다."
What happened instead: "한국어  테스트 . 이런  제대로  않습니다.지되력입로으식다니입중력입"
Steps to reproduce: Type some Korean sentence. My OS is Windows 10 Pro K.

![Korean IME Bug](https://cloud.githubusercontent.com/assets/5145369/11903546/66c6742e-a5fd-11e5-8539-15561173770d.gif)

I've tested with Microsoft Edge and Chrome, this problem wasn't occurred.

**Comment by lancewillett** [comment]
We haven't been able to work on this one, unfortunately it's an edge case. Thanks for the report.

**Comment by youngminz** [comment]
Updated to latest version and this bug seems be solved.
