### ISSUE TITLE
Comments: sometimes the page appears to freeze

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#18320]
Sometimes on a clean cache we're unable to interact with the page for a few seconds. Let's see if we can reproduce this and fix this issue.

There may be a related Calypso issue on boot (jetpack, proxied)

**Comment by vindl** [comment]
We've discussed this on several occasions and we are pretty sure that this is not related to Comments section but happens in other parts of Calypso too.

**Comment by gwwar** [comment]
closing this out for now to make a more generic perf issue
