### ISSUE TITLE
Comments: ability to filter on a particular post

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#18332]
This is part of #18315 

After chatting with @megsfulton, we won't provide a direct post selector in the site specific view, but instead link to it from a few places:

1. The Post List View ( posts/siteId ) when clicking on the comments icon
<img width="723" alt="screen shot 2017-10-17 at 3 09 24 pm" src="https://user-images.githubusercontent.com/1270189/31692085-36478a5e-b34d-11e7-9d3a-fb42b04ac338.png">

2. Clicking on a Post Title within /comments
This currently takes us to the reader, but we can instead filter down comments to that particular post. Note that in mobile, we only want to trigger this in the expanded view to avoid mis-taps.

@megsfulton what happens if it's a comment link? Filter down to that post? Show the comment specific view, or go to reader?

<img width="185" alt="screen shot 2017-10-17 at 3 11 26 pm" src="https://user-images.githubusercontent.com/1270189/31692164-88fc4050-b34d-11e7-940a-1bdb056cc125.png">

**Comment by kwight** [comment]
Started in #19127 .

**Comment by drw158** [comment]
I think I would expect it to not go outside of Comments. So maybe the comment specific view?

**Comment by gwwar** [comment]
@drw158 also see discussion in p7jreA-1cn-p2
