### ISSUE TITLE
Reader: Canceled reply reappears in main comment box

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#18331]
Once a reply has been canceled, the reply text should just be deleted instead of it reappearing in the main comment box:

![comment](https://user-images.githubusercontent.com/4924246/30929406-4ca857f4-a373-11e7-8c1d-df3b3511f008.gif)

The same issue happens in fullpost comments.

**Comment by bluefuton** [comment]
I noticed and fixed this one while working on the active comment reply changes:

https://github.com/Automattic/wp-calypso/pull/18671/files#diff-27bdbf2360c213094ee0784e459c5e29R78
