### ISSUE TITLE
People: after accepting a follower invite, the notification text is wrong

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#1834]
To reproduce:
- Invite a wpcom user to follower your blog
- Login as the user, and accept the invite
- Note the message:

![screen shot 2015-12-18 at 1 58 22 pm](https://cloud.githubusercontent.com/assets/2694219/11904712/000fbfa0-a590-11e5-9743-412dfa44d929.png)

**Comment by ebinnion** [comment]
This is fixed in #1849.
