### ISSUE TITLE
Plans: Incorrect tooltip on the "Unlimited storage space" line item

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#18350]
#### Steps to reproduce
1. Starting at URL: wordpress.com/plans/connected-jetpack-site.com
2. Click the tooltip (i) next to "Unlimited Storage Space"

#### What I expected
Text explaining that you get unlimited **backup** storage space

#### What happened instead
Text is talking about **media** storage

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/2287740/30963262-b951d2a0-a444-11e7-9c4d-916c661d44fd.png)

#### Suggested fix
- Feature title to become: _Unlimited Backup Space_
- Feature tooltip to become: _No matter how large your site is, we will backup all its content, data, media, and settings._ 

#### Beware
The existing tooltip/feature is probably in use by dotcom plans. So modify with care. May need to create a new constant.

**Comment by AnnaMag** [comment]
Note: the feature is presented and described in the same way in the .com plans. Since this would benefit from an update here, it might be possible that the same applies to .com plans. Checking that :)

**Comment by AnnaMag** [comment]
Could we double check that it is correct, please?
It seems like `Unlimited Backup Storage` is a Pro plans feature?
![screen shot 2017-11-28 at 12 54 58](https://user-images.githubusercontent.com/13561163/33318534-37d66638-d43b-11e7-817a-f268d4bbbcaa.png)

/cc @richardmuscat

**Comment by richardmuscat** [comment]
Thanks for finding this. The grid on jetpack.com was incorrect. I have now fixed it: https://jetpack.com/features/comparison/

**Comment by rickybanister** [comment]
Another user reported confusion with the text in the WordPress.com plans page recently, is this something you can prioritize for this week @AnnaMag

**Comment by AnnaMag** [comment]
Apologies @rickybanister, I missed your ping. Really late, but we will fix it this week.

**Comment by AnnaMag** [comment]
Fixed in https://github.com/Automattic/wp-calypso/issues/22701.

**Comment by AnnaMag** [comment]
Fixed in https://github.com/Automattic/wp-calypso/issues/22701.
