### ISSUE TITLE
Contact Form: add datepicker field

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#18364]
Jetpack's Contact form will soon include a new date field:
- https://github.com/Automattic/jetpack/pull/7819
- https://github.com/Automattic/jetpack/blob/7dbfd70fff4b3de8e91fc2b565686d3f43c372a4/to-test.md#contact-form

![screenshot 2017-09-28 at 15 09 09](https://user-images.githubusercontent.com/426388/30983798-c02c041e-a48b-11e7-9b48-5c400569bd9a.png)

It would be nice to add that field to the WordPress.com editor as well:
- this way Jetpack users would have the same options in the 2 interfaces;
- and WordPress.com users would benefit from a new feature.

**Comment by alisterscott** [comment]
Confirming this hasn't been implemented yet

#bug-scrub #pre-gutenburg-bug-purge
