### ISSUE TITLE
Add Contact Support for Failed Rewind

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18374]
What does a failed rewind interface look like? @keoshi 

For example, with a SUCCESSFUL rewind yet my site being down, I got a notification AND can see the Red Icon by my site status in my sites:

<img width="945" alt="screen shot 2017-09-28 at 7 45 01 am" src="https://user-images.githubusercontent.com/26996883/30973055-060116b6-a421-11e7-9437-5169c896a29a.png">

Neither of these allow for me to contact support. If I view my site, there is no option for me to contact support either (it just tells me to with no link):

<img width="928" alt="screen shot 2017-09-28 at 9 32 56 am" src="https://user-images.githubusercontent.com/26996883/30978664-0a4024ce-a430-11e7-8621-3e37697f59ef.png">

Curious what we have for a failed rewind and what flows we can build in so they contact support.

**Where to direct support:** 

For an Atomic site > this needs to go to WP.com.
For a JP connected non atomic site > this needs to go to JPOP.

**Comment by eliorivero** [comment]
Maybe the red notice could change if user has Rewind? It could prompt users to review the latest events and try fixing them with Rewind.

For emails, there could be an extra line if users have Rewind prompting them to do the same thing.

cc @MichaelArestad

**Comment by eliorivero** [comment]
Based in a convo with Michael p1512751237000242-slack we'll add a third button in the success message, like we have in error messages

![image](https://user-images.githubusercontent.com/1041600/33776040-f267b9e4-dc1e-11e7-82e5-5b1e4617243e.png)

labeled "Get help" the borderless button with chat icon similar to this

![image](https://user-images.githubusercontent.com/1041600/33776129-3610193e-dc1f-11e7-8138-829bc84718ba.png)
