### ISSUE TITLE
Disable rewind abilities for Security Threat notifications

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18370]
Right now, we show an option to restore your site for security threats:

<img width="1087" alt="screen shot 2017-09-28 at 1 17 38 pm" src="https://user-images.githubusercontent.com/26996883/30988527-6bf3811a-a44f-11e7-97d8-2777d27cfd7a.png">

This flow doesn't make much sense. **Can we audit when we allow rewinds to happen so that they make sense in context?** Why would we ever encourage someone to restore their site to a threat?  That should just be informational and not actionable. 

cc @keoshi  on this. Sorry for the double posting.

**Comment by keoshi** [comment]
This should be covered on this list and whether items are “rewindable“ or not, can you check to see if everything checks out? https://docs.google.com/spreadsheets/d/1521T068hmg8_FsPXTYBSZU-shoyPRCiGWDnwZlFQ7Ms/edit#gid=0

It may take a bit more time to get everything implemented though.

**Comment by annezazu** [comment]
Everything seems fine based on that doc :)

**Comment by samhotchkiss** [comment]
Done!
