### ISSUE TITLE
Add prompt for user to contact support if activity log is broken

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18375]
**How would a user know activity log isn't working?**

Right now, if we have a sync issue, activity log would stop functioning. We need to make sure there's a "state" designed for this. Ideally, it could tie into notifications, the site icon (show yellow or orange), and have a banner with actions to take:

<img width="1393" alt="screen shot 2017-09-28 at 11 57 11 am" src="https://user-images.githubusercontent.com/26996883/30985129-38c4f572-a444-11e7-8545-37e8100aaf60.png">

This is a really bad design ^ but it's to just demonstrate where my head is at.

Previously posted this to which @rickybanister  replied with:

> This is a good idea. We are still really bad at handling connection problems.

cc @keoshi  for true design implementation.

**Comment by keoshi** [comment]
I love the idea and that design, and actually wouldn't change much.

The only tiny thing I'm unsure about is the `View Debug Info` button. What would that show? As a user, seems like I'd go down a rabbit hole of technical information and probably wouldn't know what to do with it at the end. Would either hide that option altogether or convert it into a link to look like a tertiary option.

**Comment by annezazu** [comment]
I was thinking of just a link to the Jetpack Debugger but we don't show users much info and, I agree, we'd likely just confuse them more. 

Do we know what breaks activity log? From what I understand, it's sync problems mainly. Is that true @samhotchkiss. If so, I wonder if we can put a doc in place so they can at least take _some_ initial step to try to troubleshoot on their end. I'm never a fan of implementing something where we don't offer an option for a user to help themselves if they want to.

**Comment by keoshi** [comment]
> I'm never a fan of implementing something where we don't offer an option for a user to help themselves if they want to.

Agree! Though the biggest problem now seems to be understanding where the sync issues come from or how can we solve them, so it's definitely a hurdle we have to over, but that is an inherent part of building a new system.

And like you advocate for, we should always have the user in mind, and not assume they understand what's going on at all times so I'm all for linking to documentation and chat with HEs.

**Comment by MichaelArestad** [comment]
Closing after opening specific issues for specific breaks:

https://github.com/Automattic/wp-calypso/issues/19781

https://github.com/Automattic/wp-calypso/issues/19780
