### ISSUE TITLE
Activity Log: italicize object names

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#18385]
This decision was taken from https://github.com/Automattic/wp-calypso/issues/17743#issuecomment-327245701 so we can keep track of the styling when the API reflects those changes.

> italicizing the name of the thing that was updated/deleted helps make the update easier to read, so I'd vote for italicizing across the board

### Before

![image](https://user-images.githubusercontent.com/390760/30157674-d04708b2-93ba-11e7-90f9-c53cf7ef4369.png)

### After

![image](https://user-images.githubusercontent.com/390760/30157777-1148c4cc-93bb-11e7-99cb-992658ca7f6c.png)

Related API issue: https://github.com/Automattic/action-to-activity-log/issues/84

**Comment by sirreal** [comment]
Assigned to @eliorivero who will be taking over and I'll be ramping down on AL. This will require API changes so it's not something we're likely to need to update in the UI very soon.

**Comment by MichaelArestad** [comment]
Closing since we shifted to an updated format
