### ISSUE TITLE
Jetpack Plugins: Ratings Stars misformatted with text overlay

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#18381]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plugins/<plugin-slug>/sitename
2. Look at star ratings

#### What I expected

To be able to read ratings text

#### What happened instead

Ratings text is covered by stars

#### Browser / OS version

Tested Firefox and Chrome on macOS 10.12.6

#### Screenshot / Video

<img width="747" alt="screen shot 2017-09-29 at 12 03 28 pm" src="https://user-images.githubusercontent.com/128826/30997914-414d7bae-a50e-11e7-8722-ea9eaa08b028.png">

#### Context / Source
manual-testing

**Comment by rachelmcr** [comment]
Looks like this is fixed as of https://github.com/Automattic/wp-calypso/pull/18392.
