### ISSUE TITLE
Reader: subscriptions smushed on Manage Following

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#18387]
We're occasionally seeing this in Chrome:

![screen shot 2017-09-29 at 10 24 05](https://user-images.githubusercontent.com/17325/31012029-42481e20-a508-11e7-9d6c-059f003771da.png)

It could be connected to the recent upgrade to `react-virtualized` in https://github.com/Automattic/wp-calypso/pull/18237. Some users are reporting that a downgrade to 9.9.0 sorts the problem out: https://github.com/bvaughn/react-virtualized/issues/822

Also possibly related - Chrome 61 has some changes to scrolling behaviour: https://bugs.chromium.org/p/chromium/issues/detail?id=157855

**Comment by marekhrabe** [comment]
Most likely related: #18123 (uses `<List>`). I'll try the downgrade and also check this usage whether it gets fixed too…
