### ISSUE TITLE
Editor: Trashing post: Flash of dialog before navigation.

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#18398]
***-- More details to come --***

While writing a test plan for a refactor PR ( #18229 ) earlier in the week I noticed some strange behaviour when trashing a post directly from the post editor (Using the button in the far bottom-right).

Most likely this is a state issue - maybe we dispatch something like `showDeletedDialog: true` in the same breath as the navigation.

### To Reproduce:

- Go to a new or existing blog post
- Trash the post using the button in the bottom right of the editor view.
- Watch carefully for the flash of the dialog shown in the third image below, before immediately being taken to the posts list view.

### Screenshots
![screen shot 2017-09-29 at 14 05 41](https://user-images.githubusercontent.com/4335450/31017434-573dbeb2-a520-11e7-9cc4-236293dbd372.png)
![screen shot 2017-09-29 at 14 13 02](https://user-images.githubusercontent.com/4335450/31017432-571f365e-a520-11e7-8f0b-c164b54ac38f.png)
![screen shot 2017-09-29 at 14 14 40](https://user-images.githubusercontent.com/4335450/31017503-9c39a454-a520-11e7-8711-f1e4eecb6590.png)

![screen shot 2017-09-29 at 14 12 45](https://user-images.githubusercontent.com/4335450/31017433-573846d0-a520-11e7-9aba-bf7d95b803ec.png)

**Comment by ianstewart** [comment]
Also reported in #18545. (Closed now as a duplicate.)

**Comment by ianstewart** [comment]
This dialog will not appear at all when trashing CPTs on WordPress.com.

**Comment by rachelmcr** [comment]
We also have an issue for this in https://github.com/Automattic/wp-calypso/issues/4795. I'll close this as a duplicate report. Thanks!
