### ISSUE TITLE
Jetpack Plans: Pricing test

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#18444]
We are going to run a test (not an A/B) one that reduces the prices of jetpack plans to cheaper levels.

First, we need to retire this test:

https://github.com/Automattic/wp-calypso/pull/18233

The results are not as good as we liked, so we are going to remove the /B variation, clean up, and leave only the A/ one.

Once that's done, the next step will be to change the price of jetpack plans to this:

![image](https://user-images.githubusercontent.com/1554855/31085749-4dae5576-a798-11e7-9b22-372a443daf40.png)

Ping me for any details

**Comment by seear** [comment]
Scripts to both change and revert the prices: D7533-code

**Comment by kriskarkoski** [comment]
@johnHackworth I just found this issue when looking for something else. Is it still In Progress or can it be closed?

**Comment by seear** [comment]
This test was concluded.
