### ISSUE TITLE
Reader: Comments don't load when navigating by keyboard

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18458]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/25823
2. Click any post.
3. Hit "j" to go to previous post.
4. Scroll to the bottom. 

#### What I expected

If the post has comments, the comments would be shown.

#### What happened instead

No comments are displayed.

For example, on this post: https://wordpress.com/read/feeds/25823/posts/1605883360

I see: "Load more comments (Showing 0 of 55)"

<img width="749" alt="screen shot 2017-10-02 at 1 00 08 pm" src="https://user-images.githubusercontent.com/24388/31096713-c8dbbe22-a771-11e7-9327-0916a3df8457.png">

@samouri says: "that sounds like a problem with a `componentWilLReceiveNewProps`
aka b/c you got there with j/k and our logic is broken. should be a pretty easy fix if my hunch is right"

**Comment by blowery** [comment]
This got fixed
