### ISSUE TITLE
Can click inactive Rewind button 

### ISSUE THREAD

**Issue by joendotcom** [Automattic/wp-calypso#18450]
#### Steps to reproduce
1. Open Activity Log
2. Click an inactive "Rewind to this day button"

Note: It may take a few clicks — could also be positioning of click.

#### What I expected

Nothing happens, button is inactive

#### What happened instead

Restore dialog appears. Rewind is off, so this should not be possible.

#### Browser / OS version

Mac OS X 10.12.6 / Chrome 61.0.3163.100 (Official Build) (64-bit)

#### Screenshot / Video
![kzvtks](https://user-images.githubusercontent.com/8905369/31093009-994e1ecc-a7b0-11e7-95ab-366c7c1ca28a.gif)

#### Context / Source
#manual-testing

**Comment by keoshi** [comment]
This PR should resolve this issue: https://github.com/Automattic/wp-calypso/pull/18722
