### ISSUE TITLE
Reader: Posts with no comments showing up in Conversations

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#18454]
Example:
![screenshot 2017-10-02 11 41 07](https://user-images.githubusercontent.com/4924246/31093432-986fdce2-a766-11e7-925b-8f24073d5ee4.png)

Test blog URL:
https://wpcalypso.wordpress.com/read/feeds/47062358

I _think_ there may have been comments under that post in the past which have been removed.

**Comment by aaronyan** [comment]
Tested, and can confirm that deleting a comment will not update the `last_comment_date_gmt` field.

**Comment by aaronyan** [comment]
Posts with no comments will no longer appear in Conversations API (r164121).

**Comment by jancavan** [comment]
Tested and I'm now seeing the empty state. Thanks @aaronyan, good job!
