### ISSUE TITLE
Editor: Hyperlinks to external pages route back to internal site

### ISSUE THREAD

**Issue by graciemae** [Automattic/wp-calypso#1846]
Hyperlinks added to posts or pages in Calypso are not directing to independent links - instead they're adding the link's URL to the end of the URL for the post or page it's being added to. 

Example:

If you intend to link text to facebook.com, the hyperlink instead connects to something like http://test3737373.com/2015/12/18/links/facebook.com for a post and http://test3737373.com/testing-links/facebook.com for a page.

Steps to reproduce:
1. Create a new post or page in Calypso, or edit an already published post/page.
2. Highlight text, click the Hyperlink button, and insert a link to an external site like facebook.com.
3. Preview the post/page, or publish it and view the live post/page.

What I expected: To click the link and it direct to facebook.com, as the link displays in the editor: 

https://cloudup.com/cXwWX6u8WPE

What happened: It instead links to a non-existent page within the site: http://test3737373.com/testing-links/facebook.com

https://cloudup.com/cx6M_pUW6mA

**Comment by kriskarkoski** [comment]
I believe this is the expected link format (link added to end of current of current page URL) when the href doesn't begin with http/https to allow for relative hyperlinks, but this does differ from WP Admin where http:// is prepended to a URL if one isn't added when initially inserting it.

In WP Admin, here's what I entered:

<img width="512" alt="screen shot 2015-12-18 at 11 21 26 pm" src="https://cloud.githubusercontent.com/assets/1900444/11911266/2080f152-a5de-11e5-92b9-41d395d5ab19.png">

But here's how it's added:

<img width="786" alt="screen shot 2015-12-18 at 11 21 34 pm" src="https://cloud.githubusercontent.com/assets/1900444/11911267/28950482-a5de-11e5-9e17-bef8b8d2b667.png">

In Calypso this link is added without any http:// added

**Comment by graciemae** [comment]
Thank you thank you!
