### ISSUE TITLE
Site icon popup formatted incorrectly

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#18460]
#### Steps to reproduce
1. Go to an AT site's admin dashboard
2. Select Settings
3. Select Site Icon

#### What I expected
Seeing a near full-size popup window that contains the Media Library to choose an image from.

#### What happened instead
Popup looks much too small and formatted incorrectly.

#### Browser / OS version
n/a

#### Screenshot / Video
http://prntscr.com/gsheh3

#### Additional notes
It's not just limited AT sites -- it happens with any site where the Media Library appears in a popup (instead of a new page) -- for example, for albertaadvantagepod.com. 
I'm not familiar with why some sites open the Media Library in a new page, and others in a popup window, but for those with the popup, it's broken.

**Comment by hnotess** [comment]
I'm also seeing this bug. Here's my screenshot. 

https://cloudup.com/cqSaHjW751R

When I select "Add New" and try to upload an image, the next thing I see is this tiny box that can't be clicked in:

https://cloudup.com/cnZaXD-jU60

**Comment by sjaved87** [comment]
I have another report of a similar issue in a live chat today:
#672325-HC

**Comment by rachelmcr** [comment]
It looks like the [editor media modal CSS](https://github.com/Automattic/wp-calypso/blob/0345ff083bb0427b49c5101da4971e7efdfc1dbb/client/post-editor/media-modal/index.scss) that was being used to style this media modal is no longer being loaded on this settings page. @stephanethomas is this a side effect of the CSS splitting you did in https://github.com/Automattic/wp-calypso/pull/18194?

**Comment by gemmagarner** [comment]
Reported on Twitter: https://twitter.com/astrorel/status/915157522180444161

**Comment by stephanethomas** [comment]
Thanks for reporting this issue! This is indeed linked to the changes introduced by #18194. I'm working on a fix, but in the meantime one workaround is to load the post editor (e.g. by clicking the `Write` button in the top bar, or editing a post) before changing the site icon.

**Comment by senff** [comment]
Another workaround is doing it through the Customizer → Site Identity.

**Comment by stephanethomas** [comment]
The fix has been deployed. Everything should work normally now :).
