### ISSUE TITLE
Setup global file drop handler 

### ISSUE THREAD

**Issue by iandunn** [Automattic/wp-calypso#18463]
When dragging an image into a browser window, the default behavior is for the browser to navigate to the local image. That doesn't seem desirable in the context of a web application that supports dragging and dropping files for uploads, because it can lead to poor UX.

If someone accidentally drops a file outside of a dropzone, or they drop it before all of the necessary JavaScript has finished loading, then they'll be navigated away from the Editor, Media Library, etc.

It would be better if we loaded a small piece of JavaScript early, so that files dropped in those situations would be caught and nothing would happen. Then, the user can retry once the scripts have finished loading, rather than having to reload the page and start from scratch.

The current dropzones can override that default drop handler when a file is dropped inside one of them and their corresponding scripts have loaded.

Related #16819

**Comment by jblz** [comment]
As I noted in #16819, this is an extra good idea since we're adding a good amount of "dead" dropzone around the title UI which was previously "live":

<img width="1168" alt="screen shot 2017-10-02 at 6 39 04 pm" src="https://user-images.githubusercontent.com/1587282/31102788-a5e5be88-a7a1-11e7-923f-f9fb71b14487.png">

**Comment by designsimply** [comment]
Is overriding a browser default the best solution? I like that a solution is proposed in #18463 based on what you suggested, however, I think it will still be (possibly more) confusing to users if they try to drop an image and nothing happens at all. The problem I find is that the dropzone moves away from where I expect it to be—I think a moving dropzone target is the bigger problem.

Steps to reproduce:

1. Start a new post.
1. Try to quickly drag and drop an image as the first thing in the body of the post.

<strong>Result:</strong> the dropzone moves from where I expect it to be and I (almost always) end up opening the image in the browser directly.

<strong>Video:</strong> [46s](https://cloudup.com/cxfaSqBLvKu)
