### ISSUE TITLE
Media Editor: Double Images, Buttons

### ISSUE THREAD

**Issue by otpidusprime** [Automattic/wp-calypso#18476]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/
2. Select an Image(or any other media)
3. Click on Edit
4. The Media Editor Modal Window shows Double Images and Buttons while Editing an Image and Double Buttons while editing other types of media.

#### What I expected
Everything to appear once.

#### What happened instead
Double Images and Buttons appeared while Editing an Image and Double Buttons while editing other types of media.

Happens on all sites regardless of the Plan.

#### Browser
Chrome 61.0.3163.100

#### Screenshot
While editing an Image:
<img width="570" alt="screen shot 2017-10-03 at 18 03 30" src="https://user-images.githubusercontent.com/29238672/31125332-933a96a4-a865-11e7-97c6-dd32078cbfbc.png">

While editing a Video:
<img width="1323" alt="screen shot 2017-10-03 at 18 05 57" src="https://user-images.githubusercontent.com/29238672/31125340-97620b86-a865-11e7-97ff-6872da5a2bec.png">

**Comment by rachelmcr** [comment]
@stephanethomas This looks like another side effect of https://github.com/Automattic/wp-calypso/pull/18194.

As a workaround, I loaded the post editor first (as mentioned in https://github.com/Automattic/wp-calypso/issues/18460) and then followed the steps in this report and the modal works as expected then.

**Comment by stephanethomas** [comment]
It is, good job Rachel. I've just checked and https://github.com/Automattic/wp-calypso/pull/18477 will fix that issue as well.

**Comment by stephanethomas** [comment]
Thanks @otpidusprime for reporting this issue! This is now fixed.
