### ISSUE TITLE
Free Trials: Add `Gridicon` notice to `SiteIndicator` if the trial is in the grace period

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1848]
This is similar to how we render Jetpack sites in the site-picker when they are on an old version.

Props to @mtias for the idea.

**Comment by fabianapsimoes** [comment]
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.
