### ISSUE TITLE
Jetpack Services: Authorization page

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#18496]
Right now, the authorization page of the Jetpack Connection Flow relies heavily on information that is stored in the redux subtree. With the introduction of new flows, the number of different values that can be stored in there and the cyclomatic complexity of this code went through the roof.

We need to take a step back and review this part of the flow. We need a page that works relying only on whatever it receives as a parameter, including which flow we are in. The flow type should be enough to know what to do next, and which other params we could expect, and make the auth page a totally independent service that works on its own.

For this first version, we will use a different url ( /jetpack/connect/link , maybe? ) so we can start testing and adding the different flows step by step until we have a feature complete replacement of /jetpack/connect/authorize. The first flow we will be porting will be the basic one, where you are shown an "approve" button and, once clicked, you are redirected to the plans page (if you don't have a plan) or to your "my plan" page if you do.

**Comment by sirreal** [comment]
Over the course of [the project](https://github.com/orgs/Automattic/projects/8), I believe the goals in this issue have been achieved.

It's worth mentioning that some of the implementation details from the description were not followed. For example, no new routes were introduced and no old routes have been retired.
