### ISSUE TITLE
Posts and Pages can not be edited when SU'd

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#18507]
When SU'd as user, it's not possible to view/edit Posts and Pages in Calypso. This started happening late yesterday (October 2).

#### Steps to reproduce
1. SU as user
2. Go to Blog Posts or Site Pages
3. Select any Post or Page

#### What I expected
Post or Page can be edited.

#### What happened instead
Title of Post keeps fading in and out, and at the top right it says "Finishing set up…" in a blue box.

#### Screenshot / Video
http://prntscr.com/gsvawy

#### Additional Notes
This only happens when SU. No problems with SSP.

**Comment by hoverduck** [comment]
It looks like what's happening is that the session is losing its SU status when opening the Editor, and it's hanging because I'm trying to open a post as the wrong user.  If I re-SU from the editor page the post loads fine.

We should probably have an error message when attempting to open a post you don't have permissions to rather than just hanging.

**Comment by hoverduck** [comment]
Likely the same issue.  I've removed the Editor label.  Thanks, @supernovia!

**Comment by sstabrizi** [comment]
Just wanted to note a similar issue. When I SU into an account and try to click Settings, I am kicked out of the user account and back to my own. The same message appears that was mentioned above, "Finishing set up…" in a blue box. This only started happening about 3 to 4 days ago. Prior to that, I was able to navigate the user settings without trouble.

**Comment by synora** [comment]
I just wanted to note that I am experiencing the issue as well. @sstabrizi and I are trial HEs.

**Comment by stephanethomas** [comment]
https://github.com/Automattic/wp-calypso/pull/18614 has just been deployed, and should fix that issue.

**Comment by senff** [comment]
Looks like it's working again!
