### ISSUE TITLE
Jetpack Manage: improve notifications when disconnecting a site

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1851]
When disconnecting a site from Jetpack on Calypso, there is a small annoying step for users. Here's what the current disconnect process looks like:

1. Go to the Settings page for a site here: https://wordpress.com/settings/general/example.com
2. Click on 'Disconnect Jetpack':
![screen shot 2015-12-18 at 7 45 43 pm](https://cloud.githubusercontent.com/assets/11487924/11910200/f8a4bc22-a5bf-11e5-88c8-072a08c4fac4.png)
3. Click Disconnect on the pop up:
![screen shot 2015-12-18 at 7 46 14 pm](https://cloud.githubusercontent.com/assets/11487924/11910203/066238d0-a5c0-11e5-8f5e-120d224c48d7.png)
4. I get this warning message from the browser:
![screen shot 2015-12-18 at 7 46 35 pm](https://cloud.githubusercontent.com/assets/11487924/11910209/19a74214-a5c0-11e5-9666-50e57a4d6f2e.png)
5. Click Ok
6. I am redirected to the all sites stats page, and see a success message:
![screen shot 2015-12-18 at 7 47 07 pm](https://cloud.githubusercontent.com/assets/11487924/11910216/3459bf1a-a5c0-11e5-8bd4-842a5b1460c9.png)

I expected: no warning about leaving the page in steps 4-5.

**Comment by lancewillett** [comment]
This one looks fixed. Yay!

Using same steps above, there was no more warning in the browser. Testing with Mac-n-Chrome.

![screen shot 2016-04-21 at 15 33 29](https://cloud.githubusercontent.com/assets/66797/14726362/81e4254a-07d6-11e6-98b5-a8d8492b1957.png)

![screen shot 2016-04-21 at 15 33 33](https://cloud.githubusercontent.com/assets/66797/14726364/85c6bc86-07d6-11e6-9f12-b39c08cdac76.png)

![screen shot 2016-04-21 at 15 33 36](https://cloud.githubusercontent.com/assets/66797/14726365/8b61f0b6-07d6-11e6-8235-96fce5c05760.png)
