### ISSUE TITLE
Jetpack: I don't want to disconnect my site when there are connection issues

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1852]
Fairly often on my Jetpack site I get a cannot connect error. The only action is "disconnect site" which is never what I want to do. Is there another option that can go here that is less drastic and might help me get it connected again?

![screen shot 2015-12-18 at 7 51 17 pm](https://cloud.githubusercontent.com/assets/11487924/11910239/c5a21f44-a5c0-11e5-88c4-159f2e0041d9.png)

Some suggestions:
- let's make sure that we only display this error when it's correct: wait for polling requests to fail at least twice before showing the error message
- link to documentation about connection issues or support

**Comment by v18** [comment]
From @lezama: this error fires when we try to fetch update information and the request fails, as we are not polling plugins anymore, I think this is the only action that now tries to access a Jetpack site while not trying to write to it. The solution for this is to start using the update information that we are syncing to shadow sites since 3.4. Remember the rule, read from wpcom, write to Jetpack.

**Comment by lancewillett** [comment]
Is this still happening? I haven't seen this error recently for my Jetpack connected sites.

**Comment by lancewillett** [comment]
Feel free to re-open if it happens with frequency in the future.
