### ISSUE TITLE
Stats showing strange titles on Calypso

### ISSUE THREAD

**Issue by StefMattana** [Automattic/wp-calypso#18530]
The user on 717146-zen lamented they see weird titles displaying on Calypso on their Android App and mobile Chrome browser. I SSP'ed on a desktop Chrome and I can see the same issue: 

<img width="969" alt="screen shot 2017-10-04 at 15 31 56" src="https://user-images.githubusercontent.com/11662998/31182087-d9124bda-a91a-11e7-88ea-d2f29cc23567.png">

[This is the user's screenshot](https://photos.app.goo.gl/gAneHwtFmiDvhE7H3) - they uses Wordpress.com in Chrome Browser on Android smartphone. 

The stats on wp-admin look good though: 

<img width="1070" alt="screen shot 2017-10-04 at 15 32 38" src="https://user-images.githubusercontent.com/11662998/31181639-bb94ed7a-a919-11e7-8fb6-67036715691d.png">

Going to ask the user if they have done anything in particular (es plugin update etc) just to rule out anything else. 

If you have any more ideas, please let me know. Thanks!

Site: http://www.lionsvalleyathletics.com
Ticket: 717146-zen
NA: https://wordpress.com/wp-admin/network/users.php?s=dusmithy

**Comment by ntpixels** [comment]
The user has confirmed in a [follow-up ticket](https://woothemes.zendesk.com/agent/tickets/753791) that this is indeed only happening on WordPress.com:

> I just checked the wp-admin stats and the names of all pages are coming up correct. I guess it is only happening in Wordpress.com.

**Comment by richardmtl** [comment]
This is a Jetpack sync issue, working on it, closing.
