### ISSUE TITLE
Store: Review notification

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#18549]
Right now you can get a normal comment notification for a review (since WooCommerce treats these as no different to a normal comment or a post).

As part of our notifications work, we should hook into the comment builder (`wp-content/lib/notes/class.notification-builders-v1-1.php` see `build_comment`) , and make our own version of the notification with some adjusted copy to make it clearer these comments are product reviews.

**Comment by justinshreve** [comment]
A patch for this is now up at D8337-code. It adjusts the copy and display of the comment notification that is already generated.

Here are a few screenshots of what I have so far:

Desktop

<img width="404" alt="screen shot 2017-11-16 at 2 31 49 pm" src="https://user-images.githubusercontent.com/689165/32920923-2b8cefb4-cae0-11e7-9e0a-f57bb1edcf4d.png">

<img width="398" alt="screen shot 2017-11-16 at 2 31 38 pm" src="https://user-images.githubusercontent.com/689165/32920936-3a2522da-cae0-11e7-9b28-fa807c685bdb.png">

iOS

<img width="598" alt="screen shot 2017-11-16 at 3 10 40 pm" src="https://user-images.githubusercontent.com/689165/32920958-5a5d1a9e-cae0-11e7-9b45-ed42805cbefa.png">

Could use some design feedback. I had something slightly different originally but needed to make some changes to make sure things worked mostly consistently across iOS & desktop. The rating display is currently using emoji, but we could generate some images for stars and load those instead.

cc @kellychoffman @timmyc @jameskoster

**Comment by kellychoffman** [comment]
> The rating display is currently using emoji, but we could generate some images for stars and load those instead.

Are we allowed to use gridicons here? Asking because this would allow us to denote 4 stars out of 5 using the stars + start-outline. 

<img width="95" alt="screen shot 2017-11-16 at 5 08 45 pm" src="https://user-images.githubusercontent.com/5835847/32922743-f7c7079e-caf0-11e7-99e9-1b8f32c9e74b.png">

I'm also thinking the 'Review for' and the 'Rating' need to be above the comment for better context.

**Comment by justinshreve** [comment]
I don't think the Gridicons will work. I remember having issues with it in the expanded view of the order notification (the one being displayed there is an image), and it just came up as a question mark box.

However, we can have 5 separate images, and just load the correct one based on the rating.

i.e.

rating-1.png

![1_star](https://user-images.githubusercontent.com/689165/32924154-231d710e-caf0-11e7-8423-457a8a5ffb6d.png)

and so forth.

Would that work?

**Comment by kellychoffman** [comment]
Yep, that totally works.

**Comment by jameskoster** [comment]
Eeesh using an image makes me a sad panda. I think I'd actually prefer emoji to images but it's a minor point.

Assuming we go with images, we should be sure to make it fully transparent to account for any potential changes in background color.

**Comment by kellychoffman** [comment]
I don't feel strongly about the images, I just wanted to be consistent with other areas of Calypso that use the gridicon stars.

**Comment by justinshreve** [comment]
So it turns out that images don't work well either. They get forced aligned center on mobile. 

However, Normal unicode characters seem to be working OK on desktop and mobile, which has a filled and unfilled star. Unfortunately I don't have much power over the color, but with the stars linked, it's a lot closer to the rest of Calypso than the emoji.

<img width="435" alt="screen shot 2017-11-17 at 2 13 40 pm" src="https://user-images.githubusercontent.com/689165/32971372-d4010a9c-cba1-11e7-96f8-046de5005ab1.png">

**Comment by kellychoffman** [comment]
Ding ding ding. We have a winner!

**Comment by timmyc** [comment]
Okay here are some screen grabs from Android-land:

![screenshot_20171123-115340](https://user-images.githubusercontent.com/22080/33187464-acd92c02-d046-11e7-96e9-1e30ddefcd32.png)

![screenshot_20171123-115257](https://user-images.githubusercontent.com/22080/33187470-b634c23e-d046-11e7-90c5-d6faa94fc4ab.png)

Not sure why the default gravatar is not showing up... and the underlining of "Review For" prior to the linked product name looks a little odd.

**Comment by justinshreve** [comment]
@timmyc Thanks for testing.

I fixed up the display of the review for area and tested with an Android emulator (which was annoying to setup, but made testing tweaks there easier :P).

I can't seem to solve the Gravatar issue. The Gravatar displays on Android if one is set, but the mystery man fallback will not.

This seems to be an issue with regular comment notifications as well:

![photo_2017-11-27_14-05-31](https://user-images.githubusercontent.com/689165/33291870-27567f38-d37c-11e7-86b0-7ac66f94dbac.jpg)

![photo_2017-11-27_14-05-58](https://user-images.githubusercontent.com/689165/33291895-39c6f8aa-d37c-11e7-90d0-688a8df10ac2.jpg)

I think that is worth a bug report to Android because it's definitely odd. But I don't think it's a blocker for this, since reviews already come in as comments and have the same problem. 

If that sounds OK to you, do you mind giving the latest revision a 👍?

**Comment by timmyc** [comment]
I agree regarding the gravatar issue, that should just be reported upstream. So the latest iteration is looking great to me - here is the notif:

![edit_media_ _testing_timmy_timmay_timmaay_timmaaay_timmaaaay_timmaaaaay_timmaaaaaay_timmaaaaaaay_timmaaaaaaaay_timmaaaaaaaaay_timmaaaaaaaaaay_ _wordpress 3](https://user-images.githubusercontent.com/22080/33298187-c39cf9c2-d399-11e7-8774-afe2c9e7cb72.png)

I did notice something a bit odd though - the lock-screen version of the notification is still showing as a Comment:

![edit_media_ _testing_timmy_timmay_timmaay_timmaaay_timmaaaay_timmaaaaay_timmaaaaaay_timmaaaaaaay_timmaaaaaaaay_timmaaaaaaaaay_timmaaaaaaaaaay_ _wordpress](https://user-images.githubusercontent.com/22080/33298194-d677a628-d399-11e7-851e-a822af0e13d8.png)

In the list-view of the App, things look fine:

![edit_media_ _testing_timmy_timmay_timmaay_timmaaay_timmaaaay_timmaaaaay_timmaaaaaay_timmaaaaaaay_timmaaaaaaaay_timmaaaaaaaaay_timmaaaaaaaaaay_ _wordpress 2](https://user-images.githubusercontent.com/22080/33298205-dfaa0e0c-d399-11e7-995e-cc7e19d18b4d.png)

I wonder if there is some other code that triggers the push notification that runs on a job server, and as such still send the initial push notif as a comment. Seems like the easiest way to test this assumption is to merge in the diff and give it a try :)

**Comment by timmyc** [comment]
Also just noticed that the default gravatar works on the push notif too

**Comment by justinshreve** [comment]
Yeah merging the diff should correct the push notification. We only see the new content in the app since `public-api.wordpress.com` is sandboxed, but the notification is being sent with production code.

**Comment by justinshreve** [comment]
This has been launched in r166039-wpcom.
