### ISSUE TITLE
Editor: Deleted Post dialog flashes on screen and disappears after trashing a post

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#18545]
1. Starting at URL: https://wordpress.com/post/
2. Begin drafting a post and wait for the first auto-save
3. When the button for MOVE TO TRASH appears, click it
4. Click [Move to trash] in the “Are you sure” dialog that appears
5. A new dialog with important looking buttons will appear but so briefly that it can’t be understood
6. https://wordpress.com/posts/ will load

#### What I expected

I expected my post to simply be deleted and then to be returned to /posts.

#### What happened instead

A “Deleted Post” dialog flashed on screen so rapidly I was unable to read it or interact with it and then it disappeared.

#### Screenshot / Video

https://cloudup.com/cPsANEf7zKB

![e2b1a263-6b49-4452-bf1b-27334f306e29](https://user-images.githubusercontent.com/545779/31195289-68e971a4-a90f-11e7-8e90-06699a3790cd.png)

#### Context / Source

This popped up for me in #reallife usage.

**Comment by jeremeylduvall** [comment]
I think this is the same issue described in #18398. I was planning on taking a peek tomorrow morning.

**Comment by ianstewart** [comment]
I think you're right. I'll close this one as a duplicate and link to it there.
