### ISSUE TITLE
Store: Investigate why /wp/v2/comments is timing out

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#18540]
I was going to use `POST /wp/v2/comments` to create admin review replies, but this seems to be hitting the Jetpack API's 5 second timeout.

I've switched the code to temporarily use the WordPress.com endpoint, but we should do some investigation into why this is timing out.

Note: This also seems to be inconsistent. It works on some sites, but is timing out on others. The reply often goes through too, but fails before response.

See p7bje6-xU-p2 for some previous history on this with the products endpoint.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
