### ISSUE TITLE
Update references in documentation to deprecated features

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#18556]
We are removing deprecated features from Calypso and should also remove it from our own documentation so that we don't accidentally encourage their use.

1. [ ] React.createClass: https://github.com/Automattic/wp-calypso/pull/19093
2. [x] this.translate: https://github.com/Automattic/wp-calypso/pull/18623

## `createClass`

A quick look provides these results:

```shell
ack -l 'createClass' --markdown client server
```

- [ ] client/components/data/cart/README.md
- [ ] client/components/data/checkout/README.md
- [ ] client/components/data/domain-management/dns/README.md
- [ ] client/components/data/domain-management/email/README.md
- [ ] client/components/data/domain-management/email-forwarding/README.md
- [ ] client/components/data/domain-management/nameservers/README.md
- [ ] client/components/data/domain-management/README.md
- [ ] client/components/data/domain-management/site-redirect/README.md
- [ ] client/components/data/domain-management/transfer/README.md
- [ ] client/components/data/domain-management/whois/README.md
- [ ] client/components/data/media-library-selected-data/README.md
- [ ] client/components/data/media-list-data/README.md
- [ ] client/components/data/media-validation-data/README.md
- [ ] client/components/data/query-site-domains/README.md
- [ ] client/components/date-picker/README.md
- [ ] client/components/external-link/README.md
- [ ] client/components/faq/README.md
- [ ] client/components/feature-example/README.md
- [ ] client/components/gallery-shortcode/README.md
- [ ] client/components/image-preloader/README.md
- [ ] client/components/infinite-list/README.md
- [ ] client/components/input-chrono/README.md
- [ ] client/components/logged-out-form/README.md
- [ ] client/components/olark-chatbox/README.md
- [ ] client/components/post-schedule/README.md
- [ ] client/components/root-child/README.md
- [ ] client/components/section-nav/README.md
- [ ] client/components/segmented-control/README.md
- [ ] client/components/select-dropdown/README.md
- [ ] client/components/shortcode/README.md
- [ ] client/components/spinner/README.md
- [ ] client/components/timezone/README.md
- [ ] client/components/token-field/README.md
- [ ] client/components/track-input-changes/README.md
- [ ] client/components/upgrades/credit-card-number-input/README.md
- [ ] client/components/upgrades/google-apps/README.md
- [ ] client/components/version/README.md
- [ ] client/devdocs/design/README.md
- [ ] client/lib/ads/README.md
- [ ] client/lib/email-followers/README.md
- [ ] client/lib/followers/README.md
- [ ] client/lib/keyboard-shortcuts/README.md
- [ ] client/lib/mixins/data-observe/README.md
- [ ] client/lib/mixins/infinite-scroll/README.md
- [ ] client/lib/mixins/url-search/README.md
- [ ] client/lib/olark-events/README.md
- [ ] client/lib/olark-store/README.md
- [ ] client/lib/plugins/README.md
- [ ] client/lib/react-pass-to-children/README.md
- [ ] client/lib/signup/README.md
- [ ] client/lib/users/README.md
- [ ] client/my-sites/plan-price/README.md
- [ ] client/my-sites/sites/README.md
- [ ] client/post-editor/editor-fieldset/README.md
- [ ] client/signup/README.md
- [ ] client/state/push-notifications/README.md

**Comment by sirreal** [comment]
As far as I can tell, `/this\.(translate|moment|numberFormat)/` has been cleaned from docs. Checked off that item.

**Comment by samouri** [comment]
All remaining usages are being fixed in https://github.com/Automattic/wp-calypso/pull/22004.
Closing
