### ISSUE TITLE
Jetpack: drafts from Jetpack sites sometimes don't show up under All My Sites -> Drafts

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1856]
Steps to reproduce:

1. Connect a Jetpack site to WordPress.com
2. Make sure that site has a Post saved as a Draft
![screen shot 2015-12-18 at 8 24 53 pm](https://cloud.githubusercontent.com/assets/11487924/11910477/6a5f7136-a5c5-11e5-91b1-e20f53f47703.png)
3. You can view it from that site's Blog Posts > Drafts without any issue
![screen shot 2015-12-18 at 8 25 52 pm](https://cloud.githubusercontent.com/assets/11487924/11910482/8f8d898e-a5c5-11e5-9db6-768ef08dd4c8.png)
4. Click "Switch Site" and "All my Sites"
5. The draft is not longer showing up in Drafts
![screen shot 2015-12-18 at 8 26 29 pm](https://cloud.githubusercontent.com/assets/11487924/11910484/a98d96ee-a5c5-11e5-8101-e469e0198599.png)

**Comment by lancewillett** [comment]
Testing this again, able to repeat, but Jetpack sites' drafts are visible **sometimes** in Calypso.

1. Created new Jetpack site, connected it to WP.com.
2. Drafted a post in Jetpack site, saved it.
3. Drafted a post on the same site, but starting in Calypso (saved it).
4. Going to https://wordpress.com/posts/lancetest35.mystagingwebsite.com only shows Published posts — not either of the two drafts (and no section nav is visible)
5. "Hacking" the URL enables me to see the drafts (adding in `/drafts/`): https://wordpress.com/posts/drafts/lancetest35.mystagingwebsite.com
6. Same as original report, going to Switch Site, All My Sites, Drafts does not show the Jetpack site's blog post drafts.

**Pages** work a bit the same — not visible from All My Sites page drafts list — but they _do_ appear in in the single Jetpack site pages list, under Drafts: https://wordpress.com/pages/drafts/lancetest35.mystagingwebsite.com

![screen shot 2016-04-21 at 14 57 52](https://cloud.githubusercontent.com/assets/66797/14725709/838cc1d0-07d2-11e6-811d-f1518d42edd5.png)
![screen shot 2016-04-21 at 14 59 00](https://cloud.githubusercontent.com/assets/66797/14725710/83922544-07d2-11e6-914c-23d1fabfd946.png)
<img width="520" alt="screen shot 2016-04-21 at 14 59 11" src="https://cloud.githubusercontent.com/assets/66797/14725711/83946822-07d2-11e6-8fde-2440c2e5eb96.png">
![screen shot 2016-04-21 at 14 59 39](https://cloud.githubusercontent.com/assets/66797/14725712/8396fa38-07d2-11e6-8690-7293d908660c.png)
![screen shot 2016-04-21 at 15 04 35](https://cloud.githubusercontent.com/assets/66797/14725713/83983826-07d2-11e6-877b-efd6572614bc.png)

Note: post drafts **do** appear in the drafts "drawer" visible from the left sidebar of the editor in Calypso.

**Comment by lancewillett** [comment]
I feel like this is minor — and we can re-open if users report it again it the future.
