### ISSUE TITLE
Layout: match Masterbar height with the one on the front-end / wp-admin

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#18561]
The Masterbar changes height depending on where you are; Inside Calypso it gets a little taller at 47px, outside Calypso (site frontend, wp-admin +/- jetpack, etc) it shrinks down to 32px.

<img width="774" alt="screen-shot-2017-09-29-at-3-35-47-pm" src="https://user-images.githubusercontent.com/23619/31223545-f3db28d2-a9ca-11e7-8cbd-b0f20b909076.png">

On mobile, the Masterbar is consistently 47px on WordPress.com to allow for bigger touch targets.

<img width="776" alt="screen-shot-2017-09-29-at-3-45-31-pm" src="https://user-images.githubusercontent.com/23619/31223557-fd08018c-a9ca-11e7-87ba-311ea862a693.png">

The height discrepancy is most noticeable when transitioning between your site’s frontend and Calypso:

![masterbar-height-changes](https://user-images.githubusercontent.com/23619/31223573-0d732560-a9cb-11e7-942d-7515e0ac9f71.gif)

So let's make the Calypso Masterbar 32px tall:

<img width="776" alt="screen-shot-2017-09-29-at-3-59-00-pm" src="https://user-images.githubusercontent.com/23619/31223641-3b320f84-a9cb-11e7-8fc8-18d97ff400e3.png">

Doing so will get us a more consistent experience when switching between the frontend and Calypso:

![height-tweaks](https://user-images.githubusercontent.com/23619/31223649-414ec060-a9cb-11e7-86de-15bc5c22c5bd.gif)

Props @shaunandrews. 

Note that there is a `$masterbar-height` variable in CSS. However, it isn't used consistently, so changing the Masterbar height involves fixing the height in a few places that wouldn't necessarily be obvious. In addition, several components _seem_ to use the Masterbar height as a top offset / padding / margin — these would ideally use the variable as well, but need to be checked on a case-by-case basis.

**Comment by Visovsiouk** [comment]
@lsinger Can I try to tackle this?

**Comment by lsinger** [comment]
@Visovsiouk feel free! :)

**Comment by Visovsiouk** [comment]
@lsinger Should I still keep $masterbar-height at 47px height on <783px screen width, or should I stick to 32px all the way?

**Comment by lsinger** [comment]
@shaunandrews can you take a look? ☝️

**Comment by shaunandrews** [comment]
wp-admin switches to the taller (more mobile-friendly) toolbar around 768px. So I guess we should start by mimicking that behavior — is 783px one of Calypso's defined breakpoints?

**Comment by lsinger** [comment]
As far as I know we use [this viewport module here](https://github.com/Automattic/wp-calypso/tree/master/client/lib/viewport). I think the below code (from there) sums it up quite succinctly: 

```JavaScript
function isMobile() {
	return isWithinBreakpoint( '<480px' );
}

function isDesktop() {
	return isWithinBreakpoint( '>960px' );
}
```

So far I've only ever seen `isMobile` and `isDesktop` being used in Calypso.

**Comment by lsinger** [comment]
🤔 — the sidebar column becomes a row at about 650px (and below), seemingly in contrast with the above.

**Comment by Visovsiouk** [comment]
As far as I've seen, there's no defined breakpoint at 783px, Can you point me as to where to declare it?

**Comment by lsinger** [comment]
I think [this is the place](https://github.com/Automattic/wp-calypso/blob/master/client/layout/style.scss#L59) where we make the sidebar take up the whole page width, or in other words, switch to a mobile layout. Maybe do exactly that for now and see how it feels. We might also later decide to switch to [the tablet breakpoint](https://github.com/Automattic/wp-calypso/blob/master/client/layout/style.scss#L38). One of the two should work I would guess.

**Comment by lsinger** [comment]
We've decided to not go forward with this one for now. Closing.
