### ISSUE TITLE
Jetpack: Site Icon still trying to be loaded even after it's been removed

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1857]
Steps to reproduce:

1. Add a Site Icon through the self-hosted site's customizer at /wp-admin/customize.php?autofocus[control]=site_icon
2. Visit https://wordpress.com/ and check my self-hosted site to confirm the Site Icon appears there
3. Open the customizer again and remove the Site Icon. Confirm it no longer appears as the site's favicon in the browser.
4. Revisit https://wordpress.com/. Result: site icon still appears there, even after a hard refresh
5. Permanently delete the site icon image from my self-hosted site's media library.
6. Revisit https://wordpress.com/. Result: site icon still appears there, even after a hard refresh

I expected: Jetpack to be aware of the changes to the site icon, and to display the icon correctly (whether it exists or not)

**Comment by lancewillett** [comment]
Confirmed this is still broken, using the same steps as above.

Adding the new icon:
![screen shot 2016-04-21 at 15 11 46](https://cloud.githubusercontent.com/assets/66797/14725981/eac3f0f2-07d3-11e6-8b77-35b526ffa1df.png)

Saved in wp-admin UI of the Jetpack site:
![screen shot 2016-04-21 at 15 11 51](https://cloud.githubusercontent.com/assets/66797/14725988/f5c4ca4e-07d3-11e6-9042-ea4ac94f7f82.png)

Appearing correctly in Calypso immediately:
![screen shot 2016-04-21 at 15 12 20](https://cloud.githubusercontent.com/assets/66797/14725992/0272860a-07d4-11e6-9428-82ab604d338c.png)
<img width="415" alt="screen shot 2016-04-21 at 15 12 40" src="https://cloud.githubusercontent.com/assets/66797/14725991/0272096e-07d4-11e6-8f59-a162b13c9e77.png">

Removed from wp-admin on Jetpack site:
<img width="426" alt="screen shot 2016-04-21 at 15 16 36" src="https://cloud.githubusercontent.com/assets/66797/14726002/18196348-07d4-11e6-826c-ff05e910e0d1.png">

Still showing up in Calypso site list:
<img width="468" alt="screen shot 2016-04-21 at 15 17 04" src="https://cloud.githubusercontent.com/assets/66797/14726009/23854c24-07d4-11e6-8d89-d8a792f35e97.png">

**Comment by rralian** [comment]
As mentioned in #3045 I've dug a bit and tested jetpack and wpcom sites by uploading a site icon and I don't see the new icon showing up in our API responses. Looking into the API to figure out why.

**Comment by lamosty** [comment]
Still broken. I'm investigating why.

**Comment by lancewillett** [comment]
Brief notes from a chat with @lamosty — who is continuing to investigate this on the Jetpack side.

> This issue could be due to the fact that the `jetpack_site_icon_url` option is not updated with an empty string after the site icon is removed. In the WP.com REST API we check for that option when displaying the image for Jetpack sites. This seems to be working fine when changing icons but not when removing them.

**Comment by lamosty** [comment]
I reported the issue on Jetpack GitHub pages: [here](https://github.com/Automattic/jetpack/issues/3969).
