### ISSUE TITLE
Conversations Tracks: add calypso_reader_comment_permalink_click

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#18585]
Add the tracks event calypso_reader_comment_permalink_click when a comment permalink is clicked. Comment permalinks are the timestamps next to a comment. If clicked, it directs the page to the comment on the front-end site.

**Comment by aaronyan** [comment]
We need to add this to FullPost too!

**Comment by samouri** [comment]
@aaronyan can this be closed?

**Comment by aaronyan** [comment]
Yep! Thanks for the reminder.
