### ISSUE TITLE
Sites: Add option to start a new self-hosted site

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1858]
If `/sites` is going to show WordPress.com sites as well as self-hosted, Jetpack-connected sites, the Start a New WordPress button should also offer the choice to create a self-hosted, Jetpack-connected site through a recommended host:

![screen shot 2015-12-18 at 9 06 26 pm](https://cloud.githubusercontent.com/assets/11487924/11910726/3b6239e4-a5cb-11e5-81a2-9b83daed952b.png)

Right now the 'Start a New WordPress' link goes straight to the WordPress.com signup, but creating a new WordPress,as the button says, doesn't necessarily have to be on WP.com.

Maybe we can change the wording on the button if the user has 1 or more JP sites connected?

**Comment by lancewillett** [comment]
This is different now after lots of reworking. `/sites` no longer has the add call to action. It now lives in the sidebar as "Add Site."

<img width="348" alt="screen shot 2017-02-04 at 16 41 16" src="https://cloud.githubusercontent.com/assets/66797/22622492/df6d8c6e-eaf8-11e6-8ca1-ddb9a8092291.png">

<img width="685" alt="screen shot 2017-02-04 at 16 41 26" src="https://cloud.githubusercontent.com/assets/66797/22622493/e14dbdec-eaf8-11e6-8df4-c7abe7240e80.png">
