### ISSUE TITLE
Components: search icon and text overlap

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#18599]
#### Steps to reproduce
1. Use a site with lots of categories.
2. Go into post editor, and open Settings to see the sidebar menus.
3. Try to search for categories.
4. You'll see the visual issue there.

I could also repeat this when making a link from the post editor, the "Link to existing content" search area has the same issue.

I search for `search` at https://wpcalypso.wordpress.com/devdocs/design (the design components) but didn't see a case of this exact component; if anyone knows how to find it in the list of design components I'd appreciate it.

#### What I expected
For the "Search" text to be spaced correctly from the "Search" icon.

<img width="724" alt="screen shot 2017-10-05 at 13 26 15" src="https://user-images.githubusercontent.com/66797/31250788-ce642c1a-a9d0-11e7-89de-67d42c6c5e8f.png">

#### What happened instead
The text is overlapping the icon. Tested in Safari and Chrome on macOS.

#### Screenshot / Video
<img width="294" alt="screen shot 2017-10-05 at 13 21 08" src="https://user-images.githubusercontent.com/66797/31250811-da5a8924-a9d0-11e7-9b07-3a6682d42397.png">
<img width="420" alt="screen shot 2017-10-05 at 13 21 44" src="https://user-images.githubusercontent.com/66797/31250813-da987c0c-a9d0-11e7-907a-20ad4c8f6f65.png">

Found via #reallife usage posting to my simpledream blog.

**Comment by folletto** [comment]
I thought it was using the same search component, but apparently it's not the case: it's the [PostSelectorSearch](https://github.com/Automattic/wp-calypso/blob/b855b7a8a7e9f6a24e4fc87e8fe251cfd10603fd/client/my-sites/post-selector/search.jsx) component, which is a very basic wrapper with icon and input.

I checked quickly and a `padding-left: 30px` on the input box should solve it.

**Comment by lancewillett** [comment]
https://wpcalypso.wordpress.com/devdocs/blocks/post-selector

<img width="1028" alt="screen shot 2017-10-09 at 06 55 47" src="https://user-images.githubusercontent.com/66797/31341647-0054b58c-acbf-11e7-9a64-9ebe1609e3a0.png">

If that's the correct component, it seems "not broken" in DevDocs display, so our visual regression tests wouldn't have caught it. CC @rachelmcr 

![screen shot 2017-10-09 at 06 58 35](https://user-images.githubusercontent.com/66797/31341726-43d2ca74-acbf-11e7-8b72-13e7ca0b2757.png)

**Comment by frontdevde** [comment]
Fixed by #18689
