### ISSUE TITLE
Conversations Tracks: add Tracks events for follow/mute posts

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#18598]
Add the Tracks event `calypso_reader_conversations_post_followed` and `calypso_reader_conversations_post_muted` whenever a user follows/mutes a post. Followed posts appear in the Conversations Tool.

**Comment by bluefuton** [comment]
@aaronyan do we need a `railcar` here? And should we pass along a `follow_source` like we do for the regular follow button?

**Comment by aaronyan** [comment]
Having the `railcar` would be great! I just tested out the follow button after opening full post on a /read/search recommendation, and

**Comment by aaronyan** [comment]
No need for `railcar` or `follow_source`. Thank you though.

**Comment by aaronyan** [comment]
Because we have multiple places to explicitly follow conversations, let's add in `follow_source` please! It will help differentiate where the user follows a conversation.
