### ISSUE TITLE
Jetpack Manage: Plugins actions from wp-admin should be immediately visible on plugins list in Calypso

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1859]
Currently we are not refetching plugins on a regular basis.
Once they are loaded we don't ever try to reload them until the user refreshed the page.

As an example, here are steps to reproduce with deleting a plugin:
1. Add the Akismet plugin to a Jetpack site
2. See that the Akismet plugin shows up in https://wordpress.com/plugins/example.com
3. Go to wp-admin for the Jetpack site and delete Akismet
4. See that the Akismet plugin still shows up in https://wordpress.com/plugins/example.com (the page is not automatically reloaded)
5. When the page is refreshed, the Akismet plugin no longer shows up (as expected)

It would be great if we started to reliably sync plugin details to WP.com, and then we can more reliably refresh that list more often (or at some point, get a live, real-time updating pipe happening, which would just update based on getting new data via sync)

Here are the actions for which we should catch:
- delete plugin on remote site
- hook catches deletion and syncs back list of active plugins to wp.com
- updated list is stored in wp.com
- update triggers update in real-time pipe
- calypso sees update and UI changes immediately

**Comment by hoverduck** [comment]
28Apr16 Bug Scrub:

Confirmed this is still an issue, I had to refresh the entire page to see new information on my plugin status.

**Comment by rralian** [comment]
@lezama can you confirm the priority of this issue, and help us figure out who should tackle it? If it's a high priority, we should get it into an existing milestone to be worked on.

**Comment by lancewillett** [comment]
Removing from high priority as no action in a month or so.
