### ISSUE TITLE
Comments: refine animation for revealing user info

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#18596]
When revealing the user info panel on an expanded comment, the scaling animation feels a bit off. 

![wonky animations](https://user-images.githubusercontent.com/161697/31248874-27d74a72-a9ca-11e7-9b50-c6dd52f86746.gif)

Could we either:
- Remove the animation 
- Or change the animation to expand the content area and quickly fade the user info in 

@folletto - Out of curiosity is there any standard animation for revealing content in Calypso?

**Comment by folletto** [comment]
> Out of curiosity is there any standard animation for revealing content in Calypso?

I think the only one "standard" is the one on the [FoldableCard](https://wpcalypso.wordpress.com/devdocs/design/foldable-card) which adds margin on top and bottom (it's not visible in the devdocs tho as it's not a list there).

So... we don't. I'd loop in @shaunandrews as our ambassador for animations 🌟

**Comment by shaunandrews** [comment]
The scaling/stretching thing thats happening is less than ideal, fur sure. We should ditch that for now. A delay (to wait for the card to expand in height) with a fade-in would be better all around.

I do find the expanding-card-within-expanding-card thing strange. What if we used a popover instead?

<img width="791" alt="screen shot 2017-10-09 at 1 00 55 pm" src="https://user-images.githubusercontent.com/191598/31349610-f0b293c8-acf1-11e7-9b20-efa85fd7414f.png">

**Comment by folletto** [comment]
That's a nice idea 👍
