### ISSUE TITLE
Conversations: Posting Comment Flow

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18595]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/read/conversations
2. Post a comment to an existing post.

#### What I expected

When I hit "SEND" I expected the comment form to disappear and the comment to appear as a posted comment above (like what happens on Fullpost). 

#### What happened instead

The comment just disappears. My avatar appears in the caterpillar, but that's easy to miss (and not what should happen, since the caterpillar should be just comments that came before). The page also gets a "new post" pill, but I thought that meant a new post (not a new comment). Basically, to the user, it looks like the comment just got eaten.

#### Browser / OS version

Safari 11.0, Mac OSX 10.12.6

#### Screenshot / Video

https://cloudup.com/csBpqkvx9Zi

**Comment by bluefuton** [comment]
Fixed in #18806. 🎉
