### ISSUE TITLE
Settings: change Related Posts text to clarify meaning

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#1860]
On the Settings page: https://wordpress.com/settings/general/example.com , the Related Posts radio button text can be confusing:

![](https://cloud.githubusercontent.com/assets/5512652/5321501/d82db648-7c89-11e4-9632-3d6dd9965c83.png)

Here are a couple of suggestions for making it better:

Suggestion 1:

![](https://cloud.githubusercontent.com/assets/5512652/5327224/375a60a6-7d13-11e4-9d76-09226d8f862c.png)

Suggestion 2:

Change the 2 main radios to something like:

Don't show related content
Show related content on posts

**Comment by lancewillett** [comment]
Would love another opinion here — why is the current text confusing? I vote to close as 'works for me' and improve it later in future iterations as needed.
