### ISSUE TITLE
Guided Tours: Alone Quit button in Continue looks non-clickable

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#18619]
<img width="472" alt="screen shot 2017-10-06 at 14 30 02" src="https://user-images.githubusercontent.com/156676/31278723-6ca54ece-aaa6-11e7-923f-320bb140a065.png">

The alignment and styling don't strongly evoke that you are looking at a button, a clickable control.

For reference, adding the design overview for Guided Tour step:

<img src="https://cldup.com/QBoRhc-P0M.png" width="515" height="364" />

**Comment by lsinger** [comment]
@shaunandrews thoughts?

**Comment by shaunandrews** [comment]
Sure, I think the quit button could use a little more affordance. What if we add a subtle border around it?

![slice 3](https://user-images.githubusercontent.com/191598/37107074-5b1e3936-2201-11e8-833b-ba127351993a.png)
