### ISSUE TITLE
Domains: Refreshing the DNS editor view breaks it

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#18639]
#### Steps to reproduce
1. Navigate to the DNS editor view for your custom domain: `/domains/manage/:domain/dns/:site`
2. No errors in console, DNS records load properly.
3. Refresh the page.

#### What I expected
The DNS editor to show.

#### What happened instead
Stuck in loading state.

Also, the console has these two errors:
```
warning.js:33 Warning: Failed prop type: The prop `domains` is marked as required in `Dns`, but its value is `undefined`.
    in Dns (created by Localized(Dns))
    in Localized(Dns) (created by StoreConnection)
    in StoreConnection (created by DnsData)
    in DnsData (created by Connect(DnsData))
    in Connect(DnsData)
    in Provider
```

and

```
index.js:132 Uncaught TypeError: Cannot read property 'list' of undefined
    at getSelectedDomain (index.js:132)
    at Dns.renderDnsTemplates (index.jsx:130)
    at Dns.render (index.jsx:179)
    at eval (ReactCompositeComponent.js:796)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
 ...
```
Seems there's a race condition or something when loading the DNS records. Or maybe it never worked properly and some recent change just broke it completely.

**Comment by ehti** [comment]
Ugh, can replicate. It was not an issue until at least Sep 22, when I was testing for custom root A record bug and refreshed the DNS records page several times when trying to add/remove records.

**Comment by klimeryk** [comment]
From @delputnam's testing it seems that https://github.com/Automattic/wp-calypso/pull/18427 is the culprit.

**Comment by stephanethomas** [comment]
Thanks for the report Igor! I've added this issue to our board.
