### ISSUE TITLE
Unable to load pages/posts - Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#18645]
User reported their list of pages isn't loading.

I exported their pages (.xml) and was able to find out the problematic/invalid characters causing this. WP-Admin works fine. The code/snippet I extracted from their content is at pb in step 3 - there can be other characters as well, so the export of all their pages is here: 1b9b8-pb

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/pages/{site} (or posts)
2. Click Add - type any title
3. Switch to HTML tab, add this code and publish: 1b9b7-pb
4. Go back to list of pages/posts and *refresh* the tab/window.

#### What I expected
To be able to view the list of pages or posts.

Also, the "Publish" button keeps loading if you embed the problematic characters, but it does actually publish the thing! Though you don't get any notification in the editor.

#### What happened instead
List of pages or posts doesn't show up. One of these two errors will show up:

>We're sorry, but an unexpected error has occurred

OR

>Cannot read property '_currentElement' of null

**The console throws these errors:**

` Uncaught URIError: URI malformed
    at decodeURIComponent`

and

`Uncaught TypeError: Cannot read property '_currentElement' of null`

Plus, the "Publish" button kept animating, no notification the post/page is published.

#### Browser / OS version
Chrome, latest

#### Screenshot / Video
1st.
![image](https://user-images.githubusercontent.com/6505293/31318005-64a61e3c-ac64-11e7-91ff-e3f6a6891c9e.png)

2nd:
![image](https://user-images.githubusercontent.com/6505293/31318008-7085854e-ac64-11e7-84c7-b3baf726c823.png)

#### Context / Source
#user-report then #manual-testing. 
#723496-zen

**Comment by jblz** [comment]
Looks like the same issue solved by #17588 in another place.
...we should be able to just use the helper `lib/url/decodeURIComponentIfValid`
