### ISSUE TITLE
DevDocs: EmbedDialog and Rating design blocks incorrectly titled "t"

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#18650]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design
2. Look for the EmbedDialog and Rating blocks
3. Go to https://wpcalypso.wordpress.com/devdocs/design/t

Result: You'll see the EmbedDialog and Rating blocks but with the title "t"

#### Screenshot / Video

![screen shot 2017-10-09 at 12 09 24 pm](https://user-images.githubusercontent.com/8658164/31335611-3b583bb4-aceb-11e7-9073-90e928f09252.png)

#### Context / Source
#automated-testing #visdiffs

**Comment by jeremeylduvall** [comment]
Closed via #19005.
