### ISSUE TITLE
Jetpack Connect: Happychat link colors are not consistent

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#18652]
As @sirreal reported in https://github.com/Automattic/wp-calypso/pull/18397#issuecomment-335100243, there are some color inconsistencies between the regular Help link and the Happychat link in the Jetpack Connect footer:

![with-chat](https://user-images.githubusercontent.com/841763/31330963-b7111d80-ace0-11e7-8aca-d3412ce4c652.png)

vs

![no-chat](https://user-images.githubusercontent.com/841763/31330966-bba74a36-ace0-11e7-8ed2-2eb0ac05fb29.png)

**Comment by tyxla** [comment]
It appears this one is caused by the fact that the help link can get the `:visited` color (because it's a real link), while the Happychat button can't get that color (because it's not a real link). I'm more inclined to leave this as-is, but another solution could be to totally ditch the `:visited` color.

I'd really appreciate a designer's opinion on whether we should change anything here - cc @folletto @rickybanister.

**Comment by folletto** [comment]
I think they should coordinate colors, so both darker — also for accessibility, as the darker one passes AA text contrast.

**Comment by tyxla** [comment]
Thanks @folletto, PR coming soon.

**Comment by tyxla** [comment]
#18778 is addressing this.
