### ISSUE TITLE
Jetpack Connect: "Connect Now" button disabled when you go back to the main Connect screen

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#18665]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/connect
2. Enter a self-hosted URL and select "Connect Now"
3. On the next screen, select the "Back" button
4. Try to select "Connect Now" again

#### What I expected

I expected the "Connect Now" button to be enabled again.

#### What happened instead

The "Connect Now" button was disabled. I discovered I could enter the URL and hit "Enter" to submit the URL again, but that option wasn't obvious (at first I refreshed the page to get the button to work again).

#### Browser / OS version

Mac OS 10.12.6, Chrome 61

#### Screenshot / Video

![screen shot 2017-10-09 at 4 34 02 pm](https://user-images.githubusercontent.com/8658164/31346109-f1ef1e78-ad0f-11e7-95d9-916f26fd8fec.png)

#### Context / Source
#manual-testing

**Comment by beaulebens** [comment]
This appears to be a purely client-side disabling/styling thing, because you can still hit Enter and re-submit the form.

**Comment by seear** [comment]
@rachelmcr Are you still seeing this one? I can't reproduce it:

![button_after_back](https://user-images.githubusercontent.com/7767559/37207638-c35aebee-2395-11e8-840d-f703d596276c.gif)

**Comment by rachelmcr** [comment]
I can't reproduce it anymore, either; closing as no longer valid.
