### ISSUE TITLE
Jetpack Connect: Using browser's back button during connect flow takes you out of the flow entirely

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#18666]
#### Steps to reproduce
1. Starting at URL: https://jetpack.com/
2. Select "Install" in the top right
3. Go two or more steps through the connect flow
4. Select the back button in your browser

#### What I expected

I expected to go back to the previous step. (For example, on the "Ready for Activation" step I expected to go back to the "Connect a self-hosted WordPress" step.)

#### What happened instead

I went all the way back to https://jetpack.com/. (I repeated from other starting points, and no matter what using the back button in my browser sent me back to whatever page I was on before entering the connect flow.)

#### Browser / OS version

Mac OS 10.12.6, Chrome 61.

#### Context / Source
#manual-testing

**Comment by beaulebens** [comment]
Possibly related, because I tried using the Back button in amongst this testing: https://github.com/Automattic/wp-calypso/issues/22757

**Comment by seear** [comment]
PR #22951 will add back support for the install instructions, and is quite a big refactor of main.jsx. It will be best to tackle the remaining back/forth problems after that one lands.

**Comment by cathymcbride** [comment]
No movement for several years. Closing...
