### ISSUE TITLE
Store: Refunds: Make Total Refund Amount NOT look editable/NOT gain focus

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#18672]
Since the "Total Refund Amount" edit box can gain the focus, it looks the same as the Quantity and Shipping boxes to me - suggesting I can edit when in fact I cannot. Could we not allow it to gain the focus?

Should it even have a border box at all or should it just appear like a static text field like the Total above it does?

![looks-kinda-editable](https://user-images.githubusercontent.com/1595739/31351839-6c8bffea-ace1-11e7-9304-feead8d80914.gif)

Originally: https://github.com/Automattic/wp-calypso/pull/18633#issuecomment-335238293

**Comment by ryelle** [comment]
Since this is a changing value, and it's the value the store owner is "paying" back to the user, i do think it needs to be highlighted somehow, though clearly the not-editable-edit-field is a poor choice – @jameskoster @kellychoffman any ideas?

**Comment by kellychoffman** [comment]
Agree. Let's highlight it in a different, less editable field-y way: 

<img width="659" alt="screen shot 2017-12-15 at 3 10 00 pm" src="https://user-images.githubusercontent.com/5835847/34062545-511732e0-e1aa-11e7-81ed-1c9ac4f00c83.png">
