### ISSUE TITLE
Extract Happychat from Calypso

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#18670]
This is the master issue to track progress on creating a Happychat library out of the current Calypso component that can be used in other environments.

**Status:** Happychat has been extracted from Calypso to the [happychat-client](https://github.com/Automattic/happychat-client) library. I left this open to track that we want Calypso to use this new extracted library and remove all Happychat code from this repo.

### Untangle

SocketIO API

- [x] https://github.com/Automattic/wp-calypso/pull/18519 ~Remove EventEmitter dependency~ 
- [x] https://github.com/Automattic/wp-calypso/pull/18691 ~Reject connection promise~
- [x] https://github.com/Automattic/wp-calypso/pull/19216 ~The basic components for the revamped API~
- [x] https://github.com/Automattic/wp-calypso/pull/19223 ~Implements `connection.init`~
- [x] https://github.com/Automattic/wp-calypso/pull/19227 ~Implements `connection.request`~
- [x] https://github.com/Automattic/wp-calypso/pull/19231 ~Implements `connection.send` for typing events~
- [x] https://github.com/Automattic/wp-calypso/pull/19237 ~Implements `connection.send` for user messages and user info~
- [x] https://github.com/Automattic/wp-calypso/pull/19251 ~Implements `connection.send` for log, event, and preferences~
- [x] https://github.com/Automattic/wp-calypso/pull/19269 ~Implements remaining HAPPYCHAT_IO_RECEIVE actions~

Redux state

- [x] https://github.com/Automattic/wp-calypso/pull/18743 ~happychat.chat~ 
- [x] https://github.com/Automattic/wp-calypso/pull/18699 ~happychat.connection~ 
- [x] https://github.com/Automattic/wp-calypso/pull/18744 ~happychat.ui~ 
- [x] https://github.com/Automattic/wp-calypso/pull/18739 ~happychat.user~
- [x] https://github.com/Automattic/wp-calypso/pull/18813 ~happychat.user.geo_location to happychat.user.geoLocation~ 
- [x] https://github.com/Automattic/wp-calypso/pull/19768 ~Extract remaining selectors to own file~

React components

- [x] https://github.com/Automattic/wp-calypso/pull/19035 ~Clean Happychat CSS~ 
- [x] https://github.com/Automattic/wp-calypso/pull/19038 ~Clean React components~ 
- [x] https://github.com/Automattic/wp-calypso/pull/19394 ~Decouple UI components~

### Extract

This is done and can be found at [happychat-client](http://github.com/automattic/happychat-client).

### Consolidate

The goal is using the [happychat-client](http://github.com/automattic/happychat-client) library to provide Happychat support in Calypso, so we have only one Happychat codebase to maintain. This is on hold until Happychat has been deployed to other places. For reference and make them discoverable, I'm linking here past experiments:

- https://github.com/Automattic/wp-calypso/pull/19049 ~Try getting rid of Happychat Connection~
- https://github.com/Automattic/wp-calypso/pull/19103 ~Use the API provided by happychat-client~
- https://github.com/Automattic/wp-calypso/pull/19965 ~First step: extract /me form~

### Calypso dependencies

General

- External libs: `lodash`, `jest`, `chai`, `deep-freeze`, `is-my-json-valid`, `redux`, `react`, `react-redux`, `classnames`, `debug`, `prop-types`, `gridicons`.
- selectors that use parts of Calypso (non-happychat) state tree:
  - `getGroups` queries Calypso state tree.
  - `isHappychatOpen` uses `getSectionName` selector.
- config

Redux

- serialization/deserialization mechanism:
  - SERIALIZE/DESERIALIZE actions are available for reducers to declare their custom needs.
  - `combineReducers` from `state/utils`: same API than Redux `combineReducers`, adds knowledge about how to handle custom persistence and schema validations.
  - `createReducer` from `state/utils/`: used to add new capacities to reducers (check schema, custom serialization, etc).
  - localStorage lib: retrieve and save Redux state.
- `lib/create-selector`: to cache complex selectors.

React

- i18n mechanism: we use the `i18n-calypso` lib. React components that need i18n have a translate property that they use to print the messages. The messages to be translated are extracted from Calypso codebase with a [cli command](https://github.com/Automattic/i18n-calypso/tree/dceace781efd139fbf62c3fd6719113bac4e2f87/cli).
- migrate from mixins (scrollbleed, autoscroll)?
- `me/happychat/main`: uses `react-dom`, `lib/viewport`.
- `components/happychat/timeline`:
  - `components/emojify`: to parse UTF-8 emoji symbols. This depends on internal `config` and external `twemoji`.
  - `lib/url`: to parse links into something clickable.
- `components/happychat/button`
  - uses page and `lib/viewport` to know whether redirect to `/me/chat` or dispatch the openChat action.
  - wraps `components/button`

**Comment by southp** [comment]
Is there a post or something documenting how all these pieces fit together? I personally feel a bit lost of the bigger picture here. A short explanation on how they make HC extractable or how you are going to extract HC would be super helpful : )

Forgive my ignorance if it's just me overlooking it :D

**Comment by nosolosw** [comment]
This is the (ongoing) bigger picture! It'll evolve to reflect what we learn.

It may help to explain the process I'm following. For every area (SocketIO, Redux state, React components) what I'm doing is:

1. General cleaning and identifying dotcom dependencies.
2. Extracting those dependencies.

For example, let's focus on the Redux state: the current PRs address the first step. They clean things and help to identify dotcom dependencies (such as the libs we use for the Redux serialization mechanism, selectors that only work on Calypso, etc). After that first step, we can prepare other PRs to eliminate any dotcom dependencies from `state/happychat`. At that point, reusing this in any other place is straightforward. How we reuse/extract that (a separate repository, calypso extension, etc) is something we'll consider later because is orthogonal to this work and needs more thinking/feedback from you all.

Is this helpful?

**Comment by southp** [comment]
Yes, it is. Now I know the individual purposes better :)

**Comment by nosolosw** [comment]
Work for this is happening at https://github.com/Automattic/happychat-client/issues/152
