### ISSUE TITLE
Happychat: Doesn't always scroll to the latest message

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#18692]
As reported in p1HpG7-4hr-p2, there is a case when the user sends a message, but the timeline does not get automatically scrolled to the latest messages.

To reproduce:
* Load Happychat somewhere.
* Make sure you have a higher timeline than your current window. 
* Scroll to the top of your timeline, so at least 1 of the latest messages is hidden.
* Send a new message.
* The new message is displayed, but the user is not scrolled to the end of the timeline, thus the new message remains hidden.

cc @nosolosw @unDemian @mattwondra

**Comment by mattwondra** [comment]
I re-documented this for prioritization in 867-gh-happychat. Going to close this one.
