### ISSUE TITLE
Domains/Checkout: Changing countries causes state control to visibly change value

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#18724]
#### Steps to reproduce
1. Add a domain to your cart and navigate to http://calypso.localhost:3000/checkout/ to get to the Domain Contact Information form
2. Switch to a country with a text-entry state field ( e.g. France, Germany, Sweden )
3. Switch to a country with a drop-down state field ( e.g. Australia, Brazil, US )
4. Notice that the selector shows the first entry for a second, and then flips over to "Select State"

#### Screenshot / Video
![domains-details-state-field-flicker](https://user-images.githubusercontent.com/5952255/31415533-666ae7ca-ae67-11e7-90b2-78704e26480c.gif)

**Comment by ramonjd** [comment]
Fixed in #18732
