### ISSUE TITLE
Activity Log: restore dialog tweaks

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#18745]
Some improvements for the new restore dialog https://github.com/Automattic/wp-calypso/pull/18241 :

- [x] The timeline circle corresponding to the rewind dialog should have a blue background `#00aadc`.

![image](https://user-images.githubusercontent.com/390760/31448525-8ee4fe5e-ae9c-11e7-9e4f-1048738f2c58.png)

- [x] Icon next to _More info_ link should be `<Gridicon icon="info" />`.

![image](https://user-images.githubusercontent.com/390760/31448536-980cd1a0-ae9c-11e7-87e0-2464d75f3aab.png)

- [x] Add HappyChat link `<Gridicon icon="chat" /> Need help?`.
- [x] Apply same style to More info and HappyChat CTAs; right now one is a link and the other a button.

![image](https://user-images.githubusercontent.com/390760/31448580-b627dd4c-ae9c-11e7-9750-6f1628fa50b9.png)

- [x] Break timeline above the restore dialog.

- [x] Style all lost items/days differently.

**Reference mock**

![image](https://user-images.githubusercontent.com/390760/31447360-aeea8758-ae99-11e7-97a9-b73a27a49b5f.png)

@eliorivero let me know if this format works for you, or if you rather have this list broken down by individual issues and I'll do it.

**Comment by eliorivero** [comment]
This format works, thanks!
I ticked some issues that are already addressed in #18722 and will work on the others.
