### ISSUE TITLE
Jetpack Connect: Auto authorize users through the logged out flow

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#18753]
Currently, if a user attempts to connect their site, and that user is logged out on the WP.com side, they see a sign up form that looks like this:

<img width="451" alt="screen shot 2017-10-11 at 11 51 08 am" src="https://user-images.githubusercontent.com/1126811/31454260-7f5c37ee-ae7a-11e7-88c0-3a1b90ce1361.png">

Creating an account through that form, should also authorize the user. But, after the user creates an account, they then have to click the approve button. Then, the site will be connected.

Steps to reproduce. 

- In a logged out browser (or incognito tab)
- Log in to Jetpack site
- Make sure site is disconnected
- Click "Connect Jetpack" button
- On WPCOM, see the sign up form
- Enter details to create a new account and click "Sign Up and Connect Jetpack" button.
- Verify that on the next page you have to click the "Approve" button and you are not automatically authorized

**Comment by ebinnion** [comment]
For what it's worth, I believe we'll need to add some flag for this logged out flow, and then tweak this conditional:

https://github.com/Automattic/wp-calypso/blob/master/client/jetpack-connect/auth-logged-in-form.jsx#L85

**Comment by rachelmcr** [comment]
This seems to be resolved. I tested with the steps listed above, and on the last step I didn't have to approve the connection — it was automatically authorized (a spinner appeared while being authorized).
