### ISSUE TITLE
Editor: Inserter requires two taps to open, and its tooltip stays visible in iOS

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#18781]
In browsers in iOS, the new inserter (#18719) requires two taps to see the dropdown, and the tooltip that appears with the first tap stays visible once it appears. 

This is likely caused by a mix of iOS quirks and  tinyMCE itself, but I hope we could something about it as the tooltip hides the first item in the dropdown.

This isn't an issue in Android (The tooltip won't appear at all).

First tap:
![img_3971](https://user-images.githubusercontent.com/908665/31495423-81626c9a-af4f-11e7-960c-d4037b76c0d5.jpg)

Second tap:
![img_3972](https://user-images.githubusercontent.com/908665/31495437-8b58bd26-af4f-11e7-84a4-fa4eac0fb65b.jpg)

Tooltip stays visible:
![img_3973](https://user-images.githubusercontent.com/908665/31495460-9d3c6cae-af4f-11e7-8d68-178916fd29eb.jpg)

**Comment by donpark** [comment]
@iamtakashi more info on this issue.

- Paragraph popup works as expected.
- Insert Content Button is merged Visual View but not in HTML View.
- "Add Content" Tool Tip doesn't go away.
- Double Tap on Insert Content Button is not always necessary - Hinting that issue may be focus related.

PR #18719 is likely to blame. It needs to work like Paragraph Button.

**Comment by iamtakashi** [comment]
@donpark Thanks for the info! 

The button for the HTML view is being worked on in #18773
