### ISSUE TITLE
DevDocs: Blocks page doesn't load

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#18780]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks
2. Wait for the Blocks page to finish loading.

#### What I expected

I expected the Blocks page to load with each Calypso block.

#### What happened instead

The page reloaded and displayed the error message "We're sorry, but an unexpected error has occurred." The console showed the error `TypeError: s.props.setActiveReply is not a function`.

The same error can be seen when visiting the ConversationsCommentList block: https://wpcalypso.wordpress.com/devdocs/blocks/conversation-comment-list

But other blocks load correctly when visited directly, e.g. AuthorSelector: https://wpcalypso.wordpress.com/devdocs/blocks/author-selector

cc @bluefuton It looks like https://github.com/Automattic/wp-calypso/pull/18671 is the likely culprit here.

#### Browser / OS version

Mac 10.12.6, Chrome

#### Screenshot / Video

![screen shot 2017-10-12 at 1 05 05 pm](https://user-images.githubusercontent.com/8658164/31495134-447eb078-af4e-11e7-959c-035ef47d8e0d.png)
![screen shot 2017-10-12 at 1 05 15 pm](https://user-images.githubusercontent.com/8658164/31495137-462892a4-af4e-11e7-81c6-f0b7ed16bef7.png)

#### Context / Source
#visdiffs #automated-testing

**Comment by bluefuton** [comment]
> cc @bluefuton It looks like #18671 is the likely culprit here.

I'd say so :) Thanks for the heads up @rachelmcr, I'll fix today.

**Comment by bluefuton** [comment]
Fixed in #18810.
