### ISSUE TITLE
Empty content state for initial sync

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#18803]
Let's keep the empty content state pretty simple for now. Folks are unlikely to see this anyway. It should use the EmptyContent component and look like this:

![image](https://user-images.githubusercontent.com/1123119/31521954-bef85362-af68-11e7-88f5-da5da82b522a.png)

Here is the necessary SVG: https://cloudup.com/c-IL1cJp8il

**Comment by rickybanister** [comment]
@MichaelArestad or perhaps @eliorivero do either of you know what will happen once the site is synced? Do we need a button on this page for them to refresh the view? Will new content be 'pushed'? Etc. etc.
