### ISSUE TITLE
Sidebar: Mobile: on single site can't open front-end by clicking `.site__content` link

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#1881]
**What I expected:**
On a mobile screen, I want to open my site's front-end by clicking the home link in the sidebar of My Sites.

<img width="487" alt="broken-link" src="https://cloud.githubusercontent.com/assets/66797/11935618/0ce4dd68-a7c6-11e5-99b9-d8efc43fc230.png">

**What actually happened:**
The link doesn't work. I cannot open my site's front-end from mobile.

**Steps to repeat, using a small screen (mobile):**

1. Log in to wpcalypso.wordpress.com
2. Click on My Sites
3. Click into a single site
4. At the top, there is a "Home" link which has the home icon
5. Try to click it

**Comment by kriskarkoski** [comment]
Confirmed clicking the Site title/home area does not open my site in a new tab as it does on desktop. Reproduced in Safari 9.0 on iPhone 6 running iOS 9.2

**Comment by lancewillett** [comment]
This could be related to the "hover" change for desktop interactions for the "Go to site" link.

Note, on iOS if I hold the tap (not a single tap) the dialog does pop up. Similar to a hover on desktop.

<img width="487" alt="screen shot 2015-12-21 at 13 38 45" src="https://cloud.githubusercontent.com/assets/66797/11940810/4567a6ee-a7e8-11e5-8b91-9ff3f757704d.png">

**Comment by aduth** [comment]
Related: #1631

I think we need to bypass the [`onSelect` logic](https://github.com/Automattic/wp-calypso/blob/e7693c5/client/my-sites/site/index.jsx#L55-L58) when `this.props.homeLink` is true, since this handler is used for the `onTapTouch` event in preventing the normal link behavior.

Will put together a fix shortly.
