### ISSUE TITLE
Store: Make the Save button more prominent

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#18814]
Seems that sometimes is hard to find the "Save" button, located currently in the top right corner of the screen, and users forget/skip saving settings. This was brought up here: p90Yrv-es-p2

**How it looks now:**
<img width="1122" alt="screen shot 2017-10-13 at 13 47 01" src="https://user-images.githubusercontent.com/3812076/31544898-56b85094-b01d-11e7-88bf-cbe88b1be118.png">

**How it could look** (Screenshot of the actual WordPress.com settings screen)
<img width="599" alt="screen shot 2017-10-13 at 13 48 05" src="https://user-images.githubusercontent.com/3812076/31544901-58a1ad4c-b01d-11e7-9a2c-ea48a2fd0a04.png">

**Comment by justinshreve** [comment]
cc @kellychoffman & @jameskoster for design feedback.

We'll also be fixing https://github.com/Automattic/wp-calypso/issues/17271 soon, which should help a little with the forgetting to save part.

**Comment by justinshreve** [comment]
I think this one can be closed out. We've made the top bar sticky on all displays, and have added notices to our pages when you navigate away with unsaved changes.
