### ISSUE TITLE
Plugins: Add an Update button to the bulk actions when at least one update is available

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#1882]
Currently:

<img width="681" alt="screen shot 2015-12-21 at 12 23 16 pm" src="https://cloud.githubusercontent.com/assets/437258/11936759/eb30a4be-a7dd-11e5-8170-6efeed4ab733.png">

We have an `Update All` button in the normal `SectionHeader` but no way to update a few selected plugins in `Edit All` mode.

Ideally:

<img width="690" alt="screen shot 2015-12-21 at 12 25 07 pm" src="https://cloud.githubusercontent.com/assets/437258/11936769/f5c1a3c4-a7dd-11e5-8340-305c910a70d4.png">

We need to add a `primary` button to the very left of the `Edit All` toolbar when at least one update is available. It would also become the first option in the compacted mobile dropdown nav.

If there are no updates available, let's hide the button to save the horizontal space.

**Comment by v18** [comment]
This feature is now live, so I'm marking this as closed.
