### ISSUE TITLE
Activity Log - Server credentials during plan purchase flow

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#18832]
Once a user pays, they should be taken into a flow where they can input credentials. We may want to put an introductory step between the payment and the opt-in message or move the opt-in message to after the thank you step.

#### 1. Thank you message

![thank you](https://user-images.githubusercontent.com/1123119/31978167-4a836d20-b8fd-11e7-8d61-88bd62adb5e7.jpg)

This needs to be modified for Jetpack plans to direct the user from the Thank you to the next step of filling out credentials for backups.

#### 2. Add credentials confirmation

![approve credentials copy 3](https://user-images.githubusercontent.com/1123119/31978202-7572d9d0-b8fd-11e7-9ee0-c58b1e95c85c.jpg)

This is a short confirmation to let the user know what we plan to do with the credentials. If they skip, the user will be taken to the second chance view (#5)

#### 3. Credentials form

![server credentials - details](https://user-images.githubusercontent.com/1123119/31978311-fbd6ccde-b8fd-11e7-8c5f-cb19dfa7e7c1.jpg)

This will function and look almost exactly the same as it does in settings only, upon completion, it will go to the next view (4).

#### 4. Success!

![approve credentials copy 4](https://user-images.githubusercontent.com/1123119/31978327-1828400c-b8fe-11e7-9047-42618c43c082.jpg)

This is a confirmation of the success of the credentials. They are done with setup (possibly). The blue button directs the user to the Jetpack dashboard. If they haven't done Jumpstart yet, they will have the chance to do so.

#### 5. Second chance

![approve credentials second chance copy](https://user-images.githubusercontent.com/1123119/31978363-458165ba-b8fe-11e7-81c2-dbc104d9851c.jpg)

This gives the user the option to contact support before bailing on credentials. The can still skip. If they choose to do so, they are directed to the Jetpack dashboard.

**Comment by MichaelArestad** [comment]
@rcoll I updated the original issue here with new screenshots that describe the updated flow from the prototype. Let me know if you have any questions./

**Comment by beaulebens** [comment]
In step 3. I'm guessing you don't actually want the sidebar there, right? It should just be the form, centered (like the other views), presented kind of as part of the purchase flow?

**Comment by MichaelArestad** [comment]
Yeah. Def no sidebar on that step.

**Comment by enejb** [comment]
Step 3 still looks a bit strange to me. 
Should we add a place where the user can test the connection? 

Since if they enter the wrong info the site can't actually be backing up. 

The show public key part also seems a bit confusing to me. If I click on the button what happens?  

Could we just hide that part and only show it to the user if they select it via the credentials dropdown?

**Comment by dmsnell** [comment]
> 5. Second chance

Note that _after_ someone has chosen the already-hidden `Skip` option that we ask a yes/no question and give no `no` button to click, instead making them search again for a hidden `Skip` link that they already actively chose to click on.

This feels dirty and it would frustrate me greatly.

**Comment by MichaelArestad** [comment]
@enejb There is already validation upon submitting the form to test it. If it doesn't work, we don't take them away from the form and we show errors depending on what isn't working or what is missing.

**Comment by samhotchkiss** [comment]
> Note that after someone has chosen the already-hidden Skip option that we ask a yes/no question and give no no button to click, instead making them search again for a hidden Skip link that they already actively chose to click on.

@dmsnell -- if they found it the first time, it should be pretty easy to find it again.  Backups are a huge part of our value proposition, and it's important that we make it very clear to users that they don't get them if the don't share creds
