### ISSUE TITLE
Reader: Replying to a comment triggers orange pill

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#18846]
Steps to repro:

1. In Conversations, reply to a post: https://wpcalypso.wordpress.com/read/conversations

2. Wait for a few seconds. Orange pill will show up saying there's "1 New Post". Nothing happens when you click on this (no new post shows up at the top of the stream) so I think it's referring to the comment that I just posted.

I think the orange pill should only show up if it's someone else that posted a comment.

**Comment by samouri** [comment]
current response payload looks like:
```
{
  "code":403,
  "headers":[
     {"name":"Content-Type","value":"application\/json"}
   ],
   "body": { "error":"unauthorized","message":"User cannot read unapproved comment" }
}
```

**Comment by jancavan** [comment]
Also reported by @alisterscott:

>Try commenting/replying from the tool. How did it go?
> Great! Although commenting on a post made the conversations feed think it was a new post which was a bit confusing as I expected to see a different post not the one I had just commented on.

![comment-on-existing-conversation](https://user-images.githubusercontent.com/4924246/33032844-4942462c-cdd7-11e7-878b-dd61722f713c.gif)
