### ISSUE TITLE
Editor: cannot select tags by clicking on list of previously used tags

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#1884]
After the update to v 1.2.1 a user in 678123-f reported a problem with tag selection in the post editor.

Tags cannot be selected by clicking on the list of previously used tabs using a mouse. Clicking on a tag merely causes the drop-down to collapse without adding the tag.

![selecting tags](https://cloud.githubusercontent.com/assets/11873759/11936852/3f42d0c8-a819-11e5-8fed-3f929745be51.gif)
Adding tags by typing their names still works, though.

I tested this using the Mac version, but the user who reported this happening is using the Windows version.

Initially reported this in https://github.com/Automattic/wp-desktop/issues/28, but @lancewillett pointed out that it might be a Calypso issue, rather than specific to the app.

I confirmed that the problem also exists Chrome 47.0.2526.106 and Safari 9.0.2, but not in Firefox 43.0.1

Possibly related to #1814

**Comment by isocialtish** [comment]
Received an additional report from a WordPress.com user on the same issue in 2472336-t
