### ISSUE TITLE
Self Hosted Site

### ISSUE THREAD

**Issue by djar** [Automattic/wp-calypso#18853]
I'm just curious if it is possible to use calypso without having to either use jetpack or link to wordpress.com when you have a self hosted site?  Is there any way you can make calypso connect directly to the REST API of the self hosted site?

**Comment by alisterscott** [comment]
Hi @djar 

A Jetpack connection is required to use Calypso for a self-hosted site.

Thank you

**Comment by djar** [comment]
Thanks Alister,  is there a plan to make it possible to access without the need for jetpack?

**Comment by alisterscott** [comment]
Hi @djar 

There isn't a plan as Calypso is the new WordPress.com front-end - and we support self-hosted sites on WordPress.com using Jetpack as the connector.

Thanks

**Comment by djar** [comment]
Thanks @alisterscott . For those that don't want to force connection with a Wordpress.com account,  do you think it would be feasible for me to adapt the codebase to connect directly to the API of a self hosted site?

**Comment by alisterscott** [comment]
> For those that don't want to force connection with a Wordpress.com account, do you think it would be feasible for me to adapt the codebase to connect directly to the API of a self hosted site?

What are you trying to achieve? For self hosted sites it's best to use wp-admin: a lot of the concepts in wp-calypso only work for Jetpack or WordPress.com sites since these have more features than plain self-hosted sites.

**Comment by djar** [comment]
Thanks @alisterscott .  What I want to achieve is to be able to leverage the single page admin for our wordpress clients and host under a central domain (away from the customer facing site), accessing the hosted site via the WP rest api.  A big part of this is for the improved look and feel. 

We have a bunch of custom post types, as well as custom variables we've created and put on our own admin screens.  
I'm wondering if the Jetpack API and the Core WP API have some overlap, or are they entirely different in their structure and function?
