### ISSUE TITLE
[Activity Log] Improve coloring and placement of green icons

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18862]
<img width="1091" alt="screen shot 2017-10-15 at 6 25 03 pm" src="https://user-images.githubusercontent.com/26996883/31591617-3edd60a8-b1d6-11e7-8559-d7c0063f9c23.png">

I just noticed the two greens conflict here along with the placement and size of the icons. Not sure what the best method is to improve this  - will leave that to design minds :)

**Comment by rickybanister** [comment]
@MichaelArestad let's chat and see if there's something we can do to make it easier for these to live sidebyside. There was some debate about whether 'Jetpack' should even be an actor or not. Let's debate.

**Comment by MichaelArestad** [comment]
The simplest fix for now is to make the background of the Jetpack logo grey. I think `darken( $gray, 10% )` will look good and is about the right shade.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1123119/31691968-1d79c7c8-b355-11e7-862d-3fc270373752.png">

**Comment by rickybanister** [comment]
looks good to me, my only suggestion is to make sure we sync up the gray color with the one we use in the 'powered by jetpack' footer.

**Comment by MichaelArestad** [comment]
@rickybanister That was the first one I tried, but it ended up looking pretty dark for the icon on white. For the footer grey, I used the text-min variable that barely meets AA requirements. When I build out the PR, I'll def try both and keep that in mind.
