### ISSUE TITLE
SiteSelectorModal: SitesDropdown extends below the bottom of the browser

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#1886]
From https://github.com/Automattic/wp-calypso/pull/1483#issuecomment-165502946:

<img width="605" alt="screen shot 2015-12-17 at 16 29 45" src="https://cloud.githubusercontent.com/assets/7767559/11875224/968e213e-a4db-11e5-95aa-83d866946669.png">

> The dropdown is extending beyond the bottom of the browser on my 13" MBP.

From https://github.com/Automattic/wp-calypso/pull/1483#issuecomment-166363586:

> I think the true solution to this is to be able to specify the position of the dropdown site-selector—for example _drop up_ or _centered_. I believe there is a v1.1 design that has it vertically centred, so maybe we go with what we have for now and iterate.

(See #451 for that v1.1 design.)

**Comment by seear** [comment]
A quick fix might be to use [`component-tip`](https://github.com/component/tip) (we use this for popovers) which will pop up wherever there is most space.
