### ISSUE TITLE
Purchases: Purchases aren't removed from `PurchasesStore` when upgrading plans

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1888]
Reported by @stephanethomas [here](https://github.com/Automattic/wp-calypso/pull/1649#issuecomment-166103035). This results in the user seeing a stale purchase when e.g. upgrading from premium to business:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11917524/d08145d4-a70a-11e5-84d0-cd81d91e8109.png)

**Comment by stephanethomas** [comment]
It really looks like we should update the `/me/transactions/` API endpoint to return the new list of upgrades. This would fix renewals as well.
