### ISSUE TITLE
Store: Use merchant's address to customize address state/country dropdowns

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#18902]
**Background:** As of #18821, we have new state/country dropdowns that use the WC locations API to fetch all supported countries or states. You can see it in-use on the customer edit modal:

<img width="654" alt="31553246-d50c1496-b007-11e7-963c-3c0c08475e01" src="https://user-images.githubusercontent.com/541093/31636853-2ebbed74-b29a-11e7-82e3-4ffbc20703c1.png">

We also hard-code a few countries to be pulled to the top of the list:

![screen shot 2017-10-16 at 5 55 57 pm](https://user-images.githubusercontent.com/541093/31637139-4faa0db2-b29b-11e7-9a59-b22ff00a5775.png)

**The issues:**

1. When not provided, these should default to the merchant's country/state (which will be more relevant once we can create an order). This is pretty straightforward.

2. Should we use the merchant country to adjust the "popular" countries?

In the previous review, @allendav noted:

> Wouldn't popular countries vary by merchant and be flavored by their location? Maybe we should float just the merchant's country to the top of the list for now. I'm thinking along the lines of what's popular for a US merchant will not be the same as what's popular for say a EU based merchant.

I think we'd still want a _list_ of countries, though – for example, a US merchant will probably be shipping to US & CA most often, but if we only float US they'll still need to search for CA. But trying to create a list for X countries and showing a different popular list based on country sounds like overkill.

@kellychoffman @jameskoster Thoughts on this flow?

**Comment by kellychoffman** [comment]
Good question. Since we are targeting US & CA currently I think we can keep the popular list since it includes both CA & US. Curious to hear what others think, though.
