### ISSUE TITLE
Add happychat to Jetpack cancellation flow

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18904]
To bring parity with WordPress.com and, since we are shifting towards focuses and ownership over flows vs features, I'm posting here to start the convo around adding happychat to the cancellation flow.

**Comment by tyxla** [comment]
I've started #19441 to address this. That PR enables the Happychat step in the cancellation flow for all Jetpack plans, see the PR for more details. I'd appreciate some feedback, thanks!

Two things to note:

1. Tracking is already available - when the user clicks the Happychat button in the Happychat step, the `calypso_purchases_cancel_form_chat_initiated` tracks event is recorded. It contains the cancellation flow slug and the product (plan) slug.

2. The Happychat button is also already available in the bottom left portion of the cancellation flow survey (displayed only if there's an operator available and Happychat is currently available for this user):

![](https://cldup.com/3zrNjFnvyk.png)

Upon click of that button, the `calypso_precancellation_chat_click` event is recorded.
