### ISSUE TITLE
Add gender neutral empty gravatar

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#18906]
I tested removing my gravatar images to see what would happen and found it gave me a very male looking avatar as the default state:

<img width="247" alt="screen shot 2017-10-16 at 3 06 27 pm" src="https://user-images.githubusercontent.com/26996883/31639056-a5e75eba-b28b-11e7-8493-5e112f622603.png">

Could we add in a gender neutral option? 

To replicate:
- Remove all gravatar photos here: https://en.gravatar.com/gravatars/new
- Head to https://wordpress.com/me and you will see the male avatar

**Comment by georgestephanis** [comment]
Is this a Calypso issue or a Gravatar issue? cc: @Automattic/guardians maybe?

**Comment by annezazu** [comment]
It could be gravatar! I'm not sure. I want to call on some designers for their take on this cc @melchoyce  @karmatosed

**Comment by thekaitlin** [comment]
I think the generic one probably falls in the gender-neutral category, though because of the extreme lack of distinctly female avatars more generally, tends to look more masculine. Although this is several years old, it seems relevant to the discussion: http://molly.is/writing/no-more-put-a-skirt-on-it/

**Comment by georgestephanis** [comment]
Nice article!  Would the status quo fit into what the author refers to as geometrically neutral, or is there some slight blue tinge to the background grey that would lean masculine suggesting?  (I've not checked the spot color, so idk)

**Comment by georgestephanis** [comment]
For the record, I'd be 100% fine personally if our generic default avatar was female presenting, though it may cause some headaches for our support folks fielding complaints.

**Comment by thekaitlin** [comment]
Based on the article I linked above, I think the status quo / current default would likely be considered geometrically neutral, although it's also titled "Mystery **Man**" [Ref.](https://en.gravatar.com/site/implement/images/). In the context of the fact that most icons and avatars people see are distinctly male, the lack of decoration on a geometrically neutral default makes it lean masculine. At least that's the way I read it. 

If you see this series of "generic" avatars, does the second one really seem like it's a departure from the explicitly masculine ones?

![Avatars](https://cdn-images-1.medium.com/max/1200/1*ulGzkwNUK_L98j5f8TyRDA.png)

Twitter's [redesign of their default avatar](https://blog.twitter.com/official/en_us/topics/product/2017/rethinking-our-default-profile-photo.html) seems to also include some discussion about how the circle head is perceived as masculine even though it's might be "technically" neutral.

The visual above came from [another article on inclusive avatars](https://uxdesign.cc/design-avatars-that-make-sense-and-be-more-inclusive-in-the-process-d4dd6a486ea6) I found while looking for a visual to describe how the Mystery Man conveys masculinity even though it might be geometrically neutral. And it's a good read about some of the considerations at play (Gravatar gets a mention for some of the other default options if you're implementing on your own site).

**Comment by georgestephanis** [comment]
It used to be referred to as `Mystery Man`, but Core renamed it to `Mystery Person` some time ago -- https://core.trac.wordpress.org/changeset/30089 -- I thought we had on gravatar.com but apparently it's still designated `Mystery Man` there -- https://en.gravatar.com/site/implement/images/

It would be good to change the designation there as well.

**Comment by dbtlr** [comment]
This is definitely not a Calypso issue. While It is technically a Gravatar issue, it is likely a WordPress issue as a whole, given how embedded this image is. I'm sure the technical job of changing it to another image would be a simple one, but the political aspect of it is likely a long debate.

Personally, I don't see how the icon could be any more gender neutral. However, that is what good designers are for, which I am not. :)

In terms of changing the designation from "Mystery Man" -> "Mystery Person" on Gravatar, definitely possible. I'll create a ticket for it over there.

**Comment by annezazu** [comment]
> I'm sure the technical job of changing it to another image would be a simple one, but the political aspect of it is likely a long debate.

I don't think this means we shouldn't change it. It may also not turn into a long debate especially if we go more neutral. Plus, we have long debates about what programming languages to use and what technical decisions to make yet we endure them because they are necessary to step forward.

**Comment by donnapep** [comment]
I think it's the head for me. It's bald which implies male.

**Comment by raoulwegat** [comment]
Twitter's approach is very considered – the shoulder width and the shape of the head – so I've used that approach to create a first design. These three are all slightly different, and are all pretty much  gender neutral, but you can see the subtle move from feminine (left) to masculine (right).

I think we also need to consider users, who for privacy reasons don't want to add a gravatar, so to make it look less "temporary", I've increased the contrast and used Calypso colors.

![group](https://user-images.githubusercontent.com/2627210/31753752-56d4fe72-b4de-11e7-957c-d4f1da3b5324.png)

**Comment by dbtlr** [comment]
@annezazu Not implying that we shouldn't, however, having this debate in the Calypso issues is the wrong place, as I'm sure there are WP core stakeholders who should be a part of WordPress wide changes like this.

**Comment by dbtlr** [comment]
With that said, Calypso can provide its own default avatar by adding `?d=<url to calypso specific gender neutral avatar>` to all gravatar image requests. This way we can do this in our own context, with Calypso specific colors, without involving the whole community. Maybe once it is visible in Calypso, others in the community would want to adopt it as a wpcore standard.

**Comment by drw158** [comment]
I went through our illustration resources and tried to find the most neutral figures:

Far right is our user icon in Gridicons:

![screen shot 2017-11-15 at 3 30 12 pm](https://user-images.githubusercontent.com/618551/32861303-ed61bace-ca19-11e7-8ffa-fc4d554247d9.png)

I suggest we use our user Gridicon (or at least have the 2 be the same, whatever we decide here). If the Gridicon is not gender neutral, we should make sure to make an issue there is well.

Getting something like the far left to work is probably not feasible, since the more detailed you get, the more issues you run into, like skin color.
