### ISSUE TITLE
Always show posts if there are posts to show

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18900]
There are cases where a Site View page does not show posts when there are posts on the site to show. Usually because the post is over two years old.

For example: https://wordpress.com/read/feeds/59761274
vs: https://jasonhoffman.blog

We should avoid ever saying "no posts to show" when there are posts to show.

From MM: Old posts not being in the reader: When a specific site is requested, we need to do whatever query / etc is needed to show the reader equivalent of what visiting the site and seeing their last N posts are

cc @blowery

**Comment by blowery** [comment]
We'll need to move back to the `1.2` version of the `/read/sites/%s/posts` API endpoint, which does do this fallback. That'll require rejiggering how the site stream consumes posts a bit.

**Comment by bluefuton** [comment]
We’re now back on v1.2 of the endpoint, and the old posts are displaying 🎉
