### ISSUE TITLE
Signup: DSS: Returning to DSS using Back link causes errors

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#1890]
Steps to reproduce:

1. Visit the DSS flow, eg: http://calypso.localhost:3000/start/dss/
2. Click on a theme; Signup will move to step 2.
3. Click the "Back" link at the bottom of the page to return to step 1.
4. Errors!

<img width="1426" alt="screen shot 2015-12-21 at 1 55 12 pm" src="https://cloud.githubusercontent.com/assets/2036909/11938687/81cfcd6c-a7ea-11e5-9cfb-441688fa3ad5.png">

**Comment by sirbrillig** [comment]
Still not sure why it's happening, but some research shows that it's definitely tied to the `dangerouslySetInnerHtml` method calls in the `Screenshot` component.

**Comment by sirbrillig** [comment]
The cause is apparently that the markup injected into the page using `dangerouslaySetInnerHtml` is not all well-formed. The result is that React loses track of the components and breaks. There's a few ways to clean up the markup on the client side. Experimenting in #1903

**Comment by sirbrillig** [comment]
Fixing this on the client-side is not trivial (see discussions in #1899 and #1903). This may be possible to do on the server-side before the markup is sent from the endpoint.

**Comment by sirbrillig** [comment]
A combination of #1926 and a clean up of the markup being served by the `/dss` endpoint fixes this.

**Comment by alisterscott** [comment]
Thanks, verified this was deployed and can't see the overlap or the main errors reported any more.

**Comment by alisterscott** [comment]
Found by #automated-testing
