### ISSUE TITLE
Store: Variant Price Field Too Narrow

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#18918]
When variant prices are greater than 3 digits ( plus the . of course ), the furthers right number is currently obscured by the number up/down controls. The following is from Chrome:

![edit_product_ _care_for_animals_ _wordpress_com](https://user-images.githubusercontent.com/22080/31665634-555e697a-b2fe-11e7-9fdb-eddcac3ec43e.png)

While not critical for prices that end in zero, this could be problematic for variant pricing with non-zero last digits, or just very expensive variants $$$$$$.

__To Reproduce__
- Open up Store | Products on a site https://wordpress.com/store/products/yourtestsite.com
- Add Product Variant data, with pricing that is > 3 digits long

**Comment by dinarAkv** [comment]
Hello, timmyc,
how can I reproduce this bug ? Could you give me information where I can find those price blocks ?

**Comment by timmyc** [comment]
@dinarAkv added some steps on how to reproduce in the OP.
