### ISSUE TITLE
URL is not correctly retrieved for Stats link

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#18934]
User at 734984-zen contacted us to report that one of their site's Stats link clicks was retrieving an URL that is not correct: (it leads to a 400 error)

 https://drive.google.com/uc?export=download&amp;id=0B_-6KdFaC6WiNWprcndycUY1Nk0

When the correct link is:

https://drive.google.com/uc?export=download&id=0B_-6KdFaC6WiNWprcndycUY1Nk0

It seems the ampersand is not retrieved correctly by the Stats' list of most clicked links.

**Comment by rachelmcr** [comment]
I tested and confirmed that ampersands are encoded as HTML entities in the links in the Stats Clicks section.

The link looks fine in the list, but if you click on it, the link is encoded and leads to a 400 error:

![screenshot 2018-08-28 11 52 50](https://user-images.githubusercontent.com/8658164/44718830-41897800-aab9-11e8-8f03-07d4d17d5b44.png)

**Comment by rachelmcr** [comment]
I checked the REST API and it looks like this is how the stats data is being returned from there. The `
/stats/clicks` endpoint returns the `name` correctly but encodes the `url` value.

**Comment by mikeicode** [comment]
Also reported in 14630069-hc

**Comment by cathymcbride** [comment]
not hit for quite a while. Closing...
