### ISSUE TITLE
Posts: use relative date up to a month; after that show the exact date

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#18937]
Similar to how we show dates now with [comments](https://github.com/Automattic/wp-calypso/pull/18624), let's show the relative date only for recent posts. Posts older than a month should show the exact date.

Bonus: improve the tool-tip date / time output. Currently it's difficult to read: `2017-09- 09T14:47:29-07:00`. We could improve that to be something more readable, like: `2017-09-09 at 14:47`.

#### Steps to reproduce

Go to Blog Posts for a site, and view the post card to see the post's publish date.

#### What I expected

To see the actual date and not elapsed time, for posts older than 1 month.

<img width="758" alt="screen shot 2017-10-17 at 13 37 37" src="https://user-images.githubusercontent.com/66797/31688384-0967370c-b341-11e7-8957-2c0e944a1cb7.png">

Proposed in an internal Slack chat by Bob, Megs, Andy P — ref: p1507740672000430-slack-triton

CC @mattsherman @shaunandrews

**Comment by mattsherman** [comment]
This is already addressed in the upcoming condensed post list redesign.

We used a cutoff of one week for switching to actual dates.

See: https://github.com/Automattic/wp-calypso/tree/master/client/blocks/post-time

**Comment by mattsherman** [comment]
You can see this in action currently for CPTs.

I’ll create a backlog item to address the tooltip formatting.

**Comment by alisterscott** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/2570

**Comment by alisterscott** [comment]
Also related: https://github.com/Automattic/wp-calypso/issues/12052

**Comment by mattsherman** [comment]
Closing this issue as it was addressed back in October. Related issues are still open and will be addressed separately.
