### ISSUE TITLE
App Banner: "No thanks" button doesn't dismiss the banner

### ISSUE THREAD

**Issue by maxme** [Automattic/wp-calypso#18948]
#### Steps to reproduce
1. On a mobile phone (happen on Android and iOS).
2. Starting at URL: https://wordpress.com/ - you must be signed in.
2. Tap the notification tab.
3. You should see the app banner with 2 buttons: "Install the app", "No thanks".
4. "No thanks" button doesn't work (can't be tapped).

#### What I expected

When I tap the "No thanks" button the app banner should be dismissed.

#### What happened instead

Nothing happen when I tap the "No thanks" button.

#### Browser / OS version

iOS Safari, Android Chrome

#### Context / Source

This only happens when the Notification tab is selected.

**Comment by maxme** [comment]
ping @Automattic/lannister

**Comment by vindl** [comment]
I've just tested this in production both in Chrome responsive mode and with my Nexus 5 and wasn't able to reproduce. Do you have more details about it? Have you tried it from you browser (Dev Tools)? Any errors in console?

**Comment by kwight** [comment]
Hm, same here, unable to reproduce (iPhone SE). Noting that I _do_ have the app installed, so the options were "Open in app" and "No thanks".

**Comment by gwwar** [comment]
On the Pixel 2 it looks like the click is propagating to the children underneath the app banner. (So the notifications close, and we end up clicking whatever happens to be there on the original page).

**Comment by maxme** [comment]
cc @nielslange who got the original ticket.

**Comment by gwwar** [comment]
Here's a capture of the behavior I'm seeing in the browser + on native

![bug](https://user-images.githubusercontent.com/1270189/31971387-7602858a-b8d0-11e7-98c8-7cd0023f9b5e.gif)

**Comment by gwwar** [comment]
Related #16818. Investigating why this broke.

**Comment by gwwar** [comment]
Oddly enough the callback ref is always returning null here instead of the component instance, so the event handlers are not being added.

**Comment by gwwar** [comment]
Regression caused by https://github.com/Automattic/wp-calypso/pull/18089 

Note that "You may not use the ref attribute on functional components" from https://reactjs.org/docs/refs-and-the-dom.html

When refactoring components to be functional, please do a usage check for refs! cc @mikkamp
