### ISSUE TITLE
Store: Make email address on Checkout wider or move it for better visibility

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#18954]
When going through the checkout process, the text field reserved for the email is too short and regular or long emails are not displayed fully. Cutting this value on online purchases seems arbitrary if we take into account that the ZIP code text field has double the width and will be certainly always shorter than this value.

This can be seen here: p90Yrv-es-p2 on the minute 25:12

<img width="1077" alt="screen shot 2017-10-18 at 14 23 25" src="https://user-images.githubusercontent.com/3812076/31719258-1b0d1102-b413-11e7-8b15-ccf4a99e9116.png">

**How to replicate:**

- Go through the process of purchasing a product, you can test is here: https://mug4you.blog
- Go to https://domain.com/checkout or https://mug4you.blog/checkout
- See how the email address text field got cut in the checkout page

**What I expected:**

- To see my full email address, or most of it.

**Comment by justinshreve** [comment]
It looks like we could fix this for Stores on .com by hooking in here: 

https://github.com/woocommerce/woocommerce/blob/0510714abf22a736b29556a5a8730c525e03ccbd/includes/class-wc-countries.php#L1147-L1174

And remove the CSS classes for email/phone.

The best fix would be to have this changed in Core itself. Do you mind reporting there as well? I agree the email address field should be longer.

**Comment by iamgabrielma** [comment]
> The best fix would be to have this changed in WooCommerce Core itself. Do you mind reporting there as well?

Sure thing: https://github.com/woocommerce/woocommerce/issues/17288

**Comment by ryelle** [comment]
This was fixed in WooCommerce core in https://github.com/woocommerce/woocommerce/pull/17323 — is there anything that needs to happen on the Calypso side?

**Comment by justinshreve** [comment]
I think we can probably just depend on the core fix, since WooCommerce will be auto-updated on Store sites.
