### ISSUE TITLE
Store: Fulfill Button not Disabled During Fulfillment

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#18958]
When fulfilling an order in the Store, there really isn't a visual indicator that an action is in progress - and the original Fulfill button is still exposed/clickable.

#### Steps to reproduce
1. Open a new order that needs to be fulfilled in the store
2. Click the Fulfill button, confirm in the subsequent dialog
3. Note after the dialog closes, the fulfill button is not disabled - nor is there any visual indication an action is being taken.

#### What I expected
The fulfill button to maybe be disabled at least, and perhaps say "Fulfilling ..." or some other progress indicator on the screen.

![fullfill](https://user-images.githubusercontent.com/22080/31725204-9db93da0-b3d8-11e7-9b68-6343b6647235.gif)

**Comment by ryelle** [comment]
Fixed in #22019
