### ISSUE TITLE
Store: "Paid in Full" string is confusing when a cash on delivery order is created

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#18955]
When going through the checkout process, if "cash on delivery" option is chosen by the customer, it will show as "Paid in full" automatically from the store owner point of view, as if was paid online. This can be confusing when keeping track of which orders had been paid and which aren't.

This can be seen here: p90Yrv-es-p2 on the minute 32

**Replicate:**
- Go through the process of purchasing a product, you can test is here: https://mug4you.blog
- Go to https://domain.com/checkout or https://mug4you.blog/checkout , fill the data and click on "Place Order"
- Go to http://wordpress.com/store/orders
- See the order as well as "Paid in full"

<img width="1134" alt="screen shot 2017-10-18 at 14 31 22" src="https://user-images.githubusercontent.com/3812076/31719352-69d89928-b413-11e7-8aef-40a1e4a4c841.png">

**What I expected:**

- To see some "Pending payment" string or a checkbox to check if this payment has been done

**What happened instead:**

- Is confusing because is a cash on delivery order, just placed it and says it has been paid in full
- Going to the order details shows also how the order (in this case the specific URL is http://wordpress.com/store/orders/mug4you.blog/61) has been already paid:

<img width="1131" alt="screen shot 2017-10-18 at 14 34 38" src="https://user-images.githubusercontent.com/3812076/31719360-730f8eca-b413-11e7-8e0c-14ab6a07a5de.png">

**Comment by justinshreve** [comment]
cc @ryelle - I can replicate this as well.

I tested Checks & Bank Transfer as well, but both of those display correctly. It looks like those have a status of `on-hold` whereas the COD payment has a status of `processing`. I guess we need some for COD here.

**Comment by ryelle** [comment]
What should the label say? "Payment pending" makes it sound too much like check payments, where you still want to wait on the payment before shipping out. For Cash on Delivery you want to ship the order out immediately. "Paid on delivery"?

Also noting we assume it's paid on the payment card, this text should also be updated (and refunds disabled). This should probably use the "Mark as Paid" button that pending orders get.

<img width="738" alt="screen shot 2017-10-18 at 2 38 40 pm" src="https://user-images.githubusercontent.com/541093/31736253-3d8bbd9c-b412-11e7-9e57-e83e9d9e177c.png">

cc @kellychoffman @jameskoster

**Comment by kellychoffman** [comment]
> "Paid on delivery"?

That sounds good.
