### ISSUE TITLE
View Site: Infinite Scroll doesn't load when site has a custom domain

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#18960]
#### Steps to reproduce
1. Open a site with a custom domain, infinite scroll active, and more than 7 posts on Calypso
2. Click on **View Site**
2. Scroll down the site until it reaches the first infinite scroll breakpoint (usually 7 posts)
3. The infinite scroll will fail and it will start to "flick"

#### What I expected

The preview should continue loading posts if there are posts to load, like it does for sites without custom domains.

#### What happened instead

The preview fails to load any posts after the first infinite scroll breakpoint and starts flicking.

#### Browser / OS version

I tested on:

OS: macOS 10.12.6
Browsers: Chrome 61.0.3163.100, Safari 11.0, Firefox 54.0.1

#### Screenshot / Video

Video: https://cldup.com/YPCAI1oigl.gif

Javascript console errors: https://cldup.com/Bfc6ROB82T.png

#### Context / Source

#user-report

**Comment by lancewillett** [comment]
I'm able to repeat this on lance.blog using Safari 11.0.1 on OS X 10.12.6 — logged in to Calypso, clicking View Site.

Once I scroll to the bottom of the preview — past the first set of posts (7 posts), the 8th post appears but nothing more. And I see the "flickering" as well.

Console JS errors:

`Failed to load resource: Origin https://lance.wordpress.com is not allowed by Access-Control-Allow-Origin. XMLHttpRequest cannot load https://lance.blog/?infinity=scrolling due to access control checks`

**Comment by lancewillett** [comment]
A fix for this is in the works, see D9581-code.

**Comment by jblz** [comment]
@lancewillett When you have a sec, can you please try https://wordpress.com/view/lance.blog for me & make sure infinite scroll works there and on the frontend?

The fix is in place server-side.

**Comment by lancewillett** [comment]
Works as expected! Yay!

**Comment by jblz** [comment]
I'm going to go ahead and close this.

If anyone has any specific cases where this isn't working, please feel free to reopen or create a new issue.

**Comment by Shavindra** [comment]
Hi we are having issues too

http://gems.trurating.com/

**Comment by jblz** [comment]
> We are having issues too http://gems.trurating.com/

Hi @Shavindra. Thanks for the report.  Let's see if we can figure it out.

It looks like that site is using an [Azure Rewrite App](https://social.technet.microsoft.com/wiki/contents/articles/32229.azure-create-an-url-rewrite-azure-web-app.aspx) or something similar. Can you confirm?  Also, what kind of issues? Is infinite scroll not working in `View Site` or is the section not working altogether?
