### ISSUE TITLE
Comments: add upgrade nudge for Jetpack

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#18965]
Soon we'll be able to use the new comments-list endpoint for Jetpack sites, removing the need for our fuzzy client paging. When Jetpack 5.5 is released we will display an upgrade nudge and will be able to remove the fallback approach we've been using.

We have a 👍  from Beau on being able to nudge people to the latest version without providing a fallback. 

Note that this nudge should be visible from both the site specific and post specific comment views.

![group 8 copy](https://user-images.githubusercontent.com/1123119/31830931-f7eeafb0-b57e-11e7-9319-184b8abbb41b.jpg)

**Comment by megsfulton** [comment]
There's been some discussion in the team chat around this. For context, we were going to show the user's comments and use a [notice](https://wpcalypso.wordpress.com/devdocs/design/notices) to prompt them to upgrade but that would require extra code / maintenance for the team. Instead we're going to do a forced upgrade and not show the users comments, which has us thinking the [empty content](https://wpcalypso.wordpress.com/devdocs/design/empty-content) component makes the most sense here.


![comments m3 - jetpack upgrade](https://user-images.githubusercontent.com/161697/31794614-bfd8435e-b4d7-11e7-8594-3c04cd99865e.png)

Content options: 
1. Upgrade to Jetpack 5.5 / Comments requires the latest version Jetpack. / Upgrade Jetpack
2. Upgrade to Jetpack 5.5 / The latest version of Jetpack is required to manage your site’s comments. / Upgrade Now

I used the Jetpack illustration from the design files. @rickybanister - want to check and make sure there's not something else we should be using here instead?

**Comment by rickybanister** [comment]
That looks pretty good to me.

ccing @MichaelArestad since he recently did work on this exact situation.

**Comment by gwwar** [comment]
Should we be putting the Jetpack version into the copy? In another 2 months, Say someone with version 5.4 visits, but we'd still like them to update to the latest version of 5.7.

**Comment by megsfulton** [comment]
Oh, good point. Maybe we go with something more generic instead: 

![comments m3 - jetpack upgrade](https://user-images.githubusercontent.com/161697/31800316-f2105b00-b4f4-11e7-8ffe-91a8428953fa.png)

**Comment by MichaelArestad** [comment]
How about we do something like this?

![group 8 copy](https://user-images.githubusercontent.com/1123119/31830931-f7eeafb0-b57e-11e7-9319-184b8abbb41b.jpg)

**Comment by MichaelArestad** [comment]
Let's not show any comments UI including the tab bar so it doesn't feel broken. It also might be nice to include a button to enable autoupdates for Jetpack.

**Comment by megsfulton** [comment]
Works for me!

**Comment by gwwar** [comment]
Nice, I like it!
