### ISSUE TITLE
Editor: Cannot access drafts for Jetpack sites

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#1897]
I have 3 drafts on my Jetpack-connect site, but in the Editor the Drafts drawer is disabled like I have none. If I start a new post I can access the drafts drawer once the post auto-saves, but if I leave the Editor and return I can no longer access it again. This may be related to #1555 and general issues with Jetpack post counts.

![screen shot 2015-12-21 at 4 13 28 pm](https://cloud.githubusercontent.com/assets/1900444/11941460/cda0bc0c-a7fd-11e5-91cb-72e36561ca50.png)

The drafts do appear normally at https://wordpress.com/posts/drafts/

**Comment by SentientPrime** [comment]
I also have a Jetpack connected site and have a similar problem described by @kriskarkoski except the drafts are also disabled at wordpress.com.  Not until I create and save a new draft does the drafts drawer become enabled again.  If I leave the editor or if I enter and leave the drafts drawer, then the drafts drawer becomes disabled again.  I am using Wordpress.com App version 1.2.7 on OS X 10.11.3 (El Capitan).
