### ISSUE TITLE
Activity Log: don't show empty days before activation

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#18974]
<img width="424" alt="captura de pantalla 2017-10-18 a la s 17 11 05" src="https://user-images.githubusercontent.com/1041600/31740349-735c7dac-b427-11e7-8139-088783850d58.png">

**Comment by MichaelArestad** [comment]
We should combine them using exact styles to the empty days. It should look like this:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1123119/31740542-ec1ef260-b40e-11e7-9ae4-8506d0e7bc0e.png">
