### ISSUE TITLE
Jetpack Thank You Page: send users to Jetpack dashboard after purchase

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#18970]
The new thank you page v2 recently launched. It now has a 'view your site' link on it:

![image](https://user-images.githubusercontent.com/437258/31736618-48580496-b413-11e7-9476-e5588bbf83ee.png)

Can we change that link to go to the site's Jetpack dashboard instead? We have newly improved 'warm welcome' content there and it will help them further set up their Jetpack features.

cc 
@beaulebens @MichaelArestad 

@johnHackworth and company

**Comment by richardmuscat** [comment]
🚢 it!
