### ISSUE TITLE
Comments: Relative date not rendering correctly 

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#18973]
When looking at the comments view noticed that two comments were displaying with "In 2 hours" for the relative time stamp. 

It was happening for recent comments on p3fqKv-5Sx-p2

<img width="901" alt="screen shot 2017-10-18 at 12 58 33 pm" src="https://user-images.githubusercontent.com/161697/31739828-20bf1ee2-b404-11e7-9116-d6471a8038b5.png">

**Comment by rodrigoi** [comment]
@megsfulton apparently this is a problem with the timezone setting of the site. That's the value we are using to convert the GMT+0 timestamp of the comment to the user's timezone.

![screen shot 2017-10-27 at 12 52 31](https://user-images.githubusercontent.com/233601/32113149-d1fd03b4-bb15-11e7-9700-d19757c5abbf.png)

I'm looking for alternatives if the user has not configured the site's timezon.
