### ISSUE TITLE
Comments: Consider unicode whitespace characters when checking for missing post titles

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#18993]
See: https://github.com/Automattic/wp-calypso/pull/18884#pullrequestreview-70426208

> If we have unicode whitespace characters we'll still get a visual blank. the RegExp `\s` though I believe takes those into consideration, so if we wanted to iterate…

```js
const getTitle = ( post, comment ) => {
	const ws = /^\s*$/;
	const title = decodeEntities( get( comment, 'post.title' ) );
	if ( ! ws.test( title ) ) {
		return title;
	}

	// might `post` be `undefined`?
	// if not, we can just use `post.excerpt`
	// and leave out the `get()`
	const excerpt = stripHTML( get( post, 'excerpt' ) );
	if ( ws.test( excerpt ) ) {
		return excerpt;
	}

	return translate( 'Untitled Post' );
}
```

**Comment by gwwar** [comment]
Could you explain the use case here a bit more @Copons? This is to fix when we have a false positive for having a title with some visible content?

**Comment by Copons** [comment]
This should be in case the title is a [Unicode whitespace character](https://en.wikipedia.org/wiki/Whitespace_character#Unicode), which checks 👍, but then shows up as blank.
