### ISSUE TITLE
My debug messages not shown 

### ISSUE THREAD

**Issue by dinarAkv** [Automattic/wp-calypso#18994]
I try to make my own debug messages during contribution. As I understand I have to use debug command.

I import debugFactory in some component:

`import debugFactory from 'debug';`

than I declare debug constant:

`const debug = debugFactory( 'calypso:components:my_debug_message' );`

After that I use it in some of method of react component:

`I try to make my own debug messages during contribution. As I understand I have to use debug command.

I import debugFactory in some component:

`import debugFactory from 'debug';`

than I declare debug constant:

`const debug = debugFactory( 'calypso:components:my_debug_message' );`

After that I use it in some of method of react component:

`onClick:function(){
      
          debug( 'MY_FIRST_DEBUG_MESSAGE');
          // Some code here
      }`
        

and turn on all debug messages in chrome console:

`localStorage.setItem( 'debug', '*' );`

I definitely shure that this method is called and I see other debug message
but I don't see my own debug message.

How can I show my own debug message in browser console ?`

**Comment by alisterscott** [comment]
Hello @dinarAkv 

Could you try using simple `console.log( 'message' )` statements?

**Comment by dinarAkv** [comment]
Hello, **alisterscott**, 
It is strange but method ` debug( 'MY_FIRST_DEBUG_MESSAGE');` begin to work when I run app next day. I don't know why it doesn't work before. :) But now it works.

I tried to use console.log( 'message' ). But I have error message in my Atom editor:
"Unexpected console statement. (no console)"  I think it has forbidden to use console.log command.

Thank you  everybody for help. :)
