### ISSUE TITLE
Server Side Rendering: Move global app state to a (flux) `ApplicationStore`

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#190]
Outtake from discussion at 9287-gh-calypso-pre-oss

> Accept `section` prop as well here. Normally the section is set via `context.layout.section` I think, which is an anti-pattern.

> I think you mean `context.layout.setState()`, but I agree that it is something that should probably change. We probably should have an `AppStore` or something that holds global app state that can be updated via actions. As it is, we're basically treating the Layout instance as singleton.

> I like that. It would be cool to tidy the [getDefaultContext()](https://github.com/Automattic/wp-calypso/blob/master/server/pages/index.js#L107) data into an `AppStore`.

**Comment by ockham** [comment]
We now have a `setSection` Redux action and corresponding reducer, so I'm closing this. (No immediate need for anything else from `getDefaultContext()` to convert to a Redux subtree.)
