### ISSUE TITLE
Comments: consider disabling the bulk edit button and sorting when there are no comments.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#19019]
Currently, the Bulk Edit button and sorting are always enabled, even if there are no comments to apply them to. What do we think of disabling them in empty comment situations?

![screen shot 2017-10-19 at 11 34 48 am](https://user-images.githubusercontent.com/349751/31787748-8b39ac3e-b4c1-11e7-970b-9d59e63ba675.png)

**Comment by kwight** [comment]
cc/ @megsfulton

**Comment by megsfulton** [comment]
Good idea!

What do we think about also disabling the "Newest/Oldest" toggle as well?

**Comment by kwight** [comment]
Indeed, which leads to another question: disabled, or removed? Could be weird to see the controls toggling on and off when selecting between different statuses though.

While the button has styles for `disabled`, the sorter does not. But it looks like I could add equivalent styles for the `<SegmentedControl>` component – does that sound right, or is a disabled segmented control... weird?

**Comment by megsfulton** [comment]
>Indeed, which leads to another question: disabled, or removed? Could be weird to see the controls toggling on and off when selecting between different statuses though.

I had the same thought originally and ended up in the same place. 

Although after thinking some more, it might not be that weird to remove them both and think I might prefer that approach. If you toggle between Traffic and Insights in stats you'll see the button options at the top change.
