### ISSUE TITLE
Settings: Category descriptions cannot be removed

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#19027]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/taxonomies/category/
2. Edit a category with a description
3. Remove the entire description
4. Save
5. Edit again - the category description is still there

#### What I expected
To be able to delete a category description

#### What happened instead
The category description will only save if it has a character in it

#### Browser / OS version
Chrome, firefox, safari

#### Screenshot / Video
![setwritecatedit](https://user-images.githubusercontent.com/8921630/31797144-ae64a28e-b4e1-11e7-8e54-38a3dbad482e.gif)

**Comment by ShreyaSingh10** [comment]
@spncrb I tried reproducing the issue and yes if the string length is zero it doesn't update. I also tried to fix the issue, Looks like wpcom library is not updating the term which is passed to it properly. May be you can suggest a workaround or I create an issue on wpcom repo for this.

The line where the change is reverted back to previous string is : https://github.com/Automattic/wp-calypso/blob/master/client/state/terms/actions.js#L81

and further in latter promises it sees the previous string.
