### ISSUE TITLE
Editor: Flash of form elements before editor loads

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#19029]
#### Steps to reproduce
1. Open https://wpcalypso.wordpress.com/ in a new window
2. Navigate to posts 
3. Click title of a published post 
4. Before the editor screen loads there's a flash of form elements in the background

This only happens for the first post clicked and only when it's a new session / window. 

#### Browser / OS version
Mac OS Chrome 

#### Screenshot / Video
<img width="1320" alt="screen shot 2017-10-19 at 4 40 21 pm" src="https://user-images.githubusercontent.com/161697/31799006-55402cea-b4ec-11e7-9a02-be23157abe55.png">

Zip file contains a video - Sorry for the phone video, when I had quicktime screen capture running the bug wasn't reproduce-able. You can see the issue at :02s 
[IMG_0011.TRIM.MOV.zip](https://github.com/Automattic/wp-calypso/files/1400326/IMG_0011.TRIM.MOV.zip)

**Comment by jeremeylduvall** [comment]
I think this is the same issue discussed in #18703? I'll close this issue and crosslink it there. I think it's a result of #18500 where we moved some stylesheets to dedicated bundles that are now downloaded at specific routes.
