### ISSUE TITLE
Free Trials: Indicate the features the user has used in `PlanFeatures` dynamically

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1904]
We should indicate whether or not a feature is in use by removing the CTA button next to it in `PlanFeatures` (design in #1151) or stating that it is in use if the plan is in the grace period (design in #1471).

**Comment by fabianapsimoes** [comment]
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.
