### ISSUE TITLE
Store Orders: Should order total display the total after partial refunds?

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#19053]
If an order is partially refunded, we show the original total, then the -$X refunded below that, but we don't tell the user what the remaining total is -- what money they're actually still getting. Same thing on the order list page, we list order totals without indicating any refunded orders.

Example:

![calypso](https://user-images.githubusercontent.com/541093/31840480-85b22442-b5b3-11e7-9d81-d81e087dac3e.png)

In wp-admin, the total amount is crossed out next to a new value, the remaining order total after the refund:

![wp-admin](https://user-images.githubusercontent.com/541093/31840479-85a27916-b5b3-11e7-8095-92a9bc497c26.png)

I discovered this because I'm (accidentally?) including the refund in my total calculations when editing orders in #19047. IMO we should add the total-minus-refund somewhere on this table, and also on the orders list table. (If we don't, I should update `getOrderTotal` to not include the refund)

cc @kellychoffman @jameskoster

**Comment by ryelle** [comment]
This is kind of related to #16662 - which deals with showing the discounts applied by using coupons.

**Comment by kellychoffman** [comment]
Thanks for bringing this up. 

What about something like this? I'm not sure if "remaining total" is the best term, tho. What do you think? 

<img width="738" alt="screen shot 2017-10-23 at 1 57 06 pm" src="https://user-images.githubusercontent.com/5835847/31910249-1b8a9074-b7fa-11e7-8eb1-ef8176aaa916.png">
