### ISSUE TITLE
Simple Payments: Limit on quantity of items available for sale

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#19062]
Currently, if someone is selling an item, you can use the Simple Payments button to make undetermined no. of purchases.

So, let's say you had 20 items in stock that you wanted to sell, but 50 people visited the page/button and placed an order.

What are you going to do about the rest of the payments that were made?! When creating a Simple Payments button, there can probably be an (optional?) field where you can specify number of items to sell and once that number is reached, the button will probably get disabled or say "sold out".

#### Screenshot

Something like this (quantity available until SOLD OUT):

![image](https://user-images.githubusercontent.com/6505293/31858099-bc432168-b708-11e7-9b22-6feeb4058f97.png)

#### Context / Source
Report in #749142-zen 

/cc @iamtakashi

**Comment by iamtakashi** [comment]
Thanks for sharing the report. Noted!

**Comment by alisterscott** [comment]
Confirming this enhancement is still relevant and not implemented as yet

#bug-scrub #pre-gutenburg-bug-purge
