### ISSUE TITLE
Signup: Design Type Flow start: boxes not properly layouted

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#19068]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/design-type

#### What I expected

Boxes aligned centered.

#### What happened instead

They look left aligned, making space for a non-existant fourth box.

#### Browser / OS version

Opera 48.0 on OS X (layout engine: Chrome 61): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.50

#### Screenshot / Video

![screen shot 2017-10-23 at 11 32 09](https://user-images.githubusercontent.com/203408/31882215-52721ef4-b7e6-11e7-86e8-98caa800e6cb.png)

**Comment by alisterscott** [comment]
We no longer have this screen in sign up, the current starting screen is: https://wordpress.com/start/about

<img width="1194" alt="screen shot 2018-03-06 at 5 18 18 pm" src="https://user-images.githubusercontent.com/128826/37019038-65ec769c-2162-11e8-8da0-7a2dcddd76fc.png">
