### ISSUE TITLE
Store: Don't allow label purchase before order is paid for

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#19079]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/orders/{DOMAIN}
2. Click on an order that is "Payment Pending" and requires shipping
3. Note that Print Label & Fulfill is enabled even though the order isn't paid for yet.

#### What I expected
- I expected to have to click on "Mark as Paid" before the "Print Label & Fulfill" button would enable/appear.

#### What happened instead
- I could ship product prior to being paid for it.

#### Screenshot / Video

<img width="789" alt="screen shot 2017-10-23 at 11 29 57 am" src="https://user-images.githubusercontent.com/1595739/31906438-f619d5c0-b7e5-11e7-82ed-55609eb8ba22.png">

**Comment by timmyc** [comment]
The Print Label option is no longer shown on orders that are pending payment - the "Fulfill" button is shown. So closing this one out.
