### ISSUE TITLE
Jetpack Sites: Cannot embed scripts

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#19078]
#### Steps to reproduce
1. Starting at the editor in html mode for a Jetpack connected site
2. Paste or type some script tags with some code
3. See script tags removed

1. Open a post/page from a Jetpack connected site with Javascript tags in it
2. Find all removed
3. Draft saved, with them removed

#### What I expected
To be able to use Javascript on a Jetpack connected site (for example, embeds, demos, examples)

#### What happened instead
Unable to use Calypso without destroying (for lack of a better term, although a bit harsh) posts/pages

#### Browser / OS version
N/A

#### Context / Source

Jetpack users are not prevented from using Javascript on their own site.

**Comment by formosattic** [comment]
+1 #2168995-hc

In the meantime, the HTML editor in the WP-admin dashboard still allows for JavaScript code to be embedded.

**Comment by tijosh** [comment]
Another report of this in #18487469-hc

**Comment by Greatdane** [comment]
Unable to replicate. Script looks to work both in classic editor plugin and using the HTML block in the block editor. 

Closing
