### ISSUE TITLE
Store: No Loading Indicator on Dashboard

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#19087]
When loading the store dashboard on an empty state tree, things are very slow to render and there is no visual indicator of that things are loading. With the API sandboxed today it was so slow that I thought something was broken and was checking the console.

#### Steps to reproduce
1. Click Store from the Stats Page ( ideally sandbox the API for ultimate slowness )
2. Notice no loading indicators are shown

![dashboard-load](https://user-images.githubusercontent.com/22080/31919246-e1e43dfe-b815-11e7-9448-d0619f864371.gif)

**Comment by timmyc** [comment]
Did some investigating into performance of the dashboard p90Yrv-il-p2

**Comment by timmyc** [comment]
@kellychoffman or @jameskoster any preferences for a loading state on the dashboard?

**Comment by kellychoffman** [comment]
Can we have three different ones based on if its a store in setup mode, a store with orders, and a store without orders?

**Comment by timmyc** [comment]
> Can we have three different ones based on if its a store in setup mode, a store with orders, and a store without orders?

Sure... I _think_ setup mode does have a loading indicator already, but will have to confirm.

**Comment by kellychoffman** [comment]
Ah right, it does. Okay so since we can have three different loading screens, let's just do a basic loading indicator that includes the white boxes to indicate the cards with thin rectangular lines to indicate generic content within.
