### ISSUE TITLE
Jetpack site: Wrong tags display in Reader 

### ISSUE THREAD

**Issue by htdat** [Automattic/wp-calypso#19094]
## Steps to Reproduce

1. https://prettyupdates.com/nutriglow-c-c-creme-review/ has these tags `Beauty, CC cream review, Makeup, Nurtiglow CC cream review, NutriGlow, Nutriglow CC cream, NutriGlow Complete Color correction créme, Product review` 

2. https://wordpress.com/read/feeds/68105059/posts/1602817215 - this post on Reader shows `beautyCC cream reviewLakme Sun-kissed Bronzerlogo designmakeup` 

### Expected Result

Tags should be the same. 

### What we have asked the user 

* Run full sync manually sometimes. 
* Make "feeds" available. 

## Site info

- Site URL: https://prettyupdates.com
- Jetpack Debug URL / VP MC: https://jetpack.com/support/debug/?url=https%3A%2F%2Fwww.prettyupdates.com%2F - Green 
- Internal ref: 716596-zen and p5PDj3-48m-p2

**Comment by bluefuton** [comment]
We rely on the synced data in the shadow blog, so not technically a Reader bug. Closing for now.
