### ISSUE TITLE
Jetpack: domain mapped to WordPress.com site and pointing to Jetpack site creates confusion in WordPress.com site interface

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#19097]
#### Steps to reproduce
1. Start by creating a WordPress.com site.
2. Add a domain mapping to that site, to map it to a domain you already own.
3. Change the domain's NS records to point the domain to a new hosting provider.
4. Create a new site on that host, and install WordPress.
5. Install and activate Jetpack.
6. You can now access that site's settings in Calypso and will see the following message in the sidebar when viewing the WordPress.com site that used to be available at the mapped domain:

![screenshot 2017-10-24 at 11 25 00](https://user-images.githubusercontent.com/426388/31935022-016b30d6-b8ae-11e7-8ebe-6ee036245b10.png)

That's an error, since the site does not redirect to itself: it redirects to the mapped domain.

**Comment by jeherve** [comment]
Related: #6779

**Comment by klimeryk** [comment]
Closing this as stale.

**Comment by jeherve** [comment]
It still seems to be an issue though:

![image](https://user-images.githubusercontent.com/426388/106616375-c8d25400-656d-11eb-9d72-0c691bcd5e9b.png)
