### ISSUE TITLE
Stats: Support "total" Views by Country

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#1910]
The pre-Calypso stats page allows users to navigate to [a view](https://wordpress.com/my-stats/?view=geoviews&summarize&numdays=-1) of the "total" views by country with steps:
- Clicking on the `Summaries` link in the module
- Clicking `Since February 25, 2012` (for sites created on or before that date) OR `All time` if it was created after that date

The "All-time" stats are currently on the Insights page:
<img width="731" alt="screen shot 2015-12-21 at 11 43 47 pm" src="https://cloud.githubusercontent.com/assets/1587282/11948013/c0992d3e-a83c-11e5-84f8-a6671a998133.png">
...so, that'd be the logical place to put this.

**Comment by chris-budd** [comment]
Another request for this (2970988-t)
