### ISSUE TITLE
Site Settings: Can't disconnect broken Jetpack site

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#19117]
I know we have similar issues open but this one seems different than what I've seen before.

#### Steps to reproduce
Start with a connection to a Jetpack site that is no longer online and which is getting notifications about the site being down.

1. Starting at URL: wordpress.com
2. Click on My Sites to select the site as directed [here](https://en.support.wordpress.com/disconnect-jetpack-sites/)
3. The site may not show up or My Sites may be flashing / loading, or the site may not be listed there at all.

#### What I expected
Users should be able to disconnect a site

#### What happened instead
They can't select the site to disconnect it.  Even if I try to go to https://wordpress.com/settings/general/sitename.com I get "Finishing Setup..." and flashing "Loading" sign on the left.

#### Browser / OS version
OSX/Chrome (Both current)

#### Screenshot / Video
![screen shot 2017-10-24 at 12 05 39 pm](https://user-images.githubusercontent.com/3476361/31960032-b8e77904-b8b3-11e7-80d3-579d33247832.png)

#### Context / Source
We frequently run across this in the forums:
http://en.forums.wordpress.com/topic/my-sites-doesnt-work

**Comment by supernovia** [comment]
http://en.forums.wordpress.com/topic/please-remove-me-from-jetpack-for-this-site

**Comment by supernovia** [comment]
http://en.forums.wordpress.com/topic/remove-sites-from-my-sites-2

**Comment by annezazu** [comment]
@ockham  something to think about with the disconnect survey you are working on is whether folks can disconnect if their site is down to begin with :)

**Comment by rachelmcr** [comment]
I started with a previously connected Jetpack site that is currently down. (It was a temporary site and I received a Jetpack Monitor notification when it went down.) The Jetpack debugger gave an unknown error, and this was the detailed connection error:

> The Jetpack site is inaccessible or returned an error: Jetpack: [http_request_failed] cURL error 56: Recv failure: Connection reset by peer [-10520]

I followed these steps to disconnection the site:

1. Start at this URL: https://wordpress.com/
2. Click on My Sites.
3. Open Settings.
4. Select "Manage Your Connection" which takes me to this page: https://wordpress.com/settings/manage-connection/{site_address}
5. Select "Disconnect from WordPress.com" which takes me to this page with the disconnect survey: https://wordpress.com/settings/disconnect-site/{site_address}
6. Confirm I want to disconnect.

Result: The site was successfully disconnected.

If some users are still getting the issue described in the original report, it would help to know more about the state of their site so we can investigate that specific case, as it doesn't seem to be an issue for all broken Jetpack sites.

**Comment by coder-karen** [comment]
Just adding to this issue, the same problem was encountered by a user (in 1230985-zen) whose site does not exist anymore, and as such the site did not show up under My Sites in order for them to be able to disconnect Jetpack.

They had been receiving repeated emails from Jetpack saying their site was down but couldn't seem to do anything about it.

This has been resolved now but is another example of confusion in the Jetpack disconnection flow (following the same steps to reproduce as explained by @supernovia ).

**Comment by supernovia** [comment]
We still see this fairly often

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES

_Since the last activity here, there's also been quite a few improvements have rolled out to the way Jetpack connections break, are fixed, and notify customers. Most recently: pdKhl6-25S-p2_
