### ISSUE TITLE
Store Stats: Examine Masonry Layout

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#19125]
As we expand widgets, we are encountering possibilities of widgets of differing widths/lengths. A masonry layout may be a solution. Look into this as a possibility.

Example:
CSS masonry layout
https://codeburst.io/how-to-pure-css-masonry-layouts-a8ede07ba31a

**Comment by timmyc** [comment]
FWIW @youknowriad explored this for Site Stats and the experience wasn't ideal. Not saying we should entirely give up on the idea, but it was tried once before :)
