### ISSUE TITLE
Help: 'Sorry! We just missed you as our Happiness Engineers stepped away.' notification potentially confusing to users.

### ISSUE THREAD

**Issue by hafizrahman** [Automattic/wp-calypso#1912]
The notification `Sorry! We just missed you as our Happiness Engineers stepped away.` that appears when no operators are available makes sense in the context of our Contact Form:

![chat-ticket](https://cloud.githubusercontent.com/assets/2738252/11636546/a808e370-9cea-11e5-9a4b-df007894b2cd.png)

(Picture shamelessly re-used from #1338)

However, this notification also appears in Calypso, and in this context I feel it can be potentially confusing to users:

![sorry-we-missed-you](https://cloud.githubusercontent.com/assets/266376/11952293/c2e41774-a8c9-11e5-9b3b-fdd6302555d1.png)

If I understand correctly, the notification appears if:

1) The user is eligible for chat form display in Calypso
2) They have the chat form expanded
3) No operators are online

During day-to-day support work, especially non core US hours where coverage is not yet perfect, it's common for operators to be away and available again from time to time. This means that for users who have the chat box expanded, they can get that notification repeated again and again.

I'm not entirely sure how frequent this notification shows up: if in an hour no operators are available five times, will the users see the notification five times as well?

There's also the issue of wording here, I think. The notification mentions nothing about live chat and the only clue users can have to relate to it is the expanded live chat form, which is easily missed and located far away from the notification's location. (Example of user confusion in 285461-chat)

It's also possible that the user is not really looking for help (they just have the chat form expanded out of curiosity, for example), so saying that HE's missed them does not make sense.

One solution is to display this message inside the chat form itself in Calypso, instead of as a notification.

**Comment by designsimply** [comment]
<blockquote>2) They have the chat form expanded</blockquote>

I think I've seen this happen without having the chat form expanded. Because of that, I found it more jarring than confusing. Maybe consider keeping the notice limited to the normal chat location instead of as a giant dashboard noticed for a service that may not even currently be active.

cc @dllh

**Comment by dllh** [comment]
I also experienced this today after not having visited the contact form for a long time:

<img width="1141" alt="screen shot 2015-12-31 at 8 05 35 am" src="https://cloud.githubusercontent.com/assets/2738252/12064777/a6a8c308-af99-11e5-94e5-3e4c2581933e.png">

**Comment by omarjackman** [comment]
@designsimply @hafizrahman @dllh were you all on safari/osx when you noticed this?

**Comment by annezazuu** [comment]
I experienced this today in chrome: https://cloudup.com/ckc8TQ2OnFd. Even after dismissing the errors repeatedly.

**Comment by dllh** [comment]
I was in chrome on osx.

**Comment by folletto** [comment]
Ah, I just saw this today, opened #2076 since I couldn't find this thread.

> 1. It was random, I can't find a specific pattern to make the message appear.
> 2. It's on my account, and I was on the Stats page of my Jetpack site, which is Primary.
> 3. I got both the green and the orange message, at different times, a couple of times each.

Also I noted:

> Overall, even in the context of the PR above, it seems a rather overwhelming message, and in a weird position (top of the screen instead of where Live Chat is), to be a Live Chat related one. I'd consider a different design in a future iteration.

**Comment by designsimply** [comment]
> @designsimply @hafizrahman @dllh were you all on safari/osx when you noticed this?

I think so, yes, but I didn't see the notice that was offset that @dllh posted. I saw what @hafizrahman posted (large banner, correctly position, but surprisingly large considering it's just an afk notice).
