### ISSUE TITLE
Activity Log - style discarded events

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#19132]
This is where I ended up on the designs for the discarded states of events. I think it can be done with CSS based on what @eliorivero did in his [previous PR](https://github.com/Automattic/wp-calypso/pull/19116) about this.

#### 1. Normal state

![02-2 copy](https://user-images.githubusercontent.com/1123119/31979613-c3aa5676-b904-11e7-8bd5-012f89b9ad53.png)

#### 2. Pending rewind

![02-3 copy 5](https://user-images.githubusercontent.com/1123119/31979651-f9eb2e72-b904-11e7-899f-864bd9970191.jpg)

#### 3. Rewinding

![02-2 copy 5](https://user-images.githubusercontent.com/1123119/32235948-743a0858-be26-11e7-94b6-807074c33706.jpg)

#### 4. Rewind complete

![02-2 copy 6](https://user-images.githubusercontent.com/1123119/32235957-7a566268-be26-11e7-9b10-3d448d2d2956.jpg)

**Comment by rickybanister** [comment]
I notice a small discrepancy in the design here—when you are viewing the rewind confirmation you see the event icon is 'hollow', but once the rewind is in progress and afterward the event icon is back to color-ified. 

I think it would be most clear if they remained hollow forever once discarded. And I wouldn't mind an explicit 'discarded event' flag in there somewhere.

**Comment by MichaelArestad** [comment]
They should be hollow. That was just an oversight. Fixing.

**Comment by MichaelArestad** [comment]
Update: modified mockups to have correct icon hollowness.

**Comment by rickybanister** [comment]
Awesome
