### ISSUE TITLE
Activity Log: after a successful restore, add a new item mentioning it

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#19161]

**Comment by samhotchkiss** [comment]
@eliorivero-- A new item where?

**Comment by eliorivero** [comment]
This is solved now that we have live updates. This issued referred to adding a new event to the activity log like
<img width="760" alt="captura de pantalla 2017-12-05 a la s 12 36 30" src="https://user-images.githubusercontent.com/1041600/33624154-0bb9cd00-d9b9-11e7-92a1-aa44c0064b7e.png">
instantly after restoring but now that we have live updates this is no longer relevant so I'm closing it.
