### ISSUE TITLE
Activity Log - Download a backup

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#19163]
Folks need a way to download a backup from the activity log. Luckily, we have designs for that!

#### Flow from start to finish

To keep this issue a bit tidier (instead of 7 or 8 huge screenshots), I've compiled a couple Cloudup galleries with the screens in order.

[Cloudup gallery](https://cloudup.com/cC_PvZzmnUe)

1. User clicks `Create a backup` using the three dot menu on an event
2. A prompt opens up exactly like the rewind prompt and in the same spot
3. User clicks `Create download` button
4. Download creation starts and shows the progress at the top (just like a rewind)
5. Download completes showing the same success box at the top with the option to download
6. The user downloads the zip

#### Flow from email/notification

This is just a portion of the above flow, but is one a user might go through if they leave the Activity Log while it is creating the backup to do something else. When the download is created, we send them an email and notification that directs the user back to the activity log. You can see how these might look in the following gallery.

[Cloudup gallery](https://cloudup.com/cDRjG-X7TQ7)

#### Expired download

We should only keep a download around for a day or so once it is created. After that, we delete it from our servers. If a user navigates back to the Activity Log looking for it via their email or notification, we should show a notice like this:

![step 5 5 - activity stream guided tour - event options copy 3](https://user-images.githubusercontent.com/1123119/32024355-70b823cc-b999-11e7-95a1-53662867d3b7.jpg)

We might try an iteration of it using the Upgrade Notice, but the principle idea would be the same.

**Comment by eliorivero** [comment]
Mark created D8021 with endpoints for handling this.
