### ISSUE TITLE
Add tracking for happychats started from contact form

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#19165]
Right now, we have stats that shows overall chats started from the contact form page but we don't have specific data on what this looks like for **Jetpack users**. Can we get this added in?  I plan to use this to help with hiring requirements and to help understand where our users contact us the most and least.

**Comment by annezazu** [comment]
Nudging on this @johnHackworth  :) Thanks for all you've been doing to get other stats in place.

**Comment by annezazu** [comment]
https://mc.a8c.com/tracks/trends/?eventname=calypso_help_live_chat_begin&compareby=prop&prop=siteidlabel

This was done a while back :) Closing.

**Comment by kraftbj** [comment]
Nice.
