### ISSUE TITLE
Editor: Edit link button doesn't work in RTL visual editor

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#19189]
#### Steps to reproduce
First make sure the interface is set to an RTL language.  Then:

1. Starting at URL: wordpress.com/post
2. Add a link in visual editor
3. Try editing the link

#### What I expected
To be able to click the edit button

#### What happened instead
The hover goes away just as I reach edit, unless I'm extremely persistent. Users sometimes accidentally click the link instead, too.

#### Browser / OS version
Mac OSX, Chrome (both current)

#### Screenshot / Video
https://cloudup.com/ca0PocfBi1M

#### Context / Source
Brought up in a [forum thread](https://en.forums.wordpress.com/topic/unable-to-edit-links-in-float-bar-reported-as-a-bug-in-wordpresscom?replies=8). Similar issues have been reported in wp-admin.

**Comment by yoavf** [comment]
This happens in recent chrome versions only, see: https://core.trac.wordpress.org/ticket/42018
I'll port the change from https://core.trac.wordpress.org/changeset/41643 to calypso.
