### ISSUE TITLE
NUX: Dead button on signup confirmation screen

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#19208]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/new?ref=calypso-selector
2. Go through the process to create a new site
3. Select a free URL and a free plan
4. Continue to the confirmation screen saying "Congratulations! Your site is live."

#### What I expected
To be taken to my site when clicking the `View My Site` button

#### What happened instead
Nothing. The button does not do anything and there are no console errors.

#### Browser / OS version
Noticed in Firefox 56.0.2 on Mac OS 10.12.6 Also confirmed in Chrome 61

#### Screenshot / Video
![wordpress_com](https://user-images.githubusercontent.com/11873759/32096269-3c3970d8-bb06-11e7-91f7-6b1c7a4a12be.png)

The page URL of the confirmation page displays as https://wordpress.com/start/plans in my browser, and on refresh redirects back to https://wordpress.com/start/design-type, restarting the new site process I'd just finished

If a paid plan and domain is purchased, the confirmation page displays https://wordpress.com/checkout/thank-you/{site URL} as the URL, and the button functions correctly.

#### Context / Source

Disovered this when I created a new site in order to test a different issue.

**Comment by alisterscott** [comment]
I can no longer reproduce this, I see the checklist when going through the free site signup flow:

![signup from new site](https://user-images.githubusercontent.com/128826/43438164-234cf6ea-94d0-11e8-8409-99ef2ed20e72.gif)

Closing for now
