### ISSUE TITLE
Store: Variation values cannot be edited

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#19209]
After creating a product variations, in this case the colors "Yellow", "Pink" and "blue" (no capitalized)  for a certain product, the user intends to correct the typo ( from "b" to "B" in "Blue" ) but is not possible, she can only delete the variation in order to fix it.

This can be seen here: p90Yrv-es-p2 from 37:20 to 37:50:

**How to replicate:**

- Go to http://wordpress.com/store/product/domain.com
- Create or edit a new product
- Add variations to the product, for example "Color" and some colors
- Variations will show up below, they are clickable in order to edit its details, click on one of them

<img width="1106" alt="screen shot 2017-10-27 at 11 22 34" src="https://user-images.githubusercontent.com/3812076/32098219-49d57222-bb0c-11e7-97fd-bc279726ca40.png">

- See variation details screen
- Try to change the variation name, see is not possible

When clicking on the value to edit its details, the value string itself cannot be edited, for example from "blue" to "Blue"

<img width="1128" alt="screen shot 2017-10-27 at 11 11 11" src="https://user-images.githubusercontent.com/3812076/32098230-55f47c4c-bb0c-11e7-82a7-42189cff111d.png">

**Comment by alaczek** [comment]
I wanted to reopen this issue, as I had the same thing reported in chat today. Editing of variation names was not possible - when I selected any of the variation name fields and tried to modify it in any way (like hit backspace or add space at the end), nothing would happen, and then the page would go completely grey (it did not reload though). No content would appear on the page, until I actually reloaded it in the browser.

Here's the video of the issue: https://cloudup.com/cQjNnexUDqX

I noticed this JS error in the console, when the page turned grey:
```
TypeError: Cannot read property 'join' of undefined
    at t.value (woocommerce.e8c3f45e84f3280166e1.min.js:10)
    at Array.map (<anonymous>)
    at t.value (woocommerce.e8c3f45e84f3280166e1.min.js:10)
    at xs (147.70b22636fc8f672caf7e.min.js:79)
    at Ys (147.70b22636fc8f672caf7e.min.js:79)
    at pi (147.70b22636fc8f672caf7e.min.js:79)
    at hi (147.70b22636fc8f672caf7e.min.js:79)
    at Ki (147.70b22636fc8f672caf7e.min.js:79)
    at Vi (147.70b22636fc8f672caf7e.min.js:79)
    at Ui (147.70b22636fc8f672caf7e.min.js:79)
```

Customer report: 2877094-hc
