### ISSUE TITLE
Email forwarding option not showing up under "Email" settings screen

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#19222]
User reported this on 587858-hc and could replicate it, If on the domain management screen you go to "Domains" > "Email" you will see the email forwarding option, however if you go to "Email" only the G Suite nudge will show up.

> "I found this page:
> https://en.support.wordpress.com/email-forwarding/
> However when I click the "email" tab as instructed, the page I get looks nothing like the page in the help.
> I do not seem to have the option of an email address on this site."

**How to replicate:**

- Go to https://wordpress.com/domains/manage/ and choose one of your domains
- On the top you'll see My plan, Plans, Domains, Email

- Domains > domain.com > Email > Email forwarding the option shows up under the G Suite nudge

URL: https://wordpress.com/domains/manage/$DOMAIN/email/$DOMAIN

- When going to Email the option does not show up under the G Suite nudge

URL: https://wordpress.com/domains/manage/email/$DOMAIN

Example where email forwarding does not show up:

<img width="1095" alt="screen shot 2017-10-27 at 14 18 53" src="https://user-images.githubusercontent.com/3812076/32103752-16e80332-bb22-11e7-8f5f-4cafbc0aadfc.png">

The documentation seems to say correctly that `"You can configure Email Forwarding by Navigating to My Sites > Domains. On this domain management page, select the domain you want to connect to email forwarding to load that domain’s settings page. Select Email."` , however I'm not sure if this is expected to not show up under "Email" too, or is there something we should do about it, as can be confusing.

**Comment by jeremeylduvall** [comment]
Just a note that I think this might be similar to #12932. In that case, I had a previous PR up in #13081 that aimed to fix the behavior - just never caught on. I think some approach similar to that though should do the trick.

**Comment by cecoates** [comment]
Here's another user that couldn't find the email forwarding setting:

774948-zen

This isn't necessarily an every day occurrence due to how Gmail doesn't let you "reply" from the forwarded address, and so many people use Gmail, but when a user does go hunting for the settings it's normal for them to be confused.

**Comment by klimeryk** [comment]
This has been redesigned recently and now email forwarding is much more prominent:

<img width="1061" alt="Screenshot 2021-02-02 at 11 27 03" src="https://user-images.githubusercontent.com/3392497/106610086-3b3b3800-655e-11eb-93c8-cb79ff6ff7b9.png">

That might change a bit in the future, but we'll definitely try to keep it less hidden than before ;)
