### ISSUE TITLE
Checkout: Cart Checkout "Cannot read property 'paymentMethod' of undefined"

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#1923]
This is a special circumstance, maybe rarely encountered by users, but broken on WordPress.com nonetheless.

I've confirmed this bug appears in three circumstances:
1) When signing up for a no-cc free trial (not live yet, but original source of discovery)
2) When using credits to pay
3) When using a saved credit card to pay

The only way I've found to re-create the error is quite circuitous, but reliable.  More direct routes to checkout DO work, so this bug only works by following the steps:
1) Add a product to your cart, plans being the easiest (My Sites>Plans>Upgrade Now)
2) Click My Sites before checkout is completed (if you completed checkout now, it would work fine)
3) Click Plans again for the same site
4) Click on the cart, which now has 1 item
5) Try to checkout.  Nothing happens. With the console open, you will see this error in console:
![](https://cloud.githubusercontent.com/assets/8921630/11910483/7b89b732-a5ac-11e5-829e-b8375161ddbe.png)

Expanding the error:
![](https://cloud.githubusercontent.com/assets/8921630/11936153/d8ef6abe-a7c0-11e5-9f46-af76a1152a4e.png)

I've tested this in production, staging and on master with both new and old users.

There is an additional error that happens on page load as well:
![screen shot 2015-12-22 at 8 15 01 am](https://cloud.githubusercontent.com/assets/8921630/11960045/85afda9e-a885-11e5-83a9-01d03f7fc4a0.png)

(top error on load, 2nd error on checkout click)

Originally brought up in this PR:
https://github.com/Automattic/wp-calypso/pull/1787

**Comment by stephanethomas** [comment]
Great job finding a way to reproduce it reliably!
