### ISSUE TITLE
Comments: Edit mode does not allow changing the comment's timestamp.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#19252]
In `wp-admin`, the Edit Comment page (`wp-admin/comment.php?action=editcomment&c=x`) allows changing the comment's timestamp:

<img width="1477" alt="screen shot 2017-10-27 at 3 03 35 pm" src="https://user-images.githubusercontent.com/349751/32126973-8715a532-bb28-11e7-97f8-b56475cd614f.png">

Should we add this?

**Comment by gwwar** [comment]
I can't think of a proper use case, but let's see if anything comes up in our next interviews. cc @megsfulton

**Comment by KokkieH** [comment]
Had a request in 892059-f

According to the user their use case is to ensure comments appear at the top of the comments RSS feed once they are approved. It seems the order in which the comments actually appear on the site doesn't matter to them.

**Comment by gwwar** [comment]
>  their use case is to ensure comments appear at the top of the comments RSS feed once they are approved

Very interesting, thanks for reporting @KokkieH!
