### ISSUE TITLE
AMP settings do not have any impact on site

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#19259]
#### Steps to reproduce
1. In Calypso, go to Settings → Traffic → AMP
2. Change settings for AMP (turn on, turn off, change design)

#### What I expected
Switching these settings should change the way the site looks on mobile.

#### What happened instead
Changing these settings has no impact at all, and AMP seems to be solely controlled by the settings in WP-admin. When AMP is on, it has the default look/feel.

#### Screenshot / Video

Settings: http://prntscr.com/h3b82m
Customizer: http://prntscr.com/h3b7q9
Result: http://prntscr.com/h3b915

#### Other information
Reproduced at https://senffbugreportsamp.wordpress.com/

#user-report

**Comment by rachelmcr** [comment]
AMP is not used when visiting the front page of your site or archive pages, but it does show up when you visit individual blog posts from a Google search (as described in the [AMP support doc](https://en.support.wordpress.com/amp-accelerated-mobile-pages/)).

I checked your site but only the front page appears in Google search results for me. However, I searched for posts from en.blog.wordpress.com, and the front page shows the regular mobile view while individual posts show up with the AMP version.
