### ISSUE TITLE
Refreshing or visiting domains or plans page by URL shows the stats page or select site page

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#19262]
This looks like a regression introduced in https://github.com/Automattic/wp-calypso/pull/18962 as this was working before that commit.

This will probably cause a problem for HEs who provide customers with direct links to domains or plans pages as they won't work

cc @rcoll 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com as a single site user (user with one site)
2. Visit the domains page
3. Either refresh the page, or revisit the URL

#### What I expected

Domains page to still show

#### What happened instead

Stats page is showed (single site user)
Site picker is shown (multi site user)

#### Browser / OS version

All browsers

#### Screenshot / Video

![domains refresh](https://user-images.githubusercontent.com/128826/32151513-4279e92c-bd69-11e7-87dd-339afafca3f6.gif)

#### Context / Source

We'd also love to know how you found the bug:  #automated-testing - automated e2e tests found this

**Comment by seear** [comment]
@alisterscott Interested to know if #19339 fixes this issue?

**Comment by seear** [comment]
Confirmed fixed for me on wordpress.com

**Comment by alisterscott** [comment]
@seear Thanks!!! This fixed it. I was puzzled what was causing this!
