### ISSUE TITLE
Password characters on login form visible by default (mobile)

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#19267]
Password characters on the WordPress.com login form are visible by default (rather than hidden) on mobile devices.

#### Steps to reproduce
1. Go to https://wordpress.com/ using a browser on a mobile device
2. Select Log In
2. Go to the Password field
3. Starting typing your password

#### What I expected

Password characters to be hidden by default — which would match the behaviour of the login form on desktop browsers.

#### What happened instead

_Firefox & Safarai_
The visible icon was displayed by default and I could see the characters as I typed them in the password field.

_Chrome_
The hidden icon was displayed for a few seconds before switching to the visible icon. I could see the characters as I typed them in the password field.

#### Browser / OS version

Firefox (iOS and Android)
Safari (iOS)
Chrome (iOS and Android)

#### Screenshot / Video

_Firefox_

![wpcom-login-1](https://user-images.githubusercontent.com/11627765/32168081-156252cc-bd63-11e7-8e6c-949ce4f204ba.png)

![wpcom-login-2](https://user-images.githubusercontent.com/11627765/32168084-16a8cf08-bd63-11e7-90ab-66c24eec4fe7.png)

_Chrome_

![wpcom-login-3](https://user-images.githubusercontent.com/11627765/32168085-1a59c684-bd63-11e7-97a6-ab11a07c9e0b.png)

#### Context / Source

#manual-testing, #user-report

**Comment by abhishekgahlot** [comment]
This issue is related to #16929

**Comment by abhishekgahlot** [comment]
As per discussion on #16929 I am closing this issue.
