### ISSUE TITLE
Components: Search component doesn't highlight when selected

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#19283]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design
2. Click in the search field at the top, no highlight.
3. Type a letter, still no highlight.
4. Type a space, now it highlights.
5. Scroll down to any other component where you can enter text.
6. Click inside text field, notice it highlights correctly.

#### What I expected
I expected the search box to behave like other text fields visually.

#### What happened instead
No highlight 😞  ...until you hit space 😮 

#### Browser / OS version
OSX Chrome - Version 61.0.3163.100 (Official Build) (64-bit)

#### Screenshot / Video
![search-no-highlight](https://user-images.githubusercontent.com/945228/32180525-37248e78-bd60-11e7-863e-774ec024babc.gif)

#### Context / Source

This was found while testing a feature in Store in a PR: https://github.com/Automattic/wp-calypso/pull/19175#issuecomment-340019917

**Comment by ryelle** [comment]
The clear search button (the `X`) also does not highlight when you focus on it. To replicate, click into the search, then hit tab; you can hit enter to clear the input, but there's no indication that you're on the X.

**Comment by ryelle** [comment]
Looks like this was intentionally added (kind of) in #7905 – the highlight only shows up when the `accessible-focus` class is added to the `<body>`, and it's only added when we've detected "keyboard navigation", ie, arrow keys, tab, or space. So putting space in the search "turns on" the accessible-focus class, which enables the focus style. 

It seems like the answer would be remove the `accessible-focus` requirement, but it does end up looking like too much in the site-picker:

<img width="344" alt="screen shot 2017-10-30 at 2 56 08 pm" src="https://user-images.githubusercontent.com/541093/32189916-7e50b9da-bd82-11e7-9e05-68249f5f6120.png"> <img width="284" alt="screen shot 2017-10-30 at 2 57 37 pm" src="https://user-images.githubusercontent.com/541093/32189981-b33b1910-bd82-11e7-9c1f-fa53517a7f58.png">

Maybe we should conditionally style just those inputs to use accessible-focus? But then if you enter a space in your search, the blue border pops up. So maybe those inputs need a different focus style?

There's also the issue of the X's focus state, just adding the blue border doesn't look great:

<img width="557" alt="screen shot 2017-10-30 at 2 58 26 pm" src="https://user-images.githubusercontent.com/541093/32190121-25931b5c-bd83-11e7-9b80-ba59edf6f5f1.png">

**Comment by ryelle** [comment]
Fixed in #21866
