### ISSUE TITLE
Purchases: Fill credit card form with data upon loading Edit Card Details page

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#193]
On a purchase where a CC used as the payment method when you click "Edit Payment Method" the form loads up empty instead of allowing you to edit the CC details. If you then try to reenter your CC details, you can successfully update, however it adds it as a new credit card.

Also when you click the "Update Card" button it should disable to indicate processing.

**Comment by stephanethomas** [comment]
https://github.com/Automattic/wp-calypso/pull/485 takes care of the card holder name. We will handle the country and postal code in another pull request.

**Comment by stephanethomas** [comment]
I'm reopening this issue since we should also [populate the country and postal code](https://github.com/Automattic/wp-calypso/issues/193#issuecomment-159257700).

**Comment by fabianapsimoes** [comment]
> #485 takes care of the card holder name

The form is pre-filled when we click the Edit Payment Method button, but not when you click the Payment Method section.

![screenshot-wordpress com 2016-02-24 16-10-29](https://cloud.githubusercontent.com/assets/1248436/13289703/3338656a-db11-11e5-81f8-b67edf4ee3ea.png)

**Comment by gziolo** [comment]
As a part of #5074 fix I removed `editSpecificCardDetails` path. If we decide to implement this issue we should revert those changes. Otherwise we should completely remove logic related to filling credit card form with data upon loading.

**Comment by fabianapsimoes** [comment]
Removing this from `Amber: Backlog`, as it'd probably be better handled by Team Gold.

**Comment by gziolo** [comment]
It loads first name at the moment upon loading `Edit Card Details` page which okey. Closing this one. We can open new issue if we plan to change this logic.
