### ISSUE TITLE
Stats: click the links for each post on WP Admin, redirect to the general Stats page

### ISSUE THREAD

**Issue by htdat** [Automattic/wp-calypso#19315]
## Summary

I can replicate this issue. It looks like Calypso does not allow to access https://wordpress.com/stats/post/230/my-jetpack.com directly. 

## Steps to Reproduce

1. Go to WP Admin -> Posts (see the screenshot below).
2. Click `Stats`, the link looks like this https://wordpress.com/stats/post/230/my-jetpack.com
3. I get redirected to https://wordpress.com/stats

### Expected Result

I expect to see the stats for the specific post 
https://wordpress.com/stats/post/230/my-jetpack.com

### Actual Result

I get redirected to https://wordpress.com/stats

### Workaround 

1. Go to https://wordpress.com/posts/my-jetpack.com
2. In each post, click "Stats". 
3. I still can come to the link like this https://wordpress.com/stats/post/230/my-jetpack.com

## Other info:

Ref: 761195-zen

![2017-10-31_13-05-49](https://user-images.githubusercontent.com/10045087/32209719-494bf154-be3c-11e7-9188-503ab89f29b3.png)

**Comment by rachelmcr** [comment]
I can't reproduce this issue on a test Jetpack site. When I click the stats icon for a post on the Posts page in WP Admin, I'm directed to the Calypso stats for that post and it loads as expected without redirecting me.

Please reopen this issue with more details if you can still reproduce this issue under certain conditions!
