### ISSUE TITLE
Store: When editing a product sale, an end date before the start date can be selected.

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#19313]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/store/promotion/<site url>
2. Select "Individual Product Sale"
3. Try setting the end date before the start date.

#### What I expected
To not be allowed to do this.

#### What happened instead
It was allowed! 😮

**Comment by justinshreve** [comment]
I can't seem to reproduce this, so I'm going to close it.

Days become blocked out on the end date calendar if you change your start date. If you do happen to get an earlier day selected, validation seems to catch it before saving.
