### ISSUE TITLE
Reader: "Ghost" followed sites remains after deleting own site

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#19328]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Create new site. tested on both free & personal plan 
3. Check your following sites. New site should be there: https://wordpress.com/following/manage
4. Delete newly created site
5. Check your following sites. "Ghost" record would be there

#### What I expected

Site is unfollowed once it was deleted

#### What happened instead

Site remains in my following sites as empty record (without name, URL etc)

#### Browser / OS version

Safari / Mac OS 10.13

#### Screenshot / Video
<img width="1359" alt="manage following wordpress com 2017-10-31 15-01-48" src="https://user-images.githubusercontent.com/5654161/32225056-77dc6994-be4c-11e7-9d61-d1589055af83.png">

#### Context / Source

#manual-testing

**Comment by bluefuton** [comment]
Thanks for the report @brbrr!

**Comment by brezocordero** [comment]
There is another case reported here:  824179-zd

**Steps to reproduce**

1. On WordPress.com, create a site, change its name (WordPress.com domain)
2. With a different user:
3. Go to https://wordpress.com/following/manage
4. follow the new site name.
5. Search for the deleted name.

**What I expected**

Site is not found

**What happened instead**

5. You can follow the old site name
6. There are two messages, one saying you are following the site, another saying there was an error.
7. After following the deleted site, number of followers displayed on the reader for the new site name seems to double.

There are screenshots on the ticket.

**Comment by rantoncuadrado** [comment]
User asked about any news on this on this 824179-zen ticket

**Comment by liviopv** [comment]
Another on 937530-zen

I was also able to reproduce it on my account. It shows I follow 67 blogs, while I have less than 60 active.

The site I created to test this issue (https://thissitewillbedeleted647378409.wordpress.com) and that is now deleted also shows up in the "Blogs I Follow" widget https://cldup.com/Ss4XZiJS6t.png

**Comment by bluefuton** [comment]
Thanks folks. It's on our radar. I'll bump up the priority and hopefully get to it in our early-March bug squashing week.

**Comment by rantoncuadrado** [comment]
824179-zen gave us a sad feedback by saying 'I'm unsatisfied, you didn't give me a solution in 3 months so I created another blog'

**Comment by hacchism** [comment]
Another on 964518-zen

I was also able to reproduce it on my account.

**Comment by bluefuton** [comment]
One complication is that we don't necessarily want to automatically unfollow all subscribers when a blog is deleted - the user might just be moving to a different platform.

For example, they might have a custom domain hosted on wordpress.com and then move to a self-hosted site elsewhere and delete their old wordpress.com site after the move. Ideally, we want them to keep their subscribers in this scenario.

**Comment by bluefuton** [comment]
I've just shipped r170458-wpcom which should mean that deleted sites should no longer appear in search results or recommendations.

Two things we still need to look into:
- subscription count should ideally not include deleted sites
- Blogs I Follow widget should not include deleted sites

**Comment by bluefuton** [comment]
Now the "ghost" sites are gone, I'll close this issue. 👻

We're tracking the remaining problems related to subscriptions and deleted sites in https://github.com/Automattic/wp-calypso/issues/5840.
