### ISSUE TITLE
Store, Promotions - "Start a promotion!" button on the empty state doesn't work.

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#19329]
Logging this just to be sure we don't miss it before launch :)

#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/promotions/:sitename
2. Have no promotions
3. Click "Start a promotion!" button
4. Notice that nothing happens

#### What I expected
To be directed to the promotion creation screen.

I think we should also adjust the button label to just say "Add promotion".

**Comment by coderkevin** [comment]
This has been fixed before the original release enabled production.
