### ISSUE TITLE
Store Promotions - Promotion type dropdown labels

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#19331]
We spoke about this before but I couldn't find an issue. 

Let's refine the options a bit. Currently they are;

* Individual Product Sale
* Product Discount
* Cart Discount
* Percent Cart Discount

It's not obvious what the difference between an "Individual Product Sale" and a "Product Discount" is. 

Suggestion, but totally open to discussion;

* Product Discount Coupon [default]
* Cart Discount Coupon
* Percent Cart Discount Coupon
* Specific Product Sale

**Comment by kellychoffman** [comment]
This is fixed.
