### ISSUE TITLE
Store Promotions - Individual product sale flow

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#19330]
The current input order feels a little dis-ingenuous; we ask folks to input the sale price before choosing the product;

<img src="https://cldup.com/FKl3lEf3So.png" width="300" />

I think this should be reversed. Specify the product first, _then_ the discount.

I also think we should display the produce price in the list. Just so you can be sure you're setting the sale price correctly.

Thoughts @kellychoffman @coderkevin ?

**Comment by kellychoffman** [comment]
Agree! Good call.

**Comment by ryelle** [comment]
Closing this issue, looks like #19382 fixed it.
