### ISSUE TITLE
Guided Tour: selectors not working properly

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#19340]
While
```js
document.querySelectorAll( '.has-expanded-summary .activity-log-item:not(.is-discarded) .foldable-card__secondary' )
```
can correctly find the right node, the tour can't find it, and instead puts the Step at the top of the page.

<img width="604" alt="captura de pantalla 2017-10-31 a la s 12 53 52" src="https://user-images.githubusercontent.com/1041600/32234038-9316ce1e-be3a-11e7-9df4-e27773777c57.png">

**Comment by lsinger** [comment]
Can you provide the tour and step to reproduce this?

**Comment by eliorivero** [comment]
I'm going to close this one. After some digging, it was because of an element hidden with display: none in a foldable card.
