### ISSUE TITLE
Activity Log: line at end of timeline

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#19342]
Will be fixed by https://github.com/Automattic/wp-calypso/pull/19411

<img width="596" alt="captura de pantalla 2017-10-31 a la s 13 15 00" src="https://user-images.githubusercontent.com/1041600/32235306-db9267b8-be3d-11e7-9398-e0c1785b1372.png">

**Comment by MichaelArestad** [comment]
This one is fixed, though! https://github.com/Automattic/wp-calypso/pull/19411
