### ISSUE TITLE
DevDocs: Notices, PaymentLogoExamples, Rating components missing display names

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#19343]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design
2. Search for the components `Notices`, `PaymentLogoExamples`, and `Rating`.

#### What I expected

I expected those UI components to appear.

#### What happened instead

The components do not appear in the DevDocs under the correct display names. Instead, they appear with the display name "t" here:

https://wpcalypso.wordpress.com/devdocs/design/t

The components need a `displayName` set in their DevDocs example so the name appears correctly in the DevDocs.

#### Context / Source
#automated-testing #visdiffs

**Comment by rachelmcr** [comment]
The new Checklist component is also missing a display name and appears along with these components in the DevDocs. cc @taggon

**Comment by taggon** [comment]
This bug is resolved in bd659316a581841bc9381a872f93fc90ffcd8068
