### ISSUE TITLE
DevDocs: ReaderFullPostHeader missing styles

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#19344]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/reader-full-post-header
2. Compare the block's style to an actual full post header in the Reader

#### What I expected

The block style as seen in the Reader and previously in the DevDocs (per our visdiff tests):

![screen shot 2017-10-31 at 4 26 05 pm](https://user-images.githubusercontent.com/8658164/32235785-4cd8d410-be58-11e7-801a-ac3fab5af818.png)

#### What happened instead

The block is missing its style in the DevDocs:

![screen shot 2017-10-31 at 4 26 17 pm](https://user-images.githubusercontent.com/8658164/32235791-54e177a2-be58-11e7-9a9e-1aa85a0cd9d0.png)

#### Context / Source
#automated-testing #visdiffs

**Comment by bluefuton** [comment]
This is an interesting side-effect of CSS splitting, namely:

https://github.com/Automattic/wp-calypso/pull/19147

@stephanethomas is it possible to load all stylesheets for Devdocs?

**Comment by stephanethomas** [comment]
Haha, I didn't envision that particular use case.

Yes, I think we could just declare [a section](https://github.com/Automattic/wp-calypso/blob/62a01050f71973230bb6102e5fbeb4f65f4f9b3c/client/wordpress-com.js) for Devdocs, and create [a bundle](https://github.com/Automattic/wp-calypso/tree/06c0bb68bb961bae8b6ca5c2025521e53ce56c45/assets/stylesheets/sections) that imports all the other CSS bundles. Tangentially related, @jeremeylduvall is working on https://github.com/Automattic/wp-calypso/pull/18921 which will eventually offer the ability to [specify multiple CSS bundles for a given section](https://github.com/Automattic/wp-calypso/pull/18921#discussion_r145987929).

**Comment by bluefuton** [comment]
> I think we could just declare a section for Devdocs, and create a bundle that imports all the other CSS bundles

Sounds like the best option for the moment - thanks @stephanethomas!

> @jeremeylduvall is working on #18921 which will eventually offer the ability to specify multiple CSS bundles for a given section.

As a bonus, it would be so nice if we could specify 'all' to load all known CSS bundles (so we don't have to maintain the list for Devdocs).
