### ISSUE TITLE
Me: Changing the Interface Language requires a refresh

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#19349]
### Steps to reproduce

1. Starting at https://wordpress.com/me/account
2. Under `Interface Language` select a new language and click the "Select Language" button.
3. Click the "Save Account Settings" button to save your changes.

### Expected behavior

I expect the interface language to immediately switch to the newly selected language.

### Actual behavior

The interface remains in the previous interface language, although the newly selected language appears under Interface Language in the settings. The new language only appears after refreshing the page.

I originally observed this bug in the WP Desktop app, where you have to quit the app and restart it to see the new interface language. (The screenshots below are also from the app, but the same issue occurs in a browser.)

#### Browser / OS version

Tested on Mac OSX 10.12.6, Chrome 61 and WP Desktop app version 3.0.0-beta2

### Screenshots

Before switching language (selected language is English):

![screen shot 2017-10-31 at 5 12 07 pm](https://user-images.githubusercontent.com/8658164/32238119-d7500e50-be5e-11e7-892a-02a0c0468aa9.png)

After switching language (selected language is Spanish):

![screen shot 2017-10-31 at 5 12 15 pm](https://user-images.githubusercontent.com/8658164/32238122-d8bd9aaa-be5e-11e7-8c8c-675c19207441.png)

#### Context / Source
#manual-testing

**Comment by alisterscott** [comment]
I think this is a regression as I remember it used to do an auto-refresh after saving this.

**Comment by rachelmcr** [comment]
I am no longer seeing this issue (on Mac OSX 10.12.6, Chrome 62). When I switch language and save the account settings, the page now refreshes and the UI appears in the newly selected language. Closing as resolved.
