### ISSUE TITLE
Comments: when comment moderation is on, comment vanishes after posting

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#19359]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/40474296
2. Make a new comment on a post
3. Rather than staying visible with the text "this comment is awaiting moderation", the comment vanishes altogether.

**Comment by jancavan** [comment]
When I refresh the page (on both Convos and fullpost), the comment I just left also disappears. It should still be displayed until the site owner has moderated it.

**Comment by bluefuton** [comment]
> When I refresh the page (on both Convos and fullpost), the comment I just left also disappears. It should still be displayed until the site owner has moderated it.

That would be a great enhancement, but we might have to tackle it separately. The comment endpoints don't currently send us comments pending moderation by the user, so when you refresh, the comment vanishes until approved.

**Comment by bluefuton** [comment]
This is tricky.

In Reader, we want to get comments that are approved only, _except_ if the current user has posted a comment and that hasn’t been moderated yet.

If we try fetching all types of comment rather than just ‘approved’ ones, it fires off an API request asking for unapproved comments, which returns a 403 for a regular user.
