### ISSUE TITLE
Editor: Publish confirmation should dismiss when exiting the post-publish preview

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#19354]
#### Steps to reproduce
1. Publish a new post.
2. You'll see the preview with a green success notice.
3. Click the edit button in the preview's toolbar, near the top right.

#### What I expected
For the success notice to dismiss.

#### What happened instead
The success notice stuck around, and got in the way.

#### Screenshot / Video
![artboard](https://user-images.githubusercontent.com/191598/32241547-d6199780-be46-11e7-815d-3f0670f733d3.png)

**Comment by mattsherman** [comment]
@Automattic/tanooki will look into this.
