### ISSUE TITLE
Store promotions - Combine cart discount types (flat rate & percentage)

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#19360]
Our current promotion types are;

- Specific Product Sale
- Product Discount Coupon
- Cart Discount Coupon
- Percent Cart Discount Coupon

I think we could combine the last two. Conceptually they're the same thing - a cart discount. Then allow folks to choose a flat amount or a percentage in the "Coupon Code & Discount" card.

**Comment by kellychoffman** [comment]
@coderkevin: here is the design for combining the two:

<img width="667" alt="screen shot 2017-11-17 at 7 14 04 am" src="https://user-images.githubusercontent.com/5835847/32951381-ed9ae85a-cb66-11e7-90fc-f3159ca7584e.png">

This means the new promotion types would be:

Specific Product Sale
Product Discount Coupon
Cart Discount Coupon

**Comment by kellychoffman** [comment]
@coderkevin: Could we get this in in the next few weeks? It would close out the last big issue for promotions v1.

**Comment by coderkevin** [comment]
Hmm, I didn't have this on my list for promotions before I moved on to other tasks. If this is the desired updated design, I can get to work on it after my current tasks.

**Comment by kellychoffman** [comment]
Thanks! Sorry for the miscommunication.
