### ISSUE TITLE
What packages are included in application desktop?

### ISSUE THREAD

**Issue by dikiaap** [Automattic/wp-calypso#1937]
I use linux and size app is 53mb. What's there?
if there is some sort of node or npm package,I don't want to replace it.
https://desktop.wordpress.com/linux/

**Comment by mkaz** [comment]
The desktop app is a bundling of our application code, Node JS and the Chromium browser, the overall tool we use to bundle together is called Electron. The Node and Chrome binaries are the largest part of the download but we also include numerous node modules for running our app and Electron.

You can see a listing of the Node packages that are bundled in the desktop repository at: https://github.com/automattic/wp-desktop

More information about Electron available at: http://electron.atom.io/
