### ISSUE TITLE
Extra <title> Tag in Footer on Sites Using Logo Credit

### ISSUE THREAD

**Issue by brucea8c** [Automattic/wp-calypso#19373]
#### Steps to reproduce
1. Starting at URL: https://janicednelson.com/ or any site using the logo footer. (It appears only to be the logo footer, and is theme agnostic.)
2. View Site via MOZ, and you will see the Footer credit text added to the end of the Site Title text:
![janice-nelson-site-moz](https://user-images.githubusercontent.com/15346031/32253476-7f74891e-be71-11e7-8268-11413fe69295.png)
3. In examining the source code, there is an extra <title> tag in the footer:
![title-tag](https://user-images.githubusercontent.com/15346031/32253968-51886ea0-be74-11e7-849f-1741b2673de3.png)

#### What I expected
The Moz site title description should only show the site title.

#### What happened instead
The Site title showed the site title AND the text of the footer credit. 

#### Context / Source
Submitted by #user-report in` 892360-hc`

-->

**Comment by rachelmcr** [comment]
Since this isn't a Calypso issue, I've moved the report (wpcom-7953) to continue tracking it.
