### ISSUE TITLE
Purchases: Standardize naming for privacy protection

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#1938]
We should really standardize on how we name and present this feature to users. Right now this is really confusing since we either call it [_Private Registration_](https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=%22private+registration%22&type=Code) or [_Privacy Protection_](https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=%22privacy+protection%22). One or two year ago we decided to use `Privacy Protection` but somehow forgot to enforce it.

Note we shouldn't only update user facing messages but also **our code** as well.

Pinging @breezyskies and @mikeshelton1503 for confirmation.

**Comment by breezyskies** [comment]
I would standardize to `Privacy Protection` as it sounds like a product (that you would pay for) vs. a setting. 

Do you have a list of the user-facing places where we are using `Private Registration` instead?

**Comment by stephanethomas** [comment]
I don't have any list, I just did a [very basic grep](https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=%22private+registration%22&type=Code).

**Comment by breezyskies** [comment]
Okay, all of the user-facing ones there should be fine to be updated to `Privacy Protection`.

**Comment by fabianapsimoes** [comment]
Probably related to #2139.

**Comment by umurkontaci** [comment]
Remaining references:
![image](https://cloud.githubusercontent.com/assets/991022/12633080/dca3300a-c511-11e5-9543-9d5c2c8dd7bf.png)

**Comment by fabianapsimoes** [comment]
@klimeryk @umurkontaci did anything related to this issue come out of #2258?

**Comment by umurkontaci** [comment]
@fabianapsimoes https://github.com/Automattic/wp-calypso/issues/1938#issuecomment-175923216 should be the most recent state of the references. I've changed the ones I've come across during #2258, but I didn't actively look for other references anywhere else.

**Comment by fabianapsimoes** [comment]
@spncrb do you think you could check the status of this? Seems @umurkontaci did some work on this as part of #2258. It'd be good to a have a list of occurrences that still need updating (see also #2139).

**Comment by spncrb** [comment]
@fabianapsimoes I can dig further, but so far there are two instances we should fix asap in /purchases, both in the cancellation steps (Cancel Private Registration in both places)
