### ISSUE TITLE
Store: Email: Store owners can make their transactional emails look the way they want

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#19402]
To give our store owners more control over how their emails look, we will enable the `Email Customizer` WooCommerce extension for them.  See p75Izm-Fe-p2.

Since this is a paid extension, we won't be able to install it during our plugin setup flow. It looks like we can pull the extension in as a Git Submodule for `wpcomsh`. See `custom-colors` in that repo for an example. We should be able to load the extension from here if WooCommerce is present on the site. A few of us have some experience adding plugins to `wpcomsh`, so we can help provide guidance here.

Todo:

- [ ] Bundle the Email Customizer Extension in wpcomsh.  
- [ ] Test the various parts of the customizer extension to make sure they all work on the AT site.
- [ ] Fix https://github.com/woocommerce/woocommerce-email-customizer/issues/37 and https://github.com/woocommerce/woocommerce-email-customizer/issues/34.
- [ ] Per #15040, hide the email footer text from the emails and hide this panel from the customizer.
- [ ] If a user comes to the email customizer from Calypso, make sure we send them back to Calypso instead of  `wp-admin`.  (Like we did in #15378 for the normal customizer). 
- [ ] Add an entry point to the email customizer from Calypso.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
