### ISSUE TITLE
Themes: after switch, can't click on View Site any more

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#19401]
I think this is a regression related to https://github.com/Automattic/wp-calypso/pull/18916

#### Source

Found this via a WP.com internal stat drop email alert for "Trampoline" clicks on the "Customize" button after you click "View Site" here. They dropped from 5,000 a day to 100 a day around the same time as the above change.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/example.wordpress.com
2. Click on a theme
3. Click the ... menu to see actions, and choose "Activate"
4. In the resulting popover modal, try to click "View Site"

#### What I expected
I expected to view my site with the new theme, as well as the "Trampoline" guide with buttons to Edit or Customize.

#### What happened instead
Nothing happens when I click "View Site". No JS errors in console.

#### Browser / OS version
Tested in Safari and Chrome on macOS.

#### Screenshot / Video
![theme-switch](https://user-images.githubusercontent.com/66797/32291289-d41d99be-bef9-11e7-8331-0dd005de7bc0.gif)

CC @markryall @fditrapani 

Internal Slack ref: p1509557913000052-slack-C02ES4PHV

**Comment by markryall** [comment]
`git bisect` suggests that commit https://github.com/Automattic/wp-calypso/commit/4deab69594b0b93e9f2f65c723024f7bd3d3a9de introduced this issue (merged as part of #18557.

The result seems to be that calling `path` with an absolute url no longer does anything.  In most places, we don't do this (we use `<a />` tags with an href instead) but this button uses `path`.

Are you able to take a look at this @Tug?

**Comment by alisterscott** [comment]
We didn't have any e2e test coverage on activating a theme and then viewing the site, so I've written a PR for this that can be merged as soon as this bug is fixed.

See: https://github.com/Automattic/wp-e2e-tests/pull/769
