### ISSUE TITLE
Store: Shipping Labels: Labels Card disappears as Settings > Shipping loads

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#19403]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/settings/shipping/{DOMAIN}
2. Do a hard refresh
3. Note that the labels card disappears as the shipping settings page finishes initialization
4. Also note that the shipping label purchasing flow is working on individual orders

#### Screenshot / Video

![labels-section-disappears](https://user-images.githubusercontent.com/1595739/32291668-f8059bb4-befa-11e7-9fcb-8f4312ec5ebe.gif)

#### Context

localhost, today's master

**Comment by justinshreve** [comment]
Slack discussion: p1509560288000031-slack-store-on-wpcom.

If you want to look at a site where it works vs where it doesn't, let me know and I can make you an admin.

* `justin-devstore-at.blog` the card shows up
* `justin-devstore-at-1.blog` the card does not show up

**Comment by dechov** [comment]
Is it plausible that the `can_manage_payments` flag (originating from [woocommerce-services/classes/class-wc-rest-connect-account-settings-controller.php](https://github.com/Automattic/woocommerce-services/blob/900fe92dcb1b4a6e7a42cbd39122c3cf75d301f8/classes/class-wc-rest-connect-account-settings-controller.php#L70-L75)) might explain the anomalies?

I noticed in https://github.com/Automattic/wp-calypso/pull/17337#issuecomment-324468509 the labels settings card placeholder appearing when we don't actually want to show the settings — if we should in fact be showing the card in the above cases then the placeholder may be a secondary issue (but still worth solving IMO).

**Comment by justinshreve** [comment]
@danreylop ^
