### ISSUE TITLE
ccTLDs: allow going back from extra details screen

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#19416]
> Registering a .ca not being eligible for a .ca domain, I end up on a dialog where I can eventually lie and claim to be Her Majesty the Queen, but no link to go back, except deleting the domain from my cart.

We should add the ability to go back to the whois details from the extra cctld screen

**Comment by klimeryk** [comment]
FWIW, the checkout flow has always been a one-way street, so I'd say this actually applies to the whole flow, not only the ccTLD case.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by klimeryk** [comment]
Closing - this has been fixed by the checkout redesign 🎉
