### ISSUE TITLE
Editor: Confusing "Publish immediately" button

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#19415]
I wanted to publish a post, but the "Publish Immediately" button confused me:

![screenshot 2017-11-01 22 16 24](https://user-images.githubusercontent.com/4924246/32310844-76f39a00-bf52-11e7-9f34-3dd4a2613c0b.png)

It says "Publish immediately", but it's asking me to pick a date.

But when I pick today's date, it's showing me posts titles? I'm not sure what they were for?

![screenshot 2017-11-01 22 16 29](https://user-images.githubusercontent.com/4924246/32310861-9708efe8-bf52-11e7-9183-2772144c3f14.png)

I eventually saw the green "Publish!" button, but I think it's easy to miss.

**Comment by lancewillett** [comment]
Closing as a duplicate of #22816
