### ISSUE TITLE
Themes: Allow previewing on Jetpack sites without having to activate the theme

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#19429]
#### Steps to reproduce
1. Choose a theme for your Jetpack-connected site.
2. Note that the only option available is `Activate this design`
3. It would be nice if there was a way to preview the design on your site first without having to activate it.

#### Screenshot / Video
<img width="320" alt="screen shot 2017-11-02 at 10 24 23" src="https://user-images.githubusercontent.com/831377/32332903-f6498f84-bfbc-11e7-8853-22f95085866e.png">

**Comment by lamdayap** [comment]
Note: the try and customize button is available when not viewing the theme on it's own.

https://cdn-pro.dprcdn.net/files/acc_495411/zbXpLp
