### ISSUE TITLE
Store: Use specific currency indicator in payment method descriptions

### ISSUE THREAD

**Issue by dechov** [Automattic/wp-calypso#19435]
"2.9% + 30c per transaction" in the Stripe and PayPal fee descriptions use a somewhat vague and/or non-standard way of indicating cents.

<img width="737" src="https://user-images.githubusercontent.com/1867547/32335762-fee5145e-bfc3-11e7-8bf3-9eab0ff8af33.png">

"2.9% + 30c" should either read:
- "2.9% + 30¢" (as on https://stripe.com/us/pricing), or
- "2.9% + $0.30" (as on https://www.paypal.com/us/webapps/mpp/express-checkout)

Tested on a US store only.

Note also that https://stripe.com/ca/pricing says "2.9% + C$0.30" — though I'm not sure how the above extends to other countries / currencies (i.e. specifically Canada at the moment), or whether the fee description should be dependent on the Store Currency which it currently doesn't appear to be. (cc @allendav) (see also https://www.paypal.com/us/webapps/mpp/merchant-fees#standard-transaction-fees)

**Comment by kellychoffman** [comment]
Agree we should change this. Interesting they both present it in different ways. I'm okay with either, I would guess it depends on what is easiest for other currencies.

**Comment by justinshreve** [comment]
This is no longer valid now that we display this:

<img width="314" alt="screen shot 2018-03-07 at 2 21 07 pm" src="https://user-images.githubusercontent.com/689165/37121676-cea2cdfc-2212-11e8-837d-92af20be18a7.png">
