### ISSUE TITLE
Reader: Post Notifications API

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#19444]
We'll need the following to drive the Post Notifications setting:
- [x] Expose the setting in `delivery_methods` in `v1.2/read/following/mine`. Maybe also in `v1.2/read/sites/:site`? How do we load it for sites we follow today?
- [x] Add new API to subscribe to notifications
- [x] Add new API endpoint to unsubscribe from notifications

**Comment by bluefuton** [comment]
Added two new v2 endpoints for subscribe and subscribe in D8994-code.

```
POST /read/sites/:blog_id/notification-subscriptions/new
POST /read/sites/:blog_id/notification-subscriptions/delete
```

**Comment by bluefuton** [comment]
D9127-code has landed, so responses now include `delivery_methods->notification`. 🚢
