### ISSUE TITLE
Reader: Add Post Notifications to Settings popover

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#19440]
![post-notifications-001](https://user-images.githubusercontent.com/4924246/32339346-cc84cc5c-bfb4-11e7-8a8f-9e2a8f839f89.png)

## Notes:

- If you have this feature turned on for a site you’re following, you will be getting notifications on your wpcom sidebar when that site posts something new.
- This setting will by off by default.
- This will be added to any page in Reader that has the Settings popover show up after clicking the Follow button. For now, that’s currently in Fullpost, Site results in Search, and Manage.
- In the Site Stream, after hitting the Follow button, a green global notice (that confirms your following) floats on top of it. I think the current change in the button’s state is enough to communicate that you are already following a site. We should either remove this notice or make an exception for the Site Stream.
- There aren’t any significant changes to the layout mobile-wise, except that an additional item will be appended to the popover.
- The Settings and Follow icon should be aligned vertically. Currently, they are both flushed to the right.

**Comment by blowery** [comment]
> The Settings and Follow icon should be aligned vertically. Currently, they are both flushed to the right.

Making that work across translations (and in RTL) may be thorny.
