### ISSUE TITLE
Store: Products: Set Image: Not as clickable as hand cursor suggests

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#19443]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/product/{DOMAIN}/{SOMEPRODUCTID}
2. Note that although you have a hand cursor in the entirety of the Add images box, it only actually opens the file selector if you click on the Add Images icon inside that box

#### Screenshot / Video

![image-click](https://user-images.githubusercontent.com/1595739/32339976-8e865f40-bfb6-11e7-9367-9b5fec1bba4d.gif)

#### Context / Source
* Today's master

**Comment by coderkevin** [comment]
I just ran into this today, too.
