### ISSUE TITLE
Comments: display comment counts in navigation

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#19478]
Depends on #19477

Once the `comments-count` endpoint is implemented, we should update our Calypso components in order to display these counts properly. Some work around this was already laid out in #19442.

Notes from @drw158: 

> I'd like to see some sort of abbreviation for popular blogs.
en.blog has 127,397 All comments, and around the same for Approved
maybe something like 127k and 3.4k, similar to Twitter's likes and retweets.

**Comment by gwwar** [comment]
closed by #21899
