### ISSUE TITLE
JP Live Chat: Remove chat for SSO connection flows

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#19492]
There is a lot of confusion involved when someone ends up chatting with us through an SSO process. Does it make sense to remove the chat offering on the SSO connection pages?

A situation occurred today where a WP+JP site had SSO on, but had a separate membership area. The user hit the WP login, meaning to hit the separate membership area (not on WP). They hit the WP.com SSO button, then was lost by the prompt to connect their account to Jetpack and chatted with us, thinking we were the original site's tech support.

cc: @annezazu

**Comment by annezazu** [comment]
Oooh that's an interesting use case. I agree - we should either 1) clarify "Chat with Jetpack support" or 2) remove it.

**Comment by tyxla** [comment]
Makes sense to me. I'm more inclined to go with 1), because users might need our help in case they're stuck there. And if we get too many unrelated chats there, we might reconsider that and remove that button completely from the SSO step.

**Comment by tyxla** [comment]
#19515 rephrases the button text for the SSO flow.

**Comment by annezazu** [comment]
Let's try that first :)

**Comment by tyxla** [comment]
#19515 has been merged. Please, nudge me if you have any other ideas for improvement 😉

**Comment by kraftbj** [comment]
We'll see how it plays out. Personally, I'm inclined still to remove it since, in theory, the admin user of the site would have a valid connection, so going through the connection flow would be something that only happens for non-admins and offering support to non-connected users of a connected site seems to me to be ripe for issues. But yeah, if that is only 1 in a blue moon, fine enough.

**Comment by annezazu** [comment]
I would agree with you @kraftbj  - let's revisit. Adding a reminder for a month from now.

**Comment by tyxla** [comment]
Sounds good to me. I'm happy to remove it for the common good 😉  Please keep me in the loop.
