### ISSUE TITLE
Editor: Confusing UX when using the [recipe] shortcode

### ISSUE THREAD

**Issue by noisysocks** [Automattic/wp-calypso#19500]
#### Steps to reproduce

1. Create or edit a new post
2. In Visual mode, type in: `[recipe title="Vegetable Chili" image=""][/recipe]`
3. Place your cursor in between the `image` attribute's `"`s
4. Paste in a URL to an image that ends with `.jpg`, e.g. `http://via.placeholder.com/500x500.jpg`

#### What I expected

The text of the post to become: `[recipe title="Vegetable Chili" image="http://via.placeholder.com/500x500.jpg"][/recipe]`

#### What happened instead

The image at `http://via.placeholder.com/500x500.jpg` itself is inserted into the post, which breaks the shortcode.

#### Browser / OS version

Confirmed on Safari 11.0.1.

#### Screenshot / Video

![shortcode bug](https://user-images.githubusercontent.com/612155/32420550-fdc7e6b8-c2df-11e7-84f9-cb8d127d0006.gif)

#### Context / Source

Discovered via a user support ticket. The workaround is to edit the shortcode with the editor in HTML mode. Still, this is a confusing UX.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
