### ISSUE TITLE
Wrong German Translation

### ISSUE THREAD

**Issue by christophwolff** [Automattic/wp-calypso#1952]
The Blogsection Navbar says: "In Papierkorb". Thats wrong german spelling. It must be: "Im Papierkorb"
![bildschirmfoto 2015-12-24 um 13 15 12](https://cloud.githubusercontent.com/assets/2046613/11994525/63af5d54-aa40-11e5-9178-19db45e5a7a5.png)

**Comment by lancewillett** [comment]
Thanks for this report, we'll fix the translations on the WordPress.com side and it'll be reflected in Calypso soon.

**Comment by lancewillett** [comment]
I opened #1959 after testing this translation change.
