### ISSUE TITLE
Store: Copy the "settings" part of woocommerce-services into Calypso

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#19521]
Make it compile and make sure all the required styles & components are included, but don't go further than that in order to not create a monstruously big PR.

**Comment by jeffstieler** [comment]
Is this the `SettingsForm` component (and its dependencies)?

**Comment by DanReyLop** [comment]
I was thinking about the whole `client/apps/settings` tree, which includes the `SettingsForm` component and reducers/actions. As with the other parts that were ported to Calypso, getting *everything* into `wp-calypso` and then tweaking it to make it work seems like the best approach.
