### ISSUE TITLE
Store: Add tools to troubleshoot USPS/Canada shipping rates issues

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#19528]
In WP-Admin, WCS shows an admin notice if the latest request for USPS/Canada shipping rates failed for any reason. That notice directs the user to the self-help page (`/wp-admin/admin.php?page=wc-status&tab=connect`). In that page he can see what the error was, enable the debug log, see the latest log messages, etc.

Should we implement the error notice in Calypso, and keep the `self-help` page in WP-Admin? Or implement both parts in Calypso? Or is it not worth it for the initial release?

cc/ @kellychoffman

**Comment by kellychoffman** [comment]
I don't think we should recreate the self help page as is. It was built with a technical audience in mind and won't be helpful for most Store users.

**Comment by DanReyLop** [comment]
Nice, closing this then :)
