### ISSUE TITLE
Store: Add the WooCommerce Services shipping methods to the dropdown

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#19522]
Also, since we're hiding the "WooCommerce Services" brand, make sure they're called "USPS" and "Canada Post" instead of "USPS (WooCommerce Services)" and "Canada Post (WooCommerce Services)".

**Comment by jeffstieler** [comment]
Is there a solution that can work for Jetpack/WCS stores as well?

**Comment by DanReyLop** [comment]
In WP-Admin we want to call them `USPS (WooCommerce Services)` and `Canada Post (WooCommerce Services)` to differentiate them from the USPS and CP extensions. In Calypso we don't have that problem. If you want to revisit that decision on WP-Admin it would certainly make this task easier, but it's no big deal either way.

**Comment by jeffstieler** [comment]
> In Calypso we don't have that problem.

What about Calypso prevents this problem for Jetpack stores? Can they non install other shipping extensions?

**Comment by DanReyLop** [comment]
Yes, but they would need to manage those extensions from `WP-Admin`. We only support the "core" WooCommerce functionality in Calypso (and by "core" I'm including `WooCommerce Services`), so other shipping methods won't appear in the Calypso UI at all.
