### ISSUE TITLE
Store: WCS-powered USPS and Canada Post shipping methods

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#19529]
Umbrella issue for all the work related to porting the USPS and Canada Post shipping methods for live rates into Calypso.

Also part of this epic, these issues from `woocommerce-services`:
- https://github.com/Automattic/woocommerce-services/issues/1212
- https://github.com/Automattic/woocommerce-services/issues/1213 (Optional)
- https://github.com/Automattic/woocommerce-services/issues/1214 (Optional)
- https://github.com/Automattic/woocommerce-services/issues/1215 (Optional)
- https://github.com/Automattic/woocommerce-services/issues/938

cc/ @jeffstieler @justinshreve @marcinbot Please tell me if you think I've overlooked something.

**Comment by dechov** [comment]
Can this be closed as complete?

**Comment by DanReyLop** [comment]
Yes, closing.
