### ISSUE TITLE
Pages: replace custom notices with standard components

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#19538]
The Posts and Pages views use custom notices for trashing content.

![nov-06-2017 15-17-49](https://user-images.githubusercontent.com/618551/32464457-b60ccf5c-c305-11e7-9c01-1827daf40bcd.gif)

I think we can easily do one of two things:

1. Remove content immediately, and show a **global** notice for 4 separate states: trashing, trashed, restoring, and restored.
2. Remove content immediately and show an **inline** notice in its place for the same 4 states.

The only disadvantage is that you won't be able to see the faded content underneath anymore.

**Comment by alisterscott** [comment]
It looks like /posts now uses standard notices:

<img width="1123" alt="screen shot 2017-12-21 at 11 15 10 am" src="https://user-images.githubusercontent.com/128826/34235913-8edae442-e640-11e7-80c4-017662d52466.png">

but /pages doesn't :(

<img width="1125" alt="screen shot 2017-12-21 at 11 14 58 am" src="https://user-images.githubusercontent.com/128826/34235880-4b44db0c-e640-11e7-9195-3242f26f7a75.png">

**Comment by mattsherman** [comment]
Noting that `/pages` now uses a different style custom notice...

<img width="704" alt="screencapture at mon aug 20 08 29 23 edt 2018" src="https://user-images.githubusercontent.com/2098816/44340574-41eb9880-a453-11e8-92f7-7d21ab06f5f4.png">

Ideally, both `/posts` and `/pages` would use the same UX for notifications.
