### ISSUE TITLE
Activity Log/Rewind: Download is ready email

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#19540]
When a user wants to download a backup of their site, they need to initiate a flow that builds a zip file of their backup. It can take some time and they don’t have to sit around while we build it. We should send them both an email and a [notification](https://github.com/Automattic/wp-calypso/issues/19541) letting them know their backup is ready for download.

**Subject line:** Your backup of [site name] is ready for download

![download is ready](https://user-images.githubusercontent.com/1123119/32468704-9aa58810-c30c-11e7-910e-da77ad205b58.jpg)

Plaintext for the lovely folks implementing this:

> Download your site backup

> You recently requested a downloadable backup of your site michael.blog. Jetpack has finished preparing your files and they’re ready for download now.

> Download your backup

**Comment by roccotripaldi** [comment]
in progress at D8389-phab

**Comment by eliorivero** [comment]
Closing since this is implemented.
