### ISSUE TITLE
Activity Log/Rewind: Download is ready notification

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#19541]
When a user wants to download a backup of their site, they need to initiate a flow that builds a zip file of their backup. It can take some time and they don’t have to sit around while we build it. We should send them both an [email](https://github.com/Automattic/wp-calypso/issues/19540) and a notification letting them know their backup is ready for download.

![download is ready](https://user-images.githubusercontent.com/1123119/32862362-1f9b53a6-ca15-11e7-9d19-cea47c6ce3e0.jpg)

Plaintext for the lovely folks implementing this:

> Your backup is ready for download

> Jetpack has finished backing up The Great Mandala and your files are ready to download.

----

> Jetpack has finished preparing a downloadable backup of your site, The Great Mandala. Head over to the site's Activity log to download it.

**Comment by samhotchkiss** [comment]
Donezo!
