### ISSUE TITLE
Links: Add Links management to Calypso or retire Links widget

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#19556]
Currently, WordPress.com has a [Links widget](https://en.support.wordpress.com/widgets/links-widget/) that auto-populates with Links (Blogrolls) added from the [Links section](https://en.support.wordpress.com/blogroll/add-a-blogroll-link/) of WP Admin under `/wp-admin/link-manager.php`.

We should either port link management (the WP Admin Links section functionality) to Calypso or retire the Links widget.

#### Screenshot / Video

Links section of WP Admin:

![screen shot 2017-11-07 at 12 26 08 pm](https://user-images.githubusercontent.com/8658164/32493768-fb70e11c-c3b6-11e7-9896-ed7066970e00.png)
![screen shot 2017-11-07 at 12 26 51 pm](https://user-images.githubusercontent.com/8658164/32493770-fc685104-c3b6-11e7-8b57-af1366345419.png)
![screen shot 2017-11-07 at 12 27 00 pm](https://user-images.githubusercontent.com/8658164/32493773-fd93680c-c3b6-11e7-8174-7fe3d229f559.png)

Links widget:

![screen shot 2017-11-07 at 12 27 57 pm](https://user-images.githubusercontent.com/8658164/32493824-301e412a-c3b7-11e7-85e6-45dad721e421.png)

#### Context / Source
7955-wpcom

**Comment by lancewillett** [comment]
If I'm not mistaken, the Links functionality was removed from Core WP years ago, right?

I think we should hide for any new user — as well as all WP.com users who've never created a link before. For everyone else, it'll only be editable via WP Admin.

**Comment by rachelmcr** [comment]
Ah, you're right, it's still a wpcom feature but no longer in Core WP. In that case, +1 to hiding Links (both in WP Admin and the widget) for new users and users who haven't used the feature before.

**Comment by lancewillett** [comment]
Another note: we could migrate all existing Links to be Custom Menus instead. That way people can put them anywhere a menu or widget can go.

This'll probably come up again with Gutenberg, where "links" could be a block. Whether that's from a plugin versus core, WordPress.com should retire the older feature for anyone that isn't using it now.
