### ISSUE TITLE
Domains: Confusing messaging when a domain is already registered elsewhere.

### ISSUE THREAD

**Issue by hafizrahman** [Automattic/wp-calypso#1956]
In https://wordpress.com/domains/add/, when you try to register an already registered domain, the notice says "Aww — [domain name] is not available. Is it yours? Map it for $13.00."

![screen shot 2015-12-28 at 8 16 08 pm](https://cloud.githubusercontent.com/assets/266376/12019292/e44888d8-ada0-11e5-9d3d-ce2375561549.png)

The concept of owning vs registering a domain name is usually not very obvious to users. When a user reads the "Is it yours?" question, the answer might not be obvious as well. A user might think, "What does it mean when a domain is mine?"

I suggest we change this question to something clearer: "Have you registered this domain name elsewhere?"

**Comment by designsimply** [comment]
Alternate ideas for the wording:

* example.com is not available. If you purchased example.com elsewhere, you can map it here for $13.00.
* example.com is not available to purchase. If you already own example.com, map it for $13.00.

**Comment by breezyskies** [comment]
Proposed design change:

<img width="743" alt="screen shot 2016-01-05 at 2 00 40 pm" src="https://cloud.githubusercontent.com/assets/3011211/12128929/3593678e-b3b5-11e5-9b00-b89c5c80551e.png">

In addition to the copy change, I also de-emphasized the option, given that it's much more likely that the domain is simply registered by someone else than that they actually own it. 

We also might want to experiment with different ways of displaying the "map it" option that appears at the bottom of the results.

cc: @mikeshelton1503 @danhauk for design / copy feedback.

**Comment by danhauk** [comment]
I like the idea of a statement over a question like @designsimply suggested above. In my own internal dialogue it's easier to answer whether or not I registered it somewhere else if it's presented as a statement. Being asked a question makes me second guess "did I?"

Design looks good. I like the de-emphasis on the action.

**Comment by breezyskies** [comment]
> In my own internal dialogue it's easier to answer whether or not I registered it somewhere else if it's presented as a statement. Being asked a question makes me second guess "did I?"

:+1: Let's go with the "If you purchased example.com elsewhere..." since I think the word "purchased" makes it super clear that they had to have taken this specific actions somewhere else. Will start a PR for this.

**Comment by breezyskies** [comment]
PR started in https://github.com/Automattic/wp-calypso/pull/2154

**Comment by breezyskies** [comment]
Copy updated in https://github.com/Automattic/wp-calypso/pull/2154.
