### ISSUE TITLE
Add tracking for happychats started from cancellation flow. 

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#19563]
I am seeing a precancellation stat but nothing specific for JP chat. Is this tracked? 

If so, please DM me with the link and close this :) 

If it's not tracked, this is a request to put tracking in place. 

Thank you!

**Comment by tyxla** [comment]
I'm closing this one, as I believe the necessary tracking is already available: 

1. When the user clicks the Happychat button in the Happychat step, the `calypso_purchases_cancel_form_chat_initiated` tracks event is recorded. It contains the cancellation flow slug and the product (plan) slug, which you can use to filter by Jetpack plans (`jetpack_premium`, `jetpack_premium_monthly`, etc.).

2. When the user clicks the Happychat button in the footer of the cancellation form, the `calypso_precancellation_chat_click` tracks event is recorded. It contains the product (plan) slug, which you can use to filter by Jetpack plans (`jetpack_premium`, `jetpack_premium_monthly`, etc.)

In case you wish to build more advanced funnels, you can use some of the following events:
* `calypso_purchases_cancel_form_start` - called when the cancellation flow is started, contains a `product_slug`
* `calypso_purchases_cancel_form_select_radio_option` - you could use it to track when the user selects a particular answer to a particular question, for example: `option: "radio_1", value: "couldNotActivate"`
* `calypso_purchases_cancel_survey_step` called when changing the step, contains a `product_slug` and the slug of the `next_step`.

Hope that's helpful. Don't hesitate to ping me if you need anything specific though.
