### ISSUE TITLE
Post Settings: Sticky Post option is missing

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#19575]
#### Steps to reproduce
1. Create or edit an existing post
2. Open up the Post Settings panel and look under the Status for the toggle to enable/disable it as Sticky.

#### What I expected
To see the option to make a post Sticky or not.

#### What happened instead
The option was not there. It's important to note that the setting is still available in WP-Admin.

**Comment by cecilerainon** [comment]
I'd like to add it's actually there, but not visible. Here's a screenshare I shared with a user reporting the issue: http://cld.wthms.co/Hrbp5m

**Comment by MindyPostoff** [comment]
@cecilerainon Good to know about the clickable icon. However, there should also be a toggle switch under the Status section:

![](http://cld.wthms.co/iPfSOA+)

**Comment by rwaynick** [comment]
Also reported in 253651-hc. I shared @cecilerainon's link with the user. It was even hard for me to find since I was expecting a hover effect.

The user mentioned:

> They need to have a faint outline or something if that's the way they're going to change it.

**Comment by ehti** [comment]
The toggle/option to make posts sticky is not visible at all! URGH.

And.. looks like happiness was not informed about this change? And no made change to our public support doc too that illustrates this feature: https://en.support.wordpress.com/post-visibility/#sticky-posts

**Comment by rachelmcr** [comment]
There is an open bug report for this issue here: https://github.com/Automattic/wp-calypso/issues/18217

Closing this as a duplicate.
