### ISSUE TITLE
Can't export future posts

### ISSUE THREAD

**Issue by keithlock75** [Automattic/wp-calypso#19579]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Click "Export"
3. Click the down arrow to: Select specific content to export
4. Select "Posts"
5. Choose Status: Scheduled
6. Click "Export Selected Content"

#### What I expected
To get an export of Scheduled posts.

#### What happened instead
Error message: "There was a problem preparing your export file. Please check your connection and try again, or contact support."

Log error: "Could not find a post_status matching future. Here is a list of available stati: draft, pending, private, publish"

#### Browser / OS version
Chrome - Latest / Windows 10

#### Context / Source
#user-report

**Comment by edwinho89** [comment]
Similar issue on 2531816-zen

**Comment by ahmadbaig1** [comment]
Reported in zen-2721936

**Comment by cathymcbride** [comment]
no repro - closing
