### ISSUE TITLE
Comments: update copy in the header

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19586]
In the post specific view let's update the post header to the following: `Comments on ${ postTitle }`. As an example in the image below this would change to `Comments on "Almond Butter Breakfast Muffins"`

![31955178-7c3155c8-b89c-11e7-949d-4ff860272cd0](https://user-images.githubusercontent.com/1270189/32521893-10791418-c3ca-11e7-8ff6-2e4647890f43.png)

**Comment by drw158** [comment]
A nice enchantment would be to use Merriweather for the post title. Related: #19605

**Comment by Copons** [comment]
Just to clarify, this is what we want:

- `Comments on ${ postTitle }` or `Comments on "${ postTitle }"`? (with or without quotes)

- `<span class="serif">Comments on ${ postTitle }</span>` or `Comments on <span class="serif">${ postTitle }</span>`? (all heading in serif or just the post title?)

(also, [it's Noto Serif, not Merriweather](https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/_typography.scss#L7) 🙂 )

**Comment by drw158** [comment]
No quotes, serif font only on the post title
