### ISSUE TITLE
Pages: inconsistent label in section nav for "Trashed"

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#1959]
There is a discrepancy in labeling the "In Trash" area for /posts and /pages.

/posts shows "Trashed" (adjective) in English and "Im Papierkorb" in German (for example).
<img width="1250" alt="screen shot 2015-12-28 at 09 52 45" src="https://cloud.githubusercontent.com/assets/66797/12022015/0e1514d6-ad49-11e5-8c6b-cab90b2af5a7.png">

/pages shows "Trash" (noun) in English and "Papierkorb" in German
<img width="1256" alt="screen shot 2015-12-28 at 09 52 54" src="https://cloud.githubusercontent.com/assets/66797/12022018/123567d2-ad49-11e5-93de-1dbed735ebc7.png">

They should both be the same label.

**Comment by jeremeylduvall** [comment]
Closed via #5914.
