### ISSUE TITLE
Stats: all-time table view missing from Calypso

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1960]
We have the table views for individual posts, but we're missing the all-time summary view as seen in /my-stats and /wp-admin stats:

![image](https://cloud.githubusercontent.com/assets/363749/5378341/0d01f0aa-804f-11e4-8126-164236034a47.png)

Notes from @isaackeyet

> I would really avoid porting another big table like this over. We should figure out why people find it interesting to see all this numbers and then use that to craft something better. For instance, I doubt people care much about comparing total per month numbers for their entire site, by month, year over year (which would be the "April" column for instance). But perhaps it's interesting to somehow chart the average values month-by-month over time or over a whole year on average per month. All those things could make for some nice charts.

**Comment by timmyc** [comment]
In order to get this going it will be nice to have #10871 and #10872 in place to re-use the tables.

Also discovered that we can utilize the existing `statsVisits` endpoint to grab all the data needed:

```
/sites/${ site }/stats/visits?stat_fields=views&quantity=-1
```

**Comment by timmyc** [comment]
Before we dive into this, I was hoping to get some input from @karmatosed or @folletto on design.  From Isaac's notes, he obviously was not a fan of the design of the old tables.  However, the All Time Summary is missed by users.

Couple of design questions:

1. Where would we create a link to this page?  Perhaps from the "All Time" module on Insights?  Historically it was a text link called "Summary" right above the visits chart.
2. Isaac mentioned the data would be neat to chart.  Any thoughts on visualizations on this page?

From the feedback thread, users also asked for the ability to download this data as .csv.  That would be a nice addition too.

**Comment by folletto** [comment]
Heya! It probably needs some design work... :|

The two quick answers I can give with little context and depth on the spot are:

1. Insight today is imho the "All Times" view (maybe we should just rename that? dunno). So yes, we can probably add it on the right hand side of "All-time posts" as a small button labelled "Full stats"
2. I think it could still be a "table", but with some strong tweaks in terms of visualization to be more of a heatmap (i.e. colors and normalized numbers "12k"). 

I also agree on Isaac's position there... we need to figure out how. :)

Also yes to CSV export all from here, again with a link in the footer. ;)

**Comment by timmyc** [comment]
> I think it could still be a "table", but with some strong tweaks in terms of visualization to be more of a heatmap (i.e. colors and normalized numbers "12k")

I really like the heatmap akin to mc-stats tables.  Regarding normalized numbers, we had a thread around that topic and i18n pxLjZ-29B-p2.  Summary there was normalized numbers are available via CLDR, or possibly via http://numeraljs.com/#format****

**Comment by drw158** [comment]
+1 for normalized numbers. I love how Twitter handles it for likes and retweets. 37.6K, 50.8K, 22.2M

**Comment by folletto** [comment]
![stats-table-heat](https://cloud.githubusercontent.com/assets/4389/22511988/6eaacbec-e88f-11e6-915b-5148eaf9f526.png)

This is a very basic idea, just reusing existing stuff:

1. Pill at the top instead of two panels, since essentially they are different views on the same data
2. Basic table (so it resizes as needed)
3. Heatmap using the same colors of Insight (I'm not sure these colors are super effective, but I stuck with that to avoid reviewing them) 
3. Every cell is tappable. If tapped it shows the number in the full format (1M → 1,035,933)
4. Row/Col headers are tappable too, and show the total.

I understand it's not too fancy, but it can be a basic starting point.

**Comment by karmatosed** [comment]
I really like that suggestion for reusing what we have. I wonder if adding a scale note would be good. Or maybe an arrow showing it goes from light to dark?

**Comment by folletto** [comment]
Ah yes, we can probably reuse the one on insights:

![screen shot 2017-02-01 at 15 31 34](https://cloud.githubusercontent.com/assets/4389/22513250/8d83614c-e893-11e6-9b87-58cc58111e43.png)
