### ISSUE TITLE
Comments: make inline post title text stand out

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#19605]
We need a subtile way to distinguish the post title text within comments.

Current example (Update your Avatar on WordPress.com):

![screen shot 2017-11-08 at 12 06 26 pm](https://user-images.githubusercontent.com/618551/32566366-4d7307da-c47d-11e7-9fb5-1fcc40fb05fe.png)
![screen shot 2017-11-08 at 12 06 21 pm](https://user-images.githubusercontent.com/618551/32566370-4fe59af0-c47d-11e7-86e6-54fc641b4dde.png)

We have received feedback that it blends in, and it's hard to distinguish amongst the other comment text. I agree.

Here is one way we can do that:

- use Merriweather
- add author avatar

![screen shot 2017-11-08 at 12 09 00 pm](https://user-images.githubusercontent.com/618551/32566470-a6025be4-c47d-11e7-827a-14cac880bab3.png)

If the avatar is too much, we can drop it. I think just the font change will help a lot.

The font change would also apply to the collapsed view:

![screen shot 2017-11-08 at 11 25 41 am](https://user-images.githubusercontent.com/618551/32566623-21256168-c47e-11e7-84ac-302f3cfa2072.png)

**Comment by Copons** [comment]
For the sake of completeness, I'd go with the option not mentioned in the PR, which uses a gridicon instead of the blavatar:

![screen_shot_2017-11-08_at_11 50 44_am_1024](https://user-images.githubusercontent.com/2070010/32566969-ac0f23f8-c4b1-11e7-9edd-3bfc87325b79.png)

**Comment by Copons** [comment]
For the sake of completeness, I'd go with the option not mentioned in the PR, which uses a gridicon instead of the blavatar:

![screen_shot_2017-11-08_at_11 50 44_am_1024](https://user-images.githubusercontent.com/2070010/32566969-ac0f23f8-c4b1-11e7-9edd-3bfc87325b79.png)

**Comment by Copons** [comment]
For the sake of completeness, I'd go with the option not mentioned in the PR, which uses a gridicon instead of the blavatar:

![screen_shot_2017-11-08_at_11 50 44_am_1024](https://user-images.githubusercontent.com/2070010/32566969-ac0f23f8-c4b1-11e7-9edd-3bfc87325b79.png)
