### ISSUE TITLE
Activity Log: short event descriptions drop below actor

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#19600]
<img width="802" alt="captura de pantalla 2017-11-08 a la s 12 11 02" src="https://user-images.githubusercontent.com/1041600/32556342-e919c840-c47d-11e7-948d-141599f738ca.png">

**Comment by MichaelArestad** [comment]
@eliorivero Is this fixed for you in prod?

**Comment by eliorivero** [comment]
It's showing this which I believe is ok since the longer descriptions also drop:

<img width="691" alt="captura de pantalla 2018-01-02 a la s 16 16 35" src="https://user-images.githubusercontent.com/1041600/34496626-f12a5762-efd8-11e7-8113-26d8d15569c4.png">

So will close this.

**Comment by MichaelArestad** [comment]
Ah. That might be a breakpoint thing. Does it do that at wider screen widths?

**Comment by eliorivero** [comment]
Nope, elements stay there

<img width="1062" alt="captura de pantalla 2018-01-02 a la s 16 25 55" src="https://user-images.githubusercontent.com/1041600/34496779-a22937ea-efd9-11e7-9640-a75c09a99492.png">

**Comment by MichaelArestad** [comment]
Awesome. Thanks.
