### ISSUE TITLE
Conversations stream: hide posts that have been muted

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#19603]
When a user has hit 'Unfollow conversation' in the Conversations stream, we should probably hide the post that caused them to take the action.

@blowery says: "probably flop it for a placeholder / undo block like we do for blocks"

**Comment by jancavan** [comment]
Left a comment here: https://github.com/Automattic/wp-calypso/pull/19602#issuecomment-343278628

I think the behavior of both buttons (Follow Site and Follow Conversations) should mirror each other. We don't do this when unfollowing a site and that's ok. I also want to avoid that issue (that happens after blocking) where we display a series of undos:

![screenshot 2017-11-09 13 39 01](https://user-images.githubusercontent.com/4924246/32630942-5c473138-c553-11e7-8a24-4fc46513af16.png)
