### ISSUE TITLE
Activity Log: post auto saving registered as event

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#19601]
![drafts](https://user-images.githubusercontent.com/1041600/32557985-790217a6-c482-11e7-9ae5-805fcf4dbfac.gif)

These events shouldn't be taken into account as they're too many, impractical to track, there's little difference from one to the other, most can't be rewinded to, it's too much noise.

@roccotripaldi @gititon not sure if this requires some PR in Jetpack or branch in wpcom where this is already fixed but since I saw nothing in Jetpack repo I opened this one to track this.

**Comment by roccotripaldi** [comment]
working on calypso side here:
https://github.com/Automattic/wp-calypso/pull/19261

**Comment by gititon** [comment]
@eliorivero can you please try this again (make sure you're using Jetpack beta bleeding edge) and let us know if it resolves the issue for you?

**Comment by eliorivero** [comment]
It's solved now, good work Rocco and Michael 👍
