### ISSUE TITLE
Activity Log - Issues detected emails

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#19610]
## Plugins and themes

Both plugins and themes emails will be identical except we will replace references to `plugin` or `plugins` with `theme` or `themes`.

There are three types of emails. The first will show up if there happens to be an update to the plugin or theme. It will encourage the user to update which will wipe out the malicious code. This is to prevent the user from having to rewind their site and deal with lost content/comments/etc.

![issue detected - update plugin](https://user-images.githubusercontent.com/1123119/32571078-799220b6-c483-11e7-9e47-863187a725fc.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Jetpack found a potential issue with a plugin on your site, michael.blog. Malicious code may have been injected into the Hugh plugin. 

> Let's fix this

> We recommend updating your plugin to the latest version. You may also want to consider enabling plugin autoupdates so your plugins are kept up to date and safe!

> Update plugin

The second will show up if there is no update available. It encourages a rewind.

![issue detected - rewind plugin](https://user-images.githubusercontent.com/1123119/32571129-94e3fdee-c483-11e7-8085-fbf5a4aea136.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Jetpack found a potential issue with a plugin on your site, michael.blog. Malicious code may have been injected into the Hugh plugin.  

> Let's fix this

> The most recent backup of this plugin without the malicious code is from January 12, 2017. To remove the malicious code, you can head over to your site's Activity log and rewind your site at least that far.

> Rewind site

The third type of email will show up if the plugin or theme has a security threat in all versions:

![issue detected - deactivate plugin](https://user-images.githubusercontent.com/1123119/32679451-b7ed7a6c-c623-11e7-8d3c-eef0f7006473.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Jetpack found a potential issue with a plugin on your site, michael.blog. There is a security issue with Hugh plugin that could compromise your site. 

> Let's fix this

> This security issue was found in all recent versions of the plugin. We have contacted the author encouraging them to fix the issue. Our recommendation is to deactivate it until the next plugin update.

> Deactivate plugin

## Core files

If there is an issue detected with WordPress files, we will have to rewind. The following email encourages just that.

![issue detected - rewind core](https://user-images.githubusercontent.com/1123119/32571985-7b1612b4-c486-11e7-881b-e45fea0b22e6.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Jetpack found a potential issue with your site, michael.blog. Malicious code may have been injected into your WordPress installation. 

> Let's fix this

> The most recent backup of your site without the malicious code is from January 12, 2017. To remove the malicious code, you can head over to your site's Activity log and rewind your site at least that far.

> Rewind site

**Comment by MichaelArestad** [comment]
Updated with third type of email for when there is a plugin or theme with a security threat in all versions (or maybe all recent versions?). Hat tip @thingalon

**Comment by samhotchkiss** [comment]
@singerb -- can you please close this one, as well, after confirming that it's shipped?

**Comment by singerb** [comment]
Awaiting final re-review, but almost done, yes.
