### ISSUE TITLE
Stats: timestamp is missing from date heading

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1961]
Steps to reproduce:
1. Go to https://wordpress.com/stats and select a site if prompted
2. Current day's stats appear complete even though they are only partial since the day isn't finished yet

In `/my-stats` we displayed a timestamp next to the date:

![puns1lolgl](https://cloud.githubusercontent.com/assets/1119271/12022279/47001e7c-ad5c-11e5-949e-7d46403cf684.png)

**Comment by rclations** [comment]
I think this can be closed, since `/my-stats` no longer exists (#10213) and a "Last Updated" timestamp is included in the current stats display (61dd89105c2996137c578209bb20ae267a887bfe)
