### ISSUE TITLE
Activity Log - Issues detected notifications

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#19612]
## Plugins and themes

Both plugins and themes notifications will be identical except we will replace references to `plugin` or `plugins` with `theme` or `themes`.

There are three types of notifications. The first will show up if there happens to be an update to the plugin or theme. It will encourage the user to update which will wipe out the malicious code. This is to prevent the user from having to rewind their site and deal with lost content/comments/etc.

![issue dected - update plugin](https://user-images.githubusercontent.com/1123119/32862535-9bfc6124-ca15-11e7-8e8b-4b0664a6bf1b.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Malicious code may have been injected into the Hugh plugin on Michael.blog.

> We recommend updating your plugin to the latest version. You may also want to consider enabling plugin autoupdates so your plugins are kept up to date and safe.

---

The second will show up if there is no update available. It encourages a rewind.

![issue dected - rewind plugin](https://user-images.githubusercontent.com/1123119/32862627-eea63bb6-ca15-11e7-99de-56ea6adbe403.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Malicious code may have been injected into the Hugh plugin on Michael.blog.

> We recommend rewinding your site to the latest version without to the malicious code. The most recent backup of this plugin without the malicious code is from January 12, 2017.

---

The third type of notification will show up if the plugin or theme has a security threat in all versions:

![issue dected - deactivate plugin](https://user-images.githubusercontent.com/1123119/32862742-5a3682be-ca16-11e7-932e-69ef37091b4c.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Malicious code may have been injected into the Hugh plugin on Michael.blog.

> This security issue was found in all recent versions of the plugin. We have contacted the author encouraging them to fix the issue. We recommend deactivating Hugh to the latest version.

## Core files

If there is an issue detected with WordPress files, we will have to rewind. The following notification encourages just that.

![issue dected - rewind wordpress](https://user-images.githubusercontent.com/1123119/32862738-5642acd2-ca16-11e7-8f1d-8af63ae55b17.jpg)

Plaintext for the lovely folks implementing this:

> Jetpack detected a possible security threat

> Malicious code may have been injected into your site, Michael.blog.

> We recommend rewinding your site to the latest version without to the malicious code. The most recent backup of this plugin without the malicious code is from January 12, 2017.

**Comment by MichaelArestad** [comment]
Updated with third type of notification for when there is a plugin or theme with a security threat in all versions (or maybe all recent versions?). Hat tip @thingalon

**Comment by samhotchkiss** [comment]
This is completed, right @singerb ?  If so, can you please close?

**Comment by singerb** [comment]
No, the notification here has not been started, just the e-mail.
