### ISSUE TITLE
Store Shipping Labels: Editing an order doesn't update items in packages

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#19619]
This will be an issue once #19243 is merged. If you edit an existing order and add a product, then go  to "Print label & fulfill" the order, you don't see the added product in the packages step.

My order, with the newly added item:
![order](https://user-images.githubusercontent.com/541093/32579729-363a2ca0-c4b0-11e7-97ac-5438f1a7f5fd.png)

The packages list, still only 1 item:
![packages](https://user-images.githubusercontent.com/541093/32579728-36298986-c4b0-11e7-8ec2-755948b7de08.png)

To reproduce, check out the branch in #19243 and…

- View an order: `/store/order/:site/:orderId` (one with payment pending makes the most sense logically)
- Click "Edit Order" in the top right
- Click "+ Add Products" and select a product from the modal to add, click "Add Product" to add it.
- Save your order to update the totals etc
- You have the Fulfillment card back, so now try to "Print label & fulfill"
- Click open the Packages step, it doesn't have the product you just added.

If this was fetching the order data from the API, it should've updated with the new items, because the order has been saved on the remote site. I'm assuming I could also change product quantities or delete items (which are both in master, behind a feature flag), and it wouldn't update that either.

cc @DanReyLop @marcinbot @dechov

**Comment by ryelle** [comment]
The shipping address in the label modal also doesn't update if you update the customer's shipping address. Order editing is merged and live on wpcalypso, would be great to get this fixed up before we push to production.

It seems like the destination is cached, because even after updating the address on an order, the response from `/wc/v1/connect/label/:id` still has the old address in `destination`.

**Comment by justinshreve** [comment]
Hey @DanReyLop - I just wanted to follow-up here. Have you had a chance to look at this?
