### ISSUE TITLE
Make New Calypso Screenshot for Readme

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#19637]
In our main README.md that shows on https://wordpress.com/automattic/wp-calypso, we have the most outdated screenshot of Calypso Editor, linked directly from https://developer.wordpress.com/calypso/.

Can we update this to reflect our current state more? This screenshot was taken sometime in 2015 and especially the editor got a ton of updates since.

This is the original commit by @nb back in 2015: 435101a954012bd2932f2b536e3e9c73808fe1ff

cc: @folletto @drw158 

To kick-start this, I made a screenshot using one of our wpcom example accounts (PCYsg-6hV-p2) but I'm not sure if we want to embed it as-is or we want to add some fade-out or something that will make it look like the current screen.

<img width="985" alt="screen shot 2017-11-09 at 16 17 44" src="https://user-images.githubusercontent.com/156676/32614196-06195e98-c56d-11e7-9f2b-798c51009764.png">

**Comment by drw158** [comment]
Here's my idea. I'd like confirmation from another designer if this is good to 🚢 

![calypso-image](https://user-images.githubusercontent.com/618551/32862870-25f23de6-ca1f-11e7-9bf1-83ac156ec42b.png)

**Comment by folletto** [comment]
I like the merge of the illustration style and the screenshot, but I feel it clashes a bit when used at such a large scale. The bottom thinning lines work well, I feel the part a bit more out of place is the top rounded corners.

That said, I also recognize it's more of a personal consideration than an objective one, so I wouldn't have any concern in going live with this as it's already a step forward 👍
