### ISSUE TITLE
Publicize: change custom message length to 280 chars now that Twitter supports it

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#19630]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. If you've connected a Social Media account to your site, you will see the following box:

![screenshot 2017-11-09 at 13 35 05](https://user-images.githubusercontent.com/426388/32605749-ee686aec-c552-11e7-856c-11d24d4827bc.png)

Since Twitter now supports more characters, it would be nice to expand the limit accordingly:
https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html

Related: https://github.com/Automattic/jetpack/issues/8134

**Comment by KokkieH** [comment]
We've already had several requests for this via Twitter. Naturally.

**Comment by darnelldibbles** [comment]
Another request:

https://en.forums.wordpress.com/topic/publicize-to-twitter-280-characters?replies=1#add-note

**Comment by supernovia** [comment]
https://twitter.com/robilaz/status/930934602260271106

**Comment by jeherve** [comment]
Related: D8438-code

**Comment by vindl** [comment]
@jeherve beat me to it, I started something similar in D8439-code. :)

**Comment by lamdayap** [comment]
request here: 811582-zen

**Comment by jeherve** [comment]
Also in 834293-zen

**Comment by jesscga** [comment]
Also 604791-hc

**Comment by pmciano** [comment]
[Reported in the forums](https://wordpress.org/support/topic/publicize-still-chops-post-titles-on-twitter-after-update/)

**Comment by nielslange** [comment]
Yet another one: 1325093-hc

**Comment by arunsathiya** [comment]
@pmciano According to that forum post, the new update is not working as expected

Can anyone confirm if this update is available for all users, and is it working as expected? Thanks.

**Comment by jeherve** [comment]
@arunsathiya

> Can anyone confirm if this update is available for all users, and is it working as expected?

It is not yet available. We will update and close this issue when it is.

**Comment by lancewillett** [comment]
Just came by to 👍 this — can't wait until it's in. Now that I can make longer Twitter messages it feels like the Calypso UI is broken.

**Comment by KokkieH** [comment]
@arunsathiya the Publicize description is pre-populated with your post title and link, and shows remaining characters based on that. If you start typing your own description, the pre-added post title is removed, so that's where the additional characters come from. If you have more questions about how Publicize currently works, I think a new forum thread would be a more appropriate place for discussion than this issue. Feel free to start a new thread and tag it for staff and we'll help you there.

**Comment by jeherve** [comment]
> This is an indication that it seems to be available, maybe unintentionally? If this is not ready for public consumption, why do I see it?

@arunsathiya This was changed in Jetpack in https://github.com/Automattic/jetpack/pull/8219, but unfortunately we made the change a bit too early as the part of Publicize that lives on WordPress.com is not ready to be deployed yet.

We'll update this issue once the 280 chars are available everywhere, for everyone.

**Comment by supernovia** [comment]
Another request here: https://twitter.com/DrkwingDuck/status/949687806611378176
