### ISSUE TITLE
Stats: "Categories & Tags" module missing for Jetpack sites

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1964]
Steps to reproduce:
1. Go to https://wordpress.com and switch to a Jetpack site
2. Go to Stats > Insights > Other Recent Stats
3. Look for the "Tags & Categories" module
4. Compare to a WordPress.com site

<strong>Result:</strong> the "Tags & Categories" module is not available for Jetpack sites

Notes from @beaulebens 

> We're not syncing any terms/taxonomy stuff from Jetpack. We're looking at an overhaul/improvement to syncing across the board for Jetpack, and this is part of it. It's going to take a little while though, because it's a pretty big project.

**Comment by lamdayap** [comment]
A user queries us about this so I asked the question to the Jetpack team and we're now syncing taxonomies through here, although it looks like we're grabbing all taxonomies and not just tags/categories:

https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-module-terms.php#L11

**Comment by Copons** [comment]
Do we still need this?

In what appears to be the [relevant code](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/site.jsx#L82-L94):
```es6
// Video plays, and tags and categories are not supported in JetPack Stats
if ( ! isJetpack ) {
	videoList = (
		<StatsModule
			path="videoplays"
			moduleStrings={ moduleStrings.videoplays }
			period={ this.props.period }
			query={ query }
			statType="statsVideoPlays"
			showSummaryLink
		/>
	);
}
```
I can see that the comment refers to tags and categories but I couldn't find any mention of them anywhere.
Additionally, I can't seem to find tags and categories stats on my .com sites as well.

**Comment by beaulebens** [comment]
Also, VideoPress is available in (some) Jetpack sites now as well, so ideally this would be implemented/tested for those sites anyway.

**Comment by mbhthompson** [comment]
It's been reported in 3188809-t that VideoPress stats are not showing up for JP site. I noticed this on my personal JP site as well.

**Comment by rralian** [comment]
fwiw I've tested the relevant endpoints:
- v1.1/sites/$site/stats/video-plays
- v1.1/sites/$site/stats/tags

Video seems to work fine for my Jetpack site. I think we can just enable it in Calypso. However tags isn't returning any data for me. We'd need to dive deeper into that one.

**Comment by lancewillett** [comment]
This one still needs investigation into querying taxonomies for Jetpack sites.

**Comment by htdat** [comment]
Regarding VideoPress stats, I can see them under these places:

* WP Admin -> Jetpack -> Site Stats
* Or https://wordpress.com/my-stats/

---
Tix: 695465-zen

**Comment by lamdayap** [comment]
@htdat - It looks like in this particular case, the user in 695465-zen isn't getting any stats. Were you able to see them?

**Comment by htdat** [comment]
@lamdayap 

> It looks like in this particular case, the user in 695465-zen isn't getting any stats. Were you able to see them?

On this link http://a-domain.com/time-can-help-heal-a-feralstray-cat/, they're using this video http://a-domain.com/wp-content/uploads/2017/08/img_6298.mp4?_=1. It's not a VideoPress link.

I will reply on the ticket 695465-zen

**Comment by lancewillett** [comment]
Looping back on this one, so it doesn't get lost. What's left, investigating the taxonomy queries?

**Comment by lancewillett** [comment]
Closing this one for now. If we get more reports — or work on Stats again in the future — we can reopen it.

**Comment by danjjohnson** [comment]
Just noting that someone asked about category stats in 950005-zen
