### ISSUE TITLE
Comments: investigate how much we can reuse from reader components

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19652]
In M4 we're planning on creating a threaded-view #19238  that shows comments for a given post. Reader has already solved this problem for a different use case (consumption). To keep scope in check, we'll want to reuse as much as we can from reader comments (data-fetching, behavior etc), with different presentational components. Let the team know if we have any blockers for doing so.

**Comment by Copons** [comment]
As it happens, we're taking inspiration from `PostCommentList` but we won't reuse it.
It has too much logic that we don't need, and adding our `Comment` into that feels really forced.

I'm closing this for now.
