### ISSUE TITLE
Stats: overview chart bars are not centered horizontally

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1965]
Raised by @gcorne 

I have noticed that the bar graph is not centered horizontally. 

![screen shot 2015-12-28 at mon dec 28 1 01 52 pm](https://cloud.githubusercontent.com/assets/1119271/12023041/952cb496-ad63-11e5-88de-263375abf684.png)

Notes from @timmyc 

> I believe the extra white space on the right is due to keeping enough room to accommodate large y-axis labels. 
> 
> ![screen shot 2015-12-28 at mon dec 28 1 00 52 pm](https://cloud.githubusercontent.com/assets/1119271/12023073/ccd33b86-ad63-11e5-9d19-4dc4b8e1924c.png)
> 
> There has been discussion about making these labels restrain to a certain number of characters by using abbreviations for large numbers - but even with that I think on small numbers there will be an excess of white space over there.
> 
> It would probably be nice to make the y-axis label area dynamic, and I believe it was at one point, but when switching between charts, we could get a jumpy feeling where something like Views/Visitors may have a larger y-axis number and comments and likes are smaller. This would result in the width of the bars between these charts changing sizes as well.

Notes from @jancavan 

> Instead of having the y-axis labels on both sides, maybe we can just move it to the left. I think on standard graphs, the y-axis is almost always on the left. The right is only used if you have additional data to plot on the Y-axis.
> 
> ![barchart-yaxis](https://cloud.githubusercontent.com/assets/4924246/6084867/a91c10b6-ade9-11e4-8d93-d8cdb3404648.jpg)

Reply from @gcorne 

>  I think that reads better. I would also consider reflowing the layout based on the width of the y-axis labels and also maybe rethinking how the y-axis is labeled so that it is more data-driven. Right now, it is labeling the space not the data, so it doesn't communicate as much information as it could.

Reply from @timmyc 

> I personally like the labels on the right - I could get on board with reflowing the chart based off the label width like we have done in old stats, but I really do think the jump nature when switching between charts and having the width of the bars change would look odd.
> 
> Regardless of preferences - the chart is a huge feature to our users, and would love to test out any design ideas if we could first.

**Comment by jancavan** [comment]
I think we can close this for now. We can reopen when we revisit this issue.
