### ISSUE TITLE
.org Plans: pop-up feature descriptions are misplaced

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#19666]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/:site, where :site is a connected Jetpack site.
2. Click on the right-most column information icon and change the width of the browser window 
(in any order)

#### What I expected
The pop-up to be centered at the `i` information icon

#### What happened instead
The  pop-ups in the rightmost column are hooked at alternative locations ( -> screenshots below )

#### Browser / OS version
Firefox/macOS Sierra

#### Screenshot / Video
![screen shot 2017-11-10 at 13 07 15](https://user-images.githubusercontent.com/13561163/32658454-5de8b120-c61a-11e7-9e04-f01d49784dc7.png)
![screen shot 2017-11-10 at 13 02 40](https://user-images.githubusercontent.com/13561163/32658479-752c59a4-c61a-11e7-9174-f00312dd65ec.png)

#### Context / Source

Found while working on https://github.com/Automattic/wp-calypso/pull/19665
AND
while we are at it, we could re-think how the pop-up components should scale wrt to the screen size/platform. At the moment they are not fully responsive.

**Comment by tyxla** [comment]
Related:

https://github.com/Automattic/wp-calypso/issues/14580
https://github.com/Automattic/jetpack/pull/7254#issuecomment-304665375

**Comment by sirreal** [comment]
Note that I don't need to resize the browser. Open, close, open the same popover shows it in the wrong position:

![no-resize](https://user-images.githubusercontent.com/841763/32718863-c4f99f96-c85e-11e7-87a8-f1c7b8e6c9c5.gif)

**Comment by sirreal** [comment]
Popover positioning has some open issues, see #13602 and #9007

**Comment by AnnaMag** [comment]
more related:
https://github.com/Automattic/wp-calypso/issues/9007

**Comment by AnnaMag** [comment]
Note: the misplacement is fixed with any action that re-renders the layout, e.g. scrolling
