### ISSUE TITLE
Preview of Post Page displays the front page instead of the post page

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/wp-calypso#19689]
#### Steps to reproduce
1. Go to Customize > Static Front Page
2. Select a Static Front Page and a page to display the latest post
3. Edit the page that was selected to display the latest post
4. Press Preview

#### What I expected
The latest post page will be shown in Preview

#### What happened instead
Preview shows the Front Page

**Comment by rachelmcr** [comment]
This is a WordPress core bug, being tracked here: https://core.trac.wordpress.org/ticket/41226
