### ISSUE TITLE
Stats: hovering over links should show full URL in status bar

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1969]
Raised by @astralbodies 

When I'm looking at my stats (in particular the clicks or referrers modules) I'd like to see the URL in the browser status bar when I hover over a link. Right now I have to click the link to find out the URL and half the time it redirects to the main page of the site.

Notes from @timmyc 

> all the rows in stats-lists, and their primary actions are just click events on an `<li>` element so that is why on hover the link text isn't shown.  This has been brought up before ( I think by @jblz ) - I suppose we could look at a way of hacking `window.statusbar` and listening to hover events on these elements - or revisit the row construction itself and move to `<a>` tags.
> 
> the current issues with the span-based approach are:
> - Lack of Tooltip
> - Accessibility
> - Not Semantic

Notes from @isaackeyet 

> As a part of this I also think we should create the module-list and module-list-item components for realz so that these bits can easily be reused in other parts of Calypso down the line. It also calls for quite a bit of refactoring, especially on the list items, which have a pretty bad structure at this point and the classnames are ridiculous :)

**Comment by isaackeyet** [comment]
@timmyc almost had this at one point! I explored it too. Basically it comes down to the columns, you'd have to calculate column widths on the fly and apply widths for things to line up properly, at least as long as there are secondary actions that are inline. Another way of solving that could be a unified contextual menu shown to the right or left of the rest of the selectable area, and just always make all options hidden. Maybe not such a huge problem as long as the important actions are reworked too, such as following a user in a user list. Gravatar hovercards MIA?
