### ISSUE TITLE
Domains: check email address when adding or canceling a custom domain

### ISSUE THREAD

**Issue by wensco** [Automattic/wp-calypso#19716]
Recently, a support issue came up where a user did not get notifications related to their account because they canceled their custom domain and the WordPress.com user account email address used that same domain (eg, account email was me@example.com and the canceled domain is example.com).

It's generally not a good idea to use an email address for domain registrant contact info that uses the domain in question and it's also not a great idea to let someone cancel a domain if their wpcom account email uses it.

This lead me to think it would be nice to have a couple of checks in place to prevent users from unintentionally breaking their email address that they would normally use for account access and notifications and/or for domain-specific notifications.

1. As part of the domain cancelation flow, we can check if their wpcom account email uses the same domain. Then display a message to ask them to update their wpcom account email before canceling the domain.
1. As part of the domain registration flow (or contact update), display a warning if the user enters an email address that uses the same domain.

**Comment by dcoleonline** [comment]
The support issue was 764572-zen
