### ISSUE TITLE
Store Orders: Adding products to an order doesn't decrease stock

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#19712]
If you order a product though the front end of the site (the "normal" customer flow), the stock of the ordered products is decreased. If you as a store owner edit an order, and add a product to the order, the stock is not decreased. This seems to be an issue in both wp-admin and calypso.

In wp-admin the "solution" seems to be these "Increase/Reduce stock" buttons:
<img width="721" alt="screen shot 2017-11-13 at 12 56 54 pm" src="https://user-images.githubusercontent.com/541093/32740907-73796b6a-c872-11e7-808d-c1405c3e1b69.png">

Should we do something similar? Or should we just assume any products added to an order should reduce stock? (there might be a tech limitation here, I'll have to investigate WC core to see if this is possible via the order update API) I'm wondering if there's a reason that WC core doesn't do this automatically for orders edited in wp-admin, though.

cc @kellychoffman @jameskoster

**Comment by kellychoffman** [comment]
> I'm wondering if there's a reason that WC core doesn't do this automatically for orders edited in wp-admin, though.

Curious about this as well, as this is what I would expect to happen. 

@mikejolley: care to weigh in? :)

**Comment by mikejolley** [comment]
You can weigh in here https://github.com/woocommerce/woocommerce/issues/13359 ;)

**Comment by kellychoffman** [comment]
Awesome. Since this is being addressed in core, perhaps we can wait until that is implemented?
