### ISSUE TITLE
Reader: undo placeholders for pending comment actions

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19728]
As part of #19718 let's add an undo placeholder, when we `spam` or `trash` a pending comment in the reader. This still needs some design work.

**Comment by drw158** [comment]
Since those are destructive actions I would mirror what we do in /comments:

- Remove comment immediately
- Show global notice with undo button

**Comment by gwwar** [comment]
Closing this out for now due to research findings. We can always revisit later
