### ISSUE TITLE
Stats: add more detailed stats for likes

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1972]
Raised by @timmyc 

Provide a view to show the details about Post/Pages along with the number of likes for each.  Perhaps this could just be an alternate tab view of the existing Post/Pages module.

Notes from @eurello via 3893-gh-calypso-pre-oss

> Yes, it would be good if the likes/comments tabs at the bottom of the stats graph could load more detail, to reduce confusion in situations like the above. [Summary: someone reported seeing 9 likes in their `/stats/day` view but none in notifications—that happened because the notifications are per-user while the likes are for the entire blog and no likes were mentioned in notifications because the likes were for posts by another person.]
> 
> So, for example, if you're looking at the graph and it says 9 likes today, to be able to click on the 9 and see a list of those likes -- which user who liked which post. 

![screen shot 2015-12-28 at mon dec 28 2 33 53 pm](https://cloud.githubusercontent.com/assets/1119271/12024260/5357b572-ad70-11e5-9e9a-c1553c7c37f5.png)
<sup>When you click on "Likes" below the graph, there isn't a way to tell which posts those likes were made on.</sup>

**Comment by formosattic** [comment]
User suggested being able to see the number of Likes per post, for example, when selecting the "Likes" stats tab, have the number of "Likes" displayed, see:

<img width="739" alt="screen_shot_2016-12-06_at_21_42_35" src="https://cloud.githubusercontent.com/assets/15944096/20927571/39563b2a-bbfd-11e6-935b-a962a5a0e888.png">

546570-chat
