### ISSUE TITLE
Posts/Pages: Autosaving of draft causes scroll position to return to top of post.

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/wp-calypso#19730]
In Calypso, when trying to edit a post or page, if the post text is long the screen moves down to accommodate that additional text. If the user briefly stops typing Calypso saves a draft and returns the user to the top of the post or page, causing the user to have to scroll down to where they left off typing. I had two users report this as extremely annoying today. I confirmed and replicated on my ending using Google Chrome.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Add Title
3. Add enough text that the screen begins to scroll down. 
4. Pause typing to allow Calypso to autosave a draft of the post.

#### What I expected
Typically the draft saves and the scroll position is maintained so the user can continue typing uninterrupted.

#### What happened instead
When the post autosaves, the scroll position is returned to the top of the post requiring the user to scroll down to their cursor position to continue typing.

#### Browser / OS version

Chrome Version 61.0.3163.100 (Official Build) (64-bit) / Windows 10 Pro

#### Screenshot / Video

http://cld.wthms.co/8H5nJg

#### Context / Source

#user-report #calypso #posts #pages

**Comment by jblz** [comment]
This should be fixed in #19731. Please reopen & let me know if not.
