### ISSUE TITLE
Comments: threaded data fetching

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19732]
As part of #19238, let's be sure that the /comments section can query for threaded comment data similar to what the reader currently does. Please update this issue with findings from #19652 

Note that for any tabs using a threaded view, we'll be clicking on a "load more comments" link rather than a pager. Please follow any existing reader behavior.

**Comment by Copons** [comment]
If we want to keep 2 levels of depth, then yes, we already have the data we need: we can just filter for those comments in the tree with `commentParentId = 0` to populate the nested level.
