### ISSUE TITLE
Jetpack Elastic search doesn't work on AT sites

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/wp-calypso#19743]
The beta Jetpack Elastic search is available for all Jetpack Business customers - https://jetpack.com/support/search/

It should also be available on atomic sites but the toggle to enable it is missing. This user can't find it and I tested on my own atomic site and it isn't there:

https://wordpress.com/settings/traffic/racheltestsite.blog

#### Steps to reproduce
1. Go to https://wordpress.com/settings/traffic/racheltestsite.blog
2. Search for the toggle "Enable site-wide search powered by Elasticsearch"
3. It's not there.

Ticket: 787421-zen

**Comment by jeherve** [comment]
Related: #18249
cc @gravityrail

**Comment by gibrown** [comment]
@gravityrail shouldn't this be taken care of here: https://github.com/Automattic/wp-calypso/blob/add9eaadd15b3b90fcf3b9bdb8f47b4e473c8949/client/my-sites/site-settings/search.jsx#L78

(I've neglected to test AT or a business plan without AT so far, so my bad. Will try to get something set up).

**Comment by gravityrail** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/21764
