### ISSUE TITLE
Checkout: Credit card payment validation is too verbose for empty fields

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#19747]
Validation errors for empty fields in Credit Card payment screen include not needed validations: If the field is empty, it's validity shouldn't be checked.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Navigate to your site where you can buy a plan (w/ real money)
3. Proceed with to checkout screen
4. Press `Pay ${amount}`

#### Browser / OS version
Chrome 62
MacOS 10.13.1

#### Screenshot / Video
<img width="1222" alt="verbose validation errors" src="https://user-images.githubusercontent.com/5654161/32775836-42df13e8-c939-11e7-874b-f4603f236bb6.png">

#### Context / Source

Discovered during #needstesting for WP Desktop 3.1.0 beta2

**Comment by ramonjd** [comment]
Closed by #21064
