### ISSUE TITLE
Store - Improve flow for when WP.com users install WC plugin in Calypso

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#19757]
We should make folks who install WC manually aware of our onboarding / store management ui.

This is pretty low-hanging fruit.

Here's how we could update the 'plugin installed' notice;

![installed](https://cldup.com/S_yq4H2cPO.png)

And if they ignore that we could display a persistent message like so;

![persistent](https://cldup.com/tF2BaOglRU-3000x3000.png)

EDIT: Adding a design to cover situations where someone might see the Store link, but their store isn't based in the US or Canada;

![nope](https://cldup.com/jCZKcV6HU8.png)

**Comment by budzanowski** [comment]
Could we do something before the installation of woocommerce plugin ( from Calypso )? Present option to go through our setup flow then.

**Comment by jameskoster** [comment]
@budzanowski Hmm, not sure what the question is? This is for folks who go to plugin management in Calypso and install WooCommerce from there. IE folks who might not be aware of our store offering at all.

I did consider simply redirecting to our setup checklist on activation but that might be too jarring in comparison to the standard plugin activation flow.

**Comment by jameskoster** [comment]
Ah, sorry, I should have made that clear. That's exactly what the Get Started link should do. IE behave in the same way as clicking the "Store (beta)" link in the main nav for the first time.

It will be a little awkward if they're not based in the US or Canada though. In that case we'd have to use the third design in this post after they input their address. Perhaps with a more contextual message explaining that stores can only be managed in Calypso if they're based in US or Canada.
