### ISSUE TITLE
Plans: Plan name in sidebar misaligned (Firefox)

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#19752]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans
2. Select a site.
3. Check the Plan item in the sidebar.

#### What I expected

I expected to see "Plan" with my site's plan ("Free") on the right side of the sidebar.

#### What happened instead

The site's plan was misaligned so it was barely visible in the sidebar.

#### Browser / OS version

Firefox 56.0.2, Mac OS 10.12.6.

I also checked Safari and Chrome but didn't see the same issue there.

#### Screenshot / Video

<img width="1528" alt="screenshot 2017-11-14 11 36 17" src="https://user-images.githubusercontent.com/8658164/32778164-c0b72f8e-c930-11e7-9d8c-e7913789a154.png">

#### Context / Source
#manual-testing

**Comment by gwwar** [comment]
<img width="269" alt="screen shot 2018-02-23 at 1 45 56 pm" src="https://user-images.githubusercontent.com/1270189/36618409-e8b8e1ee-189f-11e8-8472-6106da31f226.png">

This must have been fixed someplace else, can't reproduce on FF.
