### ISSUE TITLE
Calypso editor (desktop) gets stuck on one particular site, while editing one particular page. Multiple users, browsers and devices. Not possible to place a cursor.

### ISSUE THREAD

**Issue by grigorijurasov** [Automattic/wp-calypso#19769]
#### Steps to reproduce
A user has reported that they're unable to edit a particular page in Calypso. See 1023621-hc for more details.

**Comment by kriskarkoski** [comment]
@grigorijurasov Can you see if this is the same issue as https://github.com/Automattic/wp-calypso/issues/19745 and if so close this issue and add as a comment there

**Comment by grigorijurasov** [comment]
Hi Kris,

I can confirm that this is the same issue as #19745
<https://github.com/Automattic/wp-calypso/issues/19745>. I will close one
that I created and comment in both.

Best regards,
Grigorij

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
