### ISSUE TITLE
Stats: show a small & representative image in post lists if available

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1976]
Raised by @jblz 

The list of page titles in the module entitled `Posts & Pages` (and possibly elsewhere) would benefit from a _small_ visual representation of the content.  Especially for a photo-heavy blog, this would enhance glance-ability without adding too much flair or distraction.

Currently:
<img alt="screen shot 2015-01-28 at 4 21 20 pm" src="https://cloud.githubusercontent.com/assets/1587282/5947314/22aeb366-a70a-11e4-9a19-1223f6cafb7c.png" width="500" />

Proposed, something like:
<img alt="screen shot 2015-01-30 at 5 12 16 pm" src="https://cloud.githubusercontent.com/assets/1587282/5984314/33cc618a-a8a3-11e4-9bbb-e1c2293879c9.png" width="500" />

See 3488-gh-calypso-pre-oss for a prior `try` at this.

Instead of tacking this onto the API responses, we should use existing tools and methods already in Calypso (& build on, where needed) for selecting the image from the `post` stores.

**Comment by alisterscott** [comment]
This hasn't been looked at for 2 years so closing this one out.
