### ISSUE TITLE
Comments: Moderation Hotlinks

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19774]
As part of #18321 and a follow up to #19635, let's make sure we can still moderate comments from emails. This means that we can hit a route like `/comment/{ siteFragment }/{ commentId }?action={ approve | spam | trash | delete | edit }` and we'll see a notice explaining what action has happened along with the normal comment information (content, history, permalink).

For right now we're going ahead with allowing Calypso to trigger requests from the client controller to do this. In the future we may chose to move more of this work to the server.

Some items to watch out for:
* Timing Issues (with how much data is available)
* Please discuss to finalize the expected route patterns
* Make sure that the comment is re-rendered and some notice is given.
* Edit is a special case, and when this action param is provided, we render the comment in edit mode.

Items:

- [x] Author email links on WordPress.com: D8153-code
- [x] Author email links on Jetpack Sites: https://github.com/Automattic/jetpack/pull/8144
- [x] Moderation email links on WordPress.com: D8153-code
- [x] Moderation email links on Jetpack Sites: https://github.com/Automattic/jetpack/pull/8144
- [x] _Edit_ link on WordPress.com frontend (#17221): D8002-code
- [x] _Edit_ link on Jetpack Sites' frontend (#17221): https://github.com/Automattic/jetpack/pull/8069

**Comment by rodrigoi** [comment]
Jetpack: https://github.com/Automattic/jetpack/pull/8144
WordPress.com: D8153-code

**Comment by gwwar** [comment]
@rodrigoi could you close this one, after the next Jetpack release? Thanks!

**Comment by gwwar** [comment]
Nice, looks like all items are merged!
