### ISSUE TITLE
Reader: Warning message for InfiniteList: isMounted` being deprecated

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#19783]
When tinkering in Calypso, I noticed this warning statement:
```
Warning: InfiniteList: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
```
<img width="455" alt="infinitelist_mounted" src="https://user-images.githubusercontent.com/4505888/32813272-1c3e7ec0-c95e-11e7-83ad-5402eab9471d.png">

**Comment by bluefuton** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/22893.
