### ISSUE TITLE
Activity Log - sync broke notice

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#19780]
This will show up when sync breaks on a user's site. They will likely need Happiness help to resolve this so it should pop open Happy Chat.

![sync-broke](https://user-images.githubusercontent.com/1123119/32810540-a4608d12-c958-11e7-86fc-dbc218430bb4.jpg)

Hat tip @annezazu

**Comment by annezazu** [comment]
Of note, we need tracking in place for whoever implements this. Please comment below with the track event you choose so I can follow up on my end :)

**Comment by annezazu** [comment]
@rcoll will the JITM message include a way to contact support?

**Comment by samhotchkiss** [comment]
@rcoll -- can you link to the JITM issue/PR and close this?  Thanks!
