### ISSUE TITLE
Improve "Your site deserves a boost" notice to communicate better about cart abandonment

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#19789]
This was reported originally here: 793125-zen and solved via slack p1510728111000122-slack-tickets. The user has purchased a plan and domain but receives that message, doesn't understand why if already purchased the products and don't realize that are some products on the cart waiting for the checkout process to be completed, or removed completely.

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/
2. Start to purchase any product, like a domain or a plan, but do not complete the checkout
3. Wait 10 minutes
4. Check the message on your dashboard: "Your site deserves a boost - Complete your purchase"

![screen shot 2017-11-15 at 13 31 04](https://user-images.githubusercontent.com/3812076/32826074-9d8ecee2-ca19-11e7-96e5-231177f67edc.png)

This comes from https://github.com/Automattic/wp-calypso/blob/8abd57fe22b0a778f21d8ea41967fb17d6e478d6/client/my-sites/current-site/index.jsx#L66 , were after 10 minutes with an item on the cart but without the checkout process being completed, the message is prompted.

Maybe we should rephrase the sentence in order to make more clear that they have products on the cart?

cc: @nielslange

**Comment by jamiepalatnik** [comment]
I think it would help to add some mention of the cart. I had a user in a 1:1 today ask how to get rid of this “site deserves a boost” message since it keeps popping up & they already have the Business plan. They were concerned that maybe they had a billing problem.

Ticket: 888521-zen

**Comment by millerf** [comment]
What should it be rephrased to?

What about 'You cart is awaiting for payment: Complete your purchase' ?

**Comment by millerf** [comment]
I pushed a "fix" here: https://github.com/millerf/wp-calypso/commit/406c93030924f7f5fa421fae617fad225c74dddf

Let me know if the text is fine and I'll do a PR
