### ISSUE TITLE
Discover attribution uses a WordPress logo instead of the site icon in some cases.

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#19798]
Some Discover picks show a default WordPress logo instead of the corresponding site's icon. 

---

**Expected Behavior**
The attribution line on a full-post view should display the site icon. This happens correctly for many sites:

<img width="183" alt="screen shot 2017-11-15 at 8 38 50 am" src="https://user-images.githubusercontent.com/1202812/32838884-71814764-c9e0-11e7-992b-72c4eb54a5b0.png">

---

**Actual Behavior**
One some posts however, we're pulling in a default WordPress logo instead.

<img width="314" alt="screen shot 2017-11-15 at 8 34 54 am" src="https://user-images.githubusercontent.com/1202812/32838828-41099eb0-c9e0-11e7-9196-fd820b759ad0.png">

This happens even if the site has an icon that appears in other areas of the Reader:

<img width="809" alt="screen shot 2017-11-15 at 8 41 55 am" src="https://user-images.githubusercontent.com/1202812/32839010-e99f0ccc-c9e0-11e7-9fe2-5594b5971f32.png">

---

**Steps to Reproduce**

Visit the full post view of a Discover post with the issue. Scroll down below the post body to see the attribution line. Example posts: 

- http://calypso.localhost:3000/read/blogs/53424024/posts/30360
- http://calypso.localhost:3000/read/blogs/53424024/posts/29663
- http://calypso.localhost:3000/read/blogs/53424024/posts/29632

---

cc @jancavan, who [noticed this issue](https://github.com/Automattic/wp-calypso/pull/19778#issuecomment-344473584) over at PR #19778

**Comment by bluefuton** [comment]
If I remember rightly, the default logo is handed to us by the API in those cases. I'll pop it on my list!
