### ISSUE TITLE
Incorrect year displayed when uploading to the Media Library

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#19804]
The incorrect year is displayed during the process of uploading files to the Media Library.

#### Steps to reproduce
1. Go to WordPress.com
2. Click Media > Add
3. Choose an image from your computer
4. Look at the date displayed while the image is uploading

#### What I expected

The correct date to be displayed — today would be Nov 15, 2017.

#### What happened instead

Nov 15, 2018 was displayed instead (one year ahead).

Note: clicking Edit on the image after upload showed the correct date — Nov 15, 2017.

#### Browser / OS version

* Chrome
* Firefox
* Safari

#### Screenshot / Video

![media-library-date](https://user-images.githubusercontent.com/11627765/32845006-9b426e12-ca1b-11e7-9481-8652f508fe0b.jpg)

#### Context / Source

#user-report
#manual-testing

Reported in 883871-f

**Comment by designsimply** [comment]
Nice catch! 

I tested and confirmed using Firefox 57.0 on Mac OS X 10.12.6 and could see 2018 listed only during the time the file was uploading (as seen in your screenshot). After the image had uploaded completely, I see just the month and day and can't tell whether the year is right or wrong:

![screen shot 2017-11-15 at wed nov 15 2 25 17 pm](https://user-images.githubusercontent.com/1119271/32861169-2eee3296-ca11-11e7-85c4-f0c19987e49e.png)

**Comment by ice9js** [comment]
Addressed in #19905.
