### ISSUE TITLE
Editor: Formatting dropdown z-index issue on small screens

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#19800]
This is pretty tiny, but I noticed a small z-index issue when viewing the post editor on a mobile device if you have the text formatting dropdown open. The border for the editor intersects the dropdown.

#### Steps to reproduce
(On a mobile device - iPhone 6 tested - or on an emulator)
1. Starting at URL: wordpress.com/post
2. Make sure you're in the visual editor
3. Click the text format dropdown (Paragraph, Heading 1, etc)

#### What I expected
The dropdown to sit on top of other elements

#### What happened instead
Post border intersects the dropdown

#### Browser / OS version
Tested on iPhone 6 on Firefox and Safari with iOS 11.1.1

#### Screenshot / Video
<img width="737" alt="7m7pik" src="https://user-images.githubusercontent.com/7240478/32839927-4e842432-c9d3-11e7-9092-a23a253acdeb.png">

**Comment by designsimply** [comment]
Tested and confirmed using iPhone 6S on iOS 11.1.1.

<img alt="img_1700" src="https://user-images.githubusercontent.com/1119271/32864372-29df3a6a-ca1c-11e7-8563-d31b53ff56d6.PNG" width="375" />

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
