### ISSUE TITLE
Stats: change "Activate Your Stats Page" heading to something more clear

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1980]
Raised by @shawnajean 

I had a chat with a user tonight who was reaching out about how he could activate his stats.

![screen shot 2015-07-30 at 9 31 13 p](https://cloud.githubusercontent.com/assets/775884/8999715/f05b0808-3703-11e5-88c2-4515257471d8.png)

I can see how he got confused. "Want to learn more about how your content performs?" and "Activate Your Stats Page" are about the same size. And the "Write a Post" button is visually associated with the question, not the title of activating.

Notes from @debex 

> Agreed, I don't understand what "Activate your stats page" means either. I see it on test sites I have that don't have much activity.
> 
> If the intention is to encourage users to create more content, I think it needs different wording. It doesn't come across that way to me. Rather, like this user, I read it thinking I'm supposed to find a button or something to enable tracking of stats.

Notes from @dcoleonline 

> Just noting that I had to find this thread to know what the text meant myself. Curiously, the old stats view showed the country data that the new stats view didn't, so I just gave the user a link to the old one for the time being.

**Comment by designsimply** [comment]
The current heading for `/stats/insights/:site` on a brand new site is:

* Activate Your Stats Page

Possible alternatives:

* Add Content to Activate Your Stats
* Write a Post to Activate Your Stats
* Welcome!
* Welcome! Stats Will Display Here After You Publish Content
* (Leave the heading blank)

**Comment by folletto** [comment]
I can't find that string anymore in the codebase, nor I'm able to find that UI anymore. 

Can we check if this is fixed now? :)

**Comment by shawnajean** [comment]
@folletto - Stats page on a brand new site now looks like this:
<img width="1226" alt="screen shot 2016-05-25 at 7 42 01 p" src="https://cloud.githubusercontent.com/assets/775884/15559508/d4a8700c-22b0-11e6-9050-e2f513a474e9.png">

So it looks like this is no longer an issue.
