### ISSUE TITLE
.com Plan: design of the HC card of the Business Plan stands out

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#19806]
#### Steps to reproduce
1. Starting at URL: `../plans/my-plan/:site`, where `:site` is on a Business plan

#### What I expected
The HC Card to follow the design of the ones below it: 
- icon placed on the right-hand side
- use of the standardized bottom margin
- unified color of the buttons

#### What happened instead
please see the screenshot

#### Browser / OS version
Firefox, Chrome/ macOS Sierra 

#### Screenshot / Video
![screen shot 2017-11-15 at 17 12 18](https://user-images.githubusercontent.com/13561163/32846610-f7e90f0c-ca27-11e7-89e9-b839d9855a2f.png)

compared to e.g.
![screen shot 2017-11-14 at 22 31 12](https://user-images.githubusercontent.com/13561163/32846477-a44f8e3e-ca27-11e7-9f0a-06db57943a55.png)

**Comment by AnnaMag** [comment]
Note: the `Your Site is on a Business Plan` could possibly also be adjusted?

**Comment by drw158** [comment]
Biggest issue I see here is:

The bottom margin on the first card, and the buttons. All of the buttons should be white, except for the manage payment button, which should be blue.

The other issues don't bother me so much.
