### ISSUE TITLE
Framework: Codemods

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19815]
It has been great to see many developers jump to help clear the maintenance backlog and prepare us for updates like React 16 by writing and running codemods. Updating our code to the new standards has actually improved performance and code execution time.

More:
https://github.com/Automattic/wp-calypso/projects/49

**Comment by samouri** [comment]
Just about everything from the React 16 Project has been finished
Can we close this issue or do you think there are still things to explore in the codemod space that this issue will help us track?

**Comment by apeatling** [comment]
If there's more to explore, let's open a new issue. Will close this.
