### ISSUE TITLE
Framework: The Weight of Dead Code

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19825]
Related to maintenance tasks — reality is we are loading a lot of code, including deprecated alternatives (EventEmitter, Flux, Immutable, etc), and it is hard to estimate a baseline for performance improvements with these chains. 

There are also integrated libraries (like jQuery in paygate and wpcom.js) we are pulling unnecessarily. While efforts to reduce initial load like CSS splitting and async loading are good, sometimes we are loading just as much weight through these dependencies we could more easily eliminate and get big benefits. 

For example, wpcom.js uses rest-proxy which downloads 38 KB of compressed jQuery. Furthermore, we are also using the superagent library for other requests, which is also not trivial in size. 

Consolidating mechanisms here and reducing library overhead, removing the ones we don't need, can have a significant impact on the performance of the application for a smaller effort.

**Comment by samouri** [comment]
status update: I believe @jsnajdr improved the wpcom.js rest-proxy to be very lightweight
