### ISSUE TITLE
Framework: Eliminate Pug (formerly known as Jade)

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19822]
Get rid of Pug templating on the server. This is a relic from a very early Calypso prototype that no longer makes sense as a specialized syntax for just a couple of files serving a shell. 

Either use JSX, or template literals. Be mindful of caching. [Previous attempts](https://github.com/Automattic/wp-calypso/pull/8459).

**Comment by ockham** [comment]
Edited post to `s/Jade/Pug/g` because of #19984.

**Comment by ehg** [comment]
Any method chosen should allow us transition to `renderToNodeStream`, which allows us to stream SSR responses and will presumably free up the event loop a bit.
