### ISSUE TITLE
Framework: Polling

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19840]
Parts of Calypso rely on polling (like sites) to retrieve fresh data periodically. This needs to continue working and iterated upon.

See main framework Calypso P2 post for relevant links.

**Comment by apeatling** [comment]
Sites does not use polling now.

**Comment by dmsnell** [comment]
Polling exists in a number of forms right now:
 - use the `<Interval />` wrapper inside a query component (#19604)
 - take data-specific concerns and poll from within the data layer handlers (#20459)

Important in polling is knowing when we still want to poll and when we want to stop. This depends in almost all cases on `render()`

We have taken many strides to build a generalized system of `freshness` implying "we need data in Calypso that was checked within the past N seconds"

#19060 and #22549 are iterations on an idea (and I have yet to add some code on my laptop into a PR) that build the auto-polling mechanism into the `freshness` flag.
