### ISSUE TITLE
Framework: CSS Splitting

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19847]
Manually separate stylesheets for components, blocks, sections. There are plans for Webpack 4 to generate CSS assets as part of the split pipeline, avoiding the drawbacks of all CSS-in-JS approaches which we have deemed not good for our project.

Initial [work for extensions](https://github.com/Automattic/wp-calypso/pull/18823) and main core sections [has already happened](https://github.com/Automattic/wp-calypso/pull/17988).

**Comment by apeatling** [comment]
This is planned for a webpack 4.X release. Need to wait on this.

**Comment by jsnajdr** [comment]
The complete build pipeline for CSS in Webpack has landed in #26820. What remains is to migrate all 800+ SCSS stylesheets to JS imports inside the JS components that own them.
