### ISSUE TITLE
Stats: add stat for followers per unit of time

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1984]
Raised by @andreabadgley

> I report on all the analytics for my company and I need to know if there is a way I can view the number of subscribers per month? i.e - I would like to know how many new subscribers subscribed during August

I looked in Insights and stats by day/month and see that we count views and visitors in time increments, but not followers. This is a stat I have been interested in on my personal blog as well: do my follower counts increase when I post daily vs every other day vs once a month? Or maybe I _lose_ followers when I post every single day? How do posting habits affect followers? I posted every day for the month of April, but my follower data is not easy to parse five months later when I'd like to analyze it for a talk.

**Comment by alexjgustafson** [comment]
2866120-t
