### ISSUE TITLE
Framework: Merge into wp-calypso

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19852]
At the moment, the desktop app code is spread between core Calypso modules and configuration, and a separate repository with additional libraries and the electron build. We don't think this is a good setup, as it fragments the developer experience and adds friction. 

Building for the desktop app should be as easy as building for the different environments the web supports. The tooling we can create around a single repository can also be more coordinated and useful—imagine automatically generating a build for every pull request like calypso.live. Merging the codebase is also a chance at reducing some of the accumulated weight in desktop libraries that should be cleaned up and improved.

**Comment by spen** [comment]
If this gets picked up - feel free to talk to get in touch as I have some extra context on this and would be happy to help 👍
