### ISSUE TITLE
Framework: ESLint & Prettier

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19850]
Continue making progress in the consistency of the codebase's written style by automating as many menial tasks as possible. The less developers have to manually do to conform (and the less reviewers have to bring it up) the happier everyone can work.

**Comment by apeatling** [comment]
Calypso team: We can discuss this further down the line.

**Comment by sirreal** [comment]
We might close this as superseded by #24504 which tracks the remaining eslint fixes.
