### ISSUE TITLE
Framework: Testing Methodology

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#19883]
Make it easy and clear at what layer testing should occur in the different contexts.

**Comment by apeatling** [comment]
This should be in devdocs.

**Comment by alisterscott** [comment]
> This should be in devdocs. @alisterscott Can we reference e2e documentation in the Calypso repo somehow? 

Yes, we already do :)

https://github.com/Automattic/wp-calypso/blob/master/docs/testing/testing-overview.md#end-to-end-tests
