### ISSUE TITLE
Editor: Cannot drag images with Caption

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#1989]
If an image has a caption it can not be moved to a new location by dragging instead it must be copied and pasted which leads to #1988

![calypso_caption](https://cloud.githubusercontent.com/assets/150348/12027876/92b905b0-ad82-11e5-8dae-53e5a6ad19ed.gif)

**Comment by pento** [comment]
This is also a [bug in Core](https://core.trac.wordpress.org/ticket/40540).

**Comment by rachelmcr** [comment]
Closing as this will be resolved with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
