### ISSUE TITLE
Purchases: Update "My-Upgrades" references on Billing History page

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#199]
We need to update all "My Upgrades" copy and links:

![image](https://cloud.githubusercontent.com/assets/12596797/11276990/6794bf6c-8eb2-11e5-92f1-7fd635907fbf.png)

Including the "Manage upgrade" links:
![image](https://cloud.githubusercontent.com/assets/12596797/11277022/970613d6-8eb2-11e5-85bf-85eeda80cd03.png)

**Comment by matthusby** [comment]
I added this to #543 as I will fix both in one PR.
