### ISSUE TITLE
Domains: Add an icon and description for Transfer-In product on /me/purchases

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#19914]
On `/me/purchases` there is no icon for incoming domain transfers. On the product details there is no proper description provided like there is for other products. Just the domain name is not helpful.

Suggested description: `Transfers an existing domain from another provider to WordPress.com, helping you manage your site and domain in one place.`

![image](https://user-images.githubusercontent.com/448298/32902752-38a7eeac-cac1-11e7-9dca-b86377f354d6.png)

Domain Mapping | Domain Transfer
------------ | -------------
![image](https://user-images.githubusercontent.com/448298/32902985-dcf643c8-cac1-11e7-8ec4-4eec2f89a626.png) | ![image](https://user-images.githubusercontent.com/448298/32902976-d658b9ec-cac1-11e7-8189-27937527d98c.png)

#manual-testing

**Comment by mikeshelton1503** [comment]
Can we just call it "Domain Transfer", removing the "In"? It's an awkward and unnecessary article. We won't ever have a product call "Domain Transfer Out".
