### ISSUE TITLE
Notices: Refactor broke Domain Warnings

### ISSUE THREAD

**Issue by aidvu** [Automattic/wp-calypso#19910]
Introduced by https://github.com/Automattic/wp-calypso/pull/17796

#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/
2. Pick a site that has domains with "problems"
3. Notices in the sidebar broken
4. Go to Domains
5. Primary Domain notice broken in domains list

#### What I expected
To see properly aligned icons.

#### What happened instead
Misaligned icons.

#### Screenshot / Video
![broken notices](https://user-images.githubusercontent.com/1103398/32899244-baaafe2a-caea-11e7-9fbe-083122be34b1.png)

**Comment by jameskoster** [comment]
Plugins > Manage as well; 

![notices](https://cldup.com/1fbLRdFLjh-3000x3000.png)

**Comment by rachelmcr** [comment]
Notices are also broken in the editor:

![screenshot 2017-11-16 15 47 50](https://user-images.githubusercontent.com/8658164/32900539-97311e2a-cae5-11e7-90e4-2547454a108d.png)

**Comment by ryelle** [comment]
Looks to be misaligned on any compact notice, you can see it [here if you toggle the compact notice](https://wpcalypso.wordpress.com/devdocs/design/t) (the example name in devdocs also seems to be broken, defaulting to `t`)

**Comment by jameskoster** [comment]
Working on this now. Have a call in 5 minutes but hope to have a PR up for review ASAP.

**Comment by drw158** [comment]
I think this is fixed

**Comment by klimeryk** [comment]
Correct - thanks for the fix! 🙇
