### ISSUE TITLE
Customizer/Menus: header title disappears on hover

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#19915]
Title header in Menu section of Customizer disappears on hover.

#### Steps to reproduce
1. Open any site's Customizer
2. Select "Menus" option
3. Hover mouse over heading "You are customizing Menus"

#### What I expected
Text should still be readable.

#### What happened instead
Text changes to white, which is unreadable on white background.

#### Screenshot / Video
https://cloudup.com/czzYafcEkXT

#### Context / Source
It looks like this CSS code is why it happens:

```
#customize-controls .control-section .accordion-section-title:focus, #customize-controls .control-section .accordion-section-title:hover, #customize-controls .control-section .accordion-section-title:hover .menu-in-location {
    color: #fff !important; 
}
```

#manual-testing

**Comment by rachelmcr** [comment]
I tested and reproduced the issue in the Menus section as well as the Widgets section of the customizer. This CSS was added in r165516-wpcom in the Core 4.9 merge (cc @mermel).

**Comment by Piyopiyo-Kitsune** [comment]
I also found this issue for Menus while assisting a user on a Personal plan. Tested it on my free, Personal, Premium and Business WordPress.com sites and the issues still occurs on every theme's customizer(tested 2011-2017, Photo Blog and Sequential)

**Comment by lancewillett** [comment]
Closing this bug as Customizer isn't part of Calypso.
