### ISSUE TITLE
Store: Edit Order - Unable to edit order with item costing $0.00

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#19913]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/store/orders/example.wordpress.com
2. Select an order
3. Click the Edit Order button
4. Add an item costing $0.00
5. Click Save Order

#### What I expected
The order to save

#### What happened instead
I get `Unable to save order.`  No console errors, but I do see a response from the API with `{error: "rest_invalid_param", message: "Invalid parameter(s): line_items"}`

If you already have an item costing $0.00 on the order, you can't make any other changes (such as status) to the order either.

Note also that when the free item is added to the order, the Total Price disappears

#### Browser / OS version
Linux Chrome v61

#### Screenshot
![wp-calypso-store-edit-order-free-item-edit](https://user-images.githubusercontent.com/7233112/32900147-c4476084-caba-11e7-83f8-688107df71b6.gif)

#### Context / Source
#manual-testing

**Comment by ryelle** [comment]
@hoverduck I think you got caught in an API bug that affected order saving, so the issue you're having here _should_ be resolved (now that #20018 has been merged). Can you re-test this?

**Comment by ryelle** [comment]
Closing this because I can't replicate it, and I'm pretty sure the original cause was the now-fixed API issue.
