### ISSUE TITLE
Components: Action in notices are hard to... notice (ha-ha, get it?)

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#19926]
Is it just me or did the changes in https://github.com/Automattic/wp-calypso/pull/17796 actually decrease the contrast and readability of actions in notices?

Before:
<img width="648" alt="screen shot 2017-11-16 at 17 24 05" src="https://user-images.githubusercontent.com/3392497/32902554-f9e1ee34-caf2-11e7-9e1c-53920b41b54e.png">

After:
<img width="648" alt="screen shot 2017-11-16 at 17 20 53" src="https://user-images.githubusercontent.com/3392497/32902561-feae4002-caf2-11e7-8a4c-cd8deac33ddc.png">

If I did not know better, I would not know that there are clickable actions in the new notices :/

The more subdued color of the action along with no change in the background for them makes all the less discoverable, it seems.

**Comment by shaunandrews** [comment]
- I find these new notices very masculine and "heavy," and (contradicting myself) they also seem to "fade away" into the rest of the screen.
- I agree that the actions (which are usually pretty important) are less noticeable, and not easy to read.
- I find the reversed light-on-dark text for the messaging hard to read as well — its almost as if the pure white text is "vibrating" on the dark background.

**Comment by drw158** [comment]
It can be closed. We are redesigning these notices in the next few months or so.

**Comment by klimeryk** [comment]
Awesome, thanks for the update! 👍
