### ISSUE TITLE
Domains: Incoming Transfers pre-check says privacy is disabled but it's not

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#19920]
On the pre-check screen of the incoming transfers flow, it tells me privacy is disabled even though it's not.

<img width="718" alt="screen shot 2017-11-16 at 12 57 32" src="https://user-images.githubusercontent.com/448298/32907407-e92d9676-cacd-11e7-86f6-d0c44107202f.png">

If we don't have reliable checks for the email address we should always display the heading as `Disable privacy protection.` and show the `Don't recognize that address? Then you have privacy protection enabled...` message.

#manual-testing

**Comment by aidvu** [comment]
We can't reliably determine it. We can guess by the e-mail, but that's the best we can do.

**Comment by danhauk** [comment]
If we can't reliably determine it then we should have generic copy there.

@wensco mentioned in Slack that this step really isn't about privacy protection, but more about verifying they have access to the email address. It's possible privacy protection is disabled but they still don't have access to the address.

With that in mind I took a shot at tweaking the copy in #19949 to focus on making sure they can access the email address. `Turn it off` in the copy below links to a support doc about how to turn off privacy.

> **Verify we can get in touch.**
> We'll send an email to %(email)s to start the transfer process. Make sure you have access to that address. Don't recognize it? Then you probably have privacy protection enabled. You'll need to log in to your current domain provider and <a href="#">turn it off</a> before we start. Don't worry, you can re-enable it once the transfer is done.

**Comment by danhauk** [comment]
Copy updated in #19949 to the more generic version above.
