### ISSUE TITLE
Comments: wrong position of user info box

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#19927]
#### Steps to reproduce

1. Starting at URL: `/comments/all/`
2. Make sure that you use a test site with multiple comments.
3. Click on user info of first comment, then second comment.
4. Repeat step 3 once again.
4. Notice that the position of user info box is not next to the button, but shifted up instead.

#### Browser / OS version

Chrome  61.0.3163.91/ Ubuntu 16.04 LTS

**Comment by designsimply** [comment]
Tested and confirmed the user info box in comments is sometimes shifted in weird ways.

<strong>Video:</strong> [30s](https://cloudup.com/ceOHjBnNaHH)

![screen shot 2017-11-16 at thu nov 16 7 00 40 pm](https://user-images.githubusercontent.com/1119271/32925752-c0fa4892-cb00-11e7-9da4-184e970fb257.png)
<sup>Seen at https://wordpress.com/comments/all/design5279.wordpress.com?page=1 on staging using Firefox 57.0 on Mac OS X 10.12.6 logged in as a regular user and proxied.</sup>

**Comment by vindl** [comment]
Seems to be resolved in https://github.com/Automattic/wp-calypso/pull/19992.
