### ISSUE TITLE
Store: Fulfillment notification card is not correctly aligned in MS Edge

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#19922]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/store/order/:siteurl/:orderid
2. Open any not fulfilled order

#### What I expected

Fulfillment notification card has the same width as other cards

#### Browser / OS version

Win10 / MSEdge 41

#### Screenshot / Video
<img width="1315" alt="msedge - win10 layout issue" src="https://user-images.githubusercontent.com/5654161/32908359-f743a636-cb0b-11e7-8dec-c31453102693.png">

**Comment by justinshreve** [comment]
It looks like this is no longer an issue. I tested with Win10 / Edge 41.

I think we probably fixed this when we made everything full width.
