### ISSUE TITLE
Editor: notices look visually broken

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#19930]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post/
2. publish a post
3. notice the success message
4.

#### What happened 

Notices in the editor look broken since #17796 

![screen shot 2017-11-16 at 2 56 33 pm](https://user-images.githubusercontent.com/618551/32915401-5b138c2c-cade-11e7-82c1-cab46da8280e.png)

Normally, looks like this:

![screen shot 2017-11-16 at 2 54 39 pm](https://user-images.githubusercontent.com/618551/32915418-69bf6eda-cade-11e7-8879-6ec34f0cc3c5.png)

Seems that the editor has a bunch of custom styles applied to the notices. I quickly just removed a bunch of the custom css and got it to look like this:

![screen shot 2017-11-16 at 2 59 34 pm](https://user-images.githubusercontent.com/618551/32915521-c9c0f222-cade-11e7-8d09-d307b7feeff5.png)
@jameskoster

**Comment by jameskoster** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/19924
