### ISSUE TITLE
Domains: domain available on Transfer screen looks bad

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#19933]
On the transfer screen where you enter the domain, if you enter a domain that's available for registration we show a notice. It looks pretty bad.

<img width="750" alt="screen shot 2017-11-16 at 16 30 57" src="https://user-images.githubusercontent.com/448298/32917015-d7649ab6-caeb-11e7-9ac5-686f55f093cd.png">

#### Steps to reproduce
1. Start at `/domains/add/transfer` and select a site.
2. Enter a domain that's available for registration.
3. View the hot mess that is the notice.

#manual-testing

**Comment by klimeryk** [comment]
Related: https://github.com/Automattic/wp-calypso/pull/19924#pullrequestreview-77264208
It's not only for transfers in, but for all cases - after https://github.com/Automattic/wp-calypso/pull/17796 was merged.

**Comment by klimeryk** [comment]
Closing this one as we don't have the resource to tackle this, nor is it a priority.
