### ISSUE TITLE
Domain Transfers: Improve hierarchy of domain transfer list

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#19942]
The domain transfer list is lacking hierarchy, making it hard to focus  on a starting point.

![image](https://user-images.githubusercontent.com/12596797/32924418-892ead4a-cb0a-11e7-83b8-2aa48f41c735.png)

**Comment by mikeshelton1503** [comment]
In the i2 designs (not yet implemented) there is clear headline and subtitle separate of the steps:
![image](https://user-images.githubusercontent.com/12596797/32924474-d16c9b8a-cb0a-11e7-9d84-1a285e6dff5d.png)

**Comment by danhauk** [comment]
This has been fixed with #19949
