### ISSUE TITLE
Domain Transfers: Remove sidebar and header

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#19943]
Per the i2 designs the transfer flow should be an isolated flow without the sidebar:

Current: 
![image](https://user-images.githubusercontent.com/12596797/32924651-a9d54c92-cb0b-11e7-8d0e-135e2ed47a8a.png)

Proposed design:
![image](https://user-images.githubusercontent.com/12596797/32924665-bb4432e0-cb0b-11e7-9db8-c53b8d4d6ef4.png)

**Comment by danhauk** [comment]
Now that we're killing the second step (checkbox options) do you think we still need the isolated view for existing sites? I think it would be a lot of jumping between layouts for just one screen.

**Comment by mikeshelton1503** [comment]
Agreed. We can revisit the layout if add that step back in later. Closing cc @aidvu you're off the hook removing the sidebar 😄
