### ISSUE TITLE
Reader: mobile post view is missing back button

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#19948]
#### Steps to reproduce
1. Starting at URL: Any post (eg. https://wordpress.com/read/feeds/52445727/posts/1667554040) on mobile width

#### What I expected

To see a back button (and header stuff)

#### What happened instead

No back button or header stuff, now see calypo toolbar

#### Browser / OS version

Any browser sized down to mobile width

#### Screenshot / Video

Currently

<img width="584" alt="screen shot 2017-11-17 at 2 13 34 pm" src="https://user-images.githubusercontent.com/128826/32929200-0c113df8-cba2-11e7-84bf-4a1045cc8ab6.png">

Previously

<img width="474" alt="screen shot 2017-11-17 at 2 16 15 pm" src="https://user-images.githubusercontent.com/128826/32929205-1412498e-cba2-11e7-9906-f46d443a1428.png">

#### Context / Source
#dogfooding

**Comment by samouri** [comment]
Thanks for the report @alisterscott!

This definitely wasn't intentional.

I don't believe we ever showed the back button when landing on a full-post page (what would you go back to?), but I've confirmed that I don't see a back button even when getting to a fp by clicking on a post in a stream.

**Comment by alisterscott** [comment]
> I don't believe we ever showed the back button when landing on a full-post page (what would you go back to?)

Yes, sorry about that. And yes it was there coming in from the reader stream or somewhere else (comments maybe), and the header looks entirely different now also as per the screenshots.
