### ISSUE TITLE
Domain Transfers: Update transfer notice copy

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#19946]
The Incoming Transfer notice that displays after we send you the confirm email need to be updated.

Right after purchase before it has been confirmed we should show this notice:
> We sent an email to XX_email_address_XX to confirm the transfer of XX_domain_XX. More info

After the transfer has been confirmed we should display this notice:
> The transfer of mikeshelton.me is in progress. We are waiting for authorization from your current domain provider to proceed. Learn more

**Comment by danhauk** [comment]
There's also the notice when pending confirmation on the domain edit screen.

<img width="734" alt="screen shot 2017-11-27 at 16 09 24" src="https://user-images.githubusercontent.com/448298/33289417-7ce132de-d38d-11e7-97c2-3e91c27df587.png">

The email they're looking for isn't necessarily about verifying the email address. It's really about confirming the transfer and entering the EPP auth code. What about something like this:

> Important: Confirm the transfer to proceed.
> We sent an email to confirm the transfer of example.com. Open the email, click the link, and enter your domain authorization code to start the process. Please confirm in 5 days or the transfer will be canceled.

![image](https://user-images.githubusercontent.com/448298/33289914-0fac0ce6-d38f-11e7-8bac-ff9bff5243a6.png)

**Comment by danhauk** [comment]
One more notice that should be updated is if a transfer is in progress but someone searches for it. This is the current state:

![image](https://user-images.githubusercontent.com/448298/33290836-f4b2334a-d391-11e7-9cbd-de4d585f8215.png)

Preventing mapping on in-progress transfers is currently being implemented, and we should have a meaningful message here. But I'm not sure the best messaging.

@aidvu What will we be able to check here? Could we show a contextual message if the domain is being transferred to a site the current user owns and a general message to all other users?

**Comment by aidvu** [comment]
Fixing the `confirm transfer` one in https://github.com/Automattic/wp-calypso/pull/20206.

Have a task for showing e-mail in notice, and will make a separate PR for the last one.

**Comment by danhauk** [comment]
Preventing mapping/transfer on an in-progress transfer is being fixed in #20296.

**Comment by danhauk** [comment]
Closing this since we've updated notices.
