### ISSUE TITLE
Domain Transfers: Add domain and Change Primary buttons disappear 

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#19947]
I noticed after I had purchased my domain transfer, but not confirmed my email yet that the "Add Domain" and "Change Primary" buttons disappeared.

![image](https://user-images.githubusercontent.com/12596797/32928663-168a2140-cb21-11e7-869a-9958e19388c4.png)

In checking with @danhauk to confirm the issue, he didn't have the same issue however I noticed in his case the domain that was being transferred wasn't set to primary unlike mine.

![image](https://user-images.githubusercontent.com/12596797/32928684-3e0264d0-cb21-11e7-9d5c-146d6a81368c.png)

**Comment by aidvu** [comment]
I've tried to reproduce but w/o any luck... From what I'm seeing, there is no primary domain, and it's unrelated to this.

I've disabled setting transfers as primary anyway.
