### ISSUE TITLE
Domain Transfers: Not clear how to unlock your domain

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#19945]
In the domains transfer list the unlock domain step doesn't provide any guidance on how to do that. We say "You'll need to unlock the domain at your current registrar before we can move it." but don't explain who or what a registrar is.

In the i2 designs we planned to solve this by determining who the registrar is and stating it. This is the ideal solution.

![image](https://user-images.githubusercontent.com/12596797/32926569-f4a9e8cc-cb15-11e7-8ffe-4bc543e1a40b.png)

However, if that isn't feasible or reliable, we need to improve the copy we have now to be more helpful about how to unlock your domain.

cc @aidvu

**Comment by danhauk** [comment]
In #19949 I've made some slight tweaks to the generic copy:

`Your domain is locked to prevent unauthorized transfers. You'll need to unlock it at your current domain provider before we can move it. <a>Here are instructions for unlocking it.</a>`

Note that the link will go to a support doc about unlocking the domain with a list of links out to popular registrars' specific instructions. Though I'm not sure that's any clearer. Maybe we should explicitly state to log into your current domain provider and unlock it?

**Comment by mikeshelton1503** [comment]
The instructions link is an improvement for sure but more of a band-aid. I'd agree with being more explicit.

@aidvu Can you weigh in here on the feasibility and effort needed to programmatically determine the registrar? 

If it's hard to reliably determine this, perhaps we just do it for the major ones like GoDaddy (which makes up over 50% of domains currently mapped to us) and have generic copy liek above for th rest.

**Comment by aidvu** [comment]
Maybe a bit easier than privacy, but still hardish. 

Registrars have a field in the `whois`:
```Registrar IANA ID: 81```

Problem is, there are quite a few, and even the big ones like GoDaddy have subsidiaries and might be using multiple registrars. :)

@kelliepeterson whatcha think?

**Comment by aidvu** [comment]
@kelliepeterson, did you see https://github.com/Automattic/wp-calypso/issues/19945#issuecomment-345376544?

**Comment by kelliepeterson** [comment]
In theory, I like the idea of providing the information, but it can often cause as much confusion as not displaying it, as in the cases @aidvu mentions, but also in cases where a domain retailer is a reseller of Tucows, eNom, Hexonet, etc. Also in the cases where the IANA/ICANN name of a registrar is vastly different than the name a consumer might be familiar with as is the case with Hexonet, which is known at IANA as 1API. 

I would opt for the explainer text that @danhauk suggests https://github.com/Automattic/wp-calypso/issues/19945#issuecomment-345315804

**Comment by danhauk** [comment]
Closing this. We went the more generic copy mentioned above rather than introducing potential confusion with naming a registrar that might not be 100% accurate.
