### ISSUE TITLE
Comments: Improve "comment has link" icon clarity

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#19974]
Currently, when a comment contains links, we just show a link icon near the comment author name.
This doesn't make much sense though, as it's not immediately clear what that icon is.

We should add some clues on it.
A tooltip, for example, and maybe moving it into a position more related to the comment content than the comment author.

cc @drw158 

Props to @rachelmcr for finding this!

**Comment by drw158** [comment]
I think a tooltip would be good. Perhaps it's not as important now that all comments are expanded.

**Comment by Copons** [comment]
I think it's still a valid icon for power moderators that look for comments containing links.
Though, let's add the tooltip and see how it works out. 👍
