### ISSUE TITLE
Comments: Add a link to the post in the Reader

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#19970]
With the addition of the post view, a comment's Post Title doesn't link to the Reader anymore.
Now, the only way to open a post is to navigate from the site view to the post view and from there click on "View Post" in the header.

Maybe it's worth having a link to the post directly in the comment card?

Context: p58i-6Lh-p2 (comment-37121, point 3)

cc @drw158

**Comment by drw158** [comment]
I think this is probably ok, but open to other perspectives. For this issue, do you mind linking to the p2 comment this came from?

**Comment by Copons** [comment]
Link added, although it's kind of a mouthful. 😄

**Comment by drw158** [comment]
Thanks! In my opinion, there isn't a need to link directly to a post from the main comment view. Once you are in the single post view, the 'view post' link could be more clear though.

**Comment by gwwar** [comment]
going to close this out, let me know if folks still want this / want needs to be done
