### ISSUE TITLE
Accessibility: Keyboard Only: Better visible `:focus` styles on Show advanced status details button in sidebar

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#1997]
This issue has been split out from: https://github.com/Automattic/wp-calypso/issues/697

Better visible `:focus` styles on Show advanced status details button in sidebar.

**Comment by rachelmcr** [comment]
Confirmed that this is still an issue in the editor sidebar.

#bug-scrub #pre-gutenburg-bug-purge
