### ISSUE TITLE
Comments: the Back button has erratic behaviours

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#19971]
@rachelmcr reported:
> On mobile, I noticed a difference between using that Calypso “Back” button and using my browser’s back button. Using the browser back button, I had to tap twice to get back to the full comment list and when I got there I was faced with a blank page.
> 
> When I started scrolling, the comments appeared on screen. Not sure if we can prevent that blank screen in cases like this, but it’d be nice!

**Comment by mattsherman** [comment]
Relatedly, if the user has arrived at the comments screen for a particular post by clicking on the comments icon in the post list, I would expect clicking the Back button to bring the user back to the post list.
