### ISSUE TITLE
Reader: after moderating comment, pending comment display is incorrect

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#19989]
This one is a bit subtle, but it looks like we are displaying pending comments from other users in prod under certain circumstances:

1. Make sure your post has comments from users other than yourself
2. In /comments, unapprove a comment from another user
3. _Without_ a hard refresh, visit the post in the reader
Expected: We only see our pending comments
Actual: We see all pending comments, with mismatching pending text when the user isn't yourself.

![screen shot 2017-11-17 at 1 17 43 pm](https://user-images.githubusercontent.com/1270189/32969561-71cba3ac-cb9a-11e7-9484-5729ed7a890d.png)

**Comment by gwwar** [comment]
Without digging into the code, I'm guessing that we must populate more comments in the management section than reader does, but the reader assumes that any pending comment belongs to you

**Comment by kwight** [comment]
> Without a hard refresh, visit the post in the reader

Maybe I'm misunderstanding, but I don't think this is valid any more, now that the post link goes to a comments post-view. I don't see any other way to go the post view in the Reader, without entering the direct URL (a full refresh).
