### ISSUE TITLE
Accessibility: Keyboard Only: Improve tab ordering for editor

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#1998]
This issue has been split out from: https://github.com/Automattic/wp-calypso/issues/697

I have similar [confusion as this user](https://horizonfeedback.wordpress.com/2015/09/14/call-for-testing-editor/comment-page-1/#comment-144) when using the keyboard alone:

**Comment by rachelmcr** [comment]
This tab ordering could still be improved. It has changed somewhat since the feedback given in the original issue, but it is still confusing.

#bug-scrub #pre-gutenburg-bug-purge
