### ISSUE TITLE
Site Picker: All Sites: Improve Icon Composite

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#2]
The current icon-composite used to represent all-sites could be improved.

Current: 

![original](https://cloud.githubusercontent.com/assets/128826/11198189/8d510896-8d0e-11e5-8152-9efcebf676b9.png)

Proposed by @mtias 

![proposed](https://cloud.githubusercontent.com/assets/128826/11198196/a6509b86-8d0e-11e5-96cf-9cff225c025b.png)

**Comment by jasmussen** [comment]
I like all the proposals here far more than the current one..

But it also shows some of the challenges we have. Sites have square avatars, people have circle avatars. That means if the squares are right next to each other, they might as well be one big blavatar. On the other hand at the small size here, we need all the pixels we can get. 

To be clear: I think all of these are good. The following are just mockups to explore further.

![v1](https://cloud.githubusercontent.com/assets/1204802/11850975/9f123224-a430-11e5-99b6-09de3ad93ce1.png)

![v2](https://cloud.githubusercontent.com/assets/1204802/11850981/a3996f9c-a430-11e5-8b95-dab17d1249d2.png)

![v3](https://cloud.githubusercontent.com/assets/1204802/11850986/a89a3350-a430-11e5-980f-34f2dcb3f925.png)

![v4](https://cloud.githubusercontent.com/assets/1204802/11850991/aca7a626-a430-11e5-9255-b66310520934.png)

![v5](https://cloud.githubusercontent.com/assets/1204802/11851003/b40654ee-a430-11e5-8265-dc307082e4bf.png)

![v6](https://cloud.githubusercontent.com/assets/1204802/11851007/b93c6c8c-a430-11e5-86d0-8c58bd9a7787.png)

![v7](https://cloud.githubusercontent.com/assets/1204802/11851014/bea1c442-a430-11e5-82ee-011b581edadc.png)

![v8](https://cloud.githubusercontent.com/assets/1204802/11851020/c29415fa-a430-11e5-9665-367c4190a078.png)

Like I mentioned, the circles while cool looking probably won't work as sites are square.

**Comment by mtias** [comment]
@jasmussen we have the count on the right of the component these days. Maybe we can explore just using the icon grid on the left?

![image](https://cloud.githubusercontent.com/assets/548849/12730782/d2ccc1ca-c92d-11e5-8422-a5ed28969434.png)

**Comment by jasmussen** [comment]
> Maybe we can explore just using the icon grid on the left?

That certainly makes things easier. In that case I think either 4 circles, 4 squares, or 3 stacked diagonal blavatars would work just fine. I have a slight 4 squares preference simply because blavatars are square.

**Comment by mtias** [comment]
> I have a slight 4 squares preference simply because blavatars are square.

Yes, I think we should stick to this.

**Comment by mtias** [comment]
@jasmussen 4 icons no gaps sounds good?

**Comment by jasmussen** [comment]
> @jasmussen 4 icons no gaps sounds good?

Yep, I think that's the pragmatic choice for the foreseeable future! :+1:

**Comment by alisterscott** [comment]
I'm doing a bug scrub, currently All Sites looks like this:

![screen shot 2016-06-03 at 8 43 33 am](https://cloud.githubusercontent.com/assets/128826/15764061/51998162-296b-11e6-99f0-6f526a20a12a.png)

Are we okay with it for now? Can I close this issue?
