### ISSUE TITLE
Editor: History: Move History button next to Save/Saving/Saved Button

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#20001]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post/
2. Create a draft and click save, add more content and click save again

#### What I expected

History link to appear next to the save button

#### What happened instead

History link takes the place of the Save link and moves the Save link across

#### Browser / OS version

All browsers

#### Screenshot / Video

![location](https://user-images.githubusercontent.com/128826/32999087-e0172ec8-cdeb-11e7-90fd-167445db938f.gif)

#### Context / Source
#manual-testing,

**Comment by alisterscott** [comment]
Attempted fix in #20002

**Comment by frontdevde** [comment]
Quoting the previous discussion for continuity
> [...] the positioning is actually on purpose. We swapped the position of Save and History around as the Save button has three different states (Save, Saving…, Saved) that vary in size. If the History button would be on the right, whenever an (auto)save would occur, the History button would jump in the UI. We did think about giving the Save button the size of the longest of the three states but this introduces a weird gap between the two buttons (especially in some languages like e.g. German). Wondering if maybe we should make the History button always visible and just deactivate it instead of hiding it. It could look similar to the Saved state of the save button.

**Comment by alisterscott** [comment]
Closing as works as designed
