### ISSUE TITLE
Editor: History: Doesn't show in Safari until you click the cancel button

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#20000]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post/
2. Enter some content and click save, enter some more content and click save until "History" appears next to save
3. Click "History"

#### What I expected

To see revisions

#### What happened instead

Revisions are blank until you click cancel. You can click cancel and cancel clicking to show the revisions. Upon re-entry the list of revisions appears but not the changes.

#### Browser / OS version

Safari Version 11.0.1 (13604.3.5) on macOS 10.13.1 - Also tried Safari on iOS (landscape mode) and it also showed the same thing

#### Screenshot / Video

![safari history](https://user-images.githubusercontent.com/128826/32998415-97f1469c-cde6-11e7-85ef-217fc347eb43.gif)

![safari ios - 1](https://user-images.githubusercontent.com/128826/32998531-b6067462-cde7-11e7-824e-282c307ac3f7.jpg)

#### Context / Source
 #manual-testing

**Comment by jblz** [comment]
This should be fixed by #20069 -- please feel free to reopen if not!

**Comment by frontdevde** [comment]
We had to revert the fix https://github.com/Automattic/wp-calypso/pull/20185 due to a side effect. Reopening issue for now.

**Comment by alisterscott** [comment]
Thanks for the fix @frontdevde 👍
