### ISSUE TITLE
Popover component: vertical site scroll moves the popovers into top/bottom bars

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#20014]
#### Steps to reproduce
(Most likely) all popovers exhibit this behavior, so can be tested on any site containing those. 

Example on the Plans page:
1. Starting at URL: `https://wordpress.com/plans/:site`
2. scroll up/down with a popover open

#### What I expected
Popover to close when reaching the limits of site view

#### What happened instead
Popover overlays the top/bottom margins and stays visible outside of the site view ( visible with bottom margin )

#### Browser / OS version
Firefox, Chrome / macOS Sierra

#### Screenshot / Video
Plans page, scrolling down:

![screen shot 2017-11-19 at 23 13 50](https://user-images.githubusercontent.com/13561163/33024905-b15bc58c-ce0c-11e7-8e2d-a4ca989f2356.png)
![screen shot 2017-11-19 at 23 14 01](https://user-images.githubusercontent.com/13561163/33024904-b12e6df8-ce0c-11e7-93e1-790f98f0be05.png)

#### Context / Source

Found when working on removing another odd Popover behavior in https://github.com/Automattic/wp-calypso/pull/19992.

**UPDATE**
The same limit problem occurs when decreasing the browser window size to reach small viewport
(with a popover open)
 
![screen shot 2017-11-20 at 16 23 11](https://user-images.githubusercontent.com/13561163/33025851-55c5640a-ce0f-11e7-8019-3b0759850e5c.png)

I add this case here because it looks like an overall problem with CSS selectors for the `domContext` of the Popover component and those issues can be fixed together.

**Comment by Copons** [comment]
Hi @AnnaMag!
We're having Popover positioning issues in the Comments Management section (see #19927).

There are steps and a video in there. When you have a bit of spare time, could you please confirm it's related to this issue and the previously merged changes?
Thanks!

**Comment by AnnaMag** [comment]
@Copons, #19927 is closed. Is it still relevant?
I haven't gone through the steps, but my strong guess is that #19992 fixed it. Let me know if it is not the case ( that would be odd 🤔 ).
The issue mentioned here is different- it happens when you open a popover and scroll up/down till it reaches the end of the page OR with a popover open decrease the browser window. It is most likely to affect all places where the Popover component is used, including Comments Management section. So you might want to double-check this happens for you and if you open an issue, please link it here. If nobody else grabs this issue before, I take a stab at fixing it this month. 

Hope it is helpful!

**Comment by Copons** [comment]
Got it, thanks @AnnaMag.
I'll investigate deeper and will file an issue if my findings are issue-worthy. 🙂
