### ISSUE TITLE
Accessibility: Add aria-checked attributes to radio elements in editor

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#2002]
This issue has been split out from: https://github.com/Automattic/wp-calypso/issues/697

The links for the Visual and HTML tabs of the Editor that have `role=radio` need a `aria-checked="false"` or `aria-checked="true"` depending on their state. That may be a Core issue with TinyMCE.

**Comment by rachelmcr** [comment]
Closing as this is related to TinyMCE and won't be an issue with how Gutenberg handles Visual/HTML switching.

#bug-scrub #pre-gutenburg-bug-purge
