### ISSUE TITLE
Editor: HTML added to content of code-shortcode when switching editors

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#20039]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. In the visual editor, use the [code] shortcode and add some content. Make sure the content includes a less-than `<` symbol. The content doesn't have to be code
3. Switch from visual to HTML, and then switch back.
4. Try this a few times

#### What I expected
For the content of the shortcode to remain unchanged.

#### What happened instead
A span-tag was added to the code: `<span data-mce-type="bookmark" id="mce_SELREST_start" data-mce-style="overflow:hidden;line-height:0" style="overflow:hidden;line-height:0" >&#65279;</span>`

Repeatedly switching back and forth causes the HTML to be added multiple times. If the < symbol is left out this does not happen. Substituting the symbol for the html entity, `&lt;`, makes no difference - the HTML still gets added.

In the original user report only some line breaks were initially removed at switching editors, but on repeatedly switching editors I observed the HTML being added to the user's code as well.

I am not able to replicate this behaviour in the WP-Admin editor.

#### Browser / OS version
Browser does not appear relevant, but confirmed in Chrome and Firefox on Mac OS 10.12.6 and the user who reported it experienced it in Firefox on Windows (version not provided).

#### Screenshot / Video
![code](https://user-images.githubusercontent.com/11873759/33055833-bd193f7a-ce8a-11e7-9951-a10f2f3f634a.gif)

#### Context / Source

Reported via the public forums in 884183-f

**Comment by emilyplusplus** [comment]
this is still an issue, any fixes???

**Comment by adamleone** [comment]
Hello there, 

A similar issue has cropped up with this ticket here: https://woothemes.zendesk.com/agent/tickets/1403757

Advised to use wp-admin view to use shortcode for the time being

**Comment by adamleone** [comment]
Hello there,

A similar issue has cropped up with this ticket here: zen-1403757

Advised to use wp-admin view to use shortcode for the time being

**Comment by KristinaKay** [comment]
> Hello there,
> 
> A similar issue has cropped up with this ticket here: zen-1403757
> 
> Advised to use wp-admin view to use shortcode for the time being

Using WP-Admin, in this case, does not help.

Ussing [code][/code] and Markdown for code in both Calypso (HTML Editor) and in WP-Admin doesn't work. The < >’s are being turned into `&lt;` and `&gt;`.  

I was able to reproduce this in both Calypso and in WP-Admin.

```The key insight here, and it took me a while to see it, is that the roll angle we want is the angle between the two rods in that picture. To rotate to that angle, we want the `rotation` between those two rods. If the given normal in the input data is in the variable `norm`, then we want `llRotBetween(<0,1,0>,norm)`. Why? Because the y-face normal of the transparent cube is `<0,1,0>`, because it sticks straight out in the Y direction.```

When publishing it returns this:

![image](http://cld.wthms.co/2VSpIr+)

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/DebShadovitz/status/1059224959669678081).

**Comment by WPprodigy** [comment]
Similar: https://core.trac.wordpress.org/ticket/45947

**Comment by jordesign** [comment]
This also sounds similar to this trac ticket - https://core.trac.wordpress.org/ticket/42908

and to this open Issue: https://github.com/Automattic/wp-calypso/issues/26140

**Comment by KokkieH** [comment]
Had another report in https://en.forums.wordpress.com/topic/why-not-wrapping-sql-code-in-my-this-post/

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
