### ISSUE TITLE
Comments: M4 performance profiling

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#20030]
- [x] Let's do a profiling pass to make sure that we're not rendering Comment components unnecessarily 
(https://github.com/Automattic/wp-calypso/pull/20098)
- [ ] Verify that a comments-tree call on a large site >150k comments is not prohibitively slow. 

Also see: https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab

We can profile in Chrome or FF using the timeline:
https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference
https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler
- List clear steps that you take to trigger client load
- Provide the timeline dump if possible for other people to inspect
- See https://github.com/Automattic/wp-calypso/pull/10836#issuecomment-274628155 as an example

**Comment by vindl** [comment]
@Copons already started a PR to address the first point: https://github.com/Automattic/wp-calypso/pull/20098

**Comment by Copons** [comment]
Sorry for not giving a heads up, I missed this issue. :(

**Comment by gwwar** [comment]
Note that folks are still seeing slow script warnings in FF.

**Comment by apeatling** [comment]
I left a comment on the project master thread that has a video showing some of the areas that feel sluggish when using the current iteration.

**Comment by Copons** [comment]
I think that sluggishness is caused by too many network requests.

We have an issue for the comments tree response caching, which might help us here: https://github.com/Automattic/wp-calypso/issues/19045

But we might actually need to add a new "freshness" behaviour on the `QueryComment` component.

**Comment by supernovia** [comment]
Noting a user complaint [here](https://en.forums.wordpress.com/topic/disgusting-wordpress-new-comment-edition-mode?replies=12).

**Comment by gwwar** [comment]
Thanks @supernovia!

**Comment by Copons** [comment]
@supernovia Thanks for reporting!
I'll make sure to read it all first thing tomorrow, but meanwhile you can tell them that the comments section is in active development and we're working on it as we speak. 🙇

**Comment by gwwar** [comment]
With #21155 in, I think we can close this out for now.
