### ISSUE TITLE
Access to plans (Personal, Premium, Business) for contribution purposes

### ISSUE THREAD

**Issue by dinarAkv** [Automattic/wp-calypso#20042]
Wordpress has different functionality that I can get only if I purchase different plans like "Personal", "Premium", "Business". 

Can I get this plans for free, for contribution purposes ?
For example to test new functionality, to fix bugs.

**Comment by designsimply** [comment]
That is not something we have traditionally offered. In the interest of making sure to give the request consideration, may I ask for some specific examples of things you would like to work on and may I ask if you are able and willing to make other contributions without needing access to plans as a first step? I see that you have filed a few issues here in the `wp-calypso` repository so far but that you [have not yet submitted any PRs](https://github.com/Automattic/wp-calypso/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AdinarAkv+created%3A%3C%3D2017-12-12).

**Comment by designsimply** [comment]
@dinarAkv I asked about #19959 and was told that it is some respectable sleuthing. Nice! 🙂

I would like to offer to add you to some test sites with plans active so that you can use those for contribution purposes. Can you please verify your WordPress.com username for me?

**Comment by designsimply** [comment]
Closing this since it has been over a month without a reply. Please re-open if you get to a point again where you would like access to WordPress.com plans for testing purposes and we'll revisit at that time. Thank you!
