### ISSUE TITLE
Accessibility: Provide non-visual indicators for auto-save

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#2005]
This issue has been split out from: https://github.com/Automattic/wp-calypso/issues/697

Auto-saving is not indicated to a visually impaired person, and  after auto-save there is no longer a "save" button. So the author only gets a "publish" button, and they probably are unaware it has already been saved. @rralian brought this up. We could solve this by using `aria-live` to communicate to assistive technology when a post/page is saved. See this [example](http://heydonworks.com/practical_aria_examples/#offline-alert).

**Comment by SiobhyB** [comment]
@rralian @davidakennedy: Can you take a look over my understanding of the issue to make sure I'm on the right track?

My understanding:

- The Publish module is updated to notify users of the last time a post was saved. When a post has been saved, the link to "save" isn't displayed as it's not necessary.
- VoiceOver, and other screen readers, don't notify users of changes to text within HTML elements.  
- As a result, VoiceOver users have no way to know the last time a post was saved and don't see any way to save their changes.

<img width="1081" alt="screen shot 2016-04-26 at 16 29 01" src="https://cloud.githubusercontent.com/assets/2998162/14824004/52681156-0bcc-11e6-833b-4660f92ce17d.png">

- Adding `role="alert" aria-live="assertive"` to the HTML button would update VoiceOver users when a post is saved.

**Comment by lancewillett** [comment]
Pull request is still valid, but needs feedback and testing.
