### ISSUE TITLE
Accessibility: Add feedback for selecting different site for new post

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#2006]
This issue has been split out from: https://github.com/Automattic/wp-calypso/issues/697

When already on the Editor page, clicking "New Post" and selecting a different site from the site-picker via keyboard controls will update the url, but there is no feedback and the site-picker remains open. @rralian brought this up too.

**Comment by marekhrabe** [comment]
I'll work on proper keyboard accessibility of that picker and make it close on select.

> …but there is no feedback…

Do you have any other feedback in mind that we can implement, besides closing the picker, changing the URL and changing site name with avatar in the left sidebar?

**Comment by marekhrabe** [comment]
As there is no reaction, I would opt for closing this. The feedback looks good to me as is unless I misunderstood the issue.

cc @alisterscott

**Comment by alisterscott** [comment]
This no longer appears to be an issue. Closing.
