### ISSUE TITLE
Reader Intro Box: IE11 overflow bug

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#20071]
#### Steps to reproduce
1. In IE11, navigate to the Reader as a new user. (https://wordpress.com)
2. The text in the intro box isn't wrapping.

#### Screenshot / Video
![ie11-intro-box](https://user-images.githubusercontent.com/942359/33086109-b1ab7728-ceb4-11e7-9662-c4e52c886e68.png)

**Comment by designsimply** [comment]
Tested and confirmed that the welcome message falls over outside of it's container using IE11 on Windows 10. I also tested with Edge 16 on Windows 10 via BrowserStack and did not see the problem using Edge.

![bs_win10_ie_11 0](https://user-images.githubusercontent.com/1119271/33384716-0dcc7310-d4e4-11e7-8322-2bbee977ceca.jpg)

![bs_win10_edge_16 0](https://user-images.githubusercontent.com/1119271/33384731-17372198-d4e4-11e7-87a3-224676b9f65b.jpg)
