### ISSUE TITLE
ABTests: load existing variations from the backend into the state

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#20097]
When we run an AB Test, we save logged-in users assigned variation to the backend (user attribute), and in localStorage (using `store.set`).

If that same user is evaluated for the test again, but with a clean localStorage (say, new browser on another device, or just localStorage turned off), we randomly set their variation, and save it again.

This obviously can mess with the test results and leads to non-uniform experience for the users.

#15169 introduced a method to assign variations by user IDs, but it's not the default, and it would still be safer to load existing variations from the backend (cc @aaronyan)

We should load all the current user test variations before assigning them.
The data should probably be included in the user bootstrap load so that it doesn't delay any tests.

cc @sirino

**Comment by jsnmoon** [comment]
Hi! Heads up: I've been working on fixing this and expect to tackle this in two PRs: 
1) Pull data from backend in `lib/user` using a new REST API on `GET /rest/v1.1/me/abtests`*
2) Pull data in the user bootstrapping process

I will have the first PR up shortly. 

* Backend changes: D9429-code

**Comment by jsnmoon** [comment]
#21709 had to be reverted; new PR will be up soon.
