### ISSUE TITLE
Activity Log: Retry button doesn't work on failed rewind

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#20108]
If a rewind fails, there is a button to try again. It doesn't seem to do anything.

Hat tip @TheSteveK for reporting

**Comment by eliorivero** [comment]
I actually run into this yesterday and was attempting to solve it. It's also happening for a failed backup and in this case, the rewind Id (the float one) has to be returned with the error response. I'll probably need help from @thingalon to get this in the response and also to force an error for both rewind and backups.

**Comment by beaulebens** [comment]
Related (slightly tangential) is that when you get the Retry button, there is also a button to get help. That button loads VaultPress documentation, but it should really just trigger a Happychat.

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/20454
