### ISSUE TITLE
Themes: Invariant Violation when filtering with the dropdown select

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#2010]
How to reproduce:
- Go to the themes page:
- Switch the dropdown filter from "All" to "Premium"
- Notice that the following error is printed in the console:

`Uncaught Error: Invariant Violation: findComponentRoot(..., .3.$66854811.1.1:$theme-canape.1.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID .0.3.5.`

**Comment by ehg** [comment]
Thanks :) Does #1719 fix it for you?

**Comment by Tug** [comment]
@ehg just tried on branch `fix/infinite-list-refs` but the error is still there.

**Comment by seear** [comment]
This has been fixed with the move from infinite-list to infinite-scroll in #2151
