### ISSUE TITLE
Activity Log: Allow credentials to be modified or removed

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#20110]
In the initial mockups, the main card had a caret (arrow) and would be clickable to modify settings:

![image](https://user-images.githubusercontent.com/1123119/33137609-aa6b9a0e-cf65-11e7-8815-20239c105c93.png)

I think at the very least, we should make it a clickable card and add a button to clear SSH creds.

**Comment by beaulebens** [comment]
Are there designs (even if rough) for this process? It's marked as a blocker for this release.

**Comment by MichaelArestad** [comment]
Already fixed.
