### ISSUE TITLE
Activity Log: Live update events

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#20117]
I know this is already on the radar of @dmsnell. Having the activity feed update live would be a wonderful improvement. If necessary, we could utilize similar UI to the Reader:

<img width="176" alt="image" src="https://user-images.githubusercontent.com/1123119/33141251-cf591382-cf6f-11e7-94c9-4e4347539d62.png">

**Comment by samhotchkiss** [comment]
I think this will go a long way towards cleaning up our UX

**Comment by MichaelArestad** [comment]
@samhotchkiss Currently there is live update, but not reader style and it messes with a bunch of things because it's constantly refreshing the view.
