### ISSUE TITLE
Themes: Error Cannot read property 'height' of null when clearing the search bar in Themes

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#2011]
How to reproduce:
- Go to the Themes page
- Enter a word in the search bar
- Wait for the app to trigger the search or display the search result
- Click on the cross to empty the search bar
- Notice an uncaught error is displayed in the console:
```
Uncaught TypeError: Cannot read property 'height' of null
    updatePlaceholderDimensions	@	scroll-helper.js:138
    updateScroll	@	index.jsx:253
```

**Comment by ockham** [comment]
Duplicate of #1698. @Tug can you check if #1719 fixes this for you?

**Comment by Tug** [comment]
@ockham : Weird, it does not fix it for me :(

**Comment by ockham** [comment]
Hmm, very strange. (Please comment there, though :-)
