### ISSUE TITLE
Activity Log: Add help links to connection settings

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#20116]
We need to update the credentials @rcoll built to include two links that only show when the credentials view is open.

![image](https://user-images.githubusercontent.com/1123119/33140864-8a8c4022-cf6e-11e7-8f93-55e369d4b8bb.png)

The first shows a popover with the following text:

> The best way to get your credentials is to check your hosting provider’s website for details. They usually document how to get or create these server credentials. 

CC @michelleweber :)

The second opens happy chat.

Note: I'm also proposing we removed this link:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/1123119/33140898-a8289464-cf6e-11e7-8c1b-788fd1c9986d.png">

**Comment by michelleweber** [comment]
> You can normally get your credentials from your hosting provider -- their website should explain how to get or create the credentials you need.
