### ISSUE TITLE
Store: Settings: Shipping: Cancelling label or package changes does not reset UI state

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#20138]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/settings/shipping/{DOMAIN}
2. Note that `getSaveSettingsActionListSteps` ( `woocommerce/state/data-layer/ui/woocommerce-services` ) returns a empty array
3. Change the Paper size for the label
4. Note that `getSaveSettingsActionListSteps` now returns a non-empty array (as expected)
5. Change the Paper size back
6. Note that `getSaveSettingsActionListSteps` is still non-empty (it should be empty)
7. Refresh
8. Start to add a package and give it a name
9. Note that `getSaveSettingsActionListSteps` ( `woocommerce/state/data-layer/ui/woocommerce-services` ) returns a non-empty array
10. Cancel adding the package
11. Note that `getSaveSettingsActionListSteps` is still non-empty (it should be empty)

**Comment by jeffstieler** [comment]
IIRC these modals are using the same callback for clicking the "cancel" button and clicking "off modal" - the `onClose` prop. If that's true, I think creating a new action for cancel that also results in clearing the form state makes sense. Let's make sure to keep the "off modal" click behavior intact.
