### ISSUE TITLE
Theme Showcase: navigating within a preview shows the masterbar

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#2013]
I think that navigating probably loses the `theme_preview=true` query param that hides the bar.

To reproduce:

1. Open the theme showcase in calypso
2. Click `preview` on a theme screenshot to bring up the modal
3. Verify that the masterbar isn't visible
4. Click on a link within the preview to navigate the preview to another page
5. Notice that the masterbar is now visible

**Comment by lancewillett** [comment]
I can repeat this, still happening (with Mac-n-Chrome — step 1 is https://wordpress.com/design/example.wordpress.com) — it's not *terrible* in that I'm not sure how common moving around sites in the preview pane actually is, from an end user's perspective.

**Comment by lancewillett** [comment]
Might consider closing this one during next bug scrub; it's minor and we have more important things to address.

**Comment by designsimply** [comment]
#bug-scrub

The same problem happens for post previews.

Steps to reproduce:

1. Create and save a new draft with a link to another post on the same blog
1. Click the Preview button

<strong>Result:</strong> the top toolbar appears inside the preview modal

<img width="1280" alt="screen shot 2016-07-19 at tue jul 19 4 32 36 pm" src="https://cloud.githubusercontent.com/assets/1119271/16971277/a07c1e78-4ddf-11e6-98d2-b7d398343555.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10114 using Firefox 47.0.1 on Mac OS X 10.11.5</sup>
