### ISSUE TITLE
Reader Conversations: exclude pingbacks from results

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#20147]
This post is appearing with a large list of pingbacks in the Conversations tool:

http://toni.org/2017/05/25/when-a-company-grows-but-the-office-shrinks/

Can we suppress pingbacks in the results?

<img width="906" alt="screen shot 2017-11-23 at 08 52 55" src="https://user-images.githubusercontent.com/17325/33164692-e1d69a04-d02b-11e7-8969-5a48b9e88453.png">

**Comment by blowery** [comment]
@aaronyan any updates on this one?

**Comment by samouri** [comment]
i believe this is already fixed on the es side. 
also this is a (better) dupe of: https://github.com/Automattic/wp-calypso/issues/19236

fixing this will be interesting. we either:
1. get really smart in redux about separately tracking pingbacks and trackbacks (medium to hard)
2. stop showing them in fullpost (and all of Calypso. not possible b/c of moderation requirements)
3. only filter the ui bit (easy)
4. any other ideas?

**Comment by aaronyan** [comment]
Thanks for the recap @samouri. Looks like a fix is being built here #20272.

**Comment by bluefuton** [comment]
Fixed in #20272.

**Comment by samouri** [comment]
> Fixed in #20272.

we chose ui filtering for now. will update if behavior is funky
