### ISSUE TITLE
"You have unsaved changes" despite "Settings saved" notification in Settings > Traffic

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#20151]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/traffic
2. Enter a Google Analytics ID and save
3. Navigate away to a different tab

#### What I expected

That the Google Analytics ID would be saved and I won't see the "you have unsaved changes" warning. In some cases if you proceed with refresh/going away the Analytics ID just disappears (but does get added to site's source code).

#### What happened instead

You get the unsaved changes warning. Then, in some cases when you come back to the Traffic tab again, the saved Analytics ID will simply not show there at all.

HOWEVER... the analytics ID/code is actually added to the page's source code.

#### Browser / OS version
Chrome, latest

#### Context / Source
#user-report and #manual-testing 

#806452-zen

**Comment by ehti** [comment]
cc @kriskorn

**Comment by designsimply** [comment]
I tested with the steps provided and was unable to confirm a missing Analytics ID, although I *did* see the unsaved changes warning and notices some errors in the console around the same time (I am not sure if they are related).

<img width="1280" alt="screen shot 2017-11-29 at wed nov 29 11 23 21 am" src="https://user-images.githubusercontent.com/1119271/33392046-2a5dcc9a-d4f8-11e7-9735-8d981cf432b5.png">
<sup>Seen at https://wordpress.com/settings/traffic/madefortesting347.blog using Firefox 57.0 on Mac OS X 10.13.1.</sup>

<blockquote>Loading failed for the <script> with source “https://wordpress.com/calypso/post-editor.f506062192856eb1b5ae.min.js”.
madefortesting347.blog:1
Error
columnNumber: 560
fileName: "https://wordpress.com/calypso/manifest.c88b4b6f026cb6eef6a9.min.js"
lineNumber: 1
message: "Loading chunk post-editor failed."
stack: "s@https://wordpress.com/calypso/manifest.c88b4b6f026cb6eef6a9.min.js:1:560\n"
__proto__: Object { … }
manifest.c88b4b6f026cb6eef6a9.min.js:1:9892
Error: Loading chunk post-editor failed.
manifest.c88b4b6f026cb6eef6a9.min.js:1:560</blockquote>

**Comment by designsimply** [comment]
@ehti thank you for the bug report! If you go back to https://wordpress.com/settings/traffic/ and force refresh the page, does the Analytics ID show up consistently then?

**Comment by designsimply** [comment]
Re-tested and made a video this time. When I make a change and try to navigate away from the page, I see an unsaved changes warning even though I have clicked the "Save Settings" button and I see the "Settings saved!" message appear.

Video: [1m36s](https://cloudup.com/cD4PZ_sUAPI)

Screenshots were taken using Safari 11.0.1 on Mac OS X 10.13.1. 

This is what I see if I try to save changes and navigate away by clicking a menu item:

![screen shot 2017-12-05 at tue dec 5 5 46 43 pm](https://user-images.githubusercontent.com/1119271/33638730-da8bd53a-d9e4-11e7-90cd-94b6e208d8ee.png)

This is what I see if I try to save changes and then refresh the same page:

![screen shot 2017-12-05 at tue dec 5 5 46 54 pm](https://user-images.githubusercontent.com/1119271/33638743-e1511ede-d9e4-11e7-93ac-6e82bee5fb09.png)

Also noticed a new console error on the Settings > Traffic page:

> Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)
> https://wordpress.com/calypso/sections/site-settings.css.map

![screen shot 2017-12-05 at tue dec 5 5 46 28 pm](https://user-images.githubusercontent.com/1119271/33638751-e761ad34-d9e4-11e7-85d4-99b61de8dc08.png)
