### ISSUE TITLE
Editor: Visual Mode: ctrl+a should move to the start of the line on MacOS

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#20168]
It's currently selecting all the text in post content input element (same as <kbd>cmd</kbd>+<kbd>a</kbd>). This seems to be fairly new behavior.

"HTML" mode seems fine.

This is a #stresscase because it's easy to overwrite content unexpectedly (and the undo stack in the editor is somewhat untrustworthy).

#### Steps to reproduce
1. On a Mac, start at URL: https://wordpress.com/post
2. Create a post in "visual" mode
3. While the content area has focus, attempt to go to the beginning of the line with <kbd>ctrl</kbd>+<kbd>a</kbd>

#### What I expected

To go to the beginning of the line as is conventional on the Mac.

#### What happened instead

All content is selected

#### Browser / OS version

Chrome 62.0.3202.94 / Mac 10.12.6

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
