### ISSUE TITLE
Editor: Remove Distractions

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#20170]
Some of the feedback we've received in user interviews has indicated that folks are still writing in wp-admin because we do not have a distraction free mode.

A chunk of this distraction comes from the masterbar, and almost certainly the notifications menu:

<img width="1078" alt="screen shot 2017-11-23 at 9 55 19 am" src="https://user-images.githubusercontent.com/1464705/33185053-e2f67fae-d034-11e7-80b1-3d56f7e7f16c.png">

For a first iteration, I think we could actually hide the masterbar on the posting screen. We still have top level navigation in the form of the back button in the top left:

<img width="1074" alt="screen shot 2017-11-23 at 9 57 56 am" src="https://user-images.githubusercontent.com/1464705/33185067-07b8827e-d035-11e7-943e-f08dc70fe392.png">

When you hit that back button you go back to the main Calypso navigation with the sidebar on the left, and the masterbar on the top.

**Comment by folletto** [comment]
> Some of the feedback we've received in user interviews has indicated that folks are still writing in wp-admin because we do not have a distraction free mode.

I'm curious: did they know they could close the sidebar?

> A chunk of this distraction comes from the masterbar, and almost certainly the notifications menu:

Is this a hypothesis, or one of the issues mentioned?

**Comment by lsinger** [comment]
We've heard this in user tests as well. People loved it, even though it wasn't the focus of the tests. @shaunandrews has done some design work in that direction already.

**Comment by apeatling** [comment]
> I'm curious: did they know they could close the sidebar?

I don't know, I don't think so. To be totally honest, I didn't realize you could close it either.

> Is this a hypothesis, or one of the issues mentioned?

It's a hypothesis, but also based on my own usage. That orange dot is hard to resist. ;)

**Comment by mtias** [comment]
> It's a hypothesis, but also based on my own usage. That orange dot is hard to resist. ;)

The orange dot is also likely to be less pervasive for the vast majority of users.

**Comment by mtias** [comment]
Another big drawback for me is losing access to quick drafts from the editor.

**Comment by lsinger** [comment]
Unrelated to Andy's experiences: I think three of our recent six interviewees / user test participants mentioned that they liked how simple and distraction-free it was. We tested something else, however, and never asked them about it (we tested a few navigational ideas, e.g. changing how the "W" / "My Sites" button works). It jumped out at them (positively) so much that they told us without us asking them about it at all. 

This is the editor we showed them:

<img width="1037" alt="screen shot 2017-11-28 at 5 15 52 pm" src="https://user-images.githubusercontent.com/23619/33330692-d486c648-d45f-11e7-8474-2aa002eac355.png">

**Comment by lsinger** [comment]
For if / when we decide to reopen this, the issue that came up in #20214 was that the preview had a `top: 47px` to account for the masterbar being there. It looked weird because the editor behind it had removed that `top` and was now not hidden anymore.

**Comment by mattmiklic** [comment]
> For a first iteration, I think we could actually hide the masterbar on the posting screen. We still have top level navigation in the form of the back button in the top left:

For what it's worth, this idea would align Calypso with our native apps. On both iOS and Android, the editor is a full-screen modal where the top-level navigation is not visible.

**Comment by mattmiklic** [comment]
By the way; we're doing some work on how to make the native editor minimizable to balance between being distraction-free, and allowing the user to switch back to another part of the app if they need to. Ref: p77Llu-9uA-p2.

**Comment by lancewillett** [comment]
Closed with 3401e45.

**Comment by gemmagarner** [comment]
Passing on a [Twitter request](https://twitter.com/JohnMLTX/status/1053524406109122560
) for a minimal editor with even fewer distractions (no right sidebar).

**Comment by lsinger** [comment]
> no right sidebar

FWIW, the cog wheel in the top right lets one hide the right sidebar.
