### ISSUE TITLE
Activity Log: notice about rewind 

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#20179]
This notice is showing up on a non Pressable site, free Jetpack plan, no proxy, no a11n user, no Rewind active:

<img width="834" alt="captura de pantalla 2017-11-23 a la s 20 12 02" src="https://user-images.githubusercontent.com/1041600/33190697-6ac226be-d08e-11e7-9030-70aa2e62676c.png">

@samhotchkiss @MichaelArestad Should we hide it?

**Comment by MichaelArestad** [comment]
The notice should not be visible to:

* non-rewind active sites
* free Jetpack plans

**Comment by samhotchkiss** [comment]
Fixed by @rcoll this morning
