### ISSUE TITLE
Import: prevent import on unsupported devices

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2017]
Raised by @rickybanister 

It is not currently viable to import (using a file-upload style importer) on mobile safari. 

If you attempt to upload, you can only browse for photos or take a new photo. 

We only currently have file-upload-style importers so we need to hide the import upload form for iPhone and iPad in safari at present. We should use the EmptyContentComponent and display a helpful message that explains how you can't browse for a content file on the device. 

More research is needed for Android. Once /export is ready [for testing] I can try exporting to Google Drive and attempting an import from there. Android does let you browse documents, but they are documents stored in Drive...

When we add api-driven importers we can bring back the option since it's simply entering credentials.

Notes from @folletto 

> Note that as iOS9 it's possible to download any file as it was possible already on Android. :)
iOS9 is already on [more than 50% of active devices](http://arstechnica.com/apple/2015/09/apple-ios-9-on-more-than-half-of-all-devices-fastest-adoption-rate-ever/), so I think it's safe to assume that we hit critical mass on the various platforms, and it's safe to keep the download button visible.
> 
> The email still is a great alternative to have. :)
> 
> Would be great if we could detect older mobile devices and show a different message still as indicated in this issue. iOS is clearly 9.0 where the feature was first enabled, I'm not sure Android and Windows Mobile.

Also see #78

**Comment by dmsnell** [comment]
@designsimply I was able to upload from mobile Safari via iCloud Drive and/or from Dropbox. I don't think we need to hide this and I think it should all work now.

I'm going to close it but feel free to reopen if you find something wrong with my logic.

I _was_ successful in starting an import from my iPhone
