### ISSUE TITLE
Activity Log: add vertical spacing after credentials notice

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#20176]
Vertical spacing is needed when AL is loading and the credentials notice is visible:

<img width="847" alt="captura de pantalla 2017-11-23 a la s 19 41 13" src="https://user-images.githubusercontent.com/1041600/33189957-abf7216e-d086-11e7-8f66-af591ee35490.png">

**Comment by samhotchkiss** [comment]
See also:

![image](https://user-images.githubusercontent.com/574752/33298781-712872d0-d3b6-11e7-9011-167ae5a357af.png)
