### ISSUE TITLE
Navigation: mobile My Sites menu has a horizontal scroll

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#20196]
![screen shot 2017-11-24 at 12 55 08](https://user-images.githubusercontent.com/4389/33211517-d7e6afa2-d116-11e7-8d31-8d7579352b34.png)

On top of the common issue with the double scroll on mobile sizes, apparently now there's also an additional horizontal scroll on My Site.

I verified this on both desktop Chrome and iOS.

**Comment by rachelmcr** [comment]
I tested this in desktop Chrome and iOS Safari and can no longer reproduce the horizontal scroll. Closing as resolved.
