### ISSUE TITLE
Signup: Likes from logged out users should lead to user only signup

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#2019]
Right now clicking on the Likes, while not logged in leads you to sign in.  If you don't have an account, clicking Register takes you to the /start signup, but it should take you to the signup with least friction: /start/account

To reproduce:
1) While signed out, click a like button
2) Click Register
3) You're prompted to pick a theme, instead of just create a quick user

Ideally, this would also mark the post liked once signup is filled out.

**Comment by graciemae** [comment]
User requested this feature in chat and made a good case for it: https://mc.a8c.com/support-stats/feedback/chat-transcript.php?id=287142

**Comment by folletto** [comment]
Noting here that this is a first step. In the future the "like" flow should be even more seamless with a design that doesn't change the flow. It's super important for us to get this flow as seamless as possible.

**Comment by fabianapsimoes** [comment]
This might also be fixed by https://github.com/Automattic/wp-calypso/issues/757, which aims to add a path to the user-only flow from the main flow.

**Comment by beaulebens** [comment]
Seems like this can be "fixed" with changing a single URL/redirect.

**Comment by spncrb** [comment]
This is still a valid issue that should be easily fixed. Right now the sign up link when you like a post logged out is still prompting you to create a site:
![likelink](https://user-images.githubusercontent.com/8921630/35113597-d7914a76-fc36-11e7-8ecf-3c1257b3fb40.gif)

**Comment by alisterscott** [comment]
This is also mentioned in https://github.com/Automattic/wp-calypso/issues/8631
