### ISSUE TITLE
Warn users that have active email forwarding when upgrading to G Suite

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#20208]
As reported in p2MSmN-6hy-p2 by @eurello, when a user has email forwarding set up and they want to upgrade to G Suite, we don't warn them that the email forwarding will stop working as a result.

Related issues:
https://github.com/Automattic/wp-calypso/issues/1534
https://github.com/Automattic/wp-calypso/issues/3145

**Comment by rwaynick** [comment]
Another suggestion for a warning in 2159832-hc

**Comment by klimeryk** [comment]
@Automattic/amber is this something that's on your roadmap or should we close it? I do think it's a good idea from an UX perspective - the connection between email forwarding and G Suite (and how they are exclusive) is not always obvious to the user. On the other hand, I have not seen this issue reported lately (though, it simply might not be reported to developers anymore, treated as a status quo, etc.), maybe because in most cases the G Suite account that they set up matches the email forwarding they've had?

**Comment by robertf4** [comment]
@klimeryk, I'm looking at it now; going for a more comprehensive fix than just warning the user. See p9j7e4-wG-p2.

**Comment by klimeryk** [comment]
Awesome - thanks for the follow-up and link! ❤️

**Comment by stephanethomas** [comment]
I'm going to close that issue as we now display the following warning when a user tries to purchase G Suite for a domain that already has email forwards:

![screenshot](https://user-images.githubusercontent.com/594356/68675571-7667da80-0558-11ea-82f2-be6c2a9a45c3.png)
