### ISSUE TITLE
Calypso Editor: After publishing, editor bar not going away

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#20214]
## Problem

The editor bar should disappear and the blue "My Sites, Reader" bar should appear after publishing a post/page ("old" experience). In the "new" experience, after a post/page is published, the editor bar stays at the top, and the Update button, settings toggle, and preview don't work. This leads me to believe the old experience is the correct one.

Here are pictures of old and new experiences:

### Old

<img width="691" alt="old-publish-experience" src="https://user-images.githubusercontent.com/4505888/33224446-5dde130a-d11e-11e7-8157-07feb9ba6314.png">

### New

<img width="908" alt="new-after-publish-xp" src="https://user-images.githubusercontent.com/4505888/33224449-60512ef6-d11e-11e7-9d5e-97392bf44b3b.png">

**Comment by lsinger** [comment]
Good catch. That doesn't look right. 

Maybe related to #20174? /cc @lamosty

**Comment by apeatling** [comment]
It looks like this code was relying on the masterbar being there to hide the other options underneath. Instead, the bar will need to be hidden on this screen.

**Comment by apeatling** [comment]
@lsinger Did your team work on this? It's probably just as quick to update the CSS to hide the bar on this screen, would someone mind looking at that? Otherwise we can revert the masterbar change.

**Comment by lsinger** [comment]
@apeatling can we revert for now? nobody available immediately and this seems like it needs a fast fix.

**Comment by lsinger** [comment]
cc @Automattic/tanooki who worked on the post-publish experience so they're aware.

**Comment by apeatling** [comment]
https://github.com/Automattic/wp-calypso/pull/20219

**Comment by lsinger** [comment]
Fixed through #20219, closing for now.
