### ISSUE TITLE
improve the copy in the to-Premium upgrade Media Banner

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#20226]
To-Premium upgrade Banner currently in `https://wordpress.com/settings/writing/:site` is a bit bare-bones and cryptic (no heading, mention of a plan).
Should it adhere to the standards we recently adopted in the upgrade Banners at `https://wordpress.com/settings/traffic/:site` (https://github.com/Automattic/wp-calypso/pull/20099) ?

#### Steps to reproduce
1. Starting at URL: `https://wordpress.com/settings/traffic/:jetpack_connected_site`
2. scroll down to the `Media` section

#### Screenshot / Video

![screen shot 2017-11-26 at 21 25 14](https://user-images.githubusercontent.com/13561163/33244129-fd32999c-d2f1-11e7-9ab8-055374f98908.png)

**Comment by nicoleckohler** [comment]
@AnnaMag If this is an upgrade nudge (looks like it) then yes, I'd suggest we keep the same standard and add a second line/revise the wording :)

So the revised version I'd suggest would be:

> **Enable video hosting by upgrading to Jetpack Premium**
> Get high-speed video hosting without ads, watermarks, or throttling.
