### ISSUE TITLE
Rogue postMessage event triggers invalid API call

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#20224]
Rogue `postMessage` event in `window.frame[ 0 ]` triggers invalid API call.

**Context:** I had Google's [Accessibility Developer Tools extension](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb) installed and I noticed weird API calls each time I clicked around Calypso.

Dispatching message directly in window has no affect: `window.postMessage({}, '*')`

##### Via browser console
1. Visit [wordpress.com](https://wordpress.com/) using Chrome or Firefox
1. Enter this to Browser's console: `window.frames[0].postMessage({}, '*')`
1. Observe error in Chrome's dev console or in Firefox's network tab:
    ```
    GET https://public-api.wordpress.com/rest/v1undefined?http_envelope=1 404
    ```
   _Note "undefined"._

##### Via Chrome extension
1. Install Google's [Accessibility Developer Tools extensions](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb)
1. Visit [wordpress.com](https://wordpress.com/)
1. Observe error:
    ![image](https://user-images.githubusercontent.com/87168/33084792-83a41c54-ceeb-11e7-8974-dbef6b6f61b8.png)
1. Coming from extension's code:
    ```js
    (function() {
      for (var a = window.frames, b = 0;b < a.length;b++) {
        var c = a[b], d = axs.content.removeFragment(document.documentURI);
        try {
          c.postMessage({request:"getUri"}, "*"); // 👈 here
        } catch (e) {
          console.warn("got exception when trying to postMessage from " + d + " to frame", c, e);
        }
      }
    })();
    ```

#### What I expected
No errors when browser extensions use `postMessage` internally.

#### What happened instead
![image](https://user-images.githubusercontent.com/87168/33241956-f3671b8e-d2d5-11e7-8a59-3c7428655f5d.png)

#### Browser / OS version
Chrome 62 / Firefox / MacOS High Sierra

/cc @dmsnell

**Comment by rachelmcr** [comment]
I can no longer trigger an invalid API call with the steps listed above. Closing as resolved, but please reopen if I've missed something here.
