### ISSUE TITLE
Activity Log: Let users know we've started backing up their site

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/wp-calypso#20228]
![image](https://user-images.githubusercontent.com/574752/33246612-9aebff06-d2e4-11e7-9b7e-db6da8426edf.png)

After you add credentials, we should say something like “Your first backup has been queued up.”

Probably SHOULDN'T say "Backups and restores _should_ work seamlessly"... seems awfully insecure.

Pinging @michelleweber for copy suggestions

**Comment by michelleweber** [comment]
Yeah, concur -- it's not confidence-building as-is. Can we just be nice and declarative and say "Your first backup will begin shortly?"

**Comment by MichaelArestad** [comment]
I think the success notice (GlobalNotice) should say

> You're all set! Your first backup will begin shortly.

I think we should change the copy in the settings box to a slightly different format. Something like this:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1123119/33351647-0a8c6746-d462-11e7-961d-0c40b3de4058.png">

**Comment by eliorivero** [comment]
Should we close this now that we have this in the plugin or should the content in this issue be implemented?

<img width="740" alt="captura de pantalla 2017-12-21 a la s 15 14 04" src="https://user-images.githubusercontent.com/1041600/34269012-9a601794-e661-11e7-9173-cca056c7df81.png">
