### ISSUE TITLE
Store: Order Complete Email -  Add "Disable" option for Shipment Tracking

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/wp-calypso#20258]
https://github.com/Automattic/woocommerce-services/pull/1173 added shipment tracking information into the "Complete Order" email.

This somewhat duplicates the existing customer-note-based feature ([#](https://github.com/Automattic/wp-calypso/pull/18281/commits/0f4c5cdf9825f03bbf4b33f30dfc655a44230763)), and may not be desired by all merchants ([#](https://github.com/Automattic/woocommerce-services/issues/1245)).

~Let's come up with a way to disable the tracking numbers in email - perhaps in the "shipping label" settings?~

~Should we also remove the per-order checkbox for tracking, or rethink its interplay with the new WCS functionality?~

To do (decided in https://github.com/Automattic/wp-calypso/issues/20258#issuecomment-347650881):

- [ ] Add a global setting for the default value of the per-order checkbox
- [ ] Only enable the "email details" checkbox if "mark order fulfilled" is checked

**Comment by jameskoster** [comment]
Hmm, I'm hesitant to add a global option to the shipping settings for this. The reason being that it's an extra point for potential confusion during set up and honestly, how many people are going to want to disable this? It seems like an edge case to me.

I think I'd prefer to leave the disabling to be per-order for now.

> or rethink its interplay with the new WCS functionality

How does it work currently? Does it send a separate email? 

If I understand things correctly, when the "Email shipment details to the customer" checkbox is checked I'd expect the tracking details to be included in the "Order complete" email. If it's unchecked then obviously it shouldn't be included, but an internal order note should still be created.

**Comment by jeffstieler** [comment]
> Hmm, I'm hesitant to add a global option to the shipping settings for this. The reason being that it's an extra point for potential confusion during set up and honestly, how many people are going to want to disable this? It seems like an edge case to me.
> 
> I think I'd prefer to leave the disabling to be per-order for now.

People setting up their store through WP.com probably won't want to disable it, but our WP.org merchants might already have established stores and solutions for sharing tracking details. We can add the global option and default it to "on" which should satisfy all cases.

> How does it work currently? Does it send a separate email?

Right now, the checkbox triggers an email separate from the "order complete" email, utilizing the "customer note" feature.

What's been added to the WCS plugin (version `1.9.0`) is the addition of the tracking number to the order complete email, not tied to a per-order checkbox (it's hidden in `/wp-admin`).

If a store on WP.com checks the "Email shipment details to the customer" box now, the customer-note-based email will be duplicative of the order complete email.

> If I understand things correctly, when the "Email shipment details to the customer" checkbox is checked I'd expect the tracking details to be included in the "Order complete" email. If it's unchecked then obviously it shouldn't be included, but an internal order note should still be created.

As described above, it doesn't currently work this way. If we go down this path, should the checkbox default to "on" or "off"? Should it remember the last setting? Things could get frustrating for merchants that don't want the default behavior.

**Comment by jameskoster** [comment]
The other problem with a global option is that it gives no room for manoeuvre. If, for some reason you want to include (or not include) tracking info for one order in particular you need to go and change a global setting. I know that seems unlikely, but it also seems unlikely to me that many people will want to disable this feature. 

Temporarily changing a global could cause issues for really big stores that may have multiple people working on orders simultaneously. Ironically, I presume those big stores are probably going to be the ones that are more likely to have a specific tracking setup already.

When thinking about this earlier, I concluded that if we add the global, we should probably still keep the per-order option. And at that point it felt like overkill. But I do agree, having to remember to uncheck a checkbox every time you process an order will be annoying.

If we can add the global in a clear/simple way let's do that. But keep the per order checkbox which will default to whatever the current global setting is.

**Comment by jeffstieler** [comment]
> If we can add the global in a clear/simple way let's do that. But keep the per order checkbox which will default to whatever the current global setting is.

👍 

So how about this:
1. Add a global setting for the **default** value of the per-order checkbox
1. Only enable the "email details" checkbox if "mark order fulfilled" is checked

**Comment by jameskoster** [comment]
Sounds good!
