### ISSUE TITLE
My Sites: Plans, Domains, and Plugins nav elements do not load in IE 11 all versions of Windows

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/wp-calypso#2025]
We've had a few tickets today reporting that when in My Sites when attempting to purchase a domain/mapping they see the loading icon in the masterbar but are stuck in a perpetual state and the proper screen never loads. All these users were on Windows. 

I confirmed this version in IE 11 all versions of Windows in Browserstack for the Domain, Plan, and Plugin navigational elements. Below is an image of the console output:

<img width="522" alt="screen shot 2015-12-29 at 11 35 25 pm" src="https://cloud.githubusercontent.com/assets/312395/12048203/ca2328ea-ae8c-11e5-9fad-f2fde60dedef.png">

@gziolo has a PR to fix the plugin portion of the error: https://github.com/Automattic/wp-calypso/pull/2024

Props @rootjosh

**Comment by gziolo** [comment]
This should be fixed with #2024 and #1950.
