### ISSUE TITLE
Store: Repeated requests (2x/sec) to Jetpack Proxy for /wc/v1/connect/account/settings

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#20260]
#### Steps to reproduce
1. Starting at URL: While sitting at http://calypso.localhost:3000/store/{DOMAIN}
2. Open the JavaScript developer tools, network tab
3. Observe repeated (2x/sec) calls to the Jetpack proxy for /wc/v1/connect/account/settings

Note: This doesn't seem to happen everytime you visit a store's dashboard - just some of the time

These calls all fail with
```
{"code":404,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"rest_no_route","message":"No route was found matching the URL and request method"}}
```

**Comment by allendav** [comment]
Looks like this happens if the WooCommerce Services plugin is awol. Leaving this open so we can surface the error to the merchant in calypso somehow.

**Comment by timmyc** [comment]
This also happens on the Order Details page, and prevents the Activity log from being properly shown:

![wcs-disabled-order-details](https://user-images.githubusercontent.com/22080/33787515-7024b032-dc22-11e7-8ef5-2706fb967482.png)

![activity-log-loading](https://user-images.githubusercontent.com/22080/33787520-7801324e-dc22-11e7-9473-b1835a13dbe4.png)

__Steps to reproduce__
- Deactivate WC Services plugin
- Open an Order 
- Watch the red appear in the console and listen to the fan on your macbook go into jet-mode.
