### ISSUE TITLE
Store: Shipping: Labels: Take care when prompting non Jetpack primary users to add payment methods

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#20262]
I love this new prompt

<img width="957" alt="add-a-payment-method" src="https://user-images.githubusercontent.com/1595739/33290462-9abc430e-d377-11e7-8389-a41ab19de04c.png">

but the WordPress.com user (allendav) that I was logged in as is not the primary Jetpack user for the site, so navigating to Settings > Shipping is a dead end.

<img width="887" alt="screen shot 2017-11-27 at 1 34 22 pm" src="https://user-images.githubusercontent.com/1595739/33290503-b9d258b4-d377-11e7-900e-f822881ca35e.png">

Maybe the prompt needs to say "have (primary jetpack user username + displayname ) add a payment method" in such cases?

**Comment by DanReyLop** [comment]
Duplicated of https://github.com/Automattic/wp-calypso/issues/19389
