### ISSUE TITLE
Domains: Payment Settings button on domains page doesn't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#20274]
Looks like a recent regression - I have confirmed this works in the desktop app

#### Steps to reproduce
1. Starting at URL:   https://wordpress.com/domains/manage/testsite.com/edit/testsite.com
2. Click "Payment Settings"

#### What I expected

To see payment settings

#### What happened instead

Error with console error: `Uncaught TypeError: Cannot read property 'product_slug' of undefined`

#### Browser / OS version

Tried a few and all the same - Chrome, Safari on macOS

#### Screenshot / Video

<img width="1079" alt="screen shot 2017-11-28 at 12 23 05 pm" src="https://user-images.githubusercontent.com/128826/33299361-ee32016c-d436-11e7-8adc-274e78ca797a.png">

![domain only](https://user-images.githubusercontent.com/128826/33299298-af888134-d436-11e7-82be-764eaba15a14.gif)

#### Context / Source
#dogfooding, #manual-testing

**Comment by alisterscott** [comment]
Thanks @dmsnell for pinpointing this to most likely being introduced in https://github.com/Automattic/wp-calypso/pull/19938

**Comment by klimeryk** [comment]
Ugh, great catch - @aidvu, can you take care of this one?
