### ISSUE TITLE
Plugins: inconsistent search results

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#20275]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plugins
2. Click on the search icon (magnifying glass)
3. Type "ecwid" (in this case) 

#### What I expected

I expected for the Ecwid plugin to show up as a result.

#### What happened instead

No plugins matched the search result. 
This happens sporadically for different plugins and is hard to detect.

#### Screenshot / Video

Video - http://take.ms/f1yxN

#### Context / Source

#user-report (652048-hc) #manual-testing

**Comment by kriskorn** [comment]
cc @ehti

**Comment by designsimply** [comment]
Tested and confirmed using various plans (Free, Personal, Premium, Business) that when I go to the Plugins page and search for "ecwid" sometimes the Ecwid Ecommerce Shopping Cart shows up as expected and sometimes it does not.

![screen shot 2017-12-06 at wed dec 6 2 12 40 pm](https://user-images.githubusercontent.com/1119271/33686116-055e8e18-da91-11e7-9009-f4b01f39ad99.png)

![screen shot 2017-12-06 at wed dec 6 2 14 23 pm](https://user-images.githubusercontent.com/1119271/33686125-0e3d5dfc-da91-11e7-9bf1-de3b9075edec.png)

<sup>Seen at https://wordpress.com/plugins/madefortesting554.wordpress.com?s=ecwid with a Free Plan using Firefox 57.0.1 on Mac OS X 10.13.1.</sup>

**Comment by sethmclellana8c** [comment]
I ran into this problem searching for a plugin ("Newsletter") a user had on my own test site (AT site). I was using Firefox 58.0.2 (64-bit).

Sometimes I'd search for "newsl" and keep typing, and each new screen of resulting-plugin-matches as I typed (predictive search?) came up with wildly different views. At the end when I had "newsletter", sometimes the correct plugin would be there, most often not though.

I also tried proper case-sensitive search for "N" "Ne" "New" "News" "Newsl" etc etc and again, sometimes it fixed the issue, most often not though.

I also tried clicking both the "Plugins" name on the Calypso menu versus also clicking the "Manage" button in Calypso menu with varying results.

I also tried searching other plugin names the user had, with same sketchy results.

**Comment by rachelmcr** [comment]
I have been testing the search at https://wordpress.com/plugins in Chrome 68.0.3440.106, Safari 11.1.2, and Firefox 61.0.2 and am so far unable to reproduce the result where a plugin doesn't appear in the search results.

I have seen the behavior where partial searches (e.g. "newsl") have very different results from the full term search, but once I complete typing the full term I see the plugin as expected.

That said, I _can_ reproduce the problem searching at https://wordpress.com/plugins/manage. The search results there are wildly different each time and so far never include the plugin I'd expect (e.g. with searches for Gutenberg and WooCommerce).

**Comment by cpapazoglou** [comment]
I am closing this cause I can't reproduce it anymore. If that's not the case, please reopen it.
