### ISSUE TITLE
Media : Filename search is not working

### ISSUE THREAD

**Issue by Umangvaghela** [Automattic/wp-calypso#20281]
#### Steps to reproduce
1. Starting at URL:
2. Go to media
3. Search image with filename

#### What I expected
filename search is working in WordPress so it would be great to implement the filename search functionality.

#### What happened instead
Title search is working but filename searching is not working

#### Screenshot / Video
![media one](https://user-images.githubusercontent.com/26810472/33316593-77e84826-d45a-11e7-9b9e-53c4fc68043d.png)
![media two](https://user-images.githubusercontent.com/26810472/33316594-78416e60-d45a-11e7-85cf-ed317de5d044.png)

**Comment by rachelmcr** [comment]
Thanks for the report! This is similar to https://github.com/Automattic/wp-calypso/issues/15233 so I'm going to close this issue in favor of tracking the main issue there.
