### ISSUE TITLE
install instructions for PC .exe

### ISSUE THREAD

**Issue by DigitalDavo** [Automattic/wp-calypso#2029]
Sorry, not sure how else to contact you guys over this. 

Wanted to build calypso for the PC to be able to run the debug version.

Have got git, git-scm, cloned the repository and node all installed and running fine - docs/install.md instructions apply equally to windows and osx.

please tell me what is the recommended make.exe that I need to use? Can I use Visual Studio Express 2015 to build it or do I also need gcc of some flavour ?

thanks.

perhaps the docs/install.md instructions could be updated for the windows specific steps that are needed.

**Comment by designsimply** [comment]
Calypso doesn’t run on windows yet. 

In https://github.com/Automattic/wp-calypso/issues/592, I found that the recommended solution will be to use a development environment for Calypso running on Vagrant when it becomes available. cc @stephanethomas

**Comment by hughc** [comment]
Can I suggest that the docs, specifically the Prerequisites section of 

https://github.com/Automattic/wp-calypso/blob/master/docs/install.md

be updated to reflect this?

There is reference to installing Node under Windows in there, which implies multi-platform build support, but is clearly irrelevant if there is no make equivalent available.

**Comment by nylen** [comment]
Good suggestion @hughc!  Done in #2093.

**Comment by stephanethomas** [comment]
@DigitalDavo, I just wanted to let you know that we have released this [portable development environment](https://github.com/Automattic/wp-calypso-bootstrap) based on Vagrant that simplifies the task of running Calypso on Windows. Enjoy!

**Comment by nylen** [comment]
We do now have an approach for running Calypso on Windows (see current [`install.md`](https://github.com/Automattic/wp-calypso/blob/master/docs/install.md) and #2124).

@stephanethomas, do you think the new Vagrant environment is something we should mention as an option for Windows?

**Comment by stephanethomas** [comment]
@nylen yes, and that was part of my plan. I just didn't have the time to do so. I'll open a pull request for that.
