### ISSUE TITLE
Comments: reduce jumping when comments load

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#20301]
As a side-effect of how we load comments (one request per comment), items will jump as new comments are loaded come in. Let's try to minimize that since folks can lose their reading positions.

A few approaches we might take:
- A new batch GET endpoint for comment details
- Wait until all comments have loaded on a page before rendering.

cc @apeatling

**Comment by gwwar** [comment]
Since the batch endpoint is not available on Jetpack I'm going to recommend we update the comment list endpoint:

```
/sites/{site}/comments?ids=1,2,3
```

It looks a bit awkward compared to 
```
/sites/{site}/comments/1
```

The other alternative is to add a new POST endpoint.

**Comment by kwight** [comment]
> It looks a bit awkward compared to the single comment fetch

I think it's still preferable and more predictable than a `POST` endpoint.
