### ISSUE TITLE
Cancellation Survey allows cancellation without any responses

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#20319]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Choose a plan recently purchased and try to cancel/refund

#### What I expected

For questions to be required

#### What happened instead

Can immediately cancel, and form is still enabled and active even when cancellation in progress

#### Browser / OS version

Chrome 62 on macOS

#### Screenshot / Video

![cancel refund](https://user-images.githubusercontent.com/128826/33363066-85bfe23a-d52a-11e7-90fb-31346305608b.gif)

#### Context / Source
 #automated-testing

**Comment by alisterscott** [comment]
@markryall as discussed

**Comment by markryall** [comment]
Closed with the deployment of #20320
