### ISSUE TITLE
Signup: Cannot purchase single premium theme when starting signup from theme showcase page

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#20316]
**Steps to reproduce**
1. Starting at URL: https://wordpress.com/theme/small-business (or any other premium theme showcase page).
2. Click "Pick this design" button.
3. In the plan selection step pick free plan.
4. Finish the signup process.

**What I expected**
To be prompted at some point during signup to purchase the premium theme I started from.

**What happened instead**
At no point was I prompted to buy the theme I started from, nor was it mentioned that I can get that theme with Premium/Business plan. I ended up with a brand new site running Twenty Sixteen without any info on how to get the theme I wanted. 

I made a video of this issue:
https://cloudup.com/cJu4wh6wifj

Issue found through manual testing.

**Comment by rachelmcr** [comment]
Closing this issue as it's the same as https://github.com/Automattic/wp-calypso/issues/20717 (leaving that one open as it includes additional details/screenshots).
