### ISSUE TITLE
Import: wp:wp_author data is not imported properly

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2031]
Steps to reproduce:

1. Download test data from https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml
1. Go to https://wordpress.com/settings/import and click WordPress (when it becomes available)
1. Import the test data from step 1
1. Check to see if the authors import normally or not

<strong>Result:</strong> it fails to read any authors from the export file and displays an empty author table at `/authors`. Note: test data found at https://codex.wordpress.org/Theme_Unit_Test

We need to support (or convert `wp_author` to `author`) both styles.

/hat tip @rickybanister for the original report

**Comment by dmsnell** [comment]
Hopefully will be resolved with the merge of D1064

**Comment by dmsnell** [comment]
D1064 merged in r131225-wpcom and deployed
