### ISSUE TITLE
Don't show Rewind error for site that should have no access to Rewind functionality

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#20327]
#### Steps to reproduce
1. On a Jetpack site (ping me for the URL, it's a private site), with no/free plan, go to Stats > Activity in Calypso
2. See error referring to Rewind at the top

![screen shot 2017-11-29 at 9 22 02 am](https://user-images.githubusercontent.com/108942/33386512-580d6a84-d4e8-11e7-846f-7c9cbbf4ca3d.png)

#### What I expected
- basic list of events (since it's only a free site)
- no error/mention of Rewind (unless we want a proper banner there, encouraging upgrade to get the ability to rewind your site, but let's leave that out for now).

#dogfooding #manual-testing

**Comment by rcoll** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/20347 but would appreciate testing with the original site if you're able @beaulebens . Thanks.

**Comment by beaulebens** [comment]
Confirmed that I'm not seeing any prompts for credentials on this site any more.
