### ISSUE TITLE
Import: map authors from the API response to the internal state

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2032]
Raised by @dmsnell 

Right now the author data is coming across from the API after the file upload, but there's no real activity to map them. Two things needs to happen:

 - [x] The mapping needs to hook up the returned authors with the WordPress.com users in the internal state
 - [x] The importer needs to intelligently dispatch those updates back to the server.

Also see https://github.com/Automattic/wp-calypso/issues/2031

**Comment by dmsnell** [comment]
Handled by way of a design change wherein the author mappings are stored locally and then returned to the server when the user hits "Start Import"
