### ISSUE TITLE
Store: Only 100 product categories display for promotion & product management

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#20339]
Both the "Applies to" component used in promotions management and the product category dropdown on the products page only show the first 100 categories.

100 is the default `per_page` limit for the `/product/categories` endpoint.

To reproduce:
* Create some categories via the product dropdown or wp-admin. Make sure you have something like 15.
* View the "applies to" component and note that there are only 100 categories loaded.
* Look at the autocomplete on the products page and note the same thing.

cc @coderkevin

**Comment by justinshreve** [comment]
I'm working on moving the product categories code to the data-layer and adding support for query args (like we have for other objects), so maybe something like that will be useful here.

**Comment by justinshreve** [comment]
This also has the side affect of not properly loading all the categories in the edit form, so if there are some applied that are not in the first 10 results, they won't display. Maybe a short term solution is to bump up the per_page count to something larger like `100`?

**Comment by timmyc** [comment]
confirmed this bug still exists, moving to Q1

**Comment by justinshreve** [comment]
This has been bumped up to 100 recently so it's less of a problem, but along with #20977, some updates still need to be made.
