### ISSUE TITLE
Import: add text to explain what to do in the multiple author view

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2033]
Raised by @drw158 

This text should be added

![screen shot 2015-11-17 at 12 36 53 pm](https://cloud.githubusercontent.com/assets/618551/11220966/26daeda6-8d28-11e5-8f2f-5c16dad87dd7.png)

**Comment by drw158** [comment]
Currently if I'm not mistaken, there are 2 different scenarios:

**Source blog has multiple authors, and destination blog has multiple authors** (as shown in mockup above)

> We found multiple authors on your `[Source site type]` site. Please reassign the authors of the imported items to an existing user on **`[Site Title of destination blog]`**, then click Start Import.

:point_up: I tweaked the text a little bit from what is shown in the mockup.

**Source blog has multiple authors, and destination blog has _one_ author**

> We found multiple authors on your `[Source site type]` site. Because you're the only author on **`[Site Title of destination blog]`**, all imported content will be assigned to you. Click Start Import to proceed.

cc: @dmsnell

**Comment by dmsnell** [comment]
@drw158 isn't it also worth a condition where there is only a single author from the imported blog?

**Comment by drw158** [comment]
I guess there would be 2 more:

Source blog has one author, and destination blog has one author

and

Source blog has one authors, and destination blog has multiple authors

**Comment by drw158** [comment]
**Source blog has one author, and destination blog has one author**

> We found one author on your `[Source site type]` site. Because you're the only author on **`[Site Title of destination blog]`**, all imported content will be assigned to you. Click Start Import to proceed.

**Source blog has one author, and destination blog has multiple  authors**

> We found multiple authors on **`[Site Title of destination blog]`**. Please reassign the author of the imported items to an existing user on **`[Site Title of destination blog]`**, then click Start Import.

Ok that should cover all cases. I double-checked each one, and I think it all makes sense.
