### ISSUE TITLE
Domains: Give users a way to manually override the lock status step for incoming transfers

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#20345]
There are a ton of edge cases when getting WHOIS info because it's not standardized in any way. Because our checks can't always be 100% guaranteed accurate, we should allow users to override the lock status pre-check.

In some cases, the domain may actually be unlocked but it's showing as locked when we try to parse the WHOIS record. Now the user is stuck and can't proceed with the transfer.

Allowing some sort of manual override would fix these cases. We will need to have good messaging around using the override and the risk of the transfer failing if it is actually still locked.

h/t @timmyc for having a domain that fit this case

**Comment by danhauk** [comment]
This would also help more advanced users get through the flow faster if they didn't have to wait for the lock status to update.

**Comment by mikeshelton1503** [comment]
>There are a ton of edge cases when getting WHOIS info because it's not standardized in any way. Because our checks can't always be 100% guaranteed accurate, we should allow users to override the lock status pre-check.

Do we have any idea of what percentage of the time this might happen?

Adding an override feature suggests that we're skirting around the real issue here. If we add it we're adding complexity to the product to solve for an inefficiency in another area of the product.

@aidvu Out of curiosity, what would it take to make the check 98%+ accurate? Is that an obtainable goal, timeline and effort aside for a moment?

**Comment by mikeshelton1503** [comment]
Following up on my thoughts above, one path forward I see if we work towards patching up the holes we have in the check through the override. So when someone overrides we create a record for us to use to improve the check.

With that in mind here's a proposal for an override:

After 3 unsuccessful attempt to unlock a domain (an attempt = clicking the button), we show a message that allows the user to skip to the next step. Like this:

![image](https://user-images.githubusercontent.com/12596797/33641657-71c9edaa-da04-11e7-894f-08f97aafb327.png)

Clicking "try again" would switch back to the original state, allow them to check again and then this message would show up again. OR, perhaps we shouldn't have a try again option at all and instead provide an option to contact support?

**Comment by klimeryk** [comment]
@aidvu What's the status of this one? Do we want this or will it create more problems/frustration?

**Comment by aidvu** [comment]
I don't see it becoming priority. I don't recall reports of such cases.

**Comment by klimeryk** [comment]
Cool - closing for now then. We can revisit if we notice new cases.
