### ISSUE TITLE
Site settings: sync notification looks weird

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#20356]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/manage-connection/:site (jetpack site)
2. Let "Data synchronization" section load
3. See "Last fully synced" notification

#### What I expected

This is how notification looked before PR https://github.com/Automattic/wp-calypso/pull/17796 _"Update notice colors to pass WCAG AA guidelines"_:

![image](https://user-images.githubusercontent.com/87168/33432050-38d2716c-d5df-11e7-98b5-134d115447fd.png)

#### What happened instead
This is how it looks today:
![image](https://user-images.githubusercontent.com/87168/33432056-3d6f5a78-d5df-11e7-8095-bedbac7c8f26.png)

#### Context / Source

Seems to boil down to the fact that [there's some custom css](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/jetpack-sync-panel/style.scss#L13-L24) modifying [that sync notice](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/jetpack-sync-panel/index.jsx#L152-L154).

See [how Notices normally look like](https://wpcalypso.wordpress.com/devdocs/design/notice) (choose "Compact Notices").

Checking out an issue about [inline notice styles](https://github.com/Automattic/wp-calypso/issues/20017) might be relevant.

/cc @jameskoster

**Comment by simison** [comment]
I could send a quick PR to fix this.

Would regular just `<p></p>` suffice? Notice element doesn't seem to have any ARIA attributes that we'd be missing (tho it might have them in future).

If design change would be okay, a quick fix would be make it look either one of these:

![image](https://user-images.githubusercontent.com/87168/33433190-54056daa-d5e3-11e7-9a2f-83d0a1b02152.png)

...or even like `<FormSettingExplanation>`: 
![image](https://user-images.githubusercontent.com/87168/33433226-77309480-d5e3-11e7-9251-7371a489d512.png)

**Comment by drw158** [comment]
In my opinion, it probably shouldn't be a Notice. I haven't viewed the whole context of the page, but you suggestion to just use gray text seems good to me.
