### ISSUE TITLE
Stats: yearly views shows only the graphs for last four years

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#20355]
The title pretty much says it all. When you open up Stats page for a site that has been running and accumulating view stats for longer than 4 years, the previous years are not displayed in the graph.

First reported in 1168265-hc. It seems that in this case it was an intermittent issue, since it has gone away on subsequent loads. 

I was also able to reproduce it for https://en.blog.wordpress.com/ while testing.

#### Steps to reproduce
1. Use a site that has been running for longer than 4 years.
2. Navigate to: https://wordpress.com/stats/year/
3. Notice that only last 4 years are shown.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I used one of my personal sites that have been running for 8 years. The `years` view shows all year as I would expect. As such I am closing this issue with the label `Closed - Not Reproducible`.
If work is scoped and tabled for a milestone, please feel free to re-open this bug.
