### ISSUE TITLE
Themes: navigation under search visually broken on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#20378]
#### Steps to reproduce
1. Starting at URL, using small screen device (<660px): https://wordpress.com/themes/:site
2. See search bar:
    ![image](https://user-images.githubusercontent.com/87168/33455491-e9bae618-d624-11e7-88a5-4abc5f2e95df.png)
3. Tap search:
    ![image](https://user-images.githubusercontent.com/87168/33455504-f33a0a8e-d624-11e7-8f90-88a51539909b.png)

Note icons leaking above search categories.

Note also how placeholder text doesn't fit on small screens. That problem is even bigger via https://wordpress.com/themes
![image](https://user-images.githubusercontent.com/87168/33455443-c7b66772-d624-11e7-82b8-f88b97b8c7a2.png)

#### Browser / OS version

Chrome devtools mobile emulator (iPhone 5)
![image](https://user-images.githubusercontent.com/87168/33455355-77711a46-d624-11e7-92be-d20945277978.png)

**Comment by markpernotto** [comment]
@simison is anyone currently working on this, or is it being referenced in a different ticket? I noticed this problem today, and did a little investigative work to consistently replicate it in an attempt to resolve. Could you please let me know? I'd be happy to show / document my findings with this problem. 
Thank you!

**Comment by simison** [comment]
@markpernotto nope, feel free to grab it!

Here's another good one: https://github.com/Automattic/wp-calypso/pull/20391

You rock!

**Comment by markpernotto** [comment]
@simison - here's what I've figured out so far:

While it does appear that the search categories aren't lining up properly underneath the search bar in your screenshot, I believe the bigger problem is that the search bar isn't 'sticking' to the top of the window in screens smaller than 660px in width. There's also a 'jump' with the search bar upon initial scrolling on screens smaller than 660px in width. I've created two videos documenting these differences:

**When the screen is over 660px:**
![over660px](https://user-images.githubusercontent.com/2965712/35200774-b36c92ce-fec8-11e7-97cf-08d2fa259ca6.gif)
In the above animated GIF, I'm scrolling the page; the search bar 'sticks' to the top of the frame. 

**When the screen is under 660px:**
![under660px](https://user-images.githubusercontent.com/2965712/35200800-fd50c6e4-fec8-11e7-80e2-72c8d14e43d6.gif)
In the above animated GIF, I'm scrolling the page; the search bar (almost) immediately jumps down when the page is scrolled down. Also, the search bar does not 'stick' to the top of the frame.

I think if we resolve the initial 'jump' displayed in the second animated GIF, and make the search bar 'stick' to the top of the frame (as in the >660 px version), this could resolve this issue. However, I wanted to ask if this was, in fact, the desirable outcome, or if it's not necessary to have the search bar 'stick' to the top of the frame. Could you please let me know?

Furthermore, the https://wordpress.com/themes does look considerably different, and the above proposed fixes could conceivably fix that as well.
**Under 660px:**
<img width="627" alt="screen shot 2018-01-21 at 4 46 26 pm" src="https://user-images.githubusercontent.com/2965712/35200918-ba38f578-feca-11e7-8c87-087491a3ddac.png">
**Over 660px:**
<img width="744" alt="screen shot 2018-01-21 at 4 47 32 pm" src="https://user-images.githubusercontent.com/2965712/35200930-ec51c026-feca-11e7-8a27-ef9f9f2e1992.png">

Simplified into an actionable todo list:

1. Search bar 'sticking' to the top of the frame when scrolled (node/JS based)
2. Scrolling drops the search bar when scrolled on screens smaller than 660px
3. wordpress.com/themes search bar doesn't behave properly on screens larger than 660px

Given the three issues mentioned above, I'm not sure we should over-complicate this by adding on #20391; however, I will jump over there to take a look, and comment in that thread.

Please let me know if you have any questions. Thank you.

**Comment by simison** [comment]
>I think if we resolve the initial 'jump' displayed in the second animated GIF, and make the search bar 'stick' to the top of the frame (as in the >660 px version), this could resolve this issue. However, I wanted to ask if this was, in fact, the desirable outcome, or if it's not necessary to have the search bar 'stick' to the top of the frame. Could you please let me know?

Pinging @folletto for a comment. :-)

**Comment by folletto** [comment]
> Furthermore, the https://wordpress.com/themes does look considerably different, and the above proposed fixes could conceivably fix that as well.

> wordpress.com/themes search bar doesn't behave properly on screens larger than 660px

This seems very broken, but I can't reproduce. It seems CSS for logged in and logged out got mushed together. Can you outline the steps to reproduce it?


> Search bar 'sticking' to the top of the frame when scrolled (node/JS based)

Correct. However note that I don't see the issue you have in the screenshot above, when scrolling in production I see this:

![screen shot 2018-01-22 at 13 40 59](https://user-images.githubusercontent.com/4389/35223613-e874a20c-ff79-11e7-82b1-4ee3045604e9.png)

Which is already correct.


> Scrolling drops the search bar when scrolled on screens smaller than 660px

I'm not sure what you mean exactly. If you mean that on small screens (without sidebar) the scrollbar shouldn't stick at the top, then correct. As per above, it seems it's working to me tho.

![screen shot 2018-01-22 at 13 42 35](https://user-images.githubusercontent.com/4389/35223663-1f2f94f0-ff7a-11e7-9bd7-d8c45e387d9e.png)

---

Notice that I can't reproduce in production also the original issue raised in here (apart from the already known lack of blue outline noted in #21325):

![screen shot 2018-01-22 at 13 45 37](https://user-images.githubusercontent.com/4389/35223800-9d32d5ba-ff7a-11e7-97ee-9974d51c14b6.png)


It seems there's something odd with your build. Have you tried rebuilding it, and clearing properly the test between logged in and logged out?

**Comment by markpernotto** [comment]
@folletto, thanks for the direction here. I realized that I did have some files on my local out of sync with the master repo. Apologies for the confusion. I cleared my cache, made sure everything was correctly synced before continuing.

However, I am still experiencing some issues:

>>Furthermore, the https://wordpress.com/themes does look considerably different, and the above proposed fixes could conceivably fix that as well.

>>wordpress.com/themes search bar doesn't behave properly on screens larger than 660px

>This seems very broken, but I can't reproduce. It seems CSS for logged in and logged out got mushed together. Can you outline the steps to reproduce it?

Certainly!

1. Visit http://calypso.localhost:3000/themes/:site - page renders properly. _Please note I included the browser address bar in my screenshot for clarity_:
<img width="1208" alt="screen shot 2018-01-22 at 8 34 25 am" src="https://user-images.githubusercontent.com/2965712/35233762-dc61e1f8-ff53-11e7-805c-e547545cb19c.png">
2. Remove the :site part, landing at: http://calypso.localhost:3000/themes/
For a brief moment, I see this:
<img width="1211" alt="splitsecond" src="https://user-images.githubusercontent.com/2965712/35234766-17d6435c-ff57-11e7-8990-0ce115f66ef1.png">

And then the page renders, upon finishing loading, like this:
<img width="1211" alt="screen shot 2018-01-22 at 8 34 55 am" src="https://user-images.githubusercontent.com/2965712/35234116-dd4fecbc-ff54-11e7-9e5c-0e1a912212ee.png">

The above has been tested and occurs on both Firefox and Google Chrome. I could not find a way to get to http://calypso.localhost:3000/themes/ independently of the above method.


To the other point, regarding the search bar sticking to the top:
>>Search bar 'sticking' to the top of the frame when scrolled (node/JS based)

>Correct. However note that I don't see the issue you have in the screenshot above, when scrolling in production I see this:

>screen shot 2018-01-22 at 13 40 59

>Which is already correct.

If it's not supposed to on screens smaller than 660px, that puts that concern to rest, and won't worry about it any more. If it _is_ supposed to stick to the top of the screen while scrolling, and I've misunderstood, please let me know.

Going back to @simison's original problem, I'll just focus on making sure the search categories display below the search bar when clicked, on screens smaller than 660px. I still see a 'jump' of that search bar when I scroll on that window, and I think that has something to do with this.

Please let me know if you have any questions. Thank you.

**Comment by folletto** [comment]
> Remove the :site part, landing at: http://calypso.localhost:3000/themes/ For a brief moment, I see this [...]

Afaik this is an issue happening only on the development instance of Calypso as it's something related to SSR and logged-in data. However, I'm not 100% sure. Please open a separate issue for this as it's outside the scope of this ticket.

> If it's not supposed to on screens smaller than 660px, that puts that concern to rest, and won't worry about it any more. If it is supposed to stick to the top of the screen while scrolling, and I've misunderstood, please let me know.

It's a rather minor decision, but it maximises the visibility of the themes on smaller screens. So yes, it's currently working as expected.

> I'll just focus on making sure the search categories display below the search bar when clicked, on screens smaller than 660px.

Can you reproduce the issue tho? I can't.

**Comment by markpernotto** [comment]
@folletto, thanks, I'll create a ticket for the /themes/ issue as you've suggested. Also appreciate the clarity on the <660px/search bar issue (that makes perfect sense, btw).

>>I'll just focus on making sure the search categories display below the search bar when clicked, on screens smaller than 660px.

>Can you reproduce the issue tho? I can't.

Here's the most consistent way I've been able to replicate this issue:
In either Chrome or FF:
1. Visit http://calypso.localhost:3000/themes/:site
2. Shrink the viewport to under 660px in size.
3. Scroll down approximately 5-10% of the screen (make sure the search bar is still in view)
4. Click in the search bar
You should see something like this:
<img width="563" alt="screen shot 2018-01-23 at 2 45 43 pm" src="https://user-images.githubusercontent.com/2965712/35304907-32cead98-004c-11e8-83bc-dd6b7b429e1f.png">
The categories appear covered by the search bar. I believe it has something to do with the way the search bar jumps/'drops down' ~25px or so when the page is initially be scrolled.

I think this is inconsistent with the way the same action (clicking in the search bar) is done on screens wider than 660px in width. When I click in those, The categories appear underneath as expected:
<img width="1108" alt="screen shot 2018-01-23 at 2 48 57 pm" src="https://user-images.githubusercontent.com/2965712/35305014-983fc252-004c-11e8-9da2-55f221e27293.png">

@simison, can you please confirm this was the original problem you'd described? I will continue working on a resolution for this. Please let me know if you have any questions.

**Comment by markpernotto** [comment]
>>Remove the :site part, landing at: http://calypso.localhost:3000/themes/ For a brief moment, I see this [...]

>Afaik this is an issue happening only on the development instance of Calypso as it's something related to SSR and logged-in data. However, I'm not 100% sure. Please open a separate issue for this as it's outside the scope of this ticket.

@folletto, @simison Please see #21774 in case I missed anything, thank you.

**Comment by folletto** [comment]
Is this the bug?

![cap-themes-scroll-sticky-search-bug](https://user-images.githubusercontent.com/4389/35339149-bcf4e3c2-0117-11e8-9685-458636338aec.gif)

**Comment by markpernotto** [comment]
@folletto, yes, but if you click on the search input box after you scroll, you'll see that the categories are covered up. That's what I'd interpreted from @simison's original description. Thoughts?

**Comment by folletto** [comment]
Aha! Now I noticed: I was testing on All Sites view, but apparently the above happens like that only on single site view... which might be then related to the banner shown on top. It's possible that the banner addition wasn't taken into account as a variable for the calculation of the search "undocking".

If this guess is correct, it probably need to be able to determine the original position instead of relying on a static variable.

**Comment by jordesign** [comment]
Closing this as no longer relevant after recent improvements to the theme showcase.
