### ISSUE TITLE
Editor: Creating a new post shows a blank text area with no way to enter content.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#20374]
Multiple users have started reporting they're unable to create new posts or pages.

![screen-shot-2017-11-30-at-11-55-38-am](https://user-images.githubusercontent.com/349751/33449538-f28f737e-d5bd-11e7-85b2-39fedaa32345.png)

@samouri could this be React 16-related?

**Comment by ockham** [comment]
> could this be React 16-related?

The upgrade's been merged some 20 hours ago, so I think we would've seen this earlier if it was related...

**Comment by gwwar** [comment]
This bug is only visible in production and not stage.

**Comment by kwight** [comment]
This was "fixed" by merging #20286 . One possible explanation may have been bundling hash collisions with `post-editor.css`.

**Comment by designsimply** [comment]
Noting an earlier report that came in through the forums at Nov 30, 2017, 12:01 PM UTC: https://en.forums.wordpress.com/topic/updating-posts-leads-to-blank-page?replies=21

Also see https://en.forums.wordpress.com/tags/editor

**Comment by darnelldibbles** [comment]
There were 40-50 users who tweeted us about this issue as well.

**Comment by KokkieH** [comment]
Several of the Twitter users mentioned above have since confirmed that it's fixed for them.

**Comment by designsimply** [comment]
@KokkieH, thank you for the follow-up!
