### ISSUE TITLE
Link up happychat for activity log help menu

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#20385]
We need two things:

- When someone clicks on "Help" this should link to chat with JPOP folks
- We need tracks in place for this chat location.
<img width="623" alt="screen shot 2017-11-30 at 2 24 39 pm" src="https://user-images.githubusercontent.com/26996883/33458262-6211ba74-d5da-11e7-9b28-a6959d8ed8d5.png">

Whoever fixes this, please comment with the tracks event name for this event so I can have it on my end.

**Comment by rcoll** [comment]
There are several concerns with this that I'd like to document and maybe we can come up with a better solution.

- When Happychat is unavailable, this button will not appear. This could be a source of confusion for customers.
- Also, from a customer's point of view, I wouldn't expect this particular button to give me a chat opportunity. I would more expect it to take me to some documentation on what a Rewind is.
- There are also technical issues with adding the Happychat button in this specific place. It can be done, but it's likely not quick and easy.

**Questions:**
- Would it make sense to instead link to static documentation on a page which has the Happychat feature as an option instead?
- How critical is it that we provide help in this contextual menu at all?

**Comment by annezazu** [comment]
> Would it make sense to instead link to static documentation on a page which has the Happychat feature as an option instead?

Sadly, this is an option currently as embeddable and unauthorized user chat is a ways off :/ 

> How critical is it that we provide help in this contextual menu at all?

I'd say very critical. I actually built out the banners we have in VP now for when we can't connect that pushes folks to contact support. 

Further, right now, we can't even write documentation on how to fix activity log problems because **I don't know what will cause it to break and I have no steps to offer users to fix any problems.** 

Perhaps, for now, the solution is chat and as we get more information about what breaks and why we can replace it with documentation.

> When Happychat is unavailable, this button will not appear. This could be a source of confusion for customers.

Let's have two links for now then: learn more and get help. 

- Learn more can go to this doc:  http://jetpack.com/support/activity-log/
- Get help can either open up chat OR you could have it redirect to the contact form. I'd prefer it opens chat so we can track the number of folks who ask for help on that page and so it keeps them on the activity log page itself so we can more readily help.

**Comment by dmsnell** [comment]
I'm with @rcoll on this one too about the placement of the help item in the ellipsis menu as I think it's misplaced. If we have strong evidence that there's a specific response people are going to have that leads them there for a specific failure or confusion I'd be open to listen, but putting a chat link there in anticipation seems confusing - or at least, it seems confusing to find a chat link _there_.

@annezazu can you clarify with some specifics about the motivation for wanting this? is it possible that we're wanting one goal but expressing it through another goal?

The ellipsis menu for now has also stepped down in importance as **Rewind** is exposed on the outside of it. Would it be good instead to place a general help button on the page-level _or_ even use guided tour functionality to highlight the existing help/chat button whenever some specific failure condition occurs?

**Comment by rcoll** [comment]
I'm revisiting https://github.com/Automattic/wp-calypso/pull/20642 and curious what the current decision is around this. @MichaelArestad, do you have any suggestion concerning the placement, action, and presentation of a help button on these items? Anyone else have any further comments?

**Comment by MichaelArestad** [comment]
@rcoll can you put the help button in the dropdown for the split button (below download with a line above it if possible?

**Comment by MichaelArestad** [comment]
And as far as context, let's use default happychat button behavior. It's mildly disruptive, but if they need help, that's the way to get it. We need to see what breaks before we have docs in place.

**Comment by rcoll** [comment]
New PR ready for review that solves this: https://github.com/Automattic/wp-calypso/pull/22450 (closed #20642 since the rebase would have been a nightmare)

Reviews are welcome and encouraged.
