### ISSUE TITLE
Link Failed Rewind "Contact Support" button to happychat

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#20386]
When a rewind fails, there is a box with Try Again and Contact support. The latter should open happy chat. Right now, it sends you to VaultPress documentation. First mentioned here https://github.com/Automattic/wp-calypso/issues/20108#issuecomment-347361355

We also need tracking for this in place. Whoever fixes this please include the event name you chose for tracks as a comment here so I can have it on my end.

**Comment by annezazu** [comment]
@eliorivero  did you do this? For some reason I am thinking you did.

**Comment by eliorivero** [comment]
I implemented this in https://github.com/Automattic/wp-calypso/pull/20482

The name events are
`calypso_activitylog_error_banner_backup`
`calypso_activitylog_error_banner_restore`

Will close this since it's fixed.
