### ISSUE TITLE
Reader: Dismissing site recs blocks the site

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#20392]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage.
2. From the list of Recommended Sites, dismiss a site.
3. "This site has been successfully blocked" message is displayed.

#### What I expected
For the site rec to be dismissed, but not blocked.

#### What happened instead
Site rec is blocked instead of just dismissing it.
(Although I'm not sure if this has been actually blocked or the error message being displayed is just incorrect or worded incorrectly.)

![screenshot 2017-11-30 16 05 51](https://user-images.githubusercontent.com/4924246/33461724-883013a0-d5e8-11e7-87b1-3f7344acd76e.png)

Update: I rechecked this and apparently, recommended sites are blocked once a user dismisses them. 

If a user blocks a site, this site should no longer be recommended to them ever. However, the site shouldn't be blocked. They should still show up in their Search results or they should still be able to access this site's stream of posts.

Dismissing doesn't mean "blocking"; it just means "don't recommend this to me again."

**Comment by gwwar** [comment]
Internally this dispatches `READER_SITE_BLOCK` @Automattic/reader what does blocking vs dismissing mean in this case?

**Comment by jancavan** [comment]
I checked this again and apparently, we actually do block a recommended site that a user just dismisses. I don't think we should do this. Dismissing a site recommendation just means, "Don't recommend this to me again" which doesn't necessarily mean "blocking." In Reader, blocking means you also won't be able to view the blocked site's stream of posts. If they just dismiss it, they should still be able to.

**Comment by gwwar** [comment]
@jancavan To clarify requirements, when I dismiss, how long is that recommendation dismissed for?
- Until I refresh?
- Some interval? (Can be a cookie)
- Forever? (Maybe a user pref?)

**Comment by jancavan** [comment]
> To clarify requirements, when I dismiss, how long is that recommendation dismissed for?

It's more logical to dismiss it forever. It shouldn't be recommended to them again, however, that doesn't mean this site won't show up in the Search results. They should still also be able to see this site's stream of posts.

**Comment by gwwar** [comment]
@jancavan do you mind updating the summary with the new requirements? It's always handy to have the top summary accurately reflect the issue needs without needing to read the full thread.

**Comment by bluefuton** [comment]
I wholeheartedly agree that this should be a 'soft block'. We need to do some work on the backend to make this happen.

**Comment by westi** [comment]
We should also consider soft blocking for discover content - p2-p5PDj3-12A
