### ISSUE TITLE
.org Plans: Confirmation page should link to specific sections of the support page

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#204]
On the confirmation page after a successful plan purchase the get started buttons should link to the appropriate section of the support page. Eg

- https://en.support.wordpress.com/setting-up-premium-services/#vaultpress
- https://en.support.wordpress.com/setting-up-premium-services/#akismet
- https://en.support.wordpress.com/setting-up-premium-services/#polldaddy

There are also 2 links at the bottom:
![screen shot 2015-10-14 at 11 24 30 am](https://cloud.githubusercontent.com/assets/3220162/10493451/2b373f94-7266-11e5-8d0f-f74f53f14355.png)

The first one goes to `http://jetpack.me/support/` and the second one goes to `http://jetpack.me/contact-support/`.  

Instead the first one should go to `https://en.support.wordpress.com/setting-up-premium-services/` and the second one to `https://en.support.wordpress.com/premium-services/`

Ideally we would consolidate all the documentation into Jepack.me, but that might take a bit longer.

**Comment by designsimply** [comment]
Tested and I can confirm the support links are still the same, but I didn't see any get started buttons (the page design must have been changed after this ticket was opened). The support links have different wording but still point to the same links as noted above. ([41s](https://cloudup.com/c6uOuCN-ZJQ))

Currently the support buttons links are:

* "Ask a question" → https://jetpack.me/contact-support/
* "Search our support site" → https://jetpack.me/support/

![screen shot 2016-04-28 at 18 18 53](https://cloud.githubusercontent.com/assets/1119271/14906049/7a1839d4-0d74-11e6-9532-06141da96361.png)
<sup>Seen at https://wordpress.com/checkout/thank-you/wildly.disambiguously.com/18148703 using Firefox 46.0 on Mac OS X 10.11.4</sup>

@v18, do you still think the links for "Ask a question" and "Search our support site" need to be changed? If not, feel free to close this one!

**Comment by ryelle** [comment]
@v18 I'm working on this page for auto-configuration (and as part of #5892) – should these links be updated, or is Jetpack support where they should go?

**Comment by v18** [comment]
@ryelle - the links should still go to the various en.support.wordpress.com I liked above, since the docs aren't yet available on jetpack.com
