### ISSUE TITLE
View Site: Editing from the "view site" section leads to blank page after exiting the editor

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#20400]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/view
2. Select a site to open the "View Site" section.
3. On a post or page on the site, select "Edit" to open it in the editor.
4. In the editor, select the back arrow in the top left.

#### What I expected

I expected to exit the editor and return to the "View Site" section.

#### What happened instead

The URL in the address bar showed the "View Site" URL, but I saw a blank page and a console error: `Uncaught TypeError: Cannot read property 'unbind' of null`

#### Browser / OS version

Mac OS 10.12.6, Chrome 62

#### Screenshot / Video

View Site section:

![screenshot 2017-12-01 09 31 37](https://user-images.githubusercontent.com/8658164/33476740-fa06bd70-d67a-11e7-9140-2c6ae80b7da9.png)

In the editor:

![screenshot 2017-12-01 09 31 49](https://user-images.githubusercontent.com/8658164/33476755-0a8c696a-d67b-11e7-962b-46fcadf86070.png)

Blank screen:

![screenshot 2017-12-01 09 32 13](https://user-images.githubusercontent.com/8658164/33476766-14fe4a26-d67b-11e7-87da-c4fd127f0334.png)

#### Context / Source
#dogfooding #flowsharing

**Comment by lancewillett** [comment]
Assigning to @mattsherman for triage (and possible fix, if appropriate).

**Comment by rachelmcr** [comment]
This should be fixed by either https://github.com/Automattic/wp-calypso/pull/20499 or https://github.com/Automattic/wp-calypso/pull/20491. Closing this issue as there are duplicate reports being fixed.
