### ISSUE TITLE
Sites do not load when clicking 'My Sites'

### ISSUE THREAD

**Issue by pauloeaquino** [Automattic/wp-calypso#20413]
A user is reporting that when they click on ‘My Sites’, nothing ever loads, therefore preventing access to any of their sites. It continues to display ‘Loading my sites’.  I was able to confirm this after using SU on the user’s account.

Ticket: 816070-zen

#### Steps to reproduce
1. SU into the user's dashboard.
2. Click 'My sites'

#### What I expected
I expected the user's sites to be displayed properly.

#### What happened instead
Nothing loads. It continues to display 'Loading my sites'.

**Comment by designsimply** [comment]
@pauloeaquino, any chance you can include OS/browser details for both the reporter as well as from your testing? Any time there's something funny going on with page loading, it's good basic troubleshooting to rule out a browser issue. See https://en.support.wordpress.com/browser-issues/ for a good place to start.

**Comment by pauloeaquino** [comment]
@designsimply, sure, here are my details from testing:
OS: macOS High Sierra 10.13.1
Broswer: Chrome 62.0.3202.94 | 1258 x 564

The user said they tried three different browsers and right now we're currently waiting for their reply to provide their specific browser info.

**Comment by lancewillett** [comment]
My best guess for this one is a temporary outage (could be in fetching data over the API, so network connection). Most likely resolved on its own and not a specific bug in Calypso.

Feel free to re-open if you see a larger pattern (many people reporting it).
