### ISSUE TITLE
Store: PropTypes warning on store pages

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#20417]
I'm currently seeing the following error in my console when running `master`, on any store page:

> Warning: Component TextField declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?`

The debug log makes it seem like it's coming from `promotion-models`.

<img width="997" alt="screen shot 2017-12-01 at 9 12 19 am" src="https://user-images.githubusercontent.com/689165/33494333-c26d12cc-d677-11e7-9de4-d3761a354fb7.png">

**Comment by coderkevin** [comment]
I saw this as well, but assumed it was an error within `TextField`, a global component. I'll investigate.

**Comment by coderkevin** [comment]
Fixed in #20455
