### ISSUE TITLE
Notifications: odd "flash" on small screen widths

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2042]
Steps to reproduce:

1. Go to https://wordpress.com/ using Chrome/WebKit with a small-width window (<960px should do it)
1. Click the bell in the toolbar
1. Click on several different notifications and click the "Back" link after each oen
1. Watch for a flash after clicking any notification

<strong>Result:</strong> the notifications "flash" on transition from the notifications list to an individual notification

/hat tip @kraftbj for the original report

**Comment by lancewillett** [comment]
Closing this one as edge-case.
