### ISSUE TITLE
Themes: links to /themes/themename do not work

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#20423]
#### Steps to reproduce
1. Attempt to go to any theme's showcase page using the plural "themes" in the URL path, rather than just "theme". For example https://wordpress.com/themes/textbook

#### What I expected

I expect it to redirect to the singular version of the URL -- https://wordpress.com/theme/textbook -- since the old URL format used the plural /themes/. I think it used to redirect, but I may be incorrect.

#### What happened instead

I just got a blank/404 page:

![Image](https://cldup.com/YnQ8sj_eWo.png)

Unfortunately, this link format is used in pretty much every single Automattic theme, and the links are visible in places like the WordPress.org theme showcase (eg. https://wordpress.org/themes/dyad/)

I noticed there was a similar issue with the /design URL (#20416) -- possibly related?

Hat tip to @annezazu who reported this via Slack (interal ref: p1512154183000077-themes).

**Comment by lancewillett** [comment]
Investigating with @samouri to see if this is related to https://github.com/Automattic/wp-calypso/pull/20267 user bootstrapping changes. About 8 days ago.
