### ISSUE TITLE
Create a fall back error message for activity log failures

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#20430]
<img width="1060" alt="screen shot 2017-12-01 at 2 10 09 pm" src="https://user-images.githubusercontent.com/26996883/33507291-d0e2e044-d6a8-11e7-95bc-fb55856bf688.png">

I happened to find a new JS error that broke activity log which made me think we should have a default fall back error message to show folks when they find errors that don't match what we have tracked. 

Perhaps we could have a drop down menu option like we do with backups? 

<img width="623" alt="33458262-6211ba74-d5da-11e7-9b28-a6959d8ed8d5" src="https://user-images.githubusercontent.com/26996883/33507377-41458170-d6a9-11e7-9a9b-2f5611061dc3.png">

The options could be "Attempt Resync, Help". I also think we should explain here why sync failing is a problem for activity log more.

**Comment by singerb** [comment]
If we simply want to stop displaying the error message here, or move it into a less accessible place, that's all UI work. If we instead want Rewind to send a more generic error message with these events, I can make that change on the Rewind side. Not sure what the thinking is.

**Comment by eliorivero** [comment]
I see three issues in one here plus we're no longer calling this event sync but backup:

#### a fallback error message
While we would have to be able to reproduce the first one, I think a fallback message could be just "Failed backup. We're trying again".

#### a new entry in ellipsis menu to retry backup
This would be something completely new and I don't think users should worry about this. Also, some might be a bit distressed knowing their data is copied to WordPress.com until they are reassured that their data is safe and private. This is quite technical and don't think we should do this for users.
It's also something that we should take care privately in the shadows.

#### explain why the backup failed
Perhaps the backup failure shouldn't be show the first time it fails. Maybe it could be after the second or the third failure to avoid showing something that would stress users out, something that could be solved on a second backup attempt.

**Comment by annezazu** [comment]
> a fallback error message
> While we would have to be able to reproduce the first one, I think a fallback message could be just "Failed backup. We're trying again".

Works for me. 

> a new entry in ellipsis menu to retry backup
> This would be something completely new and I don't think users should worry about this. Also, some might be a bit distressed knowing their data is copied to WordPress.com until they are reassured that their data is safe and private. This is quite technical and don't think we should do this for users.
> It's also something that we should take care privately in the shadows.

Is there a reason we are afraid to hide what's actually happening? This tells me we need to better introduce this feature then.

> explain why the backup failed
> Perhaps the backup failure shouldn't be show the first time it fails. Maybe it could be after the second or the third failure to avoid showing something that would stress users out, something that could be solved on a second backup attempt.

For VaultPress, this is exactly what we did. We'd only notify after a certain period of time. Curious what this should look like though since it's "real time" for a reason.

**Comment by eliorivero** [comment]
With https://github.com/Automattic/wp-calypso/pull/22453 in place, it's now good to close this. We have a generic/fallback message and a button to take action.
