### ISSUE TITLE
Notifications: lack of proper line breaks make long comments hard to read

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2044]
Raised by @alternatekev 

When reading a comment:

<img width="413" alt="screen shot 2015-09-08 at 9 55 02 am" src="https://cloud.githubusercontent.com/assets/1084656/9740031/f0f737b6-560f-11e5-8b30-6ab5e0b31a2e.png">

not having a proper line break between his paragraphs there makes it hard to read longer comments. Can we update notifications somehow to show the true line break there?

**Comment by lancewillett** [comment]
Raised today again by @m 

> Multi-paragraph #notifications currently run into each other, which makes them harder to read and look kind of broken. Here’s a snippet of a long comment from my blog in notification view, and on the blog itself. (And for completeness, the mobile view of it.)

![img_7197](https://cloud.githubusercontent.com/assets/66797/14827263/6643b896-0b96-11e6-90da-1bb803a76f31.jpg)
<img width="472" alt="screen shot 2016-04-26 at 10 18 06 am" src="https://cloud.githubusercontent.com/assets/66797/14827262/66427878-0b96-11e6-976d-76ca0cffa2d9.png">
<img width="486" alt="screen shot 2016-04-26 at 10 20 52 am" src="https://cloud.githubusercontent.com/assets/66797/14827264/6646fc36-0b96-11e6-9e35-965437d59b94.png">

**Comment by lancewillett** [comment]
I agree that really long comments are difficult to read, CC @drw158 in case there are easy, quick fixes to add in paragraph spacing — maybe just a bottom margin?

**Comment by drw158** [comment]
This isn't as easy as one would think. Currently, all of the text is lumped into one `div`, and the "paragraphs" are separated with `br` elements. We could insert 2 `br` elements instead of one I suppose. That might be the quickest fix.

@dmsnell is working on a replacement for the notifications client that might be able to fix this, but there is no timeline for that. It's a side project.

**Comment by catehstn** [comment]
Raised again by @m this time on iOS - it's affecting all platforms, and whilst irritating on the web it's even more annoying on mobile. @roundhill is this something you can look into as part of your other work on comments?

**Comment by dmsnell** [comment]
all, we have deployed a server-side change to split the paragraphs of text. please check to see if this is still a problem. it _should_ be solved.

please reopen if still a problem. we may have another issue going on too if its fixed in some places but not in other.

**Comment by designsimply** [comment]
To test, I added a long comment with several paragraphs via Reader:

![screen shot 2017-05-23 at tue may 23 10 39 58 am](https://cloud.githubusercontent.com/assets/1119271/26365448/e4c06690-3fa4-11e7-89b0-cb6d77cfeffd.png)
<sup>Seen at https://wordpress.com/read/feeds/42873943/posts/1469162927#comments using Safari 10.1 on Mac OS X 10.12.4.</sup>

Then I went to https://wordpress.com/ and viewed the comment in the notifications panel and it LGTM!

![screen shot 2017-05-23 at tue may 23 10 43 53 am](https://cloud.githubusercontent.com/assets/1119271/26365468/f2578f40-3fa4-11e7-9768-491ed33394be.png)
<sup>Seen at https://wordpress.com/ using Firefox 53.0.2 on Mac OS X 10.12.4.</sup>

I also checked with WPAndroid alpha-58 and WPiOS 7.7.20170522 and WPDesktop 2.5.0-beta2 and paragraphs in notifications look good in those apps as well.

<img alt="img_1195" src="https://cloud.githubusercontent.com/assets/1119271/26366460/6db193f4-3fa8-11e7-9d7a-3242fb32a57b.PNG" width="200" /> <img alt="screenshot_20170523-104702" src="https://cloud.githubusercontent.com/assets/1119271/26366464/704b5e10-3fa8-11e7-8689-aa0b7864f121.png" width="200" /> <img alt="screen shot 2017-05-23 at tue may 23 10 52 14 am" src="https://cloud.githubusercontent.com/assets/1119271/26366469/7b130c58-3fa8-11e7-8199-d0de295d254a.png" width="400" />
