### ISSUE TITLE
Use proper ES2015 module import/export syntax

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#20442]
This is just a **tracking issue** so see the milestone for more information

 - [ ] login/controller.js
 - [ ] mailing-lists/controller.js
 - [ ] mailing-lists/utils.js
 - [ ] me/controller.js
 - [ ] me/constants.js
 - [ ] signup/controller.js
 - [ ] signup/utils.js
 - [ ] auth/controller.js
 - [ ] devdocs/service.js
 - [ ] post-editor/controller.js
 - [x] jetpack-connect/controller.js (#20531)
 - [ ] components/happychat/autoscroll.js
 - [ ] components/share-button/services.js
 - [ ] components/happychat/scrollbleed.js
 - [ ] me/event-recorder/index.js
 - [ ] me/form-base/index.js
 - [ ] me/next-steps/steps.js
 - [ ] me/help/controller.js
 - [ ] me/account/controller.js
 - [ ] me/notification-settings/controller.js
 - [ ] components/post-schedule/utils.js
 - [ ] my-sites/domains/paths.js
 - [ ] me/security/controller.js
 - [ ] me/billing-history/controller.js
 - [ ] components/tinymce/i18n.js
 - [ ] me/billing-history/table-rows.js
 - [ ] me/purchases/controller.jsx
 - [ ] my-sites/invites/utils.js
 - [ ] my-sites/ads/controller.js
 - [ ] my-sites/media/controller.js
 - [ ] me/purchases/paths.js
 - [ ] me/purchases/titles.js
 - [ ] my-sites/plans/controller.jsx
 - [ ] me/concierge/controller.js
 - [ ] my-sites/preview/controller.js
 - [ ] my-sites/paladin/controller.js
 - [ ] my-sites/checkout/controller.jsx
 - [x] my-sites/pages/helpers.js
 - [ ] my-sites/pages/placeholder.jsx
 - [ ] my-sites/people/controller.js
 - [ ] my-sites/posts/controller.js
 - [ ] my-sites/domains/controller.jsx
 - [ ] my-sites/stats/controller.jsx
 - [ ] state/http/index.js
 - [ ] state/jetpack-connect/selectors.js
 - [x] state/current-user/constants.js
 - [ ] state/jetpack-sync/actions.js
 - [ ] signup/config/steps.js
 - [ ] signup/config/step-components.js
 - [ ] state/jetpack-sync/selectors.js
 - [ ] state/followers/actions.js
 - [ ] lib/abtest/active-tests.js
 - [ ] my-sites/site-settings/settings-controller.js
 - [ ] lib/domains/assembler.js
 - [ ] lib/domains/constants.js
 - [ ] lib/analytics/ad-tracking.js
 - [ ] lib/embeds/actions.js
 - [ ] lib/feed-post-store/constants.js
 - [ ] lib/feed-post-store/display-types.js
 - [ ] lib/analytics/super-props.js
 - [ ] lib/feed-stream-store/constants.js
 - [ ] lib/feed-stream-store/feed-stream-cache.js
 - [ ] lib/cart-values/cart-items.js
 - [ ] lib/localforage/localforage-bypass.js
 - [ ] lib/formatting/index.js
 - [ ] lib/cart-values/index.js
 - [ ] lib/products-values/index.js
 - [x] lib/countries-list/index.js
 - [ ] lib/route/path.js
 - [ ] lib/credit-card-details/index.js
 - [ ] lib/form-state/index.js
 - [ ] lib/credit-card-details/masking.js
 - [ ] lib/impure-lodash/index.js
 - [ ] lib/infinite-list/actions.js
 - [ ] lib/credit-card-details/validation.js
 - [ ] lib/data-poller/index.js
 - [ ] lib/siftscience/index.js
 - [ ] lib/touch-detect/index.js
 - [ ] lib/detect-history-navigation/index.js
 - [ ] lib/signup/cart.js
 - [ ] lib/notification-settings-store/toggle-state.js
 - [x] lib/like-store/utils.js
 - [ ] lib/tree-convert/tree-traverser.js
 - [ ] lib/oauth-store/constants.js
 - [ ] lib/purchases/assembler.js
 - [ ] lib/signup/step-actions.js
 - [ ] lib/url/index.js
 - [ ] lib/url/support.js
 - [ ] lib/paths/index.js
 - [ ] lib/user/shared-utils.js
 - [ ] lib/site/utils.js
 - [ ] lib/store-transactions/index.js
 - [ ] lib/viewport/index.js
 - [ ] components/data/media-list-data/utils.js
 - [ ] lib/wporg/index.js
 - [ ] lib/plugins/notices.jsx
 - [ ] lib/preferences/constants.js
 - [ ] my-sites/checkout/checkout-thank-you/utils.js
 - [ ] my-sites/site-settings/settings-discussion/controller.js
 - [ ] my-sites/site-settings/settings-security/controller.js
 - [ ] my-sites/domains/domain-management/domain-management.jsx
 - [ ] my-sites/site-settings/settings-traffic/controller.js
 - [ ] my-sites/site-settings/settings-writing/controller.js
 - [ ] my-sites/domains/domain-management/controller.jsx
 - [ ] my-sites/plans/current-plan/controller.jsx
 - [ ] my-sites/sharing/buttons/preview-widget.js
 - [ ] signup/steps/survey/verticals.js
 - [ ] state/reader/posts/display-types.js
 - [ ] state/plugins/premium/actions.js
 - [ ] state/reader/watermarks/watermark-schema.js
 - [ ] state/plugins/premium/selectors.js
 - [ ] state/plugins/wporg/actions.js
 - [ ] state/plugins/wporg/selectors.js
 - [ ] state/posts/likes/schema.js
 - [x] lib/cart/store/cart-analytics.js
 - [ ] lib/mixins/url-search/index.js
 - [ ] state/sites/plans/assembler.js
 - [ ] lib/domains/email-forwarding/index.js
 - [ ] lib/domains/google-apps-users/index.js
 - [ ] lib/domains/wapi-domain-info/assembler.js
 - [ ] lib/domains/whois/assembler.js
 - [ ] lib/domains/whois/constants.js
 - [ ] lib/domains/whois/utils.js
 - [ ] lib/media-serialization/strategies/index.js
 - [ ] lib/wp/sync-handler/constants.js
 - [ ] lib/upgrades/actions/index.js
 - [ ] components/tinymce/plugins/wpcom-view/views.js
 - [ ] extensions/woocommerce/state/sites/coupons/handlers.js
 - [ ] extensions/woocommerce/state/sites/promotions/handlers.js
 - [ ] extensions/woocommerce/state/sites/review-replies/handlers.js
 - [ ] extensions/woocommerce/state/sites/reviews/handlers.js
 - [ ] extensions/woocommerce/woocommerce-services/views/packages/input-filters.js
 - [ ] extensions/woocommerce/state/sites/settings/general/handlers.js

**Comment by samouri** [comment]
I've created a codemod that should help us attack this list https://github.com/Automattic/calypso-codemods/pull/1

**Comment by samouri** [comment]
I used webpack to find most of the erroring files. It could be best to start with these:
```
client/components/post-schedule/utils.jsx
client/config.jsx
client/lib/analytics/ad-tracking.jsx
client/lib/cart-values.jsx
client/lib/cart/store/cart-analytics.jsx
client/lib/countries-list.jsx
client/lib/credit-card-details.jsx
client/lib/data-poller.jsx
client/lib/domains/assembler.jsx
client/lib/domains/constants.jsx
client/lib/domains/email-forwarding.jsx
client/lib/domains/google-apps-users.jsx
client/lib/domains/whois/utils.jsx
client/lib/feature-detection.jsx
client/lib/feed-post-store/actions.jsx
client/lib/feed-post-store/constants.jsx
client/lib/feed-post-store/display-types.jsx
client/lib/feed-stream-store/constants.jsx
client/lib/formatting.jsx
client/lib/i18n-utils.jsx
client/lib/impure-lodash.jsx
client/lib/like-store/actions.jsx
client/lib/media-serialization.jsx
client/lib/media/store.jsx
client/lib/media/utils.jsx
client/lib/paths.jsx
client/lib/plugins/utils.jsx
client/lib/posts/utils.jsx
client/lib/route.jsx
client/lib/route/path.jsx
client/lib/shortcode.jsx
client/lib/signup/actions.jsx
client/lib/signup/step-actions.jsx
client/lib/site/utils.jsx
client/lib/sites-list/actions.jsx
client/lib/store-transactions.jsx
client/lib/touch-detect.jsx
client/lib/upgrades/actions.jsx
client/lib/url.jsx
client/lib/url/support.jsx
client/lib/users/actions.jsx
client/lib/viewport.jsx
client/me/purchases/paths.jsx
client/my-sites/domains/paths.jsx
client/my-sites/invites/utils.jsx
client/signup/config/flows.jsx
client/signup/utils.jsx
client/state/current-user/constants.jsx
client/state/jetpack-connect/selectors.jsx
client/state/jetpack-sync/actions.jsx
client/state/plugins/premium/actions.jsx
client/state/plugins/premium/selectors.jsx
client/state/plugins/wporg/actions.jsx
client/state/plugins/wporg/selectors.jsx%
```

**Comment by dmsnell** [comment]
Closing because this was solved in a plethora of small PRs
