### ISSUE TITLE
Store: Invalid URL and stuck progress bar when renewing a domain

### ISSUE THREAD

**Issue by rads** [Automattic/wp-calypso#20440]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com
2. Click "My Site"
3. In the expired domain notification on the left side, click on the "Renew' button to go to the checkout page
4. Purchase the renewal using a new credit card

#### What I expected

After the purchase is complete:
- The progress bar should go away.
- I should be redirected to a new page.
- The URL should have an actual purchase ID rather than a placeholder.

#### What happened instead

- Progress bar is stuck at the end.
- No redirect.
- Placeholder in URL.

#### Browser / OS version

macOS High Sierra 10.13.1
Safari 11.0.1

#### Screenshot / Video

<img width="1392" alt="wordpress com 2017-12-02 13-35-08" src="https://user-images.githubusercontent.com/11401/33519988-d4661d6c-d766-11e7-995c-1f4d0663bca9.png">

#### Context / Source

My account had an expired domain, rads.blog, which I was prompted to renew through an email. I logged in using the email login link.

There were no JavaScript errors in the Safari console.

#user-report a.k.a. #reallife #journey 😆

**Comment by rachelmcr** [comment]
Thanks for the report! This looks like another case of https://github.com/Automattic/wp-calypso/issues/15973; closing as a duplicate and adding a comment with the details included here.
