### ISSUE TITLE
Gravatar User Unable to Login via Google

### ISSUE THREAD

**Issue by NujabesSoul** [Automattic/wp-calypso#20469]
## Summary
A Gravatar user attempting to login via Google isn't able to click the button. Upon them inspecting the page, they found it's disabled for them. Would there be a reason for this?

#### Steps to reproduce
Haven't been able to reproduce this issue

#### What I expected
Ability to click "Continue with Google" and login via Google.

#### What happened instead
Unable to click the button as it shows itself as disabled.

#### Browser / OS version
They say they're on the latest Chrome version.

#### Screenshot / Video

![Image from user](https://woothemes.zendesk.com/attachments/token/fmaYtIEEAtkrpXJD3bmdc4lAz/?name=Screen+Shot+2017-11-29+at+10.51.24.png)

#### Context / Source

- Ticket ID / Forum thread ID / Chat ID: [815327-zen](https://woothemes.zendesk.com/agent/tickets/815427)

**Comment by stephanethomas** [comment]
I'm going to close that issue @NujabesSoul as I wasn't able to reproduce it, and we didn't really receive any other report about that particular problem. I suspect it was a transient error, but if not feel free to reopen it.
