### ISSUE TITLE
Editor: navigating away from editor throws error

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#20470]
#### Steps to reproduce
Go to editor and then navigate away from it (ie back). It will throw the following error:

![image](https://user-images.githubusercontent.com/4988512/33564127-095771a6-d91a-11e7-9f99-1b8c6019d377.png)

@aduth pointed out that we might be destroying the editor instance sooner than calling the `.unbind` on it which could cause this. I set breakpoints in [#](https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/index.jsx#L344) and [#](https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/media/drop-zone.jsx#L51) and indeed, it's the case. `editor.getWin()` returns `null`.

This bug is interesting because there was no code change (afaik) related to these lines. @ockham suggested it might be due to upgrading to React 16. I've [read](https://github.com/facebook/react/issues/11106) they changed something about `componentWillUnmount` behavior so maybe.

**Comment by designsimply** [comment]
Attention on this issue might also help with solving the problem where prompts to restore/discard changes happen even if there have been no changes. See  https://github.com/Automattic/wp-calypso/issues/9833.

**Comment by alisterscott** [comment]
Does this have any customer functional impact besides the console error? Console errors aren't great, but unless this directly impacts the customer experience I wouldn't rate this as High IMO.

**Comment by lamosty** [comment]
Good question. For me, it's possible to use Calypso after getting this error. However, if the events are not unbind and customers use Calypso for longer periods of time navigating between posts (which I think people usually do), it might create slow-downs and issues.

**Comment by aduth** [comment]
I've noticed a partial refresh when navigating away from the editor, which might be caused by this error.

**Comment by lamosty** [comment]
Fixed by #20491
