### ISSUE TITLE
Month selector: arrow pointing to the other side in RTL languages

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#20476]
Change site to RTL and go to Traffic:

<img width="218" alt="captura de pantalla 2017-12-04 a la s 11 45 05" src="https://user-images.githubusercontent.com/1041600/33567432-ca83073c-d8e8-11e7-9c2c-6d2a4c7f0fb2.png">

Issues:

- `Traffic` is not translated cc @yoavf 
- the arrow for the previous month is pointing the opposite way @samouri 

We initially noticed this in the Activity Log since we're using this component too.

**Comment by samouri** [comment]
@eliorivero: which file does this affect? 
I'm in the git blame for formatting the file, but i don't know anything about it.  We will need to go back an extra commit or two to find someone more knowledgeable about the component

**Comment by yoavf** [comment]
> Traffic is not translated cc @yoavf
Fixed this on the GP side, this string was hidden. It will be translated in next week's kit.
