### ISSUE TITLE
Framework: overlap of dashboard notices / banners

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2047]
Raised by @jeffgolenski 

Hey friends,

Whilst going through and working in calypso I noticed there was an overlap in the notifications.

I had removed an obsolete site I no longer needed, and then quickly moved on to managing another self-hosted site connected via jetpack. While managing the latter site, the notification confirming the former site had been deleted, appeared. It appeared while I was managing the plugins of the second site and made the notifications overlap:

![screen shot 2015-11-18 at 6 51 29 pm](https://cloud.githubusercontent.com/assets/214813/11258272/be40e814-8e25-11e5-9fe1-de8e0a510fa1.png)

Perhaps an edge case and possibly not a big deal since they can dismiss these banners, but as users get familiar with the UI here and can quickly navigate, it may be a bit annoying to them if they see this.

Cheers!

**Comment by lancewillett** [comment]
Feel free to re-open this if you see it again in the future — notices have received a rework since.
