### ISSUE TITLE
Month and Yearly Stats do not appear

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#20487]
This appears to be a bug, but is perhaps not affecting all WordPress.com users. I've replicated this on a WordPress.com Simple site as well as WordPress.com Atomic site.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Click on "Months" (https://wordpress.com/stats/month/) or "Years" (https://wordpress.com/stats/year/)

#### What I expected
The bar graph for Months and Years should appear based on the data there. These graphs appear properly from the WP Admin Stats page: https://cloudup.com/cHVwT3ewfEM

#### What happened instead
The stats just do not appear within the bar graph

#### Browser / OS version
Safari Version 11.0.1 (13604.3.5)
Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

#### Screenshot / Video
Here's a GIF of what I observed: https://cloudup.com/co33TngXnUM

#### Context / Source
This issue came up via a #user-report but I also observed this issue on one other user's site shortly after

Follow-up Ticket here: 828911-zen

**Comment by RealCarFax** [comment]
The second site I've observed this on is here (though this is not the reason the user connected): 1207598-hc

**Comment by rachelmcr** [comment]
I saw this once on one of my own sites, but as soon as I opened the console to check for errors the issue resolved itself (with no errors showing in the console).

@catehstn just reported the same issue. In her case, she visited My Sites > Blog Posts > Stats for a single post, and the Weeks/Months/Years chart didn't load. If she repeated those steps for the same post, the chart loaded. However, the issue was repeated for each different post she checked on her site.

**Comment by pauljacobson** [comment]
This issue has also come up in 1110594-zen where the user's yearly stats just don't load at all. Monthly, Weekly, and Daily stats load almost instantly.

![](http://cld.wthms.co/f2hEnF+)

In this case, the user also noted that this issue started occurring a few months ago. I've asked for a more specific time-frame in the hope that there's a cause that arose around that time.

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue on my test sites or on any of the sites in the customer reports here. I'm closing this issue, but please reopen with steps to reproduce if you are still seeing this happen.
