### ISSUE TITLE
 Plans: Let users "cancel" by downgrading on /plans or /purchases 

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#2048]
Raised by @breezyskies 
Currently there is not a way for users to self-downgrade from a higher plan to a lower plan. The only way to go from Business to Premium is to contact support. The user does have the ability to cancel the Business plan from /purchases but this reverts them back to the free plan. 
![37f8073e-8772-11e4-9d2d-1fe2518bf42d](https://cloud.githubusercontent.com/assets/150348/12059316/bf4624b4-af0d-11e5-8b04-8b632c5c0f84.png)

from @justinkropp 

> Surfacing the ability to downgrade/cancel is important. It shows a level of trust with the user.  

We could also build this in at /purchases allowing the user to cancel their current plan and downgrade on renewal.

**Comment by BandonRandon** [comment]
cc @melanieharari

**Comment by supernovia** [comment]
As far as I can tell, there's no way for users to cancel anything but Private Registration.
