### ISSUE TITLE
Activity Log: timeline is not broken on a rewind

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#20483]
<img width="491" alt="captura de pantalla 2017-12-04 a la s 15 18 51" src="https://user-images.githubusercontent.com/1041600/33576765-8dab7330-d906-11e7-9309-15094d093f3f.png">

<img width="290" alt="captura de pantalla 2017-12-04 a la s 15 20 35" src="https://user-images.githubusercontent.com/1041600/33576827-b427432c-d906-11e7-8ebd-e1cfd305083e.png">

**Comment by eliorivero** [comment]
@MichaelArestad does this still apply now that we no longer have discarded events?

**Comment by MichaelArestad** [comment]
Nooooooooooooope. Case closed!
