### ISSUE TITLE
Preview of gallery not visible when using plugin WP Gallery Custom Links

### ISSUE THREAD

**Issue by nielslange** [Automattic/wp-calypso#20494]
#### Steps to reproduce

1. Install plugin [WP Gallery Custom Links](https://wordpress.org/plugins/wp-gallery-custom-links/)
2. Create a page with a gallery

#### What I expected

- The preview of the gallery is visible in both _Calypso_ and _/wp-admin_.

#### What happened instead

- The preview of the gallery is only visible in _/wp-admin_, but not in _Calypso_.

#### Browser / OS version

- macOS 10.13.1 / Chrome 62.0.3202.94

#### Screenshot / Video

n/a

#### Context / Source

The customer reported that the gallery preview didn't work. After analyzing this issue I found out that it was caused by the plugin [WP Gallery Custom Links](https://wordpress.org/plugins/wp-gallery-custom-links/).

**Comment by rachelmcr** [comment]
Closing as the current editor behavior will be superseded by Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
