### ISSUE TITLE
Editor: link editing box appears above editor toolbar

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#20496]
1. Create a post with a single link:

![image](https://user-images.githubusercontent.com/1277682/33597608-df83fbbe-d997-11e7-8dc8-301249dafc75.png)

2. Click on the link box to open the editing area, then click the post editor toolbar and the dropdowns appear under the link box:

<img width="300" alt="edit_post_ _testy_blog_ _wordpress_com" src="https://user-images.githubusercontent.com/1277682/33597513-92e55c58-d997-11e7-99b0-5febfa2847be.png">

#### Browser / OS version

Chrome, MacOS

**Comment by alisterscott** [comment]
Confirmed still an issue.

#bug-scrub #pre-gutenburg-bug-purge
