### ISSUE TITLE
.org Plans: no "Registration Keys" page

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#205]
Steps to reproduce:
1. Purchase a .org Plan
2. Receive an email with your Akismet and VaultPress keys
3. Ignore those, you don't have time to deal with this right now.
4. A few days later, you forgot about the email, and go to https://wordpress.com/my-upgrades , looking for your keys.

Result: No keys anywhere.

**Comment by designsimply** [comment]
Aside: noticed that https://wordpress.com/my-upgrades now redirects to https://wordpress.com/purchases

Tested and confirmed I couldn't find a way to look up my Akismet and VaultPress keys at https://wordpress.com/ after purchasing Jetpack Premium.

Here's how a purchase I made today looks in the `/purchases` list:

![screen shot 2016-04-29 at fri apr 29 5 12 37 pm](https://cloud.githubusercontent.com/assets/1119271/14932032/25141fe2-0e2e-11e6-88a5-7876eef82db7.png)
<sup>Seen at https://wordpress.com/purchases using Chrome 50.0.2661.86 on Mac OS X 10.11.4</sup>

And here's how that purchase looks when clicked:

![screen shot 2016-04-29 at fri apr 29 5 12 44 pm](https://cloud.githubusercontent.com/assets/1119271/14932035/2b0dd050-0e2e-11e6-8230-7ed780cf56a0.png)
<sup>Seen at https://wordpress.com/purchases/wildly.disambiguously.com/6041346 using Chrome 50.0.2661.86 on Mac OS X 10.11.4</sup>

**Comment by rickybanister** [comment]
New design: p6TEKc-17s

cc @johnHackworth
