### ISSUE TITLE
Post status not updating in Desktop app

### ISSUE THREAD

**Issue by nishanttotla** [Automattic/wp-calypso#2051]
When I create a draft and save on the desktop app, it saves fine but doesn't show under the list of drafts unless I restart the app. On the other hand, a post that appears as a draft continues to do so even after clicking publish. Things are set right only by restarting the app.

The web version shows the correct status though. I think #1856, #1897, and #1555  might be related.

**Comment by lancewillett** [comment]
Hi, could you please tell us your OS version and which version of the desktop app you're using? Thank you.

**Comment by nishanttotla** [comment]
Sorry for the late response, here are the details.

OS: OSX Yosemite 10.10.5
Wordpress: 1.2.1 Release

The issue is persisting, and I recently noticed similar issues with the web app too (not reproducible though).

Thanks,

**Comment by lancewillett** [comment]
This should be solved now in more recent app versions. Feel free to re-open if you have the same issue again.
