### ISSUE TITLE
Activity Log: Master Issue for Notifications and Emails

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/wp-calypso#20521]
Master issue to track all notifications/emails

**Download is ready**
- [x] Email #19540 
- [x] Notification #19541

**Credentials needed**
- [x] Email #19542

**Issues Detected**
- [x] Email #19610 
- [x] Notification #19612

**Update Credentials**
- [x] Email #19543
- [ ] Notification #19781

Please edit this post to add other Notifications and Emails needed

**Comment by lezama** [comment]
@samhotchkiss can we close this one?

**Comment by lezama** [comment]
@samhotchkiss @samhotchkiss !

**Comment by samhotchkiss** [comment]
@lezama -- @rcoll is testing these, and then will close

**Comment by roccotripaldi** [comment]
Closing because we've confirmed that most of these are done. if it turns out we are missing an email, or we discover that an email needs updating, let's create a specific issue.
