### ISSUE TITLE
Domains: Update domain mapping screen

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#20536]
Now that we have a nice looking screen to transfer a domain to WordPress.com, the mapping option should probably get an update.

![image](https://user-images.githubusercontent.com/448298/33633557-4cfb416a-d9df-11e7-9c8c-0dd8ad0185a4.png)

Things to improve:

* Explain what mapping is in plain terms
* Refer to it as "connecting" rather than "mapping"
* Add a way to transfer the domain instead (and why I would want to)
* Match the layout and style of the transfer screen

**Comment by klimeryk** [comment]
Closing this one - we don't have the resources to do it. And it'd probably be good to do it along with a more holistic revamp of how we present these options (registration vs transfer in vs mapping).
