### ISSUE TITLE
Community translator: enabling translator breaks the site

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#20534]
Enabling community translator tool fails and causes the app to crash.

#### Steps to reproduce
1. Go to account settings: https://wordpress.com/me/account
1. Choose "Interface Language"
1. Pick something else than "English": e.g. "English (UK)" or "Spanish".
1. Click "Save accounts settings"
1. Check "Enable the in-page translator where available"
1. Click "Save accounts settings"
1. Click small blue globe icon / "Enable Translator" button:
    <img width="232" alt="screen shot 2017-12-05 at 23 46 59" src="https://user-images.githubusercontent.com/87168/33632551-9f672018-da16-11e7-9cad-6f06f9c422fe.png">
1. Observe error at console and translator to fail start:
     <img width="502" alt="screen shot 2017-12-05 at 23 47 57" src="https://user-images.githubusercontent.com/87168/33632588-bfa7229c-da16-11e7-8e99-ed2f166892a7.png">
1. Try resizing the browser window or clicking any navigation items
1. :boom: Observe everything disappear and more similar errors in console.

#### Context

`React.DOM.data` in [client/lib/translator-jumpstart/index.js](https://github.com/Automattic/wp-calypso/blob/c6ea319ccf247d23ab671ea6d1cc20ff4d0b2c47/client/lib/translator-jumpstart/index.js#L108-L109) is undefined since React 16 update.

#### Browser / OS version
Chrome 62 / Firefox 57 / MacOS

**Comment by simison** [comment]
I tested this in pre-React-16 Calypso. Doesn't seem like it worked very well back then neither:

<img width="1176" alt="screen shot 2017-12-06 at 00 46 12" src="https://user-images.githubusercontent.com/87168/33635000-ef18d824-da1e-11e7-9a86-7bf1a5e84065.png">

Texts get that glow but no tooling appears when I hover them. That's maybe the broken _tooltip_ in errors?

**Comment by simison** [comment]
X-linking https://github.com/Automattic/community-translator/issues/6

**Comment by alisterscott** [comment]
Disabled via #20555

**Comment by ramonjd** [comment]
Closing for now, as  #20992 brings us back to the state of the tool before the React 16 upgrade.
