### ISSUE TITLE
Imgur Gallery embeds no longer inflate (RegExps?)

### ISSUE THREAD

**Issue by jessestu** [Automattic/wp-calypso#20533]
#### Steps to reproduce
1. Go to My Sites > Blog Posts > Add.
1. Put an Imgur album link on a line by itself. Example: 
http://imgur.com/a/kH7sX
1. Publish and view the post and check to see if the embed works or not.

#### What I expected
The Imgur URL expands into an iFrame gallery of images within a post. Example: https://thearmoredpatrol.com/2017/02/11/pictures-from-the-texas-military-forces-musuem/

#### What happened instead
The post publishes and the URL, such as "http://imgur.com/a/kH7sX", gets displayed unchanged.

#### Browser / OS version
- macOS High Sierra: Google Chrome & Firefox, tested in Calypso and WP-Admin
- Windows 10, unknown browser

#### Screenshot / Video
1. Embed working: https://prntscr.com/hjkad3
2. Entry content for above working embed: https://prntscr.com/hjkbjw
3. Published post where the inflation/expanding no longer works: https://prntscr.com/hjkcm8

#### Context / Source
- Originally brought up on 1194462-hc

#### Notes
1. Some hints from searching this issue lead me to believe this embed/inflating/expanding might be called a *RegExps*.
2. It’s also not clear whether Imgur album embeds should be working on WordPress.com or not. While they are not mentioned in the support documentation ([https://en.support.wordpress.com/?s=imgur](https://en.support.wordpress.com/?s=imgur)) it does appear they worked in the past. Example post of it working (same link as above): [https://thearmoredpatrol.com/2017/02/11/pictures-from-the-texas-military-forces-musuem/](https://thearmoredpatrol.com/2017/02/11/pictures-from-the-texas-military-forces-musuem/)

**Comment by designsimply** [comment]
Also note Imgur embeds are not working in Reader: https://github.com/Automattic/wp-calypso/issues/7391

**Comment by designsimply** [comment]
Also requested at https://en.forums.wordpress.com/topic/embed-imgur-album on 2014-08-15.

**Comment by designsimply** [comment]
Also requested at https://en.forums.wordpress.com/topic/customize-an-embedded-imgur-gallery on 2015-11-25.

**Comment by designsimply** [comment]
Also requested at https://en.forums.wordpress.com/topic/embed-imgur-or-flickr-albums on 2016-06-01.

**Comment by KokkieH** [comment]
Another in https://twitter.com/geek_astronaut/status/1003297423211597826

**Comment by cathymcbride** [comment]
No movement on this for several years. Closing...
