### ISSUE TITLE
[Activity Log] Make security threats more noticeable

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#20538]
Right now, if there are threats they are thrown into the mix with the rest of the feed. This isn't ideal for addressing these threats or expressing a level of urgency. 

<img width="1037" alt="screen shot 2017-12-05 at 2 34 05 pm" src="https://user-images.githubusercontent.com/26996883/33634873-91244784-d9ca-11e7-9a5c-adb253da8b9e.png">

We need to find a way to pull this information out more readily, include the option to get help for addressing these threats (happychat), and a way to view ALL threats on the site that are currently active at once.

**Comment by rickybanister** [comment]
The timestamps are also a mess on the scan event card. It was reported at 1:48 to you (assuming that's displayed in your local time) and the threat is displayed in UTC. We need to sync that up or else users will assume we sat on the results for n hours.

**Comment by rickybanister** [comment]
Another thing I notice is that we should ensure that the description api endpoint wraps the file path in something so we can format it as preformatted text or similar. It's quite hard to read otherwise.

**Comment by MichaelArestad** [comment]
Let's just remove the redundant timestamp from the event copy. Perhaps something like
> A security threat, TimThumb, was found in:

**Comment by MichaelArestad** [comment]
> Another thing I notice is that we should ensure that the description api endpoint wraps the file path in something so we can format it as preformatted text or similar. It's quite hard to read otherwise.

@rickybanister That's something I definitely have been wanting to explore for actionable/expanded events.

**Comment by MichaelArestad** [comment]
@keoshi can you post the mockups you did for this here?

**Comment by keoshi** [comment]
The most recent conversation happened here: p9rlnk-8M-p2#comment-915

A more recent, more actionable one:

![image](https://user-images.githubusercontent.com/390760/37294249-500a714e-260d-11e8-880f-b274452aa07f.png)

And older, kind of out-of-date:

![image](https://user-images.githubusercontent.com/390760/37294284-656465a4-260d-11e8-9200-fa7838c01f80.png)

**Comment by keoshi** [comment]
This work has been a couple of months ago in https://github.com/Automattic/wp-calypso/pull/24375
