### ISSUE TITLE
Activity log/Rewind: Add ability to stop rewind

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#20548]
There's currently no option to stop a rewind from happening. I would recommend we add this in as it is something users do from time to time especially if it's a large site and the rewind takes a while.

**Comment by eliorivero** [comment]
I recommend against this. If a restore is partially done, the site might break. Imagine that the process is restoring the plugins folder. The user stops it. For a plugin that was active, only half of the files are copied. The half copied references functions or classes in the other half. Fatal error.
Even more, at whatever step the rewind is stopped, the resulting site will miss things. Only way to solve this by user will be to rewind again.
