### ISSUE TITLE
Guided Tours ignores all but the first `tour` query string parameter

### ISSUE THREAD

**Issue by markryall** [Automattic/wp-calypso#20553]
#### Steps to reproduce

1. Browse to `wordpress.com/?tour=main` with a logged in calypso session

#### What I expected

The `main` guided tour should be triggered

#### What happened instead

No guided tour was displayed

#### Browser / OS version

This would relate to all

#### Context / Source

I believe the issue is related to the persistence/rehydration of state.ui.route.query.initial into redux state.  It seems to ensure that subsequent values for the `tour` query string parameter will be ignored.

Triggering guided tours from support would be a useful feature so restoring the original behaviour would be very valuable.

**Comment by lsinger** [comment]
This worked fine up until this commit: https://github.com/Automattic/wp-calypso/commit/1cfa157f2f731c64d3a929c6f8c16db5eff115a0

**Comment by lsinger** [comment]
This was introduced with #20255. 

Guided Tours's query argument-based triggering relies on the timestamp in the `getInitialQueryArguments` selector. #20255 (more specifically, 6f4c446f5d87b003df99d3ae2b34a020af17c8a5) introduces caching, which includes the timestamp.

**Comment by iamtakashi** [comment]
The query strings triggering guided tours have been very useful when we design new tours. It'd be great if this issue was fixed. Bump :)
