### ISSUE TITLE
Some tests pass no matter what

### ISSUE THREAD

**Issue by notnownikki** [Automattic/wp-calypso#20565]
#### Steps to reproduce

1. Check out 674f8a0eaa4a058b279e5b5dcef2b329f901e6c8
2. Run the tests.
3. Change `calledOnce` to `notCalled` in the media libary test `client/my-sites/media-library/test/index.jsx`
4. Run the tests again

#### What I expected

Tests should fail.

#### What happened instead

Tests still pass.

#### Context / Source

While adding a test for the media library, I saw this test (which I'm fixing in another PR) had tests that passed no matter what: https://github.com/Automattic/wp-calypso/blob/674f8a0eaa4a058b279e5b5dcef2b329f901e6c8/client/my-sites/media-library/test/index.jsx

You could swap `calledOnce` to `notCalled` and the test would still pass.

I'm not certain, but this _seems_ to be because the test is using a `sinon.stub`, and not a `jest.fn` as `expect().to.be.calledOnce` expects ( as far as I can tell from http://facebook.github.io/jest/docs/en/expect.html#tohavebeencalledtimesnumber anyway) and when I changed the assertion to `expect( stub.callCount ).to.equal( numTimesItShouldBeCalled )` everything worked as expected.

I'm concerned that there may be other tests doing the same thing, and we're seeing them pass when they're not actually testing anything.

I'd like to suggest we write a something that detects this so we can be sure our tests are actually testing things.

**Comment by notnownikki** [comment]
We current have 152 instances of `to.have.been.calledOnce` so I'm writing a script that will change each test suite where they occur to `to.have.been.notCalled` and make sure they fail as expected.

**Comment by notnownikki** [comment]
My initial guess that it was a jest/sinon mixup was incorrect, This seems to be the right way to call things according to https://github.com/domenic/sinon-chai, if we're using that... Test scripts still running.

**Comment by notnownikki** [comment]
Test script has run. It replaced `calledOnce` with `notCalled` in each test suite, and ran the test suite to see if it still passed.

They all still passed.

List of affected suites:

client/post-editor/media-modal/test/preload-image.js
client/my-sites/media-library/test/index.jsx
client/extensions/wp-job-manager/state/data-layer/settings/test/index.js
client/extensions/zoninator/state/data-layer/feeds/test/index.js
client/extensions/zoninator/state/data-layer/zones/test/index.js
client/extensions/woocommerce/state/data-layer/products/test/index.js
client/components/accordion/test/status.jsx
client/components/data/query-atat-eligibility/test/index.jsx
client/components/forms/form-text-input/test/index.jsx
client/reader/test/utils.js
client/lib/wp/sync-handler/test/index.js
client/lib/abtest/test/index.js
client/lib/create-selector/test/index.js
client/lib/store/test/index.js
client/lib/posts/test/actions.js
client/lib/preferences/test/actions.js
client/lib/oauth-store/test/index.js
client/lib/media/test/actions.js
client/lib/analytics/page-view-tracker/test/index.jsx
client/lib/network-connection/test/index.js
client/lib/directly/test/index.js
client/auth/test/login.jsx
client/blocks/edit-gravatar/test/index.jsx
client/state/test/initial-state.js
client/state/data-layer/test/extensions-middleware.js
client/state/data-layer/test/wpcom-api-middleware.js
client/state/data-layer/wpcom/meta/sms-country-codes/test/index.js
client/state/data-layer/wpcom/account-recovery/validate/test/index.js
client/state/data-layer/wpcom/account-recovery/reset/test/index.js
client/state/data-layer/wpcom/account-recovery/request-reset/test/index.js
client/state/data-layer/wpcom/sites/comments/test/index.js
client/state/data-layer/wpcom/sites/comments/likes/mine/delete/test/index.js
client/state/data-layer/wpcom/sites/comments/likes/new/test/index.js
client/state/data-layer/wpcom/sites/comments/replies/new/test/index.js
client/state/data-layer/wpcom/sites/comments-tree/test/index.js
client/state/data-layer/wpcom/sites/posts/replies/new/test/index.js
client/state/data-layer/wpcom/comments/test/index.js
client/state/data-layer/wpcom/privacy-policy/test/index.js
client/state/data-layer/wpcom/timezones/test/index.js
client/state/data-layer/wpcom/read/teams/test/index.js
client/state/data-layer/wpcom/read/following/mine/test/index.js
client/state/data-layer/wpcom/read/tags/test/index.js
client/state/data-layer/wpcom/read/tags/mine/delete/test/index.js
client/state/data-layer/wpcom/read/tags/mine/new/test/index.js
client/state/data-layer/wpcom/read/feed/test/index.js
client/state/data-layer/wpcom/domains/countries-list/test/index.js
client/state/data-layer/wpcom/posts/revisions/test/index.js
client/state/data-layer/wpcom/me/devices/test/index.js
client/state/data-layer/wpcom/me/transactions/supported-countries/test/index.js
client/state/data-layer/wpcom/me/send-verification-email/test/index.js
client/state/data-layer/wpcom/me/settings/test/index.js
client/state/data-layer/wpcom/me/notification/settings/test/index.js
client/state/data-layer/wpcom/gravatar-upload/test/index.js
client/state/data-layer/wpcom/users/test/index.js
client/state/data-layer/third-party/directly/test/index.js
client/state/data-layer/wpcom-http/pipeline/retry-on-failure/test/index.js
client/state/http/test/index.js
client/state/themes/test/actions.js
server/pages/test/analytics.js

**Comment by gziolo** [comment]
`expect().to.be.calledOnce` is from `chai-sinon` so it works with `sinon.spy()`. With `jest.fn()` you would have to use `expect(). toHaveBeenCalledTimes( 1 )`. Do you plan to fix that?

**Comment by notnownikki** [comment]
I'm wondering how we ended up with 59 test suites all with this broken behaviour. Is it just a matter of changing `to.have.been.calledOnce` to `toHaveBeenCalledTimes( 1 )` (and the equiv for `notCalled`)?

**Comment by notnownikki** [comment]
I mean, I'm happy to help fix these, but I'd like to know how we got here, so that I can check for other problems too. There might be more issues than been.calledOnce/notCalled here, and with it being across 59 test suites, it seems like something was updated and left these tests with worthless assertions, so I'd like to know what else I should be checking for.

**Comment by gziolo** [comment]
I didn't check if `toHaveBeenCalledTimes` from Jest would work with Sinon's spy or stub. I would assume it doesn't. We probably need to update from one `sinon-chai` method to another. Does it work with `have.callCount(n)` properly? Personally, I would check other methods from `sinon-chai`, too. I'm sure some of them were failing when I was working on the migration. I'm happy to help with reviews, etc. Just ping me whenever you have PR open.
I'm glad you discovered it, great job 💯

**Comment by notnownikki** [comment]
Ah, so a sinon-chai upgrade :) Do you know offhand what version we upgraded from/to, so I can check the docs for any hints? If not, I can look back through the history for `package.json`

**Comment by gziolo** [comment]
I was referring to Mocha to Jest migration. Maybe there was version bump recently, I didn't follow closely. Too busy with Gutenberg 😄

**Comment by notnownikki** [comment]
Heh ok :) I'll ping some other peeps,  `expect( sinonStub ).to.have.been.calledOnce` is the correct way according to the sinon-chai docs!

**Comment by notnownikki** [comment]
Alrighty, we only use `notCalled` in a few tests. That's good, because it's `notCalled` that passes no matter what!

I can fix this quite easily. Thanks for looking into it with me!

**Comment by notnownikki** [comment]
Ok, the issues are limited to media library tests! And I'll have fixes for those lined up as part of the free image library work.

**Comment by notnownikki** [comment]
Panic over, not the huge issue it seemed, being fixed as part of the media library work I have PRs open for anyway.
