### ISSUE TITLE
Domain Transfers: Unable to restart transfer

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#20572]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/domains/manage/flockofzebras.com/transfer/in/mikestraw.com

2. This domain (flockofzebras.com) transfer was initiated, but never approved by the WHOIS contact.

3. Try to restart the transfer by clicking "Start Transfer Again"

#### What I expected

For the transfer to be restarted. 

#### What happened instead

Received "We were unable to restart the transfer" error.

DARC API log shows `oSRS Error Code #400: Transfer cannot be resubmitted. Transfer status does not allow for resubmit..`

#### Browser / OS version

Chrome Version 62.0.3202.94 (Official Build) (64-bit)
macOS High Sierra Version 10.13.1 (17B1003)

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/7596032/33677137-c8af5a7a-da85-11e7-98f3-2fc3e6ce91e5.png)

**Comment by aidvu** [comment]
Already fixed. Will update it for your domain @GeoJunkie.
