### ISSUE TITLE
Editor: console warning/error `openPostRevisionsDialog` when loading editor with history

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#20583]
#### Steps to reproduce
1. Starting at URL: calypso.localhost:3000/posts
2. Edit a post with revision history

#### What I expected

No consoler errors/warnings

#### What happened instead

```
index.jsx:97 Warning: Failed prop type: The prop `openPostRevisionsDialog` is marked as required in `HistoryButton`, but its value is `undefined`.
    in HistoryButton (created by Localized(HistoryButton))
    in Localized(HistoryButton) (created by Connect(Localized(HistoryButton)))
    in Connect(Localized(HistoryButton)) (created by EditorGroundControl)
    in div (created by EditorGroundControl)
    in div (created by Card)
    in Card (created by EditorGroundControl)
    in EditorGroundControl (created by Localized(EditorGroundControl))
    in Localized(EditorGroundControl) (created by PostEditor)
    in div (created by PostEditor)
    in div (created by PostEditor)
    in PostEditor (created by Localized(PostEditor))
    in Localized(PostEditor) (created by ProtectedFormComponent)
    in ProtectedFormComponent (created by Connect(ProtectedFormComponent))
    in Connect(ProtectedFormComponent)
    in Provider

```
#### Browser / OS version

Chrome macOS

#### Screenshot / Video

<img width="1298" alt="screen shot 2017-12-07 at 12 02 11 pm" src="https://user-images.githubusercontent.com/128826/33694928-7d4c6a84-db46-11e7-9cd5-023d53f1cd51.png">

#### Context / Source
Found testing https://github.com/Automattic/wp-calypso/pull/20326

**Comment by jblz** [comment]
This should be fixed in #20573.

I've been running that diff so much instead of master, I forgot I'd fixed that propType.

Thanks!
