### ISSUE TITLE
Jetpack sites don't support history

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#20581]
When I was writing a post on Jetpack site in the calypso editor I saw the history button. 
I am running the latest version of Jetpack
Sorry if this was reported somewhere else. 

#### Steps to reproduce
1. Starting at URL: https://calypso.live/post/enejtestpressablefun.mystagingwebsite.com/26

#### What I expected
To be able to see the history. 

#### What happened instead
I just the placeholders

#### Browser / OS version
Firefox, macos

#### Screenshot / Video
<img width="1625" alt="screen shot 2017-12-06 at 4 14 50 pm" src="https://user-images.githubusercontent.com/115071/33692149-b9398168-daa0-11e7-9a5a-d5f9c9625111.png">

#### Context / Source
#dogfooding, #manual-testing, 

cc: @jblz

**Comment by jblz** [comment]
Hi, @enejb!  This should be fixed as of #20573. Can you please confirm?

**Comment by beaulebens** [comment]
Confirmed that I'm seeing the history/diffs showing properly on a Jetpack site now 👍
