### ISSUE TITLE
Site Setup: Step 2 - "Included in WordPress.com Personal"

### ISSUE THREAD

**Issue by crunnells** [Automattic/wp-calypso#20584]
I was going through the process of setting up a site on WordPress, and Step 2 ("Let's give your site an address" https://wordpress.com/start/domains) lists domain suggestions as "Included in WordPress.com Premium" instead of Personal. I'm not sure if this is intentional, but it could be seen as misleading, as the very next screen (Step 3) mentions that domains are, in fact, included in Personal.

**Steps to reproduce**

* Starting at URL in Private/Incognito/Logged out: https://wordpress.com/
* Click on "Get Started" button, go through Step 1
* Continue to Step 2, enter a domain name, note that all domains mention WordPress.com Premium

**Comment by klimeryk** [comment]
Thanks for reporting - it's a known issue back from when we did not have a lower plan than Personal. See s5XAZ9-domains-p2 for a similar report and discussion. cc @fditrapani @danhauk

**Comment by alisterscott** [comment]
We now show "Included in Paid Plans" - closing this issue

<img width="977" alt="screen shot 2018-07-25 at 3 37 19 pm" src="https://user-images.githubusercontent.com/128826/43181476-b62ed1b8-9020-11e8-9c50-8e913f9c805b.png">
