### ISSUE TITLE
Posts: React error and missing posts when infinite scroll is triggered

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#20599]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts
2. Select a site with enough posts to trigger infinite scroll (~20?).
3. Scroll down to the bottom of the list of posts, to trigger more posts loading.
4. Scroll back up to the top of the page.

#### What I expected

I expected to see my most recent post at the top of the page.

#### What happened instead

There was a blank space at the top of my page where the most recent posts should have been, and Calypso was unresponsive temporarily until a React error appeared in the console:

```
vendor.bb911893ccbbbf18e392.min.js:37 Uncaught Error: Minified React error #185; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Also, the next page of posts never seemed to load. Some or all of these issues could be related to being on a very slow wifi connection.

#### Browser / OS version

Mac OS 10.12.6, Chrome 62

#### Screenshot / Video

<img width="1441" alt="screenshot 2017-12-07 16 03 04" src="https://user-images.githubusercontent.com/8658164/33722205-a7262728-db69-11e7-98d2-34ff020a6494.png">

#### Context / Source
#dogfooding

**Comment by bsessions85** [comment]
This one is working now. Closing
