### ISSUE TITLE
Reader: back button missing in full post on mobile

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#20597]
@shaunandrews noticed that we have some layout regressions in full post on mobile:

![_720](https://user-images.githubusercontent.com/17325/33721924-5a85208a-db60-11e7-955b-8db62149252b.png)

The back button is present but is hidden behind the masterbar.

**Comment by jancavan** [comment]
I'm seeing some alignment issues on the byline, but I think it's because we put the gravatars on top of the blavatars and this one doesn't have a blavatar.

**Comment by jancavan** [comment]
This is a duplicate of: https://github.com/Automattic/wp-calypso/issues/19948 so closing.
