### ISSUE TITLE
.org Plans: post-registration email doesn't mention the site URL

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#206]
Steps to reproduce:
1. Purchase .org Plans for multiple sites, all linked to your WordPress.com account.
2. Receive an email for each purchase, listing your registration keys.
3. Do not set up VaultPress on your site, you don't have time.
4. A few days later, look for your registration email for a specific site, to finish to set up VaultPress

You won't be able to know which email and registration key match that specific site.

It'd be nice if the site URL was included in the email's subject line.

**Comment by designsimply** [comment]
Tested and confirmed that the email with registration keys does not have the URL of the site in the title.

The email subject is "Your New Akismet + VaultPress Bundle" and here is a screenshot of the email for reference:

<img alt="screen shot 2016-04-29 at 16 31 58" src="https://cloud.githubusercontent.com/assets/1119271/14931538/93459f4a-0e29-11e6-8eed-7f08a758320a.png" width="400" />
