### ISSUE TITLE
Markdown formatting not being applied to pasted content

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#20608]
#### Steps to reproduce
1. Reproducible on any site, open up the Editor and add the ` character
2. Type anything and close with a `, Markdown formatting should be applied
3. Now, open ` again, cut the content out from between the backticks, then paste content back in, close with `
4. Markdown formatting will not be applied

#### What I expected
I expected the content to be formatted after I pasted it in

#### What happened instead
Content was not formatted
It appears if the content is cut from somewhere else, the formatting is applied, but if the content is cut from next to or in between the backticks, it will not apply formatting if pasted back in between the ticks.
#### Browser / OS version
Version 62.0.3202.94 (Official Build) (64-bit), Windows 10 V1709

#### Screenshot / Video
User submitted
https://cloudup.com/czbDYyk7Ecx

Reproduced
https://cloudup.com/cRLIvym4Tnr

Follow up ticket 834048-zen

**Comment by separatelyunited** [comment]
User replied back with their Browser / OS information: 
Chrome 63 on Linux Mint 18.3.

**Comment by designsimply** [comment]
Tested and confirmed using the testing steps provided that pasting in content between back ticks does not result in code snippet formatting as expected.

Video: [25s](https://cloudup.com/cA96eqPLDPT)

![screen shot 2017-12-07 at thu dec 7 3 52 27 pm](https://user-images.githubusercontent.com/1119271/33742692-b9c1b4b8-db66-11e7-8d63-615fd5bf2bfd.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11540 using Safari 11.0.1 on Mac OS X 10.13.1.</sup>

Please note that markdown is not currently in active development and it may take some time before markdown-related issues are reviewed.

<blockquote>Markdown support has never been addressed in REST API contexts and therefore also not in the Calypso editor.</blockquote>

Source: https://github.com/Automattic/wp-calypso/issues/2373#issuecomment-278138284

**Comment by lancewillett** [comment]
Thanks for the work to report and clarify this issue. We don't plan to work on Markdown support in the editor as @designsimply mentions above. In addition, the new Gutenberg editor will soon replace the Calypso editor (early 2018).
