### ISSUE TITLE
Comments: test and see if old endpoints are faster than using comments-tree

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#20619]
Since our designs have changed drastically. Let's do a sanity check and see if our old endpoints are faster than our current comments-tree approach.

**Comment by gwwar** [comment]
Looking at en.blog.wordpress.com: 
`/sites/en.blog.wordpress.com/comments-tree` can take anywhere from 4 seconds to 500ms
`/sites/en.blog.wordpress.com/comments` for the first page is around 1 sec to 200ms

**Comment by gwwar** [comment]
Let's also compare for the post specific view. Would we still like to use comments-tree for a threaded comment post view? cc @Copons @rodrigoi

**Comment by kwight** [comment]
Averaging 10 calls and throwing away the best and worst, I come up with these numbers. The number in parenthesis is the approximate number of total comments on the site.

| Endpoint  | en.blog.wordpress.com (127K) | kwight.ca (150) | Jetpack site (30)
| ------------- | ------------- | ------------- | ------------- |
| `comments-tree`  | 1040ms  | 193ms | 1145ms |
| `comments`  | 380ms  | 405ms | 1261ms |

**Comment by kwight** [comment]
> Let's also compare for the post specific view.

| Endpoint  | en.blog.wordpress.com (127K) | kwight.ca (150) | Jetpack site (30)
| ------------- | ------------- | ------------- | ------------- |
| `comments-tree`  | 1040ms  | 193ms | 1145ms |
| `posts/:post_id/replies`  | 429ms  | 426ms | 1349ms |

**Comment by gwwar** [comment]
Thanks for looking @kwight !
