### ISSUE TITLE
Themes: /design redirect from frontend navigation is 404'ing

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#20617]
#### Steps to reproduce
1. Starting at URL: front-end of your WP.com site
2. Click My Sites
3. Click "Themes" under Personalize

<img width="507" alt="screen shot 2017-12-07 at 14 44 59" src="https://user-images.githubusercontent.com/66797/33740248-3a891d70-db5d-11e7-8b78-7f40ef967125.png">

We link to this URL structure directly from the frontend navigation. Did something change recently with routing, or our `manage/themes` config?

#### What I expected
I expected to see the Calypso themes page (Theme Showcase).

#### What happened instead
404 for some sites; 502 Bad Gateway for a private Automattic P2 site.

#### Screenshot / Video
![screen shot 2017-12-07 at 14 42 00](https://user-images.githubusercontent.com/66797/33740131-ce8bdf90-db5c-11e7-8995-95ec56ae195a.png)

**Comment by lancewillett** [comment]
We could fix it in WP.com admin-bar.php file to point to `/themes` easily — but the bigger question is, why is this routing broken? When did it change?

**Comment by designsimply** [comment]
I am not sure when it changed, but I do know it was reported 6 days ago by @ryanboren in Slack. /hat tip

Duplicate of 7971-wpcom.

Related to https://github.com/Automattic/wp-calypso/issues/20416.

**Comment by lancewillett** [comment]
Thank you, Sheri! Closing in favor of those.
