### ISSUE TITLE
Store: Settings: Add Support for Store Notices

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#20623]
@jameskoster wrote:

Finally we have the main Store Notice option which lives in the general settings area. We’ll add a new secondary level “Display” navigation item alongside “Payments”, “Shipping” and “Taxes”. Although this will only include the Store Notice option for now, we might add catalog / image display settings here in the future. Extensions will also likely use this section so adding a new screen is justified.

When the Store Notice option is disabled you simply see a checkbox. When it’s enabled the input / preview are revealed;

![do-not-display](https://user-images.githubusercontent.com/1595739/33746068-85dcdc64-db6f-11e7-819c-3629ddab71b1.png)

![do-display](https://user-images.githubusercontent.com/1595739/33746067-85a4ea3e-db6f-11e7-9fdb-de4f5019fb61.png)

**Comment by allendav** [comment]
@jameskoster @kellychoffman - in light of WooCommerce moving these settings to the customizer - do we still want to move forward with these designs? See also #20624

**Comment by kellychoffman** [comment]
Great question. Jay and I discussed this a bit and think that its best to align with WooCommerce and move these settings to the customizer. It also provides a more accurate preview.

A store owner would discover this setting via the dashboard widget. This would link them straight to the Store Notice in the Customizer. 

Sorry we didn't catch this sooner :/

**Comment by allendav** [comment]
In light of store notice settings moving into customizer, this change is no longer desired. The companion issue #20624 will move forward with some modifications.
