### ISSUE TITLE
Atomic: WooCommerce downloadable file directory is not accessible

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/wp-calypso#20629]
When creating downloadable products, WooCommerce uploads files into the `wp-content/uploads/woocommerce_uploads/` folder, but when you try to view those files you get a 403 forbidden error.

As a workaround, you can upload files directly into the Media library and then paste the file path into the downloadable product instead of uploading it from the product page.

#### Steps to reproduce
1. Create a new Product using WooCommerce
2. Select "Downloadable" from the product data
3. Click "Add File" below
4. Click "Choose File"
5. Upload a file
6. Try to access that file

#### What I expected
I expected to be able to open the file and that my customers would be able to access their purchased files.  

#### What happened instead
Instead, they get a 403 forbidden error.

**Comment by timmyc** [comment]
@mikeyarce just to confirm this bug is for WooCommerce installs on Atomic sites? If so we might need to bring this up in at_devs or with systems since we won't be able to fix this in Calypso.

**Comment by mikeyarce** [comment]
@timmyc yes, that's right.   I wasn't sure how to tag this properly, haha! :)  I agree it's not something we can fix in Calypso but we need to either change how downloadable files are stored OR allow the `woocommerce_uploads` directory to be readable.  How do we ping the at_devs?

**Comment by mikeyarce** [comment]
@timmyc Ok, the issue seems to be that it's the file download method "Force Downloads" that isn't working properly.  Setting the download method to `X-Accel-Redirect/X-Sendfile` fixes the problem.  Should we set this as the default for all Atomic sites and then disable this option from the settings?

**Comment by timmyc** [comment]
Have there been any other reports of this problem so far? I suppose if "Force Downloads" simply doesn't work on AT, it makes sense to manually toggle the setting and perhaps hide/disable if we can do so.

**Comment by mikeyarce** [comment]
@timmyc Ok, checked a few sites and it does not seem consistent. I'm not sure what the difference would be, but for now let's leave it as it is because "Force Downloads" does work on other Atomic sites.
