### ISSUE TITLE
Store: Dashboard: Add Dashboard Widget Advertising the Store Notice Feature

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#20624]
@jameskoster wrote:

Despite many folks requiring this feature, many don’t know it exists or have trouble finding it again after not using it for some time. To help remedy this we’ll periodically/conditionally display a dashboard widget prompting them to add or update the Store Notice. Like so;

![1](https://user-images.githubusercontent.com/1595739/33746099-bfc8f214-db6f-11e7-9cec-72f45a05e5b2.png)

We’ll display the widget when the store owner has recently added a new product or promotion, prompting them to promote it. We should also display the widget when the Store Notice hasn’t been updated in a while. This will ensure it is always relevant and fulfilling it’s purpose.

Clicking the “Set up a Store Notice” button in the above design would open the customizer. Dismissing the widget will hide it.

**Comment by allendav** [comment]
@kellychoffman @jameskoster - regarding:

> We should pre-populate the Store Notice input with suggested content when a user decides to enable it after being prompted by the widget

What if the user 1) already has a notice set up that is 2) less than 30 days old - I assume we should _not_ show the dashboard widget then?

**Comment by kellychoffman** [comment]
> What if the user 1) already has a notice set up that is 2) less than 30 days old - I assume we should not show any notice-related dashboard widget then?

Agree that we shouldn't show it if that is the case.

**Comment by allendav** [comment]
@jameskoster @kellychoffman - in light of WooCommerce moving these settings to the customizer - do we still want to move forward with these designs? See also #20623

**Comment by jameskoster** [comment]
Chatted with Kelly about this just now. I think we can probably lose the dedicated settings screen. But the dashboard widget is still useful, we should just send folks to the Customizer (with the appropriate panel open) if they intend to edit the notice.

**Comment by kellychoffman** [comment]
We should only move forward with the dashboard widget. No inline editing, all editing will take place in the customizer.

**Comment by justinshreve** [comment]
I've updated this issue to just cover adding the dashboard widget pointing to the customizer feature. I've removed @allendav since I don't believe he is currently working on this.
