### ISSUE TITLE
Change App Banner dismissal time to less than a year

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#20626]
We're going to experiment with a shorter time for showing the app banner again (let's start with a month)

All we need to do is tweak this to be a month instead of a year in milliseconds.

https://github.com/Automattic/wp-
calypso/blob/9dac69a6c4f5fbb44dbb5b2ddcf9bb36559e3e3c/client/blocks/app-banner/utils.js#L67

**Comment by kwonye** [comment]
We can start with a month and tweak the time from there if we get feedback

**Comment by designsimply** [comment]
May I ask how to trigger the app banner for testing?

**Comment by designsimply** [comment]
Aha, nevermind, I saw this at https://github.com/Automattic/wp-calypso/pull/20627

> Unfortunately I'm not aware of how to change the clock on Chrome itself, so not sure how to verify the timeout is correct. No logic is changed however, so it should behave exactly as before.

**Comment by kwonye** [comment]
@designsimply to get the banner to trigger, these steps will work:

In Desktop Chrome:

This banner should not be visible on any page in non-mobile browsers.
In order to test it, you can open up DevTools in Chrome and use Toggle device toolbar. Along making the screen size smaller, this will also change the userAgent which we use to test whether the app banner should be shown. Another option would be to select the userAgent manually in Chrome DevTools by following option 2 of this guide.
Verify that app banner is shown on stats, reader, and editor pages. It should also be shown on any page when notification panel is open.

Note: If you've dismissed the widget and want to bring it back for testing in current session, you can run the following line in your console:

`dispatch( { type: 'PREFERENCES_SET', key: 'appBannerDismissTimes', value: null } );`
