### ISSUE TITLE
Stats - insights: visually broken "no records" message

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#20658]
"No popular day and time recorded" message is visually off.

#### Steps to reproduce
1. Starting at URL: `https://wordpress.com/stats/insights/:site`
2. For empty / new blog you will see _"No popular day and time recorded"_ message in _"Most popular day and hour"_ box:
    ![screen shot 2017-12-08 at 20 38 03](https://user-images.githubusercontent.com/87168/33779973-b48df3fc-dc57-11e7-82ca-7ed21973a5e6.png)
3. Message will break into two lines If you make your browser window just under ~1000px wide or around ~1300px wide:
    ![screen shot 2017-12-08 at 20 35 10](https://user-images.githubusercontent.com/87168/33779990-c45e97e6-dc57-11e7-8d37-f27ccc7442c5.png)

#### What I expected
Message box to change its height when text inside it breaks into multiple lines.

#### What happened instead
The box broke. 😢 

#### Browser / OS version
Firefox / MacOS

☝️  Remember that this was just in English: in other locales there might be more text in this message box.

**Comment by markpernotto** [comment]
Hello all, I would like to tackle this issue. I've been able to replicate the problem, as well as I've been able to come up with a possible fix. I do have a couple of questions, however.

If I change the span's class: **.most-popular__notice** at the prescribed width and include the CSS:
display:inline-flex

I get the following:
<img width="343" alt="screen shot 2017-12-13 at 10 48 31 am" src="https://user-images.githubusercontent.com/2965712/33956587-d8d3b27a-dff3-11e7-9390-d452ca1e2e97.png">

However, it does appear that where the 'Top' of the box begins gets modified with this specification. This, too, could be adjusted to something like:
Top: 18px
And only be included for the @min-width: 661px display.

This should extend for multiple languages:
<img width="329" alt="screen shot 2017-12-13 at 10 59 12 am" src="https://user-images.githubusercontent.com/2965712/33956873-be613664-dff4-11e7-8735-387f3b5d03bb.png">

But does beg the question as to best practices, as longer text (beyond two lines) could cause problems. Thoughts?

Tested in FF and Chrome on Mac OSX. Cannot get local copy of Calypso running in Safari.

This is my first attempt at working on anything here - please let me know how I should go about making this update or please let me know if you have any questions or if I'd need to do anything before submitting this merge.

Thanks!

**Comment by simison** [comment]
Hey @markpernotto! 👋  So good to see you're interested in fixing this! :-)

I would encourage you to open a PR with instructions how to replicate this (you can copy instructions from this issue), how your fix attempts to fix it and what could be caveats if any. Be mindful about [browser compatibility](https://github.com/Automattic/wp-calypso/blob/8af68412f06223a4d6614c67e2a6fee97e9f50c5/package.json#L12-L18).

I also noticed this issue in Chrome (the box overflowing from right):

![screen shot 2017-12-14 at 18 17 32](https://user-images.githubusercontent.com/87168/34005134-989bd272-e102-11e7-9b9e-b89163a23cc7.png)

I can confirm your suggestion fixes that one, too.

I noticed icon is hidden from notifications for small screens at `https://wordpress.com/stats/day/:site`:
<img width="404" alt="screen shot 2017-12-14 at 19 14 55" src="https://user-images.githubusercontent.com/87168/34005466-9ecb4fc8-e103-11e7-97e9-aeb9189013c9.png">
<img width="350" alt="screen shot 2017-12-14 at 19 14 49" src="https://user-images.githubusercontent.com/87168/34005467-9efec15a-e103-11e7-95aa-57a72c71a600.png">
...perhaps that would work here, too?

>But does beg the question as to best practices, as longer text (beyond two lines) could cause problems. Thoughts?

I think your change is quite safe since this CSS class doesn't seem to be re-used anywhere else so there should not be any unintended side-effects.

(FYI @juliaamosova who was the last one modifying this bit of code.)

**Comment by markpernotto** [comment]
Hello @simison! 

Thanks for the direction. I've tested in all browsers, created my local branch, committed, but I don't seem to be able to send a pull request. I've named the branch: fix/stats-insights-20658, but after each push attempt gets me the message that permission to push is denied.

I've read through [all](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md) [of](https://github.com/Automattic/wp-calypso/blob/master/docs/git-workflow.md#branch-naming-scheme) [the](https://help.github.com/articles/about-pull-requests/) [documentation](https://github.com/Automattic/wp-calypso/compare), and am sure I'm missing something simple. This would be my first commit to wp-calypso.

Thanks in advance for your assistance.

**Comment by simison** [comment]
@markarms Hey! Fantastic you got started! 👏 

You should first [fork this repo](https://help.github.com/articles/fork-a-repo/) so that you have your own version and push the commit you just made to a branch in your fork.

Then you can [create a pull request from your fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) back here. In description write "Fixes #20658" thus marking it related to this issue.

See also [Contributing to Calypso — Pull requests](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md#pull-requests).

Feel free to ask again if you hit any trouble!

**Comment by markpernotto** [comment]
Thank you, @simison 

I _think_ a pull request has been made. Sincerest appreciation for your detailed direction.

**Comment by simison** [comment]
@markpernotto Yep, looks good! It might take some time before someone gets to review that (holidays et all) but hopefully soon. :-)
