### ISSUE TITLE
Sharing: Disabling the Like button disables both Like and Reblog

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#20659]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/sharing/buttons/
2. Disable the Like button
3. Check front-end of site (Like button should no longer be displayed, but Reblog is no longer there as well)

#### What I expected
For Reblog button to still be displayed.

#### What happened instead
Both Like and Reblog are not displayed.

#### Browser / OS version
Chrome Version 62.0.3202.94
Mac OS 10.12.6

#### Screenshot / Video

In Sharing, only Like is disabled:
![screen shot 2017-12-08 at 10 48 47 am](https://user-images.githubusercontent.com/4924246/33780390-6ac60734-dc05-11e7-9a63-91967f9fb37b.png)

But on the front-end, both buttons (Like and Reblog) aren't displayed:
![screen shot 2017-12-08 at 10 49 45 am](https://user-images.githubusercontent.com/4924246/33780413-84fae6ba-dc05-11e7-87e5-892efbcd52e4.png)

**Comment by rachelmcr** [comment]
Same issue as https://github.com/Automattic/wp-calypso/issues/6136. As mentioned there, since this is an API issue closing in favor of 7550-wpcom.
