### ISSUE TITLE
SSR: Logged-out 404s appear in non-English Language

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#20669]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/foobar (in an incognito window)
2. View Page Source
3. Cmd-F `empty-content__title`
4. Verify what language that `h2` is. If it's English ('Looking for great WordPress designs?'), it's fine. If it's in a different language, it's broken.
5. You might have to try a couple of different inexistent theme names instead of `foobar`.
6. You might _also_ have to wait for someone to deploy Calypso -- I suspect this bug depends on whichever user hits Calypso first after a deploy, since that's what's going to be cached.

#### What I expected

Server-side rendered content for logged-out users should be English. (In an ideal world, we could try and determine it via GeoIP, headers sent by the browser, etc, but due to `i18n-calypso`'s internal state handling, we can only do English reliably for now.)

#### What happened instead

Spanish: '¿Buscas diseños de WordPress maravillosos?'

#### Browser / OS version

Chrome, macOS.

#### Context / Source

As per @stephanethomas' hypothesis (which sounds quite reasonable to me), this might be due to locale information being cached on the server across requests (#20255?)

Previous Slack discussion: p1512727499000041-slack-calypso

cc @Tug 
FYI @gwwar

**Comment by Tug** [comment]
Found a way to reproduce consistently:
- Checkout calypso `master` branch locally
- Enable user bootstrap locally:
- Edit `config/secrets.json` and set `{ "wordpress_logged_in_cookie": "<insert_value_from_session>" }` (get the value from chrome dev tools at Application > Storage > Cookies > https://public-api.wordpress.com > `wordpress_logged_in`)
- Edit `config/development.json` and set `wpcom-user-bootstrap` to `true`
- Boot calypso (`npm start`)
- Connect to an account which locale is not set to english
- Navigate to http://calypso.localhost:3000/sites/mysite.com/change-theme/foobar
- Load http://calypso.localhost:3000/theme/foobar from an other session (incognito window or curl for instance) and notice that it displays the error in the locale of the user you were logged in with.

Working on a fix now :)
