### ISSUE TITLE
Theme Showcase: Tweak "Visit Site" wording

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#20661]
I noticed that the "external site" icon on the demo overlay was recently changed to a button with the words "Visit Site." This is a step in the right direction, since the icon was not immediately understood by all.

![photo blog theme wordpress com](https://user-images.githubusercontent.com/7662449/33782857-50be4554-dc28-11e7-9353-2622fdb4a83a.gif)

I'd like to suggest tweaking the wording slightly, as it's not clear to a user which site is being referred to. 

Suggestions:

- Visit Demo
- Visit Demo Site
- Visit Theme Demo
- Visit Theme Demo site

@Automattic/editorial

**Comment by michelleweber** [comment]
+1 for either Visit Demo Site, or Visit Theme Demo.

**Comment by KokkieH** [comment]
It appears that button has now been removed completely, meaning there is no way to visit the actual demo site from the preview. Cmd/Ctr-click on the Open Live Demo link on the showcase page itself works, though.

![snaps_theme_ _wordpress_com](https://user-images.githubusercontent.com/11873759/36084917-45dd523a-0fca-11e8-8fa8-e10692bd0bb3.png)

**Comment by kjellr** [comment]
Closing this issue, since the button in question no longer exists. As per the thread in #20664, it doesn't appear that we'll be adding it back anytime soon.
