### ISSUE TITLE
Posts: Copy a Post and Copy a Page posts and pages cannot be saved or published

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#20668]
#### Steps to reproduce
1. Starting at URL: Any WordPress.com website
2. Create a draft post.
3. Copy the draft post to create a new one.
4. Edit it and try to save. 

#### What I expected

I expected the copied post to save as another draft.

#### What happened instead

The post returned an error that said, "Saving of draft failed." 

#### Browser / OS version

Chrome

#### Screenshot / Video

![cannot-save-draft](https://user-images.githubusercontent.com/617986/33784969-d738f41e-dc17-11e7-8f8b-7b6013518142.gif)

#### Context / Source
I found this bug during Support Rotation. A ticket came up about it.
#manual-testing, #user-report

**Comment by nellofn** [comment]
I was about to create this same issue. Neither a copied page nor a post can't be saved or published. I ran a test on my end and the result is the same as above. It was also reported by a user on this ticket 836996-zen

**Comment by scosgro** [comment]
Just got another report of this from a user. Confirmed on my end. Using the copy button on a post is showing the 'Saving of draft failed' and 'Publishing of draft failed' errors. 837617-zen

**Comment by krutidugade** [comment]
Another user reported this issue. I was able to reproduce on my test blog. 838111-zen

**Comment by juliasydnor** [comment]
Another user report: 837351-zen

**Comment by separatelyunited** [comment]
Another user reported in HC tonight. Follow up ticket here: https://woothemes.zendesk.com/agent/tickets/839516

**Comment by sandymcfadden** [comment]
A bit of extra information when helping trouble shoot a report of this issue. When trying to save the draft it is making a call to https://public-api.wordpress.com/rest/v1.2/sites/undefined/posts/new where `undefined` should be the site id or domain.

**Comment by gugaalves** [comment]
Another user report: 839922-zen

**Comment by nellofn** [comment]
Another user reported the error here 491650-c

**Comment by SiobhyB** [comment]
This was report in HC again earlier today. Following up in 840043-z.

**Comment by jenlynnemc** [comment]
User reported this here: 1263583-c
I also duplicated this issue on my test site.

**Comment by gugaalves** [comment]
+1 ser report: 840262-zen

**Comment by sstabrizi** [comment]
Another user reported this issue here: 1264678-hc
I'm following up here: 840330-zen

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided. I tried several routes to for both the [Copy a Post](https://en.support.wordpress.com/posts/copy-a-post/) and [Copy a Page](https://en.support.wordpress.com/pages/copy-a-page/) features (i.e. from the Published Posts list, from Drafts, from a new post, etc.), and I was unable to save or publish any post or page that has been copied first. I tested with Firefox 57.0.1 on Mac OS X 10.13.1 on a WordPress.com Simple blog logged in as a regular user.

<strong>Video:</strong> [2m50s](https://cloudup.com/cOvqSda2ZW1)

**Comment by jblz** [comment]
This usage of `selectedSite` is possibly related:

https://github.com/Automattic/wp-calypso/blob/2455cab8c7031cfe2810082c0bb77ad0da3b4fb5/client/post-editor/post-editor.jsx#L716-L718

**Comment by Copons** [comment]
@jblz Very related but not exactly the problem. :)
