### ISSUE TITLE
How to install Calypso on Windows

### ISSUE THREAD

**Issue by austinsdev** [Automattic/wp-calypso#2066]
I am trying to install calypso on windows with Cygwin after run "make run"  command I am getting this error

"
             _
    ___ __ _| |_   _ _ __  ___  ___
   / __/ _` | | | | | '_ \/ __|/ _ \
  | (_| (_| | | |_| | |_) \__ \ (_) |
   \___\__,_|_|\__, | .__/|___/\___/
               |___/|_|

module.js:339
    throw err;
    ^

Error: Cannot find module 'D:\cygdrive\c\Program'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
module.js:339
    throw err;
    ^

Error: Cannot find module 'D:\cygdrive\d\Angular\clones\wp-calypso\wp-calypso\bin\check-node-version'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
Makefile:81: recipe for target 'node-version' failed
make: *** [node-version] Error 1

"
Can any one explain me how can I install Calypso on windows after clone?

**Comment by Viper007Bond** [comment]
See #592. In short, for a variety of reasons it doesn't work on Windows and as a fellow Windows user I sympathize :(

However we have an internal [Vagrant](https://www.vagrantup.com/) bootstrapper that spins up a VM that honestly works a lot better than it ever work natively. It's what I use personally and we hope to open-source it at some point in the near future.

**Comment by stephanethomas** [comment]
@austinsdev, I just wanted to let you know that we have released this [portable development environment](https://github.com/Automattic/wp-calypso-bootstrap) based on Vagrant that simplifies the task of running Calypso on Windows. Enjoy!
