### ISSUE TITLE
Store: Add Currency Selector to Address Settings Page

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#20675]
In order to allow for non US/Canadian stores to use the Store feature - or to enable other countries to go through the NUX/Setup flow, we need to add a currency selector to the Address Page.

__Current Address Settings Page__
<img width="1439" alt="12" src="https://user-images.githubusercontent.com/22080/33788584-fe9c6530-dc27-11e7-8720-a055f5141d14.png">

The first screen in the Woo setup wizard includes the currency drop down, so if we can emulate that, it is one step in the direction of supporting other countries, but also allowing NUX/Signup to flow through this step:

<img width="766" alt="wc-setup" src="https://user-images.githubusercontent.com/22080/33788650-429fa170-dc28-11e7-9c71-accab370b618.png">

@greenafrican noted in our hangout this week that a list of currencies is already in use for Store stats and could likely be used here too:
https://github.com/Automattic/wp-calypso/blob/master/client/lib/format-currency/currencies.js

**Comment by allendav** [comment]
@kellychoffman @timmyc - I think we can defer this issue for now since #21297 is able to send nonUS nonCA to the WooCommerce wizard where users can pick the currency themselves (and since #21297 does NOT push a currency default for nonUS nonCA stores, the WooCommerce setup wizard will propose an appropriate default there anyways.)

**Comment by kellychoffman** [comment]
Agree. Store owners can currently change currency on the Payments page. I added another issue to add weight and dimension units to the Shipping page: https://github.com/Automattic/wp-calypso/issues/21279. 

Closing this issue. Reopen if you disagree.
