### ISSUE TITLE
Media: Item count unclear when selecting different media types

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#20686]
While testing out the free photo library, I noticed that the media count can get a bit confusing if I'm searching for different queries. The count continues to increment if I select an image from a different query or a different file type even if I navigate away.

#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Click "Add +" to insert a media item
3. Select "Media"
4. Click on a Media item to select it
5. With the item selected, click the search icon to search your library. Search for a term that excludes the currently selected item, but still surfaces more items to click.
6. Click an additional item.

You'll notice the count is now "2," which is correct, but it could be confusing if I didn't remember clicking the first item.

For the "Free photo library," I experienced this when I selected an item, searched an entirely different query, and selected another item. The count incremented to "2," but unless I remembered the previous query, I couldn't "unselect" the item.

#### What I expected
This is actually awesome behavior, and it matches my expectation. However, it would be awesome if I had a little gutter to see the currently selected images.

#### What happened instead
I can't tell what images are selected.

#### Screenshot
Here's an example of a screen where the count is "2" but I really don't have a great idea of what "1" is:

<img width="961" alt="screen shot 2017-12-09 at 10 41 43 am" src="https://user-images.githubusercontent.com/7240478/33797936-9f570c6e-dccd-11e7-8ffc-2c79ffb2682c.png">

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided on Firefox 57.0.1 on Mac OS X 10.13.1.

> This is actually awesome behavior, and it matches my expectation. However, it would be awesome if I had a little gutter to see the currently selected images.

Agree, and I'm also really on the edge about whether to keep this issue open, since Media is not under active development at this time. I would ❤️ another opinion on it.

**Comment by dcoleonline** [comment]
The first time I tried this, I was really happy that it kept my selections, but I do agree that it'd be nice to see thumbnails of what was already selected.

Maybe for now we could have a Guided Tour built that explains how things currently work as they are?
