### ISSUE TITLE
Theme Showcase: Inconsistent whitespace/spacing of Live Demo dialog buttons/dropdown

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#20696]
#### Steps to reproduce
1. Go to the Theme showcase
2. Choose Live demo for a theme
3. See the buttons at the top of the dialog

#### What I expected
Consistent whitespace and spacing between/around the buttons

#### What happened instead
Inconsistent whitespace/spacing between/around the buttons

#### Browser / OS version
Chrome on macOS

#### Screenshot / Video
![screen shot 2017-12-11 at 11 53 22](https://user-images.githubusercontent.com/184938/33830959-eab8d7de-de7e-11e7-8fa9-5616f419243e.png)

#### Context / Source

#reallife #dogfooding #manual-testing

**Comment by drw158** [comment]
The mixing of primary and secondary buttons is also off. There is no reason to put a secondary button in-between 2 primary buttons.

**Comment by kjellr** [comment]
Closing this issue, since the button in question no longer exists. As per the thread in #20664, it doesn't appear that we'll be adding it back anytime soon.
