### ISSUE TITLE
.org Plans: Cannot cancel my plan

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#207]
If I go to the My Upgrades page, I don't see the option to cancel:

![d5931bde-7266-11e5-8ae0-2a383a4a796d](https://cloud.githubusercontent.com/assets/11487924/11277617/4699e6ae-8eb5-11e5-8967-671f055069ae.png)

**Comment by designsimply** [comment]
I checked for a My Upgrades option in `wp-admin` under Store (for a WordPress.com account) and I saw that it has been changed to Manage Purchases, so I think My Upgrades may have been retired.

![screen shot 2016-04-29 at fri apr 29 4 59 17 pm](https://cloud.githubusercontent.com/assets/1119271/14931879/85fa1fb6-0e2c-11e6-8421-c6e373ac4c84.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/ using Chrome 50.0.2661.86 on Mac OS X 10.11.4</sup>

I don't see an option to cancel the Manage Purchases page:

![screen shot 2016-04-29 at fri apr 29 5 01 58 pm](https://cloud.githubusercontent.com/assets/1119271/14931895/a5cbbfa2-0e2c-11e6-8db7-029d469c5dff.png)
<sup>Seen at https://wordpress.com/purchases/wildly.disambiguously.com/6041346 using Chrome 50.0.2661.86 on Mac OS X 10.11.4</sup>

**Comment by kriskarkoski** [comment]
This works as expected for me now with a Remove option shown for me on both an existing .org Premium plan as well as a newly purchased plan:

<img width="734" alt="screen shot 2016-08-01 at 1 53 35 pm" src="https://cloud.githubusercontent.com/assets/1900444/17303612/6cb6e75c-57ef-11e6-88ca-bf439f0dc033.png">
