### ISSUE TITLE
Reader Tags Fixes

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#20705]
fixes associated with: p5PDj3-4is-p2
- [ ] name fixes
- [ ] tag not found
- [ ] back button placement for non-existing tags

cc @gibrown

**Comment by bluefuton** [comment]
As a tester, it would be handy if there was more detail on each problem here (or ideally split into separate issues).

**Comment by samouri** [comment]
Sure.

1. when you go to `/tag/@name` you should not see any error notices. It turns out to be the same issue as number 2:
2. when you got to a non-existent tag you shouldn't get weird behavior or error notices.
3. the back button should always be in the right place

**Comment by samouri** [comment]
closing because everything has been addressed between https://github.com/Automattic/wp-calypso/pull/20779 and https://github.com/Automattic/wp-calypso/pull/20799
