### ISSUE TITLE
Media library: media modal in site icon editor is missing styles

### ISSUE THREAD

**Issue by notnownikki** [Automattic/wp-calypso#20702]
#### Steps to reproduce
1. Start a new browsing session, go to wordpress.com
2. My sites (any site will do)
3. Go to settings
4. Underneath the site icon, click change

#### What I expected

The media library modal should pop up and render nicely

#### What happened instead

It looks bad, as if some styles are missing.

However, if you perform these steps :

1. Start a new browsing session, go to wordpress.com
2. My sites (any site will do)
3. Edit a post
4. Go to insert some media, but cancel
5. Go to settings
6. Underneath the site icon, click change

It loads the styles correctly for the site icon change.

#### Browser / OS version

Chrome 61, Firefox quantum

#### Screenshot / Video

![wheresmystylesat](https://user-images.githubusercontent.com/3314354/33837001-f43c09c6-de82-11e7-8202-f2f7fca11cb5.png)

**Comment by jeremeylduvall** [comment]
@notnownikki This is very likely the result of #18921 merging last week. I'm AFK today, but I can fix this tomorrow.
