### ISSUE TITLE
Reader Following/Manage Recs: moving targets

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#20706]
When loading `https://wordpress.com/following/manage` there is a jumpy experience with how post recs load that can be frustrating as a user.

It doesn't start with placeholders, so when the recs do load, everything else slides down. This can be a bad experience for anyone trying to click a button.

We can fix this by making sure there is a placeholder right when you load the page.

<img width="843" alt="screen shot 2017-12-11 at 1 37 44 pm" src="https://user-images.githubusercontent.com/4656974/33847480-a8a9b6c0-de78-11e7-8b70-40330d03bdaa.png">

cc @jancavan

**Comment by jancavan** [comment]
I see what you're saying. Placeholders are displayed, but they don't always show up. Any idea why?

**Comment by blowery** [comment]
i think we may delay showing the placeholders until we know we have recs. We should probably assume we'll have them and show them earlier.

**Comment by jancavan** [comment]
> We should probably assume we'll have them and show them earlier.

What needs to be done to make this happen?

**Comment by samouri** [comment]
just a probably small code-change.  I'm hoping to get to it later this week
