### ISSUE TITLE
Comments: Threaded View layout issues

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#20711]
There are several layout issues on the threaded view when the components hit the nesting depth.

#### Steps to reproduce
1. Start Calypso with `ENABLE_FEATURES=comments/management/threaded-view npm start`
2. Navigate to a comment post view.

#### What I expected
The child comments should show a single bottom border.

#### What happened instead
The child comments pile up and as many borders as child comments are show.

#### Screenshot / Video
![33195433-b3d4cb2e-d0d7-11e7-853c-8448c94f665e](https://user-images.githubusercontent.com/233601/33848602-07d4c518-de8d-11e7-98fa-649b0228ba04.png)

#### Context / Source
From https://github.com/Automattic/wp-calypso/pull/20077#pullrequestreview-78826192

**Comment by gwwar** [comment]
Removing from the milestone since this is under a feature flag
