### ISSUE TITLE
Signup: Themes cannot be purchased/activated in signup flow from logged out theme showcase

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#20717]
#### Steps to reproduce
1. Starting at URL (logged out of WordPress.com): https://wordpress.com/theme/photo-blog (or any other premium theme)
2. Select "Pick this design" and complete the signup flow.

#### What I expected

I expected to be presented with a checkout page during signup to purchase the theme, so it's activated when signup is completed.

#### What happened instead

I never had a chance to purchase the theme, and my new site has a default theme (Twenty Sixteen) activated.

If you select the Free plan during signup, checkout is skipped entirely. If you select a paid plan, you get a checkout page but only the plan (not the theme) is in the cart.

#### Browser / OS version

Mac OS 10.12.6, Chrome 62.

#### Context / Source
#manual-testing Found while retesting https://github.com/Automattic/wp-calypso/issues/8264

**Comment by rachelmcr** [comment]
@p3ob7o is this something your team could look into? Just want to make sure it doesn't slip through the cracks as it's impacting signup/checkout.

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided.

<strong>Result:</strong> selecting "Pick this design" on a logged-out theme page does not result in an opportunity to purchase the selected theme or a plan including the theme.

<strong>Video:</strong>  [1m7s](https://cloudup.com/cyv2nQozwhf)

![screen shot 2017-12-11 at mon dec 11 5 00 45 pm](https://user-images.githubusercontent.com/1119271/33860324-8397e27c-de95-11e7-9b56-9343d4892e20.png)
<sup>Starting here. Seen at https://wordpress.com/theme/photo-blog using Firefox 57.0.1 on Mac OS X 10.13.1 logged out.</sup>

It's also worth noting that the theme selection step was completely skipped in this flow and that I saw some errors flash (but not for long) that made it seem like the account wasn't going to be created (even though it was).

![screen shot 2017-12-11 at mon dec 11 5 07 00 pm](https://user-images.githubusercontent.com/1119271/33860397-d0c88682-de95-11e7-8958-327b86fc2272.png)
![screen shot 2017-12-11 at mon dec 11 5 07 03 pm](https://user-images.githubusercontent.com/1119271/33860399-d2816642-de95-11e7-934e-165ef37bf301.png)

Account username: user428
Account blog: madefortesting126.wordpress.com

**Comment by ockham** [comment]
Looks like this has been reported before: #20316 (almost 2 weeks ago! :slightly_frowning_face: )

**Comment by seear** [comment]
Seems like this was broken by #18557 in late October. That PR renamed the [`queryObject` prop to `initialContext`](https://github.com/Automattic/wp-calypso/pull/18557/files#diff-46ce4cd8580489aebbb3447a87c3cb57L101) without changing all uses of that prop, one of which is [determining the chosen theme](https://github.com/Automattic/wp-calypso/blob/9914e4cd42d7a1d00b824370fadfb0a782619970/client/signup/steps/domains/index.jsx#L105) on signup.

**Comment by rachelmcr** [comment]
@hoverduck What do you think of adding a test for this (signup through `/themes` with a premium theme) to the e2e signup spec?

**Comment by hoverduck** [comment]
> What do you think of adding a test for this (signup through /themes with a premium theme) to the e2e signup spec?

@rachelmcr Sounds like a good idea.  I'm hesitant to add new tests that lengthen our test runtime, but anything involving purchases is probably important enough to go ahead with.

**Comment by seear** [comment]
Fix in #20746.

There is a separate, unrelated issue where it is not possible to purchase a theme at signup when purchasing a dotblog domain. This seems to be some kind of server-side cart issue, where even though Calypso is adding the theme to the cart using the cart API, the theme doesn't end up in the cart at checkout. The initial selection of a dotblog domain seems to add a premium plan to the cart on the server, which may have something to do with the theme not being properly added (all themes are free with the premium plan).

I can take a closer look at the dotblog issue later.

**Comment by ockham** [comment]
I tried to repro this. It fails, but for different reasons: after completing signup, I'm not logged into WP.com (and taken to my cart and checkout) but to the log-in form which asks me to verify my email address first.

**Comment by ockham** [comment]
The issue I'm seeing ^ might be unrelated to this one -- possibly due to different locale? 

Although UI strings are displayed in English for me; I do get a note telling me 'Auch verfügbar in Deutsch' ('Also available in German') at Step 1 (domain selection).

**Comment by rachelmcr** [comment]
@ockham That could be related to the email address you used in testing (see internal ref: p58i-6Oi-p2).

**Comment by ockham** [comment]
I did use a work `+throwaway` email address. Good point @rachelmcr, didn't occur to me -- will test with a different one!

**Comment by seear** [comment]
#20746 is now merged and fixes premium theme purchase and activation on signup with free and personal plans.

There are (at least) two remaining issues:
* Signup with a premium theme when purchasing a dot blog domain does not include the theme in the cart (this looks to me like an API/back-end cart problem)
* Premium themes are not activated when signing up with a premium plan or higher

My hunch is that neither of these issues is recent, or necessarily a Calypso problem. @rachelmcr should we create separate issues for these problems and assign them to appropriate theme or signup teams?

**Comment by designsimply** [comment]
<blockquote>My hunch is that neither of these issues is recent, or necessarily a Calypso problem. @rachelmcr should we create separate issues for these problems and assign them to appropriate theme or signup teams?</blockquote>

Yes, please! 

Issues don't get assigned to specific themes (and these issues cross different areas such as NUX/Signup/Purchases/Themes) so labeling with the area of work that fits closest is the way to go.
