### ISSUE TITLE
Store - SKU pencil doesn't activate edit mode

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#20774]
On the add/edit product screen we display a little pencil icon next to the auto-generated SKU. Hovering it changes the appearance but clicking doesn't activate edit mode - you have to click the text instead.

**Comment by designsimply** [comment]
Tested and confirmed using the following testing steps:

1. Go to My Sites > Store > Products > Add.
1. Type in a product name.
1. Try to click the pencil icon that appears next to the SKU below the product name.

<strong>Result:</strong> the pencil icon does change color on hover but is not clickable. The spacing is off a big for the text itself (trash-pickup-worthy). I also noticed there is an error in the console on that page, but it looks unrelated.

![screen shot 2017-12-13 at wed dec 13 2 45 15 pm](https://user-images.githubusercontent.com/1119271/33964248-0b1669f0-e015-11e7-8068-0b6e5360744c.png)
<sup>Seen at https://wordpress.com/store/product/madefortesting347.blog (Atomic) using Safari 11.0.1 on Mac OS X 10.13.1.</sup>

Console error:

> Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)
> https://wordpress.com/calypso/sections/woocommerce.css.map
