### ISSUE TITLE
Reader: Unable to Like Posts

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#20807]
The issue is that a WordPress.com user is unable to like posts in the Reader. 

I was not able to reproduce, but user can.

See screenshot below for error in browser console for `build` JS.

#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Click Like on a post

#### What I expected
Star and like button remain orange when clicked, visiting post on site shows it as Liked.

#### What happened instead
Star animates orange and then goes back to blue; looking at post on the source site, it is not liked.

#### Browser / OS version
Firefox

#### Screenshot / Video
Video of event:
https://cloudup.com/cM4t7eLDsG2

Screenshot of console error:
<img width="1680" alt="screen shot 2017-12-12 at 9 19 16 pm" src="https://user-images.githubusercontent.com/2031017/33965641-c6268900-e0b0-11e7-95cc-8d34af8e5fda.png">

#### Context / Source
#user-report

**Comment by kristarella** [comment]
from ticket #843921-zen

**Comment by designsimply** [comment]
I was unable to reproduce the problem using steps provided and testing with Firefox 57.0.1 on Mac OS X 10.13.1. ([17s](https://cloudup.com/cbecfO583oq))

Noting the error from the console in the screenshot provided for reference:

> InvalidStateError
> build.b63aeef008876d50b973.min.js:44:5910

**Comment by blowery** [comment]
Hrm, any chance they're using a private browsing window there? https://github.com/localForage/localForage/issues/70 looks like it might affect us.

**Comment by lancewillett** [comment]
Please re-open if we get more reports to indicate a broader pattern (probably local or something resolved on its own; or logging out and back in to Calypso).
