### ISSUE TITLE
Inaccurate messaging for subdomains: "X domains are not offered on WordPress.com"

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#20804]
If you try to map a subdomain, e.g. sub.domain.com, it'll say ".com domains are not offered on WordPress.com". 

#### Steps to reproduce
1. Starting at URL: wordpress.com/domains/add/
2. Type in a subdomain, e.g. sub.domain.net or .com

#### What I expected
To not get a message that tells me the TLD isn't offered.

#### What happened instead
It tells me .COM, .NET, rather any TLD is not offered on WordPress.com.

#### Browser / OS version
Chrome, latest

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6505293/33963696-a2a89998-e077-11e7-816c-5e5ceba899a3.png)

#### Context / Source
#dogfooding #manual-testing

**Comment by klimeryk** [comment]
Yeah, it's something probably introduced in https://github.com/Automattic/wp-calypso/pull/20654 (or at least not improved by it ;)). cc @aidvu @delputnam

**Comment by delputnam** [comment]
Fixes for this pending review in #21452 and D9250-code.

**Comment by rachelmcr** [comment]
Closing as this issue was resolved per the above fixes.
