### ISSUE TITLE
Reader: send post notifications to subscribers when a new post is published

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#20829]
Should be triggered by a new post being published and send notifications to all of the site's subscribers.

**Comment by blowery** [comment]
A lot of this code is already in place. see r164611-wpcom for the spot where we need to find all the subscribers

**Comment by blowery** [comment]
We probably _don't_ want so spin up a job just to find the subscribers and queue up the notifications. Last I knew, systems preferred that we do that work in the existing async_publish_post job that the previous commit is part of.

**Comment by blowery** [comment]
That said, there may be a subscriber count threshold where we _want_ to spin up a job so that we can control how fast these notifications flow out. @westi any thoughts here?

**Comment by westi** [comment]
I suspect we will need to model things on how we send emails with master/child jobs in the end once the volume of these grows.

But to begin with I would start as simple as possible and call out to a function in async_public_post to do the work

**Comment by bluefuton** [comment]
@blowery fixed this in D9272-code. 🚀
