### ISSUE TITLE
Store: Should Payment Pending Orders Create Notifs?

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#20847]
In order to test this in action, you need to make sure your notification setting for Store Orders is turned on:

![notif-settings](https://user-images.githubusercontent.com/22080/34017051-eddc3332-e0d8-11e7-9811-d0f56e5b7207.png)

#### Steps to reproduce
1. Using wp-admin, or a local branch, create a new store order
2. Add a product, and customer data.
3. Save.
4. Note the... notif!

The orders are created with the `pending` state, since payment has yet to be remitted. I was a bit surprised that the notif appeared when testing order creation, so figured it was worth opening up an issue to discuss.

/cc @justinshreve

**Comment by justinshreve** [comment]
Yeah, good call. We probably shouldn't be firing these for pending orders.

Right now the notification is only generated when the order syncs the first time, so I think we also need to look at when the status of an order changes, so we can catch `payment pending -> payment received`.

**Comment by justinshreve** [comment]
@timmyc I have a fix for this ready at D8838-code.

I also posted D8828-code earlier which also touches notifications. FYI in case you want to test both.

**Comment by timmyc** [comment]
I will give both a test today, thanks for the quick fix!
