### ISSUE TITLE
Comments: make header in single post view sticky

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#20844]
While interviewing users, some had trouble distinguishing the single post view from the default view. Sticking the header component to the top of the viewport will help orient users.

![screen shot 2017-12-14 at 3 28 30 pm](https://user-images.githubusercontent.com/618551/34015400-eb325cd2-e0e3-11e7-9a90-b996189dc211.png)

Example of sticky header:

![screen shot 2017-12-14 at 3 29 03 pm](https://user-images.githubusercontent.com/618551/34015401-eb3f92f8-e0e3-11e7-96ab-2f7374c302e8.png)

**Comment by gwwar** [comment]
Do we have existing sticky functionality for navigation? I'd probably try to generalize the issue if not.
