### ISSUE TITLE
Login: Generate Strong Password button styling broken

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#20840]
Reported by @melchoyce 

When you are resetting your password, the "generate strong password" button/link is mis-styled.

![image](https://user-images.githubusercontent.com/12596797/34011725-0455e3dc-e0df-11e7-98b8-04a85c203fb2.png)

I'm not sure if it's suppose to be a button or link but likely introduced by some css updates for buttons.

cc @stephanethomas @cburton4

**Comment by stephanethomas** [comment]
Thanks for reporting this issue. However this page has not been ported to Calypso yet, and after a quick look it appears that this change was introduced with the merge of version 4.9 of WordPress.org (see D8231-code for more information). I've already pinged @mermel about this, so let's close this GitHub issue.

**Comment by melchoyce** [comment]
lol, that's ironic.
