### ISSUE TITLE
Theme preview: scaling artifacts when scaling down to phone size

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#20853]
1. Starting at URL: https://calypso.live/theme/small-business/SITE_URL
2. Open Live Demo
3. Make sure demo is in tablet or desktop size
4. scale down to phone size

#### What I expected

I didn't expect to see artifacts at the right edge of the preview.

#### What happened instead

I saw artifacts at the right edge of the preview.

#### Browser / OS version

The latest Safari (11.0.2) on the latest macOS (10.13.2). 

#### Screenshot / Video

![width-artifacts](https://user-images.githubusercontent.com/23619/34037885-a9fd21dc-e18a-11e7-971f-11771658e542.gif)

Introduced in #20836.

**Comment by lancewillett** [comment]
Closing as wontfix, minor.
