### ISSUE TITLE
Simple Payment: add an image from media library

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#20870]
As of now, when creating a Simple Payment button, to add an image, you have to upload it from your computer. It would be nice to have the option to select a picture from the media library.

Here's a GIF showing that we don't have any other option than getting the picture from our computer:

![screen capture on 2017-12-15 at 18-04-38](https://user-images.githubusercontent.com/16645645/34052397-7fe85b72-e1c2-11e7-8cc1-0e745226d7f9.gif)

**Comment by eduardozulian** [comment]
Also requested on 2836371-hc
