### ISSUE TITLE
My Purchases: leading zeros missing from card last 4 digits

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#20892]
#### Steps to reproduce
1. Make a purchase using a credit card where the last 4 numbers start with one or more 0 (for example, in Sandbox mode - [Stripe's amex test card](https://stripe.com/docs/testing#cards) `378282246310005`
2. Visit the Manage Purchases page, and click on the relevant purchase

#### What I expected
The last 4 digits of the card number to appear fully ( `0005`)

#### What happened instead
The first 3 zeros were truncated, only the last `5` appears.

#### Screenshot / Video
<img width="403" alt="screen shot 2017-12-17 at 13 26 46" src="https://user-images.githubusercontent.com/844866/34079051-fd9685f0-e32d-11e7-92c0-94e628e0ac6c.png">

**Comment by markpernotto** [comment]
I'd like to work on this. All of my WordPress.com sites use the 'free' Plan. How would I go about making a purchase in Sandbox mode using a free plan? I can't install plugins on my sites without upgrading to the Business plan, and I can't add the card on this page: http://calypso.localhost:3000/me/purchases/add-credit-card. 

Please let me know. Thank you!

**Comment by yoavf** [comment]
@markpernotto sorry - but I'm afraid sandbox mode is an employee only thing. Thank you very much for offering to help!
