### ISSUE TITLE
Guided Tours: requestGuidedTour doesn't work reliably

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#20915]
Some of the onboarding checklist tours cannot be launched reliably through `requestGuidedTour` but need to be triggered twice (the second time a tour gets requested it will usually work, and it doesn't seem to matter what tour was requested at the first attempt). 

Possibly related to #20553? 

/cc @markryall @dzver

**Comment by fditrapani** [comment]
Steps to reproduce this issue:

- Visit `https://wpcalypso.wordpress.com/start`
- Create a new site without checking any boxes under `What’s the primary goal you have for your site?`
- Click on `Do It`  for any task. You'll notice no tour is shown. Go back to the checklist and try it again, now you'll see the tour. 

## Screencast
![no-tour](https://user-images.githubusercontent.com/6981253/35228549-00fb94ae-ff5f-11e7-8f83-17fc043ba30e.gif)

**Comment by fditrapani** [comment]
I just tested this locally and this issue doesn't seem to be coming up in local dev environments, only on wpcalypso.
