### ISSUE TITLE
Facebook Pixel cannot be inserted into the Custom HTML widget do to "noscript".

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#20924]
#### Steps to reproduce
1. Starting at URL: 

Following our guide here:

https://en.support.wordpress.com/facebook-integration/#facebook-pixel

Create a Facebook Pixel code.

2. Copy the "noscript" portion, as described in the guide.

3. Open your customizer, and select a widget area:

https://wordpress.com/customize/

4. Since it's HTML code, select the Custom HTML widget.

5. Code cannot be used, because "Tag <noscript> is not allowed".

#### What I expected

Although the guide does explicitly state to use a Text widget, it natural to add the Custom HTML widget instead, and many users don't realize there's literally a widget named "Text". I expected the widget to be publishable, or display a more visible error message.

#### What happened instead

The error message is hard to see, and our users may not realize to hover over the X. It's also unclear from a user perspective why sometimes codes/shortcodes go in the Text widget, and some in the new Custom HTML widget.

#### Browser / OS version

Version 63.0.3239.84 (Official Build) beta (64-bit)
Debian Stretch 

#### Screenshot / Video

![tooltip_001](https://user-images.githubusercontent.com/10121835/34127457-d7a1ed28-e402-11e7-9a0e-6f15755919a7.jpg)

**Comment by lancewillett** [comment]
I don't think this is a Calypso issue, right? Either core WordPress or something specific to the WordPress.com Customizer, perhaps. Closing as this isn't related to this project.
