### ISSUE TITLE
Reader Search: margin is inconsistent on first row of recommendations

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#20936]
I've noticed that we have the wrong margin for the first row of recommendations on Reader Search at selected breakpoints:

<img width="1280" alt="screen shot 2017-12-19 at 07 40 49" src="https://user-images.githubusercontent.com/17325/34146231-14fb386c-e491-11e7-92b0-839284728153.png">

<img width="512" alt="screen shot 2017-12-19 at 07 43 36" src="https://user-images.githubusercontent.com/17325/34146243-1d74e0a6-e491-11e7-8751-7ff831fb9d75.png">

Oddly, this only happens on first load. If you enter a search query and then return to the default recommendations, it works fine.

As a sidenote, the placeholders are also cropped at the bottom:

<img width="992" alt="screen shot 2017-12-19 at 07 37 38" src="https://user-images.githubusercontent.com/17325/34146270-3c766024-e491-11e7-8675-f4b9fe1236bb.png">

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/read/search

**Comment by jancavan** [comment]
I've come across this @bluefuton.

Didn't we remove all styles associated with this before and fixed it via JS @samouri?

**Comment by samouri** [comment]
Ah, I see the margin issue. I can reliably reproduce it by starting from `/` and then clicking Search.  Basically anything will fix the issue, including resizing the page very slightly.

My guess is that this is a really easy fix, i'll take a look now.

> As a sidenote, the placeholders are also cropped at the bottom:

Lets make a separate issue for that
