### ISSUE TITLE
Editor: Image loading indicator is not centered on MSEdge

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#20945]
#### Steps to reproduce
1. Starting at URL: Wordpress.com
2. open the editor
3. upload few images from your disk

#### What I expected

Image loading indicator is centered as it is on other browsers

#### What happened instead

Indicator appear on top of the image

#### Browser / OS version
MSEdge / WIN10

#### Screenshot / Video

![screencast 2017-12-19 17-58-37](https://user-images.githubusercontent.com/5654161/34154754-3dc664a8-e4e9-11e7-8cad-b034ce50df6f.gif)

#manual-testing

**Comment by flootr** [comment]
hey, i'd like to take care of this one - cool? @brbrr @designsimply

**Comment by alisterscott** [comment]
> hey, i'd like to take care of this one - cool?

@flootr feel free - I've assigned it to you
