### ISSUE TITLE
Media: Number selected badge text overflow with >3 digits

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#20956]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/example.wordpress.com
2. Select 1000+ images
3. Observe

#### What I expected
To have the text fit inside the circle

#### What happened instead
![wp-calypso-media-library-select-overflow](https://user-images.githubusercontent.com/7233112/34170749-0a5037a4-e4ba-11e7-9f87-29d4322a1c0a.png)

#### Browser / OS version
Chrome Linux

#### Context / Source
#manual-testing

**Comment by lancewillett** [comment]
Good find. 👍

**Comment by jdlrobson** [comment]
What should it do? I see various options
1) display or 99+ for numbers greater than 100 (999+ is 4 digits so we'd have to cap it there)
2) display a replacement symbol that means "high number" (Chrome for instance doesn't show numbers over 99 and gives [a smile instead](https://www.cnet.com/news/two-easter-eggs-hatch-in-chrome-for-android/)
3) Let the circle expand (per description) but then that changes the problem from a > 3 digit problem to say a > 6 digit problem.

Personally 1) seems like the simplest thing to do here. Seems like a good first bug if so.

**Comment by lancewillett** [comment]
Good points @jdlrobson — let's start with the first option.

**Comment by SnGrimes** [comment]
Is anyone working on this?

**Comment by rachelmcr** [comment]
Closing as resolved in https://github.com/Automattic/wp-calypso/pull/21633.
