### ISSUE TITLE
Suggestion: Notice on Page slug availability when force-changed, before publishing

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#20963]
Assume there is a Page named About with the slug **_/about_**

**Steps to reproduce:**

- Open the Page creation screen https://wordpress.com/page/example.com
- Enter the Page name, something like About
- The slug will be generated as **_/about-2_**
- Edit the slug to **_/about_** again (before publishing)

**Expectation:** A notice is shown that the slug **_/about_** is occupied and that only **_/about-2_** can be assigned.

**Result:** There is no such notice. User is informed that the slug is **_/about-2_**, _after publishing_.

![no slug notice issue on wordpress com calypso](https://user-images.githubusercontent.com/18581859/34175578-ebebde4e-e522-11e7-9468-3a717429b7c2.gif)

This is not very ideal. #painpoint

**Comment by arunsathiya** [comment]
I just added a GIF, @designsimply. Helps understand this better. FYI.

**Comment by alisterscott** [comment]
Confirming this is still an issue we'll keep it open

#bug-scrub #pre-gutenburg-bug-purge

**Comment by millerf** [comment]
What would be the best behaviour?

- test the slug availability on it gets out of focus (typing is finished) and add an indicator
- test right before saving the post
- test right before  publishing the post
