### ISSUE TITLE
Store: Don't record tracks for test users

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#20962]
D8917-code has a patch for order, product, and store creation.

For all other tracks, we need to:

* Update the preferences endpoint to return if a site is a test site or not
* Add logic to our special [recordTrack](https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/extensions/woocommerce/lib/analytics/tracks-utils.js) method.
* Update existing tracks calls to use the new WC method:
    - [ ] app/dashboard/manage-no-orders-view.js
    - [ ] app/dashboard/setup-task.js
    - [ ] app/dashboard/setup-tasks-view.js
    - [ ] app/dashboard/required-plugins-install-view.js
    - [ ] app/settings/payments/payment-method-item.js
    - [ ] app/store-stats/controller.js
    - [ ] app/store-stats/store-stats-chart/index.js
    - [ ] components/reading-widget/index.js
    - [ ] state/data-layer/ui/shipping-zones/index.js

**Comment by justinshreve** [comment]
Finally following up on this now that I have a computer again :).

@timmyc I put up a Phabricator patch to add a test flag like we talked about to the preferences endpoint. D9065-code. I can then use that to check against.

**Comment by timmyc** [comment]
Phab patch LGTM 🚢
