### ISSUE TITLE
Store: Spacing issues with the package dialog

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#20969]
There seems to be some spacing issues with the weight and max weight inputs with both the add and edit package dialogs:

<img width="747" alt="screen shot 2017-12-19 at 12 54 05 pm" src="https://user-images.githubusercontent.com/689165/34178363-c5377cfc-e4bb-11e7-822c-f47ec7a7279f.png">

cc @DanReyLop @marcinbot

**Comment by kellychoffman** [comment]
Note: This is happening in Firefox only. (Chrome and Safari are okay)

**Comment by jameskoster** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/20856
