### ISSUE TITLE
Store: When only one rate is present, it should be selected

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#20965]
Ran into this while testing https://github.com/Automattic/wp-calypso/pull/20414

The rates section is in an error state:  
![screen shot 2017-12-19 at 12 57 24 pm](https://user-images.githubusercontent.com/5835847/34176718-3acf4e5c-e4be-11e7-9cda-cd8d7dcdf234.png)

Instead, we should just automatically select it so its ✅  and the store owner only has to review it and aren't forced to select it themselves. This will give them one less step to complete when creating a label. 

@DanReyLop @marcinbot @jeffstieler

**Comment by dechov** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/22193 (long ago)
