### ISSUE TITLE
Media: add a timeline/date scrollbar (using <Scrollbar /> component) to find media uploaded during a specific time

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2097]
Raised by @justinshreve 

Using the `<Scrollbar />` component added in 4259-gh-calypso-pre-oss, enable scrolling through the list of media files by month in a timeline fashion. By month.

Pictured here:

![Image of file listing](https://cldup.com/YV1CA55-Fj-1200x1200.png)

Note from @kellychoffman

> I don't want to restyle the scroll bar. The date indicator would be helpful.

**Comment by brbrr** [comment]
I going to close it since media modal now shows upload dates. But it implemented in a bit different style.
