### ISSUE TITLE
Store: Duplicate child product category names result in confusing UI selectors

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#20977]
Since the `product_category` taxonomy supports a tree hierarchy, it is valid and plausible that users will have a Product Category structure like the following:

![categories](https://user-images.githubusercontent.com/22080/34184525-1106a6b2-e4d5-11e7-9c90-5f1a6d565be4.png)

Note the duplicate child category names for "Hats > womens" and "Shirts > womens" ( and mens for both too ). That category structure with duplicate child category names results in some confusing UI's in calypso Store:

__Promotions__
![child-categories](https://user-images.githubusercontent.com/22080/34184561-467aaf28-e4d5-11e7-8521-f007573a5180.png)

__Products__
![product-category](https://user-images.githubusercontent.com/22080/34184602-80cf016a-e4d5-11e7-8890-5b8d44f9bc67.png)

also on the products page, with duplicate child category names, we have some `key` collision errors being thrown:

![duplicate-keys](https://user-images.githubusercontent.com/22080/34184622-98beab54-e4d5-11e7-8d3f-0a2ed1c68292.png)

__Ideas__
Perhaps we could consider inclusion of the parent category name in these instances to help make the category a bit more clear, i.e. `Hats > womens` or `womens ( Hats )`. This could make the tokenfield implementation a bit more _interesting_.

Core, ironically enough, has the same issue in promotion/coupon setup:

![core-promotions](https://user-images.githubusercontent.com/22080/34184688-02252212-e4d6-11e7-9256-f1a0c1aabd40.png)

But uses the term-tree selector, akin to the category selector in the product editor:

![products-category-selector](https://user-images.githubusercontent.com/22080/34184700-1ae2b440-e4d6-11e7-9f93-fa741d7ea6f1.png)

/cc @justinshreve something to consider with category management - but if we use the tree selector for parent categories we should be okay.

**Comment by ryelle** [comment]
Fixed in #24275, parent labels are now added to each category
