### ISSUE TITLE
Jetpack Onboarding: Request user confirmation

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#20985]
We need to create an initial step when starting the onboarding process, where users agree to our terms and conditions. Confirming it should be a requirement to being able to continue the onboarding flow.

As @MichaelArestad mentioned, we can use a similar pattern to what we used for AL credentials. 

Another option (hat tip @johnHackworth) is to have the copy somewhere in the first Site Title step (above the button for example).

Let's think about some raw design mockups and possible copy we can use.

**Comment by MichaelArestad** [comment]
@tyxla Are there any precedent views already implemented with the latter option? I'm cool with that if it's quick to implement.

**Comment by tyxla** [comment]
@MichaelArestad It would be very quick to implement indeed.

Well, I don't think we've used it for terms & conditions, but we have a similar element in the signup flow (see the bottom): 

![](https://cldup.com/PWCKS5eNrw.png)

Maybe something like this would work well:

![](https://cldup.com/oyS7UZm9xQ.png)

where the link would lead to https://wordpress.com/tos/

What do you think? Also suggestions on improving the copy are most welcome.

**Comment by tyxla** [comment]
Also, if you think that would make it better, we can prepend an info icon, similar to how it's done on the checkout page:

![](https://cldup.com/YlHIyPFlNC.png)

**Comment by tyxla** [comment]
I'm going to draft this one shortly @MichaelArestad, will ping you for review.

**Comment by MichaelArestad** [comment]
@tyxla let's prepend it with icon. I think that's a good solution.

**Comment by tyxla** [comment]
@MichaelArestad: done in #21066, feel free to have a look when you get a chance.
