### ISSUE TITLE
Editor: Media: allow dragging to rearrange gallery items on mobile

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2099]
It's common for users to expect to be able to drag to rearrange things. Would it be possible to allow users to drag gallery items to rearrange them on mobile?

Example request: https://en.forums.wordpress.com/topic/editing-gallery?replies=2

For reference, here are two walkthroughs creating galleries and rearranging items on an iPad and iPhone:
1. [4m50s](https://cloudup.com/cwRYRvIMYNU) - Safari iOS 8.3 on iPad 3rd Gen (Retina)
2. [5m14s](https://cloudup.com/cIKm4kW6stS) - Safari iOS 8.3 on iPhone 6

Notes from @kellychoffman

> Thanks for the video walkthroughs! Definitely highlights a lot of the current frustrations with gallery management on touch devices. 
> 
> Drag and drop ability in galleries would definitely be nice to have. The current iteration of the Cloudup editor allows you to do so. Whether or not this continues to be the case, we will definitely keep this in mind when building out gallery creation in the new media modal.

**Comment by ryanboren** [comment]
This post mentions the usability of the reorder arrows on phones. https://test.wordpress.com/2016/02/02/editor-images-in-multi-select-image-upload-are-replaced-with-dupes-of-first-image-iphone-6/

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Closing because this should be addressed in Gutenberg directly. Note that it may need to be re-opened after we switch to the Gutenberg editor.
