### ISSUE TITLE
Me: Security - 2FA - Compact notice close link is not aligned

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#21]
I was running through the steps to disable and then re-enable 2FA today and came to the step where it asked me to type my verification code. Since I had just done so to enter /me, I had to wait a bit. I got this notice and the X was underlined and not aligned to the top right. It was also is-info and would probably make more sense as a is-warning.

![image](https://cloud.githubusercontent.com/assets/7233112/11217971/fcaecbda-8d20-11e5-86c7-0e5ea3f5d1ee.png)

Error message too:
![image](https://cloud.githubusercontent.com/assets/7233112/11217980/07bf493c-8d21-11e5-9312-4c984f3a77ef.png)

Should be simple CSS and HTML class fixes here

**Comment by ebinnion** [comment]
This seems to have already been fixed, likely by pre-OSS PR 12107.
