### ISSUE TITLE
Store Orders: Enable store owners to grant new discounts to pending-payment orders

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#21000]
A store owner can apply existing coupons to orders, but if the store owner wants to grant a specific discount, they currently need to go and create a coupon, then come back to the order edit screen to apply it. We want to make it possible to do this without leaving the order edit screen.

Discounts are tied to coupons, so we can do this in one of two ways (other suggestions welcome):

- We make the discount value editable, and custom values entered would be considered "negative fees", giving the customer a discount while bypassing coupons entirely. This would show up in the line items section with the other fees (though we could swap the `FEE` label with `DISCOUNT`).
- We add a simplified coupon creation flow in the order screen, maybe just to create a fixed cart discount, which is then immediately applied to this order when created - more technically involved, and the store owner might not realize they're creating multiple coupons via this method.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
