### ISSUE TITLE
Post List: Post Items should be clickable

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#21007]
Since the move to condensed post lists, I'm increasingly bothered by not being able to click / tap anywhere on a post card to begin editing the post.

#### Steps to reproduce
1. Starting at URL: https://calypso.live/posts/
2. Attempt to click on a post item "whitespace" anywhere except for horizontally to the right of the title (in LTR locales)

#### What I expected
To be taken to the post & start editing (Or if I cannot edit the post, the "primary" action in the popover menu would make sense)

#### What happened instead
Nothing. The space is not clickable outside the `<a />` title link which spans the width of the card

#### Browser / OS version
Chrome Stable / Mac High Sierra

#### Screenshot / Video
![condensed-post-list-largely-unclickable](https://user-images.githubusercontent.com/1587282/34221340-b01ef596-e585-11e7-8b49-f287ed427de3.gif)

**Comment by mattsherman** [comment]
@Automattic/tanooki will take care of this.

**Comment by mattsherman** [comment]
Improved by #21315.

We decided not to make the entire post item clickable for now, as we were concerned about mis-clicks close to the glanceable info (views, likes, comments). Made featured image, site/author name, and data clickable.

Can be revisited in the future again when further improvements to the post list design are considered (focusable items).
