### ISSUE TITLE
Store: Dashboard: Setup view can appear after force refresh on settings

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#21008]
#### Steps to reproduce
1. Starting at URL: wordpress.com/store/{DOMAIN}
2. Click on settings and force refresh (Command Shift R)
3. Click on dashboard

#### What I expected
To see the "Hi Allen. You have new orders" dashboard

#### What happened instead
I see the "Have something to sell?" dashboard (aka Set up my store)

#### Screenshot / Video
![dashboard-regression](https://user-images.githubusercontent.com/1595739/34223618-db13d926-e574-11e7-899e-846daf50000e.gif)

**Comment by timmyc** [comment]
I can reliably reproduce this issue with the following steps:

- Click on a View Order link from a new order notif
- From the order detail view, click the dashboard link
