### ISSUE TITLE
Jetpack sites with Rewind should not reference VaultPress on My Plans page

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#21017]
On the My Plans page for a site with Rewind available (active, even), we still show this card:

![screen shot 2017-12-20 at 6 10 11 pm](https://user-images.githubusercontent.com/108942/34235844-8bbf3310-e5b1-11e7-87b5-2258944d6756.png)

We should change the button to something like "Visit Activity Log", and link it to `/stats/activity/{site}`

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/21023
