### ISSUE TITLE
UX feedback for MailChimp Integration

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#21014]
Noticed a couple of things that tripped me up when I was testing out the MailChimp integration in Store. They both occurred in step 3: 

1) Address - I didn't realize I needed to edit the address to be able to move forward. I saw that every field was required, but the address form was not expanded and the edit address link wasn't very obvious
<img width="616" alt="screen shot 2017-12-19 at 10 36 44 am" src="https://user-images.githubusercontent.com/161697/34232332-b1562cf4-e594-11e7-8dd5-6b9cb8621442.png">

2) Once I got past entering my address I was still confused why I couldn't move forward, it wasn't until I happened to accidentally scroll the view that I realized there were more fields to fill out
<img width="610" alt="screen shot 2017-12-19 at 10 37 05 am" src="https://user-images.githubusercontent.com/161697/34232380-e8b99a32-e594-11e7-983b-4b878e6113c8.png">

<img width="603" alt="screen shot 2017-12-19 at 10 37 17 am" src="https://user-images.githubusercontent.com/161697/34232429-1af8d328-e595-11e7-831b-bfcead3e60c0.png">

**Comment by jameskoster** [comment]
We should definitely highlight the address somehow if incomplete.

The scroll issue isn't specific to this modal. I think we should open a separate issue for that and investigate ways to make it more obvious when a modal can be scrolled.

**Comment by kellychoffman** [comment]
> We should definitely highlight the address somehow if incomplete.

Yes. Even better: we should make sure the address is complete in the initial store set up. (Pre egg dashboard)

**Comment by jameskoster** [comment]
Yeah, I'm surprised we don't already do that 🤔

We should probably close this out and create two separate issues.

**Comment by jameskoster** [comment]
Issues opened ^^

I'll close this one out. Thanks for the feedback @megsfulton !
