### ISSUE TITLE
Editor: The "Image Edit" button is broken without a particular class name

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#21045]
In the Visual Editor, I noticed that clicking the Edit button seen here:
<img width="360" alt="screen shot 2017-12-21 at 2 30 09 pm" src="https://user-images.githubusercontent.com/1587282/34271721-8ff27c6c-e65b-11e7-9b71-2dfc539c5252.png">
...does not work without the presence of a particular class on the `img` element in the content.

If you take a look at the [plugin](https://github.com/Automattic/wp-calypso/blob/0f69e72c8a8ae5afd13118663bf0480f7ce1b1cb/client/components/tinymce/plugins/media/plugin.jsx#L480-L484), it's looking for a class name like `wp-image-1234` where `1234` is the attachment id of the image. If it does not find that class name, clicking the `Edit` button does nothing.

Further, the pattern linked above is unanchored, so it would match a class name like `stuff-things-wp-image-1234-more-stuff`.

Moreover, if you change the numbers in the class name to the attachment id of another image, it will open that image instead!

![editor-edit-image-wrong-id](https://user-images.githubusercontent.com/1587282/34271993-91fbb072-e65c-11e7-979b-3e604d305d1d.gif)

Related to #16259

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post (choose a site if necessary)
2. Insert an image
3. In HTML mode, remove the `wp-image-###` class on the `img` element
4. Switch to Visual mode
5. Click the image
6. Click the `Edit` button

#### What I expected
To be able to edit the selected image

#### What happened instead
Nothing. No errors in the console.

If the class is changed such that the numbers point to another attachment, it opens that image in the editor.

If the class is changed such that the numbers point to a non-existing attachment, it opens the image editor w/ a blank image

#### Browser / OS version

Chrome Stable / Mac High Sierra

**Comment by designsimply** [comment]
Tested and confirmed using the following HTML for my test:

`<img src="https://imgs.xkcd.com/comics/virtual_assistant_2x.png" />`

<strong>Result:</strong> the pencil icon in the image toolbar is inactive—the resizing options are grayed out but the alignment, caption, and delete icons work as expected.
<sup>Tested using Firefox 57.0.1 on macOS 10.13.2.</sup>

#bug-scrub #pre-gutenburg-bug-purge

**Comment by rachelmcr** [comment]
I reproduced this image after copying an image in my web browser and pasting it directly into the editor. The resulting image (hosted on another site) still showed the edit button, but it didn't do anything.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
