### ISSUE TITLE
Reader: ES-powered tag streams can include sites with the blog sticker 'broken-in-reader'

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#21041]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/tag/bali?at=2017-12-21T02:22:00Z
2. Note that the first two posts are from a blog marked with the blog sticker 'broken-in-reader'

![screen shot 2017-12-21 at 18 12 32](https://user-images.githubusercontent.com/17325/34268976-a1facb66-e67a-11e7-8d1e-8e6e7b613b08.png)

#### What I expected

Posts from sites marked 'broken-in-reader' should not appear in the tag stream.

#### What happened instead

They did appear :)

#### Investigation

I did some preliminary checks and it did appear that the blog sticker is on the affected blog in the ES index, and there's also some code in the query builder to exclude this particular blog sticker.

cc @aaronyan @gibrown

**Comment by gibrown** [comment]
I think diff D8375 is the best way to address this.

**Comment by westi** [comment]
Updated D8375 and awaiting review

**Comment by bluefuton** [comment]
🚢 D8375-code shipped, which resolves this issue.
