### ISSUE TITLE
Jetpack: My Plans page "Free Plan" card

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#21052]
With a Free Jetpack site, visit the My Plans page and see this:

![screen shot 2017-12-21 at 2 55 01 pm](https://user-images.githubusercontent.com/108942/34276516-04dc0522-e65f-11e7-9bbe-6d44666cc41b.png)

Instead of "Unlock the full potential of your site with all the features included in your plan." we should have an upgrade prompt ("Upgrade your site to access all of Jetpack's features, and give your site a boost.", or something like that) and include a button labeled "Compare Plans" which takes them to the Plans view. Something like this (hacked quickly in Inspector, needs proper spacing etc):

![screen shot 2017-12-21 at 3 03 25 pm](https://user-images.githubusercontent.com/108942/34276774-1cf59adc-e660-11e7-8862-68e57167eebc.png)

cc @nicoleckohler for some better wording here.

**Comment by nicoleckohler** [comment]
@beaulebens Love this suggestion.

For the copy I'd say something like:

> Upgrade your site to access additional features, including spam protection, backups, and priority support.

This way we're being a bit more specific/enticing (and none of the features listed aren't in Personal, so we're accurate no matter what plan they choose... might even be worth revisiting once we shift what's in each plan).

What do you think?
