### ISSUE TITLE
Login: Split 2FA recovery codes into chunks

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#21067]
Longer 2FA recovery codes (7 or 8 characters) are quite difficult to remember at a glance.

Other services like Twitter split the code into chunks of 3 or 4 characters separated by a space, which are easier to remember and enter.

This would require:
- formatting of recovery codes in outgoing SMSes
- removal of restrictions on spaces in recovery code inputs
- stripping any spaces from the user input before checking validity of the recovery code

Current string example:

`33482332` is your WordPress.com recovery code.

Suggested string example:

`3348 2332` is your WordPress.com recovery code.

**Comment by cburton4** [comment]
Adding space in the existing design works well. 

![bitmoji](https://render.bitstrips.com/v2/cpanel/babe2cdc-f97b-4cb5-b869-e73cc05b5a0e-b72e8816-9f78-40e8-9df4-86358e85f091-v1.png?transparent=1&palette=1&width=246)
