### ISSUE TITLE
Login: Fix Jetpack connect flow requiring retry for passwordless accounts

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#21063]
Similarly to https://github.com/Automattic/wp-calypso/issues/15913, we should fix the connection flow which fails with a passwordless account, and prompt for a manual retry:

1. [Generate](http://poopy.life/create?src=inquisitive-macaw&key=g57uqr8kfjjn0Pwi) a new Jetpack site in an incognito window
2. Click the `all done! continue to your install` link
3. Click the `Connect to WordPress.com` button in the administration panel
4. Enter the username or email address of a passwordless account on the `Login` page
5. Click the link in the email you should have received by now
6. Click the `Finish Login` button
7. Click the `Approve ` button on the [`Jetpack Connect Authorize` page](https://wordpress.com/jetpack/connect/authorize)
8. Notice the following warning is displayed for a second:
> Error authorizing. Page is refreshing for another attempt.
9. Notice the `Jetpack Connect Authorize` page is reloaded
10. Notice the following warning is now displayed:
> In some cases, authorization can take a few attempts. Please try again.
11. Click the `Approve ` button again
12. Assert that you are redirected to the [`Jetpack Plans` page](https://wordpress.com/jetpack/connect/plans)
13. Assert a `Your site is now connected!` message is displayed

**Comment by yurynix** [comment]
Will be addressed in D9005-code

**Comment by yurynix** [comment]
D9005-code deployed

**Comment by rgenesis** [comment]
I really don't got it. I'm having this same error. This mesage don't tell me nothing. What means this? What is wrong in my server? So how can I fix this?

**Comment by rgenesis** [comment]
I thinking that my trouble is related to this here: https://wordpress.org/support/topic/connection-authorization-error/

As soon as achive the answer I will put the solution here.
