### ISSUE TITLE
“Polls and Surveys by Jetpack” appearing in Calypso

### ISSUE THREAD

**Issue by ntpixels** [Automattic/wp-calypso#21087]
"Polls and Surveys by Jetpack" appears when searching for "poll" plugins in Calypso for WordPress.com sites.

There is a WordPress.com polling functionality:
https://en.support.wordpress.com/forms/polls/

and Polldaddy for self-hosted sites:
https://polldaddy.com/

However, this appears to be a legacy feature from when Polldaddy was a part of Jetpack [plans]. Since that is no longer the case, the wording attributing polling functionality to Jetpack can cause confusion. Is there anything that can be done there to lessen that?

Perhaps it can refer to the Contact Form as a survey/information collection mechanism? If not, what about removing it entirely?

original ticket: #852884-zen
cc/ @beaulebens 

#### Steps to reproduce
1. Go to https://wordpress.com/plugins for any of your WordPress.com sites
2. Type in “poll”
3. See “Polls and Surveys by Jetpack” as already installed at the top left in the grid of choices:
<img width="1440" alt="pollssurveysjetpackcalypso" src="https://user-images.githubusercontent.com/3965153/34315443-7f3ef57e-e74d-11e7-8cea-6e3802fb2ad2.png">

Please note that neither “Jetpack” nor “Polls and Surveys by Jetpack” appears when searching for “poll” in a Pressable, sandbox, or entirely self-hosted Jetpack-enabled sites via Calypso.

**Comment by beaulebens** [comment]
This is still an issue, and the "Polls & Surveys by Jetpack" entry should really be removed.
