### ISSUE TITLE
[Activity Log] Add credentials looping

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#21088]
Created a brand new site: testtesttesttt.mystagingwebsite.com
Connected it to JP > added credentials and am now caught in a loop:

https://cloudup.com/clS4ASh9zVf

It continues to show the banner to add creds long after I've added them.

**Comment by eliorivero** [comment]
This is happening for me too. It's part of that transport server broken, because I can't rewind either

<img width="745" alt="captura de pantalla 2017-12-26 a la s 12 44 58" src="https://user-images.githubusercontent.com/1041600/34415374-1c79ef78-ebcd-11e7-8121-bcf5672e06a8.png">

cc @rcoll

**Comment by eliorivero** [comment]
Strangely enough, I went and revoked my credentials, auto configured them again, and now it's working. No credentials notice, can rewind and create backups.
