### ISSUE TITLE
Stats: back button is not behaving right in Posts & Pages View All

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#211]
Steps to reproduce:

1. Go to Days
2. Click "View All" on the Post & Pages module
3. Click on any post to view post Stats summary
4. Hit "< Back" (by now you'd be on the Post & Pages full list)
5. Hit "< Back" again (you're back on the Post Summary page)
6. Hit "< Back" again (you're now back on Days)

**Order of pages clicked:**
Days > Post & Pages View All > Post & Pages list > Post Summary Stats

**Current order when hitting "< Back":**
Post Summary Stats > Post & Pages list > Post Summary Stats <strong>(again)</strong> > Days

There is an extra view for "Post Summary Stats (again)" that shouldn't be there.

/hat tip jancavan, kriskarkoski for the original report and testing

**Comment by lancewillett** [comment]
The second scenario is now working as expected, for me. Testing with wpcalypso and Mac-n-Chrome.

1. Go to https://wpcalypso.wordpress.com/stats/day and select a site: https://wpcalypso.wordpress.com/stats/insights/testerlance.wordpress.com

2. I land on "Insights" link at the top, by default.

3. Click the "Followers" heading in that module.

4. Click the "< Back" link in the header — I end up at Insights again. https://wpcalypso.wordpress.com/stats/insights/testerlance.wordpress.com
