### ISSUE TITLE
WP-admin last modified showing future dates

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/wp-calypso#21124]
This may or may not be an unintended result from this commit: https://github.com/Automattic/wp-calypso/issues/18418 but Paulo E. Aquino found that in the wp-admin, the last modified dates act strange with drafts of pages and posts. In Calypso this is ok because there are separated tabs for scheduled posts and such, but the wp-admin gets confusing when you set a schedule date for a draft of a page or post. Essentially, that scheduled date becomes the "last modified" date.

#### Steps to reproduce
1. Starting at URL: example.wordpress.com/wp-admin
2. Create a page or post
3. Set the scheduled date and save as draft

#### What I expected
The "Last modified" area should show today's date

#### What happened instead
The "Last Modified" area shows the scheduled date

#### Browser / OS version
Chrome Version 63.0.3239.84 (Official Build) (64-bit) / MacOS 10.13.2 (17C88)

#### Screenshot / Video

User post ref: https://cloudup.com/cjkBe9Osr3O
Page ref: https://cloudup.com/cwe79nLuHED/f

**Comment by rachelmcr** [comment]
I'll close this issue since the behavior is in WP Admin and not Calypso, and this Github repo is for Calypso issues. :) This is core WordPress behavior, so it needs to be reported/discussed in the core trac repo. I found a related issue there: https://core.trac.wordpress.org/ticket/32386

**Comment by Piyopiyo-Kitsune** [comment]
Thank you @rachelmcr! I'll follow up in the core trac repo for an update on this.

**Comment by Piyopiyo-Kitsune** [comment]
Added to core trac: https://core.trac.wordpress.org/ticket/43014
