### ISSUE TITLE
Store: Fulfill Line Overflows in narrow viewports

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#21165]
Not a major bug, but a likely candidate for some easy trash pickup.

#### Steps to reproduce
1. View an Order Details Page for an un-fulfilled order
2. Resize your window to be a bit more narrow, but prior to triggering the breakpoint
3. Note the fulfillment line overflow

![fulfill-overflow](https://user-images.githubusercontent.com/22080/34447471-03b78500-ec99-11e7-9b62-5556ba5eb62b.png)

**Comment by kellychoffman** [comment]
This is addressed in #20854.
