### ISSUE TITLE
Stats: the number of followers in the Follow Blog widget and the Email Follower stats page don't match

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#212]
Steps to reproduce:

1. Add the Follow Blog widget to your blog
1. Go to https://wordpress.com/stats/follows/email and select your blog if prompted
1. Compare the number of followers shown in the widget to the one on the Email Followers stats page

<strong>Result:</strong> the numbers don't match.

I see 8,163 on the Follow Blog widget:

<img alt="screen shot 2015-11-19 at thu nov 19 6 17 50 am" width="320" src="https://cloud.githubusercontent.com/assets/1119271/11269540/89c78bd2-8e85-11e5-9a0a-a5d693e241f8.png" />

But only 20 listed on the Email Followers section in stats:

![screen shot 2015-11-19 at thu nov 19 6 26 08 am](https://cloud.githubusercontent.com/assets/1119271/11269696/a69c0bce-8e86-11e5-9272-7968960e5531.png)

Suggested changes:

* Change "Email Followers" to say "Email-only Followers" in the dropdown
* If there are no email-only followers, change the text on /stats/follows/email from "No followers" to "No email-only followers"
* Change the (i) text to explain the Follower-related stats more accurately

Current: 

<blockquote>Keep track of your overall number of followers, and how long each one has been following your site.</blockquote>

Proposed:

<blockquote>WordPress.com Followers are people who follow using the WordPress.com Reader and by email if they have opted to receive email. Email-only Followers are people who follow by email and not through the WordPress.com Reader.</blockquote>

/hat tip blowery, kriskarkoski for the original report and testing

**Comment by lancewillett** [comment]
Looks like the (i) informational area has gone away, testing with Safari 9.1 on OS X 10.11.4.

<img width="846" alt="screen shot 2016-04-07 at 16 41 09" src="https://cloud.githubusercontent.com/assets/66797/14370108/8e19f8b4-fcdf-11e5-9a0c-ebc2952274b1.png">

<img width="901" alt="screen shot 2016-04-07 at 16 41 02" src="https://cloud.githubusercontent.com/assets/66797/14370110/90cc80f4-fcdf-11e5-9eba-a14f28648903.png">

The numbers do add up though:

Publicize followers (Twitter + Facebook)
plus
WordPress.com followers
plus
Email followers

**Comment by lancewillett** [comment]
I suggest closing as "works for me."
