### ISSUE TITLE
Themes: show Jetpack user .com themes aside from locally installed ones

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2120]
~ This is part of a macro-feature to install .com themes to Jetpack, see #2123 ~

Raised by @mcsf 

**Scenario:** I want to see all the themes from WPCOM, as well as local themes

TODO:
- [ ] Combine data sources
- [ ] Figure out how search would work
- [ ] Filter? Visually differentiate?
  - Visual maybe something like the price, but that says “LOCAL”.

**Comment by folletto** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/9980
