### ISSUE TITLE
Editor: No option to remove geotagging

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#21202]
After a geotag has been added to a post or page, there is no option to remove that geotag.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. From the list of available **Post Settings** in the editor's right sidebar, select **More Options**.
3. From under **Location**, select the **Get current location** button to geotag the post with your current location.
4. **Publish** your changes.
5. Attempt to remove the geotag.

#### What I expected

I expected there to be an option to remove the geotag.

From this screenshot taken from [the Geotagging support documentation](https://en.support.wordpress.com/geotagging/#adding-a-location), it appears that there used to be a cross icon (and therefore an option to remove the geotag) to the upper right of the map:

<img width="373" alt="screen shot 2017-12-30 at 20 33 42" src="https://user-images.githubusercontent.com/2998162/34457163-c0e68484-eda0-11e7-9e2e-2170b7cd99aa.png">

It's reasonable to expect that someone may change their mind about have a post or page geotagged with their location. At the moment, they'd need to create a brand new post or page to get around that.

#### What happened instead

There is no option to remove the geotag from a post or a page after it's been set. You can see a screenshot of a map here, with no cross icon:

<img width="294" alt="screen shot 2017-12-30 at 20 33 13" src="https://user-images.githubusercontent.com/2998162/34457162-b384aba4-eda0-11e7-9d0f-a7229e5a7f35.png">

#### Context / Source

Reported in 873426-z.

#user-report #journey

**Comment by codebykat** [comment]
There's an X now and no other reports, so either this was a temporary glitch or it was fixed somewhere along the way.
