### ISSUE TITLE
No "Add Domain" button on /Domains/manage (AT)

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#21208]
It is and should be possible to add domains on AT (whether registering, mapping or transferring), but the blue "Add Domain" button is hidden. To remove "Change primary" button we've ended up hiding "Add Domain" as well.

Can be replicated at: https://wordpress.com/domains/manage/sitename.com

On-nonAT, shows up like this:

![image](https://user-images.githubusercontent.com/6505293/34460115-2c5827dc-ee27-11e7-8f7b-bc03eb4b0799.png)

AT,
Shows up like:

![image](https://user-images.githubusercontent.com/6505293/34460210-035b1184-ee2a-11e7-82fb-339c738e85f7.png)

There is still the "Add" button next to Domains in the left sidebar though, so it's still technically possible to register a domain - just the blue "Add Domain" button isn't there.

cc @jhnstn @donpark

**Comment by gpmw** [comment]
I had a user trying to map their domain but the add button in Calypso was missing in SU and available in SSP. See hc_1574523

**Comment by jsnmoon** [comment]
Hi @ehti and @gpmw, is this still a valid issue? If so, could you provide steps for reproducing the defect? 

On my end, I can see both `Change Primary` and `Add Domain` on my atomic site like so:

<img width="1061" alt="site_title_ _wordpress_com" src="https://user-images.githubusercontent.com/4044428/40942752-6655136e-680c-11e8-9ac2-4d6f1d13aeed.png">

**Comment by gpmw** [comment]
I check the site in question again (hc_1574523) and it is working now for me. I can see both `Change Primary` and `Add Domain`. Thanks for looking into this.

**Comment by jsnmoon** [comment]
Seems to be resolved, please reopen if this is still an issue!
