### ISSUE TITLE
Reader: improve handling of private site in blog stream

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#21213]
@nylen has advised that https://github.com/Automattic/wp-calypso/pull/21082 will result in private blog streams being linked, e.g.

https://wordpress.com/read/blogs/179922

We don't currently handle that situation very well:

![2017-12-22t15 07 03-0500_720](https://user-images.githubusercontent.com/17325/34480597-494b03bc-efa5-11e7-90a2-d4288a7d0145.png)

We should show an error page when this happens.

**Comment by jonathansadowski** [comment]
With r167636-wpcom, this shouldn't be as big of an issue -- but it'd still be nice to account for this case.

**Comment by bluefuton** [comment]
Thanks for the update @jonathansadowski!

( r167636-wpcom includes whether a liker's primary site is visible to the current user in the API response, so it won't be linked if it's not visible)
