### ISSUE TITLE
Themes: allow Jetpack users to install .com themes

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2121]
~ This is part of a macro-feature to install .com themes to Jetpack, see #2123 ~

Raised by @mcsf 

**Scenario:** As a Jetpack user, I want to be able to pick .com themes using the Showcase and have them be automatically installed on my Jetpack site.

TODO:
- [ ] JP API to install a theme zip (from URL or disk)
- [ ] Authentication for WPCOM zips
- [ ] Premium theme download auth?

**Comment by designsimply** [comment]
Comment from @ockham 

> We might be able to use JP's `Jetpack_JSON_API_Themes_Install_Endpoint`, extending it to allow installation from wpcom.

**Comment by folletto** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/10098
