### ISSUE TITLE
Editor: Gallery: Unable to reorder images on touch screen devices

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#21215]
It's not possible to reorder images within galleries on touch screen desktops, tablets, or mobile devices.

#### Steps to reproduce
1. Log into WordPress.com in a browser on any tablet or mobile devices of your choice.
2. Navigate to the editor of a post that already contains a gallery of images.
3. Tap on the gallery to reveal a menu containing a pencil icon and a cross icon. 
4. Tap on the pencil icon to edit the gallery and then select the "Edit" tab from the new modal.
5. Tap on any image within the gallery to reveal two arrows then try to use those arrows to reorder the image. Here's a screenshot of what those arrows look like:

![pastedimage](https://user-images.githubusercontent.com/2998162/34483088-3fc6c664-efb4-11e7-9202-de21cd6bd685.png)

#### What I expected

I expected for an image to move either to the left or right in its place in the gallery, depending on the arrow I selected.

#### What happened instead

Tapping on the arrows had no visible effect. The images were not reordered within the gallery.

The app isn't an alternative here, as it's not currently possible to edit galleries within the app.

#### Browser / OS version

I tested on the following devices:

* iPad Mini / Safari / iOS 11.2.1
* Pixel / Chrome / Android 8.1.0

The report of this issue in 873589-z mentions Windows 10 and I'm getting more details on the specific device that was used. I believe it's a desktop device as the user mentions "cursor changes to a do not enter symbol". I've added a note for more details to be added to the comments of this issue. I also asked for help testing in p1514893357000090-slack-windows.

#### Context / Source

#user-report

**Comment by SiobhyB** [comment]
@ehti tested on his Windows 10 laptop and was able to replicate the same issue. When selecting the arrows with his cursor the cursor's icon changes to the "blocked" symbol and tapping has no effect.

**Comment by ramonjd** [comment]
Fixed in #22481
