### ISSUE TITLE
Editor: When Yoast SEO is installed, adding SEO Description causes publishing/draft to fail.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#21211]
#### Steps to reproduce
Prerequisite: Install [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/) and activate on either a Jetpack-connected site, or an Atomic site.
1. Starting at URL: https://wordpress.com/post/ or https://wordpress.com/page/
2. Create a new post with title, content, and an SEO Description.
3. Click Publish.

#### What I expected
If an SEO plugin is installed, there should be some notification that the SEO Description cannot be used (or perhaps hidden altogether).

#### What happened instead
One of several errors will result: 
"Publishing of page failed" (if on a page)
"Saving of draft failed." (if it attempts to save a draft when creating a post)
"Publishing of post failed." (if you attempt to publish the post)

#### Screenshot / Video
<img width="1388" alt="screen shot 2018-01-02 at 2 00 20 am" src="https://user-images.githubusercontent.com/8002138/34479046-a1943b54-ef61-11e7-9cf7-88d56de09bc1.png">

#### Context / Source
This is a fairly common occurrence, but it seems it has never been reported. The issue is present on both Jetpack-connected sites, as well as WordPress.com Atomic sites.

**Comment by gwwar** [comment]
@apeatling suggests to not render the SEO Description section when we detect this case.
