### ISSUE TITLE
Themes: add an upload button to upload themes to Jetpack sites

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2122]
~ This is part of a macro-feature to install .com themes to Jetpack, see #2123 ~

Raised by @mcsf 

**Scenario:** As a Jetpack user, I want to be able to use Calypso/Themes to upload a ZIP-packaged theme and have it installed on my Jetpack site.

TODO:
- [ ] JP API to install a theme zip
- [ ] Upload screen

**Comment by folletto** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/10006
