### ISSUE TITLE
Accessibility: Modal windows + screen readers

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#21223]
In p4vt7e-3o-p2, we were made aware of a report that some modal windows in Calypso are tough to navigate using a screen reader.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general
2. Either select **Language** or **Delete your site permanently** > **Delete site** to open a modal window.

Screenshot of the **Delete Site** window:

<img width="773" alt="screen-shot-2017-09-26-at-08-57-37" src="https://user-images.githubusercontent.com/2998162/34498725-d98a7fca-effa-11e7-80ab-e6b5910f620b.png">

Screenshot of the **Language** window here:

<img width="773" alt="screen-shot-2017-09-26-at-08-59-44" src="https://user-images.githubusercontent.com/2998162/34498794-19b262a2-effb-11e7-9781-6af4c3456ba0.png">

I highlighted `tabindex="-1"` in both screenshots as I wondered whether that may be causing issues here, but @davidakennedy suggested that better labelling for screen readers may help.

#### Context / Source

#user-report #empathy #perspective #reallife #painpoint

**Comment by ryelle** [comment]
I think between #21753, #21779, and #21838 this issue has been fixed. I'm going to close this issue, but we can revisit this if it's still a problem.
