### ISSUE TITLE
Themes: bring .com themes to Jetpack users

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2123]
Raised by @mcsf 

This is an umbrella issue for:
- #2121 — allow Jetpack users to install .com themes ✅ 
- #2120 — All Sites, show Jetpack user .com themes aside from locally installed ones ✅ 
- #2122 — add an upload button to upload themes to Jetpack sites ✅ 
- #2128 — All Sites, allow Jetpack sites modal site-selector

**Comment by folletto** [comment]
📚 _Meta Update: I've regrouped and edited all the related issues for ease of reference._

**Comment by folletto** [comment]
Closing this one as only https://github.com/Automattic/wp-calypso/issues/2128 remains.
