### ISSUE TITLE
Jetpack Search: add a clickable card link to customizer

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#21239]
Currently the WordPress.com settings card looks like this:

![image](https://user-images.githubusercontent.com/437258/34534114-fba10fda-f08a-11e7-804c-068607abbb16.png)

The one in the Jetpack plugin includes a description that links to the customizer to assist in set up:

![image](https://user-images.githubusercontent.com/437258/34534156-1ac1de44-f08b-11e7-86e1-56f21fa3adec.png)

The ideal would be to have a description here helping explain how search works and whatnot as well as a clickable card linking to the customizer. Something like this:

![image](https://user-images.githubusercontent.com/437258/34534373-decd62fe-f08b-11e7-8d8b-9f81305cc41c.png)

cc @MichaelArestad @gibrown

**Comment by designsimply** [comment]
Closing because this is under active development and being addresses at https://github.com/Automattic/wp-calypso/pull/20677#issuecomment-354886471

**Comment by rickybanister** [comment]
That comment does not address my hope to use the clickable card pattern. Can we leave this open and have it get closed when @gibrown addresses the feedback and merges that PR?

**Comment by MichaelArestad** [comment]
Right. We should do both this along with the other PR.

**Comment by gibrown** [comment]
Fixed
