### ISSUE TITLE
Store: Not Showing All Refunds Properly

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/wp-calypso#21243]
#### Steps to reproduce
1. Starting at URL: https://christianaidministries.org
2. SSP as user and look at Refund for 2017. ![image01](https://user-images.githubusercontent.com/6686962/34542419-813ad936-f0aa-11e7-9986-b83647a99a98.png)
3. Notice that it shows $500.
4. They have 3 actual refunds that total $880.
![image02](https://user-images.githubusercontent.com/6686962/34542430-8e1a3354-f0aa-11e7-9f26-ece8d5cd6a7d.jpg)
Post IDs that are missing are 38938 ($100) and 41974 ($280).

#### What I expected

The totals would match. 

Can someone take a look into what's causing the disconnect? 

Internal ref: 877258-zen

**Comment by kellychoffman** [comment]
cc @psealock @greenafrican

**Comment by psealock** [comment]
It appears manual refunds aren't being correctly counted. Looking into the queries...

**Comment by westi** [comment]
So far I've found two related but different bugs with refunds, working on patches to fix them

**Comment by psealock** [comment]
### Update
Confirmed D9461 (Not yet deployed) fixes this issue

![screen shot 2018-02-02 at 11 58 23 am](https://user-images.githubusercontent.com/1922453/35707920-9278571e-0810-11e8-866d-c01723448b02.png)

**Comment by psealock** [comment]
Fix deployed. Closing this issue
