### ISSUE TITLE
Activity Log - Create JITM When Backups Are Lapsing

### ISSUE THREAD

**Issue by rcoll** [Automattic/wp-calypso#21256]
When backups have lapsed over a period of 48 hours or more, we should show a notice at the top of the activity log which resembles the following so that users are aware of the failure and can take steps to fix it.

![32810540-a4608d12-c958-11e7-86fc-dbc218430bb4](https://user-images.githubusercontent.com/5528445/34569286-4be9666c-f136-11e7-809c-4cad25525dc2.jpg)

The "Get Help" button should open HappyChat when available, and link to the contact page otherwise.

**Comment by samhotchkiss** [comment]
Replaces #21256

**Comment by samhotchkiss** [comment]
Closing in favor of #20431
