### ISSUE TITLE
Scrolling dialogs - could be more obvious

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#21254]
Highlighted in https://github.com/Automattic/wp-calypso/issues/21014

When a dialog / modal is scrollable it could be made more obvious. We currently use a 'fade' pattern but that's only visible if content is rendered behind it;

![fade](https://cldup.com/NEXNDzdgsj-3000x3000.png)

Depending on the modal height / content positioning that could be completely hidden making it unclear that the content can be scrolled;

![scroll](https://cldup.com/SUgzcKLF-2-3000x3000.png)

**Comment by andfinally** [comment]
This was also mentioned in https://github.com/Automattic/wp-calypso/issues/4829#issuecomment-374640007 - possibly related issue https://github.com/Automattic/wp-calypso/issues/23659
