### ISSUE TITLE
i18n: locale suggestions from locale-guess should account for activated language

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#21250]
At https://wordpress.com/start, WordPress.com suggests alternative languages with which the user may complete the signup process.

The suggestions come through as a result of a fetch to `/locale-guess`.

PR #21138 introduces a feature whereby the language switches from the default English to the first available _browser language_.

However when switching to a language variant, for example `en-GB`, `fr-CA`, or `es-CL`, the backend often returns the root language as an option.

This is especially glaring when the variant language is partly translated, such as in the case of `fr-CA`. The following is from `fr-CA`. _Etape 1 de 4_ is translated only:

<img width="884" alt="fr-ca" src="https://user-images.githubusercontent.com/6458278/34429523-64512600-ecad-11e7-8cce-6d5eee8e04d3.png">

Even weirder still, is the suggestion that the user choose English when he or she has set their browser to `en-GB`.

<img width="670" alt="en-gb" src="https://user-images.githubusercontent.com/6458278/34429440-2dfe9ed0-ecac-11e7-91dd-8cf465528f27.png">

### Possible approaches
1. `/locale-guess` should detect the activated language, and modify results accordingly. For example, by omitting a root language if the activated language is a variant. 
2. Or, we specify the locale variant description in the suggestions, for example __English (US)__ and __Español (Chile)__.

Where variants are half-translated for signup, we could prioritize the translations.

#### Steps to reproduce
**Dependent on PR #21138 being merged**
1. Switch your browser's language to `en-GB` and head to http://calypso.localhost:3000/start

#### Expectations
There's no offer to switch to English when my browser's language is English.

#### What happened instead
<img width="506" alt="screen shot 2018-01-04 at 2 55 51 pm" src="https://user-images.githubusercontent.com/6458278/34549781-700966fe-f15f-11e7-9b2e-449e808aeca3.png">

**Comment by alisterscott** [comment]
@ramonjd: with your fix in #21138 do you still consider this an issue?

**Comment by ramonjd** [comment]
@alisterscott 
It's not come up as an issue, so I'll close for now. Thanks for the reminder.
