### ISSUE TITLE
Activity Log: Plugin update should be "Plugin updates" when grouped

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#21262]
We also need to make the same change to Theme update(s)

![image](https://user-images.githubusercontent.com/1123119/34574084-952aad98-f133-11e7-86b0-846f0d9a639c.png)

Hat tip to @annezazu for reporting

**Comment by roccotripaldi** [comment]
In progress in D9216-phab

**Comment by roccotripaldi** [comment]
fix deployed in 167987-r
