### ISSUE TITLE
Activity Log: Plugin installed and Plugin activated should have grey icons

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#21265]
Currently they are green and should be grey:

![image](https://user-images.githubusercontent.com/1123119/34574444-a679d9b0-f134-11e7-9143-791568e1fab7.png)

Hat tip @annezazu

**Comment by roccotripaldi** [comment]
In progress in D9216-phab

**Comment by roccotripaldi** [comment]
fix deployed in 167987-r
