### ISSUE TITLE
Store: Adding support for more countries - Units UI 

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#21279]
Store admins need a way to change their weight and dimension units. 

Currently, we are surfacing a currency picker in payments settings. To align with this, weights and dimensions should be added to shipping settings: 

<img width="751" alt="screen shot 2018-01-04 at 3 23 51 pm" src="https://user-images.githubusercontent.com/5835847/34582822-4ed4c560-f163-11e7-9423-7f8132347583.png">

Like currency, dimensions and weights should be smart defaulted based on their country.

**Comment by budzanowski** [comment]
@kellychoffman `Size unit` feels a bit more accurate to me - but I may be skewed by my native language :)

**Comment by budzanowski** [comment]
But I see that it is the name used in API. Please ignore ^ comment.

**Comment by dechov** [comment]
https://github.com/Automattic/wp-calypso/pull/21502 appears to fix this. Just a couple things I noticed:

- The new dropdowns are being rendered inside the placeholder:
<img width="847" alt="screen shot 2018-02-03 at 7 33 26 pm" src="https://user-images.githubusercontent.com/1867547/35888470-bead177c-0b65-11e8-9f74-3671721667be.png">

- "Milimetres" typo: should be "Millimetres" — or should it be "Millimeters" (along with "Centimeters") for consistency with "Meters"?
<img width="222" alt="screen shot 2018-02-06 at 2 09 39 pm" src="https://user-images.githubusercontent.com/1867547/35888459-b37fb116-0b65-11e8-967b-dfc20dcc06aa.png">
Probably safe to go with the British variants if country isn't US, though I'd assume this kind of thing is best left to the i18n layer.

**Comment by dechov** [comment]
Looks like the spacing in the placeholder case looks better now, but there's a different issue where the dropdowns don't wrap at the proper width:

<img width="408" alt="screen shot 2018-02-26 at 11 25 39 pm" src="https://user-images.githubusercontent.com/1867547/36746601-b87159a2-1bc0-11e8-9530-bf6f5a8bca17.png">

**Comment by justinshreve** [comment]
I think this issue can be closed now. 

The placeholder issue was fixed in #22026, the overflow issue was fixed in #23022.
I created a small PR to address the typo #23469.
