### ISSUE TITLE
Themes: preview not working on mobile Safari

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2129]
Raised by @seear 

**To Reproduce**
1) Visit wordpress.com/design on iPhone or _Safari->Develop->Responsive Design_ in iPhone mode
2) Tap on a theme screenshot. Note that the preview does not appear.

Found on my phone, and OS X Safari responsive mode shows same behavior:

![mob_safari_preview](https://cloud.githubusercontent.com/assets/7767559/11103398/1903acda-88ba-11e5-8f5e-538b7bce3fd0.gif)

`.web-preview__frame` height is 0 for some reason.

Preview works in iPhone editor, but the phone/tablet/desktop switcher is obscured by the (master?)bar at the top.

Comment from @ehg 

> Changing `.web-preview__frame` to have a `min-height: 100%` fixed this for me. Not sure how wise that is.

Reply from @seear 

> It seems to be some weird interaction with the `float: right` property on the `.main` element, because dropping that causes this the preview to start working. This information strikes me as disheartening rather than enlightening.
> 
> `min-height: 100%` seems to me to be a decent solution in the circumstances.

Notes from @lancewillett 

> Still happening — not just Mobile Safari but any small screen view, like using Firefox desktop browser and changing to small screen size with Cmd-Shift-M.
> 
> ![mobile-safari-no-preview](https://cloud.githubusercontent.com/assets/66797/11223623/1eef8e16-8d2e-11e5-8203-4493f0a87eab.gif)
> 
> Relates to 7657-wpcom in that we'd like to send mobile preview requests directly to site preview and not to Customizer.

**Comment by lancewillett** [comment]
Testing this again today: it's working as expected now. :)

Testing with https://wpcalypso.wordpress.com/design/lancetest23.wordpress.com

1. On a small screen device, go to My Sites
2. Click Themes
3. Click a theme screenshot
4. The demo site preview loads correctly.

![img_4710](https://cloud.githubusercontent.com/assets/66797/14538830/845c11ce-0232-11e6-8dc2-cc69b03c256b.PNG)

iPhone 6+, iOS 9.3.1
