### ISSUE TITLE
Ampersand not being decoded on Followers and Stats page

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#21296]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me
2. Change your display name to something with an ampersand (`&`) and save
3. Go to a site you manage, and visit:
  * People > Followers; or
  * Your stats page, under the Authors box
4. Check your name 

#### What I expected

Not seeing `&amp;` but the `&` itself.

#### What happened instead

![screen shot 2018-01-05 at 15 18 07](https://user-images.githubusercontent.com/1136160/34620824-f66a009a-f22d-11e7-95f9-eaf6b154656d.png)

***

* Similar to #11799 and #1008
* User report: 881207-zen

#manual-testing #user-report

**Comment by timmyc** [comment]
Fixed in #21932
