### ISSUE TITLE
Store: Handle calypso store routes for non-US non-CA stores appropriately

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#21304]
Until we are able to confidently handle rendering our various routes for non-US non-CA stores, we probably should render something special / do a redirect if a non-US non-CA merchant guesses at the URL for a store route (e.g. store/products, store/promotions, etc.)

Maybe that something special could at least include a link taking them to an appropriate WooCommerce page in wp-admin on their site?

cc @kellychoffman @jameskoster 
  
Useful selectors:
```
import { isStoreManagementSupportedInCalypsoForCountry } from 'woocommerce/lib/countries';
import { getSetStoreAddressDuringInitialSetup } from 'woocommerce/state/sites/setup-choices/selectors';
```

**Comment by jameskoster** [comment]
I think an `EmptyContent` oughta do it.

**Comment by alisterscott** [comment]
I don't believe this is a WordPress.com site Sign Up issue so I've removed the label

**Comment by justinshreve** [comment]
This has already been handled.

<img width="1174" alt="5" src="https://user-images.githubusercontent.com/1595739/35016334-efff15c2-facc-11e7-9128-a455c5c8a1a1.png">
