### ISSUE TITLE
No Testimonials Found has a line through it

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#21313]
<img width="582" alt="capture" src="https://user-images.githubusercontent.com/1883296/34643222-8c34d29c-f2ee-11e7-8156-369a7e5bb582.PNG">

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/comments/all with a jetpack site
2. having viewport of size 1440×829
3. click the testimonials menu option
4. see a line through testimonials

#### What I expected
No line to be present

#### What happened instead
A line present

#### Browser / OS version
Chome 64 / Windows

**Comment by alaczek** [comment]
This no longer seems to be the case. Closing.
![image](https://user-images.githubusercontent.com/4550351/56935587-52512880-6b35-11e9-9c64-467477ce9f67.png)
