### ISSUE TITLE
Themes: highlight lost on search field

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#21325]
![screen shot 2018-01-08 at 13 41 45](https://user-images.githubusercontent.com/4389/34673320-c0e8ce26-f479-11e7-8f47-19d669e12dda.png)

As can be seen from the above, the search field lost the blue highlight, thus looking detached from the dropdown just below.

However, the highlight still shows (correctly) on scroll:

![screen shot 2018-01-08 at 13 43 50](https://user-images.githubusercontent.com/4389/34673387-fdfa5afa-f479-11e7-8947-3d53fdf09856.png)

**Comment by designsimply** [comment]
Fixed in #21866. Props @shaunandrews.
