### ISSUE TITLE
Store - update set up checklist to use Checklist component

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#21322]
Not a high priority item right now, but something we should do at some point is update our Store setup checklist to use the [Checklist Calypso component](https://wpcalypso.wordpress.com/devdocs/design/checklist).

**Comment by ryelle** [comment]
If we do this, let's merge the two, so we can bring over the work done to make the checklist accessible :) The core calypso one is hard to use via keyboard and doesn't pass color contrast checks.
