### ISSUE TITLE
Jetpack > Settings: mobile layout fixes

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#21333]
Looking at Settings > Security for a Jetpack site, on mobile (in my case Chrome on iOS), we can see some compressed/broken looking layouts for some settings. These could be allowed to flow more to the right to prevent some wrapping:

![img_7061](https://user-images.githubusercontent.com/108942/34685394-68e16d8c-f465-11e7-8028-6becdcf828c3.jpg)

The ones that seem broken to me are:

- [ ] Credentials for the Activity Log (SSH and microcopy wrap strangely/align with the card-collapse arrow)
- [ ] "Prevent and block malicious login attempts" label wraps prematurely
- [ ] "Your site is protected from spam" wraps prematurely
- [ ] "Your site is protected from spam" has a period, but probably shouldn't, to match other labels.

Separately, a couple of others:
- [ ] Writing > "Check your spelling, style, and grammar" wraps prematurely
- [ ] Writing > Date and time format example wraps prematurely
- [ ] Writing > Press This heading shows, but nothing else does. I think maybe this shouldn't show at all, since you can't easily use bookmarklets on mobile?
- [ ] Traffic > Site stats message "Enabled! You're collecting..." wraps prematurely

I think that's all of them.

**Comment by rickybanister** [comment]
It looks like the issue is with the foldable card css and not specifically related to settings, but I'm not sure. 

@folletto—do you remember when foldable card was first added, have you ever seen an issue with it's narrow styling? Sorry if I'm misremembering your involvement in that component!

**Comment by MichaelArestad** [comment]
It is an issue with foldable card. Basically I think we're using it in a really unexpected way and might need to cause that flex container to wrap sooner than later.

**Comment by folletto** [comment]
It seems an issue with `foldable-card__secondary`:

![screen shot 2018-01-09 at 14 33 15](https://user-images.githubusercontent.com/4389/34725843-1753b76e-f54a-11e7-9f27-8a07e7f37e8d.png)

I'm not sure on the issue – I don't think it was there before, yet the `flex` rule seems it was there since the beginning... and changing it to not grow nor shrink should do it, even if I haven't cross-checked all the variations.

**Comment by keoshi** [comment]
Will push a PR to fix this in a few.
