### ISSUE TITLE
Store: Add a "Print Test Label" button to test printing a USPS shipping label

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#21335]
The "Print Test Label" is in WP-Admin, in the `self-help` section, but there's no equivalent in Calypso. We don't need most of the troubleshooting sections of that page on Calypso, but a button to print a test label can be useful for some merchants (even though they can always reprint a label if their printer wasn't correctly configured the first time around).

cc/ @allendav for bringing it up :)

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
