### ISSUE TITLE
Domains: Allow the user the turn on / off Domain Privacy

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#2134]
Although not everyday, the users might need to enable / disable their privacy settings from time to time. 

Currently we have no way of changing this setting, but it is required to disable privacy setting when transferring-out the domain.

In order to simplify the transfer-out flow, we're showing a popup to disable privacy. We're all good up to this point. (See also #2133). But in any case should the user changes their idea and decides to stay with us, the indicator on #2133 should have an actionable view.

/cc: @breezyskies for a flow suggestion

**Comment by breezyskies** [comment]
I think we should build this in to the "cancel transfer" button shown here:

![image](https://cloud.githubusercontent.com/assets/3011211/12129292/77032824-b3b7-11e5-96da-6d4a4a96c777.png)

Basically, if they had privacy before they initiated the transfer, we turn it back on when they cancel the transfer. We might want to add a conditional line of copy here for users who did have to disable privacy to get to this point:

> Privacy Protection is currently **disabled**. Cancel this transfer to re-enable Privacy Protection, or complete the transfer to set up domain privacy at your new registrar.

We may want to build an explicit setting for this at a later point (that isn't specific to transfers), but I would stick to this simple version for v1.

**Comment by umurkontaci** [comment]
I was thinking something along the lines of that, but since the `Notice` for domain privacy under domain management page is a link; once #2133 gets in, we do need to show a some information once the user clicks a disable privacy notice.

Without it, it will link to purchase domain privacy page whenever the privacy is disabled.

**Comment by breezyskies** [comment]
> but since the Notice for domain privacy under domain management page is a link; once #2133 gets in, we do need to show a some information once the user clicks a disable privacy notice.

:+1: Will work on some designs / copy for this.

**Comment by breezyskies** [comment]
Proposed design:

<img width="740" alt="screen shot 2016-01-06 at 5 59 43 pm" src="https://cloud.githubusercontent.com/assets/3011211/12160286/5459a7f6-b49f-11e5-9854-d0bf7d2c257a.png">

The notice would then link to the transfer screen above, where they user could cancel the transfer if needed.
