### ISSUE TITLE
Activity Log: jump when a rewind/backup confirmation dialog appears

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#21341]
![rewind-jump](https://user-images.githubusercontent.com/1041600/34688885-5a917c9a-f492-11e7-9da8-21cadaf2d406.gif)

This happens when there in a day with lots of event. Experienced it in a day with 89 events.

Would be good for users to have this dialog always in center so we should smooth scroll towards the dialog.

**Comment by keoshi** [comment]
I don't think this applies anymore since we changed the way the AL structures days and discarded events. Closing for now, but feel free to reopen if it's still relevant.
