### ISSUE TITLE
Activity Log: Add "Help" link to Vulnerability Found items

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/wp-calypso#21350]
This message:
![image](https://user-images.githubusercontent.com/574752/34699089-8a7f9f74-f4a9-11e7-8690-b3890d324248.png)

Needs to have some sort of mechanism to request help from an HE in resolving their threat

**Comment by eliorivero** [comment]
@MichaelArestad can you please make a mockup for this? Maybe a button where the Rewind split button is would be ok?

**Comment by keoshi** [comment]
It seems like at this stage we can't do much in terms of auto-fixes, so the best option would be to prompt to contact support if they need help fixing it.

Here's a quick mock of how it could look. Not super stoked on the button label, so fire suggestions away.

![threat-get-help](https://user-images.githubusercontent.com/390760/35577646-ed07c996-05d9-11e8-9003-e5e428b78961.png)

**Comment by MichaelArestad** [comment]
That label is consistent to what we've used previously. I dig.
