### ISSUE TITLE
Media: Include "Uploaded to this Post" filter in Media Library

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#2136]
Core has some UX for limiting Media Library results to attachments for a specific post:

![image](https://cloud.githubusercontent.com/assets/36432/12129967/e07ad1fe-b3bb-11e5-90f0-58771c8b19cc.png)

It would be nice if the Calypso media library had this as well. As it stands, on older posts, it's very difficult to find the images uploaded to the specific post.

#calypso-gaps

**Comment by folletto** [comment]
A simple approach to start with could be just in the filter bar at the top:

![media-gallery-this-post](https://cloud.githubusercontent.com/assets/4389/19832150/146f0046-9e14-11e6-8e81-1194527c6ea6.png)

Even if it adds some categorization imbalance since it's a different way to segment items compared to the other options to the bar. I feel it's however a good first step.

**Comment by retrofox** [comment]
> Even if it adds some categorization imbalance since it's a different way to segment items compared to the other options to the bar. I feel it's however a good first step.

In terms of programming definitely, we have an imbalance here since `This post` is an especial case of `images`.
It looks pretty nice, though. I've started to taking over of this.

**Comment by retrofox** [comment]
We should keep in mind that when the `This post` filter is active we should show all media types, it means Images, Videos, Docs, etc.
Does make sense add a kind of checkbox in some way out of the filters section which could be enabled/disabled beyond the current filter?
We should keep in mind that when the `This post` filter is active we should show all of the kind of items, it means Images, Videos, Docs, etc. switching on `This post` or the whole site.

cc @iamtakashi

**Comment by folletto** [comment]
@retrofox check the PR attached to this issue, #10466 that contains already this implemented, and also an alternative design solution using the pill which would address everything you mentioned. ;)

**Comment by retrofox** [comment]
😨 Thanks @folletto

**Comment by designsimply** [comment]
<blockquote>It's very difficult to find the images uploaded to the specific post.</blockquote>

(Out of curiosity,) why is this needed?

**Comment by danielbachhuber** [comment]
> why is this needed?

On older posts, the image you want to insert may be behind several hundred newer uploads, which requires scrolling for quite a while until you find it.

**Comment by designsimply** [comment]
That seems useful but possibly also a rare case. 🙂 Thank you for the explanation!
