### ISSUE TITLE
Conversations page not loading in IE

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/wp-calypso#21383]
The Conversations page just loads and loads forever when in IE. This issue was reported to me by a user, and I tested and confirmed in my IE as well that this page never loads. They are able to access the page in Firefox and Chrome.

#### Steps to reproduce
1.  Have Internet Explorer open and navigate to https://wordpress.com/read/conversations

#### What I expected
To see my conversations

#### What happened instead
Neverending loading

#### Browser / OS version
Internet Explorer 11 ver. 11.192.16299.0 / Windows 10 16299.192

#### Screenshot / Video
https://cloudup.com/cnMkGTANoiO

**Comment by designsimply** [comment]
Tested and confirmed that Reader > Conversations doesn't load in IE11 and the following error appears in the console:

> SCRIPT438: Object doesn't support property or method 'matches'

![bs_win10_ie_11 0](https://user-images.githubusercontent.com/1119271/34780953-60c40d56-f5d9-11e7-90f6-89b87191779e.jpg)
<sup>Seen at https://wordpress.com/read/conversations using Internet Explorer 11 on Windows 10.</sup>

Note: the main stream in the Reader also doesn't load for me (IE11 on Win10 via Browserstack). Does the Reader still officially support IE11?

**Comment by blowery** [comment]
> Does the Reader still officially support IE11?

@designsimply it does support IE11. Investigating.

**Comment by chaitanyamsv** [comment]
Please follow up with the user in #891226-zen once this issue is fixed. Thank you!

**Comment by chaitanyamsv** [comment]
Oh wait, this problem is fixed and I am following up the user. Please never mind my earlier comment.
