### ISSUE TITLE
Google Apps: Show inline validation instead of notice

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#2140]
The Google Apps form validation notice is currently showing in the wrong place:

<img width="670" alt="screen_shot_2015-10-13_at_12_10_18_pm" src="https://cloud.githubusercontent.com/assets/3011211/12131116/a60d4156-b3c4-11e5-93c4-92459c53ee7e.png">

Regardless, this should be moved to inline validation to be consistent with the rest of Calypso.

**Comment by stephanethomas** [comment]
> Regardless, this should be moved to inline validation to be consistent with the rest of Calypso.

We already discussed that in the past and I don't think inline validation is the best solution. Some error messages can be quite long and forms - such as the one in the `Domain Registration Details` page - may have numerous fields and a tricky layout which makes inline messages difficult to display.

**Comment by breezyskies** [comment]
> Some error messages can be quite long and forms - such as the one in the Domain Registration Details page - may have numerous fields and a tricky layout which makes inline messages difficult to display.

Agree that there are some design issues with some of our forms to consider, but we're currently using the inline validation pattern throughout the rest of Calypso. I think we should convert these to inline on a case by case basis, so we have time to handle the design issues (e.g. stacking fields instead of inlining them). (The Google Apps one above could simply show "You must select a username." below the field, so no blockers for this one.)

Inline validation will also force us to be more concise in our error messages (and maybe link out to more info when needed) -- some of our error messages are currently too long even for notices. 

cc'ing @mikeshelton1503 for his thoughts, as we've discussed this issue in the past, particularly with regards to checkout.

**Comment by mikeshelton1503** [comment]
The issue with the current error state is that it by separating it from the field it's harder for the user to zero in on which field has issue, especially if they have several email addresses. With the form having no labels, inline validation makes it easier to identify the incorrect field and with less verbose language. For example we won't have to state "User #1:".

Also from an accessibility standpoint having the error message separated creates an issue for users using screen readers.

@stephanethomas raises fair points about some of the challenges but I think those are challenges we can solve for.

**Comment by umurkontaci** [comment]
@mikeshelton1503 @breezyskies Can you post some designs for this when you have some time?

**Comment by breezyskies** [comment]
@umur We have an existing form pattern / component for this (shown [here](https://wpcalypso.wordpress.com/devdocs/design/form-fields)). Applied it should look something like this:

<img width="742" alt="screen shot 2016-01-29 at 6 31 23 am" src="https://cloud.githubusercontent.com/assets/3011211/12678115/0cfdc346-c652-11e5-9054-6b3afd89616a.png">
