### ISSUE TITLE
Store: Firefox display issues

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#21407]
While testing #21403, I noticed that the spacing is off for the "postcode" input in both the billing and shipping dialogs. It looks fine on the settings screens. 

I only see the problem in Firefox. Chrome & Safari both look OK.

<img width="849" alt="screen shot 2018-01-10 at 10 13 25 am" src="https://user-images.githubusercontent.com/689165/34788476-8a5aebe2-f5ef-11e7-9ece-9dd49d30ccd2.png">

cc @ryelle

**Comment by justinshreve** [comment]
On the order screen in Firefox, the shipping input extends into the side of the box:

<img width="708" alt="screen shot 2018-01-29 at 10 35 49 am" src="https://user-images.githubusercontent.com/689165/35527666-5e385b94-04e0-11e8-96b5-9290470468e9.png">

**Comment by ryelle** [comment]
Fixed in #22019
