### ISSUE TITLE
Store: Redirect to update routes after creating new products, categories, & promotions

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#21427]
This is a problem for products, product categories, promotions, and other objects that we have a 'create' form for. Once the user creates their object, they are redirected back to the listing screen. The new object can get lost in the list and make it harder to verify that their object was indeed created (they do get a success notice however).

See https://github.com/Automattic/wp-calypso/pull/21379#issuecomment-356757933
Some discussion: p1515623711000695-slack-store-on-wpcom.

**Comment by justinshreve** [comment]
Design (https://github.com/Automattic/wp-calypso/issues/22550#issuecomment-366721539): 

> Can we also use what we do in Orders with the light blue background? Except in this case the background would fade away after a couple seconds.

**Comment by justinshreve** [comment]
I tried to brainstorm and tinker with this a bit today and got something that kind of works for products.

However, each object list (product, promotion, product category) works differently both in terms of display and code/structure. i.e. on the product category page we would have to wait till all the elements load, scroll down, then highlight the row. For Promotions we have to find the correct page to navigate to, because we can't even order those items by 'creation date'  (product sales are mixed in to the list and are just meta on products), possibly scroll, and highlight.

I think we could figure something out, but it seems non-trivial to get this working consistently across our pages. I'm wondering with our focus switch coming up soon, if we should actually redirect to the edit route instead? I looked at what pages and posts do in the main Calypso screens, and they redirect you to a view/edit screen instead of the list. cc @timmyc @kellychoffman

**Comment by timmyc** [comment]
> This would also be more consistent with how pages and posts work on the main Calypso screens

Seems reasonable if the established pattern after create for posts and pages is to show the edit screen - that we should do the same with store related objects. In Woo core we do the same thing on product creates.

**Comment by justinshreve** [comment]
So I pushed some changes up that change the redirect URLs as mentioned above https://github.com/Automattic/wp-calypso/compare/update/redirect-routes-21427, however things are a bit more jarring then I expected because of how the form elements mount and unmount. It's especially noticeable with promotions. See the video below for what I'm talking about.

I tinkered with a few things but I'm not sure the best way to handle this at the moment, except for some kind of success message being displayed inline between the two form loads. Any ideas?

https://cloudup.com/cmPSpme5f8V

**Comment by timmyc** [comment]
Interesting, that is definitely not an ideal experience right there. So I'm guessing that the freshly created product is not yet in state, by ID, and it is awaiting the `fetchProduct` from the API? Seems the only elegant way around that is to show a loading indicator of sorts.

Doing a direct link to an edit product page, or a hard refresh yields the same experience somewhat:

![hard-refresh-edit-product](https://user-images.githubusercontent.com/22080/39273735-81841a96-4894-11e8-911f-39bfe38ba0e4.gif)

**Comment by nerdysandy** [comment]
Closing this in favor of the fact that we are sunsetting Store by 22nd Feb,2021.
