### ISSUE TITLE
People: Increase Limit for CSV Download of Email Followers

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/wp-calypso#21443]
The user in 893459-zen has 28,887 email followers. They'd like to download this list to a CSV file, but the cap for the number of email addresses than can be downloaded is currently 20,000. 

I was able to confirm this by downloading from the Stats Admin.

Can we increase the limit or find some way to download those extra 8,887 followers?

**Comment by westi** [comment]
Raised the limit to 30,000
