### ISSUE TITLE
Suggestion: Strip off link prefix (HTTPS) when searching for a new domain

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#21458]
**Steps to reproduce**: Follow the steps below to reproduce.

1. Starting at URL: https://wordpress.com/domains
2. Search for a domain name with link prefix HTTPS (example: https://automattic.com/)

**What I expected**: The domain suggestions to strip off https

**What happened instead**: Shows httpsautomattic.com

![image](https://user-images.githubusercontent.com/18581859/34838329-ae0b13a2-f723-11e7-87c4-c0cd24fb9e7f.png)

#manual-testing

**Comment by alisterscott** [comment]
Thanks for your report. I noticed this also does the same for http:// addresses:

<img width="1054" alt="screen shot 2018-01-11 at 9 37 31 am" src="https://user-images.githubusercontent.com/128826/34838481-2269c0fc-f6b3-11e7-87fc-a3fa039043de.png">

**Comment by arunsathiya** [comment]
Yes, it happens for http too. Should have mentioned it. Thanks for bringing it up!

**Comment by arunsathiya** [comment]
@alisterscott Wondering as to why this was closed. Please let us know. Thanks.

**Comment by alisterscott** [comment]
Sorry, it was auto closed as I fixed this in a separate code repository, I have merged the change and it should be live within the next day or so. I will reopen and check back on this tomorrow.

**Comment by arunsathiya** [comment]
Thank you!

**Comment by alisterscott** [comment]
Working now:

<img width="1011" alt="screen shot 2018-01-22 at 12 07 34 pm" src="https://user-images.githubusercontent.com/128826/35202194-ece03750-ff6c-11e7-9cb2-85cd8be57fe5.png">

Thanks for raising this issue
