### ISSUE TITLE
Bug: Unable to search for a new domain with the word "wordpress"

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#21459]
**Steps to reproduce**: Follow the steps below to reproduce.

1. Open https://wordpress.com/domains
2. Search for a domain with the word **wordpress**

**What happens**: The word "wordpress" is stripped off the search results. 

**What I expected**: The word "wordpress" is not stripped off the search results.

![image](https://user-images.githubusercontent.com/18581859/34838528-6b2ac568-f724-11e7-8f54-1a4f8fcd29dd.png)

![image](https://user-images.githubusercontent.com/18581859/34838534-6db61134-f724-11e7-8efd-e442f279e6a7.png)

![image](https://user-images.githubusercontent.com/18581859/34838535-6f72ff1e-f724-11e7-9c6e-a06087812002.png)

#manual-testing

**Comment by rachelmcr** [comment]
Thanks for the report! This is actually expected behavior — the WordPress name is trademarked and can't be used in domain names without permission from the WordPress Foundation:

https://wordpressfoundation.org/trademark-policy/
