### ISSUE TITLE
Media Library Does Not Load On Chrome When Adding Featured Image After The Image Was Added Through App or Another Browser

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#21456]
<strong>Media Library Won't Load  To Select Featured Image in the Browser Version On Desktop WordPress.com After Adding Image From the App or Another Browser</strong>

For information: I am using Android version 8.1.0 with Google Pixel 2 device; before the same issue was happening on Samsung S 5 with the same Android version; the issue also happens between browsers e.g. when adding the image from Safari and trying to see it on Chrome

Detailed Steps of What I Do:
1) Open the editor in Calypso in the browser to create a new post
- click "Add" button by the word Blog Posts to start making a new post: https://wordpress.com/post
- add some text and do not publish the post yet
2) I select an image in my phone that I want to add to Media Library and click on the option Share:
https://cloudup.com/c6k9oK9efL3

3) Among the Sharing options in my phone, I select WordPress.com:
https://cloudup.com/c16ikB0k7A5

4) Select the site that you want to add it to and select the option "Add to Media Library":

https://cloudup.com/cnSta3rZw53

5) Wait until the upload is complete and check if the image is there:

https://cloudup.com/cgDAjHZpI7b

6) Come back to the post that you are editing and try adding the featured image:

https://cloudup.com/cmkSnvse8HC

The Media Library on the desktop:

<ul>
<li>at first will open without uploaded image;</li>
<li>when you leave the post and come back, and try to set featured image - the screen for the Media Library will be blank</li>
</ul>

You can leave the post and come back and the images still will not appear:
(note the image that I used in my video is different than the one on the screenshot because I made multiple tests but both of them lead to the same result).
https://cloudup.com/ctPuG-C0w3S

More Details: 
1) the other images from Media Library when clicking on "Add" in the post load normally and there is no glitch; only with featured image

2) I have tried uploading an image through Android App and then checking the  image on Safari (the same way I was testing with Chrome) and the featured image appears there right away  without a glitch:

https://cloudup.com/c-emrdb8Mwd

3) On Firefox and Android, the issue also does not appear. As soon as the image is uploaded through the app and I click on Featured Image, it is right there:

https://cloudup.com/cZekUpCAj8T

4) I can reproduce the issue between browsers. I have uploaded the image through Safari and then checked on Chrome trying to set up featured image and got a glitch:

https://cloudup.com/c2nwET0oPgp

5) When I upload the image through Chrome and add the image through Safari, the issue does not happen (I added the image right into Media Library from desktop on Chome and used the same method on Safari in point 5 above):

https://cloudup.com/ceqrIhItbNi

6) It seems that somewhat similar issue was reported here: https://href.li/?https://github.com/Automattic/wp-calypso/issues/7738

**Comment by worldomonation** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. **Report anew**: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. **Reopen**: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
