### ISSUE TITLE
Help: Translations don't always fit into contact form tabs 

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#2147]
In some languages, the choices for the second question are chopped off because of the text length.

(on Safari, with a narrow window)
Japanese:
<img width="1109" alt="_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/34067/12137804/10439dcc-b497-11e5-8620-d3d37078c43a.png">

Russian:
<img width="1108" alt="_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/34067/12137805/107a1d48-b497-11e5-843c-ea1409069e46.png">

Anything before "..." on each tab is hidden, and can be only seen through tooltips (which I initially didn't know they were there, so it's not really ideal to rely on them). The second tab in the Japanese example only shows one letter, and it's hard to understand what it means.

@jordwest suggested wrapping the text into two rows. I can't confirm that it will work for every language, but I think that's better than the current version.

**Comment by jordwest** [comment]
Chrome has slightly different behaviour:
![wordpress_com_and_wordpress_com_and_developer_tools_-_https___wordpress_com_help_contact](https://cloud.githubusercontent.com/assets/416133/12138143/4b395704-b4a2-11e5-818a-3c8a2a66760a.png)


Another solution might be to switch to the dropdowns a bit earlier:
![pasted_image_6_01_2016__6_21_pm](https://cloud.githubusercontent.com/assets/416133/12138159/64386358-b4a2-11e5-84f7-8f016c87e0a3.png)

**Comment by naokomc** [comment]
I like the idea of switching to dropdown. That's easier to scan items than having multiple rows of text side by side.

**Comment by omarjackman** [comment]
Switching to the drop down sooner for this case might be trickier than just wrapping the text to multiple lines and giving the options a fixed equal width. I vote for fixing the widths and wrapping to multiple lines when necessary.

**Comment by alisterscott** [comment]
Is there any update on the proposed direction for this: drop downs or multi lines?

**Comment by designsimply** [comment]
The Japanese options were not cut off when I tested, but the Russian ones still were:

![screen shot 2016-08-01 at mon aug 1 11 12 48 am](https://cloud.githubusercontent.com/assets/1119271/17302565/0e543cc4-57da-11e6-92e8-335fa3827c09.png)
<sup>Seen at https://wordpress.com/help/contact using Safari 9.1.1 on Mac OS X 10.11.5 logged in as design5279 with the Interface Language set to Japanese</sup>

![screen shot 2016-08-01 at mon aug 1 11 13 23 am](https://cloud.githubusercontent.com/assets/1119271/17302575/15679308-57da-11e6-981e-ef2a11197007.png)
<sup>Seen at https://wordpress.com/help/contact using Safari 9.1.1 on Mac OS X 10.11.5 logged in as design5279 with the Interface Language set to Russian</sup>

My testing steps, for reference:

1. Start at https://wordpress.com/me/account
1. Change the Interface language to Japanese or Russian
1. Click the Save Account Settings button
1. Go to https://wordpress.com/help/contact
1. Check to see if the options under the "Mind sharing how you feel?" heading fit the space or not

**Comment by lancewillett** [comment]
No action in several months — closing as abandoned. Feel free to re-open new issues for new bugs.
