### ISSUE TITLE
Store route without site loads empty page

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#21496]
Store route loads empty page:

https://wordpress.com/store

Fixing this might be as simple as adding this route definition somewhere:

```js
page( '/store', siteSelection, sites, makeLayout, clientRender );
```

This URL isn't really shared anywhere publicly so marking this low priority. It's good to take care of these anyway. ;-)

I stumbled upon it by taking the `:site` off from `/store/:site` as I wanted to share a generic URL to store with a customer, without knowing their domain.

#### What I expected
- Site selector to appear
or
- Redirecting to my only site
or
- Show some kind of error or redirect to info page

#### What happened instead
Blank page :-(

**Comment by ryelle** [comment]
This shows a site-selector as of #23805, closing this issue
