### ISSUE TITLE
Suggestion: Login field title to read "Email" too

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#21512]
**Steps to reproduce**: Follow the steps below.

1. Visit https://wordpress.com/log-in or https://wordpress.com/log-in/link
2. You will be shown a login field.

![image](https://user-images.githubusercontent.com/18581859/34908230-999ead6c-f8b2-11e7-88bb-9994faf3815b.png)

**What I see**: The title of that field reads "Email Address"

![image](https://user-images.githubusercontent.com/18581859/34908232-9d60ab58-f8b2-11e7-9075-551efdcd3ecf.png)

![image](https://user-images.githubusercontent.com/18581859/34908234-9fcb1572-f8b2-11e7-9f51-66f8c3b0a772.png)

**What I expect**: It reads "Username or Email Address" to maintain consistency, as shown in https://wordpress.com/wp-login.php?action=lostpassword

**Comment by alisterscott** [comment]
Thanks for your suggestion @arunsathiya!

This was previously username, and is actually [designed to only show email](https://github.com/Automattic/wp-calypso/pull/20500#issuecomment-350479964), so I'll close this issue for now.

Thanks

**Comment by arunsathiya** [comment]
Oh, my apologies. I meant to say "Username" too on the title. Sorry about the confusion, and I get that you are continuing to show only email. Thanks.
