### ISSUE TITLE
Plans: Full Discount Not Applied if User Previously Upgraded 

### ISSUE THREAD

**Issue by sdixon194** [Automattic/wp-calypso#21513]
#### Steps to reproduce
1. User buys a Personal plan, upgrades to Premium and $48 discount is properly applied
2. User goes to upgrade from Premium to Business on the same site, only $48 is applied.

#### What I expected

The entire cost of the Premium plan to be discounted, since the user already spend $96 total. 

#### What happened instead

It appears the plan page was only accounting for the recent $48 spent on the previous upgrade.

#### Browser / OS version

Google Chrome 

#### Screenshot / Video

<img width="1667" alt="screen shot 2018-01-13 at 1 28 20 pm" src="https://user-images.githubusercontent.com/33553323/34908926-3f201002-f866-11e7-915e-8ffc55b880bf.png">
<img width="334" alt="screen shot 2018-01-13 at 1 28 11 pm" src="https://user-images.githubusercontent.com/33553323/34908928-4247da30-f866-11e7-8938-ae33a8a76960.png">

Note: I provided the user with free credits to make up the difference. 

#### Context / Source

Relevant ticket: `897785-zen`

**Comment by prettyboymp** [comment]
The fix for this has been released server side
