### ISSUE TITLE
Editor: implement typewriter scrolling

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#2152]
_Typewriter Scrolling_ even if it's not a common term can identify the ability of the editor to detect where the user is writing and move the scroll position to a more proper position in order to make the writing process better. 

Typewriter Scrolling avoids two things:
1. The "writing against the edge of the window" effect, which makes the interface feel cramped.
2. Putting the writing point low on the screen, which is less ideal for ergonomics - a [higher eye level is more comfortable](http://lifehacker.com/5755870/how-to-ergonomically-optimize-your-workspace).

A representation of this kind of auto-scrolling is this:

![writing-point](https://cloud.githubusercontent.com/assets/4389/12140493/54dce2e0-b460-11e5-9362-a2b22e730131.png)

See a rough demo [here](https://www.youtube.com/watch?v=OYxd71J3sjY).

Avoiding the "edge of the screen" effect is something every editor does, in one form or another:
- iA Writer, WriteRoom, Scrivener — all have a default typewriter scrolling feature
- Word, Pages — are paginated, thus avoid the issue by working page-by-page (i.e. you get a full blank page). However, even them always make sure to have one [extra blank line at the edge](https://cloud.githubusercontent.com/assets/4389/12145426/faf51f92-b485-11e5-98cc-0e76d5c7640b.png).
- Ulysses — It adds three extra lines when the edge of the screen is reached.
- Atom, Sublime — They have "scroll past end" as a default feature.

We can pick one of these techniques, thus not using a pure typewriter scroll if we feel it's too much. Even if we decide to do a proper typewriter scroll, I'd still advise to do it at 2/3 (not at 1/2) and triggering it only at the end of the page, thus not while editing in the middle of the text.

A simpler way, initially, could be to just add bottom white padding, something around the equivalent to 1 to 3 lines of text. That alone could be already working well.

_Discussion split from #2131, cc @aduth._

**Comment by aduth** [comment]
@klimeryk : I don't think it's the case that your commit b297b1f closes this?

**Comment by klimeryk** [comment]
Ah, sorry about that - it seems @umurkontaci made a typo in the commit message: #2152 vs #3152 (which is the correct issue that got fixed).

**Comment by umurkontaci** [comment]
Sorry!

**Comment by KokkieH** [comment]
A request for this via [Twitter](https://twitter.com/user/status/842276904417792000).

**Comment by KokkieH** [comment]
Another complaint of the last line being obscured in 841834-f. Have people only started noticing this now?

**Comment by folletto** [comment]
It might be that by accident in the chances the space was reduced, or that the cleaner look overall made it stand out more. :) 

Thanks for the reports! :D

**Comment by KokkieH** [comment]
I suspect what it might be is that the redesign has added a somewhat-opaque bar at the bottom that appears the moment a post is auto-saved. This now obscures the entire bottom line, where previously only the small section where the word count appears was obscured.

I've already mentioned it on the editor feedback thread as well.

**Comment by KokkieH** [comment]
We've had another report in 890677-f, but given how close Gutenberg is, it's probably not worth re-opening this issue? Looks like it's already being worked on in WordPress/gutenberg#353
