### ISSUE TITLE
Add toggles for notification and email settings to follow confirmation in action bar

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#21536]
After following a site from the site frontend, we should show the notification toggles in the confirmation dialog. 

<img width="376" alt="screenshot 2018-01-15 10 09 16" src="https://user-images.githubusercontent.com/14350/34948829-41aa342a-f9dc-11e7-8ba0-6351721dfe1d.png">

To repro:
1. Visit https://b19ytest.wordpress.com
2. Follow the site using the action bar, see the confirmation dialog

**Comment by arunsathiya** [comment]
That would be very helpful!

- Currently when I follow using the Action Bar, the blog is followed all future posts from that blog appear on my WordPress.com Reader and new posts are set to "instant" email setting.
- When I follow blogs using the WordPress.com Reader instead (by not visiting that site and using the Action Bar at the bottom right), they are followed and posts only appear on the WordPress.com Reader.

It would be better to maintain consistency between the two workflows and show email settings as soon as after follow.

**Comment by blowery** [comment]
@arunsathiya thanks for the report; that's definitely not the intended behavior. We should always respect the default setting from https://wordpress.com/me/notifications/subscriptions

**Comment by bluefuton** [comment]
@arunsathiya Thanks for the feedback! To help us track that down, would you mind sharing your settings from https://wordpress.com/me/notifications/subscriptions with us?

**Comment by arunsathiya** [comment]
This is how my subscription settings look currently on my WordPress.com account. 

![image](https://user-images.githubusercontent.com/18581859/35110884-e751c526-fc9f-11e7-9bde-76f91cb92d61.png)

Hope this helps. Feel free to let me know if I can help in any other way.

**Comment by kwight** [comment]
D65679-code is a work-in-progress.

<img width="300" alt="Screen Shot 2021-08-18 at 2 24 32 PM" src="https://user-images.githubusercontent.com/349751/129974262-7376e7ba-bf0b-496c-a76a-b77f0860ef96.png">

**Comment by blackjackkent** [comment]
Apologies for lack of update here - D65679-code was deployed at the end of last week and seems to be working cleanly for the most part. @kwight noted a display bug on blogs with light-colored theme text (https://github.com/Automattic/wp-calypso/issues/56073) which is in the process of being resolved now.
