### ISSUE TITLE
Reader: auto-show comments when paging Full Post using "j" and "k"

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#21543]
When paging through posts in Full Post using the keyboard shortcuts "j" and "k", the comments do not auto-show. 

Just for reference, comments auto-show when a post is opened from the Follow stream. I think we should make the Full Post experience more consistent.

**Comment by blowery** [comment]
@samouri could you take a look at this? sounds like something fishy going on.

**Comment by samouri** [comment]
I'm having trouble repro-ing this

**Comment by samouri** [comment]
I pinged @aaronyan and he was able to explain how to repro. My current guess is that this occurs specifically for posts that have not been loaded before and its all because of a missing `componentWillRecieveProps` in `PostCommentList`.  fix incoming
