### ISSUE TITLE
Reader Post Notifications: toggle doesn't work as expected in mobile Chrome

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#21559]
@blowery reports:

> Noticed on thing on mobile chrome: I can’t get the toggle to trigger. It works most of the time for the two email toggles. Appears to highlight, like it’s selected or has focus, but not switch. If I reload, post notifications are active.

**Comment by jancavan** [comment]
I'm unable to repro this on mobile Chrome iOS and Android. Do you know which Chrome version @blowery?

**Comment by blowery** [comment]
I'm unable to reliably repro it myself...

`63.0.3239.111` / 32 bit

**Comment by blowery** [comment]
One other thing I noticed while trying to repro it: the hit targets for the collapsed following button and the cog are really really small for fingers. I kept accidentally hitting the follow button instead the cog when trying to open the popover.

**Comment by jancavan** [comment]
> One other thing I noticed while trying to repro it: the hit targets for the collapsed following button and the cog are really really small for fingers.

Yes, definitely aware of this issue. We could add more space between/around the buttons to enlarge the tap targets, but it'll make the buttons feel like they're no longer in the same group. We could also use a split button:

![screenshot 2018-01-19 10 32 23](https://user-images.githubusercontent.com/4924246/35165665-16507a8e-fd04-11e7-99a8-7d1939ceb0a5.png)

**Comment by bluefuton** [comment]
I can repro this one on Chrome iOS on iPhone X, but only on a device, not in emulated mobile in Chrome Devtools.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
