### ISSUE TITLE
Reader Post Notifications: add top margin to notification

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#21558]
@rachelmcr writes:

> just a small thing, but it feels like the full post in the comment detail could use more of a top margin — it feels a bit cramped as it is right now.

<img width="807" alt="screen shot 2018-01-16 at 10 59 24" src="https://user-images.githubusercontent.com/17325/34985564-5a79819c-faac-11e7-8cd9-b9d276ef1005.png">

**Comment by jancavan** [comment]
Does this need to be changed in https://github.com/Automattic/notifications-client?

Most posts don't have a top-margin, but there are some posts that do have them. Example:

![screenshot 2018-01-17 14 17 35](https://user-images.githubusercontent.com/4924246/35070121-2cb2f942-fb91-11e7-913f-e6c7396ca51b.png)

**Comment by bluefuton** [comment]
Thank you @kwight :)
