### ISSUE TITLE
Store: Is possible to choose non-supported countries & currencies from wp-admin

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#21557]
At the moment the Store is limited to US/Canada, but from `wp-admin` other countries as well as currencies can be chosen, creating odd behavior or confusing information through the whole site, for example when displaying products, calculating taxes or setting a shipping address:

#### Steps to reproduce
1. Starting at URL: `https://$DOMAIN/wp-admin/admin.php?page=wc-settings&tab=general`
2. Change country to `Vietnam`
3. Change currency to `Ukrainian Hryvnia`
4. Save changes

####  Example 1:
If we check the Store settings, the Store location is set to `VN`, clicking on `Edit address` does not offer the new countries (keeps either US or Canada) however Taxjar and shipping is affected:

<img width="1280" alt="screen shot 2018-01-16 at 09 14 15" src="https://user-images.githubusercontent.com/3812076/34984660-434b2290-fae4-11e7-8ce3-41315da439dd.png">

For example, Taxjar message:` "We have automatically detected your ship from state as being VN"`

<img width="1064" alt="screen shot 2018-01-16 at 17 47 26" src="https://user-images.githubusercontent.com/3812076/34985012-5991970e-fae5-11e7-9a84-1dc36164d118.png">

####  Example 2:

Changing the currency to Ukrainian Hryvnias changes it on the front end as well as on the Stats screen, but this is not eligible via Calypso and the only options are: USD, AUS, CAD, GBP, or Brazilian Real, under https://wordpress.com/store/settings/$DOMAIN > `Store Currency`

<img width="736" alt="screen shot 2018-01-16 at 17 13 25" src="https://user-images.githubusercontent.com/3812076/34985084-95ea78a6-fae5-11e7-95f9-a0299407f9b5.png">
<img width="974" alt="screen shot 2018-01-16 at 09 16 06" src="https://user-images.githubusercontent.com/3812076/34985089-9a44b678-fae5-11e7-954f-2756fdb6df76.png">

#### What I expected

Changes to get saved and be consistent across Calypso/wp-admin , or otherwise not be able to select non-supported countries/currencies.

**Comment by allendav** [comment]
I think https://github.com/Automattic/wp-calypso/issues/21304 covers this, no?

**Comment by designsimply** [comment]
> I think #21304 covers this, no?

#21304 appears to be talking about cases where someone guesses at a URL for a Store route, and if I am reading #21557 correctly, it talks about currency shown in Calypso not matching with the selected currency setting for the Store. Would fixing routes with redirects fix the currency display issue? (It's possible! I am asking because I'm not sure based on the description in #21304.)

**Comment by allendav** [comment]
@designsimply wrote:

> #21304 appears to be talking about cases where someone guesses at a URL for a Store route

Yep, exactly

> Would fixing routes with redirects fix the currency display issue?

Yes - instead of seeing the settings page they would see something like this:

<img width="1174" alt="5" src="https://user-images.githubusercontent.com/1595739/35016334-efff15c2-facc-11e7-9128-a455c5c8a1a1.png">

**Comment by allendav** [comment]
Adding this to the list in https://github.com/Automattic/wp-calypso/issues/21574 and closing this issue
