### ISSUE TITLE
Domains: ccTLD .ca - improve user-facing notices about privacy and registration type

### ISSUE THREAD

**Issue by wensco** [Automattic/wp-calypso#21564]
The way that .ca handles privacy is slightly mysterious and confusing to our users. Below are a few suggestions to add clarity.

1. Create a support doc explaining individual and non-individual registrations and how this impacts privacy - add a brief notice in the registration flow (the point where they are asked to choose the registration type would be a good place) and link to the document.
<img width="578" alt="ca contact" src="https://user-images.githubusercontent.com/7942966/34999364-8622cf9e-faaf-11e7-91df-650a622b6887.png">

2. Make sure it's clear that the user will not be able to change individual to non-individual and vice versa.

3. Improve error message when a user with a non-individual registration tries to edit contact info to remove the organization name. Currently, we display this:
<img width="842" alt="ca unable to update whois" src="https://user-images.githubusercontent.com/7942966/34999581-14074362-fab0-11e7-96b6-3b3a876aca68.png">

**Comment by hewsut** [comment]
Related: #19916, likely depends on #20081
