### ISSUE TITLE
Store: Add Tracks For MailChimp Integration

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#21579]
It appears we never adding any tracks to the MailChimp integration setup or management utilities that were shipped last quarter in Store. There has been a bit of interest from other teams in the company around this integration, so it would be nice if we had some usage data around it.

Thinking it would be handy to `recordTrack` on each step of the setup flow, and have tracks around the update/resync actions shown at https://wordpress.com/store/settings/email/STORE.

/cc @budzanowski

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
