### ISSUE TITLE
Settings > Traffic displays blank page in IE11

### ISSUE THREAD

**Issue by kamikazeballoon** [Automattic/wp-calypso#21575]
#### Steps to reproduce
1. Open any WordPress.com blog in IE11.
2. Click Settings in the sidebar
3. Click Traffic
4. (Or visit https://wordpress.com/settings/traffic/[blog-url])

#### What I expected
The Traffic page which appears in Edge, Firefox and Chrome

#### What happened instead
Only the top navbar displayed - see screenshots (mine below, user's in zd)

#### Browser / OS version
IE11 on Windows 10, tested with two accounts; both verified original user's issue.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1575367/35017046-099ff59c-fb80-11e7-8825-b23ab98b8358.png)

#### Context / Source

See 902796-zen Thank you :)

**Comment by rachelmcr** [comment]
Thanks for the report! I reproduced this issue in VirtualBox with Windows 10/IE 11. I see the following console error when I try to open the Traffic page:

> TypeError: Object doesn't support property or method 'startsWith'
> at a (https://wordpress.com/calypso/settings-traffic.842255112b74de98f67c.min.js:1:316534)

**Comment by thehenrybyrd** [comment]
I had a similar report yesterday. Didn't realize it was a bug though - the user is on Windows 7, and IE 11 has some OS-dependent features, so I assumed it was just too old.
This user was having trouble in My Site > Themes.

![wordpress screencap 01 1](https://user-images.githubusercontent.com/15107387/35848265-2b9887d0-0b26-11e8-87e5-ebb3977ed028.PNG)

See 939421-zen for context.

**Comment by molszewska** [comment]
Slightly similar case - blank screen on IE 11 while trying to upgrade the site.
941396-zen

**Comment by kamikazeballoon** [comment]
Can't replicate Themes, but here's general Settings, Plans and Domains. I have zero idea how to actually use the console window but it's there anyway :)

Domains reported 1728121-hc.

![domains](https://user-images.githubusercontent.com/1575367/35884002-18c619b0-0bee-11e8-9a0f-1ec52b90af63.PNG)
![plans](https://user-images.githubusercontent.com/1575367/35884003-18ef569a-0bee-11e8-8e50-b7df9c9e2afc.PNG)
![settings](https://user-images.githubusercontent.com/1575367/35884005-1918c408-0bee-11e8-8738-1e97becbf1c5.PNG)

**Comment by davipontesblog** [comment]
We have another report today with user in live chat.
Windows 10 Home, IE Version 1709
"When I click on the following Dashboard items, I get a blank screen: Plan, Domains, Settings. Additionally, the same thing happens when I click on Manage Purchases in my profile. I've always had access to these before. "

**Comment by sdixon194** [comment]
1798878-HC

User trying to renew the plan using both Google Chrome and IE on Windows Vista was given a blank page on "Manage Purchases" as well as their Plans page. 

![screenshot](https://user-images.githubusercontent.com/33553323/36171248-e3aa4e36-10cf-11e8-9844-dee70f6e4adb.png)

**Comment by lancewillett** [comment]
This should be fixed with #22622 

Please re-open or create new tickets if you see more issues in IE 11 or blank pages.

One helpful thing would be to use F12 to open the Internet Explorer dev tools and capture any JS errors you see there, to add to your bug report.
