### ISSUE TITLE
Request for change of copy for the People page

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/wp-calypso#21586]
Whenever someone goes to add a user to their site here https://wordpress.com/people/new/ they're met with the message “Invite up to 10 email addresses and/or WordPress.com usernames. Those needing a username will be sent instructions on how to create one.”

I’ve encountered quite a few people who think, because of this wording, that they can only add 10 people to their site instead of 10 people at a time.

Can we update the copy to be a bit more clear here? :)

**Comment by benhuberman** [comment]
That's a great catch @Piyopiyo-Kitsune. Here's an alternative version:
> Invite new users -- up to 10 at a time -- by adding their email addresses or WordPress.com usernames. If they don't have an account yet, we'll send them instructions on how to create one."

What do you think?

This is longer than the current version -- 187 characters vs 136 -- so in case this creates an issue design-wise, I'm happy to take another stab at something shorter (though on desktop, at least, it doesn't seem like this would force another line).

**Comment by benhuberman** [comment]
Alternatively, if we wanted to go with something a little "warmer" / more fun, but with slightly less detail (i.e. omitting the part about the instructions we'll be sending those without accounts), we could go with something like:

> Want to invite new users to your site? The more the merrier! Invite as many as you want, up to 10 at a time, by adding their email addresses or WordPress.com usernames.

This one clocks in at 166 characters, so quite a bit shorter than the proposed edit above.

**Comment by Piyopiyo-Kitsune** [comment]
@benhuberman I think your second copy does have more friendly and fun messaging while being clear on how many people can be added total and at a time :)

**Comment by arunsathiya** [comment]
While the second copy suggested is fun, does it go by the tone used by WordPress.com in all other places? I would definitely prefer #1 or here is my suggestion.

> Invite upto 10 in a go, using their WordPress.com username or email address. Those without an username will be instructed how to create one.

**Comment by designsimply** [comment]
Original:

> Invite up to 10 email addresses and/or WordPress.com usernames. Those needing a username will be sent instructions on how to create one.

Suggested (a **super** simple change that just adds "at a time" to the end of the first sentence):

> Invite up to 10 email addresses or WordPress.com usernames at a time. Those needing a username will be sent instructions on how to create one.

Otherwise, I like @benhuberman's suggestion and I think the tone does match with things used in other places on WordPress.com. 😊 My tendency, though, is to want keep it simple.

**Comment by benhuberman** [comment]
@designsimply I'm not opposed to keeping it simple; I thought there was an opportunity to inject a little warmth/personality there, though, and I also find the combination of "inviting" with usernames or email addresses awkward (you invite the person, not the username/address). If we keep it simple, I'd still vote for changing "Invite" to "**Add** up to 10... etc."
