### ISSUE TITLE
Editor: Images are not aligning to the centre if they have a caption on "Hive" theme

### ISSUE THREAD

**Issue by dromero20** [Automattic/wp-calypso#21592]
#### Steps to reproduce
1. Activate the Theme "Hive" and remove all sidebar Wigets.
2. Create a new Post or Page and place an image from media.
3. Align that picture to the centre.
4. Click on "caption" and write something.
5. Save your changes.

#### What I expected

The picture with the caption should be aligned to the center.

#### What happened instead

The picture is aligned to the left. If you remove the caption, the picture is aligned to centre properly.

#### Screenshot

With caption
<img width="1285" alt="captura de pantalla 2018-01-17 a las 9 30 08" src="https://user-images.githubusercontent.com/23258551/35032929-17a65f26-fb69-11e7-9062-51d1215e19ae.png">

Without caption
<img width="1346" alt="captura de pantalla 2018-01-17 a las 9 30 18" src="https://user-images.githubusercontent.com/23258551/35032934-1e6e5570-fb69-11e7-929c-72f04ea26aac.png">

#### Context / Source

Seen in: 1554696-hc

This is happening either in Calypso and wp-admin. However I tested it in a self-hosted site and it's working properly, so I'd say it's not a Core issue.

**Comment by rachelmcr** [comment]
Thanks for the report! Closing since this is an issue with a WordPress.com theme rather than Calypso itself. (Moved to internal report: 2228-wpcom-themes)
