### ISSUE TITLE
Documentation: Add doc describing how to write unit tests

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#216]
We should have a document that describes how to write and run Calypso unit tests

**Comment by pixelhandler** [comment]
@hoverduck does this document, https://github.com/Automattic/wp-calypso/blob/master/test/README.md meet the needs of this issue?

**Comment by hoverduck** [comment]
@pixelhandler Yes, that looks great.  Closing the issue.

Thanks!
