### ISSUE TITLE
Activity Log: button “Try again” in rewind doesn't work

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#21608]
When rewind has a problem restoring my site, “Try again” button doesn’t work at all. No errors in the console or anything.

![rewind-try-again](https://user-images.githubusercontent.com/390760/35049391-c3610aea-fb97-11e7-945e-3b6db2ef6e9a.gif)

**Comment by MichaelArestad** [comment]
CC @samhotchkiss to investigate

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/20454
