### ISSUE TITLE
Activity Log: “Any Questions?” link takes a while to show up

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#21607]
“Any Questions?” link in the backup download dialog took a while to show up ~5s.

Is this due to the fact we’re querying available spots in HappyChat on-the-fly? Can we decrease that delay?

![rewind-any-questions](https://user-images.githubusercontent.com/390760/35049229-3aa0adc8-fb97-11e7-876a-8f127733028f.gif)

**Comment by mattwondra** [comment]
The long-term ideal is that everyone in Calypso is immediately and always connected to the Happychat websocket. We're very close to being able to scale production Happychat across multiple containers too, which will make it easy to add new containers to share the load if the socket load gets too much.

We're currently serving ~1,000–2,000 connections at once and that seems to be going ok. This could _theoretically_ bring us to a max of ~3,200 connections (assuming no crossover).

@beaucollins — What do you think the risk is of trying that out to enable a better quicker help experience on the Activity Log HC entry points?
