### ISSUE TITLE
Activity Log: highlight credentials settings when jumping from AL initial setup

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#21610]
When asked to add site credentials, I get dropped into a settings screen without further indication on what do to.

![rewind-credentials](https://user-images.githubusercontent.com/390760/35049996-a43d0608-fb99-11e7-91e9-a1b194d38aca.gif)

This flow can be confusing, especially when we’re dealing with something as technical as “credentials”. We should highlight the credentials box somehow when jumping from the initial AL setup to make it more evident: greying-out the rest, adding a note on top?

Quick proposal:

![image](https://user-images.githubusercontent.com/390760/35050083-dfe0e6e8-fb99-11e7-8a93-3d8e7497fc14.png)

The alternative would be to create an ad-hoc version of the flow for initial setups (the same we'll have on site creation).

**Comment by keoshi** [comment]
Ping @MichaelArestad for feedback, asked the devs what can be done to target a single card here: p9rlnk-4C-p2

**Comment by keoshi** [comment]
It could also be a slow pulse animation where we change the opacity of the element two or three times to highlight it, and dismiss that state if the element (or any inside it) is clicked.

**Comment by MichaelArestad** [comment]
I think we can add ways to target a single card. I would maybe temporarily grey the other cards out for focus and then fade it in. We should also be able to focus individual settings (not just settings groups).

**Comment by keoshi** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/21961
