### ISSUE TITLE
G Suite: Add option to verified domain at G Suite set up wizard

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#21640]
At the Name Servers management screen (https://wordpress.com/domains/manage/yourgroovydomain.com/name-servers/yourgroovydomain.com) there is a button to help user add an existent G Suite account. When clicking that button, it asks G Suite token to verify domain, however some times user may have already verified their domain before so they just need help to add the MX and TXT records. 

#### Steps to reproduce
1. Starting at URL:https://wordpress.com/domains/manage/yourgroovydomain.com/name-servers/yourgroovydomain.com
2. Click G Suite button
3. It asks G Suite token to verify domain and the Set up G Suite button stays inactive

#### What I expected

I expected that there was an option for when you have already verified your domain and just want to add the MX records.

#### Screenshot / Video
https://cloudup.com/cliBLRIMzR6

#### Context / Source

There are cases where the domain has already been verified and user needs to add the email records manually, which is difficult for them. Thus providing the option of simply clicking a button would be helpful.

**Comment by klimeryk** [comment]
Even better - we can easily detect that case by just looking at existing DNS records.
I wonder, though, how often does this happen? Seems like a good candidate for the looming Domain Management revamp (~Q1/Q2 2018), so thanks for the suggestion 👍

**Comment by catkit** [comment]
Between yesterday when I added this issue and today it happened twice for me while on Live Chat. One was for a domain transfer in. I'm not sure why the domain records weren't imported, but the domain was pointing to Weebly and registered at GoDaddy. So when the transfer was complete, it seems it restored GoDaddy's name servers and dismissed the other records that probably were managed at Weebly.
The one from today, user bought G Suite directly from Google and verified domain with a meta tag.
