### ISSUE TITLE
Signup: Use `ThemesList` instead of `DssThemeThumbnail`

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#2164]
For less redundancy and maintenance burden.

See discussion at https://github.com/Automattic/wp-calypso/pull/1628#issuecomment-164847651

Possibly related PR to steal code from: #541 (specifically ff12de5b859be71e85a2c354b794d8711faeca6e)

CC @sirbrillig

**Comment by sirbrillig** [comment]
Honestly at this point I would be inclined to just remove all of DSS entirely. My reasons:

1. The code will still be around in git history
2. There are no current tests ongoing using DSS
3. Several conversations have pointed to the general fragility of the current approach
4. It would be significantly less work to remove it all than switch the components

Thoughts, @ianstewart ? @kwight ?

**Comment by kwight** [comment]
I'd be tempted to just leave it as is. DSS will certainly need more work (which will include this change), but it's nice to keep it in Calypso for now for demo and testing purposes.

**Comment by sirbrillig** [comment]
(At the very least, we could delete the `ThemeThumbnail` file, since it is not being used)

**Comment by kwight** [comment]
We'll be removing DSS for now anyways, because of Headstart work: #2193 .

**Comment by ockham** [comment]
Closed by #2193 and #2194.
