### ISSUE TITLE
Comments: add more formatting options in edit mode

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#21663]
We currently provide folks a plain text area, let's also add some formatting helpers like we do in wp-admin:

![screen shot 2018-01-18 at 2 13 03 pm](https://user-images.githubusercontent.com/1270189/35124214-2695947e-fc5a-11e7-8bbe-311b511611a3.png)

![screen shot 2018-01-18 at 2 18 39 pm](https://user-images.githubusercontent.com/1270189/35124315-818967a2-fc5a-11e7-93bb-15d8c949dead.png)

**Comment by juliasydnor** [comment]
Yes, please. We're getting a fair number of users asking what happened to the formatting buttons, and are unhappy with having to use HTML to create links, etc.

One example: 924569-zen
