### ISSUE TITLE
Reader: Obtrusive global notice for Following site in Site Stream

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#21668]
After Following a site from its Site Stream, a global notice appears on the upper right corner. It's really obtrusive and it doesn't help in making the Settings button more discoverable:

![screenshot 2018-01-18 17 55 54](https://user-images.githubusercontent.com/4924246/35133068-1dd7de9a-fc83-11e7-8756-d91a0529f8e5.png)

I think we should remove this at least in the Site Stream and `>660px`. The Follow button changing to a green Following in an instant is enough visual feedback.

**Comment by blowery** [comment]
Should we just remove them altogether? I'm failing to recall why we added them in the first place. @bluefuton you recall?

**Comment by jancavan** [comment]
> Should we just remove them altogether? I'm failing to recall why we added them in the first place. 

I also don't remember why we added it. But yes, let's just remove them altogether.

**Comment by bluefuton** [comment]
Cool - I'll spin up a PR to remove following notices.
