### ISSUE TITLE
Jetpack Onboarding: Link Summary steps to actual steps

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#21689]
The Summary steps are currently static, and don't do anything when clicked.

<img width="822" alt="screen shot 2017-08-30 at 1 56 01 pm" src="https://user-images.githubusercontent.com/22752103/29887331-12d931e0-8d8b-11e7-805c-81167215bfb7.png">

So, the question is, do we want to make them lead to each corresponding step?
 This is how it's done in the Jetpack Onboarding plugin IIRC. And it would be particularly helpful for steps that have not yet been completed.

Note that in #17652 we suggested to remove the Back button  in this last Summary step, and in #20749 we removed it, which removed the last link to any of the other steps from the Summary step.

What do y'all think?

cc @MichaelArestad, @AnnaMag, @ockham

**Comment by MichaelArestad** [comment]
Yes, let's link them to the steps. Also, let's make sure the contrast meets AA standards (if it's a normal link, it should be okay).
