### ISSUE TITLE
Jetpack Onboarding: Use current data in all steps

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#21684]
Since we can load the onboarding data at the time we show each of the steps, it makes sense to populate the data in each of the steps.

That's pretty straightforward for the Site Title and Business Address steps, where we just populate the form fields.

However, for the tile steps (Site Type, Homepage Format, Contact Form), do we want to display the current selection in any way?

Also, for the WooCommerce step, do we want to indicate in any way if WooCommerce is already installed?

cc @MichaelArestad

**Comment by tyxla** [comment]
This was addressed for the Site Title step in #21598, and is being addressed for the Business Address step in #21645.

**Comment by tyxla** [comment]
@MichaelArestad what do you think? (see the questions above)

**Comment by MichaelArestad** [comment]
I'm not sure I follow. Can you add a few screenshots for more context?

**Comment by tyxla** [comment]
As discussed in Slack, for tiles let's reuse the focus state of the input fields, but adapted to use only box shadow. 

Discussion was here: p1516387223001774-slack-jetpack-onboarding

**Comment by tyxla** [comment]
We've got several PRs that cover the remaining cases for indicating existing state, these would need some 👀 

#22246 - site type and homepage format steps
#22247 - contact form step
#22248 - WooCommerce step
