### ISSUE TITLE
Search (Beta) shows for non-Jetpack sites in Calypso's "My Plan"

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#21711]
Two issues with "Search (Beta)", i.e. the new Jetpack search showing up under My Site > Plan > My Plan.

1. It shows for normal Business plan sites, which it shouldn't.

2. It shows for AT sites, which it should, but it links to Calypso's `wordpress.com/settings/traffic/` and there's no option to enable the new search from there. It can ONLY be enabled from WP-Admin > Jetpack settings.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/my-plan/{site}

Scroll down, you'll see this:

![image](https://user-images.githubusercontent.com/6505293/35182930-31b0ca58-fdff-11e7-9b22-fc5cbd05a63a.png)

* To not show up for normal Business plan sites

* To does show up for AT sites (which it does), BUT, it links to a non-existent setting in `wordpress.com/settings/traffic/{site}` ...

There's no option to enable this search from `/settings/traffic/{site}`. This is reported in #19743

**Comment by gibrown** [comment]
I think the bug here is that we should support Search on all business plan sites. The code just needs to be synced from Jetpack to WP.com and there is no reason we can't.

**Comment by ehti** [comment]
That would be ideal. :D
