### ISSUE TITLE
Revise new site copy

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#21724]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/new?ref=calypso-selector

#### What I expected
After reading the copy, I would expect to pick a theme in the signup flow. 

#### What happened instead
The theme step has been removed from most flows in signup.

#### Browser / OS version
All

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/35223428-556a4b62-ff4f-11e7-8723-fe3512ec9428.png)

#### Next steps
Update the copy so that it doesn't reference the themes.

**Comment by ianstewart** [comment]
> Update the copy so that it doesn't reference the themes.

Could we also transpose "new" and "shiny" in the leftmost title at the same time? (It should be "shiny new" not "new shiny.")

**Comment by fditrapani** [comment]
Sure thing @ianstewart. That shouldn't be a problem.

**Comment by fditrapani** [comment]
Fix deployed: https://github.com/Automattic/wp-calypso/pull/22079
