### ISSUE TITLE
Store: Stripe Connect: Allow merchants to enter customer card info for new orders

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#21749]
For merchants who have set up their online stores through our Stripe Connect platform, allow merchants to enter customer debit or credit card info in the Edit (Create) Order view as payment. This is a useful flow for when a customer calls the merchant and places their order over the telephone.

Note: We can leverage Stripe resources to create a fully PCI compliant implementation that integrates nicely into React:

See Creating Direct Charges
https://stripe.com/docs/connect/direct-charges

See Stripe React Elements
https://github.com/stripe/react-stripe-elements

See Integration Security Guide
https://stripe.com/docs/security

Note: Not yet in scope for any release.

**Comment by kellychoffman** [comment]
@jameskoster has a design for this all ready. We held off due to some legal questions we had. I think we should revisit the prioritization of this after the first version of order creation is launched.
