### ISSUE TITLE
People: Message after accepting invite always says 'user' not 'administrator', 'editor' etc

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#2176]
1. Accept invite as administrator of site
2. Message says "You're now a user of: e2eflowtesting"

Enhancement: It would be nice to state:

"You're now an administrator of: e2eflowtesting" or "You're now an editor of: e2eflowtesting" etc.

![confirm message](https://cloud.githubusercontent.com/assets/128826/12169404/f19b50de-b583-11e5-8fbc-f766cf6b4105.png)

**Comment by lezama** [comment]
We need more tester likes you @alisterscott! thanks for testing :)

**Comment by alisterscott** [comment]
I retested this in wpcalypso.wordpress.com as an Editor and an Author and didn't see any message when accepting the invite and creating a new account. Has this changed?

**Comment by lezama** [comment]
Notices for invites are momentarily broken, working on it :)
