### ISSUE TITLE
Purchases: improve messaging when cancelling Business plans originally bought via upsell

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#2177]
Originally reported by @melanieharari:

Consider this scenario:

- the user cancels the Business plan and is refunded $199 for the upgrade from Premium to Business.
- we don’t refund the original $99 they paid, but they’re switched to the Free plan anyways. In some cases, this can cause unexpected issues with the site, when premium themes are no longer available or custom design options are lost.
- uers must contact support to be refunded the $99 or add back their Premium plan.

This is what these users see on `/purchases` when a user who bought Business via an upsell tries to cancel:
<img width="388" alt="screen-shot-2015-12-30-at-1-16-12-pm" src="https://cloud.githubusercontent.com/assets/1248436/12169653/5ba9c702-b53a-11e5-9221-ddbc7b8ab8a7.png">

@melanieharari suggested the following changes to the copy in these screens:

- The Change Plan link leads to the Plans page. The plan cannot currently be changed on the Plans page (see #2048). Should we remove this link or rename it to something like “Compare Plans”?
- There is no notice that canceling the Business plan will switch back to the Free plan. (We should consider adding this)
- The refund amount listed is $299, which is not correct. We should either fix the refund situation and refund the entire amount, or we should specify what will be refunded and/or how to get the full refund. @peterbutler said it might be possible to fix how refunds work, so users get $199 + the initial $99 back.

cc @breezyskies @bdukes @lettergrade

**Comment by bdukes** [comment]
I think you intended to cc @BandonRandon rather than @bdukes

**Comment by fabianapsimoes** [comment]
Ops! I'm sorry. Thanks for the note!

**Comment by spncrb** [comment]
Have we thought about adding the option to downgrade in here?  I'd love to complicate this further with the following:

1) Both purchases are refundable: Give them two options a) refund the $199 and revert to premium b) full refund and revert them to free

2) The upsell is refundable but not the original purchase - the only option here should be to revert them to premium and change the expiry back to one year from the purchase date.

Am I missing something?  Beyond situation 1), why would we revert them to free? (maybe technical limits - sorry if so)

**Comment by melanieharari** [comment]
The only reason I can see—beyond situation 1—for reverting to the free plan is if the user specifically asked to revert to free, so that they could leave WP.com, avoid future renewals, or delete their site.

**Comment by Tug** [comment]
@peterbutler I would be interested in knowing how you think we could fix refunds.

I don't think this is an easy fix. Here is a tricky scenario that might be interesting
    - User was on a Premium plan for a year
    - Upgrades to a Business plan shortly before the Premium plan expires
    - Cancels his Business plan

Result:
    - Case A: if we decide to simply refund the total amount: User simply had a Premium Plan for free for a year.
    - Case B: if we downgrade the user to a Premium plan: We might either be downgrading to an expired plan or renewing a Premium plan without the user paying anything.

To fix Case A, we would have to check the list of subscription for a site, exclude those which are not related to a plan, and sum every refundable subscriptions (using the price of the associated transaction).

To fix Case B, we would have to check the last subscription and see if it's still valid, if it's not then we have to look at the next subscription (a domain upgrade for instance) and check if it's still valid. 

Both fixes seem reall sloppy and I don't know how they would behave if we add HE manual interventions in the mix.

For now I think we can start by displaying the correct refund value.

**Comment by fabianapsimoes** [comment]
We decide to revert to Free, since downgrades are more complicated than the scope of this issue and would be an entirely new concept in our Store.

@melanieharari @spncrb could you give the new cancellation design a try, and see if it addresses the confusion reported here?

**Comment by BandonRandon** [comment]
While reverting to free may be the simplest solution from a technical aspect I don't think this is the best our users. I don't have the data, however, anecdotally I'd think this would cause more confusion for uers in the situations that both @melanieharari  and @spncrb mentioned above. 

If this is something we do implement I would stress how important it is to look at it with data, perhaps adding a track and looking at a way to link support requests from these users to the downgrade options.

**Comment by fabianapsimoes** [comment]
@BandonRandon yup, absolutely. It's mostly that this is outside the scope of this issue, which focused mostly on messaging improvements in Calypso. Changes to how refunds / downgrades work are on team Gold's backlog (see p2MSmN-4i7-p2).

We've implemented several changes to the cancellation flow, and hope to have addressed this issue according to Mike's guidance. I'm closing this, but feel free to give the new flow a spin and reopen this in case you'd like to suggest any further improvements.
