### ISSUE TITLE
Theme page for a8c.tv is stuck forever in the loading state

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#21784]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/a8c-tv/a8c.tv
2. The theme page is stuck forever in the loading state and never recovers:

<img width="985" alt="a8c-tv-loading" src="https://user-images.githubusercontent.com/664258/35328971-679b53d4-00fe-11e8-85f1-69ddfcb15d32.png">

**Comment by lancewillett** [comment]
I don't think the Theme Showcase is built to support private a8c themes.

Suggest closing as wont-fix for this one.

Alternative fix would be to redirect a8c themes to WP Admin instead. But, ideally no one is managing these themes via a GUI too often.
