### ISSUE TITLE
Store Orders: Help store owners fill out new order

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#21795]
A store owner can create a order by filling out customer details, adding products, etc; but no fields are required, so an order can be created without customer information, or without any products added.

Technically this is fine, but from a UX perspective it's strange. We could fix this by:

- Creating a walkthrough for store owners
- Adding form validation to flag empty sections
- Something else? Let's use this issue to figure it out 🙂 

See p90Yrv-vh-p2

**Comment by allendav** [comment]
This came up in a usability study too - the customer seemed unsure of 1) what to do first/next and 2) if they were "done"
