### ISSUE TITLE
Store ProductSearch: Hide search field if there are few products

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#21796]
This is a suggestion from @dechov – When adding products to an order, we pop up a products list and search, the `ProductSearch` component. If there are only a few products, we don't need to show the search box, because all the products are already in view. For example, with 4 products, you don't need to search for anything:

<img width="669" alt="screen shot 2018-01-24 at 11 51 46 am" src="https://user-images.githubusercontent.com/541093/35345250-23d3ddac-00fd-11e8-9ebb-10cb5a644f16.png">

**Comment by aks-** [comment]
@ryelle How do you determine when products are only "few" and we can hide the search bar? Is there a specific number?
