### ISSUE TITLE
Reader: no more notifications while following & unfollowing

### ISSUE THREAD

**Issue by abidhahmed** [Automattic/wp-calypso#21822]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/discover
2. Click `+ Follow` (or stop following) for any content (inc. main Discover)

#### What I expected

Notification within Calypso that should've said "You are now following X" and "You're no longer following X"

#### What happened instead

No notification whatsoever.

#### Browser / OS version

Happens across all devices.

#### Context / Source

#automated-testing - was going through Reader the past couple of weeks and the tests started to break today.

#### Misc

The following issues might be related :
https://github.com/Automattic/wp-calypso/pull/21816
https://github.com/Automattic/wp-calypso/pull/21815

**Comment by blowery** [comment]
@abidhahmed we removed those intentionally in https://github.com/Automattic/wp-calypso/pull/21727

**Comment by lancewillett** [comment]
Thanks @abidhahmed for the report.
