### ISSUE TITLE
Notifications: add a Promotion checkbox to the Notifications > Updates page

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2184]
Raised by @meremagee 

> With the completion of a recent google apps nudge campaign, the `promotion` unsubscribe list has gone to production. Users have been unsubscribed to this list against the `promotion` API key, but won't yet be able to manage that subscription in the new Updates section of notifs grand central. We should move forward with adding that list to the UI for users to manage. (8-gh-emails#issuecomment-106098572)

The idea is to add a fourth checkbox to this screen labeled "Promotion" so that users can opt out of promotional emails within Calypso.

Current screen shot for reference:

![screen shot 2016-01-07 at 10 05 44](https://cloud.githubusercontent.com/assets/1119271/12173713/6698ca1e-b526-11e5-9a23-71cb05598130.png)

**Comment by rodrigoi** [comment]
@designsimply any suggestions about the text to use as description of this new item?

Thanks!

**Comment by meremagee** [comment]
- Key = `promotion`
 - _UI label_: Promotions
 - _UI text_: Promotions and deals on upgrades
 - will encompass sales-related content, upgrade related promotions, etc

also note that we'll start sending emails from the news list, so it would be great to get that in there as well. 

- Key = `news`
 - _UI label_: News
 - _UI text_: WordPress.com news and announcements
 - will encompass new product & feature announcements, partnerships, etc

Fun fact: there are a finite set of email lists, so they won't grow mysteriously as folks unsubscribe from various lists. The impetus for not adding all the possible lists to the UI out of the gate was that for some of the lists, we don't actually have content/emails yet. We didn't want to have a check box that promised updates in some capacity and then fail to deliver those updates. :balloon:

**Comment by rodrigoi** [comment]
@meremagee @designsimply Updated!

![news-promotions](https://cloud.githubusercontent.com/assets/233601/12459437/75b6af2c-bf8d-11e5-8637-8ff5e9edcf70.png)

Just give me the thumbs up and tell me when to merge and deploy :wink:

**Comment by meremagee** [comment]
Wow, sorry for not catching this before. 👍 from me!

Noting that to round out the list, we have room for *digest* and *recommendations* (as noted in original list spec [here](https://cloudup.com/cbcnJQeMEky)). We don't want this list to grow indefinitely, but we also don't want to make promises to users about receiving helpful info like digests of their activity if we don't yet have the emails in production. So, as discussed in earlier repo, we'll hold off on putting the last 2 lists up (digest & recommendations) until we move forward on those ones.

Thanks @rodrigoi

**Comment by rodrigoi** [comment]
Deployed 😉
