### ISSUE TITLE
Credit Card error message

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/wp-calypso#21843]
I've found a strange error while working with an individual in #917195-zen. Please see the attached screen shot.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Select the domain mapping subscription
3.
4.

#### What I expected
Updated credit card information message.

#### What happened instead
See attached screen shot.

#### Browser / OS version
Chrome Version 63.0.3239.132 / macOS version 10.13.2

#### Screenshot / Video
<img width="730" alt="screen shot 2018-01-24 at 5 44 02 pm" src="https://user-images.githubusercontent.com/17694715/35411627-4be28a56-01ce-11e8-83e7-a229f0da3a9e.png">

**Comment by rralian** [comment]
This is fixed in production now. Thanks for taking the time to report this @Piyopiyo-Kitsune. I think that message has been broken for i18n users for a while. Glad to fix these broken windows. :-)
