### ISSUE TITLE
Vaultpress to Jetpack transition flow

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#21850]
The latest screenshots and flows can be found in the prototype. I **strongly** suggest familiarizing yourself with the prototype for full flows: p9rlnk-34

For ease of implementation, I've broken this down into unique screens, implementation details, and their assets. The first list is for tracking implementation. The details for each are just past the list.

- [ ] 1. JITM Banner
- [x] 2. Backups and security welcome
- [x] 3a. Migrate credentials prompt
- [x] 3b. Add your credentials
- [x] 4. Credentials form
- [x] 5. Success message

## 1. JITM Banner

These banners will be the entry points into the flow from Jetpack for the following user types:
* Users with Jetpack plan with or without Vaultpress with or without credentials
* Users with Jetpack without a plan (free)

**These will not be shown for anyone with a Vaultpress plan. (At least not yet)**

![vp-creds jetpack dashboard banner](https://user-images.githubusercontent.com/1123119/35409476-92402872-01cf-11e8-8acb-190e8f84d335.jpg)
![vp-creds jetpack settings banner](https://user-images.githubusercontent.com/1123119/35409477-9250d08c-01cf-11e8-9f66-f1463f51c345.jpg)
![vp-creds wp-admin dashboard banner](https://user-images.githubusercontent.com/1123119/35409478-925f509e-01cf-11e8-84a1-68e04b9a47ab.jpg)

### Copy
**Headline**
> Try Jetpack's powerful new backup and security

**Subhead**
> With a Jetpack plan, you can rewind your site to any event in its history

**Button - folks with Vaultpress**
> Switch now

**Button - folks without Vaultpress**
> Set up

**Button - folks without a plan**
> Upgrade

### Implementation notes
* The button text will change depending on user flow
* The banner will appear in the wp-admin Dashboard, the Jetpack Dashboard, and the Jetpack Settings > Security > Backups and security scanning group

## 2. Backups and security welcome
This will be the next step for folks who have clicked through the variety of JITM banners (including one on the Activity Log page). They will likely need to log in before they can see this.

![vp-no-creds welcome](https://user-images.githubusercontent.com/1123119/35415301-52b578de-01e2-11e8-8a5b-7106750bb7e2.jpg)

### Copy
**Headline**
> Welcome to Jetpack's new backups and security

**SVG**
[security.svg](https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/security.svg)

> Backing up and securing your site should be a breeze. Our new seamless system makes it possible to see all your site's activity from one convenient dashboard.

**Button - folks with Vaultpress**
> Switch now

**Button - folks without Vaultpress**
> Continue setup

**Button - folks without a plan**
> Upgrade now

**Cancel link**
> No thanks

**Subhead**
> What else can it do?

**Section 1 heading**
> Rewind to any event

**Section 1 copy**
> As soon as you switch over, we will start tracking every change made to your site and allow you to rewind to any past event. If you lose a file, get hacked, or just liked your site better before some changes, you can rewind with a click of a button.

**Section 1 SVG**
[backup.svg](https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/backup.svg)

**Section 2 heading**
> Stay on top of your site's security

**Section 2 copy**
> When something happens to your website you want to know it immediately. And you will – we'll send you instant alerts based on our 24/7 monitoring of advanced threats.

**Section 2 SVG**
[security-issue.svg](https://cldup.com/wlmSPmuUKU.svg) (might need to be added to the Calypso `images/illustrations/` directory)

**Section 3 heading**
> Log all events on your site

**Section 3 copy**
> Access a new, streamlined history of events on your site – from published posts to user-role changes. If you ever need to figure out what happened when, now you can get the answer in seconds.

**Section 3 SVG**
[stats.svg](https://cldup.com/T4IGTV0IKa.svg) (needs to be added to the Calypso `images/illustrations/` directory)

### Implementation notes
* The button text will change depending on user flow
* When `No thanks` is selected, it just takes them back to where they were previously in wp-admin or Calypso

## 3a. Migrate credentials prompt
This will only show for _users with Jetpack plan with Vaultpress with valid credentials_. There is another version for other user flows.

![vp-creds migrate credentials](https://user-images.githubusercontent.com/1123119/35416219-93e0fbf0-01e5-11e8-9261-c72964c3c9cb.jpg)

### Copy
**Headline**
> Migrate credentials

**SVG**
[almost-there.svg](https://cldup.com/xmouy_FNKy.svg) (needs to be added to the Calypso `images/illustrations/` directory)

**Copy**
> You've already configured VaultPress correctly, so we're ready to migrate your credentials over to Jetpack with just one click. Are you ready to switch to our faster, more powerful system? Let's go!

**Button**
> Migrate your credentials

**Note** (this should reuses similar styles if possible maybe from the login or someplace)
> Note: Moving to Jetpack backups and security is final, and the VaultPress backups previously generated will not be migrated to the new system. We will retain the data in case you need to restore to a backup made before you switched.

### Implementation notes
* Upon clicking `Migrate your credentials` the user is direct to the "We're backing up your site!" view
* There is a back button here. It should just go back to the previous view.

## 3b. Add your credentials
This will show for _users with Jetpack plan with or without Vaultpress without credentials_.

![jp-free approve credentials](https://user-images.githubusercontent.com/1123119/35416606-f424a9c0-01e6-11e8-8009-ea4be465bde1.jpg)

### Copy

**Headline**
> Add your credentials

**SVG**
[security.svg](https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/security.svg)

**Copy**
> To switch you over to Jetpack backups and security we need you to add your site credentials. This gives WordPress.com access to your site to perform automatic actions on your server -- like backups. It also allows us to restore your site and manually access it in case of an emergency.

**Button**
> Add your credentials

## Implementation details
* Clicking `Add your credentials` opens the Credentials form
* There is a back button here. It should just go back to the previous view.

## 4. Credentials form
This form will use the credentials validation/success notices already in place so I won't show them here, but here's the latest frankenmockup:

![jp-paid server credentials](https://user-images.githubusercontent.com/1123119/35417045-d8e81f14-01e8-11e8-8a29-8d23c2715b4d.jpg)

## 5. Success message
If everything goes smoothly with credentials, this is the message that will appear. Huzzah! If not, hopefully the errors were caught before now on the credentials form view and worked out with a Happiness Engineer if necessary.

![jp-paid approved credentials](https://user-images.githubusercontent.com/1123119/35417127-46e95ad2-01e9-11e8-9b66-7d3c06050c35.jpg)

## Copy
**Headline**
> We're backing up your site!

**SVG**
[thankYou.svg](https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/thankYou.svg)

**Copy**
> Welcome to your Jetpack Premium plan! That sound you're hearing? It's your website doing backflips with excitement!

**Button - folks who just bought a plan**
> Return to your site

**Button - everyone else**
> View your activity

### Implementation notes

* The button copy will change only for folks who just purchased a plan. This is because they might not have much activity yet and will receive notifications/emails later to lead them to the activity log.
* There probably shouldn't be a back button. ¯\\_(ツ)_/¯

**Comment by eliorivero** [comment]
In progress in https://github.com/Automattic/wp-calypso/pull/21802
