### ISSUE TITLE
Store: NUX: Need to allow setting up store with existing domain

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#21852]
I own alletrak.com - it is not hosted anywhere (yet)

As a logged in user, I started the add-a-site flow and selected online-store and then a theme.  In the "Let's give your site an address" view I didn't see anyway to tell our flow that I already had a domain name I wanted to use:

<img width="993" alt="screen shot 2018-01-25 at 4 06 19 pm" src="https://user-images.githubusercontent.com/1595739/35418919-f750c8ba-01e9-11e8-9e64-7f9aa9368bdb.png">

**Comment by alisterscott** [comment]
We now support mapping during sign up:

<img width="986" alt="screen shot 2018-07-25 at 3 41 53 pm" src="https://user-images.githubusercontent.com/128826/43181578-4c3a21da-9021-11e8-9703-8af4ecd10754.png">
