### ISSUE TITLE
JPO: remove form fields after deleting corresponding JP options.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#21868]
Data fetched from the .org site fails to be updated in Calypso when we delete it. 

#### Steps to reproduce
1. follow the instructions on https://github.com/Automattic/jetpack/pull/8426
2. input text in the site title field, click Next Step
3. on your sandbox run `wp option delete blogname `
4. go back to the Site Title step

#### What I expected
Empty Site Title field. 

#### What happened instead
The data in the field is still present.

Note: occurring both forms (Site Title and Business Address steps) and all fields.

**Comment by ockham** [comment]
To reproduce as a user would see this issue (without resorting to `wp option`):

1. In the 'Site Title' step, clear the site description field.
1. Click the 'Next Step' CTA.
1. Click 'Back'.
1. Note that the site description field still has it previous content.

**Comment by tyxla** [comment]
I've tested thoroughly and discovered that this happens only for the site description field.

Upon further investigation, it seems it's an issue in Jetpack. Filing a PR immediately.

**Comment by tyxla** [comment]
Actually, what @ockham described is a separate issue I guess, that we'll need to fix in Calypso.

But the Jetpack one is still valid - we don't allow empty taglines to be saved, and https://github.com/Automattic/jetpack/pull/8760 fixes that.

**Comment by tyxla** [comment]
#22131 addresses the issue @ockham has described. I don't think we need to handle cases when options are manually deleted/updated, at least not for the v1.
