### ISSUE TITLE
JPO: do not render field validation in form placeholder.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#21870]
#### Steps to reproduce
1. access JPO from an .org site or JP sandbox `https://YourJetpackSandbox.com/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env=development` to arrive at the first step of the flow
2. whilst the data is being fetched, the form validation displays its `required` version, which is corrected after the data has been fetched.

#### What I expected
See a placeholder for the form.

#### What happened instead

We see redundant (= not updated) validation information.
![screen shot 2018-01-26 at 16 12 08](https://user-images.githubusercontent.com/13561163/35449041-cb3e045c-02b3-11e8-9fae-0a0c1a5a169c.png)

![screen shot 2018-01-26 at 16 12 21](https://user-images.githubusercontent.com/13561163/35449037-ca690810-02b3-11e8-9a1f-f02b22bf9074.png)

**Comment by tyxla** [comment]
Additional thing here: we should probably fix the wording of the validation:
* **Required field** on error should be changed to something like "Please input your site title"
* **Required field** on success should be changed to something like "You're all set"

**Comment by joanrho** [comment]
Just chatted with Marin about this and we've decided on:

- **Required field** on error should be "Please enter a site title" (no icons) with a red border color on the field.
- **Required field** on success should be removed altogether with a green border color on the field.

**Comment by AnnaMag** [comment]
Thanks @joanrho and @tyxla. Will wrangle the changes 👍

**Comment by ockham** [comment]
Fixed by #22321, #22322, and #22336. Making the same kind of changes to the Business Address step in #22339.
