### ISSUE TITLE
Remove redundant plan purchasing

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#21880]
> Got email saying the Professional subscription is included with my Pressable plan. The problem is that I got this right after I purchased it myself. If it's a Pressable flow, I shouldn't even see the upgrade tables?

At the very least, we shouldn't let you repurchase a plan. At best, we should show you already have it.

Reported by @keoshi on p9rlnk-3m-p2

**Comment by keoshi** [comment]
This needs resting to make sure the current flow still shows this flaw.
