### ISSUE TITLE
Search: Business plan sites that are not atomic not working

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#21892]
Business plan sites that have not been moved to atomic sites (no plugins installed) are not working correctly because we don't have all JP Search code synced to wp.com and don't have it hooked up to get turned on.

Haven't tested yet how badly broken it feels.

**Comment by iamgabrielma** [comment]
Adding 1071668-zen here so we can reach out when this is live. Context: A customer which site cannot become Atomic due to the size of the SQL dump (1.47gb) but would like to have this feature on their Business classic site.

**Comment by gibrown** [comment]
Shipped: https://en.blog.wordpress.com/2018/08/31/new-in-the-wordpress-com-business-plan-jetpack-search/
