### ISSUE TITLE
Jetpack: clicking update in the site switcher closes the sidebar and no feedback is shown

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2189]
To test you wil need:

* A WordPress.com account that has both a WordPress.com blog and a Jetpack blog setup on it
* The Jetpack blog must have pending updates
* Access to the staging server<br><sup>(this problem currently only happens in staging, in production, you cannot update from the sidebar directly yet)</sup>

Steps to reproduce:

1. Go to https://wordpress.com/stats/ My Sites and switch to any WordPress.com blog
1. Click the "Switch Site" link at the top of the left sidebar
1. Find a Jetpack blog with pending updates in the list but do not completely switch to that blog yet
1. Click the orange site update indicator
1. Click the update link that appears

Result: the sidebar shuts down and I am taken back to the site I was on before and there are no updates visible regarding the update action I just took. The problem only happens if you click update from within the site switcher—it works normally if you switch sites first and then click the update link.

Video: https://cloudup.com/cSEvJsXZtHB
<sup>Tested using Firefox 43.0.2 on Mac OS X 10.10.5</sup>

**Comment by beaulebens** [comment]
Note this is an incomplete/unlaunched feature, which is only available to Automatticians currently, so other users will not see this.

**Comment by designsimply** [comment]
Closing because the feature has launched and I cannot reproduce the problem after re-testing in production.
