### ISSUE TITLE
Jetpack: the smiley that appears after an update is complete looks strange on hover

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2190]
To test you wil need:

* Jetpack blog with a pending core update (that hasn't previously been updated to the latest version)
* Access to the staging server<br><sup>(this problem currently only happens in staging, in production, you cannot update from the sidebar directly yet)</sup>

Steps to reproduce:

1. Go to https://wordpress.com/ My Sites and switch to a Jetpack blog with pending updates
1. Click the orange site update indicator
1. Click the update link that appears
1. After the update is complete, check to see if the smiley looks normal on hover

Result: the update works and a smiley appear, but the smiley looks a bit odd when you hover the mouse near it:

![screen shot 2016-01-06 at wed jan 6 11 05 25 pm](https://cloud.githubusercontent.com/assets/1119271/12162430/ff35e128-b4cf-11e5-946b-9fdee6417bff.png)

**Comment by beaulebens** [comment]
Note that this feature (core updates) is not enabled for all users either, so most folks will not see this yet.

**Comment by hoverduck** [comment]
28Apr16 Bug Scrub

Closing.  Looks like the smiley icon has been replaced with a green check (and it looks the same on hover as not).

![screen shot 2016-04-28 at 4 58 22 pm](https://cloud.githubusercontent.com/assets/7233112/14901377/eef72484-0d62-11e6-9a4f-0452240b3076.png)
