### ISSUE TITLE
Jetpack: it takes too many steps to update core, themes, and plugins and reappearing update indicator is confusing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2191]
To test you wil need:
- Jetpack blog with pending updates for core, themes, and plugins

Steps to reproduce:
1. Start at https://wpcalypso.wordpress.com/ 
2. Go to My Sites and switch to a Jetpack blog with pending updates
3. Click the orange site update indicator
4. Click the update link that appears
5. Note that after the update is complete, the orange update indicator has not gone away
6. Click the orange site update indicator again
7. Click the update link again
8. Note that it takes you to to wp-admin
9. Complete all of the theme update in wp-admin
10. Go back to https://wpcalypso.wordpress.com/ > My Sites for your Jetpack blog
11. Click the orange site update indicator again
12. Click the update link again
13. Complete your plugin updates in WordPress.com

Result: it takes too many steps to update and it's confusing that the orange update indicator reappears several times if there are pending updates in more than one area (core, themes, plugins).

![screen shot 2016-01-06 at wed jan 6 11 19 44 pm](https://cloud.githubusercontent.com/assets/1119271/12162187/4d6d93bc-b4cc-11e5-8764-080d8ac9f987.png)

Video: https://cloudup.com/c8uiovpyryX
<sup>Tested on a site running WordPress 4.3 and Jetpack 3.6.1 (updated to 4.4 and 3.8.1) hosted at Linode using Chrome 47.0.2526.106 on Mac OS X 10.10.5</sup>

Notes from @apeatling 

> When I selected the site [after updating], I saw another identical indicator, I thought it was a bug and it hadn't registered my update.
> 
> I guess though it actually means I have other things to update after the WordPress update was completed. I think there needs to be some visual difference here to separate the two.
> 
> The message is also not clear making me think that part of the "updates available" could mean the WordPress update still and the previous core update didn't work.
> 
> I think it's super important to have a clarity around the update process, there should be no room for being vague since it's a sensitive situation when you're updating something. I would love to see more clarity and feel more reassured after performing the updates.

**Comment by lancewillett** [comment]
These improvements would be nice-to-have but isn't really a "bug" per se.
