### ISSUE TITLE
Social Signup: Existing users trying to log in using Google can accidentally create a new WordPress.com account

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#21921]
On the log in screen ([wordpress.com/log-in](http://wordpress.com/login/)), users can choose to "Continue with Google" instead of entering their email address.

If you choose Google, but use a Google account that is not already tied to a WordPress.com account, we will create a new empty account for you and log you in to it, completely transparently, and treat you as a new WordPress.com user.

This can be confusing if you were expecting to be logged in to an existing WordPress.com account. 

One potential solution for this confusion in the log in flow is to add an extra step before creating the account, to confirm that this is the desired result. We can probably leave this as-in in the sign up flow.

Reported by @rachelmcr

**Comment by alisterscott** [comment]
Thanks for raising this issue

I also noted in testing visiting wordpress.com/log-in and 'continue with google' which created a new account I was redirected into the sign up for a new site flow which I wasn't expecting, only if I was at wordpress.com/start

**Comment by kraftbj** [comment]
+1 We're seeing this issue in Jetpack where folks with a Jetpack site are hitting the login screen when going from wp-admin->WordPress.com and end up spinning up a new account instead of getting to Calypso features.

**Comment by GaryBairead** [comment]
This continues to be a contributing factor to a significant number of [threads]( https://en.forums.wordpress.com/topic-tag/other-user) in the support forums.

Examples:

https://en.forums.wordpress.com/topic/duplicate-account-when-login-with-google/

https://en.forums.wordpress.com/topic/log-in-problems-24/

https://en.forums.wordpress.com/topic/email-login-issue/

https://en.forums.wordpress.com/topic/new-wp-account-using-gmail-e-mail-address/

If a user attempts to login with a Google account that isn't already to WordPress.com account, the normal expectation would be that they'd be notified and given the option to either a) try logging-in with a different Google account or b) create a new WP.com account.

**Comment by supernovia** [comment]
Heyo. We haven't really been noting these because it's not so much a "bug" as source of confusion for our users, but I just wanted to note we're still seeing confused people literally _nearly every day_ in our forums. I'm worried that as we add more social options, we'll see more lost users and duplicate accounts.
https://en.forums.wordpress.com/topic/my-current-plan/
https://en.forums.wordpress.com/topic/logging-on-to-my-site-problem/


One idea that might work: when they try to log in with a social login, just ask if they already have an account with us. Prompt them to log into that. And if possible, we could then connect that to whatever social login they want to use.

**Comment by supernovia** [comment]
I haven't personally been tagging these as often these days, but if it's helpful, here's one tag we've been using to track this issue where folks are logged in with the wrong account (usually one they just created with an outside sign-on). It's very, very common.

https://wordpress.com/forums/topic-tag/other-user/

**Comment by supernovia** [comment]
I figure I'll start noting the obvious cases too so this doesn't go stale again.
https://wordpress.com/forums/topic/dashboard-355/

When people choose to log in with Google, can we ask them if they already have an account they would like to connect?

**Comment by supernovia** [comment]
We still see this regularly.

**Comment by noahtallen** [comment]
Hey @supernovia thanks for reporting this and triaging it so regularly! I'm sure it's still an issue.

> One potential solution for this confusion in the log in flow is to add an extra step before creating the account, to confirm that this is the desired result. We can probably leave this as-in in the sign up flow.

I'm going to see if we can dredge up some designs for this.

**Comment by noahtallen** [comment]
Our current thought is to simply show an error message if you are trying to login with google, but no account exists. This would only affect the login flow, not the account creation flow. Then you would have a chance to log in with the correct account, and if they want to create an account, they can use the 'create account' button
