### ISSUE TITLE
how to enable oauth feature in browser? 

### ISSUE THREAD

**Issue by videni** [Automattic/wp-calypso#21920]
I'd like to use oauth to login , I did the following steps.

1. create an application, got the the auth client id. 

2. set the oauth_client_id to `config/_shared.json`

3. start calypso ,   started to authorize successfully

But I got an error when I access `http://calypso.localhost:3000/` 

> Failed to load https://public-api.wordpress.com/rest/v1.1/me?meta=flags: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://calypso.localhost:3000' is therefore not allowed access. The response had HTTP status code 405.

I know the reson is the browser set the origin header to `http://calypso.localhost:3000/`, but `https://public-api.wordpress.com` does not return `Access-Control-Allow-Origin: *`. 

What is the correct way to use calypso oauth function in brower please?

**Comment by designsimply** [comment]
As a starting point, I tested with a Google account using the following steps and it worked in my test:

1. Setup a Calypso server locally and start the server.
1. Go to http://calypso.localhost:3000/
1. Click the "Log In to WordPress.com" button.
1. Enter an email address for a Google account and click the "Continue with Google" button.
1. Enter login credentials for Google in the prompt that appears.

Result: the login works normally and I see the "Welcome to WP Calypso!" screen.

I see that you mentioned changing `oauth_client_id` in `config/_shared.json` but I am not very familiar with that part of the code, may I ask why you did that?

May I ask what service you are trying to use to log in? 

May I ask if you are able to log in to https://wordpress.com/ using OAuth successfully?

**Comment by videni** [comment]
@designsimply, thank for your help. Can you try create an application  use this link ,  https://developer.wordpress.com/apps/, then use that client id to authorize as the steps I described above. What I do is to use WordPress account to login my local calypso.

**Comment by designsimply** [comment]
@videni, I checked in with a few people working on the project, and I found that while it is possible to create an app, Calypso isn't built to support adding your own OAuth flow as you're trying to do. Please consider logging in with your Google account if you'd like to use OAuth to log in—and thank you for considering making contributions to Calypso!

**Comment by stephanethomas** [comment]
@videni: what are you trying to achieve exactly? Most WordPress.com app developers implement the OAuth flow described [in the documentation](https://developer.wordpress.com/docs/oauth2/) to authenticate WordPress.com users, and get access to certain users' resources. Consider the following example - VaultPress being a WordPress.com app:

1. Open the [`VaultPress Home` page](https://vaultpress.com/) in an incognito tab
2. Click the `Sign In` button in the upper right corner
3. Notice that you are redirected to the [`WordPress.com Login` page](https://wordpress.com/log-in?client_id=930&redirect_to=...)
4. Submit credentials of a WordPress.com account
5. Notice that you are redirected to the  [`WordPress.com Authorize` page](https://public-api.wordpress.com/oauth2/authorize?client_id=930...)
6. Click the `Approve` button
7. Notice that you are redirected to the  [`VaultPress Dashboard` page](https://dashboard.vaultpress.com/)

**Comment by videni** [comment]
@designsimply, stephanethomas , thanks a lot, I am clear now  , I try to use OAuth2 password mode to  authencate, this mode doesn't work in browser.
