### ISSUE TITLE
Jetpack Onboarding: Handle timeouts in WooCommerce installation

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#21929]
Right now, when issuing a request to install and activate WooCommerce, it might fail in some environments (for example Pressable):

```
"error":"http_request_failed",
"message":"cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received"
```

Obviously, before triggering the install, we need to increase the cURL limit, by increasing `CURLOPT_TIMEOUT` which currently defaults to 5 seconds in WP.

**Comment by tyxla** [comment]
It seems we'll be able to manage this in the data layer of Calypso - when we encounter these types of errors we can retry a couple of more times to allow the installation to actually complete. Handling it in Calypso might be the best way to handle it because in some installations changing the cURL options is not allowed, and will still fail.

**Comment by ockham** [comment]
Relevant: https://github.com/Automattic/wp-calypso/blob/f8cc15da5aeb38ca42eb626bb2a874846de14aaa/client/state/data-layer/wpcom-http/pipeline/retry-on-failure/README.md#usage

**Comment by ockham** [comment]
Hmm, the weird thing is, I only see one network request being made, tho it seems like there should be at least 3 attempts by default?

**Comment by tyxla** [comment]
I can see you've discussed it with Dennis already, but I agree it makes sense for `POST` requests. Implementing in the `onError` handler sounds reasonable.
