### ISSUE TITLE
Comments: ideal moderation flow to edit comments inline on a site without 2 or 3 clicks into Calypso

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#21931]
#### Steps to reproduce
1. Starting at your website front-end, logged in as admin or editor
2. View your comments on a post
3. Click "Edit" link

#### What happened

The new flow for comment moderation in in Calypso is a bit clunky. It adds an extra step, which can suck up time if you're a site owner that needs to moderate a lot of comments.

Previously, if you are moderating a comment on your site (for example, our Editorial team using the Daily Post blog) and click on "Edit," you are taken to wp-admin where the hover menu allows you to delete, modify, reply, etc.

In Calypso, when you click the edit link, you're taken to this screen.

<img width="955" alt="can i actually edit-" src="https://user-images.githubusercontent.com/66797/35524913-414b6fd0-04e0-11e8-8ee8-19fd5a1b5f51.png">

The only two options are Save and Cancel, but the intention here is to edit. This is really confusing. Eventually you can figure out that if you hit Cancel, you get to see additional options.

Now, if you click Cancel (again, here not what you would expect to do here, given that you clicked on "Edit" to get here.) You see extra options:

<img width="950" alt="step three- trash" src="https://user-images.githubusercontent.com/66797/35524919-46c9b67e-04e0-11e8-8341-a20d5ff8d154.png">

In this new flow, it takes three clicks to delete a comment, if you get past the confusion of "Cancel/Save." Before it only took two.

#### What I expected to happen instead

Ideally, any moderation should be able to edit comments inline on a site, where you get the option to Edit, then Modify, Trash, Spam, etc, without having to bounce to a different screen.

Even moving the addition options to the "Save/Cancel" screen would be a vast improvement.

#### Context / Source
Source is an Automattic editor @kristastevens, and tagged: #journey #narrative #context #perspective #reallife #dogfooding #flowsharing #painpoint

**Comment by gwwar** [comment]
@lancewillett So I'm a little confused here, when you click on edit for wp-admin you are similarly taken to an edit screen like so. Are you asking for a "Move to Trash" action here next to update?

<img width="905" alt="screen shot 2018-01-29 at 10 46 06 am" src="https://user-images.githubusercontent.com/1270189/35528100-a983aefe-04e1-11e8-92fb-81ef7edeb140.png">

**Comment by gwwar** [comment]
I also wonder how difficult it'd be to get moderation actions next to comments in core?

**Comment by gwwar** [comment]
Oh one option is to not show the page in a special edit mode, if folks are really looking to moderate when they click "edit" from the front end

**Comment by lancewillett** [comment]
Right: clicking "Edit" could mean "I want to moderate this one."

**Comment by gwwar** [comment]
@rodrigoi do you mind spinning up a wpcom patch and modifying the open Jetpack PR for the frontlinks to not open in edit mode?

**Comment by rodrigoi** [comment]
Quick fixes ready for review: 

WordPress.com: D9708-code
Jetpack: https://github.com/Automattic/jetpack/pull/8648

In case the Jetpack diff does not make it into `5.8-beta`, we can still fix this on Calypso's side until it lands.

**Comment by gwwar** [comment]
Thanks for the quick update! I'll take these for a spin

**Comment by rodrigoi** [comment]
@lancewillett WordPress.com fix has been deployed and Jetpack will ship this fix on `5.8` (beta out today) 😉

**Comment by lancewillett** [comment]
Thanks for the quick turnaround — props @kristastevens for the "flow sharing" that got it started.

**Comment by kristastevens** [comment]
Props to all of you for taking swift action!
