### ISSUE TITLE
Store: Items with a price of 0.00 show a crossed out discount line on order screen

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#21938]
When adding a product with a cost of `0.00` to an order, a discount line is shown below the price:

<img width="737" alt="screen shot 2018-01-29 at 10 33 44 am" src="https://user-images.githubusercontent.com/689165/35527923-1f1ea408-04e1-11e8-8217-a8a38e1fb985.png">

**Comment by ryelle** [comment]
Is this happening on master/wpcalypso? It should have been fixed with #21746, and I can't replicate it with my own $0 product. Or maybe you have a promotion tied to this product?

**Comment by justinshreve** [comment]
It's happening for me in staging on both justin-devstore-at.blog (3.3) and justin-devstore-at-1.blog (3.2.6).

**Comment by justinshreve** [comment]
And no promotions except for coupons (which are not applied on the order).

**Comment by ryelle** [comment]
@justinshreve Looks like this is due to not setting a price on the product when it's created. Trying to save an order with a product without a price causes an error, even though it _appears_ to be a free product. Maybe the fix should be to use a default price of `0` when creating products?

**Comment by justinshreve** [comment]
@ryelle Good catch. I added a tiny PR for that here: https://github.com/Automattic/wp-calypso/pull/22063. 

Do you think we should do anything else for the products that already exist? Or just let people know (if anyone runs into this since it's probably an edgecase) that they can go in and edit their products?
