### ISSUE TITLE
Store: Updating dimension/weight units can cause confusion setting up packages

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#21940]
If you update weight or dimension units, and then go to create a package, the units are shown incorrectly. This could lead to confusion and incorrect configuration during the NUX flow when configuring shipping settings.

Here is a video to show what I mean: https://cloudup.com/caQHSiqjCaZ. 

Notice how I set the units to pounds and inches, and the dialog shows inches for one input, but grams for the others, and millimeters in the label description. Which should I enter?

All these fields should show the current unit selection, since they get saved at the same time.

cc @budzanowski @DanReyLop

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021.
