### ISSUE TITLE
Jetpack Onboarding: Handle cases when contact page is missing.

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#21955]
As described thoroughly in https://github.com/Automattic/jetpack/pull/8638#discussion_r164310707

**Comment by tyxla** [comment]
This would a nice improvement over what we have in the JPO plugin, but it's not a huge deal and is quite an edge case. Let's leave it for another iteration.

**Comment by AnnaMag** [comment]
FWIW, I'm a fan of handling edge cases properly. Let's keep this one on the to-do list please.

**Comment by tyxla** [comment]
@AnnaMag sounds great! 

Please, note that we're keeping it on the future iterations column because:
* It'd require to be shipped with a new Jetpack release
* It's an enhancement, but not a critical one.
* It's not featured in the original plugin, so it's not essential for the v1.

This doesn't mean you can't work on it now if you wish 😉

**Comment by tyxla** [comment]
The Jetpack Onboarding feature was completely removed in #38000, so this one can be closed as well.
