### ISSUE TITLE
Jetpack Onboarding: Install Storefront Theme during WooCommerce Installation Step

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#21957]
As per discussion in https://github.com/Automattic/jetpack/pull/8643. Context: see screenshot

![](https://cldup.com/u_sYDQexf5.png)

> If we look at each notice individually (instead of merely suppressing them), the last one could be fixed by actually installing the Storefront theme as part of the JPO WooCommerce installation step...

...which might make sense to get users wanting to sell stuff started more easily.

**Comment by tyxla** [comment]
This is a nice enhancement, but:

* It'd require to be shipped with a new Jetpack release.
* It's an enhancement, but not a critical one.
* It's not featured in the original plugin, so it's not essential for the v1, where we only mirror the existing JPO plugin functionality.

So even though it's great to have it in the first version, let's leave it for the next iteration.

**Comment by tyxla** [comment]
The Jetpack Onboarding feature was completely removed in #38000, so this one can be closed as well.
