### ISSUE TITLE
Activity Log: link directly to credentials flow when missing/prompted

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#21961]
### Proposal

When the site credentials are missing and we're prompting the user to fill them out, we're linking them to the `Settings > Security` tab and it's easy to lose context and feel confused.

Instead, in these cases, we should link directly to the stand alone credentials flow @rcoll is building: https://github.com/Automattic/wp-calypso/issues/18832

### Entry points

- AL view:

![image](https://user-images.githubusercontent.com/390760/35562530-9092b5c8-05ab-11e8-93e3-89d917a070aa.png)

- Intro emails (cc @bubel):

![image](https://user-images.githubusercontent.com/390760/35562817-82f7b9b2-05ac-11e8-9b5b-5f2e32399cfd.png)

- Notifications? Does this apply here?

### Related issues
- Closing https://github.com/Automattic/wp-calypso/issues/21610 in favor of this one.

**Comment by eliorivero** [comment]
Notice link updated in https://github.com/Automattic/wp-calypso/pull/22007

**Comment by keoshi** [comment]
@bubel did you see this request? Is the email link something you can change easily?

**Comment by eliorivero** [comment]
For the email link change, I've started D10015-code. Unfortunately I can only test the missing credentials email (and it works fine), for some reason I can't send the email drip campaign ones. I assigned @bubel as reviewer of the diff, maybe he can test it.

**Comment by bubel** [comment]
Just chatted with @eliorivero about the patch. Everything tests well and LGTM. Green light given.

**Comment by eliorivero** [comment]
I've committed D10015-code so will close this.

**Comment by keoshi** [comment]
Thank you both!
