### ISSUE TITLE
Reader: When The Site Is Deleted, It Still Shows In The Count Of Your Followed Sites

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#21978]
The issue was reported by a user that if you follow the site and then it gets deleted, it will still show in the count of your followed sites. I was able to reproduce the issue with my own test site
#### Steps to reproduce
1. Create a site 
2. Log in into another account and follow that site. Check how many sites you are following and note the account. The easiest thing to do in this case is to follow just one site.
3. Go back to the account from which you created the site and delete the site.
4. Return to the test account from which you followed the site and check the list of followed sites.

#### What I expected

To see no followed sites (if testing by following just one site)

#### What happened instead

The count was showing one site and no actual sites listed: https://cloudup.com/cdSzXAuenFU

It seems that the related issue was opened here: https://github.com/Automattic/wp-calypso/issues/5840

**Comment by blowery** [comment]
Thanks for the report @katinthehatsite! I think #5840 covers it, so I'm going to close this as a dupe. If you think this should remain open because it's distinctly different, feel free to reopen it.
