### ISSUE TITLE
Reader: Getting "Load More Posts" every time a new post appears in my stream

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#2198]
Every time I have a new post in my stream, clicking the "load" button puts this "Load More Posts" between the old and new posts:

<img width="755" alt="screen shot 2016-01-07 at 2 11 13 pm" src="https://cloud.githubusercontent.com/assets/2846578/12180110/ade08fb6-b548-11e5-8488-e9295939375a.png">

There aren't any other new posts, though — just the ones I've seen and the new one(s), so clicking it doesn't do anything.

**Comment by blowery** [comment]
Confirmed, digging into this. Likely came from #2159

**Comment by shaunandrews** [comment]
I've been seeing this, too. (Whew, I thought I was going nuts all day.)
