### ISSUE TITLE
Menus: allow easy reverting of changes

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#22]
Report:

> The only way I’ve found to revert my unsaved changes when editing a menu is to refresh the whole page. It would be great if there was an easier way, especially given how easy we make making serious of changes. Probably a “Revert” button or “Undo”?

Example user flow:

1. Make an edit to menu, but don't save it.
2. Instead of refreshing the page — or clicking "Menus" link again in the sidebar (which prompts for unsaved changes but doesn't refresh the page) — you could just click "Undo" and have the menu go back to its original state.

Suggestion for the "Menus" item in sidebar: since it currently links to `/menus/[site]` it won't force a refresh on editing a menu. It might be nice to use a unique URL for menu editing like `/menus/[site]/edit/[menu_id]` so that clicking the sidebar link forces a page refresh. ([Video showing the lack of refresh](https://cloud.githubusercontent.com/assets/66797/11217996/57ca4e06-8d10-11e5-9c4d-33493a150b5f.gif).)

Needs a design mockup for the Undo action.

**Comment by dmsnell** [comment]
Looks like a great place to take advantage of some of the easy undo workflows with Redux
