### ISSUE TITLE
Jetpack Plans: SEO Tools mentioned twice on list of features being activated

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#22018]
#### Steps to reproduce
1. Start from a Jetpack site using a free plan
2. Go to https://wordpress.com/plans
3. Purchase a Professional plan for your site.
4. On the set up page (`https://wordpress.com/checkout/thank-you/yoursite`), SEO Tools is mentioned twice:

![screenshot 2018-01-31 at 21 32 11](https://user-images.githubusercontent.com/426388/35646140-8826d490-06ce-11e8-9bce-0abbe46ab6d8.png)

**Comment by beaulebens** [comment]
This was fixed in #22108
