### ISSUE TITLE
Jetpack Onboarding: Make site title step more welcoming

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#22048]
We will soon be sending customers via hosting partnerships to our new WordPress.com-based Jetpack Onboarding flow. 

Currently: the first step of the flow is rather abrupt, launching straight into picking a site title etc. 

Let's explore a more friendly introductory first step, welcome the customer to WordPress, set their expectations a little bit, show an illustration, and let them click to start setting things up. 

This 'splash' screen will be the first step of the flow in calypso. We can also test and launch JPO without this, it's simply nice to have.

![jpo welcome step 1](https://user-images.githubusercontent.com/204742/36286912-118cbc44-126f-11e8-82be-12a0a8777b26.png)

**Comment by johnHackworth** [comment]
We have been assuming that this "introductory" step will happen on the hosting side. At the end of the day, it's what happens right now in wp-admin. I think it's a good idea to have this screen for/if we want to open this to non-hosting users, but we probably need to touch base with the partners that are going to use jpo to see if we need to add an intro screen or if they can jump directly to step 1

**Comment by rickybanister** [comment]
In the current wp-admin JPO experience the first step of our UI asks if the user wants to start setting up yes/no. In the new flow we don't have the same kind of 'first step'. 

I'm not proposing that we overlap with hosts, but that we make sure we have a friendly first step like we had before (perhaps even friendlier).

**Comment by tyxla** [comment]
Sounds good to me, but I kind of agree with @johnHackworth that we'd need to sync this with each partner. Could be a good idea to personalize it for each partner, like we do for Jetpack Connect in the auth step.

In any case, we could use some designs for it.

**Comment by rickybanister** [comment]
Note: it should say 'Terms of Service' instead of terms and conditions.

**Comment by rickybanister** [comment]
(I added a design mockup to the issue)

**Comment by joanrho** [comment]
@rickybanister Just updated the design mockup with "Terms of Service" instead of terms and conditions.

**Comment by tyxla** [comment]
#22579 addresses this one, it could use some eyes @rickybanister @joanrho, thanks!
