### ISSUE TITLE
Republicize: scheduling a post to be publicized returns an error

### ISSUE THREAD

**Issue by TassyWassy** [Automattic/wp-calypso#22043]
Sharing to social media cannot be scheduled. Sharing can be done when sharing immediately.

#### Steps to reproduce
1. Go to the post page: https://wordpress.com/posts/
2. Select the three dots on a post and select share
3. Select any or all connected social media
4. Select the calendar icon and set a future date
5. Select the to 'schedule post' button

#### What I expected
The post should be schedule to be posted the social media options selected and show in the scheduled tab

#### What happened instead
An error message is produced “Scheduling share failed. Please don’t be mad.”
Tried with just one social media selected (error is given with each), tried with or without a comment added. Social media has been disconnected and reconnected and the error still occurs.

#### Screenshot / Video
<img width="750" alt="screen shot 2018-02-01 at 8 31 05 am" src="https://user-images.githubusercontent.com/6570085/35681144-74fe1ba6-072a-11e8-8f38-5f81ea2203e4.png">

#### Context / Source
 #user-report

**Comment by arunsathiya** [comment]
I just tested this, and can confirm this is happening with me too.

**Comment by cena** [comment]
Reported in 934917-zen

**Comment by jenhooks** [comment]
The user in 934917-zen that Cena cited above is also not able to schedule posts via their wp-admin -- I'm not sure if that is relevant information?

**Comment by sandymcfadden** [comment]
When I try to test scheduling a publicize message for a post I end up with this in my browser console which will hopefully be helpful in tracking it down.
![screen shot 2018-02-01 at 1 48 13 pm](https://user-images.githubusercontent.com/1326294/35694181-d3357dfa-0756-11e8-9286-68a5c11c1025.png)

**Comment by csonnek** [comment]
Reported in 919734-zen

**Comment by scosgro** [comment]
Reported in HappyChat with user researchdigestblog. (They also requested to be notified when this is fixed, if possible.)

**Comment by jeherve** [comment]
cc @artpi and @lamosty who previously worked on the Republicize feature.

Previous changes to that feature: #20912, #20921

**Comment by sarahgreenlee** [comment]
Another user reported this here 1686129- HC and wants follow up here 933644-zen

**Comment by lamosty** [comment]
This was fixed yesterday with #22064.
