### ISSUE TITLE
Editor: Tags already added to post show up in suggestions list

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#2205]
None of these first 3 tags (`a & b`, `abc`, `jnylen0-tag1`) should be showing up in the suggestions list, since they are already added to the `TokenField`:

![image](https://cloud.githubusercontent.com/assets/227022/12182315/02c52786-b54d-11e5-8b57-f838cc100615.png)

First reported at https://github.com/Automattic/wp-calypso/pull/2054#issuecomment-168996210.

Needs test case as well.

**Comment by lancewillett** [comment]
Re-testing this today, still occurring but it's not as bad a UX as I would have thought.

<img width="469" alt="screen shot 2016-04-14 at 10 58 25" src="https://cloud.githubusercontent.com/assets/66797/14538282/dcfd5ac0-022f-11e6-81d8-644298415e66.png">

As soon as I start typing the existing tag again in the input field, it is **not** suggested, which would be a much worse experience.

**Comment by jeremeylduvall** [comment]
Closed via #4980.
