### ISSUE TITLE
Signup: Parenthesis in "about" section of signup survey breaks the page

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22054]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/about
2. Under "What will your site be about?" enter any text including a parenthesis: `(` or `)`

#### What I expected

I expected the input to be accepted or sanitized if needed.

#### What happened instead

The entire page went blank with the following console error:

```
vendor.ac69b005900cda7ca7e0.min.js:63 Uncaught SyntaxError: Invalid regular expression: /(/: Unterminated group
    at new RegExp (<anonymous>)
    at signup.008603b1753ce54b0103.min.js:1
    at Array.filter (<anonymous>)
    at t.value (signup.008603b1753ce54b0103.min.js:1)
    at t.value (signup.008603b1753ce54b0103.min.js:1)
    at t.value (signup.008603b1753ce54b0103.min.js:1)
    at s (vendor.ac69b005900cda7ca7e0.min.js:63)
    at beginWork (vendor.ac69b005900cda7ca7e0.min.js:63)
    at r (vendor.ac69b005900cda7ca7e0.min.js:63)
    at a (vendor.ac69b005900cda7ca7e0.min.js:63)
```

#### Browser / OS version

Mac OS 10.13.3 / Chrome 64

#### Screenshot / Video

![screenshot 2018-02-01 17 38 53](https://user-images.githubusercontent.com/8658164/35693911-8e3a3af8-0777-11e8-92bf-e76e34f41b27.png)

#### Context / Source
#manual-testing (I wanted to enter a main topic and then explanatory details in parentheses)

**Comment by designsimply** [comment]
Tested and confirmed that typing a parenthesis "(" into the "What will your site be about?" field on step one of signup results in a blank page with the following console errors:

> SyntaxError: Invalid regular expression: /(/: Unterminated group
> https://wordpress.com/calypso/144.92f84b75c398c6fbffcd.opt.js

> Uncaught SyntaxError: Invalid regular expression: /(/: Unterminated group
> https://wordpress.com/calypso/144.92f84b75c398c6fbffcd.opt.js

![screen shot 2018-04-19 at thu apr 19 12 07 46 pm](https://user-images.githubusercontent.com/1119271/39010004-85943b1c-43ca-11e8-9d0a-192f8aefb4c6.png)
<sup>Seen at https://wordpress.com/start/about using Chrome 65.0.3325.181 on macOS 10.13.3</sup>

Found while #manual-testing a new import feature.

**Comment by alisterscott** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/25795

This was also duplicated in https://github.com/Automattic/wp-calypso/issues/25794
