### ISSUE TITLE
Store: Add WooCommerce Order Status Manager extension support

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/wp-calypso#22074]
While support for WooCommerce extensions had not been implemented yet, @timmyc asked me to log this issue here so here I am.

#### Steps to reproduce
1. On your WP.com Store site, add [WooCommerce Order Status Manager](https://woocommerce.com/products/woocommerce-order-status-manager/) extension. 

2. Create new Custom Order Status (for example "Awaiting Shipment") via **WooCommerce > Settings > Order Statuses > Statuses**:

![](https://cloudup.com/c7A2XLUZqq4+)
Image Link: https://cloudup.com/c7A2XLUZqq4

![](https://cloudup.com/ch9_T0Qpmm9+)
Image Link: https://cloudup.com/ch9_T0Qpmm9

3. Let's imagine we want to change the Order Status of Order 46:

![](https://cloudup.com/c2f8mRY0WlF+)
Image Link: https://cloudup.com/c2f8mRY0WlF

4. Open Order 46, click on **Edit** button and try to update Order Status. You will see that **Awaiting Shipment** doesn't come up as an option:

![](https://cloudup.com/ce9GdPqPyTA+)
Image Link: https://cloudup.com/ce9GdPqPyTA

#### What I expected

I expected **Awaiting Shipment** option be available in the drop-down menu of Order Status field on Order 46. I was hoping to be able to update order status to **Awaiting Shipment** and update order with that status. 

#### What happened instead

1. Instead, I opened that same Order 46 in WP Admin and was able to update Order Status to **Awaiting Shipment**:

![](https://cloudup.com/cBjOK0wwTrW+)
Image Link: https://cloudup.com/cBjOK0wwTrW

2. All Orders View also got updated with **Awaiting Shipment** custom icon as per my settings:

![](https://cloudup.com/carYuy9YYLu+)
Image Link: https://cloudup.com/carYuy9YYLu

3. If you go back to Calypso, you'll see the order status labels disappeared on All Orders View:

![](https://cloudup.com/cJek4-sH58o+)
Image Link: https://cloudup.com/cJek4-sH58o

4. If you now open Order 46, you'll see that the status disappeared there as well:

![](https://cloudup.com/cxNGy4Meq2O+)
Image Link: https://cloudup.com/cxNGy4Meq2O

#### Context / Source

It will be nice to have consistency between Calypso and WP Admin and be able to see Custom Order Statuses in Calypso as well as be able to update order status to Custom Order statuses. 

#manual-testing

**Comment by BaldwinJackson** [comment]
Have a look at this code snippet:

 function add_awaiting_shipment_to_order_statuses( $order_statuses ) {     $new_order_statuses = array();     foreach ( $order_statuses as $key => $status ) {         $new_order_statuses[ $key ] = $status;         if ( 'wc-processing' === $key ) {            $new_order_statuses['wc-arrival-shipment'] = 'Shipment Arrival';        }    }     return $new_order_statuses;

I have solved similar issue where the custom order status wasn't showing in the drop down.
**Source:** https://www.cloudways.com/blog/create-woocommerce-custom-order-status
