### ISSUE TITLE
Free Trials: Free trial stays in cart when you navigate away from checkout flow

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#2207]
![image](http://g.recordit.co/jTeWX0foaN.gif)

Steps to reproduce:
1) Add free trial to cart
2) Navigate back to `Add a Domain` (back button or via `My Sites`)
3) Domain suggestions show "free with plan" indicator (the trial is still in your cart)
4) Adding a domain to your cart removes the free trial, and shows the full price of the domain

CC'ing @Tug as this may be something that https://github.com/Automattic/wp-calypso/pull/2157 fixes.

**Comment by scruffian** [comment]
This will be addressed by #2157

**Comment by fabianapsimoes** [comment]
I'll close this since we'll no longer use the cart for Free Trials.
