### ISSUE TITLE
Free Trials: Show free trial upgrade CTA in sidebar cart when purchasing a domain

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#2208]
We currently show this CTA in the popover cart when you are mid-trial and try to purchase a domain:

<img width="361" alt="screen shot 2016-01-07 at 1 23 24 pm" src="https://cloud.githubusercontent.com/assets/3011211/12183158/f80cacf2-b541-11e5-84fa-0de5160f19a5.png">

However, it doesn't show up in the sidebar cart in the same state (and therefore, it's not visible on the checkout page):

<img width="288" alt="screen shot 2016-01-07 at 1 25 06 pm" src="https://cloud.githubusercontent.com/assets/3011211/12183182/1af414a8-b542-11e5-8249-a08d2e84ee1c.png">

We could also conditionally mention Privacy Protection is also free to sweeten the deal.

cc: @mikeshelton1503

**Comment by fabianapsimoes** [comment]
@mikeshelton1503 how does this overlaps with the other nudges for domains + free trials? Should we still do it?

**Comment by mikeshelton1503** [comment]
This won't overlap with any other planned nudges. All of the nudges we're focused on right now are focused on starting a trial not purchasing once you have a trial. Proceed!

**Comment by fabianapsimoes** [comment]
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.
