### ISSUE TITLE
When using autocomplete from Chrome on iOS, it puts the email inside the input, but after pressing continue button - deletes it

### ISSUE THREAD

**Issue by igladun** [Automattic/wp-calypso#22085]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Type first letters of your saved in autocomplete email address to the input field
3. Select your email address in suggestions of autocomplete
4. Press continue button

#### What I expected
I am logged in to Wordpress.com 

#### What happened instead
I am not logged in and my email address is cropped in the input field
#### Browser / OS version
Devices: iPhone8, iPad Mini4
OS: 11.2.2
Browser: Chrome

#### Screenshot / Video
![animated](https://user-images.githubusercontent.com/4245201/35722319-78941cdc-07fe-11e8-8808-ed3e50a886e3.GIF)

#### Context / Source
Also reproducible on other localizations

**Comment by cbauerman** [comment]
Fixed by #23010
