### ISSUE TITLE
Checkout: properly support multiple domain carts + ccTLDs

### ISSUE THREAD

**Issue by hewsut** [Automattic/wp-calypso#22097]
#### Steps to reproduce (untested)

Based on purchase timestamp logs, repro presumably should be:

Add both a .com domain and an .fr domain and attempt checkout.

#### Context / Source

We knew when we started launching ccTLDs--which have an extra form to collect special registrant details--we had not properly accounted for multiple domain carts. We considered it edgecase enough to proceed.

And that was fine-ish (we're six or seven months in now), but it's time to make it right. We've seen a couple real customer checkout explosions the last few weeks.

**Comment by hewsut** [comment]
TODO: ensure everything bills correctly too when fixed. In the observed explosions, customer was only being charged for one. That maybe a side-effect of the partial fail though.

**Comment by deBhal** [comment]
I was looking at the .fr thing, and I was able to reproduce it for a while, and now I can’t :confused:

I was getting responses from the product endpoint (https://public-api.wordpress.com/rest/v1.1/products) that had almost all of the domains with `is_domain_registration` set to false. That meant `cartItems.getDomainRegistrations()` ignored them (here https://github.com/Automattic/wp-calypso/blob/master/client/lib/cart-values/cart-items.js#L364), and then `cartItems.getTlds()` which in turn meant that we [skip that step in the domain details form](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/domain-details-form.jsx#L276), and send the query off without any extra.

I don't know where those values came from, but if we're talking about a caching issue, that would explain why we see nothing for months and the 3 in 3 days.

**Comment by hewsut** [comment]
>  I was able to reproduce it for a while

How?  Simply adding .com/.fr to cart?

**Comment by deBhal** [comment]
Actually .UK, and with the values I was seeing from the endpoint you wouldn't need the .com in your cart, and I got the same result in calypso and curl. The uk values are:
```
{
  "product_id": 326,
  "product_name": ".uk Domain Registration",
  "product_slug": "dotuk_domain",
  "description": "",
  "cost": "5",
  "available": true,
  "is_domain_registration": false,
  "cost_display": "350 ₹"
}
{
  "product_id": 327,
  "product_name": ".co.uk Domain Registration",
  "product_slug": "dotcodotuk_domain",
  "description": "",
  "cost": "5",
  "available": true,
  "is_domain_registration": false,
  "cost_display": "350 ₹"
}
{
  "product_id": 328,
  "product_name": ".me.uk Domain Registration",
  "product_slug": "dotmedotuk_domain",
  "description": "",
  "cost": "5",
  "available": true,
  "is_domain_registration": false,
  "cost_display": "350 ₹"
}
```

That `is_domain_registration: false` means that we won't recognize it as a domain and won't show the field, so we'd skip straight from the general details from to the checkout with null `extra`.

There were actually 287 products with a name that matched "Domain Registration" with `is_domain_registration: false`, All newer ones - `.*.in`, `.design`, `.yoga`, `.design`. The 3 uk domains are the only ones that could lead to the missing extra failure in this issue, but I do wonder if the others might trip up billing.

It's such a weird thing, it just went away mysteriously, and it didn't effect .FR either, so it seems more like a distraction than a lead at this point.

**Comment by hewsut** [comment]
@deBhal dunno, seems bad at a glance.. A domain registration is a domain registration so saying `false` sounds like a problem. Could you post exact repro steps? Either here if relevant to this issue or a new one if you think it's something separate.

**Comment by deBhal** [comment]
I think that's a separate issue, and I couldn't repro :(  Hopefully I did something silly with my sandbox...
