### ISSUE TITLE
Upgrades: General: add unit tests for the list of stored card model

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2209]
Raised by @stephanethomas 

We should [write tests](https://github.com/Automattic/wp-calypso/wiki/Writing-and-Running-Tests#writing-tests) for the [StoredCards](https://github.com/Automattic/wp-calypso/blob/53bde8c3f9c4668e62dbd2c670aaacc2bd820427/client/lib/stored-cards/index.js) model.

**Comment by janm6k** [comment]
Going through old issues, closing ones that does not look like important one.

Please feel free to reopen if applicable.
