### ISSUE TITLE
Billing History: cannot scroll within a receipt using Firefox 33.1 on Nexus 5

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2210]
To test you will need:

* A WordPress.com account with at least one purchase on file
* Nexus 5 device with Firefox33.1+ installed

Steps to reproduce:

1. Go to https://wpcalypso.wordpress.com/ using at least Firefox 33.1 on a Nexus 5
1. Click the account icon in the top toolbar
1. Click "Manage Purchases"
1. Select "Billing History" from the dropdown menu
1. Click "View Receipt" for any purchase
1. Try to scroll

Result: when you open a receipt, the scrollbar is still related to the Billing History in the background and you cannot scroll within the receipt modal

/hat tip @fabianapsimoes for the original report

**Comment by mtias** [comment]
Billing receipts are no longer in a modal.
