### ISSUE TITLE
Comments: In single view, show status labels for spam and trash comments

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#22106]
See https://github.com/Automattic/wp-calypso/issues/19773

Can you guess what status is this comment?

![](https://user-images.githubusercontent.com/2070010/35730903-b3f35934-080b-11e8-9fda-6b432caadc11.png)

It's a trashed.

Users would have a hard time figuring out, because both spam and trash look almost identical to approved.

We do use the "Pending" pill label (which is unnecessary-ish, since pending comments have a yellow background anyway): let's reuse it for spam and trash comments in single view.

**Comment by gwwar** [comment]
cc @drw158
