### ISSUE TITLE
Reader: Search Manage showing empty item in results

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#22115]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage.
2. Search for "en.blog.wordpress.com".
3. Third item in the result is empty.

![screenshot 2018-02-02 16 57 55](https://user-images.githubusercontent.com/4924246/35761160-72cfa9ec-083a-11e8-80c7-119d2cf93406.png)

/cc @gibrown @aaronyan

**Comment by rachelmcr** [comment]
Is it possible the third item was a deleted site? If so, it could be the same as the issue described in https://github.com/Automattic/wp-calypso/issues/5840#issuecomment-335833226.

**Comment by bluefuton** [comment]
Still seeing this one despite recent fixes to remove deleted sites from API results. Let’s check the /read/following/mine endpoint.

**Comment by bluefuton** [comment]
Actually - I think D8375-code has done the trick here. I just had a search for bluefutontest and deleted the first site in the results. It no longer appears.

I can also no longer reproduce the problem with the original example in the issue.

I still thinking "empty" results are still a problem for subscriptions (see https://github.com/Automattic/wp-calypso/issues/19328).
