### ISSUE TITLE
Activity Log: Add “fix” link to Credentials Error item

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22137]
This message needs a CTA that redirects the user to the credentials flow, where they're told what's wrong.

![credentials-error-01](https://user-images.githubusercontent.com/390760/35816781-83df57e0-0a93-11e8-8eaa-80478830f11c.png)

We also need to fix the language, where `Credential Error` should be `Credentials Error`.

### After

![credentials-error-02](https://user-images.githubusercontent.com/390760/35816959-fdd39f84-0a93-11e8-821d-b1047928ea8c.png)

**Comment by keoshi** [comment]
@rcoll cool to assign you this one?

**Comment by designsimply** [comment]
@eliorivero okay to assign you to this one since it is marked as '[Pri] High`?

**Comment by eliorivero** [comment]
Yes @designsimply 👍

**Comment by eliorivero** [comment]
@designsimply this is fixed since https://github.com/Automattic/wp-calypso/pull/22453, that introduced a Get help button in any failed backup event.

<img width="724" alt="captura de pantalla 2018-02-26 a la s 17 04 31" src="https://user-images.githubusercontent.com/1041600/36692669-7dd0068a-1b17-11e8-81df-ea6bfe34c5c3.png">

**Comment by eliorivero** [comment]
That's a good idea @keoshi. There must be an error code specifically for this so I'll check it.

**Comment by eliorivero** [comment]
@keoshi looks like it’s possible to add the button to go the flow to add credentials to the Backup failed event as requested. 
What should the button label be? It should be a primary blue button, right?

**Comment by keoshi** [comment]
@eliorivero thanks for taking a deeper look, appreciate it!

Yes, primary button and let’s go with *Fix Credentials* instead of Settings.
