### ISSUE TITLE
Checkout: prevent user from editing domain details until the stored details are loaded

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2213]
Steps to reproduce:
1. Go to https://wordpress.com/ > My Sites > Domains
2. Click the "Add Domain" button
3. Click the "Add" button next to a suggested domain
4. Watch the page load carefully to see if you can enter data before the stored details have loaded from the server

Result: most form elements have now been disabled except for the country select box, i.e. the user can change its value before domain contact information are loaded

![screen shot 2016-01-07 at thu jan 7 4 52 56 pm](https://cloud.githubusercontent.com/assets/1119271/12183862/b320d35c-b55f-11e5-9d6a-2deeacebbd74.png)

Video: https://cloudup.com/cV-MaIXsiCi
<sup>Tested using Firefox 43.0.2 on Mac OS X 10.10.5, page load slowed 4x so you can see it clearly</sup>

/hat tip @rads and @stephanethomas for the original report

**Comment by klimeryk** [comment]
Thanks to https://github.com/Automattic/wp-calypso/pull/15009, the contact details are prefetched and I can't reproduce this issue anymore.
