### ISSUE TITLE
Bug: Site picker not shown for categories and tags

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#22151]
**Steps to reproduce**: Open [https://wordpress.com/settings/taxonomies/category](https://wordpress.com/settings/taxonomies/category) or [https://wordpress.com/settings/taxonomies/post_tag](https://wordpress.com/settings/taxonomies/post_tag)

**What to expect**: Site picker is shown like shown below.

![image](https://user-images.githubusercontent.com/18581859/35837466-46867d46-0b0c-11e8-9060-2aa1237621a0.png)

**What happens instead**: Site picker is not shown.

![image](https://user-images.githubusercontent.com/18581859/35837663-6fd65cec-0b0d-11e8-9f4f-a8ef1b3d7b85.png)

**Comment by dmsnell** [comment]
Thanks for the report! I proposed a fix in #22571 but I'm not as familiar with this part of the system so it may take some time to pass through review. 👍
