### ISSUE TITLE
Activity Log: showing stats initial dialog on first AL view

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22168]
On the first visit to the AL, we're showing the initial pop-up about Stats.

This might be showing because we're in Stats, but since it's not relevant to this tab can we hide it?

I believe the only flow where this is shown is:

- New WP.com account
- New site
- Visit stats

<img width="1552" alt="screen shot 2018-02-20 at 9 25 02 am" src="https://user-images.githubusercontent.com/390760/36435954-3ef8f8c8-1620-11e8-9c1b-d2249f8d0569.png">

**Comment by eliorivero** [comment]
@keoshi can you outline the steps to reproduce this? I haven't seen this behavior before, even when working with brand new sites.

**Comment by keoshi** [comment]
Edited above with the flow where this is displayed.
