### ISSUE TITLE
Checkout: fix wrong type of product_id for product in shopping cart

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2216]
Raised by @stephanethomas 

We should investigate and fix a problem where the REST API returns a `product_id` as a string instead of an integer when adding a product to the shopping cart. This leads to an `Uncaught TypeError: Cannot read property 'product_name' of undefined` in `cart-item.jsx`. Note we should then remove [any temporary fix (2417-gh-calypso-pre-oss) we introduced in the meantime, i.e.  https://github.com/Automattic/wp-calypso/blob/9b296026b201e9a44e00527b51a03ad67e72bac2/client/lib/cart/store/cart-synchronizer.js#L40-L46

A unit test (r109756-wpcom) was created to pinpoint this issue, to no avail unfortunately. We might want to add another one once we can reproduce this error accurately.

Note I noticed a different behavior between my sandbox and the production environment. One thing that I think was triggering the mentioned error is that currently it is possible to add a domain with an empty `meta` property in the shopping cart on the domain search page - this might be not correctly interpreted by the backend which returns a product with an identifier of the wrong type.

**Comment by janm6k** [comment]
Going through old issues, closing ones that did not have any activity in long time.

Please feel free to reopen if applicable.
