### ISSUE TITLE
Activity Log: errors showing up in the AL despite having correct credentials

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22164]
Despite the credentials card showing a correct configuration:

<img width="794" alt="screen-shot-2018-02-02-at-1-32-08-pm" src="https://user-images.githubusercontent.com/390760/35860600-93aafc70-0b3c-11e8-9055-9b283a0df7c1.png">

The AL is reporting a lot of errors — `System error` and `Credential error` — that seem to a) contradict that information b) indicate something weird happening here.

<img width="1014" alt="screen-shot-2018-02-02-at-1-31-46-pm" src="https://user-images.githubusercontent.com/390760/35860681-d19bc96a-0b3c-11e8-9e1a-4d448c95fd60.png">

Reported at least by @enejb @MichaelArestad and myself.

**Comment by keoshi** [comment]
@briancolinger This is an old one and haven't seen this issue in a while. Do you think it's safe to close?

**Comment by briancolinger** [comment]
I think this is safe to close now.

**Comment by keoshi** [comment]
Thank you!
