### ISSUE TITLE
Activity Log: all saved credentials showing up as SSH

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22165]
No matter what type of credentials the user has entered (FTP, SFTP, SSH), the saved settings always show “SSH”:

<img src="https://user-images.githubusercontent.com/390760/35860600-93aafc70-0b3c-11e8-9055-9b283a0df7c1.png">

**Comment by samhotchkiss** [comment]
Fixed in #22060

**Comment by eliorivero** [comment]
Closing since creds form now says

<img width="735" alt="captura de pantalla 2018-02-19 a la s 14 25 06" src="https://user-images.githubusercontent.com/1041600/36390163-c5ecca9e-1580-11e8-8160-ba39992d39ee.png">
