### ISSUE TITLE
Checkout: create duplicate charge prevention

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2217]
Raised by @peterbutler 

The wp-admin purchase process has _some_ duplicate charge protection, using memcached to attempt to avoid matching transactions less than a minute apart.  the `/transactions` endpoint does not attempt to duplicate this - but does need to implement some kind of duplicate transaction prevention at some point.

**Comment by prettyboymp** [comment]
The transactions endpoint has an implementation to handle this.
