### ISSUE TITLE
Can't un-like posts in Reader

### ISSUE THREAD

**Issue by Gilmoursa** [Automattic/wp-calypso#22178]
Can't un-like posts in Reader

#### Steps to reproduce
1. Starting at URL:  https://wordpress.com/
2. Open the Reader
3. Like a post
4. Unlike the post
5. Refresh page

#### What I expected
I expect that that post will be unliked when I refresh the page

#### What happened instead
The post I un-liked was still visible and 'liked'

#### Browser / OS version
Chome 64-bit/ Windows 10 

a fellow HE confirmed the issue on their computer as well. A user also reported the issue in HC.

**Comment by jancavan** [comment]
I can confirm this is happening in stream and fullpost.

**Comment by cacheflow** [comment]
I'll look into it.

**Comment by bluefuton** [comment]
@samouri related to Redux-ifying likes?

**Comment by samouri** [comment]
@bluefuton, I don't think anything has been merged w.r.t reduxifying likes yet. 
@blowery is handling the task and its taking place in https://github.com/Automattic/wp-calypso/issues/22013
