### ISSUE TITLE
Navigation Menu: Front-end menu doesn't display MEDIA in Atomic

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/wp-calypso#22182]
When viewing an Atomic site from the front end and then clicking on MY SITE to view the slide-out nav menu, the link to the Media Library (MEDIA) isn't displayed:

![screen shot 2018-02-06 at 12 43 45](https://user-images.githubusercontent.com/6569475/35877991-85abc014-0b3c-11e8-8705-379588fc7b5e.png)

The behavior is different when viewing the nav-menu from the front end of a non-Atomic site:

![annotation on 2018-1-2](https://user-images.githubusercontent.com/6569475/35878052-be9fc50a-0b3c-11e8-97c4-2fe3d11627ad.png)

I discovered this while doing a Business concierge chat with a user where I was walking her through the process of adding alt tags to her images, and she clicked on MY SITES while viewing the front end of her page and was confused about what I was talking about. 

#### Steps to reproduce
1. Enter the URL of an Atomic site (incognito is fine) while logged in to that site, and then click on MY SITE at the top left of your screen while still viewing the site's front end. 
2. The link to MEDIA (Media Library) will not appear. 

#### What I expected

To see the MEDIA link available from the nav menu of an Atomic site whether I'm on the front end of the site or viewing the backend dashboard. 

#### What happened instead

Link to MEDIA does not appear on slide-out nav menu when clicking on MY SITE while viewing the site's front end. 

#### Browser / OS version

Chrome

#### Context / Source

#manual-testing

**Comment by rachelmcr** [comment]
Thanks for the report! The front-end menu on Atomic sites is actually controlled by Jetpack (not Calypso) — this issue is being tracked here: https://github.com/Automattic/jetpack/issues/7009
