### ISSUE TITLE
Editor: remove notice now that date changes redirect the old URL properly

### ISSUE THREAD

**Issue by nickmomrik** [Automattic/wp-calypso#22191]
#### Steps to reproduce
1. Edit a published post.
2. Change the date.
3. Update the post.
4. You'll get this warning...

![calypso-date-change-warning](https://user-images.githubusercontent.com/684691/35886643-c022e1c8-0b5f-11e8-9b22-10db8f3315f7.png)

This is no longer true. In WordPress 4.9.3 (and merged to WordPress.com), a fix was put in that redirects old dates for published posts. See https://core.trac.wordpress.org/ticket/15397

**Comment by lancewillett** [comment]
Thanks for adding this, Nick. @jblz Could @Automattic/delta-samus take a look at this one?

**Comment by lancewillett** [comment]
@mattsherman Could @Automattic/tanooki take a look at this one, please?
