### ISSUE TITLE
Jetpack Onboading: Use a more userfriendly route

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#22219]
It seems that the current `/jetpack/onboarding` route isn't the best route for a user-facing URL. Can we come up with a better route?

cc-ing some folks to gather some feedback:

@Automattic/luna 
@rickybanister @MichaelArestad @joanrho 
@richardmuscat @jessefriedman 
@beaulebens

**Comment by joanrho** [comment]
`jetpack/start`
