### ISSUE TITLE
Jetpack Settings: Site Verification Services notice should be converted to a module toggle

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#22215]
Right now, if a user has a paid plan but their Site Verification Services Jetpack module is not active, we display a notice that contains a button to activate that module:

![](https://cldup.com/89BLlqjdpd.png)

This is inconsistent with the rest of the settings for modules where we display a module toggle, for example **Ads**:

![](https://cldup.com/A4mR7tzTnn.png)

In order to make it less scary and more consistent, we should turn the notice into a card with a module activation toggle.

cc @rickybanister

**Comment by beaulebens** [comment]
This is another "implicit activation" situation (https://github.com/Automattic/wp-calypso/issues/22216)

**Comment by tyxla** [comment]
Addressed by #23040.
