### ISSUE TITLE
Checkout: Premium upsell on domains in redemption removes redemption product

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/wp-calypso#2221]
Domains that are in redemption automatically have the redemption product added to the cart at checkout for domain renewal. Here we show an upsell to the Premium plan stated that domain renewal is included in that.

<img width="217" alt="screen shot 2016-01-07 at 4 15 46 pm" src="https://cloud.githubusercontent.com/assets/312395/12186689/febd822a-b559-11e5-98f0-788a27c6c77f.png">

Clicking on that link takes you to Premium checkout, however the redemption product is missing.

Steps to reproduce:
1. Login to account with domain in redemption
2. Go to /purchases, click on domain purchase -> Renew
3. In checkout confirm the presence of redemption product and Premium upsell
4. Click on upsell link and confirm absence of redemption product.

**Comment by janm6k** [comment]
Going through old issues, closing ones that did not have any activity in long time.

Please feel free to reopen if applicable.
