### ISSUE TITLE
Feature request: Contact form: Add QandA search for Jetpack questions

### ISSUE THREAD

**Issue by joeboydston** [Automattic/wp-calypso#22223]
We are using the same contact form `/help/contact` for both wpcom and jetpack customers. We need to return a different set of answers for each group.

Example: Jetpack rewind. These questions should not be shown to wpcom customers.

URL:
https://wordpress.com/help/contact

cc: @notnownikki

**Comment by notnownikki** [comment]
Being addressed in https://github.com/Automattic/wp-calypso/pull/22374
