### ISSUE TITLE
Showcase: Show search filters by default

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#22228]
#### Steps to reproduce
1. Go to Theme Showcase.
2. Click into the search filed.
3. The filters appear.

#### What I expected
I didn't expect the filters to appear as a new user. The filters are hidden from users who are not familiar with this action.

#### Screenshot / Video
![show-filters](https://user-images.githubusercontent.com/617986/35941995-1540287e-0c09-11e8-8b30-8b510d2d3100.gif)

#### Context / Source
While this isn't a bug, it is a mystery meat sort of feature. The filters help guide user's queries, but only if they're visible. By showing them as default, it could help users understand how to search more specifically.

In addition to this, when the user has committed to entering text in the search field, they are likely not going to be clicking on filters at that point in their journey. So by showing them when the user is engaged in something else, we're distracting the user from their desired action.

**Comment by lancewillett** [comment]
💯 This comes up a lot during HE 1-1 sessions with customers trying to find themes. If the search filters are visible, it helps them get to a good match faster.
