### ISSUE TITLE
Site Doesn't Exist page has awkward styling on error message

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#22222]
#### Steps to reproduce
1. Starting at URL:  https://en.wordpress.com/typo/?subdomain=asdjsnejldkw
2. See hot pink error message

#### What I expected
I expected something nicely styled.

#### What happened instead
I got something not nicely styled.

#### Browser / OS version
Chrome

#### Existing Screenshot 
![screen shot 2018-02-07 at 10 46 23 am](https://user-images.githubusercontent.com/617986/35935171-87ce806c-0bf4-11e8-8d33-58367e26397f.png)

#### Proposed Screenshot with new styling
![screen shot 2018-02-07 at 10 46 11 am](https://user-images.githubusercontent.com/617986/35935188-9351917c-0bf4-11e8-84ae-59b4a4af8352.png)

Proposed element style additions and revisions:
```
height: auto;
padding: 1em;
top: 46px;
```

**Comment by designsimply** [comment]
Thank you for reporting this! I have moved this issue to wpcom.trac because that is where the code exists for front-end issues such as this one (internal reference 8005-wpcom).

**Comment by lancewillett** [comment]
Note for future: the pink banner only shows to Automattic people, logged-in with their WordPress.com username.

Rest of the world doesn't see the pink banner.

<img width="1392" alt="Screen Shot 2020-02-20 at 09 29 03" src="https://user-images.githubusercontent.com/66797/74956508-74b57a80-53c3-11ea-96c7-a30a3317b750.png">
