### ISSUE TITLE
JPC plans flows interfering with others

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#22226]
Right now, if you visit any jetpack NUX url that pre-selects a plan for you (for example, https://wordpress.com/jetpack/connect/personal  ), but then you abandon the flow and then, later, start a regular connection flow, the values we store during the first flow are interfering with the new one and we are considering that you are just continuing with the plan-purchase flow.

We probably need to make sure that any new flow clears any variable we are storing in the plan pre-selection flows to avoid this kind of side effects

**Comment by rachelmcr** [comment]
Looks like this one was fixed by https://github.com/Automattic/wp-calypso/pull/22689.
