### ISSUE TITLE
Free Trials: Add link to free trial hub on thank you page

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#2222]
The thank you page should provide a path to the free trial hub. Here's the proposed design for adding a link:

![image](https://cloud.githubusercontent.com/assets/12596797/12188985/1fbf24fa-b588-11e5-9105-7402b20d8789.png)

cc @breezyskies for design review

@fabianapsimoes I marked this as v1 because it's a quick simple change that I'd really like to get in for v1 especially since we won't have the notifications for v1 (they led to the free trial hub).

**Comment by breezyskies** [comment]
Design looks good :+1:

**Comment by fabianapsimoes** [comment]
> The thank you page should provide a path to the free trial hub. Here's the proposed design for adding a link.

We could also just redirect users to the hub right after checkout. What do you think?

**Comment by mikeshelton1503** [comment]
> We could also just redirect users to the hub right after checkout. What do you think?

That's a possibility, and something that we wanted to try in the future. We wanted to test in to it and we also have a new version of the thank you page we wanted to test as well. 

However, the free trial hub would provide all of the same info the thanks page does (with the inclusion of a notification confirming the successful action) and even more. So it's intriguing. We could still do our thank you page test later, just in a backwards order as we had planned. @breezyskies Thoughts?

**Comment by breezyskies** [comment]
+1 for redirecting to the free trial hub. Seems like a good solution for now and we can loop back to test thank you pages later.

**Comment by mikeshelton1503** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/2236
