### ISSUE TITLE
Activity Log: show "title" for text widget updates

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#22243]
Jetpack Activity log item for text widget updates could include a widget title?

![image](https://user-images.githubusercontent.com/87168/35973533-7e86e09a-0cde-11e8-8425-f33ecc9c8d2f.png)

Instead of "_Text_" this could say "_Text: test_" just like widgets area at wp-admin does:

![image](https://user-images.githubusercontent.com/87168/35973568-9b70a4d4-0cde-11e8-8749-d1b97216d2f1.png)

There is typically just one of each other widget types at a site but multiple text widgets. Activity log updates about them can get a bit confusing.

/cc @lezama @MichaelArestad

**Comment by gititon** [comment]
In progress.

**Comment by lezama** [comment]
https://github.com/Automattic/jetpack/pull/8786

**Comment by gititon** [comment]
https://code.a8c.com/D10043
https://github.com/Automattic/jetpack/pull/8786/
