### ISSUE TITLE
Invite accepted activity has incorrect gravatar

### ISSUE THREAD

**Issue by gititon** [Automattic/wp-calypso#22256]
Rick Banister reported that the Invite Accepted activity displays the incorrect Gravatar - it displays the Gravatar of the administrator that invited the user rather than the invitee himself.

![image](https://user-images.githubusercontent.com/437258/35991293-c35c5af6-0cd4-11e8-8233-ca3d8bdb9c08.png)

**Comment by eliorivero** [comment]
Another example:

<img width="729" alt="captura de pantalla 2018-02-09 a la s 13 23 06" src="https://user-images.githubusercontent.com/1041600/36037799-93ddb4a0-0d9c-11e8-8700-115d080eff10.png">

**Comment by gititon** [comment]
Thanks, @eliorivero , I'm working on this now.

**Comment by gititon** [comment]
@eliorivero , @rickybanister , would you guys mind testing this again? I believe I resolved it.

**Comment by rickybanister** [comment]
Is your fix retroactive or will we need to send a new invite? Testing instructions would be helpful.

**Comment by rickybanister** [comment]
(I'm still seeing the wrong avatar, so I assume the fix is not retroactive)

**Comment by gititon** [comment]
Hi, the fix is not retroactive (though we could probably figure something out if it was deemed important enough). You can test it by inviting a new user to your site from Calypso, creating that user and accepting the invite, and verifying that the appropriate Gravatar appears. That's how I reproduced the issue. If that isn't what you did to encounter this issue in the first place, please test it doing whatever you'd done previously and let me know. Thanks!

**Comment by rickybanister** [comment]
Confirmed that it's fixed with a new invitation.

Thanks @gititon

**Comment by gititon** [comment]
Awesome, thanks @rickybanister !
