### ISSUE TITLE
Stats panel showing over menu on mobile

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#22258]
#### Steps to reproduce
1. Log in to Calypso on mobile device/emulator, or resize a desktop browser (Chrome, Firefox) to narrow width
2. View the site dashboard

#### What I expected
The dashboard menu to look and work properly

#### What happened instead
The stats panel is showing over the top

#### Browser / OS version
Chrome emulator
Chrome/Android
Chrome/Firefox desktop browser with narrow widths

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/31110506/35991041-cb67030a-0cba-11e8-8b7e-27258bc70727.png)

#### Additional
Seems to have started with this commit: dead79441a45004ad60888bdfb6f7aa905e3dd8e

**Comment by kwight** [comment]
It turns out this is a larger issue, possibly going back days or weeks. It's not just stats showing, but other elements from the `primary` section – for example, Plans:

![screen shot 2018-02-08 at 11 45 56 am](https://user-images.githubusercontent.com/349751/35994663-fda43896-0cc5-11e8-90a3-2e627a0ac5f6.png)

As @gwwar pointed out, the real issue seems to be that the `primary` section shouldn't be rendered for this sidebar view at all (which would cover any later situations of `z-index` wars between elements and sections).

**Comment by alisterscott** [comment]
This seems to effect all mobile browser users.

Could we revert the notifications client update to see whether that helps?

**Comment by kwight** [comment]
@alisterscott I think proceeding with #22271 would be a better approach, since it's not notifications related.

**Comment by shaunandrews** [comment]
FWIW, I'm unable to reproduce this on Mobile Safari or Google Chrome iOS.

**Comment by alisterscott** [comment]
> FWIW, I'm unable to reproduce this on Mobile Safari or Google Chrome iOS.

Yes, it doesn't happen using Safari on macOS or any browser on iOS (which use Safari)

**Comment by kwight** [comment]
@alisterscott ha, you beat me to it 🙃

**Comment by alisterscott** [comment]
When no stats appear, the text comes through

<img width="649" alt="screen shot 2018-02-15 at 10 20 28 am" src="https://user-images.githubusercontent.com/128826/36235603-6709318e-123d-11e8-8e01-773dbe8dda5f.png">

**Comment by gwwar** [comment]
Yup, same type of bug! Basically any elements as a child of the primary div with z-index set will leak through into this view.

**Comment by kwight** [comment]
The regression I saw with the Reader that led to the revert of #22271 👍 

![screen shot 2018-02-14 at 4 06 59 pm](https://user-images.githubusercontent.com/349751/36236187-9e5b31ee-11a9-11e8-8d11-8046bbc409dc.png)

To replicate:
* Click on Reader.
* Select a post title.
