### ISSUE TITLE
Guided Tours: buggy z-index order

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22254]
The guided tour dialog sometimes appears on top of the masthead with a higher z-index order.

![pasted image at 2018_02_08 04_22 pm](https://user-images.githubusercontent.com/390760/35986362-c17f7cf6-0cf0-11e8-82d6-5b32f48f6d55.png)

**Comment by fditrapani** [comment]
Fix here: https://github.com/Automattic/wp-calypso/pull/22253
