### ISSUE TITLE
Domains: Add copy to explain pre-filled domain contact information

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#22262]
It would be nice to add some copy to explain where we got the contact information we pre-fill on registration and transfer-in. This is not specific to incoming transfers, but it's more important to explain it for a domain that's already registered and has contact information (that might not be the same as their WordPress.com account). As originally reported by @rachelmcr:

> I had a moment of panic when I got to the checkout page and saw the “Domain Contact Information” section filled out with my contact info. My domain has private registration, and I thought I was seeing the actual contact information associated with my domain (i.e. leaking private details to anyone who tried to transfer the domain)

<img width="741" alt="screen shot 2018-02-08 at 13 44 38" src="https://user-images.githubusercontent.com/448298/35992099-524a08ec-0cd7-11e8-8e9a-67ad354d2296.png">

**Comment by aidvu** [comment]
https://github.com/Automattic/wp-calypso/pull/22347
