### ISSUE TITLE
Site Picker: Always show site picker for multi-site accounts regardless of site visibility

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#22286]
#### Steps to reproduce
1. Log into an account that owns multiple WordPress.com sites
2. Navigate to My Blogs in WP-Admin, and set all but one site to hidden
3. Open https://wordpress.com/ and click on My Sites

#### What I expected
For my primary site to be selected, but to still be able to get to the sites I'd set as hidden if needed by using the Search box in the site picker - on accounts where more than one site is visible and listed in the site picker, hidden sites can still be reached by typing their title/URL in the search field.

#### What happened instead
Despite there being other sites in the account, there is no way to get to them in Calypso, as the Switch Site option is simply not there.

#### Screenshot / Video

<img width="572" alt="stats_ _a_lonely_pilgrim_ _wordpress_com" src="https://user-images.githubusercontent.com/11873759/36027223-123b046e-0da3-11e8-9c2f-8e48433b3e35.png">

If I set two sites in the account to visible, the site picker appears:

<img width="717" alt="stats_ _a_lonely_pilgrim_ _wordpress_com" src="https://user-images.githubusercontent.com/11873759/36027289-4ff42556-0da3-11e8-92e0-6fe75fb467c0.png">

and clicking on it allows me to access hidden sites as well if needed:

<img width="548" alt="stats_ _a_lonely_pilgrim_ _wordpress_com" src="https://user-images.githubusercontent.com/11873759/36027340-8cfc3dbc-0da3-11e8-836d-e9153714d490.png">

#### Context / Source

I did some testing prompted by p2MSmN-6nK-p2

In that case it was further complicated by the fact that the user had a hidden site set as the account's primary site. So when navigating to Calypso via the normal WordPress.com ->My Sites route, the hidden primary site was automatically selected, with no way for the user to switch to their active site.

**Comment by rachelmcr** [comment]
Recent user reports:
* p2EDhh-ut-p2
* p1533579241000370-slack-livechat
* p1525957224000364-slack-livechat
* p1531978928000079-slack-tickets
* p1534487125000100-slack-livechat

Somewhat related issue (would have resolved some of the user reports above): https://github.com/Automattic/wp-calypso/issues/23503

This also seems to be more of an issue for support now, as not all HEs are familiar with/aware of the WP Admin My Blogs screen.

**Comment by rezzap** [comment]
I recently reconnected Jetpack on a business plan site and encountered this issue. After reconnecting Jetpack the business plan site no longer displayed under My Sites and I could not select them from the My Sites list because the user's WordPress.com sites were both hidden. 

8716762-hc

**Comment by sandymcfadden** [comment]
Had another case here 2315898-zd
Their primary site was set as hidden in the My Blogs section but still displayed it when going to My Sites. Because only one site was visible they were not able to switch sites to see the other site which was marked as visible.
This caused worry for the customer as they thought they lost access to their site.

**Comment by Aurorum** [comment]
PR in #35919 for this issue. :)
