### ISSUE TITLE
Customizer: link to open customizer always uses HTTPS, even on HTTP sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#22280]
#### Steps to reproduce

1. Starting with a Jetpack site connected to WordPress.com. That site must **not** be using HTTPS.
2. Go to WordPress.com and click on My Sites
3. Select the Jetpack site
4. Click on the Customize link in the sidebar.

That link uses HTTPS, even if the site does not have a valid SSL certificate.

Related: #9655

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided that opening the Customizer from Calypso for a non-HTTPS Jetpack site results in a "Connection is Not Secure" notice in the browser ([19s](https://cloudup.com/c7SrSKfNuNs)).

![connection-is-not-secure-notice-in-the-customizer](https://user-images.githubusercontent.com/1119271/36685893-0ac7ac04-1ae2-11e8-913e-2dc265f95b4e.png)
<sup>Seen at http://madefortesting.com/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fstats%2Fday%2Fmadefortesting.com (production) using Firefox 58.0.2 on macOS 10.13.3.</sup>

@jeherve may I ask what makes this issue `[Pri] High`?

**Comment by jeherve** [comment]
> may I ask what makes this issue [Pri] High?

Every time you access a Jetpack site's dashboard, we synchronize the URL you use to access that dashboard back to WordPress.com, and use that URL for all Jetpack connection requests from that point on. This issue consequently breaks your Jetpack connection when we start using HTTPS to access your site when in fact your site does not have a valid SSL certificate.

**Comment by jeherve** [comment]
> opening the Customizer from Calypso for a non-HTTPS Jetpack site results in a "Connection is Not Secure" notice in the browser 

This is quite different. It seems you could not reproduce the issue on your end. Your site was loaded via HTTP, not HTTPS. I would be curious to see if you can reproduce when you are already logged in to your site.

**Comment by designsimply** [comment]
> I would be curious to see if you can reproduce when you are already logged in to your site.

I tested again by first logging in to WP Admin for two different HTTP-only Jetpack sites and then going to https://wordpress.com/ > My Sites > Switch to the HTTP Jetpack site > Customize where the Customizer opens in a separate tab and works but displays a "Connection is not secure" warning in the browser.

<strong>Video:</strong> [2m57s](https://cloudup.com/cKqCpOI2VcZ)
<sup>Tested with madefortesting.com with WP 4.9.4 and Jetpack 5.8 and wpcomsupport9.com with WP 4.9.4 and Jetpack 5.9-beta, both connected as user design5279, using Firefox 58.0.2 on and Chrome 64.0.3282.167 on macOS 10.13.3.</sup>

What happens differently when you test? Should I try different testing steps or are my sites configured differently perhaps?

**Comment by jeherve** [comment]
> displays a "Connection is not secure" warning in the browser.

I believe that is to be expected, and just happens because the site does not use HTTPS. Browsers have been pushing people towards HTTPS a lot more lately.

> What happens differently when you test? Should I try different testing steps or are my sites configured differently perhaps?

I actually can't reproduce the issue anymore :D It looks like we're all set! Closing.
