### ISSUE TITLE
Jetpack Plugins: "Update to" message remains after updating plugin on detail page

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#2229]
Steps to reproduce:

1. Go to https://wordpress.com/plugins/updates
2. Click on a plugin that needs updating.
3. Expand a site where the plugin is installed, and toggle "Enable autoupdates"
4. The plugin updates itself, I receive a success message, but an "Update to" button appears and stays there for 5 to 10 seconds:

![screen shot 2016-01-08 at 12 21 09 pm](https://cloud.githubusercontent.com/assets/426388/12196893/9b4aa84a-b602-11e5-96ba-de111b4c1f18.png)

Clicking on it seems to launch a new update.

**Comment by enejb** [comment]
I think this is fixed now. Feel free to open this again if that is not the case for you @jeherve
