### ISSUE TITLE
Reader: VIPs only get excerpts in search and tag streams

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#22299]
As noted in: https://github.com/Automattic/wp-calypso/pull/22101#issuecomment-364246643, in certain streams like tags/search VIPs will only get excerpts whereas if the full-post were loaded from following or directly from site/feed-stream the entire post would be visible.

> Repro steps:
> 1.  go to search
> 2. search for a "uproxx" and click one of their posts
> 3. you will only see an excerpt. refresh and you'll see the whole thing

---

This should get fixed pretty soon as I move all of the data-fetching for posts to the data-layer

**Comment by bluefuton** [comment]
Appears to be fixed by @samouri’s Redux efforts :)
