### ISSUE TITLE
Activity Log: improve pingbacks

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#22292]
A pingback—identified as a comment, which is kind of correct, since it's a special type of comment—is shown without avatar, even when it was done by the author of the site.

I ran into this while authoring a post and adding a link to a previous published post. It showed up in AL like this:

<img width="814" alt="captura de pantalla 2018-02-09 a la s 10 54 58" src="https://user-images.githubusercontent.com/1041600/36037940-f2fe401c-0d9c-11e8-9b18-879a85bc4e59.png">

- no user avatar
- mystery man avatar is top aligned
- no name
- no role
- could be identified as pingback
- has the post title at the top, don't think it's useful

Now, after approving this pingback, I got a much better view but it could be improved:

<img width="761" alt="captura de pantalla 2018-02-09 a la s 13 29 46" src="https://user-images.githubusercontent.com/1041600/36038089-66849c84-0d9d-11e8-9a73-2bfc3e01d354.png">

- *Comment by [post]* could be *Pingback by [post]*
- the title of the post that sends the pingback could be set in italic or bold

**Comment by lezama** [comment]
@MichaelArestad @keoshi any wishes here?

**Comment by MichaelArestad** [comment]
Yes, but I need more information.

Can we identify that a pingback is a pingback instead of a comment? If so, we'll want to label it differently than comments. We'll also want to show the author regardless of if approved.

**Comment by eliorivero** [comment]
> Can we identify that a pingback is a pingback instead of a comment?

Yes, a pingback is a type of comment:

```php
$is_pingback = 'pingback' == $comment->comment_type;
```

A comment can be of type `comment`, `pingback`, or `trackback`.

**Comment by gititon** [comment]
In progress.

**Comment by gititon** [comment]
@MichaelArestad I'm working on distinguishing pingbacks from comments in the AL. Can you please let me know what you'd like for their summary and content in the meantime? Thanks!

**Comment by MichaelArestad** [comment]
> Pingback by <author> on <post>
> Pingback awaiting approval

* make sure <post> is a link to the post
* the second line (small text) should be identical to the relevant comment lines, but with `comment` replaced by `pingback`

**Comment by lezama** [comment]
@gititon has a fix for this around the corner

**Comment by roccotripaldi** [comment]
I think this has been addressed already. @gititon can you confirm?

**Comment by gititon** [comment]
Looking into it, @roccotripaldi

**Comment by gititon** [comment]
Yes, @roccotripaldi, I had beautified the, way back when:

<img width="1095" alt="screen shot 2018-12-10 at 4 41 48 pm" src="https://user-images.githubusercontent.com/3246867/49763415-8ae18a00-fc9a-11e8-84af-4ab6923aee93.png">
