### ISSUE TITLE
Editor: Paste not an option from right-click menu when content area empty

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#223]
A user reported that right-click pasting was not working in the Calypso editor main content area when empty and I reproduced the issue in Chrome, Firefox, and Safari on OS X 10.11. It looks like the content area is treated as some sort of frame area that doesn't allow pasting before any content is added. Once content is added paste becomes available.

This is an issue for users who draft posts in Word or another external program and paste it into the Editor without adding other content first. Command+v shortcut continues to work as expected even without content.

![screen shot 2015-11-19 at 12 59 06 pm](https://cloud.githubusercontent.com/assets/1900444/11279509/1a3d77ba-8ebf-11e5-90d6-67857d581d14.png)

**Comment by kriskarkoski** [comment]
Marking this as Low priority as I looked into it again and the behavior seems to match WP Admin so it may be a TinyMCE expected behavior. Specifically, you can right-click paste if your cursor is in the content area and you right-click within the same line, but right-clicking further down will not work.

**Comment by rachelmcr** [comment]
I'm using Safari 9.0.1 on Mac OS X 10.10.5, and the behavior doesn't match WP Admin. In Calypso, even if I right-click directly over existing text or the cursor, I don't get a Paste option. I see the right-click menu in the screenshot above. In WP Admin, however, I do get a Paste option there.

In Chrome, it works the same as in WP Admin.

**Comment by kriskarkoski** [comment]
@rachelmcr I think #517 will fix the difference in behavior in Safari, at least it seems to for me, though the issue of not being able to right-click anywhere in the content box remains, but exists in both Calypso and WP Admin as far as I can tell

**Comment by designsimply** [comment]
Note from @lancewillett from a previous report of this issue:

<blockquote>I'm able to repeat this in Safari — seems like the focus of the mouse is on the preview iframe and not the editor.</blockquote>

<img width="1252" alt="2a3069fa-8f6b-11e5-9283-f294d10ccb82" src="https://cloud.githubusercontent.com/assets/1119271/11449532/5cd8ef4e-9547-11e5-9ea9-f87c615e17f6.png">

**Comment by aduth** [comment]
Per #517, the original issue here is fixed (not being able to right-click text due to iframe preview). However, as noted by @kriskarkoski above, the TinyMCE iframe right-click menu will be shown when clicking below the filled text area.

**Comment by lancewillett** [comment]
Closing as "works for me" — let's open new bugs in new issues.
