### ISSUE TITLE
Jetpack Plugins: Gravity Forms displays an update available even though it's not in the repo

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#2230]
Steps to reproduce:
1. Install and activate Gravity Forms on a Jetpack site.
2. When an update is available, Gravity Forms hooks into Core's Update screen to warn the user that an update is available:
   ![screen shot 2016-01-08 at 12 37 29 pm](https://cloud.githubusercontent.com/assets/426388/12197121/9c5b59d0-b604-11e5-9b30-4a23ced46f19.png)

That's super practical in wp-admin, but unfortunately that update notice also carries over to WordPress.com, where we can't update the plugin since it's not hosted in the WordPress.org repo:
![screen shot 2016-01-08 at 12 38 30 pm](https://cloud.githubusercontent.com/assets/426388/12197153/d9844b64-b604-11e5-8a56-e105659ec95e.png)

![screen shot 2016-01-08 at 12 39 20 pm](https://cloud.githubusercontent.com/assets/426388/12197158/dd064e18-b604-11e5-9493-eb31c6d7e670.png)

In an ideal world, we should be able to run the update from WordPress.com as well. If that's not possible, it'd be nice to offer an option for the site owner to go to wp-admin to run the update.

**Comment by jeherve** [comment]
cc @stevehenty: you might be interested in this issue, as it may come up with some of your clients.

**Comment by stevehenty** [comment]
Thanks @jeherve, we'll certainly look into it.
