### ISSUE TITLE
Showcase: Remove 'You might also like' section from theme sheets

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#22308]
At the bottom of each theme sheet, we show suggested themes with the header "You might also like". For example this is what I get visiting https://wordpress.com/theme/radcliffe-2:

![](https://cldup.com/GuBpYLHYh2-3000x3000.png)

These themes are all pulled from a short list ([here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/theme/themes-related-card/index.jsx#L27)), and they're loaded randomly, not based on the current theme. 

They are themes we recommend _in general_, but showing them in this way with the "You might also like" header implies they're in some way related to the current theme. In reality, it'd be a coincidence if they were comparable in features/style/purpose to the theme being viewed.

I think this section should be removed -- as it works now, it's not very helpful. It could be good to revisit in the future with more control over the suggestions.

**Comment by lancewillett** [comment]
I think we should just hide this entire section for now.

**Comment by folletto** [comment]
📚 Historical note: the title was "You might also like" because exactly as noted it was meant to be the MVP of a future iteration where the list was going to be related themes. We didn't have time to do that iteration.
