### ISSUE TITLE
Add New Site: simplify the “Add a New Site” screen

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22315]
Steps to reproduce:

1. Sign in to https://wordpress.com/ and go to My Sites > Switch Site.
1. Click "Add New Site" at the bottom of the sites list.

<strong>Result:</strong> 

![screen shot 2018-02-09 at fri feb 9 3 24 46 pm](https://user-images.githubusercontent.com/1119271/36053067-66ffaefa-0dad-11e8-8be2-2e1b5314dd92.png)
<sup>Seen at https://wordpress.com/jetpack/new?ref=calypso-selector using Safari 11.0.3 on macOS 10.13.3.</sup>

Possible solution: simplify to use a stacked/integrated flow like this:

<a href="https://user-images.githubusercontent.com/1119271/36053256-3f842ba2-0dae-11e8-9292-47bdc7f69246.jpeg"><img src="https://user-images.githubusercontent.com/1119271/36053256-3f842ba2-0dae-11e8-9292-47bdc7f69246.jpeg" width="270"></a>

/hat tip 🤠 @beaulebens for the sketch and original report at p4k3M4-2uX-p2

**Comment by drw158** [comment]
If we haven't already, it's worth looking at what we do on iOS/Android since that flow is the simplest one we have.

**Comment by designsimply** [comment]
Excellent idea. Here's how adding a site looks for WPAndroid:

<img src="https://user-images.githubusercontent.com/1119271/36055504-2041a380-0dba-11e8-8030-04d399e755b0.png" width="270"> <img src="https://user-images.githubusercontent.com/1119271/36055509-2c542788-0dba-11e8-976f-dfb08bb22ac0.png" width="270"> <img src="https://user-images.githubusercontent.com/1119271/36055512-329a953c-0dba-11e8-9d9b-2a10c5a03ba8.png" width="270"> <img src="https://user-images.githubusercontent.com/1119271/36055515-345caf36-0dba-11e8-9a56-41cefb5b3bad.png" width="270">

<sup>Tested with Pixel, Android 8.1.0, WPAndroid alpha-96.</sup>

**Comment by designsimply** [comment]
Here's how adding a site looks in WPiOS:

<img src="https://user-images.githubusercontent.com/1119271/36055615-ea45fbcc-0dba-11e8-9fea-c8d4d3739b18.PNG" width="270"> <img src="https://user-images.githubusercontent.com/1119271/36055619-ec145200-0dba-11e8-899c-9f590ac49713.PNG" width="270"> <img src="https://user-images.githubusercontent.com/1119271/36055621-edca0e0a-0dba-11e8-933a-79155a0d5521.PNG" width="270"> <img src="https://user-images.githubusercontent.com/1119271/36055622-ef784d2a-0dba-11e8-9d3c-8d5327bf87a4.PNG" width="270">

<sup>Tested with iPhone 6S, iOS 11.2.5, WPiOS 9.3.0.20180201.</sup>

**Comment by eliorivero** [comment]
Maybe we should drop the `Create wordpress.com site` and just use "Create new site" and "Add my self-hosted site".

**Comment by rickybanister** [comment]
@keoshi If you're looking at doing a more refined mockup of this I think it may make sense to remove the URL step from this screen to put both call to action buttons on equal footing. It will also be easier to maintain if this screen is simply an in-road to /jetpack/connect. That way we can iterate on the url step there independently of this UI, we can try new things and not worry about updating it in two places, etc. With remote installation coming I think that makes sense anyway.

**Comment by keoshi** [comment]
Sounds good, will take care of this soon.

**Comment by keoshi** [comment]
@drw158 @designsimply We actually tested that first before committing to this version, it was a simple popover with dotcom and JP options:

![image](https://user-images.githubusercontent.com/390760/37105019-043456bc-2226-11e8-9e95-c291d10eb0ea.png)

We also tested this dual-pane version; more context here: p58i-5KQ-p2

For now I'm going to simplify this view by having just one pane and streamline the content.

**Comment by joanrho** [comment]
FYI this is being worked on by @keoshi in #23093

**Comment by keoshi** [comment]
This on longer applies since that page is gone; closing.
