### ISSUE TITLE
Activity Log/Notifications: no icon in threat notification

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22329]
When Jetpack detects a new threat on a site and notifies the user, the notification comes up with no icon:

![image](https://user-images.githubusercontent.com/390760/36095561-9129feee-0fea-11e8-9504-538df535f4eb.png)

This type of notification should be using the `notice` gridicon:

![image](https://user-images.githubusercontent.com/390760/36095636-ef79a832-0fea-11e8-9d8f-be00111cfaf5.png)

**Comment by eliorivero** [comment]
Fixed in 169937-wpcom

<img width="410" alt="captura de pantalla 2018-02-12 a la s 15 37 23" src="https://user-images.githubusercontent.com/1041600/36113322-312d04a2-100b-11e8-8bb3-a4e571d70112.png">

**Comment by keoshi** [comment]
Thank you, @eliorivero !
