### ISSUE TITLE
Display sharing content (publicize info) dates in a calendar 

### ISSUE THREAD

**Issue by htdat** [Automattic/wp-calypso#22324]
Currently, to see the scheduled re-publicize posts, we need to go each post and check `Share` like [this](https://en-support.files.wordpress.com/2009/10/zrzut-ekranu-2017-02-14-o-16-27-30.png?w=920&h=758).

For a site with a lot of scheduled posts and re-publicize posts, having a calendar to see the schedule would be great. 

This is just the general idea for boht WordPress.com and Jetpack sites, I hope that our design can work on this in detail. 

From: 953738-zen

**Comment by rachelmcr** [comment]
Thanks for the suggestion! I'm going to close this issue as we're tracking this idea here: https://github.com/Automattic/wp-calypso/issues/16672
