### ISSUE TITLE
Checkout: optimize favorites in country lists

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2233]
Raised by @stephanethomas 

We should update the favorite countries displayed at the top of the country lists on the domain registration details page as well as the secure payment page (in the new credit card and Paypal Express forms). The favorite countries should be the top 10 most popular countries according to previous purchases.

**Comment by peterbutler** [comment]
@stephanethomas: Do you picture this being something we update dynamically, or something we check in on occasionally and update?

Personally, I'd vote to just hardcode it and check in on it every few months, I'd be surprised to learn that it changes enough to justify an endpoint, or another dynamic solution.

**Comment by hafizrahman** [comment]
I'd vote for a hardcode and regular checks too. I understand that it's something that makes life easier for users, but never heard a feedback about it being a big pain point.

**Comment by gziolo** [comment]
From #2234:
> We could display less popular countries and instead include the following:

> * The [geolocalized country](https://public-api.wordpress.com/geo/) of the user
* Any previously selected country available from the `localStorage` or a cookie
* Any country used for a previous domain registration
* Any country used for a previous payment

**Comment by stephanethomas** [comment]
I guess the most popular countries according to previous purchases could indeed be hardcoded, and probably A/B tested. However the other suggestions mentioned in https://github.com/Automattic/wp-calypso/issues/2234 that @gziolo preferred to close in favor of this one mean we'll need a way to retrieve such dynamic list anyway.

**Comment by janm6k** [comment]
Going through old issues, closing ones that does not look like important one.

Please feel free to reopen if applicable.
