### ISSUE TITLE
Color Schemes: navigation is unreadable on mobile for the dark color scheme

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#22337]
![94d04642-da70-459a-ae50-3b639617bd70](https://user-images.githubusercontent.com/1595739/36100815-5ed29222-0fbc-11e8-8767-b497e24453f0.png)

iOS Safari iPhone 6s Plus

**Comment by designsimply** [comment]
I tried looking for Admin Color Scheme settings in my Profile > Account settings page at https://wordpress.com/me/account but I couldn't see them there. How can I enable the dark color scheme in Calypso?

**Comment by frontdevde** [comment]
Hi @allendav,
Thanks for reporting the issue. This is a known issue as work on the Admin Color Schemes was paused midway. More details in my post "Color Schemes in Calypso, quo vadis?" (internal reference p58i-6Iy).

@designsimply The Admin Color Schemes are only available internally in pre-staging environments.
