### ISSUE TITLE
Checkout: update favorites in country lists to be smarter

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2234]
Raised by @stephanethomas 

We should make the favorite countries displayed at the top of the country lists on the domain contact information page as well as the secure payment page (in the new credit card and Paypal Express forms) *dynamic*. We could display less popular countries and instead include the following:

* The [geolocalized country](https://public-api.wordpress.com/geo/) of the user
* Any previously selected country available from the `localStorage` or a cookie
* Any country used for a previous domain registration
* Any country used for a previous payment

**Comment by gziolo** [comment]
Related to #2233.
