### ISSUE TITLE
Site Indicator Action: Disconnect sends folks to the old disconnect flow

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#22360]
When Jetpack sites lose contact, they are prompted to disconnect like this:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/1123119/36122116-748fbac4-1005-11e8-89d7-3e47fb7124ee.png">

### What it currently does:
It just opens up a modal:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1123119/36122177-a82916c8-1005-11e8-8007-bbf97b98c4ef.png">

### What it should do:
It should send folks to the disconnect flow initiated in Settings > General > Manage connection:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1123119/36122090-601c8590-1005-11e8-9e8b-2bc3b647b6a9.png">

**Comment by ockham** [comment]
Quoting myself from https://github.com/Automattic/wp-calypso/pull/22362#issuecomment-365997537:

> Note that we were deliberately not pointing that button to the Disconnect Survey, see #19491:
>
>> Personally, the one instance where I’m not entirely sure it makes sense to have the survey is the broken Jetpack indicator in the site selector scenario — what answer other than _It was broken, and I was nudged to disconnect_ do we expect?
