### ISSUE TITLE
Activity log: link to updates page from "update available" events

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#22369]
Instead of just informing about available plugin/theme updates, we should give customers a link to the page where they can take action.

For some more context, there could be also old & new versions mentioned?

<img width="496" alt="screen shot 2018-02-12 at 00 32 40" src="https://user-images.githubusercontent.com/87168/36140918-a307e9d4-10ab-11e8-8e0a-5a59d96c900c.png">

Action link probably shouldn't be there if we're about to auto-update anyway: 

![image](https://user-images.githubusercontent.com/87168/36141383-29475146-10ad-11e8-8ab1-fb9f806a32e2.png)

Here's an example of WooCommerce product event (_Flowers_ is a link):

![image](https://user-images.githubusercontent.com/87168/36141025-04febc62-10ac-11e8-8839-1b805df90625.png)

/cc @MichaelArestad

**Comment by MichaelArestad** [comment]
Yeah. That's something we are working toward with event actions. CC @keoshi

**Comment by keoshi** [comment]
@eliorivero can we link the object names to their own page, like we do with posts/pages currently?

For example, in the screenshots above:

- `Dara` would link to https://wordpress.com/theme/dara/{site-name}
- `AMP` and `AMP autoupdated to 0.6.0` would link to https://wordpress.com/plugins/amp/{site-name}

**Comment by eliorivero** [comment]
I started doing the hardest part, the update.

<img width="678" alt="captura de pantalla 2018-02-14 a la s 16 49 57" src="https://user-images.githubusercontent.com/1041600/36224784-5bac256c-11a7-11e8-9abc-476c57b6fa78.png">

Turns out it's not the hardest part, it's impossible: right now we have no way to update a theme in Calypso. See convo in p1518635555000318-slack-calypso. Should we sent users to WP Admin?

We do have a button to update plugins in Calypso. I think it would be inconsistent to have one without the other.

**Comment by keoshi** [comment]
@eliorivero Thanks for taking a stab at this. I'd suggest push the changes on the plugin and leave this open for when the themes API supports this.

Creating inconsistency is a great point, but if we can make the plugins management better right now, I say we do it. Thoughts @MichaelArestad ?

**Comment by beaulebens** [comment]
Would be good to link the plugin name to the plugin page for this site as well (as @simison kind of alluded to with the mention of Woo products where we link to them). Can definitely have that in a different PR though.

**Comment by MichaelArestad** [comment]
I'm okay with a little inconsistency at first. Let's get the update button for plugins that initiates the update without leaving the activity log. Let's also get the name to link to the individual plugin view.

**Comment by beaulebens** [comment]
@eliorivero I'm pretty sure @enejb worked on shipping an endpoint (a long time back) for themes... although now I'm not sure if it handled updates, or only installing a theme from the directory.

**Comment by enejb** [comment]
I am pretty sure we can update themes with the json api. We are just not doing it anywhere.
