### ISSUE TITLE
Free Trials: Redirect to free trial hub after checkout

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#2236]
Instead of going to the thank you page right after checkout [we have decided](https://github.com/Automattic/wp-calypso/issues/2222#issuecomment-169951126) to redirect to the Free Trial Hub and display a success notification acknowledging the successful start of the trial.

The success notice should be dismissible and display this copy:

> Hooray, you just started your 14 day free trial of WordPress.com Premium. Enjoy!

cc @breezyskies @scruffian @fabianapsimoes

**Comment by Tug** [comment]
Just a quick note: The thank you page is currently used to refresh the `sitePlans` and the `sites`. This was introduced in PR https://github.com/Automattic/wp-calypso/pull/1987.
The `sites` store poll the API so it will refresh eventually. We should check that `sitePlans` will refresh as well. See that call here: https://github.com/Automattic/wp-calypso/pull/1987/files#diff-de5361a54778da65f7d81479fce5719dR77
