### ISSUE TITLE
Activity log: link to product page instead of Reader

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#22371]
We link WooCommerce product related events to the Reader currently.

![image](https://user-images.githubusercontent.com/87168/36142362-88103258-10b0-11e8-9869-dff38a2820af.png)

![image](https://user-images.githubusercontent.com/87168/36141025-04febc62-10ac-11e8-8839-1b805df90625.png)

It doesn't make much sense to look at products through the Reader. It would make more sense to link to product's page at the site or in Calypso. 

Could link to `https://example.blog/product/:product/`
Instead of `https://wordpress.com/read/blogs/:siteId/posts/:productId`

/cc @MichaelArestad

**Comment by MichaelArestad** [comment]
I agree. Excellent suggestion.

**Comment by roccotripaldi** [comment]
We'll stick with the default 'product' url, but eventually we'll want to ensure we are using the exact product url for the given blog. Are we syncing that?

**Comment by roccotripaldi** [comment]
For now, let's not link products at all.

**Comment by gititon** [comment]
I installed Woo, setup a product, and modified a product to test this. 

As expected, the change I previously made to the post stream addressed this,

```		//Don't display link to post in Reader if post is custom post type or a draft
		if ( 'post' != $activity_log['object']['post']['type'] || 'draft' == $activity_log['object']['post']['status'] ) {
			$content = new Notification_Block( $activity_log['object']['post']['title'] );
		}
```
