### ISSUE TITLE
Activity log: handle posts without titles

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#22372]
In WordPress, it's possible to publish or save drafts without titles. Activity log events for these can be confusing and don't have an actionable link like posts with titles have.

#### Steps to reproduce
1. Start a new post at wp-admin or Calypso. Leave _Title_ empty.
2. Save post as a draft or publish.
3. Activity log looks like this:
    ![image](https://user-images.githubusercontent.com/87168/36144596-33a1191a-10b7-11e8-8004-5f500392b9c8.png)

#### What I expected
- Some grey placeholder like "(Draft)" or "Untitled" in place of the title, just like we have at posts list in Calypso:
    ![image](https://user-images.githubusercontent.com/87168/36145260-7fed2366-10b9-11e8-90eb-792fbf2b6bcf.png)
- Be able to click on something to preview/edit the post, just like I can press posts with titles.

#### What happened instead
No visible context for missing title.

/cc @MichaelArestad

**Comment by MichaelArestad** [comment]
@roccotripaldi for posts without titles, can we change the message to read:

`Untitled post - ID 1234` or something like that and still link to it?

**Comment by roccotripaldi** [comment]
> Untitled post - ID 1234 or something like that and still link to it?

Where would we link to? Editor? Preview page?

**Comment by simison** [comment]
For published post events this should happen quite rarely, but for drafts I could see this happen quite frequently (I have a habit to just start typing and come up with the title later on):

![image](https://user-images.githubusercontent.com/87168/38486557-10ee26ce-3be6-11e8-8f91-3547fa63deb0.png)

**Comment by gititon** [comment]
Deployed fix.
