### ISSUE TITLE
Activity log: no clear distinction between post status (draft, published...)

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#22373]
We bundle all post edit events under "post modified" title even when a customer just saved a _draft_.

UI at wp-admin 4.9.4:
![image](https://user-images.githubusercontent.com/87168/36145340-b86d5378-10b9-11e8-992c-9c48a9c1858e.png)

#### Steps to reproduce
1. Go to wp-admin (or Calypso post editor)
2. Create posts, publish some and modify them
3. Create posts, save them with "Pending review" status
3. Create posts, don't publish but save them as a draft. Modify those drafts (don't publish, just save)
4. Observe Activity log: most events say "Post Modified" — it's unclear if the post is a draft or a published post.

Here's a bunch of posts and drafts which are either created, edited, scheduled or marked as "pending review". It's impossible to tell which is which:

![image](https://user-images.githubusercontent.com/87168/36145164-2b6980aa-10b9-11e8-8218-1fe672e8913e.png)
(Don't mind empty titles here, I opened an issue #22372)

#### What I expected
- A clear distinction between different posts statuses (drafts, published, pending review).
- Additional information (at least visibility?)

Worth noting that in Calypso's post editor we don't speak about "drafts" but just about "saving" the post. It's only wp-admin editor terminology. 

When browsing posts in Calypso, "Drafts" is used:

![image](https://user-images.githubusercontent.com/87168/36145260-7fed2366-10b9-11e8-90eb-792fbf2b6bcf.png)

/cc @MichaelArestad

**Comment by MichaelArestad** [comment]
@keoshi Perhaps we need to signify the publish status of a post somehow? Maybe a small label or something?

**Comment by keoshi** [comment]
@MichaelArestad I don't think we have additional status coming in from the API right now.

@lezama can we do anything here to improve the semantics of the AL?

**Comment by lezama** [comment]
> @lezama can we do anything here to improve the semantics of the AL?

@simison is going to work on it 👍

**Comment by simison** [comment]
Working with these strings currently:

**Drafts**
> Page draft modified
> Post draft modified
> Testimonial draft modified
> Portfolio draft modified
> %s draft modified

**Scheduled**
> Scheduled Page modified
> Scheduled Post modified
> Scheduled Testimonial modified
> Scheduled Portfolio modified
> Scheduled %s modified

**Pending review**
> Page pending review modified
> Post pending review modified
> Testimonial pending review modified
> Portfolio pending review modified
> %s pending review modified

**Published**
> Page modified
> Post modified
> Testimonial modified
> Portfolio modified
> %s modified

Anyone specific I could ask to review them?

**Comment by lezama** [comment]
@MichaelArestad @keoshi ^^

**Comment by keoshi** [comment]
That list looks fantastic to me, @simison — thanks for doing that!

**Comment by simison** [comment]
Done in r170326-wpcom
