### ISSUE TITLE
Rewind: Auto configured credentials during Pressable NUX flow aren't saved

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22378]
#### Steps to reproduce
1. Starting at URL: https://my.pressable.com/sites
2. Create a new Pressable site.
3. Open the Pressable site settings.
4. At the top of the settings page, select the link to set up Jetpack: "To finish activating Jetpack Premium, please follow this link."
5. Connect the new site to a WordPress.com account.
6. On the "Start backing  up your site" screen, choose to share your credentials and confirm you get a success message about credentials being auto configured.
7. Finish the Pressable NUX flow.

#### What I expected

I expected my site to be set up with Jetpack, with my credentials auto configured for Rewind.

#### What happened instead

When I returned to my site's WP Admin I saw a nudge to set up Jetpack backups. Opening the site in Calypso, I saw messages that I needed to add my site's credentials. At that point, if I added my site's credentials it worked and the backups started.

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Screenshot / Video

I have a screencast of the full flow; please ping me if it would help (not sharing here as it includes private details).

Success message in Pressable NUX flow:

![screenshot 2018-02-13 13 18 15](https://user-images.githubusercontent.com/8658164/36151778-869fe3f4-10c0-11e8-9df6-8c1ce52463c5.png)

Jetpack backup nudge in WP Admin:

![screenshot 2018-02-13 13 18 38](https://user-images.githubusercontent.com/8658164/36151779-87fb15a2-10c0-11e8-9235-3e4c7bd1c745.png)

Success message after auto configuring credentials again in Calypso Security settings:

![screenshot 2018-02-13 13 19 05](https://user-images.githubusercontent.com/8658164/36151782-89eb1646-10c0-11e8-9dbf-da6944124903.png)

#### Context / Source
#manual-testing #flow-testing

**Comment by rachelmcr** [comment]
I confirmed that this is still an issue after this flow launched to production. I tried going through this flow while logged in to my site's WP Admin and without being logged in to WP Admin, and in both cases I see the success message but my credentials aren't actually saved.

@Automattic/poseidon just want to make sure this is on your radar.

**Comment by dmsnell** [comment]
The fact that we're getting the response "Your credentials have been auto configured" makes it seem like this is a problem on the back-end. @rcoll I'll poke you soon in Slack to continue investigating this

**Comment by rcoll** [comment]
Just tried again as a non-a11n and it went through fine.

For anyone able to reproduce, please do the following for me when you have a moment:

1. When you get to the screen in the NUX flow that has the "Share credentials" button, please open the network tab. 
2. Clear out anything that's already there, and then hit the "Share credentials" button. 
3. I'm interested in the Request and Response details for two specific requests, labeled `activate` and `rewind`.
4. I'm mainly interested in the responses for those two requests. Please share them here and we can figure out what's going on :-)

Thanks.

**Comment by rachelmcr** [comment]
I reproduced the issue (site ID 143321501). Here's the response for the `activate` request:

```
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"ok":true,"error":"","rewind_state":{"can_autoconfigure":true,"state":"awaiting_credentials","downloads":[],"last_updated":"2018-02-26T19:36:17.513+00:00"}}}
```

Here's the response for the `rewind` request:

```
{"body":{"can_autoconfigure":true,"state":"awaiting_credentials","downloads":[],"last_updated":"2018-02-26T19:36:18.430+00:00"},"status":200,"headers":{"Allow":"GET"}}
```

**Comment by rcoll** [comment]
That's beautiful, thanks so much. Definitely indicative of a problem. I'll take a look at this with @dmsnell shortly.

**Comment by rcoll** [comment]
Howdy all, I have a solution for this but don't want to ship and go AFK for the night. The fix is on the VP side, and likely requires no action in Calypso or WPCOM. I'll ship first thing in the morning.

**Comment by rcoll** [comment]
The fix has been deployed. Please test and let me know the results. Thanks all!

**Comment by rachelmcr** [comment]
@rcoll Looks good to me!

I'm still occasionally getting a failure, but no longer seeing the erroneous "Your credentials have been auto configured" success message in those cases. (I think it may be a timing issue — connecting too soon after creating the Pressable site — but I'll investigate an open an issue for the back end if I can reliably reproduce those failures.)
