### ISSUE TITLE
Rewind: Don't send users to manual credentials flow if they can auto configure credentials

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22380]
#### Steps to reproduce
1. Starting at URL: https://my.pressable.com/
2. Create a new Pressable site.
3. Open the Pressable site settings.
4. At the top of the settings page, select the link to set up Jetpack: "To finish activating Jetpack Premium, please follow this link."
5. Connect the new site to a WordPress.com account.
6. On the "Start backing  up your site" screen, skip sharing your credentials.
7. Finish the Pressable NUX flow and return to your site's WP Admin.
8. In WP Admin, click the "Set Up" button in the Jetpack Backups nudge.

#### What I expected

I expected to see an option to have my credentials auto configured, similar to the NUX flow I went through.

#### What happened instead

I was sent to `/start/rewind-setup/rewind-add-creds` where I had to add my credentials manually. I copied my SFTP credentials from the Pressable dashboard (hard to find unless you know where to look) but adding my credentials there still failed — probably because I didn't mess with the advanced settings.

I then left that flow and went to the Activity Log, which directed me to my site's Security settings with a prompt to auto configure my credentials. That worked and should have been where I was directed from the beginning.

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Screenshot / Video

I have a screencast of the full flow; please ping me if it would help (not sharing here as it includes private details).

Jetpack Backups nudge in WP Admin:

![screenshot 2018-02-13 13 18 38](https://user-images.githubusercontent.com/8658164/36151973-412d6bb0-10c1-11e8-90bc-2188d0f82b4d.png)

Nudge directed me to this screen:

![screenshot 2018-02-13 12 43 45](https://user-images.githubusercontent.com/8658164/36151998-57af13c0-10c1-11e8-9ab5-54e0a7780e73.png)

Manual credentials flow:

![screenshot 2018-02-13 12 43 49](https://user-images.githubusercontent.com/8658164/36152007-5e635a00-10c1-11e8-8ff6-835c6639e578.png)

Option to auto configure in Security settings:

![screenshot 2018-02-13 12 48 05](https://user-images.githubusercontent.com/8658164/36152157-df9f71bc-10c1-11e8-8d1c-d002aba3e0e9.png)

#### Context / Source
#manual-testing #flow-testing

**Comment by eliorivero** [comment]
Thanks for the report. Fix pending review in #22396
