### ISSUE TITLE
Guided Tours show up again and again, can't dimiss

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#22386]
#### Steps to reproduce
1. Open incognito window
2. Open Site Pages: https://wordpress.com/pages
2. Click a page title to open it in the editor

#### What I expected
To not keep showing me the guided tour of "Welcome to the editor! Add a title here."

#### What happened instead

If you sign out / close incongito window and sign in again, it'll still show the guided tour of individual pages, first asking you to add the page title.

This is shown when you come back to a page:

<img width="956" alt="screen shot 2018-02-13 at 7 24 06 pm" src="https://user-images.githubusercontent.com/6505293/36154661-f3814fe8-10f3-11e8-9eb3-7b4c29c05e07.png">

#### Browser / OS version
Chrome latest, macOS Sierra

#1795499-hc

**Comment by aportbury** [comment]
Another report in #1792090-hc, although this time it's only in the post editor, not the page editor. The message appears each time the editor window is opened.

**Comment by psealock** [comment]
The API for saving preferences is not functioning correctly. Fix being discussed in https://github.com/Automattic/wp-calypso/issues/22462
