### ISSUE TITLE
Rewind: Error entering site credentials automatically starts new chat

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22393]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/rewind-setup/rewind-add-creds
2. Select "Add your credentials"
3. On the "Site credentials" screen, enter incorrect credentials for your site.
4. Wait for the error message: "We looked for `wp-config.php` in the WordPress installation path you provided but couldn't find it."
5. Close the error message without clicking on the "Get help" link.

#### What I expected

I expected to close the error message and go back to resolving the issue with the site credentials I had entered.

#### What happened instead

A new support chat was started, even though I didn't ask for help. This was confusing to me because 1) I hadn't intentionally initiated the chat and 2) I heard the noise indicating a new message but the chat box didn't automatically appear on screen — I had another tab open where the chat icon had appeared in the sidebar.

The same thing happened when I later opened my site's Security settings at https://wordpress.com/settings/security and entered incorrect credentials there.

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Screenshot / Video

![screenshot 2018-02-13 12 46 28](https://user-images.githubusercontent.com/8658164/36159918-d4b28f76-10d7-11e8-9c12-38d929e69de6.png)

#### Context / Source
#manual-testing #flow-testing
Seen after following the Jetpack call to action in my site's WP Admin dashboard. See also: https://github.com/Automattic/wp-calypso/issues/22380

**Comment by eliorivero** [comment]
This was fixed in https://github.com/Automattic/wp-calypso/pull/22397
