### ISSUE TITLE
Activity Log: Two Post Modified events when saving a Post

### ISSUE THREAD

**Issue by lezama** [Automattic/wp-calypso#22402]
**When using Gutenberg!**

![image](https://user-images.githubusercontent.com/104869/36171186-68c892ca-10e0-11e8-9fb1-f78fda096bbc.png)

**Comment by lezama** [comment]
https://github.com/Automattic/jetpack/pull/8833 should improve this

**Comment by roccotripaldi** [comment]
@lezama and @enejb - please verify that this is fixed, and close. Thanks!

**Comment by lezama** [comment]
I couldn't reproduce, closing for now
