### ISSUE TITLE
Signup: Improve suggested usernames.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#22419]
On the Create Your Account step, seeing a suggested username like "toms-diner87239482739487" is not very inspiring. There _are_ some better variations possible (I've seen `[domain name]online` suggested), so this needs some investigation into what is currently in use.

**Comment by scruffian** [comment]
One option would be to ask users to supply a display name and then generate a username based on that - this has the advantage of also setting a display name for users, which probably most want.

**Comment by scruffian** [comment]
Still relevant to the best of my knowledge

**Comment by razvanpapadopol** [comment]
Let's keep this on hold since we're looking to remove the username input field in https://github.com/Automattic/wp-calypso/issues/52852
