### ISSUE TITLE
Editor: Contact Form: add a number field type

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22423]
Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Pages > Add > Contact Form.
1. Try to add a number form field.

<strong>Result:</strong> there isn't an option to add a number field type.

![screen shot 2018-02-13 at tue feb 13 5 16 33 pm](https://user-images.githubusercontent.com/1119271/36181365-cd6158f6-10e1-11e8-90a0-52219ab90ca2.png)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/7618 using Firefox 58.0.2 on macOS 10.13.3.</sup>

#dogfooding feedback:

<blockquote>No “number” field feels weird, even though I know I can do it using a “text” field (we’re using HTML terminology, when a normal person probably expects a field for a number, and a field for text, to be different).</blockquote>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by arunsathiya** [comment]
Reopening because this is not available yet. I second the idea of having a specific number field as well. Especially for questions like, "How many do you need?"
