### ISSUE TITLE
Site Creation: Prefill the domain name at step 3 with the site name inserted in step 1.

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#22422]
As noted by @Copons we think there is a high overlap of folks who would like the same domain name as their site name. Let's abtest if this increases the completion rate of this step.

**Comment by klimeryk** [comment]
cc @lucasartoni in case it was something that you wanted to test too as part of Kracken.

**Comment by gwwar** [comment]
Related PR is #22376

**Comment by Copons** [comment]
Closing because #22376 shipped.
