### ISSUE TITLE
Signup: show Trampoline and its "Welcome to WordPress.com" earlier

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#22421]
When Trampoline (the original main Guided Tour) was introduced, users fresh from signup were dropped on to the front-end of their site, triggering Trampoline right away – the user was welcomed to WordPress.com, and could then proceed with the tour.

![screen shot 2018-02-13 at 3 53 59 pm](https://user-images.githubusercontent.com/349751/36180684-48ffb400-10d6-11e8-9f87-dcb257acb721.png)

We now drop people in any variety of places after completing signup, at least some of which are not the front-end (`/post` is one example of a post-signup landing screen). Add to this that it's sometimes difficult for a user to get to the front-end of their site, and it might be 10-, 20 minutes or days before they trigger trampoline – and are welcomed to WordPress.com, even though they've been engaging with us for many screens.

Maybe Trampoline can be triggered earlier, depending on current post-signup landing destinations, or maybe we can also improve visibility of View Site/Visit Site. We'll need to chat with design.

**Comment by alisterscott** [comment]
We are planning to show the checklist as the entry point for a new site - does this issue/enhancement make sense in the context of that? @kwight

**Comment by kwight** [comment]
I don't believe Trampoline is an actively developed thing any more, and almost (if not all) signup is going through Gutenboarding, which consistently drops users into the editor with the homepage loaded.
