### ISSUE TITLE
Checklist for domain only users

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#22425]
Let's give folks next steps after they have purchased a domain, starting from https://wordpress.com/domains/

For examaple explaining how to use the domain, or next steps on creating a site.

**Comment by klimeryk** [comment]
It's very rudimentary, but we do show this screen:

<img width="716" alt="Screenshot 2021-02-02 at 13 57 56" src="https://user-images.githubusercontent.com/3392497/106610429-b0a70880-655e-11eb-8744-21e06c27d45e.png">

It has quicklinks to the most important things - creating a new site with this domain and adding email (plus regular domain management).
