### ISSUE TITLE
Editor: some types of code removed when added in the code shortcode

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#22432]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Create a new post, and use the [code] shortcode to add this code:
```
<div data-spotim-module="recirculation" data-spot-id="sp_XXXXXXXX"></div>

<script src="https://randomdomain.com/spot/sp_XXXXXXXX"></script>
<script src="https://randomdomain.com/deferred/bundle.js" data-spotim-module="deferred-launcher" data-spot-id="sp_XXXXXXXX" data-post-id="POST_ID_HERE"></script>
```
3. Publish the post.

#### What I expected
For the published post to display the code exactly as I entered it, but using the syntax highlighter.

#### What happened instead
All the code was stripped out, and all that appeared in the post were an empty div-tag with no attributes. 

![edit_post_ _kokkiestrialtestsite_ _wordpress_com](https://user-images.githubusercontent.com/11873759/36195149-387d4684-1175-11e8-9bd5-2c885644ff85.png)

If I leave the editor, and then edit the post again, the code has disappeared from the editor as well...

![edit_post_ _kokkiestrialtestsite_ _wordpress_com](https://user-images.githubusercontent.com/11873759/36195433-1e6ffe16-1176-11e8-8b69-6814b5a72898.png)

...while in the HTML view in the editor the post content has changed to:

```[code language="text"]</pre>
<div></div>
<pre>
[/code]
```

I was also able to replicate this using only an empty div-tag with the `draggable` and `tabindex` attributes (did a random spot-check). Using an `id` and `style` attribute on an empty div works correctly, so it looks like the attributes might be causing a problem here.

If I tried using only the `script` tags in the example code they were also stripped out and the published post contained an empty code block.

Changing the syntax highlighter language does not appear to make a difference.

The same code embeds fine if added via the WP-Admin editor, but the moment the post is updated in Calypso the same thing happens.

#### Context / Source

Reported by a user in 890602-f

**Comment by molszewska** [comment]
I came across a similar issue. While using the following code snippet in Calypso's Visual editor:

> [code lang=csharp] 
> Expression<Func<User, bool>> pre1 = u => u.FirstName != null; 
> Expression<Func<User, bool>> pre2 = u => u.MiddleName != null; 
> Expression<Func<User, bool>> pre3 = u => u.LastName != null; 
> [/code]

the output misses out `<User, bool>` part : http://cld.wthms.co/S5NVty

The code snippet looks great when backticks are used instead: http://cld.wthms.co/eKkr3x or when [code] shortcode is entered via wp-admin: http://cld.wthms.co/47Idhk

The option “Use Markdown for posts and pages” was turned on in wp-admin while testing.

Reference ticket: 957774-zen

**Comment by gemmagarner** [comment]
Code snippets have been lost when switching between visual and HTML editors.

https://twitter.com/andyinthecloud/status/968035692730175488

**Comment by gemmagarner** [comment]
Report of code being removed when it is previewed: https://twitter.com/tylerrinker/status/970305124131377152

**Comment by molszewska** [comment]
missing out library names in C language 1017216-zen

**Comment by dcoleonline** [comment]
Similar report with `<meta>` elements being stripped from Calypso, but working fine in wp-admin. 1082075-zen

Example:

```
[code language="html"]

This is some text above a meta element.

<meta itemprop="url" content="{{ shop.url }}{{ product.selected_or_first_available_variant.url }}">

This is some text below a meta element.

[/code]
```


When that is added to Calypso, only this is left in the editor after updating/publishing:


```
[code language="html"]

This is some text above a meta element.



This is some text below a meta element.

[/code]
```

**Comment by rachelmcr** [comment]
Similar report of code being removed in the r language: 2717122-hc / 1098954-zen (original report in 8039-wpcom).

Sample code added to the editor:

```
[code language="r" gutter="false"]
shift.vec <- function (vec, shift) {
  if(length(vec) <= abs(shift)) {
    rep(NA ,length(vec))
  } else{
      if (shift >= 0) {
        c(rep(NA, shift), vec[1:(length(vec)-shift)])
      } else {
        c(vec[(abs(shift)+1):length(vec)], rep(NA, abs(shift))) }
  }
}
[/code]
```

This part of the above code is stripped:

```
<= abs(shift)) {
    rep(NA ,length(vec))
  } else{
      if (shift >
```

I confirmed that the shortcode works as expected in WP Admin; it's only altered in the Calypso editor.

**Comment by elli-shaklee** [comment]
Another very short way to replicate it:
`[code language="java"]
set<string> strings;
[/code]`

**Comment by etsz** [comment]
Another short way to replicate:
```
[code language="java"]
set<string> strings;
[/code]
```
After preview/save becomes
```
[code language="java"]
set strings;
[/code]
```

**Comment by adamleone** [comment]
Hello there, 

A similar issue has cropped up with this ticket here: https://woothemes.zendesk.com/agent/tickets/1403757

Advised to use wp-admin view to use shortcode for the time being

**Comment by adamleone** [comment]
Hello there,

A similar issue has cropped up with this ticket here: zen-1403757

Advised to use wp-admin view to use shortcode for the time being

**Comment by KristinaKay** [comment]
> Hello there,
> 
> A similar issue has cropped up with this ticket here: zen-1403757
> 
> Advised to use wp-admin view to use shortcode for the time being

Using WP-Admin, in this case, does not help.

Ussing [code][/code] and Markdown for code in both Calypso (HTML Editor) and in WP-Admin doesn't work. The < >’s are being turned into `&lt;` and `&gt;`.  

I was able to reproduce this in both Calypso and in WP-Admin.

```The key insight here, and it took me a while to see it, is that the roll angle we want is the angle between the two rods in that picture. To rotate to that angle, we want the `rotation` between those two rods. If the given normal in the input data is in the variable `norm`, then we want `llRotBetween(<0,1,0>,norm)`. Why? Because the y-face normal of the transparent cube is `<0,1,0>`, because it sticks straight out in the Y direction.```

When publishing it returns this:

![image](http://cld.wthms.co/2VSpIr+)

**Comment by gemmagarner** [comment]
Another report in 1505847-zen

Recommend using wp-admin for now.

**Comment by adamleone** [comment]
Another report in 1793790-zen 

Recommend using wp-admin or code block.

**Comment by cecilearkay** [comment]
I had a similar issue using with the` <pre>` `</pre>` tags, in #10418579-hc
