### ISSUE TITLE
Domains: Searching for registered domains sometimes shows the domain as taken *and* recommended

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22440]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add
2. Select a site.
3. Search for a registered domain ending in `.com`.
4. Search for a registered domain ending in `.co`, `.uk`, or `.co.uk`.

#### What I expected

I expected searching for any registered domain to return a message that the domain is taken, with other recommended domains below it. That's what I saw when searching for a registered `.com` domain:

![screenshot 2018-02-14 13 49 49](https://user-images.githubusercontent.com/8658164/36207496-09c29ea2-118e-11e8-84dd-299c34777aff.png)

#### What happened instead

For TLDs such as `.co`, `.uk`, or `.co.uk`, I saw the message that the domain was taken _as well as_ the same domain recommended in the list below that message. (I also noticed that the styling on the "[domain] is taken" message was different for different TLD searches.)

This issue only seems to occur when adding a domain while logged in to WordPress.com. I don't see the same issue while going through the signup flow at https://wordpress.com/start

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Screenshot / Video

![screenshot 2018-02-14 13 43 37](https://user-images.githubusercontent.com/8658164/36207572-49634764-118e-11e8-9130-2f5d074f71c2.png)
![screenshot 2018-02-14 13 43 58](https://user-images.githubusercontent.com/8658164/36207573-4ac86b02-118e-11e8-86b1-71c9e42714e3.png)
![screenshot 2018-02-14 13 44 06](https://user-images.githubusercontent.com/8658164/36207574-4bb23994-118e-11e8-84c3-51e8af6cd177.png)

#### Context / Source
#dogfooding

**Comment by aidvu** [comment]
@rachelmcr IIRC, we do not support transfer-ins for these TLDs yet. :)

**Comment by rachelmcr** [comment]
> IIRC, we do not support transfer-ins for these TLDs yet. :)

Ah, is that the reason for the different message styling? That makes sense, but it doesn't explain why we're offering the domain as a recommended domain registration right below the message saying that the domain is already taken.

**Comment by aidvu** [comment]
Owww... I now see it. 🤦‍♂️

**Comment by KokkieH** [comment]
This appears to still be happening in the new iteration of domain search. A customer came into chat today in 3390032-hc wanting to register tomorrow.art. Whois shows the domain not registered, but various registrars show it as unavailable, so I'm guessing it's registry-reserved. However, searching for it at My Site ->Domains ->Add shows it as both taken and "Best Match". Selecting it under "Best Match" leads to an error message that the domain is no longer available:

<img width="614" alt="domain_search_ _kokkiestrialtestsite_ _wordpress_com" src="https://user-images.githubusercontent.com/11873759/39697522-199df48e-51e9-11e8-8684-022a8941cd65.png">

Props @agepeuve for the report.

**Comment by deancroyal** [comment]
Similar result here for user in chat [5679323-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=5679323).

They originally wanted `vea.ca`, and here was the result they saw when trying to add it via My Site > Domains > Add 

<img width="570" alt="screen shot 2018-08-13 at 8 47 03 am" src="https://user-images.githubusercontent.com/13387217/44042585-7ecbcea6-9ed5-11e8-8aa3-92eadda74f30.png">

At other registrars the domain appears as taken. Whois doesn't display any data for the domain.
