### ISSUE TITLE
Editor: Contact Form: add a customizable thank you message shown after a form is submitted

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22447]
Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Pages.
1. Add a page with a form and publish it.
1. View the page and fill out and submit the form.
1. Observe whether there is a thank you message.

<strong>Result:</strong> after submitting a form, a "Message Sent (go back)" message is displayed as well as dump of all the form details submitted. A thank you message is not displayed, and there is not a way to add a custom thank you message in the contact form settings.

![screen shot 2018-02-14 at wed feb 14 10 00 51 am](https://user-images.githubusercontent.com/1119271/36217260-37a32a96-116e-11e8-999f-e1fcd5c81618.png)
<sup>Seen at https://design5279.wordpress.com/contact-form-test/?contact-form-id=7618&contact-form-sent=11834&_wpnonce=a58aaf4a0f#contact-form-7618 using Firefox 58.0.2 on macOS 10.13.3.</sup>

For reference, here is what the contact form settings currently look like:

![screen shot 2018-02-14 at wed feb 14 10 01 05 am](https://user-images.githubusercontent.com/1119271/36217267-3ad50630-116e-11e8-86b2-96e35141b946.png)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/7618 using Firefox 58.0.2 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by rachelmcr** [comment]
We've also had 23 reported support requests for a feature like this (internal ref: pKdGS-DZ-p2)

**Comment by alisterscott** [comment]
Would this belong in Jetpack since it's a contact form feature (that would be displayed on the front end of the site)?

**Comment by beaulebens** [comment]
It's probably a bit of both, and the code that powers Jetpack's Contact Form is the same code that powers WP.com's, so... it's one of those grey areas as to where we should actually track it :)

**Comment by alisterscott** [comment]
> It's probably a bit of both, and the code that powers Jetpack's Contact Form is the same code that powers WP.com's, so... it's one of those grey areas as to where we should actually track it :)

Thanks, I also mean we'd want to make sure that all Jetpack sites would benefit as well

**Comment by arunsathiya** [comment]
This is not available yet. I am reopening this issue for improved discoverability. In case this is needed by any users, Happiness Engineers can discover this issue better and chime in with the users' experiences/needs.
