### ISSUE TITLE
Activity Log: Bunch similiar events for draft posts

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#22451]
When using Gutenberg to write a post, it saves a lot of revisions ( see https://github.com/WordPress/gutenberg/issues/3656 ). On our end, we have an activity log point displayed for every single revision to this draft post. 

For me, in writing a post over 45 minutes, it resulted in 40ish log items _before_ the post was published.
![2018-02-14 at 12 05](https://user-images.githubusercontent.com/88897/36220271-9b4a78c2-117f-11e8-86fc-95dd4dd33220.jpg)

**Comment by roccotripaldi** [comment]
I believe the Gutenberg folks have resolved this. Let's re-open if this still pops up.
