### ISSUE TITLE
API: cannot save preferences

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#22462]
After speaking with a user in chat, they claim that the “See How Your Site Is Performing” dialog box on the stats page always appears when they log in, despite the “Don’t show this again” setting checked.

Here’s the screenshot: 

![](http://cld.wthms.co/339JOP+)
http://cld.wthms.co/339JOP

#### Steps to reproduce

I have been unable to reproduce as I don't see the dialog box on my personal sites. I'm wondering if this is a new pop-up, rolled out for only some sites.

#### What I expected

The user expects that if the "Don't show this again" is checked off, that the box won't be shown again. They seem to get it every time, though.

Reported by a user in 1807555-hc 
Follow-up ticket: 959437-zen

**Comment by rachelmcr** [comment]
I can reproduce this issue with a new user signup. After signing up for a new account/site, I visited My Sites > Stats and saw the message. When I dismissed it, it made a request to the endpoint `https://public-api.wordpress.com/rest/v1.1/me/preferences?http_envelope=1` with the payload `{"calypso_preferences":{"firstViewHistory":[{"view":"stats","timestamp":1518701879547,"disabled":true}]}}`.

However, that request received this error response:
```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"invalid_input","message":"No preferences were provided for the endpoint to set."}}
```

When I refreshed the page, the message reappeared unexpectedly.

It doesn't look like this component has been modified recently, so this issue is likely caused by another change:
https://github.com/Automattic/wp-calypso/tree/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/components/first-view

**Comment by designsimply** [comment]
Tested and confirmed that dismissing the "See How Your Site Is Performing" dialog box with the "Don't show this again" option checked doesn't work to disable the dialog box after logging out and back in again when using a new account (user895 registered 2018/02/14) but that I never see the dialog box when using an older account (madefortesting554 registered 2016/09/29). 

Video: [3min](https://cloudup.com/cJiibLiGzo2)
<sup>Tested with Firefox 58.0.2 and Safari 11.0.3 on macOS 10.13.3 with account user895 registered on 2018/02/14.</sup>

Steps to reproduce:

1. Go to https://wordpress.com/ and sign up for a new account.
1. Go to My Sites > Stats.
1. You should see the "See How Your Site Is Performing" dialog box appear.
1. Check the "Don't show this again" option.
1. Click the "Got It!" button.
1. Log out.
1. Log in.
1. Go to My Sites > Stats.
1. Check to see if the "See How Your Site Is Performing" dialog box appears again.

Result: the "See How Your Site Is Performing" dialog box appears even after it is dismissed when you log out and log back in again and I can confirm the preference fails to save with `error: invalid_input` for the API call @rachelmcr noted above ([screenshot](https://user-images.githubusercontent.com/1119271/36320091-3f9b8938-1302-11e8-88cc-2eb460aef85a.png)).

`{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"invalid_input","message":"No preferences were provided for the endpoint to set."}}`

**Comment by rachelmcr** [comment]
Looking at this again, it seems like there's a more general problem with the `savePreference` method in the Calypso Preferences store (although that hasn't changed recently either, so perhaps something changed in the API?):
https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/state/preferences/actions.js#L81

That also controls whether Guided Tours should appear, which was reported as a new issue:

https://github.com/Automattic/wp-calypso/issues/22386

And I have the same issue (the dialog box keeps coming back, same error saving the preference) when trying to dismiss the media modal gallery instructions in the editor — also controlled by the Preferences store:

<img width="1440" alt="screenshot 2018-02-16 17 27 51" src="https://user-images.githubusercontent.com/8658164/36320678-deb02e8e-133e-11e8-9cbf-2bb3cd62bf13.png">

**Comment by samouri** [comment]
I agree with @rachelmcr -- i did some diggint too and came to the same conclusion.  I  think all calls to `savePreferences` are failing which probably means there are a lot of weird bugs happening right now because of it

**Comment by psealock** [comment]
Thanks for the thorough poking around @rachelmcr and @designsimply. That was very helpful for getting started.

I have a backend fix in D10297. It works, but I need some further input.

**Comment by psealock** [comment]
## Testing Shortcut
You can test the preferences API endpoint without re-creating a new user:
* As a test user visit http://calypso.localhost:3000/stats/reset-first-view
* See Network POST request to `/me/preferences` return 400
