### ISSUE TITLE
Signup: the phrase "map it" can be confusing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22470]
Steps to reproduce:

1. Go to https://wordpress.com/start
1. Click "Continue."
1. Type in any custom domain name.
1. Scroll to the end of the domain suggestions.

<strong>Result:</strong> there is a option to "Map It" at the end as well as the following text:

<blockquote>Already own a domain?

Map this domain to use it as your site's address.</blockquote>

Feedback from a #dogfooding session:

<blockquote>What does “Map it” mean? Does that just mean “Use it”?</blockquote>

![screen shot 2018-02-14 at wed feb 14 4 00 44 pm](https://user-images.githubusercontent.com/1119271/36232828-80f07b86-11a0-11e8-8f7f-5c7e3cc01a37.png)
<sup>Seen at https://wordpress.com/start/domains using Firefox 58.0.2 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by benhuberman** [comment]
I wonder if expanding just a bit in the first instance would make the button CTA clearer? 

e.g.:
> Already own a domain?
> You can map an existing domain to use it as your site's address.

**Comment by aidvu** [comment]
@designsimply we're changing that for good, as it's going to be replaced with `Already Own A Domain`, with transfer-in as the main action.

**Comment by ranh** [comment]
I'm closing this since the recent launch of the domain transfers in during NUX changes the prompt from "map it" to "use a domain I own". This is what I see now:

<img width="988" alt="ranimac3 screenshot 2018-02-19 at 18 55 21" src="https://user-images.githubusercontent.com/426518/36389060-91de36a4-15a6-11e8-8ada-835aaa2f97a3.png">
