### ISSUE TITLE
Editor: Can't add tags containing the Hebrew letter ת

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#2250]
A user [wrote in](https://en.forums.wordpress.com/topic/problem-with-adding-new-tags) with this issue:

"When the new tag includes the Hebrew letter ת, the new editor thinks it is the end of the tag and wouldn't let me go on printing the rest of the letters. This Hebrew letter ת is to be found exactly where the English comma is on the keyboard."

**Comment by ralder** [comment]
duplicate #740
