### ISSUE TITLE
Privacy: Provide a means for an atomic site owner to notify all users of a breach

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#22512]
The minimum solution will allow the site owner to compose and send an email to each (impacted) user informing them of the breach.

Related GDPR articles: 34

#needsdesign cc @hollyannehogan @kellychoffman @jameskoster

**Comment by allendav** [comment]
Not necessary for May '18. Other issues should have priority.

**Comment by jameskoster** [comment]
A lofi design for this can be found on the "Privacy settings" page in this Sketch file; https://www.dropbox.com/s/jgj38byfkt9o1w3/GDPR.sketch?dl=0

**Comment by allendav** [comment]
On further reflection, and after discussing with @timmyc - I'm broadening the scope of this issue beyond stores and to wordpress.com atomic sites in general - after all a merchant has an analog with a site owner and a customer has an analog with a site visitor/user (e.g. commenter).
