### ISSUE TITLE
Privacy: Provide a means for a site owner to update (rectify) a user's personal data

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#22513]
Depends on #23137 

Tasks

- [ ] decide if this just applies to commentors and woocommerce customers
- [ ] decide how to handle users that also have a WordPress.com account
- [ ] add the means for an admin to edit the personal data presented in their user's detail view
- [ ] decide whether or not we need to implement bulk order update (i.e. update a customer's personal info across multiple orders) for woocommerce orders
- [ ] if so, make sure we can fetch and bulk-update orders for a specific registered customer or, in the case of no-priv customers, for a specific email address

The minimum solution should consider allowing the site owner to update user’s personal data including the following:

    - first name
    - last name
    - email

If the user is a woocommerce customer, then also consider:

    - shipping address
    - billing address
    - phone number

The ideal solution might also allow the merchant to update the customer’s name, email, shipping and billing addresses and phone number in multiple orders at once. (Note: We already can update those fields in individual orders in calypso.)

Related GDPR articles: 16

#needsdesign cc @hollyannehogan @kellychoffman @jameskoster

**Comment by jameskoster** [comment]
A lofi design for this can be found on the "Customers section" page in this Sketch file; https://www.dropbox.com/s/jgj38byfkt9o1w3/GDPR.sketch?dl=0

**Comment by allendav** [comment]
On further reflection, and after discussing with @timmyc - I'm broadening the scope of this issue beyond stores and to wordpress.com users in general - after all a merchant has an analog with a site owner and a customer has an analog with a site visitor/user (e.g. commenter).
