### ISSUE TITLE
Privacy: Provide a means for a site owner to provide a copy of collected personal data to a user

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#22510]
Depends on  #23137

Tasks

- [ ] consider how this applies if a user is also a WordPress.com user
- [ ] add a means for our site owner to request confirmation of the request from the user
- [ ] add a means to export the user's personal data
- [ ] for atomic sites, determine what to do about personal data managed by jetpack, woocommerce, 
and any plugins, extensions

The ideal solution will
- assemble data across different silos (e.g. customer profile, order data, reviews)
- combine the data in a single file that can be emailed to the customer’s email address
- use the exporter in WordPress core

Related GDPR articles: 15

#needsdesign cc @hollyannehogan @kellychoffman @jameskoster 

Related: https://github.com/woocommerce/woocommerce/issues/19277

**Comment by allendav** [comment]
If our user used a WooCommerce Services shipping label to ship their package to their customer, we will probably also need to be able to export:

- tracking number
- archived label (this will be interesting)

cc @nabsul @jeffstieler

**Comment by jameskoster** [comment]
A lofi design for this can be found on the "Flow - send personal data" page in this Sketch file; https://www.dropbox.com/s/jgj38byfkt9o1w3/GDPR.sketch?dl=0

**Comment by allendav** [comment]
On further reflection, and after discussing with @timmyc - I'm broadening the scope of this issue beyond stores and to wordpress.com sites in general - after all a merchant has an analog with a site owner and a customer has an analog with a site visitor/user (e.g. commenter).
