### ISSUE TITLE
Privacy: Provide a means for a site owner to erase a user’s personal data

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#22511]
Depends on: #23137

Tasks:

- [ ] decide how this applies (if at all) if the user is also a WordPress.com user
- [ ] add a means for the admin to request confirmation from the user
- [ ] add a means to remove the user's personal data from the site and optionally remove the user too
- [ ] for atomic sites, determine what to do about personal data managed by jetpack, woocommerce and plugins/extensions

The minimum solution should consider supporting anonymizing personal data in a user's

 - profile
 - posts?
 - media uploads?
 - comments?
 - woocommerce orders
 - woocommerce product reviews

including the following

 - first name
 - last name
 - email
 - shipping address
 - billing address
 - phone number
 - IP address

Related GDPR articles: 17

#needsdesign cc @hollyannehogan @kellychoffman @jameskoster

**Comment by allendav** [comment]
If our user used a WooCommerce Services shipping label to ship their package to their customer, we will probably also need to be able to redact/delete:

- tracking number
- archived label

cc @nabsul @jeffstieler

**Comment by jameskoster** [comment]
Take a look at the "Flow - ..." pages in https://www.dropbox.com/s/jgj38byfkt9o1w3/GDPR.sketch?dl=0 for the different designs related to deleting data

**Comment by allendav** [comment]
On further reflection, and after discussing with @timmyc - I'm broadening the scope of this issue beyond stores and to wordpress.com atomic sites in general - after all a merchant has an analog with a site owner and a customer has an analog with a site visitor/user (e.g. commenter).
