### ISSUE TITLE
Activity Log: Pressable credentials flow typo

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#22545]
<img width="669" alt="screen shot 2018-02-16 at 12 53 26 pm" src="https://user-images.githubusercontent.com/437258/36321658-82b9656c-1318-11e8-9737-c0134eb1860c.png">

A space is missing between `you.Finish`

To reproduce, 
Set up a new Pressable site
Agree to share credentials
See the confirmation screen
See the missing space

**Comment by anotheredward** [comment]
Hi, I've submitted a PR to fix this issue :)
