### ISSUE TITLE
Store: New promotions display on the last page

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#22550]
This was logged at p90Yrv-m0-p2, but still seems to be an issue:

> When I add a promotion, I don't see it on the list. At first I thought it didn't get added, but then I found it at the bottom of the second page. It shows the oldest added products first. It should show me the newly added promotion first.

Related: #21427. Though I think we should update the ordering of this in the meantime while we figure out a way to better visually highlight new rows (cc @kellychoffman)

@coderkevin

**Comment by kellychoffman** [comment]
Big plus one. 

> better visually highlight new rows

Can we also use what we do in Orders with the light blue background? Except in this case the background would fade away after a couple seconds.

**Comment by justinshreve** [comment]
Since we are going to send users to the update view of a promotion after creation, instead of the listing page, I think it's OK to keep ordering as is (by expiration date).
