### ISSUE TITLE
Jetpack plugins: confusing bulk editing (auto-update, status messages)

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#2256]
I swear I tried searching for like 5 mins before posting this.

I arrived at the Plugins page for a Jetpack site today and thought I'd make all plugins auto-update since I hadn't gotten around to doing it in the prompt in wp-admin just yet. I activate a few manually but get tired of it, anyway, so I hit "Edit All".

So here are my thoughts!

<img width="806" alt="screen shot 2016-01-09 at 02 51 18" src="https://cloud.githubusercontent.com/assets/3073557/12213704/64725a4a-b67d-11e5-976a-d25c45a247ad.png">
"Edit All" to me sounds like enabling it will alter all available items. Turns out it's really just enabling a Bulk Edit mode. And here I was, expecting a wizard of some kind! Strike one sirs and madams.

I would suggest just selecting all if you hit "Edit All".. it's easy enough to unselect items if you need to and most likely you did want to do something to all of them if you hit that button. ;)

<img width="986" alt="screen shot 2016-01-09 at 02 52 44" src="https://cloud.githubusercontent.com/assets/3073557/12213711/c289b1be-b67d-11e5-85df-54737562d446.png">
So I turned on autoupdates for all remaining plugins that I had, but the Notice used in this way seems strange: it displays a line log of the commands it's doing, but there's no reference? Does each message dismiss each other or are there X stacked Notices on top of each other by the end? What if there was an error with one of them, how would I know? Would there be a way to go back or would the cycle just break then? Seems half-baked.

I also had 10+ plugins in that list and after a while I stopped seeing the autoupdate check being turned on since this activity was out of view below the fold. I almost expected the page to scroll for me, I have to say! In fact, if it did, maybe status messages wouldn't even be needed: scroll to keep activity within view to show what's going on, and upon completion, however far down the page you are, show an overlaying Notice with a success message. That's pretty much what I would expect from this UX TBH.

3rd thing on the update process: the screenshot shows what it looks like when the process had completed. It's, again, not what I expected since the "Edit All" overlay bulk edit thingie seemed highly temporary and in fact just seemed to overlay the filter bar for the container, it would seem as if when the one task you selected to perform on "All", it would dismiss itself and return to the initial state with the new results. As it is now I have to close it myself to see the fruits of my (ahem my calypso robot's) labour. And if you do keep it, please defocus the button I clicked earlier. Same reasoning as before, the task I set out to complete is now done and there's no need for me to run it again.

This is just feedback from a user. Take it for what it is and keep up the great work!

![136867519143922_animate](https://cloud.githubusercontent.com/assets/3073557/12213784/3585e452-b67f-11e5-959f-90417bc0d537.gif)

**Comment by enejb** [comment]
Thanks for your feedback @isaackeyet! It is very much appreciated. 

cc @MichaelArestad, @rickybanister and @johnHackworth thoughts?

**Comment by johnHackworth** [comment]
>  it displays a line log of the commands it's doing, but there's no reference? Does each message dismiss each other or are there X stacked Notices on top of each other by the end? What if there was an error with one of them, how would I know? Would there be a way to go back or would the cycle just break then? Seems half-baked.

about this: we had a bug when detecting several notices happening at the same time that we fixed yesterday. Now  (well, once I deploy the fix) that should say something "updating n plugins in m sites" instead of just showing the last notice. It's not a perfect solution (the global notices are being reworked completely, and plugins' bulk edit will be one of the most improved parts), but it's not as bad as showing only the last info available.

**Comment by johnHackworth** [comment]
apart from that, there are some very good points here!

**Comment by isaackeyet** [comment]
:thumbsup:

**Comment by rickybanister** [comment]
I totally agree that it is 100% safe to assume clicking 'edit all' should select every plugin in the list, rather than simply enable the mode where you then have to click another checkbox to select-all. I think it might be best to create a new issue concerning that.

The other mention here regarding the notifications should be handled either 1. already due to the aforementioned bug or 2. come in when we update notices to stack up globally.

**Comment by MichaelArestad** [comment]
What if we just change it to "Edit"?

**Comment by rickybanister** [comment]
"Edit" might go too far to vague since the SectionHeader is above the plugins list and not really _in_ context of anything particular. Also the 'Update All' button appears when updates are available and is scoped to 'all' so we could create parity by selecting everything.

I opened a specific issue for this in #2789.

**Comment by MichaelArestad** [comment]
Maybe `Edit plugins`. I suspect preselecting all is not the most common when bulk editing.

**Comment by rickybanister** [comment]
'Plugins' is already part of the context as it's the title just to the left and in the navigation. We've had 'Edit All' in production for a bit and haven't heard complaints, the only complaint was that clicking it didn't match the expectation that you would then be able to modify alllll plugins.

**Comment by MichaelArestad** [comment]
> the only complaint was that clicking it didn't match the expectation that you would then be able to modify alllll plugins.

Gotta test to see if that is the expectation. I'm not so sure it is.

**Comment by MichaelArestad** [comment]
> 'Plugins' is already part of the context as it's the title just to the left and in the navigation. 
I have no problem being explicit.

**Comment by cpapazoglou** [comment]
This is not relevant anymore since the interface has changed.
