### ISSUE TITLE
Signup: Back link from step 4 goes to step 2.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#22560]
Clicking the Back link on step 4 (`/start/user`) sends the user back to step 2 (`/start/domains`), rather than back to step 3 (`/start/plans`).

How to reproduce:

1. Go through the NUX, on the domains step select a paid domain (not a .wordpress.com domain).
2. Hit the <-- Back link at the bottom of the plans step.
3. You will be taken to the theme selection step, not the domains step.

**Comment by designsimply** [comment]
Tested and confirmed that clicking back in the plans step on signup returns you to the survey step (two steps back) instead of to the domains step as expected ([15s](https://cloudup.com/cX66FW3ZJhx)).

/hat tip 🤠 @apeatling the report at p7jreA-1wc-p2.

**Comment by lancewillett** [comment]
Closing as current signup flow has different steps, making this report no longer valid.
