### ISSUE TITLE
Security: 2FA switching phones is cumbersome

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#22572]
Moving WP 2FA to a new phone is confusing and requires too much reading.

People who use WordPress are very likely to get a new phone every now and then.

#### Steps to reproduce
1. Buy a new phone 📱✨ & have your old phone with you ☎️
2. Go to https://wordpress.com/me/security/two-step
3. Confirm that you have 2FA set up previously:
    ![image](https://user-images.githubusercontent.com/87168/36345079-3c8bfa4e-142d-11e8-8a15-4a5d9c499fa2.png)
4. Since there's no indication how to move this to a new phone, I head over to **Help**. I try _"2FA"_, _"two factor"_... no dice. I realise it's _"two step..."_ which brings me to correct help article.
    ![image](https://user-images.githubusercontent.com/87168/36345311-9169e23a-1430-11e8-94a5-8d7126434c67.png)
5. At the help article, I find [_"Moving to a New Device"_](https://en.support.wordpress.com/security/two-step-authentication/#moving-to-a-new-device)  among everything else.
6. These are the steps I'm told to follow. There are 3 links (_marked in bold here_) to additional help sections.
    > 1. Print a set of backup codes for your user account by **following the steps here**. DO NOT SKIP THIS STEP.
    > 2. On your new device, install the authenticator app.
    > 3. Disable the Two Step Authentication link with your old device by **following the steps here**.
    > 4. Set up your user account to link to your new device by **following the steps here**.
    > 5. If you are prompted to enter your verification code, use a code from your list of backup codes. Backup codes are one-time use only.
    > 6. You can now uninstall the authenticator app from your old device.

#### What I expected
Some as easy and smooth way to add new phones as others have, e.g. Google:

![image](https://user-images.githubusercontent.com/87168/36345269-fcc0cb62-142f-11e8-9d96-0d187970bfa9.png)

#### What happened instead
I felt lost.

**Comment by rachelmcr** [comment]
Absolutely agree. Should we reopen https://github.com/Automattic/wp-calypso/issues/19? That seems to cover the same issue you've reported here.

**Comment by simison** [comment]
@rachelmcr totally, I'll close this one and re-open there. Thanks!
