### ISSUE TITLE
Sidebar: browser status bar covers bottom menu item

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#2259]
<img width="330" alt="screen shot 2016-01-09 at 02 51 36" src="https://cloud.githubusercontent.com/assets/3073557/12213894/fdcf4140-b681-11e5-9640-1a622f26bd83.png">

Couldn't capture this with my cursor right now, but I'm hovering the WP Admin link at the very bottom of the sidebar. Chrome has not yet switched the status bar over to float on the right side (my cursor is not close enough to the viewport border) so it still displays the status message (in this case the href of the link).

It feels very cramped! I understand why the top of the list has to be snugly fitted to the masterbar, but some space at the bottom is a good way to let the user know that there's nothing more (and a great place to hide an easter egg, too). ;)

May I humbly suggest an additional 40px of space or so? I realize there's no good background color to go for then but I'm sure you rockstars will figure something out.

<img width="175" alt="screen shot 2016-01-09 at 03 34 46" src="https://cloud.githubusercontent.com/assets/3073557/12213892/f50a6ac6-b681-11e5-83fc-a2b1fadcbda9.png">

**Comment by lancewillett** [comment]
Closing as "works for me" — feel free to re-open later if we decide to iterate on the usability here. See also #4316.
