### ISSUE TITLE
Me: Settings should use toggles instead of checkboxes

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#226]
I believe we are moving towards always using toggles/switches when making a binary (on/off) choice. If that is so, then we'll need to replace these checkboxes with toggles.

![image](https://cloud.githubusercontent.com/assets/7233112/11280383/d07b8400-8ec3-11e5-93ea-69da9afcdab0.png)

**Comment by ebinnion** [comment]
@mtias - Will you please verify that we should move all of the `/me` checkboxes to toggles?

**Comment by mtias** [comment]
@ebinnion in general the idea is that checkboxes allow to select multiple options from a set, while toggles are on/off switches for the state of a single settings option.
