### ISSUE TITLE
NUX: Unable to sign up from IE11

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#22618]
#### Steps to reproduce
1. From a logged-out IE11 session, navigate to https://wordpress.com/start

#### What I expected
To see the signup form

#### What happened instead
A blank page loads with the following errors in the console:

```
SCRIPT1006: Expected ')'
File: signup.dabc596f83a6aac9daf4.min.js, Line: 8, Column: 21544
SCRIPT1006: Expected ')'
File: signup.dabc596f83a6aac9daf4.min.js, Line: 8, Column: 21544
Error: Loading chunk signup failed.
   {
      [functions]: ,
      __proto__: { },
      description: "Loading chunk signup failed.",
      message: "Loading chunk signup failed.",
      name: "Error"
   }
```

#### Browser / OS version
IE11 - Seen in Windows 7 and Windows 10

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/7233112/36431582-f79d7624-1625-11e8-8108-eb9386969df5.png)

#### Context / Source
#manual-testing

**Comment by stephanethomas** [comment]
I'm having this error in development:

<img width="617" alt="screenshot" src="https://user-images.githubusercontent.com/594356/36432209-f0466762-1659-11e8-94bb-eb0cc73b5e43.png">

**Comment by stephanethomas** [comment]
This might be caused by the `cpf` NPM module that was introduced in https://github.com/Automattic/wp-calypso/pull/21635 and which may use a function that is not polyfilled:

<img width="640" alt="screenshot" src="https://user-images.githubusercontent.com/594356/36433077-ff89abb0-165b-11e8-9c9c-be1463a0d68f.png">

**Comment by stephanethomas** [comment]
Actually that's not because of a function not polyfilled: this code defines a [function default parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), something that is not supported in Internet Explorer:

```javascript
e.exports=function(e=[])
```

**Comment by DanReyLop** [comment]
> Actually that's not because of a function not polyfilled: this code defines a function default parameter, something that is not supported in Internet Explorer:

Also, IE11 doesn't support arrow functions at all (`module.exports = () => {}`), and the `calc-dv.js` file has one of those too.

Either:
- We add the `cpf` library to [this RegExp](https://github.com/Automattic/wp-calypso/blob/master/webpack.config.js#L115) so it's transpiled,
- We submit a patch to `cpf` so it doesn't use ES6 features,
- We submit a patch to `cpf` so it transpiles its code before publishing to `npm`,
- or we stop using `cpf`.

**Comment by stephanethomas** [comment]
@yoavf: we've removed `cpf` in https://github.com/Automattic/wp-calypso/pull/22622. I'll let you decide [which path](https://github.com/Automattic/wp-calypso/issues/22618#issuecomment-367024456) you want to follow regarding this module.

**Comment by lancewillett** [comment]
I'm not sure if it's related, but there's been another report of blank pages in IE11: https://github.com/Automattic/wp-calypso/issues/21575
