### ISSUE TITLE
Invite Follower: dead end when inviting someone with no account

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#22619]
When you invite a follower with no account via email address, there is a dead end. The account is created(?), but the user can't log in.

![screen shot 2018-02-20 at 9 13 54 am](https://user-images.githubusercontent.com/618551/36431893-6852dccc-161e-11e8-8629-e9960737c8ef.png)

#### Steps to reproduce
1. start at https://wordpress.com/people/team
2. pick a Jetpack site or a Simple site
3. click the invite user button
4. input a throw away email address
5. make sure dropdown says "Follower"
6. Send invite
7. check inbox of throw away email
8. accept invite by copying the link and pasting in an incognito window
9. create an account using the steps shown on screen
10. click "Sign Up & Follow"
11. Message says to click the link in the email to activate 
12. go to inbox of the throw away email
13. Click on the new email — it should say "Log in to WordPress.com"
14. try to login, and it says that the account is not activated

#### What I expected

Able to login with the credentials I created.

#### What happened instead

I could not log in.

#### Browser / OS version
Chrome, macOS

#### Screenshot / Video

Here are all of the screenshots, of the steps above in reverse chronological order:

 
![screen shot 2018-02-19 at 3 33 57 pm](https://user-images.githubusercontent.com/618551/36398350-4d98c96a-158c-11e8-87f8-9bccdcce7c54.png)
![screen shot 2018-02-19 at 3 32 57 pm](https://user-images.githubusercontent.com/618551/36398351-4da5d66e-158c-11e8-8f2f-2f5352eeeb8d.png)
![screen shot 2018-02-19 at 3 32 45 pm](https://user-images.githubusercontent.com/618551/36398352-4db347d6-158c-11e8-93b5-6d790343ed1f.png)
![screen shot 2018-02-19 at 3 32 37 pm](https://user-images.githubusercontent.com/618551/36398353-4dc12608-158c-11e8-860c-d06b4be8c7f3.png)
![screen shot 2018-02-19 at 3 32 04 pm](https://user-images.githubusercontent.com/618551/36398354-4dce3276-158c-11e8-8712-1bfae8ebf457.png)
![screen shot 2018-02-19 at 3 31 41 pm](https://user-images.githubusercontent.com/618551/36398355-4ddc2a70-158c-11e8-90af-9c42dd22b8aa.png)

**Comment by shaunandrews** [comment]
This is a likely a security precaution. If you try it without an @automattic.com email address, it should work.

**Comment by drw158** [comment]
You're right, tested with a gmail and it worked!
