### ISSUE TITLE
Store: Remove Un-needed Data from Jetpack Sync

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#22656]
While not entirely certain much work will take place in this repository - this issue is going to be a place to track the need to verify what data we actually need synched back to the shadow site from Woo Installs. Since Store on WPCOM is the greatest consumer of this data, it seemed fitting to open the issue here.

Background: p7rcWF-IV-p2

Essentially the whitelist of synced attributes needs to be scrutinized to determine if there are any items that can be removed:

https://github.com/Automattic/jetpack/blame/5fbe2f5d9414426345ed4e5a66f5f8a1b483cb4a/sync/class.jetpack-sync-module-woocommerce.php#L195

Specifically, `_stock_status` has proven to be very problematic lately on sites that are using drop-shipping services that update thousands of products stock level frequently.

/cc @nabsul and @westi whom have both worked on the sync whitelist quite a bit in the past

**Comment by justinshreve** [comment]
Did a little audit of our usage. See p90Yrv-Cl-p2.

**Comment by allendav** [comment]
See also https://github.com/Automattic/jetpack/pull/9058

**Comment by justinshreve** [comment]
> If the remaining whitelist is fine as-is right now, it seems like we could keep it as-is until further issues pop up.

@timmyc Do you think we can close this until other issues pop-up? We've already removed some things as a result of this audit, and it looks like some of the improved syncing Jetpack is getting will help with the drop-shipping like sites.

**Comment by timmyc** [comment]
I haven't heard anything lately with issues of Woo data causing JP sync problems, but will /cc @enejb and @lezama to see if they have had any recent issues. I'll go ahead and close it out, but if they have some recent problem sites we can re-open and address.
