### ISSUE TITLE
NUX: Back link is broken on plans step

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#22657]
How to reproduce:

1. Go through the NUX, on the domains step select a paid domain (not a .wordpress.com domain).
2. Hit the <-- Back link at the bottom of the plans step.
3. You will be taken to the theme selection step, not the domains step.

**Comment by kwight** [comment]
Regardless of steps, this seems to be a problem going back from step 4 – rather than step 3, we get sent to step 2.

**Comment by kwight** [comment]
Erm, I sometimes get the same problem going from 3 back to 1, but not always (both situations seem to happen while testing on the `main` flow).

**Comment by apeatling** [comment]
I think this is the same as #22560?

**Comment by kwight** [comment]
Ha, it is; I have the memory of a goldfish sometimes. Closing in favour of #22560 .
