### ISSUE TITLE
Editor: cannot view reblog info while editing a reblogged post

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22664]
Steps to reproduce:

1. Find any WordPress.com post that has reblogs enabled.
1. Reblog the post to your own blog.
1. Go to My Sites > Blog Posts in your own blog and click on the post to edit it.

<strong>Result:</strong> there is no indication in the Calypso Editor that the post is a reblog or has a reblogged component.

![screen shot 2018-02-21 at wed feb 21 2 58 58 pm](https://user-images.githubusercontent.com/1119271/36507820-12fb3210-1718-11e8-8862-654b99a56e70.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11869 (Simple) using Firefox 58.0.2 on macOS 10.13.3.</sup>

This was raised as a point of confusion by a user in a #user-report at 971599-zen that says:

> if you look now the re-blogged article is there, but I can't see it in the draft on wordpress

/hat tip 🤠 @sdixon194 for the report.

**Comment by nylen** [comment]
Testing what happens in the GitHub API with an issue that has been closed and then reopened.  Ignore.
