### ISSUE TITLE
Store: Add "Powered by WooCommerce"

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#22662]
As we are looking to build a sales funnel starting at woocommerce.com -> Store on wordpress.com, we should probably add in something in Store that denotes that it is powered by WooCommerce.

Background: p8eNEx-2DG-p2

/cc @kellychoffman

**Comment by kellychoffman** [comment]
Should use the same design/placement as the Powered by Jetpack on the site pages. For example, go to https://wordpress.com/stats/day/URL

**Comment by kellychoffman** [comment]
Design and assets are in this related issue: https://github.com/Automattic/wp-calypso/issues/21376
