### ISSUE TITLE
Editor: request to update the slug description in post settings

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22676]
Steps to reproduce:

1. Go to https://wordpress.com/ > Blog Posts > (click any post) > More Options.
1. Click the (i) info bubble next to "Slug."

<strong>Result:</strong> the description is not accurate.

<blockquote>“The slug is the URL-friendly version of the page title.” is not even true. The slug is just the piece of the URL that identifies this page. It doesn’t have to have anything to do with the page title. This is also the first time I think I’ve seen mention of a “URL”.</blockquote>

![screen shot 2018-02-21 at wed feb 21 5 34 23 pm](https://user-images.githubusercontent.com/1119271/36513584-9b5aee92-172d-11e8-95e9-b8b7c661afda.png)
<sup>Seen at https://wordpress.com/post/madefortesting426.wordpress.com/2366 using Safari 11.0.3 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by benhuberman** [comment]
I think the confusion there comes from the fact that default slugs _are_ the post title (separated by dashes), but I agree it's not the most useful / clear way to explain them.

How about...
> The slug is the part of a web address that identifies a specific page or post within a site. It's often based on the post or page title.

**Comment by dimafeldman** [comment]
Hey @benhuberman , I've issued a PR to change this description. I assumed that it's better to keep the distinction between posts & pages, so I slightly modified the text for that. you can see my PR here #25491

**Comment by benhuberman** [comment]
That sounds great, @dimafeldman. If we can show contextual copy based on whether it's the page or post editor, so much the better.
