### ISSUE TITLE
Editor: Google Photos are painfully slow to scroll through

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22681]
Steps to reproduce:

1. Go to https://wordpress.com/ > Blog Posts > (click any post).
1. In the Editor toolbar, click Add > Media from Google.
1. Try scrolling through images with a Google account that has a lot of images saved in it and try to find an image from a few years back.
1. Try using the search to find images.

<strong>Result:</strong> it's slow to scroll through Media from Google and searching for something like "Feb 2017" doesn't pull up date specific photos.

![screen shot 2018-02-21 at wed feb 21 5 58 21 pm](https://user-images.githubusercontent.com/1119271/36514312-19d94e82-1731-11e8-8690-51c18568309f.png)
<sup>Seen at https://wordpress.com/post/cute.wordpress.com using Chrome 64.0.3282.167 on macOS 10.13.3.</sup>

<strong>Video:</strong> <a href="https://cloudup.com/c_YHyUdV-UM">39s</a>

<blockquote>I personally use Google Photos, so when I managed to find that option, I was excited. That’s a really nice way for me to get my images into my content. It is really painfully slow to try to scroll back through time to find old pictures if you have a lot though (and I’m on a really fast connection). And then I apparently hit a date limit? Couldn’t go back further than October 30. I guess it was a bug because it let me do it later. Might make sense to be able to jump back by date or something else, because if you have a lot of photos (which they heavily encourage), then this becomes really unwieldy for anything but your most recent photos.</blockquote>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by jakejones1984** [comment]
@designsimply I'm looking into this now. Will report back when I have more information.

**Comment by jakejones1984** [comment]
> searching for something like "Feb 2017" doesn't pull up date specific photos.

Update on this. This is an undocumented aspect of Picasa and is not fully support by Google. As a result, as we move towards Google Photos API this feature will have to be dropped. Hopefully the impact of this can be mitigated by the inclusion of better UI around

1. [Date filters](https://github.com/Automattic/wp-calypso/issues/25583)
2. [Album access](https://github.com/Automattic/wp-calypso/issues/22771)
