### ISSUE TITLE
Store: Stats: Referrer API: Return data in unit's format

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#22680]
The mechanism in Stats for filtering the currently selected data point in a set uses a date string formatted according to the unit.

For example, for `unit = 'month'` the dates returned in each object of the data array should be `YYYY-MM`.

<img width="284" alt="screen shot 2018-02-22 at 1 35 16 pm" src="https://user-images.githubusercontent.com/1922453/36513936-e9d3001a-17d6-11e8-8800-763c62bbed82.png">

Currently^^^, the response `body.date` is good, but `body.data[ 0 ].date` should similarly be formatted.

**Comment by timmyc** [comment]
fwiw i think this is a common pattern in all the other stats endpoints, where the date is still returned for unit = month as the first day of the period. Here is a snippet of the visits endpoint response for unit=month

<img width="421" alt="visits-month-data" src="https://user-images.githubusercontent.com/22080/36514382-063512b0-1729-11e8-9be7-dcf255ff0ccf.png">

**Comment by justinshreve** [comment]
Yeah I was thinking about that as well, when I was working with the other stats endpoints today. They return a `period` with the date in each response. Should I update that here as well @psealock?

**Comment by psealock** [comment]
Our new endpoints follow this pattern. Here is `orders`

<img width="246" alt="screen shot 2018-02-22 at 2 06 12 pm" src="https://user-images.githubusercontent.com/1922453/36514527-b17b6d4e-17d9-11e8-91e5-6194fb632eee.png">

When filtering over this data, keeping it in terms of a `unitDate` prevents errors I think

> They return a period with the date in each response. Should I update that here as well

I don't think it'll be needed.

**Comment by timmyc** [comment]
Cool - I didn't know that about the new woo stats endpoints, that definitely makes parsing easier.

**Comment by psealock** [comment]
Looking at the `orders` data^^^ I see the date has been placed inside the array. We have
```js
{
	fields: [ 'sales' ],
	data: [
		{ date: '2018', data: [ 99 ] },
	]
}
```
Maybe we should follow the same pattern:
```js
{
	fields: [ 'period', 'sales' ],
	data: [ 
		['2018', 99 ]
	]
}
```
@justinshreve , is this what you were asking?

**Comment by justinshreve** [comment]
@psealock Yeah that's what I meant!

**Comment by justinshreve** [comment]
Posted a patch at D10401-code.

**Comment by justinshreve** [comment]
@psealock Looking at it now, does it actually make sense to follow the 

```
data: [ 
    ['2018', ... ]
]
```

pattern?

Since we return a row per referrer, we can end up with multiple entries per date. This endpoint is different from the orders endpoint in that regard.

i.e

```
data: [ 
    ['2018-01', 'facebook.com', 99 ],
    ['2018-01', 'instagram.com', 33 ],
   // etc...
]
```
You can see what I mean in the patch I linked above.

**Comment by psealock** [comment]
Yup, I see what you mean. Sorry Justin for not thinking this through before having you get started.

On the client, it means the difference between filtering through all the data vs finding one of (at most) 30 elements in the data array

```js
// currently
const selectedData = find( data, d => d.date === selectedDate );

// Patch D10401
const selectedData = data.filter( d => d.date === selectedDate );
``` 
Potentially, it may result in expensive re-renders if we're looking at an entire month's worth of data.

**Comment by timmyc** [comment]
@psealock so can we continue with the endpoint as-is or do we need to make some changes still? Justin is out for a few days now so I just want to see what needs to be done to keep things moving forward. I'm happy to help out with API changes too.

**Comment by justinshreve** [comment]
@timmyc We still need the part of the D10401 that [returns the different date formats](https://github.com/Automattic/wp-calypso/issues/22680#issuecomment-367533325).

i.e. `2017-04` instead of `2017-04-01` when month is passed, `2017` when year is passed, etc.

I should have time to tackle this Monday, and I believe Paul said he can work with the date view for now.

**Comment by psealock** [comment]
@timmyc Known bugs are being tracked here, https://github.com/Automattic/wp-calypso/projects/26 in the MVP Bugs column.

No issues are blockers for me. We have lots of corner cases to examine as you pointed out in https://github.com/Automattic/wp-calypso/pull/21752#issuecomment-368068334

**Comment by justinshreve** [comment]
Updated and addressed in the new D10460-code.
