### ISSUE TITLE
Signup: Creating a new site with a free .blog subdomain shows the site as HTTP

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#22688]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/subdomain/design-type-with-store-nux?vertical=a8c.1
2. Create a new site using a free .blog subdomain (eg. examplesite.art.blog)
3. Proceed to the final step

#### What I expected

Site should be shown as HTTPS like free wordpress.com subdomain sites are

#### What happened instead

Site is displayed as HTTP

#### Browser / OS version

Chrome on macOS

#### Screenshot / Video

<img width="932" alt="screen shot 2018-02-22 at 3 42 33 pm" src="https://user-images.githubusercontent.com/128826/36522582-262fe520-17e9-11e8-98f5-af5fd5a52b0a.png">

#### Context / Source
#dogfooding

**Comment by alisterscott** [comment]
@fditrapani @taggon As discussed

**Comment by fditrapani** [comment]
Thanks @alisterscott

**Comment by alisterscott** [comment]
Since we'll be showing the checklist on arrival for all new blog sign ups we won't redirect to the front of the site so this won't be an issue - closing for now
