### ISSUE TITLE
My Plan: Incorrect CTA link for GA

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22694]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/my-plan/{site-url}
2. Make sure site has a Professional plan
3. Click the "Connect Google Analytics" button

#### What I expected
To be taken to the Google Analytics settings card 

#### What happened instead
I was taken to the SEO settings card

**Comment by beaulebens** [comment]
Ideally we'd be able to target/highlight specific settings with this sort of link as well.

**Comment by keoshi** [comment]
It would be great if we could highlight just the card we're referring like Beau said. This would be useful in many scenarios.

Here's a quick mock of how that could look like, taken from this issue: https://github.com/Automattic/wp-calypso/issues/21610

![image](https://user-images.githubusercontent.com/390760/35050083-dfe0e6e8-fb99-11e7-8a93-3d8e7497fc14.png)

**Comment by gravityrail** [comment]
Same issue here: https://github.com/Automattic/jetpack/issues/8727
And here: https://github.com/Automattic/wp-calypso/issues/22692

**Comment by gravityrail** [comment]
Removing from Hack Week in favour of longer term direct-link solution as per conversation with @rickybanister

**Comment by rickybanister** [comment]
@keoshi thanks for the mockup—I actually did something similar recently while thinking about the checklist project—a checklist item would direct a user to a settings page and we could highlight a single item. 

In discussing with @johnHackworth, however, we felt it would be more clear if we could create routes like /settings/traffic/google-analytics that show only one setting per page. That page would have a header-cake to go back to the whole traffic tab. 

This has been removed from hack week so we can work on implementing this along with the checklist feature and 'do it right'. 

cc @joanrho also

**Comment by rachelmcr** [comment]
I confirmed this is still an issue using the original steps to reproduce. Part of what makes this especially confusing is that I am scrolled partway down the Traffic settings page, but not far enough to get to the GA settings.

The proposed solution would definitely make this clearer.
