### ISSUE TITLE
Search JITM: Linking to the wrong place

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22690]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/{site-url}
2. Click the "learn more" link in the JITM about Jetpack search
3. You will be redirected to: https://jetpack.com/support/search/?cta&site={site-url}

#### What I expected
Should be redirected to: https://jetpack.com/features/design/elasticsearch-powered-search/

#### Screenshot / Video

<img width="971" alt="plans_ _richard_s_dot_org_sandbox_ _wordpress_com" src="https://user-images.githubusercontent.com/2287740/36535116-862b57b2-17c0-11e8-8e18-ae5f7d3d3608.png">

**Comment by gravityrail** [comment]
Committed and deployed in commit 11490 on jetpackme-new theme.
