### ISSUE TITLE
My Plan: Incorrect CTA link for Elasticsearch

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22692]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/my-plan/{site-url}
2. Make sure site has a Professional plan
3. Click the "Enable Search in Traffic Settings" button

#### What I expected
To be taken to the Elasticsearch settings card 

#### What happened instead
I was taken to the Related Posts settings card

**Comment by gravityrail** [comment]
I can't reproduce this.

I enabled Pro, clicked "Enable Search in Traffic Settings", and was taken to Traffic Settings.

https://wordpress.com/settings/traffic/goldsounds.ngrok.io

At the veeeeery bottom is Search.

Ideally we could link directly to some settings like this: https://wordpress.com/settings/traffic/goldsounds.ngrok.io#search - but currently that's not possible.

**Comment by gravityrail** [comment]
Removing from Hack Week in favour of longer term direct-link solution as per conversation with @rickybanister

**Comment by rickybanister** [comment]
In discussing with @johnHackworth, we felt it would be more clear if we could create routes like /settings/traffic/google-analytics that show only one setting per page. That page would have a header-cake to go back to the whole traffic tab.

This has been removed from hack week so we can work on implementing this along with the checklist feature and 'do it right'.

cc @joanrho also

**Comment by rachelmcr** [comment]
I confirmed this is still an issue using the original steps to reproduce. Part of what makes this especially confusing is that I am scrolled partway down the Traffic settings page, but not far enough to get to the Search settings.

The proposed solution would definitely make this clearer.
