### ISSUE TITLE
Ads: Able to activate on Free plan

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22698]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/traffic/{site-url]
2. Make sure site is on a free JP plan
3. Click the toggle to enable ads

#### What I expected
Either for the toggle to be inactive or to be given a prompt to upgrade.

#### What happened instead
Ads where enabled.

#### Screenshot / Video

Screencast: https://cloudup.com/cB-802QY3v9

<img width="665" alt="site_settings_ _richard_s_sandbox_ _wordpress_com" src="https://user-images.githubusercontent.com/2287740/36537636-afa5cfde-17c8-11e8-8f2d-b325dcc2f69d.png">

**Comment by rachelmcr** [comment]
I think the problem you're seeing is actually the wrong plan appearing for that site in Calypso. (JP debug and store admin are showing a Premium plan on that site, so you're seeing the right features but the wrong plan name.)

I checked a test site on the free plan and I'm seeing the expected upgrade nudge:

![screenshot 2018-02-23 10 55 06](https://user-images.githubusercontent.com/8658164/36590893-12802950-1888-11e8-9f5d-25b93ffdaf21.png)

**Comment by tyxla** [comment]
I've been trying to repro this one, but no luck. Calypso always seems to display the right plan and the right Ads block in all cases I'm testing with (both free and paid Jetpack plans).

@rachelmcr @richardmuscat could you folks please share some instructions on how to repro at least one of the cases you've shown?

**Comment by rachelmcr** [comment]
I couldn't repro the issue myself — I think it must be something causing the wrong plan name to appear on the site used in the original report, although I don't know why that would happen.

**Comment by richardmuscat** [comment]
Irritatingly, I am now not able to reproduce it myself and I tried a couple different ways. Feel free to close the issue and file it under "Magically Fixed" or "Richard was High"
