### ISSUE TITLE
Signup: Detect wordpress.com in the domain name

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/wp-calypso#227]
The signup should know that if I enter a domain ending in wordpress.com that I want something on WordPress.com and not `.wordpress.com.wordpress.com`.

@melchoyce reported "Just ran 5 users tests where 3/5 users typed in the .wordpress.com into the domain search bar."

**Comment by bikedorkjon** [comment]
This is happening in part because there is an is_availability check going on that shouldn't be happening in these cases.
<img width="557" alt="screen shot 2016-01-25 at 2 48 10 pm" src="https://cloud.githubusercontent.com/assets/312395/12567272/119d1fe6-c373-11e5-83a3-7187b0b3c0a3.png">

**Comment by stephanethomas** [comment]
I think this was solved last week by @dzver.

**Comment by fabianapsimoes** [comment]
Yup, this was fixed by @dzver already. Closing.
