### ISSUE TITLE
Same title for multiple posts when using keyboard shortcuts in the Reader

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#22713]
Using keyboard shortcuts (J) to move through full posts in the Reader results in the same title being displayed for multiple posts.

#### Steps to reproduce
1. Go to https://wordpress.com
2. Click Reader
3. Click on the first post in the stream to load the full post (in the Reader)
4. Press J to navigate through each full post

#### What I expected
I expected each post to display the correct title.

#### What happened instead
Around the 3rd or 4th post, the title "sticks" and becomes the same for each post. The body, avatar etc changes as you move through each post but the post title remains the same.

#### Browser / OS version

* Chrome
* Firefox
* Windows 10
* Windows 7
* Linux Mint
* Chrome OS

We have been able to replicate this internally using:

* Chrome 64.0.3282.167
* Mac OS 10.13.3

#### Screenshot / Video

![screenshot_2](https://user-images.githubusercontent.com/11627765/36549332-7183ba8c-17ea-11e8-82d4-a0dad1b10723.jpg)

![screenshot_1](https://user-images.githubusercontent.com/11627765/36549327-6fbb5e08-17ea-11e8-94cb-885d6284450e.jpg)

#### Context / Source
#user-report
#manual-testing
890689-f

**Comment by jancavan** [comment]
I'm able to repro this issue. Here's a video:
https://cloudup.com/cLc7nnH27le

I'm using:
Mac OS High Sierra 10.13.3
Chrome Version 64.0.3282.167

**Comment by bluefuton** [comment]
No longer able to repro this one. Reduxification may have fixed it!
