### ISSUE TITLE
Jetpack Connect: Update "Connect to WordPress.com" image and copy on "Ready for Installation" step

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22716]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/connect
2. Enter the URL of a self-hosted site without Jetpack installed and select "Connect Now."

#### What I expected

I expected the instructions on the "Ready for Installation" screen to match the flow.

#### What happened instead

The "Ready for Installation" instructions show the old "Connect to WordPress.com" button and copy:

![screenshot 2018-02-22 17 40 34](https://user-images.githubusercontent.com/8658164/36554689-d9346f5c-17f7-11e8-8acc-d9bd70975201.png)

Those should be updated to reflect the new "Set up Jetpack" button:

![screenshot 2018-02-22 17 44 06](https://user-images.githubusercontent.com/8658164/36554731-fcb4960a-17f7-11e8-9706-228b81dd2116.png)

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Context / Source
#bug-scrub #manual-testing

**Comment by keoshi** [comment]
Here's a quick mock of how that could look like:

![image](https://user-images.githubusercontent.com/390760/36857951-bcd2d798-1d71-11e8-95b3-e6d23b9bb046.png)

#### Changes:

- Remove green left border.
- Change main copy to `Connect Jetpack to WordPress.com`.
- Change button label to `Set up Jetpack`.
- Apply the following styles to the button:

```
border-radius: 3px;
background-color: #00be28;
color: #fff;
border: 2px #00a523 solid;
border-width: 1px 1px 2px;
```

**Comment by johnHackworth** [comment]
This could be integrated in the new remote install project we are already finishing

**Comment by alisterscott** [comment]
Just doing some cleaning up. @johnHackworth this one is assigned to you, is it in progress? Can I add the `[Status] In Progress` label?
