### ISSUE TITLE
Notification Settings: global email settings for site override user settings

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#22725]
copied from https://github.com/wordpress-mobile/WordPress-iOS/issues/4385#event-1485981044

Basically, if you have email notifications turned on for, let's say new comments, in your notification settings, you won't get that email notification if it's turned off in the site settings (Settings > Discussion)

#### Steps to reproduce
1. Starting at URL: wordpress.com/me/notifications
2. make sure you have all emails on for your site
3. go to wordpress.com/settings/discussion
4. turn off all emails shown here:

![screen shot 2018-02-22 at 1 23 06 pm](https://user-images.githubusercontent.com/618551/36559535-ec7aa0be-17d3-11e8-8f45-c0681b6eb0e6.png)

#### What I expected
I expected to get an email notification because I have the email notification setting turned on in my user preferences.

#### What happened instead
I did not get an email. I was confused because there are some global site email settings that are easy to miss.

#### Context / Source

This has been a long standing issue, and I'm surprised we don't here complaints about this.

Copied comments from original issue:

> @drw158 those are indeed the settings that are preventing you from getting emails. Those settings are global for a site, affecting all users and stored as options, and the problem with integrating them into the notifications control center is that the settings we show there are user specific.
> 
> One way I think we could fix this is by adding a Notifications tab to My Sites > Settings on Calypso/Native Apps, and disable the options accordingly on the control center. Maybe Add a warning with a link to site settings to tell the user why those settings are disabled.
> 
> For Calypso:
> 
> ![](https://cloud.githubusercontent.com/assets/233601/10885193/ccd1d2f8-815a-11e5-9de5-1ef41639f2b7.png)
> 
> Also, there are settings that will have no effect on the control center, like reblog notification.
> 

---

> Eventually we should deprecate these email discussion settings in Calypso and move them to NCC. It will be a very bad UX to have the "same" setting in 2 different areas. As you mentioned, they are not technically the same, but the text does say "Email me whenever..." so it's very confusing.
> 
> I'm not sure of the implications of mapping these email settings to NCC though. I'm thinking that we should be able to just map them over directly, but probably not so simple :). If a site has multiple authors and one of the email discussion settings are checked, then map them to each user on the blog in NCC?
> 
> There will be some growing pains since we currently don't have an equivalent setting for comments held in moderation.
> 
> Your suggestion for an alert message in NCC does sound like a good very short term solution though.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
