### ISSUE TITLE
Activity Log: allow user to take some action when plugin can't be updated

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#22721]
The following event is shown when a plugin can't be updated because the old folder couldn't be removed:

<img width="748" alt="captura de pantalla 2018-02-22 a la s 15 14 44" src="https://user-images.githubusercontent.com/1041600/36556440-eeda3224-17e3-11e8-9e86-a713473866dc.png">

At this point, the user can't advance anymore. There's something wrong in the site but they can't take action to fix it. Maybe we could add a Get help button since this is something that failed at server level and would require some technical knowledge to solve it.

Additionally, maybe we could add some popover with more info outlining a possible cause for the failure deleting the old plugin folder?

#### Reproducing

This event is rare but can be reproduced as follows:

1. add a plugin to a site
2. downgrade it manually by editing it and save it
3. access the site through SSH and set the permissions of the folder so it can’t be written, 555 works. This will prevent WP core from deleting it and will throw the issue.
4. try updating it in Calypso, it will fail
<img width="555" alt="captura de pantalla 2018-02-22 a la s 15 14 32" src="https://user-images.githubusercontent.com/1041600/36556603-865f5c8c-17e4-11e8-89ea-e24d185483ae.png">
5. now go to Activity Log and the event shown at the beginning of this description will be there

**Comment by keoshi** [comment]
This is one the prime examples for a foldable card to show more info, instead of hiding it under a popover, but we're not there yet. :)

@eliorivero Is this easily triaged for Happiness folks? If not, I think that would be a great first step. And if it's already so, then I'd say the “Get Help” button is enough for now.

**Comment by jeffgolenski** [comment]
+1 to the get help button for happiness, and maybe a link to any documentation if we have it for the DIY folks? @keoshi do we think that maybe a "hide" link would be something to add in case folks who know what they're doing just want to move along? Maybe that's too much work for the ROI.

**Comment by MichaelArestad** [comment]
I agree. Let's do a get help link with tracking. We can always remove it or find an alternate solution if it's putting too much pressure on our support team.

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/23308
