### ISSUE TITLE
Jetpack > Manage Connection > Site ownership not loading

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22720]
For any Jetpack site, if I navigate to Settings > General > Manage Connection, the "Site ownership" section is not loading for me:

![screen shot 2018-02-22 at 10 55 58 am](https://user-images.githubusercontent.com/108942/36555402-2120b6ce-17bf-11e8-95f3-a2a93fc9ab1a.png)

No console errors. Using Chrome/OSX in case it's relevant.

**Comment by tyxla** [comment]
This looks pretty bad - on it.

**Comment by rachelmcr** [comment]
Noting for reference that this has happened before and mysteriously resolved itself: https://github.com/Automattic/wp-calypso/issues/21999

**Comment by tyxla** [comment]
#22749 addresses this one.
