### ISSUE TITLE
Framework: Unique "key" prop warning on first load

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#22728]
#### Steps to reproduce
1. `git pull && npm start`
2. Navigate to http://calypso.localhost:3000
3. The following warning displays in console after webpack etc have all finished building:

```
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <Head>. See https://fb.me/react-warning-keys for more information.
    in meta
    in Document
GET / 200 240.937 ms - 24994
```

#### Browser / OS version

OSX High Sierra 10.13.3
Node 8.9.4
npm 5.6.0

**Comment by gwwar** [comment]
@flootr would it be possible to see if this is occurring because of changes from #21424 ?

**Comment by flootr** [comment]
@gwwar yes, I'm pretty sure my changes there are causing these warnings. We need to use a `key` there which is unique for each element.
