### ISSUE TITLE
Plans Page: Not able to chat with support

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#22731]
When I get send to the plans page from jetpack.com 
I am not able to chat with support if I have questions. the same way I was when I first connected the site . The link to connact support takes you to https://jetpack.com/contact-support/. 

![screen shot 2018-02-22 at 1 07 49 pm](https://user-images.githubusercontent.com/115071/36567446-474d9f6c-17db-11e8-92cb-9577b64192c6.png)

**Comment by sirreal** [comment]
A few questions about this issue:

1. This is a WordPress.com Simple, Atomic, and Jetpack issue.
1. Presumably, we should be adding chat support for all of these products.
1. The most obvious place without further changes is to make this link work with chat:
   ![jp](https://user-images.githubusercontent.com/841763/36971612-a927c73c-206c-11e8-9e72-36ee4bf82ed1.png)
   ![wp](https://user-images.githubusercontent.com/841763/36971613-a952f2cc-206c-11e8-86a0-643fc34af73a.png)
1. What is our chat support like for users across these products? Does it depend on the current site plan, or should chat be available regardless?
