### ISSUE TITLE
Chat: Weird animation when closing

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22737]
When a chat is triggered from the connection flow (or other places potentially), it loads onto the right side of the screen. When you close it, it "shrinks" down to a point on the left (where the sidebar might otherwise be?). This is a really weird animation if the sidebar is not there.

Suggest it just slides away to the right instead.

**Comment by beaulebens** [comment]
@mattwondra Any idea how hard this would be, or where someone would start?

**Comment by shaunandrews** [comment]
We plan to move the help out of the sidebar at some point. That doesn’t fix your issue right away, but it won’t be an issue once we move help.

**Comment by mattwondra** [comment]
Here is where CSS is declared for Happychat minimize animations in Calypso: https://github.com/Automattic/wp-calypso/blob/master/client/components/happychat/style.scss

It looks like there's a version of the animation that minimizes to the right though I haven't tested what this looks like: https://github.com/Automattic/wp-calypso/blob/master/client/components/happychat/style.scss#L191-L206

That version is in use already for some layout (`.is-group-editor`): https://github.com/Automattic/wp-calypso/blob/master/client/components/happychat/style.scss#L158-L160

My best guess — add another layout-specific override like the `.is-group-editor` to either use the same right-minimization, or to simply hide the panel. For example, change the last lines I linked to also include when the layout `.is-jetpack-page`:

```
.layout.is-group-editor .happychat .happychat__container.is-open.is-minimizing,
.layout.is-jetpack-page .happychat .happychat__container.is-open.is-minimizing {
	animation: happychat-minimize-right .5s 1 forwards;
}
```

(`.is-jetpack-page` is an example, I'm not sure what layout-specific classes appear on the pages in question).

**Comment by beaulebens** [comment]
This might actually be something that someone from @rickybanister's team can handle if it's going to just be the case of adding a new CSS selector!

**Comment by keoshi** [comment]
I'm on it.

**Comment by keoshi** [comment]
Addressed in https://github.com/Automattic/wp-calypso/pull/23167
