### ISSUE TITLE
JITM: Incorrect messaging on themes upgrade

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22747]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/{site-url}
2. Make sure site is *not* on a Professional plan
3. Look at the upgrade JITM promoting Professional

#### What I expected
Correct content.

#### What happened instead
Ad is claiming we offer "... advanced customization, more storage space, and video support along with all your new themes." We do not. 

#### Screenshot / Video

<img width="968" alt="wordpress_themes_ _richard_s_dot_org_sandbox_ _wordpress_com" src="https://user-images.githubusercontent.com/2287740/36590160-a2f7e91c-1885-11e8-98a8-4fd5dea3b812.png">

**Comment by beaulebens** [comment]
Note this is specific to Jetpack sites; we need to modify the content of this banner for Jetpack sites to reflect the contents of the different plans there.

**Comment by gravityrail** [comment]
@beaulebens for completeness here, can you please let me know what the exact copy in the CTA _should_ be?

**Comment by beaulebens** [comment]
@richardmuscat or @nicoleckohler might have better wording, but I'd assume we want to highlight the interesting features in a Professional plan, so probably something along the lines of:

> Get Elasticsearch-powered site search, real-time offsite backups, and security scanning along with all your new themes.

**Comment by ockham** [comment]
FWIW, the relevant LOC is https://github.com/Automattic/wp-calypso/blob/c781f2ee6271a03b5d01c1b1d91790523bbc6be2/client/my-sites/themes/single-site-jetpack.jsx#L99

**Comment by nicoleckohler** [comment]
Beau's suggestion reads well to me, maybe with a tiny tweak to say "in addition to more than # premium themes" (where # = the approximate number we're offering, so more than 100?)

**Comment by withinboredom** [comment]
![image](https://user-images.githubusercontent.com/1883296/36989201-0715defe-206f-11e8-925b-73db6cd24d58.png)
How does this look (I removed the redundant "with all your new themes" at the end

**Comment by nicoleckohler** [comment]
@withinboredom Remove the + after 100 and I think we're good to go. :)
