### ISSUE TITLE
Add search/replace option for old links

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#22744]
When a user changes their site's domain, and cancels their old domain, it can cause broken links. A search/replace option for old links would make the process of changing domains easier.

#### Steps to reproduce
1. Set up a site and register a domain to it - **example.com**.
2. Publish multiple posts, all containing links to other posts on **example.com**.
2. Cancel **example.com**.
3. Register a new domain - **mynewgroovydomain.com** - to the site.

#### What I expected

I would **hope** for the links on **mynewgroovydomain.com** to continue to work after the change in domain. 

#### What happened instead

Cancelling **example.com** and changing the site's domain to **mynewgroovydomain.com** breaks the links on it. 

There is no easy way to fix this issue for users on WordPress.com sites unless they upgrade to WordPress.com Business (so that they can use a search/replace plugin). There is also no easy internal way for support to help the user.

If the user doesn't have a Business plan or want to upgrade, either they or someone from support needs to manually update the old links. This can be a very time-consuming and tedious task in cases where there are a lot of links referencing the old domain.

#### Context / Source

This came up in #262386-h (I followed up with the user in 974542-z). The user had cancelled an old domain and replaced it with a new one, which resulted in 500+ broken links.

#user-report #reallife #stresscase #painpoint

**Comment by KokkieH** [comment]
Another case in https://en.forums.wordpress.com/topic/godaddy-blog-to-wordpress/

This user has migrated an established site with lots of internal backlinks from another host to a WordPress.com site at a new domain, and these backlinks will all stop working once the original site is taken offline.

I've suggested they map their old domain to the site as well so we can try to automatically redirect those links for now.

**Comment by SiobhyB** [comment]
A search/replace option for links was requested again in p2EDhh-11F-p2. As a "solution", two HEs went through to manually update the user's links, so a more automated solution would have saved time.

**Comment by spencerberry** [comment]
+1 from the site owner of https://walkonomics.com/ who had a site import bring the images to media, but not update the urls properly in the posts themselves.

**Comment by klimeryk** [comment]
Closing this as wontfix - we fairly clearly warn the user that canceling the domain means the site will not resolve using that domain. For internal links within the site, we should be defaulting to relative links (`/example` vs `foobar.com/example`), unless the user overrides this manually.
The last issue is for an import specifically and that's a separate issue.
