### ISSUE TITLE
Rewind: Pressable NUX wont start when running as e2e test

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#22743]
I working on automating Pressabe NUX flow (PR: https://github.com/Automattic/wp-e2e-tests/pull/967, GH Issue: https://github.com/Automattic/wp-calypso/issues/22378) and my automated tests can not trigger `pressable-nux` flow.

#### Steps to reproduce
1. checkout `add/jetpack-pressable-nux-flow` branch and run e2e test from `wp-e2e-tests` repo project root(: `./node_modules/.bin/mocha ./specs-jetpack-calypso/wp-pressable-nux-spec.js`

#### What I expected
`localStorage.signupFlowName` will be set to `pressable-nux` and once I Authorize jetpack connection I'll be redirected to Pressable NUX inside Calypso

#### What happened instead
`localStorage.signupFlowName` was `undefined`, and once I Authorized jetpack connection - I was redirected to wp-admin

#### Browser / OS version
Chrome 64 / Mac OS

#### Screenshot / Video

Pending

**Comment by rachelmcr** [comment]
I just realized that the `pressable-nux` flow isn't enabled in production yet. Here's the config check:
https://github.com/Automattic/wp-calypso/blob/464fa909e3300f1512e205ca3ea2de43aad4cd02/client/jetpack-connect/authorize.js#L581

And here's where it's disabled in production:
https://github.com/Automattic/wp-calypso/blob/6b220098e541e5b9242eb066aed5a2c5df8a0731/config/production.json#L37

It's only enabled in development and staging for now.

**Comment by brbrr** [comment]
I'm going to close this as it's not actually a bug.

**Comment by rachelmcr** [comment]
Just to close the loop, this is now in production: https://github.com/Automattic/wp-calypso/pull/22754
