### ISSUE TITLE
Free Trials: Refactor the invalidation of site data after purchase

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#2274]
The problem was raised here https://github.com/Automattic/wp-calypso/pull/2238/files#r49343214

> I think it would make sense to me that the code responsible for making the payment request would itself trigger the invalidation (not necessarily handle it but notify of a possible modification in the site data).

For future maintenance, I believe this piece of code would need a refactoring.

#### A bit of background

When we purchase a plan, we want to update both:
- The Plans page (at `/plans/:site`), which loads the Plans or PlanOverview component depending on the type of Plan (free plan or normal plan). This looks at the `sitePlans` value in the global state store.
- The name of the plan at the right of the `Plans` menu entry in the sidebar which for now uses the `site.plan.product_name` info from `lib/sites-list`.

And we want to avoid displaying stale data in both case.

A first fix was proposed at https://github.com/Automattic/wp-calypso/pull/1987 but then [it was decided](https://github.com/Automattic/wp-calypso/issues/2236) to redirect the user to a custom page after purchasing a free trial plan.

**Comment by stephanethomas** [comment]
I think we should also refactor the code that was implemented for renewals.

**Comment by fabianapsimoes** [comment]
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.
