### ISSUE TITLE
Themes: Sub-optimal link on Professional nudge

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22748]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/{site-url}
2. Make sure site is *not* on a Professional plan
3. Click the upgrade JITM promoting Professional

#### What I expected
To see Professional highlighted

#### What happened instead
Nothing was highlighted.

I think this is because the link is: https://wordpress.com/plans/{site-url}?plan=jetpack_premium

It should be: https://wordpress.com/plans/{site-url}?plan=jetpack_business 

Note **jetpack_premium** instead of **jetpack_business**

**Comment by ockham** [comment]
This thing:

![image](https://user-images.githubusercontent.com/96308/36975608-831f002c-2072-11e8-92db-3dd56606e89e.png)

Not entirely sure what a JITM is (Just-in-time-Message), but this is merely a `<Banner />` component. Working on a fix now.
