### ISSUE TITLE
Posts not publishing with backdate for specific Interface languages

### ISSUE THREAD

**Issue by krutidugade** [Automattic/wp-calypso#22753]
User reported when Interface Language is set to Arabic then posts aren't published in backdate. I tested this on my test site and was able to reproduce the issue. I checked few more languages and noticed that only specific languages are facing this issue. My test site - https://kdtestsitebusinessplan.com

User report - 965708-zen

#### Steps to reproduce
1. Starting at URL: https://kdtestsitebusinessplan.com/
2. Go to Account Settings - https://wordpress.com/me/account
3. Change Interface Language (Hindi, Arabic, Nepali)
4. Click Save Account Settings
5.  Click on My Sites > Blog Posts > Add or directly enter this URL https://wordpress.com/posts/ and click Add
6. Type the contents
7. Select a backdate
8. Wait for some time
9. If language is either Nepali or Hindi, the backdate will change to Publish immediately again
10. Select a backdate again
11. Click Publish

#### What I expected
The post should be published with the selected backdate

#### What happened instead
The post was published in today's date, that is, when the post was published

#### Browser / OS version
My Browser details - whatsmybrowser.org/b/G5S2DSQ
MacOS Version - 10.13.3

 #manual-testing #user-report

#### Checks performed
1. Checked for Polski (Eastern Europe) - works
2. Checked for Bahasa Indonesia (Asia-Pacific) - works
3. Checked for Spanish (Americas) - works
4. Checked for Afrikaans (Africa and Middle East) - works
5. Checked for Français (Western Europe) - works
6. Checked for Hindi (Asia-Pacific) - doesn't work
7. Checked for Arabic (Asia-Pacific) - doesn't work
8. Checked for Nepali (Asia-Pacific) - doesn't work
Test blog posts here - https://kdtestsitebusinessplan.com/blog/

#### My Observation
It appears that for some languages of Asia-Pacific region the feature of publishing in backdate doesn't work when Interface language is regional. I haven't tested for all languages so I can't be 100% sure about it. There could be more languages that are affected. 

Issues -
1. For some, only publishing in backdate doesn't work
2. For some, the selected publish date gets deselected the first time and the post isn't published in backdate after selecting it again

Slack discussion with @KokkieH -
p1519209682000362-slack-triage

**Comment by liviopv** [comment]
This also affects posts with publishing dates in the future. Tested arabic and hindi. 

Reported: 7378296-hc 1504368-zen

One very weird thing I noticed was in a screenshot that they sent where Calypso was not refreshing the orientation to LTR when changing the interface language to English:

![Screenshot](http://cld.wthms.co/b3ZwBD+)
Screenshot: http://cld.wthms.co/b3ZwBD

**Comment by TeniCola** [comment]
Update with another recent livechat where the user experienced this problem, the language was Arabic. I wasn't able to replicate it again when I use SSP, but another HE was able to and they recorded it in a GIF (gif may have personal info, look for the link in the following correspondence).

> HC-9970035 / ZD-1761445 
> p1548871435478700-slack-tickets

I'll make a P2 request and let the user know that it's a bug we're working on, but I'll also check to see if they're still having this error.

**Comment by rachelmcr** [comment]
This is an issue for UI languages that don't use the Latin alphabet. For some reason we're sending the publish date to the `posts` endpoint in the UI language numerals, for example like this for Arabic:

`date: "٢٠١٨-١٠-١٦T١١:١٢:٢٧"`

The API rejects this as an invalid date:

```
{"body":{"code":"rest_invalid_param","message":"Invalid parameter(s): date","data":{"status":400,"params":{"date":"Invalid date."}}},"status":400,"headers":{"Allow":"GET, POST, PUT, PATCH, DELETE"}}
```
