### ISSUE TITLE
Store: Stats: Referrer API: Include currency in response

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#22751]
Currency is required to display sales amounts correctly. 

There already is a function previously written for this `get_store_currency` in the endpoints file

**Comment by justinshreve** [comment]
Addressed in D10460-code.

**Comment by justinshreve** [comment]
@psealock The patch I put up in D10460-code includes the currency in the top level response. Would it be better to include it as a field? I think that is what orders is doing actually.

**Comment by psealock** [comment]
>Would it be better to include it as a field?

I was just looking into this. It does allow me to pass along the data as a simple array, so yes that would be ideal. Thanks!
