### ISSUE TITLE
Publicize doesn't pre-fill its message in Calypso Editor sidebar

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22762]
When using Publicize in wp-admin, you can preview the message that will be sent (based on the title of the post). In the Calypso editor, no preview is provided, so you don't know what will be sent:

![screen shot 2018-02-22 at 7 04 01 pm](https://user-images.githubusercontent.com/108942/36601284-02c65446-1872-11e8-9bfb-f94df7ab6520.png)

Confirmed for Jetpack and WP.com sites.

**Comment by designsimply** [comment]
Tested and confirmed using a WordPress.com Simple site.

![screen shot 2018-02-23 at fri feb 23 9 07 21 am](https://user-images.githubusercontent.com/1119271/36604001-baf16b1c-1879-11e8-8b28-4790d03c6ec8.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11892 (production) using Firefox 58.0.2 on macOS 10.13.3.</sup>

WP Admin view for comparison:

![screen shot 2018-02-23 at fri feb 23 9 11 53 am](https://user-images.githubusercontent.com/1119271/36604008-bf5bf8d4-1879-11e8-8c80-eb5e5c3a77c3.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/post.php?post=11892&action=edit using Firefox 58.0.2 on macOS 10.13.3.</sup>
