### ISSUE TITLE
Store: Update Setup to Use Checklist Component

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#22767]
For hack week, @jameskoster suggested we update the dashboard setup wizard to use the `<Checklist />` [component](https://wpcalypso.wordpress.com/devdocs/design/checklist)

**Comment by ryelle** [comment]
This was already reported in #21322 – which also has my note about bringing in our accessibility updates 🙂

**Comment by timmyc** [comment]
Thanks @ryelle - closing this in favor of #21322
