### ISSUE TITLE
Unnecessary (?) new window for Customizer, from Themes

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22765]
On the `https://wordpress.com/themes/{site}` route in Calypso, there is a `Customize` button in the top right. It opens (unexpectedly, no indication) in a new window. Once you're done customizing, and click the [x] in the top-left of the Customizer, you're dropped back on that same Themes page, but now you have 2 windows/tabs showing that.

![screen shot 2018-02-23 at 9 02 51 am](https://user-images.githubusercontent.com/108942/36603567-618adcee-1878-11e8-8a77-9c3885960db6.png)

Can we just open it in the same window?

**Comment by MichaelArestad** [comment]
Tentatively assigning myself. I think I can fix this.

**Comment by johnHackworth** [comment]
Happy to handle the wheel to michael! Let me know if you need dev support

**Comment by ockham** [comment]
I'm working on some themes flows now, and I think I know where to fix this. Stealing this from you @MichaelArestad 😬

**Comment by folletto** [comment]
Historical note: this was originally done because customizer on Core didn't drop the user back to the same page, but it was left stranded on WP Admin. I'm however not exactly sure when this changed. Nice to see! :)

**Comment by ockham** [comment]
> I'm however not exactly sure when this changed.

I think it has worked for a while, but you can't see in a local dev environment. Added the following note to #22985:

> _Note that in your local dev environment, clicking the 'X' (close) button in the customizer's upper left corner will have you end up at the site's fronted. However, this works fine in other environments. The reason is that we're using a `return=` qarg, for which we had to whitelist a number of domains (`wordpress.com`, most notably) through a filter in Jetpack. We just didn't include `calypso.localhost:3000` in that whitelist._

**Comment by MichaelArestad** [comment]
@ockham Nice! Thanks!
