### ISSUE TITLE
Activity Log: Icon colors for connect/disconnect

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22773]
Since Jetpack connecting/disconnecting is a pretty major event, I think disconnection should use red, and connection should use green.

![36600904-dc8199ea-1870-11e8-8a5c-0508d951e777](https://user-images.githubusercontent.com/108942/36613545-0001704a-1897-11e8-8da3-957865153aa9.png)

**Comment by eliorivero** [comment]
Fixed in 170672-wpcom
