### ISSUE TITLE
Editor: publish confirmation should show post permalink at time of publish (not site home URL)

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#22778]
#### Steps to reproduce
1. Starting at URL: /posts
2. Create a new post.
3. Publish it — and note the URL to your site in the success message.
4. Now update the post — and note the URL is now the post permalink.

#### What I expected
To be able to click the success message link and go directly to the post permalink the first time I publish the post.

#### What happened instead
When publishing a post for the first time, the post publish link sends me to my home URL (website root).

Then, every time after that, when I update the post, the link sends me to to the post permalink.

Can we make the first save also point to the permalink?

#### Screenshot / Video

First time — the link point to `https://lancetest35.wordpress.com/`:
![screen shot 2018-02-23 at 16 05 30](https://user-images.githubusercontent.com/66797/36621051-62c5487a-18b3-11e8-8d27-bbd30e290489.png)

Aften an edit, the link points to `https://lancetest35.wordpress.com/2018/02/23/new-post-number-355/`:
![screen shot 2018-02-23 at 16 05 59](https://user-images.githubusercontent.com/66797/36621073-78845372-18b3-11e8-99c5-a1ee2e67a925.png)

#### Context / Source

Found via #reallife #dogfooding aka "wine tasting" by @johnmaeda. Thanks JM for #livesharing and #flowsharing your experiences.

**Comment by lancewillett** [comment]
CC @Automattic/tanooki for triage.

**Comment by mattsherman** [comment]
@Automattic/tanooki will address this.
