### ISSUE TITLE
Reader: Can't block Jetpack sites from Lists and tags

### ISSUE THREAD

**Issue by charliescheer** [Automattic/wp-calypso#22780]
When you are working in the reader it is possible to block sites from appearing in your list or tag feeds, however currently if you try to block a site that is connected to the reader through Jetpack you will get an error message telling you that it is not possible to block that site.  It works fine for wpcom sites but not jetpack.

1. When looking at sites in the Reader, if you go to one of your lists or tags you should have the ability to block a site from appearing in that list or tag
2. Find a jetpack site that appears in one of your tags or lists and click on the options button, you should see block site.
3. Click on block site and an error Sorry their was a problem blocking that site appears

Chrome on Mac OS 10.13.3, WordPress iOS 9.3

Image of the error in iOS (was tested in Calypso as well)

<img src='http://cld.wthms.co/fL9XYY+'>

This issue was originally reported to me in this Helpshift issue https://automattic.helpshift.com/admin/issue/261593/

**Comment by westi** [comment]
I tested this in Calypso to verify the experience after finding a "simple" way of finding a Jetpack site.

Search: https://wordpress.com/read/search?q=ma.tt
Look for a post from @beaulebens :)
Try and block his site
You get an error pop up after the sucess message displays and then everything resets back.

In Production I can do the above - I see a block link but it doesn't work
In Staging I can't do the above - I don't have a block option

The backend code, explicitly excludes Jetpack sites - but it probably should support them.
The UI code ( https://github.com/Automattic/wp-calypso/blob/5e5c0259ea26c6b4bc082de244dee6cfec657952/client/blocks/reader-post-options-menu/index.jsx#L135 ) looks like it may be making incorrect decisions in Staging - It displays me an Edit link for Beau's post.

**Comment by westi** [comment]
> due to the number of posts this site is publishing almost all posts are appearing in combined cards which don't show the option to block the site, making it difficult to do so even if blocking did work.

You can blog a site from the 'blog' view in the reader e.g. https://wordpress.com/read/blogs/122301668 but of course it won't currently work because JP blocks are not supported.
