### ISSUE TITLE
Reader: when using Light color scheme, gray fade is visible on tag remove icons 

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#22796]
It looks like Color Schemes are in the process of being added to Calypso (https://github.com/Automattic/wp-calypso/pull/17200) - I can see them on wpcalypso but not production. When I choose the 'Light' color scheme, the fade on the tag remove 'x' button is visible:

![unnamed](https://user-images.githubusercontent.com/17325/36654766-d5f1b0ca-1b12-11e8-9a7b-dfbb3c0fc188.jpg)

Color Scheme can be chosen at https://wpcalypso.wordpress.com/me/account:

<img width="546" alt="screen shot 2018-02-26 at 4 35 00 pm" src="https://user-images.githubusercontent.com/17325/36654810-073c5284-1b13-11e8-84aa-c58b7b46a583.png">

**Comment by rachelmcr** [comment]
Work on Color Schemes was paused/stopped partway through development, before launching to production (internal ref: p58i-6Iy-p2). There are some other known issues (https://github.com/Automattic/wp-calypso/issues/20154, https://github.com/Automattic/wp-calypso/issues/22337) that would also need to be addressed if we pick this back up again.

**Comment by bluefuton** [comment]
Thanks @rachelmcr! As we've paused work on the Color Schemes feature, I'll close this one for now.
