### ISSUE TITLE
Export: Add Guided Transfer to Calypso

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#2279]
Currently newer users trying to purchase GT are being redirected to Calypso preventing them from purchasing. In the short-term, we've created a way to purchase from the support page:
https://en.support.wordpress.com/guided-transfer/

It would be great to have this built into Calypso Store. 

See: 7023-wpcom

**Comment by fabianapsimoes** [comment]
cc @mikeshelton1503 what's your vision for this?

**Comment by mikeshelton1503** [comment]
There hasn't been any real discussion about it. Likely it will fit into settings somewhere. The export features within Settings are being worked on so it could fit in there.

ATM it's not something that's on our near or even distant radar simply based on other priorities.

cc @breezyskies

**Comment by breezyskies** [comment]
This is not likely something we will get to any time soon due to other priorities. As @mikeshelton1503 mentioned, at this point we've only had very vague discussions about it being worked into the export flow (or other contextual places).

**Comment by fabianapsimoes** [comment]
OK, so I'll close this issue for now since this likely won't belong in Store itself.

**Comment by BandonRandon** [comment]
Reopening this and moving it to export. I fear the danger in closing it is that we may forget when the time comes to add GT.  I'm also assuming that GT will use the same checkout flow via Store even if the button itself is on the Settings or Export pages.
