### ISSUE TITLE
Store: Stats: Referrers: Rename "none" → "organic"

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#22795]
![screen shot 2018-02-26 at 1 19 26 pm](https://user-images.githubusercontent.com/1922453/36649335-2f11c896-1b01-11e8-8364-2d84d9920bb0.png)

"none" isn't as descriptive as "organic". Lets change this on the backend

**Comment by justinshreve** [comment]
Addressed in D10460-code.
