### ISSUE TITLE
Purchases: Wrong price in cart 

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#228]
@wensco was testing out something for us with expired domains when she noticed that her cart total was incorrect:

<img width="246" alt="dpfbx9wn-b-3000x3000" src="https://cloud.githubusercontent.com/assets/275961/11339404/4a6add6c-91f1-11e5-8138-9086d7337ac2.png">

$80 + $18 != $93

I could not replicate but I do not have an expired domain to test with. Also worth mentioning that the missing difference in $5 which is the cost of registration.

**Comment by fabianapsimoes** [comment]
We haven't had more reports of this issue, so I'll close this for now. Feel free to reopen if you see it happen again.
