### ISSUE TITLE
People: Logged-out acceptance of invite to known user prompts account creation

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#2280]
When an invite is sent to a known user, clicking on the Accept Invite button send that user to a signup flow. While there is a link at the bottom to sign in, we should be doing the opposite; prompting with a login flow and giving the option to sign up below. Currently, the confusing signup prompt (along with an error from the pre-filled email) might present some legitimacy questions to the user.

![screen shot 2016-01-11 at 11 24 53 am](https://cloud.githubusercontent.com/assets/8002138/12242402/1d3b9fb2-b856-11e5-9655-945fb9663146.png)

Reproduce:
1. Invite an existing user to a site.
2. Accept the invite in a logged-out browser.

**Comment by ebinnion** [comment]
cc @rickybanister

**Comment by lezama** [comment]
good catch

**Comment by rickybanister** [comment]
Yes, if the invite email matches the current logged in user they obviously don't have to sign in or do anything, they can just accept.

If the invite is a known user (logged out) we should be presenting a sign in form and pre-fill the email address.

If we don't know the email address we would default to the sign up form, with links in the footer to switch users (the email would have to be validated in this case, but we allow users to accept as a different user).

**Comment by ebinnion** [comment]
> Yes, if the invite email matches the current logged in user they obviously don't have to sign in or do anything, they can just accept.

If the user is logged in, regardless if it's the same person that was invited or not, the user can accept the invite.

> If the invite is a known user (logged out) we should be presenting a sign in form and pre-fill the email address.

We don't :disappointed:. Although, we can definitely look into this.

**Comment by designsimply** [comment]
I agree it has the potential to be a confusing flow. Because it doesn't completely break the flow (it's still possible to click "log in now" and sign in), I switched this issue from `[Type] Bug` to ` [Type] Enhancement`.
