### ISSUE TITLE
People: Direct viewers/followers to the site they were added to after accepting an invitation

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#2281]
After users accept the invitation to become a viewer/follower on a site, they are directed to the WordPress.com Reader without any success message or link to the site they were added to. There is a link on the page to accept the invitation, but if the user didn't open/bookmark it at that point there isn't a clear way for them to get to the site.

Steps:
1. Invite a user as a viewer on a private site, or a follower on a public site
2. With a different account, click the Accept Invitation button in the email
3. Note that on the Calypso accept invitation page, there is a link to the site. Accept the invitation.
Result: You are directed to the Reader with no success message or way back to the site

I found the same results for both viewers and followers, both when I created a new account and when I was logged in to an existing account when accepting the invitation. Since viewers/followers don't automatically follow the site they are added to in the Reader, there's no clear way to find the site after accepting the invitation. Since the invitation page says that the user will receive updates if they accept the invitation, one solution would be to have them automatically follow the site they are added to.

**Comment by ebinnion** [comment]
Thanks for the report @rachelmcr. Previously, we did show a notice after accepting an invitation, but @lezama mentioned that I might have broke this in #2255.

I'll circle back once we get the notice working again.

**Comment by lezama** [comment]
#2273 should put the notices back

**Comment by lezama** [comment]
notices are back, merged #2273

**Comment by rachelmcr** [comment]
Thanks! I tested and confirmed that I get a notice after accepting the invitation to become a viewer or a follower. I did see that the notice only includes the site title, not a link to the site, so a further enhancement might be to link the site title in the notice to the site.

**Comment by ebinnion** [comment]
@rachelmcr - I created #2337 to track linking the site title. Closing this issue.
