### ISSUE TITLE
Sharing: turning "Show Like Button" on for the site turns "Show Like Button" off for individual pages

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22813]
Steps to reproduce:

1. Start with the My Sites > Sharing > Sharing Buttons > "Show Like Button" option unchecked.
1. Go to My Sites > Site Pages > Add.
1. Add a title and body text.
1. Go to Page Settings > Sharing and check the "Show Like Button" option.
1. Publish the post.
1. Repeat with a second page if desired.
1. Go to My Sites > Sharing > Sharing Buttons.
1. Check the option for "Show like button" and save changes.
1. Go back to My Sites > Site Pages and check to see if the page created in step 2 is checked or unchecked.

<strong>Result:</strong> if you have a page with the "Show Like Button" option checked and you change the overall site "Show Like Button" setting to checked, the page option for "Show Like Button" will be turned off.

<strong>Video:</strong> [3m16s](https://cloudup.com/csz_YOCH-L7)

![screen shot 2018-02-26 at mon feb 26 9 53 47 am](https://user-images.githubusercontent.com/1119271/36683832-dfddb89a-1adb-11e8-9576-e125f2568d3d.png)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/11902 using Firefox 58.0.2 on macOS 10.13.3.</sup>

Question: Should toggling the "Show Like Button" in the main Sharing Settings also toggle the "Show Like Button" option for all individual posts and pages on the site?

**Comment by andfinally** [comment]
Hi, I can reproduce this issue. I'm trying to figure out what the logic is supposed to be. I'd say the main use of the site setting is to show the like button on all posts, irrespective of the setting on individual posts. So a positive site setting should override whatever's set for the post.

But you should also be able to add a like button on certain posts when there's no site-wide like button, so an unchecked site option shouldn't override a checked post option.

This would mean that to remove the like button from all posts you'd have to uncheck the site setting and also uncheck the option on each post that had it checked.

Maybe it should work like:

Site option on
Post option off
- Show like button
- Post option checked and greyed out

Site option on
Post option on
- Show like button
- Post option checked and greyed out

Site option off
Post option on
- Show like button
- Post option checked

Site option off
Post option off
- No like button
- Post option unchecked

**Comment by rachelmcr** [comment]
Related Jetpack issue: https://github.com/Automattic/jetpack/issues/2044
