### ISSUE TITLE
Domains: Transfer: Include remaining days for the end of prohibited period.

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#2282]
As @klimeryk mentioned while reviewing #2258 , once the domain is prohibited from transferring since it is new or recently transferred, it might make sense to add the registration date or the remaining days until the prohibition ends to help the user.

I think it's a nice addition, would definitely help the user feel less confused, but on the other hand I think it is pretty rare (no data to back up, just speculation) for a user who registered a domain in the last 2 months to decide to transfer out. 

Open for discussion / inputs.

**Comment by klimeryk** [comment]
This has been fixed in the meantime 🙇
