### ISSUE TITLE
Jetpack Onboarding: Edit subtitle copy on Contact Form step

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#22824]
In #22585, we changed the `formatted-header__subtitle` copy that mentions "Contact us" page creation in addition to updating the new Jetpack-specific `formatted-header__title` copy on the Contact Form step of JPO. 

The correct title/subtitle copy should be this (edited after chatting with Rick in Slack about the verbiage):

`formatted-header__title`: **Let's grow your audience with Jetpack**
`formatted-header__subtitle`: A great first step is adding a Contact Us page that includes Jetpack’s contact form. Create a Jetpack account to unlock this and dozens of other Jetpack features.

Screenshot:
<img width="614" alt="screen shot 2018-02-26 at 2 47 19 pm" src="https://user-images.githubusercontent.com/204742/36697333-fa40b912-1b03-11e8-8881-493f982e1a1c.png">

**Comment by tyxla** [comment]
Addressed by #22843.
