### ISSUE TITLE
Activity Log: move progress/success/fail dialogs above the date nav

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22851]
We should move the progress/success/fail dialogs above the date nav, since they're not directly related. cc @MichaelArestad @rickybanister 

### Before

![image](https://user-images.githubusercontent.com/390760/36739470-eb25b872-1bd7-11e8-8cc9-5d7740e4d9b5.png)

### After

![image](https://user-images.githubusercontent.com/390760/36739613-4281bf94-1bd8-11e8-982b-6a2c5cddf4e1.png)

**Comment by rickybanister** [comment]
Good catch!

We allow customers to interact with the nav while performing a restore, correct? If so and even if not, this suggestion makes more sense.

**Comment by MichaelArestad** [comment]
This makes perfect sense. I've been looking at this every day for months and didn't notice. Gotta get my vision checked.
