### ISSUE TITLE
Activity Log: Mobile view fixes

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22869]
3 hopefully quick fixes for viewing the Activity Log on a mobile/small screen:

- [x] Not currently displaying the page title (should just say "Activity" right under the site title).
- [x] No month navigation icons shown to go back/forth.
- [x] Weird wrapping of the first date/"Today" card

<img width="406" alt="dented_reality_ _wordpress_com_and_new_issue_ _automattic_wp-calypso" src="https://user-images.githubusercontent.com/108942/36769987-ed6da784-1c04-11e8-9bb0-b6b8692f12fe.png">

**Comment by keoshi** [comment]
> Not currently displaying the page title (should just say "Activity" right under the site title).

This is the expected UI:

- WP.com masterbar
- Site card
-  Tabs fold into a dropdown, which is showing the active view `Activity`

> Weird wrapping of the first date/"Today" card

Related: https://github.com/Automattic/wp-calypso/issues/21333

**Comment by beaulebens** [comment]
Within the Site Card, every other section shows a section heading, here are a few samples:

![screen shot 2018-02-28 at 6 05 53 pm](https://user-images.githubusercontent.com/108942/36821808-0d4099c4-1cb2-11e8-8b97-5b8eba9bd9eb.png)
![screen shot 2018-02-28 at 6 06 14 pm](https://user-images.githubusercontent.com/108942/36821815-155de2ba-1cb2-11e8-9f57-43e7dc89dd46.png)
![screen shot 2018-02-28 at 6 06 31 pm](https://user-images.githubusercontent.com/108942/36821820-2032f0ea-1cb2-11e8-9a1d-05434343d5ec.png)

So I guess actually in this context, technically the thing that should be shown in that Site Card is "Stats" while "Activity" lives under the "Stats" menu.

**Comment by keoshi** [comment]
Gotcha! Yeah, the `<h1 class="current-section__section-title"></h1>` tag is empty.

We must not be passing the section title prop here: https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/components/sidebar-navigation/index.jsx#L39

**Comment by keoshi** [comment]
> No month navigation icons shown to go back/forth.

Addressed in: https://github.com/Automattic/wp-calypso/pull/22949

**Comment by eliorivero** [comment]
This one should be fixed as well

https://github.com/Automattic/wp-calypso/issues/23546
