### ISSUE TITLE
People: Viewers tab is not visible on private site in invites section

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#22865]
<img width="838" alt="screen shot 2018-02-27 at 1 56 49 pm" src="https://user-images.githubusercontent.com/1270189/36757334-273e13ac-1bc6-11e8-8625-4e5ad78babe7.png">

<img width="814" alt="screen shot 2018-02-27 at 1 57 58 pm" src="https://user-images.githubusercontent.com/1270189/36757369-3dd58852-1bc6-11e8-92c1-5f2ad111156f.png">

1. Make your site private
2. Navigate to https://wordpress.com/people/invites/{yoursiteslug}
3. Verify that the Viewers tab is not visible
4. Switch to another subtab like followers

**Comment by mattsherman** [comment]
Interesting. Good catch @gwwar! @Automattic/tanooki will address this.
