### ISSUE TITLE
Plans: upgrading your Jetpack plan sends a 'cancellation' email for your old plan

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#22878]
We should be suppressing the cancellation email if the customer chooses to upgrade their plan.

They should only receive 'welcome to your new awesome plan' communications. 

![image](https://user-images.githubusercontent.com/437258/36793206-cba7a0e4-1c6a-11e8-8016-13fd3698a74f.png)

**Comment by ebinnion** [comment]
Patch here to fix the issue: D10672

**Comment by ebinnion** [comment]
Deployed in r171293-wpcom.
