### ISSUE TITLE
Store Stats: Consider Setting Default View to Week

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#22889]
Related to discussion in #21752 around how referrer data is not always fresh in the default day/today view of Store Stats. In lieu of littering that PR with a bit of a tangent discussion - it seems like this topic deserved its' own issue.

@avivapinchas had an interesting idea in a p2 discussion:

> FWIW – Google Analytics gets around this problem by making the default period 7-days, ending with yesterday. The added benefit is that you don’t see partial days in the view, which can skew things.

The notion would be to default the Store stats view to the week unit, with a `startDate` of today - 7 days. So visiting Store stats right now would default to https://wordpress.com/store/stats/orders/week/oregonpaws.blog?startDate=2018-02-21 for me.

/cc @greenafrican @psealock for your thoughts on this

**Comment by avivapinchas** [comment]
> with a startDate of today - 7 days. So visiting Store stats right now would default to 

Shouldn't it be today - 8, so it runs for the week up until yesterday?

**Comment by greenafrican** [comment]
@timmyc 
> The notion would be to default the Store stats view to the week unit, with a startDate of today - 7 days.

Yeah, 8 as @avivapinchas mentions above. In general, I think this is a good idea given that, as it stands, all the tracking data will only be available for yesterday.
