### ISSUE TITLE
Plans Page: no information provided by default on mobile

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#229]
When viewing either .org or wpcom plan pages, you are not actually told anything about any of the available plans by default, other than how much they cost.

Can we just expand the sections by default, since they're not that long? Or at least expand one of them, perhaps the "most popular" Premium plan?

Here's what each plans page looks like:

![screenshot_20151119-123231](https://cloud.githubusercontent.com/assets/11487924/11281352/3f4d849c-8ec8-11e5-860e-f2cdbbb30c14.png)
![screenshot_20151119-123220](https://cloud.githubusercontent.com/assets/11487924/11281353/3f523e42-8ec8-11e5-873a-9d7a772f7ac7.png)

(aka the same)

Here's what it would look like with the Premium plan expanded:

![screenshot_20151119-141738](https://cloud.githubusercontent.com/assets/11487924/11281440/99d052e6-8ec8-11e5-9d79-91f01e6abf4e.png)
![screenshot_20151119-141754](https://cloud.githubusercontent.com/assets/11487924/11281441/99d523f2-8ec8-11e5-9dff-a0a1e0276798.png)

**Comment by fabianapsimoes** [comment]
cc @breezyskies for design input.

**Comment by breezyskies** [comment]
Thanks for the report @v18! The mobile browser click through rate for plans is currently pretty similar to what we see on desktop. I'd like to readdress the mobile view at some point in the future on a more holistic level, but I don't think we're going to get to this soon.

**Comment by fabianapsimoes** [comment]
I'll close this for now based on Brie's input.
