### ISSUE TITLE
Activity Log: New month == no events, and no access to history

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22917]
On a Jetpack site which has historical events, and access to the Activity Log, on the first day of the month I see this:

![screen shot 2018-03-01 at 10 44 11 am](https://user-images.githubusercontent.com/108942/36860079-a177cf32-1d3d-11e8-8eae-e21bf2999f81.png)

I understand that not displaying any events is a byproduct of our "current month" oriented display (separate problem/issue), but the real kicker here is that we're also not showing any navigation arrows for me to go and look at last month (aka less than 12 hours ago).

We need to include the arrows there, unless there's really no historic events.

**Comment by beaulebens** [comment]
Also note that as soon as a site has any activity, you can see the nav arrows, as shown here on a different site:

![screen shot 2018-03-01 at 10 54 27 am](https://user-images.githubusercontent.com/108942/36860588-edbbaf70-1d3e-11e8-8d31-f1a19e919cb7.png)

**Comment by Viper007Bond** [comment]
The issue is that `oldestItemTs` is set to `Infinity`, so `hidePreviousArrow={ monthStartTs <= oldestItemTs }` evaluates as `true`.
