### ISSUE TITLE
UI: Discrepancies in Calypso Selector Jetpack Flow

### ISSUE THREAD

**Issue by joendotcom** [Automattic/wp-calypso#22919]
# Summary

This screen:

<img width="1191" alt="screen shot 2018-03-01 at 18 48 39" src="https://user-images.githubusercontent.com/8905369/36860381-61f14bec-1d81-11e8-8e7d-537ca0f6cbd0.png">

...could use a few small UI/text updates:

### Screenshot

![a 1 it s not a link it s a button](https://user-images.githubusercontent.com/8905369/36860623-1bae5822-1d82-11e8-9044-c343ad51caed.png)
![a 2 activate plugin button not activate link](https://user-images.githubusercontent.com/8905369/36860624-1bce88e0-1d82-11e8-81ef-0bdd58651170.png)

### Suggested text update:

> Then you'll click the blue "Activate" link to activate Jetpack

 → Then click the blue "Activate Plugin" button to activate Jetpack.

### Screenshot
![b it s not _install_ but _install now_ inconsistent instruction vs ui](https://user-images.githubusercontent.com/8905369/36860720-5f4e32dc-1d82-11e8-891d-8e99b9011b51.png)

### Suggested text update:

> Click the blue install button.

 → Click the blue Install Now button.

## c) "Set up Jetpack" instead of "Connect to WordPress.com"

![d this button should be called set up jetpack](https://user-images.githubusercontent.com/8905369/36860869-c319170a-1d82-11e8-98e0-aa9877c2ac2e.png)

![d set up jetpack screen](https://user-images.githubusercontent.com/8905369/36860888-cd0527fe-1d82-11e8-8564-22b204b16044.png)

### Suggested text update:

> Finally, click the "Connect to WordPress.com" button to finish the process.

 → Finally, click the "Set up Jetpack" button to finish the process.

#### Context / Source

#manual-testing

**Comment by joanrho** [comment]
@joendotcom These are being already addressed here p7rd6c-1dS#comment-2114 cc @seear
