### ISSUE TITLE
Simple Payments: Upsells for Jetpack users should refer to Jetpack plans not WP.com plans

### ISSUE THREAD

**Issue by pmaiorana** [Automattic/wp-calypso#22928]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/post/paulmaiorana.com::notes
2. Click on "+Add" in the toolbar
3. Click on payment button
4. Note the language used in the upsell

Note:  I have since upgraded to a paid Jetpack account, so this issue can no longer be reproduced with my account/at that URL. To reproduce you need to start with a site that is using the free Jetpack plan.

#### What I expected

I expected to see an upsell describing the benefits of upgrading to a paid Jetpack plan.

#### What happened instead

I saw an upsell for paid WordPress.com plans.

#### Browser / OS version

macOS 10.13.3 (17D102), Safari Version 11.0.3 (13604.5.6)

#### Screenshot / Video

http://cld.wthms.co/s25d7Z

#### Context / Source

#dogfooding

**Comment by designsimply** [comment]
Tested and confirmed that trying to add a Simple Payment button to a Jetpack site with a free plan results in an upsell mentioning WordPress.com-specific features such as a domain:

> Upgrade your plan to our Premium or Business plan!
> Get simple payments, advanced social media tools, your own domain, and more.

![screen shot 2018-03-01 at thu mar 1 11 18 19 pm](https://user-images.githubusercontent.com/1119271/36885885-e44f2f30-1da6-11e8-9912-f7700636f896.png)
<sup>Seen at https://wordpress.com/post/boiling-boa.jurassic.ninja while proxied (staging) running WordPress 4.9.4 and Jetpack 5.9-beta using Firefox 58.0.2 on macOS 10.13.3.</sup>
