### ISSUE TITLE
Videomail integration?

### ISSUE THREAD

**Issue by binarykitchen** [Automattic/wp-calypso#2294]
Hello there

I have a cool idea here! How about adding videomail support?
https://github.com/binarykitchen/videomail-client

Check out the live site https://videomail.io which explains it pretty much.

That would enhance the composition of Wordpress forms in the administration enormously. With the videomail client this recording feature can be included anywhere with one Javascript file only. No need for Flash. Works on all modern browsers (except Safari) and even on Androids.

Another good reason is to support Sign Language (Deaf people). They prefer to sign instead of writing, i.E. in a contact form. Here an example: https://binarykitchen.com/contact/action/add/

If you are open to this idea, I am more than happy to assist or even to submit a PR.

Let me know ...

**Comment by lancewillett** [comment]
Thanks for the suggestion. We'll wait on this until we get more votes from folks wanting the same feature.

**Comment by binarykitchen** [comment]
Well, @lancewillett, to get votes, we need to redirect some attention to this ticket. How? Twitter?
