### ISSUE TITLE
Post Notifications: add basic styling for headings and lists

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#22953]
@beaulebens provided this example in p58i-6RB-p2:

<img width="151" alt="screen-shot-2018-01-26-at-5-39-07-pm" src="https://user-images.githubusercontent.com/17325/36910696-590c3312-1e39-11e8-8fd6-417df7d3de65.png">

> “Acquisition” in this case is a heading (H3). It’d be nice to have some controlled formatting for “basic” HTML like that in here.

**Comment by bluefuton** [comment]
@beau also provides this example of lists formatting looking a bit odd:

![screen-shot-2018-03-14-at-10-32-14-am](https://user-images.githubusercontent.com/17325/37633825-c9173058-2c58-11e8-9dfa-e739ccd40c5e.png)

**Comment by beaulebens** [comment]
This is still an issue.

**Comment by kwight** [comment]
Heading alignment has been fixed, with relative sizes upcoming via https://github.com/Automattic/wp-calypso/issues/46111. Lists are being handled in https://github.com/Automattic/wp-calypso/issues/46113. This is all part of 217-gh-dotcom-manage. Closing this as we're tracking in the other issues.
