### ISSUE TITLE
Domains: Plan domain credit shown to users even if not eligible

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#22968]
#### Steps to reproduce
1. Create a test site
2. Purchase a plan
3. Invite a second Administrator
4. Login as user who did not purchase plan
5. Try to use free domain credit to register a domain
6. Proceed to checkout and see you'll have to pay

#### What I expected

If the site has a plan attached, and the domain credit has not been used, I should be able to use that credit.

I see a few possible solutions, either don't show the domain credit to anyone but plan upgrade owner, allow any administrator to use the credit, or provide a message if a user other than the upgrade owner tries to register a domain letting them know another user could register as part of the plan.

#### What happened instead

As the second user on the site who did not purchase the plan I was shown both a nudge to claim a free domain, and when I searched for a domain it showed the domain should be included in the plan. During checkout I saw the domain and privacy listed in the cart on the side with the full price showing, and at checkout I would have been charged for the domain.

#### Screenshot / Video

![second-user-buy-domain](https://user-images.githubusercontent.com/1326294/36937772-b24e6214-1eee-11e8-9c4b-6a614bb4e7fd.gif)

**Comment by vindl** [comment]
@Automattic/payments or @Automattic/cobalt do you know what is the expected behavior here?

1. Only plan owners are eligible to use domain credits.
2. Any user of a site that has sufficient privileges can use the domain credits.

**Comment by aidvu** [comment]
I believe it's 1, as we want both the plan/domain owned by the same user.

Amiright @kelliepeterson / @wensco?

**Comment by vindl** [comment]
Fix proposed in D10855-code.

**Comment by vindl** [comment]
Fix deployed.
