### ISSUE TITLE
Media Library: Treat Google Photos connection as a "Connected App" in settings.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#22974]
When trying to disconnect a Google Photos account from your media library, the connection has to be broken from the "Sharing" page:

![screen shot 2018-03-04 at 15 44 38](https://user-images.githubusercontent.com/10121835/36950962-30a74f84-1fc3-11e8-8523-b015604169e8.png)

Since the connection is "Global", if you connect any Google Photos account to any site, it's accessible via the media library of any of your other sites, it may be more intuitive to add the connection under the Security area's "Connected Apps" page:

![screen shot 2018-03-04 at 15 45 04](https://user-images.githubusercontent.com/10121835/36950974-573786a0-1fc3-11e8-8567-377b2423fd27.png)

That's how the connection is treated on the Google end, in their own security settings, and the other sharing page connections are for users to share content *to* another social network, not bring content in.

The help page is clear it has to be done via the Sharing area:

https://en.support.wordpress.com/photos-from-google/#disconnecting-from-google

But I think Connected Apps would be more intuitive for someone who just stumbled across the feature and has not read the help doc.

**Comment by rachelmcr** [comment]
I definitely agree with this. I connected Google Photos from within the editor's media modal, and I first went to my settings at https://wordpress.com/me/security/connected-applications when I wanted to disconnect it.

I happened to remember seeing it in my site's Sharing settings before, so I went there and successfully disconnected it, but I wouldn't have known to look there based on how I set it up initially. I also assumed based on that behavior that it was only connected on that one site — I didn't realize until now that it's a global connection.
