### ISSUE TITLE
Sharing : Reblog button and Like button not visible

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#22977]
We've got a report that Reblog button and Like button are missing on multiple WordPress.com sites **_only when users choose Japanese as their site language_**.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com > My Sites
2. Go to Sharing > Sharing Buttons
3. Check off one of the options in `Show sharing buttons on` section at least:
https://cloudup.com/c1xeLPzpnpg
4. Check off `Show reblog button` and `Show like button` in `Reblog & Like` section:
https://cloudup.com/cwUSiK-Kiev
4. Go to Settings > General > Language and choose `日本語`
5. Go to Site's URL and navigate to any post, to notice that sharing buttons are nowhere to be found

#### What I expected
Seeing Reblog button and Like button under posts/pages.

#### What happened instead
Reblog button and Like button are not found under posts/pages. I can see only `読み込み中`( which means “Loading” in Japanese):
https://cloudup.com/cELwbRlMiwz

#### Browser / OS version
Tested on Google Chrome, Firefox and Safari.
I can see the issue on both PC and mobile.

#### Reported sites
https://hoehoeneko.wordpress.com/
https://tae1.wordpress.com/
https://shinmei1952.wordpress.com/
https://mshira1973.wordpress.com/

#### Forum thread
https://ja.forums.wordpress.com/topic/3112?replies=4

**Comment by otpidusprime** [comment]
**Another report:**
Site: https://wakasa15thfd.wordpress.com
Ticket: #995773-woothemes

**Comment by rachelmcr** [comment]
I confirmed that the like and reblog buttons appear when I view a post in English, but in Japanese I see the "Loading" message and a console error:

> Uncaught Error: No locale meta information provided.

![screenshot 2018-03-05 12 03 49](https://user-images.githubusercontent.com/8658164/36974144-81881ece-206d-11e8-9c19-9d846fbc7b5b.png)

I spot-checked other non-English locales (Spanish, Hebrew, Russian) and confirmed that the like and reblog buttons are working there, so this seems to be specific to Japanese.

**Comment by rachelmcr** [comment]
Since this is a front-of-site issue, and not an issue within Calypso, I've moved it to 8016-wpcom.

**Comment by molszewska** [comment]
Another report, site's language: Italian.
site: http://321clic.com
https://imgur.com/imDaEDf
switching language to English solves the problem
1019706-zen

**Comment by rachelmcr** [comment]
@molszewska could you please add that report to the wpcom ticket noted above (8016-wpcom)? Thanks! Feel free to ping me in slack if you have any trouble with that.
