### ISSUE TITLE
Jetpack SEO Tools: Add option for Archive Title

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#23002]
Copied from https://github.com/Automattic/jetpack/issues/8918

974268-zen

The Archives setting only has options for Site Title, Tagline and Date:

![image](https://user-images.githubusercontent.com/1990037/36599811-7136d9c4-18a8-11e8-843b-0cc4a715051b.png)

For Custom Post Type archive pages, if you leave it blank, the title structure is:

**Post type - Site Title**

Could we add an option for 'Archive Title' so that the structure can be customized but still include the post type?

**Comment by cathymcbride** [comment]
Since this was already closed once, and there is no information as to why it was re-opened, I'm going to re-close. If a future visitor needs to re-open, feel free! However if yo do, please leave a little note as to why.
