### ISSUE TITLE
Site Settings: Delete Site: Allow users to cancel and remove purchases within delete flow

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#2300]
In #1402 @spncrb mentioned:

>When a user deletes a site, we should offer a simple (maybe a confirmation checkbox and a button?) way to cancel all purchases.

>In the current situation, deleting a site is completely impossible for sites with any upgrades outside of the refund window.

#1402 will now make this task possible by adding a remove link to unsubscribed purchases. However that's not a very straightforward process when want to delete a site and a very lengthy process. So we need to build an option into the delete flow to allow a user to easily cancel and remove their subscriptions.

**Comment by stephanethomas** [comment]
@mikeshelton1503, could you give us more details? Do you have any mockup or more information on how this should look like in the delete flow?

**Comment by mikeshelton1503** [comment]
@stephanethomas I was just reporting the issue to keep it from getting it lost in #1402. Yes I need to provide mockups here but I'm not sure yet the priority here.

cc @fabianapsimoes and @breezyskies to help determine priority. I would think this is on the sooner than later list but now that it's not a blocker for users (pending the changes in #1402) it's not the _highest_ priority.

**Comment by breezyskies** [comment]
I'd call this relatively low priority at the moment, given that it's not blocking users from deleting sites. It's a nice bell-and-whistle piece to loop back to in the future, but not something I think we should invest time in right now.

**Comment by fabianapsimoes** [comment]
I'm with @breezyskies. We should leave this for another moment.

**Comment by fabianapsimoes** [comment]
I'll close this issue, since we already have #3117 open to implement a middle-ground solution for this issue.
