### ISSUE TITLE
Possible coding mistake

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#23009]
Hi,

I am new in React, but I came upon this line and I am not sure what to think about it..

@sirbrillig, you wrote this line...

https://github.com/Automattic/wp-calypso/blob/5534135315e35fcc3e5ed0e46827ab34834bd9ab/client/my-sites/picker/picker.jsx#L52

Is that a shorthand for something, or is that an actual mistake?
Shouldn't it be:

```
if ( isAutoFocused !== this.state.isAutoFocused ) {
	this.setState( { isAutoFocused: isAutoFocused } );
}
```
Sorry if it is not a mistake, I am still on the learning curve, and I don't know all of React's subtilities

Thanks.

**Comment by sirbrillig** [comment]
Hi @millerf! That's using ES6 shorthand property names. Check out [this link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015) to read about the technique. Basically saying `{ isAutoFocused }` is equivalent to `{ isAutoFocused: isAutoFocused }`. Thanks for looking, though. Is there anything in particular with this code that made you think there might be a bug?

**Comment by millerf** [comment]
Thanks for the explanation @sirbrillig, I didn't know this one! Very handy, although quite disturbing :)

I just saw it while scouting for another issue and it just triggered a red flag in my mind. I wondered why it wasn't triggering a syntax issue as well...

Sorry for your time loss, I should have investigated further...

**Comment by sirbrillig** [comment]
No worries! Learning is always a good use of time, and JS moves really fast these days...
