### ISSUE TITLE
Framework: Upgrade to Babel 7

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#23011]
We need to upgrade to Babel 7. This will provide better support for React 16, fragments that allow you to get rid of extra DIVs, and support for JS configuration files.

**Comment by samouri** [comment]
This is pretty close.

1. `wp-calypso`: https://github.com/Automattic/wp-calypso/pull/23026
2. `ICFY`: https://github.com/jsnajdr/icfy/pull/4
3. `wp-desktop`: https://github.com/Automattic/wp-desktop/pull/423
