### ISSUE TITLE
Purchases: Auto-renew email sending even when payment method has expired

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#2301]
@eurello also reported (p2MSmN-4kz-p2):

> I had a user on chat today with the problem @supernovia mentions. They'd received an email warning them that their domain would automatically renew in two days. They logged in to turn that off, but there was no option to do so. Their card was actually expired, so the problem here is two-fold:

> 1.They got an email telling them they'd be automatically renewed when they wouldn't be; and
> 2.There was nothing in the My Purchases UI to indicate that the automatic renewal was already canceled due to their expired card.

If a user's payment method is set to expire before the renewal date their purchase should have been set to the "unsubscribed active state" and the auto renew emails should not send.

> There was nothing in the My Purchases UI to indicate that the automatic renewal was already canceled due to their expired card.

@eurello Do you know what the user was seeing? They should have been seeing a notice at the top of the Manage Purchase screen for that purchase that said their payment method had expired.

**Comment by eurello** [comment]
Unfortunately not, I didn't take the time to log in as the user during the live chat. But here's the chat:

**Comment by eurello** [comment]
https://mc.a8c.com/support-stats/feedback/chat-transcript.php?id=291802

And here's the user's SA: https://wordpress.com/wp-admin/network/wpcom-paid-upgrades.php?action=search&username=marcdefontnouvelle

And the email they received from us: https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2488451

**Comment by fabianapsimoes** [comment]
I haven't seen more reports of this issue. So closing, but feel free to reopen if you see more stuff like this. Thanks!
