### ISSUE TITLE
Help page: livechat form button doesn't use translated language name

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#23037]
We recently added a button on Calypso's help page where users can chat with us **in English** if their dashboard is in another language. Unfortunately, the button doesn't show the word "English" as translated (see screenshot below).

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/account
2. Change your dashboard language to, let's say French
3. Go to the help page to get the chat box: https://wordpress.com/help/contact
4. See the button that's partly translated

#### What I expected

The word "English" to be translated as "anglais"

#### What happened instead

The word "English" remains in English

#### Screenshot / Video

<img width="750" alt="capture d ecran 2018-03-06 a 14 16 40" src="https://user-images.githubusercontent.com/16645645/37034672-5fb4553c-214a-11e8-9ca4-95222bfb8d76.png">

#### Context

Where the code for the button is: https://github.com/Automattic/wp-calypso/blob/05a05f7b20c98764d9cecaf552b195899d6e66f9/client/me/concierge/shared/available-time-card.js#L30

Where the code for the translated language is: https://github.com/Automattic/wp-calypso/pull/20694

**Comment by ramonjd** [comment]
Fixed in  #24195
<img width="810" alt="screen shot 2018-04-19 at 12 41 02 pm" src="https://user-images.githubusercontent.com/6458278/38968500-19d3eada-43cf-11e8-915f-3a11a3da0199.png">
