### ISSUE TITLE
Components: customize react-day-picker

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#23083]
We use an external day picker component, for picking published dates in the editor. 

![screen shot 2018-03-07 at 10 53 18 am](https://user-images.githubusercontent.com/618551/37105824-c34eff4c-21f5-11e8-92a7-2c2ecf993e69.png)

https://github.com/Automattic/wp-calypso/tree/20b63c670ec36b29a593798ad0d1ef5c0a4a531a/client/components/date-picker

We also use noticons to customize the style, and in order to remove the noticons the best approach would be to customize the navbar as described in the `react-day-picker` docs. We'd use gridicons for the left and right arrow.

![screen shot 2018-03-07 at 10 53 04 am](https://user-images.githubusercontent.com/618551/37105805-bb448f4c-21f5-11e8-8697-5136af921fa4.png)

http://react-day-picker.js.org/examples/elements-navbar/

It's a bit over my head, so I'm posting as an issue.

@Automattic/lannister Any advice here would be appreciated!

**Comment by shaunandrews** [comment]
What if we forgo an icon for navigating months, and just use the month abbreviation:

![slice 2](https://user-images.githubusercontent.com/191598/37106613-40fe9f6a-2200-11e8-894b-e0fd3f7c4344.png)

**Comment by drw158** [comment]
That could work!

**Comment by gwwar** [comment]
> What if we forgo an icon for navigating months, and just use the month abbreviation:

cc @Automattic/i18n for 🤔

**Comment by shaunandrews** [comment]
Fortunately, most languages has some form of abbreviations for months: http://library.princeton.edu/departments/tsd/katmandu/reference/months.html

**Comment by ramonjd** [comment]
It's possible to localize month abbreviations. Taking Italian as an example:

```
import i18n from 'i18n-calypso';

i18n.moment( '2018-12-01' ).format( 'MMM' ) // => 'dic' (Dec)
i18n.moment( '2018-05-01' ).format( 'MMM' ) // => 'mag' (May)
```

It looks like it would be easier if they allowed us to define something like `localUtils.formatMonthTitleShort()` in [our props](https://github.com/Automattic/wp-calypso/blob/20b63c670ec36b29a593798ad0d1ef5c0a4a531a/client/components/date-picker/index.jsx#L84), but they [don't](https://github.com/gpbl/react-day-picker/blob/v6.2.1/src/DayPicker.js#L55). 

I haven't tested this, but if we modified out datepicker according to the module's code [example](http://react-day-picker.js.org/examples/elements-navbar/), this might work:

```
const prev = i18n.moment( previousMonth.toISOString() ).format( 'MMM' );
const next = i18n.moment( nextMonth.toISOString() ).format( 'MMM' );
```

Even in their latest version (v7.1.1), the [aria controls](https://github.com/gpbl/react-day-picker/blob/v6.2.1/src/DayPicker.js#L132) aren't localized either. We're using v6.2.1, which still allows the `<Navbar />` override.

**Comment by ramonjd** [comment]
@gwwar @drw158 I found some time to implement this. Let me know what you think #23253
Thanks!

**Comment by designsimply** [comment]
@ramonjd is this issue okay to close since #23253 was merged?

**Comment by designsimply** [comment]
@drw158 thank you!
