### ISSUE TITLE
Showcase: All/Free/Premium toggle activates search field on mobile

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#23097]
#### Steps to reproduce
1. Visit the Theme showcase using a mobile device. 
2. Tap on the `All | Free | Premium` toggle. 

#### What I expected

The page to filter the themes list. 

#### What happened instead

The page _does_ filter the themes list. But it's hard to tell, because focus shifts to the search field. This hides the toggles entirely, and initiates a page jump. This is disorienting and unexpected. 

#### Browser / OS version

iOS Safari, Chrome (+ probably other mobile browsers too)

#### Screenshot / Video

![toggles](https://user-images.githubusercontent.com/1202812/37113116-680b173e-2212-11e8-8485-6db328eb9e36.gif)

#### Context / Source
#dogfooding #manual-testing

**Comment by kjellr** [comment]
We might want to just relocate that toggle out of the search field on mobile anyway — it drastically obscures the search field content: 

<img width="381" alt="screen shot 2018-03-07 at 2 25 35 pm" src="https://user-images.githubusercontent.com/1202812/37113470-760b4060-2213-11e8-8884-edb06a60408c.png">

**Comment by jordesign** [comment]
Closing this as the All/Free/Premium toggle is no longer in place in the showcase
