### ISSUE TITLE
Extra line breaks inserted in editor when updating a published post

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#23098]
A WordPress.com customer reports that the editor sometimes inserts extra line breaks when a post is updated. I cannot reproduce, but the customer says it happens sporadically in Chrome and Firefox and was able to capture it on [this video](https://photos.google.com/share/AF1QipMlnwGX61z3q_FcOVeSEcwYVF8bkIen0bCDsfwhOoviJwdSC35w4WKTpLPahSyUcQ/photo/AF1QipMCBwVkVrKoEvhhaC0E5bDsHtCF6Y8m6JkLQ6wv?key=LW01MFRENVFKZGh3UjViWEZWMzlnODFpdFhVajJn).

The video shows the existing post with no extra line breaks above the YouTube embed, the customer making some unrelated edits, and then updating the post, at which point, the extra line breaks appear in the published post. 

(#995162 for my internal reference.)

**Comment by spncrb** [comment]
More info from user: 

> I wanted to note that this problem only seems to happen on posts that contain one or more YouTube videos that were added by just copying and pasting the short link (the one that shows when you click the share link option on YouTube) to the video which auto-embeds it, and usually the extra spacing only shows above or below the link the video(s); and this sometimes happens on new posts and when editing old posts.

> Also I am on Window 10 64-Bit fully updated (Desktop and laptop), the latest versions of Chrome and Firefox in incognito mode and private mode, the only browser extensions that I use are Ublock Origin and Video DownloadHelper, I use Adguard DNS for our DNS service, and almost all of my posts contain a centered hotlinked image at the top of each post with the image set to open a custom URL when clicked and a clickable link to the source in the caption.

**Comment by galakhyati** [comment]
Additional info from user:

> I forgot to add that I have the images in my post set to open in a new window when someone clicks them or the source in the caption; in my video you can see how I set both to open custom URLs.
