### ISSUE TITLE
Plugins: Disabled install button & tooltips

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#231]
Right now, when users are in a single plugin view, with 'all-my-sites' selected, and the plugin can't be installed in any of the sites, we are not showing the install button at all. We should adopt the same pattern we use when a plugin can't be autoupdated to tell the users what's going on:

![image](https://cloud.githubusercontent.com/assets/1554855/11281999/969275f2-8f16-11e5-9bc8-e65154a2942e.png)

**Comment by enejb** [comment]
This was fixed in https://github.com/Automattic/wp-calypso/pull/872
