### ISSUE TITLE
Sharing menu does not show up in WordPress.com if Publicize is disabled despite Social Buttons enabled.

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/wp-calypso#23114]
## Summary
*Sharing* menu does now show up in WordPress.com if Publicize is disabled despite Social Buttons enabled.

The social buttons can only be configured by accessing the *Configure your sharing buttons* link in Jetpack Settings → Sharing.

## Steps to Reproduce

1. Disable Publicize in Jetpack Settings → Sharing
2. Ensure Sharing Buttons is enabled
3. Go to WordPress.com

### Expected Result
The Sharing menu should appear on the left sidebar to allow users to configure the buttons

### Actual Result
The sharing menu does not appear.

**Comment by rachelmcr** [comment]
I confirmed the issue using the steps above. I have Publicize toggled off and Sharing Buttons toggled on in my Jetpack settings in WP Admin:

![screenshot 2018-03-08 13 29 43](https://user-images.githubusercontent.com/8658164/37153508-d64befd0-22d4-11e8-8dd9-6ee0227a5c23.png)

But in Calypso the Sharing menu doesn't appear in the sidebar:

![screenshot 2018-03-08 13 31 14](https://user-images.githubusercontent.com/8658164/37153610-30f4fc6a-22d5-11e8-8b90-2b6e1d76eb2e.png)

Enabling Publicize makes the Sharing menu appear as expected.
