### ISSUE TITLE
Login: Fix locale propagation

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#23126]
Despite https://github.com/Automattic/wp-calypso/pull/21118 there are still some flows where the login pages don't honor the current locale:

##### Scenario 1

1. Open the [`Login` page](https://wordpress.com/log-in/fr) in French in an incognito window
2. Submit credentials of an account that has 2FA enabled
3. Notice that the [`Verification Code`](https://wordpress.com/log-in/authenticator) page is displayed in English instead of French

##### Scenario 2

1. Open the [`Login` page](https://wordpress.com/log-in/fr) in French in an incognito window
2. Submit credentials of a passwordless account
3. Notice that the [`Magic Link`](https://wordpress.com/log-in/link) page is displayed in English instead of French

We should also verify that SMS codes or emails are sent in the current locale as well.

**Comment by p-jackson** [comment]
This is still an issue in log in, and is not a good experience for non-`en` user's. Especially the notice for checking your email for the magic link, it'd be hard to guess what that page was for given there's no input box.

We're doing some work on the log in page for the Gutenboarding project, perhaps we can fix as part of that.

**Comment by lsl** [comment]
@dlind1 dropped this in your roadmap / new column as I don't think we'll get to this anytime soon and I'm trying to close out #37665.

Feel free to drop it back into Ganon's project board if you don't think you can prioritize this any time soon.

**Comment by dlind1** [comment]
@lsl Yuliyan has fixed it now 🙂
