### ISSUE TITLE
Showcase: Selecting filters causes page jumps.

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#23125]
#### Steps to reproduce
1. Visit the themes showcase ( https://calypso.localhost:3000/themes ) 
2. If testing on mobile, continue to step 3. On desktop, scroll down the page a little before continuing. 
3. Select one of the filter categories (`Feature`, `Layout`, `Column`, `Subject`, `Style`)
4. Select one of the filters from the dropdown that appears.  

#### What happens

When selecting the filter categories and the filters themselves (steps 3 + 4 above), the viewport jumps back to the top of the page. This is disorienting, and obscures the search field + the filters you just selected. 

#### Browser / OS version

Safari, Chrome for iOS + Mac

#### Screenshot / Video

![focus-jumping](https://user-images.githubusercontent.com/1202812/37156960-789340e2-22b5-11e8-8841-afe02abf39f6.gif)

![focus-jumping](https://user-images.githubusercontent.com/1202812/37158765-2d25de9e-22ba-11e8-9918-d77562ebff44.gif)

#### Context / Source

This was discovered while testing #22229. We're moving it into its own issue, since the issue existed before that PR, and will be addressed separately. 

_Note: I originally opened this only for mobile, but later noticed that the same thing happens on desktop too. The issue description has been modified to reflect this._ 👍

**Comment by jordesign** [comment]
This was resolved in the recent work by the Design Selection pod 🎉

Closing as no longer reproducible.
