### ISSUE TITLE
Remove Holiday Snow setting for users of Jetpack 6+

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#23146]
The Holiday Snow feature was [just removed](https://github.com/Automattic/jetpack/pull/9016) from Jetpack for 6.0. We should disable the UI for it in Calypso for Jetpack sites on that version or above.

**Comment by jeherve** [comment]
Closing this as snow is coming back:
https://github.com/Automattic/jetpack/pull/9110
