### ISSUE TITLE
Reader: Post displays different dates in tag stream / search vs. in the Followed sites stream

### ISSUE THREAD

**Issue by nancyhuihuiyu** [Automattic/wp-calypso#23149]
#### Issue Summary
In Reader, the post displays different dates in tag stream / search vs. in the Followed sites stream (p5PDj3-4sb)

#### Steps to reproduce
1. Starting at URL: https://emilyburnsmua.wordpress.com/
1. Follow this site and check the status of this post _[February 2018 Monthly Favorites + Makeup Breakup ](https://emilyburnsmua.wordpress.com/2018/03/02/february-2018-monthly-favorites-makeup-breakup/)_

#### What I expected
In Reader, the post should display the same date in the Followed sites stream, in tag stream and in search.

#### What happened instead
* In the Followed sites stream, the post displays a date of _Feb 27_.
* In tag stream or in search, the post displays a date of _4d ago_. 

#### Browser / OS version
Chrome

#### Screenshot / Video
In the Followed sites stream
![screen-shot](https://user-images.githubusercontent.com/36929963/37179919-30f6ccaa-22dc-11e8-86c2-faad6ea8caae.png)

In the tag Stream
![tag](https://user-images.githubusercontent.com/36929963/37179953-44b7a804-22dc-11e8-91d9-a9a2211f2883.png)

In search
![search](https://user-images.githubusercontent.com/36929963/37179970-4b1b6ff0-22dc-11e8-9c89-a8a4aa1e3459.png)

#### Context / Source
A user reported an issue with this site in the reader.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
