### ISSUE TITLE
Purchases: incorrect cancellation flow for plan added to site by support

### ISSUE THREAD

**Issue by markryall** [Automattic/wp-calypso#23155]
#### Steps to reproduce

1. As a new user with a free site
2. As a happiness engineer, add a plan to that user's free site
3. Visit `/me/purchases` and select the new plan
4. Verify that you see _both_ 'cancel subscription and refund' as well as 'Remove <plan>'

#### What I expected

Only 'Remove <plan>' should appear

#### What happened instead

Both cancellation options appear - 'Cancel Subscription and Refund' as well as 'Remove <plan>'

The plan can not actually be refunded (since there was no payment) so there's just an error if you try to cancel via that flow.

#### Browser / OS version

Any & all - I happened to reproduce this in chrome on Mac OS X

#### Screenshot / Video

<img width="740" alt="screen shot 2018-03-08 at 4 52 35 pm" src="https://user-images.githubusercontent.com/1926/37189386-d8242b3a-239f-11e8-9446-5eef7d8d97b0.png">

#### Context / Source

I think the logic around whether to show the cancel with refund must be slightly incorrect.  If you compare the above to a plan purchased with credits you will see that only the 'Remove <plan>' option appears (which is correct).

**Comment by rachelmcr** [comment]
I couldn't reproduce this with the steps above. When I viewed the purchase at `/me/purchases` I saw "Add Credit Card" and "Remove WordPress.com Personal" as the two options:

![screenshot 2018-03-09 12 08 32](https://user-images.githubusercontent.com/8658164/37206984-c9f347f6-2392-11e8-9174-0f1f71175bd0.png)

Does this only happen after adding a credit card there?

**Comment by markryall** [comment]
Hmm - that is certainly what _should_ happen but not what I was seeing.

I'll attempt to reproduce it again.
