### ISSUE TITLE
Sharing checkbox state not saving when no boxes are checked

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#23172]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/buttons
2. Uncheck all checkboxes under "Show sharing buttons on" 
3. Save Changes

#### What I expected

The unchecked boxes to remain unchecked

#### What happened instead

The checkboxes return to the last state before all the boxes were unchecked. This only happens when all boxes are unchecked.

#### Browser / OS version

Chrome 64.0.3282.186
macOS High Sierra 10.13.3

#### Screenshot / Video

![screen capture on 2018-03-09 at 07-09-51](https://user-images.githubusercontent.com/7596032/37207113-761d5e38-2369-11e8-94e9-ccac245fdce6.gif)

**Comment by rachelmcr** [comment]
Thanks for the report! Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/22811.
