### ISSUE TITLE
Checkout: allow users to add or switch PayPal account for renewal

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2318]
Raised by @eurello 

Would it be possible to add PayPal accounts to the auto renewal options? If someone initially pays with a PayPal account, that information is stored by us for automatic renewal, but if a user wants to change that PayPal account or add a new one, they can't. This is difficult to explain to users -- if we can store one PayPal account for automatic renewal, why can't we store another one?

**Comment by fabianapsimoes** [comment]
Unfortunately, there’s no way to create a new PayPal billing agreement without a new payment. That's why the only way to add a new PayPal account is through a renewal.
