### ISSUE TITLE
Framework: Rename `client` to `app`

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#2319]
Since code in `client/` will be used for server side rendering, as well as client side rendering. Now that we're getting rid of the `shared/` dir — the name of the `client/` directory is misleading. We should rename it to `app`.

I think we'll need to:
- Rename `client` -> `app`
- Find and replace `client` references with `app` 
- Update external repos that depend on the client dir, for example `wp-desktop`
- Update any external docs
- Check the semantics of the top-level directory structure. Does `server` make sense? How do we define `app/`?

@mtias have I missed anything?

**Comment by gziolo** [comment]
What about this crazy idea:

* Rename `client` -> `src`
* Move `server` -> `src/server`
* Keep `extensions` in `src/extensions`

It would help whenever we need to use glob to search for JS files 😛

**Comment by coderkevin** [comment]
Oh man, that would be one *huge* PR.

**Comment by flootr** [comment]
I think this would still be nice to have. What do you think @ehg?
