### ISSUE TITLE
Checkout: Domains: rename domain registration details into contact information

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2320]
Raised by @stephanethomas

A recent translation issue (4088-gh-calypso-pre-oss) with domain **registration details** highlighted something that have been thinking a lot lately. I indeed don't think we should call the data that is requested during the checkout like this any longer. The main reason is that it is called **contact information** in most places:

* [WHOIS](http://whois.icann.org/en/lookup?name=wordpress.com)
* [Wikipedia](http://en.wikipedia.org/wiki/Domain_name)
* [Domains By Proxy](https://www.domainsbyproxy.com/Default.aspx)
* [WWD API](https://img1.wsimg.com/Rex/docs/WWDAPI_WebServicev2_7.pdf)
* Our own [support page](http://en.support.wordpress.com/domains/update-contact-information/)
* Our [own forums](http://en.support.wordpress.com/?s=domain+contact+information) (check out user questions at the bottom of the page)
* [My Domains](https://wordpress.com/my-domains/) page

If we all agree, then we need to update the code as well as the few places where we're using **registration details** to use **contact information** instead. @mattm, @ranh, what do you think?

Comment from @mattm

> :+1: I think it makes a lot of sense to make this change as well. The purpose of "contact information" is a lot clearer than "registration details".

Comment from @ranh

> Agreed, contact information is a better label.

Comment from @fabianapsimoes

> @stephanethomas do you know where else this needs to be updated, apart from the Domain Registration form in checkout?
> 
> ![domainreg](https://cloud.githubusercontent.com/assets/1248436/9630184/c7629468-5178-11e5-81f0-3f8404129193.png)

Comment from @stephanethomas

> I think this is it although the big part of the work will be invisible to users: we'll have to refactor our code to make variables and components names consistent.

**Comment by BandonRandon** [comment]
Closed, fixed in #3490
