### ISSUE TITLE
Editor: Unable to publish now when scheduled for the future

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#23214]
![omg](https://user-images.githubusercontent.com/1883296/37264939-8dbe6018-2586-11e8-93d9-1bb8e2563155.gif)

#### Steps to reproduce
1. Write a post on a site with the timezone set in a future timezone
2. Schedule for the future
3. Save and close the post
4. Open the post and schedule for immediately
5. Get invalid date/time

#### What I expected
To publish a post immediately

#### What happened instead
An error

#### Browser / OS version
Chrome / Windows

#### Screenshot / Video
See above

**Comment by alisterscott** [comment]
Hi @withinboredom 

I was unable to reproduce this, I set a test site to be in Auckland, New Zealand which is 3 hours ahead of my current location. I then scheduled the post, and I was able to come back and publish it without error.

Any other details to what would cause this?

Thanks

**Comment by alisterscott** [comment]
@Automattic/flowpatrol would you mind doing some testing around this?

**Comment by rachelmcr** [comment]
I couldn't exactly reproduce the error, but I do see something similar. Using the steps above, with my site's timezone set to any timezone other than my actual timezone (either east or west of me, selecting a city or selecting the UTC timezone), I was able to successfully publish a scheduled post immediately.

However, I did notice that after hitting the Publish button and before the preview screen appeared, the date selector showed "Invalid date":

![scheduledpostpublishimmediately](https://user-images.githubusercontent.com/8658164/37282904-eb55fdb4-25ed-11e8-9a30-cab9200d53e8.png)

By the time I closed the preview window, though, it had updated to show the correct date and there was no other sign of errors or problems with the post. (It didn't block me from publishing the post as desired.)

I wonder if the US starting daylight saving time is a factor here, but even then I'm not sure why some people can publish successfully while it's a blocker for the original reporter.

**Comment by withinboredom** [comment]
I had it scheduled for 1:27am the next day and tried publishing it at 11:30pm the night before.

I was able to reproduce by changing the timezone such that it's tomorrow:
![image](https://user-images.githubusercontent.com/1883296/37288862-ace955e4-25de-11e8-9750-9967595ac83e.png)

Then scheduling a post for tomorrow (local time):
![image](https://user-images.githubusercontent.com/1883296/37289071-28242c8e-25df-11e8-9cb6-fe15889e84b4.png)

I then go back to calypso (I refreshed the page, fwiw) and then tried to publish immediately and get the same error.
