### ISSUE TITLE
Jetpack Onboarding: Auto-select the site after connecting

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#23217]
After the site is connected, we are not pre-selecting it. This leads to weird behavior if the user clicks on "My Sites" and navigates anywhere else.

We should be pre-selecting the site immediately after connecting in order to provide a consistent experience.

**Comment by ockham** [comment]
Recording some thoughts here:

* This should happen once a user connects their site to WP.com. One option would be to run the `setSelectedSiteId` action post-connection, i.e. as part of the `ConnectSuccess` component. However, this won't select the correct site if it's connected from the start.
* It'd be nice to use the usual tool for the job -- the `siteSelection` middleware, in our JPO routes -- but that will break (i.e. redirect to the site-agnostic route) if the site is _not_ yet connected. So we'd probably have to modifiy the middleware, which could get nasty.

**Comment by tyxla** [comment]
> This should happen once a user connects their site to WP.com. One option would be to run the setSelectedSiteId action post-connection, i.e. as part of the ConnectSuccess component. However, this won't select the correct site if it's connected from the start.

All makes sense. Having this in mind, seems like the best we can do is have this site selection early, either in the controller, or in the component lifecycle methods. Considering the fact that we might be missing the sites in the controller, it would probably be best to do it in the `JetpackOnboardingMain` component lifecycle methods, just like we do it for the onboarding credentials retrieval redirection.

> It'd be nice to use the usual tool for the job -- the siteSelection middleware, in our JPO routes -- but that will break (i.e. redirect to the site-agnostic route) if the site is not yet connected. So we'd probably have to modifiy the middleware, which could get nasty.

In an ideal world -- yes, but it is already too complex and I doubt we'd want to continue adding to the pile of logic there. We would need to handle non-connected sites separately, and have some JPO specific logic directly in the middleware. I really prefer avoiding that, and keeping the JPO logic in JPO section.

So, PR coming soon.

**Comment by ockham** [comment]
> best to do it in the `JetpackOnboardingMain` component lifecycle methods, just like we do it for the onboarding credentials retrieval redirection.

I like that idea, and will admit that I didn't think of it. This is becoming the de-facto controller for a lot of JPO specific logic, which I think is fair.

**Comment by tyxla** [comment]
See #23293.
