### ISSUE TITLE
Jetpack Onboarding: Stats is already activated for a connected user

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#23219]
Currently, the following steps require the user to connect in order to be completed:

- Contact form
- Business address (only for Business site type)
- Stats

If the user connects on Contact form or Business address, we display the Stats page, but it is already activated (because it activates by default upon connecting Jetpack) and users inadvertently see the success screen. 

We should be skipping this step in that case, or at least alter the copy to be more relevant.

**Comment by ockham** [comment]
Just to save others the pain: This

```diff
diff --git a/client/jetpack-onboarding/main.jsx b/client/jetpack-onboarding/main.jsx
index 4786a74..c2d440f 100644
--- a/client/jetpack-onboarding/main.jsx
+++ b/client/jetpack-onboarding/main.jsx
@@ -193,7 +193,7 @@ export default connect(
                        STEPS.CONTACT_FORM,
                        isBusiness && STEPS.BUSINESS_ADDRESS,
                        isBusiness && STEPS.WOOCOMMERCE,
-                       STEPS.STATS,
+                       ! isConnected && STEPS.STATS, // Stats are auto-activated upon connection to WP.com
                        STEPS.SUMMARY,
                ] );
                const stepsCompleted = getJetpackOnboardingCompletedSteps( state, siteId, steps );

```

might look promising, but it doesn't cut it: In case the user only connects upon arriving at the Stats step, the 'Success' notice shown afterwards lingers in Nirvana, meaning neither the 'Continue' CTA, nor the 'Skip for now' link work.

**Comment by ockham** [comment]
Might work if we add a criterion to check whether `action === 'activate_stats'`. Will try that now.

**Comment by ockham** [comment]
See #23241.
