### ISSUE TITLE
Billing: translate date at view level rather than in the API

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2321]
Raised by @rralian 

I was looking for instances where we are requiring `moment.js` directly, so we can instead use the `moment.js` version that is incorporated into the i18n mixin (p56BUd-2u-p2). And I noticed that we're doing so in `/client/lib/wpcom-undocumented/lib/me.js`.

But rather than fixing it here, I wonder if we're providing the translation at the right level. I would think the API methods should be passing around raw date/datetime/number data and we should translate that into the appropriate format in the views where we use them. At least I think that's how we should do it when working with a piece of data, versus presentation.

So in my opinion we should move the moment.js logic into the views (and then make sure to use the moment.js instance from the i18n mixin). But let me know if you think there are good reasons to use this approach instead.

Comment from @rads

> I agree; this would be a good change.

**Comment by rralian** [comment]
good suggestion
