### ISSUE TITLE
Checkout: use more readable names when referencing products

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2323]
Raised by @rads

We currently refer to the product names by their slugs, but the slug names are difficult to read due to their inconsistency and abbreviations. For example, Google Apps is `products.gapps`, which is short but pretty reasonable. However, a premium plan is `products['value-bundle']` while a business plan is `products['business_bundle']`. The code would be easier to read with more consistent naming.

cc @stephanethomas

**Comment by janm6k** [comment]
Going through old issues, closing ones that does not look like important one.

Please feel free to reopen if applicable.
