### ISSUE TITLE
Jetpack Onboarding: Visit your site button breaks after connection

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#23248]
#### Steps to reproduce
1. Start Jetpack Onboarding flow 
2. Fill out site title, select personal type of site, set homepage
3. Skip Contact Us Form and Jetpack stats.
4. Click Visit your site button and you are taken to the site homepage
5. Go back to Contact us Form and do the connection to Jetpack. 
6. Continue through flow back to summary page.
7. Click Visit your site button
#### What I expected
I expect to be taken to the homepage of my site

#### What happened instead
Nothing happens. The button does not work at all.

#### Browser / OS version
Chrome 65.0.3325.146/ macOS 10.13.3

#### Context / Source
I noticed that if I am going through the flow and don't do the steps that do the Jetpack connection then the visit your site button works. As soon as I make the connection though, the button stops working. This also happens on business sites. I discovered this while creating some automated e2e tests.

**Comment by tyxla** [comment]
Thanks for the report @bsessions85! A quick fix for this can be found in #23257.
