### ISSUE TITLE
DevDocs: Improve this document on GitHub commits directly to master by default

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#23240]
In devdocs, the current  "Improve this document on GitHub" button leads to some very confusing behavior. When clicked it opens the GitHub edit ui (as expected), and at the bottom of the screen there is a checkbox to decide between commiting directly to master (bad) or creating a pull request (good).

The issue is that the checkbox is checked to create a pull request, but the submit button will commit directly to master.

**repro steps**
1. go to any of our devdocs readme pages like: https://wpcalypso.wordpress.com/devdocs/docs/git-workflow.md#branch-naming-scheme
2. click "improve this document"

**example**
![whattttt](https://user-images.githubusercontent.com/4656974/37297379-eef7642a-25f3-11e8-92b4-7c6980526333.png)

notice how the submit button says "commit changes" instead of "propose new changes"

**Comment by samouri** [comment]
cc @alisterscott

**Comment by alisterscott** [comment]
Mine also shows the "Commit changes" button but the default, for me at least, is "Create a new branch..."

Does choosing the new branch option create a PR?

**Comment by samouri** [comment]
so the problem I'm experiencing is that the checkbox defaults to "Create a new branch" but the button says "commit changes" and will commit directly to master.

**Comment by alisterscott** [comment]
😨 

Sounds like a GitHub bug though?

**Comment by alisterscott** [comment]
I think enabling protected branches with reviewed PR status will solve this issue, since Automattic/jetpack has this and it's not possible to push to master.

See: https://github.com/Automattic/jetpack/edit/master/readme.md

<img width="1033" alt="screen shot 2018-03-13 at 3 01 01 pm" src="https://user-images.githubusercontent.com/128826/37323410-60f10f50-26cf-11e8-882f-ca26040427d2.png">

**Comment by samouri** [comment]
I've emailed GitHub -- I'll report back here after they reply

**Comment by alisterscott** [comment]
Now that I've protected master, I see this:

<img width="1010" alt="screen shot 2018-03-14 at 10 22 46 am" src="https://user-images.githubusercontent.com/128826/37376773-b014690e-2771-11e8-8076-49107ad7fba3.png">

I don't think it's possible to push straight to master any more

**Comment by samouri** [comment]
To summarize my exchange with GH Staff.

I asked: 

> Is it possible to create a link
that makes it so that "create a new branch" is pre-selected as the default?

They replied:

> As far as I know, it shouldn't be possible to do this by visiting a special URL. I reached this conclusion from the fact that when I select "Create a new branch", the URL doesn't change.
> Even if there is a way to make it happen, I wouldn't recommend documenting it and incorporating it into workflow because for any behaviour that is not officially documented, our engineers could change the code one day and it would no longer work. Maybe that is the case here.

---

> Now that I've protected master, I see this:
... That still looks like a bug. Because the "Commit changes" is disabled even though the radio button is correctly filled out.

I'm creating a PR now to remove the query params so that the UI won't lie to future devs.

**Comment by samouri** [comment]
between the new protections to the repo and modifying the edit link in #23409, i'd say this issue is safe to close!
