### ISSUE TITLE
Make Store REST API endpoint localization consistent with the rest of the code

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2325]
Raised by @rads 

We added our own `locale` parameter to get around the lack of `Accept-Language` support in the REST API. We should make sure we're consistent with the other non-Store endpoints in how we handle localization.

Comment from @stephanethomas 

> The REST API now supports this `locale` parameter (p3hLNG-u8-p2) so we should probably remove any unnecessary code from our endpoints.

Comment from @dzver 

> I don't think the locale parameter is needed in logged-in Calypso.
> 
> r119265-wpcom

**Comment by hafizrahman** [comment]
Looked at this yesterday (with @scruffian), and it does not seem to be any right/consistent way to do this at the moment.

**Comment by scruffian** [comment]
I think we should handle this at a higher level, maybe adding a wrapper to wpcom.js so that all requests send a `locale` parameter. What do you think @mtias ?

**Comment by scruffian** [comment]
I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/264
