### ISSUE TITLE
Domain Search: add helpful links when trying to map a domain already mapped at WordPress.com

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2326]
Steps to reproduce:

1. Go to https://wordpress.com/domains/add and select a WordPress.com blog with a mapped domain
1. Search for a domain already mapped to current blog
1. Search for a domain that is mapped to a different WordPress.com blog

<strong>Result:</strong> in both cases, the response says:

> $domain is taken.

This is a search for a domain mapped to the current blog:

![screen shot 2016-01-12 at 12 32 19](https://cloud.githubusercontent.com/assets/1119271/12271357/8ab1b2d4-b928-11e5-92b4-be4745752a43.png)

This is a search for a domain that is mapped to a different WordPress.com blog:

![screen shot 2016-01-12 at 12 32 19](https://cloud.githubusercontent.com/assets/1119271/12271362/8ffdbdb4-b928-11e5-9063-1f2c6b7feeca.png)

From @kriskarkoski

> [The error] could use a link to My Upgrades or My Domains for management if it's on the same account and perhaps a view site link if it's not the right account.

**Comment by klimeryk** [comment]
Small update, the notice has been improved in the meantime (or rather, restored to its proper state) and now reads (in both cases):
<img width="751" alt="screen shot 2016-07-01 at 19 54 39" src="https://cloud.githubusercontent.com/assets/3392497/16529943/c428e13a-3fc5-11e6-977b-6c786423c32b.png">

`This domain is already mapped to a WordPress.com site.`

@kriskarkoski - can you give some additional context on this issue? Is this still a common point of confusion for our users?

**Comment by klimeryk** [comment]
Closing this one as the notice has been improved and should give a better clue about the situation to the user. Please reopen if this is still a common/big pain point for our users :)
