### ISSUE TITLE
Jetpack Onboarding: Apply more Jetpack feel to all illustrations

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#23269]
As specified by @joanrho in https://github.com/Automattic/wp-calypso/issues/23220#issuecomment-372415004, we could make the illustrations have a bit more Jetpack-y feel.

**Comment by joanrho** [comment]
On my to-do list for this week. 🙌

**Comment by joanrho** [comment]
Hey @tyxla! Here are some new Jetpackified illustrations and mockups in context for Steps 2, 3, and 4. What do you think?

https://cloudup.com/cUpCwnbmF02

cc @rickybanister

**Comment by tyxla** [comment]
Nice touch @joanrho, I like the new illustrations 👍 

My two cents: To me, the previous "static welcome page" illustration made a little more sense than the one that's being suggested here (as seen here: https://cloudup.com/iiQBN1GmRnb). Main rationale behind this is that the previous illustration resembled a static home page a little bit more than the new one.

Wondering if we could use the same illustration as before, but just apply some Jetpack love to it?

I'm fine to go with it if you folks prefer it to the previous one.

**Comment by joanrho** [comment]
Thanks for the feedback, @tyxla! The old illustration felt a little dated (it looked like two little browsers inside the larger browser), so I updated the new illustration I made with a full-width hero image. What do you think of this?

Before/After:

<img width="740" alt="screen shot 2018-03-15 at 3 36 17 pm" src="https://user-images.githubusercontent.com/204742/37492400-d6b86538-2866-11e8-879b-b97fb3910ad8.png">

**Comment by tyxla** [comment]
Looks good to me 👍 Will also test the PR you submitted.
