### ISSUE TITLE
Layout: Sidebar missing right border on "View Site" site preview

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#23267]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Select "My Site(s)" from the masterbar.
3. Note the right border on the sidebar (between the sidebar and the content).
4. Select "View Site" to open https://wordpress.com/view/SITE-ADDRESS.

#### What I expected

I expected the right border to be there between the sidebar and site preview.

#### What happened instead

The right border is no longer there for the site preview.

#### Browser / OS version

macOS 10.13.3 / Chrome 65

#### Screenshot / Video

Previous (screenshot from March 8):

![sidebarborderbefore](https://user-images.githubusercontent.com/8658164/37341874-e95f242c-26ba-11e8-8978-6c75c7151173.png)

Current:

![sidebarborderafter](https://user-images.githubusercontent.com/8658164/37341880-ebcfc2f2-26ba-11e8-93ef-5b17a86b134e.png)

#### Context / Source
#visdiff-testing #automated-testing

**Comment by shaunandrews** [comment]
Sure, @designsimply
