### ISSUE TITLE
Plans: Domains: add reroute for misspelled url path lacking tailing s

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2327]
Raised by @bikedorkjon

> For /plans, /upgrades, and /domains, lacking the tailing s in the file path results in a 404, when ideally these should be redirected to the correct path.
> 
> Hat tip @kriskarkoski (p2MSmN-3kK-p2)

**Comment by designsimply** [comment]
I tested the following urls:

* https://wordpress.com/plan → 404
* https://wordpress.com/plans — no redirect needed
* https://wordpress.com/upgrade redirects to https://wordpress.com/plans
* https://wordpress.com/upgrades redirects to https://wordpress.com/plans
* https://wordpress.com/domain → 404
* https://wordpress.com/domains — no redirect needed

Result: `/plan` and `/domain` still return a 404 response and need to be setup as redirects

**Comment by designsimply** [comment]
Related: 10182-gh-calypso-pre-oss

**Comment by fabianapsimoes** [comment]
@designsimply I believe this might require a systems request instead.

**Comment by rralian** [comment]
@fabianapsimoes Correct, this will require a system request as well as some work to handle the routes in calypso. We can start work on the calypso routing now and get that ready prior to the systems request.

**Comment by fabianapsimoes** [comment]
@rralian seems @lamosty also started some work on this with https://github.com/Automattic/wp-calypso/pull/4042.

**Comment by klimeryk** [comment]
This has been stale for a while and I have not heard about related issues so closing it.
