### ISSUE TITLE
Jetpack Onboarding: Add Jetpack logo to the rest of the screens

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#23270]
As specified by @joanrho in https://github.com/Automattic/wp-calypso/issues/23220#issuecomment-372415004, we could add the Jetpack logo to the rest of the steps.

**Comment by tyxla** [comment]
My question here is: do we want to add the Jetpack logo to all screens? My initial thinking was that we only want to do it for steps where we require Jetpack connection. Maybe it is a good idea to loop in the rest of @Automattic/jetpack-design folks here.

**Comment by rickybanister** [comment]
Adding the Jetpack logo to every screen is not really appropriate. This flow is provided by us as a kind of courtesy and only the Jetpack steps are jetpack-related.

**Comment by tyxla** [comment]
Thank you Ricky 👍

**Comment by joanrho** [comment]
I don't agree with @rickybanister here, since JPO is brought to users by Jetpack, but I understand the decision to keep it out of the way on certain steps.

**Comment by joanrho** [comment]
@tyxla I spoke with @rickybanister about this just before and we agreed that we will only have the Jetpack logo on the Jetpack-specific screens and keep the CTA buttons blue for the primary ones and white for the ones inside the white boxes.

**Comment by tyxla** [comment]
Sounds good, thanks for the heads up.
