### ISSUE TITLE
Myanmar phone numbers not validating for 2FA

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#23276]
Adding a phone number with a "9-" after the Myanmar (Burma) country code returns a validation error for 2FA.

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/
2. Go to Security
3. Click Two-Step authentication > Get Started
4. Select “Myanmar (Burma)” in Country code
5. Enter a phone number (minus country code) in the following format: 9-XXXXXXXXX
6. Click “Verify via SMS” or “Verify via App”

#### What I expected

To be prompted to complete the verification process.

#### What happened instead

I saw the error, “That phone number does not appear to be valid”. It appears we only support phone numbers without 9- after the country code.

#### Browser / OS version

Chrome
Firefox
Safari

#### Screenshot / Video

![myanmar-2fa](https://user-images.githubusercontent.com/11627765/37356597-a876f97c-26e6-11e8-8735-3f56f846da00.jpg)

#### Context / Source
1011629-zen

#user-report
#manual-testing
p1520869751000532-slack-triage

**Comment by gemmagarner** [comment]
Similar issue with Thailand phone numbers: https://github.com/Automattic/wp-calypso/issues/21862

**Comment by rachelmcr** [comment]
I checked how we validate Myanmar phone numbers: https://github.com/Automattic/node-phone/blob/6be6549b03137f2cca01e202250bf2590750119e/lib/index.js#L1124

Numbers have to start with `9` but we only accept phone numbers with 8 numbers and the format you mentioned (`9-XXXXXXXXX`) is 10 numbers. It looks like we should probably be accepting numbers with at least 8-10 digits but I haven't confirmed that.

**Comment by gpmw** [comment]
This ticket 1011629-zen has come back around after being on hold since March 13, 2018. Just checking to see if there is any progress.

Thanks

**Comment by rachelmcr** [comment]
@gpmw There is some ongoing internal discussion (ref: p4TIVU-98g-p2) about how to proceed with this and related issues.

**Comment by gpmw** [comment]
Just checking in again as the ticket has rolled through again. Any word?
#1011629-zen

Thanks
