### ISSUE TITLE
Unable to add Payment Method to Subscription Plans for Renewal

### ISSUE THREAD

**Issue by almoyen** [Automattic/wp-calypso#23290]
Note: This only happens when the Subscription Plan is transferred from another WordPress.com account.
#### Steps to reproduce
1. Create a new site.
2. Upgrade it to any Subscription Plan.
3. Add a new Admin to the site.
4. Transfer the Subscription Plan to the new Admin’s account.
5. Login/SU to the new account that just received this Subscription Plan.
6. Go to Manage Purchases and Click on the Subscription Plan to manage it.
7. The following message will appear:
“WordPress.com Business will expire and be removed from your site in a year. Add a
credit card so you don't lose out on your paid features!

**Comment by alisterscott** [comment]
Hi @almoyen, what did you expect to happen? I don't believe the payment method will transfer as it's owned by the original admin and the plan has a new owner

**Comment by almoyen** [comment]
@alisterscott , this is an incomplete report published in mistake, I'm closing this.
