### ISSUE TITLE
Unable to add Payment Method to Subscription Plans for Renewal

### ISSUE THREAD

**Issue by almoyen** [Automattic/wp-calypso#23291]
_Note: This only happens when the Subscription Plan is transferred from another
WordPress.com account._

#### Steps to reproduce
1. Create a new site.
2. Upgrade it to any Subscription Plan.
3. Add a new Admin to the site.
4. Transfer the Subscription Plan to the new Admin’s account.
5. Login/SU to the new account that just received this Subscription Plan.
6. Go to Manage Purchases and Click on the Subscription Plan to manage it.
7. The following message will appear:
**“WordPress.com Business will expire and be removed from your site in a year. Add a
credit card so you don't lose out on your paid features!**

![](https://d.pr/vo2J8c+)

8. Follow the prompt, click **“Add a Credit Card”** button at the bottom.

![](https://d.pr/oBsZ9d+)

9. Put the Card Details and click “Save Card” button.
10. An Error will appear: Could not update stored details.

![](https://d.pr/90VZh+)

11. No Payment Method will be added to the Plan, and the Payment Method field will
show **“NONE”**.

![](https://d.pr/vo2J8c+)

### Now, if you go to your Billing History, you’ll see every time you attempt to add a payment method to the Subscription, it will fail and show an error, but the “Manage Your Credit Cards” Section will show a list of cards added to your account (Even though they’re all the same card, so the list should show just ONE card).

![](https://d.pr/1psq0i+)

#### What I expected
When the prompt for adding a payment method to the Subscription Plan Appears, you should be able to add a card to the plan.

#### What happened instead
The “Could not update stored details” Error message appears, and the attempt of adding a card to the plan fails. All failed cards are listed in the “Manage Your Cards” section as Separate Cards, although **IT IS JUST ONE CARD.**

**Source:** Reported by a user: 1965399-hc

**Comment by jessestu** [comment]
Another user reported this in #3823534-hc

We started by moving the plan and mapping over to another user to control billing. Then this same issue happened with the multiple credit cards being the same card.

They then tried paying through the iDEAL payment gateway and it went through.

**Comment by prettyboymp** [comment]
Closing this out.  This issue was fixed a bit ago.  Please reopen if issues continue.
