### ISSUE TITLE
Section-nav: let's only show 'counts' for emphasis

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#233]
Currently we show counts in several section-nav areas. `/posts` and `/people` immediately come to mind, I imagine `/pages` will follow posts eventually.

All of this counting has a few unwanted effects. 
1. We have started to hide the section-nav tabs while we fetch the counts because we don't know what to display yet (that's fine, just worth mentioning)
2. In /people it takes a long time to retrieve the count (especially when a site has 17m followers) and this holds up the page load
3. It's causing notification fatigue. The numbers appear all the time and eventually stop providing value. The larger the number the less meaning it has—it becomes completely abstract.

One suggestion is that we hide the counts unless it adds something useful to the screen. In a couple of cases like /plugins/updates it can act like an alert if it appears in the section-nav. By only showing the important counts we create added value.

I would propose we only show the counts in a few places:
- **Drafts** for posts and pages
- **Updates** for plugins
- **Invites** for people (only if there are pending ones)

Illustrations:

![image](https://cloud.githubusercontent.com/assets/7233112/11282236/419817f4-8ecc-11e5-9277-f54c3fa027cd.png)

![image](https://cloud.githubusercontent.com/assets/7233112/11282241/45c96b70-8ecc-11e5-8114-963d71b2abfb.png)

**Comment by alternatekev** [comment]
Agreed. I think we should only show counts for the ones you mentioned. :+1:
