### ISSUE TITLE
Offline: Improve offline error screen

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#2330]
After logging into desktop and losing internet connection, the app displays the following:

![offline](https://cloud.githubusercontent.com/assets/1270189/12272340/dd2e704c-b914-11e5-8db1-c2152a6b8784.png)
or
![offline2](https://cloud.githubusercontent.com/assets/1270189/12272348/e3c8dd02-b914-11e5-99f0-ba8a07eecb63.png)

If we have cached data we should display that instead. Also improve the current screens to communicate what is happening if the user is not logged in/has no local cached data.

**Comment by rralian** [comment]
This has been addressed in a branch in wp-desktop (https://github.com/Automattic/wp-desktop/commits/update/offline-disconnected). We don't want to commit these changes until we actually allow for offline functionality though. Calling this done for now and closing.
