### ISSUE TITLE
Jetpack: "We don't know what product you are trying to add to your cart" error when trying to buy plan from Jetpack.com

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#23328]
#### Steps to reproduce
1. create JN site and connect it to your account
2. from `/wp-admin/admin.php?page=jetpack#/dashboard` click on Upgrade nudge
3. click on "Upgrade today" on Jetpack.com page
4. on checkout page click back browser button
5. click on "Upgrade today" on Jetpack.com page
6. see the error

#### What I expected

Every time I click on "Upgrade today" button - I would be correctly redirected to checkout page

#### What happened instead

"We don't know what product you are trying to add to your cart - please contact support if this problem persists." error shown instead

#### Browser / OS version

Chrome / Mac OS 

#### Screenshot / Video

![screencast 2018-03-15 17-51-55](https://user-images.githubusercontent.com/5654161/37459284-29d54930-287a-11e8-8d8b-77f1c51e26ff.gif)

#### Context / Source

This issue looks like an edge case, but somehow it is reproducible without 4 & 5 steps in test runs in CI. That might be happening because a product was added into cart few times

#automated-testing

**Comment by brbrr** [comment]
I was able to reproduce the same behavior on `/wp-admin/admin.php?page=jetpack#/plans`

**Comment by rachelmcr** [comment]
I reproduced the issue and noticed that this also happens if you don't navigate back (step 4 in the repro steps) but just refresh the checkout page. I'm guessing this is what's causing the test failures in CI.

**Comment by brbrr** [comment]
It looks like it is fixed by https://github.com/Automattic/wp-calypso/pull/23327

**Comment by rachelmcr** [comment]
Confirmed I can't reproduce this anymore.
