### ISSUE TITLE
Offline: implement "offline" ux state for components

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#2333]
We already support a "no data" UX for our pages, which is the loading data with pulsing placeholders. As was suggested by @mtias, for an offline state for a component that is missing data, our MVP approach could be to just show the placeholders without the pulsing animation. This could initially be as simple as removing the pulse animation effect when offline.

**Comment by rralian** [comment]
We have an offline indicator on the page now and some design guidelines. Past that, it will be a very custom decision how to present offline for each component. So I would call this addressed.

**Comment by mtias** [comment]
We should still try to disable the placeholders as a raw solution across the app. Otherwise it will feel awkward until people get to update all the components.
