### ISSUE TITLE
Space quota warnings not showing up on Calypso

### ISSUE THREAD

**Issue by hugobaeta** [Automattic/wp-calypso#2334]
A user I helped in live chat was having trouble uploading images to posts in calypso, getting this error everytime they tried uploading an image:

> The file could not be uploaded because an error occurred while uploading

It turns out the problem was he exceeded his space quota. The error did show up in wp-admin/upload.php:

![screen shot 2016-01-12 at 10 17 51 am](https://cloud.githubusercontent.com/assets/1514660/12272815/14646ede-b917-11e5-8c1b-6d3115cc9571.png)

**Comment by aduth** [comment]
@gwwar : Would you consider this to be resolved as of #4172?

**Comment by gwwar** [comment]
Fixed in #4333 and #4172
