### ISSUE TITLE
Signup: Vertical scrollbar appearing next to plans on Plans step

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#23360]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. On step 1 (About) select "Continue."
3. On step 2 (Domain) search for and select a domain.
4. On step 3 (Plans) note the scrollbar(s) you see on screen.

#### What I expected

I expected to see a scrollbar only for parts of the page that need to be scrolled (e.g. a vertical scrollbar on the edge of the screen if needed, a horizontal scrollbar across the bottom of the plans if they didn't fit in my browser width).

#### What happened instead

I see an additional empty scrollbar appear next to the plans section:

![signupplansscrollbar](https://user-images.githubusercontent.com/8658164/37519744-38de9e0c-2912-11e8-881c-852462287824.png)

This scrollbar is nonfunctional — no matter my screen size, that plans section never has scrolling enabled (only the full page has vertical scroll).

Compare to previous screenshot of plans page (on 13 March) with no scrollbar there:

![signupplansnoscrollbar](https://user-images.githubusercontent.com/8658164/37519807-74c79202-2912-11e8-92bc-b1cbcf871cfa.png)

#### Browser / OS version

macOS 10.13 / Chrome 64

The same issue did not appear in macOS 10.11/Firefox 46 or macOS 10.11/Safari 9.0.

#### Context / Source
#automated-testing #visdiff-testing

**Comment by andfinally** [comment]
I'm not seeing that. This may be related to the fact that I'm not getting the "Free" card. I wonder if the layout has changed since this issue was created.

![screen-shot-2018-04-07-at-18 22 15](https://user-images.githubusercontent.com/1647564/38458057-e746d416-3a90-11e8-8c7c-6c74816a5f98.png)

**Comment by andfinally** [comment]
Thanks Rachel - I see it now. I did have my scrollbars set to "when scrolling".

This scrollbar is related to some work that was done to improve the scrolling of the list on iOS. I've created https://github.com/Automattic/wp-calypso/pull/23979 to fix this.

**Comment by sirreal** [comment]
This also impacts plans in the Jetpack connect flow (`/jetpack/connect/SITE_SLUG`):

![scroll](https://user-images.githubusercontent.com/841763/38491363-eeb35b6e-3beb-11e8-8039-cbe825a7eac3.png)

Appears to be from:

https://github.com/Automattic/wp-calypso/blob/2d2ba355ee1669a2410fa8ef540f4d435f81839a/client/my-sites/plan-features/style.scss#L443

Apparently introduced in #22820 (cc: @fditrapani)

**Comment by andfinally** [comment]
Hi @rachelmcr, this should now be resolved, am I OK to close this issue?

**Comment by rachelmcr** [comment]
Closing as resolved, thanks!
