### ISSUE TITLE
Build size: async load live chat

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#23376]
https://github.com/Automattic/wp-calypso/pull/22487 added the ability to initiate a livechat right from the sidebar.

Seems to have unintentionally dragged in a lot of code to build. Lets figure out how to defer loading happychat code until we know the user is interested.

**Comment by jsnajdr** [comment]
A big part of the `help` chunk has moved to `build`. I suspect the `me/help/contact` import in `blocks/inline-help`.

Async loading the whole `inline-help` block seems like a promising idea.
