### ISSUE TITLE
Activity Log: wording for new backup error events

### ISSUE THREAD

**Issue by singerb** [Automattic/wp-calypso#23371]
As part of implementing better error classification for backup errors with Rewind, we have some new wording for a few different error states. The current version of this can be found in D10987-code and some more context in p9rlnk-8D-p2

The error states and current wording are:

- Site is inaccessible: `We could not back up your site because it appears to be offline`
- Credentials don't work (but site is up): `Jetpack is unable to connect to your site. Please update your server credentials`
- Any internal error that requires developer attention rather than user action: `We ran into an issue backing up your site, but we're working on fixing the issue right away`

This issue was opened in order to make sure we have reasonable and consistent copy for these errors.

cc @MichaelArestad @samhotchkiss

**Comment by kristastevens** [comment]
Hi @singerb, thanks for the ping! 

> some more context in p9rlnk-8D-p2

Should this be a hyperlink to a p2 post? I'd find some additional context really helpful here.

**Comment by kristastevens** [comment]
> Site is inaccessible: We could not back up your site because it appears to be offline

Should add a period at the end of this statement and then also offer a chance to get in touch with support in cases where the user may be less technically savvy.  Suggest: 

> We could not back up your site because it appears to be offline. Need [help](https://jetpack.com/contact-support/)? 

> Credentials don't work (but site is up): Jetpack is unable to connect to your site. Please update your server credentials

Also would put a period at the end of the final sentence. I couldn't find a specific resource around server credentials at Jetpack support, so here I would also suggest adding a link to contact support. 

> Jetpack is unable to connect to your site. Please update your server credentials. Need [help](https://jetpack.com/contact-support/)? 
 
This last error message is a little puzzling. What should a user do in this instance? How much time should they wait before checking whether their site has been backed up? I'm wondering about how to set reasonable expectations with the user here and offer helpful guidance should we somehow not meet the expectations. I'm thinking along the lines of adding something like, "Check back here in an hour. If you're still having trouble, please contact us in [Support](https://jetpack.com/contact-support/)."

**Comment by singerb** [comment]
All of these should be showing chat/help buttons on the events already since they're backup errors, so that aspect is already handled.

For the last one, I'd be wary of having any specific time mentioned; I'm already not a fan of the "right away" language. What we're trying to communicate here is that there's nothing they can do to fix this error (unlike the other two cases), and that we're already aware of it (via internal reporting) so they don't need to communicate it to us (although they can of course contact support). Actually fixing whatever the error is may take time, developers may be asleep or AFK, etc etc.

**Comment by kristastevens** [comment]
> All of these should be showing chat/help buttons on the events already since they're backup errors, so that aspect is already handled.

Ok, that said, we don't need the extra link to support. I think the language is fine as you shared it, except all sentences should have periods at the end of them. 

> For the last one, I'd be wary of having any specific time mentioned; I'm already not a fan of the "right away" language.

I was asking about time expectations to better understand the context the user is in so that I could offer appropriate language. How about: 

> Thanks for making us aware of this issue -- we're working on a fix! There's nothing more you need to do right now.

**Comment by designsimply** [comment]
> Should this be a hyperlink to a p2 post?

That is shorthand for an internal reference. If you search the Field Guide (internal reference) for "shorthand," you'll see a description for how to make those links active at the bottom of the page. This is something we'd like to automate in the future!

**Comment by singerb** [comment]
Updated the wording based on this feedback; thanks! Closing the issue.
