### ISSUE TITLE
Internet Explorer prevents users from logging into WordPress.com

### ISSUE THREAD

**Issue by openfist** [Automattic/wp-calypso#23386]
#### Steps to reproduce
1. Starting at URL: https://WordPress.com
2. click login
3. See that username/email field is greyed out

#### What I expected
username/email field is expected to be clicked and typed with username or email to log in

#### What happened instead
field is greyed out and unusable.

#### Browser / OS version
Windows 10
Internet Explorer 11

#### Screenshot / Video
http://prntscr.com/is9u7d 

#### Context / Source
customer brianmarrano reported the error while in LiveChat.

**Comment by openfist** [comment]
Forgot to mention this issue is IE only. Login works with Firefox, Chrome and Safari

**Comment by senff** [comment]
Temporary workaround (if users report this) is to go to https://wordpress.com/wp-login.php?no_calypso

**Comment by blowery** [comment]
Appears this was due to the babel-7 upgrade in https://github.com/Automattic/wp-calypso/pull/23026

Seeing `SCRIPT5009: 'Reflect' is undefined` in the IE console, in part of the babel polyfills.

**Comment by dougaitken** [comment]
Forum posts about the issue: 
* [consistent login failure](https://en.forums.wordpress.com/topic/consistent-login-failure)
* [unable to log in](https://en.forums.wordpress.com/topic/unable-to-log-in-25)
* [is wordpress down](https://en.forums.wordpress.com/topic/is-wordpress-down-9) 
* [login problem](https://en.forums.wordpress.com/topic/login-problem-46) ( IE 11, Win 7 mentioned twice)

Safari on iPad mentioned but no versions so far
