### ISSUE TITLE
Activity log: service unavailable error when adding credentials disappears too fast

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#23402]
_"Our service isn't working at the moment"_ error that might show up when adding credentials for Activity Log Rewind fades out too fast (in about 4s). I don't have time to read it nor react to call-to-action link in it.

![screen shot 2018-03-19 at 13 34 45](https://user-images.githubusercontent.com/87168/37593656-67cae80e-2b7b-11e8-87d7-54f27ebe953a.png)
![screen shot 2018-03-19 at 13 34 49](https://user-images.githubusercontent.com/87168/37593657-67eadef2-2b7b-11e8-97c7-41d9455746ab.png)

#### Steps to reproduce
Not quite sure how exactly to reproduce that exact error. Other errors such as this one:
    ![image](https://user-images.githubusercontent.com/87168/37593695-8c2b8474-2b7b-11e8-897b-c76d36740aac.png)
...don't seem to disappear so fast.

~~I have [local Docker-Jetpack](https://github.com/Automattic/jetpack/tree/7baa0c39ea5732d083de6a5a994f7d50357a6735/docker) setup running and I'm proxying to SFTP container using [Ngrok](https://ngrok.com/). At least currently that setup causes that connection problem but it might get fixed in future.~~ **Update:** Docker setup isn't causing this error anymore.

1. Starting at URL: http://calypso.localhost:3000/start/rewind-setup/rewind-form-creds
2. Add correct creds
3. Observe _"Our service isn't working at the moment"_ error (you could tricker it by modifying Calypso code?)
4. Observe it disappear very fast (~3-4s)

#### What I expected
Error message persisting visible just like other errors do.

#### What happened instead
⚠️ 💨 

#### Browser / OS version
Chrome / MacOS

**Comment by keoshi** [comment]
Can you take a look and triage this one @rcoll @briancolinger @singerb ? Thank you :)

**Comment by singerb** [comment]
Can't do anything about the Calypso stuff, but I've added some more resources on the back-end that should improve response times. I also ended up having to update the URL for this site in VP MC, since we use that URL when we save credentials and it was incorrect; unsure why the error message from that wasn't better.
