### ISSUE TITLE
Jetpack Plans: Monthly plans show 'billed yearly'

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#23413]
When selecting a plan for a Jetpack connected site, the Monthly billing option shows the price, then:

> per month, billed yearly

This is not accurate, as Jetpack plans can be billed monthly.

#### Screenshot

![image](https://user-images.githubusercontent.com/1990037/37612094-1d883c4e-2b9c-11e8-9757-b6601fcf8353.png)

**Comment by seear** [comment]
@adamziel any chance this could have been caused by #23314?

**Comment by seear** [comment]
I've rolled back to before #23314, and the issue is still there, so it seems to predate that PR.

**Comment by seear** [comment]
Issue was introduced in an A/B test (both variants) here https://github.com/Automattic/wp-calypso/pull/22244/files#diff-682fa9ded512d0b6e17bad5c1b613f85R550.

@taggon are you ok to fix the copy for the jetpack plans so that the read "billed monthly" again?

**Comment by taggon** [comment]
Oh dear, that's my fault 😱 I'm going to make a fix soon.
@seear Thanks for noticing me the problem.
