### ISSUE TITLE
Checkout: uniform format for prices

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2341]
Raised by @ranh

We should strive to use a uniform format for pricing.

![screen shot 2014-12-22 at 21 01 49 pm](https://cloud.githubusercontent.com/assets/426518/5529501/d071d438-8a1d-11e4-90c2-830ac2a1de52.png)

![screen shot 2014-12-22 at 21 01 38 pm](https://cloud.githubusercontent.com/assets/426518/5529502/d2475e72-8a1d-11e4-9c18-32e6676217eb.png)

When possible, we should use the dollar symbol, the US Dollar acronym, and the applicable subscription period:

$88 USD per year
$88 USD /year

To save space we can use the common format for prices in the US:

$88

In this case it would be good to specify USD and the subscription period somewhere else on the page.

Comment from @justinkropp

> I'm in agreement with the following convention:
> 
> > $88 USD /year
> 
> And where possible, use:
> 
> > $88 /year

Comment from @stephanethomas

> Regarding the following convention:
> 
> > $88 USD /year
> 
> Aren't we duplicating information for the currency here? I know we have to make the distinction between US dollars, Canadian dollars and so on but still I don't see the point of having two symbols for the same thing. For example in French it means we would have:
> 
> > 88€ EUR /an
> 
> It doesn't seem we're aiming for simplicity here - however please forget my comment if this is an established convention :).
> 
> Still I would love @yoavf or someone else from +i18n to chime in.

Comment from @yoavf

> I don't really know. Personally I find the duplication a bit odd, but can understand the confusion for some users if we'd just assume $ is USD when they live in Canada or Australia.
> 
> I just checked ebay, and they use $XX just for USD (without adding USD). For other currencies, they tend to do things like AU $XX, C $XX, XX EUR (no sign), ILS 55 etc.... 

Comment from @aduth

> I had posted about localizing strings in the REST API several weeks back (p3hLNG-mG-p2), and it was a topic of discussion for our recent I/O team meetup (p5j4vm-uD-p2) . The decision was that we'd support localization in the REST API through the use of the `accept-language` request header. This doesn't exist yet, and is tracked separately at 160-gh-io, 161-gh-io, and 162-gh-io.
> 
> For now, your best option may be to rebuild the price label from the REST API `amount`, `currency`, and `bill_period_label` values, where you can expect one of a few values for `bill_period_label` in store-subscription.php#2110. To make the Calypso `translate` build task aware of the expected strings, you can add the strings [manually to the build task](https://github.com/Automattic/wp-calypso/blob/53bde8c3f9c4668e62dbd2c670aaacc2bd820427/server/i18n/index.js#L118-L164) or add a function similar the one shown below (which is redundant and possibly inefficient):
> 
> ``` javascript
> module.exports = React.createClass( {
>     // ...
> 
>     getTranslatedBillPeriodLabel: function( originalLabel ) {
>         var labels = {
>             'for life': this.translate( 'for life' ),
>             'per day': this.translate( 'per day' ),
>             'per week': this.translate( 'per week' ),
>             'per month': this.translate( 'per month' ),
>             'per year': this.translate( 'per year' )
>         };
> 
>         return labels[ originalLabel ];
>     }
> 
>     // ...
> } );
> ```
> 
> In most cases, I think we should seek to avoid including human-readable strings in REST API responses wherever possible and instead provide the data necessary to build the strings on the client. For example, instead of providing `expiry_message`, `expiry_date` is sufficient for the client to build its own string. This goes back to @mdawaffe's original remarks (p10gg3-1dk-p2 #comment-7350) on how the API should provide data.

Comment from @stephanethomas

> Another option would be to display the currency code in a tooltip on mouseover and just display the price with the currency symbol.

Comment from @stephanethomas

> This is still an issue but I don't think there is any blocker remaining - the API can return localized content and it works well. We just need to take the time to come up with a convention regarding how to display prices, something that is important for the user experience. Next steps would probably be to inventory every page that display prices, then list the corresponding endpoints and update them to ensure we are returning prices in a consistent manner.

Comment from @ranh

> Re. the duplication in $88 USD, that's an interesting point, could probably use some feedback from people in USA, Australia, Canada, any place that this concerns. When you see something like $88 online, do you assume by default that it's a price in your local currency, or in USD?
> 
> Personally I don't think there's anything wrong with being redundant here. The $ sign is a very strong indicator that the number is a price, much stronger than a three letter currency code I would think. Also, losing the $ sign doesn't add up to any kind of significant win as far as I can tell, it doesn't save much space, doesn't aid readability.
> 
> However, in some cases it might make more sense to just add something like "All price in XXX" somewhere on the page. For example in the pricing page, it might be less of a strain on the page than putting that XXX after every price shown.

Comment from @fabianapsimoes

> > Next steps would probably be to inventory every page that display prices...
> 
> Here are some pages that display prices that I could find:
> - [ ] /plans
> - [ ] /plans/compare
> - [ ] /domains/add
> - [ ] /domains/add/mapping
> - [ ] /domains/manage/email
> - [ ] /domains/manage/:site/email
> - [ ] /checkout (including the Domain Registration Details form)
> - [ ] /design
> - [ ] /me/billing

**Comment by janm6k** [comment]
Going through old issues, closing ones that does not look like important one.

Please feel free to reopen if applicable.
