### ISSUE TITLE
Reader: when a site is deleted, clean up subscribers where possible

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#23426]
@blowery noted in https://github.com/Automattic/wp-calypso/issues/5840#issuecomment-362672137:

> 
> If the site in question is a *.wordpress.com site, we can and should just unsub the followers.
> 
> If the site has a domain mapping, we should not unsub the followers, as the site may just be moving elsewhere.
> 
> If a user is currently subscribed to a site that has been deleted and the sub_matrix record is a *.wordpress.com domain, we should unsub them.

We'll also need to investigate how this fits in with site renames and moves. Subscribers are migrated across by an async job, so we don't want to delete them too early.

**Comment by jamiepalatnik** [comment]
In 2487402-hc a user reported that deleted sites appeared in the Blogs I Follow widget and the user didn't know how to delete them. I was able to unfollow the blog for the user by searching for the site address and clicking the unfollow link under the search box, as mentioned in [this comment](https://github.com/Automattic/wp-calypso/issues/5840#issuecomment-367310700).

**Comment by sophiegyo** [comment]
In 1149602-zen a user reports that while their site has been migrated away from WordPress.com (and is no longer active, it just has a static holding page), others are still able to search for the domain in the Reader and follow it, even though no posts appear.  I've been able to replicate this here:
http://cld.wthms.co/zjl9sh

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
