### ISSUE TITLE
Checkout: "free cart" payment missing WP logo and layout is broken

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#23421]
#### Steps to reproduce
1. Starting by upgrading to Premium from a free site
2. Pay for the plan (I used free credits for the test)
3. Then, go to claim your free domain
4. Proceed to checkout

#### What I expected
To see a similar layout to when checking out with other plans.

![screen shot 2018-03-19 at 15 11 46](https://user-images.githubusercontent.com/66797/37625109-db7cdee0-2b87-11e8-92ab-f2a27313f21c.png)

#### What happened instead
I saw a broken layout, and no WordPress.com logo.

![screen shot 2018-03-19 at 15 08 46](https://user-images.githubusercontent.com/66797/37625077-bc01490c-2b87-11e8-99de-73539ba626b6.png)

#### Browser / OS version
Testing with Safari 11.0.3 on OS X 10.13.3

Previously related #19741

Code ref: https://github.com/Automattic/wp-calypso/commits/master/client/my-sites/checkout/checkout/free-cart-payment-box.jsx

Reported in #real-life usage by @m

**Comment by drw158** [comment]
Could be related to #23188
