### ISSUE TITLE
NPS Survey: move eligibility check to the data-layer

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#23455]
In #12966 we added a new method to the [undocumented file](https://github.com/Automattic/wp-calypso/blob/bf0adc7d4bdc7ab04fb5861e917ae6d2e0772d73/client/lib/wpcom-undocumented/lib/undocumented.js#L2446) in wpcom.js let's port move this to the [data-layer](https://github.com/Automattic/wp-calypso/tree/master/client/state/data-layer) for a few reasons:
- We won't need it in the undocumented file!
- We can take advantage of data-layer features such as automatic retries for GETs and no longer needing to keep track of potential `isLoading` tracking state in redux. 
- By updating the [action](https://github.com/Automattic/wp-calypso/blob/bf0adc7d4bdc7ab04fb5861e917ae6d2e0772d73/client/state/nps-survey/actions.js#L35) from a thunk to a plain action, we make this easier to read and use from an app context, allows other middleware to inspect it, and also enables easier testing. (We can [dispatch from the console](https://github.com/Automattic/wp-calypso/tree/bf0adc7d4bdc7ab04fb5861e917ae6d2e0772d73/client/state/console-dispatch#console-dispatcher) !)

In this refactor no known changes should happen (@jonathansadowski let us know if this is still up to date! ):

### Testing Instructions

The NPS eligibility endpoint should still determine whether or not to show the survey. To prevent unnecessary requests, the query only occurs when they user's session is "lucky" (1 out of 5000 times).

* Setup your console to see debug messages from the feature: `localStorage.setItem( 'debug', 'calypso:nps-survey' )`
* Reload Calypso and watch your console
```
calypso:nps-survey Checking NPS eligibility... +0ms
calypso:nps-survey ...Eligibility returned from endpoint. +693ms Object {display_survey: false, seconds_until_eligible: 10540794}
```
* Otherwise you should see the survey prompt, and in your console see a message like this:
```
calypso:nps-survey Checking NPS eligibility... +0ms
calypso:nps-survey ...Eligibility returned from endpoint. +722ms Object {display_survey: true, seconds_until_eligible: 0}
```

**Comment by gwwar** [comment]
Note that it looks like we should add a new action type like `NPS_SURVEY_ELIGIBILITY_CHECK`

Once this is fully ported we'll be able to test with a browser console dispatch, to trigger the dice roll/network request:
```jsx
dispatch( { type: 'NPS_SURVEY_ELIGIBILITY_CHECK' } );
```

**Comment by sararosso** [comment]
Adding @taggon to this - we've done some extensive work on NPS v2 lately and the above is most likely outdated. 

You can see more details of the project on p9jf6J-h6-p2

**Comment by gwwar** [comment]
@taggon should I update the issue then to remove unneeded code?

**Comment by taggon** [comment]
@gwwar I don't think you need to update the issue except for the testing instructions. We don't use `NPS_SURVEY_RAND_MAX` to ensure all users participate the survey two time a year. In other words, there is no _lucky_ user any more. See [this PR](https://github.com/Automattic/wp-calypso/pull/23894).

**Comment by gwwar** [comment]
@taggon Got it so we still need the API call?
