### ISSUE TITLE
Jetpack Onboarding: Change "next" link text to "skip for now" on all steps

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#23458]
Confusion between “continue” and “next” button. Should be “skip for now”. For example, we don’t want the user to fill out their site title info, click “next” and have it not be applied. The same applies to all steps.

ref: p1HpG7-4WU#comment-25005

**Comment by tyxla** [comment]
@joanrho it seems it's being suggested that we remove links in cases where we have the Continue button? See p1HpG7-4WU-p2 #comment-25088 (also you seem to have agreed with that approach in a reply). 

I'm confused as to whether to remove the links or update the text. It's worth mentioning that historically we've been through this doubt already, see https://github.com/Automattic/wp-calypso/pull/22852#issuecomment-369257353 and https://github.com/Automattic/wp-calypso/issues/22641.

**Comment by tyxla** [comment]
Or is it about doing both at the same time:

* Updating the text from "Next" to "Skip for now" in all cases
* Hiding the Next/Skip button in cases where we have the "Continue" button

Let me know if that's the case and I'll prepare a PR.

**Comment by tyxla** [comment]
I've decided to take the initiative and wrangle a PR - #23488.

Would appreciate some feedback @joanrho @rickybanister @jeffgolenski @keoshi, thanks!

**Comment by joanrho** [comment]
@tyxla exactly—it's about doing both at the same time in certain cases like your comment above:

>Updating the text from "Next" to "Skip for now" in all cases
>Hiding the Next/Skip button in cases where we have the "Continue" button

**Comment by tyxla** [comment]
@joanrho sure, that's already done in #23488 - it's already approved, but if you can take a look too that would be awesome!
