### ISSUE TITLE
Error messages are not passed back via Jetpack proxy

### ISSUE THREAD

**Issue by dechov** [Automattic/wp-calypso#23467]
The Jetpack proxy isn't passing through the error response body, causing meaningful error messages (sent back as `WP_Error`s from WooCommerce Services endpoints) to be replaced with:

`{"error":"no_response_body","message":"Server could not read response."}`

<img width="342" alt="screen shot 2018-03-20 at 5 03 01 pm" src="https://user-images.githubusercontent.com/1867547/37682753-c8decabc-2c60-11e8-9071-1c77371c94f7.png">

Is this an issue for WooCommerce as well? (WCS requests are made using the `woocommerce` extension's request module, from https://github.com/Automattic/wp-calypso/blob/master/client/extensions/woocommerce/woocommerce-services/api/index.js)

What can be done about it, other than returning a `200` status and indicating the error in the body alone?

**Comment by justinshreve** [comment]
Hmm - I don't think we have that problem in other places. We are using error messages for things like the duplicate SKU message that shows up when creating a product: `{"error":"product_invalid_sku"}`.

From a look at the Jetpack Proxy code (`class.wpcom-json-api-jetpack-blog-endpoint.php` on WPCOM), this is where it's happening:

```
$body = json_decode( wp_remote_retrieve_body( $response ) );
if ( is_null( $body ) ) {
    return new WP_Error( 'no_response_body', __( 'Server could not read response.' ), 500 );
}
```

So it's getting an empty body from Jetpack or something on the remote site itself.

**Comment by dechov** [comment]
Thanks for pointing me to that code @justinshreve. Should have caught this when documenting the issue, but the wp-admin client is also receiving a 500 status (with an HTML body), so yes, it's an issue with the host not allowing `WP_Error` responses for some reason.

**Comment by dechov** [comment]
Closing as not directly pertinent to Calypso.
