### ISSUE TITLE
Checkout: fix incorrect state field name in validation error in domain contact information page

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2346]
Raised by @stephanethomas 

> We should modify the validation error message that is displayed when no state is selected on the domain contact information page for certain countries to match the actual name of the field.
> 
> In other words, we should display `The “State” field is required.` instead.

Steps to reproduce:
1. Go to https://wordpress.com/ → My Site → Domains [#](https://cloud.githubusercontent.com/assets/1119271/9667081/c9986530-5247-11e5-9d8b-f8f3cc92ffd7.png)
2. Click the "Add Domain" button
3. Click the "Add" button next to a suggested domain
4. Click the "No thanks" link below the Google Apps ad
5. Select "Australia" for the country
6. Do not select a state and click the "Publish My Information" button

<strong>Result:</strong> the error mentions a “State/Province” field but the form field on the pages is labeled "State."

![screen shot 2016-01-12 at 15 29 31](https://cloud.githubusercontent.com/assets/1119271/12276064/90d47d04-b941-11e5-9f3a-cddcdc6d6b15.png)
<sup>Seen at https://wordpress.com/checkout/watchingstormsrollby.me using Firefox 43.0.2 on Mac OS X 10.10.5</sup>

Error:

<blockquote>Please correct the issues listed below and try again.
<br>
<br>    • The “State/Province” field is required.
<br>    • The “Postal Code” field must be in the format ‘####’ for Australia (where # represents numbers).</blockquote>

**Comment by klimeryk** [comment]
Fixed on the backend in r159196-wpcom 🎉
