### ISSUE TITLE
Jetpack Onboarding: Add an illustration on summary screen

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#23461]
Add an illustration to the Summary screen.

Fireworks asset to add to top of Summary screen: https://cloudup.com/cee1yeTTusG

Mockup:

<img width="585" alt="screen shot 2018-03-20 at 1 16 01 pm" src="https://user-images.githubusercontent.com/204742/37677516-e34c2c70-2c40-11e8-8e0f-e70a17ad7d7e.png">

ref: p1HpG7-4WU#comment-25005

**Comment by tyxla** [comment]
Looks great @joanrho, illustration added in #23485.
