### ISSUE TITLE
Checkout: only fetch products when needed and limit to data that we use in Calypso

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2348]
Raised by @gcorne 

> Right now, we're fetching all our products on every full page load regardless of whether or not the data is needed.
> 
> cc @scruffian @rads

Comment from @lancewillett 

This is still happening. Testing with:
1. Load up Calypso (wpcalypso or local dev)
2. Clear localStorage in your console with `localStorage.clear()`
3. Load the page again.
4. Inspect the localStorage value for products list: `localStorage.getItem( 'ProductsList' )`

`localStorage.getItem( 'ProductsList' )` response in the console in Chrome 47:

![screen shot 2016-01-12 at tue jan 12 3 41 22 pm](https://cloud.githubusercontent.com/assets/1119271/12276289/05063068-b943-11e5-8a25-a5355b6cd189.png)

**Comment by lancewillett** [comment]
Note from a bug scrub — still happening, testing with same steps above.
