### ISSUE TITLE
Checklist: page views reported with non-normalized paths

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#23506]
According to internal logs, some `calypso_page_view` paths coming from Checklist are reported without replacing site slug with `:site` variable. For example:

`/checklist/:site/example.wordpress.com`

In this case, since `:site` variable is already present in the path, I think that we should just remove the site slug part.

For more details on how to obtain the logs, please check out the parent issue https://github.com/Automattic/wp-calypso/issues/16902 and p7jreA-1xN-p2.

**Comment by markryall** [comment]
i'm happy to take this on - the path problem is secondary to the fact that the routing doesn't make sense when switching sites.

**Comment by markryall** [comment]
Created PR #23818 today which should solve this issue.

**Comment by markryall** [comment]
PR #23818 is now deployed so I think this issue can be considered resolved (although there are other checklist issues that will need to be addressed independently)

**Comment by Copons** [comment]
As it seems, this is _almost_ solved. We only just need to stop reporting the query params in the page view events.
E.g. `/checklist/:site?d=gsuite`
