### ISSUE TITLE
Domains: page views reported with non-normalized paths

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#23514]
According to internal logs, some `calypso_page_view` paths coming from Domains are reported without replacing passed parameters with corresponding variables. In the following examples I'll be using `[variable]` to denote the places where these parameters appear (e.g. `[site]` means that `example.wordpress.com` was recorded in our logs, instead of `:site`):

- [ ] /domains/add/[site]/google-apps
- [ ] /domains/manage/[site]/transfer/precheck
- [ ] /domains/manage/edit/[site]
- [ ] /domains/manage/edit/[random_ip_address]
- [ ] /domains/manage/[site]/email-forwarding
- [ ] /domains/manage/transfer/precheck/[site]

 I think the easiest way to see the current non-normalized paths is to run this query: 1d7bc-pb.

For more background, please check out the parent issue https://github.com/Automattic/wp-calypso/issues/16902 and p7jreA-1xN-p2.

**Comment by Copons** [comment]
This is a list of all the `/domains` paths:

/domains/add/:site
/domains/add/site-redirect/:site
/domains/add/mapping/:site
/domains/add/transfer/:site
/domains/add/:domain/google-apps/:site
/domains/manage/email/:site
/domains/manage/:domain/email/:site
/domains/manage/:domain/add-google-apps/:site
/domains/manage/add-google-apps/:site
/domains/manage/:domain/email-forwarding/:site
/domains/manage/:domain/redirect-settings/:site
/domains/manage/:domain/contacts-privacy/:site
/domains/manage/:domain/edit-contact-info/:site
/domains/manage/:domain/dns/:site
/domains/manage/:domain/name-servers/:site
/domains/manage/:domain/transfer/:site
/domains/manage/:domain/transfer/out/:site
/domains/manage/:domain/transfer/other-user/:site
/domains/manage/:domain/transfer/other-site/:site
/domains/manage/:site
/domains/manage/:domain/edit/:site
/domains/manage/:domain/privacy-protection/:site
/domains/manage/:domain/primary-domain/:site
/domains/manage/:domain/transfer/in/:site
/domains/manage/:domain/transfer/precheck/:site

It's crazy to tackle it all at once, I'll see to split the work in multiple steps.

**Comment by vindl** [comment]
cc @Automattic/cobalt in case they can come up with some generic solution. I think the easiest way to see the current non-normalized paths is to run this query: 1d7bc-pb.

@copons as a result of https://github.com/Automattic/wp-calypso/pull/23688 I see some of these patterns now correctly assigned to `/no-sites` path (via this query 1d7be-pb), although I'm not sure if they account for every occurrence of given pattern:

- `/domains/manage/[domain]/edit/[domain]`
-  `domains/manage/[domain]/transfer/in/[domain]`
-  `/domains/manage/[domain]`
- `/domains/manage/[domain]/email-forwarding/[domain]`
- `/domains/manage/email/[domain]`
- `/domains/manage/[domain]/dns/[domain]`
- `/domains/add/[domain]`

**Comment by aidvu** [comment]
@klimeryk might be good to plan this for the coming weeks?

**Comment by klimeryk** [comment]
Saw some chatter about this on Slack - @Copons will you be working on this?

**Comment by Copons** [comment]
> Saw some chatter about this on Slack - @Copons will you be working on this?

@klimeryk Yup, I've created a PR yesterday, but I need to test it more extensively before opening it up to the public. 🙂
