### ISSUE TITLE
Comments: page views reported with non-normalized paths

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#23510]
According to internal logs, some `calypso_page_view` paths coming from Comments are reported without replacing passed parameters with corresponding variables. In the following examples I'll be using `[variable]` to denote the places where these parameters appear (e.g. `[comment_id]` means that something like `123` was recorded in our logs, instead of `:comment_id`):

- [x] /comment/[comment_id] (or some other id? - query: 1d6d8-pb)
- [x] /comments/[status] (query: 1d6d6-pb)

For more details on how to obtain the logs, please check out the parent issue #16902 and p7jreA-1xN-p2.

You can also see a recent related fix for this here: https://github.com/Automattic/wp-calypso/pull/18414

**Comment by Copons** [comment]
Wondering if this is still relevant.

`/comments` should only reports normalized, manually written, paths created in the controller and passed down to `Main` that assign them to `PageViewTracker`:
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/controller.js#L65
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/controller.js#L94

`/comment` too only reports a normalized path:
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comment/main.jsx#L55

**Comment by vindl** [comment]
@Copons yes, the code seems fine, although if you run this query 1d6d6-pb for yesterday's stats you'll notice that we still have a small number of events recorded as `/comments/all` instead of `/comments/:status`.

Also, running this query 1d6d8-pb will show a small number of paths that are recorded as `/comment/123` instead of `/comment/:comment_id` (most likely, but could be `:site_id also?).

I'm still not sure what's causing this, but I've noticed the same weird issue in other sections too.

**Comment by vindl** [comment]
@Copons just a note that https://github.com/Automattic/wp-calypso/pull/23688 will probably resolve this one too.

**Comment by Copons** [comment]
@vindl Yes it should! 🕺

**Comment by vindl** [comment]
Should be resolved with https://github.com/Automattic/wp-calypso/pull/23688, I'll keep monitoring the stats in the following days.
