### ISSUE TITLE
Enhancement request for the SMS Verification code screen in Calypso

### ISSUE THREAD

**Issue by cafenoirdesign** [Automattic/wp-calypso#23549]
#### Steps to reproduce

There are a couple spots in the Calypso user flow, where users are asked to revalidate their identity. One spot is when managing subscriptions here:
https://wordpress.com/me/notifications

#### What I expected

Why is the "Send SMS" button, below the empty "Verification Code" field? 

It implies that you need the field to be filled in before clicking the button, when actually, you need to click the button, (receive the code via SMS) and then fill in the field. It would be better to have the SMS button alone in the panel first, or, if those two components need to be in the same panel for some reason, then to have the "Send SMS Code" button above the empty "Verification Code" field. It's especially confusing because the empty field has focus and not the button. Could we make this a bit more intuitive?

#### Browser / OS version

OSX/Chrome

#### Screenshot / Video

<img width="485" alt="screen shot 2018-03-22 at 22 mar 07 13 08" src="https://user-images.githubusercontent.com/225598/37781044-5ca93b0e-2dc6-11e8-82d5-482f6c381259.png">

**Comment by drw158** [comment]
This is from #22195

**Comment by drw158** [comment]
This should be kept open because this part of the UI is not going to be replaced anytime soon, and no one is currently working on 2-step. It's still a bad experience and could use an enhancement.

**Comment by torres126** [comment]
> It would be better to have the SMS button alone in the panel first

I don't think this would work in cases where the user doesn't want to receive an SMS message to get the code, but rather has the code already available to enter due to an authenticator app.

**Comment by torres126** [comment]
PR in #32089 for a stab at this :)

**Comment by Aurorum** [comment]
I do have a PR open for this which has been open for a while. Is there anyone who could review it? 

cc @samouri, @tyxla, @rodrigoi

**Comment by davewhitley** [comment]
I'm not sure what it looks like now (with only SMS enabled) but here's what it looks like with verification done via an auth app.

![Screen Shot 2020-10-05 at 9 53 09 AM](https://user-images.githubusercontent.com/618551/95095515-c1e72200-06f0-11eb-89dd-9b2ae6c3bf98.png)

I bet this new design also applies to SMS verification, so in that case I think this issue could be closed.
