### ISSUE TITLE
Link To option no longer available for post/page images

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#23543]
#### Steps to reproduce
1. Create or edit a post/page
2. Insert an image
3. Click the pencil icon, then the Edit Image button

#### What I expected

A Link To option to link the image to the Attachment Page, Media File, or a Custom URL. 

#### What happened instead

An interface to rotate, crop, or flip the image without any of the link to options available any more.

This capability still exists in wp-admin, but it seems to have been removed from Calypso. Also, previous images that were set up with the link to the Attachment Page stopped working.

#### Screenshot / Video

This is what's still available in wp-admin:

![screen shot on 2018-03-22 at 08_03_19](https://user-images.githubusercontent.com/7596032/37769502-95324b4c-2da7-11e8-9b25-f1d035fe14a5.png)

#### Context / Source

This came up during 2131831-hc. Several image links from before now gave 404 errors and the new ones didn't have the image links.

**Comment by katinthehatsite** [comment]
User reported in #2314265-hc

**Comment by katinthehatsite** [comment]
Also reported in #1090622-zen
