### ISSUE TITLE
Jetpack Onboarding: Add checklist styling to Summary view

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#23557]
As discussed in p1HpG7-4WU#comment-25192, here is a mockup of what the Summary step of JPO could look like in a future iteration with the Checklist styling applied.

<img width="615" alt="summary step with checklist buttons" src="https://user-images.githubusercontent.com/204742/37789592-f17ac2ea-2dc9-11e8-82ff-370e00eab89b.png">

**Comment by joanrho** [comment]
No dumb Qs, these are all valid!

>The steps to the left can also be incomplete, right? So we could have a mix of complete and incomplete steps there?

Yes. Incomplete and complete. We hope to group them together by complete/incomplete—would that be possible? 

>The steps to the right - these will never be completed, right? Even if the store is already setup, or pages/posts have been added, or another theme has been installed. Do you think that's expected?

Yes I think that will be the case for the right side items, but, for example, when a user clicks on the “type of site” checklist item (in the first column) to revisit since they skipped it in step 2, it will take them back into JPO (this was an issue brought up by Jeff during testing i2). So in cases like that, the incomplete circle would turn into a completed one.

A few things to consider with this checklist for future iterations:
1. Users may see incomplete items in the left column and expect to see them in the right column so they can act on them and complete them. Technically these skipped steps are "steps you've completed" bc they chose to skip that step. I wonder if moving incomplete steps to the right column would make sense?
2. When users try to complete an item in the right column, they cannot return to this checklist to complete the remaining items after going to their site to change the settings of the item they selected.

**Comment by tyxla** [comment]
The Jetpack Onboarding feature was completely removed in #38000, so this one can be closed as well.
