### ISSUE TITLE
Store: New Order screen doesn't use store currency

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#23559]
The new order screen doesn't seem to pull in the store currency when creating a new order.

Steps to reproduce:

1. Set your currency (`http://calypso.localhost:3000/store/settings/site`) to something like Pounds
2. Navigate to the new order screen (`http://calypso.localhost:3000/store/order/:site`)
3. Notice the shipping dialog displays `$`
4. Click add a product. The prices here will be displayed correctly.
5. Select a product and add it.
6. The product row will display the price in USD.
7. Save your order. The API response that comes back will contain `"currency":"USD"`.

Example: https://cloudup.com/cpQhPmtzHxl

**Comment by allendav** [comment]
Found it. We set all new orders to `USD` by default

https://github.com/Automattic/wp-calypso/blob/46b162169d2ac69b7e743d4a9259f59821eed120/client/extensions/woocommerce/state/ui/orders/selectors.js#L61

Working on a fix now.
