### ISSUE TITLE
Themes: Dropdown filters not appearing when filter is clicked

### ISSUE THREAD

**Issue by samjhamdy** [Automattic/wp-calypso#23561]
#### Steps to reproduce
1. Starting at any WordPress.com site
2. Go to the Themes panel
3. Click on a filter (e.g. 'Subject')

#### What I expected

This should trigger a dropdown of the 'Subject' filters to appear.

#### What happened instead

Nothing. Although the filter name does appear in the Search field.

#### Browser / OS version

Chrome Version 65.0.3325.162 (Official Build) (64-bit) / OS X El Capitan Version 10.11.6

#### Screenshot / Video

https://cloudup.com/c-YjKmB0HnE

#user-report (discovered while helping a user in a Business Concierge 1:1 session)

**Comment by mapk** [comment]
Looks like this has been corrected with #23562 which reverted the code that introduced the problem. I'll close this.
