### ISSUE TITLE
Onboarding Checklist: Change tooltip is still being displayed even after uploading a new Site Icon

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#23575]
#### Steps to reproduce
1. Create a brand new site.
2. Select the step where you are asked to customize your site icon.
3. Be taken to your Site Profile and click on the placeholder site icon to upload a new one (there's a tooltip telling you to Change the image).
4. Upload a new site icon.
5. Exit "Edit" mode. Notice how the Change tooltip is still there.

#### What I expected
For the Change tooltip to longer be displayed or for some confirmation that "the new site icon has been added, press change to upload a new one."

#### What happened instead
Change tooltip is still being displayed or there's no confirmation that I've uploaded a new site icon. Also, the tooltip is covering the Change button.

#### Browser / OS version
Google Chrome Version 65.0.3325.162
Mac OS High Sierra 10.13.3

#### Screenshot / Video
![screenshot 2018-03-22 09 15 18](https://user-images.githubusercontent.com/4924246/37806705-a60b584e-2dfe-11e8-8a55-0a99dd2ad772.png)

/cc @fditrapani

**Comment by fditrapani** [comment]
Thanks for sharing @jancavan. The data is coming in for the checklist and I'll have some updates to share within the next week. I'll wait on prioritizing this until then.
