### ISSUE TITLE
Framework: Investigate using babel-polyfill

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#2360]
Currently babel-runtime does not polyfill all ES6 language features, so we sometimes run into bugs when we expect certain prototype methods to be available.

For example `String.prototype.startsWith` is unavailable in IE11

**Comment by blowery** [comment]
> Currently babel-runtime does not polyfill all ES6 language features...

Half true. We're not actually using `babel/polyfill`, we're using the `babel/runtime` with webpack, which only polyfills non-prototype things. So we get Map and Set and Object.assign, but not things on String.prototype like startsWith.

**Comment by blowery** [comment]
The concern in the past was the size of the full polyfill. Given the number of crasher bugs that have slipped through on various platforms because of confusion about what's available and what's not, I think we should bite the bullet and pull in the polyfill.

**Comment by gwwar** [comment]
> Half true. We're not actually using babel/polyfill, we're using the babel/runtime with webpack
;) was the title of this issue not clear enough?

**Comment by blowery** [comment]
:D

**Comment by blowery** [comment]
I have no idea what I thought I was adding when I wrote that original comment. Total reading comprehension fail on my part. Sorry about that. :person_frowning:

**Comment by gwwar** [comment]
No worries :+1:  Thanks for adding notes on the size concerns.

**Comment by rralian** [comment]
Minified and gzipped it looks like it's 32k ([grab the polyfill here to see](https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.9.1/polyfill.min.js)). That would bring our build.js from about 170k to about 200k. It's not insignificant, but I'd pay that price to enable the features and avoid the problems we've run into. Would be great if we could include it dynamically based on feature-sniffing though. Not sure if that's a thing.

@mtias I think you are the filesize arbiter and czar. What do you think?

**Comment by gwwar** [comment]
Fixed in #25419 by @jblz

**Comment by blowery** [comment]
> That would bring our build.js from about 170k to about 200k.

oh the good old days
