### ISSUE TITLE
Site Activation Email has Incorrect Information

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#23616]
#### What I expected - 
I created a new account/site and expected consistent information between the https://wordpress.com/ page and the activation email. 

#### What happened instead
The https://wordpress.com/ says that WordPress powers 30% of the Internet, and the email says 28%.

https://wordpress.com/
![screen shot 2018-03-24 at 8 55 41 am](https://user-images.githubusercontent.com/2545184/37864238-4bee7310-2f42-11e8-978f-f36aa0b5c5ef.png)

Email - 
![screen shot 2018-03-24 at 8 54 58 am](https://user-images.githubusercontent.com/2545184/37864244-5908f2fa-2f42-11e8-8ff4-7c7864d54c7b.png)

**Comment by rachelmcr** [comment]
cc @Automattic/marketing-dev Looks like this needs to be updated in the `activation-encourage` email.
