### ISSUE TITLE
Domain-only: Unable to add Site Redirect

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#23615]
Because of the way domains purchased from wordpress.com/domains (domain-only) work, if someone wants to redirect it, it's not possible without first purchasing a plan, refunding, and THEN adding a Site Redirect.

#### Steps to reproduce
1. Starting at URL: `wordpress.com/domains` - register a domain

2. Per this [support doc](https://en.support.wordpress.com/site-redirect/), go here to add a site redirect: https://wordpress.com/domains/add/site-redirect/

#### What I expected

I've just purchased a domain thinking WordPress.com is my registrar. But.. it's not allowing me to redirect the domain.

The registrar-experience could be improved.

#### What happened instead

Unable to add a redirect.

#### Context / Source
 #empathy  #flowsharing 
#user-report , #manual-testing

**Comment by rachelmcr** [comment]
Could you give more details about a scenario where a Site Redirect is required? I would expect that in most cases the domain could be pointed to the desired location, whereas a site redirect is meant for use with sites themselves (not domains only).
