### ISSUE TITLE
Emails for Replies to Comments not Coming Through

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#23617]
#### Steps to reproduce
1. Starting at URL: https://amehrling.com/2018/03/21/logans-snow-day/
2. I made a comment as Chrissie.

#### What I expected
When my comment was replied to, I would expect a notification, either in my notifications or by email if I had that set up (I don't). 

#### What happened instead
I never get a notification of responses from this site.

#### Browser / OS version

Firefox on MacBook Pr

#### Context / Source
This was reported in 1037310-zen and on https://jimadamsauthordotcom.wordpress.com/2018/03/24/problem-not-resolved/ (same user). I related to the issue from my own experience so I'm writing this up using my own details.

**Comment by designsimply** [comment]
Thank you for reporting this! 

Reporting here is ace (no problem at all), but since the code for sending email notifications is in our internal `wpcom.trac` system right now I have moved this issue to 8030-wpcom and cc'd you there.
