### ISSUE TITLE
Signup: /business and /premium sign up flows broken in IE11

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#23662]
#### Steps to reproduce
1. In IE11 clear all cookies/local storage/data
2. Starting at URL: https://wordpress.com/start/business or https://wordpress.com/start/premium
3. Continue past about
4. Choose a theme

#### What I expected

Domains screen to load

#### What happened instead

Domains screen is blank
Forcing page refresh eventually shows it

#### Browser / OS version

Tested IE11 on Windows 7 - could **not** reproduce on MS Edge Windows 10

#### Screenshot / Video

![ie11](https://user-images.githubusercontent.com/128826/37940581-cc2f9196-31ac-11e8-83ed-6ff9fc303a2f.gif)

#### Context / Source
 #automated-testing

**Comment by alisterscott** [comment]
@taggon @fditrapani any ideas about this? It seems to be fairly recent according to our e2e tests

**Comment by fditrapani** [comment]
The only thing I could think of is that it might be related to this: https://github.com/Automattic/wp-calypso/pull/22376#pullrequestreview-100202646

@taggon any thoughts?

**Comment by taggon** [comment]
@alisterscott @fditrapani I made a fix for this problem. Can you take a look?

**Comment by fditrapani** [comment]
Thanks @taggon. Looks good to me!

**Comment by alisterscott** [comment]
Re-tested and works well now - thank you
