### ISSUE TITLE
Editor: Date Picker: allow year to be changed without clicking through months

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/wp-calypso#23677]
Currently, the date picker in the page/post editor allows users to change the month or date on which a post was published. 
However, to change the year in which it was published, users must click through months until they reach the desired year.

#### Steps to reproduce

Head into My Site > Posts and choose a Post to edit, which has already been published.
In Post Settings > Status, click the "published" date and attempt to make it one year earlier.

Same steps are valid with Pages.

#### What I expected

To click on 2018 and change it to 2017, for example. 

#### What happened instead

Clicking on the year does nothing, and there isn't another way to change years.
Instead, I need to click through twelve months to get back to March 2017.

![mar-27-2018 15-22-54](https://user-images.githubusercontent.com/15107387/37967062-e887c892-31d2-11e8-8f91-4a1cdd85e76a.gif)

#user-report

**Comment by KokkieH** [comment]
Another request in https://en.forums.wordpress.com/topic/set-the-year-for-backdated-post/

**Comment by kriskorn** [comment]
Another request - #1635787-zen
