### ISSUE TITLE
Editor: VideoPress Shortcode Adds Phantom Span Tag While Swapping Editors with Cursor in Shortcode

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#23698]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/
2. Create a new post (Premium or Business Plan)
3. Add Media
4. Videos - Select a video.
5. The video will appear in the visual editor.
6. Switch to the HTML editor.
7. Place your cursor anywhere inside the shortcode after the wpvideo portion. Don't type anything. 
8. Switch back to the visual editor.
9. The video will disappear from the visual editor. Switch back to the HTML editor.
10. An HTML span tag has been added inside the videopress shortcode:
```
<span 				data-mce-type="bookmark" 				id="mce_SELREST_start" 				data-mce-style="overflow:hidden;line-height:0" 				style="overflow:hidden;line-height:0" 			>﻿</span>
```
#### What I expected
A span tag not to show up in the cursor's location inside the videopress shortcode.

#### What happened instead
A span tag mysteriously appears inside the shortcode, breaking the video's shortcode.

#### Browser / OS version
Chrome/Mac OSX

#### Screenshot / Video
https://cloudup.com/cR2kQOA0SV9

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
This looks like a side effect of the enhancement that preserves your cursor position when switching between Visual and HTML modes. cc @Automattic/delta-samus 

It looks like the cursor marker span isn't cleaned up when switching in this scenario: https://github.com/Automattic/wp-calypso/blob/e03a17041819684b671d0914a97f10583a048d5e/client/post-editor/post-editor.jsx#L1079

**Comment by spen** [comment]
Thanks for reporting and investigating! I've tracked this in Samus's work board :)
