### ISSUE TITLE
Component: Pagination: Compact mode one-pixel oddities

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#23747]
Note in https://github.com/Automattic/wp-calypso/pull/23664#issuecomment-376375220 by @greenafrican 

>Noticing a little difference in the arrow buttons and the number buttons in your screenshot above and here:

![screen shot 2018-03-28 at 14 16 58](https://user-images.githubusercontent.com/1160732/38028502-62152694-3293-11e8-8d3f-a32d4817bdb2.png)

>Another little UX issue I experienced with this was keeping my mouse still and click the right arrow, the width of the component changes as the numbers change so I ended up clicking the last number rather than the right arrow.

**Comment by psealock** [comment]
@greenafrican Are you zoomed in (or out) on your screen settings by chance?

>keeping my mouse still and click the right arrow, the width of the component changes as the numbers change

Hmmm, not too sure how to address this one. Indeed the use case is probably different than the original intentions of this component (ie, the page would gather the next page of new data and refresh, instead of rapid clicking).

**Comment by greenafrican** [comment]
@psealock 

>Are you zoomed in (or out) on your screen settings by chance?

Yup, so I could get a good screenshot. It looked exactly the same (relatively) though at 100% zoom.

> not too sure how to address this one

Yeah, it is a bit tricky and maybe we don't need to do anything now. My initial feeling though was that I would expect them to be stationary but I may be an outlier.
