### ISSUE TITLE
Domains: Spaces stripped out when adding/updating contact info

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/wp-calypso#23752]
Spaces disappear on the checkout page with iPad while typing. I also found a workaround while testing, which is to drag the typing bar in between the letters you want a space and then add the space. Also, if you type the space and then the next letter really fast the space seems to stay?

This arose in 1043817-zen

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains
2. Add a domain to your site and click checkout
3. Try typing in any of the input fields

#### What I expected
A space can be added

#### What happened instead
Spaces get removed on the spot.

#### Browser / OS version
iPad 2017 edition 
Safari 11
Chrome - 64.0.3282.112

#### Screenshot / Video
https://cloudup.com/c1mP6Vw7eVi

**Comment by KokkieH** [comment]
This is not iPad specific. Replicated the same in Firefox on a Mac:

![address](https://user-images.githubusercontent.com/11873759/38081144-8e7c017a-3343-11e8-882c-508c09a990cb.gif)

As described above, a pause of even half a second after adding a space leads to the space being stripped out, in both address and postal code fields. 

As some postal code, e.g. UK, can only validate if a space is included, this leads to a poor user experience as essentially we are preventing them from adding the code in the format we require.

Also related to the discussion in #8681

**Comment by KokkieH** [comment]
I'm also able to replicate this when updating contact information for an existing domain, so it is not specific to the checkout/registration flow.

**Comment by KokkieH** [comment]
Oh, also encountered the issue in 893423-f :)

**Comment by rachelmcr** [comment]
It looks like the form field is being sanitized (trailing space trimmed/stripped) too early in the process. I did a quick investigation and it looks like that's happening here:

https://github.com/Automattic/wp-calypso/blob/master/client/components/domains/contact-details-form-fields/index.jsx#L164

@Automattic/cobalt Is this something you're familiar with? It seems like this sanitizing should happen on form submit or when the input field loses focus, but it's happening when you pause briefly while the field is still in focus.

**Comment by aidvu** [comment]
Yep, familiar with it, and had discussions about this problem. Will think about how to fix this. :) (might just remove the `trim()` in the meantime.

**Comment by aidvu** [comment]
https://github.com/Automattic/wp-calypso/pull/23864

**Comment by klimeryk** [comment]
Had to revert that one. But this PR will hopefully fix it once and for all: https://github.com/Automattic/wp-calypso/pull/23873
