### ISSUE TITLE
Post checkout: Open links in same window

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#2377]
The links on the `/checkout/thank-you` page used to point to pages that weren't in Calypso, so they opened in a new window. Now they point to pages inside Calypso we should remove `target=_blank` so they don't reload the whole app.

**Comment by gziolo** [comment]
This is the case at least for:
- plan purchase
- domain purchase

**Comment by fabianapsimoes** [comment]
Fixed in #2810.
