### ISSUE TITLE
Activity: upgrade banner shows up on highest paid plan

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#23772]
Jetpack site with the highest paid plan (Professional) is incorrectly showing an upgrade banner on the Activity tab.

<img width="978" alt="screen shot 2018-03-29 at 15 33 58" src="https://user-images.githubusercontent.com/390760/38094802-bb25a3d4-3366-11e8-9547-2022a897d5d8.png">

**Comment by keoshi** [comment]
@eliorivero Can you take a look here? Is this a state for a12s sites only?

**Comment by eliorivero** [comment]
I can't repro this issue. Perhaps you can add me to this site so I can check the network responses to plan data requests?

**Comment by keoshi** [comment]
I’ve added you to the site, let me know if it worked.

**Comment by eliorivero** [comment]
It's good, thanks!

**Comment by keoshi** [comment]
Closing this per https://github.com/Automattic/jpop-issues/issues/1983#issuecomment-379246462

**Comment by keoshi** [comment]
Seeing this issue again. @eliorivero can you take a look?

![image](https://user-images.githubusercontent.com/390760/41474604-52d8f138-70b4-11e8-9c35-84447de3574e.png)

Related https://github.com/Automattic/wp-calypso/issues/22452

**Comment by keoshi** [comment]
We chatted on slack:

> this site has that billing issue where rewind is not aware of the plan

Closing for now.
