### ISSUE TITLE
Signup: URLs with a locale are causing inaccurate `context.params`.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#23783]
While investigating, #23523 , I noticed that URLs with a locale were causing buggy `context`s to be passed to the signup controller.

![context](https://user-images.githubusercontent.com/349751/38110692-509aaaec-3351-11e8-829f-d5a8fb3088c5.png)

This could be affected by poor handling in `setupLocale`: https://github.com/Automattic/wp-calypso/blob/master/client/signup/index.node.js#L14

**Comment by gwwar** [comment]
@kwight should we give nux a heads up on this and remove from backlog?

**Comment by kwight** [comment]
Posted to p5XAZ9-1HD-p2 👍

**Comment by alisterscott** [comment]
I've tried a sign up on https://wordpress.com/start/fr and couldn't reproduce this - is this still an issue?
