### ISSUE TITLE
Login: post-login pages should display the login form for logged-out users

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#23785]
We should have a framework-level approach to handling logged-out users who load a route requiring login. Right now we display a blank page with links to "sign up" and "log in" in the top bar.

![logged out view](http://cld.wthms.co/0T41QQ+)

But users interpret this as a broken/blank page.

There's a PR to address this for a particular route here #23548.

We were just discussing in slack that this should probably be handled at the nginx level. There are other routes where users wind up seeing these blank pages, for example when we link them to view their receipts from wpchrg.com. It should probably be the default for post-login content to be handled this way, rather than something we need to code specially for each route. I don't think we ever want users to see that blank page.

Assigning to @blowery to figure out how to properly assign to team @Automattic/team-calypso

**Comment by rachelmcr** [comment]
Some related issues: https://github.com/Automattic/wp-calypso/issues/23623, https://github.com/Automattic/wp-calypso/issues/22857, https://github.com/Automattic/wp-calypso/issues/23033

**Comment by designsimply** [comment]
Added the `[Pri] High` label because this issue has been referenced multiple times and because the masterbar is hidden while editing, logged-out views for pages such as https://wordpress.com/post/ show up as a completely white screen with no navigation.

![screen shot 2018-06-06 at wed jun 6 2 25 53 pm](https://user-images.githubusercontent.com/1119271/41063365-a9cebdb8-6995-11e8-9c22-2a98905b16b1.png)
<sup>Seen at https://wordpress.com/post using Firefox 60.0.1 on macOS 10.13.4.</sup>

**Comment by rralian** [comment]
@sirbrillig can you take a look at this? I thought we had addressed this, but I don't remember if that was done for specific routes or at the framework level. Can we use the same approach for high priority routes if that's faster than waiting for a framework-level fix?

**Comment by blowery** [comment]
I think we can drop the priority here.

We've spun through this a couple times and it's complicated and fragile to solve generically with `page.js`. The only way to add a 404 handler is by attaching a `*` route handler as the _last_ handler overall. However, we add routes on the fly when async loading code...

**Comment by blowery** [comment]
Sticking it on @Automattic/team-calypso's radar again, even with the dropped priority.

**Comment by jsnajdr** [comment]
This has been solved over the last few years by consistently marking which pages are intended for logged-out users and redirecting all other pages to login page.
