### ISSUE TITLE
Sidebar: text overflow issues at medium size screen for sharing screen

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-calypso#238]
![pasted image at 2015_11_19 12_25 pm](https://cloud.githubusercontent.com/assets/260253/11283136/3a9c8840-8ed1-11e5-8cf6-1f46ba8614bd.png)

**Comment by lancewillett** [comment]
This has been fixed in recent redesigns.

Current, with wpcalypso and Mac-n-Chrome:
![screen shot 2016-04-07 at 10 31 16](https://cloud.githubusercontent.com/assets/66797/14360572/eae63b86-fcab-11e5-96e7-6f1b56707aef.png)
