### ISSUE TITLE
Customizer: cannot crop header image in small screens

### ISSUE THREAD

**Issue by joelwills** [Automattic/wp-calypso#2380]
It is not possible to see/press the "Crop Image" button in the Customizer on an iPhone 5 with tall images.

Using the app or the browser, in portrait mode the Crop Image button is not visible if the image is portrait/too tall:

![img_4208](https://cloud.githubusercontent.com/assets/3228004/12301681/2f7d5810-b9d6-11e5-8f7e-ac967893d5c1.jpg)

In landscape mode the button can be partially seen (slightly more can be seen in mobile Safari, the screenshot is from the app):

![img_4209](https://cloud.githubusercontent.com/assets/3228004/12301688/343b2f8a-b9d6-11e5-8bd1-6ec6bfafb553.jpg)

No scrolling is possible, either causing strange behavior with a white background coming up with my scroll, covering the screen rather than the screen moving to see what’s below. Or nothing happening at all when trying to scroll.

To replicate, select any site, select Themes, press Customize, then choose Header Image. Select "Add New Image", choose an image that is portrait or quite tall, and press "Select and Crop".

Thanks!

**Comment by lancewillett** [comment]
I'm still able to repeat this — can't get to the Crop button. Testing with iPhone 6+ in Simulator.app.

Header Image section in Customizer:

<img width="578" alt="screen shot 2016-04-27 at 10 58 31 am" src="https://cloud.githubusercontent.com/assets/66797/14862675/57ef8f1e-0c67-11e6-86c0-05f736494400.png">

Pick an image:

<img width="578" alt="screen shot 2016-04-27 at 10 58 39 am" src="https://cloud.githubusercontent.com/assets/66797/14862681/607ee08a-0c67-11e6-9240-14b2ab139ae0.png">

Can't crop :/

<img width="578" alt="screen shot 2016-04-27 at 10 59 03 am" src="https://cloud.githubusercontent.com/assets/66797/14862692/6918a6ea-0c67-11e6-8851-6b81c47eb2c8.png">

**Comment by alisterscott** [comment]
I encountered this also today.

**Comment by lancewillett** [comment]
Moved to internal Customizer bug list since this isn't specific to Calypso.
