### ISSUE TITLE
Checkout: Prompt user to use correct account when visiting /checkout/:site/:plan

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#2381]
If users visit `/checkout/:site/:plan` (the 'purchase now' link in most of the free trial emails) when logged in to an account that is not the owner of `:site`, they are redirected to the site picker with no explanation. We should add messaging here to notify users that they need to log in to the account that owns `:site` to purchase a plan.

@mikeshelton1503 Do you think we should handle this with a notice?

**Comment by mikeshelton1503** [comment]
>Do you think we should handle this with a notice?
Yea I think so. It's not a perfect solution, however this seems like it would be a fairly uncommon situation. 

I will note that the checkout link is just one of example of the general problem: clicking any link to a site that's associated with another account. Is this something we want to solve for all cases or just specifically the checkout (that's really a question of feasibility and scope of work)?

**Comment by fabianapsimoes** [comment]
Moving this to v2 since, as Mike said, this should be a fairly uncommon case.

**Comment by fabianapsimoes** [comment]
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.
