### ISSUE TITLE
Timezone suggestion selects always the first element

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#23869]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/%SITE%
2. click the suggestion as shown in the GIF

![cualquiera](https://user-images.githubusercontent.com/1041600/38271538-1a42cbe0-375d-11e8-9be6-9addcd12947f.gif)

**Comment by lancewillett** [comment]
This should be fixed now.
