### ISSUE TITLE
Media: Dropdown filter does not work.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#23878]
At different screen widths, the media filter alternates between text tabs and a dropdown. It works fine when in tabs, but doesn't work when a dropdown.

![dropdown](https://user-images.githubusercontent.com/349751/38278081-7d33a912-374f-11e8-9e7a-f575dce659b3.gif)

The filter items [are generated](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/filter-item.jsx) by `FilterItem`, and get [converted to a dropdown](https://github.com/Automattic/wp-calypso/blob/master/client/components/section-nav/tabs.jsx#L108) in `NavTabs`.

It seems like [this click handler](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/filter-item.jsx#L15) is firing properly for tabs, but not getting passed to the dropdown items, and may have something to do with `onClick` vs. `onChange` props.

**Comment by gwwar** [comment]
Note that it's broken for this view:
<img width="471" alt="screen shot 2018-04-03 at 4 21 44 pm" src="https://user-images.githubusercontent.com/1270189/38280736-d245ed8c-375b-11e8-8980-8e10fe706043.png">

But not this one:
<img width="403" alt="screen shot 2018-04-03 at 4 22 02 pm" src="https://user-images.githubusercontent.com/1270189/38280740-d9d594e4-375b-11e8-8c95-f61bb8ff39f8.png">
