### ISSUE TITLE
Store: Restrict Referrer Stats to Business Plan Users

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#23874]
Prior to launching the new referrer stat views on Store Stats, we should add logic to only display the reporting widgets to sites that have an active Business Plan. As-is, all Store Stats on Calypso are available to any Jetpack-connected WooCommerce site, but with the new enhanced reporting data coming online, we want to limit access to those reports ( like Referrers ) to business plan users initially.

So this task should ideally be implemented prior to enabling the new stat widgets in Production.

/cc @psealock

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
