### ISSUE TITLE
Domain Management: unlimited email forwards is missing for the business plan

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2387]
Raised by @ranh

> Email forwarding used to offer unlimited forwarding rules on sites with WordPress.com Business. It looks like this was lost during the switch to Calypso.

Steps to reproduce:

1. Start at https://wordpress.com/ and switch to a site with a business plan
1. Glo to My Sites > Domains
1. Click on a mapped domain (map one if you haven't already)
1. Click on the "Email" link
1. Click on the "Email Forwarding" link
1. Fill out the form and click the "Add New Email Forward" button
1. Repeat the last step until you have more than 5 email forwards

Result: got stuck and could not add more than 5 email forwards. The following note appeared at the bottom of the email forwarding page after 5 email forwards had been added:

> You are using 5 out of 5 email forwards.

![screen shot 2016-01-13 at 14 39 05](https://cloud.githubusercontent.com/assets/1119271/12305581/8b69fcdc-ba03-11e5-84e4-e0740ef2d156.png)
<sup>Tested with Firefox 43.0.2 on Mac OS X 10.10.5</sup>

Video: https://cloudup.com/coVyMy9qYXu

Comment from @bikedorkjon 

> In https://github.com/Automattic/wp-calypso/blob/53bde8c3f9c4668e62dbd2c670aaacc2bd820427/client/my-sites/upgrades/domain-management/email-forwarding/email-forwarding-add-new.jsx#L40 I added this:
> 
> ```
> 	hasReachedLimit() {
> 		let emailForwardingPlanLimit;
> 		if ( this.props.selectedSite.plan.product_id = 1008 ) {
> 			emailForwardingPlanLimit = 100;
> 		} else {
> 			emailForwardingPlanLimit = 5;
> 		}
> 
>		return this.props.emailForwarding.list.length >= emailForwardingPlanLimit;
> 	},
> ```
> 
> But that doesn't deal with the list rendering in email-forwarding-limit.jsx and I'm not sure the best way of going about this so I'm not writing duplicate code.

Comment from @gziolo 

> There is hardcoded 5 in email-forwarding-limit.jsx. I see what you mean.
>  I think the best idea is to move:
> ```js 
> let emailForwardingPlanLimit;
>     if ( this.props.selectedSite.plan.product_id = 1008 ) {
>         emailForwardingPlanLimit = 100;
>     } else {
>         emailForwardingPlanLimit = 5;
>     }
> ```
> into its own helper method with plan or productId as param passed. Then you should be able to reuse it easily. You can put this method in this folder: https://github.com/Automattic/wp-calypso/tree/53bde8c3f9c4668e62dbd2c670aaacc2bd820427/client/lib/domains/email-forwarding
Just create index.js file. Good luck :)

**Comment by breezyskies** [comment]
We should also add this to the plan comparison chart so we're advertising it properly.

**Comment by wensco** [comment]
Closing this in favor of #3156
