### ISSUE TITLE
Domains: Add further specificity to primary domain errors

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#23880]
#### Steps to reproduce
1. Set a primary domain that isn't possible.
2. Get a very generic message:
![screen shot 2018-04-03 at 9 48 34 am](https://user-images.githubusercontent.com/8921630/38279532-8cdb0148-3755-11e8-8568-227dbcf0f260.png)

#### What I expected
Something that says why the domain can't be primary. Common reasons:
1) Domains is not yet using our name servers, please point it to our name servers.
2) Domain has not yet generated an SSL certificate, please wait longer.
3) Domain is pointed away from us through DNS. Please delete any root level A records.
4) Others?

If requesting a new feature, explain why you'd like to see it added.
-->
Errors like this could clarify for users what is going on and help them either 1) be patient 2) fix it themselves or 3) come to chat informed of what is needed and help us reduce troubleshooting time.

**Comment by kelliepeterson** [comment]
Closing this. 

We introduced status indicators on domains to advise there are additional actions required which provide guidance in these cases.
