### ISSUE TITLE
Community Translator: Overlapped by the new Inline Help Button

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#23884]
Introduced in #23739, the new float overlaps the Community Translator button:

![screen shot 2018-04-04 at 11 03 19](https://user-images.githubusercontent.com/203408/38298940-118537ee-37f9-11e8-8246-c700ba4b4007.png)

As a short-term fix we could probably move the button out of the way but longer-term we should decide whether we should put the button elsewhere.

**Comment by southp** [comment]
This has been fixed by #24705 already, so I'm closing this.
