### ISSUE TITLE
Purchases: "Cancel" language confusing and inconsistent

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#2392]
In #1402 @fabianapsimoes mentioned:
>Within the refund window, "Cancel" means we'll remove the subscription, cancel the registration, and refund the payment. Outside the refund window, "Cancel" means we'll disable automatic renewal, and then we have "Remove" which means we'll remove the subscription and cancel the registration. So, with domains, depending on the refund window, "Cancel" has different meanings and implications.

@wensco mentioned:
>I haven't worked with this flow very much so I have somewhat fresh eyes. To me, this is confusing. We're using one word (cancel) to describe two very different sets of actions:

>cancel = disable auto-renew and let me use the domain until it expires, or until I renew it
cancel = refund me, cancel the registration, and remove the domain from my account (possibly giving up the domain permanently)
I'm a little late to the party on this one, but it feels like we should have a standard set of clear terms that mean distinct actions/states.

>Maybe something like:

>Unsubscribe: disables automatic renewal, but leaves the upgrade subscription intact and functioning until it expires (or for domains, past expiration to cover grace period/redemption renewals). This would address the issue that @aisajib mentioned where users can't disable automatic renewal for domains within the refund window.
Cancel: removes the subscriptions and cancels the domain registration; refunds the purchase if canceled within the refund window
Remove: removes the subscriptions for expired domains

**Comment by fabianapsimoes** [comment]
The current notice when you cancel a subscription says:

> testingupgradesagainagain.co was successfully cancelled. It will be available for use until it expires on November 25, 2016.

Especially for domains, it'd be nice if the notice made it clear the cancellation is related to the subscription. Maybe something like:

> *Your subscription* for testingupgradesagainagain.co was successfully cancelled. *Your purchase* will remain available for use until it expires on November 25, 2016.

**Comment by mikeshelton1503** [comment]
After some research and discussion here are a few changes I think we should make to clarify the use of "Cancel":

### Change Cancel Button Copy

**Button copy inside refund window:**
> Cancel Subscription and Refund

_Domains:_
> Cancel Domain and Refund


**Button copy outside refund window:**
>Cancel Subscription After Expiration

_Domains:_
>Cancel Domain After Expiration

_Privacy Registration:_
>Cancel Private Registration 

### Change Cancel Screen Copy

The button copy changes require changes to the copy on the Cancel screen as well. Along with the copy changes I have updated the design on the Cancel screen to present the relevant information clearer. Those design copy changes have represented below (along with the button copy changes).

![cancel-flow](https://cloud.githubusercontent.com/assets/12596797/12703857/6936e384-c81b-11e5-8377-664722c8a3c2.png)

@ranh Could you have a look at the copy on Cancel screen?

**Comment by ranh** [comment]
Due to the potential for confusion I suggest we go even further in some of your examples @mikeshelton1503.

### Refundable plan:

Action: **Cancel and refund**

Excluding "subscription" here reduces chance for confusion with the other actions below.

Description on cancel screen:

> Your plan is still in the 30-day refund period. If you cancel now, you will receive a full refund and your site will revert to the free plan. 

### Non-refundable plan: 

Action: **Disable automatic renewal**

We tried to avoid this phrasing, but I think it's the best description in this context. Some alternatives that may also work if we really don't want to say this:

Action: **Don't renew my subscription automatically**

Action: **Unsubscribe**

Description on cancel screen:

Your plan is based on a yearly subscription that renews automatically. If you (disable automatic renewal/unsubscribe), your site will remain on the current plan until it expires, and then revert to the free plan automatically. 

### Refundable domain:

Action: **Cancel domain and refund**

 Description on cancel screen:

> Your domain is still in the 2-day refund period. If you cancel now, you will receive a full refund, and your site will no longer be available at this domain. 
>
> Do not cancel this domain if you want to move or reuse it: canceled domains may not be available for registration again.

Added a note specific to canceling domains. 

### Non-refundable domain: 

Action: **Disable automatic renewal**

Action: **Don't renew my subscription automatically**

Action: **Unsubscribe**

Description on cancel screen:

> Your domain is based on a yearly subscription that renews automatically. If you (disable automatic renewal/unsubscribe), it will remain active until it expires, at which point your site will no longer be available at this domain. 

Action for removing unsubscribed domain: **Delete domain** 

"Delete" is a bit more accurate than "remove from site" in the case of domains, since the action is not just local to the site itself. Also, I think that "deleting" a domain is a term that is used by other hosts/registrars. 

We would then need another confirmation screen for deleting the domain. Something like:

> Your domain is set to expire on (date), and it will be removed from your site automatically when it expires. Deleting it now will remove it from your site immediately. 
>
> Do not delete this domain if you want to move or reuse it: deleted domains may not be available for registration again.

**Comment by mikeshelton1503** [comment]
Thanks Ran! A few thoughts on your suggestions:

>Refundable plan:
>Action: Cancel and refund
>Excluding "subscription" here reduces chance for confusion with the other actions below.

I felt that using subscription here helped to add clarity about what's being canceled. I agree it would have to change if we use some of the other suggestions you made, but I'm not we sure need to make those :) _(keep reading)_.

>Non-refundable plan:
>Action: Disable automatic renewal
>We tried to avoid this phrasing, but I think it's the best description in this context. Some alternatives that may also work if we really don't want to say this:

I feel strongly that we should avoid using the phrase "automatic renewal" or anything like it everywhere, in all cases. We decided to remove auto-renew as a setting and so long as that's true I don't think we should refer to the action as "automatic renewal". If the user clicks "disable automatic renewal" they may then wonder where the "Enable automatic renewal" link is. Also some current users may have become used to the auto-renew language, and while we don't want to alienate them (I don't think we are), using "auto-renew" language may add confusion if they're expecting to find an auto-renew setting that doesn't exist anymore.

"Unsubscribe" could work, however I'm not sure that it's any stronger than "Cancel Subscription After Expiration". The latter offers more clarity.

>Action for removing unsubscribed domain: Delete domain
>"Delete" is a bit more accurate than "remove from site" in the case of domains, since the action is not just local to the site itself. Also, I think that "deleting" a domain is a term that is used by other hosts/registrars.
>We would then need another confirmation screen for deleting the domain. Something like:

:+1: I think "Delete" works and offers bit more clarity for domains. Good call! 

We already have a modal that pops up after you click remove/delete so we can just replace the current copy there with what you suggested.

Also, all of the cancel screen copy looks great to me (with the exception of references to "automatic renewal" but I can easily edit that). Good call on adding this:

>Do not cancel this domain if you want to move or reuse it: canceled domains may not be available for registration again.

**Comment by fabianapsimoes** [comment]
We should also take into consideration https://github.com/Automattic/wp-calypso/issues/2177, whenever we start working on these flows.

**Comment by fabianapsimoes** [comment]
@mikeshelton1503 since we might be working on this soon, can you take a look and see if there's anything we can do to address the issues mentioned in #2177 as well?

**Comment by fabianapsimoes** [comment]
@mikeshelton1503 another question: in this redesign, we'd no longer have emails to confirm cancellations? Asking because of https://github.com/Automattic/wp-calypso/issues/728.

**Comment by mikeshelton1503** [comment]
>since we might be working on this soon, can you take a look and see if there's anything we can do to address the issues mentioned in #2177 as well?

Fixing the issue of the wrong price being noted and refunded should clear up a lot of the confusion there but that's probably best handled separate of these changes. I do agree with clarifying in the copy that when you cancel Business you'll be reverted to the Free plan. I need to provide copyable text from the above changes anyways so when I do that I'll add copy for that.

>another question: in this redesign, we'd no longer have emails to confirm cancellations? Asking because of #728.

That's right, no need to confirm it right away since they we still receive the renewal emails.

**Comment by fabianapsimoes** [comment]
> That's right, no need to confirm it right away since they we still receive the renewal emails.

@mikeshelton1503 Does this mean we should start having confirmation emails when users remove unsubscribed purchases?

**Comment by fabianapsimoes** [comment]
We should keep in mind we're sticking with Privacy Protection instead of Private Registration (see https://github.com/Automattic/wp-calypso/issues/1938).

**Comment by mikeshelton1503** [comment]
>Does this mean we should start having confirmation emails when users remove unsubscribed purchases?

Good question. Unless we need to send them for a security concern (unauthorized cancellations) I don't think it's necessary to confirm the removal of an unsubscribed purchase. There are now two actions needed to cancel and then remove so users taking both actions back to back would likely be intentional. We also display a modal that informs you what the remove action does and asks you to confirm. An additional confirmation via email seems unnecessary.

**Comment by mikeshelton1503** [comment]
Ok a few updates here for confirmations.

**Updated flow (with annotations):**

![cancel-flow-v2](https://cloud.githubusercontent.com/assets/12596797/13954647/15df7bcc-f018-11e5-8c18-fcb507e2da60.png)

**No more confirmation emails**

We will no longer send confirmation emails of cancelations. All confirmations will be handled on the page.

**Refundable Plan Confirmation**

We will show a modal window to confirm the action.
![image](https://cloud.githubusercontent.com/assets/12596797/13954989/571e7f24-f019-11e5-8c6e-62ef74fac3de.png)

**Refundable Domain Confirmation**

We will use the same survey form we currently do (with a few copy changes and minor design tweaks). The form itself should function the same as it presently does.

![image](https://cloud.githubusercontent.com/assets/12596797/13955007/710da810-f019-11e5-92b5-c1fe1182671f.png)

**Comment by mikeshelton1503** [comment]
Here's all of the copy to make copy and pasting easy :smile: 

### Refundable plan:

Action: **Cancel Subscription and Refund**

Description on cancel screen:

> Cancel Your WordPress.com Premium Subscription
>
> When you cancel your subscription within 30 days of purchasing, you’ll receive a refund and it will be removed from your site immediately.
>
>Have questions? Ask a Happiness Engineer!

Confirmation message:

> Cancel WordPress.com Premium
>
> Are you sure you want to cancel and remove WordPress.com Premium from miketestsite.wordpress.com? All plan features and custom changes will be removed from your site and you will be refunded $99.

Confirmation window actions:
[No, I'll Keep It]
[Yes, Cancel Now]


### Non-refundable plan:

Action: **Cancel Subscription After Expiration**

Description on cancel screen:

> Cancel Your WordPress.com Premium Subscription
>
> When you cancel your subscription, you’ll be able to use WordPress.com Premium until your subscription ends. Once it ends, it will be automatically removed and your site will switch to the WordPress.com Free plan.
>
> Have questions? Ask a Happiness Engineer!

Remove action:

> Delete Permanently From Site


### Refundable domain:

Action: **Cancel Domain and Refund**

Description on cancel screen:

> Cancel example.com
>
> When you cancel your domain within 2 days of purchasing, you’ll receive a refund and it will be removed from your site immediately. 
>
> Have questions? Ask a Happiness Engineer!

Description on cancel confirmation screen:

> We’ll help you cancel your domain and be sure you receive a refund, but first we want to make sure canceling your domain is the best option. Canceling a domain can cause your site to stop working so we want to get it right.
>
> Why do you wish to cancel mikeshelton.co?

Use existing options in select menu and use existing copy for all other paths.


### Non-refundable domain:

Action: **Cancel Domain After Expiration**

Description on cancel screen:

> Cancel example.com
>
> When you cancel your domain, it will remain registered and active until the registration ends, at which point it will be automatically removed from your site.
>
> Have questions? Ask a Happiness Engineer!

Remove action:

> Delete Permanently From Site

**Comment by spncrb** [comment]
A few questions and comments:
1) From non-refundable domain:

> When you cancel your domain, it will remain registered and active until the registration ends, at which point it will be automatically removed from your site.

Are we actually going to do this for the user?  As it stands now - we leave it on the site through redemption before removing it.  If we are actually going to remove the subs after it expires - then this copy is good. 

If behavior isn't being changed, the copy is a lie, we leave it on the site for a while and odd stuff starts happening.  It maybe be worthwhile to say something like:

> When you cancel your domain, it will remain active until the registration ends, at which point it will follow the domain expiration process.

With a link to https://en.support.wordpress.com/domains/domain-expiration/ . I know this makes it more complicated, but saying we will remove it sets expectations that it will be available again at the point of expiration - which isn't the case.

2) This section doesn't make perfect sense yet (plan purchase past refund):
![screen shot 2016-03-22 at 5 56 57 pm](https://cloud.githubusercontent.com/assets/8921630/13972622/8a21dec8-f057-11e5-9488-0a1e002eb577.png)

> When you cancel your subscription, you’ll be able to use WordPress.com Premium until your subscription ends. Once it ends, it will be automatically removed and your site will switch to the WordPress.com Free plan.

This doesn't make sense to me - didn't I cancel my subscription today?  Why is it going to cancel itself later on?

Something like this makes more sense to me:
> When you cancel your subscription, you’ll be able to use WordPress.com Premium until it expires. Once it expires, it will be automatically removed and your site will switch to the WordPress.com Free plan.

this lines up with the wording on /purchases - when the renewal date changes to an expiration date.

3) (same case) The text at the bottom "Subscription to be cancelled on Nov 4" contradicts what it says above - the subscription cancellation is the act of removing auto-renew and allowing the purchase to expire naturally.

I'd go with:

> WordPress.com Premium will be removed on November 4, 2016

or maybe

> WordPress.com Premium will expire on November 4, 2016

**Comment by mikeshelton1503** [comment]
>Are we actually going to do this for the user? As it stands now - we leave it on the site through redemption before removing it. If we are actually going to remove the subs after it expires - then this copy is good.

It was my intention and my understanding that yes we will remove it when it expires since the user expressly to that action. Renewal emails would still send up to the expiration date though.

>This doesn't make sense to me - didn't I cancel my subscription today? Why is it going to cancel itself later on?

I see your point. I agree with your copy suggestion, however we would also need to change the action copy on the previous screen from "Cancel Subscription After Expiration" to just "Cancel Subscription" since the copy you suggested implies that the subscription is being cancelled today but the product will remain and expire on XX/XX/XX date vs. the subscription remaining intact until the expiration date.

>WordPress.com Premium will be removed on November 4, 2016

:+1:

**Comment by melanieharari** [comment]
I've got a few questions after reading through this
- Do you have a cancellation confirmation screen?
- For Domain Purchase past 30 day window, does the “Delete permanently from site” link on the last step allow the user to cancel the domain immediately? If not, we may need an option for users who want to cancel their domains in order to delete their sites
- How will you handle plan cancellations with domain registrations (during and outside of the refund period)?

**Comment by mikeshelton1503** [comment]
>Do you have a cancellation confirmation screen?

Do you mean confirmation that cancelation was successful? We will display success notices floated in the top right corner (of which I need to provide copy for).

>For Domain Purchase past 30 day window, does the “Delete permanently from site” link on the last step allow the user to cancel the domain immediately?

Yes when you delete it you are canceling the domain registration.

> How will you handle plan cancellations with domain registrations (during and outside of the refund period)?

The same as we do now, no changes. What do we do now? If you have a domain linked to a plan you must cancel the plan first. Canceling a plan will leave the domain on your account as an individual purchase.

**Comment by drewblaisdell** [comment]
@mikeshelton1503 Should we use the plan copy above for non-plan purchases, like site redirects?

e.g. "Cancel You WordPress.com Premium Subscription" → "Cancel Your Site Redirect Subscription"

**Comment by mikeshelton1503** [comment]
Yes let's go with "Cancel Your [insert product] Subscription" for now. It's a little odd for Site Redirect but we can revisit later if needed.

**Comment by fabianapsimoes** [comment]
> It was my intention and my understanding that yes we will remove it when it expires since the user expressly to that action. Renewal emails would still send up to the expiration date though.

@mikeshelton1503 we do not remove the subscriptions once the domain has entered the expiration period. We only remove them once the domain has fully expired (went through all phases of the expiration period), and no longer belongs to us. We don't have plans to change this behavior for this iteration, in which case I believe Spencer's suggestions for the domains copy make sense.

**Comment by scruffian** [comment]
I believe everything in this issue has been taken care of, so I am closing it. If there are any things we missed, or more questions, please open new issues as this one is getting too big to follow.
