### ISSUE TITLE
People: Scrolling through team list causes an unresponsive page

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#23937]
Edit by @gwwar: I'd recommend for any content we need to manage that we have a simple pager instead of an infinite list. Infinite lists are usually better for consuming content.

When scrolling through the people list (at `/people/team/:site`), I somehow triggered an infinite loop where the InfiniteList component keeps trying to update state. I end up with an unresponsive page, and this error:

`Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops. The above error occurred in the <InfiniteList> component`

<img width="766" alt="screen shot 2018-04-05 at 11 03 30 am" src="https://user-images.githubusercontent.com/541093/38374168-0177e374-38c1-11e8-84a8-db0aee029cc2.png">

I discovered this on a site with 22 people, replicated on a site with 734 users, but could not replicate on a site with 2 users (there was no scroll).

This is on Mac OS/Chrome.

---

Update by @mattsherman:

As mentioned in #25609, this also happens in the `/people/followers/{site}` section.

**Comment by mattsherman** [comment]
This is high priority, as it prevents accessing people further down the list.

**Comment by mattsherman** [comment]
`InfiniteList` does not appear to have this problem with its usage in `client/reader/stream/index.jsx`.

**Comment by mattsherman** [comment]
@Automattic/tanooki will look into this

**Comment by mattsherman** [comment]
Due priorities and team capacity we haven't looked into this. I'll chat with @lancewillett to see if we can find capacity to address this.

**Comment by rachelmcr** [comment]
Thanks! I came across this issue because it's marked high priority; feel free to change the `[Pri]` label if this is not a current priority.

**Comment by ashercantrell** [comment]
#1884720-zen seems to be related. The user has the email followers page crash to a blank white page when scrolling. They also aren't shown all of their email followers (about 32 out of 90+). I am able to replicate this by scrolling until it stops, then trying to scroll back up. Everything disappears and the page must be reloaded.

**Comment by allykmyta** [comment]
#1935475-zen another issue that seems related. Replicated issue by going to Followers, scrolling down and then back up - page would then go blank. Refreshing page brings it back temporarily until we repeat the steps again.

**Comment by allykmyta** [comment]
Another issue reported here #1936344-zen

**Comment by darnelldibbles** [comment]
Was about to create a new issue, but came across this open one. Here is what I found:

I have come across a few instances 
(#1827744-zen and https://en.forums.wordpress.com/topic/how-to-see-blog-followers/)
where a user's page goes blank while scrolling down their email follower list under <a href="https://wordpress.com/people/email-followers">My Sites > Manage > People > Email Followers</a>. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12860686/56503016-0a4d5880-64da-11e9-949e-48e49ca01ada.gif)

It is an intermittent bug. I was able to get to the bottom of the email list every 4-5 refreshes. But, as you see in the video, most of the time the page goes blank after scrolling through the first few emails. This is an issue that only happens in Chrome. I did testing under Firefox and Safari and had no problems scrolling all the way to the bottom.

I went to the console to see if any errors popped up while scrolling and the following appears whenever the goes blank:

![Screen Shot 2019-04-22 at 8 00 00 AM](https://user-images.githubusercontent.com/12860686/56502740-fce39e80-64d8-11e9-8bad-19f9f1550f18.png)

**Comment by sixhours** [comment]
I'm able to reproduce this within the `InfiniteList` component on the Followers page as well (see closed ticket, above).

**Comment by donpark** [comment]
I do not have a site with a lot of users nor followers. I did short-circuit SiteUsersFetcher to inject 400 cloned users and tested but was not able to reproduce this bug.

**Comment by mattsherman** [comment]
I believe I've seen this with team lists for internal Automattic sites in the past.

**Comment by donpark** [comment]
> I believe I've seen this with team lists for internal Automattic sites in the past.

LOL. Can't believe I didn't think of testing with internal sites.

Just tested a few P2s but no 'luck' so far.

**Comment by donpark** [comment]
Fix for this issue has been deployed. I could not go through the full length of dotcom team list before but now I can with the patch. Thanks to everyone who contributed to getting this issue reported and fixed. 👍

**Comment by donpark** [comment]
UPDATE: This fix had to be reverted because it was causing [Media Library to go into infinite loop](https://github.com/Automattic/wp-calypso/issues/34464).

This means we may have  to reimplement InfiniteList which will take some time.

**Comment by deancroyal** [comment]
Another instance of it in #15404778-hc

"There are 34 people in your team" -- page breaks when scrolling down past the 18th person, every time. Impossible to see the remaining 16 people.

**Comment by lancewillett** [comment]
This came up today in a customer feedback ticket ( 2407927-t )

> The list WP is generating is hard to work with, except in the case of the most recent followers. The list as a whole seems not to be searchable, and as I scroll down into the past, older followers, the software resists, let’s say. **I can get bumped out of the scrolling process, etc**. What I am trying to do is to scout out followers I want to remove because they seem to be purely commercial sites or bogus or fishy in some way

**Comment by donpark** [comment]
@lancewillett I think InfiniteList needs either a rewrite or replacement. The way the current implementation initializes and manages state is very problematic.

**Comment by daledupreez** [comment]
I can also reproduce this in `/me/notifications` in Chrome on Mac. Note that this page lists many internal Automattic sites that I follow, so it is likely to be triggerable for other Automattic staff members.

**Comment by creativecoder** [comment]
Long lists of users still seem to be a problem in my testing just now.

**Comment by youbrokesomething** [comment]
It looks like there's been a couple of attempts at fixing this with the most recent, that I can find, being from October 2019. I can't reproduce the issue now and there have been no updates in over a year. So, I'm going to close this. Please reopen if there's a new user report.
