### ISSUE TITLE
Checkout: same card listed multiple times in Billing History and checkout

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2394]
Steps to reproduce:
1. Go to https://wordpress.com/ > My Sites > Domains
2. Purchase a domain mapping
3. Click your Gravatar in the top toolbar
4. Click the "Manage Purchases" link on the left
5. Click the "Edit Payment Method" link
6. Re-enter the same credit card details from before and click the "Update Card" button
7. Click the "Billing History" link
8. Note that the "Manage Your Credit Cards" section now has duplicate cards listed
9. Wait for domain mapping to offer a renewal option
10. Click the "Billing History" link
11. Click on an purchase that needs to be renewed
12. Click the "Renew Now" button (near the top right)
13. Note that the checkout page also has duplicate cards listed

Result: after you update card details, multiple listings of an identical card appear in the "Manage Your Credit Cards" section and on the checkout page:

![screen shot 2016-01-13 at wed jan 13 3 47 39 pm](https://cloud.githubusercontent.com/assets/1119271/12308008/ce374454-ba10-11e5-9425-5c822bc8a333.png)

![screen shot 2016-01-13 at wed jan 13 3 50 55 pm](https://cloud.githubusercontent.com/assets/1119271/12308007/ce36387a-ba10-11e5-84e2-0c6e38d744cc.png)

Reported in 623816-f 

/hat tip @SiobhyB, @fabianapsimoes, @peterbutler for the original report

**Comment by SiobhyB** [comment]
Closing as I can't replicate any more.
