### ISSUE TITLE
Showcase: Add a "close" button to the banner ad and upgrade notification bar

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#23944]
Currently the banner ad and upgrade notification bar take up quite a bit of prime real estate in the Showcase. It would be great to offer the user the ability to close them, removing them from their view of the Showcase forever (or at least until the cookie is cleared).

Maybe something like this?

![screen shot 2018-04-05 at 2 47 57 pm](https://user-images.githubusercontent.com/617986/38393663-5e465dd2-38e0-11e8-9d7d-4b33c87a37f0.png)

This would evidently require changing the upgrade notification right-chevron icon to the "X". The bar would still be clickable, but the "X" would now be a new clickable element.

As for the banner ad, maybe we only show the "X" on hover?

**Comment by Lobsterovich** [comment]
Zoid
