### ISSUE TITLE
Question: Blog Posts Page Slow/Unusable in Calypso

### ISSUE THREAD

**Issue by drwpcom** [Automattic/wp-calypso#23967]
#### Steps to reproduce
1. Starting at URL:http://wordpress.com/posts/my/FeedIT.cz
2. Page tries to load all posts on site in Posts List initially instead of 25, and is very slow or hangs.

#### What I expected
Perhaps pagination needed for a certain amount of posts? Or posts loaded upon scroll? Or...

#### What happened instead
The list tries to load/show all posts on the site. This is problematic with large sites. This error was reported by the site owner. I couldn't replicate it exactly but I tested on a site with >1600 posts and the page became unresponsive in several tests.

1040669-zen

#### Browser / OS version
Windows 10 Pro 64 bit, latest Chrome on both computers (Chrome 64.0.3282.186 at current, but issue goes months back)

**Comment by designsimply** [comment]
Thank you for the report! I tested viewing My Sites > Blog Posts with "Me" selected for my test WordPress.com site and my posts load quickly. I see that new posts are not loaded until I scroll to the end of the page which means they posts are loaded using "infinite scroll."

I noticed you are using capital letters in the end of the starting URL "FeedIT.cz" and when I do that I am redirected from http://wordpress.com/posts/my/FeedIT.cz to http://wordpress.com/posts/my 

However, when I use lowercase letters for the domain in the starting URL, I see the Blog Posts page load as expected: https://wordpress.com/posts/my/feedit.cz

Do you see the same behavior with regard to the redirect?

**Comment by damiannep** [comment]
I asked the user about this and his response is below (edited for spelling/grammar):

> I am opening lower case URL (like https://wordpress.com/post/feedit.cz/62737 - to open it with capital letters, it would have to be typed as Wordpress software itself opens lowercase. And i think "FeedIT.cz" is used only in "Site Title" (mapped domain is "feedit.cz")
> 
> https://wordpress.com/posts/my/feedit.cz exhibits bug we talk about
> 
> https://wordpress.com/posts/my/FeedIT.cz redirects to https://wordpress.com/posts/my which is different list of posts, but it also has only few items in left menu (as it exhibits "Switch Site" and i 'm not at feedit.cz
> 
> I have to point out that the bug we talk about is not present only at FeedIT.cz, it's also at rychlofky (https://wordpress.com/posts/my/rychlofky.cz) - it manifest itself only at site with a large number of posts (rychlofky has over 5000) - I do not think it has anything to do with capital letters (and yes, i use multiple sites with one account)

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
