### ISSUE TITLE
Domain Management: add domain mapping DNS error messaging

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2397]
Steps to reproduce:

1. Go to https://wordpress.com/domains/add and select any site
1. Add domain mapping for a domain that was purchased elsewhere with the name servers not yet pointed to ns1.wordpress.com, ns2.wordpress.com, or ns3.wordpress.com
1. Complete the purchase
1. Go to https://wordpress.com/domains/manage
1. Click on the domain mapping
1. Look for any kind of indicator noting how to make the mapped domain work

<strong>Result:</strong> there are no help messages or indicators pointing out that the name servers must be mapped to WordPress.com in order for a mapped domain to work—the domain will not work until the DNS at the registrar where the domain is being managed is updated and has time to propagate, but if you are not familiar with how domains work then it's difficult to figure that out.

![screen shot 2016-01-13 at 16 29 47](https://cloud.githubusercontent.com/assets/1119271/12308370/e8cacab4-ba12-11e5-83dc-6d95183af015.png)

Comment from @breezyskies 

> Suggested copy: 
> 
> <img width="633" alt="screen shot 2015-07-07 at 3 46 55 pm" src="https://cloud.githubusercontent.com/assets/3011211/8559233/81f7638a-24bf-11e5-9b3e-e31c0ad8b31b.png">

Comment from @umurkontaci 

> Do we have an endpoint that shows whether the domain is pointing to our NSes?

**Comment by designsimply** [comment]
@umurkontaci I don't think there is an endpoint that shows whether the domain is pointing to our NS. You can find a list of endpoints by entering `/help` on the console at https://developer.wordpress.com/docs/api/console/ Note: you may need to be sandboxed to see undocumented endpoints. There are currently 170 documented.

**Comment by klimeryk** [comment]
Fixed by #3329.
