### ISSUE TITLE
Inline Help: topics in international forums are truncated and not as useful as a user-chosen subject

### ISSUE THREAD

**Issue by jmdodd** [Automattic/wp-calypso#23981]
#### Steps to reproduce
1. Set your language to French at https://wordpress.com/me/account
2. Click on the blue (?) icon in the lower right-hand corner and click on "Contactez-nous?"
3. Add some topic content (mark as "testing" so that moderators understand that this is a test).
4. Click on "Poser des questions sur les forums" to send the request for help to the forums.
5. Visit the link to your request for help at "Votre message a été envoyé à nos forums de la communauté"; note that the topic title is the same as the topic content, and does not provide good context to the moderators in the forum view (i.e. when listing many topics together).

#### What I expected
The international forums previously had a form field for the subject which was used in the forum as the topic title.

#### What happened instead
There is no longer a subject or title field, which results in the post being sent to the forum with a truncated version of the request for help as the title. Because most requests begin with a greeting and introduction, this makes moderating the forums more difficult because users are no longer self-selecting their main idea as the post title. See:
https://fr.forums.wordpress.com/topic-tag/wpcomhelp/

#### Browser / OS version
Chrome 65.0 / Mac OS 10.13

#### Screenshot / Video
![screen shot 2018-04-07 at 10 00 22 pm](https://user-images.githubusercontent.com/235010/38472248-3b01e16c-3b4b-11e8-8f10-e44785cdfe21.png)

#### Context / Source
#painpoint for forum volunteer moderators via #user-report

**Comment by KokkieH** [comment]
This is not restricted to the i18n forums, but I've seen it on the English forums as well, and confirmed with a test account set to English that the form does not include a topic field. Using the i18n forums is better for testing, though, as English tickets for free users are not always routed to the forums, so you're not guaranteed to see the forums contact form with an account set to English.

This is how the form used to look for users being routed to the forums:

<img width="729" alt="27994167-683613c0-64b8-11e7-8b9b-a8e55fd22ccb" src="https://user-images.githubusercontent.com/11873759/38480221-8113c5c0-3bc4-11e8-861d-01af7e55519d.png">

**Comment by ramonjd** [comment]
Hi everyone!

Is this still an issue? Since bf8fdc52b708f1ea037deca58516d27c98b2905d there's a link to the forums, and no form.

<img width="335" alt="screen shot 2018-05-23 at 4 52 17 pm" src="https://user-images.githubusercontent.com/6458278/40408222-2871cbde-5eaa-11e8-9b7d-c64ecfa3e96c.png">

It's so new that the translations have only [just been added](https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bterm%5D=e+thousands+of+WordPress.com+membe&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). :)

The only issue I see is that the link is hardcoded to `en.forums.wordpress.com` [here](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/inline-help/inline-help-forum-view.jsx#L16).

I can look at localizing this link if there are no objections.

**Comment by KokkieH** [comment]
@ramonjd I was not aware of that change, and looks like @spen was not aware of this issue when working on that. I've cross-linked now.

If the form is now replaced with a direct link to the forums for free users who are also not being redirected to third-party support that would resolve this issue, yes. It would be great if you can localize the link as well based on the user's language settings.

**Comment by ramonjd** [comment]
Thanks @KokkieH 

I'll cc you when I get a PR up for the links. 👍

**Comment by spen** [comment]
Hi! 
Just for posterity, the PR referenced above (#24683) ended up being  reverted and replaced with #24771. 
This does solve the issue for folks who are accessing help via inline help but there should be no change for those who are getting to the contact form via `help/contact`  - they'll still see a form like so:
![Uploading Screen Shot 2018-05-23 at 13.03.30.png…]()

A PR for localizing the support link would be much appreciated! 
I've noticed that there are a whole bunch of references to `en.forums.wordpress.com` throughout Calypso - I wonder how much of an issue that is.

**Comment by ramonjd** [comment]
> I wonder how much of an issue that is.

It's a good point. We're deep linking to things like `en.forums.wordpress.com/forum/themes`, which doesn't have equivalents across all sites. There's not much we can do there, but #25031 has done a little good by replacing `{any_wp_slug}.forums.wordpress.com` with `{valid_bb_slug}.forums.wordpress.com`.

As much as we can we're trying to keep the UX in the user's chosen language, but, yeah, often it's impractical.

**Comment by ramonjd** [comment]
Closing stale issue for now.
