### ISSUE TITLE
Activity log: draft post events linking to reader

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#23983]
Draft titles from activity log bring you to the reader. I expected to end up in the editor instead.

#### Steps to reproduce
1. Have Jetpack connected site with Activity Log
2. Create a new draft post
3. Open activity log and see the event:
    ![image](https://user-images.githubusercontent.com/87168/38487583-5c799e0e-3be9-11e8-93e8-566e8dc8bc74.png)
4. Pressing that title brings you to the reader
    ![image](https://user-images.githubusercontent.com/87168/38487596-6c239f94-3be9-11e8-83ee-73d15b9a9d8d.png)

/cc @beaulebens

**Comment by roccotripaldi** [comment]
If the post is a draft, let's not link it at all.

**Comment by gititon** [comment]
Deployed fix.
