### ISSUE TITLE
Posts: list of posts doesn't show post format

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#240]
Currently the list of posts doesn't distinguish post formats, and it's quite hard to read:

We should display the post format info somewhere. A very quick win could be just an icon on the right here:

![image](https://cloud.githubusercontent.com/assets/7233112/11283486/fb602888-8ed2-11e5-92ab-cf7b19e1f9b2.png)

**Comment by lancewillett** [comment]
👍 Would love to see this improvement.

This is a big thing I miss from the wp-admin posts list. I use it as a visual reminder of which post format each post uses — aside, image, (standard is blank). I often quickly scan the list to find a certain type of post that way. In Calypso there's no distinction or visual cue to distinguish various post formats in the posts list.

**Comment by lancewillett** [comment]
![pasted image at 2017_02_08 22_15](https://cloud.githubusercontent.com/assets/66797/22758419/e0547140-ee0b-11e6-92b4-39db8438c965.png)

Via @mtias 

> Add icon there next to "post".

**Comment by lancewillett** [comment]
@mcsf Asked:

> How does this tie with what I believe to be a common acknowledgment that post formats were not successful in WordPress? Is a conceivable scenario to maintain the representation of the format (such as those missing icons) but have WordPress internally detect which format a post belongs to the best (i.e., no longer offer formats as an explicit option)? Or is it more valuable to ditch the concept and instead focus on improving the editing experience (and its front-end representation) to make formats obsolete? /cc @lancewillett @mtias 

Yes, work is already started in core to replace the concept. We can remove support in Calypso once that's live on WordPress.com.

I think this is important today for existing sites — not as much for new ones. People might have relied for years now on a format to fit their theme, many of which take advantage of formats, especially image, aside, quote. Twenty Thirteen is a good example, and P2 also which uses aside as the default.

An elegant way to start fading out the support is simply not to show anything (no icon) if the format isn't set, "Standard". That way new authors won't be bothered or start using it unnecessarily. Yet that allows previous users to see a visual clue of a format they've set previously.

That covers legacy cases nicely without introducing new people to a concept will be phased out. I would be open to removing the Editor sidebar post format menu for all new sites starting now. What do you think?

**Comment by lancewillett** [comment]
One suggestion for improvement and to accelerate phasing out this feature while hiding it for new users.

**Published posts**
Could we hide the editor sidebar Post Formats menu if the format isn't set? And only reveal it if the format was set before the author editing the post.

**New posts**
Don't show the editor sidebar menu at all.

<img width="338" alt="screen shot 2017-02-15 at 07 48 09" src="https://cloud.githubusercontent.com/assets/66797/22979369/55628764-f353-11e6-8c2d-0d5e08609970.png">

**Comment by mcsf** [comment]
I'd be willing to try this for new users. :)

**Comment by lancewillett** [comment]
Project update: no progress on this one yet. @mcsf Can you introduce a PR with Samus team to get something going?

An alternative idea — if we don't plan to fully support post formats in Calypso — is to match that in wp-admin for parity.
