### ISSUE TITLE
Stats: loading stats with empty localstorage fires many bogus queries

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#2400]
I noticed while watching the network traffic that if you load a stats page with empty localstorage, it first makes requests to all of the stats endpoints with a siteID of 0. E.g.,

https://public-api.wordpress.com/rest/v1.1/sites/0/stats/visits?http_envelope=1&unit=day&quantity=30&date=2016-01-13&stat_fields=views%2Cvisitors%2Clikes%2Ccomments%2Cpost_titles

![site/0/queries](https://cloudup.com/crJB1xQOefj+)

All of these requests are basically wasting time and bandwidth as they just get an error response (coded 404 but with a 200 status :smile:)... and they all get re-fetched once the sites data resolves. Can we do something so that these requests are not initiated until we have proper site data? Or can we use the site slug instead of the numeric ID, since that can be issued immediately?

## replicate this
Clear your localstorage, hit the stats page, and watch your network tab.

/cc @jonathansadowski

**Comment by jblz** [comment]
I'll grab it.

**Comment by timmyc** [comment]
One easy fix would be to do a check for siteId === 0 in the stats-list and return so no api request is made

**Comment by rralian** [comment]
> One easy fix would be to do a check for siteId === 0 in the stats-list and return so no api request is made

that'd be a quickfix, but it'd be nicer if we were better about detecting that we don't have site data yet... or just use the site-slug instead of a numeric ID since we should have that.

**Comment by timmyc** [comment]
> or just use the site-slug instead of a numeric ID since we should have that

I agree, and I have spent some time with the stats controller ( _scary_ ) trying to figure out how to do this a bit more gracefully and retain the pulsing stats components while things are loading.

The only potential drawback I could see to using the slug, is we are assuming then the user has access to the site/slug in the URL... edge case but worth noting.

**Comment by rralian** [comment]
I wouldn't say we're assuming that. We're doing an optimistic request that could possibly fail, we just need to handle the API failure gracefully. We already have a failure when requesting against siteID 0.
