### ISSUE TITLE
Store: Stats: Referrers: Data array not sent in order

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#24022]
Data from the `/stats/events-by-referrer` endpoint comes in an odd order - with the first element coming last in the array. I'm not sure what changed, but the chart is rendering oddly. It only appears with a `unit === 'day'`.

![screen shot 2018-04-10 at 2 41 30 pm](https://user-images.githubusercontent.com/1922453/38535067-e8a555e8-3cd5-11e8-8c17-9ee9116931aa.png)

![screen shot 2018-04-10 at 3 40 11 pm](https://user-images.githubusercontent.com/1922453/38535069-ecad1c0c-3cd5-11e8-85bc-af5228f76124.png)

I certainly can sort on the front end, but I don't think that should be necessary. Any ideas @justinshreve ?

**Comment by justinshreve** [comment]
@psealock Is this still a problem you are seeing? I made a few test requests using the developer API console, and the dates seem to be in order. If this is still occurring, can you provide me with the full request (blog ID and query parameters).

**Comment by psealock** [comment]
I'm seeing it on stores with a lot of data. Can you reproduce with this request?

```
https://public-api.wordpress.com/wpcom/v2/sites/113771570/stats/events-by-referrer?_envelope=1&unit=day&date=2018-04-23&quantity=30
```

**Comment by justinshreve** [comment]
Deployed the fix posted above.
