### ISSUE TITLE
Stats: redundant request?

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#2402]
I noticed while watching the network tab and hitting [a single-site day page](https://wordpress.com/stats/day/tritonp2.wordpress.com) that we are making what looks like a redundant request for visits. I see these two requests.

https://public-api.wordpress.com/rest/v1.1/sites/48006755/stats/visits?http_envelope=1&unit=day&quantity=30&date=2016-01-13&
stat_fields=views%2Cvisitors

https://public-api.wordpress.com/rest/v1.1/sites/48006755/stats/visits?http_envelope=1&unit=day&quantity=30&date=2016-01-13&
stat_fields=views%2Cvisitors%2Clikes%2Ccomments%2Cpost_titles

The only difference I see in these two requests is that the second requests asks for additional stats fields. Maybe this is a case of make a smaller query initially to show data more quickly. I'm not sure how it's used, but I figured I'd ask about it in case we have an unnecessary request.

![redundant request](https://cloudup.com/cz_f4x8aKCD+)

/cc @jonathansadowski

**Comment by jonathansadowski** [comment]
> Maybe this is a case of make a smaller query initially to show data more quickly.

That's exactly what we're doing. The first call returns significantly faster, especially for sites with a lot of likes.

**Comment by rralian** [comment]
Yeah, I suppose the first one is half a second faster which is pretty significant. Closing.
