### ISSUE TITLE
Plans: non-admins can accidentally access plan upgrades

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2405]
Raised by @breezyskies 

I came across a user capabilities issue with `/plans` where we are allowing non-admin users to upgrade a site. To reproduce:

1. Login to a non-super-admin account where you have: 1) a site where you are an admin, 2) a site where you are not an admin.
1. Navigate to `/plans` for a site you are an admin on. You should (correctly) see upgrade buttons.
1. Use the site picker to navigate to the site you are not an admin on while still on `/plans`. You should (incorrectly) see the upgrade buttons (non-admins shouldn't be able to upgrade a site). 
1. Refresh the page and you should see the upgrade buttons disappear. Based on the code, I think this is basically happening by accident, as we don't seem to be doing any capabilities checks here.

We should probably treat this the way other sections handle capability exclusions rather than just not showing the buttons (confusing). 

`/plans` viewed on a site where you are an admin (expected)

![screen shot 2016-01-13 at 20 23 43](https://cloud.githubusercontent.com/assets/1119271/12313250/ef62e8ae-ba33-11e5-8888-fdef62a5a62b.png)

`/plans` after switching to a site where you are an editor (unexpected)

![screen shot 2016-01-13 at 20 24 04](https://cloud.githubusercontent.com/assets/1119271/12313261/fe2b9dea-ba33-11e5-8ae6-e2b07085f3b1.png)

after refreshing (expected, I should not have purchase rights while logged in as an editor role)

![screen shot 2016-01-13 at 20 24 11](https://cloud.githubusercontent.com/assets/1119271/12313271/0e94e286-ba34-11e5-940a-035852f15d5b.png)

**Comment by fabianapsimoes** [comment]
I just tested this, and I no longer see the Upgrade buttons when switching to site where I'm not an admin. Closing.
