### ISSUE TITLE
Jetpack: Plan purchase from Calypso dashboard directs to WP Admin

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#24057]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans
2. Select a Jetpack-connected site.
3. Select a paid plan.
4. Complete checkout for the plan.
5. Wait for the thank you page to complete the plan setup and then select "Back to your site."

#### What I expected

Since I started in Calypso and had only been working in Calypso, I expected to be directed back to my site's dashboard in Calypso. (Aside from the masterbar and ? button, the only buttons on the thank you page are "Back to your site" and "Ask a question.")

#### What happened instead

I was directed out of Calypso, to my site's WP Admin, even though I hadn't come from there.

#### Browser / OS version

macOS / Chrome

#### Screenshot / Video

Thank you page with "Back to your site" button:

![screenshot 2018-04-11 10 04 18](https://user-images.githubusercontent.com/8658164/38607109-b761474a-3d6f-11e8-9fbd-769573a60c1d.png)

#### Context / Source
#manual-testing

**Comment by sirbrillig** [comment]
Just looking at this briefly, I think the cause of this redirect is the `redirect()` method in the `JetpackAuthorize` component: https://github.com/Automattic/wp-calypso/blob/master/client/jetpack-connect/authorize.js#L183

There are several conditions there that would result in returning to wp-admin, and presumably one of them is triggering incorrectly. My guess is that it's assuming the request is coming from a Jetpack site and so should go back to the Jetpack site.
