### ISSUE TITLE
DevDocs: Link to other resources

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#24059]
Not everything related to our design system lives in (or should live in) Calypso. We should link out to the other resources rather than duplicating content. This means linking to resources for:

- Logos
- Color
- Iconography
- Typefaces
- Voice and tone/Content

**Comment by drw158** [comment]
A simple idea for Color would be to add a new item in the sidebar, with an external icon. It would link to the handbook color page. I think that's a step in the right direction.

**Comment by scruffian** [comment]
This is done.
