### ISSUE TITLE
DevDocs: Add detail about the difference between UI components, Blocks and State selectors

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#24065]
The difference between these sections isn't clear, and isn't explained anywhere (I could see). We should add some information this and make it easy to find.

**Comment by stephanethomas** [comment]
I added more information about the different types of components [in the documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/components.md#glossary) but I agree that it should be more visible, and easier to find.

**Comment by stephanethomas** [comment]
Yes, and also where they should live (I didn't know that selectors should be located under `client/state/selectors` until very recently).

**Comment by drw158** [comment]
I like this terminology guide: https://github.com/viljamis/vue-design-system/wiki/terminology

Do you think it's possible to change the names completely? Regarding UI, I love the terms Token > Element > Pattern > Template.

I think using the word components is confusing because React has their definition, but it could be something very different to a designer. Component to me, basically means an "element".

**Comment by drw158** [comment]
This is the original formation and reasoning for the Block: p2-p4TIVU-47o

**Comment by drw158** [comment]
Further info is also in: https://github.com/Automattic/wp-calypso/blob/master/docs/components.md#glossary

Looks like there is a doc for each of the component types.

**Comment by stephanethomas** [comment]
Regarding state selectors, we already have the following documentation:

* https://github.com/Automattic/wp-calypso/tree/master/client/state/selectors
* https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#selectors

Isn't it enough? I'm not sure what @scruffian had in mind regarding this.

**Comment by scruffian** [comment]
> Do you think it's possible to change the names completely?

Yes, but a lot of work!

**Comment by scruffian** [comment]
I feel like there is a bigger issue here in that State Selectors are treated the same as UI Components and Blocks, but they are really something totally different. Maybe we could add a new section for them? I'll create a PR...

**Comment by drw158** [comment]
I think this is done
