### ISSUE TITLE
DevDocs: Suggest related components 

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#24068]
Shopify has a “related components” section, which is used for suggesting other components that you might want to use (https://polaris.shopify.com/components/overlays/popover#section-related-components)

We could do something similar for Calypso components that are

**Comment by drw158** [comment]
This would probably be manually written, not programmatic. It may be redundant if we do https://github.com/Automattic/wp-calypso/issues/24067

Even if we do the lineage, it would be nice to have manually written suggestions or tips for the most used components.

**Comment by scruffian** [comment]
I think there is value in both.

**Comment by drw158** [comment]
A related components section is now in the readme template, so all new components and updates to old components should include this section. I'll close this issue.
