### ISSUE TITLE
DevDocs: High level patterns, IA etc.

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#24069]
We have a lot of decision about the sidebar and the IA in general which are only documented internally. We should dig through these, consolidate them and move them into DevDocs.

**Comment by drw158** [comment]
Sort of related to our Glossary, which may as well be a doc about our high level patterns.

https://wpcalypso.wordpress.com/devdocs/docs/guide/glossary.md

**Comment by sixhours** [comment]
I see a couple ways this could go:

* We rename the Glossary to something that encompasses more than just definitions (maybe Design Patterns? With a section called Glossary?) and incorporate the additional info.
* We create a new page for high-level patterns and link to the Glossary from that.

Other thoughts on the structure? I'm leaning toward the first option.

**Comment by sixhours** [comment]
After looking further, I think splitting the sections up would be a better option; a glossary is a defined entity and more general information doesn't fit there. Plus it makes the page a lot longer if we try to combine them. 

I'll open a PR with a new page added to the guide to see what folks think.

**Comment by cathymcbride** [comment]
This looks addressed by the above. Closing.
