### ISSUE TITLE
ActionCard: Prevent button text breaking at smaller card widths

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#24063]
The button breaks at smaller screen widths: https://cloudup.com/cy_7Sshg26W

**Comment by andfinally** [comment]
Could you give some detail on how you're viewing it? I've tried every conceivable window width in Chrome devtools responsive view, and I can't reproduce the issue.

![image](https://user-images.githubusercontent.com/1647564/38697079-d7bcd0c6-3e88-11e8-82cb-1edef01760ec.png)

**Comment by scruffian** [comment]
@andfinally try Firefox :)

**Comment by andfinally** [comment]
Oh right, now I see it - for me it's when the viewport's between 1281 and 1460px wide and the Checklist component is floated to the right.

**Comment by drw158** [comment]
Seems like this would be true whenever we float buttons to the right with flexbox. Maybe add some css to icon buttons that prevents the icon dropping to a new line?

**Comment by drw158** [comment]
I'm also wondering if the button could just be a normal button with no icon in the example. It's a bit misleading and makes me think that this card is primarily used for external links.

**Comment by andfinally** [comment]
This issue happens above the 960 breakpoint when the width of the card is about 482px - I've tweaked the title to reflect that. I've hopefully addressed this in https://github.com/Automattic/wp-calypso/pull/24131.

**Comment by andfinally** [comment]
https://github.com/Automattic/wp-calypso/pull/24131 is now merged, so this can hopefully be closed.

**Comment by scruffian** [comment]
Thanks @andfinally 👏
