### ISSUE TITLE
DevDocs: Update /typography

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#24074]
We could update a few things to make /typography clearer:

- Provide required sass variables ($sans, $serif) for serif and sans fontstacks.
- Add info on the $code fontstack.
- Clarify the rules about when to use $serif vs. $sans.
- Link to the brandbook for other information
- Add information about the base style for regular UI text - $sans, 15px, $gray-dark, 400 weight.

**Comment by drw158** [comment]
Technically we did not do this in the PR explicitly

> Add information about the base style for regular UI text - $sans, 15px, $gray-dark, 400 weight

But the styles are in there in the code block example so I'll close this.

<img width="439" alt="screen shot 2018-04-17 at 7 56 06 pm" src="https://user-images.githubusercontent.com/618551/38905943-62e5d3d4-4279-11e8-9a95-cc9c003d93f7.png">
