### ISSUE TITLE
Store: Unable to set up Store

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#24084]
#### Steps to reproduce
Starting at URL: https://wordpress.com/store/jancavanblog.wordpress.com

Site URL: jan.blog (mapped to jancavanblog.wordpress.com)

#### What I expected
For me to be able to set up my Store.

#### What happened instead
I get an error message saying, "Some of your site settings couldn't be retrieved." I'm also not sure what this means exactly so it's not very helpful. I keep clicking on "Try again", but keep getting the same error message.

#### Browser / OS version
Chrome Version 65.0.3325.181 
Mac OS High Sierra 10.13.3

#### Screenshot / Video
![screenshot 2018-04-11 09 47 29](https://user-images.githubusercontent.com/4924246/38631128-ba1d8c98-3d6d-11e8-9576-22d0cf12fa27.png)

I also want to note that originally, jan.blog was in my site list, but after activating the WooCommerce plugin, this has disappeared. I'm only seeing its original domain, jancavanblog.wordpress.com:

![screenshot 2018-04-11 09 53 44](https://user-images.githubusercontent.com/4924246/38631344-5eab24dc-3d6e-11e8-8794-0f7a981f80f9.png)

**Comment by timmyc** [comment]
Hi @jancavan ! Did you manually install the WooCommerce plugin from the Plugins portion of your site?

**Comment by jancavan** [comment]
> Did you manually install the WooCommerce plugin from the Plugins portion of your site?

@timmyc Yes, I installed it from `/plugins` in Calypso.

> I also want to note that originally, jan.blog was in my site list, but after activating the WooCommerce plugin, this has disappeared. I'm only seeing its original domain, jancavanblog.wordpress.com

Re this, I went to `/wp-admin` to try to deactivate the plugin to see if this fixes it, but it didn't.

**Comment by timmyc** [comment]
Answered my own question 😆 - so it does look like you installed WooCommerce manually - I think we should still be able to install the other required plugins so not certain why this is failing. Might be related to #23899

**Comment by jancavan** [comment]
I think it's related to that issue @timmyc. What other plugins should I be installing?

**Comment by timmyc** [comment]
The issue was due to Jetpack connection being somehow corrupted during the AT process. All fixed up in at-happiness.

**Comment by jancavan** [comment]
Thank you @timmyc!
