### ISSUE TITLE
Billing History: Clean up Jetpack Plans display

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#24092]
Purchase a Jetpack plan, and then view the receipt via Me > Manage Purchases > Billing History.

You'll see something like this:

![billing_history_ _wordpress_com](https://user-images.githubusercontent.com/108942/38649933-65691534-3db6-11e8-9e6d-4624e710a308.png)

- [ ] Icon should be a Jetpack logo
- [ ] Should be listed as "Jetpack" at the top (not WordPress.com)
- [ ] Plan/purchase detail should be "Jetpack Premium" not just "Premium" (this problem also exists on the billing history listing page)
- [ ] Button at the bottom should say "Contact Jetpack Support", but can still go to the current location, because they will get support through there.

**Comment by ockham** [comment]
Did a bit of digging. Most of these data come from the `state.billingTransactions.items.past` Redux subtree, which in turn reflects the `/me/billing-history` API endpoint. So it's possible that most of the changes we need to do will be on the API side.

**Comment by ockham** [comment]
This seems rather deeply engrained into WP.com's purchases management (so maybe tricky to change). However, I noticed that the endpoint returns an `items` subtree that contains the actual plan's slug. Maybe we can work with that.

**Comment by ockham** [comment]
Hmm, ideally we should tackle it at `service` field level.

WIP here: D12853-code

**Comment by ockham** [comment]
Patch to include 'Jetpack' in the purchase name at D12878-code.

**Comment by ockham** [comment]
Fixed per a database change, D12878-code, and #24733. For more information, see p1YhhO-Ka-p2 and D12878-code.
