### ISSUE TITLE
Sharing: Clarify wording of oAuth post-connection dialog

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#24094]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/{site}
2. Connect to a new Sharing service (Twitter, Facebook, etc)
3. The dialog that comes up reads:

![screen-shot-2018-03-26-at-02-09-03](https://user-images.githubusercontent.com/52152/38658146-ae8a91a8-3dd8-11e8-9114-ae6da3154eb7.png)

This is somewhat confusing in that it might sound like all existing or old posts will be shared, and doesn't offer a clear next step.

We should reword it to be a bit more straightforward/friendly (we can drop constructions like "Note that...") and to make it clear what will happen if the user goes ahead with the connection, and what they still need to do.

**Comment by codebykat** [comment]
I'm thinking it should be something like this:

"Is this the account you'd like to connect? By default, all new posts will be automatically shared to this account. You can change this on a post-by-post basis in the editor sidebar."

**Comment by codebykat** [comment]
"Options for each new post will appear in the editor sidebar." ?

**Comment by andfinally** [comment]
I think you're right, the wording could do with a tweak. How about

> Is this the account you'd like to connect? All your new posts will be automatically shared to this account. You'll be able to change this option in the editor sidebar when you're writing a post.

There might be a bit of ambiguity about which posts we're talking about - it could be Facebook posts - so maybe it  ought to be "all your new WordPress.com posts".

**Comment by andfinally** [comment]
That would do it!

**Comment by torres126** [comment]
The original wording is still being used but shouldn't be too tricky to update.
