### ISSUE TITLE
Editor: Social media previews are hidden in a weird place, should be more prominent

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#24098]
#### Steps to reproduce
When writing a new post, the social media preview pane is in the screen size dropdown, which makes zero sense to me.

![screen shot 2018-04-11 at 23 08 54](https://user-images.githubusercontent.com/52152/38659216-54e27cce-3ddd-11e8-9234-c48b4c67683c.png)

I can't believe anyone would notice this here or think to look for it. Especially if this is a feature we want people to know about so they might consider upgrading... can we pull it out of this dropdown and make it a top-level button or icon or something? Could we even make it a separate preview pane that pops open from a link/icon in the Sharing sidebar?

**Comment by designsimply** [comment]
> Could we even make it a separate preview pane that pops open from a link/icon in the Sharing sidebar?

+1, this is where I would expect to find social media previews.
