### ISSUE TITLE
Plans: Handle VaultPress purchases properly in Billing History

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#24091]
When a customer has a VaultPress plan, their payments are recorded and visible in WP.com. Those purchases show up without enough information to know what's going on:

![screen_shot_2018-04-05_at_11_32_29_am](https://user-images.githubusercontent.com/108942/38649756-a18a3ce2-3db5-11e8-807e-43720572fd56.png)

"VaultPress Vault Press" makes no sense at all. It should be at least just "VaultPress", preferably a sensical descriptor of the actual specific VaultPress plan/charge.

We should also show the URL associated with the site being charged there (as seen blurred out in the 2 "Personal" entries).

**Comment by johnHackworth** [comment]
@beaulebens hmmm... ok, how could I get a VaultPress plan to work on this? You can't purchase them any longer separately. Could I get access to a wpcom account with a vaultpress plan or could anyone set me up with one in my own account? 

@samhotchkiss  ^

**Comment by samhotchkiss** [comment]
@johnHackworth -- Brian can get you set up, just drop him a ping

**Comment by johnHackworth** [comment]
> We should also show the URL associated with the site being charged there (as seen blurred out in the 2 "Personal" entries).

this is not an easy thing to add since by default the Vaultpress plans don't have an associated site. I guess that we could get which sites have activated the keys and add them there, but that probably means a lot of changes to get that piece of info, since it's not currently stored anywhere near the billing info
