### ISSUE TITLE
Add extra validation for email address when a domain is registered

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#24114]
This came up in 2718687-hc , a customer purchases a domain on WordPress.com and when has to enter the contact information data, adds the email as `www.myemail@gmail.com`, hence not receiving the verification email because the extra `www.` . 

Would it be possible to add additional validation here to avoid this in the future?

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/domains/add
2. Go through the registration process
3. On https://wordpress.com/checkout/$your-domain-name , add an email address starting with `www.`

<img width="598" alt="screen shot 2018-04-12 at 20 51 07" src="https://user-images.githubusercontent.com/3812076/38681600-452e2c7c-3e93-11e8-972a-76ec4406e8f1.png">

We don't see this often so I added` [Pri] Low`.

**Comment by aidvu** [comment]
That e-mail is valid. What we could do, although that would mean we'd have to add non-blocking validation rules that can be bypassed to the validators. Hmm... @Automattic/cobalt

**Comment by klimeryk** [comment]
I've checked and we have at least 412 users that used a `www.*` email in the past.
Some seem legit, some have changed it to one without the `www.` prefix. I'd guess the ones with a legit `www.*` ones are clients that had their site set up by someone else?

Anyway, it _is_ a valid email, but I also get how someone could get confused and input that (for whatever reason). But less than a year ago, I've merged https://github.com/Automattic/wp-calypso/pull/16166. It prevents users with unverified emails to purchase new domains (though, it does not prevent doing so if they're registering it _and_ signing up for WPCOM). Looks like most of these 412 users are at least a year old.

I'd vote to close this, but keep tracking how often this happens (tagging chats, for example?). If it happens frequent enough, we can look into solving this.

An alternative that would be quick to implement: most of these seem to be GMail. And with GMail, `www.example@gmail.com` and `wwwexample@gmail.com` are the same accounts. So we could fail `www.example@gmail.com`, but in the validation message say that if they're _sure_ that is the correct email, they can bypass it by putting `wwwexample@gmail.com`.

**Comment by iamgabrielma** [comment]
> That e-mail is valid.
TIL. Any insight and why the user was not receiving the verification email until has changed it to the non-www. variation? Or maybe has just been a coincidence and delay from the registrar when sending the verification.

**Comment by klimeryk** [comment]
If understand the case correctly they changed it from www.example@gmail.com to example@gmail.com, right? If that's the case then those two are separate emails. The `www.` one probably did not exist, which the non-www one did (and was probably what the user wanted to use).

But as mentioned above, both emails are valid and indeed we have some users that are using emails starting with `www.*`, so I'd not block them. And showing any info/nudge that it might not be the correct email doesn't seem like a high priority given the relatively small number of users that have this email among our userbase.
