### ISSUE TITLE
Jetpack Connection Flow: missing option to create account.

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#24127]
Starting from a site where you have activated Jetpack, but not connected it to WordPress.com. Your admin account's email address should match an existing WordPress.com account.

> It seems impossible to add the site to a new wordpress account through the Jetpack set up process.
> 
> I reach this screen:
> 
> ![image](https://user-images.githubusercontent.com/5859901/38670107-cfaaf442-3e3f-11e8-8b41-2e3a6432c6d2.png)
> 
> Adding the site to the right hand column and pressing continue returns me to this screen (email address removed):
> 
> ![image](https://user-images.githubusercontent.com/5859901/38670289-43a1383e-3e40-11e8-9d68-3528078d7f1a.png)
> 
> Clicking sign-up in the top right of that screen returns me to the first screen.
> 
> The options appear to be:
> 
> 1. Create a blog on wordpress.com, or
> 2. Try to sign up to wordpress.com without creating a blog but be forced to create a blog anyway.
> 
> This is a bad user experience.

Reported in https://github.com/Automattic/jetpack/issues/8994#issuecomment-380747630

It would be nice to offer the option to create a new account below the form.

**Comment by jeherve** [comment]
Still an issue.

**Comment by tyxla** [comment]
@jeherve could you please confirm that you've retested this today?

I've just ran a quick test and it seems that we have 2 links on that page that users can use to navigate to the account creation page:

**The first link in the footer below the form**
![](https://cldup.com/iQuxQdkRkc.png)

**The signup button in the toolbar**
![](https://cldup.com/VE2Q6nxg60.png)

So I think we should be safe to close this, unless I'm missing something?

**Comment by jeherve** [comment]
I did not retest this, so let's close! 👍
