### ISSUE TITLE
DevDocs: consider adding more docs to sidebar.

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#24132]
There are a lot of sections listed on the search page which aren’t accessible from the sidebar, so I think a lot of people miss them.

One that comes to mind is the A11y readme.

**Comment by drw158** [comment]
@sixhours can we investigate whether or not a sidebar item with an external link is possible?

**Comment by sixhours** [comment]
@drw158 Pretty sure it's possible, I'll test and either make a PR or let you know!

**Comment by sixhours** [comment]
Colors and Accessibility have been added! Are there others we should consider? My thinking is if the sidebar gets too long, it will be cluttered, but I'm not sure if there's more high-level info we want to put upfront.

**Comment by drw158** [comment]
I can't think of anymore to add at the moment. I think it looks good!
