### ISSUE TITLE
Reduxify: domains/nameservers

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#24139]
Store used in domain management UI for showing and changing domain nameservers. Stores a list of nameservers and flags about the state of request, keyed by domain name:
```js
{
  'example.com': {
    isFetching: false,
    hasLoadedFromServer: true,
    list: [ 'ns1.wordpress.com', 'ns2.wordpress.com', 'ns3.wordpress.com' ],
  }
  'example.org': {
    ...
  }
}
```

There are two actions that send a REST request and update the list with the response: `fetchNameservers` and `updateNameservers`.

There is no interaction with other stores and the migration should be straighforward. The `isFetching` and `hasLoadedFromServer` favor could be maybe removed and replaced with a `null` value of `list` and/or local state of the React components that issue the requests.

**Comment by jsnajdr** [comment]
I've had a WIP branch for this task for several months now. Going to revive and finish it.

**Comment by tyxla** [comment]
Oh, sorry for stepping on it. I have a working branch for it, too

**Comment by tyxla** [comment]
Opened a PR with it: https://github.com/Automattic/wp-calypso/pull/47272
