### ISSUE TITLE
Reduxify: lib/importer

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#24148]
Uses ImmutableJS, written in a very Redux-friendly style already. @dmsnell offered help with converting.

Also used in Happychat middleware to show a Happychat notice when the user starts an import. That code is currently broken, because the middleware listens for a Redux action and it’s actually Flux. (cc @nosolosw)

**Comment by bisko** [comment]
Related PR: #23930

**Comment by nosolosw** [comment]
For the Happychat part: @mattwondra would know best (https://github.com/Automattic/wp-calypso/commit/97aa165e73e5cc649de39f641b66483d89c1da88), but I think that we could just remove the `IMPORTS_IMPORT_START` action as it's not ever used.

**Comment by mattwondra** [comment]
Yes, it can be removed from the Happychat code. I believe this was put in place during a sprint where we listed a bunch of actions we thought Happychat should know about, and then we'd fill them in — but I guess we never removed that dead code.

**Comment by talldan** [comment]
Hi - I have a PR open for this - #24490 

This github issue was pointed out to me after I'd already completed the bulk of the changes. Let me know if you have any comments on the PR.

**Comment by tyxla** [comment]
@jsnajdr has been working on this recently in #48213, on top of some prior work in #27396

**Comment by tyxla** [comment]
Importers have been reduxified by the aforementioned PRs. Closing.
