### ISSUE TITLE
Reduxify: lib/preferences

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#24141]
The `preferences` module was already reduxified some time ago, but the duplicate Flux implementation is still there and used at only two places:
- to store list of ignored words for the editor proofreading plugin (After The Deadline). There is no React in that TinyMCE plugin, so the connection to Redux will need to be implemented in a slightly unusual way, without things like `connect` or `QueryPreferences`.
- to read the `editor-mode` preference when saving

The existing editor code seems a bit buggy. For example:
- what happens when editor mode is switched while save is in progress? It seems that the content might get corrupted.
- saving the proofreading ignore list seems to not work: the REST API request returns error.

This issue could be solved while working on the `post-edit-store` -- the tasks are closely related.

**Comment by flootr** [comment]
@jsnajdr is this one still valid? I couldn't locate the proofreading plugin you mentioned.

> to read the editor-mode preference when saving

Looking at [save-edited.js](https://github.com/Automattic/wp-calypso/blob/master/client/state/posts/actions/save-edited.js#L104) it seems like this is now derived from the redux state.

**Comment by jsnajdr** [comment]
@flootr Seems this was already done earlier this year by @tyxla in #39672 :tada:

Marin also removed all the TinyMCE plugins recently, including the AtD proofreading one. And `save-edited.js`, being part of the Classic Editor state, is likely on his todo list, too 🙂
