### ISSUE TITLE
Reduxify: users store

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#24150]
Manages a CRUD list of site users for each site. Used for:
- selecting author for an edited post
- domain transfers
- managing the list of site users (People)
- author mapping in importer
- sharing connections mgmt — figuring out connection owner

**Comment by tyxla** [comment]
I'm assigning myself here to give a hand to @flootr.

FWIW we've been using `react-query` for those and already removed some of those instances.
