### ISSUE TITLE
Rewind Appears to be Stalled on User Account

### ISSUE THREAD

**Issue by TassyWassy** [Automattic/wp-calypso#24155]
#### Steps to reproduce

User site was getting a 500 error on her site and she attempted to rewind her site back to the 10th of the month. The user has been waiting over 10 hours for the rewind to be complete. The process bar is at about 75%. The user does have almost 200 published post and about 90 drafts. User has 14 pages and media in the hundreds. Based on that the rewind would take a while to complete but seems to be taking too long as this point.

#### What I expected
Expected that rewind would be completed in a couple of hours

#### What happened instead
User has been waiting over ten hours to have rewind complete

#### Screenshot / Video
http://prntscr.com/j4sfe6

#### Context / Source
User: noctiluna
Site: https://noctiluna.com
HC: 2761196-hc
Ticket: 1087769-zen

**Comment by rachelmcr** [comment]
Closing this issue and moving it to an internal report. Thanks!
