### ISSUE TITLE
Purchases: not able to access Billing History after deleting all sites.

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#2415]
Originally reported by @lettergrade (pbg9X-8Tk-p2).

Right now, if a user deletes all their sites, the Billing History section is no longer accessible via navigation. It's important users continue to have access to that section since they might have completed purchases prior to deleting their sites. 

When a user has no sites, we redirect `/purchases` to the No Sites screen. That means the Header Cake from which users can access Billing History isn't visible. It's still possible though to see `/me/billing` using this URL.

**Comment by mikeshelton1503** [comment]
We should keep the sectionNav visible. When "Purchases" is selected we can still show Drake as we do currently:

![image](https://cloud.githubusercontent.com/assets/12596797/12326078/8c19c84e-ba9c-11e5-8bb1-be0f13797f17.png)

**Comment by jeremeylduvall** [comment]
This should be fixed (confirmed through a few testing accounts with no sites).
