### ISSUE TITLE
Reduxify: ads

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#24163]
**summary**
3 flux stores. [tos-store](https://github.com/Automattic/wp-calypso/blob/master/client/lib/ads/tos-store.js), [settings-store](https://github.com/Automattic/wp-calypso/blob/master/client/lib/ads/settings-store.js), [earnings-store](https://github.com/Automattic/wp-calypso/blob/master/client/lib/ads/earnings-store.js). Also has 2 utils that are basically selectors.  All 3 have barely any use, and appear in few places. Most of this has been reduxified to `state/wordads`

- tos-store: not in use anywhere
- earnings-store: use in one file. only gets fetched and observed.
- settings-store: this one hasn't been reduxified but only powers a single ui

| task size | files      |
| ----------- | ---------- |
| medium      | 11 |

**Comment by rclations** [comment]
slated to be fixed as a part of WordAds settings + stats improvements
pMyNb-4ch-p2

**Comment by rclations** [comment]
closing in favor of #18222
