### ISSUE TITLE
Reduxify: userSettings

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#24162]
**summary**
event emitter located in `client/lib/user-settings/index.js`. Already been reduxified and lives in `state/user-settings` + data-layer. Mainly used in controllers that then pass it to the main view for a url.  Those then either don't use it, or use it sparingly. Overall a smallish task as far as reduxifying goes

| task size | files      |
| ----------- | ---------- |
| small/medium       | 11 + tests |

**Comment by flootr** [comment]
In order to remove `lib/user-settings` we have to uncouple a few things. First step is to create a `withFormBase` hoc and replace the `formBase` mixin with it. https://github.com/Automattic/wp-calypso/pull/48366 takes care of that.

**Comment by flootr** [comment]
Removing `userSettings` for a bunch of route components in #48443 where it isn't used.

**Comment by flootr** [comment]
Reduxify the `withFormBase` HOC as well as `<Profile />` in https://github.com/Automattic/wp-calypso/pull/48730
