### ISSUE TITLE
Editor: Authors can delete images from the media library using the media modal

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#2416]
Users with the Author role on a site should be able to upload images to but <em>not</em> delete images from a site's media library. However, using the media modal in the editor an author can delete any images (their own and those uploaded by other users):

<img width="1113" alt="screen shot 2016-01-14 at 11 49 29 am" src="https://cloud.githubusercontent.com/assets/8658164/12323638/0afb6592-bab5-11e5-9471-0243db228291.png">

In the WP Admin editor, the options to edit or delete images in the media modal are hidden from authors. They should also be hidden from authors in the Calypso editor.

**Comment by aduth** [comment]
The required capabilities for managing media is intentionally different than wp-admin in the REST API for the purposes of enabling non-administrators to make use of the available media on the site. However, deleting seems a bit more privileged, so perhaps we should escalate the required permissions. Currently, the endpoint [checks against the `upload_files` capability](https://github.com/Automattic/jetpack/blob/7c31538591c095335699e13c6debaad68a699812/json-endpoints/class.wpcom-json-api-delete-media-v1-1-endpoint.php#L10).

The Roles and Capabilities document describes an [`edit_files` capability](https://codex.wordpress.org/Roles_and_Capabilities#edit_files) but notes that it is no longer used. Perhaps `delete_posts` is most desirable?
