### ISSUE TITLE
Signup: "Select" button too small for some translations

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#2417]
Longer translations of `Select` button used for domain registration during signup ([code](https://github.com/Automattic/wp-calypso/blob/a9df560532e2ca19c29570df39410ac70f744059/client/signup/steps/domains/index.jsx#L153)) get truncated.

Truncation, intentional abbreviation, or using a word with a different meaning (e.g. "OK") are all suboptimal from the non-EN user perspective. 

Possible solutions: make the button intentionally wider, make the button width responsive so it fits the translation, use alternative designs.

This issue is present in desktop, tablet, and mobile resolutions.

Compare EN ("Select"):
![en_desktop_2_domain_options_screenshot1449463034205](https://cloud.githubusercontent.com/assets/7637835/12324849/11fbcb64-bac6-11e5-8bfe-84e6af0c1520.png)

And pt_BR ("Selecionar"):
![br_desktop_2_domain_options_screenshot1449462724330](https://cloud.githubusercontent.com/assets/7637835/12324856/1d66d87c-bac6-11e5-9015-1de2fd822725.png)

**Comment by klimeryk** [comment]
Pinging @breezyskies - I've checked the above, it seems the part to the left of the button uses `flex` and I haven't yet read up properly on that. Don't know if it even matters in this case XD But I couldn't make the button behave properly for long strings using my limited CSS knowledge :/ Save us, Oh CSS Goddess! :bow:
