### ISSUE TITLE
Reduxify: notifications-settings-store

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#24179]
**summary**
~~I wasn't able to find any store with this name 😖 😕 🙃~~
`lib/notification-settings-store`:

LOC: ~100
Usage: only 3 files use the getters/actions AFAICT. should be easy to switch over those bits.
Task Size: medium

**Comment by spen** [comment]
Related: https://github.com/Automattic/wp-calypso/pull/28653

**Comment by jsnajdr** [comment]
Fixed in #28653 by @spen, closing 🙂
