### ISSUE TITLE
Reduxify: email-forwarding

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#24176]
**summary**
[email-forwarding](https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/email-forwarding/store.js) is a store in the lib/upgrades that utilizes an interesting helper called `createReducerStore`.  It is a flux event emitter that was written in a reducer style.  I think that should make it significantly easier and natural to convert.

| task size | files      |
| ----------- | ---------- |
| small      | 5 |

**Comment by flootr** [comment]
This one seems to be done already via #31003. I couldn't find a store left and the link above is not valid anymore.
