### ISSUE TITLE
Reduxify: plugins

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#24180]
**summary**
Three associated flux stores.

[plugins-list-store](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plugins/wporg-data/list-store.js):
responsible for storing .org data on plugins (same for each user, independent of site).
only used by the plugins browser. never shows up anywhere else. medium complexity. has interesting looking fetch logic strewn about it.  about 250 lines total between the store/actions. 4 involved files.

[store](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plugins/store.js):
monster. 600 lines of actions and then 400 of store.js. string literals used for action types. thunk style workflow for network requests. You can also interestingly find reimplementations of built-in es5 functionality like `Promise.resolve` and `Promise.reject` :).

[log-store](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plugins/log-store.js):
stores things recently done to plugins. powers some buttons and notifications, etc.
medium complexity and ~180 lines

| task-size | files      | LOC   |
| ----------- | ---------- | ---------- |
| scary      | low tens | 1500 |

Note: looks like a significant amount of the work was already done here: https://github.com/Automattic/wp-calypso/issues/8213. Parts of the UI depend on the redux state and parts depend on flux. ~29 files depend on the redux and (I think the same?) 29 also depend on the flux one. Need to better figure out exactly how the responsibilities overlap

**Comment by tyxla** [comment]
I'm starting work on this.

**Comment by tyxla** [comment]
Noting that there's prior art to reduxify plugins in #8213, kudos to @ryelle for all the great progress there already 👏

**Comment by tyxla** [comment]
#47711 reduxifies the plugin activation and deactivation actions.

**Comment by tyxla** [comment]
#47742 reduxifies the plugin update and autoupdate actions.

**Comment by tyxla** [comment]
#47860 reduxifies the plugin installation and removal actions.

**Comment by tyxla** [comment]
#47902 does some old cleanup and #47908 reduxifies the `removePluginUpdateInfo` action.

**Comment by tyxla** [comment]
https://github.com/Automattic/wp-calypso/pull/47911 removes an unnecessary flux action.

**Comment by tyxla** [comment]
https://github.com/Automattic/wp-calypso/pull/47915 reduxifies site plugin fetching.

**Comment by tyxla** [comment]
I've also opened #47920 as the first PR to start untangling the `PluginsLog` usages in favor of their Redux counterpart. This PR handles the `PluginActivateToggle`'s logic for determining whether the action is in progress.

**Comment by tyxla** [comment]
Similarly to the last PR, #47921 handles the`PluginAutoUpdateToggle`'s logic for determining whether the action is in progress.

**Comment by tyxla** [comment]
#47949 fixes a regression we introduced in #47860 (thanks @flootr for discovering it so quickly!).

**Comment by tyxla** [comment]
#47951 introduces and implements a couple of 2 new selectors that allow for more concrete checks as to whether a site plugin's status for one or more actions is the specified one.

**Comment by tyxla** [comment]
#47957, #47959 and #47960 reduxify the progress (AKA status) in other plugins components similar to #47951, #47964 does a cleanup to make untangling from the notices mixin easier, and #48000 reduxifies the mass removal of plugin notices.

**Comment by tyxla** [comment]
I've opened #48004 to help untangle any notices mixin usage from the `PluginsList` and `SinglePlugin` components, paving the way for converting the mixin to a component and refactoring `PluginsList` and `SinglePlugin` to `React.Component` instead of using `createReactClass`.

**Comment by tyxla** [comment]
#48053 reduxifies `PluginStore.getNotInstalledSites()`.

**Comment by tyxla** [comment]
#48104 fixes a bug we recently introduced with #47711.

**Comment by tyxla** [comment]
#48109 migrates the plugins list to use installed plugin status instead of flux's PluginsLog store.

#48110 is a minor enhancement to make the disconnect notice lead to the right place for managing the Jetpack connection.

#48113 reduxifies single plugin retrieval, while #48116 reduxifies the "is fetching" states.

**Comment by tyxla** [comment]
#48167 to refactor `PluginNotices` to an actual `React.Component`. And a quick fix for it: #48169

**Comment by tyxla** [comment]
#48170 removes all remaining `createReactClass` usages in plugins, making reduxification a bit easier.

**Comment by tyxla** [comment]
#48206 fully reduxifies and modernizes notices

**Comment by tyxla** [comment]
#48260 reduxifies the single plugin installation progress and together with #48206 removes the last usage of the `PluginsLog` store 🥳

**Comment by tyxla** [comment]
#48308 reduxifies `PluginsStore.getSitePlugin()` completely.

**Comment by tyxla** [comment]
#48353 removes the `log-store` flux store 🎉

**Comment by tyxla** [comment]
#48453 reduxifies `PluginsBrowserListElement`

**Comment by tyxla** [comment]
#48480 ports a `recentlyUpdated` flag from Flux to Redux, and we have the following PRs to decouple plugins from sites and prepare plugin sites for reduxification: #48481, #48482, #48483, #48484, #48485.

**Comment by tyxla** [comment]
In #48526 we'll now always be using constants for status actions.

**Comment by tyxla** [comment]
#48537 fixes a discrepancy between installed plugins and newly uploaded ones.

**Comment by tyxla** [comment]
#48538 adds missing plugin state initialization to status actions.

**Comment by tyxla** [comment]
#48570 reduxifies plugin sites and removes the unnecessary flux method `getSites()`.

**Comment by tyxla** [comment]
#48572 removes the extra last arg we added in `doActionOverSelected` to support both flux and redux.

**Comment by tyxla** [comment]
#48665 reduxifies the last `getPlugins` flux store method, and removes the last usage of the main plugins store!

#48666 follows up and removes the store, plus any related flux remnants.

**Comment by tyxla** [comment]
#48868 and #48877 are preparatory PRs to organize code and remove unnecessary bits from the legacy wporg plugins store.

**Comment by tyxla** [comment]
#48962 introduces a Redux version of the wporg plugins flux store. We'll port the existing code that uses the old store in another PR.

**Comment by tyxla** [comment]
#48999 cleans up the trash we introduced with site => site IDs and other bound functions when reduxifying plugins.

**Comment by tyxla** [comment]
Several more PRs got into place here in the meantime:
* #48996 disabled other actions while performing one in `PluginMeta`.
* #49035 fixed the `isFetching` to use the selector properly
* #49184 adds a query component and a couple of selectors on top of the work in #48962.

**Comment by tyxla** [comment]
#49198 reduxifies the `PluginsBrowser` and removes the last usage of the last plugins store 🥳 .

I've got some last cleanups to take care of before I mark this one as completed.

**Comment by tyxla** [comment]
#49266 is a fix for a bug we found while working on #49198 and #49267 removes the flux plugins pieces.

With #49267 merged, we can actually call this done!
