### ISSUE TITLE
Checkout: designs for early testing of multiple domain checkout flows

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2418]
Raised by @breezyskies 

We'd like to gather some data about how conversions are affected when we bias the the domain search and registration flow towards domains search (multiple domains) vs. bias the flow towards checkout as it is now. As discussed in Slack (p1437412814000036-slack-domains), here are designs for simple two variations for a test:

**Variation 1**
We take the user to Google Apps, just as we do now, but we present clear options for going back to domain search or continuing to checkout:
<img width="673" alt="domains_abtest_gapps" src="https://cloud.githubusercontent.com/assets/3011211/8787504/6e65b4fa-2ee9-11e5-952a-b5665122d505.png">

**Variation 2**
We keep the user on the domain search page, but open the cart and show the two options (keep searching and checkout). Clicking checkout would take them to the Google Apps step:
<img width="366" alt="domains_abtest_cart" src="https://cloud.githubusercontent.com/assets/3011211/8787535/9b41d86e-2ee9-11e5-848c-bef5541dca54.png">

As discussed in Slack, two other pieces are required for any flow we move forward with:
- Showing a [checkmark on the button](https://cloud.githubusercontent.com/assets/1119271/12326485/179cffba-ba9f-11e5-8052-d0151521e161.png) after a domain is added to the cart (work for this is already in progress).
- Show the [new version](https://cloud.githubusercontent.com/assets/1119271/12326484/17797f72-ba9f-11e5-9665-0424ad12fc4f.png) of the form for adding a user to Google Apps (reusing the piece being worked on by Iris for domain management).

cc @umurkontaci @dzver @p3ob7o

**Comment by klimeryk** [comment]
This seems like a very interesting A/B test - any reason it did not get implemented since January? /cc @breezyskies @lucasartoni 
Maybe Cobalt could look into it - the implementation should be very simple. All the parts are there, just needs adding an A/B test and those two buttons (from what I can see). /cc @wensco

**Comment by mikeshelton1503** [comment]
Closing this since the designs are a bit old now and we will implementing multiple domains on Tortuga soon and will then bring that fucntionality over to Calypso.
