### ISSUE TITLE
Activity Log: Changes From WP-Admin As Staff Record Staff Name As An Admin 

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#24192]
I was testing something on user's site and made a change from WP-Admin to their comments. When I checked an Activity Log, my name was recorded as an admin on the site: https://cloudup.com/clkGfs5fbGL

#### Steps to reproduce
1. Starting at URL: As staff who is a Super Admin, go to any site's WP-Admin e.g. https://senfftestwpplanspersonal.wordpress.com/wp-admin/
2. Make a change on user's site e.g delete a comment from WP-Admin
3. Check activity on user's site: https://wordpress.com/stats/activity/senfftestwpplanspersonal.wordpress.com

#### What I expected

Changes made to be showed as ones made by user 

#### What happened instead

My name was reflected in the Activity Log: https://cloudup.com/cXMbyX11Wgz

#### Context / Source
When I am making changes on user's site by using SU, this does not happen. I am not sure to what extent it is a bug but wanted to report it here just in case.

**Comment by roccotripaldi** [comment]
This should be resolved now. Actions in wp-admin, or while SU by a Happiness Engineer on behalf of user should now be displayed as being done by a generic Happiness Engineer avatar.
