### ISSUE TITLE
Jetpack: Add existing Jetpack site URL is buggy using backspace

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#24193]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/new?ref=calypso-selector
2. Start typing a url, eg. mountain.com - note URL defaults to HTTP
3. Use backspace on keyboard go back to the HTTP and add an S
4. Input now doesn't work, using backspace behaves strangely

#### What I expected

Can edit the URL to HTTPS using backspace

#### What happened instead

Can't edit it, weird behaviour - see screencast

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

![add new jetpack site](https://user-images.githubusercontent.com/128826/38787539-e3920fc4-4171-11e8-8ca5-c8cd77d4339f.gif)

#### Context / Source
 #automated-testing

**Comment by designsimply** [comment]
Tested and confirmed that using the backspace to delete content in the Jetpack "Add New Site" box results in some strange behavior such as not being able to add an "s" to the prepopulated "http://". Tested with Firefox 59.0.2 on macOS 10.13.4.

Note: the "Add New Site" flow is currently being redesigned in https://github.com/Automattic/wp-calypso/pull/23093/ and it would be good to circle back and re-test this issue after that update goes through.

**Comment by tyxla** [comment]
This has been fixed in #25557.
