### ISSUE TITLE
In-page translator and help round blue icons overlapping 

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#24204]
#### Steps to reproduce
1. Enable the community translator tool (https://translate.wordpress.com/community-translator/). To do this, you would need to set up your interface language to other than English.
2. Go to account settings https://wordpress.com/me/account
2. Click on Community Translator check-box (Enable the in-page translator where available)

#### What I expected
HELP and TRANSLATION icons well formatted 

#### What happened instead
 HELP and TRANSLATION icons overlap.

#### Browser / OS version

Tested on a MAC for MOzilla and Chrome with identical results.

#### Screenshot / Video
![account settings wordpress com 2018-04-16 15-28-42](https://user-images.githubusercontent.com/6404071/38811944-3bb891e6-418b-11e8-9f73-5a1c5da8720e.png)
![account settings wordpress com 2018-04-16 15-28-05](https://user-images.githubusercontent.com/6404071/38811945-3c2edc02-418b-11e8-8d2d-432455daa7c9.png)

**Comment by simison** [comment]
Duplicate: https://github.com/Automattic/wp-calypso/issues/23884

**Comment by rantoncuadrado** [comment]
Hey thanks, @simison :)
Closing this thread then.
