### ISSUE TITLE
Checkout: theme name description not very descriptive in cart

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2420]
Raised by @v18 

When purchasing a theme, the description shows the theme slug. Instead can we show the site on which it’ll be activated? Similar to the way the WordPress.com upgrades show up:

Cart PopOver | Checkout
------------ | -------------
![screen shot 2016-01-14 at 09 23 01](https://cloud.githubusercontent.com/assets/1119271/12326825/00fa0526-baa1-11e5-8f7a-1e75742a155a.png) | ![screen shot 2016-01-14 at 09 23 26](https://cloud.githubusercontent.com/assets/1119271/12326826/00fa563e-baa1-11e5-8d73-3599a1fe6ea4.png)

**Comment by alleh** [comment]
Something like this? 

<img width="308" alt="wp-calypso-cart" src="https://cloud.githubusercontent.com/assets/3101006/12365661/733526f8-bbd6-11e5-9344-508b343328db.png">

PR: #2498 

(First contribution, if I did something wrong let me know!)

**Comment by gziolo** [comment]
Fixed with #2498. Props to @alleh!
