### ISSUE TITLE
Reduxify: Transactions

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#24217]
## Summary
* Just one store, but part of checkout. 
* Exposes one method, `get`, which hands back the entire transaction
* Used in one place `client/components/data/checkout/index.jsx`
* Waits on the CartStore using `Dispatcher.waitFor` to do some work
* Already uses immutable updates
* Should be an easy port, assuming we can redux-bridge it.

**Comment by tyxla** [comment]
This legacy store has been removed in https://github.com/Automattic/wp-calypso/pull/48066, kudos to @sirbrillig 🙌
