### ISSUE TITLE
Domain Management: missing expired domain notice in the domain management list

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2422]
Raised by @breezyskies 

In the original prototype for the domains list, there are compact notices for expired domains:

![original prototype](https://cloud.githubusercontent.com/assets/1119271/12325175/49283cc4-ba96-11e5-899a-cdf7bc1eaa72.png)

In the current domain management list, that compact notice is missing:

![screen shot 2016-01-14 at 08 30 55](https://cloud.githubusercontent.com/assets/1119271/12325639/987ff692-ba99-11e5-83e8-41e82fc0b577.png)

In comparison, an expired domain notice is present on the purchases page:

![screen shot 2016-01-14 at 08 32 21](https://cloud.githubusercontent.com/assets/1119271/12325638/987e79c0-ba99-11e5-8bc7-f7d2bc7135cf.png)

**Comment by klimeryk** [comment]
Fixed by #2728.
