### ISSUE TITLE
Reduxify: People

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#24221]
`lib/people/store` is a simple little store that holds errors, but listens to 13 different actions from across people management. 

It ties in with users, viewers, invites, and followers.

A simple store (v150 LOC) but integrated into other parts.

**Comment by tyxla** [comment]
I've started working on this in https://github.com/Automattic/wp-calypso/pull/39372 which is split for easier review and testing to the following PRs:

- https://github.com/Automattic/wp-calypso/pull/39374
- https://github.com/Automattic/wp-calypso/pull/39375
- https://github.com/Automattic/wp-calypso/pull/39377
- https://github.com/Automattic/wp-calypso/pull/39378
