### ISSUE TITLE
Activity Log: pagination doesn't create an entry in brower's history

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#24220]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/activity/$ite.blog
2. use the AL pagination to go to a page other than page 1
3. click back in the browser

#### What I expected
To be taken back to page 1

#### What happened instead
I was taken to Stats main page. I had to click on Activity in the tab again

#### Context / Source
#dogfooding #anxiety #stresscase #painpoint.

**Comment by roccotripaldi** [comment]
related to filtering / url discussions here: p9rlnk-hP-p2

**Comment by roccotripaldi** [comment]
This is fixed. Thanks @dmsnell
