### ISSUE TITLE
Google Apps: update the link on the checkout thank you page so it doesn't lead to information about a step that was just completed

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2423]
From @Lochlaer:

> Currently the number 1 reason people contact us about Google Apps is because it’s not clear post-purchase what’s supposed to happen next. Perhaps a notice at checkout that they will receive their temporary login credentials from WordPress.com that they can use to login to their new Gapps account?

To test:

1. Go to https://wordpress.com/
1. Switch sites to a site that has a domain without Google Apps
1. Click Domains in the left sidebar
1. Click on the domain
1. Click Email
1. Click Add Google Apps
1. Enter an email and click Continue
1. Complete the purchase
1. Click the "More about Google Apps" button

<strong>Result:</strong> the link leads to https://en.support.wordpress.com/adding-google-apps-to-your-site/ where it begins by explaining how to purchase Google Apps—which is strange, because I already just did that. 

It would be better to link to https://en.support.wordpress.com/email-notifications/ or https://en.support.wordpress.com/adding-google-apps-to-your-site/#completing-sign-up instead.

Video: https://cloudup.com/c1W7mC-mtzB

![screen shot 2016-01-14 at 09 42 12](https://cloud.githubusercontent.com/assets/1119271/12327900/e4435c74-baa6-11e5-9ca5-6a20751b7b0d.png)
<sup>Tested with Firefox 43.0.2 on Mac OS X 10.10.5</sup>

**Comment by fabianapsimoes** [comment]
@Lochlaer We're currently redesigning the Thank You page. Could you take a look at [this copy](https://docs.google.com/document/d/1GmR-hw3gv63Lj8VT7hXirgneRHQ-Awyy19x2X3zLOA8/edit#heading=h.21qfk3txc0u6) and links, and provide feedback in #2484? 

Closing this since this layout and copy is soon gone.
