### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Butonix** [Automattic/wp-calypso#24238]
Hello!
Tell me, please, is this the same engine as WordPress on PHP?
can I use it on my server on my domain?
Is there an admin panel like in the version on php?
Are plugins supported?
Thank you very much in advance

**Comment by alisterscott** [comment]
Hello

Calypso is the new WordPress.com front-end – a beautiful redesign of the WordPress dashboard using a single-page web application, powered by the WordPress.com REST API. Calypso is built for reading, writing, and managing all of your WordPress sites in one place.

This project on runs for WordPress.com and isn't usable for WordPress local or server installations.

I will close this issue now

Thanks
