### ISSUE TITLE
Google Apps: update the subheading on the checkout page to mention where the confirmation email will come from

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2424]
From @Lochlaer:

> Can you edit the info underneath "Thank you for your purchase" so that it reads:
> 
> **You will receive an email confirmation from WordPress.com shortly.**
> 
> Sometimes the email from us is delayed. Users get emails from Google as well welcoming them to their new account, and that doesn't have login information, which leads to confusion if they haven't yet gotten the email from [WordPress.com].

For reference, the current text (as of 14-Jan-2016) reads: 

> You will receive an email confirmation shortly for your purchase of Google Apps. What's next?

![screen shot 2016-01-14 at 10 11 45](https://cloud.githubusercontent.com/assets/1119271/12328131/f7ec5522-baa7-11e5-97f1-6bfc33630806.png)

**Comment by fabianapsimoes** [comment]
@Lochlaer We're currently redesigning the Thank You page. Could you take a look at [this copy](https://docs.google.com/document/d/1GmR-hw3gv63Lj8VT7hXirgneRHQ-Awyy19x2X3zLOA8/edit#heading=h.21qfk3txc0u6) and provide feedback in #2484? 

Closing this since this layout and copy is soon gone.
