### ISSUE TITLE
Pop-up to be removed from Domain Search Redesign

### ISSUE THREAD

**Issue by lucasartoni** [Automattic/wp-calypso#24249]
#### Steps to reproduce
1. Starting at URL: https://horizon.wordpress.com/start/domains
2. Domain results show a pop-up, coming from the previous interface.

#### What I expected

No pop-up, considering it was not present in any of the design wireframes.

#### Browser / OS version

Chrome and Safari. I guess, all browsers.

#### Screenshot / Video

<img width="696" alt="screen shot 2018-04-17 at 13 31 27" src="https://user-images.githubusercontent.com/1906067/38869985-bb73d244-424c-11e8-9578-cf4e2a98f2fa.png">

#### Context / Source

#manual-testing

**Comment by jsnmoon** [comment]
@danhauk, did you mean to explicitly remove this interface via the redesign?
