### ISSUE TITLE
External Link: Reduce and make icon margin consistent

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#24241]
The [`ExternalLink` component](https://github.com/Automattic/wp-calypso/blob/master/client/components/external-link) shows an icon next to it to denote that the user will be redirected to an external site. I'd like to suggest we reduce the margin between the link text and this icon as right now they look a bit disconnected:

<img width="372" alt="screenshot" src="https://user-images.githubusercontent.com/594356/38859178-c2601f78-422d-11e8-85d7-5cb6649cfbe3.png">

This will also make it more consistent with other components that are using this design pattern such as the [`ActionCard` component](https://github.com/Automattic/wp-calypso/tree/master/client/components/action-card):

<img width="466" alt="screenshot" src="https://user-images.githubusercontent.com/594356/38859336-1448434c-422e-11e8-9662-c6d42998986e.png">

/cc @scruffian

**Comment by dezzie** [comment]
I looked into this and what's actually going on is that there are no margins to the left or right of the icon in the `ActionCard` component. What you see is a non-breaking space to the left or the right of the text where the icon is used. 

If I remove the margins from the left or right of the icon in the `ExternalLink` icon, we'll achieve consistency, but I'd have to find every place where the icon is used and make sure there is a non-breaking space too.

The faster fix, which I am going to propose, is to eyeball the margins like you proposed. That might break in case the external-link icon is used with bigger type sizes, or if we ever change out the font. The non-breaking space width in pixels is always dependent on the type size.

Here's what it would look like:
<img width="210" alt="screen shot 2018-06-11 at 7 47 02 pm" src="https://user-images.githubusercontent.com/1301932/41264069-3cc450ec-6db0-11e8-8188-fdb767bff790.png">
