### ISSUE TITLE
Domain Search: error when punctuation is present in a search query

### ISSUE THREAD

**Issue by lucasartoni** [Automattic/wp-calypso#24253]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/domains
2. Search any string with an apostrophe, comma, etc.

#### What I expected

I expected a more pleasing handling of the invalid chars.

#### What happened instead

An error message is displayed to the user.

#### Browser / OS version

All browsers.

#### Screenshot / Video

<img width="1053" alt="screen shot 2018-04-17 at 15 01 26" src="https://user-images.githubusercontent.com/1906067/38871221-7e534436-4250-11e8-9638-db4a770e8838.png">

#### Context / Source
#dogfooding, #manual-testing

**Comment by hambai** [comment]
That was a backend regression in how we handle the input validation (introduced in D11076 around 30th of March 2018). I've just reverted it.

**Comment by lancewillett** [comment]
CC @andrewspittle to close the loop. Thanks for bringing this up!
