### ISSUE TITLE
Editor: Improve UX for adding multiple pages

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#2426]
The flow for creating many page stubs in a single session is quite cumbersome. Once publishing the first page, the steps you need to take are: Click back to “Pages” and “Add” in the sidebar (There's no "Add" in the "Pages" page) OR remove the ID from the URL to start a new page. Neither one is easy or immediately intuitive.

I might imagine a scenario where a user wants to create all of their pages before filling them with content, e.g. “About”, “Contact”, etc especially when creating a new site.

Raised by @aduth.

**Comment by kellychoffman** [comment]
One possible solution that comes to mind: 

Add a **Add New Page** link in the notice upon publish, as a secondary item (**View page** being the primary)

**Comment by lancewillett** [comment]
Anecdote from @melchoyce 

> When I’m setting up a new site, I’ll often create a bunch of new pages at the same time to use as placeholders. This is super easy in wp-admin, but when I’m in Calypso, I have to make the new page → go back → make the new page instead of make the new page → make another new page. It would be nice to make it easier to continue this page-making flow. (Could be an underlying symptom of how bad site building is, though.)

**Comment by kellychoffman** [comment]
> Add a Add New Page link in the notice upon publish, as a secondary item (View page being the primary)

To add a visual:

<img width="884" alt="screen shot 2017-02-06 at 7 53 09 pm" src="https://cloud.githubusercontent.com/assets/5835847/22675976/f3ee4c60-eca5-11e6-8d6a-4df5b7f8bd75.png">

**Comment by melchoyce** [comment]
WFM 👍 

How would you see it working in the awkward mid-range widths?

<img width="688" alt="screen shot 2017-02-06 at 11 04 50 pm" src="https://cloud.githubusercontent.com/assets/2846578/22677460/b8696ccc-ecc0-11e6-8a13-8ec6ffaec566.png">

**Comment by lancewillett** [comment]
Another way to tackle this (on in addition) is a Add New Page link in the sidebar footer, next to the ? icon for help. Works for the current site only — not launching a site picker like the Write icon does.

**Comment by kellychoffman** [comment]
@lancewillett: I don't think that would be a very intuitive place to look. 

@melchoyce: What about this? 

<img width="409" alt="screen shot 2017-02-09 at 3 37 58 pm" src="https://cloud.githubusercontent.com/assets/5835847/22806124/cc9a9454-eedd-11e6-949a-7b95006690db.png">
