### ISSUE TITLE
JPC: Add a notice to the invalid credentials error notice

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#24279]
Relates to #23997 (already merged).

Let's add a red notice alerting users that their credentials were invalid right above the username/pw text fields in the white box:

<img width="379" alt="screen shot 2018-04-17 at 2 44 55 pm" src="https://user-images.githubusercontent.com/204742/38896057-eadb21a2-424e-11e8-861c-38d3e7427e2b.png">

**Comment by seear** [comment]
Also:

> add a red error text below the highlighted field saying "Username does not exist. Please try again." (for username error) and "Incorrect password. Please try again." (for password error)?
