### ISSUE TITLE
Sidebar: visual issue when resizing from small to large viewport

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-calypso#243]
I got this when I made my window bigger after having the sidebar open in mobile viewport (the main content had an overlay)

![pasted image at 2015_11_19 12_26 pm](https://cloud.githubusercontent.com/assets/260253/11284576/837f3768-8ed8-11e5-8a5a-43ff711677b0.png)

Note: sites in the sidebar smudged out in the screenshot to hide my sites.

**Comment by lancewillett** [comment]
Can't repeat this today: feel free to re-open if you see it again.
