### ISSUE TITLE
Domain Management: allow users to edit a mapped domain after purchase

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2430]
Raised by @breezyskies 

If a user purchases domain mapping, we should let them edit the domain post-purchase (we get occasional tickets when a user has made a typo during purchase).

![screen shot 2016-01-14 at 12 28 11](https://cloud.githubusercontent.com/assets/1119271/12332050/6a4aa08a-baba-11e5-8bbf-a1a550c50326.png)

Also see 8290-gh-calypso-pre-oss

**Comment by klimeryk** [comment]
Now that mappings are free with plans and we added the ability to move mappings across sites and users, this does not seem worth it anymore. Closing as wontfix.
