### ISSUE TITLE
Customize button playing hide and seek

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#2431]
I'm not totally sure this is the right place to log this, let me know where is if not. In a recent theme user test some rather interesting behaviour happened with the customize button. It doesn't appear on the first view, then it appears. As a result the person ended up going through the 'My Sites' navigation.

https://cldup.com/QDFDjt0xL5.mp4 shows the video.

**Comment by lancewillett** [comment]
This is a bug in the WordPress.com "Actionbar". I'll move it to the WP.com bug tracker.

**Comment by lancewillett** [comment]
7665-wpcom

**Comment by karmatosed** [comment]
Thanks.
