### ISSUE TITLE
Plans: broken "manage plan" button

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#24320]
Pressing "Manage plan" button doesn't bring you anywhere.

#### Steps to reproduce
1. Have a site with a Plan. Mine is Jetpack connected site, I didn't test other types of sites.
1. Open `https://wordpress.com/plans/my-plan/:site`

    ![image](https://user-images.githubusercontent.com/87168/38985649-adc67fe8-43d2-11e8-8053-4b07b09f4fa4.png)

1. Press **Plans** and end up `https://wordpress.com/plans/:site`

    ![image](https://user-images.githubusercontent.com/87168/38985847-34ce989a-43d3-11e8-921f-1ef789ed407f.png)

1. Press **Manage Plan**

    ![image](https://user-images.githubusercontent.com/87168/38985725-dd62b672-43d2-11e8-898c-edd69f84fd31.png)

1. End up to `https://wordpress.com/plans/` and see the site selector

1. Choose the site and end up back to `https://wordpress.com/plans/:site`

#### What I expected
Ending up to `https://wordpress.com/plans/my-plan/:site`

#### What happened instead
Ended up to `https://wordpress.com/plans/:site`

**Comment by rachelmcr** [comment]
Confirmed this bug on a WordPress.com Simple site.

The "Manage Plan" button points to this URL (no `:site` included): https://wordpress.com/plans/my-plan/

That URL redirects to https://wordpress.com/plans/ where the site selector appears.
