### ISSUE TITLE
Plans: Display issue of localized plan names

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#2434]
Plan names ("WordPress.com Free", "WordPress.com Premium", and "WordPress.com Business") localization: when a plan name is supposed to appear on two lines, for some locales e.g. zh_TW the wrapping happens in the middle of the second (translated) word. For optimal display, the wrap should happen after "WordPress.com".

![zh-tw_desktop_3a_plan_comparison_screenshot1449463283949](https://cloud.githubusercontent.com/assets/7637835/12335287/b6663a6c-bafe-11e5-8b04-8e274a5ae6c2.png)

cc @scruffian and @gziolo since you worked on the [file](https://github.com/Automattic/wp-calypso/blob/master/client/components/plans/plan-header/index.jsx) where the issue occurs originally.

**Comment by akirk** [comment]
An idea for a solution: output `planName.replace( 'WordPress.com', 'WordPress.com<br/>' );`

**Comment by scruffian** [comment]
I think a better solution would be to use `preventWidows`.

**Comment by akirk** [comment]
Had I known that existed, I would have suggested that :) Thanks!

**Comment by scruffian** [comment]
Actually this won't work, since in English there are two words and they are thereby forced onto one line:

<img width="686" alt="screen shot 2016-01-18 at 10 16 40" src="https://cloud.githubusercontent.com/assets/275961/12388729/9c9abe98-bdcc-11e5-9f2e-6cc8d46c15eb.png">

**Comment by jenial** [comment]
The previous solution actually had "WordPress.com" on one line and the plan name on the other line:

![en_desktop_3a_plan_comparison_screenshot1449463047635](https://cloud.githubusercontent.com/assets/7637835/12391577/0e629c46-bde9-11e5-9e63-832271a63e6e.png)

**Comment by jenial** [comment]
So, to clarify my request: for other locales e.g. zh_TW referenced in the example, the same would work, via forcing a line break after "WordPress.com".
