### ISSUE TITLE
Kraken: Disable the "Enable Dashes" if "Show exact matches only" is checked

### ISSUE THREAD

**Issue by hambai** [Automattic/wp-calypso#24372]
It makes no sense to have "Enable Dashes" as an option if the "Show exact matches only" is enabled. So maybe we should disable the checkbox in that case.

**Comment by lucasartoni** [comment]
It's a good feature. Not critical for launch, but good to implement in the future.

**Comment by jsnmoon** [comment]
I actually think dashes and exact match filters can be combined like so. Take this example:

- Query: `a new beginning`
- Enabled filters: Dashes and exact match
- Expected suggested domains: `a-new-beginning.com`, `anew-beginning.com`, etc.

I think this discussion might be moot depending on the answer to https://github.com/Automattic/wp-calypso/issues/24374#issuecomment-391113395. I provided the example above assuming the dashes filter to exclude non-hyphenated suggestions.

**Comment by klimeryk** [comment]
Marking as wontfix - agree with Jason on this.
