### ISSUE TITLE
Google Apps: insufficient feedback about Google Apps price 

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2437]
Raised by @ranh 

How did we get from $5 per user to $100 for two users? Don't make me ~~read~~ think. If we charge yearly, we should clearly show the yearly price.

Show when adding Google Apps to a previously registered domain:

![screen shot 2016-01-14 at thu jan 14 3 40 17 pm](https://cloud.githubusercontent.com/assets/1119271/12337223/cbd9d57a-bad6-11e5-9376-138aa5f54677.png)

Show when adding Google Apps to a new domain registration:

![screen shot 2016-01-14 at 15 42 22](https://cloud.githubusercontent.com/assets/1119271/12337224/cbda84de-bad6-11e5-880f-0d34728a4012.png)

After adding two users to Google Apps, here is what the cart displays:

![screen shot 2016-01-14 at thu jan 14 3 48 06 pm](https://cloud.githubusercontent.com/assets/1119271/12337225/cbdbc8f8-bad6-11e5-83d1-53882418a21f.png)

Comment from @breezyskies 

> If we're going to do this, we should run it as a test ("$50 per user / year"), not make the change straight up. cc: @lucasartoni  
> 
> Another option is to repeat this info in the cart, but there's already a lot going on with Google Apps cart items, so this would just add noise to that. 

Comment from @lucasartoni 

> I agree on setting up a test for this

**Comment by gziolo** [comment]
Related to #2341.

**Comment by janm6k** [comment]
Going through old issues, closing ones that does not look like important one.

Please feel free to reopen if applicable.
