### ISSUE TITLE
"Follow Blog" widget sends 2 emails to site owner

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#24385]
I'm reporting an issue mentioned by a user that I was able to reproduce on a test site. With the **Follow Blog** widget, a site owner will receive an email notification about a user following them twice.

#### Steps to reproduce
1. Add a **[Follow Blog](https://en.support.wordpress.com/widgets/follow-blog-widget/)** widget to your blog and have email notifications activated
2. Log into another account and follow the blog in question using the button from the widget you previously added
3. You'll receive 2 emails mentioning a new user is following your blog

#### What I expected
Just like all the other options (Reader, bottom right corner button, etc.), I expected to receive only one email.

#### What happened instead
Instead, I'm receiving 2 emails, as seen in this screenshot from the email logs:

<img width="832" alt="capture_d ecran_2018-04-21_a_13_51_37-2" src="https://user-images.githubusercontent.com/16645645/39087511-71175334-45a2-11e8-9ae2-5589fa1fb5b3.png">

#### Browser / OS version
Tested and reproduced on Chrome and Firefox

**Comment by rachelmcr** [comment]
Thank you for testing and reporting this issue! I'm moving this report to 8041-wpcom (since it's related to a widget on the front of the site, rather than in Calypso itself).
