### ISSUE TITLE
Domains: Cached "You must verify your email" message can prevent user from adding a domain

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#24381]
#### Steps to reproduce
1. Register a new account. Don't verify the email address yet.
2. Navigate to Domains  => Add Domain.
3. Check your email and click the link to verify the email address.
4. (in original browser tab, at least I think?): Go back to Domains => Add Domain.  You will see a "You must verify your email to register new domains" message which prevents you from adding a domain.  If you click the "Resend email" link, you get "The email could not be sent. The email address associated with this account is already verified".  If you navigate away and come back, the same thing happens, over and over again.

Doing a full page reload eventually fixes it.

Something along these lines was experienced by an end user (2984570-hc and 1107323-zen) and it was very confusing to help them through it since I couldn't see the same thing as them no matter what I tried.

#### What I expected

Ideally, the error message goes away automatically on its own once the email verification happens.

If not, at a minimum, the first time you click the "Resend email" link in this scenario, and the system notices that your address is already verified, it should be smart enough not to keep trying to make you verify it again.

**Comment by klimeryk** [comment]
Noting that there have been internal reports as well, see p2MSmN-6sb-p2 and we're tracking it in the Trello card mentioned there.
