### ISSUE TITLE
Domains: Kracken Select Buttons in IE11 overlap featured results

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#24388]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/start/domains in IE11
2. Navigate to domains page
3. Search for something

#### What I expected

No overlap

#### What happened instead

Overlap

#### Browser / OS version

IE11 Windows 7

#### Screenshot / Video

<img width="1346" alt="kracken ie11" src="https://user-images.githubusercontent.com/128826/39109998-b45aea2c-4712-11e8-897d-8b3435d0aa30.png">

**Comment by sixhours** [comment]
@alisterscott Are you still seeing this? I haven't been able to reproduce it in Browserstack with IE 11 on Windows 7.

**Comment by alisterscott** [comment]
@sixhours thanks for looking, I can no longer reproduce either - closing.

![Uploading Screen Shot 2018-05-29 at 9.45.38 am.png…]()
