### ISSUE TITLE
Domain Management: email confirmation is not required for forward to start working

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2439]
Raised by @ranh

Adding a new email forward sends a confirmation email to the target email address:

![screen shot 2016-01-14 at thu jan 14 4 07 47 pm](https://cloud.githubusercontent.com/assets/1119271/12337661/49786292-bad9-11e5-8901-3aa6261dfbea.png)

However, this is not mentioned during the flow for adding an email forward.

The confirmation message suggests that the email forward was added and that no further action is needed:

![screen shot 2016-01-14 at 16 05 52](https://cloud.githubusercontent.com/assets/1119271/12337689/6f33391c-bad9-11e5-8fa7-afab2520bcf2.png)

Indeed, it does look like no further action is needed. The forward starts working immediately without clicking the link. 

I was able to receive a forwarded message without clicking the "Confirm Email Forward" link in the confirmation email.

**Comment by designsimply** [comment]
Comment from @ranh moved from a separate issue:

> Clicking the confirmation link sent me to this path:
> 
> `/wp-admin/paid-upgrades.php?page=domains&email_forward=1`
> 
> This is a wp-admin screen, even though I added the forward from Calypso.

I tested just now and after clicking the "Confirm Email Forward" link in the confirmation email, this is what I saw:

![screen shot 2016-01-14 at thu jan 14 4 16 32 pm](https://cloud.githubusercontent.com/assets/1119271/12337863/9d5b7c68-bada-11e5-8a58-8c7808105f1b.png)

Path:

> `/wp-admin/paid-upgrades.php?page=domains&action=emailforwardnonce`

Error:

> We were not able to verify this email forwarding, we have resent the confirmation email.

If the email confirmation step is removed, this shouldn't matter. If the email confirmation step stays, then we need a new landing page for the confirmation step.

**Comment by aidvu** [comment]
https://github.com/Automattic/wp-calypso/pull/4257
