### ISSUE TITLE
Store: Handle "Enable stock management" being disabled

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#24410]
See p90Yrv-El-p2.

> The user was trying to update their Inventory to 13, and set to No Backorders through Calypso. They were able to edit the field, but once they hit “Publish” or “Update”, the field would revert back to 0.

> Some digging around revealed that they had Enable stock management disabled in the WP Admin area, which meant that the Inventory field in Calypso wouldn’t be used. Once this was enabled, everything worked as expected.

> The issue is there’s no obvious or immediate way for someone editing in Calypso to know whether this field is being used or not. It looks identical when stock management is both enabled or disabled.

> Would greying out the area if it’s not being used, along with a link on how to enable be possible?

**Comment by designsimply** [comment]
Tested and confirmed with the following steps:

1. Go to wp-admin > WooCommerce > Settings > Products > Inventory.
1. Set "Manage stock" = unchecked and save changes.
1. Go to Calypso > Store > Products > Add a product.
1. Fill in the required fields.
1. Set "Inventory" to a nonzero number.
1. Set "Backorders" = "Allow, but notify customer" and save changes.
1. Force refresh the product page and check to make sure the Inventory and Backorders settings were saved as expected.

Result: Inventory and Backorders settings are not saved if "Manage stock" is unchecked in wp-admin.

![screen shot 2018-04-23 at mon apr 23 11 09 56 am](https://user-images.githubusercontent.com/1119271/39142325-958a8ce0-46e7-11e8-847e-1fe2de5b6f64.png)
<sup>Seen at https://wordpress.com/store/product/madefortesting347.blog using Firefox 59.0.2 on macOS 10.13.4.</sup>

![screen shot 2018-04-23 at mon apr 23 11 03 09 am](https://user-images.githubusercontent.com/1119271/39141794-013483e4-46e6-11e8-83f1-d37919192954.png)
<sup>Seen at wp-admin > WooCommerce > Settings > Products > Inventory tested with Firefox 59.0.2 on macOS 10.13.4.</sup>

<sup>Reported at 1099066-zen (internal reference)</sup>
