### ISSUE TITLE
Domain Mapping: automatically fill if coming from a search for an existing domain

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2442]
Raised by @fabianapsimoes 

Steps to reproduce:

- Visit `/start/domain` and enter an existing domain
- Click the Map it button (not the link in the yellow banner)
- The Domain Mapping page will open with an empty field.

I understand that, ideally, users would use the Map It link instead of the button. But for those who missed it, it'd be easier if after searching for an existing domain the Domain Mapping field was pre-filled with that domain.

**Comment by klimeryk** [comment]
Related issues: #859 and #2326 (so that when we start working on this, we can fix up all the issues at once, since they are related)
