### ISSUE TITLE
Domain Management: improving UX for domain mapping

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2443]
Raised by @fabianapsimoes 

If you try to map a domain that hasn't been registered yet, you'll be prompted to register it. The elements in this prompt aren't aligned correctly.

![screen shot 2016-01-14 at 16 47 10](https://cloud.githubusercontent.com/assets/1119271/12338639/9e77f0f0-bade-11e5-8eb7-6f487e9fab37.png)

I have mixed feelings about displaying two notices, one above and one below the Domain Mapping field. We should probably also emphasize that "is available" is now related to registration, no longer mapping.

cc @breezyskies 

Comment from @kriskarkoski 

> I think we should suppress the "cannot be mapped" error when someone types a domain that is not registered but available and just keep the add domain box that's already there while fixing the alignment issues One improvement might be hiding the mapping price in this situation as it does seem confusing to have two prices on the screen or add an explanation of the price difference.

Commens from @folletto 

> > We should probably also emphasize that "is available" is now related to registration, no longer mapping.
>
> Agreed.
> Plus, red should be used just for really urgent things (i.e. use red if their site is offline, or the post exploded), this is barely a contextual information. And it's displayed above, while I would expect it to be below in terms of information architecture (top-down content structure).
>
> > I think we should suppress the "cannot be mapped" error when someone types a domain that is not registered but available and just keep the add domain box that's already there
>
> This seems a simple fix.
> For the future, I feel it should behave more like domain search than using alerts: I search, below it tells me "The domain is available, register and map" or "The domain is available, map". In terms of user goal, that's what they want, doesn't matter if technically it's "mapping" or "registering", they are both steps to the goal. :)
>
> Similarly I feel that the yellow ["Map it" banner](https://cloud.githubusercontent.com/assets/4389/9607583/e411486e-50c1-11e5-892a-19d17c12887d.png) in the domain search page could just be another box at the top of the options saying "Hey, this is registered, if it's yours great, map it!". Not really an alert either. :)
>
> This approach of just showing the options as boxes below would solve also the double price issue. ;)

Comment from @fabianapsimoes 

> > Plus, red should be used just for really urgent things (i.e. use red if their site is offline, or the post exploded), this is barely a contextual information.
>
> Just for the record, we have quite a few red notices in the Domain step. Here are a few examples:
>
> ![error3](https://cloud.githubusercontent.com/assets/1248436/9608567/680838e6-50cf-11e5-9a8b-d603b0682e01.png)
> ![error2](https://cloud.githubusercontent.com/assets/1248436/9608566/6802a368-50cf-11e5-8136-76fa037ccafa.png)
> ![error1](https://cloud.githubusercontent.com/assets/1248436/9608565/68006e7c-50cf-11e5-9807-4ec2527639ed.png)
>
> Two points with regards to this:
>
> - I'm not sure we need validation notices in the Domain Search. If a domain typed by a user includes an invalid character, it doesn't really matter became the domain suggestions won't include it and that's the final input of that step.
> - In the case of the Domain Mapping section, I do think validation is needed since we're dealing with actual user input. However, I'd like to see here the same kind of inline validation we have in the User and Site steps.
>
> > Similarly I feel that the yellow "Map it" banner in the domain search page could just be another box at the top of the options saying "Hey, this is registered, if it's yours great, map it!".
>
> The Map it option is there, at the bottom of the domain suggestions table. In #2442, I suggested automatically filling the Domain Mapping step if the user clicks on the Map It button after searching for a domain that has already been registered. However, if we remove the notice, we don't even need the automatic fill. We can just add the mapping to the cart and move on to the next step.

Comment from @folletto 

> > The Map it option is there, at the bottom of the domain suggestions table.
> 
> Ah yes! I was thinking to show _two_ boxes (one with the pre-filled Map It, and another just the standard Map It) but your idea in #2442 would be as good. :)
> 
> And yes, that's the idea. The options listed below the box are all alternative choices to go forward to the final objective (this domain will be mine!), so they should all be equally smooth and hide the technicalities of it as much as possible. :)

Comment from @breezyskies 

> I like the idea of using a "map it" domain suggestion to convey that the domain is already registered rather than the yellow warning, but we have to be very careful to convey that they must own the domain already (domains are confusing!). An early idea of how I envisioned this based on the conversation above:
> 
> <img width="674" alt="mapitcta" src="https://cloud.githubusercontent.com/assets/3011211/9672197/44024278-524d-11e5-93c9-477efabff83f.png">
> 
> However, I would note that it seems much more likely that the domain is actually registered by someone else than this is a true "I already own it" scenario -- in which case, this feels like it's potentially giving too much visual weight, so I need to try a few treatment alternatives.
> 
> In the other scenario, where a user starts from trying to map a domain, it seems much more likely they would really want to register the domain. I agree we should suppress the error and focus on the domain suggestion here (which could use some design cleanup as well). 

Comment from @folletto 

> Agreed on all your points. :)
> 
> I feel the mockup above aligns to the discussion well, and I understand also the concern on the likelihood of ownership. Feels the right direction to me. :)

**Comment by klimeryk** [comment]
This seems like a well deserved overhaul of this part of domains. Linking to #2326, #859 and #2442 as they could probably be fixed as part of these changes.

**Comment by klimeryk** [comment]
@breezyskies: pinging again with same question above (https://github.com/Automattic/wp-calypso/issues/2443#issuecomment-173400297) :bow:

**Comment by breezyskies** [comment]
Sorry @klimeryk, not sure how I missed this one. I agree that a larger overhaul of domain mapping is needed, but we won't likely get to design for this in Q2 due to other priorities. 

I would also note that these discussions are a bit old and some things have changed since (for example, we did see a lot of reports of mapped domains that the user didn't really own). I would recommend closing this issue and opening separate issues for any smaller display fix issues noted here (if they still remain).

**Comment by klimeryk** [comment]
No problem :) Thanks for the update and a great suggestion - I'll close this one. There are two related issues open (#2326 and #859), but they don't really need designer input, just some developer love :wink:
