### ISSUE TITLE
Domains: The "map it" button in NUX stops working

### ISSUE THREAD

**Issue by hambai** [Automattic/wp-calypso#24432]
In certain scenarious (logged out NUX flow) the "map it" button in NUX stops working. I tracked the issue to the `getMapDomainUrl` function which doesn't expect the `/en` suffix to the URL.

#### Steps to reproduce
1. Open https://wordpress.com/start as logged out user (try incognito)
2. Fill the form in Step 1 and Continue
3. Click on thee back button at the bottom (notice that the URL is now /start/en)
4. Then click Continue again
5. Click on I already own a domain (the transfer screen will open)
6. Click on the "map it" button

#### What I expected

To go to the mapping step screen

#### What happened instead

Nothing, looks like I'm stuck at the transfer screen

#### Browser / OS version

Mac OS 10.13.4/Chrome 66.0.3359.117 but I guess it happens on every browser

**Comment by rachelmcr** [comment]
I confirmed the issue with the steps above. I also confirmed that the mapping option is broken for localized signup flows, without navigating back during signup, as with these steps:

1. Open https://wordpress.com/start/about/es as logged out user.
2. Fill the form in Step 1 and Continue.
3. Click on "¿Ya tienes tu propio dominio?" (the transfer screen will open).
4. Click on "conéctalo manualmente" (to choose the mapping option).

**Comment by jsnmoon** [comment]
@hambai and @rachelmcr, I tried to reproduce using the above steps but failed to replicate the bug. I have a hunch that #25173 might have fixed this issue; can you help me confirm this? 

If the bug still persists, I'd be at a bit of a loss since I followed the reproduction steps to the T...

**Comment by hambai** [comment]
Actually it's this PR that fixed the issue - https://github.com/Automattic/wp-calypso/pull/25162

Also the current issue is duplicate of https://github.com/Automattic/wp-calypso/issues/25114
