### ISSUE TITLE
Simple Payments: The modal only shows last 20 buttons.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#24436]
A customer reported issue. They have more than 20 buttons on their site, but they can only see the last 20 buttons in the modal.

I was able to replicate the issue. I've created 21 buttons, and note that button number 1 is missing, and the total count of the button is stuck at 20.

<img width="995" alt="screen shot 2018-04-24 at 16 19 28" src="https://user-images.githubusercontent.com/908665/39196968-4ff91b20-47db-11e8-8aa4-ff3688849b9e.png">

Related: #20411

cc @galakhyati

**Comment by galakhyati** [comment]
Another user reported this issue. They had approx 40 products created and only last 20 are displayed.

Live chat: #4762335-hc

**Comment by sashastone** [comment]
Adding another report to this issue: 1511295-zen

When user adds more than 20 items on their page https://lucecreativedesign.wordpress.com/?page_id=584, the one furthest down disappears. 

I confirmed this issue on a test page, same result as the original report.

**Comment by simison** [comment]
FYI @rodrigoi

**Comment by ChrissiePollock** [comment]
Any updates on this? The customer is back inquiring on #1528334-zen.

**Comment by flootr** [comment]
On a quick glance it seems like the reason for this is that the API byq default only returns 20 items and there's no functionality to fetch more items in case there are some.

**Comment by ktyfuller604** [comment]
Adding a new report - #8345598-hc

**Comment by selectedselections** [comment]
Adding another new report of this issue #11405405-hc

**Comment by jessestu** [comment]
@flootr @rodrigoi @simison I don't see much activity on this thread. Is there anything we can do to get more eyes on it?

**Comment by simison** [comment]
Calypso classic editor is going away soon and replaced with Gutenberg editor and with that, this feature (a list to choose simple payments buttons) will be no more.

cc @Automattic/lannister for priority of something like this considering the above.

**Comment by retrofox** [comment]
Pretty sure it happens because of when it requests the buttons (posts with a custom post type) the limits is `20` as default. A not perfect but quick solution is passing the posts number as a request parameter ([**number** field](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/#apidoc-query)), increasing it to 50, 100, or whatever we decide. The ideal solution is to paginate the list, imo.

**Comment by jessestu** [comment]
Thank you so much for getting this fixed, @retrofox !!!! (please excuse the generous use of exclamation points)
