### ISSUE TITLE
Checkout: Allow paying with credits or a card when credits available

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#24448]
Currently we only allow customers to pay with credits if they have enough to cover their purchase. In testing this can create complicated circumstances and gives Automatticians an unrealistic purchase testing experience—especially when the plan is renewed. 

**Currently:**
![image](https://user-images.githubusercontent.com/437258/39212075-a047c720-47db-11e8-8c9a-17d1b9c6dc32.png)

It would be nice if we could change the checkout screen to look something like this if you have credits available:

![image](https://user-images.githubusercontent.com/437258/39212026-77e7acbe-47db-11e8-8022-3a5fffb00403.png)

* Customers and a12s could decide how to pay
* In testing we could get a more realistic experience without having to change how many credits we have
* We could reuse the UI for selecting a multi-year subscription

**Comment by folletto** [comment]
General concept: I agree completely. It's a solid suggestion for all the reasons you mention.

Two small bits:

1. Is the design above meant to be built as is? i.e. should I feedback on that?
2. Maybe it's something already built in and I'm not aware of: is there any reason for the two options to be side by side instead than one below the other?

**Comment by rickybanister** [comment]
I did them side by side to mirror the design of multi-year plan purchases, nothing more. I figured if we could re-use css it would help, but I have no preference on the design.

**Comment by rickybanister** [comment]
Like this:

![image](https://user-images.githubusercontent.com/437258/39438675-f9ef21ec-4c72-11e8-81da-6f921784a077.png)

**Comment by rickybanister** [comment]
I actually forgot about the paypal option. It might make sense to rethink this navigation to include credits:

![image](https://user-images.githubusercontent.com/437258/39438755-2ef78ea6-4c73-11e8-97e0-c5c345c71560.png)

**Comment by folletto** [comment]
>  I actually forgot about the paypal option. It might make sense to rethink this navigation to include credits:

This seems a nice way to handle it. Thanks for the clarification and brainstorming :)

**Comment by rickybanister** [comment]
This is still relevant. Allowing the option to do either would improve our internal testing and increase reliability.

**Comment by rickybanister** [comment]
@rralian @fditrapani 

I opened this issue a long time ago as an attempt to improve our internal empathy for checkout issues. With the new checkout flow coming I mentioned this to Filippo, but wanted to make sure this issue was noted (mostly triggered by stalebot closing it). 

It would be great if applying credits or paying with card was optional, or there was an a12-only solution to allow paying by credit card or credits, OR possibly allowing a testing credit card number or similar.

**Comment by fditrapani** [comment]
From a design perspective, we should be able to accommodate for this easily. cc'ing @sirbrillig and @nbloomf from the tech perspective to see what's involved.

**Comment by sirbrillig** [comment]
We chatted about this in our checkout redesign project meeting today. This should definitely be doable. We've got it tracked on [our project board](https://github.com/Automattic/wp-calypso/projects/89).

**Comment by sirbrillig** [comment]
This should be fixed by #38727 when composite-checkout replaces Calypso checkout.
