### ISSUE TITLE
DevDocs Playground: the editor accepts non-plain text

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#24445]
The playground seems to accept not plain text?

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/action-card
2. copy the text in the white code block
3. paste it in the playground editor
4. notice how the while background style is also pasted

#### Screenshot / Video

![screen shot 2018-04-24 at 2 03 51 pm](https://user-images.githubusercontent.com/618551/39208490-c91e771a-47c8-11e8-92d4-0c39503d9c76.png)

**Comment by scruffian** [comment]
I can't replicate this. Do you get any errors?
