### ISSUE TITLE
Domain Management: suggested improvements for form validation on email forwarding

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2445]
Raised by @ranh 

On the email forwarding page at `/domains/manage/:domain/email-forwarding/:site`

- Forms do not validate before submitting, making it harder to correct errors.
- Error messages are shown at the top of the screen, rather than next to the field where the error is, making it harder to correct errors.

![screen shot 2016-01-14 at 17 14 39](https://cloud.githubusercontent.com/assets/1119271/12339303/5bfa1a92-bae2-11e5-994e-2753f38c466c.png)

Also see 7666-wpcom

**Comment by alexjgustafson** [comment]
Seems like the issues in the original post have been addressed, but I had an instance in #377835-chat where some more precise messaging, or a change in validation, would be helpful. If any whitespace is added at the beginning or end of the "will be forwarded to" email address it throws an error:

![emailforwarding](https://cloud.githubusercontent.com/assets/933450/15408493/776f2f24-1dde-11e6-80ab-4437f3cf54c2.gif)

It's not obvious to someone unfamiliar with form validation why this would be an 'invalid destination address.' They don't see the whitespace, only their email address. Could we scrape the whitespace automatically upon submit instead? Or change the message to something more specific regarding whitespace?

**Comment by klimeryk** [comment]
Thanks for brining this to our attention, @alexjgustafson :+1: Indeed, the problems from the original post seem to have been fixed by #4257.
I'll see what I can do about the whitespace - it shouldn't be a big change and will allow us to close this ;)
