### ISSUE TITLE
Me: change "Sign out" to "Log out"

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#24451]
March 2017 we settled on this terminology for Calypso: 

* Sign up — registration
* Log in — access the account

There were many good reasons, as a summary:

1. Two distinctive terms (i.e. "Sign up" and "Sign in" are confusing)
2. They can both be user as verbs and adjectives (i.e. "Sign up" as verb, "Signup" as adjective)

See p6qnuF-4Fs-p2 for more details.

As such, the mirror action to exit should be "Log out". Here's a mock of how it should be:

<img width="270" alt="screen shot 2018-04-24 at 18 09 34" src="https://user-images.githubusercontent.com/4389/39216770-009f0ac0-47eb-11e8-9cd3-e0674ec279f5.png">

Note: iOS is already using "Log out".

**Comment by alisterscott** [comment]
Fixed by https://github.com/Automattic/wp-calypso/issues/24451
