### ISSUE TITLE
Checkout: Privacy Protection is offered even if it's in the cart

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2447]
Raised by @umurkontaci 

If you add a domain and a privacy protection for that domain to the cart, then refresh the page or navigate away and come back; you'll see privacy protection offer again.

We should not offer it if the user has privacy protection for all domains in their cart.

Comment from @kriskarkoski 

> Confirmed this is still the current behavior as of 01-Oct-2015. Here's what it looks like:
> 
> ![0a3659fe-684f-11e5-82bd-ed6c292d3240](https://cloud.githubusercontent.com/assets/1119271/12339802/07394958-bae5-11e5-85be-11def2b4ae2c.png)
> 
> However, the checkout still works as expected, clicking Add Privacy Protection does not duplicate it and simply advances the checkout, while Publish My Information displays the warning modal and the declining removes it from the cart

**Comment by peterbutler** [comment]
I'm not sure this _isn't_ desired behavior.

The alternative would be to not show this if privacy is in the cart, I suppose - but if the user decides they don't want privacy, they've got to figure out they can remove it from the cart in the sidebar.  I feel like maintaining the existing layout gives a more explicit and consistent experience, even if it is redundant.

With all that said, I'd probably rather defer to @breezyskies (or another designer).  Thoughts?

**Comment by breezyskies** [comment]
The bigger issue for me is that this happens even if you refresh the checkout page, but I would generally argue that the user doesn't need to see this step again, assuming they've already added Privacy. 

> they've got to figure out they can remove it from the cart in the sidebar

I think this part is okay and more straightforward than changing to no privacy via the page.
