### ISSUE TITLE
Domain Search: cannot map a domain purchased elsewhere if domain registration for the same TLD is not supported at WordPress.com

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2448]
Raised by @umurkontaci 

There's no way to map a domain that you own if we don't support registering in that TLD.

For example, I own `umur.io` and I can't map it.

![image](https://cloud.githubusercontent.com/assets/991022/9661917/9e32d70e-5265-11e5-876d-24c2bed70a97.png)

We should allow them to map those domains as well.

Comment from @drewblaisdell 

> It is still possible to map a TLD that can't be registered from `/domains/add/mapping/:site`. I think the issue here is that we aren't including a mapping CTA in the notice.

**Comment by klimeryk** [comment]
Closing this in favour of #2443. Especially since we do allow such mappings (as noted above), it's just not obvious from the current flow (which #2443 will try to address).
