### ISSUE TITLE
Domain Management: back button breaks after changing Primary Domain

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2450]
Raised by @umurkontaci 

Steps to reproduce:

1. Go to https://wordpress.com/domains/manage
1. Select a site with a custom domain as the primary domain that also has an additional custom domain
1. Click on a domain that is not currently the primary domain
1. Click Make Primary
1. Click Update Primary Domain
1. Click the back button in the browser

<strong>Result:</strong> when we change the Primary Domain, all the previous URLs become invalid since we are using primary domain slug in the URLs. As a consequence, back button breaks once the user changes their Primary Domain.

It's practically close to impossible fix all the previous URLs, but we can at least show something user friendly in the back button.

/cc: @rads @gziolo

**Comment by hoverduck** [comment]
05May16 Bug Scrub

Confirmed this is still an issue.  After executing the repro steps in the original post, clicking the Back button once has no affect, but clicking the second time takes me to /domains/manage where I'm prompted to (re)select a site.

**Comment by umurkontaci** [comment]
Closing this as wontfix.
