### ISSUE TITLE
Remove feature flags that are no longer necessary

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2451]
Raised by @stephanethomas 

We should remove [flags](https://github.com/Automattic/wp-calypso/blob/master/config/README.md#feature-flags) for features that have been deployed. This means updating [configuration files](https://github.com/Automattic/wp-calypso/tree/master/config) for each environment as well as removing [feature gates](https://github.com/Automattic/wp-calypso/blob/0c382004860313e76dd946fcc90e09b72c90a6b3/client/my-sites/plans/index.js#L15) in the code, for at least the following features:

* `manage/plans`
* `me/billing-history`
* `upgrades/domain-search`
* `upgrades/checkout`

Comment from @nb 

> I like that, even when deployed, we can choose to disable features. Especially with the store, that seems > very handy – we’ve had to do it few times in the past (outages).
> 
> That said, it would make sense to consolidate some of those.

**Comment by gziolo** [comment]
I agree with @nb, taking into account that we need to support also desktop apps, those flags are extremely useful. We just need to improve their setup.
This is related to #291.

**Comment by gziolo** [comment]
Closing this issue in favor of #291.
