### ISSUE TITLE
Signup: Back link on Plans page goes to first step in signup rather than previous step

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#24547]
(This may be the intended behavior, but I found it jarring, so I wanted to open a ticket to get others' thoughts.)

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/start/
2. Go through signup until you get to the Plans page.
3. Click Back at the bottom of the Plans page.
4. Note you're back at step 1, rather than the previous step (Domains).

#### What I expected

To be taken back to the previous step in the process, which is Domains.

#### What happened instead

I was taken to the very first step of the signup process. The information is still filled in, but it makes for an extra click if the intent is to fix a typo with the domain name you've picked (for example).

**Comment by jsnmoon** [comment]
I'll look into this.
