### ISSUE TITLE
Reader: show the total number of followers (WP.com + Email followers)

### ISSUE THREAD

**Issue by treibalen** [Automattic/wp-calypso#24544]
This is a feature request from a customer:

#### Steps to reproduce
- Go to https://wordpress.com/read/feeds/79718693/posts/1835392575

![](http://cld.wthms.co/kDRJ1w+)

#### What I expected
The user expects to see _the total number of followers_ (WP.com + Email followers) 
Another idea would be to have a setting in Calypso to control if you want to show WordPress.com followers, Email followers or total.

#### What happened instead
The user sees the number of WordPress.com followers

#### Browser / OS version
Not relevant

HappyChat: 3047319-hc

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
