### ISSUE TITLE
Translations appear as [object Object] when community translator is enabled

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#2455]
Reported by @jenial [here](https://github.com/Automattic/community-translator/issues/2) (thanks!) the translator related '[object Object]' bug is back:

![](https://cloud.githubusercontent.com/assets/7637835/12325375/1a567260-baca-11e5-9a7a-6c187acdc9cd.jpg)

We've been [overriding the toString() method on `ReactElement`s](https://github.com/Automattic/wp-calypso/blob/1fbab15b665978906561abc2252f4f7e31c87c47/client/lib/translator-jumpstart/index.js#L55), but in React 0.14 ReactElements [became plain old objects](https://github.com/facebook/react/commit/750338ef4794af164d452d7560cb97a558c56d3c#diff-55695b0adf2e9955d50160f0aa0cd234L235).

When we [moved to 0.14](https://github.com/Automattic/wp-calypso/pull/1498) our hack broke :(

**Comment by akirk** [comment]
Forgive my ignorance, but now that it is a plain object, wouldn't it now just work if we modified `ReactElement.toString` instead of `ReactElement.prototype.toString`?

**Comment by akirk** [comment]
This has now been fixed for me.
