### ISSUE TITLE
Editor: incorrect animation when adding/removing categories/tags

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#24577]
In the editor, when a post goes from no categories/tags to 1+ categories/tags, or from 1+ categories/tags to none, there is an unnecessary and disruptive animation that causes a content "jump":

<img src="https://user-images.githubusercontent.com/227022/39453525-dc297f26-4c9b-11e8-9720-b053c6a5b54f.gif" width="286">

**Comment by nylen** [comment]
@oscarssanchez: This text display should remain, but the screen should not jump as the text appears and disappears.

**Comment by SnGrimes** [comment]
Is anyone assigned to or is working on this issue?

**Comment by nylen** [comment]
@SnGrimes: please feel free to submit a pull request and ping me (@nylen) on it. At the moment there is no one assigned to this issue.

**Comment by Dec0y-jb** [comment]
@SnGrimes - if you're interested you can take this one. I don't mind doing it either. I followed it a few days ago but haven't started anything yet.

**Comment by SnGrimes** [comment]
@nylen Thank you. I will work on this as soon as I can get calypso installed on my Win7 machine. I have never run into an install issue like this before.

**Comment by Dec0y-jb** [comment]
I'm actually going to move this into /editor-categories-tags/style.scss rather than modify the actual component.

**Comment by Dec0y-jb** [comment]
Submitted PR #25200 - much better this way. Please let me know what you think.

Joe
