### ISSUE TITLE
Signup: Business flow shows invalid product in cart when adding domain

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#24579]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/business
2. Proceed through signup making sure you also **add a domain**
3. Get to cart stage

#### What I expected

Cart shows only valid products

#### What happened instead

The cart shows an invalid product and then removes it either with or without an error message - in this case it leaves premium when business was set in the flow

#### Browser / OS version

Chrome on macOS

#### Screenshot / Video

![create premium flow](https://user-images.githubusercontent.com/128826/39459519-71838668-4d3f-11e8-884c-0a9cb9d610e5.gif)

#### Context / Source

 #automated-testing

**Comment by hambai** [comment]
This was fixed by reverting https://github.com/Automattic/wp-calypso/pull/23104

**Comment by saouderkirk** [comment]
@alisterscott were any other tests / flows showing this problem, or only Business Plan + Domain starting from /business ?

**Comment by alisterscott** [comment]
I ran through this again on `/start/business`

First the cart loads with premium (priced) and business (with no price)

<img width="1162" alt="screen shot 2018-05-09 at 10 24 53 am" src="https://user-images.githubusercontent.com/128826/39789477-5cd9fb68-5373-11e8-88a6-0c446375253d.png">

Then premium is removed, and business is priced:

<img width="1162" alt="screen shot 2018-05-09 at 10 25 02 am" src="https://user-images.githubusercontent.com/128826/39789491-77b1d686-5373-11e8-873c-a8e082f4f723.png">

**Comment by alisterscott** [comment]
@saouderkirk actually I did some more testing and these are the results of when we see the extra product in the cart (which then disappears):

| Flow / Products | Outcome | Behaviour |
| /start/business + .live domain | ❌ | See four products including Premium Annual which is removed |
| /start/business + .com domain | ❌| See four products including Premium Annual which is removed |
| /start/business (no domain) | ✅| Only one product |
| /start/premium + .live domain |  ❌ | See four products including Premium Annual and Premium which is removed |
| /start/premium (no domain) | ✅ | Only one product |
| /start/personal + .live domain |  ❌ | See four products including Premium Annual which is removed |
| /start/personal (no domain) | ✅ | Only one product |

So it looks like any combo of plan + domain is problematic

If you look at what happens when you try /start/premium you can see two premium plans, one shows "Annual" and the other does not:

<img width="1156" alt="screen shot 2018-05-09 at 10 34 13 am" src="https://user-images.githubusercontent.com/128826/39789840-aaf16686-5375-11e8-944e-5117e50df907.png">

This then becomes just the annual one:

<img width="1160" alt="screen shot 2018-05-09 at 10 34 19 am" src="https://user-images.githubusercontent.com/128826/39789844-b2a3c55e-5375-11e8-9468-13df46eadd11.png">

I hope this helps

**Comment by alisterscott** [comment]
Confirming this is still an issue
