### ISSUE TITLE
Simple Payments: Link from email to Guided Tour

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#24589]
## Scenario

A user receives an email suggesting they can earn money with their WP site.
They're intrigued by the opportunity but they don't know where to start.

cc @cburton4 

![1](https://user-images.githubusercontent.com/2070010/39476466-4f4c7628-4d5c-11e8-8dac-aca5043806b2.png)

## Steps

- The user receives the SP email (p9Jlb4-7p-p2).
- They click on its CTA.
- The CTA landing page checks whether they are on desktop or on mobile, and directs them:
  - On desktop, to `/stats/day/{site}?tour={simplePaymentsTourName}` (e.g. `/stats/day/example.wordpress.com?tour=simplePayments`) that will start the SP Guided Tour (p9Jlb4-6x-p2).
  - On mobile, to https://en.support.wordpress.com/simple-payments/.

### Desktop/Mobile Differences

Guided Tours currently only work on desktop.
The initial plan was to implement them on mobile too, but in this particular case it would be excessively tricky because the first tour step is tied to a sidebar item which is hidden by default on mobile, and there is no infrastructure in place to toggle it on page load.
For this reason the CTA will open the SP support page on mobile.

### Landing Route and Tours

On desktop, the CTA opens the default Stats route, with a `tour` query parameter, but what about the site fragment (if any)?

Does it make sense to automatically open the user's main site?
What would happen at the Tour if they switched site to another biz site?
Would it disappear for good?
And if it doesn't disappear, what if they switched to a non-biz site instead?

Should we instead use the all sites view, which, when clicking on the Page button, opens the site selector?
Can GT work when skipping a page? (e.g. Stats has the 1st step -> site selector has no step; Page Editor has the remaining steps)

**Comment by jancavan** [comment]
> Does it make sense to automatically open the user's main site?

I think it makes sense to drop them onto their primary site.

> What would happen at the Tour if they switched site to another biz site?
Would it disappear for good?

Would it be possible to make the GT available on those other sites as well? But if they dismiss it or have completed the tour, we should probably also dismiss it everywhere else.

> Should we instead use the all sites view, which, when clicking on the Page button, opens the site selector?

My concern is dropping them into the Site Picker might result in confusion (ie Why am I here and what exactly do you want me to do?). For it to make sense, we'd have to add an additional step saying "Pick a site" or something similar.

> Can GT work when skipping a page? (e.g. Stats has the 1st step -> site selector has no step; Page Editor has the remaining steps)

You mean, for example, if they skip Stats (where the first step is) and headed over to Comments? I think we should still keep the tooltip floating on there unless they dismiss it (at least for Desktop).

@iamtakashi Do you know how we handled this in the previous guided tour?

**Comment by Copons** [comment]
Thank you @jancavan!

> Would it be possible to make the GT available on those other sites as well?

It's definitely possible!
Only issue I can find is that the last step of the tour is activated upon insertion of the SP button.
Non-biz sites can't insert the SP button because when they open the dialog they just get an upgrade nudge.
Maybe we can work around this by showing the last step of the tour whenever the dialog is closed, no matter why.

> My concern is dropping them into the Site Picker

Stats (and Pages, amongst other sections) has an "All Sites" view (`/stats/day`), so the email link could drop them into that view (e.g. `/stats/day?tour=simplePayments`), with the tour pointing to the Add Page button.
Clicking on Add Page in an All Sites button would first open the Site Selector instead of directly the Editor (because of course a page can only belong to one site).

I think the flow [All Sites -> Site Selector -> Page Editor] is clear enough, but it's definitely better to just open Calypso on the main site.

> You mean, for example, if they skip Stats (where the first step is) and headed over to Comments? I think we should still keep the tooltip floating on there unless they dismiss it (at least for Desktop).

Oh, I was really unclear on that. It was more a note for myself to double check what GT can actually do, and what would happen if they follow the intended flow (stats -> page editor), but passing through one or more pages without any tour steps (e.g. stats -> site selector -> page editor).

I'll also double check what would happen if they leave the intended flow (e.g. stats -> comments), and if we can keep the tour visible until dismissed.
