### ISSUE TITLE
Media Library: modify the component for Simple Payments use case

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#24590]
Related issue: https://github.com/Automattic/wp-calypso/issues/24595

Opening up the Media Library component now will always display the following categories as tabs at the top: All, Images, Documents, Videos, Audio. In case of Simple Payments Button we only want to upload an image, so there should be an option to override the default behavior to remove the tabs and only show images by default. The existing tab space should be replaced with the Search bar component. 

![simple-payments-media-library1](https://user-images.githubusercontent.com/1182160/39477201-d518e0e6-4d5e-11e8-9493-5064bceec6a1.png)

For more details please refer to p9Jlb4-7j-p2.

**Comment by gwwar** [comment]
Should be fixed by #24620
