### ISSUE TITLE
Signup: HTML visible in error message for suspended users

### ISSUE THREAD

**Issue by davidwatkis** [Automattic/wp-calypso#246]
#### What I expected to happen

When a user who owns a suspended site attempts to create a new blog, the expected behavior is that they are greeted with the following error message upon choosing their new URL:

> Oops! Sorry an error has occurred. Please click here to contact us so that we can fix it. Please remember that you have to provide the full, complete Blog URL, otherwise we can not fix it

'Click here' links them to, http://wordpress.com/error-report/?url=496@example.wordpress.com where they can get in touch with the TOS team and discuss the situation.
#### What actually happened

When testing this flow recently some of the HTML in the error message was displayed like so:

![Image of error message](https://cldup.com/8rMhvSckp0-3000x3000.png)

In addition to the suboptimal appearance, users are unable to navigate directly to the form and would be forced to copy the URL it into the browser.
#### Steps to repeat
1. Suspend a WordPress.com blog owned by a non-super admin account.
2. While unproxied, sign into the regular user account which owns the now flagged blog.
3. Add New WordPress, select a theme, select a plan.
4. Choose a new URL.

**Comment by fabianapsimoes** [comment]
Duplicate of 11163-gh-calypso-pre-oss. Closing this one.

**Comment by davidwatkis** [comment]
Just noting that his issue has been eclipsed by/combined with the bugs in the overall Calypso suspension experience:

https://calypsop2.wordpress.com/2017/08/09/suspensions-in-calypso-update/

Specifically, users who currently own suspended blogs and try to create _new_ blogs are met with a loading screen which never resolves. As such, they never make it to this error message of which the HTML may still be visible.

So, I'm leaving this closed in favor of that more updated calypsop2 overview.
