### ISSUE TITLE
Checkout: add support for hosted paywall

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#24615]
We're going to work with a new payment provider, using their hosted paywall service, and we need to support that in `SecurePaymentForm`.

1. The paywall can contain multiple payment methods. It can either be the only method we show to the end user, or just one of the tabs
2. On loading, it will need to request the iframe URL and additional parameters (currently two strings: `payload` encoded object, and `signature`) from the REST API. This is similar to the `paygate-configuration` step, but it needs to happen automatically before the iframe can be loaded
3. The paywall sends JavaScript window.postMessage event containing a stringified JSON object. We'll need to handle those messages to react to the payment status (completed, error, canceled etc)
4. Our TOS (`<TermsOfService>`) needs to appear above the iframe

**Comment by yoavf** [comment]
> currently two strings: payload encoded object, and signature

This might need to be a part of the cart object, since it depends on the cart contents (total_cost/currency etc).

**Comment by ramonjd** [comment]
Understood. Will await further details.

> , but it needs to happen automatically before the iframe can be loaded

Do you think this step supports a case to split payment screens as discussed?

**Comment by yoavf** [comment]
The transaction endpoint request should happen when we receive the  following postMessage
` {
    "name": "PURCHASE_STATUS",
    "submitted": true
  } `  

It will return an order_id - which can be used to route to `'/checkout/thank-you/:site/pending/:orderId'` - see `checkoutPendingRoutes`
