### ISSUE TITLE
Domain Management: email address form should have a unified design

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2462]
When adding an email address or forward, the same form design should be used each time. 

Here is the design:

<img width="678" alt="google-apps-add-email-for-existing-domain" src="https://cloud.githubusercontent.com/assets/1119271/12352220/1ace5b80-bb52-11e5-9b09-19ad4e2096b1.png">

This is the design for cases where it's possible to select from more than one domain:

<img width="675" alt="screen shot 2015-09-17 at 14 52 26 pm" src="https://cloud.githubusercontent.com/assets/1119271/12352341/2d9f3062-bb53-11e5-8ae0-7e477fcdf8c9.png">

The form is correct for:

* Signing up for Google Apps for a domain previously purchased on WordPress.com<br>**Domains > :domain > Email > Add Google Apps** ([screenshot](https://cloud.githubusercontent.com/assets/1119271/12353025/e9981fea-bb58-11e5-8a3a-7c599c6e082e.png))
* Adding more accounts to Google Apps for a specific domain<br>**Domains > :domain > Email > Add Google Apps User** ([screenshot](https://cloud.githubusercontent.com/assets/1119271/12352572/15028908-bb55-11e5-9606-3d925d5fdba2.png))
* Adding Google Apps from the main Email tab<br>**Domains > Email > Add Google Apps** ([screenshot](https://cloud.githubusercontent.com/assets/1119271/12352562/01422392-bb55-11e5-889d-2f07569f154c.png))
1. Creating an email forward<br>**Domains > :domain > Email > Email Forwarding** ([screenshot](https://cloud.githubusercontent.com/assets/1119271/12352629/aeafcde0-bb55-11e5-8386-ba237ccc6851.png))

This one needs to be updated: 

1. Signing up for Google Apps while adding a domain<br>**Domains > Add Domain > Add > Add Email** ([screenshot](https://cloud.githubusercontent.com/assets/1119271/12352650/d7622bca-bb55-11e5-8f49-548b0c9e5161.png))

Comment from @breezyskies 

> :+1: Although on the last one, we should replace that form with the [new version](https://cloudup.com/cM9AVGonwVn).

Comment form @ranh 

> For last one, you mean adding google apps while adding a domain? The dropdown in the screenshot won't be necessary there, since it would be expected that the domain to add custom emails for would be the domain currently being registered. Showing a choice for other existing domains would be very confusing.

Comment from @breezyskies 

> We're trying to move towards better allowing multiple domain purchases. The Google Apps step in this flow would only be shown once (after x domains are added to cart), with the dropdown showing all of the domains they have in their cart. If there is only one domain in their cart, it could show the static suffix field.

/hat tip @ranh for the original report

**Comment by umurkontaci** [comment]
How it looks on checkout right now:

![image](https://cloud.githubusercontent.com/assets/991022/13592636/fb57ea16-e4a8-11e5-8a24-9dfe0d654e2e.png)

**Comment by klimeryk** [comment]
Fixed by #6389.
