### ISSUE TITLE
Domains: NUX breaks if there is a message in the state and you refresh

### ISSUE THREAD

**Issue by hambai** [Automattic/wp-calypso#24626]
This bug is particularly nasty because a refresh doesn't help and clicking on the back button also doesn't help.

I'm not 100% sure why this happens but it seems the issue is because we save the state including the last availability message in it. I believe the issue is because the state is saved somewhere (including the last availability message). And when the state is restored on reload the message is not restored fully (or correctly).

#### Steps to reproduce
1. Starting at URL: /start (logged or not logged user)
2. Fill the first form
3. Enter a domain name that is already registered and mapped with wordpress.com
4. You should see a notice - `yourdomain.com is already connected to a WordPress.com site` 
5. Now refresh your browser - you'll end up in a blank screen. If you check your console you'll see a warning "Warning: Failed prop type: Invalid prop `text` supplied to `Notice`." and an error "Uncaught Error: Objects are not valid as a React child (found: object with keys {type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead." and then a bunch of other errors.

#### What I expected

I expected to see my last search and the suggestion results.

#### What happened instead

A blank screen and a bunch of errors

#### Browser / OS version

MacOS 10.13.4 / Chrome 66.0.3359.117 (Official Build) (64-bit)

**Comment by ramonjd** [comment]
I did some testing, and its borking at the interpolation of [elements in the calls to](https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/registration/availability-messages.js) `translate()`.

I'll get a PR up soon. 👍

**Comment by ramonjd** [comment]
Closed by #24720
