### ISSUE TITLE
Mac app: Unread status indicator doesn't go away

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#2463]
I installed the WordPress.com desktop app (yay!) but the unread indicator won't turn off. I've double checked my Notifications within the app and it says I'm "All caught up".

<img width="151" alt="screen shot 2016-01-15 at 12 54 25" src="https://cloud.githubusercontent.com/assets/3073557/12352577/7aad81d6-bb87-11e5-85c7-a5e73c62ce96.png">
![screen shot 2016-01-15 at 12 54 30](https://cloud.githubusercontent.com/assets/3073557/12352581/80d070a0-bb87-11e5-904b-aaab377c5321.png)

**Comment by designsimply** [comment]
Thanks for reporting this! I've moved it to  since the problem is specifically tied to the app.
