### ISSUE TITLE
Customizer: "I'll try Storefront" button broken in onboarding steps

### ISSUE THREAD

**Issue by kyleaparker** [Automattic/wp-calypso#24663]
#### Steps to reproduce
When settting up Store for the first time:
1. Starting at URL: https://wordpress.com/store
2. Click the **View and customize** step to launch customizer <img width="1231" alt="store kyleas test site wordpress com 2018-05-03 15-36-21" src="https://user-images.githubusercontent.com/712873/39598800-c2545a8c-4ee7-11e8-9efc-bcc9e03e6315.png">
3. In the **Customize Your Store** helper click on **I'll try Storefront**: <img width="1271" alt="customize kyleas test site 2018-05-03 15-37-05" src="https://user-images.githubusercontent.com/712873/39598833-dcf9014e-4ee7-11e8-81f3-ec890bf65630.png">

#### What I expected

I expected the Storefront theme to activate

#### What happened instead

The **I'll try Storefront** link doesn't go anywhere

#### Browser / OS version

Chrome Version 65.0.3325.181

#### Screenshot / Video

Video of the issue: https://monosnap.com/file/VZegwVYrMzTeyQQCbJgsP4b7wZxY9A

**Comment by timmyc** [comment]
@kyleaparker thanks for the bug report! The issue - while marked fixed a few days ago - was actually fixed today when the code was deployed to biz-plan sites.

**Comment by kyleaparker** [comment]
@timmyc thanks for fixing this! Is there an easy way to change the orphan here:

<img width="1506" alt="40336373-0dcfa464-5d1e-11e8-8778-3db12b23bdd4 png 1544x612 2018-05-30 11-01-29" src="https://user-images.githubusercontent.com/712873/40728751-d4e6ceac-63f8-11e8-8976-c9e67936e790.png">

To this:

<img width="720" alt="customize kyleas test site 2018-05-30 11-03-02" src="https://user-images.githubusercontent.com/712873/40728860-0f6d9c54-63f9-11e8-815b-7712d4d3681f.png">

I can create a new issue for this if it's easier :)
