### ISSUE TITLE
Republicize: The UI misrepresents the social media accounts eligible

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#24696]
Republicize will re-send social media posts to all accounts that _the post is eligible to be sent out to_ which is determined by the post author, not the current user republicizing it (as it is written on the wp.com backend).

This leads to a really confusion and wrong experience for customers attempting to republicize a post by someone else.

Steps to duplicate:
1. Setup a site (seen on a Jetpack site, but I don't have reason to think it wouldn't be true on wp.com)
2. Create two accounts and properly connect them if using Jetpack.
3. With Account A, setup Publicize connections.
4. With Account B, have no publicize connections. Author and publish a post.
5. With Account A, login to Calypso and attempt to share the post.
6. See the UI indicate Account A's publicize accounts will be used.
7. Initiate Republicize.

Expected:
Based on the UI, Account A's social media accounts will have an automated post.

Actual:
Nothing is shared to social media.

(Internal reference: See the attached issue for a specific case)

**Comment by aheckler** [comment]
This came up in 1848958-zen.
