### ISSUE TITLE
Need help with nginx configure for Calypso

### ISSUE THREAD

**Issue by k1tzu** [Automattic/wp-calypso#24700]
#### What I expected
```
git clone on the server
cd wp-calypso && yarn start
=> nginx setting proxy_pass to localhost:3000
=> restart nginx
=> open in browser and viola it just works
```

#### What happened instead
```
added calypso.localhost to /etc/hosts
downgraded nodejs from 10.0 to 8.11.1 LTS (there's no package for 8.11.0 on arch linux)
yarn start successfully
```
Opened in browser and just W is visible just like this https://github.com/Automattic/wp-calypso/issues/13052#issuecomment-293996870
Dev console is silent, logs showing:
```
Ready! You can load http://calypso.localhost:3000/ now. Have fun!
GET /calypso/style-debug.css?v=bef50f1142 200 22.574 ms - 1212355
```
and nginx logs
```
admin [06/May/2018:13:42:03 +0000] "GET /calypso/style-debug.css?v=bef50f1142 HTTP/1.1" 200 181775 "https://some.site.url:888/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
```

#### Browser / OS version
Arch Linux 4.16.3-1-ARCH
Browsers Safari, Chrome

#### Context / Source
nginx config
```
upstream calypso {
    server calypso.localhost:3000;
    keepalive 1;
}

server {
    listen 888 ssl;

    server_name some.site.url;
    root /usr/share/nginx/wp-calypso;

    rewrite_log on;

    error_log  /var/log/nginx/wp-calypso-ssl-error.log;
    access_log /var/log/nginx/wp-calypso-ssl-access.log;

    ssl_certificate /etc/letsencrypt/live/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/privkey.pem; # managed by Certbot
    ssl_dhparam /etc/ssl/private/dhparam.pem;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_no_cache 1;
        proxy_cache_bypass 1; 
        proxy_pass http://calypso;
        proxy_redirect off;
    }
}
```

Can you please tell me where's the error in my config? Can't find it since other NodeJS projects works just fine with alike configuration.

**Comment by designsimply** [comment]
I noticed you are trying to setup a custom domain `some.site.url:888` for your local Calypso install. I am not sure about the nginx config. May I first ask what happens if you do the following steps?

* Add `127.0.0.1 calypso.localhost` to your local hosts file.
* Execute `npm start` from the root directory of the repository.
* Open `calypso.localhost:3000` in your browser.

**Comment by k1tzu** [comment]
I port-forwarded calypso.localhost:3000 from remote server to localhost and got this:
<img width="640" alt="screen shot 2018-05-10 at 02 04 45" src="https://user-images.githubusercontent.com/8276458/39844077-deab8cbe-53f6-11e8-84f9-916f4e84c482.png">
This is how it's supposed to look? So it's not possible to run calypso on VPS as a modern php-wordpress replacement? Since currently I'm running a separate nodejs service and integrating it's output into wordpress and it's not quite elegant solution.

**Comment by designsimply** [comment]
That's how it's suppose to look!

**Comment by designsimply** [comment]
> So it's not possible to run calypso on VPS as a modern php-wordpress replacement?

I think the relevant part of this question is whether you can run it on a VPS and why you would want to. Before going further, may I ask why you are trying to install Calypso on a VPS and what your end goal is exactly?

Regarding Calypso being a PHP-WordPress replacement… you might think of Calypso more like a replacement for wp-admin that's API-driven. Calypso was created to work directly with WordPress.com systems and is not meant to work independently as a separate entity out of the box. It is an admin interface for WordPress blogs using WordPress.com back-end systems (such as APIs and CDNs and mail servers and things most website owners do not want or need to build out separately).

**Comment by designsimply** [comment]
I am going to close this issue because I have hopefully helped answer the question sufficiently. @k1tzu if you are still having trouble or concerns, please re-open this issue or start a new one!
