### ISSUE TITLE
Rewrite links to P2s inside the reader to the review view of the site

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#24713]
When we show P2 posts in the Automattic section of the reader we should experiment with rewriting the links to the reader views of the posts instead of linking out to the actual P2.

#dogfooding

**Comment by bluefuton** [comment]
We could potentially use `data-` attributes for this.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
