### ISSUE TITLE
"You have a free domain - CLAIM" link is not shown for plan users

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#24710]
#### Steps to reproduce
1. Add a plan to any site (either regular flow, or SA)
2. Do **not** pick a custom domain name

#### What I expected
In Calypso, there should be a notice at the top left, saying something along the lines of "**Free domain with a plan - CLAIM**"

#### What happened instead
Notification does not show anymore.

#### Context / Source
Not sure if this is related to change #8612

#manual-testing

**Comment by designsimply** [comment]
Tested and confirmed that I cannot see the "Free domain available Claim" nudge in the My Sites navigation for a site that has a plan and no domain (note that this site has a Business Plan but is still a WordPress.com Simple site).

![screen shot 2018-05-07 at mon may 7 11 11 42 am](https://user-images.githubusercontent.com/1119271/39714598-d08c831a-51e7-11e8-9d9a-c98aa363234a.png)
<sup>Seen at https://wordpress.com/plans/my-plan/design5279.wordpress.com using Chrome 66.0.3359.117 on macOS 10.13.4.</sup>

For comparison, here is the same site showing the domain nudge from a screenshot taken 21-Mar-2018:

![screen shot 2018-05-07 at mon may 7 11 08 20 am](https://user-images.githubusercontent.com/1119271/39714608-d5c5e2fe-51e7-11e8-9088-a120ea77f5de.png)
<sup>Seen at https://wordpress.com/settings/writing/design5279.wordpress.com using Edge on Win 10.</sup>

**Comment by arunsathiya** [comment]
Closing this as this is not an issue anymore.

By following the instructions mentioned on the original post, I was able to see that notice.

![screenshot 2018-12-30 at 19 07 25](https://user-images.githubusercontent.com/18581859/50547750-32345a00-0c66-11e9-9492-c7011d86987e.png)
