### ISSUE TITLE
Domain Management: simplify the edit site address flow

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2473]
Raised by @breezyskies 

This was previously discussed at length (9197-gh-calypso-pre-oss), I'm reopening the discussion with some new proposed designs.

One major consideration that came up previously is that the [current wp-admin page](https://cloud.githubusercontent.com/assets/1119271/12356012/5b5b1046-bb6e-11e5-8615-6221b4e02625.png) also asks the following:
- Matching Username?
- Discard Current Address?

For this first version, I'm recommending that we exclude both of these from the flow (default to no matching username and discarding the address). They are complex issues that confuse an otherwise fairly straight-forward setting change. If we decide to keep it either, we could address in the next iteration. 

Here's the flow I've been working on ([prototype](https://mydomains.herokuapp.com/domain-default-address.php)):

![687474703a2f2f672e7265636f726469742e636f2f7959475677433274724c2e676966](https://cloud.githubusercontent.com/assets/1119271/12356114/d90b9db2-bb6e-11e5-8100-7bb39cedb9c4.gif)

This is based on the [delete site flow confirmation modal](https://cloud.githubusercontent.com/assets/1119271/12356129/eb2216a2-bb6e-11e5-8018-b8a2150445b2.png) design. We definitely need a secondary confirmation, but I'm wondering if typing the address again is overkill for this feature?

cc: @ranh @mikeshelton1503 @rads 

Comment from @kriskarkoski 

> I would default to keeping the old, empty address and require a separate delete action for that. If it's deleted by default users will have to contact support to have it restored. Even if it's messaged well I think some people will ignore it and make a change they can't fix without our help.

Comment from @mikeshelton1503 

> Looking good @breezyskies! I have a couple thoughts/questions for you:
> - Is there particular reason why we require users to retype the site address over a simpler confirmation method? You can always change it later, right? Unless there is a major implication to incorrectly changing your site's address, it seems like overkill.
> - If the retyping is necessary then I would suggest a more explicit relationship between the new site address and the input to confirm it. Also, separating the "warning messages" from the action will help in clarity of the action.
> - Should the "Change site address" button be disabled prior to changing your site's address? With it enabled I can see users clicking the button prior to actually changing anything if they didn't immediately realize that they're suppose to type in the text field. If we disable it I'd suggest also adding the "shake" animation to the input field if a user clicks the disabled button.

Comment from @breezyskies 

> > Is there particular reason why we require users to retype the site address over a simpler confirmation method? You can always change it later, right? Unless there is a major implication to incorrectly changing your site's address, it seems like overkill.
> 
> I agree it might be overkill (it's currently a pattern used for delete site, which obviously has much larger ramifications), but their site will no longer be available at the old address. To @kriskarkoski's point above, perhaps defaulting to saving the old address is the best way to help address this.
> 
> <img width="486" alt="screen shot 2015-09-22 at 6 23 47 am" src="https://cloud.githubusercontent.com/assets/3011211/10019479/859fb900-60f2-11e5-843c-34412f59f974.png">
> 
> > Should the "Change site address" button be disabled prior to changing your site's address? With it enabled I can see users clicking the button prior to actually changing anything if they didn't immediately realize that they're suppose to type in the text field.
> 
> I _think_ we do this in most Calypso forms (at least in most settings). +1

Comment from @kriskarkoski  

> > Is there particular reason why we require users to retype the site address over a simpler confirmation method? You can always change it later, right? Unless there is a major implication to incorrectly changing your site's address, it seems like overkill.
> 
> You can change the address again, but you can't change it back to the old address easily, though if we do default to keeping the old address around it would be possible with import/export.
> 
> I'm in favor of the confirmation step since renaming isn't too common and it's not much of a burden to type the address again for such a big and hard-to-reverse change.

Comment from @mikeshelton1503 

> Ok fair points about the confirmation. I didn't think about it actually being deleted (not sure what I thought would happen). In that case I default to my second recommendation of my making the confirm action clearer.
> 
> @breezyskies After thinking about this more I wonder if it makes more sense to include the confirm field right away. This is fairly rough but illustrates the idea:
> ![image](https://cloud.githubusercontent.com/assets/12596797/10020821/ec4bb508-6112-11e5-949b-c3cb20a2a790.png)
> 
> A confirm modal would still pop up after clicking "Change Site Address" to explain that the details of the change (the same as you posted above).

Comment from @breezyskies 

> This is definitely clearer than the field in the confirmation modal. I also like the addition of the "Current site address" copy you added. 
> 
> I was also thinking about how the success messaging could be useful here:
> 
> ![687474703a2f2f672e7265636f726469742e636f2f683644693339526e4f312e676966](https://cloud.githubusercontent.com/assets/1119271/12357199/8c2cd94c-bb74-11e5-8eda-da96809cde0f.gif)

Comment from @mikeshelton1503 

> :+1: The addition of the success message is good. It's a good place to have "delete it" and "renew it".

**Comment by umurkontaci** [comment]
@breezyskies I've started to work on this, are you still comfortable with the last recommendation in general? (We can fine tune it later)

**Comment by breezyskies** [comment]
@umur Yes, the [last flow posted](https://cloud.githubusercontent.com/assets/1119271/12357199/8c2cd94c-bb74-11e5-8eda-da96809cde0f.gif) is good to go.

**Comment by lancewillett** [comment]
What's the project status here? We're trying to close remaining wp-admin gaps and #7562 tracks a big one with renaming WP.com blog addresses.

**Comment by breezyskies** [comment]
This is not currently on the domains roadmap, particularly given that we have a couple current projects that are time-sensitive (general improvements for domain management would be November at the earliest). Is this something Delta wants to pick up? cc: @mikeshelton1503

**Comment by lancewillett** [comment]
Not for Delta, I was asking as broader "tracking the gaps" in general. I think this fits on Triton's plate, and was possibly assigned to a trial project at one point. I asked here to make sure you weren't also doing it at the same time! Thanks for the notes.

**Comment by lancewillett** [comment]
Closing this one in favor of #7562 (part of our effort to close WP Admin parity gaps).
