### ISSUE TITLE
Improve rendering of shortcodes in the reader

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#24734]
Certain custom shortcodes are not processed when viewing in the reader.

Example: https://wordpress.com/read/blogs/30514469/posts/37516

**Comment by bluefuton** [comment]
We should tackle this shortcode-by-shortcode (each one a small project).

**Comment by bluefuton** [comment]
Still an issue. There's a suggestion in p5PDj3-4Sg-p2#comment-7871 to use some of the work done for Jetpack email processing to fix this.

**Comment by davemart-in** [comment]
Closing as dup of #796
