### ISSUE TITLE
Activity Log: updates should clearly mention what type of update they are

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#24766]
Currently we are showing available plugin updates in the log in a persistent way at the top like this:

<img width="862" alt="screen shot 2018-05-09 at 11 37 01 am" src="https://user-images.githubusercontent.com/437258/39824621-cf628740-537d-11e8-9641-e6a13d3f774a.png">

It doesn't, however, mention that it's explicitly a plugin update. Since we are soon going to add theme and core updates to this UI we should make it clear what type of update it is beyond just the activity 'type' icon.

**Comment by keoshi** [comment]
@eliorivero Any reason why we got rid of the description text below, like so?

![image](https://user-images.githubusercontent.com/390760/39824812-2804580e-53a8-11e8-9635-01781660d119.png)

If adding this back is complex or stretches the top notifications block much further (there could be 10+ plugins on this list) we should at least add some context on that string:

> Update available for [WooCommerce Stripe Gateway](#) Plugin

**Comment by eliorivero** [comment]
No reason other than I missed it. Sorry. Will update soon.

**Comment by eliorivero** [comment]
PR ready here https://github.com/Automattic/wp-calypso/pull/24770

**Comment by keoshi** [comment]
Thanks for doing that, @eliorivero !! You're the man.
