### ISSUE TITLE
DevDocs: not all supported types of PaymentLogo are documented

### ISSUE THREAD

**Issue by jsliang** [Automattic/wp-calypso#24775]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/devdocs/design/payment-logo
2. In **Required Props** section, the document says there are currently 5 possible values for the `type` prop: `amex`, `discover`, `mastercard`, `paypal`, `visa`.

#### What I expected

 I expected all those possible values are documented.
There are at least 13 possible values for `type`.

#### What happened instead

The document says there are only 5 possible values for the `type` prop, which is apparently not true.

#### Context / Source

According to the variables `$payment-cc-brands` and `$payment-types` in `client/components/payment-logo/style.scss`, I believe there are at least 12 possible values for `type`.

I also found that in `client/extensions/woocommerce/woocommerce-services/views/label-settings/label-payment-method.js`, PaymentLogo is invoked with the `type` prop being `placeholder`. That makes `placeholder` the 13th possible value.

I've tried to document all the possible values of `type` in PR #24769 , but I'm not sure about the `placeholder` type. It seems like a special case to me. I would really like to know what this `placeholder` type means and when to use it.

**Comment by designsimply** [comment]
Tested and confirmed that I see the following warning in the console at http://calypso.localhost:3000/devdocs/design/payment-logo

> Warning: Failed prop type: The prop `altText` is marked as required in `PaymentLogo`, but its value is `undefined`.
> warning.js:33:7
