### ISSUE TITLE
Purchases: Add context to domain upgrade renewal/expiration strings

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#248]
The following strings need context to specify that the corresponding dates are on different lines/cells in the UI:
- Renews on
- Renews on
- Expires on
- Mapping renews on
- Mapping expires on
- Registered on

(This will help clarify to translators that the date isn't included in the string because it can't appear in a different order within the translated string.)

![domain strings 1](https://cloud.githubusercontent.com/assets/8658164/11287416/380d4cbc-8f13-11e5-89b4-cc94240a9a9d.png)

![domain strings 2](https://cloud.githubusercontent.com/assets/8658164/11287417/3c0cd918-8f13-11e5-8f84-f7e318c5a3f2.png)

**Comment by klimeryk** [comment]
@yoavf Do you think it's worth updating the strings to contain this context or at this point it would cause more harm? (as it would invalidate the old strings, I think?)

**Comment by yoavf** [comment]
We should use a translator comment in this case. It will keep the existing translations.
