### ISSUE TITLE
Page keeps flashing after clicking "Keep my subscription" in renewal email

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#24804]
In the renewal failure email, if you click "Keep my subscription", it takes you to a page in Calypso which is supposed to let users check out. But, it keeps flashing, never loads.

No errors in console.

#### Steps to reproduce
1. Starting at URL: open renewal failure email, e.g. with title "`Your WordPress.com domain 'x' is due for renewal`".
2. Copy the link of the button and paste in a new tab. Or, click the button i.e. "Keep my subscription".
3. Calypso keeps flashing.

#### What I expected

To be able to pay for the renewal.

#### What happens instead is:

![aa](https://user-images.githubusercontent.com/6505293/39897619-8983f790-54cc-11e8-88b0-74d380957964.gif)

#### Browser / OS version
Chrome latest, Safari 11.0.2, macOS

#### Context / Source

Was doing #manual-testing from the emails I'd gotten for test domains, and came across a few user reports as well, like #1151335-zen

**Comment by ehti** [comment]
Hm, odd that for some domains the checkout page loads, and for others it doesn't.

I have a test domain under my own account for which the page keeps flashing, ping me and I can give the exact URL it takes you to plus the domain.

**Comment by sirbrillig** [comment]
I was able to reproduce this by opening one of these links for account A when I'm logged into account B. That is, it happens for me when opening a link for an incorrect account. There are no JS errors that I see.

When I open one of these links from a logged-in account or a logged-out account, I do not see the buggy behavior (in the latter, I get a log-in screen and then I'm redirected to the correct purchase page).

I think that makes this a low-priority bug, but it should still show some sort of error message if the account is wrong.

**Comment by sirbrillig** [comment]
@ehti are you still able to reproduce this when logged into the correct account? (my testing certainly may have missed something)

**Comment by rralian** [comment]
We think this might be fixed, not positive. @ehti I've assigned this to @sirbrillig, can you please confirm whether this is still broken for you and if so can you connect with @sirbrillig directly to give him details to reproduce? This has the smell of something we could fix somewhat simply if we can consistently recreate it.
