### ISSUE TITLE
Domains: during checkout, email validation fails with + in email address

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#2480]
Shouldn't we support `aaa+bbb@gmail.com` style email address format?

<img width="981" alt="screen shot 2016-01-13 at 13 50 45" src="https://cloud.githubusercontent.com/assets/66797/12360787/39a031e4-bb77-11e5-90b5-19fd57e9b7ef.png">

This was found during the checkout flow, when buying a domain, and entering the Domain Registration Details with contact information. Testing with Safari 9.0.2 on OS X 10.11.1.

**Comment by lancewillett** [comment]
This could be a change in the API side, however.

**Comment by lancewillett** [comment]
Added a patch to fix this with D871.

**Comment by umurkontaci** [comment]
The reason we're not able to accept `+` is `+` sign is not accept by every registry and we're sticking to the least common denominator right now.

We might revisit this in the future if it the situation gets better.
