### ISSUE TITLE
Reader: "Discard Recommended" button broken in Firefox

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#24811]
The user told us this doesnt work for them and I’ve checked this is true at least in Firefox 59 for MAC (It worked for me in Chrome and Safari). You cannot click on the X as it seems to be disabled.

#### Steps to reproduce
1. Starting at URL. On the reader feed, but specifically at https://wordpress.com/following/manage
2. Try to get rid of some recommended sites in the Reader, using the Discard icon (The X in the upper-right corner).
3. On Mozilla the button is not clickable.

#### What I expected
I expected the button discarding a recommendation as I've tested it works on Chrome and Safari.

#### What happened instead
The button triggers no action.

#### Browser / OS version
My browser info, here: whatsmybrowser.org/b/JDSDFEU (I’ve also asked the user about their Browser version to see if it is different)

#### Screenshot / Video
![manage-following-e28094-wordpress-com-2018-05-10-14-37-12](https://user-images.githubusercontent.com/6404071/39908960-d6e02b70-54f0-11e8-9295-d313ff14a01c.png)

#### Context / Source
User reported in #1150589-zen

**Comment by Agepeuve** [comment]
The user is using Firefox 60. I'm also using it and I can see that the issue persists on that version.
