### ISSUE TITLE
Activity Log: Double notifications when updating a plugin

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#24823]
To reproduce:

1. Have a site that needs a plugin update
2. In the Stats -> Activity, click on the 'Update' plugin within the event itself
3. Notices 2 success notifications

Note: This is not happening when I click the 'Update' button that's in the banner at the top of the screen.

See: https://cloudup.com/cIUdGgcVQB3

**Comment by eliorivero** [comment]
I wonder if we should remove the button in events. What do you think @keoshi?

**Comment by keoshi** [comment]
Removing the buttons on events would mean breaking our own guidelines. I'm for keeping it, so the UI is consistent with its own patterns and expectable at all times.
