### ISSUE TITLE
Editor: Cannot save draft after clicking "Cancel scheduling"

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#24829]
#### Steps to reproduce
1. Create a new post
2. In the Post Settings > Status, pick a date in the future 
3. Click the "Cancel scheduling" button
4. Click "Save" link in header

#### What I expected

The post draft to be saved.

#### What happened instead

Receive notice: "Saving of draft failed".

Unable to save draft.

Upon publishing post, receive notice: "Post scheduled for Invalid date!" and post is scheduled for date originally scheduled.

**Comment by designsimply** [comment]
Tested and confirmed I see a "Saving of draft failed" notice at top right on the web page, no errors in the console, and this API call and response:

```
12125?http_envelope=1&context=edit
public-api.wordpress.com/rest/v1.2/sites/5276229/posts
```

```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"invalid_input","message":"Invalid request input"}}
```

![screen shot 2018-05-16 at wed may 16 5 50 17 pm](https://user-images.githubusercontent.com/1119271/40149576-b97bd6d4-5931-11e8-8756-6e2c82413dc8.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/12125 (WP.com Simple / Business Plan) using Chrome 66.0.3359.139 on macOS 10.13.4.</sup>

**Comment by mattsherman** [comment]
@Automattic/tanooki will look into this

**Comment by mattsherman** [comment]
@jsnajdr You might be interested in looking into this issue while in the neighborhood. Here's some notes that @Automattic/tanooki had from our recent team call where we discussed this issue a bit...

Request gets sent with:

```
{
    date: null
}
```

and response:

```
{
    "code":400,
    "headers": [
        {
            "name": "Content-Type",
            "value": "application\/json"
        }
    ],
    "body": {
         "error": "invalid_input",
         "message": "Invalid request input" 
    }
}
```

This is because the `date: null` results in an empty `input` array that is rejected by the API endpoint.

One potential solution is to modify the endpoint to accept either a value or null for `date`:

```
'date'  => '(ISO 8601 datetime|null) The post's creation time.',
```

That would probably allow the `null` to be passed through so that the endpoint could handle it.

**Comment by jsnajdr** [comment]
The WP.com endpoint (`wpcom-json-api-update-post-v1-2-endpoint`) does some magic with dates, e.g., resetting it to "now" when transitioning from "draft" to "publish" or from "scheduled from future" to "publish now".

Also, the core `wp_update_post` function can clear the date in some circumstances: look for the `edit_date` param and the `$clear_date` variable.

However, I don't see the capability to reset the date of a post that already has an explicit date set in the code. The wp-admin editor UI also doesn't have the "Publish Immediately" option.
