### ISSUE TITLE
Post Checkout: update post-purchase thank you page design

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2484]
Raised by @mikeshelton1503 

As part of the No Credit Card free trials we are testing a new version of the Thank You page to increase engagement (#1124). Pending the results of that test we'll want to update all Thanks Page if the new design wins.

For reference, this is what it looks like:
![image](https://cloud.githubusercontent.com/assets/12596797/10023359/b4ba5952-611f-11e5-9d47-0969f56faea0.png)

The layout and design of the page will remain the same for all purchases but as we do now we will change the content per each type of purchase.

The different version we have:
 - Premium purchase
 - Business purchase
 - Domain registration
 - Domain mapping
 - Google apps
 - Site redirect
 - Generic

Screenshots of the current pages: https://cloudup.com/cTfdvTFheu4

Mobile version:

### Mobile

![thanks-page-premium-v3-mobile](https://cloud.githubusercontent.com/assets/12596797/9966352/6081dd0a-5e0a-11e5-917b-81f50e1dd087.png)

**Comment by mikeshelton1503** [comment]
Copy drafts: https://docs.google.com/document/d/1GmR-hw3gv63Lj8VT7hXirgneRHQ-Awyy19x2X3zLOA8/edit?usp=sharing

**Comment by breezyskies** [comment]
There are a couple feature blocks that are notifying users of required next steps (often things they need to do off wpcom). For these, we can include a "required" state. This would be a flag that would:

- Use a different visual treatment for the specific feature block (see below).
- Always show first in the list.

**Domain Mapping:**
<img width="511" alt="screen shot 2016-02-23 at 3 44 28 pm" src="https://cloud.githubusercontent.com/assets/3011211/13287825/cd882532-dabd-11e5-9609-958259c0e88f.png">

**Google Apps:**
<img width="498" alt="screen shot 2016-02-23 at 6 56 23 pm" src="https://cloud.githubusercontent.com/assets/3011211/13287826/cda6ffc0-dabd-11e5-8da6-b181b83abf07.png">

cc: @fabianapsimoes

**Comment by mikeshelton1503** [comment]
@breezyskies Thinking about the "required steps" more, this design and copy might be a little strong or too "warning like" for a post-purchase experience. Maybe we could tweak the copy to be a bit more friendly? Something like "Almost done! One step remaining ..." (not perfect but something along those lines).

**Comment by breezyskies** [comment]
> Thinking about the "required steps" more, this design and copy might be a little strong or too "warning like" for a post-purchase experience. 

I'm not sure about this (assuming we don't misuse the pattern). In both examples above, the purchased product _will not work_ if the user doesn't complete these steps (and based on what we've heard from support, this is not uncommon). It really is a warning. Maybe we could try your copy with the existing visual treatment?

**Comment by mikeshelton1503** [comment]
>Maybe we could try your copy with the existing visual treatment?
Yes that's what I meant. :)

**Comment by breezyskies** [comment]
:+1: Updated:

<img width="982" alt="screen shot 2016-02-24 at 7 24 44 pm" src="https://cloud.githubusercontent.com/assets/3011211/13308888/4e3aaa88-db2c-11e5-9040-ecbde3fd254d.png">

**Comment by breezyskies** [comment]
@drewblaisdell noted in Slack today that there is one state that won't work well with the "Almost done! One step remaining..." copy:

<img src="https://cloud.githubusercontent.com/assets/3011211/13446110/7d2064b2-dfc5-11e5-9f57-fe770f38a6e0.png" width="400">

This is the only scenario where there may be two "required" sections (and the second one is only if they chose to purchase Google Apps while registering a domain). 

cc: @mikeshelton1503 @ranh for thoughts on how to handle the copy here.

**Comment by mikeshelton1503** [comment]
Hmm interesting. Really everything, design and copy, of the "required" sections doesn't work well when there are two steps. Plus in general the nature of this page being temporary doesn't make two steps very easy.

That being said, it is an edge case, so the design is probably ok for now. What if we just have one yellow header and change the number of steps in the copy for this scenario. Then stick the two "required" sections together like this:

![image](https://cloud.githubusercontent.com/assets/12596797/13463821/0fadd1b6-e05c-11e5-8c4f-f5e93a7d034f.png)

**Comment by breezyskies** [comment]
> What if we just have one yellow header and change the number of steps in the copy for this scenario. Then stick the two "required" sections together like this:

:+1:

**Comment by ranh** [comment]
Combining two items under the Urgent header looks good to me as a quick fix. Perhaps get rid of the third item there. Though the relationship between the subtitle ("Get started with your site's new features") and the "urgent" notice becomes a bit wonky if there are only two items that are under "urgent".

**Comment by mikeshelton1503** [comment]
>Perhaps get rid of the third item there.

Agreed there shouldn't be a third item. I guess I was just demonstrating what it would like if there were :)

>Though the relationship between the subtitle ("Get started with your site's new features") and the "urgent" notice becomes a bit wonky if there are only two items that are both under "urgent".

Good point. Maybe the subtitle copy should change when there are required states present?

**Comment by drewblaisdell** [comment]
@ranh @mikeshelton1503 #3705 changes "Get started with your site's new features" to "What now?"

**Comment by ranh** [comment]
@drewblaisdell That's a good point too :) I think that works

**Comment by fabianapsimoes** [comment]
> What if we just have one yellow header and change the number of steps in the copy for this scenario. Then stick the two "required" sections together like this:

We're adding Mike's suggestion as part of https://github.com/Automattic/wp-calypso/pull/3713:

![screenshot-calypso localhost 3000 2016-03-03 14-01-14](https://cloud.githubusercontent.com/assets/1248436/13495022/7170aa26-e148-11e5-8e20-e10e2ee0bad4.png)

**Comment by fabianapsimoes** [comment]
This is now merged. Closing.
