### ISSUE TITLE
Stats: Remove Chart Animations

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#2485]
Currently when switching between charts, the bars animate, but do so in an abrupt way.  Additionally with the y-axis changing often in these changes, the animation really makes no sense.

Lets remove this during the maintenance iteration.

**Comment by timmyc** [comment]
@alternatekev just confirming from prior discussion that we just wanted to remove the animations completely?

**Comment by alternatekev** [comment]
I'm all for removing the animations entirely.

**Comment by timmyc** [comment]
They have been removed in #2490 if you want to take it for a spin.
