### ISSUE TITLE
Data-layer: Migrate checkUrl to data-layer

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#24866]
This may make sense as a promise-returning action (see https://github.com/Automattic/wp-calypso/blob/dab66765c342f27002cf8be02d53221643170e07/client/state/jetpack-connect/actions.js#L208-L234 for an example).

Evaluate data-layer and promise-returning-action alternatives and proceed.

https://github.com/Automattic/wp-calypso/blob/dab66765c342f27002cf8be02d53221643170e07/client/state/jetpack-connect/actions.js#L78-L166

**Comment by hermawan22** [comment]
Hi @sirreal , may i help on this?
But give me time to understand the flow of data layer implemented on calypso. :)

If you can provide bit more details regarding this task, it will be helpful sir. :)

Thank u very much. :)

**Comment by sirreal** [comment]
@hermawan22 Thanks for the interest!

This particular case may not even be a good fit for the data-layer, we'd need to look into it more deeply and make a decision.

I'd recommend #25270 for what looks like a good candidate for data-layer migration as a place to get started. I have a messy work-in-progress PR for doing some data-layer migration that might help: #25023

**Comment by hermawan22** [comment]
Cool, will happy help on that issue @sirreal . :)

Thanks for the chance. :)
