### ISSUE TITLE
People: "The invitation cannot be sent"

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#24886]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/people/new/
2. Input an email address
3. Select Follower for the Role
4. Click Send Invitation

#### What I expected
The user would be sent a follower invite.

#### What happened instead
A red error notification with the message "The invitation cannot be sent" appears

#### Context / Source
I am unable to reproduce this on a test site, or for any other role on the user's site. I tested it using SU in the user's site, but they also relayed the same error message when trying through their own login. It is a simple site with the Premium plan (expertchine.com).

**Comment by jeherve** [comment]
Also in 1150692-zen

I could reproduce the issue on multiple Jetpack sites. The call to the `invites/new` endpoint seems to return the following response:

```
{"code":403,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unauthorized","message":"You do not have the proper permissions to perform this action."}}
```

**Comment by tmmbecker** [comment]
also in 279506-h

It was intermittent on my test site as well. Worked one day but didn't the next.

**Comment by mlaetitia** [comment]
Also in 3694375-hc and open for followup at 1168119-zd .

This user has 2 sites, this only happens in one of them. The site with the issue is on a premium plan (karingrand.com).

All other roles were successfully added except Followers.

**Comment by westi** [comment]
These look like false positives from anti-bot protection for invites, they should now be resolved.

**Comment by mattsherman** [comment]
I have verified that I can now successfully invite a follower on a Jetpack site of mine that was exhibiting this issue previously.

**Comment by SiobhyB** [comment]
This came up again in 1356252-z from someone using the iOS app. I was able to replicate by attempting to invite someone as a Follower to my Jetpack site within the app. I see the same error shown in the screenshots here:

https://github.com/wordpress-mobile/WordPress-iOS/issues/9094

**Comment by KristinaKay** [comment]
User confirmed that the problem is specific to iOS app #362588257166-zen

**Comment by westi** [comment]
These also look like false positives from anti-bot protection for invites, better to investigate these in a more appropriate place.
