### ISSUE TITLE
Themes: For free themes, the Support link redirects to the Details page

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#2489]
From https://github.com/Automattic/wp-calypso/pull/2482#issuecomment-172053719:

> for free themes, the Support page's content seems to be identical to the Details page -- i.e. with and without /support attached.

> So maybe we want to remove/deactivate the 'Support' link for free themes altogether?

(like we're already doing on Jetpack sites)

cc @folletto

**Comment by folletto** [comment]
> the Support page's content seems to be identical to the Details page -- i.e. with and without /support attached.

It does, but I'm still not sure what's the criteria for that. I'm not sure it's just "Free".
/cc @kathrynwp maybe you know?

Ideally, the URLs should come from the APIs too, instead of being inferred. :P

**Comment by kathrynwp** [comment]
Yes, only premium themes currently have the extra support page at this URL:
https://wordpress.com/themes/[theme-name]/support/

No free themes have that second page.

**Comment by kathrynwp** [comment]
FYI we tried to create a theme-support page for a premium theme once because it was a complex theme and we wanted a second page, but the link did not work correctly in the showcase.

**Comment by folletto** [comment]
Ok, that answers it. Thank you! :) 

So we can toggle that off for Free themes. :)
