### ISSUE TITLE
Domain Management: Domain Locking doesn't refresh automatically on Transfer page

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/wp-calypso#249]
Domain Management -> Click on a registered domain -> Transfer Domain

**2 scenarios:**
- Disable lock for transfer. Message appears on top, the page stays the same.

![249a](https://cloud.githubusercontent.com/assets/312395/11287962/7d97b158-8ed4-11e5-80c5-be3c8c22a1d7.png)

- Re-Enable lock. Message appears on top, the page stays the same.

![249b](https://cloud.githubusercontent.com/assets/312395/11287963/860aee36-8ed4-11e5-8ee3-5d01281c81a3.png)

**Actual Behavior:**
If you navigate away from the page, and come back, you would expect it to show current state, but it still shows the old one.

**Expected Behavior:**
I would expect the page to show current state at least when navigating away. Whether it should change state immediately is open for discussion.

Reported by @aidvu

**Comment by breezyskies** [comment]
cc'ing @umurkontaci on this as he's working on domain transfer right now (this can probably be closed out when the simplified version launches).

**Comment by umurkontaci** [comment]
Thanks @breezyskies. This will be fixed with the simplified version.
