### ISSUE TITLE
Customizer: Simple Payments Widget UI

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#24902]
Epic: #24617
Depends on: #24614

Styling should be added to the widget to improve the display of a Simple Payment Button as a Widget.

| Before | After |
| - | - |
| <img width="325" alt="screen_shot_2018-05-14_at_11 12 34" src="https://user-images.githubusercontent.com/233601/40123688-2c496148-58fd-11e8-857d-c5bf266db026.png"> | <img width="325" alt="screen_shot_2018-05-14_at_11 37 57" src="https://user-images.githubusercontent.com/233601/40123589-ee977b32-58fc-11e8-9064-ef8cd55f032b.png"> |

The Simple Payments Widget outputs the shortcode template without adding any extra styling so it can be displayed correctly on any site's sidebar or footer.

**Comment by gwwar** [comment]
cc @vindl I believe you had a few thoughts around UI updates and styling for existing payment buttons?

**Comment by vindl** [comment]
@gwwar just to be careful while deploying it because some unwanted changes could leak into production. :)

**Comment by Copons** [comment]
D13458-code is ready for review

**Comment by gwwar** [comment]
On that note, should we be adding different classes for simple payments within content vs as a widget?

**Comment by vindl** [comment]
I don't think we can with current setup since we are rendering the same thing in both cases. One thing that we can do is modify existing classes if `.widget.simple-payments` is their parent (which is the path @Copons is already taking in his diff).
