### ISSUE TITLE
Free Photo Library: does not work on AT site pages

### ISSUE THREAD

**Issue by rfaile313** [Automattic/wp-calypso#24926]
#### Steps to reproduce (Only On an AT Site)
1. Starting at URL: https://wordpress.com/pages
2. Click Add+ > From Free Photo Library > Search for and add a photo.

#### What I expected
For the photo to insert (it does) and then click the Update/Publish button.

#### What happened instead
The Photo inserts into the page, but then the page Update/Publish button becomes grey and you cannot click on it. 

#### Browser / OS version
FireFox Quantum 60.0.1 (64-bit)
Chrome
Windows 10
MacOS (Latest)

#### Screenshot / Video
![manual testing video](https://cdn-pro.dprcdn.net/files/acc_638487/X0eK0a)

#### Context / Source
1. Was able to reproduce this error on my own test site.
2. Another HE was able to reproduce on their AT test site: p1526580314000524-slack-tickets
3. Asked Atomic Guild for Guidance: p1526581144000281-slack-at-happiness
4. They suggested Triage
5. Triage Recommended report here
 
#user-report  #manual-testing

**Comment by notnownikki** [comment]
This is a Jetpack integration issue. For some reason, the request we send to the external media API no longer works with Jetpack sites, the Jetpack client can't determine the file type of the image and rejects the upload request. FWIW, this worked when we first rolled out Pexels, so I'll carry on looking at this to determine what's changed and see how it can be fixed.

**Comment by dcoleonline** [comment]
another report in 3699926-hc

**Comment by RealCarFax** [comment]
I'm also seeing this here: 1168770-zen

**Comment by spncrb** [comment]
Also does not work in the WordPress.com/media, after you click "copy to media library":
![spinningfreeimages](https://user-images.githubusercontent.com/8921630/40271035-97232ae8-5b4c-11e8-926b-6935be61d9e4.gif)

3542636-hc

**Comment by notnownikki** [comment]
The problem here is that uploaded images are getting a `.tmp` extension, which Jetpack doesn't recognise as an image. I'm working on this today, although I'm not sure how easy a fix will be. I'll keep things updated here, it doesn't seem to be a Jetpack or Calypso issue though, but I guess this is where peeps will check for issues :)

**Comment by notnownikki** [comment]
Fix has been deployed, images are copying correctly to Jetpack powered sites again.
