### ISSUE TITLE
Reader: make blog stream URLs more descriptive

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#24921]
The urls for posts on sites are not pretty.

Current format is: https://wordpress.com/read/blogs/{ID}/posts/{ID}
Would be better if these:

- Used the domain name of the site
- Used the post slug of the post
- Included a time indicator like year

**Comment by bluefuton** [comment]
We should make the more descriptive URL canonical, and then redirect the ID-based one to it.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
