### ISSUE TITLE
Jetpack Scan: fix the 'last scanned' date shown upon activation in IE11

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#2494]
When activating on IE11, the last scanned date first shown is 01/10/1930

Steps to reproduce:
1. Click on 'Activate Scan'
2. Enter SSH details (either username+password, or key)
3. When activated see this:

![jetpack-scan-bad-date](https://cloud.githubusercontent.com/assets/11487924/8687182/9bbb0212-2a5b-11e5-8e7f-1a33e5e55dd5.png)

When checking the same page using other browser, the date 01/10/1930 does not show up (either a correct date is shown, or nothing, as expected).

**Comment by designsimply** [comment]
Tested and confirmed:

![screen shot 2016-04-22 at fri apr 22 8 14 06 am](https://cloud.githubusercontent.com/assets/1119271/14746022/80b1d9ec-0862-11e6-908c-25ef7d80cb00.png)
<sup>Seen at https://wpcalypso.wordpress.com/settings/security/wildly.disambiguously.com using IE 11 on Windows 10 via BrowserStack</sup>

In comparison, the last scanned line is not shown at all in other browsers like Firefox:

![screen shot 2016-04-22 at fri apr 22 8 17 52 am](https://cloud.githubusercontent.com/assets/1119271/14746136/117060f2-0863-11e6-8033-aa1d78e557ee.png)
<sup>Seen at https://wpcalypso.wordpress.com/settings/security/wildly.disambiguously.com using Firefox 45 on Windows 10 via BrowserStack</sup>
