### ISSUE TITLE
Discover: Feature articles double when switching tabs

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#24957]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/discover
2. Click Search then click Discover in the sidebar
3. Observe that there are now more than 3 features articles and there is overflow

#### What I expected

For there to be 3 articles after going back to discover.

#### What happened instead

Duplicated articles.

#### Browser / OS version

Mac and Chrome

#### Screenshot / Video

![discover-feature-bug](https://user-images.githubusercontent.com/1126811/40256719-0b1e95a0-5ab1-11e8-872f-c5b6316382ff.gif)

**Comment by SnGrimes** [comment]
I'm looking at this one now it appears that the 3 featured articles is being added to the posts array every time the tab is clicked. I'm trying to trace where articles are being added to state and I think the problem is in `client\reader\site-stream\featured.jsx`.
