### ISSUE TITLE
Editor: Google Photos: Scrolling only finite photos

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#24952]
#### Steps to reproduce
1. Create a test site 
2. Create a new post
3. Try to insert Google Photos and link to an account that has many years of history, or too many photos. 
4. When we backscroll, the photos stop after about a month, or some finite number of photos. It does not backscroll from there anymore
5. I am able to get older photos quickly by using the search feature and entering month, year or date there. 

#### What I expected
I expected the backscroll to continue. If this is an API limitation, It would be awesome to show an alert message asking the user to use the search feature for earlier images, and use date, location or file name to search. 

#### What happened instead
Backscroll stopped at about a month before(or perhaps due to number of photos) , and it did not scroll anytime before that. 

#### Browser / OS version
Browser: Vivaldi - 1.15.1147.42 (Based on Chrome)
OS: macOS 10.13.4 (17E202) (High Sierra)

#### Context / Source
#dogfooding #user-report

**Comment by designsimply** [comment]
Tested and confirmed that on a Google account with 18,688 photos (you can find the number in your [Google dashboard](https://myaccount.google.com/dashboard)) I can only scroll back through about 2 months of photos (I could see photos from 13-Mar while testing on 18-May).

Here is the related API call and response:

```
https://public-api.wordpress.com/rest/v1.1/meta/external-media/google_photos?http_envelope=1&number=20&page_handle=320&source=google_photos&path=recent
```

```
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"found":0,"media":[],"meta":{"next_page":false}}}
```

**Comment by jakejones1984** [comment]
I believe this is a duplicate of

https://github.com/Automattic/wp-calypso/issues/22681

**Comment by scosgro** [comment]
User came to us today in chat with this same issue, but their photos were only loading back by about 2 days by default.

Using the search function seems to be the workaround, and I was able to find more images by using specific searches/filters (dates, etc).

Report #5309738-hc
Followup #1308943-zen
#user-report

**Comment by johngodley** [comment]
Noting that this is an artifact of using the Picasa API which has a hard limit. There should be a message at the bottom of the list indicating you've reached the limit, but Google reduced the limit and so it's never triggered.

This will no longer be an issue because of #29965
