### ISSUE TITLE
Jetpack Plugins: in Updates, Drake incorrectly displayed before loading plugins with updates available

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#2495]
When loading the Plugins > Updates page at https://wordpress.com/plugins/updates and there are plugins that need an update, Drake will be shown until the list of plugins that need an update is loaded. Instead we should show a loading screen.

Here's what it looks like right now when refreshing the page:

![drake-before-plugin-updates](https://cloud.githubusercontent.com/assets/11487924/12365530/691db596-bba3-11e5-9acd-e05e97a3dc90.gif)

**Comment by enejb** [comment]
Should be fixed with #2018.
