### ISSUE TITLE
Editor: Switching between HTML and Visual removes &nbsp; spacing.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#24961]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Create or edit a post.
3. Hit the "enter" key several times to create line breaks.
4. Click the HTML view tab.
5. Click the Visual view tab.
6. All &-nbsp-; line breaks are now removed.

#### What I expected
Line breaks to be preserved when switching between HTML and Visual views.

#### What happened instead
Line breaks are removed.

#### Browser / OS version
Chrome Version 67.0.3396.48 (Official Build) beta (64-bit)

Debian Stretch 

#### Screenshot / Video
https://drive.google.com/file/d/1s-D5ks5FttQr6_nGEEDmeYxv9D0nadGj/view

https://drive.google.com/file/d/10cuJNIu85K4N5tFbG8J8HHUZ_BmICRaK/view

#### Context / Source

1167046-zen

3652653-hc

**Comment by sarahfg** [comment]
Reported 3958752-Zen
