### ISSUE TITLE
Inline Help: Mousing over a "selected" result breaks styling

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#24999]
See gif:

![inline-help-selected-plus-mouseover-breaks](https://user-images.githubusercontent.com/1587282/40367232-d4859540-5da6-11e8-9d4b-830192c701d5.gif)

#### Steps to reproduce
1. Starting at URL: https://wordpresss.com (or anywhere in calypso)
2. Click the help icon to open inline help
3. (optionally, search for something) Press the down / up arrows to "select" a result
4. Mouse over the selected result

#### What I expected

For the styling to not be adversely affected

#### What happened instead

The styling breaks such that I cannot read the "selected" result

#### Browser / OS version

Chrome Mac H.S.

#### Context / Source

Found while testing #24822

**Comment by ramonjd** [comment]
Hi all! I was looking at a seperate issue on this component, and found the same issue. 

I created a fix at #25010 

Let me know if it's okay for now.

From an accessibility point of view, should we also see if we can add focus to the `<a/>` as well?

Cheers!
