### ISSUE TITLE
NUX: user-only version of the welcome email 

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#250]
The username only signup in Calypso currently at https://wordpress.com/start/account/user is sending what looks to be a very old version of our welcome email.

Some of the information in the new email is less relevant since they haven't created a site (yet), but it still looks much better than the version we're currently sending.

We should create a new version of the account only email.

**Comment by meremagee** [comment]
We suppressed the old plaintext email and started sending the more current welcome email. Currently testing an updated email to a subset of users as well.
