### ISSUE TITLE
Domain Management: titles have inconsistent hierarchy

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2500]
Raised by @koke<br>(10202-gh-calypso-pre-oss  #issuecomment-142603378)

I find the title string for the domain pages a bit disorienting:

"Domain Management › Email › Email Forwarding ‹ Koke's Journal — WordPress.com"

We start from less specific to more specific, right to left with "WordPress.com", and site title. Then we switch to left-to-right. I think right-to-left was the right call, specially as browsers now display just the beginning of a title, if anything

![screen shot 2015-09-23 at 15 34 07](https://cloud.githubusercontent.com/assets/8739/10046364/abcbee84-6208-11e5-8f93-e8259e44f1c5.png)

![screen shot 2015-09-23 at 15 35 57](https://cloud.githubusercontent.com/assets/8739/10046408/e2e3ae70-6208-11e5-8360-c82c17e5b6d1.png)

Comment from @gziolo 

> There was also suggestion to split translations as part of this change. That's great idea. We already do it for `Purchases` pages. It would be great to sync here with this approach and make translators life easier :)

Comment from @designsimply

> I noticed it matches the url structure.

**Comment by designsimply** [comment]
Tested and confirmed with the following steps to reproduce:

1. Go to https://wordpress.com/stats/insights and select a site with a custom domain
1. Go to Domains > %domainname% > Email > Add Email Forwarding
1. Check the `title` tag in the html

<strong>Result:</strong> the title tag goes from general to specific, like so:

> Domain Management › Email › Email Forwarding ‹ %sitename% — WordPress.com

Can the title be changed to be something more intuitive like "Email Forwarding › %sitename%" or "Email Forwarding › %domain name%"?

**Comment by umurkontaci** [comment]
Yes, it should be easy to do though it is not exactly a priority for us.
