### ISSUE TITLE
Wrong currency in notifications when using WooCommerce

### ISSUE THREAD

**Issue by jobthomas** [Automattic/wp-calypso#25017]
#### Steps to reproduce
1. Starting at URL: kuvela.org
2. Currency set to ZAR
3. New order comes in and uses $ rather than ZAR or R

#### Screenshot / Video

<img width="150" alt="currency" src="https://user-images.githubusercontent.com/8783673/40420738-95deb45a-5e89-11e8-8885-b46933d85585.png">

**Comment by timmyc** [comment]
Thanks for the bug report @jobthomas - I'll look into getting this fixed up.

**Comment by timmyc** [comment]
So some good news and some bad news - good news is we indeed are sync'ing the order currency via Jetpack, so we have access to that value. The bad news is the utility we are using to format the currency for display in the notif does not have a full list of currencies ( yes it is a static array of currency data ) - and it defaults to showing `$` when a currency code does not exist in the list - such as `ZAR`.

It looks like we could lean on `WP_CLDR` to fix the issue though. I'll give it a try, and see if that will do the trick.

**Comment by timmyc** [comment]
Proposed fix D13817-code

**Comment by timmyc** [comment]
Fix deployed in r177009-wpcom
