### ISSUE TITLE
Contact Form Editor: email address with 2 hyphens is seen as invalid

### ISSUE THREAD

**Issue by arcangelinis** [Automattic/wp-calypso#25030]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/brilliant--basics.com/2
2. Edit the Contact Form from the Visual tab and then click Settings
3. Under "Enter your email address" use orders@brilliant--basics.com
4. You will receive an error stating "orders@brilliant--basics.com is not a valid email address." and will not be allowed to save

#### What I expected
This is a valid email address and a valid website, but the double hyphen is being flagged as not valid.

#### Work around
By using the Contact Form shortcode I was able to set the email address without any issues

#### Screenshot / Video
<img width="731" alt="edit_page_ _brilliant_basics_ _wordpress_com" src="https://www.evernote.com/shard/s517/sh/b36c1c78-1baa-4a76-8c3b-6a5a5c0c41ad/4edf6d1a679fcc9a/res/cbd85cae-0734-4826-8e10-a2a5d598df83/skitch.png">

<img width="731" alt="edit_page_ _brilliant_basics_ _wordpress_com" src="https://user-images.githubusercontent.com/37232147/40465316-c13d0c30-5ee5-11e8-969a-306c12275ac7.png">

**Comment by designsimply** [comment]
Tested and confirmed that I am unable to change a contact form settings email address to an address using a domain with two hyphens in a row such as `domainwith--twohyphens.com`.

<img width="1280" alt="screen shot 2018-05-24 at thu may 24 11 03 13 am" src="https://user-images.githubusercontent.com/1119271/40500542-52981ec0-5f42-11e8-910b-f1d4ae4e2dd2.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/12140 using Firefox 60.0.1 on macOS 10.13.4.</sup>

**Comment by Dec0y-jb** [comment]
I haven't looked at the code; however it might be possible it's returning an error because "--" would typically indicate SQL comments. If this inserted into the middle of a statement - it would comment out the rest of the query, and return an error.

**Comment by Dec0y-jb** [comment]
It looks like the problem might exist within "email-validator", the regex might not be recognizing "--" as valid within an email address.

**Comment by hermawan22** [comment]
Hi, i also can reproduce this issue.

And i think this from third party library.
I just create a PR on third party library to fix this issue https://github.com/manishsaraan/email-validator/pull/33

But any other options, to make it fix asap instead wait my PR to be merge?
Thanks.

**Comment by Dec0y-jb** [comment]
I haven't had the opportunity to try running it through email-validator - but I think it might have to do with the regex being used for validation.

**Comment by hermawan22** [comment]
My PR already merged https://github.com/manishsaraan/email-validator/pull/33
Hopefully can fix this issue.
