### ISSUE TITLE
Google Apps: move fetching Google Apps users to data component

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2504]
Raised by @gziolo 

> Improve this implementation and get rid of code comment: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/domain-management/email/google-apps-users-card.jsx#L34-L35.
> 
> It is a bit tricky because we need to fetch those data only in case we have domain selected. We need to double check if we should prevent sending request to the server when there are no Google Apps users assigned to the domain.

**Comment by umurkontaci** [comment]
This will be fixed with #3584
