### ISSUE TITLE
Me: HTML entities should be handled correctly

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#2505]
Here are some areas in /me where we don't display HTML entities in a name correctly:

1. Me > Security > Connected Applications: the Access Scope name
![access-scope-connected-apps](https://cloud.githubusercontent.com/assets/11487924/12374806/d00a5e94-bc75-11e5-81ac-ad80a36ee882.png)
2. Me > Security > Connected Applications: the name of the app. In /me the HTML entities are stripped:
![stripped-html-app-name](https://cloud.githubusercontent.com/assets/11487924/12374816/1316d38e-bc76-11e5-8093-e90073a56ebe.png)
Here's what it looks like on https://developer.wordpress.com/apps/ID instead:
![app-name-correctly-displayed](https://cloud.githubusercontent.com/assets/11487924/12374819/2163fc78-bc76-11e5-9187-868a381cf34f.png)

**Comment by hoverduck** [comment]
07Apr16 Bug Scrub

I was able to confirm that having text inside `< >` brackets does not show up in the Connected Apps list, but other special characters seem to be okay (& turned into &amp;).  I was unable to get an application to connect with a single-site scope, so that portion remains untested.

**Comment by hoverduck** [comment]
26May16 Bug Scrub

There hasn't been any activity on this in over 2 months, so I'm closing.  Feel free to re-open if anyone wants
