### ISSUE TITLE
Editor: No "Paste and Match Style" option

### ISSUE THREAD

**Issue by zackkatz** [Automattic/wp-calypso#2506]
**EDIT: This is related to the desktop app, not the web interface.**

Calypso lacks a common Edit Menu command: "Paste and Match Style".

When you want to paste content and strip the formatting, there is a commonly-used key combination to "Paste and Match Style": Shift + Option + Command + V. 

<img width="293" alt="screen shot 2016-01-17 at 12 58 03 pm" src="https://cloud.githubusercontent.com/assets/870979/12379525/15cf3bb2-bd1a-11e5-87ff-96d0d5d1109d.png">

__References to this functionality:__

> Paste without formatting: I don’t know about you, but I never, ever want to paste something into a fresh document AND carry across its original formatting. To paste without formatting (i.e. as plain text), hold down Shift + Option + Command and hit V. It’s a tricky keyboard combo to master, and I hold down Option + Command with my thumb, and Shift with my pinkie, leaving a finger free to hit V.
> [Cult of Mac](http://www.cultofmac.com/137885/top-10-tips-of-a-mac-master-os-x-tips/)

* https://macnancy.wordpress.com/2013/06/21/copy-and-paste-without-formatting/
* http://osxdaily.com/2013/04/18/strip-styling-font-formatting-text-mac-os-x/
* https://discussions.apple.com/message/17437479#17437479

**Comment by designsimply** [comment]
I tested and found that the keyboard shortcut works while the menu item is missing. I found this is also the case for the TinyMCE editor at https://www.tinymce.com/docs/demo/classic/ 

Do you find the same thing happens in the TinyMCE demo if you test there as well? 

Note: I tested with Firefox 43.0.4 and Chrome 47.0.2526.106 on Mac OS X 10.10.5.

**Comment by designsimply** [comment]
I tested again and found that the "Paste and Match Style" option is present in Safari 9.0.2 on Mac OS X 10.10.5 so perhaps this is a browser-related issue.

![screen shot 2016-01-18 at mon jan 18 7 57 52 am](https://cloud.githubusercontent.com/assets/1119271/12391970/7eb50022-bdb9-11e5-87c0-9f74ec31fd83.png)

@zackkatz, what browsers/versions have you tested with?

**Comment by designsimply** [comment]
You might also like: http://superuser.com/questions/512491/copy-and-paste-plain-text-only-in-osx/725127#725127

**Comment by zackkatz** [comment]
I'm sorry if I didn't clarify: the issue isn't in Safari, it's for the WordPress.com app. "Paste and Match Style" isn't an option in the app.

<img width="425" alt="screen shot 2016-01-18 at 9 10 00 am" src="https://cloud.githubusercontent.com/assets/870979/12396215/7a0328ec-bdc3-11e5-8874-582504d356a5.png">

**Comment by lancewillett** [comment]
Moved to https://github.com/Automattic/wp-desktop/issues/153
