### ISSUE TITLE
Plugins: Warn users plugins are incompatible before they upgrade to Business.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#25066]
#### Steps to reproduce
1. Switch to a site that doesn't have a Business plan on WordPress.com
2. Open the plugins page.
3. Search for a plugin from this list: https://en.support.wordpress.com/incompatible-plugins/
4. Upgrade to Business to be able to install that plugin (per what the message implies)
5. You now see a message saying it's incompatible

#### What I expected
To be told a plugin I was viewing was incompatible, before being prompted to upgrade so I could install it

#### What happened instead
You see two messages. The first: upgrades to Business, because your plan doesn't support plugins. And the second: Now that you've upgraded, you can't install the plugin.

#### Browser / OS version
Firefox 62 / Debian Stretch

#### Screenshot / Video
Plugin page, sans Business plan for "Comet Cache":

![screenshot-2018-5-24 comet cache plugin test site 2 wordpress com](https://user-images.githubusercontent.com/10121835/40516824-7b06dc82-5f80-11e8-8a5e-ddaca3ef1f1d.png)

Plugin page, after upgrading to Business. Now with message you can't install Comet Cache:

![screenshot-2018-5-24 comet cache plugin test site 3 wordpress com](https://user-images.githubusercontent.com/10121835/40516843-8d2bc80a-5f80-11e8-9441-e7d5d5928c65.png)

If the second message, the one about incompatibility, too precedence/overruled any other message such as the upgrade one, that would avoid this type of confusion.

**Comment by torres126** [comment]
Still an issue. :)

**Comment by arunsathiya** [comment]
The marketplace has changed significantly since this report. A newer issue is here: 

- https://github.com/Automattic/wp-calypso/issues/62281
