### ISSUE TITLE
Refund amounts for individual theme after more than one theme is purchased at the time of sale

### ISSUE THREAD

**Issue by adamleone** [Automattic/wp-calypso#25093]
#### Steps to reproduce

EG. As user griffinsgadgets. So when cancelling and refunding a theme, if more than one theme is purchased at the original time of sale, then when you come to refund just one of those themes the original sale price is displayed, not the cost of the actual theme. This is misleading.

1. Starting at URL:  https://wpcalypso.wordpress.com/me/purchases
2. Click on minimum theme: https://wpcalypso.wordpress.com/me/purchases/petergriffin.co.nz/8849
3. Click on cancel and refund: https://wpcalypso.wordpress.com/me/purchases/petergriffin.co.nz/8849/cancel 
4. Amount is original bulk purchase figure, not the cost of the theme

#### What I expected
I expected to see the amount refunded to be the cost of one theme. So $49 not $125 

#### What happened instead

I saw $125 (which was all of the themes bundled together) instead. 

#### Browser / OS version
Chrome: Version 66.0.3359.181 (Official Build) (64-bit)

#### Screenshot / Video

https://adamleonehetrialp2.files.wordpress.com/2018/05/calypso-bug-manage-purchases-amounts.gif

#### Context / Source

https://woothemes.zendesk.com/agent/tickets/1184740

This is misleading and the user wants to keep one of the themes. They were under the impression that when they come to refund, they'll lose everything, which isn't the case. 

#Misleading #confused #sympathy #empathy

**Comment by rralian** [comment]
This is a good find, but sounds like an extremely corner-case issue that isn't affecting too many people. We'll add it to our list, but this honestly isn't very likely to get addressed directly anytime soon. Just preparing you. In the meantime, we can just manually fix this for users when it comes up.
