### ISSUE TITLE
Signup: Plans: custom header text for /start/premium

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#251]
@mattm suggested that we could customize the header text on the plans flow (http://wordpress.com/start/premium) to remind the user that they will have a plan automatically selected for them; along the lines of:

> Before we set you up with a premium plan, we need you to choose a site address and create an account

**Comment by fabianapsimoes** [comment]
@ranh can we get a sanity check on this copy? For context, `/start/premium` is a flow used in campaigns that allow users to create a site with a Premium plan.
