### ISSUE TITLE
Media: Gallery: options to change title/alt/description are missing

### ISSUE THREAD

**Issue by antermoia** [Automattic/wp-calypso#25111]
When working on the Gallery settings in the Calypso editor, there is no way to edit/change the image title, alt-test and long description. The only thing that can be edited in the Gallery settings in Calypso is the caption. For everything else, one has to use the Media Library, which is a lot more clicking and work. It's super useful to be able to adjust title, alt-text and long description "on the fly" in the Gallery settings.

I hope it's clear what I mean. Here's a screenshot of the Gallery settings sidebar in the old ("WP-Admin") editor when I click on an image in the gallery:

![image](https://user-images.githubusercontent.com/4782083/40592944-870a6598-61d9-11e8-8d64-60355f43001b.png)

**Comment by designsimply** [comment]
Tested and confirmed that I cannot edit image meta (Title, Caption, Alt text, Description) via the Calypso gallery editor when editing a post.

![screen shot 2018-05-31 at thu may 31 2 24 01 pm](https://user-images.githubusercontent.com/1119271/40806324-5749c882-64de-11e8-9af0-651730baf275.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11970 using Firefox 60.0.1 on macOS 10.13.4.</sup>

However, I can see meta fields for gallery images when editing a post in WP Admin:

![screen shot 2018-05-31 at thu may 31 2 23 35 pm](https://user-images.githubusercontent.com/1119271/40806330-5b5d588a-64de-11e8-87ee-da1d6ca755ba.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/post.php?post=11970&action=edit using Firefox 60.0.1 on macOS 10.13.4.</sup>

**Workaround**

@antermoia, thank you for raising this issue! I like your suggestion, and I would also like to note that the gallery image meta data is tied directly to what is saved in the media library. What that means is that you can go to My Sites > Media > [image] and edit the meta details for an image and those details will be reflected in the gallery on the front end when you view and refresh that page. 

![screen shot 2018-05-31 at thu may 31 2 28 23 pm](https://user-images.githubusercontent.com/1119271/40806724-94f7110c-64df-11e8-9b30-739891ea74af.png)
<sup>Seen at https://wordpress.com/media/design5279.wordpress.com using Firefox 60.0.1 on macOS 10.13.4.</sup>

**Comment by RadoslavGeorgiev** [comment]
I am not sure what is the official procedure here, but I've been working on this (adding the fields) for a couple of days and should be able to open a PR tomorrow.
