### ISSUE TITLE
Settings: WordPress.com Toolbar Option Available on AT Sites

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#25116]
On an Atomic site, there is a toggle that lets you **Enable the WordPress.com toolbar**. You can't actually toggle this setting off like you can with Jetpack on .org as stated here - https://jetpack.com/support/masterbar/

#### Steps to reproduce
1. Go to Settings -> Writing on an Atomic Site
2. Try to turn off the toggle
3. The toggle resets

#### What I expected
This toggle should not be available if the setting can't be turned off.

#### What happened instead
The toggle is available but doesn't let you turn off the WordPress.com toolbar.

#### Screenshot / Video
<img width="745" alt="admin bar" src="https://user-images.githubusercontent.com/30090682/40611690-b39f8bb2-6277-11e8-905b-c16fd1394c2c.png">

#### Context / Source
#user-report
A user contacted us in 3875822-hc asking why the toggle wouldn't stay off.

**Comment by jeherve** [comment]
cc @vindl
