### ISSUE TITLE
Domains: Clean up columns on narrow screens

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#25146]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/domains/add/[site]
2. Search for a domain
3. Resize screen to approximately 745px wide
4. Note the results and prices lack breathing room, and the $/year line-height looks too tall: 
<img width="437" alt="screen shot 2018-05-28 at 5 05 45 pm" src="https://user-images.githubusercontent.com/2124984/40629564-03da0bbc-629a-11e8-8691-2a2664f6cf4a.png">

#### What I expected

Something more like this, with padding between the price and the domain name, and a line-height adjustment for the $/year:

<img width="437" alt="screen shot 2018-05-28 at 5 06 50 pm" src="https://user-images.githubusercontent.com/2124984/40629572-1287f8b8-629a-11e8-9f24-74ef9e6596b2.png">

**Comment by hermawan22** [comment]
Hi i create PR #25151 for this issue, hopefully it can be help.
If any suggestions or advice please let me know, since i just try contribute to calypso.

Thanks guys. :)

**Comment by sixhours** [comment]
Fixed and merged in #25151
