### ISSUE TITLE
Editor: Add "Free photo library" / "Media From Google" broken if the media modal is not loaded first

### ISSUE THREAD

**Issue by bperson** [Automattic/wp-calypso#25153]
#### Steps to reproduce
1. Starting from a "fresh" post editor ( for a new post or an existing one, it doesn't matter )
2. Click "Add" ( media ) and choose "Free photo library" or "Media From Google"
3. Get a completely blank page with a couple of stack traces in your console

**Important to note: If the media modal is loaded, you won't experience the issue, you need to do this in a fresh post editor.**

#### What I expected

The media modal:

<img width="1792" alt="screen shot 2018-05-29 at 11 51 10" src="https://user-images.githubusercontent.com/1145270/40657238-a12d68ea-6336-11e8-8ee1-b2cdf158b61a.png">

#### What happened instead

Completely blank page with a couple of stack traces in the JS console

<img width="1792" alt="screen shot 2018-05-29 at 11 50 48" src="https://user-images.githubusercontent.com/1145270/40657242-a6f7a4ac-6336-11e8-9a63-2951c34bcb0c.png">

#### Context / Source

#user-report

**Comment by designsimply** [comment]
I tried testing this on production using Firefox 60.0.1 on macOS 10.13.4 and was unable to see a completely blank page after going to My Sites > Blog Posts > Add > Add content > Free photo library. I was able to see the free photo library [#](https://user-images.githubusercontent.com/1119271/40812109-5c6cab64-64f1-11e8-82c5-145ae60bbe24.png) or the Google image library [#](https://user-images.githubusercontent.com/1119271/40812137-765e24da-64f1-11e8-8749-84d4193a34d8.png) as expected (and I made sure to not click the media library first).

May I ask if you tested in staging or production and what OS and browser version you are using?

**Comment by kriskarkoski** [comment]
I experienced the issue in Chrome 66 and FF 55 both proxied with my normal account and unproxied on my normal account and a test account.

**Comment by designsimply** [comment]
I tested again from a few different WP.com unproxied accounts using Firefox 62.0.3 on macOS 10.13.6 and am still unable to see a blank page when I go to My Sites > Blog Posts > Add > Add (editor toolbar) > Free photo library.

@bperson @kriskarkoski if you can still see this problem happening, could you reply back here and report what errors you see in the browser console at the time the problem happens? Could you also make a note of any browser add-ons you have installed?
