### ISSUE TITLE
Likes corrupted

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#25179]
Clicking the like button on a comment twice, in quick succession, appears to fire blanks. I corrupted the like count on a few comments : 

- The comment `pb6Nl-cGW-p2/#comment-88263` shows 7 likes, but you can see only 5 likes in the onhover tooltip
- The comment `pb6Nl-cGW-p2/#comment-88198` shows 4 likes, but you can see only 3 likes in the onhover tooltip
- The comment `pb6Nl-cGW-p2/#comment-88286` shows 2 likes, hover and see only 1 like in the tooltip.

However, the reader shows the correct like count, but there’s a mismatch between the like counts on the Reader and P2. Check below – the image on the left shows the comment as seen on Reader, while the image on the right shows the same comment seen on the blog:

<img width="1701" alt="s1" src="https://user-images.githubusercontent.com/1269602/40703824-1242e5dc-6404-11e8-923c-d462bb7324bf.png">

<img width="1985" alt="s2" src="https://user-images.githubusercontent.com/1269602/40703944-715a82e6-6404-11e8-9c3f-50b4347485a4.png">

**Comment by designsimply** [comment]
@niranjan-uma-shankar, thank you for the report! The mismatch in like counts looks like a super interesting 🐛 to me. 🙂 I tried testing in a couple different ways and was unable to reproduce the problem you described using the following steps:

1. Go to My Site > Sharing > Sharing Buttons.
1. Make sure "Comment Likes" > "On for all posts" is checked and save changes if needed.
1. Open a post that has comments in a side-by-side view: Reader and front-end.
1. Click on the like button twice (or multiple times) in quick succession.
1. Force refresh both page views and check to see if the comment counts match.

<strong>Result:</strong> the comment counts always matched properly in my tests.

<strong>Video:</strong> [1m36s](https://cloudup.com/cm79y18XFya) (first try)
<sup>Seen at https://design5279.wordpress.com/2018/03/20/image-upload-test-2/ and https://wordpress.com/read/blogs/5276229/posts/11970 with the Radcliffe 2 theme active tested on production using Firefox 60.0.1 on macOS 10.13.4.</sup>

<strong>Video:</strong> [48s](https://cloudup.com/cDd68ibBLxW) (second try)
<sup>Seen at https://design5279.wordpress.com/2018/03/20/image-upload-test-2/ and https://wordpress.com/read/blogs/5276229/posts/11970 with the P2 theme active tested on production using Firefox 60.0.1 on macOS 10.13.4.</sup>

@niranjan-uma-shankar, could you let me know if you spot anything different in my testing compared to what you did when you saw the problem happen?

**Comment by niranjan-uma-shankar** [comment]
@designsimply Sorry if I wasn't clear in my bug description - but you need to invert the process. Clicking the likes in quick succession on the Reader corrupts it, not on the front-end. I've put together a screen grab video [here](https://cloudup.com/cgsA_bfj-XV). 
Seen at https://niranjan-umashankar-test-1.blog/2018/04/09/the-journey-begins/ and https://wordpress.com/read/blogs/145043288/posts/3.

Hope this helps, else do let me know.

**Comment by designsimply** [comment]
Looping back to note that even though this was marked as stale and closed, it does appear to have been fixed along the way somewhere. ([35s](https://user-images.githubusercontent.com/1119271/110049353-ecc0bb00-7d0e-11eb-91a1-bb0d8cb6159f.mp4))

I just wanted to say thanks for the bug report and the follow-up with the video too though!!! It's so helpful to have things like that in our bug reports.

**Comment by niranjan-uma-shankar** [comment]
Good to hear it's fixed!
