### ISSUE TITLE
Clone site - completion email and notification

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#25185]
Once the clone process is complete, we're going to send them an email notification just like we do with a restore.

### Email
![clone ready](https://user-images.githubusercontent.com/1123119/40732488-a8a2ab48-63f0-11e8-8f18-2a46ad2b8a7f.jpg)

### Notification
![clone site - notification](https://user-images.githubusercontent.com/1123119/40732227-16dc88e6-63f0-11e8-90a9-cf67c28db611.jpg)

### Notes
* We will need a support doc or maybe a [blog post](https://jetpack.com/tag/migration/) guiding through site migration via the link in the last paragraph of each image. CC @annezazu 
* @rcoll or @singerb Do we need an error state email/notification? I'm happy to mock that up as well.

**Comment by MichaelArestad** [comment]
As for the SVG, I believe that's already an image asset in use in other emails (perhaps purchase completion emails). I can always reexport it as a PNG if you need me to.

**Comment by annezazu** [comment]
@tmmbecker  heads up on this part:

> We will need a support doc or maybe a blog post guiding through site migration via the link in the last paragraph of each image. CC @annezazu

As for the wording, can we remove "There shouldn't be any problems". That just immediately makes me nervous reading that over. "It should be fine but...." doesn't inspire confidence :D "Lend a hand" is also a bit ableist. Here are some alternatives:

- If your site looks different than expected for any reason, please contact support so we can make it right. 
- If your site looks different than expected for any reason, please contact our support team who can help fix this for you.
-  If your site looks different than expected, please contact support so we can look into any problems for you. 
-  SUPER SIMPLE: If your site looks different than expected, please contact support.

**Comment by michelleweber** [comment]
+1 to taking out the "shouldn't be problems" bit. 

Your clone is complete! Take a minute to visit your new site, which should be identical to [name]. If anything looks different or unexpected, contact our support team -- they'll get things ironed out.

And if you're migrating content to your new site, we've got a handy guide to help!

**Comment by tmmbecker** [comment]
What's the difference between a clone and a migration? Why would they need a guide to help them migrate their content if they've just cloned it to a new site? Aren't these one in the same for our purposes?

**Comment by MichaelArestad** [comment]
@tmmbecker Clone just is an alternate restore and can be used in various ways like staging. Not just for migration. However, if they are migrating, they may want to update URLs and, if necessary, fix the ID crisis following if they switch to the same domain (host switch). Cloning or alternate restore use isn't super common, but it's necessary to maintain feature parity with VaultPress.

**Comment by tmmbecker** [comment]
Thanks for clarifying @MichaelArestad. I'd argue that alternate restores are more common than that and that most of our users would use this feature to migrate the site rather than staging. I don't know that the doc for explaining a clone would necessarily be different than the doc for explaining a migration. We can highlight what you've explained, but it would likely just be another heading in the same doc. Does that make sense?

**Comment by MichaelArestad** [comment]
@tmmbecker that makes sense
