### ISSUE TITLE
Plans : popover on mobile view not showing properly

### ISSUE THREAD

**Issue by hermawan22** [Automattic/wp-calypso#25189]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/[site]
2. Click on show features
3. Click on outline icon (to show popover)

#### What I expected
Popover showing left side instead on the top

#### What happened instead
Popover showing on the top, it cause some part of popover not showing properly and screen have width scroll.
![plans1](https://user-images.githubusercontent.com/6385048/40745106-230f8390-6489-11e8-8627-c164e93a26c7.png)

#### Browser / OS version
Chrome and Firefox / Ubuntu
Safari / Iphone 6

**Comment by hermawan22** [comment]
I will make PR for it. :)

**Comment by hermawan22** [comment]
Hi guys, can anyone help me to review my PR regarding this issue?
Thanks guys. :)

**Comment by alisterscott** [comment]
Thanks @hermawan22 

Closed in #25190
