### ISSUE TITLE
[Q] Purchases: Remove site slug from paths

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#25183]
## Design Question

In #24692 I'm working to fix 1642-gh-jpop-issues.

**Can we remove the site slug from purchase view/manage routes?**

Purchase routes are generally of the form:

```
/me/purchases/:SITE_SLUG/:PURCHASE_ID/:MAYBE_AN_ACTION
```

These would become:

```
/me/purchases/:PURCHASE_ID/:MAYBE_AN_ACTION
```

The changes are quite laborious, so I've raised the question here rather than implementing in case there are any objections.

### The issue

Purchases are tangled up with site objects in Calypso. In practice, this means that users are unable to take any action for purchases associated with Jetpack sites which are disconnected and they must contact support.

It may be impossible to know the associated site slug for a purchase and keeping them in the route is problematic for technical reasons.

### A technical note

Disconnected sites do not appear in the user's sites. Extended site data is unavailable, however the purchase data includes the associated site ID which is required to operate on purchases.

### The solution

There are many things that the user should be able to do and are technically possible without a full site object. The proposal is to treat full site data as an enhancement, and allow basic functionality with only the purchase data.

#### Examples

A user can remove a purchase or update/add credit card information for a disconnected site.

A user cannot navigate to the `/plans/:SITE_SLUG` page for a disconnected site (requires full site data).

cc: @Automattic/luna @Automattic/jetpack-design

**Comment by tyxla** [comment]
You're bringing a great point IMHO.

Having the site slug in the purchases route never made any sense to me. Looking further in the code, it appears to be used mostly for navigation purposes, and for displaying some messaging - something we could already extract from mapping the purchase's `blog_id` to the user's sites list for that specific case.

So, I'm totally up for changing that and removing the site slug from those routes. If we don't use the site slug in the routes for any user purposes (making it clear which site that purchase applies to), I don't see a good reason to keep them.

A downside of doing all this might be the way that we currently track page views for the purchase management pages - they'll include the `:site` part, while if we remove it, it will make sense to also remove that part from the corresponding `PageViewTracker` instances. That can be bad if we want to keep a consistent way to measure all those page views.

**Comment by sirreal** [comment]
I'll proceed with the approach outlined here.
