### ISSUE TITLE
People: Can't paste in "Usernames or Emails" field on Android browsers

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#25205]
#### Steps to reproduce
Using any site on an Android browser: 
1. Put something in your Android clipboard (an email address or username, for example)
2. Head to My Site > People > Add 
3. Try long-press to paste a name or address in the Usernames or Emails field

#### What I expected
Normally I should see the option to paste.

#### What happened instead
Nothing.  If I try skipping down to the Message field, I can paste there, but I can't paste in the Usernames or Emails field. Typing email addresses on a phone is a bit of a pain, so it'd be nice if this worked.

#### Browser / OS version
Confirmed in Firefox and Chrome for Android. Noting this happens in the Android app as well, but I'll file a separate bug.

#### Context / Source
https://en.forums.wordpress.com/topic/cant-paste-into-invite-email-box/#post-3118381

**Comment by supernovia** [comment]
Noting mobile app bug here:
https://github.com/wordpress-mobile/WordPress-Android/issues/7838

**Comment by designsimply** [comment]
Tested and confirmed using Chrome on Pixel, Android 8.1.0.

<img src="https://user-images.githubusercontent.com/1119271/40805687-4860bdfa-64dc-11e8-84a0-ca808e5fcf45.png" width="270"> <img src="https://user-images.githubusercontent.com/1119271/40805688-487eaf54-64dc-11e8-888e-09603c96db64.png" width="270">
