### ISSUE TITLE
Rewind: Add the backup duration to the Activity log

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#25207]
I think it would be nice to show how long a backup is taking for a particular site. 
This would help a user determine if they should be triggering a backup and how long it should be taking for their site. Also if a backup is taking a really long time it would allert the user that they might need to contact support. 

It is something that we currently show to the user in VaultPress. 

cc: @roccotripaldi and @keoshi

**Comment by keoshi** [comment]
@enejb Do you simply mean adding a stopwatch-like timer (i.e.: “2 minutes”) or that we do a better job at trying to predict how long a backup will take and show a countdown (i.e.: “4 minutes remaining”)?

**Comment by enejb** [comment]
yes a stop watch like 2 minutes would be good. This way as a user you would know what kind of backup duration is expected.

**Comment by keoshi** [comment]
@enejb Sounds good, thanks! @roccotripaldi — let me know what you need from me.

@singerb @briancolinger @thingalon Could we expect consistent times both across the board but, most importantly, on a single site? I'm mostly thinking that two different backups of the same site could experience very different times, depending if the servers are under load or not. Is this a valid concern at this point?

**Comment by singerb** [comment]
After the initial backup, I think we could expect relatively consistent times for the same site. Not across different sites though.
