### ISSUE TITLE
Editor: HTML Elements Disappear After Adding Attributes To Them In Some Cases

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#25201]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Add a list to the page.  It really just needs to be any HTML element, but a list helps to illustrate this well.

Example:

```
<ol>
	<li>This</li>
	<li>Is</li>
	<li>An</li>
	<li>Ordered</li>
	<li>List</li>
</ol>
```

3. Click inside of the opening tag of an HTML element and add an attribute to that element, but **do not click anywhere else** after you type just yet yet. (It doesn't matter whether you add a class, id, inline styling, etc.)

Example:

```
<ol>
	<li>This</li>
	<li>Is</li>
	<li class="testing">An</li>
	<li>Ordered</li>
	<li>List</li>
</ol>
```

4. Click on the Visual tab **without clicking on anything else** prior to that.

5. The result will be that that element has been removed from the editor. So in the example above, the code would look like this if you click again on the HTML tab:

```
<ol>
	<li>This</li>
	<li>Is</li>
	<li>Ordered</li>
	<li>List</li>
</ol>
```

#### What I expected

The element that had an attribute added to it should remain and keep the attribute(s) it was given.

#### What happened instead

The element was deleted.

#### Browser / OS version

Mac OS High Sierra 10.13.4
Firefox 60.0.1
Opera 52.0.2871.64
Chrome Version 66.0.3359.181

#### Screenshot / Video

Here it is in action when it loses the element:

![editor-loses-element](https://user-images.githubusercontent.com/3505172/40794788-d56f9070-64c5-11e8-91bc-38cb5c88c5b2.gif)

However, if you click outside of the list **before clicking the Visual tab**, the element is not deleted:

![editor-keeps-element](https://user-images.githubusercontent.com/3505172/40795326-5a906a26-64c7-11e8-809b-bd31fc6a1892.gif)

#### Context / Source

#user-report
1184280-zen

**Comment by mariovalney** [comment]
Hi @dcoleonline ! Thank you for sharing that.
I was trying to reproduce the bug and I found a related one: when I select a LI tag (even without add a HTML attribute) and change to Visual Editor, the list breaks out.

https://www.useloom.com/share/92bd42e9b37d44f0a02daabeed94d870

I'll try to help with that.

**Comment by mariovalney** [comment]
@rachelmcr is this issue going to be superseded by Gutenberg like [18042](https://github.com/Automattic/wp-calypso/issues/18042#issuecomment-353684847) ?

**Comment by KokkieH** [comment]
Noting this still happens. Stumbled across the issue while testing some inline styling to provide to someone on an unrelated forums request.
