### ISSUE TITLE
Signup: prefill domain search with site name if entered on About page

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25214]
Per: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=30

If customer enters a site name on the about page prefill this on the domain search page

<img width="873" alt="screen shot 2018-06-01 at 2 39 52 pm" src="https://user-images.githubusercontent.com/128826/40821348-acbf1ce2-65a9-11e8-8b45-3015ba67f4cc.png">

**Comment by jancavan** [comment]
We've completed a bunch of incremental changes to the signup flow, but we haven't made significant changes to the Domain Search design. I think we should re-visit this issue once we've done that. Thoughts?

**Comment by michaeldcain** [comment]
I believe that the domain search in both Signup and Gutenboarding now pre-fill the site title (when provided). Closing.
