### ISSUE TITLE
Settings: change button obfuscated by prompt

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25217]
via: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=65

<img width="895" alt="screen shot 2018-06-01 at 2 49 01 pm" src="https://user-images.githubusercontent.com/128826/40821553-f93a172e-65aa-11e8-8b99-35728ea829b8.png">

**Comment by hermawan22** [comment]
Hi @alisterscott , how i can help on this?

Any specific instructions for it? Or i just move tooltip to be under of `change` button?
If possible, will happy to help on this project https://github.com/Automattic/wp-calypso/projects/69

Thanks. :)

**Comment by alisterscott** [comment]
Hi @hermawan22 

It's just moving to tooltip under the change button

Best way to reproduce is visit https://wordpress.com/checklist/yournewsite.wordpress.com where yournewsite.wordpress.com is a wordpress.com site, then use the Site Icon link to open the page mentioned

**Comment by hermawan22** [comment]
Hi @alisterscott  i just fixed it.
Please kindly review my PR. :pray: 

But seems i found another bug > after success change icon then tour not going to the next tour (tooltip).

**Comment by alisterscott** [comment]
Thanks for the fix @hermawan22 

> seems i found another bug > after success change icon then tour not going to the next tour (tooltip).

I don't quite understand, would you mind raising a separate issue for this perhaps with a screenshot?
