### ISSUE TITLE
Signup: activation email doesn't open calypso to user checklist/onboarding

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25218]
As reported here: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=90
https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=91
https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=96

<img width="888" alt="screen shot 2018-06-01 at 2 51 06 pm" src="https://user-images.githubusercontent.com/128826/40821606-4251b840-65ab-11e8-8964-62f6e21d8f2a.png">

<img width="880" alt="screen shot 2018-06-01 at 2 51 30 pm" src="https://user-images.githubusercontent.com/128826/40821609-4cac84e6-65ab-11e8-8ccd-fc0993235ece.png">

<img width="877" alt="screen shot 2018-06-01 at 2 51 56 pm" src="https://user-images.githubusercontent.com/128826/40821619-5b50e140-65ab-11e8-8e76-3f11d082f0c4.png">

**Comment by jblz** [comment]
Working on a solution server-side in: D14339-code

**Comment by jblz** [comment]
This is live!  Closing.
