### ISSUE TITLE
Signup: Onboarding Checklist buttons all have same copy

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25216]
From: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=57

> The button copy is a bit repetitive when it's just the same phrase over and over

<img width="870" alt="screen shot 2018-06-01 at 2 45 23 pm" src="https://user-images.githubusercontent.com/128826/40821448-711a9c24-65aa-11e8-9348-70b497ebd30d.png">

**Comment by SnGrimes** [comment]
Could I help with this? Is the copy the same in order to maintain a certain button size?

**Comment by alisterscott** [comment]
Hi @SnGrimes 

> Could I help with this?

Yes

>  Is the copy the same in order to maintain a certain button size?

I'm not sure of the design reasoning, but if you come up with a variation we can get some design input on it

**Comment by SnGrimes** [comment]
@alisterscott Alright. Could you also tell me where this file is located so I can edit it?

**Comment by jblz** [comment]
@SnGrimes Thanks for taking a look!  

It looks like this string lives here:

https://github.com/Automattic/wp-calypso/blob/81aeda510ce4eb35e61bf22cd1454b2e0a54538f/client/blocks/checklist/checklist-task.jsx#L60

**Comment by SnGrimes** [comment]
Thank you! I found it and see why the copy is all the same.

**Comment by sirreal** [comment]
@michelleweber brings up some good points (https://github.com/Automattic/wp-calypso/pull/25258#issuecomment-398019833):

> is there a reason for changing it? Like, is there a drop-off as people move through the checklist, and you suspect this has something to do with it? In that case, I'd A/B it, or change it and the look at things in 2 weeks to see if it makes any difference.

I didn't read the useronboard slide as a strong recommendation that the text needed to change, especially in the context of this view of the slide:

![heck-yes](https://user-images.githubusercontent.com/841763/41533690-f5e5b674-72fb-11e8-9f07-d9bc1dcbb9f3.png)

Is there strong motivation to make this change?

**Comment by SnGrimes** [comment]
@sirreal  I originally thought that this issue was agreed upon by the Automattic team as something that should be looked at/changed. Was this more a suggestion @alisterscott ?

**Comment by sirreal** [comment]
@SnGrimes It may not be that simple, the Automattic team conversation is happening in the open on this issue 🙂 I'd say right now it's not clear one way or the other.

That said, we really appreciate you jumping in and working on #25258 🙇 

While we get this particular change sorted out, a good place to help might be the [good first issue label](https://github.com/Automattic/wp-calypso/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by sirreal** [comment]
There was motivation provided for these changes, so we're free to proceed at this point: https://github.com/Automattic/wp-calypso/pull/25258#issuecomment-398657075

**Comment by danhauk** [comment]
Fixed in #38149
