### ISSUE TITLE
Plans: Manage Plan button shows up even when I can't manage plan

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#2522]
I see `Manage Plan` on Plans page (`/plans`) even when someone else purchased this plan. When I click on the button link is broken and redirects me to the list of my purchases. This is where `Manage Plan` is located on the plans list:
![screen shot 2016-01-18 at 15 29 21](https://cloud.githubusercontent.com/assets/699132/12393810/6ad45078-bdf8-11e5-9ddf-3cdcfe5b4c18.png)

**Comment by fabianapsimoes** [comment]
We probably shouldn't display "Manage Plan" in this case.

**Comment by jeremeylduvall** [comment]
Closed via #5501.
