### ISSUE TITLE
Build is running out of memory

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#25237]
Over the past few days I have been getting out of memory errors during incremental rebuilds.  I tried doubling the `max_old_space_size` from 8 GB to 16 GB (!!) but it didn't help (https://github.com/Automattic/wp-calypso/pull/25234).

Example error:

```
0ms after seal 
 95% emitting CopyPlugin
<--- Last few GCs --->

[4250:0x228c670]  2637499 ms: Mark-sweep 1337.2 (1411.1) -> 1337.2 (1412.6) MB, 806.0 / 0.1 ms  allo
cation failure GC in old space requested
[4250:0x228c670]  2638306 ms: Mark-sweep 1337.2 (1412.6) -> 1337.2 (1401.6) MB, 807.3 / 0.1 ms  last
 resort GC in old space requested
[4250:0x228c670]  2639113 ms: Mark-sweep 1337.2 (1401.6) -> 1337.2 (1401.6) MB, 806.5 / 0.1 ms  last
 resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x10876dea5879 <JSObject>
    1: fromString(aka fromString) [buffer.js:314] [bytecode=0xf48cace1b61 offset=164](this=0x34dbbc2
822d1 <undefined>,string=0x2b7debce0f59 <Very long string[44517373]>,encoding=0x10876deb4ba1 <String
[4]: utf8>)
```

**Comment by hermawan22** [comment]
Hi @nylen @DanReyLop , greetings.

Sorry, i'm curious with this webpack build issue.
How to reproduce this issue?
Coz i didn't face this issue at my end.

My environtment : 
- OS : Ubuntu 16.04
- RAM : 16Gb
- Node : 18.11.1

Thanks guys. :)

**Comment by nylen** [comment]
@hermawan22 I think we don't see this issue every time, unfortunately :disappointed:

**Comment by blowery** [comment]
@nylen still hitting this?

**Comment by nylen** [comment]
@blowery yes, though I haven't been working in Calypso the past few days. Was there another update that might have changed things?

**Comment by blowery** [comment]
@nylen nope, just wondering. Curious why you're hitting it and not everyone is... I did bump into a similar thing with `jest --watch` yesterday, but I have not seem OOMs with the main build.

**Comment by blowery** [comment]
Closing this as we've had no additional reports in a while and have done some work to clean up stats output. Please reopen if still an issue.
