### ISSUE TITLE
People Management: Bulk Revoke Invitation

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#25252]
Similar to #25077 

1. Starting at URL: https://wordpress.com/people/invites/
2. it is possible to click into each pending invitation and then revoke it, preventing the recipient from becoming a member of the site.
3. In the event that there are a large number of invites to revoke, this can be time consuming. The option to selectively bulk-revoke, or even a Revoke All Pending option would make this much easier.

Context:
4100779-hc
#user-report #anxiety-flow #stresscase #painpoint

**Comment by hermawan22** [comment]
As a new comers, would happy to learn and help on this features (also for #25077). :)
