### ISSUE TITLE
Jetpack: support sites with non-root wp-install routes

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#25253]
Right now, if you go to https://wordpress.com/jetpack/connect and enter the url of a site with a wp install that is not in the root of the entered url, at some point we are going to try to redirect you to [site_url]/wp-admin, and you are going to end hitting a 404 or similar error and dropping off the flow.

We need to make this flow work for this type of sites. One method would be to check [site_url]/wp-json and get the url field from there. This would make the process slower, but we probably can combine this check with some of the others we do before redirecting the user and get this info "for free" (performance-wise)

More discussion on the subject: `p1HpG7-5aG-p2`

ping  to @m and @v18 who brought this up in different occasions.

**Comment by v18** [comment]
Related: #6088, #10980 (both auto-closed before)
