### ISSUE TITLE
Plans: improve copy/content of the `/plugins/upload/` paid plan feature 

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#25276]
#### Steps to reproduce
1. Starting at URL: `https://wordpress.com/plugins/upload/:site` for a site with a Premium or Pro plan (or relevant .com plan levels )
or arrive via `Add a Plugin` feature card at `https://wordpress.com/plans/my-plan/:site`
#### What I expected
- informative content

#### What happened instead
- empty space
- minimal info
- "only single .zip files are accepted" does not come across as overly friendly :) 
<img width="1365" alt="screen shot 2018-06-05 at 13 52 58" src="https://user-images.githubusercontent.com/13561163/40974619-62512c6e-68c8-11e8-8dbb-8c8860f94b58.png">

/cc @benhuberman

**Comment by benhuberman** [comment]
It's a little hard to envision what and how much copy is needed here given all the empty space. But to start, I could envision a more welcoming message near the top:
> **Upload plugin**
You're seconds away from making your site even more powerful. 

I'd tweak the directions in the upload box:
> To upload a plugin, drag and drop a file here, or click [the arrow above / anywhere in the box].

^^ I'm not sure what the clickable area is on that screen, but we can tweak the copy accordingly.

We could make the small-print message friendlier:
> For a quick and painless upload, make sure you only add one .zip file.

What do you think of those, @AnnaMag ? Any other thoughts about places here that might benefit from more / different copy?

**Comment by keoshi** [comment]
The component used for this is the `UploadDropZone`, which is currently not specific for themes or plugins. He might have to modify it to pass the object type for the suggestions above to work: https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/blocks/upload-drop-zone/index.jsx
