### ISSUE TITLE
Migrate Jetpack rest api calls to data-layer

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#25270]
Review calls to `/jetpack-blogs` path in undocumented.js. For example: 

https://github.com/Automattic/wp-calypso/blob/ae910be794a3207284e8725af7c87f560a25d559/client/lib/wpcom-undocumented/lib/undocumented.js#L192-L195

Used here:

https://github.com/Automattic/wp-calypso/blob/1626096bbd93792babcadce92eee8b40b42cbc32/client/state/plugins/premium/actions.js#L308-L325

**Comment by hermawan22** [comment]
Hi @sirreal , can u help me regarding this tasks?
How i can test for this task? I should have premium wordpress plan account for it?

**Comment by sirreal** [comment]
That's a good observation, I think the API calls in the description are part of a flow that happens when a Jetpack plan is purchased.

Here's another that may be simpler to get started working on:

https://github.com/Automattic/wp-calypso/blob/ae910be794a3207284e8725af7c87f560a25d559/client/lib/wpcom-undocumented/lib/undocumented.js#L204-L207

If you need a way of setting up "disposable" WordPress sites for testing Jetpack, there are free services that offer that. One example is http://poopy.life/

Let me know if that's enough to get going 🙂

**Comment by hermawan22** [comment]
Hi @sirreal , cool.
Thanks for explanation and the way to testing Jetpack.

I think that's good enough to start work on it.
:+1:
