### ISSUE TITLE
Posts: the action buttons should be handled optimistically when possible

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2528]
Raised by @rralian 

For example, when deleting a post, rather than issuing a request to the API and waiting for it to resolve before telling the user the post has been moved to trash, we should immediately show that the post has been moved to trash and then handle the situation where the operation errors out for some reason. /cc @adambbecker

**Comment by alisterscott** [comment]
This now does this:

![delete](https://user-images.githubusercontent.com/128826/34232170-d2c78a22-e62a-11e7-93ff-2a706a669a35.gif)
