### ISSUE TITLE
Rearrange and simplify the Site Tools menu 

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#25286]
Currently the tools section of settings is getting a bit clunky. It currently looks like this:

![image](https://user-images.githubusercontent.com/1123119/40999866-6f56d976-68c9-11e8-85a2-236151ba460f.png)

Note: Clone is not available for everyone and will only be available to Jetpack users who have Jetpack backups setup (also not widely available).

Clone is pretty similar to Import and Export in concept sooooo, after a little discussion, @joanrho and I worked up an idea for improvement.

### Proposal

We reuse components and images already in place and work up a slightly different flow. The first think we do is combo import, export, and clone. When clicked, the user is taken to a view that has the TileGrid component showcasing the various options. After that, the flows for each are unchanged (for now, though Import/export could use a similar treatment to the upcoming Clone flow).

![settings](https://user-images.githubusercontent.com/1123119/40999811-40821110-68c9-11e8-8add-57132b718790.png)

![manage site s data](https://user-images.githubusercontent.com/1123119/40999804-3caa13a8-68c9-11e8-9e68-10bd8719eb79.png)

**Comment by lancewillett** [comment]
Closing as "works for me" as the Tools menu is completely reworked since mid-2019.

<img width="641" alt="Screen Shot 2020-02-27 at 11 33 48" src="https://user-images.githubusercontent.com/66797/75474908-063d6300-5955-11ea-99ed-a8bf000aa3a9.png">
