### ISSUE TITLE
Facebook page plugin: Widget no longer seems to load (displays nothing)

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#25295]
#### Steps to reproduce
1. Starting at URL: In the customizer: https://wordpress.com/customize/
2. Click "Widgets"
3. Select a widget area
4. Click "Add a widget" and locate the Facebook page plugin.
5. Add widget, and then type in a Facebook page URL (such as https://www.facebook.com/SYFY/ )

#### What I expected

For content from the Facebook page URL added to the widget to be displayed

#### What happened instead

Nothing is displayed, regardless of plan/site/page URL. Seems to be broken across free/Personal/Premium/Business/Jetpack

#### Browser / OS version
Version 65.0.3325.124 (Official Build) beta (64-bit)
 
Debian Jessie

#### Context / Source

4141189-hc

**Comment by selectedselections** [comment]
Hi there! I wanted to go ahead and re-open this issue as I have received a report of the issue from a user in hc-3241851 (follow up in zd-1912506)

I have reproduced the issue on several test sites using different Facebook page URLs. The widget doesnt seem to load any content at this time.
