### ISSUE TITLE
Feedback: React errors when trying to edit feedback

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#25315]
Hi! I'm reporting a bug mentioned by a user on chat and reproduced on my own account. When editing a feedback from *My Site > Feedback*, the page is blank and the console shows numerous errors.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/types/feedback/ (*My Site > Feedback*)
2. Click on a feedback to edit it
3. Page is blank
4. Check console to see errors, including [React error 40](https://reactjs.org/docs/error-decoder.html?invariant=40)

#### What I expected

To be able to edit my feedback

#### What happened instead

Blank page on WordPress.com site. **It works fine with Jetpack sites.**

#### Browser / OS version

Reproduced on Chrome, Firefox and Safari

#### Screenshot / Video

![screen capture on 2018-06-06 at 17-21-03](https://user-images.githubusercontent.com/16645645/41048006-1849dc38-69ae-11e8-9295-984ffe3fd424.gif)

**Comment by catkit** [comment]
I reproduced this error as well and I have another user reporting it at #chat-4156118

**Comment by designsimply** [comment]
Tested and confirmed using Chrome 67.0.3396.62 on macOS 10.13.4.

Console errors in text for reference:

> TypeError: Cannot read property 'display_name' of null
> 136.c4fb9fe05c4787076891.opt.js:84

> Uncaught (in promise) TypeError: Cannot read property 'display_name' of null
> async-load-post-editor-editor-author.09dbba50503699f0ea09.opt.js:1

**Comment by gwwar** [comment]
Full Steps:

- In Calypso, add a post or page with a contact form
- Publish the post or page
- Visit the page/post
- Fill in the contact form
- Navigate to https://wordpress.com/types/feedback/{site}
- Edit your feedback

Expected: Feedback loads
Actual: We get a blank page.

**Comment by gwwar** [comment]
Thanks for the detailed report @cecilerainon !
