### ISSUE TITLE
Rewind - Clone: update labels to reference destination server

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#25329]
- The labels currently don't reference that the credentials to enter should be those from the destination server. We should mention this for better clarification.

<img width="769" alt="captura de pantalla 2018-06-06 a la s 18 05 48" src="https://user-images.githubusercontent.com/1041600/41065230-566bae00-69b4-11e8-88d8-de3dd1f9d156.png">

@benhuberman can you please think of some strings for this? The general idea is that for example "Server Address" should be "Destination server address"

- The labels should use sentence case instead of title case, since that's A8c's writing style

**Comment by benhuberman** [comment]
@eliorivero  -- I wonder: instead of clarifying this with every single label (or multiple labels), is there room to add a note somewhere above the first label, saying something like "To give Jetpack access to [the/your] destination server, add your credential details below."

Another question: is "destination server" a commonly understood term for the average user going through this flow? It sounds _a bit_ jargon-y to me, but it's possible I just don't share the same vocabulary with the audience who'd see this language.

**Comment by eliorivero** [comment]
@benhuberman there is this text on top of the form:

<img width="754" alt="captura de pantalla 2018-06-07 a la s 13 27 00" src="https://user-images.githubusercontent.com/1041600/41112868-7c8bcb36-6a56-11e8-8827-c28ba98ed1fb.png">

However, I started this because when I tested it, I erroneously left the server set to the server that would be cloned from, not the one that would be cloned into. You can check the convo here p9rlnk-l7activitylogrewind-p2

**Comment by benhuberman** [comment]
Thanks for clarifying, @eliorivero. So how about this:

- Tweak the current text at the top of the form slightly:
>  Before we can start cloning your site, we need the server credentials for [site name].

note: I'm assuming "site" is correct here ("cloning your site"), but... it might not be, in which case we should change it, obviously.

- I like the addition of specific language around "destination site" before the first label to double down on that point. Suggested edit:
> Make sure the credentials you enter are for the destination site, [site name].

To me these two snippets are enough -- I still think that reminding people about the destination site on multiple labels is potentially overkill. But that's more instinct than anything more reasoned/data-backed, so let me know if you think there's room to add even more.
