### ISSUE TITLE
Sharing: Twitter sharing button does not tweet username

### ISSUE THREAD

**Issue by ajaykj** [Automattic/wp-calypso#25334]
#### Steps to reproduce
1. Go to https://wordpress.com/sharing/buttons/ and enable Twitter sharing button
2. Add your Twitter @ username on the same page in the Twitter username box. Save changes. (This will be included in tweets when people share using the Twitter button.)
3. Go to https://wordpress.com/sharing/ page and connect "Twitter" to your Twitter a/c (This step is necessary for sharing button option to include the TwitterUsername in the tweets.)
4. Go to a single blog post on the site; scroll to the sharing button section; Click Twitter button

#### What I expected

The Tweet to have via @ MyTwitterUsername. 

#### What happened instead

The Tweet contains via @ wordpressdotcom

#### Screenshot / Video
![sharing-screenshot](https://user-images.githubusercontent.com/35197279/41068618-f31d74ce-6a07-11e8-9ead-1eae07832aa9.png)

#### Context / Source

499791-hc, 1206962-zen

**Comment by twhite96** [comment]
I'd like to jump on this. I can take some time this weekend to patch it. That alright?

**Comment by KokkieH** [comment]
We're getting a lot of reports about this via Twitter.

**Comment by sarahcada** [comment]
Also reported here: 1207964-zen

**Comment by cafenoirdesign** [comment]
I'm seeing this issue for clients on VIP (#78910-z)

They set their sharing prefs using the Settings page _wp-admin/options-general.php?page=sharing_
They aren't using Calypso, but this issue is still occurring.

**Comment by sophiegyo** [comment]
Also reported here: 1207767-zen

**Comment by cafenoirdesign** [comment]
Maybe related to:
https://wpcom.trac.automattic.com/changeset/176550

Discussion here:
https://a8c.slack.com/archives/C0299DMPG/p1528368891000341

**Comment by iamgabrielma** [comment]
Reported here: 1207636-zen

**Comment by roccotripaldi** [comment]
Working on a fix now!

**Comment by roccotripaldi** [comment]
this should be fixed in r-176596
