### ISSUE TITLE
Greenkeeper not found

### ISSUE THREAD

**Issue by sagirk** [Automattic/wp-calypso#25338]
#### Steps to reproduce
1. Go to: https://github.com/Automattic/wp-calypso/blob/master/README.md.
2. Check the greenkeeper badge at the very top of the README.

#### What I expected
Greenkeeper to be enabled

#### What happened instead
![image](https://user-images.githubusercontent.com/2608321/41075784-d547c390-6a2b-11e8-8e9f-ed685e0ab692.png)

**Comment by sagirk** [comment]
@blowery Looks like it was only recently fixed: https://github.com/Automattic/wp-calypso/issues/16961. Greenkeeper is not playing nice!

**Comment by blowery** [comment]
Ah, yeah, we're moving off Greenkeeper and on to Renovate. Good eye! 

We should remove the old badge.

**Comment by sagirk** [comment]
@blowery Would it be alright if I raised a PR for that?

**Comment by nylen** [comment]
> Would it be alright if I raised a PR for that?

Definitely, yes please!  You can link it back to this issue as well.

**Comment by sagirk** [comment]
@nylen @blowery It'd be great if either of you could take a look at this PR https://github.com/Automattic/wp-calypso/pull/25376.
