### ISSUE TITLE
Stats: Display time stamp for reports

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#2533]
From feedback:

> Aside: If other stats pages aren’t going to live update, we really need some way to show when it was “generated” and have a refresh link, especially for the desktop app where there is no “refresh”.

Perhaps we could have a new component that would be shown on stats pages that simply displays time ago in words of when the report data was last updated.  Inside that component, also have a link for triggering a refresh.

/cc @jancavan @alternatekev

**Comment by apeatling** [comment]
+1

**Comment by jancavan** [comment]
We could create a "Last updated" component - probably should just be devoid of lots of custom styling so they can easily be added to other already existing components like a card, etc.

**Comment by timmyc** [comment]
So you think having it on a per component/card basis - Or also have it where it could be stand-alone for an entire page?

**Comment by jancavan** [comment]
No, not a per component basis but yes, stand-alone. What are your thoughts?

**Comment by jancavan** [comment]
Btw, displaying time ago would be nice, but I don't think I like the idea of adding a refresh link. The page should just refresh itself and we display when it was last updated. /cc @jblz

**Comment by jblz** [comment]
> The page should just refresh itself

:+1: I think we should requery the data & show updated values when a user becomes active after some period of inactivity & periodically while they are active (one a minute, tops).

The [data-poller](https://github.com/Automattic/wp-calypso/tree/8e1235b37749ca23aa3647d8c655f32fa292a7f0/client/lib/data-poller) library might be useful here as I _think_ it handles the user-activity bit above.

> and we display when it was last updated

My expectation as a user is for numbers that represent the "current" ("instantaneous" in the physics sense of the word) view to always be as up-to-date as is technically possible for the service.

The more I think about it, the less useful I think displaying a timestamp or "time ago" for our stats reporting is -- except for a "print" view (which is necessarily a snapshot of stats at the moment in time it was rendered).

> stand-alone for an entire page

One challenge here is we have a dozen or so endpoints whose return values comprise various "reports":
* day, week, month, year summary pages
* insights
* post summary
* etc.

Our endpoints take various amounts of time to complete, so it's not exactly correct to bump an overall timestamp each time an endpoint returns and call it representative of all the underlying data.

I think the best approach here is to just show the latest data as they come in and indicate in a comprehensive fashion when the report might be stale. There is a lot of work going on at the moment to make Calypso usable while offline and I think some visual cue could be applied that indicates the data are stale.

Related #2333

**Comment by jblz** [comment]
Related: #2966

**Comment by jancavan** [comment]
![screenshot 2018-01-15 12 14 57](https://user-images.githubusercontent.com/4924246/34959977-be878856-f9ed-11e7-88d6-ad321fe9875b.png)

"Last update" has been added and page auto-refreshes so closing this issue.
