### ISSUE TITLE
Reader: My likes - Combined card behaves strangely

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#25403]
When you end up with a combined card in My Likes we should elipses menu with only a single option which seems strange

Uncombined:

<img width="843" alt="screen shot 2018-06-10 at 11 46 23" src="https://user-images.githubusercontent.com/551898/41204606-0c378bb8-6ca4-11e8-83ba-caa06187a765.png">

Combined:

<img width="830" alt="screen shot 2018-06-10 at 11 43 09" src="https://user-images.githubusercontent.com/551898/41204607-10819f88-6ca4-11e8-8ee2-dcdf28654bb7.png">

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if customers report it or if someone wants to work on it.
