### ISSUE TITLE
Incorrect date in the "Your backup is now available for download" message.

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#25406]
#### Steps to reproduce
1. Open the Activity Log URL at https://wordpress.com/stats/activity/oikotimes.com?page=3

#### What I expected

See the correct date and time of the backup  creation.

#### What happened instead

Incorrect date time in the message:

> We successfully created a backup of your site at Thursday, January 1, 1970 1:00 AM!

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/1519466/41208004-4b4b0aea-6d72-11e8-8d3b-23634e61fe6e.png)

## Site info

- Site URL: https://oikotimes.com
- Plan: WordPress.com Business plan (Atomic site)
- Chat: #4215782-hc

**Comment by chaitanyamsv** [comment]
Related to #2343

**Comment by julsyd** [comment]
Also related:
https://github.com/Automattic/jetpack/issues/28366
https://github.com/Automattic/jpop-issues/issues/2348

**Comment by simison** [comment]
FYI @eliorivero

**Comment by eliorivero** [comment]
I'll get to this later today, thanks for the ping.

**Comment by eliorivero** [comment]
I've tested in my site and verified that it's working properly.

<img width="707" alt="captura de pantalla 2018-06-25 a la s 14 11 02" src="https://user-images.githubusercontent.com/1041600/41864929-eb31ea0a-7881-11e8-904e-bf07d342aa96.png">

@chaitanyamsv is it ok to initiate a backup creation in this site? I'd like to test it.

**Comment by chaitanyamsv** [comment]
@eliorivero I can't tell for sure, but I think it is okay to initiate a backup as long as it doesn't create any other problems.

**Comment by eliorivero** [comment]
<img width="1216" alt="captura de pantalla 2018-06-27 a la s 12 57 06" src="https://user-images.githubusercontent.com/1041600/41985427-a3b07de8-7a09-11e8-845b-7175f656d2fc.png">

I accessed the user site using the SWITCH TO USER button in https://mc.vaultpress.com/site/oikotimes.com and the activity log is empty?? It also doesn't seem to have a plan that would allow to backup.

**Comment by rachelmcr** [comment]
It looks like this specific user site was affected by other bugs that are now resolved. Is there further work to be done on the Calypso side, or is it ok to close this issue?

**Comment by chaitanyamsv** [comment]
@eliorivero  Somehow there are two domains of the same name: oikotimes.com 
![okiotimesdotcom](https://user-images.githubusercontent.com/1519466/44567204-7cdc2c00-a7c5-11e8-9093-34a770ad0b85.png)

@rachelmcr I think we can close this now. I just logged in and checked the first domain in the screenshot and the Activity Log looks good.
