### ISSUE TITLE
Calypso serving http://127.0.0.1:41050 when connecting to LinkedIn (WordPress APP)

### ISSUE THREAD

**Issue by adamleone** [Automattic/wp-calypso#25418]
#### Steps to reproduce

This is something that I've found very difficult to reproduce and have not yet done so. This was flagged by this ticket 1210962-zen

1. Starting at URL: https://wordpress.com/sharing/
2. Connect to LinkedIn
3. Write test post
4. Publish (shares to LinkedIn)
5. Check link that is shared to LinkedIn

#### What I expected

A connection to LinkedIn, sharing to LinkedIn as standard. 

#### What happened instead

Exactly that.

#### Browser / OS version

Google Chrome / WordPress Desktop APP .

#### Context / Source

Ticket says:  

"Hi.
This is the second time that my WordPress App shows me that the link to 'LinedIn' is broken. If I press reconnect I am not redirected to LinkedIn but to a site that wants to hire me:  The first link: So something is localy webserving ? http://127.0.0.1:41050 after clicking I land on www.automattic.com
I don't like that."

This P2 could also be related: p3btAN-Ng-p2
-->

**Comment by codebykat** [comment]
For a little more background here, we mark a connection as "broken" after a failed share attempt. You could attempt to reproduce this by revoking your authorization on the LinkedIn side and then trying to share a post -- that should put the connection into a "broken" state, and prompt you to reconnect it.

I would also recommend looking at the site's Publicize report card to see if there are failed LinkedIn shares recently.

**Comment by rezzap** [comment]
The user has reported back on this stating it happens when they use the desktop app on Mac. 

Replied to the user and putting it back on hold for follow up: 1210962-zen

**Comment by rachelmcr** [comment]
This will be fixed when version 3.8.0 of the desktop app is released — it is currently in beta, and users encountering this issue can switch to the beta version (in the app preferences) if they would like to get the fix now. Related desktop issue: https://github.com/Automattic/wp-desktop/issues/391
