### ISSUE TITLE
Korean purchases page typo preventing purchases

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#25417]
History: #user-report 
This issue was brought to us in the WordPress.com public support forums. 
https://en.forums.wordpress.com/topic/typo-in-the-check-out-korean-version/

```
you have a critical typo in the Korean version of check out page.
It says:
만료: YY/MM (expire: YY/MM)
, but actually, your customer has to put MM/YY to complete the check out.
```

#### What I expected
The month and  year fields to be accurate to make a purchase on WordPress.com

#### What happened instead
The month and year fields are switched, you have to enter them opposite of what the fields indicate in order for your purchase to not be denied. 

#### Browser / OS version
unknown

#### Screenshot / Video
not available

**Comment by akirk** [comment]
Thanks for reporting. I have fixed it here: https://translate.wordpress.com/projects/wpcom/ko/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=240095&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc
