### ISSUE TITLE
Reader: Trouble following an RSS feed

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#25434]
One thing I love about our Reader is that it gives me the freedom to follow blogs and sites through open web standards: RSS, for example.

Today I tried adding a new feed like I have done in the past and I was lost as to why I couldn't add it. The video shows it best.

![nofeeds mov](https://user-images.githubusercontent.com/5431237/41275724-1973360e-6e22-11e8-94f8-4233603f770b.gif)

There was no error message, no success message, no console warning so I don't know why there was no follow-through on the search. The URL in the video is the URL I tried with. I think that I tried to do this a couple weeks back and had the same problem but was too focused on what I was doing to ask if it was broken.

**Comment by blowery** [comment]
This seems to work for me. A button appears under the text input that says Follow gutenberg.news/feed and when I click on it, I follow the feed. @dmsnell is it working for you now?
