### ISSUE TITLE
Simple Payments: Buttons not appearing on Biz sites in Edge/IE

### ISSUE THREAD

**Issue by ashercantrell** [Automattic/wp-calypso#25446]
#### Steps to reproduce
1. Starting at URL: WordPress.com
2. Select a Biz site with plugins or custom themes
3. Add simple payment buttons
4. View site in Microsoft Edge or IE

#### What I expected

The payment buttons to appear

#### What happened instead

The payment buttons do not appear

#### Browser / OS version

Microsoft Edge and Internet Explorer on Windows 10

#### Screenshot / Video

Here are the console errors that appear: 
![download](https://user-images.githubusercontent.com/13423946/41300455-c95ae902-6e33-11e8-9f6a-b48bc555fe83.png)

#### Context / Source

Reported via chat, spotted on site oldcourthouse.blog. @senff was able to replicate with a test AT site. Error message shown in the console matches this issue: https://github.com/paypal/paypal-checkout/issues/395

cc @designsimply

**Comment by ashercantrell** [comment]
Chat happened in 4294131-hc

**Comment by designsimply** [comment]
@ashercantrell if this is still happening, we'll want to remove the `[Type] Stale` label. Can you check?

**Comment by ashercantrell** [comment]
I haven't heard anything else about it in over 6 months, and it'd be a big deal if it were still happening, I think, so it's probably okay to close this one out @designsimply
