### ISSUE TITLE
Drafts: support posts with single attached image

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2545]
Raised by @mtias 

The image thumb is meant to show featured-images, since that is one of the most reliable pieces of data for post composition, used by countless themes in very interesting ways — for many editorial flows, it's paramount to know whether a post has a featured image set.

Now, we should also try to make it easy to identify posts, specially those that are just with no text, no title, and an image attached to the content. In this cases, we could also show the image in a similar way.

A frequent case for this need: start a post with the mobile app using the camera to take a picture. This usually ends in a "No title" entry that is completely obscure.

Another thing that could work — given it's the most standard post format across themes — is showing `asides` without a title and just the first line of the body text in a lighter weight.

**Comment by mtias** [comment]
This should be done.
