### ISSUE TITLE
Reader: show who liked a comment on hover

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#25465]
In https://github.com/Automattic/wp-calypso/pull/24612 we added a popover for the like button showing who liked the post.

![39505152-26280ebc-4d96-11e8-8892-804ab340907b](https://user-images.githubusercontent.com/17325/41322416-1960207a-6e66-11e8-88ae-cc8bf85ca570.png)

It would be nice if we could also find out who liked a comment in the same manner.

**Comment by jancavan** [comment]
Hmm, I'm not sure about this since on mobile, tapping the button will Like the post.

**Comment by bluefuton** [comment]
> Hmm, I'm not sure about this since on mobile, tapping the button will Like the post.

@jancavan I concur that it's not a great solution for mobile users. Did we have a design for a non-popup version at some point?

**Comment by jancavan** [comment]
> Did we have a design for a non-popup version at some point?

Yes, I had mockups and a prototype in: wp-p5PDj3-4fQ-p2. 

Essentially, it shows all likers in a row, then you click on the caterpillar to show the popover with everyone's faces. The design is still in its first iteration so if you have any questions or run into issues, we can chat about it :)

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
