### ISSUE TITLE
Store: Create Required WooCommerce Pages Step in Setup Flow

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#25490]
If a WordPress.com site already has a custom theme or plugin installed, and the user initiates the Store setup from within Calypso (in the panel section on the left sidebar), the required WooCommerce pages are created automatically (e.g. Shop, Cart, Checkout, My Account).

However, if the user installs WooCommerce as a plugin through Calypso, the Store will show the setup process, but the required pages won’t be created. If WooCommerce is installed through WP-Admin, though, the plugin's setup wizard is run and installing the pages is one of the steps. 

So, for our Business Plan users, we often see that WooCommerce is installed, but the required pages do not exist. They come to us for help because their store doesn't work. 

The Store dashboard shows the progress of setup steps taken, which makes total sense when the Store setup is initiated through Calypso. It lets users know what still needs to be configured (e.g. shipping, payments, adding products, etc), and this is very helpful. 

As an enhancement, it would be great to have an “Install Required Pages” button/option/step in the Store setup process (exactly like WooCommerce has in WP-Admin > WooCommerce > System > Tools > Create Pages). It would create the required pages, place the necessary shortcodes, and assign the Shop page for the site.

**Comment by timmyc** [comment]
🙇 Thanks @MindyPostoff !
