### ISSUE TITLE
Simple Payments Tour - clicking "Done" button doesn't dismiss

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#25506]
I received a promotional email inviting me to make money from my WordPress.com blog (sweetrootsfarm.com). I clicked through the CTA and followed the wizard but hit a weird bug at the end where the instructional popover wouldn't close.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/somewebsite?tour=simplePaymentsEmailTour
2. Click "Add" as instructed by the wizard. 
3. Now you're on the add page screen. Click "Got it, thanks!" on the wizard popover.
4. Nothing happens

#### What I expected
Popover would close

#### What happened instead
Popover remained and wouldnt close until I clicked elsewhere in the edit toolbar

#### Browser / OS version

Chrome 66, macOS 10.13.4 (High Sierra)

#### Screenshot / Video

https://cloudup.com/cUjBZBk5qAz

**Comment by jancavan** [comment]
cc @Copons @gwwar
