### ISSUE TITLE
Reader: Topics starting with a lowercase letter should not be capitalized

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#2551]
Raised by @aerych 

Topics like iPhone, iOS, ePaper are showing up with the first character capitalized.  This looks like an API issue as the behavior is being reproduced in the iOS and Android apps where it previously wasn't. 

Examples:
<img width="333" alt="screen shot 2015-09-09 at 7 54 22 pm" src="https://cloud.githubusercontent.com/assets/1435271/9777680/ff117622-572c-11e5-882c-afae76d2498d.png">
<img width="364" alt="screen shot 2015-09-09 at 7 54 26 pm" src="https://cloud.githubusercontent.com/assets/1435271/9777681/ff13c760-572c-11e5-8ed8-e1190e406049.png">
<img width="305" alt="screen shot 2015-09-09 at 7 54 51 pm" src="https://cloud.githubusercontent.com/assets/1435271/9777682/ff151bce-572c-11e5-8428-8dd45386c59b.png">
<img width="306" alt="screen shot 2015-09-09 at 7 55 01 pm" src="https://cloud.githubusercontent.com/assets/1435271/9777684/ff16c76c-572c-11e5-82c8-cbba3dcdb400.png">
<img width="341" alt="screen shot 2015-09-09 at 7 55 12 pm" src="https://cloud.githubusercontent.com/assets/1435271/9777683/ff152d1c-572c-11e5-8ba4-3951012dfa42.png">
<img width="325" alt="screen shot 2015-09-09 at 7 55 20 pm" src="https://cloud.githubusercontent.com/assets/1435271/9777685/ff1717e4-572c-11e5-8475-03910568c545.png">

**Comment by lancewillett** [comment]
Confirmed, testing in Safari 8.0.8 on OS X 10.10.5.

Steps to repeat:
1. Log in to wcalypso, Reader tab
2. In left-hand sidebar, find Tags and enter "ePaper" or "iOS" into the "Follow a Tag" input field.
3. Click the plus icon or hit Enter on keyboard to add the tag.
4. Notice the tag title gets rename: "EPaper" and "IOS" with first letter capitalized.

Screencast:
![reader-capitalization](https://cloud.githubusercontent.com/assets/66797/10405439/bf665786-6e8d-11e5-988c-02fdf130962f.gif)

Further note: in the display title for the tag archive (`stream-header__title`) the spelling is also different, not consistent with the tag title in the sidebar or the original input.

Original input: `iOS`
Tag sidebar title: `IOS`
stream-header__title: `Ios`

**Comment by lancewillett** [comment]
See also #1546

**Comment by blowery** [comment]
hrm. half thinking we just lowercase everything, all the time. there's no way to get this right and have it automated.

**Comment by bluefuton** [comment]
> just lowercase everything, all the time. there's no way to get this right and have it automated.

+1. That's how a lot of other sites handle tags.

If we do that, do we want to make the change on the API level, or on each individual UI?

**Comment by blowery** [comment]
> If we do that, do we want to make the change on the API level, or on each individual UI?

API level would be best.

**Comment by bluefuton** [comment]
Fixed in #2775.
