### ISSUE TITLE
Activity: show site picker when visiting `stats/activity`

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#25518]
Currently, when visiting `wordpress.com/stats/activity/` it redirects the user back to `wordpress.com/stats/day/` showing the summary stats of all sites.

I expected the site picker to be presented instead, so I can select a site and see its Activity.

#### What I saw

![image](https://user-images.githubusercontent.com/390760/41462420-b63b4110-708a-11e8-807e-0e61ebbcb7f6.png)

#### What I expected

![image](https://user-images.githubusercontent.com/390760/41462401-a610262a-708a-11e8-8fa5-cc542b2ea571.png)

**Comment by simison** [comment]
Similar behaviour in https://wordpress.com/ads/settings

Both routes use `:site_id` while other routes in Calypso use `:site` — could that be related?
