### ISSUE TITLE
Domains checkout: Unable to add postal code to G Suite checkout form, in order to add new user

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#25547]
Reported in 4401200-hc (follow-up in 1226465-zen). There is at least one other instance in 1224009-zen.

#### Steps to reproduce
1. Starting at `My Sites` > `Domains` > `USER_DOMAIN` > `Email`
2. Click on `Add G Suite` button
3. Complete form by adding first and last names, selecting country from dropdown
4. Clicked in the `Postal Code` field to type in a postal code

![](http://cld.wthms.co/QTyGja+)

#### What I expected

I expected to be able to type a postal code into the `Postal Code` field.

#### What happened instead

Instead, I was unable to type a postal code into the field. The field seems to capture one character that's typed, but not the whole postal code.

It doesn't seem to make a difference which country is selected first.

#### Browser / OS version

User was using Chrome 66.0.3359.181, on Windows 10.0.

I'm using Chrome 67, on macOS 10.13.5

#### Workaround 

There's a workaround to this issue that another HE discovered:

1. Go to `My Sites` > `Domains` > `USER_DOMAIN` > `Email` and click on `Add G Suite` button. If you still have the item in your cart, you can click on the cart icon in `Domains`, and click on the Checkout button to re-open the pending item.
2. Choose the email address you want and hit `Continue`
3. Fill in `First Name`, `Last Name` and choose `Country`
4. Since we can’t type anything in `Postal Code` section now, we can copy a postal code in a note app (or to your clipboard) in advance.
5. Paste it to `Postal Code` section.
6. Reload the page. Then the postal code we pasted shows up.
7. Click on `Continue` to Checkout
8. Proceed with normal checkout process

For some reason, pasting the postal code into the `Postal Code` field, then reloading the page, seems to render the form with the postal code, and other details already entered.

**Comment by ramonjd** [comment]
Looking at this now.
