### ISSUE TITLE
Language Picker: some locales cannot be saved for Jetpack Sites

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#25546]
#### Steps to reproduce
1. Choose a Jetpack (/AT) site from your site list, and select Settings from the sidebar
2.  Under "Language", open the language picker.
3. Choose `कश्मीरी` from the Asia-Pacific tab ('ks') and click on Select Language

#### What I expected
The `ks - कश्मीरी` language to be selected.

#### What happened instead
Instead, I get `ALM Alemannisch`
If I try again I will get `ks - कश्मीरी`, but when clicking "Select Language" then "Save Settings", reloading after the settings are saved doesn't save the locale.

#### Browser / OS version
Mac OS, Chrome

#### Context / Source
This only happens on Jetpack sites.

**Comment by dimafeldman** [comment]
I opened a PR with a fix for that issue here: #25549
