### ISSUE TITLE
NUX: Posts: plug the WP.com Blogging University if you haven't written any posts yet

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#2555]
Suggested by @melchoyce 

If you haven't written any posts (except for default posts we generate, either through the regular signup or Headstart signup), we should promote https://dailypost.wordpress.com/blogging-university/.

cc @michelleweber

**Comment by michelleweber** [comment]
Blogging U. can't really handle that - we're limited in how many signups we can take at the moment, until something changes with how the project is staffed and/or its infrastructure.

Courses also start at the beginning of the month, so depending on when someone saw this message, there might not be another course actually starting for several weeks (and it might not be a course they're interested in). 

But mainly, we need to be careful doing anything that will send registration to levels we can't handle - when we've done things like this before (plugging BU at the end of NUX, in annual reports, etc), we fill classes in a matter of 1-2 hours and have to close down all registration.

**Comment by lancewillett** [comment]
Thanks for your thoughts, Michelle. Makes sense.
