### ISSUE TITLE
Reader: Vimeo embeds in streams don't always expand correctly

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#25575]
#### Steps to reproduce
1. Starting at URL:http://calypso.localhost:3000/read/feeds/59317198
2. Try playing the Vimeo video (first post).

#### What I expected

Vimeo video expanded above the post title and summary, like a Youtube video.

#### What happened instead

<img width="881" alt="screen shot 2018-06-19 at 12 51 54" src="https://user-images.githubusercontent.com/17325/41569718-24fb8898-73c0-11e8-8fcc-85659b3d2860.png">

#### Browser / OS version

Chrome, OS X, 13" Macbook Pro.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if customers report it or if someone wants to work on it.
