### ISSUE TITLE
Remove `secondary` field from `client/wordpress-com.js`

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#25585]
`secondary: true|false` in `client/wordpress-com.js` isn't needed anymore since after single-tree-rendering (https://github.com/Automattic/wp-calypso/pull/19494):

https://github.com/Automattic/wp-calypso/blob/2ed3e056afa2be61698fe6ab491668a6652bd51c/client/wordpress-com.js#L13

We can just check if `context.secondary` isn't `null`.

Similarly `hasSidebar` here could be removed: https://github.com/Automattic/wp-calypso/blob/2ed3e056afa2be61698fe6ab491668a6652bd51c/client/layout/index.jsx#L172

**Comment by tam-nguyen** [comment]
I can remove those

- line 13 at wp-calypso/client/wordpress-com.js
- line 172  at wp-calypso/client/layout/index.jsx

This is also my first time contribution to Calypso.

**Comment by simison** [comment]
@jsnajdr @blowery sorry to assign you directly here but I didn't find a PR for the commits above from @tam-nguyen, but I didn't want them to go unnoticed.

@tam-nguyen did you / could you PR your changes here so that we can review it? Thanks!

**Comment by tam-nguyen** [comment]
Here we go #26234

**Comment by jsnajdr** [comment]
This was fixed in #45216.
