### ISSUE TITLE
UX Proposal: Editor Media Gallery Date Filters

### ISSUE THREAD

**Issue by jakejones1984** [Automattic/wp-calypso#25583]
![date_filters_u](https://user-images.githubusercontent.com/40353716/41593857-56466c30-73b9-11e8-936d-64adbc70d036.png)

Users [have reported](https://github.com/Automattic/wp-calypso/issues/22681) that it's important to be able to display a specific date range of photos when they are shown in the Editor's Google Photos Media modal dialog. 

This is essential for a few reasons

1. Currently the only way to reach older photos is to scroll down and trigger the next set of photos to load. As these only load in batches of 20, if you have a large Google Photos set then this takes a long time and is [very frustrating](https://github.com/Automattic/wp-calypso/issues/25581).
2. Picasa places are hard limit on the number of photos that can be requested (`1000` as reported by @johngodley). This means some users are unable to access their old photos even when they persist with the scrolling approach described above.
3. If you're anything like me, you don't organise your Google Photos but you do know roughly when a given photo may have been taken. As a result the ability to filter by a given range of dates is very useful when trying to locate a photo.

## Potential Solution

A potential solution to this is adding a date filtering UI (see above for prototype of this) to the modal. This would allow a user to set a start and end date to load only photos within those dates.

Doing this requires:

1. Upgrading the Picasa integration to include date filtering using the [`published-min` and `published-max` fields](https://developers.google.com/gdata/docs/2.0/reference#fields) and then upgrading the WPCOM API to allow these filters to be called (note: this still requires investigation to see whether Picasa will actually respect these query parameters).

2. Addition of new UI. It would be good to get some input from Design here to validate and improve the approach above.

**Comment by jakejones1984** [comment]
# Update

Picasa API no longer supports `published-min` `published-max` fields. Therefore to implement this functionality we will need to upgrade the entire integration to use the Google Photos API. This is being discussed internally.

**Comment by drw158** [comment]
The UI shown here looks like to me. I would like to see the date range filter integrated into the search bar.

![screen shot 2018-06-19 at 4 08 19 pm](https://user-images.githubusercontent.com/618551/41624338-029f2c9e-73db-11e8-8c22-3ff6acd37a8d.png)
![screen shot 2018-06-19 at 4 08 19 pm](https://user-images.githubusercontent.com/618551/41624342-04d191a0-73db-11e8-88be-3beffdf7907f.png)

**Comment by jakejones1984** [comment]
@drw158 Thanks very much for your feedback. Very much appreciated.

For technical reasons the search _might_ be disappearing in the near future. That is why I haven't explored the approach you've outlined. 

In addition, I feel the date filtering is probably one of the most important ways to interact with Google Photos (other than filter by Album) and so I was trying to avoid it getting "lost" within the rest of the UI. 

This is being discussed internally on teamtinker P2.
