### ISSUE TITLE
UX proposal: Infinite Loading UI Loading Indicators

### ISSUE THREAD

**Issue by jakejones1984** [Automattic/wp-calypso#25581]
There have been [reports that users are perceiving the editor's Google Photos integration to be slow](https://github.com/Automattic/wp-calypso/issues/22681) (thanks @designsimply for this). Testing on a 3G connection this is actually still relatively fast however the _perception_ is that it is slow which indicates we may have a UX issue here.

Currently the Google Photos modal uses the `<InfiniteList />` component to display and load photos. This does add "loading squares" to show that new photos are loading but there is an argument that we should provide additional UI to indicate loading is in progress. This would make it absolutely _explicit_ that data is being loaded and new content will arrive soon.

The obvious candidate for this is the `Spinner`. See below for a suggested addition of this to the UI (apologies for the weird blurring, but these are my personal family photos!)

![photos_ui_spinner](https://user-images.githubusercontent.com/40353716/41592871-f9c7f7a6-73b5-11e8-817b-0ab62685bed7.png)

I'd like to get some feedback from Design on whether - given the feedback from users - this is a sensible upgrade or whether there is a better approach that could be taken.

**Comment by drw158** [comment]
You're right that the actual loading of the images appears to be adequate. I don't think that additional indicators are needed to show that the images are loading. The square make it clear that images are being loaded. 

The thing that makes it slow is that it looks like only 10 or so images are being loaded at a time. If you look at the video, the api request only loads enough to fill one or two rows. 

It would be better if we could load many times more photos at once. Or if this is impossible, then load about ~35 "loading squares" immediately, then gradually fill them with real photos.

**Comment by jakejones1984** [comment]
Thanks for your feedback @drw158.

Happy to take your lead on the loading spinner (or absence thereof).

I've checked and we seem to be hard limiting to `10` items per paged request. The API should allow us to tweak that using the [`max-results`](https://developers.google.com/picasa-web/docs/3.0/reference#Parameters) parameter to retrieve more per page.

**Comment by folletto** [comment]
I agree on Dave's assessment here. 
Context: we use _skeleton loaders_ in Calypso because they are a way to reduce the perception of waiting compared to explicit loaders. :)
