### ISSUE TITLE
Enhancement: Redirect internal links to public-facing links for visitors

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#25596]
Currently all internal links (website links) like the post edit link, page edit link and all such links should redirect to the public-facing link for visitors. 

Examples of such links:

- Post edit link - https://wordpress.com/post/name.blog/2584
- Page edit link - https://wordpress.com/page/name.blog/2585
- Feedback post edit link - https://wordpress.com/edit/feedback/name.blog/2487
- Testimonial post edit link - https://wordpress.com/edit/jetpack-testimonial/name.blog/2611
- Portfolio project edit link - https://wordpress.com/edit/jetpack-portfolio/name.blog/201

I have come across many users sharing their internal links on the social media, to their friends or with Happiness Engineers when asked. 

It would be helpful if we can redirect these to public-facing links by any means, only for visitors of the website/during the logged out state.

If this issue has come up earlier, or if it's being discussed on this repo already, please point me to it. Thank you!

**Comment by lizkarkoski** [comment]
We had a similar inquiry come to us through Twitter. See here: 
https://twitter.com/davidtedu/status/1009068846546685955

**Comment by supernovia** [comment]
Possible duplicate?
https://github.com/Automattic/wp-calypso/issues/4657

**Comment by arunsathiya** [comment]
Closing this in favor of #4657.
