### ISSUE TITLE
Signup: Theme step should use ThemesList component

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#256]
There is now a reusable Theme and ThemesList components for the theme showcase (/design) that should be used in signup for the theme selection step, for consistency's and maintainability's sake.

**Comment by melchoyce** [comment]
🙌

**Comment by oskosk** [comment]
Please see #1079. I'd appreciate your feedback.

**Comment by oskosk** [comment]
Done by #1079
