### ISSUE TITLE
Store: Renewing business plan still shows "create your store!" message

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#25601]
I renewed my test stores today and after paying I was greated with this success message:

<img width="740" alt="screen shot 2018-06-19 at 3 08 17 pm" src="https://user-images.githubusercontent.com/689165/41619100-014c983e-73d3-11e8-8e52-66737bb10257.png">

We should display a different message for existing stores here.

**Comment by nerdysandy** [comment]
We're going to sunset Store by 22nd Feb 2021. I'm closing this in favor of that.
