### ISSUE TITLE
Creating a new site: getting stuck in the store-nux flow (no free domain)

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#25607]
This is a very similar to #24008 

cc @mattwiebe 

#### Steps to reproduce

1. Starting at URL: wordpress.com (logged in)
2. Switch Sites > Add a new site
3. New WordPress site
4. Fill in site details
5. Only select "Sell products or collect payments"
6. Continue to domain name search
7. Notice there is no free subdomain available
8. Go back to first screen and unselect "Sell products or collect payments"
9. Continue to domain name search 
10. Notice there is no free subdomain available even though "Sell products or collect payments" is uncheck

#### What I expected

I expected to be able to create a new site with a .wordpress.com domain.

#### What happened instead

I was forced into buying a domain even though "Sell products or collect payments" is unchecked.

#### Browser / OS version

Chrome / OSX

#### Screenshot / Video

https://cloudup.com/cX1s0waYtCh

#### Context / Source
I was trying to create a new store test site with the .wordpress.com domain name, which is why I checked the "Sell products or collect payments" box. Once I realized it was forcing me to buy a domain, I clicked back to uncheck the box, but that didn't work either.

Context on why it is forcing a domain for the store signup:

```Just to give you a little background of what's happening here, when you only select "Sell products or collect payments" as a site goal, you are placed in the store-nux signup flow. This flow allows people to create a store right from signup and explains why you don't see any .wordpress.com subdomains along with only seeing the business plan. The reason, is because we need an Atomic site to preinstall plugins for the WP.com store that gets created after signup and being on a business plan with a custom domain is a prerequisite for that.```

**Comment by roccotripaldi** [comment]
@lsinger - have you worked on NUX flows, or can your recommend someone to investigate here?

**Comment by lsinger** [comment]
Those are owned by customer marketing currently so I’d probably ping them in their Slack channel.

**Comment by mattwiebe** [comment]
Thought this was fixed in #24912 - looks like we missed this report. I can replicate only under some conditions, so yeah, some kind of prior state from the `store-nux` flow is being held onto in the domain search step
