### ISSUE TITLE
Cannot run npm start

### ISSUE THREAD

**Issue by longbkit** [Automattic/wp-calypso#25614]
#### Steps to reproduce
1. Starting at URL: https://github.com/Automattic/wp-calypso/
2. Clone repo in ubuntu
3. Go to root dir
4. npm start

#### What I expected
wp-calypso should be started normally

#### What happened instead
Failed with error: 
sh: 1: run: not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-calypso@0.17.0 start: `npm run -s build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wp-calypso@0.17.0 start script.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/562164/41653395-20684050-74b0-11e8-8cce-3cd1d2fb3dbc.png)

#### Context / Source
Checking package.json, the follow caused error:
"build-css": "run -p -s build-css:*",

what does "run" mean in this case?

**Comment by longbkit** [comment]
Luckily, I have fixed it with the following, hope to help others with similar situation:

npm install -g npm-run-all
change run to npm-run-all, the npm-run-all script is to run many configuration in a simple syntax, for example npm-run-all build:* to run all available configuration such as build:css, build:desktop...

**Comment by keoshi** [comment]
@longbkit Happy you found a solution, thanks for sharing it with others! Closing this for now.

**Comment by longbkit** [comment]
@keoshi  Do you have any idea why could everybody else run the command "run -p -s build-css:*"?  Is my way of resolving correct and is there any fix for this in the future?
