### ISSUE TITLE
Widget: Contact Info Widget incorrectly adds API key to the end of the API request

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#25612]
#### Steps to reproduce

1. User added Contact Info widget, and added their API key to the widget to enable Google Maps
2. User noticed that the Map API call failed (see details from user below)

#### What I expected

Adding API key to widget should result in map from Google Maps being displayed in the widget.

#### What happened instead

According to the user:

>Contact and Info widget creates non-compliant tag for Google maps API - so we can't restrict the key's use outside our domain.
>Widget puts maps API ket at the end of request string - instead of at start as per G API spec.
> Here's the widget's generated string - using our key at end: src="https://www.google.com/maps/embed/v1/place?q=24+Grafton+St+Balmain+NSW+2041&key=redacted"
> Map API call fails because we restrict domain - and the supplied key is lost because widget has it out of place.
> Here''s the docs - API key goes at start of request - not the end. https://developers.google.com/maps/documentation/embed/guide#forming-the-url
> My API key is naked (so any site can use it) so grateful if someone can fix this.

The user's API key is in the chat transcript.

#### Browser / OS version

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

#### Screenshot / Video

None produced.

#### Context / Source

User report in 4440720-hc

**Comment by samiff** [comment]
While doing [testing over here](https://github.com/Automattic/jetpack/issues/10355#issuecomment-484748746), I thought I'd have a look at this issue as well. I'm not able to reproduce the behavior described here, as I'm able to add site restrictions to my API keys, and see that work as expected.

The order of the URL query parameters shouldn't matter in this case, and produces identical responses from Google either way.

I've followed up with the user in 1972264-zd to see if they have any further details.
