### ISSUE TITLE
Site Pages section in Calypso is not showing number of pages

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#25615]
#### Steps to reproduce
1. Open the Site Pages section in Calypso (any site, conventional or also Atomic). For instance https://wordpress.com/pages/raulantontest2.wordpress.com  
2. There are no number of pages in each category/status/tab
3. If you open the Blog Posts section (https://wordpress.com/posts/raulantontest2.wordpress.com) you have a number indicator.

#### What I expected

I expected Site Pages section to be coherent with Blog Posts section and provide with this information

#### What happened instead

Pages Section has no numbers in the Page status tabs.

#### Browser / OS version

Any

#### Screenshot / Video

<img width="811" alt="site pages site title wordpress com 2018-06-20 13-21-19" src="https://user-images.githubusercontent.com/6404071/41655546-7ec4afbc-748d-11e8-8f5b-d8dccd804f86.png">
<img width="803" alt="blog posts site title wordpress com 2018-06-20 13-22-04" src="https://user-images.githubusercontent.com/6404071/41655584-9417949c-748d-11e8-9436-14f7122aef23.png">

**Comment by lancewillett** [comment]
Good find!

Possibly related to #2132 and #14243

**Comment by jordesign** [comment]
Closing this as no longer reprodicible. Calypso now shows page counts by default.
