### ISSUE TITLE
Reader: unable to follow sub-domain

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#25653]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/following/manage
2. Try to follow "http://bluefuton.micro.blog/"
3. You end up subscribed to the main micro.blog domain, where no posts are shown.

#### What I expected

Subscribed to posts on bluefuton.micro.blog.

#### What happened instead

Subscribed to micro.blog, which shows no posts.

#### Screenshot / Video

<img width="877" alt="screen shot 2018-06-21 at 12 06 22" src="https://user-images.githubusercontent.com/17325/41690835-89719808-754b-11e8-8608-544f1de9c151.png">

**Comment by roo2** [comment]
this has now been fixed
