### ISSUE TITLE
Purchases: Verification screen for cancelled purchase

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#257]
When they cancel an upgrade users are being sent to the legacy upgrade management page:

<img width="982" alt="screenshot 2015-11-20 10 06 01" src="https://cloud.githubusercontent.com/assets/275961/11297152/7293f0ce-8f6e-11e5-8417-d446d9159b22.png">

We should move this notice to Calypso.

**Comment by umurkontaci** [comment]
@scruffian I can't reproduce this. Is this still an issue?

**Comment by fabianapsimoes** [comment]
@umurkontaci you need to cancel an upgrade that requires confirmation via email, like a plan or a Premium theme for example.

The link in the confirmation email points to WP-Admin, which redirects to Atlas. It's something like `https://yoursite.wordpress.com/wp-admin/paid-upgrades.php?action=unsub
