### ISSUE TITLE
Activity: collapse updates wrapper with more than X items

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#25707]
If a particular site has more than X updates available, we should collapse the updates wrapper to show the oldest Y and unfold them gradually.

![screen shot 2018-06-22 at 12 10 01 pm](https://user-images.githubusercontent.com/390760/41791580-059f168c-764e-11e8-9b82-42ab9ad684f7.png)

**Comment by keoshi** [comment]
Some context first:

- Yes, the list of things that require an update might be gigantic...
- ...but we shouldn't shy much away from telling customers to update them.
- We want users to stay safe, so even collapsing the list might hide certain items that might break the site if they go un-updated.
- In my solution I've added a single control to expand the list. Once it's expanded, you won't be able to collapse it again.

@MichaelArestad @eliorivero what do you think about this?

![al-threats-06 copy](https://user-images.githubusercontent.com/390760/41792484-ecdea70e-7650-11e8-95e8-7f1ab0bfa252.png)

![al-threats-06 copy 2](https://user-images.githubusercontent.com/390760/41792489-f06030a0-7650-11e8-8eda-7021465b5bac.png)

**Comment by MichaelArestad** [comment]
What if we just have the very top part and make it an expandable card?

This part:

![image](https://user-images.githubusercontent.com/1123119/41793715-31afcf3e-761a-11e8-8b2e-a8c8eec711a7.png)

And then on mobile, it could be almost identical, but instead of an expandable card, it just takes the user to a new view with the list.

**Comment by keoshi** [comment]
That was my first instinct too, but turning that into an expandable card means it can be collapsed back. I almost don't want it to collapse at all. Security should be what dictates what the form should be: this module isn't meant to look pretty, it's meant to tell you your site is currently (probably) not safe.

**Comment by MichaelArestad** [comment]
Well then maybe instead of an expandable card, we add a secondary button to the left of update all that says `Show all`?

**Comment by keoshi** [comment]
@MichaelArestad That makes a lot of sense. Let's do that!

**Comment by keoshi** [comment]
@eliorivero Assigned this to you, but please confirm if you have bandwidth to tackle this now, and let's work together on it.

**Comment by eliorivero** [comment]
Yeah , this is something I've been experimenting to and was also thinking about collapsing it so let's do it!
