### ISSUE TITLE
Editor: Trash post not working on first attempt

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#25702]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Add a Headline and body text
3. Wait for "Move to trash" button to appear
4. Click "Move to trash"
5. Click "Move to trash" again on confirmation modal

#### What I expected
I expected the post to be moved to trash and to be taken to trashed posts view

#### What happened instead
Nothing happened in the browser. There was an error in the console:

137.5e32285f13c4fb6e0f9a.opt.js:100 Uncaught TypeError: Cannot read property 'getState' of undefined
    at Xl (post-editor.5ab27a93a1c68c4a2dd6.opt.js:72)
    at 137.5e32285f13c4fb6e0f9a.opt.js:92
    at e (137.5e32285f13c4fb6e0f9a.opt.js:92)
    at L (build.c0b17b767bed4957654b.opt.js:13)
    at 137.5e32285f13c4fb6e0f9a.opt.js:92
    at e (137.5e32285f13c4fb6e0f9a.opt.js:92)
    at build.c0b17b767bed4957654b.opt.js:13
    at 137.5e32285f13c4fb6e0f9a.opt.js:92
    at e (137.5e32285f13c4fb6e0f9a.opt.js:92)
    at Function.k.dispatch (137.5e32285f13c4fb6e0f9a.opt.js:92)

If I try again a second time, the post is trashed as expected.

#### Browser / OS version
Version 67.0.3396.87 (Official Build) (64-bit), MacOS 10.13.5

#### Context / Source

This was found by e2e tests

**Comment by nylen** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/25703
