### ISSUE TITLE
Activity: remove credentials banner on free sites

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#25706]
The banner that invites the user to `Add site credentials` shouldn't be visible on free sites, since that plan doesn't support backups or restores.

![screen shot 2018-06-22 at 12 10 01 pm](https://user-images.githubusercontent.com/390760/41791489-c932d242-764d-11e8-9ec4-2dd2deacb54b.png)

**Comment by roccotripaldi** [comment]
this was fixed in #25716 
Thanks so much @millerf !

**Comment by millerf** [comment]
My pleasure. Quite an easy fix :)El dia 24 de jul. 2018 20:50, Rocco Tripaldi <notifications@github.com> va escriure:this was fixed in #25716
Thanks so much @millerf !
