### ISSUE TITLE
DSS: Remove remnants

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#2571]
I've noticed that there is still `lib/dss`, which doesn't seem to be used anymore (and a single line related to `dss` in `assets/stylesheets/shared/functions/_z-index.scss`). Is it safe to remove that now?

CC @sirbrillig @kwight

**Comment by kwight** [comment]
Yes, those can safely go. We were keeping the library knowing that we'd be coming back to DSS, but then ripped the rest of it out anyways (and we're not clear when revisiting it in earnest will happen). Thanks!

**Comment by sirbrillig** [comment]
Agreed. (Previously discussed in #2193)
