### ISSUE TITLE
UX Proposal: Domain Mapping Button

### ISSUE THREAD

**Issue by rfaile313** [Automattic/wp-calypso#25714]
Many users that have a domain registered outside of WordPress.com end up beginning a domain transfer, when really, they only want to map it.

#### Steps to reproduce
1. Starting at URL: WordPress.com
2. Click Domains
3. Click Add Domain
4. Click Already own a domain? -> Use a Domain I Own

#### What I expected
Users often enter their domain into the box and hit the "Transfer to WordPress.com" because it's the most prevalent thing on the page. 

My suggestion is too add a similar button for mapping below the second box "Map to WordPress.com" - users often seem to miss the <a> link: `manually connect it`.

#### Screenshot / Video
![design change](https://user-images.githubusercontent.com/13829168/41797883-4afa4a02-7631-11e8-8918-ee4d21469354.png)

#### Context / Source
Just based on user feedback. Many domain mapping tickets might be eliminated with a simple button addition.

**Comment by rfaile313** [comment]
More context for why we need this in p7DVsv-4Pc-p2

**Comment by drw158** [comment]
The button should be put inside of the card titled "Manage your domain separately". Probably as a secondary style button.

Other than that, seems like a good improvement to me.

**Comment by wensco** [comment]
Thanks for the report @rfaile313. Making changes to the UX was already planned and we launched changes several days ago. The new flow should make it clear to users that they have the option to transfer or map.  

Users are now presented with this option as described in our [support documentation](https://en.support.wordpress.com/incoming-domain-transfer/):
https://en-support.files.wordpress.com/2018/07/dom_flow.png

I'm going to mark this issue closed, but feel free to re-open it if you have other related feedback to share. Thanks!

**Comment by rfaile313** [comment]
@wensco YES! That looks WAY better. SO much more clear and expletive. 

Do all users see this at https://wordpress.com/domains/manage/ in the normal flow?

**Comment by wensco** [comment]
> Do all users see this at https://wordpress.com/domains/manage/ in the normal flow?

@rfaile313 all users will see it but not directly from /manage. That new transfer/map screen only shows up if they add a domain and then choose "use a domain I already own". So from https://wordpress.com/domains/manage/, they would first need to click "Add" and then select to use a domain they already own.

They will also see that same transfer vs map screen if they create a new site in Step 2 (https://wordpress.com/start/domains).

**Comment by rfaile313** [comment]
@wensco Beautiful. That answered my question perfectly.
