### ISSUE TITLE
Sites: the title (in the head) should not be straight "WordPress.com"

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2572]
Raised by @m

Noticed [a] bug in my sites:

* The title of the page (in the head) seems to be straight “WordPress.com”. 

(p3fqKv-1yY-p2)

**Comment by lancewillett** [comment]
Closing as "works for me" — it's not common to go directly to https://wordpress.com/sites — and the main WordPress.com pages all have custom titles.
