### ISSUE TITLE
Contact Form: in Calypso "date" field type is missing

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/wp-calypso#25738]
In the WP Admin editor, if you add a new contact form, Date is an option in the field type list. In Calypso editor, it is not.

#### Steps to reproduce
1. Create new page
2. Insert Contact form
3. Click edit to edit the form
4. Click on Field Types to see list

#### What I expected
I expected to see the same list of Contact Form Field Types in both editors

#### What happened instead
Calypso doesn't show Date as option in Contact Form Field Types

#### Browser / OS version
All

#### Screenshot / Video
WP Admin editor: [https://cldup.com/d7uW94JvRt.png](url)
Calypso editor: [https://cldup.com/vJb2gE3Doj.png](url)

Suggest adding Date field to Calypso Contact form Field Types to match WP Admin.

Forum thread: [https://en.forums.wordpress.com/topic/suggestions-for-stay-like-theme/](url)

**Comment by lancewillett** [comment]
Thanks for the report — this is something we hope to improve in the future, both in Jetpack and WordPress.com. But, it could be lower priority than building a Gutenberg "Contact Form" block, so I'm going to close this ticket for now.
