### ISSUE TITLE
Clone site - Add tracking

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#25758]
We need to make sure we're tracking how far people get in the flow and whether a clone was successful. If there's a button in the UI, let's add tracking to it. This will help us spot drop-offs or pain points.

**Comment by keoshi** [comment]
In terms of what Michael said I think this can be split into two categories:

- **Flow progress**
- **Cloning status**

_Disclaimer_: not sure about the naming of the events below, I'm sure you have better suggestions.

### Flow progress

1 - For **Flow progress** it would be valuable to have a tracks event that allow us to know in what step of the process they are. So for example, we'd have one per each of the 6 steps: `wpcom_cloning_flow_step3_visit`, `wpcom_cloning_flow_step6_visit`, etc.

2 - It would be cool to track every action, as @MichaelArestad says, which would include all buttons, such as the Save button on the credentials form in step 3: `wpcom_cloning_flow_credentials_save_click`.

3 - If any errors occur in any of these steps, it would be awesome to have them registered in tracks as well, possibly with additional params?
  - `wpcom_cloning_flow_credentials_error`
    - `error_type` : `incorrect_protocol` (example; from p9rlnk-ne-p2 )

4 - In terms of the back button, it would also provide some insight to where people might be unsure, confused, over their head, etc. If we can track this on a per-step basis, the better: `wpcom_cloning_flow_step3_back_click`; if not, this would be good too: `wpcom_cloning_flow_back_click`

### Cloning status

When a site cloning has started we should keep track of three possible outcomes (that I can see right now, let me know if there are more):
- Cloning success: `wpcom_cloning_site_success`
- Cloning error: `wpcom_cloning_site_error` (possibly with additional params including the reason?)
- Cloning cancelled: `wpcom_cloning_site_cancelled`

Does all of this make sense, @rcoll ?

**Comment by rcoll** [comment]
1. The flow progress is already tracked natively by Calypso's start framework. The events are named `calypso_signup_step_start` and will carry properties for the flow `clone-site` and then the step name. We should easily be able to create a funnel based on this.

2. I've [added an event](https://github.com/Automattic/wp-calypso/pull/25810) to the credentials form, `calypso_rewind_credentials_save_alternate`, which will carry an error property that, when empty, means the form was submitted without validation errors. This _does not mean_ the credentials were saved, simply that they were submitted for testing. We'll have to add an event to the Rewind backend to record whether the credentials were stored or not. This is not straight-forward in Calypso.  Any validation errors will be present in the `calypso_rewind_credentials_save_alternate` errors array. 

3. Yep, see #2. The only place where this really can happen is the credentials form. Unless we need to validate the site title and url in step 2. I really don't think that's necessary though. Thoughts?

4. Yep, this also happens natively by Calypso's start framework. The events are named `calypso_signup_previous_step_button_click`, and again, carry properties for which flow and step they were fired on. We should be able to create a funnel for these.

**Comment by keoshi** [comment]
Perfect, I think we're covered then. Thank you so much for all the details!

> Unless we need to validate the site title and url in step 2. I really don't think that's necessary though.

I don't think we need, not for the site name certainly. Is the site URL used persistently anywhere, given it's the credentials we actually use to clone the site?
