### ISSUE TITLE
My Purchase: Sort by "action needed"?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#25786]
#### Steps to reproduce
1. Have a purchase recently expired or soon-to-expire.
2. Get multiple e-mails reminding me of upcoming/expired purchase
3. Starting at URL: https://wordpress.com/me/purchases
4. Observe order of purchases

#### What I expected
Easily find the purchase where action is needed.

#### What happened instead
I needed to scroll around to find it.

#### Screenshot / Video
![screen shot 2018-06-27 at 10 13 58-fullpage](https://user-images.githubusercontent.com/88897/41983448-c053c1d2-79f3-11e8-8f6e-059432a8162b.jpg)

#### Context / Source
I've been getting e-mails about upcoming domain registrations/plans that are going to cancel soon and remembered while working today. Instead of trying to find the e-mail, I went to WordPress.com to the purchase list to find it myself. I found that for me (and our customers who utilize plans/domains for more than a few sites, it took more work than I expected to make the renewal.

#dogfooding

**Comment by prettyboymp** [comment]
This is a valid issue, however, I don't think it will be something we get around to fixing anytime soon.  The number of users with this many purchases is limited and we are already in the process of making other improvements to the dunning emails to give directly links to the purchases that need attention.
