### ISSUE TITLE
Activity log: upgrade nudge visible for monthly Jetpack Pro subscribers

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#25799]
We show update -nudge at the top of the Activity log:

![image](https://user-images.githubusercontent.com/87168/42025695-e0828b48-7acd-11e8-8ff5-ea8042e43415.png)

This nudge is visible for Jetpack Pro _monthly_ subscribers, although there's nothing they could upgrade to.

![image](https://user-images.githubusercontent.com/87168/42026597-2c022900-7ad0-11e8-9ba2-d64d7a8edfd6.png)

#### Steps to reproduce
1. Create a new Jurassic Ninja website
2. Connect Jetpack
2. During the connection, add a Pro plan (paid monthly -version) 
3. Go to AL in Calypso: https://wordpress.com/stats/activity
4. Observe the upgrade nudge appear

#### Context / Source
- p8oabR-ej-p2 #comment-1834
- p1530178599000292-slack-activity-log

/cc @arunsathiya @eliorivero

**Comment by keoshi** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/22452

**Comment by keoshi** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/23772

**Comment by keoshi** [comment]
I think the best way to move forward here is to bring back @roccotripaldi 's banner on this PR: https://github.com/Automattic/wp-calypso/pull/25537 and adjust the copy:

```
<Banner
	callToAction={ translate( 'Get daily backups' ) }
	dismissPreferenceName="activity-upgrade-banner-jetpack"
	event="activity_log_upgrade_click_jetpack"
	feature={ FEATURE_OFFSITE_BACKUP_VAULTPRESS_DAILY }
	list={ [
		translate( 'Secure your entire site with automatic daily backups' ),
		translate( 'See all site activity over the past month' ),
	] }
	plan={ PLAN_JETPACK_PERSONAL }
	title={ translate( 'Secure your site with daily backups' ) }
/>
```

**Comment by tyxla** [comment]
This seems to be popping up again in p1HpG7-5iF-p2 #comment-26670
