### ISSUE TITLE
Checkout: too many links on checkout form

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2579]
Raised by @p3ob7o 

The checkout form has a fully functional toolbar, as well as admin notices containing multiple links.

Each one of these is a potential distraction, we should limit links in checkout to the bare minimum for users who specifically want to cancel the process and go back to their previous location.

![screen shot 2016-01-19 at 11 05 40](https://cloud.githubusercontent.com/assets/1119271/12424173/e5794e10-be9c-11e5-960e-1f94c7b5cfce.png)

**Comment by breezyskies** [comment]
Being tested in https://github.com/Automattic/wp-calypso/pull/2558.

**Comment by breezyskies** [comment]
https://github.com/Automattic/wp-calypso/pull/2558 is now live. Going to close this one.
