### ISSUE TITLE
Cannot edit images inside the editor in MS Edge

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#25797]
#### Steps to reproduce
1. Add an image inside a post or page.
2. Click on it to show up the toolbar
3. It flashes for a second, then disappears.

#### What I expected
When I clicked on the image to see the toolbar without disappearing.

#### What happened instead
The toolbar disappeared. 

#### Browser / OS version
EDGE 42.17134.1.0

#### Screenshot / Video
http://take.ms/9xHRU (props to @keithlocka8c for helping out an outdated brother :) )

Case: #4644862-hc
Followup #1248250-zen

It appears to be caused by the very recent update of Edge as I wasn't able to replicate it on a previous version.

**Comment by thesacredpath** [comment]
Also encountered by a user in this forum thread: [https://en.forums.wordpress.com/topic/real-time-image-editing-not-working-more/#add-note](url)

**Comment by gsmumbo** [comment]
Also encountered on two sites by a user with Jetpack in #1248069-zen

**Comment by AtrumGeost** [comment]
Got another report, his time on Internet Explorer #4700123-hc
