### ISSUE TITLE
Site Settings: Change message wording to specify usernames

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#25812]
Change the "Somebody else owns this site's connection..." and "Somebody else is the plan purchaser.." message wording on /settings/manage-connection/SITEURL to specify the Site Owner and Plan Purchaser **usernames** to help clarify roles and points of contact.

**Before**
<img width="788" alt="screen shot 2018-06-28 at 1 30 56 pm" src="https://user-images.githubusercontent.com/204742/42056470-925598c0-7ad7-11e8-85b4-959845eda2cf.png">

**After** 
<img width="793" alt="screen shot 2018-06-28 at 1 35 56 pm" src="https://user-images.githubusercontent.com/204742/42056687-4339e088-7ad8-11e8-94bf-0c7731772dce.png">

See: p6TEKc-29d-p2 #comment-5042 and p1HpG7-5iF-p2 #comment-26656

**Comment by tyxla** [comment]
We could also apply that to the notices:

![](https://cldup.com/PxoA_QlFLs-3000x3000.png)

**Comment by Aurorum** [comment]
I think that I've come up with a patch for this regarding the site owner that I can open as a PR soon, but not for the "Plan purchaser" part, which I hope won't be a problem! I don't have access to a Jetpack site with a paid plan so I can't work on that bit. :)

<img width="1005" alt="Screenshot 2020-06-30 at 10 36 55" src="https://user-images.githubusercontent.com/43215253/86111101-43aa2c80-babe-11ea-895a-e269e564147a.png">

**Comment by Aurorum** [comment]
PR for that in #43788. :)
