### ISSUE TITLE
Domain Management: cannot disable a Site Redirect

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2581]
Raised by @mkaz 

I have a site redirect setup on mkaz.wordpress.com pointing to mkaz.com
I want to remove this site redirect but either its not possible, or I can't figure out how.
I tried blanking the form and submitting and it gives an empty error

![screen shot 2016-01-19 at 11 30 49](https://cloud.githubusercontent.com/assets/1119271/12425166/830f32c6-bea1-11e5-8f55-b1a5b119b7aa.png)

![screen shot 2016-01-19 at 11 30 57](https://cloud.githubusercontent.com/assets/1119271/12425173/8960dca6-bea1-11e5-95f8-9b93f10de63c.png)

In the past, wp-admin for managing site redirects used to look like this:

<img width="924" alt="12047" src="https://cloud.githubusercontent.com/assets/1119271/12425222/bb7def1c-bea1-11e5-86b0-39d09a6cce63.png">

**Comment by umurkontaci** [comment]
You can disable Site Redirect by changing Primary Domain to something else.

Closing as non-issue.
