### ISSUE TITLE
Simple Payments: Payment buttons sometimes not working for e2e tests

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25822]
Our e2e tests payment button tests are sometimes failing, where a post or a page is created with a payment button that doesn't work.

I tried in Chrome (which the e2e tests use) and can't get the button to work on this post:

1. https://e2eflowtesting3.wordpress.com/2018/06/29/payment-button-small-alpacas-shrug-softly/
2. https://e2eflowtesting3.wordpress.com/payment-button-page-fearless-otters-fight-sadly/

Example of page on the same site that works:

https://e2eflowtesting3.wordpress.com/payment-button-page-burly-camels-kneel-tensely/

console error:

```
Uncaught TypeError: window.setupButton is not a function
    at button?env=production&commit=1&style.label=pay&style.shape=rect&style.color=silver&style.fundingicons=true&sessionID=bbce8ab0f5_ga2dumjqhi2do&buttonSessionID=c0900b45c0_ga2dumjvhi2do&funding.disallowed=venmo&funding.remembered=paypal&locale.x=en_AU&logLevel=warn&uid=ebdce7f72a&version=4&xcomponent=1:1033
(anonymous) @ button?env=production&commit=1&style.label=pay&style.shape=rect&style.color=silver&style.fundingicons=true&sessionID=bbce8ab0f5_ga2dumjqhi2do&buttonSessionID=c0900b45c0_ga2dumjvhi2do&funding.disallowed=venmo&funding.remembered=paypal&locale.x=en_AU&logLevel=warn&uid=ebdce7f72a&version=4&xcomponent=1:1033
14:15:52.081 
```

<img width="1627" alt="screen shot 2018-06-29 at 2 18 18 pm" src="https://user-images.githubusercontent.com/128826/42072992-51acbdaa-7ba7-11e8-9771-a5daa41ae2f5.png">

**Comment by alisterscott** [comment]
@gwwar any ideas about this?

**Comment by gwwar** [comment]
cc @Automattic/lannister

**Comment by gwwar** [comment]
@alisterscott The example pages on the summary lead to a Page not Found. Do you have other examples?

Without looking at code, I would imagine, maybe a permissions error with the user, or a script loading error.

**Comment by alisterscott** [comment]
> @alisterscott The example pages on the summary lead to a Page not Found. Do you have other examples?

Sorry that site reguarly gets reset because of issues where we have too many posts and pages, and the new posts aren't doing it anymore.

I'll close this as can't reproduce for now - and will reopen if this happens again.

**Comment by alisterscott** [comment]
I found another bug retesting this: 25839
