### ISSUE TITLE
No picture preview in the Edit tab of Image Gallery above captions in the page editor.

### ISSUE THREAD

**Issue by mrsunilchauhan** [Automattic/wp-calypso#25837]
On Zendesk ticket:

#1252731-zen

The user has reported a problem about their page at:

https://fotograf-fuer-fotoshooting.com/paar-fotoshooting/

The issue is that when you click on the image gallery on the page editor, the images show when you are in the Preview tab but they do not show when you are in the Edit tab.

I have annotated the screenshot for you to see what user wanted to communicate. You can look at the screenshot at the link below:

https://d.pr/free/i/gpeol5

I have tried searching around the field guides and support documentation but could not find anything relevant.

When I tried to replicate this issue on my WordPress test Premium Plan site since the user is also on WordPress Premium plan, I could not replicate their issue and it worked fine for me there but on user's site it is an issue.

I would appreciate if you can take a look at this and see what we can suggest to the user.

**Comment by lancewillett** [comment]
Thanks for the report. Let's try to find more examples and see if it's specific to the one site — or a more widespread issue.

Next time you see something like this, can you check the JS console and see if there are any errors? That could point to a 404 on the server which would be out of our control.

**Comment by KokkieH** [comment]
Another report in https://en.forums.wordpress.com/topic/editing-tiled-gallery-with-block-editor/

I'm able to replicate on a test site in both classic Calypso and the Classic Editor block in Gutenlypso, i.e. only with the Calypso gallery overlay. It only appears to happen on sites that are set to private - plan and custom domain vs free address makes no difference.

I do not see any console errors when clicking on the Edit tab.

Additional steps:

Set the site to hidden/public. Edit post, edit gallery, and switch to Edit tab. Images now show.

Set the site back to private. Edit post, edit gallery and switch to Edit tab. Images still show.

Add a new image to the gallery, and switch to Edit tab. Previous images show, but the new image again has a broken image icon.
