### ISSUE TITLE
Draft Won't Save in Calypso Using Windows 

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#25836]
#### Steps to reproduce
1. Open a draft in the new editor (wp-admin saves fine) in Chrome while using Window 7 or 10
2. Edit a draft.
3. Save.

#### What I expected
I expected the draft to save. 

#### What happened instead
The draft does not save, and when closing out, a message appears prompting a save.

#### Browser / OS version
Chrome (and possibly other browsers according to initial reporter--asking for more specific information on that).

#### Screenshot / Video

![saving](https://user-images.githubusercontent.com/2545184/42125436-c0a7e994-7c44-11e8-8273-0e018363b293.gif)

#### Context / Source
#1238087-zen
#1239436-zen

#user-report

**Comment by ChrissiePollock** [comment]
Another one: #1253171-zen

**Comment by ChrissiePollock** [comment]
#1252792-zen Chrome and Explorer - both have the same problem.

**Comment by ivan-ottinger** [comment]
Probably related: https://github.com/Automattic/wp-calypso/issues/9833

**Comment by ivan-ottinger** [comment]
Device information from the user: PC, Win 10.

**Comment by blazevivan** [comment]
User contacted us regarding the update on this. #1238087

**Comment by liviopv** [comment]
Hi @bsessions85 👋 I see you're watching this ticket. Is there any estimate of when this will be investigated/worked on?

**Comment by bsessions85** [comment]
Hi @liviopv no, I don't have any idea. Adding the high priority label was a good start

**Comment by rachelmcr** [comment]
I just tested this in VirtualBox using Win10/Chrome 68.0.3440.106. I wasn't able to reproduce the issue as described here. I tried both clicking on "Save" and letting the draft autosave on its own; in both cases the post saved and I could close the editor without the AYS prompt.

Are customers still reporting this as an issue? If not, this may have been resolved indirectly.

**Comment by rachelmcr** [comment]
I'm closing this issue, but please reopen and include further details if you are still seeing reports of this.
