### ISSUE TITLE
Simple Payments: can't see payment buttons on posts when scrolling through posts page

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25839]
#### Steps to reproduce
1. Starting at URL: A test business site (eligible for payment buttons) with a blogs page with a number of posts
2. Scroll down through posts and  find an old post - edit it and add a payment button
3. Revisit the homepage or posts page and scroll down to find your post

Example site: https://testsiteonlyforjuiced.blog

#### What I expected

A payment button

#### What happened instead

Payment button doesn't show. Clicking on post shows the payment button.

#### Browser / OS version

Chrome, Firefox and Safari on macOS

#### Screenshot / Video

![payment button scroll](https://user-images.githubusercontent.com/128826/42141876-72a06a26-7def-11e8-8929-093e9422cd2a.gif)

**Comment by rodrigoi** [comment]
This happens because this javascript:

```js
wp_add_inline_script( 'paypal-express-checkout', sprintf(
	"try{PaypalExpressCheckout.renderButton( '%d', '%d', '%s', '%d' );}catch(e){}",
	esc_js( $data['blog_id'] ),
	esc_js( $attrs['id'] ),
	esc_js( $data['dom_id'] ),
	esc_js( $data['multiple'] )
) );
```

executes before `paypal-express-checkout.js` is loaded (when the post enters the viewport). The question I have is if that's a theme specific event or something we can attach to, to try render the button again.

**Comment by gwwar** [comment]
@rodrigoi Unless folks have particular hooks in mind, I think we can wait for a promise of callback once the script has loaded. If we don't have an easy hook into that, then checking if the window var is available on an interval (that stops on a success) would do the trick.

eg
```js
paypalExpressCheckoutLoaded.then( () => PaypalExpressCheckout.renderButton( ... ) );
```

cc @davidakennedy if he happens to know offhand of theme specific events

**Comment by gwwar** [comment]
Another thought that comes to mind is if we can load `paypal-express-checkout.js` for the site once, instead of a post dependency if we know that a site has at least one simple payment.
