### ISSUE TITLE
Activity/Plugin: back button should go back to the AL

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#25843]
When I update a plugin on my site, the Activity log shows me this:

![image](https://user-images.githubusercontent.com/390760/42170195-c2248fb4-7e0d-11e8-93ae-6caeb4e6d5a2.png)

When I click the plugin name link above, I’m redirected to its page with all the info:

![image](https://user-images.githubusercontent.com/390760/42170245-e7374d1e-7e0d-11e8-92a4-83fb3901b901.png)

#### Problem

The `<- Back` button on that screen opens up the plugins page `/plugins/manage/siteId`, when I expected to be redirected back to the Activity.

#### Proposal

Two things:

- Make sure the button directs the customer to the Activity.
- Change its label to `<- Activity` to maintain context.

**Comment by dmsnell** [comment]
`history.back()`?

breaking back behavior is one of the most-frequently disparaged patterns I see (maybe second to bloated apps written in JS).

can we not make the back button in the app navigate back in the browser?

**Comment by roccotripaldi** [comment]
> history.back()?

I'll laugh/cry if it's that simple 😆

**Comment by gwwar** [comment]
Maybe update the click handler to use `page.back` or the provided fallback based on what the last path was. Might be a little tricky here due to component wiring, but it should be doable. cc @retrofox for heads up on any plugin changes + Atomic

For example:
```jsx
export function feedPost( context, next ) {
	const feedId = context.params.feed,
		postId = context.params.post,
		basePath = '/read/feeds/:feed_id/posts/:feed_item_id',
		fullPageTitle = analyticsPageTitle + ' > Feed Post > ' + feedId + ' > ' + postId;

	trackPageLoad( basePath, fullPageTitle, 'full_post' );

	function closer() {
		page.back( context.lastRoute || '/' );
	}

	context.primary = (
		<AsyncLoad
			require="blocks/reader-full-post"
			feedId={ feedId }
			postId={ postId }
			onClose={ closer }
			referralStream={ context.lastRoute }
		/>
	);
	scrollTopIfNoHash();
	next();
}
```

https://github.com/visionmedia/page.js/blob/71bb2d8771159985065819fcebd8e6b5c62e3b26/index.js#L270-L285
