### ISSUE TITLE
Store: Printing a label should include deleted products in order

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#25853]
#### Steps to reproduce
1. Starting at URL: `http://calypso.localhost:3000/store/products/{site_url}` create a product that you will later be able to delete
2. Create a new order with the deleted product, for example by purchasing it at `{site_url}/shop`
3. Delete the product at `http://calypso.localhost:3000/store/product/{site_url}/{product_id}`
3. Go to the order details page for the new order: `http://calypso.localhost:3000/store/order/{site_url}/{order_id}`
4. See that the deleted product shows up on the items list for the order:
<img width="532" alt="order-has-deleted-product" src="https://user-images.githubusercontent.com/11487924/42226279-90fe4c28-7eac-11e8-9cdc-049e7ed909f0.png">
5. Open the printing label modal using the button `Print label & fulfill`
6. See that the product does not show up in the `Packages` tab (or the `Customs` tab if that's available):
<img width="627" alt="print-label-modal-does-not-have-deleted-product" src="https://user-images.githubusercontent.com/11487924/42226332-b7014eca-7eac-11e8-8d05-b0c1e3b19d59.png">

#### What I expected
I expected the deleted product to show up in the label printing modal.

**Comment by v18** [comment]
cc @DanReyLop

**Comment by v18** [comment]
Thanks @davipontesblog ! IIRC this code is also being using by the Fulfill team, so looping in @c-shultz abut this issue.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
