### ISSUE TITLE
Editor: Footnotes no longer copied in from Microsoft Word correctly

### ISSUE THREAD

**Issue by zandyring** [Automattic/wp-calypso#25857]
#### Steps to reproduce
1. Copy an academic paper in Word version 15.28 
2. Paste into the visual editor (Calypso or WP-admin)
3. Check the footnotes

#### What I expected
What used to happen is that footnotes would copy correctly, using these formats:
`<a href="#_ftn1" name="_ftnref1">[1]</a>`
`<a href="#_ftnref1" name="_ftn1">[1]</a>`

#### What happened instead
Now, universally, all footnotes are broken, as the "href" is missing from the a link, and the [1] is bumped outside the anchor:
`<a name="_ftnref1"></a>[1]`
`<a name="_ftn1"></a>[1]`

#### Context / Source
 #user-report in 1241938-zen
I'm surprised it ever worked, and we do caution that some footnotes will not copy over in the Word recommendations we provide:
https://en.support.wordpress.com/microsoft-word/

If this isn't something we'll dedicate any resources to, I'll let the customer know - it looks like this might be a dealbreaker for them.

**Comment by lancewillett** [comment]
Hi Zandy: definitely a "no" for the Classic WP Admin and Calypso editors. Possible for Gutenberg: https://github.com/WordPress/gutenberg

**Comment by sashastone** [comment]
I responded to the user: https://woothemes.zendesk.com/agent/tickets/1282825

**Comment by lancewillett** [comment]
@rantoncuadrado If you mean Gutenberg, yes.
