### ISSUE TITLE
Editor: Images with caption superposing when using alignment

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#25855]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page or https://wordpress.com/post on the visual editor
2. Insert 3 images with a caption into the page content
3. Align the first image to the left, the second image to the right, and leave the third image with no alignment
4. The first image will superpose the third image as seen below

![Screenshot](http://cld.wthms.co/rYiNKD+)
Screenshot: http://cld.wthms.co/rYiNKD

#### What I expected

The visual editor should show the image alignment similar to when the images don't have captions

![Screenshot](http://cld.wthms.co/Y65zRi+)
Screenshot: http://cld.wthms.co/Y65zRi

or the live site:

![Screenshot](http://cld.wthms.co/Ln3DAJ+)
Screenshot: http://cld.wthms.co/Ln3DAJ

#### What happened instead

The third image was displayed below the third image in the visual editor

![Screenshot](http://cld.wthms.co/rYiNKD+)
Screenshot: http://cld.wthms.co/rYiNKD

#### Browser / OS version
Mac OS 10.13.5
Chrome 67.0.3396.99

#### Screenshot / Video

![Screenshot](http://cld.wthms.co/sFkDRu+)
Screenshot: http://cld.wthms.co/sFkDRu

#### Context / Source

#user-report 1258093-zen

**Comment by Piyopiyo-Kitsune** [comment]
I updated the user and placed the ticket back on hold. Any updates? Been nearly a month :)

**Comment by lancewillett** [comment]
Thanks for raising this (and to the user for reporting it).

It's a great example of a broken flow — a bug in the current editor — that we won't prioritize right now, simply because we're working on the newer editor: Gutenberg. It'll be integrated into WordPress.com very soon — making this type of issue obsolete.

I'm going to close as "won't fix".
