### ISSUE TITLE
Customizer: Free and Personal plan previews are incorrect when just changing background colour

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#25858]
Custom colour contrasts are applied in the customizer preview when you change to a custom background colour with a free or personal plan. They aren't shown on the live site, though.

#### Steps to reproduce
1. Start on a site with a Free or Personal plan.
2. Apply a theme, preferably one where the background colour that's changed is behind text (like Radcliffe 2 or Independent Publisher 2) since it makes the issue more noticeable.
3. Change just the background to a very dark colour. Note how it looks in the preview.
4. Publish the changes.

#### What I expected

That the colours would be the same as they are in the preview.

#### What happened instead

Only the background colour, but the text returns to the theme's default colour, and is usually unreadable.

#### Screenshot / Video

Customizer Preview:

![](https://cldup.com/xhwH0AAVml-3000x3000.png)

Live site:

![](https://cldup.com/BgcmOh4qg2-3000x3000.png)

When you return to the Customizer, the preview accurately reflects the live site, with just the background colour changed.

I think the way the live site behaves makes sense -- the changing contrast is part of the colour annotations, which aren't fully available in the free or personal plans (just the palettes that come bundled with the theme). The only element you can change to any colour is the background.

The preview should only show what the user's plan supports.

Might be taken care of if #22569 is added.

Originally reported as a theme issue here: https://github.com/Automattic/themes/issues/149

**Comment by KokkieH** [comment]
Another report in the WordPress.com [forums](https://en.forums.wordpress.com/topic/radcliffe-text-color-front-page/)

**Comment by GeoJunkie** [comment]
Also reported in 2075474-zen. In this case, I was able to eventually get the title color updated, but never the tagline. It won't stick or update no matter what.
