### ISSUE TITLE
Jetpack Checklist: Add Illustration

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#25862]
See latest details: p6TEKc-2e8-p2

<img width="388" alt="banner" src="https://user-images.githubusercontent.com/841763/43000655-a2aaa3e4-8c22-11e8-8952-673b0122b062.png">

1. You’ve set up 1 out of 6 essential security features.
   Great start! Complete the rest now.
1. You’ve set up 2 out of 6 essential security features.
   Great start! Complete the rest now.
1. You’ve set up 3 out of 6 essential security features.
   You’re almost done! Complete the rest now.
1. You’ve set up 4 out of 6 essential security features.
   You’re almost done! Complete the rest now.
1. You’ve set up 5 out of 6 essential security features.
   You’re almost done! Complete the rest now.
1. Congratulations!
   You’ve finished setting up all of the essential security features. If you want to access these features again, you’ll find them in the Settings sidebar menu. _Was this checklist helpful? We’d love some feedback._

   Link to feedback survey -> todo

**Comment by tyxla** [comment]
This has been implemented in #32027 - it is a bit different from what's shown here, but we've followed the mockups from the latest blueprints in p5XAZ9-2ca-p2.
