### ISSUE TITLE
Activity Log: Hide Activity Log when user doesn't have permission

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#25875]
#### Steps to reproduce
1. Starting at URL: http://https://wordpress.com/stats/ for a site as "contributor" user or another user without access to activity log

#### What I expected

Can't see Activity Log

#### What happened instead

`Activity` Tab Displayed:

<img width="411" alt="screen shot 2018-07-05 at 10 37 48 am" src="https://user-images.githubusercontent.com/128826/42297043-7c91262c-803f-11e8-8e3c-23c71d3fee04.png">

When clicking it see:

<img width="952" alt="screen shot 2018-07-05 at 10 38 15 am" src="https://user-images.githubusercontent.com/128826/42297048-8b829184-803f-11e8-8763-aedf09b9e9b0.png">

#### Browser / OS version

Safari on macOS

#### Context / Source
#manual-testing

**Comment by cacheflow** [comment]
I'll take a look at this.
