### ISSUE TITLE
Stats numbers not being correctly displayed in Spanish accounts

### ISSUE THREAD

**Issue by Agepeuve** [Automattic/wp-calypso#25883]
The stats page of the sites that have an account using Spanish as their language is not being correctly displayed.

#### Steps to reproduce
1. Go to your Account Settings (https://wordpress.com/me/account) and change your interface language to "Español" or "Español de México". 
2. Go to your site's stats page (https://wordpress.com/stats).

#### What I expected
You should be able to read clearly the date of the stats you're checking under the bars.

#### What happened instead
Some numbers are being displayed between the days and the months.

#### Screenshot / Video
What we're seeing: http://cld.wthms.co/8SOTsP

What we should see: http://cld.wthms.co/Eodoj4

#### Context / Source
This issue came up via a #user-report but I was able to replicate it on most of my tests sites. It seems that the issue is not appearing on some sites that were created in the last 6 months. 

"Español de Chile" is unaffected by this issue.

Follow-up Ticket: 1259737-zen

**Comment by ramonjd** [comment]
I think it had something to do with the translation itself, which was causing formatting problems in the [stats list utils](https://github.com/Automattic/wp-calypso/blob/721066c/client/state/stats/lists/utils.js#L192).

<img width="985" alt="screen shot 2018-07-06 at 5 23 59 pm" src="https://user-images.githubusercontent.com/6458278/42365328-81ad86e8-8141-11e8-93c6-72a1c49d1c57.png">

I updated it to `MMM D` in [Glotpress](https://translate.wordpress.com/projects/wpcom/es/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=241483&filters%5Btranslation_id%5D=7338596), and tested on my sandbox:

<img width="525" alt="screen shot 2018-07-06 at 5 28 57 pm" src="https://user-images.githubusercontent.com/6458278/42365542-1c5727b2-8142-11e8-98a2-d9a3b03f4c68.png">

This will fix `es-mx` as well, and should be updated on production on next i18n deployment.

**Comment by ramonjd** [comment]
Deployed.
