### ISSUE TITLE
DevDocs: Fix layout issue when account verification notice is displayed

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#259]
We should update the account verification notice to fix a display issue on the `DevDocs` page:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11298332/6b338a64-8f7e-11e5-8d73-99f6bf21aaad.png)

**Comment by lancewillett** [comment]
This is working as expected, testing with brand new signup and going to https://wpcalypso.wordpress.com/devdocs in Mac-n-Chrome:

![screen shot 2016-04-14 at 10 16 06](https://cloud.githubusercontent.com/assets/66797/14536993/f4c88fcc-0229-11e6-89e2-240491a1f60b.png)
