### ISSUE TITLE
Protected pages: Blank page when visiting protected pages as non auth user

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#25905]
#### Steps to reproduce
1. Log out from your account, or open incognito tab
2. Go to: https://wordpress.com/post
3. An empty page will be loaded

#### What I expected

To be redirected to https://wordpress.com/ or https://wordpress.com/log-in

#### What happened instead

I was remaining on that blank page.

#### Browser / OS version

Chrome / MacOS

**Comment by arunsathiya** [comment]
I was able to reproduce this today as well. Tested on these browsers:

- Google Chrome Version 68.0.3440.84 (Official Build) (64-bit) 
- Firefox Quantum 61.0.2 (64-bit)
- Tor browser 7.5.6 (based on Mozilla Firefox 52.9.0) (64-bit)

All tests done on Mac OS High Sierra 10.13.6

<img width="1280" alt="screen shot 2018-08-13 at 13 22 28" src="https://user-images.githubusercontent.com/18581859/44019558-cb038468-9efc-11e8-9faa-407cf2ed947c.png">

Screenshot above indicating how the page looks.

**Comment by brbrr** [comment]
Closing in favor of #23785
