### ISSUE TITLE
Store services: validate the entered postcode for all countries, not only US

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#25937]
See https://github.com/Automattic/wp-calypso/pull/24976/files#r198578560 for more context.

On the `Purchase Label` modal, we have 2 address forms: Origin and Destination. At the moment, `Origin` can only include a country or territory with an `USPS` office, that means it will always have a US-formatted `ZIP` code. But, once the International Labels feature is enabled, the `Destination` form can take any address worldwide.

For postcode validation, we are only validating the US (and territories) ZIPcode format (`xxxxx[-xxxx]`). For other countries, we're just checking that the field is not empty. We should add worldwide validation to that field. Options:
* Copy [this logic](https://github.com/Automattic/wp-calypso/pull/24976/files#r198578560) that's on WooCommerce and port it to JS.
* Use a library. This involves writing dozens if not hundreds of RegExps, so I'd prefer if we could delegate that task to an open source contributor :)
* Don't do anything. The address will be normalized against `EasyPost` when submitting the form, so any obvious error in the postcode format would be caught on time. Not as good UX as instant client-side validation, but may be the best option if using a library adds too much bloat.

cc/ @v18

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
