### ISSUE TITLE
Sites: stop polling for sites when app is not authorized

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2593]
Raised by @beaucollins 

The web app polls `/me/sites` whether it's authorized or not. Polling should be stopped when the app is in an unauthorized state.

To reproduce:

1. Open WordPress Desktop
  - Sign out if you're signed in already
2. Look at the developer tools console

![screen shot 2015-11-11 at 11 34 38 am](https://cloud.githubusercontent.com/assets/19795/11100803/35acb4aa-8868-11e5-8d83-2840336826e2.png)

**Comment by designsimply** [comment]
Tested and confirmed, but with slightly different errors:

```
GET https://public-api.wordpress.com/rest/v1.1/me?meta=flags 403 (OK) build-desktop.js:77273
GET https://public-api.wordpress.com/rest/v1.1/me/settings 403 (OK) build-desktop.js:77273
GET https://public-api.wordpress.com/rest/v1.1/me/settings 403 (OK) build-desktop.js:77273
GET https://public-api.wordpress.com/rest/v1.1/me/sites?site_visibility=all 403 (OK) build-desktop.js:77273
```

![screen shot 2016-01-19 at tue jan 19 4 20 18 pm](https://cloud.githubusercontent.com/assets/1119271/12432480/78aba846-bec9-11e5-89dd-b120d1d48c10.png)

**Comment by lancewillett** [comment]
Closing in favor of https://github.com/Automattic/wp-desktop/issues/160
