### ISSUE TITLE
Checklist: Add 'pending' State to steps

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#25935]
To reflect e.g. ongoing VaultPress or Akismet installation/setup/provisioning.

Draw inspiration from https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx. 

Fortunately, we only need a less fine-grained approach (i.e. we don't need feature granularity -- plugin granularity should be enough, e.g. VaultPress corresponds to the 'Backups and Scanning' step, Akismet to 'Spam Protection'). Should be enough to select `plugins = getPluginsForSite( state, siteId, false )` in `connect()`, and do something like https://github.com/Automattic/wp-calypso/blob/5e62832352311e65786d9d9f9586ef9a879fe978/client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx#L484-L497

**Comment by tyxla** [comment]
This can now be closed - we're doing it in a different way than what's suggested here though. Installation, activation and configuration now happens on the server side, and the following PRs were responsible for making the "pending" state be displayed on the client.

#31684
#31547
#32152
#31963
