### ISSUE TITLE
Editor: Editing Unordered Lists in HTML Creates Nested Lists

### ISSUE THREAD

**Issue by jesscga** [Automattic/wp-calypso#25938]
#### Steps to reproduce
1. Open new post
2. Add unordered list with content
3. Switch to HTML view
4. Move closing `</li>` tag to new line, then revert
5. Check Visual editor.

#### What I expected
The existing `<ul>` would be the only one on the page

#### What happened instead
The `<li>` that was moved was recreated as a nested `<ul>` inside the previous `<ul>`

#### Browser / OS version
Chrome Version 67.0.3396.87

#### Screenshot / Video

https://cld.wthms.co/QpZfyI

**Comment by lancewillett** [comment]
Hi @jesscga - thanks for the report. We're getting ready to replace the editor very soon with Gutenberg. So the chances of fixing this are low... however, if you are able to replicate the same issue in the Gutenberg editor, it's worth reporting: https://github.com/WordPress/gutenberg
