### ISSUE TITLE
Import still processing in Calypso, need to stop the import

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#25960]
User reported that they started an import 48 hours ago but it's still going. 
They are not able to cancel the import from Calypso under the Settings > General > Import
Also can't stop the import in wp-admin since it's not appearing in wp-admin > Tools > Import. 
Recommended they export a new file and try the import from wp-admin. 

Screenshot - https://cloudup.com/cSzf2JJ6SGD

1271539-z
2740781-hc

**Comment by lancewillett** [comment]
@pablinos Could you please take a look at this one?

**Comment by pablinos** [comment]
Sure!

At first glance, I can't see exactly what went wrong with the import from the logs, but looking at the import file it's quite large and appears to be corrupted - it cuts off in the middle of the comments.

It may be that the upload didn't work correctly or a problem with the export. Either way I've cleared the importer options, so they are free to try again, but if they use the same export I think they will have a similar problem whether they use Calypso or `wp-admin`.

It looks like a good test case, so if they would like to send us the import file I can investigate it further.

**Comment by pablinos** [comment]
An improvement was made by @bisko so that stalled imports like this could be reset (p7DVsv-51V-p2) more easily. 

Without the original import file it's not possible to work out what caused this to stall. If the user comes back to us with further details then we can reopen this issue.
