### ISSUE TITLE
Plans: reword tip to be clearer (to avoid confusion)

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#25967]
It looks like our tool tip on the Jetpack Plans view in Calypso has a tooltip for "Priority support" that could be taken out of context or understood differently than intended.

![image](https://user-images.githubusercontent.com/1123119/42539231-b41f3aa4-8457-11e8-8414-788d43cd093e.png)

Here are the two places I found it:

https://github.com/Automattic/wp-calypso/blob/4bc13c20bc88b81c4e99fe2f6c63e102483727bc/client/lib/plans/constants.js#L1282

https://github.com/Automattic/wp-calypso/blob/4bc13c20bc88b81c4e99fe2f6c63e102483727bc/client/lib/plans/constants.js#L1290

I would be happy to make the change, but we should figure out what we want to say there instead. Perhaps, something like this:

> Hands-on support to help you get started with Jetpack

CC @madhattermattic

**Comment by michelleweber** [comment]
"Hands-on support to help you get started with Jetpack" sounds good generally. If "hands-on" means "live chat" though, we should just say that.

Alt: "Hands-on/Live chat support for all your Jetpack setup needs and questions."

**Comment by MichaelArestad** [comment]
It's a concierge session, so it's video chat.
