### ISSUE TITLE
Menu: Additional menu location not registered on the theme

### ISSUE THREAD

**Issue by isocialtish** [Automattic/wp-calypso#2599]
A WordPress.com user reported (2496021-t) seeing the error "There was a problem saving your menu" and was unable to save any changes to the menu.

We were unable to reproduce the error on a test site

User had recently changed themes several times and was now using the Argent theme, which only had one menu, whereas a previous theme had 2 menus.

@mendezcode found that an additional menu location was on the site's theme data (from a previous theme the user switched from), even though it was not a menu location registered on the theme.

We should check against the existing menu locations defined by the theme to fix.

**Comment by atjuch** [comment]
Going to piggy back off Tish's issue.

Received a live chat yesterday regarding their site showing a different menu on mobile compared to the desktop site.

**Steps to reproduce**

1. On a desktop browser, view the menu on the site http://kabarlgbt.org
2. Click on the menu item "Berita", it should load the page, http://kabarlgbt.org/2016/01/23/matt-dan-blue-dan-anak-laki-laki-mereka-di-hari-natal/
3. Try to load that same page on a mobile device

**Results**

The mobile menu is not displaying any content compared to the desktop menu.

https://mc.a8c.com/support-stats/feedback/chat-transcript.php?id=298554

Calypso is showing three menus that @carinapilar found, when it only should be displaying two:

![Image of users menu](https://cldup.com/E1C-W8YFi2.png)

@jeremeylduvall found this image also:

![Image of users menu](https://cldup.com/y_xTyWkKSr.png)

Slack chat: https://a8c.slack.com/archives/tickets/p1453673385000131

**Expected**

The mobile version of the site should be consistent with the desktop version.

CC: @mendezcode , @jeremeylduvall

**Comment by folletto** [comment]
> User had recently changed themes several times and was now using the Argent theme, which only had one menu, whereas a previous theme had 2 menus.

Argent defines one menu, "Primary Menu" (see `functions.php L69`).

> found that an additional menu location was on the site's theme data (from a previous theme the user switched from), even though it was not a menu location registered on the theme.

Hard to say what's happening here. Note however that each Menu Widget creates an additional location. Maybe was that?


> Calypso is showing three menus that carinapilar found, when it only should be displaying two:

These are menus, not location, and are user-created. There could be any number. :)

I checked this too, and the theme "The Morning After" has a single location, called "Primary Navigation" (`functions.php L38`).

However: it's using a mobile theme (configured in wp-admin → Appearance → Mobile).

Which has some code to try detecting which menu to show, and thus might be using a different menu.

**Comment by lancewillett** [comment]
The original report ("There was a problem saving your menu") should be fixed, see notes and similar report at :https://github.com/Automattic/wp-calypso/issues/3667#issuecomment-215408359
