### ISSUE TITLE
Me/Security: Verification buttons are disabled in two step verification

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#26]
To reproduce this bug
- Click `Get started` in two step
- Enter a valid number and click `Cancel` or click either `Verfiy via SMS` or `Verify via App` go to the next screen and Click `Cancel`
- Start again with `Get started`
- See the two verification buttons are disabled now

![image](https://cloud.githubusercontent.com/assets/7233112/11218959/d22359da-8d25-11e5-847c-190a1fa2d372.png)

**Comment by v18** [comment]
This is related to #387 - button can become disabled when phone number was already entered previously

**Comment by ebinnion** [comment]
This should be fixed in #584.
