### ISSUE TITLE
Purchases: Allow disabling input fields in credit card form

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#260]
We should be able to disable input fields of the credit card form on the `Edit Card Details` page:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11298904/9a3aae1a-8f82-11e5-8825-f7d5af9e299d.png)

This will allow us to prevent users from entering any data while we're still in the process of fetching the actual data for the stored credit card from the API. Note the handling of the submit form button shouldn't be the responsibility of the `<CreditCardForm />` component. Finally, this form is also used in the checkout on the `Secure Payment` page to allow users to enter a new credit card, which means this flow should be checked for side effects when this issue is being resolved.

**Comment by gziolo** [comment]
This is no longer an issue since #7537 landed.
