### ISSUE TITLE
Checklists: State and structure

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#26015]
This issue is to share some discussion that @ockham and I have been having while looking at #25956 

I'll summarize conversations up until this point and provide a bit of a roadmap. We're taking on some [checklist work](https://github.com/Automattic/wp-calypso/projects/70).

-  `tasks` is a mix of structure and state.
- We'd like state to be _minimal_ and live in Redux.
- We'd like structure to be declarative React.

Here's `tasks` now (or soon):

https://github.com/Automattic/wp-calypso/blob/1501e9f5ee5ebaad0934fddd0dc9b2dbcd10260d/client/my-sites/checklist/jetpack-checklist.js#L7-L19

It's connected and merged with server state in connect:

https://github.com/Automattic/wp-calypso/blob/1501e9f5ee5ebaad0934fddd0dc9b2dbcd10260d/client/my-sites/stats/checklist-banner/index.jsx#L212-L216

Note that this is undesirable because:
- It does a lot of work in `connect`
- A new object is created every time connect runs, meaning the component will likely rerender.

Then a checklist is rendered like this:

https://github.com/Automattic/wp-calypso/blob/4722397c21206359518a5790388b59a045ec0483/client/blocks/checklist/index.jsx#L102

---

What if a checklist looked like this?

No more `tasks` state and structure.

Each checklist looks more like this. Note that all of these structural things live here declaratively (task ids, urls, translated strings…)

```jsx
<SomeChecklistWrapper>

<ChecklistItem
  taskId="jetpack_brute_force"
  completedTitle={ translate( "We've automatically protected you from brute force login attacks." ) }
  status="complete"
/>
<ChecklistItem
  taskId="jetpack_spam_filtering"
  completedTitle={ translate( "We've automatically turned on spam filtering." ) }
  status="complete"
/>
<ChecklistItem
  taskId="jetpack_monitor"
  title={ translate( 'Jetpack Monitor' ) }
  description={ translate(
    "Monitor your site's uptime and alert you the moment downtime is detected with instant notifications."
  ) }
  completedTitle={ translate( 'You turned on Jetpack Monitor.' ) }
  completedButtonText={ translate( 'Change' ) }
  duration={ translate( '3 min' ) }
  tour={ 'jetpackMonitoring' }
  url={ '/settings/security/$siteSlug' }
/>

</SomeChecklistWrapper>
```

And our `ChecklistItem` blocks looked something like this?

```jsx
// Rendered mostly the same…
export default connect( ( state, props ) => ( {
  status: props.status || getTaskStatus( state, props.siteId, props.taskId ),
} ) )( ChecklistItem )
```

Now, we'd imaging that Redux state would be very minimal, including only the `status` of a particular task (pending, in progress, complete, dismissed?).

**Comment by ockham** [comment]
Love it :heart: It makes so much more sense to put stuff like `title`, `description`, or `tour` directly into React components.

**Comment by sirreal** [comment]
Noting that completed tasks move up, which changes the declared ordering. We can handle that with flexbox magic.

<details><summary>css idea</summary>

```css
.SomeChecklistWrapper {
  display: flex;
  flex-direction: column;
}

.ChecklistItem {
  order: 100;
}

.ChecklistItem.is-complete {
  order: 0;
}
```
</details>

**Comment by sirreal** [comment]
@markryall @taggon @timmyc Wanted to involve you in this conversation as you've been involved in checklists.

**Comment by sirreal** [comment]
See implementation in #26030

**Comment by sirreal** [comment]
Implimented in #26618
