### ISSUE TITLE
Investigate which packages we need to import for Gutenberg

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#26035]
- Out of all dependencies listed in package.json, what packages do we need for a standalone Gutenberg instance?
- Can we help propose and publish some npm package, that lists the above^^?

**Comment by vindl** [comment]
I think this is for the most part resolved with https://github.com/Automattic/wp-calypso/pull/26615? The only remaining package to add is `core-blocks`.

**Comment by gwwar** [comment]
Yup let's close ✨
