### ISSUE TITLE
Categories: Cannot remove description

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#26033]
The category description cannot be left blank if a description was previously entered.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/taxonomies/category/
2. Click on a category.
3. Delete the description inside.
4. Click on Update.
5. Click on the category again to see if changes were saved. (they weren't)

#### What I expected
The Description box to be empty.

#### What happened instead
The previous text was still there when I opened the category to see if changes were saved.

#### Browser / OS version
MacOS 10.13.5
Firefox 61.0.1
Chrome 67.0.3396.99

#### Screenshot / Video
![screen capture on 2018-07-12 at 16-51-27](https://user-images.githubusercontent.com/11635760/42665766-1414db22-85f6-11e8-8f74-7abac0ecd2d4.gif)

#### Context / Source
#user-report

Chat: 2352458-hc
Follow-up: 1276980-zen

**Comment by lancewillett** [comment]
Good find! Thanks for the report.

**Comment by ivan-ottinger** [comment]
Another occurrence: 
Chat: 636818-hc
Follow-up: 1313531-zen

**Comment by fabiano** [comment]
I checked and the API is not updating the description when it is left blank.

**Comment by juliasydnor** [comment]
Another report of this in 1857550-zen. Category description can be removed and saved correctly via WP Admin as a workaround.

**Comment by donpark** [comment]
The bug was in Jetpack. API endpoint `/sites/$site_id/taxonomies/category/terms/` was tossing aside `description` field if it's set to empty string.

Jetpack PR: https://github.com/Automattic/jetpack/pull/11736

**Comment by donpark** [comment]
Next version of Jetpack release, due April 2, 2019, will fix this issue.

**Comment by donpark** [comment]
Looks like the patch didn't make Jetpack 7.2 because it missed code-freeze by a day.
Should ship in the following release.
