### ISSUE TITLE
Typographical widow on the purchase confirmation screen

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#26051]
![image](https://user-images.githubusercontent.com/545779/42698202-ce3209a8-8682-11e8-8970-d92780c3ad9a.png)

A potential quick fix here would be just adding a nbsp; between "in" and "excitement."

**Comment by lancewillett** [comment]
Does Calypso have a `widont` equivalent? To automate this like we do on WordPress.com.

**Comment by artpi** [comment]
> Does Calypso have a widont equivalent? To automate this like we do on WordPress.com.

It does not look like it is the case.


> A potential quick fix here would be just adding a nbsp; between "in" and "excitement."

That may introduce translation problems, since that is a string that will need to be translated.

I am not able to take care of this PR due to the fact that I really have my hands full with Memberships.

@Automattic/neutron  - is this in Neutron's scope ?

**Comment by jeremeylduvall** [comment]
Is there a reason we shouldn't use a tool like [`typogr.js`](https://github.com/ekalinin/typogr.js/)? It has [a `widont` filter](https://github.com/ekalinin/typogr.js/#widont) built in. Then, we would have an easy way to fix these moving forward.

**Comment by artpi** [comment]
I just stumbled onto a widow helper funxction in calypso:
https://github.com/Automattic/wp-calypso/blob/master/client/lib/formatting/index.js#L56
