### ISSUE TITLE
DevDocs: "Error invoking /devdocs/content: File does not exist"

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#26066]
#### Steps to reproduce
Navigate to a `/devdocs/404` (or any URL inside `/devdocs` that doesn't exist)

#### What I expected
Page not found is displayed

#### What happened instead
A message saying "Error invoking /devdocs/content: File does not exist" is displayed

#### Browser / OS version
Google Chrome Version 67.0.3396.99 / macOS High Sierra Version 10.13.5

#### Screenshot / Video
![screen shot 2018-07-14 at 15 25 03](https://user-images.githubusercontent.com/1233880/42724913-5f1725ae-877b-11e8-829c-57e117fce9ca.png)

**Comment by alisterscott** [comment]
Fix by @ramonjd in #26105 works well 👍
