### ISSUE TITLE
Checkout: Indicate the "redemption fee" is not refundable

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#2606]
As @designsimply reported:

> There’s a note just below the shopping cart list that says I can get a full refund within 2 days of placing my order, but is that true for renewals (especially $80 late fee renewals) ?

We should indicate somehow that the redemption fee is not refundable.

**Comment by designsimply** [comment]
Consider modifying the language to say "most" purchases are eligible for a refund if requested within 2 days or simply link to a more detailed refund policy posted elsewhere because I believe more than just the redemption fee is non-refundable (i.e. additional Google Apps licenses).

**Comment by ranh** [comment]
I suggest we hide the note about refunds on the checkout screen when there are products in the cart that the note does not apply to. See also #2502

**Comment by umurkontaci** [comment]
@ranh We're already showing different messages depending on the refund policy (generic, plan with a domain, domain). I think we should keep the message but add a copy.

Current variations:

- Generic: "You can cancel within 30 days for a full refund. No questions asked"
- Plan with domain: "You can cancel within 30 days for a partial refund. No questions asked."
- Domain: "You can cancel within 48 hours for a full refund. No questions asked."

**Comment by ranh** [comment]
@umurkontaci There are two potential problems with that:

* Depending on the products in the cart, the policy may be too complicated to adequately describe in one short sentence. That could defeat the purpose of this section.
* If no refund is available, do we want to highlight this fact so visibly on the checkout page? It might be better to say nothing.

That said, it may throw the whole design off balance if we just leave the part about support. cc @breezyskies who originally designed this section.

**Comment by breezyskies** [comment]
> Depending on the products in the cart, the policy may be too complicated to adequately describe in one short sentence. That could defeat the purpose of this section.

This is a section we should do some testing on in general, but I'd agree with not including it when the policies become too complex to quickly describe. It doesn't look right with just the one section, so I'd hide the whole component. 

> If no refund is available, do we want to highlight this fact so visibly on the checkout page? It might be better to say nothing.

Agreed. This is intended to be reassurance copy (considering that many of our products have very reasonable return periods).

**Comment by melanieharari** [comment]
In the event that a domain is not able to be restored, we refund this. In the case that a user redeems a domain but later decides not to keep it (which should be fairly rare), we'd likely make the decision to refund if needed. Closing this.
