### ISSUE TITLE
Calypso not loading properly in Safari

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#26067]
We've received a fair few reports from users who are unable to use Calypso in Safari.

To date:
#1279642-zen - user claims their browser is 11.2 but the latest version I can find info for is 11.1.2
#1279026-zen - v9.1.3
#1274259-zen -  version unknown
#1279079-zen - v10.1.2
#4392471-hc - v10.1.2
#1279001-zen - v10 (precise version unknown)

#### Steps to reproduce
1. Make sure Safari is earlier version than 11.1.1
2.. Starting at URL: WordPress.com
3. Log in
4. Calypso doesn't load - screenshot: http://cld.wthms.co/xSKKsT

I haven't been able to replicate this on my computer, I have Safari 1.11.1.  So far, apart from the first noted ticket above, all others seem to have been prior to v11.

Most users have reported the problem cropping up today (14th July 2018).

**Comment by nickmiranda** [comment]
Two more: 
#1279132-zen
#1279941-zen

**Comment by KristinaKay** [comment]
Another 
#1279966

**Comment by thebud15** [comment]
#1279917-zd

**Comment by thebud15** [comment]
#1261172-zd

**Comment by ehti** [comment]
Just tested on Safari 10.1, macOS Sierra (browserstack). **Can confirm and replicate.**

Quite a few forum threads as well.

**Comment by ehti** [comment]
JavaScript errors in console when I try to log in, but Calypso fails to load (click to enlarge- from browserstack):

<img width="1639" alt="screen shot 2018-07-15 at 3 37 23 am" src="https://user-images.githubusercontent.com/6505293/42728920-8085be0c-87e0-11e8-9a3d-afe7910c3ab2.png">

**Comment by erricgunawan** [comment]
#1279681-zen - user using Safari 10.0.1

**Comment by nickmiranda** [comment]
#1279584-zen Safari version 11.1.1

**Comment by thebud15** [comment]
#5017079-hc

**Comment by nylen** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/26068

**Comment by nylen** [comment]
:disappointed: It looks like this is back again, same symptoms but possibly different cause

**Comment by nylen** [comment]
1259709-zen
1285406-zen

**Comment by GeoJunkie** [comment]
Also 1282799-zen

**Comment by nylen** [comment]
Fixed again - https://github.com/Automattic/wp-calypso/pull/26120 this time
