### ISSUE TITLE
Import without author information works in WP Admin but not Calypso 

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#26070]
Today, I imported a micro.blog import file for a user. There was no author name info, so the import threw an error in Calypso and wouldn't go through: 

> There does not appear to be any authors in your WordPress import file. Try another file or contact support.

But in WP Admin you can choose an existing author and it works.

Ticket is #1281395-zen

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/importing-wordpress-blog-2

I logged in as the site owner, and confirmed in Calypso I get the error message `There don't appear to be any authors in your import file`

I've initiated an import via wp-admin, which seems to be working (has not finished at the time I write this)
