### ISSUE TITLE
Editor: Error when attempting to restore a revision

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#26081]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/:siteSlug/:pageId for a Jetpack site
2. Make some changes to the page content, but don't click the Save button. Let autosave trigger.
3. Refresh the page.
4. Witness the restore dialog:

![](https://cldup.com/kq-Cl6lrge.png)

5. Click the button to restore the draft.

#### What I expected

To have the autosaved version restored.

#### What happened instead

I encountered an error:

![](https://cldup.com/HVWNLjcnNi.png)

#### Browser / OS version
Chrome 67.0.3396.99 on macOS High Sierra 10.13.5

#### Context / Source

Found while manually testing p58i-76n-p2.

#manual-testing

**Comment by tyxla** [comment]
I'm only guessing and haven't investigated, but could that be related with #25648? cc @jsnajdr

**Comment by jsnajdr** [comment]
Looking at it right now. After a first look at the crashing call stack, all called code is outside the actual TinyMCE library -- it's all our Calypso code and our `<TinyMCE>` React wrapper.

**Comment by jsnajdr** [comment]
@tyxla I'm unable to reproduce this bug on any of my sites, Simple, Atomic or Jetpack.

The cause however seems to be that the post loaded from server:
- does have a `meta.autosave` field indicating that autosave is available
- doesn't have a `meta.autosave.content` field or it's `null`. Then calling string methods on it crashes

Can you please do a little investigation and see what the REST call to load the editor post returns? Is the `content` field on the autosave meta indeed missing?

If yes, then the question is why. If it doesn't happen on all sites, but only on a specific Jetpack one, then some misbehaving plugin might be to blame.

**Comment by tyxla** [comment]
It's a shame I don't have a lot of time to debug this right now, but this is what I get from the endpoint:

![](https://cldup.com/rLjgC8Tunp.png)

Seems like this is enough to confuse our `hasAutosave` prop - https://github.com/Automattic/wp-calypso/blob/6da20f2bc99c0b264429c36ac758533ea929c932/client/post-editor/post-editor.jsx#L258

This is also odd, because we seem to have an autosave when we check in wp-admin:

![](https://cldup.com/7NU2IZJEN3.png)

Let me know if that helps, or if I should further debug.

**Comment by jsnajdr** [comment]
@tyxla I'm still unable to reproduce on my wpsandbox 😞 If you could help with debugging, this bug is likely to be wpcom/Jetpack issue, not Calypso.

If the post has no autosave, I just don't get the `meta.data.autosave` property at all in the response, even if the request query params ask for it. You seem to be getting the result of the `GET /sites/%s/posts/%d/autosave` endpoint there. The "No autosaves exist for this post" error is thrown only by that endpoint's callback, nothing else.

I can't even find the code that sets the `meta.data.autosave` property and what's the relationship to the autosave endpoint.

**Comment by tyxla** [comment]
Weirdly enough, I am no longer able to reproduce this as well. It was probably caused by a bad sync of the particular revision, but I'm no longer able to repro, with several attempts on different sites. Closing.
