### ISSUE TITLE
Domains: DNS: CNAME validation returns "Invalid Name" for correct CNAME

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#2609]
Not sure if this is a bug or not, but currently not entering a complete domain name in the CNAME field under 'Add New DNS Record" displays a red 'Invalid Name' warning. 

This can be confusing, especially since our previous DNS Editor allowed entering just the subdomain when creating a CNAME record.

Similar to #2284:

> it is not required to enter the whole domain name since we can just append the domain name afterwards.

To reproduce:
1. Go to /domains/manage/example.com/dns/example.wordpress.com
2. Click Add New DNS Record
3. Under "Type" select CNAME record
4. Type 'subdomain' and observe that the red 'Invalid Name' warning appears
5. Noticed that you cannot click "Add New DNS Record"
6. Type 'subdomain.domain.com' and observe that the red warning goes away, and "Add New DNS Record" becomes clickable

**Comment by klimeryk** [comment]
Fixed by #2262 (not yet merged though - adding the link here for easier tracking)
