### ISSUE TITLE
Checklist Add site icon modal hides error on file upload

### ISSUE THREAD

**Issue by mel-OR** [Automattic/wp-calypso#26098]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checklist/{:site.url:}
2. Click "Do It!" to change the site icon.
3. Click on Change
4. Drag a file that is not a supported image type, such as a .zip file

#### What I expected
On step 5, I expect that the error is shown on top of any other modals, popups, or other items so I can see what the error says. Although the error can be dismissed, I can't see what kind of error I encountered.

#### What happened instead
 An error is displayed, but it is behind the guided tour popup
![unsupported file error cannot be seen](https://user-images.githubusercontent.com/28070750/42793864-f6f7c23c-8930-11e8-9159-e5fb478db958.png)

#### Browser / OS version
Chrome 67.0.3396.99
Mac OS 10.13.6

#### Context / Source
Attempting to learn the checklist flow to later automate. Found by #manual-testing

**Comment by lancewillett** [comment]
Thanks for logging this bug, Melissa.

**Comment by fditrapani** [comment]
Thanks for sharing. That's a tricky one. Pinging @taggon again for any thoughts of how we could fix this?

**Comment by ramonjd** [comment]
Does it make sense to temporarily hide all guided tour tips when we detect an error notification (regardless of where we are in WordPress.com) or should we target this one specifically, that is, when the media library wants to display an error?

I'm not yet sure off the top of my head how, but we could retrigger the tip once the user has dismissed the error notification. Might have to store something in state to track it all.

**Comment by fditrapani** [comment]
Ideally, it would be great to solve this at a system level but I worry how big a task that is. Maybe dealing with it in this one-off case is the better approach? 

> I'm not yet sure off the top of my head how, but we could retrigger the tip once the user has dismissed the error notification. Might have to store something in state to track it all.
Sounds like a good approach.
