### ISSUE TITLE
Purchases: React key warning when loading purchases list

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#261]
This is what I see when I load purchases list:
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Card. See https://fb.me/react-warning-keys for more information.

Test url:
`/purchases`

I did some investigation and it looks like it can be caused by `<Card />` component.

**Comment by spncrb** [comment]
I wasn't able to see this in the console currently when loading /purchases - can you confirm this is still an issue?  @gziolo

**Comment by gziolo** [comment]
Neither do I :) Looks like it's fixed. Closing.
