### ISSUE TITLE
Plans: Update `sitePlans` on site switch

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#2610]
Originally reported by @mikeshelton1503 
> I was testing something locally on my Jetpack test site and saw the trials offered for Jetpack

![image](https://cloud.githubusercontent.com/assets/230230/12446937/5895b552-bf6d-11e5-98a2-dd55504f374c.png)

This is probably linked to the fact that `sitePlans` is currently not updating on site switch in `client/my-sites/plans/main.jsx`
The component should be modified to update `sitePlans` on site change. `componentWillReceiveProps` won't update on site change since we are using the observer mixin. We should use either `componentWillUpdate` to watch for a new selected site in `sites` or pass it down to a new component.

**Comment by fabianapsimoes** [comment]
> This is probably linked to the fact that sitePlans is currently not updating on site switch in client/my-sites/plans/main.jsx

So this would only happen when using the Site Switcher from `/plans`? 

Is it possible to actually signup for a trial for a Jetpack site, or will it trigger an error? If it's possible, do we know how many signups we had so far?

**Comment by Tug** [comment]
I haven't tested the checkout but I guess the server will return an error when we try to confirm the purchase.

**Comment by Tug** [comment]
Also the bug is not limited to jetpack sites I believe. Since `sitePlans` is not updating, switching from any site we have a trial on to another site won't update the view (and the other way around). That's why I set a high priority to it.

**Comment by fabianapsimoes** [comment]
> Also the bug is not limited to jetpack sites I believe. Since sitePlans is not updating, switching from any site we have a trial on to another site won't update the view (and the other way around). 

Just tested this, and `PlanActions` is re-rendered when we switch between WordPress.com sites. So it seems this is only getting Jetpack sites.

![domain](https://cloud.githubusercontent.com/assets/1248436/12449322/adab4ffc-bf7c-11e5-87bb-48543fe01ca4.gif)

It'd be good to confirm if these users are able to signup for a trial, or are getting an error.

**Comment by fabianapsimoes** [comment]
As mentioned in #2787, @johnHackworth thinks this is related to 01c54b4.
