### ISSUE TITLE
Jetpack connect: add “create a new account” link below form

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#26107]
During a Jetpack connect flow, a logged out user is presented with a login form with a pre-filled email address (email configured on the self-hosted site), but no contextual option to create a fresh dotcom account. There's the masterbar “Sign Up” link, but it's very removed from the focus of this page, especially on large screens:

![image](https://user-images.githubusercontent.com/390760/42810343-98b07ff0-89af-11e8-87f1-beb51922fb29.png)

This is not great and could be impacting the amount of customers we're getting through our doors. Granted, the examples above all stem from using a JN site where the primary email will, more often than not (always?), have a corresponding dotcom account, so the form will be correctly pre-filled.

But there might be a case where the person setting up Jetpack is not the same that installed the website, doesn't have access to that inbox or account, and needs to create a new one. We should provide more clarity and a more obvious path to create a new account.

@joanrho suggested on p6TEKc-28A-p2 that we add an additional sign up link below the form:

> Add Sign Up link below sign-in box for more visibility.

This is my proposal: add the link between the ”lost password” and “back to site” options with the copy:

> Create a new account

Visual:

![image](https://user-images.githubusercontent.com/390760/42810733-8a4e0076-89b0-11e8-97e3-17180dcf49fb.png)

**Comment by keoshi** [comment]
cc'ing @Automattic/editorial for copy review on the new item:

> Create a new account

**Comment by michelleweber** [comment]
I know it seems obvious, but I wonder if we want to specify "Set up a WP.com account." Only because two services are referenced on the screen and it'd be good to make it extra super clear what you're about to do.

**Comment by keoshi** [comment]
@michelleweber I opted for a more simplistic approach since we already reference “your WordPress.com account” on the page title. This might not be ideal, but adding a third reference there “WP.com” might be even more confusing, no?

**Comment by michelleweber** [comment]
I don't think it's *more* confusing, but if it feels unnecessary given what's on other pages people will have seen, "create a new account" is totally fine.

**Comment by keoshi** [comment]
At a second glance, your suggestion actually makes a lot of sense. Let's go with this then:

> Set up a WordPress.com account

Thank you, @michelleweber !!

**Comment by sirreal** [comment]
This is implemented

![Screen Shot 2019-04-16 at 13 38 56](https://user-images.githubusercontent.com/841763/56206607-130edc00-604d-11e9-9723-dffa86fa435c.png)
