### ISSUE TITLE
Billing: unable to edit billing details in Firefox

### ISSUE THREAD

**Issue by fresatomica** [Automattic/wp-calypso#26114]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/billing
2. Click on View receipt
3. Hover over Billing details

#### What I expected
A box should appear where you can edit the billing details.

#### What happened instead
When there are no billing details nothing appears and the details can't be edited. This, however, is possible in Chrome - you can enter new details there.

#### Browser / OS version
Firefox 61.0.1 /High Sierra

#### Screenshot / Video
http://cld.wthms.co/3PXcJN

#### Context / Source

#user-report

**Comment by alisterscott** [comment]
Confirmed this is an issue in Firefox 61

Whilst fixing this it might be worth making it more obvious that you can enter information here as it isn't very discoverable in my testing

**Comment by alisterscott** [comment]
Fix in #26309
