### ISSUE TITLE
Activity: free site has activity on creation

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#26117]
When a free site is created, it includes a couple of activities that shouldn't be visible.

These are settings changes that haven't been changed since the site was just instanced and the user hasn't done anything yet.

Here's an example of a site I just created:

![image](https://user-images.githubusercontent.com/390760/42827932-70b864ec-89df-11e8-8d82-3e616e0f5a64.png)

**Comment by simison** [comment]
Are you sure you didn't do anything else except create the site?

I haven't seen these upon creating a site this week so they're appearing probably due to some action at settings. Should be hidden nevertheless, good catch!

**Comment by simison** [comment]
An idea: E2E tests could create fresh sites + purchase plans and check that we have no events / only expected events in the activity log. Otherwise we'll end up having events creep up here each time someone implements a new module or a setting.

**Comment by keoshi** [comment]
Thank you so much, @gititon !
