### ISSUE TITLE
Gallery, Slideshow and Contact Form Shortcodes Trigger "Invalid Post Address" Error in Post Editor

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#26140]
Embedding the `[gallery]` shortcode in a post triggers a popup with this error:

> Invalid Post Address
> This post cannot be found. Check the web address or start a new post.

<img src="http://cld.wthms.co/GHokqY+" width="600" />

In this state, the post or page cannot be edited in the Calypso editor.

#### Steps to Reproduce

1. Create a new post in Calypso.
2. Click Add > Media and upload 2-3 images or more.
3. Do not insert images, but instead type in the `[gallery]` shortcode in HTML mode into the post.  It's designed to display a gallery of images attached to the post.
4. Publish the post, then click "Blog Posts" on the main menu and on the post title to edit it.

#### What I expected

To be able to continue editing the post normally.

#### What happened instead

An error popup saying "Invalid Post Address" shows up in the screen and I'm unable to edit it further.  If the shortcode contains specific image IDs (ie `[gallery id="1,2,3,4,5"`])or gallery type (ie `[gallery type="circle"]`) the issue doesn't happen.

#### Browser / OS version / Etc

I was able to replicate the error in Google Chrome Version 67.0.3396.99 and Firefox Version 61.0.1, both on Simple and Atomic sites.  The issue does not happen in wp-admin.

**Comment by juliasydnor** [comment]
The [slideshow] shortcode causes the same problem, as reported in 1271335-zen.

**Comment by MindyPostoff** [comment]
The [contact-form] shortcode is causing trouble for this user reported here: 1297675-zen

Page can be edited in WP-Admin, and if the contact form is removed from the content, the page is then accessible again in Calypso.

**Comment by juliasydnor** [comment]
Another report of this happening with the [contact-form] shortcode, despite there being attributes in the shortcode. I was able to reproduce during the chat and had the user edit the page/form from WP Admin as a workaround.

5247035-hc

**Comment by kristarella** [comment]
I came across this same issue. In my case the contact form had some weird `<span>` elements within some of the attributes. Removing them solved the problem.

eg `[contact-form subject="New Inquiry-SS<span id="mce_SELREST_start" style="overflow:hidden;line-height:0;">﻿</span>"]`

and `[contact-field label="Package you're most interested in" type="select" options="Add Second Photographer,<span id="mce_SELREST_start" style="overflow:hidden;line-height:0;">&#65279;</span>Silver,Gold,Bronze,Platinum,Other Portrait or Session,I don't know" required="1" /]`

1369581-zen

**Comment by hacchism** [comment]
Another report: 5198307-hc

**Comment by rachelmcr** [comment]
Thanks for all of these user reports! I want to note that these shortcodes don't universally cause problems in the editor — all of these shortcodes can work in the Calypso editor without causing the reported issue — so it's most likely related to specific content (such as the `<span>` elements @kristarella noted above).

If you get a report of this issue, please take a look at the shortcode content and, in the case of media-related shortcodes, the metadata saved for the media itself (such as captions or alt text). Including any details like that in your reports here will help narrow down what kind of content is causing this error, to fix the underlying issue, and may help with finding workarounds in the meantime.

**Comment by kspilarski** [comment]
I've had a user with the same issue. I've removed <span> from the contact form, and the page no longer has an error. 

1390406-zen

**Comment by sanjeev00733** [comment]
Another report in 2473315-hc

In my case the page only has two video shortcode and I don't see anything wrong with the shortcode. I also checked metadata for the videos and I didn't see anything suspicious.

**Comment by donalirl** [comment]
Another case in #6331697-hc that I was able to solve.

The contact form code was this:
`[contact-form][contact-field label="Your cute name" type="name" /][contact-field label="Your swag email" type="email" required="1" /][contact-field label="Now tell me" type="textarea" /][contact-field label="Text" type="radio" options="This is swaaag! &lt;3,Errm.. :/,Nah. XP&quot; required=&quot;1&quot; /][/contact-form]`

Instead of it showing "this is swaaag", the final quote mark rendered as `"This is swaaag! &lt;3,Errm.. :/,Nah. XP&quot; ` When I fixed that, the page could be edited again.

**Comment by thehenrybyrd** [comment]
Another in #6331117-hc 
In My Site > Blog Posts, if the user tried to edit the post "Nanny fixad, 1:a skolveckan", they got the "Invalid Post Address" error:

<img width="952" alt="screen shot 2018-10-08 at 10 42 44 am" src="https://user-images.githubusercontent.com/15107387/46598660-8dcecb80-caed-11e8-91a9-cbb697a6eef6.png">

The post was editable via wp-admin, and I could see that two gallery shortcodes were broken:
`[gallery ype="rectangular"]`
`[gallery ]`

We were able to fix it by going back to a revision from 2 Oct @ 14:56 (when the user said things stopped working). It had the correct shortcodes:

`[gallery ids="201,202" type="rectangular"]`
`[gallery ids="199,196" type="circle" columns="2"]`

The breaking changes can be seen in revision [221](https://aventyriafrikacom.wordpress.com/wp-admin/revision.php?revision=221) and [222](https://aventyriafrikacom.wordpress.com/wp-admin/revision.php?revision=222).

What's unclear to me is how these changes were made, or why the gallery shortcodes broke. Looking through the revisions, there's a progression of brokenness:

`[gallery ids="201,202" type="rectangular"]` becomes `[gallery ds="201,202" ype="rectangular"]` and then `[gallery ype="rectangular"]`

while

`[gallery ids="199,196" type="circle" columns="2"]` becomes `[gallery ype="circle"]` and then `[gallery ]`

Neither of these progressions look to me like changes the user made - the user was changing the site title during this revision. There are also some image class changes from revision 220 to 221, in a non-gallery block of images.

`
<img class="alignnone wp-image-200 size-full" src="https://aventyriafrikacom.files.wordpress.com/2018/10/dsc_0056.jpg" alt="DSC_0056" width="1280" height="853" /><img class="alignnone size-full wp-image-198" src="https://aventyriafrikacom.files.wordpress.com/2018/10/dsc_0064.jpg" alt="DSC_0064" width="1280" height="853" /><img class="alignnone size-full wp-image-197" src="https://aventyriafrikacom.files.wordpress.com/2018/10/dsc_0060.jpg" alt="DSC_0060" width="1280" height="853" />
`

becomes

`
<img src="https://aventyriafrikacom.files.wordpress.com/2018/10/dsc_0056.jpg" class="alignnone wp-image-200 size-full" height="853" alt="DSC_0056" width="1280"><img src="https://aventyriafrikacom.files.wordpress.com/2018/10/dsc_0064.jpg" class="alignnone size-full wp-image-198" height="853" alt="DSC_0064" width="1280"><img src="https://aventyriafrikacom.files.wordpress.com/2018/10/dsc_0060.jpg" class="alignnone size-full wp-image-197" height="853" alt="DSC_0060" width="1280">
`

The big changes there are the `img class`, and the rearranging of `alt`, `height`, `width`.
I'm really not sure if those are related though.

**Comment by galakhyati** [comment]
Another report: #2269155-hc

The user had contact form and the code was like this:

`[contact-field label="Item 3" type="select" options="Select colour,Brass ring - Jet Black (MYR 29),Brass ring - Brown (MYR 29),Brass ring - Rustic Brown (MYR 29),Brass ring - Steel Red (MYR 29),Brass ring - Emerald Green (MYR 29),Brass ring - Marine Blue (MYR 29),Silver ring - Jet Black (MYR 29),Silver ring - Brown (MYR 29),Gold ring - Brown (MYR 29),Gold ring - Steel Red (MYR 29),Gold ring - Emerald Green (MYR 29),Gold ring - Marine Blue (MYR 29)" required="1" <span id="mce_SELREST_start" style="overflow:hidden;line-height:0;">&#65279;</span> /]`

I removed this part: 

`<span id="mce_SELREST_start" style="overflow:hidden;line-height:0;">&#65279;</span>`

and that allowed to edit the page fine.

**Comment by jonnyruzek** [comment]
Another report: 1497410-zen

Removing an errant comma and closing a select tag with an apostrophe fixed the issue.

**Comment by adamleone** [comment]
Another report here - 1645940-zen 

The contact form was missing a " at the end of a label tag.

**Comment by jordesign** [comment]
Another report here - 1905650-zen. It does sound similar to this other open issue:
https://github.com/Automattic/wp-calypso/issues/20039

And also this old Trac ticket
https://core.trac.wordpress.org/ticket/42908

**Comment by xpurichan** [comment]
New report in 6401660-HC. Interestingly the gallery that appeared on the page wasn't supposed to be there, according to the user. They stated that they did not add it. It also appeared in the middle of a sentence.

**Comment by liviopv** [comment]
Similar report in #13848253-hc

The user noticed that when editing a gallery where the shortcode was:

```[gallery ids="24980,25107,24979,24981" type="rectangular"]```

The code would turn it into:

```[gallery ids="<span id="mce_SELREST_start" style="overflow:hidden;line-height:0;">&#65279;</span>24928<span id="mce_SELREST_end" style="overflow:hidden;line-height:0;">&#65279;</span>,24930,24934```

In a test I made, I was able to partially reproduce it by:

1. Adding a gallery using Calypso Classic Editor
2. Editing the gallery's shortcode (changed from `square` to `rectangular`)
3. Adding another image to the gallery

The result was a shortcode with `id="mce_SELREST_start" style="overflow:hidden;line-height:0"` in it for whatever reason. It didn't "break" anything for me, but it's not usual.

**Comment by tijosh** [comment]
Another one in #12580008-hc

Contents of page

```
[contact-form][contact-field label="Name" type="name" required="1" /][contact-field label="Email" type="email" required="1" /][contact-field label="Phone" type="text" required="1" /][contact-field label="Please select your item" type="select" options="Double Chocolate Brownies (1 Dozen),"A Raisin in the Sun" Vegan Oatmeal Raisin Cookies (1 Dozen),"Go Bananas about Yourself" Banana Nut Bread (1 Loaf)" required="1" /][/contact-form]
```
