### ISSUE TITLE
Stats page on marsaalamdesertretreat.com not displaying some posts/pages titles (showing number + loading title)

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#26151]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/142278191
2. Click on Stats > Scroll down to the section where it says `Posts and pages`
3. You will see under the Posts and pages section that some don't display titles, just `#1765 (loading title)` 
See screenshot: http://prntscr.com/k7xwt8
4. When you click on the actual title, it says this `We don't have that post on record yet.`.
See screenshot: http://prntscr.com/k7xxfh

This is happening on both Calypso and wp-admin. 
Screenshots in wp-admin:
http://prntscr.com/k7y0sz
In wp-admin, when you click on the actual link, it reloads the stats page. 

#### What I expected
- The Pages and Posts section of the stats showing all posts and pages titles.
- When clicking on the actual links, you will see the stats for that page / post

#### What happened instead
You will see under the Posts and pages that some titles don't display, just `#1765 (loading title)` 
See screenshot: http://prntscr.com/k7xwt8

When you click on the actual title, it says this `We don't have that post on record yet.`.
See screenshot: http://prntscr.com/k7xxfh

#### Browser / OS version
- Firefox  
- Google Chrome

#### Screenshot / Video
http://prntscr.com/k7xwt8
http://prntscr.com/k7xxfh
Screenshots in wp-admin: http://prntscr.com/k7y0sz

#### Context / Source
 #user-report 

Site: marsaalamdesertretreat.com
User: marsaalamecohealingretreat
Host: Atomic (Pressable)
Ticket: 1285418-zen
Previously reported by the same user on another ticket: 1240523-zen but it seems the issue got resolved by itself.

**Comment by alisterscott** [comment]
Hi @sourourn 

Are you able to reproduce this on a test site?

Unless you can reproduce this on a test site it doesn't appear to be a calypso specific bug and therefore doesn't belong in this repository. 

Thanks

**Comment by sourourn** [comment]
I am not sure if this helps, I exported the site's content and imported it into my test site. The same issue is showing on my test site's stats page too (see screenshot below).  Although it only showed for a few minutes and then the titles started appearing again. Maybe it's just titles loading? 

Site: wp345678.com
User: angelica10000
Screenshot:  http://prntscr.com/kagoll

**Comment by rachelmcr** [comment]
I took a look and this doesn't seem to be a Calypso issue. It's more likely related to a blog stats merge from a blog with different post IDs (so the post IDs in the stats don't match up with posts on the site). See PCYsg-2k0-p2 for more details about that or feel free to ping me on Slack. :)
