### ISSUE TITLE
Can't build production + source map

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#26170]
I was testing out #25637 and determined that our production builds no longer work when a source map is selected. This is true for master right now. It's strange though. Production builds work without a source map, and a source map build works outside of production. It's just the combination of the two.

`CALYPSO_ENV=production npm run build` works.

`SOURCEMAP=source-map npm run build` works.

`CALYPSO_ENV=production SOURCEMAP=source-map npm run build` doesn't work and gives this error.

#### Steps to reproduce
1. `CALYPSO_ENV=production SOURCEMAP=source-map npm run build`

#### What I expected

The build to succeed.

#### What happened instead

The build failed. ☹️ 

#### Browser / OS version

n/a

#### Screenshot / Video

```
TypeError: Cannot read property 'source' of undefined
    at compiler.hooks.afterEmit.tap.compilation (/Users/kevinkillingsworth/projects/wp-calypso/server/bundler/assets-writer.js:54:8)
...
```

**Comment by blowery** [comment]
This is a bug in our assets writer. Working on it.
