### ISSUE TITLE
Image replacement triggering when cursor is too close to another image with caption

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#26176]
#### Steps to reproduce
1. Add a couple images
2. Add captions
3. Place cursor next to image (with caption)
4. Add image from media inserter

#### What I expected

I expected another image to be placed without removing the image next to it

#### What happened instead
The original image in the editor was replaced by the new images

#### Browser / OS version
Chrome 67.0.3396.99 / Windows 10 (64-bit)

#### Screenshot / Video
Bug 

![calypso_bug](https://user-images.githubusercontent.com/16580129/42902507-e613ec3a-8a9c-11e8-8514-d40be975ad8c.gif)

Workaround is to add a return and then add the image
![calypso_bug_2](https://user-images.githubusercontent.com/16580129/42902508-e622a6c6-8a9c-11e8-9a67-019119b1eebc.gif)

#### Context / Source
#5098684-hc original reporting

**Comment by automattic-ian** [comment]
original reporter has returned multiple times in #1288745-zen looking for an update.
