### ISSUE TITLE
Can't access to `My Site`.

### ISSUE THREAD

**Issue by etoledom** [Automattic/wp-calypso#26183]
When creating a new account on mobile, there is an option to not create a site yet. After creating an account without a site, the `My Site` tab shows an option to create the first site.

When I log in to my account on desktop, and I try to access `My Site`, it fails. I couldn't find a way to create a site.
After going to the mobile app and creating the first site, I was able to navigate to `My Site` on Calypso.

![calypso](https://user-images.githubusercontent.com/9772967/42913955-b2e7f74c-8ac5-11e8-982f-7d56d501ef16.gif)

#### What I expected

To navigate to `My Site` section to be able to create a new site.

#### What happened instead

It stayed on the reader section, opening the Tags textfield.

#### Browser / OS version

Safari 11.1.2
Mac OS 10.13.6

#### Context

This was an old account I did for testing on the mobile app. Probably 3 or 4 months ago.

**Comment by alisterscott** [comment]
Hi @etoledom 

Thanks for the report - I can't repeat this so it may have been a once off glitch

The steps I took

1. Create new account via mobile app (iOS) without a site
2. Log onto site in calypso desktop
3. Click My Site and the site creation screen is now displayed

Would you mind re-testing?

Thanks

![new account](https://user-images.githubusercontent.com/128826/43109303-77638ebc-8f29-11e8-9d2b-1752fa2a6dcc.gif)
