### ISSUE TITLE
G Suite: email breaks after adding forwarders in Calypso

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#26196]
This is for atomic site `littlethingsstudio.com`. G Suite is linked to the site but I didn't buy G Suite from WordPress.com. I bought G Suite separately and linked it later.

**It seems really easy to break email served by another service.**

#### Steps to reproduce
1. Set up G Suite email on a site
2. Go to Domains > Email > Email Forwarding [https://wordpress.com/domains/manage/{site}/email-forwarding/{site}]
3. Add some email forwarders (e.g. sales@littlethingsstudio.com > drw158@gmail.com)
4. Try to send an email to the G Suite email address
5. You should get a "Message not delivered" fail email (see image)
6. Go to DNS Records in Calypso
7. Notice that the G Suite MX records are replaced by one that says, "Email forwarding is handled by WordPress.com" (see image)
8. Go to the G Suite admin dashboard and you'll see notices that say that the MX records are not setup. (see image)
9. Delete the "email forwarding" MX record and replace with Google MX records.
10. Email should now work
11. Go back to Email Forward in Calypso, and the email forwarders are still there even thought they shouldn't work now?

#### What I expected

To be able to add email forwarders in Calypso while having a G Suite account linked.

#### What happened instead

I added some email forwarders in Calypso, and that caused my main G Suite email to stop working.

#### Screenshot / Video

![download-6](https://user-images.githubusercontent.com/618551/42957828-65b3d7dc-8b49-11e8-95de-7863ee58d5cf.png)
<img width="622" alt="screen shot 2018-07-19 at 11 37 00 am" src="https://user-images.githubusercontent.com/618551/42957863-7af3e4b6-8b49-11e8-89ed-5d65d69d5e1e.png">
<img width="394" alt="screen shot 2018-07-19 at 11 07 53 am" src="https://user-images.githubusercontent.com/618551/42957873-808d0484-8b49-11e8-9a46-2773ca4d46ab.png">
<img width="371" alt="screen shot 2018-07-19 at 11 26 01 am" src="https://user-images.githubusercontent.com/618551/42957879-83d957be-8b49-11e8-9bd8-ec3ed26920d5.png">
![download-7](https://user-images.githubusercontent.com/618551/42957989-d94f5a04-8b49-11e8-899a-697a186f577b.png)

#### Context / Source

I set up G Suite with my domain name weeks ago, and linked it to WordPress.com. I recently needed to add email forwarders (sales@littlethingsstudio.com). I didn't see a solution using the G Suite tools. I remembered that I can do it in Calypso.

After setting up the forwarders, I saw an "email not delivered" message in my email inbox. Fortunately, I just sent an email to the G Suite email just an hour before. Eventually I figured out that the MX records in Calypso were gone.

This is pretty damaging and confusing. It was very easy to do with no warning in Calypso at all. There should be a message saying if you add forwarders you'll break your email" or something like that.

**Comment by ajaykj** [comment]
A similar but reverse in nature incident reported here: zen-1289174

**Comment by rachelmcr** [comment]
@Automattic/cobalt Is this issue on your radar? Pinging as your team seems to be the most likely to pick this one up, and it's currently marked high priority.

**Comment by rachelmcr** [comment]
I checked with Cobalt about this issue (internal ref: p1535625691000100-slack-team-cobalt) and they are tracking it but also suggested lowering the priority. This issue is rarely, if ever, reported by support, and it's rare to use forwarders in combination with G Suite.

That said, while testing I couldn't find anything that warned me not to add email forwarding. It seems the WP Admin domain manager prevents this, but in Calypso I didn't see any messaging/warnings about what would happen by setting up forwarding.

See also https://github.com/Automattic/wp-calypso/issues/20208 for the opposite situation (losing email forwarding when adding G Suite).

**Comment by drw158** [comment]
Just for the record, I labeled it high because it breaks someones email without their knowledge, and it's pretty easy to do using Calypso tools.
