### ISSUE TITLE
Reader: Sharing with WordPress still opens wp-admin Press This

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#2619]
We need this to be a native Calypso Reader experience, more integrated and easy than a popup window with wp-admin.

<img width="261" alt="screen shot 2016-01-20 at 10 57 40 am" src="https://cloud.githubusercontent.com/assets/1464705/12454241/a3cf48fc-bf64-11e5-8cc7-95475f4a0a03.png">

**Comment by shawnajean** [comment]
I had a user today who wanted to share the post from the Reader to their second site, not their primary site. 295856-chat 2500670-t

**Comment by catkit** [comment]
Same here: 2541004-t

**Comment by m** [comment]
Don't think this is worth a new bug, but this is doubly broken in that it tries to launch press-this at my Jetpack site, with the wrong URL.

https://cloudup.com/c3dTxtlDp1k
