### ISSUE TITLE
Sidebar: alignment issues in /checkout/thank-you

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#262]
The recent changes in the sidebar caused some alignment issues in the Thank You screen (`/checkout/thank-you`):

![screenshot-calypso localhost 3000 2015-11-20 12-57-28](https://cloud.githubusercontent.com/assets/1248436/11299521/bc03fa24-8f87-11e5-9c15-9d115f74a118.png)

The content in this screen used to be aligned to the center, and is now aligned to the left.

cc @shaunandrews

**Comment by breezyskies** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/302. Closing.
