### ISSUE TITLE
Stats: the comments module can be inaccurate for Jetpack sites, should we remove it?

### ISSUE THREAD

**Issue by jonathansadowski** [Automattic/wp-calypso#2621]
Comments are only synced from Jetpack sites on creation / update, and even then, only under certain circumstances. This leads to the comments module within Stats being inaccurate in many circumstances. Should we hide the module for Jetpack sites until comments are synced back to WPCOM more consistently?

**Comment by jeherve** [comment]
Also reported [here](https://wordpress.org/support/topic/comments-231). In this particular case, comments from Custom Post Types didn't get synchronized, even after whitelisting the CPT in the API and reindexing the site.

**Comment by lschuyler** [comment]
Noticed by a Jetpack user in #2991982-t.

**Comment by jeherve** [comment]
Still an issue

**Comment by jeherve** [comment]
Still an issue
