### ISSUE TITLE
"List End" marker missing on Site Pages list when viewing pages hierarchically (site with 100 pages or less)

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#26224]
The "list end" marker, the little WordPress W, seen here on the Blog Posts screen …

![image](https://user-images.githubusercontent.com/545779/43011134-355e666e-8c08-11e8-806e-98b344149063.png)

… is missing from Site Pages lists when viewing pages hierarchically (site with 100 or less pages). Like so …

![image](https://user-images.githubusercontent.com/545779/43011148-4297edb4-8c08-11e8-9bf3-d8cdad89bcfb.png)

It seems to appear on Custom Post Type list screens. Leaving Site Pages the inconsistent, odd one out.

----

### Tasks

- [x] Add list end marker when in hierarchical view for Site Pages

**Comment by mattsherman** [comment]
Yes, under the hood, Pages is a completely different implementation than Posts and CPTs. While moving the Pages implementation over to the same one as Posts and CPTs is still desired at some point, perhaps this small inconsistency could be addressed prior to that.

**Comment by mattsherman** [comment]
Actually, the "list end" W does appear for Pages, if viewing a site with more than 100 pages, in which case the pages are shown chronologically instead of hierarchically. I will update the issue description to make this clear.

**Comment by creativecoder** [comment]
@ianstewart While we're at it...

The `ListEnd` component does not show for Page lists that are empty (like the Scheduled page list)

<img width="1014" alt="screen shot 2018-08-23 at 16 56 34" src="https://user-images.githubusercontent.com/1699996/44554319-1a682a80-a6f6-11e8-84a1-c937298a023d.png">

But `ListEnd` _does_ show for empty Post lists

<img width="952" alt="screen shot 2018-08-23 at 16 56 58" src="https://user-images.githubusercontent.com/1699996/44554338-248a2900-a6f6-11e8-97e7-c333c3792243.png">

I think these should be consistent, and would hide `ListEnd` for empty lists (like the second example)--does that seem right to you?

**Comment by michaeldcain** [comment]
#26883 is ready to go.

**Comment by creativecoder** [comment]
Actually I think I answered my own question: all other list sections that are empty do not show the ListEnd component, so I'm going to remove it from the empty Post list sections.

**Comment by creativecoder** [comment]
This is been fixed on production with #26883.

**Comment by mattsherman** [comment]
Nice work! Accepting.
