### ISSUE TITLE
Editor: Unable to access the Image Detail modal for images without all wp class attributes

### ISSUE THREAD

**Issue by sarahfg** [Automattic/wp-calypso#26235]
#### Steps to reproduce
1. Starting at a post for a private site that has been previously published. Some do this and some do not
2. Click on an image
3. Attempt to click on the Pencil Icon

#### What I expected

That the image information box would open to add alt text or a caption to the image

#### What happened instead

No box appeared

#### Screenshot / Video

http://cld.wthms.co/mfAKyi

#manual-testing and #user-report in #5152293-HC

**Comment by rachelmcr** [comment]
I couldn't reproduce this issue with a newly published post, but I did reproduce it when the image in the post was missing a `wp-image` class.

I'm not sure what steps can be used to organically add an image to a post without that class — I tested with newly published posts created in Calypso, iOS, and Android and images all had the `wp-image` class (along with other wp class attributes) and the Calypso image edit icon worked as expected. (Older versions of the apps didn't add wp class attributes, so older posts created in the apps may have this issue.)

However, if I removed the `wp-image` class from an image in the HTML editor, I was able to reproduce the issue.

As a workaround, removing the image from the post and re-adding it from the site's media library ensured it had the necessary class attributes and resolved the issue.
