### ISSUE TITLE
2-year billing option not displayed on Pricing page

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#26242]
#### Steps to reproduce

1. Go to: https://wordpress.com/pricing/
2. See "per month, billed yearly"

<img width="1280" alt="screen shot 2018-07-22 at 16 49 25" src="https://user-images.githubusercontent.com/3812076/43044613-87e372f4-8dd3-11e8-9b23-ba0a238fd99d.png">

3. Go to: https://wordpress.com/plans
4. See "/month, billed annually or every two years"

#### What I expected

Consistency between both.

**Comment by rachelmcr** [comment]
The /pricing page isn't part of Calypso, so I'm going to close this issue — any updates to that page will need to be made outside this repo.

@jaswrks I see you've been working on the updates to the /pricing page. Is the 2-year billing option on your radar for this page?

**Comment by jaswrks** [comment]
Thanks for reporting this! It wasn't on my radar but it is now: p9f5aF-1g1-p2
