### ISSUE TITLE
Skype call link prefix changed on newer accounts

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/wp-calypso#26241]
The user in the reference thread was trying to put their Skype call link into their social menu so it would initiate the Skype program and start a call, but our system is expecting `skype:myusername?call` and on newer accounts where the user also uses a @outlook.com email address, Microsoft has changed things, and the call link would be `live:myskypeusername?call`. If you put that into the social menu and save, it will not initiate a Skype call when clicked.

#### Steps to reproduce

1. Set up a new MS account and then a Skpe account, which uses the outlook.com email address (example here: myusername@outlook.com).
2. Your Skype ID will then be `live:myusername` and the call link will be `live:myusername?call`

The user has provided some additional details in the forum thread linked below.

#### Context / Source
User reported in this forum post: [https://en.forums.wordpress.com/topic/skype-user-id/#post-3148151](url)

Can we update so that it will work either with `skpe:` or `live:`

**Comment by alisterscott** [comment]
@thesacredpath thanks for raising this, the [code](https://github.com/Automattic/jetpack/blob/1f4507e0cbfdbdec3eadc099a03c2799fd0f0f2c/modules/theme-tools/social-menu/icon-functions.php) for menus isn't in Calypso - would you mind raising this in the Jetpack repository? 

https://github.com/Automattic/jetpack

Thanks
