### ISSUE TITLE
Plans: Reduxify the Plan Remove page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#2626]
[As suggested](https://github.com/Automattic/wp-calypso/pull/2311#discussion_r50060573) by @drewblaisdell, we should move [the call to the REST API](https://github.com/Automattic/wp-calypso/blob/9d17d75edf1eae28cbdb4c102c8c8da00fb4f5a6/client/my-sites/plans/plan-overview/plan-remove/index.jsx#L39) in the `removePlan()`function in the `<PlanRemove />` component into its own thunk action creator in `state/sites/plans/actions`. We could then map it to a function passed through props in the second argument of `connect`.This also means that we wouldn't need to access the dispatcher through `this.props.store.dispatch` as it would be provided to the action creator.

**Comment by fabianapsimoes** [comment]
Fixed in #2952.
