### ISSUE TITLE
Customizer: Jumpy scrolling in CSS pane in Chrome when site has lots of CSS

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/wp-calypso#26287]
The easiest place to see this behavior is in the Customizer on this site: http://piedtype.com/ in Chrome browser on Mac as this site has quite a bit of Custom CSS.

#### Steps to reproduce
1. Starting at URL: https://piedtype.wordpress.com/wp-admin/customize.php
2. Open CSS pane
3. Scroll down and watch the CSS display and the scroll bar and you will see it does not scroll smoothly.
4. When the scrollbar jumps, it moves you up or down by a good bit, making it somewhat difficult to get to the CSS that you are wanting to edit.

#### What I expected

Smooth scrolling like in Safari and Firefox

#### Browser / OS version

Chrome Version 68.0.3440.75 (Official Build) (64-bit) - Mac OS 10.13.6
Did not test on Windows

#### Screencast

https://cldup.com/LG9GCrizcf.mov

Forum thread: https://en.forums.wordpress.com/topic/css-stylesheet-editor-scrolls-erratically/#post-3149889

**Comment by rachelmcr** [comment]
Thanks for reporting! I'm closing this issue as the customizer isn't part of Calypso and this issue is being tracked in another repo.
