### ISSUE TITLE
Plans: Long plan descriptions should wrap to next line

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#26282]
Currently, the plan descriptions on wordpress.com/plans/example.wordpress.com, look fine in English. However, when translated to another language, they can overflow the content box, which doesn't look great. We should just wrap it to the next line.

**To repro:**

1. Visit https://wordpress.com/plans/ for a site on your account.
2. Either change the language to French (how I found it) or edit the HTML to "/month, billed annually or every two years. But what if it's longer than that?"

**Screenshot**

<img width="673" alt="screen shot 2018-07-24 at 11 37 12 am" src="https://user-images.githubusercontent.com/7240478/43156211-bcba8bf2-8f36-11e8-9223-e2d2e201c2a7.png">

**Comment by AmandaJBell** [comment]
Hi @jeremeylduvall I'd like to try this one. Is there anyone working on it already?

**Comment by jeremeylduvall** [comment]
@AmandaJBell I don't think so! Feel free to work on it. If you haven't already, check out our [contributing guidelines](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md) as it has some specific suggestions around branch naming conventions, etc. Feel free to assign me to review when you're ready, and I'll take a peek.

And thank you for taking this on!

**Comment by AmandaJBell** [comment]
Okay I'll get started, thank you!

**Comment by rachelmcr** [comment]
Closing as resolved in https://github.com/Automattic/wp-calypso/pull/26358.
