### ISSUE TITLE
Editor: Prevent Use of Editor from Core-Apps Webviews

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#263]
Currently it is possible to launch a webview from within the core apps and navigate to "My Sites" and use the calypso editor.  Ideally we should nudge users to not use the editor in this manner, and use the core-app editor instead.

I chatted a bit with @astralbodies about this and he shared the following interesting bits:
- The session used in the iOS app can be entirely different than the web view content.  As such, you can not count on directing the user to the core editor using an app link for a certain site.  Work is underway to have shared sessions between the webviews and the iOS app though.
- It is possible to add logic to the webview to "sniff" out urls and redirect in-app, but this currently is not being done much at all in iOS
- Another solution would be to watch for the `wp-iphone` and `wp-android` user agents set in the webviews, and react in calypso accordingly

The last option seems like the most graceful at the moment to me.  Perhaps a simple middleware that looks for these user agents that could be applied to editor routes, and if a web-view is detected, display a message saying "Please use your app to perform this action".  While directing to the proper in-app action would be nice, it sounds like it isn't 100% possible yet with the un-shared sessions.

**Comment by alisterscott** [comment]
I can no longer see My Site in the WPiOS app so I can't reproduce this issue any more. Please re-open if still relevant.
