### ISSUE TITLE
Use <label> instead of <legend> to mark the name of a dropdown field

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#26302]
The label of a dropdown form field isn't being read out by an screen reader (e.g. ChromeVox). We're incorrectly using a `<FormLegend />` instead of `<FormLabel />` to label the dropdown form elements:
https://github.com/Automattic/wp-calypso/blob/03ddf9aaa09ae9af56338da57c54e5a4cef1b5eb/client/extensions/woocommerce/woocommerce-services/components/dropdown/index.js#L33

Labels are used for labelling one element, whereas legends are used for labelling a collection of form elements ([MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form)).

Adding to that, we should investigate all the usages of `<legend>` or `<FormLegend>` in our extension, since we have been using `<legend>` and `<label>` pretty much interchangeably so far.

cc/ @v18

**Comment by nerdysandy** [comment]
Based on the labels added this is related to Store. We're sunsetting Store by Feb,2021. Closing it in favour of that
