### ISSUE TITLE
Stats: Post views stats for site in different sections of Stats panel that don't correspond with actual views

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#26319]
This is a report from a user in 3651319-hc with a follow-up in 1270195-zen. The issue was also discussed here: p1532556893000284-slack-C029ENR23.

The user report is as follows:

>Hello. While I was editin one of my published posts I realzied that it automatically dropped to "DRAFTS" section. I had to Re-Publish it and now its stats are broken. I can see the views that came after I Re-Published my post again. Also same thing happened for an old post, now it has 4 likes and zero views! Also the ordering of posts on my blog page is broken due to Draft- Republish issue and I can't seem to correct the order of posts by dragging them or anything.

#### Steps to reproduce

* On investigation, we noticed that posts' actual views don't correspond with reported stats
* One post (designated "Post 1") has 71 views over its lifetime, but when you view individual post stats, there are only 20 views
* The lifetime views are apparent in **Stats** > **Traffic** with the date range set to `Years`

![](http://cld.wthms.co/iAy6fQ+)

* Post views are apparent in **Stats** > **Insights** where the post's apparent total views are reflected too.

![](http://cld.wthms.co/EB4Mvl+)

#### What I expected

Reported stats in **Traffic** and **Insights** should correspond with each other in respect of the same content, across the same time periods.

#### What happened instead

These two sets of stats don't correlate at all.

#### Browser / OS version

Browser and OS versions are not relevant to this issue.

#### Context / Source

#manual-testing #user-report

**Comment by Piyopiyo-Kitsune** [comment]
I updated the user and placed the ticket on hold

**Comment by detlefholtz** [comment]
More information from the user about the issue: 

>this event occured on mobile application. The posts dropped to draft (as if yet unpublished) after I edited (it was not really an edit but just to view the text, I quit the editing by saying “discard the changes.”) the posts on mobile application. The publication dates of last two posts are wrong (they show the “re-published” date), one post was originally published in sep/oct 2017 (don’t remember the exact date).
