### ISSUE TITLE
SDK: move publicize block to Calypso

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#26362]
Pull out this: https://href.li/?https://github.com/Automattic/jetpack/pull/9934

To `/client/gutenberg/extensions/*`

Ensuring it doesn't fatal latest Gutenberg at the minimum. Improving the code along the way at best. 🙌

**Comment by tyxla** [comment]
#26389 introduces the extension for Gutenberg - you can test it in conjunction with https://github.com/Automattic/jetpack/pull/9963
