### ISSUE TITLE
Pages: page states that are not user-facing should not be translated

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2639]
Raised by @jenial 

Translation calls were added for page states (30c83ce-gh-calypso-pre-oss). See https://github.com/Automattic/wp-calypso/blob/d0141897e584c621ad5d82071a4190b9740e999b/client/my-sites/pages/page.jsx#L29-L36

When I queried @mtias (in Slack) regarding page states: 'Published', 'Draft', 'Pending', 'Future', 'Private', 'Trashed', 'Draft', 'Inherited', the response was that they are not meant to be user-facing and therefore don't need translation. I am not 100% sure how they are used, but especially 'Future' and 'Inherited' is not something a WordPress.com user would see.

Could you please remove the translation calls for strings that are not user-facing?

**Comment by lancewillett** [comment]
I don't understand why these shouldn't be translated. ¯\_(ツ)_/¯

Current version of that file: https://github.com/Automattic/wp-calypso/blob/9cb2557484fc059ab3af01be5de03e913770abf1/client/my-sites/pages/page.jsx#L29-35 — still has them as translatable labels.

**Comment by jenial** [comment]
Making not user-facing strings translatable increases the string count in GlotPress, and therefore translation cost and overhead. It's the matter of good housekeeping.

**Comment by designsimply** [comment]
@mtias, can you confirm the following do not need to be translated? 
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/pages/page.jsx#L28-L35

**Comment by mtias** [comment]
The last two don't.
