### ISSUE TITLE
Build: running prettier on scss files removes the space in parentheses 

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#26401]
#### Steps to reproduce
1. Make changes to a scss file - add spaces to parentheses as per calypso style guide eg. 
```
@media ( min-width: $plan-features-sidebar-width + 480px ) {
		display: none;
	}
```
2. Run prettier on the file

#### What I expected

spaces inside parentheses to remain

#### What happened instead

```
	@media (min-width: $plan-features-sidebar-width + 480px) {
		display: none;
	}
```

#### Context / Source

Raised as part of https://github.com/Automattic/wp-calypso/pull/26358

**Comment by jsnajdr** [comment]
Fixed by Prettier upgrade in #26386.
