### ISSUE TITLE
Activity Log: False alarm alerts for core updates

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26412]
<img width="1588" alt="stats_ _cafeworking_com_ _wordpress_com_and_slack_-_a8c" src="https://user-images.githubusercontent.com/2694219/43464217-7cd78b08-94a8-11e8-8a94-478ffb2f9254.png">

h/t @beaulebens for the report.

**Comment by enejb** [comment]
Related D16802-code

**Comment by enejb** [comment]
Deployed D16802. Which should hopefully fix this error.
