### ISSUE TITLE
Themes: better messaging on "no theme found" screen

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2641]
Raised by @kathrynwp 

Since there are no filters (other than free/premium) we should remove the reference to trying “more filters” on the “no themes found” page:

![themes wordpress com - private browsing -3](https://cloud.githubusercontent.com/assets/7662449/12456215/c39304c8-bf6c-11e5-82cb-c0faf23e196d.png)

Suggested alternate wording:
- Try broadening your search
- Try widening your search

**Comment by designsimply** [comment]
Here is a screenshot of a prior version for comparison:

![screen shot 2016-01-20 at 16 51 59](https://cloud.githubusercontent.com/assets/1119271/12464507/43dd5456-bf97-11e5-89d8-c713c69eb87d.png)
<sup>Seen at https://wordpress.com/themes/search/yoga/ using Firefox 43.0.4 on Mac OS X 10.10.5</sup>

**Comment by folletto** [comment]
Suggestion by @meremagee from #7307: 

> Suggestion: flip the script from showing nothing to showing everything or showing the most popular/generic/extensible themes, with a little inline notice that says something to the tune of ~“darn, we couldn’t find anything particular for your search, but these popular themes can be edited to build almost anything.”

**Comment by folletto** [comment]
This component has been updated with the new magic search component that allows a full set of filters.

Closing.
