### ISSUE TITLE
Activity Log: Add Welcome Banner

### ISSUE THREAD

**Issue by gititon** [Automattic/wp-calypso#26421]
p9rlnk-p5-p2

**Comment by joanrho** [comment]
@roccotripaldi @gititon Here's the updated design mockup:

<img width="721" alt="01_intro" src="https://user-images.githubusercontent.com/204742/43659156-5d0b7402-9718-11e8-8f81-af161fcccb18.png">

link to [svg asset](https://cloudup.com/iJLSVGm6PnO).

ref: p9rlnk-pN

**Comment by enejb** [comment]
I was running into some issues with building calypso. So I used the [playground](https://wpcalypso.wordpress.com/devdocs/playground) to try it out. 
```
<Main>
    <Card>
    <EmptyContent title="Explore your site's activity"
      line="Stay informed of all your site's activity ranging fro mplugin and theme updates to user logins and settings modifications. Learn More"
     
      secondaryAction={<a className='empty-content__action button'
            href='/discover'>
            Got it
          </a>}
      illustrationWidth={200}
      illustration={'https://cloudup.com/files/iJLSVGm6PnO/download'}
       />
    </Card>
</Main>
```

Which looks like this.

<img width="688" alt="screen shot 2018-08-03 at 5 07 22 pm" src="https://user-images.githubusercontent.com/115071/43670362-bda51b2a-973f-11e8-8a9a-a81812e7a066.png">
