### ISSUE TITLE
Activity Log: update upgrade banner copy and position

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26420]
Currently our upgrade banners appear at the top of the activity log.
For our current sprint, we are going to move them to the bottom, and adjust the copy.

See: p9rlnk-p5-pw

**Comment by joanrho** [comment]
@roccotripaldi @gititon Here's the updated design mockup:

<img width="717" alt="02_upgrade" src="https://user-images.githubusercontent.com/204742/43659245-a45f48f6-9718-11e8-800d-11c9a2df5f41.png">

link to [svg asset](https://cloudup.com/iU76nRp350j).

ref: p9rlnk-pN

**Comment by enejb** [comment]
I wonder if for this banner if we should use the https://wpcalypso.wordpress.com/devdocs/design/action-panel ?

**Comment by MichaelArestad** [comment]
Current plan for Jetpack sites:

![image](https://user-images.githubusercontent.com/1123119/43799660-67d27116-9a4b-11e8-9aea-2736f5419269.png)

We need copy for dotcom as well. CC @joanrho 

Will get to this after lunch, but I think just tweaking language and plan names will work (I think).

**Comment by MichaelArestad** [comment]
WordPress.com version:

![image](https://user-images.githubusercontent.com/1123119/43801958-b97ebc4e-9a51-11e8-925b-36fd1b34b64b.png)
