### ISSUE TITLE
Themes: search prompt gets cut off on mobile

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2643]
Steps to reproduce:

1. Go to https://wordpress.com/design while logged out
1. View the search prompt

<strong>Result:</strong> the search prompt text is cut off:

<img alt="img_7210" src="https://cloud.githubusercontent.com/assets/1119271/12464719/541656be-bf98-11e5-9206-550b1119570f.PNG" width="400" />
<sup>Tested with Safari iOS 9.2 on iPhone 6</sup>

/hat tip @rachelmcr for the original report

**Comment by lancewillett** [comment]
Testing this on iOS 9.3.1 with iPhone 6+ and in the Simulator for iPhone 6, rotating to both landscape and portrait.

No longer an issue as it looks to be redesigned recently.

<img src="https://cloud.githubusercontent.com/assets/66797/14433535/77e40a12-ffc3-11e5-85ef-8e3583f6d837.png" width="480" />

<img width="779" alt="screen shot 2016-04-11 at 08 56 40" src="https://cloud.githubusercontent.com/assets/66797/14433539/7ae7a052-ffc3-11e5-949f-74e171acf88a.png">

<img src="https://cloud.githubusercontent.com/assets/66797/14433544/7e243a64-ffc3-11e5-825e-c2d0e58822cb.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/14433573/9f8f4450-ffc3-11e5-8a00-df1aebcc1c4c.jpg" width="480" />
