### ISSUE TITLE
Domains: Prevent user entering whitespace only string on form fields

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#2644]
In the page where we gather user's information, an empty string allows the user to bypass the verification page but the registration fails afterwards.

We should check if there's a proper text in the fields after stripping the whitespace.

Props for @ashercantrell bringing it up.

**Comment by ashercantrell** [comment]
Example of a user doing this: https://groups.google.com/a/a8c.com/forum/#!searchin/email-archive/deliriarose.com/email-archive/ozyqR7VEnbI/43w_gHK7CAAJ

**Comment by umurkontaci** [comment]
/cc: @aidvu This might be better done in backend?

**Comment by klimeryk** [comment]
This has been fixed by #4454.
