### ISSUE TITLE
Guided Tours: First step in contact page tour (from checklist) overlapped by page settings

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#26441]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checklist/:site for a newly created account/site
2. Select "Do it!" for the Personalize Your Contact Page item.
3. When the editor opens, note the position of the first step relative to the page settings menu

#### What I expected

I expected the steps in the guided tour to always be visible (when needed).

#### What happened instead

The first step in the guided tour was overlapped by the page settings. For a newly created account that hasn't yet confirmed the email address, the prompt to confirm the email address also overlapped the guided tour.

#### Browser / OS version

Chrome 67 / macOS 10.13.6

#### Screenshot / Video

<img width="1552" alt="screenshot 2018-08-01 15 24 05" src="https://user-images.githubusercontent.com/8658164/43528329-9bbe0756-95a0-11e8-98e1-51c358f8d06c.png">

<img width="1552" alt="screenshot 2018-08-01 15 24 12" src="https://user-images.githubusercontent.com/8658164/43528338-a0c269e0-95a0-11e8-93b6-13ac691118ad.png">

#### Context / Source
#dogfooding

**Comment by ramonjd** [comment]
![oct-19-2018 16-36-27](https://user-images.githubusercontent.com/6458278/47199397-281bf280-d3bd-11e8-9599-eb23d5ba64b1.gif)

We could bump up the `z-index` of the modal (it's at `1`):

https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/tours/checklist-contact-page-tour.js#L37
