### ISSUE TITLE
Link to be Amended in the DNS section

### ISSUE THREAD

**Issue by thebud15** [Automattic/wp-calypso#26452]
#### Steps to reproduce

Visit https://wordpress.com/domains/manage and head to turn on the TXTrecord toggle. The "Read More" button currently links to the nonexistent https://support.wordpress.com/domain-connect page.

#### What I expected

I expected that the "Learn More" link would connect to an accurate article .

#### What happened instead

It leads to a former link, and now just turns up general search results. This could be fixed by instead having the "Learn More" button link to https://en.support.wordpress.com/domains/custom-dns/

#### Browser / OS version
Mac, Safari

#### Screenshot / Video

http://cld.wthms.co/hfSOwB

#### Context / Source
An upcoming HE trial pointed this out.

-->

**Comment by klimeryk** [comment]
Thanks for reporting! @delputnam is actually working with @wensco on the content of that missing support page (which we've realized only after it was launched...) in `p99Zz8-nN-p2`. Should be resolved soon - will update here once it's published 👍

**Comment by delputnam** [comment]
The new documentation isn't quite ready yet, so I've removed the broken link in #26454 until we can get the documentation updated. Once we have the support pages updated, I'll add the correct link back in.
