### ISSUE TITLE
Themes: Business Plan Nudges show for simple sites on Business plans blocking uploading themes and plugins

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#26458]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com with a simple site on a business plan
2. Set the AB test group to `customPluginAndThemeLandingPages`
3. Go to Themes - Upload a Theme (or Plugins - Upload a Plugin)

#### What I expected

To be able to upload as I'm on business plan

#### What happened instead

See a nudge to upgrade to business 

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

<img width="1697" alt="screen shot 2018-08-02 at 1 03 58 pm" src="https://user-images.githubusercontent.com/128826/43560158-8b9e6b72-9654-11e8-91a0-15d2008ba7a6.png">

**Comment by alisterscott** [comment]
cc @markryall

**Comment by alisterscott** [comment]
Workaround in https://github.com/Automattic/wp-calypso/pull/26459 to disable this feature

**Comment by rachelmcr** [comment]
I retested these steps with the current AB test in the `customPluginAndThemeLandingPages` group and it works as expected now. (I'm able to upload on sites with the Business plan and Jetpack sites, and I see the nudge for sites on other plans.) Closing as resolved.
