### ISSUE TITLE
Inline Help: hide on DevDocs views

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#26457]
#### Steps to reproduce
1. Starting at URL:  https://wordpress.com/devdocs
2. View bottom right, see the Help menu

#### What I expected
Not to see Help on views like DevDocs, since they are for "teaching" and other uses and not core part of the product that a customer would need help on.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/66797/43555295-332b263e-95ae-11e8-9289-30bb0c24c9c2.png)

Via @ianstewart

**Comment by spen** [comment]
Tracking in @Automattic/delta-samus - This should be a very easy change so I'll get right on it once I'm at a good checkpoint with the redux task I'm working on :)

**Comment by torres126** [comment]
Is this still being worked on btw? It feels fairly low priority, so could maybe just be done with CSS?

`.is-section-devdocs .inline-help {
display: none;
} `

Or if the environment badge was also to be moved:

`.is-section-devdocs .environment-badge { 
 right: 20px;
}`

(GitHub seems to mess up the formatting with that!)
