### ISSUE TITLE
Sharing: Can't connect Facebook page for publicize

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#26460]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/yoursite
2. Disconnect a Facebook page connection
3. Add a new Facebook page connection

#### What I expected

Connection added

#### What happened instead

Can't add connection

Console warnings:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://eatkibbeling6.wordpress.com/wp-admin/options-general.php?page=sharing&action=error&service=facebook&id=20594016. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://eatkibbeling6.wordpress.com/wp-admin/options-general.php?page=sharing&action=error&service=facebook&id=20594016. (Reason: CORS request did not succeed).
```

#### Browser / OS version

Chrome and Firefox on macOS

#### Screenshot / Video

![fb](https://user-images.githubusercontent.com/128826/43563520-dd02e752-9665-11e8-991d-5dfbc59b5dfe.gif)

**Comment by kristarella** [comment]
I had this too, and a user did as well.

support reference: 4589696-hc

**Comment by MindyPostoff** [comment]
Another user report here: 1314279-zen

**Comment by thebud15** [comment]
Ticket opened here for follow up on this issue: 1319744-zen after having been reported at 560433-hc

**Comment by cbauerman** [comment]
This bug is actually caused on the server side, I am in the process of fixing. Going to go ahead a close this in favor of the fix at D16801.
