### ISSUE TITLE
Menus: Project Tag converted to Post Tag when same slug is used

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#26481]
#### Steps to reproduce
1. Select a theme that supports Portfolio then create a Project Tag and Post Tag with the same slug. Let's say `test`
2. Starting at URL: https://example.wordpress.com/wp-admin/customize.php
3. Click on Menus > Menu Name >  Add Item. Then, Project Tag > test
4. Once added you'll notice `Project Tag` switches to `Tag` in the menu. 
5. Click on the menu item and be taken to the post tag.

#### What I expected

To have the Project Tag added to the menu.

#### What happened instead

The Post Tag was added to the menu

#### Browser / OS version
Firefox 61 Linux Ubuntu 18.04

#### Screenshot / Video

Video:https://cloudup.com/cVIaTBV5IuL

#### Context / Source

https://en.forums.wordpress.com/topic/project-type-converted-to-tag-in-menu/

#user-report

**Comment by donalirl** [comment]
Related to #138

**Comment by BandonRandon** [comment]
Closing as moved. In the customization repo linked above.
