### ISSUE TITLE
Blank screen after removing domain mapping from cart on paid plan

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#26482]
#### Steps to reproduce
1. on a paid plan, select Domains → Add (or go straight to https://wordpress.com/domains/add/ )
2. add any existing domain name
3. select "Yes, I own this domain"
4. select "Buy Domain Mapping"
5. select blue "Add" button
6. from the order summary on the left, remove the domain mapping by selecting the garbage can

#### What I expected
Should be taken back to Calypso.

#### What happened instead
Blank screen, with console log shows vague error:
`Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined`

**Comment by delputnam** [comment]
Added missing default value to `initialQuery` to address this issue.

Thanks for reporting it @senff !
