### ISSUE TITLE
Importers: improve wording on "Import Another Site" screen

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#26517]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/example.wordpress.com
2. Look at the wording under each service

#### Suggested changes

As we grow this list, let's find a better way to word the types of content that each importer supports.

#### Screenshot / Video

![screen shot 2018-08-06 at 13 40 45](https://user-images.githubusercontent.com/66797/43732003-55e2e76a-997e-11e8-9e66-3b017e95f552.png)

_Viewing in Safari 11.11.1 on macOS 10.13.5_

#### Source

Props @ianstewart for pointing this out: 

> We have a checkerboard of terminology for images/media here.

**Comment by dezzie** [comment]
Closing out this issue because there's newer/redundant work going on here:
https://github.com/Automattic/wp-calypso/pull/31962
