### ISSUE TITLE
Editor: warn about invalid Simple Payment Button Id

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#26539]
As a follow up to https://github.com/Automattic/wp-calypso/pull/26469, I'll be a nice addition to the editor to have a way to show to the user that the payment id entered on the shortcode is invalid.

#### Steps to reproduce
1. Starting with a Premium or Business Site
2. Add a Simple Payment Product to a Page or Post using the Editor.
3. Save or Update the Changes
4. Remove the product by clicking on Add > Payment Button and removing the selected item leaving the shortcode on the post or page.

#### What I expected
To see a warning that the code does not correspond to a valid product, which should enable the tools to edit the item (create new product or select an existing one) or remove it without changing to the code view.

#### What happened instead

| Visual | Code |
| - | - |
| ![screen shot 2018-08-07 at 18 10 20](https://user-images.githubusercontent.com/233601/43802830-6700614a-9a6d-11e8-80b2-bd7c19384c69.png) | ![screen shot 2018-08-07 at 18 09 37](https://user-images.githubusercontent.com/233601/43802845-6ec2b734-9a6d-11e8-88d9-00d997f183a5.png) |

#### Browser / OS version
All browsers and OS versions.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
