### ISSUE TITLE
Plugins: No more single plugin view of for Atomic sites.

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#26570]
In #25767 we introduced the calyponified version of the plugin section. 

Which redirect the plugins section to the wp-admin version of the plugin section. 

#### What I expected
In the activity log we link users to a specific plugin page. 
<img width="1067" alt="screen shot 2018-08-09 at 8 50 41 am" src="https://user-images.githubusercontent.com/115071/43910355-6fa2d84c-9bb1-11e8-8d98-1002f21fc44e.png">

I expect to be redirected to the single plugin view. 
<img width="895" alt="screen shot 2018-08-09 at 8 46 07 am" src="https://user-images.githubusercontent.com/115071/43910172-f44fa210-9bb0-11e8-936a-cfbde44e7e09.png">

or 
<img width="1013" alt="screen shot 2018-08-09 at 8 43 17 am" src="https://user-images.githubusercontent.com/115071/43910184-fb647ef4-9bb0-11e8-9794-72a82a5d4d89.png">

#### What happened instead
The user gets redirect the the calypsofied  version of the plugins page and they end up looking at all the plugins that are installed.
<img width="1383" alt="screen shot 2018-08-09 at 8 43 39 am" src="https://user-images.githubusercontent.com/115071/43910208-0a8fd8e2-9bb1-11e8-871f-0f2e58e5f402.png">

**Comment by enejb** [comment]
cc: @apeatling && @retrofox

**Comment by retrofox** [comment]
it's handled here: https://github.com/Automattic/wp-calypso/pull/26333
