### ISSUE TITLE
Activity Log: add user sync module to track events on .com sites

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26589]
Currently we are only tracking user invites for .com sites.

Let's add the full jetpack sync module for users so that we are capturing when users are added or removed from .com sites.

**Comment by rachelmcr** [comment]
@roccotripaldi Could you add an appropriate `[Type]` label for this issue? Thanks!

**Comment by gititon** [comment]
Done in D17340-code, D17258-code, https://github.com/Automattic/jetpack/pull/10034
