### ISSUE TITLE
Activity Log: add feedback types to the stream

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26584]
We are already logging feedback posts in the Activity Log, but we are not displaying them because there are no stream files yet.

Let's add them!

**Comment by roccotripaldi** [comment]
@MichaelArestad will add mocks here.

**Comment by MichaelArestad** [comment]
![artboard](https://user-images.githubusercontent.com/1123119/44103724-3d1d67e6-9faa-11e8-9206-763bf283e33d.jpg)

Notes:
* The icon is `<Gridicon icon="caption" />`
* The first link should go to the feedback item in the editor (not ideal, but it's what we have)
* I'm not sure we should have the second link. If so, should it link to the page the form is on? I am not sure we can actually link the form in Calypso. Let me know what is possible (or Joan if I'm AFK)

**Comment by roccotripaldi** [comment]
@MichaelArestad - i've started on this in D17241-code

Here's a screenshot showing feedback submitted when the poster is known / logged in:

<img width="1064" alt="screen shot 2018-08-15 at 2 04 53 pm" src="https://user-images.githubusercontent.com/2694219/44168671-07bf7700-a0a0-11e8-8b31-081c882e8078.png">

And when the poster is logged out / anonymous:

<img width="1062" alt="screen shot 2018-08-15 at 2 04 43 pm" src="https://user-images.githubusercontent.com/2694219/44168696-13ab3900-a0a0-11e8-8607-8036fafe51c2.png">


The reason i needed to simplify so much from your mocks is because we don't have a ton of useful data attached to the activity currently.  We'll need to update Jetpack in order to capture more meaningful data, and it's a bit tricky because the form itself is highly customizable. We'd love for you and @joanrho to be part of the conversation on improving the data we capture.

So for now, do you think it's okay to release this simple version?  The text is:

"You've recieved feedback: <post title>"

The post title will link the feedback post in the calypso editor.

**Comment by roccotripaldi** [comment]
Nice and simple. Thanks!

**Comment by roccotripaldi** [comment]
I've update the diff. Here are the new screen shots:

<img width="1057" alt="screen shot 2018-08-15 at 10 14 29 pm" src="https://user-images.githubusercontent.com/2694219/44183447-03638000-a0d9-11e8-8481-ca585463a9e4.png">

<img width="1053" alt="screen shot 2018-08-15 at 10 14 58 pm" src="https://user-images.githubusercontent.com/2694219/44183451-06f70700-a0d9-11e8-9f3d-096a827cee43.png">

**Comment by roccotripaldi** [comment]
Added in D17241-code
