### ISSUE TITLE
Gutenberg: Convert to blocks prompt

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#26594]
In this task lets add a prompt to ask folks to convert the post when opening a post made in the Classic editor in Gutenberg. (Gutenberg has this option under the classic block, but we'll want to surface this functionality).

![screen shot 2018-08-09 at 3 47 22 pm](https://user-images.githubusercontent.com/1270189/43929880-9ed7f5a4-9beb-11e8-9be6-24457582da22.png)

Edit: updated summary to note remaining work

**Comment by kwight** [comment]
> We should also provide a similar modal when opening content published from Gutenberg in the classic editor.

Fixed in #28406 .

**Comment by vindl** [comment]
Bumping priority on this because there is no clear solution for https://github.com/Automattic/wp-calypso/issues/29569 yet. This will provide an easier alternative for block conversion at least.
