### ISSUE TITLE
Notifications: don't notify the creator of a new site that they're following their own site

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#26616]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/[ SITE NAME ].wordpress.com.
2. Select Switch Sites and Add New Site at the bottom of the sidebar.
3. Follow the steps to create a new free site.
4. Check your notifications in the top right corner of the window.

#### What I expected
I shouldn't receive any notification.

#### What happened instead
I receive a notification that `[ USER NAME ] followed your blog [ SITE TITLE ]`, where `[ USER NAME ]` is me.

#### Browser / OS version
Chrome MacOS High Sierra

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1647564/43961745-b7b27000-9cad-11e8-9e2d-854f732d41e5.png)

#### Context / Source
#manual-testing

**Comment by seanbashaw** [comment]
I'll fix this issue!
