### ISSUE TITLE
Trampoline: Arrow out of alignment with masterbar on mobile

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#2663]
![bd2da898-bf78-11e5-994a-73f6ba8b5dc9](https://cloud.githubusercontent.com/assets/2846578/12487373/e64b9cc8-c034-11e5-9cb2-7662b166551c.PNG)

We should adjust the spacing to the arrow lines up with the (W) menu item.

**Comment by apeatling** [comment]
I think the top and bottom padding is off too.

**Comment by melchoyce** [comment]
Yeah, all the spacing needs a little tweaking.

**Comment by melchoyce** [comment]
Thinking I'll swap out the arrow position and do this instead:

![trampoline-mobile](https://cloud.githubusercontent.com/assets/2846578/12565676/9fd9798e-c383-11e5-8796-492a01a13043.jpg)

**Comment by apeatling** [comment]
:+1:

**Comment by lancewillett** [comment]
Hi @melchoyce  — looping back on this one, did it get fixed yet?

Is there an easy way to trigger Trampoline on any test site, so it's easy to reproduce stuff like this?

**Comment by melchoyce** [comment]
Not sure — I think @mattwiebe had managed to fix it for the Trampoline v2 we were working on, but now I'm not sure the state of that since Delta works on Guides: Tours. 

You can trigger trampoline by appending `?landing` to your site URL.

**Comment by mattwiebe** [comment]
We ran a test with a new version that had this fixed in it, and it just shipped.
