### ISSUE TITLE
Gutenberg: enable v2 API requests

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#26639]
All of the API requests made from Gutenberg components to v2 API are currently [`noop`-ed here](https://github.com/Automattic/wp-calypso/blob/ba5df58d4d5306c42fbc4b6b1810a77cc41dd270/client/gutenberg/editor/utils.js#L24). In order to make them work with actual API data we need to achieve a couple of things:

- [ ] remove the `noop` middleware and correctly map all of the v2 endpoints to WP.com equivalents (e.g. `/wp/v2/posts` -> `/wp/v2/sites/{siteSlug}/posts`). I already added some [code to handle the mapping](https://github.com/Automattic/wp-calypso/blob/ba5df58d4d5306c42fbc4b6b1810a77cc41dd270/client/gutenberg/editor/utils.js#L31-L37), but we need to verify that there are no other edge cases that need to be mapped separately.
- [x] make authorized API request work. Once you remove the `noop` from above code you'll run into permission error (unauthorized request).

One thing that might be helpful with the above efforts is turning on the debug with `localStorage.setItem( 'debug', 'calypso:gutenberg' );`. This will display all of the currently attempted API calls in the console.

**Comment by gwwar** [comment]
Let's close this one out and make more specific issues for the ones we're running into.
