### ISSUE TITLE
Gutenberg: clean up edit-post folder

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#26642]
In order to get the first version of the Gutenberg shell in Calypso running, we copied most of the `edit-post` folder components. However, some of these like metaboxes and media library are not actually not needed. For most of the others, we are planning to add Calypso specific implementations (sidebar components).

We need to decide which ones from core we want to keep, and remove the obsolete pieces of functionality from `edit-post` folder.

The current decision of the core team is that they are not going to publish `edit-post` as an npm package. We might want to revisit this decision again, or come up with a strategy for maintaining the copied code from Gutenberg master.

**Comment by vindl** [comment]
On hold until https://github.com/WordPress/gutenberg/pull/8958 is merged.

**Comment by mmtr** [comment]
Now that the `@wordpress/edit-post` package is published we can probably import everything from it.

**Comment by vindl** [comment]
> Now that the @wordpress/edit-post package is published we can probably import everything from it.

Started a PR to handle this: #28095.
