### ISSUE TITLE
Gutenberg: fix styling issues

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#26641]
Currently, if you navigate to `/gutenberg/post/{siteSlug}` you'll notice that the styling is broken for most of the editor components and blocks. This could be caused either by missing CSS for imported components, failure to import all of the relevant styles, or style collisions with Calypso.

Related post: p7jreA-1JV-p2.

**Comment by aduth** [comment]
FWIW, all components offered by `@wordpress/components` should ideally work entirely standalone, not assuming any inherited styles from WordPress itself. If you find this to not be true, we should fix within Gutenberg.

**Comment by vindl** [comment]
@aduth I think that we've imported all of the package styles to Calypso at this point. You can see the results of that here: https://wpcalypso.wordpress.com/gutenberg. Judging by the looks of it, there are some missing inherited styles from WordPress. We'll investigate further and start filing issues in the core repo, and hopefully some fixes too.
