### ISSUE TITLE
Confusing Message in Purchases when Renewing Domains

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#26664]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Click on a domain purchase

#### Actual Message

The message that comes up is confusing. It says "Replaces your site's free address with the domain SITE.wordpress.com, making it easier to remember and easier to share." I noticed this while exploring Purchases.

 #### Expected message
Something linke: Replaces your site's free address damiannepatomicsite9383.wordpress.com with the domain, making it easier to remember and easier to share.

#### Screenshot / Video
<img width="737" alt="domain registration message" src="https://user-images.githubusercontent.com/30090682/44038292-c5e3f8c2-9f16-11e8-9382-5244ffa0b308.png">

#### Context / Source
<!-- Optional: share your unique context to help us understand your perspective. You can add context tags such as: #journey #anecdote #narrative #context #empathy #perspective #reallife #dogfooding #livesharing #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

**Comment by arunsathiya** [comment]
Great catch. I checked an order on my https://wordpress.com/me/purchases page as well, and this definitely needs to be changed.
