### ISSUE TITLE
Not being able to toggle between sites in an account, after a site was deleted

### ISSUE THREAD

**Issue by adamleone** [Automattic/wp-calypso#26667]
#### Steps to reproduce
1. Starting at URL: wordpress.com 
2. Login as user sharonecolemanspen
3. Hit "My Sites" 
4. Nothing happens, can not toggle between sites 

#### What I expected

After hitting my sites, I was expecting to see the usual list of sites in the account and move between sites as you would normally. I wanted to then navigate to the domain panel for the site sharonecoleman.com to check the status of a domain transfer but was unable to. 

#### What happened instead

Nothing happens, can keep clicking but there's no list appearing. 

#### Screenshot / Video

http://cld.wthms.co/4v1NLP

#### Context / Source

I found the bug by using the WordPress.com as to what you normally would. The user had a site previously that was deleted. This was created first at some point, before the site that's having the domain transferred to it. 

1344893-zen

**Comment by rachelmcr** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/Automattic/wp-calypso/issues/24539 (scenario 2 in that issue). The domain was previously used with a Jetpack connection, and that inactive Jetpack connection is the primary site on the account.

Changing the primary site on the account should resolve it. If that doesn't work, or you find this is a different underlying problem, please comment and we can reopen this issue.
