### ISSUE TITLE
Guided Tours: Confusing Flow for Featured Image when Publishing First Post

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#26686]
#### Steps to reproduce
1. With a new site, starting at URL: https://wordpress.com/checklist/{site}
1. Click on "Publish your first blog post" in the checklist
1. You should be on the editor page for the default blog post, with a guided tour prompt to edit the post content
1. Edit the post content, then click "All done, continue" on the guided tour prompt
1. You should now see a guided tour prompt about Categories and Tags
1. Click "All done, continue" on the guided tour prompt

#### What I expected

1. Guidance to open the Featured Image section in the sidebar to set a featured image

#### What happened instead

1. The next guided tour prompt shows in the top left of the screen and tell me to "pick an image below..." even though no images are visible.

#### Browser / OS version

Chrome / macOS

#### Screenshot / Video

Publish First Blog Post Checklist Item

<img width="1309" alt="04a publish post item" src="https://user-images.githubusercontent.com/1699996/44097224-e947dc8e-9fa2-11e8-94e1-597923ca3207.png">

Edit Post Content

<img width="1309" alt="04b copy" src="https://user-images.githubusercontent.com/1699996/44097265-f71e59dc-9fa2-11e8-9e40-3e4d6e003036.png">

Edit Post Categories

<img width="1309" alt="04c categories" src="https://user-images.githubusercontent.com/1699996/44097280-006bae22-9fa3-11e8-9691-a66eb4ce7775.png">

Featured Image Prompt

<img width="1309" alt="04d featured images" src="https://user-images.githubusercontent.com/1699996/44097292-064e0c9a-9fa3-11e8-9576-95493af6c448.png">

All Steps

![04e stuck on featured image](https://user-images.githubusercontent.com/1699996/44097318-1651020a-9fa3-11e8-9914-c74c0ba465bd.gif)

#### Context / Source

#manual-testing

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by rachelmcr** [comment]
I confirmed the issue as described above. This is a change from a couple weeks ago when the featured image step didn't appear at all in this guided tour (see https://github.com/Automattic/wp-calypso/issues/26443).

@jsnajdr I see you've been working recently on guided tours; is this a tour you're familiar with?
