### ISSUE TITLE
Domains: Missing suggestions & error message for some domain names

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#26682]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/<yourwebsite> (My Site -> Domain -> Add)
2. Enter `wordpress-ninja.com`, or one of the shorter failing domains mentioned below
3. Notice that there is no error message, and no suggestions. You may notice that the trademark error message flashes for a moment before disappearing.
4. Contrast with minor variations, like `wwordpress-ninja.com` or `wordpress-ninjaa.com` that show both error message and suggestions

#### Browser / OS version
Chrome/OSX

#### Screenshot / Video

![domain_search_ _site_title_ _wordpress_com](https://user-images.githubusercontent.com/5952255/44085746-c4520d72-9ffd-11e8-8e65-94dbbed7ff9f.jpg)

![cursor_and_domain_search_ _site_title_ _wordpress_com](https://user-images.githubusercontent.com/5952255/44086367-a690d488-9fff-11e8-8a48-1ec0f00b0b85.jpg)

#### Context / Source

I think this is about the hyphen somehow fouling up the suggestions. I've fiddled about a bit trying to get simpler failure cases, and I was able to find `ninja-`/`-ninja`, `-co`/`co-`, and `ass-`/`-ass`

Notably, `ninja-.com` & `ninja-.co` fail, but `ninja-.c` works. Also, `n-`, `ni-`, `nin-` and `ninj-` all work fine, `ninja-` and `ninjas-` both fail, but `ninjaa-` is ok.

When the message and suggestions disappear, we get an error back from the `suggestions` endpoint: `{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"empty_results","message":"No available domains for that search."}}`

I think we're filtering out the trademarked term and the tld, and then if we're left with a hypen at the beginning or end, some words will cause an error in our suggestions code.

**Comment by aidvu** [comment]
Thank you @corinnekrych. We were all on a company meetup last week, but will have time to look at this soon.
