### ISSUE TITLE
Posts: Remove view counts from blog posts list as they consume excessive network and database resources

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#26708]
The view counts from the blog posts list result in a single `/stats/post` network request for each post in the list, as well as multiple SQL queries on the backend for each `/stats/post` request. This is highly inefficient and not acceptable performance both for customers' devices as well as our servers.

The "X Views" counts will be removed from posts in the blog posts list. It may return in some fashion in the future should customer needs require it and it can be implemented in an efficient manner.

Before:

<img width="738" alt="screencapture at wed aug 15 13 21 39 edt 2018" src="https://user-images.githubusercontent.com/2098816/44163020-169e2d80-a090-11e8-9160-5b98596b09c1.png">

After:

<img width="736" alt="screencapture at wed aug 15 13 22 45 edt 2018" src="https://user-images.githubusercontent.com/2098816/44163026-1b62e180-a090-11e8-9378-79271c20464e.png">

See internal discussion for more details: p8F9tW-RX-p2 

----

### Acceptance critieria

1.
- Given a site with blog posts with views
- When Blog Posts is visited
- Then the "X Views" counts are not present on the post items in the list

2.
- Given a site with blog posts with views
- When Blog Posts is visited
- Then no `/stats/post` requests are made for individual posts

3.
- Given a customer with multiple sites with blog posts with views
- When Blog Posts is visited in All My Sites mode
- Then the "X Views" counts are not present on the post items in the list

4.
- Given a customer with multiple sites with blog posts with views
- When Blog Posts is visited in All My Sites mode
- Then no `/stats/post` requests are made for individual posts

**Comment by carladoria** [comment]
Just mentioning here that user in [3676429-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=3676429) would like to see this feature back

**Comment by arunsathiya** [comment]
5740736-hc: Noting that this user wanted to see the same back as well.

**Comment by BandonRandon** [comment]
forum post: https://en.forums.wordpress.com/topic/views-57/

**Comment by danjjohnson** [comment]
Another complaint about this in 1350057-zen

**Comment by aamills** [comment]
#5746530-hc - User will miss the feature but "I will survive LOL"

Were mostly relieved to know that it wasn't something they had accidentally turned off.

**Comment by galakhyati** [comment]
Another user mentioned about missing it: #5120254-hc

**Comment by deancroyal** [comment]
Another user misses this feature: #1360165-hc

**Comment by sarahfg** [comment]
Another user missing this feature #1895467-HC

**Comment by Robertght** [comment]
Asked about this: #1363353-zen

**Comment by Robertght** [comment]
#4022551-hc

**Comment by sashastone** [comment]
Another user who would like to see this feature come back #1364730-zen

**Comment by sophiegyo** [comment]
#1364857-hc - another request for views to stay

**Comment by nielslange** [comment]
Another one in #1066876-hc

**Comment by samiff** [comment]
#2427209-hc would like to see it back.

**Comment by mattsherman** [comment]
#26894 has been opened up to track the potential re-introduction of this functionality.

**Comment by jaymendoza** [comment]
#6005018-hc is upset about this having been removed and would like to have it back.

> I'm upset they've removed this. Now I do not know how many people are viewing my blogs. As I said before, it's very time consuming and cumbersome to have to click on the three dots, and et cetera et cetera -- and even after counting all the numbers up, I see they only go to a certain extent -- they don't show all the hits each of my blogs has gotten.

**Comment by samiff** [comment]
#6032838-hc wants it back

**Comment by wprhunt** [comment]
Yep. Also have another customer with the same:
#2255431-hc
I agree it's better to not have this cause the dashboard to be impacted so much, so maybe if we can look into at least allowing customers to just filter by posts instead of Posts & Pages in the Stats section of the Dashboard would be a good alternative.
Customers just want an easy way to see total views at a glance somewhere.

**Comment by BandonRandon** [comment]
One thing that has come up in the forums a few times is the question about why the "like" count is still shown but the "views" count is gone. 

@jmdodd  mentioned to me that this was because we store the like count in the same table as the post data (at least I think that's what was said).

From a user/UX experience I can see how this could be confusing when one count is removed but the other remains. It did give me an idea though, I'm not sure how technically plausible this is because I know adding new columns in the DB is a bit of task but would storing a cached number of views in the database work here?

**Comment by jmdodd** [comment]
To clarify, like data is not stored alongside post data, but is stored in a more query-friendly manner than stats because we never break them out over days.

**Comment by michaeldcain** [comment]
In #27090, we introduced a new "Recent Views" glance that shows a post's views in the last 30 days (if they have any) and links to the post's full stats page.
