### ISSUE TITLE
Login: Log-in page with message "Also available in English" doesn't switch language (requires refresh)

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#26702]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in/nl?redirect_to=https%3A%2F%2Fwordpress.com%2F with browser locale set to English
2. Click "Also available in English"

#### What I expected

Page displayed in English

#### What happened instead

Page still displays Dutch, however banner is not shown. Clicking refresh shows English.

#### Browser / OS version

Chrome, Safari on macOS

#### Screenshot / Video

![also available in](https://user-images.githubusercontent.com/128826/44143767-3e244232-a085-11e8-8487-65301d65edcc.gif)

#### Context / Source
#dogfooding

**Comment by ramonjd** [comment]
While #27869 achieved a minor janitorial victory, I don't think it solved this issue. I can't yet work out why it works on all environments _except_ production. Sorry, I'll keep tinkering.
