### ISSUE TITLE
People: change update notice for roles to an ephemeral notice

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2671]
Raised by @kriskarkoski 

Steps to reproduce:
1. Go to https://wordpress.com/people/team and select a blog if prompted
2. Click on a user
3. Make a role change
4. Click Save changes
5. Click Back

<strong>Result:</strong> the notice currently persists across all People Management screens: 

<img width="698" alt="screen shot 2015-10-16 at 5 09 58 pm" src="https://cloud.githubusercontent.com/assets/1900444/10555208/e01c147a-7428-11e5-873c-1a7846f4ed2d.png">

<img width="984" alt="screen shot 2015-10-16 at 5 08 42 pm" src="https://cloud.githubusercontent.com/assets/1900444/10555207/e01ab44a-7428-11e5-9ded-5dfe46bc5859.png">

Comment from @rickybanister 

> This is a perfect opportunity to display an ephemeral notice. It would appear and fade out after some amount of time (10s or so). Especially for a success message or an action that the user confirmed (removing a user). They want to know it was successful, but they don't want to have to click the X to make it go away. They definitely don't want the height of their page to jump around as things appear/disappear. 
> 
> So when the work begins, we can swap this for one of these:
> 
> <img width="711" alt="screen shot 2015-10-28 at 11 05 31 am" src="https://cloud.githubusercontent.com/assets/437258/10792634/d871972e-7d63-11e5-8175-e4f7005fc18e.png">

WIP https://github.com/Automattic/wp-calypso/pull/2413

**Comment by lancewillett** [comment]
This one is still happening — was able to reproduce exactly with steps above, using Mac-n-Chrome.
