### ISSUE TITLE
People: make the remove follower AYS message more specific

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2672]
Steps to reproduce:

1. Go to https://wordpress.com/people/followers
1. Click "Remove" next to one of the followers

<strong>Result:</strong> the warning notice that appears when you try to remove a follower may give some people a false sense of privacy: 

![screen shot 2016-01-21 at thu jan 21 2 38 14 pm](https://cloud.githubusercontent.com/assets/1119271/12492131/d5135a5a-c04c-11e5-9205-17ca8df6ba97.png)

A small wording change could in that message could help make it more clear that a remove is not the same as blocking:

> If you remove this follower, he or she will stop receiving notifications about this site unless they re-follow.
> 
> Would you still like to remove this follower?

/hat tip +horizonfeedback [#comment-152](https://horizonfeedback.wordpress.com/2015/10/14/call-for-testing-people-management/comment-page-1/#comment-152)

**Comment by BandonRandon** [comment]
I just saw this message and am wondering if we should remove "he or she". Instead how about changing this to read "they" or "the follower"
>  If you remove this follower, they will stop receiving notifications about this site unless they re-follow.
> Would you still like to remove this follower?

>  If you remove this follower, notifications will no longer be sent about this site unless they re-follow.
> Would you still like to remove this follower?

Or anything else that removes binary language from the message.

**Comment by BandonRandon** [comment]
Closing, fixed in #3120
