### ISSUE TITLE
Checklists: Jetpack checklists flash before redirect

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#26737]
Before redirecting Jetpack checklists, there may be a visible flash at `/checklist/JP_SITE`

**Comment by sirreal** [comment]
Let's wait for #26734

**Comment by simison** [comment]
This can prolly be closed? 😀

**Comment by sirreal** [comment]
I believe this was fixed by https://github.com/Automattic/wp-calypso/pull/33734 which redirects without rendering content.
