### ISSUE TITLE
Components: Remove unused `UpgradeNudgeExpanded` component

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#26745]
Currently we have the following related to upgrade nudges:

1. `UpgradeNudge` component in `client/my-sites/upgrade-nudge/`, used throughout the WordPress.com admin.

2. `UpgradeNudgeExpanded` component in `client/blocks/upgrade-nudge-expanded` that's no longer used (it tested poorly and it's use was removed in #8403, but the component remains)

3. In `client/devdocs/design/blocks`, the `UpgradeNudge` component is displayed, but it links to the readme for `UpgradeNudgeExpanded` from `client/blocks/upgrade-nudge-expanded`.

Suggested actions:

1. Re-purpose  the `UpgradeNudgeExpanded` readme for the `UpgradeNudge` component that's actually in use.
    a. Revise to apply to `UpgradeNudge`
    b. Move readme to `client/my-sites/upgrade-nudge/`
1. Delete the unused `UpgradeNudgeExpanded` component and related files.

**Comment by mirrory** [comment]
I'd like to work on this one.

**Comment by creativecoder** [comment]
@mirrory Go for it! Let me know if you have any questions.

**Comment by mirrory** [comment]
Okay, pull request #27202 is ready for review. :smile:

**Comment by creativecoder** [comment]
Resolved by https://github.com/Automattic/wp-calypso/pull/27202
