### ISSUE TITLE
UpgradeNudge: Update feature prop values to use plan constants rather than strings

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#26746]
I'd guess that feature strings need to be updated in several places to use constants from `client/lib/plans/constants` instead, but here are a few places I noticed recently when working with the `UpgradeNudge` component.

1. `client/my-sites/post-type-list/index.jsx:232` (`no-adverts`)
1. `client/my-sites/post-type-list/index.jsx:82` (`no-adverts`)
1. `client/my-sites/stats/stats-module/index.jsx:192 (`google-analytics`)
1. `client/my-sites/upgrade-nudge/docs/example.jsx:19` (`custom-domain`)

Update these to use feature constants from `client/lib/plans/constants`.

**Comment by rfaile313** [comment]
@creativecoder I'm going to take a look at this if that's alright 😄
