### ISSUE TITLE
Reader: Featured image not appearing in full post view

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#2676]
In stream:
![screenshot](https://cldup.com/pDXThExj7E.png)

FPV
![screenshot](https://cldup.com/KnOZlLqpCR.png)

from https://wordpress.com/discover?at=2016-01-21T14:02-05:00 and https://wordpress.com/read/post/id/53424024/5508

**Comment by bluefuton** [comment]
This particular image isn't showing up because it's 500px wide, and the minimum width for a featured image is 620px.

**Comment by blowery** [comment]
Right, that's the problem. The feature size for a full post is bigger than for the stream. They should be the same (and match the stream).

**Comment by bluefuton** [comment]
Plan of action:
- split `getFeaturedSize`, `featuredImageComponent` and `updateFeatureSize` out of `Post` component and into a helper; use helper in full post view too
- create stateless components for <FeaturedImage />` and `<FeaturedEmbed />`
