### ISSUE TITLE
Medium import throws 504 status code error

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#26769]
#### Steps to reproduce
1. URL: https://importtest404462790.wordpress.com
2. I was importing exported .zip file (not attaching the zip file here for security reasons but I can share)
from Medium to that ^ free WorsPress.com site from My Site -> Setting -> Import: Medium. This is `1346969-zd-woothemes`
3. Uploaded the zip file and it started running the import.

#### What I expected

I expected it to import the content without any error message. 

#### What happened instead

It threw this error message.
![screen shot on 2018-08-19 at 13_37_49](https://user-images.githubusercontent.com/16509219/44307014-7e1deb00-a3b8-11e8-96b9-3e44204ba02b.png)

#### Browser / OS version

Safari 11.1.2 / Mac High Sierra Version 10.13.6

#### Screenshot / Video

Screenshot added above

**Comment by rachelmcr** [comment]
Thanks for the report! I found a number of previous reports of the same error:
* p1527319331000070-slack-calypso
* p1498083337873210-slack-livechat
* p1502309466704887-slack-tickets
* p2UL9c-3kD-p2

It seems that a large number of posts and/or media can cause this error, and one workaround is to split the Medium export .zip file into two or more .zip files, which can then be imported separately. @nerdysandy if this came from a user report can you try that workaround?

**Comment by nerdysandy** [comment]
@rachelmcr I tried importing by splitting the file but it still threw the same error :(
