### ISSUE TITLE
Reader: Keyboard overlaps comment field on Nexus 5

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#2677]
#2667 added a nice auto-expand for comments, but there's one lingering problem: On the Nexus 5, the keyboard totally overlaps the textarea when it appears. Scrolling and typing seems to work, but it's not a great UX.

See if there's anything we can do about it.

**Comment by bluefuton** [comment]
This suggests that it's a bug, and can be worked around with `Element.scrollIntoViewIfNeeded()`:

http://stackoverflow.com/a/25032766

Not keen on the browser agent sniff though.

**Comment by bluefuton** [comment]
There's an issue in the Chrome for Android bug tracker for this that has been open since 2013:

https://bugs.chromium.org/p/chromium/issues/detail?id=270018&can=4&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified
