### ISSUE TITLE
Activity Log: Make "Feedback received" icon green

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#26785]
Change color of the gridicon container in the AL event timeline below the timestamp to green instead of grey.

<img width="780" alt="screen shot 2018-08-20 at 4 27 43 pm" src="https://user-images.githubusercontent.com/204742/44370109-045c2f00-a496-11e8-8b8e-26d1ab34c1db.png">

**Comment by gititon** [comment]
Done. D17469-code
