### ISSUE TITLE
Activity Log: Attribute pingbacks to WP actor

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#26781]
Change actor of pingbacks to WP instead of System Admin.

<img width="1093" alt="screen shot 2018-08-20 at 12 25 05 pm" src="https://user-images.githubusercontent.com/204742/44363221-cdc7e980-a480-11e8-9668-d9d036e79acd.png">

**Comment by roccotripaldi** [comment]
D17630-code
