### ISSUE TITLE
Reader: handle mixed RTL and LTR posts

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#268]
A user can use WordPress.com in an RTL language (e.g. Hebrew), but follow blogs in multiple locales. The reader stream is then RTL aligned for all posts, regardless of the post locale:

![mixed-rtl-ltr-reader](https://cloud.githubusercontent.com/assets/8658164/11302731/ff11a2b2-8f96-11e5-85b5-eeb0c0ebe7ad.png)

The opposite is also true of users who use WordPress.com in an LTR language (e.g. English) but follow blogs in RTL locales. In that case, the reader stream is LTR aligned for all posts.

A relatively easy improvement would be to add the html `dir` attribute to all post titles and content block elements. This means the browser will determine the direction based on the first relevant character in the text.

However, we'd run into design issues if we do that, for examples with margins and the excerpt fade out:

![mixed-rtl-ltr-reader-2](https://cloud.githubusercontent.com/assets/8658164/11302745/0f189e4a-8f97-11e5-94a0-be5002b87ff3.png)

![mixed-ltr-rtl-reader-3](https://cloud.githubusercontent.com/assets/8658164/11302749/140ab0b4-8f97-11e5-8c9e-84e61e0bdf9d.png)

To better solve this, the reader should be locale aware, and by extension - text direction aware. We can already do that with posts from WordPress.com (`site` has a locale property) but we also need a way to do that with external feeds directly.

We have locale detection capability in ES so we should plug that in.

Example of a reader that does it well (Feedly):

![mixed-ltr-rtl-feedly](https://cloud.githubusercontent.com/assets/8658164/11302804/54e860fe-8f97-11e5-88dc-197183f3f43b.png)

This is an issue for anyone whose interface language does not match the direction of all the blogs they follow (either because they read a mix of RTL and LTR blogs, or because they prefer to use WordPress.com in a different language from the blogs they follow). We don't have data on how many users this affects, but it is likely very common to read e.g. both Hebrew and English blogs.

cc @yoavf for the original report

**Comment by blowery** [comment]
#9664 is a first step towards fixing this
