### ISSUE TITLE
Store: Dashboard inventory alerts show scrollbars

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#26805]
There appears to be a design issue on the store dashboard. Inventory alerts are showing ugly scrollbars.

#### Steps to reproduce

This appears on the store dashboard when the setup checklist is complete and dismissed.

#### Browser / OS version

Google Chrome Version `68.0.3440.106` (Official Build) (64-bit)
macOS `10.13.6`

#### Screenshot / Video

<img width="396" alt="scrollbars" src="https://user-images.githubusercontent.com/841763/44412334-a92e4900-a536-11e8-809f-7de23333fcaf.png">

**Comment by timmyc** [comment]
Thanks for the report @sirreal and for your continued improvements to the check list component!
