### ISSUE TITLE
In D17401, I normalized attachment title and filename to ensure title does not appear in AL if it is the "same" as the filename.

### ISSUE THREAD

**Issue by gititon** [Automattic/wp-calypso#26806]
In D17401, I normalized attachment title and filename to ensure title does not appear in AL if it is the "same" as the filename.

**Comment by gititon** [comment]
D17401-code

**Comment by rachelmcr** [comment]
@gititon it looks like this is complete; is it ok to close this issue?

**Comment by gititon** [comment]
Thanks, @rachelmcr, I meant to close this.
