### ISSUE TITLE
Integration tests fail in wp-calypso-bootstrap env

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#26811]
While testing https://github.com/Automattic/wp-calypso/pull/26747 @westi found that calling `npm run test-integration` fails in the [wp-calypso-bootstrap](https://github.com/Automattic/wp-calypso-bootstrap) vagrant environment.

```
 FAIL  server/devdocs/integration/index.js
  ● devdocs › should not allow viewing files outside the Calypso repo

    EACCES: permission denied, open '/var/outside-calypso.md'

      123 | 			'outside-calypso.md'
      124 | 		);
    > 125 | 		fs.writeFileSync( pathOutsideCalypso, 'oh no' );
          | 		   ^
      126 | 		getDocument( '../outside-calypso.md', ( err, res ) => {
      127 | 			fs.unlinkSync( pathOutsideCalypso );
      128 | 			expect( err ).not.toBeNull();

      at Object.writeFileSync (server/devdocs/integration/index.js:125:6)
```

The devdocs tests assumes some things about the file environment which may not be true. We could update the test to be more robust and perhaps test this platform independent temporary folder selection.

cc @gziolo

**Comment by gziolo** [comment]
https://github.com/Automattic/wp-calypso/blob/a20f92fcfdba004e73ab725867b25733b7578de3/server/devdocs/integration/index.js#L117-L123

I think this is all correct, this thing tries to write outside of the Calypso repository. You probably should update to use temporary folder to ensure there are no permission issues.
