### ISSUE TITLE
Editor: lose focus on editor during auto-save

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#2682]
If a meta box, like tags, is expanded, upon auto-save, focus on editor is lost and placed in side bar meta box instead.

Repro:
- Write in post body/editor in a draft
- expand tags/categories meta box
- click into tags input to select
- click back into editor
- notice that tags/categories meta is still in selected state: https://cloudup.com/cM0lpaYLzwZ
- type in body
- allow for autosave to initiate and continue typing
- notice that auto-save causes a loss of focus on editor
- focus is returned to meta box

video: https://cloudup.com/cJDQmZ-nQ4q

**Comment by lancewillett** [comment]
Tested to reproduce today, happy to say it's no longer happening. Using Mac-n-Chrome with a test site.

![autosave](https://cloud.githubusercontent.com/assets/66797/14370769/df599c2e-fce5-11e5-840a-5787582b06dd.gif)

**Comment by meremagee** [comment]
This has not yet been resolved. Notice that if you don't deliberately click away from the tag/category dropdown _in the sidebar_ to escape focus on the input, it will still grab the input upon save: 

https://cloudup.com/cxp2bBLk2PX

**Comment by marekhrabe** [comment]
I did everything as in the video and I wasn't able to confirm on current master (06c8c74ee17a555c5b9225e1a3c197375509e37f) and on Wordpress.com

Is it still happening?

**Comment by marekhrabe** [comment]
I was finally able to reproduce the issue now. It works like that only in Firefox. Here is a gif:

![firefox-tag-focus](https://cloud.githubusercontent.com/assets/156676/16205636/fbef0454-3724-11e6-82a5-4bf1f9ad1b16.gif)

My assumption is that auto-saving a post has nothing to do with that problem (at least not directly). The tag input just won't give up the focus and it will take it back on next component update. Either triggered by auto-save or just typing anything in other fields (strangely, typing in body worked correctly for me, but typing in the post title did the action @meremagee described)

**Comment by meremagee** [comment]
Note that auto-save is what appears to re-focus my cursor on the meta boxes while I'm in the body of the post on FF: (video from today) https://cloudup.com/iy11W3camws

**Comment by nylen** [comment]
@meremagee this is fixed in our testing, would you mind re-checking to confirm?
