### ISSUE TITLE
Activity Log: post update | publish are being double tracked by Gutenberg

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26849]
Currently, when a post is published or updated using the Gutenberg editor, two events show up in the activity log. This is because the 'berg triggers 2 events, one in wp-admin and one in WP REST.

We can likely address this on the sync server.

We discovered this issue while working on D17485-code

**Comment by roccotripaldi** [comment]
closed in 
D18306-code
and in https://github.com/Automattic/jetpack/pull/10130

**Comment by cecoates** [comment]
I have a user that is affected by something similar:

1658268-hc
1414907-zen

This user was creating a post on their iPad. At some point, I'm unclear if they published a change accidentally or the draft was saved at the wrong time, they lost a significant amount of work they had put into the post.

There's an early version, with a small amount of content, and a newer revision with almost no content. Everything in between is gone.

The activity log shows quite a few changes/breadcrumbs that aren't reflected in either post revision (post #339,  My Chic (and First) Makeup Tutorial!). The user is frustrated that even though many changes seem to have been tracked in the AL, they can't "restore" those changes.

The revisions are missing in both the app and the web. So it's no longer, let's say, saved locally on the app on their iPad.

**Comment by roccotripaldi** [comment]
@cecoates - i'd would say this issue is closer to what you are looking for:
https://github.com/Automattic/wp-calypso/issues/20265

There is a fix in progress.

**Comment by roccotripaldi** [comment]
I created a new issue for linking activity log entries to their respective revision: 
https://github.com/Automattic/wp-calypso/issues/27204
