### ISSUE TITLE
Checklist: View your checklist link broken for Jetpack site

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#26870]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/eric.blog
2. Click "View your checklist" in checklist banner
3. Land on https://wordpress.com/checklist/eric.blog and observe "Checklist not available for this site"

#### What I expected

For the "View your checklist" link to work

OR

To not see the banner since my site is old and has a name and description.

#### What happened instead

The opposite of that.

#### Browser / OS version

Chrome Version 68.0.3440.106 (Official Build) (64-bit) on Mac

#### Screenshot / Video

<img width="1434" alt="screen shot 2018-08-24 at 8 33 38 am" src="https://user-images.githubusercontent.com/1126811/44587660-3cef5780-a779-11e8-86e5-8a4b2163b282.png">

<img width="1434" alt="screen shot 2018-08-24 at 8 33 40 am" src="https://user-images.githubusercontent.com/1126811/44587673-424ca200-a779-11e8-8d54-b8e27ae7a24c.png">

**Comment by dougaitken** [comment]
FWIW, all my WordPress.com sites I've tried are at 57% (site icon, tagline, personalize contact page still unchecked) even though most of them are at 100%.

**Comment by xpurichan** [comment]
New identical report on Zen-1368880

**Comment by mlaetitia** [comment]
New report from a user hc-3055014
Also duplicated on my AT site.

**Comment by rachelmcr** [comment]
cc @taggon

**Comment by chaselivingston** [comment]
Also reported in 5791418-hc

**Comment by michaeldcain** [comment]
cc @Automattic/marketing-dev

**Comment by dougaitken** [comment]
Chatter in Slack p1535119883000100-slack-C2D7KQKU7

Would it be useful to split this and have a separate issue for WordPress.com sites?
