### ISSUE TITLE
Sidebar: add ability to hide sidebar items

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#26887]
_Note: this is an enhancement suggestion - just looking for thoughts and feedback about the idea._

This issue proposes that we add an "edit" mode to allow users to hide items in their sidebar.

Current "My Sites" Sidebar | Concept "Edit" Mode
------------ | -------------
![sidebar](https://user-images.githubusercontent.com/942359/44596974-1989d400-a79c-11e8-9569-9158ed821073.jpg) | ![mock-sidebar-settings](https://user-images.githubusercontent.com/942359/44596977-1ee71e80-a79c-11e8-95ed-2684d0c0d0e9.jpg)

Currently, the "My Sites" sidebar for a Simple Site can be rather full with a number of sidebar item variations, based on plan, custom post types active, age of account, etc. Depending on the focus of the site and the experience of the user, many of these things may not be needed (i.e. a site that has been around for a while probably doesn’t need the “Import” item, an SMB user might not need the “Blog Posts” item, or a blogger might not need the “Portfolio” or “Testimonial” items even though their theme declares the CPT support).

While researching the status of the `NestedSidebar` project, we tossed around the idea of allowing the user to hide items in the sidebar - similar to the list edit mode on mobile devices. This would allow users to selectively see only the features they need and simplify their sidebar if desired. 

It would also provide the infrastructure  to show/hide sidebar items based on flow-defined needs (onboarding flows, user experience, etc.).

The general idea would be a single gear icon in the sidebar, that when clicked, would enter an “edit” mode and add a toggle beside each sidebar item that can be hidden (hiding the actions buttons for each item). Some items would always be shown (i.e. View Site, Plan, Settings), but other items would be shown/hidden based on a per-user, per-site setting. In edit mode, hidden items would simply be greyed-out.

Reordering of items would not be allowed. Just show/hide.

**Comment by creativecoder** [comment]
@michaeldcain What do you think of closing this one, as the new collapsible sidebar serves a similar need?
