### ISSUE TITLE
Checklist is unable to be completed for Simple Sites

### ISSUE THREAD

**Issue by dougaitken** [Automattic/wp-calypso#26890]
#### Steps to reproduce
1. Starting at URL: `https://wordpress.com/stats/day/doug.blog`
2. Note the Checklist, "update site icon"
3. Pressing "do it" and then return to checklist doesn't complete the item
4. Rechoosing the same image from my media library following the prompts it shows complete
5. Click link to Checklist - checkbox didn't show complete
6. Refresh page, Site Icon is check and moved position in the list
7. Update site tagline. Not all themes use a tagline and I don't use one for my site. I cannot bypass this

#### What I expected

To be able to bypass steps I had already completed. 

#### What happened instead

I was unable to bypass any steps I had already complete.

My URL changed to my site ID after going through any part of the checklist. i.e. it no longer showed `https://wordpress.com/stats/day/doug.blog` but `https://wordpress.com/stats/day/[site_id]`

I "tricked" the flow by putting in a temporary tagline, saving, then going back, deleting it, and saving the page again. The checklist remained complete. 
I haven't been able to check the final list item (Customize Contact page) at all. 

#### Browser / OS version

Chrome `Version 68.0.3440.106 (Official Build) (64-bit)`
macOS `10.13.6 (17G65)`

#### Context / Source

Context - was testing out #26870

**Comment by rossanafmenezes** [comment]
I Had two issues today regarding this:

https://woothemes.zendesk.com/agent/tickets/1368907

and 

https://mc.a8c.com/support-stats/happychat/transcript.php?id=5740497

**Comment by sirreal** [comment]
I've just followed the steps in the tour to update the site icon and it _did_ work.

However, it initially reported the task as incomplete. This may simply be the server taking some time to update the checklist task status. We return to the checklist and query the data before the server is updated, so the client gets stale data and is incorrectly shown the just completed step.

**Comment by mattwiebe** [comment]
Older sites would not have had their checklist properly initialized which meant that nothing would get checked off properly. I believe that completing an item manually would have done the initialization and therefore the list would have started working as expected, but simply following the Guided Tour steps would not have. Now that #26867 has landed, older sites will simply not see the checklist. We'll have to figure out that initialization logic should we wish to deploy the checklist to them, too.
