### ISSUE TITLE
Activity Log: existing image attached to a post

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26906]
To reproduce:
1. go to your media library and add a new image
2. start a new post
3. attach the image you added in step 1 to the post
4. publish

<img width="923" alt="screen shot 2018-08-24 at 6 44 45 pm" src="https://user-images.githubusercontent.com/2694219/44611191-d0527800-a7cd-11e8-9906-01f688d8a3c2.png">

Note the "Image updated" event. That should instead be an "image attached to post" event

**Comment by roccotripaldi** [comment]
Let's see if we can use meta for this.

**Comment by gititon** [comment]
Done D18015-code, D18003-code, and https://github.com/Automattic/jetpack/pull/10096
