### ISSUE TITLE
Activity Log: new attachments in calypso are being logged as unattached

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#26908]
To reproduce:

1. Go to calypso and select a jetpack site
2. Start a new post
3. Upload and insert a new image into the post
4. Publish

Note the "image upload" event:

<img width="923" alt="screen shot 2018-08-24 at 6 55 13 pm" src="https://user-images.githubusercontent.com/2694219/44611473-4acfc780-a7cf-11e8-9c4a-424bb558c188.png">

This should instead be an "image attached" event like this:

<img width="932" alt="screen shot 2018-08-24 at 6 58 27 pm" src="https://user-images.githubusercontent.com/2694219/44611559-b6b23000-a7cf-11e8-9928-3f90168e4d98.png">

Note: this is not happening in wp-admin for jetpack sites. Nor is it happening for .com sites at all.

**Comment by roccotripaldi** [comment]
closing as a dupe of https://github.com/Automattic/wp-calypso/issues/26906

**Comment by roccotripaldi** [comment]
We'll need to fix the api to include the parent id at the time of upload.

**Comment by formosattic** [comment]
Added to triage board for another review by @Automattic/dotcom-triage-pa-group .
We could consider merging https://github.com/Automattic/wp-calypso/issues/44427 to this one?

**Comment by Greatdane** [comment]
Definitely related, but unsure if fixing https://github.com/Automattic/wp-calypso/issues/44427 will also fix this. Keeping it open but we probably need to wait for https://github.com/Automattic/wp-calypso/issues/44427 to be fixed we can fully triage this.

**Comment by p-jackson** [comment]
Confirmed that Automattic/wp-calypso#44427 is the underlying issue here. Closing this issue in favour of Automattic/wp-calypso#44427 because it's a bug in WPCOM, not anything wrong with Jetpack.
