### ISSUE TITLE
Gutenberg: Edit an existing post made by the Calypso Editor without mangling content

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#26909]
When we load a post made by the classic Calypso Editor, does the content look okay?

For example, do we see unexpected content transformations from simply loading post content without user updates?

Please mind the mobile if we'd like to make changes to saved Calypso post content. (Mobile editors maintain some special transforms on the native client apps).

For more context see:
https://github.com/WordPress/gutenberg/issues/3900
p9ugOq-6P-p2

**Comment by vindl** [comment]
I believe this was resolved by the introduction of Classic block and content transformation related backend fixes.
