### ISSUE TITLE
Purchases: site slug misaligned with site nane

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#2690]
#2359 added site slugs to the SectionHeaders in Purchases. However, the site slug isn't properly aligned with the site name:

![screenshot-calypso localhost 3000 2016-01-22 11-39-50](https://cloud.githubusercontent.com/assets/1248436/12508688/bf63686a-c0fd-11e5-8da1-3fc1d9919db4.png)

Tested in Firefox.

cc @breezyskies who wrote the PR who introduced the slugs.

**Comment by breezyskies** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/2923
