### ISSUE TITLE
Stats: page goes blank on iOS mobile browsers when navigating through stats

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#26916]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com in an iOS Browser (Safari or Chrome) 
2. View Stats for a site
3. Tap around the day view until screen goes blank

#### What I expected

Stats to appear

#### What happened instead

Screen goes blank - refresh then shows the page again

I couldn't reproduce this on wpcalypso.wordpress.com or calypso.live

Console error when using Safari mobile inspector:

```
TypeError: undefined is not an object (evaluating 'e.data')
updateData — 35.66940499a003240f2a82.min.js:1:9647
```

<img width="1127" alt="screen shot 2018-08-27 at 8 51 33 am" src="https://user-images.githubusercontent.com/128826/44633988-71138400-a9d6-11e8-9575-65ff7759140b.png">

#### Browser / OS version

Mobile Safari on iOS 11.4.1 - can't reproduce on desktop safari, nor Chrome desktop mobile mode - needs to be on a device

#### Screenshot / Video

https://cloudup.com/cYhaJbYgVtF

#### Context / Source
#user-report

**Comment by lancewillett** [comment]
I'm able to easily reproduce with WordPress.com and my `lancewillett` non-Automattic super admin user. The page goes blank fairly quickly:

<img src="https://user-images.githubusercontent.com/66797/46888715-2202a080-ce16-11e8-936a-29a5bf40b500.png" width="480" />

@Automattic/team-calypso @blowery Would you be willing to take a first stab at investigating?

**Comment by blowery** [comment]
@lancewillett taking a look. We just reverted #26650 in #27830 which may have been part of it.

**Comment by lancewillett** [comment]
I can't reproduce now after the revert. 👍

**Comment by alisterscott** [comment]
Closing as no longer reproducible with the revert in #27830

**Comment by liviopv** [comment]
Asked 1488743-zen to test and sent a follow-up to the original reporter on 1493745-zen
