### ISSUE TITLE
Free Trials i18n: URL loses locale when Free Trials is enabled via AB Test

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#2691]
There is currently an AB Test for Free Trials, and when is enabled for a user in locales other than English the URL loses the locale at the end, so if a user were to refresh a page they would default back to English.

**Steps To Reproduce**

1. Open a private browser window
2. Visit https://wordpress.com/start, open developer tools, remove all local storage, and add the following local storage values via developer tools: Key: <code>ABTests</code> Value <code>{"freeTrials_20160120":"offered"}</code> and Key: <code>signupFlowName</code> Value <code>"free-trial"</code> (This ensures the free trial AB test is enabled for this user)
3. Now visit the https://nl.wordpress.com and click "Website maken"
4. The start page is in Dutch (correct) but the URL does **not** end with "/nl" it is: https://wordpress.com/start/free-trial/themes
5. Refresh the page - the page is now in English which isn't expected

If you repeat the above steps but set the local storage to Key: <code>ABTests</code> Value <code>{"freeTrials_20160120":"notOffered"}</code> and Key: <code>signupFlowName</code> Value <code>"main"</code> (the AB test is disabled) you will see that when coming in from https://nl.wordpress.com the URL now contains "nl": https://wordpress.com/start/themes/nl as expected

**Comment by fabianapsimoes** [comment]
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.
