### ISSUE TITLE
Checklist: "Not available for this site" after purchasing a Jetpack plan 

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#26911]
#### Steps to reproduce
0. Create a new JN site
1. Starting at URL: https://jetpack.com/pricing/
2. Connect your site via "Buy plan" button

Was introduced in https://github.com/Automattic/wp-calypso/pull/26876

#### What I expected

To see a checklist screen if it is available for my site, and do not redirect me to `/checklist/my_site` if Checklist is not available

#### What happened instead

I was redirected to `/checklist/my_site` which says "Checklist not available for this site".

#### Screenshot / Video

Video: https://266-131107051-gh.circle-artifacts.com/0/home/circleci/wp-e2e-tests/wp-e2e-tests/screenshots/videos/can-see-premium-thank-you-page-2018-08-25T07-15-00.mpg

<img width="1251" alt="can-see-premium-thank-you-page-2018-08-25t07-10-39" src="https://user-images.githubusercontent.com/5654161/44617425-dee67100-a859-11e8-9828-0813ef561173.png">

**Comment by sirreal** [comment]
I believe this was introduced by #26721, not #26876. See details in #26912.
