### ISSUE TITLE
Jetpack: Hide calypso's help button during the connection flow

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#26920]
When you are connecting your jetpack site, the calypso contextual help button is being rendered in the bottom-right corner of the page:

![image](https://user-images.githubusercontent.com/1554855/44649251-9fe42700-a9e3-11e8-87ca-aadfd1ebcbc7.png)

The links offered by button are not contextualized at all for Jetpack, so until we came up with something better, let's hide that button during jetpack connection flow(s)

**Comment by tyxla** [comment]
PR to hide it for now: https://github.com/Automattic/wp-calypso/pull/26921
