### ISSUE TITLE
Editor: can't close editor when navigating directly to wordpress.com/post

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#26932]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post (for a customer with a _single_ site)
2. Try to close editor

#### What I expected

Editor closes

#### What happened instead

Editor won't close. No way out except to edit the URL.

#### Browser / OS version

Chrome on macOS

#### Screenshot / Video

![cant close editor](https://user-images.githubusercontent.com/128826/44705481-16ffe500-aae2-11e8-8aee-9de75c47d05f.gif)

#### Context / Source
Found when writing an automated test 
#automated-testing

**Comment by Naaman-Saif** [comment]
Hi. I am looking into this

**Comment by Naaman-Saif** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11515602/45004650-d33c3c80-b007-11e8-8872-d44ec90a0f6b.gif)
Hi,
Does this seem to resolve the issue? I'll make the PR, if this is okay.

**Comment by alisterscott** [comment]
> Does this seem to resolve the issue? I'll make the PR, if this is okay

Yes it looks like it, please do and include me as a reviewer

**Comment by naquiuddin** [comment]
I am getting started with wp-calypso contribution. This issue is fixed in master. May I know why is it still kept open?

**Comment by alisterscott** [comment]
Sorry closing now
