### ISSUE TITLE
Notifications: After triggering error notice it reappears without any errors

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#26949]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/notifications
2. Disable your internet connection to ensure an error.
3. Change a setting and try to save it, to trigger the error notice.
4. Clear the error notice.
5. Reenable your internet connection.
6. Change a setting and try to save it, to trigger a success notice.

#### What I expected

I expected the error notice to appear when I tried to save the settings without an internet connection, and the success notice to appear when I tried to save the settings with a working internet connection.

#### What happened instead

After reenabling my internet connection, every time I click on a notification setting checkbox, the error message reappeared. (Not when I tried to save the setting.)

#### Browser / OS version

macOS 10.13.6 / Chrome 68.0.3440.106

#### Screenshot / Video

![errornotices](https://user-images.githubusercontent.com/8658164/44778648-73f8ab00-ab75-11e8-916b-371e8e1d46d0.gif)

**Comment by Naaman-Saif** [comment]
Hi Rachel. I'll look into this.

**Comment by Naaman-Saif** [comment]
Hi. I'll look into this

**Comment by alisterscott** [comment]
See fix in https://github.com/Automattic/wp-calypso/pull/27085

**Comment by lancewillett** [comment]
Re-opened as there is a pull request pending in #27085

**Comment by lancewillett** [comment]
False alarm; patch now too far out of date.
