### ISSUE TITLE
Editor: Unclear messaging in restore newer post revision alert

### ISSUE THREAD

**Issue by kylemitchell** [Automattic/wp-calypso#26971]
#### Steps to reproduce
1. Starting at URL: 
https://wordpress.com/post/about.radiopublic.com/969
2.

3.
4.

#### What I expected
To open the most recent version of the article.

#### What happened instead
There were changes to the article since I last viewed it, and I as supplied a modal with copy

"A more recent revision of this post exists. Restore?"
[Don't Restore] [Restore]

I don't know what the implications are of each option. 

#### Browser / OS version
Mac OS 10.13.6
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

#### Screenshot / Video
![screenshot 2018-08-30 16 33 52](https://user-images.githubusercontent.com/6565892/44877729-daafbe80-ac72-11e8-9af0-eee92d7f654a.png)

**Comment by KokkieH** [comment]
Looks like there's an existing issue for this in #542.
