### ISSUE TITLE
Jetpack Connect: Prepare and bring back inline help

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#26987]
As of #26921 (as suggested in #26920) we've disabled Inline Help for any Jetpack Connect routes, however it would be great if we could bring in some Jetpack context into it and turn it back on.

For more information, see p7rd6c-1Ql-p2.

cc @Automattic/jetpack-design and @beaulebens who initially brought that up.

**Comment by tyxla** [comment]
I'll let folks from @Automattic/luna decide whether this still make sense.

**Comment by jeffgolenski** [comment]
@fditrapani @shaunandrews I remember a few weeks back, Shaun and I had a conversation about the inline help in slack and how this icon is barely used by customers in wpcom. 

@simison and I were chatting about keeping this icon suppressed until something goes wrong during the jetpack onboarding flow (connection errors, unable to install VP or akismet), etc. Maybe even running a split test with showing different help prompts in different areas (inside the errors themselves). But before we entertain that idea, I'd love your input on your experiences on wpcom.

**Comment by fditrapani** [comment]
>  I'd love your input on your experiences on wpcom.

We saw a number of folks glance right over it in our usability testing because it blended into the noise that is Calypso.

**Comment by tyxla** [comment]
I'm not if any onboarding team is planning to do that, but if not, I think it can be closed.

Perhaps @Automattic/zelda ?

**Comment by tyxla** [comment]
I think is good to be closed, but I'll let folks from @Automattic/jetpack-voyager chime in.

**Comment by rcanepa** [comment]
I think we can close this. We don't have plans to make this inline help contextual so enabling it will only add noise. Furthermore, this year we will move Jetpack Connect flow to cloud.jetpack.com and we will probably change the experience so I don't think this inline help would last very long either.

**Comment by tyxla** [comment]
Thanks, Renzo! Closing then.
