### ISSUE TITLE
Request for Dark/Night mode option

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#26995]
Request for dark/night mode option.

2301355-hc, 1286416-zen

In the meantime, here are some alternatives to help reduce eye strain:

- https://justgetflux.com/
- https://darkreader.org/
- WordPress plugins [Dark Mode](https://wordpress.org/plugins/dark-mode/) (related [thread](https://make.wordpress.org/core/2018/08/30/merge-proposal-dark-mode/) to merge into WordPress.org core), [WP Night Mode](https://wordpress.org/plugins/wp-night-mode/)
- on mobile, iOS and Android have built-in settings for dark/night mode, blue light filter

**Comment by torres126** [comment]
Related: #31996
