### ISSUE TITLE
Posts Missing in Calypso After Using Gutenberg Plugin on AT Site

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#26991]
http://chrissie.blog/

This is an AT site. The issue happened after creating posts using Gutenberg.

1. Go to Posts in Calypso and see your list of posts is missing.
2. Go to WP-Admin and notice all posts listed under Posts.

3. Go to Posts in Calypso and do a search for an existing post and note that the post is then listed.

4. Note that this is not a problem with Pages, even when pages are created in Gutenberg.

I expected my posts to show in a list in Calypso.

That did not happen. All is fine on my non-AT site with Gutenberg. I looked in Firefox and Chrome.

Here's a screencast of the issue:

![screen capture on 2018-08-24 at 08-46-06](https://user-images.githubusercontent.com/2545184/44619942-d17db680-a85a-11e8-8d3e-0ed7bca9d0ae.gif)

**Comment by rachelmcr** [comment]
Do you see any errors in your browser console when you visit the Blog Posts page in Calypso?

I tried to reproduce this on a test atomic site, but I couldn't. My posts (including posts made in Gutenberg) appear in Calypso as expected.

**Comment by gwwar** [comment]
Please re-open if this is still an issue.
