### ISSUE TITLE
Unable to download a backup after a rewind

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#27040]
#### Steps to reproduce
1. User did a rewind on their website, after which when they try to downlaod a backup of their website, they are getting an error (translated to English):

> An error occurred while preparing the file
An error occurred while preparing the file to download the backup.

#### What I expected
Expected to download the backup of the website without any errors.

#### What happened instead
An error is shown on the Activity Log page on top.

#### Screenshot
http://cld.wthms.co/wLuz7o

#### Context / Source
Rewind MC looks fine. Last full backup looks fine too but the timestamp is not the current one - it’s dated at 2hrs ago. Started `2018-09-06 10:20:32`

Since @StefMattana (p1536229591000100-tickets-slack) the backup is working fine on the backend, but Calypso thinks there is an error, I created the issue here instead in JPOP-issues repo.

Website: feelthebrain.me
User: `feelthebrainadmin`
Related GH issue (closed): Automattic/jpop-issues/issues/2758
Ticket: #1359713-zen
related slack conv: p1536229008000100-tickets-slack & p1536229894000100-activity-log-happy-slack

**Comment by galakhyati** [comment]
The user came back multiple times checking on any update on the issue.
#1359713-zen

I also see @damiannep pinged @roccotripaldi to check if someone is working on the issue.

Just making sure we get some update to share with the user.

**Comment by roccotripaldi** [comment]
@lsinger maybe can help with in this area.

**Comment by lsinger** [comment]
I haven’t worked on Rewind thus far, @roccotripaldi. Was that a typo, possibly?

**Comment by roccotripaldi** [comment]
yes - i meant to ping you on https://github.com/Automattic/wp-calypso/issues/25607
oops!

**Comment by roccotripaldi** [comment]
I'm investigating the underlying cause of these errors now. In the mean time, we can advise folks who encounter this error to try again. In my experience, clicking the 'Download Button' a second time will work.

**Comment by pauljacobson** [comment]
Thanks for the update @roccotripaldi. The user followed up to say that they have an active download. I told them we're still looking into the underlying issue, but that attempting the download tends to work.

**Comment by Robertght** [comment]
The user came back with the following:

>In fact I clicked the download button (screenshot under) prior requesting it, and the backups has dowloaded correctly and also it extracted correclty.

It is unclear to me if it still an issue.

**Comment by liviopv** [comment]
I tested generating and downloading a backup on their site, and it worked, so it looks like the issue might have been fixed already.

I asked the user to confirm, so we can close this issue.
