### ISSUE TITLE
It's Friday

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#27073]
https://www.youtube.com/watch?v=kfVsfOSbJY0
![](https://i.ytimg.com/vi/kfVsfOSbJY0/maxresdefault.jpg)

**Comment by Copons** [comment]
LGTM

**Comment by roundhill** [comment]
If only GitHub autoplayed videos... but still :shipit:

**Comment by jleandroperez** [comment]
Yup :shipit: !!!

**Comment by ockham** [comment]
Imma :ship: myself into the safe haven that is the weekend. ockham over and out.

**Comment by alisterscott** [comment]
No longer Friday - closing

**Comment by Copons** [comment]
> No longer Friday - closing

Does this mean we can reopen this next Friday? 🤔

**Comment by dmsnell** [comment]
> Does this mean we can reopen this next Friday? 🤔

we will have to see…we will have to see…
