### ISSUE TITLE
Calypso -> Plugins : in hebrew the sidebar is on top of the edit/settings area

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/wp-calypso#27128]
#### Steps to reproduce
Pre-requirements : an atomic site that has at least on plugin that appears in the Settings are (like the Coming Soon and Maintenance plugin)
1. Starting at URL: https://wordpress.com/stats/day/ 
2. Click Plugins -> Plugin settings ; a coupls of issues will appear in Hebrew (possibly in all languages written from right to left):
 a. Some of the plugin settings "working area" is hidden by the Sidebar
 b. Sidebar title is on the left while the sidebar is on the right
 c. detail - there are some tabs there that still appear on the left hand.

#### What I expected
To be able to edit the plugin settings from Calypso with all languages- whereas this way it is not possible.

#### What happened instead
Editing area is hidden / some elements are on the left while others on the right.

#### Browser / OS version
Firefox / Macos sierra

#### Screenshot / Video
https://cld.wthms.co/SU72oo

#### Context / Source
#user-report  hc-6356374

**Comment by yoavf** [comment]
Confirmed.

I have a fix in the backend, with D22702-code

**Comment by yoavf** [comment]
Should be fixed now.
