### ISSUE TITLE
Activity: fix icon for Feedback-type events

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#27121]
Feedback-type events on the Activity log show up with a different icon from what's visible on the sidebar.

While I personally don't like the icon used for Feedback, we should fix it on the AL for consistency: `gridicons-caption` should be `gridicons-custom-post-type`.

![image](https://user-images.githubusercontent.com/390760/45350561-f76dbf80-b5ab-11e8-82a1-53e483dc2a78.png)

**Comment by roccotripaldi** [comment]
D18173-code

**Comment by keoshi** [comment]
Thanks, @roccotripaldi !
