### ISSUE TITLE
Gutenberg: Open an existing post

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27140]
When visiting `/gutenberg/post/< id >` I can see my post content load in the editor.

**Comment by rodrigoi** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/27074

![screen shot 2018-09-11 at 23 04 19](https://user-images.githubusercontent.com/233601/45514444-bf1cdb80-b77b-11e8-9763-c20f4aec3104.png)
