### ISSUE TITLE
Posts: ability to manage categories (edit, delete, add)

### ISSUE THREAD

**Issue by Jstachurski** [Automattic/wp-calypso#2717]
In Calypso, there is no way to edit existing categories or delete existing categories. This must be done from WP Admin under Posts > Categories.

As a suggestion, this could be added under the Blog Posts main tab. Perhaps next to Published and Drafts.

#calypso-gaps

**Comment by StevenLangbroek** [comment]
This seems like core functionality, and something almost every Wordpress site uses. It would make sense from my perspective to prioritize this over nice-to-haves. It's confusing for users new to Wordpress.

**Comment by youknowriad** [comment]
closed by #9896
