### ISSUE TITLE
Font: The letter f goes missing or rearranges itself in a word

### ISSUE THREAD

**Issue by absentendings** [Automattic/wp-calypso#2720]
URL: 298488-chat

What I expected: The words first, film, find, and words beginning with an 'f' followed by the letter 'i' appear as they should be.

What happened instead: See 'ilm' or 'iflms' instead of film[s], and 'irst' or 'ifrst' instead of first.

Steps to reproduce: 1. Site font must be Merriweather Sans
2. View posts in Safari

Browser OS version: iOS 9.2 (not 2.1 as is screencapped.)

Screenshots/Video:
![untitled1](https://cloud.githubusercontent.com/assets/16850890/12542184/bd71ad72-c2d4-11e5-8dd1-6d4d9bfbf83b.png)

**Comment by frosty** [comment]
This seems to be related to a new version of Merriweather that was released a couple of days ago. It looks like they had some issues with ligatures (which would explain this problem), which this PR addresses: https://github.com/EbenSorkin/Merriweather/issues/16.

**Comment by vladikoff** [comment]
could be related https://github.com/gruntjs/gruntjs.com/issues/81

**Comment by frosty** [comment]
@absentendings Are you able to re-test this? It looks like an updated version of the font has now been pushed to Google Fonts, so this should be fixed.

**Comment by davelab6** [comment]
This should now be totally fixed at the GF API side :)

**Comment by absentendings** [comment]
@frosty Definitely fixed and non-replicable! Thank you all for all your help and insight! :)
