### ISSUE TITLE
Gutenberg: ESLint rule for classname namespace in Gutenberg extensions

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#27211]
#27187 disables the `wpcalypso/jsx-classname-namespace` ESLint rule for any Gutenberg extensions that we build with the Calypso SDK and store in Calypso. 

It would be nice to create a custom ESLint rule for our Gutenberg extensions, so we can follow more strict guidelines when writing our classnames there.

**Comment by ockham** [comment]
I wonder if Gutenberg has any custom `className` rules we can re-use here? Can't seem to see any in their repo at first glance. Let's ask @aduth or @youknowriad :slightly_smiling_face:

**Comment by aduth** [comment]
Nope, not yet.
