### ISSUE TITLE
Reader: Prevent Blocking of Own Site

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#27215]
As per https://github.com/Automattic/wp-calypso/issues/3647, it's not currently possible for people to undo a block. 

Sometimes people will accidentally block their own site. Examples can be found in 263360-h and 1403545-z.

It'd be great if we could make it impossible for people to their own sites in the first place.

**Comment by bluefuton** [comment]
@SiobhyB we have some protection in place against a user blocking their own site in Calypso - we check to see if the user has edit permissions on the post in question. If they can edit it, we don't show the block option.

https://github.com/Automattic/wp-calypso/blob/15721e5bdc551482f980e902db65e7bec510241e/client/blocks/reader-post-options-menu/index.jsx#L166

I'm not able to reproduce and 1403545-z doesn't hold any clues. Please reopen if you're able to repro it 🙂
