### ISSUE TITLE
Support: Third party cookies prevent use of help contact form

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#2722]
Repro:
1. Disable third party cookies.
2. Visit /help/contact

Expected: You can contact us.

Actual: You see this placeholder, which never turns into any sort of contact form:

![2016-01-19_contact_us_blank](https://cloud.githubusercontent.com/assets/2738252/12536601/1a99db12-c278-11e5-9b28-f30073b038d8.png)

Disabling third-party cookies will disallow chat, but we should be able to detect that third-party cookies are disabled and show the non-chat contact form in this case.

It might also be worth considering sending along with the ticket the fact that third-party cookies are disabled, as this can lead to other issues that are often what users are reporting. Alternately, we could discover that 3rd party cookies are disabled on the /help screen and show a proactive notice. Unless it's simple to do one of those things, we should probably implement in a separate issue/PR, but for now I leave it here in case it's very simple.

**Comment by omarjackman** [comment]
Also noting here that the user might see a javascript error in their console that looks like this:

![screen shot 2016-01-25 at 7 50 38 pm](https://cloud.githubusercontent.com/assets/1854440/12569442/ffb2e926-c39c-11e5-9340-d0eb29d4fa89.png)

**Comment by designsimply** [comment]
I was unable to reproduce the problem using the testing steps provided. ([32s](https://cloudup.com/c_qWPNYU4hU))
