### ISSUE TITLE
Editor: Adding a link using toolbar button causes editor to jump to the top

### ISSUE THREAD

**Issue by rezzap** [Automattic/wp-calypso#27226]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post from a Windows machine using Windows 7 or 10.
2. Add content to a new post. Make sure it's enough content so the first line scrolls off the top of the screen.
3. Towards the end of the post, highlight some text
4. Click the hyperlink button in the toolbar and add a link.

#### What I expected
 
For the link to be added, but to still have the editor focused on the text I'm currently editing. (this is what happens when a link is added using Mac)

#### What happened instead

The editor jumped to the top of the post, and I had to scroll down to get back to the anchor text where I'd added the link.

#### Browser / OS version

I have tested and replicated this on Windows 10 Professional on latest versions of Edge and Chrome.
User reported in Chrome 68.0.3440.106 on Windows 10 (64-bit) and another user in Windows 7 (64-bit) on Opera.

#### Screenshot / Video

User provided a video recording of the issue available here: http://recordit.co/emROVNPLuq. 

#### Context / Source

#user-report
Users reported in 1418879-zen and 1408950-zen

Bug sounds exactly like what was reported here: #16741 and fixed in #16873 but now the issue is only on Windows.

**Comment by KokkieH** [comment]
Several more reports from the [support forums](https://en.forums.wordpress.com/topic/new-update-link-button-forces-me-to-the-top-of-the-page/)

> but now the issue is only on Windows.

The forum thread has Mac users also reporting this, and I'm able to replicate in Firefox on Mac OS as well.

cc @jameskoster who fixed it last time.

**Comment by lizkarkoski** [comment]
I have another report that came to us via social media (Facebook messenger)

site: resourceholidayproducts.wordpress.com

browsers: chrome and firefox exhibit the same behavior

asking the user to try using wp-admin for the time being.

**Comment by msilbers** [comment]
Another report of this in #1437466-zen
I was also able to replicate it using my Mac and Chrome

**Comment by KokkieH** [comment]
More reports from the [support forums](https://en.forums.wordpress.com/topic/difficulty-editing-links/)

**Comment by rezzap** [comment]
I have someone else reporting the same behaviour but this time when they try to edit an image. I couldn't replicate it in the Chrome, but I did replicate it in Safari on Mac. 

Steps to recreate:
- Create a post with a lot of content. 
- Add an image. 
- Click on the image to edit the text
- Cancel or Update

What happened the post automatically scrolls all the way back to the top. 
![screen recording 2018-09-24 at 02 59 pm](https://user-images.githubusercontent.com/10325627/45956687-2273fc80-c00b-11e8-87af-5581d9b4e1ac.gif)

Reported in 2632371-hc

**Comment by jameskoster** [comment]
> cc @jameskoster who fixed it last time.

I don't remember doing this 🤔 Do you have a link to the PR? Not sure when I'll have a chance to look at this.

**Comment by KokkieH** [comment]
@jameskoster you commented on and closed #16873, but I don't see a PR referenced.

**Comment by sashastone** [comment]
Another report of the same issue with editing links: #1408950

**Comment by kylemcph** [comment]
User from Zen-1408950 is reporting they are using: Windows 7 Home Premium, Opera Version: 55.0.2994.47.

**Comment by katiebethbrown** [comment]
Another Windows user reporting the editor jumping when adding links: #1460014-zen

**Comment by GaryBairead** [comment]
Another report in the [support forums.](https://en.forums.wordpress.com/topic/bug-scrolling-bug-in-online-editor/)

**Comment by flootr** [comment]
possibly related #27600

**Comment by lakellie** [comment]
Another Windows user reported this bug in #1474050-zen

**Comment by dkmyta** [comment]
Sounds like this could potentially be the same issue here: #1504360-zen

**Comment by KokkieH** [comment]
Another report in the [forums](https://en.forums.wordpress.com/topic/dislocation-after-inserting-matter/#post-3204603).

**Comment by lizswafford** [comment]
Possibly the same issue reported here #1545779-zen. 
Google Chrome on Windows 10.

**Comment by jburciaga0** [comment]
And the same issue here for 8086338-hc
Edge 17.17134 on Windows 10.0.0
Classic editor chosen in the age of Gutenberg

**Comment by KokkieH** [comment]
Another report in the [forums](https://en.forums.wordpress.com/topic/when-creating-posts-wp-jumps-to-top-of-page/) - Chrome and Opera on Windows 10

**Comment by lizkarkoski** [comment]
Another report using 
MAC OSX 10.11.6
Chrome 70.0.3538.102

Forum thread: https://en.forums.wordpress.com/topic/problem-adding-link-with-new-editor/

**Comment by katiebethbrown** [comment]
Another report in #5390627-hc

**Comment by scosgro** [comment]
Another report in #2084675-hc

User is getting this in Windows/Chrome. I could replicate in the same setup. They say their co-writer is not experiencing this in Mac/Safari.

**Comment by cecilearkay** [comment]
Another report in #9213118-hc. User is using Chrome 71.0 on Windows 10.
