### ISSUE TITLE
Odd look of the HC/support button on the plan cancellation survey for .com sites.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#27235]
#### Steps to reproduce
1. Starting at URL: for a :site on a plan got to `https://wordpress.com/plans/my-plan/:site`
2. click on  `Manage Payment`
3. and at the bottom on` Remove "plan"`
4. ... the survey appears 

#### What happened: HC link/button is visually broken (functionality works).
<img width="572" alt="screen shot 2018-09-17 at 11 35 54" src="https://user-images.githubusercontent.com/13561163/45616550-15d23000-ba70-11e8-9799-d8543c709506.png">

#### Browser / OS version
Mac

**Comment by AnnaMag** [comment]
cc/ @Automattic/editorial for thoughts on whether "your thoughts are needed" is the most optimal choice of words.

**Comment by michelleweber** [comment]
Best to just be direct. I'd lose it and change to something that communicates that the cancellation has been processed like, "All set -- your plan is cancelled," and then the next below becomes "We'd love to know why you're no longer interested in a paid plan."

This rest of the screen a few other small issues as well:
- This doesn't really need the text above the question at all; it's perfectly clear without it. 
- The first "question" should just end with a period.
- The questions themselves could be tighter and simpler: "Why did you cancel?" and "What's next for your site?"
- The "Another reason" option should just have a regular period at the end.

**Comment by AnnaMag** [comment]
Thank you @michelleweber! The bug was addressed, thus the issue was closed. Re copy improvements 👍

**Comment by spen** [comment]
Thanks again for pointing this out - It'll help getting a proper fix out much quicker :)

**Comment by sararosso** [comment]
@AnnaMag Thanks for digging into this, and thanks to @michelleweber for copy suggestions. I'll duplicate this comment on the other PR about copy suggestions but the customer marketing team has an upcoming sprint scheduled for the refund survey, so we'll lead any copy or messaging changes then, so we can close your PR for the time being.
