### ISSUE TITLE
Improve the copy of the cancellations survey for paid plans.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#27238]
It is worth to incorporate the changes to the copy in the cancellation survey which have been proposed by the editorial team:
https://github.com/Automattic/wp-calypso/issues/27235#issuecomment-421960087 

Steps:
Access the survey as outlined here: https://github.com/Automattic/wp-calypso/issues/27235.

/cc @Automattic/marketing-dev, @adamziel

**Comment by sararosso** [comment]
The customer marketing team has an upcoming sprint scheduled for the refund survey, so we'll lead any copy or messaging changes then, so we can close your PR for the time being.

**Comment by AnnaMag** [comment]
Thanks @sararosso, I see—I'll close this issue then. Let us know if/how we can contribute to the Jetpack's version of it.
