### ISSUE TITLE
Changing the copy in T&C at plan purchase checkout.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#27234]
We have started replacing with a copy that did not include the word "fascinating", which can be misunderstood.
#### Steps to reproduce
1. Go through the steps to purchase/upgrade a plan or directly to e.g.
 `https://wordpress.com/checkout/:site/jetpack-personal-monthly`
####
<img width="485" alt="screen shot 2018-09-17 at 11 11 37" src="https://user-images.githubusercontent.com/13561163/45614926-5b402e80-ba6b-11e8-99d6-97cdd9f7ceb9.png">
Would it be a good idea to change the wording?

**Comment by AnnaMag** [comment]
@joanrho, we changed it elsewhere during our plans' work. Should we continue with complete removal?

**Comment by joanrho** [comment]
@AnnaMag Yes, please!

**Comment by michelleweber** [comment]
+1 to nixing the fascinating.
