### ISSUE TITLE
Editor: scrolling through media library when adding images force closes the media browser

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#27246]
The user encountered an issue where they'd be kicked out of the media browser when they try to add a featured image to the post, or an ordinary image to the body of their post from the WordPress.com editor. It manifests when they scroll down the media library in the pop-up media browser.

#### Steps to reproduce

1. Open a draft post to edit.
2. Click on the button to add a **Featured Image**
3. This opens the media browser. Scroll down through the media library in the pop-up media browser.
4. The media browser force closes before reaching the bottom.
5. User is unable to click on the **Featured Image** button afterwards.

This reportedly happens when attempting to add images to the body of a post too.

#### What I expected

Clicking on the **Featured Image** button should open the media browser, and enable a user to scroll freely through the collection without the pop-up closing by itself.

#### What happened instead

Each time the user tested this, the media browser force closed when the user scrolled down (before reaching the bottom of the content list). Scrolling speed didn't seem to make a difference.

#### Browser / OS version

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

#### Screenshot / Video

[Video demonstration](http://cld.wthms.co/x1F987)

#### Context / Source

User report in 5879469-hc (with follow-up in 1422275-zen)

We were _not_ able to replicate this when we tested this on our side. I tested on macOS 10.13.6, using Firefox Developer Edition 63.0b6.

**Comment by edwinho89** [comment]
Similar issue reported in 2069187-zen

User's on Windows 10 Chrome web browser (https://www.whatismybrowser.com/w/EAWTN27) so it may not be browser related.

I was able to reproduce this once, and can see the following console log error here:

```
Uncaught Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:50:522
    at s (https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:50:625)
    at Xs (https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:50:95354)
    at Object.enqueueForceUpdate (https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:50:45138)
    at i.w.forceUpdate (https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:58:1789)
    at i.d.componentDidMount (https://wordpress.com/calypso/evergreen/189.7cd4a7245c2c6849db9b.min.js:32:5272)
    at Ws (https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:50:82485)
    at Hs (https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:50:85160)
    at https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:50:98367
    at Object.t.unstable_runWithPriority (https://wordpress.com/calypso/evergreen/188.f1f7acf377cb12f7415a.min.js:66:3218)
```
