### ISSUE TITLE
Customizer: Allow Business plan users to enter custom footer credit text

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#27251]
#### Steps to reproduce
1. On a Business plan site, go to My Site > Customize > Site Identity > Footer Credit.
2. Select "Hide".
3. Click "Publish".

#### What I expected

From the perspective of a user, I expect to be able to hide the WordPress.com footer credit, and replace it with my own custom footer credit, most likely referencing the name of my business.

#### What happened instead

From the perspective of a user, I only have the option to hide the WordPress.com footer credit. There is no way to add my own footer credit. I start a live chat and am told I can add my own footer credit with custom CSS. I copy and paste some random code-looking things into the Customizer, but don't really know what it is. I have no idea how to change the footer credit text in the future because I'm not familiar with CSS.

#### Context / Source
The Business plan allows users to hide the WordPress.com footer credit. Many users want to display their own custom footer credit instead, which can currently only be done by adding custom CSS. Not only are users frustrated by this, it also leads to a lot of additional work for HEs and the CSS guild who have to write custom CSS for each individual user request.

#painpoint

**Comment by eduardozulian** [comment]
I'd also mention that, if possible, we allow users to line-break and make proper use of some HTML elements.

**Comment by eduardozulian** [comment]
6712750-hc

**Comment by eduardozulian** [comment]
Any updates on this front?
