### ISSUE TITLE
Reader: share menu titles off screen in iOs

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#2725]
When tapping the sharing menu in portrait view the sharing service titles are cut off the screen in iOs in both Safari and Chrome browsers. Using iOs 9.2.1 / Chrome 47  / Safar 9.0

In both the stream and single post view.

![img_3276](https://cloud.githubusercontent.com/assets/16867830/12539197/ea15d570-c2ba-11e5-8bf5-a1f95409defc.PNG)
![img_3277](https://cloud.githubusercontent.com/assets/16867830/12539199/efb9b1fe-c2ba-11e5-8280-0ddba3de8f2a.PNG)
![img_3278](https://cloud.githubusercontent.com/assets/16867830/12539204/0de2fdac-c2bb-11e5-841c-f0420b552134.PNG)

**Comment by jancavan** [comment]
I'm unable to replicate the issue on both the main streams and the individual blog streams. I think those were solved in this PR: https://github.com/Automattic/wp-calypso/pull/2859

However, the issue still exists on single post view:
![img_7662](https://cloud.githubusercontent.com/assets/4924246/13188405/2d2cffa0-d706-11e5-88cc-7bd5508fec13.PNG)
