### ISSUE TITLE
Reader: tapping comment icon does not work

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#2726]
Tapping comment icon does not work in stream view of Reader. 

Using iOs 9.2.1 / Chrome 47 / Safari 9.0

Safari 
![img_3279](https://cloud.githubusercontent.com/assets/16867830/12539233/bdbfaa72-c2bb-11e5-8190-d16025016888.PNG)

Chrome
![img_3280](https://cloud.githubusercontent.com/assets/16867830/12539304/afe04ac2-c2bd-11e5-9236-7a652a7a374d.PNG)

**Comment by designsimply** [comment]
Closing as a duplicate of #974
