### ISSUE TITLE
Double quote is turning into the Unicode value #8221; 

### ISSUE THREAD

**Issue by zolbayars** [Automattic/wp-calypso#27263]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/zolbayarq.wordpress.com
2. Write some text wrapped in double quote
3. Publish it

#### What I expected
A text wrapped in double quote.

> "Example"

#### What happened instead
The right quote is replaced with a Unicode value. 

> "Example#8221; 

#### Browser / OS version
Chrome 

#### Screenshot / Video

![aaaaaa](https://user-images.githubusercontent.com/3589907/45671269-9a4bae00-bb57-11e8-88b9-294cc53782cb.PNG)

**Comment by alisterscott** [comment]
Hi @zolbayars 

Thanks for your report. I couldn't reproduce this - I have a feeling it is something to do with your browser language settings - what version of Chrome and what operating system are you on? 
What is your browser language settings? Would you mind pasting a screenshot?

chrome://settings/

This is Chrome 69 on macOS using English as language:

<img width="1072" alt="screen shot 2018-09-18 at 6 06 05 pm" src="https://user-images.githubusercontent.com/128826/45673353-d2f68200-bb6d-11e8-9b44-3be9e13701f9.png">

**Comment by zolbayars** [comment]
Hi @alisterscott 

- Chrome language: English 
- Chrome version: Version 69.0.3497.100 (Official Build) (64-bit)
- OS: Windows 10

Strangely, it's same in Firefox version 62.0

**Comment by alisterscott** [comment]
Hi @zolbayars 

I tried both Chrome 69 and Firefox 62 on Windows 10 and I can't see the issue:

<img width="1533" alt="screen shot 2018-09-19 at 10 28 48 am" src="https://user-images.githubusercontent.com/128826/45723894-e26ddd80-bbf6-11e8-85b0-3dc8330c8c3f.png">

I'm leaning towards something to do with language or font settings? Any ideas?

**Comment by zolbayars** [comment]
Hi @alisterscott 
It might be that. 
I think you should close this issue since no one can reproduce this except me :)
