### ISSUE TITLE
package.json: Current declaration of engines may not be playing nice with check-node-version's output if running on old node version

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#27284]
When attempting to `npm start` using a version of node previous to the one declared in `engines` (package.json) `check-node-version` proposes a command that is not working: `nvm install ^10.5.0`

#### Steps to reproduce
1. Run a distclean. `npm run distclean`.
1. Try an old version of node, like `nvm use 10.1`.
2. Run `npm start`.
3. Expect it to fail and to be shown a message like:
    ```
    Error: Wanted node version ^10.5.0 (>=10.5.0 <11.0.0)
    To install node, run `nvm install ^10.5.0` or see https://nodejs.org/
    ```
4. Run the proposed command `nvm install ^10.5.0`
5. Expect it to fail. 

cc @blowery as it was introduced in #25764 by 8efc4ba671a0f4bab9c5985e6829156fe4011285

#### What I expected

Proposed `nvm install xxxx` command to work smoothly

#### What happened instead

Fails with message:
> Version '^10.5.0' not found - try `nvm ls-remote` to browse available versions.

#### Browser / OS version

MacOS

*nvm* version: `0.33.8`.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/746152/45711414-de42b100-bb5f-11e8-9a41-29e42eac1db0.png)

#### Context / Source

Context was: long time had past without building Calypso or updating Node.

**Comment by blowery** [comment]
Submitted an issue upstream in https://github.com/parshap/check-node-version/issues/26

In the meantime, you can use plain `nvm i` and it'll pick up the right version from `.nvmrc`.

**Comment by oskosk** [comment]
Thanks @blowery !
