### ISSUE TITLE
Markdown block: icon border stays black when greyed

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#27305]
Looks like Markdown block has `stroke="#000"` that stops it turning grey in Gutenberg's "recent blocks" selector:

![image](https://user-images.githubusercontent.com/87168/45741053-4e544400-bbff-11e8-8ce2-4c215aba7845.png)

![image](https://user-images.githubusercontent.com/87168/45741088-67f58b80-bbff-11e8-9281-ada4ce6cdd4c.png)

![image](https://user-images.githubusercontent.com/87168/45741124-7cd21f00-bbff-11e8-8cd1-362acca0a83c.png)

cc @tyxla

**Comment by tyxla** [comment]
Great catch, Mikael! I'm on it.

**Comment by tyxla** [comment]
Addressed by #27310.
