### ISSUE TITLE
Gutenberg: Add missing document title for the Gutenberg Editor

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27300]
Let's use the `DocumentHead` component to set a page title. On a new post this should be:

`New Post < Site Title`

and after an autosave:

`Edit Post < Site Title`

<img width="785" alt="screen shot 2018-09-18 at 5 30 59 pm" src="https://user-images.githubusercontent.com/1270189/45723988-fe2aa280-bb68-11e8-908a-9a5f9469eeb1.png">
<img width="829" alt="screen shot 2018-09-18 at 5 31 12 pm" src="https://user-images.githubusercontent.com/1270189/45723991-ff5bcf80-bb68-11e8-8db9-17f42b52f0cc.png">

**Comment by alisterscott** [comment]
I don't think this is done, or it has regressed: https://github.com/Automattic/wp-calypso/issues/39274
