### ISSUE TITLE
Stats/Responsive: Hovercard overflows and gets cut off

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#2733]
I did: used Calypso Stats/Days in narrow (mobile) mode in my desktop app, hovering the bars to quickly gain insight into the overall trend for my site.

I saw: roughly 3 of the hovercards get cut off (see screenshot below for example) when you hover their respective bars. They're simply too wide for the viewport and should be repositioned.

I expected: to be able to see information at a glance on desktop in a narrow window. I realize this problem has occurred because the narrow responsive modes are primarily for touch devices, but nevertheless!

I recommend: at a certain point -- maybe 1 column or mobile -- stop repositioning the hovercard, center it or make it 100% width (on mobile) and instead only move the little arrow at the top to indicate selection. Clean, simple!

Note: I was able to reproduce this in my web browser as well, so it's not a problem with the Mac app specifically, rather a responsiveness issue.

Peace!

<img width="345" alt="screen shot 2016-01-25 at 14 57 55" src="https://cloud.githubusercontent.com/assets/3073557/12545373/2e8947c8-c374-11e5-9912-d452779c990b.png">

**Comment by hoverduck** [comment]
05May16 Bug Scrub

I was only able to reproduce this bug in Firefox (I also checked Chrome and Safari, all on OSX).  Firefox is the only one that was willing to go down to a width of 320px.  The minimum width on the other browsers was enough that the popup was not obscured.

<img width="335" alt="screen shot 2016-05-05 at 1 23 08 pm" src="https://cloud.githubusercontent.com/assets/7233112/15051042/bd764f7c-12c4-11e6-8429-651f0d2eb9c8.png">

**Comment by isaackeyet** [comment]
Can't reproduce anymore. Let's close it. Thanks.
