### ISSUE TITLE
Modernize the Masterbar and Layout component code

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#27338]
The `Layout` and `Masterbar` components (`client/layout/...`) contain some legacy code that can be removed or modernized. The instructions that follow will lead to a series of very nice cleanup PRs -- can be a project for a small team.

**1. Remove the `sites` prop**
The `newestSite` method is not used anywhere. The `Masterbar` component doesn't need a `sites` prop. All occurences of `this.props.sites` can therefore be removed.

**2. Stop passing `user` prop to `Layout`**
Remove the legacy `import userFactory from 'lib/user'` from `client/controller/index.web.js` and stop passing the created `user` object as a prop to `Layout`. All places that use the `user` prop should get the information from Redux.

Also, the `getCurrentUser` selector can be replaced by `isUserLoggedIn` one, which better explains what we are trying to check.

Of course, `Layout` and `MasterbarLoggedIn` should stop using the `user` prop first:
- the `renderMasterbar` method uses `user` to determine if user is logged in and render logged out master if she's not. Is this code even needed? The `Layout` component is already guaranteed to be rendered only for logged-in users. Or is it not? Verify and remove.
- the `user` info for `Gravatar` in masterbar should be retrieved from Redux
- if the `Notifications` component needs to see the `has_unseen_notes` property of user, it should retrieve that info from Redux in its own `connect` call. Can it safely use the `hasUnseenNotifications` selector? That selector seems to do more than just read `has_unseen_notes`. Consult with notifications experts.

After all usages of `user` are removed, `Layout` can stop using the `observe` mixin and can be codemodded to ES6 class :tada:

**Comment by ockham** [comment]
> - the `user` info for `Gravatar` in masterbar should be retrieved from Redux

This might be a bit misleading -- we shouldn't `connect()` the `Gravatar` component _itself_ to `user` state. Quoting myself from https://github.com/Automattic/wp-calypso/pull/27549/files#r222109977:

> Caveat, according to a quick `grep`, the `Gravatar` component is used in a couple of other places, not only `Layout`, where we're still passing a `user` prop explicitly. This change to `connect()` will override that passed prop, which can lead to developer confusion :wink: and subtle errors. On a conceptual level, we might also be using the `Gravatar` component to display the avatars of users other than the currently logged in one (maybe in a given site's user management -- the 'People' setion?)
>
> I'd suggest removing the `connect()`ion to `user` here and move it to `Layout` instead, continuing to pass on that `user` prop to child components. I think this would retain previous behavior as much as possible.
