### ISSUE TITLE
Editor: Publicize Info message isn't wrapped to fit in the sidebar

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#2736]
Steps to reproduce:

0. Go to WordPress.com/post
1. Start writing a new post on a site where Publicize is connected
2. Open the Publicize box.
3. Click on the "i" icon to view more info about Publicize.

![screen shot 2016-01-25 at 12 58 54 pm](https://cloud.githubusercontent.com/assets/426388/12550378/a64bf8a2-c363-11e5-8bee-2003f8786158.png)

**Comment by kjbenk** [comment]
I just created a new Pull Request to fix this error :)
