### ISSUE TITLE
Gutenberg: Reusable Blocks Section (wp-blocks)

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27374]
Gutenberg has a link to manage Reusable Blocks document settings. This takes us to 
`wp-admin/edit.php?post_type=wp_block`

We should ensure that we can view these custom post types in Calypso and update any of the management links.

**Comment by kwight** [comment]
> Gutenberg has a link to manage Reusable Blocks document settings

Where is this link? Can't find it for the life of me.

**Comment by Copons** [comment]
@kwight There are actually 2 links, both hidden by Calypsoify, but you can see them with `calypsoify=0`.
One is in the More Menu (the ellipsis icon in the right end of the top bar), the other in the Reusable Blocks section of the Inserter, which is only shown if you have some reusable blocks saved.
