### ISSUE TITLE
How Can I install this on windows7?

### ISSUE THREAD

**Issue by akhilesh1010** [Automattic/wp-calypso#2737]
I am trying to install wp-calypso on windows but instructions not working can any one explain me how can I install it on windows?

**Comment by klimeryk** [comment]
Are you referring to the [Desktop app](https://desktop.wordpress.com/) or are you a programmer and want to run this code locally? (and hopefully contribute :))
If the latter, we have an [open PR that adds Windows support](https://github.com/Automattic/wp-calypso/pull/2124) - please give it a try. Any feedback on that PR would be greatly appreciated.

**Comment by stephanethomas** [comment]
@akhilesh1010, I just wanted to let you know that we have released a [portable development environment](https://github.com/Automattic/wp-calypso-bootstrap) that simplifies the task of running Calypso on Windows. Enjoy!

**Comment by klimeryk** [comment]
There's also [Windows support using MSYS2](https://github.com/Automattic/wp-calypso/blob/master/docs/windows.md) - so you're covered if you prefer something more native.
Closing this as both options are well documented - feel free to re-open if needed or open a new, more specific issue.
