### ISSUE TITLE
Notifications Panel: migrate CSS to webpack

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#27397]
Notifications Panel is an async-loaded component that gets downloaded only after the user clicks on the "bell" icon in the masterbar.

Migrate the Notifications Panel CSS styles to webpack imports. That should move them to a separate CSS chunk and make the main `style.css` stylesheet smaller.

Refer to p4TIVU-98Q-p2 for context and detailed instructions on the CSS webpack migration.

Verify that the `style.css` stylesheet indeed got smaller and that a new CSS asset started to be generated by webpack.

**Comment by flootr** [comment]
@jsnajdr it seems this should be fixed by #27533, correct?

**Comment by jsnajdr** [comment]
> it seems this should be fixed by #27533, correct?

Yes, that's correct. Closing :+1:
