### ISSUE TITLE
When using a mobile browser (iOS 12) and the Visual Editor you won’t be able to properly select/highlight text

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#27399]
Hi foks!

I initially reported this on WordPress.org (https://core.trac.wordpress.org/ticket/44980), but also mentioning here as a reference.

This will happen whether you are using Calypso or WP Admin.

#### Steps to reproduce
1. Log in to your WordPress site using a browser (Safari or Chrome) on any device with iOS 12.
2. Edit or create a post/page with text on it using the Visual Editor
3. Select/highlight any word. Then try to highlight the next or previous word.

#### What I expected
To be able to highlight the text as in the Text Editor

#### What happened instead

It won't let you highlight what you want. Instead, it will highlight all the paragraph or nothing

(You will notice this only happens with the Visual Editor and not the Text Editor)

#### Browser / OS version

Safari & Chrome - iOS 12.0

#### Screenshot / Video

https://cld.wthms.co/ZOFGaV

#### Context / Source

1430881-zen

**Comment by alisterscott** [comment]
This sounds like a TinyMCE bug

**Comment by alisterscott** [comment]
Raised for TinyMCE: https://github.com/tinymce/tinymce/issues/4579

**Comment by samiff** [comment]
Was able to reproduce the issue in iOS 12 in Safari and Firefox on an iPad Mini: https://cld.wthms.co/If7Rsr

**Context / Source**
1481045-zen

**Comment by sarahcada** [comment]
User followed up at 7672786-hc

**Comment by MikeS1042** [comment]
Any word on this one? It is causing our customers some grief.

**Comment by charlesr1971** [comment]
Yes. I am getting the same behaviour on iOS 12, iPhone 7, & iPad. Please sort this out. It makes mobile editing virtually impossible. I am using the TinyMCE mobile configuration.
