### ISSUE TITLE
Photon (iX.wp.com) should not be used for *.files.wordpress.com URLs

### ISSUE THREAD

**Issue by bazza** [Automattic/wp-calypso#27410]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. My Sites (pick any public WordPress.com site)
3. Media
4.  Right click -> Copy image address on any thumbnail image

#### What I expected

To see the resized image served directly from WordPress.com

https://barry.files.wordpress.com/2015/11/img_3008.jpg?w=450

#### What happened instead

WordPress.com images being redirected through Photon: 

https://i2.wp.com/barry.files.wordpress.com/2015/11/img_3008.jpg?ssl=1&w=450

#### Browser / OS version

All

#### Screenshot / Video

None

#### Context / Source

We'd also love to know how you found the bug:  Customer complaint.

**Comment by alisterscott** [comment]
Fix in https://github.com/Automattic/wp-calypso/pull/27412
