### ISSUE TITLE
Gutenberg: update auto-draft custom endpoint to allow for any post type (including CPT)

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27430]
We may be limiting our new temporary endpoint to posts only. We should also allow creation of auto-drafts for pages, and any other CPTs

**Comment by kwight** [comment]
Verified that auto-drafts in core are saved as the intended post type, and that our custom endpoint saves non-posts as posts.

**Comment by kwight** [comment]
Patch for review in D18864-code.

**Comment by gwwar** [comment]
In D18864-code, we found that we'd need to add a custom endpoint to Jetpack to accurately fetch all registered post types. To avoid this, let's update middleware to point at our v1.2 endpoint instead to create an auto-draft.

<img width="831" alt="screen_shot_2018-10-04_at_10 58 34_am" src="https://user-images.githubusercontent.com/1270189/46640370-7957f680-cb20-11e8-83fc-f2d70296c054.png">


Follow up items after the Calypso PR lands would be:
- Removing the custom endpoint used to add an auto-draft.
- See if core folks would be open to updating the core REST api https://github.com/Automattic/wp-calypso/issues/27320

**Comment by gwwar** [comment]
@kwight heads up that I'll be spinning up a Calypso diff.
