### ISSUE TITLE
Gutenberg: Link Calypso opt-in with the wp-admin opt-in

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27431]
Let's link our opt-in status to the opt-in in wp-admin. This means that if we enable Gutenberg in wp-admin we should redirect from `/post` to `/post/gutenberg`. Similarly opting into Gutenberg from the Calypso side should enable this functionality for Calypso.

Until we have support for Jetpack sites, any `/post` links with the Gutenberg opt-in will redirect to wp-admin.

Clicking on "use the classic editor" will deactivate Gutenberg (but leave the opt-in) available to try.

wp-admin opt-in:
![screen shot 2018-09-25 at 1 03 32 pm](https://user-images.githubusercontent.com/1270189/46040405-13518500-c0c5-11e8-92b8-cabc01fe0d82.png)

Also, when viewing the Opt-In Modal, let's remove the dismiss option to force a decision:
![screen shot 2018-09-25 at 1 11 28 pm](https://user-images.githubusercontent.com/1270189/46040210-89a1b780-c0c4-11e8-9e17-8c5039939fda.png)

See also pb6Nl-cNj-p2 for additional context

cc @shaunandrews

**Comment by kwight** [comment]
There are a few flows we need to take into account; I'll recap and state how I think they could be handled. @shaunandrews let me know if I'm off or missing something.

In general, I'm assuming that we will _not_ explicitly be saving an "opt out" selection, only an "opt in" (as WP.com wp-admin currently does, by setting a `enable-gutenberg` blog sticker). If a user takes an action other than opting in, we want them to continue to have the option to opt in, as opposed to hiding opt-in UI (like the editor sidebar visual "Learn more").

| User loads  | Site has opt-in blog sticker            | Result        |
| --- | :---------------: | ------------- |
| `/post/:site`   |   Yes              |  Redirect to `/gutenberg/post/:site`             |
| `/post/:site`   |   No              |  Calypso editor with opt-in sidebar visual, dialog closed            |
| `/gutenberg/post/:site`   |   Yes              |  None (we're happy)             |
| `/gutenberg/post/:site`   |   No              |  Calypso editor with opt-in sidebar visual, dialog open (alternate: Gutenberg editor and quietly set the blog sticker, but this could look sneaky)            |

@gwwar suggests above to maybe push the user to choose, but I'd rather avoid this; it would require both disabling the three dismissal methods ("X", clicking outside the dialog, and pressing the `ESC` key), and actively tracking opt-outs (if we force someone to choose, we need to respect it on later loads). I'd also rather not mess with modal dismissal for the sake of a11y consistency throughout Calypso.

**Comment by gwwar** [comment]
> In general, I'm assuming that we will not explicitly be saving an "opt out" selection

That will be for a later phase when we default folks on Gutenberg, and provide an opt-out.

> Calypso editor with opt-in sidebar visual, dialog open (alternate: Gutenberg editor and quietly set the blog sticker, but this could look sneaky)

For the last case, I think we could try it, but if they dismiss the modal in the case where folks go to the route directly, we need to ensure that we set the blog sticker, if they dismiss the editor without making a choice (or redirect them to classic which may be jarring).

> @gwwar suggests above to maybe push the user to choose

I actually forgot my original reasoning. Maybe something around dismissing the modal for an X interval? 🤔

**Comment by gwwar** [comment]
Oh and another case for VIP, let's make sure they don't see these flows/don't get stickered

**Comment by kwight** [comment]
Calypso has been using the user-centric opt-in since the merge of #27892 , and wp-admin now also uses the user-centric opt-in as of merging D20226-code yesterday. Closing.
