### ISSUE TITLE
Janitorial: remove MEDIA_IMAGE_PHOTON from codebase

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27446]
I recently updated the media thumbnails to not use Photon in https://github.com/Automattic/wp-calypso/pull/27412

There was a review comment by @ramonjd which I'll raise as as a separate issue to work on so I can merge the PR as it is:

> If we're no longer using this constant for images, perhaps it's a good chance to cull it. For example, the default thumbnailType for <ListItemImage /> is still MEDIA_IMAGE_PHOTON.
> 
> I'm not sure however how photon relates to videos, but it looks like we're passing down thumbnailType to all <ListItem /> children, so on the face of it, it appears we can change the default type in all child components.
>
> It might be worth doing should we, for any reason, wish to prevent MEDIA_IMAGE_PHOTON from being the default. For example, if the child components don't receive a valid props.thumbnailType.
> 
> If you do decide to change the default type, then we can also get rid of the corresponding tests.

**Comment by rfaile313** [comment]
I'm going to remove all of the lines w/references to this constant. Do these need to be replaced? It seems like based on the context above that thumbnailType is being passed elsewhere.
