### ISSUE TITLE
Purchases: Invalidate purchases data after cancelling a subscription

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#2746]
Right now, when you cancel a subscription from `/purchases`, Manage Purchases is displayed in subscribed state until you refresh things and fetch data again:

![domain](https://cloud.githubusercontent.com/assets/1248436/12554692/066c5c58-c37e-11e5-9c37-12e9834487e7.gif)

This is confusing since the Cancel option is still available, even though I just used it and was told the cancellation was completed successfully.

Tested from #2602.

**Comment by drewblaisdell** [comment]
This builds on work from #2596 - we need to call `clearPurchases` after canceling a purchase.
