### ISSUE TITLE
Purchases: Add loading page skeleton for Single Purchase pages

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#275]
We need design for Purchase pages loading state. This includes following pages:
- Manage Purchase
- Cancel Purchase
- Confirmation Cancel Purchase
- Edit Payment Method (moved to #843)
- Edit Card Details

As part of this task we should also add redirects for all aforementioned pages when there is no purchase selected.

### Loading Placeholders
@mikeshelton1503 proposed the following mockups:

* [x] Manage Purchase
![screen shot 2015-10-21 at 1 44 21 pm](https://cloud.githubusercontent.com/assets/12596797/10645215/95d3a6d2-77fa-11e5-92ff-1016c04a5c57.png)

* [x] [Cancel Purchase](https://github.com/Automattic/wp-calypso/pull/915)
![screen shot 2015-10-21 at 1 44 29 pm](https://cloud.githubusercontent.com/assets/12596797/10645212/95cfe768-77fa-11e5-89c4-c6400120ce96.png)

* [x] [Confirm Cancel Purchase](https://github.com/Automattic/wp-calypso/pull/1036)
![screen shot 2015-10-21 at 1 44 37 pm](https://cloud.githubusercontent.com/assets/12596797/10645211/95cfb784-77fa-11e5-9626-e6e799e40f12.png)

* [x] [Edit Card Details](https://github.com/Automattic/wp-calypso/pull/717)
![screen shot 2015-10-21 at 1 44 52 pm](https://cloud.githubusercontent.com/assets/12596797/10645214/95d27816-77fa-11e5-9ec4-56d6e8b63305.png)

### Page Redirects
* [x] [Perform redirect when user can't access Manage Purchase page](https://github.com/Automattic/wp-calypso/pull/1255)
* [x] [Perform redirect when user can't access Cancel Purchase page](https://github.com/Automattic/wp-calypso/pull/1153)
* [ ] Perform redirect when user can't access Confirm Cancel Purchase page
* [ ] Perform redirect when user can't access Cancel Private Registration page
* [ ] Perform redirect when user can't access Edit Card Details page

### Refactoring tasks
* [x] ~~Create Edit Card Details skeleton that can be shared by loading placeholder and page component~~ - it produced more lines of code, than using duplicated code in case of Edit Card Details page, let's skip it for the time being
* [x] [Move all page titles into one place](https://github.com/Automattic/wp-calypso/pull/1030)
* [x] [Always use selectedSite.slug in urls when referencing site domain](https://github.com/Automattic/wp-calypso/pull/1147)

**Comment by gziolo** [comment]
Manage Purchase page needs some improvements on mobile view:
![screen shot 2015-11-25 at 12 57 59](https://cloud.githubusercontent.com/assets/699132/11396780/885a5100-9374-11e5-972a-f34eeec25d1b.png)

**Comment by fabianapsimoes** [comment]
> Manage Purchase page needs some improvements on mobile view:

That's being fixed in #670.

**Comment by gziolo** [comment]
Page skeleton for Edit Payment Method page moved to #843.

**Comment by gziolo** [comment]
@scruffian I was trying to accomplish refactoring: `Create Edit Card Details skeleton that can be shared by loading placeholder and page component`.
I ended up producing more lines of code, than using duplicated HTML code in case of Edit Card Details page, let's skip it for the time being. Feel free to revisit it in the future. I hope you can come up with some nice optimisation :)

**Comment by scruffian** [comment]
@gziolo IMO its worth having more lines to reduce duplication. I anticipate people forgetting to update skeletons in the future when they update a page...

**Comment by gziolo** [comment]
This is still work in progress. All loading placeholders are done. I started working on handling page redirects when there are cases like:
* purchase was removed but we try to access page using old url
* we enter the page that shouldn't be loaded for the given purchase

I'm not quite sure how we should handle the case when site's domain has changed, and user tries to load purchase page with old url. Sites list returns no data at the moment causing issues in placeholders.

@fabianapsimoes I think it'd be good to revisit if we want to implement those redirects in v1.

**Comment by fabianapsimoes** [comment]
@gziolo could you open a new issue describing this issue? Then we can discuss it and prioritize in a different thread.

**Comment by gziolo** [comment]
@fabianapsimoes: issue created: https://github.com/Automattic/wp-calypso/issues/1407, I don't think it's very important, but it would be nice to find solution for this edge case.

**Comment by fabianapsimoes** [comment]
I've reported the missing page redirects in this issue in #2519. Closing this issue.

**Comment by gziolo** [comment]
:+1:
