### ISSUE TITLE
Improve the PulsingDot component displayed when section is loading

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#27528]
When a section is loading for longer than 400ms, we consider that too long. A tracks event is reported and we display a `PulsingDot` component in the center of the masterbar to indicate that load is in progress.

There are two issues with `PulsingDot`:
- it's displayed immediately rather than after 400ms. It used to work correctly and then someone accidentaly broke it long time ago. Let's do a fix!
- post editor has a "distraction free mode" where the masterbar is hidden. When navigating from post editor to another section, a `PulsingDot` with a masterbar-blue background is displayed. That looks visually very broken. Can we fix this, too?

**Comment by flootr** [comment]
seems like the second problem is due to a mismatch between `z-index`es
