### ISSUE TITLE
Optimize Woo shipping zone selectors

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#27546]
Take a look at selectors in `client/extensions/woocommerce/state/ui/shipping/zones/locations/selectors.js`. Can you find any optimization opportunities?

Do they always return identical objects (e.g., `[]`) when state and parameters are identical?

What if I do several calls with different `siteId` and `zoneId` parameters? Are the results properly memoized?

**Comment by nerdysandy** [comment]
As per the labels this is related to Store. We're sunsetting Store by Feb,2021. Closing it in favour of that
