### ISSUE TITLE
Framework: redux sites contains functions

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#2757]
The sites module in the redux state tree is not a simple object and contains references to functions. ~~This is blocking redux state persistence in #2754~~

To see this, inspect `reduxStore.getState().sites`: 
<img width="352" alt="function" src="https://cloud.githubusercontent.com/assets/1270189/12562805/e300ba1a-c35b-11e5-893f-a4fb5a655907.png">

**Comment by aduth** [comment]
Likely a result of calling the `receiveSite` action with an object which has been processed by `lib/sites-list` to include additional handlers - https://github.com/Automattic/wp-calypso/blob/41662830d82c3b95c9c20614b577dc20f7b06518/client/my-sites/controller.js#L137

**Comment by gwwar** [comment]
We also have full moment instances on sites.plans
<img width="428" alt="moment" src="https://cloud.githubusercontent.com/assets/1270189/12601138/9fcf6496-c453-11e5-95df-a4ad2e2121d5.png">

**Comment by rralian** [comment]
@gwwar Can we close this issue, since there are separate tasks to address this in the serialize/deserialize actions?

**Comment by gwwar** [comment]
It's slightly different. For example currently sites are persisted, but the way the data is received and stored hasn't been cleaned up.

**Comment by rralian** [comment]
I think this issue is just a flavor of `sites` being one of our earliest and ugliest pieces in the data layer. I think this needs to be addressed at some point as part of regular cleanup (albeit a big cleanup task), but I'm removing it from the offline iteration.

**Comment by aduth** [comment]
At the very least, we should try to whitelist attributes when receiving a site into the Redux store in the immediate future. There are conflicts in doing this, as some sections of the application are already using Redux site state and expecting it to contain the computed properties. This should be a near-term focus, as it will only become more difficult with time.

I'll see if I can slice off some time in the next week to take a closer look.
