### ISSUE TITLE
Framework: redux themes contains immutable.js objects

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#2759]
The themes module uses immutable.js. ~~Mixed usage is blocking redux state persistence in #2754 since that section of the tree should be an immutable.js instance rather than a plain js object.~~ When redux state is deserialized, you will see errors like the following:

<img width="692" alt="deserialize" src="https://cloud.githubusercontent.com/assets/1270189/12563241/20448b34-c35e-11e5-8760-19db4fff47b4.png">

Inspecting `reduxStore.getState().themes` shows:
<img width="699" alt="instance" src="https://cloud.githubusercontent.com/assets/1270189/12563266/47532df2-c35e-11e5-819a-bc9421b0863a.png">

**Comment by ehg** [comment]
Is this a bug? We're using immutable.js data structures :)

**Comment by gwwar** [comment]
@ehg maybe bug is a little harsh for this one. Feel free to chime in on #2754 and comment on whether we should push for using immutable.js everywhere, allowing it on sub trees, or if we should stick with plain js objects. ;)

**Comment by gwwar** [comment]
I went ahead and persisted the themes subtree in #2754, @ehg if you have time I'd appreciate some :eyes: on if I got the schemas correct in the themes subtree.
