### ISSUE TITLE
Reader: Hide Share option for posts from private sites

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#2760]
Current, we show a Share button for private sites:

![screen shot 2016-01-25 at 3 25 07 pm](https://cloud.githubusercontent.com/assets/191598/12563338/d4b2c324-c377-11e5-88ab-68f9e5ed3956.png)

The options included for sharing are WordPress, Facebook, and Twitter:

![screen shot 2016-01-25 at 3 25 24 pm](https://cloud.githubusercontent.com/assets/191598/12563355/eebd2f84-c377-11e5-9cb7-0f3f2eecc3aa.png)

Since all three options share the URL to the post (which will be hidden behind a wall for non-users of the site) these aren't really useful—and actually may be a bit of a privacy issue for people who don't expect their post titles/urls to be public information (i.e. shared on twitter).

We should remove the share option for private sites.

**Comment by nb** [comment]
Fixed in #2773.
