### ISSUE TITLE
Editor: Design: Borders not consistent between HTML and Visual modes

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#2762]
On Visual mode there's no delimiter under the Title area, but when you switch to HTML mode, there is. Not sure which one is correct but they should probably match?

![screen shot 2016-01-25 at 3 23 03 pm](https://cloud.githubusercontent.com/assets/52152/12565050/4886f75c-c378-11e5-8f93-2f02aa08286d.png)

![screen shot 2016-01-25 at 3 23 10 pm](https://cloud.githubusercontent.com/assets/52152/12564984/e87e14a8-c377-11e5-81c3-aa48f6c69975.png)

cc @mtias

**Comment by mtias** [comment]
Yeah, we need to build the quick-buttons for html mode. Until then I think it's ok as it is.

**Comment by dreamertim** [comment]
Speaking of borders, would it be possible to add a border around the content section? When the cursor starts in the title section, there is not a great indicator (as a non-tech user) as to where the next place to go would be.

**Comment by rachelmcr** [comment]
Closing as this will be superseded by Gutenberg's block-level visual/HTML switching.

#bug-scrub #pre-gutenburg-bug-purge
