### ISSUE TITLE
Gutenberg: List Block indent/outdent

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27637]
Appears to render appropriately on the Simple Site published view. There may be glitches in the editor:

@vindl could you clarify what you mean by: 

> I was unable to ident/outdent the list item in order to produce nested lists.

**Status**

Works fine through `wp-admin` but not indenting or outdenting list items in Calypso when clicking on buttons or using keyboard shortcuts. No console errors.

**Comment by vindl** [comment]
@gwwar in our integration it's not possible to achieve this in the editor:

<img width="680" alt="screen shot 2018-10-09 at 18 37 21" src="https://user-images.githubusercontent.com/1182160/46684253-93faa000-cbf2-11e8-9bf4-4285002e2bd2.png">

**Comment by dmsnell** [comment]
Noting that lists aren't producing any errors in the console.
The core blocks call this:

```js
if ( this.editor ) {
	this.editor.execCommand( command );
}
```

it's possible we have a race condition with `this.editor` loading; I'll investigate more later
