### ISSUE TITLE
Gutenberg: Quote/Cover Image

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27638]
From @vindl's audit in https://github.com/Automattic/wp-calypso/issues/27294

>Quote: - The editing screen should match what users see on the front end when they publish a post. That's not the case because current themes were not developed with Gutenberg editor in mind.

> Cover Text - It's not rendered on the front-end correctly: the image is cropped to cover text container height, or it's not shown at all if there is no cover text.

> Pull Quote: there is a similar problem as with regular quote block. It looks different in editor and on front end due to different theme styling.

This seems out of scope to me, but verify with the Gutenberg core team if this behavior is expected for this phase.

**Comment by vindl** [comment]
The Quote and Pull Quote issues are no longer present after the investigation in https://github.com/Automattic/wp-calypso/issues/27635.

Cover image is partly solved by the above too, and partly by recent Media library addition.
