### ISSUE TITLE
Gutenberg: update demo content copy

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27648]
Follow up to #27484, let's work with Editorial, Marketing and @shaunandrews to craft copy and think of which blocks we'd like to highlight

**Comment by gwwar** [comment]
See related D18888-code

**Comment by shaunandrews** [comment]
I worked up a demo post here: https://conceptualwig.wordpress.com/2018/12/04/say-hello-to-the-new-editor/

I tried to use the demo post as a way to showcase various blocks in action and used the content to help educate what blocks are, and why they're better than the old way.

To get a real sense of how it would work, you'll need to edit that post in Gutenberg. If you're unable to do that, let me know and I can add you to that site.

/cc @michelleweber

**Comment by michelleweber** [comment]
I'm working on some different/additional copy for that post this week, to add a little more education in a (hopefully) fun way. If anyone has other suggestions for blocks they'd particular like to highlight, I'm more than happy to work them in!

**Comment by gwwar** [comment]
Closing for staleness
