### ISSUE TITLE
Gutenberg: Instagram Embed

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27647]
Let's make sure that we can see the preview in the editor.

**Comment by notnownikki** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/10434

**Comment by vindl** [comment]
Thanks for pointing that out @notnownikki! I'm closing this out for now since it should be handled by our upcoming package update in https://github.com/Automattic/wp-calypso/issues/27649. If not, we can reopen the issue later.
