### ISSUE TITLE
Gutenberg: add support for dynamic blocks

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27646]
Dynamic blocks like Archives, Latest comment, Categories, and Latest posts aren't rendering appropriately on the published page, because we're missing the needed php callbacks on the wpcom side. Let's add them!

https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/

(Some blocks appear to render correctly in the front end but not in the editor).

**Comment by vindl** [comment]
Just a note that all of these were rendering correctly on front end in my latest tests. There are still some problems with Archives and Latest Comment on the editor side though.
