### ISSUE TITLE
Gutenberg: should we add the opt-in flag when folks visit the /gutenberg route directly?

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27650]
The site picker isn't currently aware of Gutenberg enabled sites.

Should we try filtering this list, or opting-in folks when they visit the route directly?

**Comment by gwwar** [comment]
Maybe show the opt in modal in this case?

**Comment by dmsnell** [comment]
I vote that we close this issue as `won't fix` because of how we're changing the rules of opt-in to be user-based instead of site-based.

Augmenting the site list will also obviously have performance implications, though for the most part it won't effect single-site accounts noticeably.

**Comment by gwwar** [comment]
Yup, thanks for the reminder!

**Comment by gwwar** [comment]
See more information in: p7jreA-1R9-p2
