### ISSUE TITLE
Store: Inform the user about what a HS tariff code is and why is it important

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#27683]
As a follow-up to https://github.com/Automattic/wp-calypso/pull/27682, it would be good to inform the user of why the HS tariff code is important to include in a Customs form, but it's optional.

This is what Easypost has to say about it (thanks @jeffstieler for reaching out to them):
> Although the HS Tariff number is not usually required,  we recommend using the tariff codes to avoid certain scenarios...
>
> Delays:  Not classifying your goods will cause the importing country to spend time manually classifying the goods on their end.
> Denials: Each importing government has its own unique restrictions in place to protect local markets. While there are some products that are perfectly fine to export in one market, they might very well be denied in another.

Current UI:
![screenshot 2018-10-09 at 16 14 32](https://user-images.githubusercontent.com/1715800/46679279-8affd380-cbde-11e8-866e-b5f5f5634d58.png)

That `look up` link points to `https://hts.usitc.gov/`, where the merchant can input a keyword and find the tariff code for that kind of product.

I suggest we change that link for a `help` of `more info` link, pointing to a page on docs.woocommerce.com. That page should at least include an explanation like the one above (what is a tariff code, why is it optional, why is it recommended), and a link to `https://hts.usitc.gov/` so the merchant can search for it. Thoughts?

cc/ @Automattic/hydra 

@californiakat I've noticed that our pages on docs.woocommerce.com are kind-of "high-level" overviews of what our product can do, instead of comprehensive guides. Is that intentional? Would it be a bad precedent to add a new doc page with just this tiny thing?

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
