### ISSUE TITLE
Gutenberg: Featured Image setting missing from editor sidebar

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#27691]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Start a new post

#### What I expected
I expected to see the sidebar settings matching the existing settings

#### What happened instead
In the sidebar the featured image section is missing

#### Browser / OS version
All

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/31110506/46696801-4bca8600-cbd0-11e8-89ad-de6f852eab3f.png)

**Comment by thehenrybyrd** [comment]
Glad to see there's an issue for this already! 
Did a little testing today and this was one of the first things I noticed - vital for posts within our current themes.

**The same is true on pages.** Currently, going to https://wpcalypso.wordpress.com/gutenberg/page and starting a new page on a simple site yields the following:

<img width="304" alt="screen shot 2018-10-18 at 4 00 47 pm" src="https://user-images.githubusercontent.com/15107387/47156121-1704b000-d2ef-11e8-8ec6-eb70e120ad3d.png">

in comparison with the current sections for a new page on a simple site:

<img width="296" alt="screen shot 2018-10-18 at 4 01 12 pm" src="https://user-images.githubusercontent.com/15107387/47156169-2e439d80-d2ef-11e8-89ee-02554a7d9bbb.png">

**Here's a comparison of all features in Page Settings in Calypso, vs. Gutenberg in Calypso at https://wpcalypso.wordpress.com/gutenberg/page:**

![calypsovsgutenlypsopagesettings](https://user-images.githubusercontent.com/15107387/47158787-0f480a00-d2f5-11e8-912e-692cf363689f.png)

Missing from Page settings are Featured Image, Sharing, Slug (though I see it’s possible to edit this above the Page Title) Location, Allow Pingbacks & Trackbacks, and Copy Post.

**And here's the same for Post Settings, compared with Gutenberg in Calypso at https://wpcalypso.wordpress.com/gutenberg/post:**

![calypsovsgutenlypsopostsettings](https://user-images.githubusercontent.com/15107387/47158035-651bb280-d2f3-11e8-9632-1732603c52f0.png)


Missing from Post settings are Featured Image, Sharing, Slug (though I see it’s possible to edit this above the Post Title) Location, Copy Post.


@bsessions85 Let me know if Page discrepancies should be reported elsewhere.

**Comment by vindl** [comment]
Featured image has been introduced with the plugin update to 4.1.0 on WP.com. As for the other discrepancies between Calypso vs Gutenberg settings - for the first phase we are aiming to replicate the Core look so differences with Calypso's sidebar are expected.
