### ISSUE TITLE
Gutenberg: Embeds: Vine embed doesn't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27705]
Note: Vine is in read-only mode with no new content so setting as Low Priority

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Paste a Vine link such as https://vine.co/v/MMunvnTeudw

#### Gutenberg in Calypso Result

<img width="807" alt="screen shot 2018-10-10 at 11 48 30 am" src="https://user-images.githubusercontent.com/128826/46708551-8bea4100-cc82-11e8-913c-1efe6927d1ad.png">

#### Calypso Editor Result

<img width="788" alt="screen shot 2018-10-10 at 11 48 35 am" src="https://user-images.githubusercontent.com/128826/46708555-91478b80-cc82-11e8-9a97-621abdf283ce.png">

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

**Comment by codebykat** [comment]
This is working now.
