### ISSUE TITLE
Gutenberg: Embeds: Audio shortcodes/embed don't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27706]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Add an audio block either adding existing URL like http://en-support.files.wordpress.com/2014/10/istock_audio.wav or uploading file

#### Gutenberg in Calypso Result

1. Shows audio block - controls don't work
2. On preview/publish this doesn't display in page

<img width="770" alt="screen shot 2018-10-10 at 12 06 32 pm" src="https://user-images.githubusercontent.com/128826/46708989-e71d3300-cc84-11e8-9f68-ad89f9d3c7a8.png">

I can't work out how to use existing media

#### Calypso Editor Result

1. Shows shortcode
2. Works on preview/publish

<img width="784" alt="screen shot 2018-10-10 at 12 07 09 pm" src="https://user-images.githubusercontent.com/128826/46709000-fc925d00-cc84-11e8-9e35-68050363c45d.png">

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

See: https://en.support.wordpress.com/audio/

**Comment by alisterscott** [comment]
@gwwar I think this warrants a High Priority since audio blocks don't seem to work at all - even on preview and publish

**Comment by vindl** [comment]
Resolved in https://code.a8c.com/D19531.

**Comment by alisterscott** [comment]
Thanks for the fix @vindl 

Confirmed working on preview/publish

<img width="502" alt="screen shot 2018-10-22 at 1 24 39 pm" src="https://user-images.githubusercontent.com/128826/47276864-ca2a1d80-d5fd-11e8-8d31-e58f99ee99ee.png">

**Comment by alisterscott** [comment]
Thanks for the fix @vindl 

Confirmed working on preview/publish

<img width="502" alt="screen shot 2018-10-22 at 1 24 39 pm" src="https://user-images.githubusercontent.com/128826/47276864-ca2a1d80-d5fd-11e8-8d31-e58f99ee99ee.png">

**Comment by alisterscott** [comment]
Thanks for the fix @vindl 

Confirmed working on preview/publish

<img width="502" alt="screen shot 2018-10-22 at 1 24 39 pm" src="https://user-images.githubusercontent.com/128826/47276864-ca2a1d80-d5fd-11e8-8d31-e58f99ee99ee.png">

**Comment by alisterscott** [comment]
Thanks for the fix @vindl 

Confirmed working on preview/publish

<img width="502" alt="screen shot 2018-10-22 at 1 24 39 pm" src="https://user-images.githubusercontent.com/128826/47276864-ca2a1d80-d5fd-11e8-8d31-e58f99ee99ee.png">
