### ISSUE TITLE
Gutenberg: Embeds: Getty Images embed doesn't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27708]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Paste some Getty Images embed code like:

`<div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:Roboto,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:509px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com.au/detail/862515172" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:66.60118% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/862515172?et=vYmOdmtBS456fnJhLSKGMA&tld=com.au&sig=-m4quuP_oYkynGLLigAP6dTc7hEyp584GuXLdn02f-U=&caption=true&ver=1" scrolling="no" frameborder="0" width="509" height="339" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div></div>`

#### Gutenberg in Calypso Result

<img width="713" alt="screen shot 2018-10-10 at 2 39 37 pm" src="https://user-images.githubusercontent.com/128826/46713492-4b96bd00-cc9a-11e8-8ef1-a95b6957762f.png">

#### Calypso Editor Result

<img width="828" alt="screen shot 2018-10-10 at 2 40 13 pm" src="https://user-images.githubusercontent.com/128826/46713505-5e10f680-cc9a-11e8-992b-64bd1b56af76.png">

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

**Comment by cecoates** [comment]
This is affecting more than just the Calypso view, but after the 5.0 update and switching AT sites to Gutenberg, all of this site's Getty embeds are broken:

https://puck77.com/

Embeds are now all display an "Image not found" error like this:

![screen shot 2018-12-07 at 15 33 56](https://user-images.githubusercontent.com/10121835/49673873-9122fc80-fa35-11e8-8afa-1a33c6ba61bc.png)

To fix it, each individual image has to be edited in the Classic Editor and updated. Which is extremely labor intensive. For example, this is the process to fix the images in a single post:

https://d.pr/jQyPvV

**Comment by JavonDavis** [comment]
cc @gwwar

**Comment by codebykat** [comment]
Confirmed this is still an issue. If you publish the post it does get converted to a shortcode that works.

**Comment by gwwar** [comment]
Works using an html block to paste the shortcode in the editor:

<img width="672" alt="Screen Shot 2019-10-28 at 5 26 07 PM" src="https://user-images.githubusercontent.com/1270189/67727838-2dd0ee80-f9a8-11e9-8f9a-6abccf922ab1.png">

Published View:
<img width="586" alt="Screen Shot 2019-10-28 at 5 26 14 PM" src="https://user-images.githubusercontent.com/1270189/67727847-3295a280-f9a8-11e9-9fe8-1ee8ad5c7574.png">

On Second Edit we see that it was converted to a shortcode:
<img width="789" alt="Screen Shot 2019-10-28 at 5 26 55 PM" src="https://user-images.githubusercontent.com/1270189/67727857-3aeddd80-f9a8-11e9-8ecb-1f9617458c41.png">

Please reopen if folks have trouble
