### ISSUE TITLE
Gutenberg: Embeds: Facebook embed doesn't show preview

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27701]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Paste a Facebook post link such as https://www.facebook.com/hollybutcher90/posts/10213711745460694

#### Gutenberg in Calypso Result

<img width="771" alt="screen shot 2018-10-10 at 11 22 50 am" src="https://user-images.githubusercontent.com/128826/46707793-d36ece00-cc7e-11e8-89d4-325d842c3de1.png">

#### Calypso Editor Result

<img width="805" alt="screen shot 2018-10-10 at 11 24 51 am" src="https://user-images.githubusercontent.com/128826/46707847-1761d300-cc7f-11e8-983f-a9c7f9deea16.png">

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

**Comment by codebykat** [comment]
This is a Gutenberg core issue that is being tracked here: https://github.com/WordPress/gutenberg/issues/8360

Since the embed itself renders after publishing, I don't think there's anything we can or need to do here.

**Comment by gwwar** [comment]
Reopening to keep track of reports. If needed we can fix this ahead of core.

**Comment by jjchrisdiehl** [comment]
Another case here 9724873-hc

Customer tried embedding their facebook page and received Sorry, we cannot preview this embedded content in the editor.

**Comment by zdenys** [comment]
Another case 2089010-zen

Tested with a different Facebook Page. Embedding a page URL, like `https://www.facebook.com/AutomatticInc/` doesn't work and shows `Sorry, this content could not be embedded.`:

![](https://cld.wthms.co/JrNSOT+) 

Embedding an individual post, like `https://www.facebook.com/AutomatticInc/posts/998273493676267` works

![](https://cld.wthms.co/LdAESY+)

Is it expected behavior? It seems it is.

**Comment by selectedselections** [comment]
Hi there! I received another report of this issue here: 2170294-zen
User's facebook page link embed looks like this [#](https://cld.wthms.co/Ilf6pp)
The same is true for instagram: [#](https://cld.wthms.co/zR49Sl)

Publishing does not resolve the issue. 

Embed issue reproduced on a test site: [#](https://cld.wthms.co/D5lsBM)

**Comment by taropaa** [comment]
I am running into the same issue. Embedding a generic facebook page will just display a text URL that is not even clickable. 
To make things worse, I can't paste a facebook page URL without it being converted into a broken embed. If default profiles can't be embedded, then just leave the URLs alone. In this particular instance, it works completely against the user and will drive a less experienced user insane, who just wants to paste a facebook link.

**Comment by formosattic** [comment]
+1 15689980-hc

The _"Embedded content from facebook.com can't be previewed in the editor."_ 
message is viewed as an error which makes it sound like the embed is broken even though it'll still display on the site.

**Comment by gwwar** [comment]
This should be on the WP whitelist, though https://github.com/WordPress/gutenberg/issues/8360 is still open.

I'm still seeing the following on a standalone install. We'll need to make a core PR

<img width="865" alt="Screen Shot 2019-10-28 at 5 17 53 PM" src="https://user-images.githubusercontent.com/1270189/67727556-18a79000-f9a7-11e9-8c33-346c69ddf7aa.png">

**Comment by davipontesblog** [comment]
@lancewillett do you think this is something we could prioritize in dotCom vs core, or help with efforts in core to fix the issue? Context: this used to be possible in the classic editor.

**Comment by lancewillett** [comment]
@davipontesblog Let's help push the fix "upstream" meaning in core first.

(CC @mtias as an example where WP.com can help make a core change, then merge it back to our platform later.)

**Comment by ockham** [comment]
Ran into this today on WP.com (thanks to a . Couldn't repro in Core however -- it seems to work there now :thinking: 

WP.com (with GB 8.9.3):

![image](https://user-images.githubusercontent.com/96308/93332631-68db4b00-f822-11ea-8b30-cd48bad73888.png)

Local vanilla GB install:

![image](https://user-images.githubusercontent.com/96308/93332450-231e8280-f822-11ea-8aec-d8c5b39fbbad.png)

The difference seems to lie in the `previewable` attribute, which isn't set in vanilla GB, but on WP.com is set to `false`.

**Comment by ockham** [comment]
Hmm, maybe that's expected/consistent. The FB embed hard-wires the `previewable` attribute to `false` here: https://github.com/WordPress/gutenberg/blob/f3cdac3726638604ecb9bef639db13a755acaf1b/packages/block-library/src/embed/variations.js#L70

But in 9.0, the FB embed was "removed": https://github.com/WordPress/gutenberg/pull/24472

This means that inserting an FB URL will now create a "generic" embed -- which doesn't have `previewable` set.

**Comment by ntsekouras** [comment]
>not sure what the original motivation for setting previewable to false was)

When I refactored `embed` to use block variations that setting (`previewable: false`) was there before. I don't have the context for that decision..

**Comment by mkaz** [comment]
@ntsekouras I'm not sure about the setting either.

**Comment by ntsekouras** [comment]
> https://github.com/Automattic/wp-calypso/issues/27701#issuecomment-693373999

-cc @youknowriad @mcsf @ellatrix @jorgefilipecosta 
Do you have any context for the motivation for setting `previewable` to `false` for FB embed?  Thanks!

**Comment by mcsf** [comment]
> Do you have any context for the motivation for setting `previewable` to `false` for FB embed? Thanks!

I have no knowledge about this. Some of the people who did the most work on Embeds haven't been around in a while, either.

**Comment by ockham** [comment]
Could it be a privacy/GDPR thing? Do oEmbeds do any sort of non-GDPR compliant tracking? (Would be kinda surprising tho...)

**Comment by ockham** [comment]
Tracked it down to this PR, which seems to be where the FB embed block was first introduced (and added to a `noPreview` array, which seems to be the predecessor of the `previewable` attribute): https://github.com/WordPress/gutenberg/pull/816#issuecomment-305132046:

> Also, previewing facebook embeds is disabled, because fb scripts want to change global things about the document they're running in (which the sandboxing iframe highlighted and wouldn't allow).

**Comment by worldomonation** [comment]
Removing the Stale label as Facebook (among other media embeds) continue to provide less than ideal experience.

When embedding a link, the block turns to a simple paragraph of the embedded URL. The blocks do not render as expected in Preview nor in Published mode.

**Comment by worldomonation** [comment]
Removing Stale label.

However, upstream issue https://github.com/WordPress/gutenberg/issues/8360 is now closed with comment:

```
> This can be closed since facebook is no longer supported in the embed block because of their api changes. [87c4dc5](https://github.com/WordPress/gutenberg/commit/87c4dc536f52254975b4b5e192e36f7d98b6f0b7)
```

Given this development, either we develop our own fixes for this block, or remove the Facebook embed block entirely.

**Comment by danielbachhuber** [comment]
> Given this development, either we develop our own fixes for this block, or remove the Facebook embed block entirely.

@vindl Given the above ^, did you have an opinion on how we'd resolve this issue?

**Comment by vindl** [comment]
> @vindl Given the above ^, did you have an opinion on how we'd resolve this issue?

It would probably make more sense to develop our own fixes or version of this block. However, this falls into new feature development territory a bit, so I'll assign it back to the team that's owning the Blocks work. They might be in a better position to make this call.

**Comment by jeherve** [comment]
Closing this in favor of https://github.com/Automattic/jetpack/issues/35826 since the Facebook embed block is now part of Jetpack.
