### ISSUE TITLE
Gutenberg: Embeds: Google+ embed doesn't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27704]
**Note**: Google+ is being [sunsetted](https://plus.google.com/+googleplus/posts/ENCsBdhZC4W) so this is being set as Low Priority

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Paste a Google+ post link such as https://www.pinterest.com/pin/373869206564305678/

#### Gutenberg in Calypso Result

<img width="748" alt="screen shot 2018-10-10 at 11 42 50 am" src="https://user-images.githubusercontent.com/128826/46708422-dfa85a80-cc81-11e8-9f5a-f599b73d4317.png">

#### Calypso Editor Result

<img width="893" alt="screen shot 2018-10-10 at 11 42 59 am" src="https://user-images.githubusercontent.com/128826/46708427-e636d200-cc81-11e8-8437-284e109d973b.png">

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

**Comment by simison** [comment]
Google is being sunsetted earlier than they initially announced: https://www.blog.google/technology/safety-security/expediting-changes-google-plus/

API access will be shut down in early March.

Hence, I don't think we should spend time implementing this?

Related: p1HpG7-61o-p2

**Comment by codebykat** [comment]
Yeah no real point to fixing this.
