### ISSUE TITLE
Gutenberg: Embeds: Pinterest embed doesn't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27702]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Paste a Pinterest post link such as https://www.pinterest.com/pin/373869206564305678/

#### Gutenberg in Calypso Result

<img width="745" alt="screen shot 2018-10-10 at 11 30 04 am" src="https://user-images.githubusercontent.com/128826/46707988-d3230280-cc7f-11e8-81a2-213b026a20e4.png">

#### Calypso Editor Result

<img width="801" alt="screen shot 2018-10-10 at 11 30 34 am" src="https://user-images.githubusercontent.com/128826/46707997-dfa75b00-cc7f-11e8-85ab-f8a7e680aa43.png">

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

**Comment by alisterscott** [comment]
Should be fixed by https://github.com/WordPress/gutenberg/pull/10434

**Comment by eduardozulian** [comment]
Also reported on 1686948-hc

I tested on my end (wpcom site with Gutenberg and Calypso) and I'm seeing a different error: 

<img width="582" alt="captura de tela 2019-01-09 as 19 35 46" src="https://user-images.githubusercontent.com/1136160/50929984-dc219c80-1445-11e9-9c3b-9ca92b4d71c7.png">

**Comment by codebykat** [comment]
I can't reproduce any errors with this now. If anyone still can, feel free to re-open with more specific steps to reproduce.

**Comment by OksanaRomaniv** [comment]
I have the same issue on fresh WP install with pin URL.

## Details:
WP: Version 5.2.2
Theme: Twenty Nineteen 1.4
Browser: Chrome Version 75.0.3770.80 (Official Build) (64-bit) 
OS: Ubuntu 18.04

## Error
The block gives "Sorry, this content could not be embedded." error. In console: oembed_invalid_url message from the oEmbed proxy.

## Steps to reproduce
1. Create a fresh install of WP (version 5.2) with a default Twenty Nineteen
2. Go to post editor
3. Paste the Pinterest link (I'm testing with https://www.pinterest.de/pin/442549100879914719/)
4. See the "Sorry, this content could not be embedded." error of embed block

## Screenshots

[screenshot1](https://drive.google.com/file/d/1vFW4xBwPwwD4KpGFgZznghpKqjJn8ImW/view?usp=sharing)
[screenshot2](https://drive.google.com/file/d/1TdXvhrbGtw9Q9LNKP3XjanazoGr6MJIs/view?usp=sharing)
