### ISSUE TITLE
 Gutenberg: Reusable block: Remove from Reusable Blocks remove complete block

### ISSUE THREAD

**Issue by Stojdza** [Automattic/wp-calypso#27722]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Create Paragraph block
3. Select More options -> Add to Reusable Blocks -> Save
4. Select More options -> Remove from Reusable Blocks -> Confirm

#### What I expected
That block is not Reusable Block anymore and it should stay in Editor

#### What happened instead
Complete block is removed from Editor
NOTE: From confirmation window is clear that block will be deleted. but from More options menu it looks like that block will only be removed from reusable blocks. 

#### Browser / OS version
Chrome 69 / OS X

#### Screenshot / Video
<img width="773" alt="screen shot 2018-10-10 at 14 23 47" src="https://user-images.githubusercontent.com/7116222/46747640-20b86300-ccb2-11e8-9280-b5e2c1c5b55c.png">
<img width="861" alt="screen shot 2018-10-10 at 14 23 55" src="https://user-images.githubusercontent.com/7116222/46747647-244bea00-ccb2-11e8-8a35-fd3585384d5b.png">

**Comment by gwwar** [comment]
Are you noticing different behavior from what's in Gutenberg core?

**Comment by vindl** [comment]
@Stojdza in that case could you please [report this in Gutenberg core repo](https://github.com/WordPress/gutenberg/issues/new/choose)? 

Closing for now since we can't really fix this in Calypso integration given that it's coming from core.

**Comment by Stojdza** [comment]
@vindl Done! https://github.com/WordPress/gutenberg/issues/12791
