### ISSUE TITLE
Purchases: Domain Mapping Cancellation & Refund timeframe

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#2776]
According to the [Refund support page](https://en.support.wordpress.com/refunds/), only domain registration are subject to a 48-hours cancel and refund period.

The cancellation and refund timeframe for domain-mapping only purchase should be fixed to 30 days, and not two, as it's currently the case.
![selection_53jj4](https://cloud.githubusercontent.com/assets/15944096/12573163/91bfedd0-c430-11e5-97f0-09594fd183de.png)

**Comment by fabianapsimoes** [comment]
This was fixed in D1108-code via the backend.
