### ISSUE TITLE
Editor: Feedback Should Not Have A Link To View In A New Tab

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#27774]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/types/feedback/example.com
2. Click on a submitted feedback
3. Click the icon near the top right of the editor:
![feedback-image](https://user-images.githubusercontent.com/3505172/46760958-f4dcb380-cc98-11e8-951f-e38c2012932c.jpg)
4. Browser goes to a 404 error page because Feedback is not a public post type.

#### What I expected
There should be no icon to open the feedback on the site in a new tab

Reported in #1476849-zen

**Comment by arunsathiya** [comment]
This is no longer an issue with https://github.com/Automattic/wp-calypso/pull/30799 merged. The `Feedback` section on Calypso sidebar shall take one to wp-admin. 

But, if the user visit https://wordpress.com/types/feedback/ directly, the feedback posts can be opened and the new tab icon can be seen.

I wonder if the new tab icon should be removed before closing this.

Similar issue that can be closed - https://github.com/Automattic/wp-calypso/issues/14511

**Comment by arunsathiya** [comment]
I am closing this because feedback does not open on Calypso anymore. Was changed to open in wp-admin - https://github.com/Automattic/wp-calypso/pull/30799
