### ISSUE TITLE
Importer Stuck: "Processing your file. Please wait a few moments."

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#27775]
Opening a new issue as instructed on [this one](https://github.com/Automattic/wp-calypso/issues/17340) :)

#### Steps to reproduce
We haven't been able to consistently reproduce this issue. But once it's happening to a user, head to https://wordpress.com/settings/, click import, and notice the indicator is spinning along with no end in sight. The JS console does not contain any errors.

#### What I expected
When logs indicate the import is finished and the file deleted, the indicator should reset so the user can import again if needed.

#### What happened instead
The user is not able to start a new import, because the old one appears to still be running.

#### Browser / OS version
Doesn't matter

#### Screenshot / Video

![screen shot 2018-10-10 at 2 28 12 pm](https://user-images.githubusercontent.com/3476361/46764107-cd85e680-cc98-11e8-8804-756e83dd3766.png)

#### Context / Source
Multiple reports; I'll link a few from the past few days. We don't always catch these, because from staff's end, it seems as though the import wrapped up properly. But from the user's view in Calypso, it's stuck.

**Comment by supernovia** [comment]
https://en.forums.wordpress.com/topic/import-stuck-19/

**Comment by supernovia** [comment]
https://en.forums.wordpress.com/topic/import-stuck-20/

**Comment by gemmagarner** [comment]
https://en.forums.wordpress.com/topic/import-hung-up-2/

**Comment by supernovia** [comment]
Another: https://en.forums.wordpress.com/topic/importing-a-site-4/

**Comment by supernovia** [comment]
https://en.forums.wordpress.com/topic/import-cancellation/#post-3195329

**Comment by sixhours** [comment]
We need to investigate whether this is still an ongoing issue and if so, figure out how to reproduce it.

**Comment by lcollette** [comment]
I'm going to close this out as I can't replicate the bug.
