### ISSUE TITLE
Gutenberg: Gallery block layout options

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#27785]
Gallery block works as expected and with #27687 also supports the Calypso media modal.

Although, the Gallery block doesn't have the same layout options as the Calypso gallery shortcode.

Calypso edits the gallery directly inside the media modal as an additional "edit gallery view", where the user can remove and reorder the images, change their captions and link target, and most importantly set a layout (e.g. "tiled mosaic") and optionally the number of columns.

Gutenberg's media modal has an "edit gallery view" as well, but it has no options other than remove, reorder, and change captions.
The actual gallery options are in the block sidebar, but instead of a layout selector, the user can only change the number of columns.

| Calypso | Gutenberg |
| - | - |
| <img width="1169" alt="screenshot 2018-10-11 at 10 54 50" src="https://user-images.githubusercontent.com/2070010/46796329-50b04680-cd44-11e8-9e02-6dcd9a6a3ee3.png"> | <img width="289" alt="screenshot 2018-10-11 at 10 55 14" src="https://user-images.githubusercontent.com/2070010/46796344-59a11800-cd44-11e8-9be1-8ef6d7b414e4.png"> |

**Comment by simison** [comment]
Rest of the layouts will be implemented as part of Tiled Gallery block (on hold currently at  https://github.com/Automattic/wp-calypso/pull/27458).

Once that's in, we should probably default "gallery" to "Tiled gallery" block on wpcom or bridge these two blocks otherwise somehow more tightly.

**Comment by supernovia** [comment]
Requested here: https://en.forums.wordpress.com/topic/galleries-in-new-editor-frustrations/

**Comment by liviopv** [comment]
Also in: #8223771-hc

**Comment by retnonindya** [comment]
A user requested to have the gallery layout in circle layout: #6229588 (HC)

**Comment by sirreal** [comment]
This should be coming to Calypso soon: p1HpG7-65C-p2

**Comment by simison** [comment]
Tiled gallery block with 4 layout options is now available in Calypso. (p58i-7D1-p2):

- squares
- circles
- mosaic
- columns

We didn't implement slideshow layout in this block since it will become its own block.
