### ISSUE TITLE
Gutenberg: Embeds: GitHub Gists embed doesn't show in editor

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27782]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Paste a GitHub Gist link such as https://gist.github.com/2314628
3. Doesn't preview Gist but works on preview/publish

#### Gutenberg in Calypso Result

<img width="763" alt="screen shot 2018-10-11 at 3 43 08 pm" src="https://user-images.githubusercontent.com/128826/46783091-528e0000-cd6c-11e8-95a2-da9508fd1160.png">

#### Calypso Editor Result

<img width="747" alt="screen shot 2018-10-11 at 3 43 28 pm" src="https://user-images.githubusercontent.com/128826/46783125-6e91a180-cd6c-11e8-92ae-851a42be85b1.png">

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

**Comment by atwellpub** [comment]
Also having trouble embedding Gists with new Gutenberg.

**Comment by mmtr** [comment]
This has been fixed by #31196.
