### ISSUE TITLE
Media Library Loads Very Slowly

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#27787]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/143628165 or https://wordpress.com/media/51707092
2. Media loads really really slowly 

#### What I expected
To load normally, didn't notice this problem before

#### What happened instead
Takes ages to load. 

#### Browser / OS version

whatsmybrowser.org/b/YTZ7DLK
Mac OS 10.13.6

#### Screenshot / Video
https://d.pr/free/i/8kjZtS

Found this issue only on Atomic sites.

**Comment by lucasartoni** [comment]
Ticket: 1485517-zen

**Comment by blowery** [comment]
Should be fixed with #27791

**Comment by davoraltman** [comment]
Thanks!
