### ISSUE TITLE
Signup: Browser back button not working in "User First" signup flow

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#27797]
#### Steps to reproduce
1. Ensure you are in the userFirst bucket of userFirstSignup_20180913
2. Starting at URL: https://www.wordpress.com/start
3. Enter and submit user account details
4. Enter and submit site details, making sure to set the site as a store. 
5. Hit the browser back button

#### What I expected
I expected to be taken back to the site details page

#### What happened instead
I was taken to domain selection step

#### Browser / OS version
MacOS Chrome

#### Screenshot / Video
![back-button1](https://user-images.githubusercontent.com/31110506/46823886-a1c43880-cd4c-11e8-965a-b714bfc0355b.gif)

#### Context / Source

This issue was noticed while updating e2e tests to use the new flow that will soon be the default.

**Comment by alisterscott** [comment]
@mattwiebe are you aware of this issue with User First sign up flow?

**Comment by mattwiebe** [comment]
I was not previously aware, no. That's… suboptimal. I'm actually changing some stuff in the way it will work when I ship it for everyone, so we can go from there.

**Comment by mattwiebe** [comment]
The Calypso PR has landed and the canary, ie11, and full suites are all failing. https://github.com/Automattic/wp-calypso/pull/27832

We can continue to test the older flow by appending an appropriate vertical query string (eg `/start?vertical=movie-theater` in the signup URL. Is that a path we'd want to go? 

I'm guessing that adding a new test for the default user-only first step would also be desirable?

**Comment by bsessions85** [comment]
I think we're good for now. We have one test that uses the vertical and it still passes. The back button issue is resolved.

**Comment by michaeldcain** [comment]
Fixed by #27832
