### ISSUE TITLE
Purchases: Handle missing data in payment pages

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#278]
We should redirect users on the `Manage Purchase` page if they attempt to load the `Edit Payment Method` or `Edit Card Details` pages when no payment information is available (e.g. when the upgrade was purchased with credits).

**Comment by drewblaisdell** [comment]
It's fine to load `EditCardDetails` when payment details aren't present. In this case, updating the payment method will update the payment method, regardless of whether the purchase was method with credits. Also, as of #4555, we redirect when the user visits a page for an invalid card ID.
