### ISSUE TITLE
Crash when scrolling long team list

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#27803]
#### Steps to reproduce

This requires a large team, long enough to require lots of scrolling. I made a video I can share in Slack, but don't want to share publicly because it exposes members' names.

1. Starting at URL: https://wordpress.com/people/team/mysite.wordpress.com
2. Scroll all the way to the bottom
3. Page goes blank and error is dumped to console

#### What I expected

Autoload next page of results

#### What happened instead

Crash-o-rama

#### Browser / OS version

Chrome 69, MacOS 10.13.6 (high sierra)

#### Screenshot / Video

Video available on request

<img width="1680" alt="people-scroll-crash" src="https://user-images.githubusercontent.com/51896/46828727-b99dbb80-cd50-11e8-8c38-e0ff147efd5a.png">

**Comment by blowery** [comment]
That error is 
> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
from https://reactjs.org/docs/error-decoder.html/?invariant=185

**Comment by lancewillett** [comment]
Closing in favor of #23937
