### ISSUE TITLE
Stats: the number of WordPress.com Followers doesn't match the real number of .com followers

### ISSUE THREAD

**Issue by daniloercoli** [Automattic/wp-calypso#2780]
Seems that the number of WordPress.com Followers doesn't match the real number of followers when the blog owner is among them.

![screen shot 2016-01-26 at 12 11 39](https://cloud.githubusercontent.com/assets/518232/12579145/ff74405c-c425-11e5-8deb-f563518a5d0a.png)

The label on the top of the module reports 3 followers, but there are 4 items in the list. In this particular case the last item in the list is the owner of the blog, also the first that subscribed to the blog.

**Comment by lancewillett** [comment]
Closing as "works for me" — see also #212
