### ISSUE TITLE
Gutenberg: implement help `?` 

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27802]
This is a task to modify the help component in the Gutenberg section. We'll have want to insert Gutenberg specific support links, opt-out, and the demo launch as they become available. 

![slice_3](https://user-images.githubusercontent.com/1270189/46831126-6713cd80-cd57-11e8-8488-eae3c4e8d76f.png)

**Comment by gwwar** [comment]
Going to kick this back to backlog unless you still wanted this one @rodrigoi

**Comment by danielwrobert** [comment]
FYI, WIP PR can be viewed at #28413.

**Comment by kwight** [comment]
#26595 was closed today with #28863 : 

<img width="453" alt="screen shot 2018-11-27 at 11 04 19 am" src="https://user-images.githubusercontent.com/349751/49105029-6619fb00-f234-11e8-84cf-f3548d14ffba.png">

**Comment by kwight** [comment]
@gwwar do we have any solid design work in progress for this? Maybe we should close out, and open new issues to implement things as design passes finished work to us.

**Comment by gwwar** [comment]
@kwight sure let's use https://github.com/Automattic/wp-calypso/issues/28923 and close this out
