### ISSUE TITLE
Adding media using the "add" button on the toolbar causes the editor to jump to the top of the page

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#27806]
**Steps to reproduce**
Starting at URL: https://wordpress.com/post 
Add content to a new post. Make sure it's enough content so the first line scrolls off the top of the screen.

Click "add" button, click "media", select an image, and click "insert".

**What I expected**
For the post editor to stay where it was (where I added the media).

**What happened instead**
The editor jumped to the top of the post, and I had to scroll down to get back to where I added the media.

**Browser / OS version**
I have tested and replicated this in Chrome on Mac High Sierra 10.13.6

**Screenshot / Video**
http://cld.wthms.co/uoYpGK

**Context / Source**
#user-report
User reported in 1487169-zen 

Bug sounds extremely similar to this open issue: #27226

**Comment by sdixon194** [comment]
User came back in 1487169-zen for an update

**Comment by achyuthajoy** [comment]
The browser jump applies when adding Hyperlinks as well. User ticket here - https://woothemes.zendesk.com/agent/tickets/1507307

**Comment by sandymcfadden** [comment]
Had a report of this today and was able to duplicate it on my personal site. 7503601-hc

**Comment by sashastone** [comment]
Another report of this today. 6790938-hc and follow-up 1528336-zen

**Comment by KokkieH** [comment]
Another report in [the forums](https://en.forums.wordpress.com/topic/when-creating-posts-wp-jumps-to-top-of-page/) - Chrome and Opera on Windows 10

**Comment by mmtr** [comment]
Fixed by #29832
