### ISSUE TITLE
Gutenpack: I18n for blocks

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#27814]
We need to find a way to allow our Jetpack blocks for Gutenberg to be fully translatable. 

One way we can get around it is to make i18n-calypso use the same `jed` version that Gutenberg core does, and then try to reuse the same translations in Jetpack, thus let Jetpack supply them.

For this to happen:

* [x] We're updating `jed` - https://github.com/Automattic/i18n-calypso/pull/72#event-1900722105
* [x] We're updating Calypso to use `i18n-calypso@3.0.0` (which bundles the updated Jed) - #27820 
* [x] We're updating the translation build scripts:
  * Initial attempt - D19319-code
  * Improved attempt - D19382-code
* [x] We're updating the Jetpack blocks to use the Jetpack textdomain - https://github.com/Automattic/wp-calypso/pull/27680. 
* [x] We're making sure Jetpack serves the new version of translated files, and that they work well in both Jetpack and Gutenberg - https://github.com/Automattic/jetpack/pull/10347
* [x] We're making sure those translations are indexed by Jetpack when building translation files (see pa9srA-32-p2 , https://github.com/Automattic/jetpack/pull/10391 and https://github.com/Automattic/wp-calypso/pull/28088)
* [ ] We're making sure `jed >= 1.1` translation files are deployed for all languages.
* [ ] We're finding a way for those translations to work not only in Jetpack, but in Calypso as well.

**Comment by tyxla** [comment]
A summary of the work so far with a brief vision for the future has been posted in pafL3P-6B-p2

**Comment by scruffian** [comment]
Closing, since the code lives in Jetpack this will happen a different way: https://github.com/Automattic/jetpack/issues/11817
