### ISSUE TITLE
Gutenberg: Inline Image block doesn't update when its image is changed

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#27819]
Follow up to #27687

Modifying images in the media modal automatically updates the blocks using those media by listening to `MediaStore.on( 'change' )`.

Currently though, `Inline Image` blocks are not updated accordingly and, apparently, if their image has been changed, they will be removed on reload.

**Comment by vindl** [comment]
This was an issue specific to the Media Modal integration in Gutenlypso. After switching to Gutenframe it's no longer relevant.
