### ISSUE TITLE
Gutenberg: Add a GIF tour with demo option to first view

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#27829]
Lets try to use the `<InlineHelp />` UI to show a short animated GIF tour along with a CTA to load a demo post.

When you open Gutenberg for the first time we can show the inline help popover, but with a Gutenberg-centric welcome:

![guten first load](https://user-images.githubusercontent.com/191598/46888472-99442e80-ce2e-11e8-9908-aca2f3ab0e5a.png)

To help draw a little attention to this (and show people "where" the popover is coming from) we can use entrance transition:

![gute help entrance](https://user-images.githubusercontent.com/191598/46888546-d6a8bc00-ce2e-11e8-91b2-498bfde3a7d2.gif)

Clicking/Tapping on the "Load demo" button would open a new draft using the demo content from #27648.

Clicking/Tapping the "Close" button would reverse the entrance transition and close the popover. If/when you click on the help button again we'd show a more standard looking help popover, but with the switch and demo buttons:

![guten inline help](https://user-images.githubusercontent.com/191598/46888697-369f6280-ce2f-11e8-9dac-9878579fca0e.png)

--

Here's a quick draft for what the GIF tour could look like:

<img src="https://user-images.githubusercontent.com/191598/46889805-ceeb1680-ce32-11e8-87a1-1b2dc2064977.gif" width="300">
 
--

On mobile, the InlineHelp component displays as a full screen modal. We can do the same with ours, which would look something like this:

![guten first load](https://user-images.githubusercontent.com/191598/46889974-5cc70180-ce33-11e8-8dcd-e1cd42ba8d8a.png)

![gute help entrance mobile 2018-10-12 15_28_29](https://user-images.githubusercontent.com/191598/46890026-7e27ed80-ce33-11e8-8c2b-990e1dc822c1.gif)

**Comment by gwwar** [comment]
Closing for staleness
