### ISSUE TITLE
Gutenberg: Use a notice to introduce the new editor

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#27828]
Rather than displaying the large, obtrusive modal by default, what if we used a more subtle, standard notice:

![try new editor](https://user-images.githubusercontent.com/191598/46887447-9e53ae80-ce2b-11e8-92cc-e3b0db919570.png)

To help draw a little attention to the notice, we could delay its entrance, and animate it in with a little "pop" type transition:

![gute notice entrance](https://user-images.githubusercontent.com/191598/46887655-3e113c80-ce2c-11e8-90a9-6465e18c08c9.gif)
 
(Note: The animation is exaggerated in the GIF above. It should be much faster in reality.)

Clicking/Tapping on the **Learn more** link would open the introduction modal:

![intro modal](https://user-images.githubusercontent.com/191598/46887781-9a745c00-ce2c-11e8-8566-23a24f96931e.png)

--

For mobile, the main changes are that notices are pinned to the bottom, which is a little messy with the help button:

![classic editor](https://user-images.githubusercontent.com/191598/46887804-b8da5780-ce2c-11e8-8108-c08cbbaf7116.png)

And the intro modal goes full screen:

![intro modal](https://user-images.githubusercontent.com/191598/46887831-c4c61980-ce2c-11e8-886e-4644bafd7fe8.png)

**Comment by codebykat** [comment]
Just merged #27915 which adds this notice. Let's open a new issue if we want to remember when a user has dismissed the notice instead of opening it on every load.
