### ISSUE TITLE
Gutenberg: Audit Jetpack sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27822]
Let's try and see how many bugs there are that are specific to Jetpack sites only! This will help give us an idea if we need to further prioritize any API work.

Let's assume that our test Jetpack site has Gutenberg installed and activated.

Anything that affects both Simple and Jetpack sites should be added to "Backlog", while anything that affects Jetpack sites only should be triaged to [Jetpack Only Bugs"](https://github.com/orgs/Automattic/projects/34#column-3584717)

@Automattic/flowpatrol would you be interested in taking this one?

**Comment by alisterscott** [comment]
Hi @gwwar 

@Automattic/flowpatrol are more than happy to help out with this

I tried wpcalypso.wordpress.com/gutenberg with two Jetpack sites (Pressable and Atomic) and I couldn't even save a basic draft for either site (despite being able to work with them both in the normal calypso editor), this is what happens:

![gutenberg jetpack](https://user-images.githubusercontent.com/128826/46936503-ee3bab00-d0a1-11e8-9c3b-2fcae145f3f4.gif)

It keeps appending an id on the end and getting an error over and over.

Any idea what is happening there? It's probably a blocker to test other Jetpack specific blocks and functionality

**Comment by gwwar** [comment]
Ah so two bugs here:

One is around autosave not working for Jetpack sites, and the latter would be that the route handler shouldn't keep on adding to the url when errors occur. I'll add a bug for the latter

**Comment by gwwar** [comment]
Added https://github.com/Automattic/wp-calypso/issues/27867 for the url bug.

**Comment by alisterscott** [comment]
> And to clarify @alisterscott did this Atomic site have the Gutenberg plugin installed and activated?

Hi @gwwar Yes, the Atomic site has Gutenberg 3.9.0 installed to it via plugins

<img width="896" alt="screen shot 2018-10-16 at 2 40 15 pm" src="https://user-images.githubusercontent.com/128826/46993218-67dea200-d151-11e8-923d-7c1de02deb69.png">

**Comment by gwwar** [comment]
Re:autosave, @alisterscott I forgot D192600-code was still open 😅

**Comment by gwwar** [comment]
Thanks to @mdawaffe D19260 landed ✨. @alisterscott I think a few endpoints are somewhat unstable but we should be able to autosave/publish posts now. If you still see repeated failures, maybe check that the site is still connected. (I had to re-connect mine after a Jetpack update).

Note that I am seeing some intermittent failures. For example, I always need to click publish twice. On my first publish attempt I'm seeing :

`{"body":{"code":"http_request_failed","message":"cURL error 28: Operation timed out after 5000 milliseconds with 3099 bytes received","data":null},"status":500,"headers":{"Allow":"GET, POST, PUT, PATCH, DELETE"}}`

But the second try does goes through.

**Comment by JavonDavis** [comment]
I had a failure with this when saving draft/publishing the first time on an Atomic site, not sure if it's due to, 

> Note that I am seeing some intermittent failures because my sandbox is slow and hitting the 5 second Jetpack client timeout. 

Only able to catch screenshots, as I set up to record it decided to behave and consistently behave. I'll share the screenshots for what happened though. Refreshed a couple times as well and no errors showed up. 

<img width="1878" alt="screen shot 2018-10-22 at 11 00 47 am" src="https://user-images.githubusercontent.com/6520461/47304654-da85cc80-d5ec-11e8-96b0-d9f4a5650280.png">

This first one is especially weird with the error I received when trying to upload. 
<img width="2036" alt="screen shot 2018-10-22 at 10 48 12 am" src="https://user-images.githubusercontent.com/6520461/47304658-dc4f9000-d5ec-11e8-92fb-265673e7514a.png">

Decided to give it a go again with the AT site at Pressable and there seems to be a problem happening again. I was able to catch [a gif](https://d.pr/free/i/ddpbQm) with the console log(if that helps) this time 

I'm also able to post normally using the classic Calypso editor so it's werid what's happening here. Any idea? @gwwar

**Comment by gwwar** [comment]
Hmm, @mdawaffe or @oskosk are you able to reproduce the first time publishing fail? I thought it was my sandbox, but maybe something funny is happening.

cc @Automattic/lannister to try it on their Jetpack test sites.

**Comment by JavonDavis** [comment]
Just a heads up @gwwar, it seems to be an intermittent problem, I'm able to do everything fine now... Do you think it's worth creating a new issue for this? The problem also only happened on the Atomic sites. Gutenberg Version 4.0.0

**Comment by gwwar** [comment]
@JavonDavis Much appreciated if we could, folks will likely run into this if we are.

**Comment by JavonDavis** [comment]
Hi @gwwar, 

Is this expected?

<img width="743" alt="screen shot 2018-10-23 at 11 21 19 am" src="https://user-images.githubusercontent.com/6520461/47375466-ef7a6280-d6b5-11e8-847d-a65c67da3878.png">

The comments block shows up in Preview but there's that above error in the Block Editor?

**Comment by JavonDavis** [comment]
There was an issue both on Simple and Jetpack sites with the Tiled Gallery Block under Jetpack section. Images in Gallery overlaying other blocks. See https://github.com/Automattic/wp-calypso/issues/28029.

**Comment by gwwar** [comment]
> The comments block shows up fine in Preview but there's that above error in the Block Editor.

@JavonDavis Much appreciated if we can file a bug for that. Blocks may persist differently in save() vs edit() functions, so likely we're missing an API endpoint, or are making the call incorrectly.

**Comment by JavonDavis** [comment]
Sure no problem, see https://github.com/Automattic/wp-calypso/issues/28035

> Blocks may persist differently in save() vs edit() functions, so likely we're missing an API endpoint, or are making the call incorrectly for the editor preview.

I'd probably bank on the missing endpoint, I got interested in blocks from the Gutenberg class at the GM so if I have the bandwidth I'll try and look into more detail what might be happening here.

**Comment by mdawaffe** [comment]
> Note that I am seeing some intermittent failures because my sandbox is slow and hitting the 5 second Jetpack client timeout

> Hmm, @mdawaffe or @oskosk are you able to reproduce the first time publishing fail? I thought it was my sandbox, but maybe something funny is happening.

I haven't seen this behavior, but it is worrying. I'll look some more.

**Comment by gwwar** [comment]
@JavonDavis If you find issues that affect all sites, you're welcome to drop them into the bottom of the backlog.

**Comment by mdawaffe** [comment]
> Note that I am seeing some intermittent failures because my sandbox is slow and hitting the 5 second Jetpack client timeout

> Hmm, @mdawaffe or @oskosk are you able to reproduce the first time publishing fail? I thought it was my sandbox, but maybe something funny is happening.

For the v1 JSON API, we've been using a timeout of 30 seconds when making requests to Jetpack sites. For the v2 REST API, we're currently using a 5 second timeout. It's unfortunate we have to bump the timeout, but it is what it is.

Should be addressed in the not-yet-deployed D19979-code.

**Comment by JavonDavis** [comment]
> @JavonDavis If you find issues that affect all sites, you're welcome to drop them into the bottom of the backlog.

@gwwar ok will do that

**Comment by gwwar** [comment]
Closing this one due to staleness :)
