### ISSUE TITLE
Gutenberg: Simpler Markdown editing on select

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#27858]
Wtih #27788, the Markdown block shows a rendered preview when not selected, and shows the source for editing when the block is selected. It's necessary to click on the block twice before you can start typing in the block when it is initially not selected.

Several core blocks allow you to interact with the editable contents immediately when you select the block. This is lost with the current Markdown implementation.

An ideal situation would position the cursor and be ready to edit when the block is selected.

Here's an example of the current experience:

![markdown](https://user-images.githubusercontent.com/841763/46953482-44065800-d08e-11e8-897d-6d0fde9f44d0.gif)

cc: @Automattic/luna @MichaelArestad

**Comment by tyxla** [comment]
I agree, this would be great to have. 

In order to be able to do this though, we'll need to revert #27788. 

@MichaelArestad @Mapk what do you think?

**Comment by MichaelArestad** [comment]
I think how it was before is better than the extra click. The extra click feels broken.

**Comment by tyxla** [comment]
I like that we can solve the 2 click problem 👍 It's not optimal indeed, but it's already an improvement. 

I'll let @mapk @MichaelArestad cast their vote, but I think this makes it in an acceptable state for a v1. The other way around would be to completely revert #27788.

**Comment by MichaelArestad** [comment]
Let's ship it with the 2 click fix and get folks trying it out!
