### ISSUE TITLE
Nonthing is loading after installation

### ISSUE THREAD

**Issue by saurabhpuranik** [Automattic/wp-calypso#27876]
![untitled](https://user-images.githubusercontent.com/24870345/47018501-7f7a5280-d172-11e8-89e7-9286e26be10a.png)
After instalation nothing is loading see attached screenshot.

**Comment by lancewillett** [comment]
Hello @saurabhpuranik  — thank you for sharing this; could you help with a few more details?

- OS and browser versions

Are you trying to develop on Windows? Try this troubleshooting doc: https://github.com/Automattic/wp-calypso/blob/master/docs/install.md
