### ISSUE TITLE
Plans view when switching between a wpcom and a jetpack site broken

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#2787]
How to reproduce:
- View the plans page for a Jetpack site, eg: wp.com/plans/{your-jetpack-site}
- Use the site switcher to switch to a wpcom site
- The page will not update itself and neither will the URL in the address bar
- Also broken going the other way, ie: viewing plans for a wpcom site and switching to a Jetpack site

The flow works fine when switching from a wpcom site to another wpcom site or from a jetpack site to another jetpack site.

Using Chrome on production.

@johnHackworth thinks its related to: 
https://github.com/Automattic/wp-calypso/commit/01c54b4c

**Comment by designsimply** [comment]
@richardmuscat, I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/2610. Agree?

**Comment by richardmuscat** [comment]
@designsimply, yup looks like the same thing.

**Comment by scruffian** [comment]
Closing in favour of #2610
