### ISSUE TITLE
Plugins: 'Edit All' should select every plugin intially

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#2789]
We changed the 'Bulk Edit' button to have the more democratic title 'Edit All', but with that we created an assumption that you would immediately be in a position to actually edit all plugins. That is a false promise since no plugins are selected by default.

Let's change the experience so that clicking 'Edit All' selects every plugin in the list when clicked. The bulk select checkbox will allow users to deselect and they can individually deselect plugins from the list as before.

cc @isaackeyet who raised this issue in #2256

**Comment by MichaelArestad** [comment]
Let's try it out. I'm not sure if I like that idea or not since I've never used anything that does this.

**Comment by isaackeyet** [comment]
I think it's a win at least in terms of expectancy! :)

**Comment by slaFFik** [comment]
This issue can be closed, as it's already done, merged and live.
