### ISSUE TITLE
Gutenberg: Refresh placeholder copy in Related Posts block

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#27898]
We once discussed with @mapk that the copy we use for the placeholder content in the Related Posts block is a little outdated and could use some refresh. 

Does it make sense to tackle that for the v1?

cc @michaelarestad

**Comment by tyxla** [comment]
When we get the new copy, we'll need to also localize it - see #27899

**Comment by MichaelArestad** [comment]
I think so. @mapk Do you want take another stab at these? The design needs to:

A) Be clear that it's a placeholder
B) Show what content could look like

I don't think we need to use it to try to advertise other features or something like that. If I was a user, I might fear those would end on the front end of the site.

**Comment by mapk** [comment]
I'm struggling a bit with these. Here's another go at it though.

![screen shot 2018-10-17 at 4 53 46 pm](https://user-images.githubusercontent.com/617986/47122810-4fdc5080-d22d-11e8-94b2-938e4ebfc1d0.png)

or with an icon...

![screen shot 2018-10-17 at 4 55 26 pm](https://user-images.githubusercontent.com/617986/47122848-77cbb400-d22d-11e8-8170-95437e571891.png)


1. Should all three match in content, or should they be different as I have them in the mockup?
2. Should the image be an actual image, or just a box of color as I have it? Icon or no?
3. Should the titles of the posts actually indicate they are placeholders?

**Comment by tyxla** [comment]
Thanks for working on this.

1. My preference is to have them different.
2. I think having a real image there would help the user imagine how things would look when they have real related posts. And if y'all decide to go with the box of color - I think the icon could be confusing - a user might think that this is an image placeholder, and they might think they can upload their own image there.
3. Titles don't have to be placeholders themselves, but it's probably clearer if they are. 

And if I might add a suggestion: I think we could have some sort of ribbon on each of the posts that clearly states that each post is a sample. Let me know if that makes sense.

Let's decide a final design and I'll tinker with whatever is needed to get it done.

**Comment by MichaelArestad** [comment]
Yeah. @mapk I wonder if we could pick like 10 random scenic images that we could use (or even just three)

**Comment by MichaelArestad** [comment]
I bet @jeffgolenski might have a few we could use.

**Comment by aldavigdis** [comment]
Working on this as we speak, based on @thomasguillot's design ideas.
