### ISSUE TITLE
Related posts block: Translate placeholder copy

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#27899]
When #27898 is done, we need to make sure that the placeholder copy is properly localized. It's still early to do that, as the copy is to be refreshed, and those translations will be obsolete.

Suggested by @sirreal in https://github.com/Automattic/wp-calypso/pull/27659#discussion_r225213310

**Comment by aldavigdis** [comment]
I believe this can be closed after #30161 and #30224. Please confirm if wrong.

**Comment by tyxla** [comment]
Nice 👍 The relevant work has been done in #30161, let's close this one.
