### ISSUE TITLE
Reader: Extend arrow link target out

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#2791]
All this extra space in the top bar now is making me feel lazy, and I don't want to have to drag my cursor all the way over to the corner to go back:

![reader-arrow](https://cloud.githubusercontent.com/assets/2846578/12588101/16dac654-c425-11e5-915f-4e6e0c6f9be4.jpg)

Increasing the link area would be great not just for lazy folks like me, but also for people with repetitive stress injuries, carpal tunnel, or impaired motor control.

**Comment by shaunandrews** [comment]
This was fixed in #2805 :)

**Comment by melchoyce** [comment]
:raised_hands:
