### ISSUE TITLE
Editor: Comments enabled on old pages after editing

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#2792]
Reported by @sararosso via slack ( please add more details if possible Sara ).

> comments are being accepted & held in moderation for posts which do not have comments enabled (again). Posts are years old (with comments unchecked at the post level) and the only difference is I’m using Jetpack + the WP Desktop app to edit those pages.

**Comment by timmyc** [comment]
Might be related to #346 - though that is just for drafts apparently

**Comment by sararosso** [comment]
Thanks @timmyc!

Here are two pages on my Jetpack-enabled site (which is years and years old) which just received comments this week. Comments and pingbacks have always been off on this site. After this happened this fall I went in manually and made sure comments were disabled, as well as turned off pingbacks (which are now enabled again, which I didn't do). 

On November 10th @jeherve had me install a plugin to trace this back and said " Looks like we don’t synchronize the options back to WordPress.com properly. I’ll need to run some tests to see somehow these options are pushed back to the site, even when you don’t update a page via Calypso or the Desktop app"

<img width="774" alt="screen shot 2016-01-25 at 5 18 32 pm" src="https://cloud.githubusercontent.com/assets/4126822/12589037/96010e8a-c410-11e5-9062-dd53b427d85f.png">
<img width="777" alt="screen shot 2016-01-25 at 5 03 15 pm" src="https://cloud.githubusercontent.com/assets/4126822/12589036/95fd1258-c410-11e5-9ed8-5221fd1f8b92.png">

**Comment by jeherve** [comment]
> I’ll need to run some tests to see somehow these options are pushed back to the site, even when you don’t update a page via Calypso or the Desktop app"

I wasn't able to reproduce the issue on my test sites at the time, for some reason.

I'm not exactly sure what's causing this issue.

**Comment by timmyc** [comment]
So I was not able to reproduce this on a Jetpack site using the Desktop app either.  @sararosso what JP version is your site running?

**Comment by sararosso** [comment]
VERSION 3.8.2

**Comment by timmyc** [comment]
:) - I was on 3.8.1 - but also updated to Version 3.9.1 - and still could not reproduce.

To verify - the steps I took were:
- Open up a page in the desktop app
- Make a change
- Click Update
- Verify in wp-admin that "Allow Comments" has not been modified

**Comment by sararosso** [comment]
I'm not sure what changed...I'm going to document my changes to reaffirm once again that comments and pingbacks are turned off for all posts and pages, update the Jetpack plugin, and I'll come back next time it happens again :) It's twice now, so something is happening...

**Comment by sararosso** [comment]
In wp-admin: 
- Spammed the trackback links. 
- Did Bulk Edit pages > Do not allow comments.
- Verify " Allow link notifications from other blogs (pingbacks and trackbacks) on new articles" in Settings > Discussion is unchecked (it is).
- Unchecked "Attempt to send notifications..." from Settings > Discussion.
- Check all published pages and manually uncheck Pingbacks and trackbacks - had to uncheck on two pages on which received spam, and one page where I hadn't received any.
- Updated two plugins, including Jetpack to 3.9.1.

Opened the site in the WordPress.com app (which was open), updated one published page. Verified changes in wp-admin are correct, no pingback checked as of yet. Re-opened the WordPress.com app and made another change, verified change in wp-admin, no pingback re-checked as of yet. 

We can close for now, but worth noting this is the second problem, last one occurred in November 2015.

**Comment by timmyc** [comment]
Thanks for doing some more tests @sararosso - I will close this out for now but please do re-open if it happens again.
