### ISSUE TITLE
Gutenberg: Dynamic blocks default attributes aren't loaded

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#27963]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/post/ ; select a site and load Gutenberg.
2. Insert a dynamic block such as `Latest Comments`.
3. Open the block settings: all the toggles are off and the slider's value is empty.
4. Compare it with how the block is rendered and observe how most, if not all, settings have the incorrect values.

Notes:
- Changing one setting will fix this inconsistency for that setting. This issue is only about the default values.
- Some cases (e.g. the Categories block) might be misleading, because all the attributes actually default to `false`.

#### What I expected

That the block default values are applied to the block sidebar.

#### What happened instead

The block sidebar uses the components default values instead (e.g. false for toggle; empty for the slider input)

#### Screenshot / Video

<img width="1094" alt="screenshot 2018-10-19 at 11 53 32" src="https://user-images.githubusercontent.com/2070010/47230684-cc546800-d3c2-11e8-9476-b392f3ce8224.png">

#### Context / Source

Gutenberg feeds those default values to the blocks settings with the [`unstable__bootstrapServerSideBlockDefinitions `](https://github.com/WordPress/gutenberg/blob/48c120966e155f4c4134133ae92bfe38f2a1f846/packages/blocks/src/api/registration.js#L20-L54) function, which is called in the [`client-assets.php`](https://github.com/WordPress/gutenberg/blob/48c120966e155f4c4134133ae92bfe38f2a1f846/lib/client-assets.php#L1429-L1433) file.

That function is never called in Calypso, and therefore all dynamic blocks default attributes fallback to empty objects.

**Comment by cecoates** [comment]
1506955-hc with the "Latest posts" block.

**Comment by tanjoymor** [comment]
1675600-zd similar issue with the "Latest posts" block - when you change the settings on the block it's returning an update failed message and the block is reverting to the default values.

**Comment by khristiansnyder** [comment]
9056662-hc Same issue with the "Latest Posts" block.

**Comment by selectedselections** [comment]
1702487-zd same issue with the Latest posts block. The values are blank and when they are set to numbers, those numbers are not reflected with the published results. (ie the block is set to display 10 posts and only 4 are displayed)
