### ISSUE TITLE
Need improve big Infinite list performance

### ISSUE THREAD

**Issue by enesyteam** [Automattic/wp-calypso#27973]
Hi Calypso team,
I think you must improve the big list performance, because in Reader section, when user scroll down, the page fetch data and display, so if there're alot of data, the performance is very bad.

Instead render all items in Infinite list, we only need to render available items that user can see (on browser). I founded this library do what exactly what I'm saying:
[https://github.com/bvaughn/react-virtualized](https://github.com/bvaughn/react-virtualized)
Thanks you Calypso!

**Comment by lancewillett** [comment]
Thank you, @enesyteam.

**Comment by bluefuton** [comment]
Thanks for the feedback @enesyteam. 

We do actually use `react-virtualized` elsewhere in Calypso for that very reason - in Manage Following, for example:

https://wordpress.com/following/manage

Reader is not being actively worked on right now, but if you'd like to have a go at improving the performance of our infinite lists, all PRs are welcome :)
