### ISSUE TITLE
Activity Log: Odd menu layering issues

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#27990]
When using the Activity Log filtering, the pop-up menu can sometimes be hidden. Originally reported by @annezazu . See video on attached issue.

**Comment by annezazu** [comment]
Re-opening after re-testing. Less weirdness than the [first video](https://cloudup.com/cXzzdU8jgz0) but still some there:

https://cloudup.com/cAfhAEHKdcr
