### ISSUE TITLE
Gutenberg: Remounting the editor reapplies the fetch middleware

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#27993]
#### Steps to reproduce
0. Login with a user with at least two sites
0. Open the Sources tab of the Chrome debugger, set a break inside the WithApiMiddleware class's registerMiddleware function
1. Starting at URL: http://calypso.localhost:3000/gutenberg/post
2. Pick a site
3. Wait for Gute to load, notice the break fire and the middleware get applied
4. Hit the close button in Gute
5. Pick a site
6. Wait for Gute to load, notice the break fires again and the middleware is applied again
7. Step into the middleware's `use` function, Inspect the list of middlewares. Notice our set of interceptors has been applied twice.

It appears the list will just keep growing every time a user opens and closes the editor.

**Comment by vindl** [comment]
I think we'll be able to handle this as part of https://github.com/Automattic/wp-calypso/issues/27882.

**Comment by blowery** [comment]
Thanks @vindl! I'll close this one down in favor of the bigger issue.
