### ISSUE TITLE
Me/Security: Entering two step code is not mobile friendly in a couple of places

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#28]
1. Entering code during setup

![image](https://cloud.githubusercontent.com/assets/7233112/11219112/99716ec8-8d26-11e5-91d4-c42aa56b0d45.png)

2. Verifying a backup code

![image](https://cloud.githubusercontent.com/assets/7233112/11219115/a13f5a5c-8d26-11e5-954c-67ccef67a63a.png)

3. Disabling two step

![image](https://cloud.githubusercontent.com/assets/7233112/11219119/a7f44e98-8d26-11e5-8865-527ad6525cad.png)

**Comment by ebinnion** [comment]
Hey @hoverduck, would you mind explaining the issues in these screenshots?

I notice that the buttons are misaligned quite a bit in the 3rd screenshot, but nothing is standing out to me in the other screenshots.

**Comment by hoverduck** [comment]
The issue was originally raised in the pre-oss repo by @nprasath002, they may be able to provide more insight.  My thought on the first screenshot is that the buttons are obscured by the keyboard, which makes it hard to click Enable after typing the code.  I'm not sure about the second one either.

**Comment by nprasath002** [comment]
Two step codes are numbers and my thought to show a number layout instead of a full keyboard

**Comment by ebinnion** [comment]
Ahh! Thanks for pointing that out @nprasath002. :smile: I will get that fixed up :+1:
