### ISSUE TITLE
Gutenberg: One time error Saving Draft and Publishing Post

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/wp-calypso#28020]
I had a failure with Gutenberg when saving draft/publishing the first time on an Atomic site, not sure if it's due to the 5 second Jetpack client timeout. 

Only able to catch screenshots, as I set up to record it decided to behave and consistently behave. I'll share the screenshots for what happened though. Refreshed a couple times as well and no errors showed up. 

<img width="1878" alt="screen shot 2018-10-22 at 11 00 47 am" src="https://user-images.githubusercontent.com/6520461/47304654-da85cc80-d5ec-11e8-96b0-d9f4a5650280.png">

This first one is especially weird with the error I received when trying to upload. 
<img width="2036" alt="screen shot 2018-10-22 at 10 48 12 am" src="https://user-images.githubusercontent.com/6520461/47304658-dc4f9000-d5ec-11e8-92fb-265673e7514a.png">

Decided to give it a go again with the AT site at Pressable and there seems to be a problem happening again. I was able to catch [a gif](https://d.pr/free/i/ddpbQm) with the console log(if that helps) this time 

Also using Gutenberg Version 4.0.0. 

I was also able to post normally using the classic Calypso editor so it's weird what was happening there. 

**Note that everything works fine now, with no change on my end but creating this for visibility.** 

cc @Automattic/lannister 

I'll keep checking in on it and will update if I can reproduce consistently.

**Comment by mdawaffe** [comment]
I think this is a timeout problem and will be resolved when D19979-code is deployed.

https://github.com/Automattic/wp-calypso/issues/27822#issuecomment-433569175

**Comment by mdawaffe** [comment]
D19979-code has been deployed, so I think this problem has been "fixed".

**Comment by JavonDavis** [comment]
Fixed in D19979 deployment

**Comment by gwwar** [comment]
Thanks @mdawaffe! I didn't realize we had such a long timeout on our v1 APIs.
