### ISSUE TITLE
Gutenberg: (Tiled Gallery Block) Images in gallery extending over other blocks

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/wp-calypso#28029]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post
2. Select any site Simple or Jetpack
3. Create a new Tiled Gallery Block from under Jetpack
4. Add a few images
5. Create a new paragraph block underneath

#### What I expected
New Paragraph Block to begin under images or under the block itself be could be scrollable

#### What happened instead

Images in Tiled Gallery Block overlay the text

#### Browser / OS version

Chrome Version 70
Gutenberg Version 4.0.0

#### Screenshot / Video

<img width="727" alt="screen shot 2018-10-23 at 2 30 01 pm" src="https://user-images.githubusercontent.com/6520461/47385617-28273580-d6d0-11e8-8d90-4a9f60b101d0.png">

**Comment by JavonDavis** [comment]
Also, the Tiled Gallery block does not appear in Preview or in the published post. 

![screen shot 2018-10-23 at 5 31 14 pm](https://user-images.githubusercontent.com/6520461/47394715-7c8adf00-d6e9-11e8-8ed8-b996e7787cfa.png)

**Comment by vindl** [comment]
Removing this from Calypso Gutenberg Integration project for the same reasons stated in https://github.com/Automattic/wp-calypso/issues/29212#issuecomment-445750443.

**Comment by sirreal** [comment]
Noting that the block are in beta still, but these issues have been fixed. Closing.
