### ISSUE TITLE
Notifications: No link to comment in notifications panel

### ISSUE THREAD

**Issue by wensco** [Automattic/wp-calypso#2806]
When someone likes a comment I make on a post, I get a notification but there's no link to the comment so I can't tell what comment they liked.

To reproduce:
1. I made a comment on someone's post (not a comment on a comment)
2. 2 people liked my comment
3. I got the like notification but there's no link to my comment or the original post for me to tell what they liked.

I'm seeing the same issue in my browser, desktop app, and mobile app (Android). In each of them, there's an empty space under my name/gravatar where a link should be.

Here's a screenshot of the notification in the mobile app:
![screenshot_2016-01-26-16-49-47-1](https://cloud.githubusercontent.com/assets/7942966/12596352/7035dba8-c44d-11e5-8ca7-04c7c7edc219.png)

(Previously noted in 6298-gh-calypso-pre-oss)

**Comment by designsimply** [comment]
Thank you for the bug report!

How was the post created (P2 theme front end, Calypso Editor, or some other way)?

Does the post have a title saved or is the title empty?

**Comment by wensco** [comment]
The post was created as a scheduled post from the Calypso editor. The post does have a saved title. I'm also checking with another person who has a comment with likes on that same post to see if they see the same issue with the notification that I do.

**Comment by danhauk** [comment]
I have a comment on that same post but I'm seeing the link to my comment in the Android app and mobile web.

**Comment by lancewillett** [comment]
Closing since it wasn't reproducible — feel free to reopen if you see it happen again.

**Comment by wensco** [comment]
Fwiw, this just happened to me again recently, same exact issue as before: I posted a comment on a post, 2 people liked it, got a notification, but the notification did not show what they liked. This screen shot is from Chrome, but the same thing happens in the desktop app (Mac) and in the Android app.

<img width="795" alt="2016-04-29_0803" src="https://cloud.githubusercontent.com/assets/7942966/14915522/be7f2250-0de1-11e6-9b2c-2c982abec872.png">

**Comment by gibrown** [comment]
I had another case of this happen.

https://cloudup.com/cAbZ9D5L2Qt

Excuse the internal a8c link: https://autobabby.wordpress.com/2016/10/31/the-kids-in-halloween-costumes-thread/

Full text of my comment was:

```
<a href="http://autobabby.files.wordpress.com/2016/11/img_4667.jpg" rel="nofollow"><img src="http://autobabby.files.wordpress.com/2016/11/img_4667.jpg?w=776" alt="img_4667" class="size-full wp-image" id="i-2323" /></a>

<a href="http://autobabby.files.wordpress.com/2016/11/img_4672.jpg" rel="nofollow"><img src="http://autobabby.files.wordpress.com/2016/11/img_4672.jpg?w=776" alt="img_4672" class="size-full wp-image" id="i-2324" /></a>

Morgan (1.5) as Calvin. Guest starring a sheep as Hobbes. Mostly just an excuse for Mekayla and I to be Calvin's alter egos: Stupendous Man and Spaceman Spiff.
```
