### ISSUE TITLE
Feature: Incorrect language on username validation message

### ISSUE THREAD

**Issue by montogeek** [Automattic/wp-calypso#2807]
URL: http://calypso.localhost:3000/me/account

What I expected: Validation message in the current language

What happened instead:Validation message in another language

Steps to reproduce: 
1. Logging
2. Go to "Account settings"
3. Change your username to one that already exists.
4. See validation message in another language

Browser OS version: Chrome Version 48.0.2564.82 beta (64-bit), OSX Yosemite

Screenshots/Video: 
![screen shot 2016-01-26 at 17 21 22](https://cloud.githubusercontent.com/assets/1002461/12597147/ae8cc6f6-c451-11e5-9269-4a0f2797b67a.png)

**Comment by klimeryk** [comment]
While our community of translators are trying their best to keep up with new/changed strings, sometimes parts of the UI might not be fully translated. In this case, it seems [this particular string should be now translated](https://translate.wordpress.com/projects/wpcom/es/default?filters[term]=Choose+a+different+username.+This+one+is+not+allowed.&filters[user_login]=&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&filters[priority][]=1&filters[priority][]=0&filters[priority][]=-1&filters[view]=&filter=Filter&sort[by]=priority&sort[how]=desc) (unless I guess the language, Spanish, incorrectly). _You_ can also help out directly (and easily), by enabling the [Community Translator](https://en.support.wordpress.com/community-translator/) :+1: 
You can verify the status of a particular string on https://translate.wordpress.com/projects/wpcom
I'm closing this as this doesn't seem to be a bug (the string is "translateable", I've checked), the translation for your language just did not have this string translated at the time.
