### ISSUE TITLE
Signup: Trouble using a domain-based email while setting up that same domain

### ISSUE THREAD

**Issue by ajaykj** [Automattic/wp-calypso#28075]
Edits: Changed the title to reflect further troubleshooting (see comments): the problem wasn't the "p" so much that the domain on the email matched the domain in signup. Our signup presumes the email address is new and won't work, but given that we're bringing in more business users now that's not necessarily true.  Videos here: https://cloudup.com/c2H6T_dlREv

A user reported that trying to use `p` in the email address on https://wordpress.com/start/user page causes validation errors. However, if it's replaced by `P` then the validation goes through. The user made two comments:

- Look at the json request that occurring with that field validation and you should be able to find the bug.
- Extremely frustrating and spent way too much time looking at your JavaScript code to find that capital P characters are allowed.

I couldn't replicate the error on my end but the following are the results of what the user shared:

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/user
2. Use an email address with a `p` in it.
3. Email validation fails 
4. Replace `p` with `P`
5. Email validation goes through

#### What I expected
The email validation should work irrespective of the case of the email address

#### What happened instead
email address with `p` fails while it works with `P`

#### Browser / OS version
N/A

#### Screenshot / Video
N/A

#### Context / Source

- First reported here - https://en.forums.wordpress.com/topic/cant-sign-up-with-business-email/
- Second incidence 1500771-zen

#user-report #bug

**Comment by supernovia** [comment]
Was this fixed already? I got up and tested several "p" domains and had no problems.

**Comment by supernovia** [comment]
Noting the user in the forums said they got this error:


“Use a working email address, so you can receive our messages.”

I looked in our code, and that seems to be trying to stop people from signing up with email addresses that match a domain they're buying (since the address presumably wouldn't be working yet.) Do we know whether this second user was getting the same error?

**Comment by supernovia** [comment]
Noting I wasn't able duplicate if I went to wordpress.com/start :
https://cloudup.com/i9enJ-UBhpH

But I did get something kinda similar if I went to wordpress.com/plans and signed up from there with domain with a lowercase p in it:
https://cloudup.com/iti0ibCa7_M

**Comment by supernovia** [comment]
noting as well I don't think it's really anything to do with the p at all, probably just that the domain and email domain match since that's what's supposed to trigger the error. The user seemed pretty sure it was the P though based on their console findings, so I'm hoping they'll update us.

**Comment by supernovia** [comment]
OK yeah I think the lowercase p is a red herring.

Users can't sign up for a plan for theirdomain.com using email@theirdomain.com, even theirdomain.com is active elsewhere and email@theirdomain.com probably does exist. 

If we want to get more businesses signing up with us, particularly those who have emails but not websites yet, we'll want to fix the messaging here. Maybe suggest they use an address outside the domain they're setting up but allow them to register with that anyway if they'd like?

https://cloudup.com/iQoOOH3n2Ej
