### ISSUE TITLE
Editor: change "Stick to the front page" string

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#28125]
#### Steps to reproduce
1. Start a new post
2. Click on the Status tab on the Settings bar
3. Stick to the front page button

#### What I expected
More than once I got users that thought they would have to activate this option at every post and then they wouldn't understand why the most recent post wouldn't appear at the front page even if it's sticky. That was obvious because all the other posts were set to be sticky and they had more than 10 posts already.

Since this is misleading and if the blog page isn't at the front page of the site it's not correct, I suggest we change this copy to something else, like "Stick to the top" only.

#### Screenshot / Video

![sticky](https://user-images.githubusercontent.com/3521683/47589815-b0ac0d00-d940-11e8-80af-87ccf75eb321.jpeg)

#user-report
If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by arunsathiya** [comment]
I'd agree with this as well. The wording can be improved to indicate that the blog posts chosen with this option stay at the top of the blog archive.
