### ISSUE TITLE
Error: Cannot find module 'D:\wp-calypso\node_modules\babel-loader\lib/package'

### ISSUE THREAD

**Issue by hristov296** [Automattic/wp-calypso#28122]
#### Steps to reproduce
1. $ cd d:/lib
2. $ git clone https://github.com/Automattic/wp-calypso.git
3. $ cd wp-calypso
4. $ npm start

#### What I expected
Successful installation of wp-calypso

#### What happened instead
D:\lib\wp-calypso\node_modules\webpack-cli\bin\cli.js:244
                                throw err;

Error: Cannot find module 'D:\wp-calypso\node_modules\babel-loader\lib/package'

#### Browser / OS version
OS: Windows 10
Node -v: 10.12.0
npm -v: 6.4.0

#### Screenshot / Video
https://pastebin.com/k3ZXmdgd

#### Context / Source
Following the installation steps, I am failing to install wp-calypso. I'm pretty sure it's something on my end, so I request some help. I simply follow the steps for installing wp-calypso, but I get this error.

**Comment by lancewillett** [comment]
Hi there, thanks for trying out Calypso! Per our install docs here: https://github.com/Automattic/wp-calypso/blob/master/docs/install.md you might need to use `nvm-windows` for Windows installation.

I also suggest checking out this portable bootstrap version: https://github.com/Automattic/wp-calypso-bootstrap
