### ISSUE TITLE
My Sites: The DomainToPlanNudge component does not pass currency down to PlanPrice

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/wp-calypso#28145]
#### Steps to reproduce
1. Open a website that __has a legacy custom domain__ but does __not have a plan__. Also, the user currency __must not be USD__.
2. Navigate to __Domains__ from the main menu.
3. If there are not additional notice, you will see a plan upgrade nudge (`DomainToPlanNudge`) that mixes currencies up.

#### What I expected
I expected a message that only displays my local currency.

#### What happened instead
Most strings contain the correct currency, but the plan prices are displayed in USD.

#### Screenshot
[![Nudge](https://cdn-std.dprcdn.net/files/acc_693496/MeHk0l)](https://cld.wthms.co/MeHk0l)

#### Investigation
The whole banner is controlled by the `DomainToPlanNudge` component, which renders a `Banner`.  `Banner` on the other hand displays a couple of `PlanPrice` components:

```js
{ size( prices ) === 2 && (
    <div className="banner__prices">
        <PlanPrice rawPrice={ prices[ 0 ] } original />
        <PlanPrice rawPrice={ prices[ 1 ] } discounted />
    </div>
) }
```

As you can see, there is no prop for currency. 

`PlanPrice` is not a connected component and has the following defaults:

```js
PlanPrice.defaultProps = {
	currencyCode: 'USD',
	original: false,
	discounted: false,
	className: '',
};
```
This lets React use the default `currencyCode`, which is set to `USD`, which is the reason why prices are mismatched.

#### Suggestion
Connect `PlanPrice` and use `currencyCode: getCurrentUserCurrencyCode( state )` in `mapStateToProps`.

**Comment by RadoslavGeorgiev** [comment]
I think the PR description is detailed enough, so for this comment, simply ⬆️

**Comment by sixhours** [comment]
This is probably something we can fix. Moving it to our board to investigate.

**Comment by obenland** [comment]
@frontdevde Is this "just" a code review away from being fixed? Or is there something that's blocking (other than bandwidth of course) that needs documenting?

**Comment by frontdevde** [comment]
IIRC there were a couple of tests failing after the change. Looking back at the latest CircleCI run, I see

> 2 tests failed out of 13693
> PlanFeaturesHeader.renderPriceGroup() Should return a single, not discounted price when a single price is passed
> PlanFeaturesHeader.renderPriceGroup() Should return two prices when two numbers are passed: one original and one discounted

IIRC at the time we were advised to pause work on Janitor items after the Janitor iteration ended to focus on product work and let the next Janitor rotation pick up where we left off. That said, I should've added handover notes here to outline outstanding todos to make it easier for the next person to pick it up!

**Comment by cathymcbride** [comment]
@jaswrks does this fall to your team's purview?

**Comment by jaswrks** [comment]
@cathymcbride Thanks. Yes. We can take a look. Appreciate heads up.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
