### ISSUE TITLE
Invalid shipping locations detected in one or more zones

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#28172]
A message shows on Calypso store "Invalid shipping locations detected in one or more zones" in the Shipping section of WooCommerce settings.  At the same time the "Edit" buttons can't be clicked as seen in this screenshot:

Steps to reproduce
1. Go to wp-admin > WooCommerce > settings > shipping and add two or more zones that include the same location.  
2. Go to My site > store > settings > shipping
3. The message above displays "Invalid shipping locations detected in one or more zones"
4. Try to click the "Edit". It can't be edited
5. Go to wp-admin > WooCommerce > settings > shipping. No errors are shown, all data is correct and can be modified.  

#### What I expected

The message is confusing and it should instead warn users that "two or more zones include the same location" and either let the "edit" buttons edit these settings or add a link to wp-admin to edit these options

#### What happened instead

The invalid message is showing and the buttons are not editable

#### Screenshot / Video

![screen shot 2018-10-26 at 19 18 16](https://user-images.githubusercontent.com/23703267/47725597-3674d480-dc2f-11e8-9970-3d6a717154a9.png)

**Comment by zdenys** [comment]
Encountered the same error myself. 

![](https://cld.wthms.co/sdOKQL+)

#dogfooding, #manual-testing
