### ISSUE TITLE
NUX: Resent notification email message is misaligned

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#2817]
As a new user if I click on the "Resend activation email" link the message that shows up to say that this happened is misaligned. This happened in the editor for me.

<img width="1074" alt="screen shot 2016-01-26 at 5 28 51 pm" src="https://cloud.githubusercontent.com/assets/1464705/12600958/65d05c2e-c452-11e5-8a67-101e4dce3e06.png">

**Comment by folletto** [comment]
Note that might be more efficient to remove the message from that Editor screen specifically and replace with the popup on Publish, see #2650 for a mockup.

**Comment by apeatling** [comment]
This user had the same issue: 

![screen shot 2016-01-28 at 1 38 57 pm](https://cloud.githubusercontent.com/assets/1464705/12659632/afbb6982-c5c4-11e5-8d51-0583bdab4fc2.png)

**Comment by drewblaisdell** [comment]
There is now a PR to fix the misaligned notice here: https://github.com/Automattic/wp-calypso/pull/2904

I was unable to reproduce the issue in the separate screenshot (in either the browser or desktop app at multiple viewports), which looks like it is separate. Does anyone know how to reproduce it?

**Comment by folletto** [comment]
The second screenshot seems done on the previous non-wide Editor. Afaik it was fixed already with the new layout.

**Comment by apeatling** [comment]
Ah I think you are right @folletto
