### ISSUE TITLE
Checkout: `SitesList` is stale after purchasing a plan

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#2818]
Currently, when the user signs up for a free trial, the label in the sidebar next to their plan does not update to read 'Trial' until the user refreshes the page.

![screen shot 2016-01-26 at 5 56 10 pm](https://cloud.githubusercontent.com/assets/1130674/12601479/2a1dd68a-c456-11e5-9a4e-0d7db76a75e9.png)

This is because we don't fetch the sites list after the user checks out with a free trial. It looks like we wrote code that *should* do this [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/checkout/checkout.jsx#L135), but I have asserted that no request to the sites endpoint is triggered at this point. We should update this to actually fetch sites for all plans.

**Comment by stephanethomas** [comment]
Well, I can state for sure that [`clearSitePlans()`](https://github.com/Automattic/wp-calypso/blob/de8bd4aaa56b348218e38f7eac669f54e633a365/client/my-sites/upgrades/checkout/checkout.jsx#L131) does [nothing](https://github.com/Automattic/wp-calypso/blob/0c382004860313e76dd946fcc90e09b72c90a6b3/client/state/sites/plans/actions.js#L27).
