### ISSUE TITLE
Purchases: Update notice for unsubscribed purchases

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#282]
Originally reported by @scruffian.

If a user manually cancels a purchase before the renewal date then we should show this notice on the manage purchase screen, and leave the purchase in the list:

>You canceled this domain on [date]. It will stop working in [XX] days. Changed your mind? Renew now

**Comment by fabianapsimoes** [comment]
We already show unsubcribed purchases in `/purchases`. It's just a matter of updating the notice with more information related to the state of the purchase.

@mikeshelton1503 is the term "canceled" still the most appropriate here?

**Comment by mikeshelton1503** [comment]
Yep "canceled" is good, at least until make changes elsewhere.

**Comment by drewblaisdell** [comment]
We now show a [similar notice](https://cloudup.com/cnQJ5cvjNrG) here. It doesn't include information about the cancellation date (i.e., when the user disabled auto-renew), but as discussed elsewhere, this information isn't super useful and doesn't make sense when this is disabled via other processes or admin tools.
