### ISSUE TITLE
Gutenberg: schedule instead of publish button

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#28213]
In some cases our Gutenberg integration always displays `Schedule` instead of `Publish` button, even when the publish date is set to `immediately`.

**Comment by kwight** [comment]
Strange, I haven't been able to reproduce this on business sites or otherwise. Anyone have any other identifying features to help repro?..

**Comment by gwwar** [comment]
Potentially related https://github.com/WordPress/gutenberg/issues/11554

**Comment by vindl** [comment]
> Potentially related WordPress/gutenberg#11554

It looks like the same issue, although I've been noticing this in Calypso long before this core PR was merged.

**Comment by vindl** [comment]
@arunsathiya since you've been able to reproduce this, could you open `wp-admin/options-general.php` for your test site that you are seeing this on and let me know what's your timezone setting?

**Comment by arunsathiya** [comment]
@vindl I had looked at timezone settings earlier, but good reminder! I just tested again and it seems to be related to timezone settings. 

I live in UTC+0530, but going behind UTC shows `Publish` for me.

<img width="785" alt="screenshot 2018-11-07 at 18 50 29" src="https://user-images.githubusercontent.com/18581859/48133822-088e3080-e2be-11e8-994f-25f0d6894d4f.png">
<img width="1257" alt="screenshot 2018-11-07 at 18 50 34" src="https://user-images.githubusercontent.com/18581859/48133823-0926c700-e2be-11e8-82c7-336326ed098d.png">

Coming back to UTC, UTC+0530 or anything beyond that shows `Schedule` for me.

<img width="778" alt="screenshot 2018-11-07 at 18 46 56" src="https://user-images.githubusercontent.com/18581859/48133777-f01e1600-e2bd-11e8-9e98-99a8a66fcb63.png">
<img width="1258" alt="screenshot 2018-11-07 at 18 47 20" src="https://user-images.githubusercontent.com/18581859/48133779-f01e1600-e2bd-11e8-81f1-13503bae9434.png">

**Comment by caimin-j** [comment]
@thehenrybyrd and I discovered/tested this too. 

We only saw the schedule button when the timezone was greater than UTC +0 (further east than London), regardless of whether the timezone was set numerically (UTC +1) or using the location (Rome).

If the timezone is less than UTC+0 (further west than London), we saw the Publish button as expected, regardless of whether the timezone was set numerically or by location.

We tested with different plans and saw the same behavior.

Though we tested with these scenarios:

* Calypso and Gutenberg via wpcalypso.wordpress.com
* Calypso live via WordPress.com
* WP Admin on a Pressable site with Gutenberg
* Calypso without Gutenberg via wpcalypso.wordpress.com

we were only able to reproduce the bug with Calypso and Gutenberg via wpcalypso.wordpress.com.

**Comment by alisterscott** [comment]
Noticed this for all my sites which are set to Brisbane (UTC+10) for Calypso Gutenberg (not wp-admin) for Simple Sites

<img width="1145" alt="screen shot 2018-11-23 at 3 59 37 pm" src="https://user-images.githubusercontent.com/128826/48929945-cc530500-ef38-11e8-93ca-27287bcf475c.png">
