### ISSUE TITLE
American Express card is showing VISA icon on Billing page

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#28227]
I have a user who reported that their Billing page is showing the VISA icon next to their American Express card. 

#### Steps to reproduce
1. Using account with Amex card saved
2. Go to Manage Purchases --> Billing History
3. Scroll down and look at list of credit cards and you will see the American Express with the VISA icon

`1535933-zen`

**Comment by alisterscott** [comment]
Fix in https://github.com/Automattic/wp-calypso/pull/28229
