### ISSUE TITLE
Gutenburg: Video formatting issue and error after saving in Calypso

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#28233]
#### Steps to reproduce
1. Create and save a post/page using Gutenberg with a video inside of a video block
2. View and Update/Save the same page using the Classic editor in Calypso (no actual edits need to be made to the page, only saving is necessary)

#### What I expected
I expect no changes to be made to the post

#### What happened instead
* Formatting is lost on the page such as paragraph spacing. Per this P2 post I understand that we are aware and are looking to resolve this:
p3fqKv-6z9-p2

* The video on the page also shrinks in size, but remains operational: Screenshot one is after the page is created in Gutenberg. Screenshot two is after the page is Updated/saved in Calypso.

##Screenshot one:
![screen shot 2018-11-01 at 11 04 50 pm](https://user-images.githubusercontent.com/33190975/47893486-2f1a1a80-de2b-11e8-9446-1098319b40e0.jpg)

##Screenshot two:
![screen shot 2018-11-01 at 11 04 57 pm](https://user-images.githubusercontent.com/33190975/47893485-2c1f2a00-de2b-11e8-8ee1-4c67c0da6672.jpg)

* If we return to Gutenberg we find an error on the Video block:
![screen shot 2018-11-01 at 11 05 56 pm](https://user-images.githubusercontent.com/33190975/47893438-faa65e80-de2a-11e8-81ad-0d227b580512.jpg)

Using the Resolve button here displays the block's HTML as such and the After Conversion solution is to delete it:

```
<figure class="wp-block-video"><video src="https://videos.files.wordpress.com/QKaCWyGi/mvi_3379_hd.mp4" controls="controls" width="300" height="150"></video></figure>
```

#### Action taken to revert the errors
1. Visit the page's editor in Gutenberg
2. Use the Update button to save the page (no edits are necessary
3. Formatting to the page is restored, but the video error and reduced size remains
4. Remove and replace the Video block, and save again
5. Formatting and blocks restored completely

#### Context / Source
This was reported in 7717189-hc

#user-report

**Comment by gwwar** [comment]
Closing this out since I think https://github.com/Automattic/wp-calypso/issues/29328 and pafL3P-cU-p2 should cover this. (Work is ongoing)
