### ISSUE TITLE
Gutenberg: update existing post

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#28246]
Updating existing posts no longer works. It looks like it was broken recently so it might be the result of 4.1 update or some of the package updates.

**Comment by gwwar** [comment]
Looks like the post publish flow for existing posts doesn't work. It may be an issue with the sidebar structure or not detecting that there are changes available from the editor.

**Comment by gwwar** [comment]
One hint is that this should say Update instead of Publish

![screen shot 2018-11-02 at 3 11 20 pm](https://user-images.githubusercontent.com/1270189/47943048-967aad80-deb1-11e8-88ee-edf78982a4e8.png)

**Comment by gwwar** [comment]
I believe we're showing the PostPublishPanelToggle button here incorrectly, going to check against Gutenberg master for behavior
