### ISSUE TITLE
Gutenberg on Calypso fails for Jetpack sites without Gutenberg active. 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#28251]
#### Steps to reproduce
1. Connect a Jetpack site to wpcom that does **not** have Gutenberg active in any way.
2. In Calypso, navigate to `wordpress.com/gutenberg/post/$SITE`
3. See maybe a flash of the post editor, followed by a WSOG (White Screen of Gutenberg)

#### What I expected
I expected it to not whitescreen, and instead would be able to edit/write the post. 

#### What happened instead
It whitescreened. 

#### Browser / OS version
Chrome/OSX

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/7129409/47931629-be641400-dea5-11e8-9597-2a029a52e030.png)

#### Context / Source
#dogfooding

**Comment by gwwar** [comment]
Thanks for the report, but this behavior is expected until we add in Jetpack version checks / upgrade paths. Note that we don't plan on showing native Gutenberg in Calypso to Jetpack sites until that work is done.

Any opt-in flows will be closer to Calypsoify workflows, but similarly need a version/plugin check. See also p3fqKv-6Fa-p2

**Comment by kwight** [comment]
This is invalid at this point; we've removed Gutenberg on Calypso in favour of #31196.
