### ISSUE TITLE
Gutenburg: HTML is being added inside of the Source Code shortcode

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#28259]
#### Steps to reproduce
1. Create a post/page with Gutenberg deactivated
2. Use the Source Code shortcode:
```
[code language="css"]
Your code here!
[/code]
```
3. Publish the post, it should appear like this on the website: 
![screen shot 2018-11-02 at 6 09 04 pm](https://user-images.githubusercontent.com/33190975/47944595-92a75500-deca-11e8-88cc-91f3af764fa2.jpg)

4. Activate Gutenberg and save/update the post in Calypso or with Gutenberg (no changes need to be made)
5. The shortcode partially breaks and starts displaying HTML on the website:
![screen shot 2018-11-02 at 6 08 47 pm](https://user-images.githubusercontent.com/33190975/47944613-a2269e00-deca-11e8-810b-1715ddaa1755.jpg)

#### What I expected
For the [code] shortcode to continue displaying identically regardless of the editor used.

#### What happened instead
The content inside of the shortcode begins displaying formatting HTML like `<br />` inside of it.

#### Context / Source
#user-report

Reports:
7749118-hc
7743198-hc

**Comment by jeremypaavola** [comment]
This is happening in all WordPress.com and Jetpack documentation.

Examples:

https://en.support.wordpress.com/beginning-html/how-to-make-a-call-to-action-button/
https://jetpack.com/support/publicize/#custom-post-types

I'm going to give this a high priority as it's going to confuse anyone who doesn't know better and tries to copy-paste from the documentation.

**Comment by mkaz** [comment]
This should now be fixed, there was a conflict in priorities with the [code] shortcode and Gutenberg processing of wpautop.

For internal, fixed in D20330
