### ISSUE TITLE
Import in Signup: Add copy informing the customer that the site name is being chosen for them & they can change it later.

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#28263]
p8F0Ux-1gL-p2

**Comment by mattsherman** [comment]
Where in the flow should we tell the customer this?

**Comment by jblz** [comment]
Good question :)

I'm leaning toward a quick "Don't worry..." notice at the bottom of the "auto-continuing" last step of the flow just as a slight reassurance.

**Comment by dezzie** [comment]
Update to this stale issue. We're adding the domains step in Signup for importers, and we're not choosing a site name for them the same way anymore, they will have input during that step. Going to close this issue.
