### ISSUE TITLE
Onboarding Checklist: Atomic sites are getting the wrong message and an error

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#28282]
#### Steps to reproduce
1. SSP into AT user `jcmunich`
2. Go to Stats
3. You'll get the Onboarding Checklist message saying the email needs to be verified, even though the email has already been verified.
4. Try clicking the `Checklist` link, it'll send you to an error. 

#### What I expected
The message should show the email as already verified, and the checklist link should send them to the checklist.

#### What happened instead
The message shows the email as not verified, although it has already been verified, and the checklist sends them to this error:
![Checklist not available](https://cdn-std.dprcdn.net/files/acc_652292/8te4eI)

#### Browser / OS version
Firefox 63.0
OS Mojave 10.14

#### Screenshot / Video
What the user sees:
![Screenshot](https://cdn-std.dprcdn.net/files/acc_652292/TcWhYs)

#### Context / Source
I got two users in chat with this issue. #user-report

**Comment by benchilcote** [comment]
I am also seeing this for user rotarywatchesadmin on rotarywatchesportal.com
I was able to reproduce via SSP. 
1544223-zen

**Comment by chad1008** [comment]
Also reported in 1544238-zen

**Comment by sashastone** [comment]
Another report 1544476-zen

**Comment by jenlynnemc** [comment]
Another report 7811537-hc
Site: https://mirrorrenovations.com/
User: mirrorrenovations

**Comment by correliebre** [comment]
Another one in 7809763-hc
Site: https://adultstruggles.com
User: adultstruggles

**Comment by sashastone** [comment]
Another report 1544490-zen
Site: https://margaronegiovanni.com/
User: marganino39

**Comment by benchilcote** [comment]
Another one in 1544593-zen

**Comment by mdrockwell** [comment]
Another Report: 6660070-hc
Followup Ticket: 1544593-zen
Site: theblackbeltmillionaire.com 
User: blackbeltmillionaire87

**Comment by desnum** [comment]
**Another report**
6846275-hc
Site: businesschecklist.com
User: knaser87

**Comment by deancroyal** [comment]
Report: 7809791-hc
Followup: 1544714-zen
Site: observantiae.com
User: observantiae

**Comment by ezebecke** [comment]
Another Report: 3674057-hc
Followup Ticket: 1544490-zen
Site: healthandwellbeings.org
User: healthandwellbeings

**Comment by serabi** [comment]
Another report at 7815170-hc
Site: vahvakivuton.com

**Comment by serabi** [comment]
Another report: 3892591-hc
site: lifestyle48.com

**Comment by kriskarkoski** [comment]
I've added high priority to this as it seems to be affecting every Atomic user I have helped today.

**Comment by edequalsawesome** [comment]
Another report: 7816864-hc
site: ruemorin.com

**Comment by davipontesblog** [comment]
one more: 7816965-hc

**Comment by sashastone** [comment]
7817831-hc

**Comment by katiebethbrown** [comment]
5859883-hc as well.

**Comment by xpurichan** [comment]
7819208-hc

**Comment by synora** [comment]
7415656-hc
Follow up ticket 1545140-zen.

**Comment by synora** [comment]
7392735-hc
Follow up ticket 1545148-zen.

**Comment by mdrockwell** [comment]
Another report here: 7817522-hc
Followup Ticket: 1544953-zen
Site: myelliottassociates.com
User: easalescom

**Comment by jesscga** [comment]
Reported in 5816265-hc
User: kamaratonline
Site: https://kamaratweb.sk/

**Comment by GeoJunkie** [comment]
Reported in 7821429-hc
User: parkinsonscore
Site: parkinsonscore.com

**Comment by samiff** [comment]
Reported in 7822299-hc
User: 107145667
Site: sportgrill.blog

**Comment by sashastone** [comment]
Reported in 6619931-hc
User: tamarackmountainstudio
Site: tamarackmountainstudio.com

**Comment by nagpai** [comment]
4087217-hc
coffeefernweh

**Comment by jordesign** [comment]
Reported in https://hud.happychat.io/chat/7827466
User: asimplepieceofme
Site: https://asimplepieceofme.com/

**Comment by kristarella** [comment]
`foodingaroundwithjon` 7827270-hc

**Comment by grvrulz** [comment]
`richyarticle` 7830178-hc

**Comment by fashuvo** [comment]
Reported in 7772592-hc
User: dsautoenterprise
Site: dsauto.com.my

**Comment by stefancln** [comment]
Another report in 5807997 - hc
User: travelfoodclickrepeat

**Comment by ivan-ottinger** [comment]
Another report in 1546516-zen
User: `atrevido2`

**Comment by grvrulz** [comment]
7835179-hc
innovationtechnologyoffice

**Comment by kylemcph** [comment]
1546608-zend
user: `marcosplanet`

Spanish speaking user

**Comment by rezzap** [comment]
130083553-hc
User: bindupowercoach
Site: bindupowercoaching.com

**Comment by cecilearkay** [comment]
Reported in: 5950430-hc and 7831800-hc
Both are ESL users with AT sites.

**Comment by eduardozulian** [comment]
7840426-hc

**Comment by cecilearkay** [comment]
Another one reported in 7605959-hc

**Comment by mlaetitia** [comment]
Both AT sites:

7836633-hc
User: flrspectron
site: flrspectron.blog

6253211-hc
user: ziyaadsayed17
site: royalcarpaints.co.za

**Comment by sophiegyo** [comment]
Report for:

Site - happyvilli.com
User - thehappyvilli
#1545065-zen

**Comment by jacoswan** [comment]
Another AT site:
#142292309-hc
Site - thegreyhoundburtononthewolds.co.uk
User - gingerbreadpromotions

**Comment by rezzap** [comment]
7785457-hc
Site: https://embracefaithfully.com
User: embracefaithfully

**Comment by sourourn** [comment]
AT site:

Chat - #7842716-HC
Site - sino40.de 
User - ocean1226

**Comment by benchilcote** [comment]
7843466-hc

**Comment by liviopv** [comment]
7840164-hc

**Comment by deancroyal** [comment]
7811763-hc
Site: ilikedeals.net
User: likedeals

**Comment by synora** [comment]
7844428-hc
Follow-up ticket: 1547508-zen
Site: https://lumingo.blog

**Comment by sashastone** [comment]
7846865-hc
Site: https://hammy64000.com/
Username: hammy64000

**Comment by sashastone** [comment]
7847096-hc
Site: https://laggas.com/
Username: gedealit

**Comment by aisajib** [comment]
7825446-hc
Site: support911.net
Username: support911ltd

**Comment by Janna-Pieler** [comment]
7849360-hc
Site: myelliottassociates.com
Username: easalescom

**Comment by phillipcornwell** [comment]
7847591-hc
Site: laggas.com
Username: gedealit

**Comment by eduardozulian** [comment]
1547991-zen

**Comment by eduardozulian** [comment]
Got a report from an account without any Atomic sites: 1547795-zen

As you can see in the screenshot, we 22% message blinks when you refresh the page and then suddenly disappears:

![nov-06-2018 17-12-22](https://user-images.githubusercontent.com/1136160/48087797-66037e00-e1e7-11e8-9278-d72eabb3c0c9.gif)

**Comment by selectedselections** [comment]
7851354 -hc
Site: gatewayholiday.ca
User: gatewayholiday1

**Comment by wynwin** [comment]
A couple more reports of this here:

7814523-hc
Site: ambitiousbaba.com
Username: ambitiousbaba

6224002-hc
Site: accesstuolumne.org
Username: jerry889818811

**Comment by selectedselections** [comment]
7850754 - hc
user - reneacademy
site - reneacademy.co.uk

**Comment by edequalsawesome** [comment]
1390028-hc

User: apynes
Site: servuspartners.com

**Comment by sashastone** [comment]
5476158-hc
https://gibtdirdaslebenzitronen.blog/
User: gibtdirdaslebenzitronen

**Comment by jamiepalatnik** [comment]
Another report in #6451369-hc

**Comment by AtrumGeost** [comment]
Another report in 7632171-hc

**Comment by KristinaKay** [comment]
Another 7521328-hc

**Comment by KristinaKay** [comment]
7849696-hc

**Comment by katiebethbrown** [comment]
4015907-hc

**Comment by Piyopiyo-Kitsune** [comment]
798251-hc

**Comment by serabi** [comment]
6863255-hc
site: idoleyes.com.au

**Comment by arunsathiya** [comment]
5362212-hc

**Comment by arunsathiya** [comment]
#5362212-hc

**Comment by Piyopiyo-Kitsune** [comment]
7428649-hc

**Comment by cecoates** [comment]
7111808-hc

**Comment by krutidugade** [comment]
Another report here - 7546754-hc
Username - bhatimcom
Site - toponse.com and owtar.com

**Comment by sophiegyo** [comment]
Another report: 4332490-hc
User: movimientossismicosec
Site: movisis.org

User is admin/owner.

**Comment by StefZarb** [comment]
Reported in 1549436 -zd
User: omogoe
Site: bedicaldoctor.com

**Comment by krutidugade** [comment]
Another report - 4303836-hc
Username - ngwedi1
Site - ngwedi.com

**Comment by sourourn** [comment]
7864488-HC
Username: briannns
Site: netvision.store

**Comment by GeoJunkie** [comment]
7847130-hc
User: jerwinpastoral
Site: topeventdestinations.com

**Comment by taggon** [comment]
@GeoJunkie I tested on the site and it looks working well now.

**Comment by cecoates** [comment]
7880176-hc

sportgrill.blog
jamestgregoryblog

Anecdotally, both users I've reported had sites where the IP wasn't being proxied.

Pointing it back to WP.com and proxying the domain *tentatively* seems to have fixed it for me. Adding that here in case it's related.
