### ISSUE TITLE
Gutenberg: tooltips cut off by masterbar in wp-admin

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#28287]
Some of the Gutenberg tooltips in wp-admin are cut off by the masterbar.

![tooltip-off-screen](https://user-images.githubusercontent.com/2036909/48013149-a680d000-e0f1-11e8-89cf-aacadbf9d673.png)

cc @Automattic/lannister @georgeh

**Comment by kwight** [comment]
Lower priority since we're starting users in fullscreen mode.

**Comment by Copons** [comment]
This shouldn't be part of the Calypso integration, as Calypsoify removes the fullscreen toggles.
So, unless we missed some toggle (very possible), this is part of the Gutenberg in WP-Admin project (Tinker, IIRC)

**Comment by gwwar** [comment]
You can still see it this way by visiting /wp-admin root then crafting a post. +1 on the low priority thoufgh

**Comment by jordesign** [comment]
Scrubbing this - I'm unable to recreate this within the current iteration of the Block Editor which loads full-screen in all instances. Closing this as not reproducible.
