### ISSUE TITLE
Purchases: add number of licenses to Google Apps title

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#283]
Originally reported by @scruffian.

The title of Google Apps should also contain the number of users attached to the purchase:

<img width="728" alt="screenshot 2015-10-29 22 49 25" src="https://cloud.githubusercontent.com/assets/275961/10834245/9e3b647c-7e8f-11e5-953b-d74546b11c04.png">

**Comment by Lochlaer** [comment]
@fabianapsimoes Can we change that to *licenses* instead of *users*? Since this is in /purchases, it makes more sense to say *licenses* since users buy *licenses*, not *users*. 

Or we could do it like so: 

*2 licenses, 2 users* or *2 licenses, 1 user* (depending on the account)

**Comment by fabianapsimoes** [comment]
After some investigation, @scruffian learned that Google Apps purchases create one subscription per license. This means this task is more involved than just showing a number. We would have to group the subscriptions, and ensure that whatever happens to one happens to another. 

I'm not sure the impact of this change is worth the effort of implementing it. Calling it a won't fix, but @Lochlaer feel free to reopen if you believe this is higher impact than I'm estimating.
