### ISSUE TITLE
People: Accepting a follower invitation doesn't respect the default delivery settings

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#2830]
When you follow a site, your delivery settings for notifications from that site should match your Default Email Delivery setting here: https://wordpress.com/me/notifications/subscriptions

I confirmed that when I follow a site normally, my default delivery settings are respected. However, if I am invited to follow a site, after I accept the invitation the site is always set to deliver instant email notifications.

Steps to reproduce:

1. On a test account, set your Default Email Delivery setting to something other than "Send email instantly"
2. From your account, send an invitation to the test account to follow a public blog
3. Accept the invitation from your test account
4. Check your notification settings for the followed site at https://wordpress.com/following/edit

Result: The "Emails for new posts" setting is always enabled, with instant notifications selected

**Comment by ebinnion** [comment]
@roccotripaldi is currently working on an API patch for this so I have assigned him to the issue.

**Comment by roccotripaldi** [comment]
This was fixed in r130400-wpcom
