### ISSUE TITLE
Calypso global styles leaking to Gutenberg `SelectControl`

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28309]
When using Gutenberg's `SelectControl` in a block, it looks different in wp-admin and Calypso:

<img src="https://user-images.githubusercontent.com/87168/48071720-9f39ef00-e1e3-11e8-8bcc-6d5e48fef6ed.png" width="300" />

This is because in Calypso some of the Calypso CSS resets leak into Gutenberg core components, specifically these lines in case of `select` tag:

https://github.com/Automattic/wp-calypso/blob/8ed68be0687057b69b25473e72b2c7e213309041/assets/stylesheets/shared/_forms.scss#L192-L193

Number input doesn't look exactly like in "native" Gutenberg neither so I suspect some leakage is happening with other form elements, too.

#### Steps to reproduce
Calypso
1. Open https://wpcalypso.wordpress.com/gutenberg/post?flags=gutenberg/block/jetpack-preset
2. Insert a Payment button block
3. Observe currency and price inputs

wp-admin
1. Open https://jurassic.ninja/create/?jetpack-beta&gutenpack&gutenberg&shortlived
1. Set up Jetpack (free plan is ok)
1. Add new post
1. Insert a Payment button block
1. Observe currency and price inputs

#### What I expected
Inputs to look the same.

#### What happened instead
Wonky input sizes at Calypso.

**Comment by gwwar** [comment]
Doesn't appear to be an issue anymore
