### ISSUE TITLE
JPC: improve set up experience

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#28311]
#### Steps to reproduce
1. Connect Jetpack site.
2. Select paid plan.
3. See the set up screen where features are being activated.

See p6TEKc-2o1-p2

![screen-shot-2018-11-01-at-12-52-04-pm](https://user-images.githubusercontent.com/390760/48075038-2da97300-e1da-11e8-8ecf-876e6bb222ce.png)

#### What I expected

- A less laundry list approach to the features that are being activated.
- Better copy in the card itself (`power up your site`).

**Comment by keoshi** [comment]
This is to be replaced by the onboarding checklist, which will also allow us to close this related issue: https://github.com/Automattic/wp-calypso/issues/25582

**Comment by keoshi** [comment]
To be superseded by https://github.com/Automattic/wp-calypso/issues/28421

**Comment by joanrho** [comment]
- delete checkmarks below card
- make card white  and colorize icon
- fix CTA to clarify destinations
