### ISSUE TITLE
Gutenberg: Writing Helper in Gutenberg is non-functional

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#28318]
The writing helper ("copy a post" feature) is non-functional in Gutenberg in wp-admin (with or without a Calypso skin).

#### Steps to reproduce
1. Use a test site that has opted in to Gutenberg.
2. Navigate to the editor in wp-admin.
3. Select "Copy a Post" in the writing helper.
4. Choose a post and select "Copy."
5. In the confirmation dialog, select "Confirm Copy."

Note: If you don't see the Writing Helper in Gutenberg, you may need to enable it by going to the Classic Editor > Screen Options > under Boxes check the box next to Writing Helper.

#### What I expected

I expect the content of the post and the post settings to be replaced with the content and settings from the selected post.

#### What happened instead

Nothing.

#### Browser / OS version

Chrome 70.0.3538.77
macOS 10.14

#### Screenshot / Video

![screenshot 2018-11-06 17 29 33](https://user-images.githubusercontent.com/8658164/48082094-8b918700-e1e9-11e8-9bbb-0aa4308c7af6.png)

#### Context / Source
#dogfooding

**Comment by rachelmcr** [comment]
I checked in the current Gutenberg Calypso implementation and the writing helper isn't included there. Perhaps we should disable it in Gutenberg in wp-admin until the feature works with Gutenberg.

**Comment by kwight** [comment]
Disabling in D20397-code.

**Comment by kwight** [comment]
Merged D20397-code, closing.
