### ISSUE TITLE
Gutenberg: "Extended Settings" post meta boxes can't be moved/collapsed

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#28319]
**Describe the bug**
On WordPress.com there are two post meta boxes (Writing Helper and Likes & Shares) that can appear either below the main Gutenberg editor area or in an "Extended Settings" section in the post settings menu. (Their position in Gutenberg depends on where they are placed in the Classic Editor.)

The post meta boxes have two issues:

- Hovering on the box title shows a drag-and-drop cursor, but the box can't be moved/reordered
- The arrow to collapse/expand the meta box doesn't do anything

**To Reproduce**
1. Go to the Classic Editor (e.g. by editing an existing post in the Classic Editor mode).
2. Enable "Likes and Shares" and "Writing Helper" in the Screen Options at the top of the editor screen.
3. Open the Gutenberg editor (e.g. start a new post).
4. Find the "Likes and Shares" and "Writing Helper" meta boxes and try to move or collapse them.

**Expected behavior**
I expect the cursor to reflect the action I can take (e.g. only see a drag-and-drop cursor if I can move the post meta box), and to be able to collapse each post meta box.

**Screenshots**

Post meta boxes in Gutenberg (shown in both available positions, which can be changed by dragging and dropping the boxes in the Classic Editor):

<img width="1279" alt="screenshot 2018-08-01 17 48 11" src="https://user-images.githubusercontent.com/8658164/43536377-5b2477ca-95b4-11e8-8485-187221f773a2.png">
<img width="326" alt="screenshot 2018-08-01 17 51 02" src="https://user-images.githubusercontent.com/8658164/43536378-5b40f8f0-95b4-11e8-8141-4fd128655670.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: Chrome
 - Version: 67

**Comment by codebykat** [comment]
Likes and Sharing is now a real Gutenberg extension as of https://github.com/Automattic/jetpack/pull/12032 and the Writing Helper has been removed.
