### ISSUE TITLE
Gutenberg: Wide and Full alignments options appear in WP Admin, but not Calypso

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#28313]
When using a theme with wide alignment support, the option is available in WP Admin, but it doesn't appear to be available in Calypso.

This came up with one of our free themes, which we just added Gutenberg support to.

This may be functionality still to be added down the road, but I wanted to note it just in case!

#### Steps to reproduce
1. Start with a theme that supports wide alignment -- some options on WP.com include Radcliffe 2, Business, or Dyad 2.
2. In WP Admin, edit a post, and add a gallery block; click on it and note the alignments.
3. Fire up a new post in the Calypso editor, and add a gallery block, and click on it to note the alignments.

#### What I expected
That the wide and full alignment options would be available in Calypso, too.

#### What happened instead
WP Admin shows the options, but Calypso does not. 

#### Browser / OS version
* Firefox 63.0, Mac OS X 10.13.4 (though I can recreate in Chrome 70.0.3538.77 as well). 

#### Screenshot / Video

In WP Admin:
![image](https://user-images.githubusercontent.com/177561/48077621-98d45480-e19c-11e8-8cea-86e58222b863.png)

In Calypso: 
![image](https://user-images.githubusercontent.com/177561/48077573-76423b80-e19c-11e8-9fde-46e51556e63b.png)

#### Context / Source
This came from feedback on this post: p7DVsv-5CH-p2

**Comment by gwwar** [comment]
@laurelfulford to clarify did you test this in wp-admin or in horizon.wordpress.com/gutenberg ?

**Comment by laurelfulford** [comment]
I originally tested in wp-admin and wpcalypso.wordpress.com/gutenberg/post, but when I try from horizon.wordpress.com/gutenberg I see the same issue (no wide and full alignments).

**Comment by gwwar** [comment]
I'll check against Gutenberg master as well.
