### ISSUE TITLE
Gutenberg: Identical embeds are not embedded in editor

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#28320]
**Describe the bug**
If multiple copies of the same embed (same type and URL) are added to Gutenberg on WordPress.com everything but the first embed will not be shown embedded in the editor and instead shows a continuous embedding spinner. The embeds do work properly on the front-end

**To Reproduce**
1. Add an embed (seen with YouTube and Reddit) and insert a valid URL
2. Add another identical embed with the same URL
3. The second embed does not load, but does work on the front-end

**Expected behavior**
All embeds to load properly in the editor as they do on a WordPress.org site

**Screenshots**
WordPress.com (k2testblog.wordpress.com)

![screen shot 2018-08-07 at 3 01 34 pm](https://user-images.githubusercontent.com/1900444/43796897-93df3d54-9a53-11e8-9f13-7b0084f4340b.png)

WordPress.org (Atomic)

![screen shot 2018-08-07 at 3 01 57 pm](https://user-images.githubusercontent.com/1900444/43796915-a5c92de0-9a53-11e8-9cb8-0a5c93761a72.png)

Works on front-end

![screen shot 2018-08-07 at 3 01 42 pm](https://user-images.githubusercontent.com/1900444/43796884-8da3ec3c-9a53-11e8-9f7e-bc3ea1d3ad65.png)

**Desktop (please complete the following information):**

OS: OS X 10
Browser: Chrome
Version 67.0.3396.99

**Additional context**
Observed on Aug. 7. No version available as on WordPress.com

**Comment by gwwar** [comment]
I wasn't able to reproduce this. Going to close due to age, but please reopen if this is still an issue.
