### ISSUE TITLE
Gutenberg: Attachment in WP-Admin Media Library mistakenly shows as (Unattached)

### ISSUE THREAD

**Issue by keithlocka8c** [Automattic/wp-calypso#28325]
When viewing a list of images in the WP-Admin Media Library, an image will show as "(Unattached)", when it may very well be attached to a post created with Gutenberg.

This isn't always the case however: It remains as "(Unattached)" on Guten-posts when the image is used as a Featured Image, or in a image-type block. It does however show as "attached" when added to a Classic Editor block.

(Side note: and as has happened since the early days, when the image is removed from the Classic Editor block, we must manually "Detach" it from the Media Library. It doesn't magically unattach.)

1. Go to Media Library in WP-Amin.
2. Upload an image, make note that it is Unattached.
3. Create a new Guten-post, and choose that image as the Featured Image, or add to any other Image-type block.
4. Refresh the WP-Admin Media Library, see that it still shows as Unattached.
5. Go back to the post and add the image in the Classic Editor block.
6. Refresh the WP-Admin Media Library, see that only now it shows as Attached.

**Comment by lancewillett** [comment]
As noted this happens in Classic Editor as well. Closing for now. Let's raise in core Gutenberg or core WordPress Trac if it still needs attention.

**Comment by marcuswisecaesar** [comment]
This issue was raised in a ticket 2595553-zd and the user is asking that we make note of the issue with being unable to determine which images are actively in use on a site and which are not.

**Comment by kriskarkoski** [comment]
Closing as this is being worked on through this issue on the core side: https://github.com/WordPress/gutenberg/issues/12753
