### ISSUE TITLE
Gutenberg: Vimeo embeds don't fill available space

### ISSUE THREAD

**Issue by georgeh** [Automattic/wp-calypso#28323]
**Describe the bug**
Vimeo embeds are using a small size, even when a larger size is appropriate.

**To Reproduce**
1. Go to /wp-admin
2. Click on that Gutenberg link at the bottom of the menu. That takes you to the demo page
3. Scroll down to the Vimeo embed at the bottom
4. See how the video is crammed up in the left corner

**Screenshots**
How it looks:
![screen shot 2018-10-16 at 3 23 19 pm](https://user-images.githubusercontent.com/128240/47112684-11429800-d225-11e8-98c8-1330c0a5934e.png)

How it should look:
![screen shot 2018-10-17 at 3 57 08 pm](https://user-images.githubusercontent.com/128240/47112740-359e7480-d225-11e8-896b-592d5b083883.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 69

**Comment by torres126** [comment]
The Vimeo block in the Gutenberg demo post uses the Wide alignment. Jetpack's responsive video clashes with Gutenberg's responsive embed support, which causes an issue. That's being tracked at Automattic/jetpack#10678.

@georgeh I wonder if that's what you're seeing here?

**Comment by jeherve** [comment]
This will be fixed in https://github.com/Automattic/jetpack/pull/10880
