### ISSUE TITLE
Gutenberg: Embed: Remove WordPress embed

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#28326]
**Describe the bug**

The WordPress embed block is available on WordPress.com, but trying to add a WordPress embed always results in an error:

> Sorry, we could not embed that content.

On the front end, a plain link to the WordPress post appears.

**To Reproduce**
1. Go to a Gutenberg-enabled WordPress.com site.
2. Start a new Gutenberg post.
3. Add a WordPress embed block.
4. Paste a link to a WordPress post and click the Embed button.
5. See an error in the editor.
6. Preview the post and see the plain link to the post.

**Expected behavior**

The WordPress embed block should not show up since it isn't supported on WordPress.com. Let's make sure to disable this in all wpcom environments.

**Screenshots**

![screenshot 2018-10-30 16 08 01](https://user-images.githubusercontent.com/8658164/47732783-d138d780-dc5e-11e8-92b6-b25459b916f7.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser Chrome 70.0.3538.77

**Comment by arunsathiya** [comment]
Noting that I am still able to reproduce this, and it happens only on Calypsoified Gutenberg. On Gutenlypso, I am seeing a blank, white space instead - logged this here https://github.com/Automattic/wp-calypso/issues/29388

**Comment by alisterscott** [comment]
We've never been able to embed WordPress content for WordPress.com simple sites due to security concerns - even in the classic editor when pasting an oEmbed URL.

Perhaps we can just remove the block from appearing?

**Comment by zdenys** [comment]
Discovered this while I was going through adding all available Blocks into a post. It seems that the block is going to be removed eventually, right?

**Comment by mmtr** [comment]
Removal proposed in D25893-code

**Comment by retrofox** [comment]
> It seems that the block is going to be removed eventually, right?

right

**Comment by mmtr** [comment]
The WordPress embed block should no longer be available after landing D25893-code.
