### ISSUE TITLE
Calypso: Priority Support Feature Tile Sizing on Desktop App

### ISSUE THREAD

**Issue by dkmyta** [Automattic/wp-calypso#28336]
#### Steps to reproduce
1. Open WordPress.com Desktop App
2. Navigate to "Plan" Tab
3. Select "My Plan" Menu Item
4. View Plan Features
5. Resize your viewing window from full screen to various other widths
6. Repeat steps for site with each plan (Personal, Premium, Business)

You will notice that for screen widths less than full screen and before the structure switches from two tiles per row to one for tablet and mobile views, the first tile item, "Priority Support" is not the same height as the other surrounding tiles. I have provided a screenshot of this structure for each plan for a visual:

Personal:
<img width="783" alt="personal" src="https://user-images.githubusercontent.com/43220201/48099689-406d7900-e1d5-11e8-9fc4-8a82de4d9e21.png">

Premium (Seems good):
<img width="766" alt="premium" src="https://user-images.githubusercontent.com/43220201/48099711-4cf1d180-e1d5-11e8-9f62-92d38e7d4eb7.png">

Business:
<img width="770" alt="business" src="https://user-images.githubusercontent.com/43220201/48099717-524f1c00-e1d5-11e8-9b31-f36169920657.png">

#### Context / Source
Recognized the issue while testing the new beta version of the desktop app. Issue was visible with the most recently released version and the new beta version of the app.
Reported the issue originally during app testing before identifying it as a Calypso issue.
Testing link: p5T066-Hz-p2
#manual-testing

**Comment by lancewillett** [comment]
This might have been fixed since the report. Please re-open if you can still repeat it.

I tested with various window sizes on Chrome latest and Safari 12.1.1 on macOS 10.14.5.
