### ISSUE TITLE
Onboarding checklist: Confirm email address notice even when it's verified

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#28342]
## Description:

The onboarding checklist shown on a WordPress.com site's dashboard can sometimes show a `Confirm your email address` notice, even though the WordPress.com account's email is verified on https://wordpress.com/me/account

This primarily seems to happen for non-admin team members invited from https://wordpress.com/people/team 

Upgrading them to admin role fixes that. h/t @nagpai

Downgrading them back to the original role does not show this error again

#### Steps to reproduce 

- Start at https://wordpress.com/people/team 
- Invite a WordPress.com user to the site with non-admin role
- Login as that WordPress.com user and on the WordPress.com site's dashboard 

#### What I expected

The `Confirm your email address` notice should not be shown on the onboarding checklist.

#### What happened instead

The `Confirm your email address` notice is shown as a part of the onboarding checklist. The error `Please click the link in the email we sent to {email address}` is seen as well.

Clicking on `Resend email` changes the button `Error`.

#### Browser / OS version

Tested with the following so far:

- Google Chrome Version 70.0.3538.77 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave 
- Firefox Quantum 63.0.1 (64-bit) on macOS 10.14 - Mac OS Mojave 
- Safari Version 12.0.1 (14606.2.104.1.1) on macOS 10.14 - Mac OS Mojave 

#### Screenshot / Video

<img width="993" alt="screenshot 2018-11-07 at 12 08 09" src="https://user-images.githubusercontent.com/18581859/48115811-15912c80-e28a-11e8-9aca-c86744d90812.png">
<div align="center"><sup>Confirm your email address notice on the onboarding checklist shown for non-admin users</sup></div> 

<img width="780" alt="screenshot 2018-11-07 at 12 09 10" src="https://user-images.githubusercontent.com/18581859/48115815-175af000-e28a-11e8-8712-a3c3d238c40e.png">
<div align="center"><sup>Promoting user from editor to admin role</sup></div> 
<img width="992" alt="screenshot 2018-11-07 at 12 09 22" src="https://user-images.githubusercontent.com/18581859/48115816-175af000-e28a-11e8-9fcb-dd40dee4f25d.png">
<div align="center"><sup>Onboarding checklist error no longer seen</sup></div>

#### Related: 

https://github.com/Automattic/wp-calypso/issues/28282 - This shows the same notice for users on the WordPress.com Business plan sites with at least one plugin/third-party theme installed.

**Comment by nerdysandy** [comment]
Reported on 7889134-hc

**Comment by arunsathiya** [comment]
Shared workaround on #1563150-zen

**Comment by tanjoymor** [comment]
Same issue has occurred on: #1563047-zen (provided arunsathiya's workaround)

**Comment by GeoJunkie** [comment]
Also ran into this in #4939267-hc
