### ISSUE TITLE
Reader: Add in-content follow buttons support for Discover articles

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#2834]
Look for links in Discover articles with a `data-blog-id` or a `data-feed-id` and put a Follow button after them, inline.

**Comment by blowery** [comment]
Good test case will be https://wordpress.com/read/post/id/53424024/8946

The link at the end of each section should have a little Follow button after it.

**Comment by blowery** [comment]
Thanks @lancewillett  :)

**Comment by lancewillett** [comment]
Is this still on the radar? Would be cool to see a visual mockup of what it'd look like.

Here's that mentioned test case now (Mac-n-Chrome, logged in as `lancetest35` user).

![screen shot 2016-05-26 at 11 08 54](https://cloud.githubusercontent.com/assets/66797/15585030/3f238012-2332-11e6-8d8f-bd816d82d060.png)

![screen shot 2016-05-26 at 11 09 08](https://cloud.githubusercontent.com/assets/66797/15585044/483e5668-2332-11e6-96a7-a0eab4ad8e3f.png)

**Comment by kjellr** [comment]
I agree, this would be a fantastic enhancement! I think there are a few different ways we could implement this. 

As described in the note above, we could indeed place these buttons inline after the link. I'd imagine those looking something like one of these: 

![0003_04-inline-tiny](https://cloud.githubusercontent.com/assets/1202812/15588681/075cdd92-235d-11e6-89b5-283499800a65.png)
---
![0002_03-inline-small](https://cloud.githubusercontent.com/assets/1202812/15588682/07659cd4-235d-11e6-9526-433ec2252019.png)

I don't think we have tiny buttons exactly like that one anywhere (I grabbed the button height of the "Manage" button in the Reader sidebar, but applied our normal button styles), but if we kept this inline, it'd need to be around that size so it doesn't mess with line heights when placed in the middle of a paragraph.

Alternatively, we could just add these as separate block elements. Those attributes don't exist in any posts to date, so we'll have to start from scratch and add these into posts manually anyway - how exactly we do it is still up for grabs. We could easily use something like `<a href="https://theblog" data-blog-id="12345" class="follow-button">Follow</a>` when we want a follow button, swap that out for buttons in the Reader, and work out a treatment for that class of links on discover.wordpress.com too. 

![0000_01-standard-button](https://cloud.githubusercontent.com/assets/1202812/15588714/2af573a4-235d-11e6-8534-3a14028cf04b.png)

@blowery + @jancavan, any thoughts on those options?

**Comment by jancavan** [comment]
The Follow button next to the site link looks good @kjellr. Perhaps we can just drop the period. We can also just propose a new button style for smaller buttons.

**Comment by jancavan** [comment]
For Site Picks, we display the Follow button in both cards and fullpost, but for Editor's Pick, we only show them in cards. We should add them to Editor's Pick fullpost as well. /cc @jhnstn

**Comment by blowery** [comment]
Closing this one down. For now?
