### ISSUE TITLE
Calypso Stats - Quarter, Year, and All-Time search term lists not working for help.indiamart.com

### ISSUE THREAD

**Issue by zyousafi** [Automattic/wp-calypso#28361]
#### Steps to reproduce
1.  Start here: https://wordpress.com/stats/day/help.indiamart.com

2.  Then click here: https://wordpress.com/stats/day/searchterms/help.indiamart.com?startDate=2018-11-07

3. Then click either one of the following links:
* https://wordpress.com/stats/day/searchterms/help.indiamart.com?startDate=2018-11-07&summarize=1&num=90
* https://wordpress.com/stats/day/searchterms/help.indiamart.com?startDate=2018-11-07&summarize=1&num=365
* https://wordpress.com/stats/day/searchterms/help.indiamart.com?startDate=2018-11-07&summarize=1&num=-1

#### What I expected

That ***search terms*** stats should load for the **Quarter**, **Year**, and **All-Time** lists just like they do for the **Day Summary**, **7 Days**, and **30 Days** lists.

#### What happened instead

A blank page loads.

#### Browser / OS version

* MacBook Pro - macOS Mojave - 10.14.1 (18B75)
* Google Chrome - Version 70.0.3538.77 (Official Build) (64-bit)

#### Screenshot / Video

Screenshot: http://cld.wthms.co/SjOoMj

#### Context / Source

The user is unable to see their **Quarter**, **Year**, and **All-Time** stats for ***search terms*** in **Calypso**.  A blank page loads instead of the statistics.  When the user tries viewing these same lists in **WP-Admin** via the **Jetpack Dashboard**, they work just fine.  The issue is localized to this site and **Calypso**.  Have tried disabling this site's plugins, but that didn't work either.

Have tested this on a few other **AT Sites**, including my own, and the **Quarter**, **Year**, and **All-Time** lists work just fine.

Username: corporateim
URL: help.indiamart.com

**Comment by iamgabrielma** [comment]
I tested this a bit more and I can see the expected stats screen to show up for a second, before the page becomes blank, video can be found here: p9F6qB-1Jq-p2-#comment-9613
