### ISSUE TITLE
Gutenberg: Can't insert a background image for the Cover block 

### ISSUE THREAD

**Issue by youknowriad** [Automattic/wp-calypso#28365]
I'm testing in the horizon environment at the moment, and the cover image is not working as expected. I can't select an image from the media library.

**Steps to reproduce**

 - Insert the cover block
 - Click "Media Library"
 - Select an image
 - Click "Insert"

The media library is closed but the cover block is still showing the placeholder.

**Comment by gwwar** [comment]
Uploading is okay but doesn't appear to connect to the media modal.

**Comment by gwwar** [comment]
Oddly enough uploading, then clicking edit does show the media library correctly.

**Comment by gwwar** [comment]
Also doesn't appear to be wired in for Media & Text

**Comment by kwight** [comment]
Fixed in #29159 .
