### ISSUE TITLE
Gutenberg: autosaves may lose some content

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28370]
We've gotten a report that an autosave caused a paragraph block to disappear! Let's investigate to see if we can reproduce and fix this!

https://horizonfeedback.wordpress.com/2018/11/07/new-wordpress-editor-call-for-testing-and-feedback/#comment-439

> I eventually figured out where to add a paragraph block after the image, added some text, watched the “autosave” message display. Only to have my text in my new paragraph block disappear.

**Comment by kwight** [comment]
Maybe related to #28405

**Comment by gwwar** [comment]
@kwight thanks, I'll close this as a duplicate of https://github.com/Automattic/wp-calypso/issues/28405 unless we get additional reports/steps
