### ISSUE TITLE
App Banner: Notifications screen overlaps app banner

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#28388]
#### Steps to reproduce
1. Using a mobile device (iOS or Android), open https://wordpress.com/ in a web browser.
2. Log in to WordPress.com.
3. Open the notifications tab.

#### What I expected

I expected to see an app banner specific to notifications ("Watch engagement happening") appear at the bottom of the screen, with an "Open in app" call to action. The banner should overlay the notifications drop-down as shown in the designs here: https://github.com/Automattic/wp-calypso/issues/15228

#### What happened instead

On a phone, I didn't see the app banner at all.
On a tablet, I see part of the app banner on the left side of the screen, but it's overlapped by the notifications.

#### Browser / OS version

Safari on iOS 12.0.1 with iPhone XS and iPad Mini
Chrome on Android 8.1.1 with Moto e5 Play

#### Screenshot / Video

Screen from iPad Mini, where you can see that the app banner is there but it's underneath the notifications:

![img_0226](https://user-images.githubusercontent.com/8658164/48201276-95d29300-e359-11e8-8721-4d9158cde0fd.PNG)

#### Context / Source
#manual-testing

cc @kwonye

**Comment by torres126** [comment]
Has this been fixed?

<img width="722" alt="Screenshot 2019-06-04 at 17 42 25" src="https://user-images.githubusercontent.com/43215253/58897426-315d9380-86f0-11e9-843e-6faaa751c4f6.png">

**Comment by sixhours** [comment]
No longer able to reproduce this one, so I think it was fixed, but I haven't been able to trace that back to a specific commit. Please reopen this issue if you can still reproduce it!
