### ISSUE TITLE
Purchases: Update the successful renewal notice to make it more personal

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#284]
Originally reported by @scruffian.

It should say:
> Success! You renewed (this) for one year, until (date). We sent your receipt to (email).

**Comment by scruffian** [comment]
@mikeshelton1503 and @ranh, given that users will see this information on the page they are redirected to, do you think this change is useful still?

**Comment by ranh** [comment]
Here is an example of the current notice:

<img width="943" alt="ranimac3 screenshot 2016-06-08 at 13 19 15" src="https://cloud.githubusercontent.com/assets/426518/15891443/298b5b94-2d7d-11e6-91ba-9a14e8955cb2.png">

I like the additional context provided in the message suggested above. However it ignores automatic renewal. 

That said, the current notice ignores issues with enabling automatic renewal, and it may say that automatic renewal is enabled even if it isn't (as in the screenshot above, renewed using credits).

I suggest we use the message suggested above if automatic renewal is not enabled. 

If it is enabled:

> Success! (this) is renewed for one year, and will renew automatically in the future. We sent your receipt to (email).

**Comment by mikeshelton1503** [comment]
> given that users will see this information on the page they are redirected to, do you think this change is useful still?

I agree, I don't think this is a necessary change. The information is there on page as you mentioned. The notice's purpose should be to acknowledge successful completion of the transaction. The proposed message would be too long for a notice.

> That said, the current notice ignores issues with enabling automatic renewal, and it may say that automatic renewal is enabled even if it isn't (as in the screenshot above, renewed using credits).

Good catch, but that's a separate issue.

**Comment by scruffian** [comment]
@ranh opened https://github.com/Automattic/wp-calypso/issues/5888 to track his bug, so we can close this.
