### ISSUE TITLE
People: Declining an invitation leaves the invitation pending (for both the inviter and invitee)

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#2840]
When an invitee clicks the "Accept Invitation" button in an invitation email, they are taken to a screen where they can join the site or decline the invitation:

![screen shot 2016-01-27 at 6 20 05 pm](https://cloud.githubusercontent.com/assets/8658164/12623555/9c90248a-c522-11e5-845b-909c47b64ae3.png)

If I decline the invitation, I expect the invitation to be effectively cancelled:
- I expect the inviter to get notification that the invitation was declined (e.g. email notification)
- I expect the "Past Invitations" section under Users > Invite New in wp-admin to show that the invitation was declined
- I expect that my invitation is now cancelled/invalid

Instead, the invitation is still pending, so declining the invitation is no different from ignoring the invitation in the first place:
- The inviter gets no notification
- The invitation under Users > Invite New is still listed as Waiting
- If I click "Accept Invitation" in the invitation email again, the invitation is still valid and I can choose whether or not to accept the invitation again

In the past, there wasn't a way to actively decline invitations. If we offer a "Decline" button, I'd expect it to actively decline the invitation in a way that invalidates the invitation. If we don't plan to include that kind of behavior, it makes more sense to me to display a "Cancel" button of some kind — that way, you can cancel out of accepting the invitation, but it doesn't create the expectation that you are actively declining.

**Comment by ebinnion** [comment]
I don't believe there is an existing "Decline" functionality. With the current invite system, you decline by closing your email. We could build it, but I don't believe it's in the scope of this release.

There is existing "delete" functionality that we could hook into, but I don't like the idea of allowing an invited user to delete an invitation from a site they don't manage.

So, my preference is to update the wording on the button to be more explicit as to what is happening. "Cancel" or "Ignore" seem like appropriate options.

**Comment by lezama** [comment]
> So, my preference is to update the wording on the button to be more explicit as to what is happening. "Cancel" or "Ignore" seem like appropriate options.

:+1:
