### ISSUE TITLE
Question: Can I host Calypso on a public domain & use it for a personal or commercial project?

### ISSUE THREAD

**Issue by chrisjacob** [Automattic/wp-calypso#28411]
#### Background
The [GNU GPL 2.0 License](https://github.com/Automattic/wp-calypso/blob/59bdfeeb97eda4266ad39410cb0a074d2c88dbc8/LICENSE.md) for Calypso allows for custom projects (personal or commercial - provided you follow the license rules), and the [Calypso](https://developer.wordpress.com/calypso/) website also encourages forking Calypso to make something of your own...

> ... view the code yourself and contribute to it, which we’d love, or fork it and make it something all your own.

However, in [/docs/install.md](https://github.com/Automattic/wp-calypso/blob/59bdfeeb97eda4266ad39410cb0a074d2c88dbc8/docs/install.md) it says:

> To run Calypso locally, you'll need to add `127.0.0.1 calypso.localhost` to [your hosts file](http://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/), and load the app at [http://calypso.localhost:3000](http://calypso.localhost:3000) instead of just `localhost`. This is necessary, because when running locally Calypso is using the remote version of the WordPress.com REST API, which allows only certain origins via our current authentication methods.

#### Question 1
_Could someone please clarify if Calypso can be hosted on a public domain e.g. example.com (not wordpress.com or calypso.localhost:3000)?_

**Why?**
I'd like to Fork the repo, make customisations to the Authoring and Reader UX and add some other features, then host this custom build on my own domain. Anything valuable that I build I'd love to contribute back to the core project - but because my ideas may not align with the core project vision I'm trying to figure out if it can have it's own home on my own domain ...or whether the WordPress.com REST API would block my domain/origin?

#### Question 2
Calypso is soooo beautiful. While it's not intended to be used as a framework (like Bootstrap or RoR), it has so many valuable components, incredible UI/UX, and a powerful API that would make it a perfect foundation for experimenting and building Minimum Viable Product (MVP) publishing apps. This could both expand the WordPress dev community and the democratisation of publishing. 

_Would Automattic consider encouraging this culture of forking & experimentation on Calypso with a short docs guide (similar to the [Calypso "Hello, World" guide](https://github.com/Automattic/wp-calypso/blob/59bdfeeb97eda4266ad39410cb0a074d2c88dbc8/docs/guide/hello-world.md))?_

**Thoughts**
If I figure this out over the next few weeks I'll happily contribute back a guide (but some initial guidance from an expert would really help get me started on the right path 😺). Some things I'm trying to figure out:

1. How to easily host Calypso (Node) and WordPress (PHP) publicly (thinking DigitalOcean)
2. How to setup DNS for Calypso and WordPress on the same domain (....for Wordpress.com it seems it has Calypso on the root domain... so where on the domain is the core WordPress install used for Multisite?)
3. How to have a custom WordPress install configured for Multisite and allowing users to onboard to create their own "sites" (perhaps collaborating with [WP Ultimo](https://wpultimo.com/) for a more feature rich solution e.g. paid sites)
4. All users Login/Registration via [WP Connect](https://developer.wordpress.com/docs/wpcc/) ...similar to Gravatar hit URL https://wordpress.com/start/wpcc for registrations. (Adds more users to WordPress + provides easy access to existing WordPress community)
5. All sites running JetPack (Free), and option to upgrade to paid JetPack plan to unlock features. (Allows site to show up in Calypso)
6. All sites on subdomains with HTTPS (... unfortunately only [Cloudflare Enterprise customers can proxy wildcard records](https://support.cloudflare.com/hc/en-us/articles/200169356-How-do-I-use-WordPress-Multi-Site-WPMU-With-Cloudflare-) - so looking for alternative options)
7. How to scope the posts seen in Calypso Reader to a particular Multisite domain e.g. *.example.com (seems like I'd need to get all results from [/read/following](https://developer.wordpress.com/docs/api/1.1/get/read/following/) then filtering the results on the clientside - not pretty, but workable)
8. How to ensure the content posted from this custom app stays compatible (or degrades gracefully) when viewed in the WordPress.com Calypso Reader... so the content is still available to everyone!

If you, or someone you know, has successfully forked Calypso for a side project I'd love to chat 😄 

Thank you very much for taking the time to read and share your thoughts - really appreciate your help 🙌

**Comment by blowery** [comment]
Hi @chrisjacob, sorry for the slow response!

For the first question, you can indeed run Calypso on any old host, though it's a fairly untested and unsupported path. If your site is connected to WordPress.com via Jetpack, you could try to use the OAuth auth provider (see the client/config/features/oauth flag and https://developer.wordpress.com/docs/oauth2/) to get access to your individual site. 

If your site _is not_ connected to WordPress.com in some way (either hosted there or connected via Jetpack), then you'd have to come up with a translation layer for all of the API requests we make. That would not be an easy or very supportable path. Most of Calypso is dependant on the API WordPress.com provides; replacing all of that would not be trivial. 

Hope that explains things a bit, do let me know if you have more questions.
