### ISSUE TITLE
Improve account creation screen experience during Jetpack Connection flow

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#28420]
The Sign Up link is hard to find in top right of screen on the WordPress.com login page ("Log in to your WordPress.com account to set up Jetpack"). Screenshot: https://cloudup.com/cwyPlXUj9fn

The Sign-in box assumes user is an existing WPcom member, which more often than not will not be the case. There are only links for lost password and return to wp site below the box.

### **Proposed changes:** 

**Simplest solution:** Move the sign up link to the link stack below the sign in box. Mockup: https://cloudup.com/cPiqQON-_3S

OR 

**Better solution:** Modify the page header to read "Create a WordPress.com account to set up Jetpack", nix the Sign up link in the topnav, and create a text link for "Already have a WordPress.com account?" to place below the box. Mockup:

<img width="1317" alt="modified jpc wpcom login create acct" src="https://user-images.githubusercontent.com/204742/48259206-8dd92880-e417-11e8-8a3d-7ca107825ff3.png">

**Comment by keoshi** [comment]
Yeah, I feel like this one could go either way. @johnHackworth can you please point us to any data that might help clear if this is a problem and people are either:

- Failing to login.
- Clicking the Sign Up link on the masterbar.
- Other scenario I might be forgetting?

**Comment by johnHackworth** [comment]
> . If no email matches then the see the account creation screen here.

Hmm, this shouldn't be the case. If there's no match, the user should be redirected directly to the account creation form, not this login

**Comment by johnHackworth** [comment]
just confirmed that it's working fine :)

https://cloudup.com/cbsirtyXG8W

**Comment by johnHackworth** [comment]
ok, Rick, forget about my comments, I've just realized that I was understanding your comment totally upside-down :sweat_smile:

**Comment by johnHackworth** [comment]
>Failing to login.
> Clicking the Sign Up link on the masterbar.

I have the data!
From users who are not logged in and see the pre-filled login screen:
22.07% clicks the sign-up link
10.27% triggers a login error (so they try to log in unsuccessfully). And then, 65% (so 6.68% of everyone) manage to log in in another attempt, and only 12.5% (so 1.28% of the total) of them try the sign-up link after the unsuccessful login. 
That leaves us with 2.31% of users who give up after being unable to login. 

But what is a little bit more worrying is that only around 35-48%* of users who land in the pre-populated login page manages to get to the next step. If we trust our date, it looks like they just get there and leave without further action.

* ask me in slack about the lack of accuracy here :D

**Comment by joanrho** [comment]
I'd still like to test if adding a sign up link to the stack of links below the form field helps to improve those numbers. We can leave the existing link in the upper right in the nav.

**Comment by rickybanister** [comment]
I think that's fair @joanrho, let's just make sure it has all the tracks events we need etc.

**Comment by keoshi** [comment]
I will try to add this link today, and will report if we have a PR or more work for Javi. :)
