### ISSUE TITLE
Gutenberg: duplicated content when content is bolded and backspace

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28432]
Reported by @elibud ✨ We see some curious content duplication when inside bold formatting and we press <kbd>backspace</kbd> Note that I could only repro on the native Calypso integration.

![bold-dup](https://user-images.githubusercontent.com/1270189/48275651-dfbf8580-e3fa-11e8-852d-51c1ac440990.gif)

**Comment by mmtr** [comment]
It seems this was solved by Core in WordPress/gutenberg#11287. I'm confirming if using the latest `@wordpress/editor` package solves the issue

**Comment by vindl** [comment]
Resolved in https://github.com/Automattic/wp-calypso/pull/28450.
