### ISSUE TITLE
People: Add ability to validate an invite

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#2844]
We currently have the actions, endpoint, etc. to create an invite. But, we also need the ability to validate an invite.

This will likely involve:
- [x] Creating a new `...../validate` endpoint for the WP.com API
- [ ] Adding the method that calls the new endpoint in `undocumented.js`
- [ ] Creating a store and reducer to store valid/invalid invites in `lib/invites`
- [ ] Creating the action in `lib/invites/action.js`
- [ ] Tests for the new functionality

**Comment by ebinnion** [comment]
`POST /sites/$site/invites/validate` endpoint added in r130578-wpcom.

**Comment by lezama** [comment]
some progress in ^^
