### ISSUE TITLE
Simple payments block: shortcode transform does not load previous content

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28458]
Shortcode transform does not load existing simple payments post data to the editor.

#### Steps to reproduce
1. Create a new simple payments button in any editor, look at the source code and copy the shortcode, e.g. `[simple-payment id="451"]`
2. Copy-paste the shortcode in the editor
3. An empty form shows up

#### What I expected
I expected to see content for the simple payments button to load in the form/preview

#### What happened instead
💥 
<img width="624" alt="screenshot 2018-11-12 at 14 09 10" src="https://user-images.githubusercontent.com/87168/48346782-dc3f2f00-e684-11e8-9453-53335b877989.png">

The transform is here:

https://github.com/Automattic/wp-calypso/blob/e42d76d54009feb42c15a0949befc6cd938a4459/client/gutenberg/extensions/simple-payments/editor.js#L65-L87

I didn't test if this happens when using "convert classic block to blocks" feature but I'm expecting it to behave the same.

**Comment by sirreal** [comment]
#28686 is the proposed fix for the issue as described in https://github.com/Automattic/wp-calypso/issues/28458#issuecomment-438232214
