### ISSUE TITLE
People: Language on accept invite screen doesn't match the invited user's language when logged out

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#2845]
I tested inviting a user with Spanish as their interface language:
- The invitation email was sent in Spanish (as expected)
- If I am already logged in as the invited user, the accept invite screen appears in Spanish (as expected)
- However, if I am logged out, the accept invite screen appears in English. (I confirmed that many of the strings that appeared in English are already translated and deployed in Spanish.) 

Ideally, the accept invite screen should always match the UI language of the invited user.

Steps to reproduce:

1. In a test account, go to https://wordpress.com/me/account and set the Interface Language to Spanish.
2. In your account, invite the test account to be a member of your site
3. Open the invitation email and copy the invitation link
4. In a logged-out browser window, visit the invitation link

Result: The accept invite screen (inviting you to sign up or log in to accept the invitation) is in English instead of Spanish, even though the invited user's interface language is Spanish.

You can also test this after setting your browser language to Spanish, and the logged-out accept invite screen still appears in English (with no option to switch to Spanish). We should at the very least detect the browser language and show an option to switch to Spanish, as we do in the signup flow at https://wordpress.com/start:

![screen shot 2016-01-27 at 6 53 51 pm](https://cloud.githubusercontent.com/assets/8658164/12624501/57b892b6-c527-11e5-998e-19e6bd33e5d5.png)

**Comment by ebinnion** [comment]
@lezama - You are the most familiar with how notices are set up. Will you take a look at this please?

My guess is that:
- The text just isn't translated yet
- Notice text is created before we sign the user, and thus before the language choice has been updated

**Comment by rachelmcr** [comment]
Sorry, to clarify, the text that's in English is everything on the logged-out accept invite screen (not notices) here:

![screen shot 2016-01-27 at 10 15 30 pm](https://cloud.githubusercontent.com/assets/8658164/12630280/a3039ccc-c543-11e5-87e7-f94db2a8886c.png)

I confirmed that many of these strings are already translated into Spanish, we're just serving an English version of the page to logged-out users (even if the invite was sent to a user with a non-English UI language or the preferred browser language is non-English). Some examples of strings from that screen already translated into Spanish:
- <a href="https://translate.wordpress.com/projects/wpcom/es/default?filters[status]=either&filters[original_id]=204751&filters[translation_id]=5837047">{{inviterName/}} invited you to be %(invitedRole)s on:</a>
- <a href="https://translate.wordpress.com/projects/wpcom/es/default?filters[status]=either&filters[original_id]=204696&filters[translation_id]=5836993">Sign up to start managing {{siteLink/}}.</a>
- <a href="https://translate.wordpress.com/projects/wpcom/es/default?filters[status]=either&filters[original_id]=204712&filters[translation_id]=5836913">As an administrator, you will be able to manage all aspects of %(siteName)s.</a>

**Comment by ebinnion** [comment]
Ahh! Thanks for the explanation. I'll look into that. I believe that `/start` has some functionality to pass a language code at the end of the URL. Perhaps we can do something similar and change the interface for known users.
