### ISSUE TITLE
Simple payments block: support image

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28456]
The block will not have an image added previously via other ways to modify Simple payment buttons (widgets, classic editors) and the image will be removed from the payment button when the block is saved.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/87168/48341172-0f79c200-e675-11e8-8aa0-3b379780d73c.png">

![image](https://user-images.githubusercontent.com/87168/48341301-6089b600-e675-11e8-9181-8720a2d30906.png)

As iteration steps we might want to simply:
- [ ] stop the block overriding existing featured images
- [ ] show the existing image
- [ ] allow removing the existing image
- [ ] allow adding an image
- [ ] allow editing the image

Here’s a PR to show previously added images and stop overriding existing images: https://github.com/Automattic/wp-calypso/pull/28344

Ideally the image would be inner block using core image block, but since we're outputting a short code, this might not play nicely. As a first iteration, simply updating the `featured_media` ID of the post should work well enough.

**Comment by thomasguillot** [comment]
Can we make sure we have a function to track the use of the Featured Image?
