### ISSUE TITLE
Gutenberg: Additional CSS Class not fitting the sidebar width

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#28457]
#### Steps to reproduce
1. Navigate to https://wpcalypso.wordpress.com/gutenberg/post and start creating a new post
2. Add a paragraph block and select the block settings on the sidebar
3. Expand the "Advanced" section
4. Check the width of the "Additional CSS Class" input

#### What I expected
The input should fit the 100% of the sidebar width, like in Core:
<img width="287" alt="screen shot 2018-11-12 at 12 05 13" src="https://user-images.githubusercontent.com/1233880/48343711-65e60100-e673-11e8-8824-ffe283a0e20b.png">

#### What happened instead
The input is using a default width:
<img width="286" alt="screen shot 2018-11-12 at 12 05 39" src="https://user-images.githubusercontent.com/1233880/48343896-e6a4fd00-e673-11e8-9602-f286af71d96d.png">

#### Context / Source
Caused by #28435.

The previous `input[type='text']:not( .components-text-control__input )` selector was intended for not overriding the `width: 100%;` property [defined by `@wordpress/components`](https://github.com/WordPress/gutenberg/blob/4c487f782816e2b92d53b89ce45b99bf6e5c76b4/packages/components/src/text-control/style.scss#L2).

**Comment by kwight** [comment]
Not a problem in Gutenberg+wp-admin.
