### ISSUE TITLE
Simple payments block: save product when pressing "publish"

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28460]
There are some implications if we just save the product on draft/autosave since the user might've not filled in all the fields or some fields might be invalid. Users are expecting this behaviour at a minimum when they hit publish/save on their post.

The product data gets validated & saved only on de-select.

We should:

- Validate block (currently validation + showing validation errors is tied together so we need to decouple these)
- if the block is valid on post "save/publish", save the contents. If not, show warning
- If the block is valid on draft/autosave, what should we do?

**Comment by simison** [comment]
Here's `isSaving` example from another block:

https://github.com/Automattic/wp-calypso/blob/2227c238b1a415fc6ed7407d2d200543b045be18/client/gutenberg/extensions/related-posts/edit.jsx#L174-L181

**Comment by sirreal** [comment]
Fix in #28591
