### ISSUE TITLE
Media Content Disappearing from Page after a few days 

### ISSUE THREAD

**Issue by selectedselections** [Automattic/wp-calypso#28472]
#### Steps to reproduce
1. User is working on editing this page: https://lapugliaracconta.com/professionisti-2/
2. From the page editor, the user is visit Add -> Media to add images to this page. Then they update the page. 
3. They confirmed that the images and content added appear live on the site. 
4. After a few days, the images disappear from the page. Sometimes older content disappears and the new content remains. 
5. Examples of images that have disappeared from this page are: https://lapugliaracconta.files.wordpress.com/2018/06/sifaprestoadireciao-web-rgb.jpg?w=450 and https://lapugliaracconta.files.wordpress.com/2018/06/torre-senza-tempo.jpg?w=450

#### What I expected

We expected the page updates to stick and there should be no limit to the content added to this page 

#### What happened instead

Content disappears from this page. I also noticed that, while attempting to edit the page myself, my cursor would not appear within the page Visual editor and I could only target specific areas of the page in the HTML editing view. 

#### Browser / OS version

The user states that they are using a desktop. I am asking for more information on this in the ticket

1562301-zen

**Comment by dkmyta** [comment]
The user returned to chat not long after with another issue they wanted to have added to the request.

From what I understood the user is now saying that when they are editing a specific page and add new text or new images they are unable to edit them at all. When they click on an image already embedded in on the page they can no longer see the option delete, add, etc..

Transcript: 8003551-hc
