### ISSUE TITLE
Gutenberg: Support for previewing different screensizes

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#28477]
In the current Calypso editor you can preview the post in different screen sizes: 

<img width="882" alt="screen shot 2018-11-13 at 3 18 56 pm" src="https://user-images.githubusercontent.com/128826/48392521-77083e00-e757-11e8-8019-f56835aedac2.png">

In the Gutenberg editor the preview simply opens the site frontend without the responsive preview mode.

Source: https://horizonfeedback.wordpress.com/2018/11/07/new-wordpress-editor-call-for-testing-and-feedback/#comment-454

cc @vindl @gwwar

**Comment by retnonindya** [comment]
Hi all!

A user inquired Preview feature on Gutenberg on Zendesk. I see that this already raised in GitHub; hopefully this can be resolved soon.

ZD: https://woothemes.zendesk.com/agent/tickets/1593627

Thanks a bunch.
