### ISSUE TITLE
Free Trials: domain in cart prevents user from purchasing Premium after trial

### ISSUE THREAD

**Issue by andreabadgley** [Automattic/wp-calypso#2847]
A user in live chat today was on day 11 of a 14 day trial. When the user attempted to buy Premium while in the trial, they received this error:

`You are attempting to purchase new products with renewals. Please purchase them separately.`

The steps the user took:
- Navigate to Manage Purchases
- Click Upgrade
- Enter CC
- Red box with above error message appeared.

The user had mapping in the cart in addition to Premium. The additional item in the cart maybe what prevented them from being able to purchase Premium. As per @scruffian , when a user tries to buy a free trial the existing cart should be emptied. Emptying the cart did not seem to happen with this user. 

After removing the domain mapping item from the cart, the user was able to buy Premium.

**Comment by fabianapsimoes** [comment]
@andreabadgley do you know either the Domain Mapping was a renewal, or a new purchase?

**Comment by andreabadgley** [comment]
@fabianapsimoes There was no mapping in Store Admin, so it must have been a new purchase.

**Comment by fabianapsimoes** [comment]
I'm going to close this one, since we haven't had more reports of this issue and we'll no longer use the cart for Free Trials.
