### ISSUE TITLE
Markdown block: backspace won't remove the block

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28486]
Other Gutenblocks are removed by backspacing; Markdown sticks around.

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/post/
2. Add a Paragraph block followed by Markdown block and then again two Paragraph blocks:
   - Paragraph
   - Markdown
   - Paragraph
   - Paragraph
3. Focus on last Paragraph block and hit backspace: it gets removed and you're now focused on 3rd block
4. Hit backspace again; the paragraph block does not get removed but the focus is now in Markdown
5. Hit backspace once again and you're stuck in Markdown block

You can remove all the blocks only by pressing on drag-control and hitting backspace.

#### What I expected
All blocks to be g-o-n-e 💥 

#### What happened instead
Sticky Markdown and paragraph block under it.

#### Browser / OS version
Firefox, Macos

#### Screenshot / Video
https://cloudup.com/cfSIgpIWRCv

cc @tyxla

**Comment by tyxla** [comment]
Nice catch 👍 

Noting that this behavior is consistent with the Custom HTML core block.

Anyway, I think making this working like the rest of the blocks would be an improvement, so here's #28494 to address it.
