### ISSUE TITLE
Markdown block: different placeholder color form other blocks

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28484]
When adding a Markdown block and Paragraph block next to each other in Gutenberg, you can see how placeholder texts look inconsistent by having different tone of grey.

<img width="427" alt="screenshot 2018-11-13 at 12 19 45" src="https://user-images.githubusercontent.com/87168/48407415-6e0b7280-e73f-11e8-9339-1f403d14697c.png">

cc @tyxla

**Comment by tyxla** [comment]
Seems like this started occurring since: 

https://github.com/WordPress/gutenberg/pull/10288/ which was a fix over regressions in https://github.com/WordPress/gutenberg/pull/9562/

**Comment by tyxla** [comment]
Here's a fix: #28495
