### ISSUE TITLE
Detect on which environment block is running

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28481]
We have a need to conditionally show different content in blocks for Jetpack, WordPress.com wp-admin, Calypso mobile...

I'm not sure how we should divide different targets perhaps just _"self hosted Jetpack"_ and _"everything else"_ for starters?

In Jetpack plugin we could expose `window.Jetpack_Editor_Environment` or similar and if it doesn’t exist, default to assume we're on wpcom?

Should the SDK export this global when building the blocks for Jetpack plugin?

#### Descriptions
> Simple Payments lets you create and embed credit and debit card payment buttons on your WordPress.com and Jetpack-enabled sites with minimal setup.

#### Support links
- https://jetpack.com/support/simple-payment-button/
- https://support.wordpress.com/simple-payments/

**Comment by sirreal** [comment]
I'll get a proposal ready for this using [webpack's `DefinePlugin`](https://webpack.js.org/plugins/define-plugin/) which seems like the most obvious choice.

**Comment by sirreal** [comment]
🤔 How many environments do we need to target?

I was planning on defining a webpack global to detect Calypso/SDK builds.

However, I'd expect to build a single bundle to be used in WP Admin for Jetpack, Simple sites, Atomic sites, etc. Those cases complicate things.

---

Given that we're sharing code and the blocks are the same, maybe it makes sense to share documentation as well? Should all of these point at a single place where the blocks are documented and described as Jetpack blocks (powering WordPress.com). The functionality should be the same across different Gutenbergs.

CC: @thomasguillot @MichaelArestad

**Comment by sirreal** [comment]
Closing. We shouldn't need to implement environment detection for this via p1HpG7-5P1-p2 #comment-28708
