### ISSUE TITLE
Purchase: Make it clear that a user is purchasing a renewal

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#285]
The cart item in /checkout should make it clear that it is a renewal.

Related to https://github.com/Automattic/wp-calypso/issues/162.

**Comment by drewblaisdell** [comment]
cc @mikeshelton1503 for advice on the visual treatment here (sorry about all the pings!)

**Comment by mikeshelton1503** [comment]
Let's change the button copy for renewals to:
> Renew subscription - $XX

**Comment by mikeshelton1503** [comment]
Let's add " - annual subscription" to the cart item. Like this:

![image](https://cloud.githubusercontent.com/assets/12596797/11502490/2e151484-9809-11e5-8b51-72e7e1dec74f.png)

**Comment by fabianapsimoes** [comment]
@mikeshelton1503 Should we add this to all cart items, or only renewals?

**Comment by mikeshelton1503** [comment]
Let's add it to all.
