### ISSUE TITLE
Editor: Shortlink support

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#2850]
The wp-admin editor has a "Get Shortlink" button

![screen shot 2016-01-27 at 1 36 49 pm](https://cloud.githubusercontent.com/assets/945228/12625825/1c48fb52-c4fb-11e5-8716-9e789715f6a5.png)

There has been user feedback on WordPress.com to add that functionality to the Calypso Editor.

**Comment by mtias** [comment]
We already have it, it's in the "Sharing" module in the sidebar:

![image](https://cloud.githubusercontent.com/assets/548849/12627149/7c2eab2a-c53c-11e5-973d-8f6a74a64bd6.png)
