### ISSUE TITLE
Jetpack Contact Form Block: Use material icon instead of the current one

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28519]
Gutenberg core has moved to using Material icons for the interface. Let's make sure we do the same.

Currently we're using this one:

![screen shot 2018-11-13 at 1 12 30 pm](https://user-images.githubusercontent.com/617986/48443373-cba2bd80-e745-11e8-9d66-ae0957c75a14.png)

Let's use one of these instead:

![screen shot 2018-11-13 at 1 13 37 pm](https://user-images.githubusercontent.com/617986/48443420-f3922100-e745-11e8-8732-ab858c3e119b.png)
https://material.io/tools/icons/?icon=ballot&style=outline

or 

![screen shot 2018-11-13 at 1 14 47 pm](https://user-images.githubusercontent.com/617986/48443479-1cb2b180-e746-11e8-91cd-363e56b74be5.png)
https://material.io/tools/icons/?icon=alternate_email&style=outline

**Comment by MichaelArestad** [comment]
@enejb Let's go with the first one mark suggested instead of the `@` symbol.

**Comment by enejb** [comment]
I updated https://github.com/Automattic/wp-calypso/pull/28520 to used the new icon
