### ISSUE TITLE
Editor: No way to link photos to the post URL vs. media library default.

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#2851]
There's been user feedback from WordPress.com to add the functionality to photo link attachment options from the wp-admin editor.

![screen shot 2016-01-27 at 1 47 44 pm](https://cloud.githubusercontent.com/assets/945228/12626113/99641b16-c4fc-11e5-807e-6b27e2c04b40.png)

**Comment by ryanboren** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/307

**Comment by aduth** [comment]
Duplicates #307
