### ISSUE TITLE
Gutenberg: Slug cannot be edited

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#28529]
#### Steps to reproduce
1. On a Gutenberg enabled Calypso site.
2. Blog Posts - Select a Post
3. Document Settings
4. There is not an option to update the post slug.

![48453042-9f4b6900-e766-11e8-977c-b5efbe4b2540](https://user-images.githubusercontent.com/30731356/48453252-75467680-e767-11e8-9a1c-d879b1607cd5.png)

#### What I expected
An option to update the post slug, like the one that exists in Classic Calypso:

![untitled](https://user-images.githubusercontent.com/30731356/48453286-8e4f2780-e767-11e8-9e90-176df9822724.png)

#### What happened instead
This option does not exist in Gutenberg Calypso

#### Browser / OS version
All

#### Context / Source

We'd also love to know how you found the bug: #user-report

If requesting a new feature, explain why you'd like to see it added.

User believes Gutenberg is taking options away from them that they need for their site.

**Comment by kriskarkoski** [comment]
This is now located only above the title:

<img width="817" alt="screen shot 2018-11-15 at 2 45 31 pm" src="https://user-images.githubusercontent.com/1900444/48577417-1f97d880-e8e5-11e8-9cda-46feb182f049.png">

There are some bugs I need to report, including it not showing on auto save only manual save and in that scenario showing an invalid permalink option, but it is possible to edit it as a draft and after it's published.
