### ISSUE TITLE
Gutenberg: Sharing settings (likes, buttons, publicize options) not available

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#28528]
#### Steps to reproduce
1. On a Gutenberg enabled Calypso site.
2. Blog Posts - Select a Post
3. Document Settings
4. There is not an option to select which of your sharing social media sites to share to.

![untitled](https://user-images.githubusercontent.com/30731356/48453042-9f4b6900-e766-11e8-977c-b5efbe4b2540.png)

#### What I expected
Sharing options to be there, like they are under Post Settings in classic Calypso:
![untitled](https://user-images.githubusercontent.com/30731356/48453088-cf930780-e766-11e8-8b3a-d3ba64ff09b7.png)

#### What happened instead
Sharing Settings are missing.

#### Browser / OS version
All

#### Context / Source
 #empathy #perspective #livesharing #sharing #gutenberg

We'd also love to know how you found the bug:  #user-report 

If requesting a new feature, explain why you'd like to see it added.

User believes Gutenberg is taking options away from them that they need for their site.

**Comment by KokkieH** [comment]
Had a question about this on [Twitter](https://twitter.com/DariaVampy/status/1062913917133955073).

**Comment by zdenys** [comment]
Had a user asking "where is the sharing option on the new editor?" 1110781-hc

**Comment by gemmagarner** [comment]
Enquiry about this feature on [Twitter](https://twitter.com/merlinereads/status/1063059763464990720).

**Comment by fstath** [comment]
Another one on Twitter: https://twitter.com/WeberN/status/1063297334518398976

**Comment by wprhunt** [comment]
Multiple people asking for this section in the new edtior. Latest report in #zd-1575919

**Comment by KokkieH** [comment]
Some more details around this from [this forum thread](https://en.forums.wordpress.com/topic/remove-social-media-icons-on-one-page/):

It appears having Gutenberg enabled also removes the sharing module from the classic editor in WP-Admin.

To Replicate:

1. On a site with Gutenberg enabled go to WP-Admin ->Posts ->All Posts.
2. Edit the post using the Classic Editor link in that posts list.

The Sharing module does not appear, and is not available as an option in Screen Options.

<img width="1021" alt="edit_post_ _kokkiestrialtestsite_ _wordpress" src="https://user-images.githubusercontent.com/11873759/48918217-e25aba00-ee93-11e8-9cb2-6ad088a1023c.png">

Now deactivate Gutenberg complete and then edit a post in WP-Admin. Now the sharing module appears, and its visibility can be controlled from Screen Options.

<img width="1031" alt="edit_post_ _kokkiestrialtestsite_ _wordpress" src="https://user-images.githubusercontent.com/11873759/48918250-1504b280-ee94-11e8-9951-b60b93bea12a.png">

**Comment by sjaved87** [comment]
Another user request:
https://woothemes.zendesk.com/agent/tickets/1593391

**Comment by tbradsha** [comment]
1599658-zen

**Comment by zdenys** [comment]
Another user unable to find `Likes and Shares` checkbox by having Gutenberg active (just as @KokkieH described above). 1589404-zen

**Comment by alisterscott** [comment]
Note this should include "Sharing Buttons" and "Likes" for Posts and Pages - not just Publicize which is posts only

**Comment by goblinartificer** [comment]
Also in 8728312-hc.

**Comment by formosattic** [comment]
8696027-hc

**Comment by codebykat** [comment]
Just noting I can't duplicate the missing Likes and Sharing options in wp-admin with Gutenberg active -- would be useful to have more information about those users' setups, if that's still happening.

**Comment by scosgro** [comment]
> Just noting I can't duplicate the missing Likes and Sharing options in wp-admin with Gutenberg active -- would be useful to have more information about those users' setups, if that's still happening.

It looks like WordPress.com Calypso Gutenberg now has Like/Sharing buttons added for Atomic sites only, but no Publicize options. WordPress.com Calypso Gutenberg for simple sites (non-Atomic) does not have sharing settings at all.

If I recall, Publicize was the primary issue the original user was worried about when this Github was created. 

Screenshots for reference:

WordPress.com Classic Calypso Editor: https://cloudup.com/c3fBXgwoXIA

WordPress.com Gutenberg Calypso Editor Simple (non-Atomic): https://cloudup.com/cOKDBuix-xr

WordPress.com Gutenberg Calypso Editor Atomic: https://cloudup.com/cSpPwRWZ3SM

**Comment by StefZarb** [comment]
Another user asking about the Sharing settings here (specifically about the Twitter characters counting): 1674643-ZD

**Comment by eurello** [comment]
I also had a chat today where a customer with a simple site needed to remove the sharing/like buttons from a single page. There is no way to do this with Gutenberg, either in Calypso or in WP Admin. 

The only way to do it would be to revert to the classic editor. 

9152233-hc for reference

**Comment by gwwar** [comment]
In the future please write an issue per feature, this make it easier to keep track of what has and hasn't been done.

<img width="303" alt="screen shot 2019-01-08 at 3 11 40 pm" src="https://user-images.githubusercontent.com/1270189/50864771-eb2a2100-1357-11e9-957a-62428f776738.png">

Sharing has been implemented by Gutenpack (available in the last [Jetpack release](https://jetpack.com/2018/11/27/jetpack-6-8-building-jetpack-for-the-new-wordpress-editor/
)), and we'll keep https://github.com/Automattic/wp-calypso/issues/28332 for likes and shares.

If there are other bugs that this doesn't cover. Please re-file and we'll try and triage.

**Comment by GeoJunkie** [comment]
Had a user in 11439059-hc who had several pages with Like buttons. They were unhappy with not being able to remove them from within the editor.

**Comment by codebykat** [comment]
Likes and Sharing checkboxes have been re-added in https://github.com/Automattic/jetpack/pull/12032 (and ported to WPCOM).
