### ISSUE TITLE
Jetpack Contact Form Block: Empty checkbox/radio/selectbox items gets defaulted to "selected"

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28521]
As noticed by @alisterscott, with Radio Buttons, Select Boxes and Checkboxes, when adding options and using the enter key it creates an empty option at the end of the list – which is defaulted to "selected" on the front end if this isn’t removed – can we ignore this?

**Checkboxes**

![checkboxes-empty-option](https://user-images.githubusercontent.com/617986/48446176-6a7ee800-e74d-11e8-900a-32f6bfe992e5.gif)

**Radio buttons**

![radio-empty-option](https://user-images.githubusercontent.com/617986/48446183-6eab0580-e74d-11e8-8df2-be422a3146cf.gif)

**Solution**

Any empty options should not be displayed on the frontend, or at the very least, they shouldn't default to selected.

**Comment by MichaelArestad** [comment]
This is not a blocker for v1, but would be nice to resolve.

**Comment by enejb** [comment]
This should be fixed in https://github.com/Automattic/jetpack/pull/10537

**Comment by enejb** [comment]
This should now be fixed since is now merged Automattic/jetpack#10537
