### ISSUE TITLE
Stats: `startDate` param ignored when loading `/stats/year` page on Safari

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#2852]
When loading a stats URL such as the following, the `startDate` query param is ignored on Safari. This does not happen on Chrome or Firefox.

`https://wordpress.com/stats/year/example.com?startDate=2015-01-01`

Expected behavior:
- the passed in year is selected and displayed for stats.

Observed behavior:
- the current year is selected and displayed for stats.

**Comment by alisterscott** [comment]
Retested this on Safari Version 9.1 (11601.5.17.1) and could not reproduce this (see screenshot).

Please reopen if you still find this to be an issue:

![screen shot 2016-04-29 at 9 59 04 am](https://cloud.githubusercontent.com/assets/128826/14905116/206604c0-0df1-11e6-8395-8806e817ea38.png)
