### ISSUE TITLE
Gutenberg Post settings: categories partially displayed

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#28536]
#### Steps to reproduce
1. Get import test file with 500+ categories, from [here](https://drive.google.com/open?id=1o6iBvbfz8d2Po33mRunoCVDvYK2LI29U)
2. Import file
3. Enable Gutenberg
4. Start a new post
5. Check the Categories in the post settings, scroll down the list

#### What I expected
Be able to scroll down the list of 500+ categories like it's the case with the new Classic Editor

#### What happened instead
The list stop after about 35 categories

#### What I tried

I tried to manually replicate the issue by adding 45 categories in an empty site, but the whole list appeared in the editor.

Could it be that the total number of categories is breaking the display of the whole list?

#### Alternative until this is fixed without reverting to Classic Editor
Use Quick Edit in WP-admin

Ticket 1566272-zen

**Comment by KokkieH** [comment]
Had another report of this in [Twitter](https://twitter.com/SBGtheblog/status/1062921399562571777).

Site: southernbellegrace.wordpress.com, 134 categories.

Checked in WP-Admin and there all categories are listed for me. The user has since disabled the block editor for Calypso again.

**Comment by KokkieH** [comment]
Another [here](https://en.forums.wordpress.com/topic/new-block-format-has-deleted-most-of-my-categories/)

Site, teepee12.com, 404 categories

**Comment by mmtr** [comment]
It seems that the lack of a header in the REST API was causing the issue: https://github.com/Automattic/wp-calypso/issues/28615#issuecomment-439391651.

Proposed solution in D20976-code.

**Comment by arunsathiya** [comment]
1575772-zen

**Comment by edequalsawesome** [comment]
Another report here: 1577481-zen

User has 371 categories

**Comment by KokkieH** [comment]
@mmtr 

> It seems that the lack of a header in the REST API was causing the issue:

Would this also cause issues with the list of available pages displayed when trying to set a parent page from within the page editor? Report [here](https://en.forums.wordpress.com/topic/gutenberg-11/).

**Comment by gwwar** [comment]
D21000-code has been deployed which should fix the issue for wp-admin. Please reopen if not 👍 

See related: https://github.com/Automattic/wp-calypso/issues/28615

**Comment by KokkieH** [comment]
Thank you!
