### ISSUE TITLE
Switch to Classic Editor: New post/page launches classic editor on /wp-admin instead of Calypso editor

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#28530]
#### Steps to reproduce 

- Opt in for the new WordPress Editor on a WordPress.com site
- Click `Add` next to `Blog posts`/`Site pages` to launch the new WordPress Editor 
- Click on the 3 dots menu at the top right, to switch back to classic editor, using `Switch to classic editor`
- Visit the WordPress.com dashboard and click on `Add` next to `Blog posts`/`Site pages` again

#### What is expected 

The Calypso editor loads as expected. [The video here is the expected behaviour](https://cloudup.com/ckvxygovtfc).

#### What happens instead 

Directed to classic editor on /wp-admin dashboard instead

#### Additional note

As seen on that video, my test site is not affected. On erroneous sites, the Gutenberg opt-in shows on the /wp-admin dashboard (if it does not, one has to activate `New editor` under `Screen options` of that dashboard.

#user-report

**Comment by chaitanyamsv** [comment]
Adding the [Slack link](https://a8c.slack.com/archives/CCC9JU4A1/p1542166957158100?thread_ts=1542159518.148500&cid=CCC9JU4A1) to the steps I tested.

**Comment by tarunvijwani** [comment]
Similar issue:

- Opted for New WordPress Editor through Calypso on WordPress.com site
- Redirected to /wp-admin interface with the classic editor
- Now, whenever we try to create a new page/post - it redirects to /wp-admin on the classic editor.
- No way to opt-out of New Editor as well
- and - #1566227-zd

**Comment by mmtr** [comment]
I'm not able to reproduce the issue so I'm wondering if this was just a misunderstanding of how wp-admin works after following a Calypso SU. Note that when we visit wp-admin, this is done as ourselves not SU as the user.

Can you confirm the following?
- Have all of the above issues confirmed after SU as the user?
- Do we have any user report mentioning they don't see the "More" menu or the "Switch to Classic Editor" option on it?

**Comment by arunsathiya** [comment]
>this was just a misunderstanding of how wp-admin works after following a Calypso SU. Note that when we visit wp-admin, this is done as ourselves not SU as the user.

That definitely looks to be case here, @mmtr. I haven't been able to reproduce this on my own sites. 

I shall go ahead and close this issue at the moment. Please feel free to reopen as necessary.
