### ISSUE TITLE
Gutenberg: White/blank screen in Edge

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#28544]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Start a new post on a site you've opted into Gutenberg on or opt-in to Gutenberg once the Editor opens
3. See a blank/white screen instead of Gutenberg

#### What I expected
To be able to use the Gutenberg editor

#### What happened instead
The editor does not load and shows a blank/white screen instead

This error can be seen in the console:

<img width="702" alt="screen shot 2018-11-14 at 10 56 06 am" src="https://user-images.githubusercontent.com/1900444/48496470-0c5f0d00-e800-11e8-9d92-7cd65f9f5a66.png">

#### Browser / OS version
Reproduced on Windows 10/IE 12 17.17134 (Browserstack)

#### Screenshot / Video
<img width="1319" alt="screen shot 2018-11-14 at 11 28 06 am" src="https://user-images.githubusercontent.com/1900444/48496600-6233b500-e800-11e8-9e35-6b65e7e2a429.png">

#### Context / Source

#user-report

**Comment by adamleone** [comment]
Hello!

I've also had this twice in the last hour.

HC-8053837 
HC-2563502

**Comment by sandymcfadden** [comment]
Another case reported here 6703301-hc

**Comment by carladoria** [comment]
Another one in 6239207-hc

**Comment by jjchrisdiehl** [comment]
Here 1839667-hc

**Comment by kwight** [comment]
Noting that this error doesn't seem to guarantee the white screen; after clearing browser data, Gutenberg would load while still getting the console error.

![virtualbox_msedge - win10_14_11_2018_11_43_05](https://user-images.githubusercontent.com/349751/48508163-b475d580-e802-11e8-80b1-2518a658524e.png)

**Comment by kwight** [comment]
By the way, don't test this with an automattician account; the troublesome script is bypassed in that case. 🙃

**Comment by kwight** [comment]
Fix available for review in D20838-code. Sandboxing seems to mitigate the issue somehow, so it's tough to test, but I'm hoping that eliminating the script error will allow a clean load for anyone on Edge.

**Comment by kwight** [comment]
D20838-code is deployed, and seems to do the trick; I can sign up for an account in Edge, opt in to Gutenberg, be forwarded to wp-admin, and have Gutenberg load right away.

**Comment by chaitanyamsv** [comment]
Another report in 8063683-hc
