### ISSUE TITLE
Gutenberg: Press This does not include title or link

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#28548]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/writing/example.wordpress.com (where example.wordpress.com is any Gutenberg-enabled simple site)
2. Save the Press This bookmarklet
3. Use the bookmarklet on another URL
4. Note the title and via URL/link are not passed to Gutenberg

<img width="1141" alt="screen shot 2019-02-19 at 10 59 29 am" src="https://user-images.githubusercontent.com/1270189/53040168-a0f78d80-3435-11e9-92df-91243229fbfb.png">

#### What I expected
For the title in Gutenberg to use the title of the page I use Press This on and the link to be included in the post content

#### What happened instead
Gutenberg is opened but the title and via link in post content are not included

#### Browser / OS version
OS X 10, Chrome 70.0.3538.77

#### Screenshot / Video
Gutenberg
<img width="778" alt="screen shot 2018-11-14 at 12 50 46 pm" src="https://user-images.githubusercontent.com/1900444/48501948-6b2a8380-e80c-11e8-87fd-9e0af2a43954.png">

Classic Calypso editor
<img width="861" alt="screen shot 2018-11-14 at 12 51 23 pm" src="https://user-images.githubusercontent.com/1900444/48501959-71206480-e80c-11e8-9b7c-0e66c1e8240e.png">

#### Context / Source
#manual-testing, #user-report

**Comment by mlaetitia** [comment]
New user report: hc-7685611
Also replicated on my test site with a Personal Plan. 
What I noticed: **no title or text appear**. 

Example on a free site without Gutenberg: http://cld.wthms.co/ILDhn7
Example on a Personal Plan site with Gutenberg: http://cld.wthms.co/L8YgU8

**Comment by mlaetitia** [comment]
It works on a vanilla gutenberg installation: http://cld.wthms.co/k0pcaY (only installed gutenberg and press this on a jurassic ninja site)

Have created a brand new free site on WordPress.com to test again - and still not working.

**Comment by ChrissiePollock** [comment]
Customer in #1654635-zen is having trouble with this in Safari. They reverted to Classic Editor and now Press This would not work in Classic, either. I was not able to replicate with a test site.

**Comment by gwwar** [comment]
I think this is related to #28973

Do folks have links to where folks and saving the bookmarklet?

**Comment by AtrumGeost** [comment]
Reported here: 1766788-zen

Was able to reproduce the issue on my test site using Chrome Version 72.0.3626.81 (Official Build) (64-bit) and macOS Mojave Version 10.14.2 (18C54)

**Comment by supernovia** [comment]
Got another one here:
https://en.forums.wordpress.com/topic/press-this-tool-not-working/

i have the same issue on a test site.

**Comment by supernovia** [comment]
@gwwar we're picking it up from 
https://wordpress.com/settings/writing/justvelda.wordpress.com

Noting my browser isn't allowing me to add the bookmarklet, but I can still highlight text on that page and click "press this" -- if I'm using Classic, it starts the new post with the title and highlighted text as expected.  If I'm using Gutenberg it just gives me a new blank post.

**Comment by gwwar** [comment]
Thanks @supernovia, I added a screenshot!
