### ISSUE TITLE
New editor: media doesn't insert at specified location if originally created on classic editor

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#28540]
For content that was originally created with the classic editor and is then being edited with Gutenberg, there's a bug where you can't add a media file at a specified location.

#### Steps to reproduce
1. Create a post with content with the classic editor.
2. Edit this post with the new editor.
3. Click in your content to insert a picture, let's say between 2 paragraphs.
4. Insert media file and see how it gets added to the top of the block rather than the specified location.

#### What I expected
Media to appear where I chose to display it

#### What happened instead
Media appeared at the top of block and can't be dragged down to where I wanted it to be

#### Browser / OS version
Chrome

#### Screenshot / Video

http://cld.wthms.co/1bHfo6

Reported in 1567093-zd

**Comment by edequalsawesome** [comment]
Same issue is reported in 1577427-zd

**Comment by samiff** [comment]
8656135-hc

**Comment by kwight** [comment]
Noting that this is a core bug, reported here: https://core.trac.wordpress.org/ticket/45695

**Comment by erricgunawan** [comment]
2580503-hc

Also, this probably related to: https://github.com/WordPress/gutenberg/issues/10509

**Comment by gwwar** [comment]
Since this is a core bug, I'm closing in favor of the trac or gutenberg github issue. We can still keep an eye on this one in our project.

@mcsf do folks prefer bug reports in trac or against the Gutenberg github repository?
