### ISSUE TITLE
Gutenberg: No Categories or Tags panel visible when opening existing post 

### ISSUE THREAD

**Issue by caimin-j** [Automattic/wp-calypso#28545]
#### Steps to reproduce
1. Open a post that's previously been created in Calypso with the classic editor.
2. Note the missing Categories and Tags panel.

One thing I've not been able to check is whether this happens only with posts that have never had a category assigned to them.

#### Browser / OS version
Chrome 70.0.3538.102
Mac OS 10.14.1

#### Screenshot / Video
<img width="309" alt="screenshot 2018-11-14 at 18 06 40" src="https://user-images.githubusercontent.com/37620825/48499159-17359400-e838-11e8-9833-25095ab055f7.png">

**Comment by apeatling** [comment]
@vindl Perhaps related to https://github.com/Automattic/wp-calypso/issues/28975? I don't think we can ship this without tag/category editing support.

**Comment by apeatling** [comment]
I am seeing tags and category editing in Gutenlypso on my older posts, so not sure what's happening here.

**Comment by vindl** [comment]
Not sure either, we'll need to investigate. Marking it as a blocker and bumping up priority.

**Comment by vindl** [comment]
I'm having trouble reproducing this. So far I tried the following and it works in all cases:

- starting new posts in Gutenlypso ✅
- editing existing posts that were created in Gutenlypso ✅
- editing existing posts created in Classic editor that have category and/or tags assigned ✅
- editing existing posts created in Classic editor that don't have category and/or tags assigned ✅

> One thing I've not been able to check is whether this happens only with posts that have never had a category assigned to them.

So I've ruled out this option too:

> One thing I've not been able to check is whether this happens only with posts that have never had a category assigned to them.

It might be that this problem has been resolved by plugin and npm package updates that we have landed in the meantime. I also checked if this is a Calypsoify specific issue and that doesn't seem to be the case either.

Closing this as out of date, but feel free to reopen it if you can reproduce and please update the issue summary with specific steps on how to do so.
