### ISSUE TITLE
Gutenlypso: support "duplicate" option for posts and pages and "copy a post" in Gutenberg editor

### ISSUE THREAD

**Issue by cesarabeid** [Automattic/wp-calypso#28555]
#### Steps to reproduce
1. Starting at URL: cesar.blog
2. Click `blog posts`
3. Choose one blog post you'd like duplicated, click on the button for options
4. Duplicate option is not there

#### What I expected

When looking at a list of posts in Calypso, I expected to find the `duplicate` option to create a new post:

https://d.pr/i/aPPuMd

Another site, lance.blog, which is not converted to Gutenberg yet, shows the option:

https://d.pr/i/uqJqP0

#### What happened instead

The option is not there for the Gutenberg site (cesar.blog), but it's there for the non-Gutenberg site (lance.blog)

#### Browser / OS version

Chrome, MacOS Mojave

#### Screenshot / Video
https://d.pr/i/aPPuMd
https://d.pr/i/uqJqP0

#### Context / Source

Relevant: https://github.com/Automattic/wp-calypso/pull/28286

> Disable the "Duplicate" feature for all post types because in Calypso works the opposite way than WP-Admin: Calypso copies the selected post into a new post; WP-Admin copies a selected post into the current post.

**Comment by zdenys** [comment]
1236223-hc

Another user reported that `Duplicate` feature is missing. They use it in their workflow of creating new posts from the previous ones. 

I showed them the workaround:
- Click `Copy All Content` from the three-dots menu
- Create a new post
- Switch to `Code Editor`  from the three-dots menu
- Paste the content
- Switch back to `Visual Editor` from the three-dots menu

https://cld.wthms.co/I6HFa1

**Comment by lizswafford** [comment]
3677853-hc   (Same issue, doesn't see the Duplicate option at My Sites > Posts)

**Comment by zdenys** [comment]
Another two users asking for this: 1571266-zen, 1574857-zen

**Comment by cecilearkay** [comment]
Reported on the FR forums: https://fr.forums.wordpress.com/topic/dupliquer-un-article-avec-gutenberg/

**Comment by lakellie** [comment]
Same issue in 8183182-hc

**Comment by gemmagarner** [comment]
Issue reported [on Twitter](https://twitter.com/LoveBooksGroup/status/1064871883311644673).

**Comment by damiannep** [comment]
User asking for this in #7662166-hc

**Comment by ktyfuller604** [comment]
User reported - #8604696-hc

**Comment by ktyfuller604** [comment]
User is asking for this in #2212099-hc

**Comment by retnonindya** [comment]
User is reporting similar issue in #7190908-hc.

**Comment by AtrumGeost** [comment]
Reported here 8713945-hc

**Comment by tbradsha** [comment]
5496375-hc

**Comment by tbradsha** [comment]
3059532-hc

**Comment by JessBoctor** [comment]
8726245-hc

**Comment by simranjeetkaur10** [comment]
8735981-hc

**Comment by zdenys** [comment]
Another two users asking for this: 1640409-zen and 1630881-zen. So I shared the workaround from above [#](https://github.com/Automattic/wp-calypso/issues/28555#issuecomment-439133464)

**Comment by fditrapani** [comment]
User reported here: 1652055-zen

**Comment by KokkieH** [comment]
Another request [here](https://en.forums.wordpress.com/topic/copy-a-post-20/)

**Comment by gwwar** [comment]
I'll add a second issue for the wp-admin case.

**Comment by gwwar** [comment]
Added https://github.com/Automattic/wp-calypso/issues/29876 for the Calypsoify flow used by Atomic sites.
