### ISSUE TITLE
Gutenberg: Simple Payments buttons cannot be added or edited

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#28552]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Add a new post to a Gutenber-enabled site or try to edit a post in Gutenberg that includes a Simple Payments button
2. The option to add Simple Payments will not be shown or existing buttons cannot be edited without switching back to the Classic editor

#### What I expected
To be able to add or edit a Simple Payment button

#### What happened instead
The option to add a Simple Payments button is missing and if already added you see a shortcode with no indication on how to edit it

#### Browser / OS version
OS X 10, Chrome 70.0.3538.77

#### Screenshot / Video
Gutenberg

<img width="704" alt="screen shot 2018-11-14 at 1 23 54 pm" src="https://user-images.githubusercontent.com/1900444/48503604-944d1300-e810-11e8-9e9a-87826dfbf5fc.png">

Classic

<img width="869" alt="screen shot 2018-11-14 at 1 23 34 pm" src="https://user-images.githubusercontent.com/1900444/48503611-9a42f400-e810-11e8-9c2e-72bcb98eedd9.png">

<img width="832" alt="screen shot 2018-11-14 at 1 23 42 pm" src="https://user-images.githubusercontent.com/1900444/48503616-9dd67b00-e810-11e8-9f9b-c85c092ceaec.png">

#### Context / Source
#manual-testing, #user-report

**Comment by kwight** [comment]
This work is currently in progress (hopefully coming soon-ish) in [Jetpack](https://github.com/Automattic/jetpack/search?q=simple+payments+block&unscoped_q=simple+payments+block&type=Commits).

**Comment by jeherve** [comment]
The block is now available for both WordPress.com and Jetpack users.
