### ISSUE TITLE
Jetpack Contact Form Block: Changing/transforming an inner block isn't obvious

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28557]
When transforming an inner block, there is no feedback given to the user so they understand that the block has been changed.

This has been discovered by some while testing the block ( @fditrapani and @rickybanister ).

Here's the issue. I change the Email inner block into a Date block.

![date](https://user-images.githubusercontent.com/617986/48514107-5e109300-e812-11e8-9a96-18d749328514.gif)

**Possible Solutions**

1. Force the label to change to reflect the new block name. I'm thinking this should probably happen whether the label has been edited or not.
2. Once the block changes over, the "transform" icon should go away and show the new block's icon instead.

**Comment by MichaelArestad** [comment]
> Force the label to change to reflect the new block name. I'm thinking this should probably happen whether the label has been edited or not.

I lean toward not changing the label of content changed. Perhaps we just replace it if it's a default. We could also _not_ prefill any label at all and instead use the input placeholder to show the default. This way if they don't fill it out and transform it, the placeholder text will change. The trick there will making it show properly in preview (unselected block) mode.

**Comment by fditrapani** [comment]
> I lean toward not changing the label of content changed. Perhaps we just replace it if it's a default.

I tend to agree with this. This sounds like a good compromise to me.

**Comment by MichaelArestad** [comment]
Definitely v2 enhancement.
