### ISSUE TITLE
Jetpack Contact Form Block: Display the fields as obviously disabled while in Gutenberg

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28558]
People tend to try to click into the fields while in Gutenberg, but the fields are disabled and don't allow this to happen. Let's make them look disabled while the block is focused so it's a bit more obvious that people can't click into them.

hat tip to @fditrapani

Here's an example of the problem:

![disabled](https://user-images.githubusercontent.com/617986/48514662-b3996f80-e813-11e8-93bf-b33a494ddce4.gif)

**Possible Solution:**
It's gray when focused.

![gray-when-focused](https://user-images.githubusercontent.com/617986/48514816-17bc3380-e814-11e8-9282-4f4fcb2215cd.png)

**Comment by MichaelArestad** [comment]
@mapk I tried the grey field when focused and it was really disruptive. I can definitely implement this again in v2 no sweat.

**Comment by enejb** [comment]
What if we allows the user to edit the placeholder and the default value by clicking on the field and getting them to type something.. We would also combine it with this PR. 

https://github.com/Automattic/wp-calypso/pull/28612

See something like this?
![screen shot 2018-11-15 at 10 25 46 pm](https://user-images.githubusercontent.com/115071/48601693-89d06d80-e925-11e8-91dd-8824532aaf17.png)

I actually implemented it for just for the text toggles. (email, name, url, telephone)

**Comment by mapk** [comment]
> What if we allows the user to edit the placeholder and the default value by clicking on the field and getting them to type something.

Good exploration! I like the idea of a toggle for these two settings. However I don't think it should be in this format. We use that pattern right now for "Edit" and "Preview" modes of some blocks, so I'd rather keep it for that usage.

**Here's another idea**
![placeholder-default](https://user-images.githubusercontent.com/617986/48640530-ce8eef80-e98b-11e8-85d7-63dd5523667b.png)


Because this is getting complex and technical, maybe we limit the `placeholder` to be editable from within the input field in the block only. Then we show the `default value` and `ID` in the inspector.

What do you think?

**Comment by enejb** [comment]
I am closing this issue. since #28612 was merged and addressed this issue in a different way.
