### ISSUE TITLE
Gutenberg: Proofreading (After the Deadline) feature not included [2]

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#28550]
Edit from @gwwar 3/27:

Many folks have reported that we're missing the proofreading integration in the new block editor.

Since After the Deadline is no longer actively maintained, let's remove this integration for now across all editors and update related documentation.

We are open to investigating adding similar functionality using a different service, but let's open a different issue for that.

Classic Calypso

![proofread-writing](https://user-images.githubusercontent.com/1900444/48503142-5a2f4180-e80f-11e8-8783-af7d1503cc57.jpg)

#### Context / Source
#manual-testing, #user-report

**Comment by jjchrisdiehl** [comment]
Another request #2455378-hc

**Comment by juliasydnor** [comment]
Also reported in 1582823-zen

**Comment by formosattic** [comment]
Another request: 1586015-zen

**Comment by sarahcada** [comment]
Another request: 8702186-zen

**Comment by benchilcote** [comment]
Another request: 8820680-zen

**Comment by erricgunawan** [comment]
Another request: 1667793-zen

**Comment by jerdwyer** [comment]
Another request.  New releases should add features, not take them away.  Thanks.

**Comment by arunsathiya** [comment]
1694327-zen

**Comment by torres126** [comment]
Request here: https://en.forums.wordpress.com/topic/spell-check-15/

**Comment by torres126** [comment]
Another request has been added to the forum thread linked above.

**Comment by ashercantrell** [comment]
Requested in 8135274-hc as well

**Comment by Robertght** [comment]
Another request 1715300-zen.

Recommended the Classic block for now.

**Comment by pauljacobson** [comment]
This was also queried in 1715078-zen

I also suggested either a Classic block or Grammarly.

**Comment by simison** [comment]
1723809-zen

**Comment by jamiepalatnik** [comment]
Another request: 9127762-hc

**Comment by gaurav1984** [comment]
1747162-zen

**Comment by scosgro** [comment]
Another request: 10052164-hc

**Comment by m** [comment]
Given AtD isn't maintained we should retire across the board.

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/jetpack/issues/9128

**Comment by ChrissiePollock** [comment]
Another request #11407304-hc

**Comment by kwight** [comment]
Closing this as wontfix for the Gutenberg integration then; users can continue for now to access it from Calypso or `wp-admin`.

**Comment by gwwar** [comment]
@kwight I think we'll still want this one to either remove this across all editors or find an alternative.

**Comment by jerdwyer** [comment]
I apologize if this isn't the right place for this comment.  I can say as a user that I looked at Calypso and wp-admin and neither worked for me.  I forget now whether it was because I have a free account or if it seemed like too much work (even though I'm very good with computers, learning to use WP as a power user isn't on my to-do list).  




Bottom line is I understand  the decision, but directing the average user to Calypso or wp-admin is not a solution.




On Tue, Mar 26, 2019 at 9:13 PM +0100, "Kirk Wight" <notifications@github.com> wrote:












Closing this as wontfix for the Gutenberg integration then; users can continue for now to access it from Calypso or wp-admin.

**Comment by ashercantrell** [comment]
This is absolutely the right place for that, and thank you for sharing your feedback :-) We really appreciate it!

**Comment by gwwar** [comment]
Noting feedback from Matt and @apeatling, I'll be updating this issue to reflect removing After the Deadline in all editors.

We'd be open to investigating adding similar functionality using a different service, but let's open a different issue for that.

**Comment by sophiegyo** [comment]
Just noting that there's definitely interest in having a proofread function: #10435959-hc

**Comment by edequalsawesome** [comment]
Customer also requested the proofread function back in #12347176-hc

**Comment by darnelldibbles** [comment]
Another instance here on Twitter: https://twitter.com/LetsGoToTheMov7/status/1121804294683021317

**Comment by gwwar** [comment]
@edequalsawesome  @darnelldibbles let's open a new one to track a proofreading editor enhancement in general. This issue will close out when we remove remaining AtD editor references.

**Comment by lizkarkoski** [comment]
Another report in the WordPress.com forums: 

https://en.forums.wordpress.com/topic/proof-reader-spell-and-grammar-check-has-disappeared/

**Comment by jonnyruzek** [comment]
Another user was asking for this in 12480561-hc

**Comment by sstabrizi** [comment]
Another user wanting this feature in 1974026-zd

**Comment by noteeth** [comment]
I also encountered a user wanting this feature -hc 12434540

**Comment by jesscga** [comment]
another request for this to be reinstated on #11272135-hc

**Comment by rodrigoi** [comment]
Please, add your reports to #32798 from now on, since this Issue is linked to a WordPress.com deploy and will soon be closed.

**Comment by jonnyruzek** [comment]
Another request in 2752414-hc

**Comment by vindl** [comment]
Replaced by https://github.com/Automattic/wp-calypso/issues/32798.

**Comment by thuautp** [comment]
A user requested this feature here #12803781-hc

**Comment by guicmazeredo** [comment]
Another user requesting this feature back #12648865-hc

Highlights on what the user said:

"I want to leave a message that I hope the developers put the spell check function back in. Not having a spell check is aggravating and dumb. And please, don't tell me to use an external site like Grammarly instead. :) I can assure you a lot of bloggers are cheesed off about the spell check removal. Grammarly constantly is interjecting where it shouldn't and is aggravating. This is a big deal and it irritates the snot out me and many of my followers have wondered what the heck was up with it too."

**Comment by fresatomica** [comment]
Another one #2039773-zen

**Comment by kriskarkoski** [comment]
@guicmazeredo @thuautp These reports should go on #32798 going forward
