### ISSUE TITLE
Gutenberg: add tracks event when we opt-out in wp-admin

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28563]
As @mmtr noted, we'll want to track the full funnel of folks opting in from Calypso, and when they opt-out. We'll want to add a relevant _tracks_ event here:

<img width="299" alt="48475071-45957e00-e7fc-11e8-99c0-69e6d9592198" src="https://user-images.githubusercontent.com/1270189/48515872-d416f900-e816-11e8-9412-0c488dc8acc4.png">

Edit: it looks like we are also missing tracks events on the wp-admin opt-in. @kwight suggests we may want to record this in `submit_editor_stats` in the API, where we detect preference transitions (gutenberg to classic or classic to gutenberg).

**Comment by kwight** [comment]
Handling in D20854-code.

**Comment by kwight** [comment]
Fixed in D20854-code.
