### ISSUE TITLE
Jetpack Contact Form Block: In block inspector, the "Advanced - Additional CSS Class" doesn't work

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28565]
Both Joen Olsen and I tried to add an additional CSS class and nothing showed up in the frontend. Can we get this to work? Or should we drop this from the block inspector for this block for now?

![screen shot 2018-11-14 at 2 40 33 pm](https://user-images.githubusercontent.com/617986/48517471-41c52400-e81b-11e8-8d17-a700c81d5214.png)

**Comment by MichaelArestad** [comment]
I think whatever is fastest should be implemented. If it's easy to add the classes, great. Otherwise, lets hide the Advanced option.

**Comment by enejb** [comment]
This should be fixed in https://github.com/Automattic/jetpack/pull/10537

**Comment by enejb** [comment]
This should be fixes now. Since Automattic/jetpack#10537 is now merged.
