### ISSUE TITLE
Gutenberg: Enhancement - Scheduled posts don't appear in datepicker

### ISSUE THREAD

**Issue by ashercantrell** [Automattic/wp-calypso#28567]
In Calypso, the datepicker calendar shows faint gray circles around dates that have a post already scheduled, and mousing over that shows the number of posts scheduled for that day and their names.

You can see a screenshot of that behavior here: http://cld.wthms.co/A26y6A

Calypsofied Gutenberg currently doesn't do this, and only shows the calendar itself. I think it would be good to have this info showed there as well.

This was requested by a user in #1567530-zen

**Comment by kwight** [comment]
Marking enhancements of this sort as low priority for now.

**Comment by KokkieH** [comment]
Noting we've had another request for this in the [forums](https://en.forums.wordpress.com/topic/new-editor-unable-to-see-other-scheduled-posts/).

**Comment by supernovia** [comment]
Another complaint here. This one hits our diehard bloggers.
https://twitter.com/sarahhardy681/status/1065012897099722761

**Comment by ahmadbaig1** [comment]
Another enquiry for it through tickets-
[Zen_1593708](https://woothemes.zendesk.com/agent/tickets/1593708)

I have informed them that the issue is in our list of enhancements and will be added in the future.

**Comment by sixhours** [comment]
Another request from a user in 1567530-zen

They'd like a follow-up when this is implemented, please and thanks!

**Comment by ahmadbaig1** [comment]
The user- 1633273-zen would also like an update when this is added.

**Comment by kwight** [comment]
Bumping priority due to vocal feedback.

**Comment by KokkieH** [comment]
Another request [here](https://en.forums.wordpress.com/topic/block-editor-3/)

**Comment by donalirl** [comment]
Another request in #1756730-zen

**Comment by hannahswain** [comment]
Another request in 1748062-zen

**Comment by lakellie** [comment]
Another request in #3054688-hc

**Comment by supernovia** [comment]
Another via Twitter: 
/PhotosEmily/status/1093226553566220295

**Comment by mikeicode** [comment]
Another request #8663118-HC

Testing this I see that aside from the scheduled posts not showing on the calendar the current day (today), is not shown on the calendar like it was previously.

This: https://cld.wthms.co/bmfIeN
Compared to this: https://cld.wthms.co/MqXVmU

**Comment by ezraalamsyah** [comment]
Another request in 1784263-ZD

**Comment by torres126** [comment]
Request here: https://en.forums.wordpress.com/topic/blog-post-calender/

**Comment by AtrumGeost** [comment]
Another request here 1800713-zen

**Comment by BigDaddyLinux** [comment]
Would love to see this enhancement in Gutenberg

**Comment by torres126** [comment]
Request here: https://en.forums.wordpress.com/topic/post-scheduling-7/

**Comment by jesscga** [comment]
Another request on 4613987-hc - user asked to switch to classic editor for unrelated reasons which should resolve the calendar issue.

**Comment by spencerberry** [comment]
Requested in 13133129-hc as they accepted the block editor but rely on this feature to have a well-distributed schedule of content.

**Comment by tijosh** [comment]
Another request for this in #13111861-hc  

Followup: #2105059-zen

**Comment by supernovia** [comment]
Noting there's an issue on core about this too with some design discussion:
https://github.com/WordPress/gutenberg/issues/13713

**Comment by samiff** [comment]
1525757-hc

**Comment by Kheas** [comment]
Blogger here at Latetothegame.blog.  This function is essential to scheduling blogs.  Please find a way to implement it prior to launch.

**Comment by Kheas** [comment]
If it can not be implemented can we at least still have access to the classic editor until it is?

**Comment by deancroyal** [comment]
Another in [forums](https://wordpress.com/forums/topic/showing-scheduled-posts/).

**Comment by khristiansnyder** [comment]
Requested in 12114494-hc

> In the new editor (which is garbage) the calandar does not bring up the other post you have up or upcoming. This was a pretty fundamental feature. How can I get it back?

**Comment by davemart-in** [comment]
Heh. Here's one more duplicate issue: https://github.com/WordPress/gutenberg/issues/13713 :-P

**Comment by Fangthewonderdog** [comment]
I need this feature too.  It is needed for efficient and correct scheduling. What priority has been given to the fix please?

**Comment by macmanx2** [comment]
Also requested at https://wordpress.com/forums/topic/publishing-future-date/

**Comment by fernmed** [comment]
Another request 457171-hc

**Comment by samiff** [comment]
Requested in 3289831-zd-woothemes

**Comment by abdul5ashraf** [comment]
Another request 3297295-hc

**Comment by mriyazuddin** [comment]
Another one #3299468-zd

**Comment by fsalazarleon** [comment]
Another one #3275085-hc

**Comment by aleone89** [comment]
More request here: hc-14523525 and zen-3326301

**Comment by carladoria** [comment]
another request in 3333184-zen

**Comment by kriskarkoski** [comment]
Requested in 3330991-zd as well

**Comment by aisajib** [comment]
Another chat requesting this: #24324028-hc

**Comment by donalirl** [comment]
Another request in #16099825-hc

**Comment by rossanafmenezes** [comment]
Another request here 3389519-zen

**Comment by tbradsha** [comment]
2741645-hc

**Comment by supernovia** [comment]
Another request here:
https://wordpress.com/forums/topic/calendar-markers/ 

Glad to see this is in the works. :)

**Comment by fsalazarleon** [comment]
Another request here 3466246-zen

**Comment by SBATHOMPSON** [comment]
I had a user request this feature today. 
https://woothemes.zendesk.com/agent/tickets/3471369

**Comment by mikeicode** [comment]
Requested 3511304-zd-woothemes

**Comment by aleone89** [comment]
Another request via twitter: 

/downthebookhole/status/1346629013930913792

**Comment by rachelwinspear** [comment]
Another request: #3755376-zen

**Comment by sixhours** [comment]
Another request for this in en.blog comments: https://wordpress.com/blog/2021/03/15/block-editor-updates-2/#comment-418971

**Comment by retrofox** [comment]
Today we've merged the first approach to address this issue. https://github.com/WordPress/gutenberg/pull/29716
Let me close the issue.
