### ISSUE TITLE
Import: Blank list of importers after completing import

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#28568]
#### Steps to reproduce
1. Visit https://wordpress.com/settings/import/{site}
1. Start a Wix import and wait until it is finished
1. Click "Done"

#### What I expected

1. To be taken back to the import screen with a list of importers

#### What happened instead

1. I'm on the import screen, but no importers are shown

#### Screenshot / Video

![screenshot-2018-11-05-20-04-30](https://user-images.githubusercontent.com/1699996/48518719-1a2c8680-e830-11e8-816a-7157bfdce24c.png)
![screenshot-2018-11-05-20-04-41](https://user-images.githubusercontent.com/1699996/48518720-1ac51d00-e830-11e8-82eb-208eae502681.png)

#### Context / Source

Reported by multiple users in https://wp.me/p8F0Ux-1gL-p2

**Comment by creativecoder** [comment]
Possible cause

> Looks like a the UI has got in to a state that’s stopping the ‘current’ importer component from rendering but because that hasn’t been cleared it’s not rendering the list.

**Comment by mattsherman** [comment]
No longer an issue. Closing.
