### ISSUE TITLE
Trampoline: Singular/Plural My Sites

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#2857]
My Site(s) is pluralized in Trampoline but singular for new users who have a "My Site" menu.

![screen shot 2016-01-27 at 2 55 18 pm](https://cloud.githubusercontent.com/assets/66797/12688828/055c4e66-c696-11e5-9f37-c4210e841451.png)

**Comment by lancewillett** [comment]
(Moved screenshot inline.)

**Comment by kwight** [comment]
Fixed server-side on dotcom.

![screen shot 2016-02-03 at 9 10 13 am](https://cloud.githubusercontent.com/assets/349751/12790208/0a118192-ca56-11e5-8071-5e9833437ab9.png)
