### ISSUE TITLE
Gutenberg: on mobile screen sizes can't set post or page visibility

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#28578]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/post for a site opted into Gutenberg on a mobile sized screen width (either on a mobile or resized)
2. When editor loads from wp-admin - try to load sidebar and set visibility

#### What I expected

To be able to set visibility

#### What happened instead

Nothing

#### Browser / OS version

Chrome resized desktop mac
iOS Safari on iPhone

#### Notes

This works fine: https://wpcalypso.wordpress.com/gutenberg/post/j
Also, fails on Jetpack

#### Screenshot / Video

![editor sidebar visility](https://user-images.githubusercontent.com/128826/48536822-714b5d80-e8fb-11e8-8f5b-87f3281712b9.gif)

#### Context / Source

Found converting our e2e tests to use Gutenberg: https://github.com/Automattic/wp-e2e-tests/pull/1624

**Comment by alisterscott** [comment]
@gwwar this is potentially a big issue for some customers since there doesn't appear to be a workaround on mobile - it also happens on Jetpack though - would you like me to raise it in Jetpack?

**Comment by gwwar** [comment]
>  it also happens on Jetpack though - would you like me to raise it in Jetpack?

I tested this on Gutenberg master. Good catch @alisterscott, this looks like a core bug. Let's close this one out and file in https://github.com/WordPress/gutenberg/issues

Let me know if y'all need help getting a local vanilla setup running. https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#local-environment should be up to date

**Comment by alisterscott** [comment]
@gwwar thanks, raised on https://github.com/WordPress/gutenberg/issues/11951
