### ISSUE TITLE
Onboarding Checklist: "Your Site is Private" (but it's not)

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#28570]
#### Steps to reproduce
1. With a public site, head to https://wordpress.com/checklist/
2. Note the last item says "Launch your site
Your site is private and only visible to you. Launch your site, when you are ready to make it public.
3. Click the link
4. It says it launches the site (even though it didn't do anything)

#### What I expected
That item should be checked off (or not listed at all) if the site is already public

#### What happened instead
It confused a user who thought their site was public already (it was)

#### Browser / OS version
Doesn't matter

#### Screenshot / Video
https://cloudup.com/cNkfVb-7oWm

#### Context / Source
https://en.forums.wordpress.com/topic/site-checklist/#post-3212407

Confirmed on a test site, too

**Comment by supernovia** [comment]
I'm guessing this is solved now due to private by default. Might be worth another check.

**Comment by synora** [comment]
A user just reported the same experience in 21015072-hc. 

For my user, Launch Site doesn't appear in the customizer, but only in My Home and Manage > Settings > General > Launch Site. 

The site has been public for 8 months and has been indexed by Google. 
Follow-up in 2965359-zen.

**Comment by jordesign** [comment]
Closing this as no longer relevant
