### ISSUE TITLE
Gutenberg text editor -CHROME-: When you remove the last character, it also removes a space.

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#28581]
#### Steps to reproduce
1. Starting in the Calypso Gutenberg editor.
2. Write any text, for instance, "This is a sample text for" 
3. Remove the last word, as if you were going to replace "for" by "to", clicking on backspace 

#### What I expected
I expected to need to click 3 times on backspace and then write "to"

#### What happened instead
When you click the 3rd time on backspace the editor removes the 'f' but also removes the space between "text" and "for", so you need to retype it. It is an incoherent and unexpected behavior when you are typing.

#### Browser / OS version
I tested this on OS X 10.13.6, Chrome 70
Works properly in Firefox 63

#### Screenshot / Video

http://cld.wthms.co/g5RSAl

**Comment by arunsathiya** [comment]
From what I see, it's the same issue as the one here. https://github.com/Automattic/wp-calypso/issues/28473

I'm closing this at the moment, but if I'm misreading something, please feel free to reopen @rantoncuadrado.
