### ISSUE TITLE
Gutenberg: Opt-in modal on mobile view does not show the full illustration

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#28598]
#### Steps to reproduce 

- Start on a mobile device, or resize your desktop viewport to mobile views
- Get a WordPress.com site
- Visit https://wordpress.com/post and use the WordPress Editor opt-in on the right sidebar

#### What is expected 

The illustration on the opt-in modal is shown in full

#### What happens instead 

Parts of the illustration can be seen to be cropped out

<img width="454" alt="screenshot 2018-11-15 at 23 32 58" src="https://user-images.githubusercontent.com/18581859/48572343-395e0d80-e92f-11e8-9676-d20b68173615.png">

Related PR that introduced this modal - https://github.com/Automattic/wp-calypso/pull/27915

**Comment by arunsathiya** [comment]
@kwight I closed this issued by mistake, breaking your actions. I've reopened it again, I'm sorry about the hassles.

**Comment by kwight** [comment]
I wouldn't consider this a bug; it's the same style of cut-off image as the full desktop view, and keeping the view limited in height will aid keeping the user actions above the fold on smaller mobile screens. Let's close as invalid/wontfix.

<img width="966" alt="Screen Shot 2019-11-08 at 10 55 03 AM" src="https://user-images.githubusercontent.com/349751/68502913-742f1480-0216-11ea-9aa1-227d38aa315f.png">
