### ISSUE TITLE
Jetpack Contact Form Block: Update the wording for the form creation block placeholder

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28597]
There's been some confusion around the placeholder screen after inserting the Contact Form block. Some people have thought _this_ was the actual form and fields being created. There's confusion around the wording, input fields, and button.

![placeholder](https://user-images.githubusercontent.com/617986/48570683-c0709e80-e8b9-11e8-94e5-91bc22791665.png)

Thanks to both @danjjohnson for bringing this to our attention.

@michelleweber suggested some edits.

```
Contact Form
Add a customizable contact form to your post or page. You can edit the form itself once you add the block.

You’ll receive an email notification each time someone fills out the form. Where should it go, and what should the subject line be?
________field 1____________
________field 2____________

(If you leave these blank, notifications will go to the author with the post or page title as the subject line.)

ADD FORM
```

**Comment by mapk** [comment]
How's this work? I left off the first intro line b/c the user has already added this block to their page.

![block-and-inspector](https://user-images.githubusercontent.com/617986/48589298-c97c6280-e8ef-11e8-8640-c515a8a7c621.png)

**Comment by mapk** [comment]
I'm not entirely sure if this help though. I imagine most people will scan right through this thinking that it's the actual contact form. I'll post this on the P2 as well.

**Comment by michelleweber** [comment]
P2'd a comment:

> I think as long as there are fields here, the “first glance” problem is going to persist. For anyone who reads, I think it helps clarify what they’re entering and why. So it seems like a net gain? Some people who wouldn’t have read it either way will still misunderstand, some people who read it will understand what’s going on.
> 
> (FWIW, for our readers, I think it’s still useful to have a line explicitly telling them that they’ll be able to edit the form fields once they add the block.)
