### ISSUE TITLE
Jetpack Contact Form Block: Add form validation for recipient email errors

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28609]
The placeholder form asking for the recipient's email doesn't seem to do any form validation. If a user enters something wrong, it can get overlooked fairly easy.

This was brought up by @eliorivero, thanks!

![screen shot 2018-11-15 at 12 36 11 pm](https://user-images.githubusercontent.com/617986/48580258-8f04cc80-e8d3-11e8-8c1e-6c64429153e2.png)

and

![screen shot 2018-11-15 at 12 36 38 pm](https://user-images.githubusercontent.com/617986/48580268-9330ea00-e8d3-11e8-8919-09ad4f548fdb.png)

**Comment by enejb** [comment]
This is being worked on in https://github.com/Automattic/wp-calypso/pull/28513
