### ISSUE TITLE
Jetpack Contact Form Block: Update the email placeholder on the setup screen

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28613]
On the set up screen we're currently using an arbitrary email as the example in the placeholder. Rather than this, let's make it a bit more generic. 

Thanks, @eliorivero for bringing this up.

**Currently:**
`Example: muriel@design.blog`

**Change to:**
`name@example.com`

**Comment by enejb** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/28616
