### ISSUE TITLE
Gutenberg: fix core fetch all middleware handling

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28615]
The API Fetch package has special behavior when per_page is set to `-1`. This means we should fetch all pages of a given resource.

This appears to have broken again, leaving us with only the first 100 results. Causing issues like us not rendering the full author list in the sidebar.

https://github.com/WordPress/gutenberg/blob/cdeb4098607e8d5f1dc439e6527191359f1a1852/packages/api-fetch/src/middlewares/fetch-all-middleware.js

cc @georgeh if you had tips from the last fix

### Testing Instructions
- Navigate to a site with more than 100 users (for a8c folks a p2 site will do the trick)
- Edit a post or page
- In the sidebar click on the Author dropdown

Expected: all users are visible
Actual: only the first 100 are returned

**Comment by gwwar** [comment]
I think D20383-code was when we fixed this last?

**Comment by mmtr** [comment]
It looks like this is the same issue as https://github.com/Automattic/wp-calypso/issues/28536

**Comment by mmtr** [comment]
I found that the REST API was not exposing the `link` header. 

Proposed solution in D20976-code.

**Comment by rodrigoi** [comment]
Not only we are not exposing the `link` header on the REST proxy, but also, Gutenberg expects it to be lowercase (because of the Fetch API).

Alternative solutions:

WordPress.com/Calypsoify: D21000-code
Calypso Integration: #28644

**Comment by kwight** [comment]
D21000-code has been deployed.

**Comment by gwwar** [comment]
Awesome, I'm closing this out and I'll add new issues for the other core middleware for the native Calypso integration.

**Comment by gwwar** [comment]
Added https://github.com/Automattic/wp-calypso/issues/28777 as a follow up 👍
