### ISSUE TITLE
Gutenberg: New content is added inside blocks in the Classic editor

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#28621]
#### Steps to reproduce
1. Opt in to Gutenberg and create a post containing a Heading and a Paragraph block:
```html
<!-- wp:heading -->
<h2>My heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>My paragraph</p>
<!-- /wp:paragraph -->
```
2. Switch to the Classic editor
3. In the Visual mode, Add a new paragraph after the heading:
<img width="766" alt="screen shot 2018-11-16 at 09 31 05" src="https://user-images.githubusercontent.com/1233880/48608103-6982cc00-e982-11e8-8933-50ec0bcac90d.png">

4. Switch to the Gutenberg editor

#### What I expected
I expected to see a post containing 3 blocks (1 heading and 2 paragraphs):
```html
<!-- wp:heading -->
<h2>My heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>New paragraph</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>My paragraph</p>
<!-- /wp:paragraph -->
```

#### What happened instead
Gutenberg displays an error because the new paragraph has been included inside the heading block, causing an invalid content:
<img width="655" alt="screen shot 2018-11-16 at 09 08 18" src="https://user-images.githubusercontent.com/1233880/48608837-4efd2280-e983-11e8-92ad-73777dfd9234.png">

```html
<!-- wp:heading -->
<h2>My heading</h2><p>New paragraph</p>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>My paragraph</p>
<!-- /wp:paragraph -->
```

#### Context / Source
This is happening because when we add the content in Calypso, the cursor is between `<h2>My heading</h2>` and and the _invisible_ `<!-- /wp:heading -->` markup.

**Comment by mmtr** [comment]
This is still reproducible with Gutenframe

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
