### ISSUE TITLE
SDK: ensure SDK builds for correct Babel-env targets

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28623]
When building with the SDK, Babel is targeting `{ node: 'current' }` instead of: 
```
[ 'last 2 versions', 'Safari >= 10', 'iOS >= 10', 'ie >= 11' ]
```

In our Babel config, we set `isCalypsoClient` constant based on env variable, but for the SDK this gets set to `false`, hence we pick wrong `targets` config for `@babel/env`.

https://github.com/Automattic/wp-calypso/blob/58564744a96da9a8599fc7eed2e8da3e7d4fd09c/babel.config.js#L5-L13

This results in [broken browser support](https://github.com/Automattic/wp-calypso/pull/28617).

We need correct browser targets for sure but other areas where `CALYPSO_CLIENT` changes the build we might need to consider case-by-case. For example:
https://github.com/Automattic/wp-calypso/blob/58564744a96da9a8599fc7eed2e8da3e7d4fd09c/babel.config.js#L51
https://github.com/Automattic/wp-calypso/blob/58564744a96da9a8599fc7eed2e8da3e7d4fd09c/inline-imports.js#L4-L12

## Steps to reproduce

Create a file `in.js`:
```bash
echo "const foo = { a: 1, b: 2 };console.log({ ...foo, b: 3 });" > in.js
```

Build the file it with the SDK the regular way:
```bash
NODE_ENV=production npm run sdk -- generic in.js out-bad.js
```
Build another file by manually setting `CALYPSO_CLIENT`:
```bash
NODE_ENV=production CALYPSO_CLIENT=true npm run sdk -- generic in.js out-good.js
```

Compare results:
```bash
npx js-beautify -f out-good.js -o out-good.js
npx js-beautify -f out-bad.js -o out-bad.js
diff -y out-bad.js out-good.js
```

Bad in red:
```diff
45c45
<     }, r.p = "", r(r.s = 0)
---
>     }, r.p = "", r(r.s = 1)
46a47,60
>     var n = r(2);
>     e.exports = function(e) {
>         for (var t = 1; t < arguments.length; t++) {
>             var r = null != arguments[t] ? arguments[t] : {},
>                 o = Object.keys(r);
>             "function" == typeof Object.getOwnPropertySymbols && (o = o.concat(Object.getOwnPropertySymbols(r).filter(function(e) {
>                 return Object.getOwnPropertyDescriptor(r, e).enumerable
>             }))), o.forEach(function(t) {
>                 n(e, t, r[t])
>             })
>         }
>         return e
>     }
> }, function(e, t, r) {
48,51c62,68
<     console.log({ ...{
<             a: 1,
<             b: 2
<         },
---
>     r.r(t);
>     var n = r(0),
>         o = r.n(n);
>     console.log(o()({}, {
>         a: 1,
>         b: 2
>     }, {
53c70,79
<     })
---
>     }))
> }, function(e, t) {
>     e.exports = function(e, t, r) {
>         return t in e ? Object.defineProperty(e, t, {
>             value: r,
>             enumerable: !0,
>             configurable: !0,
>             writable: !0
>         }) : e[t] = r, e
>     }
```

cc 
@Automattic/team-calypso 
@Automattic/calypso-sdk 
@Automattic/luna 
@Automattic/poseidon

**Comment by jsnajdr** [comment]
One idea for a quick fix: turn `CALYPSO_CLIENT=true` into `CALYPSO_SERVER=true`. Then the default (no env variables specified) will be client build instead of server build. That's more appropriate because we build client bundles most of the time and it's the server that is a special case.
