### ISSUE TITLE
Images not appearing when editing in Media Library

### ISSUE THREAD

**Issue by eoinsav** [Automattic/wp-calypso#28649]
I was chatting with a user who can't see the image when they try to edit it in the Calypso media library. I noticed it on another site yesterday but didn't take note of it.

#### Steps to reproduce
1. Starting at URL: larenascorner.com 
2. Navigate to Media.
3. Select one or multiple images and click the `Edit` button.

#### What I expected
Should see the image on the left with the edit fields on the right side:

<img width="1811" alt="expected" src="https://user-images.githubusercontent.com/35590156/48667626-a38dc400-ea8f-11e8-9353-6113ba09a67d.png">

#### What happened instead
The image on the left side doesn't appear:

<img width="1611" alt="result" src="https://user-images.githubusercontent.com/35590156/48667646-febfb680-ea8f-11e8-9451-c469d412cef4.png">

Chat:#7820838-hc
Follow-up: #1575714-zen

**Comment by arunsathiya** [comment]
I can confirm that I am able to reproduce this as well on my test sites. This happens both when single/multiple images are chosen to edit.

<img width="1281" alt="screenshot 2018-11-18 at 12 32 14" src="https://user-images.githubusercontent.com/18581859/48669604-3e3ce000-eb2e-11e8-8a56-e0673c7f794d.png">
<img width="1281" alt="screenshot 2018-11-18 at 12 32 20" src="https://user-images.githubusercontent.com/18581859/48669605-3ed57680-eb2e-11e8-81d2-9b97ebdb3e81.png">
<img width="1281" alt="screenshot 2018-11-18 at 12 32 22" src="https://user-images.githubusercontent.com/18581859/48669606-3ed57680-eb2e-11e8-8997-f8fbce777560.png">

From what I see, this is the case on [wpcalypso.wordpress.com](https://wpcalypso.wordpress.com) and [horizon.wordpress.com](https://horizon.wordpress.com) as well.

**Comment by yoavf** [comment]
Seems like this was caused by #28288
The styles for `.editor-media-modal__content` are missing from the css loaded for the media editor (`async-load-post-editor-media-modal~media.css`).

Adding `import "../index.scss";` to `client/post-editor/media-modal/detail/index.jsx` seems to fix it, but I'm not sure that's the right way to go. CC @blowery and @flootr
