### ISSUE TITLE
Site Pages: List changes while scrolling

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#28640]
#### Steps to reproduce
1. SU/SSP as owner of ericarobbin.com
2. Go to Site Page
3. Scroll through the list of site pages
4. Keep scrolling until it changes

#### What I expected

The pages list should stay in place

#### What happened instead

At some point, the list suddenly changes from a date-ordered list to a hierarchical list

#### Browser / OS version 
Web Browser
Safari 12.0.1

Operating System
Mac OS

(Obtained from supportdetails.net)

I also reproduced using Chrome 70.0.3538.102

#### Screenshot / Video

![screen capture on 2018-11-16 at 15-58-32 copy 2018-11-16 16_26_32](https://user-images.githubusercontent.com/7596032/48648240-9ce24c80-e9bc-11e8-8d12-10d029837b3c.gif)

#### Context / Source

User first reported this in 4643695-hc (follow-up at 1572961-zen ). They noticed it after switching to Gutenberg. When I switched back, the problem remained, but it took much longer than before. (With Gutenberg it would happen within a few seconds of starting to scroll, now it takes more time).

I’m tagging this with Gutenberg because of that, although it may be something that’s just causing it to become more pronounced.

This is a similar behavior to 25646-gh-wp-calypso except that it doesn’t switch until you start scrolling and you can edit pages before the switch happens.

**Comment by jruud** [comment]
Another report of this in 11651483-hc. Follow up is at 1916257-zen.
