### ISSUE TITLE
Gutenberg: Can not access chat in editor for Jetpack sites

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#28642]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/help/contact/
2. Start a chat with support
3. Navigate to /posts or /pages
4. Start a new post/page or edit an existing one

#### What I expected
Being able to continue chatting with support while editing

#### What happened instead
The chat sidebar disappeared and wasn't available in the editor

#### Context / Source
Came from a chat with a customer in 8106770-hc and then tested afterwards

#user-report

**Comment by gwwar** [comment]
👍 This will be an known issue until we can fully launch Gutenberg in Calypso, or we bring chat support into wp-admin

**Comment by vindl** [comment]
I'm going to close this since it requires no specific action at this moment. It will be auto-resolved once we launch Gutenberg in Calypso (hopefully soon), and there are no plans to bring chat support into wp-admin yet.

**Comment by chaitanyamsv** [comment]
Hi @vindl 

I am re-opening this because the iframed Gutenberg doesn't show the Happychat window in the editor screen. Not being able to chat with us while in the page/post editor is frustrating to many users and it is nice to have Happychat available in the editor as well.

**Comment by vindl** [comment]
Note that this issue should be automatically resolved once Gutenframe is enabled for Jetpack sites. Since it's currently relying on wp-admin redirects (Calypsoify), the missing support chat is expected.

**Comment by mmtr** [comment]
Closing this since we enabled Gutenframe for Jetpack a few months ago.
