### ISSUE TITLE
Share: Link to change site timezone is invalid

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#28646]
#### Steps to reproduce 

- Start with a Jetpack Premium plan site, or a WordPress.com site with WordPress.com Premium plan at the least
- **Edit to add**: This appears only when the site timezone on settings is different from that of the local time. Visit the site settings at https://wordpress.com/settings/general and choose a timezone that is different from that of your local timezone.
- Visit https://wordpress.com/posts
- Click on the 3 dots next to a blog post 
- Click `Share`
- Pop open the schedule datepicker
- Click the information icon beside the message about the timezone difference.
- Click `General settings` link shown

<img width="919" alt="screenshot 2018-11-17 at 15 45 54" src="https://user-images.githubusercontent.com/18581859/48660233-94eddf80-ea84-11e8-85e8-e812be26861b.png">

#### What is expected 

I am taken to https://wordpress.com/settings/general to edit the timezone

#### What happens instead 

I am take to https://wordpress.com/settings/general/null instead, and I am shown a weird state as shown below

<img width="797" alt="screenshot 2018-11-17 at 15 46 21" src="https://user-images.githubusercontent.com/18581859/48660232-90c1c200-ea84-11e8-8eb1-99315ab288f8.png">

#### Related:

Same report but for calendar on `Post settings` section of blog post editor page: https://github.com/Automattic/wp-calypso/issues/12157

**Comment by torres126** [comment]
It looks like the bit with the link has been removed now.

<img width="446" alt="Screenshot 2019-04-21 at 13 12 37" src="https://user-images.githubusercontent.com/43215253/56469870-2e0b9280-6437-11e9-908b-857e758091e9.png">

**Comment by arunsathiya** [comment]
I am still able to reproduce this. This is how it looks.

<img width="455" alt="Screenshot 2019-04-21 at 17 46 00" src="https://user-images.githubusercontent.com/18581859/56469915-64f49f00-645d-11e9-91b6-ec0dee5a58b7.png">

I should clarify a bit: This appears only when the site timezone on settings is different from that of the local time.

**Comment by arunsathiya** [comment]
This is still an issue.

**Comment by arunsathiya** [comment]
Remains an issue. Tested.

**Comment by arunsathiya** [comment]
Tested again, still an issue.

**Comment by mreishus** [comment]
@arunsathiya , I've deployed a fix for this, could you see if it's still an issue?

**Comment by arunsathiya** [comment]
I confirm this is no longer an issue. Thanks for the patch, @mreishus!
