### ISSUE TITLE
Simple payments block: Fix disabled multiple styling

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#28659]
Via @simison: https://github.com/Automattic/wp-calypso/pull/28608#discussion_r234520202

Reproduced here:

---

When the form is in a disabled state, toggle has some funky borders going on:

<img width="218" alt="image" src="https://user-images.githubusercontent.com/87168/48691485-620a2f80-ebdb-11e8-98e2-d56006553798.png">

Seems to be coming from Gutenberg core even in latest `master`; I'll open an issue there.

Meanwhile, we could fix it by setting `border: 0` ?

**Comment by simison** [comment]
>WP Admin, Calypso or both?

Both.

#### In Calypso:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/87168/48695169-152c5600-ebe7-11e8-8540-18fcccbfb06c.png">

#### In wp-admin:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/87168/48695174-1e1d2780-ebe7-11e8-9ff0-b9a3fa7f51c2.png">

You can replicate with this block:
```jsx
/** @format */

/**
 * External dependencies
 */
import { registerBlockType } from '@wordpress/blocks';
import { Disabled, ToggleControl } from '@wordpress/components';
import { Fragment } from '@wordpress/element';
import { InspectorControls } from '@wordpress/editor';

const toggles = (
	<Fragment>
		<Disabled>
			<ToggleControl label="This is disabled" />
		</Disabled>
		<ToggleControl label="This is not disabled" />
	</Fragment>
);

registerBlockType( 'demo/toggle-control', {
	title: 'Toggle Control demo',
	category: 'layout',
	edit: () => (
		<Fragment>
			<InspectorControls>{ toggles }</InspectorControls>
			{ toggles }
		</Fragment>
	),
	save: () => null,
} );
```

Gutenberg issue: https://github.com/WordPress/gutenberg/issues/12049

**Comment by simison** [comment]
Fixed upstream: https://github.com/WordPress/gutenberg/pull/12091

**Comment by simison** [comment]
Actually, nope, this will not be fixed for 5.0 but only in the next point release after it.

Gutenberg milestones:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/87168/48767150-b5a17980-ecbe-11e8-8d45-53efc7dc376f.png">

**Comment by simison** [comment]
I opened an issue for Calypso: https://github.com/Automattic/wp-calypso/issues/28707

Meanwhile, we can patch this only for simple payments block that ships in Jetpack.

**Comment by sirreal** [comment]
I got off-GitHub confirmation that we can expect https://github.com/WordPress/gutenberg/pull/12091 to land in 5.

**Comment by simison** [comment]
Upstream merged. 👍
