### ISSUE TITLE
Gutenberg: Featured image not visible in Preview prior to Save on draft posts

### ISSUE THREAD

**Issue by nickpagz** [Automattic/wp-calypso#28657]
#### Steps to reproduce
1. Add new post from Calypso
2. Add Featured Image to post
3. Click on Preview

#### What I expected
Expected to see a preview of the post including the Featured Image.

#### What happened instead
Post preview did not include the Featured Image.

#### Browser / OS version
Chrome Version 70.0.3538.102 (Official Build) (64-bit) on Mac 10.14.1

#### Screenshot / Video
None

#### Context / Source

#user-report in chat support. Tested on my own test site and was able to reproduce. The featured image will show only after the Save Draft has been clicked.

**Comment by gwwar** [comment]
For folks taking the issue, let's verify if Gutenberg core is trigging a save on preview click.

**Comment by gwwar** [comment]
Closing this out since I verified that this is core behavior. (see p9dueE-rW-p2 for a quick way to test)

@nickpagz maybe file an enhancement or bug in https://github.com/WordPress/gutenberg/issues ?
