### ISSUE TITLE
Domains: Contact Info Validation Message Prevents Filling the Form

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#2866]
Once you click submit with an empty information, the validation message is very intrusive and does not go away, making it really annoying to fill the form out.

![vid](http://g.recordit.co/7LoamjbKUI.gif)

**Comment by umurkontaci** [comment]
/cc: @breezyskies Maybe we can inline the errors with this as well?

**Comment by breezyskies** [comment]
Yes, we should port this to inline comments too. See https://github.com/Automattic/wp-calypso/issues/2140#issuecomment-176783059 for an example.
