### ISSUE TITLE
Gutenberg: Publicize doesn't refresh after closing tab with connections

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#28664]
In the Publicize extension for Gutenberg, we're supposed to be refreshing the connections after we close the tab that was opened for connecting a new service. It seems that we're calling `dispatch( 'core/editor' ).refreshPost`, but it doesn't do the job. 

Let's make sure we properly refresh the connections after the tab is closed.

This came up several times in p1HpG7-5Ta-p2 from various testers, including @melchoyce, @arunsathiya and @alisterscott 

Additionally, do we want to refresh automatically on some interval @ockham?

**Comment by ockham** [comment]
Filed upstream issue https://github.com/WordPress/gutenberg/issues/12055

**Comment by tyxla** [comment]
Our fix for this has landed in Gutenberg:

https://github.com/WordPress/gutenberg/pull/12060

Closing this one.
