### ISSUE TITLE
Gutenberg: Unable to delete the Publicize custom message to start over

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#28677]
As reported by @arunsathiya in p1HpG7-5Ta-p2:

> I am unable to remove all the text in the Publicize message. Cmd + A > Delete does not work. [Video showing this behaviour](https://cloudup.com/cpCLq_fxFQh).
>
> Trying to remove all the words on the Publicize message does not work, fails when the time to remove the first word comes. [Video showing this behaviour](https://cloudup.com/cNAPxPrxYyE).

It seems we'll need to be smarter about defaulting the message to post title, and change this to happen only if the user hasn't yet updated the custom message manually.

**Comment by mapk** [comment]
Yep, this is frustrating.

![character-count](https://user-images.githubusercontent.com/617986/48731993-44e15b00-ebf3-11e8-8abc-e76b727ff7e3.gif)
