### ISSUE TITLE
Site Importer: Warn trying to import a WordPress.com url

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#28694]
## Summary

Looking at logs for the site importer (which currently powers Wix imports), some users are entering WordPress.com urls... presumably because that's the site they want to import content into.

Improve the error message shown to indicate users should enter the site they want to import content from, rather than the site they want to import content into.

<img width="753" alt="screen shot 2018-11-19 at 13 58 55" src="https://user-images.githubusercontent.com/1699996/48731785-7e21c700-ec03-11e8-90f9-3b6f26816625.png">

**Comment by jancavan** [comment]
I think if it's already a wpcom site, we should just ask them to login, something like - "It looks like this site already exists! Log-in now."

**Comment by creativecoder** [comment]
This is still an issue.

**Comment by creativecoder** [comment]
Still valid. Added to Caribou Reindeer pod's project board for triaging, in case it's a fit for current priorities.

**Comment by kosiew** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/49675 too

**Comment by kosiew** [comment]
hi @vishnugopal , can you review this in the Reindeer project board?

**Comment by vishnugopal** [comment]
This is fixed in the new [onboarding importer flow](pcmemI-b6-p2). We plan to retire the Tools > Import flow, so I'm marking this as WONTFIX.
