### ISSUE TITLE
Reader: Unfollowing from Followed Sites stream not working

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#287]
Earlier this week I got fed up with a site I follow—they published too many posts at once and it really killed my stream early in the morning—so I unfollowed them using the `...` menu from the card in my Followed Sites stream. A few days later, I noticed posts from this site were still showing my stream, so I unfollowed again.

This morning I was scrolling through and saw posts again:

![screen shot 2015-11-20 at 10 50 55 am](https://cloud.githubusercontent.com/assets/191598/11305190/7b312ca0-8f79-11e5-9ae3-ef99c101706c.png)

I've unfollowed them again, and will let you know if I get more posts — but maybe its worth a look at the Followed Sites unfollow button to make sure its working.

**Comment by blowery** [comment]
refs #749

**Comment by shaunandrews** [comment]
Just following up: I'm still seeing posts from www.wicz.com in my Followed Sites stream.
