### ISSUE TITLE
Gutenberg: disabled toggle visually broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28707]
While building Gutenberg block for Simple Payments, we used disabled toggle component from Gutenberg.

This is how it looked for Calypso:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/87168/48695169-152c5600-ebe7-11e8-8540-18fcccbfb06c.png">

And in wp-admin:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/87168/48695174-1e1d2780-ebe7-11e8-9ff0-b9a3fa7f51c2.png">

The border will be fixed for Gutenberg (https://github.com/WordPress/gutenberg/pull/12091) but that fix will still leave Calypso broken, as demonstrated in https://github.com/Automattic/wp-calypso/issues/28659#issuecomment-440222606:

![screen shot 2018-11-20 at 11 25 47](https://user-images.githubusercontent.com/841763/48767496-26449800-ecb7-11e8-9400-9e77b9385537.png)

You can replicate the problem with this block:
```jsx
/**
 * External dependencies
 */
import { registerBlockType } from '@wordpress/blocks';
import { Disabled, ToggleControl } from '@wordpress/components';
import { Fragment } from '@wordpress/element';
import { InspectorControls } from '@wordpress/editor';

const toggles = (
	<Fragment>
		<Disabled>
			<ToggleControl label="This is disabled" />
		</Disabled>
		<ToggleControl label="This is not disabled" />
	</Fragment>
);

registerBlockType( 'demo/toggle-control', {
	title: 'Toggle Control demo',
	category: 'layout',
	edit: () => (
		<Fragment>
			<InspectorControls>{ toggles }</InspectorControls>
			{ toggles }
		</Fragment>
	),
	save: () => null,
} );
```

Tracking the fix for Simple payments in wp-admin here: https://github.com/Automattic/wp-calypso/issues/28659

**Comment by kwight** [comment]
This must have gotten fixed at some point by something, I can't replicate on `wpcalypso` nor `master`:

<img width="201" alt="screen shot 2018-12-12 at 1 38 42 pm" src="https://user-images.githubusercontent.com/349751/49900424-5c3aef00-fe13-11e8-970c-47e3972da66d.png">
