### ISSUE TITLE
Bug: Checklist shows empty content with only the percentage image

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#28700]
There has been a case that the onboarding checklist shows an empty message for a few sites, and I am not 100% sure what triggers that. It shows only the percentage of completion on opening the WordPress.com dashboard.

It looks as shown below.

![screenshot 2018-11-19 at 16 45 15](https://user-images.githubusercontent.com/18581859/48743650-ef0bc200-ec89-11e8-9703-bfe4f39e25cd.png)

![screenshot 2018-11-19 at 16 45 32](https://user-images.githubusercontent.com/18581859/48743649-ef0bc200-ec89-11e8-9113-c3e5bb554cfd.png)
In my case, I have completed all the checklist activities.

I can add the steps to reproduce when I figure that out. 

There is an user report as well, from @katiebethbrown. #user-report

**Comment by katiebethbrown** [comment]
I have a user seeing this in 1580583-zen

**Comment by kriskarkoski** [comment]
1570223-zen

**Comment by liviopv** [comment]
Another #1610000-zen

**Comment by liviopv** [comment]
Related to #26890 maybe?

**Comment by GeoJunkie** [comment]
Also in 1616802-zen . User's percentage shows exactly as in the bug report. As a note, we calculated that 91% is 10/11, so there may be a hidden/miscounted step.

**Comment by jrodger** [comment]
Hit an instance of this here: #1627095-zen

**Comment by AtrumGeost** [comment]
Another one here:

1629286-zen

It is very odd because for a couple of seconds it displays this screen before displaying the empty one with 91%:

![email-conf](https://user-images.githubusercontent.com/3696121/49700274-7920b980-fbaa-11e8-973a-018f8b7aeed0.png)

**Comment by AtrumGeost** [comment]
1635435-zen 

site: robertbannisterphotography.com

**Comment by iamgabrielma** [comment]
9040373-hc
site: weonfamily.com

**Comment by chad1008** [comment]
Another report of this in 8659751-hc (followup in 1683236-zen)
Site:  antheiart.com

Stats page shows 89% complete in an otherwise empty block that can't be dismissed, and the actual checklist is fully completed.

**Comment by iamgabrielma** [comment]
1697064-zen

**Comment by pauljacobson** [comment]
Hi there, I also encountered this in 9406793-hc.

I didn't see it when I first accessed the dashboard. It appeared when I refreshed the page, though. As with other reports, the user had completed the steps (8/8), but was unable to dismiss the graphic.

**Comment by jamiepalatnik** [comment]
Also reported in 8089779-hc (follow-up in 1717834-zen)

**Comment by GeoJunkie** [comment]
Reported in 9546915-hc

Also stuck at 89%

**Comment by arunsathiya** [comment]
@Automattic/onboarding-dev, ping - as was previously mentioned here https://github.com/Automattic/wp-calypso/issues/30244

**Comment by ramonjd** [comment]
> It is very odd because for a couple of seconds it displays this screen before displaying the empty one with 91%:

Here's an attempt to fix that issue. https://github.com/Automattic/wp-calypso/pull/30258

I haven't yet been able to replicate the 'stuck' incorrect percentage bug yet. I levelled my first accusation at the [memoized function](https://github.com/Automattic/wp-calypso/blob/3cd9806/client/my-sites/checklist/wpcom-checklist/wpcom-task-list.js#L103) we use to grab the task list, but in all my tests it behaved :) 

If you notice anything in common with these reports, be it the order of tasks completed, site theme, or anything else relevant, please leave a comment and I'll try to investigate further. 🙇

**Comment by taggon** [comment]
I assume the bug @arunsathiya has reported is fixed with #30268. Let me know if it happens again.

**Comment by arunsathiya** [comment]
It does seem to be resolved on production. Thank you, @taggon! 

![screenshot 2019-01-22 at 12 14 27](https://user-images.githubusercontent.com/18581859/51516990-4d4a5200-1e3f-11e9-8427-e67bd66d31ae.png)
