### ISSUE TITLE
Gutenberg: Blank/white screen in Internet Explorer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#28703]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Start a new post on a site you've opted into Gutenberg on or opt-in to Gutenberg once the Editor opens

#### What I expected
To be able to use the Gutenberg editor

#### What happened instead
The editor does not load and shows a blank/white screen instead

I haven't personally tested this so far, but I have come user reports on this. @lakellie did as well.

**Related**: https://github.com/Automattic/wp-calypso/issues/28544 // cc @kwight 

#user-report

**Comment by arunsathiya** [comment]
#1580769-zen, while it's not all that helpful at the moment, I have reached out for IE and Window version information.

**Comment by KokkieH** [comment]
Another report in the [forums](https://en.forums.wordpress.com/topic/problem-z-dodawaniem-nowego-wpisu-i-edytowaniem-wpisow-juz-istniejacych). IE v. 11.0.9600.19180

I'm also able to replicate in IE v 11.0.9600.18837 on Windows 7 Home Premium.

**Comment by lakellie** [comment]
I was able to replicate using Browserstack - Windows 10, IE 11 (latest version).

I navigated to Blog Posts and clicked to edit an existing blog post, then get a blank screen: http://cld.wthms.co/Eo8fRh

The same happens when I click to add a new post.

**Comment by kwight** [comment]
This is the console error; also noting that there's no regression in Edge (Edge continues to work fine):

![virtualbox_ie11 - win81_20_11_2018_09_58_51](https://user-images.githubusercontent.com/349751/48793310-6b62cd00-ecab-11e8-9836-ab9b3b0efcde.png)

**Comment by kwight** [comment]
Patch in D21161-code ready for review.

**Comment by kwight** [comment]
Fixed in D21161-code.
