### ISSUE TITLE
Gutenberg: verify that translation strategies will work using core packages

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28724]
We use a number of core npm packages published from WordPress. Let's verify if our translation strategy is working in Calypso or if additional work is needed. We should get ahead of this in case we need to let folks translate new strings.

Note that there is core fetch api middleware that adds a user's locale that may not be working correctly.

This is an investigation task. If folks note more needed work, please close this issue and file one specific to what we need to do next.

**Comment by gwwar** [comment]
https://github.com/Automattic/wp-calypso/issues/28541#issuecomment-440777044

**Comment by mmtr** [comment]
We have the same problems we had in Calypsoified Gutenberg, so #29026 should fix them by registering the Gutenberg translations to the default textdomain.

**Comment by gwwar** [comment]
For wp-admin we should be good with:
This should be fixed by D21305-code and D21408-code, written by @mmtr and @akirk ✨ 

Gutenlypso:
And @mmtr's
https://github.com/Automattic/wp-calypso/pull/29026 and D21445-code
