### ISSUE TITLE
Jetpack: improve 2FA error in security settings

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#28738]
Activating 2FA sometimes results in an error that doesn’t direct users to actionable next steps: "An unexpected error occurred. Please try again later.". Instead of this, let's improve the error message and link users to WordPress.com/me/security/two-step to try again.

Proposed improvements:

**BEFORE:**
<img width="865" alt="screen shot 2018-12-18 at 3 17 07 pm" src="https://user-images.githubusercontent.com/204742/50186464-1af58400-02d8-11e9-9323-77595f3bbcb9.png">

**AFTER:**
> An unexpected error occurred while setting up 2-step authentication. [Please try again](https://wordpress.com/me/security/two-step)
<img width="873" alt="screen shot 2018-12-18 at 3 17 15 pm" src="https://user-images.githubusercontent.com/204742/50186472-1fba3800-02d8-11e9-912e-412c825d530a.png">

ref: p6TEKc-2m8-p2 (RB / item 5.7)

**Comment by joanrho** [comment]
Hey @oskosk ! Would the resolution to this issue have any common bits related to the work you did on the custom notices in [#10972](https://github.com/Automattic/jetpack/pull/10972)?

**Comment by oskosk** [comment]
@joanrho. Note that by updating that toggle, one is not actually enabling/disabling 2 factor authentication. Only making Jetpack "require" it, be it enabled or not for any given user, not just the admin toggling that.

**Comment by oskosk** [comment]
Question in the context of my previouse message ^. If this toggle is enabling the requirement for all users, does linking the error message to the administrator's page for enabling only their own 2 step auth still make sense ?

**Comment by oskosk** [comment]
Moving conclusions from slack to this issue.

The user attempting to toggle that setting is not blocked under any condition from doing it. If they haven't enabled step auth, they still can toggle this setting as it's not related to just their user on the Jetpack site, but to any other too. 

The error message in the screenshot here seems to be coming from another setting failing on save. Any information provided by a notice would be erroneous becase we know of no condition that would make the toggling fail for this particular setting. Thus, the "unexpected" notice is accurate.

I'm closing this issue.

**Comment by rickybanister** [comment]
I _think_ we should reopen this issue, or perhaps open a new issue to provide a clear pathway for the current admin user to set up 2fa after toggling on the requirement. At the minimum we should make it easy for the admin that requires 2fa to see a `clickable-card` appear that links them to wordpress.com/me to set up 2fa for themselves only. 

It would be great if you could try to reproduce the error @joanrho is seeing @oskosk and pinpoint whether it's related to Akismet or something else. If customers are seeing that error or the conditions for it to show are reproduce-able then we need to track that down too.

Is that a fair assessment?

**Comment by joanrho** [comment]
@rickybanister thanks for your feedback, but I think you misunderstood the problem. From @oskosk and my discussion in Slack, 2FA IS in fact active, but the error is misleading in its message and is originating from a different source than Jetpack. 

Reopening this issue, but we'll need to do more digging into the source of the error and next steps to take so the resolution is clearer from the user's perspective. Bumping to our Q1 onboarding focus, since this will exceed what we can close out for EV by this Friday.

**Comment by keoshi** [comment]
It would still be important to check what's happening and if we can improve the error message.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
