### ISSUE TITLE
Jetpack: Reorder settings tabs based on priority

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#28741]
Reorder settings tabs (Security, Traffic, Writing, Discussion) based on priority/importance.

ref: p6TEKc-2m8-p2 (RB / item 5.10)

**Comment by keoshi** [comment]
After a brief conversation on Slack, we've decided to abandon this idea for now:

- In addition to Jetpack, this also affects the experience for dotcom simple sites.
- We're not sure if “Traffic” is more relevant than, say, “Writing” settings for those users.
- We could introduce a `isJetpackSite` check, but that will fork the experience and make the UI unpredictable for no apparent reason.
- **Decision**: we'll close this for now, and focus on a better onboarding experience in the coming weeks.

Ref: p1544455926005100-slack
