### ISSUE TITLE
Calypso Gutenberg: Permalink section not shown

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#28778]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg
2. Create a post and save a draft

#### What I expected

A permalink as per wp-admin

#### What happened instead

No permalink that I could see

#### Browser / OS version

Chrome on macOS

#### Screenshot / Video Calypso

<img width="1151" alt="screen shot 2018-11-22 at 12 28 48 pm" src="https://user-images.githubusercontent.com/128826/48878231-5a07f500-ee52-11e8-9ec9-ae8edb062af8.png">

#### Screenshot / Video wp-admin

<img width="1150" alt="screen shot 2018-11-22 at 12 28 59 pm" src="https://user-images.githubusercontent.com/128826/48878238-62f8c680-ee52-11e8-9b24-676820e908ea.png">

**Comment by Copons** [comment]
This was magically fixed by #29075
