### ISSUE TITLE
Add new site: Does not continue from where I left off

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#28785]
#### Steps to reproduce
1. Sign in to https://wordpress.com/ and go to My Sites > Switch Site.
2. Click "Add New Site" at the bottom of the sites list -  _/jetpack/new?ref=calypso-selector_
3. Click the "Start Now" button for WordPress.com site
4. In the Site Goals checklist, select "Sell products or collect payments”.
<img width="511" alt="screenshot 2018-11-22 at 2 29 12 pm" src="https://user-images.githubusercontent.com/1269602/48892031-07830480-ee63-11e8-9d71-e79c63b1abbc.png">

5. Verify that you've entered the ecommerce flow ( url changed to _/start/ecommerce/...._ )
6. Drop off at the Plans step ( _/start/ecommerce/plans_) - navigate away to a different part of calypso or close tab but continue to remain logged in
7. Go to Add a New Site again _/jetpack/new?ref=calypso-selector/_  and click Start Now button

It directly takes to the Plans step but check the URL  - it will be _/start/plans_ which means we're not in the ecommerce flow any longer, as can be seen with the missing `ecommerce` in the URL.

#### What I expected

 I would expect that since I dropped off the Plans step in the ecommerce flow, I should still be in the same flow when I'm taken there.

#### Screenshot / Video

Here's a screen recording - https://cloudup.com/cC_f82jHuA2

**Comment by jhnstn** [comment]
This is fixed by #28720
