### ISSUE TITLE
Gutenberg: Classic block linking tool doesn't work

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#28786]
As [reported on the French forums](https://fr.forums.wordpress.com/topic/impossible-dinserer-un-lien-texte-avec-le-nouvel-editeur/), the linking tool doesn't work well with the Classic block.

#### Steps to reproduce
1. On a non-Gutenberg editor site, publish a new post starting at URL: https://wordpress.com/post
2. Activate Gutenberg and edit the post you created previously with the new editor. The content you previously created will be using the "Classic" block.
3. Select a word to insert a link.
4. Try to insert a link and see it doesn't work: nothing happens once you click the submit button.
5. After failing, the floating window to insert links doesn't go away.

#### What I expected
* Expected the link to be created.

#### What happened instead
* The selected word doesn't get linked.
* The linking inserter tool doesn't go away.

#### Browser / OS version
Chrome, Mojave

#### Screenshot / Video
![screen capture on 2018-11-22 at 10-41-53](https://user-images.githubusercontent.com/16645645/48894603-69cc0d00-ee43-11e8-90cc-aaa43f7f1c37.gif)

**Comment by lizkarkoski** [comment]
Another report in the forums at https://en.forums.wordpress.com/topic/problem-adding-link-with-new-editor/

Using MAC OSX 10.11.6 - Chrome 70.0.3538.102

**Comment by gwwar** [comment]
As an aside, have y'al gotten folks to convert the blocks, or do they want to continue using the classic blocks?

I'm thinking https://github.com/Automattic/wp-calypso/issues/26594 would be a better user interaction for wpcom

**Comment by cecilearkay** [comment]
I didn't know this was an option actually. Just so I understand correctly, there won't be a fix but instead, we'll have to suggest to the user to convert the block?

**Comment by gwwar** [comment]
@cecilearkay Two concerns:
- We should fix this, but it's a lower priority bug compared to what's on the current backlog
- Since folks don't know how to convert blocks, I do want to make that prompt more visible. https://github.com/Automattic/wp-calypso/issues/26594

If folks do want to use the Gutenberg editor on an older post, I would recommend converting, though some formatting might not be 1:1.

**Comment by mdrockwell** [comment]
User replied in 1645742-zen to mention that they tried in Chrome and Safari — they have the problem in both.

**Comment by samiff** [comment]
Another in 9252357-hc

**Comment by nakitadog** [comment]
I'm seeing this issue as well in WordPress 5.0.2.

**Comment by mmtr** [comment]
Seems to be solved after removing Gutenlypso in favor of Gutenframe (#31196).
