### ISSUE TITLE
X-post load error on Desktop App (mac)

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/wp-calypso#2880]
In the reader on the Mac Desktop app I have been able to replicate an error (several times) that occurs when 1 or more x-posted posts load with the "New Posts" button. The reader throws this error `build-desktop.js:7103 Uncaught TypeError: Parameter 'url' must be a string, not object` and from there you can't really do anything. Navigating around doesn't work, everything is frozen from that point on. The only way to fix the problem is to restart the app. 

https://cloudup.com/cummnVI_A-1
https://cloudup.com/cZlq7EpvoiE

Here is the full error: 

`Uncaught TypeError: Parameter 'url' must be a string, not objectUrl.parse @ build-desktop.js:7103urlParse @ build-desktop.js:7097getSiteNameFromURL @ build-desktop.js:268521getDescription @ build-desktop.js:268526render @ build-desktop.js:268619ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ build-desktop.js:314423ReactCompositeComponentMixin._renderValidatedComponent @ build-desktop.js:314443ReactCompositeComponentMixin.mountComponent @ build-desktop.js:314056ReactReconciler.mountComponent @ build-desktop.js:75945ReactMultiChild.Mixin._mountChildByNameAtIndex @ build-desktop.js:317278ReactMultiChild.Mixin._updateChildren @ build-desktop.js:317182ReactMultiChild.Mixin.updateChildren @ build-desktop.js:317130ReactDOMComponent.Mixin._updateDOMChildren @ build-desktop.js:315461ReactDOMComponent.Mixin.updateComponent @ build-desktop.js:315290ReactDOMComponent.Mixin.receiveComponent @ build-desktop.js:315235ReactReconciler.receiveComponent @ build-desktop.js:75995ReactCompositeComponentMixin._updateRenderedComponent @ build-desktop.js:314398ReactCompositeComponentMixin._performComponentUpdate @ build-desktop.js:314380ReactCompositeComponentMixin.updateComponent @ build-desktop.js:314309ReactCompositeComponentMixin.receiveComponent @ build-desktop.js:314241ReactReconciler.receiveComponent @ build-desktop.js:75995ReactChildReconciler.updateChildren @ build-desktop.js:313793ReactMultiChild.Mixin._reconcilerUpdateChildren @ build-desktop.js:317024ReactMultiChild.Mixin._updateChildren @ build-desktop.js:317155ReactMultiChild.Mixin.updateChildren @ build-desktop.js:317130ReactDOMComponent.Mixin._updateDOMChildren @ build-desktop.js:315461ReactDOMComponent.Mixin.updateComponent @ build-desktop.js:315290ReactDOMComponent.Mixin.receiveComponent @ build-desktop.js:315235ReactReconciler.receiveComponent @ build-desktop.js:75995ReactCompositeComponentMixin._updateRenderedComponent @ build-desktop.js:314398ReactCompositeComponentMixin._performComponentUpdate @ build-desktop.js:314380ReactCompositeComponentMixin.updateComponent @ build-desktop.js:314309ReactCompositeComponentMixin.receiveComponent @ build-desktop.js:314241ReactReconciler.receiveComponent @ build-desktop.js:75995ReactCompositeComponentMixin._updateRenderedComponent @ build-desktop.js:314398ReactCompositeComponentMixin._performComponentUpdate @ build-desktop.js:314380ReactCompositeComponentMixin.updateComponent @ build-desktop.js:314309ReactCompositeComponentMixin.performUpdateIfNecessary @ build-desktop.js:314257ReactReconciler.performUpdateIfNecessary @ build-desktop.js:76010runBatchedUpdates @ build-desktop.js:67262Mixin.perform @ build-desktop.js:96449Mixin.perform @ build-desktop.js:96449assign.perform @ build-desktop.js:67219flushBatchedUpdates @ build-desktop.js:67280Mixin.closeAll @ build-desktop.js:96515Mixin.perform @ build-desktop.js:96462ReactDefaultBatchingStrategy.batchedUpdates @ build-desktop.js:155390enqueueUpdate @ build-desktop.js:67309enqueueUpdate @ build-desktop.js:109422ReactUpdateQueue.enqueueSetState @ build-desktop.js:109588ReactComponent.setState @ build-desktop.js:154887updateState @ build-desktop.js:75074EventEmitter.emit @ build-desktop.js:70568setPost @ build-desktop.js:77998(anonymous function) @ build-desktop.js:78101(anonymous function) @ build-desktop.js:102010(anonymous function) @ build-desktop.js:80933classifyPost @ build-desktop.js:183669(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936(anonymous function) @ build-desktop.js:102368(anonymous function) @ build-desktop.js:80933wordCountAndReadingTime @ build-desktop.js:102508(anonymous function) @ build-desktop.js:102359iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936detectEmbeds @ build-desktop.js:102531(anonymous function) @ build-desktop.js:102359iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936disableAutoPlayOnMedia @ build-desktop.js:102594(anonymous function) @ build-desktop.js:102359iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936disableAutoPlayOnEmbeds @ build-desktop.js:102613(anonymous function) @ build-desktop.js:102359iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936makeEmbedsSecure @ build-desktop.js:102492(anonymous function) @ build-desktop.js:102359iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936safeContentImages @ build-desktop.js:102458(anonymous function) @ build-desktop.js:102359iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936removeContentStyles @ build-desktop.js:102397(anonymous function) @ build-desktop.js:102359iterate @ build-desktop.js:80925async.eachSeries @ build-desktop.js:80941withContentDOM @ build-desktop.js:102357(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936safeImageProperties @ build-desktop.js:102241(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936firstPassCanonicalImage @ build-desktop.js:102204(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936assignPrimaryTag @ build-desktop.js:102227(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936makeSiteIDSafeForAPI @ build-desktop.js:102212(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936preventWidows @ build-desktop.js:102180(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936stripHTML @ build-desktop.js:102171(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925(anonymous function) @ build-desktop.js:80936decodeEntities @ build-desktop.js:102157(anonymous function) @ build-desktop.js:102004iterate @ build-desktop.js:80925async.eachSeries @ build-desktop.js:80941normalizePost @ build-desktop.js:102002normalizePost @ build-desktop.js:78099receiveBlogPost @ build-desktop.js:78054(anonymous function) @ build-desktop.js:77934_invokeCallback @ build-desktop.js:290970dispatch @ build-desktop.js:290946handleServerAction @ build-desktop.js:3873receivePost @ build-desktop.js:89307onPostReceived @ build-desktop.js:89287(anonymous function) @ build-desktop.js:183783(anonymous function) @ build-desktop.js:68288(anonymous function) @ build-desktop.js:151755baseForOwn @ build-desktop.js:79553(anonymous function) @ build-desktop.js:304580receiveBatch @ build-desktop.js:183764(anonymous function) @ build-desktop.js:161100(anonymous function) @ build-desktop.js:195982(anonymous function) @ build-desktop.js:160068Request.callback @ build-desktop.js:77136(anonymous function) @ build-desktop.js:76780Emitter.emit @ build-desktop.js:321817xhr.onreadystatechange @ build-desktop.js:77213`

cc/ @blowery

**Comment by lancewillett** [comment]
I can't repeat this one — if you still see it in the desktop app (but not in Calypso web app) please re-open over at https://github.com/Automattic/wp-desktop/issues
