### ISSUE TITLE
Gutenberg: Cover image goes to the left when making it fullwidth

### ISSUE THREAD

**Issue by gpmw** [Automattic/wp-calypso#28809]
Testing in Calypsoified Gutenberg page editor on a Simple site with a Premium upgrade with no custom domain.

#### Steps to reproduce
1. In the Calypsoified Gutenberg page editor, add a Cover image block.
2. Add an image
3. Make the image full width
4. The cover image block is pushed to the left.
5. Change image to any other alignment and it works as normal

#### What I expected
The image should be displayed as fullwidth in the editor

#### What happened instead
The cover image block is pushed to the left

#### Browser / OS version
Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)
Mac OS Mojave Version 10.14.1(18B75)

#### Screenshot / Video
http://cld.wthms.co/1xMPEe

**Comment by arunsathiya** [comment]
I am not able to reproduce this with Twenty Seventeen theme, but is reproducible on Business theme. From your screenshot, it appears you were able to see the same with Business theme as well.

It can be moved to https://github.com/Automattic/themes/issues, @gpmw.

**Comment by gpmw** [comment]
I concur so closing here and moving to: [#](https://github.com/Automattic/themes/issues/399#issue-384081922)
