### ISSUE TITLE
Gutenberg: Missing the "Add via URL" option for media

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#28805]
#### Steps to reproduce
1. At My Site ->Blog Posts ->Add with Gutenberg enabled
2. Under the Document settings, under Featured Image, click Set Featured Image

#### What I expected
To have three options available: Select an existing file from the media library, upload a file from my computer, or upload a file hosted elsewhere online via its URL as is currently possible in Calypso

#### What happened instead
I only have the options to select from the media library or upload from my computer.

#### Screenshot / Video
Calypso:

<img width="448" alt="edit_post_ _kokkiestrialtestsite_ _wordpress_com" src="https://user-images.githubusercontent.com/11873759/48917780-43cd5980-ee91-11e8-8df5-9c73181a9dbf.png">

Gutenberg:
<img width="361" alt="edit_post_ _kokkiestrialtestsite_ _wordpress" src="https://user-images.githubusercontent.com/11873759/48917800-59db1a00-ee91-11e8-85c6-01ce9697a124.png">

#### Context / Source

User request in the [support forums](https://en.forums.wordpress.com/topic/feature-image-from-url-in-new-editor/)

**Comment by vindl** [comment]
This has been resolved by the release of Gutenlypso which integrates Calypso's Media Library.
