### ISSUE TITLE
Gutenberg in Calypso - Trashing a post doesn't show notice on resulting posts screen

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#28813]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post
2. Create a draft
3. Click "Move to Trash"

#### What I expected

Posts screen displays with message post was trashed (as per existing Calypso editor behaviour)

![trash calypso](https://user-images.githubusercontent.com/128826/48930446-58b2f700-ef3c-11e8-8119-aa9d3ea02012.gif)

#### What happened instead

No notice on posts screen:

![trash calypso gutenberg](https://user-images.githubusercontent.com/128826/48930452-623c5f00-ef3c-11e8-93eb-bca81416681f.gif)

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

*see above for before and after

#### Context / Source

Found converting e2e tests

**Comment by bsessions85** [comment]
Now this isn't taking the user to the post page at all. The post is deleted behind the scenes, but there isn't a notice and you're not taken to the posts page. The only way to know the post has been deleted is because if you click the trash button again, it tells you that it had already been deleted.

**Comment by alisterscott** [comment]
> Now this isn't taking the user to the post page at all. The post is deleted behind the scenes, but there isn't a notice and you're not taken to the posts page. The only way to know the post has been deleted is because if you click the trash button again, it tells you that it had already been deleted.

Confirmed this isn't working. We'll need to re-enable these e2e tests when it is to stop this happening again

**Comment by Copons** [comment]
@bsessions85 @alisterscott I'm working on the notice, but in my tests, clicking on "Move to trash" directs back to the posts list, trash tab.
Could you please double check? We changed plenty of things in the last couple of weeks in that area of Gutenberg.

**Comment by bsessions85** [comment]
@Copons  It is now taking me to the posts list, but the notice that the post was trashed still isn't showing( original issue )

**Comment by Copons** [comment]
@bsessions85 Yup, that's what I meant, thanks for checking! 👍
