### ISSUE TITLE
Gutenberg: JSON is missing from the Language setting for SyntaxHighlighter Code Block

### ISSUE THREAD

**Issue by reginabally** [Automattic/wp-calypso#28833]
This is a feature request from 1586070-zen.

The request is to add the JSON option into the Language setting for SyntaxHighlighter Code Block on top of the existing options listed [here](https://en.support.wordpress.com/code/posting-source-code).

**Comment by tbradsha** [comment]
Note that selecting Javascript should allow for valid JSON input.

**Comment by arunsathiya** [comment]
I am closing this as a non-issue. Like @tbradsha mentioned, JavaScript formatting should be fine and the user seems to be happy with it as well. There was a request for color-formatting that text, but @achyuthajoy clarified that color-formatting is unique to the code editor that the user is using.
