### ISSUE TITLE
Tiled gallery block: implement layouts

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28844]
Squares and circles are implemented but missing layouts still need implementing.

- [x] Squares
- [x] Circles
- [x] Mosaic
- [ ] Columns (#29760)

<table><tr><td>
<img width="516" alt="tiled-mosaic" src="https://user-images.githubusercontent.com/87168/49017870-9741ef00-f192-11e8-8044-e52e8f71fbbe.png">mosaic</td><td>
<img width="518" alt="tiled-columns" src="https://user-images.githubusercontent.com/87168/49017865-96a95880-f192-11e8-8cc8-f9b6c2120ecd.png">columns</td></tr><tr><td>
<img width="512" alt="squares" src="https://user-images.githubusercontent.com/87168/49017869-9741ef00-f192-11e8-9f73-aacc49185e2e.png">squares</td><td>
<img width="560" alt="circles" src="https://user-images.githubusercontent.com/87168/49017866-96a95880-f192-11e8-817a-79b9901b5268.png">circles</td></tr></table>

Mosaic specifically is the most challenging one.

## Option 1: porting from PHP
- https://github.com/Automattic/jetpack/tree/f60caecc31ad990eb968bff9731fd639310b5dbb/modules/tiled-gallery

## Option 2: use external library
- These don't handle calculating dimensions for images, basically requiring you to calculate sizes for images and these libraries will then position those images to different layouts:
  - https://github.com/bigbitecreative/macy.js
  - https://github.com/callmecavs/bricks.js
  - https://github.com/rnmp/salvattore
  - https://github.com/desandro/masonry
    - _Masonry does cascading grid "masonry" layouts._
  - https://github.com/metafizzy/isotope
    - _Isotope does sorting and filtering. Isotope uses masonry layouts, as well as other layouts._
  - https://github.com/desandro/packery  
    - _Packery does bin-packing layouts, which allow it to be used for draggable interactions._
  - https://github.com/eiriklv/react-masonry-component
    - Depends on `masonry`
  - https://www.npmjs.com/package/muuri
  - https://github.com/neptunian/react-photo-gallery

#### To research more
- https://github.com/awkward/react-simple-masonry
  - Depends on https://github.com/jchn/simple-masonry-layout
    Very nice for calculating masonry columns; you can give it a width of an area and it'll calculate masonry columns and give you values for each image.
    <img width="400" alt="image" src="https://user-images.githubusercontent.com/87168/49729711-e7cf4700-fc7e-11e8-83aa-c81beb7d9cfb.png">
- https://github.com/danielberndt/grid-distribute promising
- https://github.com/kombai/freewall

**Comment by sirreal** [comment]
Possible inspiration: https://github.com/keoshi/mutelife-galeria/
