### ISSUE TITLE
Gutenberg: Publicize add new service button copy not intuitive

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#28845]
Currently, in the Publicize extension for Gutenberg, we use **Connect new service** for the button to connect a new service:

![](https://cldup.com/u6pihgZYjc.png)

As reported by @Janna-Pieler and @tanjoymor, this could be non-intuitive for new users.

Let's think about how we could improve this copy to make it more understandable for new users.

cc @mapk @MichaelArestad @ockham and @Automattic/editorial

**Comment by michelleweber** [comment]
Depending on the copy around it, if there is any, it might already be clear. What's the rest of the flow / what else is on the screen when someone gets this message?

**Comment by tyxla** [comment]
@michelleweber thanks for chiming in!

This basically appears in the pre-publish sidebar, which the user sees as a confirmation when clicking "Publish":

![](https://cldup.com/akRRLBfk7d.png)

When the user clicks the button, they're presented with a new window that displays the Sharing settings in their wp-admin, where they can connect a social network.

Let me know if you need any other details.

**Comment by michelleweber** [comment]
I might change it to "connect another service" or "connect another account," both of which clarify it slightly. (I'd opt for "account" as being the clearer option.) But since it's contextual with the rest of the Publicize stuff, I don't actually think you need more than that.

**Comment by michelleweber** [comment]
Hmm. Ideally there'd be two different messages depending on whether you have anything already connect or not, but if we can't do that, we can just do "Connect an account," which covers all bases.

In general, I do think "account" is clearer -- you're not connecting to Twitter or Facebook generally, you're connecting _your_ Twitter account. I'd want to take a look at all the places it would change to make sure it makes sense and doesn't require tweaking anything else. For the other text on this screen, I'd love to update to "Connect and select the accounts where you'd like to share your post."

**Comment by tyxla** [comment]
Thanks a bunch @michelleweber! Here's a PR for that:

https://github.com/Automattic/wp-calypso/pull/28955

**Comment by MichaelArestad** [comment]
I think "account" could be taken out of context a bit more than "service." It's not always an account, either.

**Comment by michelleweber** [comment]
Honestly, it's a pretty marginal change; there's not a real way to make this that much clear in three or four words, and adding a tooltip would do more than any copy changes. If the original feels clears to you, stick with the original; I still think there's enough context on this screen that no big changes are called for.

**Comment by tyxla** [comment]
I think I prefer "account" too, which is why I filed #28955.

But @MichaelArestad if you have strong feelings against it, it's probably a good idea to close it together with this issue, since the copy is already in a satisfactory state.

**Comment by tyxla** [comment]
I'm planning to merge the PR tomorrow if there are no objections.
