### ISSUE TITLE
Calypso pulls WooCommerce product review count into Comments section

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/wp-calypso#28858]
Currently, calypso is pulling WooCommerce product reviews into the Comments section but not displaying them. The comments can be seen within the WP Admin's Comments section. Please see the source link below for full issue context and investigation results.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/comments/all
No other steps but to navigate to comments

#### What I expected
To see comments of posts

#### What happened instead
There's a comment count of ~16, but these comments do not show in Calypso and they are also not post comments, they are comments from Custom Post Types like WooCommerce product reviews.

#### Context / Source

See 3165-gh-jpop-issues for more context.

#### Possible Soluton
1. Update the count to only count comments from posts
2. Update the display to show all the comments we count, including those from WooCommerce?

**Comment by justinshreve** [comment]
There is a PR open for the first solution at #10786.
