### ISSUE TITLE
Editor: Gutenberg Stripping Paragraph Tags in Pages

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#28866]
Related to #21973, but opening as a new issue as requested here: https://github.com/Automattic/wp-calypso/issues/21973#issuecomment-441742484

Pick a Simple Site with markdown enabled under `/wp-admin/options-writing.php`

#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Click "my sites"
3. Select a site (I chose my .blog site)
4. Click "Add" next to site pages
5. Add a title
6. Write a sentence.
7. Hit return to add a new paragraph and write a new sentence.
8. Hit return to add a new paragraph and write a new sentence.
9. Click "Preview".
10. Optionally try publishing.

#### What I expected
The preview should show each sentence in a separate paragraph.

#### What happened instead
Each sentence flows together.

#### Browser / OS version
Chrome/OSX

#### Screenshot / Video
![editor view with paragraphs](http://cld.wthms.co/dntN5C+)

![preview with stripped paragraphs](http://cld.wthms.co/jEFEX1+)

#### Additional Notes
I couldn't figure out how to get the page to save with paragraph tags honored, but finally figured out a workaround. It seems if you select a paragraph block and then change the alignment, it will force the block to honor the paragraph tags, even if you toggle the alignment back to the default.

/cc @gwwar @youknowriad @mtias ping me if you want to test the post directly.

#dogfooding

**Comment by gwwar** [comment]
Thanks @rralian! I've updated the top issue summary. Folks should be able to reproduce with markdown enabled on a Simple Site, when attempting to create a page. We should also verify on CPTs 

@brandonpayton any ideas on what we need to update to add our markdown fix for all types?

**Comment by brandonpayton** [comment]
It's not yet clear why this is working for posts and not for pages.

Jetpack [merged a workaround](https://github.com/Automattic/jetpack/pull/10635) that disables markdown processing for posts with block content, and D21362 has been created to add this fix to WordPress.com. With this fix, both posts and pages appear to be working fine.

I'm going to spend some time trying to understand why posts are currently working but not pages. Based on my understanding, pages should be working now, but they are not.

**Comment by brandonpayton** [comment]
> D21362 has been created to add this fix to WordPress.com. With this fix, both posts and pages appear to be working fine.

This made it sound like the fix is already deployed, but that's not the case. It still needs review and testing.

**Comment by gwwar** [comment]
@brandonpayton just landed D21362-code, which I verified fixes behavior.

Thanks @rralian @brandonpayton! ✨

**Comment by brandonpayton** [comment]
The fix in D21362 is now deployed. Markdown processing is no longer applied to Gutenberg content.

We may improve this a bit by using hooks provided by server-side block parsing to selectively apply markdown processing to Classic blocks.

**Comment by brandonpayton** [comment]
:) I should have reloaded the tab. This still looked open to me. :) Thanks for closing @gwwar.
