### ISSUE TITLE
Gutenberg: Paragraphs broken on Pages

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#28865]
#### Steps to reproduce
1. Head to My Site > Pages > Add
2. Type up a post with a few paragraphs
3. Publish

#### What I expected
I'd expect paragraphs to render separately

#### What happened instead
They all merge together as a wall of text, with only line breaks instead of actual paragraph markup in the HTML.

#### Browser / OS version
Multiple

#### Screenshot / Video
https://cloudup.com/chkAf63Xd3p

#### Context / Source
Reported in the forums:
https://en.forums.wordpress.com/topic/paragraph-breaks-not-showing-on-pages/

Confirmed my test site; I also confirmed this does not happen on a .org installation.

**Comment by gwwar** [comment]
should be fixed by D21362-code
