### ISSUE TITLE
Related posts block: look into gnarly SVG

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28874]
https://github.com/Automattic/wp-calypso/blob/1a29e4773c961a2868830de23e851b891c1ce022/client/gutenberg/extensions/related-posts/editor.js#L22-L39

> this is a gnarly SVG for something relatively simple 

via https://github.com/Automattic/wp-calypso/pull/28752/files#r235400259

**Comment by tyxla** [comment]
Additionally, we might want to use only primitives here, just like we do for the other blocks.

**Comment by tyxla** [comment]
That should make it better: https://github.com/Automattic/wp-calypso/pull/29777
