### ISSUE TITLE
Change "home" page / destination on Store link in Calypso

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#28877]
From #comment-40102 on p58i-7nL-p2, and logged on Trello:

> when I clicked on Store from Calypso, I landed on the order page and felt confused (if I was a brand > new user). It would make more sense to end up on the Settings page, instead of a blank Order Page.

We can update this to redirect to the task list/setup for now. There is logic in the setup page that will redirect to the order page once you click "I'm done" -- which I think makes sense once you out of setup mode. This can change to a true dashboard later once we bundle `wc-admin`.

**Comment by timmyc** [comment]
Yeah this is very much a general broken flow for new Woo users that I don't think we can resolve entirely here. I agree that pointing the link at the setup task list is probably the best solution for now.
