### ISSUE TITLE
Simple Payments: Add site domain to email notification

### ISSUE THREAD

**Issue by spencerberry** [Automattic/wp-calypso#28889]
The simple payment emails that go out cannot be customized, and the recipient cannot be specified.

Furthermore, being able to filter and forward these email messages is difficult because the subject isn't unique per site or product.

A user suggested that we add the site domain or title to the email subject to help with this situation.

#2741601-hc

**Comment by hommealone** [comment]
If the message contains the domain name, we could easily filter and forward the messages. Including the title of the item might help some people, but I think that setting up the forwarder rules would be too cumbersome if you had a bunch of products. Without the domain name, forwarding is impossible, as messages from different websites would all get sent to any one chosen forwarding recipient.
