### ISSUE TITLE
Plans: Two primary buttons on the plans page during the Jetpack Connect flow

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#28882]
#### Steps to reproduce
1. On a new self-hosted site (use e.g. https://jurassic.ninja/create), install Jetpack, and connect it to WordPress.com
2. You'll be directed to the plans page, asking you to select a plan

#### What I expected

I'd expected there to be one primary button.

#### What happened instead

Two primary buttons.

#### Screenshot / Video

![image 1](https://user-images.githubusercontent.com/96308/49092802-143c9980-f263-11e8-985f-399d8c766766.png)

#### Context / Source

Discussed in Slack: p1543329196456700-slack-luna and p1543332038140800-slack-customer-marketing

Possibly introduced by https://github.com/Automattic/wp-calypso/commit/a19e1ce8c53eb645f3cc315da2ff9329b42797c2#diff-e4fe2faa07d72359c8ca689f4f183214R97, as found by @johnHackworth.

/cc @sararosso @adamziel

**Comment by adamziel** [comment]
Solved in https://github.com/Automattic/wp-calypso/pull/28937
