### ISSUE TITLE
Publicize: You can't customize when editing an already scheduled post in Gutenberg

### ISSUE THREAD

**Issue by Ipstenu** [Automattic/wp-calypso#28896]
#### Steps to reproduce the issue

1. Write a post in Gutenberg
2. Schedule it for a future date
3. You **are** prompted to edit Publicize
4. Go back and edit some more
5. Realize you want to tweak your Publicize message
6. Click Schedule (to save) and be shocked that you can't edit

#### What I expected
To be able to edit the text.

#### What happened instead

I was not prompted to edit publicize if the post was already scheduled.

NOTE: For NEW posts, this is fine. It's what happens when you schedule a post and then go back to edit. However. It's really only fine for people who don't use schedule and keep posts in drafts and never use schedule.

The edit publicize is literally the last thing some people do for their posts, because they don't 100% know what they want the message to be until they're done with the whole thing. Sometimes you want to hashtag something specific at the last minute.

Edit:

For a 'workaround' you can click 'Switch to Draft' and then 'Schedule' again to trigger it, but ... Honestly that's pretty tacky.

**Comment by jeherve** [comment]
Here is a potential solution: #28899

**Comment by tyxla** [comment]
I've just tested with the latest Jetpack bleeding edge + the latest version of Publicize for Gutenberg, and I was able to change the message for scheduled posts, using the new sidebar we introduced in #28899.

Seems like we could close this one, @jeherve?

@Ipstenu this will be included in the next version of Jetpack, but if you need it immediately, I'm happy to assist you with setting it up.

**Comment by jeherve** [comment]
> Seems like we could close this one

Yup, since #28899 I think we can close this.

**Comment by Ipstenu** [comment]
@tyxla I think we're okay waiting (since today's 5.0 day and tomorrow's WCUS etc etc ;) )
