### ISSUE TITLE
Signup: unnecessary requests are being made

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#289]
While taking a look at the current signup flow, there a three requests that always 403 because the user is not logged-in.

GET /me/sites
GET /me
GET /me/upgrades

Fetching the sites is particularly wasteful as there is polling.

cc @drewblaisdell

**Comment by stephanethomas** [comment]
I was able to reproduce this issue. To make things crystal clear, no request actually returns with a `403` HTTP status. However some of them return with a `200` HTTP status and the `403` application error code in the response:

```json
{
  "code": 403,
  "headers": [{
    "name": "Content-Type",
    "value": "application\/json"
  }],
  "body": {
    "error": "authorization_required",
    "message": "An active access token must be used to query information about the current user."
  }
}
```

**Comment by drewblaisdell** [comment]
@stephanethomas If I recall correctly, all responses to requests from Calypso have this data structure, because we include the `http_envelope` parameter with each request.
