### ISSUE TITLE
Chrome Redux Devtool before v2.16.2 crash Calypso

### ISSUE THREAD

**Issue by enesyteam** [Automattic/wp-calypso#28903]
![image](https://user-images.githubusercontent.com/16075067/49128331-777b0a00-f2fd-11e8-9d86-e7c350b7eda2.png)

**Comment by simison** [comment]
This seems to be an issue with Redux devtools. Disabling it should help.

**Comment by folletto** [comment]
I had the same issue here.
Chrome 70.0.3538.77 (macOS).

Noting for the future that:

1.  in Incognito the same account works.
2. Turning off the Redux extension — without uninstalling — resolves the issue.

**Comment by folletto** [comment]
Also I just checked and they have updated. I've now updated to v2.16.2 and it seems solved.
