### ISSUE TITLE
Contributors can't access their own published posts

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#28914]
As reported by a user and reproduced on a test site, it looks like there is a bug that prevents contributors of Atomic sites to access or edit their own posts once they've been published.

**EDIT 12/5/2018:** It looks like this is also affecting simple sites.

#### Steps to reproduce
1. In your administrator's account, set up an Atomic site and invite a user as a contributor from _My Site > People > Add_.
2. Once the invitation has been accepted, log into your contributor's account, create a post and submit it for review. The post appears as pending review in the list of draft posts.
3. Log back into your administrator's account and publish the contributor's post that is awaiting review.
4. Log back into your contributor's account, refresh the list of posts and you'll see your now published post is nowhere to be seen.

Note: Trying to add /my in the URL doesn't pull up the contributor’s own posts.

#### What I expected
Contributors are allowed to create but not publishe their own posts. Once their posts have been published by a user with a higher role, they are allowed to go back and edit it to resubmit it for review.

#### What happened instead
The contributor isn't able to see nor edit their own posts after they've been published.

#### Browser / OS version
Chrome

#### Screenshot / Video
![screen capture on 2018-11-28 at 15-28-38](https://user-images.githubusercontent.com/16645645/49158488-90e27d00-f322-11e8-87ac-c06ec02146ae.gif)

**Comment by cecilearkay** [comment]
It looks like this is also the case for simple sites after all (which I’m sure I'd checked). It was reported on the French forums by a contributor on site ID 71311522.
https://fr.forums.wordpress.com/topic/page-publie-et-brouillon-vide/

**Comment by alisterscott** [comment]
hi @cecilearkay 

This is working as designed.

As per https://en.support.wordpress.com/user-roles/#contributor

> A Contributor can create and edit only their own posts, but cannot publish them. When one of their posts is ready to be published, or has been revised, the Administrator needs to be notified personally by the Contributor to review it. Furthermore, once a Contributor’s post is approved and published by an Administrator, it can no longer be edited by the Contributor.

**Comment by cecilearkay** [comment]
@alisterscott Thanks for letting me know, I wasn't aware of this. What prompted me to file this as a bug though is because one of my users mentioned before, also as a contributor, they could still see their posts even after they were published. They mentioned it stopped about a month ago.
