### ISSUE TITLE
Plugins: Hide Plugin tab for VIP sites

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/wp-calypso#28928]
We currently show the `plugins` tab and a nudge to upgrade to Business for clients on WordPress.com VIP. This can cause some confusion. Since we already have a [method to verify if a site is on VIP](https://github.com/Automattic/wp-calypso/blob/master/client/state/selectors/is-vip-site.js) we should hide this message.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plugins/[VIP-SITE]
2. Note that the site has the VIP plan but is still being asked to upgrade to Business.

#### What I expected
To either not see the plugin tab or see a message that asked me to upload plugins via code.

#### Browser / OS version
Firefox 63.3 Pop_OS! 18.10

#### Screenshot / Video
![screenshot_2018-11-28-15-42-19](https://user-images.githubusercontent.com/150348/49195379-b92aa580-f33b-11e8-8d33-d741c6605b74.png)

#### Context / Source
Seeing the Business Upgrade nudge can be confusing for clients 

p9F6qB-1U6-p2

**Comment by westi** [comment]
cc @Automattic/atomic

**Comment by donpark** [comment]
This looks like something FixTheFlows can pickup.
