### ISSUE TITLE
Tiled Galleries: Remove external block view dependencies

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#28933]
Make `view.js` completely independent without externally enqueued dependencies. Current dependencies ([via](https://github.com/Automattic/jetpack/blob/ad962678561284debdcfb5d9fef1dfabff6aef44/modules/tiled-gallery/tiled-gallery.php#L37-L41)) are: 
- [x] `lodash`
- [x] `wp-i18n`
- [x] `wp-token-list`

### Lodash
Even if we just import small thing from `lodash`, the SDK externalizes it and we'd be required to enqueue all of `lodash`.

Another consideration is to change how SDK externalizes that library; perhaps only for `editor.js`?

### wp-i18n
Due to usage of layout styles, Tiled Galleries block view depends on i18n although it doesn't display the localized strings. Find a solution.

Via https://github.com/Automattic/wp-calypso/pull/27458/files#r227411941

### wp-token-list
Used to pick default style if none is found.

**Comment by simison** [comment]
Let's try to have 0 view dependencies,  💪

**Comment by simison** [comment]
Updated the issue to reflect removing all dependencies from `view.js`.

**Comment by sirreal** [comment]
Fix in https://github.com/Automattic/jetpack/pull/11326

I don't believe we ever had view dependencies when Tiled Gallery went into production blocks.
