### ISSUE TITLE
Domains: Remove mention of mapping cost from the UI

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#28936]
#### Steps to reproduce
1. Use a site with a paid plan, and the free domain credit unavailable (DWPO vs not does not matter)
2. Go to My Site ->Domains ->Add and select `Use a domain I own`
3. Choose the mapping option on the next page and follow the steps until checkout

#### What I expected
For the UI to indicate that mapping is free with the plan

#### What happened instead
Both at `https://wordpress.com/domains/add/use-your-domain` and `https://wordpress.com/domains/add/mapping` it indicates that domain mapping costs $13 a year. Once you reach the Checkout screen the amount changes to $0.

#### Screenshot / Video
![use_your_own_domain_e280b9_kokkiestrialtestsite_e28094_wordpress_com](https://user-images.githubusercontent.com/11873759/49225339-72e14f00-f3ec-11e8-9f18-9a2a2259a4f9.png)
![map_a_domain_e280b9_kokkiestrialtestsite_e28094_wordpress_com](https://user-images.githubusercontent.com/11873759/49225344-74ab1280-f3ec-11e8-9cdf-4568106e5a2d.png)

#### Context / Source

Noticed while testing the new domain mapping for free feature.

Context: p7DVsv-5IE-p2

cc @aidvu

**Comment by KokkieH** [comment]
@aidvu it seems the pricing still appears on `https://wordpress.com/domains/add/use-your-domain` for DWPO accounts that don't own a plan yet - I didn't check that as I didn't think it showed the pricing at all for DWPO accounts.

Must I create a new issue for that, or can we just reopen this one?

Reported in p8HJWS-nA-p2

**Comment by aidvu** [comment]
I see. That's a bug, and will check.
