### ISSUE TITLE
Tiled Galleries: Add image filters to the block

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/wp-calypso#28932]
A small neat feature that could be added to the Tiled Galleries is the ability to add a filter, similar to Instagram. 

* We could use [CSSgram](https://una.im/CSSgram/). (https://github.com/una/CSSgram)
* We should probably limit the amount of filters available (maybe 5-6) to avoid having too many options (need to check Instagram most used filters).
* We would need track its usage to see how impactful the filters are.

See: [Block Gallery](https://wordpress.org/plugins/block-gallery/) for example.

![screenshot 2018-11-29 at 11 38 53](https://user-images.githubusercontent.com/177929/49219496-67316080-f3cb-11e8-9232-8fdaaabcb2c9.png)

**Comment by sirreal** [comment]
Would this be per-image or applied to the whole gallery?

Any thoughts on which filters to include?

**Comment by thomasguillot** [comment]
As much as I think it would give us lots of flexibility if we could have a filter for each individual images, I have a hard time picturing where would the setting go ([maybe next to the close button?](https://cloudup.com/cgZb9jh8EVS)) so for simplicity, I'd say to the whole gallery.

As for the filters, here's a potential list:

* Black and White `filter: grayscale(100%);`
* Sepia `filter: sepia(100%);`
* Clarendon(*)
* Gingham(*)
* 1977(*)
* None (original)

(*) Based on [CSSgram](https://una.im/CSSgram/)

**Comment by sirreal** [comment]
@thomasguillot Can you provide SVGs for the icons used here?

**Comment by thomasguillot** [comment]
> @thomasguillot Can you provide SVGs for the icons used here?

Sure 😊

Photo filter main icon: https://material.io/tools/icons/static/icons/outline-photo_filter-24px.svg

### Option 1: Mix of material icons (+ custom)
Black & White: https://material.io/tools/icons/static/icons/outline-filter_b_and_w-24px.svg
Sepia: https://material.io/tools/icons/static/icons/outline-filter_vintage-24px.svg
Clarendon: https://material.io/tools/icons/static/icons/outline-tonality-24px.svg
Gingham: https://material.io/tools/icons/static/icons/outline-filter_drama-24px.svg
1977: https://cloudup.com/ctkmhztqqVN
No filter: https://cloudup.com/c-Tz2ChUO_m

### Option 2: Filter numbers (Material)
Alternatively we can use filter numbers, which for consistency might be better actually:
https://material.io/tools/icons/static/icons/outline-filter_1-24px.svg
https://material.io/tools/icons/static/icons/outline-filter_2-24px.svg
https://material.io/tools/icons/static/icons/outline-filter_3-24px.svg
https://material.io/tools/icons/static/icons/outline-filter_4-24px.svg
https://material.io/tools/icons/static/icons/outline-filter_5-24px.svg
https://material.io/tools/icons/static/icons/outline-filter_none-24px.svg

**Comment by scruffian** [comment]
This is done!
