### ISSUE TITLE
Stats: updates to Post & Pages Summary page

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#2894]
- [x] 1. Remove "No Views yet" from info panel - https://github.com/Automattic/wp-calypso/pull/2636

- [x] 2. Update panel messaging ("This panel gives you an overview of how many views your website gets") - https://github.com/Automattic/wp-calypso/pull/2893

- [x] 3. `% Change` in its own column doesn't make much sense, percentages should be moved right under the Average numbers (since it's also using the Average to calculate the percent change). - https://github.com/Automattic/wp-calypso/pull/3265

Quick mockup below:

![screenshot-2016-01-28-11 20 03](https://cloud.githubusercontent.com/assets/4924246/12658166/3400d334-c5bc-11e5-9f7d-3966ba744df9.png)

- [x] 4. An infinity symbol is being displayed for the following and it should be removed - https://github.com/Automattic/wp-calypso/pull/3265
a) the *very* first week post/page has been published when there's no previous week to compare to
b) partial weeks (meaning, when it's not showing a full week's worth of data)
c) if previous week to compare to is `0`

- [x] 5. `0.00%` change means there has been no change from the previous week, but doesn't communicate that very well. Should just say `No change`. - https://github.com/Automattic/wp-calypso/pull/3603

- [ ] 6. Find a solution for horizontal scrolling that shows up even on large screens:

We can rejigger the table to somehow omit the horizontal scrolling, however, this isn't a scalable solution especially if you have much larger numbers, horizontal scrolling will still somehow eventually appear. Will be creating a full-width try/branch for Stats to address this issue.

/cc @jblz @jonathansadowski @alternatekev @timmyc @designsimply @mattsherman

**Comment by jblz** [comment]
> percentages should be moved right under the Average numbers

Nice. This helps a lot.

**Comment by jblz** [comment]
I dragged some stuff around in your mockup to try out a more compact view of this module to quickly see what it'd look like. This is kind of what I was talking about on the call:

* before:
![recent-weeks-cropped](https://cloud.githubusercontent.com/assets/1587282/12661511/f824396a-c5e7-11e5-8331-d0b2ebeccae2.png)

* compact:
![recent-weeks-compacted](https://cloud.githubusercontent.com/assets/1587282/12661521/09ff427e-c5e8-11e5-9007-cb5dcb95bf57.png)

* only show month names where it's important for visual context
* remove some padding when numbers are < 3 or 4 digits wide
* separate the per-day metrics from the aggregations on the side to make it more instantly understandable

**Comment by jancavan** [comment]
@jblz This is great Jeff. Dropping the month names def saves space, too. To highlight the last 2 columns, another solution could also be changing the cell background color.

**Comment by jancavan** [comment]
All of the issues on here have been fixed except for one so I'm closing this issue out. I've created a new issue for the last item: https://github.com/Automattic/wp-calypso/issues/3775
