### ISSUE TITLE
Jetpack blocks: import beta blocks separately from stable blocks

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28942]
Currently, to load Jetpack blocks in Calypso, we define them in one list in [`client/gutenberg/extensions/presets/jetpack/editor.js`](https://github.com/Automattic/wp-calypso/blob/fb75f05668bc7487901b1c249ab25fe1e763f07e/client/gutenberg/extensions/presets/jetpack/editor.js) and import it in:

https://github.com/Automattic/wp-calypso/blob/fb75f05668bc7487901b1c249ab25fe1e763f07e/client/gutenberg/editor/init.js#L24-L31

We also define blocks separately in `index.json` and `index-beta.json` to be built for wpcom wp-admin and Jetpack via the SDK.

We could consolidate lists to json files so that we don't have two separate places. By using beta-list, it'll be easier to include in-development blocks there and not worry about separate feature flags for the blocks.

Perhaps something like this:

```js
import blocks from './index.json';
import betaBlocks from './index-beta.json';

blocks.forEach( block => {
    require( `gutenberg/extensions/${ block }/editor.js` );
} );

if ( isEnabled( 'gutenberg/block/jetpack-beta' ) ) {
    betaBlocks.forEach( block => {
        require( `gutenberg/extensions/${ block }/editor.js` );
    } );
}
```

Another example from Gutenberg core blocks: https://github.com/WordPress/gutenberg/blob/2a66db0fc99a9fb1ba99f61e59e6a0b2a4a5f9ef/packages/block-library/src/index.js

Convo p1543213792644900-slack-jetpack-gutenberg

**Comment by simison** [comment]
cc @dmsnell

**Comment by ockham** [comment]
> We could consolidate lists to json files so that we don't have two separate places. 

:+1: Yep, my original hope was pretty much what you're suggesting with your code sample.

**Comment by ockham** [comment]
Dynamic generation of `editor.js` from `index.json` (albeit containing beta blocks, too) in #29435.
