### ISSUE TITLE
Tiled gallery block: clarify disabled columns control

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#28943]
It's unclear why you could not adjust columns for some layouts: mosaic and columns. Only squares and circles support columns.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/87168/49230818-37994d00-f3f9-11e8-9bc0-16e76c6e1ad4.png">

Currently, we simply disable this option for other layouts, but we could perhaps hide it completely.

**Comment by sirreal** [comment]
Presumably circles and squares have predictable, consistent sizes that work well in columns.

The column logic is applied regardless of whether the layout "supports" it, which seems to be a bug.
