### ISSUE TITLE
Gutenberg: Publicize connections lack social icons in Calypso

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#28953]
Currently, when running the Publicize extension in Calypso, any connections lack the social icons, compared to when running in wp-admin:

**wp-admin:**
![](https://cldup.com/iuvlB0-GSZ.png)

**Calypso**
![](https://cldup.com/9yVY0jsLei.png)

**Comment by simison** [comment]
A temporary solution could be to import embed icons from Gutenberg:

https://github.com/WordPress/gutenberg/blob/5d3c7a139381e3a34469c88cf0aa0d66dd708fef/packages/block-library/src/embed/icons.js

<img width="573" alt="screenshot 2018-12-04 at 10 45 17" src="https://user-images.githubusercontent.com/87168/49429739-f1a20780-f7b1-11e8-89ab-b56d28c93c31.png">
<img width="538" alt="screenshot 2018-12-04 at 10 45 03" src="https://user-images.githubusercontent.com/87168/49429741-f1a20780-f7b1-11e8-90c0-3c32a5000227.png">

...tho they probably don't include all the icons for networks like Google+ (as it's going to shutdown in 2019).

**Comment by simison** [comment]
Just showing text label could be a very valid design choice, too:

> Twitter: Lorem ipsum

**Comment by tyxla** [comment]
Good call @simison, thanks!

I've suggested a temporary solution here: #29176 - it will make it less broken for the time being.

Anyway, let's keep this issue open even after merging the above solution, as it can be resolved when the icons are there for Calypso too.

**Comment by alisterscott** [comment]
I found this issue today.

<img width="283" alt="screen shot 2018-12-07 at 2 09 18 pm" src="https://user-images.githubusercontent.com/128826/49627347-13a5bf00-fa2a-11e8-845d-0bfe2f01b9da.png">

Perhaps if we aren't going to do icons we could use text groupings like the classic Calypso editor:

<img width="274" alt="screen shot 2018-12-07 at 2 02 40 pm" src="https://user-images.githubusercontent.com/128826/49627363-2b7d4300-fa2a-11e8-869c-f67a2453c418.png">

**Comment by tyxla** [comment]
This is an interesting suggestion. 

@mapk @MichaelArestad what do you think? Not having to figure different ways to solve problems with icon dependencies would make it a lot easier for the Publicize extension to be supported cross-platform.

My $0.02 are that ideally, we should be able to support the icons everywhere - basically, what Bernie said above - https://github.com/Automattic/wp-calypso/issues/28953#issuecomment-444013550. But I'm happy to reconsider if design folks have a different opinion.

**Comment by ockham** [comment]
TIL that (most of) these icons are available in Gutenberg https://github.com/Automattic/wp-calypso/issues/28953#issuecomment-444019714

That would sound like an easy enough option that would work across the board (tho it's indeed a shame that there's no Google+ icon there -- I'd suggest just filing a PR agains Gutenberg to add one, but now that WP 5.0 has been shipped, we'd need to add a version check :slightly_frowning_face: )

**Comment by tyxla** [comment]
> Does Calypso also group multiple connections under one label? I.e.:

Yes, it does. I think consistency is good reason to change to having groups instead of icons everywhere.

**Comment by MichaelArestad** [comment]
@tyxla could we have both? Could we have the Gberg Twitter icon next to the Twitter heading and the FB icon next to the FB heading, etc?

**Comment by tyxla** [comment]
@MichaelArestad yes we can, but the reason we don't have them right now is because our social icons repo that we use for wp-admin can't be embedded in Calypso, unless we add 100K to our bundles, which we don't want. A way around this is to update the social icons to be separately importable, but this would require some (likely non-trivial) changes to the social icons library and any code that uses it. That's why we prefer an icon-less approach, and if in Calypso we're currently grouping by a text-only name of the service, I'd prefer staying consistent and going without icons anywhere. What do you think?

**Comment by ockham** [comment]
I'll just point out that in the case of only one connection per social network (e.g. one Facebook, one Twitter) -- which to me seems like it would more widespread than multiple ones (te.g. wo Facebook, three Twitter), grouping connections under headings seems less intuitive than a social logo next to each connection.
In the latter case, IMO we would still need to group them (so all connections to one social medium are next to each other), but not necessarily with headings in between.

**Comment by MichaelArestad** [comment]
> @MichaelArestad yes we can, but the reason we don't have them right now is because our social icons repo that we use for wp-admin can't be embedded in Calypso, unless we add 100K to our bundles, which we don't want. A way around this is to update the social icons to be separately importable, but this would require some (likely non-trivial) changes to the social icons library and any code that uses it. That's why we prefer an icon-less approach, and if in Calypso we're currently grouping by a text-only name of the service, I'd prefer staying consistent and going without icons anywhere. What do you think?

What about using the ones included in Gutenberg and manually adding the G+ one for now?

**Comment by MichaelArestad** [comment]
> I'll just point out that in the case of only one connection per social network (e.g. one Facebook, one Twitter) -- which to me seems like it would more widespread than multiple ones (te.g. wo Facebook, three Twitter), grouping connections under headings seems less intuitive than a social logo next to each connection.

@ockham That's an excellent point. Perhaps we we should create a separate issue and design primarily for single accounts with a design enhancement for grouped accounts when used.

**Comment by simison** [comment]
>What about using the ones included in Gutenberg and manually adding the G+ one for now?

Even just adding _all_ those social SVGs directly in the block might not be that bad for now, just to get this look functional. 🙃

**Comment by tyxla** [comment]
Here's a PR that adds those icons directly - https://github.com/Automattic/wp-calypso/pull/29317

Thanks for the suggestion!
