### ISSUE TITLE
Gutenberg: Editor Preference default for new users is Gutenberg

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28965]
When an editor preference is not set for a new user (created after a certain date) on a Simple Site (excluding VIP), we should set the preference to `gutenberg`. Implementation details are left up to folks but likely this will be easiest to accomplish on the endpoint:

<img width="1001" alt="screen shot 2018-11-29 at 11 19 51 am" src="https://user-images.githubusercontent.com/1270189/49246063-dbb6d000-f3c8-11e8-9388-6be80791a298.png">

Folks will still be able to switch editor preferences freely, so no UI changes are necessary. 
 
Please, reach out to folks in our normal channels before landing. We'll need to verify if we're ready for this step.

**Comment by kwight** [comment]
Deployed; note that we also added a check to only make Gutenberg the default for new users _on the free plan_.
