### ISSUE TITLE
Gutenberg: Switch Over flows from Calypsoify to Gutenlypso for Simple Sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28972]
In this issue let's make sure that Simple Sites when they have an editor preference of `gutenberg` will navigate to the `/block-editor` Calypso section when editing a post.

Let's prepare this diff a bit ahead of time to make sure full flows make sense.

See p7jreA-1Y4-p2 for requirements before we can land this.

**Comment by vindl** [comment]
I believe this has been resolved in https://github.com/Automattic/wp-calypso/pull/29011.
