### ISSUE TITLE
Gutenberg: Reblog feature not included [3]

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#28973]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Click on sharing icon under any post in the Reader to reblog it
3. In the site choose, pick a Gutenberg-enabled site
4. New post will open (but is not pre-populated, as expected)

#### What I expected
To see the new post title and content area pre-populated with  post title, featured image, excerpt, and link back to original post I am reblogging.

#### What happened instead
Blank Gutenberg post.

#### Browser / OS version
Mac 10.13.6 Chrome  70.0.3538.77

This likely affects all browsers.

#### Screenshot / Video

[View screencast here](https://cloudup.com/cu9_9WxeR2H)

This video shows:
- Reblogging to a site using the classic editor in Calypso
- Reblogging to a "Calypsofied" Gutenberg editor in wp-admin

#### Context / Source
#manual-testing #user-report

**Comment by ChrissiePollock** [comment]
For November, I spent the month sharing other blogs I appreciate, and I ran into the same thing the user in #8418768-hc did. What I did personally (because I love Gutenberg) was share a post then grab the html for the reblog in the classic editor and paste it into an html block in Gutenberg. It’s a decent workaround that literally takes about 20 seconds when you are used to it.

**Comment by gugaalves** [comment]
Same issue mentioned by another user, #545989-hc

**Comment by msilbers** [comment]
issue reported in #8909463-hc and replicated by me on two test sites, both Simple and Atomic. Gutenberg is the blocker in both

**Comment by zdenys** [comment]
Another user reported this in #2514638-hc

**Comment by jesscga** [comment]
Reported as well in #9867080-hc

**Comment by sophiegyo** [comment]
Adding another report from someone who asked how reblogging worked, and I noticed it didn't work in Gutenberg, though it's fine in the Classic editor. Simple site tested. #2834874-hc

**Comment by sedocirp7** [comment]
Another user reported this in HC and we are following up with them in #1750990-ZD.

**Comment by sdixon194** [comment]
Re-opening the issue. Appears a fix was intended, but had a user run into this issue in 2121208-zen. 

I was also able to consistently reproduce as the problem was initially described in this thread.

**Comment by bsanevans** [comment]
I am reopening this issue as I can still reproduce the initial problem. Only this time, it can only be reproduced when Sharing to a Simple site. Sharing to Atomic seems to work fine.

This has resurfaced with user issue here: #2263633-zen

**Comment by gwwar** [comment]
I'll open a fresh one @bsanevans

**Comment by gwwar** [comment]
Created https://github.com/Automattic/wp-calypso/issues/35755

If steps are different or a lot of time has elapsed please favor creating new issues over reopening old ones.
