### ISSUE TITLE
WordPress.com account not connecting on login through Jetpack Support Doc 

### ISSUE THREAD

**Issue by StefMattana** [Automattic/wp-calypso#28983]
I have a Jetpack user on 1606692-zen who landed on our documentation support pages through `https://jetpack.com/contact-support/?rel=support`

Upon logging in with their WordPress.com account, the system sort of logs them in, but on the main page it still asks to login again. I tried replicating the issue a couple of times, and eventually everything went through okay. See quick video below: 
![contact support login bug](https://user-images.githubusercontent.com/11662998/49287783-a4165980-f496-11e8-8a84-c26d83d96530.gif)

I tried with my account as well on the same browser (Chrome) but no problems at all also on incognito. 
It doesn't look a big deal, though this might confuse the users :)
  
#### Context / Source
<!-- Optional: share your unique context to help us understand your perspective. You can add context tags such as: #Jetpack #account #flowsharing #confusion

We'd also love to know how you found the bug: #manual-testing,  #user-report if applicable.

**Comment by gemmagarner** [comment]
Another report: https://wordpress.org/support/topic/cannot-log-support-question-via-link-on-jetpack-dashboard/ — they were logged in to WordPress.com but the support form was still  asking them to login.

Chrome, Version 71.0.3578.98 (Official Build) (64-bit).

**Comment by gemmagarner** [comment]
Reported [on Twitter](https://twitter.com/h_batte/status/1093058256120020992).

**Comment by gemmagarner** [comment]
Issue reported when using Safari in: https://wordpress.org/support/topic/find-list-of-blog-subscriptions/
