### ISSUE TITLE
Tiled gallery block: Column support and layouts doesn't work

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#28987]
Spotted during #28986

Only circle and square layouts are supposed to support columns, but all of them do.

Currently, we only disable the column count control when using a layout that doesn't support columns.

**Comment by simison** [comment]
Is this duplicate of https://github.com/Automattic/wp-calypso/issues/28943 ?

**Comment by sirreal** [comment]
Duplicate of #28943
