### ISSUE TITLE
Contact Form Block: Only shown for logged-in users on WordPress.com

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#28997]
Originally reported at p58i-7qO-p2 #comment-40431:

> I had to revert this back to use the shortcode because the form would only appear for users logged into WordPress.com

#### Steps to reproduce
1. On a WP.com Simple Site, in wp-admin, start a new post and add a Map Block (also means setting an API token)
2. Publish that post
3. Visit that post while logged out (e.g. in an incognito window)

#### What I expected

The Contact Form to appear

#### What happened instead

The Contact Form didn't appear.

**Comment by lezama** [comment]
everything works when proxied 😄
