### ISSUE TITLE
Post-Checkout: Thank you page for Business should have "contact us" link

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#29]
After purchasing a Business plan, users land on a "thank you" page. That page currently has the link "send an email" — that should be changed to "contact us" and linked to wordpress.com/help/contact once that is launched.

Current "thank you" page:

![business-plan-confirmation-screen](https://cloud.githubusercontent.com/assets/8658164/11219229/3f633828-8d51-11e5-81e3-96953fc848c0.png)

**Comment by andreabadgley** [comment]
wordpress.com/help/contact has launched, so changing "email us" to "contact us" with a link to wordpress.com/help/contact can now be implemented.
