### ISSUE TITLE
Checkout: Redesign credit card form

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#290]
We should update the design of the credit card form in order to be more consistent with the rest of Calypso (e.g. by removing floating labels). This form is used on the `Secure Payment` page in the checkout as well as on the `Add Card Details` and `Edit Card Details` pages in the purchases management section:
##### Current Form

![screenshot](https://cloud.githubusercontent.com/assets/594356/11306530/b45de070-8fb2-11e5-842c-e231e1b368ff.png)
##### New Form

![screenshot](https://cloud.githubusercontent.com/assets/594356/11306548/e1661060-8fb2-11e5-8878-dfc58cc1abdc.png)

**Comment by iannuttall** [comment]
Closing out old issues and this isn't something we're going to get around to.

Please re-open if you think this needs higher priority.
