### ISSUE TITLE
Inspect where our state setup conflicts with redux dev tool.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#29021]
If starts from a clean state, i.e. clearing all the app data from debug tools, our state setup code could conflict with the redux dev tool and lead to the following error message:

![image](https://user-images.githubusercontent.com/1842898/49347981-90a8ff80-f6dd-11e8-9461-a925d5771d3c.png)

@lsl has discovered that the culprit is likely the way we setup the main flow variation:
```
const Flows = {
...
defaultFlowName: config.isEnabled( 'signup/onboarding-flow' )
        ? abtest( 'improvedOnboarding' )
        : 'main',
...
```

Creating this issue to keep it tracked.

**Comment by ramonjd** [comment]
Not sure if this is relevant, but I seem to remember encountering such an error. We have some [helper methods](https://github.com/Automattic/wp-calypso/tree/master/client/lib/redux-bridge) to deal with competing state updates from Flux and Redux.

If you can track down the offending redux action, using `reduxDispatch()` might help.

**Comment by lsl** [comment]
From my notes this is where things started breaking down:

```
        analytics.tracks.recordEvent( 'calypso_abtest_start', {
            abtest_name: this.experimentId,
            abtest_variation: variation,
        } );
```

Enabling debugging for `calypso:analytics:tracks` might help.

**Comment by southp** [comment]
I believe this has been resolved at some points.
