### ISSUE TITLE
New Authors can't see/edit posts

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#29028]
#### Steps to reproduce
1. Create a wpcom simple site, write a few posts/drafts/etc
2. Invite a user without an account to the site
3. Register the new user
4. User cannot see posts

#### What I expected
To see posts

#### What happened instead
Saw no posts

#### Browser / OS version
Any

#### Screenshot / Video
![peek 2018-12-03 17-15](https://user-images.githubusercontent.com/1883296/49386129-2fa21b80-f71f-11e8-8b80-2df32cca9aed.gif)

#### Context / Source

#user-report
1614496-zen

**Comment by lancewillett** [comment]
Hi @withinboredom Can you please share what role the user had that you invited? Author, contributor, etc?

I believe it's expected behavior for certain roles under Editor to only see their own posts.

**Comment by withinboredom** [comment]
The role was author. I believe the bug is in the counter (you can see the number of posts). Also, I feel like anyone should be able to see the published posts (they are published after all), but maybe not edit them?

**Comment by lancewillett** [comment]
I see; hmmm. For consistency I suggest we match the same behavior in core WordPress as well as what happens in WP Admin on WordPress.com or a Jetpack site.

As an Author role user on a WordPress.com Simple site, I should be able to view other users' posts in the post list.

I tested this flow just now with Safari / macOS on lance.blog.

1. Invited a test user, set their role to Author.
2. Logged in as that Author user in a new incognito window.
3. Viewed the posts lists in both Calypso and WP Admin and confirmed I can see the other users' posts as expected.

Screenshots:

1. This is Calypso posts list with the "Everyone" toggle on.
<img width="1396" alt="Screen Shot 2019-04-09 at 17 59 18" src="https://user-images.githubusercontent.com/66797/55844278-659e4480-5af1-11e9-9868-8b68dd7af331.png">

2. This is Calypso posts list with the "Me" toggle on (zero visible, count is correct).
<img width="1396" alt="Screen Shot 2019-04-09 at 17 59 25" src="https://user-images.githubusercontent.com/66797/55844280-659e4480-5af1-11e9-9f1c-c227dcbd4e47.png">

3. This is WP Admin posts list.
<img width="1396" alt="Screen Shot 2019-04-09 at 17 59 21" src="https://user-images.githubusercontent.com/66797/55844279-659e4480-5af1-11e9-9d73-70a7b123c29e.png">
