### ISSUE TITLE
Gutenberg: Revisions button not loading revisions

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#29048]
#### Steps to reproduce
1. Starting at URL: Add Post
2. Add content to post
3. Click Save
4. Add content to post
5. Click Save
6. Click on "Revisions"
7.  Page links to blank wp-admin revisions page

#### What I expected
Clicking on revisions would bring me to the wp-com revisions page populated with existing revisions.

#### What happened instead
Clicking on revisions brought me to a blank wp-com revisions screen.  

#### Browser / OS version
Chrome 70.0.3538.110, macOS Mojave 10.14

#### Screenshot / Video
https://d.pr/free/i/pjLYtl

#### Context / Source

This was brought to my attention by a user that was using Gutenberg and wanted to accidentally deleted content and wanted to go back and find said content.  I advised to switch back to the classic view and they were able to access their history.  

Perhaps duplicate of this issue, but in this case the next page is loading, just no data is being displayed.  
https://github.com/Automattic/wp-calypso/issues/27747
merged into 
https://github.com/Automattic/wp-calypso/pull/28296

-->

**Comment by mlaetitia** [comment]
More reports here:
hc-7794848
hc-4897833

workaround: switching to classic editor

**Comment by gugaalves** [comment]
Same issue at hc-8647420 . Not working via Calypso, working via wp-admin

**Comment by rossanafmenezes** [comment]
Another report here: hc-7441667

**Comment by gwwar** [comment]
Please reopen if folks are still having trouble. I wasn't able to reproduce in wp-admin or Calypso
