### ISSUE TITLE
Map Block: New post email doesn't show map, only list of markers

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#29054]
Originally reported at p58i-7sR-p2 #comment-40516, while testing on WP.com

Email containing post containing new Map block doesn’t show map, it has Google links to the map markers instead.

![image](https://user-images.githubusercontent.com/96308/49442147-e1495700-f7c8-11e8-9d56-b434f338a3f2.png)

/cc @jeffersonrabb @enejb @sirreal

**Comment by simison** [comment]
This is expected behavior; the link is a fallback shown in emails and RSS feeds.

**Comment by ockham** [comment]
Thanks @simison. Yeah, I wasn't entirely sure -- I'd seen this behavior in the browser before (probably with my adblocker on).

I'm not sure how this compares with whatever map feature the pre-Gutenberg Classic Editor on WP.com has which would be my benchmark. I don't seem to have any of my accounts set up to email-follow another, so I can't test right now.

Anyway, closing as wontfix -- we can re-open if the new emails turn out to be a regression over the old ones.

/cc @alisterscott
