### ISSUE TITLE
Audio Block: Error Uploading Accepted File Type

### ISSUE THREAD

**Issue by brookewp** [Automattic/wp-calypso#29086]
#### Steps to reproduce
1. Create new page or post
2. Add Audio Block
3. Upload m4a file
4. Receive error "file-name.m4a: Sorry, this file type is not permitted for security reasons."

#### What I expected

m4a is an accepted file type, so I expected to be able to upload it. It's possible still to upload the file to the media library and then choose the file from the media library within the audio block.

#### What happened instead

I received error warning "file-name.m4a: Sorry, this file type is not permitted for security reasons.". 

#### Screenshot / Video

<img width="641" alt="screen shot 2018-12-04 at 2 16 14 pm" src="https://user-images.githubusercontent.com/35543432/49476579-3f793880-f7cf-11e8-8324-3150a3ad39b1.png">

Discovered from user in chat #8569345

**Comment by arunsathiya** [comment]
@brookewp I don't think this is a Gutenberg-specific issue, but `m4a` uploads are failing on core WordPress which has been reported here https://core.trac.wordpress.org/ticket/45615#comment:60

I assume the error you have indicated happens on classic/Calypso editor as well, right?

**Comment by brookewp** [comment]
@arunsathiya - I've tested in classic/calypso without error. It opens happens in gutenberg. Here's an example of classic: http://cld.wthms.co/0Xq8vh

**Comment by brookewp** [comment]
Just tested on .com in block editor and it worked without error, I'll close this now.
