### ISSUE TITLE
Contact Form Block: Date and Phone # Fields not Validated

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#29085]
Missing date validation reported by @Stojdza at p58i-7sR-p2 #comment-40554 when testing on WP.com

> I added Date Picker and set it as a required field. As a new user in an incognito window, I added some random string as a date. The form was successfully submitted. I expected some date validation here.

Missing phone number validation reported by @reginabally at p58i-7sR-p2 #comment-40608 when testing on WP.com

> I typed non-numeric characters into the Phone field but it’s not validated.

---

Possibly a duplicate of #28561? /cc @enejb @georgestephanis

**Comment by scruffian** [comment]
Closing in favour of https://github.com/Automattic/jetpack/issues/11867
