### ISSUE TITLE
Stats: IE Bar Graph Missing Views Column

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#29088]
#### Steps to reproduce
1. Navigate to the Stats page for a blog in Internet Explorer 11 (I used Browserstack)

#### What I expected
The Views columns should display along with the Visitors column

#### What happened instead
You will see the Views (light blue) columns missing, while the Visitors (dark blue) columns remain.

#### Browser / OS version
Internet Explorer 11 

#### Screenshot / Video
![ie no column](https://user-images.githubusercontent.com/41035049/49477134-cb3f9480-f7d0-11e8-876a-7bbfcdc77598.png)

#### Context / Source
#user-report Reported by user in ticket 1612580-z

-->

**Comment by nathaow** [comment]
User in #1705922-zen is having the same issue. Only in this case, none of the bars are showing for them (see screenshot.)

![ie11-stats-bug](https://user-images.githubusercontent.com/46284490/51073344-a2cc7500-166f-11e9-9804-ed89fc5e0f69.jpg)

**Comment by SiobhyB** [comment]
Another report in 1681680-zen. None of the bars are showing up for this user, either:

![internet explorer](https://user-images.githubusercontent.com/2998162/51123552-3d65b900-1814-11e9-8839-b90633046bca.JPG)

**Comment by torres126** [comment]
Report here and in most threads linked in #30148.

https://en.forums.wordpress.com/topic/dashboard-and-statistics/
