### ISSUE TITLE
Plans/Domains: Add a feature flag that disables payments in Calypso

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#291]
We should have one flag that disables all paths to /checkout in Calypso. We could replace these links with information about where to get upgrades.

This will make it possible to list the desktop app in the app store, and still show some information about upgrades.

**Comment by gziolo** [comment]
List of features to cover with flags:

* [x] Domains search
* [x] Renew button
* [x] Credit card list and edit
* [ ] Plans upgrade
* [ ] Add Privacy Protection
* [ ] Add Google Apps
* [ ] Add Theme

**Comment by gziolo** [comment]
As part of this issue, we should think how we can consolidate the following flags:
* `manage/plans`
* `me/billing-history`
* `upgrades/domain-search`
* `upgrades/checkout`

Closing #2451 it favor of this issue.
