### ISSUE TITLE
Notifications: Broken with an RTL interface

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#2913]
I'm not sure why this is happening. I have only tested in development...

<img width="1434" alt="screen shot 2016-01-29 at 11 07 59" src="https://cloud.githubusercontent.com/assets/275961/12674071/d8999d10-c678-11e5-9cf7-aef60dcb011e.png">

**Comment by yoavf** [comment]
This doesn't look like "full" rtl, rather just Hebrew but in LTR. Works ok for me if direction is set to RTL in config.

**Comment by scruffian** [comment]
Ok, does that mean we need to force a page reload when a use switches language?

**Comment by yoavf** [comment]
To test RTL in development, you actually need to change the config value and restart the server :(

**Comment by scruffian** [comment]
Ok, but in production it does a page reload? In that case we can close this...
