### ISSUE TITLE
Block Editor: Edited post titles display on other posts

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#29153]
Changing the title of a post in the block editor causes that new post title to carry over into other posts when they are opened in the editor; it fails to update the title of the post in the post list.

This problem appears to be related to unsaved changes to a post as after publishing/updating the app state appears to reset.

![messed-up-post-titles mov](https://user-images.githubusercontent.com/5431237/49533419-27132780-f87c-11e8-8850-68a2a1910dc7.gif)

**Comment by vindl** [comment]
Just adding some details from our Call for Testing:

> The same thing as that Github issue happens with setting a new featured image, excerpt, tag, category, discussion settings, etc. I haven’t done this but it seems the Github issue should actually apply to all the Document options in the sidebar.

This is kind of expected given that it's stemming from the same general issue and our proposed fix should handle this too. I wanted to add it just in case so we don't forget to test this before we land it.
