### ISSUE TITLE
Gutenberg: Paragraph tags missing/removed from editor/live site

### ISSUE THREAD

**Issue by brookewp** [Automattic/wp-calypso#29169]
#### Steps to reproduce
1. Create a new page or post on site https://josthering.gracefulhaste.org/.
2. Type in text. 
3. See paragraph tags aren't being added. 
4. Also, if you inspect the site, paragraph tags seem to be stripped away everywhere 

#### What I expected

Paragraph tags should be added automatically. 

#### Screenshot

<img width="1463" alt="screen shot 2018-12-05 at 5 23 18 pm" src="https://user-images.githubusercontent.com/35543432/49554861-7ffdb280-f8b2-11e8-810f-38d4a215eb75.png">

#### Additional Info

Seems to be related to: https://github.com/Automattic/wp-calypso/issues/21973

**Comment by thebud15** [comment]
Let's update user at #1623576-zen when we get an update, as it's been over a month. I've let the user know that we don't have a timeline on a solution.

**Comment by arunsathiya** [comment]
I noticed that the user is using a third-party called `primcus2`. It's not offered by WordPress.com https://wordpress.com/theme/primcus2

I can also see that this is still an issue.

<img width="1400" alt="Screenshot 2019-04-05 at 13 37 37" src="https://user-images.githubusercontent.com/18581859/55613321-0f0ad080-57a8-11e9-9b79-ff809c614378.png">

This post can be seen at https://josthering.gracefulhaste.org/aktuelles/

Before suggesting that we try a WordPress.com theme, could this be a theme-level dependency? I am adding it to `Calypso Gutenberg integration` project for devs' opinion on this situation. I am also updating the priority to reflect that this is an isolated incident and not affecting all users.

**Comment by gwwar** [comment]
If we can confirm that the theme is causing the issue, we can report upstream to the theme developers.

**Comment by rosepajaroja** [comment]
This seems to be fixed now. No change on the theme, but on the primary domain name. 

Checked the same page @arunsathiya mentioned in the comment above - https://josthering.de/aktuelles/

![Alt text](https://d.pr/i/GFGcmK/bcCHRLCht5+)
