### ISSUE TITLE
Gutenberg: HTML block's preview hidden

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#29174]
When creating a HTML block and previewing its contents in the editor, iframe stays hidden:

<img width="630" alt="screenshot 2018-12-06 at 12 28 31" src="https://user-images.githubusercontent.com/87168/49578472-82afe480-f952-11e8-9516-873ee08b7df1.png">

<img width="625" alt="screenshot 2018-12-06 at 12 28 36" src="https://user-images.githubusercontent.com/87168/49578471-82afe480-f952-11e8-8a24-590cd35550b1.png">

When saving the post, result shows up as expected at the site.

- Simple site
- Firefox
- Tested with themes "Twenty Fourteen " and "Independent Publisher 2"

**Comment by wynwin** [comment]
User reported this in chat 10626105-hc 
Follow up ticket sent via 1821927-zen

**Comment by mmtr** [comment]
No longer reproducible after removing Gutenberg on Calypso in favor of #31196.
