### ISSUE TITLE
Safari sometimes results in unresponsive calypso

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#29179]
I'm not 100% sure of the cause of this. This is just a theory, but filing it in case others report it.

#### Steps to reproduce
- Have Safari long enough that ITP is trained
- Visit wpcom long enough to set up a site
- Unable to logout and other api based features stop working

#### What I expected
calypso to "just work"

#### What happened instead
calypso doesn't work

#### Browser / OS version
Safari 12

#### Context / Source

See 1622344-zen

**Comment by sdixon194** [comment]
Bumping thread, as ticket keeps bobbing back up in the queue for over a month now without the user inquiring about an update. Going to just submit as pending for now, notify user if anything changes.
