### ISSUE TITLE
Publicize: New window to connect a new account counter-intuitive for Calypso

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#29175]
Currently, the "Connect a new account" button for Publicize's extension for Gutenberg opens a new window with a page, where the user can manage their services. For Calypso, it opens Calypso's sharing settings page. 

As @mtias mentioned via Slack yesterday, in Calypso it feels off to open a new window with anotehr page from Calypso. My opinion is that if we move the user away from the post editing experience, this is even more confusing. 

We're already planning to create a new modal in #28387, but in the meantime, we could likely do something to improve the experience for Calypso.

@mtias @mapk @MichaelArestad other than creating the new modal, do you have any ideas of how we could improve this in the short term?

**Comment by mtias** [comment]
AT the very least should use the "external link" component.

**Comment by tyxla** [comment]
I'm happy to update it to use the external link component. 

@mapk @MichaelArestad does it make sense for you? We'd essentially change:

![](https://cldup.com/N70eUXbuh8.png)

to:

![](https://cldup.com/Vf-CPkL1SA.png)

Let me know if you're good with that change for the time being. Then, when we build the new modal, we could revert this change, or make it a button or something.

**Comment by tyxla** [comment]
#29228 to change it to use `<ExternalLink />`. Looking forward to building the new modal, it will be so much better experience, but in the meantime, this will make it a little more intuitive.
