### ISSUE TITLE
Gutenberg: can view plugins in WP Admin even though the site is simple

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#29184]
Related: #29183 

#### Steps to reproduce
0. First, follow the steps linked in the issue above
1. Starting at URL:https://[site].wordpress.com/wp-admin/edit.php?post_type=post&ids=106
2. Click on "manage plugins" in the sidebar
3. It should take you to `https://[site].wordpress.com/wp-admin/plugins.php`
4. You'll then see a bunch of plugins that shouldn't be viewable 

Seems like a big user access problem since it's just a simple site, and normally you shouldn't have access to the plugins list. I was able to turn on the o2 plugin and it worked. Maybe I have special access?

I am pretty sure this is a simple site and not an atomic site

**Update: it's probably a proxy thing**

cc @gwwar 

#### Screenshot / Video

![screen shot 2018-12-06 at 10 25 28 am](https://user-images.githubusercontent.com/618551/49597615-6dcb5500-f942-11e8-86a6-5e23ef8e220e.png)

**Comment by drw158** [comment]
Unfortunately, I can't test without a proxy because Chrome doesn't work at all unless I have it on.

**Comment by arunsathiya** [comment]
I tried to reproduce this on a proxied environment and it's not the same case. I am redirected to a Calypsoified look, yes, but I do not see `Manage plugins` or any references to plugins. 

<img width="933" alt="Screenshot 2019-04-05 at 13 20 42" src="https://user-images.githubusercontent.com/18581859/55612554-18933900-57a6-11e9-8c0e-81be977333fb.png">

Are you still able to reproduce this, @drw158?

**Comment by gwwar** [comment]
If folks can manage plugins, it's not a Simple Site.

**Comment by gwwar** [comment]
@drw158 did you need us to look at this, or can this be closed out?

**Comment by gwwar** [comment]
Sorry, I didn't notice the Dec opening date. Related Calypsoify styling for simple sites was fixed by @kwight  in D24873-code.
