### ISSUE TITLE
Gutenberg: redirects to wp-admin post list after trash

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#29183]
#### Steps to reproduce
1. make sure you have Gutenberg enabled on a simple site (I have not tested on atomic)
2. https://wordpress.com/posts/[site].wordpress.com
3. Click the Write button in the masterbar 
4. make sure the url is `https://[site].wordpress.com/wp-admin/post-new.php`
5. Write some content, save draft or wait for auto save
6. Click move to trash
7. It should kick you to a broken view, with plugins in the sidebar, and a WP Admin post list on the right

#### What I expected

To be redirected to the Calypso post list

#### Browser / OS version

MacOS, Chrome lastest

#### Screenshot / Video
![screen shot 2018-12-06 at 10 22 03 am](https://user-images.githubusercontent.com/618551/49596823-d0235600-f940-11e8-8f81-81d2c7cb644e.png)

cc @gwwar

**Comment by arunsathiya** [comment]
What seems to happen here is that when you are using the Gutenberg editor on wp-admin side of things, and when you trash the post, you are redirected to the post list with Calypsoified interface. I think this is expected, unless the `?calypsoify=0` flag is passed. 

When I start at https://wordpress.com/block-editor/post though, write a post and trash it, I am redirected back to the Calypso post list, as expected. 

In any case, I am going to add this to `Calypso Gutenberg integration` project.

**Comment by gwwar** [comment]
This should be resolved with new Gutenberg integration. See https://github.com/Automattic/wp-calypso/pull/30701 and https://github.com/Automattic/wp-calypso/pull/31704
