### ISSUE TITLE
Form blocks: use Gutenberg core block for submit buttons

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#29187]
I think it would be good for both the Form block and the Subscription form block to use the core Gutenberg Button block for the submit buttons. I'm hoping that if we do this we will see the following benefits:

* Direct editing of the button
* A closer preview to what the theme outputs
* Ability for the theme to programmatically customize the button's visual settings

In the following screenshot, you can see the current state of the Subscription form followed by a core Button block. I would like the "Subscribe" button to use the Button block instead.

![image](https://user-images.githubusercontent.com/1123119/49598276-81bf8880-f93b-11e8-9181-d1ac4418f39d.png)

Of course, this may not be possible from a technical perspective. @aldavigdis I know you looked into this. Could you add a bit of what you found. @mtias what do you think?

**Comment by aldavigdis** [comment]
I prefer we use the `Button` component as we are using it now, as I'm pretty sure (without having actually checked) that the button block is simply a wrapper for a large call-to-action `<a>` element UX-wise and it would be inappropriate to mix those together.

**Comment by aldavigdis** [comment]
Honestly, I think the Button block in Gutenberg should have been called HeroButton instead. :)

I am going to see if we can meet in the middle here. I will see if I can add similar sidebar options to the subscription block as come with the Button block in order to customize things like the `Button` component, which is much more flexible to work with than the block with the same name.

**Comment by MichaelArestad** [comment]
Just to recap a convo in Slack:
* Alda is trying to get the InspectorControls from the Button block into its own component for reuse.
* It would be ideal for the text of the submit button to be directly editable similar to the Button block
* The Button block name is confusing for development since it does not output a button element. However, the Button compnent can output either a button or anchor link depending on needs. However, the Button block's name makes perfect sense for the end user.
