### ISSUE TITLE
Jetpack blocks: remove option to edit HTML if doing that is not useful

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#29193]
Right now, as @mtias pointed out, if you edit the Markdown block as HTML, it's super easy to break the block. We can remove that option in the block definition like this:

```
supports: {
    html: false,
}
```

Are there other blocks that would benefit from the removal of this option?

**Comment by tyxla** [comment]
Good call, folks! #29232 addresses this for Markdown.

**Comment by tyxla** [comment]
Contact Form and Simple Payments would benefit from this, but they already have it, so they're good.

Related Posts would benefit from this, at least with its current state. I'm filing a PR.

**Comment by tyxla** [comment]
PR for disabling it for Related Posts: #29233

**Comment by tyxla** [comment]
@jeffersonrabb maybe it makes sense to disable it for Map block as well?

**Comment by tyxla** [comment]
@simison @sirreal how do you feel about disabling it for Tiled Gallery? One could easily try to add another class and break the block.

**Comment by tyxla** [comment]
PR for doing it for tiled gallery: #29234

**Comment by simison** [comment]
>@simison @sirreal how do you feel about disabling it for Tiled Gallery? One could easily try to add another class and break the block.

Good idea 👍

**Comment by tyxla** [comment]
PR for the Map block, cc @jeffersonrabb: https://github.com/Automattic/wp-calypso/pull/29235
