### ISSUE TITLE
Reader: Long site titles overflow Follow button

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#2919]
![screenshot](https://cldup.com/6cf_CQiAAM.png)

As seen at https://wordpress.com/read/post/feed/25320833/916021218

**Comment by bluefuton** [comment]
Also happening with the compact follow button on mobile:

<img width="432" alt="screen shot 2016-02-01 at 11 00 11" src="https://cloud.githubusercontent.com/assets/17325/12705271/08b9ce3c-c8d3-11e5-8592-960837e651c4.png">
