### ISSUE TITLE
Gutenberg: Calypsoify on Atomic sites with Classic plugin

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29207]
Calypsoify is not always detecting the presence of Classic plugin on Atomic site. In addition to that there are multiple option that this plugin offers, so we can infer the correct setting just based on it's activation status:

<img width="694" alt="screen shot 2018-12-06 at 3 09 21 pm" src="https://user-images.githubusercontent.com/1182160/49618900-8e36f600-f9ba-11e8-9df1-611e5f8075b9.png">

Relevant code: https://github.com/Automattic/wp-calypso/blob/33cfac1c5c5d3a7bd0922af5013a4552c2dd77f5/client/state/selectors/is-calypsoify-gutenberg-enabled.js#L23

**Comment by gwwar** [comment]
@vindl  Is this one describing the opt-in sync issues with atomic?

**Comment by kwight** [comment]
I think he's referring to the fact that even if the plugin is active, its settings can indicate any number of realities: classic editor is set, or not, with users able to set their own, or not. It's another reason in the back of my mind of why a full audit of Calypsoify flows is needed sooner than later 🙃

**Comment by kwight** [comment]
Note that the `isCalypsoifyGutenbergEnabled` selector will be going away with the [switch to JP iframing](https://github.com/Automattic/wp-calypso/pull/30788#pullrequestreview-219228237), and better integration with WordPress.com opt-in would both affect this further; we'll keep this in mind while investigating the latter.

**Comment by gwwar** [comment]
@kwight that's part of finalizing Jetpack flows in p3fqKv-6Hh-p2. Would we like to keep this as a placeholder (please update the summary) or close out? ATM I don't think this one is actionable.

**Comment by kwight** [comment]
Agreed, closing 👍

**Comment by vindl** [comment]
> @vindl Is this one describing the opt-in sync issues with atomic?

What Kirk wrote. If Classic plugin is activated we will display Classic editor in Calypso (prevent Calypsoify flows), regardless of plugin's actual settings - it could be set to Block Editor for all users on the site. If I recall correctly, these options were not synced and accessible in Calypso.

**Comment by kwight** [comment]
> If I recall correctly, these options were not synced and accessible in Calypso.

Correct. We install the Classic Editor plugin (or not) according to the owner's opt-in setting at the time of transfer, and then... they're on their own, with totally different settings in a totally different place (and no heads-up about it from us).

As part of p3fqKv-6Hh-p2 phase 2, we'll be looking at options to bridge that gap; I'm looking at extending the Classic Editor plugin to allow a third option of "Use WordPress.com settings" (set by default), which should give business users the best of both worlds (and no need for action on their part if they're happy). No solid decision or timeline yet, though.
