### ISSUE TITLE
Gutenberg: update Calypsoify in Jetpack

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29206]
Our Calypsoify version in Jetpack is out of date now and doesn't have `Switch to Classic` option, which makes switching back from Atomic sites harder. Let's try to add this before next Jetpack code Freeze.

Note that if it makes sense we can also remove extra code in wpcom for simple sites.

**Comment by gwwar** [comment]
Note that I'm bumping priority to make sure this gets done, since we missed the last Jan 3 window. - @gwwar

**Comment by gwwar** [comment]
@kwight I'm closing this out for now until we have a final strategy in mind.
