### ISSUE TITLE
No way to upgrade to eCommerce plan on Plans page?

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#29209]
#### Steps to reproduce

This happened for a site that was already on a premium plan (wpcomnewdomaintest.blog)

1. Starting at URL: https://wordpress.com/plans/mydomain.com
2. Make sure `Online Stores and Business Sites` is selected
3. No way to select Upgrade for eCommerce Plan

#### What I expected

Ability to upgrade to eCommerce plan

#### What happened instead

No upgrade button

#### Browser / OS version

Chrome, MacOS Mojave

#### Screenshot / Video

<img width="1748" alt="site-on-premium-cant-upgrade-to-ecommerce" src="https://user-images.githubusercontent.com/51896/49619304-e0ebc000-f970-11e8-89ad-67c117fb37d7.png">

**Comment by kriskarkoski** [comment]
Based on some testing I think this might only be live for Automatticians (but isn't behind a proxied check) and is likely intentionally disabled for existing sites as the plan is for new sites only at the moment. I will ask for further clarification.

**Comment by gravityrail** [comment]
Thank you! I wasn't aware that this feature isn't deployed for regular users yet.

**Comment by jhnstn** [comment]
This is intentionally disabled. We are still working on being able to transfer Simple sites to eCommerce sites.

**Comment by rwaynick** [comment]
We were testing this flow in our team chat today. Should we hide the eCommerce plan for new users that don't select it initially so that they don't ask about how to upgrade when they contact support?

cc/ @sararosso @jhnstn

**Comment by torres126** [comment]
Just noting here that there has been some confusion about this in the support forums. I think the exact threads have been deleted, but I do recall one which mentioned that coming in through the path https://wordpress.com/start/store-woo (which is the path linked on the official WooCommerce) prompts purchasing the eCommerce Plan by name...but doesn't offer it.

![screenshot_20190108-195920](https://user-images.githubusercontent.com/43215253/50855503-eed19e00-137f-11e9-962d-7093dd92301e.jpg)

There's also no support documentation on it, but the https://wordpress.com/ecommerce/ page does exist, yet the nudges at the bottom there don't offer the eCommerce Plan either.

**Comment by rwaynick** [comment]
We do have [this support page](https://en.support.wordpress.com/ecommerce-plan/) for users of the eCommerce plan @torres126. I believe we are tracking the other issue you mentioned internally. Thanks.

**Comment by torres126** [comment]
Thanks, I wasn't aware of that support doc! :)

**Comment by scosgro** [comment]
Had this happen to someone in #11479731-hc today, followed up in #1900850-zd

They wanted to upgrade from Business to eCommerce. While in SSP, I was able to replicate the original posts screenshot on their end, where it shows eCommerce, but no way to upgrade.

**Comment by timmyc** [comment]
The option to upgrade from Business -> eComm is now available:

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/22080/76358497-c4a6a380-62d6-11ea-8cd2-965b4ea8dccc.png">
