### ISSUE TITLE
Gutenberg in Calypso: offline notices overlap with each other

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29210]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post/
2. Create a new post and save but don't publish
3. Use developer tools to set tab to offline no network connectivity

#### What I expected

Offline notices as per Calypso

#### What happened instead

Offline notices overlap and look a bit messy - do we need both Gutenberg and Calypso notices?

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

<img width="1210" alt="screen shot 2018-12-07 at 10 43 15 am" src="https://user-images.githubusercontent.com/128826/49620581-3d9cb880-fa0d-11e8-98b8-1740a44dae71.png">

<img width="1212" alt="screen shot 2018-12-07 at 10 43 35 am" src="https://user-images.githubusercontent.com/128826/49620587-455c5d00-fa0d-11e8-9568-439492abd833.png">

#### Context / Source
 #dogfooding

**Comment by obenland** [comment]
![image](https://user-images.githubusercontent.com/1398304/53917196-d2b54a80-4018-11e9-9f40-33235f2d4d95.png)

This should work better now with Gutenframe (p3fqKv-6Hh-p2).
