### ISSUE TITLE
Settings: Add support for Saraiki locale

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#29219]
1. Starting at URL: https://wordpress.com/settings/general/ and https://wordpress.com/me/account/

Request to add Saraiki as a language option.

The translation project for this language exists at https://translate.wordpress.com/projects/wpcom/skr/default/

#### Context / Source

Via the [support forums](https://en.forums.wordpress.com/topic/saraiki-in-language-setting/)

Also see sxLjZ-saraiki-p2

**Comment by akirk** [comment]
Our main measure for adding a new language to our selector are high (90%+) translation percentages for the first five views visible here: https://translate.wordpress.com/views/projects/wpcom/skr/default

They are currently well below our limits:
<img width="1338" alt="screenshot 2018-12-07 at 11 41 05" src="https://user-images.githubusercontent.com/203408/49643066-06320a00-fa15-11e8-9a6b-fb78d9a8ad6b.png">
