### ISSUE TITLE
Gutenberg Publicize Social Sharing: Broken connection status not displayed

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29211]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post/ with an account with a broken social media connection
2. Click Jetpack icon and expand Share This Post

#### What I expected

As per Calypso Editor - the broken status of the connection should display:

<img width="274" alt="calypso broken" src="https://user-images.githubusercontent.com/128826/49627650-b4e14500-fa2b-11e8-83eb-620ae488e7ad.png">

#### What happened instead

Broken connections are displayed the same as other connections

<img width="283" alt="screen shot 2018-12-07 at 2 09 18 pm" src="https://user-images.githubusercontent.com/128826/49627658-c591bb00-fa2b-11e8-8004-f569e8a08545.png">

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

See above

#### Context / Source

This issue also shows #28953

**Comment by vindl** [comment]
Removing this from Calypso Gutenberg Integration project for the same reasons stated in https://github.com/Automattic/wp-calypso/issues/29212#issuecomment-445750443.

**Comment by tyxla** [comment]
It seems we're not handling connection failures properly in our Publicize extension. 

I've started fixing this in #29289, but in the meantime: @alisterscott could you tell me how I can make my social service connection broken? I'm asking so I'm certain that I'm properly reproducing the issue.

**Comment by tyxla** [comment]
We discussed with Alister via Slack (thanks!) that broken connection can be reproed when it's disconnected from the social service side (deleting the app or the auth token). I'm proceeding to prepare #29289 for review and testing.
