### ISSUE TITLE
Gutenberg in Calypso: New Post by Contributor shows "Publish..." button before "Submit for Review" then on

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29215]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post/ as a _contributor_
2. Enter some content

#### What I expected

It should go straight to "Submit for Review" as per Calypso classic editor, then "Update" for subsequent changes

#### What happened instead

It shows the "Publish..." button before displaying "Submit for Review" then on

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

![shows publish button](https://user-images.githubusercontent.com/128826/49629791-0216e400-fa37-11e8-9445-b246529779aa.gif)

Classic:

<img width="1088" alt="screen shot 2018-12-07 at 3 42 30 pm" src="https://user-images.githubusercontent.com/128826/49629798-0ba04c00-fa37-11e8-9082-55976f0ffab0.png">

#### Context / Source

Manual Testing

**Comment by retrofox** [comment]
Still seeing the `Publish` button so let's move it to our backlog.

![new-post-contributor](https://user-images.githubusercontent.com/77539/54236657-5798dc00-44d1-11e9-80db-1848ecf6a6a5.gif)

**Comment by retrofox** [comment]
It seems to be a core issue since it happens in the wp-admin too. I think we should close this one and [report it to the Gutenberg core repository](https://github.com/WordPress/gutenberg/issues).

**Classic Editor**
<img src="https://user-images.githubusercontent.com/77539/54243215-cb90af80-44e4-11e9-8c02-93aa3a69cbe3.png" width="400px" />

**Block Editor**
<img src="https://user-images.githubusercontent.com/77539/54243290-0a266a00-44e5-11e9-83fc-70bbbf81f3cf.png" width="400px" />

**Comment by gwwar** [comment]
That sounds good @retrofox maybe do a quick search in the repository before filing 👍

**Comment by retrofox** [comment]
Researching a little bit, it doesn't seem to be a bug according to the comments of [Gutemberg core folks](https://github.com/WordPress/gutenberg/issues/6725#issuecomment-388641727).

**Comment by gwwar** [comment]
It may not be a bug for the core project, but we'll want to update this. Reopening so we don't loose track of this.

**Comment by jordesign** [comment]
I just stumbled across this in my own testing - giving it a nudge and adding it to the Blogger Experience pod for a look.

Can confirm that a contributor still sees 'Publish' as the main prompt until they click, and *then* are shown 'Submit for Review'

### Editing as a Contributor

<img width="1485" alt="Screen Shot 2021-08-30 at 3 15 28 pm" src="https://user-images.githubusercontent.com/1842363/131288895-fe23349b-8667-4782-af4e-1924bc3f5961.png">

### On clicking 'Publish'

<img width="1121" alt="Screen Shot 2021-08-30 at 3 15 36 pm" src="https://user-images.githubusercontent.com/1842363/131288969-4fbfe6a1-dc10-4077-9e31-3d34e15e571b.png">

### After 'Submitting for review' button appears correctly

<img width="1521" alt="Screen Shot 2021-08-30 at 3 15 53 pm" src="https://user-images.githubusercontent.com/1842363/131289089-6d5d2588-1b34-424a-8666-2da21ca10b18.png">

**Comment by jordesign** [comment]
This appears to be an issue already under consideration in core - so will close this one.
https://github.com/WordPress/gutenberg/issues/24945

**Comment by rosepajaroja** [comment]
Closing per notes above.
