### ISSUE TITLE
Gutenberg: Shortlink section missing from editor sidebar

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29221]
#### Steps to reproduce 

- Start with a WordPress.com site and opt-in for the new WordPress Editor, start and https://wpcalypso.wordpress.com/block-editor/post/ (if you choose this, skip the second step)
- Click `Add` next to `Blog posts`/`Site pages` 
- Publish a post

#### What is expected 

A shortlink is shown on the sidebar, after publishing it. It's shown on the Calypso editor. This can be seen under the `Sharing` section.

<img width="1280" alt="screenshot 2018-12-07 at 14 34 19" src="https://user-images.githubusercontent.com/18581859/49638107-3ab1c000-fa2d-11e8-858f-2acf74989e10.png">

#### What happens instead 

No shortlink section seen, either on Gutenberg in Calypso, or Gutenberg in wp-admin

<img width="1280" alt="screenshot 2018-12-07 at 14 33 28" src="https://user-images.githubusercontent.com/18581859/49638109-3d141a00-fa2d-11e8-9070-1cf3649fc01b.png">
<img width="1280" alt="screenshot 2018-12-07 at 14 32 54" src="https://user-images.githubusercontent.com/18581859/49638110-3d141a00-fa2d-11e8-8191-571f7aa01d48.png">

**Comment by tbradsha** [comment]
4042515-hc

**Comment by tyxla** [comment]
#29475 has been merged. Shortlinks will now appear under the Publicize panel in the Jetpack sidebar:

![](https://cldup.com/0yLlAwF39H.png)
