### ISSUE TITLE
Gutenberg in Calypso: IE11 shows "Add Title" button over title field

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29220]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post/ in IE11
2. Hover mouse over title field

#### What I expected

No button

#### What happened instead

Button appears obscuring title - this doesn't happen in the wp-admin version

#### Browser / OS version

IE11 on Windows 10

#### Screenshot / Video

![ie11 title](https://user-images.githubusercontent.com/128826/49633608-b4ee3e80-fa45-11e8-9d78-429131890a7b.gif)

**Comment by kwight** [comment]
Fixed by #31196 .
