### ISSUE TITLE
Gutenberg: wpcom wp-admin && Jetpack wp-admin: blocks are not being translated

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#29244]
#### Steps to reproduce the issue

1. Set your site/WordPress.com account to a non-English language, like Spanish
2. Create a new Page and add a Jetpack block like "Form"

#### What I expected

Expected to be able to see the same language as in the rest of my site in the form block 

#### What happened instead

The form block is displayed in English while the rest of the editor is displayed in the non-English language

**Screenshots**

![screen shot 2018-12-07 at 11 09 42](https://user-images.githubusercontent.com/3696121/49660237-15648800-fa14-11e8-893a-7871fac24d0e.png)

**Comment by scruffian** [comment]
Closing, since the code lives in Jetpack this will happen a different way: Automattic/jetpack#11817

**Comment by wpericam** [comment]
I have another instance of this here on zen-2026116 where user's site settings are in Portuguese and the error (required field not filled out, malformed email, etc) appear in English in a form block. 

Should I reopen this issue or report it here https://github.com/Automattic/jetpack/issues/11817

Or something else?
