### ISSUE TITLE
Related posts block: styling issues when used as a reusable block

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#29240]
Reusable blocks wrap the block in `<Disabled>` component, which in turn adds `opacity:0.3` to each "form element" in the block. The result isn't very pretty.

Since our titles are actually `<button>` elements (because we don't have `href` and thus don't use `<a>` here), they get this opacity, too:

<img width="640" alt="screenshot 2018-12-07 at 16 43 31" src="https://user-images.githubusercontent.com/87168/49654442-7b670480-fa40-11e8-8272-bf8d9baa519a.png">

Some considerations:

- If these titles are not `a` tags, we might be missing on theme's styles that affect how the output (i.e. links) look like with current theme
- Themes sometimes have styles for `<button>`, so we should be more protective about how we reset some styling for it
- Perhaps `<span>` with link-like styling would be safer, although not semantically as accurate and might have some accessibility issues that we would probably need to mitigate with `aria-` attributes.

#### Steps to reproduce
1. Add related posts block to a post
2. Make it reusable
3. Observe how titles get opacity `0.3`

**Comment by tyxla** [comment]
Since we made the related posts block to be a single instance block per post (`multiple: false`), I think we need to disallow it from being possible to be reusable. Reason: any reusable block can be inserted more than once per post, and we don't want to allow that.

Once we disallow reusability of related posts blocks, this issue will no longer occur.

I'll file a PR.

**Comment by simison** [comment]
Note that it might be still possible to choose multiple blocks and turn those into a reusable set of blocks, including related posts.

You can recognize if the block is wrapped like that from props, though.

**Comment by tyxla** [comment]
I just checked - if one of the multiple blocks doesn't allow reusability, you can't turn them into a reusable set. Given the constraints, I'd say this is expected behavior.

**Comment by tyxla** [comment]
#29786 disallows conversion to reusable blocks.
