### ISSUE TITLE
Purchases: Purchases page will not load for user with 100+ purchases

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#29248]
A user has about 135 domain registrations, and the Purchases page at https://wordpress.com/me/purchases will not load. It flashes the loading animation indefinitely, as shown here: http://cld.wthms.co/f7EUNL

Because this involves private user information, please see the Slack discussion at `p1544134226028300-slack-triage` for this user information in order to replicate the issue.

# Steps to replicate 

1. SU as user
2. Visit https://wordpress.com/me/purchases
3. Observe the list of purchases never loads

Followup ticket has been created at `1626582-zen`

#user-report

**Comment by jessestu** [comment]
Ticket came out of hold, so I sent a note to the user that we're still working on this.

@alisterscott, thank you for triaging the ticket.

What's the next step to get this solved?

**Comment by ktyfuller604** [comment]
The user has returned to chat looking for an update on this issue. #8719616-hc

**Comment by lancewillett** [comment]
This came up again last week thanks to @andrewspittle. Next step to resolve this:

@rralian is investigating how to speed up the API endpoint and avoid the page not loading issue.

**Comment by rralian** [comment]
I looked into this over the weekend. First I would mention that the page did load for me when logging in as the affected user, although it was very slow (took nearly 30 seconds). I understand it may not have loaded for the user, I'm not suggesting that the user is incorrect here.

This endpoint is very inefficient and most of the logic should ideally be replaced, but that's not likely to happen in the near term. I started looking into paginating the endpoint and will see how easily we can implement this. I'm starting from the back-end which should be relatively straight-forward. May need some help from a front-end dev to implement from the front-end. Paginating the endpoint can probably happen this week. Not sure about the front-end... I haven't looked at that but I seem to recall this code was done in a very non-standard way.

**Comment by rralian** [comment]
We haven't yet implemented pagination, but I confirmed that this endpoint had been optimized, so the fact that I was able to load the page may mean the user can as well. I'm going to update the ticket to see if the user is now able to load the page.

**Comment by rralian** [comment]
I can't authenticate to zendesk to update the ticket so I pinged an HE on the ticket to reach out to the user. Closing this as I am now able to consistently load the page as the referenced user.
