### ISSUE TITLE
Gutenberg: Carousel Always Opens to First Image in Gallery

### ISSUE THREAD

**Issue by jruud** [Automattic/wp-calypso#29255]
#### Steps to reproduce
1. Insert a gallery
2. Click on any image in the gallery

#### What I expected
I expected the carousel to open to the image I clicked on.

#### What happened instead
Carousel always opens to the first image in the gallery set, no matter which one is clicked.

#### Browser / OS version
Any

#### Context / Source
1625258-zen

**Comment by arunsathiya** [comment]
I believe this is a Jetpack-believe issue and I have reported it here - https://github.com/Automattic/jetpack/issues/10957
