### ISSUE TITLE
Re-Publicize: provide a calendar view of upcoming scheduled shares

### ISSUE THREAD

**Issue by richardmtl** [Automattic/wp-calypso#29258]
Requested in 6907366-hc

The user has several posts to re-schedule for this month, and would have had an easier time doing it if he had a calendar overview of the shares that were already scheduled, that he could refer to.

**Comment by tmmbecker** [comment]
Requested in a concierge session: 1907700-zen

They use https://coschedule.com/ now and would fully switch to us if we could provide a calendar. FWIW they pay $59 PER MONTH for this with coschedule

**Comment by tmmbecker** [comment]
2072912-zen

**Comment by yobyot** [comment]
Let me add whatever impetus a user request for this imparts.

In short, it's braindead to expect a user to keep track externally of which posts have been scheduled. It's bad enough this function cannot be done on a self-hosted WP admin.

Ideally, items for re-Publicize should be shown as "scheduled" in a self-hosted WP admin posts view.

**Comment by pauljacobson** [comment]
I have a request for something along these lines in 2095273-zen. The user asked why they no longer see indicators on the scheduling calendar that indicate when posts are already scheduled, here:

![calendar_scheduling](https://user-images.githubusercontent.com/2912202/59156794-c0c8c500-8aa9-11e9-912b-3650ef7b8e2c.PNG)

I'll point them to the list of scheduled posts for the time being.

**Comment by tmmbecker** [comment]
Still a request, Stalebot :)

**Comment by davemart-in** [comment]
FYI: Similar request is here: https://github.com/Automattic/wp-calypso/issues/28567 and still open. Closing this one out to avoid duplicates.
