### ISSUE TITLE
Gutenberg: Change text color for individual words/characters

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#29264]
It is not possible to change the text color of individual words or characters in a block. Changing the text color changes it for the entire paragraph.

There was an open issue for this in the Gutenberg repo, but it was closed after a plugin was released which adds this functionality to Gutenberg. 
The issue: https://github.com/WordPress/gutenberg/issues/6080
The plugin: https://wordpress.org/plugins/advanced-rich-text-tools/

WordPress.com Simple site users cannot install plugins, so I'm opening an issue to suggest we add this functionality in Gutenberg in Calypso and keep track of user requests for this feature.

# Steps to Replicate
1. Add a paragraph block
2. Highlight/select a single word
3. Change the text color
4. See that the text color of the entire paragraph changed

Here's a video of the steps to replicate: http://cld.wthms.co/t7hT48

# What I expected
To only change the text color of the word I selected

# Context/Source

This was a #user-report in 1628768-zen

**Comment by SiobhyB** [comment]
There was another request for this in 1651442-z. The user would like to highlight an individual word/s with a certain colour. It'd be great to be able to guide them to do this without needing the Classic Edit block.

**Comment by KokkieH** [comment]
Another request from [the forums](https://en.forums.wordpress.com/topic/block-editor-3/)

**Comment by KokkieH** [comment]
Another request via a comment on this [Facebook post](https://www.facebook.com/134098913979/posts/10156348238248980/)

**Comment by torres126** [comment]
Request to format individual words here: https://en.blog.wordpress.com/2019/01/08/customize-your-wordpress-com-dashboard/#comment-411030

**Comment by torres126** [comment]
+1 from me too, I'd really like to see this added - I use this frequently in posts.

**Comment by KokkieH** [comment]
Another request in https://en.forums.wordpress.com/topic/ability-to-add-colour-to-parts-of-text/, though it's a Business Plan site, so I've suggested the plugin available for this.

**Comment by katiebethbrown** [comment]
Another request in #7196772-hc.

**Comment by guicmazeredo** [comment]
Another request: #1760805-zd

**Comment by torres126** [comment]
https://en.forums.wordpress.com/topic/old-editor-versus-new/

**Comment by gwwar** [comment]
@gziolo were there no plans on adding this in Gutenberg?https://github.com/WordPress/gutenberg/issues/6080#issuecomment-438758984

**Comment by gziolo** [comment]
@ellatrix added some features recently to the core:
![Screen Shot 2019-03-13 at 09 29 05](https://user-images.githubusercontent.com/699132/54264041-7e5b1f00-4572-11e9-9aeb-7033662a9e8b.png)

However, text color for individual words/characters was never considered as a core feature. It might be revisited later if there is high demand. There is API for adding more controls and there is [Advanced Rich Text Tools](https://wordpress.org/plugins/advanced-rich-text-tools/) plugins which implements the feature which is being discussed here.

**Comment by torres126** [comment]
Another request: https://en.forums.wordpress.com/topic/how-do-i-change-the-color-of-a-single-word-in-block-format/

**Comment by kylemcph** [comment]
Another request in #12147126-hc

**Comment by nerdyandawesome** [comment]
+1 request.

**Comment by trainoasis** [comment]
+1 for sure!

**Comment by cecoates** [comment]
Another: #hc-14673881

**Comment by Pisoko** [comment]
Come on!^^ +1

**Comment by Aurorum** [comment]
WordPress/gutenberg#16014 looks like it could solve this

**Comment by kriskarkoski** [comment]
12056080-hc

**Comment by AtrumGeost** [comment]
Another request: 18249597-hc

**Comment by davipontesblog** [comment]
This is now available on simple sites from the update to WordPress core 5.4:

![Screen Capture on 2020-03-09 at 22-06-30](https://user-images.githubusercontent.com/31009008/76272730-8a93be00-6252-11ea-91df-c9880e71a75a.gif)

Closing this issue.

**Comment by strarsis** [comment]
Can this also be used for just setting the background color?
This can be very useful when the themes needs individual styling controls, e.g. for particular lines of text.

**Comment by justingolden21** [comment]
![image](https://user-images.githubusercontent.com/30274440/189417369-75799fb1-4e07-47db-a919-01f5ead4fe6d.png)

I don't see this in the gutenberg editor anywhere.

**Comment by cawa-93** [comment]
Does this allow you to change font-family for single word? 

I have a design that combines several fonts and I can't figure out how to change the font for a single word in a paragraph or in a heading

**Comment by pdrittenhouse** [comment]
+1
