### ISSUE TITLE
Sharing: Changes to sharing button options not saving as expected

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#29261]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/buttons/
2. Unselect all checkboxes under "Options: Show sharing buttons on"
3. Click Save Changes

#### What I expected
The new settings should be saved.

#### What happened instead
A success message appears and the boxes are still checked.

#### Browser / OS version
Recreated in Safari and Chrome.

#### Screenshot / Video
Screen recording: https://cld.wthms.co/fx6kVp

#### Context / Source

Reported in 8574604-hc
The options seem to save as expected when at least one checkbox is checked. A workaround to leave all checkboxes unchecked is to select one option that is not available on the site, and then click Save. The checkbox appears as unselected: https://cld.wthms.co/JxdG5e

**Comment by kathrynwp** [comment]
Already reported in #22811
