### ISSUE TITLE
Gutenberg Calypso: Publish before autosave doesn't get postid in URL

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29275]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post/
2. Enter title and post content
3. _Before_ autosave starts, click "Publish"

#### What I expected

Post is published and post ID in URL - as per classic editor

#### What happened instead

Post is published but no post ID in URL - refreshing the page no longer shows the post in the editor

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

![publish before autosave](https://user-images.githubusercontent.com/128826/49709762-b4da8280-fc81-11e8-8bd7-c3f3808effc4.gif)

**Comment by obenland** [comment]
This works now with Gutenframe (p3fqKv-6Hh-p2).
