### ISSUE TITLE
Build: Loader breaks some image URLs

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#29284]
Characters may be erroneously transformed by some part of the build.

An image `paypal-button@2x.png` provided a url/file mismatch when bundled with Jetpack blocks: #29053 / #29059 

I created #29285 to debug this.

There's some relevant commentary in the workaround PR: https://github.com/Automattic/wp-calypso/pull/29059#issuecomment-444240094

**Comment by sirreal** [comment]
It's unclear to me at this time whether or not parts of the build are working correctly or not, #29285 seems to be completely broken.

According to the following, I believe `@` is a reserved character in URIs

> URIs include components and subcomponents that are delimited by
>    characters in the "reserved" set […]
> 
>       reserved    = gen-delims / sub-delims
> 
>       gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
> 
>       sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
>                   / "*" / "+" / "," / ";" / "="

https://tools.ietf.org/html/rfc3986#section-2.2

**Comment by dmsnell** [comment]
You beat me to it @sirreal - I was going to say that the `@` is special before the path because it's used for user authentication but it's part of the `safe` group inside the `path > segment` rule.

My understanding confirms what you found - it's legal and fine.

**Comment by sirreal** [comment]
This is not a Calypso bug. It turns out this is a bug somewhere between the way CircleCI creates artifact URLs and the way we're syncing them.

Additional details here: p1547643645106500-slack-team-calypso
