### ISSUE TITLE
Domains: improve button order in DNS editor on mobile

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#2928]
As mentioned in https://github.com/Automattic/wp-calypso/pull/2262#issuecomment-176759355, the Cancel button should be below the primary button on mobile:

![screen shot 2016-01-29 at 5 30 46 am](https://cloud.githubusercontent.com/assets/3011211/12676864/ff658cd0-c649-11e5-8e17-f854bc8bc9ae.png)

@breezyskies: could perhaps help with the CSS? My CSS foo is not strong enough - I've tried some `float`s but the buttons won't budge... :disappointed: I've searched other forms in Calypso, but couldn't find a similar case :/

**Comment by stephanethomas** [comment]
One way to switch the order of these buttons would be to use a [`flexbox` layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout) and just change the [`order` property](https://developer.mozilla.org/en-US/docs/Web/CSS/order) depending on the breakpoint.

**Comment by danhauk** [comment]
I'd also recommend adding some spacing between the buttons with a `margin`

**Comment by klimeryk** [comment]
Thanks for the tips, guys :bow: I've created #3026 to fix this issue.
