### ISSUE TITLE
Gutenlypso: create A8c specific file block

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29299]
Previously we turned off the default file block because it wasn't working properly, and we couldn't adjust the attributes because of security concerns on wpcom:

https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/init.js#L23

We need to provide a custom version of this block for WPCOM.

**Comment by alisterscott** [comment]
Is #29328 because of this limitation?

**Comment by vindl** [comment]
@alisterscott I think that's a separate issue - https://github.com/Automattic/wp-calypso/issues/29328#issuecomment-446565946.

**Comment by supernovia** [comment]
Just noting I switched our support document on file blocks back to draft until this is ready.

**Comment by supernovia** [comment]
And... switched it back to published because we do have a file block in wp-admin ;)

**Comment by KokkieH** [comment]
Another user searching for a file block in Gutenlypso [here](https://en.forums.wordpress.com/topic/cannot-find-file-block/)

**Comment by KokkieH** [comment]
And [another](https://en.forums.wordpress.com/topic/file-block-not-supported-anymore/)

**Comment by arunsathiya** [comment]
3560513-hc
