### ISSUE TITLE
Posts: Contributor see an "Everyone" toggle which displays flashing notice

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29297]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/ as a contributor on a site with blog posts by other authors

#### What I expected

Since Contributors can only see their own contributions the "Everyone" toggle shouldn't exist

#### What happened instead

The "Everyone" toggle exists and it flashes (see below)

#### Browser / OS version

Tested Chrome and Safari on macOS

#### Screenshot / Video

![everyone view contributor](https://user-images.githubusercontent.com/128826/49769106-af854280-fd2a-11e8-9af0-852fe3681b20.gif)

#### Context / Source

Debugging automated e2e tests

**Comment by edequalsawesome** [comment]
Same issue reported by a user in #10604068-hc
