### ISSUE TITLE
Gutenberg: Image max-width not changing with theme

### ISSUE THREAD

**Issue by jruud** [Automattic/wp-calypso#29296]
#### Summary
On themes that have full width page templates, the default $content_width is assigned to newly created image blocks. When switching themes that have a larger content area, the image is not resized to fill the larger space.

#### Steps to reproduce
1. Activate a theme that has a full width page template (I used Penscratch 2, main column width 656px)
2. Add an image block to a page, using a larger image (1024px+)
3. Save draft or publish 
4. Switch to a theme with a wider content area (I used Ixion, main column width 712px)
5. Add an image block using the same image

#### What I expected
I expected the image that was added first to adapt to the new theme's larger container. 

#### What happened instead
The first image kept at the max width of the first theme's main column (656px) and did not fill the larger container.

#### Browser / OS version
Any

#### Screenshot / Video
<img width="891" alt="screen shot 2018-12-10 at 3 51 59 pm" src="https://user-images.githubusercontent.com/35117248/49761139-2cb1a880-fc94-11e8-9885-f3960eb004c0.png">

#### Context / Source
#1632933-zen

**Comment by mmtr** [comment]
No longer reproducible after removing Gutenberg on Calypso in favor of #31196.
