### ISSUE TITLE
Can select Free plan even when buying domain

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#29290]
It's my understanding that if a user is buying a domain, they should not be able to select the Free plan since that plan is only able to work with wordpress.com subdomains (and perhaps also X.blog subdomains? Need to look at that wording)

However when buying a domain today (.blog), the free plan was available.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/new?ref=calypso-selector
2. Create a new WPCOM site
3. Search and select a new .blog domain (e.g. abcd1234.blog)
4. Click "Select" 
5. Select the Free plan (* this doesn't appear for every account, it seems, but I couldn't figure out when it works or doesn't... but it happened to me, and not @stephanethomas )
6. Proceed through the flow
7. Once you have your new site, you have a custom domain but a free plan

#### What I expected

No free plan

#### What happened instead

A free plan was available, and I was able to provision a site with a custom domain without purchasing a paid plan.

#### Browser / OS version

MacOS Mojave, Chrome 70

#### Screenshot / Video

<img width="1105" alt="free-plan-bug" src="https://user-images.githubusercontent.com/51896/49749019-10921500-fc5c-11e8-988c-c5541958c8fb.png">

<img width="1398" alt="uh-oh" src="https://user-images.githubusercontent.com/51896/49749191-7ed6d780-fc5c-11e8-94d7-f04ee1298cf2.png">

**Comment by stephanethomas** [comment]
> this doesn't appear for every account, it seems, but I couldn't figure out when it works or doesn't... but it happened to me, and not @stephanethomas 

Note I I started from https://wordpress.com/start, and created a new test account instead of adding a new site to an existing WordPress.com account.

**Comment by adamziel** [comment]
@stephanethomas can you post a login for that account?

**Comment by adamziel** [comment]
@gravityrail did that happen with your main wp.com user, or with some other account? I can't reproduce it and reading the code didn't yield any obvious hints what may be wrong there so I'm just trying to figure out an account I could use to see the problem in action :-)

**Comment by danhauk** [comment]
Existing users who signed up and made purchases on a site pre-"Domains with Plans Only" can still purchase individual domain upgrades without a plan when creating a new site. Here is the criteria for when someone is eligible vs. needing a plan:

* All users registered after 2016-05-17 will be subject to DWPO.
* All users registered before 2016-05-17 and had no purchases before 2017-02-04 will be subject to DWPO.
* All users registered before 2016-05-17 and had any purchase on any site before 2017-02-04 will not be subject to DWPO and can continue to purchase individual upgrades; unless they cancel/expire the subscription that made them eligible.

This could be the reason behind some accounts being able to reproduce and others not. It might actually be an expected result.

**Comment by gravityrail** [comment]
Thanks @danhauk. This was with a pre-DWPO user (goldsounds) so you're right. This is probably the expected result.
