### ISSUE TITLE
Purchases: Implement Edit Payment Method page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#293]
We should add a new page to allow users to edit the method of payment of an upgrade:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11306059/1b2a0ff2-8fb0-11e5-8128-fbd930c109ed.png)

This new page should offer to:

* Update details of any stored credit card
* Associate any stored credit card to the current purchase (https://github.com/Automattic/wp-calypso/issues/281)
* Delete any stored credit card not associated to any purchase
* Associate a new credit card to the current purchase (see https://github.com/Automattic/wp-calypso/issues/280)

This following modal will be displayed when users click on any `Use This Card` button:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11306953/5d858660-8fb5-11e5-8eb0-17556e6d2932.png)

This following modal will be displayed when users click on any `Delete Card` button:

![screenshot](https://cloud.githubusercontent.com/assets/594356/11306975/830e2518-8fb5-11e5-8c57-4696cdc8ba95.png)

Here is the list of existing API endpoints that relate to this new page:

* https://public-api.wordpress.com/rest/v1/me/stored-cards  
*Returns a list of credit cards stored during a previous payment*
* https://public-api.wordpress.com/rest/v1/upgrades/:subscription_id/update-credit-card  
*Updates the credit card data for a specific upgrade*
* https://public-api.wordpress.com/rest/v1/me/stored-cards/:card_id/delete  
*Deletes a specific stored credit card*

**Comment by fabianapsimoes** [comment]
I'll close this for now. Payment Method Management will likely be a project for Gold in the future.

**Comment by drewblaisdell** [comment]
I opened https://github.com/Automattic/wp-calypso/pull/6721 to remove these components, as they are currently included in the build but not used anywhere. We can revert it when development on this feature starts again.
