### ISSUE TITLE
Gutenberg: Publicize, hide message and errors when no connection is selected

### ISSUE THREAD

**Issue by lezama** [Automattic/wp-calypso#29312]
#### Steps to reproduce
1. Disable all connections

#### What I expected
The message box to disappear

#### What happened instead
You can still see the message

#### Browser / OS version
all

#### Screenshot / Video
<img width="261" alt="screen shot 2018-12-11 at 11 58 53" src="https://user-images.githubusercontent.com/104869/49810298-b4a0bc80-fd3f-11e8-8ba2-77c05fdc8d9b.png">

**Comment by mapk** [comment]
Good idea, let's hide the msg box and errors when there are no active connections. 👍

**Comment by tyxla** [comment]
#29352 addresses this one.
