### ISSUE TITLE
Gutenberg: Publicize: Improve messaging for old Profile Facebook connections

### ISSUE THREAD

**Issue by lezama** [Automattic/wp-calypso#29314]
<img width="261" alt="screen shot 2018-12-11 at 11 58 53" src="https://user-images.githubusercontent.com/104869/49810298-b4a0bc80-fd3f-11e8-8ba2-77c05fdc8d9b.png">

#### Steps to reproduce
This is a hard one to reproduce. You need a site with a publicize connection to a Profile page.

#### What I expected
A different message, something around connecting to a Page and not a Profile.

**Comment by tyxla** [comment]
#29352 will also fix this one.
