### ISSUE TITLE
Gutenlypso: Previewing first version of Saved Draft causes a 404

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#29324]
#### Steps to reproduce
1. Starting at URL: wendiloulee.com
2. Create a new post, save it as draft
3. Click "Preview" 

#### What I expected

To see a preview of the post. 

#### What happened instead

Preview tried to open `https://wendiloulee.com/?p=1009` Got a 404 error. 

Then, after adding more content to the post and clicking Save Draft again, if you click Preview, Preview instead loads `https://wendiloulee.com/?p=1009&preview=true` and displays a preview of the draft post.

(h/t to @andrewspittle for discovering this workaround. See p1544556790659900-slack-livechat.

#### Browser / OS version

Google Chrome, 71.0.3578.80. Mac OS High Sierra. 

#### Screenshot / Video

 404 error:

![404 error](https://cldup.com/4Gr7nC4c2r.png)

After updating and clicking Save Draft again:

![no 404 error](https://cldup.com/e8YyxlkFRL.png)

**Comment by retnonindya** [comment]
Got a report from a user with similar issue (error preview page whenever they want to edit and preview their post). I couldn't replicate the problem, though, so I'm confused in this issue.

#8758316-hc

**Comment by arunsathiya** [comment]
Looks like this issue was slipped earlier with no proper labels or project. I have added them now. 

I am also marking this with normal priority, as there have been a few reports about this and does not affect a single user. Please feel free to update priority as fit.

**Comment by juliasydnor** [comment]
Also reported here: https://github.com/Automattic/wp-calypso/issues/30090

**Comment by arunsathiya** [comment]
Just a note that this does not feel to be reproducible consistently. For example, when I tested today evening, I was not able to see a 404 on a simple site and a AT site. 

There are also times when the preview shows a 404 for a brief second before showing the expected preview.

**Comment by arunsathiya** [comment]
On a larger note, could this be related to core issue https://github.com/WordPress/gutenberg/issues/13232?

**Comment by kristarella** [comment]
@arunsathiya yep, I think it is, I have been following that one and the symptoms are the same

**Comment by formosattic** [comment]
Potentially related to this case p2EDhh-Gh-p2.
Only getting 404 with Safari, and posts in Draft mode.

**Comment by tavilla61** [comment]
One more site with this same issue happening only in Safari: 

-- https://chiiky.co.uk/
-- #10965754-hc 
-- I was able to replicate the issue in Safari, but preview worked fine in Chrome. In Safari, it says "generating preview" and opens the site in a new tab. User said it sometimes also says "oops, page not found" but I didn't see that when testing.

**Comment by pauloeaquino** [comment]
Similar issue in 9429085-HC. Followup in 1859108-ZD.

Steps to produce: Edit page -> click Preview -> changes don't appear

**Comment by codebykat** [comment]
The underlying implementation has changed since this was reported, and I can't reproduce it now. Please feel free to re-open if we get any new reports!

**Comment by kylemcph** [comment]
Found another instance of this. When previewing already published posts, they are displayed as expected. 

When previewing a draft, a `404 - Page Not Found` error is thrown.

Was only able to reproduce on Safari Version 12.0.3 (14606.4.5). Both Firefox and Google Chrome previewed draft as expected.

- Site: janabouc.com
- #1933939-zen

**Comment by kosiew** [comment]
Found another issue.
#2781436-zen

**Comment by susanjanec** [comment]
User reported issue here - 2794588-zen

User mentioned using Safari and Firefox.

When trying to reproduce on my end in both Safari and Firefox, when previewing the page for an unpublished post through the edit page, the preview shows the 404 page for a second, then loads the content.

Works in Chrome as expected.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was not able to reproduce this issue on both Atomic and Simple sites:

https://user-images.githubusercontent.com/6549265/108128126-2502a100-7061-11eb-8731-8dca5ced240b.mov

Steps:
1. create a new post.
2. enter post title.
3. save draft.
4. click on `Preview`.

Preview rendered as expected on both Simple and Atomic sites.

As this issue appears to be non-reproducible, it is being closed with the label `Closed - Not Reproducible`.
If this issue should remain open, please feel free to re-open this bug.
