### ISSUE TITLE
Paragraph block: Insert link without selected text

### ISSUE THREAD

**Issue by Stojdza** [Automattic/wp-calypso#29322]
When I select nothing, just put cursor somewhere in a text, and add a link, complete link is inserted into text

1. Go to wpcalypso.wordpress.com/block-editor/post
2. Add Paragraph block 
3. Enter some text and put cursor somewhere in the text (do not select any text)
4. Insert link
5. Complete link is added

**Expected behavior**
Link should not be added (as in Classic Editor)

**Screenshots**
https://cloudup.com/cWyVOE8zOsC

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.3
 - Browser: Chrome
 - Version: 70

Originally discussed here https://github.com/WordPress/gutenberg/issues/12790

**Comment by vindl** [comment]
What I'm seeing in the screen capture looks to me like an expected behaviour. In my opinion the Gutenberg core and Gutenlypso handle this case as expected, and it should probably be fixed in Calypso Classic editor.

**Comment by gwwar** [comment]
Retested in Gutenberg core / dotcom and verified that this is native Gutenberg behavior.
