### ISSUE TITLE
Log-in: Extra slash in log-in page makes page unusable

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29333]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com//log-in

#### What I expected

Log in page

#### What happened instead

Log in page is broken - console error in production:

`vendors~build.15e2466f8e9871e8aa7c.min.js:71 Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://log-in/' cannot be created in a document with origin 'https://wordpress.com' and URL 'https://wordpress.com//log-in'.`

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

<img width="1442" alt="screen shot 2018-12-12 at 5 31 52 pm" src="https://user-images.githubusercontent.com/128826/49853743-d8452f00-fe33-11e8-85cd-df1029ffebda.png">

**Comment by Aurorum** [comment]
This is still an issue
