### ISSUE TITLE
SDK: Expand documentation on Gutenberg

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#29337]
We've been chatting with @nosolosw today, and he brought up some really great points about improving the SDK documentation. He obtained those as he tried the SDK for a custom Gutenberg extension.

**Building single blocks with the SDK**

It seems that in our recent documentation updates we've concentrated on documenting well how to work with the presets, but in that effort we've left behind cases where one wants to build a single block. There are examples of how to work with the presets, but we don't have examples on how to build a single, independent block. Would be great to add some.

**Editor and view**

There are many mentions of `editor` and `view`, but we haven't made it clear enough what the purpose of each of them is, what we should them for and how they should be enqueued. Let's explain these thoroughly, and give some examples.

**Comment by nosolosw** [comment]
This captures my main feedback!

I've just realized that the editor/view usage is documented at https://github.com/Automattic/wp-calypso/tree/master/client/gutenberg/extensions#gutenberg-extensions

**Comment by tyxla** [comment]
cc @Automattic/calypso-sdk @Automattic/luna @Automattic/poseidon
