### ISSUE TITLE
Gutenberg: Publicize: Turn off - Disable connection with errors

### ISSUE THREAD

**Issue by lezama** [Automattic/wp-calypso#29357]
Disable the connection(switch the toggle off) when it's on an unusable state.

<img width="272" alt="screen shot 2018-12-12 at 11 53 27" src="https://user-images.githubusercontent.com/104869/49878847-4e7f6c80-fe07-11e8-89ba-05164a53bea2.png">

**Comment by tyxla** [comment]
Once we land #29754, this is a piece of cake to fix.

**Comment by tyxla** [comment]
And here's a fix: #29755 - could use some testing and review.
