### ISSUE TITLE
Me: profile link buttons don't appear correctly on smaller mobile devices

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#2936]
When visiting `/me` on a (simulated) iPhone 5S in portrait mode, the buttons stack but obscure some of the label:

<img width="432" alt="screen shot 2016-02-01 at 16 06 18" src="https://cloud.githubusercontent.com/assets/17325/12707848/fdd337bc-c8fd-11e5-9ec1-d3ca58c1ede5.png">

**Comment by reganstarr** [comment]
I'm not able to assign this to myself, so I am leaving a comment to indicate that I'm working on this issue.

**Comment by mtias** [comment]
Also cc @alternatekev who was recently around this component.

**Comment by alternatekev** [comment]
This shows some limitations of the SectionHeader: put too much in it, and it breaks! 

Wondering if there's a way to handle multiple actions like this within the component itself, which would take some thinking/discussing on how best to handle.

**Comment by mtias** [comment]
Seems like it could drop into an ellipsis menu / popover like we do in some other places.

**Comment by alternatekev** [comment]
@mtias Can we leverage the `Popover` component? It seems like it's just using raw `<button>` tags to do the menus. 

It would be cool if `SectionHeader` automatically passed whatever buttons you use within it to fill the popover.

Although thinking through this more, having a Save button in a dropdown/ellipsis menu is a bit weird, and lots of our SectionHeaders have Save buttons up there.

**Comment by reganstarr** [comment]
Since this requires some thinking/discussing, I'm going to hold off on working on it and move on to another issue.

**Comment by hoverduck** [comment]
07Apr16 Bug Scrub

Confirmed this is still a problem.

**Comment by bluefuton** [comment]
Fixed in #4611. Thanks @alternatekev!
