### ISSUE TITLE
Gutenpack: publish panel completely flashes when autosave taking place 

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29392]
I tested this on Gutenberg master without Jetpack and there was a very slight flash but not as obvious/jarring - especially as you can be interacting with publicize settings

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post/ (or wordpress.com/post - this also affects wp-admin usage)
2. Add a title and enter text before and click publish before auto-save 

#### What I expected

The publish panel displays

#### What happened instead

The publish panel displays but the entire panel flashes and rerenders when the autosave takes place - you can see the auto save in network traffic in dev tools

#### Browser / OS version

Chrome on macOS

#### Screenshot / Video

![sidebar flash](https://user-images.githubusercontent.com/128826/49917370-9b883f00-feea-11e8-95e8-391d1d2d9d37.gif)

#### Context / Source

#dogfooding

**Comment by tyxla** [comment]
This is actually the periodic autosave, coming from the Gutenberg core, and AFAIK it's expected behavior. I'm closing this one.
