### ISSUE TITLE
Activity log: allow filtering by product (WooCommerce)

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#29401]
The Activity log already recognizes the `product` custom post type, as it comes from the WooCommerce side of things, assigning it a different icon and description.

![image](https://user-images.githubusercontent.com/390760/49935525-1cceda00-fec9-11e8-99ec-62a5fc606a4a.png)

Since this is a unique type of content that is treated differently, we should detach them from `Posts and Pages`, expose it in the filtering options and letting customers filter their activity by product items, like so:

![image](https://user-images.githubusercontent.com/390760/49935702-a7afd480-fec9-11e8-8adb-b337370a19db.png)

h/t @dougaitken who brought this up in p1544696457012800-slack-activity-log

**Comment by keoshi** [comment]
Would still be great to have this.

**Comment by dougaitken** [comment]
This came up again as someone asked how to view which site member published or changed a product - I forgot this was via the Posts/Pages filter.

**Comment by keoshi** [comment]
This was implemented a while back, and we now have filtering options for both Products and Orders:

![image](https://user-images.githubusercontent.com/390760/132381502-49b33ee9-e10d-4af7-bfef-c599a08d79e8.png)

Closing the issue!
