### ISSUE TITLE
Gutenberg: Adding or removing a caption in classic editor block not working

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/wp-calypso#29412]
#### Steps to reproduce
1. Start with a site using the Classic Editor
2. Add a post, add an image to the post and Publish it
3. Choose to activate the new editor. 
4. Click the image and add a caption, click update and check the post: the caption isn't there (not in the image settings nor in the post itself, if you update it)

#### What I expected
Adding / removing a caption from an image should work. This also applies to changing image sizes.

#### What happened instead
The images are unaltered.

#### Browser / OS version
MacOS / Firefox

#### Screenshot / Video
Video: http://cld.wthms.co/SP93qn

#user-report hc-8047546

**Comment by arunsathiya** [comment]
Noting that this can be reproduced only on Calypsoified Gutenberg. Modifying captions and saving the updated captions works fine on Gutenlypso (Gutenberg in Calypso)

**Comment by jordesign** [comment]
As this is only related to Calypsofied Gutenberg (which is now discontinued) I'm closing this in favour of https://github.com/Automattic/wp-calypso/issues/45389
