### ISSUE TITLE
Publicize Connection Selector - Unable to Choose Different Account

### ISSUE THREAD

**Issue by aamills** [Automattic/wp-calypso#29414]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/
2. Select to Connect a Facebook account/page to Publicize to, clicking "Connect".
3. Try to select any page that isn't the first option in the pop up.
4. Only the 1st Facebook _page_ can be connected. 

#### What I expected
I should be able to select any of my Facebook Pages to connect.

#### What happened instead
Only the 1st page was select-able in the pop up. My work around - because I had only two pages, was to "Connect a different account" after the _wrong_ one was connected. And then my other page was the 1st option the list and could be chosen.

Not a suitable work around for folks with many FB pages (worked for me because I only have 2).

#### Browser / OS version
Chrome, Version 71.0.3578.98 (Official Build) (64-bit)

#### Screenshot / Video
![publicizefb](https://user-images.githubusercontent.com/29556134/49959437-c82c5e80-feca-11e8-8326-bcb76e1a47a1.gif)

#### Context / Source
 #user-report - #8800439-hc

**Comment by bikedorkjon** [comment]
I've replicated it and was reported in 1644089-zen. I'm not seeing any type of console error.

**Comment by mzakariya** [comment]
Reported in 1644043-zen. No console errors. User has many pages, so there's no suitable workaround for them.

**Comment by bikedorkjon** [comment]
@blowery is it possible that your PR is the culprit here seems to be the most one touching this component? https://github.com/Automattic/wp-calypso/pull/28607

**Comment by aisajib** [comment]
For the record, this happens with Twitter connections as well. Only the first one in the list of previously added Twitter connections can be selected. GIF showing I logged into one Twitter account but was unable to select that one. 

![screen capture on 2018-12-13 at 19-54-08](https://user-images.githubusercontent.com/2541844/49975337-ac2aca80-ff67-11e8-980f-193fc89be809.gif)

Reported in #3182223-hc

**Comment by joeboydston** [comment]
Also reported in:
https://mc.a8c.com/support-stats/happychat/transcript.php?id=874271

**Comment by sarahcada** [comment]
Also reported in: 7501961-hc

**Comment by blowery** [comment]
@bikedorkjon could you see if you can repro on https://hash-a74767e71af80cdf6a013b1c4d106775dbcc039f.calypso.live/ ? That's the commit before we landed the CSS refactoring.

**Comment by blowery** [comment]
revert has landed. This should be working again. Sorry for the trouble!
