### ISSUE TITLE
Gutenberg: cannot create new portfolio projects or remove tags from existing ones on a simple site.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#29422]
#### Steps to reproduce

1. Switch to a simple site in Calypso

2. Make sure Portfolio Projects are enabled (Settings - Writing - Portfolio Projects)

3a. If Gutenberg is already enabled, attempt to create a new Portfolio project. When "Publish" is clicked this error appears:

![edit_project_____kpgutentester_____wordpress](https://user-images.githubusercontent.com/10121835/49973111-6c2cfe80-fef9-11e8-976d-1679ee32a0b3.jpg)

This is the console error the above message refers to:

~~~~
"TypeError: Cannot read property 'some' of undefined
   at https://s2.wp.com/_static/??-eJx9z9tuwjAMANAfWvDQQNUeJj4FpYkJLrkpdin9e7ypIMSkPvjF9vEFpmpcyYJZoMYxUGZI6MkavNVYGjZgbFdyyCATiWhi4M3AH/AirU+UzcNfyWOpDZnBMqPwUv+b+07T+HTBxohtNkqEcvifWLEDSrXuAkfKDvpY3IUNi9VaAF0rpb3jh+Q5i72dKZyjxu9/nliWGZt+pOjX33U2zpULnWZIxbMJozb12MI6m6qef0L0vd6trYf0s93vdt32+7P7Gu70jZpU:268:121486
   at ph (https://s0.wp.com/_static/??-eJydj0cOwjAURC+E/WNsFGWBOIvLj3HkJhfK7bFAYh1YjkZvCtwz0Sk2jA2y79bFCrYPqbDY4RQE1Z03YFIgBaV5gosGH3SrB9jLSsZ+w24YTSow+nSjwUXK1DILLeUfPBnL3xkz4+sk170Zn+lYtcxIri3474NLOLOT4FwcxbRsL8gVddk=:131:88)
   at eg (https://s0.wp.com/_static/??-eJydj0cOwjAURC+E/WNsFGWBOIvLj3HkJhfK7bFAYh1YjkZvCtwz0Sk2jA2y79bFCrYPqbDY4RQE1Z03YFIgBaV5gosGH3SrB9jLSsZ+w24YTSow+nSjwUXK1DILLeUfPBnL3xkz4+sk170Zn+lYtcxIri3474NLOLOT4FwcxbRsL8gVddk=:159:307)
   at fg (https://s0.wp.com/_static/??-eJydj0cOwjAURC+E/WNsFGWBOIvLj3HkJhfK7bFAYh1YjkZvCtwz0Sk2jA2y79bFCrYPqbDY4RQE1Z03YFIgBaV5gosGH3SrB9jLSsZ+w24YTSow+nSjwUXK1DILLeUfPBnL3xkz4+sk170Zn+lYtcxIri3474NLOLOT4FwcxbRsL8gVddk=:160:168)
   at wc (https://s0.wp.com/_static/??-eJydj0cOwjAURC+E/WNsFGWBOIvLj3HkJhfK7bFAYh1YjkZvCtwz0Sk2jA2y79bFCrYPqbDY4RQE1Z03YFIgBaV5gosGH3SrB9jLSsZ+w24YTSow+nSjwUXK1DILLeUfPBnL3xkz4+sk170Zn+lYtcxIri3474NLOLOT4FwcxbRsL8gVddk=:172:237)
   at fa (https://s0.wp.com/_static/??-eJydj0cOwjAURC+E/WNsFGWBOIvLj3HkJhfK7bFAYh1YjkZvCtwz0Sk2jA2y79bFCrYPqbDY4RQE1Z03YFIgBaV5gosGH3SrB9jLSsZ+w24YTSow+nSjwUXK1DILLeUfPBnL3xkz4+sk170Zn+lYtcxIri3474NLOLOT4FwcxbRsL8gVddk=:171:115)
   at ng (https://s0.wp.com/_static/??-eJydj0cOwjAURC+E/WNsFGWBOIvLj3HkJhfK7bFAYh1YjkZvCtwz0Sk2jA2y79bFCrYPqbDY4RQE1Z03YFIgBaV5gosGH3SrB9jLSsZ+w24YTSow+nSjwUXK1DILLeUfPBnL3xkz4+sk170Zn+lYtcxIri3474NLOLOT4FwcxbRsL8gVddk=:183:69)
   at Se (https://s0.wp.com/_static/??-eJydj0cOwjAURC+E/WNsFGWBOIvLj3HkJhfK7bFAYh1YjkZvCtwz0Sk2jA2y79bFCrYPqbDY4RQE1Z03YFIgBaV5gosGH3SrB9jLSsZ+w24YTSow+nSjwUXK1DILLeUfPBnL3xkz4+sk170Zn+lYtcxIri3474NLOLOT4FwcxbRsL8gVddk=:74:45)"
~~~~

3b. If Gutenberg is already enabled and a "Classic" portfolio project has already been published, attempt to remove a Project Tag. Once the "Update" button the changes are thrown out and the tags are restored.

3c. If Gutenberg is not yet active, you can create/edit/publish Portfolio projects at will. However, you won't be able to enable Gutenberg from within either a new Portfolio project, or an existing one. If you try you'll be shown the error in 3a.

You can, however, edit a page or a post, and choose to enable Gutenberg that way.

#### What I expected
To be able to add new portfolio projects, or remove portfolio project tags via Gutenberg.

#### What happened instead
When trying to create a new portfolio project with Gutenberg, are presented the error “the editor has encountered an unexpected error”

When trying to remove a project tag from an existing portfolio project with Gutenberg, changes are completely ignored.

WP-Admin/Classic editor can edit/publish projects as expected with no issues. Non-simple Business sites can edit projects with Gutenberg with no issues.

#### Browser / OS version

Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

Mozilla Firefox 63.0 (64-bit)

Pop!_OS 18.10

#### Screenshot / Video

![peek 2018-12-13 17-35](https://user-images.githubusercontent.com/10121835/49974562-9681ba80-feff-11e8-8ac1-2676f2876703.gif)

![peek 2018-12-13 17-36](https://user-images.githubusercontent.com/10121835/49974570-9bdf0500-feff-11e8-9842-e1f94e105f19.gif)

#### Context / Source

Originally reported to me in 2775062-hc

But was able to verify on three of my own simple sites with Gutenberg, and also confirmed with another HE who could also reproduce the same behavior.

**Comment by katiebethbrown** [comment]
Another report in #1657011-zen.

I was also able to reproduce this on a test site. 

Screen Recording, including the console errors: https://cld.wthms.co/KaqkBZ

On my test site (simple site, free plan), when I open a Portfolio project with the new editor enabled, I see the following message in the console:

```
Unhandled promise rejection BadRequestError: "No Content-Disposition supplied."
	e https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:128:29287
	R https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:128:35447
vendors~build.d7ea041b2080d467e226.min.js:18:128288
```

When I Publish the project, I get the error "The editor has encountered an unexpected error." and the following appends to the console:

```
TypeError: "t is undefined"
	Y https://wordpress.com/calypso/1.3e429385c9b6a982c724.min.js:77:160379
	Ob https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:62069
	Gb https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:78434
	Yb https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:78811
	Nr https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:85234
	Lr https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:84614
	Er https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:90825
	Bn https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:30538
```

**Comment by sdixon194** [comment]
Another report in 1654850-zen 

Error is:


`TypeError: Cannot read property 'some' of undefined at https://wordpress.com/calypso/1.3e429385c9b6a982c724.min.js:77:160402 at Ob (https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:62069) at Gb (https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:78434) at Yb (https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:78811) at Nr (https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:85234) at Lr (https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:84614) at Er (https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:90825) at Bn (https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:30538)
`

Temporary workaround seems to be using the ellipses menu in the draft list to publish the project.

**Comment by brezocordero** [comment]
Another report in 7956861-hc
Same errors as above

**Comment by sdixon194** [comment]
again in 1659732-zen

**Comment by lizswafford** [comment]
Another report here 1659254-zen.  (Tested specifically creating a new Portfolio project, not tags, on a simple site.)

**Comment by fresatomica** [comment]
Another one 8971023-hc

`./client/gutenberg/extensions/publicize/index.js/Y<@https://wordpress.com/calypso/1.98cf932f262a331bd0c8.min.js:77:163008
Ob@https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:62069
Gb@https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:78434
Yb@https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:78811
Nr@https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:85234
Lr@https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:84614
Er@https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:90825
Bn@https://wordpress.com/calypso/vendors~build.d7ea041b2080d467e226.min.js:79:30538`
