### ISSUE TITLE
SDK: Build source outside Calypso repo

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#29427]
The SDK should be able to build from source outside of Calypso. Currently, it cannot.

#### Steps to reproduce
Try to build some source that isn't inside of Calypso:

```sh
npm run sdk generic /some/path/to/some/file.js output/file.js
# Module not found: Error: Can't resolve '@babel/runtime/helpers/typeof' in …
```

It fails

cc: @Automattic/calypso-sdk

**Comment by sirreal** [comment]
This is a hurdle that came up when the first SDK development push wrapped up. One of the goals was to be able to build some source just by pointing the sdk at it. In practice, that doesn't seem to work.

I don't have a real use case at this point, only hypothetical ones. I can say that when we started Jetpack blocks work and decided to use the SDK, putting the blocks source code into the Jetpack repository was not an option because of this limitation.

**Comment by jsnajdr** [comment]
So, the goal seems to be:
- put block sources inside the Jetpack repo (or any other place outside Calypso).
- if the block does `import from 'foo'` of a NPM package, the Jetpack repo is responsible for providing a `node_modules` folder with the `foo` package.
- the Jetpack repo is not responsible for providing `@babel/runtime` helper packages or other stuff that's an implementation detail of the SDK. The SDK should be a self-contained package.

Is that right?

**Comment by sirreal** [comment]
> Is that right?

Yep, that aligns with my expectations.

> The SDK should be a self-contained package.

This is part of my personal vision for the SDK's future, but I'm unsure whether that's a vision shared by other groups. (cc: @ehg and devx)

**Comment by simison** [comment]
We now have [`@automattic/calypso-build` package](https://github.com/Automattic/wp-calypso/tree/7ab3ee0df657c553f7a580228ebdc16f72c8b56c/packages/calypso-build) that can be used anywhere. <3

**Comment by dmsnell** [comment]
@simison I clicked the link and found no documentation or explanation of how to use - was this intentional? is the documentation elsewhere?

**Comment by simison** [comment]
@dmsnell yup, docs are still missing (https://github.com/Automattic/wp-calypso/issues/31679). The package is still in flux so API might change. Once it's stable we'll get docs sorted out; should be within couple weeks.
