### ISSUE TITLE
Reader: Clicking like on post with likes already obscures star button

### ISSUE THREAD

**Issue by astralbodies** [Automattic/wp-calypso#29432]
#### Steps to reproduce
1. Find a post in the reader with likes already and you haven't liked it.
2. Click Like.

#### What I expected
The star should turn yellow and the count increases.

#### What happened instead
The hover showing the people who already liked it increases to include "+1 more" and it obscures the star button entirely.

#### Browser / OS version
macOS 10.14.1 Safari 12.0.1 (14606.2.104.1.1)

#### Screenshot / Video
![2018-12-14_06-56-41](https://user-images.githubusercontent.com/373903/50004798-e1d2b200-ff6d-11e8-9885-262490a4f1a1.gif)

**Comment by bluefuton** [comment]
Thanks for the report @astralbodies. I'll have a tinker with the positioning.

The likes popover is currently only shown to internal users (feature flag is not enabled on production).

**Comment by bluefuton** [comment]
One possible fix would be to exclude the current user from the likers list, leaving the illuminated star to show that you've liked it.
