### ISSUE TITLE
[Classic Bright] - Update hover state border for contained buttons

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29441]
In the Classic Bright color scheme, the hover state border for contained buttons (buttons displaying as the secondary pink color (`color-accent`)(`hot-pink-500`) is displaying as blue when it should display as `color-accent-dark`

<img width="214" alt="screen shot 2018-12-14 at 10 13 25 am" src="https://user-images.githubusercontent.com/9257264/50011517-54518b00-ff8a-11e8-80a8-a1bc4d70176a.png">

**Comment by flootr** [comment]
fixed via  #29443
