### ISSUE TITLE
Posts: Post control buttons not vertically centered on mobile

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#2945]
On mobile view, the post control buttons aren't vertically centered in the container. It looks like the bug is because the buttons with padding don't fit within the container's `3em` height.

![screen shot 2016-02-01 at 1 31 34 pm](https://cloud.githubusercontent.com/assets/448298/12727044/ec7bb7ba-c8e8-11e5-8f42-93f7c0894c47.png)

They look fine once you get past the >660px breakpoint.

![screen shot 2016-02-01 at 1 39 37 pm](https://cloud.githubusercontent.com/assets/448298/12727107/469083a2-c8e9-11e5-81c5-a6af476e1aa1.png)

**Comment by mtias** [comment]
cc @adambbecker
