### ISSUE TITLE
[Classic Bright] - Update right arrow icon in Navigation Drawer list item 

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29469]
Update right arrow icon in Navigation Drawer list item on hover from `color-accent` to `color-primary`

<img width="1328" alt="screen shot 2018-12-14 at 7 31 37 pm" src="https://user-images.githubusercontent.com/9257264/50036496-470ebd80-ffd7-11e8-9408-fcf7fc0ca445.png">

**Comment by flootr** [comment]
done via #29483
