### ISSUE TITLE
[Classic Bright] - Update hover state text color on tabs

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29467]
Hover states on tabs are displaying as `color-accent`and should display as `color-primary`

<img width="1325" alt="screen shot 2018-12-14 at 7 24 05 pm" src="https://user-images.githubusercontent.com/9257264/50036354-54777800-ffd6-11e8-88ed-5352c887503c.png">

**Comment by flootr** [comment]
fixed by #29481
