### ISSUE TITLE
Framework: error and success notices don't like to co-exist

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#2946]
While testing #1916 I've encountered this error in the console:
```
Warning: flattenChildren(...): Encountered two children with the same key, `.1:$notice-0`. Child keys must be unique; when two children share a key, only the first child will be used.
```
Steps to reproduce:
* visit `/domains/manage/:site/dns/:domain`
* add a new record, a success notice will be displayed (don't dismiss it)
* trigger an error (I went offline using the Developer Tools and tried adding a new record)

It seems the success and error notices conflict with each other.
The code triggering this behaviour is in [`dns-add-new.jsx`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/domain-management/dns/dns-add-new.jsx#L95-L101). Nothing special - just calling `notices.success` and `notices.error` with a string. Note that I've observed the same behaviour with a mix of "reduxified" and normal notices (as seen in #1916).

**Comment by artpi** [comment]
Hmm, the code trigerring this is using old notices (not redux)
But good to keep an eye on that while refactoring global notices 
https://github.com/Automattic/wp-calypso/pull/2413
