### ISSUE TITLE
[Classic Bright] - Remove all instances of yellow

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29468]
Found a one off usage of yellow within the UI. @drw158 should this be `color-accent` or `color-primary`?

<img width="1327" alt="screen shot 2018-12-14 at 7 27 49 pm" src="https://user-images.githubusercontent.com/9257264/50036428-db2c5500-ffd6-11e8-99e4-06a4e7e52209.png">

**Comment by drw158** [comment]
Adding a note it should be primary.

**Comment by flootr** [comment]
@cburton4 are there wrong usages of yellow other than seen in the screenshot above? They already use the new CSS vars and it's hard to tell only by searching through code which one is right and which one is wrong.

**Comment by drw158** [comment]
There may be other wrong uses, but impossible to know based on the code I think. Another example of wrong usage of yellow and green: #29628

**Comment by flootr** [comment]
done 🎉 

```
❯ rg '\$alert-yellow'
assets/stylesheets/shared/_colors.scss
39:$alert-yellow: #f0b849;
```
