### ISSUE TITLE
[Classic Bright] - Remove all instances of orange

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29466]
Remove all instances of orange. Displays most prominently in the stats graph.

<img width="1060" alt="screen shot 2018-12-14 at 10 42 30 am" src="https://user-images.githubusercontent.com/9257264/50036268-b683ad80-ffd5-11e8-9279-17fe16d5bc45.png">

<img width="1325" alt="screen shot 2018-12-14 at 7 34 59 pm" src="https://user-images.githubusercontent.com/9257264/50036544-91903a00-ffd7-11e8-8933-4bbed5f8a0fb.png">

<img width="1325" alt="screen shot 2018-12-14 at 7 35 08 pm" src="https://user-images.githubusercontent.com/9257264/50036547-9523c100-ffd7-11e8-80ab-0edf1b3f9a54.png">

**Comment by flootr** [comment]
Just a note regarding the map (last screenshot) on the stats page: these colors are set via JS and our theming capabilites are somewhat limited (see https://developers.google.com/chart/interactive/docs/gallery/geochart for more)

**Comment by flootr** [comment]
More occurrences of `$orange-jazzy` and `$orange-fire` in code:

```
❯ rg '\$orange-*' client --files-with-matches -c
client/reader/update-notice/_style.scss:1
client/blocks/comments/style.scss:1
client/blocks/inline-help/style.scss:3
client/blocks/like-button/style.scss:4
client/layout/masterbar/style.scss:4
client/layout/community-translator/style.scss:1
client/post-editor/editor-sticky/style.scss:1
client/post-editor/editor-status-label/style.scss:1
client/post-editor/editor-delete-post/style.scss:4
client/components/drop-zone/style.scss:3
client/my-sites/plan-price/style.scss:1
client/post-editor/editor-publish-date/style.scss:2
client/lib/preferences-helper/style.scss:1
client/components/chart/style.scss:3
client/my-sites/post-relative-time-status/style.scss:1
client/my-sites/plan-features/style.scss:1
client/components/post-schedule/style.scss:1
client/components/banner/style.scss:1
client/my-sites/comments/comment/style.scss:2
client/components/forms/form-label/style.scss:1
client/my-sites/people/people-profile/style.scss:1
client/my-sites/stats/stats-chart-tabs/style.scss:1
client/my-sites/stats/stats-tabs/style.scss:1
client/my-sites/stats/stats-list/style.scss:1
client/my-sites/stats/stats-module/style.scss:1
client/components/tinymce/plugins/contact-form/style.scss:1
client/my-sites/checklist/wpcom-checklist/checklist-navigation/style.scss:1
client/extensions/woocommerce/app/store-stats/store-stats-referrer-conv-widget/style.scss:2
client/extensions/woocommerce/app/store-stats/store-stats-referrer-widget/style.scss:2
client/extensions/woocommerce/app/store-stats/store-stats-referrer-widget-base/style.scss:2
client/extensions/woocommerce/components/d3/sparkline/style.scss:1
client/notifications/src/panel/boot/stylesheets/actions.scss:4
```

**Comment by flootr** [comment]
The only occurrence of `$orange-jazzy` or `$orange=fire` left is the drop zone mentioned in https://github.com/Automattic/wp-calypso/issues/29466#issuecomment-448570678. Any other usages left (in masterbar & plans) are intended. Closing this and creating a separate issue for the drop zone which doesn't seem to be of high priority right now.

/cc @cburton4
