### ISSUE TITLE
Calypsoified Gutenberg: "Add" button on Feedback Section Does Not Work

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#29477]
I have switched my test site to Gutenberg and when I try to click on "Add" in Calypso by the section "Feedback", I am getting the error that I do not have permission to add it.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/types/feedback/
2. Then click on the option "Add" by the word Feedback:

<img width="1180" alt="screen shot 2018-12-16 at 12 00 38 pm" src="https://user-images.githubusercontent.com/25575134/50056435-3fabf900-012a-11e9-96af-5c5a83d5a1b3.png">

#### What I expected

To see the screen where I can create "Feedback".

#### What happened instead

I saw the screen that said that I do not have permission to create it.

<img width="1195" alt="screen shot 2018-12-16 at 12 01 49 pm" src="https://user-images.githubusercontent.com/25575134/50056448-6407d580-012a-11e9-911a-c1a0c4e92e12.png">

The URL it brought me to is: https://himarkblog.wordpress.com/wp-admin/post-new.php?post_type=feedback&calypsoify=1

Once I disabled Gutenberg, I am able to create Feedbacks with no issue:

<img width="1233" alt="screen shot 2018-12-16 at 12 03 58 pm" src="https://user-images.githubusercontent.com/25575134/50056471-b648f680-012a-11e9-8ab8-a5aca055fe62.png">

#### Context / Source

The report came in from the user in #1648914-zen

**Comment by katinthehatsite** [comment]
note: I am the owner of my test site.

**Comment by arunsathiya** [comment]
I saw this behaviour once as well - p2EDhh-Bu-p2, but I was able to see the editor just fine when I was using the new WordPress Editor/Gutenberg. I am not very sure what causes the permissions error to appear.

Having said this, I think this issue can be closed in favour of https://github.com/Automattic/wp-calypso/issues/17437. The `Add` button shouldn't appear for custom post types like `Feedback` at all, as the `Feedback` post type is meant to show a list of contact form submissions and is not to be created by the site owner. 

Thoughts, @katinthehatsite?

**Comment by gwwar** [comment]
Likely a permissions mismatch between wp-admin checks and the related API endpoint. (It can happen sometimes).

@apeatling did we have any use cases for manually editing feedback? For reference feedbacks are created on contact form submission, so in general there shouldn't be a case where we need to create a new one from this flow.

**Comment by gwwar** [comment]
I don't believe this is still applicable with changes in https://github.com/Automattic/wp-calypso/pull/30799 landed. If folks see another permission error, please reopen!
