### ISSUE TITLE
[Classic Bright] - Update selected state color for toggle button

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29471]
Update selected state color for toggle button from `color-accent` to `color-primary`

<img width="1329" alt="screen shot 2018-12-14 at 7 44 36 pm" src="https://user-images.githubusercontent.com/9257264/50036743-4f67f800-ffd9-11e8-899a-599587c3f537.png">

**Comment by flootr** [comment]
related #29472

**Comment by flootr** [comment]
done via #29454
