### ISSUE TITLE
[Classic Bright] - Update hover state color for toggle button

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29472]
Update hover state color for toggle button. 

@drw158 what color should this hover state be?

<img width="1327" alt="screen shot 2018-12-14 at 7 48 46 pm" src="https://user-images.githubusercontent.com/9257264/50036781-a53ca000-ffd9-11e8-8387-d62481f108fa.png">

**Comment by flootr** [comment]
see also #29454

**Comment by drw158** [comment]
Hover state should be 

background: --color-primary-light

**Comment by flootr** [comment]
done via #29454
