### ISSUE TITLE
[Classic Bright] Sidebar selected item "Add" button to use primary color

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#29485]
Update sidebar selected item "Add" button on hover from `accent` to `primary`

<img width="316" alt="screenshot 2018-12-17 at 09 24 45" src="https://user-images.githubusercontent.com/9202899/50074927-b5bd6800-01dd-11e9-8dee-0a82fe07c4e3.png">

**Comment by flootr** [comment]
@drw158 I think I could use some design feedback here. As indicated by the GIF below there's currently no hover state for the _Add_ button if the sidebar item is unselected although I think there should be one as it's a different action from the one assigned with the sidebar item itself.

![sidebar-buttons-right](https://user-images.githubusercontent.com/9202899/50150336-f2609080-02bd-11e9-80cb-53cc32b9ff7d.gif)

In comparison here's the legacy blue version:

![sidebar-button-right-legacy](https://user-images.githubusercontent.com/9202899/50150344-f9879e80-02bd-11e9-8e3b-df46388fe39f.gif)

**Comment by drw158** [comment]
Let's replicate the old scheme and do `color: var( --color-accent )` on hover for both the unselected and selected items.

**Comment by flootr** [comment]
fixed in #29933
