### ISSUE TITLE
Gutenlypso: content disposition console error

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29499]
Investigate and fix the following console error that can be seen once Gutenlypso is loaded:

```
Uncaught (in promise) Error: No Content-Disposition supplied.
    at R (vendors~build.2b2bc6e168074613c2b0.min.js:128)
```

**Comment by kwight** [comment]
Without any user-facing bug involved that we know of, I'd say console errors are rarely high priority.

**Comment by codebykat** [comment]
Closing invalid (thanks Gutenframe)
