### ISSUE TITLE
Tiled gallery block: photonize image URLs

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#29495]
By using Photon, some shape calculations might be more straightforward and we could save bytes by serving actual square images for square layout, instead of cropping them out.

That said, we'll need to ensure experience stays smooth by using "stepped" Photonized image sizes. 

Imagine if you uploaded an image or resized the gallery by opening Gutenberg sidebar; each image would now be slightly different size and start loading a new Photon image. We need to ensure that we don't load new photon image too often, especially in the editor.

Situations that we should test:

- Adding new images to the gallery
- Toggling Gutenberg sidebar hidden/visible
- Changing alignment
- Resizing the browser window
- In future, we might have drag'n'drop feature (#28950), how will that be affected?

Suppose in the editor view, we should grab the total width of the gallery and use the same size for each image that we Photonize: that way even if images are shuffled around, they always have an image already loaded.

In the view, we can be a little bit more aggressive with image sizes to save bandwidth.

A bit of code for this already in: https://github.com/Automattic/wp-calypso/pull/29465/files#diff-64399d2ba5e2912315cb18d8cc16dafbR140

Related "use large images" (#29544)

**Comment by sirreal** [comment]
Are there concerns about privacy or the other reasons sites may disable photon?

**Comment by simison** [comment]
Sites wanting to implement Content security policy headers might not want to add something as generic as `s{1,2,3}.wp.com` to their policies https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP but I'd assume that applies mostly to corporate users.

If sites implement their own automatic CDN systems, does Photon interfare with that?

**Comment by simison** [comment]
Photon doesn't pick full-width images in Gutenberg: https://github.com/Automattic/jetpack/issues/10984

**Comment by enejb** [comment]
> Are there concerns about privacy or the other reasons sites may disable photon?
cc: @jeherve I think photon is pretty much a requirement for tile galleries. No?

**Comment by simison** [comment]
> > Are there concerns about privacy or the other reasons sites may disable photon?
>
> cc: @jeherve I think photon is pretty much a requirement for tile galleries. No?

They are for the module; they don't technically have to be for the block.
