### ISSUE TITLE
Sidebar: Notice hidden behind sidebar

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#295]
After confirming my email address for a new WordPress.com account, the **is-success** notice was partially hidden behind the sidebar.

<img width="1416" alt="screen shot 2015-11-20 at 17 55 14" src="https://cloud.githubusercontent.com/assets/2998162/11307412/e6cf6964-8faf-11e5-8fbb-6cae187f288b.png">

As in #214, the dismiss button was also misaligned.

**Comment by lancewillett** [comment]
This has been fixed in subsequent changes to Calypso notices.
