### ISSUE TITLE
Gutenlypso: inline help popup links

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29502]
Most of the inline links open in a popup. For example:

<img width="773" alt="inline-popup" src="https://user-images.githubusercontent.com/1182160/50092916-950e0600-020f-11e9-9b53-a76064365224.png">

However “Inviting Contributors, Followers and Viewers” opens the help document in a new tab, and this can cause weird flow or losing the draft that is currently being worked on.

**Comment by arunsathiya** [comment]
>However “Inviting Contributors, Followers and Viewers” opens the help document in a new tab
Noting that this happens on Calypso editor as well, and is not limited to Gutenlypso.
