### ISSUE TITLE
[Classic Bright] - Update link color to `color-primary`

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29518]
Update color for all links to `color-primary`

<img width="1479" alt="screen shot 2018-12-17 at 6 19 12 pm" src="https://user-images.githubusercontent.com/9257264/50121966-94359e00-0228-11e9-9037-0cc05f4ce19f.png">

**Comment by blowery** [comment]
I added a `--color-link` with `--color-link-dark` and `--color-link-light` for this purpose. Just in case we decide we want to divorce link color from primary in some themes.

**Comment by blowery** [comment]
I noticed that a lot of the reader links set the color even though they should be able to just pick it up via the cascade. It would save us some bytes to go through and remove all the places where we just set it to primary...

**Comment by flootr** [comment]
addressed in #29574 and #29536
