### ISSUE TITLE
[Classic Bright] - Update selected state and hover state of toggle button in signup

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29517]
Update selected state of toggle button in signup from `color-accent` to `color-primary`.

<img width="1476" alt="screen shot 2018-12-17 at 6 02 48 pm" src="https://user-images.githubusercontent.com/9257264/50121389-a0b8f700-0226-11e9-90ca-7f25699c41f9.png">

Update hover state of toggle button from old blue to [TBD @drw158]

<img width="1473" alt="screen shot 2018-12-17 at 6 08 28 pm" src="https://user-images.githubusercontent.com/9257264/50121433-c6460080-0226-11e9-9602-0f40548cbc75.png">

**Comment by flootr** [comment]
this is already fixed by #29454
