### ISSUE TITLE
[Classic Bright] - Update hover state color for contained button in sign up

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29516]
Update hover state color for contained button in sign up from blue to [TBD per @drw158 ]

<img width="1474" alt="screen shot 2018-12-17 at 5 41 03 pm" src="https://user-images.githubusercontent.com/9257264/50121008-6bf87000-0225-11e9-8186-f7cb11da67fa.png">

This only appears to be happening on this screen.

**Comment by flootr** [comment]
fixed via #29443
