### ISSUE TITLE
Gutenberg: Post draft lost if created after switching from block editor to classic

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#29528]
#### Steps to reproduce
1. On a site that's opted in to Gutenberg, create a new post at My Site ->Blog Posts ->Add
2. Without adding any content, use the options menu to switch back to the Classic Editor
3. Note the post now has the title "Auto Draft"
4. Add content to the post, and update the title
5. Preview the post
6. Make sure the autosave indicator shows as "Saved" and exit the editor.
7. Go to My Site ->Blog posts ->Drafts to continue editing the draft.

#### What I expected
When clicking Preview to see a preview of the content I've added thus far.

When visiting the drafts screen to see the post listed and to be able to continue editing it.

#### What happened instead
The Preview shows an `Oops! That page can’t be found` error.

The post does not appear in the list of draft posts in either Calypso or WP-Admin, so there's no way to continue editing the post.

If I publish the post before leaving the editor it does appear everywhere it should, though.

#### Browser / OS version
n/a

#### Context / Source

Reported via the [WordPress.com forums](https://en.forums.wordpress.com/topic/block-editing-2/page/2/#post-3235942).

**Comment by arunsathiya** [comment]
I can confirm that this is still an issue. Here is a [video](https://cloudup.com/caMu3MOla7P) showing this behaviour.

**Comment by sarahfg** [comment]
The user has written us to say this doesn't just happen with a draft.

They say they did publish their drafts and the website has reverted to an old version (as shown
proved by the internet archive snapshot https://web.archive.org/web/20190109221006/https://freeforallfilms.org/  they sent). They say they lost all of the new, published edits to the website that they made after switching to the block editor.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
