### ISSUE TITLE
[Classic Bright] - Updates to "add email page" in checkout

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29521]
Update text color of outlined button from `color-accent` to `color-text-subtle`

Update copy from `color-accent` to `color-primary`

<img width="1481" alt="screen shot 2018-12-17 at 6 38 52 pm" src="https://user-images.githubusercontent.com/9257264/50122611-60a84300-022b-11e9-8572-fb055c57f75a.png">

**Comment by flootr** [comment]
fixed via #29533
