### ISSUE TITLE
Post Editor Window

### ISSUE THREAD

**Issue by beaucollins** [Automattic/wp-calypso#2953]
For the [desktop app](/automattic/wp-desktop) it would be useful to be able to open calypso in a mode that is dedicated to editing a single page/post and hide or remove all other UI/navigation.

This would allow the desktop app version to emulate a multi-window experience similar to native document editing apps.

There are at least two different ways we could approach this:
1. Render the entire calypso component graph and add the ability to hide the toolbar and sidebar
2. Create a new page that only renders the page-editor and necessary controls

**Comment by rachelmcr** [comment]
I'm closing this issue as it seems to have been addressed in https://github.com/Automattic/wp-calypso/pull/20326, which will land in the desktop app soon.

#bug-scrub #pre-gutenburg-bug-purge
