### ISSUE TITLE
Gutenlypso: Page Parent + Page Templates not showing up

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#29542]
In the block editor the Parent Page and Page Templates options don't show up.

<img width="689" alt="screenshot 2018-12-18 at 14 15 21" src="https://user-images.githubusercontent.com/4389/50156568-648da100-02cf-11e9-9fc1-83a088e5283e.png">

1. Edit or Create a Page with available Templates in Gutenlypso Editor
2. Open "Page Attributes" in the "Document" sidebar
3. Notice neither Page Templates nor Parent Page dropdowns show up

Note: the controls show up in Gutenberg / WP Admin.

**Comment by folletto** [comment]
Note that regarding "Page Templates" it seems it was an issue with the previous editor too, see: https://github.com/Automattic/wp-calypso/issues/28808

**Comment by kwight** [comment]
@folletto do you know what the active theme was in this case?

**Comment by folletto** [comment]
Field Guide.

**Comment by kwight** [comment]
Oooooooh! Interesting.
