### ISSUE TITLE
Jetpack: Add "Performance" tab after "General" settings tab

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#29545]
We've recently added a "Performance" section to the Jetpack settings within wp-admin and are looking to maintain consistency with the IA in calypso as well, for Jetpack customers.

Original issue: https://github.com/Automattic/jetpack/issues/10550
PR for /wp-admin/ changes: https://github.com/Automattic/jetpack/pull/10941

Currently:
**Calypso**
![screen shot 2018-12-06 at 2 05 32 pm](https://user-images.githubusercontent.com/214813/49606112-73379800-f960-11e8-8002-fdb26761d8f6.png)

Proposed:
Jetpack Free & Professional views

![jetpack free - calypso](https://user-images.githubusercontent.com/214813/49606223-c7427c80-f960-11e8-9a21-c50069314cca.png)
![jetpack pro - calypso](https://user-images.githubusercontent.com/214813/49606224-c7427c80-f960-11e8-90b2-5f97de51c95d.png)

cc @rickybanister @joanrho @keoshi

**Comment by keoshi** [comment]
I'm on this, but will pass it along to a developer if I hit a wall.

**Comment by keoshi** [comment]
This is ready for review on https://github.com/Automattic/wp-calypso/pull/29597
