### ISSUE TITLE
'Start using the Reader' button is not clickable on mobile 

### ISSUE THREAD

**Issue by Stojdza** [Automattic/wp-calypso#29553]
#### Steps to reproduce
1. Starting at URL: (screensize: mobile) https://wordpress.com/start/reader/reader-landing/en
2. Try to click on 'Start using the Reader' button on top of the screen

#### What I expected
To see Sign up page

#### What happened instead
Nothing, button is not clickable

#### Screenshot / Video
<img width="432" alt="screen shot 2018-12-18 at 17 32 40" src="https://user-images.githubusercontent.com/7116222/50168114-f5be4100-02ea-11e9-8cab-5fb6be853660.png">

@sixhours After merging https://github.com/Automattic/wp-calypso/pull/29508 our tests caught bug on this screen. Test execution is [here](https://circleci.com/gh/Automattic/wp-e2e-tests/25274), Reader failed test is first in the list

**Comment by sixhours** [comment]
Lookin'!

**Comment by obenland** [comment]
![image](https://user-images.githubusercontent.com/1398304/50169694-f16e3580-02a2-11e9-831e-095f33ad09e5.png)

This div prevents me from switching tabs on the plan selection page
