### ISSUE TITLE
Gutenlypso: blank lines (blank block) get stripped away

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#29560]
<img width="683" alt="screenshot 2018-12-18 at 19 32 54" src="https://user-images.githubusercontent.com/4389/50174954-de3b8400-02fb-11e9-83c6-f3f6718188ce.png">

1. Make a new post (or edit) in Gutenlypso.
2. Add a new Paragraph block, add a single space in it
3. When saving, the paragraph is gone

In Gutenberg WP Admin, the space makes the paragraph to persist, keeping a blank line when published.
Gutenlypso should preserve the blank line too.

**Comment by gwwar** [comment]
Fixed by the new integration.
