### ISSUE TITLE
Gutenlypso: blank screen in older Firefox versions

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29589]
Coming from a user report:

`Firefox 48.0.2`
`Mac, OS X, 10.7.5`

User says they tried all browser diagnostics (clear cache, updating browser as far as they could), and nothing would get their post editor to load. Only shows a blank white screen.

I'm not bumping the priority on this since this Firefox version is more than 2 years old and updating the browser should be advised first.

**Comment by gwwar** [comment]
If I recall, browser support is only last 2 major versions. Firefox latest is 64, and should have auto updates enabled by default. Closing this one out.
