### ISSUE TITLE
[Classic Bright]: tag fade in reader look off

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#29581]
View the Reader sidebar in Classic Bright with added tags:

<img width="300" alt="screenshot 2018-12-19 at 08 29 52" src="https://user-images.githubusercontent.com/9202899/50205398-5cce0b00-0368-11e9-85da-59cbf65d54d8.png">

**Comment by frontdevde** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/29591
