### ISSUE TITLE
Gutenlypso: Gutenberg-composed emails show HTML tags as well

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29587]
**Steps to reproduce**

1. Start with a WordPress.com site
2. Enable Email post changes from Settings > Email post changes under /wp-admin dashboard
3. Update a published/draft post/page using the new WordPress Editor/Gutenberg
4. Look at the email sent to the subscribers

**What is expected**

The email shows only the content, in proper format, as in the case of classic editor

**What happens instead**

The email shows the HTML tags as well as shown here - ​https://cloudup.com/cYfoevfX1hL

**Extra notes**

On testing with the classic editor, it appears fine. The issue is only with the posts with the new WordPress Editor - ​https://cloudup.com/cjxo60v2ZfJ

**Comment by arunsathiya** [comment]
1655892-zen

**Comment by kwight** [comment]
This is no longer valid, likely due to deploying #31196 .

<img width="997" alt="Screen Shot 2019-03-12 at 2 49 27 PM" src="https://user-images.githubusercontent.com/349751/54238575-11924700-44d6-11e9-98ad-06ae4442fd8b.png">
