### ISSUE TITLE
Checkout: Break credit card number into groups of 4 digits

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#29593]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/
2. Navigate to a purchase and add or edit a credit card
3. Enter a card number

#### What I expected
Expected for the card number to be broken out into groups of four digits for easy reading.

#### What happened instead
All the digits are grouped together with no spaces, making it easy to type an incorrect number.

#### Screenshot / Video
<img width="374" alt="credit" src="https://user-images.githubusercontent.com/30727666/50214951-8a6f8000-0379-11e9-816f-01a569008884.PNG">

#### Context / Source
Resulted from a user complaint at #1656404-zen.

**Comment by southp** [comment]
I've confirmed this has been fixed by https://github.com/Automattic/wp-calypso/pull/34963, so I'm closing this.
