### ISSUE TITLE
Business upgrade nudge: Direct to Business type and not Personal type plans

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29603]
#### Steps to reproduce 

- Get a free WordPress.com site
- Visit https://wordpress.com/settings/general or https://wordpress.com/settings/traffic
- Click on the WordPress.com Business upgrade nudge available here

#### What is expected 

Takes one to `http://calypso.localhost:3000/plans/{site}?customerType=business` to show the WordPress.com Business plan

#### What happens instead 

Takes one to `http://calypso.localhost:3000/plans/{site}?feature=search&plan=business-bundle` which does not show the WordPress.com Business plan. It only shows the Personal-type plans, which are `Blogger`, `Personal` and `Premium`.

**Related**: Tabbed navigation originally proposed on https://github.com/Automattic/wp-calypso/pull/27125 and visual changes to the two tabs on https://github.com/Automattic/wp-calypso/pull/29424

// cc @jancavan @adamziel I am unsure whom to direct this idea to, but since you have been involved in these two PRs, I am tagging you.

**Comment by jancavan** [comment]
Thanks for reporting this. Yes, I think users should be defaulted to the Business plan after clicking on that Business plan upsell. cc @sararosso
