### ISSUE TITLE
[Classic Blue] - Hover on filters in activity turns white

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29609]
If I add filters, then hover over the “x” to remove the filter, the background turns white:

<img width="700" alt="screen-shot-2018-12-19-at-9 34 43-am" src="https://user-images.githubusercontent.com/9257264/50230292-5a74ac80-037a-11e9-935d-b437d5642309.png">

**Comment by flootr** [comment]
fixed by  #29632
