### ISSUE TITLE
[Classic Bright] - Color contrast too low on hover state in top app bar (masterbar)

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29608]
Color contrast too low on hover state in top app bar (masterbar)

<img width="840" alt="screen shot 2018-12-19 at 10 31 24 am" src="https://user-images.githubusercontent.com/9257264/50229948-84799f00-0379-11e9-9a00-59e6adbe30c4.png">

@drw158 how should we proceed?

**Comment by drw158** [comment]
Not a huge problem imo since it passes in the normal state. We could put it in a backlog, or come up with an alternate hover state for the top app bar. We could use primary-dark instead of primary-light.

**Comment by frontdevde** [comment]
@drw158 The issue with using `--color-primary-dark` would be that the hover state then looks identical to the selected state:

`--color-primary-dark`
<img width="442" alt="screen shot 2018-12-20 at 18 54 33" src="https://user-images.githubusercontent.com/1562646/50280915-c8a79500-0488-11e9-978f-9268960a7374.png">

Would `--color-primary-900` work?

`--color-primary-900`
<img width="483" alt="screen shot 2018-12-20 at 18 53 28" src="https://user-images.githubusercontent.com/1562646/50280927-d2c99380-0488-11e9-92d8-1e3d6a092380.png">

**Comment by drw158** [comment]
You're right. Actually, now that we have more shades available to use in css vars, let's use `--color-primary-400` for the background hover. The effect will look the same, but this will pass contrast.

<img width="151" alt="screen shot 2018-12-20 at 3 52 33 pm" src="https://user-images.githubusercontent.com/618551/50312851-4a8ac480-046f-11e9-9b64-16f0323936f7.png">

**Comment by torres126** [comment]
Since there hasn't been much activity here for a few weeks, I'd like to do a PR for this if that's okay? Just noting since there's an assignee, but I can't find a branch which fixes this yet and this seems a bit quiet currently. :)
