### ISSUE TITLE
[Classic Bright] - Update colors in checklist navigation

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29617]
Update colors in checklist navigation.

Update title and steps text to: `color-primary`
Update badge to: `color-accent`

<img width="330" alt="screen-shot-2018-12-19-at-10 39 54-am" src="https://user-images.githubusercontent.com/9257264/50234338-6dd84580-0383-11e9-98da-0f7683a335d7.png">

**Comment by flootr** [comment]
fixed in #29654
