### ISSUE TITLE
[Classic Blue] - Update notification badge from blue to `color-accent`

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29612]
Update notification badge from blue to `color-accent`

<img width="284" alt="screen-shot-2018-12-19-at-9 38 35-am-1" src="https://user-images.githubusercontent.com/9257264/50230795-62811c00-037b-11e9-8bf6-3d5ca3391f0e.png">

**Comment by flootr** [comment]
That's _Classic Blue_, isn't it? That'd mean that it should already be the `-accent` color. Asking @drw158 for design feedback on which color we should use here.

**Comment by flootr** [comment]
It seems like we have the same issue here #29606

**Comment by drw158** [comment]
Technically, yes for classic blue we use `blue` as the accent color and primary color to remove all pink colors. Currently, we don't have an easy way to target all "badge" elements like this one. If we update the accent color to something like orange, then every accent element will get orange, like buttons for example.

@flootr We could just do this one bell icon dot ( I think we have that variable in the scheme file? ) and change it to pink. But, this will also come up for other badge elements too as seen in #29606

**Comment by flootr** [comment]
@drw158 you mean to change it to pink for _Classic Blue_ as well?

**Comment by blowery** [comment]
The way I'm reading this, we should _not_ use --color-accent for the bell badge and we may want a different variable to indicate "new" in general?

Possible names (assume `--color-` prefix):
badge
notification-badge
attention
...?

**Comment by drw158** [comment]
@flootr Yes sorry, I'm only referring to Classic Blue.

I hesitate to add another variable that could be unknowingly misused in the future. I think having one for this badge color goes more detailed than we want. I'm hoping this is just an exception for Classic Blue. Can we fix just this bell icon color only for Classic Blue for the public launch? If we find we need a new variable after, then we can see about it then.

**Comment by flootr** [comment]
Makes sense @drw158 thanks for clarification

**Comment by flootr** [comment]
fixed in #29682
