### ISSUE TITLE
[Classic Bright] Update FAQ links to blue in the Plans tab

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29619]
The links in the FAQ for the plan page appears to be in pink at the moment. Given that this is a hyperlink, it should be in blue instead. p58i-7ww-p2 #comment-40815

![screenshot 2018-12-19 at 21 44 23](https://user-images.githubusercontent.com/18581859/50234857-9cced580-03dc-11e9-8492-7f87fce2013f.png)

**Comment by flootr** [comment]
fixed in #29653
