### ISSUE TITLE
[Classic Bright] - Update link hover color in /help from ~color-accent` to `color-primary`

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29615]
Update link hover color in /help from ~color-accent` to `color-primary`

<img width="762" alt="screen-shot-2018-12-19-at-10 13 37-am" src="https://user-images.githubusercontent.com/9257264/50232997-711e0200-0380-11e9-8c1d-2228a88bc12e.png">

**Comment by flootr** [comment]
fixed in #29656
