### ISSUE TITLE
[Classic Bright] - Drafts popover using old grays

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29611]
Drafts popover using old grays

<img width="300" alt="screen-shot-2018-12-19-at-9 37 09-am" src="https://user-images.githubusercontent.com/9257264/50230460-b50e0880-037a-11e9-9905-d1b39f42a450.png">

**Comment by frontdevde** [comment]
@cburton4 Could you clarify what exactly we want to change here? Thank you!

**Comment by flootr** [comment]
I think it's replaced old gray values `$gray`, `$gray-dark`, etc with the newer ones according to the mapping chart @drw158 created. It could be that some of those values have already been migrated by #29636 and #29634

**Comment by drw158** [comment]
Here's the latest:

<img width="377" alt="screen shot 2018-12-20 at 3 54 10 pm" src="https://user-images.githubusercontent.com/618551/50312956-8aea4280-046f-11e9-9cac-8e9155d1c0e1.png">

looks like the "see all" background is still using an old gray

**Comment by flootr** [comment]
I think color-wise this should be fixed by #29897. Added a PR which replaces the SASS var with their corresponding CSS var at https://github.com/Automattic/wp-calypso/pull/29977

**Comment by flootr** [comment]
fixed by #29897 and #29977
