### ISSUE TITLE
Color theming: Nudge block should use new plan colors

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#29628]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/upgrade-nudge

These nudges are using the semantic colors incorrectly and should be using the plan colors as shown on the Plans page. The `plan` prop is required, so we should be able to map each plan to a color. And we shouldn't need a default color.

![screen shot 2018-12-19 at 11 28 19 am](https://user-images.githubusercontent.com/618551/50236915-3f596b00-0381-11e9-95ab-b8d3bad83481.png)

![screen shot 2018-12-19 at 11 21 14 am](https://user-images.githubusercontent.com/618551/50236814-f73a4880-0380-11e9-88d8-ceaa3034c291.png)

**Comment by flootr** [comment]
@drw158 I'm unsure about how we want to update the `<UpgradeNudge ... />` component. It seems to me that this component is only used for _Premium_ plans (at least this part is hard-coded in the component).

The plan page uses `--color-warning` as well for the border below the plan header.

<img width="362" alt="screenshot 2019-01-18 at 10 25 36" src="https://user-images.githubusercontent.com/9202899/51378021-92534900-1b0c-11e9-8708-3730c17b6ea9.png">

So I think what we'd need to do is to update both the `<UpgradeNudge />` component as well as the plans page to use the new plan colors?

There seems to be different components used for this case e.g. there's a `<Banner />` component (https://wpcalypso.wordpress.com/devdocs/design/banner) used in the Activity Log which already comes with plan colors. [It's using `$muriel-*` colors directly](https://github.com/Automattic/wp-calypso/blob/master/client/components/banner/style.scss#L13-L47) so it probably makes sense to define them as CSS custom props as well.

One last question, what color would replace `$alert-purple` which seems still to be used as color for the business plan (at least for the `<Banner />`) component.

**Comment by flootr** [comment]
thanks @drw158 👍  - I think we need to define plan colors for Jetpack as well
