### ISSUE TITLE
[Classic Bright] - Update information notices on updates

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29620]
Update information notices on updates

Update from yellow to `color-accent`

<img width="773" alt="screen-shot-2018-12-19-at-19-dec-10 54 53" src="https://user-images.githubusercontent.com/9257264/50235141-336fa800-0385-11e9-849f-b0cd17998ceb.png">

**Notice color assignment:**
Gray – for a notice with no status
Pink – for a notice with information status
Green – for a success notice
Yellow – for a warning notice
Red – for an error notice

**Comment by drw158** [comment]
In this case, let's do `no status`. I believe our naming of `info` status is misleading; it should really be `primary` or something like that.

**Comment by flootr** [comment]
@drw158 could you please clarify which colors we should use for which status? I'm not sure I understand your comment.

**Comment by drw158** [comment]
For this particular notice in the plugins section I think we should change the notice to 'no status'. I believe this is just the default empty status.

Reason is because the notices in the screenshot should not be yellow because they don't really indicate a warning.

**Comment by flootr** [comment]
@drw I'm a bit confused on what needs to be done here. Do we change colors for different types of notices or do we change which one we use for available plugin updates or both?

**Comment by flootr** [comment]
ping @drw158

**Comment by torres126** [comment]
I can take this one if you don't have time. :)
