### ISSUE TITLE
[Classic Bright] - Remove yellow background on pending posts

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29626]
Remove yellow background on pending posts.

Update to white background color. Not sure of the specific semantic name.

<img width="773" alt="comments_ _chroni_ca_ _wordpress_com" src="https://user-images.githubusercontent.com/9257264/50236478-826b0c80-0388-11e9-97f8-e61d63355ed8.png">

**Comment by drw158** [comment]
Yes, to clarify: Remove the light yellow background on the comment card so that it's white instead (--color-surface?)

**Comment by flootr** [comment]
fixed in #29649
