### ISSUE TITLE
[Classic Bright] - Update link hover color

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29622]
Have gotten feedback that the link hover color is hard to read. Let's try darkening this to 400.

@drw158 should we remove hover color altogether? There doesn't seem to be any consistency in how links are treated across the product.

<img width="362" alt="screen-shot-2018-12-19-at-10 22 28-am" src="https://user-images.githubusercontent.com/9257264/50235487-feb02080-0385-11e9-9782-d694903768dc.png">

**Comment by drw158** [comment]
If the link is `500` we can try darkening the link to `600` or `700` on hover. Maybe that should be the default hover style for links.
