### ISSUE TITLE
Signup: Log the user in without redirecting through `wp-login.php`

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#2963]
Currently, at the end of the signup flow, the user is logged in by [POSTing to `wp-login.php`](https://github.com/Automattic/wp-calypso/blob/master/client/signup/wpcom-login-form/index.jsx#L170). The user is then redirected back to Calypso.

The bearer token is obtained during signup, so we don't need to redirect the user through `wp-login.php` at all. Instead, we can pass it to [`OAuthToken#setToken`](https://github.com/Automattic/wp-calypso/blob/master/client/lib/oauth-token/index.js#L24), which will save it in a cookie. We need to:
- Dispatch [`RECEIVE_AUTH_LOGIN`](https://github.com/Automattic/wp-calypso/blob/master/client/lib/oauth-store/actions.js#L25) with the token when it [appears in the signup](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/flow-controller.js#L128).
- Make it possible to set a different `maxAge` here, and use whatever is the default in `wp-login.php`.
- Remove the [previous solution](https://github.com/Automattic/wp-calypso/blob/master/client/lib/wpcom-undocumented/index.js#L70) to this problem.

**Comment by scruffian** [comment]
We need to make changes to OAuth more broadly before we can address this, see p4TIVU-2Xj-p2.
