### ISSUE TITLE
Gutenlypso: Classic block fixed height

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29645]
The height of the Classic block takes too much space even when there is not enough content that requires it. This can be reproduced by inserting the empty Classic block in Gutenlypso.

![download 1](https://user-images.githubusercontent.com/1182160/50256317-09a29980-03f6-11e9-8298-c5f664f853dd.gif)

**Comment by lakellie** [comment]
Reproduced in both Safari and Chrome.
User reported in #1658088-zen
