### ISSUE TITLE
More Tag option not working on Classic block

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#29643]
#### Steps to reproduce
1. Add a Classic block 
2. Add the "more tag" between 2 paragraphs
3. Save and Update
4. Check post from Blog page, the tag is not applied
5. Check post individually, there is a broken "read more" reference (screenshot below)

#### What I expected
The more tag should be added and should be working (testing from an archive page or blog page)

#### What happened instead

The more tag is not added, not working, and there is a broken "read more" reference  as seen in the following  screenshot:
![screen shot 2018-12-19 at 18 45 16](https://user-images.githubusercontent.com/23703267/50252722-4357ae00-03be-11e9-8c8d-89113b5ce5e6.png)

**Comment by lizswafford** [comment]
Also reported on 1664558-zen

**Comment by ChrissiePollock** [comment]
Also reported on #1665327-zen.

**Comment by gwwar** [comment]
In Gutenlypso the following HTML is stored on save, instead of a `<!--more Keep on reading!-->` tag:
```
<p>Before More Tag</p><p><img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-wp-more="more" data-wp-more-text="" class="wp-more-tag mce-wp-more" title="Read more…" data-mce-resize="false" data-mce-placeholder="1"></p><p>After More Tag</p>

<!-- wp:paragraph -->
<p>A paragraph block</p>
<!-- /wp:paragraph -->
```

**Comment by gwwar** [comment]
Looking at code, we'll probably see a similar breakage for nextpage:

https://github.com/Automattic/wp-calypso/blob/fa549bef43a66b55e5984f09df7555945b88c106/client/components/tinymce/plugins/wpcom/plugin.js#L73-L93

**Comment by gwwar** [comment]
The above event fires correctly, but modifying `e.content` to any value doesn't appear to change content.

**Comment by juliasydnor** [comment]
reported in #9153359-hc

**Comment by gwwar** [comment]
Verified that we're creating a new editor instance in the Calypso Classic block and reusing the editor instance in the core Classic block.

**Comment by nerdysandy** [comment]
Reported on 1680893-zen

**Comment by kylemcph** [comment]
Also reported in #2752518-HC
