### ISSUE TITLE
[Classic Bright] Pre-publish confirmation on Calypso editor should be in pink

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29647]
When using the Calypso editor to publish a new blog post, the first Publish button appears in pink while the second is in green.

The pre-publish confirmation should be in pink as well.

<img width="1248" alt="screenshot 2018-12-19 at 22 55 53" src="https://user-images.githubusercontent.com/18581859/50257623-f4436480-0421-11e9-823e-ce7bdb757b85.png">
<img width="1235" alt="screenshot 2018-12-19 at 22 55 44" src="https://user-images.githubusercontent.com/18581859/50257631-002f2680-0422-11e9-9de6-3902390f51a4.png">

p58i-7ww-p2 #comment-40851

**Comment by flootr** [comment]
fixed by https://github.com/Automattic/wp-calypso/pull/29648
