### ISSUE TITLE
Editor: Contributors can publish their own posts to admins and editors.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#29644]
Contributors should not be able to publish posts; they are to submit for review, and then an editor or admin needs to publish. However, if a contributor selects "admins and editors" from the Privacy dropdown, they are given the option to publish immediately (bypassing the required approval from another user). While there's no risk of a contributor publishing a _public_ post, we should still bring Calypso's behaviour back in line with core WordPress: regardless of privacy settings, contributors cannot publish their own posts.

<img width="999" alt="screen shot 2018-12-19 at 3 22 47 pm" src="https://user-images.githubusercontent.com/349751/50254428-d84cae00-03a2-11e9-81c8-2b47db628229.png">

**Comment by davemart-in** [comment]
Yep, this issue should go away once the Calypso editor is retired - which is currently in progress..

**Comment by davipontesblog** [comment]
Thanks @davemart-in, I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
