### ISSUE TITLE
Gutenlypso: SyntaxHighlighter Code block not available

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#29641]
SyntaxHighlighter Code block is available in Calypsoify/wp-admin but it's not included in Gutenlypso.

**Comment by catrymer** [comment]
I had a user asking about this in chat today in #8621059-hc

**Comment by rossanafmenezes** [comment]
Exact same issue is happening for the File block. It's available on WP-admin but not on Calypso. 

zd-1659516

**Comment by arunsathiya** [comment]
1696776-zen

**Comment by KokkieH** [comment]
Another request in https://en.forums.wordpress.com/topic/block-type-to-publish-source-code-using-syntaxhighlighter-evolved-plugin/

**Comment by retnonindya** [comment]
10580177-hc

**Comment by codebykat** [comment]
This is available now that we've updated the underlying integration.
