### ISSUE TITLE
Gutenlypso: Latest post block not saving options

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#29669]
#### Steps to reproduce

On a site which has some posts already published.

1. Starting at URL: https://wordpress.com/block-editor/page/
2. Create a new page
3. Add the Latest Posts block
4. Edit the block settings (change category, or order, or number of posts)
5. Publish the page
6. Edit the page the page in Gutenlypso

#### What I expected

I expect the settings for the block to remain set as they were when I published the page. 

#### What happened instead

The settings aren't saved and instead they are back to the default block settings. When you view the page it shows the latest posts block it displays posts based on the default block settings, not the ones saved when publishing the page.

This only applies to Gutenlypso not the WP Admin version.

#### Browser / OS version

Firefox 64 / Mac OS Mojave 10.14.1

#### Context / Source

Customer reported the original issue and then performed some further testing.

#user-report

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by vindl** [comment]
Thanks for the report! This is a special case of a generic issue with Dynamic blocks that we are already tracking here https://github.com/Automattic/wp-calypso/issues/27963. Closing this one as duplicate.

**Comment by arunsathiya** [comment]
#8935567-hc - cc @mdrockwell
