### ISSUE TITLE
Related Posts: Thumbnails not shown on frontend

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#29662]
#### Steps to reproduce
1. On a site with a few exisiting posts with featured images (thumbnails), start writing a new post (in Gutenlypso, or WP.com wp-admin)
2. Add a Related Posts block.
3. Publish the post, view it on the frontend

#### What I expected

Thumbnails to be show for related posts

#### What happened instead

Thumbnails aren't shown

#### Context / Source
This doesn't seem to be specific to the Related Posts block -- the legacy Related Posts feature seems to have the same issue.

/cc @tyxla

**Comment by tyxla** [comment]
I think this is also related with #29782 and #27786 - all of them feel like they're caused by stale cache.

**Comment by aldavigdis** [comment]
This one can be closed after the merger of https://github.com/Automattic/jetpack/pull/11220 :)
