### ISSUE TITLE
Framework: implement redux persistence for state/plugins

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#2967]
Implement persistence for state/plugins:
- [ ] You'll need to create a schema to represent what valid state looks like
- [ ] handle SERIALIZE action in reducer to return a plain js object to persist
- [ ] handle DESERIALIZE action in reducer. If state is valid, return state and initialize with immutable js if needed. If data is invalid, return the default initial state.
```
return isValidStateWithSchema( state, schema ) ? state : defaultState;
```
- [ ] Tests for serialize, deserialize, and invalid data cases

See: #2754

**Comment by rralian** [comment]
@gwwar what should we do with this considering we're moving on to plans work?

**Comment by gwwar** [comment]
Sorry, I can close out these stub issues.

**Comment by rralian** [comment]
No worries, I'm just doing some cleanup.
