### ISSUE TITLE
[Classic Bright] - Update banner that displays on mobile web

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29683]
Update banner that displays on mobile web to give the call to action more hierarchy and to make the text more legible.

Update the button to a primary contained button (pink)

Update the text to white.

![img_8381](https://user-images.githubusercontent.com/9257264/50305583-435cba00-0461-11e9-8ed5-64af7f696343.PNG)

**Comment by flootr** [comment]
fixed in #29708
