### ISSUE TITLE
Color Schemes: activity stream uses old pale gray

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#29688]
#### Steps to reproduce
1. Starting at URL: `activity-log/[site].wordpress.com`

You can barely see it, but there is a pale blue background next to a pale gray background behind the date, time, and icon.

<img width="213" alt="screen shot 2018-12-20 at 2 03 20 pm" src="https://user-images.githubusercontent.com/618551/50308239-4acf9380-0460-11e9-9ed1-db9ae56ac39a.png">

**Comment by nielslange** [comment]
@blowery I'm going to hi-jack this one from you, as I just get started contributing to Calypso and this is a rather easy issue. Hope that's fine with you. 😉

**Comment by flootr** [comment]
seems fixed by #29691
