### ISSUE TITLE
Style bug: Button block styling works in Gutenberg but not live

### ISSUE THREAD

**Issue by kathleenjross** [Automattic/wp-calypso#29686]
#### Steps to reproduce
1. Starting at URL: https://allabastro.tv/2018/12/05/matthew-allabastro-licensed-realtor/
2. The "Contact Me" button is in black
3. However, in Gutenberg, the user tried to make the button red:

![screen shot 2018-12-20 at 1 29 20 pm](https://user-images.githubusercontent.com/14097527/50307152-920c5300-0465-11e9-9e14-ca8e412ead11.png)

User has the Twenty Seventeen theme and I was able to reproduce this on my own.

#### What I expected

Expected behavior is the button block color styling to work without resorting to CSS.

Reached out in Slack in #guternberg-on-dotcom: https://a8c.slack.com/archives/CBTN58FTJ/p1545332299528900. 

#user-report #twenty-seventeen #button-block

**Comment by kathleenjross** [comment]
Related to follow-up ticket here: https://woothemes.zendesk.com/agent/tickets/1659822

**Comment by edwinho89** [comment]
Similar issue reported on https://woothemes.zendesk.com/agent/tickets/1664118

From what it seems, the CSS on the button, `.wp-block-button .wp-block-button__link` is not identical compared to the block editor on `.wp-block-button__link` when on block editor.

**Comment by mishivee** [comment]
Do we have any update for the user?

**Comment by zdenys** [comment]
#1659822-zen In visiting the page https://matthewallabastro.com/2018/12/05/matthew-allabastro-licensed-realtor/ now I can see the button being red (and not black anymore). Was it fixed somehow?
