### ISSUE TITLE
[Classic Bright] - Update site setup checklist background color

### ISSUE THREAD

**Issue by cburton4** [Automattic/wp-calypso#29684]
Update site setup checklist background color

Update to `blue-0`

![img_8382](https://user-images.githubusercontent.com/9257264/50306678-2970a680-0464-11e9-8e7b-d370fe83100c.PNG)

**Comment by nielslange** [comment]
This sounds like the perfect issue for me to get started with contributing to Calypso. Please let me do create the PR for this, if possible. 😉

**Comment by flootr** [comment]
@nielslange go ahead 👍

**Comment by nielslange** [comment]
@flootr Just created my first PR for Calypso! 🤗Feel free to review my PR via #29737.

**Comment by flootr** [comment]
fixed in e1d8d73
