### ISSUE TITLE
Onboarding checklist: Disappears and re-appears

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/wp-calypso#29694]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day
2. Go to plugins
3. Click the back button
4. Land back on the stats page

#### What I expected
No checklist to be visible

#### What happened instead
The onboarding checklist suddenly appears

#### Browser / OS version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2)
Chrome latest version on Mac OS latest version 10.14.2 (18C54)

#### Screenshot / Video
![screenshot](https://cdn-std.dprcdn.net/files/acc_698200/QEUrQV)
Kept the window short to anonymize.

#### Context / Source

This issue was reported in 1643691-zen, and I was able to replicate this in the user's account without fail.

**Comment by jamiepalatnik** [comment]
Also reported in 8961902-hc and was able to replicate in the user's account.

**Comment by cecoates** [comment]
9081136-hc

Able to replicate. You can complete steps such as adding a favicon. It claims you're now finished. And then it just comes back stuck on that same step.

**Comment by khristiansnyder** [comment]
1712940-zen

Able to replicate and user's V2 site will not register the site tagline checklist step.
