### ISSUE TITLE
Checkout page: state validation errors

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#29701]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/checkout/{_siteSlug_}/add-support-session
2. Make sure that your cart has a product that has a decimal product cost. e.g. 22.5, 148.5. Else, add a product to your cart that does (it could be any product, e.g. a .ca domain product).
<img width="1098" alt="screenshot 2018-12-21 at 12 08 24 pm" src="https://user-images.githubusercontent.com/1269602/50328472-3c917e00-0519-11e9-8e36-c61caddf02ee.png">

3. Check browser console, shows a bunch of state validation errors because `product.cost` in the state tree is defined to be an integer.
<img width="361" alt="screenshot 2018-12-21 at 11 47 15 am" src="https://user-images.githubusercontent.com/1269602/50328489-503ce480-0519-11e9-8b0d-91cb5ac43b34.png">

#### What I expected
1. product.cost to be a float since we have many product costs that are non-integer.

#### Note

The issue is not specific to the concierge session page, which is just one of the places where this error occurs among other places.

**Comment by travisw** [comment]
@niranjan-uma-shankar - to clarify, this doesn't seem to be specific to the concierge session page, right? Or am I mistaken? I see similar errors on other pages.

eg. on /stats/day/{_siteSlug_}
<img width="1789" alt="screen shot 2019-01-10 at 12 09 51 pm" src="https://user-images.githubusercontent.com/690843/50994355-e9d03400-14d0-11e9-8258-e63f660f4d5a.png">

**Comment by niranjan-uma-shankar** [comment]
@travisw Correct, this is not specific to the concierge session page, which is just one of the places where this error occurs.
