### ISSUE TITLE
Tiled gallery block: persist alignment during transforms

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#29704]
Alignment could persist when transforming a gallery into an image and vice-versa.

Same in Gutenberg core gallery: https://github.com/WordPress/gutenberg/pull/12242

<img width="340" alt="image" src="https://user-images.githubusercontent.com/87168/50330884-88d2c300-0505-11e9-8a0b-1b123d427d9d.png">

**Comment by sirreal** [comment]
Tiled Galleries provide center, wide and full alignments (defaulting to center):

https://github.com/Automattic/wp-calypso/blob/c96c4f63252723f8aca9c05177a45712003d2009/client/gutenberg/extensions/tiled-gallery/index.js#L111-L112

Core appears to provide [left, right, and center](https://github.com/WordPress/gutenberg/blob/88a69507e0bba453fd0f239b4be1567c94953396/packages/block-library/src/gallery/index.js#L77-L79) (the default with `{ supports{ align: true } }`).

Closing this as our alignments don't _align_ 🙈 and defaulting to `center` alignment is likely the best approach.
