### ISSUE TITLE
Tiled gallery block: styles for links in captions

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#29729]
When adding links to image captions, they're blue while other caption is white.

Against dark images, blue links don't really work.

<img width="236" alt="screenshot 2018-12-27 at 22 53 05" src="https://user-images.githubusercontent.com/87168/50507798-abc22180-0a87-11e9-9c16-49c3c643be4d.png">
<img width="603" alt="screenshot 2018-12-27 at 22 53 48" src="https://user-images.githubusercontent.com/87168/50507799-abc22180-0a87-11e9-96a0-13c26e9614a7.png">

**Comment by geekpulp** [comment]
I've never contributed to a project like this before but I wouldn't mind giving this one a crack?

**Comment by simison** [comment]
@geekpulp yay! :-) That's great to hear. I would suggest looking at issues labelled as ["good first issue"](https://github.com/Automattic/wp-calypso/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

This one is tricky as we don't have design decisions yet and we have several other things going on with Captions that we need to work on first. Thanks for the offer tho!

**Comment by geekpulp** [comment]
@simison All good. Thanks for the tip about "good first issues", I'm working on one of those right now :)

**Comment by simison** [comment]
Closing as the current block iteration doesn't have captions and this is tracked also at https://github.com/Automattic/jetpack/issues/11794
