### ISSUE TITLE
App Banner: ”Open in app” opens new post

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/wp-calypso#29734]
**Steps to reproduce:**
1. Using an iOS or Android device, log in to WordPress.com in a web browser.
2. Open a WordPress.com site which does not have Gutenberg enabled.
3. Navigate to a post and click the “edit” link.
4. Click “Open in app” in the “Rich mobile publishing” banner.

**Alternative steps to reproduce:**
1. Using an iOS device, log in to the WordPress app, connecting to a WordPress.com site.
2. Go to My Site(s), selecting a WordPress.com site which does not have Gutenberg enabled.
3. Click “View Site”. The site will load in the in-app browser (it loads in a web browser on Android).
4. Navigate to a post and click the “edit” link.
5. Click “Open in app” in the “Rich mobile publishing” banner.

**What I expected**
I expected the app to open to the post I was already editing.

**What happened instead**
The app opened, but started a brand new post.

iOS:
![iosopen](https://user-images.githubusercontent.com/15107387/50385237-44445480-06ca-11e9-8901-cde75dc3c65c.png)

Android:
![androidopennew](https://user-images.githubusercontent.com/15107387/50385241-50c8ad00-06ca-11e9-8b8c-d457bf6a078d.png)

**Tested on an iPhone SE, iOS 12.1, WPiOS 11.3.1
Tested on Nokia 2, Android 7.1.1, WP-Android 11.4**

**Comment by lancewillett** [comment]
Interesting flow find! Thanks @thehenrybyrd. CC @elibud

**Comment by elibud** [comment]
Thanks for the ping @lancewillett. @diegoreymendez can you please look into this?

**Comment by diegoreymendez** [comment]
Hey, apologies!  It seems I dropped the ball on this one for some reason.

That said given that now Gutenberg is the default editor in WP.com I'm wondering if we can close this issue.  I know there are plugins to disable it, but I'm wondering if it makes sense for us to spend time testing for external plugins.

My take is that we can probably just close this issue. (again apologies @lancewillett and @elibud  !)

**Comment by diegoreymendez** [comment]
I'm closing for now since Gutenberg is the default editor.
