### ISSUE TITLE
Gutenberg: Not loading in latest version of Google Chrome/Safari 

### ISSUE THREAD

**Issue by adamleone** [Automattic/wp-calypso#29733]
#### Steps to reproduce
1. Starting at URL: My Site > Site Pages > Edit a page
2. Switch the new editor

#### What I expected

To see the new editor.

#### What happened instead

See message "couldn't load everything - try hitting reload in your browser..."

#### Browser / OS version

71.0.3578.98
macOS 10.14.2 

#### Screenshot 

https://cld.wthms.co/tREHyT 

#### Context / Source

zen-1662526

**Comment by arunsathiya** [comment]
I don't think this is reproudicible at the moment. The new WordPress Editor/block editor/Gutenberg works fine at the moment for my on Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) and Safari Version 12.0.2 with macOS 10.14.2 - Mac OS Mojave.

There are no other major reports either, so I am going to close this one. 

@adamleone Assuming you were able to reproduce this error earlier, would you mind checking if things are fine at your end now?
