### ISSUE TITLE
App Banner: Redirection Error on Posts on iPad

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/wp-calypso#29738]
**Steps to reproduce:**
1. Using an iPad, log in to the WordPress app, connecting to a WordPress.com site.
2. Go to My Site(s), selecting a WordPress.com site which does **not** have Gutenberg enabled.
3. Click “View Site”. The site will load in the in-app browser.
4. Navigate to a post and click the “edit” link.
5. Click “Open in app” in the “Rich mobile publishing” banner.

**What I expected**
I expected the app to open to the post editor.

**What happened instead**
The browser gave a redirect error with the following text:
`Error`
`Redirection to URL with a scheme that is not HTTP(S)`

![ipadopen](https://user-images.githubusercontent.com/15107387/50396851-74d8cc80-0764-11e9-9057-bfafb02a1382.png)

Clicking “Ok” did not open the app, instead it remained in the in-browser editor.
It’s not possible to get from the app via the app banner in this case.

**Tested on an iPad 2 Air, iOS 12.1, WPiOS 11.4.1 by @rezzap**

Reported in #1663519-zen

**Comment by rachelmcr** [comment]
Closing this as resolved now that we prevent navigating into the Calypso editor from within the in-app browser.
