### ISSUE TITLE
Gutenberg + Customizer: Video Widget fails to load video when added by URL

### ISSUE THREAD

**Issue by sarahfg** [Automattic/wp-calypso#29747]
#### Steps to reproduce
1. Active/Use Gutenberg on a WordPress.com Simple Site
2. Head to the customizer > widgets > Add a Video Widget
3. Select the option `Insert from URL`
4. Paste in a URL from YouTube or Vimeo

#### What I expected

 The video to embed as usual 
![](http://cld.wthms.co/oVgPKx+)

(Image link: http://cld.wthms.co/oVgPKx )
#### What happened instead
The following error is shown `Sorry, we can’t load the video at the supplied URL. Please check that the URL is for a supported video file (.mp4, .m4v, .webm, .ogv, .flv) or stream (e.g. YouTube and Vimeo).`
![](http://cld.wthms.co/qByLvM+)

(Image link: http://cld.wthms.co/qByLvM )

#### Context / Source
Reported in #1664494-Zen
Reproduced on my own test site. If I disable Gutenberg the video embed works
Similar issue reported and fixed here: https://github.com/Automattic/wp-calypso/issues/25195
As in this reported issue if I try to embed the video through a Text Widget it works.

 #user-report if applicable.

**Comment by jamiepalatnik** [comment]
Reported here as well: 7445995-hc

**Comment by ezebecke** [comment]
Reported here: [#1724157](https://woothemes.zendesk.com/agent/tickets/1724157)

**Comment by ahmadbaig1** [comment]
Reported here for Vimeo: 1914085-zen

**Comment by arunsathiya** [comment]
This is not an issue anymore. I am able to add an YouTube video by URL option, on the `Video` widget on Customizer just fine. Could you try again with your respective sites/check with your users' on the situation, @sarahfg, @jamiepalatnik and @ezebecke?

<img width="974" alt="Screenshot 2019-04-05 at 13 43 50" src="https://user-images.githubusercontent.com/18581859/55613939-842ad580-57a9-11e9-8953-8b2995ff721d.png">

@ahmadbaig1 Your situation seems to be very different in that yours being a Vimeo block itself. Could you search for a related issue/create one afresh, please? Thanks!

**Comment by jamiepalatnik** [comment]
Works for me in my test now, thanks!

**Comment by sarahfg** [comment]
Works for me on my test site :-). I've followed up with the user that reported it letting them know it's resolved.

**Comment by arunsathiya** [comment]
That's good to know! @ezebecke, I see your ticket was in Spanish. If you could followup, that would be amazing. Thank you! 

Closing as resolved.

**Comment by ezebecke** [comment]
Thanks @arunsathiya. I have followed up with the user.
