### ISSUE TITLE
Gutenlypso: Line Break Issues for Bold & Italics on Larger Displays

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#29748]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor with a large display (desktop, for example - I tested on 1024 x 768 pixels) 
2. Create a paragraph block and start typing so that it's either bold or in italics
3. Type enough content so that there should be a line break 
4. See issue 

#### What I expected

Lines should break like they can do in the Classic Editor (or Gutenberg on wp-admin), and like how they do with the paragraph block. 

#### What happened instead

_In the editor:_

![dgsffdgsdfsgdsfg](https://user-images.githubusercontent.com/43215253/50476753-3f7cea80-09c1-11e9-872f-96768186bd49.png)

_Front end:_

![sdfgsdfgsgfsdfg](https://user-images.githubusercontent.com/43215253/50476769-4d327000-09c1-11e9-9c8a-f71eee9b61f8.png)

Note that the lines break in the middle of words in the editor, and completely overflow in the front end, despite being multiple words and not just one unreasonably long word. 

#### Browser / OS version

Mac OS X 10.6.8 using Chrome 49 

#### Context / Source

Found when writing my posts, I wanted to add a bold "Note" which I do frequently and experienced this issue whilst trying to do so.

**Comment by torres126** [comment]
I still can, yes, though it's not as major with that line.

![fhfghdfghfhgdfdhg](https://user-images.githubusercontent.com/43215253/50740735-d8dea480-11ea-11e9-9df4-696c6b222e40.png)

**Comment by arunsathiya** [comment]
Thanks! Making a guess here, but would you mind checking if this is the case with other displays as well? 

I had an unrelated issue with how images appear on Jetpack's gallery a while ago https://github.com/Automattic/jetpack/issues/11058#issuecomment-451821496 and using the display monitor's recommended resolution fixed things.

**Comment by torres126** [comment]
Can confirm that using Dev tools to adjust the screen into a smaller display fixes the issue (when typing it, doesn't fix any issues written before adjusting). :+1:

Top paragraph is written with a larger display. 

![gsdfsfdgsfdg](https://user-images.githubusercontent.com/43215253/50782527-2d902700-12a0-11e9-8b2b-9d2b485ae2e0.png)

**Comment by arunsathiya** [comment]
That is interesting. Thanks for checking, @torres126. Does this happen for specific resolutions browser widths though?

**Comment by torres126** [comment]
As in, increasing it with zoom? If so, that has no effect.

**Comment by torres126** [comment]
Closing because this isn't an issue in Gutenframe.
