### ISSUE TITLE
Editor: Classic block toolbar not fixed to top of the page on wide screens

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#29746]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Add a new Classic Block
3. Add several paragraphs of text to the block, enough that the top of the block starts scrolling off the top of the page.

#### What I expected
For the block's text formatting toolbar to remain fixed at the top of the page while the text scrolls, as happens with the block editor in WP-Admin.

![classic](https://user-images.githubusercontent.com/11873759/50436969-bb5b3200-08f0-11e9-9c96-0f81f1a6f998.gif)

#### What happened instead
The toolbar scrolls off the top of the screen, requiring one to have to constantly scroll up and down to format text lower down in the block.

![classic](https://user-images.githubusercontent.com/11873759/50436876-6d462e80-08f0-11e9-8d88-eb9c7710bf08.gif)

#### Browser / OS version
Replicated in both Firefox and Chrome on Mac OS

#### Context / Source

Reported via the [support forums
](https://en.forums.wordpress.com/topic/block-editor-3/)

**Comment by liviopv** [comment]
Also affects atomic sites: https://cld.wthms.co/T4X2tm

Reported in #1836262-zen

**Comment by obenland** [comment]
This should work now with Gutenframe (p3fqKv-6Hh-p2).
For Atomic sites I could reproduce it in wp-admin with the editor in full-screen mode. The content area seems to have a second scrollbar.

![mar-06-2019 15-54-15](https://user-images.githubusercontent.com/1398304/53922883-fe413080-402a-11e9-8ae9-b46e57401985.gif)

**Comment by kwight** [comment]
I found the sticky bar to work on JP/Atomic, but only up to ~970 width (which sounds in accordance with @obenland 's fullscreen experience). It's the `block-library-classic__toolbar` element that has the `position: sticky` property, but I can't see anything overriding it upon hitting the larger breakpoint. Maybe it has something to do with [changes to its containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/position).

**Comment by cathymcbride** [comment]
No repro - looks good one simple and atomic
