### ISSUE TITLE
Related Posts Block: Posts shown in editor differ from frontend

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#29750]
Reported by @annezazu at p1HpG7-64l-p2 #comment-29577

#### Steps to reproduce
1. In the block editor, start a new post, and insert a Related Posts block.
2. This will typically show one or two posts, often the first post that was published on the site
3. Publish the post and view it

#### What I expected

The same posts to show in the frontend that were previewed in the editor

#### What happened instead

Different posts are shown

#### Screenshot / Video

Editor:

<img width="733" alt="screen-shot-2018-12-21-at-4 41 51-pm" src="https://user-images.githubusercontent.com/96308/50478335-e4eb8a80-09d0-11e9-88c1-c2ed4bb95e78.png">

Frontend:

<img width="833" alt="screen-shot-2018-12-21-at-4 46 34-pm" src="https://user-images.githubusercontent.com/96308/50478325-dd2be600-09d0-11e9-8a16-a41a7d1b05e6.png">

#### Context / Source
The frontend generally seems to display more 'relevant' posts, so I think the editor should reflect that. I'm not sure that it's just because of caching/indexing, since the posts do show up instantly on the frontend after publishing. Whatever we're doing there to fetch related posts, we should also be doing to populate the `jetpack-related-posts` API field (possibly bypassing caching, or triggering indexing, if necessary).

**Comment by tyxla** [comment]
Initial research shows that on .com, one of the functions will fetch posts with any post status (including drafts and auto drafts), but then the next function will filter them out, leaving the public ones only. This is unexpected. I'll keep digging tomorrow.

**Comment by ockham** [comment]
Fix in D22689-code.
