### ISSUE TITLE
Tiled gallery block: converting Gallery block to Tiled gallery fails

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#29766]
Converting to Tiled gallery block ~as a contributor user~ fails.

#### Steps to reproduce
1. ~As a contributor user,~ create a new post
1. Add Gallery block:
    <img width="404" alt="screenshot 2018-12-27 at 23 35 12" src="https://user-images.githubusercontent.com/87168/50495237-83f39f00-0a30-11e9-8d12-13321ba2d015.png">

1. Attempt to convert the block to Tiled gallery block 
    <img width="406" alt="screenshot 2018-12-27 at 23 35 18" src="https://user-images.githubusercontent.com/87168/50495238-8950e980-0a30-11e9-89ef-36f458cedcbd.png">

1. Check the console for _"Uncaught TypeError: Cannot read property 'attributes' of undefined"_

**Comment by MichaelArestad** [comment]
Fails at admin level as well.

I get this error:

![image](https://user-images.githubusercontent.com/1123119/50496435-225e1100-09ed-11e9-9538-4c04ee492d8f.png)
