### ISSUE TITLE
Related Posts Block: Rendered as Grid even if set to List Mode

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#29771]
Reported at p1HpG7-64l-p2 #comment-29600:

> No matter what settings I set, I could not get List View to work. Always showed my posts in Grid View after publishing. Same results in Preview.

#### Steps to reproduce
1. In the block editor, start a new post, and insert a Related Posts block.
2. In the block toolbar, set it to list mode.
3. Publish the post and view it.

#### What I expected

The block to be rendered in list mode.

#### What happened instead

The block was rendered in grid mode.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/96308/50497719-b0141d80-0a3a-11e9-96e7-88421e3fc7d2.png)

#### Context / Source
 I've verified that the correct class is applied on the frontend (`.jp-relatedposts-list`). I think the stylesheet's [selectors](https://github.com/Automattic/jetpack/blob/8e75c3799f8e77b6f726ad46886d353225303ad6/modules/related-posts/related-posts.css#L172-L188) aren't working since they require an element with ID `#jp-relatedposts` wrapped around Related Posts. (ID based styling probably isn't a good idea here -- or anywhere really -- anyway.)

**Comment by tyxla** [comment]
Seems like we don't handle lists on WP.com the same way we do for Jetpack. Will work on a fix.

**Comment by tyxla** [comment]
Fixed by:
* D22685-code
* https://github.com/Automattic/jetpack/pull/11048

**Comment by tyxla** [comment]
Both of the above have been merged, and on production things are now looking well. Closing.
