### ISSUE TITLE
Tiled Gallery block: Open Link to Media File Opens Only that Image 

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/wp-calypso#29774]
With the old Tiled Galleries, linking to a Media file would load the images from the CDN in a carousel, including an option to close the carousel to return to the post.

<img width="1364" alt="screen shot on 2018-12-27 at 20-18-21 1" src="https://user-images.githubusercontent.com/22805865/50499101-c5765100-0a14-11e9-9791-cd1fc3cbd866.png">

URL is https://tracyspress.net/2018/05/galleries-in-email/#jp-carousel-161

The Tiled Gallery block opens only the selected image in a lightbox-type window with no clear way to get back to my post:

![screen shot on 2018-12-27 at 20-19-06](https://user-images.githubusercontent.com/22805865/50499103-c8714180-0a14-11e9-882b-2655094f0cca.png)
URL is https://i1.wp.com/testingplans.files.wordpress.com/2018/12/Screen-Shot-2018-09-20-at-10.58.20-AM.png?ssl=1&resize=404%2C404

Steps to Replicate:
1. Create a Tiled Gallery.
2. Select Media File as the Link to.
3. Save the post and view it.
4. Click one of the images in the tiled gallery.

**Comment by sirreal** [comment]
Some related convo: p1545994003223100-slack-jetpack-gutenberg

If there is a core gallery and a tiled gallery block, the tiled gallery block is annotated incorrectly and the carousel doesn't work.

These will need updating:

https://github.com/Automattic/jetpack/blob/7cb3a5d9aeb5f3fd37d348f99094bc1cb33db8cb/modules/carousel/jetpack-carousel.php#L203

https://github.com/Automattic/jetpack/blob/7cb3a5d9aeb5f3fd37d348f99094bc1cb33db8cb/modules/carousel/jetpack-carousel.php#L480
