### ISSUE TITLE
Tiled gallery block: evaluate keywords

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#29780]
Currently:
- images
- photos
- masonry
- Tiled gallery (from the block title)

Ideas:
- mosaic
- columns
- squares
- circles
- pictures
- montage
- patchwork
- collage
- media
- grid

The maximum number is 3 keywords.

via p1HpG7-65C-p2

https://github.com/Automattic/wp-calypso/blob/4fbd9c47ed2c5300654a15f005b490eae070cf01/client/gutenberg/extensions/tiled-gallery/index.js#L129-L131

**Comment by sirreal** [comment]
Is this still something to revisit?

**Comment by simison** [comment]
In CfT (p1HpG7-65C-p2), "collage" came up quite a few times and "masonry" doesn't seem like a super common word in English. 🤔 

@sirreal what do you think?

**Comment by sirreal** [comment]
> should we replace "masonry" with "collage"?

Masonry sounds like a developer looking for a particular library. Collage is likely better, but I question whether folks are discovering via either of these terms.

**Comment by simison** [comment]
Anything else in the list strikes as a common word we could use? Pictures maybe?

**Comment by sirreal** [comment]
Photos, photographs, and pictures all seem like important ones we might be missing 🤷‍♂️
