### ISSUE TITLE
Gutenberg: Post Attributes Section Should Not Appear

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#29788]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/ **(site address here)**
2. Make sure the panel on the right is opened
3. Scroll to the bottom to see a **Post Attributes** section which includes a **Templates** section
4. The templates listed are actually **Page Templates** and cannot be applied to blog posts
5. Attempting to assign a template to a blog post results in a `Publishing failed` error:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/3505172/50519573-2f2c4480-0a81-11e9-9cfc-6d9a47bcef6e.png">

#### What I expected

The **Post Attributes** section would not appear.

#### What happened instead

The **Post Attributes** section appeared.

#### Browser / OS version

I tested in Safari 11.1.1 and Firefox 64.0 on MacOS 10.13.5

#### Screenshot / Video

<img width="991" alt="image" src="https://user-images.githubusercontent.com/3505172/50519916-cf369d80-0a82-11e9-8d27-97c0828d6b8d.png">

#### Context / Source

8783021-hc

**Comment by torres126** [comment]
Automattic/themes#476

**Comment by arunsathiya** [comment]
1694323-zen

**Comment by mikeicode** [comment]
Same issue on Tortuga theme: #HC-10252677

http://cld.wthms.co/nWsdjK

**Comment by vparkhere** [comment]
Also on Lovecraft: https://cldup.com/h2iIjprq7f.png

**Comment by mikeicode** [comment]
Snaps theme also.  #7664284-zen

**Comment by chaitanyamsv** [comment]
Natural theme as well. This confused a user in #10538513-hc who thought they could apply templates to posts and change their structure.

**Comment by mmtr** [comment]
No longer reproducible after removing Gutenberg on Calypso in favor of #31196.
