### ISSUE TITLE
Audio Block Does Not Appear in Email Notifications

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#29814]
#### Steps to reproduce

Tested error on a test blog after receiving a report from https://beautifullysimplyyou.wordpress.com

1. Starting at URL: 20180917kfpremium.blog (or any test site with a Premium plan)
2. Add yourself as a subscriber 
3. Create a blog post and use the Audio Block to embed [this audio file](https://20180917kfpremium.files.wordpress.com/2018/12/2018-thank-you.mp3)
4. Publish the blog and check the received email notification

#### What I expected

The post should show all content, including a link to the audio file

#### What happened instead

There was no reference at all to the audio file.

Interesting workaround - I added the audio file to a new blog post using the Classic block --> Add Media, and my subscriber received an email with the Audio File link. 

#### Screenshot / Video

**Using the Audio Block**
![image](https://user-images.githubusercontent.com/38542929/50548303-4fdad280-0c18-11e9-8bb3-0dd6e13be59d.png)
![image](https://user-images.githubusercontent.com/38542929/50548310-6bde7400-0c18-11e9-9178-ced24931f87b.png)

**Using Insert Media in the Classic Block**
![image](https://user-images.githubusercontent.com/38542929/50548327-97615e80-0c18-11e9-923d-c7ad819028a7.png)
![image](https://user-images.githubusercontent.com/38542929/50548314-726ceb80-0c18-11e9-9664-73a5a605ba0a.png)

#user-report
#1673394-zen

**Comment by lancewillett** [comment]
Good find! This isn't a Calypso bug exactly, so I might move it to a different bug tracker. Moved to 8147-wpcom
