### ISSUE TITLE
Gutenlypso: Media Modal scrolls to top on insert

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#29821]
#### Steps to reproduce
1. Starting at URL: `/block-editor/post`
2. Insert enough content to scroll down.
3. At the bottom of the post create an `/image` block and open the Media Library.
4. Insert an image.

#### What I expected

To remain in the same scroll position I was before opening the Media Library.

#### What happened instead

It scrolled back to the top of the post.

#### Context / Source

Maybe related to #16873?

**Comment by mmtr** [comment]
Confirmed this is still happening in the Classic editor, so I reopened #16873 and proposed a solution in #29832.
