### ISSUE TITLE
Gutenlypso: Classic block menu to convert to blocks difficult to get to 

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#29828]
#### Steps to reproduce
1. In Calypso: edit a post that was previously composed with the classic editor 
2. Try to use the ⋮ menu to convert the page/post to separate blocks (Convert Blocks)
3. Notice that the ⋮ menu in the classic block only toggles the advanced editor controls off/on 
4. Click around until you can finally access the Block control menu with the same ⋮ icon. 

#### What I expected
This actually tripped me up a couple of times. I tried the same in wp-admin and the classic block editor there does not have this same problem. It's nearly impossible to figure out how to convert to blocks with the Calypso classic block menu sharing the same icon as the Classic block editor icon - if you can figure out how to make that appear. 

#### What happened instead
Watch how much I have to click around to try to figure out how to get the block ⋮ menu to appear: ![http://cld.wthms.co/6oxI7v+](http://cld.wthms.co/6oxI7v+)
Direct Link: http://cld.wthms.co/6oxI7v+   

Now compare that to wp-admin's classic block editor which has one ⋮ to rule them all! 
![http://cld.wthms.co/Iw5Seq+](http://cld.wthms.co/Iw5Seq+)
Direct Link: http://cld.wthms.co/Iw5Seq 

#### Feedback

I think that Calypso needs to rethink the use of two ⋮ icons to remove confusion here. If I had trouble with this more than once I have no doubt this would be next to impossible for customers to try to figure out themselves. 

Have we ever considered a prompt asking once opening a classic page/post to convert to blocks? wp-admin makes it easy to find the Convert to blocks option, we need to try to recreate that same experience on Calypso to help move our customers into the future 🚀

#### Browser / OS version
Chrome Version 70.0.3538.110 (Official Build) (64-bit)
iOS: 10.12.6 

#### Context / Source
#empathy #painpoint

**Comment by torres126** [comment]
> Have we ever considered a prompt asking once opening a classic page/post to convert to blocks?

That's being tracked in #26594, and #29790 should take care of it. :)

**Comment by arunsathiya** [comment]
Thanks for chiming in, @torres126. 

@msdesign21 This is exactly the same report as https://github.com/Automattic/wp-calypso/issues/29569 and I am going to close this one.

@Copons has some reasoning behind why the menu is not available clearly on the `Classic block` here - https://github.com/Automattic/wp-calypso/issues/29569#issuecomment-449077955

Also, as linked in the last comment, your feedback is already in the works! :)
