### ISSUE TITLE
Editor: Blank screen when the post type isn't specified

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#29822]
#### Steps to reproduce
1. Starting at URL: `/block-editor/:site` (note: this only happens if the site fragment is provided).

#### What I expected

To being redirected to `/block-editor/post/:site`.

#### What happened instead

It opens the non-existent `/block-editor/:site` route, causing a blank screen.

**Comment by codebykat** [comment]
I'm not sure we actually expect this path to work (it's not linked from anywhere?) but this should at least 404, not white screen.
