### ISSUE TITLE
Gutenlypso: Images with captions created with the Classic editor aren't converted into blocks

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#29823]
#### Steps to reproduce
1. Starting at URL: `/block-editor`.
2. Switch back to the Classic editor.
3. Insert an image with a caption, and save the post.
4. Switch to the Block editor.
5. You should see a Classic block containing the image with caption.
6. Convert it to blocks.

#### What I expected

To see the image with caption successfully converted into an Image block.

#### What happened instead

The image with caption is converted into an HTML block.

#### Context / Source

This is an example of the code generated by the Classic Calypso editor when inserting an image with caption:

```
[caption id="attachment_1234" align="alignnone" width="960"]<img class="alignnone size-full wp-image-1234" src="https://coponstest001.files.wordpress.com/2018/12/test.jpg" alt="test" width="960" height="1440" /> Test Caption[/caption]
```

This is the code contained in the HTML block, generated by Gutenberg when failing to convert the above image with caption into an Image block:

```
<div class="mceTemp"><dl id="attachment_1234" class="wp-caption alignnone" style="width: 960px;" data-mce-style="width: 960px;"><dt class="wp-caption-dt"><figure><img class="alignnone size-full wp-image-1935" src="https://example.files.wordpress.com/2018/12/test.jpg" alt="test" width="960" height="1440" data-mce-src="https://example.files.wordpress.com/2018/12/test.jpg?w=680"></figure></dt><dd class="wp-caption-dd">Test Caption</dd></dl></div>
```

Note: this only happens in Calypso.
The same conversion works perfectly fine in Gutenberg on WPCOM.

**Comment by gwwar** [comment]
Fixed by new integration
