### ISSUE TITLE
Gutenlypso: Emoji becomes an image block on converting to blocks

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29833]
#### Steps to reproduce 

- Start with a WordPress.com site on the Calypso editor
- Add an emoji to the post
- Save or publish the post
- Opt-in for WordPress Editor/Gutenberg
- Convert the `Classic block` shown at the moment to blocks, using `Convert to blocks` option under a menu

#### What is expected 

The emoji appears in the WordPress Editor, on a `Paragraph` block

#### What happens instead 

The emoji appears as an image block instead.

<img width="1151" alt="screenshot 2019-01-01 at 20 37 21" src="https://user-images.githubusercontent.com/18581859/50574011-11eed180-0e05-11e9-8e56-1ade6faccb46.png">

[Video showing this behaviour](https://cloudup.com/cUXlmUTwXNf). This does not happen when the line contains only the emoji, but happens with text nearby (on the same line as well) - [video](https://cloudup.com/cNlJjVqaNN2).

I am unable to see this behaviour on vanilla install of Gutenberg - [video](https://cloudup.com/cdQgQW2F70t).

I am also unable to see this error on the Calypsoified Gutenberg - [video](https://cloudup.com/cwZmmyY3ttk). It happens only on Gutenlypso - https://wordpress.com/block-editor/post 

#### Context:

I came across this when trying to reproduce https://github.com/Automattic/wp-calypso/issues/29831

**Comment by gwwar** [comment]
Should be fixed by #29858

![50609495-a8160c80-0e84-11e9-830e-cbfb4a0d20dc](https://user-images.githubusercontent.com/1270189/50717120-12bc7900-103a-11e9-994a-6ccbae2fb587.gif)
