### ISSUE TITLE
Gutenlypso: Simple Payments blocks product images not updated when edited on Media Modal

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#29830]
#### Steps to reproduce
1. Open the block editor at /block-editor and select a site under a paid plan (free plans don't allow to insert Simple Payments blocks neither edit images in the Media Modal).
2. Insert a Simple Payments button block and set a Product Image using the Media Library.
3. Click on the Edit button (Pencil icon) so the Medial Modal is opened again.
4. Select the current product image and click on the Edit button.
5. Push the "Edit Image" button and apply some changes to the image (e.g. flip it).
6. Click on the Done button and insert the modified image.

#### What I expected
The product image should display the modified image.

#### What happened instead
The product image displays the previous image.

#### Context / Source
Related: #29791 and #29820.

**Comment by kwight** [comment]
Fixed in #31196 .
