### ISSUE TITLE
Unicode 11 Emojis Not Replaced with Twemoji

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#29866]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post OR https://wordpress.com/block-editor/post OR `wp-admin/post-new.php`
2. Visit the list at https://emojipedia.org/unicode-11.0/
3. Copy and paste one into a post
4. See issue 

#### What I expected

Twemojis exist for these emojis, preventing them from appearing as just a square block. For comparison, this is how Twitter displays them. 

![sgfddgfssgfdsd](https://user-images.githubusercontent.com/43215253/50588378-aa269e00-0e79-11e9-865d-94235a29d05a.png)

#### What happened instead

Square blocks for the Unicode 11 set 

![gfdsgdsfdgdfsg-1](https://user-images.githubusercontent.com/43215253/50588391-b0b51580-0e79-11e9-9dfc-a19d56a789b7.png)

#### Browser / OS version

Mac OS X 10.6.8 with Chrome 49, same issue on Samsung Galaxy Tab S2 with Chrome 70

#### Context / Source

Mentioned in #29831

**Comment by gwwar** [comment]
Thanks for filing this one!

**Comment by mmtr** [comment]
Solved by rWP189659-wpcom

**Comment by gwwar** [comment]
Much appreciated @mmtr!
