### ISSUE TITLE
Gutenberg: Blank Screen on /block-editor/posts

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29864]
#### Steps to reproduce 

- Open https://wordpress.com/block-editor/posts

#### What happens at the moment 

It loads a blank screen.

#### Suggested enhancement

Is it possible to redirect this path to https://wordpress.com/block-editor/post, so that user can pick a site to compose the post? Or, is there a way to make this path actionable?

I think the same behaviour is not available yet for WordPress Editor, as WordPress Editor is not available for Jetpack sites at this time - https://github.com/Automattic/wp-calypso/issues/28251

#### Behaviour on Calypso editor

Visiting https://wordpress.com/posts shows the list of all posts from all the sites the user has associated to their WordPress.com account.

#### Context

I came across https://github.com/Automattic/wp-calypso/issues/29822 and decided to test this path. #manual-testing

**Comment by codebykat** [comment]
I'm not sure we actually expect this path to work (it's not linked from anywhere?) but this should at least 404, not white screen.
