### ISSUE TITLE
Tiled Gallery block: Icon on the block itself is very small

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29862]
#### Steps to reproduce

- Start at https://wordpress.com/block-editor/post and choose a WordPress.com site
- Add a `Tiled gallery` block

#### What I expected

The block icon on the block is large, or as sized the same as other blocks, like the `Image` block

<img width="643" alt="screenshot 2019-01-02 at 11 58 41" src="https://user-images.githubusercontent.com/18581859/50582079-c6303c80-0e85-11e9-9c39-a3c0bc199e1d.png">

#### What happened instead

The icon is very small.

<img width="648" alt="screenshot 2019-01-02 at 11 54 54" src="https://user-images.githubusercontent.com/18581859/50582072-b0bb1280-0e85-11e9-95be-be08107786e2.png">

#### Browser / OS version

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) on macOS 10.14.2 - Mac OS Mojave.

**Comment by simison** [comment]
Noting that this happens only in Calypso so when testing the fix, please test both wp-admin and Calypso.
