### ISSUE TITLE
Gutenberg: Simple Payments in Classic Block converts to an empty Simple Payments block

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#29870]
Simple Payments in the Calypso Classic block sometimes converts to a blank simple payments block.

To Reproduce:
1. In a fresh post, add a classic block
2. Click on the Add > Payment Button
3. Choose an existing Payment Button
4. On the Classic Block option, choose Convert to Blocks
Expected: The Simple Payments block is filled with the appropriate details from the existing simple payment
Actual: In many cases we see an empty Simple Payment block

![breaks](https://user-images.githubusercontent.com/1270189/50608644-17d6c800-0e82-11e9-8fee-5f03c1bcb385.gif)

**Comment by retrofox** [comment]
> Click on the Add > Payment Button

Is still possible to add a Payment button using a _Classic_ block?
![image](https://user-images.githubusercontent.com/77539/54947605-79568200-4f19-11e9-89ec-3aa4733517f0.png)

I haven't found this option :-/

**Comment by simison** [comment]
> Is still possible to add a Payment button using a Classic block?

After switching to an iframe solution, I don't think this is possible.

Classic block in Calypso used to be "classic Calypso editor", which had this feature.

**Comment by simison** [comment]
Block itself produces a shortcode, so after creating the button in Gutenberg, you can modify post's code and remove `<!-- -->` block notation and just leave the shortcode in there, save and refresh the page.

Copypasting the shortcode in the editor should result the same test as well.
