### ISSUE TITLE
Gutenberg Calypsoify: Support Copy a Post Functionality

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#29876]
When given a query param of`?copy=postId` in the Gutenberg editor, let's start a new post with that post content and title copied. This issue will first fix the calypsoify flow from the Calypso post/page. We can iterate on duplication flows from wp-admin lists or as an extension on the Block Editor sidebar in separate followups outside of this issue.

See related https://github.com/Automattic/wp-calypso/issues/28555

#### Steps to reproduce
1. On an atomic site, visit the Calypso Page List or Post List
2. In the dropdown options select "duplicate a post" or "copy a post"
3. I'm navigated to `/wp-admin/post-new.php?calypsoify=1&copy=<postId>`
4. The postId title and content are pre-populated as expected

**Comment by kwight** [comment]
To start, I think this will need to be in two parts: one Calypso PR to add the menu item, and one Jetpack PR to add the param handling. And I'm guessing it will make sense to kick off an autosave with the copied content, creating the new permalink too.

**Comment by kwight** [comment]
PR enabling the menu item is in #29901. Diff for WP.com (needs to go into Jetpack next release cycle for Atomic) at D22805-code.
