### ISSUE TITLE
Gutenlypso and Gutenberg: Image block: Can't insert large images at original size

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#29874]
This is a strange one that doesn't seem to always happen. Might be related to https://github.com/Automattic/wp-calypso/issues/29367

#### Steps to reproduce
1. In the wp-admin Gutenberg or Gutenlypso editor, add an image block.
2. Select a large image from the libary (mine are 4000px wide).
3. In the block options in the sidebar, observe that the maximum size is much less (seems to be 700px for me in wp-admin and 1024px in Gutenlypso).
4. In Gutenlypso, I was able to get the correct dimensions to load by clicking "Edit" on the image, and then "Insert" without making any changes.

#### What I expected

For the image size in the sidebar to allow me to set the image to the original size.

#### What happened instead

The width is limited to either 700px or 1024px.

#### Browser / OS version

Firefox / OSX. This is on a blog with the (old) theme Spun.

#### Screenshot / Video
Video in wp-admin: https://cloudup.com/coPQYrQivIV
Video in Gutenlypso: https://cloudup.com/cU9uh5kkex9

Screenshots:
![screen shot 2019-01-02 at 2 46 55 pm](https://user-images.githubusercontent.com/52152/50616436-604faf00-0e9d-11e9-9e2a-0eedde111767.png)
![screen shot 2019-01-02 at 2 47 16 pm](https://user-images.githubusercontent.com/52152/50616441-63e33600-0e9d-11e9-8f05-974b811a24a6.png)
![screen shot 2019-01-02 at 2 48 52 pm](https://user-images.githubusercontent.com/52152/50616504-99881f00-0e9d-11e9-93df-5cf8d7ee3b5a.png)
![screen shot 2019-01-02 at 2 49 12 pm](https://user-images.githubusercontent.com/52152/50616509-a1e05a00-0e9d-11e9-81c8-d8108952b9b7.png)

#### Context / Source

#dogfooding for my photo blog

**Comment by codebykat** [comment]
I am also able to manually set the size to the original size after inserting it, and that seems to stick.

**Comment by arunsathiya** [comment]
Just a note that I was able to reproduce this on a free WordPress.com site with Twenty Nineteen theme. 

**Note:** This happens only when choosing the image from the media library after adding an `Image` block.

The first image is from Gutenlypso and the second from Calypsoified Gutenberg on wp-admin.

<img width="1281" alt="screenshot 2019-01-03 at 13 35 54" src="https://user-images.githubusercontent.com/18581859/50628106-9869f700-0f5c-11e9-9226-e4061f167ef3.png">

<img width="1281" alt="screenshot 2019-01-03 at 13 35 56" src="https://user-images.githubusercontent.com/18581859/50628105-97d16080-0f5c-11e9-962c-92fae3fb7132.png">

---

This is not reproducible when I drag-drop image to editor, or add `Image` block and then drag-drop image.

The first image is from Gutenlypso and the second from Calypsoified Gutenberg on wp-admin.

<img width="1281" alt="screenshot 2019-01-03 at 13 32 29" src="https://user-images.githubusercontent.com/18581859/50628018-3f01c800-0f5c-11e9-9b1f-0547479a2d57.png">
<img width="1281" alt="screenshot 2019-01-03 at 13 32 31" src="https://user-images.githubusercontent.com/18581859/50628020-40cb8b80-0f5c-11e9-8e9b-39b1db5de545.png">

**Comment by codebykat** [comment]
Closing this out in favor of related core Gutenberg issues:

https://github.com/WordPress/gutenberg/issues/11530
https://github.com/WordPress/gutenberg/issues/12276
