### ISSUE TITLE
Gutenlypso: Incorrect path for "Manage All Reusable Blocks"

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29881]
#### Steps to reproduce 

- Start at https://wordpress.com/block-editor/post 
- Add a block
- Make it a reusable block
- Click on `+` for the block picker to show up
- Scroll to the bottom 
- Click on `Manage All Reusable Blocks`

#### What is expected 

It takes me to the reusable blocks management page, on wp-admin dashboard: `{site}/wp-admin/edit.php?post_type=wp_block`

#### What happens instead 

It takes me to the site picker `https://wordpress.com/block-editor/post`

**Comment by codebykat** [comment]
The underlying integration has changed and this issue no longer exists. Actually, this functionality no longer exists but that's another issue (literally: #27374).
