### ISSUE TITLE
Cannot insert an images with special characters into a Gallery Block with the Calypso Media modal

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#29880]
Pre-requisite: Upload one image with chinese characters in it (https://sandeepsuppport.files.wordpress.com/2019/01/圖書.jpeg) and one with English.

#### Steps to reproduce

1. URL: sandeepatomicsiteblog.com (My test site)
2. My Site -> Blog Posts: Add.
3. Click on `Gallery` block to select it to add gallery to your post.
4. Use both the images you saved above in the pre-requisite, to add to the Gallery.

#### What I expected

Both the images would show when added to the Post.

#### What happened instead

The one with chinese characters in it displays as broken image whole the other one works fine.

#### Browser / OS version

Mac OS (10.13.6) whatsmybrowser.org/b/BQSKXVZ

#### Screenshot / Video

https://cloudup.com/c1PbjyFXVIe

#### Context / Source

1682814-zen

**Comment by gwwar** [comment]
Only reproducible with the Calypso media modal insert. Drop & drop works. All other environments work as expected.

**Comment by mmtr** [comment]
No longer reproducible after removing Gutenberg on Calypso in favor of #31196.
