### ISSUE TITLE
Gutenberg: Shortlinks extension - when to hide?

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#29886]
Currently, we'll always show the Shortlinks extension in the Jetpack sidebar:

![](https://cldup.com/YvcQbdFLAD.png)

But visiting the shortlink will not always work for all users. For example, if the post is a draft, or non-public, only users with sufficient capabilities will be able to view it. This brings some questions on whether we should hide the Shortlinks UI on:

* Non-public sites
* Non-published posts (drafts)?
* Non-public posts (private, password protected)

I think it's fine to always display it, because it'll only be displayed to users who can edit the post, and all those users will usually be able to view the post. But just in case, I wanted to confirm with y'all.

cc @scruffian @mapk

**Comment by adelineyaw** [comment]
User (ID: 104633187) would like to see Shortlinks available in the new editor (2570755-hc)

**Comment by tyxla** [comment]
@adelineyaw: shortlinks is already available in the new editor. To access it, you can click the "Jetpack" icon in the toolbar, and you'll see the Shortlinks UI at the bottom of the sidebar.

**Comment by scruffian** [comment]
I think the current situation is acceptable. We can revisit if we notice user confusion arising.
