### ISSUE TITLE
Gutenlypso: Calypso media uploader's empty content text overlap

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29905]
#### Steps to reproduce 

- Start at Gutenlypso https://wordpress.com/block-editor/post 
- Choose a site with no media library files
- Add an image block
- Choose `media library`
- Wait for Calypso's media uploader to load

#### What is expected 

The empty content text title and line do not overlap

#### What happens instead 

The empty content text title and line overlap

<img width="1921" alt="screenshot 2019-01-04 at 16 00 48" src="https://user-images.githubusercontent.com/18581859/50684173-9a09ec80-103a-11e9-9b6f-b8db30c196ea.png">

For search reasons, the text is `You don't have any images.` and `Would you like to upload something?`

This happens only for media uploader on Gutenlypso, and does not affect media uploader for WordPress.com sites using Calypso editor

<img width="1921" alt="screenshot 2019-01-04 at 16 00 50" src="https://user-images.githubusercontent.com/18581859/50684177-9bd3b000-103a-11e9-9d4d-eea6a1a0b238.png">

**Comment by torres126** [comment]
I'd like to take this issue if that's okay? I'll do a PR later today if possible. :)

**Comment by Copons** [comment]
Completely missed this issue, it has been fixed by #29908.

Again, @torres126, sorry about it! 🙇
