### ISSUE TITLE
Gutenberg: Avoid to break the apiFetch middleware chain

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#29909]
https://github.com/WordPress/gutenberg/pull/12365 added support for using a custom fetch handler, so we can now use wpcom.js without breaking the apiFetch middleware chain.

That should also allow us to remove the middlewares we needed to copy in https://github.com/Automattic/wp-calypso/issues/28777 for fulfilling the intent of the core middleware.

**Comment by gwwar** [comment]
Definitely worth following through/tidying in our integration ✨

**Comment by mmtr** [comment]
Started exploring this in D37093-code

**Comment by mmtr** [comment]
D37093-code is ready for a review.

**Comment by mmtr** [comment]
D37093-code has been released. Let's keep an eye on potential regressions on p7DVsv-7YN-p2
