### ISSUE TITLE
Global Notices: Long Notices Are Cut Off

### ISSUE THREAD

**Issue by iannuttall** [Automattic/wp-calypso#2990]
As [mentioned](https://github.com/Automattic/wp-calypso/pull/2413#issuecomment-178339352) by @mikeshelton1503, longer notices are being cut off and hiding important information.

For example, we display information to a user who disputes a payment with their bank or through PayPal, and we need to let them know that a chargeback carries a charge, as well as a link to their cart.  Here's what that currently looks like at 1200px browser width:

![Payment dispute notice](https://cloud.githubusercontent.com/assets/6681919/12756017/ba5b2568-c9c9-11e5-8d8e-a676ef496a96.png)

I'll try to reduce the message and cut out some information, but the shortest I could get it still wasn't fully visible between 661px and ~1100px. To make it fit we'd probably have to go with something like:

> Warning: A transaction on your site was disputed. Resolve Now or Contact Support.

cc/ @evanzi @alxblock @melanieharari

**Comment by rickybanister** [comment]
We can remove the css that is truncating long notices for the time being, but in the long run it might be nice to seek a different approach for wordy or complicated things like this. Like a short message with a notice-action that takes you to somewhere to further explain and help you resolve the problem. 

`You have a disputed transaction | Learn More`

**Comment by rickybanister** [comment]
I'll work on a quick PR to remove the truncation for now.

**Comment by iannuttall** [comment]
Thanks @rickybanister! We'll discuss the best way to approach these longer notices going forward :)
