### ISSUE TITLE
Theme Live Demo triggers JS error for Jetpack Multi-site site

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#29903]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/{site}, for a Jetpack site.
2. Click the three-dots menu for a theme
3. Click "Live demo"
4. Observe "blank screen"

#### What I expected
I expected to see an iframed live demo of the theme, similar to what I see for WordPress.com sites, or the demo I see in the Customizer when previewing a site perhaps.

#### What happened instead
I get a blank screen, and when I look in the JS console I see:

<img width="1583" alt="screen shot 2019-01-03 at 9 59 10 pm" src="https://user-images.githubusercontent.com/108942/50674433-7051b680-0fa3-11e9-9695-cf54e6292581.png">

#### Browser / OS version
Chrome/OSX

#### Context / Source
#reallife #dogfooding Wanted to try a different theme on a site I have which only posts "screenshots", so is very image-heavy.

**Comment by arunsathiya** [comment]
Noting that I am unable to reproduce this. I tested with a Jetpack Professional site, and going by the steps on the report, the `Live demo` option works fine. [Here is a video showing this behaviour](https://cloudup.com/cU_80m4C66o). 

I use Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) on macOS 10.14.2 - Mac OS Mojave.

**Comment by beaulebens** [comment]
I've just realized that apparently there's something else wrong with the site that I'm using to see this, because I also don't see any of the additional Jetpack Themes, even though the site is on a Professional plan. I can also confirm that things are working as expected on a different site. I'll close this issue and see if I can figure out this specific site's problems.

**Comment by beaulebens** [comment]
I'm re-opening because I just figured out the issue -- I'm looking at a multi-site, which I think is why I can't see the Jetpack/WP.com Themes (since I am not able to install them on this site). I looked on a different multi-site install and see the same problem there as well.
