### ISSUE TITLE
Gutenlypso: Classic Block Open Link In New Tab Checkbox

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#29916]
#### Steps to reproduce
1. Using the Classic Block, add some text. Select text and click the Insert link button.
2. Attempt to check the `Open link in a new window/tab` option.

#### What I expected
* Able to click the checkbox to open the link in a new tab.

#### What happened instead
* Unable to check the checkbox via mouse or keyboard navigation.

#### Browser / OS version
Chrome Version 71.0.3578.98 

#### Screenshot / Video
![screen shot on 2019-01-04 at 14 22 25](https://user-images.githubusercontent.com/15803018/50711826-a2f3c180-102c-11e9-8498-d616181e043a.png)

#### Context / Source
#user-report 9252357-hc

**Comment by arunsathiya** [comment]
Noting that I am able to reproduce this as well. I use Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) on macOS 10.14.2 - Mac OS Mojave.

I have submitted a related report here https://github.com/Automattic/wp-calypso/issues/29920 for the bad styling that this linker modal has at the moment.

**Comment by molszewska** [comment]
Another report: #1698053-zen
Tested and confirmed both on Simple and Atomic sites.

**Comment by codebykat** [comment]
The underlying integration has been updated and I can no longer reproduce this bug.
