### ISSUE TITLE
Gutenberg: Conflict between Gallery and Classic blocks

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#29910]
#### Steps to reproduce
1. Starting at URL: https://mytestsite.live/testing-galleries/
2. Create a Gallery block
3. Then create a Classic block
4. In the Classic block add an image on it

#### What I expected
That all the content would remain on the page.

#### What happened instead
Code from the Gallery block is removed.

#### Browser / OS version
Chrome/71.0.3578.98
OS X 10.13.6

#### Screenshot / Video
Once I added the image in the Classic block:

![screenshot - edit page my test site wordpress com 2019-01-04 15-38-59](https://user-images.githubusercontent.com/16104522/50702528-50b89d80-1038-11e9-97da-9723b693f23e.png)

After that the gallery code was removed:

![screenshot - edit page my test site wordpress com 2019-01-04 15-39-18](https://user-images.githubusercontent.com/16104522/50702567-6c23a880-1038-11e9-89a1-d3416ec93f39.png)

Here's a screencast with the steps to reproduce:

![screenshot - screencast 2019-01-04 15-40-04](https://user-images.githubusercontent.com/16104522/50702621-95dccf80-1038-11e9-86a2-addfa0627b95.gif)

#### Context / Source
Got a user on chat that had this issue. It seems that the galleries were not showing when editing the page, but were there in the page itself. We were able to fix after some troubleshoot, when we found the conflict between the blocks. We fixed manually converting the Classic block content on different blocks.

#user-report

**Comment by arunsathiya** [comment]
>I tried to test in a new page, but can't reproduce every time. But when I try to add the Classic block on that page that I shared in the screencast the issue happens.

Just to ensure I understand this better, is it specific to that page, or any page on that site?

Can you also share the theme name, and the page template this page was using? I am happy to test along.

**Comment by carinapilar** [comment]
> Just to ensure I understand this better, is it specific to that page, or any page on that site?

I was able to reproduce again in the same page, and in a new page with the same content.

> Can you also share the theme name, and the page template this page was using? I am happy to test along.

It's this page: https://mytestsite.live/testing-galleries. The gallery is there, when I add the Classic block the issue happens, it didn't happen on Calypsoified Gutenberg anymore though. 🤔

I'm using the P2 theme and the page has the default template. Thanks Arun! 🙂

**Comment by arunsathiya** [comment]
Thanks for the detail, Carina! 

>it didn't happen on Calypsoified Gutenberg anymore though.

That's good to know! 😌

>I'm using the P2 theme and the page has the default template

I tried reproducing it on the P2 theme, but I am not able to. [Video](https://cloudup.com/cQqPKCFhnSY). This was on Gutenlypso as well. At this stage, it feels to have been a one-off case at your end, but let's leave this open to see if anyone else has thoughts.

**Comment by carinapilar** [comment]
> I tried reproducing it on the P2 theme, but I am not able to.

This is so weird, it's intermittent or something very specific. 🤔

> let's leave this open to see if anyone else has thoughts.

Sounds great, thanks for testing! 🙂

**Comment by blazevivan** [comment]
I tested on the theme Mood, with Chrome 71.0 and Firefox 64 on Windows 10. 
I was not able to reproduce the issue.

**Comment by Robertght** [comment]
I confirm it using the Nikau theme via Calypso.

The weird thing is that it breaks only the first time I do it, but not the second time on the same post.

Chrome 71.0.3578.98
MacOS Mojave

**Comment by vindl** [comment]
Most likely this was caused by interaction of Calypso Classic block and Media Library. We deployed Gutenframe last week which is using the Core Classic block and this issue is no longer reproducible.
