### ISSUE TITLE
Gutenlypso: IE11 Image Block Upload Error

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#29914]
#### Steps to reproduce
1. Using IE 11, add image block to a post.
2. Click "Upload" to upload a new image file.

#### What I expected
Able to upload image as normal.

#### What happened instead
* Receive `Object doesn't support property or method 'has'`  error.
* No console errors are generated from this.
* You can select an already uploaded image from Media Library without issue.

#### Browser / OS version
Windows 10 / IE11 Version: 11.195.17763.0

#### Screenshot / Video
![error](https://user-images.githubusercontent.com/15803018/50710633-b6049280-1028-11e9-9b8f-4b74f61716cf.PNG)

#### Context / Source
#user-report 1691498-zen

**Comment by torres126** [comment]
Different error and console error, but the error message referencing `has` seems to suggest #28893 _might_ be related. (That was closed because it only affects older browsers)

**Comment by gwwar** [comment]
Getting a `No Content-Disposition Supplied` error when clicking on the upload button. The Calypso Media Modal works for uploading new images with IE11.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

We are discontinuing IE11 support soon, so this issue should be closed as `Closed - Won't Fix`.
