### ISSUE TITLE
Gutenlypso: Linker modal on Classic Block has bad styling

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29920]
#### Steps to reproduce 

- Start at https://wordpress.com/block-editor/post 
- Add a `Classic` block to the post
- Add text
- Select the text and click hyperlink icon/use `Cmd+K` (Mac) or `Ctrl+K` (Windows)

#### What is expected 

The linker modal that pops up has proper styling

#### What happens instead 

The linker modal that pops up has bad styling/lost styling

<img width="700" alt="screenshot 2019-01-05 at 10 58 57" src="https://user-images.githubusercontent.com/18581859/50720757-f1f73080-10d8-11e9-8bbc-91e0453a1375.png">

#### Context / source

I noticed this when I came across https://github.com/Automattic/wp-calypso/issues/29916

**Comment by codebykat** [comment]
The underlying integration was updated and this has been addressed in the process.
