### ISSUE TITLE
Gutenlypso: Keyboard shortcut to remove classic block does not remove the block

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#29927]
#### Steps to reproduce 

- Start at Gutenlypso https://wordpress.com/block-editor/post 
- Choose a site
- Add a `Classic block`
- Optionally write content in it
- Click `Control+option+Z` to remove the block. It's the Gutenberg keyboard shortcut to remove blocks

#### What is expected 

The `Classic block` is removed

#### What happens instead 

The block is not removed. The classic block's advanced text formatting bar gets toggled instead. [Here is a video showing this behaviour](https://cloudup.com/cU_UWIqAij9).

#### Notes

If it's decided to not allow this keyboard shortcut usage on Gutenlypso's classic block, we should hide the following keyboard shortcut tip.

![screen shot 2019-01-06 at 21 35 23](https://user-images.githubusercontent.com/18581859/50738529-05022180-11fb-11e9-8a16-79899ca129d9.png)

The `Classic block` on Calypsoified Gutenberg `{site}/wp-admin/post-new.php` works as expected.

**Comment by gwwar** [comment]
Fixed by the new integration
