### ISSUE TITLE
Gutenlypso: Reshare broken

### ISSUE THREAD

**Issue by suyogyashukla** [Automattic/wp-calypso#29930]
#### Steps to reproduce
1. Make sure Gutenlypso is active.  
2. Go to reader and try to share a post. 

#### What I expected

- The post to draft in the posts section with a preview of the original post in Gutenberg.

#### What happened instead

- A new post screen opens in Gutenberg with no preview/link to the post being reshared. 

#### Browser / OS version

- Brave browser latest version. This issue isn't browser dependent as I checked in Chrome and Firefox as well. 

#### Screenshot / Video

https://cld.wthms.co/ca9fEQ

#### Context / Source

User originally reported this in #9239723-hc 

I was able top reproduce. Reshare works perfectly fine in the normal Calypso interface.

**Comment by mmtr** [comment]
This is a duplicate of #28973
