### ISSUE TITLE
Offline: determine shape of redux post-edit-store

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#2994]
I think part of this means determining whether post-edit-store belongs in its own subtree, or whether it should point to an instance in a Posts store. If so we need to look at the different uses of posts for drafts-drawer, all-sites/single-site, and we will really be determining the shape of a Post object.

**Comment by aduth** [comment]
Proposal:

Keep `edits` under `state.ui.editor`, mapping global ID to an object containing revisions, if edits exist. A new draft doesn't yet have a global ID, which should be reflected by its key (empty string?):

```json
{
	"posts": {
		"items": {
			"3d097cb7c5473c169bba0eb8e3c6cb64": {
				"ID": 841,
				"site_ID": 2916284,
				"global_ID": "3d097cb7c5473c169bba0eb8e3c6cb64", 
				"title": "Hello World"
			}
		},
		"sitePosts": {
			"2916284": {
				"841": "3d097cb7c5473c169bba0eb8e3c6cb64"
			}			
		}
	},
	"ui": {
		"editor": {
			"edits": {
				"": {
					"title": "My New Post"
				},
				"3d097cb7c5473c169bba0eb8e3c6cb64": {
					"title": "Ribs & Chicken"
				}
			}
		}
	}
}
```

Selectors under posts subtree should only return the "persisted" entity. As a consequence, any UI that consumes from the post subtree will not receive edits (e.g. edits won't appear on post listing).

```js

// client/state/posts/selectors.js
export function getPost( state, globalId ) {
	return state.posts.items[ globalId ];
}

export function getSitePost( state, siteId, postId ) {
	return getPost( state, state.posts.sitePosts[ siteId ][ postId ] );
}
```

Selectors under the editor UI subtree should merge the revisions with the original post copy.

```js
// client/state/ui/editor/selectors.js
export function getEditedPost( state, siteId, postId ) {
	const post = getSitePost( state, siteId, postId );
	const edits = state.editor.edits[ state.posts.sitePosts[ siteId ][ postId ] ];
	return Object.assign( {}, post, edits );
}
```

Upon saving the post, the edited revisions are copied to the `posts` subtree to reflect that the revisions have been persisted. This should coincide with any REST API or local operations necessary to save the changes.

**Comment by aduth** [comment]
I should clarify that the above structure only accounts for revisions to the post object, and does not include any of the [top-level state values currently tracked by `PostEditStore`](https://github.com/Automattic/wp-calypso/blob/88f45bf7d4f2ab8c6530c849c54de0cdb4e3072b/client/lib/posts/post-edit-store.js#L42-L57).

**Comment by rralian** [comment]
I think this makes sense. I'll poke with some questions to make sure I understand correctly. An "edit" object tracks the changes as you are making them... essentially your "dirty" changes to the post that have not yet been persisted. When the post is saved, those edited attributes will then be persisted onto the local copy of the post under the "posts" subtree. We should do this update to the post object locally as an optimistic change, but it will also happen automatically when the changes are pushed to the API and we get the canonical post object back from the server (which would also correct any bad assumptions made in the optimistic record change). Once the edit has been saved, we can remove the "edit" record.

@mtias suggested here https://github.com/Automattic/wp-calypso/pull/3025#discussion_r51992170 that we store editor-specific data in a `state.editor` subtree, and I think I tend to agree. I would suggest then that the [top-level editor state values](https://github.com/Automattic/wp-calypso/blob/88f45bf7d4f2ab8c6530c849c54de0cdb4e3072b/client/lib/posts/post-edit-store.js#L42-L57) also be stored under state.editor, alongside the "edits" object suggested here.

We'll need some further thinking for how to persist changes while offline to queue them up when online again. But I think we can start with this. In fact, I think we _should_ start with this and get the simple case done first.

**Comment by aduth** [comment]
>I'll poke with some questions to make sure I understand correctly

Your summarization is exactly correct.

>@mtias suggested here https://github.com/Automattic/wp-calypso/pull/3025#discussion_r51992170 that we store editor-specific data in a `state.editor` subtree, and I think I tend to agree.

Yeah, I saw this and chatted a bit with @mtias about what purpose the `ui` key should serve. He makes the argument that `ui` is more disposable, which I can agree with to an extent. We should also consider nesting folders, perhaps as `state.posts.editor` or similar? I'm not opposed to a top-level key for the editor however, and as you suggest, it probably makes sense for top-level variables to live there too.

**Comment by rralian** [comment]
I think we have de-facto addressed this as we are already persisting redux data for the editor.
