### ISSUE TITLE
Color schemes: incorrect accent color usage on import page

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#29949]
#### Steps to reproduce
Go to Import and you'll see too many pink buttons. These pink buttons should just be all default buttons.

#### Screenshot / Video
![screen shot 2019-01-07 at 2 39 15 pm](https://user-images.githubusercontent.com/618551/50792495-c9af3380-128a-11e9-81c8-5d1d32987a60.png)

**Comment by torres126** [comment]
I think that this has been fixed now by #29956.

**Comment by flootr** [comment]
fixed with #29956
