### ISSUE TITLE
2FA Phone Validation:  French Polynesia numbers failing validation

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/wp-calypso#29943]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/security/account-recovery
2. Enter a valid French Polynesian phone number (89 XX XX XX)
3. Validation fails

Related: https://github.com/Automattic/wp-calypso/issues/25163

In our forked version of `node-phone`, we only account for French Polynesia numbers having 6 digits, but they can also have 8!
https://github.com/Automattic/node-phone/blob/e30f6b652a135819b5b9e7fa3bb84d36987a6cea/lib/iso3166Data.js#L1408-L1413

Reference: https://en.wikipedia.org/wiki/Telephone_numbers_in_French_Polynesia

I also tried entering a 6 digit phone but that seemed to fail as well, so not sure where the validation is failing.

**Comment by rahul020691** [comment]
For 9 digit numbers in Cameroon also the Validation fails. hc-11472712

**Comment by katinthehatsite** [comment]
I have another report from the Upworker in Cameroon who also can not secure their account:

<img width="718" alt="Screen Shot 2019-05-08 at 1 12 21 PM" src="https://user-images.githubusercontent.com/25575134/57394224-ef920980-7192-11e9-9737-eeaa7954268f.png">
