### ISSUE TITLE
Tiled Galleries: Expanded styles section in block setting by default

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#29979]
I noticed that “Styles” section is collapsed whenever I select the block. This not really an issue, but it makes hard to discover different style options. Also, I noticed this behavior isn’t matching to other Guten blocks where “main” settings section is always expanded.

#### Steps to reproduce
1. Starting at: Gutenberg editor
2. Add a Tiled Galleries block
3. Check the block settings - styles section is collapsed

#### What I expected

To see styles options. 

#### What happened instead

Styles section appears to be collapsed by default.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/5654161/50833513-eb401600-1383-11e9-8ec2-6433b11dcfcb.png)

**Comment by simison** [comment]
I agree this would be great but since the styles panel is generated by core, we don't really have control over it.

I'll close this since we practically cannot really implement this.

**Comment by simison** [comment]
Noting that since style previews can be kinda heavy to render, they're probably keeping it closed for that reason.
