### ISSUE TITLE
Gutenlypso: Theme support should update when theme changes

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#29982]
#### Steps to reproduce
1. Activate a theme with support for the `alignWide` feature (e.g. Twenty Nineteen).
2. Open `/block-editor` in debug mode.
3. Type `gutenbergState()['core/editor'].settings.alignWide` in the browser console, or insert a block with alignment options such as Image, and check the block toolbar.
4. Make sure you see `true` in the console, and the block has 5 different alignment options (left, center, right, wide, full) in its toolbar.
5. Now change theme into one that doesn't support `alignWide` (e.g. Planes).
6. Navigate again in the Block Editor.

#### What I expected

The block has only 3 alignment options (left, center, right), and `gutenbergState()['core/editor'].settings.alignWide = false`.

#### What happened instead

The block has 5 different alignment options (left, center, right, wide, full), and `gutenbergState()['core/editor'].settings.alignWide = true`.

#### Context / Source

The theme support is requested here:

https://github.com/Automattic/wp-calypso/blob/1113c84911876df72d58e5e1e6db8d87032acd6a/client/gutenberg/editor/main.jsx#L226-L236

We should probably invalidate `requestActiveThemeSupport` whenever the theme changes (see the [`calypso-store`](https://github.com/Automattic/wp-calypso/tree/1113c84911876df72d58e5e1e6db8d87032acd6a/client/gutenberg/editor/calypso-store) for how we keep track of the site changes for [resetting the Gutenberg resolvers](https://github.com/Automattic/wp-calypso/blob/1113c84911876df72d58e5e1e6db8d87032acd6a/client/gutenberg/editor/controller.js#L113-L127)).

**Comment by gwwar** [comment]
@dmsnell do you happen to know if there's a value we can pass to indicate that this is still loading, or does code here expect this value to be available already?

**Comment by Copons** [comment]
🤔 I can't seem to be able to repro anymore.
Might be because I tested this in the middle of my working on https://github.com/Automattic/wp-calypso/pull/29984, so maybe there was something messed up there that caused this.

We still need to invalidate the `requestActiveThemeSupport` cache on theme change though.

**Comment by rodrigoi** [comment]
When implementing `requestActiveThemeSupport` I considered theme change an edge case. Users do not change themes all the time, when they do I think it's more likely they go into the customizer than into the editor (the call to action after theme change is to... customize) and the cache get's invalidated (because of the page reload when loading the customizer).

I don't think we should give this much thought.

**Comment by Copons** [comment]
I agree that this is now of a lower priority, but...

> page reload when loading the customizer

does it? 🤔 
I've just tried with the console open, and logs persist when I enter and leave the Customizer (as opposed, for example, when I click and follow through Visit Site in the sidebar).

**Comment by gwwar** [comment]
Fixed by the new integration
