### ISSUE TITLE
Color Scheming: WordPress logo for MySites link in Masterbar isn't visible on focus

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#29995]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Click on _My Sites_ (make sure the link doesn't loose focus)
3. See how the logo "disappears" (it seems to be super dark blue)

You can also toggle the focus state with your browser devtools, by tabbing through the links or hold a mouse click and move the pointer away before releasing.

#### What I expected

The logo is visible

#### What happened instead

The logo isn't visible

#### Screenshot / Video

<img width="210" alt="screenshot 2019-01-08 at 20 15 44" src="https://user-images.githubusercontent.com/9202899/50853524-c008f700-1382-11e9-9d94-c40a2b146fcc.png">
<img width="134" alt="screenshot 2019-01-08 at 20 16 21" src="https://user-images.githubusercontent.com/9202899/50853525-c008f700-1382-11e9-8db5-509c6b9ef662.png">

#### Context / Source

discovered by accident

**note:** prior to our new color scheme the logo turned blue on focus (not white)

**Comment by flootr** [comment]
@drw158 do you have feedback on which color to use here?

**Comment by flootr** [comment]
apparently the same is true for the _Reader_ link

<img width="170" alt="screenshot 2019-01-08 at 20 22 20" src="https://user-images.githubusercontent.com/9202899/50853660-255ce800-1383-11e9-974c-45ab080cdf02.png">

**Comment by drw158** [comment]
I think the icon should always be white. This seems to have different behaviors on different browsers. Chrome is not affected, Firefox blinks, and Safari seems to do as you describe.

**Comment by blowery** [comment]
Looks like this is because the gridicon is using `fill: currentcolor` and that's resolving differently on safari?
