### ISSUE TITLE
Color Scheming: browser notification "enable" link in notice is not readable

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#29994]
#### Steps to reproduce
1. Make sure your browser is blocking notifications for WP.com
2. Go to _/me/notifications_
3. Have a look at the link to enable browser notifications in the notice

#### What I expected

Link with enough contrast to background

#### What happened instead

Link does not have enough contrast (dark blue on dark grey)

#### Screenshot / Video

<img width="774" alt="screenshot 2019-01-08 at 20 11 23" src="https://user-images.githubusercontent.com/9202899/50853120-a915d500-1381-11e9-9057-7f9a7f556517.png">

#### Context / Source

by accident

**Comment by flootr** [comment]
@drw158 do you have feedback on which colors to use?

**Comment by drw158** [comment]
If it's an action in the notice, it should look like this (light gray)

![screen shot 2019-01-08 at 1 19 18 pm](https://user-images.githubusercontent.com/618551/50853523-13118880-1348-11e9-9b9c-0af15a5de6f2.png)

If it's a link inside the notice, it should look like this (white with underline)

![screen shot 2019-01-08 at 1 20 16 pm](https://user-images.githubusercontent.com/618551/50853563-27558580-1348-11e9-94d8-aa4f2789020d.png)
