### ISSUE TITLE
Olark: Stop using Noticons

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#30]
We should try to remove Noticons from the Olark CSS. The solution is to use SVG for the gridicons. The structure of the Olark markup may pose a challenge for us. For example, at present, we're using `::before` selectors with `content` attributes, and @dllh thinks the svg solution works better when you can use `background` attributes, but there may be a way to work within Olark's markup after all.

We'll need to export SVG for the chat icon (the `\f108` character in <a href="http://genericons.com/">genericons</a>).

We'll then need to see if we can work within Olark's current markup and the current CSS or whether we can use CSS that'll let us target background attributes rather than `::before` pseudoclass attributes. @dllh had a partially working solution along these lines:

```
url("data:image/svg+xml;utf8,<svg fill='" + $blue-medium + "' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path fill='none' d='M0 0h24v24H0z'/><path d='M9 19.414l-6.707-6.707 1.414-1.414L9 16.586 20.293 5.293l1.414 1.414'/></svg>");
```

However, that didn't work in IE, so we'll want to pay particular attention to that use case.

More at https://wpcalypso.wordpress.com/devdocs/docs/icons.md

**Comment by lancewillett** [comment]
Is this one still "High" priority? We're reviewing priorities and narrowing down the list to things currently being addressed — last update here was January 4th 2016.

**Comment by dllh** [comment]
From my perspective, no. It was high priority during the time we were working on this feature, but wound up not making the cut. Fine to downgrade to whatever seems appropriate.

**Comment by designsimply** [comment]
Closing because Olark was removed in #12432.
