### ISSUE TITLE
Tiled Gallery: Adjust columns attribute when images are removed

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#30015]
We don't allow the range control for columns to be greater than the number of images in the Gallery, but if we've set it and remove images, the columns attribute can be greater than the images. We should ensure that the columns attribute and the range control are not greater than the number of images.

## Steps to reproduce

1. Add a number of image to a Tiled Gallery (8).
1. Pick a view with an adjustable columns setting (circles).
1. Set the columns to the maximum.
1. Using "Edit Gallery" from the block toolbar, remove images.
1. The images in the gallery are updated, but the maximum columns in the sidebar is not. This is the bug.

**Comment by simison** [comment]
I'm not able to replicate this.

When setting columns to maximum and then removing images, `columns` in both attributes and in slider control always matches the new number of images.

Anything I'm missing?

**Comment by sirreal** [comment]
> I'm not able to replicate this.

@simison I've updated with some decent testing instructions. It's when images are removed via the media modal, I've observed it both in Calypso and WP Admin.

This is likely related to #30065. It seems to be related with keeping the media modal and the block in sync.

**Comment by simison** [comment]
Thanks! Seems like this is happening with core block as well. Opened an issue at upstream: https://github.com/WordPress/gutenberg/issues/13423
