### ISSUE TITLE
Color Schemes: New notification dot icon has very low contrast

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#30025]
The new color schemes functionality introduced a pink-ish color for the new notification icon, which has very low contrast rate, compared to the background. 

![image](https://user-images.githubusercontent.com/184938/50901028-a49ff980-141f-11e9-87cd-917f177e69e2.png)

It's very hard to see against the blue background and strains the eyes. 

To illustrate a bit better:

![screenshot 2019-01-09 at 14 49 04](https://user-images.githubusercontent.com/184938/50901072-c7321280-141f-11e9-83c2-b79767102cef.png)

I also tried to change the color scheme, in order to change the dot color, but unfortunately, when switching the color scheme, the dot color doesn't change.

**Comment by flootr** [comment]
asking @drw158 for design feedback

**Comment by flootr** [comment]
will probably be fixed with #30003

**Comment by drw158** [comment]
I went back and forth on this color. Before, there was a similar vibrating effect with the orange and blue. @flootr let's change it to the 300 value to lighten it up and make it not so bright. (--color-accent-300)

**Comment by drw158** [comment]
@bisko let us know if the color is better for you now

**Comment by flootr** [comment]
closing for now - @bisko feel free to reopen in case you think the solution shipped with #30050 doesn't work
