### ISSUE TITLE
Color Schemes: too much accent color (i.e., pink) in the media modal

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#30026]
When selecting multiple images in Media Modal, e.g., for a Tiled Gallery block, there is a lot of accented (pink) UI elements there:

<img width="745" alt="screenshot 2019-01-09 at 13 56 00" src="https://user-images.githubusercontent.com/664258/50901089-6f8fa900-1417-11e9-9f03-8d35f726aae5.png">

The primary call to action there is "Insert", which fully deserves the color, but I'm not so sure about the "Edit" button and the selection markers.

**Comment by drw158** [comment]
I agree Insert is the main action, and Edit could even be changed to a default button. Adding an icon the edit button might make it better.

I think in this case, selecting the images is a good use of the accent color — it's a temporary state activated by the user, and it's something they must take an action on. Being able to see those selected images is important at that moment, and having it the same color as the insert button ties the images to the button.

**Comment by flootr** [comment]
> I agree Insert is the main action, and Edit could even be changed to a default button.

What about the `/media` section? There's no `insert` action and I wonder if the primary action there is _Edit_? Do we want to align both views or are we okay having a different button for _Edit_?

<img width="289" alt="screenshot 2019-01-10 at 10 33 47" src="https://user-images.githubusercontent.com/9202899/50959497-63f9bc00-14c3-11e9-89df-683700262cbf.png">

**Comment by drw158** [comment]
For the media lib, Add New should be the main action. In the media modal, it should be Insert.

In order to align these 2 screens I think:

- make Edit a default button on both screens
- Add New is primary (pink) in the media lib, default in the modal
- Insert is primary in the modal
