### ISSUE TITLE
SDK / Gutenblocks: include .pot file with built blocks

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#30048]
#### Background

> Jetpack blocks live as compiled files here:
> https://github.com/Automattic/jetpack/tree/branch-6.8-built/_inc/blocks
>
> We then extract strings from those files on release, and generate this file from it:
> https://github.com/Automattic/jetpack/blob/branch-6.8-built/_inc/jetpack-strings.php
> 
> This is done here:
> https://github.com/Automattic/jetpack/blob/branch-6.8/gulpfile.babel.js#L197
>
> However, the automatically generated file does not actually include any strings from the blocks right now. We have to go back to the 6.7 release to actually get strings from the blocks files:
> https://github.com/Automattic/jetpack/blob/branch-6.7-built/_inc/jetpack-strings.php
> (you can see the files coming from the blocks files by looking at the comments, like `// _inc/blocks/editor.js:25`)
> 
> Something broke in the process in Jetpack 6.8. It seems the format of the strings outputted in the built files by the SDK has changed, so `i18n-calypso` can’t pick them up anymore.

Ideally, to work around this problem **we could use the tools now available in Calypso to create a .pot file that should ship with the blocks we release on npm.**

PR to fix this: https://github.com/Automattic/wp-calypso/pull/30303

From @akirk:

> Gutenberg indeed has its own translatable string extractor: https://github.com/WordPress/gutenberg/tree/master/packages/babel-plugin-makepot
> And for Calypso we have https://github.com/Automattic/wp-calypso/tree/master/packages/babel-plugin-i18n-calypso
>
> What we’ll do there is to run babel on everything and makepot will extract the `@wordpress/i18n` style strings and the i18n-calypso plugin with the `translate()` style strings and then use the command line tool `msgcat` to merge the files
> `CALYPSO_ENV=production NODE_ENV=build_pot npm run build-client && find build/i18n-calypso -name \\*.pot | msgcat -f- -o calypso-strings.pot`
> 
> This is not yet in production but will be available soon

Related: #28583
PR to fix this: #29429

Once the .pot file is available with the blocks, we'll need to update the way Jetpack extracts strings from the blocks to take that into account.

Related discussion: p1547026515746300-slack-jetpack-gutenberg

**Comment by simison** [comment]
Just to confirm it here; @zinigor you're working on this?

**Comment by zinigor** [comment]
Yes, sorry, I should have assigned this to myself. I'm going to publish a PR soon that fixes it in Jetpack.

**Comment by simison** [comment]
Higher level issue here: https://github.com/Automattic/wp-calypso/issues/27814

**Comment by simison** [comment]
So this issue as it's written, is actually two separate tasks?

- generating pot files from SDK (PR https://github.com/Automattic/wp-calypso/pull/30303)
- fixing issues around string extractor (PR https://github.com/Automattic/wp-calypso/pull/29429)

Let's make sure to open a new one for the latter before closing this.

**Comment by scruffian** [comment]
Closing, since the code lives in Jetpack this will happen a different way: Automattic/jetpack#11817
