### ISSUE TITLE
Gutenberg: Clicking "Write" on masterbar on live site shows Calypso editor instead

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30049]
#### Steps to reproduce 

- Start with a Gutenberg enabled WordPress.com site
- Click `Write` at the top right of the WordPress.com masterbar when viewing the live site

![screen shot 2019-01-09 at 21 56 20](https://user-images.githubusercontent.com/18581859/50913022-793a0080-1459-11e9-811c-f725985457f1.png)

#### What is expected 

The editor launches at https://wordpress.com/block-editor/post like how it launches for `Add` next to `Blog posts`

#### What happens instead 

The editor loads at https://wordpress.com/posts

I don't see an existing report for this, but if there is one, happy to be pointed at it.

h/t @iamgabrielma for catching this. p1HpG7-67L-p2 #comment-29868

**Comment by gwwar** [comment]
> On Atomic though, with Gutenberg opted-in, it takes me to Gutenberg on wp-admin.

We still need to untangle flows. Atomic sites use the Classic plugin which has more fine grained controls (eg per post) and relies on that for editor settings in wp-admin vs the api endpoint. I can link to a related post once Kirk writes the problem up.

**Comment by gwwar** [comment]
I think it'd be worthwhile to update the front end links if possible.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
