### ISSUE TITLE
Gutenberg: HTML changes in Classic block are not visible on the visual editor

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#30044]
#### Steps to reproduce
1. In a Classic Block, select "Edit as HTML"
2. Paste some HTML 
3. Select "Edit visually"
4. Changes are not visible on the editor but they are published/saved 

#### What I expected
Any edits done on the HTML view should display on the Visual view

#### What happened instead
The HTML changes are not showing on the Visual editor

#### Browser / OS version
Tested on Chrome Version 71.0.3578.98 and Safari Version 12.0.2 

#### Screenshot / Video
The following recording shows 2 different HTML edits, none of them show on the visual editor:

http://cld.wthms.co/FFLzP4

#### Context / Source
This only happens on Calypso, the HTML edits show well on the Visual editor of wp-admin

**Comment by gwwar** [comment]
Please re-open if folks are still finding this an issue

Current behavior in the block-editor

![classic](https://user-images.githubusercontent.com/1270189/61241159-d445fc00-a6f7-11e9-8720-3b49530df61d.gif)
