### ISSUE TITLE
Classic Editor: Horizontal line does not display in the visual tab on the editor

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#30057]
#### Steps to reproduce
1. Open the editor for a post or page
2. Insert a horizontal line using the Horizontal Line button: http://cld.wthms.co/L9s2o3

#### What I expected
To see the horizontal line display in the visual editor

#### What happened instead
The horizontal line does not display: http://cld.wthms.co/lYiIje
The horizontal line `<hr />` code is visible in the HTML tab, however, and the line is visible on the published post.

#### Browser / OS version
Tested on Mac OS Mojave 10.14, both in Chrome 71.0.3578.98 and Safari 12.0 (14606.1.36.1.9)

I tested in /wp-admin and could not reproduce - appears to be specific to Calypso only. 
I tested on both a simple and AT site. 

#### Context / Source
User reported in #9023407-hc
Follow up ticket #1704800-zen

**Comment by torres126** [comment]
Report here: https://en.forums.wordpress.com/topic/new-wordpress-colors-what-is-going-on/
