### ISSUE TITLE
Jetpack: General settings disconnect button needs margin right 

### ISSUE THREAD

**Issue by kjbenk** [Automattic/wp-calypso#3005]
The Jetpack panel within the General settings has multiple button actions within the title of this panel.  Th issue is that there is no margin between these two buttons so they just sit next to each other.  I am not sure if this is a general problem with having multiple buttons within a panel heading.

![Jetpack Disconnect button spacing](https://cldup.com/CIMBVLO-uE.png)

Steps to re-create:

1. Go to the general setting for a site
2. Scroll down until you see Jetpack panel

**Comment by jeremeylduvall** [comment]
Thanks for the report @kjbenk! Here's how this is appearing on my side:

<img width="414" alt="screen shot 2016-02-21 at 11 36 46" src="https://cloud.githubusercontent.com/assets/7240478/13204537/c6b2f9b0-d88f-11e5-83d6-3db2355ea077.png">

Can you let me know if this is still appearing crowded on your site? 

(Note: I ran into this at wpcalypso.wordpress.com where we force `manage/option_sync_non_public_post_stati` to `true` — [ref](https://github.com/Automattic/calypso-pre-oss/blob/2a0ccfcfa8acc78ca11abc5f8b9740a590c26f94/config/wpcalypso.json#L19))

**Comment by kjbenk** [comment]
I guess it was fixed within a commit since I posted the bug :)  I am going to close out this issue since it has been fixed.
