### ISSUE TITLE
App Banner: Deep links to specific blogs don't take you to that blog

### ISSUE THREAD

**Issue by jkmassel** [Automattic/wp-calypso#30068]
#### Steps to reproduce
1. See mobile banner in the context of a specific blog
2. Tap the banner

#### What I expected
Opens that blog in the app

#### What happened instead
Opens the last blog that was used

#### Context / Source
Found via #dogfooding.

Change needs to happen in https://github.com/Automattic/wp-calypso/blob/112fb8f4fb3e30854897cf908d53fcd86344008a/client/blocks/app-banner/index.jsx, then in the mobile apps.

**Comment by rachelmcr** [comment]
Related issue: https://github.com/wordpress-mobile/WordPress-Android/issues/8572

As noted there, this is the current intended behavior (internal ref: p5T066-IL-p2). The majority of users have a single site, so this works for most cases.
