### ISSUE TITLE
Domain: Going to "/oauth" will not result in a 404 or anything and a blank page is shown.

### ISSUE THREAD

**Issue by kjbenk** [Automattic/wp-calypso#3007]
If you go directly to a url like "http://calypso.localhost:3000/oauth" there is no 404 page or error of any kind.  I know this is not a valid page but shouldn't this at least so a 404 error?

![no 404 page](https://cldup.com/3UCnySr4uG.png)

**Comment by lamosty** [comment]
Hey @kjbenk, thanks for reporting this! It is being worked on in #3453. I'm closing this issue in favor of that PR.
