### ISSUE TITLE
Browser notifications: Color issue on link/copy when enabling browser notifications

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30079]
#### Steps to reproduce 

- Visit https://wordpress.com/me/notifications
- Disable browser notifications if already enabled
- Open a private/incognito tab and visit https://wordpress.com/me/notifications again (private/incognito just because I been able to see the popup notice shown below on regular tab)
- Notice the text that reads `Your browser is currently set to block notifications from WordPress.com. View Instructions to Enable` if the browser is set to block WordPress.com notifications
- Click `View Instructions to Enable` for a popup to appear

#### What is expected 

- The copy `View Instructions to Enable` is readable with expected color
- The content on the popup that appears is readable as well

#### What happens instead 

- The copy `View Instructions to Enable` is not readable with expected color
- The content on the popup that appears is not readable as well

<img width="755" alt="screenshot 2019-01-10 at 15 18 14" src="https://user-images.githubusercontent.com/18581859/50960309-198c3580-14eb-11e9-9a95-6ff4701f5039.png">

<img width="827" alt="screenshot 2019-01-10 at 15 18 23" src="https://user-images.githubusercontent.com/18581859/50960307-18f39f00-14eb-11e9-91b9-a7b4f884a953.png">

These can be seen only when highlighted, which is not expected.

<img width="758" alt="screenshot 2019-01-10 at 15 18 42" src="https://user-images.githubusercontent.com/18581859/50960296-142eeb00-14eb-11e9-8a05-01208d74f97a.png">
<img width="826" alt="screenshot 2019-01-10 at 15 18 33" src="https://user-images.githubusercontent.com/18581859/50960298-14c78180-14eb-11e9-8359-22af458c805b.png">

**Comment by drw158** [comment]
@blowery @flootr since we touched something similar recently.
