### ISSUE TITLE
Classic Blue: Color on hover over `Add` on selected tab, is hard to read

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30087]
#### Steps to reproduce 

- Start at https://wordpress.com/me/account
- Choose `Classic blue` theme
- Visit https://wordpress.com/ 
- Click on `Blog posts` or `Site pages` tab on the left
- Hover over `Add` 

#### What is expected 

`Add` is readable

#### What happens instead 

`Add` is not readable. Hovering over `Add` for unselected tabs is fine though.

<img width="333" alt="screenshot 2019-01-10 at 18 34 13" src="https://user-images.githubusercontent.com/18581859/50970424-51a17180-1507-11e9-80cf-f568c224585e.png">
<img width="357" alt="screenshot 2019-01-10 at 18 34 11" src="https://user-images.githubusercontent.com/18581859/50970425-523a0800-1507-11e9-9e2a-13a1429feeb8.png">

This happens only for `Classic Blue` theme and not `Classic Bright`

<img width="313" alt="screenshot 2019-01-10 at 18 39 50" src="https://user-images.githubusercontent.com/18581859/50970448-6978f580-1507-11e9-9b2b-1ef728e6d569.png">
<img width="320" alt="screenshot 2019-01-10 at 18 39 48" src="https://user-images.githubusercontent.com/18581859/50970449-6978f580-1507-11e9-9d05-d3c3f5578155.png">

**Comment by drw158** [comment]
I see that the variable being used here is referencing white for some reason.

![screen shot 2019-01-10 at 10 24 36 am](https://user-images.githubusercontent.com/618551/50982212-3ceeba80-14c2-11e9-87fc-53f106eb051b.png)

**Comment by flootr** [comment]
should be fixed by #30150
