### ISSUE TITLE
Gutenberg: Previewing Draft Post in Calypso Returns Error

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#30090]
#### Steps to reproduce
1. jiripesik.com - SU or SSP as pesikj.
2. Go to My Site > Blog Posts > Drafts and edit the "Walk through the Walley of Střela" post.
3. Click Preview.

#### What I expected

The post preview to appear.

#### What happened instead

This error appeared instead:
Something's Missing
The content you're looking for doesn't exist at this address. Continue browsing, or try searching for your content using the form below.

The preview sometimes loads for me after refreshing, but the user only sees the error. I have not been able to reproduce on a test site, but can reproduce on the user's site.

#### Browser / OS version

User: Windows 10, Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Me: macOS Mojave 10.14.2 (18C54), Chrome Version 71.0.3578.98 (Official Build) (64-bit)

#### Screenshot / Video

https://cloudup.com/czKRDkwj_6y

#### Context / Source

#user-report in #4940300-hc

**Comment by arunsathiya** [comment]
@juliasydnor Feels to be the same issue as this one - https://github.com/Automattic/wp-calypso/issues/29324

I tried to use the `Visit site` button at the top right of the Calypso popup, and use the workaround on that issue but it does not work at the moment. [Video](https://cloudup.com/c7nTr9sF-eH).

https://github.com/Automattic/wp-calypso/issues/29324 was also not tracked properly. Updated the labels and project now. 

Can you let the user know that we are aware of this issue, and close this issue as a duplicate, please?

**Comment by juliasydnor** [comment]
I've already notified the user. That issue didn't come up when I searched for open issues. Marking this one as closed.
