### ISSUE TITLE
Gutenberg: Embeds: Amazon embed is very half-baked

### ISSUE THREAD

**Issue by Tooxic** [Automattic/wp-calypso#30107]
#### Steps to reproduce
1. Go to a Gutenberg-enabled WordPress.com site.
2. Start a new Gutenberg post.
3. Add a WordPress embed block.
4. Paste a link to a WordPress post and click the Embed button.
5. See an error in the editor.
Preview the post and see the plain link to the post.

#### What I expected
To embed a amazon link in to a post.

#### What happened instead
It says "Sorry, we could not embed that content."

#### Browser / OS version
Chrome 71.0.3578.98 
on Windows 10

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/33166817/50998634-5c203300-1528-11e9-971c-7e1fb5e8b15a.png)

**Comment by codebykat** [comment]
It does a weird half-hearted job of this now:

<img width="596" alt="Screen Shot 2019-03-12 at 4 08 11 PM" src="https://user-images.githubusercontent.com/52152/54242222-13add300-44e1-11e9-8b7d-c1ad7105d5f7.png">

Like it converts it to an embed but the embed literally just displays the link.

**Comment by gwwar** [comment]
Amazon Kindle embeds are supported, but now other products links should fallback to a plain link. Going to close this out for now, but we could add an enhancement issue in core for other products.
