### ISSUE TITLE
Gutenberg: Embeds: Spotify embed does not work

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/wp-calypso#30129]
#### Steps to reproduce
1. Add a new Spotify Embed block and paste a Spotify link such as https://open.spotify.com/playlist/37i9dQZF1DX2A29LI7xHn1

Result:

![screen shot 2019-01-11 at 1 14 11 pm](https://user-images.githubusercontent.com/6520461/51051984-66334780-15a3-11e9-9daa-ef22c43a19bf.png)

#### Browser / OS version

Chrome 71 on macOS

**Comment by codebykat** [comment]
I just tested this and it works fine for me in both Chrome and FF on OSX:

<img width="575" alt="Screen Shot 2019-03-12 at 3 45 53 PM" src="https://user-images.githubusercontent.com/52152/54241397-017e6580-44de-11e9-8d51-daf6fae96899.png">

(Your playlist seems defunct, but it worked with https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX3WvGXE8FqYX?si=H57CpzyuTDG0kllQhskeYg )
