### ISSUE TITLE
Mastercard Logo Outdated

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#30137]
#### Steps to reproduce
1. Starting at any URL which provokes a purchase, such as the plan page or the checkout
2. See the options for payments

#### What I expected

The Mastercard symbol should be used. 

![screenshot_20190112-205507](https://user-images.githubusercontent.com/43215253/51078404-6703d080-16ac-11e9-8ade-12ab54072ef0.jpg)

#### What happened instead

Old logo

![fgjhjhghgjfhjgf](https://user-images.githubusercontent.com/43215253/51078413-7125cf00-16ac-11e9-83b3-b11089670d24.png) 

#### Context / Source

Made a payment for renewing my domain today and noticed it then. 

I'd like to try having a go at resolving this. :)

**Comment by simison** [comment]
Also on plans pages: `https://wordpress.com/plans/:site`

<img width="587" alt="image" src="https://user-images.githubusercontent.com/87168/51101354-fdd2a900-17e2-11e9-8364-8d475a2d7b8b.png">

**Comment by torres126** [comment]
I think that #30138 should fix all scenarios of this across Calypso, including the ones on the plans page, because of this [here](https://github.com/Automattic/wp-calypso/blob/master/client/components/payment-logo/style.scss#L15).

**Comment by torres126** [comment]
I'm not sure why #30138 didn't take care of this, but it doesn't seem like this has been fixed. I can't exactly see why that's the case though. :thinking:
