### ISSUE TITLE
Incorrect upcoming charges date within Billing History

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#30142]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/billing (while logged in as the user).
2. Billing History > Upcoming Charges

#### What I expected
13th of December, 2019 should be the date of the upcoming charge of the user's Premium plan.

#### What happened instead
The upcoming charge date is 1 January, 1970

![Upcoming charges screenshot](https://cdn-std.dprcdn.net/files/acc_596324/uCUfwZ)
Full image: https://cld.wthms.co/uCUfwZ

User ID: 141943715
Chat: 5085244-hc

_Please note, as of the 14th of January the upcoming charge date is now correct._

**Comment by thehenrybyrd** [comment]
Another case of this in 12006905-hc, 1953999-zen. User ID: 94279891
Again, the incorrect date of Jan 1, 1970 can be seen under Billing History > Upcoming Charges.

<img width="759" alt="Screen Shot 2019-04-15 at 1 47 52 PM" src="https://user-images.githubusercontent.com/15107387/56127595-36228880-5f86-11e9-9f7d-dfc0cb30f715.png">


I was not able to reproduce the issue in my own account or a test account with the Premium plan.
