### ISSUE TITLE
Stats: Map Gives "Not a Valid Colour String" Error on Some Devices

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#30148]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats
2. Try viewing the map

#### What I expected

The map and graph to appear. 

#### What happened instead

> You can see that the daily stats do not show up on the timeline. (before I had 2 bars — views & visitors — for each day, or week…). There is no map and there is no colour (before yellow) vertical bar in front of today post (30 years ago — former…)

Several issues with stats not loading, and most notably an error which says "is not a valid colour string". 

![download 14](https://user-images.githubusercontent.com/43215253/51098417-18485a80-17c2-11e9-82cb-3c5f6a554510.jpeg)

From the reports so far, it looks like that both issues either occur at once, or none occur at all. 

#### Browser / OS version

So far, most the reports I've seen have either not given their browser or their OS. However, the user who took the screenshot above said they use Windows 7 and Internet Explorer 11. One other user said they're using Internet Explorer too. 

#### Context / Source

I have not been able to reproduce this successfully, however I've seen several reports on it: https://en.forums.wordpress.com/topic/dashboard-and-statistics/
https://en.forums.wordpress.com/topic/none-valid-colour-string-on-stats-page/
https://en.forums.wordpress.com/topic/stats-345/
https://en.forums.wordpress.com/topic/random-color-change-to-a-lot-of-things/page/2/#post-3248000
https://en.forums.wordpress.com/topic/changing-colors-lost-functionality/

(cc @flootr, this might be related to #30078 since this issue wasn't reported before then; the error is the same as the one in #30066)

**Comment by flootr** [comment]
> this might be related to #30078

It's probably related. We derive the color string to use [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/geochart/index.jsx#L122-L127) from CSS custom properties. There may be a case where the color variable is not defined or empty?

**Comment by blowery** [comment]
@flootr yeah, IE11 does't support css custom properties at all. We'll likely have to feature detect and branch there.

**Comment by flootr** [comment]
> @flootr yeah, IE11 does't support css custom properties at all. We'll likely have to feature detect and branch there.

Makes sense. As IE11 users only get Classic Bright we should be able to safely apply it as a fallback

**Comment by csonnek** [comment]
@flootr I have another user using Classic Bright in 1707735-zen having the exact same issue - using Windows 7 Professional w/ SP1 and IE 11

Can you advise if this has been fixed for users so I can send them an update?

**Comment by torres126** [comment]
Just to note, I've followed up in the forum threads where this issue was originally reported, and those who were experiencing the problem earlier have said it's working fine now.
