### ISSUE TITLE
Store Services: Prompt for credit card in label purchase sidebar

### ISSUE THREAD

**Issue by dechov** [Automattic/wp-calypso#30170]
Present the label purchase dialog even if a payment hasn't already been selected (see Automattic/woocommerce-services#1115, "Solution 2") and have a credit card selector as the final step of the label purchase flow. It should no longer be necessary to visit settings for this purpose, other than to modify the default. _(Description adapted from https://github.com/Automattic/wp-calypso/pull/22890, a previous attempt at solving this.)_

Rolling out this enhancement depends on the prior merge and _release_ of https://github.com/Automattic/woocommerce-services/pull/1569, or else on a client-side feature flag.

With a card already saved, compact summary (as already implemented on settings page):
<img width="436" alt="screen shot 2019-01-11 at 3 28 19 pm" src="https://user-images.githubusercontent.com/1867547/51069180-0c10a180-15f8-11e9-9e7d-75f6c42562ba.png">

"Choose a different card":
<img width="443" alt="screen shot 2019-01-14 at 8 04 37 pm" src="https://user-images.githubusercontent.com/1867547/51157580-79b60b00-184e-11e9-8590-143dc700bfb2.png">

Full sidebar after rate retrieval:
<img width="439" alt="screen shot 2019-01-14 at 8 05 09 pm" src="https://user-images.githubusercontent.com/1867547/51157585-80448280-184e-11e9-896a-d0097648c7cc.png">

**Comment by madeincosmos** [comment]
also reported in 1816739-zen

**Comment by v18** [comment]
> Rolling out this enhancement depends on the prior merge and release of Automattic/woocommerce-services#1569, or else on a client-side feature flag.

@dechov for the Calypso interface, will we need this change to be backwards compatible with older WCS plugin versions?

**Comment by dechov** [comment]
@v18 I don't believe so, as long as that plugin change is released ahead of the Calypso change.

**Comment by v18** [comment]
@dechov is it not possible for store owners with an older version of the plugin to access the Calypso interface?

e.g. what about atomic site users? or people who, after having set up a store, install an earlier version? 

we should make sure it fails gracefully.

**Comment by dechov** [comment]
@v18 Ah, OK – agreed it should fail gracefully – though I feel like we've rolled out changes to Calypso in the past based on the assumption that the plugin will be automatically upgraded within about a day.

Hm, it might be tricky without further plugin changes: receiving a payment method ID and ignoring it in favor of the previously saved one would not be failing gracefully. We can just have the plugin return some bit of state indicating (implicitly at least) support for payment method in the purchase request, unless there's a better approach.

**Comment by lancewillett** [comment]
Closing as this one looks out of date now.

(Cleaning up older issues as part of a GitHub scrub.)

If still valid, please re-open with a comment. Thanks!
