### ISSUE TITLE
Allow transfers of G Suite subs from one site to another on same account

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/wp-calypso#30180]
Users often transfer domains from one site to another within the same WordPress.com account. At the moment there's no way to also transfer the associated G Suite account as well to the other site. It doesn't affect the G Suite account at all, but it does make for a messy Store Admin on our end and often results in confusion on the user's end when they view their Purchases page. 

Since G Suite is linked to a domain and not to a particular site, it would be great if we could "unlink" G Suite from a site in Store Admin/Purchases, or barring that, make it possible to move the G Suite upgrade from one site to another in Store Admin. 

See p2MSmN-6XH-p2 for the most recent reference.

#### Context / Source
#user-report

**Comment by belcherj** [comment]
Fixed
