### ISSUE TITLE
Disabled SplitButton styles are broken after the Color Schemes update

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#30206]
Look at the devdocs page for the `SplitButton` component: https://wpcalypso.wordpress.com/devdocs/design/split-button

The styles for disabled variants are broken:

<img width="518" alt="screenshot 2019-01-17 at 12 45 20" src="https://user-images.githubusercontent.com/664258/51316779-f961f680-1a55-11e9-91fb-74019f6aed85.png">

**Comment by flootr** [comment]
@drw158 could you give design feedback on which colors to use for the _disabled_ state of primary buttons?

**Comment by drw158** [comment]
Have these always been broken? Here is an older screenshot:

![screen shot 2019-01-17 at 1 01 53 pm](https://user-images.githubusercontent.com/618551/51342012-52328e80-1a58-11e9-86cb-7798c7380a1c.png)

**Comment by drw158** [comment]
Looks like this is intended. The pink buttons are not disabled, but the faded ones are disabled:

<img width="418" alt="screenshot 2019-01-17 at 14 22 24" src="https://user-images.githubusercontent.com/9202899/51321563-5f08af80-1a63-11e9-84fe-428cdaac3ad7.png">

I suppose there is nothing to really fix here, although I do think our disabled states could use some work:

![screen shot 2019-01-17 at 1 49 29 pm](https://user-images.githubusercontent.com/618551/51344785-033c2780-1a5f-11e9-9ec2-9358ece85797.png)
![screen shot 2019-01-17 at 1 48 57 pm](https://user-images.githubusercontent.com/618551/51344792-059e8180-1a5f-11e9-9491-6cbe1420bc3c.png)

I think the only thing to do here is to update the old varibles to use the new red colors.

**Comment by drw158** [comment]
@flootr Let's remove color from the primary and default scary buttons, similar to how the blue button have their color removed when disabled.

So, by doing this all of these four butons types will look the same when they are disabled

- Button primary disabled
- Button default disabled
- Button scary primary disabled
- Button scary default disableld

![screen shot 2019-01-17 at 1 58 28 pm](https://user-images.githubusercontent.com/618551/51345323-43e87080-1a60-11e9-9b89-0a3e7dfa78cb.png)
