### ISSUE TITLE
Accessibility: Low contrast in All Time Views table

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#30216]
Some of the values in the All Time Views stats table are very low contrast, with dark grey text on a fairly dark blue background, e.g.

![image](https://user-images.githubusercontent.com/1990037/51330348-3f778400-1a6f-11e9-8f60-35bd85979db5.png)

#user-report

1714206-zen

**Comment by drw158** [comment]
Looks like we need to switch to white text on some of these.
