### ISSUE TITLE
Missing thumbnails from the post publish on Facebook.

### ISSUE THREAD

**Issue by tarunvijwani** [Automattic/wp-calypso#30230]
We have multiple users reporting the issue that their thumbnails are missing the from new and old posts as well at the Facebook. Earlier, they had the thumbnail for the old posts.
They all are getting the below error in FB debugger:
```Circular redirect path detected (see 'Redirect Path' section for details)."```

The account details are mentioned here: p1547783743200600-slack-triage

Follow-ups: 1727594-ze , 1727468-zen, 1727467-zen

**Comment by sarahcada** [comment]
Also for follow-up: 1727599-zen
This user I had a different error: `The following required properties are missing: fb:app_id`
But the rest of the issue is the same.

**Comment by edwinho89** [comment]
Similar issue reported on #1727568-zen

However as of current time, it seems the affected user #1727568-zen is working again, clarifying to be sure.
