### ISSUE TITLE
Signup: Not selecting a site type causes a blank style selection step

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#30246]
Type a business type in the site type step, but do not select a popup option and then hit continue:

<img width="725" alt="screen shot 2019-01-18 at 10 49 33 am" src="https://user-images.githubusercontent.com/1464705/51406729-ccbde580-1b0e-11e9-9975-1d238d2d8210.png">

The next style step is blank:

<img width="777" alt="screen shot 2019-01-18 at 10 48 23 am" src="https://user-images.githubusercontent.com/1464705/51406760-e0694c00-1b0e-11e9-81fb-8ed434eb2e11.png">

**Comment by ramonjd** [comment]
#30486 has mitigated this issue. We're still refining the UX around the vertical suggestion list itself.

![_feb-05-2019 17-05-12](https://user-images.githubusercontent.com/6458278/52255871-781cc600-2968-11e9-9145-233eb40314f9.gif)

Feel free to reopen if you notice anything weird.
