### ISSUE TITLE
Signup: I'm not sure if i need to type https://

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#30247]
The domains step in the signup flow makes me feel uncertain if I need to type the http:// part since it's show in the little help graphic underneath. As an aside this should show https:// not http://. :)

<img width="857" alt="screen shot 2019-01-18 at 10 55 44 am" src="https://user-images.githubusercontent.com/1464705/51407034-acdaf180-1b0f-11e9-8f03-fcbff8ba6125.png">

**Comment by torres126** [comment]
I think the `https://` will be updated by (https://github.com/Automattic/wp-calypso/pull/30004/commits/82c84bc7b17e0c73adf9579343525b39c6b09604) in #30004.
