### ISSUE TITLE
Signup: If a site type search returns a single result, select that result

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#30245]
If I search for a business type that only returns one result, auto selecting that result will make the experience feel more natural. It'll mean that the preview will pop up without me having to select it. You'll want to wait until the user has stopped typing for a second though.

<img width="715" alt="screen shot 2019-01-18 at 10 44 10 am" src="https://user-images.githubusercontent.com/1464705/51406458-0510f400-1b0e-11e9-833f-d6d4baeec7ee.png">

**Comment by ramonjd** [comment]
In #30486 we're looking for exact matches in the search results and loading the preview immediately. As mentioned in https://github.com/Automattic/wp-calypso/issues/30246#issuecomment-460524640, we're still working on the UX, but this address this issue for now. 

If not, please feel free to reopen and we'll 👀 

Thanks!
