### ISSUE TITLE
Notifications panel - touch devices - like post icon doesn't change when tapping

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#30257]
#### Steps to reproduce
1. Starting at URL: wordpress.com in Safari on iOS (tested Safari on Mac and not reproducible)
2. Open notifications panel and find notification of a comment on your post
3. "Like" the comment

This happened around the same time as the colour schmes

#### What I expected

The icon changes colour and text changes

#### What happened instead

No visual indicator of like

#### Browser / OS version

Safari on iOS 12

#### Screenshot / Video

https://cloudup.com/cN0UZIIixgr

#### Context / Source
#dogfooding

**Comment by torres126** [comment]
Also reproduceable on Android devices (Samsung Galaxy Tab S2, Chrome 70)

![screenshot_20190121-171936](https://user-images.githubusercontent.com/43215253/51489669-ea09e280-1da0-11e9-8fbb-233457a53338.jpg)

**Comment by alisterscott** [comment]
Thanks @torres126 - I updated the title to indicate this impacts touch devices
