### ISSUE TITLE
Google Ads credit code not displayed

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#30280]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/my-plan/martsolf.net
2. Click on "Generate code" button under Google Ads credit
3. Accept the terms

#### What I expected

To see a generated code.

#### What happened instead

A blank field was displayed, with all other information displaying as if there was a code there

#### Browser / OS version

I used Chrome Version 71.0.3578.98 (Official Build) (64-bit) on MacOS Mojave

#### Screenshot / Video

![screen capture on 2019-01-21 at 10-59-13](https://user-images.githubusercontent.com/7596032/51485263-a47ef280-1d6b-11e9-9382-8d0a42e12717.gif)

#### Context / Source

#user-report in 1717859-zen

Did confirm that the user is US-based and eligible for the credit and manually assigned a code.

This may be related to this issue from last year (although there were codes still available): https://github.com/Automattic/wp-calypso/issues/18120

**Comment by lancewillett** [comment]
I'd suggest the user try again after clearing cookies or maybe a different browser. I tried on a few different sites and was able to see the code appear. Could be intermittent?

Please re-open if you can consistently reproduce the issue across sessions, sites, browsers.
