### ISSUE TITLE
Support User: Sidebar disappears when switching

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#3029]
Reported by @dllh in #2975

![pasted_image_3_02_2016__1_10_pm](https://cloud.githubusercontent.com/assets/416133/12771805/dcb79ad4-ca77-11e5-98c5-15fb67470179.png)

**Comment by dllh** [comment]
The right-hand content pane also didn't update. I was on the reader and clicked to "My Sites" -- which you can see from the highlighting in the masterbar. The sidebar then disappeared and the right-hand content pane stayed the same. The console had the error message `Uncaught TypeError: Cannot read property 'jetpack' of undefined`
