### ISSUE TITLE
Jotform: iframe 0px height

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#30298]
Jotform embed is being displayed with height 0 on published page.  

#### Steps to reproduce
1. https://25082018jupiter.com/jotform-tester/
2. Added an embeded Jotform using both Classic Editor as well as Gutenberg

#### What I expected
Upon publish the Jotform would appear on the page with correct height.  

#### What happened instead
Nothing is displayed.  When looking at the inspector I can see that the iframe is there but the height is set to 0.  If you manually change this height using custom CSS, the page will appear.  

#### Browser / OS version
Firefox, Chome, Safari

#### Screenshot / Video

![screen shot 2019-01-22 at 20 35 15](https://user-images.githubusercontent.com/24914028/51533115-48a88c80-1e85-11e9-86e2-a07ef84e2a0f.png)

#### Context / Source
1737688-zen

**Comment by arunsathiya** [comment]
@joweber123 This seems to be the case on a core Gutenberg install as well, and not something that concerns Gutenberg on WordPress.com. I also don't think Jotform is an embed block that core Gutenberg offers, but you can check with the core folks at `WordPress/Gutenberg` as a OSS citizen (without any a8c links like tickets)

As a side note, the Jotform links shown on https://en.support.wordpress.com/forms/jotform/ are of different format - such links can be used on the `Shortcode` block. I see that @chaitanyamsv has already addressed this ticket with the next steps. 👍🏽
