### ISSUE TITLE
Cart recalculation ignores pre-selected options on refresh

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#30294]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/checkout/testing705633960.wordpress.com/business
2. Select non default subscription length: e.g. 2years
3. Wait for calculation to complete
4. ctrl+r - Refresh the page

#### What I expected
The re-calculated cart totals to match the option selected.

#### What happened instead
The default option was used to calculate totals instead of what was remembered

Hard refresh shift+ctrl+r clears the remembered selection and calculates correctly.

#### Browser / OS version
`Chromium 71.0.3578.98 Arch Linux`

#### Screenshot / Video
![checkout-calc-order](https://user-images.githubusercontent.com/811776/51516243-d6c34980-1e6a-11e9-9b87-e7c6a9b878fe.png)

Note mismatch between pay button and selected option. Sidebar totals match pay button as well (incorrectly)

#### Context / Source
#manual-testing

**Comment by joehdodd** [comment]
I'd like to take this on, but I'm new to the codebase, so I'm trying to get up to speed and am a little stuck.

Using my account to manually test choosing between the two WordPress.com Premium Subscriptions, I was lead to `client/lib/plans/constants.js`. Looking there, I noticed that setting the URL path using the `pathSlug` from the `PLAN_PREMIUM_2_YEARS` constant will cause my plan selection to persist in the "Pay" button and sidebar totals after a reload.

But that's where I'm stuck as I haven't yet understood if/how/why the URL path should change and persist the value of your selection to the "Pay" button and sidebar totals. Hopefully someone can suggest something, or hopefully this sparks an idea for someone else who has more familiarity with the codebase! Thanks. ☺️

**Comment by lsl** [comment]
> But that's where I'm stuck as I haven't yet understood if/how/why the URL path should change and persist the value of your selection to the "Pay" button and sidebar totals.

I'm not sure either. You are right, there is something that could be done with push states to make things a little cleaner.

That said, the bug would still remain - the cart calculation action does not reflect UI state - how that got to be is the bug. Changing the URL would work with/around the bug, it wouldn't really fix it.

I see two potential options:
1. Set the selected option based on URL at render time regardless of previously stored state
2. Block or better yet, restart cart calculation once the non default option is detected in the payment box.

Option 1. is inline with how the cart calculation is currently acting. Option 2. is inline with the idea that application state should be dictating what the cart calculates i.e. cart calculation should **not** dictate what the _user_ has selected in front of them. 

I originally suspected the payment box was driving initial calculation and had assumed the first option was selected on load. Now you've shown me how it is the `pathSlug` making this choice and I see this might be a bit of a bigger issue.

**Comment by lsl** [comment]
Ok, that makes sense.

Specifying the product pathSlug adds the item into the cart and relies on the server to replace whichever plans are currently in the cart.

This makes sense but it makes for a clunky experience.

It's worse if you move from say `/business` to `/premium` in either direction.

Starting to look more like a state tracking bug. Take a look at these components:

`Checkout`, `SubscriptionLengthOption`, `SubscriptionLengthPicker`

Selected value is initially passed down through `props.initialValue` but then changes are bubbled up through the `handleCheck/onClick/handleTermChange` methods. :thumbsup: for naming consistency.

This `handleTermChange` method in the `Checkout` component is initiating the cart change, and its new result does seem to be passed down into the `*Picker` components (see prices updating). 

Taking a guess I see this seems to fix it:

```
# SubscriptionLengthPicker
# client/blocks/subscription-length-picker/index.jsx
- checked={ planSlug === this.state.checked }
+ checked={ planSlug === this.props.initialValue }
```

Now you get to see the selected option flick back to the "right" selection once cart calculation finishes. Didn't test too much but seems to handle normal switching too.

Not completely ideal but better than what we have. Probably still want to clean things up a bit though. I'd try to avoid going too far into the cart-syncronizer (its due for reduxification.)

**Comment by joehdodd** [comment]
Yeah, I did notice that `SubscriptionLengthPicker` and `PayButton` are connected to different areas of state management and wondered if `cart-synchronizer` were to be ported to Redux if that would help clean things up and solve the issue along the way.

So are you saying that a selection shouldn't persist after reload, meaning that the "reset" value the pay button displays is actually correct? Which would mean that the issue above `SubscriptionLengthPicker` is the real fix.

**Comment by lsl** [comment]
FYI: Cart reduxification is happening here #24019

I would aim for just fixing the broken state tracking, maybe remove `state.checked` and rename `initialValue` to `checkedValue` before going any further, that is likely all you need.

> So are you saying that a selection shouldn't persist after reload

Not really, cart should still persist server-side through reloads as it currently does.

In the case where you pass in the pathSlug, it should be (and is) overwriting the selection with a [cart item replacement](https://github.com/Automattic/wp-calypso/blob/006d96c71bf6e41f070bed44ddb655f634b9c52b/client/my-sites/checkout/checkout/checkout.jsx#L638). This overwrite is being passed back down to `SubscriptionLengthPicker` and beyond, it's just not being used to update the internal state and thus the checked option.

> Which would mean that the issue above `SubscriptionLengthPicker` is the real fix.

The bug is definitely in `SubscriptionLengthPicker` [here](https://github.com/Automattic/wp-calypso/blob/006d96c71bf6e41f070bed44ddb655f634b9c52b/client/blocks/subscription-length-picker/index.jsx#L110) - new props coming down through initialValue should be dictating the selected cart option but the internal `state.checked` isn't being updated unless the `SubscriptionLengthOption` is [`onChanged`](https://github.com/Automattic/wp-calypso/blob/006d96c71bf6e41f070bed44ddb655f634b9c52b/client/blocks/subscription-length-picker/option.jsx#L163) with a click event.

It just so happens cart item replacements are [synchronous~](https://github.com/Automattic/wp-calypso/blob/006d96c71bf6e41f070bed44ddb655f634b9c52b/client/lib/cart/store/cart-synchronizer.js#L121) so you can get rid of the internal state altogether, i.e. this should mostly work:

```diff
-    state = {
-        checked: this.props.initialValue,
-    };

-    checked={ planSlug === this.state.checked }
+    checked={ planSlug === this.props.initialValue }
-    onCheck={ this.handleCheck }
+    onCheck={ this.props.onChange }

-    handleCheck = ( { value } ) => {
-        this.setState( {
-            checked: value,
-        } );
-        this.props.onChange( { value } );
-    };
```
