### ISSUE TITLE
Plans: payment methods component throwing React warnings

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30338]
While running Calypso in development mode, open `/plans` for a wp.com simple site and check console:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/87168/51598852-0f186580-1f07-11e9-8041-4978e9519d1c.png">

Seems like these would be coming from:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/87168/51598868-1770a080-1f07-11e9-8d35-bb70663f9e95.png">

**Comment by tyxla** [comment]
cc @yoavf @Automattic/i18n

**Comment by yoavf** [comment]
See #28837 - I'll take another stab at it

**Comment by yoavf** [comment]
The first warning can be fixed with #30347
The 2nd warning is due to a new method being tested - Sofort.
It will be fixed when #28736 lands

**Comment by tyxla** [comment]
Just tested, this appears to have been fixed. Thanks @yoavf!
