### ISSUE TITLE
Giphy block: Include editable caption?

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#30345]
When adding the Giphy block, including an editable caption was questioned several times for technical and user-oriented reasons:

- https://github.com/Automattic/wp-calypso/pull/29638#issuecomment-454818106
- https://github.com/Automattic/wp-calypso/pull/29638#discussion_r249732999
- https://github.com/Automattic/jetpack/pull/10989#discussion_r250152650

Do we keep it and figure out the details or drop it?

@scruffian @thomasguillot @jeffersonrabb @simison

**Comment by simison** [comment]
Is it possible to left/right align the block? If so, caption makes sense to me just like it does for core Image block.

That's more of a design decision I'd defer to @thomasguillot and @scruffian 

That said, if there are bigger bugs to fix (time-wise) than how long it would take to just remove the feature, I'd just remove a feature instead and add it to the backlog.

**Comment by jeffersonrabb** [comment]
The technical questions around caption are pretty minor. I'd advocate that this discussion should be entirely about whether a caption makes sense from a product perspective. The Atavist block this is based on does have a caption. However, the Atavist Map block also had a caption and we opted to remove it in the Gutenberg equivalent. The thinking was that a caption can always be added as a separate paragraph or heading block beneath the Giphy block. The decision to be made here is probably whether Giphy is more like Image (needs caption) or Map (does not).

**Comment by thomasguillot** [comment]
I think the Giphy block, even though it gives us an iframe and not an actual img, is closer to the Image block than the Map block. So to me, it makes sense to have the ability to add a caption.

Having said that, if there are some technical difficulties, let's remove the caption. Not having one is not a blocker.

**Comment by sirreal** [comment]
As @jeffersonrabb said, the technical difficulties are not blockers, just things that need to be handled. Unless @scruffian feels strongly opposed to captions here, let's go ahead and fix them up.
