### ISSUE TITLE
Giphy block: Add attribution

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#30346]
Add Giphy attribution according to [the docs](https://developers.giphy.com/docs/#api-keys):

> As per our section 5 A of our terms of service, **we require all apps that use the GIPHY API to conspicuously display "Powered By GIPHY" attribution marks where the API is utilized.** You can find approved [official logo marks here](http://www.google.com/url?q=http%3A%2F%2Fgiphymedia.s3.amazonaws.com%2Fgiphy-attribution-marks.zip&sa=D&sntz=1&usg=AFQjCNH2vioX4nvSrL6iR2kuB_WG-85VLA).

via https://github.com/Automattic/wp-calypso/pull/29638#pullrequestreview-194875739

Related convo: p1548156668251000-slack-gutenberg-design

**Comment by jeffersonrabb** [comment]
Attribution added in https://github.com/Automattic/wp-calypso/pull/30351
