### ISSUE TITLE
Giphy block: Use valid figure and figcaption

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#30348]
Currently, we use a `figure` followed by a `figcaption` sibling in the Giphy block if a caption is provided. That violates the element's spec:

> ## The `figcaption` element
> Contexts in which this element can be used:
>   - As the first or last child of a `figure` element.

[source](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figcaption-element)

https://github.com/Automattic/wp-calypso/blob/5b07a0028a69d4d388d775d9be53f54c0da732cf/client/gutenberg/extensions/giphy/edit.js#L143-L174

https://github.com/Automattic/jetpack/pull/10989#discussion_r250152650

Ensure that the `figcaption` is the first or last child of the `figure` or restructure the HTML accordingly.

This may be irrelevant depending on #30345. The caption may be removed entirely.

**Comment by jeffersonrabb** [comment]
This is resolved in https://github.com/Automattic/wp-calypso/commit/319ba38468a88b94c03ca35858bf466dedc80534 (and https://github.com/Automattic/jetpack/commit/5a9fc9ef5b1dc4f93afb527824bb89751f0498c5), because the caption is no longer in a FIGCAPTION element.
