### ISSUE TITLE
`FeatureExample` component has blue fade that doesn't match with page background

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30341]
On the _Activity log_ page, when viewing the log with simple site that doesn't have any recent events, I can see slight off-colour fade in the feature preview component:

<img width="1125" alt="screenshot 2019-01-23 at 12 14 03" src="https://user-images.githubusercontent.com/87168/51599590-a7fbb080-1f08-11e9-8a11-c0b8f4d7b7db.png">

Note how it has too blue hue compared to background and you can see slight border between the component and background:

<img width="110" alt="image" src="https://user-images.githubusercontent.com/87168/51599618-c06bcb00-1f08-11e9-8d1c-b5e22306e32b.png">

Component:
https://github.com/Automattic/wp-calypso/tree/cdcc997b9118bb998071fa095e2806993f5a2273/client/components/feature-example

Component is used here:
https://github.com/Automattic/wp-calypso/blob/cdcc997b9118bb998071fa095e2806993f5a2273/client/my-sites/activity/activity-log-example/index.jsx#L67-L78

FYI @Automattic/team-calypso

**Comment by drw158** [comment]
@flootr I found the gradient used here

https://github.com/Automattic/wp-calypso/blob/59bdfeeb97eda4266ad39410cb0a074d2c88dbc8/client/components/feature-example/style.scss#L14

Should be taken care of when we get rid of all the old uses of rgba?
