### ISSUE TITLE
Unable to remove the sharing completely

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#30350]
#### Steps to reproduce
1. Go to Sharing-> Sharing buttons
2. Try to uncheck everything and save
3. Notice that the same boxes get checked again.

#### What I expected
For them to remain unchecked.

#### What happened instead
They've gone back to being checkc.

#### Browser / OS version
Chrome

#### Screenshot / Video
https://monosnap.com/file/yEVmPK14F27Ev7DeH5wl43G7c6EXL7

I managed to uncheck them ultimately, but only by fiddling with other boxes and removing them one by one. To uncheck the Posts box, which came back all the time, I had to check the Product one, uncheck the Posts and uncheck the Product as well.

Tested on my Simple site as well.

User noticing this: #9753379-hc

**Comment by katinthehatsite** [comment]
There seems to be a similar issue opened already  #22811
