### ISSUE TITLE
/me/account: "Account deactivation" inline help article needs better copy

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30358]
On the https://wordpress.com/me/account page, there is a `Account deactivation` inline help article link/button at the .

1. The title should probably be renamed to `Close your account` instead of `Account deactivation`

2. The description currently reads `Finished with your WordPress.com account? Would you like to shut it down?` and this should be improved as well. Could something like `Learn how to permanently close your WordPress.com account and the consequences of doing so.` work here?

3. The link currently on the code side is http://en.support.wordpress.com/account-deactivation/ but it automatically redirects to https://en.support.wordpress.com/close-account/. We can update this link on the code side too.

<img width="1193" alt="screenshot 2019-01-23 at 19 29 23" src="https://user-images.githubusercontent.com/18581859/51611442-4279e500-1f45-11e9-8227-cc0f59ed10a4.png">
<img width="1188" alt="screenshot 2019-01-23 at 19 29 30" src="https://user-images.githubusercontent.com/18581859/51611443-4279e500-1f45-11e9-970e-2f5642c7ca1e.png">

@Automattic/editorial, would like to hear your thoughts, please. 

**Context**: Noticed while working on this issue https://github.com/Automattic/wp-calypso/issues/30311

**Comment by michelleweber** [comment]
I'd change the title to "Close your account." (And while I was in there, I'd change "Account settings" to "Edit your account settings" so all the items presented there have a parallel construction and start with a verb.)

For the description, I'd do "Learn how to permanently delete your WordPress.com account, and what it means for your website and data." (Something about the word "consequences" reads a little heavy to me in this context.)

**Comment by arunsathiya** [comment]
@michelleweber Thanks so much for checking! A quick followup. Would it be better to replace `permanently delete your` with `permanently close your` here? The wording used throughout https://en.support.wordpress.com/close-account/ is `close` and not `delete`

**Comment by michelleweber** [comment]
I don't think the language needs to be identical in the headline and description, and I purposely used "delete" in the description to highlight that this is a big step and to suggest that there will be data loss. 

(I'd rather see the doc/settings change to "delete" as well; we're purging all your data, so that's a lot more than just "closing.")

**Comment by arunsathiya** [comment]
Thank you, @michelleweber! Lost track of this after a super-long AFK, addressing these changes on https://github.com/Automattic/wp-calypso/pull/30806

I will also bring up your 'close vs delete' suggestion with the public-facing support docs team.
