### ISSUE TITLE
Can't upload valid third-party theme in Calypso

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#30373]
#### Steps to reproduce
1. Click on Themes on an AT site
2. Click Upload theme
3. Upload a particular theme (tested with Gardener theme from ThemeForest)

#### What I expected

If it's a valid theme that can be installed, it installs.

#### What happened instead

Received "Problem Uploading Theme" error. 

This occurs on AT V1 and AT V2 sites. It is a WordPress files only download and I was able to upload the exact same file via WP Admin.

#### Browser / OS version

Chrome Version 71.0.3578.98 (Official Build) (64-bit) on MacOS Mojave

#### Screenshot / Video

![screen capture on 2019-01-23 at 16-29-09](https://user-images.githubusercontent.com/7596032/51638578-b3f96980-1f2c-11e9-95eb-d8c70cda0021.gif)

#### Context / Source

First encountered during a Concierge session. I was able to reproduce the issue on my own test sites tacotestatomic1.blog and tacotestatomicv2.wpcomstaging.com. 

Ticket for the Concierge user is 1741898-zen. I've also uploaded the theme file to that ticket.

**Comment by arunsathiya** [comment]
I tested it on my Atomic site and I see the same behaviour on Calypso, but works fine on wp-admin.

**Comment by GeoJunkie** [comment]
Did some more testing and reproduced on Jetpack site. Found this was throwing a `PayloadTooLargeError`. 

The theme file is 25MB, which seems to be too large for Calypso currently. 

Nothing to fix, really. Closing.
