### ISSUE TITLE
We ship two copies of Lodash in the vendors~build chunk

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#30378]
We ship two copies of Lodash in the vendors~build chunk:

<img width="1192" alt="screenshot 2019-01-24 at 11 13 43" src="https://user-images.githubusercontent.com/664258/51672196-2e78c680-1fcb-11e9-8a80-bfa0322330e9.png">

They are coming from:
- `node_modules/lodash`
- `packages/tree-select/node_modules/lodash`

It's been happening since we added Lerna in #29154:

<img width="1256" alt="screenshot 2019-01-24 at 11 16 04" src="https://user-images.githubusercontent.com/664258/51672383-a2b36a00-1fcb-11e9-9fb1-efc58fc93fad.png">

Both versions are 4.7.11. I think it's caused by `packages/tree-select/package-lock.json` that mentions Lodash. Any idea how to fix this @blowery @sirreal? `lerna bootstrap` generates exactly the same lockfile when I delete it.

**Comment by sirreal** [comment]
I believe the lockfile is needed.

I _think_ we want hoist:
https://github.com/lerna/lerna/blob/master/doc/hoist.md

We should be able to add `--hoist` to any `lerna bootstrap` commands and I'd expect this to be improved. I know that @blowery was aware of this and I think we decided not to use the option for some reason. @blowery can you refresh us?

**Comment by jsnajdr** [comment]
> I believe the lockfile is needed.

That's true, `lerna bootstrap --ci` doesn't work without the lockfile.

> I think we want hoist:

Adding the `--hoist` flag to `lerna bootstrap` invocation in the `update-deps` script doesn't help. The `tree-select` lockfile is exactly the same and the private Lodash is still there, too.

**Comment by blowery** [comment]
Are you sure it's actually present twice in the built JS? I have a vague recollection of looking into this and discovering it was an issue with stats and lodash wasn't actually duped?

**Comment by blowery** [comment]
Just checked and, yes, we are shipping two copies. 👎

**Comment by blowery** [comment]
https://github.com/lerna/lerna/issues/872 sheds some light on why hoisting isn't deduping it. We'd have to sync up the exact version string between the root and the package. Just satisfying semver isn't enough.

Since we use a lockfile, switching to caret versions in the root _might_ be ok, but it would make lockfile maintenance ... much more risky.

**Comment by blowery** [comment]
The quick solution here might be to remove lodash usage from tree-select. We're still going to run into it with other packages though.

**Comment by blowery** [comment]
https://github.com/Automattic/wp-calypso/pull/30393 would be the quick solution.

**Comment by jsnajdr** [comment]
> The quick solution here might be to remove lodash usage from tree-select. We're still going to run into it with other packages though.

Yes, `tree-select` uses `isFunction`, `isObject` and `some`. All of them are easy to replace. But we'll run into the issue again when publishing a React component. Then we'll start duplicating React.

> lerna/lerna#872 sheds some light on why hoisting isn't deduping it. We'd have to sync up the exact version string between the root and the package. Just satisfying semver isn't enough.

I don't really understand why Lerna does it that way. `lerna boostrap` should behave like an extended `npm install` over multiple packages, right? And when NPM encounters two packages that depend on `react: ^16.0.0` and `react: 16.7.0`, of course it finds the version that satisfies both (16.7.0) and hoists it up (`dedupe` in npm-speak) to the root `node_modules`. So why can't Lerna do the same thing?

I'm pinging @evocateur in case he wants to join the conversation. To be clear, the issue is not that there are two lockfiles that specify different versions. The issue happens when the lockfiles are **generated** during `lerna bootstrap`.

**Comment by evocateur** [comment]
Nowhere that I can see (many ornate scripts later) are you ever calling `lerna bootstrap` with the `--hoist` option, so I'm not sure why you expected those dependencies to be hoisted.

You're also defining the root package as a leaf, despite it being private. You really shouldn't do that, as it completely defeats any hoisting Lerna is able to provide.

**Comment by jsnajdr** [comment]
Hi @evocateur!

> Nowhere that I can see (many ornate scripts later) are you ever calling lerna bootstrap with the --hoist option, so I'm not sure why you expected those dependencies to be hoisted.

Even if I remove the root package from the set of leafs and call `lerna boostrap --hoist`, the result doesn't change. A package that's specified as `lodash: 4.17.11` in root and as `lodash: ^4.17.0` in the leaf is not hoisted to the root.

The `getDependenciesToInstall` function looks compares the semver refs as literal strings and doesn't detect that the package should be hoisted. The `depsToInstall` map has two records for `lodash`:
```
Map {
  "lodash": Map {
    "4.17.11": Set { },
    "^4.17.0": Set { "@automattic/tree-select" },
  }
}
```

The relevant record in `rootSet` ends up being:
```
{
  name: 'lodash',
  dependents: [],
  dependency: 'lodash@4.17.11',
  isSatisfied: true
}
```
Note that the array of `dependents` is empty. We get a warning:
```
EHOIST_PKG_VERSION "@automattic/tree-select" package depends on lodash@^4.17.0, which differs from the hoisted lodash@4.17.11.
```
and the "Pruning hoisted dependencies" step doesn't prune the identical `lodash` package from `packages/tree-select/node_modules`, because the package is not in `dependents`.

I think that's different from what, e.g., `yarn install` with workspaces would do. It would consider the root and the packages (workspaces) as one big tree, resolve the `lodash` package to 4.17.11 that satisfies both root and packages' requirements, and then hoist the `lodash` package to root.

Does Lerna even have a chance to do that process 100% correctly? It seems to me that Yarn has a huge advantage of being a package manager and having complete control over the resolution process.

> You're also defining the root package as a leaf, despite it being private. You really shouldn't do that

If we don't do that, `lerna bootstrap` won't create symlinks from root's `node_modules/@automattic/tree-select` to the leaf `package/tree-select`. Because the dependencies are not `file:` refs, but semver specifiers. The fact that `package/tree-select` can satisfy the specifier doesn't help. `lerna bootstrap` only cross-links the directories that it manages thanks to the `packages` field.

Why we don't use `file:` refs? Well that created another set of problems that @blowery or @sirreal may remember. Something with CI?

**Comment by evocateur** [comment]
The root manifest should be coordinating shared devDependencies and scripts. Conflating that with an application is asking for trouble down the road, in my experience.

If you use `file:` refs in the root, you should use them everywhere. `npx lerna link convert` replaces `lerna bootstrap` with a single `npm install` in the root. Works great for Lerna itself and dozens of internal Zillow projects, including many "applications" (client- and server-side React + webpack etc).

There is likely a bug in bootstrap under just this sort of scenario. I'm not likely to fix it myself because I would personally rather delete the entire command and stop being a half-assed package manager.

**Comment by jsnajdr** [comment]
> If you use `file:` refs in the root, you should use them everywhere.

I think that has another consequence that we don't want: if we bump a minor version of package A, it causes a bump of package B that depends on it, because there is a change from `A: ^1.2.3` to `A: ^1.2.4` in the B's `package.json`. We want to avoid a publishing ripple-effect like this. And keep the published packages' dependencies as liberal as possible, because that helps the package manager to resolve them better.

> There is likely a bug in bootstrap under just this sort of scenario. I'm not likely to fix it myself because I would personally rather delete the entire command and stop being a half-assed package manager.

Oh yes, that sums up our experience very well, too. 😄 It's only a few days ago since I personally learned about Yarn workspaces. And they look like a perfect solution to all our `lerna bootstrap` woes.
