### ISSUE TITLE
Checklist: navigating with keyboard (tabbing) selects tasks in random order

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#30386]
#### Steps to reproduce
1. Go to a checklist to your site (`/checklist/example.blog`)
2. Mark some tasks as complete, some as incomplete
3. Navigate with Tab and Shift-Tab up and down the task list

#### What I expected
The focus is moved in a linear order, from one element to the previous or next one

#### What happened instead
The focus jumps randomly, because the tasks are reordered with `order: 0` and `order: 100` Flexbox CSS properties. The order in DOM is different from the order that's visible.

Cc @taggon who is the author of the code and also @timmyc who plans to use the checklist components in Woo. Nice opportunity to fix this little a11y bug.

**Comment by ramonjd** [comment]
For the WordPress.com checklist, we can sort the tasks by `isCompleted` descending in [getAll()](https://github.com/Automattic/wp-calypso/blob/412f7ad/client/my-sites/checklist/wpcom-checklist/wpcom-task-list.js#L76)

```
	getAll() {
		return orderBy( this.tasks, [ 'isCompleted' ], [ 'desc' ] );
	}
```

Result: 

![feb-05-2019 16-53-29](https://user-images.githubusercontent.com/6458278/52255429-a00b2a00-2966-11e9-895b-1db402ef2f7b.gif)

There are a couple checklists however, whose tasks aren't sortable as each task element is rendered:
* [my-sites/plans/current-plan/jetpack-checklist](https://github.com/Automattic/wp-calypso/blob/412f7ad/client/my-sites/plans/current-plan/jetpack-checklist/index.js)
* [extensions/woocommerce/app/dashboard/setup/tasks](https://github.com/Automattic/wp-calypso/blob/412f7ad/client/extensions/woocommerce/app/dashboard/setup/tasks.js
)

We could turn these into collections and iterate over them via `orderBy` too (?)
