### ISSUE TITLE
Security:  Unfriendly / Incorrect failure message for username containing backslash on login

### ISSUE THREAD

**Issue by draganescu** [Automattic/wp-calypso#30381]
#### Steps to reproduce
1. https://wordpress.com/log-in?redirect_to=https%3A%2F%2Fwordpress.com%2F
2. Enter a random username (doesn't have to exist) and append a backslash at the end
3. Press Enter on the keyboard or click Continue

#### What I expected
A) Typing a backslash character immediately generates a notice that usernames cannot contain the backslash character, the continue button is disabled, form does not submit on enter key.
or
B) An error that explains the username does not exist and ask the user to recheck appears in red below the username input,  the continue button is disabled, form does not submit on enter key.

#### What happened instead
For `username1000\`, a red error message that says: "404 status code for "GET /users/username1000\/auth-options" shows below the username input.

It doesn't matter where the backslash is: `username1000\` or `username\1000` have the same problem. It doesn't matter if the username without the backslash exists or not.

#### Browser / OS version
Safari 12.0.3, FF 64.0.2, Chrome 71.0.3578.98 / OSX Mojave 10.14.3

#### Screenshot / Video
<img width="423" alt="backslash-username-bad-error" src="https://user-images.githubusercontent.com/107534/51678635-8ae8df80-1fe5-11e9-8adf-0231a116e4fb.png">

#### Context / Source
#dogfooding
The problem is that the backslash is very close to the enter key on some keyboards so it might be a frequent typo 😄

**Comment by cacheflow** [comment]
I have a fix for this. I noticed in a few places you all were using formState for capturing form data and running validations, but I wasn't sure if it was called for here, so I wrote a component level validation method in LoginForm: 

https://github.com/Automattic/wp-calypso/pull/30951
