### ISSUE TITLE
Giphy Block: Additonal CSS class does not get applied on the frontend

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#30385]
#### Steps to reproduce
1. Spin up a JN with this Jetpack branch: https://github.com/Automattic/jetpack/pull/10989
2. Enable Beta blocks
3. Insert a Giphy block into your post

For some reason the additional classes you can add thanks to the option in the block inspector don't get added to the wrapper on the frontend:

![https://user-images.githubusercontent.com/426388/51679780-211a0700-1fe0-11e9-9fc8-125f56b8a112.png](https://user-images.githubusercontent.com/426388/51679780-211a0700-1fe0-11e9-9fc8-125f56b8a112.png)

**Comment by sirreal** [comment]
Closing, I've confirmed that https://github.com/Automattic/jetpack/commit/ef7603bca617f470a3dcaf271fbdef0c23d61b55 fixes it
