### ISSUE TITLE
Editor: Atomic sites don't always display the sidebar opt-in prompt.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#30404]
Noted by @samiff , Atomic sites don't always display the sidebar opt-in prompt in the Calypso editor.

A user with an Atomic site can find themselves in the Calypso editor, if the block editor is not set as their selected editor. This means they _should_ be able to opt in, and have the prompt displayed.

**Comment by kwight** [comment]
@samiff Can you replicate this at all any more (I can't)? I know we've had a lot of changes since your report, so it may have sorted itself out in all the activity.

**Comment by samiff** [comment]
> Can you replicate this at all any more

I just gave it a go, trying a decent combination of editor preferences and the Classic Editor plugin and could not reproduce it.

**Comment by kwight** [comment]
Closing; anyone can feel free to reopen if this pops up again.
