### ISSUE TITLE
Editor: Investigate if and how the Calypso editor should be shown for Atomic sites.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#30405]
Investigate if and how the Calypso editor should be shown for Atomic sites.

Currently, an Atomic user can be shown the Calypso editor [if the Classic plugin is active](https://github.com/Automattic/wp-calypso/blob/18e212b04ed799156b733b567930da4a91f6465b/client/state/selectors/is-calypsoify-gutenberg-enabled.js#L23) on the Atomic site, regardless of that plugin's actual settings. We may need to better integrate the plugin's settings into Calypso's logic, or give the user better control somehow over which editor they use of their three options: Calypso, `wp-admin` Classic, or the new Block Editor.

**Comment by gwwar** [comment]
Closing this out, since @kwight is already writing a post, we can discuss options there.
