### ISSUE TITLE
/start/plans: Business plans button missing border

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30412]
While working through https://wordpress.com/start, the third step of the process shows the WordPress.com plans on https://wordpress.com/start/plans 

Currently the `Business sites and online stores` plans button is missing a border. 

![screenshot 2019-01-25 at 19 12 32](https://user-images.githubusercontent.com/18581859/51749463-708e2f00-20d5-11e9-806a-47cf3697e3b6.png)

Would it be better to have one like shown below?

![screenshot 2019-01-25 at 19 12 20](https://user-images.githubusercontent.com/18581859/51749460-6e2bd500-20d5-11e9-87de-6d2475dd3c97.png)

Or, is the current format by design?

**Comment by shaunandrews** [comment]
It was intentional, but I don’t have a strong opinion either way.

It’s worth noting that these buttons (which are actually a hacked together segmented-control), are going away at some point soon.

**Comment by arunsathiya** [comment]
>It’s worth noting that these buttons (which are actually a hacked together segmented-control), are going away at some point soon.

That's interesting! I shall go ahead and close this issue in this case. Thanks for taking a look!
