### ISSUE TITLE
Followed sites: Manage button overlap on medium-sized windows

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#30418]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Make the window a bit larger than mobile-width (between 661 and 960px wide).
3. See the Manage button overlapping the "Followed Sites" stream.

Using Chrome on macOS; also occurs in the app (see closed issue [here](https://github.com/Automattic/wp-desktop/issues/555)).

#### Screenshot / Video
![Image](http://cld.wthms.co/kkTAkP+)

**Comment by lancewillett** [comment]
Hi there, this is intentional — the fade technique avoids a total clash, but this is a compromise for the in-between state of a small screen.

Thanks for the report and screenshot.
