### ISSUE TITLE
Removed followed sites remain as followed in the app until refresh

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#30419]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Remove a followed site
3. Return to the Followed Sites stream
4. Continue to see the unfollowed site's posts
5. Refresh the page, and the unfollowed feed no longer shows up.

Running Chrome on macOS 10.14.3; also occurs in Desktop app.

#### Screenshot / Video
![Image](
http://cld.wthms.co/3Zwh8H+)

**Comment by lancewillett** [comment]
Thanks for the report. Reader is not actively maintained, so we'll keep this open until we get back to it.
