### ISSUE TITLE
Signup: Error message is difficult to see

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#30422]
#### Steps to reproduce
1. Go to https://wordpress.com/start/import/from-url
2. Type something random into the input that's not a url (won't pass validation)
3. Click "Continue" button

The error state is difficult to see because of the low color contrast ratio.

#### Browser / OS version

Any

#### Screenshot / Video

<img width="1277" alt="screen shot 2019-01-25 at 14 53 21" src="https://user-images.githubusercontent.com/1699996/51774264-4c235a00-20b7-11e9-806c-a3e75ba83221.png">

#### Context / Source

Checking on the import in signup flow we launched last year.

**Comment by creativecoder** [comment]
Pinging @shaunandrews, as I understand you've been working on the color updates in signup.

**Comment by torres126** [comment]
What should it be? Those which pass the colour contrast look more peach than red. @drw158, any ideas?

**Comment by drw158** [comment]
That's a tough one. I guess I would add a white background to the error.
