### ISSUE TITLE
Connecting to multiple Facebook pages

### ISSUE THREAD

**Issue by nickpagz** [Automattic/wp-calypso#30423]
I'm not sure this is particularly a bug or issue, more like a feature request and to find out if what our users want is possible.

I had a user in chat today expecting to be able to add multiple FB pages to several of the sites they manage. As an example, they want to connect:
wpcom site A --> FB page A, and...
wpcom site B --> FB page B.

They said they couldn't do this, and would only allow them to connect to one FB page (the same FB page) on all their wpcom sites.

#### Steps to reproduce
I have multiple test sites and several FB pages myself, so I was able to reproduce the behavior. Again, my goal here is to connect wpcom site A to FB page A, and wpcom site B to FB page B.

1. I connect my wpcom site A to my FB Account, I get a list of FB pages to chose from and connect to.
2. I choose FB page A since this is my goal for wpcom site A.
3. I then go to my wpcom site B and try to connect to my FB page B, but I don’t get the option to connect to any other FB page other than FB page A.

#### What I expected
As an owner of multiple sites (with corresponding social/FB accounts) under a single WordPress.com account, I would expect to be able to connect my separate sites to their corresponding social accounts/FB Pages. Since the wpcom sites are effectively separate, and unattached, I can only imagine the same for the FB pages under a single FB account.

#### What happened instead
Even with multiple individual and not remotely connected wpcom sites, I was only able to connect to the same FB page for all the sites after the initial connection was made.

#### Context / Source
It's clear in our user facing [support docs on Publicize](https://en.support.wordpress.com/publicize/):

> Note: You can connect only one Facebook page per WordPress.com account per site.

The same goes for Jetpack, assuming this means the same thing.

[https://jetpack.com/support/publicize/facebook/#multiple-pages](https://jetpack.com/support/publicize/facebook/#multiple-pages)

It's unreasonable to think a user would have multiple wpcom accounts as we limit one account per email address, and the same applies to Facebook accounts.

Is this a limitation imposed by FB? Or is this an internal/self-imposed Jetpack/wpcom limitation? And, can it be changed so users can connect different FB pages (under the same FB account) to different wpcom sites?

#manual-testing #user-report

**Comment by torres126** [comment]
Automattic/jetpack#10666

**Comment by nickpagz** [comment]
I think [#10666](https://github.com/Automattic/jetpack/issues/10666) is more about adding multiple FB accounts to one wpcom account, and that makes sense. This issue is different though as a single  FB account can have multiple pages, as does a wpcom account has (can have) multiple sites.
