### ISSUE TITLE
Purchases/Domains: Need a user-facing way to remove bundled domain mapping

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#30421]
Currently, if a user has a mapped domain, it can only removed via the Manage Purchases page, and then only if they don't have a paid plan on their site.

The Manage Purchases allows removal of a mapped domain if the site doesn't have a paid plan:
![screen shot on 2019-01-25 at 15-52-13](https://user-images.githubusercontent.com/7596032/51772575-4ed37e80-20ba-11e9-908c-5a133b0a62da.png)

However, if the user has a paid plan, there's no way to remove the mapping:

![screen shot on 2019-01-25 at 16-02-19](https://user-images.githubusercontent.com/7596032/51772757-ce614d80-20ba-11e9-8bf3-bf0baafad841.png)

Either way, there isn't a way to remove the mapping from the Domains tab, which is normally the first place people look:

![screen shot on 2019-01-25 at 15-48-28](https://user-images.githubusercontent.com/7596032/51772669-98bc6480-20ba-11e9-9a7d-d5c172b35d0f.png)

I suggest that we, at a minimum, allow removal of mapping from the Purchases tab for anyone with a domain mapping subscription.

A better solution, though, would be to move/add that option to the Domains tab. With domain mapping now being free with a paid plan, it's counterintuitive to remove something that you never purchased from the Manage Purchases part of your account, rather than the Domains section of the website you mapped the domain to.

**Comment by edwinho89** [comment]
Similar reported case on #9122408-hc , and a few other cases I had where users need to contact us to remove domain mapping on their paid plans.

**Comment by DavidRothstein** [comment]
See also: p2MSmN-7g5-p2

**Comment by davipontesblog** [comment]
Moved to the Domain Management board for consideration.

**Comment by DavidRothstein** [comment]
This was fixed on the purchases page a while ago (via https://github.com/Automattic/wp-calypso/pull/38264).

Not sure about being able to remove it from the Domains page though.

**Comment by davipontesblog** [comment]
I think we should give the user at the very least a link to remove a domain (or cancel, if registered) on this screen in My Site > Manage > Domains. It's likely the first place one will go to to manage anything about domains, including removing them - so maybe adding a link here to the purchases page that says "Remove"? What are your thoughts @fditrapani?

**Comment by fditrapani** [comment]
Thanks for the ping @davipontesblog! We have this work on our backlog for updating the domain settings screen. It should be there in the coming weeks. I'll just add a note to project board so we can update this issue when it's done.

**Comment by eltongo** [comment]
Closing this issue since it has already been fixed, and users should also be able to remove it from the Domains page.
