### ISSUE TITLE
Signup: "Change Settings Later" Difficult to See 

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#30429]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/subdomain/design-type-with-store-nut (which would be seen by any user who registers a .blog subdomain) 
2. Scroll below the options 

#### What I expected

The notice to be easier to read, ideally white, and probably even aligned. 

#### What happened instead

See the screenshot. It looks like the styles here aren't taking effect. 

https://github.com/Automattic/wp-calypso/blob/a2549e0840c7f49f3e5b96f2828c62054bffc711/client/signup/steps/design-type-with-store/style.scss#L43-L49

#### Screenshot / Video

![screenshot_20190126-121044](https://user-images.githubusercontent.com/43215253/51787113-80edea80-2165-11e9-956e-0d5f37b3e7c2.jpg)

(cc @shaunandrews)

**Comment by shaunandrews** [comment]
I think this flow is unused/going away, right @michaeldcain ?

**Comment by torres126** [comment]
In terms of unused, I don't think so. Anyone who tries registering a blog subdomain would experience it (from the ones I've tested).

**Comment by torres126** [comment]
Noting that this especially bad with the newer schemes; it's completely invisible in Nightfall.

**Comment by torres126** [comment]
Fixed by #32505
