### ISSUE TITLE
Import: File type error could be more friendly

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#3043]
<img width="699" alt="screen shot 2016-02-03 at 9 36 48 am" src="https://cloud.githubusercontent.com/assets/1464705/12791005/e548a6d4-ca59-11e5-83db-7054bcdc0b98.png">

I think this error could be more user friendly. It makes the assumption that a user knows what a WXR file is, and has any idea what the version number is. I think it should be more generic.

> There was a problem with your WordPress Import File, it doesn't seem to be in a valid format. Please check that you have uploaded the correct file, or contact support for more help.

Let's make sure the contact support link starts a live chat if available, or sends them to /help. Right now it does nothing.

**Comment by roccotripaldi** [comment]
error messages handled in r131008, and support link added in #3257
