### ISSUE TITLE
Tiled Gallery Block: No Margin Beneath Block

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#30432]
#### Steps to reproduce
1. Starting in the editor, add a Tiled Gallery Block
2. Add a paragraph block directly underneath that, as if you were to continue writing
3. Publish

#### What I expected

A bottom margin to be consistent with other blocks, including the Gallery Block. 

#### What happened instead

In the editor:

![gsddfsgdgfsgfds](https://user-images.githubusercontent.com/43215253/51799953-22d20d80-2220-11e9-95b5-14d411636ff6.png)

Front end, taken with different themes, compare the margin between the Gallery and the Tiled Gallery Blocks. The Tiled Gallery one looks off. 

![fadsfadsasdfsdaf](https://user-images.githubusercontent.com/43215253/51799965-63ca2200-2220-11e9-8be9-edcbad96748b.png)

![fdasasfdadsffsda](https://user-images.githubusercontent.com/43215253/51799966-662c7c00-2220-11e9-87ac-05759a0974c2.png)

Found when using the block myself.

**Comment by torres126** [comment]
Question: Is this something which themes individually should deal with? If so, it's probably worth moving this to the Automattic/themes repo, because those were the themes I tested with this with. But since this has happened with multiple themes, I'm not sure if this should be addressed here or not.

(cc @simison & @sirreal)

**Comment by simison** [comment]
Which themes did you test with? :-)

**Comment by torres126** [comment]
Dara and Harmonic in the screenshots above, but also confirmed the issue with Sela and Photos.

**Comment by simison** [comment]
I'd expect this to work just like core gallery and that themes would not need to worry about a block shipped in plugin.
