### ISSUE TITLE
Gutenberg: gallery post format doesn't work on the blog archive (not blog post itself)

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#30439]
#### Steps to reproduce
1. Activate a theme that supports Gallery post format like [Baskerville 2](https://wordpress.com/theme/baskerville-2)
2. Add a new post
3. Add a gallery block
4. Set gallery as post format

#### What I expected
I expected the post would have the special layout defined by the theme for a post with the gallery format. 

#### What happened instead
Instead it only shows the title and meta.

#### Screenshot / Video

I tested it with different themes. Screenshots below:

##### Baskerville 2 theme
![gallery-format-bug-baskerville](https://user-images.githubusercontent.com/3521683/51806744-cd6c1f80-2264-11e9-8ccd-8500ad73c3e7.jpeg)

##### Scratchpad theme
![gallery-format-bug-scratchpad](https://user-images.githubusercontent.com/3521683/51806765-32277a00-2265-11e9-9d66-8cd06f0c9db4.jpeg)

##### Eda theme
![gallery-format-bug-eda](https://user-images.githubusercontent.com/3521683/51806796-816daa80-2265-11e9-8d00-2f6ca9452d22.jpeg)

#user-report 

Ticket: #1752646-zd

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Can reproduce but feels expected. More on that below.

📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO

I tested with the theme reported: Baskerville 2 on a simple site. Cannot reproduce.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/18581859/173811988-a1d1680a-86b0-4769-b6a4-71991401af1f.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/18581859/173812049-7ea7c3de-3f87-48a2-baa4-df13ea13dfa7.png">

I can reproduce the issue on Baskerville, and several third-party themes on a WordPress.org site. 

<img width="942" alt="image" src="https://user-images.githubusercontent.com/18581859/173812114-336c42dd-f664-4139-a687-2cd72d33a3eb.png">

<img width="921" alt="image" src="https://user-images.githubusercontent.com/18581859/173812162-6d062bb6-3f05-42cc-af3b-bc478c23f231.png">


📌 ACTIONS
- This suggests the lack of the featured image in the blog archive is a theme-level issue and each theme developer must build compatiblity with Gutenberg, like Baskerville 2 did.
- Closing as this is not a Calypso or Gutenberg on WordPress.com implementation's issue.
