### ISSUE TITLE
Ribbon: shadow using unexpected color 

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#30478]
#### Steps to reproduce
1. Starting at URL:https://wpcalypso.wordpress.com/devdocs/design/ribbon
2. Notice that the shadow of the ribbon is blue

It should be using the accent color for the shadow, probably --color-accent-dark.

#### Screenshot / Video

![screen shot 2019-01-29 at 12 06 59 pm](https://user-images.githubusercontent.com/618551/51934068-61a2c780-23c8-11e9-9149-ebf409b8f140.png)

**Comment by drw158** [comment]
While we are at it, we can update the green ribbon and use a consistent naming for the shadow. (--color-success-dark) ?

**Comment by blowery** [comment]
i'll take this one
