### ISSUE TITLE
Plans: Personal plan doesn't show credit/discount for domain registration

### ISSUE THREAD

**Issue by jhnstn** [Automattic/wp-calypso#30475]
Personal plan doesn't show credit/discount for domain registration customers wanting to upgrade

#### Steps to reproduce
Site with domain-only (no plan) and the credit does not show for the Personal plan with the higher pricing.

#### Screenshot

<img width="1321" alt="ndn4lomb8v-3000x3000_ 1" src="https://user-images.githubusercontent.com/744755/51930342-2e077380-23af-11e9-82b7-4cac07d59303.png">

**Comment by jhnstn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When non-.blog domain is purchased, do not show discount on Blogger upgrade on /plans & disable CTA to upgrade](https://trello.com/c/Ci4sxMQo/180-when-non-blog-domain-is-purchased-do-not-show-discount-on-blogger-upgrade-on-plans-disable-cta-to-upgrade)

**Comment by jhnstn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Personal plan doesn't show credit/discount for domain registration customers wanting to upgrade](https://trello.com/c/jPCVLahr/181-personal-plan-doesnt-show-credit-discount-for-domain-registration-customers-wanting-to-upgrade)

**Comment by matthusby** [comment]
This has been fixed in D23709-code
