### ISSUE TITLE
Activity log: Admin ui activity list - wrapping long filename

### ISSUE THREAD

**Issue by karlcow** [Automattic/wp-calypso#30482]
This is a spin off of https://github.com/webcompat/web-bugs/issues/24990

**URL**: https://wordpress.com/activity-log/webcompatmozilla.wordpress.com

**Browser / Version**: Firefox Nightly 66.0a1 (2019-01-27)
**Operating System**: Google Pixel (Android 9) - 1080 x 1920 pixels (~441 ppi pixel density)
**Tested Another Browser**: Yes

**Problem type**: Design is broken
**Description**: Uploaded media files with long names exceed the allocated space
**Steps to Reproduce**:
**Prerequisites:**
    1. Wordpress account created and signed in (using username).
    2. Media files with long names added to the site.
**Steps to Reproduce:**
    1. Navigate to https://wordpress.com/activity-log/webcompatmozilla.wordpress.com
    2. Scroll down the page and observe activity.

**Expected Behavior:**
Uploaded media with long names fit in the allocated space.

**Actual Behavior:**
Uploaded media with long names exceed the allocated space.

**Note**
    1. Not reproducible on Chrome 71.0.3578.99.
    2. Screenshot attached.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv 

#### Browser / OS version
Firefox Nightly 66 on Android

#### Screenshot / Video
sv;
[![Screenshot Description](https://webcompat.com/uploads/2019/1/d1c73d59-63bd-4d73-9e83-7e90a3d5239c-thumb.jpeg)](https://webcompat.com/uploads/2019/1/d1c73d59-63bd-4d73-9e83-7e90a3d5239c.jpeg)

#### Context / Source
https://github.com/Automattic/wp-calypso/blob/a71dec9acd56c5bdc95d9de357b9602702160c10/client/my-sites/activity/activity-log-item/style.scss#L299-L307

#user-report

This can be fixed with 

```css
.activity-log-item__description {
	font-size: 14px;
	word-break: break-word;
	overflow-wrap: anywhere;
}
```

**Comment by andyaffleck** [comment]
Tried to reproduce in Firefox 67.0 (Mac) in responsive mode and Safari 12.1.1 (responsive design mode) and could not replicate. 

<img width="319" alt="image" src="https://user-images.githubusercontent.com/7773109/59310249-cb36ba80-8c73-11e9-91a5-5eee2335d396.png">
