### ISSUE TITLE
Jetpack JITMs: make placement more specific 

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#30491]
Currently we are displaying JITMs in Calypso at section level ( see ` get_jitm( )` function in core). 
That in turn means we cannot enable them for only specific routes in a section, e.g. `/settings/security` - they would be shown in every route under that section.

In order to enhance targeting capabilities of JITMs, we should extend the code to e.g. handle extra parameters or process the routes differently, allowing more granularity and customization on a per route basis.

/cc @jessefriedman, @tyxla

**Comment by jessefriedman** [comment]
Great idea. We should also include a new hook into the toolbar for places that arent convenient for a JITM, or to expand it to the front-end.

**Comment by ChaosExAnima** [comment]
Reopening as this is still an issue.
