### ISSUE TITLE
Gutenberg: Gallery images disappear if user builds in Classic, switches to Block editor

### ISSUE THREAD

**Issue by kathleenjross** [Automattic/wp-calypso#30518]
A user arrived in chat, noting that in their live post, all the images in a gallery appear. However, when they head to edit the post in Gutenberg, it shows up as empty Gallery blocks. If you head to WP-Admin though, you can still see the images intact in the gallery. I followed up on ticket `1761951-zen`, and shortly after, I saw another ticket with a similar issue, `1750355-zen`. 

#### Steps to reproduce

1) I made a new site, https://gallerygutenbergtest.home.blog, with a Premium plan.

2) I set the editor to Classic in User RC.

3) I published a post: https://gallerygutenbergtest.home.blog/2019/01/31/im-a-test-post/. 

4) The gallery images look good both live and within Compose. 

5) I opted to try the Block editor via prompt in the post.

6) Immediately, within the post, I see an error for all the Gallery blocks that **“This block has encountered an error and cannot be previewed”** and when I click on the block, I’m able to copy this error:

TypeError: Cannot read property 'split' of undefined
    at t.value (https://wordpress.com/calypso/gutenberg-init.a200d30e3395d6e9efd2.min.js:77:231473)
    at t.value (https://wordpress.com/calypso/gutenberg-init.a200d30e3395d6e9efd2.min.js:77:232167)
    at Array.map (<anonymous>)
    at t.value (https://wordpress.com/calypso/gutenberg-init.a200d30e3395d6e9efd2.min.js:77:232356)
    at cb (https://wordpress.com/calypso/vendors~build.894edf730ab0a872d658.min.js:79:59850)
    at zb (https://wordpress.com/calypso/vendors~build.894edf730ab0a872d658.min.js:79:59645)
    at ub (https://wordpress.com/calypso/vendors~build.894edf730ab0a872d658.min.js:79:63322)
    at Yb (https://wordpress.com/calypso/vendors~build.894edf730ab0a872d658.min.js:79:78434)
    at Gb (https://wordpress.com/calypso/vendors~build.894edf730ab0a872d658.min.js:79:78811)
    at NM (https://wordpress.com/calypso/vendors~build.894edf730ab0a872d658.min.js:79:85234)

7) If I attempt a recovery, nothing really happens.

8) I updated the post, and the gallery is gone in the public version of the post: https://wordpress.com/block-editor/post/gallerygutenbergtest.home.blog/9. And now in Compose, I’m seeing a Tiled Gallery block that is empty.

#### What I expected

I would expect for the Gallery block to still work when moving from Classic to Gutenberg, without rebuilding the block with the images.

#### Browser / OS version

Chrome, latest version.

#### Context / Source

#user-report

Two users have seen this and it has been a #painpoint for both.

**Comment by jjchrisdiehl** [comment]
Another instance 10231453-hc

Gallery block doesnt show images and prompts to 'upload', but switching to the html view of the block shows the gallery image links.

**Comment by AtrumGeost** [comment]
Another issue here 1842633-zen

The images appear on the front-end but in the editor, there's only the option to add images:

![screen shot on 2019-03-02 at 09 30 01](https://user-images.githubusercontent.com/3696121/53683343-c609bd00-3ccd-11e9-97d8-976ef2ea92ce.png)

But if you take a look at the code, the image's IDs are there:

![screen shot on 2019-03-02 at 09 30 32](https://user-images.githubusercontent.com/3696121/53683352-e174c800-3ccd-11e9-8d4d-8e7fbd2d6538.png)

**Comment by synora** [comment]
Something similar is going on in 2187500-zen. A Tiled Gallery Block was added into a portfolio project. While the Tiled Gallery appears correct within the Block Editor for the project, the images appear as a "list" of images once published. 

Switching back to the Classic Editor (while the Tiled Gallery remains in the project) will just list the images one after another. I am able to replicate this by applying the Orvis theme (same as user's) to my test site. 

I did find a workaround: 

1. Create a new portfolio project
2. Switch to the Classic Editor
3. Create the Tiled Gallery within the Classic Editor
4. Publish the project
5. View publish portfolio project. The Tiled Gallery appears on the project as expected. 

I'll be reporting the workaround to the user.

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!
