### ISSUE TITLE
Store on WP.com: Fix design issues with the new color schemes

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#30525]
It looks like there are a few visual issues throughout Store on WP.com related to the new color schemes:

<img width="919" alt="screen shot 2019-01-31 at 2 19 47 pm" src="https://user-images.githubusercontent.com/689165/52084884-11b33480-2571-11e9-8857-a0eaa547b817.png">

<img width="593" alt="screen shot 2019-01-31 at 2 20 00 pm" src="https://user-images.githubusercontent.com/689165/52084887-14158e80-2571-11e9-9868-ce57e260408e.png">

**Comment by drw158** [comment]
Thanks for the report. Can you describe what the blue background is used for and why? If you happen to have a screenshot of what it looked like before, that would be great too.

**Comment by flootr** [comment]
We still need to replace a few old sass variables with proper replacements. [They're already using new blues](https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/_colors.scss#L9-L12) but they're equivalents are probably not correct:

```
❯ rg '\$blue-' client/extensions/woocommerce --type sass
client/extensions/woocommerce/app/orders/style.scss
16:			background: lighten( $blue-light, 25% );
19:				background: lighten( $blue-light, 24% );

client/extensions/woocommerce/app/products/product-form.scss
607:		color: $blue-light;

client/extensions/woocommerce/app/reviews/style.scss
390:			box-shadow: 0 0 0 2px $blue-light;

client/extensions/woocommerce/app/order/order-fulfillment/style.scss
5:	background: lighten( $blue-light, 25% );

client/extensions/woocommerce/app/settings/email/mailchimp/style.scss
285:	background-image: linear-gradient( -45deg, $blue-medium 28%, darken( $blue-medium, 5% ) 28%, darken( $blue-medium, 5% ) 72%, $blue-medium 72% );
286:	border-color: darken( $blue-medium, 8% );

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/style.scss
95:		background-color: lighten( $blue-light, 15 );
```

**Comment by justinshreve** [comment]
> Can you describe what the blue background is used for and why?

We were using it as a highlight for orders that needed fulfillment/action.
