### ISSUE TITLE
Related Posts Block: improve messaging

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#30527]
In #30224 - we are introducing some text to show when no related posts are found:

![screen shot 2019-01-31 at 4 06 41 pm](https://user-images.githubusercontent.com/2694219/52085512-b3875100-2572-11e9-98f6-a15a3f494fba.png)

First of all: the circled block above should look more like an error, and less like the rest of the related posts.

We should improve the messaging here. 
For example, if the context is that there are not enough related posts to show, we should say:
"We only found %n related posts, please select %n or fewer"

And if the context is there are no related posts found, what should we say?
"We did not find any related posts. Try again later"

**Comment by simison** [comment]
@aldavigdis @lezama suppose this can be now closed?

**Comment by lezama** [comment]
yes https://github.com/Automattic/wp-calypso/pull/31126
