### ISSUE TITLE
Post Scheduler Geolocates Publish Time Without Warning (Regardless of Site Time Zone Settings)

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#30533]
#### Steps to reproduce
1. Starting at URL: My Sites in Calypso (any site will work)
2. Go to Settings 
3. Adjust your site's time zone to be a different time zone than the one you're currently in.
4. Create a blog post.
5. Schedule that post to be published in your site's time zone.
6. Calypso geolocates your time in a scheduled post, which means if you're traveling (somewhere outside of your typical/site timezone), you're going to see your time zone when scheduling a post vs your site's time zone. 
7. Requires discovering that your post scheduler is geolocating (there's no warning), then doing the time conversion to schedule a post when you'd actually like it to be scheduled.

#### What I expected
When scheduling a post, for the scheduler to either show my site's time zone, as opposed to my geolocated time zone, or to have a notification/conversion assistance to let the user know that the post schedule time is geolocated, and they'll need to adjust accordingly if they want the post to be scheduled at the site's time zone.

#### What happened instead
The Calypso post scheduler geolocates your time zone, which causes confusion when you're trying to schedule a post to go live based on your site's time zone. You then have to do a conversion to publish the post at your local time zone, converted to your site's time zone.

#### Browser / OS version
All.

#### Context / Source
Optional: share your unique context to help us understand your perspective. You can add context tags such as:  #anxiety  #stresscase #painpoint.

We'd also love to know how you found the bug: #user-report

A user is currently in Singapore on a trip. Their typical home/site is based in London, and they needed to schedule a post to be published at 11am the next day in London's time zone.

Since they're in Singapore, Calypso's post scheduler was geolocating (without telling them) their time zone to Singapore time. So they were scheduling posts in Singapore time (+8) instead of their site's time zone (0), and couldn't find out why their posts were not going to be published at the correct time.

So they had to figure out they were being geolocated, do a manual time conversion, and then schedule posts in Singapore time adjusted for the time they'd like them to be published in London time, even though their site settings are set to London time.

There should be a notification/time conversion available in the post scheduler to let users know specifically what time a post is going to be published vs their site's time zone. It's currently geolocating without telling the user. 

Or, the post scheduler should remain consistent with the time zone set in the site's settings.

**Comment by pauljacobson** [comment]
A user reported a similar issue today -

* 10669647-hc
* 1827935-zen

The user is based in UTC+2 (with DST), and set their site timezone to EST (New York, specifically). They published a post, and then scheduled social media updates through Publicize for what should have been 12:00pm (noon).

Instead, the social media updates were scheduled for roughly 3am, being the user's local time based on their actual location.

**Comment by juliasydnor** [comment]
Possibly related: https://github.com/Automattic/wp-calypso/issues/32173

**Comment by jsnajdr** [comment]
This is the same bug as #32173, fixed in #32178.

The time was displayed in the time zone that was set in the computer's OS. That's the only "geolocation" that's happening. The correct behavior is to show the scheduled time in the site's timezone.
