### ISSUE TITLE
Editor: Copy UI is inconsistent across post types.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#30549]
While users can copy both posts and pages, the functionality is called "Duplicate" for posts, and "Copy" for pages.

<img width="792" alt="screen shot 2019-02-01 at 10 52 45 am" src="https://user-images.githubusercontent.com/349751/52143133-8dfc5500-260f-11e9-96fb-c86c4a58c239.png">

Also, with the addition of Jetpack's Copy Post for adding this functionality to Calypsoified Atomic and Jetpack sites, the current `?copy` parameter should be updated to the prefixed `?jetpack-copy`.

**Comment by gwwar** [comment]
I noticed that too earlier, maybe stick with "Copy".
