### ISSUE TITLE
Medium Imports: Instructions on correct file uploads

### ISSUE THREAD

**Issue by dezzie** [Automattic/wp-calypso#30558]
#### Steps to reproduce
1. Starting at URL:
2. https://wordpress.com/settings/import/
3. Select `Medium`

#### Context
People are trying to import things we don't support. I'm proposing we update the instructions in the UI to be more clear.

#### Proposed Text
![medium](https://user-images.githubusercontent.com/1301932/52151620-5c987f00-2639-11e9-97fa-98ff0673f32f.png)

Upload your **Medium export file** to start importing into [Site Name]. A Medium export file is an ZIP file containing several HTML files with your stories. Need help [exporting your content](https://en.support.wordpress.com/import/import-from-medium/)?

Related to: https://github.com/Automattic/wp-calypso/issues/30413

**Comment by mattsherman** [comment]
I'm going to take this one over to wrap it up while Marek is AFK.
