### ISSUE TITLE
Facebook Publicize Connection Error - Unable to Add Page Connection

### ISSUE THREAD

**Issue by aamills** [Automattic/wp-calypso#30550]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/
2. Choose site you want to make publicize connection on.
3. Attempt to connect Facebook (while logged into the account that is the admin/owner of a FB page - not profile only).
4. Receive error `The Facebook connection could not be made because this account does not have access to any Pages. Facebook supports Publicize connections to Facebook Pages, but not to Facebook Profiles. Learn More about Publicize for Facebook`

#### What I expected
Expected to make connection to my Facebook Page.

#### What happened instead
Receive error `The Facebook connection could not be made because this account does not have access to any Pages. Facebook supports Publicize connections to Facebook Pages, but not to Facebook Profiles. Learn More about Publicize for Facebook`

#### Browser / OS version
Chrome, Version 71.0.3578.98 (Official Build) (64-bit)

#### Screenshot / Video
![fbconnection](https://user-images.githubusercontent.com/29556134/52143242-31516800-2618-11e9-9bfc-771edb997e66.JPG)

#### Context / Source
#manual-testing
#user-report

**Comment by cecoates** [comment]
Same issue:

2263978-hc

**Comment by rickmgithub** [comment]
- Exactly the same as the above for this user 
https://mc.a8c.com/support-stats/happychat/transcript.php?id=9987263

- And when testing on my own personal FB account with wp19841901.blog

**Comment by jonnyruzek** [comment]
Another report in 1767382-zen

**Comment by allykmyta** [comment]
Another report in 1767532-zen

**Comment by smithkyle45** [comment]
I encountered this today as well in 7692718-hc

**Comment by tbradsha** [comment]
7273507-hc

**Comment by aamills** [comment]
Just checking on things again today and it appears that the connections can be made now! Maybe it was just a temporary fluke!

I'll attempt to update all the users from this thread and edit my comment to note that once it's done and then mark this as resolved.

**Comment by aamills** [comment]
Users that were reported or contacted us are updated that it appears to be working, marking as closed.

**Comment by lizthefair** [comment]
I had a new report of this on a Jetpack site today so I'm reopening:

1829001-zen

Note:  In this case I was not able to replicate on my own test site.

**Comment by pmciano** [comment]
User in 1829001-zen replied that the page in question is managed by Facebook Business Manager, so I think we can close this again.

**Comment by sstabrizi** [comment]
I'm going to reopen this issue because I had another report of this in 12377763-hc that I was able to reproduce when trying to connect my pages to my sites on WP.com. Had a discussion about this with another HE in Slack and they were having the same trouble on their test sites. This includes sites that haven't had Publicize Facebook connections before.

Example sites:
• Simple: test560034133.wordpress.com
• Simple with prior connection: verygoode-testing.blog
• Self-hosted: goode.pro
• Atomic V2: goodecommerce.wpcomstaging.com

**Comment by jamiepalatnik** [comment]
Also reported in 12378494-hc. I could recreate on the user's site, but not on my own test site.

**Comment by nielslange** [comment]
Also reported in 2082220-zen
