### ISSUE TITLE
WordPress Imports: Instructions for correct file uploads

### ISSUE THREAD

**Issue by dezzie** [Automattic/wp-calypso#30560]
#### Steps to reproduce
1. Starting at URL:
2. https://wordpress.com/settings/import/
3. Select `WordPress`

#### Context
People are trying to import things we don't support. I'm proposing we update the instructions in the UI to be more clear.

#### Proposed Text
![shorter message](https://user-images.githubusercontent.com/1301932/52151971-6b336600-263a-11e9-8ce2-b87d0c7fb1d4.png)

Upload a **WordPress export file** to start importing into [Site Name]. A WordPress export is an XML file with your page and post content, or a zip archive containing several XML files. Need help [exporting your content](https://en.support.wordpress.com/import/coming-from-blogger/)?

Related to: https://github.com/Automattic/wp-calypso/issues/30413

**Comment by andfinally** [comment]
I added a note in the PR about the final question `Need help exporting your content?` - I'd suggest we don't just leave the question hanging, but close it with a call to action.
