### ISSUE TITLE
[Business plan] 2 year plan shows the pro-rated message

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#30579]
I got an issue here with the 2-year Business plans - the user is being prompted to use the pro-rated credits, however they don’t have access to the eCommerce plan. I’ve replicated this on my end and it appears to happen only on the 2-year Business plan, but not on the 1-year one.

<img width="1386" alt="plans wordpress com 2019-02-01 09-01-35 png 2019-02-04 19-24-12" src="https://user-images.githubusercontent.com/6737345/52225215-88726980-28b2-11e9-9e54-495eb55ef75e.png">

#### What I expected
Not to see the pro-rated credits message.

#### What happened instead
I saw the pro-rated credits message.

#1765989-zen
#user-report

**Comment by obenland** [comment]
@sararosso Is that due to the A/B test for the plan switcher?

**Comment by sararosso** [comment]
@obenland 100% of new EN signups should be seeing the the plans, not sure why it would be shown to others. 

@Robertght can you share the user id in Slack - wpcom-ecommerce-plan  so we can see what tests they're a part of?

**Comment by obenland** [comment]
My test user `obietester` doesn't (though I'm not sure whether I set it up on purpose in the past and just forgot about it or not)

**Comment by sararosso** [comment]
@obenland Just added another customer who sees this (to the Trello card) and isn't a part of any test.

**Comment by dzver** [comment]
Now that eCommerce is fully rolled out, this should no longer be an issue.
