### ISSUE TITLE
Contact info: Reloading the editor

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#30608]
When I reload the editor I see this:
<img width="748" alt="screenshot 2019-02-06 at 11 39 12" src="https://user-images.githubusercontent.com/275961/52339359-c7183900-2a04-11e9-9af6-4ffbee8b66fc.png">

**Comment by enejb** [comment]
This issue only appears on WordPress.com and WordPress mutisites. Where filtering of the html appears. 
The main problem is that when we save the block The `itemscope, content, itemtype and itemprop` attributes gets removed. 

The fix entails adding the attributes to the `$global_attributes` in `_wp_add_global_attributes`.
