### ISSUE TITLE
Contact info: Empty p tag

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#30610]
There is an empty paragraph tag at the end of the address. We shouldn't be creating this:

<img width="1397" alt="screenshot 2019-02-06 at 11 37 54" src="https://user-images.githubusercontent.com/275961/52339715-c6cc6d80-2a05-11e9-9893-05ee5910bcd1.png">

**Comment by enejb** [comment]
I am having a hard time reproducing this issue. 

The only way I was able to replicate is when I click to add another block inside the contact info block but then don't add any text. 

This results in an empty tag. I think the solution here needs to happen in gutenberg/core.

**Comment by scruffian** [comment]
Yeah you're right. This is a core issue. I moved it there: https://github.com/WordPress/gutenberg/issues/13835
