### ISSUE TITLE
Gutenberg Iframe: "View post" link after publishing is trapped in the iframe.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#30622]
When publishing a post from the iframed block editor, the resulting "View post" and "... is now live" links will be within the iframe, and will navigate within the iframe (this is observable in how the URL does not update on navigating). They'll need to be bumped up to the top level.

**Comment by vindl** [comment]
Fix proposed in D24109-code.

**Comment by vindl** [comment]
Fix deployed.
