### ISSUE TITLE
MailChimp connection: Button always connecting

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#30620]
#### Steps to reproduce
1. Add a MailChimp connection
2. Notice that the connection completes and is loaded
3. The button never changes to a disconnect button, you have to reload the page

![screen shot 2019-02-06 at 17 38 23](https://user-images.githubusercontent.com/841763/52357357-525df280-2a36-11e9-882e-a39053e966f8.png)

I'd add that the language in the modal window is confusing and/or inaccurate:

![screen shot 2019-02-06 at 17 42 11](https://user-images.githubusercontent.com/841763/52357525-97822480-2a36-11e9-8594-ab7682b82f1e.png)

cc: @artpi @jeffersonrabb

**Comment by artpi** [comment]
The modal was somehow introduced in b147a93aa781f982a5b15322a65857121a46b61b by @johngodley . I don't know why it appears yet

**Comment by johngodley** [comment]
I don't think it was added in that commit, at least not intentionally. I have also seen the same modal sometimes appear for Google Photos and I haven't figured out where it's coming from - it's not consistent and I don't know how to trigger it.

**Comment by artpi** [comment]
Yeah, I also don't see how you would introduce that John :) Im just keeping a log of investigation here and this is my best bet, but that might be a coincidence that it works in the previous commit because of some caching in calypso :)
