### ISSUE TITLE
Gutenpack: Ads block rendering

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#30624]
The WordAds block currently doesn't render anything on the front end of the site.

**Comment by sirreal** [comment]
Will be handled by https://github.com/Automattic/jetpack/pull/11240

This "to do" should be removed:

https://github.com/Automattic/wp-calypso/blob/36aa7a1ac647851799a8facc0a335f4737ca4667/client/gutenberg/extensions/wordads/index.js#L42
