### ISSUE TITLE
Mailchimp block: Improve API error handling message

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#30621]
Provide some generic error messaging when the API call fails ([#30275 (comment)](https://github.com/Automattic/wp-calypso/pull/30275#discussion_r254254083))

via https://github.com/Automattic/wp-calypso/pull/30275#issuecomment-461077607

cc: @artpi @jeffersonrabb

**Comment by artpi** [comment]
This is a design decision.
I specifically obfuscate error messages so that when spammers try to abuse the mechanism, it will be harder for them to know why its failing.
There are layers of spam protection and I dont know if we want to return proper error message

**Comment by scruffian** [comment]
Closing since this seems to be deliberate.
