### ISSUE TITLE
Gutenpack: WordAds block controls

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#30631]
The size type picker should live on the block initially and then move to the sidebar once the size is selected (see the prototype for more details)

<img width="829" alt="screenshot 2019-02-06 at 17 57 09" src="https://user-images.githubusercontent.com/275961/52367395-df5b7880-2a43-11e9-9e2f-b77baac08283.png">

**Comment by sirreal** [comment]
I looked at the prototype and did't notice details related to this. I do have some UX questions and concerns.

From what I understand:

When a block is initially added, it doesn't have a format and the user is required to interact with a dropdown in the block to finish inserting the block. Until they make this second interaction, the block has no format and cannot be rendered. Requiring a second interaction and not rendering an ad that is inserted in the editor seems cumbersome and confusing.

Once a format is selected, the dropdown moves. The element disappears and is now located in the sidebar, which may or may not be visible. This seems confusing.

---

I can imagine ways to make these issues smoother, but I wonder about the premise. Is the sidebar the best place for this block setting? Block styles are ostensibly for adding CSS, but could be adapted for this use case.

I've also been conflicted about the independence of block alignment and format all along. Depending on the format (aspect ratio) that's chosen, they seem to make sense in a particular alignment or not:

| Format | Left | Right | Center | Wide/Full |
| --- | :---: | :---: | :---: | :---: |
| `Rectangle 300x250` | ✅ | ✅ | ✅ | 🚫 |
| `Leaderboard 728x90` | 🚫 | 🚫 | ✅ | ✅ |
| `Mobile Leaderboard 320x50` | 🚫 | 🚫 | ✅ | ✅ |
| `Wide Skyscraper 160x600` | ✅ | ✅ | 🚫 | 🚫 |

I'd advocate for reconsidering the format/alignment question.

cc: @thomasguillot

**Comment by simison** [comment]
Seems like if sizes are always fixed (and there's no ad format which dynamically takes the most suitable space), I'd remove wide & full options since they don't effectively change how the block looks like and is kinda equal of "center".

Not that alignment options might make sense in future where we have different areas thant "post content area":  narrow sidebars (where centered 160x600 might make sense), or header/footer (where right align leaderboard might make sense)

**Comment by sirreal** [comment]
> I'd remove wide & full options since they don't effectively change how the block looks like and is kinda equal of "center".

👍 Good point, that is what we do currently. In an ideal Gutenberg world, wide and full do make sense for some formats.

**Comment by thomasguillot** [comment]
Suggestions:

* Have [Left | Center | Right] for all the formats.
* Remove the Format dropdown from the sidebar.
* When adding a new block, rather than the "No Format" placeholder let's use a format. I'd recommend 300x250 as it's the most flexible with content.
