### ISSUE TITLE
Checklist view on the question mark icon shows the wrong status

### ISSUE THREAD

**Issue by guicmazeredo** [Automattic/wp-calypso#30652]
#### Steps to reproduce
1. SU the user `mattyandannika` to access the dashboard of the site `mattyandannika.blog`.
2. Click on the question mark on the bottom right. 
3. You will notice the checklist status shows 11/12. Click on it (Continue site setup) to get the Checklist section. 
4. Notice that the checklist page shows that all tasks are complete (12/12.).

#### What I expected

I expected the status of the checklist page and the checklist view on the question mark icon to match. 

#### What happened instead

The checklist view on the questions mark icon seems to be wrong.

#### Browser / OS version

Chrome Version 71.0.3578.98 (Official Build) (64-bit)

#### Screenshot / Video

Question mark icon view: http://cld.wthms.co/KywWBY
Checklist Page view: http://cld.wthms.co/Yngy1W

**Comment by wprhunt** [comment]
I have a similar issue with a customer who is actually a Contributor level user and is seeing 1/8 checklist when they view the support icon.

User: `freestoriesandgames`
Site: `readerscommonresource.wordpress.com`

What the customer sees:
![screenshot_2019-02-20-09-20-22](https://user-images.githubusercontent.com/16481427/53109688-02376380-34ff-11e9-97ad-d42e246d437b.png)
![screenshot_2019-02-20-09-24-28](https://user-images.githubusercontent.com/16481427/53109694-0499bd80-34ff-11e9-9a39-5ad1da528161.png)

This is true on both mobile and desktop versions of Chrome and I was able to recreate.
<img width="1658" alt="your site readers common resource wordpress com 2019-02-20 11-06-30" src="https://user-images.githubusercontent.com/16481427/53109969-a9b49600-34ff-11e9-979c-6753913ad71b.png">

I've tested completing the checklist for that site from the Administrator user and setting that user as an Administrator and completing the checklist from their end but when I set that user back to Contributor, this bug still shows the checklist is incomplete (1/8) when they click the support button when they are on the dashboard of `readerscommonresource.wordpress.`

If this is a separate bug, let me know and I can create a new topic.
