### ISSUE TITLE
Mailchimp: Visual review

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/wp-calypso#30667]
Here's a review of UI elements that need fixing:

__Editor UI:__

- [ ] I don't see the need for us to have a heading as part of the block. If for some reason we need one, we should have the same options as the Heading block.
- [ ] Can the email input be a `type="email"` rather than `type="text"`
- [ ] Could we have a button like the Button block and remove the label option from the sidebar?
- [ ] The text underneath, could it just be a Paragraph block (within the block) with some italic applied to it? At the moment, the italic setting doesn't work since it's already in italic. I'm not quite sure why this is a `figcaption` either, from an HTML point of view this makes no sense and it's invalid.
- [ ] Some places it's written "MailChimp", and some other "Mailchimp". The correct version is "Mailchimp" now.

__Front-end:__

- [ ] The forced styles on the email input are not needed `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-email` themes style their inputs and forcing this is not recommended.
- [ ] Same with `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-form-error` I would suggest we add a generic class `error` to the input. Again, most themes will style this.
- [ ] Displaying all 3 messages in the content with a `display: none` feels strange. Can we just add the message with some JS?
- [ ] Processing, have a more subtle background: `rgba(0, 0, 0, 0.025)`
- [ ] Success: Let's use an accessible green #1d7819 
- [ ] Same for error: #eb0001 
- [ ] `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-notification` let's switch to ems: `margin-bottom: 1.5em` and `padding: 0.75em`.
- [ ] Remove the `text-center` from the messages. If the user adds a bunch of text to these messages, it wouldn't look great centred.

**Comment by jeffersonrabb** [comment]
FYI @artpi I'm planning to do a PR today with these UI changes. If you see anything you'd like to weigh in on, please do!

**Comment by artpi** [comment]
> Some places it's written "MailChimp", and some other "Mailchimp". The correct version is "Mailchimp" now.

We are consistent with "MailChimp" in every other piece of this outside the block.
 
>  Displaying all 3 messages in the content with a display: none feels strange. Can we just add the message with some JS?

This was the only way to get translations when it was SSR block.
But now we can tackle this.

The problem with JS is that translations are hard, but we could turn it into some kind of param / attribute.

Problem with display:none is that error messages will be shown in the excerpt when block is at the beginning of post / page.


I have no opinion on other stuff.

**Comment by thomasguillot** [comment]
According to brand guidelines:

> “Mailchimp” is one word, spelled with a big M and a little c. It used to have a big M and a big C, but the times have changed.

https://mailchimp.com/about/brand-assets/

**Comment by scruffian** [comment]
Success: Let's use an accessible green #1d7819
Same for error: #eb0001

We should make sure we're using the Muriel colours here.

**Comment by simison** [comment]
>We should make sure we're using the Muriel colours here.

Shouldn't we use the colours from Gutenberg for consistency?

https://github.com/WordPress/gutenberg/blob/6ee1944cc96c53a2716522bdf3273d4d7459338b/assets/stylesheets/_colors.scss#L85-L88

**Comment by thomasguillot** [comment]
> We should make sure we're using the Muriel colours here.

Yep that's what I'm using: https://automattic.github.io/color-studio/index.html

**Comment by thomasguillot** [comment]
> Shouldn't we use the colours from Gutenberg for consistency?

These colours aren't accessible on normal text.

![screenshot 2019-02-08 at 15 42 02](https://user-images.githubusercontent.com/177929/52488612-1e123f80-2bb8-11e9-8622-327f8ef10a4c.png)

**Comment by simison** [comment]
>> We should make sure we're using the Muriel colours here.
>
>Yep that's what I'm using: https://automattic.github.io/color-studio/index.html

Nice 👍  We can use Muriel colours via variables, see: https://github.com/Automattic/wp-calypso/blob/eac003dfbc0bc112d9560a28838fad716b923f4a/assets/stylesheets/shared/_colors.scss
