### ISSUE TITLE
Comments: Jetpack site's comment does not show its been liked after refreshing page

### ISSUE THREAD

**Issue by aerych** [Automattic/wp-calypso#30675]
There seems to be an issue showing likes for comments from a Jetpack connected site.  Liked comments do not have a count or show they've been liked, and if you like a comment and then refresh a page the like icon is not highlighted. 

It looks like comments are calling the `v1.1/sites/%s/comments/` endpoint for both WordPress.com and Jetpack sites, but the `i_liked` and `like_count` fields are not returned for Jetpack sites unless the query includes the `force=wpcom` query parameter. 

#### Steps to reproduce
0. Have a Jetpack connected site and have comments on that site.
1. Visit https://wordpress.com/comments/all/yourjetpackconnectedsite.com
2. Like one of the published comments on the site.
3. Refresh the browser.
4. Observe the comment does not show its been liked.

#### What I expected
Comments that have been liked to have a highlighed icon.

#### What happened instead
The like icon is not highlighted.

#### Browser / OS version
Firefox 65.0

#### Screenshot / Video
![comment-like-not-saved 2019-02-08 12_35_44](https://user-images.githubusercontent.com/1435271/52498870-97e9ff00-2b9f-11e9-8705-34a9cd9c356a.gif)

**Comment by brbrr** [comment]
2475267-zen
