### ISSUE TITLE
Site checklist cannot be completed unless there's a G Suite purchase

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#30688]
The on boarding checklist shows recently a 11th step, which involves purchasing G Suite. Without finishing this step, the list cannot be dismissed and appears always in the user dashboard.

It should be possible to dismiss that notice, or alternatively be able to opt for a different type of email solution (for example [email forwarding](https://en.support.wordpress.com/email-forwarding/), or a free solution like [Zoho](https://en.support.wordpress.com/add-email/add-email-through-zoho-mail/), in order to finish this step.

<img width="602" alt="screen shot 2019-02-09 at 19 45 49" src="https://user-images.githubusercontent.com/3812076/52532470-7122f880-2d58-11e9-8971-3cbdba617f63.png">

Reported on 1786432-zen

**Comment by torres126** [comment]
#30692

**Comment by robertf4** [comment]
Sorry about that! Had a mixup between a function that returns a function, and a function that returns a function that returns a function. 🙄 

Fix will be going live shortly.
