### ISSUE TITLE
Converting classic tiled gallery to tiled gallery block

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/wp-calypso#30695]
#### Steps to reproduce the issue

1. Create a new classic block
2. Add a tiled gallery in the block via Add Media > Gallery
3. Convert to blocks

#### What I expected
Tiled gallery converted to tiled gallery block

#### What happened instead
Tiled gallery block shows error "This block has encountered an error and can't be previewed".

**Comment by simison** [comment]
Confirmed, this fails with undefined `url` here:

https://github.com/Automattic/wp-calypso/blob/dc919a5ae1f8456bf7789db46b329877a257de22/client/gutenberg/extensions/tiled-gallery/layout/index.js#L28

**Comment by simison** [comment]
Previously `[gallery]` shortcode was always transforming to Core gallery block.

Now that something has changed, the existing transform in the block has revealed to be buggy.
