### ISSUE TITLE
Editor: Reduce alignment points

### ISSUE THREAD

**Issue by alternatekev** [Automattic/wp-calypso#3072]
When writing a new post today, I noticed that the editor has a number of vertical alignment points:

<img width="1318" alt="screen shot 2016-02-04 at 6 27 26 am" src="https://cloud.githubusercontent.com/assets/1084656/12816227/6418749a-cb08-11e5-9b2b-0ea312fde69f.png">

(the second rule in that screenshot is covering up a divider line in the sidebar under the site name)

In Photoshop, I made some minor adjustments and came up with this:

<img width="1319" alt="screen shot 2016-02-04 at 6 28 37 am" src="https://cloud.githubusercontent.com/assets/1084656/12816344/2c7397ee-cb09-11e5-9e69-83157f9fc45a.png">
- Title moved down a few pixels to align its baseline with the divider in the sidebar
- Tabs/Icon bar moved up a few pixels to align the tab text baseline with the NEW DRAFT baseline in the sidebar
- Preview/Publish buttons were moved slightly to align their center with the the center divider in the Tab/Icon bar
- Bottom border of the sidebar publish box was extended a bit to align with the bottom of the Tab/Icon bar

Comparison shots:

<img width="1264" alt="screen shot 2016-02-04 at 6 24 43 am" src="https://cloud.githubusercontent.com/assets/1084656/12816332/075c00d6-cb09-11e5-917d-c452cfaa9df9.png">

<img width="1271" alt="screen shot 2016-02-04 at 6 31 29 am" src="https://cloud.githubusercontent.com/assets/1084656/12816322/f42483f8-cb08-11e5-9292-859f66364da1.png">

cc @kellychoffman

**Comment by alternatekev** [comment]
The Preview/Publish buttons could also be baseline-aligned to the center divider, it probably doesn't matter much there.

**Comment by kellychoffman** [comment]
Cool. This one is a tough one to see in this form. I would say to spin up a `try` PR. There's a lot of different scenarios to consider: Kitchen sink closed, different screen sizes, and even draft states. 

For example, compare: 

<960px width, new draft:
<img width="426" alt="screen shot 2016-02-04 at 6 55 53 am" src="https://cloud.githubusercontent.com/assets/5835847/12818748/ed473cca-cb0c-11e5-9b1e-cec473b58758.png">

<960px width, saved draft:
<img width="424" alt="screen shot 2016-02-04 at 6 56 17 am" src="https://cloud.githubusercontent.com/assets/5835847/12818749/ed476628-cb0c-11e5-95d7-1a5d8adee102.png">

cc: @hugobaeta for your input as well.
