### ISSUE TITLE
DNS configuration notice: Indicate nameservers requirement for all subdomains/Business sites

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30759]
#### Steps to reproduce 

- Add a subdomain (one that is not already pointing to WordPress.com) to a WordPress.com site with domain mapping subscription

#### What happens currently

The DNS configuration copy indicates that the domain is required to point to WordPress.com. It does, yes, but the copy currently reads:

`{domain's} CNAME records should be configured.`

![screenshot 2019-02-11 at 02 27 39](https://user-images.githubusercontent.com/18581859/52641120-293dd600-2efe-11e9-8db9-ad661cc1d448.png)

#### What is suggested instead

The copy reads `{domain's} DNS should be configured.` instead. Or, `{domain's} name server records should be configured.` as is the case for root domains.

This is suggested because the `Learn more` link points to https://en.support.wordpress.com/domains/map-subdomain and as indicated here, WordPress.com sites (Business plan) require WordPress.com nameservers to be able to install plugins/custom themes.

If we would want to retain current copy, we should at least update the copy for Business-plan sites.

It could be counterproductive to first set CNAME records, and then remove it to set name server records for WordPress.com Business plan users.

#### Context

#painpoint #manual-testing 

@Automattic/cobalt for thoughts. 🙃

**Comment by aidvu** [comment]
Made a task to follow up. Thanks for reporting!
