### ISSUE TITLE
Subdomain availability shown incorrectly when adding it to a site

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30760]
#### Steps to reproduce 

- Open https://wordpress.com/domains/add 
- Add a subdomain like `atomic.wpcom.arunsathiya.blog` (note that it's not mapped to any other site so far at this stage)
- Ensure that the root domain `arunsathiya.blog` is already used on another WordPress.com site.

#### What is shown

A notice that reads `atomic.wpcom.arunsathiya.blog is taken, if you purchased atomic.wpcom.arunsathiya.blog elsewhere, you can map it for free` is shown.

#### What is suggested instead

Since only `arunsathiya.blog` is used on another WordPress.com site, but not `atomic.wpcom.arunsathiya.blog`, the notice should be improved as below:

`arunsathiya.blog is taken, if you purchased arunsathiya.blog elsewhere, you can map atomic.wpcom.arunsathiya.blog for free.`

#### Notes

This was also https://github.com/Automattic/wp-calypso/issues/8997 which looks similar, but I am not entirely sure if that's the same.

cc @Automattic/cobalt

**Comment by aidvu** [comment]
Made a task to follow up. Thanks for reporting!

**Comment by klimeryk** [comment]
This is an edge case in a very brittle part of our code. The impact of it should be minimal. As such, I'm sorry, but will have to close this as wontfix. It is, however, in our plans to rewrite that whole logic, but cannot promise when. When that happens, I can assure you, we will be closely looking at subdomain handling cause I know it's pretty broken right now :(
