### ISSUE TITLE
CPTs: Reusable blocks section in Calypso - "Add" button leads to a blank page

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#30777]
When there’s a reusable block created on a simple site on WordPress.com, the "Block" tab will show up in Calypso.

Now, when we click on the “Add” button on the "Block" tab, we get WSOD.

#### Steps to reproduce
1. Start on any WordPress.com simple site
2. Create a reusable block in Gutenberg - this will create a Block section in Calypso
3. In Calypso click on the "Add" button
4. WSOD will be returned

#### What I expected

There will be no WSOD - or - there will be no Block section in Calypso.

#### What happened instead

Block section was present in Calypso and clicking on the "Add" button returned WSOD.

URL of the destination WSOD page:

`https://wordpress.com/block-editor/edit/wp_block/XXXXXXXX.wordpress.com`

#### Screenshot

![screen shot on 2019-02-14 at 12 46 50](https://user-images.githubusercontent.com/25105483/52784826-a8462200-3056-11e9-98ed-1c448fd52c5e.png)

#### Context / Source
#user-report (1802210-zen)

**Comment by aisajib** [comment]
Another user reported this here: 160870-hc

I would think this option not showing up at all would be less confusing for the users. But if it's going to be a feature, we hope we can get the white screen of death fixed.

**Comment by gwwar** [comment]
Let's not display the section for now or keep it as a wp-admin redirect with an external link icon provided by the sidebar options.

**Comment by galakhyati** [comment]
Another user reported this here: [10447760-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=10447760)

**Comment by galakhyati** [comment]
Another user reported this here: 10447760-hc

**Comment by lizswafford** [comment]
Another user reported this here: 8278859-hc
