### ISSUE TITLE
Import: change button types to be more clear

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#3077]
Currently, some of the buttons in the Importer could be more clear.

![screen shot 2016-02-04 at 10 48 12 am](https://cloud.githubusercontent.com/assets/618551/12824589/85dbab72-cb37-11e5-9610-556c623b9db9.png)

For the `Cancel` and `Stop Import` buttons let's use `is-scary`

![screen shot 2016-02-04 at 12 04 40 pm](https://cloud.githubusercontent.com/assets/618551/12824613/ac4b7eae-cb37-11e5-9622-32e5e604325c.png)

For the `Done` button, let's make sure it's the same as the first Start Import button.

![screen shot 2016-02-04 at 12 07 23 pm](https://cloud.githubusercontent.com/assets/618551/12824651/de6dd67a-cb37-11e5-9e56-2de257866500.png)

**Comment by lancewillett** [comment]
Related, the buttons on this screen could use a bit of spacing toward the bottom right:

![screen shot 2016-02-11 at 14 34 51](https://cloud.githubusercontent.com/assets/66797/12992434/b3c061c8-d0d1-11e5-9bea-95fa7acf7fbf.png)
