### ISSUE TITLE
Import: update to Gridicons

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#3078]
I found 2 icons that should be replaced with a Gridicon component:

The upload cloud here should use `<Gridicon icon="cloud-upload" />`

![screen shot 2016-02-04 at 10 48 12 am](https://cloud.githubusercontent.com/assets/618551/12824741/554f5232-cb38-11e5-8a75-be18adbc9185.png)

The arrow here should use `<Gridicon icon="arrow-right" />`

![screen shot 2016-02-04 at 11 27 27 am](https://cloud.githubusercontent.com/assets/618551/12824758/6b3c9ec4-cb38-11e5-8f5d-5791fd2f5e24.png)

**Comment by dmsnell** [comment]
oh dear oh dear - that certainly dates this code! what a marvel that the notifications client got a Gridicon update before Calypso
