### ISSUE TITLE
Publicize: remove service name from `maybeDisplayGooglePlusNotice` helper

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30787]
Feedback via https://github.com/Automattic/wp-calypso/pull/30504#discussion_r256775175

>we apparently know the service name because this method is dedicated to `google-plus` - why do we need to pass it as a parameter anyway?

https://github.com/Automattic/wp-calypso/blob/7918c44e9a4a76d72571d5d4061a12e5489ac965/client/gutenberg/extensions/publicize/connection.jsx#L95

https://github.com/Automattic/wp-calypso/blob/7918c44e9a4a76d72571d5d4061a12e5489ac965/client/gutenberg/extensions/publicize/connection.jsx#L35-L41

cc @tyxla @eliorivero

**Comment by richardeschloss** [comment]
Could this issue perhaps be linked to the "deprecation issue" #31299 ? I.e., in < 1 month...will all the Google+ code be phased out? And perhaps help close this issue too...

**Comment by simison** [comment]
Yep, I think we can close this as the code is going away. Thanks for the heads up!
