### ISSUE TITLE
Feedback - Spam is not visible in Calypso. Only in WP-Admin. 

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#30792]
#### Steps to reproduce
1. Create a site that has a contact form.
2. Fill out that contact form in such a way that it's a legitimate submission, but it accidentally gets filtered out as spam.
3. You won't get a notification that a contact form was ever generated in any way (no email notifications, no notifications what-so-ever), and there's nowhere in Calypso to find Contact Form Spam.
4. Spam is located in WP-Admin only. So on a simple site, you must then:

1. Know that WP-Admin exists.
2. Know how to get there.
3. Know how to find Feedback - Feedback - Spam.
4. Mark that contact form submission as Not Spam.

#### What I expected
1. Spam contact form submissions to be viewable and spam to reversible from Calypso. 

#### What happened instead
1. Contact Form submissions that get auto-flagged as spam are hidden in WP-Admin, and no notification is ever given to the user. On WordPress.com simple sites, there isn't even a link to WP-Admin on the dashboard, so the typical user would have 0 clue that a submission was even sent. If the system mistakenly marks a submission as spam, then the user is missing out on legitimate reader contact submissions and possible career opportunities. 

#### Browser / OS version
All.

#### Context / Source
#empathy #perspective #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

We'd also love to know how you found the bug:  #user-report 

If requesting a new feature, explain why you'd like to see it added: So users can find all of their contact form submissions in Calypso, including spam.

**Comment by torres126** [comment]
#17437

**Comment by thehenrybyrd** [comment]
Ran into this again in a chat, when a customer was wondering why some test messages weren't getting through. A few had been caught as spam. There's no record of these messages in the Feedback section in Calypso, but they do appear in wp-admin. #5916250-hc

**Comment by rachelmcr** [comment]
Looks like this was resolved by https://github.com/Automattic/wp-calypso/pull/30799, which redirects the Feedbacks menu item to WP Admin (Calypsoified). Closing this since that changes resolves this issue.

As a sidenote: There's currently an issue with that Calypsoified sidebar but it was reported and is being addressed in https://github.com/Automattic/wp-calypso/issues/30925.
