### ISSUE TITLE
Themes: Merge `layout/logged-out-design` back into `layout/logged-out`

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#3082]
Ideally, there'd be only one logged-out layout (for consistency and ease of maintenance) which we could also use for server-side rendering. The main differences between the two logged-out layouts currently are:

* `layout/logged-out-design` uses `ThemesHead`
 * I'm wondering a bit if `Helmet` is really that beneficial. We have two levels of wrapping there (`layout/head` and `my-sites/themes/head`), and can't really leverage React anyway but need to toss around props and then extract those data again using `rewind()`. Wouldn't it be easier to just put that stuff into a Redux subtree? (And `dispatch` inside our controllers.) @mcsf?
* `layout/logged-out` uses the old `notices` store
 * I think there's a Redux store for them now, so that would need to be connected. #3083

**Comment by mcsf** [comment]
> I'm wondering a bit if Helmet is really that beneficial. We have two levels of wrapping there (layout/head and my-sites/themes/head), and can't really leverage React anyway but need to toss around props and then extract those data again using rewind(). Wouldn't it be easier to just put that stuff into a Redux subtree? (And dispatch inside our controllers.) @mcsf?

As we discussed in a video walkthrough: Helmet would make a lot less sense if Calypso were already fully Redux'd and all state (sections, layout, routing?, etc.) lived in clear places of the global tree. I think moving from Helmet to Redux will be a relatively straightforward task once we feel ready for it, so in the meantime we can benefit from the momentum advantage we're getting from Helmet.

**Comment by ockham** [comment]
Closing this issue since `layout/logged-out` doesn't exist anymore (see #2964). Maybe we should rename `layout/logged-out-design` to `layout/logged-out` tho.
