### ISSUE TITLE
Mailchimp block: add label and aria attributes

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30839]
Block outputs this HTML:

```html
<div class="components-placeholder">
	<form>
		<input type="email" required="" placeholder="Enter your email">
		<button type="submit" class="components-button is-button is-primary">
			Join my email list
		</button>
		<p>
			<small>
				By clicking submit, you agree to share your email address with the site owner and Mailchimp to receive marketing, updates, and other emails from the site owner. Use the unsubscribe link in those emails to opt out at any time.
			</small>
		</p>
	</form>
	<div class="wp-block-jetpack-mailchimp_notification wp-block-jetpack-mailchimp_processing">
		Processing…
	</div>
	<div class="wp-block-jetpack-mailchimp_notification wp-block-jetpack-mailchimp_success">
		Success! You're on the list.
	</div>
	<div class="wp-block-jetpack-mailchimp_notification wp-block-jetpack-mailchimp_error">
		Whoops! There was an error and we couldn't process your subscription. Please reload the page and try again.
	</div>
</div>
```

### Issues:
- [x] Input needs `label`: placeholder isn't sufficient enough (https://www.w3.org/WAI/tutorials/forms/labels/#hiding-label-text)
- [x] Agreement paragraph could be connected to the form by `aria-describedby`
- [x] We could avoid using small
  - Gutenberg itself has some classes like `has-small-text` or similar. Those might play nicer with the editor and themes? I saw some pretty big line-heights in some editors (inherited from `p`)
  - semantically `small` is very fuzzy, but I guess here it would kinda be used correctly? It should not be used _just_ to change font size tho and more for secondary, “small print” -type texts.
- [ ] Processing message — or perhaps the all 3 messages need to be wrapped in`aria-busy`? Maybe also `aria-live="polite"`? I can't remember exact aria-procedures for this type of thing but the knowledge is out there. :-)
- [x] Warning message needs `role="alert"`
- [x] Success message needs `role="status"`
- [x] Considering there might be multiple widgets on page, if any ID attributes are added, they'll need running numbering (on Gutenberg editor side possible using `withInstanceId`)

**Comment by jeffersonrabb** [comment]
> * Processing message — or perhaps the all 3 messages need to be wrapped in`aria-busy`? Maybe also `aria-live="polite"`? I can't remember exact aria-procedures for this type of thing but the knowledge is out there. :-)

I'm not sure this is necessary:

- On the frontend the three notifications are actually static elements whose visibility is controlled by Javascript, so they aren't really "live" elements.
- In the editor, the display of the notifications is a bonus feature. The text of the notifications is edited in normal static text inputs so the editing of the text is fully accessible without worrying about those displays.
