### ISSUE TITLE
Notices: Connect `layout/logged-out` to Redux `notices`

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#3083]
Now that there's a Redux subtree for `notices`, can we connect `layout/logged-out` to it instead of importing the old `notices` dependency? This would be one prerequisite to #3082.

@artpi since I think you worked on the notices Redux subtree.

**Comment by artpi** [comment]
TLDR: NO.
and yes. It is already done.

So:
> Now that there's a Redux subtree for notices
Yes, there is but not every notice sent is going through redux. Most of them is going through old system and we have 2 side-by-side as an interrim solution.

> instead of importing the old notices dependency

It is not old dependency. It is importing `components/global-notices` . `GlobalNotices` component is currently displaying both old and redux notices.

And `GlobalNotices` component is already connected to redux subtree and this component is not going away.
So I dont see how this could block #3082 :)

**Comment by ockham** [comment]
Ah okay, thanks for clearing this up.

> > instead of importing the old notices dependency

> It is not old dependency. It is importing `components/global-notices` . `GlobalNotices` component is currently displaying both old and redux notices.

> And `GlobalNotices` component is already connected to redux subtree and this component is not going away.
So I dont see how this could block #3082 :)

Hmm, what about that `notices` [import](https://github.com/Automattic/wp-calypso/blob/master/client/layout/logged-out.jsx#L13) and [parameter](https://github.com/Automattic/wp-calypso/blob/master/client/layout/logged-out.jsx#L25) to the `GlobalNotices` component then? It looked like some pre-Flux singleton-style data store to me, but I might be mistaken :-)

**Comment by artpi** [comment]
That will be refactored, but the problem is we cant phase out all of them until all are sent through redux so it needs to use old datastore also

**Comment by ockham** [comment]
Closing this issue since `layout/logged-out` doesn't exist anymore (see #2964).
