### ISSUE TITLE
Mailchimp block: it's possbile to insert links to the button

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30846]
It's possible to copypaste an URL in the submit button:

- Insert block
- Select some text in the button
- Copypaste an URL
- Most of the time it "works" but I also got the block invalidated on some refresh, but couldn't really reproduce afterwards.

...not sure if this is a bug or a feature. 😁 

Maybe a defect in underlying button component used?

### Screenshots

Editor
<img width="278" alt="image" src="https://user-images.githubusercontent.com/87168/52942814-6974dc80-3374-11e9-8acf-85a7fd0de469.png">

View side
<img width="216" alt="image" src="https://user-images.githubusercontent.com/87168/52942837-7691cb80-3374-11e9-8ebb-e92c5af844e3.png">

View side Hover
<img width="218" alt="image" src="https://user-images.githubusercontent.com/87168/52942846-7eea0680-3374-11e9-8e31-9f8dbc7e74b7.png">

**Comment by simison** [comment]
@Automattic/poseidon I'd imagine this is happening also for other forms blocks where this component is used?

**Comment by jeffersonrabb** [comment]
Looked into this a bit, and I don't see an easy way to block this. I tried adding an explicit `formattingControls` attribute that excluded links `formattingControls={ ['bold', 'italic', 'strikethrough'] }` but that didn't make any difference.

**Comment by lezama** [comment]
Is it a bug or a feature? :P

**Comment by scruffian** [comment]
The block doesn't get invalidated for me. This is a very strange thing to do, but it seems to work fine so I don't think we should change anything unless it causes a problem. Feel free to reopen if you can see a reason to fix it :)

**Comment by jeffersonrabb** [comment]
I'm actually confused how you could have ever invalidated Mailchimp, since it's a Server-Side rendered block. I was under the impression invalidation only occurs for blocks with a `save()` function.

**Comment by simison** [comment]
I think it just failed with some error, not on block invalidation per-se
