### ISSUE TITLE
Customizer: Static Front Page should not be allowed to match the Posts Page

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#3085]
I suppose this could be thought of as an enhancement - but IMO it is pretty broken and should be treated as a bug - why would we allow users to break their site?

If a user selects the same page for both their Static Front Page and their Posts Page, wonky stuff starts happening.

To Reproduce:
1) Make a site, any theme
2) Under Static Front Page, set both the Static Front Page and the Posts page to the same page
3) Notice it doesn't show the front page content, nor does it act exactly like the latest posts options.

Why allow this at all?  Three (separate) solutions come to mind:
1) Not list the front page in the posts page dropdown or the posts page in the front page dropdown
2) Give an error if the user tries to save with matching front page and posts page, something like "please select the latest posts options if you want your front page to match your posts page"
3) Revert them to the "latest posts" option if the static front page matches the posts page (a yellow message letting them know we did this is probably ideal)

Without users being 100% clear what these options do, they often set them as the same and then their site doesn't work as expected.

There is no situation where the posts page and the front page should match.

**Comment by lancewillett** [comment]
Good points, thanks for raising this issue — this is a potential stumbling block especially for new users.

Notes:
- Would be great to have visuals here to document what's happening and what would be better: screenshots and maybe a video.
- This isn't Calypso related — Customizer works the same from wp-admin or other places on WP.com.

**Comment by lancewillett** [comment]
Similar-looking core WordPress.org ticket: https://core.trac.wordpress.org/ticket/21492

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue.  Different themes seem to behave differently, but they all have some sort of problem with setting the Static Front and Posts Pages to the same thing.  Here's a visrec with the Oxygen theme.  Note that the page is repeated over and over, and the X button to exit the Customizer requires several clicks in order to escape.

![wp-calypso-3085](https://cloud.githubusercontent.com/assets/7233112/17113807/3a6a667c-527a-11e6-858f-5d9598886a55.gif)

**Comment by sixhours** [comment]
Hey @hoverduck ! Definitely still a core Customizer bug. Theme team is actively working on a patch for this for WP.com.

**Comment by sixhours** [comment]
Patch is up for Automattic only, ready for testing. Example of how it works: https://cloudup.com/cRNACGlQdib

**Comment by lancewillett** [comment]
@sixhours Did this ever get merged to WP.com?

I see the core patch still in progress: https://core.trac.wordpress.org/ticket/21492

**Comment by sixhours** [comment]
Yes indeed, it's live for WP.com! I don't think we've posted it to the core ticket for consideration, though.

**Comment by lancewillett** [comment]
Cool — closing. :)

**Comment by lancewillett** [comment]
Closed today in WP core: https://core.trac.wordpress.org/ticket/21492

> Customize: Show notification error with "Your homepage displays" control when homepage and posts page are set to be the same (but not empty).
