### ISSUE TITLE
Jetpack nova_menu_item theme support does not work with the block editor

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#30851]
Reported in 1811329-zen , the food menus added by [Jetpack's nova_menu_items](https://jetpack.com/support/custom-content-types/) seem to return a blank screen if using the block editor, while using the classic editor still works fine.

This only seems to happen on non-atomic-wpcom sites, as I've been unable to reproduce it on Atomic and self-hosted.

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/ > My Sites . Select any non-atomic site.
2. Select the [Canape theme](https://wordpress.com/theme/canape) or any other theme that has `nova_menu_item` support
3. Go to http://wordpress.com/ > My Sites > your_site > Food Menus and `Add menu item`, the URL will be similar to `https://wordpress.com/types/nova_menu_item/$your_domain` , when creating a new menu the URL will be `https://wordpress.com/block-editor/edit/nova_menu_item/$your_domain`
4. See how the screen becomes blank and cannot be created:

<img width="1280" alt="screen shot 2019-02-18 at 21 14 04" src="https://user-images.githubusercontent.com/3812076/52956598-335e4980-33c2-11e9-8f94-7c0c1664c415.png">

If we go through wp-admin, or we switch to using the classic editor, this becomes usable again:

1) Go to https://example.wordpress.com/wp-admin/edit.php?post_type=nova_menu_item
2) Click on `Create one item`, you'll be redirected to `https://your_domain.wordpress.com/wp-admin/post-new.php?post_type=nova_menu_item`
3) See the nova_menu_item working fine:

<img width="1280" alt="screen shot 2019-02-18 at 21 17 23" src="https://user-images.githubusercontent.com/3812076/52956732-9cde5800-33c2-11e9-96b0-3f6128b4fc8a.png">

#### What I expected

That the menu creation post type shows up and can be created.

**Comment by fernmed** [comment]
Just had this same issue with another user. The workaround with going through WP-Admin seems to work so that was good. Also Classic editor works as well. Block editor on it's own and going through Calypso seems to break it. User was on the Restaurant theme. 

#8885090-hc

**Comment by cecoates** [comment]
Got another one, this time with the Aperitive theme.

2042243-zen

I've recommended the user stick with WP Admin for now.

Interestingly, the message asking folks to try Gutenberg seems to pick up on the use of the word "menu":

![2019-05-19_12-20](https://user-images.githubusercontent.com/10121835/57985720-b3339880-7a31-11e9-94ce-394610a7e969.png)

Although in this case it's not accurate. It's obviously referring to a site menu while these specific themes are about Food Menus.
