### ISSUE TITLE
Tokens: Add status props similar to notices

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#3086]
In [this comment](https://github.com/Automattic/wp-calypso/pull/3058#issuecomment-179957679) @rickybanister asked:

> How can we do nice inline validation in the token field? Can we?

I think we can support this by using status props similar to how notices work. We could perhaps use `isSuccess` and `isError` which would allow us to change the default colors to red and green. Thoughts?

cc @mtias

**Comment by rickybanister** [comment]
I also thought we might be able to use the Tooltip component to show a validation error attached to the errant item. Not sure how that would play together with this, but worth thinking about.

**Comment by mtias** [comment]
Mmm, it'd help to have some visuals of how this may work to better identify where it belongs.

**Comment by ebinnion** [comment]
This is what I've put together so far in #3096.

![screen shot 2016-02-04 at 5 26 01 pm](https://cloud.githubusercontent.com/assets/1126811/12851703/e436709e-cbf0-11e5-942f-6e345aaf5e71.png)

But @rickybanister's original mocks call for a bit "lighter" of a design.

![add people 5](https://cloud.githubusercontent.com/assets/1126811/12851756/2dd85a32-cbf1-11e5-8175-84fd8978dfa3.png)

I think a combination of #3090 and #3096 might give us something similar to the look in the second mock.

**Comment by rickybanister** [comment]
Here's the design showing a validation error (we may update the design to use something more like the tooltip to display the actual error, but:

<img width="276" alt="screen shot 2016-02-05 at 1 28 35 pm" src="https://cloud.githubusercontent.com/assets/437258/12855252/63551da6-cc0c-11e5-839a-a95077420e46.png">
