### ISSUE TITLE
Slideshow block: uncaught type-error

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30876]
A console error when moving Delay between transitions slider too quickly from the one end to another (Block sidebar):

> Uncaught TypeError: Cannot read property 'querySelector' of undefined at swiperResize (swiper-resize.js:7)    at eval (slideshow.js:67)

No visible issues caused by that.

via p1HpG7-6i7-p2 #comment-30448

cc @jeffersonrabb @ockham  @brbrr

**Comment by codebykat** [comment]
I am getting a slightly different error (OSX/Firefox):

```
TypeError: e.el is undefined
    	c wp-content/mu-plugins/jetpack/_inc/blocks-staging/editor-beta.js?m=1552055928h&ver=wpcom:12
pendingRequestAnimationFrame /wp-content/mu-plugins/jetpack/_inc/blocks-staging/editor-beta.js?m=1552055928h&ver=wpcom:47 
```
