### ISSUE TITLE
Gutenlypso: Adding options to choose programming language in Code Block

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#30899]
(I'm referring to SyntaxHighlighterCode Block that available in /wp-admin dashboard)

#### What I expected
1. Add Code block
2. Choose the programming language I'm going to use
3. Type the code

#### What happened instead
Code Block only provides the block and no option to choose the programming language.

It would be nice to have preferences in what kind of programming language we are going to use in the Code Block; just like in SyntaxHighlighterCode Block.

**Comment by arunsathiya** [comment]
@retnonindya 👋 That's a great suggestion, but I am afraid it's not something for WordPress.com to implement. 

The SyntaxHighlighter feature available on WordPress.com is specific to WordPress.com, and is basically one ported from a third-party plugin - [check documents](https://en.support.wordpress.com/code/posting-source-code/). If you personally feel that the `Code` block could have an option to show the code by language, you can voice your thoughts here for the community to think about it - https://github.com/WordPress/Gutenberg/issues 

That's something for core Gutenberg to implement first, and if that happens, WordPress.com will be porting to here. I am closing this as a non-issue, but if I misread something, please feel free to reopen and tag me.

**Comment by arunsathiya** [comment]
But, in the meantime, there is an active issue at https://github.com/Automattic/wp-calypso/issues/29641 to bring this SyntaxHighlighter block from wp-admin to Gutenlypso, as you are already aware. :)

**Comment by retnonindya** [comment]
Thank you so much, Arun! 

Discussed this issue here: p1550650023063100-slack-gutengroup-wpcomhappy
