### ISSUE TITLE
WordAds Block: Update Material icon to Outline style

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/wp-calypso#30898]
Currently the block is using the filled version of the icon

<img width="257" alt="screenshot 2019-02-20 at 07 23 05" src="https://user-images.githubusercontent.com/177929/53073600-6434a080-34e0-11e9-83ec-ddcd503c4f1a.png">

But we should be using the outline version instead.

<img width="94" alt="screenshot 2019-02-20 at 07 24 59" src="https://user-images.githubusercontent.com/177929/53073691-a78f0f00-34e0-11e9-9a98-5ce5bc461f8b.png">

https://material.io/tools/icons/static/icons/outline-announcement-24px.svg

**Comment by sirreal** [comment]
Should we change the icon in the inserter as well, or only inside the block?

![screen shot 2019-02-20 at 09 45 05](https://user-images.githubusercontent.com/841763/53078342-440edc80-34f4-11e9-9e9f-826a3f7f4077.png)

**Comment by thomasguillot** [comment]
@sirreal Oh yeah sorry, I meant to change the icon everywhere 😊
