### ISSUE TITLE
Calypsoify: No Permission to Access "Manage Plugins"  on wpcom simple sites

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#30925]
Calypsoify's (at least I think it's called that? assuming from @gwwar's description in #30799) "Manage Plugins" tabs feels odd and leads to a broken link. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ (your site)
2. Click Feedback
3. Click the "Manage Plugins" tab in the new screen it brings

#### What I expected

I don't think that "Manage Plugins" should be there, at least not for WPcom sites with a plan lower than Business. In my opinion, it looks to be missing a top margin, it's a bit pointless since there's already two other Plugin options in the sidebar, and I can't manage plugins even if I wanted to. 

But in order to not be broken per-say, it should probably prompt me to upgrade to the Business Plan. 

![jhgffghjfjhg](https://user-images.githubusercontent.com/43215253/53154681-3a987980-35b3-11e9-8ef5-78b26e48f065.png)

#### What happened instead

Error, even though I own the site. 

![hgdfdghfdghfdhfg](https://user-images.githubusercontent.com/43215253/53154697-43894b00-35b3-11e9-9a6f-df29ffbd37a9.png)

#### Context / Source

I was managing Feedback and the new styles looked fancy so I clicked around. :smile:

**Comment by jeherve** [comment]
> should this probably be opened over in [Automattic/jetpack](https://github.com/Automattic/jetpack/issues)?

This is most likely specific to the version of Calypsoify in use on WordPress.com though. The version installed on Jetpack sites is quite different. @Automattic/lannister Do you think you could take a look at this?

Thank you!

**Comment by gwwar** [comment]
We can take a look 👍 Thanks for the report @torres126 !

**Comment by gwwar** [comment]
Short-Term fixes for simple sites:
- Top Nav should say Feedback
- Remove the offending link

cc @mmtr any interest in a quick fix here?

We can align this a bit more for Simple Sites once we spin up this related sidebar project and can do a more complete audit. p58i-6Ts-p2

cc @apeatling if you had any thoughts

**Comment by kwight** [comment]
Patch for review in D24873-code.

**Comment by kwight** [comment]
Fixed, plus more cleanup in D24873-code. Thanks @torres126 !

<img width="827" alt="screen shot 2019-02-26 at 11 08 50 am" src="https://user-images.githubusercontent.com/349751/53770437-e08d9300-3e93-11e9-962f-adafd496fc9a.png">
