### ISSUE TITLE
Reader: Navigating to a tag page directly results in 500 error

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#30929]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. In the Reader Tags section, select "Add" to add a new tag.
3. Enter "wordpress" and confirm that the WordPress tag page loads.
4. Copy the tag page URL https://wordpress.com/tag/wordpress and paste it in your browser address bar to visit it directly.

#### What I expected

I expect the tag page to load when I visit the tag page URL directly: https://wordpress.com/tag/wordpress

#### What happened instead

I see the error "We're sorry, but an unexpected error has occurred" and the network console shows a 500 response for that page.

#### Browser / OS version

Chrome 72.0.3626.109 / macOS 10.14.2

#### Screenshot / Video

![screenshot 2019-02-21 10 45 18](https://user-images.githubusercontent.com/8658164/53163358-cca97d80-35c5-11e9-8cc1-e6f0bdedd728.png)

#### Context / Source

I suspect this has the same underlying cause as this issue in the desktop app, where exiting the app on a tag page results in getting stuck on a logged-out view when you reopen it: https://github.com/Automattic/wp-desktop/issues/400

#manual-testing

**Comment by blowery** [comment]
I can repro easily in production, so far cannot repro in local dev. Working on it.

**Comment by bluefuton** [comment]
Just noting that this was caused by a regression introduced in #30157.

Thanks for fixing this @blowery and @jsnajdr 🙂
