### ISSUE TITLE
Jetpack Connect: Hide the masterbar

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#30956]
As @keoshi sugested in https://github.com/Automattic/wp-calypso/pull/30699#issuecomment-466391274 for removing distractions, we could consider hiding the masterbar on all of the Jetpack Connect flows.

Let's discuss that, and make sure to consider any cases where we'd want to NOT hide it.

**Comment by tyxla** [comment]
cc @Automattic/jetpack-design @johnHackworth @AnnaMag

**Comment by tyxla** [comment]
I've started #30958 that removes the masterbar, so we can see how it looks/works and consider if it makes sense, and what we could improve.

**Comment by johnHackworth** [comment]
I'm ok with removing it, but if we do it we should do it for every case and not branch the flow. We are fragmented enough :)

@keoshi ^

**Comment by keoshi** [comment]
@johnHackworth I agree — the masterbar should be removed in the Jetpack flow where it constitutes a distraction or an abandonment option.

**Comment by tyxla** [comment]
Okay, that's how #30958 does it - removing it anywhere in the jetpack-connect section. It's still in progress - I'd like to polish the way we're doing it, but it's already ready for testing.
