### ISSUE TITLE
Media Modal: No Results In Free Photo Library

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/wp-calypso#30968]
#### Steps to reproduce
1. Create a post or page.
2. Add Gallery block.
3. Click `Media Library`
4. Click icon in upper left corner and choose `Free photo library`
5. Search for any common phrase. (I tried "Mountains," "Sky," "Sports," "Europe")

#### What I expected
To receive a number of photo results.

#### What happened instead
No results, with the message `No images match your search for _Europe_`

#### Browser / OS version
Chome Version 72.0.3626.96 (Official Build) (64-bit)
macOS Mojave Version 10.14.3

#### Screenshot / Video
<img width="1413" alt="screen shot 2019-02-22 at 12 42 53 pm" src="https://user-images.githubusercontent.com/1477002/53260433-7c9ee980-369f-11e9-882c-f0d5667f2fc1.png">

<img width="1599" alt="screen shot 2019-02-22 at 12 00 47 pm" src="https://user-images.githubusercontent.com/1477002/53260493-9dffd580-369f-11e9-9ca7-5b1858bf0f73.png">

**Comment by torres126** [comment]
I was just about to make this report, can reproduce in both Gutenberg and the Classic Editor...very frustrating.

**Comment by torres126** [comment]
Same report: #30967

**Comment by aamills** [comment]
Closing in favor of #30967 to streamline.
