### ISSUE TITLE
Jetpack Connect: Add a description to site topic step

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#30982]
In #30731 we wanted to add a description to the site topic step, but it got a bit repetitive and redundant in the context where a similar title exists, so we ended up landing the step without a description.

Some previous ideas by @keoshi:

> This is the only step that doesn't have a description. Should we introduce one and say something along these lines “What topic or category does your site cover?” ?

And some by @michelleweber:

> I'm thinking "What is your site about?"/"What will your site be about?" or "Tell us what your site is/will be about." I like @keoshi 's suggestions, but would like to so a bit less formal-sounding, if that works for y'all.

Here's how the step looks currently:

![](https://cldup.com/EdMPE_KYyI.png)

Let's decide on what to use and add it there.

**Comment by keoshi** [comment]
Another suggestion from Michelle came in on https://github.com/Automattic/wp-calypso/pull/30731#issuecomment-466971738 for the description. So we'd have something like this:

> **Tell us what your site is about**
> Do you have a particular focus? Enter a few keywords.

@jeffgolenski @joanrho what are your thoughts on this?

**Comment by tyxla** [comment]
My $0.02 - "a few keywords" can be a bit incorrect and might mislead the user into inputting several verticals - I think we expect a single vertical here?

**Comment by michelleweber** [comment]
If only one term is accepted here, then "Enter a keyword and we'll start tailoring a site for you."

**Comment by tyxla** [comment]
I really like that 👍

**Comment by tyxla** [comment]
And here's a PR for that change: #31010 

Thank you @michelleweber!
