### ISSUE TITLE
Reader: Keyboard Shortcut for "Visit Site"

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#30988]
#### Steps to reproduce
1. Starting at URL: WordPress.com/reader
2. Use `j` or `k` to navigate the list.
3. Type `v`.

#### What I expected
The URL for currently highlighted Reader item will be opened in a new tab/window.

#### What happened instead
Nothing.

#### Browser / OS version
Chrome / Mojave

#### Context / Source
#dogfooding
We have the ability to use the `enter` or `return` key to open the item within Reader, but coming from my experience with Google Reader and other RSS readers like FeedBin, the `v` key is commonly used to open the selected item within a new window or tab.

**Comment by joehdodd** [comment]
I'd like to take this, but I can't seem to find where the keyboard control/shortcut logic is located for the reader components.

**Comment by richardeschloss** [comment]
This is a pretty nifty nodejs module: https://www.npmjs.com/package/hotkeys-js. Let me know if that helps.

**Comment by richardeschloss** [comment]
I believe the hotkey code needs to be added to: /client/components/infinite-list/index.jsx. If the hotkeys.js module is used, then it would be something like:

```
const readerHotKeys = { // Find better home for this
  'j': // scrollDown
  'k': // scrollUp
  'v': // openDoc
  //...
}
hotkeys(Object.keys(readerHotKeys).join(','), function(event,handler) { // in the infinite list
  readerHotKeys[handler.key]();
}
```

**Comment by richardeschloss** [comment]
Oh, I misread...I just tested... 'j' and 'k' already do the scrolling. You want the 'v' key to open the post.

**Comment by richardeschloss** [comment]
@joehdodd , here's the keyboard shortcut code: 
https://github.com/Automattic/wp-calypso/blob/master/client/lib/keyboard-shortcuts/key-bindings.js#L8

So it appears that the change mainly needs to be made to lines 25 - 29.

**Comment by richardeschloss** [comment]
I just tested this code locally and it works.
https://github.com/Automattic/wp-calypso/blob/master/client/lib/keyboard-shortcuts/key-bindings.js#L8
```
{
			eventName: 'open-selection',
			keys: [ 'enter', 'v' ],
			description: {
				keys: [ 'enter', 'v' ],
				text: translate( 'Open selection' ),
			},
		},
```
I am still new to the project, and I'm still in the process of following the "contributing" docs. It may be faster for someone who has the dev environment all set up.

**Comment by joehdodd** [comment]
Thanks Richard! I was just spinning the codebase up and opening that file to make those changes. I'll make the changes and test and then open a PR. Thanks for pointing me in the right direction!

**Comment by mdrockwell** [comment]
I just realized I hadn't circled back to this yet — it looks like what was implemented wasn't exactly what I had in mind.

I was looking for the "v" key to mimic the "Visit" link that appears under each item in Reader. So when you hit the "v" key with an item highlighted, it would open up the site itself in a new tab. Instead, the "v" key now functions as the "enter" or "return" key does — opening the item inline within Reader.

Anyway we can change the functionality of the "v" shortcut so it will open the post itself in a new tab instead?

**Comment by joehdodd** [comment]
Ah, okay! Sorry about that! Now I see what you mean. So I'm looking at line 178 of `client/reader/stream/index.jsx` where it calls `showSelectedPost`, which in turn calls `showFullPost`, which just shows and looks like it adds to the history stack, opening the post in the same tab. 

In that case, where's the best place to make the refactor? We could change `showFullPost` to get the post data and use `window.open()`? Thanks!

**Comment by BigFerb** [comment]
I'm browsing "good first issues" and this one appears to be resolved.  Is that correct?  Thanks.

**Comment by mdrockwell** [comment]
@BigFerb What was implemented wasn't exactly what I had in mind. Currently the "v" key has the same functionality as "enter" when an item is highlighted in Reader. The request was for the "v" to mimic the functionality of the "Visit" link, which opens the items URL in a new browser window or tab.

![Visit link in Reader](https://d.pr/free/i/z8upMt+)

(Image link: https://d.pr/free/i/z8upMt )

**Comment by BigFerb** [comment]
I tried "v" in my Linux/Chromium setup and it opened the site on a new tab.  Maybe it's specific to a different browser (not Chrome/Chromium).

Ah!  Just tried it in Firefox and it does exactly what you describe.  Thanks!
