### ISSUE TITLE
Jetpack Connect: Remove any banners displayed during the flow.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#30980]
#### Steps to reproduce
While testing https://github.com/Automattic/wp-calypso/pull/30731 a banner popped up:
<img width="1224" alt="screenshot 2019-02-25 at 09 11 59" src="https://user-images.githubusercontent.com/13561163/53329846-58d0e300-38ed-11e9-9c25-d2d74d316f14.png">

Let's make sure we do not include those for the NUX+connection flows.

**Comment by tyxla** [comment]
Removing all the JITM banners on Jetpack Connect makes sense to me, but I want to make sure we've confirmed with all concerned sides, and that removing them won't break something done intentionally.

I made a quick audit of the existing JITMs and noticed that there are several that are specifically targeted to be displayed in our Jetpack Connect flow. Anyway, all of them are for coupons, which might actually be helping engage potential customers. Are we sure we want to remove them?

cc @jessefriedman @Automattic/jetpack-design @johnHackworth for awareness.

**Comment by keoshi** [comment]
I think we want to remove them, because any distractions during this flow might limit its potential. Fortunately, this particular JITM does not require a redirect to some other page, but I'd say it's not very well integrated.

We shouldn't be expecting users to copy/paste the coupon code and instead could add this 20% indication right on the plans tables and carry that over to the checkout page with a nice celebratory message “You just got 20% off your Premium plan!”.

This would certainly require more code and logic, but it makes for a much seamless experience.

**Comment by jessefriedman** [comment]
@tyxla @keoshi just to be clear all of the the JITMs you found are showing after the connection is complete, but during any post connection onboarding steps? Correct?

I agree that we should not be distracting users from these key steps. However I'd be sure that removing them from the screenshot steps above doesn't end up removing them, from say when they are done and arrive at the admin. @bubel can you comment on this?

**Comment by bubel** [comment]
The JITM in the screenshot should only appear on the plan selection page (and yes, it should appear there, as it's a notice about a promotion that allows our customers to save some money on a new plan), so our goal should be to remove it from any previous steps. I agree that it should not appear at any other point than the plan selection.

**Comment by keoshi** [comment]
> the JITMs you found are showing after the connection is complete, but during any post connection onboarding steps? Correct?

Exactly — the JITM in the screenshot above is being displayed on all post-connection views up until the plan selection step.

> I agree that it should not appear at any other point than the plan selection.

Great! Until we can integrate this into the plans tables somehow, that sounds like a solid solution. Thanks, @jessefriedman @bubel !

Let's then remove these JITMs from all onboarding steps that are not the plan selection:

- Site type selection.
- Site vertical selection.

**Comment by tyxla** [comment]
Thank you @jessefriedman and @bubel!

> Let's then remove these JITMs from all onboarding steps that are not the plan selection:

PR coming up.

**Comment by tyxla** [comment]
Here's a PR to disable JITMs for the site type and site topic steps: #31024
