### ISSUE TITLE
Business Hours block: Missing hours shows empty day

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#31027]
#### Steps to reproduce
1. Add a business hours block
2. Remove the start or end time from one of the days
3. Deselect the block

#### What I expected

Something to be displayed

#### What happened instead

The day is empty

#### Screenshot / Video

![screen shot 2019-02-26 at 14 57 24](https://user-images.githubusercontent.com/841763/53417906-db819d00-39d6-11e9-982d-6dd99b2cbf8a.png)
![screen shot 2019-02-26 at 14 57 14](https://user-images.githubusercontent.com/841763/53417907-db819d00-39d6-11e9-8aaa-47f15c70e52c.png)

**Comment by simison** [comment]
Good catch. Like this it seems like Monday & Tuesday are both 9am—5pm.

Should Monday be hidden or have just "open" text?

**Comment by sirreal** [comment]
> Should Monday be hidden or have just "open" text when no hours are added at all?

If no hours are provided, we show "closed". The problem is when hours are added, but both are not set.

It's unclear to me what should be done. In the edit view, it should be highlighted as invalid at least. On the frontend, "closed" might be safest.

It might be good to have design input, not sure who to ping (@thomasguillot ?).

**Comment by simison** [comment]
Would it be easiest code wise to allow undefined opening or closing hours and hide date if both hours are undefined? Would it be clear that's what's going to happen UI wise?

**Comment by roccotripaldi** [comment]
> Would it be easiest code wise to allow undefined opening or closing hours and hide date if both hours are undefined? Would it be clear that's what's going to happen UI wise?

I think we'll just mark the day as closed if it is missing any info - that's what currently happens on the front end. I'll start a quick PR today.
