### ISSUE TITLE
Refactor build tool: Extract SCSS build toolchain

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#31028]
We need to extract the SCSS build toolchain config to an individual file so we can export the build tool to NPM

https://github.com/Automattic/wp-calypso/blob/40f010e7f0d891e69464ab849822e18b4fd707ca/webpack.config.js#L251-L280

**Comment by ockham** [comment]
This commit from the spike PR might be relevant: https://github.com/Automattic/wp-calypso/pull/30772/commits/6683c7ef7ff58ad86b19e0fdaeedd70faaee7710
