### ISSUE TITLE
Jetpack Connect: update colors and styling

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#31032]
We'll be working on a new darker color scheme to customize the feel of the Jetpack onboarding flow. The goal is to make the onboarding experience and connection flow between Jetpack and WordPress.com as consistent feeling as possible.

![image](https://user-images.githubusercontent.com/390760/53424952-11755000-39dc-11e9-88b2-5a134582945a.png)

@Automattic/jetpack-design will handle implementing this on their own with assist from @Automattic/luna when needed.

See: p5XAZ9-29F-p2

**Comment by tyxla** [comment]
We've just landed #31141 which addresses this one 🎉
