### ISSUE TITLE
`upsell/concierge-session` broken flow for redirect payment types

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#31061]
#### Steps to reproduce
1. Enable config `upsell/concierge-session`
2. Set your abtest buckets to showConciergeSessionUpsell and showConciergeSessionUpsellNonGSuite
3. Checkout with redirect or pending payment type (stripe sources but likely any redirect type)

#### What I expected
After 3. you should be redirected back to the thank-you/pending page, e.g. `http://calypso.localhost:3000/checkout/thank-you/testing705633960.wordpress.com/pending/262751` 

#### What happened instead
```
return `/checkout/${ selectedSiteSlug }/add-support-session/${ receiptId }`;
```

The above code overrides the redirect url sending you to a blank screen at `http://calypso.localhost:3000/checkout/testing705633960.wordpress.com/add-support-session/262751` 

#### Browser / OS version
FF/arch

#### Context / Source
Found while testing something else and happened into the right ab test bucket. This is likely affecting production.

If a real fix can't be created quickly both disabling the feature and removing yourself from the abtest buckets resolves the issue.

This is clientside only, orders and checkout flow should still be complete and going back to wordpress.com should show everything as if the checkout completed.

#manual-testing

cc @travisw in case your abtest stats look a little wonky, CC should be fine, PayPal might be affected, not sure if PayPal comes back through the same EP and didn't test, all stripe redirect types likely are suffering this issue.

**Comment by travisw** [comment]
Great find @lsl.

I was able to reproduce this on staging.

Because it's an ab test shown only to English users hopefully that limits the number of people it's affecting - en users in those particular countries.

**Comment by travisw** [comment]
I'm not that familiar with how pending payments work and the purpose of that thank-you/pending page.
Does it seem reasonable to add another route for this upsell page for `.../add-support-session/pending/:receiptId`? that displays an alternate message?
Or does that thank-you/pending page do more than just act as an informative place to send the user?

We can also exclude users with a pending payment from the test, though I didn't see a straightforward way to do that.

**Comment by lsl** [comment]
>  Or does that thank-you/pending page do more than just act as an informative place to send the user?

It polls `/me/transactions/:orderid` (or something like that) until the order state goes successful. The page then redirects to /thank-you/complete. 

Adding a route (#31102) does seem to fix the issue can you test the abtest things still work as expected?

FYI - I think this essentially disables the nudge for redirect payment types.

That issue can probably be fixed in the [`CheckoutPending`](https://github.com/Automattic/wp-calypso/blob/382ead835e038050a3bbb73bc202a55ad6f9827e/client/my-sites/checkout/checkout-thank-you/pending.jsx#L61) component.
