### ISSUE TITLE
Jetpack Connect: Clean up site topic after the flow/before a new one

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#31072]
#### Steps to reproduce
* Go through the Jetpack Connection flow with a site with Jetpack >= 7.1.
* Finish the flow.
* Go through the Jetpack Connection flow with another site with Jetpack >= 7.1.
* Notice that the site topic remembers the previous vertical selection. It shouldn't.

#### Context / Source

Discovered by @jeffgolenski while testing the new site type/topic steps.

Context: p1HpG7-6lW-p2

**Comment by keoshi** [comment]
I could replicate this issue by attempting to connect to different sites. The value in the site topic persists from the first flow to the following one(s).

**Comment by tyxla** [comment]
#31118 should fix that one.
