### ISSUE TITLE
Tiled Gallery/Slideshow: media modal doesn't show correct image order

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#31108]
#### Steps to reproduce

1. Create a new post at URL: `/wp-admin/post-new.php`.
1. Insert a Tiled Gallery or a Slideshow by selecting a few images.
1. Confirm that your gallery/slideshow looks right.
1. Click the edit gallery button (pencil icon).
1. Reorder one image to the first spot.
1. Confirm this change by clicking the `Update gallery` button.
1. Confirm that your the image you reordered is now in the first spot. So far so good.
1. Click the edit gallery button again (pencil icon).
1. See incorrect image order on the media modal.

#### What I expected

That the images in the media modal are reordered correctly on every gallery/slideshow edit.

#### What happened instead

When you edit a gallery (tiled, slideshow, etc) and reorder images, these images aren’t presented in their correct order in the media modal if you edit more than once. Once I've refreshed the page, the order is correct though.

#### Browser / OS version

- Chrome Version 72.0.3626.109 (Official Build) (64-bit)
- macOS Mojave Version 10.14 (18A391)

#### Screenshot / Video

![gutenblock-gallery-order](https://user-images.githubusercontent.com/390760/53554565-f7508480-3b37-11e9-920f-8ec528b302d4.gif)

**Comment by simison** [comment]
Related to _"support re-ordering images by dragging"_ https://github.com/Automattic/wp-calypso/issues/28950

**Comment by simison** [comment]
Similar one from core https://github.com/WordPress/gutenberg/issues/13648

**Comment by simison** [comment]
I've tested with latest Gutenberg `master` branch where this seems to work for all core gallery, slideshow and tiled gallery.

We'll just need to wait for WP to upgrade to latest Gutenberg.

There's a chance that this is still an issue in Calypso-Gutenberg but since this is/was a core issue, I'd rather close this here.

**Comment by keoshi** [comment]
Thank you again, @simison !!
