### ISSUE TITLE
Adding unit test for React components

### ISSUE THREAD

**Issue by jklepatch** [Automattic/wp-calypso#31104]
I dont see any unit tests for components in 
https://github.com/Automattic/wp-calypso/tree/master/client/components

Would you be interested in adding some? I would use enzyme.

**Comment by blowery** [comment]
Hi @jklepatch, sorry for the slow response. We do have unit tests for some of the components under client/components ([an example](https://github.com/Automattic/wp-calypso/tree/master/client/components/accordion/test)), but not all of them. If you'd be interested in contributing some tests, we're happy to review any PRs. Thanks!
