### ISSUE TITLE
Gallery Blocks does not appear in Home page

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#31103]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/view/wphive101.home.blog
2. Add a post, add gallery (tested with Gallery and Tiled Gallery)
3. Save

#### What I expected
Images in the gallery will appear on home page.

#### What happened instead
Only the title of the post appeared on home page.

#### Browser / OS version
Chrome

#### Screenshot / Video

https://cld.wthms.co/o3oc2x

Another Block classic gallery, Block classic gallery - both are Block Editor posts with gallery within classic block.
Block gallery - a Block Editor post with a tiled gallery
Gallery - a Classic Editor post with a gallery

#### Context / Source

Ticket: #1838496-zen

#user-report

**Comment by lancewillett** [comment]
Hi @kosiew — thank you for the bug report. My feeling is this is probably a theme display bug, not Gutenberg editor or the Calypso site management tool (the latter is what we track here in this repo).

As a quick test, I used Twenty Nineteen theme: https://wphive101.home.blog/?theme=pub/twentynineteen

And I can see the preview there:
<img width="1552" alt="Screen Shot 2019-05-31 at 14 37 19" src="https://user-images.githubusercontent.com/66797/58736188-c3dcfa80-83b1-11e9-992b-2aefdfc98ad6.png">
