### ISSUE TITLE
Slideshow: Unlocalized Accessibility Text

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/wp-calypso#31124]
The Swiper library automatically defines some screen reader messages, listed here: https://idangero.us/swiper/api/#a11y. These text elements are not currently localized. 

To localize, we would need to override these parameters whenever Swiper is initialized. The initialization occurs in both editor and view, so this would mean adding `wp-i18n` as a view-side dependency. An alternate approach would be to save all of these strings as data attributes and use these to initialize Swiper on the view side. Neither approach is terribly pretty.

**Comment by sirreal** [comment]
Some related conversation: pafL3P-kL-p2
