### ISSUE TITLE
Framework: Layout for /design

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3112]
In #2964 we removed the specific layout files for logged out users and the oauth screen. There is still a separate layout screen for /design which we should also remove, although this is more complex due to the server side rendering.

This was suggested by @drewblaisdell in #2964.

Pinging @ehg @mcsf @ockham and @seear who may be interested.

**Comment by ockham** [comment]
The main reason for `LayoutLoggedOutDesign` really is server-side rendering. `Layout`, OTOH, still has a large number of dependencies that won't work on the server-side (they were the actual reason we introduced `LayoutLoggedOutDesign` in the first place). I don't see any way to get rid of that extra layout any time soon, TBH.

**Comment by drewblaisdell** [comment]
Yeah, I looked into the changes that would be necessary to run `Layout` in a browserless environment, and they are legion. Using a separate layout component seems like a reasonable solution to this until we can use these dependencies on the server, so I'm going to close this.
