### ISSUE TITLE
Improve copy for Related Posts placeholders and remove dates

### ISSUE THREAD

**Issue by aldavigdis** [Automattic/wp-calypso#31140]
A recent call for testing lead to input about how Related Posts placeholders look in the editor.

- Change the placeholder title to something like *Preview not available: no posts with similar content found*
- Remove date from Related Posts placeholders

I suggest doing this as a part of the still-unmerged #31023 in order to prevent merge conflicts and regressions.

**Comment by simison** [comment]
See https://github.com/Automattic/wp-calypso/pull/31126

@jeherve was fast! 😀

**Comment by aldavigdis** [comment]
Hahaha! Closing.

**Comment by lezama** [comment]
it still not removing the dates :)

**Comment by jeherve** [comment]
Yup, sorry, I moved to address this feedback as I wanted to get this done during the Beta period.

> it is still not removing the dates :)

As per my comment on the thread that triggered this issue, the date is there as a preview of the display option available for the block, so I don’t think we can really remove it.

**Comment by lezama** [comment]
Thanks Jeremy!

@aldavigdis feel free to close this one 👍 if you think there's nothing else we can do here.

**Comment by scruffian** [comment]
Closing this as it seems like there's nothing else we can do. Feel free to reopen if you have an idea.
