### ISSUE TITLE
Gutenberg: Instagram block not embedding content on Simple Sites

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#31155]
#### Steps to reproduce
1. Site Pages/Blog Posts > Add
2. Add an Instagram block to the post or page
3. Put the URL of a public Instagram image into the block

#### What I expected
Block would embed the Instagram post into my page/post

#### What happened instead
An error appears showing that the content couldn't be embedded -- using the URL in a Classic block *does* embed the content correctly, though!

#### Browser / OS version
Firefox 65.0.1/Chrome 72.0.3626.119, macOS 10.14.13

This is only occurring for me on Simple Sites; AT sites aren't having the same trouble

#### Screenshot / Video
![Instagram Block Borked](https://cld.wthms.co/sy9tVx+)

#### Context / Source
Reported by user in #6602196-hc / #1844565-zen

**Comment by Agepeuve** [comment]
Reported in #1840385-zen

**Comment by eoinsav** [comment]
Another report here: #10955574-hc

**Comment by vindl** [comment]
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/28314. It has been resolved after we switched to Gutenframe.
