### ISSUE TITLE
Allow hiding of Masterbar within the mobile apps

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#31157]
#### Steps to reproduce
1. Use the mobile app and navigate to "My Sites"
2. Select a site and scroll down to "View My Site"
3. It should show you your site

#### What I expected
My website without the masterbar at the top

#### What happened instead
The masterbar is shown

#### Browser / OS version
WordPress iOS and Android app

#### Screenshot / Video
![img_7487](https://user-images.githubusercontent.com/1158819/53674983-e6daff80-3c46-11e9-8c66-6ba07b6e547e.png)

#### Context / Source

We don't want the user navigating within the website while browsing through the app.

#dogfooding

**Comment by mmtr** [comment]
Proposed fix on D26162-code and https://github.com/Automattic/jetpack/pull/11758
