### ISSUE TITLE
Tax country code and postal code set as null after failed payment attempt

### ISSUE THREAD

**Issue by prettyboymp** [Automattic/wp-calypso#31151]
#### Steps to reproduce
1. Add an item to the cart
2. Fill in invalid payment details, including re/setting the country and postal code
3. Submit the payment
4. Change some payment details, but don't touch the country/postal code fields
5. Resubmit the payment

#### What I expected
The tax region data to be filled in as it was before

#### What happened instead
Both of these fields are sent as null

**Comment by lsl** [comment]
To test in #30981
