### ISSUE TITLE
Tax country_code is initially null

### ISSUE THREAD

**Issue by prettyboymp** [Automattic/wp-calypso#31150]
#### Steps to reproduce
1. Add a plan to your cart, which immediately redirects you to the checkout screen
2. Country is already selected to a default value, US for me.
3. The post requests to update the cart have `null` filled in for the `tax.location.country_code` until I manipulate the dropdown list.

#### What I expected
All cart requests to have a value for the country code, even if it's still set as the default value.

#### What happened instead
Defaults to null until the dropdown is changed for the first time.

**Comment by prettyboymp** [comment]
Thinking about this more, we need to change some behavior here.

The problem I'm finding is that there is nowhere the cart is validated in our checkout flow within Calypso making it unclear when errors about the tax location should be returned with the cart.  I think to deal with this we need to change the request data.  Here's what I'm thinking:

* If the location data (country and postal code) isn't filled in yet, `tax.location` shouldn't be set when sending the cart to the save-cart endpoint.
* If `tax.location` is set, that data will be validated on the server to make sure the postal code is valid for the country and any errors will be returned with the cart as normal errors are returned.
* If we don't have a returned saved cart with `tax.location` filled in, we shouldn't allow the `Pay` button to be clicked.
* The checkout API endpoint will return an error(s) if the cart is missing or has invalid `tax.location` data.

**Comment by lsl** [comment]
To test in #30981 (suspect will fix default values)

Not sure I agree with the validation approach seems to conflate concerns. I especially dislike only validating something if it is present. Makes for a confusing endpoint spec.

I think having the cart validate and return errors along with itself and allowing calypso to ignore or not is the best we'll get without creating a separate endpoint (not opposed to that, probably cleaner and doesn't mess with the cart-sync stuff)

I'm also open to leaving the validation situation as is. Obviously the defaulting still needs fixing.

**Comment by deBhal** [comment]
@prettyboymp, @lsl: #30981 Does add an update on mount to fix this problem (https://github.com/Automattic/wp-calypso/pull/30981/files#diff-e6fb36464cc3c32f6d63bf505728326cR59) but I like the discussion on validation

> If the location data (country and postal code) isn't filled in yet, tax.location shouldn't be set when sending the cart to the save-cart endpoint.
> If we don't have a returned saved cart with tax.location filled in, we shouldn't allow the Pay button to be clicked.

We currently do client-side validation when you hit the "Pay" button, at which point the whole form is validated before that request is sent. Both country code and postal code are validated and required, and US postcodes must be a a 5-digit number, so for actual payments calypso should never send invalid values, only for cart updates.

I'm not familiar off-hand, but I believe it's similar on the backend - I think we validate everything on payment, just not on cart updates.

> If tax.location is set, that data will be validated on the server to make sure the postal code is valid for the country and any errors will be returned with the cart as normal errors are returned.

> unclear when errors about the tax location should be returned with the cart.

I'd be inclined to say "always", and leave it to the client to decide what to do with them. In this case, I think we'd get good bang for our buck by having any error trigger the client-side validation.

**Comment by lsl** [comment]
I believe only the initial problem was solved in #30981.

The validation problems this will be addressed with #31342, D25368-code (depends D25367-code)

Specifically, D25368-code will introduce the invalid postcode messages which will only be returned if there is an invalid postcode / country pair present in the cart.

**Comment by lsl** [comment]
Breaking this down to make sure I covered everything:

> If the location data (country and postal code) isn't filled in yet, `tax.location` shouldn't be set when sending the cart to the save-cart endpoint.

All page loads involve at least one GET and one POST to the cart endpoint. The POST should always send `tax_country_code` and `tax_postal_code` (prev `tax.location`) as a **parameter**. If there are any defaults that should be set they should come from the original GET. I think GEOIP works as a default here if you like?

> If tax.location is set, that data will be validated on the server to make sure the postal code is valid for the country and any errors will be returned with the cart as normal errors are returned.

See D25368-code

> If we don't have a returned saved cart with tax.location filled in, we shouldn't allow the Pay button to be clicked.
Once errors are returned in the cart state we can add a validator that checks this cart state for any errors. We could also move this validation to the client relatively easily. (Depending on the legal requirements with that)

> The checkout API endpoint will return an error(s) if the cart is missing or has invalid tax.location data.
Not yet addressed.

**Comment by lsl** [comment]
@prettyboymp fixed a lot of these concerns in D25366-code and D25401-code

I think the only outstanding problem now is threading the validation / errors back to calypso. 

Closing this, we can track validation in #31379.
