### ISSUE TITLE
Hide (action bar) follow bar within the mobile apps

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#31159]
#### Steps to reproduce
1. Go to the Discover section within Reader 
2. Select a post from a site that you don't follow
3. Tap the ellipsis on the top right and select "Visit"
3. Scroll down to the bottom and see the "Follow" bar there.

#### What I expected
The website without the follow overlay

#### What happened instead
The website with the follow overlay

#### Browser / OS version
WordPress iOS and Android app

#### Screenshot / Video
![img_7490](https://user-images.githubusercontent.com/1158819/53675127-51d90600-3c48-11e9-9bf0-d6ecd6994e32.png)

#### Context / Source

We don't want users to have any actions within the webview that they can do within the app

#dogfooding

**Comment by mmtr** [comment]
Proposed fix on D26160-code.

**Comment by mmtr** [comment]
Closed by D26160-code.
