### ISSUE TITLE
Using Edit image to change caption removes formatting

### ISSUE THREAD

**Issue by rezzap** [Automattic/wp-calypso#31164]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/
2. Create a new post/page, insert an image from the gallery and use the toolbar to align it center and resize using the corner drag.
3. Add a caption to the image.
4. Publish post and visit. See the image respects formatting.
5. Re-open the post to edit and click on the image to open the toolbar.
6. From the 'edit' menu, edit the caption text and update. 
7. In the editor the align and size have reset in both post preview and publish.

#### What I expected
I expected that when editing the image caption from the 'edit image menu', previous changes to formatting would be respected and kept. 

#### What happened instead
When I edited the caption, the image formatting was reset. 

#### Browser / OS version
Chrome Version 72.0.3626.96 (Official Build) (64-bit) MacOS Mojave Version 10.14.3

#### Screenshot / Video
![screen recording 2019-03-02 at 07 36 am](https://user-images.githubusercontent.com/10325627/53678969-2bee4880-3cbe-11e9-8444-d4e189519c9c.gif)

#### Context / Source

User reported in 1840627-zen
Site: https://grumpyhiker.com/temptest/

**Comment by gwensmithx** [comment]
Hi there, just checking in on this. It appears we don't have a fix yet? I'm monitoring a ticket in ZD so when we have a fix I would like to update the customer.

**Comment by gwensmithx** [comment]
Hi all, I'm just following up on my GH issues list of tickets and it looks like this is not an issue anymore. I've tested this out again on the user's website and the caption is now updating when following the steps above. ZD 1840627.
