### ISSUE TITLE
Site Importer: Misleading Back Button

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#31169]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import
2. Select an importer
3. Click the "Back" button 
4. Be directed to site settings 
5. Click the Import button on the sidebar again 

You need to click the "Cancel" button to actually go back, which is a bit misleading. 

#### What I expected

Be redirected to the screen to select an importer 

#### What happened instead

Redirected to site settings, which isn't going "Back" because I was never on that page. 

#### Context 

Found when looking at #31168

**Comment by drw158** [comment]
Good find. This is because the the primary location of Import is in Settings. The item in the sidebar is sort of a "shortcut". 

We might be able make an exception for the navigation for ppl visiting Import via the sidebar menu.

**Comment by dezzie** [comment]
I ran a usability test with a participant using one of the importers, and found that the new sidebar makes this issue worse when the user starts from signup:

**Steps to reproduce**

    1. Starting at URL: https://wordpress.com/start/import
    2. Enter URL, go through signup
    3. Import flow continues in Calypso (the sidebar is fully collapsed)
    4. Click the "back" button
    5. Be directed to /settings/general/ (only the Manage section of the sidebar is expanded)
 
While you can still find the Import section through Manage>Settings>General, the better place is Tools>Import

As long as that "Back" nav item is there, it implies that the user is going to go to a previous step in the flow.

**Comment by dezzie** [comment]
Any thoughts on this?

**Comment by mattsherman** [comment]
I agree that moving it out of Settings and having import and export under Tools seems more discoverable. I would probably lean towards having separate "Import" and "Export" items under Tools in the sidebar, but I don't feel strongly either way.

**Comment by dezzie** [comment]
I'm recommending that we go with this then:

**Goal**
To avoid navigation confusion for users completing an import. We are not telling these new users where in the product they are working. If they leave the import flow, the sidebar is not indicating where they are going, and they end up lost.

**Changes needed**
1. **Remove Import and Export** sections out of **Manage>Settings>General** in the new sidebar.
2. **Add Export** section to **Tools>** in the new sidebar.
3. **Remove the cake nav** from Import and Export sections that is no longer needed.
4. When users come to the Import section from signup, the Tools section in the new sidebar is expanded to indicate which subsection they are in.

--- DETAILED DESIGNS BELOW ---

1. Move Import and Export sections out of Manage>Settings>General in the new sidebar:
<img width="1440" alt="o Import and Export" src="https://user-images.githubusercontent.com/1301932/57885178-fbfc0f00-77ef-11e9-98cc-802cc7ca7abe.png">

2. Add Export to Tools> in the new sidebar:
<img width="1440" alt="1440 - Tools _ Export" src="https://user-images.githubusercontent.com/1301932/57885212-11713900-77f0-11e9-81ae-117fb00373d6.png">

3. Remove the cake nav from Import and Export sections that is no longer needed:
<img width="1440" alt="Sidebar Expanded" src="https://user-images.githubusercontent.com/1301932/57885300-42ea0480-77f0-11e9-9ba1-6bb3ab20e5f3.png">

4. When users come to the Import section from signup, the Tools section in the new sidebar is expanded to indicate which subsection they are in.
<img width="1440" alt="Email verify" src="https://user-images.githubusercontent.com/1301932/57885343-59905b80-77f0-11e9-8a98-9e53cb927d4c.png">

**Comment by torres126** [comment]
Fixed by #33181
