### ISSUE TITLE
Hide all overlays from within the mobile app

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#31161]
There are a few elements we want to hide within the mobile view:

1. [Masterbar](
https://github.com/Automattic/wp-calypso/issues/31157)
2. [Cookie warnings](
https://github.com/Automattic/wp-calypso/issues/31158)
3. [Action bar (follow bar)](
https://github.com/Automattic/wp-calypso/issues/31159)
4. [App banners](
https://github.com/Automattic/wp-calypso/issues/31160)

The approach we want to take is not set in stone yet, and there are a few varying ways we already do accomplish some of this ([1](
https://github.com/Automattic/calypso-pre-oss/issues/11127)) ([2](
https://github.com/Automattic/wp-calypso/issues/3353))

We'll want to consolidate this logic into a single option so there aren't multiple flags we have to keep track of.

**Comment by obenland** [comment]
@kwonye @elibud Do you think we could insert a common identifier in the user agent in both apps that we could test for?

**Comment by diegoreymendez** [comment]
@obenland - This is the default user agent for a mobile web view:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B91
```

And this is the one we're using in WPiOS:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B91 wp-iphone/12.1
```

I'll add the Android user agents as soon as I know them.

**Comment by obenland** [comment]
> This is the default user agent for a mobile web view in iOS

Just for my understanding, this iOS Safari and we wouldn't have to test for that?

**Comment by diegoreymendez** [comment]
I provided the default one for context only, so spotting the custom part is easier.

The part that allows you to check for WPiOS is `wp-mobile/12.1`.

**Comment by diegoreymendez** [comment]
Right now WP Android is launching the through an external browser when pressing the "View site" option of the mobile dashboard (instead of opening a web view as in iOS).

That'll need to change in the Android side.  I'll push that.

That said, @obenland... I believe the custom user agent part used above (`wp-mobile/12.1`) should work for Android too.

**Comment by obenland** [comment]
Perfect, I'll check for that then, thanks! I assume 12.1 is the iOS version number?

**Comment by obenland** [comment]
Oh, one more question, in the user agent string you pasted it says `wp-iphone`, not `wp-mobile`. I assume we should check for both?

**Comment by diegoreymendez** [comment]
> Perfect, I'll check for that then, thanks! I assume 12.1 is the iOS version number?

Yes.

> Oh, one more question, in the user agent string you pasted it says wp-iphone, not wp-mobile. I assume we should check for both?

Actually that was a typo on my end, sorry about that.  Let's stick with just `wp-iphone/12.1` for now.

Once it's up I'll do the testing in iOS to see how that goes, since Android will probably require some work on my end.

Can we leave the option open to add another identifier for Android?

**Comment by mmtr** [comment]
Seems we're using [`wp-iphone` for the iOS app](https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Classes/Utility/WPUserAgent.m#L33-L43) and [`wp-android` for the Android](https://github.com/wordpress-mobile/WordPress-Android/blob/e70a3373f8df4023b9ebf40c89f1fe7a538f97b6/WordPress/src/main/java/org/wordpress/android/WordPress.java#L628-L651).
