### ISSUE TITLE
Plans Endpoint - "shortdesc" and "description" fields seem inconsistent

### ISSUE THREAD

**Issue by daniloercoli** [Automattic/wp-calypso#3116]
It seems that  "shortdesc" and "description" are often inverted in the response of `Plans` endpoint.
https://public-api.wordpress.com/rest/v1/plans/?locale=it-IT&pretty=true

See the snippet of the response below:
```
    {
        "product_id": 2002,
        "product_name": "Free",
        "product_name_en": "Free",
         ......
        "product_name_short": "Free",
        "product_slug": "jetpack_free",
        "tagline": "Get started",
        "shortdesc": "Jetpack (free) speeds up your site's images, secures it, and enables traffic and customization tools.",
        "description": "Spam Protection",
        "cost": 0,
        "bill_period": -1,
        ......
    },
```

`shortdesc` is longer than `description`?!

**Comment by gziolo** [comment]
`description` can be removed from REST API response. Only `shortdesc` is used in our code. I think the best solution would be to put `shortdesc` content as `description` and bump API version.
