### ISSUE TITLE
Site settings: Deleting a site: Hide delete button

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3117]
In Calypso, users who want to delete their site first have to visit /settings/general/:site. We don't show the delete site link until we have loaded the user's purchases. If the user has purchases then when they click this link they see a modal which prevents them from navigating to the delete site section until they have deleted their active purchases.

In WordPress.com, wp-admin users now get redirected to Calypso to delete their site, irrespective of whether they have active purchases. This means users can get to the delete site page while having active purchases on their site. Currently we show the user an error message after they try to delete their site while it has active purchases.

Ideally we should <a href="https://github.com/Automattic/wp-calypso/issues/2300">let them cancel their purchases and delete the site at the same time</a>. However as an interim solution we can check whether the user has any active purchases and in this case show them a message saying that they need to remove these purchases, and hide/disable the delete site button until the purchases have been removed.

See #3076 for context.

**Comment by fabianapsimoes** [comment]
cc @mikeshelton1503 since we'd some design input for copy and layout.

**Comment by breezyskies** [comment]
The design and copy for the simple version of this is on our list for next week.

**Comment by breezyskies** [comment]
Rather than adding any new copy / design, can we check for purchases and redirect here:

![screen shot 2016-02-15 at 12 57 09 pm](https://cloud.githubusercontent.com/assets/3011211/13060103/d80586b6-d3e3-11e5-9757-63b4495f5f66.png)
