### ISSUE TITLE
VideoPress: Reusable block does not render the player

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#31178]
#### Steps to reproduce
1. Go to https://wordpress.com/block-editor/post while proxied.
2. Select a site under a Premium plan.
3. Insert a video block.
4. Upload or select an existing video.
5. Add the video block to the list of Reusable Blocks.
6. Publish the post.

#### What I expected
The published post to render the VideoPress player.

#### What happened instead
The published post displays the VideoPress URL instead of rendering the VideoPress player.

<img width="656" alt="screen shot 2019-03-04 at 11 49 10" src="https://user-images.githubusercontent.com/1233880/53728686-95fc1e80-3e73-11e9-960b-6b9643af16db.png">
<img width="563" alt="screen shot 2019-03-04 at 11 49 25" src="https://user-images.githubusercontent.com/1233880/53728687-95fc1e80-3e73-11e9-9b27-8703dceb9538.png">

**Comment by simison** [comment]
Quick "fix" would be to temporarily disable re-usable block feature for this block with `supports.reusable: false`
