### ISSUE TITLE
Business Hours Block: Is closed toggle redundant?

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#31183]
In the Business Hours block, days of the week are _closed_ when they have no valid hours. That can be expressed in two ways:

- the "closed" toggle
- having hours that aren't "valid"

| Edit | View |
| :---: | :---: |
| ![screen shot 2019-03-04 at 14 00 51](https://user-images.githubusercontent.com/841763/53735388-fcd70300-3e86-11e9-8e4c-c27c1928ef52.png) | ![screen shot 2019-03-04 at 14 00 59](https://user-images.githubusercontent.com/841763/53735390-ff395d00-3e86-11e9-96c4-bd3645b75d8a.png) |

Monday (`lunes`) is open and closed at the same time.

Is the `closed` toggle redundant UI?

cc: @roccotripaldi @thomasguillot

**Comment by scruffian** [comment]
IMO this makes sense how it is. Asking people to enter invalid dates to show that they are closed is unintuitive :)

**Comment by sirreal** [comment]
Poorly expressed as I look back at this, but my idea was that something like this would be more appropriate than a toggle: 

---

Monday **9:00 - 17:00** <kbd>❌ remove hours</kbd>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <kbd>➕ add open hours</kbd>
Tuesday **Closed** <kbd>➕ add open hours</kbd>

---

**Comment by scruffian** [comment]
I think the design we went with was replicating the one Google uses... is that right @thomasguillot ?

**Comment by thomasguillot** [comment]
@scruffian correct
