### ISSUE TITLE
Ad Block: custom alignment breaks layout

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#31185]
> When adding multiple ads to a single page and stacking ads on top of one another the second (3rd, 4th, etc) tier of ads’ alignment tools become slightly or completely hidden behind the ad above and the ability to adjust alignment and switch between ad styles becomes difficult. This seems to only happen by default and when setting the second (3rd, 4th, etc) row of ads to centered, when aligned left or right the toolbar becomes visible once again.

-- p8oabR-kb-p2 #comment-2671

<img width="773" alt="stacked-overlap-2" src="https://user-images.githubusercontent.com/426388/53737994-4b3bd000-3e8e-11e9-9a6d-d6d7b6699dbf.png">
<img width="773" alt="stacked-overlap" src="https://user-images.githubusercontent.com/426388/53737995-4b3bd000-3e8e-11e9-97f3-e106bf2d733d.png">

> Also, I would have expected the ads to display in a similar structure in preview as displayed in the editor but instead without any other content they seem to jump to various, somewhat random, locations on the page:

<img width="773" alt="preview-of-above-ad-structure" src="https://user-images.githubusercontent.com/426388/53738021-5a228280-3e8e-11e9-9f91-c8127ca73bfb.png">
<img width="773" alt="ad-structure-in-editor" src="https://user-images.githubusercontent.com/426388/53738022-5a228280-3e8e-11e9-847e-a0a3f177cb9c.png">

**Comment by brbrr** [comment]
I'm going to report my finding here, as it seems very relevant (p8oabR-kb-p2 #comment-2690)
Ads block in `Wide Skyscrapper` mode does not play well with other blocks in editor and frontend. 

In my tests, I noticed that one of the form's inner blocks get stretched in the editor view. Image block (in align center mode) on frontend get's glued together with the adds block.

<img width="300" alt="1" src="https://user-images.githubusercontent.com/5654161/53739797-59441d80-3e9b-11e9-9635-5151a1948463.png"><img width="300" alt="2" src="https://user-images.githubusercontent.com/5654161/53739798-59441d80-3e9b-11e9-9a98-3779c726897a.png">

https://jetpack6test.mystagingwebsite.com/7-1-blocks-page/
