### ISSUE TITLE
Global notices: Rounded edges in Firefox

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3119]
In Firefox, there is a weird shadow around the global notices when they have a link.

<img width="803" alt="screen shot 2016-02-05 at 17 44 20" src="https://cloud.githubusercontent.com/assets/275961/12854197/305b80f6-cc30-11e5-9425-4040a3f641c8.png">

cc @rickybanister

**Comment by rickybanister** [comment]
We haven't done any work yet to make notice actions work in the global notices. In addition to that shadow, it also looks like the vertical alignment is off.

cc @mtias
