### ISSUE TITLE
Editor: Cannot scroll inside fast preview on iOS

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#312]
Steps to reproduce:

1. Go to https://wordpress.com/post and start a new post
2. Add a title and some content
3. Tap the "Actions" button
4. Tap the "Preview" button
5. Try to scroll around to see the whole post in the fast preview screen

<strong>Result:</strong> cannot scroll or see the whole post in the fast preview.

<img alt="img_4760" width="400" src="https://cloud.githubusercontent.com/assets/1119271/11022743/a86c43b0-8634-11e5-85eb-f65b7506e241.PNG" />
<sup>Seen at https://horizon.wordpress.com/post/design5279.wordpress.com/9320 using Safari iOS 9.1 on iPhone 6</sup>

Is the preview set to the correct default when viewing on mobile? When I tap the Preview button to see a fast preview, it looks oversized (see screenshot above) and when I tap the external preview button, the preview looks normal: 

<img alt="img_4761" width="400" src="https://cloud.githubusercontent.com/assets/1119271/11022745/d3dce1da-8634-11e5-8391-1654930621e3.PNG" />
<sup>Seen at https://design5279.wordpress.com/?p=9320&preview=true&iframe=true using Safari iOS 9.1 on iPhone 6</sup>

**Comment by nylen** [comment]
Reported in 271879-chat (iOS 9.1, Safari 9) and confirmed in iOS Simulator (iPad on iOS 8.2):

![ios-cannot-scroll-preview](https://cloud.githubusercontent.com/assets/227022/11484050/a1b5efaa-9771-11e5-932b-aa13027cb62f.gif)

**Comment by aduth** [comment]
Fixed by #3376
