### ISSUE TITLE
Publish package: `lib/simple-payments`

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#31205]
Used by simple payments block here:

https://github.com/Automattic/wp-calypso/blob/241292989efa898345417b4632f6402605497895/client/gutenberg/extensions/simple-payments/edit.js#L27

Packaging docs:
https://github.com/Automattic/wp-calypso/blob/ce2493f7fcb3662d16dda09d8885620f0051728b/docs/monorepo.md#readme

After moval, test by running first `npm run distclean && npm ci` to ensure you have the new package in use.

**Comment by simison** [comment]
Is Simple payments code in classic editor going to be needed in Calypso once Gutenlypso is no more? Can we just move these files to the block folder itself:

From: [`/client/lib/simple-payments`](https://github.com/Automattic/wp-calypso/tree/ad3e86832a0cec80b1c341f82e2a14e8fef62720/client/lib/simple-payments)
To: [`client/gutenberg/extensions/simple-payments`](https://github.com/Automattic/wp-calypso/tree/241292989efa898345417b4632f6402605497895/client/gutenberg/extensions/simple-payments)

...and bring them over to Jetpack and not have them in Calypso codebase?

@Automattic/lannister thoughts?

**Comment by simison** [comment]
Used only in tinymce plugin and related data-layer bits: 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/87168/53811356-e2258c80-3f61-11e9-8bf5-08fbf47f7ce3.png">

**Comment by gwwar** [comment]
There's still the Calypso Classic editor, so in terms of ordering we'd need to update usages until we complete a full editor rollout.

**Comment by sirreal** [comment]
There is some code that would be good to share so our Simple Payments experience is consistent:

- Supported currencies
- The custom post type slug

The de facto way at this time seems to be by publishing a package.

If the classic editor (and associated Simple Payments code) has a limited future in Calypso, it would be completely viable to duplicate the code for now and let it be cleaned up from Calypso.

p1551889885726100-slack-jetpack-gutenberg

**Comment by gwwar** [comment]
@sirreal Code duplication seems reasonable here to me, let's maybe just leave a comment note that they're not connected.

**Comment by sirreal** [comment]
We can let #31199 handle this.
