### ISSUE TITLE
Publish package: `lib/route/path`

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#31209]
...or consider refactoring the usage out.

Used in:

https://github.com/Automattic/wp-calypso/blob/ad3e86832a0cec80b1c341f82e2a14e8fef62720/client/gutenberg/extensions/presets/jetpack/editor-shared/get-site-fragment.js#L9

See convo p1551792263472700-slack-jetpack-gutenberg

Packaging docs:
https://github.com/Automattic/wp-calypso/blob/ce2493f7fcb3662d16dda09d8885620f0051728b/docs/monorepo.md#readme

**Comment by sirreal** [comment]
With Gutenberg moving out of Calypso, I don't think this will continue to be a consideration.

This entire block and the dependency on `lib/route/path` can be eliminated:

https://github.com/Automattic/wp-calypso/blob/ad3e86832a0cec80b1c341f82e2a14e8fef62720/client/gutenberg/extensions/presets/jetpack/editor-shared/get-site-fragment.js#L22-L27

**Comment by sirreal** [comment]
We can let #31199 handle this.
