### ISSUE TITLE
Unread notifications have poor colour contrast

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#31208]
When opening notifications panel to see unread messages, it has poor colour contrast for unread notifications using default "Classic Bright" colour scheme.

First press bell in the header:
<img width="435" alt="screenshot 2019-03-05 at 15 40 47" src="https://user-images.githubusercontent.com/87168/53809330-206c7d00-3f5d-11e9-8ba6-4d96e75fbc0d.png">

Then see notifications:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/87168/53809001-67a63e00-3f5c-11e9-9e58-83b733b097df.png">

Same for read notifications:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/87168/53809034-7856b400-3f5c-11e9-826e-cd2cd2b0680c.png">

Here is how unread and read notifications look next to each other:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/87168/53809123-a936e900-3f5c-11e9-83ca-a097930aba66.png">

https://webaim.org/resources/contrastchecker/?fcolor=636D75&bcolor=D8DEE4

<img width="736" alt="image" src="https://user-images.githubusercontent.com/87168/53809134-b18f2400-3f5c-11e9-8922-8bc5350659f3.png">

cc @drw158 @flootr

**Comment by drw158** [comment]
We try not to put opacity on our colors but in this case, I think we should.
