### ISSUE TITLE
Bring ES Lint packages in Calypso up to date

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#31204]
New packages:
- https://github.com/Automattic/wp-calypso/tree/master/packages/eslint-config-wpcalypso
- https://github.com/Automattic/wp-calypso/tree/master/packages/eslint-plugin-wpcalypso

Old packages:
- https://github.com/Automattic/eslint-config-wpcalypso
- https://github.com/Automattic/eslint-plugin-wpcalypso

See also https://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package for how to use these packages in Jetpack repo.

@Automattic/team-calypso

**Comment by simison** [comment]
@sirreal do you have any more details about this?

**Comment by sirreal** [comment]
- Unify config + plugin packages (p1551778050051400-slack-team-calypso)
- Provide multiple configs (base, react, gutenberg, prettier??)
- Pull in changes into relevant config overrides (Calypso should a config provided by the package, no rule overrides): https://github.com/Automattic/wp-calypso/blob/241292989efa898345417b4632f6402605497895/.eslintrc.js#L5-L114

**Comment by simison** [comment]
Issue to track Prettier config: https://github.com/Automattic/jetpack/issues/11474

**Comment by simison** [comment]
Tracking Gutenberg specific lint here: https://github.com/Automattic/wp-calypso/issues/31215

**Comment by simison** [comment]
I compared packages to commits in the repos and it doesn't look like these would've been diverged:

https://github.com/Automattic/eslint-config-wpcalypso/commits/master
https://github.com/Automattic/wp-calypso/blob/master/packages/eslint-config-wpcalypso/CHANGELOG.md


https://github.com/Automattic/eslint-plugin-wpcalypso/commits/master
https://github.com/Automattic/wp-calypso/blob/master/packages/eslint-plugin-wpcalypso/CHANGELOG.md
