### ISSUE TITLE
Reader: Make the follow button more buttony?

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#3121]
I have a hunch that the current follow button isn't buttony enough and folks don't know to click it. 

Maybe we could try an A/B test with a button that's more buttony and enticing to click? As an example, here are follow buttons from some other services.

Ours
<img width="108" alt="screen shot 2016-02-05 at 12 30 46 pm" src="https://cloud.githubusercontent.com/assets/14350/12854526/2f99afee-cc08-11e5-8df1-db7fc615286d.png">

Twitter
<img width="107" alt="screen shot 2016-02-05 at 12 59 05 pm" src="https://cloud.githubusercontent.com/assets/14350/12854539/44a30732-cc08-11e5-8d73-6084d73f65f2.png">

Facebook
<img width="124" alt="screen shot 2016-02-05 at 12 59 48 pm" src="https://cloud.githubusercontent.com/assets/14350/12854564/5f85ce68-cc08-11e5-98ea-cf9f19ab3b76.png">

Feedly
<img width="86" alt="screen shot 2016-02-05 at 1 01 01 pm" src="https://cloud.githubusercontent.com/assets/14350/12854587/8da935dc-cc08-11e5-8024-4c7fb8492d7c.png">

**Comment by alternatekev** [comment]
Whatever happens here should also be pushed through to the ActionBar eventually.

**Comment by bluefuton** [comment]
cc @jancavan :)

**Comment by jancavan** [comment]
Note: this button/icon style also exists in Stats > Authors module so that needs to be updated on there as well for consistency.

![screenshot 2016-03-31 19 13 46](https://cloud.githubusercontent.com/assets/4924246/14196007/dcc53d9a-f774-11e5-81b3-39619d5a8055.png)

**Comment by jancavan** [comment]
Another area this button exists is on the ActionBar for those who don't have accounts:

![screenshot-2016-04-13-11 02 59](https://cloud.githubusercontent.com/assets/4924246/14507428/789d3f4a-0177-11e6-838f-9ee48fc034bc.jpg)

![screenshot-2016-04-13-11 03 10](https://cloud.githubusercontent.com/assets/4924246/14507431/7afcba68-0177-11e6-97dc-51094dc571e3.jpg)

**Comment by jancavan** [comment]
Update: I've created a PR to add the new Follow and Following icons to the Gridicons set: https://github.com/Automattic/gridicons/pull/152

**Comment by folletto** [comment]
The update of the icon and some color tweaks seems having addressed at least in part this issue. 

For record...

Logged in action bar:

![screen shot 2016-05-20 at 16 45 56](https://cloud.githubusercontent.com/assets/4389/15433451/5d0ce79e-1eaa-11e6-84ce-17ff78fbfa0b.png)

Logged out action bar:

![screen shot 2016-05-20 at 16 46 23](https://cloud.githubusercontent.com/assets/4389/15433469/6ac5c054-1eaa-11e6-885e-a9a727223e22.png)

Reader Recommendations:

![screen shot 2016-05-20 at 16 47 12](https://cloud.githubusercontent.com/assets/4389/15433505/8ae5cc94-1eaa-11e6-9b25-007a27b1a868.png)

Stats:

![screen shot 2016-05-20 at 16 48 32](https://cloud.githubusercontent.com/assets/4389/15433548/b5d62ed0-1eaa-11e6-8cd7-39d9d7e8c450.png)


Still not with the new icons, the notifications:

![screen shot 2016-05-20 at 16 49 13](https://cloud.githubusercontent.com/assets/4389/15433599/e7f2164a-1eaa-11e6-8bea-d66ed0bdaa59.png)
