### ISSUE TITLE
Parametrize the Build Tool: Parametrize the root dir in the postcss config.

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#31210]
Currently:

https://github.com/Automattic/wp-calypso/blob/951816610782e9ada01df88e4b9ab17fdfd9ac8e/postcss.config.js#L4

related https://github.com/Automattic/wp-calypso/issues/31214, https://github.com/Automattic/wp-calypso/issues/31213

**Comment by simison** [comment]
@sirreal or does parametrize in this context actually mean that we'd not depend `postcss.config.js` to be present in target's root folder?

https://github.com/Automattic/wp-calypso/pull/30933#pullrequestreview-210630652

**Comment by sirreal** [comment]
I updated the description to reflect current master.

> does parametrize in this context actually mean that we'd not depend

I'm not entirely sure, this seems very specific. It might mean that Calypso includes this setup, but a shared base config does not. @ockham will likely have more developed thoughts.

**Comment by sirreal** [comment]
Fixed by #31363
