### ISSUE TITLE
Tiled Gallery Block: Galleries not displaying properly in IE11 on simple sites

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#31224]
It appears the Tiled Gallery block is broken on WPCOM simple sites when viewed in IE11. The images are displayed full-sized without organization.   I've reproduced it on multiple Simple WPCOM sites across multiple themes.

Cannot reproduce on AT or self-hosted.

#### Steps to reproduce
1. Add a Tiled Gallery block to a post/page on a WPCOM simple site.
2. Publish and view page/post directly on IE11
3. Review that the gallery's images are full-sized and not displaying correctly.

#### What I expected
A tiled gallery to be displayed properly as seen here: https://cld.wthms.co/G3axFC

#### What happened instead
Images are displayed full-sized with no distinct organization. https://cld.wthms.co/GjutIH

#### Browser / OS version
IE11 / Windows 10 & IE11 simulators.

#### Screenshot / Video
Expected: https://cld.wthms.co/G3axFC
Result: https://cld.wthms.co/GjutIH

#### Context / Source

#user-report 1851937-zen

**Comment by simison** [comment]
WPCOM simple sites fixed as of D25143-code
