### ISSUE TITLE
Reader Share Titles Set to Auto Draft

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#31225]
When sharing an article from the reader, the post title changes to "Auto Draft" when clicking publish.

<img width="784" alt="screen shot 2019-03-05 at 10 59 46 am" src="https://user-images.githubusercontent.com/1270189/53830365-1f285980-3f37-11e9-9bcb-6b04803ffbde.png">

#### Steps to reproduce
1. Visit https://wordpress.com/
2. Pick an article to share, and click on the share icon
<img width="859" alt="screen shot 2019-03-05 at 11 05 03 am" src="https://user-images.githubusercontent.com/1270189/53830299-facc7d00-3f36-11e9-9426-b61050cddc8e.png">

3. Select a site to share to using the block editor
4. Verify that share content loads properly
5. Click publish

Expected: Content matches draft content
Actual: title updates to "Auto Draft"

cc @mmtr

**Comment by kwight** [comment]
Fix for review in D25209-code.

**Comment by gwwar** [comment]
Fixed by @kwight in D25209-code and landed by @codebykat ✨! The change there also fixes revision titles not sticking around after publish eg:

- Revision A has title "Foo"
- Current Revision B has title "Bar"
- Apply Revision A
- Publish
- Title should be "Foo", but is "Bar" instead.
