### ISSUE TITLE
Related posts block: clicking placeholder images shrinks them on IE11

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#31237]
This might be an acceptable bug since it is very minor and happens in IE11 (didn't test other IE versions tho!)

When pressing image placeholders, they shrink a little bit. Notice how the one on the right is little bit smaller now:

<img width="671" alt="screenshot 2019-03-06 at 10 43 09" src="https://user-images.githubusercontent.com/87168/53868213-367e4a00-3ffe-11e9-86f0-4dde5150cbae.png">

Using Twenty Nineteen 1.3 theme.

**Comment by scruffian** [comment]
Wonfix
