### ISSUE TITLE
Gutenberg: Revisions button loading blank page (differently)

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/wp-calypso#31242]
#### Steps to reproduce
This is inconsistent - I've tested it on a few sites and some work and some don't. I've replicated this on [my site's one blog post](https://goblin.space/2019/01/14/2019-read-harder-challenge-book-1/); feel free to test that. 

1. Edit the post in question.
2. Click on the Revisions button on the right.

#### What I expected

To see the full Revisions dialog.

#### What happened instead

A blank page, on Firefox; on Chrome, `[siteurl] failed to connect` instead.

#### Browser / OS version
Firefox 65 on Mac OS. Also tested in Chrome.

#### Screenshot / Video

Firefox: 
![](https://cld.wthms.co/upJO65+)

Chrome (not my capture:)
![](https://cloudup.com/c0XJS27XR3W+) 

#### Context / Source

New report since it appears to be different, but potentially related to #29048

**Comment by kwight** [comment]
Hm, I haven't been able to trigger this, in Chrome nor Firefox (I wasn't able to directly test the given post, since we can't `su` as another a11n). Anything else you've seen that might allow replicating it?..

**Comment by goblinartificer** [comment]
> (I wasn't able to directly test the given post, since we can't `su` as another a11n). 

Huh, TIL. Try roamless.travel.blog instead? Any of the posts should work.

**Comment by donalirl** [comment]
We got another case of this in #9197151-hc. It's happening just as @goblinartificer described.

Was able to use WP Admin as a workaround in the meantime.

**Comment by mmtr** [comment]
This was happening on sites using a custom domain, since we were invalidating requests coming from valid origins. We fixed that on #31359.
