### ISSUE TITLE
Slideshow block: JS error when rendering empty block

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#31247]
#### Steps to reproduce
1. Starting at URL: /wp-admin/post-new.php
2. Add a `Slideshow` block
3. Publish a post and view it on frontend
4. check the DevTools to see the JS error. 

#### What I expected

No errors

#### What happened instead

JS error!

#### Browser / OS version

Chrome / MacOS

uglified error: 

```
view.js?ver=1551880397:1 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagName' of undefined
    at view.js?ver=1551880397:1
    at s (view.js?ver=1551880397:1)
    at a (view.js?ver=1551880397:1)
    at t.<anonymous> (view.js?ver=1551880397:1)
    at swiper.js:1
    at Array.forEach (<anonymous>)
    at swiper.js:1
    at Array.forEach (<anonymous>)
    at t.h.emit (swiper.js:1)
    at t.init (swiper.js:1)
```

**Comment by jeffersonrabb** [comment]
I'm having trouble reproducing this. By empty block do you mean a Slideshow in which no images were selected? And in which browser/OS are you seeing this?

**Comment by ChrissiePollock** [comment]
We are seeing more issues possibly connected to this. Issues are in Chrome and Safari, but Firefox seems to work. The customers are adding slideshows and getting an error "The Swiper Library could not be loaded." #1885514-zen and #11363763-HC.

**Comment by jeffersonrabb** [comment]
> We are seeing more issues possibly connected to this. Issues are in Chrome and Safari, but Firefox seems to work. The customers are adding slideshows and getting an error "The Swiper Library could not be loaded." #1885514-zen and #11363763-HC. Possibly also connected to #31192

Hi @ChrissiePollock, that would probably be a different error, but before we move to a separate issue:

- Are these Simple Sites, Atomic, or hosted Jetpack?
- Have you been able to reproduce the problem? (I just tried and wasn't immediately able to)
- Is your sense that something changed very recently? Or these are just a few tickets that have accumulated over time?

**Comment by mishivee** [comment]
@jeffersonrabb: 

* #1885514-zen and #11363763-HC are simple sites. 
* We have been able to duplicate this in Chrome for: #1885514-zen
* #11363763-HC see the "The Swiper Library could not be loaded." in Safari.

Slack conversation can be seen in #1885514-zen as a note

**Comment by arunsathiya** [comment]
@ChrissiePollock @jeffersonrabb Came across a few more reports today. Tested a bit and reported it as a separate issue - https://github.com/Automattic/wp-calypso/issues/31586
