### ISSUE TITLE
Contributor post visibility differs from WP Admin

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#31259]
We found that there is a difference in the blog post visibility that Contributors have in Calypso vs WP Admin. I understand that Contributors have limited posting and editing privileges as described by the role:

```
A Contributor can create and edit only their own posts, but cannot publish them. When one of their posts is ready to be published, or has been revised, the Administrator needs to be notified personally by the Contributor to review it. Furthermore, once a Contributor’s post is approved and published by an Administrator, it can no longer be edited by the Contributor.
```

However, in this case contributors can see counts for blog posts in Calypso, but those blog posts don't actually populate. In contrast they can see all of the blog posts in WP Admin and they can access any posts they're eligible to access (for example, they might be able to see a blog post's title, but they can't actually select it to edit if their role doesn't allow.

#### What I expected
I expect to see the same access and visibility in Calypso and WP Admin

#### What happened instead
Blog posts missing from Calypso, only for users in the Contributor role.

#### A few things we've noticed:

@kriskarkoski mentioned:
"I’ve narrowed this down to “context” in the call being set to edit. When this happens it returns no results, while returns the expected results when changed to display.

@koke mentioned:
"I know that when `context=edit` the API checks if the user can actually edit the posts 
`p1551486237002400-slack-api`
on wp-admin it seems like the list is shown, but the user also can’t edit the posts
sounds like a bug in calypso, I believe it shouldn’t be trying to set `context=edit` just for the posts list"

####  Calypso:
<img width="776" alt="screen-shot-2019-02-27-at-2 27 10-pm" src="https://user-images.githubusercontent.com/33190975/53923345-9811d900-403d-11e9-9ac1-d881d9a7d493.png">

#### WP Admin:
<img width="739" alt="screen-shot-2019-02-27-at-3 33 09-pm" src="https://user-images.githubusercontent.com/33190975/53923341-93e5bb80-403d-11e9-8a97-7adf5ed7b641.png">

#### Context / Source

#user-report
1837308-ZD

**Comment by wpericam** [comment]
I have an instance of this here: https://woothemes.zendesk.com/agent/tickets/1817755 

User (6 in CLI) jonathan82766625 email jonathan@chatkit.com is unable to see posts in Calypso but they ARE able to see posts in WP-Admin. Jetpack connection is okay and they are listed as an admin via CLI. 

**Calypso**
![Contributor-Calypso-View](https://user-images.githubusercontent.com/44411833/54149491-86d91b80-43f3-11e9-9c5a-14a0537d7ba1.png)

**Wp-Admin**

![Wp-CLI-Contributor-Mistmatch](https://user-images.githubusercontent.com/44411833/54149420-55f8e680-43f3-11e9-9b36-775bf2b6cab1.png)

**Comment by arunsathiya** [comment]
I also had a chance to test this with a Jetpack site with contributor user, same behaviour.

**Comment by mlaetitia** [comment]
Got a new case and some feedback from a user: while the user can see the posts via wp-admin they refer (and are correct) that in WP-admin they cannot access our SEO tools, only in Calypso. So for them the SEO tools aren't visible and cannot be used until this is fixed :)

#user-report here: 1817755-ZD
