### ISSUE TITLE
Editor: Icon in sharing panel has incorrect color

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#3125]
I noticed that when I am in the editor, and if I enter a message that exceeds the character limit in the sharing panel, that the bluish information icon doesn't update to be white (which would match the text color in the panel).

![screen shot 2016-02-05 at 2 46 57 pm](https://cloud.githubusercontent.com/assets/1126811/12858915/7fa33b76-cc18-11e5-83ce-db0500f5b908.png)

**Comment by jeremeylduvall** [comment]
Should be fixed in #4035.
