### ISSUE TITLE
Jetpack NUX: incorrect redirect back to the site for connected site.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#31269]
_two issues (design and flow coherence) in one_
#### Steps to reproduce
1. Starting at URL:
2. try reconnecting an already connected site  (`/jetpack/connect/authorize`) 
 e.g. - deactivate JP and activate it again, 
        - use Set up JP button from the wp-admin
3. arrive at the authorization completed screen
4. use the CTA button to attempt to return to the site

#### What I expected
Being redirected back to the site as per the content of the CTA button.

#### What happened instead
I was redirected to the site-type screen.
<img width="392" alt="screenshot 2019-03-07 at 01 18 12" src="https://user-images.githubusercontent.com/13561163/53959429-ebd6fd80-40e3-11e9-850e-12c42502d7d9.png">
<img width="495" alt="screenshot 2019-03-07 at 01 18 20" src="https://user-images.githubusercontent.com/13561163/53959434-ed082a80-40e3-11e9-8ffa-8052ed56ade8.png">

Flaws: 
- should we redirect to the site type screen? Even if so, currently we do not check whether that option has been provided for that site before showing selection,
- If users are meant to be redirected to the flow, this should not happen via "returning to the site" button,
- it seems like we have doubled the option of "returning to the site"
<img width="316" alt="screenshot 2019-03-07 at 14 31 41" src="https://user-images.githubusercontent.com/13561163/53960153-cba83e00-40e5-11e9-8178-b0b0e04b7a06.png"> /cc @keoshi what do you think?

**Comment by keoshi** [comment]
Thanks for catching this, @AnnaMag !

> should we redirect to the site type screen? Even if so, currently we do not check whether that option has been provided for that site before showing selection,

Definitely not. There's is a disconnect between the label and the action here. If we see “Return to your site” we definitely don't expect to be redirected to an onboarding flow.

> If users are meant to be redirected to the flow, this should not happen via "returning to the site" button,

Agreed, but I don't think that's even an option when there's a higher priority issue going on `WordPress.com account is already connected to another user on this site`, right?

> it seems like we have doubled the option of "returning to the site"

Yep, we should try to see if we can detect if the error occurred and hide the footer option conditionally, like so:

![image](https://user-images.githubusercontent.com/390760/53962593-5f2c3f80-40e3-11e9-8549-1c535c2d2c89.png)
