### ISSUE TITLE
Gutenberg: Preview Posts at Multiple Device Widths

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#31278]
The option to select different devices and screen sizes - is missing in the block editor after having been added in Dec. 2018. This is a feature request to replace the core preview in the block editor with Calypso’s Preview component.

<img width="1021" alt="screen shot 2019-03-07 at 8 39 15 am" src="https://user-images.githubusercontent.com/1270189/53972898-8a4b6a80-40b4-11e9-9880-8f59d1ddbf8e.png">

#### Steps to reproduce
1. Create or edit a post using the block editor.
2. Click on Preview.

#### What I expected
I expected the Preview to open in the same window with opens to preview on different screen sizes.

#### What happened instead
Preview of the post/page opens in a new Tab

#### Context / Source
Reported in #9792878-hc

**Comment by damiannep** [comment]
Another request in #1865261-zen

**Comment by lakellie** [comment]
Another request for this in 5052993-hc

**Comment by fstath** [comment]
A user asked us about this on Twitter:
https://twitter.com/merlinereads/status/1105809488626544640
