### ISSUE TITLE
Classic Block: Adding a new image to a gallery

### ISSUE THREAD

**Issue by mishivee** [Automattic/wp-calypso#31284]
#### Steps to reproduce
1. Use Gutenberg and add a classic block
2. Add a gallery within the classic block by **Add Media** -> **Create Gallery** -> Select images -> **Create a New Gallery** -> **Insert Gallery**
3. Click on the gallery and edit the gallery (pencil) -> **Add to Gallery** -> Select images -> **Add to Gallery** -> **Update Gallery**
4. You don't see the added image! 

#### What I expected
I added a gallery block to the classic editor. After creating the gallery, I decided to add an image to the gallery. I expected that the image would be added to the gallery within the Classic Block. 

#### What happened instead
When I created the gallery, everything looked great! I then decided to add an image to the gallery. That is when things got weird. If I added a image to the gallery and then clicked **Add to Gallery**, the image didn't show up. If I added it a second time, the image did show up. I found this when a user reported having issues adding images to their gallery in zen-1860625

#### Browser / OS version
 Firefox/OS X 10.14

#### Screenshot / Video
https://d.pr/v/jl9JyF

#### Context / Source
#user-report

**Comment by kwight** [comment]
Hi @mishivee , I'm having problems replicating this – I've tried creating a new gallery within a Classic block, then added a new image to it, and published with no problems (in both the `wp-admin` and the iframed `wordpress.com/block-editor` editors). I did notice that the Classic block uses the core media modal, rather than the Calypso one (reported in #31294). Any more hints to replicate?

**Comment by mishivee** [comment]
@kwight I haven't really found the pattern here. I am still able to duplicate on all of my test sites. I am duplicating it at https://wordpress.com/block-editor/

I hope this helps: https://d.pr/v/DcXnfZ 

I also noticed it was using that the Classic block uses the core media modal, rather than the Calypso one.

**Comment by mmtr** [comment]
https://github.com/Automattic/wp-calypso/pull/31596 replaces the core medial modal with the Calypso one on classic blocks, so this issue should no longer be reproducible.
