### ISSUE TITLE
Remove Google Plus

### ISSUE THREAD

**Issue by mdawaffe** [Automattic/wp-calypso#31299]
The API for third party access to Google+ has been [shut down](https://developers.google.com/+/api-shutdown). The service as a whole will shut down in April.

The Publicize APIs no longer return information about the Google+ Service or any Google+ Connections, so I believe it's the case that Publicize: Google+ has been removed everywhere from the visible UI.

We can remove any Google+ code, especially including the recent deprecation notices:
* #29370
* #30415

@eliorivero, what else am I missing?

Depending on how it's implemented, sharing to Google+ (via post sharing buttons) may still work, but we've removed that from WordPress.com and Jetpack already as well. I'm not sure if sharing to Google+ from the reader is possible, but the Sharing Buttons settings UI offers a Google+ button, which should be removed. See, for example, https://github.com/Automattic/jetpack/pull/11200.

**Comment by richardeschloss** [comment]
Just a small question...I know probably should look at the code before asking but, it might be quicker to ask here, and easier for future readers of this thread...is there any old oauth code that uses "sign on with Google"? I think an old way of signing on with Google used the google+ apis, but now it uses [your_client_id].apps.googleusercontent.com

**Comment by mdawaffe** [comment]
Thanks for bringing that up, @richardeschloss. I don't know the answer :)

I do know there are other Google services we connect to (Google Photos, for example), but I believe they all authenticate through their own, more specifically scoped, auth channels.

**Comment by eliorivero** [comment]
That's all on Calypso, although there are still some elements in Jetpack that must be removed like
https://github.com/Automattic/jetpack/blob/master/modules/widgets/customizer-utils.js#L38

**Comment by simison** [comment]
@mdawaffe @eliorivero Should any Google+ related stuff from Publicize-Gutenberg sidebar be removed before code freeze for the April release?

**Comment by mdawaffe** [comment]
> @mdawaffe @eliorivero Should any Google+ related stuff from Publicize-Gutenberg sidebar be removed before code freeze for the April release?

I'm not sure what all is there :) If it's just the conditional stuff, it doesn't matter too much, but, yes, it'd be nice if everything were gone.

**Comment by simison** [comment]
>Publicize-Gutenberg sidebar 

There's this notice visible for users with Google+ connections:

https://github.com/Automattic/wp-calypso/blob/9c7f23f92dce5445e0e15b77eb5aa4799f5c600b/packages/jetpack-blocks/src/blocks/publicize/connection.jsx#L37-L57

I don't know if it shows up after any possible backend code is removed. 

Notice says:

> Google+ will shut down in April 2019. You can keep posting with your existing Google+ connection through March.

...so I'd say this should be removed.

Also these bits and bobs:
https://github.com/Automattic/wp-calypso/blob/9c7f23f92dce5445e0e15b77eb5aa4799f5c600b/packages/jetpack-blocks/src/blocks/publicize/service-icon.jsx#L45
https://github.com/Automattic/wp-calypso/blob/9c7f23f92dce5445e0e15b77eb5aa4799f5c600b/packages/jetpack-blocks/src/blocks/publicize/editor.scss#L44-L46

And that CSS variable is here and there: https://github.com/Automattic/wp-calypso/search?q=--color-gplus&unscoped_q=--color-gplus

cc @flootr

**Comment by mdawaffe** [comment]
> I don't know if it shows up after any possible backend code is removed.

It shouldn't show up anymore. It should be removed.

The other stuff can be removed as long as nothing else uses it. (Google Photos?)

**Comment by simison** [comment]
>I came across Google+ preview option on re-Publicize section for a WordPress.com Premium plan+ site and I have logged it here #32105

Addressed in https://github.com/Automattic/wp-calypso/pull/32503
