### ISSUE TITLE
Gutenframe: The classic block uses the core media modal instead of the Calypso modal.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#31294]
While testing #31284 , I noticed that the Classic block pulls up the core media modal, rather than the Calypso media modal like other blocks.

<img width="1212" alt="screen shot 2019-03-07 at 1 46 02 pm" src="https://user-images.githubusercontent.com/349751/53991594-d364e400-40df-11e9-8d44-b4c030ec0457.png">

**Comment by Copons** [comment]
I gave this a look, and I'm a bit lost in the whole hooks and filters world.
As far as I understand, we would need to hack into the core's `wp_add_media` button (handling the add button in the editor toolbar) and `wpeditimage` plugin (handling the edit button in the contextual toolbar).

We have got a filter for replacing the button ([`mce_buttons`](https://codex.wordpress.org/Plugin_API/Filter_Reference/mce_buttons,_mce_buttons_2,_mce_buttons_3,_mce_buttons_4)), which would involve unsetting `wp_add_media` and pushing our own custom button.
We also have a filter for the plugins ([`mce_external_plugins`](https://codex.wordpress.org/Plugin_API/Filter_Reference/mce_external_plugins)) that works in the same way, but on `wpeditimage`.

Replacing the button in the toolbar is probably straightforward enough, in that it could work similarly to what we have already done to use the Calypso modal for the various media blocks.

Replacing the edit plugin though, sounds more complicated. This is what the plugin does: https://github.com/WordPress/WordPress/blob/f8c8d2c88039a58846dfe92e0fce065a26acf47b/wp-includes/js/tinymce/plugins/wpeditimage/plugin.js

So I wonder if we in fact have an actual way to hook into how the media library is called, regardless of where and how. 🤔 
I can't seem to find anything relevant in the Codex though.

**Comment by mmtr** [comment]
> So I wonder if we in fact have an actual way to hook into how the media library is called, regardless of where and how. 🤔

@Copons maybe we can just override the `WP_Medialib` command we add to TinyMCE? https://github.com/WordPress/WordPress/blob/fae24d54fef38acae09a360f70162f2cbbfba1a6/wp-includes/js/tinymce/plugins/wordpress/plugin.js#L409-L413

**Comment by Copons** [comment]
> > So I wonder if we in fact have an actual way to hook into how the media library is called, regardless of where and how. 🤔
> 
> @Copons maybe we can just override the `WP_Medialib` command we add to TinyMCE? https://github.com/WordPress/WordPress/blob/fae24d54fef38acae09a360f70162f2cbbfba1a6/wp-includes/js/tinymce/plugins/wordpress/plugin.js#L409-L413

Thanks @mmtr that seems the way to go.
Although, while it's easy enough to override that command, I'm having trouble making it communicate with the parent frame.
I'm looking into it and I hope to open a diff shortly.
