### ISSUE TITLE
Global Notices: add them to devdocs/design

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#3129]
We don't have a representation of global notices in the devdocs. 

Since they are 'global' and outside of the page flow it would be cumbersome and intrusive to render one on every load of devdocs in the top right, so I think they should be triggered by a button...

They are a separate component from notices, but we could add the aforementioned button next to the 'Compact Notices' button to fire off a global one (or perhaps a grouping of them). 

It would be good to have a few examples of status and one with a notice__action, one with a dismiss X, and when we build the 'ephemeral' style we can have one appear and fade away.

cc @mtias and @alternatekev

**Comment by mtias** [comment]
I don't think we need them there since this is not a reusable component. We could have it in the "patterns" section yet to be created, but I don't feel strongly about it.

**Comment by rickybanister** [comment]
These have been added to the devdocs
