### ISSUE TITLE
Sharing: Official LinkedIn sharing button appears misaligned 

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#31321]
#### Steps to reproduce
1. Starting at URL: Any test site
2. Browse to `My Sites > Sharing` >> Sharing buttons tab
3. Add a few Sharing buttons, including LinkedIn
4. Choose `Official Buttons` under `Button Style`

#### What I expected
All buttons including LinkedIn to be aligned correctly in same line

#### What happened instead
LinkedIn button appears a little below others, misaaligned as you can see in the screenshot below

#### Browser / OS version
Tested on MacOS Mojave / Chrome and Vivaldi

#### Screenshot / Video
![screen shot on 2019-03-08 at 21 51 41](https://user-images.githubusercontent.com/4162931/54040886-6a1ec700-41ec-11e9-9eac-1c242de94419.png)

#### Context / Source

#user-report

11039714-hc
1863088-zd

**Comment by torres126** [comment]
Automattic/jetpack#11407

**Comment by arunsathiya** [comment]
@nagpai, this is previously reported on Jetpack. I am closing your report as a duplicate. https://github.com/Automattic/jetpack/issues/11407 I will add your comment there.

**Comment by arunsathiya** [comment]
@torres126 Curious about something. :) I have often noticed that you inter-reference two issues **without actually commenting**. How do you do that? Or, are you commenting once and then deleting that comment?

**Comment by torres126** [comment]
Commenting and deleting, yep. Mainly because they're just relevant to each other, though actually, not sure if that's as ideal since a notification is sent.

**Comment by nagpai** [comment]
Thank you @torres126 , @arunsathiya
