### ISSUE TITLE
UX: Coupon code link visibility

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#31322]
The link to enter a coupon code is difficult to locate because of its size and location. Currently, to enter a code, you must click a link here:

<img width="1232" alt="screen shot on 2019-03-08 at 09-37-54" src="https://user-images.githubusercontent.com/7596032/54042297-c99eb780-4197-11e9-9965-22942b004ea4.png">

Because it looks like a link and not a spot to put a code, I think it often gets missed.

After the link is clicked, a box appears where the code can be entered:

<img width="301" alt="screen shot on 2019-03-08 at 11-47-11" src="https://user-images.githubusercontent.com/7596032/54042384-fbb01980-4197-11e9-81a0-cb5c9994b117.png">

It may be better to adjust that so that the location to enter the code is active by default, as this is becoming fairly common in sites accepting coupons now. 

#### Context / Source

Came up in 10004251-hc where user described it as `almost invisible and very small`.

**Comment by retnonindya** [comment]
Came up in a conversation: p1553636354528800-slack-sales-questions.

**Comment by zdenys** [comment]
Another case of a user who reported that `when I go to checkout, there is no place to enter the coupon code` 510809-hc

**Comment by GeoJunkie** [comment]
Another case where we had to give a refund because the user didn't see where to enter the coupoon code: 12676123-hc

**Comment by kristarella** [comment]
+1

The position has changed now to the right of the page, but on days when emails with coupons go out we still get a lot of questions asking where it is.

Today I had a customer say "wow, that's tiny, I had to put my glasses on to see it" after I told them where to look.

![coupon-link](https://user-images.githubusercontent.com/2031017/61923329-e1d86d00-afa6-11e9-8129-c2073cb94f1c.png)

**Comment by bsanevans** [comment]
Another case here: 10494039-hc

**Comment by Aurorum** [comment]
PR in #34905 to remove that link and automatically display the coupon input. :)

**Comment by davipontesblog** [comment]
I am closing this since it is addressed in the new checkout redesign.
