### ISSUE TITLE
Gutenframe: Missing free photo library and Google Photos library

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#31338]
#### Steps to reproduce 

- Start with a WordPress.com site and opt-in for Gutenberg 
- Visit `example.com/block-editor/post`
- Add an image block, gallery block or click on featured image section

#### What happens instead 

There is an option at the top left, to choose from `Free photo library` or `Google photos library`

Example image from Calypso editor:

<img width="664" alt="Screenshot 2019-03-10 at 11 00 03" src="https://user-images.githubusercontent.com/18581859/54081050-b7518480-4323-11e9-8530-ec1e88554781.png">

#### What happens instead 

The `Free photo library` and `Google photos library` options are missing.

<img width="1493" alt="Screenshot 2019-03-10 at 11 00 19" src="https://user-images.githubusercontent.com/18581859/54081051-b9b3de80-4323-11e9-901b-fe90f19a6a95.png">

#### Notes

I [searched a bit](https://github.com/search?q=repo%3AAutomattic%2Fwp-calypso+is%3Aissue+is%3Aopen+%22photo+library%22) but did not come across an issue for this since [introducing Gutenframe](https://github.com/Automattic/wp-calypso/pull/31196). I do see [this comment](https://github.com/Automattic/wp-calypso/issues/28960#issuecomment-448570826) about introducing this for Gutenlypso, but doesn't look to be the case for Gutenframe at the moment.

1866000-hc

**Comment by damiannep** [comment]
Another report of this in #1865261-zen

**Comment by damiannep** [comment]
User unhappy with this change in #1859943-zen

**Comment by damiannep** [comment]
> Updated users in #1859943-zen and #1865261-zen
