### ISSUE TITLE
Cant Highlight Text - Classic editor and Edge  browser

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#31339]
#### Steps to reproduce
1. Use Microsoft Edge and the Classic editor.
2. Go to edit a page or post.
3. Select HTML view.
4. When you select content it doesn't get highlighted.

#### What I expected

When you select content usually the words are highlighted with a blue background and white font.

#### What happened instead

You can still copy and paste, but without seeing the selected content. 

#### Browser / OS version

Microsoft Edge / Windows 10.

#### Context / Source

1855446-zd

#user-report

**Comment by tbradsha** [comment]
Reported here: 11038950-hc
