### ISSUE TITLE
Gutenframe: translations not being applied correctly

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#31340]
#### Steps to reproduce
1. Set interface language to a language where Gutenberg strings are mostly translated (example: pt-br)
2. Open the block editor in a simple site, so it loads the iframe version
3. Some elements will load in the selected language and some will load in English.

Examples of translated strings on the pt-br repo that are not applied to the editor:
* https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=242754&filters%5Btranslation_id%5D=7415185
* https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=242233&filters%5Btranslation_id%5D=7415363
* https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=237425&filters%5Btranslation_id%5D=7415453

#### What I expected

The editor should load the translated strings

#### What happened instead

Some strings that have translations show up in English

#### Browser / OS version

Texted on the latest versions of Firefox and Chrome on Mac OS 12

#### Screenshot / Video

![Screenshot](https://cld.wthms.co/NNW4Iq+)
Screenshot: https://cld.wthms.co/NNW4Iq

User report: 1867958-zen

**Comment by akirk** [comment]
Thanks for reporting. The reason was a corrupt JSON file with the translations (the translations were there but there was a syntax error that prevented them from being loaded). This has been fixed on the server-side, so closing this.
