### ISSUE TITLE
[Shortcopy] Calypso Plan > My Plan: prioritize Security and Performance feature cards

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#31357]
Refocusing Jetpack around Security and Performance.

Design TBD

**Comment by keoshi** [comment]
This will no doubt require a much deeper content strategy work, but pointing out that we’ve started a PR for the changes on that page here:

https://github.com/Automattic/jetpack/pull/11505

This draws in cues from the changes we’ve done on the My Plan page for sites on the free plan, so we might want to update that as well in order to unify the messaging:

https://github.com/Automattic/jetpack/pull/11418

**Comment by jeffgolenski** [comment]
### **Before**

**Jetpack Free**
![Screen Shot 2019-03-12 at 1 37 15 PM](https://user-images.githubusercontent.com/214813/54222589-1baf4800-44cc-11e9-8864-4c86c5dc142d.png)


**Paid Plan**
![Screen Shot 2019-03-12 at 1 44 40 PM](https://user-images.githubusercontent.com/214813/54223032-0686e900-44cd-11e9-8987-986704ce50d8.png)


### **After**

tbd

**Comment by jeffgolenski** [comment]
@keoshi What do you think about this organization? I think in a future iteration we can add some cards to the free plan, but as an MVP I'm just changing the organization. I like the idea of having the support card as the anchor at the bottom and having all the actual "features" above it.

**Comment by keoshi** [comment]
I love all the changes here and like that you’re approaching this as an MVP!

One thing that I can’t really confirm right now (I’m on mobile) is if each module has a corresponding URL, but at the very least we can redirect them to a filtered search of the settings. 

Ship it!!

**Comment by eliorivero** [comment]
What if we save some space moving the button to the side? The way it is now, in the center, with too much space, looks a bit isolated.

![design](https://user-images.githubusercontent.com/1041600/54241121-f7209380-44fe-11e9-9e7a-beb86168777b.jpg)

**Comment by keoshi** [comment]
Love that, @eliorivero ! Let's include that change too.

**Comment by keoshi** [comment]
Picking this up today.
