### ISSUE TITLE
Checkout: billing information accepts invalid postcodes

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#31379]
#### Steps to reproduce
1. Begin checkout with a new US [test credit card](https://stripe.com/docs/testing#cards) e.g. 4242424242424242.
2. Use US for country, 00000 for postal code.
3. Complete the checkout.

#### What I expected
An invalid postcode error.

#### What happened instead
Checkout completes.

#### Context / Source
Originally raised in #31150 by @prettyboymp. 

I'm not sure we _need_ this day one so separating and clarifying the issue for someone to pick up on it at a later time.

**Comment by prettyboymp** [comment]
We should discuss how we want to handle this.  We can add errors to the server side cart for invalid postal codes when within the US.  We just need to decide if it's worth preventing a user from checking out if they enter a postal code that isn't found.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
> We just need to decide if it's worth preventing a user from checking out if they enter a postal code that isn't found.

I don't know that it's an issue on our end of things, but I do wonder if we should be submitting the zip code to Stripe for card validation. It would likely negatively affect conversion rates, but could possibly help with fraud?

**Comment by michaeldcain** [comment]
I'll mark this as low priority, since it's technically valid, but doesn't prevent users from checking out.

**Comment by sirbrillig** [comment]
As of D60388-code we are now validating tax postal codes during a transaction using the same system we use to validate postal codes for domains. I was hopeful that would resolve this issue, but it seems that the postal code validation accepts `00000` as a valid US postal code.

**Comment by cuemarie** [comment]
Hi @michaeldcain ! Kitkat is working on reviewing issues that have been marked [Status] Stale for a long time, and manually closing them, as part of this project: pdqkMK-14B-p2 .

This issue falls under that category, but I see you've recently filed it within Shilling's backlog board. Same question as my other ping - what do you think - would Shilling like to keep this issue open despite it's stale status, age, and low priority?

**Comment by sirbrillig** [comment]
Cain is on sabbatical, but I can try to answer. We could still fix this and I think there's some value in tracking it, although since the issue is on the backend it doesn't need to be tracked in the calypso repo. I've created https://github.com/Automattic/payments-shilling/issues/1965 to track it and I'll close this one.

**Comment by cuemarie** [comment]
Sounds good, thank you @sirbrillig !
