### ISSUE TITLE
Gutenberg: Calypso Media Modal may error

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#31371]
We're getting some reports that the Calypso Media Modal may disappear unexpectedly in some cases. Next steps are to narrow down environment details/find more reproducible steps.

To Reproduce On Affected Sites:

- Click on Featured Image in the sidebar
- Click around the media modal ( for example try to edit )
- Close / re-open the media modal 
- Continue trying the above inputs until the Media Modal closes unexpectedly
- Try clicking on Featured Image
- Media Modal does not appear

**Comment by tbradsha** [comment]
Featured image wasn't able to be added: 9410749-hc

![Image](https://cld.wthms.co/WK8rZw+)

**Comment by gwwar** [comment]
closing this out for now from unactionable steps
