### ISSUE TITLE
Reader: Recommendations placeholders don't go away

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#3138]
Last night I noticed that when I go to `/recommendations`, and then scroll to the bottom, that the placeholders don't go away.

I initially noticed in the Windows WordPress.com app, but I also noticed the issue in Chrome as well. Console in Chrome doesn't show any errors.

![screenshot 12](https://cloud.githubusercontent.com/assets/1126811/12865059/12673a22-cc67-11e5-9221-0d510af2c00b.png)
![screenshot 13](https://cloud.githubusercontent.com/assets/1126811/12865058/1266c7ea-cc67-11e5-9972-b38d3e41b37e.png)

cc @blowery

**Comment by bluefuton** [comment]
I've seen this happen too, but can't reproduce consistently. 

Occasionally we seem to get less than 100 recommendations returned, and because the infinite list declares `isLastPage` to be `this.state.recommendations.length >= 100`, the placeholders never vanish.
