### ISSUE TITLE
Gutenberg: Media & Text block missing "Insert from URL" option

### ISSUE THREAD

**Issue by detlefholtz** [Automattic/wp-calypso#31399]
#### Context / Source
The Media & Text block seems to lack a useful option that is apart of the Image block. It is lacking the Insert From URL option / button. Here's a screenshot comparison of those two blocks:

![Screen Shot on 2019-03-12 at 10_38_11](https://user-images.githubusercontent.com/52152/54238560-08a17580-44d6-11e9-8598-581bff39a4d1.png)

I'd like to see this added because I think it makes sense but also a user was asking about this feature in chat. They wanted to be able to add an image by URL in order to avoid using their Media Library.

**Comment by codebykat** [comment]
Thanks for the report! This is an issue in core Gutenberg so I'm moving it over there.

https://github.com/WordPress/gutenberg/issues/14397
