### ISSUE TITLE
People: Email followers infinite list always fetching

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#31398]
When looking at my list of email followers, the list is always trying to retrieve more followers even if I'm not scrolling. When inspecting with React dev tools I can see the `fetching` state automatically flipping between `true` and `false`, and the `currentPage` keeps increasing. This is on a site that only has 7 email followers.

![2019-03-12 11-49-06 2019-03-12 11_50_06](https://user-images.githubusercontent.com/448298/54216510-2bc12a80-44c0-11e9-98f8-6d10dc8f0158.gif)

If I try to scroll I see the loading state at the bottom of the list.

On a different blog, there's only 1 email follower visible with a loading state, but the inspector says there are 2 followers:

<img width="1134" alt="Screen Shot 2019-03-12 at 12 10 30" src="https://user-images.githubusercontent.com/448298/54216554-3f6c9100-44c0-11e9-8e5c-ae3c7eae8750.png">

#### Steps to reproduce
1. Starting at URL: `/people/email-followers/{siteslug}` for a site with more than 1 follower.
2. Try to scroll through email followers.
3. Observe the perpetual loading state at the end of the infinite list.
4. Open React dev tools to inspect.
5. Observe the infinite loop of trying to update the `<FollowersComponent>`

#### Context / Source
#dogfooding #manual-testing

**Comment by lancewillett** [comment]
Possibly related to #23937
