### ISSUE TITLE
Color Schemes: White gradient on Post Format tab in Classic editor

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31392]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post/
2. Ensure you're using the Classic editor, and a theme that supports Post Formats
3. Hover over the Post Format tab and note the white gradient to the left of the arrow
4. This happens regardless of color scheme (Classic Bright shown).

<img width="275" alt="Screen Shot 2019-03-12 at 11 18 25 AM" src="https://user-images.githubusercontent.com/2124984/54212803-c4a07780-44b9-11e9-9cc5-9a5c7e2e6828.png">

#### What I expected

The tab background should stay gray on hover.

#### What happened instead

A white gradient appears to the left of the toggle arrow on hover; it's likely attached to the post format name (ie. "Standard")

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
