### ISSUE TITLE
Wix Importer: Attempt to import Wix site failing

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#31394]
#### Steps to reproduce

1. Starting at URL: https://pljcbsntestpersonal.wordpress.com
2. Tried to import a user's Wix site using the Wix Site Importer
3. I entered the Wix site's URL (https://www.lespetiteslectures.com), was presented with a site preview, and clicked to proceed.
4. The import failed, and produced [the following error](https://cld.wthms.co/9zdv1Q):

![](https://cld.wthms.co/9zdv1Q+)

#### What I expected

The importer would begin importing the targeted site.

#### What happened instead

An error message stating the following:

>It looks like we're unable to reach that website address at this time. (ID: 0761f30f-9225-4c58-8e1b-fdacee9be244) (1000002)
>Try again or contact support.

#### Browser / OS version

My browser is Firefox Developer Edition 66.0b13 on macOS 10.14.3.

The user's user agent is Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

#### Screenshot / Video

See above

#### Context / Source

This is a user report from 11151294-hc (follow-up here: 1873220-zen).

My test produced the same error as the one the user experienced on their site.

**Comment by blazevivan** [comment]
User was on chat today, to check for an update about the issue. Informed them that we don't have any ETA for this yet.

**Comment by lancewillett** [comment]
Thanks for the report, assigning to @Automattic/delta-samus CC @mattsherman 

Removing High priority tag as we reserve that for things like network-wide issues that affect most customers.

**Comment by andfinally** [comment]
I'm seeing the same issue with that URL. Looking at the URL directly, there's a series of three redirects before we get the eventual 200 response, including one 301 from `https` to `http` and then `https`. This may be causing the site parser some trouble.

https://www.lespetiteslectures.com/
    301 response redirecting to https://lespetiteslectures.com/

https://lespetiteslectures.com/
    301 response redirecting to http://lespetiteslecturesdemaud.com/

http://lespetiteslecturesdemaud.com/
    301 response redirecting to https://lespetiteslecturesdemaud.com/

https://lespetiteslecturesdemaud.com/
    200 response
