### ISSUE TITLE
Editor: Update WP Admin improved posting experience notice

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#314]
Now that the Calypso editor is launched we should review and update the WP Admin "improved posting experience" notification and consider adding an option to dismiss it.

![screen shot 2015-11-20 at 2 54 25 pm](https://cloud.githubusercontent.com/assets/1900444/11310262/a105c162-8f96-11e5-9187-dfad989b35c6.png)

Example link: https://wordpress.com/post/43021110/new/?optin

@designsimply also suggested a great update to the wording:

> Recent updates have been made based on your feedback. Switch to the new editing experience for WordPress.com!
>
> Replacing this:
>
> There’s now an easier way to create on WordPress.com! Switch to the improved posting experience.

**Comment by designsimply** [comment]
Leaning toward something even simpler for the wording:

> The WordPress.com editing experience has been updated. Switch to the new editor.

or just:

> Switch to the new editor.

I would advise against a dismiss option on this particular notice because, in this case, I think we do always want there to be a route to the latest version of the editor because it's what is under active development and the one we'd like to see more feedback about.

**Comment by lancewillett** [comment]
Good point on the reason for no dismiss link.

**Comment by lancewillett** [comment]
How about: `There's an easier way to publish on WordPress.com. <Switch to the new editor>.`

**Comment by lancewillett** [comment]
Changes proposed in D1686-code

**Comment by lancewillett** [comment]
After, using Mac-n-Chrome on a test site:

<img width="707" alt="screen shot 2016-04-27 at 4 39 29 pm" src="https://cloud.githubusercontent.com/assets/66797/14871408/a18ba82c-0c96-11e6-97d2-cdaaeaaed447.png">

Link takes me to `https://wordpress.com/post/example.wordpress.com`

**Comment by lancewillett** [comment]
Mobile after screenshots, same URLs as above — testing with iPhone 6 in Simulator.app on OS X:

**wp-admin**
<img width="487" alt="screen shot 2016-04-27 at 4 46 36 pm" src="https://cloud.githubusercontent.com/assets/66797/14871523/cfb13cc0-0c97-11e6-97ef-bd45b87b67f6.png">

**Calypso (after clicking the link in the notice)**
<img width="487" alt="screen shot 2016-04-27 at 4 46 47 pm" src="https://cloud.githubusercontent.com/assets/66797/14871525/d2fc8dc6-0c97-11e6-9b0d-672eadfa54ae.png">

**Comment by dllh** [comment]
I like the idea of this change, but I'm skeptical that adding "new" wording is the best. In a few months, it won't really be new anymore, and if we forget to come back and update, this'll wind up being a kind of inaccurate notice. I guess the same is true of the "recent updates have been made" wording. If we set a followup to revisit after some reasonable time, I'm less worried about it.

I'm also not sure what the i18n impact will be. When we ship this change, the strings will be invalid and non-English users will see the notice in English until translated, which might actually wind up making it less effective for those users. So we might want to see if we can line up translations right away for at least high-volume locales.

**Comment by lancewillett** [comment]
I'm not as worried about translations — this is how the WordPress.com workflow works for all changes.

Good point on the "new" wording — however, I think it'll still be new as long as wp-admin is around, right? I think we can revisit in 6 months and update it again, like we are now.

**Comment by dllh** [comment]
Fair enough re translations. 

I disagree with the semantics around "new" here. If wp-admin is still around in 3 years (or 1 year), that doesn't make Calypso still new -- just different ("improved"). But yeah, if there's a specific followup to revisit after a while, I'm not as bothered by it.

**Comment by lancewillett** [comment]
Deployed simpler wording in r135559-wpcom

`There's an easier way to create on WordPress.com. Switch to the improved editor.`

<img width="872" alt="screen shot 2016-05-09 at 11 45 40 am" src="https://cloud.githubusercontent.com/assets/66797/15124106/93d553ce-15db-11e6-8970-06731ed3fbda.png">
