### ISSUE TITLE
Jetpack Onboarding: Hide during support sessions

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#31435]
As a Happiness Engineer, when you have to reconnect Jetpack on an user's site (Atomic), an ability to hide this view would be helpful. Currently there isn't one, and the only option is to make a guess on what the site is about and choose the option. This is likely to skew the results. 

Extra details on p1552460136021600-slack-nux // cc @tyxla 

![Screenshot 2019-03-13 at 11 47 10](https://user-images.githubusercontent.com/18581859/54300298-94082d00-45e2-11e9-8409-cd2d4d84b736.png)

**Comment by tyxla** [comment]
Thanks for reporting @arunsathiya!

Here's a suggested fix: #31456

**Comment by tyxla** [comment]
Additionally, we're introducing skip links in #31304, which will allow HEs to skip those steps for non-Atomic sites as well.
