### ISSUE TITLE
Media & Text Block Does Not Display Custom Thumbnail Image For Video

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#31461]
#### Steps to reproduce
1. Upload a video to the Media page.
2. Set a custom thumbnail for the video by uploading an image or selecting a frame.
3. Create a new page.
4. Insert a Media & Text Block.
5. Add the newly uploaded video to the block.
6. View the page.

#### What I expected
The custom thumbnail to be used for the video.

#### What happened instead
The default thumbnail for the video is used instead.

#### Browser / OS version
Tested in Chrome / Mojave

#### Screenshot / Video
![Custom thumbnail not used in Media & Text block](https://d.pr/free/i/DMQGlO+)

(Image link: https://d.pr/free/i/DMQGlO )

#### Context / Source
#user-report
First reported 11217737-hc
Followed up here: 1878941-zen

**Comment by davipontesblog** [comment]
Exactly the same report, different user here:

Context / Source
#user-report
First reported 4020817-hc
Followed up here: 2003774-zen

**Comment by lancewillett** [comment]
Thanks for the reports.

Did you have a chance to confirm if this is a general Gutenberg block issue (not related to our WordPress.com implementation?) You can test on a self-hosted site quickly to tell if it's specific to one environment or not. If it's general to Gutenberg we can move it there: https://github.com/WordPress/gutenberg/issues

I tested a bit on a WordPress.com site as well as a self-hosted WordPress site — both had similar behavior: no thumbnail image at all, actually. After setting the custom thumbnail, I just see a blank preview for the video, both in the Gutenberg editor and on the front-end post or page view.

<img width="1265" alt="Screen Shot 2019-05-31 at 14 51 03" src="https://user-images.githubusercontent.com/66797/58736674-8f6a3e00-83b3-11e9-9761-66e797535dd7.png">

<img width="1232" alt="Screen Shot 2019-05-31 at 14 51 08" src="https://user-images.githubusercontent.com/66797/58736675-8f6a3e00-83b3-11e9-8ca1-0d5f659c99ee.png">

Let's leave it open as we investigate further; but my sense is it could be a broader issue than only WP.com sites.

**Comment by davipontesblog** [comment]
> Thanks for the reports.
> 
> Did you have a chance to confirm if this is a general Gutenberg block issue (not related to our WordPress.com implementation?) You can test on a self-hosted site quickly to tell if it's specific to one environment or not. If it's general to Gutenberg we can move it there: https://github.com/WordPress/gutenberg/issues

I actually tested this today and could not find a way to set a thumbnail image to a video in the media library - both in calypso, and wpadmin, both for wpcom and wporg sites (my wporg site has Jetpack connected so I tested this on calypso media library, and wpadmin as well) I tested this on. So there was no way to add a thumbnail image, hence I wasn't able to test whether the media and text block would display the thumbnail or not on atomic or .org site.

**Comment by mmtr** [comment]
Closing this favor of https://github.com/Automattic/jetpack/issues/13239, given this needs to be fixed in Jetpack (where the VideoPress extension for Gutenberg lives).
