### ISSUE TITLE
Hide Share option for posts for Atomic sites 

### ISSUE THREAD

**Issue by selectedselections** [Automattic/wp-calypso#31472]
#### Steps to reproduce
1. Visit the WordPress.com reader from an account with an atomic site
2. Click on the share button from the reader for any post
3. Share the post to your atomic site 
4. The draft will appear as blank

#### What I expected
* The reblog option does not work for atomic sites 
* When I click on "share" from the reader, my atomic site should not be a share option

#### What happened instead

* The share option from the reader lists my atomic site, but the button results in a blank draft. 

#### Browser / OS version

Chrome 72 Mojave 10.14.2

#### Screenshot / Video

https://cld.wthms.co/SJfoiM

**Comment by bluefuton** [comment]
Thanks for reporting this @selectedselections! It does still work for me in the pre-Gutenberg editor:

<img width="1141" alt="Screen Shot 2019-03-21 at 17 29 58" src="https://user-images.githubusercontent.com/17325/54733567-2621be00-4bff-11e9-811e-e459902f96ac.png">

...but as soon as I switch the Atomic site to use Gutenberg, I see the issue you described.

Reader Share passes the post details along via the query string using the `embed`, `image`, `title`, `text` and `url` parameters, which don't seem to work in this case. Here's an example URL:

`https://example.com/wp-admin/post-new.php?embed=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F215324720&image=https%3A%2F%2Fgogreygirl.files.wordpress.com%2F2018%2F09%2Fcombine.jpg%3Fquality%3D80%26strip%3Dinfo%26w%3D1600&title=Well+of+Lost+Thoughts+–+2018+—+Fueled+by+Chocolate&text=When+I+find+ideas+that+speak+to+me%2C+but+I’m+not+ready+to+blog+about+them%2C+I+save+them+on+my+Fueled+by+Chocolate+‘Well+of+Lost+Thoughts’+Facebook+Page.+Here+are+just+a+few+of+the+ones+I+have+‘rescued’+from+there+to+share+with+you.+The+Man+Drawer+The+Car+Guy+has+more%C2%A0%5B…%5D&url=https%3A%2F%2Fgogreygirl.wordpress.com%2F2019%2F03%2F20%2Fwell-of-lost-thoughts-2018%2F`

**Comment by gwwar** [comment]
This one should be fixed by https://github.com/Automattic/wp-calypso/pull/36124
