### ISSUE TITLE
Importers: Make file upload success more obvious

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#31481]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/[ site ].wordpress.com
2. Click on the `Start Import` button on a WordPress import.
3. Click the file upload pane and select a WordPress export file to upload.
4. Observe the UI at the end of the successful upload.

#### What I expected
The UI gives a clear indication that my file has been successfully uploaded.

#### What happened instead
The result of the upload isn't obvious - the colour of the upload pane and its text is the same. The only difference is a change of text and the appearance of a `Continue` button below the pane.

#### Browser / OS version
MacOS Chrome 72.0.3626.121

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1647564/54421983-6e277900-4705-11e9-8e9d-f77e31ef4206.png)

![image](https://user-images.githubusercontent.com/1647564/54421998-72539680-4705-11e9-9187-e359b36b93d7.png)

![image](https://user-images.githubusercontent.com/1647564/54422011-77184a80-4705-11e9-883b-b163f881ee4e.png)

#### Context / Source
With the improvements to the importer UI introduced in https://github.com/Automattic/wp-calypso/pull/31364, it's no longer so obvious when an import file upload has succeeded. With the previous UI, a magenta button popped into view in the middle of the pane. We could maybe improve this by changing the colour of the pane border and text to green.

#manual-testing

**Comment by bisko** [comment]
We're now automatically proceeding when an upload was successful, so we're mostly not seeing this UI.
