### ISSUE TITLE
Domains: Site Redirect: Add placeholder

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3148]
We should add a placeholder for editing Site Redirect

![image](http://g.recordit.co/WRs3g3XhHV.gif)

**Comment by jsnmoon** [comment]
Closing this as it's no longer applicable to the current Site Redirect page, which uses a placeholder for the input field:

<img width="746" alt="redirect_a_site" src="https://user-images.githubusercontent.com/4044428/40942468-8955e07e-680b-11e8-9476-be902b7dea27.png">

Please reopen if the issue remains relevant to the current interface.
