### ISSUE TITLE
Editor: Autosave needs to properly recover from errors / network drops

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#315]
Right now if you start a new post and then your network drops out the editor gets stuck at "Saving..." and doesn't recover when the network reconnects. Clicking "Publish" from here does work, but there's no preview and clicking the preview popout link goes to a New Post editor page for some reason.

We need to handle errors from autosave and do some background polling or something.

raised by codebykat

**Comment by lancewillett** [comment]
Let's re-open this in the future once we have specific bugs or tasks. If you notice errors or autosave problems, log a new issue with as much detail as possible.
