### ISSUE TITLE
Create a package for calypso sass utils assets.

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#31507]
See how we extracted color-schemes into it's own package:

https://github.com/Automattic/wp-calypso/tree/ba2d24f39fa7fb85efc039fb94f9b3fcf416bf1d/packages/calypso-color-schemes

We should do the same for all of the utils styles sheets: 
https://github.com/Automattic/wp-calypso/blob/ba2d24f39fa7fb85efc039fb94f9b3fcf416bf1d/assets/stylesheets/shared/_utils.scss

Question for @Automattic/gutenpack 

1. Should our extracted  packages be dependent on the `calypso-build` package? IE should we use our shared sass pipeline?

**Comment by roccotripaldi** [comment]
> Should our extracted packages be dependent on the calypso-build package? IE should we use our shared sass pipeline?

Answering my own question: No. It looks like we expect clients to import the sass file directly into their project

**Comment by sirreal** [comment]
> > Should our extracted packages be dependent on the calypso-build package? IE should we use our shared sass pipeline?
> 
> Answering my own question: No. It looks like we expect clients to import the sass file directly into their project

I think that's right. I'd expect that `calypso-build` might depend on this, or that consumers might depend on both this and `calypso-build`, but my intuition is that `calypso-build` wouldn't need to depend on this 👍

**Comment by simison** [comment]
We seem to rely only in these 3 variables:
```
$green-jetpack
$muriel-hot-red-500
$muriel-hot-green-500
```

Seems like we shouldn't treat having this package as a blocker and try to leave it in Calypso for now?

convo p1552929274432100-slack-jetpack-gutenberg

**Comment by roccotripaldi** [comment]
fixed in #31503
