### ISSUE TITLE
Mailchimp block: Connection pop-up window does not go away after logging in

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#31521]
#### Steps to reproduce
1. Starting at URL: https://kpgutentester1.wordpress.com/ (test site)
2. Site Pages > Add Page
3. Click the + symbol at the top left to add a new block
4. Search for "Mail" in the block search box, select "Mailchimp" block 
5. Click "Set up Mailchimp form"

<img width="1168" alt="Sharing ‹ kpgutentester — WordPress com" src="https://user-images.githubusercontent.com/7662449/54498841-3590c680-48e2-11e9-9ab4-4ca79b56fa1c.png">

6. In the new window that opens, click "Connect":
<img width="1168" alt="Sharing ‹ kpgutentester — WordPress com-1" src="https://user-images.githubusercontent.com/7662449/54498855-58bb7600-48e2-11e9-8c8f-798b0c245d14.png">
7. In the pop-up login window, enter your Mailchimp credentials.

#### What I expected

The pop-up should clearly accept your credentials and show a confirmation message, and I should be taken to a screen that lets me select _which list_ I want to connect.

#### What happened instead

The pop-up window stays open and there is no confirmation message. I still see the username and password fields, so it's not clear whether the connection was successful. If I try to close the pop-up window, another one just takes its place. The only way to get the pop-up to close is to close the underlying Sharing window.

#### Browser / OS version

Firefox 65.0.1 / MacOS 10.12.6

I watched the same thing happen to a WordPress.com customer running Safari. 

#### Screencast

https://cloudup.com/cc3PnAtZVWP

#### Context / Source
Business concierge session with WordPress.com customer.

#user-report

**Comment by simison** [comment]
FYI @artpi

**Comment by simison** [comment]
@scruffian do you know if this is still an issue?

**Comment by scruffian** [comment]
I believe this is no longer an issue. I could not replicate. Feel free to reopen if you can.
