### ISSUE TITLE
Mailchimp block: "MailChimp" does not have a capital "c"

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#31522]
"Mailchimp" shouldn't have a capital "c".

Seen at https://wordpress.com/sharing/ on a WordPress.com Simple site with a Premium plan.

#### Screenshot / Video
<img width="1168" alt="Sharing ‹ kpgutentester — WordPress com-2" src="https://user-images.githubusercontent.com/7662449/54499081-565a1b80-48e4-11e9-998d-e95008f64d11.png">

#### Context / Source

WordPress.com Business Concierge session

#user-report

**Comment by simison** [comment]
FYI @artpi

**Comment by scruffian** [comment]
I created a PR for this here: https://github.com/Automattic/wp-calypso/pull/31993
