### ISSUE TITLE
Manage purchases -page has texts with poor colour contrast

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#31526]
Some texts and inputs at purchase management pages have poor colour contrast — all light grey texts in these screenshots:

<img width="740" alt="Screenshot 2019-03-18 at 08 54 16" src="https://user-images.githubusercontent.com/87168/54516027-74686000-4966-11e9-974f-37c565b2032c.png">
<img width="732" alt="Screenshot 2019-03-18 at 08 53 54" src="https://user-images.githubusercontent.com/87168/54516028-7500f680-4966-11e9-824c-d5865bed36d1.png">

Specifically, go to _Me → Manage Purchases → Billing history_.

https://webaim.org/resources/contrastchecker/?fcolor=969CA1&bcolor=FFFFFF

<img width="729" alt="image" src="https://user-images.githubusercontent.com/87168/54516137-be514600-4966-11e9-9eb1-05632a2430a0.png">

These texts are also pretty small in size, which also makes them harder to read.

Since similar issues are visible at "Account recovery" -page, this might be a more generic issue of using `--color-neutral-light` variable for texts at all? If this should not be allowed, we should probably have a lint rule to disallow this.

<img width="741" alt="Screenshot 2019-03-18 at 08 56 38" src="https://user-images.githubusercontent.com/87168/54516048-7b8f6e00-4966-11e9-98de-7557116c3c59.png">

cc @drw158 @flootr

**Comment by drw158** [comment]
I would search all instances of neutral-light used with text and replace with text-subtle. We just need to be careful because we can't assume the text is on a white background. Using neutral-light is acceptable for text, if the background is dark.
