### ISSUE TITLE
Purchases: No way to re-enable Auto Renew

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3153]
You can enable Auto-renew without a charge in WP Admin, but you cannot do that on Calypso. The only option you have is "Renew Now" which charges the account to extend and then enables Auto Renew.

We should let them enable Auto Renew without going through checkout process.

WP Admin:
-
![image](https://cloud.githubusercontent.com/assets/991022/12875648/afe8c38c-cda3-11e5-81f0-33d84489f92a.png)

**Comment by fabianapsimoes** [comment]
We're moving away from the auto-renew toggle we had in WP-Admin, and moving to a subscribe / unsubscribed model (pbg9X-8Tk-p2). Users are able to switch from unsubscribe to subscribe either by renewing or by updating their payment details. 

I'll close this, but here's a ping to @mikeshelton1503 in case he has anything else to add about this.
