### ISSUE TITLE
Business Hours Block: Shows up while editing a page/post but it's not published

### ISSUE THREAD

**Issue by dromero20** [Automattic/wp-calypso#31533]
User reached us in #11315817-hc, they added a Business hours block. It's showing up on the preview but it's not showing up on the site. I was able to replicate the issue in my test site, which is using a different Theme.

#### Steps to reproduce
1. Starting at URL: https://machomestaging.com/contact-us
2. Edit the Page by using Gutenberg.
3. Add Business hours block.
4. Publish your changes.

#### What I expected
Business hours block should appear on the page.

#### What happened instead
It is not showing up, but it does show up on the edition page.

I replicated the steps in my test site and they're not showing up on there too.

Editor view:
<img width="951" alt="Captura de pantalla 2019-03-18 a las 15 06 48" src="https://user-images.githubusercontent.com/23258551/54535866-c376bb00-498f-11e9-9a1a-fc1abf2b5a8b.png">

Page view:
<img width="1313" alt="Captura de pantalla 2019-03-18 a las 15 09 29" src="https://user-images.githubusercontent.com/23258551/54535906-dc7f6c00-498f-11e9-9ebd-7fd9c296157e.png">

**Comment by arunsathiya** [comment]
Something does seem to be off, yes. I am not able to see the block either on first publish, but on editing the block settings a bit (like opening or closing hours), the block appears fine.

| ![Screenshot 2019-03-18 at 20 35 12](https://user-images.githubusercontent.com/18581859/54540546-2aab6400-49be-11e9-8b41-780937639929.png) | <img width="780" alt="Screenshot 2019-03-18 at 20 35 00" src="https://user-images.githubusercontent.com/18581859/54540541-2aab6400-49be-11e9-864d-455fb7303160.png"> |
|------|------|
| ![Screenshot 2019-03-18 at 20 38 00](https://user-images.githubusercontent.com/18581859/54540612-4b73b980-49be-11e9-9b57-6f3795d3a6b9.png) | ![Screenshot 2019-03-18 at 20 38 03](https://user-images.githubusercontent.com/18581859/54540613-4b73b980-49be-11e9-9f65-515c17ec5c6d.png) | 

<img width="1030" alt="Screenshot 2019-03-18 at 20 35 35" src="https://user-images.githubusercontent.com/18581859/54540692-73631d00-49be-11e9-898b-c6236124fce1.png">

I am also not seeing the block element when I inspect the page. @Automattic/gutenpack for thoughts.

**Comment by simison** [comment]
What type of site was this? Jetpack site, simple site, at site?

**Comment by arunsathiya** [comment]
I tested on a simple site `gutenberg.wpcom.arunsathiya.blog` earlier, but I just tested on a Pressable-hosted Jetpack site, and a WordPress.com-hosted Atomic site. I am able to reproduce this behaviour on both.

**Comment by simison** [comment]
Confirmed with simple free site as well that the block doesn't load on the frontend, works well in the editor. Using twentysixteen theme.

**Comment by simison** [comment]
So this happens when none of the block inputs is modified when adding the field, thus limiting impact to users who are happy with default values the block provides. We'll prolly get this fixed for Jetpack 7.2 release and earlier for wpcom sites.

**Comment by roccotripaldi** [comment]
A fix for wpcom was deployed today in r-189110-wpcom

And [the fix for Jetpack sites](https://github.com/Automattic/jetpack/pull/11596) will go out in the 7.2 release

Feel free to verify the fix, and close the issue!

**Comment by arunsathiya** [comment]
Tested on a free, simple WordPress.com site. Tests well. Thanks, Rocco and team!
