### ISSUE TITLE
Portfolios share automatically to Facebook 

### ISSUE THREAD

**Issue by mishivee** [Automattic/wp-calypso#31538]
There is not a way for someone to opt out of sharing a portfolio. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/ connect your site to your Facebook page
2. Go to **My Site** -> **Portfolio** -> **Add**
3. Create a portfolio at https://wordpress.com/block-editor/edit/jetpack-portfolio
4. Hit **Publish** and see this https://d.pr/draw/3BSY4o/ and hit **Publish** again.
5. Check your Facebook page to see that the portfolio was indeed shared.

I was able to duplicate this with my test site mishiveenstra.home.blog and it shared the portfolio I created to my Facebook page (https://www.facebook.com/WordPress-Sharing-267147754218982)

* Blog post sharing option: https://d.pr/free/i/DnrQzL
* Portfolio sharing option: https://d.pr/draw/3BSY4o/
* Share to Facebook: https://d.pr/free/i/9iegmZ
* Test Site: mishiveenstra.home.blog
* Portfolio on test site: https://d.pr/free/i/tHqOPE

#### What I expected
I expected that you would see the option to not share to Facebook. 

#### What happened instead
When I published a portfolio, I didn't have the option to not share to Facebook. Instead I see this: https://d.pr/draw/3BSY4o/ 

Despite looking like Facebook isn't connected, it is. It shared to facebook after being published. 
#### Browser / OS version

Firefox/OS X 10.14

**Comment by iamgabrielma** [comment]
For reference, reported here: 1888153-zen
