### ISSUE TITLE
Accessibility: can't access Reader sidebar with keyboard

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3155]
It's not possible to access Reader sidebar links using the Tab key. In My Sites you can get there eventually after tabbing through all the main content, but because we use infinite scroll in the Reader stream, you never get there.

Ideally we'd tab to the sidebar first, then have a skipnav to get to the main content (related: #1990).

h/t @MichaelArestad for reporting.

**Comment by bluefuton** [comment]
Related: #694

**Comment by SiobhyB** [comment]
This is still an issue, changing from an "enhancement" to a "bug" as this prevents some people from being able to navigate WordPress.com.

**Comment by omidfi** [comment]
@SiobhyB  I just sent PR #22791  to address this. Not sure where to go from there.

**Comment by SiobhyB** [comment]
Thanks so much @omidfi! Happy to see that some people have already jumped into review that PR. :)

**Comment by gwwar** [comment]
@ryelle @omidfi can we close this one or did we need more work? Thanks!

**Comment by ryelle** [comment]
It can be closed - we switched the content order & added the skip link in #22884  👍
