### ISSUE TITLE
Onboarding: offer customers an “Other” option on site type step

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#31560]
### Scope

The site step options we offer to our customers might be limiting, and even make some consider if this is the right platform for them if we don't offer a way of customizing and defining their path.

With this in mind, here's a quick proposal to offer an “Other” option on which they can enter a customizable site type. The goal is to analyze how people use this option and refine the list above until we don't need this open-ended option.

See more background context in p5XAZ9-2dj-p2

#### v1

![demo-01](https://user-images.githubusercontent.com/390760/54628722-05762e80-4a6e-11e9-9f4d-f457e8903bce.gif)

#### v2

![proto-v4](https://user-images.githubusercontent.com/390760/54679273-cb08a200-4afe-11e9-9349-891a5e4d1e2c.gif)

### Notes

- The UI update happens on the same step without a URL change.
- Didn't include that here, but we might need to consider a “go back” link to see the initial site types list.
- Uses dotcom's latest iteration on the site type selection, where we replaced radios for entire clickable rows: https://github.com/Automattic/wp-calypso/pull/31400

### Feedback

Thoughts? @jeffgolenski @joanrho @AnnaMag @tyxla @fditrapani @shaunandrews

**Comment by jeffgolenski** [comment]
@keoshi I really like your utilization of current design patterns and that really smooth transition.

My only concern here is now that second input after the transition matches the site vertical very very closely. During the 2nd step (the site vertical / topic), I'm predicting that folks _may_ get confused thinking "didn't I just answer this?" 

Perhaps we can roll both steps into a single prototype to see the bigger picture to make sure it's a bit more clear. Or if there was some sort of magical design transition we could create that would keep the list sort-of still in-view? Just talking out loud now....

**Comment by fditrapani** [comment]
> My only concern here is now that second input after the transition matches the site vertical very very closely. During the 2nd step (the site vertical / topic), I'm predicting that folks may get confused thinking "didn't I just answer this?"

Good point @jeffgolenski. I like some of those suggestions too.

**Comment by keoshi** [comment]
> My only concern here is now that second input after the transition matches the site vertical very very closely. During the 2nd step (the site vertical / topic), I'm predicting that folks may get confused thinking "didn't I just answer this?"

Couldn't that be a sign that it doesn't make sense to ask this question if those concerns are raised just by having the same UI? Meaning, could they get the same level of customization and could we get the same data if they just picked “Other” and moved on the vertical selection?

**Comment by keoshi** [comment]
I've added a v2 above that retains the pre-selection context and an option to go back to the previous list.

**Comment by fditrapani** [comment]
> Meaning, could they get the same level of customization and could we get the same data if they just picked “Other” and moved on the vertical selection?

We're currently using this step to help us segment users so that we can prioritize our efforts for business users. In the future, I'd like to see us drop this step when we have effective coverage for all our segments with regards to previews and vertical search results. It'll take some time but we'll get there!

**Comment by keoshi** [comment]
@AnnaMag Ping so you can see this, since Luna's working at rethinking this at the moment. Can you weigh in and make sure our efforts on these aren't duplicated with dotcom's?

**Comment by jeffgolenski** [comment]
@keoshi I LOVE that v.2 that's really cool. To respond to your Q above:

> Couldn't that be a sign that it doesn't make sense to ask this question if those concerns are raised just by having the same UI? Meaning, could they get the same level of customization and could we get the same data if they just picked “Other” and moved on the vertical selection?

Aside from what Filippo mentioned above, this step is currently used internally for our research efforts and we want it to help customize the experience for the customer as well. I think the site type is a higher tier of categorization than the site topic. Personally, I want to utilize the "Other" option an a qualitative method to figure out if our site type list is pertinent for jetpack customers. 

I suppose we could eventually move to just having one of them and not both steps, but we'll have to team up with wpcomnux to make that decision. When we get to the point of customization, site type will be used to set up a more tailored experience, and I think the site topic can even further that eventually.

Example: 
Site type = "business." (super generic category) 
Site topic = "wedding photography" 

As a birthday cake we could set them up on a customization path for businesses - woocommerce, shop themes, etc. 

As a wedding cake, we can add the site topic into communication and even more customized messaging: "Welcome to Jetpack, make the most of your photography business with these great tools...."

I think they serve different purposes here.

**Comment by keoshi** [comment]
@jeffgolenski I don't disagree, and my question was mostly an exercise on questioning what we have so far from the perspective of someone looking at this for the first time. Food for thought. :)

My main question was if the confusion you alluded to would come solely from using the same UI pattern. Generally speaking using a familiar pattern is a good thing — do we want to make these two steps highly distinct in form to help our customers think of them in different ways?

I know the data we're analyzing will allow us to make this experience much more streamlined in the future, but what can we do right now to make these steps super clear for the customer? Especially when we're considering the introduction of a free form option like this one.

Quick-fire section:

> I think the site type is a higher tier of categorization than the site topic.

- Same for me, but is that clear for someone who hasn't seen the flow before and doesn't know what step is coming next?

> Personally, I want to utilize the "Other" option an a qualitative method to figure out if our site type list is pertinent for jetpack customers.

- If we introduce this “Other” option (which, again, I'm completely on board with so we can customize the flow according to _real_ data), what's preventing someone from clicking “Other” entering ”wedding photography” as their site type?
- Will that skew our analysis? Will we have to consider both data sets (type, topic) as one big one because customers might be confused by the terms we're using?

**Comment by tyxla** [comment]
Whatever we do here, I think we should be consistent with what we have on .com. We finally have some alignment there, and it's worth keeping and maintaining that in the future.

**Comment by AnnaMag** [comment]
@keoshi, wpcom will not use the other option in the end ( in principle, let's draft it for the Jetpack sites). Should we go for v2?

**Comment by keoshi** [comment]
Let's do it! For the placeholder, I'd suggest something like:

> e.g. Community, Directory, Governmental

**Comment by AnnaMag** [comment]
@keoshi, not meaning to drag the discussion, thinking/reading ^ a bit more:

> Will that skew our analysis? 

from the data perspective, this is really not great—missing data. I'd hope we do record it in some way.
I love the v2 version, also recognize that site type and topic could be potentially confusing. 

What are your thoughts on the pattern we used for the disconnect Other option:
<img width="591" alt="Screenshot 2019-03-22 at 12 15 14" src="https://user-images.githubusercontent.com/13561163/54819505-57040080-4c9c-11e9-838d-f5c5aff0706d.png">

Another idea/question: how about we list site topic under the v2 screen you proposed? so both questions at once.

**Comment by keoshi** [comment]
I like both ideas!

I'm also on the fence with offering an input as an option on the first screen. Would that make that option more visible to customers? Will that in itself skew the number of people selecting the other options?

Will they use it to input a “vertical”, and should we be ready to quickly deploy your second suggestion if so? If all we want is data, then we shouldn't even offer any selectable option and go for just the input, right?

**Comment by AnnaMag** [comment]
side note: it seems like icons will be merged soon for the site type step, so we will need an "other" icon for JP.

**Comment by keoshi** [comment]
@AnnaMag Where did you see that? Do you have a PR number?

**Comment by shaunandrews** [comment]
I was going to use the plan icons on the `site-type` step, but they don't map well to the segments, and the icons are different between wpcom and Jetpack. So, until we have some better icons, there won't be any icons on the `site-type` step. I'm super open to suggestions here :)

**Comment by jeffgolenski** [comment]
Launched: https://github.com/Automattic/wp-calypso/pull/32125#event-2262438549
