### ISSUE TITLE
Nightfall: Site Lock not Appearing

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#31574]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Activate the Nightfall scheme 
3. Navigate to the reader with a visible private site 
4. Click the share button beneath a post 

#### What I expected

Site lock to appear next to a private site, like it does on hover. 

#### What happened instead

Site lock invisible. 

![Screenshot_20190319-222007](https://user-images.githubusercontent.com/43215253/54645950-81d03800-4a95-11e9-9182-248b469e53ee.jpg)

**Comment by arunsathiya** [comment]
Not sure I am following the steps here, @torres126. 🤔 

Could you expand on this a bit more, please? Or could you share a larger screenshot of where this section appear?

**Comment by torres126** [comment]
Sorry, probably didn't help that it's so dark too! There's no lock next to the site title as the colour makes it invisible (the second site in the list is a private site). 

![Screenshot_20190320-074736](https://user-images.githubusercontent.com/43215253/54667549-83751c80-4ae4-11e9-8e79-a420d6342b60.jpg)

**Comment by arunsathiya** [comment]
I see what you mean now; thanks for reporting and for submitting a patch!
