### ISSUE TITLE
Sharing buttons not appearing after copying a post or page

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#31575]
#### Steps to reproduce
1. Create a page with the sharing buttons enabled.
2. Use the Jetpack's feature to "copy" that page.

#### What I expected
To see the share buttons as on the original page

#### What happened instead
When you visualize the page you'll notice that it's not displaying the sharing buttons

#### Browser / OS version

Chrome Version 72.0.3626.121 (Official Build) (64-bit), macOS Mojave 10.14.3 (18D109)

#### Screenshot / Video

![54492623-33a11600-4896-11e9-9f5f-877f26fe0ac9](https://user-images.githubusercontent.com/3696121/54647900-4b34f600-4a72-11e9-9dc6-b941763ea207.png)

#### Workaround
What I had to do to get the sharing buttons to show up was to switch to the "Classic" editor and click on "Update".

#### Context / Source

This problem is specific to WordPress.com sites, I tried with a WordPress.org site with Jetpack configured and couldn't replicate the issue.

Also this doesn't happen on simple sites when using the classic editor when you copy the post.

User report: 1865324-zen

#user-report

**Comment by tijosh** [comment]
Another report of this in #2008057-zen

**Comment by ajaykj** [comment]
Another report of this in #2060008-zen.

**Comment by wpericam** [comment]
Another report of this in hc-13183588

**Comment by kristarella** [comment]
Workaround that worked for me was to turn sharing buttons off on new page, save, then turn on again.

**Comment by AtrumGeost** [comment]
I wasn't able to reproduce the issue. I'm closing it.
