### ISSUE TITLE
Eventbrite page template can't be saved in the Block editor

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#31599]
We can follow these steps to setup an Eventbrite page template which will automatically display Eventbrite events on a website:
https://en.support.wordpress.com/eventbrite/ 

The page template assignment in step #6 must be done in WP Admin. We see the option to assign the Eventbrite Template regardless of whether we’re using the Block editor or the Classic editor while we're in WP Admin.

However, if we assign the template in the Block editor then the change fails to save. We have to revert to the Classic editor in order to save these changes.

Screenshot of the option to add the Eventbrite Template in Gutenberg:
![Screen Shot 2019-03-20 at 1 27 15 PM](https://user-images.githubusercontent.com/33190975/54709812-3c068480-4b14-11e9-8829-d75dddcb6a6a.jpg)

Screenshot of the error we see when saving the template (`Updating failed`):
![Screen Shot 2019-03-20 at 1 27 42 PM](https://user-images.githubusercontent.com/33190975/54709805-39a42a80-4b14-11e9-83c8-088426ea69b1.jpg)

**Comment by rossanafmenezes** [comment]
HC-9574858

user is having the same issue for the site restlessbear.com

**Comment by tbradsha** [comment]
13920161-hc

**Comment by lancewillett** [comment]
Closing as this feature is being removed.

From https://wordpress.com/support/eventbrite/

> This feature is no longer supported as of December 2019. Instead, you can use the fully-supported Eventbrite block: https://wordpress.com/support/wordpress-editor/blocks/eventbrite-block/
