### ISSUE TITLE
Eventbrite template doesn’t load content

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#31603]
The Eventbrite template can be setup in WP Admin on any theme after completing the steps in the setup guide here:
https://en.support.wordpress.com/eventbrite/ 

*_Note that this can only be setup in the Classic editor, it is not possible to use this template on the Block editor even though the option does appear, it will fail to save._

The setup guide notes that it can take up to 10 minutes for the events to appear on the page, but in my and a user’s experience today the events do not appear on the page automatically once the steps on this guide are followed.

The only way we were able to populate events on this page was by going to Calypso, changing the post template there (I returned the post to the default template), then returning to WP Admin and re-applying the Eventbrite template. Toggling between the templates in WP Admin is not sufficient.

#### What I expected
For the Eventbrite-templated page to begin loading published events within 10 minutes of creation.

#### What happened instead
No events appeared until I performed the page template swap.

#### Context / Source
#user-report in 1892411-zen

**Comment by sandymcfadden** [comment]
I have another report of this here 1967829-zen

Nothing I've tried have I been able to get the events to show. The events seem to work for the eventbrite widget though. 

Calypso doesn't give the option to change the page template at all. You can't change it from the [block editor.](https://github.com/Automattic/wp-calypso/issues/31599) The only place to set it is in WP Admin classic editor. The template seems to be applied to the page but the events won't show.
