### ISSUE TITLE
Themes: Sheet feature list

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3163]
List a theme's features.

**TODO:**
- [ ] List features in token pill style.

**UI:**
![screen shot 2016-01-21 at 13 01 29 copy](https://cloud.githubusercontent.com/assets/215074/12884814/b5676dc6-ce58-11e5-8cbe-488f5b75dc84.png)
![screen shot 2016-01-21 at 13 00 30](https://cloud.githubusercontent.com/assets/215074/12884840/da324068-ce58-11e5-94d3-ce719f50abaa.png)

**Comment by folletto** [comment]
Closing, this was done in #4021
