### ISSUE TITLE
People: Update dropdown component to use radio buttons

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31638]
![image](https://user-images.githubusercontent.com/2124984/55015245-e114d780-4fc2-11e9-92ef-11730fc3a2a0.png)

Found on the invite screen and edit user screens.

At first we thought this was an out of date pattern and needed the `Dropdown` component, but @drw158 suggested it would be better to use radio buttons for usability/accessibility.

**Comment by drw158** [comment]
Yep, it's fine to use the native `select` element, but in this case we didn't need it since I think there were fewer than 5 items.

**Comment by sixhours** [comment]
Good catch @lancewillett ! This got migrated from a Trello board but it appears I forgot to bring the image over. I've added it for reference. We don't have an "After" image for this one yet, but I expect the corresponding PR will when I get to it!
