### ISSUE TITLE
Jetpack Connect: Site Type and Vertical suppression for reconnections...

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#31631]
![Screen Shot 2019-02-26 at 9 06 20 AM](https://user-images.githubusercontent.com/214813/54759390-5dbf4480-4bc4-11e9-8a61-ca553f5c8785.png)

Per a conversation in slack with @tyxla, @eliorivero, and others, Our Jetpack site type and vertical steps should be suppressed (hidden) for sites that:

1) Are reconnecting
2) We can see have already provided this info to us in general
3) Non-primary / non-admin users 

cc @keoshi @AnnaMag

**Comment by keoshi** [comment]
Big **+1** on this!

Couple of quick questions:

> Are reconnecting

- Should we introduce any time conditionals here? I'm thinking the onboarding flow could be useful if their site hasn't been active for the past X months and they're reconnecting again.
- Also, what are the current rules? Will an existing active site ever see the onboarding flow if they try to reconnect? Take my blog for instance: I've set up Jetpack a long time ago, but wouldn't mind going through a flow that recommends me certain benefits if I were to cycle my connection for some reason (and hadn't seen the flow before ofc).

> We can see have already provided this info to us in general

- Will the minimum requirement be that they've already filled at least one of the steps?

**Comment by tyxla** [comment]
> Should we introduce any time conditionals here?

FWIW, we totally can, from Jetpack 7.2 on - we'll have the assumed site creation date, that could help us.

> Also, what are the current rules? Will an existing active site ever see the onboarding flow if they try to reconnect?

Yes. They'll currently always see it, regardless of whether they connect for the first time or reconnect.

The only necessary conditions to be matched are:
* They're admins
* Their Jetpack version is relatively new (>= 7.1 alpha).

There are also some exceptions for various flows in which users won't see these steps, for example:

* Our SSO flow.
* Woo connection flows.
* Legacy JPO connection flow.
* Jetpack start / partnership connection flow

Couple of questions from me as well, @jeffgolenski @keoshi:

> We can see have already provided this info to us in general

We're planning to ship the skip buttons soon. Does skipping count as "providing"?

> Non-primary

Just to confirm: does that refer to any user that's not the connection owner?

> Are reconnecting

If they reconnect but haven't provided those so far, should we ask them or not?

Generally, how would those rules you suggested work when combined together? I could use some clarification before getting to actual coding.

**Comment by keoshi** [comment]
> Does skipping count as "providing"?

Following the logic we're applying here, I'd say yes. If people considering skipping a better option than filling out details, then they likely wouldn't want to be bothered again with it.

> If they reconnect but haven't provided those so far, should we ask them or not?

If they didn't fill any steps and didn't skip them, I think we should present the flow.

**Comment by tyxla** [comment]
So if I understand this correctly, in addition to what we have already, we'd only skip these steps if we have data from previous submissions. Everything else should stay the same.

> Following the logic we're applying here, I'd say yes. If people considering skipping a better option than filling out details, then they likely wouldn't want to be bothered again with it.

Hmm, the current version of skipping we're suggesting is literally skipping, and not saving an empty value. So we wouldn't be able to differentiate between the ones who skipped, and the ones who never submitted that value. Should we change that?

**Comment by keoshi** [comment]
Good point. I think so, but I'll @jeffgolenski weigh in on this.

Also, would it make more sense to add a skip option only on the first step with something like:

> I know what I'm doing, skip this setup.

I know we've discussed this in the past but seems extra valuable here since it:

- Provides a clear way for users to skip the flow entirely.
- Allows us to set that “empty” value more clearly.
- Sets the correct expectations in terms of value provided by these steps.

**Comment by arunsathiya** [comment]
+1 on this! I ran into this when recycling connection on my test site on Pressable. Here is what the scenario looked like:

- I had to disconnect for some reason.
- Started a reconnection process, and that's when I first came across the new onboarding flow (for this site)
- Choose `Blog`, and none of the site type recommendations on the next step matched my needs (the site was test purposes)
- Typed `test` manually, and chose the last option from the list.
- Completed connection.
- Had to disconnect again.
- Reconnected, and during this process, came across the onboarding flow for the second time.

So, +1 on introducing time conditionals! If I am reconnecting within the next few days/weeks, I feel that suppressing the flow would be helpful. Perhaps if I am reconnecting after a couple of months/a quarter, I wouldn't mind seeing the flow again. 

If it's not a big challenge, it would also be cool to see different flow; something along the lines of, 

- "We see that you are reconnecting Jetpack. Are you building something different now?"
- "Has your goal changed recently?"

>If they reconnect but haven't provided those so far, should we ask them or not?

I am not sure how I could have skipped providing my answers. There was no skip button, but I like to see something like this - https://github.com/Automattic/wp-calypso/issues/31115#issuecomment-472877725 (ability to speed through the connection flow by just clicking on "Continue" when I don't have any answers to choose)

Just sharing my experience through the process as another Jetpack user. :) Was about to file a report for suppressing flow for reconnections, and came across this issue.

**Comment by tyxla** [comment]
I've started giving this a thought, but I'd appreciate a final description of how you'd expect it to work @jeffgolenski.

**Comment by tyxla** [comment]
cc @Automattic/luna - this is the one I mentioned that should be prioritized.

**Comment by simison** [comment]
We've decided to hide these steps from the Jetpack flow for now (paObgF-k1-p2)
