### ISSUE TITLE
Customizer and Gutenberg exit signs are different.

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31639]
**Gutenberg:** 
<img width="119" alt="Screen_Shot_2019-03-15_at_5 08 39_PM" src="https://user-images.githubusercontent.com/2124984/54764070-72540a80-4bcd-11e9-998d-1f3fc05af33e.png">

**Customizer:**
<img width="85" alt="Screen_Shot_2019-03-15_at_5 08 56_PM" src="https://user-images.githubusercontent.com/2124984/54764072-72540a80-4bcd-11e9-9630-f3897804e9a9.png">

We should use the same symbol for both for a consistent user experience. I'd expect to follow Gutenberg's lead, but consider opening a ticket for this in core since it's a core issue.

**Comment by sixhours** [comment]
...actually it's not a core issue. :) Core doesn't use the Calypso-ified exit button since it's still based in /wp-admin. For now, we'll just consider this change for WP.com.

**Comment by sixhours** [comment]
I started a patch at D26035-code to swap out the symbol in the Customizer. 

**Before**

<img width="571" alt="Screen Shot 2019-03-26 at 1 50 28 PM" src="https://user-images.githubusercontent.com/2124984/55020922-3e625600-4fce-11e9-9f2e-e4c60513aff5.png">


**After**

<img width="626" alt="Screen Shot 2019-03-26 at 1 25 12 PM" src="https://user-images.githubusercontent.com/2124984/55020936-43bfa080-4fce-11e9-9e4f-2aa66e674126.png">

**Comment by sixhours** [comment]
Fixed in r189774-wpcom

**Comment by zdenys** [comment]
@sixhours I found the above after submitting #34121 some time ago. Would it be possible to reverse the above change to get back the `X` exit button for the Customizer? It would confuse users less. I notice it very frequently during Concierge sessions.
