### ISSUE TITLE
"My Sites" menu confusion

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31647]
<img width="351" alt="Screen_Shot_2019-03-16_at_12 50 19_PM" src="https://user-images.githubusercontent.com/2124984/54775701-e352ec80-4be4-11e9-9c6a-29fba2b8d3cc.png">

It's strange that when you're editing a site you have to click "My Sites" to open the slide out menu to access your site settings.

If you actually want to access your sites you have to click again on "Switch site."

The name for "My Sites" should probably be something that's descriptive of what you actually get when you click, like "Dashboard" or "Settings".

**Comment by dezzie** [comment]
What about Site Builder? I like the idea of "Dashboard" but it feels like it leaves out all of the editing and styling. "Settings" feels like a small part of the whole thing too.

My Site:
<img width="705" alt="Screen Shot 2019-04-16 at 4 21 16 PM" src="https://user-images.githubusercontent.com/1301932/56245005-e9ad7a80-6063-11e9-9aa8-bca1e3e3449f.png">

or Site Builder:
<img width="773" alt="Screen Shot 2019-04-16 at 4 21 32 PM" src="https://user-images.githubusercontent.com/1301932/56244992-e5815d00-6063-11e9-9252-4344bb35fc5e.png">

**Comment by alaczek** [comment]
How about "Site Manager"?

**Comment by donpark** [comment]
Weird but in a passive way. Most users have only one site so this is more a curiosity and use of plural serves as:

- hint where other sites can be accessed from
- a gentle suggestion to create more sites
- create their own site if they're not the site owner

**Comment by sixhours** [comment]
Good to note that the wording is contextual; it's "My Site" when one has a single site, and changes to "My Sites" when one has multiple sites.

**Comment by sixhours** [comment]
Let's hold off on doing anything with this until we've looked at the masterbar as a whole.

**Comment by lancewillett** [comment]
Closing this one since there isn't an actionable next step. 

Agree on revisiting as part of a larger rethink of the top navigation.
