### ISSUE TITLE
Checklist: Too many shades of green!

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31649]
<img width="968" alt="Screen_Shot_2019-03-14_at_1 27 21_PM" src="https://user-images.githubusercontent.com/2124984/54776020-9c192b80-4be5-11e9-9624-27b4de09caeb.png">

The green used for the checklist progress indicator is different from that in the illustration, and also different from the green upgrade notice in the sidebar. Some consistency would be ideal here.

**Comment by drw158** [comment]
The upgrade notice is using `color-success` which is right. The illustration is using a completely wrong green, baked into the svg. The Gauge component looks like it's setting wrong colors in the html, not using variables.

**Comment by sixhours** [comment]
@drw158 I could use some Muriel guidance here. Should we use the `--color-success` variable color for the gauge and illustration? Or choose a different color since those aren't success messages?

**Comment by sixhours** [comment]
The Gauge component adds the color as an inline style; we can use a CSS var if we use `!important` to override the inline style.
