### ISSUE TITLE
Incorrect information displayed for mapped domains that can't be transferred

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#31648]
#### Steps to reproduce
1. Map a TLD that can't be transferred to WordPress.com (e.g., .co.uk)
2. Click "Add" next to "Domains"
3. Click "Use a domain I own"
4. Choose "Transfer to WordPress.com"
5. Enter that same mapped domain name
6. Click Transfer

#### What I expected

To receive an error saying this domain can't be transferred:

<img width="940" alt="Screen Shot on 2019-03-21 at 14-21-06" src="https://user-images.githubusercontent.com/7596032/54775554-a1c24180-4be4-11e9-8e0d-c9f41ae7c06a.png">

#### What happened instead

Received an error saying the domain is already mapped to a WordPress site:

<img width="1530" alt="Screen Shot on 2019-03-21 at 14-22-00" src="https://user-images.githubusercontent.com/7596032/54775604-b7d00200-4be4-11e9-9e40-8e44ebc2eb60.png">

This causes confusion as the user isn't informed that the domain isn't eligible for transfers. 

#### Context / Source

This came up in 4842940-hc when the user was trying to transfer their .co.uk domain in. The message left them and me confused since the error was a false report (a mapped domain can be transferred). It wasn't until I realized the extension couldn't be transferred that we could connect the dots.

**Comment by klimeryk** [comment]
A crucial bit of information is that this only occurs if the domain the user is trying to transfer in is _already_ mapped on WPCOM.
Otherwise, the correct notice is shown:

<img width="1066" alt="Screenshot 2019-03-22 at 23 56 39" src="https://user-images.githubusercontent.com/3392497/54858688-2654b300-4cfe-11e9-9a7f-6ca35c944f07.png">

**Comment by Gilmoursa** [comment]
Happened with another user with a _.us_ domain.

**Context / Source**

5523275-HC

**Comment by marcuswisecaesar** [comment]
Happened with another user with a .ca domain.

Context / Source

11263679-hc

**Comment by nickpagz** [comment]
Another report, for an .se domain. This confused the user, and added a support interaction that wasn't required if the messaging was clear. 

#10727712-hc

**Comment by nickpagz** [comment]
Another one, a .co.za domain this time.
#17815135-hc
