### ISSUE TITLE
Themes: Related themes

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3164]
We want to show related themes on the theme sheet page.

**TODO:**
- [ ] Get related themes from details endpoint, using ES?
- [ ] Show two related `Theme`s
- [ ] Add footer

**UI:**
![screen shot 2016-01-21 at 19 06 55](https://cloud.githubusercontent.com/assets/215074/12884933/7defe7aa-ce59-11e5-95e2-9b2e900fff0c.png)

**Comment by folletto** [comment]
We decided to proceed on this incrementally:

* Step 1 (MVP) — We take always two themes from a subset of hard-coded themes. With this we'll check if the feature is used and how much.
* Step 2 (Related API) — We create a proper API that returns the related themes based on tags, swapping the subset done in Step 1.

Step 1 is the only piece for M4.

**Comment by alaczek** [comment]
> Step 1 (MVP) — We take always two themes from a subset of hard-coded themes.

I came up with a list of 10 candidates that present a cross-section of our theme offering:
- Twenty Sixteen
- Rowling
- Hemingway Rewritten
- Gazette
- Ecto
- Isola
- Edin
- Sela
- Pique
- Harmonic

Hope this helps!

**Comment by seear** [comment]
@budzanowski: For the theme data, you can do something very similar to how it is done in signup here:
https://github.com/Automattic/wp-calypso/blob/master/client/signup/steps/theme-selection/index.jsx#L29
(and note the screenshot url below).
So no data fetching will be necessary, which will keep it nice and simple :D

**Comment by budzanowski** [comment]
Nice hint @seear!

**Comment by folletto** [comment]
Closing, this was done in #5629.
