### ISSUE TITLE
Infinite Scroll Working Inconsistently on archive pages across Sites and Themes

### ISSUE THREAD

**Issue by AMcGrady** [Automattic/wp-calypso#31657]
#### Steps to reproduce
1. Activate Wanderer theme on site
2. Add Archive Widget 
3. Have at least 8 posts in a given month
4. Enable Infinite Scroll
5. Click on a month with 9+ posts on the Archive Widget in the live site

#### What I expected
All posts for the given month to be displayed on Archive page.

#### What happened instead
Inconsistent results. On my test site:
https://amwpapp060718.com/2018/07/
only 7 of 9 posts are displayed.

Same thing on user's site here:
http://thedailynugget.blog

but on this site:
https://alex27pl.wordpress.com/

all posts display

 #user-report

**Comment by lancewillett** [comment]
Thanks @AMcGrady. This is a theme issue rather than something with Calypso, right? (the site management tool for logged-in site owners).
