### ISSUE TITLE
Domains: Primary domain change success notice should disappear on switching to another site

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#31673]
#### Steps to reproduce 

- Visit https://wordpress.com/domains/manage 
- Choose a site
- Update the primary for the site, assuming there are at least two domains on the site
- Click on the site switcher on the left and visit another site

#### What is expected 

The success notice from the primary domain change on the first site is no longer shown.

#### What happens instead 

The success notice from the primary domain change on the first site continues to be shown.

#### Screenshots indicating this behaviour

![Screenshot 2019-02-11 at 02 33 36](https://user-images.githubusercontent.com/18581859/54817871-f1c10700-4cbd-11e9-8e54-46e20cfd9900.png)
![Screenshot 2019-02-11 at 02 33 41](https://user-images.githubusercontent.com/18581859/54817872-f2599d80-4cbd-11e9-8707-2cfc39cd4acd.png)
![Screenshot 2019-02-11 at 02 33 46](https://user-images.githubusercontent.com/18581859/54817874-f2599d80-4cbd-11e9-800b-33d65daca595.png)

The screenshots may be viewed in the order shown. 

cc @Automattic/cobalt 

#manual-testing

**Comment by arunsathiya** [comment]
Related: When I attempted to click `Undo`, a notice `This domain can't be set as primary for the requested site.` was shown - which I think is normal given that the other domain is not associated with the currently active site.

<img width="1673" alt="Screenshot 2019-03-22 at 16 20 34" src="https://user-images.githubusercontent.com/18581859/54818110-86c40000-4cbe-11e9-8056-194cd7f2cb50.png">

**Comment by klimeryk** [comment]
Nice catch!

The fix _should_ not be too complicated. Looks like we store the notice in the component's state (https://github.com/Automattic/wp-calypso/blob/89ab4b4eeab28e2d9c8f7f66ca9b2e5d19ff8d91/client/my-sites/domains/domain-management/list/index.jsx#L63) and don't clear it when the site changes.

So, from the top of my head (I'm certain that in the end it will not be _that_ simple) the solution is to add a `componentDidUpdate` (https://reactjs.org/docs/react-component.html#componentdidupdate) method in the component and check if the `siteId` prop has changed. If it did, call the `this.hideNotice()` method.

@arunsathiya, I see you've been busy with Calypso PRs (impressive stuff!), want to take a stab at this one? Happy to pair program on it if you want 🙇
