### ISSUE TITLE
Jetpack Connect: clean style duplication

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#31670]
Sequel to https://github.com/Automattic/wp-calypso/pull/31297. 
Code improvement -> clean up style duplication https://github.com/Automattic/wp-calypso/pull/31297#issuecomment-475237849.

**Comment by tyxla** [comment]
One thing I've noticed and I think it'll be resolved with the componentization of this one is that we have legacy colors on focus for example:

![](https://cldup.com/VArHaeWKJF.png)

An issue like this wouldn't happen if we used the same components for all steps. For example, here's how the focus colors are on the site type step:

![](https://cldup.com/2-J6W50Psm.png)

So I'd say this isn't really a Low priority issue, but rather a Normal one - considering that it affects the consistency of the flow. In the context of the recent color updates we did (they were a separate project), I think this is important.

What do you think @AnnaMag?

**Comment by tyxla** [comment]
These steps are already gone, closing.
