### ISSUE TITLE
JP Onboarding: make title + subtitle consistent across the flow

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#31676]
_This was copied from https://github.com/Automattic/wp-calypso/pull/31297 where the introduction of a user-type step sparked these thoughts:_

Notes for @jeffgolenski, @joanrho, and myself: when introducing the user-type, we'll have to step back and see what kind of improvements we want to do throughout the entire flow because:

1. Site type: in addition to instructions for the step, it also includes:
  - A tagline for Jetpack: `High performance. Solid security. Your site, just better.`
  - A description for the entire flow: `To get started, tell us a little bit about your site goals.`
2. Site topic:
  - The question could be improved to match the clarity on the others: `Tell us about your website`
  - The description — `Enter a keyword and we'll start tailoring a site for you.` — will stop making sense if we add the site ownership at the end.
3. Site ownership:
  - Do we need a description here? It's kind of the only one that doesn't have it.

Let's block out some time to look at the entire flow with fresh eyes and make some changes here.

I like @shaunandrews' [suggestion here](https://github.com/Automattic/wp-calypso/pull/31403#issuecomment-474578852) of making the brand tagline much smaller on step 1, and then utilize a title and description consistently across all the steps.

Here are my suggestions for that:

> What kind of site do you have?
> To get started, tell us a bit more about your website.

> What's the main purpose of your site?
> Select a category or enter a keyword that matches your site.

> Are you setting up the site for yourself or someone else?
> In no time, we'll start tailoring a site for you.

**Comment by AnnaMag** [comment]
proposal for updating the copy of the Site Type -> https://github.com/Automattic/wp-calypso/pull/31706.

**Comment by tyxla** [comment]
All the steps that we're referring to above have been removed from the Jetpack onboarding flows already, so this one can be closed, too.
