### ISSUE TITLE
Sites: Default site icon could be improved

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31693]
![image](https://user-images.githubusercontent.com/2124984/54840900-6424ed80-4ca4-11e9-9500-99bc15e33322.png)

> That’s always made me think “dinosaur egg” and it never communicated “site” to me.
— John

**Comment by sixhours** [comment]
I flagged this for Muriel because I think we should replace this with an icon of some kind. Does that fly with Muriel guidelines, and are there any icons in the Material realm that fit the concept of "default site icon"? (I know we're waiting on licensing for those, just thinking ahead.)

**Comment by sixhours** [comment]
I was thinking about the Home icon from Dashicons in the meantime: https://developer.wordpress.org/resource/dashicons/#admin-home

**Comment by drw158** [comment]
Until we fully integrate Material icons, I think the `themes` icon in Gridicons is the best choice here. Even, better we should make a new icon without the "multiple" characteristic and remove the outline around the icon to signify "single site".

https://github.com/Automattic/gridicons/blob/master/svg-min/gridicons-themes.svg

**Comment by drw158** [comment]
I just opened a PR to add a new icon https://github.com/Automattic/gridicons/pull/302

**Comment by sixhours** [comment]
This was deployed in Automattic/gridicons#303
