### ISSUE TITLE
Signup: Overzealous error message on email field

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#31694]
<img width="559" alt="Screen_Shot_2019-03-14_at_1 03 44_PM" src="https://user-images.githubusercontent.com/2124984/54841021-b403b480-4ca4-11e9-9450-d2f764a44507.png">

At the moment you are about to type '@' it shows you the error message in red warning text; doesn't give the user a chance to type in a correct email address, which is off-putting.

**Comment by scruffian** [comment]
What's the expected behaviour here? We currently wait for the user to not type for 1.5 seconds before we do a validation check. Should we extend this to, say, 2 seconds, or not check at all until the user submits the form?

**Comment by sixhours** [comment]
> What's the expected behaviour here? We currently wait for the user to not type for 1.5 seconds before we do a validation check. Should we extend this to, say, 2 seconds, or not check at all until the user submits the form?

I feel like waiting to do a validation check until focus shifts away from the field would be better; although I see the benefit to validating while focus is still on that field, it feels a bit mean (for lack of a better word) to throw a red-level error so quickly. Thinking of folks who type slowly, hunt-and-peck style, or who have cognitive difficulties, who'll probably need more than 1.5-2 seconds to type in an email address.

**Comment by scruffian** [comment]
Yeah I can see that too. This is more of a complex change, as we are using a generic form validation library written for Calypso.
