### ISSUE TITLE
Jetpack Backups: Credentials card looks broken

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#31700]
#### Steps to reproduce
1. Enable Rewind on a site in vpmc 
2. Clear any credentials 
3. View this card

![image (2)](https://user-images.githubusercontent.com/7129409/54853786-300ef400-4cc7-11e9-9ca8-62e214b672d3.png)

#### What I expected
It to be styled appropriately 

#### What happened instead
Looks broken

**Comment by simison** [comment]
cc @jsnajdr in case this is from CSS refactoring.

**Comment by jsnajdr** [comment]
Thanks for the ping @simison ! It's indeed a regression from the CSS refactoring. Fixed by #31918.
