### ISSUE TITLE
List block: Unable to delete the last bullet 

### ISSUE THREAD

**Issue by suyogyashukla** [Automattic/wp-calypso#31717]
#### Steps to reproduce

1. Add a list block.
2. Add some items, let's say, 3.
3. Make sure the third item is empty and publish the page.
4. Once published, remove the third bullet (empty item) 

#### What I expected

- For Calypso to detect the change and allow updating the page.

#### What happened instead

- The change is not detected at all and there's no way to update the page after removing the empty bullet. 

#### Browser / OS version

- Brave browser Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)/Mac OS 10.14.3 

#### Video

https://cld.wthms.co/49OOb6

### User Report

#11401609-hc

**Comment by arunsathiya** [comment]
I can confirm this happens on WordPress.com, but it is a core Gutenberg issue. This is reproducible on a local install of Gutenberg, on jurassic.ninja and on a site on Pressable.

I am closing this issue in favor of https://github.com/WordPress/gutenberg/issues/13864#issuecomment-476159111

But, if I am misreading something, feel free to reopen @suyogyashukla!
