### ISSUE TITLE
Simple Payments: Improve buttons list interface

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#31736]
It's possible to create many buttons for a site. In the near past, [we've had some](https://github.com/Automattic/wp-calypso/issues/24436) issues when the number of buttons was greater than 20 buttons. So [we implemented a quick solution](https://github.com/Automattic/wp-calypso/pull/31640) increasing the buttons to show until 100 units.
Clearly, a solid fix it will require more work if we want to handle rightly the cases when customers create hundreds of buttons. Among some options, add pagination seems to be a good (and kinda easy) solution to implement.

**Comment by scalarbane2** [comment]
Hi @retrofox can I get a screenshot of the current one? Looking into this issue now.

**Comment by lancewillett** [comment]
@scalarbane2 Note that retrofox is on extended leave (3 months).
