### ISSUE TITLE
Update site card to match Megs' mockup

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31765]
RE: https://github.com/Automattic/wp-calypso/pull/31742

![](https://d1jfzjx68gj8xs.cloudfront.net/items/2d02350j0l1c463v3q1A/Screen%20Shot%202019-03-26%20at%2010.40.22%20AM.png)

**Comment by drw158** [comment]
I think this can be done for the next iteration, since I think this would required reworking the current switch site pattern. This can be used until then:


![Screen Shot 2019-03-26 at 11 59 16 AM](https://user-images.githubusercontent.com/618551/55017470-c8a2be00-4fbe-11e9-9c30-bee93f7dc724.png)

**Comment by drw158** [comment]
Responsive layout if there's room to show the whole url:

![Screen Shot 2019-03-26 at 12 45 49 PM](https://user-images.githubusercontent.com/618551/55020566-191d1a00-4fc5-11e9-9e8d-8e26ec4ec98e.png)

Different options for private site icon 

![Screen Shot 2019-03-26 at 12 46 42 PM](https://user-images.githubusercontent.com/618551/55020648-3fdb5080-4fc5-11e9-82fe-6180c18d396d.png)

**Comment by davemart-in** [comment]
OK, sounds good! I'll punt this one in the Nav Drawer Redesign project: https://github.com/Automattic/wp-calypso/projects/81

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
