### ISSUE TITLE
Update back navigation on mobile web

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#31772]
This is tangentially related to the redesign of the nav drawer. There is a component on mobile that allows you to navigate back after tapping on a menu item.

Current:

![Screen Shot 2019-03-26 at 12 43 01 PM](https://user-images.githubusercontent.com/618551/55020378-b75cb000-4fc4-11e9-852a-1115f0ca5178.png)

**Comment by drw158** [comment]
Proposed design:

![Screen Shot 2019-03-26 at 12 40 37 PM](https://user-images.githubusercontent.com/618551/55020391-bf1c5480-4fc4-11e9-9c10-58ce027506de.png)

**Comment by davemart-in** [comment]
@drw158 just to clarify, so you're suggesting dropping the site avatar, and then flipping the order and styles of the section name and the site name?

**Comment by drw158** [comment]
Yep. Dropping the avatar will make it consistent with the Calypsofy back navigation.

**Comment by drw158** [comment]
Here's my proposal that aligns with Material as best as I could find 

![Screen Shot 2019-03-28 at 1 59 46 PM](https://user-images.githubusercontent.com/618551/55185202-d3e21f00-5161-11e9-8877-e9f8fddd4c9b.png)

**Comment by davemart-in** [comment]
Updated in: https://github.com/Automattic/wp-calypso/commit/ef3f327fe236b8630f08b50e5adae30b83faf2dc

Before: https://cl.ly/366181e5e690
After: https://cl.ly/2d8800f199d5

Note: I also addressed some linting issues. See: https://cl.ly/07dacf96db6c

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
