### ISSUE TITLE
Nav Drawer: update Me design

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#31770]
Update look and feel on Me left nav menu to match My Sites section changes

**Comment by drw158** [comment]
Icon replacements:

![Frame 3](https://user-images.githubusercontent.com/618551/55019567-289b6380-4fc3-11e9-8d77-ae9573d64f94.png)

**Comment by davemart-in** [comment]
Note: We're currently waiting on word from Google to indicate that Material icons are GPL compatible: https://a8c.slack.com/archives/CGVQWH08H/p1553697844065000

**Comment by johnmaeda** [comment]
@drw158 Can this be closed now?

**Comment by drw158** [comment]
It hasn't been implemented yet so this issue should stay open. But yes, we can do this now that we have the green light to use the icons.
