### ISSUE TITLE
Show external link icon

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31777]
Links that open in a new tab should still show the external link icon on the right: 

![](https://d1jfzjx68gj8xs.cloudfront.net/items/213U473u2H1z3W3n2D3I/%5Ba51ac79bbeb190f38596eead775bd381%5D_Screen%2520Shot%25202019-03-26%2520at%25206.23.41%2520AM.png)

**Comment by griffbrad** [comment]
This is covered by 4545e3b on PR #31742

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
