### ISSUE TITLE
Prevent height change on section header click

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31774]
RE: #31742

When you click to expand a section that the height/padding around the section header should not increase by a pixel or two: 

![](https://d1jfzjx68gj8xs.cloudfront.net/items/3O1E222i2f1O3J2T1r3r/Screen%20Recording%202019-03-26%20at%2006.29%20AM.gif)

**Comment by jffng** [comment]
This issue can be resolved in `client/layout/sidebar/style.scss`. Removing the box-shadow (currently line 210) on the toggled state does the trick, if the goal is to keep the hover state and active state consistent:

![toggle_height](https://user-images.githubusercontent.com/5375500/55086041-1a5e4d80-507e-11e9-865a-97da27073add.gif)

cc @allancole

**Comment by davemart-in** [comment]
Updated in: https://github.com/Automattic/wp-calypso/commit/26c7040541c3281cb10430716048bd7269b4495d

Before: https://cl.ly/17bed1707473
After: https://cl.ly/ac3a117a57f2

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
