### ISSUE TITLE
Remove StatsSparkline from stats menu item

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31778]
when stats are flat, it looks like there is a horizontal line here by mistake: 

![](https://d1jfzjx68gj8xs.cloudfront.net/items/0c1y1Q1j2b1T161r1S2X/%5Bb3b12bf15eb2e03f6879a9708c7693e6%5D_Screen%2520Shot%25202019-03-26%2520at%25206.15.48%2520AM.png)

@jsnajdr suggested we might just consider [removing this sparkline](https://github.com/Automattic/wp-calypso/pull/31742#issuecomment-476647957) altogether.

**Comment by davemart-in** [comment]
Leaning towards punting this one. Discussing it here: https://a8c.slack.com/archives/CGVQWH08H/p1553628681037700

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
