### ISSUE TITLE
Nav Drawer: update Reader design

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#31771]
Update look and feel on Reader left nav menu to match My Sites section changes

**Comment by drw158** [comment]
Icon replacements:

![Frame 2](https://user-images.githubusercontent.com/618551/55019636-48328c00-4fc3-11e9-8866-c874151972f8.png)

**Comment by drw158** [comment]
For Lists and Tags, we’ll need to align the caret icon on the right

![Screen Shot 2019-03-26 at 12 33 23 PM](https://user-images.githubusercontent.com/618551/55019678-5c768900-4fc3-11e9-9172-b672840ac018.png)

**Comment by davemart-in** [comment]
Note: We're currently waiting on word from Google to indicate that Material icons are GPL compatible: https://a8c.slack.com/archives/CGVQWH08H/p1553697844065000

**Comment by alaczek** [comment]
The icons in the Reader are now as in the screenshot. @drw158 - could you clarify if your screenshot represents what needs to change, or how things should be (if it's the latter can we close this issue)? With the lists and tags, the caret icon is on the left, are you suggesting it's moved to the right?

**Comment by shaunandrews** [comment]
Made a PR to resolve this ^^

@drw158 I couldn't find the icon you had for conversations. I went with the `chat` icon for now.

**Comment by drw158** [comment]
@alaczek Sorry, yes I believe the caret icon should be aligned to the right to be consistent with the My Sites nav drawer.

**Comment by shaunandrews** [comment]
Working on the caret icon for lists/tags over in #34051 — gonna take some work though. CSS/Markup needs a bit of a refactor to avoid duplicative code.
