### ISSUE TITLE
Add margin to bottom of nav drawer

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31775]
RE: #31742

We should maybe add a little extra margin at the bottom of the nav drawer so that the browser address info toaster message doesn't sit half way over the "Manage" link: 

![](https://d1jfzjx68gj8xs.cloudfront.net/items/2B08233v2p162c352z3s/Screen%20Recording%202019-03-26%20at%2006.26%20AM.gif)

**Comment by davemart-in** [comment]
Updated in: https://github.com/Automattic/wp-calypso/commit/01e931cd8841002d7a5f8142ebdebd913c2c9661

Before: https://cl.ly/5b1b4b5f6eab
After: https://cl.ly/2f3ccf3e7c89

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
