### ISSUE TITLE
Add Material icons to My Sites left nav menu

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31782]
We just need to update the icons that Dave W selected for the My Sites nav drawer.

**Comment by davemart-in** [comment]
Note: We're currently waiting on word from Google to indicate that Material icons are GPL compatible: https://a8c.slack.com/archives/CGVQWH08H/p1553697844065000

**Comment by davipontesblog** [comment]
Closing this issue based on status update in the [Nav Drawer Redesign project](https://github.com/Automattic/wp-calypso/projects/81).
