### ISSUE TITLE
Signup: Poor contrast on signup through Gravatar

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#31785]
#### Steps to reproduce
1. Start logged out at https://gravatar.com
2. Click "Create your own Gravatar"

#### What I expected
A clearly visible signup page like I get with regular signups

#### What happened instead
I see this:
![Screen Shot 2019-03-26 at 2 08 02 PM](https://user-images.githubusercontent.com/3476361/55030014-0a3c6480-4fd1-11e9-95ca-e49327eab960.png)

Note the grey is really hard to see against the deep greenish blue. On other signup pages, the text is white and the box shape is normal. **This _only_ seems to happen if I click signup via Gravatar.**  Noting the box shape looks funky too.

Here's what it's supposed to look like.
![Screen Shot 2019-03-26 at 2 16 18 PM](https://user-images.githubusercontent.com/3476361/55030321-c302a380-4fd1-11e9-9f29-1b9064675855.png)

#### Browser / OS version
Chrome / Mac

#### Context / Source
A user [contacted us on Twitter](https://twitter.com/exchange12rocks/status/1109508136883376128/photo/1) complaining about being unable to use \ in a password (I'll check on separate issues for that) but I noticed the screenshot looked pretty bad, too.

**Comment by shaunandrews** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/191598/55084199-34e2f780-507b-11e9-8279-401bb414f634.png">

This appears to affect the wpcc/oauth flows in general.

**Comment by apeatling** [comment]
Fixed
