### ISSUE TITLE
Jetpack Connect: dark mode links aren't meeting AAA standards

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#31784]
New "Dark mode" has failing AAA link colors for small text links, as [noted here](https://github.com/Automattic/wp-calypso/pull/31304)

**Example:**
![Screen Shot 2019-03-25 at 4 58 40 PM](https://user-images.githubusercontent.com/214813/54953745-5929c180-4f1f-11e9-88c3-d1c01a9380df.png)

The "Skip" link fails to meet AAA guidelines for contrast.

<img width="703" alt="Screen Shot 2019-03-26 at 3 33 03 PM" src="https://user-images.githubusercontent.com/214813/55027790-7a9cb300-4fdc-11e9-9211-beb7be5232be.png">

Above, the install jetpack and get help links aren't meeting the guidelines as well.

**Test results:**

![Screen Shot 2019-03-26 at 3 35 04 PM](https://user-images.githubusercontent.com/214813/55027897-c3546c00-4fdc-11e9-9936-f85530576d4c.png)

**Proposal**

Just bumping the link color up one from our color studio guidelines from `#969ca1` to `#b0b5b8` will meet the AAA standards on that bg color.

https://automattic.github.io/color-studio/
![Screen Shot 2019-03-26 at 3 37 40 PM](https://user-images.githubusercontent.com/214813/55028158-6c9b6200-4fdd-11e9-949f-8e6639ec9cc2.png)

@keoshi if you concur, we can make this quick change before we ship the "Skip" step. cc @tyxla

**Comment by tyxla** [comment]
Just updated the colors here: https://github.com/Automattic/wp-calypso/pull/31304#issuecomment-477033823

**Comment by jeffgolenski** [comment]
Thanks @tyxla!
