### ISSUE TITLE
Remove Manage button on Reader

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#31780]
We need to figure out a solution for removing the "manage" button in the Reader nave drawer:

![](https://d1jfzjx68gj8xs.cloudfront.net/items/3P0c211e003U0G1G3f1b/%5Beccc0ba737eb42b2b3d54c72c5461bd8%5D_reader-nav.png)

**Comment by davemart-in** [comment]
@apeatling let's move the manage button to be like domains. Let's leave the Add tag button for now as the use case is a tad different (it's an async action).

**Comment by apeatling** [comment]
What do you mean when you say "like domains"?

**Comment by apeatling** [comment]
Do you mean replace it with a button on the page like this?

<img width="185" alt="Screen Shot 2019-04-04 at 1 22 20 PM" src="https://user-images.githubusercontent.com/1464705/55585961-b4587280-56dc-11e9-94e7-e7ff4aa7174b.png">

**Comment by davemart-in** [comment]
Oh, sorry! 

We basically just need to:

1) Remove the Manage button in the left nav
2) Then copy this component from domains: https://cl.ly/8593290ddab9 and change the button from "Add Domain" to "Manage"

Here's how I imagine that looking:

![](https://d1jfzjx68gj8xs.cloudfront.net/items/0f4031171l0g1R3H3M2G/Screen%20Shot%202019-04-04%20at%204.26.50%20PM.png)
