### ISSUE TITLE
Domain renewal date incorrect for biennial plans

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#31840]
Only the first year of the domain is included in the price of paid plans. However for biennial plans, the domain renewal date is shown as two years from date of purchase. 
#### Steps to reproduce
1. Create a new site with a custom domain and on a 2-year plan. 
2. Head to /me/puchases and click the custom domain purchase. 
3. You should now be on the purchase details page which looks like this:
<img width="728" alt="Screenshot 2019-03-28 at 6 22 29 PM" src="https://user-images.githubusercontent.com/1269602/55159187-8035fc80-5186-11e9-88bd-b7a4861c814e.png">

The `Domain renews on` field shows a date two years from now. 

#### What I expected

I expected the date to be one year from now, since only the first year is free.

#### What happened instead
The `Domain renews on` field shows a date two years from now. 

#### Browser / OS version

Chrome / Mac OS latest versions.

**Comment by klimeryk** [comment]
cc @Automattic/marketing-dev

**Comment by niranjan-uma-shankar** [comment]
I just tried again and this issue is still valid. I wonder if this is just a UI glitch or something more serious? Not sending the domain renewal notice at the end of the first year would mean that the user loses their domain, but from the lack of any support escalations since this bug report was filed, I wonder then if we are bearing the domain cost for two years and hence losing out on domain renewal revenue for a year?

**Comment by DavidRothstein** [comment]
As far as I know, users who buy two-year plans get the domain for two years also (and I think this is the way the two-year plans always worked).  So the screenshot is correctly reflecting the state of the actual domain.

Whether it should be something different, I am not sure... it does conflict with the general "free domain for one year" wording found in various places in the user interface.  But it also seems like a deal-sweetener for people who are willing to commit to two years.  Overall, this seems like a policy discussion more than a Calypso bug?

**Comment by dzver** [comment]
When 2-year plans were introduced, domains were registered for either 2 or 3 years with 2-year plans. A brief check with a random user showed that their domain, bundled with a 2-year plan, will renew in 2 years because it is registered for 2 years.

**Comment by niranjan-uma-shankar** [comment]
Thanks for clarifying @dzver . I did get confused because we say "free domain for a year" in a lot of places and assumed that to be the case for 2-year plans.

Another reason why I got confused is that we have different messaging for a 2-year plan that has not claimed the free domain. Check below the /plans page for a 2-year Personal plan that has not claimed the free domain:

<img width="1044" alt="Screenshot 2020-01-01 at 6 35 37 PM" src="https://user-images.githubusercontent.com/1269602/71641678-e9beda80-2cc5-11ea-8114-4417ce5cb2be.png">

It says that the domain is free for one year only. I agree that the user is not going to be mad that we gave them an extra free year, but we could certainly show them that we are giving away a bigger benefit. 

I haven't checked the emails yet, but I'd check this messaging there too.

@dzver Do you think there's a case for re-opening this bug to update the messaging on /plans page, or it's better to raise a new bug on that?

**Comment by dzver** [comment]
Sounds like a new and very easy to fix issue for team Cobalt.

**Comment by klimeryk** [comment]
I don't agree this falls under Cobalt - just as there's logic in that component for the Blogger plan added by Customer Marketing (https://github.com/Automattic/wp-calypso/blame/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/my-sites/checkout/checkout-thank-you/custom-domain-purchase-detail.jsx#L33), this seems more tied to a plan feature than a domain issue per se.

But this example also shows how we are bad at removing this custom logic, so I'd be careful with adding more code there for a plan that was supposed to be a test and a path to either a proper implementation of a generic x year plan or abandoning of the idea/plan. Unless we have a clear indication this is driving lower sales for this plan, I honestly would not bother with it. We need a holistic approach at that point as this is not the only place we mention "one year with a plan" (example: https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/blocks/domain-tip/index.jsx#L96). And I'm sure we have more.

**Comment by niranjan-uma-shankar** [comment]
> for a plan that was supposed to be a test and a path to either a proper implementation of a generic x year plan or abandoning of the idea/plan. 

> Unless we have a clear indication this is driving lower sales for this plan, I honestly would not bother with it. We need a holistic approach at that point as this is not the only place we mention "one year with a plan"

IMO it feels like a wasted opportunity to not pitch a benefit that we are offering to multi-year plan subscribers. Whether this benefit will drive additional sales to 2-year plans needs to be tested out.

Showing the right benefits becomes especially important given the projects planned for Q1 - overhaul of the domain step and plan step in signup, and the already in-progress checkout page overhaul. We might want to incorporate elements that highlight multi-year benefits - for example in the domain step in signup, or an upsell in the checkout page. If we do these things, then  it also becomes important to maintain consistency in benefits we show post purchase too. 

My bigger concern though is not about marketing or feature benefits for the 2-year plans, but whether are bearing a cost that we are not _expected_ to. Right from the logged out home page, to signup pages, the emails that go out, and everywhere else in Calypso, we only pitch the first year as free. We save an additional year's domain costs for all 2-year plans with no change to our marketing material with just a backend change. I'm assuming here that this change will not be custom logic for this feature, but can be made generic. This depends on a policy decision about whether we are okay to give second year free as an incentive or not.

**Comment by dzver** [comment]
> IMO it feels like a wasted opportunity to not pitch a benefit that we are offering to multi-year plan subscribers. Whether this benefit will drive additional sales to 2-year plans needs to be tested out.

I agree. I'm not sure who would own a test like that. Also not sure who would own maintenance tasks for domains-not-part-of-plans. I thought it's team Cobalt.

**Comment by klimeryk** [comment]
My reasoning here is that this is part of the work related to plans - same as all the changes that were made by Marketing when the Blogger plan was introduced: https://github.com/Automattic/wp-calypso/blame/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/my-sites/checkout/checkout-thank-you/custom-domain-purchase-detail.jsx#L33
