### ISSUE TITLE
Improvement: Change "Delete" button text inside the editor when multiple images are selected

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#31843]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/
2. Select multiple images
3. Click on "Edit"
4. Notice the "Delete" button. It would seem it only deletes one image (although the warning message is in plural)

#### What I expected

For the "Delete" button to change to something like "Delete selected items/images"

#### What happened instead

Even when having multiple images selected the "Delete" button shows the same text as if you had selected only one image. Based on user feedback, this could be misleading

#### Browser / OS version
Chrome Version 73.0.3683.86 (Official Build) (64-bit) / macOS Mojave Version 10.14.3 (18D109)

#### Screenshot / Video

![Screen Capture on 2019-03-28 at 09-13-12](https://user-images.githubusercontent.com/3696121/55164583-e2b4db80-5139-11e9-9f97-a21bb47564ef.gif)

#### Context / Source

 #user-report

Reference: 1913409-zen

**Comment by desnum** [comment]
User suggests some ways of approaching this in #2342943-zen

```
1. Show a number in confirmation. “Are you sure you want to delete these 99 items? Deleted media will no longer appear anywhere on your website, including all posts, pages, and widgets. This cannot be undone.”
2. Show a number before delete. Instead of just a “Delete” link on the page in "select everything" mode, how about “Delete 99 items”? It’s a bit more wordy but there’s space there.
3. Warn if deleting an image that is used on the site. “Warning: 99 of the images that you are deleting are used on your site. Deleted media will no longer appear anywhere on your website, including all posts, pages, and widgets. This cannot be undone.”
4. Gmail-style undo. After someone deletes media, show a toast at the bottom of the screen that says “99 items deleted UNDO”. If gmail can magically recall an email after it’s sent or undo Archiving a message, then why can’t WordPress do the same with my images?
5. iPhone-style trash bin. Yes, photos are large, so you don’t want to keep them around forever if your users delete them, but why not have a 30-day trash bin like iPhones have? If you don’t recover them within a month of deleting them, THEN they’re gone forever.
```

**Comment by desnum** [comment]
The customer mentioned in #2342943-zen returned with a prototype for how this could look! I think this could be a good solution. 

Please see their prototype at: https://invis.io/S5TXE6JRKD7

**Comment by sgryzko** [comment]
Thanks @desnum. I made a gif of the prototype, just in case it gets taken down.
![Kapture 2019-09-22 at 20 19 08 800](https://user-images.githubusercontent.com/15422197/65399484-1b94dc80-dd7a-11e9-9503-ae1b29d4889e.gif)

I also [blogged about this experience](https://shanegryzko.wordpress.com/2019/09/22/what-did-i-just-do/). I hope this gets fixed but I'm so grateful that @desnum and the Automattic team was able to bring back my images!

**Comment by lancewillett** [comment]
Good find; thanks for the report. This is indeed confusing.

I double checked with core WordPress (self-hosted version) to see how it behaves. It's a bit different: once you enter Bulk Edit mode to select more than one image, you are not able to enter single Edit mode. You're prompted to bulk delete in a clear way.

**Comment by Aurorum** [comment]
PR to make this improvement regarding the "Delete" button text for the Media Library in #36248. :) 

<img width="708" alt="Screenshot 2019-09-23 at 22 26 59" src="https://user-images.githubusercontent.com/43215253/65464518-e3f96380-de51-11e9-9b8a-7d623343e76f.png">

**Comment by Aurorum** [comment]
Made that change in the PR above :)

<img width="256" alt="Screenshot 2019-09-24 at 18 16 07" src="https://user-images.githubusercontent.com/43215253/65534503-7e5fb280-def7-11e9-92c5-757ed15cc722.png">

I think that the other changes outside of the button text should be handled by separate PRs.

**Comment by sgryzko** [comment]
@Aurorum that's brilliant, thanks! So it sounds like items 1 and 2 in the following list will be covered by your PR.

> ```
> 1. Show a number in confirmation. “Are you sure you want to delete these 99 items? Deleted media will no longer appear anywhere on your website, including all posts, pages, and widgets. This cannot be undone.”
> 2. Show a number before delete. Instead of just a “Delete” link on the page in "select everything" mode, how about “Delete 99 items”? It’s a bit more wordy but there’s space there.
> 3. Warn if deleting an image that is used on the site. “Warning: 99 of the images that you are deleting are used on your site. Deleted media will no longer appear anywhere on your website, including all posts, pages, and widgets. This cannot be undone.”
> 4. Gmail-style undo. After someone deletes media, show a toast at the bottom of the screen that says “99 items deleted UNDO”. If gmail can magically recall an email after it’s sent or undo Archiving a message, then why can’t WordPress do the same with my images?
> 5. iPhone-style trash bin. Yes, photos are large, so you don’t want to keep them around forever if your users delete them, but why not have a 30-day trash bin like iPhones have? If you don’t recover them within a month of deleting them, THEN they’re gone forever.
> ```

3, 4, and 5 are probably much more work, but it would be amazing if at least one of them were also done.

**Comment by Aurorum** [comment]
Noting that the branch ended up being really odd to work with (and somehow I managed to create a new PR?) so I'll let someone else take up this issue. :)
