### ISSUE TITLE
Private Site Videos URLs Break in Safari

### ISSUE THREAD

**Issue by azollafox** [Automattic/wp-calypso#31859]
#### Steps to reproduce
1. Have a simple WordPress.com site with a Premium or Business plan that's set to private
2. Upload a mp4 file
3. Grab the url for the video and paste it into Safari

#### What I expected
The video would play as it does in any other browser

#### What happened instead
An error screen shows. This goes away if the site is made public

![broken videos in safari](https://cld.wthms.co/vEKosx+)

(Image link: https://cld.wthms.co/vEKosx )

#### Browser / OS version
MacOS Mojave 10.14.3
Safari Version 12.0.3 (14606.4.5)

User reported there's also a problem on iPhones, but I haven't been able to test yet as I have Android. @senff did some testing with me on this in the #tickets Slack channel but reported that he couldn't get it to open and keep him logged in

> I log in, then I go to that MP4 and it says I'm not logged in

#### Context / Source
The user reported it in #1916549-zen and I was able to reproduce along with @senff .  I was able to reproduce this on my own test site with a video. When the site is set to private the video does not play on Safari. When I switch to public it's fine. I'm wondering if it's related to this other issue with the media library and private simple sites https://github.com/Automattic/wp-calypso/issues/25115 or to the new Safari privacy features. 

#user-report

**Comment by samjhamdy** [comment]
Also reported in #2443578-zen

**Comment by cpapazoglou** [comment]
This issue is still present.

I get an error in Safari `Failed to load resource: Plug-in handled load`. This happens with all Videos served directly from a private P2. I also get an error even in **Chrome** when trying to edit a video in media library of **Calypso**. I am not sure if these are related though.

```
Access to XMLHttpRequest at 'https://public-api.wordpress.com/rest/v1.1/videos/3xFfnR7f/playlist/dvd-master' from origin 'abrRw-p2' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
VM1567 videopress-routes.min.js:2 GET https://public-api.wordpress.com/rest/v1.1/videos/3xFfnR7f/playlist/dvd-master net::ERR_FAILED=

VM1567 videopress-routes.min.js:2 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Et {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}
```

**Workaround**: Adding the video with a video block, eventually uses video.wordpress.com which works as expected.

Related convo: pd8D2H-3j-p2#comment-20

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Not Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Following the instructions above, I uploaded an MP4 to a private, Premium plan site. On both Firefox and Safari, I can open the URL of the file directly in browser (so long as I'm logged into an account following the site). 
     - Mac OS 12.5.1
     - Safari 15.6.1 , Firefox 105.0.1, Chrome 105.0.51 
- Tested from the owner account as well as a Viewer on the site.

*Example*

![Markup on 2022-10-04 at 10:50:41](https://user-images.githubusercontent.com/27249804/193890655-c8322b11-ef5b-4624-a160-eb55e7daec8d.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
