### ISSUE TITLE
Domain Management: Add ability to edit custom DNS records

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#3185]
On https://wordpress.com/domains it is possible to add custom DNS to a domain, but once a record is added it cannot be edited, only deleted.

<img width="714" alt="domain_management_ _name_servers_and_dns_ _dns_records_ _hkwp20150918blog_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/12923439/70276656-cf5e-11e5-9d4d-4c37c444208a.png">

However, https://wordpress.com/my-domains and WP-Admin's My Domains both have the ability to edit existing custom records:

<img width="747" alt="my_domains_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/12923600/093735c4-cf5f-11e5-8858-b5997521fd33.png">

While it's simple enough to delete a record with a mistake and replace it with a correction, it would simplify it if records could just be edited as on previous interfaces.

**Comment by ehti** [comment]
Looks like it's on low priority, but just adding that another user contacted us regarding editing existing DNS records.

**Comment by umurkontaci** [comment]
Bumping it's priority, we should take a look at it to provide a complete experience.

**Comment by klimeryk** [comment]
Closing this - if we get to it, it'd be as part of a bigger effort to refactor and redesign the DNS editor and that's not in our short-term plans.

**Comment by happychait** [comment]
29917834-hc
