### ISSUE TITLE
Reader: blog description/tagline displays encoded HTML

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#31858]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/50155126

#### What I expected

Blog tagline displays decoded HTML

#### What happened instead

Blog tagline displays encoded HTML

#### Browser / OS version

Chrome, Firefox on Mac

#### Screenshot / Video

![Screen Shot 2019-03-29 at 9 32 09 am](https://user-images.githubusercontent.com/128826/55199355-8cad6a00-5205-11e9-8afb-2c478ae195b4.png)

#### Context / Source
#user-report

**Comment by bluefuton** [comment]
Thank you for the bug report @alisterscott :)
