### ISSUE TITLE
Gutenframes: Theme - Full Frame - Text Options Do Not Save

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#31860]
Can not reproduce on Atomic - Only WordPress.com Simple Sites. 
#### Steps to reproduce
1. WordPress.com Simple Site (Premium Plan to have theme access)
2. Activate the theme Full Frame https://wordpress.com/theme/full-frame
3. Create a blog post (or edit an existing one)
4. Change the text position to something other than default.
5. Update/publish the page.

#### What I expected
The changes would stick.

#### What happened instead
The changes revert back to default, regardless of the option you try to save. 

You then need to revert back to the Classic Editor, find WP-Admin (option not available in Calypso, WP-Admin link not on dash on Premium, and not all WordPress.com users are familiar with WP-Admin), and edit the post in WP-Admin Classic to adjust the Text Position option for this theme.

#### Browser / OS version
All.

#### Screenshot / Video
https://cloudup.com/cul9_hVxLJ5

#### Context / Source
 #reallife #flowsharing #anxiety #anxiety-flow #stresscase #painpoint

 #user-report

**Comment by arunsathiya** [comment]
Can confirm I am able to reproduce this as well. 👍🏽 I wonder if this should be filed on theme repositories because this is isolated to this theme/related themes. 🤔 

Let's leave this open for devs to share their thoughts though.

**Comment by scosgro** [comment]
Theme is now Retired. Closing.
