### ISSUE TITLE
Block Editor: Iframe sometimes fails, then refreshes successfully.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#31877]
Noticed by myself and @folletto : occasionally, when loading the iframed block editor on WordPress.com, the initial load fails with the SAMEORIGIN console error: `Refused to display '***' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` However, after a few seconds, it will refresh and successfully load.

I haven't been able to consistently reproduce. One theory is that it could be cache-related: if the page load uses a cached `frame-nonce` from an old API call that has expired, it will fail – but a refreshed `sites` API call would then provide a new valid nonce.

**Comment by kwight** [comment]
I think I saw this today; it failed, and then when the API call to `sites` with the token in it finally resolved, the screen refreshed successfully. Maybe we need to add something that blocks on the throbbing placeholder until the `sites` call resolves.

**Comment by codebykat** [comment]
In Firefox, I saw this on a first load (a site I hadn't used for testing in some time, so probably nothing was cached):

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://public-api.wordpress.com/geo/?v=1555561147268. (Reason: CORS request did not succeed).`

I think I did see it fail and then refresh, but I'm not positive if it's the same behavior. So far I haven't been able to reproduce it by disabling cache, faking a slow connection in devtools, switching browsers or switching test sites...

**Comment by kwight** [comment]
I've been able to reliably replicate by just sandboxing the API, and having the Netowrk tab open to see the correlation. I conveniently have hundreds of sites which slows the API down enough to see it 🙃 Maybe adding a delay to the sandboxed API response (`sleep()`?) would help see it?

**Comment by vindl** [comment]
Maybe it happens on clean cache load - for starters we could prevent loading the iframe if `frame_nonce` is empty. If we want some more involved error handling and reporting that are coming from the iframe, we could look at what Customizer is already doing: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/customize/main.jsx

**Comment by obenland** [comment]
Possible cause and fix: p1556225048260800-slack-lannister
