### ISSUE TITLE
Block Editor: Unnecessary call to trash post twice

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#31878]
Needs further auditing to confirm issue and assess its consequences.

When trashing a post from within the editor iframe I see two network calls to trash the post. I believe that one originates from inside Gutenberg inside of the iframe, the `DELETE` call; and the other originates in Calypso when we issue the `trashPost( siteId, postId )` action, which calls `wpcom().site( siteId ).post( postId ).delete()`

![Screen Shot 2019-03-29 at 12 32 07 PM](https://user-images.githubusercontent.com/5431237/55257966-b58e2900-521e-11e9-828c-d82f4a90675b.png)
![Screen Shot 2019-03-29 at 12 32 17 PM](https://user-images.githubusercontent.com/5431237/55257967-b6bf5600-521e-11e9-9b11-50a0aff2cc01.png)

**Reproduce**
 1. Open post on Simple Site in Block Editor at `/block-editor/post/…`
 2. Click on the trash button in the `Document` tab of the sidebar
 3. Look for the requests in the network panel of the browser's debug tools

**Comment by gwwar** [comment]
I believe this one should be fixed by https://github.com/Automattic/wp-calypso/pull/34855
