### ISSUE TITLE
Featured image drop zone text hard to read

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#31888]
Featured image drop zone background color is accent, which was introduced here https://github.com/Automattic/wp-calypso/issues/29936 👍🏽 

The text and icon should be white though for better reading. It's hard to read at the moment.

<img width="1091" alt="Screenshot 2019-03-30 at 08 44 09" src="https://user-images.githubusercontent.com/18581859/55270696-23425f80-52c8-11e9-9794-13433220c6ee.png">

@Automattic/color-theming, thoughts on this, please?

**Comment by torres126** [comment]
Contrast ratio of `--color-accent` upon `--color-text` in Classic Bright is 2.85:1, so fails the contrast checker too. With white, it would be 4.84:1.

**Comment by stephanethomas** [comment]
https://github.com/Automattic/wp-calypso/pull/36074 should fix that.

**Comment by Aurorum** [comment]
Fixed by #36074 in its normal state, but the hover state now fails contrast instead.

<img width="488" alt="Screenshot 2019-09-13 at 16 27 27" src="https://user-images.githubusercontent.com/43215253/64894440-adf9f980-d671-11e9-8185-dd279efea7ba.png">

**Comment by sixhours** [comment]
Closing this out in favor of #36239
