### ISSUE TITLE
Gutenberg: Block editor doesn't recognize italics and bold Markdown syntax

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#31890]
I noticed incomplete treatment of basic Markdown syntax in both the Classic and block editors.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/he20171027.com/607 (private WP.com site)
2. While in the Classic Editor, I was able to create a level two heading with `##`, and a bullet list with `*`. Trying to format text as italics using the `_` didn't work, though, [like this](https://cld.wthms.co/Ddq3gL).
3. I switched back to the block editor to see if it would pick up on the Markdown syntax, but it actually broke some of the syntax, [here](https://cld.wthms.co/4ZOQfY).
4. When I copied the text that I tried to format as italics into a new Paragraph block, the editor converted into italics text correctly, [like this](https://cld.wthms.co/3rlsYr).

#### What I expected

The block editor should recognize, and convert basic Markdown syntax such as italics, and bold (I only tested these two options at this time).

#### What happened instead

Typing `_` before and after text I intend to format as italics directly into the editor doesn't seem to format the text as italics (the same applies with bold formatting using `**`).

The editor will format the text in the editor if I copy and paste the formatted text into a Paragraph block, though, [like this](https://cld.wthms.co/3rlsYr):

![](https://cld.wthms.co/3rlsYr+)

#### Browser / OS version

Firefox Developer Edition, v67.0b6 (macOS 10.14.4)

WordPress.com Editor v4.0.1 beta 1

#### Context / Source

This was an outcome of #dogfooding #internaltesting

**Comment by gwwar** [comment]
Gutenberg doesn't have full markdown support. I'd recommend adding an issue to the core project https://github.com/WordPress/gutenberg if there isn't an open request. 

See also p9dueE-rW-p2 for handy test environments.
