### ISSUE TITLE
Editor: Port the wpemoji TinyMCE plugin to Calypso

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#319]
See https://core.trac.wordpress.org/browser/trunk/src/wp-includes/js/tinymce/plugins/wpemoji/plugin.js

**Comment by alisterscott** [comment]
Emoji are supported in the editor and post titles which was why this was originally raised. Closing

**Comment by pento** [comment]
Reopening.

The purpose of the wpemoji plugin is to render emoji that the browser doesn't support, similar to the Emojify component.
