### ISSUE TITLE
Broken LGTM emoji (images) on contributing doc

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#31900]
Looks like the LGTM emoji (images, or icons) seem to be broken at the moment. Looks like these were image files and the files are deleted somehow at GitHub's end? 🤔 

<img width="719" alt="Screenshot 2019-03-31 at 18 15 06" src="https://user-images.githubusercontent.com/18581859/55289640-86c2af00-53e6-11e9-8177-de62e94a6e11.png">
<img width="515" alt="Screenshot 2019-03-31 at 18 51 58" src="https://user-images.githubusercontent.com/18581859/55289641-86c2af00-53e6-11e9-9eac-f5517011d7ac.png">

These can be seen at:

- https://wpcalypso.wordpress.com/devdocs/.github/CONTRIBUTING.md
- https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md

**Comment by arunsathiya** [comment]
I think these can be fixed by listing them as emoji, 

- https://emojipedia.org/thumbs-up-sign/
- https://emojipedia.org/collision-symbol/

But I do not remember what the last two were.

**Comment by torres126** [comment]
It was a ship 🛳 and this one:

![Screenshot_20190331-174611](https://user-images.githubusercontent.com/43215253/55291967-08adda80-53dd-11e9-9f6f-790f1c607d4c.jpg)
