### ISSUE TITLE
Gutenframe: custom blog posts page shows wp-admin screen

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#31917]
#### Steps to reproduce
1. Use a test site that has opted in to Gutenberg.
1. Create a new page on you site with empty content.
1. Navigate to Customizer -> Homepage Settings and set the above page as a posts page.
2. Go to My Sites > Site Pages. 
3. Attempt to edit the above page.
4. Notice that this will show the wp-admin editor with a blank page.

Since this wp-admin view is iframed, trying to click on `Add new` button or similar functionality will result in `refused to connect` iframing error.

More info in the comments section of this post: p7DVsv-69v-p2.

**Comment by vindl** [comment]
In order to reproduce this locally the page's content should be empty. At that point this core override kicks in:

https://github.com/WordPress/WordPress/blob/733ec3da48353bea73d6c4b332a76e8fed18389f/wp-admin/includes/post.php#L2086-L2089

**Comment by vindl** [comment]
For comparison, both in Core Classic and Calypso Classic editor we are allowing the editing of this type of page regardless of content. I find it strange that we are making an exception for block editor only an cases when the content is empty.

/cc @pento in case you have any additional context behind this decision (pinging you since you were mentioned in the props for the above change).

**Comment by pento** [comment]
That exception was originally put in due to the block editor not playing nicely with post types that don't support showing the content editor. I don't know if that's changed in more recent versions of the Gutenberg plugin.

**Comment by vindl** [comment]
@gwwar there seems to be no obvious for for overriding this core behavior in WPCOM. Some of the options going forward for this edge case (empty content, posts page):

- prevent linking to the editor in posts list,
- fallback to Classic editor (similar to what core does).

Let me know if you have any other ideas.

**Comment by gwwar** [comment]
@vindl for context when we set a page to be a post page, does any custom page content show or is it overwritten with recent posts on the published view? For example imagine a page with "Hello World" as its post_content

**Comment by vindl** [comment]
> Edit: testing this myself, custom content doesn't appear. Let's disable the ability to edit in the list with a notice.

Thanks for the suggestion @gwwar! I deployed a fix which handles this edge case. I'll see if it makes sense to follow-up and do the same thing in general case with some popover explanation.
