### ISSUE TITLE
Jetpack Contact Form Block: Checkbox group can't handle commas (breaks entry into multiple checkboxes)

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#31929]
#### Steps to reproduce
1. Add a Jetpack Contact Form block
2. Add a "Checkbox group" to that block.
3. For one option, add an entry with commas in it, such as "African-Canadian, Indigenous, Hispanic/Latina"
4. Looks fine in the editor. However, viewing the published page/preview it's now three separate checkboxes.

Interestingly, the single "checkbox" option works fine. It's just the "checkbox group" that breaks lines into multiple boxes when commas are used.

#### What I expected

For African-Canadian, Indigenous, Hispanic/Latina to remain on a single line as entered into the checkbox group.

#### What happened instead

It's turned into three separate checkboxes:

African-Canadian
Indigenous
Hispanic/Latina 

#### Browser / OS version

Chrome Version 73.0.3683.86 (Official Build) (64-bit) / Pop!_OS 18.10 

#### Screenshot / Video

![Annotation on 2019-3-1 (2)](https://user-images.githubusercontent.com/10121835/55346695-b3270b80-5478-11e9-99f4-145eb45e9c16.png)

![Annotation on 2019-3-1 (3)](https://user-images.githubusercontent.com/10121835/55346710-be7a3700-5478-11e9-82f4-1814e395f015.png)

#### Context / Source

#11744520-hc

**Comment by lancewillett** [comment]
Closing as duplicate.
