### ISSUE TITLE
Block Editor: Admin notice is not full width for full-width sidebars.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#31945]
At widths where opening the sidebar would expand it full-width (such as a screen width of 850 pixels), admin notices will shrink to the size of a normal column. This makes the admin notice appear to be floating to the left side (it's full-width and fine, however, when the sidebar is closed).

<img width="863" alt="Screen Shot 2019-04-01 at 8 18 35 PM" src="https://user-images.githubusercontent.com/349751/55373983-d030fe00-54bb-11e9-8c49-9a93c5da8583.png">

<img width="866" alt="Screen Shot 2019-04-01 at 8 18 50 PM" src="https://user-images.githubusercontent.com/349751/55373989-d7580c00-54bb-11e9-9be4-9a737aee6268.png">

**Comment by Copons** [comment]
This happens in Core as well.
I've opened an issue there (https://github.com/WordPress/gutenberg/issues/14775) and will close this.

**Comment by Copons** [comment]
@kwight quick update: in fact this does not happen in Core as well.
I was testing on the latest commit, but with the plugin disabled. 😅
 
In other words, this happens on the version of Gutenberg currently merged into Core, but not on the current version of the Gutenberg plugin.
So in all likelihood this issue will fix itself whenever we get 5.2 on WPCOM.

**Comment by kwight** [comment]
@Copons Oh sweet, let's wait for that then. Thanks for double-checking!
