### ISSUE TITLE
Widgets: image widget broken in WP Admin, when Gutenberg enabled

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#31950]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize (on a site opted-in to Gutenberg)
2. Add an image widget to widget area and publish
3. Head to WP Admin > Appearance > Widgets
4. Click on image widget

#### What I expected

Expect to see and be able to change the image

#### What happened instead

There is no image, and area where it would display is missing (no height)

#### Browser / OS version

Chrome 72.0.3626.121
Firefox 66.0.2

#### Screenshot / Video

On customer site in Firefox:
![image](https://user-images.githubusercontent.com/2031017/55380497-1a71b800-556c-11e9-94ac-6d32b2b2f1e4.png)

On my test site in Chrome:
![image](https://user-images.githubusercontent.com/2031017/55380507-22315c80-556c-11e9-8c7f-4f4091c91c1d.png)

#### Context / Source

If you change the Gutenberg setting in the user report card back to Classic editor the problem goes away, and console errors shown in screenshot go away

#user-report 1924545-zen

**Comment by arunsathiya** [comment]
I am not able to reproduce it. `gutenberg.wpcom.arunsathiya.blog` has Gutenberg enabled, and I was able to change the image on the widget on wp-admin just fine. No console errors as indicated either.

![Screenshot 2019-04-03 at 14 52 03](https://user-images.githubusercontent.com/18581859/55468010-1bfcb800-5620-11e9-8e3f-d923e8943ad4.png)
![Screenshot 2019-04-03 at 14 52 18](https://user-images.githubusercontent.com/18581859/55468012-1bfcb800-5620-11e9-90c4-07763caa7cf1.png)

I am using Twenty Nineteen on Google Chrome Version 72.0.3683.86 (Official Build) (64-bit) with macOS 10.14.2 - Mac OS Mojave. 

Are you using a specific theme, @kristarella?

**Comment by kristarella** [comment]
@arun I was using Twenty Nineteen also.
I will not be able to test again for a while. Can you check the ticket to see if it's still on customer's site. Maybe it has been fixed.

**Comment by arunsathiya** [comment]
Thanks, @kristarella! That's a bit strange, but I replied to the ticket 1924545-zen and added some notes over there. I am going to leave this GitHub open for others to see what might be causing the image widget to not load. Especially curious because it seems to happen only with Gutenberg activated on your tests.

**Comment by gwwar** [comment]
Thanks for the console error screenshots!

If folks are having trouble reproducing we can keep this open for a while to see if there are additional reports. Without digging too deeply, it sounds like a missing script/bad ordering of globals. Could be a race-condition or something like Gutenberg modifying filter priority when activated.

**Comment by gwwar** [comment]
Doesn't look there was much activity on this one. I'm going to close out for now, but please re-open if folks are still running into trouble.
