### ISSUE TITLE
Private Sites Can't Use Image Editing Features

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#31965]
#### Steps to reproduce
1. Starting at URL: [https://wordpress.com/media/](https://wordpress.com/media/)
2. Click on an image in the Media Library, and then select the Edit button
3. In the modal that appears, there will be no Edit Image button
4. Change site to Public from the Site General Settings page here: [https://wordpress.com/settings/general/](https://wordpress.com/settings/general/)
5. Go back to Media Library
6. Select the same image, and then hit the Edit button
7. Edit Image button will now be available

#### What I expected
Edit Image button would be available regardless of site visibility

#### What happened instead
Wasn't able to edit the image until the site was set to Public. Was still able to edit the image from site's WP Admin, however.

#### Browser / OS version
Firefox/Chrome, macOS 10.14.4

#### Screenshot / Video
[Screen Recording](https://cld.wthms.co/Xd1lIX)

#### Context / Source

Initially reported in #9974062-hc / Follow-up #1928156-zen

**Comment by torres126** [comment]
Related/duplicate: #25115

**Comment by arunsathiya** [comment]
Closing as a duplicate. 👍🏽
