### ISSUE TITLE
Stats: Changing the post date or "slug" doesn't display previous stats for that post.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#31982]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Identify a post to use an example in your "Top Posts & Pages"
3. Edit that post, and update the slug or the post date. Publish your changes.
4. Check the stats page again. Click on the post title now only displays the stats from when you changed the URL/slug/date onwards.

#### What I expected

To see all the previous stats for the post.

#### What happened instead

It's almost as if it's considered a new page. Except the "All time" stats seem to still be present/accurate when I tested it myself.

#### Browser / OS version

Pop!_OS 18.10
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

#### Screenshot / Video

Test post, which had 8 views before I changed the post date to today:

![Annotation on 2019-3-2 (7)](https://user-images.githubusercontent.com/10121835/55440990-f9f72d00-556e-11e9-926b-5d26e9bd27c4.png)

All time stats view, which shows 12 views. Which is accurate.

![Annotation on 2019-3-2 (8)](https://user-images.githubusercontent.com/10121835/55441017-1004ed80-556f-11e9-8ff9-65f859a25847.png)

#### Context / Source

#8634998-hc

#1626950-zen

#1922048-zen

**Comment by lschuyler** [comment]
I'm seeing the same behavior on a Jetpack site. When the site owner bumps a post by changing the publish date, the only stats available are from that new published date forward. However if the published date is changed back to the original date, the historical stats reappear.
