### ISSUE TITLE
Media: we should avoid a dead-end when uploading video without the VideoPress upgrade

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#3199]
Raised by @ryanboren 

> What happens when you attempt to upload a video to your new wordpress.com blog? This…

<img width="1282" alt="screen shot 2016-02-09 at 4 08 05 pm" src="https://cloud.githubusercontent.com/assets/66797/12932572/b2bef786-cf40-11e5-996a-5b676378bf33.png">

> Users often try to change the filename to progress beyond the unhelpful dead end message. This is what everyone who doesn’t already have the VideoPress upgrade experiences. Please, please, please fix this and help out [WordPress core](https://core.trac.wordpress.org/ticket/28367) in the process.

This happens on any new blog with a space upgrade or VideoPress upgrade.

**Comment by lancewillett** [comment]
Current state: you get to a dead end with the red warning about file type.

Better state: clearly say that authors can indeed upload this file type if they upgrade to a plan with video support (or a plan with enough space).

I also went through this painful UX the other day on a testing site, with the Calypso editor.

**Comment by ryanboren** [comment]
https://test.wordpress.com/2016/02/09/video-uploading-video-without-the-videopress-upgrade/

https://kibbling.wordpress.com/2014/09/16/uploading-video-without-the-videopress-upgrade/

https://core.trac.wordpress.org/ticket/28367

**Comment by ianstewart** [comment]
@meremagee has noted that we don't even get an error on Android. It just fails silently.

**Comment by lancewillett** [comment]
@apeatling Did solving this come up during any team discussions for plans and upgrades recently? It's been an unsolved dead end for a long time now.

**Comment by apeatling** [comment]
@vindl Can we handle this with the new VideoPress nudge? Detect the file type being uploaded and redirect to this screen if it's not accepted?

**Comment by vindl** [comment]
@apeatling Yes, we should be able to handle this with VideoPress nudge. I'll try to update #7839 in order to show it here too.

By the way, we are no longer hiding `Video` and `Audio` tabs for free users, so it's probably a little less confusing than before:
![screenshot from 2016-09-08 19-34-30](https://cloud.githubusercontent.com/assets/1182160/18359771/b0ff1ebe-75fb-11e6-8b02-3d5da7724c29.png)

**Comment by ryanboren** [comment]
With recent changes:

![screen shot 2016-09-08 02 09 55 pm](https://cloud.githubusercontent.com/assets/2047747/18365195/5748b584-75d7-11e6-8769-3e1d85412680.png)

Upgrade Plan opens this page:

![screen shot 2016-09-08 02 16 58 pm](https://cloud.githubusercontent.com/assets/2047747/18365220/722ac270-75d7-11e6-838a-d1f0a77c7fd3.png)

**Comment by ryanboren** [comment]
On iPhone 6+

![img_0981](https://cloud.githubusercontent.com/assets/2047747/18365613/098f4a0e-75d9-11e6-8a59-e7ab952b1dc7.PNG)

**Comment by vindl** [comment]
Just wanted to note that expanded nudge didn't perform well in AB tests, and we decided to remove it altogether. That includes the expanded VideoPress nudge that was supposed to replace the existing nudge in this case. 

More info in this PR: https://github.com/Automattic/wp-calypso/pull/8403

**Comment by vindl** [comment]
> Better state: clearly say that authors can indeed upload this file type if they upgrade to a plan with video support (or a plan with enough space).

@lancewillett it seems to me that, with recent changes, this component is already in desired state. If that is the case I think we can close this issue. Could you please verify?

**Comment by lancewillett** [comment]
Yes, thanks Vindl.
