### ISSUE TITLE
Me: Settings: Privacy section overlaps with Primary Site picker

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#3200]
This happens in: `https://wordpress.com/me/account`

![screenshot 2016-02-09 14 23 51](https://cloud.githubusercontent.com/assets/4924246/12932738/24641324-cf39-11e5-80bc-0bce9412d654.png)

**Comment by hoverduck** [comment]
The Privacy card was removed with #3174.  Closing.
