### ISSUE TITLE
Prevent adding email forwards for wpcomstaging.com

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#32006]
#### Steps to reproduce

On an Atomic v2 site

1. Starting at URL: https://wordpress.com/email/example.wpcomstaging.com/forwarding/example.com
2. Add an email forward to example.wpcomstaging.com
3. Test the email forward and note it doesn't work

#### What I expected
The forwarding to work or be prevented

#### What happened instead
The forwarding does not work. Confirmed in p9o2xV-eO-p2 that we should prevent the option from adding an email forwarding from being available on the wpcomstaging.com domain like WordPress.com

#### Context / Source

#manual-testing

**Comment by lancewillett** [comment]
Hi @kriskarkoski — can we mark as normal priority? Seems like a good bug to fix but not high priority versus other open issues. Do you have a sense of how many people would run into this?
