### ISSUE TITLE
"Add People" link should be consistent when sidebar is accessed from the frontend or from Calypso

### ISSUE THREAD

**Issue by p3ob7o** [Automattic/wp-calypso#32001]
#### Steps to reproduce
1. Start on any WordPress site you own with Jetpack and the WordPress.com toolbar activated. In my case it was http://paolo.blog
2. Click on "My Sites" on the top left of your window to see the sidebar.
3. Hover over the Add button next to People and notice the link to https://paolo.blog/wp-admin/user-new.php
4. Click on Stats to see the Calypso sidebar.
5. Hover over the Add button next to People and notice the link to https://wordpress.com/people/new/paolo.blog

of course in both cases, paolo.blog will be replaced by the URL of the site you are using to test.

#### What I expected

I expected the link to lead to Calypso in both cases, as all the other links in the Sidebar excepted Customizer, which leads to wp-admin in both cases. From the user perspective, the sidebar is the same, whether accessed from within Calypso or from the site frontend: it should behave in the same way.

/cc @lancewillett

**Comment by lancewillett** [comment]
Thanks for the report, good eye.
