### ISSUE TITLE
Purchases: Site domain missing on removal confirmation

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#32014]
#### Steps to reproduce 

- Start at https://wordpress.com/me/purchases
- Click on a paid WordPress.com plan
- Follow the removal instructions
- On the final removal step, note a copy that reads `Are you sure you want to remove {plan} from Site Plan`?

#### What is expected 

`Site Plan` here should be the name of the site name / domain.

#### What happens instead 

It reads `Site plan`

<img width="727" alt="Screenshot 2019-04-03 at 16 03 56" src="https://user-images.githubusercontent.com/18581859/55535596-49576d80-56d5-11e9-87e2-81e50d1888b5.png">
<img width="639" alt="Screenshot 2019-04-03 at 16 06 41" src="https://user-images.githubusercontent.com/18581859/55535598-49f00400-56d5-11e9-91d6-51952c1f0ab9.png">

This happens for both WordPress.com sites and Jetpack sites.

My initial understanding was that this should be the site name, but I think it should be the site domain. Because G Suite removal shows site domain:

<img width="670" alt="Screenshot 2019-04-03 at 23 07 56" src="https://user-images.githubusercontent.com/18581859/55535662-70ae3a80-56d5-11e9-9ab5-32259ed89fe6.png">

Two or more sites having same site name can be confusing, but domains are unique. :)

**Comment by rfaile313** [comment]
Hey @arunsathiya thanks for reporting this. I'll work on this it (and I shudder to say) _seems_ like an easy enough fix. 

I'll reply when I have an update.

**Comment by arunsathiya** [comment]
Oh, nice work, @rfaile313! Thanks for the patch!
