### ISSUE TITLE
Me: Notifications settings - alerts never go away

### ISSUE THREAD

**Issue by shawnajean** [Automattic/wp-calypso#3203]
Not only do they not timeout, they actually collect and just fill up the screen.
![screenshot_08-03-2016-18 52 49](https://cloud.githubusercontent.com/assets/150348/13623926/07e494a8-e55f-11e5-8d73-56f12fdecf24.png)
Repro by changing & saving your settings at bunch at https://wordpress.com/me/notifications

**Comment by hoverduck** [comment]
07Apr16 Bug Scrub

Confirmed this is still a problem, although at least for me on OSX Chrome v49, the notifications stacked up along the right side of the screen, which is slightly less annoying.

**Comment by BandonRandon** [comment]
This is still occurring upon save.

**Comment by ebinnion** [comment]
I'm tied up with the Jetpack 4.1 release right now. Ping @rodrigoi who worked on much of this code and @artpi, who I believe updated the notification call to redux to see if they have a better idea of how to fix.

**Comment by BandonRandon** [comment]
Thanks for taking a look @ebinnion. This is not urgent just was at the top of the bug scrub so I was testing if it was still happening. 

Coping my comment from #3254 

>I would like to see inline alerts where we auto-save when checking/unchecking a box instead of having to click "Save Settings" button but that may be out of the scope of this alert.

**Comment by beaulebens** [comment]
I would definitely +1 this. Any of these types of simple confirmations should ideally timeout pretty quickly, and just fade/slide/whatever out of view. It's pretty infuriating that it requires user interaction to effectively confirm that you've seen a confirmation!

Since this is a broader issue than just for the "Me" section (definitely also happens in the Site Settings section), it'd probably be worth just doing a sweep through all of Calypso to standardize how they work.

**Comment by lancewillett** [comment]
Re-tested this today in Safari 10.0 on OS X 10.12 — using Me > Notifications settings. It seems fixed! Notifs are not piling up, I only get one occurring at the top right of the screen for each save.

**Comment by hoverduck** [comment]
Re-opening...I'm still seeing this on Safari 10.0, Chrome v54, and Firefox v46.0.  It works correctly on the main /settings pages (clearing out the old Notice when saving settings again), but the specific example below of /me/notifications doesn't clear them out:

![wp-calypso-3203](https://cloud.githubusercontent.com/assets/7233112/19401480/90849584-9229-11e6-8fe8-b68017bf47bb.gif)

**Comment by ryanboren** [comment]
This notification style always gets in the way of repeated operations. I let them pile up until they obscure and then Cmd+R to save clicks.

![screen shot 2017-03-29 at 1 30 36 pm](https://cloud.githubusercontent.com/assets/2047747/24470736/97bd067c-1485-11e7-96b8-378d43b08548.png)

**Comment by nickmomrik** [comment]
Was coming to report this bug and found this ticket. Happens to me when updating my Notification Settings in Chrome on a Mac.

<img width="980" alt="screen shot 2017-07-23 at 7 52 10 am" src="https://user-images.githubusercontent.com/684691/28499123-341c0a1c-6f7c-11e7-9243-6a755bc4a60d.png">

**Comment by alisterscott** [comment]
I noticed this testing the new Gravatar upload feature:

<img width="1020" alt="notice text" src="https://user-images.githubusercontent.com/128826/28553027-df288886-7134-11e7-98fa-7c8093127736.png">

**Comment by rachelmcr** [comment]
I tested and confirmed this still happens on the notifications settings screen:

![screenshot 2018-08-28 15 23 53](https://user-images.githubusercontent.com/8658164/44729501-e0709d00-aad6-11e8-9443-75cd9f065fde.png)

It feels especially intrusive on mobile, where the notices stack up and completely obscure the bottom of the screen:

![2018-08-28 15 30 54](https://user-images.githubusercontent.com/8658164/44729810-7c020d80-aad7-11e8-97c4-a6789476078c.png)

**Comment by alisterscott** [comment]
Please find fix in #26943
