### ISSUE TITLE
Gutenframe: Align the iframe bridge communication code for both Jetpack and Simple sites.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32044]
This involves moving the active WP.com file to JP and sync it with Fusion, so that the code already correcting issues for WP.com can also be applied to Jetpack sites (media modal, revisions, back button, etc.).

See: p7jreA-2gu-p2.
Background: p3fqKv-6Hh-p2.

**Comment by kwight** [comment]
We also need to be aware that for opt-in, their settings can be controlled by the Classic Editor plugin (Jetpack and Atomic currently have no understanding of the opt-in API, only simple sites). This means the "Switch to Classic Editor" piece of this file will need special handling in consideration of https://github.com/Automattic/wp-calypso/issues/32047.

**Comment by obenland** [comment]
@mmtr Can this be closed?

**Comment by kwight** [comment]
https://github.com/Automattic/jetpack/pull/12070 is the fix for this (which isn't merged yet).
