### ISSUE TITLE
Gutenframe: Add UI explaining failure when the user is not logged in on the Jetpack side.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32046]
Display a “to use the block editor on this Jetpack site, you’ll need to log into that site”-type screen if the user is not logged in on the JP side. When the user is not logged in, the XML-RPC verification will fail, and the `sameorigin` error screen will be shown, which doesn't help a confused user at all.

Background: p3fqKv-6Hh-p2

**Comment by kwight** [comment]
Initial research by @dmsnell:

> There are some endpoints that should be there for every Jetpack site and we should get back a positive acknowledge of missing auth at those endpoints.
> 
> For example, if we hit `/wp-json/jetpack/v4/connection/url` without auth we get a `401` status code plus `invalid_user_permission_jetpack_disconnect` in the body of the response.
> 
> Either with this one or another we should be able to make the call and differentiate between “this network call failed” and “this request failed due to no auth” and the async wrapper component I built a while back for the Block Editor can be used to defer rendering until we know.

**Comment by kwight** [comment]
The parts required would be:

* a selector/helper function for fetching the above API result, and
* using that selector [near the top](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/controller.js#L170) of `redirectIfBlockEditor` to further inform whether or not to load the iframed block editor.

**Comment by dmsnell** [comment]
> a selector/helper function for fetching the above API result

this or some variant of it might work fine
```js
const getJetpackAuthStatus = baseUrl => requestHttpData(
	'jetpack-remote-connection-url-as-proxy-for-auth',
	rawHttp( { path: `${ baseUrl }/wp-json/jetpack/v4/connection/url` } ),
);

const mapStateToProps = state => {
	const baseUrl = getJetpackBaseUrlIfWeHaveSuchAFunction( state );
	const jetpackAuth = getJetpackAuthStatus( baseUrl );

	const lacksRemoteAuth = (
		jetpackAuth.state === 'failure' &&
		jetpackAuth.error.code === 'invalid_user_permission_jetpack_disconnect'
	);

	const remoteAuth = jetpackAuth.state === 'pending' ? 'pending' 
		: ( jetpackAuth.state === 'success' ? 'authorized' 
		: ( lacksRemoteAuth ? 'unauthorized' : 'indeterminate' ) );

	return {
		remoteAuth
	}
};

const wrappedThing = connect( mapStateToProps )( ( { remoteAuth } ) => (
	<>
		{ 'pending' === remoteAuth && (
			<StillLoadingEditor />
		) }
		{ 'authorized' === remoteAuth && (
			<EditorIFrame />
		) }
		{ 'unauthorized' === remoteAuth && (
			<PleaseAuthOnRemoteEnd />
		) }
		{ 'indeterminate' === remoteAuth && (
			<SomethingWrongTryAgain />
		) }
	</>
) );
```

This will request the author information and provide it as props to the wrapped component. We can use `waitForData()` and/or `asyncWrapper()` to defer loading but if we keep things tidy here through data-only connections then it will be easier to test…

```js
// test.js
import { UnwrappedEditorThingy as EditorThingy } from '../';

<EditorThingy remoteAuth="pending" />
<EditorThingy remoteAuth="authorized" />
<EditorThingy remoteAuth="unauthorized" />
<EditorThingy remoteAuth="indeterminate" />
```

If we want some types we could do this…
```ts
type RemoteAuthState
	= 'pending'
	| 'authorized'
	| 'unauthorized'
	| 'indeterminate';

interface ConnectedProps {
	remoteAuth: RemoteAuthState;
}
```

**Comment by mmtr** [comment]
I decided to explore a different approach in https://github.com/Automattic/jetpack/pull/12135 which seems to be simpler and easier, since it doesn't involve any API call.

This approach relies on the `wpcom-block-editor` module in Jetpack which will show a custom message using the `wp_die` function if we detect the user is not logged in. With `wp_die` we make sure the `send_frame_options_header` function is not executed, allowing the response to be rendered in a iframe.
