### ISSUE TITLE
Reader: Post header is not clickable (even though it appears that way)

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3205]
The header of a post in the reader is not clickable, even though it appears to be clickable as it changes the cursor for the entire post. This is quite confusing as it clicking it multiple times doesn't do anything and it isn't obvious to click the section under the header.

![reader header not clickable](https://cloud.githubusercontent.com/assets/128826/12935294/7e2875ba-cfe0-11e5-9153-ae155e362cdd.png)

Steps to Reproduce

1. Open reader
2. Click a site header - displays that site and its posts
3. Click on the header of a post
4. Nothing happens
5. Expected: post is displayed (same as clicking below header)

Screen recording

![reader post header not clickable](https://cloud.githubusercontent.com/assets/128826/12935350/d284c0dc-cfe0-11e5-9c90-78c87dd94431.gif)

**Comment by jancavan** [comment]
Closing this as this is the same as: https://github.com/Automattic/wp-calypso/issues/3639
