### ISSUE TITLE
Gutenberg: Cannot scroll the editor in mobile Safari browser with portrait orientation [2]

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#32068]
#### Steps to reproduce
1. Starting in Safari on a mobile device, go to: https://wordpress.com/
2. Log in and start a new post in the block editor.
3. Add content to the post — either one block with a lot of content, or multiple blocks — until the content is longer than what is visible on a single screen.
4. Try to scroll down to the end of the content you added.

#### What I expected

I expected the content to scroll as usual so I could add or edit content.

#### What happened instead

When I dismiss the keyboard, I see a single screen of content and can't scroll down any farther. If the keyboard is in view, I can scroll down as far as the bottom of that single screen of content and not beyond that point. There is a grey bar at the bottom of the screen that cuts off the visible editor content.

If I rotate my device to landscape orientation, the editor works as expected, but when I rotate back to portrait the problem remains. (This is only slightly helpful, as very little of the editor is visible in portrait orientation.)

The same occurs with a new post or editing an existing post.

#### Browser / OS version

Safari / iPhone XS with iOS 12.2

I also tested on an Android moto e5 play with Chrome / Android 8.1 and the block editor worked as expected there.

#### Screenshot / Video

![2019-04-05 11 27 42](https://user-images.githubusercontent.com/8658164/55638251-ada22c00-57be-11e9-8306-c594da21d33c.png)

#### Context / Source
#dogfooding #manual-testing

**Comment by apeatling** [comment]
@rachelmcr thanks for this, for next time can you ping me directly on any critical editor usability issues like this? Thanks!

**Comment by gwwar** [comment]
Should be mostly fixed by #33689. We added #33703 and #33702 as follow up issues.
