### ISSUE TITLE
Jetpack Mobile theme: Calypso typo in settings toggle

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#32082]
#### Steps to reproduce
Find an AT site with mobile theme settings enabled:

1. Navigate to Jetpack → Settings → Writing.
2. View Mobile Theme settings.

![Image](https://cld.wthms.co/aq9qlu+)

1. Go to My Site → Settings → Writing.
2. View Mobile Theme settings.

![Image](https://cld.wthms.co/kDltq9+)

Jetpack settings shows a setting called "Show featured images". Calypso incorrectly states "Hide all featured images" instead of "Show".

As a side note, it'd probably be best if the wording was consistent for all the settings in the Mobile Theme section.

#### Context / Source
User reported in 11861763-hc.
#user-report

**Comment by simison** [comment]
FYI @jeherve @kraftbj

**Comment by rfaile313** [comment]
☝️ should fix.
