### ISSUE TITLE
Gutenberg: Unable to enable sharing buttons in Gutenberg editor in Calypso, inconsistent options in WP Admin

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#32093]
#### Steps to reproduce
1. A user reported that they had enabled sharing buttons in Sharing in the WordPress.com dashboard
2. I noticed that Gutenberg in Calypso does not include a Sharing panel in the editor sidebar to enable or disable sharing buttons on a per post basis as we indicate [here](https://en.support.wordpress.com/sharing/#disabling-sharing-likes-on-specific-posts)
3. In this user's case, despite enabling sharing buttons in Sharing ([like this](https://cld.wthms.co/N8PW17)), they weren't able to enable the sharing buttons unless they did so in the (Classic) editor in the WP Admin dashboard, [here](https://cld.wthms.co/EySbfc).
4. The option in the WP Admin dashboard doesn't respect the option set in Sharing in the WordPress.com dashboard.

#### What I expected

1. An option to enable or disable sharing buttons in the block editor in Calypso;
2. When setting the option to enable sharing buttons in the Sharing section of the WordPress.com dashboard, this preference should be respected in the WP Admin too.

#### What happened instead

Enabling sharing buttons in the WordPress.com dashboard in Sharing doesn't actually display sharing buttons. The user had to enable the option in the post editor in the WP Admin dashboard.

I noticed that when I tested this in my test site, https://he20171027.com, I wasn't able to access the sharing buttons options in the Classic Editor in the WP Admin dashboard. I was, however, able to access this option when I switched over to the Classic Editor in Calypso, [like this](https://cld.wthms.co/JSfRkG):

![](https://cld.wthms.co/JSfRkG+)

#### Browser / OS version

Firefox Developer Edition v67.0b8 (64-bit)
macOS 10.14.4

#### Context / Source

This was a user report in 1944286-zen

**Comment by simison** [comment]
cc @Automattic/lannister

**Comment by Copons** [comment]
Per-post sharing options are available on Gutenberg in the Jetpack sidebar.
The JP icon should be available in the top bar, unless it has been "unpinned"; in that case it can be opened (and re-pinned) through the More menu (the ellipsis icon in the right end of the top bar).

![Screenshot 2019-04-09 at 11 44 00](https://user-images.githubusercontent.com/2070010/55794704-cd3a9c80-5abd-11e9-906f-571c9bfea151.png)

![Screenshot 2019-04-09 at 11 44 15](https://user-images.githubusercontent.com/2070010/55794710-d0ce2380-5abd-11e9-95b9-8a1065428b98.png)

Regarding the site-wide Sharing options: there is an issue with them (#22811) that sounds like it's the cause of what is reported here.
I've already opened a PR to fix it (#32107), but it depends on a JP change (https://github.com/Automattic/jetpack/pull/11981), so it will take a while to land.
