### ISSUE TITLE
Media: Uploading high resolution images on Atomic sites causes "HTTP Error" and does not properly display thumbnail

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#32095]
#### Steps to reproduce
1. Create Atomic site.
2. Open media library. Calypso or WP Admin will both work (or not work, really).
3. Upload a very large image. As in resolution, not filesize (filesize seems irrelevant). Aim for 7000x7000 pixels or larger.
4. On Calypso, you'll see the error:

~~~~
1 file could not be uploaded because an error occurred while uploading.
~~~~

On WP Admin, you'll see the error:

~~~~
HTTP error.
~~~~

#### What I expected

For image to upload properly, including associated metadata, usable as featured images, etc.

#### What happened instead

Error displays, implying image is NOT uploaded. But it is, it's just doesn't seem to be categorized as an actual image along with relevant metadata like image resolution, a thumbnail, etc.

#### Browser / OS version

Pop!_OS 18.10 / Chrome Version 73.0.3683.86 (Official Build) (64-bit)

#### Screenshot / Video

![Annotation on 2019-3-0 (1)](https://user-images.githubusercontent.com/10121835/55688263-4ca06280-593c-11e9-8b89-e0f49b75de74.png)

![Annotation on 2019-3-0](https://user-images.githubusercontent.com/10121835/55688264-4f02bc80-593c-11e9-8b4a-7eb38c8f3122.png)

Examples of image that causes the issue:

![Vae-Victus-Shirt-Template](https://user-images.githubusercontent.com/10121835/55688275-6346b980-593c-11e9-821a-6675381db970.png)

#### Context / Source

1941463-zen

10064325-hc

Seems similar to:

https://github.com/Automattic/wp-calypso/issues/20349

Except I can replicate consistently on Atomic sites when using high res images. In each case, shrinking the image to something smaller (below 8000x8000 pixels works most consistently for me, but in the above example file, it's 7500x7500 pixels and still breaks things) fixes the issue.

Issue does NOT affect simple sites.

**Comment by lancewillett** [comment]
Moved to p9o2xV-lV-p2
