### ISSUE TITLE
Purchases: Domains shows twice in Purchases with different prices

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#32094]
I've had users report that they see two different prices to renew their domain, but I haven't been able to replicate this. I had a user in chat recently who was able to recreate the situation and advise me of their steps. In the user report, the said the link where they see this is [#](https://wordpress.com/me/purchases/thetravellerseyes.blog/10601353
).

The first link shows a price of £18.65 in this case while the second one shows a cost of £11 (cost of domain mapping only).

#### Steps to reproduce
1. Click on My Site at the top
2. Click domains and then the custom domain
3. Click Payment Setting
4. Click the back arrow to see two purchases for the domain:

![domain shows twice in purchases](https://user-images.githubusercontent.com/30090682/55684557-71043b00-594c-11e9-939b-406000c5e645.jpg)

#### What I expected
I didn't expect the last item in the list of purchases.

#### Context / Source
Reported in #6600737-hc

I was unable to replicate this issue when I SU'ed into the user's account and I can't replicate this in my own account, but the user's screenshot clearly shows the issue.

**Comment by arunsathiya** [comment]
I had a look at this as well, but I am not seeing what's shown on the image. It does not happen on my account either. @Automattic/cobalt, not sure what might be causing this, but would this be something you can take a look at? Thank you!

I am tagging this with low priority because this seems to be isolated to an account.

**Comment by damiannep** [comment]
I've had several user reports of this in the past, but have never had someone send me a screenshot before now, so was always a bit skeptical since I can't replicate it. Will post any other reports i come across here in future.

**Comment by damiannep** [comment]
Here is an old case of the same thing reported in #1776737-zen. User also included 2 screenshots in their message, but didn't have steps to replicate:

![price2](https://user-images.githubusercontent.com/30090682/56423953-9713ce80-62ae-11e9-878a-6d1bb17c61eb.png)
![price1](https://user-images.githubusercontent.com/30090682/56423955-9713ce80-62ae-11e9-9b75-c4180a3ee6e1.png)

**Comment by damiannep** [comment]
Another case of this in #2633596-hc. Video from user - https://cld.wthms.co/HjbLmQ

I can't be the only one encountering these...

**Comment by damiannep** [comment]
I finally had a case in a ticket where I could see the domain purchase twice in the user's Purchases. Ticket #2007487-zen. Issue no longer exists after user renewed domain. You can see one purchase for $18 and one for $13. 

![$18 and $13 domain purchases](https://user-images.githubusercontent.com/30090682/57406598-68b84d80-71e1-11e9-9252-08f3680c3155.gif)

**Comment by damiannep** [comment]
I'm removing the Low priority as this issue is not isolated to one account.

**Comment by klimeryk** [comment]
Fixed by D35702-code, as mentioned in https://github.com/Automattic/wp-calypso/issues/37671#issuecomment-555963553 - props to @DavidRothstein for the fix! 🙇
