### ISSUE TITLE
Editor: Media: Search media by default when selecting featured image

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#321]
Suggested by @mtias:

> think it'd be nice to remove all the filters and have the search opened by default "search your images" for this use case.

Currently, when selecting a featured image the media modal appears and defaults to the Images filter while disabling all other filtering options (audio, documents, etc.)

**Comment by alisterscott** [comment]
This hasn't moved in 18 months despite work on featured images, closing for now.
