### ISSUE TITLE
Exporter: Redundant media library export failure notice for sites without media files

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#32109]
#### Steps to reproduce 

- With a site without media library files, visit https://wordpress.com/settings/general 
- Click on the `Export` section available on that page

#### What is expected 

There is no `We couldn't export your media library at the moment. Please try again later.` failure notice shown.

#### What happens instead

A `We couldn't export your media library at the moment. Please try again later.` failure notice appears out of nowhere. In particular, it can be noted that this happens without having to click on `Export all` button for `.xml` export, or `Download` for media library files export.

No warnings/errors shown on console.

![Screenshot 2019-04-08 at 19 51 13](https://user-images.githubusercontent.com/18581859/55731525-06302e00-5a38-11e9-81e5-4843ee123ec4.png)
![Screenshot 2019-04-08 at 19 51 26](https://user-images.githubusercontent.com/18581859/55731527-06302e00-5a38-11e9-84b7-9b466d781a19.png)

The failure notice seems to be redundant and should not appear unless the media library exporter is used, and fails.

#### Notes

I have noticed that this happens particularly for sites without media library files and for sites with one or more media library files, that notice does not appear.

![Screenshot 2019-04-08 at 19 55 17](https://user-images.githubusercontent.com/18581859/55731697-4099cb00-5a38-11e9-96c4-9ca8df5030f6.png) 

#manual-testing

**Comment by arunsathiya** [comment]
This is still an issue.

**Comment by Aurorum** [comment]
PR for this issue in #41255. :)
