### ISSUE TITLE
Block Editor unexpectedly crashing [6]

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#32120]
See p2EDhh-Hn-p2
See WordPress/gutenberg#14873

# Key issue

When performing normal expected tasks in the editor it crashes with the error display.

> This is a tracking/meta issue to follow work in the core editor and share our own debugging journey - yay type errors.

---

## Crashing page attributes

In [`PageAttributesParent`](https://href.li/?https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/page-attributes/parent.js#L30) we were receiving invalid data for the pages and page titles.

I observed an invalid JSON response to the `/wp/v2/sites/{siteId}/pages` response. The response was 2.34 MB large, the second page was 1.94 MB large and also invalid, the third and final page was 581 KB and valid JSON.

The invalid part of the response came in as truncated text. Of note is that we appear to be requesting the entire post contents for all pages on a site just to fill in the parent post selector. Both truncated responses weigh in at around 360 KB gzip'd. If I `curl` the request from a command line I receive the full message. They took 2601 ms and 2348 ms while the good one took 899 ms to complete.

There is no `Content-length` header

| Site | # of Pages | Returns invalid JSON | Notes |
|---|---|---|---|
| I | 114 | Y | Shows console error |
| N | 103 | N | Shows console error |
| W | 228 | Y | Shows console error |
| Local test | 3 | Y | Shows console error |

Although I see the error in the console from the iframe'd version of the editor from within Calypso I cannot reproduce the crash. When I use the editor directly from `wp-admin` the editor does indeed crash as soon as the response with invalid JSON returns.

፨

After more inspection I think that in the case of the page attributes it's not the API call causing the problem but the assumption that there will be pages which cases the problem. We don't have a state to show "API request failed" either, which would help here.

1. Editor asks for all pages on a site in order to show list of page titles
2. Very large responses break for some reason I don't yet understand
3. When the API requests fail to parse as JSON it is `apiFetch` which throws an error but the editor goes on
4. The editor assumes that there will be `items` in `PageAttributesParent` but `getRequestEntities(…)` returns `null` so we get a type error. Bloody type errors.

፨

After even more inspection I found that we're making a second request to grab the next page of results of _pages_ except we're making a request to `/wp/v2`

```
https://public-api.wordpress.com/wp/v2/sites/{ siteId }/?_envelope=1&_envelope=1&per_page=100&exclude[0]=X&parent_exclude[0]=X&orderby=menu_order&order=asc&context=edit&_locale=user&page=2
```

The fact that we have two copies of `_envelope=1` makes me suspicious that we're seeing an invalid `next` link due to issues in the backend. Backend is sending…

```
https://public-api.wordpress.com/?_envelope=1&per_page=100&exclude%5B0%5D=X&parent_exclude%5B0%5D=X&orderby=menu_order&order=asc&context=edit&_locale=user&page=2
```

፨

In `wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php` we call `rest_url( … )` and that strips away the path from the intended endpoint URL. at that point…

```php
$path = sprintf( '%s/%s', $this->namespace, $this->rest_base ) === 'wp/v2/pages';
rest_url( $path ) === 'public-api.wordpress.com';
```

It's this stripping-away of the REST API endpoint that causes the request for the second page of _pages_ to return the initial REST discovery URL and the editor accepts that the list of returned endpoints are legitimate pages, but of course they have no `.title` property, thus CRASH

፨

To recap this is what is triggering the crash, though I haven't been able to pin down why the URL gets mangled…

 1. Editor asks for list of pages on site with large payload (# of pages ✖️ size of the pages' contents)
 2. Server responds with broken `next-link`, though I was able to correct this by removing a filter that replaced `[original domain part]/wp/v2/pages` with `https://public-api.wordpress.com` - this filter was wiping out the path and causing the `next-link` to point to `/`, returning the list of API endpoints instead of the list of pages. _With the `fetch-all-middleware` in there_ the editor automatically requests the endpoint list, then it assumes that the list of endpoints are valid pages, assumes that they have a `.title` property, and crashes as it tries to use them.
 3. In removing the middleware or simply preserving the path I was able to get the proper `next-link`, however, something (presumably the `fetch-all-middleware` is making a request for `https://public-api.wordpress.com/wp/v2/pages/https://public-api-wordpress.com…` and that's returning a `404` (of course). I don't know where this additional domain part is getting concatenated onto the existing `next-link` or why. The result of removing the middleware though is that instead of crashing, the editor never gets the page list.

## `500` Error causing broken UI and missing elements

See p7H4VZ-2bQ-p2

**Comment by iamgabrielma** [comment]
Adding 1938541-zen here to be sure to follow-up when this is resolved.

**Comment by lizkarkoski** [comment]
Another report of this error using Gutenberg for galleries. This report is from the forums: 
https://en.forums.wordpress.com/topic/the-editor-has-encountered-an-unexpected-error-4/

Initially we were able to clear the error through some browser troubleshooting but the issue returned a few days later.

**Comment by pauljacobson** [comment]
In case this isn't added here yet, another instance of this issue: 2009785-zen

The user is waiting for feedback so I'm adding the label.

**Comment by zdenys** [comment]
Another case 2070333-zen where a follow-up would be great once fixed.

**Comment by glendaviesnz** [comment]
Have checked and the symptoms are the same as #33147. This was fixed by D29347-code which has been deployed. 

I verified with editor directly from `wp-admin` with a site with 120 pages and PageAttributes is now requesting the second page of results with the correct API path.
