### ISSUE TITLE
Emoji such as heart smilies do not show up in titles in various locations

### ISSUE THREAD

**Issue by martinremy** [Automattic/wp-calypso#3212]
I noticed that heart smilies ( <3 ) in the titles of posts or in comment text don't show up in web notifications or notifications in the mobile apps, so I thought -- the latter was reported separately somewhere.

To reproduce.  Write a post with "<3" in the title.  Get someone to like it.  The <3 will be eaten by a rogue parser in web and mobile app notifs, so maybe something on the API side?

Pre-populated examples available on request :)

**Comment by alisterscott** [comment]
I reproduced this on desktop web and mobile apps

<img width="400" alt="desktop" src="https://cloud.githubusercontent.com/assets/128826/15060507/88faee7e-136e-11e6-84ab-3190deb1f8fe.png">

![fullsizerender 1](https://cloud.githubusercontent.com/assets/128826/15060523/b02ce5f6-136e-11e6-9740-fab2d88a0419.jpg)

Oddly, it works fine on an Apple Watch

![img_0193](https://cloud.githubusercontent.com/assets/128826/15060530/c73f4324-136e-11e6-8f67-1477802d86b6.PNG)

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the following testing steps:

1. Start at https://wordpress.com/post 
1. Add a title with emoji in it
1. Publish the post
1. Log in as a different user and like the post
1. Log back in as post author and check notifications

<strong>Result:</strong> emoji don't show up in titles in the notifications panel

![screen shot 2016-07-25 at mon jul 25 1 59 50 pm](https://cloud.githubusercontent.com/assets/1119271/17115504/c5b1f362-5270-11e6-9201-baf6184e8c38.png)
<sup>Seen at https://wordpress.com/me/notifications using Safari 9.1.1 on Mac OS X 10.11.5</sup>

![screen shot 2016-07-25 at mon jul 25 2 05 39 pm](https://cloud.githubusercontent.com/assets/1119271/17115587/3f15dd86-5271-11e6-96fd-d29d423ec746.png)
<sup>Tested with the Desktop App version 1.3.4 on Mac OS X 10.11.5</sup>

<img alt="img_8252" src="https://cloud.githubusercontent.com/assets/1119271/17115665/abb12da6-5271-11e6-841a-04cf825190f3.PNG" width="400"/>
<sup>Seen at https://wordpress.com/ using Safari iOS 9.3.3 on iPhone 6S</sup>

In comparison, emoji seem to work in comments inside notifications (see first screenshot above) and they work in gmail:

<img width="817" alt="screen shot 2016-07-25 at mon jul 25 1 57 29 pm" src="https://cloud.githubusercontent.com/assets/1119271/17115722/e8abb8c0-5271-11e6-9a73-a616cbcda366.png">

For reference, here is the post showing the emoji in the title right after it was published:

![screen shot 2016-07-25 at mon jul 25 1 46 11 pm](https://cloud.githubusercontent.com/assets/1119271/17115735/ff06be94-5271-11e6-8013-eccdd526d36d.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10145 using Safari 9.1.1 on Mac OS X 10.11.5</sup>

Emoji are also missing from titles in My Sites > Blog Posts and in the Reader:

![screen shot 2016-07-25 at mon jul 25 2 14 23 pm](https://cloud.githubusercontent.com/assets/1119271/17115877/8fe6eac4-5272-11e6-90b5-e7d575a64ee5.png)
<sup>Seen at https://wordpress.com/posts/design5279.wordpress.com using using Safari 9.1.1 on Mac OS X 10.11.5</sup>

![screen shot 2016-07-25 at mon jul 25 2 15 49 pm](https://cloud.githubusercontent.com/assets/1119271/17115887/988c47c8-5272-11e6-897e-189273dfba0e.png)
<sup>Seen at https://wordpress.com/ using using Safari 9.1.1 on Mac OS X 10.11.5</sup>

Related: #1887

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue as documented above.  The heart emoji itself shows up fine, but the `<3` is stripped.  Seen in Chrome v54 in the Reader, Notifications pane, and Posts list

**Comment by alisterscott** [comment]
I can confirm this is no longer an issue:

<img width="405" alt="screen shot 2017-11-28 at 3 00 59 pm" src="https://user-images.githubusercontent.com/128826/33303143-fff0f8a2-d44c-11e7-9c64-810493722487.png">

🎉
