### ISSUE TITLE
Account Recovery Form: Accept username without URL

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#32131]
#### Steps to reproduce
1. Go to https://wordpress.com/wp-login.php?action=recovery
2. Fill in your username but do not enter a URL
3. Enter in your contact email and a proof of ownership.

#### What I expected
I expected to be able to submit the form.

#### What happened instead
I got an error message: 
> Please provide the username, registered email, or URL of the specific blog you are contacting us about.

![enter URL](https://cld.wthms.co/xsXee4+)

#### Context / Source
Tested after user complaint in #1871534-zen

**Comment by jsnajdr** [comment]
Hi @damiannep :wave: The Account Recovery UI lives in the wpcom repo rather in Calypso. Please submit the issue as a wpcom Trac ticket.

**Comment by damiannep** [comment]
Thank you @jsnajdr. Created issue - #8143-wpcom Trac
