### ISSUE TITLE
No failure notice when invalid credentials are entered

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#32154]
#### What happened

Manually entering a garbage password on a site results in a notice saying "Testing connection..." It never changes. An error shows in the console:

![image](https://user-images.githubusercontent.com/1123119/55821851-a24f4900-5abb-11e9-9c52-9a7860c0a2f4.png)

#### What is expected
There should be a failure notice (it already exists, but isn't showing) to let the user know something is wrong with the credentials.

**Comment by oskosk** [comment]
This was fixed the day after this issue was filed in https://github.com/Automattic/wp-calypso/pull/32180. Closing.
