### ISSUE TITLE
Tiled gallery + Boardwalk theme: margin issues resulting in clipped/cropped images

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#32151]
#### Steps to reproduce
Visit test draft post here: https://wematter.blog/?p=1165&preview=true

The images on the second row of the tiled gallery are clipped:

![Image](https://cld.wthms.co/ACbepc+)

In the block editor, the gallery looks correct. Disabling other plugins and also trying Health Check (with JP) gave the same issue. It appears the theme has the following code that is resulting in the issue:

```
@media screen and (min-width: 768px)
.wp-caption.caption-big, .image-big {
    display: block;
    margin-bottom: 24px;
    margin-left: -72px;
    width: 768px;
    max-width: 768px;
}
```

Removing the `margin-left` seems to fix it.

#### Browser / OS version
Chrome 73.0.3683.86 on macOS 10.14.4.

#### Context / Source

Reported here: 10277547-hc, 1941117-zen

**Comment by tbradsha** [comment]
I recently realized I added this to Calypso instead of Automattic/themes, as originally I thought it was a Calypso issue. That said, I don't see any files associated with the Boardwalk theme in Automattic/themes repo, so I'm not sure where to move this.

**Comment by suyogyashukla** [comment]
Moving this to automattic/themes#726
