### ISSUE TITLE
Posts: List is fragile due to API request including unneeded data

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#32159]
Atomic sites (and likely Jetpack sites as well) frequently experience issues with Calypso's post list displaying empty due to issues with the API call when the site does in fact have valid posts that appear normally in WP Admin.

The exact cause varies (examples include reblogs, MP3 encoding, context=edit, and general timeouts) but they all result from the API requesting too much information that it cannot handle properly and that is not needed to render the posts list. 

@donpark summarized the issue:

> To show a list of posts, it doesn't need post content nor list of attachments. But Calypso is using the endpoint to get much more than what it needs immediately because:
> 
> > The posts in Redux state are shared by all components that query lists of posts of any type. For example, the SEO preview of a post uses the content to create excerpts or find the first image or other media in the post content.
> 
> One for all. All for one
> 
> Since:
> 
> 1. including everything related to each post is the default behavior of post listing API endpoint and
> 2. getting everything can fail fatally (shortcode, bad post meta, etc),
>
> 3. wp-admin's post listing page does not fail because it only queries what it needs when it needs them. I think Calypso will have to do the same.

Specific cases and additional notes can be found in 353-gh-atomic

**Comment by jsnajdr** [comment]
When querying posts for any purpose, Calypso never specifies the `fields` list on any of the post-fetching REST requests, always fetching the whole post object. It's always been so, even in the pre-OSS Flux version of the Posts Store.

And it's true that we should fetch only some curated subset of `fields`, like we've been doing for sites for some time.

Even in the basic post list, however, the `content` attribute is used to pick a "canonical image" for the post thumbnail. First, content is scanned for media, and the canonical image is then picked from these media.

**Comment by donpark** [comment]
> When querying posts for any purpose, Calypso never specifies the fields list on any of the post-fetching REST requests, always fetching the whole post object. It's always been so, even in the pre-OSS Flux version of the Posts Store.

This bug goes deeper so, even if `fields` were specified, API endpoint will try to grab more than it needs at the implementation level. At the design level, there is a lack of `list` notion in caps and context..

> Even in the basic post list, however, the content attribute is used to pick a "canonical image" for the post thumbnail. First, content is scanned for media, and the canonical image is then picked from these media.

We'll have to either nix that feature or reimplement it on the server-side, in a job when a post gets inserted/updated. I think sacrificing nice-to-have feature to make must-have  functionality robust is fair exchange.

**Comment by kriskarkoski** [comment]
#2235891-zen

**Comment by kriskarkoski** [comment]
#2251436-zen

This was another issue with audio attachments having null bytes.

**Comment by samiff** [comment]
p9F6qB-4kl-p2

Invalid block reference in a couple pages causing entire post list to fail from Calypso.

**Comment by lancewillett** [comment]
Another case p9F6qB-4xb-p2

API returns 400 error

**Comment by ccwalburn** [comment]
Another case: 3103518-zen

This is a Simple site that has Embed Code from Getty Images in most of their posts.

**Comment by druesome** [comment]
#3162662-zen

Posts were not loading due to attachments with large postmeta that had `post_parent`'s.  Had to remove the `post_parent` on all images to get the post list to load.  We've also had similar cases of posts with huge post revisions.  It doesn't seem necessary to load `post_parent` data to generate the post list unless they were pages.

**Comment by kriskarkoski** [comment]
One cause on Simple sites look to be [Getty embeds](https://en.support.wordpress.com/images/getty-images/). Here's a comparison of a published post with Getty embeds, a cloned draft with the embeds present, and the same draft with Getty removed:

<img width="1440" alt="Screen Shot 2020-08-14 at 11 19 42 AM" src="https://user-images.githubusercontent.com/1900444/90265204-39e74900-de20-11ea-86b6-78427f78f961.png">

With the embeds removed the loading time drops by over 1s. Multiplying this across 20 posts explains the slow loading times this user is seeing.

**Comment by bsanevans** [comment]
Another case: 3487618-zd-woothemes where a post's editor, and the list of posts, would not load.

The recent post had `<p style="text-align: justify;">` and other non-Gutenberg oddities throughout. (No embeds, just badly formatted paragraph blocks.) Manually fixing the code in a text editor and pasting it back in fixed it.

**Comment by danielbachhuber** [comment]
@kriskorn Per [your comment here](https://github.com/Automattic/atomic/issues/353#issuecomment-993581203) and @donpark's [comment](https://github.com/Automattic/atomic/issues/353#issuecomment-485918388), is it fine to close this issue too? It doesn't seem like there's anything actionable here, although we could potentially look into better diagnostic tools the next time it comes up.

**Comment by kriskorn** [comment]
@danielbachhuber As far as I understand the issue, we over fetch data needed to lists posts in Calypso. It gets the whole post content, which can contain a lot of data that could break the post list. An example was the Reusable blocks infinite loop issue - p7DVsv-alB-p2 where something inside of the content of the posts made the post list inaccessible.

If possible, I think we should fetch only the needed metadata and post title to list the posts in Calypso. I do not see why getting the post content would be necessary, as it is not used anywhere. Maybe I am misunderstanding something.

Though, since we have really not had reports since November 2020, I think we can assume that things work better and this may not really be an issue, so could also be closed and looked into if ever necessary in the future.

**Comment by danielbachhuber** [comment]
@kriskorn Yep, makes sense. I think it's unlikely we'll refactor the post list, but not impossible. I'd like to punt this until the issue presents itself again, and review at that point.
