### ISSUE TITLE
Gutenframe: Revisions are not respected on post update.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32153]
Gutenframe uses the Calypso Revisions UI, rather than core. However, while, it displays and behaves properly, clicking Update to save the previous revision will result in the most recent version being stored (and then refreshed in the editor).

Steps to reproduce:

1. Load a post in `/block-editor/post/:site/:postId` that has revisions (or create a new post and add revisions).
2. Open the revisions UI in the block editor, and select a previous revision.
3. Note that it displays properly now in the editor.
4. Click the Update button.
5. The editor refreshes, and the previous version (not the loaded revision) will be displayed.
6. Confirm it's the wrong version on the front-end too.

**Comment by kwight** [comment]
I dug into this a bit. Everything seems to be fine in `onLoadRevision`; I can see the payload being properly applied, and that the `updatePost` call results in a proper updated "current post". Then, after we're back in the editor, following autosaves will also be correct. But when clicking Update to save, the form data passed will be the editor data from before the revision selection. It's also interesting to note that this issue doesn't happen in core, because Gutenberg does a full page reload with the returned revision ID as a query param. (I tried directly calling `savePost` within `onLoadRevision` after the `updatePost`, but no go.)

@mmtr, maybe you can you see what I'm missing here?

**Comment by mmtr** [comment]
I noticed that only the title is reverted. The post content in both the editor and published view remains with the content of the selected revision after updating the post.

https://cloudup.com/cjgjg_wgg9X




Am I missing any step?

**Comment by mmtr** [comment]
Fix ready on D26715-code

**Comment by kwight** [comment]
Ah, there we go, that's it – thanks! D26715-code ready to go 👍

**Comment by mmtr** [comment]
Closed by D26715-code
