### ISSUE TITLE
RichText not found on `gutenberg-wpcom.js`

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#32164]
On my Simple site's wp-admin dashboard (i.e. not on the editor page) I see following console error:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/87168/55856285-86f34500-5b72-11e9-910a-743a0d1c99ec.png">

```
wp.richText is undefined
```

Coming from `RichTextUnderlineButton`'s `wp.richText.registerFormatType()`

Note also cache buster date which is pretty old but maybe it doesn't matter if `m` arg changes with modifications?

FYI @Automattic/lannister

**Comment by Copons** [comment]
@simison Working on it in D26728-code. Thanks for reporting! 🙇

**Comment by Copons** [comment]
Forgot to close this one!
Fixed in D26728-code.
