### ISSUE TITLE
Jetpack Checklist: Add upsells when on a free plan

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#32167]
With the Jetpack security checklist enabled, when the user is currently on a Free plan, there isn't a clear path on how to get Jetpack Backups or anti-spam protection. 

It would be nice if we display upsells for those just below the checklist, as a natural way for the user to further protect and secure their site.

This idea was brought up by @jeffgolenski while testing the security checklist: https://cloudup.com/cqK-IkaWi3O

**Comment by tyxla** [comment]
Still valid IMHO. cc @Automattic/jetpack-voyager in case this is something they might want to consider.

**Comment by monsieur-z** [comment]
Recorded here: 1164141197617539-as-1199991542916123

**Comment by monsieur-z** [comment]
Actually it's safe to close this issue. The checklist is soon to be removed.

**Comment by tyxla** [comment]
Good to know. Thanks! Will close.
