### ISSUE TITLE
Jetpack Checklist: Put some focus on the checklist itself after immediate onboarding of customer

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#32171]
With the Jetpack security checklist enabled, the "My Plan" page is quite a big page:

![](https://cldup.com/IM9xvgo_Ga.png)

It would be useful if we could put some focus on the checklist section, possibly by reducing the contrast of the other sections or blurring them when the checklist is not finished. Let's think about how we could achieve that.

This idea was suggested by @jeffgolenski while testing the security checklist: https://cloudup.com/cqK-IkaWi3O

**Comment by jeffgolenski** [comment]
![checklist visual focus](https://user-images.githubusercontent.com/214813/56685290-9a88ca80-669f-11e9-81ce-d5bf3d76ceef.jpg)

I've outlined the current vs proposed flow for the checklist. It may be something that @fditrapani & @shaunandrews could benefit from on the wpcom side of things as well. I'd love your feedback.

My intent here is to focus on the thank you / loading message above the checklist immediately after purchase (we're loading akismet and vaultpress here and automatically completing tasks). 

Currently, we've taken customers from wp-admin, into our onboarding, and then introduce them to a brand new layout (calypso), that sort of looks like wp-admin, but sort of doesn't. It's a lot to take in all at once. 

The the "plan setup" loading is done, I'd like to kind of fade in the sidebar, masterbar, and other things. So there's a clear linear focus of the checklist, the customer won't just be thrown into a new UI with a million possible actions on large screens.

**Comment by simison** [comment]
Shall we hide these on mobile, too?

<img width="391" alt="image" src="https://user-images.githubusercontent.com/87168/57538866-f2872880-7351-11e9-832f-ec3354ff01d8.png">

**Comment by simison** [comment]
Should we use [`FeatureExample`](https://github.com/Automattic/wp-calypso/tree/88f717c18a6818bee0b4077095d61c9554bae918/client/components/feature-example#readme) component here that fades the content inside it or should the whole checklist be visible instead — albeit still not really readable?

> _Feature Example is a component used to render an mocked example of any feature. It renders whatever children it receives. The example is covered by a layer of fading gradient that gives the user a sense of UI that they are missing._

Quick test using `FeatureExample` with sidebar still visible:

<img width="1592" alt="Screenshot 2019-05-10 at 18 36 17" src="https://user-images.githubusercontent.com/87168/57539288-d89a1580-7352-11e9-8ce0-fa500bd9f468.png">

**Comment by simison** [comment]
Some initial testing how this feels can be done in https://github.com/Automattic/wp-calypso/pull/32951
