### ISSUE TITLE
Jetpack Checklist: Clarify why users can't change automatic tasks

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#32170]
Currently, the tasks that get finished automatically don't have a "change" button. We could do better clarifying why that is the case:

![](https://cldup.com/P9tfpyrNVo.png)

This was suggested by @jeffgolenski while testing the security checklist: https://cloudup.com/cqK-IkaWi3O

As Jeff pointed out, several options we have are for example:

* Display a "premium service" label there.
* Some sort of a gridicon.
* Maybe something to say "this is all set ✅"

**Comment by jeffgolenski** [comment]
I want to make sure we're keeping the Ui as uncluttered as possible, so only if we find customers are asking us about this, will be implement my suggestions.

**Comment by jeffgolenski** [comment]
Closing this for now in favor of: https://github.com/Automattic/wp-calypso/issues/32557
