### ISSUE TITLE
Comments and Likes Won't Post on First Try Using Firefox

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#32186]
The issue is that one cannot like or comment on posts on many WPcom sites. Chrome works, Firefox and Safari do not. One must reload twice to get Likes and Comments to work. This report is focused on Firefox since I was able to replicate the issue here.

In testing we went through all the browser troubleshooting steps (cache, extensions, do not track) and now have a clean install of Firefox still experiencing the issue. This has been replicated it on two different networks, two different computers, on two different versions of windows (including 10) by the reporter and also on my end using a MacBook Pro on a wifi network. 

This appears to be an issue only on WordPress.com sites with a custom domain.
Console logs and screenshots of the reporter's error results on #1947820-zen.

This is possibly connected to https://github.com/Automattic/wp-calypso/issues/30675

#### Steps to reproduce
1. Starting at URL: https://jolenemottern.com/2019/04/09/i-could-never-be-a-breck-girl/
2. Leave a comment. 
3. Notice it will not post.

#### What happened instead: I could not post as seen in my screencast on https://cloudup.com/ceKWMoudnue. The errors I got were:

![screenshot](https://cld.wthms.co/AULsZ7+)

#### Browser / OS version
Firefox - 66.0.2 (64-bit)

#### Screenshot / Video

https://cloudup.com/ceKWMoudnue

#### Context / Source
#user-report

**Comment by richardeschloss** [comment]
For what it's worth, I see a lot of other "loading mixed (insecure) display content" errors, just on page load.
![image](https://user-images.githubusercontent.com/5906351/55933306-c60caf00-5be1-11e9-86b8-f19a3058cd24.png)

**Comment by DanAntion** [comment]
> 
> 
> For what it's worth, I see a lot of other "loading mixed (insecure) display content" errors, just on page load. This usually occurs when you navigate to the secured "https" version of the website and the page attempts to load resources over an insecure transport (http)
> ![image](https://user-images.githubusercontent.com/5906351/55933306-c60caf00-5be1-11e9-86b8-f19a3058cd24.png)

Would this explain why reloading the page always seems to work? Also, If I paste the link into an existing page, or even if I open the link in a new Tab, instead of a new Window, the Like button seems to load. 

I've looked into forcing Firefox to use https, and I've also looked into whether Bitdefender could be causing this issue. Bitdefender has suggestions for preventing certificate handling problems in Friefox - I followed those instructions, to no avail.

**Comment by richardeschloss** [comment]
Also just curious, may I ask what Firefox extensions / add-ons those are at the top right? Does the same behavior occur if the extensions are disabled? (I know it's not an ideal solution, but it may help to still know). I.e., are there any script blockers or ad blockers installed in firefox but not in your other browsers?

**Comment by DanAntion** [comment]
Other than Bitdefender and one Firefox extension listed as required, there are no extensions running. In fact, I uninstalled Firefox and reinstalled a clean copy with nothing added.  I have done all I can to disable ad-blockers, pop-up blockers and trackers.

As I understand it, Chrome is more accommodating of pages with mixed security content. Many of the blog sites where the like button is not visible (until the page is reloaded) have insecure elements (usually images).

I’ve explored changes to Firefox’s config, but it is difficult to understand which one might be involved.

**Comment by richardeschloss** [comment]
Ok the information you provided is helpful. Just want to disclose: I don't actually work for Automattic, I'm volunteering my time on this out of pure interest to be helpful...and I'll try to be as helpful as I can be. 

My only other question now is...in the event I have to leave a test comment on your friend's blog, such as "testing comment post", can you please give your friend the heads up? I don't want your friend to get spammed or feel like she's being spammed. (I might be able to troubleshoot without resorting to this...but I just didn't anyone to receive unwanted surprises)

**Comment by DanAntion** [comment]
I’ll let her know. Thank you.
