### ISSUE TITLE
Jetpack Settings - Create beautiful Beautiful Math setting

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#32183]
Beautiful Math will no longer be on by default. Because of this, we need to make a setting for it visible in Jetpack and Calypso settings.

> Use the LaTeX markup language to write mathematical equations and formulas

Copy for info popover:

> LaTeX is a powerful markup language for writing complex mathematical equations and formulas.

Details in Automattic/Jetpack#11931
Jetpack implementation in Automattic/Jetpack#11956

**Comment by MichaelArestad** [comment]
Updated popover copy to match this: https://github.com/Automattic/jetpack/pull/12040
