### ISSUE TITLE
Olsen Theme Enhancement Settings Overwritten by wp-admin site settings

### ISSUE THREAD

**Issue by wpericam** [Automattic/wp-calypso#32191]
#### Steps to reproduce
1. Start with an AT site with theme Olsen installed and more than 6 posts
2. Change feed to 6 posts under My Site > Settings > Writing > Feed Settings
3. Change Theme Enhancements Infinite Scroll to load more posts with button
4. View the site and it loads with all post coming up as you scroll

#### What I expected
I expected that changing the _Theme Enhancements Infinite Scroll_ to _load more posts with button_  would stick and the site would display 6 posts and then have a button to load more posts. 

#### What happened instead
Reload Page and the _Theme Enhancements Infinite Scroll_ setting jumps back to _load more posts upon scrolling_ 

I was able to change it by going to site.com/wp-admin and changing the setting under Settings > Reading > unchecking infinite scroll 

#### Browser / OS version
Chrome Chrome 72 on macOS (Mojave)
and again after updating to Chrome Chrome 73 on macOS (Mojave)

#### Screenshot / Video
Screencaps, site links, and original user details at zd-1947738

#### Context / Source

#user-report

-->

**Comment by lancewillett** [comment]
I believe this is intentional; if someone is using Jetpack or WP.com the global infinite scroll settings will override the theme settings.

Also noting this isn't a Calypso bug exactly... would maybe be a theme bug or possibly WP.com backend (Trac).
