### ISSUE TITLE
Editor: hidden post text entry during input

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#322]
If your cursor is active in the top part of a post, and you scroll down, it is then out of view. If you start typing in this state you cannot see what is being typed.

What I Did:
- Scrolled down while drafting a new post (Visual Editor)
- Typed some post contents
- Env:
  - Macbook Pro Retina 15" Late 2013
  - Browser: Chrome stable.
  - Resolution: "Default for display"
  - Window "zoomed" full screen

What I Expected:
- The things I typed to be visible & not obscured by editor chrome
- If the caret happens to be obscured when entering text, it should bring the insert location into view.

What Actually Happened:
- When the editor bar becomes fixed, the entry box flows beneath it
- The top few rows of the input element become obscured
- The result of typing in this space is only visible once I've scrolled.

Here's a video:
https://cloudup.com/cA2xIIIGbdP

/hat tip jblz for the original report

> So expected behavior would be to pad the mce editor so text never hides behind the toolbar?
> 
> That would be fine, or scrolling such that the top of the entry box is not obscured when typing otherwise would be, but the padding approach seems easier / to have less edge cases.

From timmyc

> Some findings from my testing.  The root cause appears to be the fact we scroll a portion of the editor behind the toolbar and masterbar.  So the behavior will happen when in the first ~110px top part of the editor.
> 
> In the following gif, I keep my cursor on the first line, slowly scroll up and type, and you will notice when I reach the third line - or the point that the editor text region actually scrolls off the top of the browser page, the browser's default behavior kicks in and scrolls the cursor back into view:
> 
> ![scroll](https://cloud.githubusercontent.com/assets/22080/10381622/264c3e7e-6dd1-11e5-8400-1c487aab8502.gif)

From gwwar

> @timmyc scrolling is trigged as a [side effect](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/EditorCommands.js#L654) of the `mceInsertContent` command. Might be worth investigating if adding an [after callback](http://www.tinymce.com/wiki.php/api4:event.tinymce.Editor.ExecCommand) or [before callback](http://www.tinymce.com/wiki.php/api4:event.tinymce.Editor.BeforeExecCommand) is worth it.

From kelly

> [Made] an incremental improvement would be to make the sticky toolbar slightly transparent so you could see that _something_ was happening behind it. It also makes the stickiness more apparent because it adds depth. 
> 
> ![transparent](https://cloud.githubusercontent.com/assets/5835847/10469939/ab7bc0b2-71c6-11e5-9a56-9ee3061e354b.gif)
> 
> It would be nice if it could act more like Google Docs:
> 
> ![back up](https://cloud.githubusercontent.com/assets/5835847/10493652/84f8a51e-726f-11e5-9f0f-30f3b24dac96.gif)

**Comment by alisterscott** [comment]
Retested 12 May 2017: no longer an issue: text is bought into focus when typing after scrolling
