### ISSUE TITLE
twentynineteen-sb: can't edit page title

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#32209]
When using the twentynineteen-sb theme, we cannot set a page title for new pages created from the pages section.

Steps to Reproduce:

1. Create a new site starting from https://wordpress.com/start/onboarding
2. Select Business in the first prompt, proceed with site creation, and select any plan
3. Navigate to https://wordpress.com/pages and select your newly created site
4. Add a page and save 
Expected: Some controls to edit page title
Actual: Page shows as "untitled" in list

Switching themes is available as a workaround in the interim.

cc @mattwiebe @apeatling

**Comment by mattwiebe** [comment]
D26887-code should fix this

**Comment by mattwiebe** [comment]
Code shipped, this should be done.
