### ISSUE TITLE
InlineHelp: Help button dot is rendering "below" the help icon

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#32216]
![image (2)](https://user-images.githubusercontent.com/191598/55984251-111ed480-5c6b-11e9-8783-74742872f8eb.png)

After creating a new account (`/start/onboarding/` choose the business segment) I land in Gutenberg. However the help icon looks broken. The icon itself seems to render over-top of the pink dot.

**Comment by kwight** [comment]
I thought this might be Gutenberg-specific, but the Calypso editor looks out of alignment too:

<img width="89" alt="Screen Shot 2019-04-11 at 12 13 15 PM" src="https://user-images.githubusercontent.com/349751/55984857-4fa89500-5c53-11e9-95da-295c5d628cfe.png">

@sixhours Is this the sort of thing y'all look at? Feel free to throw it back if not :)

**Comment by sixhours** [comment]
Thanks for the heads-up! Added to the Fixing the Flows project.

**Comment by Copons** [comment]
Just FYI this was caused by a piece of CSS left over from the Gutenlypso (Gutenberg native in Calypso) days, that was not playing well with Gutenframe (Gutenberg loaded in an iframe in Calypso).
