### ISSUE TITLE
Sharing Settings: Google+ option appears in Sharing settings

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32218]
<img width="1212" alt="Screen_Shot_2019-03-20_at_7 05 38_PM" src="https://user-images.githubusercontent.com/2124984/55985141-2b59b200-5c6d-11e9-9fe5-8c684ac9de5e.png">

Problem: Google+ has been shut down and shouldn't be available as an option anywhere.

What this should look like: The Google+ button should be removed as a default option and as a possibility in general.

**Comment by alaczek** [comment]
We need to think about what happens on the front-end too. Right now if someone has Google+ button enabled, a greyed out button appears on the front-end (visible only to site owner):
![image](https://user-images.githubusercontent.com/4550351/56008167-98795000-5d1e-11e9-9583-e92ad6532795.png)
On hover there's a message:
"The Google+ service has shut down. This sharing button is not displayed to your visitors and should be removed."

If we remove the button from Calypso, then I think we should also remove it from the front-end.

**Comment by apeatling** [comment]
100% agree this should be removed from the front end at the same time. It's worth looking in to why this wasn't done originally, it seems like a strange choice to leave it there.

**Comment by alaczek** [comment]
Here are the relevant threads/PRs I found:
* https://github.com/Automattic/jetpack/pull/10951
* p1HpG7-61o-2
* p58i-7iC-p2

From reading all this I think the settings in Calypso were missed. It looks like the Google + button is gone from Calypso now though? I just checked on my site where I had it enabled, and it's gone from both Sharing settings (now under Tools > Marketing), and from the front-end (the greyed out version visible only to site owner mentioned above). I looked at PRs merged within the last week, and can't seem to find when this happened. @sixhours can you confirm if it's gone?

**Comment by alaczek** [comment]
Looks like Google + has been removed via Jetpack: https://github.com/Automattic/jetpack/pull/11564
Closing.
