### ISSUE TITLE
Reader: Cursor does not indicate you can click on the "x" to unfollow a tag.

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32221]
<img width="279" alt="Screen_Shot_2019-03-06_at_10 24 34_AM" src="https://user-images.githubusercontent.com/2124984/55987256-1d0c9580-5c6f-11e9-8e67-810afc631f23.png">

If I want to unfollow a tag by clicking the "x" to the right of each tag, the cursor stays as an arrow rather than a hand; it does not behave like a button or link, so there's no indication you can click on it.

**Comment by alaczek** [comment]
While testing the PR I also noticed some odd use of color, that perhaps warrants a separate issue?
![image](https://user-images.githubusercontent.com/4550351/56105135-18e9bc00-5f7e-11e9-98a4-8455a7c0103f.png)
I'm talking about the selected tag specifically - the use of white for the X feels off here - like there's too many colors. What do you think Caroline?
