### ISSUE TITLE
Sharing Settings: Social buttons toggle state appears reversed

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32224]
<img width="1437" alt="Screen_Shot_2019-03-06_at_10 32 25" src="https://user-images.githubusercontent.com/2124984/55988024-d881f980-5c70-11e9-92c1-63930443ee17.png">

Problem: The toggled state of the social buttons seems reversed. When you select a button it changes the opacity so that it looks disabled or not selected.

Steps to reproduce:
1. Visit sharing > sharing buttons
2. Click on Edit sharing buttons.

**Comment by alaczek** [comment]
While we're at it we should also look at the opacity of the inactive buttons (especially if we invert the states as you suggest) as they are a bit unreadable. For context this is how the Icon & Text buttons look like disabled:
![image](https://user-images.githubusercontent.com/4550351/56010360-b2b72c00-5d26-11e9-8b05-c5c87408a8b1.png)
