### ISSUE TITLE
Domains: Add a Domain page is missing navigation

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#3222]
if you click on the ‘add a domain’ button when viewing /domains (or the sidebar 'Add' button) there is no mechanism to get back to your list of domains (other than re-clicking the section-nav 'Domains' tab again).

<img width="764" alt="screen shot 2016-02-10 at 2 17 57 pm" src="https://cloud.githubusercontent.com/assets/437258/12958727/21deff42-d001-11e5-9caa-b3149a574182.png">

The Add a Domain page should have a header cake with a back button since it is another level deeper in the nav structure. It currently cannot have a header cake because that would hide the shopping cart icon. So, this issue is really about finding a more sustainable home for the shopping cart. 

Perhaps a floating element, similar to a global notice? It wouldn't want to obstruct other content, but the global notice's mobile treatment could be a viable solution for the mobile shopping cart. 

cc @breezyskies @mikeshelton1503

**Comment by breezyskies** [comment]
We are going to take a look at some options for this next week.

**Comment by breezyskies** [comment]
As background, there are a couple of tests we'd like to run in the near future related to how we show (or don't show) the shopping cart, but there's still some data collection and test ideation to do here.

In the meantime, we need to solve the navigation issue here. A couple ideas @mikeshelton1503 and I brainstormed:

1) In the header cake:
<img width="760" alt="screen shot 2016-02-19 at 1 49 08 pm" src="https://cloud.githubusercontent.com/assets/3011211/13190109/1c11c7fa-d710-11e5-8bb1-38ab537b339a.png">

This is probably the simplest option for solving the main problem, but doesn't feel very elegant, and seems like a slightly-odd position for it, given that the header cake is usually a stand-alone component.

2) In the search bar:
![image](https://cloud.githubusercontent.com/assets/3011211/13190155/52c46866-d710-11e5-8336-f53d51ed7e4b.png)

Mike suggested floating it to the right end of the search bar. This feels appropriate when you consider that most multiple-item purchases are going to be domains, and puts us in a good spot for testing multiple domain purchase flows.

3) Global notice style you suggested above
> Perhaps a floating element, similar to a global notice? It wouldn't want to obstruct other content, but the global notice's mobile treatment could be a viable solution for the mobile shopping cart.

The original `calypso-ux` designs for the shopping cart were almost exactly what you describe here ([mobile](https://cloudup.com/ivysABPAwLm), [desktop](https://cloudup.com/iVrpag2ssVL)), but they were modified to be more consistent with the existing UI patterns at the time of implementation. This could be a really interesting twist on the original design though, something like:

<img width="290" alt="screen shot 2016-02-19 at 2 05 18 pm" src="https://cloud.githubusercontent.com/assets/3011211/13190399/d94246fa-d711-11e5-99ea-3ba9956c6354.png">

My concern here would be whether it would make sense for this to be persistent, and if so, would it conflict with other global notices.

Thoughts?

**Comment by rickybanister** [comment]
Do we have much data on whether users' checkout flows are fairly 'linear' or not? What I mean by that is do they add something and then immediately purchase it, or do they in significant quantities purchase more than one item (domain) in one shopping session? If it seems to be mostly a linear (add then buy) process maybe the 'floating' shopping cart is less important. 

I could perhaps see a case for (at least testing) a hybrid approach with a floating checkout action and the shopping cart icon to the right of the search.

Additionally, do we need a 'separate' shopping cart? If you're only really purchasing domains ad hoc then can't we just make the search results list into the shopping cart? Meaning: in addition to selected domains card, we add a 'footer' to that area with a subtotal/total and checkout button? As the user selected more domains they would slide up to the selected area.. I can help make a sketch if my rambling is unclear.

**Comment by breezyskies** [comment]
> Do we have much data on whether users' checkout flows are fairly 'linear' or not?

Right now, the flow is biased towards a single product purchase. For example, we push them through the checkout flow as soon as they select a single domain (but if they exit the flow on their own, they could go add more products to their cart). 

We do, however, have plans to test other flows, particularly around multiple domain purchases, but this could be done in a number of ways -- waiting for the user to explicitly click "checkout, or as an upsell in the flow ("get xyz.net, xyz.org, xyz.me for just $x more"). 

>  I could perhaps see a case for (at least testing) a hybrid approach with a floating checkout action and the shopping cart icon to the right of the search.

This is interesting -- it would solve a few flow issues, in addition to the persistence issue I mentioned above.

> Additionally, do we need a 'separate' shopping cart? If you're only really purchasing domains ad hoc then can't we just make the search results list into the shopping cart?

You could potentially purchase a domain and a plan together (or any other combination of products), so domains are not the only issue (although I like your suggestion, might make a good multiple-domain flow test). Again, this is really a matter of the flow we present, and we still have a lot of testing to do here. @mikeshelton1503 also has some ideas in mind for a cart-less flow.

**Comment by klimeryk** [comment]
What's the status of this? Is there something we could improve now?

**Comment by lancewillett** [comment]
If this page gets a rework — please see also #109 and #7096 as they affect the Domains page layout.

**Comment by kriskarkoski** [comment]
This is 4 years old with no traction. Is this still something we plan to revisit or okay to close?

**Comment by klimeryk** [comment]
Not sure why this was not closed by Stale Bot 🤔 Thanks for highlighting it - I'd say let's close it. The work @fditrapani is doing around this whole flow should help with this issue as well.
