### ISSUE TITLE
Sharing Settings: Inconsistent typography on Twitter connection modal

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32223]
<img width="1437" alt="Screen_Shot_2019-03-06_at_10 29 12" src="https://user-images.githubusercontent.com/2124984/55987928-98bb1200-5c70-11e9-917a-e777de114f22.png">

Problem: The light weight title feels out of place. 

Steps to reproduce:
1. Go to Sharing > Connections
2. Connect Twitter
3. See modal.

**Comment by alaczek** [comment]
Yep, font-weight 400 would look much better and be consistent with other areas:
![image](https://user-images.githubusercontent.com/4550351/56010704-0e35e980-5d28-11e9-8d51-792464e1c075.png)

**Comment by sixhours** [comment]
Closed in #32266
