### ISSUE TITLE
Reader: Gray icon indicates Visit Post is disabled (?)

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32228]
<img width="829" alt="Screen_Shot_2019-03-06_at_10 42 59_AM" src="https://user-images.githubusercontent.com/2124984/55990572-fb62dc80-5c75-11e9-9afc-7f2ccb62e0d2.png">

The Visit Post option has a gray icon. Use of color here is confusing. Does this line up with Muriel guidelines? I would expect the icon color to be the same as the link color. The light gray seems to indicate it's disabled.

**Comment by bluefuton** [comment]
We can easily fix this one in Reader only, but it looks like it's the default color value for all popovers with gridicons:

https://github.com/Automattic/wp-calypso/blob/073abff711bceecb9d39be709b78d8ed60a2e72c/client/components/popover/style.scss#L204

Do we want to change this Calypso-wide?

**Comment by bluefuton** [comment]
Just noting that 'Edit Post' appears the same way:

<img width="251" alt="Screen Shot 2019-04-19 at 12 04 34" src="https://user-images.githubusercontent.com/17325/56398183-5c546b00-629b-11e9-8b34-830829b83ce1.png">
