### ISSUE TITLE
People: It's unclear what "Email Followers" means

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32234]
<img width="1561" alt="Screen_Shot_2019-03-06_at_10 23 28_AM" src="https://user-images.githubusercontent.com/2124984/55992804-6f53b380-5c7b-11e9-86b6-b29b27096740.png">

**Steps to reproduce:** 
- Click on "People" in the navigation drawer
- Click on "Email Followers"

**What we see:**
Why is the list of people that you see under "Email Followers" different than my list of "Followers." It's unclear now what "Email Followers" is for and why it's different.

**Comment by alaczek** [comment]
I had to check what the difference is, and I found some explanation in our [support docs](https://en.support.wordpress.com/followers/):

> Followers: A list of people currently following your site.
> Email Followers: A list of people who are subscribed to your blog via email only. They may or may not have a WordPress.com account.

From my experiments it looks like the two lists don't overlap. It does not mean though that Followers don't receive email updates too, which is a bit confusing.

One possible fix would be to include the above description (or its improved version) above the list in each tab. To keep things consistent maybe the other two items (Team, Invites) could have a description too.

**Comment by bluefuton** [comment]
There's also a related bug that means sometimes followers appear in neither tab. We have an internal support FAQ about it (P5PDj3-4Em-p2):

> When viewing their email followers list, users sometimes report that it’s not showing everyone who subscribes by email.
> 
> https://wordpress.com/people/email-followers
> 
> This is a presentation issue that happens because only show followers in these two groups:
> 
> * Email followers who do not have a WordPress.com account
> * Followers who do have a WordPress.com account
> 
> We do not show the email addresses of followers who have a WordPress.com user ID.
> 
> We generally respond to queries like this with:
> 
> > Thank you for reporting this issue. The Email Followers tab currently only shows email subscribers who do not have a WordPress.com account. Our development team are aware of this and plan to make adjustments so that all email followers are shown. Your followers should still be receiving your email updates if they are shown in the main Followers list:
> > 
> > http://wordpress.com/people/followers
> > 
> >

**Comment by obi2020** [comment]
I stumbled on this, too, and wondered if users might mistake "Email followers" for meaning that this is where you send an email (or newsletter) to you list of followers. 

One thing that may improve comprehension is the updates being made by #32693, in which we clarify the header (not the section label!) empty state to better describe with email following is:

**header:** `You have # followers receiving updates by email`
**empty state:** `No one is following you by email yet, but you can [invite up to 10 at a time]`
