### ISSUE TITLE
Reader: Under Followed Sites, the header cake (Search, Recommended) needs design love

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32231]
<img width="758" alt="Screen_Shot_2019-03-06_at_10 55 44_AM" src="https://user-images.githubusercontent.com/2124984/55991958-695cd300-5c79-11e9-8aaa-1afcf0f35df6.png">

The placement of the "x" icons feels off here. They're floating away from the content and it's not clear what they belong to. Perhaps moving these underneath the Follow at the very bottom of the card would help.

**Comment by alaczek** [comment]
These do feel out of place indeed, and without hovering on the "x" I was wondering for a bit what it does exactly in this context. If we pushed the action to the bottom, could we maybe make it a button that explicitly says "Dismiss this recommendation" (or just "Dismiss")?

**Comment by alaczek** [comment]
Moving @blowery's comment and closing the PR, since I think we need to re-think the approach:
> This is something we struggled with in the original designs. How to make the rec's dismissable, but not overwhelm the little content . We tried to make the action subtle since it's not something folks typically do.

> I think in this treatment, the dismiss button has too much visual weight and becomes too visible.

> Perhaps instead, we could change the follow button (which doesn't get much use either) to be a dropdown menu, more like how Facebook and Twitter treat actions on the card? Then push follow and dismiss into the action menu.

**Comment by scalarbane2** [comment]
Let me see what I can come up with.

**Comment by scalarbane2** [comment]
So I was thinking, can I use Muriel (Material) Design cards for that section?

**Comment by scalarbane2** [comment]
Hello y'all! This is what I tried coming up with for the reader page. Let me know your thoughts @cburton4 @drw158 

![Follow - elevation](https://user-images.githubusercontent.com/50745054/58198891-3588ba80-7cc7-11e9-9195-3f831354a854.png)

![Follow](https://user-images.githubusercontent.com/50745054/58198892-3588ba80-7cc7-11e9-85ce-e9c4a4d83778.png)

**Comment by alaczek** [comment]
Can't speak to the idea of using the Material Cards here, but I like how it really helps to tie the  "x" to the specific piece of content in a non-confusing way. I still wonder though it needs further clarification, that "x" is a dismiss action. Maybe I'm overthinking it :)

**Comment by sixhours** [comment]
Using the card component around recommended sites/posts helps give that X button a better sense of place/function. 👍 from me.

**Comment by donpark** [comment]
Is there a PR for this?

**Comment by alaczek** [comment]
Nope, so far we've been exploring design options. Sounds like both me and Caroline agree using cards is the good way to go, so we can now start looking into implementing.

**Comment by sixhours** [comment]
I started working on a PR for this yesterday and made some slow progress; the Recommended Posts section of the reader is put together in an interesting way, so moving the Follow button and the Dismiss button is more of a refactor than I would have thought. I'll keep working on it! It's a fun puzzle. :D

**Comment by jancavan** [comment]
> It's a fun puzzle.

I know this and I remember it being quite confusing!

I don't remember having recommended sites in stream, but they do exist in `/following/manage`. I just wanted to note that site recommendations don't always end up having the same number of lines so adding the Follow button underneath the URL might be tricky (but it might also end up looking fine).

![Screenshot 2019-07-02 20 26 12](https://user-images.githubusercontent.com/4924246/60561281-e0998480-9d07-11e9-9a7d-9317e53f4485.png)

**Comment by lcollette** [comment]
Archiving this issue as we have a PR open.
