### ISSUE TITLE
Signup: Remove /next

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#3224]
With welcome/next replaced in Signup with [the NUX Trampoline](https://github.com/Automattic/wp-calypso/pull/2539) is the /next screen necessary for any flows? Can we remove it from the /me menu? Remove it entirely?

**Comment by lancewillett** [comment]
+1 to removing this. Should we move ahead with it?

**Comment by lancewillett** [comment]
#3347 has a bit of history.
