### ISSUE TITLE
Gutenberg: Dictation duplication on macOS + Safari

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#32240]
#### Steps to reproduce
1. Open any post using Gutenberg (using Calypso interface).
2. Use built-in dictation service: https://support.apple.com/en-us/HT202584

#### What I expected
My spoken word to be dictated.

#### What happened instead
My spoken word results in two copies of what I said, sometimes one nested in the other.

#### Browser / OS version
Safari 12.1 on macOS 10.14.4

#### Screenshot / Video
![Image](https://cld.wthms.co/efIOTU+)

#### Context / Source
Perhaps it has something to do with the way Apple's dictation is constantly changing the wording during the process (maybe at the same time an autosave occurs or something).

Reported in a difficult chat here, (they were chatting using dictation and HappyChat seems to have the same bug on the user's end): 11332076-hc

**Comment by poojashetty18** [comment]
Found another issue noted here
ZD: https://woothemes.zendesk.com/agent/tickets/2347114

**Comment by tbradsha** [comment]
This no longer seems to be an issue in macOS 11.2.1 + Chrome 88 + Gutenberg 10.0.2.
