### ISSUE TITLE
Sidebar Navigation: Width of Highlight

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#32256]
Right now, the accent colour of the sidebar navigation extends to most of the space, but there's a small primary border-like colour on the right. 

This screenshot was taken on my tablet but it's especially noticeable on desktop devices. Note the pink right border:

![Screenshot_20190412-214517](https://user-images.githubusercontent.com/43215253/56060781-7dcfc700-5d70-11e9-91de-e2ef971f4e09.jpg)

Is this intentional? It feels pretty odd to me that it doesn't extend the whole way, and I've noticed it for a while, but never filed an issue until now. I personally think it feels more like a bug that it doesn't extend the whole way instead of an intentional design decision. :) 

cc @drw158, @sixhours

**Comment by drw158** [comment]
This is a result of having a border on the entire sidebar that extends the entire length of the sidebar. I'm not sure if there is a solution here.

**Comment by sixhours** [comment]
Since we use a white or gray background in the content area, maybe using a light gray border color would make the border look like part of that content area rather than the sidebar.

**Comment by torres126** [comment]
If there is a fix possible (not had the chance to take a look yet), it'd also probably be worth applying it to the promotional banner thingy that also has the sidebar border.

![Screenshot_20190412-230458](https://user-images.githubusercontent.com/43215253/56063331-9c858c00-5d77-11e9-95bc-f87393da4a87.jpg)

**Comment by dezzie** [comment]
I accidentally self-assigned this, sorry.

**Comment by enriquesanchez** [comment]
I'm not sure this is a bug. To me, the border adds a nice visual separation between the sidebar and the main content area. Without it, the default 'Classic Bright' theme lacks enough contrast between these two regions:

<img width="377" alt="Screen Shot 2019-06-13 at 4 37 02 PM" src="https://user-images.githubusercontent.com/3276087/59473988-cc91ef80-8df9-11e9-8fda-dbcf364daca6.png">

Also, given that only ~2% of users change their theme, removing the border will affect a big chunk of users on 'Classic Bright'.
