### ISSUE TITLE
Gutenberg Button Block: Add Option to Open Link in New Tab 

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#32270]
#### Steps to reproduce
1. In Calypso or WP Admin with Gutenberg active, add a button block into a page or post.
2. Insert text and a link URL into the button.
3. Since there's no option to open the button link in a new tab, edit the button block as HTML.
4. In the link HTML, add `target="_blank"` to force the button link to open in a new tab.
5. Change the button block back to edit visually.

#### What I expected

I expected there to be an option to open the button link in a new tab, as there is when adding links in a paragraph block.

#### What happened instead

There was no option to open the button link in a new tab.

After editing the button block HTML and adjusting the link HTML to force it to open in a new tab, the button block shows `This block contains unexpected or invalid content`, so that option doesn't work either.

#### Screenshot / Video

https://cld.wthms.co/rj1JRw

#### Context / Source

This has been requested by multiple WP.com users. It's confusing that the button block doesn't offer the same option as other links, such as a link in a paragraph block.

#user-report

**Comment by simison** [comment]
@juliasydnor I'm gonna close this here since this is a feature in core and there's an issue already: https://github.com/WordPress/gutenberg/issues/8000
