### ISSUE TITLE
Color schemes: Change notification highlight color for Nightfall

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#32303]
With the Nightfall color scheme enabled, notifications use the color `#2b2d2f`, for example, to indicate if a comment has been liked, and to highlight unread notifications in the notifications drop-down.

And the notification bubble on the bell icon if there are unread notifications, while contrasting with the black masterbar, is a dull, grey color that doesn't really pop out so you easily notice it.

Would we consider using a more contrasting color instead? Perhaps the purple that's used for links, buttons and the stats map?

#### Screenshot / Video
![My_Profile_—_WordPress_com](https://user-images.githubusercontent.com/11873759/56207892-2a9b9400-6050-11e9-8d2d-1b9596b106b4.png)

![Stats_‹_if_all_else_fails___use_a_hammer_—_WordPress_com](https://user-images.githubusercontent.com/11873759/56208231-ec52a480-6050-11e9-931f-8e93aca935b4.png)

#### Context / Source

Currently using this color scheme for my account, and finding it difficult to see what I've interacted with and what not, given the lack of color :)

**Comment by torres126** [comment]
@drw158 should these receive the accent colour? I think this also applies to the Reader's Like button tbh
