### ISSUE TITLE
Sites: Preview broken for Jetpack sites with different home, site URLs

### ISSUE THREAD

**Issue by mdawaffe** [Automattic/wp-calypso#32332]
##### Set up a Jetpack Site

1. Create a Jetpack site where the home URL (homepage) is different than the site URL (location of WordPress' files).
2. Make sure that Jetpack site also has non-trivial permalink settings (the "Day and Name" setting works).

(Note that, in wp-admin/ → Options → General, the home URL is confusingly called the "Site Address (URL)", and the site URL the "WordPress Address (URL)".)

Automatticians can use `marvellous-junglefowl.jurassic.ninja` via user `zvwmbxk`.

##### View Site in Calypso
1. Starting at URL: https://wordpress.com/
2. Go to "My Sites".
3. Switch site to the Jetpack site from above.
4. Click "View Site".
5. See 404 in iframed preview.

#### What I expected
To see a real preview :)

#### What happened instead
Calypso is using the site's site URL to build the preview URL. For sites where the site URL and home URL are different, this will usually result in a 404.

Calypso uses `site.options.unmapped_url` for these preview URLs, which is essentially just a wrapper for the site URL.

For WP.com sites, I think we use the site URL since it uses the *.wordpress.com domain, which is useful for auth.

For Jetpack sites, though, we need the home URL. There's no guarantee that there is any useful content at the site URL of a Jetpack site.

(On WP.com sites, both the home and site URL are pathless, so this issue never comes up.)

I'm not sure if this is a Calypso issue, an API issue, or both. I think the root problem is that "mapped v. unmapped" is not the correct distinction to make for preview URLs. We *always* want the home URL for previews. It's just that, on WP.com specifically, we want to mung the home URL to use the *.wordpress.com domain, which happens to be the same as the site URL.

#### Screenshot

<img width="947" alt="Screen Shot of 404ing site preview" src="https://user-images.githubusercontent.com/125994/56240171-a04f3200-6047-11e9-97a5-a5160a4ab3ff.png">

#### Context / Source
#manual-testing, #user-report

**Comment by sirreal** [comment]
This is where that base url is from:

https://github.com/Automattic/wp-calypso/blob/882d9db8b360c99aafb44dd49d9f6d84146cdcab/client/my-sites/preview/main.jsx#L117-L119
