### ISSUE TITLE
Classic Block: Not possible to add an image gallery

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#32348]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post
2. Create a new post using the block editor and add a classic block
3. Click the Add Media button in the block toolbar
4. Attempt to select multiple images to create a gallery

#### What I expected
To be able to select multiple images, as in the classic Calypso editor, that will then change the action button to the Create Gallery option rather than immediately inserting the image

#### What happened instead
Selecting a second image causes the first image to be deselected, in other words, there's no way to select multiple images at once.

Wonder if it might be related to the change to the classic block media modal in #31596. @mmtr?

#### Context / Source

Discovered while trying to replicate an unrelated issue.

**Comment by KokkieH** [comment]
It also appears that editing an existing gallery in the classic block causes the core media modal to open, rather than the Calypso one.

**Comment by mmtr** [comment]
Thanks for reporting this! 

Yeah, this is caused by #31596. When we replaced the core media modal with the Calypso media modal on classic blocks, we didn't include any support for galleries.

I added this to our backlog so it can be prioritized.
