### ISSUE TITLE
Gutenframe: load most recent autosave instead of navigation to core revisions

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#32369]
![autosave](https://user-images.githubusercontent.com/1270189/56324372-7ff4a580-6123-11e9-88e7-c6f13d85be01.png)

Let's override the following notice to either display Calypso Revisions, or update the message to simply load the autosave.

Folks are getting lost in core revisions. This may require a core contribution to add in a clean override.

See: paObgF-6l-p2 PCYsg-jzC-p2

**Comment by mmtr** [comment]
This was fixed by https://github.com/Automattic/wp-calypso/pull/32667
