### ISSUE TITLE
Sharing Settings: Find better way to mark active sharing buttons

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#32375]
This is something that came up while working on #32224
Sharing buttons in sharing settings use opacity to mark which buttons are active vs inactive. These changes in opacity are extremely subtle and cause accessibility issues. We should consider adding a visual indicator of some other kind, for example a border or checkmark icon.
While working on a solution, it's also important to consider the various buttons styles - icon & text, icon only, text only.

Steps to reproduce
1. Visit sharing > sharing buttons
2. Click on Edit sharing buttons.

Screenshots:
Icon & Text style buttons
![image](https://user-images.githubusercontent.com/4550351/56331079-2a290780-61ce-11e9-8821-3cc8703a6882.png)

Icon only buttons
![image](https://user-images.githubusercontent.com/4550351/56331091-3a40e700-61ce-11e9-9ee0-50420810b94e.png)

Text only buttons
![image](https://user-images.githubusercontent.com/4550351/56331116-547ac500-61ce-11e9-8de3-f995bbdef0ce.png)

**Comment by thomasguillot** [comment]
I have 2 ideas here:

1. Just add some CSS to the current elements (see 
1851eba)

![2 after](https://user-images.githubusercontent.com/177929/57181860-f8cc5f00-6e90-11e9-8bd6-9fab54bb3213.png)

2. Rewrite the whole section and use Calypso's buttons `is-compact` for all button style variations with a row of active and a row of inactive buttons

![sharing-button-rework](https://user-images.githubusercontent.com/177929/57181888-303b0b80-6e91-11e9-8bf8-f6784891099e.png)

**Comment by donpark** [comment]
@thomasguillot any plan to create a PR with the commit?

**Comment by thomasguillot** [comment]
@donpark well, I'm not sure if 1851eba is the right way to go to be honest.

cc @sixhours

**Comment by donpark** [comment]
I think `none` or `dashed` border-style make work better.

`border-style: none`

<img width="600" alt="screenshot_644" src="https://user-images.githubusercontent.com/127594/57639210-423d3e00-7564-11e9-92d9-6450f2145b44.png">

`border-style:dashed`

<img width="571" alt="screenshot_646" src="https://user-images.githubusercontent.com/127594/57639221-46695b80-7564-11e9-96cf-a7cc8fb3d053.png">

**Comment by sixhours** [comment]
I liked the dashed border idea, but I don't think it qualifies as

**Comment by thomasguillot** [comment]
Fixed in #33856
