### ISSUE TITLE
Login: Error message refers to the mobile app

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32374]
<img width="560" alt="Screen_Shot_2019-03-23_at_6 23 07_AM" src="https://user-images.githubusercontent.com/2124984/56326835-aa575a80-6145-11e9-9deb-3c87c25571b0.png">

This error message could be reworded to be clearer. What does the mobile app have to do with requesting a code?

**Comment by sixhours** [comment]
I haven't been able to reproduce this error message in trying to log in with 2FA enabled.

I'm also not able to find the message string in this repo, so I'm guessing it's either delivered via an API from elsewhere, or it's been removed since this ticket was first reported (about 1.5 months ago in Trello).

**Comment by sixhours** [comment]
Aha, this error message originates from a plugin on WP.com proper. I'm still not sure how to get it to appear. I've tried:

* Logging in in two different tabs at the same time
* Refreshing the auth request page
* Going back/forward in the browser at login
* Closing and reopening the tab
* Using both regular window and Incognito mode

I get this authentication request at first (I can't log in with the WP app, it never sends a push notification -- I may have disabled them, not sure):

<img width="435" alt="Screen Shot 2019-04-30 at 1 47 18 PM" src="https://user-images.githubusercontent.com/2124984/56982174-addbe000-6b4e-11e9-9d2f-9c98c77d0427.png">

Then I get this one if I refresh, go back or forward, etc.:

<img width="429" alt="Screen Shot 2019-04-30 at 1 45 09 PM" src="https://user-images.githubusercontent.com/2124984/56982198-c4823700-6b4e-11e9-9957-31a5a5335aaf.png">

But no error.

I'm not sure how to make the message clearer, except perhaps to remove the part about the WordPress.com mobile app. Something like:

> "You can only request a code once every two minutes. Please wait and try again."

**Comment by michelleweber** [comment]
Yeah, I think removing the app reference is the best way to go. I'd probably delete "only" as well.

**Comment by sixhours** [comment]
There's a revision here ready for review: D27747-code

**Comment by donpark** [comment]
> There's a revision here ready for review: D27747-code

Looks good. Accepted.

**Comment by sixhours** [comment]
One of the pre-commit hooks is failing, and I'm not sure why, or if this is a big deal given the small changes. @donpark could you take a look?

**Comment by sixhours** [comment]
Deployed by @donpark in r191296-wpcom
