### ISSUE TITLE
Scrolling error on Annual Site Stats page

### ISSUE THREAD

**Issue by chrisaldrich** [Automattic/wp-calypso#32378]
Perhaps this is a native WP.com issue, but I suspect it's JetPack functionality as it occurs both with a .org connected account as well as an example.wordpress.com domain both of which have a "Powered by JetPack" logo on the bottom of the page.

#### Steps to reproduce the issue
1. Go to https://wordpress.com/stats/day/annualstats/example.com
2. Scroll down the page (zoom in if necessary so that the table fills the entire screen; the error isn't as obvious  on a new account or if one doesn't have several years worth of data to view)

#### What I expected
I expected the entire chart and page to scroll down.

#### What happened instead
The Year column stayed fixed and the remainder of the chart scrolls down the page instead. Without zooming in/out on the entire page, one can't visualize the data or have it align properly.

**Screenshots**
Here's a shot of the misaligned static year column versus the remainder of the chart which scrolls up/down.

![Jetpack scrolling glitch](https://user-images.githubusercontent.com/5882943/56334941-581b3700-614f-11e9-8435-377f6dad7f69.PNG)

(This issue was originally published on https://boffosocko.com/2019/04/17/scrolling-error-on-annual-site-stats-page/)

**Comment by kraftbj** [comment]
Thanks for the report @chrisaldrich! I've transfered it to the wp-calypso repo, which is the code that powers the wordpress.com administrative interface you're seeing the odd behavior.
