### ISSUE TITLE
People: Confusing pattern for user attribution on delete card

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32399]
<img width="725" alt="Screen_Shot_2019-03-06_at_11 24 26" src="https://user-images.githubusercontent.com/2124984/56367152-9dc51780-61c2-11e9-83ec-125faabf307d.png">

"Select a user" dropdown is inconsistent with the rest of the dropdown components. It's also buried inside a radio button. It's very unclear what I'm meant to do here.

To reproduce:
1. Have a user invited to your site
2. Click user to edit from the Team tab
3. "Delete" card is at the bottom

**Comment by sixhours** [comment]
I did a quick design mock-up of a potential solution for this one, simplifying the radio options such that if you choose the attribution option, it opens up the Author Selector, and using the same dropdown pattern as is used in the Importer for consistency.

<img width="461" alt="Screen Shot 2019-04-23 at 9 46 40 AM" src="https://user-images.githubusercontent.com/2124984/56585970-d7c06000-65ac-11e9-8284-8a9771b08c9e.png">

This means an extra click, but hopefully less confusion, since there's less to grok all at once. Would love to hear your thoughts, or suggested alternative patterns.

**Comment by donpark** [comment]
If user A wrote a post, attributing the post to user B later doesn't seem reasonable.

What's the reasoning behind the need to reattribute content? Is it because WordPress doesn't support users without any capability?

**Comment by sixhours** [comment]
> What's the reasoning behind the need to reattribute content? Is it because WordPress doesn't support author without any capability? What about one-time contributors?

I think it's that we don't support posts without authors, and/or it's a holdover from WordPress core, where you're able to attribute content to a user upon delete/import:

<img width="383" alt="Screen Shot 2019-04-24 at 1 01 07 PM" src="https://user-images.githubusercontent.com/2124984/56678592-1596b480-6691-11e9-84cd-89c03cb52056.png">

**Comment by donpark** [comment]
Ah. Design legacy. Let's not dig there then. Sorry. ㅡ.ㅡ;;

**Comment by scruffian** [comment]
LGTM
