### ISSUE TITLE
Reader: Articles and headlines fade out to the left

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32393]
<img width="942" alt="Screen_Shot_2019-03-06_at_10 53 48_AM" src="https://user-images.githubusercontent.com/2124984/56366045-3312dc80-61c0-11e9-9676-0bb2de34ad71.png">

Originally seen by @obi2020 

Extra long headlines in the reader are fading out instead of wrapping. Notable that SOME headlines do wrap while others do not.

This needs browser/device information, since I can't reproduce it in the latest version of Chrome for Mac.

**Comment by laurelfulford** [comment]
I did a bit of digging to try to reproduce this issue. 

Only after I followed the [same blog in the screenshot above](https://newslanes.wordpress.com) could I recreate this in any browser on Mac OS 10.14.3, including, Firefox 66.0.3, Safari 12.0.3 and  Chrome 73.0.3683.103:

![Screen Shot 2019-04-19 at 3 22 12 PM](https://user-images.githubusercontent.com/177561/56446345-055c8f00-62b7-11e9-8034-cae183d21cfc.png)

It's using the classes `.reader-combined-card__post .reader-excerpt` on the content and `.reader-combined-card__post-title` on the title, both of which have styles that set `white-space` to `nowrap`.

Once I had a name to search for, I found [this public post about combined cards](https://en.blog.wordpress.com/2017/03/21/reader-combined-cards/) -- the TL;DR: is that this style is used when you follow a blog that updates frequently, to stop it from overwhelming your feed by reducing the size of its posts. 

So this is working as intended, but perhaps it could be tweaked to make it look more deliberate -- like show the full title? Here's my bad browser inspector version of that below: 

![Screen Shot 2019-04-19 at 3 21 52 PM](https://user-images.githubusercontent.com/177561/56446361-14dbd800-62b7-11e9-8589-0cb253af9798.png)

@sixhours what do you think the best approach would be in this case?

**Comment by sixhours** [comment]
@laurelfulford I think showing the full title makes more sense than fading it out. 👍

**Comment by laurelfulford** [comment]
Okay, cool - thanks @sixhours! I should be able to put together a PR this week.
