### ISSUE TITLE
Editor: Allow dropping on featured image

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#324]
Suggested by @mtias:

> we should set a drag-and-drop area on the featured image upload placeholder.

We should enhance the Featured Image editor sidebar by making it a droppable area (using the <DropZone /> component).

![screen shot 2015-11-20 at 3 27 50 pm](https://cloud.githubusercontent.com/assets/1900444/11311036/4d2e3538-8f9b-11e5-804d-c4f664775542.png)

**Comment by lancewillett** [comment]
Another vote for this in a recent #dogfooding session by @beaulebens 

> Can't drag/drop a Featured Image directly into that sidebar panel. Sadface

**Comment by lsinger** [comment]
Closing because #11839 got merged! 🎉
