### ISSUE TITLE
Cart: No hover state on cart icon

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32405]
<img width="181" alt="Screen_Shot_2019-03-07_at_10 47 02_AM" src="https://user-images.githubusercontent.com/2124984/56368971-76704980-61c6-11e9-9163-62b2a3d51b90.png">

This cart icon button does not have a hover state. Regular Calypso icon buttons have a hover state.

**Comment by donpark** [comment]
in progress by @torres126
