### ISSUE TITLE
Idea: Remove Follow button for Business sites

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32401]
<img width="250" alt="Screen_Shot_2019-03-13_at_2 35 53_PM" src="https://user-images.githubusercontent.com/2124984/56367650-b97ced80-61c3-11e9-8ec6-b92dbddb9cc9.png">

The prominent "Follow" button does not make sense for small business owners who are creating a static website and aren't as likely to make use of a blog. Consider hiding the action bar on business sites.

**Comment by alaczek** [comment]
What sort of changes do you think are needed in Calypso to facilitate this? I assume we'd need to add this as a setting, maybe under Manage > Settings > General?

**Comment by sixhours** [comment]
This is part of a larger project -- namely, rethinking the whole action bar and its contents. Moving to On Hold for now since we need to think about this holistically rather than as a single option.

**Comment by blowery** [comment]
How would we identify "business" sites?

**Comment by sixhours** [comment]
At one point in signup we asked site owners to classify themselves as Blog, Business, Ecommerce, etc. so I suspect we had that information stored somewhere.

Those steps were recently removed, though, so I'm not sure how we could identify business sites beyond looking at folks on the Business plan and assuming they're actually businesses. I suspect we have a lot of businesses using other plans, too, though, so it's not a very accurate measure.

I'm not sure this is still a relevant issue, TBH. It was a JM request, and businesses can have blogs. I'm going to close it; anyone should feel free to reopen it if they feel differently. :)
