### ISSUE TITLE
Stats: Misleading G Suite Upgrade Nudge with Email Forwarding

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#32409]
#### Steps to reproduce
1. Purchase a custom domain
2. Enable email forwarding
3. Set up responding from that email 
Relevant support doc: https://en.support.wordpress.com/email-forwarding/
4. Visits the stats page 

This nudge implies viewers can't contact me at the "contact@clubpenguinmountains.com" email, which is misleading and contradictory to what I assumed by setting up an email forward. 

![Screenshot_20190418-190834](https://user-images.githubusercontent.com/43215253/56375184-82cbc500-620d-11e9-81c2-56f3378abb4d.jpg)

I expected the G Suite nudge to focus more on the other advantages to making a purchase, because readers _can_ email me and I can respond back with that email...without purchasing G Suite. 

I could imagine that being quite confusing for someone!

**Comment by arunsathiya** [comment]
That's a great catch, @torres126! Definitely agree how this can look contradicting when I have email forwarding enabled. 

FYI @Automattic/amber. We could possibly improve the copy here. I am also tagging this with normal priority because all users see this nudge from what I know.

**Comment by ajaykj** [comment]
Similar issue in 2353424-zen. The user moved their G Suite subs to Google and seeing the G Suite upgrade nudge.

> Why isn't it syncing with Wordpress site? There only seems to have option online within Wordpress to sign up for a new contact not re-install a previous one.

**Comment by stephanethomas** [comment]
I'm going to close that issue since the copy has been updated in https://github.com/Automattic/wp-calypso/pull/38856 to be less confusing.

> Similar issue in 2353424-zen. The user moved their G Suite subs to Google and seeing the G Suite upgrade nudge.

Unfortunately this particular issue hasn't been addressed yet because of scalability issues. We're aware of it, and tracking it via our Trello board though.

**Comment by gravityrail** [comment]
Thank you!
