### ISSUE TITLE
Add New Site: Dead end error when adding a new Jetpack site

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32400]
<img width="655" alt="Screen_Shot_2019-03-06_at_11 58 34_AM" src="https://user-images.githubusercontent.com/2124984/56367273-e2e94980-61c2-11e9-830c-4d3c4cd20b8e.png">

As a user unfamiliar with Jetpack (and who didn't read / understand the page sub-header copy) I entered the URL for the site I just created and got this error "That's a WordPress.com site, so you don't need to connect it." I can dismiss the error, but the page remains, which can be very confusing.

It works to just use the browser back button, but we should help the user get back to the previous screen or simplify by removing or minimizing Jetpack options.

This could be a moment to celebrate/highlight -- "You already have Jetpack's great features!" (Something more eloquent than that, but you get the idea) -- rather than a bright red, off-putting error.

**Comment by donpark** [comment]
This PR needs review: https://github.com/Automattic/wp-calypso/pull/32442
