### ISSUE TITLE
FSE: handle i18n for different environments [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32418]
As it stands now we'll need to ship this plugin to:

- WP.com
- Atomic
- Jetpack (long term)

All of these handle translations slightly differently or use their own text domains. Currently our plugin is using the translate function from `@wordpress/i18n` package which won't work out of the box on all platforms (e.g. WP.com).

See the discussion in the original PR for more details https://github.com/Automattic/wp-calypso/pull/32355/files#r276423438

The purpose of this task is to research what are our options when it comes to making this work in all environments. We can consider this task complete when one of the following is requirements is met:

- our initial research shows that it doesn't require much work, and we implement the solution.
- we uncover that this is a bigger task, document our findings (preferably P2), and create follow-up issues for sub-tasks.

**Comment by gwwar** [comment]
@simison @yoavf is this mainly around missing pot files? The calls themselves should be externalized to `wp.i18n` https://github.com/Automattic/wp-calypso/blob/e085b45f61b3b993c798211a7c03f2f6e7760f33/packages/wordpress-external-dependencies-plugin/index.js#L44

**Comment by simison** [comment]
@gwwar last time I checked, .com didn't support translating strings from `@wordpress/i18n` functions. (p1554291623027800-slack-i18n) and support was pending implementation by team global.

That might've changed since then of course. :-) (cc @Automattic/i18n)

Jetpack plugin itself gets translated in .org when the code is pushed to SVN. The process looks up for `__()` functions in built JS bundles and automatically includes translations when files with matching paths are enqueued via PHP. It's basically the new .org/core -process which under the hood runs [`wp i18n` command](https://github.com/wp-cli/i18n-command), so you can even test it locally for your plugin. (@Automattic/jetpack-crew)

**Comment by akirk** [comment]
We have received mixed messages about implementing support for `__()` or rather not implementing it, see https://github.com/Automattic/wp-calypso/pull/29429#issuecomment-465733377

I agree we should find a workflow that uses the `wp i18n` command for consistency with .org.

**Comment by simison** [comment]
@akirk from the Slack convo with @yoavf (p1554291623027800-slack-i18n) I understood that there should be no problem implementing the `wp i18n` flow for .com now that it's used for blocks in Jetpack successfully.

**Comment by ockham** [comment]
> We have received mixed messages about implementing support for `__()` or rather not implementing it, see [#29429 (comment)](https://github.com/Automattic/wp-calypso/pull/29429#issuecomment-465733377)

Hmm, that one's on me, it seems. Apologies for any confusion caused -- within the context of the other PR, I thought we were talking about implementing support for `__()` inside Calypso, so we could use it for JP blocks, whose code at the time still _was_ in the `wp-calypso` repo (but which were imminent to be moved into the JP repo, which meant we would no longer require `__()` for Jetpack blocks in `wp-calypso`, as suggested by my comment there).

My understanding is that those translations don't work in the code that's synced from Jetpack to WP.com and thus need work there. (Calypso seems rather circumstantial to those blocks -- it just happens to iframe the WP.com wp-admin block editor.)

> I agree we should find a workflow that uses the `wp i18n` command for consistency with .org.

:+1:

**Comment by simison** [comment]
Internal reference pxLjZ-5nz-p2 (@obenland lemme know if this is not a correct project)

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
