### ISSUE TITLE
Full Site Editing: deployment workflow for Dotcom [1]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32419]
Since we'll need to deploy this plugin to Dotcom, it would be preferable to automate and standardize that process as much as possible.

One of the proposed approaches is to replicate what with did with Masterbar Notifications - create a CircleCi artifacts and automate their fetching on WP.com side. See https://github.com/Automattic/wp-calypso/pull/32163 for a recent example of this.

**Comment by Copons** [comment]
Closed by D27231-code
