### ISSUE TITLE
Stats: suggestions for improvements to the Insights screen

### ISSUE THREAD

**Issue by chrisaldrich** [Automattic/wp-calypso#32428]
I've been enjoying the idea that Jetpack is providing a Github contributions-like functionality at https://wordpress.com/stats/insights/example.com under the heading Posting Activity.

![Posting Activity](https://user-images.githubusercontent.com/5882943/56339032-61ad9a80-6161-11e9-9d0b-ebb55f670774.PNG)

Seeing this naturally provides me some additional motivation to post more often, which is generally a good thing for the platform. It also dovetails in visually with the "you have posted X days in a row" notifications sent by the mobile app.

I'm sure it all may be on the roadmap somewhere, but in case it's not I thought I'd leave a few ideas about continuing to extend this general functionality and UI features.

* It would be nice to be able to display more than one calendar year of activity. Perhaps a tabbed UI could provide access to prior years while still being relatively compact? (This could be similar to "All Time Views" just below it which has button (aka tab) options for "Months and Years" or "Average per Day". 
![all time views](https://user-images.githubusercontent.com/5882943/56339048-6bcf9900-6161-11e9-8639-d5c5622ff998.PNG)
* While hovering over a particular square representing a date provides some useful information like the number of posts on a particular date, it would be awesome if clicking on that date would take one to the correct archive page for that date. This is not too dissimilar to from GitHub's functionality and the permalinks for each day should already exist in core. Example: https://example.com/2019/04/17 to show all of that day's posts.
* Similar to the functionality for posts, it would be interesting to have a similar set up for comments to allow sorting through those visually as well.
* It would be awesome to have all of the above rolled up into a widget that would allow one to post the visual data for several months and/or years visually on a sidebar, footer, or other widgetizeable area. This also provides site readers the ability to quickly jump to a particular date and/or set of posts much like the Archives widget allows, but with a more visual interface.
* If there is a widget, while I'm sure that many will love the blue WordPress-based color scheme, many will want to key their colors off of their theme as a customizable widget option.
* Given the infrastructure for creating a lot of the above functionality, one could go a half step further and create an "On this Day" feature similar to that of Facebook, Timehop, and many others which allow one to create archive page views for what happened on this same day a year ago, two years ago, three, four, etc. This could be wonderfully useful for a wide variety of sites to look back at birthdays, anniversaries, and red letter dates as well as the average Tuesday. To my knowledge there is only one old plugin that I was able to find after some serious search that has somewhat similar functionality: Room 34 presents On This Day https://wordpress.org/plugins/room-34-presents-on-this-day/. There is also some similar functionality like this recently built into the Post Kinds Plugin (url tk) which creates archive views for several date-based permalinks.  This would be all the better if there is a better API for such an endpoint so that it could be tied into third party platforms like Timehop which are overly focused on social sites like Facebook, Twitter, Google, etc., but which could include WordPress-based websites.

Also as I post this, and as I'm thinking the functionality is relatively new, I notice that my JetPack enabled .org site only has Posting Activity that goes back to mid-October 2018 (despite the fact that it should go back much further), while my wordpress.com site has data that goes far back beyond that date. Is this a potential bug, or could it be the case that my self-hosted site hasn't been parsed back far enough to cover more time yet? It may also be related to the fact that I've recently (this week) disconnected and reconnected JetPack to do some troubleshooting.

(This was originally posted at https://boffosocko.com/2019/04/17/extension-of-the-insights-posting-activity-functionality/)

**Comment by jeherve** [comment]
> I notice that my JetPack enabled .org site only has Posting Activity that goes back to mid-October 2018 (despite the fact that it should go back much further)

I would recommend that you contact the Jetpack support team about this, via [this contact form](https://jetpack.com/contact-support/?rel=support). They'll be able to look into this with you, and possibly bring those stats back if they were attached to a different domain / URL at some point.

**Comment by jeherve** [comment]
> It would be awesome to have all of the above rolled up into a widget that would allow one to post the visual data for several months and/or years visually on a sidebar, footer, or other widgetizeable area. This also provides site readers the ability to quickly jump to a particular date and/or set of posts much like the Archives widget allows, but with a more visual interface.

This is definitely something that would be nice, and that would be a nice improvement to our existing Blog Stats widget. I tracked this suggestion here:
https://github.com/Automattic/jetpack/issues/12097
