### ISSUE TITLE
Editor: Remove switch to classic notice for new sites in Calypso [3]

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#32439]
For new sites created, let's remove all visual opt-out escape hatches if the site is using our Twenty Nineteen fork as the theme (which means it is using Gutenberg page templates and has starter content).

![pasted image 0](https://user-images.githubusercontent.com/1464705/56439072-bbb17b80-6299-11e9-828b-26b19791a443.png)

Currently, this means every new user that selects the business segment in our onboarding. As we ramp up with other segments it will mean every new user signing up and creating a site.

For contest: if a site is using this theme, and they switch to the classic editor, everything around editing their website design will break for them so it's a very detrimental option to expose.

**Comment by gwwar** [comment]
Do we want to remove all opt-out points or just the one under the `?` help control

**Comment by apeatling** [comment]
Yes, all of them, there should be no opt out option at all.
