### ISSUE TITLE
Post Checkout: update VideoPress link from WP-Admin to Calypso

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#3245]
Originally reported by @apeatling.

The Thank You page for Premium plans has a button "Start Using VideoPress" that still links to WP-Admin. We should point that to the Calypso editor, preferably with the media modal open.

cc @breezyskies, is this fit for trash pickup?

**Comment by breezyskies** [comment]
We would probably need a dev's help with this given that it's a dynamic link (to a specific site) and the editor needs to open (not sure if we have an existing way to do that).

**Comment by fabianapsimoes** [comment]
Added to Amber's backlog.

**Comment by apeatling** [comment]
At the same time, can you also handle the "cancel this domain" button here:

![screen shot 2016-02-19 at 8 31 10 am](https://cloud.githubusercontent.com/assets/1464705/13181697/2ab62288-d6e3-11e5-9bc6-55c9c848cada.png)

And the "Renew" links in this notification:

![screen shot 2016-02-19 at 8 29 44 am](https://cloud.githubusercontent.com/assets/1464705/13181749/6c846648-d6e3-11e5-8d62-504ccfc0ba8b.png)

**Comment by fabianapsimoes** [comment]
I've opened T347-code and T348-code for these two other changes, since they related to the back-end.

**Comment by fabianapsimoes** [comment]
Fixed in #3548.
