### ISSUE TITLE
Earn: Navigation broke on page refresh or direct URL access

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#32459]
#### Steps to reproduce
1. Start at the **Earn** page for a site.
2. Navigate away from Calypso (eg clicking on the View Site link), then use browser back navigation.
3. Alternatively, try refreshing the **Earn** page.
4. Alternatively, try accessing the **Earn** page URL directly (ie https://wordpress.com/earn/ads-earnings/__SITE__)

#### What I expected
* Able to navigate away from and back to the **Earn** page via standard browser navigation.
* Able to access **Earn** page for a site via URL directly.
* Able to refresh **Earn** page without issue.

#### What happened instead
* When not navigating to **Earn** directly from within Calypso, you will receive a `Page not found.`
* Subsequent `back` navigation is broken. 

#### Screenshot / Video
![Screen Capture on 2019-04-21 at 14-04-25](https://user-images.githubusercontent.com/15803018/56474970-dc670600-643e-11e9-9357-8db4f0d1a880.gif)

#### Context / Source
#dogfooding

**Comment by artpi** [comment]
This should be fixed now CC @cphilleo
