### ISSUE TITLE
Gutenberg: Turn off core Welcome Tips [1]

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#32472]
Currently the Tips ("Welcome to the wonderful world of blocks!") shows up every time I visit the block editor on a new site.

Related: https://github.com/WordPress/gutenberg/issues/15105, but there's no reason we can't fix it on WPCOM in the meantime.

#### Steps to reproduce
1. Go to a site you haven't used Gutenberg on before and add or edit a post.
2. Switch to the block editor if necessary / prompted.
3. Note that this tip appears, no matter how many times you've seen it in the past:
  
<img width="598" alt="Screen Shot 2019-04-22 at 9 36 25 AM" src="https://user-images.githubusercontent.com/52152/56511772-471d4d80-64e2-11e9-941f-a428bd8cbfca.png">

#### What I expected

1. This should show up once per user, not per site or per browser cache.

#### What happened instead

1. It is stored in localStorage on a per-site basis so it shows up repeatedly if you have multiple sites or if you clear your browser cache.

For now let's turn off these welcome tips for everyone on WordPress.com

#### Browser / OS version

OSX/Firefox

#### Context / Source

#dogfooding a12s discussed this in Slack.

**Comment by gwwar** [comment]
Another low cost option to consider is to turn off core tips, which will also help us when we run our own instead.

**Comment by designsimply** [comment]
Adding my vote to make it easier to turn them off per user instead of per site!
