### ISSUE TITLE
People: Invites header text needs same treatment as Team, Followers, and Email Followers

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32487]
<img width="745" alt="Screen Shot 2019-04-22 at 3 40 18 PM" src="https://user-images.githubusercontent.com/2124984/56523220-35a16900-6515-11e9-8ad7-d6d325d3a78e.png">

Related to the work done in #32247, the Invites section of People should have the same treatment; rather than displaying the number after "Pending", it could say "You have pending invites for X users"  for better context.

Also, when you've invited someone who has accepted, you get a list of the invitees that needs similar treatment. Could say "X users have accepted your invites" (? that sounds awkward, I'm sure there are better suggestions out there!):

<img width="764" alt="Screen Shot 2019-04-22 at 3 49 24 PM" src="https://user-images.githubusercontent.com/2124984/56523902-50c0a880-6516-11e9-8276-173ed4de11fb.png">

**Comment by drw158** [comment]
Ideas

`Pending Invites ( 2 )`

`You have 2 pending invites`

`You have 2 accepted invites`
