### ISSUE TITLE
Full Site Editing: research plugin deployment flows for Atomic [4]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32489]
Depends on: https://github.com/Automattic/wp-calypso/issues/32419, https://github.com/Automattic/wp-calypso/issues/32488

After working out the plugin development and deployment flow for Dotcom sites via downloading CircleCI artifacts (see issues above), we need to figure out how can we replicate the same process for Atomic.

The result of this research should be either an automated or manual process for deploying changes to Atomic sites that is documented in a P2 post and FG. We should contact the new Atomic team to coordinate the work on this and ask for inquire for best options going forward.

Most likely we'll need to publish our FSE plugin to the .org repo, since that will probably be the easiest and cleanest way to handle this process.

**Comment by Copons** [comment]
> Most likely we'll need to publish our FSE plugin to the .org repo, since that will probably be the easiest and cleanest way to handle this process.

Let's follow the development of p9F6qB-3fh-p2 and piggyback on that.
I don't see the need to come up with a completely different solution.

The only difference, for FSE, would be to have a way to enable both the plugin and the theme at the same time.

**Comment by vindl** [comment]
The first deployment will be handled by the Atomic team. After that, updates will be automatically fetched from the .org repo.

I updated the instructions for how to publish the new plugin version (and effectively update it on Atomic) in PCYsg-ly5-p2.
