### ISSUE TITLE
Full Site Editing: automate visual progress of the last 500 sites launched [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32498]
Help automate visual progress of the last 500 sites launched to create reports like paAmJe-fl-p2.

We can use the Tinker's mshots API to help create reports: `https://s0.wordpress.com/mshots/v1/" . urlencode($url) . "?w=800`

**Comment by apeatling** [comment]
I will handle this.

**Comment by apeatling** [comment]
Completed, see our P2.
