### ISSUE TITLE
Full Site Editing: research spike on block page templates for page rendering [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32496]
Research spike to see what will be needed to enable block page templates to take over page rendering. We will investigate on whether the "blank" theme will fully take over the page template hierarchy or just the rendering of pages.

The result of this should be a P2 post with the proposed approach for handling this. Based on that we'll create new tasks for actual implementation.

**Comment by Copons** [comment]
Also relevant for this: https://github.com/Automattic/wp-calypso/pull/32865

(I think this issue and #32617 are quite intertwined)

**Comment by mattwiebe** [comment]
Putting this back into the Sprint queue - I mistakenly assigned it to myself when I meant to do #32824 (which I've been working on).

**Comment by Copons** [comment]
This research spike has been completed in #32865 and the results have been published in paAmJe-lZ-p2.
