### ISSUE TITLE
Editor: Remove switch to classic option for new sites in Dotcom [3]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32499]
As a follow-up https://github.com/Automattic/wp-calypso/issues/32439 we'll also need to disable opt-out option for new sites on Dotcom (and by extension Gutenframe). This can be reached in editor's ellipsis menu:

<img width="297" alt="Screenshot 2019-04-22 at 23 34 30" src="https://user-images.githubusercontent.com/1182160/56533030-322ed180-6557-11e9-91e5-95373631d65d.png">

Note: let's also check if there is some special handling that we need for Atomic and Jetpack sites here (e.g. syncing code updates).

**Comment by rodrigoi** [comment]
Closed by rWP191276-code
