### ISSUE TITLE
Removing Featured Tag from Page when set as Featured Content tag doesn't remove from the page after updating

### ISSUE THREAD

**Issue by susanjanec** [Automattic/wp-calypso#32501]
#### Steps to reproduce
1. Starting at URL: moonsailcapital.com
2. User added `featured` tag under Featured Content via Customizer - uncheck both options `Do not display tag in post details and tag clouds.` and `Also display tagged posts outside the Featured Content area.`
3. User added the `featured` tag to their News page
4. Tried to remove the `featured` tag on their News page, but after clicking Update, the `featured` tag comes back.

User is using the Radiate theme

#### What I expected

Removing the `featured` tag and updating the page would remove the tag entirely.

#### What happened instead

The `featured` tag when removed reappears under the Tags

#### Browser / OS version

Tested this on my end using the following:
Chrome 73.0.3683.86 (Official Build) (64-bit) / Mac OS High Sierra

#### Screenshot / Video

https://cld.wthms.co/haKyRm

#### Context / Source

I added the Radiate theme on my test site and added the `featured` tag under Featured Content and added the tag to a page and clicked Update. 

Went back into the page and removed the `featured` tag and clicked the Update button. `featured` tag came back.

When removing the tag from WP-Admin under Quick Edit, and then Updating removes the tag from the page.

Gave the user the WP-Admin workaround for now.

1979285-zen

**Comment by jonnyruzek** [comment]
Encountered this in 1981703-zen

**Comment by desnum** [comment]
In hc-12296089, a user found that they couldn't remove the "featured" tag from a [post](https://wordpress.com/block-editor/post/rndy.blog/42
).

**Comment by ezebecke** [comment]
Same issue in 13003554-hc

**Comment by aleone89** [comment]
Another report: hc-12996717. The work around I provided was by going to wp-admin and remove the tag via quick edit.

**Comment by arunsathiya** [comment]
I see a related issue here https://github.com/Automattic/wp-calypso/issues/28775 about not being able to remove all tags, which @tbradsha had linked to as well. If both the reports are the same, should we consider closing https://github.com/Automattic/wp-calypso/issues/32501 in favor of https://github.com/Automattic/wp-calypso/issues/28775?

**Comment by annperegrina** [comment]
Another report on this hc-13116453. The work around I provided was by going to wp-admin and remove the tag via quick edit.

**Comment by annperegrina** [comment]
Another report on this hc-13139273. The work around I provided was by going to wp-admin and remove the tag via quick edit.

**Comment by nagpai** [comment]
Another report here : #4995653-hc

**Comment by AtrumGeost** [comment]
Got a similar issue here 13742823-hc

**Comment by kristarella** [comment]
Also reported in 13960569-hc

**Comment by automattic-ian** [comment]
new report in #13108281-hc

**Comment by noahtallen** [comment]
Closing this in favor of #28775. Please stick any reports in that issue! Whenever you try to remove all of the tags at once (i.e. a single `featured` tag), all of the tags remain. You should still be able to replace the tag - for example, remove `featured` and set `abc`. That action seems to be working for me. I'll try to come up with a solution for that other one. :)
