### ISSUE TITLE
Domains: Consider making "web" address more clear at the Domains step of signup

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32515]
<img width="554" alt="Screen Shot 2019-04-23 at 10 29 29 AM" src="https://user-images.githubusercontent.com/2124984/56589359-0fcaa180-65b3-11e9-91f3-9dfc8ae775b2.png">

~Might be worth mentioning the web part, as we just asked them for their literal address two steps prior.~

This is no longer an issue, we don't ask them for their business address during signup any more, and there are tests around removing domains from signup, too.

That said, I'm leaving this open in case we want to re-examine the copy; ccing Dan since he's working on the domains search in general, and Shaun for signup-related feedback.

**Comment by shaunandrews** [comment]
Doesn't seem like there's any action needed for this issue at the moment. Feel free to reopen if you disagree.
