### ISSUE TITLE
GSuite: Skip and Yes button should be closer on G Suite view

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32519]
<img width="791" alt="Screen_Shot_2019-03-06_at_10 47 38_AM" src="https://user-images.githubusercontent.com/2124984/56594351-ac447200-65ba-11e9-80a4-0b881e789a19.png">

Muriel standards suggest that buttons like these should be next to one another.

(Check in with @gravityrail before working on this, please.)

**Comment by gravityrail** [comment]
Seems fine to me :) I will ask someone from catalyst to comment.

**Comment by stephanethomas** [comment]
I don't see any problem with that. Thanks for letting us know though! @sixhours could you link to the Muriel page next time please? This would help for context as well as to propagate knowledge.

**Comment by sixhours** [comment]
@stephanethomas Sure thing! Here you go: https://murieldesignsystem.blog/components/buttons/#placement

**Comment by donpark** [comment]
Left-aligned button makes sense if it the action was Back button with left arrow but, in this case, Skip is forward secondary action so I think it make sense to move it next to the primary action without outline.
