### ISSUE TITLE
Domains: "Select" button is a purchase action; copy should be clearer.

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32526]
![download_(40)](https://user-images.githubusercontent.com/2124984/56603323-8e343d00-65cd-11e9-9870-2b47cfe7e311.png)

Go to add a domain to your site; search for a domain and click "Select."

The "Select" button is more like a purchase button. It doesn't just add it to your cart; you are are immediately taken into the checkout flow.

If we're going to move to the checkout flow immediately, the button should say "Purchase" to make it clearer that you're checking out.

**Comment by danhauk** [comment]
@sixhours Should we still keep it "Select" in the signup flow which is a bit different? The plan selection immediately follows the domains in that flow.

@Automattic/cobalt Is this something we will want to test? I agree the copy should be clearer here but not sure if it's something we need to test against conversion rate.

**Comment by sixhours** [comment]
> Should we still keep it "Select" in the signup flow which is a bit different? The plan selection immediately follows the domains in that flow.

Good point, I think "Select" makes sense in the context of signup.

**Comment by klimeryk** [comment]
FWIW, it's not always `Select` even now: https://github.com/Automattic/wp-calypso/blob/407b02e5b94ff69926327c0559f5a256edd1562c/client/components/domains/domain-registration-suggestion/index.jsx#L143

If it's not signup _and_ the user is using their domain credit, the CTA is `Upgrade`.

As for the `Select` copy - I think this should be A/B tested if we want to change it. To play the devil's advocate - `Select` in this context makes sense to me as I (as the user) have been searching for a domain I like and when I finally find one I like I "select" it from the rest.

**Comment by danhauk** [comment]
Yeah, we'll keep `Upgrade` in that case for sure. To play devil's advocate to your devil's advocate, you're also "purchasing" that specific domain. 

I think either makes sense to me honestly, but we can run a test to see if there's any effect. My hypothesis is it won't change anything - who actually reads buttons?

**Comment by klimeryk** [comment]
Closing as wontfix - `Select` IMHO works best as the generic action here. We might add a new step after selecting the domain to let the user chose if they want to purchase it for a new site, existing or just buy the domain and in that context it makes sense to keep it `Select`. I have also not heard any issues from HEs/users about this being a pain point here.
With new onboarding it's also been avoided, so even less of an issue.
