### ISSUE TITLE
Customizer - Edit option showing on Chrome

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#32539]
When the Customizer is open, it appears that the expected behavior is to not show the **Edit** option for Pages and Posts. This is the case in Safari and Firefox, but not on Chrome, where **Edit** shows with a confusing 🚫 icon where one would assume the link doesn't work but it does. When clicked, a new tab will open with the editor.

<img width="781" alt="Screen Shot 2019-04-24 at 14 26 18" src="https://user-images.githubusercontent.com/15944096/56636999-1b929280-669d-11e9-8093-8fb187af595c.png">

#12270589-hc

**Comment by lancewillett** [comment]
Closing as duplicate.
