### ISSUE TITLE
Jetpack Checklist Enhancement: Remove redundant cards, add configure and view links to checklist items

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#32557]
**The problem:** The checklist needs to replace the functionality of the cards that are displayed directly below it - there's now redundancy in the UI which can be confusing. It's an especially bloated interface.

**The solution:** Clean up the security related cards below the checklist, and add any actionable links to the checklist items themselves after the feature has been turned on.

**Current checklist UI w/ completed tasks**

![Screen Shot 2019-04-24 at 11 52 18 AM](https://user-images.githubusercontent.com/214813/56674469-1d9e2680-6688-11e9-8cca-39327bf53528.png)

**Proposed Checklist UI changes**
![Adding configure links  Removing cards](https://user-images.githubusercontent.com/214813/56674490-27278e80-6688-11e9-9b36-5f377316150e.jpg)

**To-do:**
1) Brute force attack feature: 
a) remove card below checklist. 
b) add "configure" link to the completed checklist item that sends customers to the appropriate settings within calypso.

2) backup and scan feature: 
a) remove site security card below checklist. 
b) add link to "view security dashboard" in the completed checklist item. for now it should take the customer to their respective vaultpress dashboard. in the future, we'll send them to the calypso UI formerly known as Rewind (cc @rcoll )

3) spam filtering feature:
a) remove spam filtering card below checklist
b) add "view spam stats" to its respective completed checklist item to take customers to their akismet dashboard within wp-admin. I think this will show a little more value for customers. Note: have this link open in new window since there’s currently no way for customers to return to wordpress.com from akismet dash

4) concierge orientation card
a) @chaselivingston had mentioned that concierge may be shutting down for a bit in Q2. If that's the case, and if this block won't auto disappear, we should hide it for now. Also in the future, I think concierge orientation should be part of the checklist. 

5) update completed tasks action link verbiage
a) currently completed tasks say "change" to the right of the checklist. Paired with the language to the checklist item, the word "change" make it seems like a customer can only turn something on or off. It doesn't communicate that these features have settings that can be configured.

Example:
![Screen Shot 2019-04-24 at 12 13 42 PM](https://user-images.githubusercontent.com/214813/56675600-8c7c7f00-668a-11e9-85c2-b743b55d3584.png)

 I think we should update "change" to read as "configure" for checklist items, since all of these checklist items are features that can be configured, not just turned on or off.

**Comment by tyxla** [comment]
Thanks for this, Jeff. Unassigning myself, as it's not in the plans for me to work on this, but I'll keep an 👁 😉

**Comment by ockham** [comment]
Imma give this a stab :dagger:

**Comment by ockham** [comment]
> 2) backup and scan feature: 
> a) remove site security card below checklist. 
> b) add link to "view security dashboard" in the completed checklist item. for now it should take the customer to their respective vaultpress dashboard. in the future, we'll send them to the calypso UI formerly known as Rewind (cc @rcoll )

Note that we already have separate checklist items for VaultPress
https://github.com/Automattic/wp-calypso/blob/0fb357b99f5fe8f46b08a43991ab93d8e7033c06/client/my-sites/plans/current-plan/jetpack-checklist/constants.js#L72-L75
vs Rewind:
https://github.com/Automattic/wp-calypso/blob/0fb357b99f5fe8f46b08a43991ab93d8e7033c06/client/my-sites/plans/current-plan/jetpack-checklist/constants.js#L61-L70, which are conditionally used depending on which of either the site is running.

The 'Rewind' one already points to the Rewind Calypso UI. I'll just change the link label from 'Change' to 'Configure'.
