### ISSUE TITLE
Jetpack Checklist Enhancement: Getting to/from checklist and wp-admin. Introducing checklist mention in wp-admin

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#32565]
![get back to checklist](https://user-images.githubusercontent.com/214813/56689374-eee47800-66a8-11e9-840f-7b5874b7b697.jpg)

**Currently:** 
Right now it's difficult for customers to traverse wp-admin and calypso fluidly. The checklist exists in calypso, and it's going to be important that we allow customers a way to navigate between the two, easily. 

I also think it's incredibly important, that if folks can discover their setup progress and checklist if they're in wp-admin, so they always have their progress beacon. 

**Proposal:** 
**wp-admin first visit**
I think it's important we provide a linear pathway for customers who aren't familiar with jetpack. I'm suggesting that the **first time they visit** the jetpack dashboard in wp-admin, we display a dismissible banner welcoming them to their jetpack dashboard and informing them of the checklist. 

![Screen Shot 2019-04-24 at 3 56 43 PM](https://user-images.githubusercontent.com/214813/56689663-93ff5080-66a9-11e9-99dc-71e269c92bad.png)

Clicking "continue jetpack setup" will bring them to the actual checklist to complete tasks. Clicking the "wp-admin" sidebar link will return them to their jetpack dashboard under "my plan," where a permanent mention of the checklist will reside...

**a home for the checklist indicator in wp-admin**
I think the checklist deserves a permanent mention under the "my plan" tab in the jetpack dashboard in wp-admin (consistent with its location in calypso as well). I'm envisioning a visual that's simple and consistent with all the UI that we see in calypso for consistency.

![Screen Shot 2019-04-24 at 3 59 45 PM](https://user-images.githubusercontent.com/214813/56689834-040dd680-66aa-11e9-9603-efa8a4f129fb.png)

Important note: The idea moving forward is to begin removing redundant action cards, and placing emphasis on the checklist in calypso, as outlined in this issue: https://github.com/Automattic/wp-calypso/issues/32557

@joanrho I'd love your feedback, since this overlaps jetpack design territory, but it's still technically part of onboarding for new customers. I think it's going to be important to help them navigate. Open to flow and visual feedback as always!

**Comment by jeffgolenski** [comment]
ccing @dereksmart as well

**Comment by joanrho** [comment]
@jeffgolenski your plan for both the dismissible banner and the "permanent" home in the wp-admin My Plan view (to align with the Calypso location) sounds like a good first iteration on this to me.

**Comment by simison** [comment]
Might be interesting to add an item to WP's new "security checklist" under "recommended items":

> _Finish setting up essential Jetpack security features_

https://make.wordpress.org/core/2019/04/25/site-health-check-in-5-2/

p1HpG7-6wC-p2

**Comment by fditrapani** [comment]
A small note on copy. Rather than `Continue Jetpack setup` what if we went with something like `Complete Jetpack Setup`

**Comment by jeffgolenski** [comment]
@simison That's a great point - I'll think a little more about how we can also add it as a health check item this week! 

As Filippo mentioned above, we should also change the verbiage of the CTA to say "Complete Jetpack Setup"

**Comment by sirreal** [comment]
The Calypso side of this is implemented. Tracking the Jetpack side changes in https://github.com/Automattic/jetpack/issues/11997
