### ISSUE TITLE
Imports: inconsistency in behaviour when navigating away from importers and back

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#32570]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/settings/import/[ site ]
2. Click on "Start Import" button in the GoDaddy or Wix importer to enter that importer.
3. Click on a link in the sidebar to navigate away.
4. Click on "Import" in the sidebar to go back.

#### What I expected

To see the previously selected importer.

#### What happened instead

With these two importers, you see the list of importers.

#### Browser / OS version

MacOS FF 66

#### Screenshot / Video

![importer-navigation](https://user-images.githubusercontent.com/1647564/56719220-382fd880-6738-11e9-888d-93669bce22a3.gif)

#### Context / Source

We may have introduced this inconsistency in https://github.com/Automattic/wp-calypso/pull/32037. Actually, the behaviour of these two importers seems to make more sense than the old way. It's reasonable to assume someone is finished with an importer if they navigate away from it. IMHO, all the importers should behave like this.

#manual-testing

**Comment by youbrokesomething** [comment]
I can no longer reproduce this issue; we likely changed the behavior since the ticket opened in 2019.
