### ISSUE TITLE
Update “Back to Site” link after checkout to link to Calypso > Plan > My Plan to start Checklist

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#32582]
[Screenshot](https://cloudup.com/cs7gv_cpKWC)

**Comment by eliorivero** [comment]
@MichaelArestad I started something on #32586 but after seeing that the new onboarding checklist will be merged soon, I think we might not need this.

To check the new feature, launch https://wpcalypso.wordpress.com and buy a plan for a JP site. After paying (I tested with credits) you're immediately taken to Plan > My Plan and Checklist is initiated.

**Comment by MichaelArestad** [comment]
Good point. Closing for now.
