### ISSUE TITLE
Billing history: not loading receipt list

### ISSUE THREAD

**Issue by jessestu** [Automattic/wp-calypso#32580]
A user reports that their billing history doesn't always load. They needed us to send receipts their way, which is how I learned of the issue.

#### Steps to reproduce
1. Starting at URL: wordpress.com → Me → Manage Purchases → Billing History

#### What I expected

To see the billing history, like in this screenshot after I tried it about 10 minutes after the first attempt (screenshot below):

![billing-history-not-loading-2nd-time](https://user-images.githubusercontent.com/32908730/56745731-8517ad00-6740-11e9-83e4-2403d1584716.png)

#### What happened instead

I let the page load for about five minutes. It never changed from this:

![billing-history-not-loading](https://user-images.githubusercontent.com/32908730/56744684-965fba00-673e-11e9-994f-2f57d9a68f07.png)

I asked the user if this has happened before. They replied, "Yes, it has happened from time to time. I usually wait and the problem goes away." It went away for me when I looked again while writing this ticket.

#### Browser / OS version

Customer: Safari 12 on macOS 10.13.6

Me: Chrome on macOS 10.14.4

#### Context / Source

#user-report in 11830991-hc

**Comment by arunsathiya** [comment]
>Yes, it has happened from time to time. I usually wait and the problem goes away

It sounds like they could be on a slower network. 

I also remember seeing a similar issue, but my search skills are failing at the moment. @jessestu, could you reach out to the user to see how fast their network is? I had a look and it loads fine.

**Comment by jessestu** [comment]
It failed one time when I tried it in my own network, and I have 60 Mbps downstream on that network.

I'd rather not reach back out to the user if that can be avoided as we did not discuss a followup and it failed once on my own computer and worked once. Thanks!

**Comment by arunsathiya** [comment]
>it failed once on my own computer and worked once

That's interesting, Jesse. I would imagine that it should never fail, but since that seems to happen, let's leave this issue open. 👍🏽

**Comment by arunsathiya** [comment]
We don't have concrete reproduction steps at the moment, so, let's leave this as closed.
