### ISSUE TITLE
Drafts: infinite-scroll not working correctly

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3258]
I noticed while working on post-list changes that the draft drawer fires off pagination queries one-after-the-other without any input from the user. I believe this is a bug and not done by design, but let me know if I'm wrong. Normally infinite-scroll functionality is triggered by user interaction when a user scrolls to the bottom of a list. In this case if someone has tons and tons of drafts, it's going to keep querying until it gets them all.

I haven't looked very deeply into this, but it looks like `draft-list` is using the `infinite-scroll` mixin rather than the `infinite-list` component. And I believe the `infinite-scroll` mixin really only handles scrolling at the window level. `infinite-list` however can work with a scrollable element like this.

/cc @mtias to confirm this is indeed a bug.

![draft-list](https://cloudup.com/cx-dUtD2KYc+)

**Comment by mtias** [comment]
Yes, this is a bug. I believe it was alright before because the panel wasn't fixed to scroll independently and just scrolled with the document.

**Comment by rralian** [comment]
I'm detaching this from the milestone, as we're moving on... but we should track the (smallish) bug and address it at some point.

**Comment by hoverduck** [comment]
14Apr16 Bug Scrub

Looks like this is still an issue.

**Comment by rralian** [comment]
Marking this low priority, as the issue is more about the component not working as intended than about a negative user impact. This will be unnoticeable for about 99.9% of users.

**Comment by lancewillett** [comment]
Closing because we have higher impact items to focus on.
