### ISSUE TITLE
Help: Help icon covers Send button in mobile browser

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#32590]
The Help (?) icon covers the Send button in a mobile browser.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/help/contact in mobile browser
2. Start a chat.
3. Go to another page in the dashboard.
4. Tap on the chat icon to return to chat.

#### What I expected
The Help (?) icon hides itself.

#### What happened instead
The Help (?) icon reappeared and covered the Send button.

#### Browser / OS version
iOS 12.2
Chrome

#### Screenshots
![IMG_8831](https://user-images.githubusercontent.com/11635760/56764699-3414b280-675a-11e9-84e0-dd30f08da76e.PNG)
![IMG_8833](https://user-images.githubusercontent.com/11635760/56764708-3840d000-675a-11e9-8170-7523675f0ebd.PNG)
![IMG_8836](https://user-images.githubusercontent.com/11635760/56764726-468eec00-675a-11e9-897a-eccf52c4bfea.PNG)
![IMG_8835](https://user-images.githubusercontent.com/11635760/56764732-4989dc80-675a-11e9-9243-84c6a6860a0c.PNG)

#### Context / Source
#user-report
12146251-hc

**Comment by lsl** [comment]
When opening up chat for the first time the context menu (?) is hidden but any re-opening of the chat afterwards will not hide.

Suspect it only gets hidden on that first initialization. Subsequent reloads or views that take you to /me/chat result in the context menu remaining visible on top.

**Comment by alshakero** [comment]
This has been partially fixed by @enejb in https://github.com/Automattic/wp-calypso/commit/abaf9ae2fb4d22597c5a8ab70622b4d884b5e99d. 

The only remaining issue is this one:
![wordpress com_help(iPhone 6_7_8 Plus) (1)](https://user-images.githubusercontent.com/17054134/80362306-b0b50200-8882-11ea-8837-cad6a6b9eabe.png)
