### ISSUE TITLE
Editor: Adjust height for larger of browser height and editor content

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#326]
We should automatically adjust the height of the editor to whichever is the larger of:
- The current scrollable height of the page contents
- The height of the editor contents

@azaozz "As far as I see the wpcom-autoresize plugin takes care of min height. Can be adjusted to use the initial viewport height (minus toolbars) as min editor height, but don't think it will work/feel better. (Currently it uses the initial textarea offsetHeight as min height)."

Code suggestion in Oct. 29 comment on 7194-gh-calypso-pre-oss

raised by aduth

**Comment by alisterscott** [comment]
@aduth: do you still see this as task we should be focussing on? Can I close it?

**Comment by aduth** [comment]
If I recall correctly, there was originally an issue where the editor would load with a scrollbar present when content wasn't long enough to justify it. This appears to have since been remedied (likely through one of the few redesigns) so this issue should be safe to close.
