### ISSUE TITLE
Media: uploading new image with the same filename as an old deleted image results in incorrect thumbnail.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#32621]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/
2. Upload an image. Such as example.jpg
3. Delete that image.
4. Choose a different image on your hard drive. Rename it to example.jpg
5. Upload new image. Thumbnail displays  the older, original photo.

#### What I expected

To see a thumbnail of the actual file.

#### What happened instead

Thumbnail is of the older image that was previously uploaded, with the same filename.

Interestingly, the file/image itself is accurate. It's just the thumbnail that seems to be wrong (although that's still confusing for users).

#### Browser / OS version

Chrome Version 73.0.3683.86 (Official Build) (64-bit)

Pop!_OS 18.10

#### Screenshot / Video

![Peek 2019-04-26 14-21](https://user-images.githubusercontent.com/10121835/56831527-ed44bc80-682e-11e9-84be-5eccbd98b270.gif)

#### Context / Source

12374499-hc

**Comment by arunsathiya** [comment]
A few questions:

- What happens on refreshing the media library page?
- If a refresh does not help, what happens on logging in afresh?
