### ISSUE TITLE
Remote Login: First visit not always recognizing logged-in/following status

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#32638]
#### Steps to reproduce
1. Go to WordPress.com in the mobile browser and ensure that you are logged in
2. Choose a WordPress.com simple site that you own and are subscribed to - view the stats page and note the number of views today
3. Visit the site itself in a new tab and observe that the follow button in the lower right corner says '+Follow', indicating that you are not following the site
4. Refresh the page in the app and observe that button changes to recognize that you are indeed following the site
5. Check your stats page for the site and see that your view was counted

#### What I expected

I expected to be recognized as following the site in the first visit, and for my view not to be counted in stats.

#### What happened instead

I was not recognized as following the site in the first visit, and my view was counted in stats.

#### Browser / OS version

Reproduced in Android 8.0 on both Firefox 62.0.1 and Chrome 72.0.3626.105

#### Context / Source
#user-report #12416984-hc

**Comment by rachelmcr** [comment]
I tested this using a device with Android 8.1.0 and Chrome 75.0.3770.101, using a WordPress.com Simple site with a custom domain and one without. In both cases, I was immediately logged in to my site and saw nothing unexpected (admin bar appeared, I wasn't counted in stats, I was recognized as following the site, etc.).

Per some other internal reports (ref: p58i-7JY-p2 #comment-42183) this doesn't seem to be a mobile-specific issue and may be related to how the user logs in (possibly bypassing remote login).
