### ISSUE TITLE
Nav Drawer: Hover Colours Appearing when Clicking does Nothing

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#32634]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me (example link, it's present throughout Calypso, such as the Reader)
2. Hover over "Profile" on the nav drawer/sidebar

#### What I expected

No hover colour - clicking it does nothing, but a hover colour implies it does something. 

#### What happened instead

A hover colour (with not a great contrast in Sakura) appears.

<img width="162" alt="Screenshot 2019-04-27 at 09 16 03" src="https://user-images.githubusercontent.com/43215253/56846946-31869a00-68cd-11e9-83bb-5dd9a3654f4d.png">

**Comment by flootr** [comment]
My guess is this hover effect should only be applied to the new nav drawer. It seems like the relevant styles were introduced here https://github.com/Automattic/wp-calypso/commit/47e778be86708c16aeb78a8a23c8aaeea8bcac0b /cc @davemart-in @griffbrad

**Comment by flootr** [comment]
I noticed a bug in the devdocs probably somehow related to the one reported above:

![devdocs](https://user-images.githubusercontent.com/9202899/56945357-3777b780-6b27-11e9-8f02-73b1dad79b8f.gif)

**Comment by davemart-in** [comment]
Thanks @flootr! I've added this to my list.

**Comment by drw158** [comment]
I'll add to this issue that is probably the same problem:

![Apr-30-2019 08-58-57](https://user-images.githubusercontent.com/618551/56967306-8d982b00-6b26-11e9-96fc-c64018e3dc3a.gif)

Default scheme (notice how the color of the section title doesn't change while hovering over items):

![Apr-30-2019 08-59-19](https://user-images.githubusercontent.com/618551/56967324-9a1c8380-6b26-11e9-9ebe-3bb2b89fd0e4.gif)

**Comment by torres126** [comment]
I think that wrapping that code in `.is-group-sites` should solve this issue.

```
.is-group-sites .notouch li.sidebar__menu:hover {
	&:not( .selected ) {
		& > h2 {
			color: var( --sidebar-menu-hover-color );

			& > .material-icon {
				fill: var( --sidebar-menu-hover-color );
			}
		}
	}
}
```
