### ISSUE TITLE
Editor: Unable to scroll in WordPress.com block editor

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#32637]
This is feedback on an issue I came across while testing Jetpack v7.3-alpha-9688-g91a3f01

#### Steps to reproduce

I created a new post to test, and the URL is https://atomicpljcbsn2.com/wp-admin/post.php?post=608&action=edit

I wasn't taken to a `/block-editor/*/:site` path at all. That said, the editor definitely behaved differently in my tests.

I added an image using the **Image** block. I selected an image from my Media library. I closed the post, then returned to the post, and found I couldn't scroll below the visible image to the caption, or the space below it to type into a new Paragraph block, or even add a new block. See [here](https://cld.wthms.co/lnvPXC):

![](https://cld.wthms.co/lnvPXC+)

I decided to switch themes to Twenty Nineteen (my site was on Storefront). I went to **Design** > **Themes** and was met with a screen asking me to enable Jetpack Manage. I did this (it opened a new tab in my browser), but the screen persisted, [like this](https://cld.wthms.co/tDVl5Q):

![](https://cld.wthms.co/tDVl5Q+)

I clicked through to the Site Theme Browser, and this opened a new tab in my browser where I added Twenty Nineteen through a Calypso-skinned WP Admin UI for adding new themes. I didn't initially see an option to browse Jetpack themes as I'd expect. [This is what I see](https://cld.wthms.co/JSfaDD) in a WordPress.com Business plan site without the Jetpack Beta plugin:

![](https://cld.wthms.co/JSfaDD+)

I noticed that when I refreshed the page again, after activating Twenty Nineteen, I was taken to the Calypso **Themes** page to select further themes.

I returned to the post, and tried adding a Gallery block. When I did this, I encountered the scrolling issue again. When I added a Gallery block below the existing image after hitting return from the Paragraph block below the initial image, I couldn't scroll down to access the block options.

I removed the block, and then added it from the block browser option at the top of the editor. This gave me more access to the block options so I could upload images, and create the gallery. Still, when I added the gallery to the post in editor, I couldn't scroll down to view the whole block (and a space below it as usually is the case), [like this](https://cld.wthms.co/X5GiXA):

![](https://cld.wthms.co/X5GiXA+)

#### What I expected

To be able to scroll below the bottom block to a space where I can add a new block, or start typing into the default Paragraph blog.

#### What happened instead

As I described above, I was unable to scroll.

#### Browser / OS version

Browser: Firefox Developer Edition v67.0b14
OS: macOS 10.14.4

My test site is a WordPress.com site with a WordPress.com Business plan.

#### Screenshot / Video

See above

#### Context / Source

This report is a result of internal testing.

**Comment by mmtr** [comment]
It will be fixed once https://github.com/Automattic/jetpack/pull/12279 is merged
