### ISSUE TITLE
Mailchimp Block:  "set up Mailchimp Form" button links to wrong page

### ISSUE THREAD

**Issue by lizthefair** [Automattic/wp-calypso#32641]
#### Steps to reproduce the issue

1. Go to a post or page and add the Mailchimp Block. Be sure both publicize and sharing options are turned on.
2. Click on "Setup Mailchimp Form"
3. Button links to:  https://wordpress.com/sharing/[blog-id]  which redirects to: https://wordpress.com/marketing/traffic/[blog-id]
4. The information needed to set up Mailchimp isn't on that page.  It's on: https://wordpress.com/marketing/connections/[blog-id]

#### What I expected
To click on the button and be taken to the page with the Mailchimp information.
 
#### What happened instead

Linked to the "traffic" tab instead of the "connections" tab.

**Comment by simison** [comment]
Seems to have been fixed. Feel free to add a link to PR where this was fixed for a record.
