### ISSUE TITLE
"Remove" button is off in navigation panel

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#32644]
When Jetpack site's connection is broken (e.g. the site is gone), there's a prompt to remove button in the sidebar:

<img width="236" alt="Screenshot 2019-04-29 at 11 32 32" src="https://user-images.githubusercontent.com/87168/56884487-a21aeb80-6a72-11e9-829b-74a267dc392a.png">

<img width="400" alt="Screenshot 2019-04-29 at 11 32 32" src="https://user-images.githubusercontent.com/87168/56884522-beb72380-6a72-11e9-8cbb-6cfa48242e4f.png">

The "remove" link looks off visually. The link might've been smaller before?

**Comment by rfaile313** [comment]
I can't replicate this issue. When I disconnect or break the jetpack connection it removes it from the "My Sites" list. Additionally, the "This site cannot be accessed. Remove Site" portion was visible for a few moments after the disconnect and it was nicely aligned not like the screenshot here.

**Comment by simison** [comment]
On bigger screens it seems to be fine:

![image](https://user-images.githubusercontent.com/87168/58120720-7cff4000-7c0e-11e9-974c-5acb6360ab41.png)

Under 960px breakpoint it still breaks:

![image](https://user-images.githubusercontent.com/87168/58120770-9902e180-7c0e-11e9-88f6-6003a4dd42bf.png)

It's prolly possible to change JS code temporarily so that the component shows up, without breaking a connection intentionally.

**Comment by alaczek** [comment]
I was able to see the notice, but not the issue on the desktop (even under 960px).

![image](https://user-images.githubusercontent.com/4550351/59244329-4ccc1f80-8c57-11e9-9acb-55975398e40e.png)

I do see it on mobile though:
![image](https://user-images.githubusercontent.com/4550351/59244357-71c09280-8c57-11e9-884d-210408b4f3c2.png)

It also appears a space is missing between the text and the link. @scalarbane2 is this something that you'd like to tackle? If not I'll take it. :)

**Comment by sixhours** [comment]
This probably just needs some CSS tweaks to fix it. Moving to Development since it doesn't need mock-ups or design work.
