### ISSUE TITLE
Reader: No clear way to go back to followed sites

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#32640]
Reader has two general views: stream of articles from followed sites, and manage, where subscriptions can be managed. The problem is, there's no clear path back from manage screen to the article stream.

#### Steps to reproduce
1. The initial Reader screen at https://wordpress.com/
![image](https://user-images.githubusercontent.com/4550351/56877438-680d1200-6a91-11e9-95b5-7f2ca798f340.png)

2. Click on "Manage" to go to the subscription management screen at https://wordpress.com/following/manage
![image](https://user-images.githubusercontent.com/4550351/56877460-968aed00-6a91-11e9-948b-4d264fb9694e.png)

Note that there's no clearly labeled way to go back to the stream of articles (you can do that by clicking on "Followed Sites" in the sidebar, or "Reader" on top). Also note that "Followed Sites" is highlighted in the sidebar in both cases, which is technically correct, but also feels somewhat confusing.

**What I expected**
To have a clearly labeled way to go back to the stream of articles from the manage screen.

One idea for a fix would be to implement a top SectionNav with two tabs:
https://wpcalypso.wordpress.com/devdocs/design/section-nav

**Comment by torres126** [comment]
Another idea could be this but I'm not sure if the design is ideal width a full width search beneath it

<img width="1025" alt="Screenshot 2019-04-29 at 18 03 07" src="https://user-images.githubusercontent.com/43215253/56913261-16708180-6aa9-11e9-8723-3895cf06a08a.png">

Just for comparison, them switched:

<img width="836" alt="Screenshot 2019-04-29 at 18 05 33" src="https://user-images.githubusercontent.com/43215253/56913380-694a3900-6aa9-11e9-820e-f3cdb135e955.png">

**Comment by davemart-in** [comment]
I just wanted to add that we discussed this in Slack and @drw158 agreed that we should just add a back button on the manage screen. 

> Brad is right on in that Tabs are used to separate 2 views of related content and not a great fit here. There are several routes you could take but I think emulating the native apps would be good for now.

> Keep the Manage button where it is. On the manage view, show a back button, similar to how tag pages show a back button. In Calypso this may be known as a Header Cake.

Though the mockup he shared didn't have the border around it:

![screen_shot_2019-04-30_at_2 05 08_pm](https://user-images.githubusercontent.com/5634774/57101206-b2d79580-6cee-11e9-9514-2b5ba59328e5.png)
