### ISSUE TITLE
Inline Justify text not reflected in editor

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#32648]
**Update 2023-04-05** - This issue was closed as completed on Feb 26, 2021, but was reopened on Dec 25, 2022, and user reports have been steadily coming in since then. Please see [my latest comment](https://github.com/Automattic/wp-calypso/issues/32648#issuecomment-1498211764) for newest triage/scrubbing notes.

---

_Older notes_

**Update Nov 18, 2019: This is now broken only for [Atomic sites on all browsers](https://github.com/Automattic/wp-calypso/issues/32648#issuecomment-555210007).**

This is feedback on an issue I came across while testing Jetpack v7.3-alpha-9688-g91a3f01 (also happens in WPCom Simple)

This is currently broken for Simple, Jetpack and Atomic sites, but [only in Firefox and only in the Editor](https://github.com/Automattic/wp-calypso/issues/32648#issuecomment-497868118).

#### Steps to reproduce

_Update 2023-04-05 as previous report did not include steps, and included now-expired screenshots_

1. Open page or post and add text in a paragraph block
2. Use the block's floating toolbar to **Justify**
3. Save the content and view the live site

#### What I expected

The paragraph to appear justified in the editor, and the "Justify" button in the menu to be highlighted

#### What happened instead

Text appears justified in the live site, but the editor does not reflect the change.  The only change seen in the editor is the floating toolbar's `v` icon is highlighted, indicating a change has been made there.

![Markup on 2023-04-05 at 15:07:59](https://user-images.githubusercontent.com/27249804/230222697-2006bb55-4e3b-474a-bfdf-4da5d7b55de7.png)

![Markup on 2023-04-05 at 15:08:12](https://user-images.githubusercontent.com/27249804/230222731-5f903235-2e85-4699-adb6-c4677e50797f.png)

**Comment by mattwiebe** [comment]
Firstly, underline is working fine. The red spellcheck dots seem to be obscuring it in the editor. I'm going to edit out that portion for clarity.

Secondly, the justified text is oddly broken, but **only in Firefox**, and only in the Editor. Having devtools open shows that the paragraph is receiving the correct inline `style` attribute but it's not reflected in the editor:

<img width="931" alt="Screen Shot 2019-05-31 at 16 32 48" src="https://user-images.githubusercontent.com/195089/58736000-ea0a9680-83c1-11e9-9c79-a531c7d82c22.png">

The same behaviour was observed on both Jetpack and WPCom Simple, which is to be expected given that both rely on the same script.

Given that this is only affecting Firefox and a little light Googling didn't turn up any results, I'm going to bump this to lower priority.

**Comment by mmtr** [comment]
According to [this](https://stackoverflow.com/questions/30887273/justify-content-with-pre-wrap), it seems that the `white-space: pre-wrap` style is causing the issue.

<img width="1002" alt="Screen Shot 2019-06-08 at 12 36 14" src="https://user-images.githubusercontent.com/1233880/59141556-13db4300-89ea-11e9-954c-c62637234ee4.png">

**Comment by gwwar** [comment]
If this rule is coming from Gutenberg we may need to make a PR to reduce CSS specificity for this case.

**Comment by tijosh** [comment]
Another report of this via WPcom ticket #2106996-zen

Please ping me when resolved so I can follow up with the user.

**Comment by tanjoymor** [comment]
Another report here: #2145106-zen

**Comment by geekinthegirl** [comment]
One more report here: #15531608-zen

The user's going to check back in with us in a few days.

**Comment by susanjanec** [comment]
A report here 15496168-hc - in this case, the Justified option is applied to the text, but is not showing up on the user's site. Provided CSS as a workaround for now.

**Comment by smithkyle45** [comment]
I had a report of this recently in [14764602-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=14764602)

I provided CSS as a workaround. I would like to notify them of the fix when available.

**Comment by mikeicode** [comment]
Another in 15020826-hc the class is added to the text but not applied. They say it stopped working the same day 6.5 was released.

**Comment by susanjanec** [comment]
Added new GH report regarding specific issue here - #36391

**Comment by chatoxz** [comment]
Another #2398420-zen.

Fixed it with:

.has-text-align-justify{
   text-align: justify;
}

**Comment by davipontesblog** [comment]
Here is another report, on an atomic site running Gutenberg 6.6 plugin - #2414777-zen

**Comment by hacchism** [comment]
Another report: #2415200-zen
Gave them a CSS code as a temp solution.

**Comment by ccwalburn** [comment]
This is an instance where the justified text displays correctly in the editor, but not on the front end.

The user said that it worked when they added the text, but then after they edit it, it changes to left-justified. The issue can be seen on their home page.

I added CSS as a workaround: 

```
.has-text-align-justify{
   text-align: justify;
} 
```

#2471641-zen

**Comment by mikeicode** [comment]
Another in 16387878-hc I gave the CSS fix for now.

**Comment by chaitanyamsv** [comment]
Another report in 13812215-hc

**Comment by kwight** [comment]
Continuing reports on this issue are Atomic-related, and not Firefox-related, due to front-end styles for justified text not being properly enqueued in Jetpack. This will be fixed with JP 8.0, due out Dec 3rd, assuming the inclusion of this fix: https://github.com/Automattic/jetpack/pull/14070

**Comment by rinazrina** [comment]
Another report: 2525777-zen

**Comment by nerdysandy** [comment]
Reported on #2531269-zen But I shared the same CSS as mentioned above

**Comment by simison** [comment]
> This will be fixed with JP 8.0, due out Dec 3rd, assuming the inclusion of this fix

Jetpack 8.1.1 on Atomic, still broken.

**Comment by lizswafford** [comment]
#2722903-zen
Justify text does not appear in post editor but does appear in the post Preview and Published version.

**Comment by obenland** [comment]
This works as expected for me on an Atomic site with Twenty Twenty-One and Radcliffe 2 themes.

Please feel free to re-open with testing instructions if this is still reproducible for you.

**Comment by sudeepbaral** [comment]
The issue seems to have resurfaced below.

- [ ] 5815915-zen

Using the justify text option in editor is not showing any changes but after we update the page/post the changes are reflected in the live page/post and the texts in paragraphs are justified.

The site is using Radcliffe 2 theme and is on Business plan.

Screen-recording showing the issue: 
https://user-images.githubusercontent.com/3326057/209509453-d692f056-07e4-44c1-a7c6-920d9e0cb7ea.mp4

**Comment by DavidSaladu** [comment]
Also reappeared here 5866007-zd-woothemes (Business plan and Jackson theme)

**Comment by freelylovinglife** [comment]
Another report 5885998-zen

**Comment by sudeepbaral** [comment]
Another report of the issue here (Personal plan, Livro theme): 

- [ ] 5896983-zen

**Comment by danielbachhuber** [comment]
I wasn't able to reproduce this my Simple site with the Livro Theme:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/36432/217397926-227346dc-0da8-4f72-971c-ab298f4b7a9e.png">

<img width="853" alt="image" src="https://user-images.githubusercontent.com/36432/217397954-6a2d9514-9f66-4536-8654-56453f49d320.png">

However, I was able to reproduce the issue in the site from 5866007-zd-woothemes

<img width="908" alt="image" src="https://user-images.githubusercontent.com/36432/217398941-4b45274b-a8f9-428e-af79-a210b60c9437.png">

<img width="909" alt="image" src="https://user-images.githubusercontent.com/36432/217398998-48bd424a-8769-4ff0-a398-977a757eafb4.png">

My Simple site seems to have the `.has-text-align-justify` CSS injected into the DOM:

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/36432/217399131-4c9c4b49-3e2b-4d58-9550-d33045660cb7.png">

There doesn't appear to be any equivalent in the user's site:

<img width="1739" alt="image" src="https://user-images.githubusercontent.com/36432/217399197-c26b50d0-8f37-41b4-8344-45373201e4ad.png">

**Comment by danielbachhuber** [comment]
I was able to reproduce this on my test Atomic site with the Jackson theme.

Here's where the `.has-text-align-justify` CSS is injected in Jetpack:

https://github.com/Automattic/jetpack/blob/210e75345653abee7954a11d3669cd56175b9ea5/projects/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L400-L407

It seems to make it into `wp-block-library-inline-css`:

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/36432/219425997-cc9e8d99-ef8b-43f9-9f71-80ef7aa8114f.png">

However, it some how gets stripped off the end of the blob passed to the iframe:

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/36432/219425527-88c6a874-1d09-4477-9d5e-610fc9ee4a98.png">

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/36432/219426323-a5503b79-51be-46ba-a0ad-daece42b20dd.png">

Changing the priority for `enqueue_block_assets` doesn't seem to have an impact.

**Comment by danielbachhuber** [comment]
Somewhat related https://github.com/Automattic/wp-calypso/issues/66474#issuecomment-1432236259

It seems like there's a history of related issues at the intersection of `wp_add_inline_style()` and the `<iframe>` editor https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+wp_add_inline_style

**Comment by jamiepalatnik** [comment]
Encountered an issue with justify not working in editor or preview on a simple site, Varese theme. 

I also tested on a simple test site with Bitácora theme active and was able to recreate this issue for a Paragraph block in a column, but justify worked when the Paragraph block was not in a column.

Chat: 41897993-hc

**Comment by tanjoymor** [comment]
Another case with Russell theme. Not working in editor, but applying the setting and updating does render it on the live site. 

Chat: 33780387-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **Yes** _(feature powered by Jetpack plugin)_

📌 FINDINGS/SCREENSHOTS/VIDEO
- Across my test sites, I'm not seeing any editor changes when using the toolbar's `Justify` tool:

**Screenshots/Recordings**

**Simple Site Example: Theme Livro - Editor**

https://user-images.githubusercontent.com/27249804/230220772-0dc8b001-6a06-40e3-91b4-bf8ad232d022.mov

**Atomic Site Example: Theme Zoologist - Editor**

https://user-images.githubusercontent.com/27249804/230221143-931f7863-5bdb-4a5d-bdd7-dabb4af64dbb.mp4


**Self-Hosted Site Example: Theme Twenty Twenty-Three - Editor**

https://user-images.githubusercontent.com/27249804/230220545-469685d5-c81d-44fc-b01e-251d89bc0033.mp4

**Self-Hosted Site Example: Theme Twenty Twenty-Three - Live Site**
![Markup on 2023-04-05 at 14:54:37](https://user-images.githubusercontent.com/27249804/230220555-d30b12bf-3c3b-44f6-8d86-b34a2ebbd5ae.png)

📌 ACTIONS
- Assigned to Cylon
- CC: @jeherve is this something Jetpack folks can/should help with?

**Comment by danielbachhuber** [comment]
@cuemarie FYI - @sejas is going to shape a Project Thread (https://github.com/Automattic/dotcom-forge/issues/1913) to 1) add the feature to Gutenberg (https://github.com/WordPress/gutenberg/issues/48202), and then 2) remove the feature from Jetpack (https://github.com/Automattic/wp-calypso/issues/73455).

Unfortunately, "fixing" the problem is going to take a little effort.

**Comment by cuemarie** [comment]
Ah, thanks for the insight, @danielbachhuber !

**Comment by sejas** [comment]
I'm not able to reproduce the issue in any case. Can someone else try to reproduce it?
Here are some recordings:

**Simple - Theme Livro** - Working as expected on calypso and wp-admin

https://github.com/Automattic/wp-calypso/assets/779993/091dfdaf-cc15-4085-ac02-8a4fa4810f3e


**Atomic - Theme Zoologist** - Working as expected on calypso and wp-admin

https://github.com/Automattic/wp-calypso/assets/779993/0ce4cdff-da01-46a6-9a8f-e74469122712


**Atomic - Theme Jackson** - Working as expected on calypso and wp-admin

https://github.com/Automattic/wp-calypso/assets/779993/93cfc7c3-cd09-4503-a43c-0ddaf38ee4fd


**Self-hosted - Theme Twenty Twenty-Three** - Working as expected on calypso and wp-admin

https://github.com/Automattic/wp-calypso/assets/779993/e9b8fd87-0134-4685-b7f0-aa39007cae09

**Comment by cuemarie** [comment]
Thanks @sejas - It's working for me as well across all test sites. I'll go ahead and close!

📌 ACTIONS
- Closed as resolved
