### ISSUE TITLE
"Authenticator" text that needs to be changed to lowercase

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#32654]
There was some work here https://github.com/Automattic/wp-calypso/pull/17599 a few years ago on changing all strings that read `Authenticator` to `authenticator`, but I still see one more. cc @iamgabrielma 

![Screenshot 2019-04-29 at 19 26 07](https://user-images.githubusercontent.com/18581859/56902171-4f175780-6ab7-11e9-87bf-5f0ecb31e754.png)

This can be seen when attempting to login on a WordPress.com account with 2 step authentication enabled and having push authentication enabled (users of WordPress app)

I searched Calypso codebase, but I am not seeing any string. Any chance you would know where this comes from, @klimeryk?

**Comment by klimeryk** [comment]
Ah, this one comes from the backend. Since it was a quick one to address I fixed it and one other that I noticed in the same file (`Please enter the verification code generated by your Authenticator mobile application.`) in r191197-wpcom. Thanks for pointing it out! 🙌
