### ISSUE TITLE
Login: Authenticator login text is misplaced and is missing styles

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#32653]
#### Steps to reproduce 

- Login into WordPress.com with an account having 2 step authentication enabled
- When a push notification is sent to WordPress mobile app to authenticate, look for `Verify with code instead` button/CTA

#### What happens currently

![Screenshot 2019-04-29 at 19 26 07](https://user-images.githubusercontent.com/18581859/56901556-1034d200-6ab6-11e9-86e0-a5884a89072e.png)

Look at the `Verify with code instead` text at the very top of the image.

#### What is expected

- It should appear somewhere below the illustration and text.
- It has proper styles.

I am not very sure how it used to display in the past.

**Comment by jsnajdr** [comment]
Hi @arunsathiya! The screenshot doesn't look like a Calypso UI. Maybe it's the WP.com login page? What is that page's URL?

The Calypso one (at `wordpress.com/log-in/push`) looks like this:

<img width="975" alt="Screenshot 2019-04-29 at 16 53 32" src="https://user-images.githubusercontent.com/664258/56905455-862e3e80-6aa0-11e9-9064-3f68b2624fdb.png">

**Comment by torres126** [comment]
Looks like this was added in #13235

**Comment by arunsathiya** [comment]
Giving it a closer look, it does look to be a WordPress.com login page. Let me move this to the internal tracker, thanks! 👍🏽

**Comment by arunsathiya** [comment]
8146-wpcom
