### ISSUE TITLE
Theme gallery: uploaded themes should not display an "Open live demo" button.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#32663]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/
2. Upload a theme.
3. Click on that theme to view its information page.
4. Click on "open live demo".

#### What I expected
To see a live demo of the uploaded theme.

#### What happened instead
You see a generic, non-setup WordPress blog. Which is confusing for users (is the theme broken?)

It's understandable we can't display theme demos of randomly uploaded themes, but in that case we shouldn't display that link, either.

#### Browser / OS version
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

Pop!_OS 18.10

#### Screenshot / Video

![Peek 2019-04-29 12-14](https://user-images.githubusercontent.com/10121835/56914148-fb861900-6a78-11e9-908e-9968b46241ae.gif)

**Comment by tijosh** [comment]
User reported this issue as broken functionality in #2326185-zen

**Comment by Aurorum** [comment]
I can't reproduce this, was this fixed?

When on the single theme view, I see a button to "Customize site" instead.

<img width="768" alt="Screenshot 2020-04-06 at 09 39 11" src="https://user-images.githubusercontent.com/43215253/78539487-8f647700-77ea-11ea-9c8d-f7e31e176063.png">

When clicking "Live Demo" on the popover, I'm redirected to an external site with a proper demo: https://wp-themes.com/petals/?demo=true&iframe=true&theme_preview=true

<img width="328" alt="Screenshot 2020-04-06 at 09 39 23" src="https://user-images.githubusercontent.com/43215253/78539538-a3a87400-77ea-11ea-9bb8-4bb18ee858c4.png">

**Comment by lancewillett** [comment]
I'm still seeing a link to "Open Live Demo" on https://wordpress.com/theme/petals

URL: `https://wordpress.com/theme/petals/lancetest14.wordpress.com`

<img width="1392" alt="Screen Shot 2020-04-14 at 14 45 41" src="https://user-images.githubusercontent.com/66797/79277422-9f213280-7e5e-11ea-849b-1a07c9b35019.png">

Nothing happens, though, as the request is blocked:

`Blocked a frame with origin "https://wp-themes.com" from accessing a frame with origin "https://wordpress.com". Protocols, domains, and ports must match.`
