### ISSUE TITLE
Purchasing eCommerce plan on an unlaunched site results in site remaining private after going AT

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#32671]
Originally reported and discussed in p9F6qB-33v-p2

New WPCOM simple sites are now private by default, and need to be “launched” to be made public. If this isn’t done before purchasing the eCommerce plan, this causes some issues after the site goes AT automatically upon plan purchase, as the site is still marked private in the `blog_public` status after it goes AT

As mentioned in the P2 linked above, the same types of blocks/warnings that are in place for users going AT on their own should also be put in place for sites going AT automatically after eCommerce plan purchase, including a warning about launching the site first, and what features are lost when going AT.

Steps to replicate:

1. Create a new free site and make sure to leave it as private (don’t click the launch site button under Settings > Privacy)
2. Purchase the eCommerce plan on the site, check and make sure the site went AT
3. Check the site’s privacy with option get `blog_public` in CLI and it will be set to -1 which is private

Here's what I see in Calypso immediately after going AT: https://cld.wthms.co/VQROFw
Neither privacy setting, hidden or public, is selected under Privacy settings.

On any impacted sites, the issue can be resolved by setting the site to Public under Privacy Settings in Calypso, then disconnecting and reconnecting Jetpack.

**Comment by GeoJunkie** [comment]
This can also happen when purchasing an eCommerce plan on a brand new site. I recreated it with two test sites.

I also found that a Jetpack disconnect/reconnect will remove the Jetpack error and allow the user to manage their site, but `blog_public` is set to `-1` and Calypso shows no options selected for site visibility: 

<img width="757" alt="Screen Shot 2019-04-30 at 17 07 26" src="https://user-images.githubusercontent.com/7596032/56993448-7bd87700-6b6a-11e9-9608-96e09f6cc224.png">

**Comment by seear** [comment]
This is preventing backups on sites, because the Rewind activation process calls (for example) `https://public-api.wordpress.com/rest/v1.1/sites/161822052?force=wpcom&fields=URL` to get the URL for a site, which is 403ing for sites with this problem.

**Comment by AtrumGeost** [comment]
I was able to replicate the issue. Got a free private site, then purchased the eCommerce plan. Got stuck on this screen during the onboarding process:

![Screen Shot 2019-06-17 at 08 04 53](https://user-images.githubusercontent.com/3696121/59606669-58946780-90d7-11e9-96e2-b45398887627.png)

Took me a couple of tries to figure out it was because my site was private 😅

**Comment by jessestu** [comment]
I experienced this in 2135318-zen (concierge call)

When I went to Settings to switch to public, then reconnect JP, the whole Settings page disappeared and said "Jetpack 3.3 is required to manage Settings". So, I disconnected JP, reconnected. Changed the setting, then disconnected and reconnected again. I don't know if that all was required, but it's fixed now.
