### ISSUE TITLE
Jetpack Checklist: Point Rewind Task link to Rewind UI

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#32698]
Carried over from #32557 and #32649:

> 2. backup and scan feature:
>    1. [x] remove site security card below checklist.
>    2. [ ] add link to "view security dashboard" in the completed checklist item.
>       - [x] for now it should take the customer to their respective vaultpress dashboard.
>       - [ ] in the future, we'll send them to the calypso UI formerly known as Rewind (cc @rcoll )

Furthermore: https://github.com/Automattic/wp-calypso/issues/32557#issuecomment-487577032:

> [...]
> Note that we already have separate checklist items for VaultPress
> https://github.com/Automattic/wp-calypso/blob/0fb357b99f5fe8f46b08a43991ab93d8e7033c06/client/my-sites/plans/current-plan/jetpack-checklist/constants.js#L72-L75
> 
> 
> vs Rewind:
> https://github.com/Automattic/wp-calypso/blob/0fb357b99f5fe8f46b08a43991ab93d8e7033c06/client/my-sites/plans/current-plan/jetpack-checklist/constants.js#L61-L70
> 
> which are conditionally used depending on which of either the site is using.
> The 'Rewind' one already points to the Rewind Calypso UI. I'll just change the link label from 'Change' to 'View security dashboard'.
> 
> **Edit:** Hmm, this might mean that we need different links in the 'completed' state (different from the 'setup' case).

Elaborating on the latter:
- The link is currently pointing to `/settings/security/:site`, where the user can set up credentials for Rewind.
- The Rewind UI is located at `/activity-log/:site`. If credentials haven't been provided, there is a banner on top of the page starting a wizard to add them (different from `/settings/security/:site`).
- We don't currently have a mechanism to provide different links in case of completed vs pending tasks. I'm not sure if there should be one, since arguably, whatever target we're pointing to in the 'completed' case should alert and/or redirect the user to set up the feature first.

@jeffgolenski How should we proceed here? :grimacing:

**Comment by jeffgolenski** [comment]
@ockham Hey hey B - Sorry for the late response due to AFK. 

Can you help me understand the scenario a little better? In my mind, I'm thinking that:

1) If VaultPress is setup, we send customer to their VP dashboard (as shown in the mockup in #32557)
2) If rewind is enabled, we instead send them to their rewind / activity log area. 
 
My logic behind this is that VP is currently the tool that's being set up... but in the future, if / when VP sunsets, we'll have that switch to flip to send them to rewind seamlessly. 

The priority here is of course the VP logic since that's the active tool for most everyone.

**Comment by ockham** [comment]
Hey Jeff! And no worries :grimacing: Sorry for taking a while to get back to you now :sweat_smile: 

> @ockham Hey hey B - Sorry for the late response due to AFK.
> 
> Can you help me understand the scenario a little better? In my mind, I'm thinking that:
> 
> 1. If VaultPress is setup, we send customer to their VP dashboard (as shown in the mockup in #32557)
> 2. If rewind is enabled, we instead send them to their rewind / activity log area.
> 
> My logic behind this is that VP is currently the tool that's being set up... but in the future, if / when VP sunsets, we'll have that switch to flip to send them to rewind seamlessly.
> 
> The priority here is of course the VP logic since that's the active tool for most everyone.

So the problem isn't really about VP vs Rewind :slightly_smiling_face: -- fortunately, they are separately encoded, so we can treat them differently.

The question is about what link target to point a checklist item to, depending on its completion status (relevant only for Rewind, not for VP). Currently, each checklist item can only point to one given link target, irrespective of its completion status. However, the Rewind UI (to which we'd want the 'View security dashboard' link to point to) lives at `/activity-log/:site`, i.e. a location that's different from the Rewind setup screen `/settings/security/:site` (to which we point the user if the checklist item hasn't been completed yet).

So my question is essentially, do we want to add logic to conditionally point the user to different link targets depending on checklist item completion state? My gut says: No, not really worth the added complexity; little added benefit -- after all, the main use case is when checklist items _haven't_ been completed yet; and potentially confusing to the user. Instead, I think it'd should be the target screen's responsibility to prompt them user to complete setup, or to redirect wherever they can do so. (Currently, there's a banner on top of `/activity-log/:site` if Rewind hasn't been set up, but alas, it starts a wizard that lives at a different location than `/settings/security/:site`.)

**Comment by jeffgolenski** [comment]
>  after all, the main use case is when checklist items haven't been completed yet; and potentially confusing to the user. Instead, I think it'd should be the target screen's responsibility to prompt them user to complete setup, or to redirect wherever they can do so. 

Add that logic in the tail end of that experience is fine with me. I think that makes most sense since rewind is going to be built right into the UI of activity log, essentially. We'll send the customer there. The "view security dashboard" link will only show on a completed task. At this point we really haven't had any discussions about how we'll be implementing Rewind for all our customers - I think that's a ways off, so we can punt that conversation down the line. 

Let mw know if I'm missing anything - that's a complex scenario you wrote out above. haha

**Comment by ockham** [comment]
> > after all, the main use case is when checklist items haven't been completed yet; and potentially confusing to the user. Instead, I think it'd should be the target screen's responsibility to prompt them user to complete setup, or to redirect wherever they can do so.
> 
> Add that logic in the tail end of that experience is fine with me. I think that makes most sense since rewind is going to be built right into the UI of activity log, essentially. We'll send the customer there. The "view security dashboard" link will only show on a completed task. At this point we really haven't had any discussions about how we'll be implementing Rewind for all our customers - I think that's a ways off, so we can punt that conversation down the line.

Great, sounds good to me :+1: 

> Let mw know if I'm missing anything - that's a complex scenario you wrote out above. haha

Indeed, sorry 'bout that :sweat_smile:
