### ISSUE TITLE
Jetpack Checklist: Add Guided Tour for Brute Protect Task

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#32699]
Carried over from #32557 ([illustration](https://user-images.githubusercontent.com/214813/56674490-27278e80-6688-11e9-9b36-5f377316150e.jpg)) and #32649:

> - [ ] Brute force attack feature:
>  - Add Guided Tour
>  - Auto-expand

**Comment by ockham** [comment]
There are a few conceptual questions with this Guided Tour:

Our current UX paradigm is to trigger a Guided Tour only if the corresponding checklist item hasn't been completed yet. However, Brute Protect is enabled by default:

![image](https://user-images.githubusercontent.com/96308/58070035-5367f980-7bb9-11e9-8559-a875bf0f4d35.png)

We could make it so that the checklist item becomes unchecked again if the user disables Brute Protect manually (we have logic to support checks like that), which would then trigger the Guided Tour if they clicked on the checklist item. However, this seems like a total edge case, and arguably, if a user managed to find the screen to _disable_ Brute Protect, there doesn't seem to be a lot of need for a Guided Tour to that screen to show them to turn it (back) on.

Finally, another way to use a Guided Tour for this checklist item could be to show the user additional features after the item has been completed (such as using the IP whitelist, in this case), but that would require quite a lot of changes to the checklist implementation -- and the underlying UX paradigm, at the risk of over-exposing them to too many Guided Tours (not just for unchecked checklist items, but also completed ones).

![image](https://user-images.githubusercontent.com/96308/58069935-f8ce9d80-7bb8-11e9-8cea-e55e8de2c00e.png)

Should we:
1. Implement the Guided Tour in case the Brute Protect item is unchecked (which, as stated above, will only be triggered if the user actively disables Brute Protect since it's auto-activated upon JP Connect) [edge case, dubious added value]
2. Make changes to show (different?) Guided Tours for completed checklist items [changes UX paradigm, significant implementation effort for a rather unspectacular Guided Tour]
3. Not add a Guided Tour for this checklist item?

@jeffgolenski @johnHackworth

**Comment by jeffgolenski** [comment]
@ockham 

Based on this:

> We could make it so that the checklist item becomes unchecked again if the user disables Brute Protect manually (we have logic to support checks like that), which would then trigger the Guided Tour if they clicked on the checklist item. However, this seems like a total edge case, and arguably, if a user managed to find the screen to disable Brute Protect, there doesn't seem to be a lot of need for a Guided Tour to that screen to show them to turn it (back) on.

I think it's more than fine to leave out the guided tour for now since most customers will have it auto enabled. We don't yet know what the usage will be of the "Configure" link, so until we see heavy usage, i don't think the effort to build that in is needed. I think we can address this in the near future when we look at phasing out jumpstart in jetpack inside wp-admin, completely.
