### ISSUE TITLE
Editor: on-page search doesn't work as expected

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#327]
Steps to reproduce:

1. Open a post and add a small amount of text
1. Search for one of the words in the text

<strong>Result:</strong> notice that the search results are double what they should be and you have to cycle through the content once before you start seeing words get highlighted in the edit area—very impractical for posts with a lot of content

Reported at https://en.forums.wordpress.com/topic/editor-feedback/page/8?replies=98#post-2500332

From codebykat

> I wonder if it's also searching the hidden TinyMCE textarea?

**Comment by aduth** [comment]
It appears that this is related to the background preview `iframe` and will be incidentally fixed by #517.
