### ISSUE TITLE
Jetpack Version is Stale

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#32709]
The Jetpack version in Calypso state may be stale, causing issues when we change Jetpack versions during upgrade or testing. The Jetpack version is used to determine things like if we should enable certain features or redirect to specific areas.

To reproduce this issue:
- Connect a Jetpack Site
- Install the Jetpack Beta Plugin
- Choose Bleeding Edge
- Visit https://wpcalypso.wordpress.com/block-editor/yoursite/post/X
- Verify that we can edit in the block-editor
- Update settings in the Jetpack beta plugin to latest released version (not bleeding edge) 
- Visit https://wpcalypso.wordpress.com/block-editor/yoursite/post/X?debug

The incorrect version is read:
<img width="901" alt="Screen Shot 2019-04-30 at 3 58 49 PM" src="https://user-images.githubusercontent.com/1270189/56998714-38c5d600-6b61-11e9-9ec2-6c883a1c3d67.png">

`state.sites.items[ state.ui.selectedSiteId ].options.jetpack_version` returns `7.3-alpha` instead of `7.2.1`

I would recommend adding a query component to update this value more consistently. Maybe in layout since this is used in many views.

**Comment by mmtr** [comment]
A quick update before further investigating this. Seems that problem is with the `/me/sites` endpoint returning a cached value. 

We already have a query component that updates the options of all sites (including the jetpack version) on the layout ([#](https://github.com/Automattic/wp-calypso/blob/4479631cb241355d04cdd0f6ec139feb38a978c3/client/layout/index.jsx#L126)).

That query component makes an API request to `/me/sites` but the response contains a cached `jetpack_version` value for my test JP site (`7.3-alpha` instead of `7.2.1`). I get the same response when testing manually on https://developer.wordpress.com/docs/api/console/. However I noticed that the `/sites/:site` endpoint returns accurate data.

**Comment by mmtr** [comment]
I'm facing a wall and I don't know how to get any progress on this, so I'm going to leave it here and hopefully someone else can identify what I'm missing.

For some reason, the WP.com-side of the Jetpack site has a wrong value for the blog option that stores the identify the JP version which is the value we return on calls to `/me/sites` (see `public.api/rest/sal/class.json-api-site-jetpack-shadow.php#L258` and `wp-content/mu-plugins/misc.php#759`).

That value comes from a constant that Jetpack syncs back to WP.com ([#](https://github.com/Automattic/jetpack/blob/1109bc63b610ec5503c8a97c8999234d1fa9f07b/sync/class.jetpack-sync-defaults.php#L195)). 

Maybe the Jetpack Beta plugin is not updating that constant when switching between stable, RC and bleeding edge? Or maybe Jurassic Ninja sites have some kind of limitation that prevents from syncing the constants?

**Comment by obenland** [comment]
@Automattic/jetpack-crew Do you have any advice on that? ^

**Comment by kwight** [comment]
> Maybe the Jetpack Beta plugin is not updating that constant when switching between stable, RC and bleeding edge? Or maybe Jurassic Ninja sites have some kind of limitation that prevents from syncing the constants?

I still have this issue on my local JP (not JN), and after disabling the beta plugin and downgrading Jetpack (by checking out the `7.2` SHA).

**Comment by kwight** [comment]
Noting also that I don't think we should consider this a blocker; any users with 7.2 and lower are properly handled (they are sent to `wp-admin` via Calypsoify). It only affects those that have the `jetpack_version` successfully synced at >=7.3, then downgrade.

**Comment by gwwar** [comment]
What's the time to cache invalidation for that response @mmtr ? If folks have a stale value, on upgrade they also won't get new features until that happens or until they happen to clear browser cache.

**Comment by kwight** [comment]
I've verified this is fixed by @enejb in D27700-code. 🎉
