### ISSUE TITLE
SEO Tools isn't available on eCommerce plan?

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#32714]
#### Steps to reproduce
1. Make sure that a site is on eCommerce plan
2. Go to "Tools > Marketing > Traffic" (URL: https://wordpress.com/marketing/traffic/mydomain.com)
3. Make sure that `Enable SEO Tools to optimize your site for search engines` is on under `Search engine optimization
` section.

![Screen Shot on 2019-05-01 at 15:38:59](https://user-images.githubusercontent.com/32432463/57008040-177bed00-6c28-11e9-9b65-8ed9279855a5.png)

#### What I expected
We should see some sections from SEO Tools mentioned in https://en.support.wordpress.com/seo-tools/ (such as `Custom Title Formats`, `Front Page Meta Description`, etc)

#### What happened instead
Don't see anything related to SEO Tools. 

#### Context / Source
I originally found this on one of our user's sites on eCommerce plan. And I could reproduce it on my test eCommerce site. Also, another HE could reproduce it on his test site (p1556687048259200-slack-livechat)

**Comment by belcherj** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/32734
