### ISSUE TITLE
Gutenframe: Autosave admin notices persist after closing the revisions modal.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32710]
Gutenframe uses Calypso's Revisions modal instead of the core `revision.php` page. This means that if a user clicks "View the autosave" admin notices, the notice will remain after they've returned from closing the Revisions modal. Core doesn't have this situation, since clicking the notice sends the user to `revision.php` (meaning a full page reload occurs however the user returns to the editor).

<img width="1130" alt="Screen Shot 2019-04-29 at 12 53 20 PM" src="https://user-images.githubusercontent.com/349751/57001037-6e6fbc80-6b6b-11e9-93aa-f29da57a957f.png">

**Comment by kwight** [comment]
I'm imagining we need to fire an action that closes the active notice, as clean up from closing the Revisions modal.

**Comment by obenland** [comment]
It's an interesting UX conundrum. On the one hand, clicking on "View the autosave" technically doesn't convey the intention of closing the notice. On the other, once the autosave has been viewed and dismissed, there is no need to show the notice anymore.

@mapk Do you have any advice?

**Comment by kwight** [comment]
Hm, really, it's useful to keep it if the user cancels out of the modal, but if they Load a revision, they've taken decisive action and removing the notice automatically makes sense. So maybe the fix is removing the notice only on Load click in the modal.

**Comment by mapk** [comment]
Sorry for my late response here, but it looks like the solution in the PR makes sense to me. Thanks for the ping!
