### ISSUE TITLE
Editor: Preview not displaying edits to published pages

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#32725]
This issue is based on a user's report. I tested this issue on my test site, https://atomicpljcbsn.blog

#### Steps to reproduce

1. Edit a _published_ page in some way in the block editor;
2. Click **Preview** to preview a change;
3. The preview doesn't reflect the change;
4. Click **Update** to publish the updated version of the page;
5. The published version of the page reflects the edits.

This doesn't affect _Draft_ pages.

#### What I expected

Edits to a published page should appear in a page preview when I click on the **Preview** button in the block editor.

#### What happened instead

Edits to pages don't appear until the edited pages are published by clicking on the **Update** button.

#### Browser / OS version

Browser: Firefox Developer Edition v67.0b14 
OS: macOS 10.14.4

#### Screenshot / Video

Testing with the DailyMag theme that the user who reported the issue was using:

![dailymag_preview_issue](https://user-images.githubusercontent.com/2912202/57022808-e821ac00-6c38-11e9-90a4-fb309354757b.gif)

Testing with Twenty Nineteen theme:

![dailymag_preview_issue_part2](https://user-images.githubusercontent.com/2912202/57022952-68e0a800-6c39-11e9-82c9-bba5f99fe039.gif)

#### Context / Source

This was a user report. The follow-up ticket with relevant links is 2000699-zen

**Comment by lancewillett** [comment]
Thanks for this report. I'm removing the High label for now.

@gwwar (non-urgent ping) Could you triage this one and see if it needs dev attention to research a fix? That way we'll know the scope of the issue.

**Comment by gwwar** [comment]
Should be fixed by https://github.com/Automattic/wp-calypso/pull/35824, which I verified behavior today. 

@pauljacobson please reopen if you're able to reproduce,
