### ISSUE TITLE
Signup: Not possible to edit site name after submitting the step

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3273]
Start from `/start/developer` to replicate (other signup flows don't have the same steps).

If you go through the desktop signup flow when logged out (or any flow with a site step), submit the site step, and then go "Back" to it, the site text field will be disabled. This is unnecessary as you should be able edit this step until it is submitted.

Noticed by @mjangda in #3221:

> Bug: hitting "Back" from step 3, you end up on step 2 with the text field filled but disabled and the button saying "Creating your site..."

**Comment by lancewillett** [comment]
Testing this today with the above steps — the site name is editable as expected. Can't reproduce now using Mac-n-Chrome desktop starting at https://wordpress.com/start/.

Even going to step 5, back to 1 or 2 — on step 3 the title field is still editable. When you change it, the suggested free domain changes as expected.

![screen shot 2016-05-03 at 1 42 56 pm](https://cloud.githubusercontent.com/assets/66797/14997702/f5400f92-1134-11e6-90ba-a25a85a20622.png)

**Comment by scruffian** [comment]
Thanks for investigating @lancewillett. The issue refers to the `site` step, which is different from the `domains` step which is shown above. I believe this issue still exists on the `site` step:

<img width="492" alt="screen shot 2016-05-04 at 10 00 31" src="https://cloud.githubusercontent.com/assets/275961/15009583/13cfe842-11df-11e6-9e5a-15c5dd2459d5.png">

You can reproduce by going to /start/developer.

**Comment by lancewillett** [comment]
Got it! Thanks for clarifying.

Here are full page screenshots (I find them more useful for the context, URL, etc.)

![screen shot 2016-05-04 at 10 29 06 am](https://cloud.githubusercontent.com/assets/66797/15022985/21d8cc98-11e3-11e6-950f-af0842e3f303.png)

![screen shot 2016-05-04 at 10 29 24 am](https://cloud.githubusercontent.com/assets/66797/15022986/246824ae-11e3-11e6-8a7d-3ad7be23bc78.png)
