### ISSUE TITLE
Republicize: social avatars don't load

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#32741]
@retrofox can you take a look at this (or bring in someone who can)?

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/
2. Select the three dot menu
3. Select "Share" from the menu
4. Look for the social media icons over where the avatars should be.

#### What I expected

I expected to see profile images associated with connected social accounts.

#### What happened instead

I saw white gaps that looked broken.

#### Browser / OS version
Chrome - latest / MacOS - latest

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1123119/57044287-58273680-6c27-11e9-826a-5e6f2331ec53.png)

#### Context / Source

#dogfooding

**Comment by arunsathiya** [comment]
I see the avatar just fine on production and latest `master`. 

<img width="752" alt="Screenshot 2019-05-02 at 10 15 58" src="https://user-images.githubusercontent.com/18581859/57056990-96723380-6cc3-11e9-9dba-681c8b4617a5.png">

<img width="764" alt="Screenshot 2019-05-02 at 10 17 26" src="https://user-images.githubusercontent.com/18581859/57056991-96723380-6cc3-11e9-8137-5488bdfa25be.png">

In the second image though, I uploaded my avatar on Twitter and reconnected, which is why it shows an image.

Wonder why it's blank at your end. 🤔

**Comment by MichaelArestad** [comment]
Thanks for testing @arunsathiya. I'll do more digging. Could be an extension or something.

**Comment by MichaelArestad** [comment]
Confirmed broken on every browser and on my phone (mobile Safari latest). I'm going to try disconnecting and reconnecting one of them.

**Comment by MichaelArestad** [comment]
Disconnecting and reconnecting did the trick, but I shouldn't have to do that.

Here's what it looks like after reconnecting just Twitter:

![image](https://user-images.githubusercontent.com/1123119/57159371-fbe92180-6da2-11e9-9f0a-6209fd0754d3.png)

**Comment by arunsathiya** [comment]
Actually, I can reproduce the issue now. Same on the [connections page](https://wordpress.com/marketing/connections).

<img width="1076" alt="Screenshot 2020-02-14 at 20 26 47" src="https://user-images.githubusercontent.com/18581859/74541830-618c5000-4f68-11ea-9334-dc3befd0374f.png">
<img width="1099" alt="Screenshot 2020-02-14 at 20 26 40" src="https://user-images.githubusercontent.com/18581859/74541855-6ea93f00-4f68-11ea-8ef5-164b7fe4218d.png">

**Comment by lancewillett** [comment]
Let's keep this open for when a team loops back to Publicize flows in Calypso.

**Comment by cometgrrl** [comment]
@pablinos Doesn't this fall under Jetpack/Reach now? Should we move it to the Jetpack repo? It's pretty old, and I wasn't able to reproduce, but I didn't want to close it without sending it your way first.

**Comment by pablinos** [comment]
Yes, that seems like a good plan, although this code does live in Calypso. I don't think there's a clear line to be drawn. If it's still an issue then it should probably be Reach that fixes it, so perhaps this is best placed in the Jetpack repo.

**Comment by cometgrrl** [comment]
Ah, the pesky detail of where the code lives!  I'll leave it here in Calypso for now, and see if we can reproduce, if not, we'll close it.
