### ISSUE TITLE
InlineHelp: Should the Help button be a FAB or not according to Muriel?

### ISSUE THREAD

**Issue by allancole** [Automattic/wp-calypso#32740]
The bottom-right Help button is technically a FAB (Floating Action Button). It’s unclear wether it should be a FAB or or some other kind of high emphasis button. Material Design guidelines suggests only having one(1) FAB per page, which means we should re-design and/or reposition the Help button. Material Design also recommends [adding it to multiple navigation menus](https://material.io/design/communication/help-feedback.html#use-placement) as an alternative. 

I’m not sure what is right here, but I think it deserves further discussion and some input from Muriel folks, cc: @drw158, @cburton4 

#### Screenshot

![image](https://user-images.githubusercontent.com/709581/57043712-5ca71b80-6c36-11e9-9630-fd1be98c31e4.png)

#### Context / Source
This issue came about while reviewing this related issue: https://github.com/Automattic/wp-calypso/issues/32639 and was lightly discussed in the #muriel-designdev channel without a clear solution.

#dogfooding #manual-testing

**Comment by donpark** [comment]
Given that there is at least one outstanding issue (#32283) around the placement of FAB Help button, we should consider moving it elsewhere with less chance of conflicting with layout, say somewhere on the Master Bar.

**Comment by cathymcbride** [comment]
Muriel is no longer. Closing...
