### ISSUE TITLE
Marketing: Sharing card CTA incorrect link

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#32767]
#### Steps to reproduce
1. Starting at URL: `/marketing/tools/[site]`
2. Click on "Start sharing" CTA on the Sharing card

#### What I expected
That it would link to `/connections/[site]`

#### What happened instead
It links to `/sharing-buttons/[site]`

#### Browser / OS version
Google Chrome Version 68.0.3440.106
Mac OS 10.14.12

#### Screenshot / Video
![Screenshot 2019-05-02 09 46 56](https://user-images.githubusercontent.com/4924246/57092614-9f153a80-6cc0-11e9-91cc-4ee9b6a2f5c1.png)

cc @ebinnion @belcherj @stephanethomas @cbauerman @huguesvincent

**Comment by stephanethomas** [comment]
We should also fix the wrong icon used for this card:

![screenshot](https://user-images.githubusercontent.com/594356/57611491-491f7d00-7573-11e9-986c-6a40c48189d3.png)

I indeed believe that the Mailchimp logo should be used on its own card.

**Comment by jancavan** [comment]
> We should also fix the wrong icon used for this card:

Fixed in: https://github.com/Automattic/wp-calypso/pull/32989
