### ISSUE TITLE
My Plan: Google Ads credit doesn't work for two year plans, eCommerce

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#32765]
#### Steps to reproduce
1. Starting at URL: On a site with a two-year Premium or Business plan or any eCommerce plan visit https://wordpress.com/plans/my-plan/jkgengo.com
2. Click Generate Code in the Google Ads credit section
3. After completing the flow a blank box is shown where the code should be.

#### What I expected
To have an ad code generated.

#### What happened instead
A blank box is shown where the code should be. The API returns a 403 that the site is ineligible:

![Screen Shot 2019-05-02 at 12 47 04 PM](https://user-images.githubusercontent.com/1900444/57091992-6a14e200-6cd8-11e9-8d7e-227a08801858.png)

After discussion with @ebinnion this appears to be because the code is specifically checking the following:

```
$planId = WPCOM_Store::get_subscribed_bundle_product_id_for_blog();
        $allowedPlanIDs = array( 1003, 1008 );
```

But the two-year plans and eCommerce plans have different IDs that do not match this.

#### Screenshot / Video

![Screen Shot 2019-05-02 at 12 35 42 PM](https://user-images.githubusercontent.com/1900444/57092108-9a5c8080-6cd8-11e9-944b-41dbd5a78b90.png)

#### Context / Source
#manual-testing, #user-report

@Automattic/catalyst

**Comment by kriskarkoski** [comment]
2000879-zen

**Comment by ebinnion** [comment]
This should be fixed in D28131
