### ISSUE TITLE
Gutenframe: Pexel focus outline cuts out

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#32772]
#### Steps to reproduce
1. Try inserting an image or Gallery
2. Click on Media Library
3. In the top left dropdown select Free photo library
4. Click into "Search for free photos"

#### Screenshot / Video
<img width="388" alt="screenshot-2019-05-02-at-12 13 40" src="https://user-images.githubusercontent.com/1398304/57097694-3da79880-6ccd-11e9-8e91-f9111ef2196e.png">

**Comment by torres126** [comment]
This is also the case in the classic Editor - open issue here too: #30974

**Comment by obenland** [comment]
Thanks for the heads up @torres126. Closing in favor of #30974.
