### ISSUE TITLE
Billing: My Memberships needs empty state

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#32770]
There's no empty state for the My Memberships tab. It looks like something is just not loading or broken.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/448298/57096674-d77a4000-6ce3-11e9-929b-c7f26a55d36f.png">

#### Steps to reproduce
1. Make sure you're logged in to an account with no active membership plans
2. Visit https://wordpress.com/me/purchases/memberships

#### What I expected
Some kind of empty state indicating I have no active memberships. Here's how it looks when you have no posts for a given site:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/448298/57096801-1dcf9f00-6ce4-11e9-9de9-f3ef5bdf50c2.png">

No pending payments:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/448298/57096975-7acb5500-6ce4-11e9-9b42-3bffcd891534.png">

#### What happened instead
There's a header but no content at all.

#### Browser / OS version
Firefox 66.0.3 / Mac OS 10.14.4 (18E226)

#### Context / Source
#dogfooding #manual-testing

**Comment by artpi** [comment]
CC @davemart-in

**Comment by alaczek** [comment]
@davemart-in can you think of an existing illustration that could work here?

**Comment by davemart-in** [comment]
One option from [this PDF](https://www.dropbox.com/work/design-repo-a8c/illustrations/dotcom%20Brand%20Illustrations/Landing%20Page%20Mockups?preview=Illustrations_bc.pdf) might be to take this illustration and replace the lock with a simple grey outline of a coin: https://cl.ly/35336276d5a0

**Comment by alaczek** [comment]
Good idea, I can mock that up! I also went through existing illustrations, and found this one that could potentially work:

![memberships](https://user-images.githubusercontent.com/4550351/57353374-9b475380-71ab-11e9-9d5f-73f1e2467fe4.png)

As for the text below, I was thinking:
* No memberships yet.
* No memberships found.
Often there's some sort of call to action too, but I can't think of any in this case.

**Comment by davemart-in** [comment]
Ah! Good point. No button needed then! :-)

**Comment by alaczek** [comment]
@artpi it's in `public/images/illustrations/type-blog.svg`
