### ISSUE TITLE
Full Site Editing: allow editing template CPT [3]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32796]
Templates may be edited using the Gutenberg editor as a custom post type, but not in a unified editor view. We should enable loading the full template in the editor and editing the surrounding parts of the page (`post_content` will not be editable in this phase).

To achieve this we'll want to allow accessing the template list in Calypso, which will require us to deploy the generated plugin files to Dotcom. Since we don't want to expose this to users yet, we should gate the plugin initialization behind a couple of checks:

- block sticker (e.g. `full-site-editing`) - this will allow us to easily add new test sites
- a12s - so it won't be enabled for user sites by accident
- sandboxed and !vip (just in case)

**Comment by rodrigoi** [comment]
Closed by `rWP191946` on D28074-code.
