### ISSUE TITLE
Site Settings: Start Over

### ISSUE THREAD

**Issue by johnmaeda** [Automattic/wp-calypso#32792]
#### Steps to reproduce
1. Starting at URL: WP.com/settings/start-over/

#### What I expected

There would be a button that lets me start my site over.

#### What happened instead

The documentation refers to the feature existing but it's not there.

#### Screenshot / Video

<img width="745" alt="Screen Shot 2019-05-03 at 9 23 59 AM" src="https://user-images.githubusercontent.com/2140796/57140380-a5b9b580-6d85-11e9-94cc-0a8e45fe52ca.png">

#### Context / Source

This feature apparently existed. Maybe it was forgotten to be reinstated when the "Follow the Steps" was re-prioritized?

https://github.com/Automattic/wp-calypso/issues/7594 cc @chrisfromthelc @jeremeylduvall 

**Update from Jun 2 2022**

As @jordesign mentions [here](https://github.com/Automattic/wp-calypso/issues/32792#issuecomment-998490859), this is still a good idea that gets requested fairly often by users in WordPress.com. We have HE-facing tools for both:

- Emptying Simple Sites (removes all posts, pages, comments, images, videos, settings in Customizer, submission forms. All you're left with is the theme you're using and the site title).
- Resetting Atomic sites (removes all posts, pages, tags, categories, uploaded media, and custom themes and plugins. The following actions are also taken: only default plugins installed, default WordPress theme installed, any WordPress.com site users retained, any SFTP users removed, Jetpack connected).

So the functionality is there - it's a matter of figuring out a design solution for making them user-facing.

This comes up in conversation with WordPress.com customers an average of 60 times per week in live chat with HEs since Jan 1, 2022 (internal data source).

**Comment by jeremeylduvall** [comment]
Is it still possible to empty a site through Calypso? Looking here:

https://en.support.wordpress.com/empty-site/

I only see:

1. Manually delete posts/pages
2. Create a new blog, export, import

I feel like this used to be an option. Not sure when it was removed.

**Comment by sixhours** [comment]
I have a feeling this is connected to Headstart. @ianstewart @kwight @michaeldcain  As former Headstart developers, do y'all know the history of the "Start Over" feature?

**Comment by kwight** [comment]
> There would be a button that lets me start my site over.

I think this is an example of unclear copy. Both processes that the copy refers to are manual processes: do-it-yourself (the first button, leading to the docs @jeremeylduvall is referring to), or by HE (who themselves would just follow the same docs). There is no automatic "empty my site" tool.

> I have a feeling this is connected to Headstart.

In fact, Headstart (well, on theme switch) is still active in Settings on `wpcalypso`:

<img width="1057" alt="Screen Shot 2019-05-13 at 8 34 09 AM" src="https://user-images.githubusercontent.com/349751/57634758-cd193b00-755a-11e9-9a7b-9dc65a8d6a5a.png">

It only does the theme switch part, but it was always an idea in my mind to use the site-emptying capabilities of Headstart to automate the Start Over section too. Then other priorities took over ¯\_(ツ)_/¯

**Comment by sixhours** [comment]
I no longer see an option in Settings to "Start Over". The page is there if you know the URL, but I can't find a link to it. Perhaps we should consider removing this page since it's not very helpful as a "setting" but more a support document.

**Comment by sixhours** [comment]
Taking that back, I found the option; I think it's only available to Simple (non-Atomic) sites, which is why I wasn't seeing it before.

**Comment by davipontesblog** [comment]
This is a really old issue, but I think it's still very relevant. With projects like Gutenboarding, it would be more and more invaluable to allow people to be sent back to the "new site creation" flow to start from scratch. Adding this to the Gutenboarding project for consideration.

**Comment by ianstewart** [comment]
This one's a bit stale but +1 to @davipontesblog. It's relevant _and_ in the wrong place — buried. Best considered as part of the onboarding flow. Adding it to the Create backlog for consideration later as part of ongoing onboarding efforts. cc @ollierozdarz

**Comment by jordesign** [comment]
Pinging @ollierozdarz  and @ianstewart on this 'Oldie but Goodie' to see if it is something worthing keeping in consideration as we keep looking towards onboarding options?

**Comment by kwight** [comment]
I think it'll be a great idea until we do it. 🙂 Depending on how the video UI project goes, Serenity might be a fit for this over the next couple of months.

**Comment by kwight** [comment]
Also recently mentioned in a user feedback report: p58i-bhH-p2

**Comment by jordesign** [comment]
Noting this is still a great idea :) Good news is that there is that we have HE-facing tools for both:
- Emptying Simple Sites
- Resetting Atomic sites

So the functionality is there - it's a matter of figuring out a design solution for making them user-facing.

**Comment by mpkelly** [comment]
As per this heads-up post, this feature is now available in Calypso. Closing this issue. 

p7DVsv-jA6-p2
