### ISSUE TITLE
Editor: autosave changes to localStorage

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#328]
When editing a post, the following needs to be done:
1. After the post is loaded, a poller needs to be added that triggers the autosave every so often. We might even do something like debounce editor change events or something so that it is more deterministic than a simple timer.
2. If the data hasn't changed, do nothing.
3. Else, write a backup to localStorage.

When loading an existing post, we need to:
1. Check localStorage to see if we have an autosave.
2. Show a UI for restoring the most recent autosave if there is one.

**Comment by alisterscott** [comment]
Closing this as auto-save is implemented in the editor and #1765 covers local storage (offline mode)
