### ISSUE TITLE
sync-handler: need some cache invalidation strategy

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3281]
Although indexedDB has a very large storage volume, it's still limited. So we need to implement some invalidation strategy to make sure we don't just completely fill up our available storage before we would launch this to production.

A first pass on this could just be time-based, like removing any fetches that are more than a few days old. We could probably launch with that, at least to horizon.

But we should also come back to this and add smarter logic. For example, if we run a fetch against a paginated list and we get a new value for `page_handle`, we know that any cached responses against later pages in the list can be removed because they no longer line up with the current pagination requests and will therefore never be requested again.

Another level of sophistication would be to determine the amount of storage available and the amount of storage taken and protect against going over our limit. Should probably do that in conjunction with the redux persistence.

/cc @retrofox @gwwar

**Comment by retrofox** [comment]
### time-based

Although every record has its own `__sync.synced` value, a marktime which is set when the record is synced, and localforage has a way to walk through of all records maybe maybe we could spend resources creating a new record (`records-history`?) where each item will have the pair values record-key and synced marktime so finally we just have to iterate this array filtering by its lifetime.

**Comment by rralian** [comment]
Yeah, that sounds reasonable. I would think this would be faster than iterating over all records (though I don't know for sure). But it will also be a good way to keep track of all of our stored records to see how the storage grows over time.
