### ISSUE TITLE
Refactor checklist to enable proper sorting, and collapsing and expanding

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#32823]
This task calls for a generic refactor of the checklist, used by WordPress.com, (and possibly Jetpack and WooCommerce???) to enable the following:

- hover state on uncompleted, collapsed tasks
- make the entire area of the elements comprising _uncompleted, collapsed_ tasks clickable
- allow expansion of uncompleted, collapsed tasks (assuming there is content inside the collapsed element)

See the discussion on: https://github.com/Automattic/wp-calypso/pull/32679

Also, if this task's scope permits, we can look at making the checklist tasks properly tabbable.

Completed tasks are displayed at the top of the list, however the elements themselves not sorted in order of completion, but by CSS voodoo.

We can fix this by sorting a collection of tasks. See comments on this GitHub Issue: https://github.com/Automattic/wp-calypso/issues/30386

**Comment by fditrapani** [comment]
Related PR: https://github.com/Automattic/wp-calypso/pull/33666

**Comment by ramonjd** [comment]
Closing this. It's been mostly dealt with in https://github.com/Automattic/wp-calypso/pull/33666 and the phase 2 checklist tasks (https://github.com/Automattic/zelda-private/issues/75)
