### ISSUE TITLE
Saving "Writing" settings in Calypso removes slashes from custom date format

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#32820]
#### Steps to reproduce
1. Starting at **WP Admin > Settings > General**, set up a custom date format with slashes like the default for pt-br `j \d\e F \d\e Y`
2. Go to [My Site > Manage > Settings > Writing in Calypso](https://wordpress.com/settings/writing/), make any changes and save
3. The custom date format on **WP Admin > Settings > General** will appear without slashes, which will cause to display incorrectly on the site

#### What I expected

Changing the Writing settings should not affect the Date Format

#### What happened instead

Changing the Writing settings broke the Date Format 

#### Browser / OS version

Any browser or OS

#### Screenshot / Video

Video: https://cld.wthms.co/vK0jHm

#### Context / Source
We had a lot of issues with this in the Portuguese Support queues but the volume slowed down to the point we thought the issue was fixed, so we never reported it.

The issue surfaced again and @yoavf recommended reporting it here.

**Comment by akirk** [comment]
This is not i18n specific, for example if you want to have a date like "May the 6th, 2019", you need to put `M \t\h\e jS, Y` and have the same problem in English.

**Comment by carinapilar** [comment]
Got another one on 2012619-zen.

Date shows like `5 05America/Sao_Paulo maio 05America/Sao_Paulo 2019`.

**Comment by liviopv** [comment]
#2110386-zen

**Comment by liviopv** [comment]
Another #2151180-zen

**Comment by lancewillett** [comment]
@donpark Could you please take a look at this one?

**Comment by donpark** [comment]
@lancewillett sure thing, Lance.

**Comment by donpark** [comment]
PR fixing this bug is ready for review.

**Comment by donpark** [comment]
This bug should now be fixed in production. Good job everyone!
