### ISSUE TITLE
Full Site Editing: disable opt-out for FSE sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32833]
Our planned Full Site Editing flows won't work well with Classic editor. There will be no way to change page templates easily. Let's just limit this functionality to Gutenberg and remove the ability to opt out or `Edit in Classic` for relevant post types.

This should probably cover the following for all FSE enabled sites:

- removal of core's `Edit in Classic` links and similar escape hatches if they exist.
- removal of `Switch to Classic` option in Gutenberg's ellipsis menu on Dotcom.
- removal of `Switch to Classic` option from Inline Help component in Calypso.

**Comment by rodrigoi** [comment]
Removing _Switch to Classic_ has already been covered by #32439 (#32735  and D27724-code), but we may want to revisit the rules to include a new sticker to override the theme list for example.

**Comment by gwwar** [comment]
We're currently gating on `full-site-editing` blog sticker, so the task here is to audit for any other areas and see if the current implementation holds up for our needs here.

**Comment by noahtallen** [comment]
Currently on my sandbox site with the sticker, I am unable to switch to classic anywhere within Calypso.

In wp admin, it is possible to edit a page with the classic editor:
<img width="400" alt="Screen Shot 2019-08-08 at 10 42 39 AM" src="https://user-images.githubusercontent.com/6265975/62725522-219d4c80-b9ca-11e9-824b-dce03f15cfec.png">

Making changes to it just affects the post content, so you are able to get back into the block editor ok.

You can add a new page with the classic editor too:
<img width="268" alt="Screen Shot 2019-08-08 at 10 43 48 AM" src="https://user-images.githubusercontent.com/6265975/62725547-31b52c00-b9ca-11e9-830f-195ffb6c7806.png">

This results in the following going back to Calypso:
<img width="1406" alt="Screen Shot 2019-08-08 at 10 44 25 AM" src="https://user-images.githubusercontent.com/6265975/62725606-527d8180-b9ca-11e9-81f0-db7167774f81.png">

Additionally, trying to resolve the conflicts looks like this:
<img width="1448" alt="Screen Shot 2019-08-08 at 10 46 11 AM" src="https://user-images.githubusercontent.com/6265975/62725635-61643400-b9ca-11e9-9f74-526e58b82efa.png">

However, the "convert to blocks" button does nothing.

I think the ideal solution would be to disable page/post editing/creation with the classic editor in wp admin if FSE is active on the site.

**Comment by vindl** [comment]
> I think the ideal solution would be to disable page/post editing/creation with the classic editor in wp admin if FSE is active on the site.

I agree, let's proceed with that solution if possible.

**Comment by noahtallen** [comment]
This isn't possible on vanila wordpress, just on wpcom

**Comment by noahtallen** [comment]
done in D31361-code

**Comment by noahtallen** [comment]
I think I'll also extend this to cover the endpoint mentioned in D27724-code once Matt's diff is merged.
