### ISSUE TITLE
Jetpack checklist: improve mobile experience

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#32835]
Interacting with the checklist on mobile is a bit rough:

320px wide, ui broken, narrow space for text:

<img width="320" alt="Screenshot 2019-05-06 at 20 05 29" src="https://user-images.githubusercontent.com/87168/57242133-60261280-703b-11e9-9411-36db73cfdde1.png">

378px wide, ui broken:

<img width="378" alt="Screenshot 2019-05-06 at 20 05 51" src="https://user-images.githubusercontent.com/87168/57242159-7502a600-703b-11e9-9f02-45dc4d11d94c.png">

The checklist is way under the fold. Above the fold, there's a huge image (of a _computer..._ on my mobile screen 😀):

<img width="374" alt="Screenshot 2019-05-06 at 20 06 15" src="https://user-images.githubusercontent.com/87168/57242168-8055d180-703b-11e9-9491-70ed32c77ce4.png">

There's no easy way back to the checklist from settings — tour is hidden for non-desktop users:

<img width="377" alt="Screenshot 2019-05-06 at 20 11 29" src="https://user-images.githubusercontent.com/87168/57242197-96639200-703b-11e9-91d2-e941b675a2c1.png">

_"Choose which WordPress plugins you want to keep automatically updated."_ they said. Now what?

<img width="377" alt="image" src="https://user-images.githubusercontent.com/87168/57242501-52bd5800-703c-11e9-951c-b67bc20aa442.png">

Consider that in some languages text takes more space — we'll need to protect against flex-shrinking:

<img width="305" alt="Screenshot 2019-05-07 at 23 54 31" src="https://user-images.githubusercontent.com/87168/57332499-8921d280-7123-11e9-9770-796fb7ce7fe6.png">

cc @jeffgolenski

**Comment by simison** [comment]
For a comparison, wpcom checklist:

<img src="https://user-images.githubusercontent.com/87168/57622438-408c6e00-7596-11e9-9cc9-6105338059be.png" alt="" width="320" />

<img src="https://user-images.githubusercontent.com/87168/57622410-34081580-7596-11e9-82d0-347f4a3ddf1c.png" alt="" width="320" />

**Comment by jeffgolenski** [comment]
@simison I really appreciate how thorough you are. 

I'm only going to quickly address a few quick changes we can make for a better mobile experience.

1) Drop the task actions to a separate line under 400px (or a similar pre-existing breakpoint)

![Screen Shot 2019-05-13 at 2 59 41 PM](https://user-images.githubusercontent.com/214813/57647125-30719000-7590-11e9-8c8e-d0ecc5e6d019.png)

This way the length of the content becomes less of a factor that breaks the cleanliness of the UI on smaller devices. Changing those parent elements from `display: flex;` to `display: block;` should be all we need, along with some `text-align: left;` in there. 

2) Drop show / hide toggle below checklist progress bar on small screens 400px or similar breakpoint

Before: 
![Screen Shot 2019-05-13 at 3 05 12 PM](https://user-images.githubusercontent.com/214813/57647284-880ffb80-7590-11e9-8bf8-e060ee361700.png)

![Screen Shot 2019-05-13 at 3 05 37 PM](https://user-images.githubusercontent.com/214813/57647304-99590800-7590-11e9-9e5e-569dd8bda990.png)


After: 
![Screen Shot 2019-05-13 at 3 17 33 PM](https://user-images.githubusercontent.com/214813/57647939-43855f80-7592-11e9-9fa0-a5aaf056d06c.png)
![Screen Shot 2019-05-13 at 3 16 11 PM](https://user-images.githubusercontent.com/214813/57647945-48e2aa00-7592-11e9-8746-941b366e28dd.png)


The guided tour issues you mention, I think are a larger issue shared by both platforms. We should raise those issues with the folks who built / build that stuff, I think.

**Comment by fditrapani** [comment]
> The guided tour issues you mention, I think are a larger issue shared by both platforms. We should raise those issues with the folks who built / build that stuff, I think.

There are no teams currently maintaining this so we'll either need to make fixes where necessary or work around the limitations.

**Comment by jeffgolenski** [comment]
> There are no teams currently maintaining this so we'll either need to make fixes where necessary or work around the limitations.

Bummer. :-(

**Comment by fditrapani** [comment]
An alternative to the tours is to use a modal. You can see it in action by checkout out Shaun's latest post for onboarding.
