### ISSUE TITLE
Customizer: Broken Background Pattern Images

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#32843]
#### Steps to reproduce
1. Access the Customizer.
2. Click on Colors & Backgrounds.
3. Navigate through the images under "Pick a Background Pattern". 

#### What I expected
To see all the available images.

#### What happened instead
Most of them don't load. It happens for the user (omundogiraalusitanaroda.home.blog) and on my test site (mytestsite.live), we are using the Floral and Aquene themes.

#### Browser / OS version
Chrome/73.0.3683.103
OS X 10.13.6

#### Screenshot / Video
![Screen Shot 2019-05-06 at 18 22 08](https://user-images.githubusercontent.com/16104522/57256751-df144e80-702d-11e9-98c6-b355fc00fafa.png)

Some images that aren't showing:
https://i0.wp.com/colourlovers.com.s3.amazonaws.com/images/patterns/5456/5456885.png
https://i0.wp.com/colourlovers.com.s3.amazonaws.com/images/patterns/5454/5454302.png
https://i1.wp.com/colourlovers.com.s3.amazonaws.com/images/patterns/5457/5457842.png

They all show `"We cannot complete this request, remote data could not be fetched"`.

#### Context / Source
#user-report 
2012619-zen

**Comment by rachelwinspear** [comment]
Another report: #2015911-zen
Theme: Sela
User is unable to see the **Pick a Background Pattern**, as shown above.

Some missing images: 
https://i2.wp.com/colourlovers.com.s3.amazonaws.com/images/patterns/947/947821.png
https://i1.wp.com/colourlovers.com.s3.amazonaws.com/images/patterns/946/946185.png
https://i0.wp.com/colourlovers.com.s3.amazonaws.com/images/patterns/985/985516.png

**Comment by supernovia** [comment]
I just noticed this personally when setting up a new work P2

**Comment by eduardozulian** [comment]
Another WordPress.com report: 13611168-hc. 

I was able to reproduce it as well.

**Comment by ezebecke** [comment]
Another report: #13748238-hc

I couldn't replicate the issue, but the user tried several browsers and two different networks. 

![image](https://ezebecke4test.blog/wp-content/uploads/2019/07/broken-pattern.png)

**Comment by lancewillett** [comment]
Thanks for this report. Currently investigating a fix.

**Comment by lancewillett** [comment]
Background patterns should load correctly now in Customizer.

Please let me know if you see any issues, both in Customizer, saving the image — and loading it on the front-end of the site.
