### ISSUE TITLE
Gutenberg: Embeds: SoundCloud embed - consistency issue

### ISSUE THREAD

**Issue by blazevivan** [Automattic/wp-calypso#32856]
#### Steps to reproduce
1. Create a new post
2. Paste the link https://soundcloud.com/ivancancialosi/ivan-cancialosi-image
3. Publish the post

#### What I expected
I expected when I paste the link that SoundCloud track will be embedded in the post.
It is not working on my site, nor user's site. It worked from wp-admin and it worked on another site here during the testing: https://cld.wthms.co/c5LTBS
It looks like the issue might be with this account/track in particular, but it's strange that it works on one site and not on another 2 sites on a different account. During testing, this was not working on one site that is on Free another one on Premium plan, and user's site was on Personal - none of these were able to embed it.

#### What happened instead
It gives an error as you can see here: https://cld.wthms.co/MZGFCO

#### Browser / OS version
Chrome 74.0, Mac 10.14.4

**Comment by blazevivan** [comment]
Not sure if this Mixcloud issue is related, but linking it here as some testing was done and it might help. 

https://happinessfeedback.wordpress.com/2019/04/20/mixcloud-player-not-displaying-for-some-visitors/

**Comment by mdrovdahl** [comment]
I'm consistently able to reproduce this issue on a wp.com simple site:

Steps:
1. Create new post or page
2. Add SoundCloud block
3. Paste valid SoundCloud URL (I've been testing with https://soundcloud.com/mdrovdahl/45-minutes-of-silence)
4. Click "Embed"
5. Receive "Sorry, this content could not be embedded." error...and yet(!) if I "Publish" and view the published page, it has indeed embedded.

I was also able to replicate this a few times, on Jetpack connected sites (hosted on Pressable).

I was NOT able to replicate this on a vanilla (not-wp.com) WP site w/out JP.

**Comment by gwwar** [comment]
This embeds pretty consistently for me across multiple plan types, though the box sizing needs to be fixed. Let's see if we get more reports and tidy the following visual defect:

<img width="768" alt="Screen Shot 2019-10-28 at 5 12 09 PM" src="https://user-images.githubusercontent.com/1270189/67727304-29a3d180-f9a6-11e9-9d1d-334ca2910d1e.png">

**Comment by bsanevans** [comment]
Another case reported here: 17753789-hc 2616992-zen

The embed throws an error in the editor of the Simple plan, but shows fine in the Preview and on the published page.

![soundcloud-embed-in-editor](https://user-images.githubusercontent.com/49054298/72054639-bbb44880-330c-11ea-93bb-4296cccce3bb.png)

![soundcloud-embed-in-preview](https://user-images.githubusercontent.com/49054298/72054664-c5d64700-330c-11ea-9cd7-ac2141d2fc4b.png)

**Comment by joweber123** [comment]
Another report here - 2704222-zen

I am able to reproduce the same effect that @bsanevans has mentioned above on a simple site.   I am receiving an error in the editor but in the preview and on the actual published page the embed is working normally.

**Comment by joweber123** [comment]
Another report here 2704222-zen

I am able to reproduce the same issue as @bsanevans has mentioned above on a simple site.  The embed is displaying an error in the editor but in the preview of the post and in the actual published post the embed is working normally.

**Comment by kathrynwp** [comment]
Also reported by a user in 2748641-zen on a Simple site with a Personal plan. Asked the user to go ahead and publish the post even with the error in the SoundCloud block

**Comment by cuemarie** [comment]
👋 Hey folks! Since this issue has been inactive for quite some time, KitKat has made the decision to close it. 

- Internal reference, for more on this decision: pdqkMK-14B-p2

If you think this issue warrants another look, here are some next steps!

1. Report anew: A new report with more current details and steps to replicate may be the best way to renew attention on this issue.  Feel free to refer back to this closed issue in your report!
2. Reopen: If you feel the issue still matches the context/history here, you can also reopen the issue and add fresh logs, screenshots and steps to reproduce. 

Thanks for your involvement!

📌 ADDITIONAL NOTES
A much more recent report on this https://github.com/Automattic/wp-calypso/issues/78943 was closed as not reproducible.
