### ISSUE TITLE
Checklist task: Add rel attribute to external href tasks

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#32853]
External links with `target="_blank"` should include an appropriate `rel` attribute.

https://developers.google.com/web/tools/lighthouse/audits/noopener#recommendations

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/32839/review_comment/create_

**Comment by ockham** [comment]
The `target` prop [trickles down](https://github.com/Automattic/wp-calypso/blob/5d30badc44b3e794c71afa88f20138353458a1c9/client/components/checklist/task.js#L154) to the `Button` component, which [takes care of that](https://github.com/Automattic/wp-calypso/blob/5d30badc44b3e794c71afa88f20138353458a1c9/client/components/button/index.jsx#L38-L41) for us.
