### ISSUE TITLE
Theme Showcase: "View Plans" Callout Button Not Working

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/wp-calypso#32867]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/veni (or any premium theme)
2. Click on the "View plans" callout button.

#### What I expected

When I click on the link, I should be taken to the plans page.

#### What happened instead

Clicking the link doesn't take me anywhere.

#### Browser / OS version

MacOS + Chrome.

#### Screenshot / Video

![Screen Shot 2019-05-07 at 2 24 14 PM](https://user-images.githubusercontent.com/1473618/57323822-7e8c1c80-70d4-11e9-81eb-1d95e3db3bbf.png)

**Comment by alaczek** [comment]
The button seems to be working for me on simple sites with free and personal plan. Are there any other specific circumstances/conditions you can think of that would trigger this? Was it a Jetpack site maybe?

**Comment by torres126** [comment]
@alaczek you need to be in a state without a selected site (eg. viewing the theme directly), #32873 should solve this
