### ISSUE TITLE
Signup: Email verification does not support `+` character.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32862]
While a user can sign up for a WordPress.com account with an email including a `+` character (`tom+wp@gmail.com`), the verification email will never be sent to the user. The user will continue to get prompts to verify their email, but will not receive the email, no matter how many times the email is "resent".

I discovered this by signing up for a business account; I never got the verification email, but _did_ get my receipt for the business plan to the same email address.

Note that this is _not_ the case with "ordinary" emails (`tom@gmail.com`).

**Comment by lancewillett** [comment]
I don't think this is accurate. I've been testing signup for months with a Gmail and + alias. The verification email comes through each time.

Closing (but feel free to re-open if someone else can repeat it).

**Comment by kwight** [comment]
Tried again today, no problems at all ¯\_(ツ)_/¯
