### ISSUE TITLE
Gallery block image display issue on older iPad / iOS models

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#32864]
Images using the Gallery block don't display correctly on older iPads / iOS. Doesn't appear to be theme related as I have tested 5 different themes and they all have the same result.

#### Steps to reproduce
1. Add an image block to a page, add multiple images
2. View published page on older model iPad
#### What I expected

Images should display correctly in the grid

#### What happened instead

The images stack on top of each other and the surrounding text.

#### Browser / OS version

I am testing in Safari on an iPad with iOS 9.35. which is the latest available for this device.

#### Screenshot / Video

![img](https://cld.wthms.co/Ne0wMY+)

#### Context / Source

Reported in #8024078-hc

**Comment by simison** [comment]
Does this happen in core Gutenberg as well (and not just on wpcom)? If so, you should open the issue there: https://github.com/WordPress/gutenberg

**Comment by mikeicode** [comment]
@simison I tested and yes the same issue exists on core, I reported the issue there now (not sure if this issue should be closed now):

https://github.com/WordPress/gutenberg/issues/15488

**Comment by simison** [comment]
Yeah, if it's a core problem this can be closed. Thanks for testing it!
