### ISSUE TITLE
Remove the checklist checkbox interaction

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#32888]
_The green tick icon_ should appear if a task **is complete**.

_The hollow, grey ring_ should display if a task is **not complete**.

<img width="415" alt="Screen Shot 2019-05-07 at 9 34 11 am" src="https://user-images.githubusercontent.com/6458278/57347225-e144ed00-7194-11e9-885c-8a8ba567cd10.png">

The icon in any state should not be clickable, and should not trigger any action.

> We should remove the functionality, for two reasons:
>
> 1. Its not-obvious and essentially hidden.
> 2. Once you mark a task done, there's no way to undo it. If you click it accidentally, or out of curiosity, you basically lose that task.

See comments on https://github.com/Automattic/wp-calypso/pull/32679#issuecomment-489642508

**Comment by ramonjd** [comment]
Thanks for chiming in, @arunsathiya 

You can lay the blame on my extrapolation of @shaunandrews 's comments. :)

I created this issue to track idea and whether we want or need to do it.

I'll update as we get clarification.

**Comment by spen** [comment]
There has been some informal talk about making efforts toward a proper 'skipped' state for tasks... That way we can differentiate between _actually done_ and _skipped_ and avoid showing false messaging like 'You added a Site Title' when that person actually just skipped the task, plus a few other benefits.

**Comment by shaunandrews** [comment]
> what's the best way to dismiss unwanted tasks?

I think we'll add a skip option to tasks at some point to address this:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/191598/57869212-8c2b5b80-77d2-11e9-831d-97b1711ccfb5.png">

**Comment by ramonjd** [comment]
Closing for now. I think we should address this as the new designs/UX specs come in
