### ISSUE TITLE
Ecommerce Plan: Creating store on eCommerce plan takes user to Mailchimp API key setup page (existing user only)

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#32884]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/new?ref=calypso-selector
2. Create a new WordPress.com site
3. Select eCommerce Plan
4. Click on "Create your store"
5. Land on Mailchimp API key page

#### What I expected
To land on the store setup screen, as on this screenshot: https://cld.wthms.co/zudMgg

`wp-admin/admin.php?page=wc-setup`

#### What happened instead
Landed on Mailchimp API key page, as on this screenshot: https://cld.wthms.co/w2RbNE

#### Browser / OS version
Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

#### Context / Source
#manual-testing

**Comment by lancewillett** [comment]
I'm noting the URL `https://wordpress.com/jetpack/new?ref=calypso-selector` — @davipontesblog could you share how you got there? 

Just checking the entry point as a user would encounter the buttons or page they landed on.

**Comment by davipontesblog** [comment]
> I'm noting the URL `https://wordpress.com/jetpack/new?ref=calypso-selector` — @davipontesblog could you share how you got there?
> 
> Just checking the entry point as a user would encounter the buttons or page they landed on.

Thanks for the question @lancewillett  - this is where you land when you are on WordPress.com and click on left top corner "Switch Site", and then "Add New Site". The screenshot below shows the button and the link URL for the destination from there.

Screenshot:

![Screen Shot 2019-05-08 at 14 25 53](https://user-images.githubusercontent.com/31009008/57398658-8cf23b00-719d-11e9-9d96-aaa62adcb5c1.png)

**Comment by zdenys** [comment]
Encountered the same behavior myself.

![](https://cld.wthms.co/iirrlF+)

**Comment by mattsherman** [comment]
Note: This only happens when going through "Add New Site" flow for existing user. Going through a new *user* flow does not exhibit this behavior.

**Comment by mattsherman** [comment]
Note: The user is not required to enter their Mailchimp API key. They can click on any other item in the sidebar to navigate away from this and continue setting up their store.

/cc @michaeldcain (this answers your question from during our chat earlier)

**Comment by creativecoder** [comment]
A fix for this has merged. I'm working on getting it deployed.

**Comment by creativecoder** [comment]
Fix is now live for new eCommerce sites.

**Comment by timmyc** [comment]
I upgraded a business plan site to the ecommerce plan, and was redirected to the MailChimp settings page instead of the setup checklist, so it seems this bug is still present. As such, I'm going to re-open.

**Comment by timmyc** [comment]
@jonathansadowski and @creativecoder I dropped this in a new project board for our HACK week sprint next week. I'm going to clear out you both as assignees too, but please feel free to join in on the ecomm plan HACK week fun if you would like.

**Comment by creativecoder** [comment]
Thanks @timmyc ! We already have some other plans for HACK week, but I'd be happy to help review any work you do on this issue, just let me know.
