### ISSUE TITLE
Search block not working

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#32891]
#### Steps to reproduce
1. Create a page or a post.
2. Add a search block
3. Try to customize it. Check the front end - it won't be there.
4. Refresh the editor, the changes you previously did won't be there either.

#### What I expected

To have the search block rendered and customized.

#### What happened instead

None of the above expected.

#### Browser / OS version

Tested in Chrome/Edge, so Windows and MacOS so it's not OS related.

#### Context / Source
#user-report

Chat: #11776947-hc
Ticket:  #2016094-zen
We had this reported by a WordPress.com user and I tested this on a self-hosted site. The problem is only present on WordPress.com

**Comment by obenland** [comment]
I'm unable to reproduce this on wpcalypso.wordpress.com. Do you think you could add a screencast here that shows the url bar and the steps to reproduce it?

**Comment by kwight** [comment]
I'm able to reproduce this in Gutenframe for simple sites, on both production and `wpcalypso`, as well as `wp-admin`. I'd agree this is a WP.com issue, but not related to the Jetpack iframing launch of yesterday.

**Comment by mmtr** [comment]
Didn't investigate this yet, but my first hypothesis is that maybe the restricted `wp_kses` we have on Simple Sites is filtering the HTML output produced by the block.

For reference, this is how the block renders the markup (it's a server-side rendered block): https://github.com/WordPress/gutenberg/blob/efbbebd44c94e5a910d2671a97ea9a54a290c37f/packages/block-library/src/search/index.php#L15-L57

**Comment by gwwar** [comment]
Please re-open if folks are still running into this. I wasn't able to reproduce on a Simple Site. I verified editing in the iframe, wp-admin, and that the published component does search for results
