### ISSUE TITLE
Video upload isn't working like expected

### ISSUE THREAD

**Issue by marecar3** [Automattic/wp-calypso#32910]
**Describe the bug**

1. When I try to upload an mp4 video using Premium account, It's with success in 30% of attempts and in a case of failure, I am getting random errors :

- Stuck on "converting 99% "
- Stuck on "Loading..."
- Stuck on "Conversion error"
- Stuck on "converting 52%" 

2. When it's a success I can't preview uploaded video

**To reproduce**
1. Download video from https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
2. Create a new Gutenberg (Block Editor) Post
3. Add video block
4. Select Upload and pick a downloaded video from step 1.

**Expected behavior**
Sometimes it's stuck with uploading, sometimes it's working

**Screenshots**

<img width="710" alt="Screen Shot 2019-05-08 at 1 34 45 PM" src="https://user-images.githubusercontent.com/28219092/57396044-7f39b700-7197-11e9-99ac-7d92996cfc1e.png">

<img width="1114" alt="Screen Shot 2019-05-08 at 11 10 02 AM" src="https://user-images.githubusercontent.com/28219092/57396069-9082c380-7197-11e9-9257-66434b4b8607.png">

**Desktop (please complete the following information):**
 - OS **Mac OS Mojave : 10.14.3**
 - Browser **Chrome**
 - Version **73.0.3683.86 (Official Build) (64-bit)**

**Comment by cecoates** [comment]
I had a similar issue today.

#14530001-hc

This error was a bit less helpful, "unknown error".

That error shows when using the video block AND in the media library.

The video itself seems fine, and if you copy the video URL into a paragraph block it embeds as expected.

![Screen Shot on 2019-08-16 at 13_32_15](https://user-images.githubusercontent.com/10121835/63191685-bdfcca00-c02e-11e9-94ff-0625a46c9857.png)

**Comment by nagpai** [comment]
Noticed this on #14691764-hc

**Comment by kwight** [comment]
This seems to be caused by some sort of polling to `https://io.videopress.com/socket.io/?guid=<guid>&...` that never resolves; they just continue endlessly (which presumably means that some UI check never completes, leaving the preview in an unresolved state).

The VideoPress preview is also an iframe within an iframe within the Video block; that can't be good.

<img width="450" alt="Screen Shot 2019-10-11 at 3 35 04 PM" src="https://user-images.githubusercontent.com/349751/66688745-b7f52500-ec3c-11e9-95ea-46c47ae0f220.png">

**Comment by mmtr** [comment]
I noted an interesting pattern. Every time the previews gets stuck in the loading state, requests to `https://public-api.wordpress.com/rest/v1/videos/<guid>?http_envelope=1` return valueless `width`/`height`: 

<img width="1183" alt="Screen Shot 2019-10-15 at 11 30 09" src="https://user-images.githubusercontent.com/1233880/66819407-37d20680-ef3f-11e9-82a4-a1ec7aaff99f.png">

However, working previews get proper values:

<img width="1144" alt="Screen Shot 2019-10-15 at 11 31 14" src="https://user-images.githubusercontent.com/1233880/66819479-589a5c00-ef3f-11e9-970c-da52a7c598aa.png">

I think this is related to some kind of race condition and it's depending on the speed of the transcoder job (sometimes data is retrieved when the transcoder already set the dimensions, sometimes it is retrieved too early).

**Comment by mmtr** [comment]
Just confirmed the issue is coming from the VideoPress JS library. The player gets stuck because it is not refetching the data when the video is processing, although it should do it according to https://github.com/Automattic/videopress/blob/ff199f65feff54db19799005237b11687e3b9385/lib/watch.js#L28. Will keep investigating.

**Comment by mmtr** [comment]
It ended up being a problem of the `video-wp-com` theme in WP.com. That theme is setting a custom request provider that is executed only once because it is hooked into the `window`'s `load` event. I'm preparing a diff refactoring that function to see if that solves this issue.

**Comment by mmtr** [comment]
Fix undergoing in D34084-code.

**Comment by kwight** [comment]
The first part of this bug is now fixed by @mmtr in D34084-code: uploads complete predictably and consistently 🎉

> When it's a success I can't preview uploaded video

This part remains; I'm closing this issue and we'll use https://github.com/Automattic/wp-calypso/issues/36836 to track the inactive UI.
