### ISSUE TITLE
Plan buttons on homepage misaligned 

### ISSUE THREAD

**Issue by nodeone** [Automattic/wp-calypso#32914]
#### Steps to reproduce
1. Starting at URL: wordpress.com (incognito mode, logged out of wp-com)

#### What I expected
The buttons for the plans to be bottom-aligned, and evenly aligned together. 

#### What happened instead
The buttons are flowing vertically according to their container content, and are not aligned to the bottom of their containers, and with each other. 

#### Browser / OS version
Mac OS Mojave, Chrome Version 74.0.3729.131

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/49699157/57411319-055afb00-71a2-11e9-8edb-4c8a7a5d9306.png)

#### Context / Source
Found by dogfooding/testing onboarding in incognito: #dogfooding, #manual-testing #onboarding

**Comment by donpark** [comment]
I think this page is one of the many and often changing WPCOM marketing pages, not something rendered by Calypso, meaning any fix won't stay fixed until whoever creates and edit them needs to add Incognito Mode to the testing process.

**Comment by danhauk** [comment]
I'm not sure if I'm in a different test bucket or not, and it looks like this for me in all browsers. If the new design below is live for everyone it looks to not be an issue anymore.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/448298/57795585-57f16580-7714-11e9-8f49-c52b36bcb4f8.png">

**Comment by nodeone** [comment]
I see it as fixed, too. Yeah, I was thinking this was the place to put all of the bottle pickups, but maybe that doesn't make sense for non-calypso things...
