### ISSUE TITLE
Jetpack thank you header: Ensure no widows

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#32919]
The line break here leaves a widow under the plan icon at some widths. Would be nice to keep the text properly aligned:

![Screen Shot 2019-05-07 at 11 24 30](https://user-images.githubusercontent.com/841763/57289035-ec2b4f00-70ba-11e9-9a8b-7368609eb332.png)

From https://github.com/Automattic/wp-calypso/pull/32758#pullrequestreview-234365094

cc: @jeffgolenski

**Comment by Aurorum** [comment]
I think #35511 dealt with this
