### ISSUE TITLE
Block Editor: Reusable blocks are not available.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32913]
The Add to Reusable Blocks menu item has disappeared from the block ellipsis menu. This applies to simple sites, in both Gutenframe and `wp-admin` itself:

![reusable](https://user-images.githubusercontent.com/349751/57407272-a2fcfd00-7197-11e9-8ee8-ff051f8e8dd1.png)

The Add Block section is still there, and the Manage... item is still available from the top right ellipsis menu.

Initially reported by @otpidusprime in p7DVsv-6sB-p2.

**Comment by david-binda** [comment]
This was not related to Calypso, but rather to some WPCOM quirks and should be fixed as of now.

I dare to close this out, but feel free to reopen if my action is not appropriate.
