### ISSUE TITLE
Setup guide checklist completion under the "Stats"

### ISSUE THREAD

**Issue by pranali333** [Automattic/wp-calypso#32930]
Hi there,

I came across a user who was not satisfied with the user experience of the setup guide we provide to newly created websites under the My Sites > Stats.

Happychat: 10469567-hc

**Problem:**
The user was prompted to complete the task from the checklist even if it is done.
I checked her website and I was able to replicate the issue.
The task was to – “Upload a site icon”. The icon was already uploaded. I also get them uploaded new one while chatting and the stats were still showing it is incomplete.

**Further troubleshooting:**
I tried to regenerate the issue at my end. In one of my website, I managed to regenerate the issue. I am stuck at the step to create a contact page.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/
2. Check for the site with incomplete steps for the checklist guide.
3. Go through them one by one and do it to complete it.
4. The stats should get updated as and when you complete the steps.

#### What I expected
The Stats To-Do meter should get automatically updated as and when you complete the steps.

#### What happened instead
The Stats To-Do meter prompts to complete the task from the checklist even if it is done.

#### Browser / OS version
Chrome/ Mac (10.14.4)

#### Screenshot / Video
<img width="942" alt="contact-form-incomplete" src="https://user-images.githubusercontent.com/7771963/57466891-1a698400-729f-11e9-8c9e-158d5f3f726e.png">

Site : atsite1pranaliwp.blog
Theme: 2019
Here you can find the contact page here – [https://atsite1pranaliwp.blog/contact/](https://atsite1pranaliwp.blog/contact/)

**Current hack:**

Fortunately, we do have a sort of hack to fix this for now while it gets fixed to reflect under the website “Stats”.
We can complete the task manually from the checklist page. We need to click on the green checkmark to complete the task manually then only it can reflect on the % chart.

<img width="653" alt="checklist-page" src="https://user-images.githubusercontent.com/7771963/57467340-f8243600-729f-11e9-994b-3b0ede88cf42.png">

Thanks!

**Comment by adamziel** [comment]
That's working as expected in the new checklist
