### ISSUE TITLE
Gutenframe: Audit popular plugins for blacklist.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32934]
Some plugins (such as page builders) may result in confusing, broken, or unintended flows by being iframed with Gutenframe. #32915 adds the capability to blacklist plugins by slug; let's do an audit of the most popular plugins on Atomic sites and see if anything else needs to be added to that blacklist before attempting another launch of Gutenframe for Jetpack sites.

**Comment by mmtr** [comment]
I checked the most popular plugins in Jetpack sites (see p1557449462040900-slack-lannister for instructions on how to get that list) and focused on the ones activate on more than 400 sites.

These are the page builders I found that add buttons and links that could cause a conflicted flow while iframed and/or Calypsoified:

- [**WPBakery Page Builder**](https://wpbakery.com/) (`js_composer`).
- [**Page Builder by SiteOrigin**](https://siteorigin.com/page-builder/) (`siteorigin-panels`).
- [**Divi Builder**](https://www.elegantthemes.com/plugins/divi-builder/) (`divi-builder`).
- [**Beaver Builder Plugin (Lite Version)**](https://wordpress.org/plugins/beaver-builder-lite-version/) (`beaver-builder-lite-version`).
- [**Fusion Builder**](https://theme-fusion.com/products/fusion-builder/) (`fusion-builder`).
- [**Thrive Architect**](https://thrivethemes.com/architect/) (`thrive-visual-editor`).
- [**Visual Composer Website Builder**](https://visualcomposer.com) (`visualcomposer`).

I already included them in the blacklist added on #32915.

**Comment by codebykat** [comment]
I'm not sure exactly what we're looking for, but here's a list of [plugins tagged "page-builder" in the plugin repo](https://wordpress.org/plugins/tags/page-builder) that appear in our AT list:

[Unyson](https://wordpress.org/plugins/unyson/) (`unyson` -- 451 installs)
[Brizy](https://wordpress.org/plugins/brizy/) (`brizy` -- 325)
[Live Composer Page Builder](https://wordpress.org/plugins/live-composer-page-builder/) (`live-composer-page-builder` -- 181)
[Landing Page – Lead Page – Optin Page – Squeeze Page – Responsive Landing Page Builder](https://wordpress.org/plugins/page-builder-add/) [`page-builder-add` -- 160)
[Kadence Blocks](https://wordpress.org/plugins/kadence-blocks/) (`kadence-blocks` -- 140)
[Themify Builder](https://wordpress.org/plugins/themify-builder/) (`themify-builder` -- 105)

Of these, it looks like Kadence may be the only one that adds anything to the block editor. But that's only from skimming their videos.

**Comment by codebykat** [comment]
Over 50 but under 100 we've also got

[Bold Page Builder](https://wordpress.org/plugins/bold-page-builder/) (`bold-page-builder` -- 79 installs)
[Nimble Page Builder](https://wordpress.org/plugins/nimble-builder/) (`nimble-builder` -- 73)
[WordPress Page Builder by MotoPress](https://wordpress.org/plugins/motopress-content-editor-lite/) (`motopress-content-editor-lite` -- 62)

Bold seems to extend the existing editor; the other two look like they don't.
