### ISSUE TITLE
Flickr video embed

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#32937]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/pages/
2. Create a new page using either the block editor or the classic calypso editor.
3. Try to embed a video from Flickr the one we use on our support page is https://www.flickr.com/photos/chaddles/2402990826
4. Use either the shortcode or just the URL

#### What I expected

For the video to show up and be able to play.

#### What happened instead

With the shortcode nothing appears in the test post. If you use the straight url you get the preview but with an overlay that says No video with supported format and MIME type found. and the video can not be played

#### Screenshot / Video

![Screen Shot 2019-05-09 at 4 45 22 PM](https://user-images.githubusercontent.com/1326294/57482015-ecbe1400-7279-11e9-8664-998020081198.png)

#### Context / Source
#user-report 

1987529-zd

**Comment by lancewillett** [comment]
Thanks for the bug report. This probably isn't related to Calypso; rather the underlying WP.com code that supports embeds.

See related Trac ticket: 8115-wpcom
