### ISSUE TITLE
Store: Default currency is wrong for Canada.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32948]
When starting a WooCommerce store, Calypso correctly identified my address automatically somehow (which I accepted), but then made my default currency British pounds, instead of CAD.

<img width="793" alt="Screen Shot 2019-05-10 at 7 39 46 AM" src="https://user-images.githubusercontent.com/349751/57535635-76f88d80-72f7-11e9-8e77-f797f2beb61d.png">

I found the currency under Settings, and updated it. When I went back to change the currency of my existing product, the currency was already updated however, which was nice. But it also made me wonder why I couldn't update it from the product itself, by clicking the currency icon (which was my first instinct to fix it before).

<img width="261" alt="Screen Shot 2019-05-10 at 7 42 21 AM" src="https://user-images.githubusercontent.com/349751/57535820-cb9c0880-72f7-11e9-8072-8aa8c49512a7.png">

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
