### ISSUE TITLE
Full Site Editing: create a simple navigation block [13]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32946]
Build a simplified navigation block (scoping/design work needed). See related core proposal and issue. A first iteration might be a Menu “magically” created without editing controls.

While working on this we should be aware of ongoing core work around the menu block and widget areas.

Core references:

- https://github.com/WordPress/gutenberg/issues/13690
- https://github.com/WordPress/gutenberg/pull/14812
- https://make.wordpress.org/design/2019/02/26/proposal-navigation-menu-block/

**Comment by apeatling** [comment]
I'd encourage you to make this a simple server side rendered preview of navigation for the first iteration. Our new users are not going to have complex menus. By the time they do we will either use the core block, or have iterated on this further.

**Comment by apeatling** [comment]
This looks like it will be addressed in https://github.com/Automattic/wp-calypso/issues/33109

**Comment by apeatling** [comment]
This one is done.
