### ISSUE TITLE
Full Site Editing: switch MVP sites to a new theme [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32942]
Depending on the research conducted in https://github.com/Automattic/wp-calypso/issues/32824 the particular steps of this task may vary (details to be added after the investigation is complete).

We'll probably want to switch all of the MVP sites to a new "blank" theme during the data migration process, or to a plain 2019 theme if possible.

**Comment by apeatling** [comment]
No longer relevant, closing.
