### ISSUE TITLE
HeaderButton: Update the design to put icon and text side-by-side.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#32949]
[headerButton](https://wpcalypso.wordpress.com/devdocs/design/header-button) is a relatively new and less used component, and it has a unique design. It stacks vertically the icon and the text. Because of it, the icon gets small, and overall it looks less like a button. We can see instances in /themes and /plugins.

<img width="154" alt="Screen Shot 2019-05-10 at 15 43 44" src="https://user-images.githubusercontent.com/908665/57535582-703f3a00-733a-11e9-87a2-29dc97d4712f.png">

I assume the design intended to save horizontal space, but it's probably better to make the icon and the text side-by-side to make it more like a button/link.

<img width="171" alt="Screen Shot 2019-05-10 at 15 31 27" src="https://user-images.githubusercontent.com/908665/57534816-cb702d00-7338-11e9-92de-7c421eb3c0f7.png">

To add more context, in issue #32531, the consensus was to change the missing text cart button to `headerButton`, but the small cart icon doesn't work well with the count. We could take the route that customises `headerButton` for the cart button, but as suggested in the issue, it's probably better to change the component to put the icon and the text side-by-side. to add more clarity.

**Comment by ctoynbee** [comment]
@iamgabrielma does this layout look ok to you?

https://www.dropbox.com/s/emhx2jkk4o9sj1g/Screenshot%202019-05-14%2012.10.02.png?dl=0

Let me know if you need to change the alignment of the icon and text.

Thanks.

**Comment by alaczek** [comment]
If we make this change, we should also probably update devdocs.
