### ISSUE TITLE
Full Site Editing: remove Twenty Nineteen fork [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#32943]
This is a follow-up task to https://github.com/Automattic/wp-calypso/issues/32824 and https://github.com/Automattic/wp-calypso/issues/32942. After we complete the investigation in the previous tasks we might decide that it's not required, or add more details here.

The goal of it is to clean up the Twenty Nineteen fork that removed global theme options.

**Comment by apeatling** [comment]
No longer relevant, closing.
