### ISSUE TITLE
Gutenframe: Admin notices are hidden by an active top toolbar.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#32958]
If a user enables the Top Toolbar from the block editor's ellipsis menu, any admin notices will be hidden behind it due to misalignment.

<img width="1108" alt="Screen Shot 2019-05-10 at 7 59 17 AM" src="https://user-images.githubusercontent.com/349751/57544860-78cd4b80-730d-11e9-9b34-85cb15830fae.png">

**Comment by mmtr** [comment]
Note that to reproduce this, the viewport needs a width no greater than 782px.

![May-11-2019 14-09-12](https://user-images.githubusercontent.com/1233880/57565310-7a267300-73f6-11e9-98c4-95e2351797e5.gif)
