### ISSUE TITLE
Editor: front end name @ mentions do not work with P2 themed websites

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#32952]
History and #user-report come from this WordPress.com forum thread: 
https://en.forums.wordpress.com/topic/p2-mentions-and-email-notifications-not-working/#post-3308408

The user has posted a screen share video demonstrating the issue: 
https://youtu.be/wpNuoYD5U-4

#### Steps to Reproduce
Outlined in video

#### What I expected
The at mention function on the front end should populate a list of username options as it does when working from the back end of the site. 

#### What happened instead
There are no prompted usernames when adding an at mention from the front end of the site.

#### Browser / OS version
I will update with OS type and version number. 
Chrome and Firefox used with out any extensions. 

Updated details: 
Operating System: Ubuntu 18.04 bionic (x86-64)
Desktop: Cinnamon v4.0.9
Chrome: v74.0.3729.131
Firefox: v66.0.4

#### Screenshot / Video
https://youtu.be/wpNuoYD5U-4

#### Context / Source
<!-- Optional: share your unique context to help us understand your perspective. You can add context tags such as: #journey #anecdote #narrative #context #empathy #perspective #reallife #dogfooding #livesharing #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

**Comment by lancewillett** [comment]
I'm not sure we'll fix this one, since P2 is a special theme that is intended to work on its own with its own front-end editor.

Let's keep it open for now, to gather other opinions and see if it's a requested feature from other users.
