### ISSUE TITLE
Gutenberg: Adding link on Paragraph block breaks the block on Safari

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#32965]
#### Steps to reproduce
1. Open your WordPress.com account on Safari.
2. Go to Site > Pages.
3. Create a new page.
4. Add a text using a Paragraph block.
5. Select part of the text and hyperlink it.

I was able to replicate the above on an AT and Simple site.

#### What I expected
The link to work.

#### What happened instead
It breaks the block.

#### Browser / OS version
Safari Version 12.1 (13607.1.40.1.5)
OS X 10.13.6

#### Screenshot / Video
![GutenIssue](https://user-images.githubusercontent.com/16104522/57554361-a1723700-7347-11e9-84d4-8d6806d99c32.gif)

This is what it shows in the Console:

![Screen Shot 2019-05-10 at 17 27 38](https://user-images.githubusercontent.com/16104522/57554898-0d08d400-7349-11e9-9beb-a1c4ce0e34dd.png)

#### Context / Source
#user-report 
2017169-zen

**Comment by gwwar** [comment]
Verified on Simple but not in Gutenberg nightly. 

It's more specifically breaking on `window.getSelection().getRangeAt(0)`
<img width="692" alt="Screen Shot 2019-05-10 at 1 49 09 PM" src="https://user-images.githubusercontent.com/1270189/57555924-75948880-732a-11e9-8beb-81ff1c1ef18c.png">

**Comment by gwwar** [comment]
Update: I can reproduce this in Gutenberg master with the following steps:

In Safari:
- Add a link to a paragraph
- Click on another paragraph
- Click directly on the link you added

![May-10-2019 14-49-33](https://user-images.githubusercontent.com/1270189/57558567-0b341600-7333-11e9-857f-c9d2f57c6d1b.gif)

**Comment by mmtr** [comment]
D28094-code has a temporary fix for WP.com sites while we wait for changes from https://github.com/WordPress/gutenberg/pull/15576

**Comment by mmtr** [comment]
Fixed by D28094-code.

**Comment by mmtr** [comment]
Created https://github.com/Automattic/wp-calypso/issues/33004 as a reminder to revert D28094-code during the next Gutenberg update in WP.com sites.
