### ISSUE TITLE
Tooltip is covering "add a custom address" and there is no way to dismiss it

### ISSUE THREAD

**Issue by eeeeevon13** [Automattic/wp-calypso#32967]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/gonzoandhenrietta.wordpress.com
2. As a first time user click to add a new site icon
3. Add an icon then return to the "general" settings tab.

#### What I expected
I expected to be able to close the tool tip. It hides the "site address" bar. I was trying to see what's underneath it.
This is also concerning because the call to action to but a custom domain is being obscured by the tool tip

#### What happened instead
I could not dismiss the tool bar and got frustrated

#### Browser / OS version
Mac, Chrome 

#### Screenshot / Video
https://drive.google.com/file/d/1qxsp-SfYKY03cfGBkKwPfU1Lc4kFwW1A/view

#### Suggestions
Allow me to dismiss the tooltip by clicking/tapping outside of it (anywhere on the screen)

**Comment by sixhours** [comment]
This tooltip appears when you've come from the checklist or clicked to change an item on the checklist. We'd need to look at the bigger picture for how the checklist interacts with its to-do items, since allowing people to close the tooltip might disrupt that checklist flow. It's part of a larger pattern we need to revisit.

**Comment by scalarbane2** [comment]
I can't seem to recreate this issue on my end. Could you help me with a full page screenshot?

**Comment by mmtr** [comment]
Seems that the checklist no longer includes a set site icon task after the improvements to the onboarding experience (paObgF-aE-p2, paObgF-1c-p2), so this is not reproducible anymore.
