### ISSUE TITLE
Tool tip arrow is pointing to the wrong button in settings

### ISSUE THREAD

**Issue by eeeeevon13** [Automattic/wp-calypso#32966]
#### Steps to reproduce
On mac, in Chrome as a first time visitor
1. https://wordpress.com/checklist(your site name).wordpress.com
2. Click "upload site icon"
3. The tool tip says "Good choice choose continue to use as your site icon" but the arrow is pointing to the cancel button

#### What I expected
I expected the arrow to point to the button that is referenced in the tooltip

#### What happened instead
The arrow is pointing to cancel. I worry skimmers will be confused

#### Browser / OS version
Mac, Chrome Version 74.0.3729.131 (Official Build) (64-bit)

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/87168/58041889-e82f1080-7b41-11e9-9be4-51531387fda6.png)

### Suggestions
- move the arrow to the right to sync up with the correct button

**Comment by arunsathiya** [comment]
Interestingly I am not seeing the same Calypso media modal when I click on the button to update my site icon. It takes me to the Customizer instead, and when I click on the `Select logo` option under `Identity` I see the core media picker instead. 🤔
