### ISSUE TITLE
Cover Block nested inside Columns Block cut the text formatting options

### ISSUE THREAD

**Issue by StefZarb** [Automattic/wp-calypso#32988]
#### Steps to reproduce

1. Add a column block with 3 columns
2. Add a cover block inside the column block
3. Enter a title to the cover

#### What I expected

Being able to add a link to the text or use italic.

#### What happened instead

All the options after bold are not visible.

#### Screenshot / Video
https://cld.wthms.co/fnBn2A

#### Context / Source
Ticket: #2027267-zen

**Comment by arunsathiya** [comment]
This is not specific to Gutenberg implementation on WordPress.com. I am able to reproduce this on core WordPress installs - self-hosted WordPress (WordPress.org) sites. Could you submit an issue on `WordPress/Gutenberg` instead, @StefZarb? 

The closest I came to this is https://github.com/WordPress/gutenberg/issues/11499, but it's not the same. Perhaps when you create a new issue on the Gutenberg repo, you can link to https://github.com/WordPress/gutenberg/issues/11499 as well on that report. 

I am closing this report.

**Comment by arunsathiya** [comment]
Seems to be reported here https://github.com/WordPress/gutenberg/issues/15620
