### ISSUE TITLE
Notifications: Sometimes you can't tell which blog a notification is coming from

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#32986]
<img width="451" alt="Screen_Shot_2019-04-25_at_5 19 37_PM" src="https://user-images.githubusercontent.com/2124984/57632295-4e7ac880-756f-11e9-9438-537b4ff6448d.png">

When you're notified of a new post or comment on a blog you follow and the title of that post or comment is very long it obscured the title of the blog where the notification is originating from. 

e.g. John Doe posted "this is a very long title—it's so long that it will hide the part where It tells the user what blog this was posted on" on The Studio

The "on The Studio" part would probably be hidden. If the title is especially long it's even hidden when you click on the notification and expand the drawer. (see screenshots) 

This might be a very a8c-centric problem since we really push the notification feeds functionality to its limits, but it still feels like the website that a notification is originating from should be put in a spot where it won't get easily hidden.

Originally reported by @dabowman

**Comment by scalarbane2** [comment]
Hello all! I looked into this and this is what I think: 

![Notification](https://user-images.githubusercontent.com/50745054/58425027-b0b7eb00-8090-11e9-8915-107e0ba0315f.png)


I tried putting the blog where the article was posted and the author as a label at the top. This would make room for a longer title in the title section.

I tried some other options by putting the gravatar and the name of the author at the bottom left and the blog where it was posted at the bottom right, but it no longer looks like a notification after doing that.

@dabowman Let me know what you think.

**Comment by alaczek** [comment]
@scalarbane2 looks like you mocked up the new post notification only - could you also explore the other types of notifications?

**Comment by scalarbane2** [comment]
Yeah, @alaczek Other notifications won't change because none of them has a lengthy title that will overflow.

**Comment by sixhours** [comment]
Moving this back to To Do so a CrT or dev can pick it up!

**Comment by sixhours** [comment]
It took some digging, but I eventually found where that post subject line gets put together, like so:

`$subject = __( '%1$s posted %2$s on %3$s' );`

It's fairly easy to rearrange that line and restyle it to match the proposed design:

`$subject = __( '%1$s posted %2$s on %3$s' );`
 but I noticed moving the post title to the end breaks things a little if there isn't a word or phrase between each placeholder. I'm guessing there's some regex searching for a pattern that fails to match when you change the elements' orders. I can fudge it with a non-breaking space between the blog name and the post title, but that's hacky. :)

This makes me think we need to consult with someone who has notifications experience before we consider this change.

@kwight, could you take a look and let me know if I'm on the right track? You wrote the guide that helped me figure out where to find this,

**Comment by kwight** [comment]
@sixhours Hm, I _can't_ find where that subject is assembled, so you're ahead of me 🙃 But I'd say do whatever you think is best; feel free to ping me for review if you like 👍

**Comment by sixhours** [comment]
@scalarbane2 The more I look at this, the more I think we shouldn't change the text formatting, beyond shifting the title to its own line. Because every other notification follows the same format, with the username in bold, the title in italics, etc:

<img width="409" alt="Screen Shot 2019-06-26 at 11 55 30 AM" src="https://user-images.githubusercontent.com/2124984/60195648-76657900-9809-11e9-825b-1f8bd02dac7f.png">

If we updated one type of note to use a different format than the rest, that would be confusing. But moving the title to its own line fixes the bug in question without disrupting the existing experience.

**Comment by sixhours** [comment]
I've updated this in D29846-code

**Comment by sixhours** [comment]
Deployed in r193725-wpcom
