### ISSUE TITLE
Posts: scheduled preview pulls wrong image for post

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#33]
One of a user's posts is using an incorrect image preview on the Calypso "Scheduled" posts listing. The image is being pulled from another one of the user's posts. The post itself looks fine in the editor and has the right content - it's just the preview image that is incorrect.

The post has no featured image.  I didn't detect any image change in the post revision history (but can't say for sure), which lead me to believe there was an issue beyond that.

This is issue I think being caused by how we're selecting the image to show in the list. One of the bits of data it considers is the set of images that are attached to the post, which can easily lead to confusion because the attaching of an image to a post is not something that is emphasized in the UI. WordPress core has also really downplayed it.

**Comment by rachelmcr** [comment]
Another user came across this issue with a published post. The image showing in the blog posts list was uploaded and attached to the post, but never used in the post content. Another image was upload and attached to the post, and used in the post content, but doesn't appear with the post in the post list. (It'd be better if the post list selected images added to the body of the post over other images.)

**Comment by hoverduck** [comment]
14Apr16 Bug Scrub

Confirmed this is still an issue.  Here are the steps to reproduce:

1) Start a new post
2) Add an image to the post.  Upload a new file, don't select one that's already in the media library.
3) Select the image and remove it from the post with the X
4) At this point you can either add a new image from the media library to replace it, or leave it empty for a post with no images
5) Publish
6) Return to the Posts list and you'll see the post preview has the first image displayed

![wp-calypso-issue-33](https://cloud.githubusercontent.com/assets/7233112/14535879/f468c60a-023d-11e6-9a62-2a12f6921c34.gif)

**Comment by lizkarkoski** [comment]
I saw this today too, with an image I did not use in my post displaying in my posts list but I did use another image in my post that should be displayed instead. Deleting the image that was showing made a different image that I uploaded show instead of the image in the post.

**Comment by gwwar** [comment]
It looks like post.canonical_image is pointing to the old image. I'll investigate

**Comment by lancewillett** [comment]
@gwwar Reviewing this bug in a scrub: did you have a chance to investigate ` post.canonical_image is pointing to the old image` yet?

**Comment by gwwar** [comment]
I wasn't able to find anything concrete back in Jun. This is on our backlog, but other teams are welcome to work on this if it's blocking anything.

**Comment by alisterscott** [comment]
Retested using @hoverduck's steps above and I don't see an incorrect image, or an image when there isn't any image, so it looks this like has been resolved 🎉
