### ISSUE TITLE
Gutenberg: Revert temporary fix for linking issue in Safari

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#33004]
In order to avoid issues like https://github.com/Automattic/wp-calypso/issues/32965, we implemented D28094-code as temporary fix while we wait for changes from https://github.com/WordPress/gutenberg/pull/15576 to arrive to WP.com. 

This issue is a reminder to revert D28094-code during the next Gutenberg update, although we might want to wait until all unsafe `getRangeAt` usages are fixed (https://github.com/WordPress/gutenberg/issues/15606).

**Comment by mmtr** [comment]
@gwwar I forgot to bring up this one during our meeting today.

Do you think we should revert this one now that WordPress/gutenberg#15576 is in WP.com, or should we wait for WordPress/gutenberg#15606?

I always prefer to be on the safer side but I don't know if overriding a native function can be considered safer than avoiding a [potential issue with the autocomplete component](https://github.com/WordPress/gutenberg/blob/449c25459c917b546cdfd786dbfd56dd3cb9a43a/packages/components/src/autocomplete/index.js#L142) which never has been reported.

**Comment by gwwar** [comment]
We can wait for https://github.com/WordPress/gutenberg/issues/15606, if I find some time I'll try spinning up a patch for that if no one else takes it

**Comment by gwwar** [comment]
Added D32837-code
