### ISSUE TITLE
Ecommerce plan: Thank you page notices

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#33009]
When signing up and purchasing Ecommerce plan, the "Thank you" page has two notices regarding email address confirmation, with slightly different messages, and different colors.

![image](https://user-images.githubusercontent.com/4550351/57671479-439b6300-7657-11e9-8a4d-8885723ef879.png)

Clicking on "Create your store" takes you to a screen, where you're asked about it again, with yet another color and copy in the notification.

![image](https://user-images.githubusercontent.com/4550351/57671687-329f2180-7658-11e9-929a-d067ac4a661a.png)

#### Steps to reproduce
1. Start the signup process and select ecommerce plan. Don't immediately confirm email.
2. Go through checkout, to get to "Thank you" page.
3. Note the two notices

#### What I expected
To have a single notice, but perhaps this is an opportunity to think more broadly about the requirement to confirm email address, before proceeding with the setup.

#dogfooding, #manual-testing, #automated-testing

**Comment by sixhours** [comment]
I wonder if this has already been fixed; I no longer see the warning or error  when I check out with an unverified email address. I get this instead:

<img width="534" alt="Screen Shot 2019-07-02 at 6 19 33 PM" src="https://user-images.githubusercontent.com/2124984/60550452-0453cf00-9cf6-11e9-9a21-eb5a77ddeb50.png">

I also found the code blocks for these errors, but the red one doesn't appear to be referenced elsewhere, leading me to believe it was disabled at some point:

https://github.com/Automattic/wp-calypso/blob/5963c4990fb544197f4836455aaa578c24cec1bf/client/my-sites/checkout/checkout-thank-you/index.jsx#L221-L240

I'll check the commit history and see if this was fixed as part of a different update.

**Comment by sixhours** [comment]
Yup, it appears the double notice was fixed in #33812 about two weeks ago.
