### ISSUE TITLE
Manage section visible for non-admin users as well, while it shouldn't be

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#33020]
#### Steps to reproduce 

- Start with a non-admin account on a WordPress.com site
- Visit the WordPress.com dashboard
- Look for the `Manage` section on the left navigation

#### What is expected 

The `Manage` section is not visible because the features here are primarily actionable by the admin users.

#### What happens instead 

The `Manage` section is shown and it does not have any child sections.

<img width="453" alt="Screenshot 2019-05-14 at 19 59 00" src="https://user-images.githubusercontent.com/18581859/57706983-70b23a80-7684-11e9-94e6-1faaf8428eb4.png">

#### Notes

On a related note, the `Tools` section is visible and has the `Marketing` child section - which is okay.

<img width="452" alt="Screenshot 2019-05-14 at 22 07 53" src="https://user-images.githubusercontent.com/18581859/57715595-c2fb5780-7694-11e9-99dc-0d579c9a36d6.png">

**Comment by torres126** [comment]
> On a related note, the Tools section is visible and has the Marketing child section - which is okay.

I proposed a fix for the Manage section, but should the Tools section really be visible for non-administrators? As a contributor, I'm getting a notice error for it and I don't feel like I should have permission to access it.

**Comment by arunsathiya** [comment]
>As a contributor, I'm getting a notice error for it and I don't feel like I should have permission to access it.

I completely missed that. I believe for `contribute` role, all sections under `Tools` do not work and should be hidden as well. 👍🏽 

<img width="391" alt="Screenshot 2019-05-14 at 22 23 25" src="https://user-images.githubusercontent.com/18581859/57716563-eb845100-7696-11e9-9260-1c5ee3df4259.png">

**Comment by arunsathiya** [comment]
Created a tracker for https://github.com/Automattic/wp-calypso/issues/33020#issuecomment-492322409 here - https://github.com/Automattic/wp-calypso/issues/33033
