### ISSUE TITLE
Ecommerce Plan: Processing screen design needs revamp

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33037]
<img width="774" alt="Screen Shot 2019-05-14 at 3 59 51 PM" src="https://user-images.githubusercontent.com/2124984/57728224-67fc3d00-7661-11e9-8fba-696808523afe.png">

After checking out with the eCommerce Plan, you get this processing screen, which doesn't look very inspiring given the $$$ the customer has just paid. 

Originally reported by @ianstewart . The whole video of signup process can be found in this post (under eCommerce plan customers): paObgF-7Y-p2

**Comment by jeffikus** [comment]
We already removed the masterbar for pages like Checkout and Thank You, should we not remove it for this page too?

**Comment by sixhours** [comment]
Yes, I think we should @jeffikus

**Comment by scalarbane2** [comment]
I tried replicating this but it seems it has been fixed. After checking out, the next screen that appears is "Thank you screen" which looks okay to me.

<img width="817" alt="Screenshot 2019-07-09 at 5 18 50 PM" src="https://user-images.githubusercontent.com/50745054/60905994-1a214100-a26e-11e9-9104-b23dd0d0b219.png">

**Comment by lcollette** [comment]
I went through the flow and was able to replicate the issue. The 'Processing' screen appears for about 7-8 seconds before the 'Thank you' screen appears. Here's a video:

https://cl.ly/66fa05e50330

**Comment by scalarbane2** [comment]
Alright. I didn't see it while I was doing that.

**Comment by scalarbane2** [comment]
This is what I came up with, using a progress bar to show activity and process on the page. 
![Processing](https://user-images.githubusercontent.com/50745054/61144687-7b931b00-a4cd-11e9-9744-60cc13888333.png)

Let me know what you think.

**Comment by sixhours** [comment]
@scalarbane2 Thanks for taking a first pass at this! I think we should use a similar processing screen to the one we currently use for onboarding, for consistency. You can see it as you finish up the setup process at https://wordpress.com/start (there are floating icons, and the WordPress logo). Have a look and let us know what you think.

**Comment by scalarbane2** [comment]
![Processing](https://user-images.githubusercontent.com/50745054/61558685-a1856600-aa5f-11e9-8965-7ebdfa77894b.png)

Following the similar processing screen.

**Comment by sixhours** [comment]
I started working on this and realized that our checkout flow uses different colors from signup, so I'm swapping out the dark blue background for checkout's gray background and using darker colors for the foreground text and elements.

Testing this one is tricky, though, because I can't seem to get it to pause on the loading screen long enough to debug the styles and animations effectively. Will keep plugging away at it.
