### ISSUE TITLE
Editor: Page Title says "Edit Post ‹ Blog Name..." when adding a new post

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3303]
I find this confusing as I am adding a new post not editing an existing one.

**Steps to reproduce**
1. Start creating a new post
2. Look at page title in tab bar

**Expected: "Add New Post ‹ Blog Name..."  (This is what wp-admin shows)**

**Actual:** "Edit Post ‹ Blog Name..."

![add new post title](https://cloud.githubusercontent.com/assets/128826/13040681/f54474aa-d3fa-11e5-8591-e9418c33a5ad.png)

**Comment by alisterscott** [comment]
The "Edit Post" would still show if the post has already been published.

**Comment by alisterscott** [comment]
Looking at the code, the page title initially is set to "New Post" until auto-save kicks in.

I think it would be preferable to base this upon whether the post is published yet rather than changing a few seconds after entering some data.

**Comment by alisterscott** [comment]
Same issue applies to pages

**Comment by rachelmcr** [comment]
Confirmed this is still an issue.

#bug-scrub #pre-gutenburg-bug-purge
