### ISSUE TITLE
Ecommerce Plan: Simplify Masterbar to avoid confusion

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33038]
<img width="775" alt="Screen Shot 2019-05-14 at 4 05 55 PM" src="https://user-images.githubusercontent.com/2124984/57728613-56fffb80-7662-11e9-8218-e9f04dd96aba.png">

When checking out with the eCommerce Plan, we could simplify or even remove the masterbar (like we do in signup) to avoid confusion. It's easy for folks to get away from their original setup goal by clicking  these links. 

Originally reported by @ianstewart . The whole video of signup process can be found in this post (under eCommerce plan customers): paObgF-7Y-p2

**Comment by jeffikus** [comment]
@sixhours I'd be keen to work on this. Isn't this a duplicate with #33012 ?

**Comment by sixhours** [comment]
Nope! The screenshot wasn't very clear, sorry. This ticket refers to removing the masterbar at the top of the screen:

<img width="775" alt="57728613-56fffb80-7662-11e9-8218-e9f04dd96aba" src="https://user-images.githubusercontent.com/2124984/58972702-22c4ba00-878c-11e9-84e8-531c9530bfee.png">

The other ticket refers to the other elements on the page besides the masterbar.

**Comment by jeffikus** [comment]
Sure, I'll take a look at the masterbar part then :)
