### ISSUE TITLE
Ecommerce Plan: Store setup uses outdated signup design patterns

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33041]
<img width="776" alt="Screen Shot 2019-05-14 at 4 17 28 PM" src="https://user-images.githubusercontent.com/2124984/57729306-de01a380-7663-11e9-974c-fa8bbb410eee.png">

The Store setup experience should be updated to use the new signup flow design patterns found at `wordpress.com/start`

* "Floating squares" background should be removed
* Colors should be updated to use the new color schemes CSS vars
* Typography sizes/weights/etc. should match

**Comment by laurelfulford** [comment]
It looks like this code lives in [wc-calypso-bridge here](https://github.com/Automattic/wc-calypso-bridge/blob/5b5155e4de597bbfc079ed24c095e12b6b5129c5/includes/class-wc-calypso-bridge-admin-setup-wizard.php#L91).

Following the step-up steps there, I’m running into errors getting Calyposify working.

@jeffikus helped me troubleshoot; we finally zeroed in that it’s not working with Jetpack 7.4, but it does work with older versions — it looks like it stopped working as of Jetpack 7.3, but works in 7.2 and older.

Next steps:

We put out some feelers to try to narrow down what’s going on; for the short-term I’m going to wait to hear back about them, then likely relocate this issue to wc-calypso-bridge.  

p1560294493012300-slack-wp-paid-plans
p1560295437282100-slack-jetpack-crew

**Comment by laurelfulford** [comment]
I moved this issue over to the wc-calypso-bridge repo, where the code lives. 

There's some additional discussion around the Calypsoify issues I had, as well as a work-around, p1560363676321600-slack-jetpack-crew. The issue hasn't been recreate-able by everyone who's looked at it, so I'm at a bit of a loss over what specifically's causing problems.
