### ISSUE TITLE
Gutenberg: Convert to Blocks Prompt [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33043]
In this task lets add a prompt to ask folks to convert the post when opening a post made in the Classic editor in Gutenberg. (Gutenberg has this option under the classic block, but we'll want to surface this functionality).

<img width="704" alt="50568850-1d5ed180-0d0d-11e9-9722-6d80d4c8eae4" src="https://user-images.githubusercontent.com/1270189/57731663-08496600-7650-11e9-89d9-aa898220d103.png">

![screen shot 2018-08-09 at 3 47 22 pm](https://user-images.githubusercontent.com/1270189/43929880-9ed7f5a4-9beb-11e8-9be6-24457582da22.png)

This was previously implemented in https://github.com/Automattic/wp-calypso/pull/29790, but should be added to our latest integration.

To outline behavior requirements:
- Opening a post with a **single** Classic block displays the prompt
- Clicking on Convert to Blocks will convert the classic blocks
- Folks may undo this action using normal Editor undo

Implementation wise, this may be done at /block-editor only, or at both /wp-admin and /block-editor. Depending on what folks choose we may need an additional Jetpack PR, or use core dialog components.

See also prior work in p7jreA-22i-p2 and discussion in p58i-7OD-p2
See PCYsg-l4k-p2 and PCYsg-l4k-p2 for how the integration works

**Comment by mtias** [comment]
It would be good to assure users that this can be undone if something doesn't look right.
