### ISSUE TITLE
Sakura: Account settings: Sidebar heading shouldn't be white on hover

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#33051]
#### Steps to reproduce 

- Start at https://wordpress.com/me/account and choose `Sakura` color scheme
- Look for the `Profile` and `Special` sidebar headings
- Hover over them

#### What is expected 

They should use `--color-schemes` as indicated below.

<img width="341" alt="Screenshot 2019-05-15 at 09 49 22" src="https://user-images.githubusercontent.com/18581859/57760779-e6b4b100-7719-11e9-9ff0-bee840fc5d87.png">
<img width="350" alt="Screenshot 2019-05-15 at 09 49 29" src="https://user-images.githubusercontent.com/18581859/57760780-e74d4780-7719-11e9-8e1f-b63847a1bf3f.png">

#### What happens instead 

They appear in white at the moment.

<img width="418" alt="Screenshot 2019-05-15 at 09 47 31" src="https://user-images.githubusercontent.com/18581859/57760776-e6b4b100-7719-11e9-8349-a751bb8c85aa.png">
<img width="399" alt="Screenshot 2019-05-15 at 09 47 34" src="https://user-images.githubusercontent.com/18581859/57760778-e6b4b100-7719-11e9-8ee5-62b862d5d30d.png">

#### Notes

Hover state appears to be fine for other color schemes.

| Color scheme | Images |
|------|------|
| Classic Bright | <img width="357" alt="Screenshot 2019-05-15 at 14 02 07" src="https://user-images.githubusercontent.com/18581859/57760957-2ed3d380-771a-11e9-97a9-3c80b81f977d.png"> <img width="358" alt="Screenshot 2019-05-15 at 14 02 10" src="https://user-images.githubusercontent.com/18581859/57760958-2ed3d380-771a-11e9-8a9b-3705ec913b48.png"> | 
| Classic Blue | <img width="315" alt="Screenshot 2019-05-15 at 14 02 23" src="https://user-images.githubusercontent.com/18581859/57760959-2f6c6a00-771a-11e9-826d-7d3ba9ce26a7.png"> <img width="344" alt="Screenshot 2019-05-15 at 14 02 25" src="https://user-images.githubusercontent.com/18581859/57760960-2f6c6a00-771a-11e9-8773-2ee7941c1853.png"> | 
| Powder snow | <img width="315" alt="Screenshot 2019-05-15 at 14 02 35" src="https://user-images.githubusercontent.com/18581859/57760962-2f6c6a00-771a-11e9-849e-0d1ab2ae3293.png"> <img width="332" alt="Screenshot 2019-05-15 at 14 02 38" src="https://user-images.githubusercontent.com/18581859/57760963-30050080-771a-11e9-8832-6f132dfb98aa.png"> | 
| Nightfall | <img width="330" alt="Screenshot 2019-05-15 at 14 02 47" src="https://user-images.githubusercontent.com/18581859/57760965-30050080-771a-11e9-9cb6-56c7ea720dc9.png"> <img width="395" alt="Screenshot 2019-05-15 at 14 02 50" src="https://user-images.githubusercontent.com/18581859/57760966-30050080-771a-11e9-9fe0-9d354e28fc06.png"> |

**Comment by torres126** [comment]
Shouldn't this and #33052 be addressed by #32912?

**Comment by arunsathiya** [comment]
You are right, @torres126. 👍🏽
