### ISSUE TITLE
Signup: resume signup flow in the desktop app

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#3305]
In a browser, if you partially complete signup and leave the page, we'll try to resume signup when the user returns to `/start`.

On the desktop app, on the other hand, we just redirect the user back to the login screen (See https://github.com/Automattic/wp-desktop/pull/84). @mjangda suggested we should have the same behavior in both the app and the browser.

cc @breezyskies for input from Cerulean.

Related to https://github.com/Automattic/wp-calypso/pull/3221.

**Comment by breezyskies** [comment]
Agree with the previous suggestions to mimic the browser behavior here.
