### ISSUE TITLE
Plugins: Upload Plugin button isn't very prominent

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33061]
<img width="1031" alt="Screen Shot 2019-05-15 at 12 10 14 PM" src="https://user-images.githubusercontent.com/2124984/57791307-866a4300-770a-11e9-9ddf-093da7580d48.png">

If uploading a plugin is one of the most important actions on the Plugins page, we should treat it as such and make it stand out a bit more. Currently there are many potential pathways one can take from this page (search for a plugin, upload a plugin, browse the directory) but the page lacks visual hierarchy so none of these actions stand out clearly.

It's also not very clear that you can't do *any* of these things until you have a Business plan. The callout at the top of the page is very small. I can see allowing folks to browse and maybe get excited about adding plugins before they choose to purchase the Business plan, but I wonder if that's too much of a distraction, provided the end goal is for them to upgrade.

Found during this walkthrough by @ianstewart  https://cloudup.com/cTAV7Njdy1z

**Comment by alaczek** [comment]
For reference, this is how the Calypsoified version of this screen looks like (after the first plugins is installed).

![image](https://user-images.githubusercontent.com/4550351/57817238-c8a28b80-77c1-11e9-927a-238a23a15eea.png)

**Comment by sixhours** [comment]
Uploading plugins isn't necessarily the primary action for this page, but we need some design explorations around how to make it more prominent.

**Comment by sixhours** [comment]
Good to note, once you've "gone Atomic" you never see this screen again, and the primary action on the new screen is to upload a plugin.

**Comment by scalarbane2** [comment]
This is what I came up with: since it isn't a primary action, I thought it would be great to add space between the bar and the action to make the upload button distinct and not adding a sense of it being the primary action. Let me know what you think about this. @donpark @lcollette @sixhours 

![Plugin upload](https://user-images.githubusercontent.com/50745054/61052519-7bb6ec00-a3e3-11e9-8530-2860d8a52bf6.png)

**Comment by donpark** [comment]
It's definitely better IMO, helping with search also needing some emphasis. Frankly, my main beef with current design is with seemingly arbitrary categories being presented front and center at the expense of search and upload.

Wondering if moving separated Upload Plugin button to the left will work better. This layout also emphasizes the Search button (by being at the end).

**Comment by scalarbane2** [comment]
Speaking of that, it seems to me that moving the upload button to the left makes it look like a primary action. Personally, I would go with the first design. 
![Plugin upload 2](https://user-images.githubusercontent.com/50745054/61080703-8e4e1700-a41d-11e9-87f3-330fd07bbc78.png)

**Comment by lcollette** [comment]
I like that the upload CTA is visually distinctive now. The separation draws the eye, solving for the prominence issue. Though I agree with @donpark about the placement of Search and the arbitrary categories. 

Search could use more prominence while the keywords could have less.

**Comment by chickenn00dle** [comment]
Separated Plugin Upload button out, and moved to the left here: https://github.com/Automattic/wp-calypso/pull/36141

IMO moving to the left is a better call to bring attention to both button and search as @donpark mentioned.
