### ISSUE TITLE
Plugins: Upload plugins page says there's an error if you don't have a Business plan

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33063]
<img width="1031" alt="Screen Shot 2019-05-15 at 12 21 24 PM" src="https://user-images.githubusercontent.com/2124984/57792024-0cd35480-770c-11e9-9aec-5d16d8d6ac82.png">

If you try to upload a plugin when you don't yet have a Business plan, you see this page.

* "The errors above must be resolved before proceeding." - This message is generic and not very helpful. If this is an error, it should display with the red indicators/icons around it. 
* That said, I don't think we need this message at this stage in the process. If the goal is to drive people to the Business plan from this page, we shouldn't distract them with extraneous messaging. 
* This page needs a clearer call to action. The upgrade notice uses small type, and the wording doesn't mention plugins at all -- it distracts with "also get...." a bunch of features that distract from the ultimate goal, which on this page is to upload plugins.

Found during this walkthrough by @ianstewart https://cloudup.com/cTAV7Njdy1z

**Comment by ianstewart** [comment]
Closing this issue as the screen has changed. It still needs work! But the original issue has been corrected. (It no longer has an "error" message.)
