### ISSUE TITLE
Plugins: Unnecessary Guided Tour after successful plugin upload

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33065]
<img width="1026" alt="Screen Shot 2019-05-15 at 1 15 27 PM" src="https://user-images.githubusercontent.com/2124984/57795651-85d6aa00-7714-11e9-8209-61d7e34e6ee7.png">

When you successfully upload a plugin (and your site first gets converted to an Atomic site), a guided tour appears in the sidebar, instructing you as to where to go to install and manage plugins.

Since you've already gone through the process of installing a plugin, the guided tour is unnecessary and should be removed.

Found during this walkthrough by @ianstewart https://cloudup.com/cTAV7Njdy1z Timestamp ~ 3:55

**Comment by alaczek** [comment]
This tooltip is being addressed in #32821. Closing as duplicate.
