### ISSUE TITLE
Plugins: No clear next step after installing plugin

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33066]
After installing a plugin, you're brought to the plugin information page, which looks something like this:

<img width="1032" alt="Screen Shot 2019-05-15 at 1 25 11 PM" src="https://user-images.githubusercontent.com/2124984/57796871-2928be80-7717-11e9-912d-7dc1683eb0de.png">

This page offers little useful information for someone who has already chosen the plugin. There is no clear call to action or direction. Provided I want to use or set up the plugin, I don't know where to go to do that.

Returning to the Plugins page, there's no indication the plugin you've installed is available. At this point, we get into Calypsoify/wp-admin which is probably out of the scope of this audit, but perhaps there is something we can redesign on the previous page to better guide users to the right place.

Found during this walkthrough by @ianstewart https://cloudup.com/cTAV7Njdy1z

**Comment by sixhours** [comment]
Can we redirect them to Installed Plugins after installation?

**Comment by ianstewart** [comment]
Edit: Moving my comment to another issue because it's not related enough. :)

**Comment by davipontesblog** [comment]
Wanted to support this one again since it's still as relevant as it was when created.

**Comment by ianstewart** [comment]
The status has not changed here. It's probably even a little more complicated than this issue suggests now.

The Core WordPress experience is something like this.

After activation some plugins redirect the user to a special flow (like WooCommerce) or throw a special modal (like BuddyPress) with special information or clear next steps. Some plugins also use WordPress notifications for providing additional information on the Dashboard or Plugins screens. Here are the three different general cases I'm aware of:

![image](https://user-images.githubusercontent.com/545779/115083522-17d12980-9ecd-11eb-8410-f9781d2286d1.png)

That said, it seems most plugins return one to `plugins.php` where WordPress provides hooks or filters for adding links to those special flows or modals or screens.

![image](https://user-images.githubusercontent.com/545779/115084043-eb69dd00-9ecd-11eb-9442-de8a6566927b.png)





Those experiences are available now to our users on the Business and Ecommerce Plan level. But there's an additional post-activation flow that further complicates this. The initial one. When you first install a plugin on WordPress.com the first post activation screen you see is one like the one above in the issue.

![image](https://user-images.githubusercontent.com/545779/115083842-a3e35100-9ecd-11eb-9999-cbe2f1ba9a29.png)

The extra-complication is that you only experience that flow **once** right now as you later see only /plugins.php when attempting to return to the plugins screen.

![image](https://user-images.githubusercontent.com/545779/115084219-2c61f180-9ece-11eb-86b8-f7310fb60063.png)

As to untangling some of this … :)

I recommended in another issue that we remain true to [the intended custom post-activation screen for WooCommerce](https://github.com/Automattic/wp-calypso/issues/51327). I think that makes sense, in general, as it will match expectations for tutorials and plugin documentation. (Though I wonder if WordPress core could offer more to plugins in general for standardizing those flows in a separate core issue.)

That out of the way, what about general plugins? 

1. Is it possible to make some of the same default next actions available per plugin available in Calypso?
2. Is it possible to use the WordPress.com/plugins screen as a default for navigating plugins excepting when the "Show advanced dashboard pages" button is active?

**Comment by obenland** [comment]
> Is it possible to make some of the same default next actions available per plugin available in Calypso?

Back when I worked on [Shiny Updates](https://make.wordpress.org/core/features/shiny-updates/), those default next actions were added by hijacking the page load after a plugin was activated and redirecting it to a plugin's onboarding screen. Not sure how to replicate that in Calypso without dropping customers in wp-admin's plugin screen with those same parameters, which I imagine could be a little jarring.

> Is it possible to use the WordPress.com/plugins screen as a default for navigating plugins excepting when the "Show advanced dashboard pages" button is active?

We've decided to always point to wp-admin/plugins.php for WoA sites because of the special meta links and other customizations that plugins register and you pointed out:

![image](https://user-images.githubusercontent.com/545779/115084043-eb69dd00-9ecd-11eb-9442-de8a6566927b.png)

**Comment by obenland** [comment]
> The extra-complication is that you only experience that flow once right now as you later see only /plugins.php when attempting to return to the plugins screen.

Even doing the atomic transfer upon plan upgrade won't fix this since it would still happen for all sites that are not on a business plan yet. :(

Maybe we could change the CTA from Install to Upgrade Plan?

**Comment by JanaMW27** [comment]
Yes, currently there is no clear next step for the user once they install and activate the plugin. We are looking into introducing a SETUP cta for the Yoast project, that will be revealed after installation, so the user can click on it and go to set up the plugin.
Within the plugins experience we should look into:
- Aligning both experiences (calypso and core)
- Adding the next step once the plugin is installed to continue the journey
- Information parity on the plugin detail page

**Comment by pablinos** [comment]
> Maybe we could change the CTA from Install to Upgrade Plan?

That makes sense to me. It seems like wasted effort to maintain two experiences like this, especially as one will only be seen for the first plugin installation. Interestingly, I can use the Calypso plugin management for my Jetpack site, so there's another fork in the experience.

Perhaps we make the plugins page a static CTA to upgrade as well as optionally install a plugin, and from then on we send them to `wp-admin`. We can concentrate on improving the experience there.

**Comment by allilevine** [comment]
See https://github.com/Automattic/wp-calypso/issues/54034

**Comment by cpapazoglou** [comment]
This is resolved by the new marketplace thank you page

https://wordpress.com/marketplace/thank-you/:slug/:siteId

<img width="845" alt="CleanShot 2022-04-25 at 15 34 57@2x" src="https://user-images.githubusercontent.com/12430020/165089976-5428facf-37f3-4014-acbe-e60018fcb49d.png">
