### ISSUE TITLE
Gutenframe: Unexpected login failure on Jetpack site [3]

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#33083]
Edit: Please timebox this investigation to 3 days. Add related server logging to help debug. If we cannot find reproduction steps within 3 days, please close this issue, and we can see if we get additional reports.

While testing on my Jetpack test site I was redirected to `wp-login.php` through the editor's iframe.

Surprised that I wasn't logged in (because I thought I was) I proceeded to enter my credentials. The login rejected my credentials.

In another browser tab I went to the `wp-admin` page of that same test site and logged in with my usual credentials. The site accepted the credentials and redirected me to the WordPress dashboard.

Back in the editor I reloaded in hopes that now the iframe would load properly. Instead it showed me the `wp-login.php` page again. It still wanted me to login but this time said I only had three more attempts at a failed login. I reloaded the page - two more attempts at a failed login.

After trying a few things I got locked out of my site. Once I switched back to the other tab I discovered that my entire login session was killed and I got kicked out where I had previously been allowed int.

Not sure what happened or why but somehow my session was invalidated. I'm guessing this relates in some way to the `jetpack_frame_nonce` and maybe it's expired but Calypso is still trying to use it?

These details are scant but I didn't have much to work with when I saw it happen.

**Comment by kwight** [comment]
Noting that these flows have been greatly improved with the merge of https://github.com/Automattic/jetpack/pull/12215, meaning this may even be very difficult to reproduce.

**Comment by dmsnell** [comment]
@kwight if you are saying that Automattic/jetpack#12215 is going to make it harder to debug then that's cool; if you are saying it should prevent this then I think we have a problem because it happened yesterday.

could it be that that PR _caused_ this? the kicker is that I wasn't logged-out of my remote site when it blocked - me - I was logged-in and it somehow rejected that and also triggered a false-login
