### ISSUE TITLE
Plans: No clear action after upgrading to Blogger plan

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#33085]
The "Thank you" screen customer is presented with after upgrading from Free to Blogger plan has no clear path on what to do next (other than contacting support).

#### Steps to reproduce
1. Start on a site with Free plan.
2. Go to Plans: https://wordpress.com/plans/{site}
3. Upgrade to Personal plan.
4. Take note of the "Thank you" screen.

![image](https://user-images.githubusercontent.com/4550351/57827596-416a0d80-77eb-11e9-911d-b0c1d9e91603.png)

Compare to the "Thank you" screen after upgrading to Personal plan:
![image](https://user-images.githubusercontent.com/4550351/57827964-f81abd80-77ec-11e9-9279-d65439c32875.png)

#### What I expected
Support is not the only features included in Blogger plan, so at the very least I expected all the features listed.

#dogfooding, #manual-testing

**Comment by sixhours** [comment]
Let's not work on this until after the A/B test around the Blogger plan is complete.

**Comment by dzver** [comment]
Fixed in #34359
