### ISSUE TITLE
Themes: "Customize Site" button to open in a New Tab

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#33088]
Imagine that user activates a new theme and they want to customize it.

Even if the user gets to the page with the theme instructions, once they click on Customize site button:

![screen-shot-on-2019-04-14-at-121801](https://user-images.githubusercontent.com/25105483/57844636-c1cf4500-77d0-11e9-968a-d890db876112.png)

it gets them right to the Customizer – as we would expect. BUT – at this point, they no longer see the theme Setup page and can be (and feel) lost.

I usually suggest users to open one browser tab with the theme setup instructions and then the second tab with Customizer – so they can switch between tabs as necessary. Sometimes even the third tab is needed – to make changes to posts and pages, or other settings in Calypso.

**My suggestion to make the process less confusing, would be to have the Customize site button (in the screenshot above) open Customizer in a new tab.**

Users can already open theme instructions in a new tab from Customizer like this:

![screen-shot-on-2019-04-14-at-122832](https://user-images.githubusercontent.com/25105483/57844751-fba04b80-77d0-11e9-89cb-7c737999b09b.png)

which is handy!

**Comment by arunsathiya** [comment]
Huge +1 to this. We often run into questions related to theme setup on Happiness, and this enhancement could help with that. I am tagging this with `FixTheFlows` and adding it to the related project, but if this isn't an idea for now, let's feel free to remove. 👍🏽
