### ISSUE TITLE
Jetpack checklist: completed titles are links and it's confusing

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33093]
I keep accidentally clicking/tapping these links that don't reveal themselves as links:

<img width="543" alt="Screenshot 2019-05-16 at 15 37 35" src="https://user-images.githubusercontent.com/87168/57856424-b2aebe00-77f5-11e9-9054-186513599aec.png">
<img width="602" alt="Screenshot 2019-05-16 at 15 37 53" src="https://user-images.githubusercontent.com/87168/57856423-b2aebe00-77f5-11e9-8c5c-2f3b3540498a.png">

I suggest we remove links when tasks are completed and keep links only in "change" and "configure" actions:

<img width="690" alt="Screenshot 2019-05-16 at 16 15 34" src="https://user-images.githubusercontent.com/87168/57856507-e689e380-77f5-11e9-970e-6c5115365d59.png">

cc @jeffgolenski

**Comment by jeffgolenski** [comment]
@simison make it so!
