### ISSUE TITLE
Editor: Media: image toolbar overlaps Actions and Preview screens on iPhone 6 iOS 9.1

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#331]
Steps to reproduce:
1. Start a new post using iPhone 6 on iOS 9.1
2. Insert an image
3. Tap the image so the image toolbar appears
4. Tap the "Actions" button
5. Tap the "Preview" button

<strong>Result:</strong> the image toolbar overlaps the Actions and Preview screens

<img width="414" alt="screen shot 2015-11-08 at sun nov 8 3 11 09 pm" src="https://cloud.githubusercontent.com/assets/1119271/11022660/19a3bcc8-8632-11e5-9b1f-43a1a0bef5c6.png">
<sup>Tested with Safari on iPhone 6 iOS 9.1</sup>

<img width="414" alt="screen shot 2015-11-08 at sun nov 8 3 11 27 pm" src="https://cloud.githubusercontent.com/assets/1119271/11022661/19a4997c-8632-11e5-864b-13080409fdea.png">
<sup>Tested with Safari on iPhone 6 iOS 9.1</sup>

**Comment by nylen** [comment]
Closed by mistake.  It seems likely that this is still an issue.

**Comment by designsimply** [comment]
Closing because I am unable to reproduce the problem after re-testing with iPhone 6S, iOS 11.2.1.

<img alt="img_1754" src="https://user-images.githubusercontent.com/1119271/34233410-6b2ccce8-e5a2-11e7-9437-882d59471946.PNG" width="200" /> <img alt="img_1755" src="https://user-images.githubusercontent.com/1119271/34233411-6b45ae3e-e5a2-11e7-9be4-99f7c58c981c.PNG" width="200" />
