### ISSUE TITLE
Importer Navigation and New Sidebar Usability: Expand Tools section when initiating import after signup

### ISSUE THREAD

**Issue by dezzie** [Automattic/wp-calypso#33105]
This is a sub-story of: https://github.com/Automattic/wp-calypso/issues/31169
And directly following: https://github.com/Automattic/wp-calypso/issues/33104
There are sub-stories for each of the goals for better QA. Either me or @shaunandrews can design review and approve all of them.

@obi2020 or @ranh I'm tagging you for copy review, but no pressure.

**Context**
I ran a usability test with a participant using one of the importers, and found that the new sidebar makes an existing navigation issue worse (the one described in #31169), especially if the user starts from signup.

**Goal**
To avoid navigation confusion for users completing an import. We are not telling these new users where in the product they are working. If they leave the import flow, the sidebar is not indicating where they are going, and they end up lost.

**Changes needed**
- [ ] When users come to the Import section from signup, the Tools section in the new sidebar is expanded to indicate which subsection they are in. 
- [ ] When users Cancel or or otherwise navigate back during an import task, they now only have one place to go to, which is directly the main importers list:

This is what that should be like:
<img width="1440" alt="Email verify" src="https://user-images.githubusercontent.com/1301932/57886470-e9cfa000-77f2-11e9-9de4-fd6323f097ad.png">

If they navigate or cancel:
<img width="1440" alt="Sidebar Expanded" src="https://user-images.githubusercontent.com/1301932/57886606-31562c00-77f3-11e9-99d0-2361df83870b.png">

**Comment by creativecoder** [comment]
PRs to address this issue are awaiting review

- https://github.com/Automattic/wp-calypso/pull/33556
- https://github.com/Automattic/wp-calypso/pull/33519
