### ISSUE TITLE
Full Site Editing: Navigation Placeholder Block [8]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33109]
Let's create a navigation placeholder block in the [full site editing plugin](https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing). This means that in the full site editor, the navigation renders a preview, but is uneditable. Changes made in the customizer should reflect the preview. 

Twenty Nineteen supports three menu locations. In our block page templates this means that there are two navigation blocks in the "header", and one in the "footer".

Primary, Social Logos and Footer

<img width="1448" alt="Screen Shot 2019-05-16 at 4 15 57 PM" src="https://user-images.githubusercontent.com/1270189/57892954-eb4e9780-77f5-11e9-9448-0913b0148e64.png">

<img width="1690" alt="Screen Shot 2019-05-16 at 4 26 51 PM" src="https://user-images.githubusercontent.com/1270189/57893405-a88dbf00-77f7-11e9-8d6f-ac9aa2422234.png">

<img width="697" alt="screenshot-2019-05-17-at-19 59 57" src="https://user-images.githubusercontent.com/1270189/57947324-75007280-7893-11e9-8a57-d96f78103308.png">

See also: paAmJe-nP-p2

**Comment by kwight** [comment]
@gwwar A few questions I'm wondering as I start out on this:

* How specific or abstract is this supposed to be re: Twenty Nineteen? Is it intended to work for all themes?
* Would the front-end display take the `wp_nav_menu()` params as attributes?
* How much, if any, UI are we thinking of for the edit side? Maybe just a dropdown to select which menu location to display? I'm uncertain how we would then go about determining the specific params used in the theme template.

**Comment by gwwar** [comment]
> How specific or abstract is this supposed to be re: Twenty Nineteen? Is it intended to work for all themes?

As a first pass at this is targeted to Twenty Nineteen so no need to worry about abstracting this across all themes. To start with the absolute bare minimum is a visual placeholder that redirects to the customizer for editing. (This allows us unblock some basic Full Site Editing flows).

For context this is being worked on in Gutenberg in https://github.com/WordPress/gutenberg/issues/13690 and https://github.com/WordPress/gutenberg/pull/14856

And for the edit cases is extremely complex/tricky to nail down flows. 

> Would the front-end display take the wp_nav_menu() params as attributes?

I would recommend creating a dynamic block here as navigation here as this may be edited in a few places (outside the editor).

I'd need to verify how the `theme_location` interacts, but at a minimum initially this might look something like this in code view `<!-- a8c:navigation {"themeLocation":"menu-1"} -->`.

Where the themelocation is baked into the "header" template_part and not editable by the user. This is inferred because the navigation block is in the header template part.

**The key idea being, the block has enough information for the server hook to render the correct thing, and if we edit this in the customizer, the correct menu/updates appear.**

The client will similarly need to create a preview view, which we might need to back by an API if not available.

> How much, if any, UI are we thinking of for the edit side? 

As noted in the mocks no editing will take place in the Block Editor in this iteration. The edit button should redirect to the appropriate customizer link.

<img width="697" alt="57947324-75007280-7893-11e9-8a57-d96f78103308" src="https://user-images.githubusercontent.com/1270189/58920106-8d6eea80-86e5-11e9-8139-5760e2a6b70b.png">

See also: 
https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/ 
https://developer.wordpress.org/block-editor/key-concepts/#serialization-and-the-purpose-of-html-comments
https://developer.wordpress.org/block-editor/developers/block-api/block-edit-save/#edit
