### ISSUE TITLE
Full Site Editing: Header Logo Support [8]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33108]
Let's make sure logos are supported in the [full site editing plugin](https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing). This means that we can update this value in the Customizer under Site Identity, and have that reflected in the full site editor.

Optional: Also allow update of this logo from the full site editor.

<img width="1662" alt="Screen Shot 2019-05-16 at 3 42 53 PM" src="https://user-images.githubusercontent.com/1270189/57892133-b8ef6b00-77f2-11e9-9c22-60ebfd5da1b5.png">

We can register this option with `register_setting` with a `'show_in_rest' => true` arg so that it can be be fetched/updated via core's `/settings` endpoint.

Also keep in mind the difference between core's logo support and the wpcom/jetpack logo feature used in some places. We should target core support.

<img width="776" alt="logo-block-simple-version" src="https://user-images.githubusercontent.com/1270189/57947860-eab90e00-7894-11e9-8ae5-1132b3a48c98.png">

See also: paAmJe-nP-p2

**Comment by apeatling** [comment]
I'd encourage the use of a standard image block for this as a first iteration. If you're able to make the image block show up on a search for "logo" that will satisfy the MVP feedback.

**Comment by gwwar** [comment]
cc @mattwiebe @obenland @mtias if you'd like to add any notes on requirements

**Comment by apeatling** [comment]
Scratch my above comment, you'll need a new block because you're going to need to make sure the image passes through to the logo setting.

**Comment by gwwar** [comment]
Until we move away from theme styling, this block is going to be extremely simple, and probably won't make sense outside of the header template part. 

In the long run a block like this likely only needs to exist during the transition period were we'd like to support more Themes while pieces transition to full block page templates. After logic is removed from the PHP header, I can't think of a good reason not to use a normal image in a template_part "header".

For context:
- Site Logo is stored per site, per _theme_. This is set as part of a set of theme mods as a site option. https://developer.wordpress.org/reference/functions/get_theme_mods/ internal usage is normally get_theme_mod( 'custom_logo' ). There are multiple backing implementations.
- What can be modified depends on the theme/styling. So some themes might allow for sizing, but others like Twenty Nineteen only allow one to select a logo and that's it.

**Comment by gwwar** [comment]
8 points for the initial iteration. I'll link follow up tasks shortly

**Comment by gwwar** [comment]
https://github.com/Automattic/wp-calypso/issues/34006
https://github.com/Automattic/wp-calypso/issues/34007
