### ISSUE TITLE
Full Site Editing: Site Description (Tagline) block [8]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33107]
Let's create a new site description block in the [full site editing plugin](https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing) that is backed by the the “blogdescription” record in the wp_options table.  This means that we can update this value by:

1. In the FSE using this Site Description block
2. “Tagline” set in /wp-admin/options-general.php
3. In the Customizer under Site Identity

Please verify if we need to respect any related description hooks on display.

<img width="1660" alt="Screen Shot 2019-05-16 at 3 38 43 PM" src="https://user-images.githubusercontent.com/1270189/57891610-dc191b00-77f0-11e9-8e6e-526b99218b30.png">

The site description can be be fetched/updated via core's `/settings` endpoint as the `description` member.

See also: paAmJe-nP-p2

**Comment by apeatling** [comment]
Be sure to take a look at and reuse @mattwiebe's MVP block work where possible (although it was a combined header block).

**Comment by gwwar** [comment]
cc @mattwiebe @obenland @mtias if you'd like to add any notes on requirements
