### ISSUE TITLE
Full Site Editing: WP.com Footer Credit Support [13]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33114]
WordPress.com supports a few credit options. The full site editor should support choices made in the customizer under Site Identity > Footer Credit.

<img width="1303" alt="Screen Shot 2019-05-16 at 4 40 11 PM" src="https://user-images.githubusercontent.com/1270189/57893875-6796aa00-77f9-11e9-93f4-d70a71dbf9b0.png">

<img width="290" alt="Screen Shot 2019-05-16 at 4 39 47 PM" src="https://user-images.githubusercontent.com/1270189/57893894-7715f300-77f9-11e9-834e-09a0f333a223.png">

**Comment by apeatling** [comment]
I think this should be punted and fall back to the customizer for the first iteration.

**Comment by alexislloyd** [comment]
I'm fine with @apeatling's suggestion for the first version.

**Comment by mattwiebe** [comment]
A very tricky aspect of this, and the reason for cutting it from the MVP scope, is that WP.com credits are only allowed to be hidden under the Business Plan. Preventing the removal of this block and/or enforcing its position at the bottom of the page will require a fair bit of work.

**Comment by gwwar** [comment]
@apeatling I think we'll need to verify how this is being injected, I think we can cut out preview/edit support from the FSE, but we need this notice in general to be displayed on the published site. If we use a blank theme, this still needs to be implemented in some way.

**Comment by apeatling** [comment]
That sounds good. It should not be tough to inject this with a bit of PHP in the theme.

**Comment by gwwar** [comment]
added an investigation task https://github.com/Automattic/wp-calypso/issues/33134

**Comment by gwwar** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/33114
