### ISSUE TITLE
i18n: Support for atomic sets of strings with fallback

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#33129]
When we make a relatively minor change to a string or two on an existing flow (à la #33127), the immediate, post-merge result is suboptimal.

When the string change lands, & new strings go live across all locales, the experience, will, of course, be fine in English.

However, non-English locales will take an indeterminate amount of time to update and, if there are multiple changes, all translations will not necessarily be complete at the same time.

In cases like the above where we have localized copy already being shown in production flows & the copy change is (relatively) minor, I think it would be preferable to only show the new set of strings when all in the set return true for [`hasTranslation`](https://github.com/Automattic/wp-calypso/blob/7c9c4edef984fe9d407be7b5d99e5ebf398efa3f/packages/i18n-calypso/src/i18n.js#L360).

If some in the set do not have required translations for the current locale, we could provide the previous version of the set of strings as a fallback.

While we could put logic in each component's `render` function to do something along these lines, it would be nice to have a cohesive solution for this across Calypso.

### I Did

Changed wrapped-for-translation string values in a component's `render` funcionality

### I Saw

The new strings shown properly while using the English locale, but unlocalized amongst localized strings in a non-English locale.

### I Expected

All strings to be localized (even if they don't match the most up-to-date English locale copy)

**Comment by ramonjd** [comment]
@Automattic/i18n

**Comment by ramonjd** [comment]
@jblz 

Should we be using the string freeze label more in certain circumstances do you think?

> If you’re launching or updating a calypso feature and you want to make sure all new strings are translated before merging, add the [Status] String Freeze label to your PR.

See: p4TIVU-5Jq-p2

**Comment by ramonjd** [comment]
Ah, I just saw this initiative from Team Global – pxLjZ-5mb-p2

It might be germane to the subject matter too
