### ISSUE TITLE
People Invites: make welcome notice non-global

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#3312]
Currently we use a global notice to display the welcome message when a user accepts an invite. Global notices shouldn't be used for wordy multi-line messages. Let's stick with an in-page notice for this with a standard dismiss button.

Before:

<img src="https://cldup.com/F2QVW-HNJG-3000x3000.png" />

**Comment by rickybanister** [comment]
Our change to the global notices also affected the email verification message we show to users that have just signed up. I think it may be beneficial to work on a possible new component or variation of global notice that works well for these special case notices with a lot of text. They would benefit from friendly graphics as well. I'll think about an alternative so perhaps we don't need to rush to apply the recommended fix above.

**Comment by lancewillett** [comment]
Possible related: #5185

**Comment by designsimply** [comment]
Tested and confirmed using the following testing steps:

1. Log in as the inviter
1. Go to My Sites > People > Invite user
1. Enter the username of the invitee
1. Click the "Send Invitation" button
1. Go to the email inbox for the invitee and copy the "Accept invitation" link
1. Log out
1. Log in as the invitee
1. Go the the "Accept Invitation" link that was copied a few steps earlier
1. Click the "Join" button

<strong>Result:</strong> a really large, green global notice appears that says:

> You're now an Administrator of: Just Another Test Blog with a Very Long Title
> 
> This is your site dashboard where you will be able to manage all aspects of Just Another Test Blog with a Very Long Title

Video: [48s](https://cloudup.com/cnVB0WidupV)

<img width="1280" alt="screen shot 2016-08-30 at tue aug 30 7 40 28 pm" src="https://cloud.githubusercontent.com/assets/1119271/18113018/c7779e00-6ee9-11e6-8282-7da8206939c7.png">
<sup>Seen at https://wordpress.com/posts/17567174 logged in as the invitee (user552) using Firefox 48.0.1 on Mac OS X 10.11.6</sup>

**Comment by rickybanister** [comment]
The new 'first look' design would be a much better experience for users that have just accepted an invitation. It would cover the screen, welcome them, and allow them to dismiss it after learning a bit about this whole new world.

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue as described above.  @ebinnion this is in your bin, do you have a milestone we could put this under, or should we just set it aside under `[Type] Low Priority` for now?

**Comment by rickybanister** [comment]
If we can swap this notice to a non-global one in a very short amount of time, that seems worth it as a temporary fix, but otherwise we will be doing some overhaul to the invite process for Jetpack sites and perhaps we can make all users benefit from that work. If @ebinnion doesn't have time to swap this over we can just close this issue for now.

**Comment by ebinnion** [comment]
Adding the non-global notice isn't too difficult. But, I'd rather do it after I refactor invites to use Redux that way we can get rid of setting a `localStorage` value. I intend on doing some invites work in the new year.

I created a milestone and have added this issue there.
