### ISSUE TITLE
Edit category: Missing space between "Top level category" label and toggle

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#33141]
On https://wordpress.com/settings/taxonomies/category/, click on the 3 dots next to a category to edit the name.

When the popup opens up, notice that there is a missing space between `Top level category` label and toggle.

![Screen Shot 2019-05-19 at 14 53 36](https://user-images.githubusercontent.com/18581859/57980235-2a732780-7a46-11e9-9430-4f9a986a7d73.png)

Likely similar to https://github.com/Automattic/wp-calypso/issues/32057 but I have not investigated.

**Comment by trey** [comment]
I've submitted a PR to fix this. It shows some linting errors that are unrelated to the change I made. I'm not sure how to fix that.

**Comment by arunsathiya** [comment]
@trey I have shared some feedback to help you move forward. - https://github.com/Automattic/wp-calypso/pull/33446#pullrequestreview-245513370

You may ignore the linter warnings for now, which you can address after working on the shared feedback.
