### ISSUE TITLE
Editor: Tags Temporarily Disappear and Won't Reappear When Typing Next Tag Quickly

### ISSUE THREAD

**Issue by darnelldibbles** [Automattic/wp-calypso#33145]
A user reported that as you type in tag into the new editor and press comma, they temporarily disappear for a second and then reappear. However, if you try to type the next tag before the previous tag pops back up, the previous one never shows never shows. The user created and tweeted to us a good video demonstrating the issue here:

https://twitter.com/prissguerrero1/status/1130173823628849154

I was able to reproduce both the _flickering tag issue_ and _the tag not showing up_.

**Example of Tags Flickering:**
It happens intermittently, but it does happen very often and can be frustrating as the user notes in her video:

![Flickering Issue](https://cldup.com/Fa5LBVsOYu.gif)

**Example of First Tag Not Appearing After Second Tag is added Quickly:**

This also happens intermittently, but it particularly happens when you press comma after typing in the first tag and then the tag disappears, but while the tag is temporarily not showing for that second or two, you type in another tag and press comma. The second tag appears, but the initial tag at time does not reappear - or in the case below, temporarily shows up again, but does not permanently.

![Tag doesn't display](https://cldup.com/iIRnFqCBNZ.gif)

**Comment by arunsathiya** [comment]
From what I have seen, this is not a Gutenberg issue specifically on WordPress.com, but happens with WordPress.org installs as well. I am closing this report as it's already reported on the core repository here https://github.com/WordPress/gutenberg/issues/13282.
