### ISSUE TITLE
Reconsider using the LimitChunkCountPlugin to enforce a single chunk

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#33156]
@blowery asked me some time ago to investigate why the `LimitChunkCountPlugin` might be considerably slowing down our webpack builds. Here's what I found.

Webpack calls the various `optimizeChunks*` hooks in a loop that runs as long as at least one handler returns `true`, meaning "I changed something". `LimitChunkCountPlugin` taps into the `optimizeChunksAdvanced` hook.

The plugin looks at all possible pairings of all the chunks and determines how much code is duplicated between them and how much code could be saved by integrating them together. Then it chooses the most promising pair and merges both chunks into one. That eliminates one chunk. The process is repeated as the `optimizeChunks` loop continues to run, eliminating just one chunk in each step.

Finding the most promising pair is very expensive. There are _n(n-1)/2_ possible pairings (imagine a soccer tournament where every team plays with everyone else). Calypso build has approx 300 chunks, which leads to an array of 50000 pairings to sort out in each step. No wonder each step takes approx 10 seconds.

We use `LimitChunkCountPlugin` to create just one chunk when the `code-splitting` option is not enabled. Turns out that it's an extremely slow way to achieve this goal. We should be looking for a better one: prevent creating new chunks in the first place. In other words, enforce [`webpackMode: "eager"`](https://webpack.js.org/api/module-methods/#magic-comments) for each dynamic import.

Our [`optimization.splitChunks` configuration](https://github.com/Automattic/wp-calypso/blob/7f1ac96b9e87aeccf6beb3b976c8d702f0cdca4d/webpack.config.js#L173) looks nonsensical: when `codeSplitting` is disabled, `splitChunks` should also be completely disabled rather than configured to `chunks: 'async'`.

**Comment by blowery** [comment]
> Our optimization.splitChunks configuration looks nonsensical: when codeSplitting is disabled, splitChunks should also be completely disabled rather than configured to chunks: 'async'.

Agreed, we should just turn it off when code splitting is disabled.

Or disable the ability to turn off code splitting and make everything behave with it on? That feels like a longer road...

**Comment by blowery** [comment]
> The plugin looks at all possible pairings of all the chunks and determines how much code is duplicated between them and how much code could be saved by integrating them together. Then it chooses the most promising pair and merges both chunks into one. That eliminates one chunk. The process is repeated as the optimizeChunks loop continues to run, eliminating just one chunk in each step.

Sounds like a special purpose plugin that forces everything into one chunk might be a way forward? Then we don't have to evaluate candidates, just move everything into the entry chunk it came in from. Not sure how that would handle multiple entry chunks though... 🤔

**Comment by blowery** [comment]
@jsnajdr Are chunks that contain CSS dealt with in any special way?

**Comment by jsnajdr** [comment]
> Or disable the ability to turn off code splitting and make everything behave with it on? That feels like a longer road...

I suspect that if we just disabled code splitting right now, Desktop and Server would just continue working as if nothing happened. There's no reason why dynamic chunk loading shouldn't work out of the box in these environments.

> Sounds like a special purpose plugin that forces everything into one chunk might be a way forward?

Yes, a special-purpose plugin based on the `LimitChunkCountPlugin` could work.

> Not sure how that would handle multiple entry chunks though...

They have some special considerations for chunks that contain entrypoint or the webpack runtime. See the [`Chunk.canBeIntegrated`](https://github.com/webpack/webpack/blob/bbe71d89cb7a8c1cc81ce1e17929d8de2260ff80/lib/Chunk.js#L456-L491) method. If we call that method and respect the result, then we are probably fine.

> Are chunks that contain CSS dealt with in any special way?

I'm not aware of anything. When eliminating chunks, the CSS is still inside the JS module created by the style loader. The extraction happens at a later time, when the chunk graph is finalized and sealed.

Ideally, it should be possible to tell webpack to not split a new chunk when there is a dynamic import. But that seems to be hardcoded without any configurability. Only `/* webpackMode: 'eager' */` can prevent that.

**Comment by blowery** [comment]
cc @loremattei
