### ISSUE TITLE
Checklist: gets stuck for sites with disabled file modifications

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33153]
If the site is managed via some other means than allowed file manipulation via WordPress, the checklist gets stuck on attempting to install VaultPress and Akismet plugins.

<img width="500" alt="Screenshot 2019-05-20 at 13 22 22" src="https://user-images.githubusercontent.com/87168/58015079-ff9ad900-7b02-11e9-87f7-ddcdbab740bb.png">

With status:
```json
{progress: 10, akismet_status: "not_active", vaultpress_status: "not_active"}
```

You can test this by adding `DISALLOW_FILE_MODS` constant to your `mu-plugins` file (on Docker setup in `docker/mu-plugins/`):

```php
define( 'DISALLOW_FILE_MODS', true );
```

We should just show a message as we do in the old flow:

<img width="400" alt="Screenshot 2019-05-20 at 13 22 22" src="https://user-images.githubusercontent.com/87168/58015281-83ed5c00-7b03-11e9-9df2-f77b62a0cd0c.png">

> We can't modify files on your site.
> You will have to set up your plan manually.

With link to https://jetpack.com/support/installing-vaultpress-akismet/

cc @jeffgolenski @johnHackworth

**Comment by simison** [comment]
The flow could look like this:

1.
![image](https://user-images.githubusercontent.com/87168/58015802-d9763880-7b04-11e9-8f38-d812b88adb4e.png)

2. Link to [instructions](https://jetpack.com/support/installing-vaultpress-akismet/)  form the checklist
 — do we need that "key setup" there?
 — see https://github.com/Automattic/wp-calypso/issues/32562

**Comment by jeffgolenski** [comment]
@simison Great find. I love your approach - I just have a couple of verbiage changes.

line 1: "Unfortunately, we can't modify files on your site, so you'll need to set up your plan features manually."
line 2: "Don't worry. We'll quickly guide you through the setup process." 
Button: "Set up features"

I agree with the idea of adding a different graphic, I just want to think on that  a bit to figure out the best one for the job. I thinking changing the language of the button is fine for now though since it can't be ignored - customers have to click it to move forward.

Can we add some tracking to this so we can keep an eye on how many people are experiencing this scenario?

**Comment by simison** [comment]
I had a look at what kind of error states there are in the old flow. The first generic one is the one we'll really want to address in the UI and maybe figure out more granularity to it. The rest are minor.

- **Old flow's copy:** _We can't automatically configure the Akismet plugin. / We can't automatically configure the VaultPress plugin. / We can't automatically configure the Akismet and VaultPress plugins._
    **Event:** `calypso_plans_autoconfig_error`
    **Common?** happens

- **Old flow's copy:** _We can't modify files on your site._
    **Event:** `calypso_plans_autoconfig_error_filemod`
    **Common?** not common but happens

- **Old flow's copy:** _We are unable to set up your plan because your site has an older version of Jetpack. Please upgrade Jetpack._
    **Event:** `calypso_plans_autoconfig_error_jpversion`
    **Common?** not common but happens

- **Old flow's copy:** _Your site is part of a multi-site network, but is not the main network site._
    **Event:** `calypso_plans_autoconfig_error_multisite`
    **Common?** not common but happens

- **Old flow's copy:** _Your site is part of a multi-network._
    **Event:** `calypso_plans_autoconfig_error_multinetwork`
    **Common?** never seems to happen

- **Old flow's copy:** _Jetpack Manage must be enabled for us to auto-configure your %(plan)s plan._
    **Common?** no tracking for this but I think Manage is nowadays always on.

These are all from https://github.com/Automattic/wp-calypso/blob/e052e6e604389350b649e1a2f31cffedd681cb37/client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx
