### ISSUE TITLE
Jetpack performance checklist: site accelerator

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#33168]
We need to add a new task to the post-connection performance checklist, to help users configure photon:

![image](https://user-images.githubusercontent.com/1554855/58028802-c28f1080-7b1b-11e9-9004-805973de1864.png)

The "do it" button should link to /settings/performance/, with a guided tour prompting the user to activate everything in here:

![image](https://user-images.githubusercontent.com/1554855/58029090-2c0f1f00-7b1c-11e9-8fbf-15d4dd08a327.png)

Once the task is completed, the button is replaced by a "configure" link that links to the same page.

This checklist item is available for all the users, including those in the free plan tier.

paObgF-89-p2

**Comment by johnHackworth** [comment]
pinging @jeffgolenski  and @eeeeevon13  for the copy on the guided tour

**Comment by sirreal** [comment]
#33571 added the task. Assigned to @ockham for the tour.

**Comment by simison** [comment]
@jeffgolenski says:

>the majority of people who come through our checklist will want to enable both. It’s only the more technical folks who have special configurations that may or may not want both of these together, right? - I’d like to say that the task will complete when we see they’ve clicked “do it” and enabled at least one. they can always revisit and change it regardless of the task status

p1559913554122900-slack-luna
