### ISSUE TITLE
Full Site Editing: deploy Twenty Nineteen child theme to WP.com [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#33164]
After a child theme is created we should find a way to deploy it only for a specific set of sites, similar to the plugin in https://github.com/Automattic/wp-calypso/issues/33163.

If possible we should also tie it's activation to the activation of the plugin - they should both always been enabled or disabled at the same time.

This task depends on: https://github.com/Automattic/wp-calypso/issues/33160

**Comment by apeatling** [comment]
@vindl I think this one is done and we can close?

**Comment by apeatling** [comment]
Reopen if that's wrong.
