### ISSUE TITLE
 Jetpack performance checklist: Lazy loading images

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#33169]
We need to add a new task to the post-connection performance checklist, to help users configure lazy loading images:

![image](https://user-images.githubusercontent.com/1554855/58029259-801a0380-7b1c-11e9-9348-4335ea0b7306.png)

The "do it" button should link to /settings/performance/, with a guided tour prompting the user to activate this setting:

![image](https://user-images.githubusercontent.com/1554855/58029288-8c05c580-7b1c-11e9-92be-b541853d5623.png)

Once the task is completed, the button is replaced by a "upload images" link that links to the media section of calypso.

This item is available for all the users, including those in the free plan.

paObgF-89-p2

**Comment by johnHackworth** [comment]
pinging @jeffgolenski  and @eeeeevon13  for the copy on the guided tour

**Comment by sirreal** [comment]
#33571 added the task. Assigned to @ockham for the tour.
