### ISSUE TITLE
Jetpack performance checklist: Video hosting

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#33170]
We need to add a new task to the post-connection performance checklist, to help users configure their video hosting:

![image](https://user-images.githubusercontent.com/1554855/58029408-c96a5300-7b1c-11e9-9964-f0e54f7c366f.png)

The "do it" button should link to /settings/performance/, with a guided tour prompting the user to activate this setting:

image
![image](https://user-images.githubusercontent.com/1554855/58029431-d5eeab80-7b1c-11e9-91d0-e197a4438353.png)

Once the task is completed, the button is replaced by an "upload videos" link that links to the media section of calypso.

This item is available only for users on premium and professional plans (monthly and yearly)

paObgF-89-p2

**Comment by johnHackworth** [comment]
pinging @jeffgolenski  and @eeeeevon13  for the copy on the guided tour

**Comment by sirreal** [comment]
#33571 added the task. Assigned to @ockham for the tour.
