### ISSUE TITLE
Jetpack performance checklist: Enhaced search

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#33171]
We need to add a new task to the post-connection performance checklist, to help users configure elastic search

![image](https://user-images.githubusercontent.com/1554855/58029702-6a590e00-7b1d-11e9-95e9-e039e89aff4b.png)

The "do it" button should link to /settings/performance/, with a guided tour prompting the user to activate this setting:

![image](https://user-images.githubusercontent.com/1554855/58029719-7513a300-7b1d-11e9-820f-f9a804584062.png)

Once the task is completed, the button is replaced by an "add search widget" links to the wp.com customizer

This item is visible only for users with the professional plan

paObgF-89-p2

**Comment by johnHackworth** [comment]
pinging @jeffgolenski  and @eeeeevon13  for the copy on the guided tour

**Comment by jeffgolenski** [comment]
@johnHackworth for all the performance-related checklist item guided tours, please just add some basic text for now and we'll refine them after implementation. Same goes for all tasks. cc @simison @sirreal @ockham - thank you all!

**Comment by sirreal** [comment]
#33571 added the task. Assigned to @ockham for the tour.
