### ISSUE TITLE
Myanmar not included in country list on checkout page

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#33188]
Myanmar (Burma) is not included in the country list on the checkout page.

#### Steps to reproduce
1. Go to My Site > [Plans](https://wordpress.com/plans)
2. Add a plan to the cart
3. Click on the cart icon > [Checkout](https://wordpress.com/checkout/)
4. Click Country and scroll down to the `M` section

#### What I expected

Myanmar to be included in the country list.

#### What happened instead

- Myanmar was not included in the country list
- I checked for Burma and that isn't included either
- Myanmar _is_ listed in the domain contact information form

#### Browser / OS version

Non-browser specific issue.

#### Screenshot / Video

![myanmar-checkout-m](https://user-images.githubusercontent.com/11627765/58081155-79d36800-7bac-11e9-9003-c02e9290c251.jpg)

#### Context / Source

#user-report, #manual-testing

Reported: https://en.forums.wordpress.com/topic/dont-find-country-in-checkout-page/

**Comment by supernovia** [comment]
Hi, any update on this? We've got a user who can't seem to check out here:
https://en.forums.wordpress.com/topic/buying-wordpress-popular-premium-package/

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
This was addressed in D39079-code. Closing.
