### ISSUE TITLE
Gutenberg back button missing on small screen

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#33182]
#### Steps to reproduce
1. Starting at URL: Visit wordpress.com on mobile device
2. Go to a site and edit a post or page

#### What I expected
I expected to see a back button to exit Gutenberg and go back to my posts

#### What happened instead
The back button was missing

#### Browser / OS version
Chrome on Google Pixel 2

#### Screenshot / Video: Desktop
<img width="904" alt="Screen Shot 2019-05-20 at 10 16 44 PM" src="https://user-images.githubusercontent.com/6981253/58063751-81afef80-7b4d-11e9-9a3f-503ad06b54a6.png">

#### Screenshot / Video: Mobile
<img width="499" alt="Screen Shot 2019-05-20 at 10 17 01 PM" src="https://user-images.githubusercontent.com/6981253/58063759-8b395780-7b4d-11e9-8028-9547125bf2f4.png">

#### Context / Source
I was trying to edit a post on my phone. After saving, I wanted to edit another post and I couldn't get back without using my Android back button. 

#dogfooding

**Comment by simison** [comment]
cc @gwwar

**Comment by cathymcbride** [comment]
Closing....
