### ISSUE TITLE
Full Site Editing: Polish theme and plugin for release

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#33190]
Let's use this issue to track all the small things that we need to take care before launching the first iteration of Full Site Editing:

- [ ] Fill all the plugin and theme informations (see for example [Jetpack](https://github.com/Automattic/jetpack/blob/5dfd71c84c89a4410d94804d07c1beab180c5372/jetpack.php#L3-L13)).
- [ ] Only allow `page` post types to be published.
- [ ] Pre-fill `wp_template_part_type` with Header and Footer, and remove it from the UI.
- [ ] Pre-fill `wp_template_part` with default header and footer, and prevent deleting them.
- [ ] Remove inherited Twenty Nineteen functions and options that might conflict with the Blank Theme.
- [ ] Anything else?

**Comment by vindl** [comment]
Closing since most of these tasks have already been handled in other issues, and some are no longer relevant since we don't need a custom/blank theme.
