### ISSUE TITLE
Me: Send SMS Code has no follow up indicator

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#3319]
I went to https://wordpress.com/me to change something and got the 2FA prompt. I chose to have it send a code via SMS, but when I pressed the button nothing happened. The SMS button became disabled:

![sms-code](https://cloud.githubusercontent.com/assets/5835847/13059114/9b35f3c4-d3ed-11e5-8f09-1ddbf3554944.png)

We should probably add a notice here to alert the user that yes, the message is on its way or no, an error has occurred.

**Comment by hoverduck** [comment]
07Apr15 Bug Scrub

Confirmed this is still an issue.  And for future reference, to force that popup to display, delete the "twostep_auth" cookie for wordpress.com

**Comment by BandonRandon** [comment]
Currently still an issue. 

Steps to Reproduce:
1) Delete the `twostep_auth` cookie
2) [re]load WordPress.com/me
3) Click on "Send SMS Code"
4) Notice no feedback given although a SMS is sent. 

Action: Changing from Bug to Enhancement
