### ISSUE TITLE
Programming error when changing site address

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#33192]
Trying to change the site address results in a programming error.

#### Steps to reproduce
1. Go to My Site > Manage > Domains
2. Click on the address (free WordPress.com subdomain)
3. Scroll down to _Change Site Address_
4. Enter a new address

#### What I expected

To be able to click the "Change site address" button.

#### What happened instead

The "Change site address" button flashed up as clickable for a second and then an error appeared:

> Programming error: the type is a required value and cannot be empty

I tested this on sites with and without a custom domain but the behaviour was the same on both.

#### Browser / OS version

Doesn't appear to be browser specific — replicated in Chrome, Firefox and Safari.

#### Screenshot / Video

![change-address-1](https://user-images.githubusercontent.com/11627765/58092467-19502500-7bc4-11e9-9dc9-79079b91838d.jpg)

#### Context / Source

#manual-testing
#user-report

Report: https://en.forums.wordpress.com/topic/programming-error-displayed-upon-changing-the-domain-name/

**Comment by gemmagarner** [comment]
Another report: https://en.forums.wordpress.com/topic/changing-site-address-23/

**Comment by gemmagarner** [comment]
https://en.forums.wordpress.com/topic/problem-with-changing-site-address/

**Comment by gemmagarner** [comment]
https://en.forums.wordpress.com/topic/changing-domain-name-error/

**Comment by gemmagarner** [comment]
https://en.forums.wordpress.com/topic/changing-domain-name-error/

**Comment by macmanx2** [comment]
Per Slack, this should be fixed now. I've replied to the listed threads and will close upon confirmation.

**Comment by macmanx2** [comment]
Confirmed fixed!
