### ISSUE TITLE
Store: Update sidebar to use the new sidebar design pattern 

### ISSUE THREAD

**Issue by kyleaparker** [Automattic/wp-calypso#33205]
The sidebar was recently updated on WP.com. Action buttons were removed and items were reorganized into collapsible menus:

<img width="333" alt="Stats ‹ Kylea Parker — WordPress com 2019-05-21 11-57-25" src="https://user-images.githubusercontent.com/712873/58111607-c70d0500-7bbf-11e9-879b-a542d4b602b9.png">

When you click through to Store a new window is loaded. The sidebar for store is using the old pattern where actions are included in the sidebar, in this case the action is "Add" on the Products and Promotions menu items. 

<img width="393" alt="Store ‹ Kylea Parker — WordPress com 2019-05-21 11-57-35" src="https://user-images.githubusercontent.com/712873/58111623-d2603080-7bbf-11e9-99c7-db1f30b0fac3.png">

Some enhancements we could make to this: 
- Remove the "Add" actions from the sidebar
- Update the icons so they are consistent with the rest of WP.com, for example the Settings icon in Store is slightly different to the Manage icon in WP.com 
- Make sure the spacing and alignment is consistent 
- All of these items could potentially be included under the main "Store" heading rather than taking the user away to a new screen. I'm unsure on the technical feasibility of this

**Comment by danielwrobert** [comment]
> Remove the "Add" actions from the sidebar

TT @jameskoster at The Bottle Pick-Up Festival and he advised that he has already removed the "Add" actions from the sidebar in 888528f.

> All of these items could potentially be included under the main "Store" heading rather than taking the user away to a new screen. I'm unsure on the technical feasibility of this

There is [ongoing work](https://core.trac.wordpress.org/ticket/47012) with navigation for WP Core and Plugins so we should wait to see the outcome there before making any larger changes in this.

> - Update the icons so they are consistent with the rest of WP.com, for example the Settings icon in Store is slightly different to the Manage icon in WP.com
> - Make sure the spacing and alignment is consistent

These would be good to resolve for this ticket, I will work on them.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
