### ISSUE TITLE
Store: Fix styling on Product description editor quote button is misaligned

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#33203]
Navigate to a product by going to Store > Products > Add New (Or just choose a product in the list) 

Notice the "quote" button in the product description editor is misaligned:

<img width="653" alt="Screen Shot 2019-05-21 at 11 38 42 AM" src="https://user-images.githubusercontent.com/5835847/58110338-56fd7f80-7bbd-11e9-80ba-6ae22bac6419.png">

**Comment by kellychoffman** [comment]
Not able to consistently replicate this.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
