### ISSUE TITLE
People Management: user removal confirmation message issues

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#3322]
The confirmation message when removing a user from a site overlaps the logo, is not full width, and shifted to the right of the page. 
Running Chrome 48, OSX 10.11.3

![screen shot 2016-02-12 at 12 38 37 pm](https://cloud.githubusercontent.com/assets/16867830/13060769/cbb18612-d401-11e5-957b-60670c608108.png)

**Comment by lancewillett** [comment]
I think this is the intentional design now. The messages are no longer full-width.
