### ISSUE TITLE
Activating Jetpack Monitor reports failure in Calypso, but succeeds on site

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#33237]
#### Steps to reproduce
1. With a site that does not have monitor activated
2. Go to https://wordpress.com/settings/security/[your site domain]
3. Try to activate monitor - you will see an error like `There was a problem saving your changes. Please try again.`
4. Go to http://yoursitedomain.com/wp-admin/admin.php?page=jetpack#/settings
4. See that Monitor is now active

#### What I expected

No error in Calypso if module was correctly activated

#### What happened instead

Module was activated but Calypso reported an error

#### Browser / OS version

Chrome 74 on macOS Mojave 10.14.4

#### Screenshot / Video

https://cloudup.com/cRbZFW2Zmsw

**Comment by kraftbj** [comment]
The request response from the API was `{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"data":{"code":"success","message":"The requested Jetpack module was activated."}}}` for me, with the error, so seems that something in Calypso isn't handling the response as expected.

**Comment by simison** [comment]
Cc @Automattic/luna in case this is a regression related to Jetpack checklist work.

**Comment by sirreal** [comment]
I don't see how it could be related, but with the timing we should review changes from #33193

**Comment by ockham** [comment]
I can repro in production, but curiously not in local dev. Will try to dig deeper.

**Comment by ockham** [comment]
Also reproducible in `wpcalypso`. Looking at the browser's Redux panel there, I see

> error: "Cannot read property 'tasks' of undefined"

![image](https://user-images.githubusercontent.com/96308/58225490-0c5a3f80-7d44-11e9-9ffa-655c9ffd13f0.png)

**Comment by ockham** [comment]
Okay, that probably just means that `state.checklist[ siteId ]` isn't present for the given `siteId` since it hasn't been initialised yet (since we're visiting the settings page before ever loading the checklist).

**Comment by ockham** [comment]
Fix coming right up.
