### ISSUE TITLE
Full Site Editing: Move related block plugins to the FSE plugin [1]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33239]
Let's group related a8c feature blocks, and other plugins into the Full Site Editor plugin. https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing

See also: paAmJe-nW-p2

**Comment by getdave** [comment]
We've made good progress on this today https://github.com/Automattic/wp-calypso/pull/33250/
