### ISSUE TITLE
Checklist: Targeted placement step is mispositioned when window is too wide

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33247]
Guided tour popup for "tagline" checklist item in a wrong place.

#### Steps to reproduce
1. Starting at URL: have an existing simple site
2. Go to checklist
3. Click to do the tagline task
4. Write in tagline
5 See:
    <img width="1139" alt="Screenshot 2019-05-23 at 08 38 06" src="https://user-images.githubusercontent.com/87168/58228124-43295900-7d36-11e9-90f1-471749437d52.png">

#### Browser / OS version
Latest Chrome
Browser width ~1640px

cc @Automattic/zelda

**Comment by donpark** [comment]
Confirmed that misplacement happens when window is wide (>= 1600px).

**Comment by donpark** [comment]
Based on initial survey of the code, problem appears to be in `getStepPlacement()` function in [client/layout/guided-tours/positioning.js](https://github.com/Automattic/wp-calypso/blob/fca5b51e923b69a113a294e3da58f49aaa9ebafb/client/layout/guided-tours/positioning.js#L137) which calculates placement of the step.

Same function also misbehaves with scrolling.
