### ISSUE TITLE
Store illustrations using the old color scheme

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33259]
These are the examples I found:

During on-boarding:

![1](https://cldup.com/fpWl-9pDPM-3000x3000.png)

![2](https://cldup.com/ETBpnvjUZC-3000x3000.png)

And on the Dashboard:

![3](https://cldup.com/fFWFIHHvQX-3000x3000.png)

**Comment by garymurray** [comment]
@jameskoster I checked in with @drw158 - it appears these illustrations are updated as per the latest from the brand work on WP.com.

Is their an example of a colour use elsewhere you think these should be making use of?

**Comment by garymurray** [comment]
After chatting with @porada the illustrations during onboarding are correct - although the grey could be a little lighter perhaps. But the ones on the dashboard are not using the correct colour studio colours. I will leave this open to fix during the design meetup.

**Comment by garymurray** [comment]
Here is a proposal for changing the colours of the existing illustrations for Store on WP.com located here: https://github.com/Automattic/wp-calypso/tree/master/static/images/extensions/woocommerce from the old blue of WordPress.com to the new colours available in Colour Studio: https://automattic.github.io/color-studio/

![Before-After](https://user-images.githubusercontent.com/10805911/59358943-55b60300-8ce2-11e9-8fc8-ce68124b9971.jpg)

The process I used was:

- Pulled out the colours used in the original illustrations (there were about 8 colours used)
- Found the best possible matches for these colours in Colour Studio
- Compared this to an existing illustration that had been updated: https://wordpress.com/calypso/images/illustrations/illustration-empty-results.svg to confirm they were correct

@jameskoster can you take a quick glance over these for anything that jumps out that I missed?

One possible issue I am aware of is the contrast between the hand and circle background is not the greatest in the last illustration (the lady with the wrench) - but it was like this in the before illustration too.

Then - question to @jameskoster and @drw158 - should I create components out of these for use in Figma - I have worked in Figma to update the colours, so perhaps we should have a library of the illustrations available as components for designers to pull from?

**Comment by jameskoster** [comment]
Nice! Yeah, the circle "background" could perhaps be a little lighter to increase the hand contrast. I'm not sure if we're using this pattern elsewhere in Calypso but I think not, so that should be a safe change.

After the recent brand work, I'm not sure of the intended lifespan of this illustration set. If they're here to stay then a Figma lib sounds like a great idea.
