### ISSUE TITLE
WooCommerce+Jetpack connect flow has differing landing pages at the end

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33257]
#### Steps to reproduce
1. Have a site with WooCommerce but no Jetpack installed, e.g.: https://jurassic.ninja/create/?nojetpack&woocommerce
2. Start with the wizzard
    <img width="300" alt="Screenshot 2019-05-23 at 12 27 28" src="https://user-images.githubusercontent.com/87168/58241704-2a30a000-7d56-11e9-8202-ec6672a56f06.png">
3. Fill in the infos/disable them in steps
4. In Jetpack connect step, press "Continue with Jetpack"
    <img width="400" alt="Screenshot 2019-05-23 at 09 12 33" src="https://user-images.githubusercontent.com/87168/58244535-73372300-7d5b-11e9-820e-f2640795e851.png">
5. You'll land in WordPress.com: test as authenticated and un-authenticated users.

    - When you are authenticated already, you'll eventually end up in wp-admin's Jetpack dashboard, skipping the "ready" woo step visible in previous screenshot's breadcrumps navi:

        <img width="500" alt="Screenshot 2019-05-23 at 09 14 37" src="https://user-images.githubusercontent.com/87168/58244593-8ea22e00-7d5b-11e9-83d3-8b8253ad75b7.png">

    - When you were not authenticated and login during the connection flow, you'll land in "ready" step in woo flow:

        <img width="500" alt="Screenshot 2019-05-23 at 09 18 42" src="https://user-images.githubusercontent.com/87168/58244648-b42f3780-7d5b-11e9-9369-2818f5e360c6.png">

Feels like authenticated flow where you land in Jetpack dash is a bug.

I didn't test what happens if you step aside the from the flow and either create or recover an account.

#### What I expected

Continue with Woo onboarding during these steps.

#### What happened instead

Landed in Jetpack dash.

# E2E tests

There are existing E2E tests [for this flow](https://github.com/Automattic/wp-calypso/blob/0580a07a70dc2e8bcfd2e27cc65daadd94a2befc/test/e2e/specs-jetpack-calypso/wp-jetpack-connect-spec.js#L370) but [I had to disable](https://github.com/Automattic/wp-calypso/pull/33232) the Jetpack connect flow parts today because they were consistently failing/broken (the test was broken, not the flow).

Conversation p1558593446013600-slack-e2e-testing-discuss

Looks like the test for the final step (that this bug report is about) had been disabled already previously: https://github.com/Automattic/wp-calypso/blob/0580a07a70dc2e8bcfd2e27cc65daadd94a2befc/test/e2e/specs-jetpack-calypso/wp-jetpack-connect-spec.js#L470-L473

Conversation p1556635263170900-slack-proton

**Comment by brbrr** [comment]
FWIW This issue was reported in https://github.com/woocommerce/woocommerce/issues/23560

**Comment by simison** [comment]
Ah cool. Thanks!

Since the code-problem is actually in Calypso it feels to me more natural to have it here but I'll lave it to @claudiosanches @kloon to triage and re-open if they feel so! Meanwhile, I'll close this. :-)

**Comment by kloon** [comment]
@simison thanks, we were not sure if the issue was here or on the WooCommerce.com side. We closed the issue out on the WooCommerce core side already and opened an issue on the WooCommerce.com side since we thought the issue might be from there, but since you are saying this is actually an issue on Calypso side I would agree this needs to be fixed in here then.

Reopening so this can be fixed.

**Comment by simison** [comment]
I could be wrong but I'm assuming there's a bug somewhere in Calypso flows that shortcuts the woo onboarding flow and throws people to Jetpack dash instead.

Is someone from Woo teams owning this bug now? Happy to do testing when there's a PR.

Would be ace to get those E2E tests enabled again, too!

**Comment by kloon** [comment]
@simison nobody I know of that is currently working on this. We don't have anyone working on Calypso from Woo side, and I for one would not know where to start looking in Calypso. Would appreciate some help from someone familiar with this to assist.
