### ISSUE TITLE
Seamlessly integrate Store nav with main nav

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33263]
Currently, clicking the Store menu item opens up a separate navigational experience. We use this awkward pattern to allow folks to "return" to general site management:

![1](https://cldup.com/mQd00i_qLf-3000x3000.png).

With the new navigation structure we've an opportunity to integrate the Store menu seamlessly. IE:

![2](https://cldup.com/ntPNiktSFl-3000x3000.png)

There are some additional considerations here. Store peruses an "app bar" component to house a breadcrumb / primary action which we'd need to cater for.

There's a discussion to be had around whether Store settings should live in the main site settings or not.

If https://github.com/Automattic/wp-calypso/issues/33205 is a Birthday Cake, this could be considered a Wedding Cake.

**Comment by scottysimpson** [comment]
Hey @jameskoster curious about this expand solution and how it will solve the nested navigation needs of wc? This was brought to my attention from @josemarques recent post https://woocommercep2.wordpress.com/2019/05/22/woocommerce-admin-next-steps/

**Comment by jameskoster** [comment]
@scottysimpson I don't think it would solve that problem.

But Store is unique because it isn't the _full_ WooCommerce experience. It's significantly stripped back and there are no extensions. There's _potential_ for it to integrate in a way that the full-fat WooCommerce probably couldn't, as in Store we've no need for the nav to scale in the same way. 

Certainly it would require exploration and discussion.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
