### ISSUE TITLE
Store - Editing the fallback shipping Zone during on-boarding doesn't work

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33269]
#### Steps to reproduce
1. Initiate Store on-boarding
2. Click "Review shipping" button in on-boarding task list
3. Click "Edit" button in the "Locations not covered by your other zones" Zone

#### What I expected
To edit the zone

#### What happened instead
The page refreshed

#### Button in question

![1](https://cldup.com/JPJA-aYGwQ-3000x3000.png)

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
