### ISSUE TITLE
Store on-boarding - Add an "Add another product" link to product setup task

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33266]
The first task in the Store on-boarding task list is to add a product which sends folks to the add product screen. Once a product has been added and you return to the Dashboard this is what is displayed:

![1](https://cldup.com/t4SSNN--B3-3000x3000.png)

While it's possible to add another product by clicking View products -> Add product, it might be nice to include a direct link here to add another product and save a click.

**Comment by jeffgolenski** [comment]
Related clean up I'll try to tackle for bottle pickup. 

The selected state of the store links in the sidebar need some color adjusting

![Screen Shot 2019-06-06 at 12 52 55 PM](https://user-images.githubusercontent.com/214813/59051164-35a5c000-885a-11e9-8bfe-98918f6fd66e.png)
