### ISSUE TITLE
Store - Add product card spacing

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33265]
The spacing between the "Additional details" and "Category" cards on the add product screen is inconsistent with the spacing between other cards.

![1](https://cldup.com/etyLfYp1vI-3000x3000.png)

**Comment by wrightcj03** [comment]
#### Steps to reproduce
1.  Add a product
2. Expand "Add Additional Details" card
3. Hover cursor over "Write" button in navigation

I think this is related to a bigger issue that causes the page to jump and left-side nav to become partially obscured, in addition to breaking the spacing on the additional details card so closing this issue and re-reporting here: https://github.com/Automattic/wp-calypso/issues/33835

cc @davemart-in
