### ISSUE TITLE
Sidebar: WP Admin Jetpack link is incorrect

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#33277]
I believe this may have been introduced in #32790 (cc @sirreal)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/nnn where nnn is a Jetpack site.
2. Click on the WP Admin link at the bottom of the sidebar.
3. You'll be redirected to https://nnn/wp-admin/?page=jetpack#/my-plan

This link is incorrect. While it loads the right page, the WordPress navigation does not support it:

![image](https://user-images.githubusercontent.com/426388/58255639-bc906e00-7d6d-11e9-9c2c-000fc4b5dc7c.png)

It should be https://nnn/wp-admin/admin.php?page=jetpack#/my-plan

![image](https://user-images.githubusercontent.com/426388/58255678-cfa33e00-7d6d-11e9-8b52-a42c5a12a1a6.png)

**Comment by sirreal** [comment]
CC @Automattic/luna

**Comment by simison** [comment]
there are two links in calypso, both might need looking at: 


<img width="700" alt="Screenshot 2019-05-23 at 17 16 19" src="https://user-images.githubusercontent.com/87168/58260166-a50db100-7d7e-11e9-83a2-4b87a00a3aa7.png">

**Comment by ockham** [comment]
I'll take a look

**Comment by ockham** [comment]
Fix: #33299
