### ISSUE TITLE
Store - Stripe setup - segmented control is confusing

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33271]
When configuring Stripe in store you're presented with the following Dialog:

![1](https://cldup.com/MyfoW2ayI4.gif)

It's not really clear to me how the two options in the segmented control impact my next action. In particular the "New Stripe account" option. Will this create an account for me? Or do I need to create a new account myself? If so, what will happen when I click the "Connect" button?

I think we should explore clarifying these options.

**Comment by scalarbane2** [comment]
Hi, @jameskoster I'm trying to replicate this issue to get a screenshot, but it seems I can't find my way around it.  

Can you please upload a screenshot of this page without Setup?

**Comment by scalarbane2** [comment]
![On Hover](https://user-images.githubusercontent.com/50745054/60897898-b6dce200-a260-11e9-8589-9ce86fe1049f.png)

This is the design solution I could come up with, replacing the segmented control with radio buttons which makes it easier for the user they are to select one of the options. Let me know what you think @jameskoster @sixhours @lcollette

**Comment by jameskoster** [comment]
I think that looks pretty good @scalarbane2, I like the label change on the account creation option :)

**Comment by lcollette** [comment]
I agree with @jameskoster. Looks good!
