### ISSUE TITLE
Store - it's possible to enable an un-configured payment method

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33272]
#### Steps to reproduce
1. Navigate to Payment settings in Store
2. Enable an un-configured payment method
3. Save settings

#### What I expected
To be told to configure the payment method I enabled

#### What happened instead
Nothing

#### Screenshot / Video
![1](https://cldup.com/hNbVjHH9Qr-3000x3000.png)

In this screenshot the bank transfer payment method is enabled, but hasn't been configured.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
