### ISSUE TITLE
Store - variation selection pattern is confusing

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33275]
#### Steps to reproduce
1. Have at least 1 variable product at your store
2. Create a new promotion
3. Specify that the promotion applies to a variable product
4. Click "Select variations" button
5. Choose a variation

You're presented with the following UI:

![1](https://cldup.com/OBRcMAw-Or-3000x3000.png)

It is not intuitive to use. 

Selecting options from the dropdown will form a table of variations with corresponding checkboxes. It would seem that this step could be skipped and simply display the variation table. Like so:

![2](https://cldup.com/rPuBvFxuno-3000x3000.png)

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
