### ISSUE TITLE
Store - service packages aren't loading

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33270]
#### Steps to reproduce
1. Navigate to Store shipping settings
2. Scroll to the bottom of the screen, find the "Packages" section and click "Add package" button
3. Click the "Service package" option in the segmented control

#### What I expected
Service packages to appear

#### What happened instead
Nothing

#### Screenshot / Video

![1](https://cldup.com/bsy06TDij6-3000x3000.png)

**Comment by cathymcbride** [comment]
Closing due to staleness. Feel free to re-open if you disagree!
