### ISSUE TITLE
Page Template Selector: Visual style iteration

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#33279]
Collected feedback about our design: 

> Have you tried just leaving this at the standard modal size?
> —@mtias

I can't find the quote now but I believe @iamtakashi suggested transforming template tile into buttons which will immediately close the dialog and apply the template, without additional confirmation step. To make things more simple, he also suggested putting the "Blank" option among other templates and completely getting rid of all buttons/links under the template list.

**Comment by marekhrabe** [comment]
#33318 replaces radio selector with buttons. We should add `cursor: pointer` for it and also update the hover style. No other place uses blurred box-shadow as a hover state. 

The closest piece of UI to our usage is the Style selector and I think we should copy its hover/active states for our plugin too. At least make border widths the same and remove blur in favor of changing border color.

<img width="280" alt="Screenshot 2019-05-27 at 14 04 37" src="https://user-images.githubusercontent.com/156676/58418571-63378000-8088-11e9-9627-2306adfa076a.png">

**Comment by frontdevde** [comment]
Solved by https://github.com/Automattic/wp-calypso/pull/33358 and https://github.com/Automattic/wp-calypso/pull/33318.
