### ISSUE TITLE
Store on-boarding - Review taxes link in task list takes me to a blank screen

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33274]
#### Steps to reproduce
1. Initiate store on-boarding
2. Click "Review tax" link

#### What I expected
To view tax settings

#### What happened instead
I was taken to a blank screen

**Comment by lcollette** [comment]
I'm not able to reproduce this bug, @jameskoster. Can you confirm you're still encountering it?

**Comment by davemart-in** [comment]
> I'm not able to reproduce this bug, @jameskoster. Can you confirm you're still encountering it?

Same. Here's what I'm seeing: https://cl.ly/5f982210c027
