### ISSUE TITLE
(3days) Make new API endpoint for vertical templates

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33282]
- [x] This API will return both list of templates and also their full content
  - > We could have a `get_item()` method and loop through that in `get_items()`, which should be pretty future proof

- [x] It will accept an argument of "vertical id", example value `p12v30`. If the vertical is not provided, we will fallback to pull templates from a generic site as explained in https://github.com/Automattic/starter-page-templates/issues/20

- [x] This endpoint should be publicly available and not tied to site_id

- [x] API response should also include the full vertical name so we can use it on frontend: https://github.com/Automattic/wp-calypso/issues/33280#issuecomment-495211686 (eg: for `p12v30`, the name is `"Website Designer"` as per all-verticals.php)

**Comment by obenland** [comment]
In its current form D28635-code satisfies 3/4 of the requirements. Not sure if we need to return full post objects or if we should customize it somehow. 

@Automattic/ajax Do we want anything other than the vertical name in there as well? The name is only relevant when we return all templates I assume?

**Comment by marekhrabe** [comment]
Just accepted D28635-code
