### ISSUE TITLE
Jetpack checklist: ensure people know how to find back to wp-admin

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33285]
Ensure folks can find their way back to wp-admin from the connect/onboarding flow.

There are currently two ways to get back:

<img width="700" alt="Screenshot 2019-05-23 at 17 16 19" src="https://user-images.githubusercontent.com/87168/58260166-a50db100-7d7e-11e9-83a2-4b87a00a3aa7.png">

Could we as an MVP add some copy to some of these views and tell how to get back to wp-admin:

<img width="700" alt="Screenshot 2019-05-23 at 17 14 40" src="https://user-images.githubusercontent.com/87168/58260168-a5a64780-7d7e-11e9-9dd7-80c6faf057c6.png">
<img width="700" alt="Screenshot 2019-05-23 at 17 14 31" src="https://user-images.githubusercontent.com/87168/58260170-a5a64780-7d7e-11e9-87f9-c49041079cef.png">
<img width="700" alt="Screenshot 2019-05-23 at 17 14 23" src="https://user-images.githubusercontent.com/87168/58260171-a5a64780-7d7e-11e9-9f68-8efe28729dbf.png">

Would it be easy to add a guided tour at the beginning of the checklist flow pointing out how to get back to wp-admin:

![image](https://user-images.githubusercontent.com/87168/58260274-d71f1300-7d7e-11e9-9bdd-7a92efe21c04.png)

**Comment by jeffgolenski** [comment]
@simison for the guided tour, let's break it down into two steps. After the thank you page finishes loading and customers click "continue" we'll do this:

step 1: Guided tour modal pointing to the checklist saying: "This is your security [and performance] checklist that'll help you quickly setup Jetpack. Pick and choose the features that you want." - [Got it button]
step 2: "After you're done setting everything up, you can return to your WordPress admin here or continue using the WordPress.com dashboard." [got it button} (this one will point to the wp-admin link)

I'll do a quick mockup for the MVP in a second....

**Comment by jeffgolenski** [comment]
@simison As an MVP let's explore quickly implementing this verbiage for both free and paid plans:

> This is your new WordPress.com dashboard. You can manage your site here, or return to your self-hosted WordPress dashboard using the link at the bottom of your checklist.

![Screen Shot 2019-05-23 at 4 59 35 PM](https://user-images.githubusercontent.com/214813/58286184-2b74c380-7d7c-11e9-853a-23a34d70553b.png)

**Comment by simison** [comment]
Bringing over https://github.com/Automattic/wp-calypso/pull/33300#issuecomment-495512529 by @sirreal:

> Given that this is going into the post-provisioning views, we could just make a clickable link to WP Admin right in the card.
