### ISSUE TITLE
Reader copy is vertically misaligned with reader images

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#33292]
## URL

https://wordpress.com/

## Screenshot

![](https://d1jfzjx68gj8xs.cloudfront.net/items/2n0X433U0E1r0p2l453Z/%5B2864dc7b7a3635ec16959cf11e95410e%5D_Screen%2520Shot%25202019-05-23%2520at%25204.29.51%2520PM.png)

## Issue

The copy on the right does not appear to be vertically aligned with the image on the left.

## Expected

The copy (headline, description, and links) should all move up a couple of pixels to align with the image on the left.

**Comment by jordesign** [comment]
Working on a PR since this seems like it didn't end up getting worked on at the Design Meetup. Hope that's ok with you @jancavan ?

**Comment by jancavan** [comment]
@jordesign I missed that one. Sure, thanks for picking that up.
