### ISSUE TITLE
Update copy for mobile app promo

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#33290]
## URL

https://wordpress.com/

## Screenshot

![](https://d1jfzjx68gj8xs.cloudfront.net/items/1l1i2W381s0Z3A081n0u/%5Bc416301fa410afafaa70ffecd80b02b9%5D_Screen%2520Shot%25202019-05-23%2520at%25204.20.50%2520PM.png)

## Actual

"download app for mobile" feels a tad robotic.

## Proposal

Perhaps we could change this to something like "Download the mobile app"

**Comment by pablohoneyhoney** [comment]
I can't figure out where or when exactly this banner shows up.
