### ISSUE TITLE
Full Site Editing: Atomic Deploy Process

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33296]
Let's define how we'll deploy the full-site-editing-plugin internally for Simple and Atomic sites.

https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing

Requirements:
- Some API endpoint that can return if a new plugin version is available
- Plugin artifacts can be downloaded without manual steps
- Coordinate with @jmdodd on any other Atomic requirements. (Please update this issue or p2)

Suggestions:
- Circle CI workflows may be updated to create a plugin artifact that can be downloaded via API

See also comment in paAmJe-pm-p2

**Comment by obenland** [comment]
Linking back to my question in the canonical place for this discussion p1558679127003400-slack-atomic-plugins-tmp

**Comment by gwwar** [comment]
Closing this out, since we don't look like we're moving forward with this.
