### ISSUE TITLE
(3P) FSE: Test small screens, browsers other than Chrome

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33304]
Test issues on existing UX and feedback to Takashi so these can be resolved early.

Still to do:

- [x] ~scrollable area is missing `-webkit-overflow-scrolling: touch;`~ (this would require applying to the `body` and it's a webkit only feature. 
- [x] stress test layout/design with more/less Templates (esp. on mobile). Currently, idealised x3 Templates isn't sufficient
- [x] The buttons need to have their `appearance` reset. There is [currently a default browser inherited background](https://user-images.githubusercontent.com/444434/58618696-2f906c00-82bb-11e9-93d1-0e29ed0623b8.png) on all the Template buttons on mobile devices.

**Comment by getdave** [comment]
Also, note these issues

https://github.com/Automattic/starter-page-templates/issues/16#issuecomment-494913017

**Comment by getdave** [comment]
# Issues

#### Template selection on mobile devices is difficult

![Screen Capture on 2019-05-24 at 14-47-06](https://user-images.githubusercontent.com/444434/58332419-1149ec80-7e33-11e9-9cc3-0e398004c9b6.gif)

* Scrolling within a modal on touch devices is not a nice experience
* Once selected you to have to scroll down to find the button to confirm
* Difficult to skip to "Blank Page" option - you have to scroll down
* Difficult to comprehend all the possible options

**Comment by obenland** [comment]
Thanks for that screenshot!

With "Blank Page" becoming a selection itself, could we make all of these selectors button elements that close the modal? That would solve the scroll-to-confirm issue and save us a (unnecessary) click.

**Comment by frontdevde** [comment]
Should "Blank Page" be the first option so it's easy on mobile to remove the modal without making a selection?

**Comment by getdave** [comment]
Agreed. 

The other point is still valid - we still need to scroll to see all the other Templates. It does feel like a nice experience...

**Comment by obenland** [comment]
We could consider not to show preview screenshots on small screens

**Comment by iamtakashi** [comment]
Just for the record: My suggestions to most of the issue was here: https://github.com/Automattic/starter-page-templates/issues/16#issuecomment-494913017

> We could consider not to show preview screenshots on small screens
This could be an option as the thumbnails won't be accurate representation of the pages. But they can just be smaller sizes so that like three templates in a row to reduce the scrolling.

**Comment by marekhrabe** [comment]
Judging from the recording above, the scrollable area is definitely missing `-webkit-overflow-scrolling: touch;`. Let's add it as part of other changes.

**Comment by getdave** [comment]
> This could be an option as the thumbnails won't be accurate representation of the pages for mobile. 

If these were SVGs we could show hide portions of the graphic via CSS based on the active media query.

Alternatively, we could have separate images for smaller viewports.

In general, we should aim to retain content parity between all screen sizes.

**Comment by getdave** [comment]
Closing in favour of more specific tasks.
