### ISSUE TITLE
Jetpack Plugins: missing update icon for Multisite networks

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#3331]
Steps to reproduce:
1. Install Plugin A on the main site of a Multisite network, and on a separate single site.
2. Connect both sites to WordPress.com.
3. When an update becomes available for that plugin, head over to `wordpress.com/plugins`
4. The available update is displayed. Click on the plugin's name to get to the plugin's detail page (`https://wordpress.com/plugins/color-posts` in my tests)
5. It mentions that the new version is available on 2 of my sites, but I only see one update icon in the site list:

![screen shot 2016-02-16 at 8 57 18 am](https://cloud.githubusercontent.com/assets/426388/13070285/a1626e50-d48b-11e5-90ae-01f441ff54db.png)

I had to click on the multisite network's name to see a button to update. It seems that update icon is always missing for multisite networks.

**Comment by designsimply** [comment]
I don't see an option to install a plugin from `/wp-admin/plugins.php` in my multisite, but do see the "Add New" button for plugins in Network Admin at `/wp-admin/network/plugins.php`. Is that normal? For step 1, does it matter where the plugin is installed from or if it's network activated or not?

I went ahead and installed a plugin via Network Admin and now I can see it on `/wp-admin/plugins.php` for the main site and a separate single site on the network—now I just need to wait for an update to come through to finish testing.

**Comment by jeherve** [comment]
> Is that normal?

Yes, that's the expected behaviour.

> For step 1, does it matter where the plugin is installed from or if it's network activated or not?

It doesn't matter, and it doesn't matter if it's activated or not.

**Comment by kriskarkoski** [comment]
@designsimply Do you still have your testing setup for this issue? You mentioned waiting for an update to come through above, I wanted to see if you were able to repro.
