### ISSUE TITLE
Jetpack checklist: switch to a modal

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33319]
Currently, landing to the checklist looks like this:

<img width="1402" alt="Screenshot 2019-05-14 at 14 17 29" src="https://user-images.githubusercontent.com/87168/57694057-70e61200-7653-11e9-9fed-cdc29144ca7c.png">

Instead of thank-you + faded checklist + hiding navigation UI, we could show a modal over everything.

@shaunandrews via https://github.com/Automattic/wp-calypso/pull/32951#issuecomment-493111708

> I would think a modal overlay would be way more appropriate than hiding bits of our UI.
>
> <img width="1256" alt="image" src="https://user-images.githubusercontent.com/191598/57865657-fdb3db80-77cb-11e9-8662-679d7b87e539.png">
>
> Or a separate screen altogether, similar to what @sirreal suggested.
>
> <img width="751" alt="image" src="https://user-images.githubusercontent.com/191598/57865783-381d7880-77cc-11e9-9bc1-543f6ca61937.png">
>
> Perhaps there's a reason for having the checklist and filterbar visible, but obscured — but its not obvious.

Should we do the modal over navigation elements + checklist _OR_ should we instead remove the faded out checklist and leave just thank you page? Latter we could do as an MVP towards the modal anyway.

Slack convo p1558619729142900-slack-onboarding-exp

**Comment by jeffgolenski** [comment]
I'd prefer to have that moved into the modal. I think it feels more natural .

**Comment by jeffgolenski** [comment]
Just some polish. @simison I see the modal has been added, but can we match it match the exact styling of wpcoms modal as seen above?

**Comment by simison** [comment]
Thanks, good one. I opened a new issue to track that: https://github.com/Automattic/wp-calypso/issues/33731
