### ISSUE TITLE
Checklist: Split Account Settings page into sections, each with Save Settings button

### ISSUE THREAD

**Issue by donpark** [Automattic/wp-calypso#33331]
As mentioned in https://github.com/Automattic/wp-calypso/pull/33214#issuecomment-494938598 and subsequent discussions, Account Settings currently has only one Save Account Settings at the bottom which conflicts with mobile UX needs as well as complicating Guided Tour.

Suggested solution is to split up the page into logical sections like Site Settings page and add Save Settings button on section headers.

Reminder: Tours related to Account Settings page also needs to be updated after this design refactor.

**Comment by donpark** [comment]
Account Settings page needs a redesign because fields on the page are a mixed bag that does not easily divide into logical sections. Code needs a rewrite too as it's just not in a state ready to add sections.

**Comment by sixhours** [comment]
Moving this back as a Design To Do since it needs more work before we could begin development.

**Comment by davipontesblog** [comment]
Is this related to the Jetpack onboarding, or dotCom onboarding?

**Comment by sixhours** [comment]
I think we can close this out; it's related to an older issue about guided tours and the checklist, which we're not using now. If we do in the future, we may want to revisit this.
