### ISSUE TITLE
Gutenberg: Category search broken, requires lowercase

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#33334]
When editing a post with Gutenberg on WPCOM (Simple and AT), the option to search for categories appears to be broken.

For example, the category may be titled "Test 5" or "New Category" but you must search for it as "test 5" or "new category" for it to appear in your search results.

Video: https://cld.wthms.co/inV0r4

This appears to be impacting WPCOM only and **could not reproduce on self-hosted**.

#### Steps to reproduce
1. Create or edit a post on a WordPress.com site (via Calypso or WP-Admin)
2. Add a category with an uppercase title such as "My New Category"
3. Attempt to search for the category  (will need enough categories for the search option to appear). 
4. Searching for **_My New Category_** will yield no results. The category will only appear in search results if the lowercase _**my new category**_ is used. 

#### What I expected

For a category to appear in search results no matter the case used. As it does on self-hosted.

#### What happened instead

Category search requires the usage of lowercase and uppercase will not yield any results. Works as expected on self-hosted.

#### Browser / OS version
Occurs across multiple browsers and operating systems include mobile devices.

#### Screenshot / Video
Video: https://cld.wthms.co/inV0r4

#### Context / Source
2049943-zen
p1558803269002200-slack-triage

#user-report

**Comment by gwwar** [comment]
cc @gibrown any insight on why matches are case sensitive? Are we missing any headers or query parameters to ensure we use a lower case filter on the query?

**Comment by gibrown** [comment]
@gwwar no idea, what endpoint is this using? I thought we only used Elasticsearch for cross site search in Calypso but maybe that has changed.

**Comment by gwwar** [comment]
Ah @gibrown so it's a local search! This was fixed recently in https://github.com/WordPress/gutenberg/pull/14786/ so we should get the fix eventually on WordPress.com when we update version

**Comment by gwwar** [comment]
This was fixed by the Gutenberg v5.8 version bump 👍
