### ISSUE TITLE
Memberships: Memberships don't have their own tab under Earnings section

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#33365]
#### Steps to reproduce
1. On a site with a paid plan, add Memberships block to a post.
2. Notice the "Member management" section in the sidebar.
![image](https://user-images.githubusercontent.com/4550351/58444071-b0bff580-8139-11e9-8f4a-80994b805a8c.png)

3. The link goes to the Tools >  Earn section: https://wordpress.com/earn/memberships/{site}, but the only tabs available are "Ads earnings", and "Ads settings". There's no clear path to go back to this screen, once you navigate away.
<img width="800" alt="earn_memberships" src="https://user-images.githubusercontent.com/4550351/58444178-3e9be080-813a-11e9-9dcc-8a47b8bd3209.png">

#### What I expected
I expected "Memberships" to have its own tab under Tools > Earn, so that customers know where they are, and how to go back to that screen.

Found via: #dogfooding, #manual-testing

**Comment by artpi** [comment]
Thank you! This is because the tab is hidden until we launch the feature.
Tomorrow, the tab will appear.

**Comment by alaczek** [comment]
Oh ok! I think it's safe to close this one then.
