### ISSUE TITLE
Add a security policy for reporting issues

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#33385]
Set up a security policy.

Help the community understand how to securely report security vulnerabilities for calypso.

https://github.com/Automattic/wp-calypso/security/policy

**Comment by griffbrad** [comment]
This seems worth addressing.  We already have some basic info in the main README.

**Comment by sarayourfriend** [comment]
Shall we just copy what's in the README?


https://github.com/automattic/wp-calypso/blob/6037b345736168b583ea0c7a4fd06729338841c0/README.md#L35

**Comment by lynnbgriffith** [comment]
Yes. Also worth glancing at Jetpack’s policy:
https://github.com/Automattic/jetpack/blob/master/SECURITY.md
