### ISSUE TITLE
Wix Importer: Add documentation

### ISSUE THREAD

**Issue by dezzie** [Automattic/wp-calypso#33392]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/
2. Choose the Wix importer

#### What I expected
Consistent with the UIs of the other importing tools, a link to documentation specific to this importer.

#### What happened instead
- No such info

#### Browser / OS version
- everywhere

#### Screenshot / Video
<img width="1023" alt="trash add wix documentation" src="https://user-images.githubusercontent.com/1301932/58511248-07402a80-8160-11e9-97cf-9e41bf6565de.png">

### Add:

- [ ] Link to `https://en.support.wordpress.com/import/import-from-wix/`

### Update:

- [ ] Anything in the UI that isn't accurate or has changed
- [ ] Review en.support documentation to make sure it's up-to-date both ways.

#fix-the-flows, #importers-design, #muriel

**Comment by mattsherman** [comment]
Closing this. The documentation doesn't actually provide any extra value to the user when they are already on this screen, as all they need to do it provide their URL.
