### ISSUE TITLE
Full Site Editing: Merge Template and Post Content

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#33394]
As part of the Editor-in-Editor (or the E of FSE), we need to find a way to load template parts and content together when the User edits a Post or Page. The scope of this task is just to create the necessary infrastructure to merge those elements and send them together to the editor instance as `post_content`.

Things that are **out of the scope** of this task:

- Support for creating new posts or pages. It's expected to fail in that case.
- Support for displaying the content. This task is concerned only with sending the full page content to the editor.
- Support for creating new templates. A template Id has to be used. It can be, for example, the first template Id available.

For more context: paAmJe-p3-p2

**Comment by vindl** [comment]
We'll not be pursuing this approach for now, and will instead try to build an intermediate solution that allows editing the template parts and post content in different editor views. For context see paAmJe-rq-p2.

We'll be doing a timeboxed research spike to determine if alternative approach with `EditorProvider` is feasible.
