### ISSUE TITLE
Full Site Editing: Preserve changes on Template Parts and Post Content [?]

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#33396]
Depends on #33395.

As part of the Editor-in-Editor (or the E of FSE), we need to find a way to allow the User to persist changes made while editing the full page content.
When the user changes the template parts or the post content, those elements need to be preserved independently, and without conflicts. The scope of this task is to create the necessary infrastructure to intercept the save operation, parse the full page content, save all the template parts and clean up the `post_content` so it can be saved.

Things that are **out of the scope** of this task:

- Support to create new template parts. If the User adds a new template part, it's not expected to be saved.
- Support to remove template parts. If the User removes a template part, we are not expecting it to be removed.
- Support to remove post content. If the post content is missing, nothing should change for the template (since we are only saving parts), but `post_content` is expected to be empty.

For more context: paAmJe-p3-p2

**Comment by vindl** [comment]
We'll not be pursuing this approach for now, and will instead try to build an intermediate solution that allows editing the template parts and post content in different editor views. For context see paAmJe-rq-p2.

We'll be doing a timeboxed research spike to determine if alternative approach with `EditorProvider` is feasible.
