### ISSUE TITLE
Store: Dashboard assumes I have not setup, after wp-admin setup 

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#33397]
I setup a store in wp-admin, when viewing via Calypso the dashboard shows me as not setup. 

#### Steps to reproduce
1. Create a new store, setting up via wp-admin (add product, configure payment)
2. Go to Calypso > Store > Dashboard
3. See step asking you to setup the store: 
![https://cld.wthms.co/0znQut+](https://cld.wthms.co/0znQut+)
Direct Link: https://cld.wthms.co/0znQut 

#### What I expected
Dashboard to show my sales stats. I have 2 orders on this site. If a site has an order we could assume some configuration has taken place. 

#### What happened instead
Graphic asking me to setup my store (which has already been setup) showing on the Dashboard. Next step is to confirm business address. If this needs to be done on the Calypso end, the first dashboard view should be a checklist with this at the top to complete rather than the initial setup graphic. 

Example of checklist after I've confirmed the address: 
![https://cld.wthms.co/reEq5O+](https://cld.wthms.co/reEq5O+)
Direct Link: https://cld.wthms.co/reEq5O 

#dogfooding #manual-testing #store

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
