### ISSUE TITLE
Store: "Powered by WooCommerce" logo should link to WooCommerce.com

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#33398]
At the bottom of all store pages we mention "Powered by WooCommerce.com". It would be helpful if this linked to WooCommerce.com or better yet, a landing page specific to WooCommerce on WordPress.com to introduce customers to our brand/marketplace. 

![https://cld.wthms.co/aoTThT+](https://cld.wthms.co/aoTThT+)
Direct Link: https://cld.wthms.co/aoTThT 

#### Steps to reproduce
1. Go to any Store admin page in Calypso. 
2. See bottom footer "Powered by WooCommerce" 
3. Try to click for more info.
4. Whomp. Whomp. 

#### What I expected
Click the logo to learn more 

#### What happened instead
Nada

**Comment by kellychoffman** [comment]
>  linked to WooCommerce.com

I'm worried this will cause more confusion as you can't actually add any extensions to Store. 

>  better yet, a landing page specific to WooCommerce on WordPress.com

This would be great, but I'm not sure we have one. We could point people to the help section: https://en.support.wordpress.com/store/

**Comment by msdesign21** [comment]
> I'm worried this will cause more confusion as you can't actually add any extensions to Store.

Do you mean you can't add WooCommerce extensions to be used in Calypso Store? How's this any different than uploading a plugin via Calypso? It's also mentioned that this is possible in the docs page you linked to: https://en.support.wordpress.com/store/#advanced-customization

I wasn't sure if there would be any opportunity for collaboration on bottle pickup at the meetup, ideally I could work with @slobtsov for a WordPress.com Store landing page on WooCommerce.com.

**Comment by kellychoffman** [comment]
> Do you mean you can't add WooCommerce extensions

You can but then you have to use wp-admin to access the UI of the extension. The user would have to switch interfaces to make it happen. They wouldn't know how to do it. 

Collabo is most definitely encouraged! Will be super easy to do IRL too.
