### ISSUE TITLE
Full Site Editing: Edit Template and Content [?]

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#33395]
Depends on #33394.

As part of the Editor-in-Editor (or the E of FSE), we need to find a way to allow the User to edit template and post content on the same editor instance.
When we load an `a8c/template-part` or an `a8c/post-content` block, we are merely showing the corresponding content for the `edit` operation. This behaviour needs to be changed to allow treating the template part content or the post content as editable `InnerBlocks`.

The scope of this task does not include loading the full page content, nor saving the user changes.

For more context: paAmJe-p3-p2

**Comment by vindl** [comment]
We'll not be pursuing this approach for now, and will instead try to build an intermediate solution that allows editing the template parts and post content in different editor views. For context see paAmJe-rq-p2.
