### ISSUE TITLE
GoDaddy Importer: Add documentation

### ISSUE THREAD

**Issue by dezzie** [Automattic/wp-calypso#33391]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/
2. Choose the GoDaddy importer

#### What I expected
Consistent with the UIs of the other importing tools, a link to documentation specific to this importer.

#### What happened instead
- No such info

#### Browser / OS version
- everywhere

#### Screenshot / Video
<img width="1023" alt="trash add godaddy documentation" src="https://user-images.githubusercontent.com/1301932/58511060-b4667300-815f-11e9-91a5-16ad3c51ea13.png">

### Add:

- [x] Link to `https://en.support.wordpress.com/import/import-from-godaddy/`

### Update:

- [x] Anything in the UI that isn't accurate or has changed
- [x] Review en.support documentation to make sure it's up-to-date both ways.

#fix-the-flows, #importers-design, #muriel

**Comment by davipontesblog** [comment]
Pinging @sdixon194 and @donalirl  on this one - is this something that can be transferred to your Docs repo?

**Comment by donalirl** [comment]
@davipontesblog The doc itself already exists https://en.support.wordpress.com/import/import-from-godaddy/

This issue is asking to include a link to the doc in the importer itself, similar to the other importers: https://d.pr/i/LXlucm

Therefore, wp-calypso is the corrert repo.

**Comment by lancewillett** [comment]
Current screen:

<img width="774" alt="Screen Shot 2020-03-15 at 19 18 43" src="https://user-images.githubusercontent.com/66797/76717739-cbc41c00-66f1-11ea-8af9-deec1e978de1.png">

This should be a fairly simple text change. Adding a short phrase with a link here is a good start.

> Import posts, pages, and media from sites made with the GoDaddy GoCentral website builder to [YOUR SITE]. [Learn more](https://en.support.wordpress.com/import/import-from-godaddy/).

Where Learn More links to the support doc.

**Comment by lancewillett** [comment]
Notes:

1. Let's add this same change to the Wix importer screen, using https://en.support.wordpress.com/import/import-from-wix/.
2. Bonus point: change the support docs to open in-app instead of going out of Calypso. CC @Aurorum

**Comment by Aurorum** [comment]
Sorry, I forgot about this. I'll spin up a PR for it. :)

**Comment by Aurorum** [comment]
PR for this issue in #40356. :)

**Comment by lancewillett** [comment]
Confirmed fixed. Testing with Firefox latest stable on macOS Catalina — with `testerlance` user.

Tools > Import and clicking GoDaddy importer. I can now see the "Need help?" links appear. Clicking the link launches the WordPress.com support page inline (yay!).

<img width="1392" alt="Screen Shot 2020-03-22 at 09 59 22" src="https://user-images.githubusercontent.com/66797/77255408-6d80c700-6c24-11ea-8cd3-d7e60dbeffd3.png">

From the inline help page overlay, clicking "Visit Article" opens the support page in a new tab:

<img width="1392" alt="Screen Shot 2020-03-22 at 09 59 24" src="https://user-images.githubusercontent.com/66797/77255409-6fe32100-6c24-11ea-9ef9-8d30104812d9.png">

**Comment by lancewillett** [comment]
Deployed to production! Thank you for the fix, @Aurorum. 🌟

**Comment by Aurorum** [comment]
Thanks @lancewillett! :)
