### ISSUE TITLE
Editor: Surface selected categories to the top of the category selector

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#334]
> Selected categories don’t surface to top (even after save and refresh). In comparison, when you add a category and refresh the page, wp-admin has the selected categories at the top. 

In the Calypso editor, should we show selected categories toward the top of the list? Should this occur immediately, or only after the page refreshes? The latter seems to be inconsistent with the intent of a React application to reflect the current state at any given time, but the former may become an annoyance as categories shift around while selected.

Comment: "If we do go this route I think there should be a separate section on the top of the component that shows the current selections ( along with their paths if applicable )."

**Comment by folletto** [comment]
I'd close this issue and reopen if it will appear as an actual problem. When it was raised is was mostly a question, and before other UI elements landed.

We already have the second line inside the accordion that highlights the categories, as well as search, so the need might be absent or lessened.

**Comment by alisterscott** [comment]
Categories have changed a lot since this was raised and I don't think it takes into account hierarchies. Closing as per Davide's suggestion
