### ISSUE TITLE
FSE: Iteration 1 Demo Prep

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33404]
- [x] Create an outline of what we want to show
- [ ] Test a run through of that outline to make sure everything works as intended.
- [ ] Add more steps to this issue if necessary

**Comment by getdave** [comment]
# Outline

* Repeat the scope of this phase of work based on Master Thread for context.
* Show where "Templates" reside as Pages within the Default Vertical Site - show [endpoint](https://public-api.wordpress.com/wpcom/v2/verticals/default/templates) 
* Outline the specific feedback we're looking for:
  - UI interactions
  - Confirmation that static screenshots are ok for an MVP launch
* Demo creation of new Page using the default Templates

## Prerequisites

* This should be demoed on WP.com environment

**Comment by getdave** [comment]
Dave to write up question about directory structure.

**Comment by getdave** [comment]
# Questions about Prototype

* Is the _instant_ nature of the insertion too fast - would a slight delay help?
