### ISSUE TITLE
Color Schemes: Powder Snow thumbnail is inaccurate

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33431]
I noticed this while working on another color scheme. In the Powder Snow color scheme's thumbnail preview, the secondary backdrop color (color behind the main content area) should be `#f6f6f6` rather than white. It's an oversight on my part when I launched the color scheme.

<img width="1280" alt="Screen Shot 2019-05-29 at 1 57 44 PM" src="https://user-images.githubusercontent.com/2124984/58581525-c0186f00-821d-11e9-9ed6-370e29c20850.png">

**Comment by scottsweb** [comment]
I will take a look at this during the design meetup

**Comment by torres126** [comment]
Just a quick heads up that there's a PR for this in #33435. :)

**Comment by sixhours** [comment]
@scottsweb It looks like there's an open PR to fix this at #33435 -- you could take responsibility for reviewing and deploying that PR at the meetup, or you could choose a different issue. Let us know what you want to do!

**Comment by scottsweb** [comment]
Good catch, I have another issue to my name. So I will review this and work on the other one as well. All counts as progress. Thanks for the PR @torres126
