### ISSUE TITLE
Store: Title case to sentence case audit

### ISSUE THREAD

**Issue by kyleaparker** [Automattic/wp-calypso#33438]
Store on WP.com is currently inconsistency switching between title case and sentence case for buttons, labels, and headings. 

Sentence case is the preferred style on Material and I'd like to do a full audit in Store to update any copy to use sentence case. 

A few examples: 

<img width="1655" alt="Promotions" src="https://user-images.githubusercontent.com/712873/59473628-17ab0300-8df8-11e9-80a1-13276dc48f9e.png">
<img width="1664" alt="Taxes" src="https://user-images.githubusercontent.com/712873/59473629-17ab0300-8df8-11e9-903e-d6a21907352e.png">

**Comment by msdesign21** [comment]
Some examples I've found. 

Once you've completed the onboarding checklist: 
1. "Test all the things" on the dashboard: 
![https://cld.wthms.co/d5ZtZ4+](https://cld.wthms.co/d5ZtZ4+)
Direct Link: https://cld.wthms.co/d5ZtZ4 
2. View full stats on bottom of dashboard stats: 
![https://cld.wthms.co/kVsGuV+](https://cld.wthms.co/kVsGuV+)
Direct Link: https://cld.wthms.co/kVsGuV 

3. On Promotions before you've added one: 
![https://cld.wthms.co/gHrFUR+](https://cld.wthms.co/gHrFUR+)
Direct Link: https://cld.wthms.co/gHrFUR 
4. Also pink `Add promotion` button in the top right 

Personally I prefer sentence case, I wonder if the decision for title case is the best? Was talking to @MichaelArestad about this as well.

**Comment by kyleaparker** [comment]
Thanks @msdesign21 ! I had captured most of these in the audit I have done so far but missed the first one :) 

I chatted to @cburton4 about this as it looks like sentence case is the preferred pattern on Material. Also agree that sentence case looks better. 

However, if updating the writing style on WP.com isn't a priority right now, it makes sense for us to follow the current standards on WP.com until those writing guidelines have been defined within Muriel.

**Comment by MichaelArestad** [comment]
@kyleaparker I think it would be wise to make the change to the writing guidelines now. It's not just a preference. Sentence case has proven to be more legible than title case in Interface (well in anything, but...) CC @cburton4

**Comment by kyleaparker** [comment]
👍 I'm happy to do the updates on Store to use sentence case for all buttons, titles, and labels - it won't be a small undertaking to make those updates in the rest of WP.com so I think a product decision needs to be made and then prioritized
