### ISSUE TITLE
Domains: Signup domain search screen issues in IE11 on Windows 7

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#33443]
1. Start signup from the WP.com homepage in IE11 with Windows 7
2. Clickthrough to domains screen
3. Layout looks broken (see screenshot below)

Note: I was using Browserstack here. Not sure if that caused the issue or not.

![image](https://user-images.githubusercontent.com/545779/58599773-544afc00-8247-11e9-8b56-dace243910c9.png)

**Comment by thomasguillot** [comment]
Looks like it's related to `.featured-domain-suggestion .domain-suggestion__content { flex-basis: 100% }`. Switching to `flex-basis: auto;` would potentially fix it but I'm not quite sure we set `flex-basis: 100%;` in the first place.
