### ISSUE TITLE
Currency should be based off store location

### ISSUE THREAD

**Issue by scottysimpson** [Automattic/wp-calypso#33444]
When on-boarding to Store it first asks you to enter your location. After entering a address (US one in this case) and proceeding to settings the currency is default set to pounds. This would be a good opportunity to match the currency to the address entered (if currency for that address is available)

#### Steps to reproduce
1. Starting at URL:
2.
3.
4.

#### Screenshot / Video
![Screenshot](https://cld.wthms.co/dXcQbe+)
Screenshot direct link: https://cld.wthms.co/dXcQbe

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
