### ISSUE TITLE
Global Notices: Change the position on screen

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#33441]
Following up on the discussion in #32229, this issue is about making a global change to the position of the snackbar notices. So far, these have been shown in the top right, and in #32229 a change to bottom right and bottom centre (seems to be the consensus) were discussed.

Here's where they appear now for reference:
![image](https://user-images.githubusercontent.com/4550351/58598196-9bc09f00-82be-11e9-9f99-e1f70282ff37.png)

@scalarbane2 could you drop your explorations in the comments?

**Comment by scalarbane2** [comment]
Yes. The reason why I put the snackbar in the first instance is that that is how it is across the platform.

![Remove Follower - Success-1](https://user-images.githubusercontent.com/50745054/58653874-9428e680-830e-11e9-9cd9-440e18f082f9.png)

![Edit User - Sucess](https://user-images.githubusercontent.com/50745054/58653951-c4708500-830e-11e9-9818-0bacd3d0f11b.png)

**Comment by sixhours** [comment]
@scalarbane2 Could you also post a snackbar in the bottom center screenshot, just to see how that would look?

**Comment by scalarbane2** [comment]
![center](https://user-images.githubusercontent.com/50745054/58897199-b1372e00-86ef-11e9-9040-2f8c14b4769c.png)

This is how it looks like. I don't think it looks good at the center.

**Comment by shaunandrews** [comment]
@scalarbane2 I noticed your mockups don't account for the inlineHelp button, which appears at the bottom-right of the screen.

**Comment by scalarbane2** [comment]
Oh! Forgot that. 
![center](https://user-images.githubusercontent.com/50745054/60749404-4d737f80-9f91-11e9-99c9-f0228354696a.png)

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.
