### ISSUE TITLE
FSE: determine whether thumbnail is an appropriate place to store Template preview graphics

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#33452]
Please see `D28788-code`

We need somewhere to store the preview images for each Page Template (the graphic which visualises what the Template will look like once selected).

An idea was to use the post thumbnail. However @marekhrabe said:

> I'm not sure it's a good idea to make use of the featured image (get_post_thumbnail_id ). They are definitely easy to add/update but in most themes, featured images would be visibly shown on the frontend and that might break the looks of vertical pages. Remember, those sites are also used by the Headstart and it pulls featured images. I think we shouldn't use them unless we want those images propagated.

He then suggested

> Could we use a different post meta field to store the id of the image and keep the rest of the code the same?

We'd value input from @michaeldcain on what might be most appropriate.

**Comment by obenland** [comment]
We'll store them in the segment site and add them through post meta in the vertical json files.
