### ISSUE TITLE
Inline Help: "Contact us" button breaks in Spanish

### ISSUE THREAD

**Issue by evilluendas** [Automattic/wp-calypso#33460]
The "Contact us" button in the Inline Help popover looks broken when the interface is in Spanish ("Contacta con nosotros" is much longer). 

![image](https://user-images.githubusercontent.com/820374/58635492-50be8000-82ee-11e9-8465-a4f342042108.png)

This could be fixed either changing the translation ("Contacto" would work perfectly fine too) or fixing the layout altogether so it breaks line more gracefully. The latter sounds like the preferable solution because this probably happens with other languages too.

For comparison, this is how it looks in English:

![image](https://user-images.githubusercontent.com/820374/58635720-dd693e00-82ee-11e9-9c74-883ef23c2f29.png)

**Comment by lancewillett** [comment]
@evilluendas For the shorter translation, do you want to just go ahead and fix it directly? Or do you want a 2nd opinion?

Steps to fix:

1. Go to https://translate.wordpress.com/projects/wpcom/
2. Navigate to `ES` https://translate.wordpress.com/projects/wpcom/es/default/
3. Click "Filter" and search for the term `contacta con nosotros` there
4. You should be able to make the correction there, save
5. Deploy with i18n tools in MC

I'm happy to help as well.

**Comment by lancewillett** [comment]
I went ahead:

https://translate.wordpress.com/projects/wpcom/es/default?filters[translated]=yes&filters[status]=current&filters[before_date_added]=2019-05-28%2016:37:16

Once we deploy and confirm we can close this issue.

**Comment by evilluendas** [comment]
Hi Lance! Thanks for fixing the translation! I think it looks much nicer with a shorter call to action.

I was planning to work on this issue during the All Designers Meetup in a couple of weeks as part of the "bottle picking time", could we leave the issue open? Since this is probably happening with other languages too, I'd like to try to fix the button itself so it doesn't look broken in any case.
