### ISSUE TITLE
Themes: Get rid of "Please enable JavaScript" message

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#3346]
To reproduce -- turn off JavaScript, and navigate to http://calypso.localhost:3000/themes/something

![js](https://cloud.githubusercontent.com/assets/96308/13089461/f96c3030-d4f0-11e5-9726-b04c8a6c24f7.png)

We don't want that on a server-side rendered, SEO-targeted page.

**Comment by folletto** [comment]
Woh. Well spotted. :)

**Comment by folletto** [comment]
#3616 is taking care of this. :)

**Comment by ockham** [comment]
Heh, thanks for linking to that. Forgot I had filed an issue :-)
