### ISSUE TITLE
Recurring Payments block: typo in error message

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#33462]
The recurring Payments block has a typo in an error message when you attempt to set a payment amount less than $5, the error message reads; 

> Please enter an amount thats at least 5.

It should read: 

>Please enter an amount that is at least 5.

Although I propose the following for clarity: 

>The amount entered is less than the minimum supported by Recurring Payments. 

With a link to documentation on why there's a minimum.

 
#### What I expected:

Appropriate grammar and spelling. 

#### What happened instead:

Missing punctuation.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/33329175/58635708-8a769300-82bc-11e9-8003-d6db1fbbb2b1.png)

#### Context / Source
Discovered via:  #dogfooding, #manual-testing

**Comment by arunsathiya** [comment]
cc @artpi
