### ISSUE TITLE
Jetpack onboarding: Checklist confirmation message

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#33464]
I was given some feedback regarding the onboarding copy for Jetpack:

![Image from iOS](https://user-images.githubusercontent.com/411945/58638366-8c584a80-82ec-11e9-9f81-d65e71a001cf.jpg)

Could make a good meetup issue to look at

**Comment by jeffgolenski** [comment]
@scottsweb Since you created this issue a lot of this flow has changed. 

This prompt now displays in a dialog and the checklist isn't faded out below it anymore.

**Comment by scottsweb** [comment]
Happy to close this then @jeffgolenski
