### ISSUE TITLE
Gutenberg: Feature Request Text/Code Block

### ISSUE THREAD

**Issue by AMcGrady** [Automattic/wp-calypso#33471]
From Ticket:
zd-2064410

User would like a block that can handle displaying code and text within it for instructional purposes. Gist isn't working for them:

>Unfortunately that doesn't really work for me. The point of a coding tutorial is to show bits and pieces of code with explanations along the way; so in order to do that using the Gist plugin I would need to have a separate Gist for each step along the way, which would be really cumbersome and really isn't the point of Gist anyway.

>The thing is, I'm sure I could find a work-around for this that will work temporarily, but if I'm going to have this problem with every post I make it's definitely not going to work out. So I'm wondering, can this be logged as a bug that will be fixed in a future release? If not I might have to go back to self-hosted WordPress, or switch to something else.

**Comment by lancewillett** [comment]
Thanks for the suggestion.

This should be possible now by simply wrapping code with `backtick` marks in the paragraph block. @AMcGrady — do you know if they tried that technique?

For more complex workflows, noting that for Atomic sites (as well as self-hosted) authors can opt to use the Classic Editor plugin if Gutenberg isn't suited to their specific workflow.

**Comment by lancewillett** [comment]
Here's an example:

<img width="710" alt="Screen Shot 2019-05-31 at 09 12 09" src="https://user-images.githubusercontent.com/66797/58719328-30d99b80-8384-11e9-9f37-8f0a2c72ef81.png">

Steps to accomplish this:

Start typing normal text.

To start a code snippet, type backtick ` once — type or paste your code, then another `. Gutenberg editor automatically creates code formatting.

For more complex syntax highlighting, yes: each code snippet will need to be separate. I think that's still doable with paragraph and code blocks intermingled.

**Comment by sarahfg** [comment]
Thank you! I've let the user know your solution.

**Comment by pauljacobson** [comment]
@lancewillett and @sarahfg I noticed an issue with how the code renders in a Syntax Highlighter Code block on the user's site that I wanted to point out. I added the code snippet with the HTML to the user's test post, [here](https://cld.wthms.co/omjDRe):

![](https://cld.wthms.co/omjDRe+)

_Screenshot direct link:_ https://cld.wthms.co/omjDRe

I also previewed the updated draft post, and all of the code seems to render in the post preview, despite the errors that the editor (albeit with what seems to be somewhat modified syntax highlighting), [like this](https://cld.wthms.co/3bOrtk):

![](https://cld.wthms.co/3bOrtk+)

_Screenshot direct link:_ https://cld.wthms.co/3bOrtk

I also did [a test on a test site ](https://he20171027.com/2019/06/02/code-and-commentary/)with the same block of code that contains HTML. In this test, the code blocks render differently. They include line numbers, and better syntax highlighting, [like this](https://cld.wthms.co/CdkrHh):

![](https://cld.wthms.co/CdkrHh+)

_Screenshot direct link:_ https://cld.wthms.co/CdkrHh

I haven't ruled out an error earlier in the user's draft post that caused the degraded rendering on their site, but this seems to be worth pointing out.
