### ISSUE TITLE
(3P) FSE: Make templates API endpoint locale-aware

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33490]
Includes 
- [x] Fall back to English when there are not templates for a requested locale

**Comment by kwight** [comment]
> Figure out how to get new templates translated (incl. strings in this plugin)

p6nuNy-CL-p2 may help point in the right direction.

**Comment by obenland** [comment]
API changes tracked in D29163-code

**Comment by obenland** [comment]
Fixed in D29163-code
