### ISSUE TITLE
DevDocs: Mention the Vagrant bootstrap as an alternative development environment

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/wp-calypso#3349]
Building Calypso natively is fairly easy on Mac OS but a pain on Windows. Let's promote the awesome [wp-calypso-bootstrap](https://github.com/Automattic/wp-calypso-bootstrap) as an alternative development environment. It's nice just being able to do `vagrant up` and having Calypso up and running magically. :)

**Comment by lancewillett** [comment]
+1
