### ISSUE TITLE
Store>Settings>Payments switches has confusing "ENABLED" label

### ISSUE THREAD

**Issue by scottysimpson** [Automattic/wp-calypso#33504]
#### Brief description
Inside Store>Settings>Payments, there are UI switches that allow users to enable payment methods. The label is confusing as it says "ENABLED" in both states.

#### What I expected
- When the switch is in the disabled/off state:
the label said "DISABLED", "OFF" or "ENABLE"

or

- When the switch is in the enabled/on state:
the label "ENABLED" was stronger i.e. darker text colour.

or

- There was no label at all (The switch state alone should be sufficient)

#### What happened instead
No matter what state the switch was in (on or off) the label "ENABLED" is displayed in the same light grey colour.

#### Screenshots
Disabled state:
![Screenshot](https://cld.wthms.co/5EcYeW+)
Screenshot direct link: https://cld.wthms.co/5EcYeW

Enabled state:
![Screenshot](https://cld.wthms.co/cwd9A1+)
Screenshot direct link: https://cld.wthms.co/cwd9A1

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
