### ISSUE TITLE
Full Site Editing: Replace the Visual Header [8]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33512]
Using our `template_part` "header", lets make sure that on page render, this replaces the semantic visual site `<header />`

<img width="665" alt="Screen Shot 2019-05-31 at 12 37 09 PM" src="https://user-images.githubusercontent.com/1270189/58730402-e4e91f80-83a0-11e9-855e-bfee1e23d647.png">

See also code examples in paAmJe-rq-p2

**Comment by kwight** [comment]
If I'm following that code correctly, it's using a `final_rendered_html` filter to parse/search/replace the full page markup, which might be fragile and error-prone. Maybe we can narrow down operations to just the header with the `get_header` action from the template's `get_header()` call?..

**Comment by vindl** [comment]
> If I'm following that code correctly, it's using a final_rendered_html filter to parse/search/replace the full page markup, which might be fragile and error-prone. Maybe we can narrow down operations to just the header with the get_header action from the template's get_header() call?

I don't think that `final_rendered_html` filter exists, might be something from the Dennis' demo code.

I've looked into various filters and actions around it and I don't think that it's possible to narrow it down with what's currently available. While `get_header` does expose an action, we could only use it to inject our custom header, but there is no way to filter/remove the default header after that.

**Comment by kwight** [comment]
Hm, indeed – nothing there looks helpful.

If we control the themes being used (which I think are all child themes of Twenty Nineteen), another option might be to add a `header.php` to the child themes, based on the parent theme's same file, but with whatever code needed to load our block template part instead inside the `<header>` tag.
