### ISSUE TITLE
Full Site Editor: populating our template_part header as part of site creation on WP.com [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33515]
**Update Note:** this task is now specifically related to inserting data on WP.com during site creation. The general case of plugin usage on self-hosted WP installs will be handled in https://github.com/Automattic/wp-calypso/issues/33636.

During site creation, let's make sure our header backed by `template_part` is populated with the expected content. We may do this programmatically via headstart.

In order to do this while preserving our initial data representation scheme, the following should be created:

1. `wp_template_part_type` taxonomy for `wp_template_part` CPT.
2. `wp_template_part` CPT post representing the header. Let's add a `Header` title to this post, and assign `header` term to `wp_template_part_type` taxonomy for it.
3. `wp_template_part` CPT post representing the footer. Let's add a `Footer` title to this post, and assign `footer` term to `wp_template_part_type` taxonomy for it.
4. `wp_template_type` taxonomy for `wp_template` CPT.
5. `wp_template` CPT representing the page template. Let's add a `Page template` title to this post, and assign `page_template` term to `wp_template_type` taxonomy for it.

![template-parts-5](https://user-images.githubusercontent.com/1182160/59374248-b4fc2d80-8d4b-11e9-8628-7d70e3b19423.png)

<img width="665" alt="Screen Shot 2019-05-31 at 12 37 09 PM" src="https://user-images.githubusercontent.com/1270189/58731104-c08e4280-83a2-11e9-9c92-93d7f6b2043d.png">

**Comment by kwight** [comment]
If I understand correctly, a few steps have to happen:

* The dotcom loader needs to register the CPTs (basically, do everything that the plugin's activation hook does).
* Set up a test annotation that we can use for development.
* Verify Headstart's processing of the CPTs.
* Move the CPT content into intended production annotations.

One thing to note is that Headstart does not currently support hierarchical taxonomies (this is why tags are currently supported, but categories are not). I don't believe that's important yet (we are registering hierarchical taxonomies, but I don't see us using them), but may represent some significant work down the road.

**Comment by jeraldjuice** [comment]
This is on hold for now, pending the outcome of [Marko's solution](https://github.com/Automattic/wp-calypso/pull/34640).

**Comment by vindl** [comment]
Closing this for now since I've merged https://github.com/Automattic/wp-calypso/pull/34640 and https://github.com/Automattic/themes/pull/1062 which should also handle it.
