### ISSUE TITLE
Full Site Editor: Better options for replacing the visual header [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33513]
Let's writeup the approach needed in https://github.com/Automattic/wp-calypso/issues/33512 and see if there are any cleaner ways of doing this. For example, existing hooks / potential core PRs we may submit.

Timebox the initial writeup to 3 days. This does not include implementation.

<img width="665" alt="Screen Shot 2019-05-31 at 12 37 09 PM" src="https://user-images.githubusercontent.com/1270189/58730736-d5b6a180-83a1-11e9-8225-adaa96de129e.png">

**Comment by apeatling** [comment]
I think we have this figured out now, closing.
