### ISSUE TITLE
Full Site Editor: Spike for cost (only) using Editor Provider and creating a new Editor Instance [5]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33514]
Let's do a timeboxed investigation for a ballpark estimate of what costs are for implementing a new editor instance using two editor providers as noted in https://github.com/Automattic/wp-calypso/issues/32944#issuecomment-497074526

We're aiming to figure out the order of magnitude of difficulty out of this task, and as part of that, an idea of any known blockers we have currently. It doesn't need to be perfect, this gives us an initial baseline of work required here.

Our goals are to answer:
- Is it possible to implement this now, using Gutenberg packages?
- If not what work is required?
- If so, what does this cost to implement, and what do ongoing costs look like? Is it reasonable to maintain.
- If costs are unreasonable, are there any contributions we can make to lessen this?

As @mtias noted:

- Create your own editor that represents the _page title_ as a block (is not saved in `post_content`) and the _content_ is passed to another inner block with its own editor provider. ([Inspiration](https://github.com/WordPress/gutenberg/pull/14715)).

To handle this you'll need a custom template supplied to your root provider that has a page title and content blocks. I'd start with a locked template so that ordering cannot be changed (title cannot go under content).

See also paAmJe-p3-p2 for further explanation

**Comment by dmsnell** [comment]
Did a little playing in https://codesandbox.io/s/angry-bhaskara-r3zrc

From what I can see it looks like this route is the intended way to solve our dilemma but it may take someone more knowledgable than I to figure out how to do it.

My current perspective is that we have two approaches:
 - clone the existing `EditorProvider` at the risk of being a hard-to-maintain fork of the official one and have all the bells and whistles provided for us
 - start from scratch or from the `BlockEditorProvider` and get essentially nothing premade. this seems like it would practical mean rebuilding `EditorProvider` as I'm not sure what we wouldn't need from `EditorProvider`

**Comment by apeatling** [comment]
Since we're not going to be looking at this in further iterations, I'm going to close.
