### ISSUE TITLE
Me: Changing email address got Gravatar in a broken state

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#33520]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Make sure you have a profile pic set
3. Change the Email Address to one you haven't previously used with WPCOM / Gravatar and save
4. Note that your profile picture is now blank.
5. Click the link to confirm your new email (not sure if this is necessary but I did it).
[I didn't feel like finding and uploading my profile pic from my hard drive again, so...]
6. Go to gravatar.com and authenticate with WPCOM
7. I then found myself in an odd state where my new email was displayed on the upper right as my username, I still had a profile pic, but my old email was the only one visible on my profile
<img width="764" alt="Screen Shot 2019-05-31 at 2 14 57 PM" src="https://user-images.githubusercontent.com/52152/58735732-38169e80-83b0-11e9-9dd0-151e61c5855c.png">

8. "Add email address" and put in the new email address I used for my WPCOM account
9. "Whoops! Something went wrong!":
<img width="981" alt="Screen Shot 2019-05-31 at 2 13 41 PM" src="https://user-images.githubusercontent.com/52152/58735603-c2aace00-83af-11e9-80e8-18cb8f258990.png">
10. I eventually tried "Delete email" and that magically fixed everything: my new email now showed and I was able to set the old profile pic as the new email's Gravatar.

#### What I expected

Changing my WPCOM email should have also changed my primary email with Gravatar, and kept my profile pic intact.

#### What happened instead

Profile pic was cleared, Gravatar was confused.

#### Browser / OS version

OSX / Firefox

#### Context / Source

#dogfooding as I try to set up a personal account to use while on sabbatical!

**Comment by lancewillett** [comment]
Thanks for the report, Kat.
