### ISSUE TITLE
Reset Password: Generate Strong Password button and New password field overlap

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/wp-calypso#33523]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/wp-login.php?action=lostpassword
2. Filling the form and waiting for the Reset password email
3. Selecting the "Reset password" button in the email
4. Arriving at: https://wordpress.com/wp-login.php?action=rp

#### What I expected
The "Generate strong password" button not overlapping the "New password" field.

#### Browser / OS version
Was able to replicate with Chrome and Firefox

#### Screenshot / Video

![Overlap_of_the_password_generator_1](https://user-images.githubusercontent.com/905781/58739027-8f485d80-8408-11e9-9295-5ca4aa3ccc6b.jpg)
![Overlap_of_the_password_generator_2](https://user-images.githubusercontent.com/905781/58739031-91122100-8408-11e9-87d3-eaf50f2043ab.jpg)
![TvbqgWwpZP](https://user-images.githubusercontent.com/905781/58739050-9bccb600-8408-11e9-9e0b-b68e776337c5.gif)

#### Context / Source

I was able to find an old, closed issue (#20840) about a styling issue with the "Generate strong password" button, but this one seems to be different.

**Comment by sixhours** [comment]
Since this would be fixed by #33924, I'm going to close this issue as a duplicate and we'll continue any work in the other ticket.
