### ISSUE TITLE
Me: Uploading a new profile pic suddenly mentions Gravatar

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#33521]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me
2. Click your profile pic to change it and upload a new one.
3. Crop and save
4. Get this message: "You successfully uploaded a new Gravatar! Looking sharp!"
<img width="553" alt="Screen Shot 2019-05-31 at 2 32 21 PM" src="https://user-images.githubusercontent.com/52152/58735928-f2a6a100-83b0-11e9-9e27-ea96e7047d14.png">

#### What I expected

It should probably say "You've uploaded a new profile picture" since this is the language the rest of the UI is using.

#### What happened instead

If I didn't know what "Gravatar" was it would be confusing and maybe a little alarming since none of the preceding text or buttons mentioned it.

#### Browser / OS version

OSX / Firefox

#### Context / Source

#dogfooding setting up a personal WPCOM account to use while on sabbatical!

**Comment by lancewillett** [comment]
Good find! (Enjoy your break!)

**Comment by dezzie** [comment]
Draft PR: https://github.com/Automattic/wp-calypso/pull/33833
<img width="565" alt="Screen Shot 2019-06-11 at 3 59 38 PM" src="https://user-images.githubusercontent.com/1301932/59312653-bdc50480-8c62-11e9-8dbb-9270dd1f0b0f.png">
