### ISSUE TITLE
(8P) FSE: Define target group for initial launch

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33536]
Make plugin available to:

- [x]  Sites that have one of the Gutenberg Business themes activated.
- [x]  Sites with locales that we have json annotations for.

**Comment by apeatling** [comment]
I think it's fine to start with English, and limit using an A/B test. We need to kick off translation work though. What do we need to start that?

Once the translations are available then remove the A/B test and push out for everyone.

**Comment by obenland** [comment]
If we want to limit by locale, we probably wouldn't even need an A/B test but could just return an empty value in the API. [If the page template selector has no templates to select, it won't load](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php#L73-L76).

**Comment by apeatling** [comment]
Okay 👍

**Comment by obenland** [comment]
See D29268-code
