### ISSUE TITLE
Editor: Media library: Drag-dropping image/file on the popup does not show drop region

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#33533]
#### Steps to reproduce 

- Start on a WordPress.com site with a `contributor` user account.
- Create a new post or page, using the Calypso editor (WordPress.com editor/non-Gutenberg editor)
- Click on `Add > Media`
- Drag-drop a file/image from computer to this media popup

#### What is expected 

The drop region appears when attempting to drop this image/file, but the upload itself fails because contributor role cannot upload files to media library.

#### What happens instead 

The drop region does not appear, but instead the image can be seen to be pulled towards the `Featured image` region in the background. But eventually it does not get attached to the featured image section either.

Here is a [video](https://cloudup.com/c1Rrso55WK2) showing this behaviour.

#### What is suggested

It's best to hide the `Add > Media` option for contributors, similar to hiding the `Free photo library` and `Google Photos library` here - https://github.com/Automattic/wp-calypso/issues/22829#issuecomment-498098874

**Comment by donpark** [comment]
> It's best to hide the Add > Media option for contributors, similar to hiding the Free photo library and Google Photos library here - #22829 (comment)

I don't think this is the ideal solution because hiding `Add > Media` menu item will prevent Contributor from adding images already in the Media Library.

**Comment by donpark** [comment]
#34601 will hide "Google Photos library" and "Free photo library" menu items from the Media Library.

What remains to be addressed is preventing drag and drop events from leaking to components below the modal dialog, like the featured image component.
