### ISSUE TITLE
Ecommerce Plan: Require Business or eCommerce plan if "Online store" is selected in signup

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#33543]
**Samus estimate: 2**

> As an online store owner, I want only plans that will let me create an online store offered to me, so that I pick a suitable plan.

If a customer picks a Free, Blogger, Personal, or Premium plan, they are not able to create an online store. We should remove these plans if "Online store" is selected as the kind of site. A related issue (https://github.com/Automattic/wp-calypso/issues/33544) will make it more clear that "Online store" functionality requires a Business or eCommerce plan. 

Note: Leave Business plan as an option. A related issue (https://github.com/Automattic/wp-calypso/issues/33549) will improve the discoverability of Store functionality for Business sites.

Page where "Online store" is selected:
<img width="1213" alt="ScreenCapture at Thu May 30 10:26:00 EDT 2019" src="https://user-images.githubusercontent.com/2098816/58806648-a2b02000-85e4-11e9-86cd-c992ab03b44d.png">

Current plan selection page:

<img width="1257" alt="ScreenCapture at Thu May 30 10:30:52 EDT 2019" src="https://user-images.githubusercontent.com/2098816/58806655-a643a700-85e4-11e9-931b-4b9bbd2e48af.png">

Desired plan selection page:

![image](https://user-images.githubusercontent.com/6981253/58890626-fd1ab080-86b8-11e9-9fd0-374fef0b7733.png)

## Acceptance criteria

1.
- Given a customer going through the main signup flow
- When they select "Online store" for the kind of site
- Then only Business and eCommerce plans are available for selection

2.
- Given a customer going through the main signup flow
- When they select anything other than "Online store" for the kind of site
- Then all current plans are available for selection

## Tasks

- [ ] Remove Free, Blogger, Personal, Premium from "Pick a plan page" if "Online store" is selected as kind of site

## References

- [`PlansStep`](https://github.com/Automattic/wp-calypso/blob/master/client/signup/steps/plans/index.jsx) component - plan selection signup step
- [`PlansFeaturesMain`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plans-features-main/index.jsx) component - shows plans in columns

**Comment by mattsherman** [comment]
@michaeldcain You mentioned that you thought things were built such that selection could be limited to a single plan. Do you remember where that is? I didn't see if when taking a quick look at the referenced components.

**Comment by mattsherman** [comment]
@fditrapani Is it acceptable from a design-perspective to simply show only the Business and eCommerce plans when in this scenario? In other words, no new design required?

**Comment by fditrapani** [comment]
> Is it acceptable from a design-perspective to simply show only the Business and eCommerce plans when in this scenario? In other words, no new design required?

That's right. This is what it would look like. 

![image](https://user-images.githubusercontent.com/6981253/58890626-fd1ab080-86b8-11e9-9fd0-374fef0b7733.png)

This can be dealt with in a separate issue but we should update the copy so that it clearly reflects the difference between the two plans.

**Comment by mattsherman** [comment]
@fditrapani @michaeldcain Should we also default/highlight the eCommerce plan instead of the Business plan? Or leave it how it is shown in the mockup from Filippo ("Start with Business" as the primary button, and "Popular" on the Business plan)?

**Comment by fditrapani** [comment]
It would be a pretty arbitrary decision on my part. Can you check in with @sararosso for that and any copy support?

**Comment by mattsherman** [comment]
> This can be dealt with in a separate issue but we should update the copy so that it clearly reflects the difference between the two plans.

#33600 has been opened to handle any copy improvements

@sararosso What are your thoughts on what plan to highlight and default to when a customer selected "Online store" as the kind of site they are building? Should it be Business or eCommerce?

**Comment by mattsherman** [comment]
> @sararosso What are your thoughts on what plan to highlight and default to when a customer selected "Online store" as the kind of site they are building? Should it be Business or eCommerce?

When @creativecoder @jonathansadowski @mattsherman discussed this yesterday, we all agreed it feels extremely off to be steering the customer to the Business plan, when that (currently) is a much poorer initial experience if you are creating an online store.

@michaeldcain @fditrapani @sararosso What are your thoughts on this?

**Comment by fditrapani** [comment]
> we all agreed it feels extremely off to be steering the customer to the Business plan, when that (currently) is a much poorer initial experience if you are creating an online store.

I guess it depends on the scope of work we're taking on but if we could direct Business plan customers right into the WP.com store then it could work well.

**Comment by mattsherman** [comment]
> I guess it depends on the scope of work we're taking on but if we could direct Business plan customers right into the WP.com store then it could work well.

Improving the Business plan experience to make the store more discoverable is currently a separate issue (https://github.com/Automattic/wp-calypso/issues/33341) that is out of the scope of our involvement. Let me check to see what the expected timeframe is for the resolution of that issue.

**Comment by niranjan-uma-shankar** [comment]
Should we similarly limit plan selection when the user clicks the `Start with eCommerce` on the landing page? 

Screen recording: https://cloudup.com/ckgKeCIb5dO

gif version:

![giphy (2)](https://user-images.githubusercontent.com/1269602/60602439-61708300-9dd1-11e9-9899-83bb08161145.gif)

This means that we just need to link the `Start with eCommerce` to the `ecommerce-onboarding` flow instead of the `ecommerce` flow.

**Comment by creativecoder** [comment]
> Should we similarly limit plan selection when the user clicks the Start with eCommerce on the landing page?

Or maybe skip the plans step all together when linking from that button, since a user has effectively already picked a plan?

See this related issue: https://github.com/Automattic/wp-calypso/issues/34253
