### ISSUE TITLE
Ecommerce Plan: Improve email verification experience

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#33541]
> As a new customer that has provided valid payment details, I want it to be clear that I need to verify my email address before setting up my store, so that I am able to proceed without confusion.

<img width="1552" alt="ScreenCapture at Thu May 30 11:26:12 EDT 2019" src="https://user-images.githubusercontent.com/2098816/58805328-db9ac580-85e1-11e9-838a-495feace0187.png">

Currently, we show two email verification notices to new customers after they pay for their eCommerce plan, and let them continue with creating their store, even though the next step is confusing (this only appears because the email address is unverified).

<img width="540" alt="ScreenCapture at Mon Jun 10 11:26:42 EDT 2019" src="https://user-images.githubusercontent.com/2098816/59206416-deae2c80-8b72-11e9-97ac-249262106284.png">

Email verification is currently a prerequisite for installing a plugin on a Business site (thus creating an Atomic site). So, we should limit our changes to improvement and simplification of the verification experience.

Improvements:
- Don't show email verification notices at all on the thank you page (the notices make it feel as if the customer did something wrong)
- Don't show "Create your store!" button at all, unless the either
    - An existing customer
    - The new customer has verified their email address already
- Reword thank you page to make it clear that the customer *needs* to check their email and confirm their address to continue
> Thank you for your purchase
> 
> Now that we have taken care your plan, we need to verify your email address to create your store.  Please click the link in the email we sent to {email@address.com}. Resend email
- When customer clicks the link in the confirmation email to verify their email address, take them to the first page of the Store setup wizard

<img width="587" alt="ScreenCapture at Mon Jun 10 11:24:47 EDT 2019" src="https://user-images.githubusercontent.com/2098816/59206529-1d43e700-8b73-11e9-8e1a-06639b994417.png">

## Acceptance criteria

1.
- Given a customer going through the main signup flow that hasn't verified their email address
- When they select an eCommerce plan
- Then no notices asking them to verify their email address are shown on the "thank you" page

2.
- Given a customer going through the main signup flow that hasn't verified their email address
- When they see the "thank you" page 
- Then "Create your store!" is unavailable

3.
- Given a customer going through the main signup flow with a verified email address
- When they see the "thank you" page 
- Then "Create your store!" is available (this includes polling if this page was shown and the user verified their email while this page was still up)

4.
- Given a customer that purchased an eCommerce plan
- When they verify their email address by clicking on the link in the email
- Then they are automatically taken to `*.wpcomstaging.com/wp-admin/admin.php?page=wc-setup`

## References

- paObgF-7Y-p2 (discussion of email verification)

**Comment by mattsherman** [comment]
Alternate approach discussed by @creativecoder @jonathansadowski @mattsherman during call yesterday:

- Don't show email verification notices at all on the thank you page (the notices make it feel as if the customer did something wrong)
- Don't show "Create your store!" button at all
- Reword thank you page to make it clear that the customer *needs* to check their email and confirm their address to continue
- When customer verifies their email address, take them to the first page of the Store setup wizard

What do you think @michaeldcain @fditrapani ?

**Comment by fditrapani** [comment]
> What do you think @michaeldcain @fditrapani ?

I agree with the notices looking like someone did something wrong. I like the direction you all are proposing. You have my vote with that approach.

**Comment by mattsherman** [comment]
> I agree with the notices looking like someone did something wrong. I like the direction you all are proposing. You have my vote with that approach.

Thanks @fditrapani. Would you be able to provide us with a design for this approach?

**Comment by mattsherman** [comment]
One detail that we will need to account for... if the user verifies their email address before they get to this page (which probably only would happen if the user has email notifications enabled and happens to see the "Activate" email while during signup -- side note... this is confusing), we should probably just show the current design (without the verification notices, of course).

**Comment by fditrapani** [comment]
> Thanks @fditrapani. Would you be able to provide us with a design for this approach?

Sure thing, here is some updated copy you can start with: 

-----

#### Thank you for your purchase
Now that we have taken care your plan, we need to verify your email address to create your store. Please click the link in the email we sent to {email@address.com}. [Resend email](#)

-----

Since I'll be at the design meetup, you can ping @shaunandrews for feedback on the PR.

> One detail that we will need to account for... if the user verifies their email address before they get to this page (which probably only would happen if the user has email notifications enabled and happens to see the "Activate" email while during signup -- side note... this is confusing), we should probably just show the current design (without the verification notices, of course).

Another case might be for an existing user that has already verified their email. Going with the current copy is fine.

**Comment by mattsherman** [comment]
> existing user

Thanks for reminding me of this scenario!

**Comment by creativecoder** [comment]
@mattsherman Regarding 4. in the description

> Given a customer that purchased an eCommerce plan
> When they verify their email address by clicking on the link in the email
> Then they are automatically taken to *.wpcomstaging.com/wp-admin/admin.php?page=wc-setup

See D29483-code

Note that as is, the email verification redirect works for any user who signed up for the eCommerce plan, whether or not they choose the site type of online store. Do you think this is okay?

To limit the redirect to users who selected online store, I believe we would need to save site type to user attributes on the server, as it seems to be stored only in Tracks right now.

**Comment by mattsherman** [comment]
> Note that as is, the email verification redirect works for any user who signed up for the eCommerce plan, whether or not they choose the site type of online store. Do you think this is okay?

I think that is reasonable. Given the name and positioning of the eCommerce plan, I don't see why somebody would purchase it unless they were setting up a store, so it is helpful to redirect them, even if they picked another type of site.

**Comment by creativecoder** [comment]
Thanks! This does bring to light the bigger piece that is missing: an ecommerce specific onboarding checklist. I the meantime, the Woo setup wizard is better than nothing at all.

**Comment by creativecoder** [comment]
Whoops... this isn't complete until D29483-code lands... reopening.

**Comment by jonathansadowski** [comment]
> Whoops... this isn't complete until D29483-code lands... reopening.

Silly "Fixes #..." magic. Thanks for reopening.

**Comment by creativecoder** [comment]
D29483-code has landed... closing out this issue!
