### ISSUE TITLE
Ecommerce Plan: Auto connect site to Jetpack; do not show Jetpack connection screen

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#33542]
> As a new eCommerce plan customer, I want to proceed to setting up my store without having to manually connect my site to Jetpack, so that I don't get confused.

Currently, auto-connection of eCommerce sites to Jetpack is not working. This causes customers to see a confusing Jetpack "Connect with WordPress.com" screen. This exposes too much of the implementation details of the site setup, and should be hidden from the customer.

<img width="1552" alt="ScreenCapture at Thu May 30 11:46:50 EDT 2019" src="https://user-images.githubusercontent.com/2098816/58806032-48628f80-85e3-11e9-9102-fa27013ff56f.png">

## References

- paObgF-7Y-p2 (discussion of Jetpack connection)
- p9o2xV-it-p2 (discussion of Jetpack connection)

**Comment by mattsherman** [comment]
@simison Would you happen to have any insight into why Jetpack connection is not automatically happening during eCommerce plan signup? See paObgF-7Y-p2 for video of the issue. Any pointers you could give us would be much appreciated! (I think @michaeldcain may have already asked you about this, so apologies if so, and you just haven't had a chance to respond yet!)

**Comment by simison** [comment]
@mattsherman nope, sorry. 😞 Wouldn't even know where to start looking.

@Automattic/jetpack-crew team generally knows a lot about the connection bits and how to debug it. I'd also loop in Atomic infra team.

**Comment by mattsherman** [comment]
This issue is invalid and will be closed. After further investigation, we determined that the current, by-design behavior requires a verified email address in order to install plugins on a site. And, if the email address is verified, the Jetpack connection does happen automatically, behind the scenes, with no user involvement.
