### ISSUE TITLE
Ecommerce Plan: Make it clear that a paid plan will be required if "Online store" is selected

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#33544]
> As an online store owner, I want it to be clear to me that I will need a paid plan in order to create an online store, so that I understand my initial investment.

Existing page:

<img width="1213" alt="ScreenCapture at Thu May 30 10:26:00 EDT 2019" src="https://user-images.githubusercontent.com/2098816/58806984-3e419080-85e5-11e9-8c7e-6fb1136832eb.png">

Update, with badge:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/191598/59287491-bf310580-8c3f-11e9-99bc-179ea9e68887.png">

## Tasks

- [x] Add badge to "Online store" item

**Comment by mattsherman** [comment]
@fditrapani Can you provide us with a design mockup of how we should style the "Online store" option to make it clear that selecting that will require a Business of eCommerce plan?

**Comment by fditrapani** [comment]
Sure thing, here it is: 

![Segments](https://user-images.githubusercontent.com/6981253/58890271-50d8ca00-86b8-11e9-9a07-99af11a5b45a.png)

It uses the [Badge component](https://wpcalypso.wordpress.com/devdocs/design/badge) with `light-gray-500` as it's background colour.

**Comment by mattsherman** [comment]
Thanks @fditrapani! Two comments/questions...

1. Do we use the term "subscription" anywhere else in the signup/product? I only see "plan". 
2. The alignment feels a bit off with that badge. Is it intended to be like that? We can always tweak once we get it in and have you review it, so probably not a huge deal right now.

**Comment by fditrapani** [comment]
Thanks for the question. 

> Do we use the term "subscription" anywhere else in the signup/product? I only see "plan".

The alternative would be "Plan required" and the thinking was that maybe the word "plan" is too early in the flow at this point. We didn't want to assume everyone meant that. What do you think?

> The alignment feels a bit off with that badge. Is it intended to be like that? We can always tweak once we get it in and have you review it, so probably not a huge deal right now.

I chose to align it to the baseline of the copy as to not mess with the spacing of the explanatory copy below. What do you have in mind?

**Comment by mattsherman** [comment]
What about "Paid plan required"? Because even a "Free Plan" is a plan. And, if we introduce this change after we introduce #33543, then the vagueness of "Paid" will be okay, since we will only offer them plans that are suitable.

I'd vote for avoiding "subscription" if we don't use that term anywhere else on WordPress.com to describe what is usually called a "plan".

I don't have a specific suggestion for the badge alignment right now. 

All that said, talking this through a bit more, I begin to wonder if we need this badge at all... after all, soon after selecting "Online store", they will be presented with the suitable plans. On this screen they aren't told the price or any other details. So, by badging this, are we potentially turning customers away before they have enough information to make an informed decision?

**Comment by fditrapani** [comment]
> All that said, talking this through a bit more, I begin to wonder if we need this badge at all... after all, soon after selecting "Online store", they will be presented with the suitable plans. On this screen they aren't told the price or any other details. So, by badging this, are we potentially turning customers away before they have enough information to make an informed decision?

This is a great point. The concern without the badge was that it would suck for someone to go that far only to find out that they had to pay. That being said, this is a business and we need to make money. People might be more likely to buy if they aren't deterred up front. I am ok with leaving out the badge. 

@michaeldcain any thoughts?

**Comment by michaeldcain** [comment]
My original thought about the badge was around setting user expectations - they won't really know at which point they've made a decision that locked them into a plan without either a badge up front or a note in the copy on the plans page. We should be doing one or the other.

**Comment by mattsherman** [comment]
@michaeldcain I don't follow. On the plans page they see the prices. And they can change their plan after signing up. What "lock in" are we talking about? What sort of note would we add to the plans page?

**Comment by michaeldcain** [comment]
Our acquisition marketing and landing pages would all be referencing starting for free, but if they choose an online store, then on an unrelated page (plans), they’ll be stuck with only two higher-priced options and no explanation. At minimum, we should use the sub header on the e-commerce plans page to reference the fact that an online store requires a paid plan.

**Comment by shaunandrews** [comment]
I hated the badge when I first saw it, but I think it might be the right path forward. It might lead to a drop in the number of people who enter the flow, but I'd wager that the people who do enter the flow would be more qualified and lead to an overall improvement in conversion.

Adding additional logic/copy to the plan page could be a good compromise, but it might lead to a wall for customers who aren't willing to pay for the higher-end plans.

**Comment by mattsherman** [comment]
@shaunandrews @michaeldcain What do you suggest for the badge text? "Subscription required" is not ideal, since we don't use the term "subscription" elsewhere (and, it is vague, assuming "subscription" === "plan"). "Plan required" is vague (as would be "Paid plan required")... everything requires a plan.

This is why I think the badge is a poor idea -- I don't think it really gives the customer enough information to help them make a decision.

Some sort of text on the plans page stating that these two paid plans are the only two that support eCommerce would be clear and shown at the point where we also show other information (price, features) to help the customer make a decision on what is best for them.

**Comment by michaeldcain** [comment]
I don’t see an issue with saying “requires paid plan” or “requires purchase”.

**Comment by shaunandrews** [comment]
> Some sort of text on the plans page stating that these two paid plans are the only two that support eCommerce would be clear and shown at the point where we also show other information (price, features) to help the customer make a decision on what is best for them.

The problem here is that the plans page is pretty late in the flow. Going back is an option, but not ideal. I'd wager many people would just give up and go elsewhere.

--

I like "Requires purchase" or "Purchase required" for the badge.

--

I tried out a few different treatments/placements for the badge:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/191598/59287491-bf310580-8c3f-11e9-99bc-179ea9e68887.png">

<img width="566" alt="image" src="https://user-images.githubusercontent.com/191598/59287507-c5bf7d00-8c3f-11e9-9c07-e6e4ec3a8c37.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/191598/59287517-cb1cc780-8c3f-11e9-8639-3ed07d3f41a1.png">

I'm leaning towards the first one (width the badge on its own line at the bottom). @fditrapani —  any thoughts?

**Comment by mattsherman** [comment]
@shaunandrews I like the first design as well.

**Comment by fditrapani** [comment]
> I'm leaning towards the first one (width the badge on its own line at the bottom). @fditrapani —  any thoughts?

Yeah, I think that works better for other languages and is less prone to breaking. The alignment seems a bit off with it though, the text "Requires purchase", nor the pill, don't seem to line up with the Online store copy.

**Comment by creativecoder** [comment]
Agreed on the alignment... otherwise this seems good to go. Maybe align the pill with above text?

<img width="573" alt="59287491-bf310580-8c3f-11e9-99bc-179ea9e68887" src="https://user-images.githubusercontent.com/1699996/59357843-265ac280-8cf1-11e9-947f-e075cbffc7b0.png">

**Comment by shaunandrews** [comment]
Ya'll picking on my sloppy mockups. I take blame, but I'm also looking sternly at Figma.

I intended to have the text aligned, with the pill shape breaking the margins a little.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/191598/59358631-e8629c00-8cfa-11e9-9a10-19c318b179f4.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/191598/59358683-003a2000-8cfb-11e9-9e79-d1bf9d741950.png">

Aligning the shape of the pill with the text feels strange, but I don't have a strong opinion as long as something lines up with something :)

**Comment by creativecoder** [comment]
Reopening--I've removed the badge temporarily because it was showing up in the Jetpack onboarding flow, as well.

**Comment by mattsherman** [comment]
@creativecoder What is required to wrap this up? Let's go with a simpler, yet less ideal solution for now if need be, so we can get this change out there to customers.

**Comment by creativecoder** [comment]
@mattsherman PR incoming: https://github.com/Automattic/wp-calypso/pull/34444
