### ISSUE TITLE
Jetpack checklist: hide autoupdates task when autoupdates are not allowed

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33559]
When autoupdates are not allowed, this checklist item is a bit awkward: 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/87168/58861022-1f5eff00-86b6-11e9-8d43-137de583469e.png">

<img width="567" alt="Screenshot 2019-06-04 at 10 45 02" src="https://user-images.githubusercontent.com/87168/58861006-18d08780-86b6-11e9-9c19-a69d8d9bd3be.png">

We should hide it when autoupdates are not possible.

cc @jeffgolenski is hiding this task ok in this scenario?

## replicate

- Test e.g. with a multisite (create one via Jurassic ninja special ops) or set `define( 'DISALLOW_FILE_MODS', true );` at your site.
- Open checklist at `https://wordpress.com/plans/my-plan/:site`
- Try autpupdates task

**Comment by iamgabrielma** [comment]
> We should hide it when autoupdates are not possible.

@simison  Quick question: for Atomic site auto-updates are forced even if the current settings are enabled/disabled , these are bypassed and auto-updates will happen anyway. 

Should I open a new report for this or could be part of the scope of this issue? In this case hide auto-updates because is not possible to disable them.

**Comment by simison** [comment]
Good question! We can have that as part of the scope here for now — I'd expect it can easily be just one PR.

**Comment by simison** [comment]
@iamgabrielma actually looking at this now, I don't see jetpack checklist for atomic sites. Although they are Jetpack, they're also under wpcom plans:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/87168/58871237-4fb09880-86ca-11e9-82f8-1a68b1e0ba18.png">

(see `http://calypso.localhost:3000/plans/my-plan/ATOMIC_SITE_URL`)

Did you get the list somehow visible for an Atomic site?

**Comment by iamgabrielma** [comment]
> Did you get the list somehow visible for an Atomic site?

Actually I don't! I see now that you were referring specifically to the list when I was meaning the calypsoified view on https://yourdomain.com/wp-admin/plugins.php 

<img width="1680" alt="Screen Shot 2019-06-05 at 09 29 27" src="https://user-images.githubusercontent.com/3812076/58926175-79be9500-8774-11e9-93e2-811521cae6ce.png">

I understand in this case is outside of the scope of the PR, right?

**Comment by simison** [comment]
Yep, that's outside of this scope.

Calypsoified styles are in https://github.com/Automattic/jetpack or otherwise atomic issues might be the best place.

**Comment by jeffgolenski** [comment]
> cc @jeffgolenski is hiding this task ok in this scenario?


Of course.
