### ISSUE TITLE
Stats: Post/Page Summary should just show title on header cake while loading

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#3358]
**Steps to reproduce:**
Click on post/page title from the Post & Pages module to view its summary.

The header cake displays the message "We don't have that post on record yet." while data is loading. It should just show the post/page title even while data is still loading.

![screenshot 2016-02-16 18 06 29](https://cloud.githubusercontent.com/assets/4924246/13097764/e2c00504-d4d8-11e5-8544-0a21636838b6.png)

As pointed out by @timmyc on here as well: https://github.com/Automattic/wp-calypso/pull/3265#issuecomment-184334981

**Comment by timmyc** [comment]
Thanks for opening this issue up @jancavan

**Comment by jancavan** [comment]
This is fixed in: https://github.com/Automattic/wp-calypso/pull/3380
