### ISSUE TITLE
Editor: Persist expanded accordion state as preference

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#336]
When a user expands or collapses an editor sidebar section, this preference should be persisted between page views as a user preference.

**Expected behavior:**
1. Navigate to the [Calypso editor](https://wordpress.com/post)
2. Select a site, if prompted
3. Expand a sidebar accordion item
4. Refresh the page
5. Note that the sidebar accordion item expanded in step 3 is expanded

raised by aduth

**Comment by alisterscott** [comment]
Confirmed still an issue. Since this wasn't covered in the recent editor redesign I am closing this out for now.
