### ISSUE TITLE
Ecommerce Plan: Clarify the differences between Business and eCommerce plans on plans page

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#33600]
> As a new customer, I want to understand the differences between the Business and eCommerce plans, so that I can select the plan that is best suited for me.

We should update the plans page to clarify the differences between the Business and eCommerce plans. 

Existing page:

<img width="1257" alt="58806655-a643a700-85e4-11e9-931b-4b9bbd2e48af" src="https://user-images.githubusercontent.com/2098816/58908589-f737c600-86de-11e9-8d8b-6432f9ee8a5b.png">

**Comment by mattsherman** [comment]
@sararosso Can you please help provide updated copy for the plans page to better clarify the differences between the Business and eCommerce plans.

/cc @michaeldcain @fditrapani @davemart-in in case this is already being planned in the context of another issue that I failed to find!

**Comment by sararosso** [comment]
@mattsherman what specific questions would a copy change help address? What problems or confusion have been identified that can serve as a reference?

**Comment by fditrapani** [comment]
For more context @sararosso this will be for folks that identify they want to create an online store. We will only be showing them the business + ecommerce plans in signup. The default copy for business doesn't explain how, as a plan, it's suited for creating online stores or how it's different from the ecommerce plan.

**Comment by mattsherman** [comment]
@fditrapani Should we use the same updated copy on the general plans page, or only when going through the "Online store" scenario? I'd vote for keeping things consistent and showing the updated copy always.

**Comment by mattsherman** [comment]
@sararosso For more context, also see paObgF-7Y-p2, from which this originally came.

**Comment by fditrapani** [comment]
Ideally we tailor the plans copy for each segment accordingly so we can optimize for conversion. Each group is looking for something different in the plans so having them all say the same thing might not be as effective.

**Comment by davemart-in** [comment]
@mattsherman My 2 cents: I'd punt this one in your current sprint. This is not a bug, more like an update/improvement IMO.

**Comment by mattsherman** [comment]
@davemart-in Agreed. Just trying to collect some info based on Filippo's idea. This is definitely an enhancement.

**Comment by mattsherman** [comment]
Removing from Samus's current Priority Exception backlog. This is definitely an issue that deserves further consideration from another team in the future though!
