### ISSUE TITLE
Can't add new tags with classic editor active

### ISSUE THREAD

**Issue by tijosh** [Automattic/wp-calypso#33606]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Go to My Site > Site > Posts > Select a Post
3. Ensure Classic Editor is active
4. Click into the tags editor to add a new tag

#### What I expected

The editor allows me to add tags

#### What happened instead

The editor kicks me out of the tags field

#### Browser / OS version

Any

#### Screenshot / Video

![Screenshot](https://cld.wthms.co/CH1jB2+)

#### Context / Source

#13218115-hc

**Comment by tanjoymor** [comment]
Another case here #13218632-hc

**Comment by JessBoctor** [comment]
Had another case here: #8658631-HC

I was also able to replicate this issue on a test site.

**Comment by grvrulz** [comment]
Another one in 13117750-hc

**Comment by galakhyati** [comment]
Another one in 13239024-hc

**Comment by KokkieH** [comment]
> Go to My Site > Site > Pages > Select a Page

With the exception of a small number of themes that use page tags, pages in general don't use tags, so I wouldn't expect to be able to add tags to a page. Nor is it possible to add categories to a page, and in your GIF I can see the bottom of the Categories section. 

Did you perhaps intend to say Posts, rather than Pages?

**Comment by tijosh** [comment]
> Did you perhaps intend to say Posts, rather than Pages?

Yes. Edited original comment.

**Comment by blowery** [comment]
Digging into this. I can repro locally.

**Comment by aamills** [comment]
Another report in 562752-hc
Follow up started to user in 2087262-zen

**Comment by JoshuaGoode** [comment]
Another report on 13225198-hc
Follow-up: 2087512-zen

**Comment by kcswong** [comment]
Another report in 12938446-hc
Follow-up: 2087651-zen

Gave them the workaround to add tags in WP-Admin for the time being.

**Comment by arcangelini** [comment]
Same here ⇢ 12846624-hc
Followup ⇢ 2084151-zen

**Comment by CompChris** [comment]
Another report: 13246054-hc
