### ISSUE TITLE
Gutenberg: Embeds: Facebook embed doesn't work with URL of the Facebook update through mobile

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#33625]
This might be more about a feature request rather than an issue.

If we try with the Facebook update URL we can get through a PC browser, the embed works. But it doesn't work with the URL we can get through a mobile browser.

**_Example:_**
Works: https://www.facebook.com/StarWars.jp/photos/a.210681582325219/2438309436229078/
Doesn't work: https://m.facebook.com/story.php?story_fbid=2438309742895714&id=184716408255070

### Steps to reproduce
1. Go to "**_My Sites > Site > Posts_**" and click on "**_Add New Post_**"
2. Make sure that a block editor is active
3. Paste a Facebook photo link (which we can get by accessing Facebook through mobile browser) such as https://m.facebook.com/story.php?story_fbid=2438309742895714&id=184716408255070 in Paragraph block or Facebook block

### What I expected
A Facebook embed shows up like this in the post:
![Screen Shot on 2019-06-05 at 13:40:09](https://user-images.githubusercontent.com/32432463/58930725-a932c900-8797-11e9-92fa-bcccff9c895e.png)

### What happened instead
Only a link shows up instead:

![Screen Shot on 2019-06-05 at 13:38:35](https://user-images.githubusercontent.com/32432463/58930742-c36ca700-8797-11e9-9e39-04b1aecb7d68.png)

**Comment by arunsathiya** [comment]
I am seeing this for a WordPress.org site with Gutenberg as well. Seems to be a core issue, and I am not seeing a related report on [this search](https://github.com/search?utf8=%E2%9C%93&q=repo%3AWordPress%2FGutenberg%20is%3Aissue%20facebook%20mobile%20link) or similar ones. 

I am closing this report, @hacchism - could you flag this up at https://github.com/WordPress/gutenberg/issues/ as a OSS citizen, please?
