### ISSUE TITLE
Full Site Editing: header changes pre-publish confirmation [3]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#33629]
Before the header changes have been published/updated, a pre-publish confirmation should be shown:

<img width="624" alt="Screenshot 2019-06-05 at 13 43 16" src="https://user-images.githubusercontent.com/1182160/58953931-0fb7e700-8798-11e9-8b11-37b1bbc9a531.png">

Given the context this flow should be applied when editing `wp_template` and `wp_template_part` CPTs in general.

**Comment by mattwiebe** [comment]
I'll take this easier one to ease back into the flow

**Comment by mattwiebe** [comment]
"Easy" he says, not recognizing that he'll need to roll his own post-publish experience since this is for updates, not the initial publish. 🙃

**Comment by vindl** [comment]
> "Easy" he says, not recognizing that he'll need to roll his own post-publish experience since this is for updates, not the initial publish. 🙃

I think we can propose some alternatives when it comes to messaging if that one turns out to be tricky.
