### ISSUE TITLE
Desktop App: There is no option to use/access 'Store' via the desktop app on a business plan

### ISSUE THREAD

**Issue by garymurray** [Automattic/wp-calypso#33630]
#### Steps to reproduce

View and WordPress.com site on a business plan from the Desktop App after installing a custom plugin.

#### What I expected

To see the Store menu item so that I could either create a store, or continue using the Store I had created if I had been doing it via wp-admin

#### What happened instead

There is no option to access the Store settings via the desktop app.

#### Browser / OS version

Desktop app V4.1.0 for Mac

#### Screenshot / Video

<img width="141" alt="screenshot-2019-05-31-at-15 39 36" src="https://user-images.githubusercontent.com/10805911/58954504-43dbd980-8791-11e9-8bb3-dd80d25509f0.png">

**Comment by rachelmcr** [comment]
The store tab is currently disabled in the desktop environment by disabling the store management experience (with the feature flags `woocommerce/extension-*`) in the desktop config:

https://github.com/Automattic/wp-calypso/blob/6969fb8c697d4deced72015a7a2c59f9839c4782/config/desktop.json#L101-L118

Enabling or removing those feature flags should make the store tab available in the app, if it's ready and working in the app environment. Feel free to ping me when that's done if you'd like further beta testing attention on it after it's enabled.

**Comment by designsimply** [comment]
Re-tested and confirmed as part of WPDesktop 6.7.0-beta2 testing and wanted to add my notes for reference.

Steps to reproduce:

1. Open the Desktop App, log in, open a free site.
1. Go to Plans > Business site and online stores > eCommerce > Upgrade.
1. Follow the prompts to complete the purchase.
1. Click the "Create your store!" button.
1. Land at the web for a Jetpack connection step.
1. Close and re-open the app, and observe that there is no store section.

Video: [4m6s](https://cloudup.com/cOIUCIrATRA)
<sup>Tested with WPDesktop 6.7.0-beta2 on macOS 10.15.6.</sup>

Create your store!|Land on web not app|Store missing from the app
---|---|---
![create-your-store-button-post-purchase-wpdesktop-6 7 0-beta2](https://user-images.githubusercontent.com/1119271/102673105-03b03200-4150-11eb-8e91-c1e350d593c4.png)|![landing-page-after-clicking-create-your-store-button-post-ecommerce-plan-purchase-wpdesktop-6 7 0-beta2](https://user-images.githubusercontent.com/1119271/102673132-19255c00-4150-11eb-9b3e-66b5114692f0.png)|![Screen Shot 2020-12-18 at Dec 18 4 13 11 PM](https://user-images.githubusercontent.com/1119271/102673138-1fb3d380-4150-11eb-990d-e1ef9e54e0a6.png)

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
