### ISSUE TITLE
Remove Upwork entry points in Help and Support

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#33665]
The Upwork referral entry points need to be removed from the following:

1. Support - https://en.support.wordpress.com/
2. Help - `/help`
3. Help popover

cc @belcherj @pcdonohue

**Comment by belcherj** [comment]
Help popover: https://github.com/Automattic/wp-calypso/pull/31096

**Comment by belcherj** [comment]
Completed
