### ISSUE TITLE
Purchases: Table gets cut off at small to medium screen widths

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#33690]
Noticed these visual quirks as I was testing another issue:

<img width="716" alt="Screen Shot 2019-06-05 at 9 06 59 PM" src="https://user-images.githubusercontent.com/2124984/58999975-778d2280-87d6-11e9-80cb-c352f07c9fa0.png">

<img width="701" alt="Screen Shot 2019-06-05 at 9 10 18 PM" src="https://user-images.githubusercontent.com/2124984/58999976-778d2280-87d6-11e9-8e7a-806d56dfa657.png">

1) Go to Me -> Manage Purchases and resize your screen to ~700px wide.
2) Note the charges get cut off, or "float" outside the given content area.
3) The pagination could also be optimized to fit in the space, rather than splitting to two lines.

**Comment by danieldudzic** [comment]
Hi @sixhours,

I have tested this, but was unable to replicate the issue with the cut off charges both in Firefox and Chrome with browser window set to 700px width:

![Billing_History](https://user-images.githubusercontent.com/905781/60212692-1cdd6880-9862-11e9-988a-cb4236493a22.jpg)

Perhaps there was an update that took care of it? :)

**Comment by sixhours** [comment]
It's still happening for me; it's because I have some pretty long domain names in there, like this one:

`testingwcsignupbusinessforeigncountrycalobee.wordpress.com`

Definitely an edge case, but one we could pretty easily account for with some smarter overflow rules.
