### ISSUE TITLE
Checklist: Fix section hiding in Jetpack checklist

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#33698]
Checklists can hide completed tasks. If a sections tasks are completely hidden, the section header should probably be hidden?

Note how "Performance Tools" seems out of place here:

![Screen Shot 2019-06-06 at 11 52 01](https://user-images.githubusercontent.com/841763/59024237-c4faa580-8851-11e9-8487-0af5e1af78d4.png)

@jeffgolenski any thoughts on this?

Related: #33571

**Comment by jeffgolenski** [comment]
@sirreal Yes definitely. Let's make it vanish!

**Comment by simison** [comment]
We'll remove sections altogether instead https://github.com/Automattic/wp-calypso/issues/33748
