### ISSUE TITLE
Blocked Sites Needs Context

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#33700]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/me/site-blocks
2. If you do not have any blocked sites, you will see "Blocked sites will not appear in your Reader and will not be recommended to you. You haven't blocked any sites yet." without any context.

#### What I expected
Explanation or link to support article able what a blocked site is.

#### What happened instead
No info or context.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/3011211/59032449-eea0d600-882b-11e9-8200-8e536d848a19.png)

HT @mikeshelton1503 for the report.

**Comment by mikeshelton1503** [comment]
There is no support doc that exists to link to for instructions on how to block a site. I've requested one to be created.

**Comment by sixhours** [comment]
> There is no support doc that exists to link to for instructions on how to block a site. I've requested one to be created.

@mikeshelton1503 Where did you request a doc be created? Just wondering so I can keep an eye on it and follow up when it's ready.
