### ISSUE TITLE
Jetpack: Set up JS trigger for heatmaps specific to jp checklist 

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#33712]
As mentioned in slack, the wordpress.com and jetpack checklists share the exact same URL structure. In order to properly distinguish between them in hotjar, we'll need to set up a JS trigger for jetpack specific interactions. 

heatmaps: https://help.hotjar.com/hc/en-us/articles/115011867948-Using-JavaScript-to-Trigger-Heatmaps
anon screen records: https://help.hotjar.com/hc/en-us/articles/115015712548-How-to-Use-JavaScript-Triggers-to-Start-Recordings

Ideally the triggers should start right at the thank you page dialog for jetpack customers.

**Comment by simison** [comment]
>Ideally the triggers should start right at the thank you page dialog for jetpack customers.

Should it trigger also when the customer lands on the checklist from wp-admin and won't see the thank you dialog?

**Comment by sirreal** [comment]
#33732 implements this
