### ISSUE TITLE
FSE: Dynamic Previews: Design Explorations

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33728]
Tracking ticket for design explorations for dynamic previews in the page template selector.

**Comment by jasmussen** [comment]
Here's a quick mockup:

<img width="1282" alt="Template Previews" src="https://user-images.githubusercontent.com/1204802/59095371-9562a080-8918-11e9-8b9b-be1e7f0bbc70.png">

The page templates and the preview, in this mockup, would both use an actual HTML preview like what is already present in Gutenberg block variations. For an example of what we have, insert a quote block in Gutenberg, then press the block switcher button, or open the sidebar, to see previews. 

Those previews are not great, often cropped or badly sized, but Codepen.io uses the same general method to create previews, and previews there work great. So the mockups shown assume that we can improve previews in the block editor to reach the same fidelity that codepen thumbnails have. 

Thumbs on left use 4/3, the preview on the right would use 3/4 aspect ratio. Both aligned top/center. Worth noting that we might want to just use 3/4 aspect ratio for both the small thumbnails on the left, and the big ones on the right. 

On mobile, you would not see the “Preview” pane at all, you’d see “only” the thumbnails with integrated previews on the left.

**Comment by obenland** [comment]
@iamtakashi @allancole @enriquesanchez @alexislloyd When you get a chance, could you leave a first round of design feedback here, to start iterating on the mockup?

**Comment by obenland** [comment]
> Worth noting that we might want to just use 3/4 aspect ratio for both the small thumbnails on the left, and the big ones on the right.

If we had four columns of previews with a 3/4 aspect ratio, I wonder if we even needed the right-hand preview then. I reckon the the thumbnails themselves wouldn't be much smaller.

**Comment by jasmussen** [comment]
> If we had four columns of previews with a 3/4 aspect ratio, I wonder if we even needed the right-hand preview then. I reckon the the thumbnails themselves wouldn't be much smaller.

This sounds like it could be a good first iteration, and then we can proceed further if necessary.

**Comment by enriquesanchez** [comment]
Agree with @obenland, I feel like there's no need for a separate preview if the thumbnails themselves are big enough and with a 3/4 aspect ratio. This should also avoid us from having a separate experience for smaller screens.
