### ISSUE TITLE
Jetpack checklist: highlight inline-help button in checklist tour

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33733]
During the initial checklist tour, we could point out the help button so that users know where to seek support if they get lost during onboarding:

<img width="957" alt="Screenshot 2019-06-07 at 14 05 20" src="https://user-images.githubusercontent.com/87168/59099955-4e32da80-892d-11e9-9adc-172599850cc8.png">

There are many elements and navigation items in Calypso and help button might not be the most obvious one to notice before you've spent some time in Calypso.

I copied the text example from this but it could obviously say something else. Shorter and more to the point the better, methinks:

<img width="400" alt="Screenshot 2019-06-07 at 14 05 20" src="https://user-images.githubusercontent.com/87168/59099986-63a80480-892d-11e9-8b71-5bbf2ed0596c.png">

cc @jeffgolenski thoughts?

Checklist tour is in `client/layout/guided-tours/tours/jetpack-checklist-tour`

**Comment by Aurorum** [comment]
PR in #39063 for this issue. :)

**Comment by davipontesblog** [comment]
Moved to Jetpack Improved Onboarding for triaging.

**Comment by Aurorum** [comment]
Could it be moved to Needs Review? I think that PR should still work. :)

**Comment by folletto** [comment]
Heya! I was doing some triaging, and I reviewed this with Design and with Happiness.

We were wondering about the benefits of having such an explicit callout for support. Our support levels seem ok, so... did we have any evidence that people can't find a way to reach out? 

It also seems a broader question to me, and not something that should be specifically resolved in Jetpack.

So — and with specific apologies to @Aurorum — I'd advise to close this issue, until we get to a point where we have some evidence that this is needed, and if yes, we should review with Dotcom and HEs too.

**Comment by Aurorum** [comment]
No worries, thanks @folletto. I'll close the PR as soon as the issue is settled and closed. :)

**Comment by folletto** [comment]
Closing per above discussion.
