### ISSUE TITLE
Non-retina circular progress bar during site setup

### ISSUE THREAD

**Issue by jwold** [Automattic/wp-calypso#33735]
#### Steps to reproduce
1. On a site that's only partially setup, visit a url such as: https://wordpress.com/stats/day/testingground728.blog 
2. Notice the setup banner: https://d.pr/i/gESI8a, it's blurry on a retina device

#### What I expected

A retina circular progress image

#### Browser / OS version

MacBook Pro (15-inch 2018)
Resolution: scaled to look like 1440x900
macOS Mojave
Version 10.14.5

Google Chrome 74.0.3729.169 (Official Build) (64-bit)

#### Screenshot / Video

![Screen Shot 2019-06-07 at 13 12 23](https://user-images.githubusercontent.com/3411173/59100669-0d37c780-8927-11e9-8d2b-76143c2d8ad4.png)

#### Context / Source

In getting ready for the All Design Meetup, I was prepping my local machine for bottle pickup. I saw something I thought I could dig into, a blurry graphic. 

What's the problem?

In Calypso the circular setup completion gauge is blurry on a retina device. 

Screenshot: https://d.pr/i/gESI8a

In inspecting the element I saw that it uses HTML5 Canvas.

Screenshot: https://d.pr/i/BMyu9q

I thought I found a simple solution at first: https://coderwall.com/p/vmkk6a/how-to-make-the-canvas-not-look-like-crap-on-retina

However, to generate that Canvas it appears we're using Canvas Gauge as a library to create circular progress graphics. 

I checked their repo and saw an issue that appears to resolve the retina issue: https://github.com/Mikhus/canvas-gauges/issues?utf8=%E2%9C%93&q=retina

My question is, should I open a new issue on their repo, or is there a workaround we can do on our end?

**Comment by arunsathiya** [comment]
I have seen this a lot of times as well, and someone had failed to file a report here. Thanks for bringing it up!

**Comment by MichaelArestad** [comment]
I can't seem to get this one resolved. I can get really close by essentially doubling the image size and then using CSS to scale it down, but an invisible box of the original canvas size seems to push on other wrappers/containers. Will take another shot at it sometime in the future.

**Comment by jwold** [comment]
Thanks for trying!

Is it using a special library? Looked like it was something we couldn’t
just tweak in html canvas. More than I could figure out. Ha

**Comment by MichaelArestad** [comment]
It's not using a special library. It's using the standard canvas tools. What needs to happen is that we need to draw everything at twice the size and then scale it down (just like we do with images). However, I'm not super familiar with the idiosyncrasies of canvas and how it behaves to make this likely simple change.
