### ISSUE TITLE
Jetpack checklist: update thank you modal visuals

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33731]
In PR https://github.com/Automattic/wp-calypso/pull/33406 (issue https://github.com/Automattic/wp-calypso/issues/33319) we moved the "thank you" page to a modal:

<img width="1735" alt="Screenshot 2019-06-07 at 13 10 08" src="https://user-images.githubusercontent.com/87168/59097199-9b12b300-8925-11e9-80fb-78f6af7ace7c.png">
<img width="1521" alt="Screenshot 2019-06-07 at 13 10 02" src="https://user-images.githubusercontent.com/87168/59097200-9bab4980-8925-11e9-81f8-239dcdffcc8b.png">

Let's change this modal to look more like the .com modal looks like:

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/191598/57865657-fdb3db80-77cb-11e9-8662-679d7b87e539.png">

@jeffgolenski I'm assuming the same change for both "progress-bar" as well "continue" -steps?

Remember to mind the mobile; the image can be hidden for small screens.

**Comment by jeffgolenski** [comment]
I'm really only concerned with implementing the shadow and dark overlay to force focus on the modal @simison - right now there isn't much contrast and it's difficult to focus
