### ISSUE TITLE
Reader Discover: The Discover Header doesn't look like a link.

### ISSUE THREAD

**Issue by scalarbane2** [Automattic/wp-calypso#33747]
#### Steps to reproduce
1. Go to WordPress.com
2. On the reader page, click "discover"
3. On the discover page click the "Discover" title.
4. It goes to the new https://discover.wordpress.com

It is not obvious to users that the header links to another site. What other ways can this be represented?
#### Screenshot / Video
<img width="1446" alt="Screenshot 2019-06-07 at 3 47 12 PM" src="https://user-images.githubusercontent.com/50745054/59112814-ae307d80-893b-11e9-8e20-dfda23f5f3bc.png">

**Comment by dreamertim** [comment]
I looked into this and came up with a solution. The code could be removed from these two places to remove the link:

https://github.com/Automattic/wp-calypso/blob/28fd561063de6d9a1291062a7a66abdf47de34c5/client/blocks/reader-feed-header/index.jsx#L96

https://github.com/Automattic/wp-calypso/blob/28fd561063de6d9a1291062a7a66abdf47de34c5/client/blocks/reader-feed-header/index.jsx#L106

However, this doesn't effect just the Discover page in the Reader. It would also effect the "Site View" page (click "Followed Sites", then click the name of a blog you follow).

I don't think it would be bad to remove this from either page. It isn't obvious that this is a link.

An additional fix might be to move the link to the upper-right of the card, under the Follower count and Follow button, and adding the external link grid icon.

**Comment by scottsweb** [comment]
It is worth noting that the link colours across the page vary quite a bit based on the theme you are currently using:

<img width="1439" alt="Screenshot 2019-09-15 at 10 47 34" src="https://user-images.githubusercontent.com/411945/64923288-8c4e5e80-d7a6-11e9-8abd-6db5853acac0.png">

<img width="1438" alt="Screenshot 2019-09-15 at 10 48 07" src="https://user-images.githubusercontent.com/411945/64923293-93756c80-d7a6-11e9-8a02-87102a10b734.png">

<img width="1440" alt="Screenshot 2019-09-15 at 10 48 55" src="https://user-images.githubusercontent.com/411945/64923295-983a2080-d7a6-11e9-9a22-42e36139e2dc.png">

**Comment by scottsweb** [comment]
Given that the article titles are obviously clickable (only way to read the article), I think we should move to using the primary page link colour for the site/blog title. It should aid with discoverability.
