### ISSUE TITLE
Android Post Image Editor: usability bugs

### ISSUE THREAD

**Issue by osullivanchris** [Automattic/wp-calypso#33742]
Issue lives here https://github.com/wordpress-mobile/WordPress-Android/issues/8416

#### Steps to reproduce
1. Edit a post
2. Add an image
3. tap on the image

#### What I expected
Clear actions to confirm or reject the changes 

#### What happened instead
- The top right contains a negative action (remove image)
- The top left has an 'x' which closes the view, and is actually the positive action

#### Screenshot / Video
![46813178-e799f480-cd7e-11e8-829c-fcfc7a1c0275](https://user-images.githubusercontent.com/50576199/59107492-acad8800-8930-11e9-97be-90f7e17441e2.png)

#### Context / Source
Found on our mobile groundskeeping board
This definitely has some usability issues. The behaviours are also completely different on iOS and Android
Seems like something I can design in a day, and get on a team's backlog to build.

**Comment by lancewillett** [comment]
@osullivanchris Should we close this one in favor of the Android issue? We can track it there directly, since this repo tracks the web app (Calypso) only.

**Comment by osullivanchris** [comment]
@lancewillett hey! Yes the Android issue is more relevant. I only made this one so it could be tracked as part of the Fixing the Flows / Bottle Pickup initiative during the Design Meetup.
