### ISSUE TITLE
Jetpack checklist: combine the two lists into one

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33748]
To simplify things going forward, let's combine the two lists into one:

So the titles highlighted here can go away:

<img width="765" alt="Screenshot 2019-06-07 at 17 46 06" src="https://user-images.githubusercontent.com/87168/59112717-3fa7eb80-894c-11e9-882c-dcf4c7d510da.png">

Like so:

<img width="741" alt="Screenshot 2019-06-07 at 17 46 22" src="https://user-images.githubusercontent.com/87168/59112725-446c9f80-894c-11e9-9312-2da419d1139a.png">

The order of the items can stay as-is for now.

This should make it a bit easier to implement design changes that are unifying the checklists for .com and Jetpack (https://github.com/Automattic/wp-calypso/pull/33666)

We also wouldn't need to figure out what to do with temporary solutions to make the two lists work (e.g. https://github.com/Automattic/wp-calypso/pull/33548/files#diff-3964e898582a8b8558983dd0677b543aR73).

cc @fditrapani @jeffgolenski

**Comment by fditrapani** [comment]
I should note that with my upcoming changes my other branch, things will feel less overwhelming as we will only have one task expanded to task and people will be able to expand/collapse the other tasks as they see fit.

**Comment by simison** [comment]
Yasss good point @fditrapani.  Also, performance bits are not available to the public yet so they'd see security parts only for now.
