### ISSUE TITLE
Signup: broken site preview image layout in Professional flow with latest Safari on macOS

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#33758]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/start/site-type
2. Select Professional site type
3. Note the image layout in the preview

#### What I expected

A nice-looking site preview

Image:

<img width="1396" alt="Screen Shot 2019-06-07 at 10 54 17" src="https://user-images.githubusercontent.com/66797/59123801-ef606780-8912-11e9-9783-a9e474d735d4.png">

URL: https://a8cvm4.files.wordpress.com/2019/05/flowers.jpg?w=480&strip=all&quality=80

#### What happened instead

The image is stretched and weird and tall

<img width="1396" alt="Screen Shot 2019-06-07 at 10 54 09" src="https://user-images.githubusercontent.com/66797/59123784-ea031d00-8912-11e9-95e5-afd0af7e4f0b.png">
<img width="1396" alt="Screen Shot 2019-06-07 at 10 54 11" src="https://user-images.githubusercontent.com/66797/59123786-ea031d00-8912-11e9-892a-358fd54e8374.png">

#### Browser / OS version

Safari desktop 12.1.1 on macOS Mojave 10.14.5

CC @Automattic/zelda

**Comment by ramonjd** [comment]
Mmm, I can't reproduce.

<img width="400" alt="Screen Shot 2019-06-08 at 8 44 53 am" src="https://user-images.githubusercontent.com/6458278/59137576-c6e87400-89cb-11e9-8378-965c01aaee80.png">

Maybe it's been fixed overnight?

I think there were some tweaks to Professional base site (a8cvm4) however so I've gone ahead and regeneration the Professional annotation JSON.

D29251-code

**Comment by lancewillett** [comment]
Still broken for me. What browser / OS are you testing with?

**Comment by lancewillett** [comment]
Firefox and Chrome latest stable versions on macOS look as expected; seems to be only Safari in my testing. Tried both new user and existing user.

**Comment by ramonjd** [comment]
> seems to be only Safari in my testing. Tried both new user and existing user.

Ah, my bad. Now I see it. Only seems to occur in the iframe, but I can't see any difference in the style definitions yet. Needs further 👀 .

I've added it to our board.

Thanks 👍

**Comment by lancewillett** [comment]
Thanks; looking great now in another test with Safari.

<img width="1372" alt="Screen Shot 2019-06-10 at 21 54 41" src="https://user-images.githubusercontent.com/66797/59244682-578ca300-8bca-11e9-88b8-8705eb60fb3b.png">
<img width="1372" alt="Screen Shot 2019-06-10 at 21 54 43" src="https://user-images.githubusercontent.com/66797/59244683-578ca300-8bca-11e9-9638-223e851bcc6f.png">
