### ISSUE TITLE
Add Ability to Copy a Post/Page's Permalink from the Post/Page List

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#33764]
#### Steps to reproduce
1. From My Site > Site > Pages/Posts
2. Click on the … icon next to a post title

#### What I expected
There should be a "Copy permalink" option, which copies the post/page's URL to the clipboard.

#### What happened instead
The option doesn't exist

#### Context / Source
#anecdote

This would be a nice feature to add as it would help streamline the process of sharing a URL to a recent post or page elsewhere — without having to navigate directly to the post/page first or right-clicking and copying the URL from the "View" option.

**Comment by lancewillett** [comment]
<img width="234" alt="Screen Shot 2020-03-11 at 00 20 10" src="https://user-images.githubusercontent.com/66797/76392064-13cbf300-632e-11ea-85b5-325d417d9c23.png">

Just a note to say this feature now exists —  added in October 2019 with #37049
