### ISSUE TITLE
Themes: "Available Icons" List Stacking

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#33768]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/baskerville-2
2. Scroll to Available Icons

#### What I expected

The list to be floating next to each other. 

#### What happened instead

![Screenshot_20190608-161421](https://user-images.githubusercontent.com/43215253/59149076-f073c080-8a08-11e9-92ef-4b65fe3fa29b.jpg)

#### Browser / OS version

Samsung Galaxy Tab S2, Android 7

**Comment by timmdunker** [comment]
Potential fix: 

Line 849 in the css:

```
ul,ol {
    margin: 0 0 1.5em 1.5em;
    /*     margin: 0 0 1.5em 3em; */ <- This was the default value.
}
```

Remember it will affect the placement of the unordered lists on the other page.

**Comment by obenland** [comment]
@Aurorum Is this something you'd want to take a stab at fixing by any chance? Could be as simple as limiting list-item widths to 50% on small screens

**Comment by Aurorum** [comment]
I'm not sure this is something which can/should be fixed with styling added to Calypso (sorry, not sure I realised that when I made this issue). It seems to be that the lists have their own styling to make them sit next to each other. If a `max-width` was to be imposed upon all lists within Calypso, I think that'd also affect those lists where they should be full width.

For example, you'd end up with something like this, and I can't really think of a solution around that.

<img width="619" alt="Screenshot 2021-03-19 at 15 03 39" src="https://user-images.githubusercontent.com/43215253/111800933-5bcc1100-88c4-11eb-8d45-9ea52bc84535.png">

**Comment by valterlorran** [comment]
I believe that the best option is by merging both lists into one and using the `columns` style to create the columns automatically:

```html
<ul style="columns: 2"> 
  <li></li>
  ...
</ul>
```

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/columns

**Comment by valterlorran** [comment]
I fixed the issue by editing the theme description with the html that I [mentioned above](https://github.com/Automattic/wp-calypso/issues/33768#issuecomment-1105480713). However it is not working on the Calypso theme show case, seems to be some sort of cache.

**Before**
<img width="506" alt="Screen Shot 2022-04-25 at 11 19 48" src="https://user-images.githubusercontent.com/1234758/165134386-a9795a70-6b9e-4300-94c6-d5abcb80a14f.png">

**After**
<img width="621" alt="Screen Shot 2022-04-25 at 13 40 40" src="https://user-images.githubusercontent.com/1234758/165134560-fefd2559-5dca-4c04-91b0-2dd8830b0b88.png">

**Comment by valterlorran** [comment]
The cache seems to have cleared itself, and now it's working on the Calypso theme showcase.
