### ISSUE TITLE
Gutenberg: Update Plugin to v5.9 [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33796]
The next Gutenberg release is planned to be released on 6/12.

See additional instructions in PCYsg-m14-p2

**Comment by gwwar** [comment]
Around 4 points spent for sprint 23-24

**Comment by kwight** [comment]
I'd say another point for the deploy and e2e kerfuffle today.

**Comment by gwwar** [comment]
reopening for the last snackbar regressions

**Comment by kwight** [comment]
@gwwar Should we close this and go straight to 6.0? https://github.com/Automattic/wp-calypso/issues/34016

**Comment by gwwar** [comment]
Yes, Kirk let's close this out. Thanks for the reminder! 

Noting that we were unable to land this due to https://github.com/WordPress/gutenberg/issues/16194
