### ISSUE TITLE
Jetpack settings: sites with fresh plan purchases cannot activate features

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33794]
#### Steps to reproduce
1. Create a new Jetpack site
2. Connect it and purchase a professional plan
3. Go to settings `https://wordpress.com/settings/performance/:SITE`
4. Try switching on Search or VideoPress, get this error via API:
    ```
    {"error":"not_supported","message":"The requested Jetpack module is not supported by your plan."}
    ```
    and this in UI:
    <img width="463" alt="image" src="https://user-images.githubusercontent.com/87168/59201932-32853980-8ba4-11e9-877d-9e0ed601473c.png">

The API that returns `not_support` seems to be `/jetpack/v4/module/*/active/`:

```
error    not_supported
message    The requested Jetpack module is not supported by your plan.
```

Affects not only Search and Video, but any paid module, such as SEO, google analytics etc.

5. If you now visit wp-admin, and then try again in Calypso — switching the setting works.

Convo p1559832260010200-slack-jetpack

@gwwar mentions:
>Either requires a query component call for fresh data in that section or looking at sync ordering

cc @dereksmart @p3ob7o @Automattic/luna

**Comment by simison** [comment]
Some more chatter p1560176800132800-slack-jetpack-crew

So the problem seems to be (quoting mostly @dereksmart):

Jetpack site relies on two things to determine plan features:
    1. Update via heartbeat cron (every 24hrs)
    2. A visit to the Jetpack admin (used to be the default flow after plan purchase)

 @Automattic/luna changed the flow recently (Thu 24 May) so that the flow doesn't land users to wp-admin, keeping them looking at "onboarding checklist" instead. Therefore Jetpack site doesn't yet know that it has a paid plan. Calypso knows about the plan so it doesn't show upsell banners and shows the module toggles.

When you now try to turn on paid settings, Calypso tries to change the setting at the live site but Jetpack site responds that it doesn't have a paid plan for the feature.

Solution is to ping Jetpack site to update right after plan purchase, these seem like good starting points:

`Jetpack_Plan::refresh_from_wpcom()`
`do_action( 'jetpack_heartbeat' );`

**Comment by ockham** [comment]
> `Jetpack_Plan::refresh_from_wpcom()`
> `do_action( 'jetpack_heartbeat' );`

There's only one instance of the [latter](https://github.com/Automattic/jetpack/blob/274c46db5e8f79cb0f3bb8bcfc8a23028cf310d2/class.jetpack.php#L687-L688) which in turn calls the former (defined [here](https://github.com/Automattic/jetpack/blob/96a9b033147b723eb1e6f5052151dc01c4f3b165/class.jetpack-plan.php#L71-L89)).

`refresh_from_wpcom()` in turn queries WP.com using `Jetpack_Client::wpcom_json_api_request_as_blog()` and syncs the response back to the JP site using `Jetpack_Plan::update_from_sites_response`.

Fortunately, there's an [endpoint](https://github.com/Automattic/jetpack/blob/180a46c9bc1e14f2d6ff280e24d4b5ffcb15f03a/_inc/lib/class.core-rest-api-endpoints.php#L180-L185) that [does](https://github.com/Automattic/jetpack/blob/180a46c9bc1e14f2d6ff280e24d4b5ffcb15f03a/_inc/lib/class.core-rest-api-endpoints.php#L1367-L1392) the [same](https://github.com/Automattic/jetpack/blob/180a46c9bc1e14f2d6ff280e24d4b5ffcb15f03a/_inc/lib/class.core-rest-api-endpoints.php#L1333-L1366). (Note that it's a `GET` endpoint -- it's meant to return some site data, but as a side effect, it syncs plan data and the like from WP.com to the Jetpack site.)

We should thus be able to fix the issue by making Calypso `GET jetpack/v4/site` for the Jetpack site in question -- ideally right after a plan is purchased.

**Comment by ockham** [comment]
D29305-code

**Comment by simison** [comment]
Fixed by r193040-trac
