### ISSUE TITLE
Previews for published posts with an autosave are blank and grayed out

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#33799]
Steps to reproduce: 

1. Open a post that has already been published using the block editor.
1. Make a change to the post but do not save.
1. Wait 60 seconds for an autosave.
1. Leave the post (accept unsaved changes if prompted).
1. Re-open the same post.
1. Click the "Preview" button.

Result: preview is gray and blank and the following error appears in the console. ([1m55s](https://cloudup.com/c1vK6ok4f_c))

> TypeError: Parameter 'url' must be a string, not object
> https://wordpress.com/calypso/evergreen/187.f2f1ef7a300315776f05.min.js:58

![preview-with-autosave-console-error-calypso-block-editor](https://user-images.githubusercontent.com/1119271/59234497-42a01780-8baa-11e9-93c6-fd5e2309d391.png)
<sup>Seen at https://wordpress.com/block-editor/post/made4testing0318.blog/146 logged in as `user0313` tested using Firefox 67.0 on macOS 10.14.5.</sup>

Note: I also tested with WordPress 5.2.1 wp-admin and did not see the same problem happen there. ([1m26s](https://cloudup.com/cWJD4TuXfd4))

**Comment by liviopv** [comment]
Similar behavior reported in #2277189-zen. 

I was not able to reproduce the error reliably by creating a new page, but I do see the same issue when I visit the user's page (https://housesevendesign.com/presets/).

Console when loading the preview on Firefox/Mojave:

![Screenshot](https://cld.wthms.co/M86UCo+)
Screenshot: https://cld.wthms.co/M86UCo

**Comment by designsimply** [comment]
> I was not able to reproduce the error reliably by creating a new page

Needs to be a previously published post or page.

**Comment by gwwar** [comment]
Going to keep tracking https://github.com/Automattic/wp-calypso/issues/30145 in favor of this issue. Will leave a note for repro hints. Thanks for the report!
