### ISSUE TITLE
MKTG: Update en.blog header featured image to center vertically.

### ISSUE THREAD

**Issue by ballio2000** [Automattic/wp-calypso#33816]
The header image is cropped by the top navigation bar on https://en.blog.wordpress.com/ and the respective content pages.

**Comment by ballio2000** [comment]
Add the below CSS code snippet to fix the theme:

```
body.wpcomblog #wrapper
{
    margin-top: 42px;
}
```

**Comment by scottsweb** [comment]
Pushed to .com via sandbox.
