### ISSUE TITLE
Feedback Area: Free Plan vs. Business Plan (Atomic) - different menu structure in WP-Admin [2]

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/wp-calypso#33829]
Users with a business plan and at least one plugin installed (atomic site) see after clicking "Feedback" in the main menu a different page than for example free plan users.

Screenshot Menu Business Plan User vs. Free Plan User:
https://cloudup.com/ceQ6kmQDPjM

Video:
https://cloudup.com/cSJnncZA-Vm

As a business plan user you get linked to the "PlugIns" area, and on the left side menu you have no menu item that refers to the active view ( like "Contact Form" for free plan users). 

Expected behaviour would be, as on the free plan, to be forwarded to a dedicated "feedback area", that also includes the "polls" and "ratings" area (currently only available via installing the Crowdsignal plugin).
If you would have used these polls/rating features before your upgrade, you would loose access to these features after the upgrade.

**Comment by mmtr** [comment]
Around 2 points spent for sprint 23-24. We'll likely need 2 more before closing this (updated the title to reflect this).

**Comment by glendaviesnz** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/12691 - Scheduled for next Jetpack release July 2, 2019.
