### ISSUE TITLE
MKTG: Make featured image on en.blog articles clickable

### ISSUE THREAD

**Issue by avonclausburg** [Automattic/wp-calypso#33823]
<img width="862" alt="Screen Shot 2019-06-11 at 6 22 36 PM" src="https://user-images.githubusercontent.com/51723737/59310983-0639ed80-8c76-11e9-817b-6700bfb0205f.png">

Featured images on en.blog should be clickable so that they open the article. Currently you cannot click on them. 

For example <div class="postthumbnail" style="background-image: url( 'https://en-blog.files.wordpress.com/2019/05/wp-simple-heart.png?w=720' );"></div> 

should be wrapped in the same link from the headline 

<a href="https://en.blog.wordpress.com/2019/05/13/publishing-to-wordpress-from-bear-just-got-better/">Publishing to WordPress from Bear Just Got&nbsp;Better</a>

**Comment by scottsweb** [comment]
This was deployed on .com by me.
