### ISSUE TITLE
Store: Hovering over "Write" button causes the page to jump, left-side (product) nav to become partially obscured, and margins to break in cards

### ISSUE THREAD

**Issue by wrightcj03** [Automattic/wp-calypso#33835]
#### Description
Hovering over "write" button causes the page to jump and left-side nav to become partially obscured, in addition to breaking the spacing on the additional details card. (Original issue https://github.com/Automattic/wp-calypso/issues/33265 )

#### Steps to reproduce
1.  Add a product
2. Expand "Add Additional Details" card
3. Hover cursor over "Write" button in navigation

#### What I expected
For the page to not react to the cursor hover; for the fold-able card bottom margin not to change.

Bonus: also breaks without expanding the additional details card, but the bottom margin doesn't change.

#### What happened instead
The screen jumps and the left-side nav is partially obscured.

#### Browser / OS version
OSX 10.14.4 / Google Chrome Version 73.0.3683.103
OSX 10.14.4 / Firefox 66.0.2 

#### Screenshot / Video
![storecategorybug](https://user-images.githubusercontent.com/23107581/59311352-029a6c80-8c5e-11e9-868e-3612a2ff8582.gif)

Somewhat related https://github.com/Automattic/wp-calypso/issues/33263

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
