### ISSUE TITLE
Pressable NUX styles are inconsistent with normal NUX styles (and kind of busted)

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#33841]
The pattern for NUX on WordPress.com has changed. The content is no longer in Card components and instead relies on white text on blue background. The buttons and progress are also in different spots.

Here is what the WordPress.com NUX looks like:
![image](https://user-images.githubusercontent.com/1123119/59313551-5c9f3000-8c66-11e9-95fd-baf7b5da921e.png)

And here is the Pressable NUX:
![image](https://user-images.githubusercontent.com/1123119/59313575-6cb70f80-8c66-11e9-9cf5-a044e86efe87.png)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/pressable-nux/

OR

1. Create a Pressable site
2. Set up Jetpack once logged in

#### Context / Source
#dogfooding

**Comment by jeffgolenski** [comment]
Dupe! Thanks though @MichaelArestad luv u bye. 

https://github.com/Automattic/wp-calypso/issues/33276
