### ISSUE TITLE
Gutenberg: File Block: Download Attribute Missing

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#33866]
#### Steps to reproduce
1. Open a test Simple site.
2. Create a new page. 
3. Add **File block** and select image from the Media Library.
4. Publish and open the page.
5. Click on the **Download** button.

#### What I expected

Browser will let you download the image file - dialog to choose download destination will open.

#### What happened instead

Image is opened in the browser.

It seems that the `download` attribute is filtered out. When testing on Atomic site, everything is working as expected.

#### Screenshot / Video

https://cld.wthms.co/jZM1eE

#### Context / Source

#2102365-zen #user-report

**Comment by gwwar** [comment]
See p5TWut-ft-p2 for more history, but this is expected behavior on Simple Sites.
