### ISSUE TITLE
Signup: when choosing a custom domain, the WP.com username step can autosuggest a taken username

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#3388]
#### What I expected

I expect the suggested username to be available.

#### What happened instead

The suggested username was not available (but already marked green).

#### Steps to reproduce
- Go to https://wordpress.com/start/
- Choose a custom domain on the `domains` step

#### Browser / OS version

OSX 10.11.13/Chrome (most recent)

## Screenshots / Video

![autosuggest](https://cloud.githubusercontent.com/assets/349751/13151282/5e06cca2-d61e-11e5-8e6c-92e6207e508c.gif)

**Comment by fabianapsimoes** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/760

**Comment by hoverduck** [comment]
#bug-scrub

Closing, this is fixed:

![wp-calypso-3388](https://cloud.githubusercontent.com/assets/7233112/17112954/47352ed6-5276-11e6-9eb3-1a9595b1f7ae.gif)

**Comment by SiobhyB** [comment]
Reopening as I'm still able to replicate the issue by following the steps set out in the original post.

Screencast:

![username](https://cloud.githubusercontent.com/assets/2998162/19013645/ef90df16-87ce-11e6-8c7c-18020c002648.gif)

There is some delay between arriving at the *Create your account* form and the *Sorry, that username already exists!* error popping up. I had time to enter an email address before it appeared.

**Comment by kwight** [comment]
Closing as fixed, at some point – I can no longer reproduce.
