### ISSUE TITLE
Error when adding extra G Suite licenses

### ISSUE THREAD

**Issue by cbauerman** [Automattic/wp-calypso#33888]
#### Steps to reproduce
1. checkout and boot calypso master brnach locally
2. Starting at URL: `/email/:domain/gsuite/add-users/:siteSlug`
3. Add a new G Suite user to the cart
4. return `/email/:domain/gsuite/add-users/:siteSlug`
5. open browser console
6. add additional user for same domain
7. observe error
<img width="1187" alt="Screen Shot 2019-06-12 at 2 34 46 PM" src="https://user-images.githubusercontent.com/2810519/59387918-41442b80-8d1f-11e9-90cc-70fe48c40a4a.png">

**Comment by stephanethomas** [comment]
Looks good, and works fine.
