### ISSUE TITLE
Table block: Cannot center text in a table.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#33882]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/
2. Add a Table Block
3. Add text/sentences to the block cells.
4. Click the "Center align" item on the block.

#### What I expected
The text to be centered.

#### What happened instead
The "Center align" setting is for aligning the block itself. To the left, right, or center of the content area.

Centering text in a table is a common expectation, so this is a bit confusing. 

Adding an option to align the text itself as you would in a spreadsheet would be helpful (perhaps where the tools to bold/underline text are located).

#### Browser / OS version
Chrome Version 75.0.3770.80 (Official Build) (64-bit)

Pop!_OS 18.04

#### Screenshot / Video

![Screen Shot on 2019-06-12 at 14_13_24](https://user-images.githubusercontent.com/10121835/59379459-45227e80-8d1c-11e9-9c24-be3832e1ff0b.png)

#### Context / Source

13386610-hc

**Comment by pablohoneyhoney** [comment]
Just to clarify: Would the center alignment be applied to all cells in the table?

**Comment by cecoates** [comment]
I think that'd be a good compromise, personally. Cell-by-cell does seem a bit over the top.

**Comment by selectedselections** [comment]
Reported here hc-14940542
