### ISSUE TITLE
Remove "Add" links from Store on WP menu

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#33894]
#### Steps to reproduce
1. Navigate to a site with Store on WP.com and enter store management
2. Notice the legacy "Add" buttons next to the "Products" and "Promotions" menu items

#### What I expected
No add buttons - these are a legacy design pattern

#### What happened instead
I saw add buttons

#### Screenshot / Video
![add](https://cldup.com/yYV1VfwIa9-3000x3000.png)

**Comment by jeffgolenski** [comment]
@jameskoster Tested and works as expected!

<img width="508" alt="Screen Shot 2019-06-12 at 4 06 19 PM" src="https://user-images.githubusercontent.com/214813/59392319-11e7eb80-8d2c-11e9-9a59-f0d7a3d82222.png">
