### ISSUE TITLE
Signup: Domain already taken has blue callout left border that no longer works with same-color background

### ISSUE THREAD

**Issue by andyaffleck** [Automattic/wp-calypso#33898]
#### Steps to reproduce
1. Walk through the signup process and enter a domain that you know is already taken
2. The box telling you that the domain is already taken has a 3px wide blue left border to call the user's attention to the issue. (See images, below)

#### What I expected

A clear alert that the domain is already taken.

#### What happened instead

An unclear situation that looks more like a visual goof than a callout.

#### Browser / OS version

Any/All

#### Screenshot / Video
This is the way it USED to look (you will notice that the blue bar stands out and is quite visible):

![The way it used to look](https://user-images.githubusercontent.com/128826/43436830-81182152-94c9-11e8-8f16-31c44322845e.png)

This is the way it looks today (note that the callout is the same color as the background and it looks not like a callout but a visual goof): 

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/7773109/59389639-a39f2b00-8d23-11e9-872b-a82eef8b1f20.png">

**Comment by andyaffleck** [comment]
One possible solution (unless red is a "bad color")

**Comment by andyaffleck** [comment]
One possible solution (unless red is a "bad color")

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/7773109/59390861-5b820780-8d27-11e9-98d2-bba7ccac11a8.png">

**Comment by michiecat** [comment]
Another possible solution is to replicate the grey background and red border used for regular error messages, and to use white text (with the link underlined to indicate that it's a link).

<img width="1244" alt="Screen Shot 2019-06-12 at 3 37 14 PM" src="https://user-images.githubusercontent.com/1385492/59391103-26c28000-8d28-11e9-8ac2-e36728cd25a1.png">

Here's another version using yellow (if we want to show that it's a warning and less of an error):
 
<img width="1241" alt="Screen Shot 2019-06-12 at 3 46 47 PM" src="https://user-images.githubusercontent.com/1385492/59391541-6b9ae680-8d29-11e9-9f7e-c3a8ad49b12a.png">

**Comment by andyaffleck** [comment]
@drw158 Can we get your thoughts on the above ideas? (Also, we are sitting right behind you :)

**Comment by andyaffleck** [comment]
@zeldman What do you think?

**Comment by zeldman** [comment]
Yellow stripe, black background is much better. Focuses my attention. Works as an alert (the traditional purpose of yellow) instead of as an error like red. Well done. This seems to be the best choice. Onward!

**Comment by drw158** [comment]
Which component is being used? This seems like a good fit for the Notice component, which has a warning variant I believe. You'll also get the dark background for free.

**Comment by klimeryk** [comment]
This was introduced in https://github.com/Automattic/wp-calypso/pull/19183

And the idea was that a Notice is not a good fit for it - it makes it seems like an error occurred, like this is an unexpected state. Whereas I'd say this is a flow that users are supposed to land on when they are trying to transfer in or map a domain they already own. I'd prefer to preserve that - Notice seems like a poor fit here, at least the warning variation. It's also much smaller than the current implementation.

**Comment by klimeryk** [comment]
I've re-checked and looks like the border is a different shade now and does not seem like a "visual goof" anymore:

<img width="1001" alt="Screenshot 2019-12-19 at 18 37 51" src="https://user-images.githubusercontent.com/3392497/71200015-1bc84980-228f-11ea-963e-ab3013837547.png">

Closing the issue.
