### ISSUE TITLE
Editor: Media: add a "Reverse order" button to the edit gallery screen

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#339]
Can we add back the "Reverse order" button for images in the create a gallery flow?

![screen shot 2015-09-29 at tue sep 29 6 39 53 pm](https://cloud.githubusercontent.com/assets/1119271/10180337/36eee392-66da-11e5-9234-bd9d2dfb3a27.png)<sup>Seen at https://design5279.wordpress.com/wp-admin/post-new.php using Chrome 45.0.2454.101 on Mac OS X 10.10.5 logged in as designsimply (superadmin) proxied.</sup>

Here's a screencast explaining more about it: [5m3s](https://cloudup.com/cMTEDaxWpaL)
# calypso-gaps

**Comment by KokkieH** [comment]
Had a request for this in 678123-f.

**Comment by rachelmcr** [comment]
Another request for this in 69963-helpshift.

**Comment by alisterscott** [comment]
I've started work on a PR for this: #8959

**Comment by ryanboren** [comment]
> If I didn’t have wp-admin as fallback, I’d work around this by changing the sort order in my source app (Pixave) and reuploading the gallery. Reuploading is my go to workaround for media bugs and awkward flow, impacting quota.

https://test.wordpress.com/2016/09/13/session-notes-reader-editor-free-domain-claim-gallery-ordering-editing-links/

**Comment by lancewillett** [comment]
+1 for this, ran into reordering a gallery last night in a dogfooding session and found it hard to do (ended up doing it in wp-admin instead).

**Comment by folletto** [comment]
> +1 for this, ran into reordering a gallery last night in a dogfooding session and found it hard to do (ended up doing it in wp-admin instead).

Can you help me with some background?

1. What was hard to do from the "Edit" gallery tab? Or are you referring exclusively about a "reverse order" as a quick way to reverse instead of manually reordering?
2. How did you end up there, given the media library order is determined by the click order? How comes you clicked an order and then you had to revert? Can you describe the steps?

**Comment by folletto** [comment]
The discussion expanded a bit in #8967 so we probably want to just keep discussing there instead of splitting par of it here.

**Comment by lancewillett** [comment]
This is implemented now with https://github.com/Automattic/wp-calypso/pull/14904
