### ISSUE TITLE
Action Bar: Follow/Following label is vertically misaslinged after hiding/showing on scroll

### ISSUE THREAD

**Issue by enriquesanchez** [Automattic/wp-calypso#33914]
#### Steps to reproduce
1. Go to a wordpress.com site front end
2.  Scroll down, and then up to hide and show the Action Bar. Then open the Action Bar menu (...)
3. The "Follow/Following" label icon is not positioned correctly:
<img width="277" alt="Screen Shot 2019-06-12 at 4 07 41 PM" src="https://user-images.githubusercontent.com/3276087/59392535-d4d02900-8d2c-11e9-986c-5ee783ace413.png">

#### What I expected
No misalignment of the Follow icon

#### What happened instead
Saw misalignment after hiding/showing the Action Bar.

#### Browser / OS version
Safari and Firefox, Mac

**Comment by enriquesanchez** [comment]
There seems to be different CSS rules affecting the icon on some themes:

```
div#actionbar li.actnbr-hidden > a .gridicon {
    position: absolute;
    top: 6px;
    left: 5px;
```

**Comment by enriquesanchez** [comment]
Also, this code lives in the older PHP codebase. You’d need a sandbox to fix it.

**Comment by sixhours** [comment]
This only appears to happen when you're a user of the site you're viewing.

**Comment by sixhours** [comment]
Patch up for review in D29438-code

**Comment by enriquesanchez** [comment]
@sixhours and I spent some time troubleshooting this. It turns out the icon gets an offset after the action bar is hidden and then reappears after you scroll down and back up.

**Comment by crunnells** [comment]
Works for me!

**Comment by sixhours** [comment]
Deployed in r193148-wpcom
