### ISSUE TITLE
Outdated WP core Lost Password action screens

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/wp-calypso#33924]
Log in (correct styling): https://wordpress.com/log-in
![Log_in_to_your_account_-_big_screenshot](https://user-images.githubusercontent.com/905781/59393181-5f198c80-8d2f-11e9-81bd-084762b9b0d3.jpg)

Lost Password: https://wordpress.com/wp-login.php?action=lostpassword
![Lost_Password_Big_Screenshot](https://user-images.githubusercontent.com/905781/59393184-6345aa00-8d2f-11e9-8bab-5c920c12a1ea.jpg)

Reset Password: https://wordpress.com/wp-login.php?action=rp
![Reset_Password_Big_Screenshot](https://user-images.githubusercontent.com/905781/59393187-650f6d80-8d2f-11e9-8f4a-8d9f47e9936e.jpg)

The Reset Password actions should be handled by Calypso and not WP core, otherwise the styling will keep getting outdated.

_Related issue: https://github.com/Automattic/wp-calypso/issues/33523_

**Comment by sixhours** [comment]
Likely what would happen here, rather than moving the whole system into Calypso, is we'd want to re-style these screens to use the newer Calypso styles.
