### ISSUE TITLE
Issue Template: Possible improvements

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#3392]
The new Issue template is fantastic; lots of information, links, and prompts for desired data. I also find it... discouraging, and I'm wondering if there's a middle ground. Some notes from creating [this issue](https://github.com/Automattic/wp-calypso/issues/3388):

* In general, once I read through everything, I didn't feel like submitting the issue any more, it feels like a lot of work. (Of course, I'm lazy, so that doesn't help).
* Having docs and troubleshooting as the first thing I read came across as rather RTFM. I wonder if a lower placement would help.
* Bringing up the title prefixing gave me more confusing things I had to think about. I'm used to it myself, but I could see it creating confusion for others.
* The bug template sections come across as all required; I felt the _need_ to do a video or a series of screenshots, which are time-consuming and again, discouraging. Can we mark some sections as optional, if we're happy to receive a more basic issue report?
* Producing screenshots or a GIF is surprisingly complicated (to me and others, I imagine); maybe a link to a tutorial?

All the info is appropriate, I just wonder if there's better sequencing, wording, and/or concision that can keep a reporter keen to complete the issue once they've clicked "New Issue".

> Thank you for contributing to Calypso!
> 
> Docs & troubleshooting:
> =======================
> https://github.com/Automattic/wp-calypso/blob/master/CONTRIBUTING.md
> https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md
> 
> Think you found a bug?
> ======================
> Use the template below to log a new bug. If you want to prefix the title with a “Question:”, “Bug:”, or the general area of the application, that would be helpful, but by no means mandatory. If you have write access, add the appropriate labels.
> 
> Have a feature request?
> =======================
> If you want to prefix the title with “Question:”, “Feature Request:”, or the general area of the application, that would be helpful. For example, "Editor: add ability to choose from most popular tags" would make a great title.
> 
> 
> ## URL:
> 
> ## What I expected
> 
> ## What happened instead
> 
> ## Steps to reproduce
> 
> ## Browser / OS version
> 
> ## Screenshots / Video

**Comment by lancewillett** [comment]
Thanks for your feedback!

**Comment by lancewillett** [comment]
I'd like to let this sit for a few days or a week — the audience is new contributors, so keeping that in mind.

Also, it's fine for "veterans" to just delete it — if you are good at making top-notch bug reports.

**Comment by hoverduck** [comment]
I agree with @kwight on the ordering.  I think it will work better with the actionable fields at the top, and the comments/documentation at the bottom.  Then people at least know right away when they load the page that it's a template with fields to fill out and not just a bunch of documentation to read.

Once the template is at the top, I'd make the first line of the comment block something like this:

> Thank you for contributing to Calypso!  All text below this point will not appear in your issue once submitted.  It is for informational purposes only, and can be deleted if you wish.

On the note of sounding too RTFM, I think moving the Docs & Troubleshooting section to the bottom is a good idea, but I don't have a strong opinion about it.  But with that context in mind, I'd rename the "Think you found a bug?" header to just be "Found a bug?" so it doesn't come across as questioning whether their bug is real.

And if we add text like this to the details of that section it will help people realize that fields like screenshots/video aren't mandatory.

> Use the template _above_ to log a new bug, **filling out as many of the fields as you can, along with any other information you think might be useful**. If you want to prefix the title with a “Question:”, “Bug:”, or the general area of the application, that would be helpful, but by no means mandatory. If you have write access, add the appropriate labels.

**Comment by lancewillett** [comment]
Great feedback and changes, @hoverduck .

**Comment by lancewillett** [comment]
#3426 has many improvements.

**Comment by folletto** [comment]
I'd like to suggest a more concise structure:

```
<!-- Thanks for contributing! Pick a clear title above, like "Editor: add spell check" and proceed -->

#### Steps to reproduce
1. Starting at URL: 
2. 
3. 
4. 

#### What is the expected behaviour?


#### What happened instead?


#### Browser / operating system version


#### Screenshot / Video


<!-- 
PLEASE NOTE
— This comment won't show up when you submit the issue
— Everything is optional, but try to give us as many details as possible.
— If possible prefix the title with the area of the application ("Editor: ...", "Reader: ...", "People: ...", etc)
— If you're writing a feature request, try explaining WHY and not just the feature you want.
— For more details: https://github.com/Automattic/wp-calypso/blob/master/docs/new-issue.md
-->
```

Notes:

1. The first comment should fit on a single line in most desktop browsers
2. The first comment explicitly says "clear" title and shows an example that primes the right format.
3. Steps to reproduce come first, making the sequence chronological: steps → expected / unexpected (google code does the same).
4. The URL is embedded as the first step
5. It also requires a new single page with more details, instead of suggesting multiple links that have to be copy-pasted.
6. Double space below the titles so people won't have to add manually extra spacing.
7. Titles two sizes smaller to not break the post too much visually.
8. The notes lines shouldn't go on multiple lines either.

I hope it helps. :)

**Comment by lancewillett** [comment]
Thank you, Davide. I've incorporated many of your changes.
