### ISSUE TITLE
Not able to switch to classic editor on simple site

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#33958]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/DOMAIN/PAGE-ID
2. Click on "Show more tools and options" on the top bar (three dots icon)
3. Look through options to find option for "Switch to classic editor", immediately below "Options"

#### What I expected
To find the option there.

#### What happened instead
Option is not there: 
![](https://cld.wthms.co/RrRjld+)

#### Browser / OS version
Google Chrome
Version 75.0.3770.80 (Official Build) (64-bit)

#### Context / Source
#manual-testing

**Comment by KokkieH** [comment]
We also have a user report in https://en.forums.wordpress.com/topic/my-patience-is-out/

It looks like this might be happening for new sites set to the block editor by default - I still see the option on my old sites, but on creating a new account and site the option is not there, nor is it if I create a new site in my personal account.

**Comment by KokkieH** [comment]
cross linking to p58i-7uc-p2

**Comment by gwwar** [comment]
If users are using the new business themes from /start/onboarding they won't be able to switch to classic. Please have them switch themes first.

See https://github.com/Automattic/wp-calypso/issues/32439

Closing this unless y'all have different steps.
