### ISSUE TITLE
Signup: Business name not updating in contact details area of preview

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#33969]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/site-type create a business site
2. Name business "Cat Corp"
3. Scroll down, contact details still call your site "Your New Website"
4. Refresh and rename your business "Dog Corp"
5. Scroll down, contact details still call your site "Cat Corp"

#### What I expected

The business name in the contact area to update like it does at the top of the page.

#### What happened instead

Looks like the contact details aren't reacting to changes to the store.

#### Screenshot / Video

https://cld.wthms.co/C5Pino

#manual-testing

**Comment by ramonjd** [comment]
Thanks @p-jackson 

I haven't had a chance to look at this, but maybe it can be wrangled in https://github.com/Automattic/wp-calypso/pull/33944 ???
