### ISSUE TITLE
Update logo on 331 vertical landing pages 

### ISSUE THREAD

**Issue by avonclausburg** [Automattic/wp-calypso#33972]
<img width="1895" alt="Screen Shot 2019-06-13 at 6 20 39 PM" src="https://user-images.githubusercontent.com/51723737/59471099-11bd1e00-8e08-11e9-92cb-0feb3cff1169.png">

All our vertical landing pages currently use the badge-less version of the logo.

**Comment by jaswrks** [comment]
Closing. Logo updated successfully across 300+ LPs. 
https://wordpress.com/websites/transportation/gas-station/
