### ISSUE TITLE
(3P) Track "blank" the same as all other templates

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#33987]
Add event for when a Page was published when the user _selected_ a blank template.

**Comment by getdave** [comment]
This is as per @apeatling 's comment. He mentioned he would be exploring the funnels to determine whether this was absolutely necessary.

**Comment by marekhrabe** [comment]
For reference this is how the post is tagged with template name https://github.com/Automattic/wp-calypso/blob/cc99f3a52ce9ff673fa239e79b1f1d6d71b4118f/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js#L123

and the call would need to happen before this `return` which handles the blank template https://github.com/Automattic/wp-calypso/blob/cc99f3a52ce9ff673fa239e79b1f1d6d71b4118f/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js#L43
