### ISSUE TITLE
Posts: My VideoPress video doesn't show in the posts listing

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#34]
No preview at all of the video, or a video player. There is supposed to be a VideoPress loaded video here:

![image](https://cloud.githubusercontent.com/assets/7233112/11221415/fd977d28-8d32-11e5-804b-25f6a55d2a2b.png)

The same is true for YouTube videos.

**Comment by alisterscott** [comment]
The posts list is now condensed so no longer shows videos at all:

<img width="786" alt="screen shot 2017-12-21 at 8 45 11 am" src="https://user-images.githubusercontent.com/128826/34232286-532dedd2-e62b-11e7-9edf-9cdc7d176249.png">
