### ISSUE TITLE
Editor: Open media dialog when clicking featured image

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#340]
In Calypso, clicking on the Featured Image should open the media dialog for that particular image. That way users can easily add the caption and other metadata. This would match WP Admin behavior.

**Comment by aduth** [comment]
We should decide whether we want to direct the user to the image details (for editing) or to the default list view (for choosing a different featured image). It's not obvious that there's a choice here since the detail fields are shown on the list view in wp-admin.

**Comment by alisterscott** [comment]
The default list view is now displayed and the selected image is shown with a tick. There's also an EDIT button on this dialog.

I think this is close enough as described in this issue - closing and we can add a more specific enhancement item if necessary.
