### ISSUE TITLE
Search bar block: Missing space between search bar and search button in themes where the search button is below the search bar

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#34008]
#### Steps to reproduce
1. Activate a theme like [Sequential](https://wordpress.com/theme/sequential) or [Publication](https://wordpress.com/theme/publication)
2. Go to a page or post and insert the Search block
3. Click Publish
4. Check your page or post

How it looks:

![searchexample](https://user-images.githubusercontent.com/23703267/59541386-fa953380-8ece-11e9-9de3-de122f8dd3e2.jpeg)
![searchexample2](https://user-images.githubusercontent.com/23703267/59541390-fd902400-8ece-11e9-8fd2-8d13348726b4.jpeg)

How it should look

There should be a space between the search bar and search button 
#### Context / Source
This only happens with themes where the search button is placed under the search bar. Those themes where the search button is next to the search bar look okay.

**Comment by tsetend** [comment]
Hey @carladoria,

The ticket for the search block popped up to me. Is there any update on this issue?

Thank you. :)

**Comment by carladoria** [comment]
It seems the issue hasn't been looked at yet. I'm asking in Slack to see if the report is missing something

**Comment by gwwar** [comment]
cc @laurelfulford does this look like a theme specific bug here?
