### ISSUE TITLE
Full Site Editor: Pick Site Logo Implementation [2]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34006]
Let's answer if we should use this dynamic block or simply use a media and text block directly in the "header" template (and perhaps drop that custom_logo theme integration).

As a follow up to https://github.com/Automattic/wp-calypso/issues/33108, the Site Logo block was originally implemented as a dynamic block that links to the customizer.

However:
- Site Logos are stored per theme. (Not per site) As a concept this makes it less important to retain this, since changing themes already causes users to loose their site logo.
- Linking to the customizer is an awkward flow

![editing](https://user-images.githubusercontent.com/1270189/59454721-90de3200-8dc7-11e9-8cd1-0a176550618c.gif)

How well does using a Media and Text block work? What follow up tasks do we need to create? One key thing that @apeatling notes is that folks are explicitly searching for "Logo" So at a minimum we'd need to alias search terms to existing blocks.

Timebox this to two days and make a recommendation for either using the media and text block approach, or the current dynamic block.

#### related mocks

<img width="776" alt="57947860-eab90e00-7894-11e9-8ae5-1132b3a48c98" src="https://user-images.githubusercontent.com/1270189/59542246-b21f4b00-8eb9-11e9-943e-f1504fbf58bb.png">

<img width="796" alt="59316331-c6253b80-8c72-11e9-9e58-5e63afaa7407" src="https://user-images.githubusercontent.com/1270189/59542272-d844eb00-8eb9-11e9-8009-913473b4753c.png">

**Comment by kwight** [comment]
On first investigation, I'm having a hard time justifying anything beyond a stripped-down Image block.

I think most people already have any desired text within their logo image (to guarantee the font), and if they really want to add the title beside the logo, they can use a Media+Text block.

The differences I'd consider for a Logo block vs. a normal Image block would be stripping out the caption, and removing the Wide options (leaving us with the three basic alignment buttons and the special icon shown in the "simple version" mockup above).

**Comment by apeatling** [comment]
I agree with Kirk on this one, and then we can gather feedback. I do think expecting users to go from the logo block, to knowing that they need a media+text block is a stretch, so I suspect we'll find that option would need to be integrated.

**Comment by gwwar** [comment]
@apeatling If we pick a standard core block, we can easily use a placeholder (block template) for it in the "header" `template_part`

**Comment by apeatling** [comment]
Having now tested the block on a local install I agree the customizer is an awkward flow, I think that is a non starter. A simple image block makes more sense here as long as we can alias to a "logo" search.

> @apeatling If we pick a standard core block, we can easily use a placeholder (block template) for it in the "header" template_part

That makes sense. Ready to try that when you have something.

**Comment by gwwar** [comment]
We've decided to go forward with a simple image or media_text block.
