### ISSUE TITLE
Full Site Editor: Dynamic Block Site Logo Improvements [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34007]
Please work on https://github.com/Automattic/wp-calypso/issues/34006 first. **ONLY** take this if we move forward with the dynamic block approach.

1. As a follow up to https://github.com/Automattic/wp-calypso/pull/33714:

Update the placeholder markup to include a picture of the <img width="32" alt="Screen Shot 2019-06-14 at 3 03 00 PM" src="https://user-images.githubusercontent.com/1270189/59541309-87cb8e80-8eb5-11e9-9bfb-72555d1ed3e5.png"> edit button in the prompt

![](https://user-images.githubusercontent.com/1270189/59454866-e0246280-8dc7-11e9-83f6-f71ade617cb4.png)

2. Update the site logo block icon to match mocks, can ping @jasmussen for related SVG

**Comment by jasmussen** [comment]
> Update the site logo block icon to match mocks, can ping @jasmussen for related SVG

Yep! I'm always here, easy to find. In this case I believe the mockup uses this design:

<img width="295" alt="Screenshot 2019-06-17 at 09 23 40" src="https://user-images.githubusercontent.com/1204802/59585843-b2019400-90e1-11e9-8b9f-d4935fd5ded7.png">

But let's use the outline version, which is here:

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zm7.48 7.16l-5.01-.43-2-4.71c3.21.19 5.91 2.27 7.01 5.14zm-5.07 6.26L12 13.98l-2.39 1.44.63-2.72-2.11-1.83 2.78-.24L12 8.06l1.09 2.56 2.78.24-2.11 1.83.64 2.73zm-2.86-11.4l-2 4.72-5.02.43c1.1-2.88 3.8-4.97 7.02-5.15zM4 12c0-.64.08-1.26.23-1.86l3.79 3.28-1.11 4.75A7.982 7.982 0 0 1 4 12zm3.84 6.82L12 16.31l4.16 2.5A7.924 7.924 0 0 1 11.99 20c-1.52 0-2.94-.44-4.15-1.18zm9.25-.65l-1.11-4.75 3.79-3.28c.14.59.23 1.22.23 1.86 0 2.48-1.14 4.7-2.91 6.17z"/></svg>
```

**Comment by gwwar** [comment]
We've decided to use core blocks instead, closing these related tasks.
