### ISSUE TITLE
Full Site Editor: Add Site Logo block to Header Template [2]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34015]
Please work on #34006 _first_. 

Following up with work in https://github.com/Automattic/wp-calypso/issues/33636, add the Site Logo block in context with the "header" template and get feedback from @apeatling and @alexislloyd 

If we have follow up work that is more than styling updates, please file new issues to track and estimate this work.

See related tasks for population on:
WPCOM Side: https://github.com/Automattic/wp-calypso/issues/33515
Standalone: https://github.com/Automattic/wp-calypso/issues/33636 (https://github.com/Automattic/wp-calypso/pull/33878)

**Comment by kwight** [comment]
A PR for this will not work until https://github.com/Automattic/wp-calypso/issues/34166 has a solution.

**Comment by apeatling** [comment]
I think we can close this as we're going with an image for now. I'll open a new issue for looking more deeply at a logo block for post launch.
