### ISSUE TITLE
Mailchimp Block: Configuration settings missing when Publicize is disabled

### ISSUE THREAD

**Issue by csonnek** [Automattic/wp-calypso#34018]
#### Steps to reproduce the issue

1. Disable Publicize
2. Add Mailchimp block to a new post or page
3. Click the "Set up Mailchimp form" button which should go to https://wordpress.com/marketing/connections/SITEADDRESS - which is fine. 
4. However, to manage or set up that connection outside that block, we should be able to access those settings in the WordPress.com dashboard by going to Tools -> Marketing -> Connections tab, but when Publicize is disabled, the Connections tab does not show in the available options.   

Would affect any site that has Publicize disabled and using the Mailchimp block.

**Comment by brbrr** [comment]
It seems that connections page is accessible via direct link now. Although the tabs do include "Connections" tab, sine publicize is disabled

<img width="836" alt="Sharing ‹ HelloWord — WordPress com 2019-09-25 10-18-28" src="https://user-images.githubusercontent.com/5654161/65578201-012b5080-df7e-11e9-881c-5150548756f8.png">

@csonnek can you double-check this issue, please?

**Comment by csonnek** [comment]
@brbrr re "It seems that connections page is accessible via direct link now." - it's always been available there. 

The problem is that we direct people to go to Tools > Marketing > Connections to configure these settings. If the Connections tab is hidden due to Publicize being disabled, they can't configure the other connections like MailChimp or Google Photos.

**Comment by pauljacobson** [comment]
There seems to be a variation of this issue. In 2541395-zen, the user doesn't have Publicize enabled, but there is a _Connections_ tab, [here](https://d.pr/i/ywkk7q/2xUGDBm45y):

![](https://d.pr/i/ywkk7q/2xUGDBm45y+)

_Screenshot direct link:_ https://d.pr/i/ywkk7q/2xUGDBm45y

At the same time, the user sees this error message when they add a Mailchimp block to a page:

>Your site doesn't include support for the jetpack/mailchimp block

I've asked the user to enable Publicize to see if this resolves the issue with the block.

The site is a Jetpack-powered, self-hosted WordPress.org site.

**Comment by jordesign** [comment]
I'm able to see the 'connections' and also add a Mailchimp block while the Publicize module is deactivated. Marking this is 'Can't Reproduce' as it is also over 12 months old.
