### ISSUE TITLE
Full Site Editing: Add Navigation block to Header Template [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34014]
Following up with work in https://github.com/Automattic/wp-calypso/issues/33636, add the Navigation blocks in context with the "header" template and get feedback from @apeatling and @alexislloyd 

If we have follow up work that is more than styling updates, please file new issues to track and estimate this work.

See related tasks for population on:
WPCOM Side: https://github.com/Automattic/wp-calypso/issues/33515
Standalone: https://github.com/Automattic/wp-calypso/issues/33636 (https://github.com/Automattic/wp-calypso/pull/33878)

**Comment by apeatling** [comment]
I've tried the block locally and see no styling, so looking forward to seeing that in place and testing. Also, on my local install the block showed:

<img width="315" alt="Screen Shot 2019-06-18 at 12 46 07 PM" src="https://user-images.githubusercontent.com/1464705/59714680-10547280-91c7-11e9-8853-4ed755beda47.png">

If a page has no title set, it should be hidden from the navigation here.

**Comment by gwwar** [comment]
> If a page has no title set, it should be hidden from the navigation here.

Does that differ from what the Customizer menu generates? This block is simply a placeholder.

**Comment by apeatling** [comment]
Looks the same. Since we're using menus created by the theme, how will we be automatically adding new pages created so they show up here without any user interaction?

**Comment by apeatling** [comment]
Tried this again locally, and the pages seem to be added automatically to the menu, so I think we're good. 👍

**Comment by kwight** [comment]
> how will we be automatically adding new pages created so they show up here without any user interaction?

This block is server-side rendered, so it's just [displaying the output](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.php#L90) of `wp_nav_menu()` – everything WordPress does in the background with menus (like autopopulating new pages in some cases) we get for free 🎉

**Comment by kwight** [comment]
A PR for this will not work until https://github.com/Automattic/wp-calypso/issues/34166 has a solution.
