### ISSUE TITLE
Gutenberg: Update plugin to 6.0 [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34016]
Let's update the Gutenberg Plugin for Simple and Atomic sites to v6.0

- [ ] Test the 6.0 Gutenberg RC for both Simple and Jetpack Sites (6/24) https://github.com/WordPress/gutenberg/releases/tag/v6.0.0-rc.1
- [ ] Test the 6.0 Gutenberg plugin for both Simple and Jetpack Sites (6/26)
- [ ] Report and help fix related issues in the core project / Jetpack / wpcom
- [ ] If no issues are found attempt to deploy the wpcom diff for Simple Sites
- [ ] If simple sites are stable, file a related request to update the atomic Gutenberg plugin version.

See also steps in PCYsg-m14-p2

**Comment by mmtr** [comment]
We are finally skipping this version due to a bug when resizing images within blocks (https://github.com/WordPress/gutenberg/issues/14652). 

Will try again with the new release on July 10th. See paAmJe-vD-p2 for more context.
