### ISSUE TITLE
Full Site Editor: Add Site Title and Description block to Header template [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34013]
Following up with work in https://github.com/Automattic/wp-calypso/issues/33636, add the Site Title and Description blocks in context with the "header" template and get feedback from @apeatling and @alexislloyd 

If we have follow up work that is more than styling updates, please file new issues to track and estimate this work.

See related tasks for population on:
WPCOM Side: https://github.com/Automattic/wp-calypso/issues/33515
Standalone: https://github.com/Automattic/wp-calypso/issues/33636 (https://github.com/Automattic/wp-calypso/pull/33878)

**Comment by kwight** [comment]
This will present an interesting challenge: we have two separate blocks title and description blocks (which makes sense), but in our Twenty Nineteen base theme, they're visually presented side-by-side, with an em-dash between them:

<img width="749" alt="Screen Shot 2019-06-18 at 8 47 39 AM" src="https://user-images.githubusercontent.com/349751/59699194-03735700-91a6-11e9-8ebb-aa0663a666f9.png">

**Comment by apeatling** [comment]
Can we wrap them in a columns block to achieve this?

**Comment by apeatling** [comment]
The same is true of the Friendly, Sophisticated, and Professional business themes.

**Comment by gwwar** [comment]
Does the ordering need to change for RTL languages?
