### ISSUE TITLE
.com checklist: switching the site hides the checklist

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#34028]
When switching sites from the sidebar's site switcher while at the checklist, I get an empty checklist.

#### Steps to reproduce
1. I'm looking at my Atomic site's completed checklist as expected:

    ![image](https://user-images.githubusercontent.com/87168/59591719-2bf04800-90f7-11e9-961a-7197ae6ffc8e.png)

2. I switch to free simple site (`simisontestingfree.`) and see:

    <img width="1259" alt="Screenshot 2019-06-17 at 11 48 36" src="https://user-images.githubusercontent.com/87168/59591332-83da7f00-90f6-11e9-8bcc-8dadd32db846.png">

3. I switch to another free simple site and see uncompleted checklist (as expected):

    <img width="1257" alt="Screenshot 2019-06-17 at 11 48 49" src="https://user-images.githubusercontent.com/87168/59591427-a66c9800-90f6-11e9-99f3-ca8537636397.png">

4. Now when I switch back to the previous free site, I see:

    <img width="1256" alt="Screenshot 2019-06-17 at 11 49 10" src="https://user-images.githubusercontent.com/87168/59591452-b08e9680-90f6-11e9-8e30-5e4349a6a580.png">

... so as if the header state just remains what was used for the previous site and the new checklist doesn't load.

No errors in the console. 

I do see API request to `https://public-api.wordpress.com/rest/v1.1/sites/140695178/checklist?_envelope=1&http_envelope=1&_locale=en-gb` with a response:
```json
{
  "code": 200,
  "headers": [
    {
      "name": "Content-Type",
      "value": "application/json"
    }
  ],
  "body": {
    "designType": "blog",
    "phase2": false,
    "segment": false,
    "verticals": [],
    "tasks": {
      "about_page_updated": {
        "completed": false
      },
      "blogname_set": {
        "completed": true
      },
      "blogdescription_set": {
        "completed": true
      },
      "custom_domain_registered": {
        "completed": false
      },
      "contact_page_updated": {
        "completed": false
      },
      "post_published": {
        "completed": true
      },
      "site_icon_set": {
        "completed": false
      },
      "site_logo_set": {
        "completed": false
      },
      "social_links_set": {
        "completed": true
      },
      "site_launched": {
        "completed": true
      },
      "about_text_updated": {
        "completed": false
      },
      "homepage_photo_updated": {
        "completed": false
      },
      "business_hours_added": {
        "completed": false
      },
      "service_list_added": {
        "completed": false
      },
      "staff_info_added": {
        "completed": false
      },
      "product_list_added": {
        "completed": false
      },
      "avatar_uploaded": {
        "completed": true
      },
      "email_verified": {
        "completed": true
      },
      "mobile_app_installed": {
        "completed": true
      }
    }
  }
}
```

cc @Automattic/zelda 

Note that screenshots are with toggles because I was testing https://github.com/Automattic/wp-calypso/pull/33666, but I can replicate also in production.

**Comment by ramonjd** [comment]
It's failing [this check](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checklist/wpcom-checklist/index.jsx#L74) because `viewMode` is empty and in `isEligibleForDotcomChecklist()`, I'm half-certain, the site has a creation date that is earlier than the one in [this check](https://github.com/Automattic/wp-calypso/blob/master/client/state/selectors/is-eligible-for-dotcom-checklist.js#L36).

The date restriction was introduced in https://github.com/Automattic/wp-calypso/pull/28415
