### ISSUE TITLE
(5P) FSE: Research Gutenberg tracking

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#34037]
Talk to Gutenberg folks about the best way to track user actions.

See how much we can associate events with common properties, like class names, ids, innerHTML.
Add to the plugin that was introduced in #33322.

**Comment by obenland** [comment]
@mtias suggested checking how much we can get from Redux events before we go with an editor-wide onclick handler

/cc @Automattic/ajax

**Comment by marekhrabe** [comment]
good idea to explore - I know that's how a lot of things are tracked in Calypso. 

My only worry is that tracking tasks consist of specific UI elements to track as opposed to their actions (which might likely have multiple UI places to be called from). If we can confirm that's fine to do, I think we might get a lot from redux.

**Comment by obenland** [comment]
Results tracked in paYJgx-5g-p2.
