### ISSUE TITLE
(3P) Update API route to accept vertical slug

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#34038]
We read the vertical from `site_options`. This should be assigned during onboarding and should be the vertical _ID_.

eg: `https://public-api.wordpress.com/wpcom/v2/verticals/p31v28/templates`

However for some sites we are getting the Vertical _Name_.

eg: `https://public-api.wordpress.com/wpcom/v2/verticals/Cameras%20&%20Photography/templates`

We need to know either that 

1. It's ok to exclude those sites using _Name_ from the feature
2. Update the API to accept both types (ie: ID or Name)

**Comment by getdave** [comment]
Note that `synonyms` are also available and used for searching. Could we add the pretty slug to the synonyms for matching.

**Comment by obenland** [comment]
@michaeldcain It looks like some Jetpack sites save the vertical slug instead of the vertical id in their `site_vertical` option. We use that value to retrieve templates from the API.
Are you aware of that behavior, is that expected? Should it be changed? Or should we just update the API endpoint to accept either?

**Comment by michaeldcain** [comment]
> Note that synonyms are also available and used for searching.

@getdave I believe the synonyms won't be searched until the ES integration is complete.

> It looks like some Jetpack sites save the vertical slug instead of the vertical id in their site_vertical option.

@obenland: I believe that this is done when the user's input doesn't match to one of our verticals, and was done as part of some JP data analysis (panfyZ-18-p2). I don't think you should update your endpoint to accept either. @jeffgolenski @mikael what do y'all think of removing that exception?

**Comment by getdave** [comment]
Have chased in `CJS75TX3R/p1562148628090300-slack-ajax`

**Comment by jeffgolenski** [comment]
I'll let @simison speak to the technicalities of this. It doesn't matter to me how it's done. Just that we collect that data. Let me know if I'm missing anything!

**Comment by AnnaMag** [comment]
@obenland, @simison 

For Jetpack (and non-atomic) sites we indeed enabled free text for both Site Type and Vertical in D26585-code, meaning we save plain text if no id is encoded.

That said, data analysis of the vertical step ( see panfyZ-1w-p2 ) indicated that in fact, it can be removed. Or re-run, refined and removed, since its usage at the time of the analysis was < 3%.

**Comment by getdave** [comment]
See also `paObgF-k1-p2`.

**Comment by getdave** [comment]
# Important 

This is being addressed in `D30218-code`

**Comment by simison** [comment]
Steps collecting this data during jetpack flow being removed in https://github.com/Automattic/wp-calypso/pull/34506

**Comment by getdave** [comment]
Shipped `D30218-code`
