### ISSUE TITLE
Billing History: Cannot print receipts in Safari 9.0.2

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#3404]
## URL:

https://wordpress.com/me/billing/
## What I expected:

To be able to print out a receipt from the billing history page.
## What happened instead:

The receipt displayed when I clicked on View/print, but when I clicked the Print button the majority of the receipt was only white space.
## Steps to reproduce:

In Safari, open the Billing History page and click on View Receipt. On the receipt, click the Print Receipt button. The print preview will show the page header and the footer with the page URL, but the information in between is blanked out. Actual printouts appear the same as the preview. See screen shot below.

The receipt prints correctly on Firefox and Chrome.
## Browser / OS version:

Safari 9.0.2 on OSX 10.11.3
## Screen shot

<img width="405" alt="screenshot_2016_02_19__11_50" src="https://cloud.githubusercontent.com/assets/11873759/13173074/33190f1e-d704-11e5-8252-565b07a03af6.png">

**Comment by ehti** [comment]
Had a user in #319204-chat not being able to print receipts. Although they didn't reply back but Chatomattic said they were on Safari 9.

**Comment by catkit** [comment]
Same with this user here #323045-chat

**Comment by melanieharari** [comment]
This is a bit of an edge case, the browser has been updated since then, and we won't have resources to fix it any time soon. Closing this.
