### ISSUE TITLE
Mobile Upgrade Notice: Copy could be less terse

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#34053]
Similar to #33913, the copy for some of these notices could be lightened up to sound less robotic:

<img width="269" alt="Screen Shot 2019-06-17 at 3 51 30 PM" src="https://user-images.githubusercontent.com/2124984/59634266-602a2f80-911c-11e9-8b9c-9701c28a2b00.png">

Should this be "Get *the* WordPress.com app for your desktop"?

<img width="264" alt="Screen Shot 2019-06-17 at 3 52 07 PM" src="https://user-images.githubusercontent.com/2124984/59634267-602a2f80-911c-11e9-9298-49eb52b52db4.png">

Suggesting "WordPress.com at your fingertips -- download the desktop app."

**Comment by benhuberman** [comment]
I like your suggestion, @sixhours, but "at your fingertips" makes me think more about mobile devices/apps than the desktop app. Maybe something along the lines of...
> Fast, distraction-free WordPress.com -- download the desktop app.
Or
> Download the WordPress.com desktop app for a fast, distraction-free experience.

(We could tweak/trim either of these if there's a concern around space/length.)
