### ISSUE TITLE
Signup: Missing font weight in Preview with Professional Business

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#34056]
Currently, the preview with Modern Business theme is not loading a font weight 600 that's used in the actual theme. Therefore, all the text in 600 appears as 700. This gives a false impression of the theme.

![Screen Shot on 2019-06-18 at 00:27:10](https://user-images.githubusercontent.com/908665/59643255-dd2ac880-915f-11e9-9918-b9d2aeb2b834.png)

**Comment by michaeldcain** [comment]
Fixed by #34060
