### ISSUE TITLE
Checkout: unable to submit payments in the desktop app

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#3405]
I am currently unable to complete checkout in the desktop app using a new credit card -- running `master` in wp-calypso and wp-desktop on Linux.

When I click the Pay button after filling the credit card details, a blue notice saying "Submitting payment" appears but nothing happens. I've tried several times and users are not charged, and nothing happens even after waiting 3-5 minutes.

I have no issues when making purchases using WordPress.com credits, or using a stored credit card.

Opening the console with `Ctrl`+`Shift`+`I`, I see the following errors after clicking the button:

`Uncaught ReferenceError: jQuery is not defined(anonymous function) @ jquery.js:1`
`Uncaught ReferenceError: jQuery is not defined(anonymous function) @ paygate.js:34`
`Uncaught TypeError: Cannot read property 'setProcessor' of undefined @ build.js:81425`

This bug is also a blocker for merging https://github.com/Automattic/wp-calypso/pull/3363, since that adds purchases to signup in the app.

cc @peterbutler @scruffian

**Comment by gziolo** [comment]
Web version works properly. I could reproduce it also using Mac development version.

**Comment by gziolo** [comment]
This is bug we deal with when in Desktop mode:
https://github.com/atom/electron/issues/254

**Comment by gziolo** [comment]
We reverted changes because of issues with Calypso build.
