### ISSUE TITLE
Signup: Missing font weight in Preview with Sophisticated Business

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#34057]
Currently, the preview with Modern Business theme is not loading a font weight 600 that's used in the actual theme. Therefore, all the text in 600 appears as 700. This gives a false impression of the theme.

![Screen Shot on 2019-06-18 at 00:35:19](https://user-images.githubusercontent.com/908665/59643547-01d37000-9161-11e9-8fe6-86de4eeee7a1.png)

**Comment by michaeldcain** [comment]
Fixed by #34060
