### ISSUE TITLE
(3P) Full Site Editing: deploy the new version of the plugin to WP.com [2]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34068]
In order to be able to test and develop our new flow against Simple sites, we'll need to deploy the new version of the plugin to Dotcom first. This can be done by following the instruction in this FG article PCYsg-ly5-p2.

We also need to do it in order to start the process we all recently agreed upon - plugin updates on Dotcom at the end of each sprint (ideally on Monday).

**Comment by obenland** [comment]
WP.com: D29612-code, D29617-code, D29618-code
WP.org: http://plugins.trac.wordpress.org/changeset/2108772, http://plugins.trac.wordpress.org/changeset/2108780, https://plugins.trac.wordpress.org/changeset/2108784
