### ISSUE TITLE
Plans: Refactor Compare Plans page to use v1.2 of /plans/features endpoint

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#3407]
While working on Plans for mobile applications we introduced several improvement to `/plans/features` endpoint. Once we release Plans on mobile we should iterate also on Calypso version and align UI to make even better user experience.

Old endpoint:
https://public-api.wordpress.com/rest/v1.1/plans/features?pretty=true

New endpoint:
https://public-api.wordpress.com/rest/v1.2/plans/features?pretty=true

Please note that we introduced plans `property`which improves the way we handle messages displayed to the user. Check `D1104` for more details.

We should also investigate if we want to consume new version 1.3 of `Plans` endpoint which introduces different taglines.

/cc @mikeshelton1503 @breezyskies @daniloercoli

**Comment by breezyskies** [comment]
Just a quick note that I'm already seeing some unexpected changes to the plans info in the web:

<img width="725" alt="screen shot 2016-02-23 at 3 22 58 pm" src="https://cloud.githubusercontent.com/assets/3011211/13270206/5d3130ac-da41-11e5-8df0-72b0170f0faa.png">

The plan taglines are now longer, which is causing some display issues with the "current plan" checkmark. Can we keep the existing content in v1.1 until we're ready to change this out?

**Comment by daniloercoli** [comment]
> The plan taglines are now longer, which is causing some display issues with the "current plan" checkmark. Can we keep the existing content in v1.1 until we're ready to change this out?

That content comes from the `Plans` endpoint v1.2 - https://public-api.wordpress.com/rest/v1.2/plans/?pretty=true
A quick fix would be reverting the changes we made to the `tagline` field in the `Plans` endpoint. And (maybe) create a new version (v1.3) with new tagline/fields that will be only used on mobile for now.

I think we should fix the code, instead of shortening the tagline.
We can shorten the tagline for the english language, but what will happen on those more verbose languages?

**Comment by gziolo** [comment]
@breezyskies we reverted taglines for v1.2 and introduced new `Plans` endpoint v1.3 that we are going to use only for mobile apps development. Calypso version looks now like before:
![screen shot 2016-02-24 at 12 27 03](https://cloud.githubusercontent.com/assets/699132/13284043/fa058c92-daf1-11e5-85c5-66ac360ff305.png)

**Comment by breezyskies** [comment]
Thanks for reverting that @gziolo. We could fix the display issue separately, but I was mostly concerned with making untested copy changes to the existing design. We'll need to look at how / when to sync these up soon.

**Comment by fabianapsimoes** [comment]
@gziolo what's the current status of this?

**Comment by gziolo** [comment]
We should wait until `Plans` on mobile apps are deployed, then we should adjust web version to provide similar experience.

**Comment by fabianapsimoes** [comment]
@gziolo can you ping me and @breezyskies when this happens?

**Comment by gziolo** [comment]
Sure :)

**Comment by scruffian** [comment]
@gziolo - I checked in with @daniloercoli - the new plans endpoint is being used in the apps now, so we can start to look at implementing this :)

**Comment by gziolo** [comment]
Sounds great :)

**Comment by retrofox** [comment]
Just FYI @gziolo we aren't using this endpoint anymore in calypso. I'll remove the `features-list` lib and then close this one.

**Comment by gziolo** [comment]
Sure, that works, too :)
