### ISSUE TITLE
Full Site Editing: override Edit button link for Gutenframe [3]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34074]
Currently, the Edit button link that appears on hover will work fine in wp-admin context, but we need to make it work with Gutenframe too. That means overriding the default link that it produces to equivalent `/block-editor` path in Calypso and opening it in `parent` window.

---
**Update**

Reopening this issue since Edit button behavior is not handled properly. For example, if I'm editing the page at `/block-editor/page/{test-site}/30` and click on Edit for Header (ID: 21), after showing the Header editing view the route remains unchanged, instead of being updated to `/block-editor/page/{test-site}/21`.

This leads to some weird behavior: refreshing the header page will show the previous page view. By clicking back a couple of times, you get to see Calypso in an iframe - at this stage you can even switch the site and navigate to a different section entirely, but the above route still sticks.

Noticed this while trying to track down https://github.com/Automattic/wp-calypso/issues/34713.

**Comment by vindl** [comment]
Reopening this issue since Edit button behavior is not handled properly. For example, if I'm editing the page at `/block-editor/page/{test-site}/30` and click on Edit for Header (ID: 21), after showing the Header editing view the route remains unchanged, instead of being updated to `/block-editor/page/{test-site}/21`.

This leads to some weird behavior: refreshing the header page will show the previous page view. By clicking back a couple of times, you get to see Calypso in an iframe - at this stage you can even switch the site and navigate to a different section entirely, but the above route still sticks.

**Comment by mmtr** [comment]
@jeraldjuice FYI, I just opened https://github.com/Automattic/wp-calypso/pull/34738 where I'm expecting the edit buttons to redirect to URLs like `/block-editor/edit/wp_template_part/:atomicSiteDomain/:templatePartId?fse_parent_post=:pageId`.
