### ISSUE TITLE
Bug: Edit Post URL

### ISSUE THREAD

**Issue by starxedsteph** [Automattic/wp-calypso#3408]
## URL
https://wordpress.com/post/  (editor for any post)
Reported in [Forum Post](https://en.forums.wordpress.com/topic/edit-post-didnt-work?replies=6
)

## What I expected
For the "Edit Post URL" chain link to have the URL next to it that allows me to edit the URL text.

## What happened instead
The URL does not display and clicking the chain link returns this error in the JS console:

`build-stage.89c85c2bbc760069d3c1.min.js:45  Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(PostEditorSlug)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(PostEditorSlug)".`

## Steps to reproduce
Click the "Edit Post URL" icon in any post.

## Browser / OS version:
Chrome 48 on Mac OS X
Safari 9 on Mac OS X
Firefox 44 on Windows 7

## Screenshots / Video:
https://cldup.com/Fons7rOo49.png

**Comment by lancewillett** [comment]
Thank you for the report! I can repeat in Mac-n-Chrome using my `testerlance` user and test blog.

![screen shot 2016-02-19 at 11 29 21](https://cloud.githubusercontent.com/assets/66797/13184973/113c0a02-d6fc-11e5-89f3-d09724989308.png)

**Comment by lancewillett** [comment]
Thanks for the quick fix!

Confirmed working again:

![screen shot 2016-02-19 at 13 09 27](https://cloud.githubusercontent.com/assets/66797/13187720/0f89cb32-d70a-11e5-86e9-d6aa8bcdc43d.png)

**Comment by starxedsteph** [comment]
So fast!  Thank you!
