### ISSUE TITLE
Editor: Floating GroundControl panel leaves a gap prior to resetting static appearance

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#341]
![gap](https://cloud.githubusercontent.com/assets/1779930/8916765/b55e8d40-347b-11e5-8c1a-39cefb809fdc.gif)

__Steps to reproduce:__

1. Navigate to the [Calypso post editor](http://wordpress.com/post)
2. Select a site, if prompted
3. Scroll down the page until the Ground Control (i.e. status) panel becomes fixed
4. Scroll up until just before the panel is reset to no longer be fixed
5. Note the gap between the panel and the sidebar accordions

__Expected behavior:__

I would not expect there to be such a gap when scrolling back up to the top of the page.

raised by aduth

**Comment by aduth** [comment]
Fixed by #2131
