### ISSUE TITLE
Design a skip button in the domains step of the onboarding flow

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#34100]
This card is about exploring what's the best option to A/B test skipping the domains, Some research and design work is required before we get to the implementation.

**Comment by fditrapani** [comment]
In addition to the skip, I'm wondering if we should be showing people the default option that would used if they skip. Thoughts?

cc @michaeldcain

**Comment by fditrapani** [comment]
Either way, it would be good to mock this up before we implement anything.

**Comment by adamziel** [comment]
Let's hold on then until there's a mock or design we can talk about

**Comment by adamziel** [comment]
@fditrapani I added a Design label and updated the description to reflect more the fact that we need to still work on mocking

**Comment by fditrapani** [comment]
Thanks @adamziel. @shaunandrews is on the case!

**Comment by michaeldcain** [comment]
P2 discussion: paObgF-hi-p2

**Comment by shaunandrews** [comment]
Here's a simple solution that adds a skip button to the domain step, below the explanatory text+illustration:

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/191598/60184601-55475d00-97f6-11e9-99f8-eba114edc47c.png">

Alternatively, I think we might be able to add a new step that lays out the options for a domain:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/191598/60184673-790aa300-97f6-11e9-8b83-d34496b423d9.png">

--

I have a slight preference for the new step, but I understand that is more complex.

Here's the Figma file: https://www.figma.com/file/I5wPkPsKydrFXjNHwr5XWWQQ/Skip-Domains-in-Signup?node-id=0%3A1

**Comment by fditrapani** [comment]
Thanks @shaunandrews. The first screenshot should be good enough to get development started. I'd like to replace the "Skip" copy with one of the other options that came up in the comments of your p2 post. We can circle back on that during development with final copy.

cc @adamziel

**Comment by shaunandrews** [comment]
Ah yes, the Figma has a few alternatives for the label. I have both "Skip for now" and "Choose this later". I'm leaning towards "Skip for now" as I suspect people will look for the word "skip".

**Comment by fditrapani** [comment]
"Skip for now" works for me.

**Comment by fditrapani** [comment]
This is ready for dev @adamziel. Please use the design Shaun provided with the copy "Skip for now" and ping us on the PR for review.
