### ISSUE TITLE
Stats: Discrepancy in Page & Post View Calculations Depending on UI Language

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#34109]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/example.com with your Interface Language set to English.
2. Switch to Week view and choose a week that has some traffic across a few different posts & pages.
3. Observe that the views listed under Posts & Pages on this overview screen are the same as when you click into the Posts & Pages screen.
4. Switch your Interface Language to Spanish or German.
5. Repeat steps 2 & 3, noticing the numbers are different.

#### What I expected

The numbers would be the same on the main overview screen and the Posts & Pages screen.

#### What happened instead

The numbers are different. The “Posts & Pages” totals are consistently lower than the totals on the overview page. With my language set to German and Spanish, the stats I see on the Posts & Pages screen match the stats for the corresponding Sunday (a single day instead of the entire week instead of the full week.)

The suspected cause (courtesy of @rachelmcr) is:

* In locales like Germany and Spain the week is Monday-Sunday, while in the US it’s Sunday-Saturday.
* The overview page is making the API request for the week ending on Saturday, no matter what, while the API request for the Posts & Pages screen depends on the UI language (requesting stats for the week ending on Saturday when set to US English, but requesting stats for the week ending on Sunday when set to e.g. German).
* The way the weekly stats are calculated, by requesting the weekly stats for a week ending on Sunday (instead of Saturday), the only stats being returned are the ones for that Sunday.

#### Browser / OS version

Not browser-specific.

#### Screenshot / Video

English (main screen): https://cld.wthms.co/a5GU3Q
English (Posts & Pages): https://cld.wthms.co/ohSL9b

German (main screen): https://cld.wthms.co/TzjhVT
German (Posts & Pages): https://cld.wthms.co/Mf2HoB

Spanish (main screen): https://cld.wthms.co/HpNI3O
Spanish (Posts & Pages): https://cld.wthms.co/kNEUjw

#### Context / Source
#2090644-zen

**Comment by rickmgithub** [comment]
Hi. The user came back saying the following regarding the previous screenshots.

I switched languages after making them so that I could better communicate with support. I’ve attached 2 new screenshots.

They provided the two extra screenshots here - 
https://woothemes.zendesk.com/attachments/token/m2RZ4IzJ54IOBxP0FzZuD20wh/?name=1.JPG
https://woothemes.zendesk.com/attachments/token/1qfboEr5nkGLf8sf8ewcanjWv/?name=2.JPG

**Comment by donalirl** [comment]
Just to add context to @rickmgithub's comment, the user's language in those screenshots is set to English (UK) which appears to have the same bug as German and Spanish. Except English UK seems to have a week of Tuesday → Monday.

The numbers are accurate with the _American_ English, not the UK one.

Can we standardize the stats week view across all languages?
