### ISSUE TITLE
Customizer: Exit button confused with back arrow

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#34121]
In quite a few Concierge Sessions I found that users accidentally exit the Customizer instead of navigating to a previous section. This is the case for all sites without plugins. Visually, the exit icon is composed of a back arrow `←` and a closing square bracket `]`, hence it looks similar to the angle bracket `<`.

The original exit icon is [here](https://wordpress.com/wp-content/mu-plugins/theme-customizer/css/exit.svg).

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize/
2. Navigate to any subsection

#### What I expected
See an `X` button for exiting and `<` for navigating back to the previous (parent) section. This is the case for all sites with at least one plugin installed.

![](https://cld.wthms.co/YYsPam+)

#### What happened instead
See ![](https://cld.wthms.co/FkUCOt+) button for exiting and `<` for navigating back to the previous (parent) section.

![](https://cld.wthms.co/apCGuE+)

#### Context / Source

#dogfooding #user-report

**Comment by sixhours** [comment]
I can totally see the confusion here; thanks for bringing it to our attention! I think we will probably revert the change, but I'd like to get a second opinion. @scalarbane2 @lcollette can you take a look at the ticket history and let me know what you think?

**Comment by sixhours** [comment]
Started a patch to revert this change in D30103-code

**Comment by donpark** [comment]
> Started a patch to revert this change in D30103-code

D30103 accepted. :-)

**Comment by sixhours** [comment]
Thanks! Deployed in r193863!
