### ISSUE TITLE
FSE: Investigate intermittent Template rendering issue on Template insertion

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#34176]
Occasionally on Template selection and insertion, there is a rendering error whereby half of the Editor contents are completely invisible. Very odd.

Only happens in Chrome.

See `p58i-7RD-p2#comment-42214`

**Comment by marekhrabe** [comment]
I have seen this bug several times working on the core Gutenberg. Quite sure it's not something we are directly causing with our plugin but it's possible it's combination of blocks which triggers the error. 

As we have a good reproducibility with our content we might help to create and/or update a core issue for this bug.

**Comment by obenland** [comment]
Fixed in Gutenberg Core.
