### ISSUE TITLE
(1P) FSE: Normalise and match the vertical spacing below and above the help text in the Modal

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#34175]
Currently, the help text on the Page Template selector modal has unequal spacing. Fix that.

See `p58i-7RD-p2#comment-42213`

**Comment by marekhrabe** [comment]
When you hover a tile you will see why it looks like there is more space under the intro text. The actual spacing from the code perspective is equal for "above" and "under", however the tile's invisible padding causes the gap to be bigger.

<img width="804" alt="Screenshot 2019-06-21 at 12 47 55" src="https://user-images.githubusercontent.com/156676/59917676-d7b0d500-9422-11e9-9f1a-1818fd5929c0.png">

Should we lower the bottom margin of the intro text by the size of the padding inside the tile so it looks equal without hovering anything?

**Comment by getdave** [comment]
Could we utilise a negative margin on the intro text to compensate for this?
