### ISSUE TITLE
Users can purchase Site Redirect upgrade on Atomic sites despite feature being incompatible

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#34189]
The Site Redirect upgrade will only work on simple sites, and is not compatible with Atomic sites. Users should not be able to purchase this upgrade for an Atomic site, since it will not work. However, users are still able to purchase it, then they contact support, confused/frustrated when something they spent money on is not working.

#### Steps to reproduce
1. Add a site redirect to an Atomic site starting here https://wordpress.com/domains/add/site-redirect
2. You will have no issues completing the checkout process and will see no warnings about the upgrade not being compatible with your site
3. The redirect will not work.

#### What I Expected

To see some sort of warning/message about the upgrade not being an option for my site and an alternate way I can accomplish a site redirect. Atomic sites can use a redirection plugin instead, so that could be mentioned in the messaging.

#### Context / Source
#user-report This came up yesterday in #13540992-hc

**Comment by Aurorum** [comment]
PR for this issue in #34907 :)
