### ISSUE TITLE
"Feedback" link in sidebar turns Calypsoify on for Jetpack sites

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#34204]
When controlling a Jetpack site in Calypso and pressing "feedback" from the sidebar, Calypsoify is turned on.

<img width="346" alt="Screenshot 2019-06-22 at 14 09 40" src="https://user-images.githubusercontent.com/87168/59963749-2ed8a780-9500-11e9-867b-b1783b5ae3c3.png">

<img width="1440" alt="Screenshot 2019-06-22 at 14 09 24" src="https://user-images.githubusercontent.com/87168/59963751-30a26b00-9500-11e9-82c3-c0a2ab24ce82.png">

From that on, users's whole wp-admin is Calypsoified:

![image](https://user-images.githubusercontent.com/87168/59963746-2aac8a00-9500-11e9-91fa-13b04f8f71b2.png)

#### What I expected

No Calypsoified styles for a Jetpack site.

#### What happened instead
Calypsoified.

cc @gwwar @dereksmart  do you know what team nowadays owns Calypsoify flows?

**Comment by gwwar** [comment]
> do you know what team nowadays owns Calypsoify flows?

There's no particular team assigned, but I would hope that we can update the behavior here a bit in future janitorials, and to consolidate implementations on Simple/Jetpack. The original implementation was for plugin support for Atomic sites and it stores a boolean on user meta, which makes this sticky for all sites until a user hits root `/wp-admin` ( p58i-76F-p2 )
