### ISSUE TITLE
Full Site Editing: Request to hide Edit link for logged out users

### ISSUE THREAD

**Issue by rwaynick** [Automattic/wp-calypso#34209]
#### Steps to reproduce
1. Use the `Blog Posts Listing` on a new page.
2. Open page in Private/Incognito window.
3. Notice that Edit link is shown.

![Screen_Shot_2019-06-23_at_4_00_59_PM](https://user-images.githubusercontent.com/10882502/59981365-29e32900-95d0-11e9-98a9-20f33d3ed33b.jpg)

#### What I expected
 
I expected the Edit link to only be shown for logged in Users of the site that have Editing ability.

#### What happened instead

The Edit link was shown in the post list for each post no matter if I was logged in or not.

#### Browser / OS version

Chrome 75.0.3770.100 on macOS 10.14.5

#### Context / Source

#user-report 
13056989-hc

The user mentioned,

> Having an edit button will look odd to readers.
> Diminishes the credibility of the site.

In the meantime they used some CSS to hide it.

```
.a8c-posts-list-item__edit-link {
	display: none !important;
}
```

**Comment by arunsathiya** [comment]
I am not able to reproduce this anymore. 

On testing with a site without FSE activated, I added the `Blog posts listing` block and I do not see the `Edit` button anymore.

<img width="616" alt="Screenshot 2019-08-17 at 16 43 55" src="https://user-images.githubusercontent.com/18581859/63210937-5453ed00-c10e-11e9-9998-1f349d287577.png">
<img width="566" alt="Screenshot 2019-08-17 at 16 43 51" src="https://user-images.githubusercontent.com/18581859/63210938-5453ed00-c10e-11e9-8e55-49c5c48eb35d.png">

In the case of a site with FSE activated using instructions on p58i-7YJ-p2, I see this coming soon template instead, so, the original concern isn't the same.

<img width="1228" alt="Screenshot 2019-08-17 at 16 42 36" src="https://user-images.githubusercontent.com/18581859/63210942-6e8dcb00-c10e-11e9-9e8b-1249561715fd.png">

I think this report can be closed, but if we are able to continue and report this, let's open again.
