### ISSUE TITLE
Rename the first checklist task from "You launched your site" to "You created your site"

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#34215]
![image](https://user-images.githubusercontent.com/205419/60009520-4cc81880-9676-11e9-963d-1340bffe0304.png)

"You launched your site" seems to contradict the main heading, and (with private-by-default) confuses terms. We should change it to "You created your site"

**Comment by davipontesblog** [comment]
This seems to be done so I am closing it for now.
