### ISSUE TITLE
Suggestion: Add hourly stats widget to dashboard sidebar when Stats is selected

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#34218]
It's not immediately apparent where to find the hourly stats widget in the Calypso dashboard. Clicking on the site name near the site switcher reveals it. It may be worthwhile making it visible when clicking on the _Stats_ menu item.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Open the WordPress.com dashboard for the site.
3. When you click on _Stats_, the hourly stats graph isn't visible.
4. When you click on the site name near the site switcher, the hourly stats graph appears.

Here's a demonstration:

![hourly_stats_sidebar](https://user-images.githubusercontent.com/2912202/60026415-32a52f00-96a4-11e9-93cc-e05793a7c25b.gif)

#### What I expected

Arguably, have the hourly stats widget appear when I click on _Stats_ (even if this is in addition to the current trigger/location).

#### What happened instead

It's not immediately apparent how to find the hourly stats widget.

#### Browser / OS version

Not relevant.

#### Context / Source

This was a #user-report in 3710879-hc

**Comment by lancewillett** [comment]
Re-opening since a valid fix is ready in https://github.com/Automattic/wp-calypso/pull/34230
