### ISSUE TITLE
Checkout: Update `state.receipts` from `store-transactions`

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#3422]
@stephanethomas [pointed out](https://github.com/Automattic/wp-calypso/pull/3270#discussion_r53483645) that handing off data between the transactions store and the global state tree via `Checkout` isn't ideal:

> I'm not a big fan of accessing the transaction data directly like this. It would be great to hide that logic by using the receipts reducer. To be more specific, what I suggest is to update the `store-transactions` module to update the [receipts state tree](https://github.com/Automattic/wp-calypso/tree/master/client/state/receipts) when [receiving a response](https://github.com/Automattic/wp-calypso/blob/master/client/lib/store-transactions/index.js#L172) from the API. What do you think? That way we would also reduce the number of lines of code by reusing the [receipt assembler](https://github.com/Automattic/wp-calypso/blob/master/client/state/receipts/assembler.js).

I'm not sure how we can provide `store-transactions` with the Redux dispatcher, but we are going to investigate this.

**Comment by stephanethomas** [comment]
We spent some time trying to figure out a way to refactor this code to no avail, for the reason @drewblaisdell mentioned. Since it's probably not a good idea to allocate more time on that considering how little value it would add I'm going to close this issue.
