### ISSUE TITLE
Copy Sync: SEO setting

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#34234]
Before:

![Screenshot 2019-06-24 at 17 44 46](https://user-images.githubusercontent.com/411945/60036735-d2b08780-96a7-11e9-8425-abcba0b40598.png)

After:

See PR: https://github.com/Automattic/jetpack/pull/12796

As part of a [recent copy sprint](https://github.com/Automattic/jetpack/projects/23) on Jetpack, many small changes were made to the settings and interface copy. This issue is a sync of the original Jetpack issue, it can be found here:

https://github.com/Automattic/jetpack/issues/9754

**Comment by eeeeevon13** [comment]
@scottsweb I did not update the upgraded copy as it appears to behave a little differently than on WP admin side. The link doesn't take you to edit your settings it takes you to an info page. Thought we should discuss a bit. I'm not quite sure what I'm looking at.

**Comment by eeeeevon13** [comment]
I also noticed that when you go from an upgrade prompt to an upgrade in the flow, the wording on the CART page no longer carries the Jetpack branding. We should probably address that at some point

**Comment by scottsweb** [comment]
Closing as this does not translate well between Jetpack and Calypso.
