### ISSUE TITLE
FSE: The navigation menu block needs a full render on the front-end.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#34239]
Currently, the navigation menu block renders the same for the editor and the front-end: a stripped down preview version intended only for the block editor. We'll need to add a new render function for the front-end and handle the switching, [similar to the site logo block](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-logo/index.php#L15).

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
