### ISSUE TITLE
Publicize connection cannot be managed from Calypso

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#34236]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/marketing/tools/domain.com
2. Make sure this is a Jetpack connected site
3. Notice you cannot manage your social connections or turn this feature on (screenshot 1)
4. Head to wp-admin and enable publicize wp-admin/admin.php?page=jetpack#/sharing
5. You can now manage connections (screenshot 2)

#### What I expected

To be able to enable publicize from Calypso, we have a marketing card in screenshot 1 that suggests I can.

#### What happened instead

I could not find the setting

#### Browser / OS version

All

#### Screenshot / Video

![Screenshot 2019-06-24 at 17 56 51](https://user-images.githubusercontent.com/411945/60037573-d04f2d00-96a9-11e9-8b61-eb9d4d909a2f.png)

![Screenshot 2019-06-24 at 17 58 42](https://user-images.githubusercontent.com/411945/60037582-d513e100-96a9-11e9-8d0c-e31bc0ebac52.png)

**Comment by MichaelArestad** [comment]
Well I could have sworn there was a setting for it, but I can't find it. It's on by default so it's not entirely necessary.

**Comment by simison** [comment]
@MichaelArestad @scottsweb do you know if this is on someone's agenda?

**Comment by scottsweb** [comment]
@simison I do not think it is on anyones agenda. I only noticed it when looking to sync up copy changes. I agree that it feels like quite a big issue. Especially given that we have an advert for Publicize in Calypso for Jetpack sites:

![Screenshot 2019-06-28 at 09 24 54](https://user-images.githubusercontent.com/411945/60328651-a1c1a280-9986-11e9-9cb6-facbcd347157.png)

Clicking it takes you to the sharing buttons screen when the setting is off in wp-admin:

![Screenshot 2019-06-28 at 09 25 49](https://user-images.githubusercontent.com/411945/60328709-bdc54400-9986-11e9-8c8c-0c7dbcd3fba8.png)

When this setting is switched on, it behaves as expected.

**Comment by simison** [comment]
So seems like this might've started when sharing/publicize was removed from Jumpstart? (assuming it was)

**Comment by scottsweb** [comment]
I need to check that actually, I will be setting up a new site shortly so will see what I get by default.

**Comment by scottsweb** [comment]
Just created a new site (7.5-alpha) and it doesn't get enabled by default. We no longer have jumpstart either - the checklist is used instead.

**Comment by simison** [comment]
Yeah for latest 7.5 for sure not since no more jumpstart, but I was wondering if publicize was dropped from jumpstart that shipped already in v7.2—3 -ish. Pretty sure it was removed so this has been broken for a while already. Doesn't matter much since in the latest version it's dropped and at any rate, someone needs to deal with this now. :-)
