### ISSUE TITLE
Domains: shows validation errors with placeholder values ( IE11 only )

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#3423]
I found the following while testing #3026
## URL:

```
http://calypso.localhost:3000/domains/manage/<yourdomain>/dns/<yourdomain>
```
## What I expected

![screen shot 2016-02-19 at 2 39 03 pm](https://cloud.githubusercontent.com/assets/1270189/13191137/896c0aee-d716-11e5-9378-ab750d9498dd.png)
## What happened instead

![screen shot 2016-02-19 at 2 29 39 pm](https://cloud.githubusercontent.com/assets/1270189/13191130/81b5ceac-d716-11e5-9034-1fd70227a940.png)
## Steps to reproduce
- Navigate to domain management
- Click on the type dropdown: Select A or AAA
- Wait a tick
-  The default placeholder will now show red with a validation error
## Browser / OS version

IE11/Win10 (Edge is fine)

**Comment by BandonRandon** [comment]
Confirmed still happening in IE11
![capture](https://cloud.githubusercontent.com/assets/150348/15061391/a2c959ce-12e9-11e6-90dd-f96f686246c5.PNG)

**Comment by cathymcbride** [comment]
IE11 won't be supported starting Aug 2021. Closing as this doesn't seem worth fixing at this point.
