### ISSUE TITLE
Checkout: Show post-checkout message errors to user

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3424]
If a post checkout actions fail for some very rare reason, ie. we charge the user but the domain could not be registered, we refund the amount in store credits and need to show a message to the user.

@breezyskies How shall we show the message the user?

/cc: @aidvu 
Related: D916-code D869-code

**Comment by breezyskies** [comment]
Is this something we would know failed by the time they hit the thank you page, or is it better-suited for a follow-up email (in replace of the receipt)?

**Comment by umurkontaci** [comment]
> Is this something we would know failed by the time they hit the thank you page

Yes, we'd know at the end of the transaction.

**Comment by breezyskies** [comment]
Do you have a list of possible reasons for failure, just to give me some context?

**Comment by umurkontaci** [comment]
As far as I know, this should happen very rarely since we do some pre-checks before authorizing a transaction, but they might still occur for example if a 3rd party API request fails and we fail to register. 

@aidvu and @dzver will be able to provide more details.

**Comment by aidvu** [comment]
@breezyskies If for some reason external APIs fail, timeouts, network failures. This can happen for domains or Google Apps. We currently refund what's spent, and the list of failed product purchases is returned. We want to tell the user what failed, and that we gave him credits to try again, instead contact support.

Makes sense?

**Comment by breezyskies** [comment]
Makes sense. I've added this to Cerulean's list to look at next week.

**Comment by umurkontaci** [comment]
cc: @fabianapsimoes keeping you in the loop since this is very likely to land in post-purchase thank you page.

**Comment by breezyskies** [comment]
As discussed in Slack, we should display this error messaging on checkout, with the products that failed in the cart, along with appropriate credits added to the account (should be $0 owed at that point with the credits). Validation errors will be handled separately, and the `error 2004 domain already registered` is already fixed.

On checkout, we should display a generic error (since there are a few possible reasons for this, and we're not going to address every one individually at this time):

<img width="826" alt="screen shot 2016-03-03 at 2 49 02 pm" src="https://cloud.githubusercontent.com/assets/3011211/13512422/692a5ebe-e14f-11e5-937e-377b88873e9c.png">

> There was a problem completing the purchase of these products, so we've issued you credits to try again. If you continue to experience this problem, please contact support.

cc: @ranh for copy review -- I'm trying to make sure this doesn't look like a "your payment failed" error, but not let it get too long. Let me know what you think.

**Comment by breezyskies** [comment]
Note that the suggested copy would need to be pluralized based on products in the cart.

**Comment by ranh** [comment]
Do we know exactly which products failed? "These products" is a bit vague. Since we're asking the user to try again, we should be clearer on what they need to try.

How about something simpler?

> There was an issue with your purchase of (Product). We credited your account so you can try again. Please [contact support](#) for help.

**Comment by fabianapsimoes** [comment]
@umurkontaci is this something Cobalt will work on? Asking because Spencer recently prioritized it for Amber, so I'm making sure we're not colliding.

**Comment by breezyskies** [comment]
@ranh Good suggestions -- what about just rewording the support bit like this so they only contact support if the problem persists (hopefully they will try the credit purchase again first):

> There was an issue with your purchase of (Product). We credited your account so you can try again. If you continue to have problems with this purchase, please [contact support](#).

**Comment by umurkontaci** [comment]
@fabianapsimoes That was in Cobalt's backlog as well, but this fits more in your area than ours, so if it is something you can prioritize to get it done in the following week then go for it. If it's going to take any longer I think we can get it done

**Comment by fabianapsimoes** [comment]
I'm not sure we can get to it in the following week. If it's a hurry, feel free to grab it. Let me know :)

**Comment by ranh** [comment]
@breezyskies Yeah that's much better, mine did read a bit like contacting support was the suggested next action

**Comment by umurkontaci** [comment]
@fabianapsimoes I'll give it a shot, you can remove it from your backlog

**Comment by fabianapsimoes** [comment]
Sounds good! Thanks @umurkontaci. Let us know if you have any questions re the Thank You page!

**Comment by umurkontaci** [comment]
- [ ] "Back to My Sites" button doesn't work when purchases is empty
- [x] `redirectIfThemePurchased` throws when purchases is empty

**Comment by umurkontaci** [comment]
@fabianapsimoes @aidvu @spncrb 
By the time I made plans for this and the time I was able to start working on this; many things have changed in the code. The plan was to return the failed purchases in an array as a result of the transaction, but now the checkout thank you page seems to be using the receipt data as the source of truth, and we don't have a record of failed purchases in the receipt itself.

I need your advice on what to do with this going forward.

Also, @aidvu we don't cancel failed products - I intentionally failed a domain registration after we have registered it; still got a receipt for $0 (including the items I've purchased); the domain has been registered and whois info matches, but it is not tied to my account. (It's a semi-edge that I broke in intentionally but it seems the effects of this is big (domain exists but not tied to any account); we might want to reiterate on this.

**Comment by fabianapsimoes** [comment]
@umurkontaci from this comment https://github.com/Automattic/wp-calypso/issues/3424#issuecomment-192005146 from Brie, it seems the plan was to display the error in checkout, not in the Thank You page. If this changed, what's the current design for this error?

**Comment by aidvu** [comment]
Not sure about the Thank You page. The receipt seems good. Maybe you can
pass the failed purchases to the "Thank You" page?

As for the cancelations. You either register a domain or not. How it would
be possible to register a domain and then have failed domain products
afterwards?

If it's only privacy, it's ok.
If it's domain registration, the privacy is in the same call.

**Comment by umurkontaci** [comment]
@fabianapsimoes I noticed @breezyskies mentioned checkout just now, but I'm not sure if it's the right fit. We are not cancelling the rest of the items in the cart, but only the ones that failed on post-purchase actions. (If there dependent items, those are cancelled). 

If the user has multiple items in cart one of them went through, we don't want them to try again with the same cart.

**Comment by umurkontaci** [comment]
@fabianapsimoes It seems we won't be able to spend more time into this issue. Do you mind taking it over and fixing at your convenience?

**Comment by fabianapsimoes** [comment]
It depends on where the change will be in the end. If it's on `checkout/thank-you`, happy to add it back to our backlog. If it's on `/checkout`, it probably makes more sense to have Gold take a look (cc @peterbutler). I've added the Post Checkout label for now, so it doesn't fall through the cracks.

@breezyskies would you mind reviewing your recommendation based on Umur's input in https://github.com/Automattic/wp-calypso/issues/3424#issuecomment-205132326?

**Comment by breezyskies** [comment]
I chat with @umurkontaci about this in Slack. The main concern about showing the error on either the checkout _or_ thank you page was that some of the purchases may have gone through just fine, so the user then ends up in this weird state where some purchases worked an others didn't. 

Instead, we discussed canceling all purchases in the cart and landing the user back on checkout with the messaging above. While still far from ideal, at least it removes the issue of the mixed messaging, and lands the user right where they need to be to try purchasing again.

**Comment by fabianapsimoes** [comment]
> Instead, we discussed canceling all purchases in the cart and landing the user back on checkout with the messaging above.

Changing labels and milestones so Gold can take a look then.

**Comment by kristarella** [comment]
FWIW some of the most common reasons for domain failing to register are:
- Host no found [ns1|ns2].wordpress.com (error on WWD's end)
- DBP ID verification failed (can't register with privacy, needs to be registered without, then DBP ID reset, then privacy enabled)
- Contact info validation failure (user might have entered bad postcode format or phone number) (becoming more common as oSRS/HRS is more strict with contact verification than WWD)

Also, in my experience, when registration fails we show the regular thank you message, but the shopping cart remains on the left side of the page, like this:
![image](https://cloud.githubusercontent.com/assets/2031017/20332183/3cd1b5ae-abfe-11e6-97ad-bc27ca2007e8.png)

**Comment by aidvu** [comment]
Fixed: https://github.com/Automattic/wp-calypso/pull/10328
