### ISSUE TITLE
Full Site Editing: Post Content Disappears on Second Edit

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34243]
On subsequent page editor, post_content fails to load in the editor:

To reproduce:
- Install the FSE plugin, and activate it
- Edit a page
- Note that the header and footer template appears, within the page editor.
- Make some post content changes and save
- Verify that the published view reflects this.
- Edit the page again (with a refresh). The post_content is missing in the block editor.

**Comment by glendaviesnz** [comment]
I have a follow on fix from #34289 at https://github.com/Automattic/wp-calypso/blob/fix/fse-template-content-parsing/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L475 - which allows for changing post content attributes, as well as properly applying the existing attributes - just need to do a bit more testing and will put up a PR for this
