### ISSUE TITLE
Videos: video thumbnails are displayed as regular images in media list

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#34259]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media
2. Upload a video on a site that supports it (a Jetpack site with a Premium plan and the Video feature active, for example).
3. Once the video has been transcoded, you'll notice the thumbnail appear next to the video.
4. Every time you change the thumbnail, a new image is generated and appears next to the video:

<img width="500" alt="screen-shot-2019-06-24-at-10 44 12-pm" src="https://user-images.githubusercontent.com/426388/60080430-35e5fc80-9730-11e9-8d28-3ae1787aa238.png">

#### What I expected

The video thumbnails should be hidden from the media list, just like in w-admin:

![image](https://user-images.githubusercontent.com/426388/60080471-4eeead80-9730-11e9-9eda-5660a3016d6a.png)

Reported in p8oabR-nm-p2#comment-3112

**Comment by kriskarkoski** [comment]
A user asked about this in #14208655-hc. They wanted to see the thumbnails in both, but I think consistency is more important generally.
