### ISSUE TITLE
Full Site Editing: Simple Site Page Template Support [5]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34288]
As a follow up to https://github.com/Automattic/wp-calypso/pull/34196 let's add support for Simple Sites to correctly render the full site header and footer using our new page template, when a related improved on-boarding Twenty Nineteen theme is chosen.

**Manual setup in WP.com**

See steps in PCYsg-ly5-p2 for how to get latest plugin changes on the sandbox.

Since the FSE data is not created automatically on WP.com yet (https://github.com/Automattic/wp-calypso/issues/33515), we need to perform the following steps manually before testing:

- Create a header template part with the following blocks:
  - Site title
  - Site description
  - Navigation menu (default location)
- Assign the `header` template part type to the previous template part.
<img width="882" alt="Screen Shot 2019-07-03 at 14 29 43" src="https://user-images.githubusercontent.com/1233880/60565618-438a2a80-9d9f-11e9-88da-6d4ea699b5e7.png">

- Create a footer template part with the following blocks:
  - Navigation menu (footer location)
- Assign the `footer` template part type to the previous template part.

- Create a template with the following blocks:
  - Header template part
  - Post content
  - Footer template part
- Make sure all the previous blocks are either full or wide width:
<img width="602" alt="Screen Shot 2019-07-03 at 14 34 31" src="https://user-images.githubusercontent.com/1233880/60565745-b4c9dd80-9d9f-11e9-960f-6c4fd503022d.png">

- Create a new page.
- On the FSE sidebar, select the template created above:
![image](https://user-images.githubusercontent.com/1233880/60566413-cc09ca80-9da1-11e9-9e6e-d06f3e5919ad.png)

- Publish the page and reload the editor, so the template is applied.

**What's need to be tested?**
Verify that:
- In the page editor, we see the FSE header and footer in the block-editor
- Header and Footer is seen in the published view
- We can add dynamic blocks, and they are correctly represented in the header/footer.

**Current issues**
Actual:
~~After manually adding the template, and template parts, and setting a page to using the page template, we see empty header/footer previews.~~ (@mmtr: I think this issue is not reproducible if we follow all the manual population steps).

![error](https://user-images.githubusercontent.com/1270189/60553862-031ca500-9cea-11e9-8610-8fc6d39b0322.gif)

Clicking on the header or footer we see:
<img width="1079" alt="Screen Shot 2019-07-02 at 4 51 22 PM" src="https://user-images.githubusercontent.com/1270189/60553882-1cbdec80-9cea-11e9-8411-2c9eb1e45538.png">

Expected:
<img width="1322" alt="Screen Shot 2019-06-25 at 4 45 56 PM" src="https://user-images.githubusercontent.com/1270189/60141064-b7f21780-9768-11e9-9eb9-0558052f78ad.png">

**Comment by mmtr** [comment]
Some first findings I noted so far that are different from behavior in self-hosted sites:

**`A8C_WP_Template::get_template_content` is returning extra lines between blocks**

```
<!-- wp:a8c/template {"templateId":1657} /-->

<!-- wp:a8c/post-content /-->

<!-- wp:a8c/template {"templateId":1658} /-->
```

That's generating some invalid blocks when parsing blocks with `parse_blocks`:

```
 Array
(
    [0] => Array
        (
            [blockName] => a8c/template
            [attrs] => Array
                (
                    [templateId] => 1657
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 
            [innerContent] => Array
                (
                )

        )

    [1] => Array
        (
            [blockName] => 
            [attrs] => Array
                (
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 


            [innerContent] => Array
                (
                    [0] => 


                )

        )

    [2] => Array
        (
            [blockName] => a8c/post-content
            [attrs] => Array
                (
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 
            [innerContent] => Array
                (
                )

        )

    [3] => Array
        (
            [blockName] => 
            [attrs] => Array
                (
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 


            [innerContent] => Array
                (
                    [0] => 


                )

        )

    [4] => Array
        (
            [blockName] => a8c/template
            [attrs] => Array
                (
                    [templateId] => 1658
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 
            [innerContent] => Array
                (
                )

        )

)
```

When testing in Core, `get_template_content` returns all the markup in one single lines:

```
<!-- wp:a8c/template {"templateId":41,"align":"full"} /--><!-- wp:a8c/post-content {"align":"full"} /--><!-- wp:a8c/template {"templateId":42,"align":"full"} /-->
```

So the parsed blocks are the 3 expected ones:

```
 Array
(
    [0] => Array
        (
            [blockName] => a8c/template
            [attrs] => Array
                (
                    [templateId] => 41
                    [align] => "full"
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 
            [innerContent] => Array
                (
                )

        )

    [1] => Array
        (
            [blockName] => a8c/post-content
            [attrs] => Array
                (
                    [align] => "full"
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 
            [innerContent] => Array
                (
                )

        )

    [2] => Array
        (
            [blockName] => a8c/template
            [attrs] => Array
                (
                    [templateId] => 42
                    [align] => "full"
                )

            [innerBlocks] => Array
                (
                )

            [innerHTML] => 
            [innerContent] => Array
                (
                )

        )

)
```

**Comment by mmtr** [comment]
Alright, finally managed to see the template parts applied on the published view after assigning the `header`/`footer` template part types:

<img width="882" alt="Screen Shot 2019-07-03 at 14 29 43" src="https://user-images.githubusercontent.com/1233880/60565618-438a2a80-9d9f-11e9-88da-6d4ea699b5e7.png">

That step needs to be done manually until the FSE data is not inserted automatically in WP.com (https://github.com/Automattic/wp-calypso/issues/33515).

Note that the post content block needs to have set the `align` attribute to either `full` or `wide` due to a current bug when merging the post with the template (https://github.com/Automattic/wp-calypso/issues/34431):

<img width="602" alt="Screen Shot 2019-07-03 at 14 34 31" src="https://user-images.githubusercontent.com/1233880/60565745-b4c9dd80-9d9f-11e9-960f-6c4fd503022d.png">

**Comment by gwwar** [comment]
@mmtr feel free to update the summary with what's left, for example if we need more accurate manual population steps ✅or specific bugs to tackle.

**Comment by gwwar** [comment]
I don't think what's left here in the issue requires any next steps. We'll sort this out with other implementation PRs, or open new issues if we discover related work.
