### ISSUE TITLE
Couldn't inline an image inside Gutenberg on WP.com

### ISSUE THREAD

**Issue by elazzabi** [Automattic/wp-calypso#34313]
#### Steps to reproduce
1. From Calypso, edit a draft
2. Try to inline an image
3. It fails randomly

#### What I expected

Image to be inlined

#### What happened instead

Nothing happened, and the following error was logged in the console: `Uncaught TypeError: Cannot read property 'replace' of undefined`

#### Browser / OS version

MacOS with Chrome 75

#### Screenshot / Video

![Kapture 2019-06-26 at 19 09 04](https://user-images.githubusercontent.com/12542046/60205373-ee06c880-9848-11e9-9d3a-e2879b260a59.gif)

**This works** inside `wp-admin`

Thank you!

**Comment by noahtallen** [comment]
That's definitely weird! I just tried to reproduce this, but it seemed to work for me. Could you test this again? We recently updated Gutenberg on wpcom, so that may have resolved it.

**Comment by elazzabi** [comment]
Hmm looks like it's working now. Thank you! 🙏
