### ISSUE TITLE
Contact Info block: allow adding Form Blocks within the Contact Info block

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#34324]
#### Steps to reproduce
1. Add a Contact Info block
2. Click in the first empty block below the Contact Info block
3. Try adding a Form block

#### What I expected
I would like for a Form block to be available.

#### What happened instead
- The block is within the existing Contact Info block and thus I can't add a Form block.
- Pressing Enter results in more paragraph blocks directly within the Contact Info block.
- Dragging it out of the Contact Info block results in another empty block.

#### Browser / OS version
Chrome 75, macOS 10.14.5

#### Screenshot / Video
![Screen Capture on 2019-06-26 at 15-00-53](https://user-images.githubusercontent.com/32492176/60218230-93a74100-9823-11e9-9102-d5974660aed0.gif)

**Comment by tbradsha** [comment]
This remains an issue. There is always a stray Paragraph block added to the end of the Contact Info block:

![image](https://user-images.githubusercontent.com/32492176/80967344-72b06480-8dd3-11ea-8fc5-898b5144b6c1.png)

**Comment by davipontesblog** [comment]
@apeatling since you've been working on the Jetpack blocks recently, could you help us check if this is a non-issue on the new design version of this block that is being worked on?

**Comment by tbradsha** [comment]
Confirmed that this remains an issue on macOS 11.2.1 + Chrome 88 + Gutenberg 10.0.2.

**Comment by tbradsha** [comment]
Confirmed this is still an issue in macOS 11.4 + Chrome 92.0.4515.159 + Gutenberg 11.3.0

**Comment by jeherve** [comment]
I'm afraid we will not be able to add additional, non contact-info related blocks to the Contact Info Block. This could break the contact info container structured data, and thus stop Google and other search engines from being able to easily parse the block and extract data from it.

This is why the type of block you can add to the existing block is limited.

I hope this clarifies things a bit.

**Comment by tbradsha** [comment]
It looks like the original issue was renamed; the actual issue is that there's a permanent empty paragraph block within the Contact Info block. The Form block not being able to be added was more of an example/side-issue (which, fair enough, doesn't need to be added).

**Comment by jeherve** [comment]
> the actual issue is that there's a permanent empty paragraph block within the Contact Info block. 

I wasn't able to reproduce this on my end. Do you still experience this issue?

**Comment by tbradsha** [comment]
> I wasn't able to reproduce this on my end. Do you still experience this issue?

No, I can no longer reproduce it, so it seems to have been fixed at some point. 😆 I'll close it anew.
