### ISSUE TITLE
Jetpack Onboarding: Move "site owner" Q to beginning of flow. Build logic to "skip all"

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#34329]
tbd. Currently the "Are you building this site for yourself or someone else?" site ownership question is towards the tail-end of the onboarding flow for Jetpack.

If we move this question to the beginning (in front of site vertical), we can offer an option to allow the more experienced folks like builders to skip the lengthy onboarding flow

**Comment by simison** [comment]
We've decided to hide these steps from the Jetpack flow for now (paObgF-k1-p2)
