### ISSUE TITLE
Jetpack Onboarding: Change site vertical verbiage

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#34328]
**Current**

<img width="777" alt="Screen Shot 2019-06-26 at 8 56 52 PM" src="https://user-images.githubusercontent.com/214813/60225465-f9f88780-9854-11e9-8837-d8ed2678b8b1.png">

**Title:** "What are we building today?"
**Sub-title:** Choose the best starting point for your site. You can add or change features later.

At some point our title and sub title changed to match WordPress.com onboarding, but this verbiage is out of context for Jetpack customers. We're not helping them build anything, just enhance their current site, which may be old or new.

Also, the sub-title future-tense under each option represent actions that don't apply to Jetpack either, since we're not going to help them create these things with Jetpack.  example: "Online Store - Sell your collection of products online."

**Proposed:**

**Title:** "What type of site is Jetpack enhancing?"
**Sub-title:** "We'll use this info to your Jetpack experience."

**Option sub titles** - remove. If a customer already has a blog, business site, portfolio, etc. We don't need to explain to them what they already have.  #subtraction

<img width="633" alt="Screen Shot 2019-06-26 at 9 13 33 PM" src="https://user-images.githubusercontent.com/214813/60226016-62e0ff00-9857-11e9-947c-140176bf651b.png">

@Automattic/jetpack-design What are your thoughts on this, since you all are wrapping up a copy sprint?

cc @simison @fditrapani @shaunandrews

**Comment by scottsweb** [comment]
Really pleased to see this being looked at. It felt quite jarring to be connecting an established site to Jetpack. For the first title, how about:

> What type of site are you connecting to Jetpack?

or possibly:

> What type of site do you have?

I am leaning towards the first as we don't currently do a very good job at explaining why or what Jetpack is connecting to and for what reason. It may also read better as:

> What type of site are you connecting to the WordPress.com cloud? 

or

> What type of site are you connecting to the Jetpack cloud?

Whatever we come up with, I would like it to be consistent naming. I think the connection should be considered its own thing. When we explain it as a cloud I think we inherit quite a bit context. It makes sense that the CDN, backups etc are part of our cloud.

The secondary line is good:

> We'll use this to customise your Jetpack experience

**Comment by simison** [comment]
Earlier internal convo p1HpG7-70w-p2#comment-32316

**Comment by MichaelArestad** [comment]
This is a great simplification! The other thing that bugs me is that the skip link is in the spot that "continue" buttons usually live. I wonder if it would be better as just option 5?

**Comment by simison** [comment]
While at it, I'd like to update copy for these two steps as well:

<img width="750" alt="Screenshot 2019-07-02 at 11 36 47" src="https://user-images.githubusercontent.com/87168/60516844-3578d300-9ce7-11e9-9cc7-e1ae3118fd69.png">
<img width="767" alt="Screenshot 2019-07-02 at 11 36 44" src="https://user-images.githubusercontent.com/87168/60516846-3578d300-9ce7-11e9-8541-4bc04a11d9d5.png">

Alternatively can also look at hiding them, but that might be more complicated than just copy change.

**Comment by simison** [comment]
We've decided to hide these steps for now (paObgF-k1-p2)

**Comment by jeffgolenski** [comment]
@simison I know you all are doing a lot of heavy lifting on g-blocks, but is there anyway we can expedite this quick change?
