### ISSUE TITLE
Full Site Editing: Post content block is removable [5]

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#34331]
When editing a full site page, we should make the post content block unremovable in order to avoid having pages without, well, content 😄.

Apart from losing the content, if a user remove the `a8c/post-content` block will result in an editor with the post title missing, given that since https://github.com/Automattic/wp-calypso/pull/34296 we're rendering the post title as part of the post content block when editing a full site page (and adding a `show-post-title-before-content` class to the `body` element that would keep the regular editor post title hidden).

**Comment by kwight** [comment]
I guess we'd need to add some UI explaining this to the user also.
