### ISSUE TITLE
Signup: no option to log in with existing username for non-EN users

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3433]
## URL:
https://wordpress.com/start/upgrade/user

## Issue Description
During signup process, if a user enters an already existing username, the English version shows this error message: 
`Sorry, that username already exists! If this is you log in now.`

For non-English, a partial error message is shown: only the translated version of `Sorry, that username already exists!` (no option to log in for existing users).

Confirmed the issue in DE, FR, ID, NL, RU locales. Likely a global issue for all non-EN locales.

## Browser / OS version
Google Chrome 48.0.2564.109 (64-bit)
OS X El Capitan 10.11.3

## Screenshots
_English_
![en_desktop_4b_account_validation_invalid_screenshot1453773513950](https://cloud.githubusercontent.com/assets/7637835/13197026/8888baea-d7e9-11e5-972a-df78f05d4e6b.png)

_French_
![fr_desktop_4b_account_validation_invalid_screenshot1453773931548](https://cloud.githubusercontent.com/assets/7637835/13197032/ab6b15a8-d7e9-11e5-8491-6119c6298912.png)

**Comment by lancewillett** [comment]
Confirmed this is still broken, testing the signup flow in Spanish:

![screen shot 2016-05-03 at 1 45 20 pm](https://cloud.githubusercontent.com/assets/66797/14997783/519973f0-1135-11e6-8e5a-2eb40dcf8b39.png)

Missing the <log in now> link and text.

**Comment by lancewillett** [comment]
The translated text is saved correctly in GlotPress: https://translate.wordpress.com/projects/wpcom/es/default/?filters%5Bterm%5D=If+this+is+you&filters%5Buser_login%5D=&filters%5Bstatus%5D=either&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

![screen shot 2016-05-03 at 1 48 33 pm](https://cloud.githubusercontent.com/assets/66797/14997881/c71e4f42-1135-11e6-8eab-8c7222ba6bcd.png)

**Comment by lancewillett** [comment]
Code ref: https://github.com/Automattic/wp-calypso/blob/9cb2557484fc059ab3af01be5de03e913770abf1/client/components/signup-form/index.jsx#L293 — looks properly coded with the translate call.

**Comment by bisko** [comment]
This requires an API change, tracked on D1793-code. It should work automagically after the fix is released.

**Comment by bisko** [comment]
The change is live and the issue should not be occurring anymore. @lancewillett Can you verify that?

**Comment by lancewillett** [comment]
Confirmed worked as expected! Nice.

![screen shot 2016-05-13 at 10 13 34 am](https://cloud.githubusercontent.com/assets/66797/15255872/61866dc0-18f3-11e6-8dad-d2be975789af.png)
