### ISSUE TITLE
Full Site Editing: investigate integration points with existing onboarding flows [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34347]
This should be a time-boxed investigation aimed to uncover any blockers or major areas of work needed in order to include FSE into existing onboarding flows.

Some areas of interest might be: 
- [ ] modifying existing Headstart scripts to pre-populate FSE data on sites
- [ ] how do we handle existing sites that might be eligible for FSE (they will not go through creation process above)
- [ ] how can we integrate our default header and footer layouts into site previews that users see during onboarding?

Feel free to add more items to the list if I've missed anything.

**Comment by gwwar** [comment]
As we investigate and find more detail, let's make new issues if needed and convert this to a tracking epic. (add an epic label instead of a task)

**Comment by gwwar** [comment]
Closing this out
