### ISSUE TITLE
Full Site Editing: improve content slot block interactions [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34344]
When editing a page that shows the header and footer template parts in the same view, we need to click twice on post content slot in order to start editing some of its inner blocks.

Let's try to improve this in order to avoid the need for an extra click.

**Comment by mmtr** [comment]
This PR might be relevant to understand how the `click-through` approach (first click to select parent, second one to select a child) has been implemented in Gutenberg:

https://github.com/WordPress/gutenberg/pull/15537

**Comment by kwight** [comment]
With WordPress/gutenberg#15537 merged, does that mean this can be closed?

**Comment by mmtr** [comment]
> With [WordPress/gutenberg#15537](https://github.com/WordPress/gutenberg/pull/15537) merged, does that mean this can be closed?

No no, I just referenced it because that's where the two clicks to edit a nested block was implemented, so it might give us a clue on how to disable that behavior.

**Comment by noahtallen** [comment]
It looks like they may be reverting it: https://github.com/WordPress/gutenberg/pull/16888

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.
