### ISSUE TITLE
Domains: localize address format for non-EN locales

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3434]
Address display used for domain registration is EN-specific: Address, City, State, Postal code. This order does not apply to all the locales. For example, in Japanese, the order of address should go from larger to smaller: zip code, prefecture, city, street address. Different order is also used e.g. in Russian.

To do: investigate different options to display an address form in a locale-specific way.

Signup screenshot:
![en_desktop_5a_domain_reg_screenshot1453773528077](https://cloud.githubusercontent.com/assets/7637835/13197128/dc706a06-d7ec-11e5-9dc1-dce8d0a9e5bc.png)

**Comment by klimeryk** [comment]
This would make for an interesting A/B test... but it seems we're only able run those for en-only users. So closing this for now - it'd be great to revisit it if/when we redesign the form (it's in dire need of that).
