### ISSUE TITLE
Full Site Editing: investigate styling issues with template parts and site blocks [?]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34345]
Currently, the default theme styling is not applied as we'd expect to header and its blocks and it diverges from default Twenty Nineteen look.

Let's maybe timebox an investigation to figure out why this is happening, and propose a way forward, taking into account the fact that we'll have multiple child themes (business vertical themes) that will style these template parts in different ways.

/cc @kwight if you can add any more details

**Comment by mmtr** [comment]
Is this a duplicate of https://github.com/Automattic/wp-calypso/issues/34279?

**Comment by vindl** [comment]
> Is this a duplicate of #34279?

Yes, I haven't caught that one because it wasn't in the backlog column. Let's continue the work there.
