### ISSUE TITLE
Stats Chart Tabs: "Post Published" Gradient

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#34365]
#### Steps to reproduce
1. Starting at URL: /stats/day in the Nightfall scheme 
2. Hover over a stat bar

Note the blue at the end of the post title, I expected that fade to match the other colours better.

<img width="250" alt="Screenshot 2019-06-29 at 08 02 59" src="https://user-images.githubusercontent.com/43215253/60380889-78674c00-9a44-11e9-930c-6188fa2dec3e.png">

**Comment by lancewillett** [comment]
Thanks for the report, @Aurorum .

Also, big thanks for all your recent contributions to WordPress.com via the Calypso project. You're awesome! ⭐️ 

If you ever want to come over to the team and do this kind of work full-time, we'd love to have you — https://automattic.com/work-with-us/.
