### ISSUE TITLE
Fix the hash string shown in checkout cart for Concierge sessions

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#34375]
#### Steps to reproduce
1. While logged in, proceed to URL: /checkout/SITE_SLUG/offer-quickstart-session
2. Add the quickstart session to cart
3. The Order Summary shows a hashed string value

#### What I expected

To not show weird hash values, but human readable product name and other relevant details.

#### What happened instead

Seeing hashed string value.

#### Screenshot / Video

<img width="480" alt="螢幕快照 2019-06-27 上午10 30 43" src="https://user-images.githubusercontent.com/1842898/60243859-bbfa7280-98eb-11e9-9602-b84255008281.png">

Props to @southp for reporting in #33996

**Comment by davipontesblog** [comment]
Closing as this is no longer offered.
