### ISSUE TITLE
Reader: improve follow new site UI

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#3437]
I just ran a new user through the follow site UX under "Manage" in the reader. They found it really confusing.

I think there is a disconnect between typing in a site URL and the card below showing the details. They are not sure where to hit follow. The icon to the left in the follow URL box looks like a button to them.

Also it's not clear that the site has appeared below, after it has been followed. I had to explain to them that it was now in that list and was followed. They didn't really know what do do next. I think there needs to be a message here with a bit of guidance. Maybe even a link to the followed sites stream.

As an aside, they expected to be able to see the posts for the site just followed, and didn't immediately grasp that the posts for the site would show up in the stream with everything else. There was also confusion that "discover" was being followed automatically, when it also appears in the sidebar -- I don't see any good reason to duplicate the content in both for new users.

**Comment by jancavan** [comment]
I've posted first iteration mockups for an overhaul of Manage Following UI on our P2.

In the mean time, we're working on the addition of the OPML import/export feature and some of those changes will improve the current UI: https://github.com/Automattic/wp-calypso/pull/3878#issuecomment-194991987

**Comment by samouri** [comment]
I'm not sure what the UI looked like at the time this issue was made.

Its went through a couple iterations and is going through another one right now here: https://github.com/Automattic/wp-calypso/issues/11549

Is this closeable?
@fraying

**Comment by fraying** [comment]
Ayup
