### ISSUE TITLE
FSE: Update Header and Footer styles in Edit and Publish view to match Modern Business 

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#34387]
While most of our targeted themes are similar, let's try matching styles in modern Business first. Screenshots of the editor vs publish view should match closely and not have major differences.

To create a site with Modern Business:
- Visit WordPress.com/start/onboarding
- Pick any segment besides blog
- For your vertical type pick a business keyword
- Name your site and select "modern" as the style
- If all went well, the themes tab should display "Modern Business" as active

<img width="369" alt="Screen Shot 2019-07-09 at 11 15 54 AM" src="https://user-images.githubusercontent.com/1270189/60912744-f42e7900-a23a-11e9-8079-f642db0de754.png">

It's possible to run these themes locally as well.

In the published view  the header content is formatted as below:
<img width="537" alt="Screen Shot 2019-06-25 at 10 54 39" src="https://user-images.githubusercontent.com/1233880/60063360-a6dce280-9737-11e9-81aa-d1ec9fc56f37.png">
 
But when editing the Header template part, both blocks are on independent lines with the separating dash missing:

<img width="1065" alt="Screen Shot 2019-06-25 at 10 57 43" src="https://user-images.githubusercontent.com/1233880/60063509-22d72a80-9738-11e9-80a4-49c033b33e05.png">

**Comment by glendaviesnz** [comment]
In order to better match the two views we would need to change the way the blocks are rendered in the template parts edit. There is some related work being done in #34146 which may be relevant.

#34279 should probably be handled first to find a solution for adding in the relevant css from the themes.

**Comment by mmtr** [comment]
I think the most complicated problem to solve here is the fact that each block is in a new line. 

Given that we cannot have _inline blocks_ in Gutenberg, the only workaround I can think of in order to match the edit view with the published view as much as possible is to use a column block that wraps both blocks (site and description), so the site block is placed in the left column and the description one will be on the right column.

**Comment by apeatling** [comment]
This needs to be a combination of the right blocks, and editor styles. It can't be done with CSS alone.

**Comment by apeatling** [comment]
I'm going to see what I can do to help here in terms of accurately reproducing one of our Business theme child theme headers.

**Comment by apeatling** [comment]
Can we close this in favor of https://github.com/Automattic/wp-calypso/issues/34279?

**Comment by apeatling** [comment]
I managed to get this working for modern business in my sandbox:

<img width="1293" alt="Screen Shot 2019-07-09 at 3 05 34 PM" src="https://user-images.githubusercontent.com/1464705/60926327-03bdba00-a25b-11e9-80bb-c145858d9d99.png">

There is a branch here: https://github.com/Automattic/themes/compare/add/modern-business-fse-header-support

that adds the styles necessary to support displaying the header correctly in both the editor, and on the front end. Before this will work and can be turned into a PR, the new header content will need to be deployed to the plugin in https://github.com/Automattic/wp-calypso/issues/34279

**Comment by apeatling** [comment]
This will only support the modern business theme right now. I think we will need to have multiple block templates that support single or dual column headers, that are set depending on the theme that is activated.

**Comment by apeatling** [comment]
All business themes have now been updated to support FSE header styles in the editor.

**Comment by apeatling** [comment]
I'm going to close this and open a separate issue for footers.

These issues will also address the need to support different block templates in order to satisfy the default header content needs for the business themes:

https://github.com/Automattic/wp-calypso/issues/34560
https://github.com/Automattic/wp-calypso/issues/34610
