### ISSUE TITLE
Checklist: Tooltip and referenced button name don't match

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#34383]
<img width="612" alt="Screen Shot 2019-07-01 at 11 31 23 AM" src="https://user-images.githubusercontent.com/2124984/60457364-d6915c00-9c09-11e9-827f-6bd51683997e.png">

When you go to change your site icon from the checklist, the name of the button says **Modifier** when the tooltip refers to it as **Changer**.

My settings are Canadian French in the above screenshot; I don't know if this occurs for all languages or if it's a translation lag/discrepancy but we should look into it and find the cause.

**Comment by sixhours** [comment]
This appears to be a translation issue. We have two different strings -- one for the button itself, and one for the reference to it in the Guided Tour. These strings are found here:

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/site-icon-setting/index.jsx#L302

and here: 

https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/button-labels.jsx#L29

In the above example (Canadian French), the first uses this translation:

https://translate.wordpress.com/projects/wpcom/fr-ca/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=222476&filters%5Btranslation_id%5D=6970413

The second uses this translation:

https://translate.wordpress.com/projects/wpcom/fr-ca/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=880&filters%5Btranslation_id%5D=979956

In GlotPress, they've been translated separately with interchangeable verbs, because one string has included context and one has not. Translators can't know they're meant to have the same verbiage because they're not connected in any other way that's notable.

I think the solution here is to add context to the guided tour button label so both strings use the same translation from GlotPress, but I'm not certain. Pinging i18n for guidance.

**Comment by deBhal** [comment]
> I think the solution here is to add context to the guided tour button label so both strings use the same translation from GlotPress, but I'm not certain. Pinging i18n for guidance.

Exactly right.

If I create https://github.com/Automattic/wp-calypso/pull/34455 do you want to confirm/review/merge the fix?

**Comment by sixhours** [comment]
This was fixed in #34455
