### ISSUE TITLE
Signup: RTL locales "< BACK" arrow direction

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3438]
## Issue description
For RTL locales, there "BACK" text with an arrow pointing in a certain direction is displayed inconsistently, in some cases pointing in the wrong direction. 

## Hebrew screenshots
![he_desktop_2a_domain_new_wrong arrow direction](https://cloud.githubusercontent.com/assets/7637835/13201941/60b791c0-d88f-11e5-98d3-6d052d231e51.png)
![he_desktop_2b_domain_map- wrong arrow direction](https://cloud.githubusercontent.com/assets/7637835/13201943/60fc9b9e-d88f-11e5-95c8-a2bdf09d4603.png)
![he_desktop_3a_plan_comparison_wrong arrow direction](https://cloud.githubusercontent.com/assets/7637835/13201942/60eb055a-d88f-11e5-8b4c-39cf2f26a0a5.png)

@yoavf maybe you would like to take a look?

**Comment by yoavf** [comment]
@jenial pretty sure I've fixed that with #2978 - are those screenshots recent?

**Comment by jenial** [comment]
@yoavf: you are right, the screenshots are out of date -- I should have checked, sorry.
