### ISSUE TITLE
Jetpack plans: highlight "site monetization" when feature=simple-payments

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#34399]
"Site monetization" section doesn't get highlighted when entering plans page with URL:

`https://wordpress.com/plans/SITE?feature=simple-payments&plan=jetpack_premium`

<img width="349" alt="Screenshot 2019-07-02 at 12 54 44" src="https://user-images.githubusercontent.com/87168/60503534-9e048780-9cc8-11e9-9235-e915bcfffa77.png">

It currently gets highlighted only with `feature=wordads-instant`:

<img width="352" alt="Screenshot 2019-07-02 at 12 54 29" src="https://user-images.githubusercontent.com/87168/60503531-9ba22d80-9cc8-11e9-8252-22888bb00186.png">

For premium block flows from the block editor, we'll need to make the row highlight also for simple-payments.

Found while testing https://github.com/Automattic/jetpack/pull/12823

**Comment by ockham** [comment]
There's a chance that these visual feature rows map 1:1 to `feature` strings (meaning we maybe can't have `feature=simple-payments` highlight 'Site Monetization', but have to add a row of their own).

FWIW, 'Simple Payments' are present for WP.com plans (under that name). The plans grid generally works kinda differently there, features are listed even if they're included in the next lower tier plan -- probably for ease of comparison. E.g. with `feature=simple-payments`, the entire row listing the 'Simple Payments' feature across different plans is highlighted.

Another instance of subtly different UI and strongly different underlying paradigms.

**Comment by simison** [comment]
Ohh right. I'm pre-lunch and just didn't realise I shouldn't be concentrating on Jetpack aspect of this flow. :-) This obviously needs to work only for .com sites for our purposes and it does:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/87168/60506592-d0b17e80-9cce-11e9-8256-ad204843c02b.png">

I'll just close for now since this will just come up again when ever these flows are considered for Jetpack.
