### ISSUE TITLE
SignUp: Resuming a flow with progress jumps between first step and progressed step

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#34397]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/start
2. Progress through the flow a few steps, in my example I progress to `/plans/`
3. Open a new tab and enter http://calypso.localhost:3000/start
4. You should first see the `/site-type/` step (First step in thee flow, currently), then after a short time, you'll jump to `/plans/`

#### What I expected
I should be taken to the same place as I left off... Though there has been talk of ditching this resuming functionality completely.

#### What happened instead
We land at `http://calypso.localhost:3000/start`. 
Then our controller navigates to the first step in the flow, taking us to `http://calypso.localhost:3000/start/site-type`.
Then after a few moments our controller figures out where we left off and navigates to that step, in the example case: `http://calypso.localhost:3000/start/plans`

In my opinion, this is quite jarring... The customer may start trying to interact with the first step and be taken aback by the unexpected jump to another step.
We should be resolving/reconciling the target step in one go, rather than in different, disconnected places.
Or, get rid of the saved progress functionality altogether, until we can address it properly and make it a positive experience, rather than a negative one.

#### Screenshot / Video
Here, Calypso is just starting to load after I went directly to `/start/`
<img width="1293" alt="Screenshot 2019-07-02 at 13 23 53" src="https://user-images.githubusercontent.com/4335450/60484599-cee6bb80-9ccc-11e9-9346-749a43c6b9cb.png">
Then, before content renders, we're navigated to the first step - `start/site-type`
<img width="1293" alt="Screenshot 2019-07-02 at 13 24 14" src="https://user-images.githubusercontent.com/4335450/60484605-d0b07f00-9ccc-11e9-9c90-13402aa6bf86.png">
As that step renders in, we see the URL update once more to `start/plans`
<img width="1293" alt="Screenshot 2019-07-02 at 13 24 27" src="https://user-images.githubusercontent.com/4335450/60484604-d017e880-9ccc-11e9-9548-343647acd097.png">
Finally the plans step renders
<img width="1293" alt="Screenshot 2019-07-02 at 13 24 34" src="https://user-images.githubusercontent.com/4335450/60484602-cf7f5200-9ccc-11e9-98c7-a6aac43d3f92.png">

**Comment by adamziel** [comment]
I moved it closer to the bottom of Up next - while it's not perfect, it doesn't seem like a top priority either.

CC @p-jackson: it seems related to your work on resumeProgress

**Comment by p-jackson** [comment]
Yep, this was fixed by #34949.

Tested and the behaviour is what I expected: the second tab won't jump forward at all, it proceeds forward one step. It *will* have the dependencies pre-filled, so it remembers the site title/style/subject from the first tab. I think this is fine.

**Comment by p-jackson** [comment]
fyi @spen @adamziel
