### ISSUE TITLE
Signup: translated text truncated on mobile

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3439]
## URL
https://wordpress.com/start/domains/

## Issue description
Russian text gets translated on a mobile screen. The "Billed yearly — get 2 months free!" ("При ежегодной оплате два месяца бесплатно!") text is truncated on both sides.

This issue happens on mobile (iOS).

## Russian screenshot
![ru_mobile_2a_domain_new_screenshot1453779258867](https://cloud.githubusercontent.com/assets/7637835/13202099/5e0127e6-d896-11e5-92c8-e4b0a894b974.png)

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Closing, appears to be fixed.  Please re-open if it's still an issue elsewhere.  Seen here on an iPhone 5 simulator:

![screen shot 2016-05-12 at 11 09 10 am](https://cloud.githubusercontent.com/assets/7233112/15219567/43f832b4-1832-11e6-8e84-500fe06c0b27.png)
