### ISSUE TITLE
Improve back button and progress wording during sign up

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#34390]
***This issue continues discussion raised in https://github.com/Automattic/wp-calypso/issues/34299***

> We have a back button, that replicates the browser back, to reassure people that nothing is going to blow up if they press our back button.

Agreed with @fditrapani here.

--

> Based on this definition, we might choose to update the Back button's label:

Regardless of the behavior of the back button, I really like the idea of improving the label. @ramonjd's suggestion of "Back to {{step title here}}" might be a little too verbose. We could take a cue from iOS and just shorten the label to "{{step title here}", like this:

<img width="160" alt="image" src="https://user-images.githubusercontent.com/191598/60445848-0df20f80-9bee-11e9-9ca5-399c7942039d.png">

This could get tricky on smaller screens, where our horizontal space is limited. We could remove the label and/or adjust the layout to make room.
--

Another option is to remove the back button and list the steps available:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/191598/60445593-80aebb00-9bed-11e9-91c8-224c70545970.png">

I like this option, as its more clear what's happening. But, if steps change, we'll need to do something to accommodate. That is, can we accurately list the future steps without knowing the answer to the current question?

This also presents some challenges on mobile. We could get creative and show the list in some sort of dropdown, or revert to a more standard back button.

_Originally posted by @shaunandrews in https://github.com/Automattic/wp-calypso/issues/34299#issuecomment-507298963_

**Comment by andrewserong** [comment]
The tasks out of this issue are:

## Short term

* [ ] Update the back button text to: "{{step title here}}", and carefully test the length of the step titles on mobile.

## Long term
* [ ] Explore the idea of listing the steps available instead of the back button, like in the design above ☝️ — this can be discussed here, but might need to be split out into separate issues if we reach consensus on the approach.

**Comment by ramonjd** [comment]
Did an experiment for the short term work

https://github.com/Automattic/wp-calypso/pull/35082

Might need shorter titles....

**Comment by ramonjd** [comment]
https://github.com/Automattic/wp-calypso/issues/34598

**Comment by ramonjd** [comment]
Related issue: https://github.com/Automattic/zelda-private/issues/121
