### ISSUE TITLE
Editor: contact form flow is missing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#344]
It has come up multiple times from happiness engineers that contact forms is a big missing piece when it comes to site setup.

Prior work exists in the `editor-contact-form` repo.

Any chance we can pick this up again and get it into the Calypso Editor sooner rather than later?

From kriskarkoski

> The contact form is under development again by @rodrigoi

**Comment by ianstewart** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/4683
