### ISSUE TITLE
Simple Payments: Ability to convert Simple Product to WooCommerce Product

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#34406]
The idea here is to foster better integration among our product offers in calypso. Users can currently create simple payment products, and in the future might need to "upgrade" their online presence to a WooCommerce store. In this scenario, there is no easy way to migrate their simple payment products to WooCommerce products - they need to re-create Woo products from scratch. This would create frustration and could be a deterrent to upgrading to Woo from Simple Payments.

We want to allow users to more easily upgrade from Simple Payments to Woo, and this would be a critical step to allow for that to happen.

#### Idea and steps envisioned here
1. Ideally, simple payment products would have a "home" in calypso, either under My Site > Store > Simple Payments, or Tools > Earn > Simple Payments. Going there we would see a list of all products created so far;
2. There would be a button to click and convert products into WooCommerce products;
3. If Woo is installed on the site, calypso takes the user to step 4; if not, the user is given a message to install WooCommerce first, with guidance on how to do so (Probably a good way to introduce Woo to users as well);
4. User is prompted to select all products or pick from a list of current simple products on the site;
5. Products are converted into Woo products.

#### What I expect from this enhancement
- Greater success for users who convert from Simple Payments to Woo
- Less frustration for users who need to convert

#### Context / Source
#journey #empathy #perspective #painpoint.

**Comment by DavidRothstein** [comment]
Tracking internally here: pNPgK-4Nw-2

It sounds like a good idea!  But maybe a big project (not sure).

Since it's more than just a front-end change, I don't think it makes sense to keep this issue open in the Calypso project separately, though, so I'm closing this issue for now.
