### ISSUE TITLE
Checklist: Half of checklist already done immediately after creating site

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#34402]
#### Steps to reproduce
1. Starting logged out at URL: https://wordpress.com/
2. Select "Get started" to start the signup flow.
3. Follow the steps to complete signup and create a site.
4. Complete signup and land on the site checklist.

#### What I expected

I expected to a see a checklist with items to complete.
 
#### What happened instead

Two of the four items were already marked as completed:

![calypso-checklist-postsignup](https://user-images.githubusercontent.com/8658164/60507827-b75e0180-9cd1-11e9-8b21-ebb08e8f5ec1.png)

#### Browser / OS version

Chrome 75.0.3770.100 / macOS 10.14.5

#### Context / Source
#manual-testing

cc @Automattic/start-dev

**Comment by shaunandrews** [comment]
Is there a draft post, too?

**Comment by michaeldcain** [comment]
@Automattic/zelda @adamziel: I just ran into this while doing an onboarding demo. Since the editor task is so important, this should be prioritized immediately.

**Comment by spen** [comment]
Here's the response from `fetchChecklist` (`/sites/${ action.siteId }/checklist`), so it's definitely a server-side issue...

<img width="320" alt="Screenshot 2019-07-02 at 22 38 23" src="https://user-images.githubusercontent.com/4335450/60521609-219a9480-9d1a-11e9-8149-0bd0c481178e.png">

**Comment by jblz** [comment]
Debugging & discussion of server-side changes happening at D30045-code

**Comment by jblz** [comment]
D30050-code & D30053-code fixed up the "You updated your homepage" item.

The "Launch your site" item is going to take some discussion.
See: p1562082809355800-slack-CCS1W9QVA

**Comment by jblz** [comment]
Marking as fixed. Thanks very much for the report, @rachelmcr!

See discussion linked above about site launch & p1562088094369500-slack-CCS1W9QVA re: marking as fixed.
