### ISSUE TITLE
FSE: Header and Footer template_parts CPTs should render header and footer tags [2]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34423]
Current header and footer template_parts should render their respective semantic containers of `<header>` and `<footer>` in the published page view.

<img width="1174" alt="Screen Shot 2019-07-02 at 3 43 53 PM" src="https://user-images.githubusercontent.com/1270189/60551465-33f7dc80-9ce0-11e9-9b0e-6906a38e3922.png">

Example FSE Markup (Note the missing header tag)
<img width="1048" alt="plugin-published" src="https://user-images.githubusercontent.com/1270189/60551535-6bff1f80-9ce0-11e9-899b-03d52d6587bf.png">

Example Vanilla TwentyNineteen
<img width="1072" alt="vanilla-published" src="https://user-images.githubusercontent.com/1270189/60551525-61448a80-9ce0-11e9-8275-9a9c6666e02e.png">

**Comment by mmtr** [comment]
Probably we should add the missing header in our page FSE template ([#](https://github.com/Automattic/wp-calypso/blob/85fc28d75538f1a973f04158187272b32e523464/apps/full-site-editing/full-site-editing-plugin/full-site-editing/page-fse.php#L23)) or when getting the header content from the template part ([#](https://github.com/Automattic/wp-calypso/blob/85fc28d75538f1a973f04158187272b32e523464/apps/full-site-editing/full-site-editing-plugin/full-site-editing/utils/class-a8c-wp-template-data-inserter.php#L73-L78)).

I guess the footer could be fixed similarly.

**Comment by kwight** [comment]
> Probably we should add the missing header in our page FSE template

This is my strong preference 👍

**Comment by glendaviesnz** [comment]
The fix for this should probably also include the`<div class="site-info">` wrapper in the footer, as this is responsible for some of the footer styling which currently isn't applied in the FSE footer so it renders different to the default 2019 theme in the page view.

**Comment by glendaviesnz** [comment]
I think this is going to be superseded by https://github.com/Automattic/wp-calypso/pull/34640, so check progress on that before proceeding with this work

**Comment by gwwar** [comment]
This issue is mainly a reminder to use semantic markup in the final page output for the header/footer. Feel free to close out as soon as we have examples of this in our new themes.
