### ISSUE TITLE
FSE: Trashed templates are applied to pages

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#34424]
It seems that we are not stripping out the trashed templates when getting the global template to be applied to pages without a specific template.

#### Steps to reproduce
1. Go to Templates (`/wp-admin/edit.php?post_type=wp_template`)
2. Select and move all of them to trash.
3. Go to Pages > Add new (`/wp-admin/post-new.php?post_type=page`)
4. Select any starter template.

#### What I expected

To see the editor without any template applied:

![image](https://user-images.githubusercontent.com/1233880/60555148-402e7900-9d76-11e9-8340-56340e084ce9.png)

#### What happened instead

The trashed default template has been applied:

![image](https://user-images.githubusercontent.com/1233880/60555175-6fdd8100-9d76-11e9-8957-2142611fd1b2.png)
-->

**Comment by apeatling** [comment]
The templates section will be hidden from users, but it's still possible to trash a template via Gutenberg. We need to disable this option.
