### ISSUE TITLE
Verticals in Signup: Twenty Nineteen default pages using incorrect nomenclature

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#34422]
Submitted by @jjchrisdiehl 

## Steps to replicate

1. Create a site
2. Choose Blogging when prompted "What's your site about"
3. Select 2019 theme or one of its children
4. Go to Customizer or Site > Pages

## Result

The default pages, used to showcase a static homepage and a posts page, use the titles Blog Home and Blog Feed, respectively.

WordPress core is aiming to move away from using Blog, and instead Site should be used.

If anything, could be useful to use simply Home and Blog, as these are more concise and to the point, using *Blog* leads to user confusion as is the case in this instance towards the bottom of the chat - 13764042-hc

![2019_default_pages](https://user-images.githubusercontent.com/16580129/60550410-de2e2f00-9cf5-11e9-8509-9725f08cabe1.png)

## Expected

I expected a more concise default name to be used, such as Home or Blog, rather than Blog Home and Blog Feed.

* User report: 13764042-hc
* Slack discussion p1562099434181600-slack-themes

CC @Automattic/zelda

**Comment by ramonjd** [comment]
> The page names can be changed on a8cvm2.wordpress.com and then someone from @zelda-team will need to regenerate the annotation for the blog segment

p1562099434181600-slack-themes

Thanks. I've placed this issue on our backlog.

**Comment by michaeldcain** [comment]
The front page name was updated to "Home" in D30275-code. I left the "Blog Feed" page name alone, b/c it's a strange concept for users.
