### ISSUE TITLE
FSE: Navigation menu block styles are broken if site does not have primary and footer menus

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#34429]
#### Steps to reproduce
1. Check out branch and follow instructions in https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing#build-system. Install the FSE plugin, and activate it on local gutenberg dev
2. Make sure that your site has no Primary or Footer menu defined
3. Compare the header content in the edit view and published page view with that of a standard 2019 theme site.  The navigation menus should display roughly the same, but styling is different, eg. multiple menu items will display on new lines instead of inline.
4. Add a Primary and Footer to the site and check edit and page views again - they should now be the same as a standard 2019 site.

Nav menu with no site menus defined:
<img width="598" alt="Screen Shot 2019-07-03 at 3 53 48 PM" src="https://user-images.githubusercontent.com/3629020/60562230-d54b6500-9daa-11e9-951c-c5b9a40c7204.png">

Nav menu with site menus defined:

<img width="640" alt="Screen Shot 2019-07-03 at 3 56 12 PM" src="https://user-images.githubusercontent.com/3629020/60562296-19d70080-9dab-11e9-933b-2b316a4619b2.png">

#### What is expected

Some discussion needed about this. Possibly the menu should not be rendered if the site does not have any menus defined. `wp_get_nav_menu_object( $locations[ $args->theme_location ] );` returns false if no menu for given location so this could be used to bail early if no menu defined.

**Comment by apeatling** [comment]
@glendaviesnz @vindl @gwwar I think this one is a blocker for having a working Modern Business by the end of the sprint.

**Comment by glendaviesnz** [comment]
I have a potential fix for this almost sorted, but phpcs has decided to pack a sad for me so couldn't get up a PR, should be able to sort first thing in the morning
