### ISSUE TITLE
Clicking "Enable SEO" from my-plan in wp-admin takes me to Calypso error

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#34436]
#### Steps to reproduce the issue

1. On a site with Jetpack Professional, go to /wp-admin/admin.php?page=jetpack#/my-plan
2. Click on 'Configure site SEO' under SEO Tools
3. See error "This page is only available to Jetpack sites running version 3.4 or higher with the Sharing module activated."
4. But the SEO tools are actually there on the page (though not scrolled into view)

#### What I expected
To see SEO tools (scrolled to those settings), perhaps a tour, some notification on how to enable them, or that they are enabled, etc.

#### What happened instead
Confusing error

**Screenshots**
<img width="1676" alt="enable-seo-bug" src="https://user-images.githubusercontent.com/51896/60317242-00553500-9923-11e9-9639-0143c89dc8a0.png">

**Comment by juliasydnor** [comment]
Noting this also happens with JP Premium plans. One example in 2262356-zen.
