### ISSUE TITLE
FSE: Content not saved when post content block align attribute is unset

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#34431]
#### Steps to reproduce
* Make sure you have activated the FSE plugin in your [dev environment](https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing).
* Go to Templates (`/wp-admin/edit.php?post_type=wp_template`)
* Create a new template containing a header template part, a post content block and a footer template part.
![image](https://user-images.githubusercontent.com/1233880/60566275-6584ac80-9da1-11e9-9817-569d3b9ffd6a.png)

* Make sure the post content block doesn't have any align attribute specified:
![image](https://user-images.githubusercontent.com/1233880/60566320-8fd66a00-9da1-11e9-9459-178c9518c495.png)

* Publish the template.
* Go to Pages > Add new (`/wp-admin/post-new.php?post_type=page`)
* Select any starter page template.
* On the FSE sidebar, select the new template created above:
![image](https://user-images.githubusercontent.com/1233880/60566413-cc09ca80-9da1-11e9-9e6e-d06f3e5919ad.png)

* Publish the page and reload the editor, so the new template is applied.
* Add some content, update the page and reload the editor.

#### What I expected

The new content to be in the editor.

#### What happened instead

The content is missing in the post content block.

#### Context / Source

I think this is a edge case not covered in https://github.com/Automattic/wp-calypso/pull/34318

**Comment by apeatling** [comment]
@mmtr Is this one still relevant now that these options are gone?

**Comment by mmtr** [comment]
@apeatling Yup, it is. Actually, this is now easier to reproduce with https://github.com/Automattic/themes/pull/1103 and the cause of the behavior described in https://github.com/Automattic/themes/pull/1103#pullrequestreview-264482606.

I'm preparing a PR fixing this, it should be ready in a few mins.
