### ISSUE TITLE
Signup: Plans comparison table misaligned on mobile for non-EN locales

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3443]
## URL:
https://wordpress.com/start/plans/compare

## Issue description
Plan comparison on signup is not localization-friendly. Different translation lengths, for example for NL, result in a misaligned table.

## Browser / OS version
Mobile: iOS

## Screenshots
![screen shot 2016-02-04 at 11 34 35](https://cloud.githubusercontent.com/assets/7637835/13203387/b54427be-d8bf-11e5-9820-351f9e290d28.png)

**Comment by fabianapsimoes** [comment]
This is solved in #2887, which will be merged soon. See:

![screenshot-calypso localhost 3000 2016-03-03 13-28-40](https://cloud.githubusercontent.com/assets/1248436/13494357/f85bd5b0-e143-11e5-9a87-69061bf0bc2f.png)
