### ISSUE TITLE
FSE: Add CoBlocks to Simple Sites [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34449]
Let's explore where this code will live in wpcom and outline the related update process. I think it'd be a good idea to leave a versioned folder like 1.11.0, so updates are easier to try and revert. See Gutenberg plugin structure as an example.

This can be done in parallel with the audit in https://github.com/Automattic/wp-calypso/issues/34448 but do not land any code until this is complete.

**Comment by mmtr** [comment]
We have created D30133-code that adds the latest version of the plugin to WP.com simple sites.

**Comment by kwight** [comment]
We've decided to go with a minimal implementation: rather than have the whole plugin on Simple sites and strip out/script the changes required, we'll build a WordPress.com loader that pulls in only certain blocks as needed.

**Comment by kwight** [comment]
I still like the idea of a pinned version folder, only now it won't be the full plugin, but `/src/blocks` of the plugin. Mixing versions of individual blocks could be fragile and frustrating to troubleshoot/reconcile.

**Comment by mmtr** [comment]
Closed by D30413-code
