### ISSUE TITLE
Checklist: Cannot dismiss or close the "Your site is ready to share" 

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#34452]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Complete onboarding checklist items.
3. Click "X" to dismiss the "Your site is ready to share!" banner.
4. Banner is dismissed, but returns if you reload the stats page, or navigate away and come back.

#### What I expected
Banner would be dismissed and stay dismissed.

#### What happened instead
Banner returns after every refresh, even across different devices and browsers.

#### Browser / OS version
Firefox and Chrome. Windows 8 and Windows 10.

#### Screenshot / Video
![Annotation on 2019-6-3 (1)](https://user-images.githubusercontent.com/10121835/60628965-70e3d200-9db9-11e9-9133-28a4d0e1adcb.png)
![Annotation on 2019-6-3](https://user-images.githubusercontent.com/10121835/60628967-72ad9580-9db9-11e9-91a1-8a56ef24e15f.png)

#### Context / Source

I'm able to reproduce consistently when NOT proxied (although for me, only when logging out and back in).  Banner does continuously return under certain conditions. Does it need a cookie to stay hidden? Because for users that have strict privacy settings or change computers, that means they'll be infinitely bugged by the banner.

1663051-zen
13791766-hc

**Comment by davipontesblog** [comment]
Moved to DotCom Manage for triaging.

**Comment by gwwar** [comment]
Let's remove this nudge with https://github.com/Automattic/wp-calypso/issues/38172
