### ISSUE TITLE
FSE: CoBlocks Investigate Atomic flows [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34450]
Let's investigate if we'll run into any general issues with adding CoBlocks to newly created Atomic sites. For example do we see any errors with our selected Gutenberg version or common plugin combinations?

If we find any issues let's document these in posts/issues.

**Comment by glendaviesnz** [comment]
Have done a quick check and in general CoBlocks run ok on an Atomic site if the user is an Admin or Editor. For an Author user the same KSES issues as with Simple sites causes a number of the blocks to have saving issues.
