### ISSUE TITLE
App Banner: Nudge to the mobile app doesn't show on block editor (Gutenberg)

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#34460]
#### Steps to reproduce
1. Starting on a mobile device at URL: https://wordpress.com/post
2. Select a site to start a new post. Note whether you see an app banner at the bottom of the screen.
3. Switch to the other editor. (If you started in the block editor, tap the 3-dot menu in the top right and select "Switch to Classic Editor." If you started in the classic editor, tap the Settings icon in the top menu to open the sidebar, select "Learn more" on the block editor prompt, and select "Try the block editor.")
4. When the other editor loads, note whether you see an app banner at the bottom of the screen.

#### What I expected

I expect the block editor to include an app banner like the one seen in the classic editor:

![2019-07-03 21 04 01](https://user-images.githubusercontent.com/8658164/60653838-7e4d9a80-9e53-11e9-9994-11555de83356.png)

#### What happened instead

The block editor shows no app banner:

![2019-07-03 21 03 55](https://user-images.githubusercontent.com/8658164/60653847-84437b80-9e53-11e9-841b-e3f581d36f41.png)

#### Browser / OS version

Safari on iPhone XS, iOS 12.3.1

#### Context / Source
#manual-testing

**Comment by Aurorum** [comment]
PR in #34582 for this. :)

**Comment by rachelmcr** [comment]
This is still an issue and I see there's actually an open PR for this that's been waiting quite a while for review. @lancewillett what's the best way to make sure this moves forward?

**Comment by Aurorum** [comment]
By the way, I just resolved the conflicts in that PR so it should be ready for review again. :)

**Comment by lancewillett** [comment]
Thanks to you both for nudging this "nudge." 😄

Adding to @Automattic/create team board for consideration. CC @noahtallen @p-jackson
