### ISSUE TITLE
Add own domain page for blogger plan states domain mapping included

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#34465]
#### Steps to reproduce
1. Starting in a site that has the blogger plan choose to add a domain you already own https://wordpress.com/domains/add/use-your-domain/<site>
2. Under the information for Map your domain without moving it from your current registrar. it states Free with your plan, but registration costs at your current provider still apply

#### What I expected
I would have expected the domain mapping to not be available or prompt for a different plan to be able to map a domain

#### What happened instead
It lets me try to map a domain and doesn't tell me until I add the domain that the Personal plan is needed.

#### Screenshot / Video

<img width="1285" alt="blogger-map-domain" src="https://user-images.githubusercontent.com/1326294/60678984-95dd5100-9e5c-11e9-9f61-b3c11e3ec6b2.png">

#### Context / Source

A customer reported the issue in 2154933-zd they were frustrated by the fact that it seemed like a bait and switch. They were told it was free with their plan on one screen and then had the Personal plan added to their cart automatically when trying to add the domain mapping.

 #user-report

**Comment by klimeryk** [comment]
Blogger plan has been sunset so I'm closing this issue as wontfix.
