### ISSUE TITLE
FSE: Create a WordPress.com loader for individual CoBlocks blocks.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#34466]
Rather than adding the proper CoBlocks plugin to Simple sites, we will create a minimal WordPress.com loader that uses only the CoBlock blocks we've identified as necessary at this point. We were going to need a custom loader and scripting to make various modifications anyways.

This will greatly reduce the amount of code review required, while taking no more time. CoBlocks blocks will continue to be identified as CoBlocks to users.

**Comment by mmtr** [comment]
Closed by D30413-code
