### ISSUE TITLE
Domains: Placeholders in email management

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3450]
Currently the email management screen looks like this before the domain details load for a given site:

<img width="773" alt="screen shot 2016-02-22 at 10 18 24" src="https://cloud.githubusercontent.com/assets/275961/13215513/c7035b94-d94d-11e5-858d-f8e79a3d4698.png">

We should probably consider using placeholders here, although exactly what they should show I am not sure.

cc @wensco @umurkontaci @breezyskies

**Comment by umurkontaci** [comment]
@scruffian Thanks :+1:  I put it in our backlog.

**Comment by breezyskies** [comment]
We already have designs for this in https://github.com/Automattic/wp-calypso/issues/857.

**Comment by klimeryk** [comment]
Closing this in favor of #857 :bow:
