### ISSUE TITLE
Site Privacy: allow an option to change a website to "coming soon" instead of "private"

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#34503]
Suggested by @m when discussing how Private by Default allows for a "coming soon" splash page. But, once you go live, you cannot get back to that state. How could we allow sites to go back into maintenance mode in the future?

Discussed briefly with @michaeldcain to sharpen the idea.

**Goal**: provide a simple solution to allow any WordPress.com site to change to a "coming soon splash page" by toggling the site setting to Private with an optional message.

Here are the current site privacy options:

<img width="754" alt="Screenshot 2019-07-07 15 52 00" src="https://user-images.githubusercontent.com/66797/60774849-320e8e80-a0cf-11e9-8d23-66d243aae0d7.png">

I suggest we add a sub-option under "Private" that reveals a text entry field in Calypso to allow the site author to change the "Private" message to say "Coming Soon" or anything they'd like it to say, such as "Maintenance Mode".

If the text is empty, we'd show the default "Protected Blog" page design:

<img width="1428" alt="Screenshot 2019-07-07 15 55 52" src="https://user-images.githubusercontent.com/66797/60774885-b5c87b00-a0cf-11e9-8b75-b3ee9c2f2299.png">

If the text field is NOT empty, we'd update the private page background image to look a bit nicer so that site owners can advertise WordPress.com a bit more for us. This is a much better advertising and marketing tactic than showing thousands or millions of broken or default-looking empty sites.

<img width="1392" alt="screen-shot-2018-11-08-at-15-05-58" src="https://user-images.githubusercontent.com/66797/60774921-4ef79180-a0d0-11e9-8190-ff23cc08f73f.png">

Cain suggested using the Private by Default custom image and design for the private mode when the custom message is added.

_Note: this suggestion is intended to K.I.S.S. Keeping it simple and not launching a full-blown landing page customization scheme, which would require choosing a page and design, etc._

**Comment by cecoates** [comment]
While we're at it, if we could add this functionality to Atomic sites too that would be fantastic.

It's disconcerting for a user to have their site on private while they build it, then have to go public to install a plugin, then have to install a plugin for maintenance mode to make it private again. From the user's perspective something that simple seeming becoming so much harder is a hard sell.

**Comment by michaeldcain** [comment]
@cecoates: I agree that it's a horrible user flow. Both Private Sites and Private by Default are planned to be added to Atomic sites. There was previously some work done to achieve this by adding them to Jetpack, but that work was shelved after questions arose as to the feature fit for Jetpack's product tiers.

**Comment by tbradsha** [comment]
While we're talking enhancements, allowing a custom image (or a few preset backgrounds) could be a nice touch as well.

**Comment by lancewillett** [comment]
"Splash page for sites under construction" comes up fairly often in support interactions. Internal ref: wp.me/pKdGS-Sk

**Comment by jancavan** [comment]
I wanted to add this here so it doesn't get lost.

From initial glance, it doesn't look like the "Login here" button is intended for the site owner only; it looks like it's inviting everyone to log-in because of its prominence and general placement. Having it say, "If this is your site, log-in here" would be much clearer. It also probably needs to go elsewhere on the page - like a small text at the bottom, or at the top right corner.

I like the idea of being able to customize it, and even just to be able to select from a few preset backgrounds as mentioned by @tbradsha above.

Another great idea that @michaeldcain mentioned was a way to add your email address to get updates to when the site launches. Could we use the Follow Blog Widget here?

**Comment by lancewillett** [comment]
Work as almost done on the "Private by Default" project, which has a Coming Soon component in Settings > Privacy.

<img width="734" alt="privacy-settings" src="https://user-images.githubusercontent.com/66797/81221110-3ded0a80-8f97-11ea-8dba-4e3ddaed73c4.png">

<img width="879" alt="logged-out" src="https://user-images.githubusercontent.com/66797/81221103-3b8ab080-8f97-11ea-99d4-1da1ab768cc8.png">

Closing this issue for now. Let's log new enhancements — such as the ability to customize a background image, or set an existing post/page as the Coming Soon splash page — in new issues in GitHub.

**Comment by adamziel** [comment]
To close the loop, this is now available to everyone: https://wordpress.com/blog/2020/05/15/coming-soon/
