### ISSUE TITLE
Notice: Compact notices' gridicon has an unnecessary top margin of 6px

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#34504]
Compact notices' gridicons seem to have an unnecessary top margin of 6px, which makes the icon look misplaced (not centered) as seen here:

https://wpcalypso.wordpress.com/devdocs/design/notice

Normal notices are fine. It's just compact ones that are affected.

<img width="506" alt="Screenshot 2019-07-08 at 08 31 38" src="https://user-images.githubusercontent.com/18581859/60780197-0b963500-a15b-11e9-869a-6e16982600ab.png">

<img width="1826" alt="Screen Shot 2019-07-08 at 08 31 56" src="https://user-images.githubusercontent.com/18581859/60780202-118c1600-a15b-11e9-9ffe-d85c19c0e81e.png">

It was introduced here - https://github.com/Automattic/wp-calypso/pull/19924/commits/3bcebe38fa0d056b5fab0e4cc6fb74561832a4c0 on https://github.com/Automattic/wp-calypso/pull/19924.

https://github.com/Automattic/wp-calypso/blob/532be1f7ecf67cc73e14ff2e9c55f271870fd7a7/client/components/notice/style.scss#L222-L224

Wonder if we should remove this rule. @jameskoster, could you share if there was a certain reason for this rule, please?

Happy to submit a patch if we would want to remove this.

**Comment by cbauerman** [comment]
This appears to have been closed by #34828. Icons look to be perfectly centered in the component example now!
