### ISSUE TITLE
Plan/domain notices' icon background doesn't blend with dark sidebar

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#34505]
When using Calypso themes (from https://wordpress.com/me/account) with dark sidebar, the plan/domain notices' icon section is having a `is-success` class. This sets a green background as shown below.

| Name of color scheme | Image |
|------|------|
| Ocean | <img width="321" alt="Screenshot 2019-07-08 at 08 56 19" src="https://user-images.githubusercontent.com/18581859/60781089-9d537180-a15e-11e9-8d10-9314add1f800.png"> | 
| Sunset | <img width="393" alt="Screenshot 2019-07-08 at 08 56 31" src="https://user-images.githubusercontent.com/18581859/60781088-9d537180-a15e-11e9-8072-86d46f43f14e.png"> | 
| Midnight | <img width="394" alt="Screenshot 2019-07-08 at 08 56 39" src="https://user-images.githubusercontent.com/18581859/60781087-9cbadb00-a15e-11e9-8973-ef53131fb66d.png"> | 
| Night | <img width="383" alt="Screenshot 2019-07-08 at 08 57 15" src="https://user-images.githubusercontent.com/18581859/60781086-9cbadb00-a15e-11e9-9e1a-66dcdc760f7c.png"> | 

The notices look fine against color schemes with light background.

**Proposal:** We should use `is-info` class instead of `is-success` for positive notices, only in this sidebar region. 

But then, domain warning/error notices would not be improved with that change. 

<img width="309" alt="Screenshot 2019-07-08 at 09 02 33" src="https://user-images.githubusercontent.com/18581859/60781281-5f0a8200-a15f-11e9-9fa8-b303c6a28a40.png">

This was originally reported by @rantoncuadrado at p58i-7SN-p2#comment-42330

Tagging design review for thoughts, and also possibly @Automattic/cobalt as domains warning notices come under their territory. 

Should we leave things as they are now? 🤔

**Comment by sixhours** [comment]
I don't think we can change the green to yellow, since it's not semantically a warning. We've also been asked to be very careful about changes made to those upgrade flags in the sidebar in general: https://github.com/Automattic/wp-calypso/issues/32532#issuecomment-488878475

I don't think the green clashes with the darker color schemes--Sunset is the exception, but given color schemes' relatively low usage, I don't think we should worry about it. :)

**Comment by arunsathiya** [comment]
Interesting, it's good to have the link to the other thread! Feels like a non-issue at the moment, let me close this. We can reopen in the future, as necessary. 👍🏽
