### ISSUE TITLE
Earn Section: Code up copy variations for each card

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34517]
## Description

We'll need to instrument different copy and links depending on the plan that a customer is currently on:

![copy](https://user-images.githubusercontent.com/5634774/60831009-858fe380-a186-11e9-83b9-35970ed8773b.png)

**Comment by eliorivero** [comment]
Reviewed in p2JRYi-46s-editorialp2

**Comment by benhuberman** [comment]
@eliorivero I just wanted to confirm -- was this handled already by another editor via p2?

**Comment by benhuberman** [comment]
Please disregard the previous comment -- I just found the relevant thread and @michelleweber's replies. Let us know if you need any further assistance!
