### ISSUE TITLE
Signup: credit card icon misalignment in RTL

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3451]
## Issue description
In the domain payment form for RTL locales, the credit card icon is not fully displayed: it is truncated because it is aligned too far left.

## Screenshots
English (correct icon alignment)
![en_tablet_5c_domain_payment_form_screenshot1453773609561](https://cloud.githubusercontent.com/assets/7637835/13216333/d4d48110-d963-11e5-9d3b-ad3791c5eaa0.png)

Hebrew (icon is misaligned)
![he_desktop_5c_domain_payment_form_card icon is not fully displayed](https://cloud.githubusercontent.com/assets/7637835/13216210/18287a76-d963-11e5-8f34-2c1acccc1228.png)
![he_mobile_5c_domain_payment_form_truncation](https://cloud.githubusercontent.com/assets/7637835/13216213/1aedfa74-d963-11e5-9849-50c85cb3b141.png)

**Comment by gziolo** [comment]
@breezyskies another one for your team :)

**Comment by lancewillett** [comment]
Still seeing this bug.

Mac-n-Chrome with `he` locale set for my test user:

![screen shot 2016-05-12 at 11 16 04 am](https://cloud.githubusercontent.com/assets/66797/15225431/3fb3b15a-1833-11e6-9bdf-2119dbea95cc.png)

I think the RTLCSS change from 100% to 0% when flipping the icon from right (100%) to left (0%) and subtracting 10px doesn't take into account that for RTL that would need to be +10% (not minus).

One solution is to use `right` which flips to `left` for RTL — much simpler. Or 99% and 1% — something that doesn't need too much `calc` calculations. :)

CC @yoavf

**Comment by yoavf** [comment]
Our current version of RTLCSS doesn't support `calc`. Newer versions do, but have a bug related to this specific case.
I've opened https://github.com/MohammadYounes/rtlcss/pull/72 - if I can get it merged, I'll bump our RTLCSS version.

**Comment by lancewillett** [comment]
Cool — I think in situations like this, it also points to "how could this be simpler" rather than trying to out-think it. :)

**Comment by yoavf** [comment]
Fixed with #5440
