### ISSUE TITLE
Earn Section: Tracks funnel specifically for upgrade button click -> conversion

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34520]
## Description

We'd like to have a separate tracks funnel that just looks at "Upgrade to X Plan" buttons and their conversion to paid plans.

**Comment by pablinos** [comment]
The tracks events are now in place, so it's a case of setting up a funnel to report on it

**Comment by kwight** [comment]
Closing as the funnel can be done at any time.
