### ISSUE TITLE
Earn Section: Create a CTA card component

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34529]
## Description

This can be modeled after the existing [marketing section CTA card](https://github.com/Automattic/wp-calypso/pull/32510/files#diff-a9a814f97b424ca36613aca77c1f7bc0R21).

The goal will be to abstract this out into a generic component that can then be reused within multiple sections.

## Related

- https://github.com/Automattic/wp-calypso/issues/34530
- https://github.com/Automattic/wp-calypso/issues/34528

**Comment by pablinos** [comment]
I'm hopefully going to be able to use a variation on the [`ActionPanel`](https://wpcalypso.wordpress.com/devdocs/design/action-panel) component for this, and use a prop to make the header component version needed for #34528
