### ISSUE TITLE
Earn Section: Add earn section item to onboarding checklist congrats screen

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34524]
## Description

We tried to get promotion for the Earn section on the checklist itself, but the Start focus team is trying to keep that list as short and focused as possible. We did however get permission to add a promotion on the [congrats screen](https://wordpress.com/checklist/) that is shown just after you complete all of your checklist items.

![](https://d1jfzjx68gj8xs.cloudfront.net/items/3w0U471s2P2l0c2k0F0r/Image%202019-07-22%20at%207.16.28%20AM.png)

## Backstory

We know customers are asking for it. 8 out of the top 12 goals people list having when going through the onboarding flow have to do with wanting to make money.

**Comment by davemart-in** [comment]
I'd like to propose punting this idea for two reasons:

A) If we add something, it will have to be way at the bottom, and I doubt anyone will realistically see it. 
B) My hope is to completely replace the checklist and the completion screen with the customer home screen.

**Comment by Aurorum** [comment]
I wonder if this was sort of resolved by #42808 then?
