### ISSUE TITLE
Earn Section: Add header cake to recurring payments

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34525]
## Description

We'll want to remove the tabs and add the header cake component:

![](https://d1jfzjx68gj8xs.cloudfront.net/items/0j0j0W2j150U26452W3k/image_preview%20(1).png)

**Comment by eliorivero** [comment]
Can you please specify where it will go **Back**?

**Comment by pablinos** [comment]
As I understand it, it should go back to our new earn page, which doesn't exist yet! Shall we set up a placeholder `/earn/example.com` page and use that?

**Comment by davemart-in** [comment]
@eliorivero Paul is correct. The back link should take you back to the main Earn section that we're designing (https://wordpress.com/earn/yourdomain.com)
