### ISSUE TITLE
Earn Section: Create a header card component

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34528]
## Description

This can be modeled after the existing [marketing section header card](https://github.com/Automattic/wp-calypso/pull/32510/files#diff-b024540dc11a9394de31e09810c8379eR17).

The goal will be to abstract this out into a generic component that can then be reused within multiple sections.

## Related

- https://github.com/Automattic/wp-calypso/issues/34530
- https://github.com/Automattic/wp-calypso/issues/34529

**Comment by kwight** [comment]
It seems this was taken care of in the related PRs.
