### ISSUE TITLE
FSE: Tortuga Theme does not display Starter Page Templates on AT sites

### ISSUE THREAD

**Issue by AMcGrady** [Automattic/wp-calypso#34548]
#### Steps to reproduce
1. Activate Tortuga theme on an AT Site
2. Make sure Gutenberg and Full Site Editing plugins are Active
3. Add New Page

#### What I expected
I expected the Starter Page Templates to pop up.

#### What happened instead
The Gutenberg editor loaded without the Starter Page Templates showing up.

**Comment by frontdevde** [comment]
Issue triage 27-02-2020
Closing stale issue as it's tracked in https://github.com/Automattic/wp-calypso/issues/39741
