### ISSUE TITLE
FSE: Investigate Jetpack and CoBlocks Maps block.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#34549]
The CoBlocks Maps block apparently has a better UX than the Jetpack Maps block. Let's investigate what the differences are, and how best to proceed for offering an improved Maps block on WordPress.com.

https://github.com/godaddy/coblocks/blob/master/includes/class-coblocks-google-map-block.php
https://github.com/Automattic/jetpack/tree/master/extensions/blocks/map

**Comment by iamtakashi** [comment]
> The CoBlocks Maps block apparently has a better UX than the Jetpack Maps block

The problem with Jetpack Map block is that it requires users signing up with a third party, Mapbox and getting an API from them to add a map.

**Comment by kwight** [comment]
This may involve iframing for the preview, to avoid needing a key right away (let's confirm this).

**Comment by simison** [comment]
I suspect this can be closed now that Maps block doesn't require API key anymore on wpcom.
