### ISSUE TITLE
Full Site Editing: wrong block inserter position

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34544]
After overriding the default inserter with our custom one in https://github.com/Automattic/wp-calypso/pull/34425 in order to prevent the blocks from being inserted outside of Content Slot, the new inserter is now incorrectly positioned:

<img width="249" alt="Screenshot 2019-07-08 at 21 00 36" src="https://user-images.githubusercontent.com/1182160/60885786-b1779b80-a250-11e9-9119-3a4c24d4b963.png">

It should appear after the Close button and the separator/bar.

**Comment by noahtallen** [comment]
🤔🤔I'm not seeing this on a local install of `master`:
<img width="289" alt="Screen Shot 2019-07-10 at 6 23 27 PM" src="https://user-images.githubusercontent.com/6265975/61015301-d434ad80-a33f-11e9-8156-81c20db5733c.png">

It seems to be in the correct position for me on the template, template part, page, and post editor screens. Are there any steps you need to take to reproduce it?

**Comment by vindl** [comment]
Thanks for verifying @noahtallen! I can't reproduce this with latest master anymore either.
We only have to worry about template CPTs because that's where the override happens iirc.

Closing this for now, but let's keep an eye on it in case it returns.

**Comment by noahtallen** [comment]
Sounds good! :)
