### ISSUE TITLE
Checklist: Can't complete the steps in order with a new account

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#34556]
#### Steps to reproduce
1. Starting logged out at URL: https://wordpress.com/start
2. Complete the signup flow for a new account and site.
3. When you land on the checklist, select "Try It" for the next item in the checklist ("Update your homepage").

#### What I expected

I expected to be able to complete the next task in the list.

#### What happened instead

Starting the task opens the editor, but I can't update the page because my email address isn't yet confirmed.

I have to complete the last task in the checklist ("Confirm your email address") before I can update my homepage.

#### Browser / OS version

Chrome 75.0.3770.100 / macOS 10.14.5

#### Screenshot / Video

![Screenshot 2019-07-09 18 33 12](https://user-images.githubusercontent.com/8658164/60910546-05967600-a279-11e9-8da1-40b702e6d922.png)

![Screenshot 2019-07-09 18 34 06](https://user-images.githubusercontent.com/8658164/60910549-06c7a300-a279-11e9-8981-71c340bf62bd.png)

#### Context / Source
#manual-testing

cc @Automattic/start-dev

**Comment by mattsherman** [comment]
Confirmed this is still an issue.

/cc @michaeldcain

**Comment by ramonjd** [comment]
<img width="600" alt="Screen Shot 2019-07-30 at 1 32 16 pm" src="https://user-images.githubusercontent.com/6458278/62098770-1ada4f80-b2cf-11e9-87d6-475acebd7283.png">

Maybe we could give priority to the `email_verified` task at all times?

**Comment by michaeldcain** [comment]
This is a regression from disabling Private by Default. Once it's re-enabled in #35007, users will be able to edit/publish content again with un-verified emails while a site remains private.

**Comment by creativecoder** [comment]
I believe this issue can be closed. I just tested signup with a new user and I am able to update the home page without verifying email.
