### ISSUE TITLE
Linting: "not installed" error for PHPCS could have a reference to installation docs and instructions.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#34552]
When the pre-commit hooks run for linting, a user will see an error if they do not have PHPCS locally installed. Instead of just the error, we can add a more helpful information like links to docs or installation instructions.

**Comment by mattwiebe** [comment]
This would have been nice to have today :)

Looks like you need to add `~/.composer/vendor/bin` to your `$PATH`.

**Comment by mattwiebe** [comment]
No, that doesn't do it, either. This is very frustrating. We should not have this here if it's not documented properly. Pretty sure we should have a `composer.json` file here to manage the dependencies we're expected to have to make this work.

`--no-verify` it is for me.

**Comment by kwight** [comment]
Part of the problem is that you can install PHPCS so many different ways and in different locations locally, so of which may or may not need `$PATH` adjustments. Basically, if you can get `which phpcs` to find a binary and exit `0`, it'll pass that check.

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.
