### ISSUE TITLE
FSE: Split the plugin update script into two diffs with a summary at the end.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#34559]
Currently, the script will make one diff that both adds the new plugin version and activates it. This is not considered best practices for our deploys, so let's split the constant changes into their own diff.

Because of the long SVN output after the successful diff creation, also add a summary of the two new diffs as final output when exiting the script.

**Comment by noahtallen** [comment]
Closing as this has been accomplished.
