### ISSUE TITLE
FSE: The site navigation block is placing the CSS class on the wrong element

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34565]
When using the site navigation block in the header, the CSS "main-menu" class is placed on a wrapping DIV, instead of directly on the main UL element. This means the CSS in the theme for the navigation is not picked up correctly:

<img width="951" alt="Screen Shot 2019-07-09 at 1 28 41 PM" src="https://user-images.githubusercontent.com/1464705/60920703-acfdb380-a24d-11e9-9b3b-a9c22d5e7b27.png">

If the class is instead placed on the main UL, and the DIV wrapper is removed, then the menu is rendered correctly:

<img width="944" alt="Screen Shot 2019-07-09 at 1 31 20 PM" src="https://user-images.githubusercontent.com/1464705/60920783-dc142500-a24d-11e9-9b7c-d86ba5545b59.png">

**Comment by apeatling** [comment]
The fix for this is to modify the default params for the site navigation block in the main menu position:

<img width="387" alt="Screen Shot 2019-07-09 at 1 32 15 PM" src="https://user-images.githubusercontent.com/1464705/60920864-08c83c80-a24e-11e9-8bdd-567f05246987.png">

**Comment by noahtallen** [comment]
Possibly related conversation: https://github.com/Automattic/wp-calypso/pull/34396#discussion_r299671761

**Comment by apeatling** [comment]
Yes this is the same issue. Closing this as a duplicate of #34429
