### ISSUE TITLE
Videopress: video uploads keep failing on notesonfilm1.com

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#34576]
User is trying to upload this video: https://drive.google.com/file/d/1fHmEO1sPypmeyPPgc68bOw4ghXe0vpUl/view?usp=sharing on their site but the upload keeps failing, it shows an error `file could not be uploaded`. The video is about 30MB.

I was not able to replicate this issue on my side. 

I suspected this might be due to their internet upload speed which is 450 Kbps (see screenshot: https://snag.gy/CyeuN2.jpg) however user says they were able to upload even larger videos with the same internet connection previously. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/notesonfilm1.com
2. Upload media file: https://drive.google.com/file/d/1fHmEO1sPypmeyPPgc68bOw4ghXe0vpUl/view?usp=sharing

#### What I expected
- Video uploads to media library 

#### What happened instead
Video does not upload, instead it shows an error message: `1 file could not be uploaded because an error occurred while uploading`.

#### Browser / OS version
Chrome Version 75.0.3770.100

#### Screenshot / Video
![IeV1QZ](https://user-images.githubusercontent.com/39188945/60989444-51fbb780-a346-11e9-8629-3c8a44c5ae36.jpg)

#### Context / Source
 #user-report 

#### Site info
- Site URL: notesonfilm1.com
- User: `joseantonioarroyo`
- Chat: 13907517-HC 
- Ticket: 2168758-zen

**Comment by lancewillett** [comment]
Hi @sourourn — I suggest closing this (or you can in the future use the Happiness Feedback P2 instead) since it appears to be a one-off issue. Especially if you can't replicate it yourself.

We usually log bugs in GitHub that are a pattern, or more than one case, so we can look for underlying causes.
