### ISSUE TITLE
FSE: Site title and description blocks have a white background

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34571]
Both the site description and title blocks have a white background which means they look broken on business child themes that do not use a white background:

<img width="731" alt="Screen Shot 2019-07-09 at 3 52 57 PM" src="https://user-images.githubusercontent.com/1464705/60928315-c0b31500-a261-11e9-8804-2ee86123235d.png">

Here's a clearer example when a group block background is set:

<img width="733" alt="Screen Shot 2019-07-09 at 3 54 15 PM" src="https://user-images.githubusercontent.com/1464705/60928326-d0325e00-a261-11e9-9b91-1a72be4c242b.png">

The background to the blocks need to be transparent.

**Comment by noahtallen** [comment]
Looks like this is because `textarea`s have a white background by default. Should be a straightforward fix! :)
