### ISSUE TITLE
Components: global notices have fixed width in IE11

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#3459]
## URL
https://wordpress.com/settings/general/ (or any other view that uses global notices)

## What I expected

No word wrapping, since the message was short (`Settings saved!`)

## What happened instead

The message was wrapped after the first word. Testing with other messages, it seems that the notice has a fixed width, it doesn't matter how long the message is.

## Steps to reproduce

1. Visit the `Settings` page for a selected site: https://wordpress.com/settings/general/ using IE11
2. Click `SAVE SETTINGS`.

## Browser / OS version

IE11 / Win7

## Screenshots
![notices](https://cloud.githubusercontent.com/assets/3392497/13221331/30849100-d97b-11e5-9ef8-ff43ad472c74.jpg)

/cc @mtias @artpi

**Comment by mtias** [comment]
@rickybanister could you take a quick look?

**Comment by rickybanister** [comment]
Looking.

**Comment by rickybanister** [comment]
There's some sort of width + flex bug in IE11, I'll work on a fix.

**Comment by MichaelArestad** [comment]
I can't reproduce on IE11 on Windows 7 or IE11 on 8.1.

**Comment by klimeryk** [comment]
@MichaelArestad: I've tested it again on IE11 on Windows 7 with the newest `master` and on `wpcalypso` - both still show the issue for me :/
It looks like `flex-basis` might not be behaving as expected on IE11? It's [defined as `flex-basis: 100px;`](https://github.com/Automattic/wp-calypso/blob/master/client/components/notice/style.scss#L47) and it seems that IE treats that as the maximum width. If I change it to, say, `200px` it grows to `200px`... Unfortunately, I'm no CSS expert (especially, when it comes to `flex`), so I can't figure out a fix for it.

**Comment by rickybanister** [comment]
I think the bug still exists, however 'Settings Saved' now fits within the 100px flex-basis because of our switch from Open Sans to system fonts. Still looking for a solution here.

**Comment by MichaelArestad** [comment]
Fix proposed here: https://github.com/Automattic/wp-calypso/pull/3910

**Comment by klimeryk** [comment]
Verified - #3910 indeed fixes this. Thanks! :+1:
