### ISSUE TITLE
Editor: comments appear to be allowed in the preview even though they've been disabled for the post

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#346]
Steps to reproduce:
1. Create a new post and disable comments
2. Click the "Preview" button
3. Look for the comment form

<strong>Result:</strong> comments appear to be allowed in the preview even though they've been disabled for the post.

Clip: [25s](https://cloudup.com/cCUKHdwmdGK)

![screen shot 2015-11-02 at mon nov 2 2 33 05 pm](https://cloud.githubusercontent.com/assets/1119271/10891924/af9223f0-816e-11e5-8550-91f550048762.png)

Found during user testing.

**Comment by alisterscott** [comment]
This has been fixed:

![comments](https://cloud.githubusercontent.com/assets/128826/25983324/67caf77a-3727-11e7-9bcd-da06b8cb029d.gif)
