### ISSUE TITLE
Full Site Editing: create primary menu during plugin activation

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34608]
Aa follow up to https://github.com/Automattic/wp-calypso/pull/34568, we've noticed that styling to the navigation menu block is not applied correctly if primary menu is not created.

Let's make sure that we create it, if it doesn't exist already, when activating the plugin.

**Comment by apeatling** [comment]
This will be fixed by https://github.com/Automattic/wp-calypso/pull/34796
