### ISSUE TITLE
FSE: Support multiple header block templates

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34610]
In order to support all of our business themes, we will need to support ~two~ three different site header block templates.

One block template will be for a single column header with description first, one for a single column header with title first, one for a two column header:

![screenshots-1](https://user-images.githubusercontent.com/1464705/61091840-8cbe2800-a3f8-11e9-9adf-d409c8489ffc.png)

Currently the FSE plugin hard codes the default header block template content. This needs to be offloaded and support multiple versions.

An ongoing discussion around this can be found in https://github.com/Automattic/wp-calypso/issues/34560

/cc @vindl

**Comment by apeatling** [comment]
I've confirmed in local testing that this template will work to support all business themes that need two columns:

<img width="684" alt="Screen Shot 2019-07-11 at 4 28 41 PM" src="https://user-images.githubusercontent.com/1464705/61091948-06eeac80-a3f9-11e9-86b8-6616e5b970bf.png">

Here it is working with Friendly Business:

<img width="1414" alt="Screen Shot 2019-07-11 at 4 29 51 PM" src="https://user-images.githubusercontent.com/1464705/61091965-1ff75d80-a3f9-11e9-8997-07d99663cc67.png">

**Comment by apeatling** [comment]
For completeness. The second single column header block template content is already in the plugin here:

https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/utils/class-a8c-wp-template-data-inserter.php#L75

**Comment by apeatling** [comment]
We actually need a third header block template. Elegant business places the title block before the site description block:

<img width="1006" alt="Screen Shot 2019-07-12 at 9 45 28 AM" src="https://user-images.githubusercontent.com/1464705/61144466-cc812000-a489-11e9-9cfa-384e6facd0cd.png">

This can be done using this block template:
https://codepen.io/pen/?editors=1000

**Comment by vindl** [comment]
> Currently the FSE plugin hard codes the default header block template content. This needs to be offloaded and support multiple versions.

After the merging of #34560 this is no longer the case. I don't think we need a separate issue for this, since each theme will handle data population separately and can pull in any data that it needs. I'm going to close this issue for now and will be opening more specific ones for each theme.
