### ISSUE TITLE
FSE: CoBlocks Food & Drink Block - Text can't be edited in menu heading block

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#34615]
When adding a CoBlocks Food & Drink block, it is not possible to edit the Menu Title block - the text is fixed at "Menu title..."

#### Steps to reproduce
1. Apply D30340-code and D30379-code to your sandbox
2. Also sandbox  public-api.wordpress.com 
3. In your sandbox site add a Food & Drink CoBlock
4. Attempt to edit the Menu title ... text

**Comment by kwight** [comment]
Hm, I can't replicate; no problems in the editor nor the front-end. This is testing with a fresh build today in D40311-code and D40313-code. Will close for now.

![Uploading Screen Shot 2019-07-12 at 3.03.32 PM.png…]()
