### ISSUE TITLE
Plans: Icons still using incorrect color

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#34634]
#### Steps to reproduce
Starting at URL: https://wpcalypso.wordpress.com/plans/my-plan/[site]

#### What I expected
To not be seeing any icons with green in them. I think we updated them before, but I couldn't find the PR for it.

#### What happened instead
Icons still using green

#### Browser / OS version
Mac OS Mojave 10.14.2
Google Chrome Version 75.0.3770.100

#### Screenshot / Video
![Screenshot 2019-07-12 13 15 26](https://user-images.githubusercontent.com/4924246/61156035-4d9ae000-a4a7-11e9-92e1-5942e735494b.png)

**Comment by Aurorum** [comment]
It was addressed on #33115. I think it's a wider issue with updated SVGs, #30138 still hasn't taken effect for me.

**Comment by arunsathiya** [comment]
Here is what seems to be going on for me.

Google Ads Credit is broken for me. It's showing a 404 both on https://wordpress.com/ and https://wpcalypso.wordpress.com/ and I have logged it here - https://github.com/Automattic/wp-calypso/issues/34641

The green colors in the illustrations seems to be happening only for "Advertising removed" block for me, and only on https://wpcalypso.wordpress.com AND only on the upcoming color schemes:

- Ocean
- Sunset
- Midnight
- Contrast

Using the same color schemes, the illustrations appear in blue on https://wordpress.com/ 

Any chance the two of you are on https://wpcalypso.wordpress.com and using one of these new color schemes?

**Comment by Aurorum** [comment]
I actually don't see the 404 error. The colour schemes didn't have an impact for me, I've been using Ocean but I also changed to Nightfall to check.

wordpress.com:
<img width="1628" alt="Screenshot 2019-07-14 at 18 45 35" src="https://user-images.githubusercontent.com/43215253/61187298-cba5e500-a667-11e9-88ab-05fd5585d512.png">

wpcalypso.wordpress.com:
<img width="1603" alt="Screenshot 2019-07-14 at 18 45 42" src="https://user-images.githubusercontent.com/43215253/61187303-d2345c80-a667-11e9-8af4-18e8a9cf25f6.png">

**Comment by sixhours** [comment]
I'm seeing the old colors when un-proxied. They use the correct colors when I proxy. I have no idea why that would happen, though. 🙃

**Comment by sixhours** [comment]
@jsnajdr confirmed with opers this is a server-side caching issue with static images. It sounds like a "quick" fix is to rename the files to force flush the cache, but I'm not sure that's the best solution.
