### ISSUE TITLE
My plan: Google Ads Credit: Illustration missing

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#34641]
When reading https://github.com/Automattic/wp-calypso/issues/34634, I noticed that the Google Ads Credit illustration is not showing up on production:

![Screen Shot 2019-07-14 at 17 38 22](https://user-images.githubusercontent.com/18581859/61183543-37844f80-a660-11e9-91e3-e1017a35ad4c.png)

To add to confusion, I see it on the actual file page: 

https://wordpress.com/calypso/images/illustrations/google-adwords.svg

To add to more confusions, the file itself seems to be broken:

https://github.com/Automattic/wp-calypso/blob/master/static/images/illustrations/google-adwords.svg

I have zero knowledge of .svg files, so, not sure what's going on here.

I am marking with high priority because something is broken on the production at the moment.

**Comment by arunsathiya** [comment]
Also noting that I checked two different WordPress.com accounts on two different computers before logging this request. Broken on both.

**Comment by sixhours** [comment]
Pinged in Slack to see if something is going on on the server side. I'm seeing that image as intended, except when unproxied, at which point it appears but uses the old colors.

**Comment by sixhours** [comment]
@jsnajdr confirmed with opers this is a server-side caching issue with static images. It sounds like a "quick" fix is to rename the files to force flush the cache, but I'm not sure that's the best solution.

**Comment by arunsathiya** [comment]
Google Ads credit is no longer available - p7DVsv-8Wc-p2. Closing.
