### ISSUE TITLE
Editor: Non-latin alphabet characters display as unicode in post/page slug

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#3465]
## URL:

https://wordpress.com/post and /page
## What I expected

When a draft is saved or published, the post title is added as the permalink slug, and can be edited under More Options in the editor menu. When using non-Latin alphabet characters, the expectation is that those characters will display in the edit-box. This happens in the WP-Admin editor, and the non-Latin characters also display when viewing the page in a browser.
## What happened instead

This was reported by a Hebrew user in 2537264-t. On saving the post the slug displayed in Hebrew letters, but the moment the post was published those changed into encoded characters instead.

I tested this in a few other non-Latin alphabets as well with the same result.

The actual permalink of the page still shows the correct characters, but the characters not displaying in the editor makes it problematic to edit the existing slug if needed.
## Steps to reproduce

Create a new post or page.

Add a title in any non-Latin alphabet.

Save the post, and expand More Options to see the slug matching the post title.

Publish the post. The slug will change as soon as the post is published.
## Browser / OS version

It happens on various browsers, on Mac and Windows, and also in the desktop apps
## Screenshots / Video

![hebrew slug](https://cloud.githubusercontent.com/assets/11873759/13222126/3456d85e-d987-11e5-8774-c500cd2f0d3a.gif)

**Comment by hoverduck** [comment]
21Apr16 Bug Scrub

Confirmed this is still a problem.  Tested with Chinese, Arabic, Cyrillic, Thai, and various Unicode characters

**Comment by designsimply** [comment]
Tested and confirmed using the following text: `זהו עין הנמר` 

<strong>Video:</strong> [14s](https://cloudup.com/cZuey1UI5ma)
