### ISSUE TITLE
Remove cookie banner when previewing your own site (especially for the first time)

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34654]
## Description

Gareth Noon came up with a great idea.

When a new user goes through the process of setting up their first site, if they make it all of the way through the flow and then go to preview their site, they see the big cookie policy banner blocking the bottom portion of their site.

![](https://d1jfzjx68gj8xs.cloudfront.net/items/0e312C211E2d1n1o3a2U/%5B2aade3921e99b4a4bf527a580bfdbb5f%5D_Screen%2520Shot%25202019-07-15%2520at%252011.11.09%2520AM.png?X-CloudApp-Visitor-Id=3172841)

_Sorry for the low res image!_

## Suggestion

It would be great if when logged in and viewing your own site we just hid that banner. It doesn't really serve any purpose but to just get in the way if it's your own site.

**Comment by sixhours** [comment]
We need to check to see if we're allowed to remove the banner; even on one's own site, I don't know if we're required to display it regardless. I'll look into this!

**Comment by sixhours** [comment]
The short answer: If our ad cookies are running on a site, we need to display the GDPR banner, regardless of site ownership.

The current site preview is the whole site displayed in an iframe, so any ads/cookies are active, and therefore we need to show the banner. :-/

Full discussion here: p1563292173038400-slack-privacy-help

This doesn't mean we can't remove the banner for new sites -- if we opted not to show ads on new sites for a limited time, for example, we could remove the banner during that time. Basically, remove the ads, remove the banner.

If we do come up with a changeset that would make the banner disappear for certain scenarios, we need to let the privacy folks know so they can confirm it legally and leave a breadcrumb trail with our reasoning: p1563293158054300-slack-privacy-help

**Comment by sixhours** [comment]
There's a past discussion on the subject here, it gets pretty involved: p4H3ND-Ns-p2

More context in #31158

**Comment by sixhours** [comment]
So it seems like we *can* remove the banner from the site preview within Calypso based on confirmation from @rclations in p4H3ND-Ns-p2 and #31158. It's been removed from the owner's site in the mobile apps already.

Now it's a matter of technical feasibility and ensuring we notify folks before we deploy anything.

**Comment by sixhours** [comment]
In testing this, I'm not seeing the cookie banner in the site preview within Calypso. I do see it on the front end. @davemart-in do you have more specific steps to reproduce the issue? I wonder if it was already addressed, or if I'm missing something.

**Comment by davemart-in** [comment]
Oops! Sorry for not including steps to replicate! 

To clarify, this issue was specifically for how we deal with previewing on the front-end of the users site, not specifically related to the in-app site preview section.

**Comment by sixhours** [comment]
Ahhh, that makes sense. :) I started a patch here: D30504-code

**Comment by rclations** [comment]
I don't think we want to remove the banner from the front-end _view_ of the site for administrators. If there's a preview section in Calypso we'd like to suppress it on, that's more in line with the work done in the past.

**Comment by sixhours** [comment]
> I don't think we want to remove the banner from the front-end view of the site for administrators. If there's a preview section in Calypso we'd like to suppress it on, that's more in line with the work done in the past.

It looks like it's already been disabled in the site preview in Calypso, and clarification from Holly suggested we can extend that to hide it for site admins on their own sites:

> We can definitely remove the banner on the site owner's own site, Will be non-targeted ads on their own site--but a good tradeoff for improved UX .

**Comment by davemart-in** [comment]
I've spoke with a number of folks behind the scenes. I'd like to propose the following:

My vote would be to prevent the cookie banner from being shown on your site for the first 30 days after you first sign up. I don't think this has the potential to have any impact on revenue (since we hide ads for the first 30 days already), and it saves the new user from seeing it the first time they visit their own site, alleviating the UX issue.

Any concerns with this proposal?

**Comment by sixhours** [comment]
No concerns! @cphilleo and I chatted about this and he pointed me toward the correct place to implement this. I created a new patch here: D30546-code

**Comment by davemart-in** [comment]
@sixhours 

![jig](https://user-images.githubusercontent.com/5634774/61409614-9d671600-a8b0-11e9-8c2c-845fe8dcb156.gif)

**Comment by donpark** [comment]
AFAIK Caroline will be deploying this to WPCOM when she returns.

**Comment by sixhours** [comment]
Planning to deploy this today! Waiting to hear back from Cat about how we should notify HEs of the change.

**Comment by sixhours** [comment]
Notified HEs in p7DVsv-6Yg-p2 and deployed this in r194451-wpcom
