### ISSUE TITLE
FSE: Update the design of the header hover

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34659]
The design of the header on hover needs more polish. It's too dark to see through on hover, and too quick to highlight an unhighlight making it disorienting.

![2019-07-15 10 38 27](https://user-images.githubusercontent.com/1464705/61236439-dbb3d800-a6ec-11e9-83b2-8ad1753d4eba.gif)

TL;DR from conversation in https://github.com/Automattic/wp-calypso/pull/35158
====== 
Let's update the hover state to:
<img width="1257" alt="62586343-05869780-b872-11e9-80f5-639a6a171733" src="https://user-images.githubusercontent.com/1270189/62586811-0b7d7800-b874-11e9-859b-367376048a99.png">

And the Focus State to the following possibly using https://caniuse.com/#feat=css-backdrop-filter
<img width="1474" alt="62586353-146d4a00-b872-11e9-9aac-20e4c31dbf61" src="https://user-images.githubusercontent.com/1270189/62586821-13d5b300-b874-11e9-8c6a-b74302920506.png">

**Comment by shaunandrews** [comment]
I've been thinking we should avoid the drastic highlighting — its very distracting, especially with larger headers/footer. It also obscures the content within the block — making it difficult to understand what's within it.

We could adopt the standard Gutenberg block `:hover` which would look something like this:

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/191598/61236928-38bc8780-a707-11e9-8673-402f2f1b19fe.png">

Its really (really, really) subtle, but I think thats a bigger issue with Gutenberg.

Then we can show the message when the block is focused. Here's a few different treatments for that:

![Header Focused](https://user-images.githubusercontent.com/191598/61237662-ee3c0a80-a708-11e9-8e04-86d6fec942a5.png)

The first and last are my preference, with the only difference being the positioning of the toolbar.

**Comment by glendaviesnz** [comment]
I didn't get really get anywhere on this due to issues getting my local setup running with the latest Modern Business changes - sorted now, so will have another look on Monday, but feel free anyone else to pick this up in the mean time.

**Comment by apeatling** [comment]
I think the first and last options are off the table now, because we've hidden the template and post content block UI.

**Comment by shaunandrews** [comment]
> because we've hidden the template and post content block UI

We hid them because as-is, they offer nothing. But, if we can make them useful, we should bring them back. At least for the template_part blocks. I still see no use-case for the content block UI to come back.
