### ISSUE TITLE
FSE: CoBlocks multisite support options

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34658]
Lets investigate options on how we can safely provide CoBlocks in multisite environments. Currently, blocks are only fully supported on single site instances using the Admin or Editor roles.

**Comment by davipontesblog** [comment]
Closing this as we have CoBlocks in simple sites now.

**Comment by gwwar** [comment]
We can close out, but @davipontesblog this one in particular would be an upstream contribution. CoBlocks often break in [multisite](https://www.smashingmagazine.com/2020/01/complete-guide-wordpress-multisite/) WordPress installs because of single site assumptions and privileged permissions,  which is why we've whitelisted so few blocks on simple sites.
