### ISSUE TITLE
Cropping an image in a post causes disappearance 

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#34665]
**Preface:** Some websites seem to allow the user to edit the image (rotate, crop, flip) within the Calypso editor when inserting an image to a page or when editing the image from the Media page. Not all sites seem to have this, as we can see here: [can edit images](https://cldup.com/Pz1jTtmIzS.jpg), [cannot edit images](https://cldup.com/ucO7CVgJ_m.jpg). If you want to replicate this behavior you need to work on a **simple site using Gutenberg that can edit images** from this option.

**Summary:** If we use the aforementioned image editor to crop an image while adding it on the page then all prior content on that page will disappear. This includes other images, paragraph blocks, etc. The new image will be inserted and cropped but all other content will disappear.

#### Steps to reproduce
_I have added a GIF below as well._
1. Create a new page/post
2. Add an image block and insert an image, you can choose to edit and crop it or not
3. Add a second image block and before inserting the image use the "Edit Image" button and crop the image, then insert it
4. Once an additional image is added (only if it is cropped before being inserted) then the prior content on the page disappears.

#### What I expected
Image cropping should not cause other content on the page to disappear.

#### What happened instead
By opting to add a second image and cropping it before inserting it to the page then the prior content on that page disappears.

#### Screenshot / Video
![GIF:https://cldup.com/ORnhe3wuJ8.gif](https://cldup.com/ORnhe3wuJ8.gif)

#### Context / Source
#user-report on 2174695-zd

**Comment by Aurorum** [comment]
Seems to almost be a duplicate of #34281

**Comment by xpurichan** [comment]
Thanks much for finding that @Aurorum ! I tried to find an existing report of this of course, but couldn't. I'm closing this in favor of the above existing report.
