### ISSUE TITLE
Plans: Disabled .blog button in /plans

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#34683]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/plans/[site]
2. Make sure you are in the `hideBloggerPlan2` AB Test and `control` variation
3. Click on the "Blogs and Personal sites" tab

#### What I expected
I think this is supposed to be a header and not a disabled button?

#### What happened instead
There's a strange disabled button that says "Only with .blog domains"

#### Screenshot / Video
![Screenshot 2019-07-16 09 44 10](https://user-images.githubusercontent.com/4924246/61313144-b6879e00-a7ae-11e9-8bf1-4a15aac4dd83.png)

**Comment by Aurorum** [comment]
I'm fairly sure that if you have a custom domain which isn't `.blog`, that disabled button appears as you can't upgrade. But with a site without a custom domain, it's a usual button as expected.

<img width="433" alt="Screenshot 2019-07-16 at 18 03 56" src="https://user-images.githubusercontent.com/43215253/61314234-194f5880-a7f4-11e9-90d4-e55839b10bac.png">

Do you have a custom domain?

**Comment by jancavan** [comment]
> Do you have a custom domain?

It appears on sites that either have a custom domain or not.

I updated the issue description to say that this only appears when you have a plan that's higher than Blogger, regardless if you have a custom domain or not.

> that disabled button appears as you can't upgrade.

I see what you're saying. I don't think this is clear to users though. A disabled button should communicate what the possible action would be when it changes to its active state.

In this case, they don't look like the same button in different states - rather, two completely separate buttons.

I think something like this would be much clearer, but I'm open to suggestions:

![Screenshot 2019-07-16 11 13 59](https://user-images.githubusercontent.com/4924246/61318866-e2108580-a7ba-11e9-9c84-2c9ab68cb610.png)

**Comment by dzver** [comment]
I inspected the code and tested the flow, I can confirm that:

- I don't see this button on a clean site with no plans or domains
- I don't see this button if I have a higher tier plan of any kind as written in the description. I see this:

<img width="1033" alt="Screenshot 2019-07-17 at 13 14 31" src="https://user-images.githubusercontent.com/82778/61367688-d72a2380-a894-11e9-8bfa-dd820451554f.png">

- I don't see this button if I have a domain in the shopping cart and there's nothing in the code that checks the cart. 

<img width="1013" alt="Screenshot 2019-07-17 at 13 16 33" src="https://user-images.githubusercontent.com/82778/61367844-296b4480-a895-11e9-8db4-a8e9cd545fd1.png">

- I do see this if I have a custom .live domain that's not part of the plan as it's supposed to be:

<img width="1017" alt="Screenshot 2019-07-17 at 13 19 38" src="https://user-images.githubusercontent.com/82778/61368015-97177080-a895-11e9-8f32-9c5593f27886.png">

Given this research I think that the entire task narrows down to updating the copy of this button.

@jancavan do you mind checking #34711? And also, please LMK if you see another flow that displays the button and shouldn't.

**Comment by jancavan** [comment]
@dzver This is unrelated - why were the plan titles and Premium plan's description translated, but the other texts remain in English?

**Comment by dzver** [comment]
Because the Bulgarian translation is community-driven and has wide gaps. I'm translating from time to time but we have a lot of strings.

**Comment by jancavan** [comment]
> I don't see this button if I have a higher tier plan of any kind as written in the description.

I actually still see the button if I have a higher-tier plan. As you can see in these screenshots, I have a Premium and Business. The other plans have no buttons on them.

![Screenshot 2019-07-22 08 41 55](https://user-images.githubusercontent.com/4924246/61645925-b2e79180-ac5c-11e9-8bbb-0eaacd045701.png)

![Screenshot 2019-07-22 08 42 26](https://user-images.githubusercontent.com/4924246/61645941-ba0e9f80-ac5c-11e9-83c0-648f0203efc4.png)

Although I could have sworn they weren't there the second time I checked.

**Comment by stephanethomas** [comment]
I had a look to this issue as part of the GM Bottle Pickup. The `hideBloggerPlan2` has been ended on July 28th with https://github.com/Automattic/wp-calypso/pull/34906. However, between https://github.com/Automattic/wp-calypso/pull/34711 and p2-p9jf6J-1SA it's not clear to me what exact option has been chosen, and it looks like we're still waiting for feedback from some people. As such, I'll remove it from https://github.com/orgs/Automattic/projects/119.

**Comment by jancavan** [comment]
@stephanethomas Yes, we no longer offer the Blogger plan so we can close this issue.
