### ISSUE TITLE
Calypso: Media date wrong while uploading

### ISSUE THREAD

**Issue by joendotcom** [Automattic/wp-calypso#34723]
#### Steps to reproduce

1. Starting at URL: Any test site > Media > Add New
2. Upload large test file (image/video)
3. Click Edit, check date

#### What I expected

Date shows today

#### What happened instead

Date shows 364 days into the future

#### Browser / OS version

Chrome Version 75.0.3770.142 (Official Build) (64-bit)
OS X 10.13.6

#### Screenshot / Video

Recorded video of issue in action: https://cld.wthms.co/FBONZA

#### Context / Source

#user-report 2174148-zen

**Comment by lancewillett** [comment]
Thanks for the report. A few clarifying questions:

1. Does this happen in WP Admin also?
2. What about other videos or media files (could it be related to the metadata of that particular file)?

**Comment by joendotcom** [comment]
1. Not sure
2. It happened with multiple media files.

Since this only happens _during upload_, it's a real edge. But I reported it on behalf of the user :)
