### ISSUE TITLE
(5P) Block Previews: streamline block editor `BlockPreview` component variants

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#34747]
- We should consider combining the use cases of `BlockPreviewContent` and `BlockPreview` to just `BlockPreview` with a prop to handle scaling. The "Preview" heading should be removed from the component in favor of using it directly as a heading solely in places where it's needed.
  - For details see https://github.com/WordPress/gutenberg/pull/16033#issuecomment-502641040

**Comment by marekhrabe** [comment]
Happening in https://github.com/WordPress/gutenberg/pull/16801
