### ISSUE TITLE
Email: Tab not Selected in Sidebar

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#34744]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/email/site
2. Look at the "Manage" bit of the sidebar

#### What I expected

"Domains" to be selected, as is the case in https://wordpress.com/domains/manage/site

#### What happened instead

Nothing was selected

<img width="255" alt="Screenshot 2019-07-18 at 14 48 21" src="https://user-images.githubusercontent.com/43215253/61462755-1aef5c80-a96b-11e9-9a2f-ec86ddae2c85.png">

**Comment by lamar-frankie** [comment]
Is it safe to say that we can close this issue?

**Comment by Aurorum** [comment]
It's still an issue, I filed a PR in #34745 which would automatically close this issue when merged, but it still needs to be reviewed (and then merged) first. :)

**Comment by lancewillett** [comment]
@sixhours Could you review this one for @Automattic/fixing-the-flows please? There is a pull request waiting: https://github.com/Automattic/wp-calypso/pull/34745
