### ISSUE TITLE
Block Previews: allow passing blocks as an array to block editor BlockPreview

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#34743]
- Currently, the block editor `BlockPreview` component expects `name`, `attributes` and `innerBlocks` props to render the preview.
  - With the goal of exposing this component, it would be better to allow passing blocks as an array instead of these granular props.
  - When scoping this task we should factor in that we'll need to update all existing instances of `BlockPreview` to the new approach.
  - For details see https://github.com/WordPress/gutenberg/pull/16033#pullrequestreview-247002854

**Comment by retrofox** [comment]
handled on https://github.com/WordPress/gutenberg/pull/16033
