### ISSUE TITLE
Missing free for one year copy in domain transfer flow

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#34742]
When trying to map a domain, I see incorrect copy that inbound transfers are free with the plan. They are most likely free for the first year only.

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/domains/add/use-your-domain/TEST_SITE

#### What I expected

Free for first-year only copy

#### What happened instead

Free copy

#### Screenshot / Video

<img width="397" alt="Screenshot 2019-07-18 at 15 40 54" src="https://user-images.githubusercontent.com/82778/61458676-c13f6000-a973-11e9-8173-e2e9c9c37be6.png">

**Comment by xpurichan** [comment]
This appears to have been resolved. For domain transfer-ins we state "Extends registration by one year" now, and for mappings we properly state "Free with your plan, but registration costs at your current provider still apply".

![Screen Shot 2021-05-11 at 11 22 38 PM](https://user-images.githubusercontent.com/33190975/117913656-c9d2fa00-b2af-11eb-8a82-2ca63116ef4f.jpg)
