### ISSUE TITLE
(13P) Block Previews: dynamic responsive scaling of the block editor BlockPreview

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#34749]
- The `BlockPreview` should responsively fill the available space while maintaining the correct aspect ratio based on the true size of the previewed content.

**Comment by frontdevde** [comment]
This issue was created to track the task. There's already a work-in-progress PR here https://github.com/WordPress/gutenberg/pull/16113

**Comment by getdave** [comment]
I got this one.

**Comment by obenland** [comment]
See https://github.com/WordPress/gutenberg/pull/16113
