### ISSUE TITLE
Block Previews: expose block editor `BlockPreview` so it can be used by plugins

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#34748]
- `BlockPreview` would be a useful component for plugin developers that want to show a preview outside the main editor area. We'd thus want to expose it e.g.`wp.blockEditor.BlockPreview`
- For details see https://github.com/WordPress/gutenberg/pull/16834

**Comment by retrofox** [comment]
handled on https://github.com/WordPress/gutenberg/pull/16834
