### ISSUE TITLE
FSE: Remove the edit in customizer option on the navigation block

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34755]
I don't think we should be sending people using our full site editing experience to the customizer. We should be actively trying to remove it from any of our flows.

There is currently an edit button on the navigation block that sends you to the menus section of the customizer. I think this should be removed. The goal of this block is for it to be zero setup. Your pages just appear when you add them, and remove when you delete them. There is nothing to edit.

<img width="651" alt="Screen Shot 2019-07-18 at 1 44 52 PM" src="https://user-images.githubusercontent.com/1464705/61490608-3bff7f80-a962-11e9-8e23-f1fca0c8632e.png">

**Comment by gwwar** [comment]
In terms of technical steps here this might break down into the following:
- [ ] Remove the edit button from the front end of the block https://github.com/Automattic/wp-calypso/pull/34756
- [ ] Out of the box the menu should just appear/update with new pages. So in the render callback, we should make generate our own markup based on existing pages and uncouple any theme menu functions https://github.com/Automattic/wp-calypso/blob/e7c6389499574b6841fb1c21aa479f4c76669dc6/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.php#L91
- [ ] Hide menu functionality in the customizer for these themes.
- [ ] Chat further what we need to build for more advanced cases / types of menus

**Comment by apeatling** [comment]
> Out of the box the menu should just appear/update when pages are added or renamed. So in the render callback, we should generate our own markup based on existing pages and uncouple any theme menu functions

Yes, it should show the pages you've added to your site automatically and bypass the wp_menus system. Right now that would mean only showing "Home", but when you add an "About" page it shows up automatically. If I delete the page it's removed. Zero setup or editing outside of adding or removing pages.

> Hide menu functionality in the customizer for these themes.

I don't think we need to do this, instead we'll hide the customizer for these users. If they are WP savvy and find their way into the customizer and create an actual menu and somehow assign it to the right location in the theme, the block should show that -- so use wp_nav_menu() instead.

> Chat further what we need to build for more advanced cases / types of menus

I think overriding the basic listing of pages is enough, as long as it can be overridden with wp_nav_menu() if a menu has been created and added to the primary location.

**Comment by gwwar** [comment]
> I don't think we need to do this, instead we'll hide the customizer for these users.

So remove the section from the Calypso dashboard? We might need to do an audit for functionality that we're not providing in the block editor yet. For example paid features that only are in the customizer.

**Comment by apeatling** [comment]
I've created an issue in the backlog for removing references to the Customizer: https://github.com/Automattic/wp-calypso/issues/34791

I will create a separate issue to discuss handling missing plan functionality present only in the customizer.

**Comment by apeatling** [comment]
@gwwar Could you break your list out into a new issue?

**Comment by gwwar** [comment]
> @gwwar Could you break your list out into a new issue?

Sure, no problem

**Comment by gwwar** [comment]
Added https://github.com/Automattic/wp-calypso/issues/34793
