### ISSUE TITLE
Vertical: Remove copyright notice from Business template.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#34752]
As we released secondary page templates (about, contact, etc.), we moved on from "one-page" website. Now the copyright notice that only appears on the business homepage template doesn't make a lot of sense, and we need to remove it.

<img width="839" alt="Screen Shot 2019-07-18 at 18 46 11" src="https://user-images.githubusercontent.com/908665/61479948-cbba2380-a98c-11e9-852a-9a3db2b0879f.png">

cc @adamziel @apeatling @michaeldcain

**Comment by michaeldcain** [comment]
I don't think this is valid anymore, given the new starter content.
