### ISSUE TITLE
FSE: Modified Template Part block attributes trigger a blank revision in the page editor

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34751]
I am seeing this notice on my home page in the editor almost 100% of the time:

<img width="1001" alt="Screen Shot 2019-07-18 at 10 43 35 AM" src="https://user-images.githubusercontent.com/1464705/61479984-d30c0d80-a949-11e9-9755-ec0310d2664f.png">

When I look at the revision it wants to restore I'm seeing this blank revision:

<img width="1104" alt="Screen Shot 2019-07-18 at 10 45 18 AM" src="https://user-images.githubusercontent.com/1464705/61480006-db644880-a949-11e9-920f-d8ea7edc0dd4.png">

We should investigate this and make sure it's not a bug. It's possible I am not saving the home page enough, since I've mainly been editing the header template part content. However, seeing a blank revision gives me pause, that shouldn't happen.

**Comment by noahtallen** [comment]
So I'm really digging into this to see if I can ever get a blank revision. Unfortunately, not yet! I think I know why we get the message almost 100% of the time, though.

Two conditions have to both be true to get into the loop:
1. You click "leave" after it tells you you have unsaved changes.
2. When you click leave, it had recently done an autosave of those unsaved changes.

To reproduce:
1. Open a page, and just click into the placeholder where it says "start writing or type / to choose a block":
<img width="798" alt="Screen Shot 2019-07-31 at 11 28 54 AM" src="https://user-images.githubusercontent.com/6265975/62237738-63a10f80-b386-11e9-95e1-f744b8428e4b.png"> That inserts a new paragraph block even if you don't type anything
2. Wait for one minute. At the one minute mark, it should trigger an autosave.
3. Click the back button OR "edit header" (either one will take you away from the page)
4. It will prompt you that you have unsaved changes to see if you want to leave anyways. Click "leave" without saving or publishing or anything like that.
5. Immediately go back to the page and you'll see the autosave revision message. With just clicking into the placeholder, I get the smallest revision I can reproduce so far:
<img width="1074" alt="Screen Shot 2019-07-31 at 11 31 40 AM" src="https://user-images.githubusercontent.com/6265975/62237925-c5617980-b386-11e9-95bf-e645b7a25061.png">

Every time you go back to the page, it will tell you about the autosave revision until you manually "update" or "publish" or "save" the post.

Personally, I think this is not a great flow. I think when you go back, it should always restore the latest autosave in the spirit of always being up to date of your latest changes. That's pretty far out of the scope of this issue, though!

**Comment by noahtallen** [comment]
I wonder if the blank revision could be an edge case where gutenberg (or whatever mechanism) falsely thinks the post is dirty, so the autosave happens, but there aren't any changes to compare in the diff. No clue what that edge case would be though. I'm also trying to modify things like block attributes to see if that would trigger something like that.

**Comment by noahtallen** [comment]
Yay, I was able to trigger a blank revision! You can do it by:
1. Open a page with FSE enabled
2. Select the header template part block. In the sidebar, add an anchor and hit enter:
<img width="1222" alt="Screen Shot 2019-07-31 at 12 02 41 PM" src="https://user-images.githubusercontent.com/6265975/62240305-87b31f80-b38b-11e9-8cf6-1b44d5c24091.png">

3. Open the sidebar again to make sure the anchor is still there
4. Wait at least one minute for the autosave _Note, make sure you didn't make any changes other than the anchor_
5. Navigate away from the page (and click "leave" when it warns you of unsaved changes)
6. Go back into the page and see the revision notice.
7. Click the link to see the revision. It will be blank.

**Comment by noahtallen** [comment]
It should no longer be possible to reproduce this, but feel free to reopen if you notice it again :)
