### ISSUE TITLE
Page Templates: Update "blank" page template to include a grid/columns block by default

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#34750]
With our new "Starter Page Templates" we give customers an option to choose from a set number of pre-defined blocks when creating a page. One of these options is "Blank" which as you can guess starts with no blocks.

Along side this work, we're also adding the ability to display and edit your site's Header/Footer from the new page editor. This means that at some point soon, the "Blank" template will look something like this:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/191598/61467750-29794c00-a94a-11e9-8673-62d7ff7bc2c7.png">

Customers will see their site's header at the top, a default Gutenberg paragraph placeholder ("Start writing..."), and their site's footer at the bottom.

This is a good starting point. But the default paragraph block is really aimed at writing/blogging, and doesn't highlight Gutenberg's ability to create page layouts. This also doesn't do a great job at defining the actual page content area.

One idea I had here was to include the Layout Grid block (you can try it at https://pages.a8ctesting.com under "Tinker Blocks") on our "Blank" template:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/191598/61468827-25e6c480-a94c-11e9-859b-dac27e7ce2f1.png">

The Layout Grid provides a few options by default, including a single column layout, and better defines the page content area.

**Comment by vindl** [comment]
> One idea I had here was to include the Layout Grid block (you can try it at https://pages.a8ctesting.com under "Tinker Blocks") on our "Blank" template:

In my opinion this looks a lot better than the empty space we have now.

One thing that's already present on the blank page and would not be a part of Layout Grid block is page title:

<img width="1118" alt="Screenshot 2019-07-18 at 18 12 46" src="https://user-images.githubusercontent.com/1182160/61473936-d2926780-a987-11e9-9497-0ca50fc87db7.png">

We had to implement some workarounds to get it to show there, so I'm wondering if it should remain visible above Layout Grid block placeholder initially, given that it's not clear to which column it should be assigned in some cases.

**Comment by shaunandrews** [comment]
> We had to implement some workarounds to get it to show there, so I'm wondering if it should remain visible above Layout Grid block placeholder initially, given that it's not clear to which column it should be assigned in some cases.

For now, we can just leave the title (above the Layout Grid block) as-is. Over in [another thread](https://github.com/Automattic/wp-calypso/issues/34728#issuecomment-512538125), I've mentioned that we'll need to consider moving the title at some point.

**Comment by ianstewart** [comment]
Agreed with Marko that this looks better than the blank space presented above but …

> the default paragraph block is really aimed at writing/blogging, and doesn't highlight Gutenberg's ability to create page layouts.

I wonder if this is the problem-to-solve for someone who wants to start with a blank layout versus a template with layouts?

**Comment by shaunandrews** [comment]
Another option to consider is reconsidering our use of a modal for the starter page templates. What if we showed those templates in the content area, like this:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/191598/61485714-d619f480-a96f-11e9-9e4d-629b4f11c2bc.png">

This helps set expectations around where the page content lives.

**Comment by vindl** [comment]
> This helps set expectations around where the page content lives.

Agreed - I think this is important because of overall confusion with different meanings of "page template" that we've created. I suspect that the users will assume that "starter page template" will cover the entire page.

**Comment by frontdevde** [comment]
Issue triage 27-02-2020:
Closing this issue as it's been stale and the FSE experiment has been shelved.
