### ISSUE TITLE
Full Site Editing: add static footer part for Modern Business theme

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34754]
As discussed here https://github.com/Automattic/wp-calypso/issues/34733#issuecomment-512927200, we need to modify the `footer.php` of Modern Business theme to render:

` [Site Name], Proudly powered by WordPress`

However, this should not be part of CPT content.

**Comment by apeatling** [comment]
You will likely need to make some footer style tweaks to left align the message, so that on the front end it looks more like this:

<img width="399" alt="Screen Shot 2019-07-18 at 1 27 34 PM" src="https://user-images.githubusercontent.com/1464705/61489583-e3c77e00-a95f-11e9-9d9c-a7ae0d4901af.png">

**Comment by vindl** [comment]
> However, this should not be part of CPT content.

Any concerns about this, given that this will be the only part that's not visible in the editor atm?

**Comment by apeatling** [comment]
Yes, I think it needs to be in the editor as a block in a future iteration. I'm not concerned about it for the first release though.

**Comment by apeatling** [comment]
Created an issue for that here https://github.com/Automattic/wp-calypso/issues/34760
