### ISSUE TITLE
FSE: Create a block for handling the Powered by message

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34760]
On WordPress.com we include a message in the footer that is not visible in the editor, even with full site editing:

<img width="571" alt="Screen Shot 2019-07-18 at 3 10 38 PM" src="https://user-images.githubusercontent.com/1464705/61495621-54759700-a96e-11e9-9ee1-c965ea8b2551.png">

For higher paid plans it is possible to remove this message, and for all plans it is possible to adjust what this message says.

All of these settings are in the customizer. We need to build a block to port these settings to the block editor, and also then allow customers with higher paid plans to hide the message without getting lost in the customizer (which we are mostly hiding).

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
