### ISSUE TITLE
Onboarding: Verify email address before publishing conflicts with checklist

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/wp-calypso#34776]
#### Steps to reproduce

1. Create a new site __with a brand new account__
2. At the end of the onboarding process, you will have a checklist with the first item being "Update Your Homepage". You will also have banners scattered around Calypso (e.g. /plans/) telling you to "Update Your Homepage"

#### What I expected

Being able to actually update my homepage...

#### What happened instead

I have an error message (😱) in the editor telling me to validate my email address first if I want to be able to publish anything.

Bear in mind that "Validate your email" is in the checklist, but it's the last step.

This is quite contradictory.

#### Screenshot / Video

![Screenshot 2019-07-19 at 12 15 40](https://user-images.githubusercontent.com/177929/61531772-bd691780-aa1f-11e9-945d-1cecd388d9a8.png)

![Screenshot 2019-07-19 at 11 43 16](https://user-images.githubusercontent.com/177929/61531779-c35ef880-aa1f-11e9-9b7e-abb744b88719.png)

![Screenshot 2019-07-19 at 11 44 17](https://user-images.githubusercontent.com/177929/61531792-cb1e9d00-aa1f-11e9-9274-a8571ceadea5.png)

**Comment by jblz** [comment]
This is should be solved when private by default lands.

**Comment by sixhours** [comment]
Looks like we can close this since PBD landed.
