### ISSUE TITLE
Buying a Plan From a Free .blog Subdomain Renders Strange Text

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#34779]
The thank-you screen is unexpected

#### Steps to reproduce
1. On a test that has a free .blog subdomain, buy Premium
2. The thank you screen would treat the .blog subdomain as a domain registration

#### What I expected

The copy should suggest getting a free domain

#### What happened instead

The copy is incorrect - it says that the free domain is the one included in my plan.

#### Screenshot / Video

<img width="748" alt="Screenshot 2019-07-19 at 16 12 47" src="https://user-images.githubusercontent.com/82778/61537653-51e37200-aa40-11e9-9b2d-7553aaa53d6c.png">

#### Context / Source

**Comment by klimeryk** [comment]
<img width="727" alt="Screenshot 2021-02-09 at 22 04 26" src="https://user-images.githubusercontent.com/3392497/107434531-cc904880-6b22-11eb-9557-9aa5bfdab4ad.png">

Could not reproduce anymore 👍 Possibly the improved check mentioned in https://github.com/Automattic/wp-calypso/issues/34775#issuecomment-776273075 fixed this issue as well.
