### ISSUE TITLE
Onboarding: "Purchase required" badge looks misaligned

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/wp-calypso#34773]
#### Steps to reproduce
Simply create a new site and you will notice it at Step 1 of 6

#### What I expected

The left-hand side of the badge to be aligned with the rest of the text

#### What happened instead

The content of the badge is aligned with the rest of the text which means that the left-hand side of the badge is overflowing.

#### Screenshot

![Screenshot 2019-07-19 at 11 34 16](https://user-images.githubusercontent.com/177929/61530151-30bc5a80-aa1b-11e9-980b-ea16f36bfa8a.png)

#### Context / Source

It might just be me but it looks a bit odd.

Have we considered having the label and the badge side by side?

![Screenshot 2019-07-19 at 11 52 47](https://user-images.githubusercontent.com/177929/61530386-d2dc4280-aa1b-11e9-9ebd-862ec6b2eb01.png)

**Comment by p-jackson** [comment]
For context, the discussion about alignment happened on #33544 when this was added. Which doesn't mean the way it is is set in stone of course!

Got an idea on what direction we should take @monikaburman?

**Comment by monikaburman** [comment]
Based on #33544 it seems the alignment of the pill causes some type of awkward alignment/misalignment of the text. It's entirely subjective, so while some may see the pill overhang as a mistake, the misaligned text could be interpreted similarly. I suggest we close this; it is working and appearing as-designed.

**Comment by sixhours** [comment]
Marking this as "wontfix" per the above comments. Thanks all!
