### ISSUE TITLE
Inconsistent Personal Plan Upsell in Manage Domains

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#34775]
#### Steps to reproduce
1. On a site with a free .blog subdomain and no upgrades or domains, go to /domains/manage
2. The wording says that I can use the plan with the existing domain

#### What I expected

The wording is incorrect because I can't use it with an existing domain even if I had one.

#### What happened instead

This nudge is inconsistent. It's visible by some sites and not visible by others. The message is incorrect. It needs to be reworked and A/B tested because purchasing a domain currently adds Premium and not Personal.

#### Screenshot / Video

<img width="1037" alt="Screenshot 2019-07-19 at 14 09 54" src="https://user-images.githubusercontent.com/82778/61531327-36bc3680-aa2f-11e9-83fb-80d1925c0cba.png">

on a site with a .wordpress.com domain

<img width="1023" alt="Screenshot 2019-07-19 at 14 28 36" src="https://user-images.githubusercontent.com/82778/61532144-987da000-aa31-11e9-9cd7-66527b57638d.png">

**Comment by klimeryk** [comment]
I've checked and the `isWPCOMDomain` check (that was failing before for .blog subdomains) has been fixed and the upsell is not shown in those cases anymore.
