### ISSUE TITLE
Full Site Editing: template warning on Dotcom sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34784]
When editing the page with FSE enabled I'm seeing the following notice on Dotcom:

<img width="583" alt="Screenshot 2019-07-19 at 16 32 51" src="https://user-images.githubusercontent.com/1182160/61544248-4f374b80-aa45-11e9-878c-1308ee5817f8.png">

This should be removed in FSE context. It seems to be coming from core's `template-validation-notice`. Not sure why it's not showing up on self hosted sites though.

Confirmed while testing D30622-code, it can be reproduced by following the steps outlined there.

**Comment by noahtallen** [comment]
Another couple of findings:
- It does not show up when you make a new page with the patches active, but it does show up when editing any page, including after you've published a new page.
- While this error shows up, the FSE template part blocks are not visible
- While the error is there, the styles of the page are messed up, as if it didn't finish rendering.

**Comment by apeatling** [comment]
Confirmed I also see this as described by @noahtallen

**Comment by mmtr** [comment]
I actually believe the invalid template warning is being displayed for valid reasons and we should fix that instead :)

We use the content of the FSE template as the editor template ([#](https://github.com/Automattic/wp-calypso/blob/d05a79ff74bac431ff30a2e74dab54746cc39475/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L572-L578)).

Note that the FSE template is still using the `align` attributes ([#](https://github.com/Automattic/themes/blob/904bffbea60a929cb9c027446e0b21fe1ce6af32/modern-business/inc/fse-template-data.php#L131-L135)), but those attributes are no valid anymore after https://github.com/Automattic/wp-calypso/pull/34691. 

That means that the attributes of the blocks will be striped out when saving the page, diverging from the editor template defined and triggering the invalid template error.

**Comment by noahtallen** [comment]
That definitely makes sense :P We could also be missing out on other bugs that the template validity check is supposed to catch.

What about that one gutenberg core issue about nested blocks with template locks?

**Comment by noahtallen** [comment]
I opened a theme PR here: https://github.com/Automattic/themes/pull/1103 to fix one of the issues. We probably still have to care about the gutenberg issue, so our first fix may still be needed.

**Comment by noahtallen** [comment]
I can confirm that on a local install, the

**Comment by noahtallen** [comment]
RIP me! Anyways, I can confirm that on a local install, the old suppression code (`domReady`) does in fact suppress the warning that the theme generates. I can comment out the suppression code, run the theme with the invalid template, and the error shows up. As soon as I turn on the old suppression code, the error goes away. After I fixed the issue on the theme side, the error does not show up even with the suppression code off.
