### ISSUE TITLE
Jetpack checklist: Scan incorrectly says turned on for Personal plan

### ISSUE THREAD

**Issue by robertbpugh** [Automattic/wp-calypso#34787]
I just set up a Jurassic Ninja site and bought a personal plan. It says in my checklist that scan is turned on. But then I go to the security dashboard and it’s not enabled, I think that’s correct since scanning is a Premium feature. If that’s right, would need to update that copy in the checklist for Personal plan users.

![image](https://user-images.githubusercontent.com/52668747/61549587-6151c380-aa1e-11e9-942e-5acd1107b128.png)

![image](https://user-images.githubusercontent.com/52668747/61549601-7169a300-aa1e-11e9-9193-52c2e98e72d9.png)

**Comment by davipontesblog** [comment]
Moved to Jetpack Improved Onboarding for triaging.

**Comment by robertbpugh** [comment]
Closing this since we don't have a Personal plan anymore.
