### ISSUE TITLE
FSE: Handle plan features from the Customizer when the Customizer is hidden

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34792]
With sites supporting full site editing, we are going to be hiding the customizer because it presents a very confusing experience for users. See https://github.com/Automattic/wp-calypso/issues/34791 for what this will take.

For our business themes and design system based themes this means losing access to the custom css functionality. There is no other WordPress.com plan functionality in the customizer for these themes. 

If a user switches to a different theme that extends the customizer, then all customizer links will reappear, so we are covered there. 

If they install a plugin that extends the customizer but stick to a full site editing theme, they will not be able to easily access this.

So two questions to work through: 

* How do we provide access to custom css?
* What do we do in the case of a user installing a plugin that extends the customizer?

**Comment by apeatling** [comment]
> How do we provide access to custom css?

One option here is to provide an "edit css" link somewhere in our experience that opens this page in the customizer, but disables all other menus.

**Comment by gwwar** [comment]
@apeatling This one is likely going to be pretty big. I think we need an audit first. It's not just custom CSS.

> How do we provide access to custom css?
> One option here is to provide an "edit css" link somewhere in our experience that opens this page in the customizer, but disables all other menus.

I'd like to avoid trying to disable pieces of the customizer. It's confusing, hard to maintain and folks don't really like the approach with the plugins section.

I think a Gutenberg sidebar extension would make sense for CSS support. Folks might be able to see changes in the FSE then. That is of course a larger project outside the scope of this sprint though. In the meantime keeping it in the Customizer probably makes sense.

> What do we do in the case of a user installing a plugin that extends the customizer?

We can put a warning in the customizer if folks are using new flows, but I don't see any reason why we would stop folks from using the customizer, esp if they installed a plugin to extend functionality.

**Comment by mattwiebe** [comment]
> How do we provide access to custom css?

We still have the creaky, old version of Custom CSS running on dotcom under `wp-admin/themes.php?page=editcss`. (We still link there from the Customizer because the interface there still shows revisions.) It only previews in a separate window and you can't see your edits in realtime but it works. 

That being said I don't think we especially want to use it.

> What do we do in the case of a user installing a plugin that extends the customizer?

We could have a simple blacklist of sections and/or controls that we want to unregister in the Customizer. This would get rid of the things we know we want to get rid of, while leaving things like Custom CSS and whatever gets installed via plugin.

**Comment by apeatling** [comment]
Closing this one in favor of: https://github.com/Automattic/wp-calypso/issues/35173
