### ISSUE TITLE
FSE: prefix function names and follow plugin best practices

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34795]
Let's remember to prefix function names, `a8c_` should probably do the trick, but let us know if folks had other suggestions.

https://developer.wordpress.org/plugins/plugin-basics/best-practices/#prefix-everything

cc @Automattic/ajax @Automattic/cylon @Automattic/serenity

**Comment by apeatling** [comment]
I think this should be in the current sprint. It shouldn't take a lot of work to add prefixes to block function names. Everything inside a class is fine, we just need to prefix the class name.

**Comment by gwwar** [comment]
Sure, let's try to frontload this cc @Automattic/ajax since this might also affect the team's work

**Comment by obenland** [comment]
Our PHP requirements allow us to use proper namespaces even. `A8C\FSE`?

**Comment by vindl** [comment]
> Our PHP requirements allow us to use proper namespaces even. A8C\FSE?

I think we could use namespaces too (min 5.3) since our plugin requirements are 5.6+. The same holds true for Jetpack now.
