### ISSUE TITLE
Google Apps: Offer font mismatch

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3479]
The fonts between the price and the subtext after the divider look a bit off.

#### URL: 
/domains/manage/:domain/email/:site

#### SS:
![image](https://cloud.githubusercontent.com/assets/991022/13234534/f29d8192-d96d-11e5-96b7-2917eaa6e335.png)

/cc: @breezyskies

**Comment by BandonRandon** [comment]
This is still the case, Adding the tag Good first bug, as this should a fairly simple fix.

**Comment by breezyskies** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/5588.
