### ISSUE TITLE
Do we need to keep the "include this CSS in the mobile theme" option for simple WP.com sites? 

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#34798]
Do we need to keep the "include this CSS in the mobile theme" option for simple WP.com sites? It doesn't appear for Jetpack-connected sites (including Atomic), and this disparity can cause some confusion. 

In addition, when more tech-savvy users enter CSS for the mobile theme, there's sometimes confusion around why it's not working (the option's disabled by default).

Is there any way to make the `.mobile-theme` selector work in custom CSS without selecting the "include this CSS in the mobile theme" option? If not, can it be enabled by default? 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize/
2. Navigate to the Customizer's CSS panel.
3. Scroll down to see the "include this CSS in the mobile theme" option.

#### Screenshot

<img width="301" alt="Screenshot 2019-07-20 at 14 56 38" src="https://user-images.githubusercontent.com/2998162/61578380-ae0ccb80-aafe-11e9-988a-2fe4113fa34d.png">

More discussion around [the documentation for the mobile theme](https://en.support.wordpress.com/themes/mobile-themes) in https://github.com/Automattic/en.support-docs-content/issues/381.

**Comment by davipontesblog** [comment]
closing this in favor of https://github.com/Automattic/wp-calypso/issues/36322 .
