### ISSUE TITLE
Showcase: No Preview on Theme Showcase

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#34804]
#### Steps to reproduce
1. Access the theme's showcase on WordPress.com.
2. Find the Redhill theme.

#### What I expected
To show a screenshot like other themes.

#### What happened instead
It doesn't show its screenshot, as follows:

![RedhillTheme](https://user-images.githubusercontent.com/16104522/61598270-716dcc80-abf1-11e9-9ef0-f86a4cf6fc8b.png)

It seems that the image is missing:

https://i0.wp.com/jhnstndec13d.wpcomstaging.com/wp-content/themes/pub/redhill/screenshot.png

I noticed that once you click on a theme, and then click on Back to the theme's showcase, the preview shows. But then the image's address is different:

https://i2.wp.com/s2.wp.com/wp-content/themes/pub/redhill/screenshot.png

Which is an URL that works.

#### Browser / OS version
Chrome 75.0.3770.142
OS X 10.13.6

#### Context / Source
#dogfooding

Originally reported here: https://github.com/Automattic/themes/issues/1112.

**Comment by davidakennedy** [comment]
I wanted to follow up here and provide some more context as to what I've tried to help troubleshoot this:

- First, I re-indexed the Elasticsearch Index for the WordPress install that powers the theme showcase. That worked Friday, as Redhill and Varia both had working screenshots. But whatever is causing the bug has reappeared again.
- This morning, I nuked the Photon cache for the specific image for the Redhill screenshot. That doesn't seem to help. 
- This came up previously in the past week or two with Radcliffe 2 and Coherent. I solved it by the Radcliffe 2 one by uploading a new screenshot and re-indexing the Elasticsearch Index. I solved Coharent by just re-indexing the Elasticsearch Index.

Currently, this is also happening for Redhill, Varia and Twenty Sixteen. All three have screenshots uploaded.

**Comment by jhnstn** [comment]
`jhnstndec13d.wpcomstaging.com` is my test WordPress.com Business site. I have been using it to test out changes to our Business site infrastructure but I have no clue how that would make this site the source for the screenshots on the theme showcase.

**Comment by davidakennedy** [comment]
This should be fixed, thanks to re-indexing the Elasticsearch Index in a different way.
