### ISSUE TITLE
Signup: Stuck with Business/eCommerce plans after switching to a different segment

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#34818]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/
2. Select the "Online Store" segment
3. Find and select a domain, click "Back" and be taken to Step 1 again
4. Select a different segment that's not "Online Store"

#### What I expected
To be shown all the other plans - eg: Picking the "Blog" segment would display all the other lower-tier plans

#### What happened instead
I'm stuck seeing Business and eCommerce plans

#### Browser / OS version
Google Chrome Version 75.0.3770.142
MacOS Mojave 10.14.2

#### Screenshot / Video
https://cloudup.com/c2kEkexQRrW

cc @creativecoder @michaeldcain

**Comment by ramonjd** [comment]
Having trouble reproducing this. I'll throw it on our board so we can investigate further.

**Comment by ramonjd** [comment]
Given the recent improvements/bug fixing to the flow forking here, I think we can close this issue. 

 @jancavan Can you reproduce on production any more?

cc @andrewserong

**Comment by jancavan** [comment]
@ramonjd Thanks for asking. I checked again and could no longer repro. Closing this issue.
