### ISSUE TITLE
Checkout: Ad blocker breaks checkout

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3484]
#### Steps to reproduce
1. Block domain `www.googleadservices.com`.
2. Add a domain to cart (Other items may work)
3. Open console
4. Proceed with the checkout

It throws on https://github.com/Automattic/wp-calypso/blob/master/client/analytics/ad-tracking.js#L173 with undefined function error. The button stays disabled as if it's processing, and never redirects to thank you page.

**Comment by mattm** [comment]
Created a PR to prevent this error in #7385.

**Comment by umurkontaci** [comment]
Fixed in #7385
