### ISSUE TITLE
full-site-editing returns a PHP fatal if Jetpack is disabled

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#34840]
Since the latest 0.4 update we have seen some instances where Atomic sites with Jetpack disabled seems to crash due to full-site-editing:

`PHP Fatal error:  Uncaught Error: Class 'Jetpack_Options' not found in /wordpress/plugins/wpcomsh/2.4.33/feature-plugins/full-site-editing.php:85`

This seems to come from wpcom_fse_global_editors_script which was introduced on https://github.com/Automattic/wp-calypso/pull/34655 in order to add site meta data for Gutenberg Tracking. 

#### Steps to reproduce
1. Starting at URL: yoursite.com (Atomic site) . Note that the plugin will be pre-installed and automatically updated.
2. Deactivate jetpack via CLI with `wp plugin deactivate jetpack`
3. See Fatal.

Edit: Added on 304-gh-automattic-wpcomsh

**Comment by vindl** [comment]
cc @Automattic/ajax
