### ISSUE TITLE
Gutenberg: AT sites with denied plugins can switch to the block editor

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#34856]
We're currently allowing JP/AT sites to switch to the block editor even if they have activated a denied plugin for Gutenframe (see PCYsg-lOu-p2 for information about denied plugins).

Under these conditions, JP users will get WP Admin flows (the opt-in API will return `gutenberg-redirect` as the value for the selected editor) and AT sites will get Calypsoified WP Admin flows (`gutenberg-redirect-and-style`). 

Since the denied plugins can navigate the user away from the editor, we should ensure AT users won't get Calypsoify flows (which are intended to keep the user in the editor only). JP users are not affected by this (they don't get Calypsoify flows).

We could do two things to fix this:
- Make sure the user of an AT site cannot switch to the block editor if the site has a denied plugin active.
- Make sure the opt-in API (`/wpcom/v3/sites/:site/gutenberg`) returns `classic` as selected editor for AT sites having a denied plugin active.

**Comment by mmtr** [comment]
> Make sure the opt-in API (`/wpcom/v3/sites/:site/gutenberg`) returns `classic` as selected editor for AT sites having a denied plugin active.

Just opened D30746-code to take care of this task.

**Comment by gwwar** [comment]
Not sure if I understand the issue here fully but I'll note some higher level issues that we should resolve that might explain weird behavior:

- Atomic sites depend on the Classic Editor plugin for opt-in preferences on the wp-admin side of things. This doesn't map neatly, and also has one extra level of customizability. It's opt-in per site, per user, and per post
- Calypso views are still powered by the opt-in API and may get out of sync
- When a site uses a plugin that's incompatible with an iframe we try to redirect folks to wp-admin

**Comment by mmtr** [comment]
Thanks for those notes, @gwwar.

> When a site uses a plugin that's incompatible with an iframe we try to redirect folks to wp-admin

This is the issue I wanted to highlight here, but probably I should've include some clear steps to reproduce in order to make this easier to understand 🙂 

Try this:
- In an AT site eligible for Gutenframe, activate a denied plugin such as Elementor.
- Go to `/block-editor`.
- Because of the denied plugin, you'll be redirected to the calypsoified WP Admin editor, so the user still thinks they are in Calypso.
- This editor will contain an "Edit with Elementor" button in the header.
- If you click on it, you'll get the Elementor's plugin UI calypsoified with the styles messed up.
- From there, we don't have any control and the user might navigate to other sections of the WP Admin which can increase the confusion and no clear way to go back to Calypso.

Shouldn't we prevent the user from navigating to other WP admin pages from the calypsoified WP Admin editor in order to avoid unexpected calypsoified flows?

**Comment by mmtr** [comment]
> Shouldn't we prevent the user from navigating to other WP admin pages from the calypsoified WP Admin editor in order to avoid unexpected calypsoified flows?

My suggestion to prevent this is to keep the user in Calypso using the classic editor (done in D30746-code).

But we should also ensure the user cannot switch to the block editor from the classic editor under these circumstances (since we'll redirect them back to the classic editor), which is what's handled in https://github.com/Automattic/wp-calypso/pull/34858.

**Comment by kwight** [comment]
> My suggestion to prevent this is to keep the user in Calypso using the classic editor if they have any conflicting active plugin (done in D30746-code).

This was my assumed best solution too, but with user confusion from the reverted deploy, maybe the best (also sub-optimal 🙃) solution is both Jetpack and Atomic get `gutenberg-redirect` (no Calypsoify)?

**Comment by mmtr** [comment]
> This was my assumed best solution too, but with user confusion from the reverted deploy, maybe the best (also sub-optimal 🙃) solution is both Jetpack and Atomic get `gutenberg-redirect` (no Calypsoify)?

Or leave it as it is given we have not received any real feedback from users complaining about this 🙂. As per our conversation in p1564612367428500-slack-serenity, we're dropping this for now, until we can give the whole Calypsoify mess proper time to sort out.

Although this issue was intended to also hide the opt-in prompts on unsupported AT sites in the desktop app (in order to prevent the behavior noted in https://github.com/Automattic/wp-calypso/pull/34833#issuecomment-514420024), but I'll create a separate issue to fix that.
