### ISSUE TITLE
FSE: Navigation Block renders empty on Simple Sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34853]
Create a new site using WordPress.com/start, pick anything but "blog" as the segment.

Then add the `full-site-editing` sticker to your Simple Site with the Modern Business theme. In the header try to add a navigation block. It renders empty content instead of the primary menu.

<img width="812" alt="Screen Shot 2019-07-23 at 2 27 28 PM" src="https://user-images.githubusercontent.com/1270189/61748950-5cf71480-ad56-11e9-8e22-ee3f908df00b.png">

<img width="1270" alt="Screen Shot 2019-07-23 at 2 28 12 PM" src="https://user-images.githubusercontent.com/1270189/61748991-78fab600-ad56-11e9-8f1c-2d5d6e2dad39.png">

**Comment by vindl** [comment]
Some info also available in https://github.com/Automattic/wp-calypso/issues/34865 which seems to be a duplicate.
