### ISSUE TITLE
Stats: Discrepancy between stats in desktop browser and Android browser

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#34861]
A user reported that Stats when viewed in a desktop browser reflect very different stats to those displayed in a browser on their Android phone.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/URL?startDate=2019-07-23
2. According to the Stats for 23 July when viewed in the browser, the site didn't receive any visits.
3. When the user compared this with Stats on their Android phone, they saw that the Android phone reflected visitors on this day.

#### What I expected

Stats reflected in the dashboard when viewed in a desktop browser should mirror what a user sees on their phone.

#### What happened instead

The dashboard, when viewed in a browser, doesn't reflect any traffic on 23 July. The Android phone, however, does.

#### Browser / OS version

The user's User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

Verified on macOS 10.14.5, using Firefox Developer Edition v69.0b6.

#### Screenshot / Video

In the browser:

![2203293_Browser_stats](https://user-images.githubusercontent.com/2912202/61797981-2d690a80-ae31-11e9-961a-6264f9c07a1a.png)

Android Stats view:

![2203293_Android_app_stats](https://user-images.githubusercontent.com/2912202/61798000-3528af00-ae31-11e9-8120-eb9fd7910d04.jpg)

#### Context / Source

This is a user report - 2203293-zen

**Comment by tanjoymor** [comment]
Are there any updates for this? The ticket has just come off hold again after a 7 day hold period...

**Comment by katiebethbrown** [comment]
I noticed that in the screenshots there are different dates highlighted, so I've asked the user to check again to see about which dates specifically show a discrepancy.

They are using the browser (and not the app) so these should just be two different formats of the same page. It sounds like they just selected different dates accidentally.

**Comment by katiebethbrown** [comment]
User responded and they aren't seeing the discrepancy any longer, so it's possible that we were just comparing two different days. I'm marking this issue as closed.
