### ISSUE TITLE
Editor: Password Protected/Private Posts default to "Public" upon editing them

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3486]
#### Steps to reproduce
1. View a password protected post or a private post with edit permissions
2. Click "Edit"
3. Click post visibility

#### What I expected

Post should still show password protected or private

#### What happened instead

Post shows public
Upon saving it seems the private still 

#### Browser / OS version

Chrome/Firefox/Safari OSX 10.11.3

#### Screenshot / Video

![editing password post](https://cloud.githubusercontent.com/assets/128826/13238446/be79cdd8-da1e-11e5-8e0c-af09a045b246.gif)

**Comment by jeremeylduvall** [comment]
Should be fixed via #3628. Somewhat related new issue started in #3673. Closing this one though!
