### ISSUE TITLE
FSE: Header template part has extraneous UI for group block

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#34887]
Our current Header template part uses a Group block to contain all the elements in the Header.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/191598/61888927-7a50ed80-aed2-11e9-8ab6-99d4d565d9fd.png">

This adds an extra click to edit anything in the Header, which creates some confusion. Also, the settings for the Group block allow a customer to add a background color which "breaks" the design.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/191598/61888984-a2d8e780-aed2-11e9-9cb1-cb1025662f57.png">

There's also the ability to add a new block _outside_ of this group using the default inserter.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/191598/61889075-c69c2d80-aed2-11e9-921b-852eea96cfd6.png">

Doing so will break the layout of the site.

I suggest we remove the ability to interact with the parent Group block. That is, a customer should not be able to focus the Group block, nor update its settings in the sidebar. There's also an extra inserter button that appears at the bottom-left of the Group block — we should also remove this.

Similar, we should remove the ability to add blocks outside of this Group block.

**Comment by shaunandrews** [comment]
Turns out once you interact with that inserter below the Group block its impossible to remove it. I now have an empty placeholder in my site's header:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/191598/61889757-06174980-aed4-11e9-8f62-ea3b8ded264d.png">

**Comment by gwwar** [comment]
> I suggest we remove the ability to interact with the parent Group block.

This likely needs to be specific to the theme/header content. Folks may want to look into the Gutenberg template block API, where we can lock down specific elements.

https://developer.wordpress.org/block-editor/developers/block-api/block-templates/

How blocking is this @shaunandrews ?

**Comment by apeatling** [comment]
The only reason we need the group block is to apply the css classes that the theme needs. If we can find a way to apply the class names without the group block, that might be the easiest direction.

**Comment by shaunandrews** [comment]
Here's a related Gute issue mentioning the need for this same functionality: https://github.com/WordPress/gutenberg/issues/7469
