### ISSUE TITLE
FSE: Header blocks are rendered with different spacing on the frontend

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#34890]
I've noticed that the spacing for elements when editing the Header template part is different from what's rendered on the front end. Here's two screenshots over-layed to show the spacing and letter-spacing differences:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/191598/61893278-b2106300-aedb-11e9-94b8-512c707276a8.png">

I know this problem exists just about everywhere in Gutenberg, but I wonder if there's anything we can do to make it look closer to reality.

**Comment by gwwar** [comment]
As a general note to folks. To avoid an issue that can never be closed lets target issues/fixes to specific themes/scenarios. I'll assume this one is for Modern Business.

We 💯want to fix these, but to be actionable we'll need to file small issues that clearly state what themes/content causes the problem.

**Comment by apeatling** [comment]
This is a tough one, and I'd advocate for not dealing with this in the sprint, other than this one:

<img width="1131" alt="Screen Shot 2019-07-29 at 4 15 53 PM" src="https://user-images.githubusercontent.com/1464705/62089047-5405b780-b21c-11e9-8011-b4acaa8e0c4e.png">

**Comment by apeatling** [comment]
I'll work on this extra space.

**Comment by apeatling** [comment]
Unassigned myself on this one, so free to pick up. Also wanted to make it clear that for the v1 launch this should only focus on removing the space as shown here: https://github.com/Automattic/wp-calypso/issues/34890#issuecomment-516197699
