### ISSUE TITLE
Re-instate wpcom_admin_page_view tracking

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#34898]
The file containing that event was removed in D22403-code. Let's bring it back as a file in `tracks/hooks`, as described in pa1C6h-wH-p2#comment-2960

**Comment by mmtr** [comment]
Added the event back in D31617-code. Will close this issue once that diff lands.

**Comment by mmtr** [comment]
We're tracking `wpcom_admin_page_view` events again after landing D31617-code and D31655-code.
