### ISSUE TITLE
Adding images to pre-existing Gallery Block in Portfolios erases pre-ecisting image's 

### ISSUE THREAD

**Issue by bsanevans** [Automattic/wp-calypso#34903]
#### Steps to reproduce
1. Starting at URL:
2.
3.
4.

**Comment by zdenys** [comment]
It seems the incomplete version of https://github.com/Automattic/wp-calypso/issues/34904

**Comment by bsanevans** [comment]
Oops, sorry about that! 🙇🏻‍♂️I have no idea how that happened. 😅
