### ISSUE TITLE
Adding images to pre-existing Gallery Block in Portfolios erases pre-existing images' captions

### ISSUE THREAD

**Issue by bsanevans** [Automattic/wp-calypso#34904]
#### Steps to reproduce
1. Create a Portfolio in Calypso with a Gallery, add some images, give captions and publish.
2. Close the Portfolio and reopen it in the editor.
3. Add a new image to the pre-existing gallery.
4. Captions added to pre-existing images in the gallery will get erased. However, captions pre-annotated to images in Media will not get erased.
5. The issue does not happen when using the Gallery Block in Posts, but can be reproduced on Pages and Portfolios.

#### What I expected
Captions should remain, even after attempting to add a new image.
Happened on User site and was able to reproduce it on my test site.

#### Screenshot / Video
https://d.pr/fDcxaW

#### Context / Source
#user-report
#14212162-hc

**Comment by Robertght** [comment]
Found another one in #15706287-hc/ #2397497-zen

**Comment by kriskarkoski** [comment]
#18048879-hc

**Comment by rachelwinspear** [comment]
Another case here: #2725984-zen

**Comment by retnonindya** [comment]
Another case: #2745398-zen

**Comment by cathymcbride** [comment]
@bsanevans are you still able to repro this? I am not seeing it.

**Comment by bsanevans** [comment]
I've tested again and I can no longer reproduce the issue ether. Looks like something fixed this in the last 5 months or so 😃 Closing for now.
