### ISSUE TITLE
Checkout: Prevent Items from being removed on Submit

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#3491]
#### Steps to reproduce
1. Starting at URL:  /checkout
2. Add a product to your cart.
3. Proceed to the "complete your purchase page"
4. Click the "X" to remove the upgrade
5. Watch as the price goes down to $0 
#### What I expected

Not to be able to remove products after clicking submit
#### What happened instead

The products appear to be removed from cart. However, the upgrade went through. 
#### Browser / OS version

Chromium 48 / Linux Mint (Ubuntu 14.04)
#### Screenshot / Video

https://cloudup.com/cXtpKSGhxP2

Related #221 #2353

**Comment by alxblock** [comment]
Since this doesn't seem like an issue for a majority of users, I'm closing this issue for now.
