### ISSUE TITLE
Full Site Editing: update Elegant Business header

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#34915]
We need to update Elegant Business header to support FSE styling in the editor and if necessary while rendering FSE footer on the front end. While doing that we should make sure that we don't cause regressions for existing header and layout - when FSE is disabled the theme should fall back to original header.

For analogous example, you can check out how this has been done for the Friendly Business header in: Automattic/themes#1058

**Comment by noahtallen** [comment]
Closed in favor of #34916
