### ISSUE TITLE
Theme Showcase: Brompton missing 'Open Live Demo' button

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#34922]
The Brompton theme is missing the `Open Live Demo` button in the showcase.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/brompton/

#### What I expected

Should have the demo button here:

![img](https://cld.wthms.co/ynbdlG+)

The demo link is here: https://bromptondemo.wordpress.com/?demo

**Comment by lancewillett** [comment]
I'm seeing the link from a request like this when I have a site active: `https://wordpress.com/theme/brompton/lancetest14.wordpress.com`:

Testing with Safari on macOS:

<img width="1392" alt="Screen Shot 2020-04-14 at 14 47 30" src="https://user-images.githubusercontent.com/66797/79277556-e4ddfb00-7e5e-11ea-839f-79756f739e3b.png">

Clicking the link opens a live demo:

<img width="1392" alt="Screen Shot 2020-04-14 at 14 47 27" src="https://user-images.githubusercontent.com/66797/79277590-f6bf9e00-7e5e-11ea-9792-971a3567326c.png">

---

There is a possible bug — when loading the same theme page without choose a site first: `https://wordpress.com/theme/brompton`

```
TypeError: null is not an object (evaluating 'Object(je.a)(e).URL')
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'Object(je.a)(e).URL')
```

The result is a blank page.

**Comment by lancewillett** [comment]
Tracking the bug in a separate issue: https://github.com/Automattic/wp-calypso/issues/41118

**Comment by michaeldcain** [comment]
@lancewillett: I actually think this is unrelated to #41118, and is rather a ES indexing issue that sometimes happens with the pages that power the showcase endpoint. I bet someone queued a manual re-indexing in the time since this was reported.
