### ISSUE TITLE
FSE: Editing a template part often pop's a browser alert about unsaved changes.

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#34926]
If you go to create a new page, and then from that new page click the "Edit Header" button you'll often see a rather scary alert from your browser:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/191598/61977256-fa06b700-afbb-11e9-8e88-4e21fdd8a176.png">

In chrome, the alert is even scarier as it mentions unsaved changes:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/191598/61977942-d3e21680-afbd-11e9-8b3e-02014b3ba92b.png">

This happens if you try to edit the template part before an auto-save kicks in, but also if you make changes between auto-saves. To reliably see the alert:

0. Ensure the latest FSE plugin is activated.
1. Create a new page.
2. Choose any template.
3. Click the Edit Header button.

At this point you should get the scary browser alert.

**Comment by gwwar** [comment]
@apeatling @shaunandrews  This is the unsaved changes alert, removing this might include content loss. Do you want to update this flow only for default content population (might be hard to detect)?

We could maybe investigate if it's possible to force an autosave before navigation.

**Comment by apeatling** [comment]
I think forcing a save before navigating to the header or footer block would be the ideal solution here.

**Comment by noahtallen** [comment]
Just a note that you can reproduce this by following the steps here: https://github.com/Automattic/wp-calypso/issues/34751#issuecomment-516969402. Definitely two separate fixes, but related
