### ISSUE TITLE
Earn: Store card is displayed even if user is not on a supported country

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#34934]
This is a known issue by the time we release the Earn home. For now the only checking performed by Calypso is at the end of the Store onboarding process when they ask the user for address information. It responds with this screen:

<img width="802" alt="Captura de Pantalla 2019-07-26 a la(s) 20 38 38" src="https://user-images.githubusercontent.com/1041600/61986783-e83b0900-afe7-11e9-97eb-3a2163beca4e.png">

Since this is beyond our scope and we need tools for geolocation detection, we're punting this issue.

**Comment by huguesvincent** [comment]
What is the list of countries where this would be an issue?

**Comment by davemart-in** [comment]
Store card has been punted for now.

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
