### ISSUE TITLE
Menus: Menu items with duplicate id and parent-id freeze browser

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#34936]
#### Steps to reproduce
1. On a WordPress site that has access to [wp-cli](https://wp-cli.org/) and some menu items to test with, open up the CLI for that site.
2. Run `menu list` to get a list of menus.
3. Run `menu item list <menu> --fields=db_id,title,menu_item_parent` showing the optional `menu_item_parent` CLI output field. This will list out a particular menu's items.
4. Run `menu item update <db-id> --parent-id=<db-id>` setting a particular menu item's parent-id to itself.
5. Open that menu up for viewing in the Customizer.

#### What I expected

* For the menu in question to load in the Customizer even with the duplicate menu/parent id.

#### What happened instead

* Customizer will freeze browser upon navigating to the menu in question.
* You are able to view the menu in WP Admin without freezing the browser.

#### Browser / OS version
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

#### Screenshot / Video

Video: https://cld.wthms.co/RAxjnq

#### Context / Source
p9F6qB-3HU-p2
#user-report

**Comment by samiff** [comment]
2552796-zen

**Comment by arunsathiya** [comment]
This seems to happen on `medical-flycatcher.jurassic.ninja` (a dotorg site) as well.

Cannot find a ticket with [this search](https://core.trac.wordpress.org/search?q=menu+Customizer+freeze) but if I am reading it right, there already seems to be a [related patch](https://core.trac.wordpress.org/attachment/ticket/47564/fix_customizer_nav_menu_freeze.diff) (https://core.trac.wordpress.org/ticket/47564) to avoid this. Not merged yet.

**Comment by samiff** [comment]
2622315-zen

**Comment by cuemarie** [comment]
I've run into this a couple of times:

- 4183165-zd-woothemes in July 2021
- 35867260-hc today

Walking through steps 1-3 helps uncover the issue, where the `db_id` and the `menu_item_parent` of one menu item match. Not sure how the problem came about in the first place

**How to Fix on User's site**: 

- Open `Appearance > Menus` to access the wp-admin menus page
- Move the menu item in question under another item, and then out again, resets it's parent id.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- As mentioned earlier by @arunsathiya , this appears to be a core issue and it hasn't been added/merged.
- Core ticket: https://core.trac.wordpress.org/ticket/47564

📌 ACTIONS
- Marked as Triaged for Quality Squad review
