### ISSUE TITLE
Live Chat: invalid CSS rules cause console warnings in Safari

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3494]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Open Safari console

#### What I expected

No errors/warnings

#### What happened instead

`Unexpected CSS token: !important`

#### Browser / OS version

Safari OSX 9.0.3

**Comment by shaffi** [comment]
@alisterscott   Did you had any luck on this issue?

**Comment by alisterscott** [comment]
I'm still seeing about 5 of these warnings on initial page load of wordpress.com in Safari

**Comment by lancewillett** [comment]
This is coming from invalid CSS rules in Live Chat CSS files, such as ```

**Comment by lancewillett** [comment]
@dllh That file just probably needs a quick formatting cleanup and CSS validation check.

**Comment by lancewillett** [comment]
Closed #5355 as a duplicate

**Comment by lancewillett** [comment]
No action in several months, closing.
