### ISSUE TITLE
Reader subscriptions: max limit?

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#34961]
I'm essentially summarising this over from the most recent post on readersquad P2 since it's quite quiet over there. The problem is that a user is finding one specific site they've followed isn't showing up in their reader.

The user has 2191 sites they're subscribed to. Is that more than Reader can handle?

ETA: ticket reference is 2178249-zen
P2 post is from 15 Jul, posted by Ashley.

#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Follow 2000< sites
3. Find that at least one doesn't appear in the Reader feed
Ashley was able to replicate this when SU'd in as the user.

Ashley then got an export of the followed sites and tried to import that to a test account, with the following results:

* New blogs followed: 119
* Invalid feed URLs: 46
* Feeds that couldn’t be subscribed to: 1659

Would this be a hint that Reader breaks for people following more than a certain amount?

**Comment by bluefuton** [comment]
Thanks for the question @sophiegyo!

We limit the feed to the first 2000 subs, regardless of how many you have. So anything past 2K stops showing up in the Following feed.
