### ISSUE TITLE
Earn Section: Responsive styles for buttons

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34960]
## Description

Elio pointed out that at smaller resolutions, the buttons wrap in an awkward fashion. 

I need to spend a few minutes fixing this up.

**Comment by kwight** [comment]
This seems fine and was moved to a Done column, closing.

<img width="413" alt="Screen Shot 2020-09-09 at 10 13 27 AM" src="https://user-images.githubusercontent.com/349751/92630762-2bf0e080-f285-11ea-90e4-52ade08e9868.png">
