### ISSUE TITLE
(3P) Block Previews: Update headstart annotation & API

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#34977]
Dependent on:
https://github.com/WordPress/gutenberg/pull/16033
https://github.com/WordPress/gutenberg/pull/16113
https://github.com/WordPress/gutenberg/pull/16801

- [ ] Remove images from headstartdata.
- [ ] Update the FSE mu-plugin to not include preview images in headstart annotation.
- [ ] Regenerate headstart annotation.
- [ ] Double-check topic-verticals endpoint to see if preview-related code exists and needs to be removed.

**Comment by getdave** [comment]
Just noting here that if Templates are not created with an accessible description then the previews are not accessible. Adding a meta field to the Pages on the master site would allow Template authors to describe the Template which would allow us to add a text-based description of the Template in the Template selector UI.

**Comment by obenland** [comment]
It turns out we'll need preview images a while longer. Closing until the day that we don't.
