### ISSUE TITLE
Earn Section: Swap out Referral Program for Store card

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#34995]
## Description

Due to a lack of faith in both the Store and the eCommerce plan, we'll hold off on promoting them. We need to:

A) Remove the existing Store card (you can leave the props there, because we'll likely re-add it in the near future)

B) Add a referral program card as outlined in the [spec](https://paper.dropbox.com/doc/Spec-Earn-Section--Ah4MXOtddrdjNR2pb_Hw4kTqAg-SlHLOApkfcL12Re1o8nNa#:h2=REFERRAL-CARD) and the [HTML prototype](https://codepen.io/lessbloat/full/QXPaKY) as the **very last card** on the Earn screen.

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/34996
