### ISSUE TITLE
Posts: Last item in top menu of Posts section is hidden on first load

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#35]
There are four categories of posts displayed on the Posts page, Published/Drafts/Scheduled/Trashed.  If you're viewing a the Posts page for a site that doesn't have all four, and then use the site picker to switch to a site that does, the last menu item is cut off:

![image](https://cloud.githubusercontent.com/assets/7233112/11222050/42cd46a4-8d36-11e5-864e-8a8a74796de3.png)

Once the page is reloaded it shows up as a dropdown like it's supposed to:

![image](https://cloud.githubusercontent.com/assets/7233112/11222065/501d82f6-8d36-11e5-95b9-8d4216ed5a1f.png)

**Comment by artpi** [comment]
Confirmed with reporters,
Unable to reproduce.
