### ISSUE TITLE
Settings → General: Disparity in site languages

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#35026]
There seems to be a disparity between the Site Languages available in Calypso vs WP Admin on atomic sites. 

#### Steps to reproduce
1. Go to Calypso's Settings → General for an atomic site
2. In another tab, open WP Admin's Settings → General
3. In Calypso, select a site language that is not listed in WP Admin, such as Norsk

#### What I expected
I expected the selected language in Calypso to be applied to the site.

#### What happened instead
If you select a language in Calypso that isn't available in WP Admin, like Norwegian, it appears as an unsupported language and an "unexpected error" message pops up.

#### Screenshot / Video

https://snag.gy/vAHP6p.jpg

#### Context / Source
Languages are being shown in Calypso that are not supported.

Seen in #8973012-hc

**Comment by lizswafford** [comment]
Also seen in #15639342-hc

They were able to choose and save the language selection for "Norsk nynorsk". But that is old Norwegian the customer is not familiar with. They would prefer to use "Norsk", but see the error "unsupported language" and the change doesn't save.

**Comment by cesarabeid** [comment]
Also seen in [this ticket](https://woothemes.zendesk.com/agent/tickets/3032048)

I was able to change to Norsk bokmål via wp-admin.

**Comment by davoraltman** [comment]
Another one in 3043136-zen

**Comment by tbradsha** [comment]
Issue with Norsk in 3517700-hc. Switched to Norsk bokmål in WP Admin.

**Comment by brookewp** [comment]
Another zd-3417232

**Comment by khristiansnyder** [comment]
Another in 25478204-hc

**Comment by inaikem** [comment]
Another: 3717374-zd

**Comment by scosgro** [comment]
Another 26936016-hc (Norsk)

**Comment by tarunvijwani** [comment]
Another one: 4187697-zn, 30896655-HC

**Comment by Greatdane** [comment]
Another 30766845-hc (Simplified Chinese)

**Comment by tbradsha** [comment]
> Simplified Chinese

It seems to be there for me, both in "Popular languages" and "Asia-Pacific":
![image](https://user-images.githubusercontent.com/32492176/129779290-e2573be9-262d-44d2-8a95-bcd8a7bd40e9.png)

**Comment by Greatdane** [comment]
Yes, this ended up being unrelated! (Jetpack reconnect fixed things)

**Comment by mreishus** [comment]
Possibly related to missing language packs on Atomic.
- (better) Automatically download the language pack for the user
- (worse) Let the user know they can download a language pack

**Comment by mreishus** [comment]
My first assumption was the problem related to language packs. Atomic sites don't come with all languages installed. For example, my test site has only two languages installed.
![2021-10-11_13-22](https://user-images.githubusercontent.com/937354/136836633-a2630ec4-cc42-4da3-b22b-8128b3e3367f.png)
I assumed that when using calypso to select a non-installed language, that would cause the error. However, that's not the case. Selecting the language in calypso causes the site to automatically download the language pack. (That's how my test site obtained the Spanish language pack.)

Examining the "Norsk" vs "Norsk nynorsk" languages in greater detail, my atomic site has "Norsk nynorsk" in the "available" section, meaning it knows how to download a language pack for it. But "Norsk" is missing.
![2021-10-11_13-24](https://user-images.githubusercontent.com/937354/136836872-ecc43b0f-2384-4229-9026-2934d9046c71.png)

Checking Calypso's [definitions of the two languages](https://github.com/Automattic/wp-calypso/blob/07609a11bb94605406a3de0ab548db5dad6f5343/packages/languages/src/languages-meta.json#L1052-L1073), something stands out: "Norsk nynorsk" has a `wpLocale` of `nn_NO`, but Norsk doesn't have a `wpLocale`.

We can check for all languages with a `wpLocale` of empty string:
```
cat languages-meta.json | jq -c '[ .[] | select( .wpLocale | length == 0) | .name ]' | jq
[
  "Alemannisch",
  "Aragonés",
  "ܕܥܒܪܸܝܛ",
  "авар мацӀ",
  "aymar aru",
  "Bamanankan",
  "Нохчийн мотт",
  "Kaszëbsczi",
  "чӑваш чӗлхи",
  "ཇོང་ཁ",
  "Français de Suisse",
  "Interlingua",
  "ꆇꉙ",
  "Pagsasao nga Iloko",
  "कश्मीरी",
  "Коми",
  "Latine",
  "Malti",
  "Mirandés",
  "Nahuatl",
  "Nnapulitano",
  "Plattdüütsch",
  "Norsk",
  "Norrǿna",
  "Diné bizaad",
  "ଓଡ଼ିଆ",
  "Runa Simi",
  "Sardu",
  "Reo Mā`ohi",
  "Удмурт кыл",
  "Vèneta",
  "Хальмг",
  "ייִדיש",
  "èdè Yorùbá",
  "(Cuengh)"
]
```

These languages also cause the same error:
![2021-10-11_13-30](https://user-images.githubusercontent.com/937354/136837529-8818e810-d5ee-4eb4-a557-2e61fd1cd8db.png)
![2021-10-11_13-30_1](https://user-images.githubusercontent.com/937354/136837534-35e5412e-c1a8-43b7-8531-c2f2275fc86b.png)

Next is to determine why these languages have `wpLocale == ""` - Does it mean that we added extra languages to Calypso that core WP.org does not support? And if so, what solution is best - is there anything better than hiding these languages when changing the language on an atomic site?

**Comment by mreishus** [comment]
## Calypso Languages such as Norsk and Interlingua are missing from WP.org

I've confirmed that the languages with `wpLocale == ""` don't appear on translate.wordpress.org. However, they do appear on translate.wordpress.com.

## There are also language on WP.org that are missing in Calypso

There are also languages that appear on wordpress.org that aren't in calypso:
![2021-10-11_13-53](https://user-images.githubusercontent.com/937354/136843560-b309d4a3-f9cd-478d-8f04-c6715f8c1ec0.png)
![2021-10-11_13-53_1](https://user-images.githubusercontent.com/937354/136843570-b09f62d4-602f-41a2-abe0-5c0c0c14e563.png)

On a lark, I tried adding nb_NO (Norsk bokmål) to my Calypso's language-meta.json. It worked when setting the language for my atomic site, but also appeared in the WP.Com interface languages, where it causes an error:
![2021-10-11_13-54_1](https://user-images.githubusercontent.com/937354/136843750-1728b704-29f2-4cef-accf-d919e6b6622b.png)
![2021-10-11_13-55](https://user-images.githubusercontent.com/937354/136843753-54c8447f-c73b-4c86-be4b-289799c0b01f.png)
![2021-10-11_13-56](https://user-images.githubusercontent.com/937354/136843766-6123d237-8dc6-45a5-9db6-09ac402c238e.png)

Summary coming up in next reply.

**Comment by mreishus** [comment]
## Summary

Two summarize, we have three categories of languages:
* **(A)** Languages that exist in Calypso's languages-meta.json only, and are not on translate.wp.org. 
  * (Example: "Norsk")
* **(B)** Languages that exist in both Calypso's languages-meta.json and translate.wp.org.
  * (Example: nn_NO "Norsk nynorsk")
* **(C)** Languages that are not in Calypso's languages-meta.json, and exist only on translate.wp.org. 
  * (Example: nb_NO "Norsk bokmål")

![2021-10-11_14-25](https://user-images.githubusercontent.com/937354/136845316-fbb08ca5-8b24-48fb-ab0f-acf7f6ed10f1.png)

If you have Simple and Atomic sites on WP.com, Calypso allows you to set languages in 5 places:
* **(I)** WP.com interface language settings
  * Displayed: **(A) (B)**
* **(II)** Simple Site - Calypso - General Settings `/settings/general/<site>`
  * Displayed: **(A) (B)**
* **(III)** Simple Site - WPAdmin - General Settings `/wp-admin/options-general.php`
  * Displayed: **(A) (B)**
* **(IV)** Atomic Site - Calypso - General Settings `/settings/general/<site>`
  * Displayed: **(A) (B)**
    * :x: Choosing a category **(A)** (Calypso only) language causes an error.
    * :heavy_check_mark: Choosing a category **(C)** (WP.org only) works properly in my limited testing - but Calypso does not currently have a list of these languages.
* **(V)** Atomic Site - WPAdmin - General Settings `/wp-admin/options-general.php`
  * Displayed: **(B) (C)**

## Solutions

From here, the path forward seems to be:

1. **(IV)** Atomic Site - Calypso - General Settings `/settings/general/<site>` - Hide category **(A)** languages
2. **(IV)** Atomic Site - Calypso - General Settings `/settings/general/<site>` - Display category **(C)** languages
  i. This may be more difficult as far as I know, Calypso does not have a list of these languages available.

**Comment by mreishus** [comment]
We have changed the Calypso language picker (`/settings/general/<url>`) to match the languages offered on Jetpack and Atomic sites. Simple sites remain unchanged. 
For example:
* My simple site allows me to choose "Norsk" or "Norsk nynorsk", both save without error
* My atomic site allows me to choose "Norsk bokmål" or "Norsk nynorsk", both save without error.

Please let me know if you are still seeing issues around this.
