### ISSUE TITLE
Calypso Navbar: Expand the "sites" tab by default.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#35034]
#### Context / Source

Less tech savvy users don't always realize the navbar tabs can be expanded, which makes them reluctant to click on the navbar to locate specific features.

![Screen Shot on 2019-07-31 at 15_30_32](https://user-images.githubusercontent.com/10121835/62246183-b8ee1880-b3a8-11e9-9829-bee5e7a39544.png)

If the "sites" section was expanded by default it would contrast with the collapsed items and imply those sections can be expanded as well.

Plus, the sites tab is the most likely section to be used day-to-day.

That way there's a compromise between saving screen real estate but still giving the user enough information to work with.

![Screen Shot on 2019-07-31 at 15_31_43](https://user-images.githubusercontent.com/10121835/62246193-bb507280-b3a8-11e9-96a4-736e272405e0.png)

**Comment by nerdysandy** [comment]
Closing it because we're rolling out new nav unification where this doesn't apply.
