### ISSUE TITLE
Signup: use blog name in subsequents steps as a starting point to avoid re-typing the same thing again

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#35032]
Every time I run through signup I think "why don't we just reuse the text I already entered on the previous steps?"

@michaeldcain nudged me to share this on GitHub after we chatted today.

#### Steps to reproduce
1. Starting at URL: /start and pick Blog from the site type
2. Site title with preview step: enter "your blog name"
3. Domain step: "Give your blog an address"

#### What I expected

I'd expect to re-use the blog name here to give me a starting point for domain suggestions. Don't make me enter it again.

#### What happened instead

I have to type the same name again.

#### Screenshots

<img width="1816" alt="Screen Shot 2019-07-31 at 10 42 51" src="https://user-images.githubusercontent.com/66797/62244958-58091500-b395-11e9-8ec1-54270b9a4ed1.png">

<img width="1816" alt="Screen Shot 2019-07-31 at 10 42 56" src="https://user-images.githubusercontent.com/66797/62244959-58091500-b395-11e9-881b-6110fba4b620.png">

<img width="1816" alt="Screen Shot 2019-07-31 at 10 43 24" src="https://user-images.githubusercontent.com/66797/62244960-58091500-b395-11e9-85ea-8596e332f751.png">

**Comment by spen** [comment]
I'm working on this now and it seems pretty easy to achieve!
What I'm wondering though, is whether or not this should be split tested, or whether or not we should add some tracking to gauge whether or not people are selecting the suggestion that we give based on their site title - what do you guys think?

**Comment by ramonjd** [comment]
> What I'm wondering though, is whether or not this should be split tested, or whether or not we should add some tracking to gauge whether or not people are selecting the suggestion that we give based on their site title - what do you guys think?

Good idea, @spen 

I'm speculating, but a button to clear the fields might help folks who don't wish to use pre-filled data, similar to what we have on the domains step

<img width="164" alt="Screen Shot 2019-08-26 at 12 51 08 pm" src="https://user-images.githubusercontent.com/6458278/63662374-901f3e80-c801-11e9-91f2-ddabac511e43.png">

**Comment by lancewillett** [comment]
Closing as this change was tested and reverted. See #36799.
