### ISSUE TITLE
Gutenberg: Opt out is still available to new sites in the More menu.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#35033]
This may have been missed in #32735: while the opt-out in the support bubble was updated, the "Switch to Classic Editor" menu item in the block editor's ellipsis More menu is still available. Both should be missing for sites created after March 14, 2019.

<img width="639" alt="Screen Shot 2019-07-30 at 1 01 51 PM" src="https://user-images.githubusercontent.com/349751/62245932-7b34c400-b397-11e9-8207-0dd2e1175d4b.png">

**Comment by kwight** [comment]
Both Switch to Classic Editor options are now available on new sites, and I have no idea why I think opt-out shouldn't be allowed for sites after March 14, 2019 🙃

<img width="397" alt="Screen Shot 2019-11-08 at 10 32 54 AM" src="https://user-images.githubusercontent.com/349751/68501540-3da3ca80-0213-11ea-8ddd-e41ff40b8129.png">

**Comment by lancewillett** [comment]
Is it possible that older users (signup up before December 16, 2019) will still see the UI to opt-out?

I created a new site today (March 7, 2020) with an older user `testerlance` and I see the UI to opt-out but only in the ... menu (not in the Help menu).

URL: https://wordpress.com/block-editor/post/neweditorlance2020.wordpress.com/9

<img width="1552" alt="Screen Shot 2020-03-07 at 10 29 08" src="https://user-images.githubusercontent.com/66797/76147922-8010d300-605e-11ea-9a62-28a3ffb54f9a.png">

CC @philnick206

**Comment by noahtallen** [comment]
> Is it possible that older users (signup up before December 16, 2019) will still see the UI to opt-out?

Yeah, the implementation in D36556-code is only for new user accounts. I think other logic might affect it as well, including if the site has dotcom-fse, and if the site is using one of a certain list of themes.

**Comment by davemart-in** [comment]
Update: We're going to be removing this link once the Calypso editor has been retired. That project is underway now. Once that project is complete, this issue can just be closed.

**Comment by noahtallen** [comment]
Fixed as part of deprecating the classic editor
