### ISSUE TITLE
FSE: Add a "Set as Front Page" option to /pages

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35043]
Any site using a full site editing compatible theme will have the customizer hidden (see https://github.com/Automattic/wp-calypso/issues/34791). There is one major setting that this hides from users that is not present in Calypso.

Setting the front page, and setting the post listing page.

We do not need to keep the post listing page setting because this is replaced with a static page and the "Blog" template (with the latest posts blog).

We do need to allow users to set which page is their front page.

I suggest the following changes for any site with a FSE compatible theme enabled:

<img width="1005" alt="Screen Shot 2019-07-31 at 8 55 00 PM" src="https://user-images.githubusercontent.com/1464705/62264607-78f15a80-b3d5-11e9-98b0-47174d07d700.png">

Selecting "Set as Front Page" on any other page will do just that.

/cc @shaunandrews

**Comment by mattwiebe** [comment]
Our previous implementation was removed by https://github.com/Automattic/wp-calypso/pull/13314

**Comment by Copons** [comment]
> Our previous implementation was removed by #13314

And as it turns out, it was added back in #24087 (Lannister, and well, me specifically, were involved with it in a review day IIRC) and then... we never turned the feature flag on for all environments... 🤦‍♂

**Comment by apeatling** [comment]
Terminology is important with this one, we reference Front Page and Homepage in that above PR, it needs to be consistent.

**Comment by Copons** [comment]
@apeatling You're right, although it's not that PR's fault.
I'd say: let's call everything "homepage" because it's either a more common term, and it's what Core uses for this setting.
