### ISSUE TITLE
FSE: Placeholder text for blank paragraph displays in the page editor template

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#35040]
#### Steps to reproduce
1. Use gutenberg master on your local install. (I conveniently use the gutenberg docker setup, so you'll have to pull, build, and restart docker to get the update.)
2. Open a page with FSE enabled.
3. Open the template editor for the header and insert a paragraph but leave it blank.
3. Navigate back to the page editor. The paragraph placeholder text still shows up:
<img width="1274" alt="Screen Shot 2019-08-09 at 4 49 29 PM" src="https://user-images.githubusercontent.com/6265975/62814447-c3ee2a80-bac5-11e9-9c3c-bdd939f00564.png">

Since you can't edit the header from this view, this text should be removed. It also messes up the spacing between the header and the post content block. I think maybe we should strip blank paragraphs at some point in the header?

**Comment by noahtallen** [comment]
The bug is actually a bit different than I thought, and not really a bug per se.

In the template editor, you can insert a paragraph block, but leave it blank. Then save the template.
<img width="1427" alt="Screen Shot 2019-08-09 at 4 49 21 PM" src="https://user-images.githubusercontent.com/6265975/62814458-d0728300-bac5-11e9-91b2-dc37c21ea51d.png">

Back in the page editor, the placeholder text for the blank paragraph block shows up:
<img width="1274" alt="Screen Shot 2019-08-09 at 4 49 29 PM" src="https://user-images.githubusercontent.com/6265975/62814447-c3ee2a80-bac5-11e9-9c3c-bdd939f00564.png">

We should probably strip the blank paragraph from the template block at some point, but I'm not quite sure.

**Comment by jeraldjuice** [comment]
At this point, it probably doesn't make sense to implement a fix for this. "Empty" state for individual blocks in Gutenberg is notoriously hard to pin-down, and potential workarounds seem to just uncover a snowball of issues. (In-depth explanation in the summary [of this PR](https://github.com/Automattic/wp-calypso/pull/35415), along with some issues that Noah found with my approach)

I suggest closing this issue and accepting this as: maintaining existing Gutenberg functionality and calling out when there are empty blocks in the header (which will ultimately create spacing issues on the frontend, which is currently expected of anything edited in Gutenberg and not exclusive to FSE).

Feel free to re-open if that assumption is incorrect. Either way, we will need design/flow input for this moving forward.
