### ISSUE TITLE
FSE: Blocks color settings not respected when inside Template Parts

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#35058]
Reported in https://github.com/Automattic/wp-calypso/pull/34997#issuecomment-517325918

If I add a block with background color it will not be rendered properly on the front end:

In Editor:
<img width="1126" alt="Screenshot 2019-08-01 at 16 47 07" src="https://user-images.githubusercontent.com/1182160/62304237-e22ca880-b47d-11e9-8a30-1acc6c57cabd.png">

On Front End:
<img width="1051" alt="Screenshot 2019-08-01 at 16 47 25" src="https://user-images.githubusercontent.com/1182160/62304275-efe22e00-b47d-11e9-9f1b-435b2700c8e1.png">

---

[Palettes in Gutenberg](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes) needs to be defined both in PHP and CSS to work.
In PHP we basically create the colors definitions, that will be eventually used in the editor and to generate some CSS classes (e.g. the `red` color will be applied to a block as the `.has-red-color` class).
While Gutenberg uses the hex code provided in PHP, the front end is not aware of it, and only relies on those CSS classes.

Of course, though, themes nest those classes inside the post content class.
See for example Modern Business: https://github.com/Automattic/themes/blob/04f46cd956e06ab10aa787b7eca08c21075050c0/modern-business/sass/blocks/_blocks.scss
Try searching for `.has-primary-color`, and notice how everything is nested inside `.entry .entry-content`.

How do we fix this?
Random idea: we could wrap our template parts with .entry .entry-content elements in the front end.

**Comment by glendaviesnz** [comment]
> we could wrap our template parts with .entry .entry-content elements in the front end.

I tried this and it does work - but have a PR up at https://github.com/Automattic/themes/pull/1172 which instead adds additional selectors to the blocks scss which is perhaps a bit more explicit for people editing themes - but I have no idea what the implications are for us of adding FSE selectors to the theme scss, so totally open to discussion on this :-)
