### ISSUE TITLE
FSE: Update the remote template parts fetching with the theme class changes

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#35059]
In #34997 we changed how theme classes are applied to Template Parts.

We should iterate on this by updating (well, rebasing really) accordingly https://github.com/Automattic/themes/pull/1167.

Also, we might try updating D31012-code to return, along with the default Template Parts content, the theme classes that FSE is expected to use.

For example, instead of [hardcoding `.site-header .site-branding` in FSE](https://github.com/Automattic/wp-calypso/blob/197da1b65eddc939c997573fe6846e7fc31807c4/apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/editor-template-classes/index.js#L17-L29), we could retrieve them from the same API that will eventually return the template parts.

E.g. in the current proposed diff it returns something like this:
```js
{
  header:
    '<!-- wp:group {"className":"site-header site-branding"} -->
      <div class="wp-block-group site-header site-branding">
        <div class="wp-block-group__inner-container">
          <!-- wp:a8c/site-title /-->
          <!-- wp:a8c/site-description /-->
        </div>
      </div>
    <!-- /wp:group -->',
}
```
But we could make it return this instead:
```js
{
  headerClasses: [
    'site-header',
    'site-branding',
  ],
  headerContent:
    '<!-- wp:a8c/site-title /-->
     <!-- wp:a8c/site-description /-->',
}
```

cc @vindl

**Comment by noahtallen** [comment]
Since the same class is used in 2019 child themes, I'm going to stick this back on the backlog since it's not a blocker at the moment.

**Comment by gwwar** [comment]
@Copons is this one still needed?

**Comment by Copons** [comment]
> @Copons is this one still needed?

Not needed in the short term, but in the off chance we want to extend FSE to themes not derived from Twenty Nineteen, this will be useful imho

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
