### ISSUE TITLE
Earn Section: Couple minor tweaks

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#35054]
## Description

Two issues have been called out in our call for testing:

1) “Earn Cash from Referrals” should be “Earn cash from referrals”

2) We should consolidate simple payments nudge copy found in the plan section with the one in the Earn section

**Comment by eliorivero** [comment]
First one is done 
https://github.com/Automattic/wp-calypso/pull/34896/files#diff-6d934f22e0b322d8ae8daa0978804e26R161

**Comment by davemart-in** [comment]
Note: I'm just going to wait until the Earn section ships and handle this as a separate PR.

**Comment by kwight** [comment]
Closing as out-of-date, @davemart-in you can re-open if there's still something actionable here.
