### ISSUE TITLE
CoBlocks: Pricing Table doesn't have an option to move up/down

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#35053]
The pricing table doesn't allow you to move it up or down unless you set it to wide/full width:

#### Steps to reproduce
1. Be sure to have another block like a paragraph block already created
2. Add a Pricing Table block
3. Try to move the pricing table up or down

#### What I expected
To have the arrows to move it up or down

#### What happened instead
I couldn't move the Pricing Table block unless I change its width settings

#### Browser / OS version
Google Chrome Version 75.0.3770.142 (Official Build) (64-bit) | macOS Mojave 10.14.5 (18F132)

#### Screenshot / Video

![Screen Capture on 2019-08-01 at 08-51-19](https://user-images.githubusercontent.com/3696121/62299217-2a29dc00-b43a-11e9-8a45-c14c2d138d1b.gif)

#### Context / Source

#manual-testing

**Comment by kwight** [comment]
This is a CoBlocks issue, reported at https://github.com/godaddy/coblocks/issues/1081.

**Comment by davipontesblog** [comment]
https://github.com/godaddy-wordpress/coblocks/pull/1100 closes this.
