### ISSUE TITLE
Page Templates: More goal based templates

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35062]
We have page templates for: About, Contact, Portfolio, Services, Team, and Blog. We also have a number of home page specific templates.

We need to build a broader range of page templates that have more specific goals, and are likely to include more advanced, and in some cases premium, and/or third party blocks.

This task could be broken out for each new page template.

Quick list of ideas: Products, Events, Bookings, Restaurant Menu, Social Accounts, Videos Page, Photo Gallery Page.

Looking at verticals and understanding the page template needs will help with this.

The engineering component to this is building the blocks and/or sourcing and supporting the third party blocks we need.

**Comment by apeatling** [comment]
These are being added by the theme folks. First example here for Menu:

https://github.com/Automattic/wp-calypso/issues/35613

**Comment by apeatling** [comment]
Block needs addressed in this epic issue: https://github.com/Automattic/wp-calypso/issues/35633

**Comment by obenland** [comment]
Should we close this one?

**Comment by apeatling** [comment]
Yes, close. We still need to do this as a product, but I think it should be broken out.

**Comment by apeatling** [comment]
@olaolusoga This was the issue I was thinking of. It was closed to be broken out, I think we could work together to get that figured out.

**Comment by frontdevde** [comment]
Issue triage 27-02-2020:
Closing as it's been replaced by https://github.com/Automattic/wp-calypso/issues/37782
