### ISSUE TITLE
Checkout: Jetpack purchase redirects to wrong location

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#35068]
@oskosk and I have been observing an issue where Jetpack plan purchases are redirected to `/` after checkout. It seems to be from change from #34156

https://github.com/Automattic/wp-calypso/blob/1db732dd298e035d7c97a22c9d30c6f31f405a22/client/my-sites/checkout/checkout/index.jsx#L449

## Steps to reproduce
1. Use any Jetpack site that has a plan upgrade option (not already on highest tier plan).
1. Visit https://wordpress.com/plans for the site.
1. Pick a plan upgrade.
1. Complete checkout.
1. After checkout you're returned to `wordpress.com/` rather than the expected https://wordpress.com/plans/my-plan/SITE_SLUG. This is a regression.

This also affects purchases initiated via Jetpack WP Admin (`https://example.com/wp-admin/admin.php?page=jetpack#/plans`)

cc: @niranjan-uma-shankar

**Comment by sirreal** [comment]
If a plan is purchased during the signup (Jetpack connect) flow, this issue does not seem to occur. It's purchasing a plan initiated from an already connected Jetpack site.

**Comment by sirreal** [comment]
#35084 was merged as a workaround. This issue should be present in production but I'll leave this open while @niranjan-uma-shankar works on a better solution.

**Comment by simison** [comment]
This can be closed now since https://github.com/Automattic/wp-calypso/pull/35283 has been merged,  @niranjan-uma-shankar ?

**Comment by niranjan-uma-shankar** [comment]
Yes indeed @simison . #35283 removes the temporary fix by @sirreal and adds a proper fix, so I'll close this one.
