### ISSUE TITLE
Full Site Editing: Log template population failures and provide last fallback

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#35077]
Currently if the template population fails while activating the Modern Business theme it does so silently and the user is not aware that their site is not in a fully functional state.

Let's log this to Kibana, with debug information, but also provide some default basic fallback content.

**Comment by glendaviesnz** [comment]
This is dependant on completion of the API for population of the template data - the initial version of this was abandoned - and this may well be fixed in the new iteration. Will leave open for now as a reminder to check that error notifications are handled in the new iteration.

**Comment by gwwar** [comment]
Maybe we can do max three retries on error?

**Comment by glendaviesnz** [comment]
> Maybe we can do max three retries on error?

PR up at https://github.com/Automattic/wp-calypso/pull/35269 with retry option. 

Haven't managed to find a way top notify to notify the user at the point of failure yet. Ideally it just needs something like https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices to dispatch a notification at the point of the 3rd retry failure, but this won't work in the context of a Simple site calypso environment. 

Maybe with the retry in place we don't worry about the user notification unless we see issues during user testing? The other option is to have some sort of notification if the user edits a page with FSE enabled and no template data is present?
