### ISSUE TITLE
Import: Bold text in the instructions disappears on page reload

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#3507]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/import
2. Select "Start Import" for a new WordPress import
3. Note that the instructions include details about the type of import and the site where the content will be imported, e.g. "Upload a WordPress export file to start importing into rachelmcrtest2."
4. Drag or click to upload an import file.
5. After you see the "Success! File uploaded." message, reload the page in the browser.

#### What I expected
I expected that reloading the page wouldn't have any effect. I'd still see the import instructions and other options.

#### What happened instead
The text for the type of import and site disappeared, leaving the sentence, "Upload a                   to start importing into                ."

#### Browser / OS version
Mac OSX 10.11.3, Chrome 48.0.2564.116

#### Screenshot / Video

Before reloading the page:
![screen shot 2016-02-23 at 8 26 16 am](https://cloud.githubusercontent.com/assets/8658164/13258550/6fd8558e-da08-11e5-9057-69e535b562d2.png)

After reloading the page:
![screen shot 2016-02-23 at 8 26 30 am](https://cloud.githubusercontent.com/assets/8658164/13258559/7a7840d0-da08-11e5-996f-8cfce05e1fb4.png)

**Comment by alisterscott** [comment]
I noticed this also during testing but couldn't reproduce it consistently on page refresh, especially if you have dev tools inspector open.

**Comment by alisterscott** [comment]
This could possibly be related to this other issue I saw: https://github.com/Automattic/wp-calypso/issues/3326

**Comment by rachelmcr** [comment]
I can reproduce it consistently when dev tools are closed. If I open the dev tools inspector the text reappears, and if I keep dev tools open while refreshing it doesn't reproduce consistently.

While checking just now, I also discovered that the text is there but is white, so it isn't visible against the white background.

**Comment by jessefriedman** [comment]
I can reproduce regularly but for me it isn't on refresh it's anytime I highlight text and try to make it bold.

**Comment by aduth** [comment]
Ref: p58i-3wV-p2 , /cc @mattmiklic

**Comment by mattmiklic** [comment]
@rachelmcr Can you still reproduce this issue?

It sounds similar to the Chrome bug we've been dealing with in the Merriweather webfont. I hadn't seen the issue in Open Sans personally, but this sounds like the same one. We're no longer using the Open Sans webfont for this interface, so I would expect for this issue to be resolved.

**Comment by rachelmcr** [comment]
I can't reproduce this issue anymore, no matter what steps I try, so it looks like this is now resolved. I'll close this issue. Thanks!
