### ISSUE TITLE
Import: Importer goes in a loop if you don't reassign all authors

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#3509]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/import
2. Choose a site with multiple authors (the site you will import into)
3. Select "Start Import" and upload a file to import (make sure this import file also includes multiple authors)
4. After the import file is uploaded, select "Start Import"
5. On the screen where authors are assigned, note that the "Start Import" button is greyed out. For the first user in the list, choose an author to assign their posts to. Note that the "Start Import" button is no longer greyed out.
6. Select "Start Import" without reassigning the other authors.
#### What I expected

I would be blocked from starting the import until all authors were reassigned, or the importer would assume that any unassigned authors would be reassigned according to some default rule.
#### What happened instead

The importer went back a step to the "Success! File uploaded." screen. I can continue in a loop like this if I don't assign all authors in the import file.
#### Browser / OS version

Mac OSX 10.11.3, Chrome 48.0.2564.116
#### Screenshot / Video

![calypso-importer-authors](https://cloud.githubusercontent.com/assets/8658164/13259697/605d6838-da0d-11e5-95fb-10e72db64e59.gif)

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue.

**Comment by hoverduck** [comment]
No longer an issue.  We now have a default author assigned when you start the import.
