### ISSUE TITLE
My Plan: Feature card headings need higher contrast

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#35098]
<img width="486" alt="screen-shot-2019-07-08-at-12 53 28-pm-1" src="https://user-images.githubusercontent.com/2124984/62387190-f0cf9a00-b527-11e9-87da-ad6902741000.png">

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/my-plan/
2. The headings on each of the feature cards (as seen above) need more contrast to pass AA WCAG standards
3. We can probably use the CSS var `--color-text-subtle` instead.

**Comment by drw158** [comment]
I agree the text could be darker, but just noting here that "Large" is anything 18 or above, not 21. Or at least that's what I thought.

https://developer.paciellogroup.com/blog/2012/05/whats-large-text-in-wcag-2-0-parlance/

**Comment by ryelle** [comment]
@drw158 Large is `18pt`, but that's usually computed to `24px`. I was saying (this screenshot came from me) that this text is 21px, so it's not "large".

> The ratio between sizes in points and CSS pixels is 1pt = 1.333px, therefore 14pt and 18pt are equivalent to approximately 18.5px and 24px.

from [note 1 here](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)

**Comment by drw158** [comment]
@ryelle Wow, I never noticed that! Thank you for clarifying. I'll keep that in mind in the future.
