### ISSUE TITLE
FSE: Back to Page Link should respect if flows started in wp-admin

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35105]
Click on "Back to Page" when editing in wp-admin takes me to `https://wordpress.com/block-editor/page/{site}/{page id}` instead of `/wp-admin/post.php?post={postid}&action=edit`

<img width="898" alt="Screen Shot 2019-08-02 at 11 08 02 AM" src="https://user-images.githubusercontent.com/1270189/62389939-f7551600-b515-11e9-9fee-2f05e0d7614e.png">

**Update:**
Note that this doesn't happen on Atomic or self-hosted sites in general, but only when you edit pages on Simple sites through wp-admin.

**Comment by gwwar** [comment]
Verify if this is an issue or not, might already be fixed.

**Comment by noahtallen** [comment]
Also reported in D31440#626687-code

**Comment by noahtallen** [comment]
Still an issue for my. I think this is caused by the MU wrapper using the `a8c_fse_close_button_link` action to override the back button in the FSE context in order to make it a Calypso URL.

**Comment by gwwar** [comment]
I'd say non-blocking for the call for testing, but something we can enhance later before we A/B testing.

**Comment by vindl** [comment]
Not that this doesn't happen on Atomic or self-hosted sites in general, but only when you edit pages on Simple sites through wp-admin.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
