### ISSUE TITLE
Import: Uploaded import file reappears after cancelling the import

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#3510]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import
2. Select "Start Import" and upload an import file
3. Select "Cancel" to cancel the import and go back to the starting screen
4. Refresh the screen
#### What I expected

I expected to remain on the initial importer screen after refreshing the page, with my previously uploaded import file wiped out.
#### What happened instead

I was taken back to the "Success! File uploaded." screen, even though I had cancelled that import attempt earlier. (This is also confusing because there is no indication on that "Success!" screen about what file was uploaded.)
#### Browser / OS version

Mac OSX 10.11.3, Chrome 48.0.2564.116

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue:
![wp-calypso-3510](https://cloud.githubusercontent.com/assets/7233112/15222830/7567d18a-183f-11e6-9c89-04847cfd88e5.gif)
