### ISSUE TITLE
Purchases: Manage Purchases page could use some improvement

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#35102]
![Screenshot 2019-08-02 10 59 34](https://user-images.githubusercontent.com/4924246/62389408-9ed14900-b514-11e9-9a5f-6b964e12985f.png)

#### Steps to reproduce
Manage Purchases page: https://wordpress.com/me/purchases/[site]

I think minor improvements can be made to improve this page:

- Are icons supposed to be pink?
- Not sure why the dividing line needs to be in pink, it's really prominent
- Shouldn't the notice be red here?
- Center-alignment for the items within the table looks off
- Toggle switch center-aligned looks off
- It's not obvious that credit card info (Payment Method column) is clickable/editable
- Description feels disconnected from the domain itself

**Comment by sixhours** [comment]
@lcollette Another potential flow to audit.

**Comment by jancavan** [comment]
@taggon Any way to easily repro this issue? cc @scalarbane2

**Comment by michaeldcain** [comment]
The notice styles now match the rest of Calypso, and the colors on the page are a little more muted.

<img width="1543" alt="Screen Shot 2021-03-08 at 1 41 16 PM" src="https://user-images.githubusercontent.com/942359/110366301-17af5580-8014-11eb-8549-fd54f20b35c2.png">

We have some upcoming work on Shilling to update these screens, so I'll go ahead and close this issue.
