### ISSUE TITLE
FSE: Make sure all themes set a editor background color

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35117]
All themes for FSE must set an `.editor-styles-wrapper` background color to support the full site editing frame. They cannot assume it will be `#fff`.

It's enough to set this on the parent theme as `#fff`.

Related: https://github.com/Automattic/wp-calypso/pull/35116#issuecomment-517890406

**Comment by noahtallen** [comment]
Added this task to the overarching theme issues

**Comment by vindl** [comment]
Let's limit this to just Modern Business for now in case it hasn't already been added. If it is, we can kick it out of the current sprint.

**Comment by noahtallen** [comment]
I don't see one in modern business yet, but it'll be super easy to add.

**Comment by noahtallen** [comment]
Closing now that we have the initial support in modern business and a link to it from all the other theme issues.
