### ISSUE TITLE
Podcasts: Apple removed/updated categories so our topics are out of date

### ISSUE THREAD

**Issue by brookewp** [Automattic/wp-calypso#35111]
#### Summary

In June, Apple updated and removed categories for Podcasts. We received a user report that their podcasts aren't showing up anymore because they are in the deleted category but with no option to change to the new one here. 

For example, Apple renamed "Science & Medicine" to "Science".  So any podcasts still in “Science & Medicine” won't show up in Apple's newly named "Science". Here is a list of these changes: 

https://podnews.net/article/apple-changed-podcast-categories-2019

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/podcasting/[site-address]
2. Go to section 'Podcast Topics'
3. Click on drop-downs there
4. See old topics (apple refers to as categories)

#### What I expected 

When selecting Podcast topics, they would match the categories that Apple uses currently. 

#### What happened instead

Our topics and subtopics are out of date since Apple updated these in June. Here is a list of all of the changes to Podcasts categories: https://podnews.net/article/apple-changed-podcast-categories-2019

#### Screenshot / Video

Topics I am referring to:
<img width="700" alt="Screen Shot 2019-08-02 at 2 14 37 PM" src="https://user-images.githubusercontent.com/35543432/62399453-ba4a4d00-b530-11e9-81d2-b7faf2570c92.png">

Example, Science & Medicine should now just be Science:
 
<img width="709" alt="Screen Shot 2019-08-02 at 2 14 12 PM" src="https://user-images.githubusercontent.com/35543432/62399466-c1715b00-b530-11e9-9c8a-a28f61cc45b7.png">

#### Context / Source

Reported by user here: hc-#11418367
Follow up: zd-#2244712

 #user-report

**Comment by jonnyruzek** [comment]
Another report in 2246569-zen

**Comment by donpark** [comment]
^^ @brookewp @jonnyruzek patch is ready for review

**Comment by donpark** [comment]
Deployed. Thanks to @arunsathiya for helping out.

**Comment by bsanevans** [comment]
Thanks @donpark and @arunsathiya !
Follow-up sent to both #2244712-zen and #2246569-zen.
