### ISSUE TITLE
Podcasting: Widget "Subscribe via iTunes" Link Does Not Work

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#35127]
#### Steps to reproduce
1. Starting at URL: Activate Podcasting feature on a Simple Site via Settings > Writing
2. Go to Customizer
3. Select Widgets and choose the Podcast widget

<img width="330" alt="Screen Shot 2019-08-04 at 12 59 50 PM" src="https://user-images.githubusercontent.com/25575134/62426803-c7de0f00-b6b7-11e9-9eff-04bf5df9c15e.png">

4. Add your iTunes ID and publish the widget.

5. Check the link "Subscribe via iTunes" from the widget

#### What I expected

The link to bring to iTunes.
#### What happened instead

I got the "Page Not Found" instead with this link: http://phobos.apple.com/WebObjects/MZStore.woa/wa/viewPodcast?id=1458286521

#### Screenshot / V
![Farben](https://user-images.githubusercontent.com/25575134/62426852-43d85700-b6b8-11e9-8f86-b62b78c4ce28.gif)
ideo

#### Context / Source
Reported by the customer in 2248376-zen
I also found another case by searching though Slack in 2031586-zen

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by katinthehatsite** [comment]
This might also be related https://href.li/?https://github.com/Automattic/jpop-issues/issues/3913#issuecomment-494982400

**Comment by katinthehatsite** [comment]
#3913

**Comment by katinthehatsite** [comment]
Also found this discussion: https://github.com/Automattic/jpop-issues/issues/3913#issuecomment-494982400

**Comment by bluefuton** [comment]
I've created a patch to fix this - D36994-code.

**Comment by bluefuton** [comment]
Fixed by D36994-code 🚢 It uses the new Apple Podcasts URL in the format:

 https://podcasts.apple.com/podcast/id1463927670
