### ISSUE TITLE
In Reader - Posts not Showing Under Tags

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#35125]
From #2181927-zen

The customer has been publishing posts to their site http://sebastienginihome.wordpress.com/ and their posts are appearing in the Reader and are marked with the appropriate tags, but if you search the tags the posts don’t appear in the tag view.

For example, when looking at this post  - https://wordpress.com/read/blogs/157205334/posts/61  -  it is showing posts under these tags: auto-stop Équateur backpacking couchsurfing Ecuador

One can find this post under couchsurfing but none of the rest of its tags.

**Comment by bluefuton** [comment]
Thanks for the report @ChrissiePollock!

The user seems to be using too many tags and categories on this post (more than 15 combined) and it's triggering our tag spam rules. This means the post will not appear in tag streams.
