### ISSUE TITLE
Editor: Instances of English appearing when site is set to another language.

### ISSUE THREAD

**Issue by susanjanec** [Automattic/wp-calypso#35143]
#### Steps to reproduce
1. Starting at URL: http://becutelina.com/
2. User sees instances of English in the Editor here - https://cld.wthms.co/TutlGh
3. They have their language set to `ZH TW` for their site.

I do see some instances of English and then Chinese. Is everything supposed to be in Chinese or are these areas English? They said that they didn't change the language on their end and seeing the English instances all of a sudden and want to know why.

**Comment by lsl** [comment]
Tried a few different scenarios but could not reproduce. I'm guessing some kind of caching issue might be the cause. Does the problem continue after a hard refresh of the page?

**Comment by donalirl** [comment]
I changed the title of this issue as it seems to be affecting more languages than just ZH TW.

In #14419843-hc, we have a case where the interface and site language are both set to German, but a lot of the editor experience is appearing in English when it should be German. 

See this screenshot: https://cld.wthms.co/7sbTqT

Apparantly the editor experience was in German up until a few weeks ago.

**Comment by mmtr** [comment]
Seems this has been accidentally caused by the removal of an unused plugin done in D31054-code. I restored the translations file in D31275-code, and the translations appears back in GlotPress but we still need to deploy them.

More context in pxLjZ-5ri-p2

**Comment by mmtr** [comment]
After deploying the strings it looks like everything is mostly translated now.

**Comment by lakellie** [comment]
Hi @mmtr! Can I confirm if this is supposed to be fixed in production now, including for Atomic sites? I just spoke to a user in chat #14305928-hc who is seeing a mix of Japanese and English on their Atomic site in Gutenberg (Calypso). I SSP'ed and was able to replicate: https://cld.wthms.co/ka17B1

**Comment by mmtr** [comment]
Thanks for the report @lakellie. It seems that not all the translations were deployed yesterday and there are some languages like Japanese that can still see the editor partially untranslated.

I requested a deploy for those languages in pxLjZ-5ri-p2#comment-16607

**Comment by donalirl** [comment]
It looks fixed for the user I reported above in #14419843-hc. Thanks!
