### ISSUE TITLE
Import: Can't upload export file into IE11

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#3515]
#### Steps to reproduce
1. In Windows IE 11, starting at URL: https://wpcalypso.wordpress.com/settings/import
2. Select "Start Import" and drag a file to the drag/drop box or click and select the file to import

#### What I expected
The file will start to upload

#### What happened instead
There was no response in the UI, and the error `Object doesn't support property or method 'find'` appeared in the console:

<img width="454" alt="screen shot 2016-02-23 at 12 59 14 pm" src="https://cloud.githubusercontent.com/assets/8658164/13266528/5b999540-da2d-11e5-85b5-ed4c1107a4d9.png">

The same issue occurred both when I tried to drag/drop the file, and when I clicked and selected the file to upload.

#### Browser / OS version
Windows 8.1, Internet Explorer 11

**Comment by BandonRandon** [comment]
Confirmed this is still an issue with IE 11. Tested on Windows 10 as well.  Setting priority to normal.

**Comment by lancewillett** [comment]
Removing from high priority since import isn't being actively worked on right now.

**Comment by dmsnell** [comment]
All: Sorry for the neglect on this one. Please see #5736 for a fix - it's a relatively easy one I believe. Will merge after the reviews/tests.

**Comment by lancewillett** [comment]
Tested the fix, works nicely. 👍 🙇
