### ISSUE TITLE
FSE: Add default About and Contact pages in Signup

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35176]
I know this is technically not FSE, however:

* We should be adding About and Contact pages by default to all new sites. We know these are the most popular, and it's currently easier to delete a page, than add a new one.
* Doing this will flesh out the navigation block since it auto populates with available pages.
* In future iterations we will offer in-editor ability to add/edit/remove pages without leaving the editor, that will build on this.

This should be done before v1 launch depending on how hard this is to switch on in headstart. @apeatling will contact the start folks to see how to fit this in, but we should also learn how this works.

See p58i-7Xz as an example of why this is important.

**Comment by michaeldcain** [comment]
> to all new sites

Is this all sites in the business segment, or all sites period (business, blog, and professional)

> how hard this is to switch on in headstart

The quickest way currently would be to run through the vertical starter sites and publish a new default contact and about page using the template selector. Then @Automattic/zelda can run the script to update the annotations.

**Comment by apeatling** [comment]
> Is this all sites in the business segment, or all sites period (business, blog, and professional)

We can start with the business segment only, since we're launching with Modern Business support.

> The quickest way currently would be to run through the vertical starter sites and publish a new default contact and about page using the template selector. Then @Automattic/zelda can run the script to update the annotations.

That sounds great :+1:

**Comment by apeatling** [comment]
This would need to be part of our launch A/B test, and not for everyone. https://github.com/Automattic/wp-calypso/issues/35181

**Comment by apeatling** [comment]
There's also onboarding preview work to have these pages show up in the preview in onboarding, but let's leave that off for v1 launch.

**Comment by vindl** [comment]
Another option would be to have this insertion handled in FSE plugin (or themes) in a similar fashion that we do for header and footer now. We'd have to fetch corresponding SPT content for Content and About page from the API (if available).

Not sure how much work that would entail, so doing what @michaeldcain proposed could still be easier/faster.

**Comment by ramonjd** [comment]
> Then @Automattic/zelda can run the script to update the annotations.

Let our team (Zelda) know when you're done with the verticals sites, and we can coordinate.

> This should be done before v1 launch

What's the timeline?

**Comment by vindl** [comment]
> Let our team (Zelda) know when you're done with the verticals sites, and we can coordinate.

We haven't worked with vertical sites so far, are there any docs available to get us up to speed?

> What's the timeline?

It would be great if we could land this by Monday, to unblock us for usability testing and internal call for testing.

**Comment by ramonjd** [comment]
> are there any docs available to get us up to speed?

Check out the info under the heading **The lifecycle of a vertical Headstart annotation** at PaWIov-3k-p2

There's a bit more faffing before things can go into production (translations and so on)
 however this should be enough to get you started, and at least generate the annotations for internal testing.

I'm not reliable over the next week due to some relocation-related AFK, but ping
our team @Automattic/zelda if you have questions. Or compliments. Or gifts.

**Comment by apeatling** [comment]
All page templates are now translated into 15 languages, so we should be okay there.

**Comment by vindl** [comment]
Proposed creating from FSE plugin in https://github.com/Automattic/wp-calypso/pull/35225. If that turns out to be insufficient, we'll look into Headstart.
