### ISSUE TITLE
FSE: Allow switching between pages in the editor

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35177]
Users should be able to:

1. Create a new page
2. Change to an existing page

When inside of the editor experience. We have this existing mockup of that experience

<img width="872" alt="Screen Shot 2019-08-06 at 2 45 45 PM" src="https://user-images.githubusercontent.com/1464705/62579532-e2032300-b858-11e9-99e1-e8f6f79f2df7.png">

We should also update the navigation block to support clicking on a page title to change pages in the editor. Also consider if it should include adding a new page.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
