### ISSUE TITLE
Full Site Editing: allow easier access to support Call for Testing

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#35179]
We need to find an easier way to provide folks access to FSE internally, to make it easer for them to test the flows during Call for Testing. Sandbox access and adding blog stickers manually shouldn't be a requirement.

Here are a couple of options we could do this:

1. Make it always work on Horizon. (preferred)
2. Add MC tool for applying blog stickers to the site.
3. Offer instructions for setting blog sticker via API endpoint (WP.com Developer Console).
4. Some other option that I haven't considered. :)

**Comment by vindl** [comment]
I'm not sure we'll be able to always enable this on Horizon easily. We could do it for Gutenframe, but that's because we can pass the environment parameter to the iframe. However, this has to affect all of Calypso, and not just the Gutenframe.

Alternatives that are viable and will require less time:

1. Enable this for all proxied users or a12ns - it's probably fine since we are going to run an announcement post and CfT so it's less likely that folks will get confused.

2. Direct them to developer console to add stickers to their test sites.
<img width="703" alt="Screenshot 2019-08-08 at 18 03 26" src="https://user-images.githubusercontent.com/1182160/62718953-2af8da00-ba07-11e9-8975-280852256609.png">
The problem with any sticker adding method (MC tool included) is that it makes it hard to test new site creation flows. They'd likely have to pick blog id and add a sticker at some specific time in that process.


cc @apeatling @gwwar For thoughts. I'm in favor of option 1.

**Comment by mattwiebe** [comment]
After some good Slack discussion, our strategy will be to create a signup flow, enabled only in Horizon, that will create a new site with the `full-site-editing` sticker applied. This will require a small, accompanying backend patch, but this work will be productive towards the eventual opening up of FSE more generally.
