### ISSUE TITLE
FSE: Implement A/B test to allow 10% rollout [3]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#35181]
We need to provide a way to roll this feature out to 10% of users to start with. We should be using A/B testing framework from Calypso if at all possible (will limit this to `en` users only by default, which is desirable since we haven't resolved i18n task yet).

Note that we need to make sure Private by Default is enabled, and that related Grow/Customer Home tests are disabled.

**Comment by mattwiebe** [comment]
D31339-code should have this now :)

**Comment by vindl** [comment]
Landed in D31339-code.
