### ISSUE TITLE
Earn: WordAds without Premium Plan Users Locked out 

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#35195]
#### Steps to reproduce
1. Starting at URL: `/earn` on a site with WordAds but without the Premium Plan

I'm prompted to upgrade to the Premium Plan, when I should be able to access my WordAds dashboard by clicking this button. Instead, I'm redirected to Checkout. 

<img width="574" alt="Screenshot 2019-08-07 at 17 02 33" src="https://user-images.githubusercontent.com/43215253/62638351-2ebc2c00-b935-11e9-9136-4ed6c153c2e1.png">

**Comment by pablinos** [comment]
This is interesting and thanks for fixing it @cphilleo!

Could I just ask why a site has ads setup and isn't on a paid plan? Is it that Ads gets setup and then the plan lapses? Whatever the reason it makes sense to change the logic here.

**Comment by cphilleo** [comment]
@pablinos plan lapsing is one scenario. It's a little complicated, but ads aren't tied to plans per se. The requirements for ads are:

1. Site has a domain name
2. Meets certain traffic requirements
3. Has content that is "family friendly"

This means that even a free site with a mapped domain can technically apply and be accepted. By upgrading to a Premium or Business plan we allow the site to be auto approved, essentially skipping the traffic requirement step while keeping the others.

We're currently working on an updated application and onboarding flow that will hopefully make the experience easier and more straightforward to navigate.

**Comment by Aurorum** [comment]
> Could I just ask why a site has ads setup and isn't on a paid plan?

Most sites have a paid plan to use WordAds, but there is an option for sites without a paid plan but a custom domain to apply to have WordAds. If the site reaches a traffic requirement, then it'll be accepted into the programme: https://wordads.co/faq/#eligibility

Whilst you need a paid plan to have a custom domain now, in the past, it was possible to buy it as a standalone purchase, and people who did that can continue renewing that domain without upgrading to a paid plan. :)

**Comment by Aurorum** [comment]
whoops, sorry for the overlap!

**Comment by pablinos** [comment]
Got it! Thank you both for clarifying. It’s good to learn about all these edge cases
