### ISSUE TITLE
GIF block mixed media HTTPs errors

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#35203]
The following behavior can be found on both Atomic and simple sites.

#### Steps to reproduce
1. Create page/post and add a GIF block to it
2. Add the URL to a GIF in the box, like this one from Giphy: `https://media.giphy.com/media/srWI1wDmsGBVK/giphy.gif`
3. Save the changes and publish the page
4. We will notice that the GIF will not load (unless your browser security settings are low) and we get mixed media errors in the browser inspector, even though the GIF URL we added to the block was HTTPS. It seems like Giphy, Jetpack, or something is trying to force http.

As a sidenote, if we view the public page once the GIF is added we do see an empty space where the GIF should be, and if we hover over it we do see Giphy content (if using Giphy) still appear. 

#### What I expected
For GIFs to load, especially when providing an HTTPS address to the GIF block

#### What happened instead
The GIF is being serves over HTTP instead of HTTPS, so it isn't loading due to security concerns.

#### Screenshot / Video
![Screen Shot 2019-08-07 at 4 00 12 PM](https://user-images.githubusercontent.com/33190975/62657584-74c0c200-b92c-11e9-92e5-41324adf7b18.jpg)

#### Context / Source
#user-report in 2257992-zen

**Comment by suyogyashukla** [comment]
Letting the user know we're still working on this.

**Comment by nagpai** [comment]
Giphy links end with giphy.gif for all images and use a script to render the GIF image, hence the GIF block will not work for this. 

Copying the Giphy image link directly to the editor automatically changes it to an `Embed` block and the GIF runs fine. 

The user will however need to use the correct type of GIF link within Giphy as shown below

![Screen Shot 2019-08-11 at 13 04 02](https://user-images.githubusercontent.com/4162931/62831215-392e3c80-bc39-11e9-89e5-5fa39b73a406.png)

Marking this as closed for now
