### ISSUE TITLE
Media & Text Block: Can't change background and text color for 2019 and business themes

### ISSUE THREAD

**Issue by brookewp** [Automattic/wp-calypso#35207]
#### Summary

When using 2019 or one of the business themes, the media & text block doesn't allow you to edit the text or background color. It changes in the editor but doesn't show in the preview or when published. You can also see the right classes are being added as well.

I was unable to replicate this on a self-hosted site w/o JP or with other WordPress.com themes.  Only on WordPress.com with the themes mentioned above. 

Thought this seemed like high priority because customers can't use edit our new templates and use our newer themes properly. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/[site-address-here]
2. Add media & text block to a page
3. Change the background color via block settings (I tried #c33c80). 
4. See the color change in the editor
5. Preview or publish the page to see that the background color doesn't reflect changes in editor

#### What I expected

To be able to change the background color or text color via block settings. 

#### What happened instead

The color remained the same as before the changes were applied. 

#### Screenshot / Video

Example of changed background color and text in the editor: 

<img width="1944" alt="Screen Shot 2019-08-07 at 3 02 35 PM" src="https://user-images.githubusercontent.com/35543432/62660966-6f5f7980-b924-11e9-9009-8a9e401071c2.png">

Example of it published: 

<img width="1717" alt="Screen Shot 2019-08-07 at 3 02 11 PM" src="https://user-images.githubusercontent.com/35543432/62660985-7d14ff00-b924-11e9-9061-35980f908b67.png">

#### Context / Source

First reported by a user here: hc-#14317124
#user-report

**Comment by iamtakashi** [comment]
We've been discussing the related matter here: https://github.com/Automattic/wp-calypso/issues/35842

**Comment by noahtallen** [comment]
Closing this as most of the above theme work has been finished. (In particular, this is no longer an issue with FSE-compatible themes)

**Comment by gwensmithx** [comment]
I ran into another instance of this with Modern Business theme, which I realize is retired now but should it still be acting this way? Same steps as Brooke's initial issue. 2397678-zd. Added media & text block, tried to set background colour in editor and looks good in editor but in preview and published it's stuck on a black background.

**Comment by noahtallen** [comment]
Honestly, we retired those themes because there were issues like this which were difficult to solve. I don't think we're planning on updating them since new themes like Maywood resolve not only this issue, but many others similar block editor issues.

**Comment by iamtakashi** [comment]
@noahtallen is correct. All six business themes have been retired and will no longer be updated.

WP.com has started using Gutenberg plugin that changes and improves at a very fast pace, there was no way to maintain those themes with the way that they were built.
