### ISSUE TITLE
Marketing survey for domains mentions plans

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#35224]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/
2. Select a domain to view its purchase management page.
3. Turn off toggle for the auto-renew

#### What I expected

I expected the survey to mention domains.

#### What happened instead

The survey mentions plans.

#### Screenshot / Video

1. Screen recording - https://cloudup.com/c-BamUMLv1f

2. 

<img width="789" alt="Screenshot 2019-08-08 at 7 26 15 PM" src="https://user-images.githubusercontent.com/1269602/62709163-749af200-ba12-11e9-90fd-87aa1611369a.png">

#### Context / Source

This is related to the survey change introduced in https://github.com/Automattic/wp-calypso/pull/35044

**Comment by mktgmolly** [comment]
Yes, I think we can just swap out the word "plan" with "domain" in this case but we'll also want to make sure we can pull the responses separately since this is specific to domains.
