### ISSUE TITLE
(3P) SPT: scroll dynamic preview on hover

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#35223]
Currently, only a small portion of each template is visible in the thumbnail preview. It is difficult for a user to tell what they will get once they select a certain template.

To get an improvement relatively quickly, it has been suggested that we could let the dynamic preview scroll inside the thumbnail area on hover. 

This could look something like this (scrolling considerably slower though):

![scroll-on-hover](https://user-images.githubusercontent.com/1562646/62708515-ddbf3d00-b9f3-11e9-9a4c-09743e690d6f.gif)

## Possible iteration

@mtias  shared the following design exploration. In this case, the three-column layout would make way for a two-column layout that allows for a larger preview. The preview could be scrolled as well.

![image (1)](https://user-images.githubusercontent.com/1562646/62708784-5d4d0c00-b9f4-11e9-9a35-f7d4bab2cbfe.png)

## Considerations

@shaunandrews is contemplating removing the preview entirely in favor of a way to quickly change between templates. If this is a route we're ultimately going down, it is questionable whether investing time in multiple iterations of the preview makes sense.

![image](https://user-images.githubusercontent.com/1562646/62708952-b5840e00-b9f4-11e9-9d8a-5e29df1f84ef.png)

**Comment by obenland** [comment]
@frontdevde We're already doing that for the large preview. Can that same functionality be reused if/when we switch to block preview thumbnails?

**Comment by obenland** [comment]
See p1571153655467200-slack-ajax.
