### ISSUE TITLE
Full Site Editing: support wpcom naming in supported themes

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#35236]
In our `SUPPORTED_THEMES` constant [here](https://github.com/Automattic/wp-calypso/blob/a8dec8dddf0af275d99558854ce1cf381e6bdb7d/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L47), we only supply the slug as `modern-business`, but it will be `pub/modern-business` on wpcom.

This will cause our `is_supported_theme` method to fail and therefore `insert_theme_template_data` to not run when it should.

We could either use both forms in `SUPPORTED_THEMES` or just adjust for both cases within `is_supported_theme`.

This will be a blocker for #35179

**Comment by vindl** [comment]
@mattwiebe I already added `normalize_theme_slug` that's used when setting the `theme_slug` in that class https://github.com/Automattic/wp-calypso/blob/5483ab163aab05b2d112e9802c6f947139b3bd10/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L122.

Feel free to reopen if you think that this doesn't help though.
