### ISSUE TITLE
Color Schemes: Hovering over Home icon shows light gray bottom border

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#35231]
#### Steps to reproduce
1. Log in to WordPress.com and change your color scheme to any of the darker/colorful ones; Midnight, Sunset, Ocean, etc. This can be done under Me -> Account Settings.
2. Hover over the "home" icon for your current site. Note the gray bottom border; it sticks out particularly on the darker color schemes.

#### What I expected

For there to be no border; the icon background should be a solid color.

#### Browser / OS version

Chrome 76 for Mac

#### Screenshot / Video

<img width="273" alt="Screen Shot 2019-08-08 at 11 07 28 AM" src="https://user-images.githubusercontent.com/2124984/62716299-ed2c8f00-b9cf-11e9-85e5-bfec6f1f0832.png">

Found while I was working on another part of the sidebar, no follow-up necessary.

**Comment by Aurorum** [comment]
Odd, I can't reproduce this

<img width="253" alt="Screenshot 2019-08-08 at 16 52 22" src="https://user-images.githubusercontent.com/43215253/62718019-e9fbc800-b9fc-11e9-8509-fd1ae5d7e782.png">

**Comment by sixhours** [comment]
I can't reproduce it in Firefox, but it does something completely different in Safari:

<img width="273" alt="Screen Shot 2019-08-08 at 11 56 52 AM" src="https://user-images.githubusercontent.com/2124984/62718338-a93b8900-b9d3-11e9-9d8f-9dca31a04841.png">

**Comment by sixhours** [comment]
Hah, I just realized this is related to the changes I was making. 🙃 The hover icon is absolutely positioned, so if the height of the container is off, it won't align properly. Closing, since this is something I'll have to wrestle with as part of my changes.
