### ISSUE TITLE
(5P) FSE: Explore performance improvement options for BlockPreview

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#35233]
This should be a rather timeboxed task to determine how we can cut down the template selector load time to under 1 second. If we find that it's not possible for us to do so, let's go forward with #35232.

Let's consider researching the following items:

- [ ] Only loading visible contents (maybe the first X Blocks)
- [x] ~Dynamically loading full template Blocks only on :hover (interaction)~
- [x] Ability to define X number of Blocks to load
- [x] Memoization (59beaa824bf0d9e04b83921089896414a482d5f5)
- [x] Small images for thumbnails preview
- [x] Compare performance loading static images
- [ ] Try adding a new `thumbnail` field in the endpoint response
- [x] Move parsing templates content to higher component: https://github.com/Automattic/wp-calypso/pull

**Comment by getdave** [comment]
Do we have input from @youknowriad on possible avenues to explore here in terms of performance?

**Comment by getdave** [comment]
Some avenues:

* Only loading visible contents (maybe the first X Blocks)
* Dynamically loading full template Blocks only on `:hover` (interaction)

**Comment by retrofox** [comment]
[I've defined the number of blocks](https://github.com/Automattic/wp-calypso/pull/35022/commits/2445d1a8662355f0a66e95604afb8e4133228152) to load until 10.

**Comment by obenland** [comment]
Optimized images and updated json annotation for EN: D31446-code
