### ISSUE TITLE
FSE: update site creation preview to reflect a newly generated site

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35239]
When going through WordPress.com/start and we generate a site with the new FSE flows, the site creation preview doesn't fully reflect the site that's generated. (For example missing items in the header).

<img width="1279" alt="Screen Shot 2019-08-08 at 12 24 07 PM" src="https://user-images.githubusercontent.com/1270189/62731626-798e8000-b9d7-11e9-8c3a-2c610bfcd579.png">

**Comment by davipontesblog** [comment]
Closing in favor of the Gutenboarding implementation in dotCom.
