### ISSUE TITLE
FSE: Use the top level template classnames not data attribute

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35246]
In the FSE style.scss I see:

<img width="501" alt="Screen Shot 2019-08-08 at 1 37 19 PM" src="https://user-images.githubusercontent.com/1464705/62736178-a6e02b80-b9e1-11e9-9e60-c6dc603c75f4.png">

Unless there is a specific reason for this, it should use the new top level classnames to target our blocks, not data attribute selectors as this is fragile.

**Comment by noahtallen** [comment]
For whoever picks this up, the relevant code is:
https://github.com/Automattic/wp-calypso/blob/0a3e4474cd1060ee3cb462ba51c41b7ccedb0f39/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/index.js#L41-L49

So `.template__block-container` should do the trick
