### ISSUE TITLE
FSE: Header block spacing is inconsistent

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35257]
When editing on a page the header block spacing looks like this:

<img width="1164" alt="Screen Shot 2019-08-08 at 2 31 53 PM" src="https://user-images.githubusercontent.com/1464705/62739332-6a183280-b9e9-11e9-8f41-0c6c4f32fffb.png">

When I click through and edit the header, the block spacing looks like this:

<img width="1209" alt="Screen Shot 2019-08-08 at 2 32 00 PM" src="https://user-images.githubusercontent.com/1464705/62739350-743a3100-b9e9-11e9-875b-6cc3215d5145.png">

Both of these views should have consistent spacing between blocks.

**Comment by noahtallen** [comment]
It's also different on the front end:

**Page Editor**
<img width="215" alt="Screen Shot 2019-08-08 at 3 26 34 PM" src="https://user-images.githubusercontent.com/6265975/62741757-f0844280-b9f0-11e9-9c39-1a57536fa71f.png">

**Template Editor**
<img width="343" alt="Screen Shot 2019-08-08 at 3 25 35 PM" src="https://user-images.githubusercontent.com/6265975/62741727-db0f1880-b9f0-11e9-8156-2e79d90b2f7a.png">

**Front End**
<img width="238" alt="Screen Shot 2019-08-08 at 3 25 41 PM" src="https://user-images.githubusercontent.com/6265975/62741734-e19d9000-b9f0-11e9-977c-2f05da0148d5.png">

**Comment by apeatling** [comment]
Front end will be harder, I think at minimum it should be identical in the page and header editing views.

**Comment by glendaviesnz** [comment]
> Front end will be harder, I think at minimum it should be identical in the page and header editing views.

Will have a look at front-end once we have decided on approaches outlined in https://github.com/Automattic/wp-calypso/pull/35296
