### ISSUE TITLE
Earn Section: Rework 'Thank You' page promo

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#35252]
<img width="720" alt="Screenshot 2019-08-08 at 07 51 45" src="https://user-images.githubusercontent.com/96462/62737283-555a8f80-ba27-11e9-937b-b11cc4ec4c50.png">

On the premium plan's 'Thank You' page we also promote WordAds as the way to monetise your site. It may be better to signpost the customer to the new earn section here and include this card on the other plan's pages too.

**Comment by davemart-in** [comment]
I've got this on my list now. Thanks @pablinos!

**Comment by davemart-in** [comment]
After considering this for a bit, I think we should punt this task for the v1. 

My worry is that we'd have to factor in logic for whether someone has access to Customer Home or not and change the copy and CTA accordingly based on that condition. It seems a tad too complicated for now. 

My vote would be to hold off on this until we've released Customer Home to all users.

**Comment by davemart-in** [comment]
@pablinos I got my wires crossed on this one. I thought this one was related to Customer Home. I'm going to likely close this issue out and open up 2 fix the flows issues in it's place. That way they will still be on my radar, but someone else might get to them before I get back from parental leave.

**Comment by cbauerman** [comment]
I am going to pull this out of the GM fixing the flows project since it would involve copy ( unless there is existing copy to reuse, please point out in that case! )
