### ISSUE TITLE
FSE: Site tagline should come above logo Image block in header

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35258]
Our current Modern business header puts the logo image (and placeholder) above the site tagline:

<img width="1430" alt="Screen Shot 2019-08-08 at 2 42 02 PM" src="https://user-images.githubusercontent.com/1464705/62739891-ef501700-b9ea-11e9-8b09-57b08c1a0027.png">

Based on the reference graphic it should be below the tagline by default:

<img width="939" alt="Screen Shot 2019-08-08 at 2 42 45 PM" src="https://user-images.githubusercontent.com/1464705/62739900-f70fbb80-b9ea-11e9-99e9-563bcbead7f6.png">

**Comment by noahtallen** [comment]
I updated the demo site with this and ran the script to update the template in the prod API. Should work correctly on new sites once the FSE plugin is synced
