### ISSUE TITLE
Reader: site block message can appear out of view

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3525]
When choosing 'Block Site' from inside a post stream using the post options menu, the blocked post is replaced with a post card explaining what's been blocked:

<img width="793" alt="screen shot 2016-02-24 at 15 03 07" src="https://cloud.githubusercontent.com/assets/17325/13273368/c0ff04bc-db07-11e5-9516-43a9623c94a8.png">

This card can appear out of view, which is disorienting to the user. Video showing this happening:

https://cloudup.com/i9BTY3EoHuI
- The card should be scrolled into view into it's not visible
- The spacing on the 'blocked' card needs fixing
- The cursor should be 'pointer' when hovering over the undo link

**Comment by tellyworth** [comment]
I've re-tested this and I'm pretty confident it's no longer an issue. The message is always visible regardless of screen size, looks fine, and the pointer is correct. No idea when it was fixed.

**Comment by bluefuton** [comment]
Thanks @tellyworth! I reckon we fixed this one during the Reader Refresh at the tail end of last year.
