### ISSUE TITLE
FSE: Template hover states are still visible

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35250]
Hovering over the header or footer template block still shows:

<img width="596" alt="Screen Shot 2019-08-08 at 1 50 16 PM" src="https://user-images.githubusercontent.com/1464705/62736989-9fba1d00-b9e3-11e9-921c-2508c82731b0.png">

This is hidden for the content block and should be hidden here too.

**Comment by noahtallen** [comment]
Ah I thought we wanted to reenable this per discussion in https://github.com/Automattic/wp-calypso/pull/35158?

**Comment by apeatling** [comment]
Thanks, yes I glossed over this point. Using it though it seems completely redundant to me, what value does it add? I don't think we should have a hover state if it's not adding any value.
