### ISSUE TITLE
Reader: tables in content should have some padding by default

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3526]
When a table is rendered in a post body in Reader, it does not appear to have any padding:

<img width="797" alt="screen shot 2016-02-24 at 09 45 55" src="https://cloud.githubusercontent.com/assets/17325/13273400/0bf30e96-db08-11e5-8750-ebb852824c8e.png">

The cells should be padded by at least a few pixels by default.

**Comment by blowery** [comment]
Test post: http://calypso.localhost:3000/read/post/feed/25320833/937448000
