### ISSUE TITLE
Gutenberg: Styling Broken in Post Publish Panel

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#35286]
#### Steps to reproduce
1. Starting at URL: `https://wordpress.com/block-editor/post/`
2. Click Publish

It looks like the styling isn't being imported? The Jetpack logo is missing, the notices look very odd, the width of the textarea is too narrow, and the Twitter icon isn't blue. 

<img width="310" alt="Screenshot 2019-08-09 at 22 44 21" src="https://user-images.githubusercontent.com/43215253/62810908-7e4a5580-baf7-11e9-83d0-4aaf70366520.png">

**Comment by simison** [comment]
We had an incident where some styling went missing for several blocks. This should now be fixed.

Thanks for the report!
