### ISSUE TITLE
People: searching for username with @ returns no results

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3529]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/people/team/
2. Search for a known username including @
#### What I expected

To see results with that user which includes the @
#### What happened instead

No results returned (searching without the @ returns results)
#### Browser / OS version

OSX 10.11.3 Chrome
#### Screenshot / Video

![search for alisterscott](https://cloud.githubusercontent.com/assets/128826/13278031/c459a28c-db18-11e5-8e11-30aaa1dfbd41.png)

![search for alisterscott](https://cloud.githubusercontent.com/assets/128826/13278036/cde3fa78-db18-11e5-81a9-443920993713.png)

**Comment by lancewillett** [comment]
I can repeat this — still not working with the `@` sign when searching. One solution could be just to trim that character from the query.

Testing with Mac-n-Chrome, using `testerlance` user.

<img width="856" alt="screen shot 2016-05-05 at 16 40 13" src="https://cloud.githubusercontent.com/assets/66797/15060510/18a1e1c0-12e0-11e6-95bd-cd2cf5957025.png">

<img width="791" alt="screen shot 2016-05-05 at 16 40 22" src="https://cloud.githubusercontent.com/assets/66797/15060511/1ae2d2be-12e0-11e6-9817-ee66915182e9.png">
