### ISSUE TITLE
Gutenberg on Simple Sites: Tiled Gallery block appears in one column in the editor

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/wp-calypso#35294]
#### Steps to reproduce
1. Starting at URL: any simple site with the block editor active
2. Create a post or page
3. Add the block "Tiled Gallery" and select multiple images
4. All images appear in one single column

#### What I expected

Images should appear as they do in the preview and live site - in multiple columns, as here (atomic site):

![see screen shot](https://cld.wthms.co/8NWQKp+) https://cld.wthms.co/8NWQKp

#### What happened instead

They appear in one single column, as shown here: ![see screen shot](https://cld.wthms.co/2f8P5j+) https://cld.wthms.co/2f8P5j

#### Browser / OS version
Tested this in multiple browsers and themes

#### Context / Source
#user-report : reported in #2265682-zen

**Comment by sophiegyo** [comment]
I noticed this on Saturday too and I've made sure to test on self-hosted.

Here's a video of what happens both in wp-admin and Calypso on a Simple site:
https://d.pr/HRrOGx

The problem doesn't replicate on self-hosted either (I used a jurassic ninja site with free Jetpack connected to my account): https://d.pr/xsKbRo

**Comment by sophiegyo** [comment]
Tested again after getting another ticket about it: 2270004-zen

Problem seems to be solved?

**Comment by Aurorum** [comment]
I wonder if this issue was part of the wider issue that @simison mentioned in Automattic/jetpack#13214?

**Comment by simison** [comment]
Seems so — CSS styles went missing for some blocks around August 9–13.

Everything should work well again and no data was lost. Sorry for the inconvenience! :-)
