### ISSUE TITLE
Stats: cannot print stats details pages

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#353]
Steps to reproduce:
1. Go to http://wordpress.com/stats and select a blog with a decent number of stats recorded for a given year
2. Click "Years" in the top navigation
3. Click ~~"View All"~~ the right arrow at the top right of the Posts & Pages box
4. Print the page

Results: several pages are printed but every page after page one just has duplicate data

Example printed to pdf: https://cloudup.com/cJlvH9AEJzb

<sup>Testing with Firefox 34.0 on Mac OS X Yosemite 10.10.1 logged in as design5279</sup>

Reported in http://en.forums.wordpress.com/topic/stats-classics-how-to-set/page/2?replies=45#post-2169493 by theo48 (section B)

[Update as of Mar 5: trying to print results in no content and just a printout of the sidebar only.]

![screen shot 2015-03-05 at thu mar 5 2 59 48 pm](https://cloud.githubusercontent.com/assets/1119271/6513345/4a36cf72-c348-11e4-9556-a5be3d382628.png)

**Comment by BandonRandon** [comment]
Another report of this in 330080-chat

**Comment by lancewillett** [comment]
Re-tested today with `testerlance` user, looks a bit better. :)

[Stats ‹ Lance Jetpack Test — WordPress.com.pdf](https://github.com/Automattic/wp-calypso/files/251357/Stats.Lance.Jetpack.Test.WordPress.com.pdf)

Not perfect — sidebar needs to not be printed. Good first change?

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided.

<img width="1280" alt="screen shot 2016-07-25 at mon jul 25 1 20 16 pm" src="https://cloud.githubusercontent.com/assets/1119271/17114124/cf2c22ba-526a-11e6-8e8e-0c10ba4ba17d.png">
<sup>Seen at https://wordpress.com/stats/year/posts/cute.wordpress.com?startDate=2015-01-01 using Safari 9.1.1 on Mac OS X 10.11.5</sup>

👍 for the `[Type] Good First Change ` label

**Comment by alisterscott** [comment]
Retested this today and the sidebar is not appearing and no information is being duplicated. Example: 
[Stats ‹ Eat Kibbeling — WordPress.com.pdf](https://github.com/Automattic/wp-calypso/files/560953/Stats.Eat.Kibbeling.WordPress.com.pdf)

Closing.
