### ISSUE TITLE
Reader: New style excerpts need to trim empty content

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#3531]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/blog/feed/1324099
2. Notice some excerpts have blank lines to start https://wordpress.com/read/post/feed/1324099/937760846

![screenshot](https://cldup.com/scBUtTI48N.png)

#### What I expected
No blank lines.

#### What happened instead
Blank lines

#### Browser / OS version
Chrome / Mac, but happens on all

**Comment by blowery** [comment]
Caused by #3448

**Comment by bluefuton** [comment]
Fixed in #3537.
