### ISSUE TITLE
Audit and Automate more Steps to prepare the Full Site Editing Plugin

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35313]
Every two weeks we sync changes in wpcom for https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing and sometimes https://github.com/Automattic/themes/ to prepare the plugin/themes for publishing.

1. Let's review the manual steps that this takes
2. Identify some steps that would benefit the most from automation
3. And script that

For this issue lets timebox work to a few days. We can follow up with additional and specific issues if certain improvements may take longer.

**Comment by noahtallen** [comment]
Closing since we've done this on p2 :)
