### ISSUE TITLE
Generate a matching phab diff for any Block-Editor changes

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35310]
When we make changes to https://github.com/Automattic/wp-calypso/tree/master/apps/wpcom-block-editor

Let's add a hook that can prepare the related backend patch when:
- A branch is created (for testing)
- On master merges when we note that related files have changed.

Note that any patches still need to be manually approved and landed.

For potential prior art check out how we handle this automation for Jetpack fusion patches.

See also: PCYsg-l4k-p2

**Comment by vindl** [comment]
@sirreal this might be a good candidate for the new Gutenberg platform squad?

**Comment by sirreal** [comment]
@noahtallen in case this fits with ETK related improvements.

**Comment by noahtallen** [comment]
Sure does 👍

**Comment by noahtallen** [comment]
Closing this now that I've migrated all the monorepo apps to use `install-plugin.sh`
