### ISSUE TITLE
Trustpilot logo colors are off in Jetpack checkout

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#35323]
When purchasing a Jetpack plan, the background of the checkout step is dark. New Trustpilot logo doesn't work well on this background:

<img width="1191" alt="Screenshot 2019-08-13 at 08 55 12" src="https://user-images.githubusercontent.com/87168/62918403-2c7c2680-bda8-11e9-8856-df48cdb87f24.png">

The logo was introduced in https://github.com/Automattic/wp-calypso/pull/34677 (cc @victorespigares @niranjan-uma-shankar)

#### Steps to reproduce
1. Have a Jetpack site (use e.g. https://jurassic.ninja/?create)
2. "Set up" Jetpack and choose a plan during connection flow
3. Note Trustpilot logo against the dark background at checkout step

**Comment by niranjan-uma-shankar** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/35404.

**Comment by arunsathiya** [comment]
Found a similar one for order confirmation copy - https://github.com/Automattic/wp-calypso/issues/35503
