### ISSUE TITLE
FSE: Fix styling of header on Simple Sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35358]
<img width="1190" alt="Screen Shot 2019-08-13 at 5 28 27 PM" src="https://user-images.githubusercontent.com/1270189/62986315-e054d480-bdef-11e9-9f4f-05c0e2569f8a.png">

As a new user going through https://horizon.wordpress.com/start/test-fse

The header block is missing the class `template__block-container` causing the visual glitches above.

**Comment by apeatling** [comment]
This is also true for the footer block.

It seems this code is not working:

https://github.com/Automattic/wp-calypso/blob/1ed592a8f0d557f2d21f80c83d276abf18ab1a3a/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/index.js#L41

**Comment by gwwar** [comment]
The hook is running, but maybe the block attribute classnames are overriding this property:

<img width="1647" alt="Screen Shot 2019-08-14 at 9 32 20 AM" src="https://user-images.githubusercontent.com/1270189/63038779-c5797300-be76-11e9-89e0-89d9c171d9cd.png">

**Comment by noahtallen** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/35386
