### ISSUE TITLE
Domains: Unregistered domain with unsupported TLD incorrectly showing as taken when trying to register

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#35369]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/{site_URL}
2. Click Add domain
3. Search for a domain that is not already registered, using a TLD that's not available for registration on WordPress.com

#### What I expected
To see a message saying the TLD is not supported, and maybe a prompt to map it after I register it somewhere else.

#### What happened instead
I see a message stating that the domain is taken, and prompting me to map it if I already own it.

#### Screenshot / Video
Searching for a .au domain that doesn't exist:

![Domain_Search_‹_kokkiestrialtestsite_—_WordPress_com](https://user-images.githubusercontent.com/11873759/63022472-4d757200-bea3-11e9-982d-2d22d057c60a.png)

Searching for a .com.au domain that is registered has an identical error message:

![Domain_Search_‹_kokkiestrialtestsite_—_WordPress_com](https://user-images.githubusercontent.com/11873759/63022442-39317500-bea3-11e9-9243-f633d1878f0c.png)

Could this be related to the changes made in #34605?

#### Context / Source

Reported by a forums volunteer in p8HJWS-qb-p2

**Comment by donalirl** [comment]
I came to report this as well. These domains are definitely not taken:
![Screen Shot on 2019-08-23 at 14_24_48](https://user-images.githubusercontent.com/30727666/63566906-5ad0e180-c5b2-11e9-9817-2245fe7c8f8d.png)
![Screen Shot on 2019-08-23 at 14_24_33](https://user-images.githubusercontent.com/30727666/63566909-5e646880-c5b2-11e9-8363-7506fa87c96c.png)

Seen in #14753457-hc

**Comment by donalirl** [comment]
Keeping this open, because it's not right that we present domains as "taken" when they're not. Is this a quick validation fix, or is it more complicated under the hood?

**Comment by klimeryk** [comment]
It is more complicated under the hood - we cannot reliably check the availability of TLDs we don't support registering. ccTLDs (which is the most often case it seems) are also the least reliable too.

However, we did fix the bug where unsupported TLDs were mistakenly reported as always taken:

<img width="1060" alt="Screenshot 2021-02-09 at 22 09 36" src="https://user-images.githubusercontent.com/3392497/107435089-9acbb180-6b23-11eb-9186-38319c8acf98.png">
<img width="1071" alt="Screenshot 2021-02-09 at 22 09 52" src="https://user-images.githubusercontent.com/3392497/107435092-9b644800-6b23-11eb-8ff3-3af939d995b4.png">

It's not perfect, but in most cases that's what the user probably wants/expects (has a ccTLD registered elsewhere and want to connect it to a WPCOM site). So I'll mark this as resolved 🙇‍♂️

**Comment by donalirl** [comment]
Thank you @klimeryk!

**Comment by darcie** [comment]
Thanks, @klimeryk! Glad to get an update on that.
