### ISSUE TITLE
FSE: The editor sidebar is closing when clicking on the header

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35378]
When I first enter Gutenberg as a new user, and click on a block in my header, the sidebar closes. This is unexpected.

**Comment by noahtallen** [comment]
This will be resolved in https://github.com/Automattic/wp-calypso/pull/35387

**Comment by Copons** [comment]
@noahtallen Thanks for assigning me while I wasn't paying attention! 🙇 
I came here to do it myself and it was already done: SUPER CONVENIENT!! 🎉

**Comment by noahtallen** [comment]
Haha no prob! I noticed a few of these reports would be covered by everyone's existing work, so I took the liberty of handling the gh organization for them 😁
