### ISSUE TITLE
FSE: Deleting template post types crashes editor

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35381]
If you empty out your wp_posts table and try adding a new page, the editor will hang and expire available memory.

I expect there needs to be a check to see if templates exist before trying to load.

This is an unlikely scenario, but stranger things have happened.

**Comment by gwwar** [comment]
Bumping to normal priority, since the error state is very bad.

**Comment by apeatling** [comment]
I don't think we need to fix this before the 10% launch, going to move.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
