### ISSUE TITLE
FSE: Footer is aligned center on front end, but to the left in the editor

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#35389]
#### Steps to reproduce
1. Use a site with FSE enabled on the modern business theme
2. Navigate to the page editor. The footer style looks like this, with the template blocks left aligned:
<img width="1616" alt="Screen Shot 2019-08-14 at 1 09 49 PM" src="https://user-images.githubusercontent.com/6265975/63052679-d33df100-be94-11e9-9c57-ba5cc65deb54.png">
3. Click preview. The footer style looks like this, with the template blocks centered:
<img width="1641" alt="Screen Shot 2019-08-14 at 1 10 13 PM" src="https://user-images.githubusercontent.com/6265975/63052720-e81a8480-be94-11e9-819e-85b0538da3df.png">

**Comment by glendaviesnz** [comment]
Fixed by https://github.com/Automattic/themes/pull/1256
