### ISSUE TITLE
Full Site Editing: supporting existing users on Dotcom

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#35399]
**[Note: I consider this a blocker that we should figure out before enabling support for multiple themes]**

This one has to do with the order of plugin and theme activation, and how that affects template data population. This is important since if the template data is not present, the plugin will just bail, and things will look like it's not active.

**Self-hosted sites:**

On self-hosted sites this is already sorted. We check whether template data needs to be inserted both on plugin's `register_activation_hook` ([#](https://github.com/Automattic/wp-calypso/blob/dcfae35b54af61b2004548c5ac72c68bb71703cc/apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php#L117)) and during theme activation ([#](https://github.com/Automattic/wp-calypso/blob/dcfae35b54af61b2004548c5ac72c68bb71703cc/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L60)).

That means that regardless of theme and plugin activation order, we will have the data ready once the appropriate conditions are met, namely:

- FSE plugin is active,
- FSE supporting theme is active.

**Dotcom sites:**

This are a bit more complicated on Dotcom because `register_activation_hook` won't work there, and the plugin is not always active (we gate it based on sticker).

That means that if someone has the Modern Business theme active, and we enabled FSE for them by adding the sticker - apparently nothing will happen, since the templates are not present we will bail before showing FSE flows. For comparison, this would trigger the plugin activation hook on self-hosted WP installs and populate the data (as explained above), but in Dotcom environment that hook is not firing.

This is not an immediate problem because the first rollout phase assumes new users and sites, so they will always have the plugin active before the Modern Business is activated during site creation. It will start being an issue once we start enabling this for existing users that already have FSE supporting theme active - with current setup they'd have to toggle the theme activation to get the template data.

**Possible solutions**

1. We can try to simulate what we did before with template population code in themes, while still avoiding duplicating that functionality across each theme that needs to support FSE.

Similar to the code and hook [here](https://github.com/Automattic/themes/pull/1062/files#diff-4a8680b203b5b10f0b51630d479dd956R97), we could check if `WP_Template_Inserter` file exist in plugins folder (with some complications due to versioning now), include it, and run the template population method that it provides ([#](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php#L139)). Since this file should always be present on Dotcom, it will work regardless of whether FSE is active (when sticker is not applied).

One problem with it is that it that it won't help with users that have activated Modern Business say 6 months ago, or at any time before the new code is committed.

2. Add something like `activate_fse_on_site` method on Dotcom that should apply the sticker and execute template data population. This resolve the issue mentioned in (1), but the drawback of this is that we'd have to loop through all sites that use Modern Business and execute it (will likely need a script and batching).

3. Make opt-out/opt-in functionality for FSE - that way we can trigger the population when the customer is opting in.

4. Switch from `after_switch_theme` hook ([#](https://github.com/Automattic/wp-calypso/blob/dcfae35b54af61b2004548c5ac72c68bb71703cc/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L60)) to something like `init`, or `after_setup_theme` that runs on each load. That way it's guaranteed to pull in data when needed, but it's more risky since if there is something wrong in the logic, we might end up crippling the site by doing API fetch on each page load.

The above is unlikely to occur because we check for the option when template data is populated. The option will be cached which ensures a quick bail before that happens. However, we must verify that we can't end up in a situation where we attempt the request and fail to set the option (due to errors in the middle of the process), effectively repeating this on each page load.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
