### ISSUE TITLE
Reader: site icon missing in Reader even though it has been set in WP Admin > Settings

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#354]
The site icon (blavatar) is missing in the blog feed view at https://wordpress.com/read/blog/feed/18785507

![screen shot 2015-07-10 at fri jul 10 10 01 36 pm](https://cloud.githubusercontent.com/assets/1119271/8631830/ab286fe6-274f-11e5-9233-91033f7ba9b3.png)
<sup>Seen at https://wordpress.com/read/blog/feed/18785507 using Firefox 39.0 on Mac OS X 10.10.4 logged in as user744 proxied.</sup>

I tried the following testing steps to see if I could reproduce the issue by adding the WordPress.com `/feed/` URL manually, but I couldn't reproduce the problem that way:

1. Go to https://wordpress.com/following/edit/
1. Follow https://matt.wordpress.com/feed/
1. Go to https://wordpress.com/
1. Click the site title "Matt on Not-WordPress" on one of the posts from that blog
1. Check to see if the blavatar appears normally in the blog feed header card

<strong>Result:</strong> blavatar looks good here. Why is the URL different though? Here it's `/read/blog/feed/25814` and before it was `/read/blog/feed/18785507`.

![screen shot 2015-07-10 at fri jul 10 10 07 17 pm](https://cloud.githubusercontent.com/assets/1119271/8631843/3a5b3a86-2750-11e5-8124-3cfa23896079.png)
<sup>Seen at https://wordpress.com/read/blog/feed/25814 using Firefox 39.0 on Mac OS X 10.10.4 logged in as user744 proxied.</sup>

Aside: I also noticed the number of followers are different for these:

* `read/blog/id/4` has 233,317 followers [#](https://cloud.githubusercontent.com/assets/1119271/8633671/a951e37a-27a2-11e5-90c0-0d52496dc219.png)
* `/read/blog/feed/25814`/ has 236,615 followers [#](https://cloud.githubusercontent.com/assets/1119271/8633672/a9535f0c-27a2-11e5-80f4-f3b3b40b2757.png)
* `/read/blog/feed/18785507` has 1 follower [#](https://cloud.githubusercontent.com/assets/1119271/8633673/a9550942-27a2-11e5-83d7-25c28d0c4387.png)

Related: 6904-wpcom, #7605

**Comment by blowery** [comment]
The diff in the feed items is because one is a sub to http://matt.wordpress.com and one is a sub to http://matt.wordpress.com/feed

How that slipped through the normalizer, I'm unsure.

**Comment by lancewillett** [comment]
I think we should close this as it works for *most* sites, and open new issues if bug appears for newly created sites.
