### ISSUE TITLE
Site on an eCommerce plan is not setup in some cases

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#35406]
#### Steps to reproduce
1. Starting at URL: wordpress.com/start
2. Go through the signup flow. Add a custom domain and eCommerce plan to cart.
3. Complete checkout, you will now be shown a GSuite upsell nudge.
4. Complete purchase of GSuite.

#### What I expected

I expected to be taken to the Thank You page for the eCommerce plan.

<img width="666" alt="Screenshot 2019-09-03 at 10 56 59 AM" src="https://user-images.githubusercontent.com/1269602/64146174-9339b080-ce39-11e9-92fd-4cbb6c8407c8.png">

#### What happened instead

I was taken to Thank You page for GSuite.
<img src="https://user-images.githubusercontent.com/6458278/63241015-74fa7f00-c295-11e9-97ef-07494ac13d8d.png">

**Comment by ianstewart** [comment]
Noting that this works as intended now.

- Starting at URL: wordpress.com/start
- Go through the signup flow. Add a custom domain and eCommerce plan to cart.
- Complete checkout, you will now be shown a GSuite upsell nudge.
- Complete purchase of GSuite.

After completing these steps I see the correct Thank you for your purchase screen …

![image](https://user-images.githubusercontent.com/545779/70253183-5a66eb80-1748-11ea-9f50-e11327e52242.png)
