### ISSUE TITLE
Test in Samsung Galaxy Tab S2

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#35416]
Contributor @Aurorum reports that this image is stretched.

![Screenshot_20190812-220957](https://user-images.githubusercontent.com/43215253/62898781-3bce8600-bd4e-11e9-99ac-7b611c963e67.jpg)

**Comment by davemart-in** [comment]
On it. Thanks @eliorivero!

**Comment by eliorivero** [comment]
<img width="568" alt="Screen Shot 2019-08-15 at 16 52 09" src="https://user-images.githubusercontent.com/1041600/63122425-1bd0d980-bf7d-11e9-854e-ce965e390264.png">

Tested using Browserstack and was able to repro. Tested using an S3 setup with Chrome.
