### ISSUE TITLE
FSE: Placeholder for missing image in header makes site appear broken.

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35425]
via @ianstewart

**Comment by noahtallen** [comment]
In https://github.com/Automattic/wp-calypso/pull/35415 we remove "empty" blocks when rendering template blocks in the page editor, so you will not see the placeholder in the page editor with that PR.

**Comment by apeatling** [comment]
Hiding the placeholder in the page view makes total sense.

**Comment by apeatling** [comment]
I think https://github.com/Automattic/wp-calypso/issues/35456 makes this irrelevant, so I'm going to close.

@jeraldjuice hopefully you didn't get too far on this.

**Comment by jeraldjuice** [comment]
@apeatling nope, it was piggybacked on another issue that I don't think we should move forward with, so that works out 👍
