### ISSUE TITLE
FSE: Site title apostrophe character entry doesn't work as expected.

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35420]
Via @ianstewart 

Attempted to use an apostrophe in my site title, saw a single prime character instead, after updating my header and returning to the page I saw the HTML entity for my "apostrophe" instead.

**Comment by noahtallen** [comment]
Currently noticing
- Only shows up for Site Title and Site Description blocks.
- Does not show up for normal paragraph block
- Shows up navigating away from and back to the template editor.
- Does not show up on the front end, just in the page / template editors.
