### ISSUE TITLE
FSE: Can not delete Content Block from Header

### ISSUE THREAD

**Issue by sarahfg** [Automattic/wp-calypso#35436]
#### Steps to reproduce
1. Open the header editor and add a content block to the header
2. Save
3. Head to the Page editor. See the error you've done the wrong thing
4. Reopen the header editor

#### What I expected

I see an error in the page editor that I can only use the content block once. I want to be able to click on the content block to remove it.

#### What happened instead

There is no 3 dots to click to remove the content block from the header editor

#### Browser / OS version

Chrome  Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS 10.14.6 (18G87)

#### Screenshot / Video

Attempts to remove the content block

![](https://cld.wthms.co/SWAdSJ+)
(Image link: https://cld.wthms.co/SWAdSJ )

**Comment by sarahfg** [comment]
If I use `control + a` then press delete I can remove the block, but there is no "clickable" spot to remove it

**Comment by noahtallen** [comment]
Interesting! We've specifically disabled the UI around the content block, which is probably why you don't have a clickable spot to remove it. I think in this case we should not show the content block as a block for insertion in the Template Editor.

**Comment by gwwar** [comment]
Let's add a server-side filter to prevent the content-block from ever being saved in templates. I think pre-save should is a bit preferable. If needed, we can also add a client load filter, if we have bad content out in the wild, so the editor can load properly/save.

> add a content block to the header

@sarahfg do you recall what steps you took to do this? We'll want to prevent any client UI from allowing this too.

**Comment by sarahfg** [comment]
1. Open the full site editor Header Editor
2. Click the `+` button
3. Select the `Content` block

![](https://cld.wthms.co/vqaePz+)

(Image link: https://cld.wthms.co/vqaePz )

**Comment by gwwar** [comment]
Ah thanks @sarahfg ! We should definitely remove that from the inserter :D

**Comment by Copons** [comment]
I think it should be enough to remove the Content block from the inserter. 🤔

**Comment by gwwar** [comment]
> I think it should be enough to remove the Content block from the inserter. 

Never doubt a user's ability to insert weird content ;) but I'd be okay leaving that for a follow up issue.
