### ISSUE TITLE
FSE: Full Width Blocks Broken in Footer

### ISSUE THREAD

**Issue by sarahfg** [Automattic/wp-calypso#35432]
#### Steps to reproduce
1. Create a site as instructed
2. Add a full width block, like a cover or image to the footer editor
3. Publish

#### What I expected

I expected the footer content to be full-width as it is in the preview on the footer editor.

#### What happened instead

When viewing the site cover blocks appear wide width. Image blocks flow over to the right.

#### Browser / OS version

Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS 10.14.6 

### Screenshot / Video
Full-width cover block in footer

![](https://cld.wthms.co/9pXqEJ+)
(Image link: https://cld.wthms.co/9pXqEJ )

Full-width Image block in footer

![](https://cld.wthms.co/FpMaiW+)
(Image link: https://cld.wthms.co/FpMaiW )

**Comment by apeatling** [comment]
We fixed this for headers, we should fix it for footers too.

**Comment by noahtallen** [comment]
<img width="1373" alt="Screen Shot 2019-09-27 at 5 47 01 PM" src="https://user-images.githubusercontent.com/6265975/65809122-d17f7280-e14e-11e9-98fd-98f7e076b1eb.png">

This has been resolved with the latest styles :)
