### ISSUE TITLE
FSE: Edit Header button is too small

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35438]
From Aadil:

The 'Edit Header' button is quite small, and was not easy to see, given there is no contrast with the background

**Comment by gwwar** [comment]
Removing from the sprint until this is ready for implementation work.

**Comment by shaunandrews** [comment]
We could try making the button bigger by increasing the font-size and padding. Along with this, I think the current grey overlay color is too similar to the secondary button color — which leads to the button _blending in_ with the overlay. If we use white for the overlay color, the button stands out a little more:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/191598/63386199-7a78c780-c370-11e9-8196-fc5109cf2fb2.png">

We could add a box-shadow to the button as well to really help emphasize it:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/191598/63386298-ba3faf00-c370-11e9-91ce-4d75c437a20d.png">

**Comment by apeatling** [comment]
The colors are changed now, and with your animation updates I think the button is much more noticeable. Let's close this one and revisit if we get more reports.
