### ISSUE TITLE
Reader: use thumbs up Gridicon for Recommendations

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#3543]
Current: 

![screen shot 2016-02-24 at 3 32 51 pm](https://cloud.githubusercontent.com/assets/618551/13301728/f924dc00-db0b-11e5-8e79-3a50929b8161.png)

`<Gridicon icon="thumbs-up" />`

May I add this to the UI Nits milestone? Feel free to remove if you want.

cc @blowery

**Comment by blowery** [comment]
@drw158 That's just fine. We're about to close the milestone and start work on a new one, but we can slip this in.

**Comment by drw158** [comment]
Thanks!
