### ISSUE TITLE
FSE: Needing to click on the header to edit is not clear

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35437]
From Aadil:

When I scrolled over to the header section it was not clear to me that it was clickable or editable - would it be possible to show the ‘Edit Header’ text dynamically when you mouse over and have the background be more transparent.

**Comment by apeatling** [comment]
I think we should see if more feedback for this comes in. The hover is more obvious, but we had a back and forth on this before.

**Comment by noahtallen** [comment]
we'll come full circle 😁

**Comment by gwwar** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/35419

**Comment by shaunandrews** [comment]
If we treat the Header just like any other block on the page, then is should get a hover indicator with both a line on the left, and a label for the block name:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/191598/63381001-bfe3c780-c365-11e9-8167-6793b200369c.png">

**Comment by shaunandrews** [comment]
Here's what that could look like in motion:

![template states](https://user-images.githubusercontent.com/191598/63386079-3e456700-c370-11e9-881a-010709720963.gif)

**Comment by shaunandrews** [comment]
If the Gutenberg-standard border+label is too subtle (which I think it might be) we could slightly fade (but not blur) the content of the header block on hover:

![fade and borders](https://user-images.githubusercontent.com/191598/63386581-6d100d00-c371-11e9-9100-a732852b8ce3.gif)

This helps convey the grouping of the elements within the header.

**Comment by apeatling** [comment]
This animation and transition to the button showing makes sense. Before when we had only the side border hover without transition it didn't make a lot of sense.
