### ISSUE TITLE
Editor: When a site is private, make it clearer that hitting "publish" will not make the post/page public

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35444]
From Aadil:

Selecting a page template from the template selector was fine but the wording ‘Publish’ confused me quite a lot because my site was still private when saving a new page.

**Comment by apeatling** [comment]
The most obvious option is to update the Publish button action title. Another option would be to add a message in the pre-publish menu:

<img width="305" alt="Screen Shot 2019-08-15 at 4 45 23 PM" src="https://user-images.githubusercontent.com/1464705/63133918-1626c400-bf7c-11e9-9998-d98bad86a188.png">

**Comment by shaunandrews** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/191598/63460676-f92f3c80-c424-11e9-9aa2-3d5cda67b5ed.png">

For private sites, I suggest we remove the ability to change the visibility of individual posts or pages. Instead we show a message that the entire site is private.

Pages/posts would be _internally_ marked as "public" so when a site is launched all pages would be available, and customers could update the visibility of a page to make it private or password protected.
