### ISSUE TITLE
Preview: Remove the site preview in Calypso

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35445]
From Aadil:

In this screen it’s super confusing that I can’t find a way to edit my page but I can click around the different pages ( I finally found the small ‘Edit’ button at the bottom of the page, but it looked like it was actually part of the page)

<img width="741" alt="Screen Shot 2019-08-15 at 4 53 13 PM" src="https://user-images.githubusercontent.com/1464705/63134181-330fc700-bf7d-11e9-9dc2-e4eff179e8f0.png">

**Comment by apeatling** [comment]
I don't know why we keep this preview screen because it's very confusing and looks like another edit screen. Let's remove it from Calypso and link directly to the website itself.

**Comment by michaeldcain** [comment]
@apeatling: it shouldn't affect Signup, but we'll need to search Calypso to see where we're currently linking to the preview (e.g. the "view site" link after importing). I don't have an objection to removing the view from the sidebar, but to be clear, we'd be leaving the component for post editing previews?

**Comment by lancewillett** [comment]
Reminder of the "why" of this feature.

Previously, viewing your site opened a new tab or window. The intended design here is to keep people in Calypso, not span lots of open tabs in their browsing session. A quick look to see what the site looks like.

**Comment by apeatling** [comment]
An edit site button was added to this screen, closing this.
