### ISSUE TITLE
FSE: Button Alignment Display Errors 

### ISSUE THREAD

**Issue by sarahfg** [Automattic/wp-calypso#35441]
#### Steps to reproduce
1. Add a button to your header
2. Change the alignment of the button

#### What I expected
The view of the button in the header editor, page editor, and page itself should be the same and reflect the alignment I chose in the block editor

#### What happened instead

All 3 views look different. Only the page itself reflects the chosen alignment for the buttons

#### Browser / OS version
Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS 10.14.6 (18G87)

#### Screenshot / Video

Centered buttons in header editor
![](https://cld.wthms.co/DUSlkw+)
(Image link: https://cld.wthms.co/DUSlkw )

Centered buttons in page editor
![](https://cld.wthms.co/fzd4Wl+)
(Image link: https://cld.wthms.co/fzd4Wl )

Centered buttons on live site
![](https://cld.wthms.co/LL0yuP+)
(Image link: https://cld.wthms.co/LL0yuP )

**Comment by noahtallen** [comment]
This is no longer reproducable!

**Page editor**
<img width="1010" alt="Screen Shot 2019-09-27 at 5 39 19 PM" src="https://user-images.githubusercontent.com/6265975/65809015-de4f9680-e14d-11e9-8c70-e6da6b1414be.png">

**Header editor**
<img width="1039" alt="Screen Shot 2019-09-27 at 5 39 50 PM" src="https://user-images.githubusercontent.com/6265975/65809014-dc85d300-e14d-11e9-9c99-e0d3cafe7cb1.png">


**Front end**
<img width="1313" alt="Screen Shot 2019-09-27 at 5 39 36 PM" src="https://user-images.githubusercontent.com/6265975/65809013-d98ae280-e14d-11e9-9a37-23f5a3d88966.png">

There are still some weird interactions around the buttons, but those are just oddities with the block editor, and not related to FSE.
