### ISSUE TITLE
FSE: Editing the Page title does not update the page title in the Navigation

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35440]
From Aadil:

When I change the name of the ’Title’ of my page, I am not sure why the title of my page in the Nav menu does not update, even after I click ‘Update’ I only see the change reflected once come back into the page.

Rewording from @gwwar:
 
When updating the title, the navigation block should update after the publish/update action, without requiring a full page refresh.

**Comment by vindl** [comment]
Punted since this will be handled in Core navigation block (https://github.com/Automattic/Dotcom-roadmap/issues/51).
