### ISSUE TITLE
FSE: Prevent accidentally deleting nav block

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35443]
From Aadil:

Clicking on the Nav menu - ‘Home, About, Contact’ bar was really confusing. I tried to edit the names of the menu items but I was not able to. I then clicked on it and tried to delete a single letter but just ended up deleting the whole section and could not get it back like so.

**Comment by apeatling** [comment]
I'm not sure what we can do about this one. I'm open to ideas of how we can prevent this kind of deletion of the block, or make it clearer that titles are not editable. Perhaps in combination with https://github.com/Automattic/wp-calypso/issues/35439 this will be clearer?

/cc @shaunandrews

**Comment by gwwar** [comment]
I think this one can be avoided if the navigation block has interactions vs is simply a placeholder. Likely a no-op if we iterate on the navigation block further, for allowing key interactions like in https://github.com/Automattic/wp-calypso/issues/35439

Removing from the sprint until we have clear implementation steps.

**Comment by shaunandrews** [comment]
> can be avoided if the navigation block has interactions vs is simply a placeholder

Agreed. I think the simplest thing would could do is show a message and button when the Site Navigation block is focused. Over in #35669 I proposed doing just that:

![Site Navigation Focused Copy](https://user-images.githubusercontent.com/191598/63459785-2f6bbc80-c423-11e9-9679-7a80375e9f77.png)

I think the would help set expectations better that customers can't type or edit the block in anyways — and hopefully resolve the problem of people accidentally deleting the block when they think they're typing.

**Comment by vindl** [comment]
This will be solved by the core navigation block (https://github.com/Automattic/Dotcom-roadmap/issues/51).
