### ISSUE TITLE
FSE: Add a default logo placeholder image

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#35456]
There is no code to review for this issue as the header template has been updated in the fsemodernbusiness site.

#### Steps to test
1. Set up a new FSE site either locally or via the Horizon FSE CfT steps
2. Check that default modern business logo is displaying in the header instead of the image placeholder

**before**

<img width="730" alt="default-logo-before" src="https://user-images.githubusercontent.com/3629020/63815238-f766fb00-c987-11e9-875d-221f0eee1728.png">

**after**

<img width="643" alt="default-header-logo" src="https://user-images.githubusercontent.com/3629020/63815163-a2c38000-c987-11e9-987c-abc6fad0207e.png">

**Comment by gwwar** [comment]
@apeatling the site logo placeholder is pretty prominent. Should we maybe populate the design with a logo to start with to avoid these screens? cc @iamtakashi @shaunandrews

**Comment by apeatling** [comment]
Yes we should, this has come up. I think we should actually update this issue to reflect that. 

@iamtakashi Should we use the placeholder logo from the modern business proofs?

**Comment by apeatling** [comment]
I probably should have opened a new issue instead, but this will work for now.

**Comment by iamtakashi** [comment]
I agree with starting with an actual logo image rather than a placeholder. But, would FSE themes header always start with having a logo? Or does it depend on demo site?

**Comment by apeatling** [comment]
It will depend on the header template being used, so it could be different depending on what the theme needs.

**Comment by iamtakashi** [comment]
Ok, and we'll define the header template in the demo site, correct?

**Comment by apeatling** [comment]
I think we can do that, but it's not really in scope for this discussion, we just need to decide what the best default logo is in the context of Modern Business.

**Comment by iamtakashi** [comment]
Sure, we can use the logo in the demo site instead of the placeholder.

**Comment by glendaviesnz** [comment]
@apeatling  Can you please point me to the proofs so I can get a copy of the logo mentioned?

**Comment by glendaviesnz** [comment]
As far as I can tell there are no code changes required for this. We just need to update the header template content and change the image block from 
```
<!-- wp:image {"className":"fse-site-logo"} -->
<figure class="wp-block-image fse-site-logo"><img alt=""/></figure>
<!-- /wp:image -->
```
to 

```
<!-- wp:image {"className":"fse-site-logo"} -->
<figure class="wp-block-image size-large fse-site-logo"><img src="https://modernbusinessdemo.files.wordpress.com/2019/06/logo-modern-3.png" alt=""/></figure>
<!-- /wp:image -->
```

Just need to hunt down that code for snapshooting the template data ...

**Comment by glendaviesnz** [comment]
@qwwar I can't access the templates any more at https://fsemodernbusinessdemo.wordpress.com/wp-admin/edit.php?post_type=wp_template - gives a console error - did we move these to the main modernbusiness demo site already?

**Comment by glendaviesnz** [comment]
So for some reason the patch D31361-code had broken access to the fse demo site for me, I think maybe because I had classic editor set for my user from past edits of the templates. I can get in and edit them my temporarily reverting that on my sandbox - @gwwar  - do you want me to go ahead and add that logo to the header template on fsemodernbusiness?

I have added and issue for the problem of forcing gutenberg for users that have chosen classic - https://github.com/Automattic/wp-calypso/issues/35804

**Comment by glendaviesnz** [comment]
This is now done and the default modern business logo now displays instead of the placeholder if you go through the FSE setup flow

<img width="643" alt="default-header-logo" src="https://user-images.githubusercontent.com/3629020/63815031-25980b00-c987-11e9-82f2-b5ce71381ce6.png">

**Comment by iamtakashi** [comment]
> @iamtakashi The logo in the demo site looks fuzzy on a retina display, do we have a 2x version of it? Is this going to be different in Maywood?

Sorry for the delay in response. We could use a different logo for Maywood. It's not a big deal if that's not convenient though. Here is a big version of a new logo. Let me know if there is any issue.

![maywood-logo](https://user-images.githubusercontent.com/908665/63892933-c8c93e80-c9e0-11e9-89e5-19a3a4915f72.png)

**Comment by glendaviesnz** [comment]
> It also looks like we're hotlinking. Not sure if we need to tidy before the 10% test, but we should for 100%. @obenland any ideas for what we'd need to do for side-loading? 

There is code at /full-site-editing/full-site-editing-plugin/starter-page-templates/class-wp-rest-sideload-image-controller.php for side-loading images, but would be a bit of work to get this working in tandem with the fse template creation api - I would suggest we defer for the 100%

> At worst, this looks small enough where even a base64 encoded image would be preferable.

Have tried base64 encoded data: version of the new logo but on saving the base64 data is stripped - I am guessing the the KSES filters remove this.

So, any thoughts on whether we just make do with a hotlinked image for the 10% trial, or is there another way to get base64 encoded version accepted?

**Comment by apeatling** [comment]
Hot linking seems fine for the test, since we are still hot linking other images in templates right now (until we figure out side loading).

**Comment by apeatling** [comment]
@glendaviesnz Let's update this to use the high res logo Takashi provided.

**Comment by obenland** [comment]
> Hot linking seems fine for the test, since we are still hot linking other images in templates right now 

I'd strongly advise against hotlinking more images. We'll _never_ be able to change or remove those images once we start doing that, even for a small amount of sites. It's part of the reason why I've held back updating those template images with optimized versions so far.

**Comment by obenland** [comment]
#35588 added the utility functions to communicate with the endpoint, #34839 has the code that integrates the side-loading endpoint in the templates selector. We've had a a fair bit of performance troubles with it, especially for multiple images though.

**Comment by apeatling** [comment]
Thanks @obenland, that's a good point. I'm concerned about the performance issues of side loading as a blocker for the test.

**Comment by obenland** [comment]
If it's just this one image with a size of 35kb it should be fine. We've not had many problems with [the blog template](https://a8ctm1.wordpress.com/blog/) so far, [Professional](https://a8ctm1.wordpress.com/professional/) with its 12+ images is where it becomes pretty bad. I do realize though that implementing that sideloading approach might delay the test.

**Comment by gwwar** [comment]
I'll create a new issue for the hotlinking fix, since that sounds like a decent amount of work.

**Comment by glendaviesnz** [comment]
@gwwar have added the explicit centre alignment now.

**Comment by gwwar** [comment]
Thank @glendaviesnz verified that this populates with the attribute on a new site:
<img width="600" alt="Screen Shot 2019-08-30 at 9 50 41 AM" src="https://user-images.githubusercontent.com/1270189/64038249-74bb7880-cb0c-11e9-8ef2-510dda746bc5.png">

Closing this out and will add a second one for the hotlinking

**Comment by apeatling** [comment]
@gwwar @glendaviesnz Based on the above, it doesn't look like the new logo Takashi linked? The hotlink URL needs to be updated to:

https://maywooddemo.files.wordpress.com/2019/08/maywood-logo.png
