### ISSUE TITLE
FSE: Finishing editing your homepage does not take you back to checklist [2]

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35452]
If I come to the editor via the checklist, when you hit the close button it should take me straight back to the checklist, not the pages screen.

![2019-08-15 20 27 06](https://user-images.githubusercontent.com/1464705/63141643-56e20580-bf9b-11e9-88a9-40fb1d2b3903.gif)

**Comment by gwwar** [comment]
@apeatling we currently keep a simple link back to the page/post list, since it can be a mess for replicating browser back history. Can we make an exception for the checklist and keep behavior simple?

**Comment by apeatling** [comment]
Yes, let's make an exception for the checklist since it's an important flow (the way most users will get to the editor for the first time).

**Comment by noahtallen** [comment]
Somehow, we managed to screw some part of the back button up again so that this fix doesn't work any longer.

**Comment by apeatling** [comment]
@noahtallen Can you co-ordinate with @jblz on this one and https://github.com/Automattic/wp-calypso/pull/36833

**Comment by noahtallen** [comment]
@apeatling thanks for pointing that out!
