### ISSUE TITLE
FSE: We need a link to Custom CSS in the customizer [3]

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35451]
From Josh Ruud:

We help users with custom CSS on a daily basis. While FSE will bring a lot of flexibility to customizations, it would be great for folks to be able to self-serve CSS and have an easy access link for us to help them with it.

> I want to make my site title bigger

**Comment by gwwar** [comment]
Should we spike to see if https://github.com/Automattic/wp-calypso/issues/35173 doesn't cost as much as we think?

Any flows that send folks to the customizer I think will be pretty confusing.

**Comment by gwwar** [comment]
To summarize a chat with Andy, we'll still implement the link for now.

**Comment by apeatling** [comment]
I think we can add an "Edit CSS" link underneath "Themes" in the sidebar menu, that links directly to custom css in the customizer.

**Comment by apeatling** [comment]
This is fixed with: https://github.com/Automattic/wp-calypso/issues/35851
