### ISSUE TITLE
Full Site Editing: improve performance of switching between template views

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#35457]
Currently when you navigate to header/footer and back the transitions appear to be too slow. There is a noticeable delay until the new view with separate iframe loads.

One thing we could try instead is to preload and render both header and footer iframe, along with the full page iframe, but just hide them from users initially. This can be likely be done here: https://github.com/Automattic/wp-calypso/blob/fba9a0b9a5c4b9c1ccba8435944e2aa04bf9ac0e/client/gutenberg/editor/calypsoify-iframe.tsx#L545

For example we could track `activeView` in component state above (one of `page`, `header`, `footer`) and make just one iframe visible depending on it. For this to work, the `Edit` and `Close` button functionality will have to be modified a bit - on `postMessage` from child iframe, instead of navigating to given post ID, it should just update the above state value.

One thing that I also think we'll need to handle in that case is refreshing the template part previews, after making an update in some of the template views, so they are reflected in the full page view.

We could try to to this before production launch, or leave it for 1.x releases.

cc @gwwar and @apeatling for thoughts

**Comment by apeatling** [comment]
I like the thinking, but I don't think this should be considered until after the v1 release. We have a lot of blocking and high issues to get through.

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.
