### ISSUE TITLE
(8P) SPT: Fix tabbing behaviour between Template preview thumbnails

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#35462]
Noticing some very strange tabbing behaviour when attempting to tab between the Template previews whereby the tab focus gets shifted to the `<body>` element for no apparent reason.

See [this video](https://cld.wthms.co/p143Dd) for an example.

**Comment by getdave** [comment]
Confirmed this is due to us descending into the DOM of the preview. A bug in `Disabled` component is allowing this to happen:

https://github.com/WordPress/gutenberg/pull/17064#discussion_r315158019

**Comment by getdave** [comment]
Blocked waiting on fix to `Disabled` component.

**Comment by obenland** [comment]
What are the next steps? Anything I can do to help?

**Comment by getdave** [comment]
Thanks @obenland . 

> What are the next steps?

Trying out [the feedback here](https://github.com/WordPress/gutenberg/pull/17064#discussion_r318236971). I remember feeling a little overwhelmed by this problem a while back. 

If this is still "in scope" for Iteration 9 then I'm happy to pick it up again though.

> Anything I can do to help?

Help me get support from Core team members where necessary.

**Comment by frontdevde** [comment]
Issue triage 27-02-2020:
Closing issue as history above indicates it was marked done on 26 Sep 2019.
