### ISSUE TITLE
Full Site Editing: migrate MVP sites to FSE

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#35465]
After releasing FSE to production, let's make sure to circle back and migrate existing MVP sites to FSE.

@mattwiebe has already draft a migration scrip so we should build up on that solution.

**Comment by davipontesblog** [comment]
@vindl do you think it's still relevant to keep this one open in light of core FSE down the road?

**Comment by vindl** [comment]
@davipontesblog probably not. It's not clear whether we'll be able to invest time in MVP migration at all.
