### ISSUE TITLE
Full Site Editing: figure out Atomic strategy before releasing to production [5]

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#35463]
FSE is currently turned off on all Atomic sites via filter in `wpcomsh`. We need to remove this override and also figure out how to enable it just for a given subset of users - initially it will be new 10% EN.

I think it's okay to not include Atomic sites in the 10% test, but we need to respect any Simple Sites that are in the test and have transferred. The FSE flows should still work.

The easiest way I can think of is to record activation in site option that will get copied during transfer, which we can then in turn inspect in `wpcomsh` and conditionally trigger `a8c_disable_full_site_editing` filter.

**Comment by gwwar** [comment]
@apeatling we need this one before turning on the A/B test. As folks will be able to upgrade/transfer

**Comment by noahtallen** [comment]
To summarize, this was handled by creating an option on the remote site if the original site has the FSE sticker.

Wpcomsh checks the option and uses the filter to disable FSE: https://github.com/Automattic/wpcomsh/pull/320

Atomic transfer includes the option if the site has the sticker: D32425-code

Next up, API tweaks to make sure eligibility support works correctly: https://github.com/Automattic/wp-calypso/issues/35854

I'll wait to merge until everything is deployed and I can test in prod.

**Comment by noahtallen** [comment]
The API tweaks are complete :)

The next issue is that based on feedback about using an option to support Atomic eligibility, we should move to a different approach. I've been told that a wpcom API endpoint should suffice, so I'm thinking of how to integrate that locally.

This should work well because the site option exists on the wpcom shadow site when an Atomic site is transferred.

**Comment by vindl** [comment]
@noahtallen do you think it would make sense to move that to a non-blocking follow-up task?

**Comment by noahtallen** [comment]
Yes, will do! I'll close this one now because Atomic is working correctly.
