### ISSUE TITLE
Customer Home: Link 'My Sites' to the Customer Home

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#35468]
Currently, this defaults to the stats screen for a site, but it makes sense to use the new Customer Home where it's available.

This also involves a change to the master-bar.

**Comment by pablinos** [comment]
I've been doing some research into this and the change to the master-bar makes for an interesting problem. The master-bar is generated in PHP, so we need to sync the A/B test groups between the front and backend. We could do this by using a calculation on the user ID, but it would be better to use the standard libraries we have available.

The PHP library sets the test group as a user attribute, so hopefully, we can use that and pass the attribute to the frontend.

Also, the eligibility criteria for the checklist (which we are mimicking for customer home) is based on the site creation date. It could be that a user who is part of the test has access to Jetpack sites, or older sites, and therefore won't see the customer home option for them. This may not be too much of an issue, but having the 'My Sites' link point to different locations depending on the site, could be confusing.

The master-bar is also part of Jetpack, so we will need to consider that when we eventually roll this out to Jetpack sites.

@davemart-in and @jancavan - I'd be interested to hear your thoughts on the UX of this.

**Comment by davemart-in** [comment]
> This may not be too much of an issue, but having the 'My Sites' link point to different locations depending on the site, could be confusing.

Thanks for bringing this up. I'm not worried about this in the short-term. In the long-term, my goal is to show the Customer Home to **all users** whenever "My Sites" is clicked.

Let's look at our list of conditions:

A) **New user** - we won't be showing it to existing users
B) **Is admin** - for the v1 we're restricting this screen to just administrators
C) **Not JP user** - this is out of scope for the v1 launch
D) **In variation B** - We'll be A/B testing this feature, so only 50% of new users will see it
E) **All plans** - including free
F) **Checklist completed**

The important conditions appear to be A-D to make this work. "A" can be replicated on the front and back-end by using the same User ID as a constant. I'm assuming "B" and "C" are both easy to figure out in PHP and React. "D" as you pointed out would need to be set on the PHP side and assigned to either a cookie, localstorage, or the DB for the front-end to consume.

I'd say keep pressing forward!

**Comment by pablinos** [comment]
Fixed by #35688 and r195620-wpcom
