### ISSUE TITLE
FSE: The header Image block Settings disappear when resizing

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35474]
* Upload an image in the header image placeholder.
* Resize the image
* The block is deselected and you lose the sidebar settings, and block frame/menu.

This does not happen for an image inserted with FSE disabled.

Screen Recording 2019-08-15 at 6.53.07 PM

https://videopress.com/v/q1ftbvKD

**Comment by noahtallen** [comment]
This bug is no longer reproducible! :D
