### ISSUE TITLE
Editor: Gutenberg image size dropdown is not functioning

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35475]
Changing the size of the image via the “Image Size” dropdown does nothing.

https://videopress.com/v/UAxbNZ9k

Can we confirm if this is a Gutenberg regression or something specific to WordPress.com?

**Comment by mmtr** [comment]
This issue was already reported in #34969, so I'm closing this as duplicate (I bumped the priority of #34969 to high).

 > Can we confirm if this is a Gutenberg regression or something specific to WordPress.com?

This is specific to WordPress.com, the issue is not reproducible in a self-hosted site.
