### ISSUE TITLE
FSE: Investigate "Changes may not be saved" message

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35477]
via Gui Azeredo:

I found something that I’m not sure if it’s expected but it’s odd. These are the steps to reproduce it: 

* create a new page
* select a template
* click to edit the header. 

At this point, I got a pop-up notification saying “Changes you made may not be saved”. 

I believe the content created by the template hasn’t been saved yet. This could make the user insecure but I’m not sure if there is a way to avoid this. 

Then, I clicked Cancel and the header kept loading forever. 

Here is a screenshot: https://cld.wthms.co/8YFmgL

**Comment by noahtallen** [comment]
This is definitely strange, maybe it's a regression. We 100% had this working the other day, where it autosaves your post at this point instead of showing the message. 🤔

**Comment by noahtallen** [comment]
We recently fixed bugs around this, so I'll close unless it comes up again :)
