### ISSUE TITLE
FSE: Update customize link in the welcome notification

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35473]
Let's make it link to the editor and editing the home page.

<img width="772" alt="screen-shot-2019-08-15-at-3 29 27-pm" src="https://user-images.githubusercontent.com/1464705/63179592-55e3bf00-c001-11e9-93be-79ce3861dc3a.png">

via @kwight

**Comment by arunsathiya** [comment]
Similar one on the new account welcome email - https://github.com/Automattic/wp-calypso/issues/35513

**Comment by mattwiebe** [comment]
D34114-code will fix this

**Comment by mattwiebe** [comment]
This is done
