### ISSUE TITLE
FSE: Disable and Hide Status and Visibility settings for Template parts

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35485]
Seems the template parts work regardless of the visibility set on the editor sidebar. 

But if it’s scheduled to be published in a different day, any change done to the template part is not reflected on the published view.

**Comment by gwwar** [comment]
@apeatling I can't think of any use cases where we'd want to allow this functionality to set status, schedule, or hide these CPTs. I've updated the title here to reflect that.
