### ISSUE TITLE
FSE: Possibly add option to show/hide header/footer

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35480]
via Gui Azeredo:

It would be good if there was an option to hide/show header and footer when editing a page. I was wondering that maybe the header and footer wouldn’t be edited very ofter, so an option to hide it could make it easier to get to edit the page content more quickly (not having to scroll down)

**Comment by apeatling** [comment]
Let's see what feedback we get after launch before considering this one.

**Comment by apeatling** [comment]
Adding these to the Not Doing column for now and will move if we hear feedback that this is an issue.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
