### ISSUE TITLE
FSE: Reusable blocks appear as temporary unavailable

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35486]
When loading a page, if the header or footer contains a reusable block, it’s displayed momentarily as unavailable, but then it’s rendered correctly.

https://videopress.com/v/iuaEI3kr

**Comment by gwwar** [comment]
Let's investigate why this message notice is displaying (might be a core issue, or how we're including these). If we can't pre-populate to avoid a loading screen, work with @shaunandrews on options (spinner, text etc).

**Comment by Copons** [comment]
At first I thought it could have been an issue with [fetching reusable blocks](https://github.com/WordPress/gutenberg/blob/df7afa8b550515fbf7f85e7816bebabf7b2438c8/packages/block-library/src/block/edit.js#L107-L109) from templates, but in fact I can't seem to reproduce this issue, both locally and on WPCOM:

![Aug-19-2019 18-33-40](https://user-images.githubusercontent.com/2070010/63286547-332b0200-c2b0-11e9-80b7-888a5cd0b604.gif)

**Comment by noahtallen** [comment]
I am also unable to reproduce this on wpcom:

![2019-08-21 13 36 59](https://user-images.githubusercontent.com/6265975/63466854-00e8e400-c419-11e9-9891-7bca99628258.gif)


Interestingly, I do see this previewing the reusable block, but this error shows up on the post page without FSE enabled, so it's unrelated to what we're doing:
<img width="721" alt="Screen Shot 2019-08-21 at 1 35 58 PM" src="https://user-images.githubusercontent.com/6265975/63466772-d7c85380-c418-11e9-922a-8ee38e8d0550.png">

**Comment by noahtallen** [comment]
I also slowed down the internet in the network tab to "Fast 3G", but even tough the editor takes 1.2 whole **minutes** to load, it never shows the deleted/unavailable message.

Is there maybe a more specific way to reproduce it than just by creating a simple reusable paragraph block?

**Comment by apeatling** [comment]
If it's this hard to reproduce I think we should just close this issue and wait for any more reports.
