### ISSUE TITLE
FSE: Hide widgets and menus in wp-admin

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35481]
From Gui Azeredo:

If customizer will keep hidden though, I noticed that it’s also hidden from WP Admin, but Widgets and Menus aren’t. Wouldn’t it make sense to hide these sections too?

**Comment by kriskarkoski** [comment]
If we hide the Customizer and Menus links how can users customize the menu on v1 as Kerry mentioned here: https://dotcom.wordpress.com/2019/08/15/call-for-testing-full-site-editing/#comment-42730

Would they just need to know to visit wordpress.com/customize or WP admin menus manually?

**Comment by vindl** [comment]
Let's hide the Widgets but keep Menus to allow Navigation block customization.
