### ISSUE TITLE
FSE: Home page title is missing to edit [2]

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35492]
From @m:
If you're editing a page in Gutenberg, and you can edit the title of that page, it looks like you're editing the header. 

But then when you look at your home page, that edit isn't there and the header is the Site Title heading

**Comment by apeatling** [comment]
According to @michaeldcain this might be related to the `hide_homepage_title` theme mod that Signup themes use. Could y’all query that theme_mod to sometimes hide the page title?

**Comment by apeatling** [comment]
Need to investigate this.

**Comment by gwwar** [comment]
Some themes display the title and some don't. We probably need some though on the title treatment, and how that's grouped with templates vs the page editor.

**Comment by shaunandrews** [comment]
I'm not sure what design related help I can give here — it seems like we should hide the page title for the Home page within our template-first themes.

At some point, the title will act just like any other block — and we'll need to have a place outside of the page/post content to update the title.

**Comment by apeatling** [comment]
All of our template first hide the homepage title by default. With @iamtakashi updating modern business to be based on varia it should hide there too. I think this is enough to deal with this issue.

**Comment by apeatling** [comment]
Let's close this out once modern business is updated. 

Fixed by: https://github.com/Automattic/template-first-themes-private/issues/126

**Comment by vindl** [comment]
Closing this out since https://github.com/Automattic/template-first-themes-private/issues/126 has been resolved and we switched to Maywood in the meantime.
