### ISSUE TITLE
FSE: try zipping generated artifact in circle workflow

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35495]
We currently use the `build-full-site-editing` Circle CI workflow to generate our Full Site Editing plugin artifacts. See [example build](https://circleci.com/gh/Automattic/wp-calypso/402212?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). Let's see if we can zip the final artifact on the circle side to reduce the number of requests to pull files. If we update this workflow, we'll need to update internal scripts.

Another alternative might be committing the generated dist files from Circle to git.

**Comment by davipontesblog** [comment]
@gwwar do you think this one is still relevant to the work in the FSE plugin?

**Comment by gwwar** [comment]
@Automattic/cylon and folks on Create should be able to help you triage these. @noahtallen would be good to ping on any last internal tooling updates

**Comment by vindl** [comment]
> Let's see if we can zip the final artifact on the circle side to reduce the number of requests to pull files. If we update this workflow, we'll need to update internal scripts.

This was already completed as part of the FSE tooling project and it's fine to close it out. (paYE8P-i0-p2)
