### ISSUE TITLE
People: Invites: Invite button is missing bottom margin

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35504]
On the [People tab](https://wordpress.com/people/team), under the `Invites` section, the `Invite` button is missing the bottom margin on certain mobile widths.

![Screenshot_20190815-133724](https://user-images.githubusercontent.com/18581859/63208304-0def9580-c0f0-11e9-986f-acb2bf61f784.jpg)

**What's expected:** Has margin at the bottom, similar to the top margin.

**Comment by Aurorum** [comment]
Hmm, I can't seem to reproduce this.

<img width="452" alt="Screenshot 2019-08-17 at 09 15 06" src="https://user-images.githubusercontent.com/43215253/63208712-927dec00-c0cf-11e9-8a83-91726aa4171f.png">

**Comment by Aurorum** [comment]
Never mind! Figured it out, you need to be on a site that has no pending invites. PR in #38753. :)

<img width="967" alt="Screenshot 2020-01-09 at 17 06 59" src="https://user-images.githubusercontent.com/43215253/72088856-ed281680-3302-11ea-8b38-5a32a663ab6f.png">
