### ISSUE TITLE
My plan: Description isn't positioned to the right of the icon on mobile landscape mode

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35507]
On the `My plan` page of any WordPress.com site or Jetpack site, it can be seen that the description is not positioned entirely to the right of the icon. 

It looks fine on the mobile vertical mode, but on mobile landscape mode, the description spans the icon bottom as well (which should not happen)

![Screenshot_20190815-133549](https://user-images.githubusercontent.com/18581859/63208454-deda2380-c0f1-11e9-922e-854ba7a71ce7.jpg)
![Screenshot_20190815-133554](https://user-images.githubusercontent.com/18581859/63208455-df72ba00-c0f1-11e9-8db8-e73f2bf6a296.jpg)

One solution that I can think of is - hide the icon on mobile landscape view (that is after a certain width) as well, or make the description stay positioned entirely to the right of the icon.

**Comment by Aurorum** [comment]
PR in #35511 for this issue. :)
