### ISSUE TITLE
Checkout: Order confirmation text hard to read on Jetpack checkout

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35503]
When checking out a Jetpack plan, the order confirmation text `Review your order and proceed with a payment method to finish` is hard to read. 

![IMG_0056](https://user-images.githubusercontent.com/18581859/63208218-fcf25480-c0ee-11e9-90d1-05497e16a68a.png)

On WordPress.com checkouts, it's fine.

<img width="1102" alt="Screenshot 2019-08-17 at 12 58 30" src="https://user-images.githubusercontent.com/18581859/63208215-f5cb4680-c0ee-11e9-9195-252b4b6f3191.png">

**Comment by Aurorum** [comment]
PR in #35508 for this issue. :)
