### ISSUE TITLE
People: Invite field: Unable to paste a username or email address into the field

### ISSUE THREAD

**Issue by gracie** [Automattic/wp-calypso#35514]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/people/new
2. Have an email address in your clipboard
3. Right click on the field beneath Username or Emails
4. Try to select Paste

#### What I expected

For paste to be an option

#### What happened instead\

In Chrome: Right clicking highlights the content beneath the field, making it only copy-able. 
![Screen Shot 2019-08-17 at 09 14 11](https://user-images.githubusercontent.com/21203710/63212250-695d5b80-c0cf-11e9-8759-fc435c608a0f.png)

In Safari: No option to paste appears.

#### Browser / OS version

Firefox: 68.0.1
Safari 12.1.1
Chrome Version 75.0.3770.142

#### Screenshot / Video

![Screen Shot 2019-08-17 at 09 17 15](https://user-images.githubusercontent.com/21203710/63212273-d7a21e00-c0cf-11e9-8d59-6b0f1ff3e767.png)

#### Additional info

As a note, clicking out of the field and back into it a bunch of times eventually allows you to right click > See the paste.

Command + V also works well.

Less tech-savvy users tend to rely on right-click > Paste, though.

Reported from a WordPress.com chat. #14614189-hc

**Comment by arunsathiya** [comment]
Here's what's going on. The entire field is a validator, and at the start of this field is an input field. That is, when we right-click at the start of the field, we will be able to paste, but anywhere outside of that child-input-field, we cannot.

<img width="438" alt="Screenshot 2019-08-17 at 19 07 16" src="https://user-images.githubusercontent.com/18581859/63212441-59229c00-c122-11e9-97d6-ba01c22050dd.png">
<img width="565" alt="Screenshot 2019-08-17 at 19 07 12" src="https://user-images.githubusercontent.com/18581859/63212442-59229c00-c122-11e9-9b61-c8f207235328.png">

The above screenshots can indicate that behaviour.

When the first username/email is filled up, the space immediately to the right of it is another child-input-field, where one can right-click to paste again.

This seems to be working as designed, but for an end-user, this may not be immediately clear. Wonder how we could improve this.

**Comment by samiff** [comment]
Another in 15608377-hc advised on using keyboard shortcuts for pasting as a work around.
