### ISSUE TITLE
FSE: Update customize link on the new account welcome email

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35513]
On creating a new account, there is a link to the Customizer for the first site on their account. It can be update to the editor of the homepage, similar to https://github.com/Automattic/wp-calypso/issues/35473

![Screen Shot 2019-08-17 at 18 07 27](https://user-images.githubusercontent.com/18581859/63211810-ed3c3580-c119-11e9-84d2-af684bffc823.png)

**Comment by apeatling** [comment]
@mattwiebe Is this covered by https://github.com/orgs/Automattic/projects/90#card-24744905?

**Comment by mattwiebe** [comment]
@apeatling yes, it's covered there. Testing emails is tricky and other things took higher priority initially. I'll circle back.

**Comment by apeatling** [comment]
Thanks, I think we need to address at least the most common emails. Certainly the welcome email.

**Comment by mattwiebe** [comment]
This one has been sorted out by D31096-code
