### ISSUE TITLE
FSE: Remove "View all posts" button from blog page template

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35516]
When one is using the `Blog` page template, the idea is to have a page that acts as a blog archive, showing all the posts.

And, when the `Blog posts listing` block on this page template automatically adds a `View all posts` button, that leads one to the homepage of the site, it doesn't look right. 

#### Steps to reproduce 

- Start with a FSE site.
- Create a page
- Choose `Blog` page template when creating this page
- Notice that this page now has a `Blog posts listing` block on it.
- This block automatically has a `View all posts` button, with no ability to update the link on this button
- Clicking that button takes one to the homepage of the site.
- The homepage has no blog posts to show. 

The larger issue is https://github.com/Automattic/wp-calypso/issues/35515 and when one has the ability to modify where `View all posts` points, or when one has an ability to remove that button from the `Blog posts listing` block, this report may not be necessary.

**Comment by marekhrabe** [comment]
The block we were using for listing posts has been replaced with one that has the pagination button included and loads more posts dynamically on the same page. Together with this "View all posts" button has been removed and this should no longer be an issue.
