### ISSUE TITLE
FSE: CoBlocks Masonry design on parent post's header/footer isn't same as on header/footer editor

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35510]
When CoBlocks' Masonry block is added to a header or footer region, the design isn't the same on the parent page, as it looks on the actual header or footer editor.

On the actual header or footer editor, it looks good:

<img width="1112" alt="Screenshot 2019-08-17 at 16 49 55" src="https://user-images.githubusercontent.com/18581859/63211015-42267e80-c10f-11e9-99f8-6dcba8dce9cf.png">

But on the header or footer from the parent page, it appears to be broken. We can see that all the images in the Masonry block do not have space between them.

<img width="1126" alt="Screenshot 2019-08-17 at 16 49 40" src="https://user-images.githubusercontent.com/18581859/63211016-510d3100-c10f-11e9-938a-0d1337fa178c.png">
<img width="1127" alt="Screenshot 2019-08-17 at 16 49 35" src="https://user-images.githubusercontent.com/18581859/63211017-51a5c780-c10f-11e9-9a44-f3fd220299a0.png">

The same Masonry block on the content section itself looks fine:

<img width="1149" alt="Screenshot 2019-08-17 at 16 49 29" src="https://user-images.githubusercontent.com/18581859/63211020-58ccd580-c10f-11e9-945c-00d9b6989dc1.png">

Context: Noticed when reporting https://github.com/Automattic/wp-calypso/issues/35509

**Comment by apeatling** [comment]
@kwight @mmtr Would you be able to help us track down this CoBlocks issue?

**Comment by mmtr** [comment]
I'm not sure if I'm missing any step, but I cannot reproduce this.

This is how the template editor looks like with a Gallery Masonry block:

<img width="1440" alt="Screen Shot 2019-08-24 at 10 30 17" src="https://user-images.githubusercontent.com/1233880/63630864-5fe96b80-c65a-11e9-8c9b-aa1d03e1232e.png">

And this is the page editor:

<img width="1440" alt="Screen Shot 2019-08-24 at 10 30 49" src="https://user-images.githubusercontent.com/1233880/63630872-6972d380-c65a-11e9-9a05-02589ab47355.png">

Both editors display the gallery with the same design.

**Comment by arunsathiya** [comment]
I am not able to reproduce either. 

The details mentioned on the report are correct, but something seems to have changed since the time I reported this bug and now.

I am closing this for now, but if we see this again in the future, let's feel free to reopen.
