### ISSUE TITLE
FSE: Button block has misplaced link toolbar when adding via page templates

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35512]
When using some page templates on a site with FSE activated, a button block may be added to the content section. Such a button block has misplaced link toolbar.

<img width="878" alt="Screenshot 2019-08-17 at 16 41 20" src="https://user-images.githubusercontent.com/18581859/63211056-e6a8c080-c10f-11e9-9b9e-0fb546838392.png">

Adding the button block on the same site manually has the link toolbar in the expected place:

<img width="873" alt="Screenshot 2019-08-17 at 16 41 11" src="https://user-images.githubusercontent.com/18581859/63211057-e7415700-c10f-11e9-9739-f2287deceffd.png">

**Comment by apeatling** [comment]
@Copons I think this is another case of alignment styles being too strong in the theme?

**Comment by noahtallen** [comment]
I used the same template on the current version, and I think this has been fixed by all of our style updates!

<img width="1044" alt="Screen Shot 2019-09-27 at 5 45 21 PM" src="https://user-images.githubusercontent.com/6265975/65809107-a137d400-e14e-11e9-832e-82ee7f347445.png">
