### ISSUE TITLE
2FA: Improve copy for download codes' button

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35521]
When creating a new WordPress.com account, I noticed that the download codes button on the 2FA flow reads `Download Codes Yo!`. That doesn't look like the type of wording we would want to use.

<img width="355" alt="Screenshot 2019-08-18 at 10 17 11" src="https://user-images.githubusercontent.com/18581859/63220288-9ed27980-c1a1-11e9-8641-f537d017ec04.png">

The other buttons read `Copy Codes` and `Print Codes`, which look fine. We should update the copy of the download button.

This can be seen when setting up 2FA, on the recovery codes stage.

**Comment by arunsathiya** [comment]
Cannot reproduce anymore. Seems to be fixed.

**Comment by Aurorum** [comment]
I still can reproduce this (EN-GB language). 

<img width="336" alt="Screenshot 2020-06-01 at 13 51 08" src="https://user-images.githubusercontent.com/43215253/83410797-f8452580-a40e-11ea-9c30-ad8c7693296e.png">

**Comment by arunsathiya** [comment]
Interesting! I can see the same behaviour for `EN-GB` but not for `EN-US`. 👍🏽

**Comment by Aurorum** [comment]
Hmm, looks like this isn't an issue within Calypso.

https://github.com/Automattic/wp-calypso/blob/1dfab2539492a833a0ffbbbae8ab797fe9edf0b6/client/me/security-2fa-backup-codes-list/index.jsx#L348

Instead, it appears there's an issue with the translation.

<img width="1081" alt="Screenshot 2020-06-01 at 19 32 26" src="https://user-images.githubusercontent.com/43215253/83441624-bc29b900-a43e-11ea-96c1-22a9c4348006.png">

I've proposed an alternative here: https://translate.wordpress.com/projects/wpcom/en-gb/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=35144&filters%5Btranslation_id%5D=8603995

**Comment by arunsathiya** [comment]
Thanks @Aurorum! I do not see an issue on English (UK) mode anymore either. Closing.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/18581859/112402935-71fa2700-8d33-11eb-8e55-395886b3ad1c.png">
