### ISSUE TITLE
FSE: Media selection section on "Media & Text" block overflows on the sides

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35524]
When adding a `Media & Text` block on a site with FSE enabled (details on p58i-7YJ-p2), the media selection section overflows on the sides.

<img width="1127" alt="Screenshot 2019-08-18 at 11 36 21" src="https://user-images.githubusercontent.com/18581859/63220825-c24ef180-c1ac-11e9-8a8b-337349b2c5ab.png">

<img width="1295" alt="Screenshot 2019-08-18 at 11 40 11" src="https://user-images.githubusercontent.com/18581859/63220836-faeecb00-c1ac-11e9-9195-15fa15c8992a.png">

Tested with:

- Firefox Quantum 66.0.5 (64-bit) 
- Google Chrome Version 74.0.3729.169 (Official Build) (64-bit) 

Both on macOS 10.14.5 - Mac OS Mojave. Tested with Mac display and external displays.

This does not happen on a WordPress.org site with Gutenberg plugin:

<img width="1048" alt="Screenshot 2019-08-18 at 11 37 09" src="https://user-images.githubusercontent.com/18581859/63220829-dabf0c00-c1ac-11e9-8e82-640243abd712.png">

**Comment by apeatling** [comment]
This is intended as part of the modern business design:

<img width="766" alt="Screen Shot 2019-08-19 at 2 16 26 PM" src="https://user-images.githubusercontent.com/1464705/63299979-f9480480-c28b-11e9-9ef9-5a35c3ef1a30.png">
