### ISSUE TITLE
FSE: Header and footer section do not load for editor role

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35527]
When creating a page on a FSE site (details on p58i-7YJ-p2) with an editor role account, the header and footer do not load. They keep showing a spinner icon.

<img width="1920" alt="Screenshot 2019-08-18 at 12 23 12" src="https://user-images.githubusercontent.com/18581859/63221225-8d926880-c1b3-11e9-89ef-62ca6d10bfca.png">

Tested on Firefox Quantum 66.0.5 (64-bit) with macOS 10.14.5 - Mac OS Mojave.

**Comment by arunsathiya** [comment]
I was able to notice the same behaviour for existing pages as well.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
