### ISSUE TITLE
FSE: Jump to content section from title on clicking "Enter"

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35525]
When creating a page on a site enabled with FSE (details on p58i-7YJ-p2), clicking on "Enter" key on the title section doesn't move the focus to the content section.

Clicking on the arrow-down key does that though.

On any other site with Gutenberg (non-FSE site on WordPress.com) or a WordPress.org site with Gutenberg, the "Enter" key works as expected. This looks like a bug specific to FSE sites.

**Comment by arunsathiya** [comment]
Additional note: I tested with `Modern Business` theme on a non-FSE site, and `Enter` key takes me to content section, from title section, as expected.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
