### ISSUE TITLE
FSE: Change "View posts" to "View pages" when closing a header/footer template editor

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35529]
When editing a header or footer template, the editor at the top right shows `View posts`. It should read `View pages` instead, as it takes one back to the pages list.

#### Steps to reproduce 

- Visit a page on a site enabled with FSE (details on p58i-7YJ-p2)
- Click on the header or footer part and click on the following edit button
- When the header or footer editor loads, remove the `fse_parent_post=xxx` URL parameter. This is required to show the close icon at the top right. With this URL parameter, we will simply see a `Back to page` button at the top right.
- Load the page without that URL parameter.
- Hover over the button at the top left.

#### What is expected 

The button reads `View pages`.

#### What happens instead 

The button reads `View posts`.

<img width="424" alt="Screenshot 2019-08-18 at 13 47 14" src="https://user-images.githubusercontent.com/18581859/63221995-15ca3b00-c1bf-11e9-8298-2cccf387897b.png">

#### Additional note

On a site without FSE, we see `View pages` as expected.

<img width="424" alt="Screenshot 2019-08-18 at 13 47 14" src="https://user-images.githubusercontent.com/18581859/63221998-1d89df80-c1bf-11e9-88bd-499cee8a0c61.png">

**Comment by arunsathiya** [comment]
Another quick note that this does not happen for pages. When closing a page, the button reads `View pages`, as expected.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
