### ISSUE TITLE
FSE: Site title and Site description blocks show escaped characters on editor view

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35522]
When updating the site title or site description on https://wordpress.com/settings/general, or directly on the `Site title` or `Site description` blocks, I noticed that the escaped characters are shown on the editor view.

![Screenshot_20190818-094119](https://user-images.githubusercontent.com/18581859/63220382-d510f880-c1a3-11e9-94cc-d7c89b1022db.jpg)
![Screenshot_20190818-094553](https://user-images.githubusercontent.com/18581859/63220383-d510f880-c1a3-11e9-92e7-91c3883b6273.jpg)

On the live view though, the characters appear as expected.

![Screenshot_20190818-094031](https://user-images.githubusercontent.com/18581859/63220381-d04c4480-c1a3-11e9-8b7a-8dd470b295f5.jpg)

Here is how it looks on the site description field of https://wordpress.com/settings/general: 

![Screenshot_20190818-094023](https://user-images.githubusercontent.com/18581859/63220386-e22de780-c1a3-11e9-9667-6efaaa085892.jpg)

### Note:

Interestingly, this did not happen the first time I had used `Arun's Bistro` as the site title during setup. Only when updating the title or description on https://wordpress.com/settings/general, or on the block itself, the escaped characters appear on the editor view.

**Comment by gwwar** [comment]
This one should be fixed by https://github.com/Automattic/wp-calypso/pull/35431. We sync code ~every two weeks though on wpcom, so might take a while to show up.

**Comment by apeatling** [comment]
Closing this because it will be fixed by https://github.com/Automattic/wp-calypso/pull/35431
