### ISSUE TITLE
Recurring Payments: Add to the plans' feature list

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35538]
Currently the `Recurring payments` feature is mentioned only on the https://wordpress.com/earn page, and clicking on the `Update to a paid plan` nudge here takes one to https://wordpress.com/plans

<img width="1135" alt="Screenshot 2019-08-18 at 18 43 41" src="https://user-images.githubusercontent.com/18581859/63224895-686c1d00-c1e8-11e9-98f2-ebd995e150fd.png">

On this page, the plans' feature list is shown, but `Recurring payments` is nowhere to be seen. It can be added to all plans, starting from the Personal plan. (both for WordPress.com and Jetpack)

We may also want to improve the `Site monetization` copy, which is shown starting from WordPress.com Premium plan and Jetpack Premium plan.

<img width="585" alt="Screenshot 2019-08-18 at 18 42 24" src="https://user-images.githubusercontent.com/18581859/63224893-630ed280-c1e8-11e9-847b-85e116f3961f.png">

cc @artpi

**Comment by artpi** [comment]
Yes, this is on the roadmap, however the efforts to announce the feature are being worked on to provide a unified launch.

**Comment by arunsathiya** [comment]
No longer an issue. It's available now.

<img width="633" alt="Screenshot 2020-03-28 at 13 45 25" src="https://user-images.githubusercontent.com/18581859/77818684-6c570a80-70fa-11ea-9a51-3aac73006ba5.png">
