### ISSUE TITLE
Media: Page should show a permission error for contributor users

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35530]
#### Steps to reproduce 

- Start with a WordPress.com site with a contributor user on it.
- Visit https://wordpress.com/media for that site, as the contributor user.

#### What is expected 

The page isn't actionable by this user, as media uploads are not available for contributor users. [Details](https://en.support.wordpress.com/editors/media-icons/).

#### What happens instead 

The page shows the list of media files uploaded on that site.

There is also a broken bar where typically "Add new" button and the storage space slider appears.

<img width="1920" alt="Screenshot 2019-08-18 at 13 59 05" src="https://user-images.githubusercontent.com/18581859/63222118-d1d83580-c1c0-11e9-8797-91ca6f4a5f71.png">

Also, drag-dropping files shows no response. 

#### What is suggested

We should just avoiding showing these media library files, and show a notice that this page is not actionable by contributor users. Something similar to what was proposed in https://github.com/Automattic/wp-calypso/issues/33032.

**Comment by Aurorum** [comment]
PR in #35533 :)
