### ISSUE TITLE
FSE: CoBlocks "Pricing Table" CTA shows error on console before loading the destination

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35536]
#### Steps to reproduce 

- Start with a FSE site.
- Create a post or page and add the CoBlocks' `Pricing table` block.
- On one of the table columns, set a CTA text and link.
- Open that page/post and click on the CTA, with browser console open.

#### What is expected 

CTA loads without any errors.

#### What happens instead 

This error can be seen to be logged, just before loading the CTA link.

```
Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined
    at removeAllFocusStates 
    at HTMLDocument.<anonymous> 
```

#### Notes

Testing the same block on a dotorg site with [CoBlocks plugin](https://wordpress.org/plugins/coblocks/) installed shows no such errors. 

Possibly this was a bug earlier, and was fixed in the latest versions of CoBlock, and dotcom version is yet to be updated?

**Comment by kwight** [comment]
I couldn't replicate now, nor could I find references to `removeAllFocusStates` in CoBlocks or FSE – I think we're good now.
