### ISSUE TITLE
FSE: "Find original" action on duplicate content section doesn't work

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35535]
When I copied a full page using the `Copy all content` option at the top-right hamburger menu of the Gutenberg editor, and pasted the data on a new page, the `Content` section pasted from this data doesn't render. It shows a `Content: This block can only be used once.` notice, which appears to be expected, because there is already another `Content` section (AKA `Content` block) on this page.

On trying to use the `Find original` action that's shown, there is no response.

<img width="932" alt="Screenshot 2019-08-18 at 17 51 45" src="https://user-images.githubusercontent.com/18581859/63224422-939f3e00-c1e1-11e9-9e31-ae1eb532bc85.png">

And, such a published page does not load. That is, when attempting to view this page on a new tab, the browser keeps trying to load it, but after a few minutes, nothing is to be seen. The browser tab just shows a white screen of death.

The `Remove` action works though, and after the removal of this duplicate `Content` block, the page loads fine.

#### Context

Ran into https://github.com/Automattic/wp-calypso/issues/35534 as well while trying this process.

**Comment by arunsathiya** [comment]
>And, such a published page does not load. That is, when attempting to view this page on a new tab, the browser keeps trying to load it, but after a few minutes, nothing is to be seen. The browser tab just shows a white screen of death.

One more thing that I noticed - after removing the duplicate header and footer blocks, we have these blocks:

- Header of the page
- Content of the page
- Duplicate content block on this page
- Footer of the page

At this stage, loading the page on a new tab fails with a proper `HTTP 500`. And, after removing the `Content` block as well, the page loads normally with these blocks:

- Header of the page
- Content of the page
- Footer of the page

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
