### ISSUE TITLE
FSE: All headings on left-aligned on editor but centered on the live view

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35532]
Noticed that all the headings (`Heading` block) are left-aligned on the editor, but are centered on the live page view.

They should be similar - either left-aligned as on editor, or centered. 

Example 1:

<img width="1051" alt="Screenshot 2019-08-18 at 14 09 23" src="https://user-images.githubusercontent.com/18581859/63222353-5aa4a080-c1c4-11e9-85d9-cdfc774008b3.png">
<img width="1162" alt="Screenshot 2019-08-18 at 14 09 13" src="https://user-images.githubusercontent.com/18581859/63222354-5aa4a080-c1c4-11e9-9db1-a392ab544e23.png">

Example 2:

<img width="754" alt="Screenshot 2019-08-18 at 14 28 06" src="https://user-images.githubusercontent.com/18581859/63222357-6b551680-c1c4-11e9-8f93-0ea9b8f7aae5.png">
<img width="763" alt="Screenshot 2019-08-18 at 14 27 59" src="https://user-images.githubusercontent.com/18581859/63222358-6b551680-c1c4-11e9-905b-d5f9d0c849d6.png">

**Comment by apeatling** [comment]
Related: https://href.li/?https://github.com/Automattic/wp-calypso/issues/35569

**Comment by Copons** [comment]
On hold!
Let's check again after Automattic/template-first-themes-private#126

**Comment by iamtakashi** [comment]
This won't be an issue with Maywood (Modern Business refresh).

**Comment by Copons** [comment]
Fixed by using Varia/Maywood.
