### ISSUE TITLE
FSE: "Copy all content" should not copy header and footer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35534]
When using the `Copy all content` option at the top-right hamburger menu of the Gutenberg editor, the header and footer is copied to the clipboard as well.

On pasting this clipboard data on a new page, the header and footer can be noticed to be added again to the page.

<img width="979" alt="Screenshot 2019-08-18 at 17 47 06" src="https://user-images.githubusercontent.com/18581859/63224371-b5e48c00-c1e0-11e9-9b21-42f8b62a7f8c.png">

The above image shows the duplicate header.

Likewise, there is a duplicate footer.

#### What is suggested

We do not copy the header and footer data to the clipboard. Ideally we should be copying only the page's `Content` block data.

**Comment by arunsathiya** [comment]
Related copying - https://github.com/Automattic/wp-calypso/issues/35605 and https://github.com/Automattic/wp-calypso/issues/35604

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
