### ISSUE TITLE
FSE: Tiled gallery: "Wide width" setting always renders as "Full width" on header

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35540]
When adding a `Tiled gallery` from Jetpack on the **header section** of a FSE site, choosing `Wide width` design always renders the gallery as a `Full width`. 

| Wide width | Full width |
|------|------|
| ![Screenshot 2019-08-18 at 19 26 25](https://user-images.githubusercontent.com/18581859/63225492-280f9d80-c1ee-11e9-8ecf-28bb151383f4.png) | ![Screenshot 2019-08-18 at 19 26 38](https://user-images.githubusercontent.com/18581859/63225491-27770700-c1ee-11e9-933c-3f489dd54ab0.png) | 

The `Align center` option loads as expected.

![Screenshot 2019-08-18 at 19 26 12](https://user-images.githubusercontent.com/18581859/63225487-1fb76280-c1ee-11e9-8037-fbb93d30ce12.png)

It can also be seen that for `Full width`, the images get cut off on the sides.

#### Notes

The same gallery loads as expected for all designs (`Align center`, `Wide width` and `Full width`) on a non-FSE site.

Since `Tiled gallery` is a block from Jetpack, I am adding the Jetpack label as well.

**Comment by arunsathiya** [comment]
>It can also be seen that for Full width, the images get cut off on the sides.

This sounds a bit similar to this issue https://github.com/Automattic/wp-calypso/issues/35432 where images overflow as well.

**Comment by noahtallen** [comment]
This has been resolved with the latest updates :)

<img width="1471" alt="Screen Shot 2019-09-27 at 5 49 27 PM" src="https://user-images.githubusercontent.com/6265975/65809156-2de29200-e14f-11e9-8092-f839c90b4ccb.png">
