### ISSUE TITLE
FSE: Tiled gallery: In footer, block renders at "Align center" width irrespective of the choice chosen

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35541]
Similar to https://github.com/Automattic/wp-calypso/issues/35540, when testing the `Tiled gallery` block from Jetpack on the **footer section**, I noticed that the gallery always loads as `Align center` width, irrespective of choosing one of these:

- Align center
- Wide width
- Full width

Basically, the last two are not rendering as expected.

Align center:

![Screenshot 2019-08-18 at 19 31 14](https://user-images.githubusercontent.com/18581859/63225564-e6332700-c1ee-11e9-8950-85c9a23b6e26.png)

The other two options:

| Wide width | Full width |
|------|------|
| ![Screenshot 2019-08-18 at 19 31 35](https://user-images.githubusercontent.com/18581859/63225562-e29fa000-c1ee-11e9-84eb-166cd4a4ca53.png) | ![Screenshot 2019-08-18 at 19 31 48](https://user-images.githubusercontent.com/18581859/63225561-e29fa000-c1ee-11e9-9365-ad341167b1f9.png) |

**Comment by Copons** [comment]
On hold!
Let's check again after Automattic/template-first-themes-private#126

**Comment by Copons** [comment]
Fixed by using Varia/Maywood.
