### ISSUE TITLE
FSE: Use custom colors on buttons in Blog Posts Listing block

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#35558]
The `Blog posts listing` block contains two buttons:

1. `Edit`
2. `View all posts`

Both buttons display, as their background, the main accent color for the theme. The problem comes when you add a different color via Customizer > Colors.

Example using the theme Elegant Business:

<img width="890" alt="Captura de Tela 2019-08-19 às 12 10 00" src="https://user-images.githubusercontent.com/1136160/63276739-5cc93680-c27a-11e9-8d72-3a2b848c551b.png">

#### What I expected
To see the same colors I chose in Customizer > Colors.

#### Context / Source
#dogfooding

**Comment by davipontesblog** [comment]
I am closing this issue since this block as been replaced with the [Blog Posts block](https://github.com/Automattic/newspack-blocks).
