### ISSUE TITLE
FSE: Invisible saves on empty titles causes ugly page titles

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35566]
From Kris Karkoski:

It was nice to see making changes and then editing the header prompted an invisible save, but I had wiped the title so when I went to edit the header the title shown was pretty ugly. Maybe we can revert to the previous title if blank on auto save?

![screen-shot-2019-08-16-at-1 58 49-pm](https://user-images.githubusercontent.com/1464705/63283704-cb9c9480-c266-11e9-8af2-e7b3181de005.png)

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
