### ISSUE TITLE
FSE: Heading text alignment doesn't work when editing the header

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35569]
From Sarah Wolff Milligan:

When I edit headings in the editor, even when I set the header as centered under Text Alignment, the header doesn’t show as centered in the editor:

<img width="689" alt="screen-shot-2019-08-19-at-11 21 40-am" src="https://user-images.githubusercontent.com/1464705/63283991-7b720200-c267-11e9-90a2-d87f390863cb.png">

On the front end it is working:

<img width="689" alt="screen-shot-2019-08-19-at-11 31 12-am" src="https://user-images.githubusercontent.com/1464705/63284006-80cf4c80-c267-11e9-9508-b19f9c57d728.png">

**Comment by arunsathiya** [comment]
I ran into the same/similar bug. 

### Content section

When I set the `Heading` block as centered, left-aligned or right-aligned, the `Heading` block continues to remain left-aligned on editor and centered on live site.

### Header section

The block continues to be centered on editor, for any alignment, and is centered on live site as well.

### Footer section

The block continues to be left-aligned on editor, for any alignment, and left-aligned on live site as well.

Overall, seems like the block is misbehaving on all sections of a FSE page.

**Comment by Copons** [comment]
On hold!
Let's check again after Automattic/template-first-themes-private#126

**Comment by iamtakashi** [comment]
This is essentially the same issue as #35532, and Maywood(Modern Business refresh) will not have the same issue.

**Comment by arunsathiya** [comment]
@iamtakashi Trying to understand better, does this mean that the issues will continue to be visible on Modern Business, but we are fixing that only on Maywood?

**Comment by Copons** [comment]
> @iamtakashi Trying to understand better, does this mean that the issues will continue to be visible on Modern Business, but we are fixing that only on Maywood?

@arunsathiya Basically we realized that Modern Business has too much tech debt to be efficiently adapted to support Full Site Editing, and have decided to drop its support and replace it with Maywood (and other "sibling" themes).

**Comment by arunsathiya** [comment]
@Copons That is great information to have, thanks Jacopo!

**Comment by Copons** [comment]
Fixed by using Varia/Maywood.
