### ISSUE TITLE
FSE: Setting a featured image breaks the header design

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35574]
When a featured image is set on a page, the header section on the page is broken. It appears with a brown-shaded background and none of the elements are not actionable.

<img width="1920" alt="Screenshot 2019-08-19 at 22 46 41" src="https://user-images.githubusercontent.com/18581859/63285468-70ed5200-c2d3-11e9-8e54-89b535c3f2af.png">
<img width="1920" alt="Screenshot 2019-08-19 at 22 46 45" src="https://user-images.githubusercontent.com/18581859/63285469-70ed5200-c2d3-11e9-9afc-ef817db041bb.png">
<img width="1920" alt="Screenshot 2019-08-19 at 22 46 52" src="https://user-images.githubusercontent.com/18581859/63285470-7185e880-c2d3-11e9-8858-a8167bcfefc4.png">

I had a look at the page's markup, but it's not immediately clear what's going on.

<img width="1920" alt="Screenshot 2019-08-19 at 22 49 30" src="https://user-images.githubusercontent.com/18581859/63285563-a2661d80-c2d3-11e9-9e38-f7aa67190ac1.png">

**Comment by apeatling** [comment]
We should remove the featured image setting for pages.
