### ISSUE TITLE
FSE: 404 page copy misaligned at certain widths

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35575]
The 404 copy `Oops. That page can't be found` appears to be misaligned (not-centered) between 768px and 956px.

![404 copy](https://user-images.githubusercontent.com/18581859/63286616-1275a300-c2d6-11e9-875e-749da3600c9b.png)

After 956px, the copy slowly starts to get centered, and we can see this behaviour on [this video](https://cloudup.com/cH670d3JJcp).

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
