### ISSUE TITLE
Question: Could Calypso be used with any backend that supports the Wordpress REST API

### ISSUE THREAD

**Issue by balupton** [Automattic/wp-calypso#3557]
Hey all,

From https://developer.wordpress.com/calypso/

> The new WordPress.com codebase, codenamed "Calypso," moves WordPress.com away from MySQL and PHP. It's built entirely in JavaScript, and communicates with WordPress.com only using our REST API. This means the new WordPress.com is a browser-based client for our API, just like any other application built on top of it — lighter, faster, and more flexible for a mobile-focused world.

This makes me wonder whether not Calypso could work with any backend that implements the [Wordpress REST API Specification](https://developer.wordpress.com/docs/api/) exactly. Making Calypso potentially backend agnostic.

Is this a reasonable target? If so, it could open up the world for developing a Wordpress REST API server for front-matter files (popular in Static Site Generators) then hooking up Calypso to be the client editing interface.

**Comment by codebykat** [comment]
Hi there @balupton! It would certainly be pretty easy to modify Calypso to talk to a different API that used the same spec. You might also be interested in checking out the REST API project, slated to become part of WordPress core in the near future -- http://v2.wp-api.org. The WordPress.com API is ultimately planned to sync up with the core API, which will make it even easier to build the sort of client you're talking about.
