### ISSUE TITLE
FSE: At 781px and lesser, "Back to page" button is missing on header and footer editor

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35573]
When editing the header or footer on a device with width 781px or lesser, the `Back to page` button is missing at the top left. We see only an option to add new blocks.

781px and lesser:

<img width="309" alt="Screenshot 2019-08-19 at 22 39 12" src="https://user-images.githubusercontent.com/18581859/63285086-9c237180-c2d2-11e9-939d-01eb78a882ed.png">

Above 781px:

<img width="319" alt="Screenshot 2019-08-19 at 22 39 06" src="https://user-images.githubusercontent.com/18581859/63285088-9cbc0800-c2d2-11e9-8427-a09c3fb4605a.png">

For a mobile user, this can be a challenge. A few ways such an user to go back to the page would be:

- Type https://wordpress.com/pages manually and choose the page they were working on.
- Click on the hamburger menu at the top right of the Gutenberg editor, choose `Manage all reusuable blocks`, click on `My site` at the top left and choose `Pages` to view all the pages.

**Comment by noahtallen** [comment]
I think the challenge with this is that the button is hidden in gutenberg at low breakpoints regardless. Ultimately, the user can still use their browser back button or a back swipe to navigate back. For example, here is the mobile post editor with no FSE styles.
<img width="785" alt="Screen Shot 2019-08-19 at 7 22 40 PM" src="https://user-images.githubusercontent.com/6265975/63312551-bd766480-c2b6-11e9-9204-062d23cf5289.png">

**Comment by apeatling** [comment]
Good catch Noah, reducing severity of this because it's already true of live sites. There should still be a way for users to easily get out of the editor at smaller sizes, where the core navigation bar is not present.

**Comment by noahtallen** [comment]
This was fixed a month or two ago :)
