### ISSUE TITLE
FSE: wp_template post type does not return API response in wpcom namespace

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35587]
When directly visiting https://wordpress.com/types/wp_template/{siteId} we see that the count endpoint works, but no post content is being returned for this post type. We should mirror the edit functionality that `/wp-admin/edit.php?post_type=wp_template` provides

Calypso
<img width="1106" alt="Screen Shot 2019-08-19 at 3 54 36 PM" src="https://user-images.githubusercontent.com/1270189/63305145-9873f880-c29a-11e9-9a41-755688ceef8c.png">

wp-admin
<img width="1118" alt="Screen Shot 2019-08-19 at 4 02 15 PM" src="https://user-images.githubusercontent.com/1270189/63305206-dd982a80-c29a-11e9-9acd-7ac50c618249.png">

**Comment by vindl** [comment]
Note: this is now `wp_template_part`.

**Comment by mattwiebe** [comment]
D34120-code will fix this

**Comment by Copons** [comment]
🤔This works for me without any additional work...

Tested on one of my test sites right now: https://wordpress.com/types/wp_template_part/coponsa8cfse12.wordpress.com

<img width="1242" alt="Screenshot 2019-10-17 at 17 02 20" src="https://user-images.githubusercontent.com/2070010/67026553-e7ee6d80-f0ff-11e9-8830-ad18ca3666b8.png">

Should we also want to show it in the menu, we can remove these lines:

https://github.com/Automattic/wp-calypso/blob/9ab21f03e217c8956d0c655dd58958f12421ed96/client/my-sites/sidebar/site-menu.jsx#L143-L146

**Comment by mattwiebe** [comment]
This fix has been deployed
