### ISSUE TITLE
Checklist: Launch your site and email address confirmation

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35585]
Confirm your email address is ordered after "Launch your site" on the checklist, but is a requirement for launching the site. Maybe consider ordering the email address confirmation earlier, or adding a re-send confirmation link within the notice.

<img width="775" alt="Screen Shot 2019-08-19 at 3 46 09 PM" src="https://user-images.githubusercontent.com/1270189/63304812-39fa4a80-c299-11e9-95bc-5f25b81c7048.png">

To reproduce, try creating a new private by default site, then visit the checklist without confirming an email address.

**Comment by jblz** [comment]
Fix for review in D31715-code

**Comment by jblz** [comment]
Fixed in D31715-code
