### ISSUE TITLE
Masterbar: wonky rendering of Reader menu item in Themes

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#35596]
This bug does not occur in production. 

#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/theme/stow while logged in 
2. Masterbar briefly shows logged out state

<img width="774" alt="Screen Shot 2019-08-20 at 16 53 47" src="https://user-images.githubusercontent.com/17325/63318590-199ac080-c36b-11e9-8830-50cb4995a749.png">

3. Masterbar shows logged in menu items but with incorrect class name on Reader item leading to wonky display

<img width="1392" alt="Screen Shot 2019-08-20 at 16 49 35" src="https://user-images.githubusercontent.com/17325/63318580-0ee02b80-c36b-11e9-9159-bc3c68872564.png">

Investigating the markup further shows that we're appearing to render the 'logged out' children inside logged in component (note that `data-tip-target`, `title` and the masterbar__reader class name are missing from the Reader link).

Correct markup:

<img width="997" alt="Screen Shot 2019-08-20 at 16 17 34" src="https://user-images.githubusercontent.com/17325/63318675-62527980-c36b-11e9-862c-cff5a2de4550.png">

Markup in this scenario:

<img width="888" alt="Screen Shot 2019-08-20 at 16 16 40" src="https://user-images.githubusercontent.com/17325/63318687-6bdbe180-c36b-11e9-85d0-0668a7c218b4.png">

#### What I expected

First two menu items look like this when I am logged in:

<img width="235" alt="Screen Shot 2019-08-20 at 16 56 32" src="https://user-images.githubusercontent.com/17325/63318721-83b36580-c36b-11e9-82fb-74030c0bb3db.png">

#### What happened instead

First two menu items look like this:

<img width="213" alt="Screen Shot 2019-08-20 at 16 57 05" src="https://user-images.githubusercontent.com/17325/63318735-9168eb00-c36b-11e9-924a-da8bf89c33a8.png">

#### Context / Source

Found while working on https://github.com/Automattic/wp-calypso/pull/35595.

cc @Automattic/team-calypso

**Comment by jsnajdr** [comment]
This is a known SSR bug that affects only development mode where there is no server-side user bootstrapping.

The server doesn't know that the user is logged in and renders a logged-out Theme Showcase page that has a custom masterbar:

<img width="525" alt="Screenshot 2019-08-20 at 14 43 09" src="https://user-images.githubusercontent.com/664258/63348337-52319e80-c359-11e9-8d0d-b6272cbbe1c6.png">

Then the client renders a logged-in Themes view over that SSR-ed markup. But React hydration is very sensitive to the server and client markup not being the same. The DOM structure is not correctly updated and results in a broken view.

**Comment by bluefuton** [comment]
Thanks for explaining @jsnajdr! This looks like the related issue: https://github.com/Automattic/wp-calypso/issues/27550.

**Comment by bluefuton** [comment]
Closing this - #27550 details the bug and it only affects development mode.
