### ISSUE TITLE
Domains: Make it clear on Domains Page that adding a domain will not create a new site

### ISSUE THREAD

**Issue by wpericam** [Automattic/wp-calypso#35593]
#### Steps to reproduce
1. Head to Manage > Domains > Add 
2. Register a domain 

#### What users report that they expected
Often time, users think that adding a domain from this page will create a new site at that domain. 

#### What happens instead
- Users instead see that their new domain has been added as a secondary domain on their existing site 
- At that point, they must be directed to create a new site and choose a free domain and then move their domain to the new site after the fact

#### Context 

One of the most common support interactions I have are the result of customers adding secondary domains when what they wanted to do was add a new site. It seems they miss the "Add Site" option under My Site > Switch Site and they go right to the domains page. 

#### Suggestion 

It may be helpful to note on the domains page that all domains listed here will point to the primary domain and add an option to "start a new site instead of adding a domain to this site" somewhere prominent on the domains page.

**Comment by wpericam** [comment]
Original request in zen-1908600

**Comment by wpericam** [comment]
Would have helped in this case as well

zen-1974175

**Comment by wpericam** [comment]
User added several domains when they meant to start new sites 

HC-9206112

**Comment by wpericam** [comment]
Another report 

HC-13711178

**Comment by wpericam** [comment]
Another report

zen-2148181

**Comment by wpericam** [comment]
Another user added a domain when they meant to start a new site

HC-13841102

**Comment by arunsathiya** [comment]
I had reported this earlier on https://github.com/Automattic/wp-calypso/issues/29971 and I recently closed it in favor of https://github.com/Automattic/wp-calypso/issues/27932.

Can you add your reports to https://github.com/Automattic/wp-calypso/issues/27932 and close your report, please? 

There is also work happening for the same on https://github.com/Automattic/wp-calypso/pull/34990

Related - p7DVsv-6Vg-p2

**Comment by wpericam** [comment]
Closed and added reports #27932
