### ISSUE TITLE
Plans grid: payment options have no space in medium sized screens

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#35597]
Payment options on Plans grid (https://wordpress.com/plans) on medium-sized screens seems off:

<img width="848" alt="Screenshot 2019-08-20 at 09 36 15" src="https://user-images.githubusercontent.com/87168/63323424-6ca25280-c32e-11e9-91ba-3f038416de5a.png">

Expected to see more space like on bigger screens and small mobile sized screens:

<img width="1196" alt="Screenshot 2019-08-20 at 09 36 45" src="https://user-images.githubusercontent.com/87168/63323431-72983380-c32e-11e9-9081-4ce162dc8026.png">

The whole grid could collapse little earlier than it does now — looks very tight:

<img width="750" alt="Screenshot 2019-08-20 at 09 38 04" src="https://user-images.githubusercontent.com/87168/63323456-7fb52280-c32e-11e9-8a21-d779b098269b.png">

cc @yoavf @niranjan-uma-shankar as I'm not sure whom to ping but I've seen you work on this stuff before. 😁

**Comment by Saravanan90** [comment]
Hi @simison I have fixed this style issue. Will be raising a PR.
