### ISSUE TITLE
Me: No 404 page in /me section

### ISSUE THREAD

**Issue by p3ob7o** [Automattic/wp-calypso#3559]
#### Steps to reproduce
1. Start at URL: https://wordpress.com/me/randomstring

#### What I expected

A page that let users know nothing exists at that URL and helps them find their way back.

Like the one at https://wordpress.com/randomstring

#### What happened instead

Blank Calypso page

#### Browser / OS version

Browser / OS independent

**Comment by lamosty** [comment]
This is being worked on in #3453. At the moment, it displays this:
![](https://i.imgur.com/Qls1pmn.png)

I think it is safe to close this issue.

**Comment by lamosty** [comment]
Closing in favor of #3453.
