### ISSUE TITLE
FSE: Do not show page templates when copying a page

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35604]
When copying a page using the `Copy` option on a page's menu (on https://wordpress.com/pages), the page template selector shouldn't be shown. We are basically duplicating an existing page, so, the same page template should be retained.

<img width="785" alt="Screenshot 2019-08-20 at 16 23 16" src="https://user-images.githubusercontent.com/18581859/63341619-45b44280-c367-11e9-97d8-2197c938bfc1.png">

![Screenshot 2019-08-20 at 16 29 51](https://user-images.githubusercontent.com/18581859/63341849-c2dfb780-c367-11e9-8740-3651a975c313.png)

**Comment by obenland** [comment]
I've not seen that one. @apeatling should we add that to our next iteration?

**Comment by apeatling** [comment]
Yes please.
