### ISSUE TITLE
(5P) SPT: Add (food) Menu page template as a global page template.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#35613]
Recently launched theme, Rockfield has a nice and simple [menu page template](https://rockfielddemo.wordpress.com/menu/?demo) that could work  with many themes. And it'd be nice to add the template in the page template selector.

- [x] Double-check image sizes and update them with optimized versions if needed
- [x] Filter out professional and small-business template in the API endpoint. We need them to stay in the json for #35255.
- [x] Filter out the menu template in the API endpoint for non-English locales
- [x] Update json file with new template
- [ ] Submit the new json for translation (pxLjZ-5cM-p2#comment-16107)

**Comment by iamtakashi** [comment]
I've already copied over the template to the template master site, but before progressing further, I was wondering if we should remove either Small Business or Professional page template. So that we can keep the nice 3x3 grid that we have now.

<img width="817" alt="Screen Shot 2019-08-20 at 15 02 12" src="https://user-images.githubusercontent.com/908665/63353981-8a39e100-c35b-11e9-9615-11abac1425e3.png">

I remember seeing the data suggesting those page templates are worst performer amongst them, and these were actually confusing to be there in some of the usability sessions.

Any opinion on this? cc @apeatling @obenland

**Comment by apeatling** [comment]
Yes, let's remove both professional and small business, these perform considerable worse than other templates, and confuse the template selection process.

**Comment by retrofox** [comment]
> I was wondering if we should remove either Small Business or Professional page template

What do you think just removing the _blank_ one?

**Comment by apeatling** [comment]
I think we should leave the blank template because it's an obvious pass through if you don't want to use a template. Otherwise these people have to click the X or outside of the modal, that seems annoying.

**Comment by retrofox** [comment]
> Otherwise these people have to click the X or outside of the modal, that seems annoying.

Or the cancel button. 

![image](https://user-images.githubusercontent.com/77539/63444606-50291780-c40d-11e9-8826-b78b41b0b11b.png)

**Comment by apeatling** [comment]
Thanks, yes. I would still say relying on the cancel button feels like a less optimal path than selecting blank.

**Comment by iamtakashi** [comment]
> I would still say relying on the cancel button feels like a less optimal path than selecting blank.

I agree. I'd vote for keeping the blank. And remove Professional and Small Business.

This is an example of good use of a blank template as an option. I click that all the time :)

<img width="1639" alt="Screen Shot 2019-08-21 at 18 59 18" src="https://user-images.githubusercontent.com/908665/63456167-38ba5080-c446-11e9-80e9-316badcea73f.png">

We don't need to follow what Google does, but I'm sharing this as I find it useful.

**Comment by iamtakashi** [comment]
@retrofox How about something like this for the description?

`Text-based introduction section, followed by three sections of food menu items laid out in three columns.`

And here is the thumbnail:
![menu](https://user-images.githubusercontent.com/908665/64294248-32f45d00-cf66-11e9-8288-6d95e4399bbb.png)

Let me know any issue! Thanks for working on this.

**Comment by retrofox** [comment]
> Yes, let's remove both professional and small business, these perform considerable worse than other templates, and confuse the template selection process.

are we going to show 8 templates in a matrix (usually) of 3x3?

![image](https://user-images.githubusercontent.com/77539/64555859-77cc1b00-d2fb-11e9-8bad-ca309ac279d7.png)

I think it looks _weird_

**Comment by obenland** [comment]
I personally don't mind it too much. The amount of previews changes based on screen size anyway, so unless we have 12 it'll never look perfect. Not sure that should be something that keeps us from making this change

**Comment by iamtakashi** [comment]
I agree with @obenland. I don't see it's a big deal.

**Comment by getdave** [comment]
Just a note that the _browser_ will calculate how many previews to show per row via the CSS Grid spec. We do not and cannot (in any sane world) have control over this. Nor (I believe) should we attempt to.  Glad we agree on this 😌.

**Comment by getdave** [comment]
@iamtakashi What more help do you need from @Automattic/ajax to get the task "Add (food) Menu page template as a global page template" completed?

**Comment by obenland** [comment]
The changes live in D32499-code and are in a note in the "Ready for Review" column on our board. It will fix the first four checkboxes. Once the above is in, I'll kick off another round of translations.

**Comment by iamtakashi** [comment]
Thanks for your help on this, @Automattic/ajax!
