### ISSUE TITLE
Replace Template Selector Modal

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#35620]
Our existing template selector is presented as a modal. This is fine for a v1, but it does not allow you to easily switch between templates.

Let's look at ways to replace the modal with something that will allow you to quickly switch between templates, even after you've selected one.

Design: #35248

Considerations:
* Styling the modal in a way that it looks like part of the Editor rather than converting it into a block.

**Comment by obenland** [comment]
@mtias p1566313830261900-slack-ajax is the beginning of our deliberations around what it could look like to move the selector out of the modal.

The current consensus is to solve it through styles and have it be appear more integrated, mostly due to the unknown of what it means to convert it into a block and create a new workflow. It was mentioned that you've talked about setup blocks before and might have some more information to share on that?

**Comment by mtias** [comment]
I'd advise against using styles for this. The modal component comes with specific interactions — contained focus, etc — with accessibility implications. If you want to use the modal, it should look like a modal. If you want to integrate it with the editor as a block, you should use a block.

**Comment by obenland** [comment]
-[ ] Replace modal component with a div
-[ ] Use second design iteration
-[ ] Maintain existing interaction design
-[ ] Thumbnails return to square design
-[ ] Keep mobile experience the same for now

@shaunandrews to decide where the "Select this template" button will live.
