### ISSUE TITLE
(?P) Add tests for missing images in gallery full-screen preview on front of site

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35629]
See p58i-7RD-p2#comment-42220

> if you don’t replace the images in the gallery on the Portfolio template when you view the page on the front of the site and click one of the images to bring up the full screen view, you get a blank image. However, when you replace the images with your own, then you do see the full screen images.

This is more complicated than it looks. 

See 

* Original bug report: p58i-7RD#comment-42220
* Related Jetpack issue: https://github.com/Automattic/jetpack/issues/11191

**Comment by obenland** [comment]
We will not be working on this. Image side loading could have been a way to prevent this bug, but we won't move forward with that either, given the high amount of data we'd be pushing around.
This really should just be fixed in Jetpack.
