### ISSUE TITLE
FSE: Roll out to 100% of Maywood theme users

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35622]
With the completion of epic issues:

https://github.com/Automattic/wp-calypso/issues/35519
and
https://github.com/Automattic/wp-calypso/issues/35544

Along with getting back neutral or positive launch rate data, we will ramp the test up to 100% of Modern Business users.

Prerequisites are:

- [ ] https://github.com/Automattic/wp-calypso/issues/35519 Modern Business launch cleanup
- [ ] https://github.com/Automattic/wp-calypso/issues/35544 At minimum navigating and adding pages via the navigation block.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
