### ISSUE TITLE
Build Missing Blocks Needed for Theme Templates

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35633]
The new themes and templates (not recreations of existing themes) that we build for WordPress.com will have more advanced block needs.

This is currently being supported by Tinker, however we need more help building blocks and block settings to support these new themes on WordPress.com.

Block needs identified so far:

- [x] Social links block for business theme headers (being worked on by Tinker)
- [ ] Featured post slider block for Daria theme. See: paAmJe-Ik#comment-1839

**Comment by marekhrabe** [comment]
Social links are done (in core) and already being used in templates. Any news on the slider? Is that still happening or should we close this issue?

**Comment by iamtakashi** [comment]
> Any news on the slider? Is that still happening or should we close this issue?

I think this design exploration done by @thomasguillot was the latest. pafL3P-oz-p2

cc @davemart-in Is there any plan for building featured content block?

**Comment by davemart-in** [comment]
Not in the grow focus. @artpi and his team are looking into building a premium content block though.

**Comment by artpi** [comment]
Both Premium Content block ( p8hgLy-2ym-p2 ) and Recurring Payments is something we would love to promote in the page templates. (Simple Payments as well, but it's less of a priority for us).

Page templates look like a fantastic way to promote these features.
The caveat is that these are all premium features and there is currently no framework for that.

**Comment by davipontesblog** [comment]
For the slider gap in dotCom now, I suggest you have a look at this plugin here: https://wordpress.org/plugins/block-slider/
It does a really good job of allowing users to simply nest any block combination into a slider parent block, and define options from there, such as timing between slides, arrow styles, etc etc.
It's also featured in the Gutenberg Hub: https://templates.gutenberghub.com/section/slider

**Comment by SiobhyB** [comment]
We also discussed the possibility of [Newspack's Article Carousel block](https://newspack.blog/support/blocks/article-carousel-block/) filling the post slider gap in p7DVsv-8e1-p2#comment-27040.

**Comment by davipontesblog** [comment]
> We also discussed the possibility of Newspack's Article Carousel block filling the post slider gap in p7DVsv-8e1-p2#comment-27040.

Wow, this is great. I think it'd be better for consistency to keep expanding the Newspack library with this additional block in dotCom as opposed to creating something new.

@lancewillett this seems like something that could be implemented with lower effort than creating a new block. The lack of a "featured post slider" in Gutenberg is one of the biggest gaps we have now when comparing classic Premium themes and the new all-in Gutenberg ones. Do you see this as something we could push for?

**Comment by lancewillett** [comment]
@davipontesblog Yes. CC @davemart-in @apeatling @creativecoder for consideration for Grow/Explorers roadmap.

CC @ianstewart for confirmation of post slider as a gap especially as many folks choose a "premium theme" for this exact feature.

**Comment by davemart-in** [comment]
👍 Happy to add it to the list of projects. Note: @amamujee is in the process of prioritizing upcoming projects.

**Comment by lancewillett** [comment]
I believe strongly that "Slider" support is one of the features people first look for when picking a theme or design. Even if they don't need it. 😄 

So having it available might give our halo a bit more shine. (Halo effect: if they have Sliders, they probably have all the other goodies I expect on a WordPress website.)

**Comment by ianstewart** [comment]
>  post slider as a gap especially as many folks choose a "premium theme" for this exact feature

Without question.

**Comment by amamujee** [comment]
How hard is it to pull in the NewsPack Carousel block? I thought we were updating the plugin with Newspack functionality anyway?

**Comment by guicmazeredo** [comment]
I'm happy to see we are gathering efforts to come up with a featured content slider block. Just to let you all know we also discussed using the Cover Block as the bases for this block combined with the slider functionality of blocks like Newspack's Article Carousel and Slideshow here: pb5gDS-8f-p2#comment-366 

What's interesting about using the Cover Block is that it can embed other blocks and that allows users to feature pretty much any kind of content: pages, posts, or, for instance, have a background image with a button linking to an external site.

**Comment by synora** [comment]
@apeatling 👋  Is this issue still worth pursuing or can it be closed?

**Comment by apeatling** [comment]
I'm going to add a new note in our backlog for the slide block, closing this one.
