### ISSUE TITLE
Editor: Static home page displays incorrect link preview in slug editor

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3563]
![Preview](https://cloud.githubusercontent.com/assets/1779930/13323070/b0fffeec-dba5-11e5-9878-e7097c962d7b.png)

__Steps to reproduce:__

Your site must be configured to have a static home page. This can be configured from the Customize option in the sidebar navigation.

1. Navigate to the [Calypso pages list](https://wordpress.com/pages)
2. Click the name of the assigned static home page
3. Note the link preview shown below the title

__Expected Result:__

The link text should read: `https://example.wordpress.com/`

__Actual result:__

The link text reads: `https://home` (where `home` is the slug of the page)

**Comment by hoverduck** [comment]
21Apr16 Bug Scrub

Confirmed this is still an issue:

![image](https://cloud.githubusercontent.com/assets/7233112/14719914/d89b9292-07cc-11e6-8a6b-d6c4ce834464.png)
