### ISSUE TITLE
Sign Up: Site Topics page broken in ie11

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#35634]
In IE11, The site topic page doesn't load, which halts the signup process. Below is a screenshot of the screen, along with the console

#### Steps to reproduce
1. Starting at URL: https://www.wordpress.com/start
2. Fill out contact info
3. Select site type

#### What I expected
I expect to be taken to the page to select a site topic

#### What happened instead
Instead I see a blue background with nothing else on it

#### Browser / OS version
Windows 10/ IE11 (edge seems to work)

#### Screenshot / Video
<img width="565" alt="2019-08-20_1406" src="https://user-images.githubusercontent.com/31110506/63380864-a5edb900-c354-11e9-8c4a-2cec59f73485.png">

#### Context / Source

This was found by IE Canary tests that run daily. I hadn't noticed the failures as I have been focused on other areas, but it has been occurring since August 6th or so.

**Comment by jblz** [comment]
I'd guess this has something to do with running the site preview in an iframe and the [JS polyfills](https://babeljs.io/docs/en/next/babel-polyfill.html) are not present there.

**Comment by jblz** [comment]
The iframe thing was a red herring.  It looks like we're actually not providing a polyfill for Symbol transform as per:

https://github.com/Automattic/wp-calypso/blob/20a8d2f4fd8adeea79b472c56702927c33ae765d/babel.config.js#L17-L18

See #30492

Linked issue in CRA: https://github.com/facebook/create-react-app/pull/5278

**Comment by p-jackson** [comment]
#35638 is a potential fix, spinning up a live branch to test in browserstack.
