### ISSUE TITLE
FSE: Add message when activating an older theme that uses the customizer

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35646]
If the user goes from a template-first full site editing supported theme, back to an older theme that still uses the customizer, we should show them a message.

The message should inform them that they will no longer be able to edit their header and footer in the editor, and will need to use the customizer instead, and point them to the customizer.

Wording TBD.

**Comment by noahtallen** [comment]
@shaunandrews @apeatling Before implementing this, it'd be great to know how this message ought to look!

1. At what point in the customer flow will this be placed? When the user clicks "activate theme" and the theme is not supported?
2. Where will this be positioned? Is it a modal or a notice or something else?
3. What words / icons should go there?

**Comment by vindl** [comment]
> If the user goes from a template-first full site editing supported theme, back to an older theme that still uses the customizer, we should show them a message.

Do we want to show them a confirmation dialog informing them of the consequences before they actually activate unsupported theme, or just show this information after the fact. I'm leaning toward the former, but the wording above might suggest the latter. 

@mattwiebe did we have similar messaging in MVP that we could reuse here?

**Comment by mattwiebe** [comment]
> did we have similar messaging in MVP that we could reuse here?

No. We were considering it if the MVP stayed enabled but never bothered since we turned it off.

**Comment by apeatling** [comment]
Will look at this tomorrow and chat to Shaun about it.

**Comment by apeatling** [comment]
My thought is that we can place the message in this modal after the theme is activated? /cc @shaunandrews 

<img width="651" alt="Screen Shot 2019-09-26 at 9 48 11 AM" src="https://user-images.githubusercontent.com/1464705/65708181-d5be6980-e042-11e9-87a7-f43a4d1424dd.png">

**Comment by shaunandrews** [comment]
Here's a quick mock of what a message in that modal could look like:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/191598/65724542-9e6dae00-e07e-11e9-8f0c-d7955ecf1998.png">

I worry that this might be too late in the flow, and that any wording we put here will be out of context and cause more confusion.

--

Another option would be to place the message in context; Within the editor. Here's a mockup showing how we could use a wp-admin notice at the top of a post/page to help inform customers that they now have to use the customizer to edit their header and footer:

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/191598/65724414-55b5f500-e07e-11e9-8194-92a8d361283e.png">

I'm unsure about having the ability to dismiss, but I do foresee it being annoying after you've seen in a dozen times. It also bring up the question of how you'd get it back if you wanted it.

--

Alternatively, another option to create a "fake block" of sorts that offers similar messaging:

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/191598/65724484-8007b280-e07e-11e9-9a40-0f33b32a9d14.png">

**Comment by apeatling** [comment]
Let's go with the blue in editor message, and make sure when they close it stays hidden from that point on.

**Comment by vindl** [comment]
@apeatling @shaunandrews what do you think about the solution proposed in the above PR, namely showing this confirmation dialog before switching away from FSE theme:

<img width="546" alt="65799932-e3571a80-e13a-11e9-8c86-8d710fa49b29" src="https://user-images.githubusercontent.com/1182160/65883527-860bd500-e397-11e9-9a5b-fa86554933d5.png">

**Comment by apeatling** [comment]
I think this is too aggressive, and contains a lot of jargon that most users will not understand.

I'd like us to punt on this until after the 10% test, and revist once we have that live and before pushing out to a larger percentage of users.

**Comment by ianstewart** [comment]
Somewhat related … 

![image](https://user-images.githubusercontent.com/545779/67896581-a5c72200-fb2a-11e9-85fd-9d7bfe829e48.png)

… I was wondering about just _not_ recommending people go to the customizer immediately after switching a theme. Came to mind most recently when participating in a usability test. Most of the "set up" for any theme is not really "customizer" related with the most recent themes on WP.com. It's all content-related. Definitely true with the all of our "template-first" themes.

**Comment by vindl** [comment]
@apeatling do we still need this after the recent changes to Themes section? (`Show More` button)

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
