### ISSUE TITLE
Checkout: Sometimes, credit card option not visible in mobile view

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#35650]
#### Steps to reproduce
1. In mobile web, add an item to cart and proceed to the checkout page
2. In the payment options dropdown, select PayPal
3. Open the payment options dropdown once again

#### What I expected

I expected to see the credit card option in the dropdown

#### What happened instead

The credit card option was missing.

<img width="478" alt="Screenshot 2019-08-21 at 12 27 51 PM" src="https://user-images.githubusercontent.com/1269602/63410732-9bddc000-c411-11e9-86d6-6fb1438cacf4.png">

To replicate this issue, it is necessary to have enough number of visible payment options so that a dropdown is seen in smaller screen sizes. 

So, when proxied through Europe, I see four visible payment options which are seen in a dropdown in smaller screen sizes. In some smaller screen sizes, the Credit card option disappears as can be seen in the screen recording below. Note in the screen recording video below that iPad view(set via Google Chrome browser tools) does not show the Credit card option in the dropdown, whereas iPad pro and Google Pixel 2 show the option. Resizing the browser window also makes the credit card option disappear.

https://cloudup.com/cBFYYx9RE06

With fewer payment options, the dropdown is not seen and hence this issue does not appear:

<img width="494" alt="Screenshot 2019-08-27 at 4 31 23 PM" src="https://user-images.githubusercontent.com/1269602/63766130-23cb3a80-c8e8-11e9-9325-e01f11469d87.png">

**Comment by anuragbhd** [comment]
Hi @niranjan-uma-shankar. Hope you're well. I've recently started contributing to Calypso. I stumbled upon this issue while looking for first issues to fix. How did you add item to cart? I did that by going to:

**My Sites** → **_my blog_** → **Design** → **Themes** → **Premium** → **Novaro** → **Purchase**

Here's what I saw (iPad view in Chrome DevTools device toolbar):

![calypso localhost_3000_stats_day_anuragbhandari wordpress com(iPad)](https://user-images.githubusercontent.com/1288616/63706441-0c8b3f00-c84d-11e9-8e8b-39328738c77e.png)

**Comment by niranjan-uma-shankar** [comment]
Hi @anuragbhd. I've updated the description with some more details that will hopefully answer your question. The additional details should also help anyone else reading the bug report, so thanks for asking the question!

**Comment by anuragbhd** [comment]
Thanks, Niranjan. The extra details and video certainly help :)

I'll re-check using a European proxy.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
This will be resolved with the Checkout Redesign project. We'll track it there and close once it launches.
