### ISSUE TITLE
FSE: Chrome: Support opening Header and Footer editor on a new tab using Command/Control key

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35665]
When editing a page on a FSE site, using Command (Mac) or Control (Windows) key to open the Header or Footer section **does not work on Google Chrome**.

When editing a page on a FSE site, using Command (Mac) or Control (Windows) key to open the Header or Footer section **works at times on Firefox**.

#### Steps to reproduce 

- Start with a FSE site
- Create a new page at https://wordpress.com/page
- Choose any page template
- Click on the header or footer section
- Hold the Command (Mac) or Control (Windows) key and click on the `Edit header` or `Edit footer` button

#### What is expected 

The header or footer editor opens on a new tab.

#### What happens instead 

When using Google Chrome, it does not work on a new tab. It opens on the same tab.

When using Firefox, it opens on the same tab as well. But, when I refresh the page editor once, and then try the same, the header/footer editor opens on a new tab.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
