### ISSUE TITLE
Editor: Emoji rendering as regular images in Safari Reader Mode

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#35660]
## Issue

When a post in a Simple Site with an emoji is viewed on Safari's reader mode, the emoji is rendered like regular images, blown out of proportion.

## Steps to reproduce

1. Create a post on a simple site with some text and an emoji in the body
2. Open the post on Safari
3. Turn on Reader Mode by going to Safari > View > View Reader Mode

## What I expected

Emoji should be rendered inline with text in their normal size.

## What happened

Emoji was displayed like images inserted in the post

## Screenshot

![Screenshot](https://cld.wthms.co/v5EIQ1+)
Screenshot: https://cld.wthms.co/v5EIQ1

## Tech details

* Tested on Safari/Mojave
* Issue does not happen on self-hosted or Atomic sites
* Issue does not happen on Firefox Reader Mode
* Happens on posts edited with the Classic and Block Editors
 #reallife #dogfooding #livesharing #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

#user-report #2291474-zen

**Comment by arunsathiya** [comment]
Sorry about the wrong label, didn't realise it's about Safari's reader mode and not WordPress.com Reader.

**Comment by arunsathiya** [comment]
I cannot reproduce this anymore. 

| Live post | Reader view |
|------|------|
| <img width="426" alt="Screenshot 2020-05-25 at 16 00 19" src="https://user-images.githubusercontent.com/18581859/82805021-ea3c5580-9ea0-11ea-8d6c-c1349115b3df.png"> | <img width="563" alt="Screenshot 2020-05-25 at 16 00 14" src="https://user-images.githubusercontent.com/18581859/82805025-ec9eaf80-9ea0-11ea-93dc-a1419d43ce1b.png"> | 

@liviopv could you confirm if this is resolved for you as well?
