### ISSUE TITLE
FSE: Update focus state for Site Navigation block to better explain its functionality

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#35669]
We've noticed people getting confused by the lack of interaction available with the current Site Navigation block. To help explain the functionality of this block better, I propose we update the focus state to include some text and a button to add a new page.

![Site Navigation Focused Copy](https://user-images.githubusercontent.com/191598/63456291-95087a80-c41c-11e9-9e6e-58354c47f2d0.png)

**Comment by vindl** [comment]
Closing since the work will be continued in core navigation block.
