### ISSUE TITLE
FSE: Integrate Single-Editor FSE Codebase

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35676]
Matias' and I/O have created a version of Gutenberg that will support full site editing in a single editor instance. We need to integrate this on WordPress.com because it's clearly a superior experience.

Timing is a critical component to this happening. They will first need to break down their work into separate parts so that it can be merged into the main branch of Gutenberg. Once this has happened we can proceed to use this to support a single editor experience on WordPress.com.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
