### ISSUE TITLE
Page Templates: Improve the blog post listing block

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35677]
We have a few open issues for improving the blog listing block.

- [ ] Ability to update "View all posts" link 
 https://github.com/Automattic/wp-calypso/issues/35515
- [ ] Ability to hide author and date in the Blog Posts Listing block https://github.com/Automattic/wp-calypso/issues/35559

**Comment by obenland** [comment]
The blog list block is no longer insertable, now that the Blog Posts block is available.
