### ISSUE TITLE
Full Site Editing: Health Dashboard

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35671]
Are there any performance, stats, or error metrics that we want to monitor? Let's add a home for these in one view. Some good initial candidates would be site launch rate and template population errors.

**Comment by mattwiebe** [comment]
Couple of other ideas off the top of my head

* list of recently launched FSE sites, with screenshots
* pull in some Tracks data, eg "FSE sites that launched" and watch it over time

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.
