### ISSUE TITLE
Import in Signup: Prevent URLs used in tests from being logged

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#35672]
We should update our importing tests to not log URLs used in tests, as they are skewing our reporting.

**Comment by jonathansadowski** [comment]
I think that these logged URLs might actually be as a result of the tests in D26042-code. We should start there first.

![image](https://user-images.githubusercontent.com/363749/63459936-20810c00-c41b-11e9-8532-f66a22b2a6a2.png)

If it's not the tests, I'd wager these would go away naturally once we kill off that old flow that explicitly suggests those URLs.

**Comment by jonathansadowski** [comment]
I'm going to assign this to myself -- but I'll be looking into it in the context of fixing the tests reporting things to logstash :)

**Comment by mattsherman** [comment]
Thanks @jonathansadowski! I agree with your approach (which we discussed during our 1:1, for anybody else wondering).

**Comment by mattsherman** [comment]
Updated the title and description -- if you have any further updates to those, please do so @jonathansadowski.

**Comment by michaeldcain** [comment]
Fixed in attached patch by the talented Mr. Sadowski.
