### ISSUE TITLE
FSE: Roll out to 100% of Template-first Themes

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35679]
Once we have updated the Varia base theme to support FSE (https://github.com/Automattic/wp-calypso/issues/35632), we will need to iterate through every template first theme and confirm each works with full site editing.

We will then need to make sure every theme has a header and footer template that matches what the theme needs, and works with FSE.

Each theme may also need some style adjustments and tweaks in order to support headers and footers.

**Comment by apeatling** [comment]
Because it's hard to find a place for this to fit at the moment, I'm making a note of a follow up issue to look at when this is complete:

https://github.com/Automattic/wp-calypso/issues/32490

**Comment by apeatling** [comment]
Estimates for this work happening here: https://github.com/Automattic/wp-calypso/issues/35792

**Comment by apeatling** [comment]
We need to do a full documentation sweep before the greater rollout happens. For example in our welcome email we have this:

<img width="495" alt="Screen Shot 2019-08-29 at 4 10 53 PM" src="https://user-images.githubusercontent.com/1464705/63982498-97e81880-ca77-11e9-8dab-91670c84b36b.png">

All of which links to incorrect and outdated steps for setting up your website.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
