### ISSUE TITLE
FSE: Improve the Site Title, Site Description, & Navigation blocks to support font size, text, and background colors

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35678]
This functionality is already built in to Gutenberg, update these blocks to support it.

Related task issue: https://github.com/Automattic/wp-calypso/issues/35435

We will need to determine where it makes sense to contribute this work back to core blocks, while in the shorter term allowing this to happen on our own simple blocks.

**Comment by eduardozulian** [comment]
Just to note that it would be great to also have options for bold and italic on all of those!

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
