### ISSUE TITLE
Page Templates: Implement way for themes to pull in templates to the picker via demo sites.

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35675]
Themes will be adding their own page templates that should show up in the picker only if that theme is enabled.

We need to implement support for this.

**Comment by apeatling** [comment]
There is background on what to support, and how to support it in this comment in this thread: paAmJe-EG#comment-1747

This graphic is also helpful:

![global-local-templates](https://user-images.githubusercontent.com/1464705/63462459-da727b00-c40f-11e9-9163-09cac925ca08.png)

**Comment by obenland** [comment]
This is currently implemented through the `auto-loading-homepage` theme tag.
