### ISSUE TITLE
Broken link on the calypso documentation

### ISSUE THREAD

**Issue by mayeaux** [Automattic/wp-calypso#35690]
Going here: https://wpcalypso.wordpress.com/devdocs/design

![Screen Shot 2019-08-21 at 9 04 08 PM](https://user-images.githubusercontent.com/7200471/63482746-40362580-c457-11e9-8ff3-d392766eb844.png)

That 'component documentation' link points to: 
https://wpcalypso.wordpress.com/docs/components.md

Which is a dead link. Thanks.

**Comment by simison** [comment]
cc @Automattic/team-calypso
