### ISSUE TITLE
Hello world guide fails  (https://wpcalypso.wordpress.com/devdocs/docs/guide/hello-world.md)

### ISSUE THREAD

**Issue by mayeaux** [Automattic/wp-calypso#35691]
Following the steps listed here: https://wpcalypso.wordpress.com/devdocs/docs/guide/hello-world.md

![Screen Shot 2019-08-21 at 9 21 16 PM](https://user-images.githubusercontent.com/7200471/63483439-a15ef880-c459-11e9-97de-cb5600b8b32e.png)

This steps errors because `config` is undefined in `sections.js`

Also, the example doesn't work in general, besides erroring out here. This is just the most obvious way to show that the docs don't work. A little bit nervous about trying to do a project on top of calypso given the sparse (and broken) documentation.

**Comment by simison** [comment]
cc @Automattic/team-calypso

**Comment by anuragbhd** [comment]
Hi @mayeaux. This can be fixed with a simple `require` at the top:

```javascript
/**
 * Internal dependencies
 */
const config = require( 'config' );
```

I am a total newbie to Calypso and feel the docs are still mostly decent. You noticed something extra concerning?

**Comment by jsnajdr** [comment]
Hi @mayeaux, thank you for your feedback! I improved the Hello World guide a bit in #35779.

Please let us know if you have any other feedback about the Calypso onboarding experience.

**Comment by jsnajdr** [comment]
> something I felt would be very easy to do and well documented would be to add something to the sidebar on Calypso.

Yes, adding new things to sidebar is not straightforward and poorly documented.

To begin with, there are three sidebars in Calypso:
- My Sites, in `client/my-sites/sidebar`, for items that are related to a particular site
- Me, in `client/me/sidebar`, for items related to the user's account
- Reader, in `client/reader/sidebar`, for Reader

In My Sites, there's also an "All Sites" view, which shows and overview of all sites. Some views support that, some don't. The sidebar item is then visible or hidden, respectively.

Sidebar items can also change depending on user permissions, the site's plan, the site's type (Simple, Jetpack, Atomic, ...) etc.

Our sidebar code is currently in state of heavy refactoring. We can document it better after things settle down a bit.
