### ISSUE TITLE
--redacted-- podcast downloads are missing from Stats page

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#35694]
--redacted--

#### Steps to reproduce
1. Log in with Customer's account
2. Go to https://wordpress.com/stats/day/interludecancerstories.com

#### What I expected
File downloads information is visible

#### What happened instead
Downloads information is missing

#### Browser / OS version
Chrome on MacOS

#### Screenshot / Video

--redacted--

#### Context / Source

#2292606-zen

**Comment by arunsathiya** [comment]
Moved - p1566474431099900-slack-triage
