### ISSUE TITLE
Jetpack Site Video Stats Don't Appear on WordPress.com Dashboard

### ISSUE THREAD

**Issue by pmciano** [Automattic/wp-calypso#35703]
A user is no longer able to view stats for videos through their WordPress.com dashboard. Their WP Admin dashboard shows very limited stats. (see [related issue for screenshots and site diagnostic information](https://github.com/Automattic/jpop-issues/issues/4245)).

Issue has been replicated by several HEs and does not appear to be related to a plugin conflict.

We confirmed the following:

```
Hmm... they can see it here but

https://wordpress.com/stats/month/videoplays/www.trec.org?startDate=2019-08-01

But I can comfirm "Video" section does not display in:

https://wordpress.com/stats/day/www.trec.org
https://wordpress.com/stats/month/www.trec.org
or https://wordpress.com/stats/year/www.trec.org
I can replicate a similar issue on my own testing site.
```

The issue appears to be restricted to Jetpack sites.

- Ticket: 2271607-zen
- [Related Issue](https://github.com/Automattic/jpop-issues/issues/4245)

**Comment by bluefuton** [comment]
@tmmbecker it looks like the video stats module has always been hidden in the Site view for Jetpack sites. Here's the file recently before we started work on File Download Stats:

https://github.com/Automattic/wp-calypso/blob/fc4269b03d42d25637fcf0cc8cb6b5ae43294d17/client/my-sites/stats/site.jsx#L138

If video play stats are now officially supported in Jetpack, I'd be happy to work up a PR to show that module on the Site view.

**Comment by arunsathiya** [comment]
I was about to say the same as @bluefuton. I had tested this yesterday as well, and it looks like video stats are now supported:

<img width="1103" alt="Screenshot 2019-08-28 at 07 19 40" src="https://user-images.githubusercontent.com/18581859/63819793-400cbd00-c964-11e9-93e6-fe411c6973c3.png">

Maybe that also explains why stats are available on certain links like this one:

https://wordpress.com/stats/month/videoplays/www.trec.org?startDate=2019-08-01

I have a patch to review here - https://github.com/Automattic/wp-calypso/pull/35829

**Comment by bluefuton** [comment]
Thanks for the PR @arunsathiya! There is a Video Plays module appearing in Jetpack Site Stats now (`/wp-admin/admin.php?page=stats`), so I think we're safe to add it in Calypso:

<img width="523" alt="Screen Shot 2019-08-28 at 14 05 32" src="https://user-images.githubusercontent.com/17325/63820352-04421980-c99d-11e9-886b-50d5c84f51d4.png">
