### ISSUE TITLE
Full Site Editing: populate templates from the respective theme demo site [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35708]
From changes in https://github.com/Automattic/wp-calypso/pull/35698 and D31833-code

Varia and Maywood are using the Modern Business demosite to back the `https://public-api.wordpress.com/wpcom/v2/full-site-editing/templates` response for those theme slugs.

We should be populating the response from the Varia and Maywood demosites respectively when given those theme slugs.

At a minimum, we need to:
- [x] Update the respective demosites to add expected header/footer templates
- [x] Add a fse sticker to the demosite
- [x] Update the API mapping
- [x] Verify that there aren't any other hardcoded areas pointing to Modern Business in code.
- [ ] Verify that Shawburn's header/footer look like the default demo.
- [ ] Verify that Exford's header/footer look like the default demo.

See also paAmJe-Gy-p2 for why we need this on the demosite.

**Comment by Copons** [comment]
If the plan is to have FSE support on several Varia children themes, what about having only 1 demo site for Varia, and let the children themes inherit that?

**Comment by Copons** [comment]
I've got one doubt about this: we talk about the theme demo site, but I think that's kind of incorrect.

For example, the Modern Business actual demo site (that we use for example on https://wordpress.com/theme/modern-business) is https://modernbusinessdemo.wordpress.com/, while the _"demo site"_ that contains the templates data is https://fsemodernbusinessdemo.wordpress.com/.

So, in the case of Varia for example, the demo site is https://variademo.wordpress.com/, but I guess we will need to create a new site called `fsevariademo.wordpress.com`, and use that for the templates data.

**Comment by gwwar** [comment]
> If the plan is to have FSE support on several Varia children themes, what about having only 1 demo site for Varia, and let the children themes inherit that?

I'll defer to @iamtakashi for preferences, but we previously noted one per theme.

**Comment by iamtakashi** [comment]
> I'll defer to @iamtakashi for preferences, but we previously noted one per theme.

I'd prefer each theme having a demo site that acts as a single source of truth for this purpose as well. Minimising irregularity unless that's absolutely necessary would be helpful for us.

**Comment by noahtallen** [comment]
Closing this out since we do have a working solution now.
