### ISSUE TITLE
Busy button animation not visible on "Contrast" color scheme

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35726]
When using the `Contrast` color scheme (available on https://wordpress.com/me/account), the busy button animation is not visible. Can be seen when trying to import on https://wordpress.com/import 

<img width="784" alt="Screenshot 2019-08-23 at 14 25 57" src="https://user-images.githubusercontent.com/18581859/63580591-cadf6780-c5b2-11e9-9f98-d70b4e3ad4c7.png">

**Comment by arunsathiya** [comment]
I have confirmed that the busy button animation looks fine on all other color schemes.

**Comment by Aurorum** [comment]
I can't reproduce this, is this still occurring?

<img width="691" alt="Screenshot 2019-11-08 at 21 00 56" src="https://user-images.githubusercontent.com/43215253/68510260-e893a300-026a-11ea-90e2-37c978697cd0.png">

**Comment by arunsathiya** [comment]
Thanks! It seems to be resolved indeed. ✅
