### ISSUE TITLE
GA: Update support documentation

### ISSUE THREAD

**Issue by huguesvincent** [Automattic/wp-calypso#35739]
- [ ] https://en.support.wordpress.com/google-analytics/ - "available as a feature of the WordPress.com Business plan" & "is part of the WordPress.com Business plan"
- [ ] https://en.support.wordpress.com/traffic/ - "upgrade to the WordPress.com Business plan" & this graphic: https://cl.ly/6dfd607fdba7
- [ ] https://en.support.wordpress.com/google-integration/ - "upgrading to the Business upgrade"

**Comment by supernovia** [comment]
I can help with this when we're ready

**Comment by huguesvincent** [comment]
Sounds good Velda! Thanks a ton!

**Comment by creativecoder** [comment]
I've updated the support page urls to include those listed in #36367

**Comment by huguesvincent** [comment]
Updated on all three pages.
