### ISSUE TITLE
GA: Make GA available to Premium plans

### ISSUE THREAD

**Issue by huguesvincent** [Automattic/wp-calypso#35737]
Work already advanced by Robert here: https://github.com/Automattic/wp-calypso/pull/32478

Need to be adjusted to Premium plans and not all paid plans as built by Robert so far. 

Listing bits and pieces, that need updating:

- [ ] The support docs - https://en.support.wordpress.com/google-analytics/
- [ ] The plan features - https://wordpress.com/pricing/
- [ ] Update the API to ensure the plugin is enabled - It looks like the setting is saved for all sites, but the plugin is only enabled on Business plans

**Comment by creativecoder** [comment]
I've updated the description to include the support page urls listed in #36367
