### ISSUE TITLE
Importer: Decode characters before rendering the author name

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35730]
Certain characters like `&` in the author name appear as `&amp;`. They should be decoded before rendering.
<img width="780" alt="Screenshot 2019-08-23 at 17 48 50" src="https://user-images.githubusercontent.com/18581859/63592365-0be57500-c5cf-11e9-9a33-686f3a66a8c3.png">

**Comment by Aurorum** [comment]
PR in #35734 :)
