### ISSUE TITLE
Importer: Handle longer author names better

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35731]
We should find a better way to display super long author names like the one below:

<img width="784" alt="Screenshot 2019-08-23 at 17 49 46" src="https://user-images.githubusercontent.com/18581859/63592380-199afa80-c5cf-11e9-8ab6-7e1ea31ce7dd.png">

It should not overflow the available space.

The name is set on the `Public display name` section of https://wordpress.com/me/account

<img width="747" alt="Screenshot 2019-08-23 at 17 53 00" src="https://user-images.githubusercontent.com/18581859/63592381-199afa80-c5cf-11e9-9e25-32b5f3de60de.png">

Noticed when reporting https://github.com/Automattic/wp-calypso/issues/35730

**Comment by Aurorum** [comment]
PR in #35733 to offer one potential solution to this issue by using `text-overflow: ellipses.` :)

<img width="1029" alt="Screenshot 2019-08-23 at 14 00 48" src="https://user-images.githubusercontent.com/43215253/63594623-da5cb180-c5ae-11e9-9eaa-1880cd280af6.png">
