### ISSUE TITLE
(?P) Add prop type declarations to all React Components

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#35732]
Currently finding missing props make components less than resilient and difficult to reason about.

Todo

- [ ] Ensure default props provided where appropriate
- [ ] All prop type declarations (especially focus on where it adds value to define the "shape" of the props for more complex props)

**Comment by getdave** [comment]
Looks like Gutenberg Core doesn't want to pursue this approach

https://wordpress.slack.com/archives/C02QB2JS7/p1564515199397200

**Comment by getdave** [comment]
Also https://medium.com/javascript-scene/you-might-not-need-typescript-or-static-types-aa7cb670a77b

**Comment by marekhrabe** [comment]
Should we close then?

**Comment by getdave** [comment]
I think we close in favour of good JSDocs, type checking and (possibly) TypeScript.
