### ISSUE TITLE
Compiling Calypso into executable installers for different operating systems

### ISSUE THREAD

**Issue by mayeaux** [Automattic/wp-calypso#35748]
Hi there, 
I was wondering if it is possible to compile Calypso into an executable installer for the Windows and OS X operating system. I was looking to build custom functionality into a Calypso client but wouldn't necessarily want the end user to have to understand how to install and run node, git, etc to be able to use it.

Is this possible? I know that Automattic has installers for vanilla Calypso. Thanks!

**Comment by griffbrad** [comment]
@mayeaux Thanks for reaching out!  To pull this off, you'd essentially be building a customized version of the wp-desktop app (https://github.com/automattic/wp-desktop) against your version of Calypso.  The project's README includes info both on running the Electron-based app in development and creating a release build.  Hope that helps! 😄
