### ISSUE TITLE
(?P) Update Plugin dir structure to better separate src and built files

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#35746]
When it comes to running linters we need to be able to point at the unbuilt "source" files for the Plugin. However, our JS source files are mixed with PHP files. In JS land we need source files to be discint from built files and they should be in their own `src` dir.

**Comment by lancewillett** [comment]
Sounds like a question for @Automattic/team-calypso?

**Comment by jsnajdr** [comment]
I'm afraid I miss some context: what's `(?P)` and which plugin is The Plugin?

**Comment by obenland** [comment]
We won't continue to iterate on the page template modal. Let's close this for now. Happy to pick it back up if/when we continue work on the modal.
