### ISSUE TITLE
GA: Update Marketing pages (pricing grids, Plans ...)

### ISSUE THREAD

**Issue by huguesvincent** [Automattic/wp-calypso#35740]
- [ ] https://en.blog.wordpress.com/2015/01/29/google-analytics-for-wordpress-com-business-sites/ (We might add an update to the top of this post)
- [ ] https://wordpress.com/go/digital-marketing/analyzing-organic-traffic-using-google-analytics/
- [ ] https://wordpress.com/google/analytics/ - Mentions "is included as part of WordPress.com Business"
- [ ] https://wordpress.com/ - "design, Google Analytics, and" under business plans description
- [ ] https://wordpress.com/pricing/ - "design, Google Analytics, and" & "Google Analytics Integration" feature row
- [ ] https://wordpress.com/install-plugins/ - "concierge support, Google Analytics, and" under business plan description
- [ ] https://wordpress.com/premium/
- [ ] https://wordpress.com/create-blog/
- [ ] https://wordpress.com/easy/
- [ ] https://wordpress.com/create-website/
- [ ] https://wordpress.com/built-for-business/
- [ ] https://wordpress.com/business-everywhere/
- [ ] https://wordpress.com/brand-everywhere/
- [ ] https://wordpress.com/creativity-everywhere/
- [ ] https://wordpress.com/everywhere/
- [ ] https://wordpress.com/resolutions/

**Comment by creativecoder** [comment]
I updated the description to include all the marketing page urls mentioned in #36367
