### ISSUE TITLE
No Stackoverflow community for wp-calypso

### ISSUE THREAD

**Issue by mayeaux** [Automattic/wp-calypso#35749]
Hey guys, am I not looking in the right place for the SO community for wp-calypso? 

https://stackoverflow.com/search?q=calypso

https://stackoverflow.com/search?tab=newest&q=wp-calypso

These both look like ghost towns. Does the project encourage people to bring their questions/issues to this Github repo as opposed to Stackoverflow? Thanks

**Comment by kriskarkoski** [comment]
@mayeaux Sorry for the delay, I just found your question while doing a bug scrub. I am not aware of an active community around wp-calypso outside of Github but you are welcome to ask questions here. Cheers!
