### ISSUE TITLE
Domains: Office 365 no longer supported

### ISSUE THREAD

**Issue by sarahfg** [Automattic/wp-calypso#35760]
Office 365 no longer supports adding a custom domain to email, unless that custom domain is registered through GoDaddy.

https://support.office.com/en-gb/article/get-a-personalized-email-address-in-office-365-75416a58-b225-4c02-8c07-8979403b427b

It looks like we'll need to remove the button to add the TXT verification on the domain's DNS page:

![](https://cld.wthms.co/RxD9SB+)
(Image link: https://cld.wthms.co/RxD9SB )

I've also noted that our support document is outdated and switched it to a draft 
https://github.com/Automattic/en.support-docs-content/issues/430

**Comment by separatelyunited** [comment]
It appears that may only be for Outlook.com (or Microsoft has odd inconsistencies in their updated documentation).

I found this doc from Microsoft 365: https://docs.microsoft.com/en-us/office365/admin/setup/add-domain?view=o365-worldwide

And also their general instructions for multiple registrars: https://docs.microsoft.com/en-us/office365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide

For now, I am going to re-publish our support doc, but if we find that our process is indeed deprecated, let us know here: [Connect with Office 365 support doc](https://github.com/Automattic/en.support-docs-content/issues/430)
