### ISSUE TITLE
Contact Form Block: Re-opening page in editor resets any color changes.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#35761]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page
2. Add a Contact Form Block.
3. Click the "Add Form" button.
4. Click on the submit button.
5. In the block settings, under "Button Color Settings" change the background and/or text color to anything you like.
6. Publish the page.
7. Exit the editor.
8. View published page, colors are correct.
9. Re-open same page in editor. Preview page, or click "Add form" to check the form settings again. Colors have now reset.

#### What I expected
Contact Form color adjustments should persist even if you edit the same page again.

#### What happened instead
Any sort of editing resets the color settings.

Even if all you do is open the page in the editor, and avoid touching the Contact Form Block at all, once make any sort of change whatsoever and then click "Update" the colors will have now reset.

#### Browser / OS version
Chrome OS Version 76.0.3809.102 (Official Build) (64-bit)

#### Context / Source

Reported in #zen-2299822 but I was able to repro on my own site. Issue occurs on both simple sites and atomic sites.

**Comment by chaitanyamsv** [comment]
User confused and reported in 15868019-hc

**Comment by katiebethbrown** [comment]
This seems to be happening to more than the form block.

Reported in #6333717-hc as well, but in relation to the background color of the button block. 

The color in the sidebar shows that the correct color is set, but the button appears as black in the editor.

<img src="https://cdn-std.droplr.net/files/acc_680347/Y9hrZ4">

**Comment by andreabadgley** [comment]
Another user has the issue in the Forms block in 17638443-hc. Provided CSS workaround.
