### ISSUE TITLE
CoBlocks: No hero heading, content and button sections after adding a Hero block

### ISSUE THREAD

**Issue by reginabally** [Automattic/wp-calypso#35764]
#### Steps to reproduce
1. Add the Hero block to a page or post
2. No hero heading, content and button sections can be seen
3. Add a background image, the content sections are still not showing
4. Save the changes and exit page or post editor
5. Go back to the page/post, the content sections can be seen now.

#### What I expected

The content sections should be showing when the Hero block is added.

#### What happened instead

No hero heading, content and button sections can be seen after adding the Hero block.

#### Browser / OS version

Firefox 68.0.2 | Mac OS 10.14

#### Screenshot / Video

I've recorded a screencast here: https://cld.wthms.co/UQxxTr

#### Context / Source

#user-report

2300472-zen

**Comment by kwight** [comment]
Recent updates must have taken care of this, I can't replicate at all (in Chrome nor Firefox). Closing, @reginabally let us know if the user is still having issues 👍
