### ISSUE TITLE
Cover Block: Making any change to focal point results in block error.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#35762]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/
2. Add a Cover Block.
3. Select an image for the Cover Block.
4. In the Cover Block settings, adjust the focal point. You can type it in or drag the dot, it doesn't matter.
5. Publish page.
6. Exit editor.
7. Re-open the same page in the editor. Block now says "This block contains unexpected or invalid content."

#### What I expected
To not see any sort of error on the cover block.

#### What happened instead
If you refresh the page, exit the editor and re-open the page, any change to the focal point even by a single % results in "This block contains unexpected or invalid content."

#### Browser / OS version
Chrome OS Version 76.0.3809.102 (Official Build) (64-bit)

#### Context / Source

zen-2299822

Also seems similar to https://github.com/Automattic/wp-calypso/issues/34944

If the value for the focal point is anything except 50% and 50%, you'll see an error the next time you edit the page.

Affects both simple and atomic.

**Comment by kwight** [comment]
I can replicate this, including in 6.4 (production is currently at 6.2).

The failing validation makes sense, with what comes back from the db:

> Block validation: Expected attribute `style` of value `background-image:url(https://kwighttest.files.wordpress.com/2015/09/sad_puppy.jpg);background-position:0% 0%`, saw `background-image:url('https://kwighttest.files.wordpress.com/2015/09/sad_puppy.jpg');background-position:0 0;`

`background-position`s are stripped of their percent signs.

> Block validation: Expected attribute `class` of value `wp-block-cover-image has-background-dim wp-block-cover`, saw `wp-block-cover has-background-dim`.

Classes don't match.

<img width="930" alt="Screen Shot 2019-09-05 at 1 53 48 PM" src="https://user-images.githubusercontent.com/349751/64380051-13e8e000-cfe5-11e9-9d57-ee7be0b1a1ec.png">

`sections`s replaced by `div`s, and other oddness.

**Comment by kwight** [comment]
Any fix produced for this should also verify it against the CoBlocks Hero block, as mentioned in #34944 .

**Comment by brookewp** [comment]
Ran into this exact issue with another customer in this chat: hc-15203959

**Comment by kriskarkoski** [comment]
Another report in 2392376-zen

**Comment by rickmgithub** [comment]
I think this sounds like the same issue with the cover block although they are not adjusting the focal point. All they do is save the page and come back to edit it again and it now says "invalid content"

13127959-hc
2428388-zen

**Comment by formosattic** [comment]
+1, in 2422924-zen

**Comment by catrymer** [comment]
+1 in 16213388-hc

**Comment by ktyfuller604** [comment]
Another report - #16763142-hc

**Comment by carinapilar** [comment]
+1 in 16999148-hc

**Comment by cecilearkay** [comment]
Same in 2872573-zd

**Comment by WunderBart** [comment]
This issue has been fixed with the recent CoBlocks update (https://github.com/Automattic/wp-calypso/issues/45033).
