### ISSUE TITLE
Posts: Inconsistent tab ordering for post statuses

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#35785]
While switching from one site to another in order to work on some draft posts I discovered that the ordering of the selector tabs for _Published_ and _Drafts_ is inconsistent.

<img width="829" alt="Screen Shot 2019-08-26 at 12 31 41 PM" src="https://user-images.githubusercontent.com/5431237/63710022-c490fb80-c7fd-11e9-98cb-fd90f717e226.png">

<img width="833" alt="Screen Shot 2019-08-26 at 12 31 52 PM" src="https://user-images.githubusercontent.com/5431237/63710033-c8bd1900-c7fd-11e9-99a5-47d036a53e93.png">

Although this isn't too disruptive it's odd and unexpected and probably unintentional. I would expect the ordering to be consistent.

**Comment by anuragbhd** [comment]
@dmsnell Perhaps I am missing the context but I'm unable to replicate this. I tried switching across 3 different sites (2 on wordpress.com and 1 self-hosted). Could you share more steps to reproduce this?

<img width="652" alt="Screen Shot 2019-08-27 at 8 14 19 PM" src="https://user-images.githubusercontent.com/1288616/63781385-520c4280-c907-11e9-98ca-b9f440fb6826.png">

<img width="652" alt="Screen Shot 2019-08-27 at 8 14 25 PM" src="https://user-images.githubusercontent.com/1288616/63781391-546e9c80-c907-11e9-8f7d-1d7efbf4b7f9.png">

<img width="652" alt="Screen Shot 2019-08-27 at 8 14 30 PM" src="https://user-images.githubusercontent.com/1288616/63781402-589aba00-c907-11e9-9d5b-f588f2ee28b4.png">
