### ISSUE TITLE
Full Site Editing: move theme whitelist checks 

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35794]
To help with scaling, we should be able to dynamically mark that a new theme is ready for FSE, without updating committed code whitelists.

As just one example here's a committed array. There are more in various areas, so please do a usage search.
https://github.com/Automattic/wp-calypso/blob/6cf687c54a1512ecb41006732685be94f4a331bc/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L47-L51

Let's update that into reading from the theme (for standalone sites) or from our wpcom theme API. 

The idea being that folks who create a new Themes that support FSE flows, can do so by themselves without contacting Edit teams for assistance.

@kwight suggested that we might use https://developer.wordpress.org/reference/functions/add_theme_support/ and https://developer.wordpress.org/reference/functions/get_theme_support/ for this purpose
in paYKcK-eB-p2

cc @iamtakashi  on preferences.

**Comment by glendaviesnz** [comment]
A quick test seems to indicate that it is possible to add a method to the themes functions.php file that we could use for this, eg.

```php
function maywood_fse_enabled() {
    return true;
}
```

Then in the FSE plugin, as long as we are checking in a place where the theme has already loaded we can do something like:

```php
        $theme_fse_check = "\\" . $theme_slug . "_fse_enabled";
        if(function_exists( $theme_fse_check ) && $theme_fse_check() === true) {
            \\ Looks like this theme is FSE enabled
        }
```

**Comment by gwwar** [comment]
Updating summary to note Kirk's suggestion of https://developer.wordpress.org/reference/functions/add_theme_support/

**Comment by iamtakashi** [comment]
> cc @iamtakashi on preferences.

I'm not fully aware of the pros and the cons of each, but `add_theme_support` has historically often been used to enable a feature in a theme, and I'd say themes are familiar with it.

**Comment by noahtallen** [comment]
We should update the function here as needed: https://github.com/Automattic/wp-calypso/blob/023d7357a25c4b0ff7d5944114c4415073419917/apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php#L120-L122

This will make sure all of the API continue working as expected without modifications.
