### ISSUE TITLE
Framework: pages placeholder glitch when offline

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#358]
To reproduce:

1. Visit http://calypso.localhost:3000/ or load the Desktop app
2. Lose your internet connection (or turn off your wifi)
3. Visit http://calypso.localhost:3000/pages/example.wordpress.com (click on the Pages sidebar link)
4. Note the crazy flashing between the Pages placeholder and the `EmptyContent` message

https://cloudup.com/c0B4gJZHOxI

Note that /posts simply displays the `EmptyContent` message when there is no connectivity. We should standardize how we handle situations when we can't fetch data (no connection) as opposed to having no data to fetch. It could be disconcerting to see the `EmptyContent` message when using the Desktop app—a user could assume their posts or pages were deleted.

**Comment by gwwar** [comment]
@rralian @rickybanister is this still an issue? I wasn't able to reproduce the issue on production. 
I think it would be nice to also add a disconnected notice somewhere on the page, I'm currently seeing loading placeholders pulsing forever when disconnected.

**Comment by rralian** [comment]
Yep, definitely still an issue. See video: https://cloudup.com/cbX1saGeMDt

**Comment by gwwar** [comment]
Thanks for the vid!
