### ISSUE TITLE
Full Site Editing: Mode Switch Challenges

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35802]
We observed some folks moving from editing a header or footer to their original page fluidly and easily. Moving from page to page was a challenge. 

Explore a clearer method to move between existing pages or back to the list of pages. The current X in the far left is missed and/or ignored as a control.

See paAmJe-JF-p2 for context

**Comment by vindl** [comment]
We are no longer working on Dotcom FSE since it will be replaced with core's version.
