### ISSUE TITLE
Cover Block: Fixed Background setting doesn't work on mobile

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#35800]
#### Steps to reproduce
1. Create a new post/page.
2. Add the Cover block on it.
3. Select an image in the block.
4. Enable the "Fixed Background" option under Cover Settings.

#### What I expected
For the Fixed Background behavior to work anywhere. As it does on desktop:

![CoverBlock](https://user-images.githubusercontent.com/16104522/63729047-50297d00-c83c-11e9-89c0-6c75f7a72545.gif)

#### What happened instead
The Fixed Background behavior doesn't work on mobile:

![CoverBlockMobile](https://user-images.githubusercontent.com/16104522/63729368-5ec46400-c83d-11e9-9b7d-2ad7da6f89c2.gif)

#### Browser / OS version
Tested on Chrome and Safari on an iPhone XS with iOs 12.4.

#### Context / Source
#user-report

**Comment by nickpagz** [comment]
Another report here:
#17652379-hc

**Comment by philnick206** [comment]
Another report here:
#19135543-hc

**Comment by ChrissiePollock** [comment]
The person from #19135543-hc added 

> I have noticed that it is not working on the tablet view either. And in fact, on the tablet view, it is distorting the photo, enlarging it that the photo is not even viewable.

**Comment by formosattic** [comment]
+1 on iPhone 11, 21599085-hc

**Comment by katiebethbrown** [comment]
Another report in 22161129-hc.

Cover blocks in iPad are not showing the fixed background and the image is distorted.

**Comment by lizswafford** [comment]
22823186-hc

Request for Parallax scrolling effect on iOS devices.

**Comment by aleone89** [comment]
25449616-hc

Another request made here.

**Comment by philnick206** [comment]
Another report here: #3504081-zen

**Comment by Agepeuve** [comment]
One more report in HC-26079990/zen-3540859

**Comment by sstabrizi** [comment]
Another report here: #26961092-hc

**Comment by MaxPhilip** [comment]
Another report: 3758720-ZD

Firefox 68.11.0 on Samsung works. Chrome does not.

**Comment by zdenys** [comment]
Another case 28154596-hc.

**Comment by mpmedialab** [comment]
One more report → #3792547-zen

**Comment by ivan-ottinger** [comment]
Another report (iPad Pro): 3864419-zd-woothemes

**Comment by aleone89** [comment]
Another report here: hc-30499569
 iPhone XR
 iOS 14.6
 Safari 14

**Comment by inaikem** [comment]
Another report in 23213008-hc + follow-up in 4132861-zen.

**Comment by marcuswisecaesar** [comment]
User reported this here and asked for an update: hc-30672648
iPhone XR
iOS 14.6
Chrome 84.0.4147.71

**Comment by renata-franco** [comment]
Another one: 4248299-zd-woothemes

**Comment by cuemarie** [comment]
Another report of this here: 31923276-hc
User is using Safari on an iPhone 7, and I can replicate the issue on Safari 14.1 on iOS 14.7

**Comment by cuemarie** [comment]
Has anyone been able to offer any workarounds for this issue?

**Comment by Robertght** [comment]
This is a core issue(https://github.com/WordPress/gutenberg/issues/17718) and it looks like there's some progress(https://github.com/WordPress/gutenberg/pull/32824) but it's not merged yet.

**Comment by ccwalburn** [comment]
Another report 29090034-hc
I can replicate it on both Safari and Chrome on my iPhone

**Comment by desnum** [comment]
The cover block background remains fixed on an Android phone, but I can confirm that it loses that parallax effect on an iPhone. This was brought up by a user in 38181454-hc.

**Comment by cometgrrl** [comment]
The linked core issues were completed and closed in 2021.

**Comment by carinapilar** [comment]
@cometgrrl, the original issue doesn't seem to be fixed, so I'm not sure I understood why this was closed. I tested again and can still replicate it on an iPhone. Should we change this thread to a feature request for the Parallax scrolling effect on mobile?

**Comment by cometgrrl** [comment]
@carinapilar Sorry for the confusion. Looking at the linked core issues, it looks like this was actually not fixed by the linked issues. However, [Disable fixed cover attachment on iOS](https://github.com/WordPress/gutenberg/pull/11480#top) indicates that this feature is not supported in Safari on iOS.

I removed the `closed fixed` label, however, I'm not sure what to do with it next since it seems that it's a limitation of iOS/Safari. So either by design or won't fix might make more sense?

**Comment by carinapilar** [comment]
Ah, yes, that makes sense @cometgrrl! I think `won't fix` sounds like a good fit. Thanks!
