### ISSUE TITLE
Full Site Editing: Mental Model and Expectations

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35801]
The mental model for header and footer worked well, but in some cases similar outside models like MS Word brings over expectations of functionality we don’t support. It’s worth exploring what functionality is resident in the editing space vs. the toolbar above.

See paAmJe-JF-p2 for context

**Comment by vindl** [comment]
We are no longer working on Dotcom FSE since it will be replaced with core's version.
