### ISSUE TITLE
Gutenberg: Opt-out missing on help icon

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35817]
With an older user, on a non FSE site, I noticed that the "Switch to Classic" button is missing in the help area. There's still an option on the more menu in the Editor.

<img width="668" alt="Screen Shot 2019-08-27 at 10 50 24 AM" src="https://user-images.githubusercontent.com/1270189/63795342-9d4b3480-c8b8-11e9-90af-9b90ce1637bd.png">

Expected:
<img width="368" alt="screen-shot-2019-07-08-at-11 34 58-am" src="https://user-images.githubusercontent.com/1270189/63795461-d08dc380-c8b8-11e9-9edf-33efc59f3d4b.png">

**Comment by kwight** [comment]
This has been fixed somewhere along the way, no longer an issue.

**Comment by noahtallen** [comment]
yay, cleaning up code resolved an old issue!
