### ISSUE TITLE
FSE: Long non-breaking page title doesn't look good on navigation menu

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35827]
For a page with a long, non-breaking title like `Super/Duper/Long/NonBreaking/Path/Name/To/A/File/That/Is/Way/Deep/Down/In/Some/Mysterious/Remote/Desolate/Part/Of/The/Operating/System/To/A/File/That/Just/So/Happens/To/Be/Strangely/Named/.txt` does not look good on the navigation menu. 

It overflows the available screen space to the right.

![Screenshot 2019-08-28 at 06 53 03](https://user-images.githubusercontent.com/18581859/63818877-ae4f8080-c960-11e9-95b0-854fb043156f.png)

Specific header view with the navigation menu:

<img width="1920" alt="Screenshot 2019-08-28 at 06 52 47" src="https://user-images.githubusercontent.com/18581859/63818893-bad3d900-c960-11e9-8d3a-2fc0afd56f00.png">

Specific footer view with the navigation menu:

<img width="1920" alt="Screenshot 2019-08-28 at 06 52 51" src="https://user-images.githubusercontent.com/18581859/63818897-bc9d9c80-c960-11e9-8657-eaba6c7d1d8b.png">

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
