### ISSUE TITLE
Plugins: Auto update and active toggle visual jump

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#35838]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plugins/manage/[siteurl]
2. Use the toggle switches on plugins

#### What I expected

1. For there to be one method of feedback that doesn't cause a jerky UI

#### What happened instead

![Aug-28-2019 14-56-25](https://user-images.githubusercontent.com/411945/63862356-59cdf480-c9a4-11e9-970e-837e58076384.gif)

#### Browser / OS version

Chrome 76 on Mac OS X 10.14.6

#### Context / Source
#manual-testing

**Comment by scottsweb** [comment]
Just to note there is a duplicate notification at the top of the screen during this process
 
![Screenshot 2019-08-28 at 15 12 32](https://user-images.githubusercontent.com/411945/63870167-555c0880-c9b1-11e9-98c3-fdf332c26dfa.png)

so we can probably remove the ones in the first GIF?

**Comment by davipontesblog** [comment]
Auto-update toggle has been disabled in WordPress.com sites now.
