### ISSUE TITLE
Simple Payments: add image variation

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#35845]
Recently, Gutenberg included an option to [change the look of an image block](https://github.com/WordPress/gutenberg/pull/16475). One could change the image from its original form to a circle crop.

This is a request to transport this functionality, if possible, also to the Simple Payments block.

#### Screenshot / Video

Example:

<img width="802" alt="Captura de Tela 2019-08-28 às 14 46 13" src="https://user-images.githubusercontent.com/1136160/63879727-a7e1f880-c9a2-11e9-9748-5b1408839f9c.png">

#dogfooding

**Comment by DavidRothstein** [comment]
Tracking internally here: pNPgK-4Ny-p2

**Comment by artpi** [comment]
This would be achieved by pbMlHh-4Q-p2 and decoupling simple payments design
