### ISSUE TITLE
FSE: allow plugin to handle checking if fse is active

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35853]
With site eligibility (default true) handled by a custom filter, let's then allow the plugin to have an is_fse_active (or similar function). 

This is true when: The active theme says it can support Full Site Editing

Note related theme tidying in https://github.com/Automattic/wp-calypso/issues/35794

Checks outside of the plugin may need to see if the function is available or not.

**Comment by vindl** [comment]
This one has already been resolved.

**Comment by noahtallen** [comment]
This function now exists here: https://github.com/Automattic/wp-calypso/blob/023d7357a25c4b0ff7d5944114c4415073419917/apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php#L59-L61
