### ISSUE TITLE
FSE: update Jetpack is_fse_active to properly handle Atomic Sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35854]
We currently disable FSE flows on Atomic, but in https://github.com/Automattic/jetpack/pull/13196/files#diff-beb8fdb5dbdc5157b63e21370779561cR190-R200 `is_fse_active` is true on the single site response, if the plugin is active and we have a specific theme. This means that Atomic sites may get updated Calypso screens without the full FSE flows.

**Comment by gwwar** [comment]
https://github.com/Automattic/jetpack/pull/13392 should fix the single site endpoint, but we have follow up work on cached site data with /me/sites in the site response. We won't have access to the remote filter `a8c_disable_full_site_editing` and we shouldn't depend on the wpcom filters (as we don't want to force a sticker). 

For Cached Jetpack Sites:
1. Check for the site option `a8c-fse-is-eligible`, if the remote is overriding `a8c_disable_full_site_editing` I think this is good enough for checking eligibility. 
2. Verify that the plugin is installed + activated
3. Defer to the plugin for the theme support check 

Past work in D31808-code
See related logic cleanup in D32356-code + units

Let's add tests if possible so we don't forget all these cases.

I'll leave the second part up for grabs so maybe @noahtallen or @mattwiebe would be interested. Happy to help if folks have questions.

**Comment by noahtallen** [comment]
I'll start investigating this

**Comment by noahtallen** [comment]
> Check for the site option a8c-fse-is-eligible, if the remote is overriding a8c_disable_full_site_editing I think this is good enough for checking eligibility.

Just tried this out. One thing that's confusing here is the difference between the shadow site and the actual site.

I verified that the option exists on the local site, but it does not exist via `$this->get_replicastore()->get_option( 'a8c-fse-is-eligible' );`. Additionally, when the shadow API calls FSE, it is calling the wpcom instance of FSE, not the local install. Could see that being problematic 🤔

**Comment by noahtallen** [comment]
Another interesting aspect:
1. Apply the filter `apply_filters( 'a8c_disable_full_site_editing', false );`
2. It hits the MU plugin instance of the filter
3. It does not trigger the API context handler part of `is_fse_disabled`, it triggers the default sticker check.

I was trying out these changes with [this PR](https://github.com/Automattic/wp-calypso/pull/35959/files) to see if I could call `\A8C\FSE\is_full_site_editing_active();` from the API endpoint as that would greatly simplify things. Since it's in the wpcom context, and since the sticker DNE on the jetpack site, it won't be quite that simple. But it almost is!

**Comment by noahtallen** [comment]
see D32490-code for a sample of how it could be handled

**Comment by noahtallen** [comment]
Full implementation now in D32575-code

**Comment by noahtallen** [comment]
Fix merged in D32575-code. After merging, I verified that the endpoint continues saying `is_fse_active: true` when upgrading a site to Atomic. Related Calypso flows are also respecting the value, so the customizer is hidden, etc.
