### ISSUE TITLE
Can't test Full Site Editing on wordpress.com

### ISSUE THREAD

**Issue by yannickiki** [Automattic/wp-calypso#35860]
I have a website on wordpress.com and I'd love to test Full Site Editing. I've tested to run it locally and also using Horizon but I don't have access to these new features. Is there any way?
Also do you have an estimated release date for it to be included in wordpress.com?
Thanks

**Comment by arunsathiya** [comment]
Thanks for your interest, and question! @gwwar or @apeatling can probably answer here.

**Comment by gwwar** [comment]
Hi @stevegarnier we're still preparing things, but we hope to have this out for folks in the near future.

**Comment by stevegarnier** [comment]
Thank you for your reply. if you have a list of beta testers, count me in!
