### ISSUE TITLE
Support User: Ensure Redux store and sync-handler are cleared when switching

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#3586]
To ensure compatibility of the support user feature with the upcoming persistence of Redux state and sync, persisted state should be cleared between activating/deactivating support user mode.

See [this discussion](https://github.com/Automattic/wp-calypso/pull/3492#discussion_r54187095) on #3492

cc @gwwar @aduth @retrofox

**Comment by retrofox** [comment]
#3327 is landing today. Then let's hook `syncHandler` method to clear local data.

**Comment by jordwest** [comment]
This was closed by #3977
