### ISSUE TITLE
Import: Add Tracks events for client-side events

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#35878]
Tracks events corresponding to the following client-side events in Importing should be added in order to aid in better understanding customer behavior and areas for future improvement.

_Note: These events are necessary because the `/import` section does not change the route when navigating within the section._

Note: Importer engine should be recorded as a prop for each event.

- [x] Importer UI shown (example, when the user clicks "Start Import" for WordPress or Blogger on `/import`)
- [x] File uploaded (for file-based importers)
- [x] URL entered (for URL-based importers)
- [x] Author mapping shown
- [x] "Start Import" clicked
- [x] "Cancel" clicked
- [x] All Done shown

**Comment by jonathansadowski** [comment]
There are some events in place already that may satisfy some of these... I'll add new events for the others.

> Importer UI shown (example, when the user clicks "Start Import" for WordPress or Blogger on /import)

`calypso_importer_main_start_clicked` has prop of `importer_id` (`importer-type-*` where `*` is the engine)

I'm not sure if this only triggers on explicit click -- I'll double check if auto-start triggers the same event, if not, I'll probably add a new one, as `clicked` probably shouldn't be used for a `view` event.

> "Cancel" clicked

`calypso_importer_main_cancel_clicked` has the same prop (`import_id`) as `calypso_importer_main_start_clicked`

The names of the existing events are a bit unfortunate, as I believe the standard is supposed to be `*_click`, but I'll leave them unchanged, as they have history.
