### ISSUE TITLE
How can i change the lenguage of my plugin ?

### ISSUE THREAD

**Issue by daqniwloe** [Automattic/wp-calypso#35873]
My wordpress native language is Portuguese, so i dowload a plugin in portuguese, but when i use the plugin, all plugin become in English. How can i solve this problems? 

![Plugins ‹ Personalizze — WordPress - Google Chrome](https://user-images.githubusercontent.com/13256524/63957762-6b280700-ca5f-11e9-881b-d82451a8864d.jpg)

**Comment by eliorivero** [comment]
Hi, this is the repository for the Calypso framework and doesn't have anything to do with WordPress or those plugins. You'll find help at the plugin support forums https://wordpress.org/support/plugin/woocommerce-correios/ or at the plugin repository https://github.com/claudiosanches/woocommerce-correios
