### ISSUE TITLE
SPT: Modal header is unnecessary and takes up valuable vertical space

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#35886]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/191598/63974304-953af280-ca7a-11e9-98b2-f6c3da727d22.png">

This bit at the top of the page template modal is largely unnecessary. I understand that it may be a common pattern for the Modal component, but as we plan to move away from it, we should consider short-term adjustments to make the most of the space we have available.

As we have a Cancel button, and the ability to click the scrim as two methods of dismissing the modal, I wonder if we can remove the "X" icon and reduce the label down to be smaller. Something like this:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/191598/63974657-45106000-ca7b-11e9-9087-1f502dc5a853.png">

**Comment by obenland** [comment]
The header is part of the Gutenberg Modal component. The best way to hide it seems to be through CSS. #35248 might help with changing that.

**Comment by obenland** [comment]
We'll replace the modal in Iteration 9, so this won't be an issue after that. See #35248.
