### ISSUE TITLE
Gutenberg: Image Blocks in Full Width alignment load images smaller than width of content.

### ISSUE THREAD

**Issue by spencerberry** [Automattic/wp-calypso#35881]
#### Steps to reproduce
1. Static Front Page
2. Add an image block with a large, crisp image
3. Set alignment to full width, size to full
4. Publish page
5. Notice the image comes out blurry
6. Notice that the image is loaded at a smaller size than full width with a url like https://prmmjnk.files.wordpress.com/2019/08/bandportrait.jpg?w=640

This happens in both Twenty Nineteen (640px) and Morden theme (750px)

#### What I expected
I would expect a full width block to load an image that is the size of the content area, or larger.

#### What happened instead
The image is loaded at a smaller size than full width.

#### Browser / OS version
Mac 10.14.6 Chrome 76

#user-report if applicable.

**Comment by kwight** [comment]
Closing as a duplicate issue to https://github.com/Automattic/wp-calypso/issues/35822 (steps to replicate are different, but they have the same unlying cause).
