### ISSUE TITLE
SPT: Various (and numerous) rendering bugs when previewing page templates

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#35888]
As I click between templates in the modal to see their larger preview, I notice that there are often visual rendering bugs in the previews. Some are obvious and some are subtle, but together than create a less-than-stellar impression. Here's some of the ones I've noticed:

<img width="538" alt="image" src="https://user-images.githubusercontent.com/191598/63975801-da145880-ca7d-11e9-84bb-91a25ce22f93.png">

The About template's testimonial columns overflow on top of each other, making the text impossible to read and breaking the layout of the design.

--

<img width="563" alt="image" src="https://user-images.githubusercontent.com/191598/63975866-ffa16200-ca7d-11e9-9e56-29b1bf8eb35e.png">

The Contact template is showing a strange blue-outline around the first paragraph, almost like the block is selected.

Also, the missing Jetpack block placeholders are visible. I'm assuming this is because I don't have Jetpack setup on my local install, but even so the layout of these columns is broken — the blocks overlap each other and render the text impossible to read.

--

<img width="577" alt="image" src="https://user-images.githubusercontent.com/191598/63975979-45f6c100-ca7e-11e9-92ee-55620721688e.png">

The Portfolio template's gallery block is getting cut off on the left and right. Notice how the first and third image appear smaller than the middle?

--

<img width="546" alt="image" src="https://user-images.githubusercontent.com/191598/63976036-5f980880-ca7e-11e9-8475-18c824a6f076.png">

The Services template uses three columns, but the text within these columns overlaps making it impossible to read.

--

<img width="538" alt="image" src="https://user-images.githubusercontent.com/191598/63976085-80605e00-ca7e-11e9-87e0-1ca23c7217f3.png">

The alignment of the text within the Media + Text block is far too close to the edge on the left. In general the margins and images seem very large, while the text is disproportionately small.

--

<img width="457" alt="image" src="https://user-images.githubusercontent.com/191598/63976173-bbfb2800-ca7e-11e9-8942-a3ddbe6e8b0f.png">

The Blog template shows a shortcode instead of the contact form. I'm again assuming this is because I don't have JP installed.

--

<img width="568" alt="image" src="https://user-images.githubusercontent.com/191598/63976231-e351f500-ca7e-11e9-98c5-42485a3c5a60.png">

The Professional template's gallery block is being cut off, similar to the Portfolio template's gallery block. Notice that the first and third image are a different width than the middle?

--

<img width="536" alt="image" src="https://user-images.githubusercontent.com/191598/63976282-fd8bd300-ca7e-11e9-8ce7-63891f48d72b.png">

Again on the Professional template, the three columns of text about half-way down the page are overlapping each other making them impossible to read.

--  

<img width="551" alt="image" src="https://user-images.githubusercontent.com/191598/63976338-16948400-ca7f-11e9-846d-bc1c63d2d63d.png">

Again on the Professional template, the list of client logos is rendering way too large, with icons overlapping and generally looking broken.

--

The Professional template shares the same issue with the Media + Text block that the Team template does; The margins and images seem large, while the text seems too small in comparison.

The Professional template also has missing Jetpack blocks, and the placeholders that are rendered are overlapping.

--

The Small Business template essentially has all of the above issues, plus one more:

<img width="193" alt="image" src="https://user-images.githubusercontent.com/191598/63976455-63785a80-ca7f-11e9-9280-696f0076246b.png">

Notice how the thumbnail shows space on the left-right of the dark background, with the image overflowing into the margins?

In the preview none of these margins are rendered:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/191598/63976501-7ab74800-ca7f-11e9-9c80-05b2cdd99077.png">

**Comment by obenland** [comment]
Thanks for tracking all of these @shaunandrews!

Good news is that #35910 will fix most of the issues. The one that it will not fix is the gallery block getting cut off on the left and right. With #335910 it's now cut off on the right only.

The Blog template showing a shortcode instead of the contact form will need the jetpack subscription block to be available. 
The Small Business template not rendering the Welcome block correctly is due to the way the preview image is cropped and should be fixed with dynamic previews.

**Comment by obenland** [comment]
The remaining issue, gallery being cut off, was fixed in #35958.
