### ISSUE TITLE
(1P) SPT: Thumbnail labels are invisible when :active

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#35885]
When I press on a thumbnail the label turn's white, making it invisible against the white background:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/191598/63973922-cb2ba700-ca79-11e9-8048-5b0909b776e2.png">

This is likely a result of reusing the Button component, but not overriding it's :active state.

**Comment by obenland** [comment]
Does this still happen for you on latest master?

**Comment by obenland** [comment]
Reproducible in Safari.

**Comment by obenland** [comment]
Might get fixed through converting labels to buttons in this iteration.

**Comment by marekhrabe** [comment]
I have fixed this by being explicit about inheriting the dark color even for active states. Tested well in Safari. https://github.com/Automattic/wp-calypso/pull/36346/commits/f0ee6569b3344f31b7adc38edbff93fd7c122c7f

The fix is inside #36346
