### ISSUE TITLE
(2P) SPT: Template thumbnails are missing an active state

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#35884]
When you click on a thumbnail to see its larger preview, there is no active state to indicate which thumbnail has been clicked.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/191598/63973557-fd88d480-ca78-11e9-8936-741b8aa53179.png">

In the screenshot above I've clicked on the Contact template, but there's no indication of this. I suggest we add a border around the currently active thumbnail:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/191598/63973693-4771ba80-ca79-11e9-81c4-88e7695bd405.png">

**Comment by obenland** [comment]
Make the blue frame based on the selected template prop, rather than CSS :hover.

**Comment by marekhrabe** [comment]
Main issues addressed in #36346. However, this work brings up an opportunity for updating our tile styles. We are using the exact same blue border for :hover, :active and selected item. We initially modelled our UI after the "Styles" tiles from Gutenberg as shown here:

<img width="286" alt="Screenshot 2019-09-25 at 20 51 55" src="https://user-images.githubusercontent.com/156676/65649876-598e3c80-dfd6-11e9-82ba-9d1906117bf9.png">

Meanwhile, those styles in Gutenberg got significant updated from the point we started. Should we also update ours too, @shaunandrews?

To summarise current Styles styling from Gutenberg:

- hover only changes the background of the tile to a light gray

<img width="129" alt="Screenshot 2019-09-25 at 20 49 07" src="https://user-images.githubusercontent.com/156676/65649763-f00e2e00-dfd5-11e9-968f-f52ae1825154.png">

- keyboard :focus and :active show the blue outline

<img width="138" alt="Screenshot 2019-09-25 at 20 49 39" src="https://user-images.githubusercontent.com/156676/65649799-0916df00-dfd6-11e9-9246-eaccf5ea7974.png">

- active selection shows a grey border

<img width="131" alt="Screenshot 2019-09-25 at 20 49 52" src="https://user-images.githubusercontent.com/156676/65649804-0f0cc000-dfd6-11e9-8d40-6f928865cb8f.png">

- active selection AND focus/active at the same time show both borders

<img width="138" alt="Screenshot 2019-09-25 at 20 50 45" src="https://user-images.githubusercontent.com/156676/65649834-2a77cb00-dfd6-11e9-84bb-13fd1dc3dcb9.png">

**Comment by shaunandrews** [comment]
> those styles in Gutenberg got significantly updated from the point we started. Should we also update ours too, @shaunandrews?

@marekhrabe I'm not opposed to updating to match. Right now our hover and active states are the same, so this could help.

I will say I find the double border style from Gutenberg to be a little strange.

**Comment by getdave** [comment]
@marekhrabe Did we address this anywhere? I've been reviewing https://github.com/Automattic/wp-calypso/pull/36456#pullrequestreview-296149146 and it's not possible to tell the difference between the "active" state and the focus/hover state on the preview thumbs.

**Comment by marekhrabe** [comment]
> I will say I find the double border style from Gutenberg to be a little strange.

Agreed on the strange part but I view the consistency as a higher priority so we might as well update to use the same styles.

> Did we address this anywhere?

Not yet.

**Comment by marekhrabe** [comment]
Reopening to address the styling

**Comment by getdave** [comment]
As you've self-assigned this one I'm not going to tackle it. I think it's important to have this complete and in place for:

1. The demo.
2. This iteration.
3. The next release.

Shout when you need a review.

Much appreciated.

**Comment by getdave** [comment]
@shaunandrews please see https://github.com/Automattic/wp-calypso/pull/36524
