### ISSUE TITLE
(3P) SPT: On mobile, selecting and then confirming is unnecessary

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#35887]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/191598/63975290-aab11c00-ca7c-11e9-8265-42a107d87ee2.png">

On mobile-sized screens, customers are required to tap a thumbnail and then tap on the blue button at the bottom. Since there's no large preview, this extra tap seems unnecessary. Until/Unless we have some form of larger preview for mobile screen sizes, I suggest we remove the second tap and just let people load a template by tapping on the thumbnail.

**Comment by obenland** [comment]
Mobile == Screen sizes where we don't show the large preview.

**Comment by obenland** [comment]
@shaunandrews Should the preview thumbnails remain 3:4 rather than square, where we don't have a large preview?

**Comment by getdave** [comment]
To confirm - there is no 2nd click at all on "mobile".

**Comment by shaunandrews** [comment]
> Should the preview thumbnails remain 3:4 rather than square, where we don't have a large preview?

Yea, I think so. We should probably try to see if we can make the previews overall larger, as we won't have the bigger preview. Here's a few options we could try to adjust the ratio and grid:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/191598/65795556-86f2fb80-e138-11e9-8ed7-9e6ededfc93a.png">

Alternatively, we could try to do a horizontal scrolling/swiping UI like this:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/191598/65795620-ae49c880-e138-11e9-936c-df5c87e8ea2b.png">

^ This one also shows what it could look like if we bring over the box-shadow from the large preview.

--


> To confirm - there will be (after this Issue is addressed) no 2nd click at all on "mobile".

Correct.

**Comment by getdave** [comment]
@frontdevde This is a solution I implemented previously on the original PR which had the buttons _inside_ each Template preview

https://github.com/Automattic/wp-calypso/pull/36263/commits/714591bd5369330ce3e5f1af84c37633257bd3e5

Basically the click handler on the `button` is an intermediate function which determes (based on `matchMedia()` whether to call:

* the function which "previews" the template 
* the function which selects and inserts the template 

On breakpoints where the large preview is _not_ shown then we use the later to auto insert the template on single "click".

In an ideal world the breakpoint would be shared from the CSS into the JS but on my version, I hardcoded it into both places manually for the sake of expediency. You could inline the breakpoint value into a psuedo element's `content` property and parse that out using JS and use that in the `matchMedia` if you wanted...
