### ISSUE TITLE
SPT: Clicking on the Blank thumbnail dismisses the template modal

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#35883]
Currently, the Blank template thumbnail behaves differently from every other option in the list — yet there's no way of knowing that.

<img width="827" alt="image" src="https://user-images.githubusercontent.com/191598/63972861-97e81880-ca77-11e9-8b62-6c88022ba6bb.png">

When I first see the template modal, I'm instructed to "Select a page template to preview." So, I go about clicking on a few templates and see a preview.

However, if at anytime I select the Blank template, the modal disappears and there's no way back. This is especially confusing when/if a customer clicks on the Blank template first — they'll never get to preview the other available templates.

I understand that we have nothing to "preview" and that this could be helpful for some people who don't want a template, but I find it extremely confusing. I suggest we treat the blank template just like any other, and show a blank preview. Something like this would help:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/191598/63973318-881d0400-ca78-11e9-95b2-1d5750e12d79.png">

/cc @apeatling as I know he has opinions.

**Comment by shaunandrews** [comment]
Oooh, one other thing to add: I think we could/should have the Blank template selected by default when the modal opens.

**Comment by obenland** [comment]
With the new UI, let's open the editor with the blank template selected, as @shaunandrews mentioned above, and show the "Select Template" button in the thumbnail. See https://github.com/Automattic/wp-calypso/issues/35248#issuecomment-524016960
