### ISSUE TITLE
FSE: Classic block content is broken when site enables FSE

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#35894]
#### Steps to reproduce
1. In your local FSE environment install and enable the classic block plugin and add some pages using the classic editor
2. Install and enable the FSE plugin and activate an FSE enabled theme
3. Attempt to edit an existing page with classic content

#### What I expected

The Classic block to appear within the Block Editor the same way it does when FSE not enabled

<img width="647" alt="classic" src="https://user-images.githubusercontent.com/3629020/63994376-87ec3980-cb48-11e9-86a5-cf0c8b113ca5.png">

#### What happened instead

The Block Editor indicated an issue with the classic content: 

<img width="656" alt="invalid" src="https://user-images.githubusercontent.com/3629020/63994401-a6523500-cb48-11e9-9deb-45f5f6b8b467.png">

When selecting the option to resolve the issue nothing happens when clicking either button and the dialog remains open:

<img width="588" alt="resolve" src="https://user-images.githubusercontent.com/3629020/63994448-d7326a00-cb48-11e9-9537-de35cadb7217.png">

**Comment by apeatling** [comment]
@glendaviesnz I expect the chances of this happening to a new user to be very slim on WordPress.com. I think we can bump this one out until after the 10% test?

**Comment by glendaviesnz** [comment]
@apeatling yes, probably unlikely a new user will end up in this state  so can be bumped - was not sure were it goes exactly so will leave it to you to move out.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
