### ISSUE TITLE
Stats: should Taiwan be included as a province of China, or as a separate country (current situation)

### ISSUE THREAD

**Issue by hyfree** [Automattic/wp-calypso#35896]
# Taiwan is part of China
jetpack上的地图绘制错误，台湾不应该作为国家从中国剥离。请jetpack修复这个错误。
Map drawing error: Taiwan is part of China。
The map on jetpack is wrong, and Taiwan should not be stripped from China as a country. Please jetpack fix this error.

# What happened?
state-->Map

![image](https://user-images.githubusercontent.com/26597853/63984015-e808be80-cafb-11e9-88e3-c64c2fab3cf0.png)
![image](https://user-images.githubusercontent.com/26597853/63984081-3027e100-cafc-11e9-9e0a-4737cd568cbd.png)

# What I expected
The map on jetpack is wrong, and Taiwan should not be stripped from China as a country. Please jetpack fix this error.

# What happened instead

**Comment by jeherve** [comment]
Related:
https://github.com/woocommerce/woocommerce/issues/24237
https://github.com/woocommerce/woocommerce/pull/24425

**Comment by Lin-Buo-Ren** [comment]
On behalf of most (if not all) Taiwan citizens, I would like to express my deep concern and objection of this issue.  It is a well-known fact that Taiwan is in almost every aspect, independent from PRC(despite its status in UN, as which is not a member due to the "Two Chinas dilemma").

Making this change will certainly give non-China-nese users confusion as web visitors have drastically different point of views, networking accessibility (e.g. we don't have the #GFW), and political preferences, etc.

As a separate issue, you should consider using "region" instead of "country" in your section titles as country names are highly disputed in various state-like entities.

**Comment by unfulvio** [comment]
Related discussion ongoing in https://github.com/woocommerce/woocommerce/pull/24425

**Comment by unfulvio** [comment]
Additional resources, for those interested:

* https://en.wikipedia.org/wiki/Political_status_of_Taiwan
* https://en.wikipedia.org/wiki/Taiwan,_China
* https://www.drupal.org/project/drupal/issues/1938892 (why ISO-3166-1 is problematic)

**Comment by yoren** [comment]
FYI. In Google Analytics, Taiwan is listed as "Taiwan" in the Country column of Audience - Geo - Location table, as seen: https://www.dropbox.com/s/myehzl7idfduxaq/Analytics.png?dl=0 and the map also segments Taiwan as a country: https://www.dropbox.com/s/z4cyt04anpj3tm9/Screenshot_2019-08-31_09_02_54.png?dl=0. 

Hope that can help to show ISO 3166 isn't adopted in the similar software, hence it's really not an issue but will be, for JetPack users to gain the valuable visitor source data, if updated as requested.

**Comment by lsl** [comment]
This is an artifact of the [GeoChart component](https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/stats/geochart) from Google and is not something we can reasonably change.

I suggest reporting the issue [upstream](https://developers.google.com/chart/interactive/docs/gallery/geochart).

**Comment by nobodxbodon** [comment]
@lsl thanks for the info. After checking the code, it seems the controversial label 'Country' [is here in the project](https://github.com/Automattic/wp-calypso/blob/1951f770d435e8109a72db361004b27cb0f87447/client/my-sites/stats/geochart/index.jsx#L116), if I'm not mistaken. On the other hand [GeoChart](https://developers.google.com/chart/interactive/docs/gallery/geochart#overview) states that:

> The regions style fills entire regions (typically countries) ...

So maybe better to use 'Region' as label to avoid controversy?
