### ISSUE TITLE
Theme Gallery: "Thanks for choosing" dialogue can't be closed by clicking outside the box.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#35892]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/
2. Activate a theme.
3. On the "Thanks for choosing" popup, try clicking outside the dialogue area to close the popup.
4. Popup refuses to close unless you click "Learn about this theme" or "Customize site".

#### What I expected
To be able to easily close the popup dialogue, especially if testing multiple themes back-to-back.

#### What happened instead
You either have to click "Learn about this theme" which redirects your current page to the theme info, even if you don't want your page redirected.

Or open the customizer in a new window, even if you don't want it to or need to customize anything.

#### Browser / OS version
Chrome OS Version 76.0.3809.102 (Official Build) (64-bit)

#### Screenshot / Video
![Screen Shot on 2019-08-29 at 17_17_39](https://user-images.githubusercontent.com/10121835/63980812-501abe80-ca82-11e9-8b20-161c8d1911c8.png)

#### Context / Source

This is extremely frustrating especially if you're trying to change themes in one tab, and then refresh/review the new theme style on the site in another.

You either get tabs you don't want opening, or you have to click back every time you change a theme.

Both create unnecessary work and being locked into a popup is generally frustrating, like when a popup ad won't let you dismiss it.

**Comment by arunsathiya** [comment]
I agree, I have run into this a few times and it is frustrating.

**Comment by tijosh** [comment]
+1 on this. Came here to open an issue if it didn't exist.

**Comment by iamtakashi** [comment]
+1 on this. This is very inconvenient as you need to go either of those pages to get out.

**Comment by kristarella** [comment]
+1 This is annoying af. I'm pretty sure it was not always like this, clicking outside or hitting ESC used to close it. This should always be the case for a popup dialogue!

**Comment by formosattic** [comment]
+1 This is really irritating when frequently changing themes for testing purpose.

**Comment by noahtallen** [comment]
I just made a fix for this here: https://github.com/Automattic/wp-calypso/pull/36584! It looks like there was "just" a small typo: it tried to call `_close` instead of `close`.

**Comment by noahtallen** [comment]
If anyone wants to test and give a 👍 feel free!

**Comment by iamtakashi** [comment]
@noahtallen Thank you for fixing this issue! 🎉
