### ISSUE TITLE
Signup: Plans: Promote free domains

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3590]
We'd like to test promoting that the domain that comes with a plan is free. @breezyskies can you create some designs for this?

**Comment by breezyskies** [comment]
Proposed design:

<img width="738" alt="screen shot 2016-02-26 at 3 15 13 pm" src="https://cloud.githubusercontent.com/assets/3011211/13398775/bf10a498-deb4-11e5-848b-8b4e40faa1b0.png">

<img width="346" alt="screen shot 2016-02-26 at 3 20 12 pm" src="https://cloud.githubusercontent.com/assets/3011211/13398777/bf25247c-deb4-11e5-9a7a-1106023893f9.png">

These should probably only show to users who are currently on the free plan (maybe using the `excludeSitesWithPaidPlan` flag for the test).
