### ISSUE TITLE
FSE: Support Maywood on Simple Sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35913]
Maywood was recently published but doesn't work with FSE flows. It's half-on based on plugin vs API checks.

When editing a page we see infinite loaders in the header/footer:
<img width="1199" alt="Screen Shot 2019-08-30 at 2 07 42 PM" src="https://user-images.githubusercontent.com/1270189/64051337-a1cd5280-cb2f-11e9-9bcd-3dfd9f59070e.png">

Single site endpoint, /sites/mysite and /me/sites returns `is_fse_active` to false
<img width="974" alt="Screen Shot 2019-08-30 at 2 10 32 PM" src="https://user-images.githubusercontent.com/1270189/64051486-1a341380-cb30-11e9-8376-8f41ccdf7c17.png">

This means we also see links to the customizer.

To Reproduce:
- Create a new user/test site on horizon, verify that FSE flows work with Modern Business
- Sandbox with a FSE plugin snapshot using Calypso master. For example `./bin/calypso/build-full-site-editing.sh 419548 0.6.1`
- Make sure external themes svn is up to date.
- Activate Maywood
- Sandbox both the site and the public api
- Try editing a page

This is currently blocking any style verification on Simple Sites, and likely caused by the duplicate code in mu-plugins for is_fse_active.

If we only have 0.6.1 available on wpcom:
- Let's update the MU code to at least call is_supported_theme from the plugin, if possible. Verify that Call for Testing flows work with Modern Business.
- While sandboxed with latest, this should allow us to test FSE flows on Maywood

If the plugin has updates, with the cleaner is_fse_eligible, and is_fse_active,
- Let's remove or update calls in MU to use is_active logic as much as possible.

**Comment by gwwar** [comment]
For folks looking at this, the related wp_templates are populated

<img width="1077" alt="Screen Shot 2019-08-30 at 2 19 36 PM" src="https://user-images.githubusercontent.com/1270189/64051852-6c296900-cb31-11e9-912e-70f4afd209cf.png">

<img width="1075" alt="Screen Shot 2019-08-30 at 2 19 02 PM" src="https://user-images.githubusercontent.com/1270189/64051866-751a3a80-cb31-11e9-88d9-9e94592959ea.png">

**Comment by glendaviesnz** [comment]
@gwwar looks like there might be a couple of things at play here. I was able to get the templates loading ok on Horizon with a new site creation with Modern Business and then switching to Maywood:

<img width="1661" alt="maywood" src="https://user-images.githubusercontent.com/3629020/64085427-c2431a00-cd86-11e9-8108-c1edc6e38e58.png">

So not sure why you get the spinner when you try - it seems like the template spinner is sometimes caused if there are no, or invalid, templates for the given site/theme combination.

It does however still show the customizer link for me - so the site as not be flagged as fse_active. I verified that it is the MU plugin is_fse_active_for_theme method that is the issue by adding this temporary patch, D32314-code, and the customizer link did then disappear.

I looked at removing the hard coded supported themes array and instead calling out to `\A8C\FSE\Full_Site_Editing::get_instance()->is_supported_theme( $theme_slug );` but  `\A8C\FSE\Full_Site_Editing` is not available when the call to `is_fse_active_for_theme` is made.

So bit of a chicken and egg situation ... so trying to work out what other options we have - maybe it is worth applying D32314-code as a temporary fix?

**Comment by glendaviesnz** [comment]
This is probably more related to https://github.com/Automattic/wp-calypso/issues/35853, but it looks like we can use a `\A8C\FSE\Full_Site_Editing::get_instance()->is_active()` type function from 
`~sandbox/wp-content/mu-plugins/full-site-editing.php` but not from `~sandbox/wp-content/mu-plugins/full-site-editing/class-full-site-editing.php` it is not defined in the second context `is_fse_active_for_theme` is currently used - will catch up with you about this tomorrow as not sure on best way forward with this.

**Comment by gwwar** [comment]
I created D32356-code, but let's see what feedback folks have for the approach. We can try landing tomorrow morning otherwise.

**Comment by glendaviesnz** [comment]
fixed by #35994
