### ISSUE TITLE
Checkout: weird layout in Submitting notice for payment with domain credit

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#3593]
The layout of the blue notice in `/checkout` is broken, when you purchase a domain using domain credits.

Steps to reproduce:

- Purchase Premium or Business for a site.
- Visit `/domains/add/:site` for that site, and purchase a domain.
- You'll be told you can use a domain credit to pay for the domain. Click the blue button, and check the blue notice in the top right corner of the screen. It looks like this, with the dismiss button in a separate line:

![screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2016-02-26 12-36-12](https://cloud.githubusercontent.com/assets/1248436/13351248/a0e27b44-dc85-11e5-9410-ba91ea39eb71.png)

**Comment by gziolo** [comment]
@breezyskies Can you check this one?

**Comment by breezyskies** [comment]
Can't reproduce (in Chrome). I do believe there was a browser-specific issue with the global notices and flexbox (not specifically for checkout), but I can't find a related issue for it. 

@fabianapsimoes can you verify if this is for all global notices and which browser it's in?

**Comment by fabianapsimoes** [comment]
This does not happen for all notices. Not even all checkout notices. I could only reproduce it in this context, and in Firefox. @scruffian has seen this as well, as he mentions here: https://github.com/Automattic/wp-calypso/pull/3839#issuecomment-194225672

**Comment by Tug** [comment]
It seems to be happening for notices which text width is smaller than 100px. Probably due to that CSS property here:

> `flex-basis: 100px;`
> https://github.com/Automattic/wp-calypso/blob/master/client/components/notice/style.scss#L47

We have to test the impact of removing this property on current notices (and maybe even add global notices to devdocs)
