### ISSUE TITLE
FSE: Blog Posts Listing Block: Add Category Filter

### ISSUE THREAD

**Issue by tijosh** [Automattic/wp-calypso#35933]
It would be great to have the option to specify which category the Blog Posts Listing block displays. 

More often than not, new users add `Pages` to their site's menu, intending for them to have post categories. Rather than making them convert those to `Pages` to `Category` menu items, the Blog Posts Listing block with a category filter could be a simple solution.

![Screenshot](https://cld.wthms.co/IbZ73x+)

**Comment by davipontesblog** [comment]
Closing this as this blog has been replaced with the [Blog Posts Block](https://github.com/Automattic/newspack-blocks) which has this functionality.
