### ISSUE TITLE
Editor: Publicize option not appearing on mobile site

### ISSUE THREAD

**Issue by reginabally** [Automattic/wp-calypso#35941]
#### Steps to reproduce
1. Log in to WordPress.com via a mobile browser (e.g. Chrome or Firefox)
2. Choose a page/post to edit
3. Click the vertical ellipses and then Jetpack
4. Nothing happened instead of showing the publicize option

#### What I expected

The publicize option should be displayed on a mobile site.

#### What happened instead

Nothing happened. The screen stayed as it is.

#### Browser / OS version

Tested on:

* Mozilla Firefox on Android: https://whatismybrowser.com/w/F257BYC
* Google Chrome on Android: https://whatismybrowser.com/w/EWY328E

#### Screenshot / Video

The screen stayed after clicking the Jetpack link on mobile:

![Screenshot_20190903-133727](https://user-images.githubusercontent.com/40906847/64146703-90968580-ce50-11e9-8eab-c3ade58eba57.png)

Expected to see the publicize option on desktop like this:

![Screen Shot on 2019-09-03 at 13:41:56](https://user-images.githubusercontent.com/40906847/64146736-ad32bd80-ce50-11e9-94e8-4a08c6ebfbed.png)

#### Context / Source

#user-report

2315582-zen

**Comment by kriskarkoski** [comment]
This looks to have been fixed. Testing on Chrome on iOS I can tap the Jetpack option and manage sharing settings. There does look to be an issue with extra padding at the top of the editor making the Show sharing buttons hard to get to, but I'll open a new issue for that.
