### ISSUE TITLE
Gutenberg: SWIFT Language missing for SyntaxHighlighter Code Block

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#35942]
This is a feature request from 2319609-zen.

The request is to add the SWIFT option into the Language setting for the SyntaxHighlighter Code Block on top of the existing options listed [here](https://en.support.wordpress.com/wordpress-editor/blocks/syntax-highlighter-code-block/view-all/).

**Comment by Robertght** [comment]
Another request here: 4663612-zen

**Comment by liviopv** [comment]
The block now has the Swift, closing as fixed.

![CleanShot 2024-01-10 at 09 41 21@2x](https://github.com/Automattic/wp-calypso/assets/14153300/1d10eade-6d3b-4b4d-ba32-56742ddfb755)
