### ISSUE TITLE
SPT: Blog main image is cut off on edge of window

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35956]
Even at the largest window and modal width, it is still cut off on the right edge:

<img width="640" alt="Screen Shot 2019-09-03 at 11 07 06 AM" src="https://user-images.githubusercontent.com/1464705/64197500-1c9db280-ce3b-11e9-8dd8-442561d2d3e1.png">

**Comment by apeatling** [comment]
Also the "blog posts" block is under the image below it.

**Comment by obenland** [comment]
> Also the "blog posts" block is under the image below it.

That appears to be a bug with the Modern Business editor styles.

**Comment by retrofox** [comment]
I've tested with different themes, from the current `marter` branch of Calypso and Gutenberg. 

**Modern Business**

Large Preview
![image](https://user-images.githubusercontent.com/77539/64211135-75cd0c80-ce62-11e9-82ae-c5a439974041.png)

Thumbnail (testing purpose)
![image](https://user-images.githubusercontent.com/77539/64211171-91381780-ce62-11e9-8ac2-020b36e729e1.png)

**Morden**

Large Preview
![image](https://user-images.githubusercontent.com/77539/64211095-4fa76c80-ce62-11e9-93bb-de5bdb22a2d8.png)

Thumbnail (testing purpose)
![image](https://user-images.githubusercontent.com/77539/64211063-37375200-ce62-11e9-9e97-982efdbe3b2a.png)


**Gutenberg Starter Theme**

Large Preview
![image](https://user-images.githubusercontent.com/77539/64211215-b2990380-ce62-11e9-8da1-01a76d5eb716.png)

Thumbnail (testing purpose)
![image](https://user-images.githubusercontent.com/77539/64211224-b88ee480-ce62-11e9-91fa-0822c8e8d489.png)

**Comment by retrofox** [comment]
fixed with https://github.com/Automattic/wp-calypso/pull/35958
