### ISSUE TITLE
SPT: Keep the large preview a consistent width

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35957]
When the window is reduced in width the previews are not scaling correctly, and most of them are just getting cut off:

<img width="679" alt="Screen Shot 2019-09-03 at 11 09 07 AM" src="https://user-images.githubusercontent.com/1464705/64197628-5ec6f400-ce3b-11e9-928e-9f86c15ec241.png">

To fix this in the short term I suggest keeping the large preview a consistent width, and reducing the number of columns on the left of small previews, until there is not enough space for one column. At that point hide the large preview as it does on mobile viewports.

**Comment by retrofox** [comment]
Fixed in #35958
