### ISSUE TITLE
Show storage limit and usage for Business and eCommerce sites

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#35965]
The storage space limit and usage indicator is not currently shows on Business and eCommerce sites (both simple and Atomic). We need to expose this to display the upload limit and current usage.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/site
2. Note the indicator is not shown on Business and eCommere sites as it is on lower plans

#### What I expected
To see how much space I am using and my space limit.

#### What happened instead
I cannot see the space bar.

#### Screenshot / Video
Here is what this looks like on a Premium site (the upsell would not be present on these sites as they are on our maximum storage plans):

<img width="1131" alt="Screen Shot 2019-09-03 at 10 48 23 PM" src="https://user-images.githubusercontent.com/1900444/64222588-a16de800-ce9e-11e9-8304-7a8a864545f4.png">

**Comment by thehenrybyrd** [comment]
Yes please! 
There's currently no easy way to direct folks using the Business or eCommerce plan to find out how much space they're using. Since this space is no longer "unlimited", but rather 2GB, it's important to users to be able to see find information easily.

**Comment by timmyc** [comment]
Confirmed this bug is still present, but since it is happening in both the biz plan and ecomm plan, I'm going to remove the ecomm plan label.

**Comment by lancewillett** [comment]
Work in progress: https://github.com/Automattic/wp-calypso/pull/40268

**Comment by cecilearkay** [comment]
It seems there may be a discrepancy with the Media Library in Calypso as it doesn't reflect the correct storage. In this [example](https://atomicrequests.wordpress.com/2020/04/03/hi-this-user-reached-out/), we found that Site Health shows 188/200 Gb and the Media Library in Calypso, it showed 0.5% used (so about ~1 Gb).
