### ISSUE TITLE
Social Signup/Login: Redirect to wordpress.com overrides social redirect to /start

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#35978]
#### Steps to reproduce
1. Starting logged out at URL: https://wordpress.com/
2. Select "Log in" to go to the login screen. Note that the login URL already includes a redirect: `https://wordpress.com/log-in?redirect_to=https%3A%2F%2Fwordpress.com%2F`
3. Select "Continue with Apple."
4. In the pop-up window, log in to an Apple ID not linked to a WordPress.com account (including the email address is not currently used with a WordPress.com account).
5. Continue with the prompts in the pop-up window to confirm you want to use the Apple ID with WordPress.
6. Note that the login screen now says "Creating your account," and wait for the login screen to redirect you.

#### What I expected
I expected to be redirected to the site creation flow at `/start`.

#### What happened instead
I was logged in to my new account and directed to https://wordpress.com/ with no site, skipping the site creation flow.

This seems to be caused by the redirect in the URL on the login screen. If I visit https://wordpress.com/log-in directly and follow the same steps from there, I am redirected to `/start` as expected.

#### Browser / OS version
Original report from @etoledom with Safari Version 12.1.2 / macOS Mojave 10.14.6

Reproduced with Chrome 76.0.3809.132 / macOS Mojave 10.14.6

#### Context / Source
Beta testing, internal ref: p77Llu-cz5-p2#comment-14647

**Comment by Tug** [comment]
I'm not really sure but I believe this is expected, we might want to customize the sign up experience by giving it a custom redirect_to as part of the url. Maybe the url on wordpress.com should be updated instead. I created a server side patch for this D32806.
If we don't want that, then yeah we should update calypso to ignore the `redirect_to` param in case of a new signup
