### ISSUE TITLE
Me: Improve the on-screen feedback when an account is closed

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#35977]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Select "Close your account permanently."
3. On the next screen, select "Close account."
4. In the modal that appears, enter your username and select "Close your account" to confirm.

#### What I expected
I expected some kind of message or spinner to indicate that my account closure was being processed, and/or a confirmation message that it succeeded.

#### What happened instead
There was no indication on-screen that anything was happening (the modal window just disappeared) and then I was logged out of my account with no further message.

#### Browser / OS version
Safari version 12.1.2 (14607.3.9)
Mac OS Mojave 10.14.6

Reproduced in 76.0.3809.132

#### Context / Source
Beta testing, h/t @serabi and @coder-karen for the reports (internal refs: p77Llu-cz5-p2#comment-14708 and p77Llu-cz5-p2#comment-14719 )

**Comment by Aurorum** [comment]
PR in #37688 for this issue. :)

![ezgif-4-38189b5c2a99](https://user-images.githubusercontent.com/43215253/69093584-a32f5c80-0a46-11ea-875b-e7c158fc2dbd.gif)

**Comment by bluefuton** [comment]
Thank you @Aurorum 🙂
