### ISSUE TITLE
Checkout: Thank You: Free trial nudge

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#3597]
Proposed design for the free trial nudge on the new thank you page (uses existing design treatment from the [new thank you page](https://github.com/Automattic/wp-calypso/issues/2484)):

<img width="708" alt="screen shot 2016-02-25 at 3 24 53 pm" src="https://cloud.githubusercontent.com/assets/3011211/13357284/63feee0a-dc5e-11e5-89ec-8d4f6152b06f.png">

I think this is a good starting spot, though we may want to test a [different design treatment](https://cloud.githubusercontent.com/assets/3011211/13357314/7955a6ea-dc5e-11e5-9fd7-75c1795aae1a.png) at a later point, as we refine this test.

Proposed copy (reusing some of the copy from the landing pages):

> Try WordPress.com Premium free for 14 days
> 
> Go beyond basic with a supercharged WordPress.com website. The same easy-to-use platform, now with more features and more customization.
>
> Try Premium for Free

cc: @ranh @mikeshelton1503 @fabianapsimoes

**Comment by fabianapsimoes** [comment]
We'll we only nudge for Premium?

**Comment by fabianapsimoes** [comment]
@breezyskies another question: what happens in terms of flow when the user clicks "Try for Free"? We talked about removing the confirmation page before. Should we just send users to the trial hub with the green confirmation notice?

**Comment by breezyskies** [comment]
> We'll we only nudge for Premium?

My vote is to start with Premium and test the Business nudge separately (or a future test could include both CTAs). We could eventually try being smart about which one to show (e.g. using the verticals data, or showing Business if the user has a static homepage). 

> what happens in terms of flow when the user clicks "Try for Free"? We talked about removing the confirmation page before. Should we just send users to the trial hub with the green confirmation notice?

Correct, since they just came from checkout, I think we can take them straight to the hub with confirmation notice.

**Comment by ranh** [comment]
Copy LGTM

**Comment by stephanethomas** [comment]
Where should we display this new section? Just below the `What now?` heading? Or at the bottom of the list of features?

**Comment by stephanethomas** [comment]
This was mentioned internally but this issue doesn't mention it: we should only display this nudge after domain registration or domain mapping purchases.

**Comment by breezyskies** [comment]
> Where should we display this new section? Just below the What now? heading? Or at the bottom of the list of features?

Let's go with the bottom for the first test.
