### ISSUE TITLE
FSE: Remove Try & Customize option for FSE + Template First Themes

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35985]
Template first themes rely on page templates to match themes to the demo sites. This means the "Try and Customize" option is no longer relevant. You are not trying to see how your existing content looks in the new theme because it will not be present.

Instead we should be removing this option for every new template first theme that supports full site editing, and leaving only the activate option. This will also remove another entry point into the customizer.

<img width="456" alt="Screen Shot 2019-09-04 at 2 28 21 PM" src="https://user-images.githubusercontent.com/1464705/64293009-7fb54500-cf20-11e9-816c-6de0de9fc37d.png">

<img width="1517" alt="Screen Shot 2019-09-04 at 2 28 30 PM" src="https://user-images.githubusercontent.com/1464705/64293011-80e67200-cf20-11e9-8b40-6ebc27f20360.png">

**Comment by apeatling** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/36044

**Comment by davipontesblog** [comment]
Closed as this has been implemented now.
