### ISSUE TITLE
Featured Image: Error with images from Free Photo Library

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#35987]
#### Steps to reproduce
1. Create a new post
2. Click on the button to add a Featured Image
3. Select the option to find images from the Free Photo Library
4. Search and select an image from there

#### What I expected
To have the image added as the post's Featured Image.

#### What happened instead
When I try to save the post it throws the error:

> Updating failed. Error message: Invalid parameter(s): featured_media

I have to remove the image I selected, then select again from the site's media library, now that it shows the image there.

#### Browser / OS version
OS X 10.13.6
Chrome 76.0.3809.132

#### Screenshot / Video
![FeaturedImage](https://user-images.githubusercontent.com/16104522/64295823-a5eedb00-cf48-11e9-9ae8-e42988e0494a.gif)

#### Context / Source
#dogfooding

**Comment by arunsathiya** [comment]
I think it is the same as this issue - https://github.com/Automattic/wp-calypso/issues/35987

I am not seeing the `Uncaught (in promise) Error: [object Object]` error as noted by @kwight on that report, but I see `Unhandled promise rejection` on my console logs. Wonder if we should close this report in favor of the other one.

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/31230.
