### ISSUE TITLE
Page Templates: Show the Theme homepage template in the picker

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35991]
Every new theme now has a specific homepage template included with it. There is no way for users to select this as the template to use via the picker.

As part of this we should be building a way for any theme to override a global page template. See:

![global-local-templates](https://user-images.githubusercontent.com/1464705/64299944-ea21b180-cf2f-11e9-843b-39852af3b55f.png)

**Comment by obenland** [comment]
Related: #35682, paYJgx-bI-p2

**Comment by obenland** [comment]
Homepage templates are part of the template selector.
