### ISSUE TITLE
Theme showcase: Customize Theme overlay cannot be dismissed

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#35995]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/SITE_URL
2. Select a theme and click on Activate theme
3. When the "Thanks for choosing {theme}" overlay appears, try to dismiss it without selecting either of the options in the overlay by clicking outside of the overlay.

#### What I expected
For the overlay to disappear if I click on the screen anywhere outside it, allowing me to return to the main Calypso menu. This is how it worked in the past.

#### What happened instead
There is no way to dismiss the overlay and return to the Calypso menu. Clicking outside the overlay has no effect at all, and the only options are to click the buttons to go to either the theme's showcase page or to the Customizer.

#### Browser / OS version
Confirmed in latest versions of Firefox and Chrome on Mac OS 10.14.6

#### Screenshot / Video
<img width="764" alt="WordPress_Themes_‹_kokkiestrialtestsite_—_WordPress_com" src="https://user-images.githubusercontent.com/11873759/64314859-b470dd00-cfb0-11e9-9698-a7a5fbaf4ea9.png">

#### Context / Source

Discovered when switching themes on a test site.

**Comment by arunsathiya** [comment]
I am closing this in favor of the previous report - https://github.com/Automattic/wp-calypso/issues/35892

If I misreading something, let's feel free to reopen.
