### ISSUE TITLE
Domains: Change Site Address confirmation modal vertical space

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36009]
<img width="446" alt="Screen Shot 2019-09-05 at 5 07 40 PM" src="https://user-images.githubusercontent.com/2124984/64381281-d09c6a80-d000-11e9-89f4-75f5e4b202ab.png">

This panel has some inconsistent vertical spacing that could be cleaned up.

1) The red and green site address notices are crowded.
2) There's not much space above the "Check the box to confirm" heading.

To find this panel, go to Domains -> Click on a site -> Scroll to Change Site Address. Input an available site address and click Change Site Address.

**Comment by Aurorum** [comment]
PR for this issue in #36050. :)
