### ISSUE TITLE
Domains: Consider standardizing copy on Change Site Address error and confirmation messages

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36008]
<img width="736" alt="Screen Shot 2019-09-05 at 4 56 53 PM" src="https://user-images.githubusercontent.com/2124984/64380626-5e775600-cfff-11e9-84d5-276d358ae87b.png">
<img width="737" alt="Screen Shot 2019-09-05 at 4 57 04 PM" src="https://user-images.githubusercontent.com/2124984/64380627-5e775600-cfff-11e9-9fa6-337ffc203e51.png">

To see these messages, go to Domains -> Click on a site address -> Go to Change Site Address at the bottom of the screen.

1) The error message when you input a site URL that's already taken has an exclamation point -- seems unnecessary, since we're not delivering happy news.
2) We use different terms when a site address is available vs. not:

> Error: Sorry, that site address has already been used!

> Success: Good news, this site address is available!

"That site address has already been used" sounds awkward to me. What if we mirrored the success message and said, "Sorry, that site address is unavailable." ?

Another nitpick -- we use “that site address” for the error message, and “this site address” for the success message. Can we pick one or the other?

**Comment by nerdysandy** [comment]
https://cloudup.com/cTGCROxJ8yt - The error message comes from the server. This means we can't fix it directly.

**Comment by nerdysandy** [comment]
Changed the success message to use the word `that` in it. This is because we can't edit the error message for now. This way they will be both consistent.

**Comment by sixhours** [comment]
The error message can be changed by someone with a WP.com sandbox; I'll look into that!

**Comment by sixhours** [comment]
Started a diff in D33039-code

**Comment by sixhours** [comment]
This is really old! But I think the idea still has merit. @danhauk can you spare a review so I can ship this this week? It's a relatively minor wording change.

**Comment by danhauk** [comment]
Just approved D33039-code. Thanks for handling that! I'll let you close this issue once it's deployed.

**Comment by sixhours** [comment]
Yay thanks! Deployed in r200884-wpcom!
