### ISSUE TITLE
Gutenberg: WooCommerce Product Blocks on Safari

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#36001]
#### Steps to reproduce
1. Create a new page on a site with WooCommerce
2. Add a Products block (ex: Newest Product, Products by Category, Best Selling Products)
3. Make sure the block is set to display more than 2 columns and one row
4. View published page on Safari

#### What I expected

All products to be displayed on a single row. 

#### What happened instead

The last product drops to the next row (tested with 3, 4, 5, and 6 columns)

#### Browser / OS version

Safari 12.1.2

(Works as expected in Chrome and Firefox. Did not test in IE)

#### Screenshot / Video
Test Page: https://20181019kfstore.blog/346-2/

noted that if the display declaration in `.wc-block-grid__products::after` is unchecked, then the items appear on a single line. 

Screenshot: ![Screenshot](https://cld.wthms.co/9r0OrY+)
Image URL: https://cld.wthms.co/9r0OrY

#### Context / Source
#user-report 
#2318300-zen

**Comment by mikeicode** [comment]
Also reported in 15053310-hc (6 products in a row jumped to 2 lines in Safari)

**Comment by samiff** [comment]
Another in 2349706-zd

**Comment by champagnebonden** [comment]
I have the same issue. Does anyone have a good guess on when this could be solved? Many thanks in advance.

**Comment by mikeicode** [comment]
Issue still exists, another report 17420396-hc

I created CSS which can be used as a solution until this is resolved.

```

/* WooCommerce Products block - fix spacing for Safari  */

.wc-block-grid.has-2-columns .wc-block-grid__product {
	flex: 1 0 49.9%;
}
.wc-block-grid.has-3-columns .wc-block-grid__product {
	flex: 1 0 33%;
}
.wc-block-grid.has-4-columns .wc-block-grid__product {
	flex: 1 0 24.95%;
}
.wc-block-grid.has-5-columns .wc-block-grid__product {
	flex: 1 0 19.5%;
}
.wc-block-grid.has-6-columns .wc-block-grid__product {
	flex: 1 0 16.6%;
}

@media (min-width: 481px) and (max-width: 600px) {
	.wc-block-grid.has-2-columns .wc-block-grid__product,
	.wc-block-grid.has-3-columns .wc-block-grid__product,
	.wc-block-grid.has-4-columns .wc-block-grid__product,
	.wc-block-grid.has-5-columns .wc-block-grid__product,
	.wc-block-grid.has-6-columns .wc-block-grid__product {
		flex: 1 0 49.89%;
	}
}

/* end - WooCommerce Products block  */
```

**Comment by kriskarkoski** [comment]
@ktyfuller604 @mikeicode I think this may be fixed now but want to be sure I'm testing it properly. I published a page with the Newest Products block. I have 4 published products and set it to 4 columns and 2 rows and all 4 appear in one row in Safari https://k2businesstest.wpcomstaging.com/newest-products/

Can you check if that understanding is correct and if it seems to be fixed now. Thanks!

**Comment by mikeicode** [comment]
@kriskarkoski  That's the correct issue you were testing. I tested all the columns from 3-6 now and they work correctly in Safari. I'll close this issue.
