### ISSUE TITLE
Domains: Change Site Address confirmation modal icon alignment

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36010]
<img width="444" alt="Screen Shot 2019-09-05 at 5 08 12 PM" src="https://user-images.githubusercontent.com/2124984/64381390-12c5ac00-d001-11e9-88c1-e297ad4a050c.png">

The red and green X and checkmark icons could better vertically align with their text counterparts. They're riding a bit high right now.

To find this panel, go to Domains -> Click on a site -> Scroll to Change Site Address. Input an available site address and click Change Site Address.

**Comment by Aurorum** [comment]
PR for this issue in #36050. :)
