### ISSUE TITLE
FSE: Replace the default header image with a retina version

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#36017]
Replace this placeholder image that is fuzzy on HiDPI with the maywood header image

<img width="371" alt="Screen Shot 2019-09-05 at 6 49 55 PM" src="https://user-images.githubusercontent.com/1464705/64395118-ff6d0d80-d00d-11e9-9f87-0b786d835e49.png">

Not a blocker, but it looks sloppy and should be a simple URL update.

**Comment by apeatling** [comment]
New image URL https://maywooddemo.files.wordpress.com/2019/08/maywood-logo.png

**Comment by Copons** [comment]
![](https://modernbusinessdemo.files.wordpress.com/2019/06/logo-modern-3.png) is the Modern Business' logo, which is still being used for Maywood for ease of testing until we switch the template data fetching from `modern-business` to `maywood`.

Now, Maywood apparently doesn't have a logo?
Or, at least, it's not used in the [Maywood Demo site](https://maywooddemo.wordpress.com/), but only pops up in the [theme instructions](https://wordpress.com/theme/maywood#logo) (and that very hi-res version is in fact uploaded and available in the demo site).

Once we have a Maywood "data" site (might it be the demo site, or a new one as we did for Modern Business), we can either keep the template data without placeholder logo, or add it using the hi-res one (cc @iamtakashi for opinions).

Either way, I think it's fair to say this doesn't really need an issue per se, as it's part of our current sprint goals (paYKcK-dN-p2), and will be solved for free once we complete this:
> - Cleanly providing FSE theme support for Maywood and future themes.
>   - Includes making sure the template population is backed from the related demo site.
