### ISSUE TITLE
FSE: Overlap on homepage template

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#36019]
In editor:

<img width="1206" alt="Screen Shot 2019-09-05 at 7 02 41 PM" src="https://user-images.githubusercontent.com/1464705/64395652-da799a00-d00f-11e9-9ccc-e6d9e76c7760.png">

On front end:

<img width="1049" alt="Screen Shot 2019-09-05 at 7 03 42 PM" src="https://user-images.githubusercontent.com/1464705/64395686-f3824b00-d00f-11e9-8a75-ef3850d9bf46.png">

**Comment by iamtakashi** [comment]
I had a look at this, and this is an issue with the conflict between the themes and the newly introduced height setting in Cover block in 6.4. We're working on the themes to remove the minimum height that's been set in the theme in a less destructive way at the moment.

**Comment by iamtakashi** [comment]
Are we keeping 6.4 in Horizon or revert back to 6.2?

**Comment by apeatling** [comment]
cc @kwight ^
