### ISSUE TITLE
Cart: Empty cart square inner div overrides cart's rounded corners

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36012]
When viewing an empty cart, you'll notice the rounded corners get overridden by a white box:

<img width="347" alt="Screen Shot 2019-09-05 at 5 32 47 PM" src="https://user-images.githubusercontent.com/2124984/64383355-c334af80-d003-11e9-8274-b5eee7acc411.png">

For comparison, here's a cart with items in it to see how it should look:

<img width="340" alt="Screen Shot 2019-09-05 at 5 33 06 PM" src="https://user-images.githubusercontent.com/2124984/64383227-badc7480-d003-11e9-8fa7-f2823010637f.png">

You can find the cart on the Domains or Plans pages. To see the problem, remove any existing items from the cart. To see how the cart should look, add a Plan to the cart, then exit checkout without checking out.

**Comment by Aurorum** [comment]
PR in #36042 for this issue. :)

**Comment by sixhours** [comment]
Thanks much @Aurorum ! Can you hold off on any more PRs for issues on this board (anything marked "Grand Meetup - Fixing the Flows") for the next week? We're holding these for the company meetup as "quick fixes" to introduce new folks to the contribution process for Calypso. :D

**Comment by Aurorum** [comment]
Ahh, I didn't realise that, sure thing. :)

**Comment by sixhours** [comment]
No worries at all, we really appreciate your speedy work. :)
