### ISSUE TITLE
Post Checkout: Dangling word ("widow") in first sentence

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36029]
<img width="996" alt="screencapture-wordpress-checkout-thank-you-calobeetesting07-food-blog-39989612-2019-08-27-11_37_16" src="https://user-images.githubusercontent.com/2124984/64430107-87dac500-d085-11e9-91a8-cde4adb07936.png">

Note "excitement!" is hanging out on its own line. We should wrap this sentence in `preventWidows()` to add a non-breaking space between the last two words. It may also be worth looking at the other cards/components on this page to make sure there are no other widows as well.

To see this screen, complete the checkout process with a plan.

**Comment by rcoll** [comment]
@sixhours Presumably this is fixed in https://github.com/Automattic/wp-calypso/pull/36070 however I've been unsuccessful in testing this (Can't seem to get this particular page to appear). Can you respond with specific instructions on how to get to this screen from wordpress.com?

Thanks!

**Comment by bluefuton** [comment]
@rcoll the steps to repro may be the same as #35371:

1. Start on a plan lower than Premium
2. Upgrade to premium plan
3. View CTA on success page
