### ISSUE TITLE
Pages: Make references to "Blog Feed" consistent

### ISSUE THREAD

**Issue by lcollette** [Automattic/wp-calypso#36023]
<img width="1059" alt="Screen Shot 2019-09-05 at 11 18 01 PM" src="https://user-images.githubusercontent.com/181733/64405474-145c9780-d034-11e9-9bc4-327a2b66d8b4.png">

Blogs Posts, Blog Feed, Posts Page all refer to the same thing. Can we pick one and update the copy to that choice?

It might be wise to search across WP.com for other references to Blog Feed/Blog Posts/Posts Page and update those as well.

**Comment by rcoll** [comment]
I'm afraid that the text for "Blog Posts" and "Blog Feed" referenced in the screenshot above are both the names of pages created on that site. They're not actually copy we can change in Calypso. As for the third referenced text for "latest posts", I'm hesitant to change that in any way since it is an accurate representation of what it is.

**Comment by mattsherman** [comment]
I think that really addressing this issue involves rethinking how the "Blog Posts" page is set in Calypso. My team was involved in the Calypso implementation of this... it seemed like a reasonable design at the time, but I don't think it is clear at all.

**Comment by lcollette** [comment]
> I think that really addressing this issue involves rethinking how the "Blog Posts" page is set in Calypso.

@mattsherman Completely agree. 

Maybe this is a crazy idea but if we can't have consistency in naming, how about we remove the Blog Posts callout at the top?

**Comment by mattsherman** [comment]
> Maybe this is a crazy idea but if we can't have consistency in naming, how about we remove the Blog Posts callout at the top?

Hmm, tough call. I question the value of the Blog Posts callout at the top, so I would lean towards just removing it. But, if a site has a lot of pages, then the callout at the top could be useful.

It would be interesting to know how frequently users make use of the related "Set as Homepage" and "Set as Posts Page" functionality on this screen, which could help us determine whether the callout may be valuable. Unfortunately, there doesn't appear to be Tracks events logged for these.

Just thinking out loud here... What about removing the "Blog Posts" title from the callout, and adding some sort of an "info" icon in front... rough idea...

<img width="756" alt="ScreenCapture at Sat Sep 14 10:24:35 EDT 2019" src="https://user-images.githubusercontent.com/2098816/64909436-ff3dd380-d6d9-11e9-9923-abd2b2d6ae12.png">

**Comment by lcollette** [comment]
This is a really nice interim solution. I like how you've deemphasized the call-out. Thank you for putting thought into this issue!

>It would be interesting to know how frequently users make use of the related "Set as Homepage" and "Set as Posts Page" functionality on this screen

Yes! Let's set up Tracks events so we can see where we stand on usage. Perhaps also add a tracks event to the call-out at the top.

**Comment by mattsherman** [comment]
@chickenn00dle @lcollette  I'll create a separate PR to add the Tracks events.

**Comment by chickenn00dle** [comment]
Submitted a PR for this here: https://github.com/Automattic/wp-calypso/pull/36129

I agree it might be best to keep the callout but remove the title, making it a sort of info callout.

**Comment by michaeldcain** [comment]
I hate to delay this since there's already a PR, but I don't know that this card is worth keeping around at all. We already indicate homepage and blog page settings in the page list, and the current card just links to the front-end blog feed (duplicated by the functionality of clicking the title of that page inside the list).

![Screen Shot 2019-09-15 at 10 39 22 AM](https://user-images.githubusercontent.com/942359/64923145-3200ce00-d7a5-11e9-8514-f80132a6cbd5.png)

Could we instead highlight those indicators using the "pill" method from #35241? @mattsherman might know of a reason that the card was initially added. @lcollette and @chickenn00dle thoughts? I can update the PR, or just review as-is.

**Comment by lcollette** [comment]
Thanks for weighing in @michaeldcain! If we've got the okay to remove the card, let's do it! 

I like the idea of using the pill to highlight those indicators though I'd like to see it in context with the updates from #36057 first.

**Comment by chickenn00dle** [comment]
Thanks for the suggestion @michaeldcain 

I am also for removing the callout. I did notice that when your homepage is set to display your latest posts (the default in Homepage Settings in Customizer) there is no indicator for where your latest posts appear:

![page-list-post-callout_homepage-no-callout](https://user-images.githubusercontent.com/17905991/65301464-a1fec200-dbb2-11e9-940a-3c0da23abf2d.png)
 
Perhaps this is why this callout was added in the first place. I've submitted a commit to only add the callout for this case just to clarify to users where their blog posts are appearing:
https://github.com/Automattic/wp-calypso/pull/36129#issuecomment-533413519

Let me know what you think!

**Comment by sixhours** [comment]
This is a very rough mockup of the pill-button style for this screen, but you can see the exact CSS we used in the PR here:

https://github.com/Automattic/wp-calypso/pull/35241/files#diff-071cc0fdc73aa1a784e930b9bcbcc634R177-R185

<img width="597" alt="Screen Shot 2019-09-23 at 1 04 23 PM" src="https://user-images.githubusercontent.com/2124984/65446614-b9cc8500-de02-11e9-9c02-7cc35ad868b2.png">

**Comment by mattsherman** [comment]
> @mattsherman might know of a reason that the card was initially added.

This was added because if the site has more pages than can be shown without paging, the page set as the "Blog Posts" page may not be shown in the list yet.
