### ISSUE TITLE
FSE: Spacing with frontend cover image is too tight to header

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#36021]
This is with the homepage template:

<img width="934" alt="Screen Shot 2019-09-05 at 7 15 15 PM" src="https://user-images.githubusercontent.com/1464705/64396163-a606dd80-d011-11e9-9926-60406009ad1a.png">

**Comment by iamtakashi** [comment]
The vertical paddings of 48px have been overridden with FSE.

<img width="1042" alt="Screen Shot 2019-09-06 at 03 36 51" src="https://user-images.githubusercontent.com/908665/64397044-b3df5180-d057-11e9-9bf9-db57d45904ed.png">

**Comment by Copons** [comment]
Ah, I had no idea we hid the page title on the homepage... just on WPCOM...

https://github.com/Automattic/themes/blob/b40c5196eab8a650a7c85628c917f64e3433dae3/varia/inc/wpcom.php#L96

Basically what happens here is that on WPCOM we add the `.hide-homepage-title` to the homepage body, and then we add some style to hide it:

https://github.com/Automattic/themes/blob/b40c5196eab8a650a7c85628c917f64e3433dae3/varia/inc/style-wpcom.css#L5-L14

I didn't consider this case as testing locally wouldn't trigger this.

I'll come up with a fix ASAP!
