### ISSUE TITLE
Domains: Domain name missing on domain transfer hold page

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36043]
<img width="827" alt="screencapture-wordpress-domains-add-transfer-sixhourssandbox-wordpress-com-2019-09-06-12_48_38" src="https://user-images.githubusercontent.com/2124984/64456593-909bbd00-d0be-11e9-93ab-38aa306a2468.png">

#### Steps to reproduce
1. Starting at URL: `/domains/`
2. Go to Add Domain -> Use a domain I own -> Transfer to WordPress.com
3. Put in the URL of a domain that is not yet outside the 60-day transfer hold window (`calobee-testing.club` is the one I used)
4. Note the domain name is missing from the informational screen that follows. This happens with both my super admin account and a non-super admin account. 

#### What I expected

I expected to see "calobee-testing.club can be transferred in X days" and "calobee-testing.club was registered X days ago" in the heading/copy of this page.

#### What happened instead

The domain name does not appear in the heading or the copy.

#### Browser / OS version

Mac OSX, Chrome 76

**Comment by stephanethomas** [comment]
This will be fixed by https://github.com/Automattic/wp-calypso/pull/36086.
