### ISSUE TITLE
Gutenberg: UI elements float over the full-width open sidebar.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36045]
The core "hamburger" menu icon and Gutenberg's toolbar will float over top of an open sidebar, when that sidebar is full width because of a narrow screen size.

<img width="859" alt="Screen Shot 2019-09-06 at 4 19 07 PM" src="https://user-images.githubusercontent.com/349751/64465663-cd69b300-d0c2-11e9-8bb2-0a819d03b415.png">

These don't happen on standalone installations.

**Comment by gwwar** [comment]
Still an issue, make sure to uncheck the full-screen option in editor settings and resize to a small screen in /wp-admin to reproduce.

**Comment by Addison-Stavlo** [comment]
> make sure to uncheck the full-screen option in editor settings and resize to a small screen in /wp-admin to reproduce.

I am seeing this show up regardless of whether or not the full-screen option is checked.

**Comment by jordesign** [comment]
Closing this as it is no longer reproducible
