### ISSUE TITLE
Getting error while running npm start

### ISSUE THREAD

**Issue by dswebnaveen** [Automattic/wp-calypso#36048]
getting below error while running npm start
@automattic/babel-plugin-i18n-calypso: sh: 1: transpile: not found
@automattic/calypso-ui: sh: 1: transpile: not found
lerna ERR! npm run prepare exited 1 in '@automattic/babel-plugin-i18n-calypso'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-calypso@0.17.0 start: `npm run -s build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-calypso@0.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/naveen/.npm/_logs/2019-09-07T03_34_52_320Z-debug.log

#### Steps to reproduce
1. Starting at URL:
2.
3.
4.

**Comment by lilucool** [comment]
same issue

info cli using local version of lerna
lerna notice cli v3.18.4
lerna info versioning independent
lerna info Executing command in 11 packages: "npm run prepare"
(node:3256) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
@automattic/babel-plugin-i18n-calypso: sh: transpile: command not found
lerna ERR! npm run prepare exited 1 in '@automattic/babel-plugin-i18n-calypso'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-calypso@0.17.0 start: `npm run -s build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-calypso@0.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leoli/.npm/_logs/2020-01-08T04_01_52_478Z-debug.log

**Comment by nbloomf** [comment]
I started getting this error too, and was able to fix it with `npm run distclean && npm install`. Kudos to @sirbrillig for helping with troubleshooting. I'm still not sure what caused it.
