### ISSUE TITLE
Integration: CPT, Custom pages

### ISSUE THREAD

**Issue by andrewmclagan** [Automattic/wp-calypso#36058]
Apologies, not the correct forum.

My team are considering building a platform using wp-calypso as the backend for managing content, but also custom views for managing other non-Wordpress and semi-Wordpress resources.

The idea is; Rather then creating another backend in React to manage other resources and having calypso only manage pages/posts, we could have a unified experience. Wordpress as a headless CMS serving content to our fronted, with wp-calypso as the backend.

We are seeking general community advice to 
* the feasibility of this approach
* the maturity of wp-calypso 
* the ease of customisation 
* CPT integration
* ability to create custom views

We would be looking to also contribute heavily to the project, being a large-ish team of ~19.

**Comment by kriskarkoski** [comment]
Hi @andrewmclagan! Apologies for the wait, we missed your comment initially and are just catching it now during a bug scrub. As far as I am aware what you proposed should be feasible. wp-calypso interacts with the WP.com and WordPress APIs already so doing so in a headless fashion should already be mostly supported. If you haven't checked it out yet https://developer.wordpress.com/ is a good resource.

For CPT integration, there is some prior art in the integration of Portfolios and Testimonials from Jetpack that you could check out. 

I am going to close this issue but will be happy to answer any further questions you have!
