### ISSUE TITLE
Signup: Easy to create mysterious error message on first step

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#36052]
- Press enter on the email address input of the account creation step without filling out any other fields.
- The next step in signup will load and then you’ll be thrown back to the account creation step with a confusing and mysterious error message.

![image](https://user-images.githubusercontent.com/545779/64541962-557cd200-d2e8-11e9-9f92-8c19291b0e92.png)

Compare with an attempt to move forward by pressing enter when only the password input is empty.

![image](https://user-images.githubusercontent.com/545779/64542036-76ddbe00-d2e8-11e9-932c-86a428dfd8a1.png)

A "Don’t forget to enter a username." error message under the "Choose a username" input would be a better result than the loading-disappearing of the next step in signup followed by the mystery message above.

**Comment by michaeldcain** [comment]
I can no longer reproduce this issue - closing.
