### ISSUE TITLE
Checkout: Thank You: Fix the generic thank you page

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#3607]
We used to render a generic version of the thank you page at `/checkout/:site/thank-you`, to handle the case where the API didn't return a receipt ID. Currently, visiting it returns an error, and no thank you page is rendered.

We need to fix this, and remember to test that route when making changes to the thank you page.

**Comment by stephanethomas** [comment]
This will be fixed by https://github.com/Automattic/wp-calypso/pull/3622.

**Comment by BandonRandon** [comment]
Closing as resolved as #3622 has been merged.
