### ISSUE TITLE
The Customizer and the Theme Selector Use Legacy Colors

### ISSUE THREAD

**Issue by porada** [Automattic/wp-calypso#36096]
[Originally reported](https://github.com/Automattic/wp-calypso/pull/35949#pullrequestreview-285476271) in #35949.

<img width="1382" alt="Screenshot" src="https://user-images.githubusercontent.com/87168/64530793-a4d9f700-d316-11e9-83a5-deab3763ae53.png">

The colors should be updated with `calypso-color-schemes`.

**Comment by drw158** [comment]
Based on the report, it seemed like the main issue is with the 2 clashing blues — the masterbar blue (WP Blue) and the header background blue (Blue). Is the solution to change the header background to use WP Blue instead?

**Comment by porada** [comment]
Since those two are visually dependent on each other and the masterbar can use a different color depending on the active color scheme, I’d add a secondary color property to the masterbar theme properties and use it for that. In the default scheme’s case, yes, that would be WordPress Blue.

**Comment by Aurorum** [comment]
I proposed #36111, which makes the case that it might just be better to use the masterbar colour, unless there's a desire to change things to how they were before #35949 landed.
