### ISSUE TITLE
List Block: Add Color Options

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#36110]
#### What I expected
For [List Block](https://en.support.wordpress.com/wordpress-editor/blocks/list-block/) have color options, for example, like for [Paragraph Block](https://en.support.wordpress.com/wordpress-editor/blocks/paragraph-block/#color-settings).

#### What happened instead
No color options are available in the right-hand side panel

#### Screenshot
![](https://cld.wthms.co/1Bd0Od+)
_Link: https://cld.wthms.co/1Bd0Od_

#### Context / Source
#user-report in 2348563-zen

**Comment by kylemcph** [comment]
Another request here: 16548010-hc

**Comment by david-szabo97** [comment]
Added by https://github.com/WordPress/gutenberg/pull/21387
It will be available from Gutenberg 8.9.0

**Comment by david-szabo97** [comment]
Closing, this feature is now available.
