### ISSUE TITLE
Pages: Expand search scope from one tab to all tabs

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#36121]
This is the exact same issue as https://github.com/Automattic/wp-calypso/issues/36057, but for pages rather than posts.

**Comment by kriskarkoski** [comment]
Confirmed this is still an issue for pages. I added a draft titled Test, then searched from the Published tab for Test and it returned no results.

**Comment by millerf** [comment]
I'll try my luck with it 👍

**Comment by DavidRothstein** [comment]
I am so sorry -- I apparently never pushed the in-progress work I had for this in September up to GitHub.

I rebased it and pushed it now: https://github.com/Automattic/wp-calypso/pull/40148

I don't remember exactly where I left off, exactly, but I'm sure there were things left to do and that the code is somewhat outdated now.  @millerf Feel free to take a look and borrow or modify or completely change/replace any of it as part of your pull request.  Thanks for working on this!

**Comment by millerf** [comment]
@DavidRothstein At least I can see I was on the right track :)

It seems to be working fine, and I don't see much room for improvement... Or maybe some refactor to merge both page and post behaviours somehow...

**Comment by gwwar** [comment]
closed by https://github.com/Automattic/wp-calypso/pull/40464
