### ISSUE TITLE
Centering Banner icons on Settings > Performance page

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/wp-calypso#36130]
Banners are designed to have the icon at the top but when viewing on mobile maybe it could be centered to look a little more uniform I think. 

Now

<img width="461" alt="Screen Shot 2019-09-14 at 11 46 04 AM" src="https://user-images.githubusercontent.com/6520461/64910520-44b3ce00-d6e5-11e9-9384-d32ee806120a.png">

Proposal

<img width="554" alt="after 1" src="https://user-images.githubusercontent.com/6520461/64910522-4ed5cc80-d6e5-11e9-8969-884ce2413086.png">

We can do this by adding

```
flex-direction: column;
justify-content: center;
```

to `.banner__icon-plan` 

Originally raised in #36125

**Comment by synora** [comment]
Closing since this was merged in https://github.com/Automattic/wp-calypso/pull/36125.
