### ISSUE TITLE
My Plan: Monetize card not present on atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36198]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/my-plan/
2. Look for the "Monetize" card tile.

#### What I expected
The section is present on simple sites, so expected to see it here on this page.

#### What happened instead
The section is not present.

#### Screenshot / Video
Screenshot Simple --  https://cloudup.com/cOeBemj_d_p
Screenshot Atomic -- https://cld.wthms.co/WbNV9V

#manual-testing

**Comment by gwwar** [comment]
Please reopen if this is still an issue, but I see this card for atomic/simple
<img width="465" alt="Screen Shot 2020-01-30 at 12 32 05 PM" src="https://user-images.githubusercontent.com/1270189/73487812-98554a00-435c-11ea-945c-5489d6053258.png">
