### ISSUE TITLE
Feedback: Incoherent UI between simple and atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36199]
#### Steps to reproduce
1. Starting at URL: https://DOMAIN/wp-admin/edit.php?post_type=feedback
2. Look for options on the left sidebar on the screen.

#### What I expected
Expected the options in both simple and atomic sites to be the same.

#### What happened instead
The options are different, and confusing on atomic sites since they list other plugins.

#### Screenshot / Video
Screenshot Simple --  https://cloudup.com/ctt2-9vtAP4
Screenshot Atomic -- https://cloudup.com/cgEheJMwQJT

#manual-testing

**Comment by davipontesblog** [comment]
@obenland is Feedback a wp-admin page in Nav unification? If so we can close this issue as they would be the same in simple and atomic then.

**Comment by obenland** [comment]
It is, yes. Sounds good, thanks!
