### ISSUE TITLE
Import: Possible memory leak in author mapping page

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#36200]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/people/new/[ SITE ], add 11 users to your test site.
2. Go to https://wordpress.com/import/[ SITE ] and click on an import type, and upload an import file which contains a couple of hundred posts by at least 12 authors.
3. The importer will process the import file and then go the author mapping page, showing a list of authors in the import, with a dropdown list allowing you to map each to a user in your test site.

#### What I expected
Each dropdown should show all users in my test site, and I should be able to select a user from each for each author in the import.

#### What happened instead
Not all users are shown in the dropdowns, and after a while the page freezes. The JS console shows the message `MaxListenersExceededWarning: Possible EventEmitter memory leak detected.`

#### Browser / OS version
Firefox 69 macOS Mojave

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/1647564/65256458-79fe5880-daf7-11e9-89f1-b9879e9b45bf.png)

![image](https://user-images.githubusercontent.com/1647564/65256523-91d5dc80-daf7-11e9-99fd-c737186bce2a.png)

#### Context / Source

This happened in the context of a large Medium import with 382 posts and 12 authors. The import works fine on a site with only one user, but not on a site with 12 users.

#reallife

p1568902140002300-slack-CBZ6ZM3DW

**Comment by JoshuaGoode** [comment]
Initially discovered on 2358176-zen

Discussed  in p1568902140002300-slack-calypso-importers

**Comment by andfinally** [comment]
There's a similar workaround that doesn't require you to remove the users – you can set all but about 4 of them authors to be Viewers. The author mapping page will only show users who can author posts. After doing the import you can change them back to their original roles and reassign their posts using multi-select in the wp-admin Posts list.

**Comment by kylemcph** [comment]
Another report of this while working on #2412175-zen.

The workaround was import content to a site with one author, assign all posts to that author, then export that content to the intended destination, and manually assign posts to the correct user.

**Comment by lancewillett** [comment]
Closing as wontfix ("mayb later").
