### ISSUE TITLE
Full Site Editing: Update scripts dependencies for Gutenberg 6.5

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#36206]
As reported in p7H4VZ-2jE-p2, a breaking change on how the scripts dependencies are generated has been merged in Gutenberg 6.5: https://github.com/WordPress/gutenberg/pull/17298.

We should be ready to update this part of the FSE class as suggested in the P2:

https://github.com/Automattic/wp-calypso/blob/00ac5a72fd3c3bb12f35c305fbb296da30978e97/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L161-L173

**Comment by vindl** [comment]
@kwight what's the planned date for landing Gutenberg 6.5 on Dotcom?

**Comment by kwight** [comment]
Working on it, it's top priority for this sprint. We need to get these e2e tests all passing one way or another: https://github.com/Automattic/wp-calypso/pull/36142 (WP.com tests are clean for 6.5).

**Comment by Copons** [comment]
After a deeper look, I don't think this is a blocker, but something that we can do at our own pace.

My initial understanding was that Gutenberg 6.5 had some breaking changes on the dependencies extraction script that, once we had upgraded Gutenberg, it would have broken FSE.

In fact, though, our `calypso-build` script does not depend on Gutenberg, but uses a [fixed version](https://github.com/Automattic/wp-calypso/blob/bd40b88837c2fc985f8a2fc69511d21285d997aa/packages/calypso-build/package.json#L48) (currently 1.1.0) of the `@wordpress/dependency-extraction-webpack-plugin` package.
Gutenberg 6.5 updates it to 2.0.0, which yes it's a breaking change, but as long as we don't update the script, it won't affect us.
Even updating the script won't break already-built versions of FSE.

Since `calypso-build` is used by many different teams (and even inside FSE, it's used in all three "sub-plugins"), I feel wary of updating it by myself without knowing all the implications.

I'd suggest to remove the blocker label from this issue, and move it away from the FSE 10% Test milestone and from our current sprint, and back into the backlog.
We can then tackle this when @Automattic/team-calypso will update the `@wordpress/dependency-extraction-webpack-plugin` version to 2.x (we'll probably notice something is wrong, as FSE will have broken dependencies and whatnot).

What do y'all think?

**Comment by Copons** [comment]
Note: this will be fixed by https://github.com/Automattic/wp-calypso/pull/36583

I haven't added the `Fixes` line to the PR so that if by any chance our build command breaks we still have this issue to remind us what the problem might be. 🙂
