### ISSUE TITLE
Update mocking in Functional Test suite to mock `BlockPreview` directly and remove the pass-through component.

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#36210]
Currently the test suite needs to mock out the `BlockPreview` component as it introduces a tonne of "noise" and complexity into the test which isn't part of the component under test. We isolate it by mocking it and returning a simple component which acts as a placeholder.

However, because Calypso doesn't allow us to redeclare `@wordpress/components` as a dependency of the app (this is provided at the root `package.json`) we cannot mock it using Jest. Therefore we create a pass-through component `block-preview.js` which simply proxies everything through to the `BlockPreview` component from Core. Because this pass-thropugh component is in the app itself we _can_ mock it easily.

If/when we migrate away from Calypso we can declare the dep and mock the node module directly thereby removing the requirement for the pass-through component.

**Comment by obenland** [comment]
p1571151852433800-slack-ajax.
