### ISSUE TITLE
(5P) SPT: Update thumbnails with inner "confirm select" buttons

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#36235]
Design: https://github.com/Automattic/wp-calypso/issues/35248#issuecomment-524016960

Mobile behavior should stay the same.  Also see https://github.com/Automattic/wp-calypso/issues/35887

See https://github.com/Automattic/wp-calypso/issues/35248

**Comment by obenland** [comment]
![template transitions](https://user-images.githubusercontent.com/191598/63538812-ab7b0880-c4e6-11e9-9723-8fe55459b1b0.gif)

**Comment by obenland** [comment]
@shaunandrews During planning the question came up where the central select button should go. Should that be maintained, or are we switching to in-thumbnail buttons only?

**Comment by getdave** [comment]
Closely related to https://github.com/Automattic/wp-calypso/issues/35887

**Comment by obenland** [comment]
Closing in favor of #36323.
