### ISSUE TITLE
Full Site Editing: Create an FSE test suite

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#36238]
We currently have a Full Site Editing test inside the Site suite (`/isolated/suites/Site/SiteFullSiteEditingTest.php`).
We should pull it out the Site suite and into its own.

Also, we should add appropriate tests to track the transformations happening when merging templates and posts, to be sure that there are no regressions and everything works as expected on the front end. (See https://github.com/Automattic/wp-calypso/pull/36026#discussion_r322407991)

**Comment by noahtallen** [comment]
This has been done and there is an fse suite in TC.
