### ISSUE TITLE
Classic Editor: Drop zone needs additional fine-tuning for colors

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36239]
The normal state has been mostly fixed by #36074, but the hover state (white text on a light pink background) fails AA contrast checks:

<img width="488" alt="Screenshot 2019-09-13 at 16 27 27" src="https://user-images.githubusercontent.com/43215253/64894440-adf9f980-d671-11e9-8185-dd279efea7ba.png">

I'm also still seeing the gridicon in black instead of white in the latest version of Chrome for Mac:

<img width="281" alt="Screen Shot 2019-09-23 at 1 33 53 PM" src="https://user-images.githubusercontent.com/2124984/65448571-23e72900-de07-11e9-84fd-e6abfae11582.png">

To reproduce:

1) Add a new post or page in the Classic Editor
2) Open the Featured Image accordion menu and drag and drop an image over it
3) Note how the colors change when the image is dragged in and out of the drop zone

_Originally posted by @Aurorum in https://github.com/Automattic/wp-calypso/issues/31888#issuecomment-531389176_

**Comment by Aurorum** [comment]
> I'm also still seeing the gridicon in black instead of white in the latest version of Chrome for Mac:

I think that's a defect of #35949. I've proposed a fix for it (and a contrast boost on hover) in #36243 though :)
