### ISSUE TITLE
WP Admin: No link in simple sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36241]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/DOMAIN
2. Look for the "WP Admin" option on the left sidebar in calypso

#### What I expected
The option is available in both simple and atomic sites.

#### What happened instead
The option is only shown on atomic sites, not on simple sites. (Observation: Older simple sites WILL show WP Admin. This is just for sites from a couple of years ago and more recent).

#### Screenshot / Video
Screenshot Simple --  https://cld.wthms.co/CJfduL
Screenshot Atomic -- https://cld.wthms.co/hSIm0s

#manual-testing

**Comment by Aurorum** [comment]
I believe that this is intentional: #9764

**Comment by gwwar** [comment]
This one is intentional, but we can have product revisit.

**Comment by gwwar** [comment]
There's likely a general consensus is that Simple site users should be able to access wp-admin easily. Let's reverify, and if so, let's make the wp-admin link visible for all site types.
