### ISSUE TITLE
Editor: Interface is different between simple and atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36244]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/DOMAIN/PAGE_SLUG
2. Compare the editor interface between simple and atomic sites.

#### What I expected
We expect the interface to be the same, with button styling as well as tools behaving the same way.

#### What happened instead
Some elements of the Gutenberg editor are slightly different between simple and atomic. For example:
- "Featured Image", in "Document Tab".
- "Preview" button, on the top editor bar
- "Publish" button, on the top editor bar

#### Screenshot / Video
Screenshot Simple --  https://cld.wthms.co/LXeM4q
Screenshot Atomic -- https://cld.wthms.co/2hj4QH

#manual-testing

**Comment by gwwar** [comment]
Closing this out since we should be running the same Gutenberg version on Simple/Atomic (though might be out of sync for ~1 day each update cycle.) If folks spot specific issues, please file a new issue and ping the create focus.
