### ISSUE TITLE
My Sites: Slide-out panel only on atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36240]
#### Steps to reproduce
1. Starting at URL: https://DOMAIN
2. Click on "My Sites" on the top left corner

#### What I expected
Users expect to see site admin options here, and for this experience to be the same whether on simple or atomic sites.

#### What happened instead
On simple sites, this takes you into calypso, at https://wordpress.com/stats/day/DOMAIN. On atomic sites though, this shows a calypso panel that slides in, which redirects to the WP.com dashboard (full calypso). Depending on which item you select from the slide-out panel, it takes you to a different spot in calypso. This seems like an unnecessary extra step to get into calypso, and incoherent with the simple site experience.

#### Screenshot / Video
Screenshot Atomic -- https://cld.wthms.co/JP6bi1

#manual-testing

**Comment by AtrumGeost** [comment]
Had a user who reported this is a confusing experience since the slide-out panel doesn't match the panel/menu on the WordPress.com dashboard.

15748514-hc

**Comment by gwwar** [comment]
@AtrumGeost let's capture that in a separate issue. There is a general problem with the My-Sites sidebar in wp-admin needing to be manually kept up to date and this is a big pain point.

This issue mainly needs a product decision on consistent behavior here.

**Comment by obenland** [comment]
Closing in favor of 186-gh-Automattic/dotcom-manage
