### ISSUE TITLE
Search sites -input in sidebar visually broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#36261]
When opening the sidebar and searching for sites, the input is visually broken in both focused and unfocused states:

![image](https://user-images.githubusercontent.com/87168/65513643-4ac75d00-dee4-11e9-8a69-934145c2cab2.png)

![image](https://user-images.githubusercontent.com/87168/65513615-371bf680-dee4-11e9-8aa1-e480d2401bef.png)

Removing `line-height:3` seems to fix it:

```css
.search__input[type=search] {
    line-height: 3;
}
```

Tests in both the latest Chrome and Firefox.

cc @Automattic/team-calypso due CSS refactoring and depends on the order of bundles loaded?

**Comment by sixhours** [comment]
Found another side effect of #36190 when using the search for Pages or Posts:

<img width="967" alt="Screen Shot 2019-09-24 at 4 01 01 PM" src="https://user-images.githubusercontent.com/2124984/65546422-7e56b700-dee5-11e9-909e-ef0d5bd55e01.png">

The black underline from the header cake selected tab styles overflow into the search box.

**Comment by sixhours** [comment]
Wondering if it would be better to revert #36190 since the bug it fixes is less noticeable than the visual bugs it created. What do you think @ramonjd ?

**Comment by ramonjd** [comment]
Good call @sixhours 

I'll prepare a patch. Sorry for that.

**Comment by ramonjd** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/36282
