### ISSUE TITLE
Video Widget: Not accepting YouTube URL as valid

### ISSUE THREAD

**Issue by vajrasar** [Automattic/wp-calypso#36262]
The Video Widget, when used with the option of "Insert URL", does not accept YouTube video URL as valid and throws an error. The same YouTube video gets easily embeded with YouTube Block. 

#### Steps to reproduce
1. Add Video Widget in Sidebar
2. Opt to Add Video
3. Click on "Insert URL" on left side
4. Insert YouTube video URL

Example: https://www.youtube.com/watch?v=e1IiGdB2gxM

#### What I expected
The video should show up, as the message says that we can "add a video from YouTube, Vimeo, or another supported provider".

#### What happened instead
The error shows up asking to provide a valid URL.

> Sorry, we can’t load the video at the supplied URL. Please check that the URL is for a supported video file (.mp4, .m4v, .webm, .ogv, .flv) or stream (e.g. YouTube and Vimeo).

#### Browser / OS version
- Chrome  76.0
- FF Quantum 69.0
- macOS Mojave 10.14.6

#### Screenshot / Video

![image](https://razzmtazz.blog/wp-content/uploads/2019/09/Screenshot-2019-09-24-at-5.25.01-PM.png)

![image](https://razzmtazz.blog/wp-content/uploads/2019/09/Screenshot-2019-09-24-at-5.24.46-PM.png)

[This](https://personal01.blog/2019/05/30/test-post/) is the Test Post, where the same video is embedded.

#### Context / Source
#manual-testing #user-report

**Comment by kathrynwp** [comment]
Does not appear to be a Calypso issue. Reported in 8153-wpcom
