### ISSUE TITLE
FSE: Cleanup Atomic eligibility check

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#36273]
As a follow up to #35463, we need to clean up the Atomic eligibility check. Feedback we got from systems indicates that a user could do stuff to their Atomic site which affects their options (and as a result, the option we add for Atomic eligibility). We don't have full control over site data on the remote Atomic site, so the goal of this issue is to rely on something we do have full control over.

For context:
* p9o2xV-vy-p2 (initial discussion)
* pMz3w-ahn-p2 (see comment with feedback from systems)
* p1HpG7-7yf-p2 (see comment with feedback from Jetpack team)

The main suggestion from those p2s is that we could use a API call to check eligibility instead of transferring an option. I think this API call would go in wpcomsh. See this PR for the code which handles this: 320-wpcomsh. I did some investigation for implementing this. After a site gets transferred, you can still check for blog stickers on the site on wpcom (I assume this is based off of the shadow site). You cannot do the check on the remote site, but we could create a wpcom endpoint which checks if the shadow site has the blog sticker. Then we use the result in the eligibility/fse disable filter to disable FSE on the remote site.

 **Note: When implementing this, be sure to remove the Atomic transfer changes we added in D32425-code**

**Comment by davipontesblog** [comment]
@noahtallen is this issue still relevant? I am closing it for now since it's linked to a Merged PR.

**Comment by noahtallen** [comment]
@davipontesblog thanks for closing all of these issues! I'd rather them be closed and we reopen if needed 👌 

I will reopen this one because we may need to do some related work on this for core-fse-on-dotcom :)
