### ISSUE TITLE
Hosting: Redux and API fetch boilerplate

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36284]
Did we add new APIs? This is a great chance to learn about:
- Our data layer and wpcom-http layer https://github.com/Automattic/wp-calypso/tree/master/client/state/data-layer/wpcom-http
- If needed, setting up a redux store and the associated wiring.

Note that if we don't interact with data, and it's read only, `getHttpData` may be a better choice https://github.com/Automattic/wp-calypso/pull/24951 

This is a placeholder task, so please split out work across many PRs as it makes sense. @gwwar will be available to pair or answer questions as folks run into issues.

**Comment by jeraldjuice** [comment]
I'm keeping this issue active until we've gotten to the point that the API is merged in and stripped out the dummy data. 👍
