### ISSUE TITLE
Hosting: Restore Database Password Button [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36283]
<img width="627" alt="Screen Shot 2019-09-24 at 4 34 21 PM" src="https://user-images.githubusercontent.com/1270189/65558423-7e59b580-deeb-11e9-8201-8e33dcdeb3b4.png">

It's pretty common for folks to follow tutorials online, with one of the first tasks being resetting the database password. This will break their database access since that is set at the environment level. In the Database Access card, also offer a button to reset the database password to account for this case.

When folks pick up this task, please consult the Serenity and team Atomic before diving in.

**Comment by brandonpayton** [comment]
Using the word "reset" confused me when I first learned about the feature, and I think it may confuse others. Maybe we should use a word like "restore" for the user-facing piece.

**Comment by mmtr** [comment]
See p9o2xV-xk-p2#comment-1354 for info about the API endpoint we should use.

**Comment by glendaviesnz** [comment]
@brandonpayton does the fact that endpoint returns a job number indicate that this is an async process? Just wondering if on success we need to notify user that there may be a delay in seeing the restore, eg. "Your database password restore has been actioned and should be completed within the next {time_period}". Or is it a fast enough process that the user won't notice any delay?

**Comment by brandonpayton** [comment]
Hi @glendaviesnz , it is an async process that relies on the Atomic job queue. In practice, I think it should run quickly most of the time, but it's still a job in a queue. A message that acknowledges that seems reasonable to me.
