### ISSUE TITLE
Hosting: PHPMyAdmin login link generation [8]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36281]
<img width="627" alt="Screen Shot 2019-09-24 at 4 34 21 PM" src="https://user-images.githubusercontent.com/1270189/65557804-65e89b80-dee9-11e9-9769-01c0b4ccca82.png">

Clicking on "Access PHPMyAdmin" should open a new tab, to a view that looks like this:
<img width="842" alt="Screen Shot 2019-09-23 at 6 01 47 PM" src="https://user-images.githubusercontent.com/1270189/65557938-e0192000-dee9-11e9-8ce6-17bc27ec2448.png">

Work here involves:
* Creating the new wpcom API, potentially with a server to server call
* Making sure this approach has security signoff
* Verifying what role or capability we align access to. Unless folks note otherwise I think the admin role makes the most sense.

The login link should expire within a short timeframe for security purposes, so with Calypso being a single page application we may need to regenerate the login link.

cc @jmdodd or @jhnstn was the related atomic endpoint documented here P72Wkx-2iQ-p2 I don't think I'm seeing a related one just scanning the list.

**Comment by glendaviesnz** [comment]
Done in D34245-code
