### ISSUE TITLE
Hosting: SFTP Information Card and Database Access Card UI [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36280]
<img width="627" alt="Screen Shot 2019-09-24 at 4 34 21 PM" src="https://user-images.githubusercontent.com/1270189/65557723-2f128580-dee9-11e9-9fde-48f1d587436e.png">

This is a task for the UI pieces only. Feel free to put in dummy information for prototyping.

Please use Calypso components like https://wpcalypso.wordpress.com/devdocs/design/card appropriately. We may need new icon assets.

**Comment by apeatling** [comment]
Per @shaunandrews Let's use the outline version of the icons instead:

https://cloudup.com/cG3kHIj3xfd
