### ISSUE TITLE
Signup/Checkout: User is redirected to plans page instead of the checklist

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#36290]
One of e2e tests is failing — after sign up, Plans page is displayed instead Checklist:

![slack-imgs](https://user-images.githubusercontent.com/205419/65593428-b9fa8b00-df90-11e9-9691-6903ac150304.png)

Test name: Sign up for a site on a personal paid plan coming in via /create as personal flow in GBP currency @parallel
CircleCI execution: https://circleci.com/gh/Automattic/wp-calypso/432731
You can find screenshot/video in Artifacts tab > Container 1 > tmp > artifacts > screenshots > screenshots

**Comment by adamziel** [comment]
See C04S2FRPA-slack-p1569406985025900 for more context

**Comment by adamziel** [comment]
> Test started to fail when upsell nudge was introduced with this PR 
> https://github.com/Automattic/wp-calypso/pull/36035 Screenshot: https://425507-45936895-gh.circle-artifacts.com/1/tmp/artifacts/screenshots/screenshots/FAILED-EN-DESKTOP-can-then-see-the-onboarding-checklist-1567999018351.png(109 kB)
> https://425507-45936895-gh.circle-artifacts.com/1/tmp/artifacts/screenshots/screenshots/FAILED-EN-DESKTOP-can-then-see-the-onboarding-checklist-1567999018351.png
> Upsell nudge is not present anymore (I cannot find was it removed and when), but test is still failing on the same step (after submitting payment details), and this time with different error — Plans page is displayed instead Checklist.

CC @niranjan-uma-shankar

**Comment by Stojdza** [comment]
To test this just remove `.skip` from [this](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-signup-spec.js#L651) line and run e2e against PR.
