### ISSUE TITLE
Tools: Plugins, Import and Export sections redirect to wp-admin on atomic sites only

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36299]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Go to Tools > Plugins, or Import, or Export

#### What I expected
We expect to see a calypso page for the respective section we navigate to. This does not _always_ happen. See below.

#### What happened instead
No Calypso Equivalent in atomic sites (it redirects to wp-admin with calypsoified UI for the respective section - Import, Export, or Plugins). The interesting thing here is that if you happen to be on the simple site version of Plugins, Import, or Export, for example: https://wordpress.com/plugins/, and then go to "Switch Site" and pick an atomic site, you don't get redirected to the calypsoified UI for the respective section right away. Instead, you see a splash page with a button to take you to that page in wp-admin. This behavior is inconsistent with the flows in calypso as you only get this splash page by duplicating these steps described here. More on the screen recording linked below.

#### Screenshot / Video
Screencast recording showing this behavior on simple and atomic sites --  https://cld.wthms.co/93qjfu

#manual-testing

**Comment by lancewillett** [comment]
Thanks for logging this, @davipontesblog.

CC @Automattic/start-samus for any further background, notes, or pointing to prior work on the expectations for user experience.

**Comment by jordesign** [comment]
Closing this is it will/should be resolved by Nav Unification.
