### ISSUE TITLE
Settings: Site address does not appear for AT sites in General settings

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#36309]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Look for the “Site Address” section

#### What I expected
The section is present on simple sites, so expected to see it here on this page.

#### What happened instead
Site address appears in General settings only on simple sites, not AT sites.

#### Screenshot / Video

Simple site
<img width="764" alt="Screen Shot 2020-05-05 at 17 37 58" src="https://user-images.githubusercontent.com/66797/81128832-29f1cc00-8ef7-11ea-9443-d9c5005448e4.png">

Atomic site
<img width="750" alt="Screen Shot 2020-05-05 at 17 38 10" src="https://user-images.githubusercontent.com/66797/81128840-31b17080-8ef7-11ea-8064-af9160f9da10.png">

#manual-testing

**Comment by JoshuaGoode** [comment]
Confirming that this is still relevant but likely due to the fact that the site address cannot be changed when a site on the Atomic platform. https://github.com/Automattic/wp-calypso/issues/36301

**Comment by obenland** [comment]
Closing based on https://github.com/Automattic/wp-calypso/issues/36301#issuecomment-776702055
