### ISSUE TITLE
Domains: AT can't change site address

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#36301]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage/ 
2. Click site address

#### What I expected
I expected both simple and atomic sites to have the option to change the site address.

#### What happened instead
Simple sites have the option to change the site address (to a new free address). Atomic's .wpcomstaging.com URL is treated as a custom domain, and has only the DNS and Email options.

#### Screenshot / Video
Screenshot Simple — https://cloudup.com/cOHfKTWIujW
Screenshot Atomic — https://cloudup.com/cOX-dEeNw0k

#manual-testing

**Comment by klimeryk** [comment]
@aidvu, what do you think about this? I understand that most Atomic users probably always have a custom domain on their site and don't want to/care about the staging subdomain. But I can also see how they can be concerned with the previous name "leaking" through somewhere in the site's HTML or just for completeness' sake.
If it's an easy fix (maybe the backend supports this operation now?), then I'm happy to lift the restrictions in Calypso. If it's a more complicated change, then I'd vote for a wontfix (unless it's a frequent enough request from users).

Edit: related issue that seems to indicate that there are indeed some users that like/care about their free subdomain on Atomic sites: https://github.com/Automattic/wp-calypso/issues/36662

**Comment by aidvu** [comment]
I think this is a `wontfix`. We rarely get these, and I don't think it's worth all the trouble it may cause with `siteurl/home` options.

**Comment by obenland** [comment]
Closing based on https://github.com/Automattic/wp-calypso/issues/36301#issuecomment-776702055
