### ISSUE TITLE
Settings: No option to delete content in General settings for AT sites

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#36315]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Look at the “Site Tools” section

#### What I expected
I would expect to see the same options on simple and AT sites.

#### What happened instead
Simple sites have the option to "Delete your content." AT sites do not.

#### Screenshot / Video
Screenshot Simple
![image](https://user-images.githubusercontent.com/1398304/110382286-88a03e80-800f-11eb-87bd-d2685ba17720.png)

Screenshot Atomic
![image](https://user-images.githubusercontent.com/1398304/110382298-8f2eb600-800f-11eb-9dda-70ee2aef19cd.png)

#manual-testing

**Comment by JoshuaGoode** [comment]
There was a discussion, at some point, to expose a site reset option to users. That could potentially help achieve some parity but would be a bit more than what is offered to Simple sites. 

Confirming that this is still a valid request and I'll share with the platform team.

**Comment by mpkelly** [comment]
As per this heads-up post, this feature is now available in Calypso. Closing this issue. 

p7DVsv-jA6-p2
