### ISSUE TITLE
Customizer: Different styling between simple and atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36317]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Go to Design > Customize

#### What I expected
We expect the look and styling of the Customizer to be the same between simple and atomic sites.

#### What happened instead
Button styles and color palette of the Customizer UI change on atomic site. Dropdown styling is different: Simple sites have a down carrot and AT sites have a double arrow.

#### Screenshot / Video
Screenshot Simple --  https://cloudup.com/c4VngUpzn9Q, https://cld.wthms.co/ZJHpYl
Screenshot Atomic -- https://cld.wthms.co/mPQxYa, https://cld.wthms.co/PVA6JS

#manual-testing

**Comment by gwwar** [comment]
Note that we can come close, but since we extend the customizer in wpcom (Simple), and Atomic sites may be affected by additional plugin styling, it won't be 100% matching for everyone.

**Comment by davipontesblog** [comment]
As per https://wp.me/p58i-8HP

**Comment by gwwar** [comment]
Closed by D402180-code
