### ISSUE TITLE
Settings: No option to set AT site to private

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#36311]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Look at the “Privacy” section

#### What I expected
I would expect to see the same options on simple and AT sites.

#### What happened instead
There is no option to set AT site to private.

#### Screenshot / Video
Screenshot Simple — https://cld.wthms.co/MnZdjO
Screenshot Atomic — https://cld.wthms.co/uCyDLR

#manual-testing

**Comment by poojashetty18** [comment]
This issue came up again where one of our users were not happy with this and stated this as such a difficult and is unnecessarily convoluted for such a simple setting. HC-15942133

**Comment by poojashetty18** [comment]
Another one HC-16937544

**Comment by gwwar** [comment]
Noting that this one is pretty large (project sized across multiple teams). @Automattic/zelda was there any ongoing work here?

Looks like some activity?
p9o2xV-Gc-p2
p9o2xV-Ac-p2

**Comment by lancewillett** [comment]
This feature is launching for Atomic sites very soon.

Work tracking here: https://github.com/Automattic/wp-calypso/projects/93
