### ISSUE TITLE
Settings: WordPress version appears only on AT sites, not simple

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#36310]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Look at the “WordPress version” section

#### What I expected
I would expect to see the same options on simple and AT sites. 

#### What happened instead
The WordPress Version section only appears on AT sites. Does it make sense to remove the WordPress version from AT sites, or add it to simple sites?

#### Screenshot / Video
Screenshot Simple — https://cld.wthms.co/oShnKt
Screenshot Atomic — https://cld.wthms.co/uCyDLR

#manual-testing

**Comment by gwwar** [comment]
🤔 I suppose we could display it, but we typically run latest WP and early RC versions on Simple Sites.

**Comment by lancewillett** [comment]
I'm going to close this one. The philosophy form Matt, for WordPress.com sites, is that the underlying software versions are not relevant to customers, much like Chrome. "Latest stable."

Based on that, we shouldn't reveal the exact version numbers for WordPress.org core running. It's always going to be the latest stable or RC (release candidate).
