### ISSUE TITLE
Settings: No option to change site address in General settings for AT sites

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#36313]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Look at the “Site Tools” section

#### What I expected
I would expect to see the same options on simple and AT sites.

#### What happened instead
Simple sites have the option to "Change your site address." AT sites do not. Related to this issue: #36301 

#### Screenshot / Video
Screenshot Simple — https://cld.wthms.co/MnZdjO
Screenshot Atomic — https://cld.wthms.co/uCyDLR

#manual-testing

**Comment by gwwar** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/36301
