### ISSUE TITLE
Customizer: CSS Mobile option not available on atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36322]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Go to Design > Customize > CSS

#### What I expected
I expected both simple and atomic sites to show the same options for CSS customization.

#### What happened instead
In Simple Site, in CSS, you have the option for "On Mobile" which lets you check off "Include this CSS in the Mobile Theme" -- this disappears in Atomic

#### Screenshot / Video
Screenshot Simple 
![image](https://user-images.githubusercontent.com/1398304/110383175-c782c400-8010-11eb-83fe-69c7605fe9c2.png)

Screenshot Atomic 
![image](https://user-images.githubusercontent.com/1398304/110383139-bdf95c00-8010-11eb-9918-11671817ebba.png)

#manual-testing

**Comment by davipontesblog** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/34798

**Comment by gwwar** [comment]
Weren't we planning on removing the Mobile theme @iamtakashi ?

**Comment by iamtakashi** [comment]
@gwwar I honestly don't know. I'm not very familiar with this.

**Comment by davipontesblog** [comment]
Quoting @SiobhyB on the related issue above:

Do we need to keep the "include this CSS in the mobile theme" option for simple WP.com sites? It doesn't appear for Jetpack-connected sites (including Atomic), and this disparity can cause some confusion. 

In addition, when more tech-savvy users enter CSS for the mobile theme, there's sometimes confusion around why it's not working (the option's disabled by default).

Is there any way to make the `.mobile-theme` selector work in custom CSS without selecting the "include this CSS in the mobile theme" option? If not, can it be enabled by default? 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize/
2. Navigate to the Customizer's CSS panel.
3. Scroll down to see the "include this CSS in the mobile theme" option.

#### Screenshot

<img width="301" alt="Screenshot 2019-07-20 at 14 56 38" src="https://user-images.githubusercontent.com/2998162/61578380-ae0ccb80-aafe-11e9-988a-2fe4113fa34d.png">

More discussion around [the documentation for the mobile theme](https://en.support.wordpress.com/themes/mobile-themes) in https://github.com/Automattic/en.support-docs-content/issues/381.

**Comment by obenland** [comment]
The mobile theme was deprecated in D57911-code. Would hiding this setting when the mobile theme is disabled be a satisfactory solution?

**Comment by davipontesblog** [comment]
> The mobile theme was deprecated in D57911-code. Would hiding this setting when the mobile theme is disabled be a satisfactory solution?

I think this would work well!

**Comment by obenland** [comment]
Fixed in r222431-wpcom.
