### ISSUE TITLE
FSE: Blocks within the post content block are sometimes shown with dashed borders

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#36329]
In a recent Gutenberg update a new feature was added that shows dashed borders around nested blocks when a parent block is selected. Since FSE uses a parent block to contain all the content-specific blocks — but hides all UI for this parent block — you can sometimes get into a state where it appears nothing is selected, but still showing the nested block outlines.

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/191598/65633288-bf180400-dfa9-11e9-9e72-fcc32b1bdc7c.png">

Since we've intentionally hidden the UI for the parent Content block, we should also hide the nested block outlines when the parent block is "selected."

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
