### ISSUE TITLE
Widget: Instagram widget not available on atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36324]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Go to Design > Customize > Widgets

#### What I expected
I expected both simple and atomic sites to have the same widgets available (other than any widgets added by external plugins on the atomic site).

#### What happened instead
The Instagram widget is not available on Atomic sites

#manual-testing

**Comment by creativecoder** [comment]
The Instagram widget was updated to work with Atomic sites earlier this year when dealing with the [Instagram API deprecation](https://www.instagram.com/developer/). Additionally, the [Instagram widget is now available in Jetpack](https://github.com/Automattic/jetpack/blob/master/modules/widgets/class-jetpack-instagram-widget.php).
