### ISSUE TITLE
Marketing: Connections - Eventbrite option not available on AT sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36326]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/marketing/connections/DOMAIN

#### What I expected
I expected both simple and atomic sites to show all options available for integrations.

#### What happened instead
Connections is almost identical—Only difference is Eventbrite which shows up on simple sites. The Eventbrite API plugin that a8c develops is the replacement for the missing sharing connection on AT, but it's not available here on this page.

#### Screenshot / Video
Screenshot Simple --  https://cld.wthms.co/JLGBsQ
Screenshot Atomic -- https://cld.wthms.co/GuiRE2

#manual-testing

**Comment by gwwar** [comment]
Closing this one due to p58i-8p5-p2 though explorers is working on a new block.
