### ISSUE TITLE
Marketing: Traffic - Toggle for Sitemaps not available on simple sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36334]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/marketing/traffic/DOMAIN

#### What I expected
I expected both simple and atomic sites to show the same options for sitemap toggle "on/off"

#### What happened instead
The section is not present on simple sites, only in AT ones.

#### Screenshot / Video
Screenshot Simple --  https://cld.wthms.co/c4vVlX
Screenshot Atomic -- https://cld.wthms.co/faAnNb

#manual-testing

**Comment by gwwar** [comment]
Probably a Jetpack only feature?

**Comment by lancewillett** [comment]
@gwwar is correct here. On non-Atomic sites sitemaps are always on (no option to disable).

<img width="972" alt="Screen Shot 2020-03-29 at 10 04 26" src="https://user-images.githubusercontent.com/66797/77855344-aed52180-71a4-11ea-9ee6-4add42ff8f8b.png">
