### ISSUE TITLE
Marketing: Traffic - Duplicated "Ads" section in AT sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36331]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/marketing/traffic/DOMAIN

#### What I expected
I expected both simple and atomic sites to not show any "Ads" section here **since it's already presented in Tools > Earn**.

#### What happened instead
Simple sites have ad placement controls in calypso under Tools > Earn. Atomic sites have the same, and also show an "Ads" section under Tools > Marketing > Traffic that seems misplaced in the context of this calypso area.

#### Screenshot / Video
Screenshot Simple --  https://cld.wthms.co/w0HTVX
Screenshot Atomic -- https://cld.wthms.co/0lkFtl

#manual-testing

**Comment by davipontesblog** [comment]
Related:
https://github.com/Automattic/wp-calypso/issues/14489
https://github.com/Automattic/wp-calypso/issues/14807

**Comment by obenland** [comment]
Let's remove the Ads section in Tools > Marketing > Traffic for WoA sites

**Comment by mmtr** [comment]
This was fixed by https://github.com/Automattic/wp-calypso/pull/51689
