### ISSUE TITLE
Checklist: No guidance for the "Update your homepage" task

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#36338]
#### Steps to reproduce
1. On a new Simple Site, visit the checklist page `/checklist/{site}`
2. Click "Try it" on the "Update your homepage" task
3. I land in the editor for the Home page (though I might not immediately know that, since I may have not seen the editor before)

#### What I expected

- Guidance on what to do next to update my homepage.
- When I'm done updating the homepage, to go back to the checklist.

#### What happened instead

- I don't see any prompts about what to do in the editor.
- When I click back (upper left) I land on the Pages list, rather than back on the Checklist

#### Browser / OS version

Chrome / macOS

#### Screenshot / Video

<img width="1552" alt="Screen Shot 2019-09-25 at 15 57 26" src="https://user-images.githubusercontent.com/1699996/65639518-e1ac1c00-dfad-11e9-961b-49005bed32c4.png">

<img width="1552" alt="Screen Shot 2019-09-24 at 17 11 16" src="https://user-images.githubusercontent.com/1699996/65639535-ea9ced80-dfad-11e9-903b-6c40cd9a0cb9.png">

<img width="1552" alt="Screen Shot 2019-09-24 at 17 11 48" src="https://user-images.githubusercontent.com/1699996/65639555-f4beec00-dfad-11e9-815f-0260ede9e1ce.png">

**Comment by jancavan** [comment]
I think one issue here is also that when a user is looking around trying to figure things out, if they accidentally hover over blocks, there isn't enough feedback; there's a very faint gray vertical line that shows up on the left of each block, and a small plus sign.

**Comment by olaolusoga** [comment]
Is this being addressed with the new customer home work? @lcollette

**Comment by brookewp** [comment]
_I just ran into an issue with a user related to this task, but let me know if I should create a new issue._ 

**Context:** 
When a user has their homepage set to display latest posts, the checklist shows 75% complete: 

<img width="1062" alt="Screen Shot 2019-11-26 at 4 06 05 PM" src="https://user-images.githubusercontent.com/35543432/69678620-11da6e80-1074-11ea-8927-e1551a1f83d8.png">

When they click on "Start" or "View Checklist → Start" it brings them to the editor as outlined in OP.

However, they don't need to create a page if the homepage is set to latest posts. So the checklist shouldn't bring them to the editor if they have this setting. 

**User Painpoint:** 
The user was happy with their site's homepage but the 75% completion score & step to "Update your Homepage" task made them think they were missing a page/a step. 

**Possible solution?**
Perhaps there could be options in the checklist between creating a static homepage or keeping the posts showing on the homepage so they have a chance to obtain 100% completion.

**Comment by jancavan** [comment]
@brookewp Thanks for the report. I think that needs to be tracked as a separate issue.

**Comment by apeatling** [comment]
I think this is fixed by our work on 0-FSE and the flows there.

**Comment by gwwar** [comment]
The block-editor should now display a welcome modal. Closing this one out for now, but we're thinking through more options in future iterations.
