### ISSUE TITLE
Question: Gridicons\SocialLogos - How are index.jsx files for gridicon and social-logo generated?

### ISSUE THREAD

**Issue by afsheenirani** [Automattic/wp-calypso#3634]
#### Steps to reproduce
In the gridicon and social-logo component definitions it says that those files are auto-generated and should not be manually updated.
- wp-calypso/client/components/gridicon/index.jsx
- wp-calypso/client/components/social-logo/index.jsx

`/* !!!
IF YOU ARE EDITING gridicon/index.jsx
THEN YOU ARE EDITING A FILE THAT GETS OUTPUT FROM THE GRIDICONS REPO!
DO NOT EDIT THAT FILE! EDIT index-header.jsx and index-footer.jsx instead
OR if you're looking to change now SVGs get output, you'll need to edit strings in the Gruntfile :)
!!! */`

As part of #460 I am looking to introduce search/filter capability for Gridicons and SocialLogos and wanted to better understand this bit...

#### What I expected
I expected to search on the entire codebase for either one of the following three keywords to produce some results in order that I could inspect the logic of how these are generated.
1. index-header.jsx
2. index-footer.jsx 
3. Gruntfile

#### What happened instead
My search turned up no results.

#### Browser / OS version
N/A

#### Screenshot / Video
N/A

#### Subject Matter Experts
@apeatling @ehg @jasmussen @nb @alternatekev @mcsf @ockham @seear

**Comment by folletto** [comment]
We have a separate repo to manage that, and we still hadn't open sourced yet properly tho. Thanks for raising the question — we'll update here once it's done. :)

**Comment by afsheenirani** [comment]
@folletto - Thanks for the update...will watch out for any updates to this thread then. Cheers!

**Comment by folletto** [comment]
The Gridicons repository has just been put live, under a GPL license. :)
https://github.com/Automattic/gridicons/

:tada:

**Comment by afsheenirani** [comment]
@folletto - Thanks for the quick turnaround...really appreciate it!

**Comment by afsheenirani** [comment]
@folleto - I also don't see SocialLogo in the new repository. I'm guessing that is another repository as well. Any clue why they are kept separate?

**Comment by folletto** [comment]
Yes, unfortunately that's another one.

The reason it's separate it's because social logos are third party logos, not something we design, and are added in different ways. Sorry about that.

**Comment by jasmussen** [comment]
The Social Logos repo is also GPL, though! https://github.com/Automattic/social-logos

**Comment by afsheenirani** [comment]
Thanks @folletto and @jasmussen!
