### ISSUE TITLE
Full Site Editing: header and footer no longer visible on Dotcom

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36364]
Header and Footer template parts are no longer shown on newly created Dotcom sites.

1. Pre-sandbox the URL of the site that you are going to test.
2. Start the onboarding flow at https://horizon.wordpress.com/start/test-fse with a new user.
3. Select the business vertical.
4. Make sure to create a site with the URL that was sandboxed in step 1.
5. Notice that About and Contact page have been automatically populated, along with Header and Footer CPTs (you can verify this in `wp-admin/edit.php?post_type=wp_template`.
6. Open an existing page for editing or try to create a new one. The Header and Footer template parts are no longer visible.

When the page is first opened the Header area is shown with a loading spinner, but after that it just disappears.

**Comment by noahtallen** [comment]
Is this reproducible with the latest version of the FSE plugin synced? We had this earlier this week and https://github.com/Automattic/wp-calypso/pull/36228 should have fixed it, but that's not available on prod yet

**Comment by noahtallen** [comment]
I saw this in the console (not syncing FSE master). could be related

<img width="1528" alt="Screen Shot 2019-09-26 at 1 30 50 PM" src="https://user-images.githubusercontent.com/6265975/65722807-e7633980-e061-11e9-904a-37ecb0913255.png">

**Comment by vindl** [comment]
> Is this reproducible with the latest version of the FSE plugin synced? We had this earlier this week and #36228 should have fixed it, but that's not available on prod yet

Good point @noahtallen , I'll make sure to check with newer versions. 👍

**Comment by vindl** [comment]
@noahtallen thanks for the tip! It turns out that my files were not properly synced to latest during my testing. After updating them everything works fine now. Closing the issue as not reproducible.
