### ISSUE TITLE
Build: make translate returns success (0) after errors

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#3637]
#### Steps to reproduce
1.  Introduce an error in the source that will trip up webpack, e.g. `let borked = require('./non-existent-file.js');
2. Run `make translate` and check it's return value, e.g. `make translate && echo "make translate incorrectly succeeded"`

#### What I expected
`make translate` should:
- fail during the bundler step
- never call `get-i18n`
- return a non-zero value.

#### What happened instead
`get-i18n` is run, and the `calypso-strings file is generated using broken sources.
Both the bundler and get-i18n tools return 0 when they error, and the make target overall.  The bundler and get-i18n tools both return 0 on most errors.

#### Browser / OS version
OSX, Node 5.5.0

#### Screenshot / Video
![calypso_ _bash_ _158x95](https://cloud.githubusercontent.com/assets/5952255/13382786/e3974ee8-dec8-11e5-9f59-1897013ca022.jpg)

**Comment by alisterscott** [comment]
Confirming this is still an issue. @deBhal: is there a plan to merge that PR for this? #bugscrub

**Comment by deBhal** [comment]
That PR fixes get-i18n, but not this issue which is actually in webpack, so we should merge it, but it's pretty low priority.

To resolve this issue, we need to bubble the errors up from Webpack.  I had a look, but it was not at all obvious how to fix.  Webpack is configured to do fancy incremental building for hot reloading, and I couldn't figure out how to get the failure without wrecking the incremental building.

I'll try and find someone with stronger webpack-fu.

**Comment by deBhal** [comment]
So get-i18n is actually called `i18n-calypso` now, and passes on failures successfully, so #7068 is all we need to resolve this issue.

**Comment by ehg** [comment]
Should be fixed by #7068 now!
