### ISSUE TITLE
Full Site Editing: Classic editor WSOD

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36375]
When attempting to load a page on a site that has FSE enabled with a classic editor the WSOD appears.

This is a major issue for support, since HEs opening a customer site for the first time won’t be be automatically using the Block Editor.

I think we should force Gutenberg for all users on FSE enabled sites, regardless of usual per user per site opt-in preferences that we use to determine whether Gutenberg should be loaded.

More info and discussion in this post: paYE8P-8W-p2

**Comment by noahtallen** [comment]
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/35804. Will summarize everything there since there is already some conversation around this.
