### ISSUE TITLE
Settings: Writing - Media options not available in calypso in simple sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36374]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/writing/DOMAIN 
2. Go to "Media" section

#### What I expected
I expected both simple and atomic sites to show the same media options.

#### What happened instead
The media section only appears in atomic sites (background color and enabling carousel). These are options existent in simple sites, but not in calypso - you need to go to wp-admin to access them in WP Admin > Settings > Media.

#### Screenshot / Video
Screenshot Simple --  (WP Admin) https://cld.wthms.co/NuMwvR / (Calypso) https://cld.wthms.co/BAZVvY
Screenshot Atomic -- https://cld.wthms.co/tDTpJl

#manual-testing

**Comment by davipontesblog** [comment]
@obenland do you know if this is irrelevant now in the context of nav unification? I think we may be able to close this issue if that's the case.

**Comment by obenland** [comment]
Yes, Settings > Media will be accessible from both Calypso and wp-admin and will link to the wp-admin page with those settings.
