### ISSUE TITLE
Signup: Ability to create blank sites easily for HEs

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#36381]
Part of the Atomic downgrade process on WordPress.com involves creating a backup site. The process looks like:

- Create a new site on the account.
- Export from original site.
- Empty the new site.
- Import the original site data to new site.
- Hard revert old site.
- Import data back to original site from new site.

At this stage, the manual revert (downgrade) process is over.

It would be much easier if there is an option to create blank (without business/travel segment) sites in one click, without having to go through the full site creation flow. This eliminates one step (emptying the site) during the process.

cc @Automattic/zelda. Previously discussed at p7DVsv-7of-p2#comment-23484

**Comment by ramonjd** [comment]
Copied over from p7DVsv-7of-p2:
 
If this would be a useful feature, we could use much of the ground work from the escape hatch code.

See: https://github.com/Automattic/zelda-private/issues/128

In particular, the very sparsely-populated blank canvas (<code>m6*.json</code>) annotations

D31408-code

Perhaps we could introduce  a one-click site setup button, hidden behind a stage flag in https://github.com/Automattic/wp-calypso/blob/master/config/stage.json that sets up a free blank site and automatically skips the domain step (<a href="https://github.com/Automattic/wp-calypso/pull/34389" rel="nofollow">something for which we have the code too</a>).

**Comment by arunsathiya** [comment]
As I had mentioned on the other thread, one bonus would be an ability to automatically add a WordPress.com Business plan to such newly created sites. And, also, do not send a receipt to the user's email when that happens. 

This is totally optional request.

**Comment by michaeldcain** [comment]
> As I had mentioned on the other thread, one bonus would be an ability to automatically add a WordPress.com Business plan to such newly created sites. And, also, do not send a receipt to the user's email when that happens.

@arunsathiya: I think this would cause the scope to grow quite a bit. Let's start with the blank site flow and then go from there.

> Perhaps we could introduce a one-click site setup button, hidden behind a stage flag in https://github.com/Automattic/wp-calypso/blob/master/config/stage.json that sets up a free blank site and automatically skips the domain step (something for which we have the code too).

@ramonjd: would this be easier than adding a new `blank-site` Signup flow with just the user and domain steps? @arunsathiya is it a hassle to pick the simple site name for the backup site?

**Comment by arunsathiya** [comment]
>is it a hassle to pick the simple site name for the backup site?

Picking up a name is fairly easy. HEs normally follow this format: if site is `domain.wordpress.com`, we choose `domainbackup.wordpress.com` as a address for the backup site. It would be good to have an option/field to choose the site address normally as we do. Site name/title can be empty by itself, as mostly the task is around export-import of the site content and media library files.

**Comment by scruffian** [comment]
Could you use the flow at wordpress.com/start/developer?

**Comment by arunsathiya** [comment]
Interesting, I wasn't aware we had this path! That seems to work well, created a site `domainbackup.wordpress.com` with it, but the final stage of the flow takes me to a 404 page - 
https://wordpress.com/devdocs/welcome

<img width="1076" alt="Screenshot 2019-09-28 at 01 46 10" src="https://user-images.githubusercontent.com/18581859/65799479-d6194a80-e191-11e9-8753-939040192760.png">

I also noticed that this site is having the Twenty Sixteen theme with the default post and page. If these could be switched to the latest theme, Twenty Nineteen, or any template-first theme that we are moving to, and if the default post and page are removed as well, it would be great.

**Comment by ramonjd** [comment]
> would this be easier than adding a new blank-site Signup flow with just the user and domain steps?

I was riding on the assumption that, since we'd already tested skipping the domain step, and the code is there, it wouldn't be such a difficult endeavour.

> Could you use the flow at wordpress.com/start/developer?

This is a good idea. The redirect is easy enough to change I'd say, and if we can get the flow to honour query params, e.g., 

https://wordpress.com/start/developer/site?site-type=blank-canvas

That might do the business?
