### ISSUE TITLE
Classic editor: Gutenberg opt-in fails

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#36388]
When trying to switch to Gutenberg editor, nothing happens.

#### Steps to reproduce
1. Create a new free wpcom site
2. Navigate to create a new post in Calypso (`https://wordpress.com/post/SITE`)
3. You'll land in the classic editor, choose "learn more" from the notification that appears at the bottom of the screen:
    <img width="611" alt="Screenshot 2019-09-27 at 16 02 59" src="https://user-images.githubusercontent.com/87168/65771544-19979880-e141-11e9-867e-0044f45ecb6b.png">
4. Choose "try block editor" from the modal
    <img width="1212" alt="Screenshot 2019-09-27 at 16 03 52" src="https://user-images.githubusercontent.com/87168/65771555-23210080-e141-11e9-805e-efac5deea5a9.png">
5. Observe `/gutenberg` API call return status 500:
    <img width="969" alt="Screenshot 2019-09-27 at 16 06 07" src="https://user-images.githubusercontent.com/87168/65771572-2e742c00-e141-11e9-9278-53fbcc8ce425.png">
6. Nothing else happens; modal dissapears and you're in classic editor. No gutenberg when refreshing the page neither.

#### What I expected
- Get to Gutenberg

#### What happened instead
- Got classic :-(

#### Browser / OS version
Latest Firefox & Chrome

**Comment by simison** [comment]
Can't switch from wp-admin neither using this link:

<img width="929" alt="Screenshot 2019-09-27 at 16 20 59" src="https://user-images.githubusercontent.com/87168/65772457-e950f980-e142-11e9-84c2-2a173ae71c23.png">

**Comment by kwight** [comment]
@simison I can't replicate at all; newly-created sites for me are Gutenberg by default, and I can currently opt out and back in with no issues (which may be a [bug](https://github.com/Automattic/wp-calypso/issues/35033) in itself, but I digress). Any other hints?

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
