### ISSUE TITLE
Full Site Editing: create demo site for Maywood theme

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36386]
When transitioning from Modern Business to Maywood theme we never really created a separate demo site for it. This is not ideal since we are now fetching the template parts from the demo site of another theme, and these might not fit the structure that Maywood expects.

In order to resolve this we should move away from `fsemodernbusinessdemo.wordpress.com` and create a new demo site `fsemaywooddemo.wordpress.com`. This can be achieved by simply following the usual FSE demo flow. After that we should update the following:

- snapshot script in `bin/calypso/snapshot-fse-demo-data.php`
- FSE API endpoint `rest-api-plugins/endpoints/full-site-editing.php` to add a mapping for Maywood demo site id.

**Comment by Copons** [comment]
We should also mention that using a separate demo site for FSE (e.g. `fsemaywooddemo`) is not ideal and won't be the long term approach.

Eventually we will use the "normal" demo site (e.g. `maywooddemo`), but right now we need to keep things as small and simple as possible for the 10% test.

**Comment by vindl** [comment]
The demo site has been created an our API was modified to work with it.
