### ISSUE TITLE
Editor: Justify text option not working on Simple Sites

### ISSUE THREAD

**Issue by susanjanec** [Automattic/wp-calypso#36391]
#### Steps to reproduce
1. Starting at URL: https://susanjanewptestsite12345.blog/2019/08/26/a-sticky-post-example/
2. Applied the Justify option to all paragraphs
3. Published the post and viewed the post and not seeing the text is justified
4. CSS class on all paragraphs showing as `has-text-align-justify` to confirm the justify option was applied.

#### What I expected

Text will appear as justified.

#### What happened instead

Text did not justify

#### Browser / OS version

Chrome Version 76.0.3809.132 / macOS High Sierra Version 10.13.6

#### Screenshot / Video
https://cld.wthms.co/s6UEA7

#### Context / Source
User came into chat regarding this issue - provided CSS as a workaround for now.

**Comment by mikeicode** [comment]
Another in 15020826-hc (the class is added to the text but not applied).

This appears to be related to the 6.5 release since this occurs on Simple sites but not on AT sites (which aren't at 6.5 yet).

**Comment by detlefholtz** [comment]
Got another in 15179400-hc. 

All of the posts that the user's written in the last month aren't justifying correctly, so I sent them the CSS, which did the trick. 

Unfortunately, their galleries are also not showing correctly. The images are aligned vertically instead of horizontally. Editing the galleries via the editor fixes them, but they have many galleries and have to do this manually.

**Comment by kwight** [comment]
@detlefholtz can you open a separate issue for the galleries please, thanks!

**Comment by kwight** [comment]
Ah, it turns out this has been broken since Gutenberg 6.3 (but we've been on 6.2 until skipping to 6.5 yesterday).

It's due to [this change](https://github.com/WordPress/gutenberg/pull/16794); I'll update our plugin to use the new class format.

**Comment by kwight** [comment]
D33289-code is ready for review; this will likely go out this coming Monday.

**Comment by darnelldibbles** [comment]
A few reports in forums on this today - posting here so that we can notify them once things are back up and running:
https://en.forums.wordpress.com/topic/justify-function-not-working/
https://en.forums.wordpress.com/topic/justify-paragraphs/#post-3373241

**Comment by macmanx2** [comment]
Also reported at https://en.forums.wordpress.com/topic/jusify-text/

**Comment by kosiew** [comment]
another case here #2384169-zen

**Comment by liviopv** [comment]
Another report: #2383730-zen

**Comment by carinapilar** [comment]
Another report: #2384453-zen. User doesn't have the CSS option to use the workaround.

**Comment by CoachBirgit** [comment]
Another report: #2384515-zen (German upwork). User doesn't have the CSS option to use the workaround.

**Comment by tijosh** [comment]
Another report in #2384693-zen

**Comment by sourourn** [comment]
Another one here: #2382364-zen

**Comment by sophiegyo** [comment]
With regards to the report from #2383564-zen, it looks like paragraphs using drop caps don't actually get the justify class, even if the justify alignment is selected in the editor.

**Comment by sophiegyo** [comment]
Another report: #2386304-zen

**Comment by mlaetitia** [comment]
Another report: #2383722-zen
User doesn't have the CSS option to use the workaround.

**Comment by Agepeuve** [comment]
Also reported here: https://es.forums.wordpress.com/topic/justificar-el-texto/

**Comment by Agepeuve** [comment]
And here: #2388190-zen

**Comment by kylemcph** [comment]
Another report here: #14892362-hc 

Sent CSS workaround.

**Comment by sourourn** [comment]
Another one: #2388362-zen

**Comment by catkit** [comment]
Chat: #15603626-hc
