### ISSUE TITLE
SPT: Closing the template selector shows a blank editor

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#36397]
With the new not-a-modal-modal, I kind of expected to go back to the pages list when I clicked the X icon. Not sure this is a real problem, but it feels a little confusing to click the X and see the editor.

![double close](https://user-images.githubusercontent.com/191598/65796666-34ffa500-e13b-11e9-9369-98ea0d5b37ef.gif)

/cc @apeatling

**Comment by apeatling** [comment]
Agree with this new setup, it should close out the editor and go back to the previous screen. Also the X should be aligned positionally with the X behind it, I noticed it's not quite the same.

**Comment by getdave** [comment]
In this case the `X` should become a back button. The icon should represent the intent.

**Comment by shaunandrews** [comment]
> In this case the X should become a back button. The icon should represent the intent.

The FSE plugin customizing this icon. More and more I've been seeing the trouble around this, and made a PR to undo this: https://github.com/Automattic/wp-calypso/pull/36476

If this does get merged, than changing the SPT to use a left-facing chevron would probably make sense.

**Comment by shaunandrews** [comment]
Something that came up today, is that we have two slight variations of the editor's chrome. 
* When the editor is in "full-screen" then we should have the `<` button. When the editor is in "default" mode, there's no need for a back button.
