### ISSUE TITLE
Reader: post card header should not be clickable in site and feed streams

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3639]
When in a site or feed stream on the Reader, it is still possible to click the top of the post card, which links to the current page. 

Nothing happens, and the clicks get added to the history, which makes using the '< Back' link quite confusing:

https://cloudup.com/iyvi5ZDMVSw

#### Steps to reproduce
1. Starting at a feed stream, e.g. https://wpcalypso.wordpress.com/read/blog/feed/38960801
2. Click the site name or URL in the header of a post card
3. Try and navigate using the '< Back' link at the top of the page 

#### What I expected

The post card header should not link anywhere if you're browsing a blog or feed stream.

**Comment by blowery** [comment]
Let's just kill that header altogether on those streams. It serves no purpose.

**Comment by blowery** [comment]
Discover was wanting this too I think @kjellr ?

**Comment by kjellr** [comment]
Yeah, definitely. That header doesn't really serve a purpose when you're on the Discover tab already. Trimming it out would be nice and clean: 

<img width="599" alt="screen shot 2016-02-28 at 7 51 12 pm" src="https://cloud.githubusercontent.com/assets/1202812/13383239/d7877ee4-de54-11e5-9d2a-7969384657dc.png">

**Comment by blowery** [comment]
@kjellr tangent, but why is _Deadline_ missing it's site icon? Do they have one set?

**Comment by kjellr** [comment]
@blowery They do have one set, so I'm not sure why it's missing for us there. The icon does appear on their site stream page, and also on Discover.WP.com. I'll open another ticket for it. :+1:
