### ISSUE TITLE
Visiting Gutenberg in Calypso on a Jetpack site Calypsoifies wp-admin from that point on

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#36400]
#### Steps to reproduce
1. With a connected Jetpack site
2. Go to the "posts" page in Calypso
3. Add a new post, or edit an existing one (be sure that you've opted into the Gutenberg editor)
4. Complete editing, and go back to the posts page
5. Click the "WP Admin" link at the bottom of the sidebar

#### What I expected

To be taken to the Jetpack dashboard in regular wp-admin

#### What happened instead

I was taken to the Jetpack dashboard in a Calypsoified wp-admin (on my site's domain) with incorrect menu hierarchy displayed on the left

Visiting the /wp-admin root appears to undo the effect

#### Browser / OS version

Chrome 77 on macOS 10.14.6

#### Screenshot / Video

<img width="1748" alt="jetpack-calypsoified" src="https://user-images.githubusercontent.com/51896/65797102-3ae98c00-e123-11e9-95d4-131d9597abe6.png">

Video:

https://cloudup.com/cMrGxEoO37i

**Comment by kwight** [comment]
Yep, it's known madness. The whole Calypsoify Frankenstein needs an audit and rethinking (it was pressed into service to do far more than it was ever intended to do, and in a huge rush in the push to 5.0). We're just waiting for a team with the time and no higher priorities to take it on.

**Comment by pablinos** [comment]
Automattic/jetpack#17826 fixes this issue.
