### ISSUE TITLE
Block editor jumps to top to post when trying to add/edit paragraph blocks in Microsoft Edge

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#36417]
User in reported in 2382935-zen and another HE was able to reproduce on their own site in Edge using Browserstack.

I tried to replicate myself in Browserstack but the editor was so laggy in Edge that I couldn't effectively test it; reporting here anyway since another HE was able to successfully reproduce.

Steps to reproduce:
1. Create a new post in Microsoft Edge
2. Try to type something
3. The editor will jump to the top of the post

According to the user, this started happening yesterday for the first time.

**Comment by liviopv** [comment]
Another report in #2385494-zen. The user shared a video where the problem is evident, I'm asking their permission so I can share it here

**Comment by liviopv** [comment]
One more #2387683-zen. I'm still confirming if this one is using Edge

**Comment by liviopv** [comment]
> Another report in #[2385494-zen](https://href.li/?https://automattic.zendesk.com/agent/tickets/2385494). The user shared a video where the problem is evident, I'm asking their permission so I can share it here

The user from this ticket reported that the behavior also happened in the WordPress.com app, and also shared this video where the issue can be seen live: https://cld.wthms.co/qh6i3E

**Comment by kwight** [comment]
Ack. This is a known core Gutenberg bug, since 6.4: https://github.com/WordPress/gutenberg/issues/17255

Easy workaround for now (although never fun to hear) is to use either Firefox or Chrome.

**Comment by zdenys** [comment]
Two more reports on the Forums https://it.forums.wordpress.com/topic/errore-ultimo-aggiornamento/ One for Microsoft Edge and one for WordPress.com Desktop App on Windows 10.

**Comment by smithkyle45** [comment]
I had a report of this issue in #16659977-hc. Advised trying Firefox or Chrome as a workaround for now

**Comment by donalirl** [comment]
Another case in #2553064-zen

**Comment by lakellie** [comment]
Just cleaning up some old issues of mine. According to this: https://github.com/WordPress/gutenberg/issues/17255
This issue was resolved in WP 5.3.1, so it should be resolved on WP.com as well by this point.
