### ISSUE TITLE
Settings: EXIF Metadata Settings for Jetpack Carousel & Galleries on Simple Sites

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#36415]
It appears simple site users must navigate to their WP-Admin to adjust Jetpack's EXIF metadata settings.

EXIF metadata settings detailed here: https://jetpack.com/support/carousel/ -- currently pending WPCOM documentation on 443-GH-en.support-docs-content

#### Steps to reproduce
* Use/create simple site.

* Simple sites must go to WP-Admin > Settings > Media to disable/enable this via `show photo metadata (Exif) in carousel, when available.`

![image](https://user-images.githubusercontent.com/4887830/65819685-7f415e80-e1ed-11e9-8f4b-fd1418fa82e8.png)

* Atomic sites can access this setting the following ways:
  * Via Calypso under My Site > Manage > Settings > Writing
  * WP-Admin > Settings > Media,  
  * WP-Admin > Jetpack > Settings > Writing

#### What I expected

* Setting to be available in Calypso like on Atomic sites under My Site > Manage > Settings > Writing

![image](https://user-images.githubusercontent.com/4887830/65819700-a5ff9500-e1ed-11e9-81da-45bb6266a289.png)

#### What happened instead

* Had to access WP-Admin > Settings > Media to turn of EXIF data from displaying.  

#### Context / Source
Discovered the issue while assisting a fellow HE, reviewing our documentation at https://jetpack.com/support/carousel/, and making a  WPCOM documentation improvement suggestion: 443-GH-en.support-docs-content

**Comment by michaeldcain** [comment]
Related: #36374

**Comment by donalirl** [comment]
Another need for this in #19868284-hc

**Comment by eduardozulian** [comment]
Another in 21644706-hc

**Comment by michaeldcain** [comment]
This is still a difference between Atomic/Jetpack and Simple. @obenland would it make sense to add it to https://github.com/Automattic/wp-calypso/projects/88?

**Comment by cpapazoglou** [comment]
Since nav unification, both Simple & Atomic sites can edit this setting from **Settings -> Media** .

So, accessing it Via Calypso under Settings > General > Writing is duplication. In the spirit of removing duplicate settings / screens and keeping the source of truth (WP Admin), I would suggest removing this options from Atomic sites too.
