### ISSUE TITLE
Reader: Instagram posts do not embed correctly

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3642]
Instagram embeds appear correctly in wordpress.com blogs:

<img width="713" alt="screen shot 2016-02-29 at 16 51 34" src="https://cloud.githubusercontent.com/assets/17325/13385407/2db6706c-df05-11e5-99d7-42e4b6608ec5.png">

...but the image does not load in the Reader:

<img width="735" alt="screen shot 2016-02-29 at 16 52 06" src="https://cloud.githubusercontent.com/assets/17325/13385410/31c3a90e-df05-11e5-9b40-fd83d3556607.png">

Example post: http://calypso.localhost:3000/read/post/feed/40474296/941652093

**Comment by blowery** [comment]
> We provide two ways to programmatically add an Instagram post to your page: an oEmbed endpoint and a simple URL append endpoint. Neither requires an access_token or client_id.

> Given a short link, the oEmbed endpoint allows you to get the embed code and additional information about the media associated with the link.

> The embed code contains a preview HTML code and a reference to the Instagram embeds.js JavaScript library. When the library is loaded, it scans the page for the HTML code and generates the fully rendered post.

> If you want to load the library separately from the HTML code, you can call the oEmbed endpoint with the omitscript parameter. This is useful for websites that want to handle the loading of the embeds.js script by themselves. To manually initialize the embed code, you can then call the JavaScript function instgrm.Embeds.process().

> The embedded post is responsive and will adapt to the size of its container. This means that the height will vary depending on the container width and the length of the caption. You can set the maximum width by using the maxwidth parameter. You can also use the hidecaption parameter to display the post without the caption.

> If loading the embed code is not an option, you can use the URL append endpoint. Given an Instagram short link, this endpoint issues a redirect to that media’s image file. If you embed an Instagram image this way, you must provide clear attribution next to the image, including attribution to the original author and to Instagram, and a link to the Instagram media page.

from https://www.instagram.com/developer/embedding/

We drop the script tag when sanitizing the feed, but we can sideload the embed script and then run `instgrm.Embeds.process()` as part of `componentDidMount` like we do for emojify

**Comment by blowery** [comment]
Fixed with #4397
