### ISSUE TITLE
Auto-loading Homepage: Add Barnsbury and Dalston to TFT theme list

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#36421]
@obenland We've launched two new template-first themes on Thursday 26th Sep. Could you add them to the `tft_themes` list? Thanks in advance!

```
pub/barnsbury
pub/dalston
```

**Comment by obenland** [comment]
How far are we on the theme tag to denote template-first and/or business themes? This is not very scalable

**Comment by iamtakashi** [comment]
I agree it's not ideal. We just need to decide how to call the tag, and I've asked in a comment of the thread paAmJe-LW-p2 :)

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.

**Comment by obenland** [comment]
I think this has been fixed in the meantime, too
