### ISSUE TITLE
Theme Showcase: Provide a way to close modal after theme activation

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#36422]
I'm pretty sure you used to be able to close the modal by clicking outside of the small modal after you activate a theme. But it doesn't seem to be the case anymore.

![wordpress com_themes_iamtakashi wordpress com (1)](https://user-images.githubusercontent.com/908665/65869720-db81bb00-e372-11e9-8137-f95a2ca7d698.png)

The thing is that you have to go to the theme showcase page or Customizer after activating a theme since there is no way to just close the modal. This is inconvenient if you just want to go to other parts of Calypso, and we should provide a way to close the modal.

**Comment by eduardozulian** [comment]
That's right, @iamtakashi. It's been like this for some time now according to #35892

**Comment by iamtakashi** [comment]
@eduardozulian Thanks for letting me know it's been reported! I'll plus one there and close this issue as duplicated.
