### ISSUE TITLE
New site getting stuck on "Hooray! Your site will be ready shortly." step

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#36428]
Creating a new site in Calypso from the Add New Site sidebar option is getting stuck on the "Hooray! Your site will be ready shortly." step at https://wordpress.com/start/plans and the site is not created.

#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Click My Sites > Switch Site > Add New Site at the bottom, which should open https://wordpress.com/jetpack/new?ref=calypso-selector
3. Create a WordPress.com site
4. Choose a vertical, set a title, choose a free address, and free plan
5. The process gets stuck at "Hooray! Your site will be ready shortly." on https://wordpress.com/start/plans with no site created.

#### What I expected
To create a new site

#### What happened instead
The process gets stuck and a site is not created

#### Browser / OS version
Chrome 77.0.3865.9, Mac OS

#### Screenshot / Video

https://cld.wthms.co/7GFr2a

#### Context / Source
#manual-testing

**Comment by adamziel** [comment]
This issue was solved by reverting Automattic/wp-calypso#34768
