### ISSUE TITLE
FSE: home page title not shown on front end

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36431]
I'm not sure what's the intended behavior here, but there is a discrepancy between the editing and rendering mode when it comes to displaying Home page title.

**In editor:**

<img width="1360" alt="Screenshot 2019-09-30 at 16 33 00" src="https://user-images.githubusercontent.com/1182160/65888550-00d8ee00-e3a0-11e9-99d2-529c6eac71f7.png">

**On the front end:**

<img width="1666" alt="Screenshot 2019-09-30 at 16 32 41" src="https://user-images.githubusercontent.com/1182160/65888568-07fffc00-e3a0-11e9-82c6-0fbafc7478d1.png">

**Comment by apeatling** [comment]
This is something we need to fix, but I would not consider it a blocker for the 10% test.

**Comment by noahtallen** [comment]
Will this be fixed when https://github.com/Automattic/themes/pull/1406 is synced?

**Comment by vindl** [comment]
Yes, my testing setup was wrong at the time and this is a duplicate of https://github.com/Automattic/template-first-themes-private/issues/126. Sorry about that.
