### ISSUE TITLE
Support User: i18n locale is not observed when switching on wpcalypso

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#3643]
#### Steps to reproduce
1. Set a test user's interface language to something other than English/your own language.
2. Log in to the test user using support user **on calypso.localhost** (ref p195om-2GO-p2)
3. Note that the interface changes to the test user's language upon reload
4. Log in to the test user using support user **on wpcalypso**
5. Note that the interface is not displayed in the test user's language
##### On calypso.localhost (this is the expected behaviour)

![screen shot 2016-02-29 at 2 10 34 pm](https://cloud.githubusercontent.com/assets/416133/13385583/56293b22-deee-11e5-9980-d339aeca650b.png)
##### On wpcalypso (shows default language)

![screen shot 2016-02-29 at 2 10 58 pm](https://cloud.githubusercontent.com/assets/416133/13385588/608afcea-deee-11e5-82a3-61204ffba7da.png)

**Comment by jordwest** [comment]
@mtias mentioned this is likely due to the user bootstrap process (ref p6jOYE-kE-p2). Although we're intercepting and exiting early before the main `user` object bootstrap, the `localSlug` is likely bootstrapped elsewhere

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue.  As an additional data point, it works fine on https://calypso.live (i.e. the user's language setting is honored)

**Comment by hoverduck** [comment]
For the record, it also does not work on https://wordpress.com.

**Comment by alisterscott** [comment]
Bug Scrub: This is still an issue.

![screen shot 2016-10-11 at 8 38 39 am](https://cloud.githubusercontent.com/assets/128826/19253422/45b473b4-8f8e-11e6-9684-510c92b94d9a.png)

@jordwest: is this low priority? If so I can mark it as such.

**Comment by jordwest** [comment]
@alisterscott This is still an issue, but low priority. For the next support user milestone, this should be fixed by reviving #3778

**Comment by rachelmcr** [comment]
Confirmed this is still an issue. Matt also noted this after his last support rotation — as he observed, it's very helpful for HEs to know the exact labels that the user sees in their dashboard when giving instructions (even if the rest of the instructions are given in English). Not having that with the Support User makes it less useful for supporting non-English-speaking users.
