### ISSUE TITLE
FSE: About page is using the menu template

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#36437]
The about page that is auto created on signup is using the menu page template, not the about page template.

**Comment by apeatling** [comment]
The menu template was just added last week.

**Comment by apeatling** [comment]
<img width="1155" alt="Screen Shot 2019-09-30 at 3 42 35 PM" src="https://user-images.githubusercontent.com/1464705/65922074-f404cc00-e398-11e9-9072-4fa12a6a88cb.png">

**Comment by noahtallen** [comment]
code is here. I think the hardcoded value may need to be changed:

https://github.com/Automattic/wp-calypso/blob/95bd67a93309e97ab722dae6a7a142777b70413c/apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php#L323-L325

**Comment by obenland** [comment]
`wp_list_pluck()` could help here. It probably broke with #36237.
