### ISSUE TITLE
Gutenboarding: Custom Gutenberg Canvas

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#36448]
Let's do a spike to see how we can take https://github.com/WordPress/gutenberg/tree/master/playground and adapt it to what we want as our canvas for the new onboarding on WordPress.com

**Comment by davipontesblog** [comment]
Closing this as it's been moved to "Done" in [Gutenboarding](https://github.com/orgs/Automattic/projects/127#card-28759811).
