### ISSUE TITLE
Reader: Discover highlights do not always appear

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3644]
At the top of the Discover page, there's a Highlights section:

<img width="793" alt="screen shot 2016-02-29 at 17 27 00" src="https://cloud.githubusercontent.com/assets/17325/13385820/34c7a34e-df0a-11e5-8bff-34d33e8137b3.png">

This only shows up if you are currently following discover.wordpress.com.

Users may want to visit `/discover/` whilst not being followers of the feed itself.

Thanks to @jancavan for spotting this in her design review.

**Comment by bluefuton** [comment]
cc @mjangda

**Comment by bluefuton** [comment]
Originally thought this only happened if you weren't following Discover, but it seems it can occur either way.

The API request to `/featured` gets fired correctly, and the store even seems to have the correct postKeys, but `posts` is `[]` inside the `FeedFeatured` component.

**Comment by alisterscott** [comment]
I confirmed this is appearing whether I follow Discover or not:

https://wordpress.com/discover

<img width="865" alt="screen shot 2017-05-11 at 2 04 58 pm" src="https://cloud.githubusercontent.com/assets/128826/25931989/e562cef4-3652-11e7-9642-3d6e9272e998.png">

Also, Discover isn't a menu option anymore.
