### ISSUE TITLE
Gutenboarding: Integration with Calypso

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#36450]
We need to find a way to serve a Gutenberg customized canvas from WordPress.com, so even unlogged users could get our new onboarding experience.
We will be doing a spike to find the best way of doing this.

**Comment by davipontesblog** [comment]
Closing this as it's been moved to "Done" in [Gutenboarding](https://github.com/orgs/Automattic/projects/127#card-28759811).
