### ISSUE TITLE
Editor (Classic): Can't use Excerpt in Safari browser

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#36455]
The “Excerpt” box which is found in the More Options section of the Classic editor isn’t functional in Safari. 

Steps to reproduce:
1. Create a new post using the classic editor (not Gutenberg).
2. Attempt to write text in the post Excerpt box, you won’t be able to type anything and an “information” bubble will appear to describe what this box does. This bubble seems to be creating the problem.
3. Note that we also can’t copy+paste text in to this box normally. We can right-click in to the box and paste text, but we can’t use Cmd+V to paste the text (nothing happens) *unless* text is already present in the box.

#### What I expected
We should be able to type text in to the post Excerpt box. We should also be able to close out of the "information" bubble that appears for this text box.

#### What happened instead
We can't enter text in to the Excerpt box, the "information" bubble is also repeatedly appearing even if we close it out, it seems to be causing the problem itself.

#### Browser / OS version
Safari, tested in version 13.0.1.
The user reported that this issue just recently began happening.
This problem does not occur in Chrome.

#### Video
![Screenshot: https://cldup.com/FLvITX2edp.gif](https://cldup.com/FLvITX2edp.gif)
 (First shows entering text in to the content area of the blog post, then the inability to enter text in to the excerpt box. Next it shows the ability to copy+paste text via a right-click with the mouse. Last it shows that we cannot paste text with Cmd+V on the keyboard.)

#### Context / Source
#user-report in 15642430-hc

**Comment by retnonindya** [comment]
I was able to replicate it on my end too. Checked with the developer team in: #p1570174428146500-slack-calypso

**Comment by jonnyruzek** [comment]
This also happened in #2399124-zen with the meta description box.
