### ISSUE TITLE
Stop including calypso-color-scheme in calypso-build automatically

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#36466]
Calypso build includes a color scheme in the build automatically:

https://github.com/Automattic/wp-calypso/blob/30089f3f4670a923583a07df72c2251daaf9beb1/packages/calypso-build/webpack.config.js#L109-L112

That's nice and well for Calypso but problematic for other consumers like Jetpack.

Upgrading `calypso-build` at consumer's end brings surprise changes via changes in [`color-studio`](https://github.com/Automattic/color-studio) that are hard to track down because nothing fails in the build; CSS variables are not guaranteed to exist. Each update now requires lots of manual testing and kinda unrelated tweaking.

Ideally, consumers would just update `calypso-color-scheme` (or color-studio) directly.

cc @kraftbj @jeherve @Automattic/team-calypso @porada

**Comment by simison** [comment]
Moreover, `calypso-color-schemes` has unscoped generic variables such as `--color-text`, `--sidebar-background` etc, which could collide when used by consumers in `wp-admin` where we don't control the whole environment.

**Comment by jsnajdr** [comment]
Yes, there should be no default value for the `prelude` option. This was harmless when `calypso-color-schemes` defined a set of SASS variables. But now it defines CSS variables that are part of the build output.

Should `calypso-build` depend on `calypso-color-schemes` at all? There's also a default `importFrom` dependency in the [PostCSS config](https://github.com/Automattic/wp-calypso/blob/master/packages/calypso-build/postcss.config.js). That should probably be removed and the user of `calypso-build` (like the Calypso app) should configure that explicitly. But I'm not very familiar with what other users of `calypso-build` do, so not 100% sure it's a good idea.

**Comment by simison** [comment]
I know Jetpack uses some of the sass and CSS variables that get carried over automatically like that but I'd (and I'm sure others) prefer to have that magic go away and just have it manually done. It's much easier to understand, modify and update like that.

I know Newspack also uses the setup so cc @jeffersonrabb 

I think it would be just a matter of consumer projects either:
- extending the shared config with the same line and things continue working as usual, except that they get power over the color scheme's versioning
- projects add (or don't) color schemes in their own ways

**Comment by jsnajdr** [comment]
I'm removing the `calypso-color-scheme` dependency in #36471. Please look at that PR and let me know if that works with Jetpack, Newspack and other users of `calypso-build`. Let me know if you need help adapting these projects.
