### ISSUE TITLE
Simple Payments block doesn't work when AMP is enabled 

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#36472]
This issue appears to date back a few years, but I don't think it has been reported yet. Found a Slack discussion at p1516218589000514-slack-triage and was reported by a user yesterday in 13642208-hc.

#### Steps to reproduce
1. Add a Simple Payments block to a post
2. Make sure AMP is enabled on the site (it is enabled by default)
3. Visit the AMP version of the post by appending `/amp` to the end of the URL
3. The button to pay is missing: https://cld.wthms.co/qkvGi4

In both discussions, the issue was problematic for the user because posts shared to Twitter will direct to the AMP version of the post on mobile. When the user tried to disable AMP as a workaround, all the Twitter links still pointed to the AMP version of the post and resulted in a 404, so they turned AMP back on.

**Comment by DavidRothstein** [comment]
Tracking internally here: pNPgK-4NA-p2

Since it's probably not a Calypso-specific change, though, I don't think it makes sense to keep this issue open in the Calypso project separately.  So I'm closing this issue for now.
