### ISSUE TITLE
Hosting: Initiate automated transfer, show transfer progress, and transfer error [8]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36486]
In Phase 2, we'd like Business customers who haven't yet transferred their site to Atomic to be able to see the Hosting Section.

In this issue clicking on "Proceed" in Eligibility warnings should initiate the transfer. Note that we should show some progress and handle error states. There may be a bit of technical debt, so be sure to split out other janitorials into additional PRs.

This issue also includes any additional API fetch + redux boilerplate we need. Please use your judgement and split out these pieces into small PRs with a safe landing order. 

Unless folks had design input we can use prior art in theme or plugins to help determine the type of indicator we need for transfer. (Try installing a plugin or a custom theme with a business plan).

It's easiest to search for usages by looking for `/sites/:site_id/automated-transfers/initiate` or other endpoints off of `/sites/:site_id/automated-transfers` 

See the following for additional detail on automated transfer status https://github.com/Automattic/wp-calypso/blob/master/client/state/automated-transfer/README.md

<img width="633" alt="Screen Shot 2019-10-02 at 4 10 22 PM" src="https://user-images.githubusercontent.com/1270189/66089371-d6b83500-e533-11e9-9048-708dbd3d68b3.png">

<img width="734" alt="Screen Shot 2019-10-02 at 4 20 17 PM" src="https://user-images.githubusercontent.com/1270189/66089373-dae45280-e533-11e9-94fd-09f93f27a7a0.png">

**Comment by mmtr** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/37983
