### ISSUE TITLE
Hosting: Sidebar link is visible to all Business Customers [1]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36484]
In Phase 2, we'd like Business customers who haven't yet transferred their site to Atomic to be able to see the Hosting Section.

In this issue update the visibility of the sidebar and update routing checks to allow to display the section for Business Customers. While development is in progress, please make sure that this is featured flagged to the dev environment only.

<img width="633" alt="Screen Shot 2019-10-02 at 4 10 22 PM" src="https://user-images.githubusercontent.com/1270189/66088367-bb4b2b00-e52f-11e9-8fe8-ace49cd90c77.png">

**Comment by kwight** [comment]
> we'd like Business customers who haven't yet transferred their site to Atomic to be able to see the Hosting Section

I thought would only be applicable to users who _had_ transferred to Atomic?..

**Comment by kwight** [comment]
Oh! After seeing #36483 , I get it 👍

**Comment by gwwar** [comment]
Since we're unblocked on Phase 1 work @jeraldjuice we'll need a new feature flag for this.
