### ISSUE TITLE
Reader: "block site" appears in My Likes when the site in question has already been blocked

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3649]
@jancavan noticed:

> when blocking a site, previous posts from them that I liked still show up on My Likes. That’s fine as I think historical activity should be retained. However, the “Block site” button is still there (change to Unblock?) and “re-blocking” them throws an error.

**Comment by jancavan** [comment]
@bluefuton Now that I think about it more, I agree. We shouldn't retain historical activity anymore so once a site has been blocked, liked posts should no longer appear under Likes.

**Comment by jancavan** [comment]
@bluefuton After blocking a site, I also noticed that it still shows up on my "Followed Sites" until after a refresh.

**Comment by bluefuton** [comment]
I've just made an API change (wpcom-132118) that removes blocked sites when putting together a post list for the `/read/liked` v1.2 endpoint.

This means we shouldn't see any blocked sites in My Likes on the initial page load.

**Comment by jancavan** [comment]
Checked and issue has been addressed :+1:
