### ISSUE TITLE
FSE: template part generic name appears in block inspector

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36508]
When you open block inspector on an FSE page you can see the following:

![image](https://user-images.githubusercontent.com/1182160/66161331-59242000-e62c-11e9-9c90-0a1b6f346fe4.png)

As @shaunandrews suggested, a better solution here would be to show the label instead of the block name.

Let's follow this up with a core PR (and issue possibly) after the launch.

**Comment by shaunandrews** [comment]
There's some activity around this in Core, too: https://github.com/WordPress/gutenberg/pull/17519

**Comment by talldan** [comment]
I'm going to move forwards with being able to specify an attribute that can act as a block display name. Does that fit the use case for these templates? 

I imagine there'll be a follow-up PR at some point. Possibly showing the block name before the display name, or allowing a function/component to be used.

**Comment by vindl** [comment]
> Does that also fit the use case for these templates?

Yes, I think we can make it work with that. Looping in @Automattic/cylon for thoughts.

**Comment by noahtallen** [comment]
Yeah, I think we could pretty easily work that in!

**Comment by noahtallen** [comment]
> Possibly showing the block name before the display name

In our case, we would probably want to be able to turn that off. For example, we wouldn't want "Template: Header" in our case.

**Comment by vindl** [comment]
Closing this since the core PR has been merged: https://github.com/WordPress/gutenberg/pull/17519
