### ISSUE TITLE
Domains: Transfers always default to public registration at checkout

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#36507]
#### Steps to reproduce
1. Go the `/start` to create a new site
1. At the domains step, enter a domain that is already registered and select "Yes, I own this domain"
1. Select a paid plan
1. Proceed to checkout

#### What I expected

The domain transfer defaults to "Register privately with Privacy Protection (recommended)", if the TLD for the domain supports it.

#### What happened instead

The domain transfer is always defaulted to "Register publicly"

#### Browser / OS version

Chrome / macOS

#### Screenshot / Video

<img width="1229" alt="Screen Shot 2019-10-03 at 14 41 20" src="https://user-images.githubusercontent.com/1699996/66158621-e3985f80-e5eb-11e9-98b3-cf9285e45dad.png">

#### Context / Source

Seen while testing #34255 

See comments on that issue
- https://github.com/Automattic/wp-calypso/pull/34255#issuecomment-536967959
- https://github.com/Automattic/wp-calypso/pull/34255#issuecomment-538098516

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by creativecoder** [comment]
I don't think this is relevant any longer with the updated checkout interface--I no longer see an option for public vs private domain registration during checkout.
