### ISSUE TITLE
Classic Editor - Sharing > "Customize the message" info popover opens when cursor is placed in the text field

### ISSUE THREAD

**Issue by smithkyle45** [Automattic/wp-calypso#36512]
* Was able to reproduce this issue on my own account & via SU 
* only happening in **Safari** using the **Classic Editor**

#### Steps to reproduce
* In Safari, with Classic Editor active on simple site 
* verify that a Twitter account is connected via Tools > Marketing > Connections
* Add new or edit an existing Post
* expand the *Sharing* panel on the right hand side
* Click in the text field labelled "Customize the message"

#### What I expected
When cursor is placed in the "Customize the Message", I was expecting to be able to type/edit this text freely. 

#### What happened instead
The info popover appearing to the right (toggled with the small "i" icon) defaults to open, which removes the cursor from this text area

#### Browser / OS version
Safari - Version 13.0.1 

#### Screenshot / Video
Screenshot of instance on my own site: https://d.pr/i/o4jtL4
Screenshot of `encorerehab` user's site: https://d.pr/i/PpaJQS

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
