### ISSUE TITLE
Login: Redirect to previous location

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#36518]
#### Steps to reproduce
1. Starting at URL: bullettodo.wordpress.com (or your own private site when not logged in)
2. Click login button 
3. login to WordPress.com 

#### What I expected

If starting at a site URL and logging in to it, I expect to be redirected to the page I was trying to access (eg the home page)

#### What happened instead

I am taken to https://wordpress.com, to the Reader

This is despite the redirect query that is in the URL of the login page:
https://wordpress.com/log-in?redirect_to=http%3A%2F%2Fbullettodo.wordpress.com%2F

#### Browser / OS version
Safari 13.0.1
Firefox 69.01
Chrome 77.0.3865.90

#### Context / Source
#user-report #2394920-zd

**Comment by kraftbj** [comment]
I'm reasonably sure this was caused by #33642.

**Comment by sgomes** [comment]
Thank you, @kristarella and @kraftbj. It does look related. Investigating.

**Comment by sgomes** [comment]
I've found the root cause and created #36540 with the fix. Thanks again for letting me know!
