### ISSUE TITLE
Settings: Images have incorrect alignment

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36532]
When you go to Site Settings, at the bottom you'll find options to Delete Content and Delete Site:

<img width="746" alt="Screen Shot 2019-10-04 at 9 30 00 AM" src="https://user-images.githubusercontent.com/2124984/66212753-7a1c5d80-e68c-11e9-8f76-05bfa224f72f.png">

The images on these pages are misaligned; they should be right aligned, but they're stuck at the top:

<img width="759" alt="Screen Shot 2019-09-30 at 1 08 20 PM" src="https://user-images.githubusercontent.com/2124984/66212781-86a0b600-e68c-11e9-80c5-05f7d9ea0855.png">

<img width="746" alt="Screen Shot 2019-10-04 at 9 52 06 AM" src="https://user-images.githubusercontent.com/2124984/66212852-a637de80-e68c-11e9-9c92-cc29a3fd6c4f.png">

**Comment by sixhours** [comment]
Also happens on the Theme Setup page, found when you're using one of the newer themes (like Friendly Business).

![screencapture-hash-a713519db5ffe162245323104527f3a77025f79d-calypso-live-settings-theme-setup-sixhourssandbox-wordpress-com-2019-10-07-09_15_11](https://user-images.githubusercontent.com/2124984/66315157-30798000-e8e3-11e9-85d4-015bc6bd27e1.png)

**Comment by Aurorum** [comment]
This is a defect cause by [this](https://github.com/Automattic/wp-calypso/commit/790599f82e85caec3583c2f6da0da7ff5a3a7098), PR in #36570 to make that change more specific. :)
