### ISSUE TITLE
After Atomic upgrade, the classic editor may load in Calypso for a short while

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#36548]
#### Steps to reproduce
1. Create a new user and a new site through the FSE horizon flow
2. Verify that FSE is working and you get :gutenberg:
3. Invite your wpcom user so that they can upgrade you to business with credits
3.  install Yoast SEO from the horizon account
4. Immediately go to the pages list in Calypso and edit a page. You might see the classic editor.
5. If I refresh the site after a minute, it starts showing, and it's hard to reproduce. (p.s. this happened non-sandboxed) 

#### What I expected
That my Gutenberg editor preference is respected. 

#### What happened instead
The Calypso classic editor was loaded for a while.

#### Browser / OS version
Brave / Chromium

The code which fetches the classic editor should likely be updated to _not_ rely on global state [here](https://github.com/Automattic/wp-calypso/blob/84dc1bc322cf1150a05d70fb152ac8e831a16bd4/client/gutenberg/editor/controller.js#L128-L131). Since this could easily be a caching issue.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
