### ISSUE TITLE
Signup/Checkout: Flicker in header text

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#36557]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Go through the signup flow, add a plan to cart and proceed to the Checkout page

#### What I expected

The header text to stay consistent

#### What happened instead

The header text initially says `Your WordPress.com site is ready! Finish your purchase to get the most out of it.` and then changes to `Great choice! How would you like to pay?`

Note that to see this, the payment options need to be visible on your Checkout page, which means that you shouldn't be having any WPCOM credits. 

#### Screenshot / Video

Screen recording: https://cloudup.com/cFdp-LK1S8D

Related to the change introduced in https://github.com/Automattic/wp-calypso/pull/35757

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by rickybanister** [comment]
@michaeldcain is this issue still relevant the new checkout experience?

**Comment by michaeldcain** [comment]
@rickybanister: nope - thanks for closing the loop.
