### ISSUE TITLE
Themes: Show 404 page for missing themes

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3656]
On the client and server side, we should show a 404 page when `/themes/foobar/(page)?` isn't found.

**Comment by folletto** [comment]
Design reference:

![tshowcase-m4-m7-404-i3](https://cloud.githubusercontent.com/assets/4389/13503751/188deb28-e169-11e5-9dbf-0eb9607bc59e.png)

This is the existing `EmptyContent` structure, statically rendered server-side.
