### ISSUE TITLE
Explore the best way to customize FSE's gutenberg header

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#36563]
Following team Ajax exploration at https://github.com/Automattic/wp-calypso/issues/36323, we need to find the best way to modify the header of the gutenberg version that's used in wpcom so it can be adapted to the special customizations we need to create for the new onboarding flow

**Comment by davipontesblog** [comment]
Closing as it's been moved to "Done" in Gutenboarding project.
