### ISSUE TITLE
CoBlocks: Update to 1.15 [5]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36575]
CoBlocks has a new update: https://github.com/godaddy/coblocks/releases/tag/1.15.0

Let's test and upgrade if things look stable.

**Comment by kwight** [comment]
CoBlocks 1.15 is now running in production (D33753-code).

**Comment by kwight** [comment]
@gwwar This ended up a `[2]` rather than a `[5]`.
