### ISSUE TITLE
Themes: Tapping on a screenshot in mobile sheet view opens full-size screenshot

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3657]
When we're in mobile view, as the screenshot may be quite small, we want to open it full screen. Probably in a modal.

**Comment by folletto** [comment]
Design reference: 

![screen shot 2016-03-03 at 17 54 28](https://cloud.githubusercontent.com/assets/4389/13503724/ff027dae-e168-11e5-86b6-4e727135244c.png)

Note: in the first version there will be no multiple images, so no swiping nor the top dots.

**Comment by folletto** [comment]
Descoped from milestone M4 'Theme Sheets' as we don't have tall screenshots nor multiple ones. 
To review later once we reach M6 'The One', where swapping screenshots in won't risk other showcases to break (as they won't exist).

**Comment by folletto** [comment]
We have something along these lines now, even if it's not the same I guess we can close this for now.
