### ISSUE TITLE
Customer Home: Sometimes not visible for Atomic sites

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#36578]
#### Steps to reproduce
1. Using a development environment (local or calypso.live), create a new Atomic site
1. Add yourself to the `show` group of the `customerHomePage` a/b test
3. Try to visit the "My Home" section (by clicking on that link in the sidebar)

(You may need to clear the site data from the browser to remove cached state in order to reproduce this bug)

#### What I expected

To see the "My Home" item in the sidebar and be able to access the Customer Home page

(This also affects checklist visibility for users in the `hide` group).

#### What happened instead

The sidebar link is not shown and visiting the page shows "This page is not available on this site"

Note that if I refresh the page in the browser, the Customer Home should eventually appear.

#### Browser / OS version

Chrome / macOS

#### Screenshot / Video

<img width="1552" alt="Screen Shot 2019-10-07 at 16 20 39" src="https://user-images.githubusercontent.com/1699996/66349433-87e91180-e91e-11e9-910d-65a9ffe42214.png">

#### Context / Source

This appears to be caused by a discrepancy in how the `/sites/{siteId}` and `/me/sites` endpoints return data for Atomic sites

- `/me/sites` returns a date value for `created_at` within the blog options from wpcom
    <img width="736" alt="Screen Shot 2019-10-07 at 16 24 54" src="https://user-images.githubusercontent.com/1699996/66349906-8a983680-e91f-11e9-96d4-139e39b66b9d.png">
- `/sites/{siteId}` request is proxied to the site via Jetpack, and serves the default value of `'0000-00-00T00:00:00+00:00'`, I believe because the site creation date doesn't exist outside the WordPress multisite context (https://github.com/Automattic/jetpack/blob/master/sal/class.json-api-site-base.php#L395)
    <img width="735" alt="Screen Shot 2019-10-07 at 16 26 50" src="https://user-images.githubusercontent.com/1699996/66349907-8a983680-e91f-11e9-85be-201289ad8173.png">

So depending on which of these responses is loaded into `state.sites.items`, the `isEligibleForDotcomChecklist` selector will return `true` (if there's a date value) or `false` if the date is `'0000-00-00T00:00:00+00:00'`.

https://github.com/Automattic/wp-calypso/blob/master/client/state/selectors/is-eligible-for-dotcom-checklist.js#L19

https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/selectors/can-current-user-use-checklist-menu.js#L36

**Comment by creativecoder** [comment]
This should be fixed via D33813-code.

@davipontesblog please let us know if you see any more of the "disappearing Customer Home" on Atomic sites.

**Comment by davipontesblog** [comment]
> This should be fixed via D33813-code.
> 
> @davipontesblog please let us know if you see any more of the "disappearing Customer Home" on Atomic sites.

Sure thing!
