### ISSUE TITLE
Gutenberg: Test 6.7 Plugin [10]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36576]
The Gutenberg 6.7 plugin is set to be released on October 16th! Let's help test in advance and see if this is stable for WordPress.com.

- call for testing: p7DVsv-7si-p2
- e2e tests PR: https://github.com/Automattic/wp-calypso/pull/36572
- diff to activate on prod: D33674-code

**Comment by kwight** [comment]
All unit and e2e tests are green so far 👍

**Comment by kwight** [comment]
6.7 was deployed October 16 with D33674-code.
