### ISSUE TITLE
Editor: Unable to edit/add posts/pages with Internet Explorer

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#36589]
This is happening with versions of Internet Explorer when trying to add or edit posts or pages. It doesn't matter which editor is being used the error happens. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts with Internet Explorer
2. Choose to edit or add a new post
3. See error message "We're sorry, but an unexpected error has occurred"

#### What I expected
For the editor to load 

#### What happened instead
The error message mentioned above happens

#### Browser / OS version
I tested on Windows 7 with IE 11
Customer report had the same. 

#### Screenshot / Video
<img width="1431" alt="ie-error" src="https://user-images.githubusercontent.com/1326294/66391967-e78a0000-e9a4-11e9-9ae2-31842e421b07.png">

#### Context / Source
#user-report 

A couple issues have come in so far 
2406778-zen
2406566-zen

**Comment by sgomes** [comment]
It appears #36439 may have introduced this issue, by updating `filesize` to a version that ships with ES6 syntax, namely default parameter values (`function t(t,o={})`). I'll prepare a fix.
