### ISSUE TITLE
FSE: provide an easy way for HEs to detect FSE sites in Blog RC

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36599]
We have no way of differentiating FSE from normal sites in Blog RC now. This can be inferred by presence of `full-site-editing` sticker **and** Maywood theme being active, but it would be nice to make this more obvious.

cc @apeatling @selectedselections

**Comment by mattwiebe** [comment]
D33808-code will do this

**Comment by noahtallen** [comment]
@selectedselections this adds an item to the "blog stickers" section of the blog RC:

**The user will see FSE flows:**
<img width="803" alt="Screen Shot 2019-10-09 at 2 40 37 PM" src="https://user-images.githubusercontent.com/6265975/66522878-4635a380-eaa3-11e9-9d30-b394a9fba027.png">

**The user would see FSE flows if they switched to the Maywood theme again:**

<img width="802" alt="Screen Shot 2019-10-09 at 2 41 59 PM" src="https://user-images.githubusercontent.com/6265975/66522904-55b4ec80-eaa3-11e9-88b5-cf1a98da0e1b.png">

If the user has no way of ever seeing FSE, then there will be no info here.

**Comment by selectedselections** [comment]
Alright! This looks great! I think this is exactly what we need. Thank yall so much for your work on both of these!

**Comment by mattwiebe** [comment]
@selectedselections this has been shipped - thanks for throwing in the screenshots @noahtallen
