### ISSUE TITLE
Themes: Theme details 1.2 endpoint

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3659]
We'll want an ES-backed details endpoint for theme details, with a similar data structure to the 1.2 listing endpoint.

TODO:
- [ ] Copy and modify 1.1 endpoint to use 1.2-like fields, e.g. `price` and `active`
- [ ] Make the new endpoint ES backed
- [ ] Switch over to new endpoint in Calypso

**Comment by folletto** [comment]
#6148 got merged, closing. :)
