### ISSUE TITLE
Editor: CoBlocks Typography feature only available on atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36593]
### Steps to reproduce
- Starting at URL: https://wordpress.com/block-editor/page/DOMAIN
- Add a new Paragraph Block
- Look for the new Typography button on the block toolbar

Note: This _Typography_ button seems to be added to other blocks too where there is text functionality, like on Heading and Button Blocks (screenshot provided below).

### What I expected
I would expect to see the same options on simple and atomic sites.

### What happened instead
The functionality is not present on simple sites. Since this is coming from CoBlocks, and we have it running in dotcom for both simple and atomic sites (where the plugin is installed and active), should it not come up on simple sites too?

This article [here](https://managewp.com/blog/coblocks-plugin) explains the Typography as:

> ... CoBlocks includes a Typography feature that will give you more control over your text elements. You can customize the font, letter size, spacing, and more from the block toolbar ... 

### Screenshots / Videos
Screenshot showing the CoBlocks plugin installed and active on my test business plan atomic site, version 1.15.0: https://cld.wthms.co/2Wl00h

Calypso editor screenshots
Screenshot Simple — https://cld.wthms.co/4kHIwP
Screenshot Atomic — https://cld.wthms.co/yisdnL, https://cld.wthms.co/6iqZD7, https://cld.wthms.co/wpfHlY

#manual-testing

**Comment by gwwar** [comment]
cc @apeatling going to close this out, as I'd expect we'd use Global Styles in FSE over CoBlocks here. Please reopen if otherwise.
