### ISSUE TITLE
Themes: Downloads

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3660]
We want to provide a way for themes to be downloaded from the Sheet view.

TODO:
- [ ] Download uses theme download endpoint. Only show download button when permission has been granted to download.
 - Premium: must have bought theme/plan
 - Free: available logged in and out
 - Theme Details endpoint should return a download_uri when a theme is downloadable
 - Make sure the events are tracked (Tracks)

**Comment by folletto** [comment]
Design: 

![screen shot 2016-03-02 at 12 42 53](https://cloud.githubusercontent.com/assets/4389/13460700/4e62b184-e074-11e5-805f-b23b32a5fff1.png)

**Comment by seear** [comment]
@mendezcode: you may want to take this issue

**Comment by mendezcode** [comment]
@seear you got it! :)

**Comment by mendezcode** [comment]
Created the [add/theme-sheet-downloads](https://github.com/Automattic/wp-calypso/tree/add/theme-sheet-downloads) branch to work with this issue.

**Comment by mendezcode** [comment]
Implemented in a5783b56088a29371d68a393d7877e358fbc3095

Tracking of downloads coming down the road.

Premium themes are not downloaded, therefore not showing the card on those.

There are cases, in which themes do not have `download_uri` set. Such as the case with Twenty Sixteen, which recommends downloading from WordPress.org. In this particular case, the card is shown like this:

![screen shot 2016-03-31 at 4 26 46 pm](https://cloud.githubusercontent.com/assets/5881557/14189892/bf2c271a-f75d-11e5-8ff1-421b742dcc32.png)

The download button (and link in the description) will point to `http://wordpress.org/themes/twentysixteen`.

The text above has been adapted from the original Twenty Sixteen page from the theme showcase: https://theme.wordpress.com/themes/twentysixteen/

I would like your input and review on these @seear :)

**Comment by seear** [comment]
> Created the add/theme-sheet-downloads branch to work with this issue.

@mendezcode: you need to create a PR for the branch, then we can add review comments to that PR :)

**Comment by folletto** [comment]
> There are cases, in which themes do not have download_uri set. Such as the case with Twenty Sixteen, which recommends downloading from WordPress.org. In this particular case, the card is shown like this

Ok two things here:

1. Can we keep the text the same? I'm not sure there's any value in specifying the source in that situation.
2. Can we link directly to the download from .org? 

Also: how do we know that's the right URL, and that URL should be used? What's the condition?
