### ISSUE TITLE
Full Site Editing: Add styling options to the Navigation Menu block

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#36605]
Currently, the Full Site Editing's Main Navigation block doesn't have any styling options (except the wide/full block width), and simply reuses the theme CSS `.main-navigation` class styles.

We should keep the theme CSS as default and fallback, but also let the user set their own styling options.

**Comment by noahtallen** [comment]
should we punt this in favor of core work?

**Comment by Copons** [comment]
> should we punt this in favor of core work?

I'd love to add the same attributes as we are adding to the Site Title and Description.
Here colors are more annoying because menus are inherently more complicated, but it might be worth a try.

**Comment by apeatling** [comment]
I would only try this if it is one day of work, the colors work is almost already completed on the core navigation block from Ajax: https://github.com/WordPress/gutenberg/pull/17832
