### ISSUE TITLE
FSE: provide an easy way for HEs to detect FSE sites in HappyChat

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36600]
We have no way of differentiating FSE from normal sites in HappyChat now. It would be nice to make this more obvious so HEs don't have to piece together information from Blog RC to infer it.

cc @apeatling @selectedselections

**Comment by selectedselections** [comment]
Hi there! I think the best place for this might be in the same area that we show if a user is v1/v2 (or a simple business site) here: https://cld.wthms.co/FSvPaR

Perhaps a sticker there that says FSE?

**Comment by noahtallen** [comment]
So the thought would be to add a tag here?

<img width="351" alt="Screen Shot 2019-10-08 at 1 00 13 PM" src="https://user-images.githubusercontent.com/6265975/66428811-99d4be00-e9cb-11e9-8599-34cc0349fcbd.png">

**Comment by noahtallen** [comment]
Reading through the state, we could easily add a tag if there is a sticker (those tags render based off of blog stickers and it's set up to support new stickers very easily). However, the HE would also have to check if the theme matches, so not ideal...

**Comment by selectedselections** [comment]
@noahtallen Yes that is the location I was thinking. For the theme issue, maybe we could list the supported themes in another color for now? Like if the user is using Maywood, its shown in red? Does that make sense?

**Comment by noahtallen** [comment]
that's a good idea, but we unfortunately don't have a good way to respond to HappyChat with the themes that would be supported.

After talking with @mattwiebe, we're going to add another sticker 'full-site-editing-active` to the HappyChat API - and then the presence of `FSE` in that list would indicate if a user should currently see FSE flows on their site.

**Comment by selectedselections** [comment]
That sounds great! I think that makes perfect sense.

**Comment by noahtallen** [comment]
We have a solution working:

<img width="332" alt="Screen Shot 2019-10-09 at 10 24 04 AM" src="https://user-images.githubusercontent.com/6265975/66505086-7408f100-ea7f-11e9-858b-9f7073ea02da.png">

Hopefully everything will be deployed by the end of the day!

**Comment by selectedselections** [comment]
Thank you Noah! This is looking great. For this issue: https://github.com/Automattic/wp-calypso/issues/36599 is there a similar fix in place @mattwiebe ? Looking forward to letting Happiness know :)

**Comment by noahtallen** [comment]
Not yet, but we are working on it. :)

**Comment by noahtallen** [comment]
This has now shipped and should be live on production for HappyChat.

(screenshot from hud.happychat.io, chatting from wordpress.com)

<img width="1910" alt="Screen Shot 2019-10-09 at 3 53 58 PM" src="https://user-images.githubusercontent.com/6265975/66526324-19868980-eaad-11e9-9f00-d31823fc5809.png">
