### ISSUE TITLE
FSE: Spinner in template part previews is confusing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36609]
I don't understand the template part spinner when loading the full page editor. In this example, it seems to represent the nav menu, and any other blocks that aren't the site title, tagline, and a cover block I threw in under the tagline. Is the spinner section supposed to cover everything in the header template (that would make the most sense I think)?

<img width="1158" alt="Screen Shot 2019-10-08 at 10 40 12 AM" src="https://user-images.githubusercontent.com/349751/66421752-4c515480-e9bd-11e9-818a-a18d3f62945c.png">

**Comment by noahtallen** [comment]
I think it would make sense to have a spinner over the whole thing. The nav block is dynamic, so it has to load before rendering (same with title/description) (and I think the loading state is just a spinner). We should probably have one UI to convey all three of those items are loading.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
