### ISSUE TITLE
FSE: "Back to page" isn't vertically aligned.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36607]
"Back to page" isn't vertically aligned:

<img width="226" alt="Screen Shot 2019-10-08 at 10 34 34 AM" src="https://user-images.githubusercontent.com/349751/66421509-d4832a00-e9bc-11e9-8bae-81f846dfd327.png">

**Comment by noahtallen** [comment]
Huh. Not sure why we hadn't noticed this!
