### ISSUE TITLE
Gutenberg: Embed: Vimeo Embed will stop working after switching editor back to classic

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#36619]
#### Steps to reproduce
1. Create a new post in Gutenberg and paste a Vimeo video url
2. Publish the post
3. Visit the post - everything is fine.
4. Go back to the editor and switch it back to Classic
5. Vimeo video embed preview works in the editor
6. Update post and visit the post - Vimeo video has turned into a link

#### What I expected
I expected that no matter which editor I am using Vimeo video should remain embeded, not turn into a plain link.

#### What happened instead
After switching to Classic editor Vimeo video turned into a link

#### Context / Source

#user-report

**Comment by catkit** [comment]
Followup ticket: #2407741-zen

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
