### ISSUE TITLE
Checklist: Completed checklist becomes incomplete when transfering to Atomic

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#36618]
#### Steps to reproduce
1. From `/start` create a new site with a Business plan
1. After checkout, you should see the checklist (either on the Customer Home or the Checklist page, depending on your a/b test group for `customerHomePage`)
1. Complete the checklist (by completing or skipping each task)
1. Go to Tools > Plugins and install a plugin to transfer the site to Atomic
1. Go back to the `/checklist/{site}` or `/home/{site}`

#### What I expected

For Customer Home: to see the customer home page
For Checklist: to see a completed checklist

#### What happened instead

I see a different checklist with some tasks incomplete. In some cases I might see a task I've already completed as incomplete (like "Create a tagline")

#### Browser / OS version

Chrome / macOS

#### Screenshot / Video

<img width="601" alt="Screen Shot 2019-10-08 at 15 57 56" src="https://user-images.githubusercontent.com/1699996/66432765-71a58900-e9e4-11e9-82c9-5e4c1f779298.png">

#### Context / Source

Preparing to launch Customer Home to all customers

**Comment by davipontesblog** [comment]
Moved to DotCom Manage for triaging.

**Comment by gwwar** [comment]
For now we do not show the checklist for Atomic sites.
