### ISSUE TITLE
Domains: Possible to reach domain transfer options for unsupported TLDs

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#36627]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/transfer/{SITE_URL}
2. Type in a domain with a TLD not supported for transfer
3. Click "Transfer". An error message will appear that the TLD is not supported for transfer
4. Click "Transfer" again. Optionally, make a change to the domain searched before clicking Transfer a second time.

#### What I expected
To still see the error that the TLD is unsupported.

#### What happened instead
I'm taken to the next screen that checks if the domain is unlocked, and asking for the Auth code.

This happens with unsupported TLDs we're accredited for as a registrar, and ones that we aren't.

#### Screenshot / Video
![domain](https://user-images.githubusercontent.com/11873759/66470539-0f9f5f00-ea8a-11e9-885a-f3200772960d.gif)

#### Context / Source

Did some testing after two conversations in three days about users apparently able to reach transfer options for unsupported TLDs:

p1570458789063600-slack-domains
p1570611103015100-slack-domains

And one on users unable to reach transfer options for a TLD that is supported (since fixed, but might be relevant given the timing):
p2MSmN-7v4-p2

**Comment by delputnam** [comment]
Really good catch here @KokkieH .  Thanks for finding this!
