### ISSUE TITLE
AMP: small image error in Search Console

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#36622]
This is a bit of an edge-case, but it seems like it should not happen.

On a simple site with AMP enabled if no image is used in the post, Google Search Console gives an error:

> Image size smaller than recommended size

The recommended size is at least 1200px wide. However, on a page that has no images, the two images we load are the site icon and the author's gravatar.

#### Steps to reproduce
1. Starting at a blog post on a simple site without an image 
2. Load the AMP version by appending /amp to the URL [example on my test site](https://badaboomtest.wordpress.com/2019/09/05/testing/amp/)
3. View page source
4. View JSON object in head, which contains `ImageObject` and see there are two images smaller than 1200px.

Eg from my test site:
```
{"@context":"http:\/\/schema.org","@type":"BlogPosting","mainEntityOfPage":"https:\/\/badaboomtest.wordpress.com\/2019\/09\/05\/testing\/","publisher":{"@type":"Organization","name":"Premium Multi-user Test Site","logo":{"@type":"ImageObject","url":"https:\/\/s0.wp.com\/i\/favicons\/apple-touch-icon-60x60.png","width":60,"height":60}},"headline":"Testing","datePublished":"2019-09-05T07:26:20+00:00","dateModified":"2019-10-09T00:41:21+00:00","author":{"@type":"Person","name":"Kristen S."},"image":{"@type":"ImageObject","url":"https:\/\/1.gravatar.com\/avatar\/18bcc1fa8f451839396b2018b2b95e00?s=200&amp;d=identicon&amp;r=G","width":200,"height":200}}
```

#### What I expected

AMP pages should not generate errors in Google Search Console

#### What happened instead

An error of "Image size smaller than recommended size" was generated

#### Browser / OS version
n/a

#### Screenshot / Video
![amp-small-img](https://user-images.githubusercontent.com/2031017/66443994-28f5da80-ea8d-11e9-84e6-c361338edfc4.png)

#### Context / Source
#user-report 
#13694641-hc
#2406161-zd

**Comment by kristarella** [comment]
I marked as bug and enhancement as I'm not sure which it is.
I'm thinking a solution to this would be to not load the icon or gravatar if there are no other images, or add an option to set a default image for AMP pages when there is no other image larger than 1200px.

**Comment by NewsView** [comment]
Same issue here. My gravatar/WP profile image is causing the same "Image size smaller than recommended size" error. I would think this is a bug. I'm wondering how to go about getting Google to address this — or if my only option is to update the WordPress theme I'm using.

**Comment by kristarella** [comment]
> I'm wondering how to go about getting Google to address this — or if my only option is to update the WordPress theme I'm using.

If your error is exactly the same, then it is using the "reader" version of AMP and changing theme has no effect. 

I'm not sure if it's on us to remove the images, or whether we need to ask Google to ignore this error when the images are an icon and a gravatar.

**Comment by kristarella** [comment]
Another report 2624823-zen

**Comment by kristarella** [comment]
Reopening as I believe it's still an issue.

**Comment by kristarella** [comment]
Received another report 3960932-zd

**Comment by wojtekn** [comment]
We removed AMP support for Simple sites on July 11th, 2022 so this issue is not actual anymore. pdKhl6-lx-p2#comment-368
