### ISSUE TITLE
Reader: Discover attribution lines are showing oddly-shaped icons

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#3663]
In the [wordpress.com/discover](https://wordpress.com/discover) feed, we sometimes display oddly-proportioned attribution avatars/site icons. This appears to happen when Editors have uploaded a custom icon that is not square-shaped. We should be cropping these to a square when we display them.

#### Screenshots

<img width="376" alt="screen shot 2016-02-29 at 9 16 31 am" src="https://cloud.githubusercontent.com/assets/1202812/13396927/49e75958-dec5-11e5-954e-f84692c006e7.png">
( [Post](https://wordpress.com/read/post/id/53424024/10909) ) 

<img width="380" alt="screen shot 2016-02-29 at 9 16 50 am" src="https://cloud.githubusercontent.com/assets/1202812/13396930/49f0275e-dec5-11e5-9299-a2a441ca6ae4.png">
( [Post](https://wordpress.com/read/post/id/53424024/10889) )

<img width="364" alt="screen shot 2016-02-29 at 9 16 56 am" src="https://cloud.githubusercontent.com/assets/1202812/13396928/49ee661c-dec5-11e5-950f-f38c69d3002d.png">
( [Post](https://wordpress.com/read/post/id/53424024/10848) )

<img width="476" alt="screen shot 2016-02-29 at 9 17 06 am" src="https://cloud.githubusercontent.com/assets/1202812/13396931/49f2574a-dec5-11e5-9ed8-b20dd3869741.png">
( [Post](https://wordpress.com/read/post/id/53424024/10825) )

<img width="418" alt="screen shot 2016-02-29 at 9 17 25 am" src="https://cloud.githubusercontent.com/assets/1202812/13396929/49ef8696-dec5-11e5-98d0-c389444e7b66.png">
( [Post](https://wordpress.com/read/post/id/53424024/10343) )

**Comment by lancewillett** [comment]
I can repeat this — testing in recent Discover feed with https://wordpress.com/discover using Mac-n-Chrome.

![screen shot 2016-04-28 at 4 45 58 pm](https://cloud.githubusercontent.com/assets/66797/14904896/c7fc4f64-0d60-11e6-9d0a-9dbe817c5548.png)

Look next to "Originally posted on" to see the squished avatar image.

**Comment by kjellr** [comment]
Should be fixed now — just gave a run through the Discover feed and couldn't reproduce anymore. 

We corrected this in the API, rather than on the front-end in Calypso: Discover now auto-crops icons down to a square when serving them up through the `discover_fp_thumbnail_url` metadata property. 👍 

cc @hakanb
