### ISSUE TITLE
Flow: add new site option at Domains Add screen

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#36637]
#### Reason
- Many users will miss the Add new site option, mainly when they have more than one site. It's too hidden in the Switch site menu.
- Also, many users don't know the difference between a site and a domain, so they will add a new domain and they will get confused when they realize their new domain is redirecting to their current site.
- They need to contact support to create a new site and move the domain to it.
- Chat sample: #1573822-hc

**Comment by Aurorum** [comment]
> Also, many users don't know the difference between a site and a domain, so they will add a new domain and they will get confused when they realize their new domain is redirecting to their current site

This is a separate issue being tracked in #27932, with a proposed solution currently on hold in #34990.
