### ISSUE TITLE
Cover Block, when use large image full width, get  "The backup of this post in your browser is different from the version below" when reopen the page

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#36649]
#### Steps to reproduce
1. On a new page, add a cover block
2. Use a large image (5 MB)
3. Set image to full width
4. Save the page
5. Exit the page
6. Reopen the page

#### What I expected
The page does not reopen with the error.

#### What happened instead
The page opened with error.

![image](https://user-images.githubusercontent.com/29057562/66563806-28df0300-eb91-11e9-9769-57c34e910ccd.png)

#### Browser / OS version
Chrome/MacOS 10.14

#### Screenshot / Video
https://cld.wthms.co/QqVGJV

The image file is attached.

![dsc01199-e1570505483275-1a](https://user-images.githubusercontent.com/29057562/66564219-10bbb380-eb92-11e9-8e61-ba84e818e06e.jpg)

**Comment by kosiew** [comment]
Yesterday, I thought the issue was with large images.

Today, while filing another bug https://github.com/Automattic/themes/issues/1511, I again encountered this issue.

The steps are in the issue.
After Publish, and reopen the page for edit, I got this error too.

![Screenshot](https://cld.wthms.co/bKyvoF+)
*if image does not load, please click on this link  : https://cld.wthms.co/bKyvoF*

The post is https://wpexford101.wordpress.com/2019/10/11/test-classic-block-center-image/

**Comment by synora** [comment]
Noting that I'm unable to replicate the initial issue. The second issue about the Classic Block and the small image has been resolved at https://github.com/Automattic/themes/pull/1547. Closing this issue as I'm unable to replicate the initial issue.
