### ISSUE TITLE
Symfony...Check that the webserver is running, and that there are no firewalls blocking Facebook's crawlers

### ISSUE THREAD

**Issue by wispas** [Automattic/wp-calypso#36640]
Could Not Connect To Server | Check that the webserver is running, and that there are no firewalls blocking Facebook's crawlers.
-- | --

#### Steps to reproduce
1. Starting at URL:
2.
3.
4.

**Comment by wispas** [comment]
![OGTag](https://user-images.githubusercontent.com/20275356/66533747-9fa2de80-eb46-11e9-9e25-d59a093ed16c.PNG)

**Comment by davipontesblog** [comment]
Hi @wispas 👋 
We haven't seen any reports on this one since your report so we will close for now and we ask you to reopen with more information if still an issue.
Cheers,

**Comment by wispas** [comment]
Hi @davipontesblog this issue solved Thank you.
Issue was on closed port. After  turn off firewall
