### ISSUE TITLE
Enable support for creating sites as private via Calypso signup which will instantly be transferred to Atomic

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#36657]
We need to pull out the workarounds that we put in place to avoid creating sites as private which would be immediately transferred to atomic on checkout.

Additionally, we need to pull out the functionality that warns & then launches a site upon upgrading to a plan that would do the same.

**Comment by jblz** [comment]
Working on this in https://github.com/Automattic/wp-calypso/pull/36663

**Comment by JoshuaGoode** [comment]
It appears that this was initially completed via https://github.com/Automattic/wp-calypso/pull/36663

However, we no longer launch sites private by default and utilize Coming Soon v2 for new and unlaunched sites.

Closing.
