### ISSUE TITLE
Menus: unable to save menu

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#3667]
Related to this ticket: 2559800

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/menus/example.com
2. Try to save the menu.
3. Receive the error pop-up: `There was a problem saving your menu.`

#### What I expected
To be able to save the menu.

#### What happened instead
The error.

#### Browser / OS version
Chrome 48.0.2564.116 (64-bit)

#### Screenshot / Video
Screencast: http://recordit.co/WRD3qj54pk

**Comment by eduardozulian** [comment]
Got the same issue with a huge menu: http://yesinspire.com/

Here's a screencast showing the problem.

![menu](https://cloud.githubusercontent.com/assets/1136160/13444038/c2688604-dfe2-11e5-8a94-d6491812415a.gif)

**Comment by BandonRandon** [comment]
This error is found in the code here: https://github.com/Automattic/wp-calypso/blob/8a2656ee974afe96f25423d53ab3e113e6c046f5/client/lib/menu-data/menu-data.js#L394

It comes up every now and again in chat. It would be great to know if there is a work around.

**Comment by catkit** [comment]
Other ticket with the same problem: 342227-c

@BandonRandon they may use the WP dashboard or the Customizer as a work around.

**Comment by BandonRandon** [comment]
Thanks @catkit I've been directing users to the Customizer when I come across it. I should have been more clear in my question. Is there a work around in Calypso to prevent this error or must we direct the user elsewhere?

**Comment by catkit** [comment]
yet other ticket: 346983-c

**Comment by rachelmcr** [comment]
There was one case where this error was triggered after the site changed themes. In that case, if the site had a custom menu set to a menu location, and the new theme did not have the same menu location, this error was triggered. That case has been fixed. (ref: p2UL9c-2xw-p2)

Are you still running into this error? If so, it would help if you can check the HTTP request/response headers in the console for additional details about the error.

**Comment by lancewillett** [comment]
Please re-open or start a new ticket if this pops up again — closing as fixed.
