### ISSUE TITLE
FSE: Site Description and + icon overlap

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36671]
The + button is right on top of Site Description block so it’s easy to trigger that instead, when trying to add a description.

<img width="613" alt="screen-shot-2019-10-07-at-15 15 02" src="https://user-images.githubusercontent.com/1182160/66645536-0649fa00-ec24-11e9-8b83-c62110d52c3a.png">

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
