### ISSUE TITLE
FSE: update template updated message to reference specific template part

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36679]
When you update the header area you see a message that says “template part updated”. Is it possible to switch this to “header updated”?

When updating Header/Footer area now, the success message that the user sees is "template part updated". One suggestion that was raised in p7DVsv-7qC-p2 (#comment-23865) was to change this to "Header/Footer updated".

cc @apeatling @shaunandrews @selectedselections for thoughts on this.

**Comment by shaunandrews** [comment]
Yes, please.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
