### ISSUE TITLE
FSE: empty placeholder in template part area

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36672]
If you add an empty paragraph block at the end of Header and save it without typing any text in, upon returning back to page you'll see the following:

<img width="613" alt="screen-shot-2019-10-07-at-15 34 56" src="https://user-images.githubusercontent.com/1182160/66645721-6fca0880-ec24-11e9-8c94-95e803940da3.png">

However you can't type in this area immediately and this might be confusing for users.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
