### ISSUE TITLE
FSE: empty editor page after completing the signup

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36676]
We received one report of blank editor page after completing the FSE signup flow:

<img width="1644" alt="6RmeRsmaWI" src="https://user-images.githubusercontent.com/1182160/66647095-401cff80-ec28-11e9-8e08-ff028d74b12c.png">

However, none of us have been able to reproduce it so far. The issue disappeared after launching the site. If someone gets into this state it would be extremely helpful to capture the console log output if any, and preserve the site in that state for further investigation.

Reported steps for the above case:
1. Visit https://horizon.wordpress.com/start/test-fse in a private or incognito window (because you’re about to create a new user.)
2. Create a new user on that page.
3. Select the business vertical for your site.
4. Go through the remaining steps.
5. Edit a page and you should get the Full Site Editing experience.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
