### ISSUE TITLE
FSE: scrolling on themes page doesn't work

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36673]
Scrolling on Themes page in Calypso sometimes doesn't work. This is likely not related to FSE but we should at least investigate.

Quoting @creativecoder report:
> Scrolling on the themes page in Calypso wasn’t working for the first 2 FSE sites I created, but then it started working on all sites after I created a non-FSE site. (This could have been an unrelated Calypso bug, but I’m mentioning it here just in case).

**Comment by lschuyler** [comment]
I'm hitting this often when trying to set up a new free site and trying to change the theme here: https://wordpress.com/themes/

I can't scroll down, or use Page Down. The only way to see themes lower on the page is to drag my browser window to a larger size. No amount of refreshing or clicking around on the page seems to fix it.

Browser's Javascript console reports this error:
`Uncaught ReferenceError: fullSiteEditing is not defined`.

Browser: Version 78.0.3904.97 (Official Build) (64-bit)
Mac 10.15.1

**Comment by vindl** [comment]
This is a special case and duplicate of https://github.com/Automattic/wp-calypso/issues/35305 and will be resolved in https://github.com/Automattic/wp-calypso/pull/37902.
