### ISSUE TITLE
FSE: duplicate About page after site creation

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36674]
There has been an intermittent issue of duplicated About page being created during FSE signup flow. It's not clear whether the same is happening with Contact page - I haven't seen any cases so far.

It's been really hard for us to reproduce it, so if someone reports it please try to capture the site URL so we can examine that particular case in more detail.

Update borked site: https://hungrypeopleneedtoeat.wordpress.com

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
