### ISSUE TITLE
FSE: try & customize for Maywood leads to a blank screen

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36680]
The Try & Customize option within the theme showcase for Maywood leads to a blank customize screen:

![Screen Shot 2019-10-09 at 10 59 11](https://user-images.githubusercontent.com/1182160/66653436-53d06200-ec38-11e9-9fe7-57389ccb209f.png)

**Comment by apeatling** [comment]
I think we should be retrying this, but only for themes that have FSE enabled: https://github.com/Automattic/wp-calypso/pull/36044

**Comment by mattwiebe** [comment]
@apeatling I'm going to take an approach that just fixes the underlying bug so **Try & Customize** works again in these cases.

(This is because we don't have enough info on the Calypso side to detect FSE themes at this point.)
