### ISSUE TITLE
Draft header count hover color inconsistent/unreadable 

### ISSUE THREAD

**Issue by zandyring** [Automattic/wp-calypso#36685]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/zandy.blog (or, any blog with a draft post)
2. View the draft header count: 
<img width="257" alt="Screen Shot 2019-10-11 at 11 12 52 AM" src="https://user-images.githubusercontent.com/7304712/66663105-19ef6380-ec18-11e9-814b-3993ffac1a17.png">
3. Hover over the header count:
<img width="268" alt="Screen Shot 2019-10-11 at 11 13 24 AM" src="https://user-images.githubusercontent.com/7304712/66663151-2a9fd980-ec18-11e9-9d66-d23c62df24a0.png">
4. This also happens when you click on the number:
<img width="350" alt="Screen Shot 2019-10-11 at 11 08 06 AM" src="https://user-images.githubusercontent.com/7304712/66663197-3ab7b900-ec18-11e9-82ba-347f3fddb52d.png">

#### What I expected
That the background color wouldn't move on hover.

#### What happened instead
The background color moved to exclude the number on hover, obscuring the number partially.

#### Browser / OS version
Chrome Version 77.0.3865.90 (Official Build) (64-bit) / MacOS 10.14.6

#### Screenshot / Video
See above

#### Context / Source
#reallife #dogfooding

**Comment by Aurorum** [comment]
PR in #36690 for this issue. :)
