### ISSUE TITLE
Domains: Content width changes throughout flow

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#36693]
The width of the content on desktop viewports changes throughout the flow of searching for or transfer/mapping a domain. This causes inconsistencies that make it feel broken.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/{site}
2. Select the option to use a domain you own.
3. Choose one of the transfer or map options.

#### What I expected
The width of the content to remain uniform throughout the process.

#### What happened instead
The width changes from full width (initial Domain Search screen), to narrow (Transfer or Mapping), back to full width (enter a URL).

#### Screenshot / Video
![Screenshot_2019-10-11 Domain Search ‹ Dan Hauk — WordPress com](https://user-images.githubusercontent.com/448298/66680024-99dbf480-ec3d-11e9-8796-acbff7604c19.png)
![Screenshot_2019-10-11 Use Your Own Domain ‹ Dan Hauk — WordPress com](https://user-images.githubusercontent.com/448298/66680041-9cd6e500-ec3d-11e9-9c38-e2cdcabe6aa3.png)
![Screenshot_2019-10-11 Transfer a Domain ‹ Dan Hauk — WordPress com](https://user-images.githubusercontent.com/448298/66680047-9f393f00-ec3d-11e9-9709-0ca0993be276.png)

**Comment by klimeryk** [comment]
Related issue for the more general problem: https://github.com/Automattic/wp-calypso/issues/7096

**Comment by klimeryk** [comment]
I've closed the parent issue and will close this one as well - this needs a proper design overhaul and there does not seem to be bandwidth for that right now.
