### ISSUE TITLE
Domains: Back button unpredictable behavior

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#36692]
The back button when search for a domain or going through the transfer/mapping flow doesn't behave as expected. In each case I'm taken back to the very beginning of the domain search rather than the previous screen.

Use cases for changing the behavior:

* As a user I search for a domain. After browsing a bit I accidentally select the wrong one. I click the back button but I'm taken all the way to the beginning. Now I have to start over and remember what I searched for to get my previous search results.
* As a user I click to use my own domain, then click the transfer option. I decide I'd rather map the domain instead so I click back. Now I have to start over instead of just clicking the mapping option.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/{site}
2. Search for a domain.
3. Select a domain.
4. Click the back button or use the browser's back button.

1. Starting at URL: https://wordpress.com/domains/add/{site}
2. Click to use a domain you already own.
3. Select the transfer or mapping option.
4. Click the back button or use the browser's back button.

#### What I expected
To be taken to the previous screen in the flow.

#### What happened instead
I'm taken all the way to the start of the domains flow.

#### Screenshot / Video
https://cloudup.com/cwbBYo0yZfB

**Comment by ctoynbee** [comment]
@danhauk I've uploaded a video of how the flow is working currently in my development environment.

Would you say it's working as you'd hope it would now:

https://www.dropbox.com/s/jomj29qlecgmwpp/36692.mov?dl=0

**Comment by danhauk** [comment]
@tophertoy Thanks for the ping here. I just took it for a spin in production and the flow seems to be fixed. I'll close this out.
