### ISSUE TITLE
CoBlocks: Hyperlinks getting removed from pictures when editing the Masonry Gallery.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36691]
Reported by @guicmazeredo in https://github.com/godaddy/coblocks/issues/983 – adding here for tracking.

> **Describe the bug**
> When editing a Masonry gallery to add a new picture, the hyperlinks that were set for the pics that were in the gallery get removed once the new picture is added.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Add a Masonry Gallery to a page or post.
> 2. Add a few images to the gallery.
> 3. Click on one of the images and select **Custom URL** under the **Link settings** tab. Then add URL to one or more pics.
> 4. Then, click on the **Edit** button on the gallery toolbar and add an image to the gallery.
> 5. Check the images that were in the gallery already and notice that the URLs set in the previous step are gone.
> 
> **Isolating the problem:**
> Mark completed items with an [x].
> 
> * [x]  This bug happens with no other plugins activated
> * [x]  This bug happens with a default WordPress theme active
> * [ ]  This bug happens **without** the Gutenberg plugin active
> * [x]  I can reproduce this bug consistently using the steps above
> 
> **WordPress Version**
> WordPress 5.2.3

**Comment by gwwar** [comment]
This was fixed upstream by https://github.com/godaddy/coblocks/pull/984 ✨We should be able to close out this tracking issue when we update to CoBlocks 1.16.0 on WordPress.com

**Comment by kwight** [comment]
I've confirmed that this is fixed on Horizon, running CoBlocks 1.16.1.

**Comment by kwight** [comment]
CoBlocks 1.16.1 is now in prod, and this issue is fixed.
