### ISSUE TITLE
FSE: blog posts page

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36711]
FSE users are not currently able to designate a blog posts page for their site. 

![Screen Shot 2019-10-07 at 14 54 26 (1)](https://user-images.githubusercontent.com/1182160/66739150-5ddca580-ee70-11e9-89c8-c10a82d9ff8d.png)

That option is usually exposed in the above menu, but for FSE sites there is only `Set as Homepage`.

The current way of doing this is adding a Blog Post Listing block to your static page and setting it as homepage for example. However, this approach has limitations - it will show only up to 50 blog posts, and clicking on `View All Posts` will just open up one of the existing static pages that has been set as homepage.

**Comment by vindl** [comment]
This will be handled by @Automattic/ajax and their work on improving the Newspack version of this block.

**Comment by apeatling** [comment]
See https://github.com/Automattic/Dotcom-roadmap/issues/55
