### ISSUE TITLE
Domains: wpcomstaging domain blank loading screen

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#36727]
#### Steps to reproduce
1. On a WordPress.com site that has installed plugins or custom themes, go to `Manage > Domains`
2. Click on the automatically provisioned `example.wpcomstaging.com` domain name.

#### What I expected
* To view/manage the domain name like other domain names.
* Some information on what the `wpcomstaging` domain actually is.
* Enhancement: An ability to change the wpcomstaging address as referenced in #36301 

#### What happened instead
* A blank loading screen that never updates:

![Screen Shot 2019-10-14 at 11 50 00 AM](https://user-images.githubusercontent.com/15803018/66771970-d2b3dd80-ee78-11e9-8338-ae92f6e9cbde.png)

#### Browser / OS version
* Chrome Version 77.0.3865.90 (Official Build) (64-bit)

#### Context / Source
#user-report
p9F6qB-4bR-p2

**Comment by klimeryk** [comment]
cc @aidvu - can you look into this one? Is it something that recently broke?

**Comment by aidvu** [comment]
I think @eltongo and @daledupreez did some work on it recently. :)
