### ISSUE TITLE
Editor: Password protected posts are pretty buggy

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#3673]
Now that the bugfix in #3628 is merged you should see the following additional buggy behavior in the editor.

1. Load a password protected post in the editor.
2. Backspace over the password.  Post visibility magically changes to public.
3. Click "Password" again.  The error message about an empty password reappears, but the password is no longer blank.
4. Backspace over the password again.  This time it appears to work as expected.

<img width="250" src="https://cloud.githubusercontent.com/assets/227022/13411182/617b0358-df01-11e5-8cfe-1c3842755fae.gif">

It looks like the `EditorVisibility` component is due for a rewrite - there is a lot of convoluted and subtly broken logic in there to attempt to handle password-protected posts, and especially the error condition of an empty password.

**Comment by nb** [comment]
#3827 doesn’t fix it all, so reopening. See [this comment](https://github.com/Automattic/wp-calypso/pull/3827#issuecomment-195054783) on #3827.

**Comment by DanReyLop** [comment]
@aduth What steps can you follow to save a post with the default (invalid) " " password? Since you can't close the popover until you choose a valid password, you can't interact with the UI, so how is that possible?

**Comment by aduth** [comment]
Spent some time trying to recreate the issue described at https://github.com/Automattic/wp-calypso/pull/3827#issuecomment-195054783 and was not able, so I'll consider this resolved unless I encounter it again.
