### ISSUE TITLE
Importers: Button capitalization consistency

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#36734]
When you finish a successful import, the primary action brings you to a screen where you can "View Site":

<img width="382" alt="16 (1)" src="https://user-images.githubusercontent.com/2124984/66774830-9b512b00-ee90-11e9-89f7-91ab739ad6e6.png">

Clicking it brings you to the site previewer, which has a similar primary action button to "Visit site":

<img width="382" alt="18 1" src="https://user-images.githubusercontent.com/2124984/66774827-9a1ffe00-ee90-11e9-9d6f-1bd1b29829d1.png">

The first primary action uses Title Case, the second uses Sentence case. Which is correct?

This is likely not restricted to the Importers section. I have a feeling we're inconsistent about how we capitalize text within buttons across Calypso. It stands out in this case because the two buttons occur one after the other in the flow, and have similar contents.

**Comment by sixhours** [comment]
A brief audit of other buttons across Calypso suggests we are indeed inconsistent about this, but we lean toward Title Case more often than Sentence case.

**Comment by danhauk** [comment]
I think this inconsistency comes from the previous attempt at standardizing via the Muriel design system. Before that, we were more or less standardized in `Title Case`, and as the Muriel/Material thing progressed we were starting to standardize to `Sentence case`.

According to the [README for the button component](https://github.com/Automattic/wp-calypso/tree/83cefb18976d90ddee3ca9518c7cb375b0ff1a14/packages/calypso-ui/src/button#general-guidelines) we're to use sentence case. I think this is also they way core is standardizing but could be wrong.
