### ISSUE TITLE
FSE: missing back to page button in wp-admin

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36769]
`Back to page` button that allows users to navigate back to previous page after editing a template part is now visible only in Gutenberg's full screen mode. This is not a problem in Calypso, since Gutenframe forces it. However, in wp-admin it's still possible to disable it and end up in a state where the current sequential full page editing flow is broken.

This is likely not as critical for new Dotcom users since they tend to stay in Calypso (and the Gutenframe preference will persist), but it might be a problem for Atomic users since they rely on wp-admin flows.

<img width="1678" alt="Screenshot 2019-10-15 at 11 31 22" src="https://user-images.githubusercontent.com/1182160/66819485-5a641f80-ef3f-11e9-8051-061f22fdf0ae.png">

cc @shaunandrews for thoughts on how to handle this.

**Comment by shaunandrews** [comment]
I'd suggest we look at showing the button regardless of the full-screen mode.

**Comment by vindl** [comment]
> I'd suggest we look at showing the button regardless of the full-screen mode.

Any ideas about placement? Putting it before the Block Inserter might be weird. 🤔
