### ISSUE TITLE
Classic editor's editing area shrinking on iOS 13

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#36763]
When using the classic Editor on an ipad mini, the editing area gets shunk.

![Screen Shot 2019-10-15 at 16 20 53](https://user-images.githubusercontent.com/24914028/66809176-d1151300-ef67-11e9-96d5-8245fabcd8a4.png)

#### Steps to reproduce
1. Switch a site back to the Classic Editor
2. Add dummy content to the post.
3. View the post in Responsive Design Mode from Developer Tools set to ipad Mini 4.
4. Refresh the page.

#### What I expected
The editing area would expand to fit the entire screen.

#### What happened instead
The editing area shrinks to be less than half of the page.

It appears to be a set height that is added to the iframe of the tinymce that is doing this.

![Screen Shot 2019-10-15 at 16 25 19](https://user-images.githubusercontent.com/24914028/66809504-7203ce00-ef68-11e9-871d-7a02157aab37.png)

#### Browser / OS version
 iPad mini 4, iPad OS 13.1.2, Google Chrome/Safari/Firefox

#### Screenshot / Video

Video: https://cld.wthms.co/oMatiG

#### Context / Source
2409148-zen

**Comment by joweber123** [comment]
This seems to be the same issue as reported here as well 

https://github.com/Automattic/wp-calypso/issues/36714#issue-506605867

**Comment by AtrumGeost** [comment]
Got another report here 2417542-zen

Ran a couple of tests and found out it is not only happening on iPad mini but also on iPhone, and it is specific to iOS 13 (iOS 12 and Android works well).

Updating the GH issue title :)

**Comment by joweber123** [comment]
Very interesting and good catch!

**Comment by joweber123** [comment]
Another report here: #2459594-zen

IOS 13.1.3 Ipad Pro.

**Comment by joweber123** [comment]
Another report here: #16462227-hc

**Comment by rachelmcr** [comment]
@apeatling Heads up - this severely breaks the classic Calypso editor on iOS devices.

**Comment by Robertght** [comment]
Found another case in #2511869-zen.

**Comment by lancewillett** [comment]
Thanks for the report.

Just to set clear expectations, supporting the old Classic editor is lower priority for teams versus building compatibility and quality in the Gutenberg editor.

**Comment by apeatling** [comment]
Bumping this to critical since it's a rough one, and adding to Serenity's board after a chat with Kerry. They'll prioritize it accordingly.

**Comment by mmtr** [comment]
This can be reproduced on Safari desktop by forcing an iOS user agent:

![image](https://user-images.githubusercontent.com/1233880/69877305-2613ab00-12c2-11ea-8cf7-da5d422f1cd9.png)

**Comment by kwight** [comment]
I can also reproduce with @mmtr 's tip in Safari. The difference is definitely the `height` attribute on the edit content iframe; I wonder if it's something involving [resize](https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/wpcom-autoresize/plugin.js#L138).
