### ISSUE TITLE
Marketing Survey: Fix missing import warning

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#36768]
When building Calypso, the following warning is shown:

```
WARNING in ./client/components/marketing-survey/cancel-purchase-form/index.jsx 510:25-49
"export 'IMPORT_SURVEY_STEP' (imported as 'steps') was not found in './steps'
```

You can see that this name, `IMPORT_SURVEY_STEP`, imported and accessed here:
https://github.com/Automattic/wp-calypso/blob/5193409e8df1af61e4991f97cb625b25e2a50f2b/client/components/marketing-survey/cancel-purchase-form/index.jsx#L32
https://github.com/Automattic/wp-calypso/blob/5193409e8df1af61e4991f97cb625b25e2a50f2b/client/components/marketing-survey/cancel-purchase-form/index.jsx#L560

Is not a named export of the module:

https://github.com/Automattic/wp-calypso/blob/5193409e8df1af61e4991f97cb625b25e2a50f2b/client/components/marketing-survey/cancel-purchase-form/steps.js#L2-L8

**Comment by sirreal** [comment]
Seems to have been introduced by #36272

cc: @Automattic/start-samus

**Comment by jonathansadowski** [comment]
Sorry 'bout that. Thanks for noticing @sirreal. Fix incoming.

**Comment by sirreal** [comment]
Thanks for the fix 👍
