### ISSUE TITLE
Syntax Highlighter Block rendering > as &gt;

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/wp-calypso#36778]
#### Steps to reproduce
1. Starting at URL:
2. Add SyntaxHighlighter Code Block on a page/post.
3. Add any code that contains the `>` character or use the below code for example:

```
 // injector.ts
let mocks:{[id: string] : () => any} = {}

export const injectMock = <T>(factory: () => T, mock: () => T) => {
  mocks[factory.toString()] = mock
}
  
export const clearMocks = () => {
  mocks = {}
}

export const mockable = <T>(factory: () => T): T => {
  if (typeof mocks[factory.toString()] !== 'undefined') {
    return mocks[factory.toString()]()
  }
  return factory()
}
```
4. Save or Publish the page/post.

#### What I expected

`>` should appear as is when the page/post is previewed or viewed at the front end.

#### What happened instead

The `>` character changed to `&gt;` when previewed or viewed at the front end. I have tested this on a test website with Chrome 77 and macOS Catalina and was able to replicate this.

#### Browser / OS version

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

#### Screenshot / Video

NA

#### Context / Source

13467026-hc
2422567-zen

**Comment by zdenys** [comment]
Since a fix hasn't been implemented yet, I provided the user with the workaround of converting the `SyntaxHighlighter Code Block` into `Code Block`:

![](https://cld.wthms.co/7NBlkg+)
_Link: https://cld.wthms.co/7NBlkg_

**Comment by mriyazuddin** [comment]
Thanks Denys!

**Comment by kylemcph** [comment]
Recording another instance of this bug: 11028813-hc → [2460256-zen](https://woothemes.zendesk.com/agent/tickets/2460256)

**Comment by kylemcph** [comment]
Recording another instance of this bug: 11028813-hc → 2460256-zen

**Comment by gwwar** [comment]
Potentially related https://github.com/WordPress/gutenberg/pull/17994

**Comment by mkaz** [comment]
Fixed on WordPress.com applying this fix.
Automattic/syntaxhighlighter#3
