### ISSUE TITLE
Spec for the Domains Flow

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#36782]
Description | The domains component is a persistent element on the Gutenberg master bar to allow upgrades into paid domains. It will be available for all users, both new and existing. It should not affect the current signup flow.
-- | --
Goals | Test out the Gutenberg ‘modular’ onboarding concept with the domains block as the first module. Data also shows that active domains drive plan retention up and reduce refund rates.
Metrics | Improve purchase conversion rates for plans and domains for both new and existing users.
Stakeholders | @amamujee @themeshaper @johnpercivalhackworth @kelliepeterson
Team (roles; which might be filled by the same person) | Product Lead: Aadil @amamujeeEng Lead: Javi @johnpercivalhackworthDesign Lead: @themeshaper

https://docs.google.com/document/d/1mnXVg-ksOWF89XjoWD68Hiwbss4zIzc3W0Cp06fyTyA/edit#

**Comment by davipontesblog** [comment]
Closing this as it's been moved to "Done" in the Guteboarding project.
