### ISSUE TITLE
FSE: migrate old MVP sites to FSE with Maywood

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36798]
A placeholder task so we don't forget to migrate existing MVP users to FSE in the end.
Some preparatory work has already been done here in:

- https://github.com/Automattic/wp-calypso/issues/32942
- https://github.com/Automattic/wp-calypso/issues/32824

**Comment by vindl** [comment]
Just a note that our tentative strategy here would be to just mark MVP sites with `full-site-editing` sticker. A couple of reasons behind that decision:

- MVP sites are now on Modern Business, so explicit migration would have to forcefully switch these users to a different theme and change the appearance of their site - not good.
- Even if we preserved them on FSE version of Modern Business some visual changes are bound to happen.
- With a growing pool of FSE supporting themes, they will seamlessly be migrated once/if they initiate a theme switch.
- We should keep MVP stickers for them in case they decide to revert to their original theme and look.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
