### ISSUE TITLE
Gutenberg: Fully-justified styles do not always display on the front-end.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36794]
WP.com offers full justification for text. While the feature will always behave as expected in the editor, it will not always display properly on the front-end.

<img width="1447" alt="Screen Shot 2019-10-15 at 1 48 37 PM" src="https://user-images.githubusercontent.com/349751/66868683-a1a7db80-ef52-11e9-8a38-30641ec96ab6.png">

**Comment by kwight** [comment]
This is due to faulty logic while enqueuing `common.css` – fix is in D34065-code.

**Comment by mmtr** [comment]
> This is due to faulty logic while enqueuing `common.css` – fix is in [D34065-code](https://href.li/?https://code.a8c.com/D34065).

Is this the same issue as https://github.com/Automattic/wp-calypso/issues/36770?

**Comment by Robertght** [comment]
Yes - I'll close that one. :)

**Comment by kwight** [comment]
Fixed in D34065-code.
