### ISSUE TITLE
Gutenberg: Paragraph Block: "Open link in New tab" option for link button doesn't save in draft

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#36796]
#### Steps to reproduce
1. Add a paragraph block
2. Select a word and turn it into a link clicking the link button
3. Save the draft
4. Click the word to edit the link
5. Select the option to open link in new tab

#### What I expected
This is a post edit and should trigger the Save draft option

#### What happened instead
It didn't trigger it and didn't save the option.

#### Screenshot / Video
![link-bug](https://user-images.githubusercontent.com/3521683/66871648-7b963180-ef7a-11e9-9a41-8d662e193159.gif)

#### Context / Source

#user-report

**Comment by catkit** [comment]
User reported this here: #15561067-hc

**Comment by gwwar** [comment]
Recently fixed by @glendaviesnz in https://github.com/WordPress/gutenberg/pull/17794 Simple and Atomic sites should be using Gutenberg 6.7 so the fix should be in production.
