### ISSUE TITLE
Get a playground-based version of the block editor working

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#36806]
At this point, I think it’s safe to assume that we are going to be working with the editor that is being used by the FSE-plugin for a while (which ATM is a regular block editor provided by the Gutenberg Plugin, which we use to have more control over which version of Gutenberg we use in production). 
So if we are going to build our onboarding experience around the current system, we need the Gutenberg instance we use in production to be customizable. Right now, the FSE-wpcom plugin just uses a vanilla Gutenberg instance, which is not easy to customize. When talking with the Gutenberg-core folks about how to do this, their suggestion is to stop using the prepackaged version of the Gutenberg editor and just build whatever we need from its components. If we don’t do this first, every bit of custom UI we would need to add would need to be “hacked” there in a non-orthodox way, which would make things brittler in the long run. On the other hand, if we refactor the plugin to make that editor build from Gutenberg parts, it won’t only make our onboarding work easier, but also would open more possibilities for everyone working on this.

So let's see what we need to do to make a complete block editor built from its basic components. 

- [ ] Let's get everything in gutenberg's editor.js and put it in our playground-editor, and see how much it works right away and what we need to patch 
- [ ] Get a way to 'inject' content (a post, a page, etc) into the editor

**Comment by davipontesblog** [comment]
Closing this as it's been moved to "Done" in [Gutenboarding](https://github.com/orgs/Automattic/projects/127#card-28759811).
