### ISSUE TITLE
Permalinks: Consider adding a Copy Permalink item to the post list dropdown.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36826]
Consider adding a Copy Permalink item to the post list dropdown. Currently there is no easy way to get permalinks from the post or page list views.

<img width="1197" alt="Screen Shot 2019-10-16 at 9 21 32 AM" src="https://user-images.githubusercontent.com/349751/66938816-bccc2700-eff6-11e9-92d5-d1725c9b92a8.png">

**Comment by shaunandrews** [comment]
Its also using older icons, which don't match up with the newer icons in the sidebar.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/191598/66950938-58758b80-f027-11e9-8516-cc24d5db1980.png">
