### ISSUE TITLE
Previews: Some Jetpack site modal previews may fail with connection errors. [5]

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36824]
Some Jetpack site modal previews may fail with connection errors. This doesn't seem to happen with all JP sites, and doesn't happen with simple sites.

![2019-10-16_at_11 11_am](https://user-images.githubusercontent.com/349751/66938474-12540400-eff6-11e9-8d7a-45110a69406c.png)

**Comment by gwwar** [comment]
I think this can happen when layers outside of WordPress explicitly set `X-Frame-Options` to `same-origin`, for example in an nginx config. When this happens, I think we can gracefully fallback to a new tab preview instead of attempting to iframe this.

**Comment by gwwar** [comment]
If there are general iframe nonce issues, whitelisting works in the following way:

1. In Calypso the preview iframe src is set to something like `https://gwwar-at55.blog/2018/11/29/the-journey-begins/?iframe=true&theme_preview=true&frame-nonce=examplenonce&cachebust=1`

Note the `frame-nonce` parameter.

https://github.com/Automattic/wp-calypso/blob/eb4662440234155e8c10eb1921477f8e8cb4c5b4/client/components/web-preview/content.jsx#L184

2. This is validated in https://github.com/Automattic/jetpack/blob/970c62b90addcd0894c1a59a45b658d10475ea30/class.frame-nonce-preview.php#L49 

See original issue in https://github.com/Automattic/jetpack/pull/4692. (Note that the block-editor does this in a slightly different way in https://github.com/Automattic/jetpack/pull/11354/files#diff-5bc82dd7b78333ce5067bd34d92debc8R46 ). See also D2472-code for the xml rpc request handling.
