### ISSUE TITLE
VideoPress: Newly-converted Video blocks are not playable.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36836]
Once a VideoPress block finishes uploading and converting, it displays its UI. However, the UI is inaccessible (it's not possible to click on the Play button for example).

The preview ends up being an iframe within an iframe, which could be related.

**Comment by mmtr** [comment]
It is not the first time this issue comes up 🙂. As said in D30868-code, this behavior is intentional:

> > I also can't play the video at all, or interact with any of the controls. (This is the case with two videos I've had in my library for a while; a new VideoPress video added by URL is fully interactive)
>
> This is expected because we deliberately disable the video player so users don't interact accidentally with it when they want to focus the block ([#](https://github.com/Automattic/jetpack/blob/ebe6dc3793bdad659184d6d5868822686b11e355/extensions/blocks/videopress/edit.js#L140-L148)). Gutenberg also does the same with the default `core/video` block ([#](https://github.com/WordPress/gutenberg/blob/823ba362fa3ca0016ef5f690e8f267420b994697/packages/block-library/src/video/edit.js#L293-L304)). 
>
> You can interact with the player when adding the video via URL because Gutenberg doesn't render the `Disabled` component on `core/embed` blocks (`core/video` blocks are transformed to `core/embed` when using URLs).

Should we diverge from what `core/video` does and remove the disabled layer?

**Comment by kwight** [comment]
Lol, my memory is so short sometimes 🙃 

Intentional or not, it's hard not to see it as just broken from a user's point of view 🤔 My first thought was that this should work like nested?inner? blocks, where the first click is the parent (disabled) block, and the second click would be the inner video, with active UI. Looks like this was called Clickthrough, and [was disabled](https://github.com/WordPress/gutenberg/pull/17239) for desktop (presumably kept for mobile?), because desktops have enough padding to allow clicking the padding to select the block itself. If all this works as explained, it makes me wonder why the core Video block is disabled; need to play with it.

**Comment by mmtr** [comment]
Found some context about why Core disables the controls: https://github.com/WordPress/gutenberg/pull/7929#issuecomment-415107072

There is an open issue asking for a better visual on the video controls when they are disabled: https://github.com/WordPress/gutenberg/issues/9252

**Comment by kwight** [comment]
I'm happy to close this in deference to WordPress/gutenberg#9252 then.
