### ISSUE TITLE
Customizer: Opens site on closing

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#36830]
#### Steps to reproduce
1. Go to any Atomic site on Calypso.
2. Click on Design > Customize.
3. Click on the top left X to close the Customizer.

#### What I expected
To close the Customizer and go back to the Calypso's menu.

#### What happened instead
It opens the current site.

#### Browser / OS version
Chrome 77.0.3865.120
OS X 10.13.6

#### Screenshot / Video

![CustomizerAtomic](https://user-images.githubusercontent.com/16104522/66948200-9e801e80-f02a-11e9-94b7-4f0e6c38d546.gif)

#### Context / Source
#dogfooding

**Comment by zdenys** [comment]
Just x-linking #33208 and the further discussion is here: p8hWIX-3dW-p2

**Comment by eduardozulian** [comment]
Noting that the same applies if you use the Try & Customize function.

**Comment by zdenys** [comment]
Fixed as per p8hWIX-3dW-p2#comment-2098. Closing.
