### ISSUE TITLE
Safari Storage Prompt

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#36858]
#### Steps to reproduce
1. Using specific Browser/OS version below
2. Starting at URL: Varies

#### What I expected

To use the browser without prompting for storage

#### What happened instead

Users are periodically receive a variation of this message:

`Do you want to allow "https://wordpress.com" to use up to X.X GB of storage on your Mac?`

We haven't been able to reproduce the error locally, but have received multiple user reports. It seems to be related to the MacOS Catalina release and/or the Safari 13.0.1 release.

For several users, even after accepting the local storage the message continues to pop up. Even if the initial notification is necessary, having to repeatedly answer this prompt is a bad UX. The size of the data varies from several hundred MB to several GB.

#### Browser / OS version

Safari 13.0.1
MacOS 10.14.6

or

iPadOS13 with Safari

#### Screenshot / Video

<img width="1028" alt="Screen Shot 2019-10-17 at 09 58 01" src="https://user-images.githubusercontent.com/7596032/67015568-b4dab880-f0c4-11e9-8f84-21498d1065dd.png">

#### Context / Source

Discussed in p2EDhh-Us-p2
Reported in:
14160447-hc
1041772-hc (follow-up in 2382371-zen)
15565796-hc
15472317-hc
15522283-hc (This one is on iOS with iPadOS 13)
8031519-hc
2411378-zen (iPad)
14339371-hc

**Comment by edequalsawesome** [comment]
Another report in #16032814-hc

macOS 10.14.6, Safari 13.0.2, on a MacBook Air (2018). 

Suggested they try using Chrome or Firefox in the meantime, since AFAIK that hasn't been an issue with those browsers.

**Comment by msilbers** [comment]
Reports have also been made by a12s. They are not using the Progressive Web App when this happens so I've removed that part from the original issue

One example on MacBook, macOS Mojave version 10.14.6, Safari version 13.0.2

**Comment by goblinartificer** [comment]
also in #642068-hc , macOS Mojave Version 10.14.6 on a MacBook Air, requesting 12GB.

**Comment by thebud15** [comment]
As mentioned above, noting that this is taking place not only in Calypso, but also in HUD while chatting.

**Comment by carladoria** [comment]
reported also on #2447379-hc

**Comment by jonnyruzek** [comment]
Reported in #16217643-hc

Safari 13.0 on Mac OS X 10.15.0

**Comment by GeoJunkie** [comment]
If possible, please have users follow the steps at the bottom of this post: p2EDhh-Us-p2

This will collect additional information to help narrow down what data is being downloaded. 

Tagging @thebud15 @elibud @arunsathiya @p3ob7o as people who have reproduced the error on either Calypso or HUD and may be able to collect this information, as well.

**Comment by liviopv** [comment]
User from #2447379-zen provided this:

![Screenshot](https://cld.wthms.co/qXftnP+)
Screenshot: https://cld.wthms.co/qXftnP

**Comment by elibud** [comment]
@GeoJunkie will do if I get the message again, didn't happen gain after the day when I reported.

**Comment by Robertght** [comment]
Reported as well in #16441653-hc

**Comment by htdat** [comment]
2482997-zen

**Comment by gracie** [comment]
#16662618-HC too

**Comment by retnonindya** [comment]
#17064238-HC

**Comment by dromero20** [comment]
#2512544-zd

**Comment by kriskorn** [comment]
Also reported in 17068895-hc.

**Comment by sophiegyo** [comment]
Another report: 744991-hc

**Comment by rickmgithub** [comment]
> User from #2447379-zen provided this:
> 
> ![Screenshot](https://camo.githubusercontent.com/37dd66da1bc210de512b84c4d7cd3f3dde72a957/68747470733a2f2f636c642e7774686d732e636f2f715866746e502b)
> Screenshot: https://cld.wthms.co/qXftnP

User also provided additional screenshot - https://d.pr/i/t7DuUZ

**Comment by dromero20** [comment]
#2545646-zd

**Comment by donalirl** [comment]
#10539048-hc

**Comment by katiebethbrown** [comment]
17747626-hc
Safari 13.0 on Mac OS X 10.14.6

**Comment by nagpai** [comment]
#2622232-zen

**Comment by jerrysarcastic** [comment]
Also reported in #2626532-zen
- Mac OS 10.14.6
- Safari 13.0.4

**Comment by donalirl** [comment]
#2619534-zen

**Comment by amamujee** [comment]
Do we know how prevalent this issue is? Could we add some logging to figure out how frequently this is happening for real users before prioritizting?  cc @gwwar so it's on the manage focus radar.

**Comment by gwwar** [comment]
@amamujee this is already being investigated by @blowery see https://github.com/Automattic/wp-calypso/pull/38781 and p7H4VZ-2qV-p2

**Comment by jacoswan** [comment]
Another: #2657284-zen

1. Catalina 10.15.2
2. Safari 13.0.4
3. Just after I was typing a message to you in the chat-box.

**Comment by AtrumGeost** [comment]
Got another case here 14765053-hc but I wasn't able to get browser details from the user

**Comment by cecilearkay** [comment]
Another report in #2659608-zen

User is on Mac OS Catalina 10.15.2 with Safari 13.0.4. The pop up appears randomly when they write content in their posts, so many times per hour.

**Comment by blowery** [comment]
We're now reporting an MC stat (see https://github.com/Automattic/wp-calypso/pull/38976) when we see browser quota errors.

**Comment by blowery** [comment]
Found one more mitigation: if the user refreshes the page, the storage counter should reset... If they just click Allow, they'll get reprompted sooner than if they don't.

**Comment by chaitanyamsv** [comment]
18315914-hc

**Comment by gwwar** [comment]
Let's not close this until https://github.com/Automattic/wp-calypso/pull/39219 lands

**Comment by blowery** [comment]
The mitigation is currently live on staging. If you'd like to test, that's a great place to try.

**Comment by blowery** [comment]
And we're live! Reloading Calypso will pick up the fix.

**Comment by blowery** [comment]
Reopening because it appears the mitigation does not work in some cases.

**Comment by blowery** [comment]
[Tracking bug](https://bugs.webkit.org/show_bug.cgi?id=202137) over in webkit land

**Comment by blowery** [comment]
New mitigation is now live. Hope this one sticks.
