### ISSUE TITLE
Latest Posts Block: iframe code is stripped on front-end

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#36868]
When you have iframes in your posts and use the "Full Post" option under "Post Content Settings" when using the Latest Posts Block the iframe appears in the editor but is stripped on the front end.

#### Steps to reproduce
1. Starting at URL: Add a Latest Posts block to a page (AT site)
2. Make sure a post has an iframe in a HTML block
3. Choose the "Full Post" option under "Post Content Settings"
4. Publish the page, view the front-end

#### What I expected

The iframe should display on the front-end.

Editor:

![img](https://cld.wthms.co/NaXkpz+)

#### What happened instead

The iframe is stripped from the front-end, other HTML blocks are fine.

Front-end:

![img](https://cld.wthms.co/tCxWUU+)

#### Context / Source

Reported in:

16027974-hc 2428694-zen

Also tested on a separate AT site with multiple iframes and different WordPress.com themes.

**Comment by laurelfulford** [comment]
There's been a second report of this in 2568451-zen.

Originally tracked here: https://github.com/Automattic/newspack-blocks/issues/299
