### ISSUE TITLE
Editor: Typing on chrome iOS is slow

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#36870]
This is a repost of https://github.com/WordPress/gutenberg/issues/17729 that should have been fixed with https://github.com/WordPress/gutenberg/pull/17869

A user came back today and reported that this has not been fixed on their end. Adding Github per Slack conversation. 

Describe the bug
When typing on an empty paragraph, after the first character is typed the editor may take 3 seconds or more to show that character.
If during the 3 seconds delay the user continues to fast type many characters to the editor becomes very very slow and the characters typed may take 30 seconds or more to appear (or never appear at all).
If we type in paragraphs with content (at least one character) the problem does not happen.

On safari, it is possible to notice something similar, but it is not as slow as in chrome.

#### Steps to reproduce
Open Gutenberg on chrome for iOS type in a paragraph.
Press enter to create a new paragraph and type a character. Verify it takes more than 3 seconds for the character to appear.
Press enter to create another paragraph.
Fast type many characters verify it takes very long for the text to appear or it may not appear at all.

#### What I expected
Text to appear without issue.

#### What happened instead
The text loads very slowly.

#### Browser / OS version
Chrome for iOS

**Comment by gwwar** [comment]
For folks verifying, I believe we need a full native device. I'm not sure xcode or other emulators will trigger the issue.
