### ISSUE TITLE
SPT: Menu page template is cropped and has an extra scrollbar

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#36901]
#### Steps to reproduce
Starting at URL: https://wpcalypso.wordpress.com/block-editor/page/[site]

#### What I expected
For the Menu template to be displayed correctly

#### What happened instead
- Preview is cropped
- There are in an extra scrollbar next to the page heading

#### Browser / OS version
Google Chrome Version 77.0.3865.90
Mac OS Mojave 10.14.2

#### Screenshot / Video
![Screenshot 2019-10-18 15 06 15](https://user-images.githubusercontent.com/4924246/67131309-02d0e880-f1b9-11e9-8e6e-16f5c7c476b4.png)

**Comment by kwight** [comment]
Hm, wasn't able to repro myself on Horizon, staging, nor wpcalypso:

<img width="1530" alt="Screen Shot 2019-10-18 at 3 24 23 PM" src="https://user-images.githubusercontent.com/349751/67131920-7542c800-f1bb-11e9-9b24-b1f17e0aeecf.png">

**Comment by jancavan** [comment]
Thanks for looking into this @kwight. One thing I forgot to mention is my site **has not yet been launched yet**. Not sure if that's relevant, but the menu items don't seem to be cropped in a site that's already live. I do still see that scrollbar in the heading.

![Screenshot 2019-10-18 15 55 03](https://user-images.githubusercontent.com/4924246/67133049-f7cd8680-f1bf-11e9-818e-2216f2848da4.png)

On that screenshot you posted, I also noticed what seems to be a trace of the scrollbar, although scrollbar itself isn't completely there:

![Screenshot 2019-10-18 15 56 14](https://user-images.githubusercontent.com/4924246/67133085-1af83600-f1c0-11e9-8d40-17852c7f7b87.png)

**Comment by davipontesblog** [comment]
@iamtakashi is this still relevant to remain open?

**Comment by obenland** [comment]
Fixed in #39628 (crop) and #37616 (scroll bar).
