### ISSUE TITLE
Upgrade flow from Recurring Payments block leads to plans page with no context

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#36910]
#### Steps to reproduce the issue

1. Add a recurring payments block to a site on Jetpack Free
2. Click "Upgrade Your Plan"
3. You are taken to a plans page

#### What I expected
Obvious which plan(s) contain(s) the requested feature

#### What happened instead
Generic plans page

**Screenshots**

Widget with prompt:

<img width="544" alt="upgrade-plan-button" src="https://user-images.githubusercontent.com/51896/67124478-710caf80-f1a7-11e9-8f6f-319cb9c87b4b.png">

Plans page:

<img width="983" alt="plans-page-memberships" src="https://user-images.githubusercontent.com/51896/67124485-74a03680-f1a7-11e9-8db1-1d7830a100fb.png">

**Comment by artpi** [comment]
CC @fditrapani you discovered this as well

**Comment by fditrapani** [comment]
Yes I did. We have some inconsistent behaviour with how our upsells work. In some cases, we're sending people to the cart and others to the plans. After a quick analysis, I found that people going directly to the cart are converting at a higher right. While we are working on [updating the plans](https://github.com/Automattic/wp-calypso/pull/41567) I think it would be better for us to take people straight to the cart.

**Comment by davemart-in** [comment]
+1 on taking people straight to the cart. We do this for a hand full of cards already on the Earn page.

**Comment by sixhours** [comment]
Added D43796-code to address this

**Comment by sixhours** [comment]
Deployed in r207988-wpcom
