### ISSUE TITLE
Private Sites do not function in Edge

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#36926]
#### Steps to reproduce
1. Starting at URL: pick any private wpcom hosted site.
2. ensure you are logged into a wpcom account (if not logged in private site message displays as normal)
3. visit private site in Edge
4. Notice that the site does not load.

#### What I expected
I expect to have the site function as normal
#### What happened instead
instead it returns a white screen and appears to be loading in a loop.

#### Browser / OS version
User reported IE on windows 7 and Edge + IE on windows 10. 
Tested and reproduced on edge 18 with windows 10 pro. 

#### Screenshot / Video
console output for reference. 
![opera_OdaVBmitbI](https://user-images.githubusercontent.com/33329175/67244896-c0adde00-f428-11e9-8177-12bdf0288511.png)

![image](https://user-images.githubusercontent.com/33329175/67245157-55b0d700-f429-11e9-90eb-48bb7abe1e6a.png)

#### Context / Source
originally reported in multiple tickets tested and discussed with @GeoJunkie and @susanjanec 
#user-report

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by susanjanec** [comment]
Reported in 2428548-zen

**Comment by josephscott** [comment]
This should be fixed now.
