### ISSUE TITLE
CPT: Custom post type list rendering

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3693]
Related: #3691 

We need to list custom post types for a site, filtered by type, post status, and/or search. It's expected that this will be modeled closely after the Pages listing, though we should consider any additional design requirements (cc @hugobaeta ).

We should balance leveraging existing components from page listing with our desire to move post state fetching to newer Redux global state. This may require updating existing page listing components if overlap exists.

**Comment by hugobaeta** [comment]
> It's expected that this will be modeled closely after the Pages listing

Actually, custom post types can be modeled after either Pages or Posts (as far as I know, it's an option when you initially register the post type). I believe the ones on WordPress.com are Pages based ones (Portfolio, Menus, Testemonials).

**Comment by aduth** [comment]
>Actually, custom post types can be modeled after either Pages or Posts

Sorry, the original text was unclear. This was meant more in terms of how we should present listing of custom posts types in relation to existing Calypso [Posts](https://wordpress.com/posts) and [Pages](https://wordpress.com/posts) screens, or whether we should create a separate design. The pages listing screen in Calypso shows less detail than that of the posts screen, which is probably closer to what we want for new custom types screens.

**Comment by aduth** [comment]
This is now satisfied. A handful of related PRs:

- #3703
- #4022
- #4055
- #4276
- #6434
- #6572
- #6686
