### ISSUE TITLE
FSE: Site Description block in Core

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36948]
This work should be similar to the Site Title issue: https://github.com/Automattic/wp-calypso/issues/36947

However, in this case there is no open PR for Site Description block so it should be somewhat easier to coordinate. It should still largely be based and similar to the work that's going on for Site Title.

Since this is one of our first Core FSE issue that we'll be contributing to, it will also be important for informing and scoping our future work. Please note any obstacles that you might encounter along the way. :)

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
