### ISSUE TITLE
CoBlocks: Update to 1.16.1 [5]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36956]
CoBlocks has a new update: https://github.com/godaddy/coblocks/releases/tag/1.16.1

Let's test and upgrade if things look stable.

**Comment by kwight** [comment]
CoBlocks 1.16.1 is already on Horizon; the diff to activate it on production is D34290-code.

Our version on Horizon includes [an upstream patch](https://github.com/godaddy/coblocks/issues/1033) that should be in the next release.

**Comment by kwight** [comment]
Call for testing: p7DVsv-7xI-p2

**Comment by mmtr** [comment]
Production is now running CoBlocks 1.16.1

**Comment by mmtr** [comment]
I forgot we need to request an update for AT sites as well

**Comment by gwwar** [comment]
@mmtr we don't need to request a manual update for CoBlocks, only for Gutenberg updates.
