### ISSUE TITLE
CPT / Editor: Ensure editor uses post type labels when applicable

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3695]
Post types can define labels to be shown in the interface. In the current editor, many labels are hard-coded to either the post or page context. We should update these labels to pull from the post type API response when possible.

#### Return to list view

![image](https://cloud.githubusercontent.com/assets/1779930/13431024/a4ef4f88-df95-11e5-878a-2a961f6cf8c4.png)

From: `postType.labels.menu_name`

#### New post header label

![image](https://cloud.githubusercontent.com/assets/1779930/13431054/be401008-df95-11e5-9ab7-2ce6e826dd0b.png)

From: `postType.labels.new_item`

#### Status label loading text

![image](https://cloud.githubusercontent.com/assets/1779930/13431918/628fbb60-df99-11e5-87df-1f4082b8e5a4.png)

https://github.com/Automattic/wp-calypso/blob/6dde06c/client/post-editor/status-label.jsx#L62-L68

This should be updated to either `Loading…` or `Loading %(postType)s…`

From: `postType.labels.singular_name` (lowercase)

**Comment by mtias** [comment]
How about translation?

**Comment by aduth** [comment]
>How about translation?

Already accounted for in the WordPress.com REST API.

Example: https://public-api.wordpress.com/rest/v1.1/sites/example.wordpress.com/post-types?locale=fr

Some related discussion for WP-API at https://github.com/Automattic/wp-calypso/pull/3130#issuecomment-190380378 , which is relevant for this project given #3690.

**Comment by mtias** [comment]
@aduth I mean more about the UX flow for submitting and tweaking translations, we'll lose the community-translator benefits, which has been great so far.

**Comment by aduth** [comment]
>I mean more about the UX flow for submitting and tweaking translations, we'll lose the community-translator benefits, which has been great so far.

Many strings we (rightfully) have no control over, particularly labels of custom post types for plugins used on a Jetpack site. We could hard-code labels for custom post types known to be translated on WordPress.com, or decide upon new labels which are post-type agnostic.

**Comment by aduth** [comment]
Finished items:

- "New Post/Page" label (#3768)
- View Post action bar tooltip (#4263)
- Document title (#5447)
- Loading post label (#4157)
- Sidebar close button label (#4029)

Remaining items:

- [ ] [View Post in publish success notice](https://github.com/Automattic/wp-calypso/blob/cf28f5860102de9592ca284c8e296f00ea8f30b4/client/post-editor/post-editor.jsx#L94-L96)
 - Use `postType.labels.view_item`

Skipped items:

- [Trash confirmation prompt](https://github.com/Automattic/wp-calypso/blob/cf28f5860102de9592ca284c8e296f00ea8f30b4/client/post-editor/editor-delete-post/index.jsx#L53-L57)
- [Slug field explanation](https://github.com/Automattic/wp-calypso/blob/cf28f5860102de9592ca284c8e296f00ea8f30b4/client/post-editor/editor-more-options/slug.jsx#L24-L30)
- [Remaining messages in `<PostEditor />` aside from `view`](https://github.com/Automattic/wp-calypso/blob/cf28f5860102de9592ca284c8e296f00ea8f30b4/client/post-editor/post-editor.jsx#L58-L165)

Reasoning: You can see the labels we have available for a post type here at the following REST API response, which you'll note does not cover these cases:

https://public-api.wordpress.com/rest/v1.1/sites/example.wordpress.com/post-types
