### ISSUE TITLE
Gutenberg: Test 6.8 Plugin [10]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36955]
The Gutenberg 6.8 plugin is set to be released on October 30th! Let's help test in advance and see if this is stable for WordPress.com.

- [x] Add `6.8.0-alpha` files: D34332-code
- [x] Activate `6.8.0-alpha` on Horizon: D34338-code
- [x] call for testing: p7DVsv-7xI-p2
- [x] Add `6.8.0-rc1` files: D34616-code
- [x] Activate `6.8.0-rc1` on Horizon: D34617-code
- [x] Add `6.8.0` files: D34762-code
- [x] Activate `6.8.0` on Horizon: D34763-code
- [x] e2e tests PR: https://github.com/Automattic/wp-calypso/pull/36966
- [x] Activate `6.8.0` on prod: D34624-code
- [x] Request update for AT sites pMz3w-ayi-p2

**Comment by kwight** [comment]
Both unit and e2e tests are all green for 6.8.0-alpha ✅
