### ISSUE TITLE
CoBlocks: Investigate Stacked Gallery Block Behavior [2]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36961]
Please investigate and verify that the CoBlocks Stacked Gallery Block works as expected. We've gotten a report on `add caption` not working, and that creating said galleries only work from the media library versus other source.

We may also want to add E2E tests for CoBlocks to avoid manually testing on each update.

**Comment by goblinartificer** [comment]
Thanks for this! To clarify, captions are what's only editable from the Media library. 

Where the user recalls being able to use the *Add caption* field in the editor by clicking into it and typing there, now they have to select the image, edit it, then hit the Edit button in the Media overlay to edit the caption there (or do the same via visiting the Media library directly).

**Comment by katiebethbrown** [comment]
I created another issue for this before seeing this one. I'm not able to add/edit captions on CoBlocks Stacked or Masonry galleries on simple sites (works fine on AT and self-hosted).

https://github.com/Automattic/wp-calypso/issues/37090

**Comment by kwight** [comment]
Closing in favour of #37090, which has a complete description (I've also added a note about including an e2e test to any fix).
