### ISSUE TITLE
CPT / Editor: Reimplement Categories & Tags accordion as taxonomy-agnostic

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3697]
Custom post types may be associated with custom taxonomies. In the current editor, it is only possible to assign a `category` or `tag` taxonomy type to an edited post. With custom post types, we should seek to accommodate whichever taxonomies are associated with that particular post type.

Categories and tags are rendered uniquely, with categories shown as a tree view, and tags shown as a `<TokenField />` input. This distinction can be made on the basis of whether the taxonomy is hierarchical (see [`register_taxonomy`](https://codex.wordpress.org/Function_Reference/register_taxonomy)).
- `post-editor/editor-categories` should be renamed and updated to render hierarchical taxonomies
- `post-editor/editor-tags` should be renamed and updated to render non-hierarchical taxonomies

**Comment by aduth** [comment]
Related: #5297

**Comment by timmyc** [comment]
Pretty sure we are all done with this issue ✅

**Comment by aduth** [comment]
Good catch @timmyc . I think I overlooked because it was never assigned to the milestone.
