### ISSUE TITLE
Plans: Business and eCommerce show {{/strong}} tags in French

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#36996]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/ while logged into an account set to French
2. Switch to the "Sites commerciaux et boutiques en ligne" tab
3. Note the Business and eCommerce plans show `Espace de stockage de {{/strong}}200 Go{{strong}}` where the strong tags look to be inverted so are being rendered as text instead of making `200 Go` strong/bold.

#### What I expected
To not see the tags and 200 Go to be strong.

#### What happened instead
The tags are rendered as text. The same does not happen for other plans including Premium on the same tab.

The translations I checked seem to have the tags in the correct order:

https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bterm%5D=Espace+de+stockage+de+&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

The same issue does not occur in English or Spanish.

#### Browser / OS version
Chrome 77.0.3865.12

#### Screenshot / Video

https://cloudup.com/cxNhWgC_iHg

#### Context / Source

Thank you to Abdelhamid for flagging this issue.

**Comment by akirk** [comment]
Oh, I had fixed this 3 hrs ago but it took another re-deploy right now to take it online.

![Screenshot 2019-10-23 at 16 23 30](https://user-images.githubusercontent.com/203408/67402876-7c017e80-f5b1-11e9-8890-f8c332da9d9a.png)
