### ISSUE TITLE
Inconsistent scroll behaviour when sidebar and content are both scrollable

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#370]
If you have a scrollable sidebar *and* content areas (because the screen is short), then scrolling "past" the top of the sidebar then propagates the scroll to the content.

This behaviour doesn't work in the opposite direction - scrolling past the top of the content doesn't move the sidebar.

Not a big deal, necessarily, but I found this a bit unintuitive. I can imagine folks like my parents trying to scroll with their mouse on the wrong part of the screen and getting confused, and feeling like the sidebar is "broken".

<img width="805" alt="scroll-behaviour" src="https://cloud.githubusercontent.com/assets/51896/11315300/92ddf6be-8fa4-11e5-99a8-ba1d97f47209.png">

**Comment by lancewillett** [comment]
> This behaviour doesn't work in the opposite direction - scrolling past the top of the content doesn't move the sidebar.

This is incorrect, at least in Mac-n-Chrome in latest wpcalypso. Screencast:

![scrolling-example](https://cloud.githubusercontent.com/assets/66797/13714775/dce790a8-e78d-11e5-8806-9de67b9d885d.gif)

When you have your mouse on the sidebar, and scroll back up — the content scroll engages as expected.

This works well, in my opinion. Feel free to re-open if you feel it's still not ideal (or if I missed something else).
