### ISSUE TITLE
CPT / State: Implement terms state subtree

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3700]
Related: #3697. #3699

The current `lib/terms` stores are implemented with only categories and tags in mind. We'll need to implement an taxonomy-agnostic term store, which should likely be included in the global Redux state, not in the existing Flux-based module.

**Comment by timmyc** [comment]
@aduth with the new `taxonomies` landed ( nice work ) I was considering picking up this task but wanted to see if you had started in on it yet.

**Comment by aduth** [comment]
@timmyc All yours :smile: You may consider using #4217 as a reference of a start-to-finish Redux state implementation.

**Comment by aduth** [comment]
@timmyc Is there anything outstanding that's missing from the terms state, or should we close this issue?

Related PRs:

- #4912
- #5350
- #5500
- #6137

**Comment by timmyc** [comment]
I think we are good to close this out.  Just working on the UI for adding terms right now, and the `addTerm` action is working as expected.
