### ISSUE TITLE
Primary Site dropdown conflicting with Color Schemes

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#37024]
## Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Change the color scheme to Classic Blue
3. Have some sites set to Private
4. Check the "Primary Site" dropdown.

#### What I expected
To have the same navigation experience on the "Primary Site" dropdown with any color scheme I choose.

#### What happened instead
1. Can't see the Private label
2. Hovering other sites don't change the background color:

![PrimarySiteDropdown](https://user-images.githubusercontent.com/16104522/67484395-7140fb00-f63e-11e9-9338-3e587a983e72.png)

This also happens with the Powder Snow and Sunset schemes. 

The label is also overlapping with the search field:

![PrimarySiteDropdown2](https://user-images.githubusercontent.com/16104522/67484540-ae0cf200-f63e-11e9-9429-898644c350e3.png)

#### Browser / OS version
Chrome/78.0.3904.70
OS X 10.13.6

#### Context / Source
#dogfooding

**Comment by carinapilar** [comment]
It seems that this dropdown is used in multiple places, with the same issue, here's another example on the Contact page:

![ContactPage](https://user-images.githubusercontent.com/16104522/67519366-1b3f7800-f67d-11e9-8eea-37627cc518cf.png)

**Comment by Aurorum** [comment]
PR in #37095 for this issue :)

![ezgif-6-3a6e4e67dd0b](https://user-images.githubusercontent.com/43215253/67622441-0fd18580-f812-11e9-954c-ecef2540ac68.gif)
