### ISSUE TITLE
Auto-Loading Homepage: Theme homepage not loaded if no published pages present on site

### ISSUE THREAD

**Issue by tijosh** [Automattic/wp-calypso#37027]
#### Steps to reproduce
1. Empty a simple site via NA
2. Activate a template-first theme with auto-loading homepage

#### What I expected

Theme's homepage template is loaded and set as home page

#### What happened instead

* No home page is created
* Homepage template is not loaded
* Theme's homepage template is not available in template selector
* If a template-first theme was active when the site was emptied, that theme's homepage template is available in the template selector

#### Context / Source

#13169319-hc 

In this instance, the user's language was Turkish, so I discovered later that the homepage template would not have loaded anyway since it's not English.

**Comment by samiff** [comment]
To clarify, I'm able to recreate this simply by having no Published pages showing in Site > Pages and switching themes.

1. Remove any Published pages on the site.
2. Switch to one of the Recommended Themes that auto load a homepage.
3. The theme is switch, but the theme's homepage is not activated.

Users might clear out site pages when deciding on a new theme, and the prompt still comes up saying the theme's homepage will be activated, even though it's not.

**Comment by Addison-Stavlo** [comment]
I tested this out today with a new test site.  Everything seems to work well.  Even after deleting and getting rid of all published items, the theme switch still headstarts a new homepage on my end.  Maybe this was resolved with other recent fixes to some of these themes.

Closing the issue, but if this still persists feel free to reopen - but also it may help to include the specific theme that is failing in the process.
