### ISSUE TITLE
Global Styles: consider more fonts (pre and code)

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#37032]
In adding support for Global Styles in some themes, I've noticed that there are a few cases that can't be covered by base and headings fonts.

Specifically, varia-based themes https://github.com/Automattic/themes/pull/1516 use different fonts for code and preformatted text (search for `$font__code` and `$font_pre`).

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core Global Styles.
