### ISSUE TITLE
Global Styles: typography improvements v2

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#37033]
For v2, we may want to do a couple of things:

- Add typekit support (now we only support Google Fonts).
- Review and curate the font list to include fonts with non-latin characters.
- Bold/Italic buttons for heading/body text fonts. Also, the ability for a font pairing/preset to define this font style/weight. For example the "System Font & Libre Baskerville" combination should have headings with a font weight of 900.
- Consider more fonts https://github.com/Automattic/wp-calypso/issues/37032
- Justified/left aligned text.
- Override Global Styles at the inline level.

**Comment by kathrynwp** [comment]
Could we also consider displaying the font names in the dropdown menu using the fonts themselves? Currently, users have to select each font to see what it looks like, which is time consuming.

![Pages ‹ Site Title — WordPress com](https://user-images.githubusercontent.com/7662449/70161735-9176c780-168a-11ea-9e8d-4fb5e8a0ebd2.png)

Compare to font list in the Customizer, where it's quick to scan down the list of fonts and see what they look like:

![Customize_ KP Main Test site – An awesome tagline](https://user-images.githubusercontent.com/7662449/70161886-c8e57400-168a-11ea-9c06-d3aebf118b7e.png)

No user report, dogfooding. :)

**Comment by donalirl** [comment]
> No user report, dogfooding. :)

Got a user report for this in #6833071-hc :)

**Comment by davipontesblog** [comment]
@nosolosw with the focus on core Global Styles now, I am closing this issue. Please reopen if needed!
