### ISSUE TITLE
FSE: conditional block removal

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#37044]
We need to figure out if it's possibly to conditionally disable block removal with existing Block API, so we can implement the proposed Footer Credit block paywall.

If there are no extension points in Core for this, we should start communicating with Core folks on the best way to introduce it and start a PR for doing that.

<img src="https://user-images.githubusercontent.com/191598/67234111-81749280-f412-11e9-98a2-f59add679fc2.png" />

For context and related work you can check out this parent issue: https://github.com/Automattic/Dotcom-roadmap/issues/50.

**Comment by noahtallen** [comment]
This feature does not appear to exist yet: https://github.com/WordPress/gutenberg/issues/16364

**Comment by noahtallen** [comment]
I have a Gutenberg contribution here which adds this to Gutenberg https://github.com/WordPress/gutenberg/pull/18118

**Comment by noahtallen** [comment]
The required block message likely doesn't exist in Gutenberg either.

**Comment by noahtallen** [comment]
Removed myself since we aren't actively working on this at the moment.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
