### ISSUE TITLE
FSE: create Footer Credit block for self-hosted sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#37045]
At this stage we should disregard Dotcom and plan concerns and just try to make this block work in self-hosted context. Hopefully this will make it easier to seamlessly integrate it to Atomic sites later on.

@noahtallen to add more details on the feasibility of the approach or replace with other issues if needed.

Please consult the parent issue for designs. It should contain everything except the Dotcom specific upgrade nudges: https://github.com/Automattic/Dotcom-roadmap/issues/50#issuecomment-544657971.

**Comment by noahtallen** [comment]
Some semi-difficult aspects of this:
1. We need to specify the list of options in an extensible way.
2. We need to persist the selected option.
3. We may need to make this a reusable block. Reusable blocks don't really have a programmatic API -- they just exist as a way for end users to make a specific block the same on all pages/posts. So we may need to build that into Gutenberg. My suggestion would be to avoid this for the initial scope of the problem (e.g. we do not support template part variations for the footer, and I imagine this is not a short term goal)

**Comment by noahtallen** [comment]
I have solved the above aspects in #37045.

1. We'll do this with a PHP filter so we can reuse the existing options on WordPress.com
2. This now works and saves to the option used by the current footer credit.
3. We got around this by making it a dynamic block, so it renders from the option.
