### ISSUE TITLE
Jetpack Onboarding: Add in-page anchor links to focus on Guided Tour card steps

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#37050]
The current checklist Guided Tour experience for Jetpack users doesn't scroll down automatically to the next guided tour card. We should add some in-page anchor links to each guided tour card so that the user can be taken to each step.

This will be important to have in place for the two additional guided tour steps introduced in pa0RFL-oP. cc @jeffgolenski 

<img width="1199" alt="Screen Shot 2019-10-24 at 3 27 04 PM" src="https://user-images.githubusercontent.com/204742/67526863-e2020a80-f672-11e9-89fb-d187a3560dfa.png">

**Comment by seear** [comment]
Sending to @Automattic/jetpack-voyager to prioritise.

**Comment by rcanepa** [comment]
Guided tours support this functionality so I'll make sure to enable it. You can follow the progress in 1164141197617539-as-1199702075754309.

**Comment by rcanepa** [comment]
Last week, we merged #48630, which addressed this issue, so I believe we can now close this issue.

**Comment by inaikem** [comment]
Closing per @rcanepa's Jan 4th comment above
