### ISSUE TITLE
Customer Home: Clicking the support button displays a flash of the checklist

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#37077]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/home
2. Select a site that has the Customer Home.
3. Click the support button/bubble.

#### What I expected

I expect the support menu to open.

#### What happened instead

While the support menu opens, I see a flash of the checklist on screen before the customer home appears again.

#### Browser / OS version

Chrome 77.0.3865.120 / macOS 10.15
(Also seen in the WP.com desktop app 4.5.0-beta1)

#### Screenshot / Video

![CustomerHome-Help](https://user-images.githubusercontent.com/8658164/67587824-87d57800-f74c-11e9-97df-c1b11ec4984d.gif)

#### Context / Source
#manual-testing

**Comment by davipontesblog** [comment]
Moved to DotCom Manage for triaging.

**Comment by Aurorum** [comment]
I could definitely reproduce this a while ago, but I no longer can currently. 

![ezgif-3-60b2a17317fd](https://user-images.githubusercontent.com/43215253/77399621-b5792880-6da1-11ea-8fd9-813eff3f5724.gif)

@rachelmcr Are you still seeing this issue?

**Comment by rachelmcr** [comment]
Yep, I can still see the issue — at least on sites where I previously had access to the site checklist:

![checklist-supportbutton](https://user-images.githubusercontent.com/8658164/77411924-0f371e00-6db5-11ea-8eb3-abda4b88134a.gif)

**Comment by sixhours** [comment]
👋 @rachelmcr Are you still able to reproduce this? I added myself as an admin to the test site URL noted in the ticket description and I'm not seeing a flash in the latest version of Chrome, Firefox, or Safari.

**Comment by rachelmcr** [comment]
Thanks for the nudge! I confirmed I am no longer able to reproduce this — not on an existing site where I completed the site checklist before, or after signing up for a new account/site and completing the site checklist. Closing!
