### ISSUE TITLE
Tumblr and Instagram Embed blocks fail to embed

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#37070]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/
2. create a new page or open an existing one.
3. attempt to add an instagram or tumblr block
4. add link to block and click embed.

#### What I expected
For instagram feed and tumblr to embed

#### What happened instead
An error message appears 

> Sorry, this content could not be embedded.

#### Browser / OS version
bug appears to be browser/os agnostic. 

#### Screenshot / Video
<img width="606" alt="Screenshot_2019-10-25 09 03 48_3oYE88" src="https://user-images.githubusercontent.com/33329175/67573674-e841c680-f706-11e9-8f5e-d60d0652b080.png">

#### Context / Source
reported in #2438001-zen

**Comment by zdenys** [comment]
You cannot embed the entire site URL, but should only embed single Posts. This seems to apply to all embeds.

Tumblr example:

`https://photomatt.tumblr.com/post/188589146937/the-tremendous-leisure-industry-that-has-arisen-in`

![](https://cld.wthms.co/WFIL3L+)
_Link: https://cld.wthms.co/WFIL3L_

But for `https://photomatt.tumblr.com/`

![](https://cld.wthms.co/T5L0Nf+)
_Link: https://cld.wthms.co/T5L0Nf_

Instagram example: 

`https://www.instagram.com/p/B2kohC1gWTB/` 

![](https://cld.wthms.co/8tsSUh+)
_Link: https://cld.wthms.co/8tsSUh_

But for `https://www.instagram.com/photomatt/`

![](https://cld.wthms.co/cMxz1j+)
_Link: https://cld.wthms.co/cMxz1j_

[Learn more about embeds link](https://wordpress.org/support/article/embeds/) explains some limitations for embeds:

> Tumblr – only posts (name.tumblr.com/post/etc) are recognized, not standalone images (name.tumblr.com/image)

And [Facebook Embeds support page](https://en.support.wordpress.com/facebook-integration/facebook-embeds/#embedding-with-a-url) reads:

>Unlike the Facebook Page Plugin Widget, which displays a page feed in your sidebar, Facebook embeds allows you to display any individual update, photo, or video from a public Facebook timeline in a blog post or post comment
