### ISSUE TITLE
Blocks: Need to be able to hide or move the title on pages

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37088]
On a site I've been building I wanted to include the page title inside of a cover block so that each page could have a header with a background image. Like this:

<img width="1067" alt="Screen Shot 2019-10-25 at 2 42 12 PM" src="https://user-images.githubusercontent.com/1464705/67606324-e0e5e180-f735-11e9-8a14-26e96ec49e80.png">

In the editor this results in two titles, and then having to hide the actual title on each page with CSS. No regular user would do this, but I'm sure that they'd like to either remove the page title, or move it around to a different location.

There is some core Gutenberg work to turn the page title into a block. Let's use that work and enable it on WordPress.com. That way the user can delete the block if they don't want to keep it, or move it somewhere else if they prefer.

**Comment by ccwalburn** [comment]
Hi @apeatling! I was wondering if it would be possible to include a checkbox in the Editor Sidebar for pages and posts to hide the title while we wait for the core work you mentioned above? Hiding page and post titles is one of the most common CSS requests that we get and would be a great feature!

**Comment by ianstewart** [comment]
Closing this one as (while I don't have the issues at hand) this'll be tackled with the Block Editor (Post/Page/Site). Exciting times. :D
