### ISSUE TITLE
Blocks: Can't change font size on button block

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37087]
There is no way to adjust the font size of a button. This means adding a button to a cover block feels a little small when you want it to be a primary call to action on a page:

<img width="828" alt="Screen Shot 2019-10-25 at 2 37 59 PM" src="https://user-images.githubusercontent.com/1464705/67606053-15a56900-f735-11e9-871b-2cda398ae4e3.png">

There should be a font size adjuster in the sidebar for a button:

<img width="299" alt="Screen Shot 2019-10-25 at 2 39 27 PM" src="https://user-images.githubusercontent.com/1464705/67606144-45547100-f735-11e9-83ad-e76a88639918.png">

**Comment by WunderBart** [comment]
> Was going to mention this exist (albeit with some bugs, see [godaddy-wordpress/coblocks#1640](https://github.com/godaddy-wordpress/coblocks/issues/1640)), but it turns out the implementation I see is added via CoBlocks.

This functionality does exist when using CoBlocks on Atomic sites (via CoBlocks' contextual typography controls). It's not available on Simple sites, unfortunately, as we install a limited version of CoBlocks there. I'd suggest we move this one to Gutenberg repo for an upstream feature.

About CoBlocks future in WPCOM: pbAok1-1Jj-p2

**Comment by WunderBart** [comment]
Closing as per pbAok1-1Jj-p2.
