### ISSUE TITLE
Atomic: unable to delete tags and categories in Calypso via Manage > Settings > Writing

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#37092]
#### Steps to reproduce
1. On a WordPress.com AT or Jetpack connected site, create a new tag from Calypso in `Manage > Settings > Writing (tab) > Tags`.
2. Try to delete that tag using the toggle menu.

#### What I expected

* The tag would be deleted.

#### What happened instead

* The tag is not deleted.
* A console error is thrown: `Uncaught (in promise) InternalServerError: The body hash exists and does not match.`
* The API response returns an error:

```
{"body":{"code":"invalid_body_hash","message":"The body hash exists and does not match.","data":{"status_code":400,"redirect":false}},"status":500,"headers":{"Allow":"GET, POST, PUT, PATCH, DELETE"}}
```
* Deleting tags works fine from WP Admin for AT or JP connected sites.
* Deleting tags works fine on a simple site from Calypso.

**Edit**: This also appears to be the case for Categories in the same fashion as well.

#### Context / Source

#user-report
p9F6qB-4gl-p2

**Comment by iamgabrielma** [comment]
Another one in p9F6qB-4SK-p2

**Comment by hafizrahman** [comment]
Another one in p9F6qB-4WY-p2

**Comment by tanjoymor** [comment]
Another case of not being able to delete categories via Calypso: #2794242-zd

Was able to delete via WP Admin.

**Comment by lancewillett** [comment]
@brandonpayton Would you be willing to do a first pass at investigating this one?

**Comment by brandonpayton** [comment]
sure!

**Comment by guicmazeredo** [comment]
Another case one here: #19448672-hc

**Comment by rinazrina** [comment]
Got two users reported this issue today: 
#2899429-zen
#2899525-zen 

And I can reproduce this on [my test site](https://lyrics.water.blog)

**Comment by brandonpayton** [comment]
This appears to be a bug in the WordPress.com Jetpack client. The fix appears simple, but I'll need to confirm that with someone more familiar with Jetpack. Will post a link to the patch once it's available.

**Comment by brandonpayton** [comment]
I have a patch here, waiting for review:
D42975-code

**Comment by sandymcfadden** [comment]
Had another report here 20949353-hc

**Comment by brandonpayton** [comment]
This is now fixed via the patch above. In testing, I am able to delete both tags and categories on AT and Jetpack sites.
