### ISSUE TITLE
Editor: Dirty post hangs when changing from HTML to Visual

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3709]
Video: https://cloudup.com/cbSNta8VtpI

I only ever click the Visual tab once at the very start of the video. Yes, it takes that long for the switch to occur.

__Steps to reproduce:__

1. Navigate to the [Calypso post editor](https://calypso.localhost:3000/post)
2. Select a site, if prompted
3. Enter some text in the Visual editor
4. Quickly change to the HTML tab before autosave takes effect
5. Switch back to the Visual tab before autosave takes effect

__Expected result:__

There should be no delay in the change from the HTML to Visual tabs.

__Actual result:__

There is a very noticeable hang when switching to the HTML to Visual tab.

**Comment by codebykat** [comment]
Seeing this occasionally in my dogfooding. It can also happen on the switch from Visual to HTML.
