### ISSUE TITLE
CoBlocks Galleries: Not Able To Add or Edit Captions on Simple Sites

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#37090]
#### Steps to reproduce
1. Starting at URL: Block Editor on a Simple Site
2. Add a CoClocks Gallery (Masonry or Stacked)
3. Add images from the media library
4. Toggle on the `Captions` option

#### What I expected

To be able to add and edit captions

#### What happened instead

The "Write caption" text appears but isn't clickable or editable. Captions added directly to the images in the media library appear but are not editable.

#### Browser / OS version

Firefox

#### Screenshot / Video

Video showing what's happening:
https://href.li/?https://cld.wthms.co/bcIsSx

#### Context / Source

I can't edit the captions on a Simple site.

I tested and can edit the captions correctly on:
- my AT site (with CoBlocks 1.15.0)
- a Jurrasic Ninja site (CoBlocks 1.16.1)

**Comment by kwight** [comment]
Any fix for this should include an update to the CoBlocks e2e tests. While we have basic tests in place to ensure that each CoBlocks block can be added and will be rendered on the front-end, we have no tests specific to each block's behaviour (which could catch this sort of problem).

**Comment by edequalsawesome** [comment]
Issue also reported in #16310199-hc

**Comment by thebud15** [comment]
Reported in #16745325-hc

Seems like this should be an important fix, as it's a prominent feature of our CoBlocks-first Mayland theme.

**Comment by tanjoymor** [comment]
User came in asking if there was a Masonry alternative because of this bug.
#16747208-hc

**Comment by retnonindya** [comment]
Reported in #2514680-zen and I was able to replicate it on my test sites too

**Comment by lakellie** [comment]
Another report in #16952149-hc

**Comment by goblinartificer** [comment]
A new report in #17038738-hc from a user who's experienced it before. They say that the pencil icon on each image has now disappeared, making the previous temporary fix also unusable. Now there's no way for them to edit the caption from the Editor.

**Comment by kwight** [comment]
@gwwar I think we should consider pushing this into the next sprint.

**Comment by glendaviesnz** [comment]
Related to this bug https://github.com/godaddy-wordpress/coblocks/issues/1143 - captions can be edited in the block if they already exist.

**Comment by glendaviesnz** [comment]
This has been fixed in https://github.com/godaddy-wordpress/coblocks/pull/1180 - we are going to look at incorporating this into the 1.18 release that will go onto wpcom once we have finished testing.

**Comment by glendaviesnz** [comment]
The fix for this was included in the 1.18.0 release of CoBlocks to Simple Sites

**Comment by thabotswana** [comment]
A new report in #2645782-zen. User is not able to edit existing captions. The URLs can be changed but the text in the caption can not be altered

Screencast: https://d.pr/v/SWuDB6

**Comment by davipontesblog** [comment]
This should be fixed now with this PR: https://github.com/godaddy-wordpress/coblocks/pull/1527
Please reopen if needed.
