### ISSUE TITLE
Gutenframe: CoBlocks 1.16.1 breaks our format toolbar.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#37094]
_Note: this is present only on Horizon, where we are testing CoBlocks 1.16.1 – this is not in WP.com production._

Something in our 1.16.1 custom build of CoBlocks is combining with presumably `rich-text.js` of the WP.com Block Editor app to break the editor's formatting toolbar. Tools such as bold, italic, and the link handler are not present, and only the Uppercase subtool is displayed.

**Good :)**
<img width="789" alt="Screen Shot 2019-10-25 at 5 40 48 PM" src="https://user-images.githubusercontent.com/349751/67611486-c10ee780-f74e-11e9-9ca9-eefcf5d581f8.png">

**Bad :(**
<img width="792" alt="Screen Shot 2019-10-25 at 5 39 59 PM" src="https://user-images.githubusercontent.com/349751/67611490-cb30e600-f74e-11e9-8ce4-35aac8a885cd.png">

It is only the combination of our CoBlocks 1.16.1 and our own `common` tools that is broken (so just Horizon at the moment); the most recent, full versions of both CoBlocks and the Gutenberg plugin work perfectly fine on a standalone install. Out latest Gutenberg 6.8.0-alpha and our custom 1.15 CoBlocks build also work as expected.

**Comment by kwight** [comment]
@mmtr CoBlocks 1.16.1 definitely seems to be the common element for me; whether on `wordpress.com` or Horizon, with Gutenberg 6.7.0 or the new RC, CoBlocks 1.16.1 will have broken controls, and CoBlocks 1.15 will not.

**Comment by mmtr** [comment]
Oh, that makes sense, since I was not activating CoBlocks 1.16.1 in my sandbox. That should narrow down the root cause, will continue investigating. There have been recent changes to the uppercase format in CoBlocks like https://github.com/godaddy/coblocks/pull/986 that could be related.

**Comment by kwight** [comment]
Fix available in D34715-code.

**Comment by mmtr** [comment]
D34715-code has been deployed
