### ISSUE TITLE
Editor: Word Count Not Calculated For Some Languages

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#37126]
#### Steps to reproduce
1. Starting at URL: Switch your language to, for example, French Canadian: https://wordpress.com/me/account

<img width="387" alt="Screen Shot 2019-10-28 at 5 26 57 PM" src="https://user-images.githubusercontent.com/25575134/67719409-2873a400-f9a8-11e9-86a5-672f1061feb0.png">

You can also set the language in the Settings for a specific site: https://wordpress.com/settings/general/

2. Go to the post editor and check the Content Structure option

#### What I expected

- The word count to show the number of words

#### What happened instead

- The word count was stuck at 1
<img width="1552" alt="Screen Shot 2019-10-28 at 5 28 06 PM" src="https://user-images.githubusercontent.com/25575134/67719535-5fe25080-f9a8-11e9-8e08-61b58601e6a8.png">
- When I set the English language interface for my account (https://wordpress.com/me/account), the count shows correctly: 

<img width="789" alt="Screen Shot 2019-10-28 at 5 31 52 PM" src="https://user-images.githubusercontent.com/25575134/67719771-d8491180-f9a8-11e9-9a47-eeeaccd9eaa7.png">

#### Browser / OS version

I tested on Chrome: Version 77.0.3865.120 (Official Build) (64-bit)

#### Other details

So far, the issue was reported with these languages:
- Canadian French
- French
- Brazilian Portuguese
- 

#### Context / Source
#user-report
Reported by the user in 2441788-zen

**Comment by kathrynwp** [comment]
Also reported in 2526065-zen (French)
