### ISSUE TITLE
Media Library: Incorrect Plan Nudge Within Audio Tab

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#37155]
#### Steps to reproduce
1. From a Free Site create a new post or page
2. Insert an Audio block
3. Click on Media Library

This can also be seen by navigating to **My Site > Site > Media > Audio**.

#### What I expected
To see a notice encouraging you to upgrade to the Personal plan to enable audio file uploading.

#### What happened instead
The notice encourages you to upgrade to the Premium plan instead, even though audio file uploading is supported on the Personal plan.

#### Browser / OS version
Tested in Chrome 78 on Mojave

#### Screenshot / Video
<img width="1063" alt="Screen Shot 2019-10-29 at 3 06 21 PM" src="https://user-images.githubusercontent.com/42454301/67800856-6df2a880-fa5e-11e9-9cfb-3a23fe37e7f8.png">

#### Context / Source
#manual-testing

**Comment by Aurorum** [comment]
From #29437, might be relevant :

> As for what plan to suggest, I'm not sure I can comment on this -- perhaps WordPress.com Premium is the preferred plan for nudges from a Marketing perspective?

**Comment by mdrockwell** [comment]
Also worth noting, this plan upgrade nudge for uploading audio files within the Media Library is inconsistent with the upgrade nudge within My Site > Manage > Settings > Writing > Podcasting Set Up, which mentions the Personal plan.

**Comment by michelleweber** [comment]
@anneforbush, do you know if this nudge is as intended by marketing? (I assume so.)
