### ISSUE TITLE
Global Styles: improvements to publish flow

### ISSUE THREAD

**Issue by nosolosw** [Automattic/wp-calypso#37152]
Being able to update things other than the post from the editor is a newish thing and we need to keep an eye on how well customers get used to it. We've got some tracks data at p7DVsv-7zo-p2.

Some small and big things that may be worth iterating over: 

- **Integrate font selection within the post publish / draft flow**. Now that Gutenberg has better support for saving different entities it can be worth exploring.

- **Buttons and / or sidebar copy**. Some ideas include using a different word than "Publish" for the button, as to differentiate it from the post publish button.

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core Global Styles.
