### ISSUE TITLE
Hosting: Style redirect screen

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37166]
After clicking on Open PHPMyAdmin we're taken to a redirect page with an unstyled link.
<img width="898" alt="Screen Shot 2019-10-29 at 3 34 45 PM" src="https://user-images.githubusercontent.com/1270189/67814643-caa39280-fa61-11e9-97d6-69feddee0f21.png">

Let's add the following to the redirect page:

Option for a Short Redirect:
<img width="776" alt="screen-shot-2019-10-23-at-11 31 14-am" src="https://user-images.githubusercontent.com/1270189/67814707-02123f00-fa62-11e9-9901-288aaddcc28c.png">

A Longer Redirect:
<img width="776" alt="screen-shot-2019-10-23-at-11 32 45-am" src="https://user-images.githubusercontent.com/1270189/67814714-08a0b680-fa62-11e9-8310-332d71c6277f.png">

See D34245-code for prior redirect work.

**Comment by mmtr** [comment]
Fix available in D34754-code

**Comment by glendaviesnz** [comment]
Fixed by D34754-code
