### ISSUE TITLE
Payments: cannot properly select payment method

### ISSUE THREAD

**Issue by ellatrix** [Automattic/wp-calypso#37175]
Apologies if reported before or if this is the wrong place! I didn't see anything after a quick check.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checkout/xxx.wordpress.com
2. Try to select a payment method by clicking in the circles. It doesn't work.

![pay](https://user-images.githubusercontent.com/4710635/67847791-bd3ee480-fb03-11e9-90cb-b114961db636.gif)

**Comment by Aurorum** [comment]
PR in #37177 for this :)

![ezgif-6-f93629899d72](https://user-images.githubusercontent.com/43215253/67856829-532b3d00-fb0d-11e9-9ba5-de3bb92c9b7d.gif)

**Comment by fditrapani** [comment]
Thanks for the fix @Aurorum!
