### ISSUE TITLE
Gutenboarding: Audit `apiFetch` usage for wpcom APIs

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#37187]
`apiFetch` really targets a WordPress environment and WordPress API calls. We don't really have one here. It might make sense to use `fetch` directly.

https://github.com/Automattic/wp-calypso/blob/8bcfefe6d04682b23d1f200bd4ef2b4c83dadf1c/client/gutenboarding/store/resolvers.ts#L18-L19

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/37118_

**Comment by sirreal** [comment]
Related: https://github.com/WordPress/gutenberg/issues/13491

**Comment by simison** [comment]
D37093-code related?
