### ISSUE TITLE
Mailchimp connection: highlight connection area when landing on Calypso after clicking in the block to configure service

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#37208]
#### Steps to reproduce
1. Starting from a site that's connected to WordPress.com, but hasn't used the Mailchimp block yet.
2. Add the block to a new post. 
3. Click the button in the block to create a connection with Mailchimp.
4. When you land on `marketing/connections`, the Mailchimp option is at the bottom, not expanded, and may be hidden from view if the site owner has a small screen.

#### What I expected

Ideally, when you land on the page, the Mailchimp card would be extended and you should automatically scroll to that area so you don't have to look for it.

As suggested here:
p8oabR-qb-p2#comment-3478

![image](https://user-images.githubusercontent.com/426388/67937366-c3999300-fbcd-11e9-87d3-dd7763b9037b.png)

**Comment by Aurorum** [comment]
PR in #37216 for this issue :)
