### ISSUE TITLE
Jetpack Checklist: auto-enable feature when checking out via feature-specific flow

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#37206]
> When I clicked the upgrade button in the wp-admin At a Glance card for Jetpack Search, I went through checkout and landed on the Calypso checklist. The “Enhanced Search” checklist item was collapsed and I had expected it to be completed/activated since I had just purchased it.
> 
> Clicking “Try it” took me to Settings where I had to manually activate it.
> 
> Is this something we can automatically activate on purchase if users specifically click the upgrade CTAs from the Jetpack Search card(s)? This would need to be reflected in the Calypso checklist, Jetpack Dashboard > My Plan feature card, Calypso Performance settings, and wp-admin Performance settings, but it would feel a lot more seamless. I wouldn’t be left wondering, “Wait, did my purchase work? Did I get the better Search?”

-- p8oabR-qb-p2#comment-3476

**Comment by davipontesblog** [comment]
Moved to Jetpack Improved Onboarding for triaging.

**Comment by jeherve** [comment]
This is no longer relevant as the UI was updated. Closing.
