### ISSUE TITLE
CoBlocks: Captions cannot be filled when using Stacked Gallery block  

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#37205]
#### Steps to reproduce
1. Add a `Stacked Gallery` block to your content, select some images and click `insert`
2. Enable `captions` within the block settings
3. Click on any image of the gallery and you'll see the `caption` textfield enabled, but cannot be selected nor filled.

#### What I expected

That captions can be added.

#### What happened instead

Captions cannot be added.

#### Screenshot / Video

![gh-311019-coblocks-stacked-captions](https://user-images.githubusercontent.com/3812076/67934927-6d434900-fbfb-11e9-85b3-e2f89473d5d0.gif)

#### Context / Source

Originally reported in 2457277-zen

**Comment by gwwar** [comment]
cc @mmtr @kwight do you mind helping validate/triage

**Comment by kwight** [comment]
Thanks! Closing as duplicate of #37090 .
