### ISSUE TITLE
Page Templates: use system fonts in the preview area 

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#37219]
While playing around with page templates I noticed a strange font treatment on the preview area (the white box on the right side of the screen). Upon further inspection it was inheriting my theme typography styles. To me this felt like UI and should use system fonts (like the rest of the elements on the left):

Before:

<img width="1657" alt="Screen Shot 2019-10-31 at 9 21 20 AM" src="https://user-images.githubusercontent.com/437258/67950916-ee311f00-fbc0-11e9-9a6f-01ad42272023.png">

**Comment by shaunandrews** [comment]
To be clear, it’s only when the blank template is selected that we should use the system font in the preview on the right. Otherwise we should continue to inherit the theme’s font in the preview.
