### ISSUE TITLE
Plans:  Prevent Multiple Plans From being added to the same site. 

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#3722]
Currently it's possible to have both WordPress.com Premium and Business active on a site. Here's how. 
#### Steps to reproduce

1) Create a site and add two unique admin users
2) Admin 1 buys WordPress.com Premium (from /plans)
3) Admin 2 buys WordPress.com Business (from /plans)
4) Watch in awe and grief as the site now has both Premium and Business on it. 
#### What I expected

When trying to upgrade from Business either getting the $100 already paid off so being charged $199 or being told I couldn't do that. 
#### What happened instead

The site now has both Premium and Business active.

**Comment by retrofox** [comment]
we should consider what we should do if the user has a `PREMIUM` plan and tries to upgrade to `BUSINESS`.
  - implement the upgrade by $199.
  - do not allow this action.

cc @apeatling @rralian

**Comment by rralian** [comment]
I'd be interested in feedback from the original store team about this, to see if it's come up before and if they already have opinions/guidelines for dealing with this. My gut says we should let Admin 2 make the purchase for the Business plan, and give them a discount in the amount of the premium plan ($99) and so only charge them $200.

But then it gets a little complicated with cutoff dates. If the site is only one week away from renewing, do we charge $200 now to upgrade for that one week and then charge them $300 a week later to renew? Or do we reset the renewal date to one year from this purchase?

/cc @lucasartoni Do you have an opinion here, or if you're not the right person to ask, can you point us in the right direction?

**Comment by retrofox** [comment]
PRs:

* https://github.com/Automattic/wp-calypso/pull/6704

**Comment by lucasartoni** [comment]
@retrofox A Premium plan should always be able to be upgraded to Business.
@rralian the ideal upgrade process would be:
- if there are more than 90 days to the expiration of premium, the upgrade happens prorata considering the difference beween premium and business and then applying it to the remaining days until expiration, than there is a natural renew.
- if there are less than 90 days, the remaining days are given for free.

In both cases there is no change in the date of the subscription to avoid misalignements with the domain registrations or other unexpected complications.

**Comment by retrofox** [comment]
#### I created a new testing site - `FREE` plan
![image](https://cloud.githubusercontent.com/assets/77539/16780599/b6a87472-484d-11e6-9b55-720b5b903b8d.png)

#### I bought `PREMIUM` plan from first admin user
![image](https://cloud.githubusercontent.com/assets/77539/16780623/d11840e4-484d-11e6-8ca1-59f077aaed55.png)

#### I bought `BUSINESS` plan from second admin user (Spanish)
![image](https://cloud.githubusercontent.com/assets/77539/16780761/7a9d797c-484e-11e6-8466-29efea06a4c2.png)

#### The first user now sees the updated plan.
![image](https://cloud.githubusercontent.com/assets/77539/16780842/d43c8d92-484e-11e6-8622-ee7b8064ff3c.png)

So I don't see any issue here @BandonRandon. Am I making something wrong?

**Comment by BandonRandon** [comment]
@retrofox  I just re-tested this and was able to replicate it.  Here are a few notes:

- The site I'm testing on is an old account (January 2013) with a newly created site
- I am using a credit card to pay and not free credits
- Looks like we may be in different Plans views (maybe an A/B test?)
- The checkout process never shows a thank you page but the transactions are being complete and the card is being charged

For this test I used Brave browser (with Brave mode off) on Linux Mint 18. 

If you'd like to see this you can check out the report card for the users flagtest and bdukesapptest to see the two active plans on the newly created site  plantestblog.wordpress.com

**Comment by rodrigoi** [comment]
@BandonRandon would you mind retesting this issue? When introducing the Personal Plan, the backend flow for upgrades was buggy and allowed for multiple plans to be active on a site. A backend fix was deployed about a week ago that should fix this for new upgrades.

**Comment by BandonRandon** [comment]
Hi @rodrigoi Sorry for the delay here. 

I was just able to replicate this with Calypso Master on my site plantest.wordpress.com. This time I bought the Person Plan on the user bdukesapptest and then signed out and bought the Premium Plan on the user flagtest both users were charged the full amounts for the plans and the site is showing both plans. 

I've left both plans shown in the Store Admin pages so you can see what it looks like when a site has two plans, one for each user. 

----

I also wanted to test with new accounts/sites to see if this bug only happens with older accounts. To do this I created the users plantest2 and plantest3. I added plantest3 to the plantest2 site and was able to replicate this issue. You can review the Store Admin and see the site has two plans. 

Video of latest test here: https://cloudup.com/cI-U3rOAr0T
(ping bdukes in Slack for password)

CC:// @retrofox

**Comment by kriskarkoski** [comment]
If we support a second user upgrading from Premium to Business we need to consider what happens to the included domain. The domain should remain owned by the account that originally purchased it, but the upgraded plan would be on another account and I think there are issues with the domain and plan being split across accounts, but I would need to test that to be sure if that's still the case.

**Comment by BandonRandon** [comment]
The domain consideration that @kriskarkoski brought up is a good point.  After thinking about this a bit I personally would vote that we let the second user buy the upgrade but it's a "gift" to the original purchaser.

If/when we allow users to transfer upgrades between accounts they could then the plan could be moved between users. For now they could contact support and ask us to move it. 

Something like: 
> The Premium Plan upgrade you are about to buy for $[upgrade amount] will be active on your site **example.wordpress.com**. However as the plan was originally bought by **testuser** they will retain ownership. If you'd like to transfer the plan to your account, please have **testuser** contact support.
