### ISSUE TITLE
Gutenberg: Investigate improvements when Block Is Invalidated

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37230]
**Please take a few days to investigate what next steps make sense**. We can create new issues/refine the summary here to reflect what we find.

Suggested courses of action:
- Promote Attempt Block Recovery as primary CTA or auto-run the Attempt Block Recovery (handled by https://github.com/Automattic/wp-calypso/issues/38329 )
- Investigate if server transforms can fix issues earlier on
- See if core contributions are possible to make block validation both more relaxed and bulletproof (additive attributes/whitespace differences for example should be okay)

### Context

When a block parses HTML markup, it also tries to validate the data by re-serializing and comparing the result. Unfortunately blocks currently compare with an extremely strict mode. Even a small class addition for change for completely equivalent markup/styling, is enough to cause the following scary error:

<img width="685" alt="Screen Shot 2019-10-31 at 10 21 49 AM" src="https://user-images.githubusercontent.com/1270189/67970464-4881ae00-fbc8-11e9-956f-da38e919206c.png">

Clicking on the primary action usually isn't what the user wants. It converts the previously nice to understand block into a plain HTML block:

<img width="947" alt="Screen Shot 2019-10-31 at 10 21 56 AM" src="https://user-images.githubusercontent.com/1270189/67970538-60593200-fbc8-11e9-925b-2ba42308f35b.png">

The best action is usually "Attempt Block Recovery" or "Convert to Blocks"

<img width="823" alt="Screen Shot 2019-10-31 at 10 23 29 AM" src="https://user-images.githubusercontent.com/1270189/67970772-c5148c80-fbc8-11e9-95fd-b9cce1d70b2c.png">

Traditionally WP allows manipulation of content from a variety of filters/customizations, so this is a very easy case to fall into.

**Comment by gwwar** [comment]
Nice Matias also pointed out a related issue in https://github.com/WordPress/gutenberg/issues/7604

I think we can potentially add try PRs in parallel with our wpcom work and chat with the community on better CTAs, smarter validation and better overall user experience.

**Comment by mmtr** [comment]
> See if core contributions are possible to make block validation both more relaxed and bulletproof (additive attributes/whitespace differences for example should be okay)

After reading all comments in https://github.com/WordPress/gutenberg/issues/7604, I think the community could benefit from having 2 validation modes:
- Strict: the current one that marks a block as invalid if it is not an exact match.
- Moderate: allows extra attributes, as long as the ones provided by the `save` function are not altered (i.e. additional classes, `data-*` attributes, etc). It could still warns the differences in the browser console, and shows as tiny icon as a UI indicator that displays those differences when hovering it.

The strict mode will be the default one, allowing developers to switch to the moderate mode with a new Gutenberg setting in WP Admin.

For technical reference, the current strict mode is implemented in [the `isEquivalentHTML` function](https://github.com/WordPress/gutenberg/blob/cca3ddeaaa83fc434fa712b2f64dadce3eff8f1e/packages/blocks/src/api/validation/index.js#L536).

**Comment by gwwar** [comment]
Actually will close this one out since we have a few PRs up
