### ISSUE TITLE
Signup: Use more natural language in the domain name input prompt

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37235]
In a user testing session Erhan struggled to understand what to type in the domains box on the domains step. "I just don’t know what to put in there".

Please watch the first minute "Choosing and Selecting a Domain" testing video (after theme activation) on this post: p58i-8d4-p2

Our existing prompt in the input box is not a great help "Enter a name or keyword" -- these are vague and keyword is technical.

<img width="726" alt="Screen Shot 2019-10-31 at 11 58 03 AM" src="https://user-images.githubusercontent.com/1464705/67977631-b4b6de80-fbd5-11e9-99f8-3cfe16455d37.png">

We should provide a more friendly prompt, and also include some examples based on the vertical they have selected in signup. For example, Ehran selected the "Cameras & Photography" vertical. The prompt could be:

> Enter your preferred website address, or keywords like "photography", or "gallery"

ref: p58i-8d4-p2

**Comment by jancavan** [comment]
> Our existing prompt in the input box is not a great help "Enter a name or keyword" -- these are vague and keyword is technical.

> We should provide a more friendly prompt, and also include some examples based on the vertical they have selected in signup. For example, Ehran selected the "Cameras & Photography" vertical. The prompt could be:

> Enter your preferred website address, or keywords like "photography", or "gallery"

Not the exact suggestions in this issue, but a related change: https://github.com/Automattic/wp-calypso/pull/37554

**Comment by roo2** [comment]
A very similar change was discussed in [37567](https://github.com/Automattic/wp-calypso/pull/37567) and implemented as a test, I'll look into whether the test can be deployed for everyone yet.
