### ISSUE TITLE
Hosting: Handle users who don't have correct capabilities

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37231]
When visiting the SFTP and MySQL management section, what behavior do we prefer?

1. Redirecting folks without the right permissions to MySites root
~2. Showing the disabled cards, but also with an additional notice to contact the administrator for permission.~

cc @olaolusoga @shaunandrews  @apeatling 

Edit: Let's show the disabled cards with a top notice.

**Comment by kwight** [comment]
Two sounds much less confusing and aids discoverability. One is also the sort of thing that causes frustration with HEs and support sessions (magical/conditional disappearing UI).

**Comment by olaolusoga** [comment]
Agree with @kwight . 2 sounds like the right UX. If a person is intentionally trying to access the SFTP and MySQL management section, being redirected will get frustrating. It'd be best if the UI shared that permission is required for access.

**Comment by gwwar** [comment]
Thanks @olaolusoga, so maybe replace any top nudges (for automated transfer / plan upsell) with this notice instead?

**Comment by olaolusoga** [comment]
Have a screenshot of the notice you're referring to @gwwar ?

**Comment by gwwar** [comment]
The entire `Manage` section is not visible to folks with roles of Editor and below.
<img width="274" alt="Screen Shot 2019-11-06 at 2 37 41 PM" src="https://user-images.githubusercontent.com/1270189/68344139-2cd44700-00a3-11ea-926a-0cafe51287e9.png">

Since this is the case, I'm going to update the logic here to redirect instead of show a notice

**Comment by mmtr** [comment]
I agree that showing a disabled section with a notice is the ideal flow, but perhaps we can defer that to phase 2 or 3 now that we have the workaround that redirect users without permissions to `/stats/day`.

**Comment by gwwar** [comment]
Going to close this one out for now.
