### ISSUE TITLE
Full Site Editing: No Way to Change Page Title When Title is Hidden

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#37242]
#### Steps to reproduce
1. Ensure Hide Homepage Title is checked under Customize → Homepage Settings
2. Attempt to change the page title in the page editor

#### What I expected

To be able to change the page title. Even if the page title is not visible publicly, there is a need to change the title - for example, when the default page titles like Home do not suit.

#### What happened instead

There is no way to change the page title in Calypso.

#### Context / Source
#16322565-hc #user-report 

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by noahtallen** [comment]
We could possibly add this in the document sidebar 🤔

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.
