### ISSUE TITLE
Menu Custom Links: `https://` is set as placeholder, not as value in URL field

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#37246]
#### Steps to reproduce
1. Starting at URL (on a site without plugins installed): _WordPress.com > My Sites > Design > Customize > Menus > [Menu Name] > Add Items > Custom Links_ 

#### What I expected
Have `https://` prefilled into the URL field (hence set as a default value via `value="https://"` attribute of the `<input>` HTML tag)

This is how it appears on site with plugins installed:

![](https://cld.wthms.co/j11jbV+)
_Link: https://cld.wthms.co/j11jbV_

#### What happened instead
`https://` is only set as a placeholder (`placeholder="https://"`) of the `<input>` HTML tag, hence you need to type it manually.

![](https://cld.wthms.co/omOZwE+)
_Link: https://cld.wthms.co/omOZwE_

#### Context / Source
#dogfooding #concierge

**Comment by gwwar** [comment]
I'm seeing the same behavior on Atomic/Simple.

Probably worth checking to see why we need the menu customization, and file an upstream core patch for https vs http.

<img width="601" alt="Screen Shot 2020-03-24 at 12 17 46 PM" src="https://user-images.githubusercontent.com/1270189/77467635-968e8c80-6dc9-11ea-8db0-a7bab3b00bfe.png">

**Comment by davemart-in** [comment]
One concern I would have with adding "https://" in as text is that people might click into the field and quickly paste a URL, then unintentionally end up with `https://https://google.com` without knowing.

**Comment by obenland** [comment]
I share Dave's concern.

@zdenys Is this something you can still reproduce? I just tested with a WoA site and a standalone Jetpack site on Core trunk and both were using the placeholder.

**Comment by zdenys** [comment]
I can agree on @davemart-in's point too. I can confirm that on Simple Site and WoA sites I can now see `https://` as a placeholder only, not as a value. So there is consistency and parity between the two types of sites. Hence the issue can be closed. Thanks for checking!
