### ISSUE TITLE
Signup: update Plan page sub-heading

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#37251]
From user-testing, we've identified that users are unaware that they can change plans after picking one in Signup. We should add a sub-heading to the step to help explain this. Additionally, this could be an opportunity to mention our refund policy.

**Current Heading:** Pick a plan that's right for you.
**Suggested sub-heading:** You can add one now and update it later. Our 30-day refund makes changing risk-free.

If we do mention the 30day refund, we need to keep in mind that domain registrations are 96-hr.

<img width="1146" alt="Screen Shot 2019-11-01 at 11 19 11 AM" src="https://user-images.githubusercontent.com/942359/68035174-7e429780-fc99-11e9-97b3-86d39f53e682.png">

ref: p58i-8d4-p2

**Comment by michelleweber** [comment]
Given the domain issue, the "risk-free" feels too misleading, and I think the mention of the free option is really important and shouldn't be nixed here. This proposed copy also feels like a lot of text for this subhead. 

What do you think about something like "Choose a plan. Update it as you grow. Or start a free site!" or "Pick a plan now, move between them at any time. Or start a free site!"

**Comment by michaeldcain** [comment]
> Choose a plan. Update it as you grow. Or start a free site!

Love - as always. Thanks, @michelleweber!

**Comment by michaeldcain** [comment]
@michelleweber: I ended up dropping the "Or start a free site!" because of the "Not sure yet? Start with a free site." button just below the subheader.

<img width="1552" alt="Screen Shot 2019-11-07 at 1 43 14 PM" src="https://user-images.githubusercontent.com/942359/68417980-5e154b80-0165-11ea-9a74-efdce1404934.png">

**Comment by apeatling** [comment]
Looks great!
