### ISSUE TITLE
Hosting: Add visibility of last full site backup and Jetpack Connection Health [2]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37258]
Updating files using SFTP or modifying the DB may result in potential data loss. Before making changes, lets help the customer by displaying when the last full site backup occurred.

Here's a mock of how to introduce displaying the last good backup—a new card labeled `Site backup`

**Site backup card:**
<img width="291" alt="Screen Shot 2019-11-14 at 6 47 23 PM" src="https://user-images.githubusercontent.com/1382943/68905504-6cd4a300-070f-11ea-96e7-972dabfdcb7d.png">

Button links to the activity log, where if I'm reading "I can add enhancement issues for adding the explicit backup request" correctly, they should have a way to initiate a backup once the enhancement issue is worked on. If not, and we're doing it within the SFTP/MySQL page, the button should start the backup.

In page:
<img width="1467" alt="Screen Shot 2019-11-14 at 6 47 32 PM" src="https://user-images.githubusercontent.com/1382943/68905514-73631a80-070f-11ea-8a36-3e0cf180b45f.png">

cc @singerb for technical feasibility

cc @apeatling @shaunandrews  @olaolusoga

**Comment by seear** [comment]
List of current API endpoints is at Pa0RFL-ct-p2.

> lets help the customer by displaying when the last full site backup occurred

D34701-code, which should ship today, adds a `last_good_backup` (a unix timestamp) field to the state endpoint `GET /wpcom/v2/sites/<site_id>/rewind`.

> and if technically possible, add the ability to trigger a full site backup.

There is currently not a Calypso endpoint for triggering a backup, but there is no barrier to creating one. For the wpcom-side implementation, `vaultpress-api-client.php` has a `site_queue_backup()` method.

**Comment by gwwar** [comment]
> There is currently not a Calypso endpoint for triggering a backup, but there is no barrier to creating one.

Are there any concerns about additional load here, or would we be able to build one?

**Comment by seear** [comment]
> would we be able to build one?

It would be best if you could build this, with support and reviews from Chronos. The restore endpoint linked from Pa0RFL-ct-p2 should serve as a good example. (`POST /wpcom/v1.1/activity-log/<site_id>/rewind/to/<timestamp>`)

Also see the "Queue Backup" button in the Rewind Debugger in MC as an example.

**Comment by seear** [comment]
An alternative (MVP?) approach would be to link to the Activity Log, filtering on backup events, like:
https://wordpress.com/activity-log/{site}?group=rewind

There is no facility for queuing a backup there.

**Comment by gwwar** [comment]
Let's scope to displaying the last good backup / Jetpack Connection health. I can add enhancement issues for adding the explicit backup request, and a warning to this section without a recent backup or good Jetpack Connection

**Comment by olaolusoga** [comment]
Here's a mock of how to introduce displaying the last good backup—a new card labeled `Site backup`

**Site backup card:**
<img width="804" alt="Screen Shot 2019-11-13 at 5 12 45 PM" src="https://user-images.githubusercontent.com/1382943/68808970-dfbf1a80-0638-11ea-9ce0-3d3cedc32128.png">

Buton links to the activity log, where if I'm reading "I can add enhancement issues for adding the explicit backup request" correctly, they should have a way to initiate a backup once the enhancement issue is worked on. If not, and we're doing it within the SFTP/MySQL page, the button should start the backup.

In page:
<img width="1327" alt="Screen Shot 2019-11-13 at 5 28 34 PM" src="https://user-images.githubusercontent.com/1382943/68809966-1302a900-063b-11ea-98f5-743100a397a7.png">

**Comment by gwwar** [comment]
Note that the button for "Backup your site now" is out of scope for this issue.

**Comment by seear** [comment]
> D34701-code, which should ship today, adds a last_good_backup (a unix timestamp) field to the state endpoint GET /wpcom/v2/sites/<site_id>/rewind.

Update on this. We added a new endpoint instead that lists the last 10 backups along with status:
 
`GET /wpcom/v2/sites/<site_id>/rewind/backups`
Source/docs: https://wpcom.trac.automattic.com/browser/trunk/wp-content/rest-api-plugins/endpoints/sites-rewind-backup.php

**Comment by automattic-ian** [comment]
as discussed in Slack, I think we should be changing the copy around rewind on the hosting page, in order to proactively manage user expectations of Rewind. 

Presently we do explain that rewind can lead to lost content, for example if a post is published and a user rewinds to *before* the post was published, the post is lost. 
![image](https://user-images.githubusercontent.com/33329175/69170237-be8e7c00-0ac7-11ea-8fd7-ca6f38c3eaa3.png)

This is great, except the user only sees it *after* they've encountered a situation where they need to rewind. 

If we added similar copy on the Hosting page this would hopefully ensure that since SFTP and DB are what I would define as risky actions, that users think twice before diving straight in. 

It would also help ensure Happiness has the option to address pushback if a user claims "no one warned me things would be missing if I broke my site"

**Comment by obi2020** [comment]
A few suggestion for this card:

- Change the hierarchy a bit so the warning doesn't get lost. 
- We don't need the header and the subheader here, so just lead with the impactful info
- I have a little lightbulb here, but I'm sure that's not kosher for the design system. Is there some other icon we can use that implies ATTN or NOTE! or HEADS UP! @olaolusoga 

<img width="432" alt="last backup" src="https://user-images.githubusercontent.com/3373750/69277934-35527480-0baf-11ea-8cd9-f0a8929cc466.png">

**Comment by mmtr** [comment]
@jeraldjuice not sure the status of this, but you might need some of the layout changes added in #37777
