### ISSUE TITLE
Syntax Highlighter Block: '&' Ampersand sign in C/C++ is converted to its HTML entitty `&amp;`

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#37264]
**Steps to reproduce**

1. Add a Syntax Highlighter Block
2. Select C/C++ as the Code Language
3. Add code with the ampersand sign &.

View the results

What I expected-
<img width="491" alt="Screenshot at Nov 02 14-36-35" src="https://user-images.githubusercontent.com/40609190/68068788-19616d00-fd7f-11e9-9fb4-68294585ad73.png">

When I preview the page, what do I see-
<img width="761" alt="Screenshot at Nov 02 14-37-08" src="https://user-images.githubusercontent.com/40609190/68068804-457cee00-fd7f-11e9-931c-1cf1120c27cb.png">

Browser / OS version
Any

PS- The same issue is for the 'Greater Than' sign, which gets converted to `&gt;`
Reported here- https://github.com/Automattic/wp-calypso/issues/34931

The issue was originally reported by a user here- 2463182-zen

**Comment by gwwar** [comment]
Related is https://github.com/Automattic/wp-calypso/issues/37264, probably from the same filter

**Comment by gwwar** [comment]
Potentially related https://github.com/WordPress/gutenberg/pull/17994

**Comment by mkaz** [comment]
Fixed on WordPress.com applying this fix.
https://github.com/Automattic/syntaxhighlighter/pull/3
