### ISSUE TITLE
Signup: Make smarter recommendations for TLDs based on vertical

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37266]
Please watch the "Choosing and Selecting a Domain" testing video on this post: p58i-8d4-p2

* He’s selected previously that he wants a photography portfolio, and the first recommendation of a domain name uses “.dog”. 😳

-------

We know the vertical that the user has selected, I think we can provide better and more relevant recommendations of TLDs for the user on this step.

**Comment by kelliepeterson** [comment]
This is on our radar. We actually always wanted to do this, but the vertical clues were not strong enough (or were changing a lot) until this past year and we were busy with migration stuff. Our third-party provider of search suggestions actually built a solution per our request to do just this kind of thing. 

I know this result was particularly egregious, but domain suggestion engines are always challenged by personal names, especially non-anglo names. 

Added to our repository in Asana. We'll review how much work this is and see when we'll be able to make it so now that we're post back end migration and there's been stability in the verticals part of onboarding.

**Comment by klimeryk** [comment]
Just to close the loop - in https://github.com/Automattic/wp-calypso/pull/38472, we've introduced an A/B test to check how using verticals to influence domain suggestions affects our metrics.
