### ISSUE TITLE
Signup: Inform the user that their selected domain will not be used until they complete payment

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37268]
Please watch the "Choosing and Selecting a Domain" testing video on this post: p58i-8d4-p2

* He picks [paid domain], but every email he receives from that point on said [subdomain], and this was confusing for him. “This was very confusing to me, I thought I’d picked [paid domain]”. 

This is because he didn’t previously complete the domain registration and payment, there’s a good opportunity to better explain this and prompt for completion.

ref: p58i-8d4-p2

**Comment by olaolusoga** [comment]
cc: @obi2020

**Comment by klimeryk** [comment]
Marking this as wontfix - I'm not sure what would be an actionable fix here. The user did not finish checkout, they don't own the custom domain, not sure why they'd expect it being mentioned as if they own it?
We do have already a notice with a reminder to finish checkout, though:

<img width="515" alt="Screenshot 2021-02-09 at 22 55 19" src="https://user-images.githubusercontent.com/3392497/107439409-e7b28680-6b29-11eb-8e10-adf204306f45.png">
