### ISSUE TITLE
FSE: A changed site option in a block resets when block is dragged into another group block

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#37260]
From @Addison-Stavlo:

I am finding that the selected option gets reset when drag-and-drop is used into or out of a parent block.  That is (as outlined in the gif below), if we select the logo option and then move the block to a different parent the option resets to the default text credit.

![drag-drop-reset](https://user-images.githubusercontent.com/28742426/68039753-2ad54700-fca3-11e9-8952-cca3091c813f.gif)

#### Steps to reproduce
1. Edit the header
2. Make a change to the site title
3. Drag the site title block into a group block
4. Observe the site title reset

#### What I expected
The site title to be persisted.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
