### ISSUE TITLE
Customer Home: Delay the GSuite upgrade banner from showing

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37273]
Please watch the "Figuring out GSuite" testing video on this post: p58i-8d4-p2

> He’s immediately prompted to upgrade to GSuite, or add another domain name, even though he has just been through both experiences in signup. “It’s already telling me to add more stuff!”

ref: p58i-8d4-p2

**Comment by stephanethomas** [comment]
I don't have any problem with postponing the display of this banner by a week.

/cc @Automattic/larimar

**Comment by apeatling** [comment]
@lcollette The experience issues that you're assigned to, are they active at all? If not I think we're almost at the point where other teams can pick these up.

**Comment by jancavan** [comment]
I ran into this issue too and documented it here: https://github.com/Automattic/wp-calypso/issues/37927 (will close this, didn't realize it's a duplicate.)

**Comment by apeatling** [comment]
This does really affect the ability to use the checklist on a more typical screen resolution:

<img width="1196" alt="Screen Shot 2019-12-02 at 1 30 34 PM" src="https://user-images.githubusercontent.com/1464705/69997006-0f5e9580-1508-11ea-8308-8aded1195c29.png">

**Comment by ianstewart** [comment]
Duplicate issue with some other examples https://github.com/Automattic/wp-calypso/issues/38122

**Comment by apeatling** [comment]
Lets start with a 2-day delay on all banners like this that appear on Customer Home. This will prevent you from completing a step and then seeing a different banner on a new page load.
