### ISSUE TITLE
Checklist: Include a checklist item for viewing your website

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37275]
Please watch the "Interacting with the Checklist and Domain Verification" testing video on this post: p58i-8d4-p2

> He wants to view his site first to see if its “up and ready” but ends up being drawn to the verify domain name notice in the sidebar. At this point he enters the verification flow, even though this wasn’t his original intention. “I’m assuming if I hit fix it’s going to open up a tab and go to the site” (it doesn’t).

ref: p58i-8d4-p2

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.

**Comment by sixhours** [comment]
This can be closed, we've added a "View Site" button prominently in the header area of Customer Home.

<img width="1100" alt="Screen Shot 2020-03-11 at 8 50 04 AM" src="https://user-images.githubusercontent.com/2124984/76418610-4fd67680-6375-11ea-9e3f-c45d49e97fde.png">
