### ISSUE TITLE
Domain Verification: Improve the wording of domain unreliability notice

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37276]
Please watch the "Interacting with the Checklist and Domain Verification" testing video on this post: p58i-8d4-p2

* The “domain may be unreliable in the first 72 hours” notice is too long and he only reads the first part of it.

----

I think we can do a better job of being clear on this notice, so it doesn't feel like a really long warning to read. The user clearly just skips over this and doesn't absorb what it means. A single bolded clear sentence that "It may take up to 72 hours for your domain to become active" and what that actually means for using the product would be more beneficial.

**Comment by klimeryk** [comment]
This has been changed to say `...30 minutes` in https://github.com/Automattic/wp-calypso/pull/39313. Marking as closed/resolved.
