### ISSUE TITLE
Gallery Block: Add a clearer option to edit existing images than Media Library button

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37289]
Please watch the "Editing a Page Template: Gallery Block" testing video on this post: p58i-8d4-p2

[stub, full description will be added today]

**Comment by vindl** [comment]
We still need a full description and design for this.

**Comment by davipontesblog** [comment]
I am closing this in favor of https://github.com/WordPress/gutenberg/issues/18529 in core. Feel free to reopen it if you feel needed, or continue contributing to the related core issue.
