### ISSUE TITLE
Themes: For template-first themes change the customizer button to a block editor button

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37286]
Users with a template-first theme should not be prompted to go into the customizer when activating that theme. See the "Changing Designs" testing video (after theme activation) on this post: p58i-8d4-p2

* When activating a theme he expected to be “put back into the page where I was struggling with the design”. He expects to go right back into the block editor with his new homepage and design. Instead he selects Customize site and is put into the Customizer. “Oh it’s different? It is letting me customize it, but the whole format of this page is different.”

**Comment by mattwiebe** [comment]
I started exploring the plumbing bits of this. 

Firstly, there are no great ways of handling any of this on Atomic. I don't think this is a huge problem, as users there will likely be installing a theme from Themeforest or some equivalent. What we're doing here is leveraging control where we have it, on Simple sites, to improve the UX of especially our new users.

Our theme endpoints and listings are all powered by a `theme` custom post type on `theme.wordpress.com` and various support bits that power the filtering interface in Calypso are all represented as various taxonomies. I believe that what we'll want to do is to tag the themes we want with a "Full Site Editing" `theme_feature` taxonomy.

The `/themes` screen already supports filtering on these things. The quick-n-dirty way to do this would be to prepopulate the search bar with `feature:full-site-editing` for sites with FSE enabled.

**Comment by noahtallen** [comment]
Some theme features have been added to the current template first themes, including:

- `global-styles`
- `block-editor-styles`
- `auto-loading-homepage`

Block Editor Styles contains more than just the template-first themes, but both Global Styles and Auto Loading Homepage are on the template first themes published on wpcom.

Maywood also already has 'full-site-editing' as theme support (and hence a tag). This format looks exactly the same as how the above features are declared at the theme level. Somewhere along the way, wpcom code does stuff to translate those tags/theme-supports into features. As Matt says, they're represented as taxonomies, but I'm having trouble finding exactly where this happens.

**Comment by noahtallen** [comment]
I couldn't quite grok where the code would live for getting "Full Site Editing" to show up. Oh well. @apeatling we could likely use one of the above tags to change the button behavior here. Thoughts?

**Comment by apeatling** [comment]
This is the current popup:

<img width="363" alt="Screen Shot 2019-11-05 at 7 27 02 PM" src="https://user-images.githubusercontent.com/1464705/68266102-ddd6d500-0002-11ea-9d51-f52f9235f049.png">

The "Learn about this theme" does not seem useful to me, you literally just learned about the theme before activating. For older themes it might be more useful because you need to read the 50 steps to get your homepage set up like the demo.

I think for template first themes we should change the buttons to:

[View Site] [Edit Site]

The edit site would open the homepage in the block editor.

/cc @olaolusoga interested in your thoughts on this one.

**Comment by noahtallen** [comment]
I think "Learn about this theme" is there so the customer has an active button to click while the theme is loading. I also agree it seems useless. (we also don't want to send the user into a rabbit hole of reading all about the theme. seeing it on their site is more effective).

I created this, following your suggestions:

### Gif:
![2019-11-06 11 52 43](https://user-images.githubusercontent.com/6265975/68332847-46b65f80-008c-11ea-8562-da481cbc0db5.gif)

### Activating theme state:

<img width="388" alt="Screen Shot 2019-11-06 at 11 56 11 AM" src="https://user-images.githubusercontent.com/6265975/68332950-7d8c7580-008c-11ea-986e-ba1776a52990.png">

### Theme activated state:

<img width="462" alt="Screen Shot 2019-11-06 at 11 56 15 AM" src="https://user-images.githubusercontent.com/6265975/68332961-854c1a00-008c-11ea-889d-a8486b3c2e34.png">

Could use feedback on the UI bits of this. (Still working on the plumbing.)

**Comment by olaolusoga** [comment]
>The "Learn about this theme" does not seem useful to me, you literally just learned about the theme before activating.

Agree. It has no value—even for old themes, having that button bounces folks out of the flow and into a rabbit hole. We should remove & replace with your suggestion of [View Site] [Edit Site].

Can a person select a template first theme from the theme section? How many template first themes d we have?

>How should we change the copy of the button? Should it say "Edit Site" or "Edit Homepage" or something different?

Depends on where we're dropping them after the click. If we're dropping them in the SPT (starter page template view) then we should say site, if we're dropping them in the homepage template, then homepage. As we saw with Rachel's test today, the more context and wayfinder guidance we can provide, the better.

Took a quick look at how Wix and webflow handle it, and like how site isn't mentioned.

Screenshot:
WIX
<img width="415" alt="Screen Shot 2019-11-06 at 3 10 44 PM" src="https://user-images.githubusercontent.com/1382943/68333993-acfcab80-00a7-11ea-8c57-c8c4c1395e2a.png">

Webflow
<img width="305" alt="Screen Shot 2019-11-06 at 3 14 14 PM" src="https://user-images.githubusercontent.com/1382943/68334750-437d9c80-00a9-11ea-831f-98b57f1709d1.png">

We should remove "site" from [View site] [Edit site]. Thoughts? 

Also for buttons, almost want to test tacking buttons (similar to WIX) with [Edit] first, then [View] second. Thoughts? 

cc: @shaunandrews any history on button placement we need to worry about on this themes modal ?

**Comment by noahtallen** [comment]
> Can a person select a template first theme from the theme section? How many template first themes d we have?

Yes, about 18ish of the themes which can be selected are template first themes. I think they are all at the top of the list by default.

And then, we’d be dropping them into the default homepage template (not template selector).

My thought with removing “site” is that we don’t currently define site == theme. So if we just have edit there, it may look like they are about to edit the theme (which doesn’t really mean anything on our end but maybe it does to the user).

**Comment by apeatling** [comment]
Your Gif looks spot on to me, that is already a big improvement. I agree with Ola that "Edit Homepage" is better and provides more context.

**Comment by apeatling** [comment]
I think we should keep "Site" for now, I don't think [View] and [Edit] creates enough context in this particular situation.

[View Site] [Edit Homepage] is probably as specific as it can get, is that better?

**Comment by noahtallen** [comment]
BTW @apeatling I'll have a PR up soon for this. Just have to figure out how to limit this to SPT themes

**Comment by olaolusoga** [comment]
All sounds good. And GIF also looks good to me. Observation: Surprised we don't "Activate" on hover.

**Comment by noahtallen** [comment]
Note that the gif has changed a bit and now looks more like it did previously. Feel free to test the exact change here: #37378

> Surprised we don't have an "Activate" option on hover

That's a great point. That should be an easy change if you want to change "info" to "activate", and not much more to just show another item on hover. Let me know if you want me to make that change :)

**Comment by apeatling** [comment]
Making a note here to follow up, that we also need to remove try and customize for these new themes since that takes them directly to the customizer.

**Comment by noahtallen** [comment]
@apeatling I remember #36044 as prior art :)

In fact, with the new selector I added for determining themes which should be edited in Gutenberg, it's essentially a one line change: https://github.com/Automattic/wp-calypso/pull/37378/commits/c88dd288354992cae8b5884d11a04ff8182c4810

I pushed it to the existing PR because of the selector. Note that if we merge, we will need to give a happiness heads up post as promised :)

**Comment by olaolusoga** [comment]
>That should be an easy change if you want to change "info" to "activate", and not much more to just show another item on hover.

That'd be a great addition for folks who would like to skip a click. 

Here's a mock for how it should look.

**Current hover state**
<img width="276" alt="Screen Shot 2019-11-07 at 8 12 41 PM" src="https://user-images.githubusercontent.com/1382943/68441087-01348800-019b-11ea-897f-8e3ca684c1e3.png">

**Updates hover state with "activate theme", and "info" expanded to "more information"**
<img width="275" alt="Screen Shot 2019-11-07 at 8 09 22 PM" src="https://user-images.githubusercontent.com/1382943/68441115-1f9a8380-019b-11ea-8c9f-8ad9e302dc2d.png">


**In context**
<img width="1396" alt="Screen Shot 2019-11-07 at 8 09 13 PM" src="https://user-images.githubusercontent.com/1382943/68441127-26c19180-019b-11ea-8fd2-635f7724378b.png">


If the copy in buttons are too long when i18n is considered, it can be [Activate] [More info]

**Comment by noahtallen** [comment]
@olaolusoga One thing I just realized about the interaction is that the entire section highlighted in blue here is the button:

<img width="363" alt="Screen Shot 2019-11-09 at 2 16 19 PM" src="https://user-images.githubusercontent.com/6265975/68535706-8cc52a80-02fb-11ea-9470-14fbcb541885.png">

When you hover over that theme thumbnail, you can actually click anywhere on it to open the info screen. The "button" isn't actually button, it just informs us what clicking on the card will do.

That's definitely a weird interaction, and I'm not sure if that changes anything about how the design should work.

**Comment by noahtallen** [comment]
digging into the implementation a bit, it isn't all that straightforward to add a new button here. :( Definitely possible, but is enough effort to be split out into another issue at this point

**Comment by apeatling** [comment]
I think those changes should be another iteration and not block what’s already been done.

**Comment by olaolusoga** [comment]
> I think those changes should be another iteration and not block what’s already been done.

Agree. Thanks for highlighting Noah. The improvements made in this issue are good enough. 

The new changes can be punted to a new issue, and would say is a nice to have vs urgent need.

**Comment by noahtallen** [comment]
Created #37476. Not what projects it should go into.

**Comment by shaunandrews** [comment]
Why are we opening the editor in a new tab? Could we just open it in the existing tab?

**Comment by noahtallen** [comment]
@shaunandrews with the latest changes it opens in the same tab :) (the gif is slightly out of date)

**Comment by shaunandrews** [comment]
Ah, ok. Thats what I get for trying to review PR's by images alone :)
