### ISSUE TITLE
Editor: Scrollbar showing for page template titles in preview

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37287]
Please watch the "Adding a New Page" testing video (after theme activation) on this post: p58i-8d4-p2

The user sees a scrollbar when selecting the portfolio template. They were using a theme that does not have editor styles:

  
<img width="569" alt="Screen Shot 2019-11-04 at 11 42 38 AM" src="https://user-images.githubusercontent.com/1464705/68152338-4e44ff80-fef8-11e9-9e39-e68efe6084b3.png">

**Comment by obenland** [comment]
@marekhrabe @WunderBart This would be a good one to take a look at, too

**Comment by vindl** [comment]
Also reported in p7DVsv-7zo-p2 (#comment-24511).

**Comment by apeatling** [comment]
@obenland I'm assigning you right now, just so I can see this as taken by Ajax in the milestone view.

**Comment by vindl** [comment]
@Automattic/cylon will be taking this one over if there are no objections. :)
