### ISSUE TITLE
Paragraph Block: Support color pairings in paragraph block (see this issue for nav block support)

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37292]
Please watch the "Editing a Page Template: Paragraph Block" testing video on this post: p58i-8d4-p2

It took him some time to discover that font and color options were in the sidebar, he looked through everything in the block options menu first. He then looked at the sidebar but clicked off the paragraph block first, meaning he did not initially see paragraph block settings. Once reselected he found the options.

-----

I think color settings should be in the block toolbar, they are formatting controls like bold or italic. I like how this works with the new navigation block, and something similar could be applied.

**Comment by davipontesblog** [comment]
This can be done as of WordPress 5.4 and Gutenberg plugin 7.4. Closing the issue here. See https://github.com/Automattic/wp-calypso/issues/29264
