### ISSUE TITLE
Paragraph Block: Reverse background and text color order in the sidebar

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37293]
Please watch the "Editing a Page Template: Paragraph Block" testing video on this post: p58i-8d4-p2

It took him some time to discover that font and color options were in the sidebar, he looked through everything in the block options menu first. He then looked at the sidebar but clicked off the paragraph block first, meaning he did not initially see paragraph block settings. Once reselected he found the options.

His expectation without thinking about it was that the first color settings option would be for the text, not the background color. This seems completely logical to me. “I thought it would change the font color, oh I didn’t notice that was the background color”.

-----

It seems logical to me that text color would be first, before background color.

**Comment by bluefuton** [comment]
From the testing writeup:

"The user's expectation without thinking about it was that the first color settings option would be for the text, not the background color."

I frequently run into this one myself.

**Comment by Addison-Stavlo** [comment]
It looks like this must have been done already at some point.  I will close this issue as well.
