### ISSUE TITLE
Paragraph Block: Make it clearer block settings can be toggled

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37294]
Please watch the "Editing a Page Template: Paragraph Block" testing video on this post: p58i-8d4-p2

He selects the Uppercase option in the more menu, but then gets very confused, he does not realize that you can select the uppercase menu again to change it back to lowercase. He ends up getting frustrated and retyping the paragraph text from scratch. He does not find the undo option, or realize the setting was a toggle, the dark “on” icon was not clear at all. “What’s happening? There’s no undo! I have to type the whole thing again unless I’m missing something…”.

-----

The toggle between off and on in this settings menu is not clear. What if we used toggle switches, or some clearer indicator that a setting is off or on?

**Comment by rickybanister** [comment]
@ianstewart @apeatling if this is still an issue maybe we should open in the gutenberg repo instead?

**Comment by apeatling** [comment]
This has changed with G2, so I'm inclined to just close.
