### ISSUE TITLE
Gallery Block: Make sure older images are removed when newer images are still uploading

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37291]
Please watch the "Editing a Page Template: Gallery Block" testing video on this post: p58i-8d4-p2

If you remove existing images in a gallery block while new images are still uploading, the existing images that you removed will reappear. The user in this testing video struggled with this multiple times.

**Comment by Addison-Stavlo** [comment]
I have opened a PR in core for this - https://github.com/WordPress/gutenberg/pull/19134

**Comment by lancewillett** [comment]
Closing as a duplicate of https://github.com/WordPress/gutenberg/pull/19134

No need to track it in two places; and once fixed it'll be merged into WordPress.com in a future Gutenberg core merge.
