### ISSUE TITLE
Connections: Missing icon & info for Google Drive section

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#37302]
#### Steps to reproduce
1. Starting at URL: /marketing/connections/$site_url
2. check google drive section
3. see the issue

#### What I expected

To see Google Drive icon, and details once the card is expanded

#### What happened instead

An icon is missing, the expanded card is empty.

#### Browser / OS version

Chrome / MacOS

#### Screenshot / Video

<img width="1059" alt="Sharing ‹ Plain   Obvious — WordPress com 2019-11-04 14-52-39" src="https://user-images.githubusercontent.com/5654161/68122348-cf10f500-ff12-11e9-82e4-a9ebad839325.png">

**Comment by rachelmcr** [comment]
I no longer see Google Drive as an option on this page; looks like it is under development (not meant to appear in the list of available connections) and was removed outside the development environment in https://github.com/Automattic/wp-calypso/pull/37358.
