### ISSUE TITLE
Hosting: Add Tracks Events

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37317]
This is a tracking issue for any metrics/instrumentation we need to add. If folks take a task, please add your github handle next to the item.

### Add stats + tracks event when a user clicks on
- [x] SFTP Card:  "Enable SFTP" (@gwwar)
- [x] SFTP Card: "Reset password" (@gwwar)
- [x] Database Access: "Open phpMyAdmin" (@gwwar)
- [x] Database Access: "restoring the database password" (@gwwar)
- [x] Support: "Contact us" (@gwwar)

### Verify
- [x] That page analytics works as expected, eg a page view is reported correctly
<img width="1185" alt="Screen Shot 2019-11-22 at 3 05 17 PM" src="https://user-images.githubusercontent.com/1270189/69466623-9a39d600-0d39-11ea-9caf-ebb46ae6b9b5.png">

### Support/Admin Audits
- [ ] If needed, see if we need internal logging as make sense 
- [x] New user facing Activity Log events are tracked in https://github.com/Automattic/wp-calypso/issues/37423

**Comment by kwight** [comment]
> See if adding an activity log entry makes sense

This is being tracked in https://github.com/Automattic/wp-calypso/issues/37423

**Comment by gwwar** [comment]
closed by #37897 activity logs will be handled in https://github.com/Automattic/wp-calypso/issues/37423
