### ISSUE TITLE
Paragraph: "Justify" belongs with block-wide text alignment options

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#37323]
#### Steps to reproduce
1. Starting a new post with the Block Editor.
1. Add a Paragraph block, type some text in.
1. Move the cursor to the block's toolbar.
1. Open the _rich-text formats_ dropdown menu (Fig. 1) by clicking on the chevron next to the Link icon.
1. Notice the options listed and how pertain to inline-text-level formatting: underlining, inline objects, etc.
1. Try selecting a fragment of text from the Paragraph block and applying one of these.
1. Look at the serialised markup for the block and how the chosen formatting is applied inside the paragraph tag (`<p>`).
1. Go back to the dropdown menu and notice the odd one: Justify. Try applying it.
1. Look at the serialised markup again, notice that text justification is a block-wide setting.

#### What I expected
_Justify_ should be an option in the same dropdown as _Align Text Left_, _Centre_, _Right_ (Fig. 2). At the very least, until integration constraints are solved, it could live as button next to that dropdown.

#### What happened instead
_Justify_ is wrongly categorised as an inline format.

#### Screenshot / Video
<figure>
<figcaption>Fig. 1</figcaption>
<img width="682" alt="Captura de ecrã 2019-11-05, às 11 42 00" src="https://user-images.githubusercontent.com/150562/68205534-7d27a800-ffc2-11e9-978b-d4ded278f258.png">
</figure>

<hr>

<figure>
<figcaption>Fig. 2</figcaption>
<img width="336" alt="Captura de ecrã 2019-11-05, às 11 42 07" src="https://user-images.githubusercontent.com/150562/68205535-7d27a800-ffc2-11e9-8399-ddf0c2e2f855.png">
</figure>

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

This issue remains reproducible as of 
Gutenberg: v10.2.0
CoBlocks: 2.5.3
Editing Toolkit: 3.2465

While there has not been any activity for half a year, I suggest keeping this issue open as it does lead to a slightly confusing UX for users.

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/73455
