### ISSUE TITLE
Gutenboarding: Acquire Intent

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#37325]
The next step will be actually building the first step of the onboarding flow already. Since the data is not persisted in the database (everything is stored locally until the user creates an account or moves to FSE) we can build this step in a pretty functional state already (even if it wouldn’t be useful at all in production yet). The final design is TBD, and we have added some extra pressure on our design team with the change of plans, but if by the time we are supposed to start with this there’s no design, we’ll work on building the original figma concept and then change the UI once the design is ready.

**Comment by davipontesblog** [comment]
Closing this as it's been moved to "Done" in [Gutenboarding](https://github.com/orgs/Automattic/projects/127#card-28759811).
