### ISSUE TITLE
Editor: Feedback from contact form is displaying in Link to existing content

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#3732]
2567489-t

#### Steps to reproduce
1. When editing a post, try to add a link to the body
2. The "Link to existing content" search/dropdown seems to display user information / feedback received from contact form submissions

#### What I expected
Only see posts/pages/content previously published.

#### Screenshot / Video
<img width="623" alt="feedbackbug" src="https://cloud.githubusercontent.com/assets/8488219/13469562/f623cdda-e075-11e5-8008-a63f38de117f.png">

**Comment by jeremeylduvall** [comment]
This looks like a duplicate of #4940 (well, rather that issue is a duplicate of this one). I'm closing in favor of that issue since Andrew laid out a few notes on suspected causes and next steps.
