### ISSUE TITLE
Front Page Meta Description: "Show Previews" Briefly shows preview before redirecting to new tab

### ISSUE THREAD

**Issue by wynwin** [Automattic/wp-calypso#37334]
#### Steps to reproduce
1.  Open a site with a Business or eCommerce plan 
2. Navigate to: Marketing > Traffic > Front Page Meta Description (https://wordpress.com/marketing/traffic/)
3. Enter some text into the "Front Page Meta Description"
4. Select "Show Previews"

#### What I expected
I expected the preview window to popup showing the preview of the meta description (example screenshot: https://en.support.wordpress.com/seo-tools/#front-page-meta-description) 

#### What happened instead
The preview momentarily showed up before closing. The site then opened in a new tab. 

#### Browser / OS version
Confirmed issue in Chrome (78.0.3904.70) & Firefox/Catalina

#### Screenshot / Video
https://cld.wthms.co/3KSu4L

#### Context / Source
#dogfooding

**Comment by scottsweb** [comment]
I am seeing this issue as well:

* Jetpack site 
* Twenty Ninteen
* Chrome 79.0.3945.88

**Comment by pauljacobson** [comment]
I encountered an instance of this in 2931704-zen.

This doesn't seem to be affected by theme. I tested this using the following browsers:

* Firefox Developer Edition v77.0b1 (the user was using the release version of Firefox); and
* Brave v 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit) (with Shields down).

macOS 10.15.4
