### ISSUE TITLE
Menus: Phantom Items Appearing in Menu Areas Drop Down

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#3733]
#### Steps to reproduce
1. Load menu editor for letsgetrightdotcom.wordpress.com
2. Select Primary Menu drop down
3. Observe that there are phantom menu items there, perhaps from a previous theme. The user has switched themes quite a few times.

<img width="344" alt="screen shot 2016-03-02 at 11 08 22 am" src="https://cloud.githubusercontent.com/assets/789137/13472568/53e986aa-e06a-11e5-8ac5-9b369756d0ac.png">

These menus or areas do not appear in the wp-admin menus editor. I tried to reproduce this but had no luck.

**Comment by BandonRandon** [comment]
I can't reproduce this and the user has changed site names. I checked both in the Calypso menu editor as well as the Customizer menu editor. No phantom menu items appear. 

If we get more cases of this, this issue may be reopened.
