### ISSUE TITLE
Hosting: Verify that SFTP credentials are revoked when user role changes [12]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37341]
After creating an SFTP user, if the WordPress.com user role is downgraded or removed from site ensure that SFTP credentials are also revoked.

**Comment by noteeth** [comment]
I tested this issue on https://sftp9.wpcomstaging.com/.  I added a second admin account, provided SFTP creds, removed the admin account and the credentials still work for the FTP client.

**Comment by gwwar** [comment]
Note the related https://github.com/Automattic/wp-calypso/issues/37366, and we'll likely need an async job to catch any stray users should we miss any flows.

**Comment by kwight** [comment]
Related discussion: paYKcK-lp-p2

**Comment by kwight** [comment]
First diff in progress: D35268-code.

**Comment by apeatling** [comment]
@kwight How's the progress on this one?

**Comment by kwight** [comment]
Good! We've got the two [base](https://code.a8c.com/D35332) [methods](https://code.a8c.com/D35336) merged as of today, now just plugging away on the hooks that will use them (eg. D35268-code, D35533-code). As shown in paYKcK-lp-p2 though, there are more than a few cases to cover.

**Comment by gwwar** [comment]
Let's pause work on this since, we're considering other strategies

**Comment by gwwar** [comment]
Alternative handled by https://github.com/Automattic/wp-calypso/issues/37891
