### ISSUE TITLE
Hosting: Avoid forcing height of columns

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#37340]
I noticed that the two columns within the Hosting section are being forced to be the same height. This leads to some awkward whitespace:

![image (7)](https://user-images.githubusercontent.com/191598/68239033-48265000-ffd8-11e9-8ed9-883b71d13990.png)

I'd expect the columns to only be as tall as needed to contain the elements within. Something like this:

![image (8)](https://user-images.githubusercontent.com/191598/68239069-57a59900-ffd8-11e9-977e-5e51ec1a0f7c.png)

**Comment by gwwar** [comment]
Clearing assignees, but noting this is up for grabs in the team backlog.
