### ISSUE TITLE
Hosting: invalidate all SFTP users on plan downgrade [2]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37366]
Let's verify and ensure that when a site downgrades a plan from Buisness, any existing SFTP users are removed, and DB access is no longer available.

**Comment by kwight** [comment]
Related discussion: paYKcK-lp-p2

**Comment by mmtr** [comment]
See paYKcK-lp-p2#comment-425 for implementation details

**Comment by mmtr** [comment]
Fix available in D35533-code.

**Comment by mmtr** [comment]
Noting here that there is not currently a way to revoke existing phpMyAdmin logins and they will eventually expire: paYKcK-lp-p2#comment-415

**Comment by gwwar** [comment]
Please pause on this, until we sort out implementation options

**Comment by gwwar** [comment]
Alternative handled by #37891
