### ISSUE TITLE
Hosting: restore wp-config files

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37372]
When a user accidentally deletes `wp-config.php` let's expose a self-serve option to restore this, as their site will be broken otherwise.

This needs design work. One thought from @westi is that we could maybe consolidate the UI from https://github.com/Automattic/wp-calypso/pull/37220

cc @olaolusoga @shaunandrews 

See p9o2xV-Ca-p2 for implementation details

**Comment by mmtr** [comment]
Not sure if we can know when the `wp-config.php` file is missing on the WP.com side at the moment, so I asked for clarification in p9o2xV-Ca-p2 

Alternatively we could display always a button, but I don't think that's an ideal UI. 

cc @olaolusoga @shaunandrews

**Comment by mmtr** [comment]
It has been suggested that we display the button only if a a required param is present on the URL (ie. `hosting-admin/:site?restoreWpConfig`), so the Atomic frontend site can use that link instead of the current "contact support" link:

![image](https://user-images.githubusercontent.com/1233880/68585385-65e53080-0482-11ea-8144-497202fdb863.png)

**Comment by shaunandrews** [comment]
Can we make it so the file can't be deleted? Or, if it is, automatically restore it?

**Comment by mmtr** [comment]
> Can we make it so the file can't be deleted? Or, if it is, automatically restore it?

Users might have legit reasons for deleting a file, for example when saving it as a backup file (`mv wp-config.php wp-config.backup.php`) before uploading/creating a new `wp-config.php` file, so I don't think we should restrict users from deleting it.

**Comment by westi** [comment]
> Can we make it so the file can't be deleted? Or, if it is, automatically restore it?

Not really.  The file needs to be editable at which point it can be deleted.

**Comment by mmtr** [comment]
Server-side part of this ready at D35302-code. This exposes a new `wpcom/v2/hosting/restore-wp-config` endpoint that will be consumed by Calypso when a user clicks on the restore button.

Will work on the client-side part tomorrow.

**Comment by mmtr** [comment]
@kwight raised a very good concern about this feature during our team retrospective today. Wouldn't be this covered by restores done with Rewind? If so, what's the reasoning behind adding a separate restore process only for `wp-config.php` files?

**Comment by westi** [comment]
> @kwight raised a very good concern about this feature during our team retrospective today. Wouldn't be this covered by restores done with Rewind? If so, what's the reasoning behind adding a separate restore process only for `wp-config.php` files?

The point is this can be a single click fix for the site.

**Comment by mmtr** [comment]
> The point is this can be a single click fix for the site.

Maybe we could add a "Restore" button when developing https://github.com/Automattic/wp-calypso/issues/37258? That way this would be also a single click action.

**Comment by mmtr** [comment]
Oh wait, it seems that Rewind fails to restore site if wp-config is deleted: https://github.com/Automattic/jpop-issues/issues/4469 

cc @seear

**Comment by seear** [comment]
We actually do not restore wp-config.php to Atomic sites at all currently. Discussion here: pa0RFL-su-p2.

**Comment by olaolusoga** [comment]
When user selects the link from front end (we should adjust the copy to something like "Missing wp-config.php. Log in to your hosting dashboard to restore the file.". Will create issue.) we should redirect them to the SMFTP/MySQL section, and display the notice below.

**Notice:**
<img width="934" alt="Screen Shot 2019-11-13 at 5 05 53 PM" src="https://user-images.githubusercontent.com/1382943/68808682-4263e680-0638-11ea-9732-0e8ceee6436c.png">

**In page:**
<img width="1429" alt="Screen Shot 2019-11-13 at 5 05 43 PM" src="https://user-images.githubusercontent.com/1382943/68808704-4b54b800-0638-11ea-81a1-975e9d8f6a98.png">

**Comment by westi** [comment]
> When user selects the link from front end (we should adjust the copy to something like "Missing wp-config.php. Log in to your hosting dashboard to restore the file.". Will create issue.) we should redirect them to the SMFTP/MySQL section, and display the notice below.

This sounds great, when we are ready with a working link I can update the copy that appears on the sites, so please assign the issue to me.

**Comment by mmtr** [comment]
We're considering to wait for Rewind to restore the `wp-config.php` file. See pa0RFL-su-p2#comment-1625

**Comment by gwwar** [comment]
@seear I'm closing this one in favor of 4469-jpop-issues, please reopen if this won't be covered by that
