### ISSUE TITLE
Hosting: Users need a way to restore any deleted symlinked themes.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#37424]
As reported by @kdevnel, it's possible to delete symlinked themes, and then have no way to restore that theme for the site; Rewind will not work.

See: p58i-8eh-p2#comment-43563

**Comment by glendaviesnz** [comment]
I don't think there is much for us to do here at this stage. It looks like wpcom may already have a function that Rewind can hook into to  - have referenced in https://github.com/Automattic/jpop-issues/issues/4474  - will wait to see where Rewind and Atomic folks want to head with this.

**Comment by mmtr** [comment]
pa0RFL-su-p2 is also relevant

**Comment by apeatling** [comment]
It sounds like this will be handled by @seear and rewind folks? It could be moved out of Serenity sprint. /cc @gwwar

**Comment by gwwar** [comment]
@seear closing in favor of the rewind issue. Let us know if we should reopen otherwise.
