### ISSUE TITLE
Social Links Block: No Option to Open Links in New Tab

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#37428]
#### Steps to reproduce
1. Starting at URL: Create a new Page
2. Add the Social Links Block
3. Populate the block with social media links and publish the page.
4. Visit the page and click a link. All of the links open in the same window as the site, directing the reader away from your site, and to social media. There is no option to change this in the block.
5. User requested an option to have links open in a new tab.

#### What I expected
We have the option to open links in a new tab in every other social links section (social menus, widgets), so the option was expected here as well.

#### What happened instead
No options available to open social links in a new tab.

#### Browser / OS version
All.

#### Context / Source
#empathy #perspective #reallife #user-report

**Comment by kwight** [comment]
@scosgro Would you like to open a Gutenberg core ticket for this? You're right, other blocks like Button have a Link Settings > Open in new tab setting, can't think of a reason why Social Links wouldn't.

**Comment by scosgro** [comment]
Added here: https://github.com/WordPress/gutenberg/issues/18486

**Comment by simison** [comment]
Done in https://github.com/WordPress/gutenberg/pull/25468
