### ISSUE TITLE
Hosting: Add an activity log entry for phpMyAdmin access. [4]

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#37423]
It will be very helpful for support people to know clearly if and when a user accessed these tools. Let's add an Audit Log entry for the user when they access either tool.

Maybe to start:
* DB Access
* SFTP User Creation / Deletion

**Comment by automattic-ian** [comment]
Ideally if this could be mirrored in activity log so users can see too, this would be especially useful on sites with multiple administrators.

**Comment by glendaviesnz** [comment]
Based in reply to comment here p58i-8eh-p2 going to just add an activity log when user accesses pma for now.

**Comment by glendaviesnz** [comment]
Some initial work was done on this at D35467-code - but when revisiting see note about whether we just append these activities to existing `user` activities instead of creating new `atomic_hosting` category.

**Comment by gwwar** [comment]
@apeatling @automattic-ian any specific events we'd like to bubble up? I think new SFTP user and DB access to start?

**Comment by gwwar** [comment]
Let's see if we can collaborate with Jetpack folks on this one.

**Comment by automattic-ian** [comment]
> any specific events we'd like to bubble up? I think new SFTP user and DB access to start?

@gwwar ideally all of them eventually. Part of the appeal of Activity Log is that it covers just about everything on a site. If SFTP and DB access introduce blindspots into Activity Log that lessens its value to our users. 

For a start though as you mentioned, New SFTP users, and connecting to the DB sounds perfect.

**Comment by glendaviesnz** [comment]
Waiting on feedback to 9rlnk-p2 on best pattern to use for this.

**Comment by mmtr** [comment]
Quick update to note that after addressing feedback received at p9rlnk-Ag-p2, we have 2 diffs ready for review adding activity logs for:
- Database accesses from phpMyAdmin (D35467-code).
- New SFTP users and password reset (D36185-code).

**Comment by kwight** [comment]
Work for this is complete. Rather than audit log entries, we've added Activity Log entries, so that they're visible to both support and users.

SFTP was handled in D36185-code, and phpMyAdmin was in D35796-code.
