### ISSUE TITLE
Hosting: Remove SFTP credentials on plan expiry.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#37425]
We should clean up SFTP credentials for users whose Business plans have expired. Adding this to Phase 2, since it's not considered urgent for initial release; we don't currently lock down sites at all on plan expiry anyways.

See: paYKcK-lp-p2#comment-400

**Comment by gwwar** [comment]
We can probably close this one out unless atomic folks feel strongly about this
