### ISSUE TITLE
Build: Creating npm-shrinkwrap.js on npm 3 breaks build

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#3743]
#### Steps to reproduce
1. https://github.com/Automattic/wp-calypso/blob/master/docs/shrinkwrap.md#bumping-sub-dependencies-in-all-packages Follow these steps
2. Make a pull request
3. Observe broken build on CircleCI

#### What I expected

I expected build not to be broken

#### What happened instead

Build is broken. https://circleci.com/gh/Automattic/wp-calypso/9379

#### Browser / OS version

Ubuntu 15.10

**Comment by lancewillett** [comment]
Hi @belcherj — could you try this one again? Still happening (or can we close it?)

**Comment by belcherj** [comment]
Hi @lancewillett on first test it looks like tests are passing locally.
