### ISSUE TITLE
$ amounts stripped out of blocks with FSE active

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#37432]
#### Steps to reproduce
1. Start on a site using Maywood theme with Full Site Editing enabled
2. Create a new page - template selection doesn't appear to matter
3. Add some text to a paragraph block, including a $ amount, e.g. "$20"
4. Publish the page
5. Leave the editor, then edit the page again

#### What I expected
For the page content in the editor to be the same as the last time I closed it.

#### What happened instead
The $ amount has disappeared, from both the visual and code editors. Revision history shows the current revision still showing the amount, though, and it still appears on the front end, but not in the editor.

Confirmed with paragraph, list, heading and blockquote block.

Does not happen in the block editor on a site without FSE. Tested with and without the Maywood theme.

Does not happen if the amount contains a space, e.g. `$ 20`, nor if text follows the $ symbol, e.g. `$three`, nor if the $ symbol is used on its own. It only happens for numerical values as you'd use when indicating the cost of something, e.g. `$20`

It does not happen with other currency values such as £20, €20 or ¥20

#### Context / Source

Reported by a user in the [support forums](https://en.forums.wordpress.com/topic/part-of-my-page-keeps-erasing-itself/).

**Comment by tbradsha** [comment]
Reported via in 16846570-hc. The live site shows correctly (unless one saves the stripped content again). Perhaps an errant regex or template var?

Before saving/refreshing the editor:
![image](https://user-images.githubusercontent.com/32492176/71921679-8bbb4880-3146-11ea-8255-57f2b570a9b1.png)

After saving/refreshing the editor:
![image](https://user-images.githubusercontent.com/32492176/71921975-3a5f8900-3147-11ea-8973-48c187b77272.png)

**Comment by tbradsha** [comment]
#38545

**Comment by scosgro** [comment]
User wanted an update on this. in 2770350zd

Let them know we don't have an ETA at this time.

**Comment by davipontesblog** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/38545
