### ISSUE TITLE
Reader: searching for empty URLs on the Manage Following page should not be allowed

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#3744]
**Steps to reproduce:**

1. visit the Manage Following page
2. click on the "Follow Site" button to find a site to follow
3. type in a [dot]-something and the deactivated Follow button changes to an active state

![screenshot 2016-03-02 18 11 32](https://cloud.githubusercontent.com/assets/4924246/13482464/4fb00234-e0a2-11e5-9635-af6ae4c03e56.png)

**Comment by bluefuton** [comment]
URL validation... always a joy.

We're not currently able to lookup feed URLs in real time (waiting on some Elastic Search magic for that), and we currently do a very basic sanity check:
- does the hostname contain at least one dot?
- does the hostname have a valid-looking .tld?

We could add a third check to make sure the segment before the .tld has at least one character.

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/3748
