### ISSUE TITLE
Login: Standalone Recovery SMS Number option not working

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#37459]
#### Steps to reproduce
1. On a WordPress.com account, visit https://wordpress.com/me/security/account-recovery
2. Enter and verify a `Recovery SMS Number`.
3. Make sure the account does **not** have Two-Step Auth active.
4. Logout of the account and attempt to use the password reset form: https://wordpress.com/wp-login.php?action=lostpassword

#### What I expected

* When resetting the password, that the `SMS Password Reset` form would show accepting a code sent to the `Recovery SMS Number` previously setup.

#### What happened instead

* The `Recovery SMS Number` is not considered, and a password reset message is dispatched to the account email.
* Note that enabling Two-Step Auth via SMS shows the expected `SMS Password Reset` form which works.

#### Context / Source
p9k6jH-D2-p2

**Comment by jeyip** [comment]
I can reproduce the issue by following the instructions from the PR description 👍

**Comment by jeyip** [comment]
Drafted a phab diff for this. ~Currently trying to figure out how to test it 🤔~ Added testing notes!

D58565-code

**Comment by jeyip** [comment]
@davipontesblog @samiff Hi team -- I'm drafting a fix for this. I had a product question, and was wondering if either of you happen to know.

If a user has a two-step authentication number and a recovery sms number that are different, which do we ping when they attempt SMS recovery? Currently, it defaults to the two-step number. To me, sending it to the recovery number seems to make more sense, but curious what your thoughts are.

**Comment by samiff** [comment]
> If a user has a two-step authentication number and a recovery sms number that are different, which do we ping when they attempt SMS recovery? Currently, it defaults to the two-step number.

@jeyip As far as I can tell, currently the `Recovery SMS number` is not used in either case (standalone Recovery SMS, or Recovery SMS + Two-step SMS).

> To me, sending it to the recovery number seems to make more sense, but curious what your thoughts are.

Would sending to both be an option? If not, maybe using the Two-Step might be more relevant in the sense that it is _required_ to access the account.

In any case, it'd be great to get the standalone Recovery SMS working (or deprecated) 👍

**Comment by jeyip** [comment]
> As far as I can tell, currently the Recovery SMS number is not used in either case (standalone Recovery SMS, or Recovery SMS + Two-step SMS)

Ah I think I could've been clearer here. Yeah, the SMS recovery number doesn't work in either case right now 😅 

What I meant to do was ask, assuming that the recovery SMS number _is_ working again, what should we do when a user has two distinct phone numbers -- one number for the two-step SMS, and another for the recovery SMS. Which should we send the recovery SMS to? 

<img width="1344" alt="Screen Shot 2021-03-11 at 11 14 14 AM" src="https://user-images.githubusercontent.com/5414230/110870651-bd1b3100-8281-11eb-99ce-c4a61eac9ae0.png">

> Would sending to both be an option? If not, maybe using the Two-Step might be more relevant in the sense that it is required to access the account.

You still answered my question though, so thanks for the response!

> In any case, it'd be great to get the standalone Recovery SMS working (or deprecated) 👍

Yep! D58565-code should get it working again.

**Comment by ciampo** [comment]
Hey @jeyip! As I'm going through the gardening board, I'm just checking on the progress of this issue, since it's marked as "in review", but D58565-code still has pending feedback

Do you think you'll address this feedback soon? Should this be moved back to "In progress"? If the changes that are required are minor, I could try to pick it up (although I'm not really knowledgable with that part of the codebase)

Thank you!

**Comment by jeyip** [comment]
Hi @ciampo! Thanks for checking in 🙏 

I've been a little busier with other priorities the past few weeks and was hoping someone in gardening would've picked it up (p1615781382183400-slack-C013QHLF28Y and p1616421141015200-slack-C013QHLF28Y). 

> although I'm not really knowledgable with that part of the codebase

No worries! I'll have some extra time next week, and would be more than happy to take it across the finish line then if you're busy 🙂

**Comment by ciampo** [comment]
> No worries! I'll have some extra time next week, and would be more than happy to take it across the finish line then if you're busy 🙂

Alright @jeyip — I'll give it some time and see where I can get. If we could pair on it next week, it'd be great!

**Comment by yansern** [comment]
This is tested and now deployed in D58565-code.
