### ISSUE TITLE
Gutenframe: Verify flows with upcoming `SameSite` cookie changes.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#37451]
With Chrome 80 in February 2020, Chrome will be changing the default “SameSite” cookie behavior to effectively disable 3rd party cookies. We can avoid this by settings `SameSite:None` on those cookies and settings the secure attribute on the cookie ( meaning it will only be usable over HTTPS ).

We need to verify if any changes are needed for our Gutenframe flows. See: pb6Nl-daR-p2.

**Comment by gwwar** [comment]
Please test in Chrome Canary. This is an investigation task, please open new issues if there's additional work needed, and we'll prioritize in upcoming sprints.

**Comment by mmtr** [comment]
Verified Simple sites still work (both with and without mapped domains), but Atomic and Jetpack sites cannot load Gutenframe. Thankfully, our fallback ends up redirecting to the WP Admin editor, but we should keep existing behavior (load Gutenframe) by setting `SameSite:None` on the auth cookies. 

Opened a separate issue: https://github.com/Automattic/wp-calypso/issues/37558.

**Comment by kwight** [comment]
Awesome that @glendaviesnz 's fallback work remains robust – nice to know we wouldn't fall over anyways.
