### ISSUE TITLE
Facebook embeds don't resize on mobile

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#37469]
#### Steps to reproduce
1. Add a Facebook embed to a page
2. View on mobile / small screen

#### What I expected

The embed should fit the screen size.

#### What happened instead

It's cut off:

![img](https://cld.wthms.co/cxh3DD+)

#### Context / Source

2478519-zen

Also a related open issue, I don't think it's theme specific since I've tested on multiple themes and they all have this issue:

https://github.com/Automattic/themes/issues/989

Temporary solution:

```
/* Decrease Facebook Embed width on Mobile (DOC) */

@media only screen and (max-width: 767px) {
	.fb_iframe_widget iframe {
	    width: 270px !important;
	}
}
```

**Comment by edwinho89** [comment]
Still experiencing this on 34360190-hc

Provided CSS as workaround below:

```
/* Facebook embed overflow fix mobile | 4808591-zen EH */
@media only screen and (max-width: 768px){
    #facebook * {
        max-width: 100%;
    }
}
```
