### ISSUE TITLE
FSE: Maywood + WooCommerce breaks page editor.

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#37494]
When an AT site has FSE enabled with the Maywood theme and a user then adds WooCommerce, the page editor stops working with the error:

`The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.`

PHP-ERRORS in CLI shows:
`Uncaught Error: Call to a member function get_cart_subtotal() on null in /wordpress/themes/pub/varia/inc/woocommerce.php:105`

Disabling the FSE plugin fixes the issue and the page editor can then load. 

hc-16584047

**Comment by khristiansnyder** [comment]
I see another instance of this in 2470526-zen

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom. Please reopen if still an issue.
