### ISSUE TITLE
Site Picker: allow people to "star" sites.

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#375]
This is an idea started by @rickybanister:

> Users with more than a few sites have some trouble using the site picker. There isn't yet an interface for managing the hiding/showing of sites. That brings us to: Starred Sites. We star their "primary site" by default to introduce them to the feature. An "edit" button mode allows them to manage their stars within the picker.

<img width="780" alt="2aba7ad2-3b8d-11e5-9159-87315b1949ea" src="https://cloud.githubusercontent.com/assets/548849/11318023/8116dd76-9042-11e5-923c-ddf5f1870cc4.png">

This idea could easily be expanded to handle hiding/showing sites if we accommodate a star and a visibility icon. (This iteration would use an EDIT button at the bottom next to the add button since you are editing more than just stars.)

<img width="1010" alt="5686ded0-3c28-11e5-9803-5cee4646b0ae" src="https://cloud.githubusercontent.com/assets/548849/11318059/7b885c4e-9043-11e5-9023-65e830b544dd.png">

**Comment by rickybanister** [comment]
After much conversation and design huddling with @mtias we created an interface idea for editing starred sites (and editing site icon) within the site card.

It also includes a more integrated hover/link to a site's front-end.

<img width="476" alt="screen shot 2016-01-27 at 12 59 50 pm" src="https://cloud.githubusercontent.com/assets/437258/12623114/9daeca8c-c4f6-11e5-8316-bc3048ac9c4f.png">

**Comment by folletto** [comment]
Looks good! :+1:
