### ISSUE TITLE
Auto-renew toggle: Send email notification confirming auto-renew has been disabled

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#37519]
A user reached out in #2484299-zen after a subscription renewed that they believed they had disabled auto-renew for. They suggested we send an email notification when a user toggles auto-renew on or off, confirming the change.

I think this is a good idea - for users who claim they disabled it but actually didn't, we can ask them to search their inbox for the confirmation, and additionally, it provides the user with some additional peace of mind that the billing change is confirmed. I told the user I'd pass their feedback along.

**Comment by thehenrybyrd** [comment]
Great idea! This would be really helpful and I'm sure users would love to have that confirmation.

**Comment by DavidRothstein** [comment]
This is not really a Calypso issue, so I'll close it in favor of https://github.com/Automattic/payments-shilling/issues/2701 where there is more internal discussion.  (But I'll make sure to note there the suggestion that it not just be sent for turning auto-renew off, but also for turning auto-renew back on.)
