### ISSUE TITLE
Support User: Display correct notifications

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#3751]
Currently the notifications are not displaying for the support user (to prevent notifications being missed by actual user)

Solution would be to display the notifications to the SU but not to mark them as read

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue.

**Comment by alisterscott** [comment]
@jordwest: isn't this by design so the actual user doesn't miss notifications?

**Comment by jordwest** [comment]
@alisterscott: We did this to prevent marking the notifications as read, but a better solution would be to show them and prevent them being marked as read.
