### ISSUE TITLE
Purchases: receipts cannot be printed in Chrome

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#37549]
#### Steps to reproduce 
1. Go to Me > Manage Purchases > Billing History
2. Pick a recent purchase and click on "View Receipt"
3. Click on the Print Receipt.
4. In Firefox I do not get a Print preview and can print with no issues. In Chrome, however (v. 78.0.3904.97), I see this:

![image](https://user-images.githubusercontent.com/426388/68754839-cd78b880-0607-11ea-854c-bd81562d5202.png)

5. Proceeding with printing (or in my case saving to PDF) generates a file with those same issues.

Originally reported in 2488800-zen

**Comment by jeherve** [comment]
cc @melanieharari who may know best how to triage this. Thank you!

**Comment by andreabadgley19** [comment]
I got another report of this in 13478775-hc (followup in 2490274-zen). Like Jeremy, I am able to replicate in my own account in Chrome and in the user's account via Switch User: the print receipt is gobbledy gook while the screen receipt looks fine. In Firefox the print receipt is a-okay -- it's just Chrome.

**Comment by eamcgill90** [comment]
Another report: 16738114-hc 
Followed up: 2501114-zen

Emailed them the receipt in the meantime.

**Comment by kanishkdudeja** [comment]
Looks like it has to do something with the font used in Calypso. I used a [Font Changer](https://chrome.google.com/webstore/detail/font-changer-with-google/jgjhhoglgjdklldfgoffdiaceffijeke?hl=en) extension in Chrome to override the webpage font to Arial and it’s now printing the receipt correctly.

**Comment by kanishkdudeja** [comment]
This seems definitely not specific to the receipts page or the payments related area in Calypso since I tried printing a couple of other different pages in Calypso (in Chrome) and some of them showed garbled characters in the printed PDF.

**Comment by samiff** [comment]
2531736-zen

Advised on using FF as workaround for time being.

**Comment by adekbadek** [comment]
2542458-zen
(As above)

**Comment by jeherve** [comment]
This may not be specific to WordPress.com, and may be an issue with Chrome itself:
https://mobile.twitter.com/BillErickson/status/1202737958228500480

**Comment by liviopv** [comment]
Another in #17345470-hc I was able to reproduce in Google Chrome. Printing the receipt directly from our payment system works.

**Comment by tbradsha** [comment]
2564979-zen

**Comment by n3f** [comment]
Seems the problem is with the font: `BlinkMacSystemFont`.  By adding a print media query I was able to get rid of the issue:

```css
@media print {
    body {
        font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen-Sans,Ubuntu,Cantarell,Helvetica Neue,sans-serif;
    }
}
```

**Comment by DavidRothstein** [comment]
Worth noting that the above fix was for receipts specifically (not the more general problem of other pages in Calypso being unprintable in Chrome).  But it sounds like this is fundamentally a Chrome bug, and in practice people were pretty much only encountering it on the receipts page anyway.
