### ISSUE TITLE
Hosting: make left column cards 70%, right column 30%

### ISSUE THREAD

**Issue by olaolusoga** [Automattic/wp-calypso#37585]
**Current:**
<img width="1314" alt="Screen Shot 2019-11-13 at 7 35 36 PM" src="https://user-images.githubusercontent.com/1382943/68816546-cc1daf00-064c-11ea-9395-9ee90ee9be89.png">

**Should be:**
<img width="1542" alt="Screen Shot 2019-11-14 at 7 06 04 PM" src="https://user-images.githubusercontent.com/1382943/68906309-d786de00-0711-11ea-99bc-9e663efe337d.png">

**Comment by gwwar** [comment]
@olaolusoga did we still want this one? Mocks in the settings section have cards in a single column.

**Comment by gwwar** [comment]
Closing this since we're moving this under settings.

**Comment by gwwar** [comment]
Barry requested that this section remain a top-level menu item under manage. The Atomic team is planning on adding many more features, so this would provide more room for growth.

**Comment by mmtr** [comment]
@olaolusoga what's the desired behavior for the SFTP credentials labels (URL, port, username, password) if they exceed the max available space in other languages?
