### ISSUE TITLE
Hosting: Add header, and subheader to page, Change Section Name

### ISSUE THREAD

**Issue by olaolusoga** [Automattic/wp-calypso#37584]
The fix the flows team are working on implementing a heading pattern across dotcom (link to [Calypso doc](https://wpcalypso.wordpress.com/devdocs/design/formatted-header)) 

Ongoing work in https://github.com/Automattic/wp-calypso/pull/37343

Also, let's rename the section name to "Hosting Configuration", since "Hosting Access" and "SFTP & MySQL" doesn't fit as well with planned future features. The route name should also match the new name -> `/hosting-config`. See p1574259922359400-slack-atomic

**Mock of page with header/subheader:**
<img width="1280" alt="Screen Shot 2019-11-14 at 7 40 25 PM" src="https://user-images.githubusercontent.com/1382943/68907677-a4931900-0716-11ea-92aa-75d061c90be0.png">

**Comment by apeatling** [comment]
I think this should be the limit of the scope changes for the design before shipping Phase 1, and further iterations happen beyond Phase 1 shipping.

**Comment by gwwar** [comment]
One note here was that I think @apeatling agreed to move this under settings

**Comment by apeatling** [comment]
This is a version prior to @olaolusoga's latest work on the P2 thread.

**Comment by gwwar** [comment]
Closing this one out since folks agreed to move this to a Settings subsection

**Comment by gwwar** [comment]
Barry requested that this section remain a top-level menu item under manage. The Atomic team is planning on adding many more features, so this would provide more room for growth.

**Comment by kwight** [comment]
Note we've settled on "Hosting Configuration" as the page title, at the `/hosting-config` path.
