### ISSUE TITLE
Hosting: Replace spinner for Reset Password to Busy Button State [2]

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#37580]
The spinner to indicate we're resetting the SFTP password causes the SFTP card to redraw, and is awkwardly positioned.

<img width="696" alt="Screen Shot 2019-11-13 at 1 01 08 PM" src="https://user-images.githubusercontent.com/349751/68804136-ee480a80-0615-11ea-90fa-9c1e5761916a.png">

Maybe it could be positioned to the right of the Reset Password button instead?

**Comment by kwight** [comment]
cc/ @shaunandrews @olaolusoga

**Comment by olaolusoga** [comment]
Can we do something like this instead? 

![Screen Capture on 2019-11-13 at 17-01-47](https://user-images.githubusercontent.com/1382943/68808287-64109e00-0637-11ea-802c-47d5cdc70d43.gif)

Button text changes to "Reseting...", then password displays. The spinner seems unnecessary.

**Comment by shaunandrews** [comment]
We could use the busy state of the Button component.

**Comment by olaolusoga** [comment]
Link to busy state button https://wpcalypso.wordpress.com/devdocs/design/button . @kwight ignore my previous suggestion. Agree with using the busy button state component

**Comment by gwwar** [comment]
As a heads up, the spinner is shared between the card and the button
