### ISSUE TITLE
Videopress image thumbnails confusing

### ISSUE THREAD

**Issue by cena** [Automattic/wp-calypso#37599]
#### Steps to reproduce
Discussed in: 4472-gh-jpop-issues

Side Issue summary (from above): The original video, and three thumbnail images, are displayed in  the media library, which makes it look like there are 4 of the same video.

That's the expected display in Calypso today: each one of the video thumbnails is saved and you will see them as images in the media library,  but this is unexpected/confusing.

#painpoint 
#confusing

**Comment by lancewillett** [comment]
I suggest closing this as "works but isn't ideal" since we don't have plans to work on this feature at the moment.

Let's see if it comes up again with other reports in the future, and it can be re-opened.
