### ISSUE TITLE
Pages: Cannot un-set (or delete!) a Posts Page once set in Calypso

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#37618]
After using the Calypso […] menu on /pages to set a page as my posts page …

![image](https://user-images.githubusercontent.com/545779/68897704-aa2b3780-06f3-11ea-8f51-26937ea70900.png)

… I cannot undo that action nor can I delete the page. 

I expected:

1. To be able to "Set as normal page" (or something similar).
2. To be able to still delete the page.

**Comment by ianstewart** [comment]
@michaeldcain this might be very confusing with all of the single page sites we're creating. @apeatling I added this to the FSE bug triage as it has the customizer turned off right now. In the customizer this works more as expected.

**Comment by vindl** [comment]
cc @Copons in case this sounds familiar :)
