### ISSUE TITLE
Editor: Investigate resource hints as alternative to background preview loading

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3762]
The `<EditorPreview />` component loads the current post preview in a hidden element on the page, which has the advantage of enabling a faster perceived speed when pressing the Preview button in the editor, but has historically caused issues depending on the rendered contents of the preview (e.g. autoplay videos, focus on page load).

There are specifications for providing hints to the browser for preloading content, and we should explore whether we can leverage any for accomplishing this same purpose, without needing to have the preview rendered on the page at all times.

See: https://www.w3.org/TR/resource-hints/

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

@aduth does this issue need to be addressed separately in the Gutenberg editor?

**Comment by aduth** [comment]
It doesn't need to be explored in that Gutenberg doesn't have the same background-loaded preview (the in-app preview overlay). It's not clear to me whether at the point that Gutenberg is integrated into Calypso that we'd want to try to preserve the current behavior or allow the preview to open in a new separate tab.
