### ISSUE TITLE
Image block not maintaining cropped settings

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#37636]
Using Calypso’s block editor, if you add an image block to a page/post and edit it the image to crop it, the block holds onto the cropped image until you change its size in the block settings. Then, the image shows as the original, even though the image in the media library is still showing the cropped view.

#### Steps to reproduce
1. From the Page/Post editor, add an image block.
2. Within the image selection dialog box, edit the image by cropping it.
3. Save the image in the block. You should see that the cropped image is displayed.
4. From the block settings of the image, change the size (e.g. to Full, Medium, etc).

#### What I expected

The image in the block to maintain the cropped display.

#### What happened instead

The image in the block reverted back to the original, uncropped shape, despite the fact the image in the Media Library shows as cropped.

#### Browser / OS version

Chrome, but I don't think that's a cause.

#### Screenshot / Video

https://cld.wthms.co/0mf6YO/HUfq6nL4gX

#### Context / Source

#user-report #16638011-hc

**Comment by tijosh** [comment]
Please ping me when this is resolved so I can notify the user from the original report.

**Comment by cathymcbride** [comment]
Looks like this has been fixed along the way....
