### ISSUE TITLE
Store: No Rates Available when Printing Shipping Labels

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#37638]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/store/order/ with an existing order
2. Click "Print label & fulfill"
3. Under Packages, select any Shipping Package (I used "Regional Rate Box A1")
4. Add a total weight
5. Click "Use these packages"

#### What I expected

The ability to select a shipping rate and print shipping labels. 

#### What happened instead

Cannot select a rate, and receive the error message "No rates available, please double check dimensions and weight or try using different packaging"

The issue does not happen in WP-Admin with the same product, same shipping settings. It just started yesterday. 

#### Browser / OS version

Chrome 78.0.3904.97 / Mac

#### Screenshot / Video

![Screenshot](https://cld.wthms.co/z9WiOG+)
Image URL: https://cld.wthms.co/z9WiOG

#2493385-zen

**Comment by chaitanyamsv** [comment]
Another report in 14333150-hc

**Comment by shaunkuschel** [comment]
Related:

https://extendomattic.wordpress.com/2019/11/16/services-on-store-missing-flat-rate-packages/

**Comment by chaitanyamsv** [comment]
Another report in 16208768-hc

**Comment by andreabadgley19** [comment]
Another report in 2499600-zen.

**Comment by m155y** [comment]
Another report in 2504764-zen
