### ISSUE TITLE
Block Editor Jumps to the Top of the Page in Microsoft Edge (Atomic Only, Gutenberg Plugin deactivated)

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#37644]
#### Steps to reproduce
1. Using Microsoft Edge: Create a new WordPress.com Business Plan Site
2. Install a plugin on it (any plugin, it just needs to go Atomic)
3. Deactivate all plugins except Jetpack and Akismet
4. Create a new page, and add enough content to that page so that a scrollbar appears.
5. Once the scroll bar appears, adding content to the bottom of that page will cause the editor to jump to the top of the page for every keypress.

Activating the latest version of the Gutenberg plugin (6.9.0) resolves this issue. With it deactivated though, this issue comes back.

#### What I expected
The editor not to jump to the top with every keypress.

#### What happened instead
The editor jumps to the top of the page with every keypress.

#### Browser / OS version
Microsoft Edge 44.18362.449.0 / Windows 10

#### Screenshot / Video
https://cloudup.com/ch8-1zhLqkX

#### Context / Source
#reallife #stresscase  #user-report

**Comment by gwwar** [comment]
Likely related to https://github.com/WordPress/gutenberg/issues/18546

**Comment by Robertght** [comment]
@scosgro  It looks the same as https://github.com/Automattic/wp-calypso/issues/36417

**Comment by cathymcbride** [comment]
@scosgro Do you still repro?

**Comment by scosgro** [comment]
> 
> 
> @scosgro Do you still repro?

Nope! Looks to be solved. Closing this now.
