### ISSUE TITLE
Theme Showcase: Incorrect Link To Storefront Demo site

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#37658]
#### Steps to reproduce

On an atomic Business plan site:

1. Install & activate WooCommerce.
2. Starting at URL: https://wordpress.com/themes/
2. Search for the Storefront theme
3. Click the three dots and then "Live Demo"

#### What I expected

I expected to view a site that showcases the Storefront theme, like this:

https://themes.woocommerce.com/storefront/

#### What happened instead

It opens this page:

https://wp-themes.com/storefront/?demo=true&iframe=true&theme_preview=true

While that seems to be using the Storefront theme, it is not a demo site that shows the features of Storefront. For example, no products on the homepage. This is unhelpful for people considering Storefront as the demo site does not show the potential of the theme.

Same result when accessing the live demo from this screen:

https://wordpress.com/theme/storefront/

#### Screenshot / Video

![Screen+Recording+2019-11-18+at+10 27 14 87+AM](https://user-images.githubusercontent.com/1398304/105103286-3017e080-5a65-11eb-8a14-a1fffb51a080.gif)

#### Context / Source

Seen during #2499500-zen

**Comment by obenland** [comment]
Storefront does not seem to be available on wordpress.com/themes anymore.

**Comment by donalirl** [comment]
@obenland Did you have WooCommerce installed on the site? I can still very much recreate the issue. Can you try:

1. Installing Woo
2. Go to My Site → Design → Themes  and scroll down below the 'recommended' themes to click the 'show all themes' option

Screen recording:


https://user-images.githubusercontent.com/1398304/111550686-d74e8680-873b-11eb-8c30-9e6c87044ec4.mp4

**Comment by obenland** [comment]
@jeffikus Could this be fixed by setting up a theme demo site for Storefront?

**Comment by ianstewart** [comment]
That seems like the simplest fix. Or finding an existing one at least and linking to it.

**Comment by sixhours** [comment]
Investigated this this morning. Right now, the Theme Showcase treats Storefront like it would a WP.org theme, pulling the [automated theme demo URL](http://wp-themes.com/storefront) from the WP.org API.

I see a couple avenues for fixing this:

* We've talked about adding Storefront as a free theme to the `/pub` repo, and that would solve this problem, because then we can set up a custom demo site at http://storefrontdemo.wordpress.com like we would for any WP.com theme.
* Alternatively, we can hack the Showcase to show a specific demo URL for Storefront. This might be a good temporary solution if getting Storefront to `/pub` is not an option.

@ianstewart What do you think?

**Comment by ianstewart** [comment]
> we can hack the Showcase to show a specific demo URL for Storefront. This might be a good temporary solution if getting Storefront to /pub is not an option.

This seems like the best case for now for the themes we intend to promote on the Ecommerce Plan. (Not sure how it works for other "installed" themes— is it broken for them as well?)

**Comment by sixhours** [comment]
> (Not sure how it works for other "installed" themes— is it broken for them as well?)

Yep. If it's not properly in the themes repo, it's considered an outside/WP.org theme and will pull the data from that API.

**Comment by ianstewart** [comment]
> Yep.

Fun. Let's fix this for Storefront and then make sure that's tracked for all installed themes. (Likely a "later" task for us, right now.)

**Comment by sixhours** [comment]
There is no tracking on that "Open Live Demo" button, so I've added an issue to track it in #53312
