### ISSUE TITLE
Add prominent “Skip” buttons on plans and domains in sign-up.

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37659]
If a customer isn’t ready to commit, we should still let them through to see if we can show value as they build their site.

This will give us some data and satisfy the spirit of “Starting for free”. (See Free option above. We will need to exclude a “free plan” option when a domain is selected.

This change should be included in user tests, but should be A/B tested before being launched.

Domains screen:
<img width="1617" alt="Screen Shot 2019-11-17 at 9 53 37 PM" src="https://user-images.githubusercontent.com/1464705/69027789-e9bc8280-0984-11ea-8872-4bf10fb8e7a8.png">

Plans Screen:
<img width="1466" alt="Screen Shot 2019-11-17 at 9 53 49 PM" src="https://user-images.githubusercontent.com/1464705/69027801-f0e39080-0984-11ea-88f3-dee4d2737dad.png">

**Comment by adamziel** [comment]
> but should be A/B tested before being launched.

We've already A/B tested a very similar change - this would need to happen in tandem with some changes in the checklist/customer home/launch flow. Nothing blocking for the user test though.

**Comment by michaeldcain** [comment]
@apeatling: the best way to have this ready for user testing without waiting for the AB would be to put it in a Signup flow only used for user testing. I've started a PR for this over in #37565.

**Comment by apeatling** [comment]
Thanks!

**Comment by apeatling** [comment]
@michaeldcain How does that jive with this? https://github.com/Automattic/wp-calypso/issues/37690

**Comment by michaeldcain** [comment]
@apeatling: should we just merge the steps into the `test-fse` Signup flow and use that flow for the user test?

**Comment by donlair** [comment]
We're tackling something similar with [#37554 ](https://github.com/Automattic/wp-calypso/pull/37554). Hoping to launch a first test this week.

The difference is that we're presenting a Skip option that keeps them on the paid pathway by offering a domain credit. [Additional context here](https://marketingtestingp2.wordpress.com/2019/11/07/squad-2-quick-win-test-1-additional-context-on-the-domain-step-in-signup/#comment-2721).

**Comment by apeatling** [comment]
@donlair I think we can test that one separately. Cain tells me he's working on this one, so assigning him.
