### ISSUE TITLE
Switch from 'Scheduled post' to 'Publish' is not intuitive

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#37656]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post
2. Click on publish date and select date in the future
3. Then try and publish immediately instead

#### What I expected

There's should be a quick way to choose 'now' on the calendar, or otherwise there's a simple option revert my choice to schedule the post and publish it straight away.

#### What happened instead

The only way to reverse my choice seems to be by entering the date now (or in the past) to force the post to publish.

#### Screenshot / Video

<img width="390" alt="Screen Shot 2019-11-18 at 11 17 07" src="https://user-images.githubusercontent.com/17325/69015073-5707fc00-09f5-11ea-80e2-13422a19849d.png">

#### Context / Source

A WordPress.com user shared in 2499384-zen:

"I need to take a post off of a schedule module and I don't know how to put it
back to 'publish immediately'"

**Comment by ctoynbee** [comment]
@bluefuton I can see since you created this issue the UI has changed slightly:

https://www.dropbox.com/s/gtm3uof5jk2o06e/37656.mov?dl=0

There is now a "reset" link in the bottom left of the date picker.

Would you say this is satisfactory?

If not, what UI changes would you make?

**Comment by bluefuton** [comment]
Thanks for highlighting the new reset link @ctoynbee!

I'd say that solves the problem I reported 👍
