### ISSUE TITLE
CoBlocks: Pricing Table uses $ symbol

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#37650]
When editing the Pricing Table block, the currency symbol $ shows beside the price. This was user reported, because the user wanted to use the pounds symbol instead of $. I realized upon testing that the $ doesn’t show on the live site, but is a prompt for the user to enter a price.

In editor: 
![in editor](https://cld.wthms.co/q6qrS8+)

On live site:
![live site](https://cld.wthms.co/SgTphD+)

Could we use a currency selector or use words instead of $ to indicate where the price should go.

**Comment by WunderBart** [comment]
This seems to be resolved with the recent update (https://github.com/Automattic/wp-calypso/issues/45033). The `$` symbol is now editable and renders correctly in the front-end.
