### ISSUE TITLE
Checkout: different currency formatting for credits

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#37662]
#### Steps to reproduce
1. Add some credits to your account (internal users only)
2. Add a product to your cart (such as a new domain) and visit https://wordpress.com/checkout

#### What I expected

Credits and product price would be formatted in the same way, with a currency symbol (e.g. £15).

#### What happened instead

Credits balance is shown as "10 GBP" and other amounts show as "£10".

#### Screenshot / Video

<img width="688" alt="Screen Shot 2019-11-18 at 17 02 14" src="https://user-images.githubusercontent.com/17325/69023989-b978f080-0a25-11ea-8309-6cd5785b45da.png">

#### Context / Source

Discovered debugging an unrelated issue during support rotation.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
This is fixed in the new Checkout flow. Closing.

<img width="571" alt="Screen Shot 2020-07-19 at 10 29 15 AM" src="https://user-images.githubusercontent.com/942359/87877173-c41bc900-c9aa-11ea-9878-c6df37469df8.png">
