### ISSUE TITLE
Enforce Storage Limit on Simple sites with the Business plan

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#37660]
It seems like the [200GB storage limit](https://en.support.wordpress.com/plan-features/#wordpress-com-business) is not enforced on a Simple site with the Business plan, hence, when it's beyond the limit, a warning gets triggered when the user wants to install a plugin or theme:

> Upload not available: This site is not currently eligible to install themes and plugins. Please contact our support team for help.

![slack-imgs com](https://user-images.githubusercontent.com/15944096/69021928-794d4a00-09f4-11ea-8f58-0be1263e9ceb.png)

@iamgabrielma @katiebethbrown 

Chat: 16595841-hc

**Comment by CompChris** [comment]
Had the same problem with another site. Site is unable to add plugins as it has gone beyond that limit. Luckily, issue the user was having was worked around with another feature.

Chat: 15698318-hc

**Comment by obenland** [comment]
Closing in favor of #58041.

/cc @mreishus
