### ISSUE TITLE
Jetpack Inline connection flow: Create an account flow takes customer out of flow

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#37677]
#### Steps to reproduce
1. Spin up a new Jurassic ninja site w/ jetpack. Make sure you're logged out of wordpress.com
2. Navigate to "Jetpack" in the sidebar
3. Click "Connect using wordpress.com"
4. A log in pop-up window should display. Click "create a new account"
5. Actually create a new account using a new email.
6. Once you input your new account details a wordpress.com screen loads in the pop-up window, saying that the account hasn't been activated yet
7. You then have to navigate to your email to confirm the account. The link in the email will take you to the reader, not back to Jetpack.

#### What I expected

To not have to activate my account and to stay within wp-admin

#### What happened instead

Taken to the reader inside calypso

#### Browser / OS version

Latest mac OS, latest chrome

#### Screenshot / Video

Video shared in slack and p2. Here are some sequential screenshots:

![Screen Shot 2019-11-18 at 10 30 46 AM](https://user-images.githubusercontent.com/214813/69066156-dc3be280-09ee-11ea-9994-40f028497bbd.png)

![Screen Shot 2019-11-18 at 10 30 53 AM](https://user-images.githubusercontent.com/214813/69066169-e0680000-09ee-11ea-897e-2b8bf0179b16.png)

![Screen Shot 2019-11-18 at 10 31 00 AM](https://user-images.githubusercontent.com/214813/69066240-f4136680-09ee-11ea-99f2-3ebecd89aa99.png)

![Screen Shot 2019-11-18 at 10 31 38 AM](https://user-images.githubusercontent.com/214813/69066250-f7a6ed80-09ee-11ea-9890-2c88b8300b21.png)

![Screen Shot 2019-11-18 at 10 31 54 AM](https://user-images.githubusercontent.com/214813/69066267-fbd30b00-09ee-11ea-934b-cf5dfcc48fa3.png)

**Comment by tyxla** [comment]
This is expected, and going to happen only for automattic.com emails, so it's fine for all others. Closing.

**Comment by jeffgolenski** [comment]
Thanks for the quick explanation Marin!
