### ISSUE TITLE
me/purchases shows different content after viewing a specific purchase

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#37671]
#### Steps to reproduce
1. Start at `me/purchases` for a user who has at least one domain registration purchase.
2. Click on the row for a domain registration.
3. Click on the "Back" link in the top left corner.

#### What I expected
The same set of items to be listed after clicking back.

#### What happened instead
I saw additional rows added to the table that look like they may be domain mapping entries for the site. I did not see an additional request to the server, so I *think* this is all happening client-side.

#### Browser / OS version
MacOS 10.15.1 Catalina 
Chrome 78.0.3904.97 (Official Build) (64-bit)
Firefox 70.0.1 (64-bit)

#### Screenshot / Video
Initial display:
![single_domain_purchases](https://user-images.githubusercontent.com/3376401/69059904-1c1abe00-0a1f-11ea-8a96-800bdb57b8dc.png)
Display after clicking "Back":
![duplicated_domain_purchases](https://user-images.githubusercontent.com/3376401/69059959-35236f00-0a1f-11ea-850b-7134606a100a.png)

#### Context / Source
Working on testing for a PR related to displaying renewal information in the shopping cart.

#dogfooding #manual-testing

**Comment by daledupreez** [comment]
As an additional information, some of the discrepancy may be stemming from the fact that we're retrieving the data from the state in `connect()`, and the page for listing all purchases is calling `/rest/v1.1/me/purchases`, while the UI for managing a specific purchase for a site is calling `/rest/v1.1/sites/166057264/purchases`. The second API returns additional purchase rows, but after moving into the second context, there is an increase in the number of overall purchases returned to the UI component.

**Comment by DavidRothstein** [comment]
This should be fixed by D35702-code.

You are correct about the fundamental reason -- Calypso sort of switches back and forth between using data from the two API endpoints.  This used to be a rare bug, but something must have changed recently to make it use the data from the site-specific endpoint more often on the Manage Purchases page.  That is the endpoint that was returning data with an incorrect list of domain subscriptions.  So fixing the endpoint should fix the bug.

**Comment by damiannep** [comment]
I've come across this several times as posted here - https://github.com/Automattic/wp-calypso/issues/32094

A colleague also shared a similar case here from today - https://files.slack.com/files-pri/T024FN1V2-FQD3QAUHG/image.png

**Comment by klimeryk** [comment]
Patch reviewed and merged - I went ahead an deployed it to stop the stream of issues ASAP. Thanks, David, for providing a fix for it so quickly! 🙇
