### ISSUE TITLE
Plugin updates: Gutenberg 7.0.0 / CoBlocks 1.17.3

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37684]
The Gutenberg 7.0 plugin is set to be released on Nov 27th, with a chance of an earlier release! Let's help test in advance and see if this is stable for WordPress.com.

The Navigation block is expected to land, so do remember to ping @Automattic/ajax and @Automattic/cylon for call for testing.

Let's also updated CoBlocks to 1.17.3

- [x] Install Gutenberg `7.0.0-alpha`: D35698-code
- [x] Activate Gutenberg `7.0.0-alpha` on Horizon: D35700-code
- [x] call for testing: p7DVsv-7Ks-p2
- [x] Install CoBlocks `1.17.3`: D35871-code / D36076-code
- [x] Activate CoBlocks `1.17.3` on Horizon: D35872-code
- [x] Install Gutenberg `7.0.0-rc1`: D35917
- [x] Activate Gutenberg `7.0.0-rc1` on Horizon: D35918-code
- [x] Install Gutenberg `7.0.0`: D3640-code
- [x] Activate Gutenberg `7.0.0` on Horizon: D3641-code
- [x] e2e tests PR: https://github.com/Automattic/wp-calypso/pull/37807
- [x] Activate Gutenberg `7.0.0` on prod: D36045-code
- [x] Request update for AT sites:  pMz3w-aMD-p2
- [x] Activate CoBlocks `1.17.3` on prod: D36064-code

**Comment by mmtr** [comment]
Seems the lightbox effect for the CoBlocks galleries is not working. It’s always showing the first image.

I noted with a quick debug that is caused by the srcset attribute not being updated when changing the active image.

Possible fix: D36079-code

**Comment by mmtr** [comment]
Gutenberg 7.0.0 and CoBlocks 1.17.3 is now live on production.
