### ISSUE TITLE
YouTube URL doesn't play from the specified start time

### ISSUE THREAD

**Issue by wesinator** [Automattic/wp-calypso#37699]
#### Steps to reproduce
https://wordpress.com/post/
1. new post, add YouTube video from URL with a start time parameter, e.g. `https://youtu.be/gwfCO_1pxl0?t=180`

#### What I expected
YouTube video embed in post plays at time specified in URL

#### What happened instead
YouTube video always plays from beginning

#### Browser / OS version
Firefox 70.0.1

**Comment by formosattic** [comment]
Issue is raised in the main Gutenberg repo at WordPress/gutenberg#9678

At WordPress.com, there's a workaround using the [YouTube shortcode](https://en.support.wordpress.com/videos/youtube/#video-customization-options).

Although, the shortcode doesn't seem to like the `?t` in the URL, so make sure it's `?start` instead.

Using a Shortcode block with `[youtube https://youtu.be/gwfCO_1pxl0?start=180]` shall do the trick.

**Comment by davipontesblog** [comment]
Closing this one in favor of https://github.com/WordPress/gutenberg/issues/9678.
