### ISSUE TITLE
Stats: Sometimes counts for files are displayed in the "Posts & Pages" card 

### ISSUE THREAD

**Issue by aisajib** [Automattic/wp-calypso#37717]
We've got a report that counts for files started to show up in the Posts & Pages section. I along with the HEs that have tested was unable to reproduce this on our test sites. For folks investigating please confirm expected behavior and look more deeply into the affected site. 

#### Steps to reproduce
We're unable to reproduce this on our test sites.

#### What I expected
The "Posts & Pages" card/section on the stats page should not include the direct links to the image files (not attachment pages, but the direct files). 

#### What happened instead
This user's site was showing the stats for the direct image files. 

#### Context / Source
#user-report
#11836700-hc

**Comment by chaitanyamsv** [comment]
Also, The Views counts don't match between the Daily `Posts & Pages` view and the `View All` view.

In the https://d.pr/i/CwBIXU screenshot, for January 22, the day view (if you click the day bar in the main graph for January 22) shows, `MUN_8316` image has 82 views, but if you click on the `View All` link below the Posts & Pages section, the highly viewed image is `MUN_6515` with 8 views as shown in this screenshot: https://d.pr/i/b4HR2U

**Comment by kriskarkoski** [comment]
Is this a dupe of https://github.com/Automattic/wp-calypso/issues/32642?

**Comment by annacmc** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/32642
