### ISSUE TITLE
Free plan offers backup upgrade prompt to users who just purchased Jetpack Backup

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#37737]
#### Steps to reproduce
1. Buy a Jetpack Backup solution during connection
2. You will be taken to `https://wordpress.com/plans/my-plan/[site-url]`
3. See "Jetpack Free" under "My Plan" with an "Upgrade Plans" prompt that suggests getting backups

#### What I expected

Some confirmation that I have backups, since I just purchased them

#### What happened instead

A lot of unrelated and incorrect information, including a prompt to upgrade to get backups

#### Browser / OS version

All of them

#### Screenshot / Video

<img width="1086" alt="jetpack-free-upgrade-prompt" src="https://user-images.githubusercontent.com/51896/69188104-bd158180-0ad0-11ea-911e-48e3ad871cae.png">

**Comment by seear** [comment]
The updated flow is designed: p6TEKc-3bS-p2. Asana board linked from a comment on that post.

These tasks are in progress but we can't go fast on it until the back-end work is polished off.

**Comment by delawski** [comment]
The "My Plan" page is going to include the products section once #37727 is reviewed and merged like this:

![Screenshot 2019-11-19 at 18 14 50](https://user-images.githubusercontent.com/478735/69221069-ae81a580-0b76-11ea-8b22-d5d43acc5287.png)

It doesn't alter, though, the copy that's displayed below the free plan title.

**Comment by delawski** [comment]
The copy below the Free plan title is updated in the following PR: #37997
