### ISSUE TITLE
Template selector shows no margin for some templates, looks broken

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#37761]
A picture is worth a thousand words:

<img width="1385" alt="69153514-abd37180-0ade-11ea-9ced-b951224a4c40" src="https://user-images.githubusercontent.com/205419/69240167-2e6e3680-0b9c-11ea-8a74-9c60405ed20c.png">

Previously reported here: https://github.com/Automattic/wp-calypso/pull/37458#issuecomment-555523978

**Comment by Copons** [comment]
Closing this because already tracked by #37742 🙂
