### ISSUE TITLE
Build more page layouts

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37782]
We need more page layouts:

1. Alternative layouts for existing goals: About, Contact, Portfolio, Services, Team, Blog, Menu
2. New goal based page layouts, some rough examples:, Events, Products, Bookings, Social Accounts, Videos, Photo Gallery.

Lets build many of these, and we'll handle the updating of the layout selector in a separate issue.

Replaces: #35062

**Comment by michaeldcain** [comment]
@iamtakashi has already started some work on alternative portfolio/gallery designs. 

Given that they're designed inside Gutenberg on WPcom, using launched blocks, we could open up the process to other designers too.

**Comment by apeatling** [comment]
Awesome, let's use this as a top level issue and link to any work on any templates that is happening.

**Comment by apeatling** [comment]
@iamtakashi Assigning you on this one to keep it up to date with your latest work on the Portfolio alternative layouts, and anything beyond that.

**Comment by iamtakashi** [comment]
![Artboard](https://user-images.githubusercontent.com/908665/69478082-12f66c00-0de6-11ea-8011-9aecb318a6ed.jpg)

Here are the new portfolio/gallery page layouts that I've been working on. You can see them live here: https://iamtakashinuxtest2019112113719.wordpress.com/

@apeatling One thing to note. I've been using Tinker's Layout Grid block for those layouts as it works nicely to make various layouts without CSS. But the block is only available in Simple site at the moment. I've heard that it's going to be available in Atomic soon p7DVsv-7Dw-p2, but we want to make sure that's happening as the plan.

**Comment by apeatling** [comment]
@iamtakashi I've pinged @mkaz about this. It's a standalone plugin that we'd need to enable on Atomic, this should not be too tough.

**Comment by olaolusoga** [comment]
It'd be great to fill out the gaps around the alternative layouts for existing goals next, so: 
- About
- Contact
- Services
- Team
- Blog
- Menu (header/footer layouts)

Then move on to the new goal based page layouts: Events, Products, Bookings, Social Accounts, Videos, Photo Gallery. The goal based layouts will be very interesting, I'm assuming we may not have blocks for a lot of these, so  it'd be great to us the layouts to inform the products we'll need to build out—ex: does a product blocks use WooCommerce? If so, what block? How do we set up WooCommerce, and do all the things needed to where all a user needed to do is add the product details.

**Comment by iamtakashi** [comment]
> Could we do the same for blogging templates with the newspack block?

@apeatling When would the block be available in a Simple site? Working on layouts on a simple site makes the process easier than working on a local install as there wouldn't be surprises from the differences between WP.com and my local install in terms of available blocks or the editor itself. I don't expect that I need a lot of time to create a few blog layouts once it's available.

I can make a few about page layouts in the meantime as it's one of the popular pages for a site to have.

> it'd be great to us the layouts to inform the products we'll need to build out

@olaolusoga Yes. We need to take a good balance between making shippable layouts and exploring layouts to inform the product what we need. And having a tight feedback loop between designers and engineers is important as the process of making layouts uncovers bugs and needs in blocks/themes.

**Comment by apeatling** [comment]
> When would the block be available in a Simple site?

Ajax are actively working on this, there have been some hurdles like paYJgx-jW-p2 but it's moving. The goal of the current sprint is to get it available in the FSE plugin. That means it should be on simple sites next week sometime if that deadline is met and the plugin is synced to simple sites. /cc @obenland

**Comment by olaolusoga** [comment]
If we introduce header/footer layouts in the next experience sprint, do we have enough header layouts for folks to select? If not, focusing on that would be helpful.

**Comment by apeatling** [comment]
We should gain at least a handful from the FSE theme conversion work.

**Comment by apeatling** [comment]
@iamtakashi This is percentage occurrence of template selection in the last 14 days, I think it would be good to use this to prioritize:

<img width="374" alt="Screen Shot 2019-11-27 at 1 12 51 PM" src="https://user-images.githubusercontent.com/1464705/69760014-47389800-1118-11ea-9144-2deda37f4c88.png">

This reinforces the importance of good blog templates. What about using an Atomic site and installing the Newspack block there? It would allow you to get a week or two ahead of that block landing.

**Comment by ianstewart** [comment]
+1 on prioritizing more blog templates.

And, in addition to more "pure" blog templates. More home page templates that have recent posts on them. Whether that's something that looks like a "magazine" or "portal" or something that looks like the home page of popular "pro bloggers" (my favourite example is always Pioneer Woman but there are many more examples) or the homepage of a Business that wants to showcase recent blog posts. 

We can use these in signup to help people get started with the type of site they want.

**Comment by iamtakashi** [comment]
I'm going to wrap up about page layouts at the end of this week, and I can start making blog layouts from next week using a new Atomic site.

**Comment by iamtakashi** [comment]
![about page layouts](https://user-images.githubusercontent.com/908665/69874639-6881bb80-12b3-11ea-8d26-58c9c5e40c3b.png)

Here is the new about page layouts that I've worked on. You can see them live here: iamtakashinuxtest20191125111820.wordpress.com (btw, this is a different site from the one with the portfolio layouts).

The page title ruins the look. This is another thing that the user can't control yet, and we've seen it's confusing the users in some usability testing. Could we help core to move these forward?

* https://github.com/WordPress/gutenberg/issues/16776
* https://github.com/WordPress/gutenberg/issues/11553

**Comment by apeatling** [comment]
@iamtakashi Great work! The post title block is now in the plugin under an experimental flag. https://github.com/WordPress/gutenberg/pull/18461

I've added a task to the backlog to investigate how we could enable this on WordPress.com.

**Comment by iamtakashi** [comment]
@apeatling OK, thanks for the info.

**Comment by iamtakashi** [comment]
While I was playing around the Newspack block, I quickly put together some simple product(s) page layouts. Since Simple Payments block is rigid in terms of layout, I kept them simple for now until we have V2. You can view live here: https://iamtakashinuxtest20191204103359.wordpress.com/

![products](https://user-images.githubusercontent.com/908665/70167941-b46f9e80-16bf-11ea-82a8-8a74b32f5ea2.jpg)

**Comment by iamtakashi** [comment]
Event page layouts for when Eventbrite block is ready.

![event copy2](https://user-images.githubusercontent.com/908665/70723001-1d729a00-1cf0-11ea-9827-9cdc1fdaece0.jpg)

cc @huguesvincent We can keep making more layouts and adjust the verticals based on event sub-vertical data if we have.

**Comment by apeatling** [comment]
We need to get these into the template selector, but need to redesign the template selector first of all. That should be a high priority in Jan when everyone is back.

**Comment by mtias** [comment]
These are looking nice!

**Comment by getdave** [comment]
> need to redesign the template selector first of all

I agree! Do we have insight into what our users are struggling within the Template Selector? With the current choices and design, as a user, I'm finding it to be increasingly confusing as to what I'm actually supposed to be choosing. Is it a Theme? Is it just a collection of predefined Blocks? Will the design of my site (eg: color scheme, fonts...etc) change when I select one of these? 

Another (known) the issue is also the discrepancy between the thumbnail _previews_ and how they will appear in the current Theme. I'd like to see how this plays with users when they come to select a template.

Looking forward to tackling this.

**Comment by WunderBart** [comment]
> I agree! Do we have insight into what our users are struggling within the Template Selector? With the current choices and design, as a user, I'm finding it to be increasingly confusing as to what I'm actually supposed to be choosing. Is it a Theme? Is it just a collection of predefined Blocks? Will the design of my site (eg: color scheme, fonts...etc) change when I select one of these?

> Another (known) the issue is also the discrepancy between the thumbnail previews and how they will appear in the current Theme. I'd like to see how this plays with users when they come to select a template.

There has been some discussion on this matter happening here: https://github.com/Automattic/wp-calypso/issues/37742.

**Comment by iamtakashi** [comment]
> need to redesign the template selector first of all

It's worth keeping an eye on the related work happening in core: https://github.com/WordPress/gutenberg/issues/17335

**Comment by gracie** [comment]
We find people setting up a site for a physical business is one of the top items in quick start sessions. It would be super helpful to have a template for these that includes:
- phone number (clickable on mobile)
- email address (clickable)
- Coblocks Map
- Who we are section
- What we do section

**Comment by iamtakashi** [comment]
@alaczek and I collaborated on some Services page layouts.

![services](https://user-images.githubusercontent.com/908665/72727643-5c173200-3b83-11ea-8e6e-ccb8ce2cf9d3.png)

**Comment by marekhrabe** [comment]
We seem to have much better selection now. Still relevant to keep this issue opened?

**Comment by obenland** [comment]
@iamtakashi What's the status of translations on these?

**Comment by iamtakashi** [comment]
> @iamtakashi What's the status of translations on these?

I'm not sure. @apeatling has added the last batch.

**Comment by ianstewart** [comment]
I was reviewing translations on the front-end yesterday in Canadian French and Espanol — everything looked good. Are all translations fully deployed for Mag 16?

**Comment by ianstewart** [comment]
I have a correction to the above …

**WP.com Test Site Settings**

Site Language Settings

![image](https://user-images.githubusercontent.com/545779/75922064-e9f36780-5e27-11ea-9350-d95648883b81.png)

UI Language Settings

![image](https://user-images.githubusercontent.com/545779/75922012-cf20f300-5e27-11ea-8711-64e046812aca.png)

**Result**

![image](https://user-images.githubusercontent.com/545779/75922100-fa0b4700-5e27-11ea-8c8e-a983dd4320b2.png)

**Comment by ianstewart** [comment]
What needs to be done to correct the above?

**Comment by obenland** [comment]
The updated template annotation will need to be sent out for translations as described in pbFcYn-1A-p2. Once translated, they'll ping with deploy instructions, IIRC

**Comment by obenland** [comment]
It's worth noting that there are a number of themes that are missing their headstart translations, leading to their homepage templates not being returned in the template response. Those require separate translation requests.

**Comment by michaeldcain** [comment]
I believe that the remainder of template-first themes were submitted for translation a couple of months ago - I wonder if the deployment email was missed. @Automattic/i18n might be able to help us track them down.

**Comment by emilyaudela** [comment]
Yes, they were translated! There were a handful translated last year and the rest translated at the beginning of this year. It looks like the only theme that is showing up translated is Rivington. Here are the strand IDs:

Rockfield: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50945
Brompton: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50947
Leven: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50948
Hever: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50949
Stow: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50950
Coutoire: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50951
Morden: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50952
Stratford: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50953
Exford: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50954
Alves: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50955
Rivington: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50956
Maywood: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50957
Balasana: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50958
Shawburn: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50959
Mayland: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50960
Barnsbury: https://mc.a8c.com/i18n/linguine/inspect.php?strand=50961
Redhill: https://mc.a8c.com/i18n/linguine/inspect.php?strand=46506
Dalston: https://mc.a8c.com/i18n/linguine/inspect.php?strand=49457

**Comment by alaczek** [comment]
Good to know. I went through all the themes in open grok, and found only a handful has translations deployed though: Dalston, Rivington, Stratford, Coutoire, Leven and Redhill. But then I went to see each strand in mc, and in many cases it said some of the languages were already deployed (but I could not see those files when viewing via open grok).

I also tried running the translation command for non-homepage layouts, and looks like the en.json file got too big (275.3 KiB). Error:
`>>> Error: Headstart File Processor (validate_file): File must be non-empty and smaller than 80000 bytes.`

**Comment by AtrumGeost** [comment]
Hi @ianstewart  and everyone!

We previously talked about the issue with the Page Layouts described above. I can see more Page Layouts are being displayed now. Thank you!

I just noticed a bug that might (or might not) be related to this.

When you activate one of these themes on a site with the Spanish interface:

- Maywood
- Balasana
- Shawburn
- Twenty Twenty

The correct Home Page Layout won't be loaded. The user will get a Blog Page Layout like this one:

![Screen Shot 2020-05-19 at 07 51 24](https://user-images.githubusercontent.com/3696121/82328524-9fed3d00-99a5-11ea-83cc-62c4ef0acdf9.png)

A quick way to reproduce this bug is by trying to change the page layout:

![Screen Capture on 2020-05-19 at 08-05-36](https://user-images.githubusercontent.com/3696121/82329943-ba281a80-99a7-11ea-8d89-971f432b42fc.gif)

Please, let me know if my report here is ok. Otherwise, I can open a new GH issue :)

**Comment by iamtakashi** [comment]
I've also noticed that issue above while I was working on #41364. It looks like the homepage layouts that are without translations fallback to the default.

Also, some blocks are broken on the layouts that have been translated as well. I'll test all of them in all of Mag16 and create an issue for it to track.

**Comment by ahmadbaig1** [comment]
Noticed the layout issue here as well 3122767-ZD for the Japanese language for Shawburn theme page layout.
In fact, the user was seeing Jetpack error code on Shawburn layout after the header. Could not replicate on my test site.

**Comment by AtrumGeost** [comment]
Hi @ianstewart and @iamtakashi!
Do you have any news [about the issue I mentioned above](https://github.com/Automattic/wp-calypso/issues/37782#issuecomment-630805327)?

With the introduction of the screen that asks the user if they want to keep their homepage or use the theme's one (which is very cool), this issue is more obvious to users. We have also noticed this issue is showing up on new themes like Seedlet.

If this is a translations issue, we could talk with the i18n team so they can help us :) (Also, please let me know if I need to create a new issue since this one is already closed)

As a reference, here's a recent report from one of our HCs:

pbEMJv-fh-p2

**Comment by ianstewart** [comment]
@AtrumGeost I don't have any news but I'll start digging in.

**Comment by AtrumGeost** [comment]
Hey @ianstewart. Thank you :)

**Comment by noahtallen** [comment]
> We have also noticed this issue is showing up on new themes like Seedlet

This makes sense, as seedlet doesn't have any translations yet. (They are in progress though!)

However, this is obviously buggy behavior for themes which don't have translations yet, so it should still be fixed. I'm working on something right now. I've narrowed down the cause of the default content, just have to test that the whole flow will work correctly if we stop returning the default content.

**Comment by noahtallen** [comment]
But yeah, to sum up, there are no headstart annotation translations at all for any of these themes:

- [ ] Maywood
- [ ] Balasana
- [ ] Shawburn
- [ ] Twenty Twenty
- [ ] seedlet

The other suggested themes do have translations.

**Comment by noahtallen** [comment]
@AtrumGeost @ianstewart I created a new issue for this here: #46662
