### ISSUE TITLE
FSE: add support for Hever theme

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#37792]
Part of our effort to add FSE support to all of the template-first themes. For reference you can check how this has been done for Exford and Shawburn already.

https://github.com/Automattic/themes/pull/1649
https://github.com/Automattic/themes/pull/1650

**Comment by apeatling** [comment]
It's not possible to support this theme until we can align navigation links to the right. One option would be to force this using theme CSS is the short term.

**Comment by apeatling** [comment]
PR for review here https://github.com/Automattic/themes/pull/1690

**Comment by vindl** [comment]
This theme update has been released to production.
