### ISSUE TITLE
FSE: add support for Morden theme

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#37795]
Part of our effort to add FSE support to all of the template-first themes. For reference you can check how this has been done for Exford and Shawburn already.

https://github.com/Automattic/themes/pull/1649
https://github.com/Automattic/themes/pull/1650

**Comment by apeatling** [comment]
PR for review here: https://github.com/Automattic/themes/pull/1684

**Comment by Copons** [comment]
Morden merged!
Or is it Morded mergen?
