### ISSUE TITLE
Checklist: Improve "start/change" homepage button call to action

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37803]
The button on the checklist for editing your home page is either labeled "Start" or "Change" depending on whether the step is complete or not. Both of these are very generic call to actions, and I think we can be more specific.

Related to this, users are looking for the word "Edit" (we've seen this in multiple tests across different areas of calypso). The word "Change" does not seem to grab people the same way. "Start" is not immediately relevant to the actual action they are taking.

<img width="567" alt="Screen Shot 2019-11-20 at 1 14 09 PM" src="https://user-images.githubusercontent.com/1464705/69278817-e8af6f00-0b97-11ea-95a8-d60457320fb5.png">

<img width="565" alt="Screen Shot 2019-11-20 at 1 14 30 PM" src="https://user-images.githubusercontent.com/1464705/69278822-e9e09c00-0b97-11ea-8e47-5ace0fc5fa1e.png">

**Comment by lcollette** [comment]
@obi2020 Would love your guidance with this button copy. We recently changed it from "Try it" to "Start". Can you suggest an alternative button label for initiating a task? For "Change", would "Update" suffice?

**Comment by danhauk** [comment]
I think it would be better to make the CTAs specific to the task rather than trying to find something that works for everything:

* `Update homepage`
* `Create tagline`
* etc.

It does repeat some of the copy in the task title, but it helps to reinforce what the button does.

**Comment by sixhours** [comment]
Agreed on Dan's point. Descriptive labels also make for a more accessible experience.

**Comment by obi2020** [comment]
To build on Dan's suggestion and incorporate Andy's feedback from testing:

- `Edit homepage` on the button after the task is completed; and can we change the subheader, too? Something like
- `Edit your page anytime you want to change the text or images.`
