### ISSUE TITLE
Checklist on Home: Confusing subtitle after purchase

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#37805]
The subtitle on this post-purchase screen from the signup flow seems incorrect.

![image](https://user-images.githubusercontent.com/545779/69284730-e6a7d900-0bb4-11ea-8478-2a112e735e61.png)

Thank you for your purchase
Next, use this quick list of setup tasks to get it ready to share.

I expected:

A purchase-related subtitle, not a checklist-related one. :)

cc @sixhours

**Comment by sixhours** [comment]
Hmm /cc @obi2020 what do you think? I cribbed the subtitle from a suggestion you'd made in an earlier  Slack conversation about the checklist, but now that the checklist and Customer Home are the same, maybe we need to adjust the wording? Let me know and I can update everything.

**Comment by ianstewart** [comment]
It reads a bit like …

Thank you for your purchase
Next, use this quick list of setup tasks to get [your purchase] ready to share.

:)

**Comment by obi2020** [comment]
Would you mind sharing more of that screencap? It's difficult to know what's best without the broader context

**Comment by sixhours** [comment]
@obi2020 Absolutely, here you go: 

![screencapture-calypso-localhost-3000-home-calobeetesting48372812133-wordpress-com-2019-11-21-11_33_44](https://user-images.githubusercontent.com/2124984/69357311-dd6d4980-0c52-11ea-8cb7-7625f0b98b7a.png)

You get this screen on Customer Home after starting a new site from `wordpress.com/start` and purchasing a plan.

**Comment by gwwar** [comment]
Closing this as we no longer display this
