### ISSUE TITLE
Gutenboarding: have a clear way to get out from the flow if user is already signed in

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37815]
Imagine flow where the customer:

1. is logged in to WordPress.com
2. clicks site list and "add new site":
    <img width="200" alt="Screenshot 2019-11-21 at 10 05 14" src="https://user-images.githubusercontent.com/87168/69318776-924d3980-0c46-11ea-86f2-62368c2fe582.png">
3. Ends up in Gutenboarding flow:
    <img width="500" alt="Screenshot 2019-11-21 at 10 05 52" src="https://user-images.githubusercontent.com/87168/69318792-9bd6a180-0c46-11ea-9933-50708f167524.png">
4. Doesn't have way back anymore

We already have this back-arrow pattern in Gutenberg-on-wpcom so suppose we should re-use that:

<img width="230" alt="Screenshot 2019-11-21 at 10 49 01" src="https://user-images.githubusercontent.com/87168/69322019-c9264e00-0c4c-11ea-8997-fefb5fb7aece.png">

Maybe the W-logo should turn into that < arrow on focus/hover?

**Comment by simison** [comment]
@dwolfe I saw you had this actually in your designs:

![image](https://user-images.githubusercontent.com/87168/69410307-6481f680-0d13-11ea-9453-ae798fa12177.png)

Do you think we should change the current one in Calypso-Gutenberg to this new style, too? Should "back" word be there only initially and collapse to an arrow at some point?

**Comment by dwolfe** [comment]
That's a great question - this is all in flux at the moment. We may end up leaving the left side of the top bar as it is, and moving the title/domain elsewhere. Sorry I don't have better guidance around this right now, but we're actively working on this very piece, and hopefully next week I'll have a better response for you.

**Comment by simison** [comment]
@andrewserong has been looking into this at https://github.com/Automattic/wp-calypso/pull/38823 by making the initial back button functional if there's a signed-in user. UI might look different in the future but mechanics might be the same.

**Comment by simison** [comment]
W logo is now a way out in the header during onboarding, as well as good-'ol browser back button.
