### ISSUE TITLE
Reader: Accented characters and quotes do not appear as expected

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#37829]
#### Steps to reproduce

- Visit a feed on WordPress.com Reader. Here is the [Mashable feed](https://wordpress.com/read/feeds/9752470) as an example.
- Go through a few posts' titles. The ones with quotes in the titles, or accented characters in the titles do not appear as expected.

#### What I expected

<img width="1033" alt="Screenshot 2019-11-21 at 22 10 20" src="https://user-images.githubusercontent.com/18581859/69357880-eb02ed80-0cab-11ea-9ea1-11b7ba852851.png">

<img width="1035" alt="Screenshot 2019-11-21 at 20 48 04" src="https://user-images.githubusercontent.com/18581859/69357884-eb9b8400-0cab-11ea-8ec3-328586e2bca6.png">

#### What happened instead

<img width="735" alt="Screenshot 2019-11-21 at 22 10 15" src="https://user-images.githubusercontent.com/18581859/69357881-eb02ed80-0cab-11ea-8207-f8253f85cf94.png">

<img width="862" alt="Screenshot 2019-11-21 at 20 47 44" src="https://user-images.githubusercontent.com/18581859/69357885-ec341a80-0cab-11ea-9b71-9e8977d23159.png">

#### Browser / OS version

Safari 13.0.3 with Mac OS Catalina 10.15.1

#### Screenshot / Video

NA

**Comment by bluefuton** [comment]
This also happens for x-post titles:

<img width="325" alt="Screen Shot 2019-12-12 at 10 11 04" src="https://user-images.githubusercontent.com/17325/70733549-c6f16580-1cc7-11ea-8f43-cef4f4ab76c5.png">
