### ISSUE TITLE
FSE: Add Shawburn default template part content

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#37839]
On the main demo site, we need to make sure the default template part content for Shawburn looks like the demo site.

1. Activate the Shawburn theme on the demo site
2. Go to wp-admin/edit.php?post_type=wp_template_part on the demo site
3. Edit the header/footer and make sure it looks as much like the demo site's header/footer as possible.
4. Run the snapshot script for Shawburn on your sandbox (`bin/calypso/snapshot-fse-demo-data.php shawburn`)

Once this is done and #37434 is released to the public, sites will be able to use Shawburn for FSE.

**Comment by Copons** [comment]
I've just updated the Shawburn template parts to look as much as possible like the Shawburn demo site.
I haven't snapshotted them yet, though, as one of the #37434 test steps assumes that the template site doesn't have Shawburn snaphots yet.

**Comment by noahtallen** [comment]
I created the snapshot since we've now merged that PR.
