### ISSUE TITLE
Gutenboarding: focus on site title automatically

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37846]
We should automatically focus on site title input when appropriate at `/gutenboarding`.

When clicking on an already filled title:

![Screen Recording 2019-11-21 at 15 45 26](https://user-images.githubusercontent.com/87168/69405385-35b25300-0d08-11ea-8570-dee8c5e6a7d7.gif)

When choosing site vertical and then automatically getting to site title next up:

![Screen Recording 2019-11-21 at 16 02 10](https://user-images.githubusercontent.com/87168/69405376-30ed9f00-0d08-11ea-886d-8669f67b1b78.gif)

**Comment by sirreal** [comment]
I was working on this in https://github.com/Automattic/wp-calypso/pull/37613
