### ISSUE TITLE
Gutenboarding: don't persist data forever

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37849]
Currently, we persist entered data forever at `/gutenboarding` flow.

Live onboarding flow [persists for 7 days](https://github.com/Automattic/wp-calypso/blob/e86ef811a5b8473d0bbfd066b9d4d728b62a25ee/client/state/initial-state.js#L26).

Other situations where we might not want to persist:
- the user initially entered flow as logged-in, and then re-enters as logged-out. (<s>We'll need user object</s> we have user object now #37852 )
- the user is HE [on support session](https://github.com/Automattic/wp-calypso/blob/e86ef811a5b8473d0bbfd066b9d4d728b62a25ee/client/state/initial-state.js#L48)
- the user finishes the flow by creating a site
- the user adds `?fresh` param in the URL

**Comment by sirreal** [comment]
We'll need to either figure out how to do this with [the `persistence` plugin](https://github.com/WordPress/gutenberg/tree/master/packages/data/src/plugins/persistence) or roll our own.

**Comment by ramonjd** [comment]
As far as I know signup also defaults back to the 7 day `MAX_AGE` in the initial state.

Other areas we clear the signup progress state:

- [After a user has logged in](https://github.com/Automattic/wp-calypso/blob/master/client/signup/main.jsx#L345)\
- [if the cached progress contains a "processing" step](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/flow-controller.ts#L119)
- [if if user has newly authenticated](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/flow-controller.ts#L119)

To reset based on 'staleness', could we add a timestamp to `localStorage` and then introduce a check before retrieval? Similar to what we do for [Calypso storage](https://github.com/Automattic/wp-calypso/blob/master/client/state/initial-state.js#L101)?

**Comment by ramonjd** [comment]
> We'll need to either figure out how to do this with the persistence plugin or roll our own.

Maybe the dependency injection is there just to make testing easier, but, [looking at the tests](https://github.com/WordPress/gutenberg/blob/master/packages/data/src/plugins/persistence/test/index.js#L46), it may be possible to overwrite `getItem` with an 'enhanced' version via the `options` arg :)

See: https://github.com/WordPress/gutenberg/blob/master/packages/data/src/plugins/persistence/index.js#L67

Actually, it's probably not a fab idea now that I see they've added a fallback: https://github.com/WordPress/gutenberg/blob/master/packages/data/src/plugins/persistence/storage/default.js

**Comment by sirreal** [comment]
> See: https://github.com/WordPress/gutenberg/blob/master/packages/data/src/plugins/persistence/index.js#L67

Good spot! I hadn't seen that. It looks like what we need to add our own persistence layers and should let us customize how to store things, and for how long 🚀

**Comment by jeraldjuice** [comment]
@Addison-Stavlo I'm pickin' this one up 👍

**Comment by sirreal** [comment]
We'll likely want a mechanism to clear the persisted data as well, for example when we create a site.
