### ISSUE TITLE
Back button context is lost if you create a page/post

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#37841]
Similar to #37840, if you create a new page/post from customer home, the back button context is lost. This is because a full page reload is done, so we need to make sure that doesn't happen :)

**Comment by noahtallen** [comment]
@Automattic/serenity 

I see that @mmtr was the last person to touch the code I’m looking at, which is why I pinged (but others probably have ideas too.)

Basically, we navigate to `wordpress.com/post/$site_id`, instead of doing client-side navigation with `page`, we do a `window.location` change. The result is that we reload all of Calypso, loosing the navigation context in particular. This means we can’t go back to an arbitrary page which got us into the editor — instead we always go back to a hardcoded /posts page. I see this happening in a couple cases:

https://github.com/Automattic/wp-calypso/blob/23f80dcc63ff9b3c167df12db7550bef61772f74/client/post-editor/controller.js#L194

https://github.com/Automattic/wp-calypso/blob/23f80dcc63ff9b3c167df12db7550bef61772f74/client/gutenberg/editor/controller.js#L140

Is there a reason we do this instead of using page.js? And would there be any pitfalls to changing it to use the SPA navigation instead? Maybe it could even be conditionally based on the type of site we are navigating to if there are issues with jetpack/atomic.

**Comment by gwwar** [comment]
Reading https://github.com/Automattic/wp-calypso/commit/3a7349c9dffc82a41e89f20ed7db06a8f22a282a#diff-f132a0b1166ff56a85c37344eac23235L207

It's to account for Jetpack sites that may need a full redirect to wp-admin (say using a blacklisted plugin). Can probably add a check around host path for a page vs full redirect.

**Comment by noahtallen** [comment]
> that may need a full redirect to wp-admin

👍 That makes sense. I wanted to clarify because I see that the window.location was still used before that change

**Comment by noahtallen** [comment]
I have a PR which solves the bug here: https://github.com/Automattic/wp-calypso/pull/37844. Feedback on whether it will cause other bugs would be great!
