### ISSUE TITLE
Hosting: Do not create extra SFTP user if one already exists for a wpcom user

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37843]
To reproduce call the POST endpoint of `/hosting/ssh-user` multiple times. Let's return an error for this case.

**Comment by mmtr** [comment]
Fix: D35833-code

**Comment by gwwar** [comment]
Sorry might be worth pausing to see which approach we pick

**Comment by gwwar** [comment]
Fixed by #37891
