### ISSUE TITLE
Gutenboarding: show loading indicator when loading domains

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37848]
When typing in domain search, I'd expect to see some kind of loading/pulsing indicator when domain(s) are loading on slow connections (these will likely be mobile phones).

See the fast and slow comparison:

Fast

<img src="https://user-images.githubusercontent.com/87168/69406696-58923680-0d0b-11ea-8f5d-8660bf024453.gif" alt="" width="400">

Slow

<img src="https://user-images.githubusercontent.com/87168/69406685-4e703800-0d0b-11ea-8b51-99cd6f94e82a.gif" alt="" width="400">

Another similar situation is when customer changes their site name and we load another domain suggestion:

<img src="https://user-images.githubusercontent.com/87168/69411777-479af280-0d16-11ea-8f30-66f498c10bc7.gif" alt="" width="300">

Showing the old domain for a little while can be disorienting. I'd expect; old domain be grayed out to loading indicator and new one appear once it loads:

![image](https://user-images.githubusercontent.com/87168/69411934-9ea0c780-0d16-11ea-9c18-456094deb606.png)

cc @olesyabrk

**Comment by ockham** [comment]
:+1: 

Domain suggestions loading state is reflected by this selector: https://github.com/Automattic/wp-calypso/blob/4f4acfdb54c1bf675abe68d82b7516094fb79de0/client/landing/gutenboarding/stores/domain-suggestions/selectors.ts#L29

**Comment by simison** [comment]
`client/assets/stylesheets/shared/mixins/_placeholder.scss` mixin might be useful.

**Comment by olesyabrk** [comment]
Grayed out indicator looks good. One thing that I noticed that is a bit disorienting is how the width of the domain window resizes based on the text. Can we keep it fixed?

We can use skeleton screens to indicate the loading. 
![skeleton](https://user-images.githubusercontent.com/51215741/69448801-35b55180-0d0e-11ea-9607-d5e1bf0533ae.gif)
