### ISSUE TITLE
Gutenboarding: bring user object back

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37852]
We might need to detect if the customer is logged in for:

- Showing some kind of “go back” button in the header so that they can escape the flow? ([issue](https://github.com/Automattic/wp-calypso/issues/37815))
- Stored data should not persist from logged-in → logged-out sessions. ([issue](https://github.com/Automattic/wp-calypso/issues/37849))
- Customer’s locale should be respected ([issue](https://github.com/Automattic/wp-calypso/issues/37665))

Anything else?

**Comment by andrewserong** [comment]
Just jotting down that depending on how we want to [handle account creation](https://github.com/Automattic/wp-calypso/issues/37328), where we might use a temp account before sending the user to FSE, then the user object would be useful for an "is logged in" check `user.get()` before we create and log in to a temporary account.

**Comment by ramonjd** [comment]
Related PR https://github.com/Automattic/wp-calypso/pull/38823

**Comment by sirreal** [comment]
> Related PR [Add user store to packages/data-stores and use wpcom-proxy-request for API calls](https://github.com/Automattic/wp-calypso/pull/38823) #38823

👍 When that lands, we can start to use that for localization.

**Comment by sirreal** [comment]
We've got a user store now that #38823 has landed.

In development:

```
console.log( wp.data.select('automattic/user').getCurrentUser() )
```
