### ISSUE TITLE
Reader: Manage Following needs a better empty state

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#3785]
When you're Manage Following Sites page is empty, it's not clear what you should be doing. The search (followed sites) and sorting functionality are also still there when there's nothing to either search or sort:

![screenshot-2016-03-04-12 54 27-copy](https://cloud.githubusercontent.com/assets/4924246/13540204/e36b754a-e209-11e5-9256-ce1aebd942ef.jpg)

Copy isn't final, but something like this. I think we should also add a link to Support docs for more info: https://en.support.wordpress.com/reader/
![empty-state-001](https://cloud.githubusercontent.com/assets/4924246/13540471/911c8fca-e20b-11e5-8f6d-525a42c0556f.jpg)

On focus, I don't think we need the secondary label anymore, it seems redundant (is it there though as an actual placeholder for when you’re already typing something in?):
![empty-state-on-focus-001](https://cloud.githubusercontent.com/assets/4924246/13540560/2891d3a6-e20c-11e5-87eb-17bf1c3c035a.jpg)

No secondary label on focus:
![empty-state-on-focus-002](https://cloud.githubusercontent.com/assets/4924246/13540564/2e5921cc-e20c-11e5-9cc8-c60bbd5dcdc6.jpg)

As you're typing in a URL:
![empty-state-type001](https://cloud.githubusercontent.com/assets/4924246/13540605/5d5066f2-e20c-11e5-813a-5224f019d995.jpg)

/cc @blowery @bluefuton

**Comment by blowery** [comment]
Maybe an example URL or two? I'm not sure half the people in the world know what a URL is.

**Comment by jancavan** [comment]
Yeah, this is a good place to add recommendations as well.

**Comment by blowery** [comment]
Whatever we do, it should probably be mirrored to some extent on `/` too, if you have zero feeds.

**Comment by jancavan** [comment]
> Whatever we do, it should probably be mirrored to some extent on / too, if you have zero feeds.

That page links to recommendations and Discover. So we could have those 2 links as well with an added search. Thoughts?

**Comment by blowery** [comment]
sounds like a plan!

**Comment by jancavan** [comment]
Here's a mockup that includes a search bar and Discover/Recommendations buttons. Copy not final yet:

![empty-state-002](https://cloud.githubusercontent.com/assets/4924246/13543578/638561ca-e221-11e5-8636-4b4b3cbb2a4d.jpg)
