### ISSUE TITLE
Gutenboarding: small style tweaks to intent gathering step

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37853]
Sorry for multiple things in one issue, but these were so minor that I figured one PR will likely cover it. Happy to split to separate issues as well if needed.

1. Skip button needs focus/hover styles:
    <img src="https://user-images.githubusercontent.com/87168/69412337-5504ac80-0d17-11ea-96b7-0cc89c5eb04b.png" width="200">

2. "enter title" shouldn't look the same as a filled-in title:
    <img src="https://user-images.githubusercontent.com/87168/69412411-7bc2e300-0d17-11ea-968c-5c418d094e66.png" width="300">
    <img src="https://user-images.githubusercontent.com/87168/69412390-706fb780-0d17-11ea-9285-95724fbf4333.png" width="300">
   Maybe it should be greyed out and underlined? Is the text contrast of blue or grey without underline enough to indicate these are clickable?

3. Keyboard focus and mouse hover look different (upper is hover):
    <img src="https://user-images.githubusercontent.com/87168/69412517-b4fb5300-0d17-11ea-83df-503039b67a26.png" width="300">
    Not sure if this is expected, or should the keyboard hover actually be more substantial (like a border around the whole word instead of just changing the color of the understroke?)

4. Dropdown visuals likely need some tuning:
    <img src="https://user-images.githubusercontent.com/87168/69412615-f0961d00-0d17-11ea-915d-e726e74b2cb7.png" width="500">
   I'd at least hide the inputs grey border that's visible above the dropdown and doesn't match its width.

cc @dwolfe

**Comment by dwolfe** [comment]
1. Let's go with the an underlined blue link when the skip button is hovered:
![Screen Shot 2019-11-22 at 10 16 24 AM](https://user-images.githubusercontent.com/1348738/69450099-3996a300-0d11-11ea-9d99-575e6c7dd18e.png)

2. Placeholder text should be Grey 20 from https://color-studio.blog/
![Screen Shot 2019-11-22 at 10 17 55 AM](https://user-images.githubusercontent.com/1348738/69450237-9003e180-0d11-11ea-9f60-fd0ae5ddab96.png)

3 and 4 need some additional thought, will circle back on those later.
