### ISSUE TITLE
Gutenboarding: increase clickable domain area in header 

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37851]
Clickable area in the domain picker is currently only the domain:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/87168/69410442-be82bc00-0d13-11ea-9acd-7ac4fd4a3f23.png">

This can be scary because users might expect to end up to that URL by clicking that. Clickable area is also smaller like this — bigger the better!

It would be less scary if the whole thing is clickable and indicated so on mouse hover & keyboard-focus:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/87168/69410602-10c3dd00-0d14-11ea-8301-beec27736148.png">

Border wouldn't be visible when not hovering/focusing on the item.

The only caveat is that if the customer should be able to change the title by clicking it in the header? Should that happen directly in the header where there isn't a ton of space, or in the domains dropdown?

@olesyabrk thoughts on how this should look like and function?

**Comment by olesyabrk** [comment]
As far as I know the customer won't be able to change the title in the domain dropdown or the header. Title change happens in FSE or in Site Settings. I don't mind the border on focus/hover, bigger targets are more accessible. Let's do it.
