### ISSUE TITLE
Gutenboarding: close drop-downs when clicking outside them

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37856]
Clicking outside any of these drop-downs should close them, as is the common UI practise:

<img width="1024" alt="Screenshot 2019-11-22 at 12 12 10" src="https://user-images.githubusercontent.com/87168/69417451-5d61e500-0d21-11ea-9d3f-9b8ce22ec49c.png">

## Todo

- [x] DomainPicker Popover (@sirreal) - #37859 
- [ ] VerticalList (@razvanpapadopol)

**Comment by sirreal** [comment]
Closely related to #37854
