### ISSUE TITLE
CoBlocks: Images in Collage gallery disappear when you edit the post/page 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#37858]
I've noticed image sin the collage gallery disappear if I open the page/post in the editor.

Tested on a Simple site with the latest Chrome.

**Steps**
* Add a CoBlocks Collage gallery onto a page
* Add an image to each placeholder
* Publish the page
* Notice the images on the frontend of the published page
* Edit or reload the page in the editor
* Notice the images are gone :/

<img width="1392" alt="Screenshot 2019-11-22 at 11 07 02" src="https://user-images.githubusercontent.com/908665/69421205-57b3d180-0d18-11ea-971c-78afc6f36bcb.png">

<img width="1392" alt="Screenshot 2019-11-22 at 11 05 25" src="https://user-images.githubusercontent.com/908665/69421234-64382a00-0d18-11ea-97ae-e249b56cac55.png">

<img width="1392" alt="Screenshot 2019-11-22 at 11 05 52" src="https://user-images.githubusercontent.com/908665/69421259-7c0fae00-0d18-11ea-894a-1d5b22c77ab1.png">

**Comment by kcswong** [comment]
Had a user report this in 16916582-hc. They were scheduling a post, then noticing coming back to the editor that all of the images in the Collage blocks had disappeared. I was able to replicate this on a test site, as well as the steps in the original report above. 

Recommending the user to try a different gallery block in the meantime.

**Comment by iamtakashi** [comment]
Could @Automattic/serenity look into this when you folks have a chance? I'm planning to use this block in new templates. 

I've added it to the project board, but I probably should've pinged you all before doing that :)

**Comment by gwwar** [comment]
@glendaviesnz would you be interested in investigating this one?

**Comment by gwwar** [comment]
Verified that the published view is okay, but a second edit gets wiped. Version 1.18.0 doesn't fix this.

Example:

Published View:
```
<!-- wp:coblocks/gallery-collage -->
<div class="wp-block-coblocks-gallery-collage has-caption-style-dark"><ul><li class="wp-block-coblocks-gallery-collage__item pb-2 sm:pb-2 lg:pb-2"><figure class="wp-block-coblocks-gallery-collage__figure"><img src="https://helpingcatblog.files.wordpress.com/2019/08/bearded-man-casual-wear-daylight-2594859-1.jpg?w=682" alt="" data-id="150" data-imglink="" data-link="https://helpingcatblog.wordpress.com/?attachment_id=150" class="wp-image-150" /></figure></li><li class="wp-block-coblocks-gallery-collage__item pb-2 sm:pb-2 lg:pb-2 pl-2 sm:pl-2 lg:pl-2"><figure class="wp-block-coblocks-gallery-collage__figure"><img src="https://helpingcatblog.files.wordpress.com/2016/05/wrj1.jpg" alt="" data-id="23" data-imglink="" data-link="https://helpingcatblog.wordpress.com/wrj1/" class="wp-image-23" /></figure></li><li class="wp-block-coblocks-gallery-collage__item pl-2 sm:pl-2 lg:pl-2"><figure class="wp-block-coblocks-gallery-collage__figure"><img src="https://helpingcatblog.files.wordpress.com/2019/08/looking-up-sitting-woman-1588038-1.jpg?w=750" alt="" data-id="145" data-imglink="" data-link="https://helpingcatblog.wordpress.com/?attachment_id=145" class="wp-image-145" /></figure></li><li class="wp-block-coblocks-gallery-collage__item pl-2 sm:pl-2 lg:pl-2"><figure class="wp-block-coblocks-gallery-collage__figure"><img src="https://helpingcatblog.files.wordpress.com/2019/08/bearded-man-blur-casual-wear-2594830-1.jpg?w=682" alt="" data-id="149" data-imglink="" data-link="https://helpingcatblog.wordpress.com/?attachment_id=149" class="wp-image-149" /></figure></li><li class="wp-block-coblocks-gallery-collage__item pl-2 sm:pl-2 lg:pl-2"><figure class="wp-block-coblocks-gallery-collage__figure"><img src="https://helpingcatblog.files.wordpress.com/2016/05/full-width1.jpg?w=750" alt="" data-id="21" data-imglink="" data-link="https://helpingcatblog.wordpress.com/contact/placeholder-image-3/" class="wp-image-21" /></figure></li></ul></div>
<!-- /wp:coblocks/gallery-collage -->
```

2nd Edit Load:
```
<!-- wp:coblocks/gallery-collage -->
<div class="wp-block-coblocks-gallery-collage has-caption-style-dark"><ul><li class="wp-block-coblocks-gallery-collage__item pb-2 sm:pb-2 lg:pb-2"></li><li class="wp-block-coblocks-gallery-collage__item pb-2 sm:pb-2 lg:pb-2 pl-2 sm:pl-2 lg:pl-2"></li><li class="wp-block-coblocks-gallery-collage__item pl-2 sm:pl-2 lg:pl-2"></li><li class="wp-block-coblocks-gallery-collage__item pl-2 sm:pl-2 lg:pl-2"></li><li class="wp-block-coblocks-gallery-collage__item pl-2 sm:pl-2 lg:pl-2"></li></ul></div>
<!-- /wp:coblocks/gallery-collage -->
```

**Comment by glendaviesnz** [comment]
We have a potential fix for this at D36576-code

**Comment by glendaviesnz** [comment]
D36576-code has been deployed and I retested this on a simple site and the issues is resolved.
