### ISSUE TITLE
Gutenboarding: focus on vertical input on re-select

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#37854]
At `/gutenboarding`, do these steps:

- type in a vertical search keyword, I see the list of verticals:
    ![image](https://user-images.githubusercontent.com/87168/69412949-8c278d80-0d18-11ea-90c8-340d2ba32999.png)

- Choose a vertical, all good still:
    ![image](https://user-images.githubusercontent.com/87168/69412984-9ea1c700-0d18-11ea-9d66-57d749a78640.png)

- Click again on that vertical to pick another on. You'll get this confusing state where I don't see the search keyword but I see the results and the keyword is highlighted:
    ![image](https://user-images.githubusercontent.com/87168/69413025-b37e5a80-0d18-11ea-9ba5-2a2a47ddd6c1.png)

- If you click on the vertical _again_, you'll see the keyword:
![image](https://user-images.githubusercontent.com/87168/69413072-c98c1b00-0d18-11ea-9898-9c61e274c486.png)

- If you click elsewhere on the page, I see again the previously selected vertical and the dropdown list:
    <img width="875" alt="Screenshot 2019-11-22 at 11 12 43" src="https://user-images.githubusercontent.com/87168/69413205-0bb55c80-0d19-11ea-8f90-e1264f23f665.png">

- If you type in a new search keyword but don't select it (click elsewhere on the page again), you'll see a new list and previously selected vertical:
    ![image](https://user-images.githubusercontent.com/87168/69413354-50d98e80-0d19-11ea-925d-2d75858734f9.png)

#### Problems:
- It's not obvious that I need to click _again_ on vertical to actually see the keyword; let's focus that input right away so that keyword becomes visible
- Let's close dropdown when the customer clicks outside the list; if they had chosen vertical previously, we can keep it.
- Maybe highlight previously selected vertical in the dropdown if they don't modify the search keyword?
- If they modify the search keyword, we should probably clear out the selected vertical.

**Comment by sirreal** [comment]
> It's not obvious that I need to click again on vertical to actually see the keyword; let's focus that input right away so that keyword becomes visible

I intended to address this with #37613

**Comment by razvanpapadopol** [comment]
> Let's close dropdown when the customer clicks outside the list; if they had chosen vertical previously, we can keep it.

This was part of the first iteration so I think I can re-add it quite easily.

> If they modify the search keyword, we should probably clear out the selected vertical.

We can do this. So if the user then clicks outside or tabs to other input we show again `enter a topic` as the button text.

**Comment by simison** [comment]
> > If they modify the search keyword, we should probably clear out the selected vertical.
>
>We can do this. So if the user then clicks outside or tabs to other input we show again enter a topic as the button text.

Good question; I think so — that would mean that we also clear out the search keyword that they typed and didn't choose a vertical from the list?

Right now when the intent gathering starts and customer types in a search term but never chooses a topic, we persist the dropdown even when clicking outside it and "don't let them go" until they've chosen something:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/87168/69423450-c8fe7f00-0d2e-11ea-8272-c960da44855f.png">

When the topic is cleared out, this "next" link should be hidden or disabled, because we can't let them go yet:

<img width="866" alt="Screenshot 2019-11-22 at 13 52 16" src="https://user-images.githubusercontent.com/87168/69423663-5fcb3b80-0d2f-11ea-9192-eabe36914402.png">

What if there are no results for their search? It can look like they're at dead-end, not knowing that they should try another keyword:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/87168/69423439-bf751700-0d2e-11ea-9742-542e62da84f1.png">

Suppose we can't store just the keyword — they _have_ to pick a topic from the list?

**Comment by dwolfe** [comment]
I didn't realize that the search keyword and selected vertical were separate things, at least at this stage. My understanding was that when a user clicks on a vertical in the dropdown, that vertical _becomes_ the search keyword, as in, it replaces whatever the customer typed, the way a basic Google search works.

I feel like I'm missing a piece of the puzzle here though - is the above not possible?

**Comment by simison** [comment]
@ockham asked at https://github.com/Automattic/wp-calypso/pull/37876#pullrequestreview-322118315 about this flow:

> decision if we want to allow for free-form input here, or if the user always has to select something from the vertical

We had a look at the live selector:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/87168/69527279-a52c7a80-0f74-11ea-80e6-50a9519df160.png">

- It allows customers to enter freeform terms
- picking up suggested vertical clears out user typed search term

I suppose that's how our selector can work as well, @dwolfe if you can confirm?

**Comment by dwolfe** [comment]
@simison Yes, great example - the vertical step we have today is how I envisioned that working.
