### ISSUE TITLE
Theme/Styles steps in test-fse flow

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#37870]
Let's see how users react when they're able to pick their site design and style early on

### Tasks

- [x] Enable the following step for the test-fse flow: https://github.com/Automattic/wp-calypso/pull/36825
- [x] Disable layout picker in the checklist for users who went through the test-fse flow - they already had a chance to pick a design: #38016

**Comment by ianstewart** [comment]
I made a small tweak to the text for the test-fse flow …

![image](https://user-images.githubusercontent.com/545779/69455758-b2582800-0d2e-11ea-9d64-a0951b92e885.png)

**Comment by p-jackson** [comment]
@ianstewart the new copy above looks like a better version of what we already have:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1500769/69762205-6abe1a00-11ce-11ea-9f6b-e92356a155fe.png">

**Comment by p-jackson** [comment]
Sorry for the pings, mis-clicked.

I'm going to update the wording using the screenshot above, but only for the `test-fse` flow. I thought it might have been an improvement for all flows, but I think changing nomenclature from "theme" to "design" is probably FSE specific.

**Comment by ianstewart** [comment]
Definitely FSE-specifc. You're selecting a theme here but also the starter content. So it's neither theme nor content. Hence, "Design."

**Comment by p-jackson** [comment]
All done, users now choose their initial design as part of the signup flow, not in the editor 👍

**Comment by apeatling** [comment]
@p-jackson This is still limited to Horizon? Because the vast majority of these themes are not FSE compatible yet.

**Comment by p-jackson** [comment]
@apeatling limited to the `test-fse` flow, which I'm guessing users won't stumble upon.

The themes shown in this step are defined in `themes-data.js`, I'll put the info in #38059
