### ISSUE TITLE
Refer to theme picker in signup as ‘choose a design’

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#37872]
The checklist task that opens the design picker is called `Update your homepage`. We found it confuses users - let's rename it to "Choose a design" and also update the description copy

<img width="626" alt="Zrzut ekranu 2019-11-22 o 16 44 15" src="https://user-images.githubusercontent.com/205419/69439479-5b128180-0d47-11ea-9277-e5f0b7c68d64.png">

**Important note:** We're going to disable the design picker for some users as part of https://github.com/Automattic/wp-calypso/issues/37870 - keep that in mind for the purposes of this task.

CCing @michaeldcain - what would be the right copy here?

**Comment by michaeldcain** [comment]
I honestly don't know that we should change it right now, given the translation time and that the picker will be removed with #37870 in (possibly less than) two weeks. @apeatling @ianstewart thoughts?

**Comment by ianstewart** [comment]
Adding @lcollette and @sixhours to the conversation here with this comment.

**Comment by michaeldcain** [comment]
In re-reading this issue, @adamziel are you actually referring to the Signup step title (to be introduced in #37870)? I think I got confused with the checklist image. If so, let's add that as a requirement on the other issue and close this one.

**Comment by apeatling** [comment]
+1 -- if it's the signup step this makes sense. Changing the checklist step doesn't because you won't be picking a design after milestone 2 is done.

**Comment by adamziel** [comment]
Closing this one
