### ISSUE TITLE
Design picker with generic/verticalized content

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#37874]
*Goal:*
On our way to Gutenberg onboarding, we need to find out whether we should move forward with generic content starter sites or highly customized content. One way to do it is testing both starter sites against each other and this is what this card is all about

*Tasks:*
- [ ] Merge design picker step https://github.com/Automattic/zelda-private/issues/119
- [ ] Prepare 9 Photography starter sites 
- [ ] Set up an A/B test that enables design picker and site style steps in `onboarding` flow for Photography-related verticals (all segments).
- [ ] Variation A: Generic starter sites in design picker step
- [ ] Variation B: Photography sites in design picker step

Generic sites should serve as a fallback in case we need one

**Comment by michaeldcain** [comment]
> Prepare 9 Photography starter sites

This is partially being handled by @iamtakashi in #37782. After we have ~2-3 possible Photography matches for each homepage template type (blog, site, portfolio), @ianstewart, Takashi, and I will work on customizing the imagery for photography.
