### ISSUE TITLE
Full Site Editing: Hide nested blocks dashed border in the Post Content block

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#37885]
When selecting a Group (or group-like, as Cover) block, Gutenberg automatically decorate its nested blocks with dashed borders.

<img width="1141" alt="Screenshot 2019-11-22 at 18 31 26" src="https://user-images.githubusercontent.com/2070010/69451095-80f35280-0d56-11ea-92a2-6c81fa1aa37c.png">

While this is a nice usability feature, it's not really needed for blocks nested directly inside the FSE Post Content block.

The FSE Post Content block has more of a technical purpose than visual, and in fact all its UI hidden and disabled, so there aren't any usability reasons to show the borders.

**NOTE**
Several layouts heavily relies on the Group block, which will trigger the borders for its children blocks.
I think this should remain unchanged, so let's make sure to ONLY hide the borders from blocks _directly descending_ from the Post Content block.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
