### ISSUE TITLE
Checklist: Remove the "Set a tagline" item

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37892]
This has been ignored in all of our user tests. It's also something that can be edited directly in Gutenberg with the FSE flow, so is not needed.

Let's remove it. I think this is happening as part of the overall rethink of the checklist items, so feel free to close this once that's in place.

**Comment by sixhours** [comment]
I started a diff to remove the tagline item in D36187-code.

**Comment by sixhours** [comment]
Deployed in r200207-wpcom
