### ISSUE TITLE
Marketing - Traffic: previewing Website meta opens home page

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#37904]
When you want to preview the Website meta and how it looks in Google, Facebook, or Twitter, the preview closes automatically after a few seconds and the home page is open in a new tab.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/marketing/traffic/elio.blog
2. Scroll down to Website meta
3. Click the Show Previews button (issue occurs regardless of whether there's text Front Page Meta Description or not)
4. wait for it

#### What I expected
To stay in the preview modal and be able to check all of them

#### What happened instead
After a few seconds and without any user intervention, the site home page is open in a new tab while the modal is closed

#### Browser / OS version
Chrome 78 / MacOS Catalina 

#### Screenshot / Video
![jump-redirect](https://user-images.githubusercontent.com/1041600/69475178-d0fb0500-0da8-11ea-9c3f-6046d9eb319a.gif)

#### Context / Source
#reallife #flowsharing #anxiety #anxiety-flow #stresscase #painpoint
#manual-testing #user-report

**Comment by donalirl** [comment]
I constantly run into this. Most recently in #2630533-zen at the 28:20 video mark.

**Comment by pauljacobson** [comment]
FYI, this issue seems to have been opened here first: #37334
