### ISSUE TITLE
Customer Home: Thanked for purchase after clicking "Skip Purchase"

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#37939]
#### Steps to reproduce
1. Start with an un-launched simple site that already has a plan (I used personal)
2. Launch site (I launched from Customer Home)
3. Complete launch flow, skip domain purchase
4. Land on Customer Home

#### What I expected

Customer Home banner would say something like "Congratulations on launching your site".

#### What happened instead

Customer Home banner says "Thank you for your purchase!"

I'm guessing this is because I made a purchase within the last 30 minutes, but it doesn't feel right because I just clicked a button that literally said **Skip Purchase**. Did I just accidentally spend more money?

Bringing up my past purchase just doesn't feel right since launching is much more exciting.

#### Screenshot / Video

![Nov-26-2019 15-45-17](https://user-images.githubusercontent.com/1500769/69595397-48a88880-1064-11ea-9539-7b12b2d03552.gif)

**Comment by gwwar** [comment]
This one is fixed by @Aurorum ✨ in https://github.com/Automattic/wp-calypso/pull/39330
