### ISSUE TITLE
Customer Home: Did not get any confirmation after launching site

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#37930]
#### Steps to reproduce
1. Go through the current onboarding flow, pick "Blog" as the vertical, pick a free Domain/Plan
2. Once you reach Customer Home, Launch your site (I launched it from that big "Launch" button on the right)
3. Be prompted to pick a Domain and a Plan again
4. Once you're back in Customer Home, notice how there isn't any sort of feedback that your site has been launched. If anything, it's more confusing because it's telling you "Your site has been created" when it already _has been_ created

#### What I expected
To be shown some sort of confirmation that my site has been launched.

Earlier today, I launched a different site (different vertical, I know it wasn't "Blog"), and I saw a notice telling me my site has been launched (`global notice` component). There was also another notice (`banner` component) telling me I've completed all my Checklist items. But I didn't see those in this particular case.

#### What happened instead
I was brought back to Customer Home without any confirmation about my site already launched.

#### Browser / OS version
Google Chrome Version 78.0.3904.97 
Mac OS 10.14.2

#### Screenshot / Video
![Screenshot 2019-11-25 11 45 08](https://user-images.githubusercontent.com/4924246/69573416-e4f66080-0f7a-11ea-9cf0-88cee2249fb2.png)

**Comment by iamtakashi** [comment]
+1
