### ISSUE TITLE
Signup: All activation are showing the passwordless email version

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#37943]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Signup for an account with email, username and password(not a passwordless signup)

<img width="404" alt="Screenshot 2019-11-26 at 11 21 56 AM" src="https://user-images.githubusercontent.com/1269602/69602883-fc971d00-103e-11ea-9c95-045b6fc39fcc.png">

3. Check the activation email

#### What I expected

The activation email should show the `marketing_activation_encourage` template:

<img width="489" alt="Screenshot_2019-11-26_at_11_23_15_AM" src="https://user-images.githubusercontent.com/1269602/69603102-a1b1f580-103f-11ea-9882-6a6c5555c443.png">

#### What happened instead

It shows the `activation-encourage-passwordless` template:

<img width="486" alt="Screenshot_2019-11-26_at_11_27_26_AM" src="https://user-images.githubusercontent.com/1269602/69603159-cc03b300-103f-11ea-902b-222f4505e437.png">

**Comment by niranjan-uma-shankar** [comment]
Worked on in D35945-code.

**Comment by andrewserong** [comment]
Approved! Thanks again.

**Comment by niranjan-uma-shankar** [comment]
Thanks for the quick review!
