### ISSUE TITLE
Themes: Get rid of `Helmet`

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#3795]
We should really get rid of Helmet, as it's more hassle than benefit.

Rationale: For most pages we want to give `title` and `meta` tags, we'll have to fetch some data from Redux (e.g. theme name for a theme sheet). From there, we have to add those data to Helmet; `rewind` Helmet right after `renderToString` to get the data back (and not forget to cache them alongwith the rendered markup!); and pass them to `index.jade` to have them rendered in their appropriate places.

Or we just get them from Redux, and pass them to `index.jade`.

**Comment by ockham** [comment]
We might want to turn the `setTitle()` Flux action in `lib/screen-title` into something Reduxy for us to use.

**Comment by ockham** [comment]
Now that there is the `DocumentHead` component, I think that's what we'll want to use. Internally, this still relies on Flux stuff (invoked by Redux actions), so we'll need to change that before we can use `DocumentHead` on the server.

The TODO would be:
* [ ] Remove all calls to `screen-title` actions, replace them by `DocumentHead` components in the corresponding places.
* [ ] Remove anything Flux-y in `screen-title` (legacy actions), handle window title setting directly from the Redux action
* [ ] Replace our `<Head>` component with `<DocumentHead>`, use the corresponding Redux subtree to populate HTML Head elements in `server/pages` and `server/render`, respectively.

**Comment by tomas-andr** [comment]
Ok, I took a look at the source code, if I understand correctly:
- `DocumentHead` is trying to be the new Reduxy way of managing the document head (title, meta, ...)
- the real work is still being done by `lib/screen-title`, which relies on Flux, the meta tags are not really supported
- Helmet is there mostly for the first (probably server-side) render anyway

I propose to merge `DocumentHead` and `lib/screen-title` into one Reduxy component, and also use this one in `Head` (currently only a Helmet wrapper)

**Comment by ockham** [comment]
Sounds quite good! You're right with your diagnosis -- one note on the suggested therapy:

> I propose to merge `DocumentHead` and `lib/screen-title` into one Reduxy component

Not sure I'm reading you correctly here, but I wouldn't merge everything into a component. Note that `DocumentHead` already uses Redux actions, so we shouldn't unnecessarily introduce new ones. Instead, let's make sure that any side effects currently handled by the Flux stuff are instead handled in a Reduxy way. And as for server-side rendering, it will ideally be able to just use the initial Redux state.

You might find some more ideas floated around in issues around `DocumentHead` by @aduth.
