### ISSUE TITLE
Hosting: tighten copy and other minor styling updates

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#37979]
Consolidating some feedback from @obi2020 + others

- [x] Let's pare down answers as much as possible to maybe one sentence. This avoids copy going out of date and folks skipping over large chunks of text
- [x] Switch subheader to be more descriptive when both SFTP / PHP Version Switcher are enabled. "Access your website and database directly." or "Advanced settings for managing your site’s files and databases."
- [x] Copy check: "Enable SFTP Credentials". Generate? Create?
- [x] Should we still display common SFTP questions after creating an SFTP user? I would +1 keeping it around, though the UI was a bit awkward when we don't hide this. cc @olaolusoga
- [x] Design: "losing changes since last backup" is too easy to miss. Let's be careful not to make the whole page a single giant warning.
- [x] Drop "Reasons to access my database" or provide better reasons

**Comment by carolynannewells** [comment]
@gwwar Please can you direct me to the original copy for review? Thank you very much!

**Comment by gwwar** [comment]
@carolynannewells see paYKcK-nL-p2 let me know if you had any questions, we plan on trimming down on quite a lot.

**Comment by carolynannewells** [comment]
@gwwar Sorry to keep bothering you, but it that a P2 link? Sorry I am having such problems getting to the copy!

**Comment by mmtr** [comment]
All feedback covered on #37991 and #37258
