### ISSUE TITLE
Domains: Missing DNS records after changing Domain Mapping to a different site

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#3798]
As reported on `p2MSmN-4Al-p2`
#### Steps to reproduce

(these steps might need to be verified with the original poster)
Wanting to map domain `example.com`
1. Already have `example.com` mapped to a site that has been deleted (the site, not the mapping).
2. Delete the mapping from the old site.
3. Map `example.com` to the correct, new site.
4. Check DNS records on https://wordpress.com/domains/manage/example.com/dns/example.com
#### What I expected

Normal DNS records for Domain Mapping
#### What happened instead

Stuck at loading placeholder.
Note that after a while (a few hours), it seems the DNS changes were propagated and correct DNS records showed up. During that time however there should be a more helpful info displayed than a loading placeholder.
#### Screenshot / Video

![screen-shot-2016-03-04-at-1-05-25-pm](https://cloud.githubusercontent.com/assets/3392497/13551254/9c4db4d6-e333-11e5-8fc7-b668ca683579.png)

**Comment by umurkontaci** [comment]
Is this an edge case or something might happen more often?

**Comment by klimeryk** [comment]
Honestly, no idea. I think the more common scenario is that the user renames their site instead of deleting one and creating a new mapping subscription on a new one.

**Comment by klimeryk** [comment]
We haven't seen more reports of this and I can't reproduce it - closing.
