### ISSUE TITLE
Purchases page: "Cancel Subscription" downgrade option broken

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#37982]
#### Summary:
When a user visits their [Purchases page](https://wordpress.com/me/purchases) they have an option to "Cancel Subscription". Upon choosing this option they go to a new page which states:

>When you cancel your subscription, you'll be able to use WordPress.com Premium until your subscription expires. Once it expires, it will be automatically removed from your site.

If they move forward with the cancellation and choose the reason "The plan was too expensive." then we will solicit the option for them to downgrade to a low-cost plan, like the Personal or Premium plan. If they agree to this then that plan is immediately applied, contrary to the message on the prior page. Based on the message that I quoted above, we could easily assume that the Premium plan would remain active and the Personal plan would take effect whenever it expired. 

In the case of my user this caused their Premium theme and CSS to be unexpectedly remove and they will need to set things up themselves.

#### Prerequisite:
* Must be a simple site (not Atomic)
* Needs to have the Premium or Business plan upgrade
* Auto renewal must be enabled

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Select the Business or Premium plan that you wish to downgrade
3. Select "Cancel Subscription" here and then "Cancel Subscription" on the next page too
4. For the "Please tell us why you are canceling:" question please choose "The plan was too expensive."
5. For the "Where is your next adventure taking you?" question I chose "I'm staying here and using the free plan.", not sure if this matters
6. Select "Next Step"
7. You will be offered a downgrade to a lower-tier plan such as Personal or Premium, accept this offer
8. Note that the lower-tier plan is immediately applied to the website and the previous plan is gone

#### What I expected
On the cancellation page we state "you'll be able to use WordPress.com Premium until your subscription expires". This is true if a basic (non-downgrade) option is selected. However, if the user accepts our offer to downgrade to a lower-tier plan then they're immediately moved to that plan instead of getting to remain on their plan until it expires.

Based on this messaging we should allow the user to keep their existing (Premium/Business) plan, then only downgrade it automatically on that plan's expiration date.

#### What happened instead
If the user accepts our offer to downgrade to a lower-tier plan in the cancellation process then we immediately downgrade them instead of allowing them to continue using their plan and then downgrading once it expires. This doesn't make sense with the other messaging we provide in the cancellation process.

#### Screenshot / Video
The video contains credit card information, please DM me if needed.

#### Context / Source
#user-report in 16919678-hc

**Comment by DavidRothstein** [comment]
I remember raising this issue in a code review when the plan downgrades were being implemented (D30716-code#618798) and suggested that the expected behavior needed to be discussed more internally.

I'm not sure if that ever happened and if a decision was made, but delaying the downgrade to the point of expiration seems like it would be pretty complicated to implement... Probably it would be better to just improve the wording in the UI to make clear to the user that if they choose to downgrade now, the downgrade takes effect immediately.  And then they can make an informed decision about whether that's what they want to do or not.

**Comment by aaronrobertshaw** [comment]
I've added a PR (https://github.com/Automattic/wp-calypso/pull/41270) with the additional wording for this.

**Comment by glendaviesnz** [comment]
We have improved the wording in #41270 and this is merged in now. @xpurichan, do you want to keep this issue open to see someone can pick it up to change the functionality so downgrading doesn't apply until the current plan expires, or based on @DavidRothstein comment this was seen as too difficult to implement, should take the wording change as good enough for now and close this?

**Comment by youbrokesomething** [comment]
Messaging around downgrading was updated in 2020 and nothing further has been added to this issue since. I'm going to close this but it should be reopened if user reports come up again.
