### ISSUE TITLE
Hide launch banner from popup preview window

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#37984]
Private by default sites display a large launch banner in the preview window, it creates an ugly double primary button:

<img width="190" alt="Screen Shot 2019-11-26 at 12 06 47 PM" src="https://user-images.githubusercontent.com/437258/69660283-f492a980-104d-11ea-8a3f-41a3f9086c2c.png">

We should hide this just for the pop up preview, but let it remain for a full screen preview. Hopefully that is do-able with a body class. 

Edit by @gwwar: If we detect a site is in an iframe, do not show the launch site banner.

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.

**Comment by gwwar** [comment]
This was fixed by @michaeldcain and @adamziel  in D41403-code and D41416-code
