### ISSUE TITLE
Checkout: Missing validation for coupon code

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#3799]
#### Steps to reproduce
1. Proceed to checkout
2. Input any (or even none) coupon code
3. Hit `Apply`
#### What I expected

Not allowing the submission of empty coupon code (disabled `Apply` button, validation error on the input field, stuff like that).
Not allowing the submission of an invalid coupon code (_if_ there is a common format for them).
#### What happened instead

The form instantly submitted, but returned an error in a `Notice` after a considerable delay.

**Comment by janm6k** [comment]
Going through old issues, closing ones that did not have any activity in long time.

Please feel free to reopen if applicable.
