### ISSUE TITLE
Mobile/Settings: Double Save Buttons

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#38]
Double save buttons look particularly ridiculous/redundant on pages like this. Can we just go back to using a single Save button at the bottom of these pages?

![image](https://cloud.githubusercontent.com/assets/7233112/11223452/f7459b02-8d3d-11e5-81ca-a1a04254dbcc.png)

Whilst I understand the reasoning behind a double save, it feels cumbersome even on longer pages. Asking me to save before I've even done anything is a little awkward from a user's view. I'm not convinced it adds all the benefits it's intended to.

**Comment by lancewillett** [comment]
I think it's a nice UX convention because if you decide to make a tiny change and just save, it saves a scroll.

Closing for now... feel free to bring up again if you feel strongly. :)
