### ISSUE TITLE
Gutenboarding domain picker: don't change width when showing different domains

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38018]
Domain picker at `/gutenboarding` changes width depending on the content. 
It should stay more or less the same width if possible.

<img src="https://user-images.githubusercontent.com/87168/69789758-d3ef5e80-11c9-11ea-90ef-2c14b6a2aa98.gif" width="350" />

**Comment by roo2** [comment]
I attempted to solve this but found some other issues, the picker gets cut off on mobile and very long domains cause it to get pushed off-screen, I think it might need a higher level look at. https://github.com/Automattic/wp-calypso/pull/38678

**Comment by simison** [comment]
I elaborated more on https://github.com/Automattic/wp-calypso/pull/38678#issuecomment-571776696 but in gist — we'll likely move domain picker in some other spot eventually. I'll close this in meanwhile.
