### ISSUE TITLE
Checklist: Incomplete score when homepage set to latest posts

### ISSUE THREAD

**Issue by brookewp** [Automattic/wp-calypso#38012]
#### Steps to reproduce
1. Make sure homepage is set to display latest posts and you've never changed to a static page before (can add you to test site if needed). 
2. Starting at URL: https://wordpress.com/stats/day/
3. You will see 75% completed checklist. Click on "Start" or "View Checklist" under "Update your homepage".
4. If you clicked "View Checklist", click on "Start"
5. You will end up in editor for a new page

#### What I expected

User has homepage set to display latest posts, so they don't need to update their homepage. I expected the checklist would be 100% complete or there would be an option to confirm having homepage display latest posts or option to create a page if I wanted a static page instead. 

#### What happened instead

User was sent to a page editor, which made them think they needed to create a page for their homepage when they don't need to. It made them feel like something was wrong. 

#### Screenshot / Video

View of Stats page in Step 2 & 3 above: 

<img width="1062" alt="Screen Shot 2019-11-26 at 4 06 05 PM" src="https://user-images.githubusercontent.com/35543432/69747871-29b5ff00-1115-11ea-9a1f-74aea9673bbc.png">

View of Checklist in Step 4:

<img width="997" alt="Screen Shot 2019-11-26 at 4 04 33 PM" src="https://user-images.githubusercontent.com/35543432/69747927-42beb000-1115-11ea-8e66-86800442ce18.png">

#### Context / Source

I mentioned this here as well since it seemed related to the checklist "update your homepage" workflow: https://github.com/Automattic/wp-calypso/issues/36338#issuecomment-558856494

This was found via a #user-report in chat, hc-16785317

**To quote the user's painpoint:** 

>User: My site doesn't see to have a homepage, although it works as I want it to. How can I fix this please? 
>_Me: Your homepage is currently set to display your blog posts instead._
>User: I know, but on the Stats page it shows as only 75% set up

**Comment by KokkieH** [comment]
Another report in https://en.forums.wordpress.com/topic/update-your-homepage/

#38097 looks like it might also be related.

**Comment by JessBoctor** [comment]
I had another user with this issue: [#2538730-ZN](https://woothemes.zendesk.com/agent/tickets/2538730)

It might be worth noting that there is not a way to dismiss this notice in the 'View Checklist' option either.  It requires switching to a recently edited page in My Site > Design > Customizer >Homepage Settings to remove the notice.

**Comment by davipontesblog** [comment]
Moved to DotCom Manage for triaging.

**Comment by gwwar** [comment]
Let's remove this entire nudge with https://github.com/Automattic/wp-calypso/issues/38172
