### ISSUE TITLE
Media library: insert image from free library

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38027]
#### Steps to reproduce
1. Edit any page on one of your sites
2. Add a new block image
3. Pick an image from the free media library

#### What I expected
Image from the free image library to be inserted.

#### What happened instead
No image was inserted. It was added to my library but not to the page. I had to open the media library and pick the free image from my library again.

#### Browser / OS version
Chrome — MacOS

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/69828837-79ff9080-11eb-11ea-9e20-4ed34311f48c.png)

**Comment by fditrapani** [comment]
Might be related to https://github.com/Automattic/wp-calypso/issues/31230

**Comment by iamtakashi** [comment]
> No image was inserted. It was added to my library but not to the page. I had to open the media library and pick the free image from my library again.

I've also experienced this when I tried to replace an image on a page layout with an image from the free library. The image should be inserted to the block immediately without the need to go back to the WordPress library again.

**Comment by apeatling** [comment]
Keeping this #38067 and closing this one as a duplicate.
