### ISSUE TITLE
Launch: Sites not going through launch flow

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38028]
#### Steps to reproduce
1. Create a new site from `/start`
2. Visit the front-end of the site
3. Click on the launch button in the banner

#### What I expected
Some kind of feedback saying my site was launched or even going through the launch flow.

#### What happened instead
The banner just disappeared and the site was launched.

#### Browser / OS version
Chrome on MacOS

**Comment by davipontesblog** [comment]
I cannot replicate this one. Clicking on the Banner "Launch" button takes me to the launch flow. Closing this one, please reopen if needed.
