### ISSUE TITLE
Signup Plans: Free plan messaging under the personal plan

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38026]
#### Steps to reproduce
1. Starting at URL: `/start`
2. Make your way to the plans page in signup.
3. Notice the last bullet point under the personal plan

#### What I expected
Personal plan features

#### What happened instead
It says "All free features" but the free features are not listed anywhere.

#### Browser / OS version
Chrome

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/69828404-c0ec8680-11e9-11ea-8d58-fc5e7d6cd787.png)

**Comment by davipontesblog** [comment]
I can confirm this is still an issue with a test done today.

**Comment by lancewillett** [comment]
Confirmed with `https://wordpress.com/start/plans` — using an existing user.

<img width="872" alt="Screen Shot 2020-03-11 at 21 26 47" src="https://user-images.githubusercontent.com/66797/76487254-15a1bf00-63df-11ea-91b1-2e9110f3a9c1.png">

Suggested change:

- Replace "All free features" with "Dozens of free themes"
