### ISSUE TITLE
Domains: tweak copy for domain contact verification notice

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#3802]
The notice shown when a domain registered with WordPress.com has unverified contact details mistakenly states that domains affected can be "lost forever". Further, it could use a link to the relevant support page.

Suggest changing the notice copy to the following:

> Urgent. Please verify your address through the verification email as soon as possible, or your domain may be suspended.

> (button)

> Use this button to resend the verification email. It contains a link to verify your address. [Learn more](https://en.support.wordpress.com/register-domain/#email-validation-and-verification).

The Learn More link points to: https://en.support.wordpress.com/register-domain/#email-validation-and-verification

This is re. some post-merge discussion in PR #3365.

cc @wensco @BandonRandon

**Comment by BandonRandon** [comment]
Thanks this should be updated in #3818 please test.
