### ISSUE TITLE
Signup: inconsistent emails

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38033]
#### Steps to reproduce
1. Visit `/start`.
2. Create a new account .
3. Pick a paid plan.
4. Create your site.

#### What I expected
I received 3 emails in very short time

#### What happened instead
Each of those emails looked different from the other

#### Browser / OS version
Chrome / MacOS

#### Screenshot / Video
<img width="710" alt="Screen Shot 2019-11-28 at 2 06 43 PM" src="https://user-images.githubusercontent.com/6981253/69829742-4b83b480-11ef-11ea-9e3d-f86ac5bab5f4.png">
<img width="723" alt="Screen Shot 2019-11-28 at 2 06 50 PM" src="https://user-images.githubusercontent.com/6981253/69829752-50486880-11ef-11ea-8218-d4454093b5a1.png">
<img width="713" alt="Screen Shot 2019-11-28 at 2 06 58 PM" src="https://user-images.githubusercontent.com/6981253/69829753-51799580-11ef-11ea-8af6-cf76b2470ef5.png">

**Comment by ianstewart** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/38037

**Comment by davipontesblog** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/38037 where the task is being tracked.
