### ISSUE TITLE
Checkout: New store not created properly if domain and eCommerce plan in cart

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#38038]
After signing up with eCommerce plan and paid domain there are some issues navigating around Calypso.

- The store menu item takes a while to appear sometimes
- Navigating to editor or Store shows a Jetpack connect page asking the user to verify email.

I think this is happening because adding a paid domain to the cart means the [gsuite nudge is shown](https://github.com/Automattic/wp-calypso/blob/e5b263eefe16343d2ea1489b172dc5bd9b4fc9d9/client/my-sites/checkout/checkout/index.jsx#L414). Without a paid domain then post-checkout a "doing more processing" page shows, and then a very strong encouragement to verify your email now.

Reported p1574963020131100-slack-CCS1W9QVA

#### Steps to reproduce
1. Logged-out, new incognito session, in Chrome — still proxied.
2. Create new user in signup.
3. Select Business segment at segment step in signup
4. Select a paid domain in signup
5. Select eComm Plan in signup
6. Checkout
7. **Bug:** See the Customer Home screen above with no Store link in sidebar
8. Navigate to /pages
9. Click on Home page to edit
10. **Bug:** See the Jetpack connect screen to connect instead of the editor
11. Use the browser back button to go back to Calypso and see the Store menu item appear in sidebar
12. Click on the Store menu item
13. **Bug:** See the Jetpack connect screen instead of the setup wizard

#### What I expected
After checkout, an extra loading screen should appear (which I'm guessing waits for AT to complete so the Store menu item appears), and a big green nudge to verify your email.
![image](https://user-images.githubusercontent.com/1500769/69834639-83970000-12a0-11ea-85c9-8e451e88e854.png)

#### What happened instead
No store link.
![image](https://user-images.githubusercontent.com/1500769/69834634-79750180-12a0-11ea-9ded-dd84cbf00b1d.png)

When trying to edit the homepage.
![image](https://user-images.githubusercontent.com/1500769/69834465-6e6da180-129f-11ea-92e3-71ef63106edc.png)

**Comment by p-jackson** [comment]
CC @Automattic/marketing-dev

**Comment by niranjan-uma-shankar** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/35406.

I have a PR to fix this in https://github.com/Automattic/wp-calypso/pull/35384 but I missed responding to feedback from @ramonjd , my bad. I'll pick that up again.

**Comment by p-jackson** [comment]
Closing as duplicate
