### ISSUE TITLE
Gutenberg: Back button doesn't do what it says

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38031]
#### Steps to reproduce
1. Go to `/pages` or `/posts`
2. Pick a page or post to edit.
2. Hover over the back button (it says view pages)
3. Click the back button

#### What I expected
When I press the back button, I expect to go back to the pages (it said so in the hover). 

#### What happened instead
I always get taken back to the home page no matter how I arrive to the editor. 

#### Browser / OS version
Chrome on Mac OS

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/69829535-5f7ae680-11ee-11ea-8017-89aeaf9960cd.png)

**Comment by iamtakashi** [comment]
I've also experienced this before, but the button seems to work correctly now 🤔

**Comment by apeatling** [comment]
This is fixed by the recent sync.
