### ISSUE TITLE
Customizer: Launch site does nothing

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38032]
#### Steps to reproduce
1. Create a new site that hasn't been launched.
2. Go to the customizer
3. Click on Launch

#### What I expected
Go through the launch flow

#### What happened instead
Nothing

#### Browser / OS version
Chrome / MacOS

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/69829627-c1d3e700-11ee-11ea-896e-e14460fdecfd.png)

**Comment by michaeldcain** [comment]
The launch banner is no longer visible in the Customizer. Closing.
