### ISSUE TITLE
Create account: Username field validation error

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38030]
#### Steps to reproduce
1. Open an incognito window
2. Create a new site here
3. Enter an email address
4. Tab to the user name

#### What I expected
To enter my user name

#### What happened instead
I got a field error the second I tabbed over to it.

#### Browser / OS version
Chrome on MacOS

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/69829495-335f6580-11ee-11ea-892e-abd2cf52ab79.png)

**Comment by iamtakashi** [comment]
+1!

**Comment by ianstewart** [comment]
+1 see https://github.com/Automattic/wp-calypso/issues/38068

**Comment by rickybanister** [comment]
@niranjan-uma-shankar I just confirmed this is still happening. 

Wondering if it's something you and your team could pick-up? It might scare or frustrate customers a bit to see the validation error before ever typing anything.

**Comment by obenland** [comment]
@niranjan-uma-shankar Have you had a chance to take a look at this?

**Comment by niranjan-uma-shankar** [comment]
I haven't yet gotten a chance to look into it. I've added this issue to our project board to track.

**Comment by ddc22** [comment]
Working on a fix here #49393 :)

**Comment by simison** [comment]
@jdc91 safe to close? :-) Feel free to re-open if still an issue.
