### ISSUE TITLE
Emails: Out of Date Copy

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38037]
Example:

> Once you’ve logged in, I recommend looking through the hundreds of free templates available for your site. Click here to see them now. Don’t worry about finding the perfect template, you can always choose a different theme later!
> 
> After you’ve selected a template, you can start customizing your website with our exclusive Customizer tool. This is where you’ll upload your logo, choose your colors, write your site copy, and any other changes you’d like to make. All without needing to know a single bit of code!

We refer to themes as templates interchangeably. And confuse the Customizer with Gutenberg. And suggest it's "exclusive."

It may be better to redact much of this and send people to Customer Home?

**Comment by michelleweber** [comment]
Looks like this is part of a drip or onboarding campaign from customer marketing, but I don't know which -- @donlair, do you know?

**Comment by donlair** [comment]
I think it's the 'welcome-encourage' email template. CC @sararosso

**Comment by sararosso** [comment]
We already have a thread for this on emailp2 - not sure if this is a public thread so won't link here - I just posted it yesterday @michelleweber @donlair

**Comment by ianstewart** [comment]
It appears as if this one is still live. Or, at least, I can still see it in the template?

**Comment by bubel** [comment]
I'm grabbing this one now and adding it to our internal email tracking board. It's in my hands, and I'll jump on it ASAP.

**Comment by ianstewart** [comment]
Thanks @bubel!
