### ISSUE TITLE
Homepage layouts previews do not show the full site content

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#38049]
When creating a new page https://wordpress.com/page, we have the new `Homepage layouts` section on the left. I believe this is as a part of the FSE (Full site editing) project. Previewing the templates on the right, does not show the full width. The content on the left/right are cut out. 

This does not seem to be isolated to a theme, but happens for all `Homepage layouts` options.

<img width="1524" alt="Screenshot 2019-11-28 at 19 57 01" src="https://user-images.githubusercontent.com/18581859/69873283-ece93400-12dd-11ea-8cdd-e0dfcc6faa20.png">
<img width="1525" alt="Screenshot 2019-11-28 at 19 56 49" src="https://user-images.githubusercontent.com/18581859/69873284-ed81ca80-12dd-11ea-8f9b-88fe3c372fc4.png">
<img width="1539" alt="Screenshot 2019-11-28 at 19 56 35" src="https://user-images.githubusercontent.com/18581859/69873285-ed81ca80-12dd-11ea-9bd2-880e202bf2d3.png">

**Comment by apeatling** [comment]
This should now be fixed with #39122
