### ISSUE TITLE
Update design step in signup to only show FSE supported themes

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#38059]
Currently the step shows all template first themes, and a few of the older default themes. We should only be showing FSE enabled themes in this step.

@vindl What's the best way to filter themes by FSE support?

/cc @andrewserong @michaeldcain

**Comment by vindl** [comment]
> @vindl What's the best way to filter themes by FSE support?

By checking for `full-site-editing` theme tag. For reference you can check out this code example and replace `auto-loading-homepage` with `full-site-editing`.

https://github.com/Automattic/wp-calypso/blob/55c3c384cb33ef318f96ae74e9e4d7cff61b22e8/client/state/themes/actions.js#L947-L964

**Comment by p-jackson** [comment]
The themes displayed during the `test-fse` flow are defined in `themes-data.js` https://github.com/Automattic/wp-calypso/blob/5696d84c15e5b5915c671bcf7e9909c3068b2bf6/client/lib/signup/themes-data.js#L226

The step shows any theme where `design = 'template-first'`

**Comment by apeatling** [comment]
Just template first won't be enough, they need to be full site editing compatible.

**Comment by p-jackson** [comment]
Understood. We should probably create a new step definition then that's basically a copy of `'template-first-themes'` except `designType = 'fse-compatible'` (or something similar), then add the 3 fse compatible themes to `themes-data.js`.
