### ISSUE TITLE
FSE: Remove Switch to Classic Editor from Help

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38056]
![image](https://user-images.githubusercontent.com/545779/69882080-a02d3b00-1294-11ea-91dc-cbefd4671444.png)

The large button in Help allowing a switch to the Classic Editor feels out of place in the test-fse flow.

**Comment by apeatling** [comment]
This should be removed for all new users. I also cannot switch back to Gutenberg after selecting this!

**Comment by noahtallen** [comment]
Post here about whether to do this more broadly: paAmJe-Tq-p2

**Comment by noahtallen** [comment]
Interesting -- I do not see this on my FSE site. We did implement this at some point, so there might be an edge case here:

<img width="1551" alt="Screen Shot 2019-12-09 at 11 25 02 AM" src="https://user-images.githubusercontent.com/6265975/70465803-9a92da80-1a76-11ea-8977-739fe7f035a8.png">

**Comment by ianstewart** [comment]
Hmm. I was just able to reproduce it …

![image](https://user-images.githubusercontent.com/545779/70466067-f44fd080-1a87-11ea-9890-799bd0cdaf49.png)

Starting from Horizon as a new user.

**Comment by noahtallen** [comment]
Ah, yeah I see that now too. It looks like it happens the first time, but if you reload the page, it doesn't happen anymore. I think it probably needs to redo the API call to make sure the data is fresh. There are some other cases where this seems to be flakey as well, so I'll take a look
