### ISSUE TITLE
FSE: Elements inside the column block can't be seen in the Header

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#38050]
#### Steps to reproduce
1. Edit your header
2. Add a column block with 2 columns
3. On the left column, add a menu block
4. Add something else, like social links, to the right column

#### What happened

I can see the elements on the front end:

<img width="1680" alt="Captura de Tela 2019-11-29 às 11 04 11" src="https://user-images.githubusercontent.com/1136160/69874153-1469dd80-1299-11ea-9103-f15ef27a7a78.png">

But I can't see them at all when I close the Edit Header option and go back to the full home:

<img width="1381" alt="Captura de Tela 2019-11-29 às 11 00 44" src="https://user-images.githubusercontent.com/1136160/69874199-28154400-1299-11ea-8966-a9dbfbb244cd.png">

#### Browser / OS version

Chrome 78.0.3904.97 on Mac OS

#### Screenshot / Video

In the video below, I added the columns on a group block:

https://d.pr/v/mUjSvF/nOZUm94xzl

Other notes:

* This happens with or without right-aligning the social links
* With the right alignment, things look vertically off

#### Context / Source
#dogfooding

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.

**Comment by eduardozulian** [comment]
@davipontesblog can you link me to a p2 post that has more info about it? Thanks!

**Comment by davipontesblog** [comment]
@eduardozulian AFAIK FSE sites will have the site editor replaced with core site editor experience once that is available soon, so this won't be pursued for fixing. Pinging @lancewillett  for confidence check.
