### ISSUE TITLE
Test FSE flow: Improved Onboarding into Editor when exiting Signup

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38058]
When selecting a design in Signup, entering the Editor when exiting signup seems like a natural choice. There are, however, downsides. There is a lot of information to process all at once in the Document Inspector. Additionally, there is little orientation provided. "Where am I exactly?"

We could, perhaps, hide the document inspector on the first view. Additionally, we could perhaps use the Help dialog to improve this first view. See this quick sketch, for example …

![image](https://user-images.githubusercontent.com/545779/69883402-a671e600-1299-11ea-86f6-a329a30d172e.png)

… if we did anything like the above we'd want to reveal the sidebar again after dismissing the help dialog. Otherwise, the user will potentially miss out on valuable block and document editing tools.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
