### ISSUE TITLE
Test FSE Flow: Landing in the Editor after exiting Checkout from signup feels broken.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38057]
In testing the test-fse flow today on Horizon, I was able to land in the Editor after checkout in signup — without any success messages. The flow felt broken.

To reproduce …

1. Signup as a new user at horizon.wordpress.com/start/test-fse
2. Select a plan
3. Complete Checkout
4. Land in the Editor w/o a success message

**Comment by apeatling** [comment]
Let's turn off this change for this milestone, and review improving that flow with new messaging in milestone 3.

**Comment by andrewserong** [comment]
Sure thing! I’ll whip up a PR on Monday to set the destination back to the customer home.

**Comment by apeatling** [comment]
@andrewserong I ended up straight in the editor still after selecting a free plan with a free domain. This should still go to the checklist too.

**Comment by andrewserong** [comment]
@apeatling from the timestamp of your comment, I think you might have tested this _just_ before the change was deployed (after merge but before deployment). Do you mind giving this another try?

**Comment by ianstewart** [comment]
Just tested it out now, works as noted by @andrewserong. 

1. Create account
2. Get a free domain.
3. Get a free plan.
4. Exit signup on home screen.

LGTM.

**Comment by apeatling** [comment]
👍 :+1:
