### ISSUE TITLE
FSE template part editor messaging misaligned with sidebar tab bar

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38069]
The "Update to this template..." notice at the top of the template part editor is similar in height to the tab bar at the top of the sidebar, but slightly taller, which looks like it's misaligned where they meet.

#### Steps to reproduce
1. Invoke the template part editor by editing the header in FSE.
2. Look at the right side of the screen where the notice meets the sidebar.

#### Screenshot / Video
![Screen Shot 2019-11-29 at 11 13 32 AM](https://user-images.githubusercontent.com/1348738/69887024-c3a6b480-1299-11ea-9d70-69a26abe1a75.png)

#### Potential solutions
- Use a different pattern than the notice?
- Apply a margin around the notice so it isn't flush with the top and sides of the canvas?
- Lean into it and make the notice the same height as the tab bar?

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
