### ISSUE TITLE
Account Step: Hasty Error Reporting

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38068]
We display error messages on username and password fields faster than it's possible to type …

![image](https://user-images.githubusercontent.com/545779/69886968-446dac80-12aa-11ea-9436-3a78c82df98f.png)

And I'm a pretty fast typist! :) More seriously, there should be some sort of delay here, rather than displaying the error message as soon as the focus changes.

**Comment by iamtakashi** [comment]
Previously reported in #38030.

**Comment by ianstewart** [comment]
Closing as duplicate.
