### ISSUE TITLE
Signup: Account creation notice flashes briefly before auto-navigating to next step

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38062]
In the test-fse flow on Horizon, there's a success notice after account creation that appears on the screen just before the page navigates to the domain step, so the user never gets a chance to read it.

#### Steps to reproduce
1. Signup as a new user at horizon.wordpress.com/start/test-fse
2. See notice flash on the screen just before the domain step fades up.

#### Screenshot / Video
![EH1-AccountCreationNoticeFlash mov](https://user-images.githubusercontent.com/1348738/69885496-4d528400-1292-11ea-814b-240067ea620e.gif)

#### Potential solutions:
- Do we need it? Can this just be removed?
- Turn it into a toast at the bottom of the screen which persists across signup steps?
- Move notice to the next step?
- Add a continue button that appears after account creation success?

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
