### ISSUE TITLE
Themes:  Hide "more themes" button change if filter is present.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#38061]
Follow-up to PR #37696 and Issue #37285.

After placing a "Recommended Themes" section at the top of the themes page and hiding the search functionality behind a "Show More" button, we see that it may be desired to hide these changes when a search filter is present.  This will allow HEs and users to share URLs with themes search results, without the results being hidden behind a button and beneath a recommended section.

#### Steps to reproduce
1.  With PR #37696 active.  Visit wordpress.com/themes (or calypso.localhost:3000/themes) while logged in, open the "More Themes" button, and add a search criteria to the search bar.
2.  Reload this URL now with the predefined search criteria.
3.  Notice that the "Recommended Themes" section appears first, and that you must click the "More Themes" button to view the search results you were trying to "share".

#### Thoughts on solving
My first thought to solving this issue is to make it so that if search filters are present, Recommended Themes does not render and the All Themes search section is open.  This would mean that in the normal flow of visiting my-sites/themes section a user would:
* See the Recommended Themes section.
* Scroll down to open "More Themes"
* Apply a filter in the search bar.
* At this point the Recommended Themes section at the top would now disappear.

Does this seem like a reasonable behavior?  @apeatling , @shaunandrews

**Comment by Addison-Stavlo** [comment]
After looking further, it seems to make more sense to always keep the Recommended Themes section there, but to auto-scroll (and auto open) to the search input when there is a query.  I have a working demo of the fix https://github.com/Automattic/wp-calypso/pull/38086 and am setting up a description on that PR.

**Comment by Addison-Stavlo** [comment]
Another idea (and more simple fix) is to hide Recommended Themes altogether and force the showcase open whenever a query is present. A working PR for this can be tested here - #38107.

What are our thoughts on how we want to proceed? We can show "Recommended Themes" at the top and force scroll-to's on loading for situations where queries are present, or we can hide "Recommended Themes" altogether when there is a query present.

**Comment by Addison-Stavlo** [comment]
@apeatling @shaunandrews -  Any thoughts on which way we should go here?  There are PRs above that can be tested for both directions.  I am a bit eager to get some feedback and ship some kind of fix for our users, but at the same time most of cylon is traveleling and it may take a little while to get a review anyways.  Either way, if we can narrow down the choice to either (or both as acceptable options) we can move on faster once a review is approved.

**Comment by shaunandrews** [comment]
> hide "Recommended Themes" altogether when there is a query present.

This seems like a good solution to me. The scrolling option seems like it could be a little confusing, and adds too many moving parts that could fail.
