### ISSUE TITLE
Confusing transition from checklist "Edit Homepage" step to layout picker

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38063]
When clicking "Edit Homepage" from the checklist on Customer Home, I think most users are going to expect to see their homepage, but the first time through, we take them through the layout picker. The layout picker doesn't explain what a layout is, nor does it indicate that the user is picking a layout _for their homepage_.

#### Steps to reproduce
1. Signup as a new user at horizon.wordpress.com/start/test-fse
2. Skip the domain step and start with a free site.
3. Reach customer home.
4. Click "Edit Homepage" in the first checklist item.

#### What I expected
To see my homepage, which I could then edit.

#### What happened instead
I'm shown a layout picker with no heading and no indication of what I'm picking a layout for.

#### Screenshot / Video
![EH1-EditHomepageSelectLayout](https://user-images.githubusercontent.com/1348738/69885790-ba1a4e00-1293-11ea-8a60-cff9c163d8aa.gif)

#### Potential solutions
![Screen Shot 2019-11-29 at 10 38 04 AM](https://user-images.githubusercontent.com/1348738/69886034-ea162100-1294-11ea-9441-b298840daaba.png)

**Comment by ianstewart** [comment]
@apeatling this isn't _currently_ an issue in the test-fse flow — because we have the theme step in there with an incomplete set of FSE themes. But, I think, if we're moving back to no theme-step … +1 on some variation of the above.

**Comment by davipontesblog** [comment]
Moved this to the Manage team board for review if this is applicable with the work being done on Customer Home and Checklists.

**Comment by davipontesblog** [comment]
No longer applicable with recent changes in new site creation and changes to the checklist - it now redirects to the Editor directly.
