### ISSUE TITLE
Layout Picker: headers in thumbnails aren't shown in preview

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38064]
In the layout picker, all of the thumbnails have headers, but the large preview doesn't have a header, which was the case for all of the themes I tried.

#### Steps to reproduce
1. Invoke the layout picker, either in the document sidebar; or by signing up as a new user in the test-fse flow and clicking "Edit Homepage" from the checklist
2. See previews with no header, next to thumbnails that all have headers

#### What I expected
Previews that match the thumbnails in content and structure

#### Screenshot / Video
![Screen Shot 2019-11-29 at 10 45 20 AM](https://user-images.githubusercontent.com/1348738/69886267-f64eae00-1295-11ea-9d42-bdfe64216879.png)

**Comment by iamtakashi** [comment]
This issue has been tackled here: https://github.com/Automattic/wp-calypso/issues/39352

We're changing the current mshots for the homepage layouts to static thumbnails that don't include the themes' headers.

**Comment by davipontesblog** [comment]
This is not an issue anymore, tested in a simple site with
Gutenberg: 8.3.0
CoBlocks: 1.23.0
wpcom-FSE: 131824367
![Screen Shot on 2020-06-18 at 08-21-42](https://user-images.githubusercontent.com/31009008/85019455-dd77ee00-b13c-11ea-8957-a27968cdecab.png)
Closing this issue.
