### ISSUE TITLE
Editor: Adding an image from a Pexels search doesn't actually add the image

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38067]
When adding a stock photo from the "Free photo library" in the Media Library, clicking "Insert" doesn't actually add/replace the image in the page. You have to go back to the Media Library and select the image from the WordPress library.

Even worse, if the user fails to notice that the image has been added to the WordPress library, and goes back to the Pexels search and finds/selects the same image, the same problem will occur, and a duplicate of that image will be added to the WordPress library.

#### Steps to reproduce
I saw this in a signup test when I first edited my homepage, but I was also able to reproduce on a test site just now.

1. Click the edit/swap button in the block controls on a cover or image block.
2. Navigate to the "Free photo library" search and find an image.
3. Select an image and click "Insert".
4. See the old image instead of the one you just selected.

#### What I expected
The new image to be inserted into my page.

#### What happened instead
Old image remains in place.

#### Screenshot / Video
![EH1-MediaLibraryDoesn'tInsert](https://user-images.githubusercontent.com/1348738/69886872-087e1b80-1299-11ea-9327-fff0dd5ccbd0.gif)

**Comment by apeatling** [comment]
Possibly related #31230

**Comment by ianstewart** [comment]
Also reported here: https://github.com/Automattic/wp-calypso/issues/38079

**Comment by iamtakashi** [comment]
This issue happens with featured images too. Adding a featured image from Pexels library requires opening the media library again and select the image added to the media library.

**Comment by zdenys** [comment]
As per pbAPfg-1z-p2#comment-94 it should not be happening anymore. I'll close this for now, but feel free to re-open.
