### ISSUE TITLE
Business and eCommerce Plan: View Plan Features link leads to the wrong location

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38076]
The View Plan Features link in account settings here …

![image](https://user-images.githubusercontent.com/545779/69887930-fdce8100-12ae-11ea-9a3f-25fb235ecf5e.png)

… leads to the Plans screen here …

![image](https://user-images.githubusercontent.com/545779/69887963-1b9be600-12af-11ea-9682-a1546d7bac01.png)

… and not the Plan Features screen here …

![image](https://user-images.githubusercontent.com/545779/69887982-31a9a680-12af-11ea-9522-f7f9c26b96a5.png)

**Comment by timmyc** [comment]
I verified the above on both the ecommerce plan, and the business plan - as such I think this possibly affects the link on all plans. As such I'm going to remove the ecommerce plan label here.

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.
