### ISSUE TITLE
Different button styles for "back" in template part editor and full editor

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38075]
The back buttons in the template part editor and the full editor are visually very different - the template part editor uses a standard button component, while the full editor uses a new icon + text button style. Should these use the same button style, or at least be more similar?

#### Steps to reproduce
1. Load up the FSE editor and note the "< Pages" button style at top left.
2. Edit the header and see the "Back to page" button at top left.

#### What I expected
Visually consistent button styling

#### Screenshot / Video
![Screen Shot 2019-11-29 at 11 44 46 AM](https://user-images.githubusercontent.com/1348738/69887804-a8d63f00-129d-11ea-99bf-fc68ff3ea3f7.png)
![Screen Shot 2019-11-29 at 11 42 24 AM](https://user-images.githubusercontent.com/1348738/69887813-b390d400-129d-11ea-8aa1-cacbf71850d2.png)
![Screen Shot 2019-11-29 at 11 42 59 AM](https://user-images.githubusercontent.com/1348738/69887814-b390d400-129d-11ea-9d14-158301599ff2.png)

**Comment by noahtallen** [comment]
cc @shaunandrews / @olaolusoga to see if we want to change this

**Comment by noahtallen** [comment]
(The last time this was discussed we decided not to change it)

**Comment by olaolusoga** [comment]
We should move forward and match pattern. 

Reasons:
- Consistency 
- If we moved forward with introducing the Icon + text pattern in the main editor, we should do the same in the header editor.

Suggestion on label:
- Back Icon + "Page Layout"
- Back Icon + "Layout"
