### ISSUE TITLE
Post-checkout and Customer Home: Strange Rendering with Flashing Confetti

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38074]
#### Steps to reproduce
1. Starting at URL: horizon.wordpress.com/start/test-fse
2. Checkout with the eComm Plan or Business Plan
3. Customer Home will start loading
4. Followed by a post-purchase "Confetti" graphic
5. Which will then disappear and be replaced by Customer Home

![image](https://user-images.githubusercontent.com/545779/69887726-fbb7f280-12ad-11ea-9fa9-d1090297ed0a.png)

![image](https://user-images.githubusercontent.com/545779/69887732-02df0080-12ae-11ea-8968-ece23445d581.png)

![image](https://user-images.githubusercontent.com/545779/69887739-0a9ea500-12ae-11ea-9ca6-2b08bac5aee9.png)

**Comment by davipontesblog** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/36557.
