### ISSUE TITLE
"Template part updated" message should be replaced with template part name

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38072]
When updating a header or footer in FSE, a toast at the bottom of the part shows "Template part updated". "Template part" isn't really customer-facing language - can we change this to say "Header updated" and "Footer updated", using the name of the template part that's being edited?

#### Steps to reproduce
1. Make some changes to the header in FSE
2. Click "Update"
3. See toast at bottom left of viewport

#### What I expected
"Header updated"

#### What happened instead
"Template part updated"

#### Screenshot / Video
![Screen Shot 2019-11-29 at 11 37 39 AM](https://user-images.githubusercontent.com/1348738/69887709-22216200-129d-11ea-8f5b-0f3aa7c7f66f.png)

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
