### ISSUE TITLE
Customer Home: Dual email verification checklist items

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38078]
We have competing email verification checklist items in the checklist …

![image](https://user-images.githubusercontent.com/545779/69888390-1b9ce580-12b1-11ea-9596-81f4200c6bec.png)

Verifying one's email will check both off, leaving only one completed item remaining …

![image](https://user-images.githubusercontent.com/545779/69888404-3f602b80-12b1-11ea-86a9-2cf92b172615.png)

To reproduce, purchase a domain in the horizon.wordpress.com/start/test-fse flow.

**Comment by davipontesblog** [comment]
Cannot replicate this issue, so closing for now.
