### ISSUE TITLE
Blog posts listing block hides settings until focused

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38077]
The blog posts listing block allows the user to customize the number of blog posts to be listed, but you wouldn't know it unless you select the block - the "Number of posts to show" control isn't shown until the block is selected. This might not be a problem when the user inserts the block themselves, but when a blog post listing is included in starter content, for example, there could be better affordance there.

The post count control doesn't make the block placeholder any taller, so...
- Could we just show the control by default?
- Could we add a description that hints that it's a setting, like "Number of posts to show: **5**"

#### Steps to reproduce
1. Add a Blog Posts Listing block to a page.
2. Deselect the block.
3. See only the "Your recent blog posts will be displayed here" message.

#### Screenshot / Video
![Screen Shot 2019-11-29 at 11 59 43 AM](https://user-images.githubusercontent.com/1348738/69888278-d58b5600-129f-11ea-89ed-70699adedd7e.png)
![Screen Shot 2019-11-29 at 11 59 55 AM](https://user-images.githubusercontent.com/1348738/69888279-d58b5600-129f-11ea-8b2f-7ddc2b3ea11b.png)

**Comment by davipontesblog** [comment]
I am closing this issue as this block has been replaced with the [Blog Posts block](https://github.com/Automattic/newspack-blocks) now.
