### ISSUE TITLE
Passwordless onboarding email copy contains random site title  

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38082]
I believe that passwordless onboarding was removed from the test-fse flow, but I'm reporting this for when/if it comes back. I went through the test-fse signup flow on Horizon and skipped domain and site title steps, which resulted in a random username and a random site title. Then I got an email with the subject line "Activate eaglecheeseelektra14872", which I think it likely to look like spam to real users - I know the intent is to personalize the email, but when we create something random, it's not personalized to the user at all.

In these cases, I think it might be better to make the subject line generic, ex. "Activate your new account".

#### Steps to reproduce
1. Launch a site with passwordless onboarding in test-fse (still possible?)
2. Get an email with a subject line containing a random username.

#### Screenshot / Video
![Screen Shot 2019-11-29 at 12 18 44 PM](https://user-images.githubusercontent.com/1348738/69888827-ca85f500-12a2-11ea-9e30-826129919c00.png)

**Comment by michelleweber** [comment]
+1, I'd go with "Activate your new WordPress.com account" to make it extra clear. Good call.

**Comment by obenland** [comment]
@dwolfe Is this still an issue or can the ticket be closed?

**Comment by dwolfe** [comment]
I assume this can be deleted, but I would check with @ianstewart to be sure.

**Comment by ianstewart** [comment]
We can close this one out. Thanks for the ping, @dwolfe.
