### ISSUE TITLE
Page Layouts: Not available on all themes

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#38081]
#### Steps to reproduce
1. Starting at URL: https://www.wordpress.com/themes
2. Click on "Show all themes"
3. Activate any theme on this section
4. Go to "Site > Pages"
5. Click on "Add New Page"

#### What I expected
To see the new page layouts picker, since this is released to all wpcom sites now.

#### What happened instead
The templates don't come up if you're using certain themes. I tested on my test site on Premium plan, test375739965.wordpress.com, and I tested the first 17 themes in our wpcom repo after the first template-first themes, and here is what I got so far:
- Yellow means it loads the page layout picker
- Red means it doesn’t

<img width="1206" alt="Screen Shot on 2019-11-29 at 14-31-20" src="https://user-images.githubusercontent.com/31009008/69889007-bf3fc300-12bc-11ea-8383-ba3fee7a302a.png">

**Comment by obenland** [comment]
The template selector is currently disabled for themes that register [legacy page templates](https://developer.wordpress.org/themes/template-files-section/page-template-files/).
See `maybe_disable_spt()` in mu-plugins on dotcom.

/cc @apeatling

**Comment by davipontesblog** [comment]
Update: It looks like this has been fixed - I am not seeing this behavior anymore in DotCom. I just tested this with Twenty Twenty, Lodestar, and Dara, and page layouts are coming up now :tada:

**Comment by obenland** [comment]
Apologies, I did not remember this ticket when we started working on it last week.
Yes, #39741 is the tracking ticket for these changes.
