### ISSUE TITLE
Replace generic browser dialogs with custom error messaging

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38087]
We use generic browser dialogs in a number of places, which limits our ability to offer solutions and forfeits an opportunity to provide a better designed experience.

I have two cases to hand:
- When trying to navigate away from a page that has unsaved changes, you get the generic warning from the browser that input is in danger of being lost. That seems like a use case that we should be handling explicitly, with an option to save right there in the dialog. Right now it looks like the browser is the only thing saving the user from losing work.
- The warning about "Switch to Draft" being a destructive-ish act is obviously a custom error, but using the default browser dialog makes it look undesigned. We can provide a better experience here.

We already have a modal component in WordPress components - is there a reason we're not using it here?

#### Steps to reproduce
- Click "Edit Header" in FSE with unsaved changes in the main page
- Click "Switch to Draft" on any published page/post

#### Screenshot / Video
![SystemDialog-SwitchToDraft](https://user-images.githubusercontent.com/1348738/69891363-eb554700-12b0-11ea-9817-745656b22631.png)
![SystemDialog-UnsavedChanges](https://user-images.githubusercontent.com/1348738/69891364-eb554700-12b0-11ea-9f72-33b88e09e3b8.png)

**Comment by davipontesblog** [comment]
Closing this as it's been marked as "Will be fixed by Gutenboarding & CoreFSE" in our [Experience Issues / 0-FSE project](https://github.com/Automattic/wp-calypso/projects/92#card-29928591).
