### ISSUE TITLE
"Your site will be ready shortly" messaging appears in cases where it may be confusing

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38089]
We use the "Hooray! Your site will be ready shortly" messaging in at least three places:
1. During initial free site creation, between plan selection and Customer Home
2. During free site launch, between plan selection and Customer home
3. During initial paid site creation, between plan selection and checkout

I saw it twice during the free site creation and launch process, which made me realize that it's a generic waiting message. Then I saw it between selecting a paid plan and the checkout screen, which made me wonder: what happens if I abandon checkout? Will my site still be ready shortly?

I wonder if it might be more useful to have either a more generic "one moment, please" message on this screen, so that we can use it anywhere we need it without creating an expectation. Maybe we can even provide a moment of delight with an animation.

Or, maybe we could make the messages more specific, and be more deliberate about where we use it. This is terrible copy, but "Loading your shopping cart" would make more sense in scenario #3 above. "Launching your site" would make more sense in scenario #2 above, and so on.

#### Steps to reproduce
- Select a free or paid plan during signup as a new user using the test-flow on Horizon
- Complete all the checklist items and click "Launch site"

#### Screenshot / Video
![HoorayYourSiteWillBeReadyShortly](https://user-images.githubusercontent.com/1348738/69891891-c236b580-12b4-11ea-8e8b-18fbadb1a167.png)

Creating a free site:
![EH1-HooraySiteCreation](https://user-images.githubusercontent.com/1348738/69891929-20639880-12b5-11ea-97eb-be72e29d2739.gif)

Signing up with a paid plan:
![EH2-HoorayYourSiteWillBeReadyShortly](https://user-images.githubusercontent.com/1348738/69891895-c4990f80-12b4-11ea-8fc2-52845ef04453.gif)

Launching a free site:
![EH1-HooraySiteLaunch](https://user-images.githubusercontent.com/1348738/69891973-89e3a700-12b5-11ea-8aa7-d02b2ff858da.gif)

**Comment by davipontesblog** [comment]
Closing this as it's been marked as "Will be fixed by Gutenboarding & CoreFSE" in our [Experience Issues / 0-FSE project](https://github.com/Automattic/wp-calypso/projects/92#card-29928591).
