### ISSUE TITLE
Site creation success message flashes briefly before checkout screen appears

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38091]
When selecting a paid plan in the test-fse flow, a site creation success message briefly flashed on the screen before the checkout screen loaded in. I didn't even notice during the actual signup, I only caught it during playback of the video.

There's a page skeleton below the messaging, so I'm guessing this is an interstitial waiting screen, but there were two additional loading screens immediately before this ("Hooray! Your site will be ready shortly." and a centered grey WordPress logo - see GIF below), so I'm not sure it's necessary for that reason. If the messaging is important, we should incorporate it into the checkout screen. If it's not, we should probably just remove it.

#### Steps to reproduce
1. Signup as a new user using the test-flow on Horizon
2. Select a paid plan on the plans screen
3. See "Your WordPress.com site is ready!" screen for a brief moment before checkout screen appears.

#### Screenshot / Video
![EH2-HoorayYourSiteWillBeReadyShortly](https://user-images.githubusercontent.com/1348738/69892231-3a52aa80-12b8-11ea-9633-73b3aad305f6.gif)
![Screen Shot 2019-11-29 at 2 55 54 PM](https://user-images.githubusercontent.com/1348738/69892250-6a01b280-12b8-11ea-90b8-92b7db0a10f9.png)

**Comment by davipontesblog** [comment]
Closing this as it's been marked as "Will be fixed by Gutenboarding & CoreFSE" in our [Experience Issues / 0-FSE project](https://github.com/Automattic/wp-calypso/projects/92#card-29928591).
