### ISSUE TITLE
Checkout screen still active while payment processing is in progress

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38094]
After you click/tap the "Pay $X" button on the checkout screen, the button disappears and a progress bar appears, but the screen is still live, meaning, the screen can still be scrolled, and form input can still be changed.

When the user clicks the button, this should either navigate to an interstitial screen or lock the checkout screen and show a scrim; with a progress bar and messaging (ex. "One moment while we process your payment").

#### Steps to reproduce
1. Signup as a new user using the test-flow on Horizon
2. Select a paid plan on the plans screen
3. Fill out the checkout details and click the "Pay $X" button
4. See button change into progress bar
5. Scroll up and change elements of the checkout form

#### What I expected
An interstitial screen; or a scrim + messaging over the checkout form, with form and scrolling disabled.

#### What happened instead
Page was still scrollable and form was still editable - only change was the disappearance of the Pay button, and the appearance of the progress bar.

#### Browser / OS version
(Desktop) Chrome w/dev tools open, iPhone X/XS emulator active

#### Screenshot / Video
![EH2-ProcessingPaymentProgressBar](https://user-images.githubusercontent.com/1348738/69892491-d7164780-12ba-11ea-8c4a-3ff3afd6c076.gif)

**Comment by davipontesblog** [comment]
Leaving this open so the Checkout team can check if this is still applicable to the new Checkout redesign flows.

**Comment by sirbrillig** [comment]
👍 This is fixed in the new checkout. We should probably still leave it open for now since it's technically not fixed in the old checkout, which is still live. Hopefully the old checkout will be replaced soon and this can be marked as complete.

**Comment by davipontesblog** [comment]
@sirbrillig is there a PR we can link here to close once merged?

**Comment by sirbrillig** [comment]
🤔 Not really. ... I guess the question is: this issue is for the old checkout and does not apply to the new checkout, so if we're not going to fix it, should we just close the issue? Or should we keep it around until the new checkout completely replaces the old? As much as I hate closing issues that are valid, I'm starting to be inclined to pick the former option particularly since it's very possible that we'll forget to close this when the new checkout is complete. What do you think?

**Comment by davipontesblog** [comment]
I agree we should close it in favor of the new checkout experience. Closing it now :)
