### ISSUE TITLE
Position mobile help popover closer to bottom of screen

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38092]
On mobile web, the help popover appears at the top of the screen, which is both far away from the button that spawned it, and far away from thumb range. Could we just position this window as we do on desktop, just above the help button with a caret pointing to the button? That would be an ergonomic improvement, and also create a stronger association with its trigger.

#### Steps to reproduce
1. Visit a Calypso or editor page on mobile web
2. Tap help button in bottom right
3. See help window appear at top of screen

#### Screenshot / Video
![Screen Shot 2019-11-29 at 3 03 38 PM](https://user-images.githubusercontent.com/1348738/69892369-9d910c80-12b9-11ea-97c7-fbc499658b27.png)
![EH2-MobileHelpButton](https://user-images.githubusercontent.com/1348738/69892373-a255c080-12b9-11ea-8d28-755888ccf97d.gif)

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.

**Comment by gwwar** [comment]
Could reproduce!

**Comment by Aurorum** [comment]
PR in #40386 for this issue. :)

<img width="371" alt="Screenshot 2020-03-24 at 08 31 48" src="https://user-images.githubusercontent.com/43215253/77404802-2ae8f700-6daa-11ea-9b59-239aa0b599cf.png">
