### ISSUE TITLE
No confirmation of successful purchase during signup

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38096]
After completing checkout with a paid plan (I was testing on mobile web, but I don't believe this issue is limited to mobile), the user is taken to the FSE editor with no confirmation/success message about the transaction they just completed, nor a receipt or a link to a receipt. (There isn't any messaging about next steps either, but a ticket for that already exists: https://github.com/Automattic/wp-calypso/issues/38058)

This information should be combined with the solution to the ticket above, but we should give the customer some indication that their purchase was successful, and advise them how to find a record of that transaction (ex. tell them that they'll receive an email with their purchase details, and maybe point them towards their billing history).

#### Steps to reproduce
1. Signup as a new user using the test-flow on Horizon
2. Select a paid plan on the plans screen
3. Complete checkout
4. See site loaded in FSE with no confirmation of purchase success (or failure, but hopefully that generates an error)

#### What I expected
A receipt? A confirmation message?

#### What happened instead
Nothing - site loads into FSE

#### Browser / OS version
(Desktop) Chrome w/dev tools open, iPhone X/XS emulator active

#### Screenshot / Video
![EH2-CheckoutNoSuccessMessage](https://user-images.githubusercontent.com/1348738/69892905-5a399c80-12bf-11ea-9835-0990c8b7d2db.gif)

**Comment by ianstewart** [comment]
This might be a wontfix? I think this issue is from the time when the time test flow exited the signup. @apeatling?

**Comment by davipontesblog** [comment]
Closing this as it's been marked as "Will be fixed by Gutenboarding & CoreFSE" in our [Experience Issues / 0-FSE project](https://github.com/Automattic/wp-calypso/projects/92#card-29928591).
