### ISSUE TITLE
Mobile app promo flashes onscreen while loading into FSE from public site

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38098]
Saw a promotional banner flash onscreen while loading into FSE from viewing a live site. See GIF below.

#### Steps to reproduce
1. Setup a test site in FSE with Maywood layout and Maywood theme active
2. From Calypso left menu header, click site title/domain, then click "Visit site" button
3. Scroll down to bottom and click "Edit" at top of footer
3. See promo banner flash at the bottom of the screen as FSE loads in

#### Browser / OS version
(Desktop) Chrome w/dev tools open, iPhone X/XS emulator active

#### Screenshot / Video
![EH2-FlashOfMobilePromo](https://user-images.githubusercontent.com/1348738/69893919-0df55900-12cd-11ea-9507-4d496b0e7971.gif)

**Comment by davipontesblog** [comment]
Closing this in favor our implementation of core FSE in WordPress.com.
