### ISSUE TITLE
Purchases: Google Apps: No refund on cancellation

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3810]
I cancelled a Google Apps account that I registered 5 minutes ago and it didn't give me a refund, I think our refund policy is at 30 days for the first license in a domain, but no refunds for the additional licences.

**Comment by fabianapsimoes** [comment]
You mean you didn't get a refund for the first license? I just tested this and I got a refund just fine. After cancelling through purchase, I was sent an email to confirm the cancellation and then got my refund.

**Comment by spncrb** [comment]
I also received a refund right away when testing - either this was resolved in another PR, or has very specific requirements to reproduce.  

@umurkontaci  if you can still produce this bug, please add more detailed instruction on how - otherwise I'm going to close it.
