### ISSUE TITLE
Private by Default atomic upgrade

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#38110]
## Goal

We've improved a private-to-atomic upgrade process a little bit. There is still some way to go as seen in the following figma file: 233b7-pb

## Tasks

https://github.com/orgs/Automattic/projects/92?card_filter_query=label%3A%22pbd+interim+fix%22

## Related links:
* p9jf6J-2f4-p2
* paObgF-I3-p2

**Comment by adamziel** [comment]
@jancavan On Figma the checkout "thank you" page has a few changes:

1. It communicates the site has been launched
2. It doesn't have "What now?" and "Priority support" sections.

Is your intent to only apply these changes to the "thank you" page that's visible after the business plan checkout via plugins/themes page? Or should we remove "What now?" and "Priority support" for all the checkout pages for all plans?

**Comment by adamziel** [comment]
I just created https://github.com/Automattic/wp-calypso/pull/38139 to bring us one step closer

**Comment by jancavan** [comment]
> Still I wonder if there's a value in removing "What now?" and "Priority support" for all the checkout pages for all plans?

Oh sorry for the confusion @adamziel. when I said "ALL", I meant "all blocks/cards" but _only for this particular flow_, not for "all plans". Meaning, those who upgrade to Business from this flow.

The post-purchase screen does need to be cleaned up for other plans and flows, but that should be handled separately.

**Comment by davipontesblog** [comment]
Closing this as per the activity above.
