### ISSUE TITLE
0–FSE Post-Launch Home: Remove Change Theme from Site Tools?

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38126]
**Current status:** 

![image](https://user-images.githubusercontent.com/545779/69996079-f0b3cb00-1516-11ea-950f-1c089a662822.png)

The 0–FSE flow encourages one to pick a design early on, make edits, and then launch their site. We also discourage exploration of the Theme Showcase in that flow by explicitly hiding older themes and implicitly with Themes under that collapsed Design menu in the sidebar.

Post-launch we're explicitly encouraging that exploration — which will potentially undo much of the gains from the pre-launch flow.

Should we hide or replace that item? I might suggest replacing it with "Edit Homepage" and removing the My Site card on the top right as users will have learned that they can see their whole site in the Block Editor _and_ preview the front end of the site from there as well.

**Comment by davipontesblog** [comment]
I am not sure if this is relevant in the context of not testing FSE in dotCom anymore. I believe Gutenboarding will fix this with new sites, and this "Change Theme" tile might still be relevant for existing sites. Leaving it in the Manage board for further discussion and explorations.

**Comment by gwwar** [comment]
I don't think we can remove this for now until FSE is available.
