### ISSUE TITLE
Hosting Config: The site selector should only display capable sites.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#38127]
When a user goes directly to `https://wordpress.com/hosting-config`, they're presented with the site selector. However, the selector displays all of the user's sites, not just those that could be sites qualified for hosting. The list should be filtered to Atomic sites created after October 30, 2019.

**Comment by gwwar** [comment]
Note that work in https://github.com/Automattic/wp-calypso/milestone/289 may change logic around which sites are displayed in the site list

**Comment by kwight** [comment]
> Note that work in https://github.com/Automattic/wp-calypso/milestone/289 may change logic around which sites are displayed in the site list

Good point – I'll make any PR dependent on #38155, meaning this should just filter out VIP and Jetpack sites.
