### ISSUE TITLE
Zero to FSE: Remove G Suite from Post-Checkout Flow and Pre-Launch Home Screen

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38122]
Current experience …

![image](https://user-images.githubusercontent.com/545779/69993415-62891600-1511-11ea-892e-9a6cdaaa85aa.png)

This screen appears immediately after checking out in signup before you've even seen your site and had a chance to edit it.

Additionally, after skipping that screen, the Business Plan user with a domain then sees the following on their home screen …

![image](https://user-images.githubusercontent.com/545779/69993677-ed6a1080-1511-11ea-8cca-a80bbcde40a0.png)

A large banner obscuring the primary action (completing the checklist, launching your site) that we want the customer to take.

**Suggestion:**

- We remove the GSuite screen from the Post-Checkout flow
- And remove the large banner (or any large banner) from the checklist home screen
- and potentially re-introduce GSuite as a Checklist Task item for Domain Purchasers ("Add Professional email with GSuite to your new domain"?)
- or simply as this already existing card that would appear on the home screen _after_ launching one's site.

**Comment by ianstewart** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/37272

**Comment by ianstewart** [comment]
This issue may be more like, "Controlling the pace of upsell notices prior to launching a site". On the same test site, after dismissing the gSuite notice on the home screen the following notice appeared _after_ I verified my email but _before_ I launched my site.

![image](https://user-images.githubusercontent.com/545779/69995741-476cd500-1516-11ea-8336-42c10c043f0d.png)

**Comment by davipontesblog** [comment]
@ianstewart I think this one can be closed, what do you think?

**Comment by ianstewart** [comment]
With Zero to FSE stopped as a project and the Onboarding project gaining steam, yeah. Closing!
