### ISSUE TITLE
0-FSE: FSE Header Template Style Issues

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38124]
There are a few issues with the Shawburn Header Template in the FSE test flow …

**Current Status:**

![image](https://user-images.githubusercontent.com/545779/69994352-543bf980-1513-11ea-95c0-6031401fc0ea.png)

Vertical margins/padding/line-height on Title and Tagline not matching up (live demo of the theme on the right) …

![image](https://user-images.githubusercontent.com/545779/69994425-7a619980-1513-11ea-946d-18a0d7dd6c63.png)

Social media menu links have a different size and colour and are too close to the horizontal page menu …

![image](https://user-images.githubusercontent.com/545779/69994497-9b29ef00-1513-11ea-81ed-ed9e6106c4bf.png)

Page menu missing current menu item styles (the home link is the wrong colour) … 

![image](https://user-images.githubusercontent.com/545779/69994544-b4cb3680-1513-11ea-81c2-7f310dfcbe33.png)

The block below the horizontal menu is too far below the menu …

![image](https://user-images.githubusercontent.com/545779/69994584-c7457000-1513-11ea-90f3-75f5b152deff.png)

**Comment by ianstewart** [comment]
Additionally, the social menu styles change when one enters the template editor …

![image](https://user-images.githubusercontent.com/545779/69995189-425b5600-1515-11ea-98ad-bffc156c0d8e.png)

The Site Title is now too close to the top of the template, and the social menu is now spaced differently (if better) relative to the horizontal menu.

**Comment by ianstewart** [comment]
Updating the issue title to be more generic for the header templates, regardless of active theme. Similar issues are present in Exford …

![image](https://user-images.githubusercontent.com/545779/70067044-505fb400-15b3-11ea-8771-9cb6344deb69.png)

**Comment by ianstewart** [comment]
There's also some title and tagline disparity in Maywood as well …

![image](https://user-images.githubusercontent.com/545779/70067279-a59bc580-15b3-11ea-8c0c-243145e4a8b9.png)

**Comment by apeatling** [comment]
I don't think we are going to be able to fix many of the issues you've found here without further Gutenberg improvements and access to margin/padding support. We can improve the front-end rendering of spacing, but matching in the editor is almost impossible until more work is done on editor controls that do not add extra space.

**Comment by apeatling** [comment]
Shawburn needs a bunch of front end work, I can look at that today.

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
