### ISSUE TITLE
Page Layouts: GDPR Notice in Template Screenshots

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38125]
It looks like our template screenshots are displaying the GDPR notice …

![image](https://user-images.githubusercontent.com/545779/69994893-8863ea00-1514-11ea-9509-66f828d1311f.png)

**I expected:**

To have a "clean" screenshot of the design.

**Comment by obenland** [comment]
Duplicate of #39669. Fixed in D39336-code.
