### ISSUE TITLE
Checklist: Define Complete/Skip pattern

### ISSUE THREAD

**Issue by lcollette** [Automattic/wp-calypso#38132]
On Customer Home, we need to update the design pattern for interacting with (start/skip) and completing tasks in the task list. 

 
![Screen Shot 2019-12-02 at 3 02 03 PM](https://user-images.githubusercontent.com/181733/70002383-ba754c00-1514-11ea-9350-0f171366deb8.png)

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.
