### ISSUE TITLE
[PBD interim fix] Redirect back to /themes or /plugins if users empty their cart

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#38144]
Related to PBD interim fix epic https://github.com/Automattic/wp-calypso/issues/38110

**Goal**

Improve redirection logic for users checking out the business plan with intention to install plugins or themes. Currently, when they empty their card, they are taken back to /plans. Let's take them back to where they came from instead:

<img width="726" alt="Zrzut ekranu 2019-12-3 o 15 40 57" src="https://user-images.githubusercontent.com/205419/70060766-6e450d00-15e3-11ea-8731-02c416e08bf7.png">

**Links**
* Figma file 233b7-pb
* paObgF-I3-p2

**Comment by andrewserong** [comment]
Just unassigning myself from this one since I'm going on AFK. If anyone would like to pick this one up, it's ready for review in: https://github.com/Automattic/wp-calypso/pull/38232
