### ISSUE TITLE
FSE: Confirmation modal style seems a little off?

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#38146]
I'm not up to date on the WordPress components, so if this is the style that follows the guideline, feel free to close :)

The confirmation modal style seems to be a bit off especially the button's alignment.

<img width="381" alt="Screenshot 2019-12-03 at 15 42 10" src="https://user-images.githubusercontent.com/908665/70066651-f1b32e00-15e4-11ea-96f9-31f8994cc9ad.png">

**Comment by Aurorum** [comment]
PR in #39478 for this issue. :)
