### ISSUE TITLE
Starter Content: A missing image in "My First Blog Post"

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#38145]
The cover image is missing in one of the posts in the starter content for the blog segments. It has probably been deleted from the vertical master site at some point.

https://redboxtravel.wordpress.com/2019/11/29/example-post/

**Comment by rickybanister** [comment]
@iamtakashi @ianstewart could you confirm whether we fixed this at any point or see if a fix is possible?

**Comment by ianstewart** [comment]
Technically now an invalid issue since that content is no longer used anywhere. Can be closed.
