### ISSUE TITLE
error install wp-calypso on localhost

### ISSUE THREAD

**Issue by Mifan168** [Automattic/wp-calypso#3815]
I try using wp-calypso, and i get error when i install it

i get 

```
npm ERR! tar.unpack unzip error /tmp/npm-26068-ee1e0147/registry.npmjs.org/babel-core/-/babel-core-5.8.12.tgz
npm ERR! tar.unpack untar error /tmp/npm-26068-ee1e0147/registry.npmjs.org/babel-core/-/babel-core-5.8.12.tgz
npm ERR! Linux 3.19.0-51-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.8.0
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/lampstack/apache2/htdocs/wp-calypso/npm-debug.log
make: *** [node_modules] Error 251
```

can you help me?

**Comment by lamosty** [comment]
Hey Mifan168,

looks like [npm](https://www.npmjs.com/) is not able to unzip/untar [babel-core](https://www.npmjs.com/package/babel-core) (which is required to run Calypso locally).

Try running 

```
npm cache clean
```

in your terminal/command line app. That should [delete data out of the cache folder](https://docs.npmjs.com/cli/cache). Then, try running 

```
make run
```

again. Please report back if it works/doesn't work.

**Comment by Mifan168** [comment]
i get this code 

`
npm WARN deprecated babel-core@5.8.12: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated jade-lexer@0.0.9: Replaced by pug-lexer
npm WARN deprecated jade-runtime@2.0.0: Replaced by pug-runtime
npm WARN deprecated jade-runtime@1.1.0: Replaced by pug-runtime
npm WARN deprecated jade-attrs@2.0.0: Replaced by pug-attrs
npm WARN deprecated jade-error@1.2.0: Replaced by pug-error
npm ERR! Linux 3.19.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! shasum check failed for /tmp/npm-14569-d3bdc71f/registry.npmjs.org/babel-core/-/babel-core-5.8.12.tgz
npm ERR! Expected: dd4b8a225a77675a66e167592b3a4119ea24a9a8
npm ERR! Actual:   f5a25ce7db6dca43158dfa20e79c924d305afd9e
npm ERR! From:     https://registry.npmjs.org/babel-core/-/babel-core-5.8.12.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/mifan/58ce7c03-1ce7-4498-8026-7650ad9d8b26/Project In Action/coba/wp-calypso/npm-debug.log
make: *** [node_modules] Error 1
`

**Comment by lamosty** [comment]
Thanks for the error report. Unfortunately, not much can be deduced from it. Could you copy-paste the `/media/mifan/58ce7c03-1ce7-4498-8026-7650ad9d8b26/Project In Action/coba/wp-calypso/npm-debug.log` file? It's a more verbose log file, which could help.

**Comment by Mifan168** [comment]
it huge if i write list of code in this line, please download my npm.debug.log file at 
`https://www.dropbox.com/s/8ffrh17jciuevd0/npm-debug.log?dl=0`
thanks for your help, mr lamosty

**Comment by Mifan168** [comment]
Dear Sir,

i update a whole of my npm & packages, it works very well
thanks for your help, mr lamosty

**Comment by lamosty** [comment]
Oh cool, I'm glad it works for you Mifan. :)

Have a nice day.
