### ISSUE TITLE
Remove checklist nudge from stats

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#38172]
### Steps to reproduce
URL:ddimages.org

![Annotation on 2020-01-19 at 14-38-45](https://user-images.githubusercontent.com/1270189/77364072-1147a100-6d11-11ea-9491-32c070b1a13a.png)

SUMMARY:
* Last week the user said the checklist in MyHome was complete at 100% of the setup tasks.
* Now it says 67%.
* My home option is also coming and going in their dashboard.

ACTION:
* I checked the site during HC and saw it showed 67% too.
* When I checked later for a followup ZD there was no checklist for me - https://d.pr/i/A4BC3v
* The user replied back to say it is still visible for them 
* By using the following link I can see the checklist (but not the percentage). https://wordpress.com/checklist/ddimages.org
* The checklist indicates the site is indeed not complete and the home page needs fixing
* However the home page of the site is set to show the latest posts.  There is no content on the home page itself.
* The site was created on 2019-06-08 which looks to be the exact date the feature was being applied to sites from.

#### What I expected
To see My Home and see the % completed
Not see 67% remaining when the site was set to show blog posts on the front page

2537191-zen

**Comment by JessBoctor** [comment]
A report of a similar bug in 18025604-HC. 

Customer's site setup is complete but it shows 0%. The banner is constantly reappearing, even though the customer closes it. 

Screenshot here: https://d.pr/i/O5XWqZ

**Comment by davipontesblog** [comment]
Moving this to the Manage board for consideration.

**Comment by gwwar** [comment]
Updated issue to remove this nudge completely
