### ISSUE TITLE
Billing History: Redundant navigation on mobile

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#382]
When viewing me/billing, the section nav becomes a drop-down menu. However, because it has only one item, it's redundant.

Here's what it looks like:

![screen shot 2015-11-21 at 9 09 11 am](https://cloud.githubusercontent.com/assets/11487924/11318826/99d1bdda-902f-11e5-9d0a-c0fa2addde7b.png)

![screen shot 2015-11-21 at 9 09 18 am](https://cloud.githubusercontent.com/assets/11487924/11318827/9bf14ca2-902f-11e5-8fe2-3456c2d810ab.png)

**Comment by hoverduck** [comment]
Looks like now there are two entries in the list, Purchases and Billing.  Closing issue.
