### ISSUE TITLE
Gutenberg: editor preferences request may fire with a null siteId

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38220]
During editor load at WordPress.com/block-editor we sometimes notice an invalid request of:

`https://public-api.wordpress.com/wpcom/v3/sites/null/gutenberg`

This is caused by an early event being dispatched with a missing siteId

<img width="891" alt="screen_shot_2019-12-05_at_11 27 03_am" src="https://user-images.githubusercontent.com/1270189/70267180-c5b5bb00-1752-11ea-9deb-f2222f541fbf.png">

The data-layer then fires this bad http request, and then retries 3 times since it'll come back with an error repsonse

https://github.com/Automattic/wp-calypso/blob/57261aa3f0b3398e720a6ae91a6c03b88028e62c/client/state/data-layer/wpcom/sites/gutenberg/index.js#L25

Let's make sure components do not dispatch bad `EDITOR_TYPE_REQUEST`s!

**Comment by noahtallen** [comment]
This can also happen accessing other pages in Calyps, like `/pages/url`.

For example, on my test site we see that the site ID is null and that Calypso does not load at all (in fact, it reloads and fails again with the retry query param)

<img width="1680" alt="Screen Shot 2019-12-05 at 7 11 24 PM" src="https://user-images.githubusercontent.com/6265975/70267417-55308d80-1796-11ea-9b4a-48f96702870c.png">
