### ISSUE TITLE
Help: Chats not starting properly when using ? help icon

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#38228]
Chats are not starting properly when launched via the "?" help icon at the bottom right of WordPress.com.  Chats started via https://wordpress.com/help/contact work just fine.

When a user initially sends in their message, the help box disappears completely and a chat is not started.  The user must click on the icon again and choose the contact option to start the chat.

Reported internally and it doesn't appear to be an issue with the chat service itself. 

I've reproduced this across Firefox, Chrome, and Safari so it looks like it may be having a decent impact on new support requests.

Each time, I have to click the "?" again, click on Contact Us, and click on Chat. Refreshing clears this and starts the process over again.  

#### Steps to reproduce
1. Login to WordPress.com
2. Select a site with a plan that includes live chat support during the hours you are testing.
3. Click the "?" help icon on the bottom right and attempt to initiate a chat.

#### What I expected
* For chat to start normally after the first message attempt. 

#### What happened instead
* The help box disappeared.

#### Browser / OS version

* Latest Chrome, Firefox, and Safari on macOS 10.15.1

#### Screenshot / Video

* https://d.pr/v/XkLSUh

#### Context / Source

* User report and reproduced across multiple browsers.

* 89855-hc

* Re: p1575581937226200-slack-happychat

* Shared in p1575585825162200-slack-calypso, p1575585968232500-slack-wpcom-happy-announce, and p1575587006090800-slack-automattic

 #reallife #dogfooding

**Comment by samiff** [comment]
Reproduced from normal WPcom account w/out proxy, Firefox v71.0
12515466-hc

**Comment by lancewillett** [comment]
Thanks for the report. Adding high priority label.

**Comment by lancewillett** [comment]
@JoshuaGoode Do you have a general sense (or exact details, if possible) of when this started happening?

**Comment by JoshuaGoode** [comment]
@lancewillett Regarding when it started, a user first expressed their frustrations to me at 21:25 UTC
To tell when it appears to have really begun, we may be able to take a look into our support stats to find a dip in new interactions but that may be difficult to decipher.

The only console error I initially found was entry-main.7634e5c5f91baae056c8.min.js:2 Uncaught TypeError: Cannot read property 'clientHeight' of null after attempting to start a chat. 

Immediately reproduced in Safari, Chrome, and Firefox across various Calypso pages including Stats, Plan, Site > Pages.

**Comment by lancewillett** [comment]
Thanks for the info! I wasn't able to reproduce in Firefox, myself — but yes in Chrome and Safari. Using a non-a11n user, not proxied.

The related change looks to be 8 days old... any chance it's been broken longer than just today?

**Comment by lancewillett** [comment]
Testing a revert here: https://github.com/Automattic/wp-calypso/pull/38229

**Comment by beaucollins** [comment]
Revert has resolved the problem.

**Comment by lancewillett** [comment]
Props @beaucollins for your quick fixes along with @aidvu 

Thx @kwight for helping out as well

Good job @JoshuaGoode for the report and help to raise the alarm.
