### ISSUE TITLE
Customizer: Widget visibility settings showing incorrect setting after selection

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#3824]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize/
2. Click on Widgets and add any widget to a widget area visible in the preview
3. Click the Visibility button, and select any visibility option.

#### What I expected
After selecting `Show` if `Page` is `Archive` I expected the Archive option to be visible.

#### What happened instead
Instead, the selected option was only visible for a brief time before disappearing again. The setting was correctly applied (in browser Customizer, NOT in desktop app Customizer), but it wasn't visible in the widget. Clicking `Save and Publish` made no difference.

Refreshing the Customizer completely caused the selected option to appear, but now if I tried to change an option, it would revert back to Archive each time the preview window updated to the new setting.

#### Browser / OS version
Tested in Firefox and Chrome in Windows 7 and Mac OSX, as well as the desktop apps on those platforms.

#### Screenshot / Video
![widget visibility](https://cloud.githubusercontent.com/assets/11873759/13570168/41baa2b6-e475-11e5-8348-98f5217d267e.gif)

This was reported in 327196-chat. This bug makes it very difficult for users to confirm widget visibility settings, or to make changes to these settings. This feature works as expected in WP-Admin.

**Comment by lancewillett** [comment]
I don't think this is specific to Calypso UI — it's a bug in WP.com if you launch the Customizer from anywhere. Closing in favor of #7727-wpcom.

**Comment by lancewillett** [comment]
This should be fixed with r135253-wpcom.

**Comment by formosattic** [comment]
Still a small kink, what happens now: upon clicking on the Visibility button, and selecting a visibility option, the selected option doesn't stick in the Customizer interface.

The visibility option actually gets saved (checked in WP-Admin > Appearance > Widget, or by refreshing the page and opening the Customizer again), but it's just not sticking while the user is configuring it in the Customizer, hence, giving the impression that the setting isn't saved at all.

What I've noticed too, when selecting a visibility option:
- if a visibility option **wasn't** previously selected, the option will display the option a the top of the list (illustrated below with the widget Archives, which I'm setting to Category "Weekly", but goes back to "All Category Pages")
- if a visibility option **was** previously selected, the option will switch back to the previous selected option (illustrated below with the widget Search, which I'm setting to Category "Uncategorized", but goes back to "Weekly"))

See animation (wait after Save & Publish, as the page is getting refreshed):
![widget-visibility](https://cloud.githubusercontent.com/assets/15944096/15774239/eb7bd630-29ad-11e6-9774-181061da15db.gif)

**Comment by starxedsteph** [comment]
User reported this issue in 405290-chat

The user is setting three visibility options for specific pages. In this case, only one of the pages selected is saved and the remaining two are saved as having no page selected. The result is that the widget displays on all pages.

I have replicated this on my test site.

Preview of WP-Admin > Appearance > Widgets after adding visibility options through the customizer for three pages:
<img width="406" alt="screen shot 2016-06-24 at 6 55 42 am" src="https://cloud.githubusercontent.com/assets/11230557/16337183/f704fabe-39d8-11e6-81f5-8fd2d2eada00.png">

**Comment by lancewillett** [comment]
Please comment further on 7727-wpcom if you have notes — this is not specific to Calypso.
