### ISSUE TITLE
Hosting: remove SFTP siteId restriction

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38258]
Let's prepare a client and server diff to remove the siteId restriction. This will allow any sites with a Business+ plan to access SFTP and phpMyAdmin

- [x] Client Diff
- [x] Server Diff
- [x] Prepare to land not before Dec 9
- [x] Update related support docs: https://en.support.wordpress.com/sftp/ https://en.support.wordpress.com/phpmyadmin-and-mysql/

**Comment by kwight** [comment]
Client PR: #38261
Server diff: D36402-code

**Comment by kwight** [comment]
All deployed, and docs are updated.
