### ISSUE TITLE
Promotions under Store lead to empty page when coupons are not enabled

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#38262]
#### Steps to reproduce
1. Log in to an Atomic site that has WooCommerce installed
2. Go to WP-admin → WooCommerce → Settings 
3. Uncheck the "Enable the use of coupon codes" option for "Enable coupons"
4. Save page
5. Go to Calypso → Store → Promotions

#### What I expected
The page should show any promotions that have been set up.

#### What happened instead
The page doesn't load any **product sales** that have been set up through this page. This is not related to coupons at all, so the "Enable coupons" setting should not have an impact on that.

#user-report

**Comment by senff** [comment]
Also reported in #2128292-HC

**Comment by eduardozulian** [comment]
On top of that, if coupons are disabled and you try to add one from Store, you'll get an error:

```
There was a problem saving the promotion
```

23294319-hc

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
