### ISSUE TITLE
FSE: No way to add certain widgets (Instagram, Twitter, Facebook)

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#38263]
FSE removed the functionality to add widgets to a widget area. The issue is that all widgets aren't available to be added as blocks, so they can't be used on a FSE site. Instagram, Twitter, Facebook all have embed blocks for example, but these don't embed the feeds. There is no Instagram feed block we can use (the same is true for any widget that doesn't have a block).

#### Steps to reproduce

For example, using the Maywood theme on a non-FSE site you can add the Instagram feed widget to a footer widget area.

![img](https://d.pr/i/SFBs87+)

The same theme on FSE has the widget area disabled:

![img](https://d.pr/i/UKXoq1+)

There is no Instagram feed widget block (only the embed):

![img](https://d.pr/i/Gq70V0+)

You can access the footer widget area by manually going into wp-admin:

![img](https://d.pr/i/0cUHde+)

However widgets added here do not display on the site.

If the FSE themes could display the footer widget area if we manually add widgets that could be a temporary solution until these blocks are added.

#### Context / Source

Reported 17150779-hc

**Comment by philnick206** [comment]
I have another reported example of this issue.

2617517-zen

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
