### ISSUE TITLE
Themes: 'Show all' link not functioning

### ISSUE THREAD

**Issue by samjhamdy** [Automattic/wp-calypso#38272]
#### Steps to reproduce
1. Starting in Calypso Themes panel, scroll down and click Show All Themes
2. Click on a filter (e.g. Subject)
3. Click on 'Show all' link at right

#### What I expected

Full filter list should be displayed

#### What happened instead

Nothing

#### Screenshot / Video

https://d.pr/v/kFHu4i

password: 9LnG6sVcCJ

#### Context / Source

We'd also love to know how you found the bug: #user-report

**Comment by noahtallen** [comment]
cc @Addison-Stavlo

**Comment by Addison-Stavlo** [comment]
Thanks for pointing this out @samjhamdy !  I am not sure how/when this got broken, the error was totally unrelated to other changes that I have seen made recently.  Nevertheless, we have a PR with a working fix in review.
