### ISSUE TITLE
Signup: Adding a new site to an existing WP.com account doesn't work immediately after creating a site

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#38287]
#### Steps to reproduce
1. Starting logged out at URL: https://wordpress.com/
2. Sign up for a new account and site, ending up at URL: https://wordpress.com/home/SITE_ADDRESS
3. In the sidebar, select "Add new site."
4. Under "Create a shiny new WordPress.com site" select "Start Now."

#### What I expected

I expected to be taken to https://wordpress.com/start/site-type?ref=calypso-selector where I could begin the site creation flow (similar to the first site I created).

#### What happened instead

I was taken to https://wordpress.com/start/site-type?ref=calypso-selector with the message "Hooray! Your site will be ready shortly." No site was created.

If you confirm your new account email address and try again to add a new site, after "Start Now" it will work as expected.

#### Browser / OS version

Chrome 78.0.3904.108 / macOS 10.15.1

#### Screenshot / Video

![add-new-site](https://user-images.githubusercontent.com/8658164/70439970-0b42f280-1a89-11ea-9a26-9b5342b4a9ca.gif)

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
@Automattic/start-dev @johnHackworth Heads up about this very broken flow for users with unconfirmed email addresses.

I see a similar (although not identical) issue when I try to add a new site on my a8c account, but with any non-a8c account I tested I saw the results reported above.

**Comment by adamziel** [comment]
It's happening when you try to create a second site without refreshing a page. This isn't related to email confirmation - it's just page refreshing that solves the problem.

**Comment by jblz** [comment]
I really don't know if this is related, but it might be, so thought I'd mention it here:

Eslint flags the `start` signup page.js controller function as being [at risk for race conditions](https://eslint.org/docs/rules/require-atomic-updates) when we set the `context.primary` componet here:

https://github.com/Automattic/wp-calypso/blob/177aea017157bcb15e8f6f09b713e573b810e4cb/client/signup/controller.js#L167

As far as I can see, this is the only such function in our codebase that uses async / await, so I wonder if the way we're loading the step chunks isn't somehow involved:

https://github.com/Automattic/wp-calypso/blob/d1be047e543cb010e05a56fd1db25b038e749c51/client/signup/config/step-components.js#L66-L72

**Comment by ramonjd** [comment]
I haven't confirmed, but it might also be related to https://github.com/Automattic/wp-calypso/pull/36047, in which we had to clear the signup progress state to prevent something _very_ similar.
