### ISSUE TITLE
Support contact form: No "Site I need help with" indicated for free users

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#38280]
Related to #16015

When free users submit a support request via https://wordpress.com/help/contact, one of two things happen: They get routed to our Expert User support using the service, DIrectly (90% of support requests currently), or it gets posted to https://en.forums.wordpress.com/, with the account's primary site automatically indicated as the site they need help with, and the tag `wpcomhelp` added to the thread.

As of Friday we've noticed a sharp increase of forum threads being created in this way where the primary site is no longer included, even though the user owns a WordPress.com or Jetpack-connected site that is correctly set as the primary site in the account. This makes it difficult to provide support, as there's nothing indicating to volunteers what site someone needs help with, and requires staff to access our internal tools to see what sites a user owns, leading to extra back and forth communication to confirm the nature of the issue and sites involved.

#### Steps to reproduce
1. Log into an account only owning sites on the free plan (I can reliably replicate this on the test account with the username `boogeedeeboo`
2. Go to the support contact form at https://wordpress.com/help/contact
3. Provided the Submit button says "Ask in the forums", fill out the title and content fields and submit. (If the button lets you submit a ticket, it means the user is being rerouted to Directly support. I'm not sure how to force the request to be routed to the forums)
4. Check the post that is created for the user in the forums.

#### What I expected
For the user's primary site to be indicated as the "The site I need help with is:"

#### What happened instead
No site is indicated.

#### Screenshots

<img width="706" alt="WordPress_com" src="https://user-images.githubusercontent.com/11873759/70420614-c8752080-1a70-11ea-9609-b50b10c143a7.png">

![Topic__Help___WordPress_com_Forums](https://user-images.githubusercontent.com/11873759/70420701-f22e4780-1a70-11ea-9e94-825d3ac166ed.png)

#### Additional info

Some time ago we requested in #16015 that a site selector be added to that form for free users, as one already appears for paid users using the same form - users don't always want help with their primary site, leading to confused follow-ups in the forums as to why that site is being indicated in their support request.

However, since that issue was created the pop-up support contact form has also been introduced. Instead of using the API to create a new forum thread, that form simply has a button that sends the user directly to the forums to create their thread there instead.

<img width="351" alt="WordPress_com" src="https://user-images.githubusercontent.com/11873759/70420766-14c06080-1a71-11ea-8364-59a4e29ed737.png">

I wonder if it wouldn't be better if the form at https://wordpress.com/help/contact behaved in the same way for users being routed to the forums rather than to Directly. That would make for a consistent experience across the two contact options, make it clear to the user that they're posting in a public support forum (as they don't always realise that), and give them the ability to select the correct site they need help with via the forum's own submission form at https://en.forums.wordpress.com/?new=1

#### Context / Source

This issue was discovered by team Chiron over the weekend.

**Comment by jsnajdr** [comment]
I see some race conditions and subtle bugs in `<SitesDropdown>` and `<SiteSelector>` component that might cause this. But the affected code hasn't been substantially changed for at least several months. I don't see anything that looks like a regression from last Friday.

**Comment by KokkieH** [comment]
> But the affected code hasn't been substantially changed for at least several months. I don't see anything that looks like a regression from last Friday.

I'll take your word for it :)

The PR where I pinged you this morning is the only change that seemed relevant that I could find as well.

In case it helps, here is the last post I can find where the primary site was automatically indicated:

https://en.forums.wordpress.com/topic/this-is-my-blog-but-i-lost-all-my-emails-and-passwords-when-i-lost-my-phone-i-cant-do-the-password-recovery-as-i-cant-remember-when-i-paid-for-my-plan-and-i-dont-have-my-o/

Posted at 10:46UTC on 5 December. I know this thread was created via the contact form because of the `wpcomhelp` tag that's present.

The first one I can find where the site was not indicated:

https://en.forums.wordpress.com/topic/what-is-the-use-of-my-blog/

Posted at 07:47UTC on 7 December. At that time the user already had a site, created around 07:40UTC and the site is set as primary site in the account.

(Ordering of threads at https://en.forums.wordpress.com/topic-tag/wpcomhelp/ is based on last reply, not creation date of the thread itself, so the gap between those two isn't telling of anything in particular. Another example is https://en.forums.wordpress.com/topic/how-to-i-get-back-to-the-guttenberg-editor/ created at 21:42UTC on 6 December)

**Comment by supernovia** [comment]
I just wanted to add that when we select the primary site by default, we have still had quite a bit of confusion over what site is selected.

I'd propose we make the site option *required* but don't select one by default, and have "Other site specified above" and "I do not have a site with WordPress.com yet" as options.

**Comment by supernovia** [comment]
.. or if someone is willing to put in the time for this, add a field that lets them specify if the site if they choose other.  That would help greatly with AR threads, for example.

**Comment by KokkieH** [comment]
This is still an issue that Chiron would really appreciate if it could be fixed.

**Comment by jsnajdr** [comment]
Let's keep this open, I'm still hoping to fix it sometime soon.

**Comment by Aurorum** [comment]
PR for this issue in #52979. :)
