### ISSUE TITLE
(5P) FSE: fix styling inconsistencies between a8c and core Nav blocks 

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#38317]
As per https://github.com/Automattic/wp-calypso/pull/38197 the `a8c/navigation-menu` block may be transformed into the `core/navigation` block.

As part of this, upon transformation we need to minimise styling differences between the two across all our key Themes.

Here's the current state of play in [Alves](https://wordpress.com/theme/alves/):

#### a8c Block (old)
<img width="1278" alt="Screen Shot 2019-12-10 at 15 33 11" src="https://user-images.githubusercontent.com/444434/70543503-65fc4d00-1b62-11ea-920e-6dcc0fe92f34.png">

#### Core Block (new)
<img width="1277" alt="Screen Shot 2019-12-10 at 15 29 17" src="https://user-images.githubusercontent.com/444434/70543293-14ec5900-1b62-11ea-8aca-cb29624a327c.png">

#### a8c Block (old)
<img width="1267" alt="Screen Shot 2019-12-10 at 15 28 40" src="https://user-images.githubusercontent.com/444434/70543353-2cc3dd00-1b62-11ea-9925-aa9d20b956bc.png">

#### Core Block (new)
<img width="1272" alt="Screen Shot 2019-12-10 at 15 29 29" src="https://user-images.githubusercontent.com/444434/70543369-33eaeb00-1b62-11ea-94a8-b0fae96f2325.png">

#### Steps to reproduce
1. Setup FSE sync as per https://github.com/Automattic/wp-calypso/pull/38197
2. Use the [Alves FSE Theme](https://wordpress.com/theme/alves/)
3. View the editor and front end with the old block in place
4. Edit the Header template part and update to core Nav block
5.  View the difference on the editor and front end with the new block in place

#### What I expected

* Visual consistency between the two blocks when upgrading between them.

#### What happened instead

* Styles are visually inconsistent. See screenshots above.

#### Browser / OS version

* All

**Comment by getdave** [comment]
Pinging @shaunandrews and @iamtakashi for design support on this one.

**Comment by iamtakashi** [comment]
Is this because of the theme lacking the support for the blocks? If so, it should be reported in https://github.com/Automattic/themes/. I remember seeing that's what the theme team prefers theme issues to be reported.

**Comment by obenland** [comment]
Let's update these styles in Varia for template-first themes.

**Comment by getdave** [comment]
I'm going to [raise an Issue for Varia](https://github.com//Automattic/themes) and then ping `@/allancole`.

**Comment by getdave** [comment]
I raised [the issue here](https://github.com/Automattic/themes/issues/1743).
