### ISSUE TITLE
eComm Plan: Manage Site links to Stats, not Home , on new sites

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38321]
To reproduce, signup on WP.com and purchase an eCommerce Plan.

Click the Manage site button in the sidebar.

![image](https://user-images.githubusercontent.com/545779/70552663-6df6c580-1b3f-11ea-9a30-014ae7a8563d.png)

It will lead to the Stats page.

![image](https://user-images.githubusercontent.com/545779/70552699-7bac4b00-1b3f-11ea-853a-df670f841059.png)

**I expected:**

It would lead to the new My Home page now that it's available.

**Comment by alaczek** [comment]
I was able to reproduce this in my signup walkthrough as well ( p9Jlb4-16V-p2#comment-1747 ).

**Comment by davipontesblog** [comment]
I can reproduce this on my test site with eCommerce plan following the steps described here. Adding this to the Manage board for review.

**Comment by davipontesblog** [comment]
@gwwar would this be a quick win one to add to the next sprint?

**Comment by gwwar** [comment]
We should be able to take it cc @Automattic/isotope for visibility

**Comment by gwwar** [comment]
This will likely be visible sometime next the end of next week in prod, I think we're planning on bundling a few more fixes in for store.
