### ISSUE TITLE
Theme Showcase: Unable to search for theme on IE11

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#38332]
#### Steps to reproduce
1. Start at https://wordpress.com/themes/
2. Click on `Show All Themes`
3. In the search bar, try to search a theme based on Feature or something else.

#### What I expected
You should be able to search a theme as you can in Chrome (just fine)

#### What happened instead
The page just jumps and you can't search for a theme. https://d.pr/i/l1XX2j

#### Browser / OS version
IE 11 I replicated this using Browserstack.

#### Screenshot / Video
 
Recorded screen here: https://d.pr/i/l1XX2j

**Comment by nerdysandy** [comment]
Reported on 2551034-zen

**Comment by Addison-Stavlo** [comment]
I took a look on IE11 and I see that it is getting "syntax error in regular expression".

@akirk @deBhal - I think this might be related to the RegExp that was added recently in `keyed-suggestions` component.   [It sounds like IE11 doesn't support the `new RegExp()` constructor function. ](https://stackoverflow.com/questions/36789118/javascript-regular-expression-failing-in-ie-but-working-in-chrome-edge)

https://github.com/Automattic/wp-calypso/blob/bea7d6c6929e5cc0ce45c18b729ecf1028bb0a6b/client/components/keyed-suggestions/index.jsx#L225-L228

**Comment by akirk** [comment]
Thanks for the detailed report. We were looking to replace this with https://fusejs.io, I hope to be able to expedite the switch over.

**Comment by kriskarkoski** [comment]
Confirmed this is still an active issue in Browserstack

**Comment by davemart-in** [comment]
@akirk did we ever get around to using fusejs.io?

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

We are discontinuing IE11 support soon, so this issue should be closed as `Closed - Won't Fix`.
