### ISSUE TITLE
"My plan" description font size looks to be off

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#38349]
When looking at a site's plan on https://wordpress.com/plans/my-plan/, I noticed that the font size for the plan description looks to be off. I am referring to the text `Learn more about everything included with Business and take advantage of its professional features.` in this issue.

Wasn't it smaller earlier? 🤔 

It appears to be the same font as the rest of the page though. 

<img width="1099" alt="Screenshot 2019-12-09 at 21 40 56" src="https://user-images.githubusercontent.com/18581859/70645777-9c71bf00-1c6b-11ea-846d-e3db7ff2f9da.png">
<img width="739" alt="Screenshot 2019-12-11 at 23 10 42" src="https://user-images.githubusercontent.com/18581859/70645786-a1367300-1c6b-11ea-92a3-fb1eb28c2b51.png">
<img width="1101" alt="Screenshot 2019-12-11 at 23 10 36" src="https://user-images.githubusercontent.com/18581859/70645787-a1367300-1c6b-11ea-9ae1-166286976e7d.png">

**Comment by kriskarkoski** [comment]
Since this is not causing any issues I'm going to close this as it matches the other font sizes on the page

**Comment by arunsathiya** [comment]
Not sure we can close this yet, @kriskarkoski. The `My plan` description's font size is larger than the rest of the page's, as seen in the first image. Would you know if we can get anyone from Design to review it? Maybe @sixhours?

**Comment by arunsathiya** [comment]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/18581859/112402614-d9fc3d80-8d32-11eb-904c-c672468b6dc8.png">

This appears okay now. Closing.
