### ISSUE TITLE
Styles broken when changing the primary domain

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#38350]
When changing the primary domain on https://wordpress.com/domains/manage, the style for `Setting primary domain...` appears to be broken, or misplaced.

<img width="1124" alt="Screenshot 2019-12-09 at 22 15 50" src="https://user-images.githubusercontent.com/18581859/70645906-dba01000-1c6b-11ea-83f0-f8e4a5fffac0.png">
<img width="1097" alt="Screenshot 2019-12-09 at 22 16 01" src="https://user-images.githubusercontent.com/18581859/70645907-dc38a680-1c6b-11ea-8d9b-123d19fdd632.png">

**Comment by kriskarkoski** [comment]
I am not able to reproduce this in Chrome:

<img width="1093" alt="Screen Shot 2020-03-13 at 2 13 18 PM" src="https://user-images.githubusercontent.com/1900444/76648318-da190900-6534-11ea-9c91-bd8e37962014.png">

@arunsathiya What browser did you experience the issue in? Can you check if you're still seeing it and close if not.

**Comment by arunsathiya** [comment]
Does seem to be fixed now. 👍🏽
