### ISSUE TITLE
Gutenberg: Post Titles with Apostrophe Turn to `&#039;` When Published

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#38362]
#### Steps to reproduce
1. Create a new post or page on a non-AT WordPress.com site
2. Add a title that includes an apostrophe
3. Publish the post or page

#### What I expected
That the title of the post/page would display the apostrophe in the post title in the editor

#### What happened instead
The apostrophe in the post title was turned into the `&#039;` code

#### Browser / OS version
Firefox 71/Google Chrome 78.0.3904.108
macOS 10.15.2

#### Screenshot / Video
[![GIF of Issue](https://d.pr/i/JqpUt8+)](https://d.pr/i/JqpUt8)

#### Context / Source
User report (#17239929-hc)

**Comment by tbradsha** [comment]
11673935-hc

**Comment by nickpagz** [comment]
Another report here:
#17299627-hc
...and easily reproducible on any simple test site.

**Comment by GeoJunkie** [comment]
Also reported in 16959970-hc

**Comment by pauloeaquino** [comment]
14678057-hc

**Comment by Agepeuve** [comment]
Another report in 2564854-zen.

**Comment by jjchrisdiehl** [comment]
2563189-zen

Also producible on previews, doesn't necessarily need to be published to reproduce

**Comment by glendaviesnz** [comment]
Potentially related to https://github.com/WordPress/gutenberg/pull/18616/files

**Comment by glendaviesnz** [comment]
A fix for this was merged into gutenberg, which should be available on wpcom early January.

**Comment by kspilarski** [comment]
Adding 2583224-zd report here as well. I told the user that it will be available in early January based on the comment above.

**Comment by kspilarski** [comment]
Adding 2588969-zd report. Mentioned the fix will be in early January.
