### ISSUE TITLE
Simple Payment Button Block: converts into paragraph block when pasting in the email address

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#38370]
#### Steps to reproduce
1. Starting at URL: Any page or post on sites with or without plugins
2. Add `Simple Payment Button Block`
3. Paste any text into `Email` field

#### What I expected
See text appear

#### What happened instead
`Simple Payment Button Block` disappears and transforms into a `Paragraph Block` with the pasted text

#### Screenshot / Video
![](https://d.pr/i/41Gbaz+)
_Link: https://d.pr/i/41Gbaz_

#### Context / Source
#dogfooding

**Comment by tijosh** [comment]
Had a report of this in #18999914-hc

The user was copying the email from an existing payments block, and when it's pasted into the new block, it makes both blocks have the same payment ID:

![Screenshot](https://d.pr/i/c3v5gN+)

**Comment by zdenys** [comment]
Fixed by https://github.com/Automattic/jetpack/issues/15121
