### ISSUE TITLE
Blog Posts Block: Double Dates on Front End of site in Post Meta

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38389]
Noticed in testing on an unlaunched WP.com site:

![image](https://user-images.githubusercontent.com/545779/70739970-adf3af00-1cdd-11ea-890e-52f5ff7823db.png)

Unexpected double dates on the front-end in the post-meta.

**Comment by ianstewart** [comment]
cc @obenland

**Comment by obenland** [comment]
I'd consider that a theme issue, see `_s`: https://github.com/Automattic/_s/blob/master/style.css#L850

**Comment by michaeldcain** [comment]
I'll fix this with the other theme style updates.

**Comment by michaeldcain** [comment]
The fix for this was removed in the review cycle of https://github.com/Automattic/themes/pull/1710. Re-opening.
