### ISSUE TITLE
eCommerce Plan: "Shortcode" pages have Amp Errors

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38386]
#### Steps to reproduce
1. Create a new eCommerce Plan site
2. Edit one of the auto-generated pages (other than the homepage)
3. Check out the stats & visibility panel in the document inspector

![image](https://user-images.githubusercontent.com/545779/70737109-68cc7e80-1cd7-11ea-8b33-3041f435a369.png)

I expected not to see AMP errors on these post types. I suspect it's related to the AMP plugin and the post type registration? I don't see these errors on pages for example. We merely note that the AMP feature is for blog posts only …

https://en.support.wordpress.com/amp-accelerated-mobile-pages/

**Comment by davipontesblog** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/39314
