### ISSUE TITLE
Blog Posts Block: add class to "more" button

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#38391]
Without a CSS class or a wrapper element with a CSS class, the "more" button can't be specifically targeted for styling.

![Screen Shot 2019-12-12 at 2 59 59 PM](https://user-images.githubusercontent.com/942359/70744690-30856a00-1cf0-11ea-8dc6-568a98cb62c7.png)

/cc @obenland

**Comment by obenland** [comment]
Does `button[data-load-more-btn]` work?

**Comment by michaeldcain** [comment]
It does.
