### ISSUE TITLE
Jetpack Backup confirmation in Activity Log says "real time" but I purchased "daily" backups

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#38395]
#### Steps to reproduce
1. Buy Daily Backups for a Jetpack site
2. Head to Activity Log and enter your credentials
3. You will see a notification like "Your backup is underway. We're currently backing up your site for the first time, and we'll let you know when we're finished. After this initial backup, we'll save future changes in real time."
4. Note that I did _not_ buy real-time backups.

#### What I expected

Prompt that correctly describes the product I purchased

#### What happened instead

Prompt says real-time, product says daily

#### Browser / OS version

Chrome 79 / Android 10, and
Chrome 78 / macOS 10.15

#### Screenshot / Video

<img width="992" alt="daily-real-time" src="https://user-images.githubusercontent.com/51896/70755322-632e6300-1cee-11ea-9d16-73797bbf9bf2.png">

**Comment by seear** [comment]
This one is for @Automattic/jetpack-voyager

**Comment by tyxla** [comment]
Thanks for the ping @seear, this is on us indeed. Tracking in 1142395350490785-as-1154202007236393.

**Comment by tyxla** [comment]
PR: #38473
