### ISSUE TITLE
Me: shouldn't use "green" as color

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#384]
The Me section, on the two factor authentication page (after being authenticated), is using green and red for colors:

![image](https://cloud.githubusercontent.com/assets/548849/9247561/8234be30-41b4-11e5-80f8-5d404913551d.png)

![image](https://cloud.githubusercontent.com/assets/548849/9247613/fa6eff96-41b4-11e5-9036-7ebce4b9229a.png)

It should use our $alert-green and red instead. Or a different design altogether.

**Comment by kellychoffman** [comment]
Just noticed this. I'll create a PR to swap out the colors.
