### ISSUE TITLE
Themes: Only returning 22 themes when clicking to reveal more themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38410]
#### Steps to reproduce
1. Create a new site as a new user.
2. Navigate to the theme showcase in Calypso.
3. Click to "Show all themes" at the bottom of the screen.

#### What I expected

To see all available "294" WP.com themes.

#### What happened instead

I only saw 22 themes.

![image](https://user-images.githubusercontent.com/545779/70812902-22862680-1d8e-11ea-9b06-9b3865106508.png)

**Note:** Using the All|Free|Premium filters on the search component seems to reveal all themes. (I expect very people to find those filters. Merely noting for helping debug.)

cc @apeatling

**Comment by ianstewart** [comment]
cc @Addison-Stavlo

**Comment by Addison-Stavlo** [comment]
Pasting some of our slack discussion here for more info on the issue for anyone else reviewing.

That odd behavior seems to be a result of how the pagination on scrolling was set up originally.  While we haven't changed anything for how that works, now that its not initially loading that section at the top of the page and hides behind a button, it "leaves room" for someone to scroll too far and "overshoot" it before its ready.

This bug should fix itself if you scroll up to near the top of the page and then back down again to trigger the pagination.  It seems our best bets to fix this without redoing how the pagination checks work is to either:
a - add more themes to the initial list.  This will allow us to be scrolled to a relatively higher location on the overall screen when the button is opened, making it less likely that we are scrolled down further than the pagination trigger.
b - remove the `More themes` button.  This will allow us to be scrolled at the top of the page so there is no way we are below the level that triggers pagination.

Note that we can currently always find a way to bug out the pagination if we scroll down too far and too fast while a new page is being retrieved and added.
