### ISSUE TITLE
Gutenberg: Clicking on an image in P2 can intermittently cause an unresponsive cursor.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#38417]
Clicking on an image in P2 can intermittently cause an unresponsive cursor. Found a few times today, writing different p2 posts that all of a sudden, when I tried to type in a text field, it wouldn’t show my cursor or allow me to type.

Workaround: Before I found out how to fix, I saved my post, exited out and came back to draft (which worked, but clearly not ideal). I found the problem and solution while writing a recent post: after I insert an image (by dragging from file explorer into post writing area), if I don’t exit out of the block menu for that image, the problem happens where I can’t type. But if I click into that image, then open that image block menu, and X-out of the entire menu, you can go back to typing in the post.

Reported by @sethmclellana8c in p4k3M4-2Cc-p2.

**Comment by simison** [comment]
Likely fixed in https://href.li/?https://github.com/WordPress/gutenberg/issues/19731

**Comment by kriskarkoski** [comment]
Since this is likely fixed and there have been no further reports I'm going to close for now, but please reopen or open if a new issue if it reoccurs.
