### ISSUE TITLE
FSE: Footer - Controls for the Nav Menu Block Invisible When Inside Column Block

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#38423]
If you are editing footer and add a column block on the top, and add a nav block inside the column block, the controls to adjust the navigation block become invisible. 
#### Steps to reproduce
1. Starting at URL: Create a site using FSE flow and choose one of the block themes (I used Stow and Hever in my testing)
2. When editing the Home page, choose to edit Footer
3. Add a column block on the top of the footer:
<img width="1173" alt="Screen Shot 2019-12-13 at 3 32 26 PM" src="https://user-images.githubusercontent.com/25575134/70830246-caffaf00-1dbd-11ea-9e7d-e200a2a6e890.png">

4. Inside the column block with at least two columns, add a nav menu block

#### What I expected

For the controls for the nav menu block to be visible
#### What happened instead
I could not see the controls:

<img width="1666" alt="Screen Shot 2019-12-13 at 3 33 48 PM" src="https://user-images.githubusercontent.com/25575134/70830334-01d5c500-1dbe-11ea-9a14-506876190495.png">

#### Browser / OS version

Chrome: Version 78.0.3904.108 (Official Build) (64-bit)
OS: Mac Catalina Version 10.15.1 (19B88)

**Comment by katinthehatsite** [comment]
I tested this issue with two themes: Hever and Stow

**Comment by eduardozulian** [comment]
Probably related to #38050

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
