### ISSUE TITLE
Reader: Following and Discover postcard inconsistent behavior

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#3842]
**Steps to reproduce:**
1. from Followed Sites, I clicked on a Discover postcard (for example this article: Why Men Fight: An Empirical Investigation of the Extremes of Masculinity)
2. I'm then taken to this link https://wordpress.com/read/feeds/41325786/posts/948500296
3. from the Discover tab, I clicked on the same postcard but I'm taken to another link https://wordpress.com/read/blogs/39587363/posts/613980 (the actual full-post view)
4. then I go back to Followed Sites, I'm now taken to the same link in 3 instead of 2

**Comment by jancavan** [comment]
Essentially, I'm unable to see the full-post view of articles that have "originally posted by...". Viewing them from Following _first_ only shows the excerpt. However, if I view them from Discover (where I'm actually able to see the full-post) then go back to Following, only then am I able to view the full post.

Video: https://cloudup.com/cFDiz3az_7a

/cc @blowery @bluefuton

**Comment by bluefuton** [comment]
@jancavan is this one now resolved?

**Comment by jancavan** [comment]
I don't think I can repro so we can close this for now.
