### ISSUE TITLE
Block Editor: Edit Image option missing on image block

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#38421]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/ or https://wordpress.com/block-editor/post
2. Add an Image blog and add an image (method should not matter)
3. There is no Edit Image option:

<img width="43" alt="edit-image" src="https://user-images.githubusercontent.com/1900444/70825360-3ba0ce80-1db2-11ea-8907-21273597cb14.png">

Instead it seems to have been replaced by Replace text with a dropdown:

<img width="349" alt="Screen Shot 2019-12-13 at 2 10 06 PM" src="https://user-images.githubusercontent.com/1900444/70825398-4e1b0800-1db2-11ea-9e70-3a0627dff7da.png">

#### What I expected
To be able to edit an inserted image.

#### What happened instead
Without the Edit Image button there is no easy way to modify an already inserted image. On Atomic/core it looks like these have moved to Crop Settings in the sidebar but maybe due to our custom library we haven't brought that over?

<img width="281" alt="Screen Shot 2019-12-13 at 2 13 20 PM" src="https://user-images.githubusercontent.com/1900444/70825627-dac5c600-1db2-11ea-9839-04e2e1c303b5.png">

#### Context / Source

#2559723-zd - The user reported this changed in the last 24 hours

**Comment by gwwar** [comment]
Thanks @kriskarkoski for the report! There's a current awkward workaround, with replace > media modal, select an image then click edit, but it's not great.

@apeatling @olaolusoga any thoughts on how we should adapt this in our integration?

The [crop settings](https://github.com/godaddy-wordpress/coblocks/tree/0637a8b010235d59a5d7983745450b618f9c53af/src/extensions/image-crop) are from the full CoBlocks plugin. We whitelist a subset of blocks on Simple Sites so this is the reason why we don't see this in the sidebar.

One option might be to see if this extension is safe to include the CoBlocks crop extension, another option would be to add back an edit button, but this could be more fragile if it's a wpcom only customization.

**Comment by kriskarkoski** [comment]
Thanks for clarifying where the Crop Settings were coming from!

It looks like this would be the related core Gutenberg issue for adding support for in-editor cropping: https://github.com/WordPress/gutenberg/issues/13748

**Comment by kristarella** [comment]
@kriskarkoski From memory the "edit image" button previously on blocks was never really an option to edit the image, it only opened the media library for the option to edit from there or replace. So really, this change just renamed the option to what it really does. So yes, this would be a core issue.

**Comment by kriskarkoski** [comment]
I didn't use this much recently so I can't recall the previous behavior, but it looks like the main difference now is when you open the library on our version no image is selected, where on core the current image is shown and you can click Edit without needing to find it again:

<img width="1394" alt="Screen Shot 2019-12-16 at 8 01 34 AM" src="https://user-images.githubusercontent.com/1900444/70909264-16db6f80-1fdb-11ea-9397-04eecc2dbf9d.png">

Clicking Edit opens this:

<img width="1420" alt="Screen Shot 2019-12-16 at 8 01 43 AM" src="https://user-images.githubusercontent.com/1900444/70909275-21960480-1fdb-11ea-9dc7-871495753354.png">

I'll leave it up to @gwwar and team if we want to keep this issue open on our side given this difference or wait for https://github.com/WordPress/gutenberg/issues/13748 to be addressed.

**Comment by mmtr** [comment]
> where on core the current image is shown and you can click Edit without needing to find it again:

I get a different behavior than this. Actually, I get the same behavior as currently in WP.com: the core media modal shows up without any image selected, which matches with what I found on the code ([the id of the current image is not passed to the `MediaUpload` component](https://github.com/WordPress/gutenberg/blob/cd015494bb5ac6bec044d55c799ce6be03f8bfa8/packages/block-editor/src/components/media-replace-flow/index.js#L145-L156)).

@kriskarkoski Maybe you're using the block editor bundled in WP core rather than the Gutenberg plugin? WP 5.3.2 doesn't not include yet the changes from https://github.com/WordPress/gutenberg/pull/16200, so the "Edit" button has not been changed yet to "Replace" and therefore, it relies on [the _old_ flow that passes the current image id to the the `MediaUpload` component](https://github.com/WordPress/gutenberg/blob/cd015494bb5ac6bec044d55c799ce6be03f8bfa8/packages/block-library/src/image/edit.js#L401-L424).

**Comment by kriskarkoski** [comment]
This is being worked on in core at https://github.com/WordPress/gutenberg/pull/20637. Marking this issue as closed as we'll get the core improvement soon enough.
