### ISSUE TITLE
Gallery won't import from media library properly

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#38437]
I was testing using the Gallery Block. Each time I uploaded an image from my computer, it was fine. But when I tried to add an image from the media library, it added a large image, and the other images disappeared. This was in Firefox and using Horizon and also on my regular test site on a WordPress.com free plan. 

Here is a screencast of uploading - https://d.pr/i/TeCsft

And another of trying to add from the media library - https://d.pr/i/vLn4Nn

The only way to get back to the gallery after adding the image from the media library was to do a cmd-z. 

#### Steps to reproduce
1. Open then editor for any post or page. 
2. Add the /gallery block.
3. Click upload and upload a few images to the gallery. 
4. Choose to add an image from the media library. 
5. Note that the image shows very large and the other images are missing.
6. Choose cmd-z on a Mac to undo the last step (ctrl-z on a PC) 
7. Note the rest of the gallery images show up again, but the one you tried to add does not appear.

#### What I expected

I expected my media library image to show in the gallery.

#### Browser / OS version

Firefox 71.0 (64-bit)

We'd also love to know how you found the bug: #manual-testing

**Comment by kriskarkoski** [comment]
Added to the Gutenberg board. I can still reproduce this on 7.7.1 on an Edge-stickered site.

**Comment by cathymcbride** [comment]
@kriskarkoski @ChrissiePollock I'm not reproing this anymore. Are ya'll?

**Comment by ChrissiePollock** [comment]
This is now working for me so I will close.
