### ISSUE TITLE
Checkout: no locale is passed to Stripe.js on init

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#38439]
#### Steps to reproduce
1. With a supported(*) locale other than English, load the checkout by adding a plan to the cart
2. Add a partial credit card number, and click submit.
3. The error message under the field will be in English

#### What I expected
When we initialize the Stripe object ([here](https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/lib/stripe/index.js#L227) and [here](https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/lib/stripe/index.js#L155)), we should be passing one of the supported locales as the 2nd parameter. Stripe [currently supports](https://stripe.com/docs/stripe-js/reference#stripe-function) the following locales: `ar, da, de, en, es, fi, fr, he, it, ja, lt, lv, ms, nb, nl, pl, pt, ru, sv, zh`.

cc @fditrapani, @sirbrillig - this affects both new and current checkouts.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.
