### ISSUE TITLE
Editor: Slideshow functionality not working for sites with the classic editor enabled as default

### ISSUE THREAD

**Issue by pauloeaquino** [Automattic/wp-calypso#38434]
#### Steps to reproduce
1. Ensure site has Classic Editor enabled as default editor
2. In page or post, Add -> Media -> insert two images or more
3. Under Layout, select Slideshow -> Insert
4. Preview OR Publish post/page

#### What I expected
I expect the slideshow to render on the frontend

#### What happened instead
The published site displays a "This slideshow requires JavaScript." message, and the slideshow is not loaded.

#### Browser / OS version
Chrome 78 on macOS (Catalina)

#### Screenshot / Video
Screenshot: https://d.pr/i/gegFqY
Video: https://d.pr/v/zwK3WQ

#### Context / Source
Issue first seen in user report in 2560131-zen. I further confirmed issue is consistent across all browsers and personal testing.

**Comment by scosgro** [comment]
Another report in 2560167-zd

**Comment by pauloeaquino** [comment]
Report in 2560386-zd

**Comment by pauloeaquino** [comment]
Another one here 2560397-zd

**Comment by kristarella** [comment]
2560496-zd

**Comment by kristarella** [comment]
2560490-zd

**Comment by reginabally** [comment]
2560625-zd

**Comment by reginabally** [comment]
2560639-zd

**Comment by kriskorn** [comment]
2560610-zen

**Comment by kriskorn** [comment]
2560953-zen

**Comment by zdenys** [comment]
Another report in 2560763-zen

In Chrome Console the error is `Failed to load resource: the server responded with a status of 404 ()` for https://s0.wp.com/wp-content/mu-plugins/jetpack/_inc/build/shortcodes/js/slideshow-shortcode.min.js?ver=20160119.1

**Comment by lizswafford** [comment]
2561198-zen 

Customer has had the same Text Widgets with Gallery Shortcodes for more than 5 years. But they are either not showing up and display the JS error message, or the images are not being resized correctly to fit the space.

**Comment by JoshuaGoode** [comment]
Slideshow is a Jetpack feature and this appears to be impacting self-hosted sites as well.  We may want to move to https://github.com/Automattic/jetpack/issues and raise it with Jetpack devs ASAP.

**Comment by JoshuaGoode** [comment]
Adding another note that this appears to only be impacting WordPress.com sites that do not have plugins installed/hosting configuration features enabled.

**Comment by AtrumGeost** [comment]
Another case here: 2560436-zen

**Comment by westi** [comment]
Should be resolved by D36769-code cc @kraftbj

**Comment by fstath** [comment]
Multiple reports in a forum thread:
https://en.forums.wordpress.com/topic/new-multiple-problems-with-galleries/
