### ISSUE TITLE
Support User: `localeSlug` error when active

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#3843]
When support user mode is active, the following error sometimes appears:

![983f3604-e440-11e5-805e-132b182f94ea](https://cloud.githubusercontent.com/assets/416133/13592674/2c533d54-e540-11e5-86ed-8e1ca0864b48.png)

Originally reported by @dllh in #3820 and #3778

**Comment by lancewillett** [comment]
Does this cause UI issues? Is it repeatable? I'd say let's ignore it unless it causes UI problems. Feel free to reopen if it's important or urgent.

**Comment by jordwest** [comment]
Re-opening until #6854 is merged, as it's now causing support user to fail after the reboot
