### ISSUE TITLE
Layout Selector: Missing Twenty Twenty Homepage Layout

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38449]
#### Steps to reproduce
1. Add a new page via Calypso
2. Scroll to the Twenty Twenty Homepage Layout in the Layout Selector
3. **Bug:** Note the missing screenshot
4. Select the Twenty Twenty Layout
5. **Bug:** Note the missing layout screenshot in the Editor

#### What I expected

To see a screenshot of a Twenty Twenty Homepage Layout.

#### What happened instead

Screenshot courtesy of @simison (and props to him for finding that!)

![image](https://user-images.githubusercontent.com/545779/70914876-78510d80-1fde-11ea-85b1-31d8aaf85f05.png)

cc @vindl @obenland

**Comment by noahtallen** [comment]
Huh, it's weird that the screenshot doesn't exist. Possibly something with it being a core theme (?)

**Comment by noahtallen** [comment]
There is some info here: PCYsg-m0L-p2, but I've not had to work with it before.

**Comment by noahtallen** [comment]
So a normal theme layout has its preview like this: https://s.wordpress.com/mshots/v1/https://heverdemo.wordpress.com/?theme_preview=true?w=332.

The twentytwenty layout looks like this: https://s.wordpress.com/mshots/v1//wpcom/v2/verticals/p12v2/templates?_locale=en&theme_preview=true?w=332

which is weird. Obviously the latter does not exist.

**Comment by obenland** [comment]
Looks like `wpcom_get_theme_demo_site()` messed that one up

**Comment by obenland** [comment]
It's not `wpcom_get_theme_demo_site()`'s fault. The theme demo site is missing the `theme-demo-site` blog sticker

**Comment by noahtallen** [comment]
Yep, just noticed that!

**Comment by noahtallen** [comment]
Just added it. How do we update the caches?

**Comment by obenland** [comment]
I deleted the cache for twentytwenty. Looks like the API response is proper now.
https://public-api.wordpress.com/wpcom/v2/verticals/m1/templates?_locale=en

**Comment by noahtallen** [comment]
Thanks! It's working correctly now in SPT:

<img width="294" alt="Screen Shot 2019-12-17 at 4 45 04 PM" src="https://user-images.githubusercontent.com/6265975/71046255-a15fc400-20ec-11ea-9cb6-0411f5ba5dbf.png">
