### ISSUE TITLE
Reader: Images with protocol-relative URLs do not load

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#38442]
#### Steps to reproduce
1. Create a post which contains images where the source does not set a protocol(like `src="//a-domain.com/the-image.jpg`).
2. Publish the post
3. Check the post in the reader

#### What I expected
The image to load

#### What happened instead
No image it loaded, and no img tag is output in the html source.

#### Testing Notes:

This came to light from a user trying to add Amazon Affiliate links to their posts. Amazon provides code in the format:

`<a target="_blank" href="https://www.amazon.com/gp/product/B07Y9BGZ54/ref=as_li_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B07Y9BGZ54&amp;linkCode=as2&amp;tag=jordesign-20&amp;linkId=bb0e6fb748346e85ac31fb420c650af5"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&amp;MarketPlace=US&amp;ASIN=B07Y9BGZ54&amp;ServiceVersion=20070822&amp;ID=AsinImage&amp;WS=1&amp;Format=_SL250_&amp;tag=jordesign-20"></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=jordesign-20&amp;l=am2&amp;o=1&amp;a=B07Y9BGZ54" width="1" height="1" border="0" alt="" style="border:none !important;margin:0!important;">`

You can check out my test post which contains a version as supplied (no protocol) and a version where I've amended the code to use https:// at https://lamontjordan.blog/2019/12/16/testing-amazon-affiliate-links/

This seems to impact all places that content is output as a reader subscription (Reader in the browser, Reader in the Mac OS App, Reader in the iOS App and in follower emails. It does not seem to effect the RSS feed itself.

#### Screenshot / Video

<img width="795" alt="Screen Shot 2019-12-16 at 1 33 39 pm" src="https://user-images.githubusercontent.com/1842363/70875117-fa562c00-2008-11ea-9184-9f1a71efe9f7.png">

_Front end of the post in the browser  (both images shown)_

<img width="993" alt="Screen Shot 2019-12-16 at 1 30 07 pm" src="https://user-images.githubusercontent.com/1842363/70875065-caa72400-2008-11ea-9207-b13ed5eb7ab2.png">

_Follower Email_

<img width="1515" alt="Screen Shot 2019-12-16 at 1 28 03 pm" src="https://user-images.githubusercontent.com/1842363/70875072-d1359b80-2008-11ea-9220-235f82f64ddf.png">

_Reader Mac OS App_

<img width="813" alt="Screen Shot 2019-12-16 at 1 20 41 pm" src="https://user-images.githubusercontent.com/1842363/70875079-dabf0380-2008-11ea-8edf-3273b32af4f2.png">

_Reader (Web Browser)_

#### Context / Source
<!-- Optional: share your unique context to help us understand your perspective. You can add context tags such as: #journey #anecdote #narrative #context #empathy #perspective #reallife #dogfooding #livesharing #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

We'd also love to know how you found the bug: #dogfooding, #manual-testing, #automated-testing, or #user-report if applicable.

**Comment by bluefuton** [comment]
Thanks for the report @jordesign 👍 

Link to the test post in Reader: http://wordpress.com/read/blogs/150058315/posts/394

**Comment by GeoJunkie** [comment]
Adding a note that this was originally reported in 2563198-zen

**Comment by davipontesblog** [comment]
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by yansern** [comment]
Technical analysis: When a protocol-relative URL is used, the `?ssl=1` is not appended to the photon CDN url, without `?ssl=1`, the image doesn't load.

**Comment by yansern** [comment]
Update: Images are converted from regular urls to photon CDN urls on the client-side, not server-side.
The function that needs to be fixed is `makeImageSafe()` in `client/lib/post-normalizer/rule-content-make-images-safe.js`.

**Comment by yansern** [comment]
Slack discussion to fix this within the reader component by adding a additional normalization rule instead of touching a global library like `makeImageSafe()` here: p1622850673109200-slack-C020SHYRB24
