### ISSUE TITLE
Checklist: Opening Inline Help shows a flash of the completed checklist

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#38452]
We conditionally show the checklist on the Customer Home screen and hide it once the checklist is completed revealing the customer home UI.  When the inline help screen mounts, something is causing the completed checklist to show (presumably fetching the endpoint):

![inline-help-flashes-completed-checklist](https://user-images.githubusercontent.com/1587282/70926452-28347400-1ffb-11ea-8f49-9359c6022cfa.gif)

#### Steps to reproduce
1. Starting at URL: `/home` for a dotcom simple site
1. Complete all checklist items
1. Notice the Checklist disappears and the Customer Home UI appears in its place
1. Click the "question mark button" to reveal the Inline Help panel
1. Notice the completed checklist flash on to the screen momentarily

#### What I expected

For the checklist to not flash

#### What happened instead

It flashed

**Comment by Aurorum** [comment]
Related/duplicate: #37077

**Comment by davipontesblog** [comment]
Moved to DotCom Manage for triaging.

**Comment by gwwar** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/37077
