### ISSUE TITLE
Editor: Changing The Width Of Inline Image Makes The Field Animate And Jump Screen

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#38457]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/
2. Add a paragraph block
3. Insert inline image

<img width="955" alt="Screen Shot 2019-12-16 at 2 42 45 PM" src="https://user-images.githubusercontent.com/25575134/70937511-6721f400-2012-11ea-9aae-384a58b31167.png">

4. Change the width of the image with the field that appears

<img width="919" alt="Screen Shot 2019-12-16 at 2 43 35 PM" src="https://user-images.githubusercontent.com/25575134/70937561-799c2d80-2012-11ea-9382-99a649feaf44.png">

#### What I expected
For the field , whee you change the width to stay fixed

#### What happened instead

The field started jumping over my screen: 

<img width="899" alt="Screen Shot 2019-12-16 at 2 44 38 PM" src="https://user-images.githubusercontent.com/25575134/70937648-a2bcbe00-2012-11ea-8b2c-42c464f47c16.png">

#### Browser / OS version

Chrome Versión 79.0.3945.79 (Build oficial) (64 bits) on Windows 10.
FireFox 71.0 (64-bits) for Linux
Chrome Version  78.0.3904.108 (Official Build) (64-bit) on MacOS Catalina

#### Context / Source
Reported by the user in 2561400-zen. 
#user-report 

Comment from the Happiness Contractor who initially dealt with the ticket:

"I believe it calls different classes with different positions:
– components-popover components-animate__appear is-from-top is-from-center
– .components-animate__appear.is-from-top, .components-animate__appear.is-from-top.is-from-left
– which changes the .data-x-axis to right or center and the .data-y-axis to bottom and top, according to the class."

**Comment by kriskarkoski** [comment]
I could reproduce this on our current version of the Block Editor, but this looks to be fixed by the update to 7.7.1 based on testing on an Edge stickered site.

**Comment by noahtallen** [comment]
This has been fixed in the latest gutenberg version in production :)
