### ISSUE TITLE
Gutenboarding: missing loading / Calypso boot styles

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38469]
When Calypso boots to `/gutenboarding` landing page, it's missing some styles and looks like this for a brief moment:

<img width="1900" alt="image" src="https://user-images.githubusercontent.com/87168/70995189-a0bd3280-20d8-11ea-9459-7b5b439f6178.png">

Visit at http://wpcalypso.wordpress.com/gutenboarding to test.

It should look more like this:

<img width="1758" alt="image" src="https://user-images.githubusercontent.com/87168/70995075-4e7c1180-20d8-11ea-977f-2cfda24cabd9.png">

...or preferably with colors that fit into Gutenboarding (white background & no header?)

...or maybe even something that fits better transitioning from marketing landing pages on WordPress.com to Gutenboarding's account creation? At first, just getting that W look like it should be would be a good first step, anyway.

cc @shaunandrews @dwolfe @olesyabrk @ianstewart

**Comment by sirreal** [comment]
Related: The environment bug styles are also slightly off, but that's not a priority.

**Comment by dwolfe** [comment]
Looks like this has been taken care of - I'm seeing @simison's "should look more like this" screen.

We'll revisit this later as part of the transition from marketing pages, but I think this is great for now. 👍

**Comment by simison** [comment]
Oh ye, this can be closed for now since I PRed this: https://github.com/Automattic/wp-calypso/pull/38530

The second screenshot was elsewhere in Calypso. I went with a look that's a little paler and without blue header which looked totally out of place in Gutenboarding flow, see screenshot below:

<img width="1621" alt="Screenshot 2019-12-19 at 13 48 12" src="https://user-images.githubusercontent.com/87168/71171704-1bb45380-2267-11ea-90d0-80398a45a30f.png">
