### ISSUE TITLE
Editor:Page Templates: TwentyTwenty thumbnail broken 

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#38477]
#### Steps to reproduce
1. Create a test site on WordPress.com
2. Open a new page and look for the home page layouts
3. The TwentyTwenty homepage layout thumbnail appears broken as seen below 

![twentytwenty-1](https://user-images.githubusercontent.com/4162931/71020301-0e418100-2122-11ea-8780-7167db681220.jpg)

4. Once you add the TwentyTwenty layout the sidebar also shows a broken thumbnail

![twenty-twenty-2](https://user-images.githubusercontent.com/4162931/71020548-8f007d00-2122-11ea-92c6-570eb2b79419.png)

#### Browser / OS version
Vivaldi (Chromium based). / Mac OS 10.15.1 (Catalina)

**Comment by marekhrabe** [comment]
All homepage layouts should now look nicer. We have updated their size ratios and removed cookie notices which were present in some templates. Now looking like this:

<img width="431" alt="Screenshot 2020-02-27 at 15 19 31" src="https://user-images.githubusercontent.com/156676/75453700-963ed500-5974-11ea-9928-fe65da37a2f0.png">
