### ISSUE TITLE
Blog Posts Block: Alignment option does not work on front of the site

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#38470]
**Steps**
* Activate one of the template-first themes or Twenty Twenty.
* Add a blog posts block (Assuming you have some posts)
* Set the block alignment either `wide` or `full`
* See the setting is respected in the editor.
* However, the setting isn't respected on the front-end.

![iamtakashinuxtest20191212171508 wordpress com_142-2_](https://user-images.githubusercontent.com/908665/70997827-c729a080-20cd-11ea-9ea7-d46641c16631.png)

The block has a strange wrapper `div` that seems unnecessary(?), and that prevents the css classes from the block to be on the outermost container where they should be.

<img width="441" alt="Screenshot 2019-12-17 at 13 10 00" src="https://user-images.githubusercontent.com/908665/70998169-926a1900-20ce-11ea-87c5-68765686df5d.png">

cc @obenland

**Comment by WunderBart** [comment]
> The block has a strange wrapper div that seems unnecessary

This change was added along with the "Load More" functionality to separate the articles `div` from the button.

>, and that prevents the css classes from the block to be on the outermost container where they should be

Thanks for the tip 🙌 I'll start working on the fix today.

**Comment by WunderBart** [comment]
Update:

This issue has already been reported here: https://github.com/Automattic/newspack-blocks/issues/279 and fixed here: https://github.com/Automattic/newspack-blocks/pull/282. Currently being synced to FSE here: https://github.com/Automattic/wp-calypso/pull/38498. 

cc @jeffersonrabb

**Comment by iamtakashi** [comment]
Thanks for the info @WunderBart
