### ISSUE TITLE
Customer Home: Domain step does not indicate there's free domain credit available

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#38497]
While completing theLaunch step from Site Setup List
#### Steps to reproduce
1. Starting at wordpress.com sign up with a new account. Pick one of the paid plans, but use a free wordpress.com subdomain in domains step. Complete purchase.
2. After signing up go through Site Setup List, up to "Launch site" step.
3. When ready, click the "Launch site" button. You should be asked to pick a domain. Note there's no mention of one year free domain registration available with your plan.
4. Click "Back to site" in the top left corner to get back to Calypso, then click on the "Free domain available" nudge. Note it mentions free one year domain registration included with the plan.

#### What I expected
For the information about free one yer domain included in plan to be displayed in both places.

#### Screenshot / Video
https://cloudup.com/cbZevLNQ7x2

#dogfooding, #manual-testing

**Comment by gwwar** [comment]
@Automattic/cobalt any interest in this one? Basically we're not displaying the free credit notice during the site launch domain upsell step.

**Comment by klimeryk** [comment]
It's a limitation of the signup flow - it's written with the assumption that there is no current site (since, well, it's signup). As such, it'd not be trivial to change it and I don't think it's worth it. Especially if we're pushing for Gutenboarding.
