### ISSUE TITLE
Domains: Link in free domain explainer unexpectedly ends signup flow

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#38495]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Scroll down to plans section and click signup link under one of the plans.
3. Go through signup until the domains step. Type in some terms in the input field.
4. Click the "Review our plans to get started" link in the free domain explainer box on top.

#### What I expected
I expected to be taken to plans page.

#### What happened instead
The signup unexpectedly ended, and I landed on the checkout page with the plan I originally picked on WordPress.com homepage (I cut the video a bit short, but that's where I ended up after clicking the link). 

The issue does not happen if I start signup on WordPress.com by clicking a button not in plans section of the homepage.

#### Screenshot / Video
https://cloudup.com/c_-WU-pj7bi

#dogfooding, #manual-testing

**Comment by klimeryk** [comment]
cc @niranjan-uma-shankar looks like it might be related to your work in https://github.com/Automattic/wp-calypso/pull/37661 or https://github.com/Automattic/wp-calypso/pull/37546. Could you take a look? 🙏

**Comment by niranjan-uma-shankar** [comment]
Thanks for the report @alaczek. I'll take this one - thanks for bringing to my notice @klimeryk ,
