### ISSUE TITLE
Plugin updates: Gutenberg 7.2.0 / CoBlocks 1.19.3

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#38504]
Gutenberg 7.2.0 will be out on Jan 8, 2020.

**Gutenberg**
- [x] Install alpha version: D36877-code / D37145-code / D37205-code
- [x] Activate alpha version on edge sites: D36878-code
- [x] Install RC version: D37297-code
- [x] Activate RC version on edge sites: D37298-code
- [x] Install stable version: D37407-code
- [x] Activate stable version on edge sites: D37409-code
- [x] Activate stable version on prod: D36879-code / D37460-code / D37568-code
- [x] Request update for AT sites: p9o2xV-GT-p2

**CoBlocks**
- [x] Install 1.19.1: D37052-code
- [x] Activate 1.19.1 version on edge sites: D37055-code
- [x] Activate 1.19.1 version on prod: D37056-code
- [x] Install 1.19.3: D37510-code
- [x] Activate 1.19.3 version on edge sites: D37511-code
- [x] Activate 1.19.3 version on prod: D37512-code

**Other**
- [x] Call for testing: p7DVsv-7T1-p2
- [x] E2E tests PR: https://github.com/Automattic/wp-calypso/pull/38507

**Comment by jeraldjuice** [comment]
7.2.0-alpha has been updated to latest version of master.
