### ISSUE TITLE
Stats: Inconsistencies in reports

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#38505]
A few authors don't appear on the Stats page for a particular month, even though their posts have views in that particular month.

Another issue is that when you sum up weekly views of an author for a particular month, the stats are off compared to the number that gets displayed for a monthly views of that same author.

All the details can be found in p56BUd-mg-p2

**Comment by kriskarkoski** [comment]
Unless there is something reproducible across sites I think this is best handled on a p2 on a case-by-case basis so we can audit the underlying data. Closing this issue.

**Comment by davoraltman** [comment]
@kriskarkoski This issue has been on a p2 for quite a while but there's been no progress. Which p2 do you suggest we move this to so that someone can take a look?

**Comment by kriskarkoski** [comment]
I'd maybe drop a note in #data in Slack to start to see if someone can take a look. I just don't think it'll get any more attention here given it has only been reported by one site in four months and generally only favor issues for things we have multiple reports of or can reproduce.

**Comment by lancewillett** [comment]
The Stats area doesn't have a current owner — Data team will likely only get involved if there's an emergency such as data loss or security bug.

Closing this one as "maybe later".
