### ISSUE TITLE
Offset block: Disappearing Captions

### ISSUE THREAD

**Issue by catkiinson** [Automattic/wp-calypso#38501]
#### Steps to reproduce
1. Add an offset block to a post or page and add a few images. 
2. Add captions to those images. 
3. Add a new image to the block. 

#### What I expected
To be able to add a new image to the block without any impact on existing content within the block. 

#### What happened instead
All captions that were added via the editor disappeared once a new image was added. 

#### Browser / OS version
Chrome 79.0.3945.79 / macOS Catalina 10.15.2

**Comment by gwwar** [comment]
@catkiinson are there any more steps here? I'm having trouble reproducing on a Simple Site. Was this an Atomic site? 

After uploading a new image was the caption property still toggled on?

<img width="295" alt="Screen Shot 2019-12-18 at 10 21 57 AM" src="https://user-images.githubusercontent.com/1270189/71112433-52636e80-2180-11ea-8431-e460b83f1f01.png">

**Comment by catkiinson** [comment]
@gwwar It looks like rounded corners and a small gutter need to be selected. Here is a "before" screenshot (Simple Site) where captions are added to the two top images:
![Screen Shot 2019-12-18 at 4 12 45 PM](https://user-images.githubusercontent.com/43645273/71133934-3f1cc700-21b1-11ea-8385-82a15264a6ff.png)

Here is the "after" screenshot where a new image was added, and those captions are gone: 
![Screen Shot 2019-12-18 at 4 13 28 PM](https://user-images.githubusercontent.com/43645273/71133964-5cea2c00-21b1-11ea-899a-f81dc9cdbed0.png)

**Comment by gwwar** [comment]
Thanks @catkiinson! I'm still having trouble, but we'll continue to investigate

**Comment by catkiinson** [comment]
@gwwar Thanks! I double checked and can replicate on a simple site, for both pages and posts. It also happens regardless of how many images exist in the block before adding a new one.

**Comment by mmtr** [comment]
I could reproduce this on a self-hosted site as well, so I filed the issue in the CoBlocks repo: https://github.com/godaddy-wordpress/coblocks/issues/1229

**Comment by mmtr** [comment]
This should be solved next Monday once we activate CoBlocks 1.19.3 on WP.com: p7DVsv-7T1-p2

**Comment by mmtr** [comment]
This is fixed now that CoBlocks 1.19.3 is live on WP.com.
