### ISSUE TITLE
Domains: "Add domain" uses slightly different design pattern

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#38500]
I was initially confused by a different look of Domains sections in Calypso.
Clicking on Plan, then Domains leads to:
![image](https://user-images.githubusercontent.com/4550351/71047868-51870880-2191-11ea-8a81-e39630fabe2a.png)

Clicking on the "Free domain available" nudge in the sidebar leads to:
![image](https://user-images.githubusercontent.com/4550351/71047904-6b285000-2191-11ea-8982-fbbb2d7c12f1.png)

I later realized that the nudge links to "Add domain" section, and you can also get there by clicking "Add Domain" from the Plan > Domains page. But it can be hard to notice this is a sub-section of Domains, because the design changes slightly, and doesn't follow a pattern we have in other places:
* the "Domains" heading is gone
* there's no back button

Compare this to what happens in the People section when you click "Invite" (note the header)
![aIKAOhEqGu](https://user-images.githubusercontent.com/4550351/71049480-92cde700-2196-11ea-827f-ae58315beb0b.gif)

#### What I expected
For the "Add domain" section to use the same design pattern for the header as in other places in Calypso (for example in People section)

#dogfooding, #manual-testing

**Comment by klimeryk** [comment]
Marking this as wontfix - we don't have the design resources to take this on (unless there are volunteers 🙏). Just wrapping it in a card does not seem like it will be a much better solution at this point (with the revamped domain management).
