### ISSUE TITLE
Domains: Domain-only site has weird button sandwich

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#38512]
A domain-only site has a weird primary-secondary-primary button sandwich. Can we clean this up to improve it?

* What is the _one_ primary action we want people to take here? Let's make that the only primary button
* What are the pros and cons for removing the other buttons?

![image (6)](https://user-images.githubusercontent.com/448298/71102682-e0daee80-2186-11ea-9cc8-3d0b122d8032.png)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/domain/domain-only
2. Purchase a domain
3. Choose "Just buy a domain"
4. Complete purchase
5. View your domain-only site

**Comment by wensco** [comment]
> What is the one primary action we want people to take here? Let's make that the only primary button

I'd suggest 'create a site` as the primary action. 

> What are the pros and cons for removing the other buttons?

Pros: there would be one button only :)
Cons: there would be no clear way for a user to manage their domain without first creating a site (which is not intuitive imho if they want to do something like change contact info/DNS, transfer it etc). We also lose a CTA to create email, which can be a revenue opportunity via G Suite.

**Comment by klimeryk** [comment]
Working on a fix here: https://github.com/Automattic/wp-calypso/pull/49937
Will make the Create new site the only primary action and add a check for Titan as well (we're only checking for G Suite right now).
