### ISSUE TITLE
Page Layouts: Update screenshot for the "Team" layout

### ISSUE THREAD

**Issue by wynwin** [Automattic/wp-calypso#38514]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/pages/ (With one of the FSE themes active: Alves, Exford, Hever, Maywood, Morden, Shawburn, or Stow)
2. Add New Page
3. From here you will be presented with the "Recommended Layouts"
4. The "Team" layout has an incorrect and misleading screenshot: 

![Screenshot](https://d.pr/i/7zfupF/XUQocB8SxA+) Screenshot: https://d.pr/i/7zfupF/XUQocB8SxA

#### What I expected
I expected the screenshot to display how the page layout will look once selected:

![Screenshot](https://d.pr/i/m5ERY3/fwKoelGK4I+) Screenshot: https://d.pr/i/m5ERY3/fwKoelGK4I

#### What happened instead
You'll notice that the image does not overhang/stagger as it does in the screenshot. Even when setting a background color: 

![Screenshot](https://d.pr/i/hmnmRy/J2kGqRZR2G+) Screenshot: https://d.pr/i/hmnmRy/J2kGqRZR2G

Can we please update this screenshot to more accurately represent the "team" page's layout?

#### Browser / OS version
Chrome | MacOS

#### Context / Source
I was hosting a 1:1 Quick Start session when the user wanted to achieve the look they noticed in the page layout screenshot. Upon further investigation, we realized that this is not possible with the Media with Text block.  

#user-report

**Comment by obenland** [comment]
@iamtakashi Is this something you'll have time to look into?

**Comment by iamtakashi** [comment]
Thanks for the ping! Here is an updated thumbnail for the team page layout. This was taken with Maywood like other layouts.

![team-2](https://user-images.githubusercontent.com/908665/76535955-97dbc300-6473-11ea-86d8-3e80b5e6bbf0.png)

**Comment by obenland** [comment]
Fixed in D40408-code.
