### ISSUE TITLE
Gallery block: images linked to Media File not opening full size when subsequently edited

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#38526]
#### Steps to reproduce
1. Create a new page/post/portfolio project
2. Add a Gallery block with multiple images, at least 3000px on each side
3. Change `Link To` setting to `Media File`
4. Publish and click on an image in the gallery

#### What I expected

For the image to show full size. Here's where it's working on the user's site: https://zphotovideo.wordpress.com/portfolio/ghana/

Clicking on an image will open the full-sized Media File in a new tab.

#### What happened instead

Clicking on an image opened a smaller version of the Media File, with a URL parameter added. Example here: https://zphotovideo.wordpress.com/portfolio/london-2019/
 
Replicated here: https://affordablesiteforaperson.wordpress.com/giant-gallery/

![URL parameter](https://d.pr/i/hYv5yj+)

#user-report 

Chat: 17401393-hc
Follow-up ticket: 2571443-zen

**Comment by edwinho89** [comment]
Was testing this myself, and was not able to reproduce this when creating gallery images for the first time. Using the same image, what caught me (based on post revisions) that the `?w=768` was later added when editing the post again.

https://edwinho89.wordpress.com/wp-admin/revision.php?revision=3203

**Comment by kristarella** [comment]
I got this ticket in play...

1. The user doesn't have the carousel turned on in the media settings:
https://zphotovideo.wordpress.com/wp-admin/options-media.php
2. The galleries where the images open to another page with a small image are set to open to the attachment page, not the media file
3. I think the width parameter on the media file link is normal, but I'm not sure why

Looking at the original chat, I think they just need to turn on the carousel.

**Comment by kcswong** [comment]
Ah, looks like they changed that from Media File to Attachment Page on the Ghana project. I tested this out again and can see that when a gallery is originally created the width parameter isn't present. However, once the page is edited and updated in any way (doesn't have to be a change made to the gallery itself, it could be adding a different block or changing the title, anything like that) the gallery changes to have the width parameter on each image, the same as what @edwinho89 found above. 

Test project here: https://kcswong.wordpress.com/portfolio/gallery-bug-test/ 
First gallery shows width parameter on images, second gallery doesn't. 

Steps to reproduce: 

1. Make sure JP carousel is turned off
2. Create new page/post/project
3. Add Gallery block and set `Link to` to `Media File`, then Publish
4. Published gallery shouldn't have width parameter in URL when clicking on an image
5. Go back and make any change to the page/post/project, then update
6. Published gallery should now have width parameter in URL when clicking on an image

**Comment by kriskarkoski** [comment]
Adjusted the title slightly to reflect the subsequent editing required to reproduce this issue.

**Comment by synora** [comment]
This is a stale bug but I'm able to reproduce the expected steps in @kcswong's initial post but the last step in the last comment ( width parameter in URL when clicking on an image) doesn't happen for me when I attempt to reproduce based on those steps.

It also looks like @kristarella provided a reply in 2571443-zen. Closing issue.
