### ISSUE TITLE
Block Editor: HTML in titles converted to entity references

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#38521]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/
2. Add a title with HTML, such as `Hello <em>World</em>`
3. Publish and view post
4. Note the results compared to the same test on a current WordPress.org installation.

#### What I expected
A WordPress installation at another host handles it like this:
![Screen Shot 2019-12-18 at 2 04 18 PM](https://user-images.githubusercontent.com/3476361/71123473-fc9ebe80-219f-11ea-808d-b176997fa20c.png)
![Screen Shot 2019-12-18 at 2 04 36 PM](https://user-images.githubusercontent.com/3476361/71123484-032d3600-21a0-11ea-8c03-5edf7d141f6d.png)

#### What happened instead
WordPress.com handles HTML in the title like this:
![Screen Shot 2019-12-18 at 2 04 12 PM](https://user-images.githubusercontent.com/3476361/71123509-0b857100-21a0-11ea-8cbd-60788a70bd6d.png)
![Screen Shot 2019-12-18 at 2 04 43 PM](https://user-images.githubusercontent.com/3476361/71123521-1213e880-21a0-11ea-9fb8-dde07e944ab0.png)

#### Browser / OS version
Happens in current Chrome on a current Mac as well as at least two other browser from the user.

#### Context / Source
https://en.forums.wordpress.com/topic/part-of-the-title-in-bold-italic/

**Comment by supernovia** [comment]
Noting if the person uses Quick Edit from the post list to adjust post titles, they can fix the HTML by re-typing it and saving.

**Comment by kriskarkoski** [comment]
This looks to be handled correctly again in the most-recent version of the Block Editor. Closing.
