### ISSUE TITLE
iframe video embeds from Google Drive don't play in Safari. 

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#38535]
#### Steps to reproduce
1. add video embed from google drive via iFrame in HTML Block:  ex `<iframe src="https://drive.google.com/file/d/1_uqXlLK9gYpHgeVFAAl8XR0p6hbs6sl6/preview" width="640" height="480"></iframe>`
2. see video load and playback properly in Chrome and Firefox
3. attempt to play video in safari

#### What I expected
video to play like it does in other browsers tested (chrome and firefox) 

#### What happened instead
video embed loads, and can be interacted with, but video itself does not play/load 

#### Browser / OS version
Safari 13
Mac OS Mojave

#### Screenshot / Video
https://d.pr/v/vuMPXI

#### Context / Source
reported in #15071605-HC reporting with user permission to include their links.

**Comment by automattic-ian** [comment]
follow up requested in #2572817-zen

**Comment by JoshuaGoode** [comment]
I was able to get this to play after disabling cross-site tracking prevention under Safari > Preferences > Privacy.

It seems to be related to ITP and cross-site tracking prevention.

**Comment by davipontesblog** [comment]
Closing this for now since it does appear to be related to cross-site tracking prevention. @automattic-ian feel free to reopen as needed if this continues to happen and disabling the Safari featured does not fix it.

**Comment by Ramoncg1** [comment]
Estou enfrentando o mesmo problema com todos os navegadores. Os vídeos não carregam e ficam nesta mesma tela.
