### ISSUE TITLE
Blog Posts block: "Load More" button in the editor

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#38532]
The "load more" button says just "more..." in the editor when it says "Load more articles" on the front of the site.

**Front of the site**
<img width="242" alt="Screenshot 2019-12-19 at 12 56 24" src="https://user-images.githubusercontent.com/908665/71175312-29fe7180-225f-11ea-9b17-bcd4d00c63d1.png">

**Editor (when it's styled)**
<img width="121" alt="Screenshot 2019-12-19 at 12 56 12" src="https://user-images.githubusercontent.com/908665/71175307-27038100-225f-11ea-9b45-2d2dd30adb07.png">

**Comment by WunderBart** [comment]
The button title has been updated to "Load more posts" (for both editor and front-end) here: https://github.com/Automattic/newspack-blocks/pull/276 and will be live once https://github.com/Automattic/wp-calypso/pull/38498 is shipped 🙌
