### ISSUE TITLE
FSE parsing issue causes data loss with $ and numbers

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#38545]
#### Steps to reproduce
1. Starting at URL: new WP.com site with FSE enabled (double check with blog sticker)
2. Add text to a post or page with the following format, something like: `$1234`
3. Publish the page, confirm it displays on front of site correctly
4. Load the editor again, notice that the $ and two numbers are gone, leaving `34`

#### What I expected
To see the same text in the editor

#### What happened instead
Certain characters are stripped; seems to be after and including the $ sign

#### Browser / OS version
Chrome, latest macOS

#### Screenshot / Video
<img width="884" alt="Screen Shot 2019-12-19 at 17 11 23" src="https://user-images.githubusercontent.com/66797/71220076-8cb63400-2284-11ea-83d7-583f119dea1e.png">
This is the front-end HTML output

<img width="744" alt="Screen Shot 2019-12-19 at 17 11 53" src="https://user-images.githubusercontent.com/66797/71220084-93dd4200-2284-11ea-9dcb-e58ab04202a9.png">
This is the back-end Gutenberg editor HTML output

Here's what the Gutenberg source code around the text looks like:

```
<!-- wp:media-text {"mediaId":210,"mediaType":"image"} -->
... (truncated for clarity) ...
<!-- wp:paragraph {"align":"left","customFontSize":16} -->
<p style="font-size:16px" class="has-text-align-left">0 for 3 sessions, 5 for 5 sessions, or 0 for 10 sessions </p>
<!-- /wp:paragraph -->
<!-- /wp:media-text -->
```

#### Context / Source
Sent in by a customer in WordPress.com support #user-report ( 17423796-hc )

**Comment by lancewillett** [comment]
From looking at the conversion, my first instinct is maybe a regex that's too greedy, and shouldn't be looking in user-generated text content.

**Comment by lancewillett** [comment]
I also wonder if this is more of a one-off issue; the site was reverted from Atomic back to Simple. Could it be something in post-meta? Or bad characters being stripped?

I made a test site here: 
https://gutentestinglancephotos.photo.blog/testing-it-out/

And using the block editor with the same type of content, using  FSE and Global Styles — the editor saved the $ formatting correctly.

<img width="1412" alt="Screen Shot 2019-12-19 at 17 48 20" src="https://user-images.githubusercontent.com/66797/71220953-cb99b900-2287-11ea-9fa3-ff03fbef67c3.png">

**Comment by lancewillett** [comment]
I am able to consistently repeat this now.

Steps:

1. Create a new FSE editing site using https://horizon.wordpress.com/start/test-fse
2. Choose Maywood theme
3. Paste in the content below

`
<h2 class="has-text-align-left">Puppy</h2>



<p style="font-size:16px" class="has-text-align-left"><em>Position or Job Title</em></p>



<p style="font-size:16px" class="has-text-align-left">A short bio with personal history, key achievements, or an interesting fact.</p>



<p style="font-size:16px" class="has-text-align-left">0 for 3 sessions, 5 for 5 sessions, or 0 for 10 sessions.</p>
`

Save the post or page.

Then, edit the text back in the editor to:

`$250 for 3 sessions, $375 for 5 sessions, or 0 for 10 sessions.`

Save again. The editor immediately loads with the missing characters, and triggers an auto-save warning.

**Comment by lancewillett** [comment]
Here's a screen capture:

https://cloudup.com/cdx-iGyzWhB

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core FSE.
