### ISSUE TITLE
Mobile Theme jitm

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#38558]
I have a site that is showing the JITM for the mobile theme deprecation.

<img width="272" alt="Screen Shot 2019-12-20 at 4 46 31 PM" src="https://user-images.githubusercontent.com/115071/71266301-6ce84400-2348-11ea-9bc4-c9040565756d.png">

#### Steps to reproduce
Not sure how to reproduce it.

#### What I expected
That the notification doesn't look so bad :( 

#### Browser / OS version
Firefox on a mac.

**Comment by jeherve** [comment]
Fixed in D37010
