### ISSUE TITLE
Comments: Liked comments do not appear as liked after a refresh

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#38550]
#### Steps to reproduce

- Start with a Jetpack site or Atomic site (WordPress.com site with a plugin or third-party theme installed)
- Visit https://wordpress.com/comments/all/
- Like a comment here (if the comment doesn't exist, create one first)
- Refresh the page

#### What I expected

The comment appears to be liked.

#### What happened instead

The comment appears as if it's not liked. Visiting the comment on the live site itself though shows the liked status.

#### Browser / OS version

Firefox 71.0 (64-bit) with macOS 10.15.2 - MacOS Catalina. 

#### Screenshot / Video

<img width="1314" alt="Screenshot 2019-12-20 at 15 54 39" src="https://user-images.githubusercontent.com/18581859/71248639-5db1c800-2341-11ea-81fc-9950fff79082.png">
<img width="1133" alt="Screenshot 2019-12-20 at 15 52 38" src="https://user-images.githubusercontent.com/18581859/71248640-5e4a5e80-2341-11ea-9758-1d718f106003.png">

The first comment in both images are liked, but they do not seem to appear so.

#### Context / Source

#user-report

**Comment by arunsathiya** [comment]
@suyogyashukla's report. #17430582-hc (#2574920-zen)

**Comment by jamiepalatnik** [comment]
I was able to recreate this on my site as well. Also reported in 24219011-hc.

**Comment by JoshuaGoode** [comment]
This also applies to likes made on the front end. 

You can like a comment on the front end of your site but it will not appear as liked when viewed via Calypso. 

Discussed in p1600977328204500-slack-C03TY6J1A

Adding tag and sending to Dotcom Manage Backlog.

**Comment by arunsathiya** [comment]
I cannot see this issue anymore, cannot see the issue that @JoshuaGoode reported about liking on live site either! 🎉 Closing.
