### ISSUE TITLE
Can't delete grey block within right column of Maywood's Cover block

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38564]
There's a grey placeholder block that can't be deleted on the right side of the Cover block that's part of the Maywood homepage layout.

#### Steps to reproduce
1. Switch to Maywood page layout
2. Select grey placeholder block on right side of Cover block
3. Click on "More" button at right of block toolbar
4. Observe no "Remove block" menu option

#### What I expected
I expected to be able to delete the grey placeholder block. 

#### Browser / OS version
macOS / Chrome 78.0.3904.108 

#### Screenshot / Video
Video: https://d.pr/v/XNlkrf
![Screen Shot 2019-12-20 at 2 47 28 PM](https://user-images.githubusercontent.com/1348738/71297276-ac5a6480-2337-11ea-81a1-da038274f4f4.png)

/cc @ianstewart @michaeldcain

**Comment by kriskarkoski** [comment]
I am no longer seeing this block on the current version of the Maywood home page. Please reopen if you are still seeing the issue.
