### ISSUE TITLE
WooCommerce.com 2FA button isn't centered

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#38580]
The 2FA button on WooCommerce.com login (using WordPress.com) is not centered. 

#### Steps to reproduce 

- Start at https://woocommerce.com 
- Click on `Log in with WordPress.com` at the top.
- Enter WordPress.com username and password.
- When prompted for 2FA, see how the button is displaced. 

![Screen%20Shot%20on%202019-12-24%20at%2011-19-11](https://user-images.githubusercontent.com/18581859/71396610-d5813a80-2640-11ea-858d-677d1cb7e198.png)

On the contrast, the WordPress.com 2FA button seems to have a different design now. :) 

<img width="378" alt="Screenshot 2019-12-24 at 11 20 30" src="https://user-images.githubusercontent.com/18581859/71396612-d619d100-2640-11ea-9ce1-25c2b204a864.png">

**Comment by Aurorum** [comment]
PR in #38581 for this issue. :)
