### ISSUE TITLE
Shortcode Block: selection color not visible

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#38592]
#### Steps to reproduce
1. Starting at any Post/Page on a site without plugins
2. Add Shortcode Block
3. Type any text
4. Try to select it

#### What I expected
See selection

#### What happened instead
Selection is invisible (but happens as if I select the text and then click `delete/backspace` on my keyboard, the selected text is deleted)

#### Screenshot / Video

![](https://d.pr/i/Ll3rJk+)
_Link: https://d.pr/i/Ll3rJk_

Adding the following CSS to the textarea element makes the selection visible:
```
::selection {
  background-color: lightblue;
}
```

![](https://d.pr/i/7tgPGW+)
_Link: https://d.pr/i/7tgPGW_

#### Context / Source
#dogfooding

**Comment by kriskarkoski** [comment]
This looks to have been fixed as I can see highlighting on the shortcode block now.
