### ISSUE TITLE
Me: improve error message when changing email to a currently used email address

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#386]
There are two related bugs in the changing email process:
1. The error message does not give enough information
2. The unusable email the user entered remains on the page

Steps to reproduce:

(1) Go to me/account

![screen shot 2015-11-21 at 9 16 01 am](https://cloud.githubusercontent.com/assets/11487924/11318988/c70c3900-9035-11e5-8a46-21e416f8fcc6.png)

(2) Enter an email that is already used for a different WordPress.com account in the 'email address' field

(3) Click 'Save Account Settings'

![screen shot 2015-11-21 at 9 16 10 am](https://cloud.githubusercontent.com/assets/11487924/11318990/ce084c58-9035-11e5-9620-db6f1211d5fe.png)

(4) See that the email entered in step 2 remains in the email address field, even though it cannot be used. See that the error message does not tell you that you cannot use the same email twice.

![screen shot 2015-11-21 at 9 16 55 am](https://cloud.githubusercontent.com/assets/11487924/11318991/d207e08e-9035-11e5-9070-a16239d69c59.png)

Instead here's what should happen:

(1) The user should see an error message like:

> 'The email address new-email@example.com is already being used for another WordPress.com account. Please use a different email'

(2) The email field should show the currently used email address for the account.

**Comment by rickybanister** [comment]
It should be contextual and look like this:

(from the pattern library)

<img width="311" alt="screen shot 2015-12-09 at 1 31 41 pm" src="https://cloud.githubusercontent.com/assets/437258/11694653/4efa6e1c-9e79-11e5-96c2-20f07f7d9015.png">

**Comment by ebinnion** [comment]
We should improve error messaging and field validation throughout `/me`. So, closing this issue in favor of #1647.
