### ISSUE TITLE
Reader: handle full-post 404s more gracefully

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#3860]
**Steps to reproduce:**
Visit a non-existent full post link (example: https://wordpress.com/read/feeds/41325786/posts/121321321)

**What I expected:**
A 404 page just like our other pages:
![23caa2f4-dfd1-11e5-9ed6-eeef00bb1f56](https://cloud.githubusercontent.com/assets/4924246/13613911/e8043fda-e522-11e5-81c4-932b1ac7f5a7.png)

**What I saw instead:**
A blank page with a blavatar and some text:
![screenshot 2016-03-08 11 44 11](https://cloud.githubusercontent.com/assets/4924246/13613962/1a72f33a-e523-11e5-84ff-a592053fbc3b.png)

If you also happen to be following that site, the same thing is being displayed but with a Following button:
![screenshot 2016-03-08 11 45 28](https://cloud.githubusercontent.com/assets/4924246/13613995/4d695d1a-e523-11e5-9006-539a1821d2af.png)

The "Back" arrow is also only partially showing:
![screenshot-2016-03-08-11 46 02](https://cloud.githubusercontent.com/assets/4924246/13614026/6d0eed9c-e523-11e5-934b-79c301406b0f.jpg)

Related to https://github.com/Automattic/wp-calypso/issues/3681 and https://github.com/Automattic/wp-calypso/issues/3680.

/cc @bluefuton

**Comment by lamosty** [comment]
@jancavan Do we need the sidebar or is this good enough?

![](https://i.imgur.com/rE03p1s.png)

**Comment by jancavan** [comment]
@lamosty a sidebar would be good, thanks.
