### ISSUE TITLE
Gutenboarding: use react-spring

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38612]
Now that the broad strokes are in place for animations between Design picker & Page selector (https://github.com/Automattic/wp-calypso/pull/38471), we should revisit implementing animations using `react-spring`. 

This should;
- possibly simplify the need to share variables across JS and CSS (since `react-spring` can calculate durations on its own)
- improve visuals since `react-spring` might have nicer looking animations 
- align us with core Gutenberg technically and visually, see the above point. See also https://developer.wordpress.org/block-editor/components/animate/
- Mind the performance, though.

Slack p1576859343088200-slack-luna

**Comment by dwolfe** [comment]
Leaving this here for clarity: let’s hold off working on animating the intent capture steps for now. The next iteration should require much simpler animation, and sidestep the current questions and pain points with Spring and transitions generally.

This applies to related issues as well (will edit to add refs in a sec)

**Comment by simison** [comment]
👆I think this was meant for "intent capture" step specifically only, not about page-selector. :-) cc @Automattic/luna

**Comment by dwolfe** [comment]
Whoops, sorry - yes, that's correct. Design picker + page selector will animate very closely to how it is now, tweaks only there, if anything.

**Comment by sirreal** [comment]
Let's keep this open util we land #38721.

Any other cases we know of that need to move to react-spring?

**Comment by sirreal** [comment]
> Let's keep this open util we land #38721.
> 
> Any other cases we know of that need to move to react-spring?

Actually not:



> Leaving this here for clarity: let’s hold off working on animating the intent capture steps for now. The next iteration should require much simpler animation, and sidestep the current questions and pain points with Spring and transitions generally.
> 
> This applies to related issues as well (#38471, #38721)
