### ISSUE TITLE
Profile → Security: Connected app's site name should be unescaped

### ISSUE THREAD

**Issue by TooTallNate** [Automattic/wp-calypso#3861]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/me/security/connected-applications
2. Must have an application connected with a single-site approval, and the site's name must have characters in the title that require escaping / use of HTML entities.
3. Click the dropdown to expand the detail info about the approved application
4. See the __*Access Scope*__, the HTML entities in the site title are not properly unescaped.

#### What I expected

I should see `@TooTallNate's Blog` as the site name (2 locations).

#### What happened instead

I see `@TooTallNate&#039;s Blog` instead (2 locations).

#### Browser / OS version

Chrome latest / OS X El Capitan 10.11.4

#### Screenshot / Video

![](https://cloudup.com/cLEjC7g2RCF+)

**Comment by hoverduck** [comment]
07Apr16 Bug Scrub

Closing as duplicate of #2505
