### ISSUE TITLE
Jetpack connect: modal is off-screen

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38617]
When connecting Jetpack, modal is off-the-screen at least for a free plan:

<img width="1440" alt="Screenshot 2019-12-30 at 21 08 07" src="https://user-images.githubusercontent.com/87168/71596625-b60a7600-2b48-11ea-9bca-271dec7d5054.png">

I expected something more like this:

![image](https://user-images.githubusercontent.com/87168/71597491-0e8f4280-2b4c-11ea-8cba-e96ec86c11eb.png)

You might be able to replicate by visiting `http://calypso.localhost:3000/plans/my-plan/[JETPACK_SITE]?thank-you=`

Tested with Chrome and Firefox browsers.

cc @jeffgolenski

**Comment by simison** [comment]
Bummer, can’t replicate in localhost. Might depend on CSS bundles loading order then? cc @Automattic/team-calypso

**Comment by tyxla** [comment]
Quick fix here to workaround the loading order problem: https://github.com/Automattic/wp-calypso/pull/38618

**Comment by tyxla** [comment]
Shipped it. Thanks for reporting it @simison!
