### ISSUE TITLE
Social Links Block: Removing WP icon makes the Block apparently disappear

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#38640]
#### Steps to reproduce
1. Add Social Links Block to any Page or Post on a site without plugins
2. Clicking three dots to remove the WP icon

#### What I expected
WP icon be removed and Block to remain visible

#### What happened instead
The entire block is apparently removed. Moving the icon to the right first, and then clicking three dots to remove works as expected (the block remains visible). 

However, then clicking away from the Social Links block makes it apparently disappear. It's still there if you click where it used to be. It's confusing but possibly is the intended behavior (since only WP icon actually has a link added, hence when removed, other icons seem to disappear since no links were added to them).

#### Screenshot

![](https://d.pr/i/J3GGyn+)
_Link: https://d.pr/i/J3GGyn_

#### Context / Source
#quick-start-session #user-report

**Comment by kriskarkoski** [comment]
I have confirmed that this issue is still valid.

**Comment by kriskarkoski** [comment]
It looks like the issue is that the block loses focus when the WP block is removed. If focus was maintained it should work as expected and only be hidden if it's clicked away from, which seems to be how it's designed to function.

**Comment by synora** [comment]
I'm unable to replicate this as of today. The Social Icons Block is working as expected.
