### ISSUE TITLE
Jetpack Checklist: vertical line on top of icon

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#38643]
#### Steps to reproduce

* Start with a Jetpack site. 
* View the checklist on the "My plan" page. 
* Complete a few tasks in the list. 
* View the "completed" section at the bottom of the list. The green checkmark icons will have the vertical line in front of them, instead of behind.

#### What I expected

The vertical line to sit "behind" the icon

#### What happened instead

Vertical line sits in front of icon

#### Screenshot / Video

![Screen Shot 2020-01-03 at 12 20 52 PM](https://user-images.githubusercontent.com/214813/71740080-4b4b8a00-2e29-11ea-8e20-b3b672c07aa8.png)

I'm fairly certain a quick `z-index` adjustment of the icon will be a suitable solution. I'm just having some development issues with my machine right now.

@tyxla would you or someone on the team take a quick look?

**Comment by Aurorum** [comment]
There's a PR for this in #38614 :)

**Comment by tyxla** [comment]
Indeed, #38614 fixes that, thanks @Aurorum!

**Comment by jeffgolenski** [comment]
Thanks all!
