### ISSUE TITLE
Gutenboarding: Brief flicker when clicking between inputs (topic/name)

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#38658]
I notice a brief flicker (not sure if this the right word to use btw) when moving selection between the site topic and name inputs. Looks like a pretty minor/tiny issue due to the font size changing when the inputs receive/lose focus, and likely something to be dissolved as we implement more of the designs. Here's a gif of what I'm seeing (observe "Continue ->" moving up/down along with the rest):

![Kapture 2020-01-06 at 16 00 29](https://user-images.githubusercontent.com/1705499/71822524-ba311900-309d-11ea-96bf-3d4cb5e32de2.gif)

Maybe a little more obvious when holding the mouse briefly before releasing:

![Kapture 2020-01-06 at 16 04 12](https://user-images.githubusercontent.com/1705499/71822711-43485000-309e-11ea-9b65-5fc2f6a94780.gif)

CC @dwolfe

**Comment by simison** [comment]
Relevant: https://github.com/Automattic/wp-calypso/issues/38687 (or https://github.com/Automattic/wp-calypso/pull/38721) cc @razvanpapadopol

**Comment by dwolfe** [comment]
I left a comment on #38721 that might be relevant:

> As an aside, some of the ideas we're iterating on might make some of this animation between the first couple of intent gathering steps a lot simpler, or maybe even unnecessary.
>
>...maybe we don't need to get this perfect right now, given that we're still iterating.

**Comment by Addison-Stavlo** [comment]
I think this has been fixed with #38992 as the size transition only takes place once and no longer happens when select/deselecting the items.  Take a look on master and see if you notice any flicker, but if not I think we can close this one.

**Comment by Addison-Stavlo** [comment]
closing this issue as it seems to have been fixed with  #38992 .
