### ISSUE TITLE
i18n: localizeUrl() creates invalid URLs in Safari

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#38668]
Localized URLs in Safari include a port `:0` in the URL, thus making them invalid. This was introduced in #38560

Reproduce in production: 
#### Steps to reproduce
1. Use Safari
2. Change your language to something other than English (e.g. German)
3. Go to https://wordpress.com (Calypso)
4. Open the question mark menu and check the localized links

#### What I expected

URLs like https://de.support.wordpress.com/reader/

#### What happened instead

URLs look like this: https://de.support.wordpress.com:0/reader/ and are thus invalid

#### Browser / OS version

Safari 13.0.4

#### Screenshot / Video
<img width="325" alt="Screenshot 2020-01-06 at 20 58 24" src="https://user-images.githubusercontent.com/203408/71844871-69ceb100-30c7-11ea-9073-9d6ea67cd4c2.png">

**Comment by sgomes** [comment]
#38671 fixed this by reverting, and #38683 should re-introduce the new functionality minus the bug.
