### ISSUE TITLE
Checkup: notice falsely leads me to another tab to change my SMS

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#3866]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/security/checkup
2. Notice says `To edit your SMS Number, go to Two-Step Authentication.`
3. Go to: https://wordpress.com/me/security/two-step
4. There is no way to edit my SMS Number.
#### Browser / OS version

Safari 9.0.2
#### Screenshot / Video

![screen shot 2016-03-08 at 3 43 56 pm](https://cloud.githubusercontent.com/assets/618551/13617608/35f97f80-e545-11e5-8d86-33934875273f.png)
![screen shot 2016-03-08 at 3 44 11 pm](https://cloud.githubusercontent.com/assets/618551/13617612/387d4890-e545-11e5-87ed-54b6063b9785.png)

**Comment by hoverduck** [comment]
07Apr16 Bug Scrub

Confirmed this is still a problem.  The only way to edit your SMS Recovery number is to disable Two-Step Authentication, make the change, then re-enable it.  If that's the expected procedure, it should be documented on the page.

**Comment by BandonRandon** [comment]
This is still occurring.

**Comment by hoverduck** [comment]
#bug-scrub

This is still an issue.  There's no built-in way to change your 2FA settings without disabling and re-enabling it.

**Comment by rachelmcr** [comment]
As noted on https://github.com/Automattic/wp-calypso/issues/6141 (same issue), I tested this issue and there's no longer a "checkup" section at https://wordpress.com/me/security/checkup. Instead, there is an "Account Recovery" section at https://wordpress.com/me/security/account-recovery with the option to add a Recovery SMS Number separate from your 2FA number. (This number is no longer tied to the 2FA number.)

In addition, the 2FA settings screen currently includes clear instructions for changing the phone number being used:

> Authentication codes are currently being sent to #########. If you wish to change this number, please disable Two-Step Authentication, then go through the setup wizard again.

Given that we no longer have incorrect or misleading instructions for editing the 2FA number, I think we can close this issue. Enhancements related to changing the 2FA number can be tracked with #19.
