### ISSUE TITLE
Checklist Banner: Progress indicator misaligned

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#38663]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/191598/71835246-0de03a00-307f-11ea-9e98-d026f551788a.png">

**Comment by simison** [comment]
Could be CSS specificity issue and thus depend on order of pages that were visited.

Cc @Automattic/team-calypso

**Comment by roo2** [comment]
hmm I can't work out how to reproduce this. It looks normal to me and I couldn't find any css that looked likely to cause it. 

@shaunandrews which browser was this in?

Can you give me any more information to help me reproduce it?

**Comment by jsnajdr** [comment]
I can't reproduce it either. Need to know some basic info about the browser. And also some CSS devtool investigation by the reporter would be welcome. Are there any suspicious CSS classes and properties that cause the unwanted offset?

**Comment by simison** [comment]
Could be combination of specific browser width & order of pages visited? 😁

**Comment by shaunandrews** [comment]
This was in Safari, but now I can't reproduce. The screenshot is proof that it happened, but I'll close this for now until I see it again.
