### ISSUE TITLE
Text in badges isn't vertically centred

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#38661]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start.
2. Select a kind of site in the next step of the flow, https://wordpress.com/start/site-type.
3. Enter a blog topic in the next step, https://wordpress.com/start/site-topic-with-preview.
4. Enter a site title in the net step, https://wordpress.com/start/site-title-with-preview.
5. Check the "Our Recommendation" and "Best Alternative" badges on the next page, https://wordpress.com/start/domains-with-preview.

#### What I expected

The text in the badges is vertically centred.

#### What happened instead

The text is aligned more towards the bottom.

The CSS uses `line-height` to size the badge. This should work, but maybe due to some typographical quirk it looks wrong. I've found that reducing the line height and adding a `height` rule fixes the appearance.

```css
line-height: 16px;
height: 18px;
```

#### Browser / OS version

FF 71 / macOS Mojave

#### Screenshot / Video

<img width="990" alt="image" src="https://user-images.githubusercontent.com/1647564/71832421-cc618600-30a2-11ea-9961-f38281729c07.png">

#### Context / Source
#manual-testing

**Comment by roo2** [comment]
opened PR https://github.com/Automattic/wp-calypso/issues/38661
