### ISSUE TITLE
Gutenboarding: don't resize intent gather questions on focus

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38687]
During the intent gathering, each focused question is highlighted bigger:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/87168/71898235-730c5c00-3161-11ea-9048-05e6f935819d.png">

This was useful at the time when we had 3 questions. Is it useful anymore? Does it just distract as-is and other focus styles are enough?

If we need it, should there be smoother animation to switch the size?

@olesyabrk @dwolfe @joanrho I would like some design input here.

**Comment by olesyabrk** [comment]
Yes, let's not resize.

**Comment by Addison-Stavlo** [comment]
This has been fixed with #38992 as the size transition only takes place once and no longer happens when select/deselecting the items.
