### ISSUE TITLE
Cover block added to columns creates overlap into footer widget area

### ISSUE THREAD

**Issue by selectedselections** [Automattic/wp-calypso#38696]
#### Steps to reproduce
1. Create a site using a theme with a footer widget area
2. Add a columns block to the homepage and add cover blocks to those columns
3. Add a widget to the footer widget area on the site
4. Publish the page and you will see that the cover blocks are overlapped by the footer widgets

#### What I expected

I expected that the columns block would house the cover blocks within the content of the page in a grid

#### What happened instead

The cover block are sometimes overlapped by the footer widgets, and sometimes over lap the footer widgets, depending on the theme. 

#### Screenshot / Video

Screenshot on my test site: https://d.pr/i/KXhLou
Here is a video of how I added the cover blocks to columns for this result: https://d.pr/v/5uQMsA

#### Context / Source

This was reported by a user 

#user-report

**Comment by mikeicode** [comment]
Same issue today 17274562-hc

I found that if you have multiple Cover blocks in the same column within a Columns block this happens.

If you use multiple Columns blocks, with only one Cover block per column it doesn't happen.

Also this doesn't appear to be related to the content in the footer widget area, but instead any content below this Columns block on the page.

4 Cover blocks in 2 Column blocks: 

![img](https://d.pr/i/xveKBa+)

4 Cover blocks in 1 Column block: 

![img](https://d.pr/i/BE7mPL+)

**Comment by mikeicode** [comment]
Looks like this is the issue:

```
.wp-block-cover {
  height:100%
}
```

This resolves it:

```
.wp-block-cover {
  height:unset
}
```

Looks like the cover block sets itself to be the full height of the surrounding element, which causes an issue when that’s a column, there isn’t enough room for any other items in the column.

**Comment by tbradsha** [comment]
Another columns + cover block issue in 18339245-hc. The above CSS fixes it.

![image](https://user-images.githubusercontent.com/32492176/73771577-d88d4180-473b-11ea-8aaf-de39d5c56a7e.png)

Block structure:
```
Columns
-Column
--Cover
---Paragraph
--Paragraph
-Column
--Cover
---Paragraph
--Paragraph
Image
```

**Comment by mikeicode** [comment]
Looks like this issue was reported here earlier, I'll close this:

https://github.com/WordPress/gutenberg/issues/17921
