### ISSUE TITLE
Purchases: Error when unable to load purchases

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3869]
@sararosso reported that she sees this message in screens in Calypso other than /purchases:

![image](https://cloud.githubusercontent.com/assets/275961/13619408/b8b8826e-e580-11e5-8bc5-f574ac0039a5.png)

This happens when the purchases endpoint fails to load for some reason, but the user has already navigated away. We should investigate:
1. Why the endpoint is failing (hard)
2. Only show the error if the user is on /purchases (not so hard)

Pinging @fabianapsimoes for triage.

**Comment by sararosso** [comment]
This was the endpoint called for this specific error, though it happened other times: https://public-api.wordpress.com/rest/v1.1/sites/107946568/purchases
