### ISSUE TITLE
[Gutenboarding]: Frontend site creation request/response handling

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38707]
Subtask of EPIC #38701

## Create a site

Immediately after a user signs up in Gutenboarding (#38794), **we should create a site** so they can move onto FSE. 

This task involves adding code to the Gutenboarding/data-store architecture to call the `sites/new` endpoint and handle the response.

## Technical details

It seems like we could integrate HTTP `POST` request and handle the response in [`@automattic/data-stores` package](https://github.com/Automattic/wp-calypso/blob/6f8da7a/packages/data-stores). 

Depending on how we integrate into the Gutenboarding code, the account (#38794) and site HTTP requests would probably need to be chained, and their responses merged on the frontend (TBD).

Most of what we want to do is available already in the `/sites/new` endpoint.

As in #38794, we have to know what we need to do (if anything) to hit the WordPress.com API without `lib/wp`. Related comments: https://github.com/Automattic/wp-calypso/issues/38703#issuecomment-572479664

A typical request to `sites/new` sends the following post body

```
{
    blog_name: string // could be taken from vertical or site name field
    blog_title: string,
    public: -1,
    options: {},
    validate: false,
    find_available_url: true, // will find an available `*.wordpress.com` url based on the `blog_name`
}
```

A successful POST to `sites/new` returns:

```
{
    success: true,
    url: string,
    blogid: number,
    blogname: string,
    xmlrpc: string,
}
```

Would we need to add anything else for our purposes?

## PR

https://github.com/Automattic/wp-calypso/pull/39050

**Comment by ramonjd** [comment]
How we call this endpoint will be mostly led on the outcomes of https://github.com/Automattic/wp-calypso/issues/38794

**Comment by ramonjd** [comment]
We might need to think about whether we need this in frankenflow. 

For instance, if frankenflow uses the current domain + site creation steps, we won't need to create a site immediately, but cache the user's site/template selections and pass them to the signup framework.

For example, we'll need to pass the selected pages in the [existing create sites method](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/step-actions.js#L162).

Not sure, just making a note.

**Comment by p-jackson** [comment]
@ramonjd this task seems done, was there something else this issue was supposed to cover other than what we already do?

**Comment by ramonjd** [comment]
>  this task seems done, was there something else this issue was supposed to cover other than what we already do?

Thanks @p-jackson. I think I was waiting to see how Frankenflow turned out, but you're right... looks like it was resolved for us.

closing

🎤drop
