### ISSUE TITLE
Reader: Hide the follower count when viewing the site in Reader.

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#38715]
#### Steps to reproduce
1. Access the Reader from your account.
2. Select on of the sites you follow.

It shows the number of Followers for that site:

![image](https://user-images.githubusercontent.com/16509219/71981248-fbfdc300-3247-11ea-9668-30ab10a576f5.png)

The user wants to be able to hide this Follower count because they think that if they have less number of Followers, this can prevent new followers from subscribing. This is especially when they are starting with new site.

I've added this feature request.

Reported on: 17762347-hc.
Follow up: 2614154-zen

**Comment by bluefuton** [comment]
Thanks for writing this up @nerdysandy! 

As a rule we don't generally offer the user any customisation options for how their sites appear in Reader, so I'll close this one as a wontfix.

**Comment by nerdysandy** [comment]
Thanks :) I will let the user know.
