### ISSUE TITLE
Actionbar: Follow button not consistently visible on single posts

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-calypso#38710]
Mac, Chrome, I'm an `editor` on the wp.com hosted site in question:

The Follow button is visible on the blog homepage in the action bar:

<img width="208" alt="Screenshot 2020-01-08 at 10 09 34" src="https://user-images.githubusercontent.com/1204802/71964981-09428f80-31ff-11ea-8ce1-834e74b6163d.png">

The follow button is not visible on single posts. Neither in the default version:

<img width="253" alt="Screenshot 2020-01-08 at 10 10 26" src="https://user-images.githubusercontent.com/1204802/71965002-1a8b9c00-31ff-11ea-8d54-63155eb15601.png">

(This is possibly intentional, but I'd love to see it there as well, for a nice bit of consistency)

... but it's also not available for me in the popover:

<img width="373" alt="Screenshot 2020-01-08 at 10 11 27" src="https://user-images.githubusercontent.com/1204802/71965076-3f800f00-31ff-11ea-92bf-519ab7698888.png">

I have checked with others who in the same popover see the following:

<img width="252" alt="Screenshot 2020-01-08 at 10 11 40" src="https://user-images.githubusercontent.com/1204802/71965108-5161b200-31ff-11ea-9f53-1f6c0a9e5ae4.png">

**Comment by kwight** [comment]
@saygunnyc Do you see a clear way forward for this?

We should also check if having the Editor role is influencing the Follow button's appearance.

**Comment by saygunnyc** [comment]
While I believe the longer-term approach for the whole action bar is something for us to discuss – _esp. for Simple/Atomic parity_, I agree with @jasmussen on the sentiment he shared about 1,5 years ago. We should always benefit from each opportunity to create a consistent experience. 

As additional context for @jasmussen, starting to explore subscriptions we noticed that while simple sites with subdomains on WP.com display both "Following/Follow" and the overflow menu, simple sites with custom domains only display the overflow menu without "Follow/Following" and atomic sites do not have an "Action Bar" at all. Sharing screenshots below:


**P2s**
<img width="317" alt="P2" src="https://user-images.githubusercontent.com/78876323/128932064-2f422bfa-73dd-4818-b8bb-515e83510eee.png">

**Simple Sites - Custom Domain**
<img width="127" alt="SimpleSite_CustomDomain" src="https://user-images.githubusercontent.com/78876323/128932065-dca7e094-4e99-4312-a687-a88d5941a203.png">

**Simple Sites - Subdomain on WP.com**
<img width="136" alt="SimpleSite" src="https://user-images.githubusercontent.com/78876323/128932068-9812dcc0-d0be-47d9-82e8-2a7492049fd4.png">

We should consolidate all of these discrepancies IMO. And, I think it's worth considering removing the action bar completely or just displaying it only if the user is also logged into WordPress.com, or at least having an option to remove it, so we don't force a bar on a user's site design. Leaning towards the subscriptions widget and/or subscriptions block for the following actions might be beneficial to have parity with Atomic sites and to leave the decision of having a follow widget/block to the site owners.

For the action bar, when it's displayed, I believe Follow button always deserves a place either at the first level and within the overflow menu if there are more than 3 items already displayed. 4 items next to the overflow menu might be too much.

Let me know your thoughts!

**Comment by kwight** [comment]
> We should consolidate all of these discrepancies IMO.

True, we just have to watch that each aspect could be a project unto itself; for instance, adding the Action bar to Atomic seems like a great idea to me, but I'm wary of why it hasn't been done yet (would need some technical and MGS spelunking).

> simple sites with custom domains only display the overflow menu without "Follow/Following"

[I'm not sure about that](https://github.com/Automattic/wp-calypso/issues/55168#issuecomment-896299569).

> For the action bar, when it's displayed, I believe Follow button always deserves a place either at the first level and within the overflow menu if there are more than 3 items already displayed. 4 items next to the overflow menu might be too much.

We also have the "collapse" ability for the bar, which means not having to worry too much about the size of the full bar (when the user can collapse it to just the Edit and Ellipsis icons).

<img width="372" alt="Screen Shot 2021-08-10 at 3 03 28 PM" src="https://user-images.githubusercontent.com/349751/128941195-eb39799f-0f6a-4a10-990a-6ffd854b7163.png">

**Comment by kwight** [comment]
And by the way, any idea how you got a Stats button? Haven't seen that one myself at all. ¯\_(ツ)_/¯

**Comment by jasmussen** [comment]
Love the discussion here, and finding myself agreeing with points all around!

I do think there's an opportunity to rethink whether we need such an actionbar in the first place, or whether there's a better way to integrate it. Some "in the clouds" sketches on what else we could do would likely be useful. In my opinion this is worthwhile mostly because on mobile, giant cookie notices, notification prompts or newsletter dialogs feel like they are teaching us to dismiss or dislike things that float or aren't integrated parts of the webpage.

At the same time, there's likely some low-hanging fruit that could be picked as a step on the path, just to figure out if the heuristic for showing the button is buggy.

✨

**Comment by saygunnyc** [comment]
> And by the way, any idea how you got a Stats button? Haven't seen that one myself at all. ¯_(ツ)_/¯

Once in post details on a P2 that I'm a member of.

![replace](https://user-images.githubusercontent.com/78876323/129090637-0f97bd90-8c5c-4904-9cd9-9b06a5d308bf.png)

**Comment by saygunnyc** [comment]
> [I'm not sure about that](https://github.com/Automattic/wp-calypso/issues/55168#issuecomment-896299569).

Oh wow, it seems like we might have even more discrepancies between the two. Perhaps depending on a global level user, site settings? Note that I wasn't able to find any regarding the action bar behavior.

> We also have the "collapse" ability for the bar, which means not having to worry too much about the size of the full bar (when the user can collapse it to just the Edit and Ellipsis icons).

👍

**Comment by saygunnyc** [comment]
> I do think there's an opportunity to rethink whether we need such an actionbar in the first place, or whether there's a better way to integrate it. Some "in the clouds" sketches on what else we could do would likely be useful. In my opinion this is worthwhile mostly because on mobile, giant cookie notices, notification prompts or newsletter dialogs feel like they are teaching us to dismiss or dislike things that float or aren't integrated parts of the webpage.
> 
> At the same time, there's likely some low-hanging fruit that could be picked as a step on the path, just to figure out if the heuristic for showing the button is buggy.
> 
> ✨

I couldn't agree more with this sentiment! I am leaning towards questioning the need for the action bar as well. It also creates confusion over sites where users have a subscription form block and gets even more confusing when the user also has follow widgets, where all of those serve the same purpose.

**Comment by davemart-in** [comment]
Closing this issue as there is a project in the works to redesign the action bar: pe7F0s-1U-p2
