### ISSUE TITLE
Global Styles: Include Font Colors

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/wp-calypso#38714]
Allowing colors to be selected in Global Styles would be extremely helpful, as many new themes don't include the options for Colors & Backgrounds in Customizer.
Because of this, we now have to resort to CSS where a simple change in Customize > Colors & Backgrounds would have done the trick previously.

Here's how color selection looks in Colors & Backgrounds:

<img width="292" alt="Screen Shot 2020-01-08 at 2 26 46 PM" src="https://user-images.githubusercontent.com/15107387/71981238-a0710c80-322a-11ea-9f18-5ac09f9de919.png">

While I don't think that's the best format for Global Styles, hopefully this gives some context.

#### Context / Source
I've chatted with two users in the last 24 hours who wanted to change the color of their headers. We needed to use CSS because there was no way to change this with normal customization settings.

**Comment by simison** [comment]
cc @ItsJonQ @nosolosw @vindl @johnHackworth

**Comment by davipontesblog** [comment]
I am closing this in favor of the current efforts with core Global Styles.
