### ISSUE TITLE
Gutenboarding: Align suggestions properly under verticals container

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#38713]
The suggestions dropdown extends a little to the right of the container, as opposed to the design mocks.

Current:

<img width="875" alt="Screenshot 2020-01-08 at 3 00 06 PM" src="https://user-images.githubusercontent.com/1705499/71980017-c0eb9780-3227-11ea-9d1c-393d4fc9918b.png">

In mocks:

<img width="631" alt="Screenshot 2020-01-08 at 2 58 18 PM" src="https://user-images.githubusercontent.com/1705499/71980025-c77a0f00-3227-11ea-9fb2-667e8d1369b9.png">

**Comment by ockham** [comment]
Fixed by #38716.
