### ISSUE TITLE
Free domain incorrectly states renewal will cost $22

### ISSUE THREAD

**Issue by noteeth** [Automattic/wp-calypso#38731]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/new?ref=calypso-selector
2. Select "start now" to add new site
3. Select "Blog" for site type, and then continue
4. Enter "test" as keyword, and then continue

#### What I expected
I expect to see a free domain option.

#### What I see
The testxxx.home.blog option claims to renew at $22 after a year

#### Browser / OS version
Chrome 79/ MacOs Catalina 10.15.1

#### Screenshot / Video
<img width="1419" alt="Screen Shot 2020-01-08 at 2 27 28 PM" src="https://user-images.githubusercontent.com/16570939/72021733-8da70980-3223-11ea-9e87-9608904a1cf2.png">

**Comment by kriskarkoski** [comment]
We have made some changes to our signup in recent weeks and this issue looks to have be resolved by that work as free domains properly show as free for me.
