### ISSUE TITLE
Gutenboarding: add template title in page selector

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38742]
At https://wpcalypso.wordpress.com/gutenboarding

At page selector step, we'll need template names as per @dwolfe 's design (paObgF-RB-p2):

![image](https://user-images.githubusercontent.com/87168/72061415-80028a00-32de-11ea-80af-d610bd51096b.png)

Currently, we have:

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/87168/72061441-8d1f7900-32de-11ea-87d3-f50cae0b9770.png">

**Comment by simison** [comment]
@dwolfe @olesyabrk @joanrho curious to hear your thoughts on thumbnail height — should we show the whole thing, or cut it to fit the size in Dave's designs?

I suppose we'll eventually build a bigger preview/scroll mechanism for these so it might be ok to make them smaller at this point already?

**Comment by ockham** [comment]
I'll give it a stab.

**Comment by dwolfe** [comment]
Yep, the intent was to mimic the aspect ratio (if not necessarily the size) of the thumbnails in the layout picker current in production:

![Screen Shot 2020-01-09 at 11 50 36 AM](https://user-images.githubusercontent.com/1348738/72099836-4a59a300-32d6-11ea-95e6-1838db0a1f9d.png)

We have challenges that the layout picker doesn't have, of course, and one of those is to figure out how to do previews, like @simison mentioned. But generally, at this stage I'd love to see the thumbnail images in a 300 x 280 container; with the actual screenshot matching that width and clipped by the container, aligned to the top; and with a 56px footer bar at the bottom that contains the centered template name.
