### ISSUE TITLE
Gutenboarding: add spacing to design picker header

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38741]
At https://wpcalypso.wordpress.com/gutenboarding

Let's add little bit of air between the heading and grid here in design picker:

<img width="1542" alt="Screenshot 2020-01-09 at 11 32 12" src="https://user-images.githubusercontent.com/87168/72055705-fd74cd00-32d3-11ea-992e-fa622bc4bb61.png">

As per @dwolfe 's design (paObgF-RB-p2):

![image](https://user-images.githubusercontent.com/87168/72055730-05cd0800-32d4-11ea-8bb1-4d18c86d8074.png)

**Comment by dwolfe** [comment]
I don't know enough about how our styles are set up (yet) to make a specific suggestion, but the intent for that header area was to have 48px margins above and below the `design-selector__header-container`.
