### ISSUE TITLE
Gutenboarding: Page selector aspect ratio

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#38762]
Yep, the intent was to mimic the aspect ratio (if not necessarily the size) of the thumbnails in the layout picker current in production:

![Screen Shot 2020-01-09 at 11 50 36 AM](https://user-images.githubusercontent.com/1348738/72099836-4a59a300-32d6-11ea-95e6-1838db0a1f9d.png)

We have challenges that the layout picker doesn't have, of course, and one of those is to figure out how to do previews, like @simison mentioned. But generally, at this stage I'd love to see the thumbnail images in a 300 x 280 px container; with the actual screenshot matching that width and clipped by the container, aligned to the top; and with a 56px footer bar at the bottom that contains the centered template name.

_Originally posted by @dwolfe in https://github.com/Automattic/wp-calypso/issues/38742#issuecomment-572729112_

So to illustrate, roughly:

<img width="1417" alt="Screenshot 2020-01-13 at 12 29 09" src="https://user-images.githubusercontent.com/87168/72248708-7344a580-3600-11ea-883a-0390eb4efa59.png">

**Comment by simison** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/38805, with just little follow up left: https://github.com/Automattic/wp-calypso/issues/38895
