### ISSUE TITLE
SPT: Some translations break preview markup

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#38777]
Some translations break the HTML, causing entities to be shown and block validation errors:

![screen-shot-2020-01-10-at-12 37 03](https://user-images.githubusercontent.com/1398304/72179630-2bbce000-339a-11ea-9a73-8f20b8aeef77.png)

See paAmJe-Uu-p2

**Comment by akirk** [comment]
The broken blocks seem to be caused by out of sync cached block HTML (not translated) and blocks content (translated).

**Comment by obenland** [comment]
What's the best way to fix this?

**Comment by akirk** [comment]
D38293-code is an attempt to fix Spanish but I was unable to test it.

**Comment by obenland** [comment]
Oh, so escaped emoji entities is the problem?

The only way to test API changes with SPT is a local install with the FSE plugin activated and public-api sandboxed. 😬

**Comment by akirk** [comment]
No, the problem is the out of sync (translated) HTML and (untranslated) serialized data in the Gutenberg comment.

**Comment by obenland** [comment]
I updated D38293-code to fix all these things

**Comment by obenland** [comment]
Fixed in D38293-code and D38910-code
