### ISSUE TITLE
Syntax Highlighter Block: Cannot format MATLAB code.

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/wp-calypso#38788]
#### Steps to reproduce
- Go to My Sites > Posts > Add new post
- Select Syntax highlighter block
- Add a code and choose MATLAB as the language from block settings.

#### What I expected
- It should ideally view the formatted code on publishing. 

#### What happened instead
- The code isn't formatted. 
- The code falls out of the margin.
- No line breaks between two syntax highlighter blocks.
- Tested this with Maywood/Twenty-Twenty/The Writer. I could see the issue on all the themes.

#user-report Ticket #2622184 in zd with the user having this issue (Using Maywood theme)

#### Browser / OS version
Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

#### Screenshots
Unformatted code: 
![Screen Shot 2020-01-11 at 15 39 57](https://user-images.githubusercontent.com/49183855/72202716-c398f780-3488-11ea-872b-7a6f0fd01ef2.png)

![Screen Shot 2020-01-11 at 15 42 04](https://user-images.githubusercontent.com/49183855/72202736-f642f000-3488-11ea-8c6d-9731bdb1f180.png)

![Screen Shot 2020-01-11 at 15 45 06](https://user-images.githubusercontent.com/49183855/72202777-6f424780-3489-11ea-9c45-b42be4a102e0.png)

**Comment by kriskarkoski** [comment]
I believe we use a version of SyntaxHighlighter Evolved on WordPress.com. I tested the user's MATLAB example on Jurassic Ninja using that plugin and it caused an error:

<img width="1440" alt="Screen Shot 2020-03-12 at 10 22 06 PM" src="https://user-images.githubusercontent.com/1900444/76583641-266e3580-64b0-11ea-89ce-c80b44fac6f1.png">

On my test site the code wasn't formatted, but also didn't cause layout issues as in the screenshots above.

@mkaz I also tested your plugin and it worked as expected. Pinging you in case you have bandwidth to take a look at this issue given your expertise :)

**Comment by mkaz** [comment]
The Evergreen team (formerly Guardians) is managing the SyntaxHighlighter plugin so they might be able to help with the errors.

With the regards to my plugin, I saw this raised in another channel and provided some info, but not sure the priority of switching out, or if anyone is working on it. @simison might know?

**Comment by simison** [comment]
> [...] but not sure the priority of switching out, or if anyone is working on it.

No plans as far as I know. 

WordPress.com blocks are maintained by Grow focus tho, @lessbloat @obenland @creativecoder

**Comment by supernovia** [comment]
Noting another complaint here:
https://en.forums.wordpress.com/topic/bug-matlab-in-syntaxhighlighter-code-block/

This person is switching to C to see the code displayed properly.

**Comment by synora** [comment]
Noting that I'm still able to replicate this issue. I've tested with Twenty-Twenty and Twenty-Twenty One themes.

**Comment by obenland** [comment]
> The Evergreen team (formerly Guardians) is managing the SyntaxHighlighter plugin so they might be able to help with the errors.

@Automattic/evergreen Is this something you've come across before or could possibly help out with?

**Comment by jom** [comment]
I put up a fix for it in https://github.com/Automattic/syntaxhighlighter/pull/188. I _think_ the WPCOM version has diverged a bit, but this is an easy change to make so once approved I'll fix it on WPCOM.
