### ISSUE TITLE
Child Pages: Unable to set (no parent) after trashing parent

### ISSUE THREAD

**Issue by tijosh** [Automattic/wp-calypso#38789]
This applies when you have a parent page you want to delete altogether and make the child a top-level page. 

#### Steps to reproduce
1. Create two pages, make one a child of the other
2. Trash the parent page
3. Do not delete the parent page from the trash

#### What I expected

I can select `(no parent)` for the child to update its URL

#### What happened instead

For the child page, `(no parent)` is already selected, but the URL still shows `/parent-page__trashed/`, and I cannot click "Update" to make it a top level page.

#### Browser / OS version

Any

#### Screenshot / Video

![Screenshot](https://d.pr/i/2kG0OF+)

#### Context / Source

#17659723-hc

**Comment by kriskarkoski** [comment]
I was able to reproduce this in core. Opened issue at https://github.com/WordPress/gutenberg/issues/20855 and closing this one.
