### ISSUE TITLE
[Gutenboarding] Update new user endpoint

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38795]
Subtask of EPIC #38701

This task requires more clarity/investigation.

We might need to modify the `user/new` endpoint or response object.

We could reuse our work from passwordless signup (paWIov-6C-p2) and ask for an email only, but it's possible that we could pass a gutenboarding-specific request parameter instead of `is_passwordless`?

- [x] At the moment, we generate a username based on arrays of random words, e.g., `rabbitsaturnpizza`. If a user has entered information in the site title field however, this should take priority as a base for a user name. If a user has entered information in the site vertical field, this should take second priority. If no further information is available, then we can fall back on the existing random generator. We can probably reuse the existing `extra` field. See: https://github.com/Automattic/wp-calypso/blob/master/client/signup/steps/user/index.jsx#L199
- [x] ~Potentially a minor addition to `users/new` to add a specific "gutenboarding" user meta (TBD) flag to the user account.~ We'll set the signup flow property to `"gutenboarding"`
- [ ] Forking the welcome/verification emails to something Gutenboarding-specific. Related task: #38796 

Frontend task: #38794

**Comment by p-jackson** [comment]
Working on a diff to generate the username based on the site title or vertical: D37924-code

> Potentially a minor addition to users/new to add a specific "gutenboarding" user meta (TBD) flag to the user account.

I think we should leave out a new flag and use the `signup_flow_name` property to say it's `"gutenboarding"` does that seem reasonable @ramonjd ?

**Comment by ramonjd** [comment]
> I think we should leave out a new flag and use the signup_flow_name property to say it's "gutenboarding" does that seem reasonable

Perfectly reasonable :) Good idea!

**Comment by ramonjd** [comment]
> Forking the welcome/verification emails to something Gutenboarding-specific.

We're going to track email-related stuff here #38796
