### ISSUE TITLE
[Gutenboarding]: Integrate account creation/signup form

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38797]
Subtask of EPIC #38701

## Dependencies

#38794
#38792
#38795

Once we've developed a signup module/component, we can integrate it into the Gutenboarding signup flow.

Users will need to create an account **before** they jump into FSE, but we might like to nudge them if they're taking a long time in the headless Gutenberg editor.

We also need to be able to a trigger account creation modal from anywhere in the onboarding flow. 

## User experience

When we ask the user for their email address, think about what we're giving them return?

For example, we could couch the request by saying _"We just need your email so we can save your progress... we won't use it for evil! :)"_

## Tasks
- [ ] Define when we should require the user to sign in (e.g., after `n` time or `x` action)

**Comment by p-jackson** [comment]
Picking this up, looks like the next thing in the #38701 checklist.

My plan is to show the signup modal when the user clicks the "Create my site" and then sending them to `/start/frankenflow`, which means the user step will be skipped in frankenflow. This seems to be in line with MVP 1 here: pbAok1-8J-p2

**Comment by p-jackson** [comment]
I think this task is complete now. The signup modal is integrated with the rest of the gutenboarding flow, it's handling error responses, using locale and username hints gathered from gutenboarding.
Heads up @ramonjd I've closed this.
