### ISSUE TITLE
[Gutenboarding]: add analytics (tracks) 

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38799]
Subtask of EPIC #38701

Along with generating a temporary user account and site to allow users to interact with Gutenboarding, we’ll probably have to set up some way to track it all.

⚠️ We'll need to work out whether we're going to import [lib/analytics](https://github.com/Automattic/wp-calypso/blob/master/client/lib/analytics/index.js) into the project.

From the discussion in p1579140697040600-slack-gutenboarding I think the consensus is that:

- we start with just [tracks](https://github.com/Automattic/wp-calypso/blob/master/client/lib/analytics/index.js#L471) for Gutenboarding
- instead of pulling in the entire `lib/analytics` behemoth, we build a tiny tracks lib in @automattic/analytics package, which will furnish the necessary tracks methods:
   - `recordEvent`, `recordPageView`

### After account creation,  and reassign events triggered by the anonymous ID

For WordPress.com, before users sign up, we set a cookie that assigns to them an anonymous ID.

After sign up, [Calypso calls a method](https://github.com/Automattic/wp-calypso/blob/77318c9b32568459aeb80639f8e01a137b3a5ee1/client/lib/signup/step-actions.js#L481) called [identifyUser](https://github.com/Automattic/wp-calypso/blob/master/client/lib/analytics/index.js#L716) , which records the user’s new ID and username, both of which we send back in the API response after a successful account creation.

Tracks then (somehow) reassigns events triggered by the anonymous ID to the new user ID. 👍

We’d have to determine whether anonymous ID tracking in Gutenboarding before user sign up/sign in is acceptable.

Since it’s working currently on WordPress.com however, my guess is that it is appropriate. A conversion with folks from data might be enough to give us the greet tick.

### Event validation

Double check with the data team that our events and props are okay in light of the product.

## Related links

 p1579140697040600-slack-gutenboarding

Some initial investigation on anonymous IDs: pbxlJb-4t-p2

**Comment by ramonjd** [comment]
I think the consensus is that:

- we start with just [tracks](https://github.com/Automattic/wp-calypso/blob/master/client/lib/analytics/index.js#L471) for Gutenboarding
- instead of pulling in the entire `lib/analytics` behemoth, we build a tiny tracks lib in @automattic/analytics package, which will furnish the necessary tracks methods:
   - `recordEvent`, `recordPageView`
- if we're super lucky and nice, we'll get assistance from @jsnajdr / @Automattic/team-calypso 

See context in p1579140697040600-slack-gutenboarding

**Comment by roo2** [comment]
I'm making a start on pulling the track analytics code into the shared lib. `@automattic/calypso-analytics`
Slack discusion: p1579140697040600-slack-CNMU1UHHB
PR to refactor lib/analytics to be more tree-shakeable and remove the signup specific functions
https://github.com/Automattic/wp-calypso/pull/37913
