### ISSUE TITLE
Editor: Link to existing content component resizes width as you search

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3880]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Use the editor button "Insert/Edit Link"
3. Search for previous content
#### What I expected

Component width to remain the same
#### What happened instead

Component resizes as content is searched, and if content is found or not found
#### Browser / OS version

Chrome48  on OSX 10.11.2
#### Screenshot / Video

![link to existing content](https://cloud.githubusercontent.com/assets/128826/13626635/76c4b866-e60f-11e5-9bd2-f9c37492bbba.gif)

**Comment by aduth** [comment]
@alisterscott Are you still able to reproduce this? Do you think it's related to long titles? In my testing the titles wrap correctly:

![image](https://cloud.githubusercontent.com/assets/1779930/20797609/8738eac0-b7a9-11e6-8b7f-245b422ed9f3.png)

**Comment by alisterscott** [comment]
Thanks @aduth: I can no longer reproduce. Closing.
