### ISSUE TITLE
Add some new layouts to layout selector

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#38811]
I'm aware of [the ongoing work in core](https://github.com/WordPress/gutenberg/issues/17335) for the UI adding block patterns and layouts, but since [we have some layouts ready for the customers](https://github.com/Automattic/wp-calypso/issues/37782), it'd be great if we can add some of them to the current layout selector instead of waiting for the core UI.

Like what we did for the homepage layouts, some grouping should help though. Something like...

![page-layout-selector](https://user-images.githubusercontent.com/908665/72805374-9e577680-3c4a-11ea-98cc-f85499d1cf00.png)

It won't provide the best experience with the long list on the left, but it's kind of a shame to wait for the UI, and it might not be too bad as we don't yet have tons of new layouts :) If the long list is really a concern, eash section(group) could be a collapsible accordion that is opened as default.

I'll make a list of layouts that can be added as the next step. 

cc @apeatling @ianstewart @shaunandrews

**Comment by apeatling** [comment]
@iamtakashi Can you ping me on here when you have the list of layouts

**Comment by ianstewart** [comment]
@iamtakashi is the "About 1" "About 2" our general consensus on final choice for naming? That question isn't a critique — more just me playing catch up. :)

**Comment by shaunandrews** [comment]
For the grouped layouts, I'm thinking we might not need to expose the names at all. The group title is the descriptor, and the grid below is just a collection of options for that descriptor.

**Comment by iamtakashi** [comment]
> Can you ping me on here when you have the list of layouts

Thank you, @apeatling! Much appreciated ❤

 Here is the list of the layouts that I'm thinking to add.

**About Page Layouts**

- https://iamtakashinuxtest20191125111820.wordpress.com/layout-2/
- https://iamtakashinuxtest20191125111820.wordpress.com/layout-3-2/
- https://iamtakashinuxtest20191125111820.wordpress.com/layout-4/
- https://iamtakashinuxtest20191125111820.wordpress.com/layout-5/
- https://iamtakashinuxtest20191125111820.wordpress.com/layout-6

**Portfolio Page Layouts**
- https://iamtakashinuxtest2019112113719.wordpress.com/
- https://iamtakashinuxtest2019112113719.wordpress.com/layout-2/
- https://iamtakashinuxtest2019112113719.wordpress.com/lauout-3/
- https://iamtakashinuxtest2019112113719.wordpress.com/layout-4/
- https://iamtakashinuxtest2019112113719.wordpress.com/layout-5/
- https://iamtakashinuxtest2019112113719.wordpress.com/layout-6/
- https://iamtakashinuxtest2019112113719.wordpress.com/layout-7/
- https://iamtakashinuxtest2019112113719.wordpress.com/layout-8/

**Product Page Layouts**
- https://iamtakashinuxtest20191204103359.wordpress.com/
- https://iamtakashinuxtest20191204103359.wordpress.com/layout-2/
- https://iamtakashinuxtest20191204103359.wordpress.com/layout-3/
- https://iamtakashinuxtest20191204103359.wordpress.com/layout-4/
- https://iamtakashinuxtest20191204103359.wordpress.com/layout-5/
- https://iamtakashinuxtest20191204103359.wordpress.com/layout-6/

We should also have five new services page layouts by the end of the week.

--

I don't have a strong opinion on naming, and the idea from @shaunandrews sounds good to me too!

**Comment by ianstewart** [comment]
We currently _recommend_ the Menu Layout to all sites regardless of the site type.

![image](https://user-images.githubusercontent.com/545779/72561644-42b67300-386f-11ea-8b60-e39504011a78.png)

Is "recommended" the right label there?

**Comment by iamtakashi** [comment]
Many of the layouts that we currently have in the recommended section — About, Contact, Portfolio, Services, and Blog will soon to be grouped with new layouts. Then, Blank, Team, and Menu will be left so it'd make sense to move Team and Menu even they are on their own for a bit and we can quickly make some more Team and Menu layouts as well.

But then, the question would be where Blank should be placed?

**Comment by iamtakashi** [comment]
@apeatling I'm going to move all the layouts that I posted above to the master layout site along with the images used on them. I'll edit the urls once that's done and ping you again :)

**Comment by iamtakashi** [comment]
@apeatling I have added a bunch of new layouts to the master layout site. I've edited the URLs above. All the About, Portfolio, and Services pages are ready to go. 

But Product pages that use premium blocks (Simple Payments) are still drafts to be checked by @michaeldcain since the premium flows haven't been tested yet.

@michaeldcain, As requested, all the Product pages have been left as drafts for you. Could you let me know if there is anything I should do?

**Comment by iamtakashi** [comment]
Just to see what the selector would look like with the current ideas: 

![page-layout-selector](https://user-images.githubusercontent.com/908665/72722206-aee9ed00-3b75-11ea-8424-96a3f36e85f6.png)

As we suspected the list on the left is long. Is it ok as a temporary solution? Keep in mind that this will be a short-lived UI. I think we want to fill the empty slots quickly though.

**Comment by ianstewart** [comment]
>  If the long list is really a concern, each section(group) could be a collapsible accordion that is opened as default.

Perhaps we could continue recommending our best layouts in an open recommended section with the rest closed by default? Similar to core's block inserter?

**Comment by iamtakashi** [comment]
I updated the mockup after sharing it with Dotcom Design team.

Let's show all the layout on the left. The length isn't too much a concern at this moment, especially this is going to be a short-lived UI that will be replaced by the inserter that being worked on in core.   

I also considered using accordions or/and showing the first six layouts and hiding the rest in accordion. But since the length of the list isn't a big concern, it's not necessary. We can circle back if we hear a lot of complaints.

A search field was also suggested, but I honestly don't think it's necessary at this point. Again, let's keep the dev. cost minimum so that we can get this out asap.

The Blank is at the top, and the home pages are at the bottom now. The rest of the layouts are in A-Z order. Each page name is removed as the group title is now the descriptor. We're working on more blog, contact, menu layouts to fill the empty spots.

We could also recommend some layouts, but I feel we should get this out first without it, and run a test after we have a little more dev resource.

![page-layout-selector](https://user-images.githubusercontent.com/908665/72805374-9e577680-3c4a-11ea-98cc-f85499d1cf00.png)
