### ISSUE TITLE
New website: No WooCommerce plugin installed for the new website with eCommerce plan

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/wp-calypso#38824]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Create eCommerce new site (with eCommerce plan) under wordpress.com domain. 
3. Pay with credits.
4. Go to website admin.

#### What I expected
I expected the WooCommerce plugin to be installed and the website has some initial config for online-store. Or an invitation is expected at the dashboard for initial config.

#### What happened instead
The site looks like an ordinary blog

#### Browser / OS version
Google Chrome Version 79.0.3945.117 , OSX Catalina (10.15.2)

#### Screenshot / Video
Admin menu
![image](https://user-images.githubusercontent.com/3139099/72334375-4232a680-36ce-11ea-876d-c2ecb98a413b.png)

The site view
![image](https://user-images.githubusercontent.com/3139099/72336225-6479f380-36d1-11ea-8bc1-dfac8e77581f.png)

Site plan page
![image](https://user-images.githubusercontent.com/3139099/72336178-5035f680-36d1-11ea-809f-ae9024610ebe.png)

#### Context / Source
Tried to create a test woocommerce site for learning and experiments.
Feel free to ping me in a8c slack for details (vbelolapotkov)

**Comment by vbelolapotkov** [comment]
Update: tried to reproduce the issue again with a new site. And the behaviour is the same.
One little detail though is the checkout page is stuck in the `Processing` state (see screenshot below)

![image](https://user-images.githubusercontent.com/3139099/72338552-c76d8980-36d5-11ea-9f26-2fec5c0e5c87.png)

**Comment by zdenys** [comment]
I can reproduce the above never-ending checkout process with `Processing…
Almost there – we're currently finalizing your order.` message.

**Comment by JoshuaGoode** [comment]
A similar issue was fixed up last week. Linking here. 

* https://github.com/Automattic/wp-calypso/pull/38695

Internal discussion for previous issue:
* p9F6qB-4CC-p2
* p1578348423018900-slack-CCS1W9QVA

**Comment by GeoJunkie** [comment]
While working on the Happiness Outreach Project, I came across one that wasn't ATed. See site details in 2632030-zen
