### ISSUE TITLE
Stats: Insights NUX uses a fragile test to decide if you are eligable 

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#3882]
In #3848 we tweaked the way insights decides if we are in the nux to reflect a fix in the API to only count posts.

However, this test make niave assumptions about the number of posts a site might start with and as we introduce headstart this assumption is completely invalidated.

I think we need to change the code to use a flag set server side in the API rather than trying to infer something in the API where we have less info.

cc @kwight

**Comment by timmyc** [comment]
Indeed this logic is quite flawed - and was never liked from the start.  Just some background the NUX portion of stats was launched last spring just towards the end of the Stats team actively working on Calypso Stats.  This particular test was always something we wanted to circle back on.

> I think we need to change the code to use a flag set server side in the API rather than trying to infer something in the API where we have less info.

+1 here, having a meta flag that could be read through [preferences](https://github.com/Automattic/wp-calypso/tree/master/client/lib/preferences) would be much more ideal, and really would allow for making the stats nux experience more than just two states potentially.

**Comment by kwight** [comment]
Headstart is adding `_headstart_content_status` of `original` post meta to all the content is creates (posts and pages), and is swapping that for `updated` on changes (if a user updates a Headstart post with their on content, rather than just starting a new post, we want to reward them for that). Not sure if that can be used for preferences?

**Comment by kwight** [comment]
Oh, each Headstarted site will also have a blog option with counts:

```
array(
	'original' => array(
		'posts' => (int),
		'pages' => (int),
	),
	'updated' => array(
		'posts' => (int),
		'pages' => (int),
	),
)
```

These are adjusted when the post meta is changed also.
