### ISSUE TITLE
Signup offers random `.blog` domain as the free option

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#38827]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/.
2. Choose a site type, for example "Blog".
3. Enter a site topic in the input on https://wordpress.com/start/site-topic-with-preview, for example "home", and click the "Continue" button.
4. Enter a blog title in the input on https://wordpress.com/start/site-title-with-preview, for example "Home", and click the "Continue" button.
5. Enter a blog name in the input on https://wordpress.com/start/domains-with-preview. Note the free domain suggested when you do this.

#### What I expected

The free domain suggested would be either generic, or related to the information I entered earlier in the flow.

#### What happened instead

I'm offered a topic domain like `gntest0017photography.photo.blog` or `gntest0017drive.car.blog` which has nothing to do with the information I've provided.

#### Browser / OS version

FF 72 / macOS Mojave

#### Screenshot / Video

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1647564/72344264-b8340f00-36c8-11ea-8188-1da1a316585c.png">

#### Context / Source

I believe this behaviour discourages some people from signing up. You're offered a random domain that's nothing to do with your intended site, and there's no obvious way of changing it. You can either accept the weird domain, sign up for a domain that will eventually cost you, or go away.

**Comment by klimeryk** [comment]
While the suggestions can (and will be) improved, this is the expected behaviour when you select `Blog` as your site type. Please MGS for more details.
