### ISSUE TITLE
Gutenboarding: domain picker texts are centered

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#38834]
_(Let's keep this issue for new Automattic devs for practicing!)_

At https://wpcalypso.wordpress.com/gutenboarding domain picker dropdown texts are centered:

<img width="389" alt="Screenshot 2020-01-14 at 20 46 18" src="https://user-images.githubusercontent.com/87168/72372478-0835c480-370f-11ea-91d6-552f36d24b4d.png">

It used to look something like this (pretty old screenshot so details might be different):

<img src="https://user-images.githubusercontent.com/87168/72372508-197ed100-370f-11ea-829b-ebb122f3042c.png" alt="" width="300"/>

**Comment by nuwe1** [comment]
@simison I would like to work on this as my first issue. Could you please give more context on what has to be done?

**Comment by simison** [comment]
Hi there! If you don't mind, I'd like to reserve this as
developer-onboarding task for Automattic developer in a couple days. The
same with other "good first issue" with Gutenboarding label.

Hope you understand!

Thank you so much for offering to help!

**Comment by nuwe1** [comment]
Yeah sure!

**Comment by yansern** [comment]
Quick Update: This styling issue started to appear at renovate commit 520612ee916b6b30a11f41a784c68d380c73da76 and is possibly related to #19535.

CSS for domain-picker is loaded **BEFORE** the CSS from `@wordpress/components`.

![image](https://user-images.githubusercontent.com/1287077/72979502-c1b02c00-3dd8-11ea-88bf-6becf642aec5.png)

![image](https://user-images.githubusercontent.com/1287077/72979505-c543b300-3dd8-11ea-8a2c-64d7dc9bf4a5.png)
