### ISSUE TITLE
Post Link in Calypso shows as HTTP with Custom Domain

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#38833]
I had a customer today in the WordPress.com Live who reported that the post link in the Calypso post editor shows with http instead of `https` if you have a custom domain.

#### Steps to reproduce
1.  Open an existing or start creating a new post on a site with a custom domain set as primary
2. Click on the post link icon in the editor

#### What I expected

If the SSL is provisioned, the link should show with HTTPS as it does with in the Gutenberg editor:

<img width="815" alt="Screen Shot 2020-01-14 at 1 38 09 PM" src="https://user-images.githubusercontent.com/25575134/72371840-27aefc00-36d3-11ea-8b01-0f239623110f.png">

#### What happened instead

Although my domain was with provisioned SSL, the link was showing with HTTP:
<img width="868" alt="Screen Shot 2020-01-14 at 1 35 55 PM" src="https://user-images.githubusercontent.com/25575134/72371750-00f0c580-36d3-11ea-82fa-bc27b32c79f2.png">

If the site has no custom domain, the version that shows is the HTTPS one:

<img width="813" alt="Screen Shot 2020-01-14 at 1 40 24 PM" src="https://user-images.githubusercontent.com/25575134/72372005-8b392980-36d3-11ea-8bed-87aea3f1d6ef.png">

#### Browser / OS version

Google Chrome: Version 79.0.3945.117 (Official Build) (64-bit)

macOS Catalina: 10.15.2

#### Context / Source

Reported by the customer in 2632169-zen

**Comment by lancewillett** [comment]
Similar report in WP Admin: 8122-wpcom

**Comment by kriskarkoski** [comment]
@lancewillett Should we close this as wontfix for Calypso editor while keeping the Trac issue for Classic?

**Comment by lancewillett** [comment]
Yes, good call.
