### ISSUE TITLE
Blog Posts Block: Appears "Broken" at full width, with grid view

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38840]
Screenshot on a page with Twenty Twenty active, MacOS Chrome:

![image](https://user-images.githubusercontent.com/545779/72387378-0822ce00-36e9-11ea-8412-591d0aeda758.png)

The edges of the screenshot are the edges of the browser chrome.

I expected:

To have some sort of limit on the block built in to prevent this, perhaps matching the built-in columns?

**Comment by ianstewart** [comment]
cc @obenland @michaeldcain

**Comment by obenland** [comment]
Could I trouble you to move this ticket to https://github.com/Automattic/newspack-blocks/issues? Thank you!

**Comment by ianstewart** [comment]
No trouble at all. :) Moved:

https://github.com/Automattic/newspack-blocks/issues/334
