### ISSUE TITLE
Customer Home: Improve Mobile Download Card

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38861]
When visiting WordPress.com/home, the "Go Mobile" card should be improved in two ways:

1. Instead of linking to the app store, we should instead provide the option to SMS or email a link when the user is visiting on a desktop device. (We have examples on https://wordpress.com/me/get-apps )
2. Placement of the "Go Mobile" should have much higher priority placement when viewed in smaller viewports. For example folks should see this on their phone, without needing to scroll.

<img width="354" alt="Screen Shot 2020-01-15 at 10 47 01 AM" src="https://user-images.githubusercontent.com/1270189/72453295-78326200-3784-11ea-9001-fe8442915207.png">

For folks taking this, please also be aware of p3btAN-1c0-p2 which we may need to help with

**Comment by megsfulton** [comment]
Additional improvement suggestion - on mobile web, if we can detect the user's OS, display the correct store button rather than display both buttons.

**Comment by gwwar** [comment]
Oh gotcha, yes I think that should be possible @megsfulton. We can do a bit of sniffing with the user agent string. For desktop clients I assume displaying both would be acceptable?

**Comment by gwwar** [comment]
Testing the flows it looks like the SMS route has a download link, but the email provides both a download link and a magic login link. I might focus on email first, especially with the work that needs to be done in p3btAN-1c0-p2

**Comment by gwwar** [comment]
I might need to split out a few janitorials to tidy some of the request methods here

**Comment by gwwar** [comment]
@mmtr you're welcome to take the next part, which is adding another email button to the Go Mobile card, otherwise I can circle back.

**Comment by megsfulton** [comment]
>For desktop clients I assume displaying both would be acceptable?

Yep, that's great.
