### ISSUE TITLE
(8P) Search for Navigation/Site Settings

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38860]
It can be difficult to find the right pages to visit on WordPress.com to perform a particular site action. 

Let's allow folks to search for a setting or action to perform. We'll approach this in two steps. 

First, let's embed the [help FAB](https://a.cl.ly/v1uDOXZ5) directly on My Home:

![support-inline](https://user-images.githubusercontent.com/5634774/81288928-878b3300-9033-11ea-9d2d-d6f9f1e0a6c3.png)

After this is done (probably in another Issue/PR), let's revive @ramonjd's [PR](https://github.com/Automattic/wp-calypso/pull/31903) which included helpful hints for where to find things. We'll need to make sure we can translate it somehow.

**Comment by frontdevde** [comment]
For clarification:
The idea is to make the help section that shows up when pressing the FAB a permanent citizen of the Home.

![81288928-878b3300-9033-11ea-9d2d-d6f9f1e0a6c3](https://user-images.githubusercontent.com/1562646/81317079-b08be200-908c-11ea-836b-433cabf88c78.png)

**Comment by olesyabrk** [comment]
also want to link [this issue](https://github.com/Automattic/dotcom-private/issues/32) that deals with the same problem

**Comment by olesyabrk** [comment]
OK, [a few options here](https://www.figma.com/file/RJunD2teJ28W3dUZiyeT27/Support-in-Customer-Home?node-id=833%3A4320) to match the rest of the Customer Home design patterns:

![image](https://user-images.githubusercontent.com/51215741/81730854-08d33300-9443-11ea-93cf-536a10a4aa58.png)
This is a close replica of the existing FAB layout. My main concern here is that with Quick Links and the Support link modules expanded, we're not only overwhelming the customer with a neverending parade of links, Support is also falling below the fold, so we're losing discoverability which is the main purpose of this project.

Having said that, I designed a minimized Support version:

![image](https://user-images.githubusercontent.com/51215741/81731184-71baab00-9443-11ea-9071-98248d633e5a.png)
That would keep it above the fold, but hide the content behind an extra click, so a little bit of a trade-off there.

Which brings me to a design that @danhauk introduced in earlier Customer home iterations:

![image](https://user-images.githubusercontent.com/51215741/81731812-54d2a780-9444-11ea-83ca-961fd097bba9.png)

Do we need those extra links or can we get away with just a search field? I think it looks cleaner and still maintains its discoverability and usability. 

In addition to that, I have iterated on combining Support and Quick Links since there is quite a bit of overlap and thematically it makes sense to display them together which remains my preferred approach to solving for both discoverability and layout improvements.

![image](https://user-images.githubusercontent.com/51215741/81731881-716edf80-9444-11ea-8116-6e29d1a917b7.png)

Pinging @davemart-in , @lcollette and @jancavan for feedback

**Comment by davemart-in** [comment]
I'm a fan of this one for [the v1](https://a.cl.ly/9ZuEybZB). My goal for the v1 is just to prove whether embedding this UI directly on My Home leads to more people interacting with support. Once we verify that hypothesis, I'm happy to invest more time into optimizing this section further.

> I have iterated on combining Support and Quick Links since there is quite a bit of overlap and thematically it makes sense to display them together

Interesting exploration. Personally, I'm not a fan of combining them. There may be some overlap, but they serve different purposes in my mind. Quick links are meant to be a dependable, constant, unchanging list of links that I can return to much more akin to navigation. The help section is more ephemeral. I'd love for it to eventually adapt based on your previous search patterns, what we know about you, and things like pages you've visited recently. I know that is a bit down the line, but I see this as a separate function from Quick links.

**Comment by olesyabrk** [comment]
@davemart-in thanks for your feedback, sounds good to me. @lcollette and @jancavan -- do you have anything to add? If not, then we can submit the following as the official design for this ticket: 
![image](https://user-images.githubusercontent.com/51215741/81743820-25796600-9457-11ea-8413-930403147721.png)

**Comment by davemart-in** [comment]
Good point @jancavan. Thoughts @olesyabrk?

**Comment by olesyabrk** [comment]
@jancavan excellent point, can we limit the search results to 6 and if the search result wraps to a second line, we can just truncate it to keep the height consistent? What do you think @obenland @davemart-in ?

**Comment by obenland** [comment]
We could also fix the hight of the box and scroll results

**Comment by lcollette** [comment]
Could we cap at 5 or 6 results, with a link to see all results prepopulated at /help? I hesitate to add inline scrolling as there are inherent usability issues when scrolling content in a small area.

**Comment by rickybanister** [comment]
The help box has five suggested articles displayed by default and results are always capped at four articles. 

It does jump, as @jancavan mentions based on the length of article titles and translations, even though there's a fixed number of results. If there are no results, it gets even taller, showing 'no results' with the five default articles below. 

I did a quick inspector hack, reversing the order of the mobile nudge and support card. With a task present the top of the support box is 893 pixels down from the top of the viewport with quick links closed. With quick links open, the default, both the mobile card and search are off screen on my laptop monitor. I don't know if that's a blocker, but it is something to consider for all of the proposed solutions. 

The mobile nudge, while we're at it, is the odd one out in this sidebar. For new customers, they're introduced to the apps via the checklist. For more tenured customers, we now have task cards. Perhaps we put an item in the backlog to remove the mobile prompt from the sidebar and try it in a different location. Perhaps even outside of a card in the footer of the page? On mobile web there's a much more aggressive overlay (at least in the editor). 

Another thing I miss in the solutions proposed here is a way to teach the help fab. I think we can introduce customers to it without any duplication and perhaps without inadvertently increasing any burden on support (there's already a contact us link on the My Home screen). Is there a way to hint at the existence that this same content will be accessible via the FAB on other screens? This could come through the presence of the blue icon in or near the box, or some other affordance. Without that I feel we're asking customers to relearn a piece of UI once they leave the Home page.

**Comment by olesyabrk** [comment]
@rickybanister Thanks for jumping in. You're bringing up important points re: discoverability of FAB. The current scope of this project was decreased to the following per @davemart-in:

> My goal for the v1 is just to prove whether embedding this UI directly on My Home leads to more people interacting with support. Once we verify that hypothesis, I'm happy to invest more time into optimizing this section further.

Which is not to say we're abandoning more improvements to this section, but instead we're experimenting on it for MVP. 

I also am curious if we need a mobile card so prominently displayed on the customer home. @lcollette and @danhauk what are some of the metrics you've seen of our users interacting with it? How essential is it?

**Comment by olesyabrk** [comment]
I agree with @lcollette re: scrolling in a small area. Since removing the mobile card is not on the table for this project, let's cap the results at 6 and truncate the longer results to keep it one line per item.

cc: @davemart-in @obenland

**Comment by jancavan** [comment]
Are we retaining current behavior when clicking on the search results links?

**Comment by olesyabrk** [comment]
@jancavan no, we're going straight to modal like this:

![image](https://user-images.githubusercontent.com/51215741/81871309-62fbf300-952c-11ea-9f1b-baf7219db20b.png)

**Comment by getdave** [comment]
I'm going to be taking a look at the code implementation here.

As there's been a fair amount of discussion regarding Design and UX I'd like to clarify that the following is the "accepted direction".

Firstly the initial visual state is as per:

 ![image](https://user-images.githubusercontent.com/51215741/81743820-25796600-9457-11ea-8413-930403147721.png)

...then once a search result is clicked the corresponding support page shows up in a Modal:

![image](https://user-images.githubusercontent.com/51215741/81871309-62fbf300-952c-11ea-9f1b-baf7219db20b.png)

I also note that the FAB icon is hidden on this view (presumably to avoid duplication?).

@olesyabrk Is there anything else I need to consider before I dive in here?

**Comment by getdave** [comment]
Documenting some useful locations in code:

* Sidebar "Support" card - `client/my-sites/customer-home/cards/features/support/index.jsx`

**Comment by olesyabrk** [comment]
@getdave thanks for jumping in on this. For search results to avoid the card from jumping heights, let's go with this:

> I agree with @lcollette re: scrolling in a small area. Since removing the mobile card is not on the table for this project, let's cap the results at 6 and truncate the longer results to keep it one line per item.

And to answer your question:

>I also note that the FAB icon is hidden on this view (presumably to avoid duplication?).

This is to follow the existing behavior with the FAB, skipping the preview.

**Comment by gwwar** [comment]
> Should we extract portions of Inline Help code to reusable, shared components that are not coupled to either "Inline" or "Customer Home" versions of the widget?

@getdave Use your best judgement but I would recommend copy/pasting into a new component since it sounds like needs may diverge for the two components. If there are shared pieces that makes sense you can then pull those out and refactor as needed with a fun 🔪PR. (eg https://github.com/Automattic/wp-calypso/pull/41855 https://github.com/Automattic/wp-calypso/pull/42255 )

If there's another iteration of the support card, if it's pretty drastic update making a different component, before switching them out fully in views has been helpful in past sprints.

For the most part code reuse generally isn't that helpful vs the coupling/bugs it introduces when folks don't test in all areas or aren't aware of usages.

We also have updated documentation for the server pieces of My Home in PCYsg-qpk-p2 though don't hesitate to reach out to Serenity for a review or chat.

**Comment by olesyabrk** [comment]
@getdave reposting [the Figma doc](https://www.figma.com/file/RJunD2teJ28W3dUZiyeT27/Support-in-Customer-Home?node-id=833%3A2037) for colors/font sizes/details. 

Small change from the final version is replacing the generic Help icon with the FAB icon to aid discoverability. 

![image](https://user-images.githubusercontent.com/51215741/82372825-8235cd00-99d1-11ea-905c-2a8865261031.png)

**Comment by lcollette** [comment]
Thanks, @olesyabrk for bringing in the Fab! 

Some minor feedback/suggestions:

- Rename Support to Get help for clarity
- Remove the underline from links (to match the other blue links on My home)
- Update placeholder text from "Search for help" to "Search support articles" to better represent the functionality

**Comment by olesyabrk** [comment]
@getdave , I agree with @lcollette suggestions, here is the updated mock. 

![image](https://user-images.githubusercontent.com/51215741/82385564-3e4dc280-99e7-11ea-875c-5950c7b7c439.png)

[Figma](https://www.figma.com/file/RJunD2teJ28W3dUZiyeT27/Support-in-Customer-Home?node-id=833%3A2037)

**Comment by getdave** [comment]
> If there's another iteration of the support card, if it's pretty drastic update making a different component, before switching them out fully in views has been helpful in past sprints.

@gwwar I'm concerned because [as Dave indicates](https://github.com/Automattic/wp-calypso/issues/38860#issuecomment-627569447), this is not something we're 100% certain will be retained. It would be a fair amount of effort to decouple and refactor the components vs sharing them. @davemart-in would you be happy for me to circle back to a refactor once we're confident the implementation on the Customer Home is here to stay?

To be clear, I don't mind putting in the effort, but it's important we understand that this will have a _significant_ knock-on effect in terms of the delivery time for this work. Therefore, if we're not fully committed then are we happy to invest this effort?

**Comment by davemart-in** [comment]
Let's hold off on investing any more into this. For this v1 pass, as long as it works, I'm 👍. Once we have some more data, I'm happy to circle back and clean things up.

**Comment by getdave** [comment]
@davemart-in Question regarding tracking. Currently, we are tracking when a user submits an empty search string. Do we want to continue with this or would you prefer I filter out empty strings to avoid noise?

**Comment by getdave** [comment]
> @getdave , I agree with @lcollette suggestions, here is the updated mock.
> 
> ![image](https://user-images.githubusercontent.com/51215741/82385564-3e4dc280-99e7-11ea-875c-5950c7b7c439.png)
> 
> [Figma](https://www.figma.com/file/RJunD2teJ28W3dUZiyeT27/Support-in-Customer-Home?node-id=833%3A2037)

@olesyabrk Any chance you can granted me access to that file?

**Comment by davemart-in** [comment]
> Question regarding tracking. Currently, we are tracking when a user submits an empty search string. Do we want to continue with this or would you prefer I filter out empty strings to avoid noise?

If it's not too difficult @getdave I'd say filter out empty strings.

**Comment by davemart-in** [comment]
The big thing we want to know is: Did the click or search come from the inline support card (within Customer Home), or via the floating action button version (in the right hand corner).

**Comment by gwwar** [comment]
> @gwwar I'm concious that Dave indicated, this is not something we're 100% certain will be retained.

To clarify copy/paste here is totally fine in it's own folder 👍We can always delete unused code later.

I naturally assume devs have an urge to refactor or aim for code reuse which isn't always needed. This of course can be done at a later date if the code has value and needs more changes.

**Comment by olesyabrk** [comment]
@getdave, here is my feedback and responses:

- The links should be identical to the font, size, color, and hover of the other links on customer home. See below:
![image](https://user-images.githubusercontent.com/51215741/82614416-a5e94680-9b7c-11ea-9415-96d4efb3be5b.png)
- More help link takes you here: https://wordpress.com/help
- > The search results are all left aligned with no horizontal padding. However this "breaks" the keyboard navigation (using down arrows) "selected" state visuals. See existing FAB.

Not sure what this means. The links should have the focus status of other links on the Customer Home, no dark blue background. 
- Placeholder text is not the replacement for labels, it's not read by screen readers, and the contrast rules don't typically apply there if there are other cues. "Get help" above the search field is an indicator for that. If we observe user confusion post implementation, we will try a more descriptive label. 
- Let's drop the placeholder text on smaller screens altogether.
- Let's keep the box height consistent. If there are fewer results, there will be white space. It's temporary tho, so I don't see a problem there, @lcollette any objection to that?
- Let's max results to five. 

Thanks for reaching out, let me know how it goes! Good job!

**Comment by getdave** [comment]
Thanks for feedback. Now we've moved to a specific implementation [I've responded to the design points over on the PR](https://github.com/Automattic/wp-calypso/pull/42365/#issuecomment-632699664).

**Comment by frontdevde** [comment]
Reopening this issue as it was closed by an accidental merge.

**Comment by getdave** [comment]
Update: the client side code to add the new Card is in place. However the new card will not show up until we deploy the Phab diff (see `code-D43941`) that enables the card on the various variations of the "My Home" section via the layout API.

Next steps to follow.

**Comment by getdave** [comment]
This is now in production https://github.com/Automattic/wp-calypso/commit/3574c1b761a7f3f230e76971a87afe5078a0b086

**Comment by zdenys** [comment]
Is it best to open a new issue for a tiny improvement of this feature? I noticed this difference and hope it can be addressed:

| Search for `Menu`  | Search for `Menus` |
| ------------- | ------------- |
| ![](https://d.pr/i/VUSAuq+)| ![](https://d.pr/i/8yMsQw+)|

**Comment by olesyabrk** [comment]
@zdenys yes, please, and a bit more background on this would be helpful. @jancavan worked on the expansion of the Support card.

**Comment by zdenys** [comment]
@olesyabrk what I meant is that for the search `menu` the `Edit my menu` link appears, but for `menus` it does not and I guess it should as users may type `menus`, not only `menu`. 

Also, is there a list of keywords for which the `Show me where to` shows up and for which suggestions can be offered?

**Comment by rickybanister** [comment]
@getdave could you share how the string matching works, is it hard coded or is there any synonym matching happening? If not, that would be a wonderful future improvement.

**Comment by obenland** [comment]
@zdenys @rickybanister This file contains all suggestions and keywords, `menus` could probably be added here: https://github.com/Automattic/wp-calypso/blob/8e806f2ce055e30db6a3eb7e627d052ce48c7169/client/blocks/inline-help/admin-sections.js#L78

**Comment by rickybanister** [comment]
cc @boonerang in case you feel like contributing any synonyms to the help search to spur on your nomenclature discussion.
