### ISSUE TITLE
Signup: No free subdomain option shown for certain words

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#38878]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/free/
2. At Step 4 of 5, type `okay`, `blog`, `test`, `testX`(where `X` is any single digit), or many other 4-5 character-long words

#### What I expected
See a free subdomain `.wordpress.com` or `.home.blog` or similar

#### What happened instead
The subdomain option `.home.blog` is offered as paid along with other TLDs

#### Screenshot
![](https://d.pr/i/O17O8G+)
_Link: https://d.pr/i/O17O8G_

#### Context / Source
 #dogfooding

**Comment by delputnam** [comment]
Thanks for reporting.

This is due to some of the recent changes we've made regarding how we generate these .blog subdomain suggestions and not being getting good, available suggestions for some of these very short or common query terms.

Proposed fix in: code-D37815

**Comment by delputnam** [comment]
D37815 has been deployed. So, I'll close this issue.
