### ISSUE TITLE
Notifications: orange dot returns even after reading all notifications (in WP Admin only)

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#38873]
As reported in 2631315-zen, the user reports that the orange dot next to the bell icon in the top right corner never goes away, even after reading all the notifications. This only happens in WP Admin dashboard. After refreshing the page, the dot returns.

![](https://d.pr/i/brdUrN+)
_Link: https://d.pr/i/brdUrN_

#user-report

**Comment by caimin-j** [comment]
The user kindly sent us some screenshots which are available via the ZD ticket. I'm not posting them here as they don't add anything to @zdenys screenshot above.
