### ISSUE TITLE
Plans: Multiple requests to the same endpoint

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3888]
When testing #3839 I noticed that we make multiple requests to the endpoint at `/site/:site/plans`:

<img width="555" alt="screen shot 2016-03-09 at 10 21 49" src="https://cloud.githubusercontent.com/assets/275961/13632590/50415140-e5e2-11e5-9a35-59ced33f6544.png">

We should find where this extra request is coming from and ensure we only make one.

**Comment by Tug** [comment]
I added a breakpoint in `fetchSitePlans` and I have noted the following components triggering the fetch:
- `my-sites/upgrades/cart/popover-cart.jsx` (1 time)
- `my-sites/plans/main.jsx` (2 times)

**Comment by drewblaisdell** [comment]
> `my-sites/plans/main.jsx` (2 times)

One of these requests is to the generic plans endpoint, so I think we're only fetching `sites/%s/plans` once from `plans/main`.
