### ISSUE TITLE
TFT: Change Layout Button limiting number of homepage layouts

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#38889]
#### Steps to reproduce
1. Starting at URL: My Site > Design > Themes
2. Activate the Shawburn theme
3. Go to My Site > Site > Pages and open the homepage in the editor
4. Click on 'Change Layout'

#### What I expected

I expected to find all of the FSE themes available under `Homepage Layouts` or `Reommended Layouts`

![layouts-expected](https://d.pr/i/rFJ3T8+)

#### What happened instead

In certain accounts, we only see five of the FSE layouts. Shawburn is not included. This means the user cannot activate the Shawburn homepage layout. They get a broken version of it instead. I can log into the same site with two different users and get different results, meaning some users get the correct experience while others don't.

![layouts-limited](https://d.pr/i/KExCio+)

This was tested with multiple user accounts and themes.

#### Browser / OS version

Chrome 79.0.3945.117
Mac OS 10.15

#### Context / Source
 
#painpoint.
#user-report

**Comment by zdenys** [comment]
This happens for sites that have a non-English language set up (because headstart translations are missing). More discussion and details here p1579253842001100-slack-onboarding-exp

**Comment by zdenys** [comment]
In the meanwhile users who experience the above can switch their site to English language in _WordPress.com > My Sites > Manage > Settings > Language_, them pick the layout they want (as all of them should become available) and then switch back to their preferred language again.

**Comment by obenland** [comment]
> I can log into the same site with two different users and get different results, meaning some users get the correct experience while others don't.

This should be fixed now, templates are always dependent on site languages.

The case of missing templates in mag16 languages is tracked in #37782.

Not sure if this ticket can be considered a duplicate?

**Comment by davipontesblog** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/39161
