### ISSUE TITLE
Template preview content expanding past preview frame (and sometimes too close to the frame).

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38884]
Template preview content is expanding beyond the preview frame or right up to the edge of the frame and looks either "very broken" or "broken" in Chrome on MacOS. Some examples …

Expanding beyond the template preview …

![image](https://user-images.githubusercontent.com/545779/72561383-b310c480-386e-11ea-9f2b-39ae82d9124f.png)

Too close to the edge of the preview …

![image](https://user-images.githubusercontent.com/545779/72561428-d471b080-386e-11ea-8bdf-924ada3925ad.png)

cc @apeatling @iamtakashi @alaczek

**Comment by apeatling** [comment]
I can't reproduce this at all on Mac Chrome. Anything specific I need to do?

**Comment by iamtakashi** [comment]
I can see the same thing as Ian does when the viewport is narrower like the screenshot. It seems a responsive issue in the preview.

**Comment by ianstewart** [comment]
I can reproduce this in Mac Chrome with both the Maywood theme and the Independent Publisher 2 theme at a browser window size of 1366x768. It's most noticeable on the Menu template and the Barnsbury template.

Definitely looks like a responsive issue in the preview. Barnsbury will start to almost look right if only you can get your browser window past the 2200px width. :)

**Comment by ianstewart** [comment]
> Anything specific I need to do?

- Open Chrome on a Mac with browser resolution set at 1366x768
- Create a new account and site from WP.com
- Add a new page 
- Click on Menu and Barnsbury, the preview should look like the following …

Maywood active …

![image](https://user-images.githubusercontent.com/545779/72825647-03a46b00-3c3d-11ea-867e-5cea11f15824.png)

![image](https://user-images.githubusercontent.com/545779/72825664-0bfca600-3c3d-11ea-8090-10f0ff721fd7.png)


Independent Publisher 2 active …

![image](https://user-images.githubusercontent.com/545779/72825562-dfe12500-3c3c-11ea-8fb0-de0249742aa0.png)

![image](https://user-images.githubusercontent.com/545779/72825576-e7a0c980-3c3c-11ea-804e-f3baf68028c1.png)

**Comment by ianstewart** [comment]
cc @michaeldcain who has started looking at this one.
