### ISSUE TITLE
Gutenboarding: i18n for new users

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#38909]
When a non logged-in user is going through Gutenboarding we should use the <s>browser language to handle i18n and also suggest an alternate language based on different variables (eg: location, campaign code, other tracking info, etc).</s> locale passed in the URL

**Actions:**
- [ ] <s>detect browser language (see an [experimental PR ](https://github.com/Automattic/wp-calypso/pull/37756/files#diff-4287893adde6391414d6d81302e7cf2eR26-R35)that introduce this) and possibly extract this as a reusable utility
- [ ] define how to set an alternate locale to suggest to the user
- [ ] display locale suggestions like in the [current signup](https://github.com/Automattic/wp-calypso/blob/master/client/signup/main.jsx#L512-L514)</s> 

Locale detection is already done in the landing page https://github.com/Automattic/wp-calypso/issues/38909#issuecomment-580727458

**Comment by simison** [comment]
We might actually get away with just having language as URL parameter, much like current `/start` flow does. I elaborated more in the master issue: https://github.com/Automattic/wp-calypso/issues/37665

**Comment by akirk** [comment]
I'd think it's favorable to keep it the current way. Language selection is harder than it appears and we've got a flow established that works. See also my comment on https://github.com/Automattic/wp-calypso/pull/37756/files#r373471313

**Comment by simison** [comment]
> I'd think it's favorable to keep it the current way.

Yep, I agree and I wrote to that effect in [master issue](https://github.com/Automattic/wp-calypso/issues/37665).

Just for clarity, I'll quote you also here from your PR comment:

> Traditionally the detection is done on the landing page https://wordpress.com/ that might redirect to localized landing pages which then link to the onboarding with the language as a parameter (e.g. https://wordpress.com/start/fr). We then use the `LocaleSuggestions` class to offer a switch into the right language.

**Comment by simison** [comment]
...so basically todo for this issue: we need that kind of language fragments (e.g. `/gutenboarding/fr/`) and setting UI language to those from the beginning of the flow.

**Comment by sirreal** [comment]
Do we need to support language route parts, or subdomains? `es.calypso.localhost:3000` seems to work out of the box with #39282.

**Comment by simison** [comment]
>Do we need to support language route parts, or subdomains? 
> es.calypso.localhost:3000/gutenboarding seems to work out of the box with #39282.

@akirk do you know answer to this?

**Comment by akirk** [comment]
@sirreal How is the language set for logged-out users?

**Comment by sirreal** [comment]
Ignore my question, we won't go with subdomains here.

**Comment by sirreal** [comment]
With #39571, we now use the locale slug from the URL path to localize gutenboarding.
