### ISSUE TITLE
Blank Page Template: Does Not Apply When You Switch From Another Template

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#38913]
When you switch to the blank layout from another layout, it does not get applied to the page. I am not sure if it is intentional but you can start with the blank layout so should not you be able to switch to it as well?

#### Steps to reproduce
1. Starting at URL: Add a new page to a site
2. Select any layout except the blank layout:

<img width="1539" alt="Screen Shot 2020-01-17 at 3 54 59 PM" src="https://user-images.githubusercontent.com/25575134/72645487-c2ad0d80-3941-11ea-8bcf-44bb8a6b8243.png">

3. After that, you can apply the layout and update the page
4. Next, select the option "Change Layout":

<img width="1523" alt="Screen Shot 2020-01-17 at 4 01 20 PM" src="https://user-images.githubusercontent.com/25575134/72645879-af4e7200-3942-11ea-9ec2-74744a12baed.png">

5. Select the Blank Layout and click the option "Use this layout":

<img width="1517" alt="Screen Shot 2020-01-17 at 4 02 58 PM" src="https://user-images.githubusercontent.com/25575134/72645960-e6248800-3942-11ea-9866-c5dff7bd6da5.png">

#### What I expected

The layout to change to blank

#### What happened instead

The layout does not apply and shows the previously selected the layout - even after you publish the page:

<img width="1517" alt="Screen Shot 2020-01-17 at 4 04 28 PM" src="https://user-images.githubusercontent.com/25575134/72646021-0fddaf00-3943-11ea-8639-188c35bdd547.png">

#### Browser / OS version

Chrome: Version 79.0.3945.117 (Official Build) (64-bit)
macOS Catalina 10.15.2 (19C57)

**Comment by apeatling** [comment]
We'll get this fixed, closing since we have a duplicate in #38913
