### ISSUE TITLE
Cart: Loading state

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#3891]
The the cart loading state still needs placeholders:

<img width="349" alt="screen shot 2016-03-09 at 12 06 58" src="https://cloud.githubusercontent.com/assets/275961/13634748/8f3489c8-e5ef-11e5-9319-ea5e5a7cb976.png">

Pinging @breezyskies since I'm not sure who owns this.

**Comment by breezyskies** [comment]
I had designs for the sidebar version of the cart in the old repo, but looks like the issue was closed instead of moved over:

<img width="287" alt="30ca3e22-3c18-11e5-990e-03215865fafe" src="https://cloud.githubusercontent.com/assets/3011211/13640583/13da2744-e5ca-11e5-9233-a410df4668f5.png">
