### ISSUE TITLE
Stats: Flag icons not showing under Traffic tab

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#38927]
#### Steps to reproduce
1. Open up the Stats > Traffic area
2. Check the countries listed under the Countries area 

#### What I expected
To see flag icons next to the countries listed

#### What happened instead
No flag icons show next to the countries listed

#### Browser / OS version
Firefox 72.0.1
macOS 10.15.2

#### Screenshot / Video
Simple site: ![](https://d.pr/i/d81CQQ+)
Atomic site: ![](https://d.pr/i/bqtaaT+)

#### Context / Source
A user came to chat to mention it, and I was able to reproduce it both in Simple sites and Atomic sites.

**Comment by kriskarkoski** [comment]
Another report in 17979119-hc. I've added some labels and will drop in the Calypso Slack channel for visibility.

**Comment by ajaykj** [comment]
Another report in 17198587-hc.

**Comment by ajaykj** [comment]
Could it be https://github.com/Automattic/wp-calypso/pull/38920 as I see the flags are showing in https://github.com/Automattic/wp-calypso/pull/38919 but not in https://github.com/Automattic/wp-calypso/pull/38921?

**Comment by Aurorum** [comment]
Came here to report this but found this issue open instead - using Chrome and experiencing it. :)

**Comment by chatoxz** [comment]
Another one zen 2644941
