### ISSUE TITLE
Editor: Vague Error Message When Trying to Publish a Sticky Post with Password on a Simple Site

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#38926]
#### Steps to reproduce
1. Create a new sticky post for a simple site
2. Change the visibility to Password Protected
3. Try to Publish the post

#### What I expected
To get an error message telling me that I can't set a sticky post to have a password, which is what happens with AT sites: 

[![Error When Publishing on AT](https://d.pr/i/2rWueT+)](https://d.pr/i/2rWueT)

#### What happened instead
A generic error that says "An unknown error occurred" appears

[![Error When Publishing on Simple Site](https://d.pr/i/CGJIUG+)](https://d.pr/i/CGJIUG)

#### Browser / OS version
macOS 10.15.2 / Chrome 79.0.3945.130 / Firefox 72.0.1
Windows 10 / Chrome 79.0.3945.117

#### Context / Source

#2642710-zen

**Comment by donalirl** [comment]
Another case of this in #19343058-hc

**Comment by lancewillett** [comment]
Good find. Moving this to the Manage board for consideration.

**Comment by yansern** [comment]
Phab patch for this fix here. D47683-code

**Comment by razvanpapadopol** [comment]
Closing this issue as D47683-code is now live on simple sites.
