### ISSUE TITLE
Purchases: Allow to pick stored card in Edit Payment Method

### ISSUE THREAD

**Issue by janm6k** [Automattic/wp-calypso#3892]
Currently, it is only possible to use new card in the Edit Payment Method form of a purchase. However, user might want to use a stored card (or possibly other payment method in the future).

Because this will need an API on backend, I am putting this to Gold backlog, despite the Purchases label.

**Comment by fabianapsimoes** [comment]
There are designs for this task here: https://github.com/Automattic/wp-calypso/issues/293
