### ISSUE TITLE
Instagram embeds broken on Atomic sites

### ISSUE THREAD

**Issue by vajrasar** [Automattic/wp-calypso#38942]
Using the Block Editor on the Business plan (AT) the Instagram Embed does not show preview and gives an error, whereas the embed actually works if you publish the post/page or preview the post/page.

**Steps to reproduce:**
1. Check on a site with a Business plan (AT)
2. Copy and Instagram URL
3. Paste the URL in content, and it should expand with an error
4. Or, use Embed Block and paste in it, and it should show and error

**Expected:**
The preview of the Instagram image.

**Result:**
Error: `Sorry, this content could not be embedded.` 

Please note: This does not happen on the Simple Sites and it works as expected. The issue seems to be with the Business AT sites.

Thread: #2646912-zen

**Comment by kriskarkoski** [comment]
This looks to have been fixed, I could not reproduce on my Atomic test site pasting the URL or adding to Instagram block.
