### ISSUE TITLE
Block inserter: poor search results for "form"

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38955]
Results when searching for "form" in the block inserter …

![image](https://user-images.githubusercontent.com/545779/72756058-b9b27b00-3b91-11ea-99f6-a27ce1c6e80b.png)

I expected … 

![image](https://user-images.githubusercontent.com/545779/72756079-cfc03b80-3b91-11ea-99e7-a88f9a9cf6f4.png)

… to see a form as the top result, not "formatting".

**Comment by ianstewart** [comment]
cc @apeatling @johnHackworth

**Comment by simison** [comment]
This needs to be improved in core: https://github.com/WordPress/gutenberg/issues/14868

**Comment by kriskarkoski** [comment]
Closing in favor of linked core issue
