### ISSUE TITLE
Editor: iterate on status chevron menu

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3895]
Several users (and even team members) have reported they were confused by the chevron menu in the editor. It's the downward-pointing triangle next to "New Draft" and "Published 4 Months Ago" in these screenshots:

![status menu draft](https://cloudup.com/cUlS5SppiUx+)

-----------------

![status menu published](https://cloudup.com/cnFwVURHOfD+)

Opening the menu gives you some advanced options:

![status menu draft open](https://cloudup.com/cDr9VoqjhjR+)

----------------

![status menu published open](https://cloudup.com/cAS8aVU62Ag+)

The issue is that people just aren't finding these options... or even seem aware of the menu at all. I think it's partially because the status message (e.g., "Published 4 Months Ago") just doesn't seem like a dropdown select element. And it's also because these advanced options don't necessarily seem related to a published/draft message.

**Comment by apeatling** [comment]
This seems like it would fit fine as a separate menu that can be expanded, just like any other menu below. The discoverability would be far higher.

**Comment by folletto** [comment]
I agree this might be an issue, but I'd avoid creating a new accordion box just for these options. Let's see if we can find a design that optimizes for both uses. Might be as simple as moving something inside an existing box, and changing the trigger to a cog or something (which was one of the earlier iteration we did with Matías).

**Comment by mtias** [comment]
Yeah, and moving the sticky post to the header action icon tray which we didn't finish because of time.

**Comment by apeatling** [comment]
Why is there aversion to a new menu in the accordion?

**Comment by folletto** [comment]
It's simply that the number and scope of the items in the sidebar has to be carefully balanced. 

These features are not commonly used, so they shouldn't be top-level items. Remember that we already have a "More option" accordion item. ;)

**Comment by apeatling** [comment]
Okay, agreed they are not commonly used. Looking at the menus we have there, is anything other than tags/categories commonly used? Most of the options are going to be rarely touched there, so it seems like more rarely used options would not be out of place. "Rarely used" is also very dependant on the person.

**Comment by apeatling** [comment]
Chatted on Slack to @folletto about this. Moving content out of the sidebar makes sense, to keep the sidebar about post meta, and content area about... content.

One thing that I'm not clear on: Why adding more specific menus to the sidebar is worse that having the chevron menu that is hidden and hard to find, and a basement-like menu with "More Options".

My feeling is that even if there are more menus, if they are clear and specific that is better than not being able to find something, and then having to hunt through the "More Options" menu.

I would also follow that up with the need to allow users to personalize the ordering of this sidebar in the future. Let them decide what is most important for them, because it's different for everyone (something I was trying to elude to earlier).

**Comment by mtias** [comment]
Yes, another thing we should do is keep the state of that panel stored in preferences (like html/visual mode) so that fi you leave ti open it's open next time you load editor.

**Comment by apeatling** [comment]
The cog icon is sort of an improvement, but it still doesn't look like a menu. @mtias How are you planning on testing if it's easier to find now?

**Comment by mtias** [comment]
Also #4186, moving sticky post to action bar. We can see impact of the two. As for general testing, hard to measure convincingly since the original issues is only a partial estimation, but we can set up a couple user tests.

**Comment by rralian** [comment]
Iterations implemented in #3979 and #4168. We should circle-back to see the how the buttons are used, but I'm closing the iteration task. I also think we could just ask happiness for qualitative feedback to see if they anecdotally get fewer questions about sticky posts and revert to draft, as those seem like the more commonly-needed actions in this menu.
