### ISSUE TITLE
Press This Bookmarketlet should allow for Image Selection

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38951]
As a follow up to https://github.com/Automattic/wp-calypso/pull/31148 

Using the PressThis bookmarklet no longer allows the user to select images from the media selector

https://wordpress.com/settings/writing
<img width="1191" alt="53654409-fc9ff300-3c4d-11e9-8599-1ac802f331d9" src="https://user-images.githubusercontent.com/1270189/72750286-4dc01a80-3b71-11ea-9783-d1ca4ec91692.png">

https://en.support.wordpress.com/press-this/

We should also consider whether it's worth retiring the bookmarklet in favor of browser extensions, or share buttons from the published page.

**Comment by cathymcbride** [comment]
Adding to Manage Backlog to discuss @gwwar's suggestion of : "We should also consider whether it's worth retiring the bookmarklet in favor of browser extensions, or share buttons from the published page."

**Comment by cathymcbride** [comment]
@davemart-in is no longer able to repro so closing
