### ISSUE TITLE
Plans: plans page design iterations

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3896]
Incorporate monthly pricing into the page.

Extra credit: provide context about reasons for upgrade if someone linked from a particular place (e.g., like the storage progress bar).

/cc @adambbecker @drw158

**Comment by apeatling** [comment]
With this, lets also think about how we can re-arrange our plans around plugins. See the plan for plans wireframe, and lots of good thinking in #3840 along with a list of the "plugins" we currently offer and could highlight as such https://cloudup.com/cVezc37pNRy

**Comment by adambbecker** [comment]
Good ideas regarding the plugins. I'll be keeping an eye on #3840 as that progresses and I think there will definitely be some things to bring over into the plans page.

Taking a look at the plans wireframes, I think they're looking really good and shouldn't need too much tweaking. They actually highlight the various plugin differences pretty well towards the bottom of the page and I think that is the place that houses a good bit of potential with the crossover with #3840.

How I'm thinking that could work is that each row of the table that represents a set of plugins could be expandable. So when someone hovers over that row, if they click, it opens up a panel that showcases the various plugins, informs which plan those that are included under the plan / upgradable plans, and also gives an immediate place to upgrade if that's appealing.

Here's an idea of how that could look (wireframe snippet):

![screen shot 2016-03-11 at 4 36 53 pm](https://cloud.githubusercontent.com/assets/1427136/13716313/4a73d9fa-e7a8-11e5-8db3-9948f8f2d0e0.png)
