### ISSUE TITLE
Media: progress bar for storage limits

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3897]
In wp-admin we show users their storage usage and limits.

![wp-admin storage numbers](https://cloudup.com/cPEqnjXyCI1+)

We don't have anything like this in calypso yet. We need to figure out where this should go (an existing section), make it look decent, and it should link to the plans upgrade page.

We may at some point want to create a dedicated "media" section, but this is out of scope for this particular issue.

Fun idea... we could probably have a clever image for going over the limit... like stuff leaking out the side of the progress bar? Maybe dumb... I dunno. :-)

/cc @adambbecker @drw158 @gwwar

**Comment by apeatling** [comment]
There's a reasonable spot to put the status in the media modal right now:

<img width="896" alt="screen shot 2016-03-10 at 4 54 16 pm" src="https://cloud.githubusercontent.com/assets/1464705/13689846/cdee4324-e6e0-11e5-8434-0803028c646e.png">

**Comment by gwwar** [comment]
related rest api diff: D1287-code

**Comment by gwwar** [comment]
@adambbecker added some other options
![quota_line2](https://cloud.githubusercontent.com/assets/1270189/13893829/f0f269c4-ed1e-11e5-931d-279fd61340e2.png)
![quota_line1](https://cloud.githubusercontent.com/assets/1270189/13893833/0522b41c-ed1f-11e5-9f5d-5a87a210ab17.png)
![quota_circle](https://cloud.githubusercontent.com/assets/1270189/13893835/08269016-ed1f-11e5-87dd-61472c85c98a.png)

**Comment by drw158** [comment]
The second one is nice. Would this be hidden once an image is selected? The Edit button is displayed there I think.

**Comment by gwwar** [comment]
> The Edit button is displayed there I think.

You're right. I'll try to place it there for now. We can let it display when no items are selected.
