### ISSUE TITLE
Domain Price in New Checkout Not Indicated as first year only

### ISSUE THREAD

**Issue by kelliepeterson** [Automattic/wp-calypso#38978]
Stated at https://horizon.wordpress.com/

selected Business, searched a domain, selected a .blog, added the personal plan. 

I expected to see that the domain name was only included for the first year. 

Instead, there was no indication of that. 

![Screen Shot 2020-01-21 at 7 08 06 AM](https://user-images.githubusercontent.com/3022756/72817709-15771580-3c1f-11ea-8c44-07793809032b.png)

@sirbrillig, @nbloomf, @fditrapani

**Comment by fditrapani** [comment]
Thanks for documenting this for us Kellie. Here's a design we have to address this:

![image](https://user-images.githubusercontent.com/6981253/73093488-a0207480-3eac-11ea-8d36-3af70ea8f00e.png)
Figma link: https://www.figma.com/file/MhywbVRJLQGEyhZiArLR0v/Checkout-Design?node-id=38%3A783

**Comment by sirbrillig** [comment]
For the record we've started moving toward this with some preliminary work in D39946-code and #39916.

**Comment by sirbrillig** [comment]
Here's the current work: #39943
