### ISSUE TITLE
Media Library: Informing Users that Files in the Library are Public

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#38974]
Many users don't realize that everything they put into the Media Library can be accessed by anyone.

I believe we should explicitly inform users that content uploaded to the Media Library is Public. There could be a short notification on top of the Media Library users could read and then close - so it won't clutter the interface.

Thank you.

#### Context / Source

Discussions with users on 1:1s, observations from tickets and chats.

#anecdote #user-report

**Comment by Aurorum** [comment]
I opened #38989 for this issue, which would include a warning about this in the Guided Tours section. 

<img width="551" alt="Screenshot 2020-01-21 at 20 17 15" src="https://user-images.githubusercontent.com/43215253/72840063-69b7df00-3c8b-11ea-85d1-c67ad094a6bf.png">

**Comment by ivan-ottinger** [comment]
Thank you very much! That looks great!
