### ISSUE TITLE
New checkout: Contact form not validation checked

### ISSUE THREAD

**Issue by kelliepeterson** [Automattic/wp-calypso#38981]
Stated at https://horizon.wordpress.com/

selected Professional segment
searched a domain
selected a .org
added the personal plan
filled in cc details
filled in contact information
clicked to proceed

I expected the contact form to be validated

It was not validated. 

![Screen Shot 2020-01-21 at 7 41 56 AM](https://user-images.githubusercontent.com/3022756/72819135-89b2b880-3c21-11ea-9c97-130c818a4f90.png)

@sirbrillig, @nbloomf, @fditrapani

**Comment by kelliepeterson** [comment]
Actually, the form will validate upon submission, but just one field at a time.

**Comment by nbloomf** [comment]
This should be fixed by #39842.
