### ISSUE TITLE
New checkout: Upon removing plan the payment method is lost

### ISSUE THREAD

**Issue by kelliepeterson** [Automattic/wp-calypso#38980]
Stated at https://horizon.wordpress.com/

selected Business segment
searched a domain
selected a .blog
added the personal plan
deleted personal plan

When I removed the personal plan the payment method was lost. 

![Screen Shot 2020-01-21 at 7 19 59 AM](https://user-images.githubusercontent.com/3022756/72818583-9387ec00-3c20-11ea-81f7-96a27ad8283e.png)

@sirbrillig, @nbloomf, @fditrapani

**Comment by fditrapani** [comment]
I tested this again and it doesn't seem to be the case anymore — we've made a lot of changes since this was reported.. When I remove the plan, the payment method doesn't go away.
