### ISSUE TITLE
New checkout: New flow not supported on domain only purchase at /domains

### ISSUE THREAD

**Issue by kelliepeterson** [Automattic/wp-calypso#38983]
Started at https://horizon.wordpress.com/domains

searched a domain
selected a .com
chose domain only
rec'd error message "We're sorry, but an unexpected error hs occurred."

I expected to be directed into the registration path. 

![Screen Shot 2020-01-21 at 8 07 59 AM](https://user-images.githubusercontent.com/3022756/72821288-29257a80-3c25-11ea-88f4-71fb195c5cc5.png)

Note: tried again by selecting "new site" as an option and was directed into the new checkout flow as expected. 

@sirbrillig, @nbloomf, @fditrapani

**Comment by sirbrillig** [comment]
Reproduced. The specific error is "TypeError: Cannot read property 'slug' of null" from the line `selectedSite.slug` in the checkout controller. It is followed by the debug message `calypso:layout Chunk checkout could not be loaded`.

I fixed the error in #38991 but there's an inherent issue where we assume we have a site when performing various operations. I'll need to study the no-site checkout in more detail to see how to make it work properly.
