### ISSUE TITLE
FSE: broken layout of template part editor navigation links.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#38988]
When navigating to the template part editor in Dotcom FSE, the styles and layout of the navigation links are broken.  This may be a result of the recent Gutenberg update.

![Screen Shot 2020-01-21 at 1 32 52 PM](https://user-images.githubusercontent.com/28742426/72832477-f4301c80-3c52-11ea-8b36-6a8b5b6fe3ef.png)

**Comment by noahtallen** [comment]
+1 this is an issue on more than one theme

**Comment by noahtallen** [comment]
Fixed in #39157
