### ISSUE TITLE
New checkout: Contact Form Phone Validation Errors

### ISSUE THREAD

**Issue by kelliepeterson** [Automattic/wp-calypso#38982]
Building on this issue: https://github.com/Automattic/wp-calypso/issues/38981

Started at https://horizon.wordpress.com/

selected Professional segment
searched a domain
selected a .org
added the personal plan
filled in cc details
filled in bad contact information
clicked to proceed
Clicked button to pay $48
Fields were checked and got validation errors. 
Corrected them one by one until I got to the phone number field, which I could not correct. 

![Screen Shot 2020-01-21 at 7 45 33 AM](https://user-images.githubusercontent.com/3022756/72819848-d2b73c80-3c22-11ea-9f37-13de92f11a96.png)

@sirbrillig, @nbloomf, @fditrapani

**Comment by fditrapani** [comment]
We have made a number of updates to our checkout since this was reported. This issue has been resolved.
