### ISSUE TITLE
Menus: allow creation of empty page when editing menus

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3899]
When first doing setup, it would be nice if rather than having to create pages first, you could start by creating your menus. Currently you can only add an item to a menu if it already exists (post/page/category/link). But you could be editing your menu and decide "Oh, I need a 'bio' page". You should be able to create an empty "bio" page from the menu.

**Comment by folletto** [comment]
Also there's already a controller to do that built in, just showing up for one item — and now looks odd:

![screen shot 2016-03-15 at 14 28 30](https://cloud.githubusercontent.com/assets/4389/13781146/3cfb67b0-eaba-11e5-974f-41bdd68dc16b.png)

**Comment by folletto** [comment]
Also: I've tried to create the page, but then I clicked on "Pages" and didn't show up. However it was created on the front-end.

Still, in the Menu UI, showed up as `New Page [ Create Page]`, not as a proper separate page.

**Comment by apeatling** [comment]
@artpi Are you currently looking at this one?

**Comment by artpi** [comment]
Yes, right now I'm implementing @mtias and @folletto suggestions in #4034 . It turned out to be waaaay more complicated, but should push within 2-3 hours

**Comment by apeatling** [comment]
Thanks, just came here to link to #4034 :)

**Comment by apeatling** [comment]
@artpi Closing this one since #4034 has been merged. :ship:
