### ISSUE TITLE
Site Settings: Viewers list missing when site is private

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#39]
The Site Visibility setting for a private site in Calypso does not display the viewers list like we do in WP Admin. Viewers are preserved when toggling a site from private to public and back to private again so it is important to have this information available so site admins understand who can view their site. With People Management launching soon this could be as easy as adding a link to the Viewers tab in People Management below the setting for now.

Here's what it looks like in WP Admin:

![image](https://cloud.githubusercontent.com/assets/7233112/11223507/46b981c6-8d3e-11e5-89ce-9d0967edd09b.png)

And here's Calypso:

![image](https://cloud.githubusercontent.com/assets/7233112/11223513/4a3c5aa8-8d3e-11e5-9570-04aa82ffa358.png)

It should link to /people/viewers, but we need to think about the language we use to make it clear that there are already viewers on a site when that's the case and display a count.  I think we can take a look at the 'Delete Site' interface in /settings for inspiration here.

**Comment by alisterscott** [comment]
People management is now in Calypso, but this information isn't summarised on the Site Settings page. 

This enhancement still stands.
