### ISSUE TITLE
Customer Home: Collapse site tools on mobile viewports

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39005]
The current layout of the Site Tools on the mobile viewport of Customer Home takes up a large amount of vertical space - almost two full viewport heights.

<img src="https://user-images.githubusercontent.com/448298/72857315-4725c600-3c8b-11ea-9816-a4ba5c1833a7.png" width="300" /> <img src="https://user-images.githubusercontent.com/448298/72857321-4ab94d00-3c8b-11ea-84f5-98016e0aae50.png" width="300" />

For these smaller viewports, we should compact the Site Tools as much as we can to improve usability and reduce the amount of scrolling necessary.

1. The Site Tools are collapsed by default on mobile
<img width="386" alt="image" src="https://user-images.githubusercontent.com/448298/72857157-c5ce3380-3c8a-11ea-993d-0dee94b0348f.png">

2. Opening the Site Tools menu reveals the options in a more compact button (ignore the change in button text here, use the existing buttons)
<img width="388" alt="image" src="https://user-images.githubusercontent.com/448298/72857231-08900b80-3c8b-11ea-92f8-478defc46316.png">

**Comment by Aurorum** [comment]
PR for this in #39075. :)
