### ISSUE TITLE
Settings: add page for Reading Settings

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3900]
We're missing a couple of settings that sometimes come up... "infinite scroll" and "Posts per page" ". We can also move over "related posts".

Note: these shouldn't be ported over directly, but first we should consider if they can go into Customizer fields first.

**Comment by apeatling** [comment]
Posts per page in general should be on this settings page.

**Comment by rralian** [comment]
We didn't get to this in the support iteration... I'm releasing it from the milestone but leaving it as an open item for us to circle back to. Not adding it to the next iteration, but we can prioritize it if/when we want to.

**Comment by drw158** [comment]
In general, we should think about renaming it. Reading was never clear to me, makes me think of Reader.

If we add a new section, I propose we combine SEO, Import, and Export into one tab, Tools.

## Posts per page jetpack

I could not find this, can we get a screenshot of the setting?

## infinite scroll

![screen shot 2017-01-23 at 4 01 13 pm](https://cloud.githubusercontent.com/assets/618551/22224813/9be8ea6e-e185-11e6-952e-6995de8bec56.png)

**Comment by lancewillett** [comment]
Noting that some of the Reading settings from wp-admin have moved into Customizer, and we don't need to duplicate it. Such as Static Front Page.

**Comment by lancewillett** [comment]
Here's a story from @kathrynwp to help illustrate this:

> When setting up a new site, I want to decide how many blog posts are displayed on the blog page, and how many portfolio projects are displayed on the portfolio. I can’t find a spot to change those numbers in Calypso, and I don’t know that WP Admin exists, so I have to find the relevant support pages (separate ones for blog and portfolios) and make my way to an interface I’ve never seen before. This leaves me confused about why there are two redundant dashboards, and whether it’s important for me to familiarize myself with the second one — this literally happened when my mom set up her site. Or if I’m not search-savvy, I have to contact support for help finding the settings.

I think we shouldn't add Calypso site settings that duplicate Customizer settings, though. So before adding a Reading setting like Posts per Page we should consider adding that to Customizer — including drafting a proposal for that to be in core WP, as well, not just a WP.com/Jetpack feature.

**Comment by lancewillett** [comment]
@melchoyce  shared this mockup of Posts per Page number setting in Customizer:

https://marvelapp.com/e1a1bd/screen/11733810

**Comment by kriskarkoski** [comment]
We also need to port (and update) the now incorrectly titled "Logged out users" setting that disables the follow option for both logged-out and logged-in users despite what the text says:

<img width="837" alt="screen shot 2017-02-16 at 5 50 58 pm" src="https://cloud.githubusercontent.com/assets/1900444/23045023/d1325b44-f470-11e6-9c16-28f0266c655a.png">

It looks like the functionality was updated sometime after the logged-out actionbar with following was launched, but the text was not updated to reflect that it hides both logged-in and logged-out now. We should also either remove the setting from WP Admin or update the title and text to clarify what it does now.

**Comment by lancewillett** [comment]
Posts per page could also go into Pages -> Home as a direct way to tie it to setting the home page.

> I’d like to easily set a number of “posts per page” for the home page of my site. Right now I think I have to use wp-admin (can’t remember.)
> Maybe I could add it here on the Home Page setting.

<img width="773" alt="screen-shot-2017-02-14-at-16-12-13" src="https://cloud.githubusercontent.com/assets/66797/23045952/1ed8962c-f464-11e6-9589-317106d4509a.png">

**Comment by lancewillett** [comment]
Ran into the Logged-out Follow thing today — was looking at my site https://simpledream.net and couldn't understand why the Follow links in actionbar were hidden. Turns out in wp-admin Reading Settings I'd toggled it off (not sure why).

I couldn't see a way to turn this back on in Calypso.

**Comment by lancewillett** [comment]
https://github.com/Automattic/wp-calypso/issues/3900#issuecomment-280490035

> We also need to port (and update) the now incorrectly titled "Logged out users" setting that disables the follow option for both logged-out and logged-in users despite what the text says:

Let's not show this setting at all any more, and turn the Follow links on/off intelligently in the actionbar.

**Comment by lancewillett** [comment]
Good ideas from @mattsherman 

> I worry about these settings being hidden in a “Settings” item in the popover. But, we could increase discoverability of this if we were to list some of the key settings in the Blog Posts list row (where “Your latest posts, shown on homepage”). Would have to be careful not to clutter this up too much though.

> Another option would be to make the “Blog Posts” itself clickable, taking you to the settings page. This would somewhat mirror the behavior of clicking on a page to edit it.

**Comment by lancewillett** [comment]
With D4527-code WordPress.com sites no longer show the Logged-out Follow wp-admin option.

**Comment by lancewillett** [comment]
Anecdote from @kathrynwp 

> When setting up a new site, I want to decide how many blog posts are displayed on the blog page, and how many portfolio projects are displayed on the portfolio. I can’t find a spot to change those numbers in Calypso, and I don’t know that WP Admin exists, so I have to find the relevant support pages (separate ones for blog and portfolios) and make my way to an interface I’ve never seen before. This leaves me confused about why there are two redundant dashboards, and whether it’s important for me to familiarize myself with the second one — this literally happened when my mom set up her site. Or if I’m not search-savvy, I have to contact support for help finding the settings.

@melchoyce Shared a mockup of what this would look like in the Customizer

<img width="1161" alt="screen shot 2017-04-13 at 08 39 12" src="https://cloud.githubusercontent.com/assets/66797/25012251/bc42605a-2024-11e7-8de0-21c078d981b2.png">

**Comment by rickybanister** [comment]
We've already built Infinite Scroll for Jetpack sites. I'd love to sync up about this issue, since I think we can avoid adding the Reading tab to settings.

**Comment by lancewillett** [comment]
>  I think we can avoid adding the Reading tab to settings

**Comment by lancewillett** [comment]
I split out this specific task: #13569

**Comment by designsimply** [comment]
Quick follow-up to note that the "Posts Per Page" setting was added to Settings > General in #13718, r155891-wpcom, https://github.com/Automattic/jetpack/pull/7154 and moved to Settings > Writing in #13916. Here is a screenshot of how it looks now for reference:

![screen shot 2017-05-18 at thu may 18 1 59 14 pm](https://cloud.githubusercontent.com/assets/1119271/26221090/8330f276-3bd2-11e7-8e9b-5b90e833d22d.png)
<sup>Seen at https://wordpress.com/settings/writing/design5279.wordpress.com using Firefox 53.0.2 on Mac OS X 10.12.4.</sup>

**Comment by designsimply** [comment]
Since infinite scroll was mentioned specifically, I checked on it and it doesn't appear to be available in Calypso yet. Here's how it looks in wp-admin for reference:

![screen shot 2017-05-18 at thu may 18 2 04 57 pm](https://cloud.githubusercontent.com/assets/1119271/26221267/27dabc80-3bd3-11e7-9ea0-527238143ccf.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/options-reading.php using Firefox 53.0.2 on Mac OS X 10.12.4.</sup>

Also noting that the related image in the support documentation is old and this section should be updated when the infinite scroll setting is added to Calypso. See https://en.support.wordpress.com/infinite-scroll/#disabling-infinite-scroll (<a href="https://cloud.githubusercontent.com/assets/1119271/26221401/9812798e-3bd3-11e7-806f-60c8d151e7bd.png">screenshot</a>)

**Comment by designsimply** [comment]
A lot of changes have been happening in Settings lately! 🎉

Here is an audit of wp-admin > Settings > Reading:

1. Front page displays → Customize > Static Front Page ([screenshot](https://cloud.githubusercontent.com/assets/1119271/26223857/3ab14e50-3bdd-11e7-84a1-d3679d826f47.png))
2. Blog pages show at most → Settings > Writing ([screenshot](https://cloud.githubusercontent.com/assets/1119271/26223880/4e8c4a38-3bdd-11e7-83a3-8f5f47aa2798.png))
3. Syndication feeds show the most recent → missing in Calypso.
4. For each article in a feed, show → missing in Calypso.
5. Site Visibility → Settings > General > Privacy ([screenshot](https://cloud.githubusercontent.com/assets/1119271/26223910/62cbdb4e-3bdd-11e7-8504-545dd0ea8548.png))
6. Related posts → Settings > Traffic ([screenshot](https://cloud.githubusercontent.com/assets/1119271/26223923/707377fc-3bdd-11e7-8013-fe307a54dee4.png))
7. Infinite Scroll Behavior → missing in Calypso.
8. Enhanced Feeds → missing in Calypso.
9. Follower Settings → missing in Calypso.

I suspect the following settings will not be moved. Can you confirm?

* Syndication feeds show the most recent
* For each article in a feed, show 
* Enhanced Feeds
* Follower Settings

**Comment by rickybanister** [comment]
Infinite scroll will get fixed up for .com sites and the posts per page setting will be moved to live with post types. 

I can't speak to the other missing items you mention, @designsimply could you clarify who the 'you' in your question is?

**Comment by designsimply** [comment]
Anyone working on the project who feels confident about making a decision about those settings is who should reply. I would consider this open for discussion and something worth discussing but wouldn't assign it to any one person or team. A decision can be reversed in the future if needed. The reason for the ask is that closing the gaps between wp-admin and Calypso is currently high priority.

**Comment by rickybanister** [comment]
@lancewillett or @shaunandrews any thoughts on those last remaining Reading settings—does anyone have a sense of whether they need to be migrated to a new place? If they are requirements I can help wrangle solutions and new homes for them.

**Comment by designsimply** [comment]
Looking again. It would probably be good to keep "Syndication feeds show the most recent" and "For each article in a feed, show" and I would remove "Enhanced Feeds" and "Follower Settings" unless there are good arguments to keep them.

**Comment by lancewillett** [comment]
My vote is to not move those final four at all, and use smart defaults for all WP.com feeds. If people want to customize it further — they could eventually fit better with a WP.org site running Jetpack, use a plugin to do those advanced changes.

**Comment by rickybanister** [comment]
I like the sound of that.

**Comment by lancewillett** [comment]
Closing this issue now since it was an "umbrella" issue, and smaller tasks and changes can be tracked separately.
