### ISSUE TITLE
Framework: implement "preview" everywhere

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3901]
We have an excellent in-page preview component that we use for the editor. We should use this in other areas where it is helpful for people to preview their content. Examples include post-list, pages-list, menus, etc.

**Comment by mtias** [comment]
cc @ehg @mcsf :)

**Comment by folletto** [comment]
A note: the component still has some bugs which I feel should be sorted before diving more into using it (#3707, #2129, #2001, #568, #312, #316, and to a lesser extent #2013, #3220).

I've also noticed that in some instances two scrollbars show up (remember to always work with visible scrollbars), and in Firefox I noticed (but I can't reproduce consistently) that with the trackpad the scrolling sometimes doesn't work until the page behind has scrolled completely.

**Comment by rralian** [comment]
This seems more like a goal than a concretely achievable task. I think specific integrations make more sense as trackable items. I'm removing this from the plans iteration 0 milestone for now. @mtias up to you if you want to keep this item open on its own.

**Comment by mtias** [comment]
@rralian I've worked on #4140 adding a `layoutFocus` for previewing that is the general approach. Anything else we can track separately.
