### ISSUE TITLE
Gutenberg: explore, refine, and clean up topbar

### ISSUE THREAD

**Issue by olaolusoga** [Automattic/wp-calypso#39021]
**Goal**
Refine the Gutenberg top bar. It's important we keep the top bar clear, and concise so users know it is solely used for high level document management. If we allow any UI component in the top bar it will degrade the experience to the point that the top bar loses value, and importance. By cleaning up the noise in the top bar, creating guidelines, make things contextual, and introducing mechanisms that will keep the order, we can ensure that the top bar component will continue to evolve in a self sustaining way.

**Description**
The top bar is an important component in the Gutenberg editor experience. It contains contains document-level actions like Editor mode, save status, global actions for undo/redo/insert, the settings toggle, and publish options.

As the editor, and Gutenberg continues to expand, we need to keep the top bar free from unnecessary UI components—from core, and 3rd party plugins— that reduce its importance. 

With dotcom buidling a custom editor based off core gutenberg parts, we can improve the UX, serving a stronger, more streamlines exp.

**Example of top bar noise**
![Screen Shot 2020-01-22 at 1 21 33 pm](https://user-images.githubusercontent.com/1382943/72931428-d5ea1f80-3d2b-11ea-8314-3f9baa5507fe.png)

**Comment by MichaelArestad** [comment]
Some ideas I've been kicking around:
* Move the block navigator away from this toolbar
* Move the info icon (shows stats and outline) elsewhere (sidebar most likely)
* Migrate much of the contents of the three dot menu elsewhere (have mocks for this) and reduce need for it.

**Comment by simison** [comment]
Once FSE is available, we can probably either remove the "preview" button or move it to the document sidebar as it's less relevant.
