### ISSUE TITLE
Settings: add timezone setting in calypso

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3902]
Probably makes sense to put this in the general settings area.

**Comment by retrofox** [comment]
@rralian http://calypso.localhost:3000/me/account ?

**Comment by rralian** [comment]
No, I think /settings/general, as it's a site-specific setting.

**Comment by retrofox** [comment]
Right, like wp-admin does
![image](https://cloud.githubusercontent.com/assets/77539/13647038/0bcf65fe-e611-11e5-8960-15c9884075cb.png)

**Comment by apeatling** [comment]
Yes that's the one.

**Comment by apeatling** [comment]
@retrofox There is a typo here with the period and semicolon:

<img width="259" alt="screen shot 2016-03-29 at 10 52 46 am" src="https://cloud.githubusercontent.com/assets/1464705/14118048/74a7f312-f59c-11e5-8358-20fc8b109e28.png">

**Comment by lancewillett** [comment]
Usability notes: https://test.wordpress.com/2016/04/13/settings-timezone-picker-usability/

1) It's hard to scroll the huge long list.
2) You can't type in the form like a native browser `select` dropdown menu.

**Comment by lancewillett** [comment]
See #5231 for usability bug example.
