### ISSUE TITLE
ToS Update: Create WordPress.com ToS Banner

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#39046]
Create a new banner for WordPress.com that notifies customers of changes within Terms of Service. Please reach out to design and @jennyzhu when taking this for guidance.

Requirements:
- Visible in a frequently trafficked section
- Has a call to action that displays a small dialog that has links to WordPress.com/tos, and possibly a link to a blog post that highlights the most recent changes.
- On clicking accept, we fire an API event to mark that a user has accepted terms of service. (Pick a user attribute name. We should collaborate with Mobile on the name).
- Not sure if VIP should see this?
- Not sure yet if folks can dismiss the dialog without accepting.

**Comment by danhauk** [comment]
I think we can leverage previous work and the existing banner component.

![image](https://user-images.githubusercontent.com/448298/73310344-1e08b680-41f2-11ea-91b0-17fe0d810f8f.png)

* The user logs in and sees a banner on My Home (or Stats if My Home is not available to them yet).
* Explicit action is required to dismiss the banner. From a legal perspective this is better, but it’s less disruptive than a full screen modal.
* (Dependent on technical lift) The link in the banner opens the updated ToS in a modal, similar to how we display support articles from the inline help menu.

**Comment by mmtr** [comment]
> 1\. The user logs in and sees a banner on My Home (or Stats if My Home is not available to them yet).

Since users can access other pages directly by typing the URL in the browser, wouldn't be safer to display it on any page? I believe that's what we did for the GDPR banner.

> 2\. (Dependent on technical lift) The link in the banner opens the updated ToS in a modal, similar to how we display support articles from the inline help menu.

It’s not a requirement that we serve the actual content in the dialog, so we decided to keep things simple and link to the ToS page from the banner, which avoids adding an endpoint for serving ToS content.

See pbAPfg-29#comment-81

**Comment by danhauk** [comment]
@mmtr Thanks for taking a look at these.

> Since users can access other pages directly by typing the URL in the browser, wouldn't be safer to display it on any page?

That sounds like a better plan!

> It’s not a requirement that we serve the actual content in the dialog

Awesome. I was just going by the requirements listed in the issue description above. I read a few other threads, but missed that decision in the one you linked above. Thanks for pointing that out!

**Comment by mmtr** [comment]
> > Since users can access other pages directly by typing the URL in the browser, wouldn't be safer to display it on any page?
> 
> That sounds like a better plan!

That leads to new design challenges 😅 The banner you proposed doesn't fit in screens not using the standard Calypso layout (like wordpress.com/block-editor/post or https://wordpress.com/customize/). We could hide the banner in such screens or maybe we can display it sticked to the bottom as we did with the GPDR banner (https://github.com/Automattic/wp-calypso/pull/25392).

<img src="https://user-images.githubusercontent.com/23619/41160469-23002122-6b30-11e8-80b5-d74c2cb6fe01.gif">

**Comment by mmtr** [comment]
> maybe we can display it sticked to the bottom as we did with the GPDR banner

The "open in app" banner takes also the same approach:

<img width="349" alt="Screenshot 2020-01-29 at 15 59 13" src="https://user-images.githubusercontent.com/1233880/73367905-730b0200-42b0-11ea-8fe5-9c2f9d28de7f.png">

**Comment by danhauk** [comment]
The GDPR banner seems like a good way to go for a consistent experience across all screens. We should repress all other non-essential sticky banners like the "open in app" if the TOS update banner needs to be displayed.
