### ISSUE TITLE
Pages: Create a pseudo blog page and add the home icon to it by default

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3905]
This probably needs to be fleshed out more... maybe a mock and some notes about how this impacts the pages area? Are you able to "edit" the pseudo page? What if you want your blog page elsewhere?

/cc @retrofox @mtias @adambbecker @drw158

**Comment by drw158** [comment]
Is there some more explanation on this? Does this mean that this blog page would be already selected (for the Posts Page) when a user changes the Front Page option in the Customizer.

Just a note, I didn't expect to find this Setting in the Customizer. I thought it might have moved to the Pages view.

**Comment by rralian** [comment]
> Is there some more explanation on this?

@drw158 There is some prior art about the general issue we're trying to solve (a post @adambbecker had written on calypso concepts), but I'm not sure those ideas line up with the stated suggestion. I think this task might have come from @mtias or @adambbecker, so maybe one of them can provide more details.

**Comment by mtias** [comment]
@drw158 currently if you have a static page set you see this:

![image](https://cloud.githubusercontent.com/assets/548849/13677335/c7f96698-e6e9-11e5-97fc-b89fa134b178.png)

But if your front page is your blog posts, we don't show that anywhere in the UI. The idea is to always have this:

![image](https://cloud.githubusercontent.com/assets/548849/13677356/f1341a80-e6e9-11e5-8cad-d07029dd5d7f.png)

Which would be a fake-page we create if your front page is not a static page. The next step then is to make it easy to change which page gets the "home" icon from there.

By always having an "item" that is your home we'll make it easier to understand how things work, and how you can change it.
