### ISSUE TITLE
Social Links Block: Add More Icons

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39053]
Add more icons to the collection of the available ones. Here is the list of requested ones so far:

- [x] Patreon
- [ ] Microsoft Store
- [ ] Apple Music
- [x] Whatsapp

![](https://d.pr/i/pcQ8qL+)
_Link: https://d.pr/i/pcQ8qL_

Requested in 2647169-zen.

#user-report

**Comment by zdenys** [comment]
17558748-hc A request to add WhatsApp icon which is not supported at the moment:

![](https://d.pr/i/UjCmT4+)
_Link: https://d.pr/i/UjCmT4_

**Comment by kcswong** [comment]
User was trying to add the Apple icon for their podcast, but it's not available; concerning, since it's listed as supported on [the document for the Social Links block](https://wordpress.com/support/wordpress-editor/blocks/social-links-block/#list-of-supported-icons)

23189484-hc

**Comment by simranjeetkaur10** [comment]
Request to add Apple and iTunes icons came in 25161291-hc

**Comment by synora** [comment]
The block supports Patreon now, but Apple icon has been removed from the list of supported icons. 

We can keep this open as a feature request/enhancement to add the Apple icon again as well as the iTunes icon.

**Comment by paulopmt1** [comment]
Request to add WhatsApp icon came in 34442050-hc

**Comment by metabreakr** [comment]
User is asking for the following social icons in 36680078-hc:

* WhatsApp
* Discord

**Comment by csonnek** [comment]
Request for Discord in https://wordpress.com/forums/topic/replacing-the-chain-image-for-a-social-icon-with-another-icon-discord/?view=all

**Comment by paulopmt1** [comment]
[WhatsApp was added here](https://github.com/WordPress/gutenberg/pull/42137)

**Comment by zdenys** [comment]
I'm closing this one in favor of the newer feature request here where I aggregated all the missing icons:

- https://github.com/Automattic/wp-calypso/issues/71562
