### ISSUE TITLE
Free Photo Library: Highlight feature

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#39067]
The Free Photo Library allows customers to quickly add free images to their pages and posts. It's a powerful tool to help folks with content creation, and we regularly recommend this feature during Quick Start sessions ~(17% this month).

Natural discoverability of this feature is currently buried in the media modal. It requires opening the media modal by inserting an image block > clicking on an unlabed image icon > then clicking on Free photo library

<img width="1042" alt="Screen Shot 2020-01-24 at 11 31 49 AM" src="https://user-images.githubusercontent.com/1270189/73097938-33ea4480-3e9d-11ea-9121-cbd912e143e7.png">

How might we help customers find this feature? @dezzie @danhauk maybe this might make sense as a Customer Home card?

![Screen Shot 2020-02-12 at 5 36 38 PM](https://user-images.githubusercontent.com/1270189/74393873-2222ff80-4dc0-11ea-8389-69ef0008372a.png)

**Comment by dezzie** [comment]
Yes! It's one of the concepts that previous iterations of the work looked into exploring, but under the assumption that we did not have an offering yet. If do already have it, I say let's leverage it.

**Comment by zdenys** [comment]
Can we also fix this https://github.com/Automattic/wp-calypso/issues/31230 bug as it gets in the way every time we use Free Photo Library from within the Post/Page (instead of from _WordPress.com > My Sites > Site > Media_)?

**Comment by arunsathiya** [comment]
18386381-zen. Request to improve visibility of this feature as well. Right now is accessible only on Calypso. Not on wp-admin.

**Comment by gwwar** [comment]
@dezzie are you comfortable with us trying to implement this?

![Screen Shot 2020-02-12 at 5 36 38 PM](https://user-images.githubusercontent.com/1270189/74393923-3ff06480-4dc0-11ea-98ea-c6a85fb2343f.png)

Would we try showing a video here, or linking directly into the media modal to the free library search?

**Comment by gwwar** [comment]
After chatting with @lcollette to start with I think a video here would make sense. We can always follow up in future iterations with a tour or better media modal UX in general.

**Comment by Aurorum** [comment]
I opened a PR in #39506 for this issue. :)
