### ISSUE TITLE
Help: Make help search results more relevant

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3907]
![help results](https://cloudup.com/cmF-zSQTx7h+)

The search results in https://wordpress.com/help show some pretty irrelevant... see in the example, none of the top results are helpful at all. :disappointed: This is frustrating for users and means we're sending more people through our support queue than necessary.

Make it moar better! Being worked on by both @roundhill and @dmsnell

**Comment by roundhill** [comment]
We improved search results by including the Page tags in the search. We also audited the top 30 searches and added tags to the pages that we wanted to bubble up higher in the search results.

Improvements were all made in the api, so no code changes needed here. Closing!
