### ISSUE TITLE
Edge: Can't highlight comments under Site->Comments section

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#39076]
#### Steps to reproduce
1. Go to WordPress.com
2. Select one site and go to Site->Comments
3. Try to highlight a piece of text from a comment or the title

#### What I expected
For the text to be highlighted as it is in the other browsers.

#### What happened instead
Despite the text being selected actually, I'm seeing the title's color barely changed when selected and the content of the comment is not changed/highlighted at all.

#### Browser / OS version
Edge 18.18362

#### Context / Source

 #user-report

**Comment by automattic-ian** [comment]
This issue appears to affect any text in all of WordPress.com text is not selectable even when on the WordPress.com sign in page. To clarify, the text doesn't show as selected but keyboard shortcuts still work.

**Comment by tijosh** [comment]
#2753501-zen

**Comment by kriskarkoski** [comment]
I can reproduce this issue in Edge 18, but not in Edge 80 (the current version)

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

As Microsoft Edge is no longer active development, I would propose that this issue be closed with the label `Closed - Won't Fix`.
If this issue should remain open, please feel free to re-open this bug.
