### ISSUE TITLE
TFT: Make it clear that the previous Homepage becomes a Draft

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39073]
When a template-first theme (TFT) is activated on a site, the previous Homepage becomes a Draft. We should warn the users about this as it's confusing.

Consider a user that picks a theme, creates their own personalized Homepage, then decides to switch to a different TFT. The result is that their new Homepage is replaced with the demo content from TFT and their previous page is "gone". How are they supposed to find it and figure out that it's in Drafts?

I noticed this situation several times during Quick Start sessions.

I even have a predef for this situation now:

>Whenever you switch to one of [these Themes](https://wordpress.com/themes/filter/block-editor-styles/) (which are created only with the use of [Blocks](https://en.support.wordpress.com/wordpress-editor/blocks/) and our [Block Editor](https://en.support.wordpress.com/wordpress-editor/)) it may be the case that your current homepage gets unpublished and saved as a Draft (in __WordPress.com > My Sites > Site > Pages > Drafts__). This happens so that the new theme homepage can be applied instead of yours.

>Even if it happens, you can go to Drafts, open your previous homepage and Publish it. Then you can go to __WordPress.com > My Sites > Design > Customize > Homepage Settings > A static page > Homepage__ and set it to be your homepage.

#### Context / Source
#painpoint #user-report

**Comment by olaolusoga** [comment]
Tested running TwentyNineteen theme, and then switching the Twenty Twenty and Dalston, not noticing the previous homepage becoming a draft. Could you record a video of the issue?

If it is an issue, then recommend we introduce a warning before activating TFT. The modal explicitly states what will occur, and asks if person would like to continue. 

Confirmation modal:
![Desktop - 1](https://user-images.githubusercontent.com/1382943/73408469-511e7900-42ca-11ea-983a-bd49a2e93007.jpg)

**Comment by zdenys** [comment]
>Tested running TwentyNineteen theme, and then switching the Twenty Twenty and Dalston, not noticing the previous homepage becoming a draft. Could you record a video of the issue?

Start with a custom Homepage (that has a `Blank` layout) on Maywood. Switch to a different TFT, let's say Barnsbury. The new theme creates a new Homepage called `Home` with its own layout and the previous Homepage becomes a Draft (in my case it's called `Custom Home Page`).

![Screen Capture on 2020-01-30 at 16-38-37](https://user-images.githubusercontent.com/39308239/73464680-93ee5880-437f-11ea-8c47-bedac995971c.gif)

Now, starting from this new situation where I have a Barnsbury's Homepage, if I switch to another theme such as Dalston, Barnsbury Homepage becomes a Draft (with an annotation which is good) and Dalston creates a new Homepage called `Home`.

![Screen Capture on 2020-01-30 at 16-45-21](https://user-images.githubusercontent.com/39308239/73465128-360e4080-4380-11ea-814e-c15cada8c8fe.gif)

So in both cases, the previous Homepage becomes a Draft and it could be confusing for the users (since they don't know that it is the expected behavior).

**Comment by obenland** [comment]
@retrofox Is there already a public PR that could be linked to here?

**Comment by retrofox** [comment]
> @retrofox Is there already a public PR that could be linked to here?

No yet, Konstantin. :-D
