### ISSUE TITLE
Sidebar Notices: Don't display upsells when more important site notices are active

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#39089]
### What happened

Sometimes an upsell will appear alongside another notice in the sidebar, like this:

<img width="364" alt="screen_shot_2020-01-27_at_10 31 12_am" src="https://user-images.githubusercontent.com/2124984/73211255-e4647c80-4119-11ea-993d-ef4d5bbd8335.png">

### What I expected

Rather than overwhelming folks with information, we should show only one notice or upsell at a time.

Currently, the notices are split into three separate files and are unaware of each other:
https://github.com/Automattic/wp-calypso/blob/362980e27e983dc2bad4dd4484332f27fbdc1929/client/my-sites/current-site/index.jsx#L86-L92

### Possible solutions

We could convert these notices to JITMs, so only one notice is shown at a time, with site alerts taking priority over things like upsells.

We might also combine these notices into one file, so we can more easily check for the presence of one type before displaying anything.

We could find a new home for non-upsell notices (like Customer Home) to avoid crowding the sidebar area.

A similar issue occurs with the Site Redirect nudge in #38672

**Comment by gwwar** [comment]
Please reopen if urgent site notices are not moved to Customer Home
