### ISSUE TITLE
Help: design iterations

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3909]
Make https://wordpress.com/help more helpful. FAQ? Latest questions?

/cc @drw158 @apeatling

**Comment by apeatling** [comment]
I think having an accordion of the top 10 most asked questions in support, where you can expand to see the answer would be ideal here.

**Comment by drw158** [comment]
Things that I think are quick wins:

- Update icons to use Gridicons.
- Remove page header and use that text as a search placeholder instead.
- Use standard components for the 3 big external links.
- Add a "Most Helpful" section with a few of the most visited docs.

Here is a mockup that updates all of those, except for the first one. (Andy, I can do a mockup of your accordion idea tomorrow).

![artboard](https://cloud.githubusercontent.com/assets/618551/13653694/d77484bc-e618-11e5-84c6-7bf7e5f5f0dc.png)

The 4 docs were picked from the most visited articles this year so far. "All About Domains" actually isn't that popular, but it has more info than the more popular Domain Mapping article. This is why I think that this list should be curated and hardcoded.

cc @eduardozulian

**Comment by folletto** [comment]
> Update icons to use Gridicons.
> Remove page header and use that text as a search placeholder instead.
> Use standard components for the 3 big external links.
> Add a "Most Helpful" section with a few of the most visited docs.

These all look solid to me. :) 💯


>  This is why I think that this list should be curated and hardcoded.

I agree on the editorial approach here, data informed, but editorial.
Maybe we can just tag these pages in a way, so we can query the endpoint and get dynamically whatever matches the tag? :)

**Comment by roundhill** [comment]
I think these are great improvements, especially with the currently weak search results.

**Comment by rickybanister** [comment]
Maybe we call it 'All Support Articles' to create parity with the language above, but overall I like the change. 

Maybe the three clickable card options below get icons/graphics floated to the left. All the thin type makes me glaze over and miss the important 'Contact Us' option.
