### ISSUE TITLE
[Gutenboarding]: Chain account/site creation/redirect requests

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#39096]
Requires:

Frontend account creation request/response handling #38794
Frontend site creation request/response handling #38707

This task involves:

- working out architecture/where to put the thing (`landing/gutenboarding`?)
- creating an account via the signup form
- immediately after a successful account creation, create a site
- after site creation, build redirect url using the new site's homepage's id.

**Comment by ramonjd** [comment]
> after site creation, build redirect url using the new site's homepage's id.

We'll probably have to build the redirect url to FSE, e.g.,

/block-editor/page/newsite291051204.wordpress.com/9

Grabbing the post ID of the relevant post _may_ require another HTTP request to `/v1.2/me/sites`, after which we'd pluck `page_on_front` from the current site's options.

Related comment:
https://github.com/Automattic/wp-calypso/issues/38798#issuecomment-574566399

**Comment by ramonjd** [comment]
Not sure about this, but we might need to wrap the sites request in a condition if frankenflow is using the current domain step. E.g., https://wordpress.com/start/domains-with-preview

See comment: https://github.com/Automattic/wp-calypso/issues/38707#issuecomment-579575352

**Comment by razvanpapadopol** [comment]
There is a possibility of removing the domain step (https://github.com/Automattic/wp-calypso/pull/39244) but we'll know more next week.
