### ISSUE TITLE
Plugins: concept mockups for plugins area

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3911]
Since so many users ask us about plugins or even leave wpcom because they think they need a plugin, create a "plugins" section that can better explain the plugin functionality we automatically provide... help people understand what we offer and that we manage this for them as a feature.

**Comment by drw158** [comment]
Discussion can be found here: #830 

Mockup: 
![plugins 2](https://cloud.githubusercontent.com/assets/618551/13652100/fed35050-e60f-11e5-9ac2-576f6041ba8d.png)

**Comment by apeatling** [comment]
Let's close this in favor of #3840
