### ISSUE TITLE
Customer Home: Display Three Cards Max

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#39119]
As suggested by @lcollette and @davemart-in, it can look visually distracting when 4 cards are stacked. Let's try to limit this to three. For now it might be possible to hide the "Grow and Earn" card while the Site Setup List remains uncompleted.

![horizon wordpress com_home_feralcats food blog](https://user-images.githubusercontent.com/1270189/73316809-05e06980-41e9-11ea-9855-7ff5ad3e7920.png)

**Comment by mmtr** [comment]
There is a new issue to track the feedback from #39133, so we can close this.
