### ISSUE TITLE
Reader: Ability to remove tags from sidebar

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#39125]
#### Steps to reproduce

- Start at https://wordpress.com/read
- Add a tag on the left sidebar
- Try to remove that new tag. 

#### What I expected

I expected that there is a `X` mark as shown on [these images](https://en.support.wordpress.com/reader/#tags). 

<img width="268" alt="reader-sidebar-2" src="https://user-images.githubusercontent.com/18581859/73333294-65915000-428f-11ea-88c2-189e3971f4e4.png">
<img width="268" alt="reader-sidebar-3" src="https://user-images.githubusercontent.com/18581859/73333295-6629e680-428f-11ea-99df-bb1494dfa25e.png">

We also say `Remove a tag from your list at any time by clicking the “X” to the right of the tag.` on that support document.

#### What happened instead

There is no `X` mark. 

I had to click on `Following tag` button at the top right of a tag page to remove it.

![Screen%20Shot%202020-01-29%20at%2012 04 00](https://user-images.githubusercontent.com/18581859/73333336-7e016a80-428f-11ea-9441-cd6c3ec5e7c6.png)

#### Browser / OS version

Firefox 71.0 (64-bit) on macOS 10.15.2 - MacOS Catalina.

#### Screenshot / Video

Added above.

#### Context / Source

#18261070-hc - noted here.

**Comment by arunsathiya** [comment]
When I visit https://wordpress.com/read/edit, it reads me to https://wordpress.com/following/edit/ where it's available. It's a legacy Calypso dashboard. It's not clear if this is internal or for all users.

<img width="1026" alt="Screenshot 2020-01-29 at 12 06 35" src="https://user-images.githubusercontent.com/18581859/73333540-17c91780-4290-11ea-86df-db089cac4d4f.png">


Having said that, visiting https://wordpress.com/following/edit/ **directly** shows the current Calypso, by redirecting to https://wordpress.com/following/manage Very odd.

**Comment by blowery** [comment]
> When I visit wordpress.com/read/edit,

Out of curiosity, where did you find that URL? It shouldn't be active anymore. The interface returned is the 5+ year old Atlas interface... I'll see about getting that URL handled by Calypso.

**Comment by arunsathiya** [comment]
>It shouldn't be active anymore. The interface returned is the 5+ year old Atlas interface

I see. @hafizr found that URL an year ago, in a private Slack channel. It's not exposed on current Calypso AFAIK.

**Comment by bluefuton** [comment]
Thanks for reporting this @arunsathiya. Looks like the button was removed in https://github.com/Automattic/wp-calypso/pull/34051/files#diff-f43e68b4c0b5cf0cb2601d79e4dac9e2L70.

@shaunandrews was it intentional to take away the 'remove tag' functionality from the sidebar? 

I'm happy for us to update the support docs if so.

**Comment by shaunandrews** [comment]
I _think_ the reason it was removed was to follow the pattern of having only a single action in a sidebar menu item. On the My Site(s) sidebar, there used to be little "add" buttons. Those were removed with the intention that sidebar menu items should contain a _single_ action, and we removed the "x" icon to follow that pattern.

**Comment by bluefuton** [comment]
Ah yes, I remember - we removed the 'Manage' button for follows too. Thanks @shaunandrews!

@arunsathiya I don't this functionality will be coming back to the sidebar, and it's best to direct users to unfollow tags on the tag stream itself. Can we update the support docs accordingly?

**Comment by bluefuton** [comment]
No plans to bring this back in the sidebar at the moment. User can unfollow a tag on the tag stream itself:

<img width="909" alt="Screen Shot 2021-01-05 at 10 38 15" src="https://user-images.githubusercontent.com/17325/103582150-2f019200-4f42-11eb-8341-1e7a379daa3d.png">
