### ISSUE TITLE
Customer Home: Add Block Editor resources

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39132]
Now that Customer Home is available to all users https://github.com/Automattic/wp-calypso/pull/39071, it would be very helpful to add a prominent mention of Block Editor linking to a support page about how to use it. 

We need to make Block Editor resources available for our users.

It could be done by:
- Replacing one of the Site Tools items (for example `Manage comments`) that realistically have a lower priority than knowing how to get started with the editor that would be used for the creation of the majority of the site content
- Adding an additional item to Site Tools
- Adding it to Site Setup List
- Adding it to the sidebar (as a GIF, for example, that would catch users' attention)

![](https://d.pr/i/bbJ8dJ+)
_Link: https://d.pr/i/bbJ8dJ_

![](https://d.pr/i/gzxg3p+)
_Link: https://d.pr/i/gzxg3p_

The need for making resources about Block Editor has been confirmed by:
- Research sessions p9Jlb4-1aj-p2#comment-1725
- Quick Start sessions
- Live Chat interactions with struggling users p9ag8j-Ro-p2

We already have at least a few resources about Block Editor to which we can direct users. Now it's just the matter of making them readily available, prominently visible:
- https://en.support.wordpress.com/getting-started-with-wordpress-com/#the-block-editor
- https://en.support.wordpress.com/wordpress-editor/

#### Context / Source
#painpoint #user-report

**Comment by zdenys** [comment]
User case where having the above would have been helpful: 2670906-zen

**Comment by gwwar** [comment]
@dezzie @lcollette @danhauk I think this one might be categorized under feature/educational, similar to https://github.com/Automattic/wp-calypso/issues/39067

If possible I'd be interested in seeing if we can think through options of giving folks helpful tips here without fully pulling folks out of WordPress.com to en.support docs. For example this could trigger a guided tour or quick inline video.

**Comment by dezzie** [comment]
New users get onboarded to the block editor when they edit their first page:

![Screen Shot 2020-01-29 at 14 07 04-fullpage](https://user-images.githubusercontent.com/1301932/73393156-d42ad980-42a0-11ea-9082-58c7b17fe8c9.png)

@zdenys Do users mention this in their support interactions? It'd be great to learn more about some of the gaps between that and something Customer Home could take on, to avoid redundant features.

**Comment by zdenys** [comment]
The modal doesn't appear to be very efficient:
- Users in most cases dismiss it to get straight to the editing (and then don't know how to get back to it, if it's even possible)
- The link to the Block Editor's detailed guide is on the fourth page of the modal and it's to the external .org page, not even our .com support (which is not the best experience I'd say).

**Comment by danhauk** [comment]
I took a quick pass at a few options.

1. Add a large feature/educational content card. The button would a guided tour using the Gutenberg tooltips or video in a modal.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/448298/73477581-88d8ff80-4362-11ea-98f7-6eb520ec3118.png">

2. Add a card on the side with a few specific features or need-to-knows of the editor. We would look to your expertise @zdenys (and others) to define what specific links are important (for example, what do you see customers struggling with the most)

<img width="879" alt="image" src="https://user-images.githubusercontent.com/448298/73477919-1b799e80-4363-11ea-8122-680e79d5676f.png">

**Comment by dezzie** [comment]
I think adding this as a content module is a good idea, because we can re-surface it in different contexts. 

Adding it as an additional link to the Quick Links module reduces discoverability, which is what we need this thing to do to help lighten HE's load. Likewise, that section was meant to link users to actions and things they can do in the product. Adding a link to resources doesn't fit that model.

**Comment by zdenys** [comment]
I do like option 2 more because it has those additional links, but it's hard for me to say without any data if it would be more efficient than option 1. 

Either way, there are indeed several things users struggle with in the Block Editor and I asked other HEs to share their thoughts in p1580461727180900-slack-business-concierge

One thing I personally teach users is using `Block navigation` button to select specific Blocks precisely (which is not easy when for example there are many nested Blocks). This came up in p8hWIX-3j5-p2#comment-2167 and here's the screencast of the process I use https://d.pr/v/J6NPrY

**Comment by scosgro** [comment]
> New users get onboarded to the block editor when they edit their first page:
> 
> ![Screen Shot 2020-01-29 at 14 07 04-fullpage](https://user-images.githubusercontent.com/1301932/73393156-d42ad980-42a0-11ea-9082-58c7b17fe8c9.png)
> 
> @zdenys Do users mention this in their support interactions? It'd be great to learn more about some of the gaps between that and something Customer Home could take on, to avoid redundant features.

@dezzie 
For this, I just had a user who was having this appear every time they logged in to add/edit content (so they've dismissed it numerous times now), and was wondering how to turn it off.

**Comment by dezzie** [comment]
Tagging @olaolusoga on this one since he's the TL for that.

**Comment by yashitamittal11** [comment]
The user has requested to turn off the block editor in this ticket also - #2699828-zen

**Comment by yamphoenix** [comment]
The user has requested to turn off the block editor popup in this ticket also - #2699828-zen

**Comment by gwwar** [comment]
Let's look into short videos (< 30 sec) that we can display inline in Customer Home, that show how to do very basic things to start. Some candidate tasks:
- Adding a block
- Removing a block
- Adding a link
- Images / Media Modal

**Comment by samiff** [comment]
Similar to what scosgro posted, noting that a user reported in Firefox v72 on Windows 10 that having `Do Not Track` enabled causes the "Welcome to the block editor" popup to return each time they edit a post. I'm wasn't able to reproduce from Firefox v72 on macOS; but we did try running through various troubleshooting such as disabling extensions and trying from a private FF window. 

Context: 18776303-ch

**Comment by Aurorum** [comment]
I started a PR for this in #39617, still a WIP though :)

**Comment by kwight** [comment]
@scosgro @yamphoenix @samiff and others, please use https://github.com/Automattic/wp-calypso/issues/39641 for reporting and followup of the "cannot dismiss welcome guide" issue, since it's a separate from what we're dealing with here. 👍

**Comment by pauljacobson** [comment]
How about a section that reminds users about upcoming Quick Start Support sessions that they've booked?

**Comment by Aurorum** [comment]
@pauljacobson There is a separate issue for that in #38998. :)
