### ISSUE TITLE
Gutenboarding: add back button to page selector

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39134]
We've been talking about having "more contextual back buttons" in Gutenboarding, instead of the back button in the header. In one of the designs, there was a back button in page selector:

<img width="1661" alt="Screenshot 2020-01-29 at 16 07 10" src="https://user-images.githubusercontent.com/87168/73363579-b44fe180-42b1-11ea-99f6-89f520154642.png">

@Automattic/gutenboarding-design is that still the direction we're headed? This would be a good task for @yansern to practice Gutenboarding. Is it worth doing even with the risk of this view being redesigned and we wouldn't show the back button anymore here specifically in the future?

**Comment by olesyabrk** [comment]
I'm a bit torn about this tbh. On one hand I like the consistency and predictability of the back button in the top bar. It teaches the user about the top bar and minimizes the learning curve. On the other hand, that back button will disappear post Gutenboarding, so how much do we really need that to be a consistent element if it's so temporary? I think I'm leaning towards removing it and replacing it with the contextual buttons instead throughout.

**Comment by simison** [comment]
@olesyabrk samesies; on the other hand I like the idea of making space for potential menu-icon in the header.

Another placement which we might be able to do consistently is in the canvas area but below the header:

<img width="1440" alt="Screenshot 2020-01-30 at 09 36 11" src="https://user-images.githubusercontent.com/87168/73429336-1ce79e80-4344-11ea-9c32-c6cdad82e9e1.png">

That way we can keep it closer to content on bigger screens wihout customer "losing" it:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/87168/73429464-6df79280-4344-11ea-905c-1a93114b4e33.png">

**Comment by olesyabrk** [comment]
Should we just remove it altogether and have users use the browser back button for when we don't provide a contextual way to go back?

**Comment by yansern** [comment]
> I think I'm leaning towards removing it and replacing it with the contextual buttons instead throughout.
@olesyabrk +1. I vote for having *contextual* back button.

> Should we just remove it altogether and have users use the browser back button for when we don't provide a contextual way to go back?

I would say, keep the contextual back button. The browser back button functionality now works through this PR https://github.com/Automattic/wp-calypso/pull/39210.

@simison On those yellow boxes you highlighted, maybe instead of display a normal back button, I'll just make them contextual by just having custom labels like "Back to Design Selection" or "Select Another Design" or "Change Design", I don't know... then we can see how the effect looks like. 👍

**Comment by simison** [comment]
>Should we just remove it altogether and have users use the browser back button for when we don't provide a contextual way to go back?

> On those yellow boxes you highlighted, maybe instead of displaying a normal back button, I'll just make them contextual by just having custom labels like "Back to Design Selection" or "Select Another Design" or "Change Design", I don't know... then we can see how the effect looks like. 👍

We can look at the whole flow closely separately — adding an additional back button just to the page selector would be fine too as a first step.

**Comment by razvanpapadopol** [comment]
navigation buttons are now implemented for the whole flow
