### ISSUE TITLE
Gutenboarding: fix confusing keyboard focus / mouse hover states

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39138]
When landing at page selector, the first item has "focus" by default and it thus gets focus styles (dark border):

<img width="1441" alt="Screenshot 2020-01-29 at 16 17 10" src="https://user-images.githubusercontent.com/87168/73364382-2d9c0400-42b3-11ea-9fab-a722075c5914.png">

When I now hover with mouse anything else on this page, they also get hover state:

<img width="1442" alt="Screenshot 2020-01-29 at 16 17 16" src="https://user-images.githubusercontent.com/87168/73364410-3987c600-42b3-11ea-8f29-156f0aa41659.png">

Once I select something, things look good again:

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/87168/73364447-499fa580-42b3-11ea-96a1-b9ab2001c9e3.png">

I would expect to see the initial focus state be visible only when I'm keyboard navigating. I think we use [`accessible-focus`](https://github.com/Automattic/wp-calypso/tree/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/lib/accessible-focus) elsewhere to show keyboard focus only when tabbing with keyboard, but there could be some more simple solution as well.

**Comment by Addison-Stavlo** [comment]
My apologies if I am stepping on any toes here.  

I was looking into #38665 and noticed this lingering-focus problem while I was working on that.  I went ahead with trying to fix it before I saw this issue had some folks assigned already.  Im going to go ahead and open this small PR for it, but feel free to take it over or make any changes you see fit.

Again, sorry for jumping onto the already assigned issue.
