### ISSUE TITLE
Customer Home: Remove Go Mobile card after app is downloaded

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39146]
The "Go Mobile" card on Customer Home should be removed on Customer Home after the user has downloaded the app and the user has logged in to the apps at least once. After folks have been using the apps, the customer knows about it and knows to search for it if they need to download again for any reason.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/448298/73377853-bacc6200-428d-11ea-96c2-643bfed06950.png">

**Comment by gwwar** [comment]
@elibud any feedback on the proposed change?

**Comment by elibud** [comment]
This is fine with me as long as we check that the user has logged in into the app via tracks, thanks for the ping.

**Comment by gwwar** [comment]
Thanks for taking a look @elibud

**Comment by gwwar** [comment]
I think this will be handled by the Customer Home API, so I'm going to close this one out.
