### ISSUE TITLE
Customer Home: Make cards dismissable

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39147]
As a user if I make a decision to use mobile web instead of the native app I don’t want to see a marketing message that I can’t remove every time I log in. This is especially important on mobile, where the card moves to the top of the viewport.

**Comment by gwwar** [comment]
What dismiss times are we proposing? Forever? Hide for X months?

**Comment by danhauk** [comment]
Not sure of a proposal time yet, this was mostly just to capture the idea before it slipped through the cracks.

**Comment by gwwar** [comment]
I wonder if this would be more interesting if we could make this apply to the other cards once we have more to offer.

For example, quick options to click to dismiss or note that a card was useful. This would be a great way of seeing what folks are interested in.

**Comment by danhauk** [comment]
Absolutely. I like the idea of asking if a card was useful, maybe after it's dismissed. We've been working with this pattern so far

<img width="350" alt="image" src="https://user-images.githubusercontent.com/448298/73392848-98940d80-42a8-11ea-9970-4b2e289c824f.png">

Another idea is to have a "Remind me later" or "Not now" that also dismisses it for a week (as an example), then pops up again and the "Not now" link changes to "Don't show again" that dismisses is forever.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/448298/73393054-04767600-42a9-11ea-8dd2-eeff975ca834.png">

<img width="699" alt="image" src="https://user-images.githubusercontent.com/448298/73393427-9ed6b980-42a9-11ea-9b6b-22d43fc0fa96.png">

**Comment by gwwar** [comment]
Let's close this out, I think this has been covered by the featured task
