### ISSUE TITLE
Calypso build: optionally bundle `@wordpress/icons`

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39158]
Via https://github.com/WordPress/gutenberg/pull/19809:

> The design team plan to add hundreds/thousands of icons to this (`@wordpress/icons`) package for third-party users. That makes it impossible to load it as its own script (bundle size). Instead we should encourage its usage via npm and tree-shaking.

FYI @Automattic/team-calypso  @sgomes

**Comment by sgomes** [comment]
Gutenberg seems to have chosen the SVG-in-JS route for now. In Calypso, we're currently doing icons with SVG spritemaps, which have a number of advantages in terms of runtime and loading performance.

My advice would be to opt out of `@wordpress/icons` for as long as possible in Calypso, and hopefully by that time the package will have taken a different approach, which @gziolo mentioned as a possibility [at the end of the linked Gutenberg PR](https://github.com/WordPress/gutenberg/pull/19809#issuecomment-577605497).

**Comment by simison** [comment]
Thanks for analyzing! FYI @kraftbj @jeherve since the same might apply to Jetpack.

**Comment by jeherve** [comment]
I'll be keeping an eye on this as well, this definitely seems like something we could use in many different areas of Jetpack.
