### ISSUE TITLE
Gutenboarding: create an FSE site

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39168]
When pressing "create site" button after page selector, folks end up with a site:

<img width="400" alt="Screenshot 2020-01-30 at 15 46 49" src="https://user-images.githubusercontent.com/87168/73455016-edeb2000-4377-11ea-9e67-6933ab3f7885.png">
<img width="400" alt="Screenshot 2020-01-30 at 15 47 44" src="https://user-images.githubusercontent.com/87168/73455021-f04d7a00-4377-11ea-99b1-a20c327887ce.png">

Let's make that site be an FSE site. That will help us do more realistic user testing for the flow.

@ramonjd comments:

>At present, FSE is enabled if `'test-fse' === $site_creation_flow;`.
>
> So for now, you could set `site_creation_flow` to equal `'test-fse'` in the request object for testing, but we'll need to elaborate on that condition in the new sites class to either accept something like `'gutenboarding'` as the `$site_creation_flow` or maybe a more generic `full-site-editing: 1`.

Slack convo p1580327754282800-slack-cylon and Github comment: https://github.com/Automattic/wp-calypso/pull/39128#discussion_r372393273

We'll likely need to do something like this anyway since we will turn Gutenberg FSE experiment on for the flow before it's fully available for all sites.

**Comment by Addison-Stavlo** [comment]
After looking into this a bit, we may want to rethink creating these as FSE sites.  The main question to consider is "are we willing to limit our design picker to only 7 designs for the purpose of using dotcom FSE as a placeholder until a better editor is available?"

Only 7 of the 18 Themes available in our design step are 'compatible' with dotcom FSE.  If we enable FSE site creation, then sites created with a design/theme selection from the first group will load in the FSE editor while sites created with selections from the second group will load the standard editor.  It is probably best to keep things consistent and have them all load into the same editor.

Getting the other 11 Themes loading in FSE would require a lot of work converting each to be compatible as outlined on `paYE8P-dy-P2`.  Alternatively, getting rid of 11/18 of the design options in Gutenboarding seems restricting when using the standard block editor as our placeholder would give us consistency across all available designs.

If we really want FSE in Gutenboarding, then the only realistic option is limiting the design selection to FSE compatible themes.   Alternatively, the wpcom block editor will work well and consistently for all theme/design selections in Gutenboarding and seems to be the best option as our placeholder.

**Comment by simison** [comment]
Ahh, I didn't realize it's so few. Thanks for the investigation and clear summary!

Eventually, I expect our home page layouts to be separate from "themes", and we'll just have a good big bunch of designs available. Those new ones might again not be compatible with wpcom-FSE.

I think it's important we experiment with more designs (i.e. more "realistic" design picker) rather than with FSE (i.e. more "realistic" editor experience). Let's drop this requirement and hop into next challenges instead.

Thanks again!

FYI @johnHackworth @vindl
