### ISSUE TITLE
TFT: Primary menu is created but not assigned to its location

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39165]
On Maywood (and possibly all template-first themes) a Primary menu is created (e.g. with Home and Blog Feed items) but the location is not assigned, so the menu doesn't appear on the site and users are unaware they'd need to go to Customizer to assign the location.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Create a new site that will have one of the template-first themes (TFT) active, such as Maywood

#### What I expected
See the navigational menu active on the site (since it's created)

#### What happened instead
A menu called Primary is created (with items `Home` and `Blog feed`) but it's not assigned to its location

#### Screenshot / Video

![ezgif-7-87a96ba68a1c](https://user-images.githubusercontent.com/39308239/73452798-ef621b80-436a-11ea-93b9-e63d0bcf0346.gif)
_Link: https://d.pr/i/UlxXbT_

**Context / Source**
#painpoint #user-report #quick-start-sessions

**Comment by zdenys** [comment]
Most recent case: 2673338-zen (Quick Start session)

**Comment by ramonjd** [comment]
It seems as though we've _never_ added menus to segment-based site (Business, Blog etc) in the onboarding flow.

The JSON annotations (such as `m1.json` and `m2.json`), which headstart uses to create sites, do not define a primary menu


```
        "theme_mods": {
            "0": false,
            "custom_css_post_id": -1,
            "hide_front_page_title": true,
            "nav_menu_locations": []
        },
```

I tested this code, 

```
        "theme_mods": {
            "0": false,
            "custom_css_post_id": -1,
            "hide_front_page_title": true,
            "nav_menu_locations": {
              "menu-1": "primary"
            }
        },
```

and it adds the menu:

<img width="1024" alt="Screen Shot 2020-01-30 at 12 17 45 pm" src="https://user-images.githubusercontent.com/6458278/73495401-925e6980-435a-11ea-9db9-b8b409f5ff3c.png">

🎉 

Maybe @michaeldcain or @ianstewart might know whether this omission was deliberate. 

The onboarding project has sunken into the foggy mire of my memory.

**Comment by ianstewart** [comment]
iirc, I think it was a roadmap item tied to adding multiple pages like About and Contact to starter sites. It looks a bit weird in that screenshot above to have A Home and a Blog Feed menu item on what I assume is a single page site with only a blog. That said, if we could have a menu set automatically with Home … heavy plus one to that.

**Comment by zdenys** [comment]
2680626-zen Another case of a user where a Primary menu was created but not assigned to its location.

**Comment by ramonjd** [comment]
> That said, if we could have a menu set automatically with Home for single-page sites … heavy plus one to that.

I was digging around here and saw that we might be able to define primary nav elements in the `"menus"` property of each headstart JSON file, e.g.,

```
  "menus": {
    "primary": {
      "name": "Primary",
      "items": [
        {
          "menu-item-title": "Home",
          "menu-item-db-id": 4,
          "menu-item-object-id": "2",
          "menu-item-object": "page",
          "menu-item-type": "post_type",
          "menu-item-status": "publish",
          "menu-item-position": 1,
          "menu-item-parent-id": "0",
          "menu-item-description": ""
        }
      ]
```

Just not sure what the following properties relate to:

```
"menu-item-db-id": 4,
"menu-item-object-id": "2",
```

Do they have to correspong to IDs in the starter site?

**Comment by zdenys** [comment]
Today I had a case 2709738-zen with a WordPress.com site that has plugins. It had Maywood Theme for which a Primary Menu was created but not assigned to its location. 

We assigned it, added some items and then switched to Exford Theme. 

The primary menu became unassigned again which is not the desired behavior and it's confusing.  So we had to visit Customizer again and assign it to the location.

**Comment by zdenys** [comment]
Another case with Maywood Theme https://it.forums.wordpress.com/topic/visualizzazione-pagine-preparate/

**Comment by ramonjd** [comment]
As [described above](https://github.com/Automattic/wp-calypso/issues/39165#issuecomment-580491749), I've created a patch to add a Home menu item to Blogs in D39025-code

**Comment by ramonjd** [comment]
> As described above, I've created a patch to add a Home menu item to Blogs in D39025-code

I can get this in if anyone has time to review and ✅ it

**Comment by obenland** [comment]
@ramonjd With D39025-code abandoned, can this be closed?

**Comment by ramonjd** [comment]
> With D39025-code abandoned, can this be closed?

Yep, thanks for the reminder @obenland 

It didn't seem important enough to attract many 👀 anyway :)
