### ISSUE TITLE
People: user should see log in screen when accepting invite while logged out

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3916]
#### Steps to reproduce
1. Invite a user to a site here: at  /people/team/$site
2. Find the email invite in your email inbox, and click on the link while logged out of WordPress.com in your browser
3. See the sign up screen, asking the user to sign up using a different email address than the one that is associated with the user from step 1:
   ![sign-up-on-logged-out-invite-link](https://cloud.githubusercontent.com/assets/11487924/13648009/bf7faf76-e604-11e5-929c-270a9d504bc5.png)
4. If you continue with this step and sign up using a new username and email address, this new user is set to follow the site.
#### What I expected

I expected to be asked to log in using the username or email address used when sending the invite.

**Comment by ebinnion** [comment]
I'm going to remove the milestone for this issue. It is something that we made a conscious decision to do, mainly because we anticipate there being a lot of work to get login functionality working.

**Comment by v18** [comment]
Ok, sounds good!

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue.

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue as described above.  I'm going to re-label it as an Enhancement instead of a Bug since it hasn't seen any activity in months.  If anyone disagrees, feel free to change it back and give it higher priority.
