### ISSUE TITLE
Page Layouts: Switching to Blank Template Doesn't Work

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39174]
#### Steps to reproduce
1. Starting at URL: Any Page on a site with template-first theme (TFT) (such as Maywood)
2. Click `Change Layout`
3. Select `Use Blank layout`

#### What I expected
Be switched to `Blank`, just like it happens with any other Layout

#### What happened instead
Page remains with the previous Layout and only in the right-side panel under `Page Layout` it reads `Blank`.

#### Screenshot / Video

![PageLayoutsBlankBug](https://user-images.githubusercontent.com/39308239/73461322-3e637d00-437a-11ea-8f37-9a64b4ac64a3.gif)

#### Context / Source
#dogfooding #manual-testing

**Comment by apeatling** [comment]
Another report in https://github.com/Automattic/wp-calypso/issues/38913

**Comment by obenland** [comment]
The template selector assumes an empty editor and just closes without any action when the blank template is selected. 

To make it work for changing templates we'll have to amend `PageTemplateModal.setTemplate()` to empty the editor [when there are no blocks to be inserted](https://github.com/Automattic/wp-calypso/blob/72acfa571f216d32163f093e3ae15f99c40b5c88/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js#L139-L143).
