### ISSUE TITLE
Gutenboarding: don't slide out page selector when pressing "create site"

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39175]
When pressing "create site" in Gutenboarding and we start waiting for the site creation, pages slide down:

![image](https://user-images.githubusercontent.com/87168/73460924-ff392a00-4381-11ea-9522-f139e06ee713.png)

<img width="1270" alt="Screenshot 2020-01-30 at 17 00 18" src="https://user-images.githubusercontent.com/87168/73461169-5ccd7680-4382-11ea-8d18-eb7fcddea0f2.png">

Video: https://cloudup.com/cQ32B89_OLw

They should just stay where they are and the experience would be a little less jarring. :-) 

Eventually, we'll have some kind of loading step here, disable all the controls on the page or something like that but for now just not sliding the selector down would be great. Disabling the button itself could be a good bonus.

**Comment by Addison-Stavlo** [comment]
> Eventually, we'll have some kind of loading step here,

#39266 Should help with this.  The page selector sliding out isn't very noticeable when we are immediately advancing to a site creation screen.  Although you can still see it start to move as the page redirects, maybe this may still be worth looking into?

**Comment by simison** [comment]
Loading screen now hides this so we're good to close it. 👍
