### ISSUE TITLE
Gutenboarding: "create my site" doesn't work when not logged in

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39170]
When I'm not authenticated (e.g. in incognito), I cannot press "create my site" button without an error in console:

<img src="https://user-images.githubusercontent.com/87168/73455729-4a9b0a80-4379-11ea-8f98-b337bc53cba2.png" width="300">
<img src="https://user-images.githubusercontent.com/87168/73455737-4e2e9180-4379-11ea-9c29-86f4d04bbab7.png" width="600">

> Uncaught Error: AuthorizationRequiredError: An active access token must be used create a new Site for the User.

Depending on difficulty, we could either:
- Show signup form in Calypso
- Just not support this when authenticated but show e.g. `window.alert( 'Please sign up first before testing this flow' );`

**Comment by sirreal** [comment]
> Show signup form in Calypso

This has potential to be a good amount of work. The alternative is trivial to add, so I'd vote for that. Perhaps disabling the button with a `title` suggestion you sign in is another good alternative.

**Comment by simison** [comment]
Yep, sounds good for now! Team Ganon is working on the signup bits so I'd expect this gap to be closed pretty soon.
