### ISSUE TITLE
Customer Home: Add a welcome banner for older sites

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39178]
With Customer Home being enabled for all Simple and Atomic sites in #39071, older sites need something to introduce them to this new page they haven't seen before. The goal here is to let them know what this page is for and why they're seeing it so it's not so jarring, especially if it becomes the default logged in page.

We can use a full width banner across the top that shows only for sites created before August 2019 (when Customer Home was made available to all new sites). The button would dismiss the banner.

![image](https://user-images.githubusercontent.com/448298/74945093-1c7f7800-53c5-11ea-8b9a-d08790ef4f0b.png)

<img src="https://user-images.githubusercontent.com/448298/74945116-2608e000-53c5-11ea-9774-8fcc51fca3c7.png" alt="image" width="300"/>

**Comment by gwwar** [comment]
@danhauk @dezzie @lcollette is this ready to work on, or still in ideation?

**Comment by dezzie** [comment]
This is still in ideation and shouldn't alter any pre-existing alignment over scope or content areas/ layout. Design can triage this one a bit more before it goes into any sprint or phase.

**Comment by danhauk** [comment]
Still in ideation, though ideally it's ready before we switch on Customer Home in production.

**Comment by danhauk** [comment]
I did a quick iteration on this card. I tried a few different approaches to layout, color, but ended up coming back to the original style above.

**Updated the illustration**
The building/house was awkward. It wasn't very welcoming and didn't provide much value with a literal representation of "My Home". So I used the illustration to convey the value prop of Customer Home - a guide to be here for you.

**Tweaking some copy**
There's still a lot of copy here so I'd like to get @obi2020 to take a look. If anyone else has suggestions on reducing copy while keeping the general message the same, please share them.

* I updated the heading to communicate the benefit of this new section vs. a standard, non-functional welcome message.
* Changed "recommendations" to "guidance" because "recommendations" can sound sales-y.
* Added a line to let people know we'll be continuing to add more value for them.

![image](https://user-images.githubusercontent.com/448298/74799877-d2e93d00-529f-11ea-8268-c314187721d9.png)

<img src="https://user-images.githubusercontent.com/448298/74799893-db417800-529f-11ea-85df-7f1da8ea3dc2.png" alt="image" width="300"/>

**Comment by kwight** [comment]
@danhauk Lovely! Two quick things as I get going here:

* Is the illustration already committed somewhere (couldn't seem to find it)? 
* Should the button be primary, given that we have the first action in the action list as primary?

**Comment by obi2020** [comment]
Try this out?

> **Learn and grow with My Home**
> This is your new home for quick links to common tasks, easy access to support, and guidance tailored to you. We’ll keep improving what you see here to help you learn and grow with us.


I did cut it down a bit, but I think all the meaning is there. Let me know what you think.

**Comment by Aurorum** [comment]
@kwight The illustration is here: https://github.com/Automattic/wp-calypso/blob/master/static/images/extensions/woocommerce/woocommerce-setup.svg

**Comment by danhauk** [comment]
> Should the button be primary, given that we have the first action in the action list as primary?

@kwight Older customers who will be seeing this most likely won't have a checklist, but you do raise a good point about buttons in general. We already have so many buttons on the screen with the Quick Links, let's not add another. How about instead of a primary button we just make it dismissable with an `x` in the top right. 

![image](https://user-images.githubusercontent.com/448298/74945050-0b366b80-53c5-11ea-8873-5bcaab37c88f.png)
