### ISSUE TITLE
Customer Home: Remove My Site card after launch

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39182]
This is a new issue to track the feedback from #39133.

In order to be able to remove the My Site card after launching a site, we'll do a few things:

* Move `View Site` button to the top right of Customer Home. It's one of the most clicked actions so it can have a prime location.
* Use a card/banner for the "You launched your site" message instead of the large illustration on the background. This helps to ground the View Site button.
* Make changes to the buttons listed in the Site Tools (optional: change "Site Tools" to "Quick Links" as a better section label)

<img src="https://user-images.githubusercontent.com/448298/73464028-41477900-434c-11ea-95f2-c9f22ce1f98a.png">

There are different user needs that these quick links serve for static homepage vs. a homepage showing latest blog posts. Let's go with the following actions in the site tools for each case:

If static homepage:

* Edit homepage
* Add a page
* Write blog post
* Edit menus
* Customize theme
* Change theme
* Design a logo
* Add a domain

If not static homepage (showing latest blog posts)

* Write blog post
* Manage comments
* Add a page
* Edit menus
* Customize theme
* Change theme
* Design a logo
* Add a domain

**Comment by Aurorum** [comment]
PR in #39330 for this issue. :)
