### ISSUE TITLE
Customer Home: Break down "Update homepage" task into smaller tasks

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39183]
**This is a proposed change and open for discussion in terms of impact/effort and exactly how we break down the tasks.**

The task in the pre-launch checklist to "Update your homepage" is a big, ambiguous task. By breaking that down into smaller tasks with a narrow scope, they're easier to digest and comprehend. Completing a few smaller tasks builds momentum for the user.

I'm proposing two tasks to replace "Update your homepage":

---

**Personalize your homepage cover photo**
Make a good first impression. Change your cover photo by uploading your own or choose one from the free photo library integrated into your site.

[ Change photo ]
_Estimated time: 5 minutes_

Since photos have an immediate emotional connection, let's get them looking at their cover photo as soon as possible. This task would take the user to the editor and, if possible, highlight the cover image block with the Gutenberg tooltip dot.

---

**Update homepage text**
Take a moment to review and update the text we’ve written for you. Describe what makes your business unique. Make your homepage speak to your customers.

[ Edit homepage ]
_Estimated time: 5 minutes_

This would again take the user to the editor on the homepage.

![image](https://user-images.githubusercontent.com/448298/73486865-ecb7f400-4373-11ea-82dd-31caea921174.png)

cc @obi2020

**Comment by gwwar** [comment]
This might be worth pausing until we have FSE or if we decided to move away from the site setup checklist to more bite sized individual tasks to complete.

**Comment by lcollette** [comment]
Closing this for now.
