### ISSUE TITLE
Help icon sits over UI elements

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#39181]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage/{domain}/edit-contact-info/{site}
2. Scroll to the bottom of the screen in a narrow browser
3. See the help button cover UI underneath it making it hard to press.

#### What I expected
Maybe scroll down a little more to move the buttons above the help button.

#### What happened instead
The help button covered the cancel button on the screen.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/73478594-5cbe7e00-4364-11ea-8aa6-12bb64af89b1.png)

#### Context / Source

This came up in an internal conversation about standardizing button placement. We have a number of action buttons that appear at the bottom right of our cards. 

cc @lcollette

**Comment by sixhours** [comment]
We could "fix" this by adding padding at the bottom of every screen at small to medium screen sizes to allow it to scroll out of the way of the actions.

Another option is to hide the help menu until you scroll up, at which point it animates in from the bottom, kind of like the browser toolbar for Chrome on a mobile device. That might be a bit too much engineering, though, and I'm not sure it's as intuitive as keeping the inline help menu on the screen.

**Comment by fditrapani** [comment]
Your scrolling idea does sound fancy but like you said a little complex and maybe tricky for people. The padding at the bottom sounds more practical and less error prone.
