### ISSUE TITLE
Domains: Transfer domain button won't work for domain transfer between site admins

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#39207]
This user came into chat to transfer their site to another admin at their site.
When they follow the steps to transfer the domain to another site admin, they select the new owner but the button stays greyed out and they can't click on it.

#### Browser / OS version
Mozilla/5.0 (Windows NT 10.0; Win64; x64)

#### Screenshot / Video
![gFv6ch](https://user-images.githubusercontent.com/3521683/73572716-41c93800-4450-11ea-9679-bacbb898c591.png)

Followup ticket: #2677537-zen
Site: cours-de-patisserie.com

**Comment by kriskarkoski** [comment]
I've asked in our domains channel if we have seen any further reports of this.

**Comment by kriskarkoski** [comment]
Closing this for lack of additional reports. Please reopen if it's still happening.
