### ISSUE TITLE
Billing: When adding a new card, its not obvious that it will update _all_ sites

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#39227]
Head to `/me/purchases/billing` and scroll down. You'll see your existing credit cards, and a primary button to "Add Credit Card". Click that button.

Take a second and notice the small text below the form. The second note is very important: "This card will be used for future renewals of existing purchases."

<img width="744" alt="image" src="https://user-images.githubusercontent.com/191598/73687106-55b2ab00-4697-11ea-8d09-5222dea10279.png">

A customer this morning needed to add a new card, but didn't want to use it for all their sites. They missed this small text, and unintentionally created a bunch of work for themselves. They had to go through and review/update their credit card for each of their (5, I think?) websites.

Somehow, this _also_ lead to repeated credit cards being listed at the bottom of `/me/purchases/billing` which has caused more confusion.

--

I'd expect this small text to either be larger (and easier to understand) or, to make this an option. That is, adding a checkbox that says "Use this card for all sites and subscriptions".

**Comment by DavidRothstein** [comment]
I'm adding this to the payments backlog.

**Comment by DavidRothstein** [comment]
For what it's worth, the user interface for this has been redesigned since this was originally filed -- it now looks like the screenshot below.  I'm not sure that necessarily makes it more visible to users or not though:

![Screenshot from 2021-01-04 14-50-49](https://user-images.githubusercontent.com/235183/103573578-7c2b2880-4e9c-11eb-887a-f35e011514d6.png)

**Comment by Greatdane** [comment]
Marking this as closed now that the user interface has been redesigned. 

There is also now a checkbox that lets a user decide about using the new card for existing renewals. 

<img width="824" alt="Markup 2021-09-23 at 14 42 31" src="https://user-images.githubusercontent.com/5075840/134459498-93644b27-da42-4041-9061-ee21dcb7a788.png">
