### ISSUE TITLE
Unable to re-order blocks in editor using Internet Explorer (IE)

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#39221]
#### Steps to reproduce
1. Open page in the WordPress editor using IE 11 and add multiple blocks to the page 
2. Try to reorder a blocks

#### What I expected

1. The control with arrows up and down would be there to reorder the blocks

#### What happened instead

1. There was no control to reorder the block, and no visible workaround using visual controls

#### Browser / OS version

IE 11 on Windows 10 (18362)

#### Screenshot / Video

![Annotation on 2020-02-03 at 17-39-27](https://user-images.githubusercontent.com/51966986/73676404-37a37580-46ac-11ea-91d9-024ab0e55b51.png)

#### Context / Source
 

#user-report

2659165-zen

**Comment by zdenys** [comment]
Possibly the same issue as the one in Microsoft Edge https://github.com/Automattic/wp-calypso/issues/39072. The workaround is to set the Top toolbar as mentioned in https://github.com/Automattic/wp-calypso/issues/39072#issuecomment-582491328. I'll keep this one open so it can be closed once the other issue is addressed.

**Comment by kriskarkoski** [comment]
#39072 has been resolved and this looks to be fixed now as well. Tested IE 11 on Windows 10 on Browserstack and was able to see and use reorder buttons
