### ISSUE TITLE
People: fix awkward wording in author invite email message

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3924]
The body of the email for author invites says:

> [Site Owner Name] has invited you to author [Site Name]. As an author you will be able to publish and edit your own posts as well as upload media.
 
The sentence "[Site Owner Name] has invited you to author [Site Name]" is a bit awkward. Here are a couple suggestions to make it better:

- [Site Owner Name] has invited you to become an author of [Site Name]
- [Site Owner Name] has invited you to write for [Site Name]

**Comment by ebinnion** [comment]
Fixed in r132653-wpcom.
