### ISSUE TITLE
People: in admin invite email, fix body title

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3925]
When sending out an invite to administer a site, the email's title is incorrect, it refers to contributing instead of administrating. It says:

> Valerie invited you to contribute to Test Site

![screen shot 2016-03-09 at 5 39 56 pm](https://cloud.githubusercontent.com/assets/11487924/13653205/3a989592-e61e-11e5-95d1-e88c76268f19.png)

Instead the title should say:

> Valerie invited you to administrate Test Site

**Comment by ebinnion** [comment]
Fixed in r132652-wpcom. Props to @v18!
