### ISSUE TITLE
Homepage Articles block: allow multiple instances per post

### ISSUE THREAD

**Issue by adekbadek** [Automattic/wp-calypso#39251]
As reported on newspack-blocks repo (https://github.com/Automattic/newspack-blocks/issues/317), adding multiple Homepage Articles (aka Blog Posts) blocks should be possible. 

This was done deliberately in https://github.com/Automattic/wp-calypso/issues/38404:
https://github.com/Automattic/wp-calypso/blob/b6e7b09b1be3c9b8eb9d790755ec8c9adb1cd23f/apps/full-site-editing/full-site-editing-plugin/blog-posts-block/editor.js#L36
This issue is more of a reminder and a place for further discussion.

As @kspilarski mentioned, this surfaced in 2666978-zd

**Comment by kspilarski** [comment]
User in 2666978-zd would like to be able to use the Blog Post block more than once in a page or post. But it's not possible, as when it's used once, trying to add Blog Post button again would be greyed out and is not possible to be selected: 

Here's a screenshot from my test site: 

<img width="1504" alt="Screen Shot 2020-02-04 at 3 28 07 PM" src="https://user-images.githubusercontent.com/36863633/73753801-89f39d80-4763-11ea-8feb-e8c613614a65.png">

**Comment by zdenys** [comment]
Just cross-linking this other issue https://github.com/Automattic/wp-calypso/issues/39212 so it can be closed once the above one is addressed.

**Comment by simison** [comment]
Still an issue, pending fix in https://github.com/Automattic/wp-calypso/pull/39270
