### ISSUE TITLE
Pages: copy link dropdown option has strange formatting

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#39255]
![image](https://user-images.githubusercontent.com/437258/73755956-d5428780-4734-11ea-82ad-92fa1f8293b2.png)

The copy link option is a button within the dropdown. It should not be. There's also a strange hover state that causes a wiggle in the dropdown.

**Comment by kwight** [comment]
Doesn't look like this is valid any more, but I can't immediately see an commit that would have "fixed" it – @rickybanister @lcollette  are either of you still seeing this anywhere?..

**Comment by kwight** [comment]
Calling this "fixed", and closing.

<img width="403" alt="Screen Shot 2020-02-12 at 11 13 05 AM" src="https://user-images.githubusercontent.com/349751/74368537-b5404300-4d88-11ea-9775-e4884db6915f.png">

**Comment by danhauk** [comment]
Repoening this since I saw it appear inconsistently today on Chrome 80.0.3987.116

<img width="236" alt="Screen Shot 2020-02-26 at 2 55 54 PM" src="https://user-images.githubusercontent.com/448298/75403330-ac627c00-5907-11ea-819a-9b1a65c90aa9.png">

**Comment by simison** [comment]
This might depend on loading order of CSS bundles, which depends on order of visited pages.

cc @Automattic/team-calypso

**Comment by tyxla** [comment]
Going to file a fix to make this independent from the loading order of CSS bundles.

**Comment by tyxla** [comment]
Fix: #39994
