### ISSUE TITLE
Mapping own domain: only `http` could be misleading?

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#39264]
#### Steps to reproduce
1. Add a new website
2. Use "Use Domain I Own" step

#### What I expected
You are asked to enter your website address. It starts with *http* (see screenshot), while my website only starts with *https* :trollface:.

#### What happened instead
It forces me to enter an *http* domain name (see screenshot)

#### Browser / OS version
All

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/790558/73786853-68fa6f00-479a-11ea-9b0b-436e26640338.png)

#### Context / Source
It is not a bug *per say*, but it could be misleading to some users. Just reporting as I noticed it. 
Also, the bare http being less and less used, maybe something should be done here for "standard" users.

#anecdote #user-report

**Comment by Aurorum** [comment]
This does appear to me to be an old screen, what is the path for it? I presume it should've been removed with #32635.

**Comment by millerf** [comment]
@Aurorum It is, I just realised I was working from a fork I did ages ago. Closing this issue now.
