### ISSUE TITLE
People: invite email small print should correctly say whether email or username was entered

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3926]
#### Steps to reproduce
1. Invite a user - using the username, and not the email address - to your site in any role: follower, admin, author, editor, contributor
2. See that the invite email says this in the footer:

> Small print: This message was sent by a WordPress.com user who entered your email address to invite you.

![screen shot 2016-03-09 at 5 45 19 pm](https://cloud.githubusercontent.com/assets/11487924/13653282/c1c161d4-e61e-11e5-8010-44572b69a545.png)

This is technically incorrect - the WordPress.com user entered this person's **username**, not their **email address**. We can fix this by specifying which was used - either email address or username.

**Comment by ebinnion** [comment]
Addressed in r132671-wpcom.

Note that I updated the the string to be:

> This message was sent by a WordPress.com user who entered your email address **or username** to invite you.
