### ISSUE TITLE
SPT: Overflowing Featured Image in Blog Posts block in preview

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#39278]
I just saw that the featured image in the blog posts block in the blog layout is overflowing. 

<img width="1761" alt="Screenshot 2020-02-05 at 12 31 34" src="https://user-images.githubusercontent.com/908665/73843153-f9c26080-4815-11ea-9645-92ead984e861.png">

However, the overflow doesn't happen when you're in the editor after selecting the layout.

![Screenshot 2020-02-05 at 12 46 20](https://user-images.githubusercontent.com/908665/73843290-47d76400-4816-11ea-9a64-8d090879ecfa.png)

It looks like the preview doesn't have the 100% max-width rule from Gutenberg.

<img width="341" alt="Screenshot 2020-02-05 at 12 41 59" src="https://user-images.githubusercontent.com/908665/73843118-e616fa00-4815-11ea-87f6-0b7baf0470c2.png">

**Comment by marekhrabe** [comment]
Very likely to be solved with the work being done to move previews into an iframe, where media queries and other styles match better.

**Comment by iamtakashi** [comment]
It looks like the preview is now in an iframe(?) But I can still see the overflowing images.

![Screenshot 2020-03-02 at 10 33 28](https://user-images.githubusercontent.com/908665/75668766-ba026380-5c71-11ea-908e-1edcea669fcb.png)

**Comment by obenland** [comment]
It looks like it's caused by [this Varia style](https://github.com/Automattic/themes/blob/master/varia/sass/blocks/blog-posts/_editor.scss#L48-L53)

**Comment by iamtakashi** [comment]
> It looks like it's caused by this Varia style

No :) If it was caused by the Varia style, the image would overflow in the editor as well, right? But it's fine in the editor.

I mentioned initially in this issue, the preview doesn't have [this CSS from Gutenberg plugin](https://github.com/WordPress/gutenberg/blob/81d8afce4b6a85a90941bfc08368e0d4d03d7203/packages/edit-post/src/style.scss#L89) that is available in the editor. And themes rely on it. If that's not expected to be available in the preview, we'd need to add it for the preview somehow.
