### ISSUE TITLE
FSE: Template part does not load until you click it

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#39271]
After digging into this a bit, I only see this issue on Firefox Developer Edition, not in normal Firefox or in Brave.

### Steps to reproduce
1. On WordPress.com, open the FSE page editor
2. Observe the indefinite loader spinner on the header or footer
3. Click the header template part block
4. Observe the header load

### What I expected
The header should load immediately.

### What happened instead
The header loaded indefinitely

### Browser / OS version
Only seen in Firefox Developer Edition, **not** Brave or normal Firefox

### Screenshot / Video
![2020-02-04 19 17 36](https://user-images.githubusercontent.com/6265975/73808030-51fc5280-4783-11ea-801f-8b285a7df464.gif)

So far, I have determined that `const template = templateId && getEntityRecord( 'postType', 'wp_template_part', templateId );` is undefined until you click into the template part block.

**Comment by noahtallen** [comment]
If I run `wp.data.select( 'core' ).getEntityRecord( 'postType', 'wp_template_part', $header_id )` from the console, I do get a correct result, but it appears that it is not re-running the code once the template part exists

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
