### ISSUE TITLE
Purchases: "Remove plan" button inconsistent with other options

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39283]
The option to remove a plan subscription has inconsistent styling with the other options above it. It looks odd and out of place with an icon and the text is smaller than the other options.

![image](https://user-images.githubusercontent.com/448298/73865379-288a0800-4811-11ea-9fcd-9ab36be1aae4.png)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Click on a plan purchase.
3. See the options below the purchase details card.

#### What I expected
The button to have the same styling as the other items in the list. OR if the goal is to distinguish it from the others, break it out of this list.

#### What happened instead
The remove purchase button is styled different even though it's in a list.

#### Browser / OS version
Chrome 79.0.3945.130 / Mac OS 10.14.6 (18G1012)

#### Context / Source
#dogfooding

**Comment by nerdysandy** [comment]
It's still the same styling. This is why I removed the label ^

**Comment by michaeldcain** [comment]
This will possibly be handled by Shilling's Subscription Management updates. I'll add it to our backlog.

**Comment by michaeldcain** [comment]
Filippo designed a consistent set of actions before he left:

<img width="1214" alt="purchase-management" src="https://user-images.githubusercontent.com/942359/114056690-ecf92c80-985f-11eb-947c-af248160df35.png">
