### ISSUE TITLE
Plugin updates: CoBlocks 1.21.0

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#39290]
### Update March 16
The delay due to the data migration project (pbAok1-f8-p2) continues. We've taken the decision to start testing 7.7.1 https://github.com/Automattic/wp-calypso/issues/40078

### Update February 26

Due to the ongoing work on the data migration project (pbAok1-f8-p2), we're jumping to 7.6.0-rc.1 (and eventually 7.6.0). See https://github.com/Automattic/wp-calypso/issues/39689

----

Gutenberg 7.4.0 [was released on 5th Feb](https://github.com/WordPress/gutenberg/releases/tag/v7.4.0). CoBlocks 1.21.0 [was released on 13th Feb](https://github.com/godaddy-wordpress/coblocks/releases/tag/1.21.0). This issue tracks progress upgrading wpcom to use these versions.

Note that due to delays pbAok1-bt-p2 we are skipping alpha and RC versions of Gutenberg for this release cycle, and going straight to the stable release 7.4.0.

### Gutenberg
- [x] ~Install stable version: D38572-code~
- [x] ~Activate stable version on edge sites: D38573-code~
- [ ] ~Activate stable version on prod~
- [ ] ~Cleanup old versions of GB~
- [ ] ~Request update for AT sites~

### CoBlocks
- [x] Install stable version: D38905-code
- [x] Activate stable version on edge sites: D38916-code
- [x] Update the coblocks builder https://github.com/Automattic/coblocks-builder/pull/4
- [ ] Activate stable version on prod
- [ ] Cleanup old versions of GB
- [ ] Request update for AT sites

~Update: For the time-being we are just focusing on upgrading to GB 7.4.0 and will address CoBlocks upgrade separately.~ CoBlocks release added by @p-jackson 

### Other
- [ ] ~GB call for testing: p7DVsv-87m-p2~
- [ ] ~CB call for testing: p7DVsv-8a3-p2~
- [x] E2E tests PR: https://github.com/Automattic/wp-calypso/pull/39292

### Bugs encountered
- [ ] https://github.com/Automattic/wp-calypso/issues/39622
- [ ] #39710

**Comment by ramonjd** [comment]
We can still track Coblocks here. 

[7.6.0-rc.1 has a separate issue](https://github.com/Automattic/wp-calypso/issues/39689)

**Comment by ramonjd** [comment]
@p-jackson Have you got any spare time to verify if 1.21.0 fixes this bug?

https://github.com/Automattic/wp-calypso/issues/39710

**Comment by ramonjd** [comment]
Another https://github.com/Automattic/wp-calypso/issues/39622

**Comment by p-jackson** [comment]
Just following up #39710 is an existing CoBlocks issue, and I can't repro #39622

**Comment by ramonjd** [comment]
> Just following up #39710 is an existing CoBlocks issue, and I can't repro #39622

Thanks for chasing that up!

**Comment by roo2** [comment]
A fix for #39710 is included in coblocks 1.23.0

https://github.com/godaddy-wordpress/coblocks/releases/tag/1.23.0
https://github.com/godaddy-wordpress/coblocks/pull/1407

**Comment by roo2** [comment]
updating to 1.23.0 will solve those two bugs identified #40598

**Comment by roo2** [comment]
This user ran into a bug which would be fixed once we can deploy 1.21.0+ of codeblocks https://woothemes.zendesk.com/agent/tickets/2826522

**Comment by noahtallen** [comment]
This is now obsolete since we are testing the 1.23 update.
