### ISSUE TITLE
Reader: LaTeX rendered as superscript

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39329]
#### Steps to reproduce
1. Starting at URL: Post using [LaTeX](https://en.support.wordpress.com/latex/)
2. View it in the Reader

#### What I expected
See LaTeX in line with the rest of the text (as when I visit the Post in a new browser tab)

![Screen Shot on 2020-02-08 at 10:37:16](https://user-images.githubusercontent.com/39308239/74082916-05549800-4a5f-11ea-837b-48d9620c74f1.png)

#### What happened instead
All LaTeX formulas are rendered as superscript

![Screen Shot 2020-02-08 at 10 34 47](https://user-images.githubusercontent.com/39308239/74082891-c7f00a80-4a5e-11ea-84f6-ab1c971bcf63.png)

#### Browser / OS version
Any

#### Context / Source
#user-report ([on the forums](https://it.forums.wordpress.com/topic/problemi-latex/))

**Comment by millerf** [comment]
@zdenys Could you explain what you mean by Reader? 

I tried to reproduce the error without success. The Previewer displays this:

![Screenshot 2020-02-09 at 22 59 01](https://user-images.githubusercontent.com/790558/74110814-ddb11d00-4b8f-11ea-8eda-253575c2c7fc.png)

But I can see ssomething that might be of importance on the website referenced in the forum:
the latex is not processed in the summary of the article:
![Screenshot 2020-02-09 at 23 00 48](https://user-images.githubusercontent.com/790558/74110871-4f896680-4b90-11ea-9804-262a2dbac324.png)

Which makes me think this might be theme-related. As you can see here:
![Screenshot 2020-02-09 at 23 04 22](https://user-images.githubusercontent.com/790558/74110924-cd4d7200-4b90-11ea-808b-379760bc371d.png)

The theme I installed simply doesn't seem to process latex...

If you have any more information I'd be happy to help.

**Comment by millerf** [comment]
@zdenys Nevermind, I found it.
