### ISSUE TITLE
composite-checkout: Summary step does not make it clear that price shown is total

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#39321]
A tester did a quick test and choose Business > Digital Marketing and selected the free domain and saw $100 for the Business plan on checkout (instead of $300) in the first step. This is actually expected, because what's displayed in that step is the total (which already includes the credit discount), not the product price, but it's unclear from the UI especially when there's only one product.

**Comment by fditrapani** [comment]
I don't believe this happens anymore. @sirbrillig have you come across it lately?

**Comment by sirbrillig** [comment]
This is still happening, here's the steps to reproduce:

1. Add $100 in free credits to an account.
2. Add the Business plan to your cart.
3. Notice that the first step reads $200. This is the total, but it could be misunderstood to be for the Business plan rather than the actual cost of $300.

![Screen Shot 2020-03-30 at 11 55 22 AM](https://user-images.githubusercontent.com/2036909/77934071-8ff68e00-727d-11ea-8e5d-622a4de328e9.png)

**Comment by fditrapani** [comment]
Ok, right. Thanks. This is something that will most likely not be an issue after we reorder the steps.

**Comment by sirbrillig** [comment]
Fixed by reordering the steps.
