### ISSUE TITLE
DevDocs: CommentButtons component example - Search\Filter not working

### ISSUE THREAD

**Issue by afsheenirani** [Automattic/wp-calypso#3933]
#### Steps to reproduce
1. Starting at URL: [App Components](https://wpcalypso.wordpress.com/devdocs/app-components)

#### What I expected
Searching for `CommentButton` would filter down to that one component in the page.

#### What happened instead
Searching for `CommentButton` did not apply any filtering. Additionally, checking in Developer Console, the following error was displayed:
`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`

The issue here is that in `client/components/comment-button/docs/example.jsx` the `CommentButton` example has been refactored from a class into a stateless function and lost it's `displayName` property owed to which the search\filter functionality is currently broken.

#### Browser / OS version
Chrome, Mac OS X

cc: @bluefuton

**Comment by bluefuton** [comment]
Good spot @afsheenirani!

**Comment by afsheenirani** [comment]
Thanks @bluefuton! As you can see, I was already making a bunch of changes to the whole UI/App Components seach/filter summary, this just happened to show up once i rebased my branch :smile: 

Btw, let me know if you have any comments on the fix. I've lumped it in with my changes in #3811.

**Comment by afsheenirani** [comment]
This issue should now be closed via #3813.

**Comment by aduth** [comment]
As noted, closed by #3813.
