### ISSUE TITLE
Domain search filter does not remember selection

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#39337]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Go through the signup flow, and at the domain step select the exact match filter 
<img width="967" alt="Screenshot 2020-02-10 at 4 40 53 PM" src="https://user-images.githubusercontent.com/1269602/74145139-20243980-4c24-11ea-8042-b60101dffb56.png">

3. Select any domain to go to the Plans step. Now, hit the Back button to go back to the domain step.

#### What I expected

To see the filter remain selected

#### What happened instead

The filter selection is removed, though the search results show the filtered results

![domain-filter](https://user-images.githubusercontent.com/1269602/74145416-c2dcb800-4c24-11ea-8f4e-d02a1bfc48ec.gif)

**Comment by millerf** [comment]
@niranjan-uma-shankar This seems to be fixed. Just tested it right now.


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/790558/74588646-91863280-4ffe-11ea-9cec-71d793d46806.gif)

**Comment by niranjan-uma-shankar** [comment]
@millerf I pushed in a fix for this with https://github.com/Automattic/wp-calypso/pull/39346. I'll update the issue here, thanks.
