### ISSUE TITLE
Layouts: Missing Margin in Layout Preview

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39341]
Chrome and MacOS. I expected to see margin on either side of the preview.

![image](https://user-images.githubusercontent.com/545779/74169974-cc006180-4bf1-11ea-9226-dace894d7d40.png)

@iamtakashi @alaczek

**Comment by ianstewart** [comment]
Another example from the Menu Layout:

![image](https://user-images.githubusercontent.com/545779/74171201-c6a41680-4bf3-11ea-9f34-21a3cecdd1f4.png)

**Comment by ianstewart** [comment]
Another example from a Services layout …

![image](https://user-images.githubusercontent.com/545779/74180642-82217680-4c05-11ea-8923-5f5c764dd760.png)

**Comment by ianstewart** [comment]
Another example from the Balasana layout:

![image](https://user-images.githubusercontent.com/545779/74180935-f8be7400-4c05-11ea-85a6-13be74ff4cca.png)

**Comment by ianstewart** [comment]
Another example in the Hever layout:

![image](https://user-images.githubusercontent.com/545779/74182363-856a3180-4c08-11ea-8646-4c6a8110c95d.png)

And in the Leven layout:

![image](https://user-images.githubusercontent.com/545779/74182398-961aa780-4c08-11ea-9bc2-3c1233ae3693.png)

**Comment by ianstewart** [comment]
Another example here in the Morden layout:

![image](https://user-images.githubusercontent.com/545779/74182584-f01b6d00-4c08-11ea-9b89-7ad24343f0f8.png)

**Comment by ianstewart** [comment]
And the Rivington Layout:

![image](https://user-images.githubusercontent.com/545779/74182639-0aede180-4c09-11ea-81d8-ea8f5a7cb5a5.png)

**Comment by ianstewart** [comment]
Shawburn:

![image](https://user-images.githubusercontent.com/545779/74182776-4be5f600-4c09-11ea-9343-bce3ec83eb21.png)

**Comment by ianstewart** [comment]
Stow:

![image](https://user-images.githubusercontent.com/545779/74182814-5bfdd580-4c09-11ea-8ec5-f30fdf6eb054.png)

**Comment by ianstewart** [comment]
Twenty Twenty:

![image](https://user-images.githubusercontent.com/545779/74182855-6ddf7880-4c09-11ea-89c6-e5f0e5234809.png)

**Comment by obenland** [comment]
> we are rendering previews in a narrow container (that would usually trigger some smaller media queries), however the CSS media queries are computed against the whole screen which means unexpected results. […] core is working on processing media queries in a way they could be used regardless of screen size: https://github.com/WordPress/gutenberg/pull/19082
—@marekhrabe
