### ISSUE TITLE
Layouts: Poor Preview of Blog Layouts on new sites without any posts

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39342]
This is a poor example of what a blog post layout could provide. 

![image](https://user-images.githubusercontent.com/545779/74170317-55b02f00-4bf2-11ea-99cf-0f10e2874f14.png)

Is it possible to serve up example or placeholder content here to improve the preview? This will likely be something we'll also need to consider in onboarding contexts as well. cc @johnHackworth 

@iamtakashi @boonerang @alaczek

**Comment by ianstewart** [comment]
Another example from the Barnsbury Layout.

![image](https://user-images.githubusercontent.com/545779/74182163-26a4b800-4c08-11ea-8ff8-af4041ac742c.png)

**Comment by marekhrabe** [comment]
For the preview, we use real block code to render it and it always goes directly to API to get posts. 

Adding some sort of override just for the preview, while technically possible, could bring a lot of unnecessary complexity to the block. 

I know that in the past, new wpcom sites used to be created with some example posts already posted on a site to prevent this exact situation happening on homepages (it was saying "Nothing here"). Did we stop doing this? Would it be a good idea to bring this back?

What is the priority on this issue? That will help us understand how we can solve this and if any short term compromises need to be done.

**Comment by marekhrabe** [comment]
For the preview, we use real block code to render it and it always goes directly to API to get posts. 

Adding some sort of override just for the preview, while technically possible, could bring a lot of unnecessary complexity to the block. 

I know that in the past, new wpcom sites used to be created with some example posts already posted on a site to prevent this exact situation happening on homepages (it was saying "Nothing here"). Did we stop doing this? Would it be a good idea to bring this back?

What is the priority on this issue? That will help us understand how we can solve this and if any short term compromises need to be done.

**Comment by getdave** [comment]
We do now have a way to manipulate Blocks going into Preview only if that helps sort this. But it sounds like it could add lots of complexity as well...

**Comment by iamtakashi** [comment]
> I know that in the past, new wpcom sites used to be created with some example posts already posted on a site to prevent this exact situation happening on homepages (it was saying "Nothing here"). Did we stop doing this? Would it be a good idea to bring this back?

I've just tested this by creating some new sites. It seems that we only make some example posts if the site is in the blog segment. So newly created sites in the business and professional segments will have this issue. I wonder if we should make some example posts for those segments as well.

**Comment by marekhrabe** [comment]
> I wonder if we should make some example posts for those segments as well.

I think that would be a good idea. While we can _technically_ solve it in the block, it will be an unprecedented change. All other alterations of blocks in previews are only done by tweaking some of their settings/attributes. Here we would have to update the main block source code to add a specific behavior solely for a preview.

Another thing to look at is that adding example posts to headstart will only fix newly created sites. Is that an acceptable solution?

**Comment by alaczek** [comment]
> Adding some sort of override just for the preview, while technically possible, could bring a lot of unnecessary complexity to the block.

Would this mean the block would display posts in the preview, but not when the page template was actually applied on a site with no posts? If so, it could be really confusing for the customer.

> Another thing to look at is that adding example posts to headstart will only fix newly created sites. Is that an acceptable solution?

Not ideal, but I would say yes - it seems to be a better long term solution. But curious to hear what others think.

**Comment by davemart-in** [comment]
It looks like we already have a placeholder to put something, it just doesn't look great:

<img width="846" alt="placeholder" src="https://user-images.githubusercontent.com/5634774/75810307-5868f480-5d58-11ea-8e32-913545b0b604.png">

As a simple next step, let's just update the design/content of what we're showing in that spot to be something like:

![blank-slate](https://user-images.githubusercontent.com/5634774/75810762-2dcb6b80-5d59-11ea-8d9d-2b96bfeb3294.png)

Borrowing styles from the post list blank slate screen:

![posts-blank-slate](https://user-images.githubusercontent.com/5634774/75810789-3d4ab480-5d59-11ea-99b0-922398e3fa65.png)

**Comment by ianstewart** [comment]
This issue can still be reproduced.

At some point this year we will likely replace all these occurrences with [the Query Block](https://github.com/WordPress/gutenberg/issues/26316) (or a _Variation_ of it) — cc @alaczek  — but unsure of the specific timelines beyond that more general one.

**Comment by shaunandrews** [comment]
The Navigation and Social Icons blocks have a new(-ish) empty state that shows a minimal visual representation of how the block _could_ look once setup:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/191598/110505399-1a6d8180-80cc-11eb-87db-4ff99038eeec.png">

It might make sense to create and render a similar "skeletal" placeholder for the content blocks.

**Comment by apeatling** [comment]
I don't think we are going to work on this, and will replace with the Query block, so removing from backlog.
