### ISSUE TITLE
Page Templates: Track template insertion/removal caused by the template selector

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#39357]
Looking at the tech implementation of the template selector, the template insertion has been switched in November to use `replaceInnerBlocks` instead of `insertBlocks` under the hood. Doing this switch in #37500, tracking wasn't considered and has been effectively removed with that change.

This means events are no longer being triggered for blocks inserted or removed as part of the template selector interactions. I think this should be fixed in order to be able to build reliable funnels like `block_inserted > block_published`. Currently, we only know about the "published" part.

I propose we add tracking for `replaceInnerBlocks` to fire the same events as regular `insertBlocks`/`removeBlocks` and we add a new property to the event to indicate the source of the event is the template selector.

**Comment by getdave** [comment]
I wonder if we could implement some kind of test coverage on our tracking? Perhaps testing that certain actions fire certain events...etc.

**Comment by marekhrabe** [comment]
About to be shipped in the next FSE release very soon.
