### ISSUE TITLE
Layouts: Replace Home Page Previews with static images

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39352]
~We can see that they're too short for the space given to display them.~

# Edit 6th March:

This issues has been changed from fixing issues with aspect ratios into replacing mshot previews with static images. We need to find a place where to store previews (should be the same as vertical layout screenshots) and we need to update our backend code to return those images instead of generating mshot link.

Images: p1582672574371100-slack-CJS75TX3R

Place to update code in backend - similar as D39359-code

Fixes #38064.

**Comment by obenland** [comment]
That is an mshot issue. We might be able to leverage the existing workaround for demoblog banners to not show those notifications on mshot requests

**Comment by ianstewart** [comment]
Are the other page templates using mShots?

**Comment by obenland** [comment]
To my knowledge, homepage templates are the only ones

**Comment by ianstewart** [comment]
Perhaps skip using mshots altogether? And just provide thumbnails similar to the other layouts? It might help the home page layouts from looking so much like … themes. cc @iamtakashi

**Comment by obenland** [comment]
We could use `headstartdata` for homepage templates as well. At the time we added them we only had `a8ctm1` and wanted to avoid having assets all over the place.

**Comment by iamtakashi** [comment]
> Perhaps skip using mshots altogether? And just provide thumbnails similar to the other layouts? It might help the home page layouts from looking so much like … themes

I have sent @apeatling static screenshots of the homepages with Maywood a while ago.

**Comment by ianstewart** [comment]
I think (for now, until we have dynamic previews or something better) that static screenshots will be best.

**Comment by obenland** [comment]
@iamtakashi Do you still have access to those static screenshots? Would you mind making them accessible here?

**Comment by marekhrabe** [comment]
This is two separate issues mixed together, I'll extract the visible notice into its own and let's solve the screen ratio here. 

We can fix the thumbnail size ratio by properly requesting a screenshot from mshots. Reading through mshots source code, I can see it has parameters to configure the viewport width and height (`vpw` and `vph`), as well as the width and the height (`width` and `height`) of resulting image. 

Example URL that does a square thumbnail of theme demo site: https://s.wordpress.com/mshots/v1/https%3A%2F%2Falvesdemo.wordpress.com%2F%3Ftheme_preview%3Dtrue?w=300&height=300&vpw=1300&vph=1300

Can somebody from design play with `vpw` and `vph` to make sure screenshots look their best for the selector? Once we have determined the right size, I can make a PR that updates it. 1300 looks ok to me but I'll leave that decision up to you to confirm

**Comment by obenland** [comment]
Nice find! Do the width/height and vpw/vph sets need to be in the same aspect ratio for this to work?

**Comment by marekhrabe** [comment]
I'm still getting some strange ratio issues as you've described even with lower sizes. Looking into it…

**Comment by marekhrabe** [comment]
960 ended up being the best number that worked without any unexpected glitches. There might be a bug in mshots that prevents anything higher than default (which is 960) but I think we should be good for now just using the number. Screenshots look good to me

D39359-code up for a review

**Comment by marekhrabe** [comment]
code updated, backend caches might take ~24hrs to clear

**Comment by marekhrabe** [comment]
All homepage layouts should now look nicer. We have updated their size ratios and removed cookie notices which were present in some templates. Now looking like this:

<img width="431" alt="Screenshot 2020-02-27 at 15 19 31" src="https://user-images.githubusercontent.com/156676/75453700-963ed500-5974-11ea-9928-fe65da37a2f0.png">

**Comment by ianstewart** [comment]
> @iamtakashi Do you still have access to those static screenshots? Would you mind making them accessible here?

… or in a separate issue?

**Comment by iamtakashi** [comment]
I sent it to @obenland a while ago.

**Comment by obenland** [comment]
I shared it in slack: https://a8c.slack.com/files/U029G7YEU/FUK7NH60N/homepage-thumbnails.zip

**Comment by iamtakashi** [comment]
What was the reason for keeping mshots? Not that I'm saying the static ones are 100 times better, but at least they don't include the headers and have consistency with other thumbnails.

**Comment by marekhrabe** [comment]
Since updating the current dynamic screenshots was a matter of only changing query arguments of the image URLs, it felt like the quickest solution we can get done and I went that way. 

Are they not acceptable? I don't know how to update templates to use static images but somebody in Ajax definitely knows so we can make that happen if it is a requirement. Feel free to reopen and update the issue if that needs to be done

**Comment by iamtakashi** [comment]
I'm reopening this and add a note of what we discussed about static thumbnails vs mshots for homepage templates.

Although it's not the most urgent item to do, but we do prefer static thumbnails over mshots because of the consistency with other non-homepage layouts.

**Comment by marekhrabe** [comment]
Started in D39999-code. 

I have used preview images that were uploaded to headstartdata site (somebody did that before me). They looked equal but I haven't checked all of them in detail. If some of them need to be replaced, we can do that.

**Comment by obenland** [comment]
Fixed in r205217-wpcom
