### ISSUE TITLE
List Block: Add "Text Settings" option to control text size, color

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#39358]
#### Summary

The "list" block in the block editor does not have any setting available in the page editor. This means we can setup paragraph blocks and control things like text size, color, background color, but then the list block can't match without using CSS (if the user has the Premium plan or higher.)

Example of the mismatch:
![Screen Shot 2020-02-10 at 4 40 20 PM](https://user-images.githubusercontent.com/33190975/74192775-2fa38280-4c24-11ea-996a-8a36af83ddea.jpg)

Options found in the paragraph block:
![Screen Shot 2020-02-10 at 4 40 42 PM](https://user-images.githubusercontent.com/33190975/74192823-49dd6080-4c24-11ea-8c3b-e3ea9ffe4b75.jpg)

Options found in the list block
![Screen Shot 2020-02-10 at 4 40 28 PM](https://user-images.githubusercontent.com/33190975/74192833-4d70e780-4c24-11ea-98bc-d2f045ac0ac7.jpg)

#### What I expected
A solution to make all of the text on my page look the same.

#### What happened instead
I have no options to control the text size, color, background, etc. of the list block

#### Context / Source
#user-report in 18487269-hc

**Comment by xpurichan** [comment]
Another request in 18631303-hc

**Comment by lancewillett** [comment]
This is more likely a core Gutenberg feature request, not something specific to WordPress.com.

That said, I'll be happy to share it between the projects.

Shared here: https://github.com/WordPress/gutenberg/issues/8171

See also:

- https://github.com/WordPress/gutenberg/issues/12420
- https://github.com/WordPress/gutenberg/issues/9016

**Comment by lancewillett** [comment]
Thanks for the report, @xpurichan — I'm closing it for now, as we can track it on the Gutenberg project GitHub instead.
