### ISSUE TITLE
Gutenboarding: Tighten fresh URL param

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#39370]
This is a bit loose, matching both of these:
- `https://example.com/?not-fresh`
- `https://example.com/?not-interested=fresh`

How about the following to better cover edge cases?

```suggestion
	return new URLSearchParams( window.location.search ).has( 'fresh' )
```

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/39310/files_

**Comment by jeraldjuice** [comment]
Good catch, thanks @sirreal !
