### ISSUE TITLE
People: Telling me superuser has a role when they don't

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#3937]
Steps to reproduce:
1. Find a superadmin user who's not already a user on your site
2. Try to add them to your site as one of these roles: admin, editor, author, contributor (not follower).
3. See this error:

> Invitee is already a member of site

![superadmin](https://cloud.githubusercontent.com/assets/11487924/13674267/ce15c3da-e6aa-11e5-8ee3-fb3c792c2e07.png)

**Comment by v18** [comment]
I can reproduce this with multiple superadmin users.

**Comment by ebinnion** [comment]
This should be fixed in r132385-wpcom. Please let me know if you continue to have issues.
