### ISSUE TITLE
Reduxify: Media

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#39379]
`lib/media` contains 4 flux stores, coupled together, and they're used to power the media library and its functionality that's integrated in the classic post editor. 

All those stores should be reduxified, and the relevant code ported to use the redux implementation:

- [x] `library-selected-store` - @tyxla, #40269
- [ ] `list-store`
- [ ] `store`
- [x] `validation-store` - @tyxla, #39372

**Comment by tyxla** [comment]
I've started working on this in https://github.com/Automattic/wp-calypso/pull/39372 which is split for easier review and testing to the following PRs:

- https://github.com/Automattic/wp-calypso/pull/39374
- https://github.com/Automattic/wp-calypso/pull/39375
- https://github.com/Automattic/wp-calypso/pull/39377
- https://github.com/Automattic/wp-calypso/pull/39378

**Comment by simison** [comment]
@tyxla are you also making sure they don't end up being part of monolithic store, and could easily be exported out from Calypso with rest of library? Asking because of @jameslnewell 's work.

**Comment by tyxla** [comment]
> @tyxla are you also making sure they don't end up being part of monolithic store, and could easily be exported out from Calypso with rest of library? Asking because of @jameslnewell 's work.

This is a good call, but we're not doing that right now. We're approaching it incrementally - reduxifying is one thing, and modularizing is another. It is on our radar, but IMHO it should be done step by step.  FWIW, once those stores are reduxified, modularizing them shouldn't be a big deal.

**Comment by lancewillett** [comment]
Possibly related — Document moving Media Library to Redux #26168

**Comment by tyxla** [comment]
I'm reduxifying some more today. I've spent some time working on getting rid of the media library selected items store in #40269 which is split for easier review and testing to the following PRs:

* #40271
* #40272
* #40273
* #40274

**Comment by saramarcondes** [comment]
I've started working on `list-store`. I'll update with PRs as I get them ready 😊

**Comment by tyxla** [comment]
@saramarcondes that's awesome news, thanks for working on that 🚀 ! 

Would you mind helping with reviewing and landing #40271, #40272, #40273, and #40274 first though? These remove one of the other media stores (the selected media items store) and have been pending for a review for a while 😉 

Thanks a bunch! 🙌

**Comment by saramarcondes** [comment]
@tyxla Yup! I'm seeing some overlaps in the `list-store` work anyway. I'll switch back to focusing on the existing PRs.

**Comment by tyxla** [comment]
Ace, thanks so much for picking those up ❤️

**Comment by flootr** [comment]
closing this as we fully reduxified the media flux store
