### ISSUE TITLE
Domain step in onbarding hiding prices on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39387]
#### Steps to reproduce
1. Starting at URL: WordPress.com/start
2. Click until you're at domain picking step
3. On small screen see this 
    ![Screenshot_20200211-221039_Firefox](https://user-images.githubusercontent.com/87168/74275223-2b5a9080-4d1c-11ea-95c6-8333fd8f4207.jpg)

#### Browser / OS version
Firefox mobile

#### Context / Source

Cc @kelliepeterson @klimeryk

**Comment by klimeryk** [comment]
@niranjan-uma-shankar is it perhaps connected to your changes from https://github.com/Automattic/wp-calypso/pull/39362?

**Comment by niranjan-uma-shankar** [comment]
@simison I see that the issue was raised a week ago. There've been some changes gone in since then. If you don't mind, could you check once again if you're still seeing this? (if yes, do you mind sharing the updated screenshot, thanks!)

**Comment by simison** [comment]
@niranjan-uma-shankar seems to work now 👍 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/87168/74822194-6c9b0380-530d-11ea-9b7f-da6ec564936b.png">

Tested with Firefox:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/87168/74822067-3a89a180-530d-11ea-86cc-267c9bd7b0dd.png">

Another tiny thing I noticed was that after selecting domain, I get to plans page with scroll little bit lower from the top of the page:

<img src="https://user-images.githubusercontent.com/87168/74822127-4ecd9e80-530d-11ea-98d1-da8d3c8e781d.png" alt="" width="300"/>

vs 

<img src="https://user-images.githubusercontent.com/87168/74822132-512ff880-530d-11ea-9dee-1d7202466cdb.png" alt="" width="300"/>
