### ISSUE TITLE
Reader: Tumblr embedded posts don't appear in the reader

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3939]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. View a WordPress.com post that has an embedded tumblr post (eg. http://juicedpixels.com/2016/03/10/how-to-lose-weight-in-4-easy-steps/)

#### What I expected

Tumblr post to show in Reader: as per viewing the web page: 
![embed](https://cloud.githubusercontent.com/assets/128826/13660630/8a27b89a-e6d7-11e5-95a5-1981d8d8c010.PNG)

#### What happened instead

Tumblr post shows as URL: 
![reader view](https://cloud.githubusercontent.com/assets/128826/13660652/bdabb77a-e6d7-11e5-8b62-3eda9a1ea065.png)

**Comment by blowery** [comment]
Fixed!
