### ISSUE TITLE
Domain step test: Fix pricing text alignment

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#39393]
As @niranjan-uma-shankar pointed out in his [comment here](https://github.com/Automattic/wp-calypso/pull/39295#issuecomment-584093378), the alignment of the pricing text (info icon, unit of currency, price, and "Free"/"Free with a paid plan" text) is off in some currencies.

To fix this, I'd like to suggest we move the info icon to the right of the text and make the pricing text group right-aligned. Screenshots:

<img width="758" alt="Screen Shot 2020-02-11 at 2 58 11 PM" src="https://user-images.githubusercontent.com/204742/74283354-f67c1880-4cde-11ea-9045-2ba7d821aeb7.png">

**Comment by niranjan-uma-shankar** [comment]
@joanrho I see that the *.wordpress.com has a new tooltip icon included. Is that intentional? If yes, what would be the tooltip text for it?

**Comment by joanrho** [comment]
@niranjan-uma-shankar Sorry for not including that mock and text in the Issue. Yes, that's intentional and should look and read as follows:

<img width="1311" alt="Free domain tooltip" src="https://user-images.githubusercontent.com/204742/74439151-e6705000-4e28-11ea-9aa5-b186365c1c41.png">

**Test to use:**
>Every WordPress.com site comes with a free address using a WordPress.com subdomain. [Learn more](https://en.support.wordpress.com/domains/#domain-name-overview)

^ where "Learn more" links to our Support page at https://en.support.wordpress.com/domains/#domain-name-overview, which explains the free *.wordpress.com subdomain address.

**Comment by niranjan-uma-shankar** [comment]
> Every WordPress.com site comes with a free address using a WordPress.com subdomain. Learn more

I just realized that this text might not sound apt if we show this against a *.blog domain:

<img width="999" alt="Screenshot 2020-02-17 at 11 30 39 AM" src="https://user-images.githubusercontent.com/1269602/74627464-f2397a80-5178-11ea-9afb-ee6adb86d9a9.png">

**Comment by michelleweber** [comment]
Since there's a "learn more" link in the tooltip, I'd think you just say something like "Every WordPress.com site comes with a free address on our subdomain." or "Every WordPress.com site comes with a free wordpress.com or .blog address."

As an aside, I wonder if the "our" language will help drive people to making a purchase, because they want their site to be *theirs*. Although I'd probably go with the second of those two options to avoid the word "subdomain" altogether; it reads kinda technical.

**Comment by victorespigares** [comment]
@niranjan-uma-shankar how much trouble is to change the tooltip message depending if there's a .blog subdomain or a WordPress.com one?

That way, for WordPress.com subdomains we can have...

> Every WordPress.com site comes with a free address using a WordPress.com subdomain. Learn more

And for .blog subdomains...

> Every WordPress.com blog comes with a free address using a .blog address. Learn more

**Comment by niranjan-uma-shankar** [comment]
It's not much of a hassle. When site type is `Blog`, we show _both_ the .blog and .wordpress.com tooltips as shown in the screenshot in my comment above. Do you suggest a different content for the tooltips even when both .blog and .wordpress.com subdomains are visible at the same time?

**Comment by victorespigares** [comment]
Yes, I was thinking of having a different tooltip for .blog and for .wordpress.com subdomains, so it makes sense for each one. But as said, we can have same text for both with the previous suggestions and that'd work just fine.
