### ISSUE TITLE
Make Privacy Warning (Shown Before a Simple Site Goes Atomic) More Helpful

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#39408]
Before a user installs a third-party plugin or theme on a private Simple site, they're shown a warning that prompts them to set the site to public. That warning isn't currently that helpful, as it doesn't provide clear instructions for changing the setting and the **Help** button leads to [a support doc](https://en.support.wordpress.com/settings/privacy-settings/).

#### Steps to reproduce
1. Starting at URL, on a private Simple site: https://wordpress.com/plugins/
2. Select any plugin and go through the steps to install it.
3. View the warnings.

#### What I expected

After upgrading to WordPress.com Business, I expect the process of installing a third-party plugin or theme to be relatively smooth, without any need to navigate away from the WordPress.com dashboard. 

#### What happened instead

The following warning is displayed before I'm able to install a plugin/theme:

<img width="847" alt="Screenshot 2020-02-12 at 11 58 55" src="https://user-images.githubusercontent.com/2998162/74333058-11a66100-4d8f-11ea-9633-9803ff4d2780.png">

The **Help** button leads to [a support doc](https://en.support.wordpress.com/settings/privacy-settings). 

It'd make the process smoother if the button actually led to the relevant settings within the WordPress.com dashboard or, better yet, actually launched the site for the user.

Note, it'll soon be possible for Atomic sites to be private (ref: p58i-8xH-p2), so this warning may soon be gone completely.

#### Context / Source

Posting this after a discussion in our team's channel from earlier today. cc: @davoraltman @cecilearkay 

#context #empathy #perspective #dogfooding #painpoint

**Comment by gwwar** [comment]
@adamziel @michaeldcain is there any reason to not wire in a launch my site button here in eligibility warnings? After Atomic private sites are available to folks this can be removed as an error from eligibility checks as a server diff.

**Comment by gwwar** [comment]
I think we can probably go ahead and add a launch site button here. If private atomic sites are available later, this will be removed from the eligibility checks endpoint.

Note that I would recommend skipping the domain upsell flow in this case, since folks already paid for a business plan and would like to AT.

**Comment by Aurorum** [comment]
@gwwar are you aware of any way to make this appear without upgrading? I was going to try spin up a PR for this, but the logic for making it appear doesn't it seem to be present in Calypso

https://github.com/Automattic/wp-calypso/blob/84c84cb4b83a414cae33ea7a03dfeae5a8989d98/client/my-sites/plugins/plugin-eligibility/index.jsx#L54-L57

**Comment by gwwar** [comment]
@Aurorum This one might be tricky to test without access to the backend pieces here and a few test sites. If you're still interested feel free to spin up a WIP patch, and we can maybe async pair on it.
