### ISSUE TITLE
Domain Search Results Page: Improve filtering experience

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#39415]
The current and variant Domain Search Results pages have a few different filtering option areas:
1. Exact text matching (showing only domain names that exactly match input text)
2. TLD filtering via a "More extensions" dropdown menu
3. Sponsored TLD filtering (the .com, .net, .org, .blog, .club, .co buttons next to "More extensions")

**Screenshots:**
<img width="1357" alt="Screen Shot 2020-02-12 at 9 57 26 AM" src="https://user-images.githubusercontent.com/204742/74358305-7c9b6c00-4d7e-11ea-93d9-7da0aa833301.png">
<img width="1358" alt="Screen Shot 2020-02-12 at 9 59 39 AM" src="https://user-images.githubusercontent.com/204742/74358313-7f965c80-4d7e-11ea-9bf6-ec933f26c0ea.png">

**Problems with the above filtering options:**

- These filtering options could possibly be combined for a more streamlined experience, as both options affect the resulting list view. See example from @niranjan-uma-shankar in his [comment here](https://github.com/Automattic/wp-calypso/pull/39334#issuecomment-585022170). 
- The "More extensions" button and the long list of TLDs within the dropdown need to better indicate that selected TLDs (tokens) affect the results list when in the collapsed state. The solution needs to make the selected TLD tokens visible outside of the dropdown—more design exploration is needed here.
- We need to design for future advanced filtering options, such as price filtering. One idea [I mentioned here](https://github.com/Automattic/wp-calypso/pull/39334#issuecomment-585290812) would be to include a sliding scale for price filtering, but further discussion with Product and Marketing is needed to assess what we need to design for.

cc @olaolusoga

**Comment by klimeryk** [comment]
Closing this as wontfix - I agree there's a lot of potential here and the filters need improvements, but I'm not sure keeping this issue around will make that happen.
