### ISSUE TITLE
Customer Home: Completed checklist details are confusing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#39416]
When looking at the completed checklist, we're offered additional details in the card expansion. For the two I've seen, they're quite confusing; they seem to imply you still have to do (or should do again) the action that is marked as done. We should either give more appropriate next actions for the, uh, next action, or update the text to better reflect the completed context.

<img width="738" alt="Screen Shot 2020-02-12 at 9 56 05 AM" src="https://user-images.githubusercontent.com/349751/74362986-7d340280-4d7e-11ea-905a-974e47062a04.png">
<img width="739" alt="Screen Shot 2020-02-12 at 9 56 37 AM" src="https://user-images.githubusercontent.com/349751/74362938-668dab80-4d7e-11ea-9123-3764e09cfd87.png">

**Comment by dezzie** [comment]
@danhauk or @sixhours might have the context for this one, but my understanding is that the implemented checklist is a scoped-down versioni of the full thing as we've got it in calypso dev docs: https://wpcalypso.wordpress.com/devdocs/design/checklist

At first glance, it looks like bad UI copy. But it might have something to do with the checklist not being smart enough right now to know whether or not you actually completed a task. If we can make it so, we can most definitely clean up the bad UI copy. What do you think?

**Comment by Aurorum** [comment]
Would something like this with a disabled button and a checkmark (like the one in the link above rather than the quick one I added in the image below) work better?

<img width="750" alt="Screenshot 2020-02-12 at 20 49 30" src="https://user-images.githubusercontent.com/43215253/74375990-3cb5a280-4dd9-11ea-8972-15940b3f77ef.png">

**Comment by sixhours** [comment]
Looks like we just need to add a `completedDescription` prop to each task and update the copy. I'll start a PR and ping Obi for copy assistance.
