### ISSUE TITLE
Domain Step test: Fix "More Extensions" button so it doesn't remain depressed

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#39414]
As @ramonjd and @niranjan-uma-shankar [pointed out in 39346](https://github.com/Automattic/wp-calypso/pull/39346#issuecomment-585034607), the "More Extensions" button remains depressed when TLDs are selected from the dropdown. This behavior feels like a bug, and should be fixed so that the button remains in the non-depressed state for now.

That button and the long list of TLDs within the dropdown is a larger design issue that needs to be solved and then implemented outside of the current A/B test to avoid introducing too many variables. The improved experience will need to better indicate that selected TLDs affect the results list when in the collapsed state. I'll open a separate Issue for that tagged "Needs Design". (fyi @olaolusoga)

**Comment by niranjan-uma-shankar** [comment]
@joanrho I believe the reason why the button shows in a pressed state is to indicate that a TLD filter from the dropdown has been selected. Else, there is no visual indication that a TLD from the dropdown has been selected if that TLD is not already visible in the filter bar. 

In the image below, I have selected .accountants and .agency from the dropdown, and the depressed button shows some indication that a filter has been selected.

Can we show it pressed only when a TLD not in the visible area has been selected?
Or do we always remove the pressed state of the button?

<img width="961" alt="Screenshot 2020-02-13 at 8 58 00 PM" src="https://user-images.githubusercontent.com/1269602/74450076-8bc80a00-4ea3-11ea-8b6c-15d23a86f050.png">

**Comment by joanrho** [comment]
>I believe the reason why the button shows in a pressed state is to indicate that a TLD filter from the dropdown has been selected. Else, there is no visual indication that a TLD from the dropdown has been selected if that TLD is not already visible in the filter bar.

I understand that that's the intention, but it's not a good solution and feels more like a bug/mistake. We need to fix that experience entirely, which is why I opened #39415 to address this larger design problem (cc @olaolusoga). 

For example, when several TLDs (here in my screenshot, ".com", ".app", ".co", ".me") are selected, users need to see that all of their selections are affecting the output in the list of results. We need a solution that shows all of those selected ".com", ".app", ".co", ".me" tokens. Screenshot:

<img width="1439" alt="Screen Shot 2020-02-18 at 2 51 35 PM" src="https://user-images.githubusercontent.com/204742/74781165-381c3e80-525e-11ea-94ab-73356a1bfe0d.png">

For now, as an immediate fix to this, I'd recommend always removing the pressed state of the button and reusing an existing pattern on that page: applying the same color change as the Filter icon. The behavior there is that when "exact matches" checkbox is selected and "Applied", the Filter icon changes in color from dark grey to magenta. Likewise, it would make sense that the "More extensions" text and down arrow change in color accordingly. Screen capture of what I'm describing:

![filter](https://user-images.githubusercontent.com/204742/74781448-baa4fe00-525e-11ea-8f8c-9d061b925e72.gif)

Quick screenshot of what the interim solution should look like: 

<img width="1438" alt="Screen Shot 2020-02-18 at 2 56 45 PM" src="https://user-images.githubusercontent.com/204742/74781664-1f605880-525f-11ea-8791-de105c8dc145.png">

cc @olaolusoga @rickybanister if that makes sense to you both too ^ .

**Comment by olaolusoga** [comment]
Makes sense. I agree that _"We need to fix that experience entirely"_. The interim fix doesn't solve the problem, just provides a variation. We should work on a new UX (https://github.com/Automattic/wp-calypso/issues/39415) that provides a solution to the problem, and test that.
