### ISSUE TITLE
[Gutenboarding]: Investigation adding existing user login

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#39426]
We want existing users to be able to login in Gutenboarding. We don't want to send them off to a different page, e.g., wordpress.com/login, like we do in the current signup flow.

In very general terms, when an existing user is prompted to sign up, we'll offer a link to the login form which they can fill out _in situ_.

This might be rendering a login component in place of the signup component. The signin flow should otherwise be the same.

This take will require:

- investigation of [how users log in now in Calypso](https://github.com/Automattic/wp-calypso/tree/master/client/login)
- an update on the latest UI/UX from design. See pbAok1-bP-p2 to get started
- a decision/proposal as to what and how to port to Gutenboarding, including, ideally, buy-in from the Create team on required components, state, and so on

## Outcomes

Once we get an idea, or even half an idea of how we'd like to proceed, let's p2 a spec and ask for feedback from Create, design and others. 👍 

## Related reading

How native apps might unify WordPress.com sign up and login pauD4L-Bb-p2

**Comment by roo2** [comment]
I've started porting code across from `client/blocks/login/login-form.jsx`. I'm planning on getting passwordless login and username/password login working and leaving out social login for now.

* [] add to data-stores/user: `getAccountType` 
* [] add to data-stores/user: `loginUser`
* [] add to data-stores/user: `sendEmailLogin` for passwordless login
* [] manage expand/collapse state of the form
* [] work out what happens after login (redirect)
* [] error handling for getAccountType (user does not exist)
* [] error handling for loginUser (der waz error)
* [] loading states
* [] CSS styling tidy up
* [] work out what to do about social login (Link to existing login page for now?)
