### ISSUE TITLE
Framework: Migrate tests from Makefile to single test runner

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#3942]
Part of #3822.

### Makefile list

The following list contains all Makefiles we had when we started migration process:
* [x] [client/analytics/Makefile](https://github.com/Automattic/wp-calypso/pull/3994) @blowery √
* [x] [client/auth/Makefile](https://github.com/Automattic/wp-calypso/pull/4886) @gziolo √ 
* [x] [client/components/accordion/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/bulk-select/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/count/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @blowery √
* [x] [client/components/data/media-list-data/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/drop-zone/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/forms/counted-textarea/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/forms/form-phone-input/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @blowery √
* [x] [client/components/forms/form-toggle/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/forms/multi-checkbox/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/forms/range/Makefile](https://github.com/Automattic/wp-calypso/pull/4132) @umurkontaci √
* [x] [client/components/gravatar/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @jhnstn, @blowery √ 
* [x] [client/components/infinite-list/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @aduth, @blowery √ 
* [x] [client/components/root-child/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @aduth, @blowery √ 
* [x] [client/components/search/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @jhnstn, @blowery √ 
* [x] [client/components/section-nav/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @jhnstn, @blowery √ 
* [x] [client/components/theme/Makefile](https://github.com/Automattic/wp-calypso/pull/4163) @seear √
* [x] [client/components/themes-list/Makefile](https://github.com/Automattic/wp-calypso/pull/4163) @seear √
* [x] [client/components/tinymce/plugins/contact-form/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @blowery √ 
* [x] [client/components/tinymce/plugins/media/restrict-size/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @blowery √ 
* [x] [client/components/tinymce/plugins/wpcom-sourcecode/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @blowery √ 
* [x] [client/components/token-field/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @blowery √ :snail: 
* [x] [client/components/track-input-changes/Makefile](https://github.com/Automattic/wp-calypso/pull/4341) @blowery √ 
* [x] [client/devdocs/Makefile](https://github.com/Automattic/wp-calypso/pull/4411) @jhnstn √  
* [x] [client/lib/accept/Makefile](https://github.com/Automattic/wp-calypso/pull/4503) @aduth √
* [x] [client/lib/ads/Makefile](https://github.com/Automattic/wp-calypso/pull/4413) @gziolo √
* [x] [client/lib/auth-code-request-store/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/cart/store/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/lib/cart-values/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/lib/comment-like-store/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/comment-store/Makefile](https://github.com/Automattic/wp-calypso/pull/4354) @blowery √
* [x] [client/lib/create-selector/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/credit-card-details/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/lib/deterministic-stringify/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/domains/Makefile](https://github.com/Automattic/wp-calypso/pull/3784) @gziolo √
* [x] [client/lib/domains/dns/Makefile](https://github.com/Automattic/wp-calypso/pull/3784) @gziolo √
* [x] [client/lib/domains/email-forwarding/Makefile](https://github.com/Automattic/wp-calypso/pull/3784) @gziolo √
* [x] [client/lib/domains/nameservers/Makefile](https://github.com/Automattic/wp-calypso/pull/3784) @gziolo √
* [x] [client/lib/domains/whois/Makefile](https://github.com/Automattic/wp-calypso/pull/3784) @gziolo √
* [x] [client/lib/email-followers/Makefile](https://github.com/Automattic/wp-calypso/pull/4413) @gziolo √
* [x] [client/lib/features-list/Makefile](https://github.com/Automattic/wp-calypso/pull/4294) @stephanethomas √
* [x] [client/lib/feed-post-store/Makefile](https://github.com/Automattic/wp-calypso/pull/4354) @blowery √
* [x] client/lib/feed-store/Makefile @blowery √
* [x] [client/lib/feed-stream-store/Makefile](https://github.com/Automattic/wp-calypso/pull/4339) @blowery √
* [x] [client/lib/follow-list/Makefile](https://github.com/Automattic/wp-calypso/pull/4339) @blowery √
* [x] [client/lib/followers/Makefile](https://github.com/Automattic/wp-calypso/pull/4413) @gziolo √
* [x] [client/lib/form-state/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/formatting/Makefile](https://github.com/Automattic/wp-calypso/pull/4504) @aduth √
* [x] [client/lib/geocoding/Makefile](https://github.com/Automattic/wp-calypso/pull/4505) @aduth √
* [x] [client/lib/happiness-engineers/Makefile](https://github.com/Automattic/wp-calypso/pull/4413) @gziolo √
* [x] [client/lib/help-search/Makefile](https://github.com/Automattic/wp-calypso/pull/4465) @gziolo √
* [x] [client/lib/highlight/Makefile](https://github.com/Automattic/wp-calypso/pull/4465) @gziolo √
* [x] [client/lib/i18n-utils/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/importer/Makefile](https://github.com/Automattic/wp-calypso/pull/4279) @dmsnell √
* [x] [client/lib/interpolate-components/Makefile](https://github.com/Automattic/wp-calypso/pull/4465) @gziolo √
* [x] [client/lib/interval/Makefile](https://github.com/Automattic/wp-calypso/pull/4278) @dmsnell √
* [x] [client/lib/invites/Makefile](https://github.com/Automattic/wp-calypso/pull/4465) @gziolo √
* [x] [client/lib/keyboard-shortcuts/Makefile](https://github.com/Automattic/wp-calypso/pull/4521) @gziolo √
* [x] [client/lib/like-store/Makefile](https://github.com/Automattic/wp-calypso/pull/4339) @blowery √
* [x] [client/lib/local-list/Makefile](https://github.com/Automattic/wp-calypso/pull/4544) @gziolo √
* [x] [client/lib/local-storage/Makefile](https://github.com/Automattic/wp-calypso/pull/4544) @gziolo √
* [x] [client/lib/media/Makefile](https://github.com/Automattic/wp-calypso/pull/4524) @aduth √
* [x] [client/lib/media-serialization/Makefile](https://github.com/Automattic/wp-calypso/pull/4526) @aduth √
* [x] [client/lib/menu-data/Makefile](https://github.com/Automattic/wp-calypso/pull/4197) @seear √
* [x] [client/lib/mixins/data-observe/Makefile](https://github.com/Automattic/wp-calypso/pull/4561) @gziolo √
* [x] [client/lib/mixins/dirty-linked-state/Makefile](https://github.com/Automattic/wp-calypso/pull/4561) @gziolo √
* [x] [client/lib/mixins/i18n/Makefile](https://github.com/Automattic/wp-calypso/pull/4884) @gziolo √
* [x] [client/lib/mixins/pageable/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/mixins/searchable/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/mixins/url-search/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/network-connection/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/lib/notification-settings-store/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/oauth-store/Makefile](https://github.com/Automattic/wp-calypso/pull/4561) @gziolo √
* [x] [client/lib/olark-events/Makefile](https://github.com/Automattic/wp-calypso/pull/4579) @gziolo √
* [x] [client/lib/olark-store/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/paths/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/people/Makefile](https://github.com/Automattic/wp-calypso/pull/4866) @jhnstn  √
* [x] [client/lib/phone-validation/Makefile](https://github.com/Automattic/wp-calypso/pull/4867) @jhnstn  √
* [x] [client/lib/plans-list/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/lib/plugins/Makefile](https://github.com/Automattic/wp-calypso/pull/4877) @jhnstn √
* [x] [client/lib/plugins/wporg-data/Makefile](https://github.com/Automattic/wp-calypso/pull/4877) @jhnstn √
* [x] [client/lib/popup-monitor/Makefile](https://github.com/Automattic/wp-calypso/pull/4526) @aduth √
* [x] client/lib/post-formats/Makefile @blowery √
* [x] client/lib/post-metadata/Makefile @blowery √
* [x] client/lib/post-normalizer/Makefile @blowery √
* [x] client/lib/posts/Makefile @blowery √
* [x] [client/lib/preferences/Makefile](https://github.com/Automattic/wp-calypso/pull/4720) @aduth √
* [x] [client/lib/purchases/Makefile](https://github.com/Automattic/wp-calypso/pull/3884) @gziolo √
* [x] [client/lib/purchases/stored-cards/Makefile](https://github.com/Automattic/wp-calypso/pull/3884) @gziolo √
* [x] [client/lib/react-pass-to-children/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/react-test-env-setup/Makefile](https://github.com/Automattic/wp-calypso/pull/4526) @aduth √
* [x] [client/lib/reader-comment-email-subscriptions/Makefile](https://github.com/Automattic/wp-calypso/pull/3973) @blowery √
* [x] [client/lib/reader-feed-subscriptions/Makefile](https://github.com/Automattic/wp-calypso/pull/3973) @blowery √
* [x] [client/lib/reader-lists-items/Makefile](https://github.com/Automattic/wp-calypso/pull/3973) @blowery √
* [x] [client/lib/reader-lists-tags/Makefile](https://github.com/Automattic/wp-calypso/pull/3973) @blowery √
* [x] [client/lib/reader-post-email-subscriptions/Makefile](https://github.com/Automattic/wp-calypso/pull/3973) @blowery √
* [x] [client/lib/reader-site-blocks/Makefile](https://github.com/Automattic/wp-calypso/pull/3973) @blowery √
* [x] [client/lib/reader-site-store/Makefile](https://github.com/Automattic/wp-calypso/pull/3973)  @blowery √
* [x] [client/lib/reader-teams/Makefile](https://github.com/Automattic/wp-calypso/pull/3973) @blowery √
* [x] [client/lib/recommended-sites-store/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/resize-image-url/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/route/Makefile](https://github.com/Automattic/wp-calypso/pull/4605) @aduth √
* [x] [client/lib/safe-image-url/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/safe-protocol-url/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/scroll-to/Makefile](https://github.com/Automattic/wp-calypso/pull/4882) @jhnstn √
* [x] [client/lib/security-checkup/Makefile](https://github.com/Automattic/wp-calypso/pull/4883) @jhnstn
* [x] [client/lib/shortcode/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/signup/Makefile](https://github.com/Automattic/wp-calypso/pull/4301) @stephanethomas √
* [x] [client/lib/site/Makefile](https://github.com/Automattic/wp-calypso/pull/4412) @jhnstn √
* [x] [client/lib/site-roles/Makefile](https://github.com/Automattic/wp-calypso/pull/4412) @jhnstn √
* [x] [client/lib/sites-list/Makefile](https://github.com/Automattic/wp-calypso/pull/4412) @jhnstn √
* [x] [client/lib/stats/stats-list/Makefile](https://github.com/Automattic/wp-calypso/pull/4412) @jhnstn √
* [x] client/lib/store/Makefile (@gziolo) √
* [x] [client/lib/terms/Makefile](https://github.com/Automattic/wp-calypso/pull/4053) (@blowery) √
* [x] [client/lib/text-utils/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/tree-convert/Makefile](https://github.com/Automattic/wp-calypso/pull/4527) @jhnstn √
* [x] [client/lib/user/Makefile](https://github.com/Automattic/wp-calypso/pull/4609) @jhnstn √
* [x] [client/lib/user-settings/Makefile](https://github.com/Automattic/wp-calypso/pull/4609) @jhnstn √
* [x] [client/lib/users/Makefile](https://github.com/Automattic/wp-calypso/pull/4609) @jhnstn √
* [x] [client/lib/viewers/Makefile](https://github.com/Automattic/wp-calypso/pull/4609) @jhnstn √
* [x] [client/lib/wp/localization/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/lib/wp/sync-handler/Makefile](https://github.com/Automattic/wp-calypso/pull/4810) @gziolo √
* [x] [client/lib/wpcom-xhr-wrapper/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/my-sites/media-library/Makefile](https://github.com/Automattic/wp-calypso/pull/4552) @aduth √
* [x] [client/my-sites/menus/item-options/Makefile](https://github.com/Automattic/wp-calypso/pull/4197) @seear √
* [x] [client/my-sites/plugins/plugin-action/Makefile](https://github.com/Automattic/wp-calypso/pull/4604) @gziolo √
* [x] [client/my-sites/plugins/plugin-activate-toggle/Makefile](https://github.com/Automattic/wp-calypso/pull/4604) @gziolo √
* [x] [client/my-sites/plugins/plugin-autoupdate-toggle/Makefile](https://github.com/Automattic/wp-calypso/pull/4604) @gziolo √
* [x] [client/my-sites/upgrades/cart/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/my-sites/upgrades/components/domain-warnings/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/my-sites/upgrades/domain-search/Makefile](https://github.com/Automattic/wp-calypso/pull/3978) @gziolo √
* [x] [client/post-editor/editor-discussion/Makefile](https://github.com/Automattic/wp-calypso/pull/4550) @aduth √
* [x] [client/post-editor/editor-ground-control/Makefile](https://github.com/Automattic/wp-calypso/pull/4550) @aduth √
* [x] [client/post-editor/editor-sharing/Makefile](https://github.com/Automattic/wp-calypso/pull/4550) @aduth √
* [x] [client/post-editor/editor-taxonomies/Makefile](https://github.com/Automattic/wp-calypso/pull/4550) @aduth √
* [x] [client/post-editor/Makefile](https://github.com/Automattic/wp-calypso/pull/4088) @aduth √
* [x] [client/post-editor/media-modal/Makefile](https://github.com/Automattic/wp-calypso/pull/4552) @aduth √
* [x] [client/reader/route/Makefile](https://github.com/Automattic/wp-calypso/pull/3988) @gziolo √
* [x] [client/signup/config/Makefile](https://github.com/Automattic/wp-calypso/pull/4301) @stephanethomas √
* [x] [client/signup/Makefile](https://github.com/Automattic/wp-calypso/pull/4301) @stephanethomas √
* [x] server/api/Makefile @blowery √
* [x] server/config/Makefile @blowery √
* [x] server/i18n/Makefile @blowery √
* [x] ~~server/i18nlint/Makefile~~ - folder replaced by ESLint plugins √
* [x] server/pages/Makefile (@blowery) √
* [x] [state/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/application/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/comments/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth)  √
* [x] [state/current-user/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/google-apps-users/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/notices/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/plugins/wporg/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/post-types/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/posts/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/receipts/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/sharing/publicize/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/site-settings/exporter/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/sites/plans/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/support/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/themes/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/themes/current-theme/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/themes/theme-details/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/themes/themes/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/themes/themes-last-query/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/themes/themes-list/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/ui/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/ui/editor/contact-form/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/ui/reader/fullpost/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √
* [x] [state/users/Makefile](https://github.com/Automattic/wp-calypso/pull/3773) (@aduth) √

Please assign yourself to the list when you start working on removing `Makefile` in favor of single test runner.

√ - it means test suite can be executed independently from other suites using `npm run test-client path/to/test/file-name.js`
x - it means test suite depends on other suite - we should fix that at some point

**Comment by gziolo** [comment]
@mtias can you help us find more devs to speed up migration process? :)

**Comment by aduth** [comment]
I assigned myself a handful more tests, which I'll plan to start migrating today.

**Comment by gziolo** [comment]
@aduth: Awesome, feel free to ping me for a review ;)

I noticed that also @umurkontaci assigned to some tests, same rule applies of course :D

**Comment by umurkontaci** [comment]
I have tried `client/auth`, `components/count` and `components/forms/form-phone-input` but they all failed with one way or the other. 

@blowery @aduth @gziolo Is there a known way to fix them? 

One thing I've encounter was I think we were cleaning up DOM but the components were still trying access `window`. Some async weirdness.

The other was: `this.translate` or any `this.numberFormat` was undefined, I think this was due to `this` being the wrong context, not just mixins being skipped.

**Comment by gziolo** [comment]
@umurkontaci Thanks for working on that. I marked them on the list and I would skip them now, and get back to them once we migrate easier bits :)

**Comment by blowery** [comment]
Gotta be careful with those commit messages. :smile:

**Comment by gziolo** [comment]
@umurkontaci Do you plan to work on removing `client/auth/Makefile` this week or should someone else take care of it?

**Comment by gziolo** [comment]
> @umurkontaci Do you plan to work on removing client/auth/Makefile this week or should someone else take care of it?

Forget it, I was able to move it myself, you can help with review :)

**Comment by gziolo** [comment]
Done 🎆

**Comment by aduth** [comment]
Woohoo! 🎉  But to avoid premature celebration, there's still three remaining Makefiles that I believe should be removed:

- https://github.com/Automattic/wp-calypso/blob/master/client/lib/auth-code-request-store/Makefile
- https://github.com/Automattic/wp-calypso/blob/master/client/components/button-group/makefile
- https://github.com/Automattic/wp-calypso/blob/master/client/components/feature-example/makefile

The first looks to have been migrated already, and should probably be simply deleted.

**Comment by gziolo** [comment]
@aduth: 2 of them are removed with https://github.com/Automattic/wp-calypso/pull/4596 :)
I missed lowercase :D
