### ISSUE TITLE
Checkout: Update support section in generic Thank You page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#3943]
In some very rare cases we have to display a generic `Thank You` page. This happens when the API failed to return a receipt and the corresponding list of purchases. However we shouldn't probably display a placeholder for the support section when that happens:

![screenshot](https://cloud.githubusercontent.com/assets/594356/13667225/ad9304f0-e6b5-11e5-99cb-761c9b1cf8be.png)

@breezyskies, @mikeshelton1503, what do you think? It looks like we have three options :
1. Hide the support section entirely
2. Display (force) the WordPress.com version of the support section instead of the placeholder
3. Wait until @peterbutler has fixed the API and retire this generic page :)

Note this issue should probably be addressed at the same time than https://github.com/Automattic/wp-calypso/issues/3932.

**Comment by breezyskies** [comment]
> Wait until @peterbutler has fixed the API and retire this generic page :)

I think we should keep the generic page as a fallback regardless of the API fixes. It's a good fallback for other scenarios that may be outside our control (or knowledge) -- like a new product being added. 

Between options #1 and #2, I think forcing the WordPress.com support section is probably the way to go. It's possible that we're sending them to the wrong support, but then they can get directed to the right place (and this should be for minimal cases). They just paid us money (and in some cases, something possibly went wrong), so I wouldn't want to leave them with no hint of support options.

**Comment by fabianapsimoes** [comment]
> Display (force) the WordPress.com version of the support section instead of the placeholder

We had a similar discussion when working on the support section for other Thank You pages (https://github.com/Automattic/wp-calypso/pull/3755#issuecomment-193309987). In the end, we decided to use placeholders since the support URL can change depending on either we're dealing with a Jetpack prodcut or not. We should probably remain consistent in terms of that behavior.
