### ISSUE TITLE
Classic Editor: show opt-in dialog for all users who can opt-in

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#39445]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. If you're not already in the Block editor, you should be prompted to go there. Do it.
3. Now use the "three dots" in the upper right to switch to Classic. Many users seem to want to write with something less intrusive / distracting, then add blocks afterward.
4. Type up a few paragraphs. Try to switch back to Blocks. Can you? 

#### What I expected
To find a way to switch back to the Block Editor

#### What happened instead
There aren't any options on the screen.  I did find if I save the post, and exit, when I open it again i'm offered the option to move to Blocks. However, then all of my line breaks are stripped.

#### Browser / OS version
Chrome (Current) on Mac 10.14.16

#### Screenshot / Video
https://cloudup.com/cvgp6Z21mqU

#### Context / Source
https://en.forums.wordpress.com/topic/switch-from-classic-to-block-editor-2/

**Comment by millerf** [comment]
@supernovia What would be the best way to add this feature? I haven't been able to switch back to block... I had to remove my local storage and re-log to be asked to "try the new block editor".

Where should we add the functionality? In the "post settings" sidebar, in the "header", next to "Publish"? How much emphasis do you want to give this feature...

I think we would need some help from the UX department...

**Comment by millerf** [comment]
We also might have to add a `EditorGutenbergOptOutDialog` to retain as many users as possible on Gutenberg...

**Comment by supernovia** [comment]
So @millerf sorry I didn't see your notification earlier. It's quite a big design decision, but we've been using a tabbed editor for the better part of a decade, so maybe mimicking that somehow might work.

I'm gathering (just anecdotally) that most people who switch between classic and tabbed fit one of a few molds:

- They prefer typing all their paragraphs with minimal formatting and minimal distraction, just to do a mind dump of sorts, then going back in to add blocks and headings and what not later.

- They are actually running into bugs with the block editor, like one we recently fixed where too many backspaces would delete the whole paragraph.

- Or, there are some cases where themes require the classic editor to work right with certain things (I just saw this with Orvis's wide images today.).

**Comment by millerf** [comment]
@supernovia ,

So if I understand it well, the idea is to let the user free to switch between both editors. Each of them having their own pros and cons.

You do think a tab navigation is the way to go? Can anyone at @Automattic/team-calypso add some thoughts, as there might be some big changes ahead...

**Comment by supernovia** [comment]
Hi @millerf , just an idea on that. Maybe someone will have a better idea. It's just a convention people are used to for switching.

I've been sick but I came in to note we've got another case of someone wanting to switch to blocks again. Noting here in case I can get more feedback from them :D
https://en.forums.wordpress.com/topic/how-do-i-switch-back-to-the-block-editor/

**Comment by millerf** [comment]
@supernovia I looked a bit deeper into it.

There is actually a nice way and easy way to do this.

Basically, this 'OptIn' option:

<img width="395" alt="Screenshot 2020-03-05 at 21 09 17" src="https://user-images.githubusercontent.com/790558/76021565-c9113c00-5f25-11ea-8ad1-f522cde4f68b.png">


Is hidden once the editor is "forced" back into classic mode. 
Basically, removing [this line](https://github.com/Automattic/wp-calypso/blob/master/client/state/selectors/is-gutenberg-opt-in-enabled.js#L14) would allow the `OptIn` to be available all the time:

I am not sure this is the best, as it is still hidden in the side menu, but at least it would be available without having to reload the page, which might be what happened to the person who has written this 👆post

**Comment by millerf** [comment]
Also hope you feel better! Take care! Health is the most important thing we might have :)

**Comment by supernovia** [comment]
Ah. @mmtr what are your thoughts on this? We have some people who like to switch between editors.

**Comment by mmtr** [comment]
Yeah, I don't know if it's intentionally hidden or if it's a bug caused by the cached state, but it makes sense to always display the opt-in dialog as long as the user can actually opt in.

**Comment by lancewillett** [comment]
Work-in-progress here: https://github.com/Automattic/wp-calypso/pull/39965
