### ISSUE TITLE
Social Login: Can't connect Google in Me > Security > Social Login settings

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#39459]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/security/social-login
2. Select "Connect" next to Google, to connect a Google account to your existing WordPress.com account.
3. Login/select your Google account in the pop-up window that appears.

#### What I expected

I expected my Google account to be linked to my existing WordPress.com account.

#### What happened instead

The window closed but nothing changed in the Social Login settings; the Google account was not connected. (Refreshing the page does not show a connected Google account. There are no visible errors in the console/network requests.)

This prevents me from linking a Google account to a WordPress.com account using a different email address — my only option is to use the same email address for my WordPress.com account and link them using the Google login flow.

#### Browser / OS version

Chrome 79.0.3945.130 / macOS 10.15.3

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment]
@lsl Does this need a fix similar to the one in https://github.com/Automattic/wp-calypso/pull/39291?

**Comment by kriskarkoski** [comment]
Tested and confirmed this is still an issue.

**Comment by mdrockwell** [comment]
User ran into this issue earlier today: 2804941-zen

**Comment by rachelmcr** [comment]
@lancewillett I was just reminded about this open issue by a teammate who tried to connect a Google account and couldn't. We don't have many reports from end users, but it's really broken; can you help me decide if it needs to be prioritized and, if so, who might be able to help with a fix?
