### ISSUE TITLE
composite checkout error handler should record event for unknown errors

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#39469]
https://github.com/Automattic/wp-calypso/blob/bb9a9466e35bffffbd51df566679aa10fac2d4f1/client/my-sites/checkout/checkout/composite-checkout.js#L684

This should record something like `calypso_checkout_composite_unknown_error` rather than swallowing errors we didn't anticipate.

**Comment by sirbrillig** [comment]
Good idea. Currently there's a very small number of events but as they grow it'd be all too easy to end up there and we'd never know.
