### ISSUE TITLE
People: invites should use site's custom domain if set

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3947]
#### Steps to reproduce
1. Invite a user to a site with a custom domain. For example, the base site is example.wordpress.com and the primary URL is set to example.com
2. See that the email invitation uses the base site (example.wordpress.com) as the link to the site, instead of the primary URL (example.com)
![custom-domain-not-used](https://cloud.githubusercontent.com/assets/11487924/13674878/3718b084-e6ad-11e5-96f0-20302696a3d1.png)
3. When accepting the invitation, the base URL is also shown:
![no-custom-domain-on-accept-page](https://cloud.githubusercontent.com/assets/11487924/13674982/991b5868-e6ad-11e5-8f72-feaff06a7a75.png)
4. The 'successfully added' email also links to the incorrect base site instead of the main site URL:
![success-email](https://cloud.githubusercontent.com/assets/11487924/13675278/d9c6bd0c-e6ae-11e5-9f4f-164d5414d19d.png)

Overall the URL is shown incorrectly in 3 places:
1. the invite email
2. the acceptance page
3. the success email

#### I expected
I expected the site address (as show in wordpress.com/settings/general/$site) to be used instead.
![site-address](https://cloud.githubusercontent.com/assets/11487924/13675132/36138f8c-e6ae-11e5-9981-2d55ab13dc75.png)

**Comment by ebinnion** [comment]
Fixed in r132678-wpcom.
