### ISSUE TITLE
Reader: deleted list is stuck at loading state

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#3949]
**Steps to reproduce:**

1. create a List
2. delete this List
3. visit link that still exists, but it's stuck at loading state

![screenshot 2016-03-10 07 51 30](https://cloud.githubusercontent.com/assets/4924246/13675097/ebd8dcb0-e694-11e5-8bb3-cd8c387c51dd.png)

Example deleted List: https://wordpress.com/read/list/jancavan/b

The loading state appears for both the creator and follower of this List. 

This should show a 404 page instead or "This List no longer exists" message.

/cc @blowery @bluefuton

**Comment by blowery** [comment]
Fixed by #4756
