### ISSUE TITLE
On a free plan, domain price sometimes shown as "Free with your plan"

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#39500]
#### Steps to reproduce
1. Log in to an account that is on a Free plan
2. Go to Add domain page at  `/domains/add/{SITE_SLUG}`
3. You will see that the domain price for the initial suggestions says `First year included with paid plans`

<img width="1492" alt="Screenshot 2020-02-18 at 12 49 03 PM" src="https://user-images.githubusercontent.com/1269602/74712945-8a089880-524d-11ea-80bc-161ac3200f29.png">

4. Now navigate to /plans page, add a plan to cart and abandon cart. Head to Add domain page again at `/domains/add/{SITE_SLUG}`

#### What I expected

Domain product prices to still say that first year is free with a paid plan

#### What happened instead

The price message now says `First year free with your plan`. This isn't right because I'm still on the Free plan.

<img width="1515" alt="Screenshot 2020-02-18 at 12 49 48 PM" src="https://user-images.githubusercontent.com/1269602/74713144-ea97d580-524d-11ea-8700-306d31f7407b.png">

**After typing a search query**

<img width="1554" alt="Screenshot 2020-02-18 at 12 51 35 PM" src="https://user-images.githubusercontent.com/1269602/74713177-07340d80-524e-11ea-8195-810523e45bef.png">

**Comment by klimeryk** [comment]
This was on purpose - the logic takes into account the paid plan you have in the shopping cart. If you buy the domain with the current state of the shopping cart, it _will_ be free.

I understand it's a bit confusing, but that's partially because how the shopping cart contents are not shown during domain search.

Have you heard of any reports of this causing user confusion?

**Comment by niranjan-uma-shankar** [comment]
Ah okay. I am not basing this on any user tickets, just something that I noticed and thought might be a bug. I'll close the bug then if it's an intentional design, thanks.
