### ISSUE TITLE
People: follower invite email should include 'trouble clicking' link at the bottom

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3952]
#### Steps to reproduce
1. Send an invite to a user as a follower
2. Open the invite email and see that there is no 'trouble clicking' link to use in case the button doesn't work:

![follower-email-no-link](https://cloud.githubusercontent.com/assets/11487924/13676249/060f4a10-e6b3-11e5-8416-51ce73f606e2.png)

#### What I expected
There should be a plain link included, similar to the other invitation emails:
![trouble-clicking-link](https://cloud.githubusercontent.com/assets/11487924/13676288/331e7576-e6b3-11e5-87fe-fd299999f493.png)

**Comment by ebinnion** [comment]
Fixed in r132690-wpcom.
