### ISSUE TITLE
My Plan backup checklist item appears to be infinitely loading

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/wp-calypso#39529]
When setting up a new Jetpack plan for a site requiring VaultPress for backups, the Checklist within the My Plan page displays an item for Backup and Scan that appears to be stuck:

![Screen Shot 2020-02-19 at 09 58 00](https://user-images.githubusercontent.com/17905991/74792054-9816f180-52ff-11ea-829d-62f3e6599c5d.png)

#### Steps to reproduce
1. I created a test site and purchased a Jetpack Premium plan 
2. During the sign-up flow, I hid the progress modal (it was taking quite some time to load)
3. I manually installed and set up VaultPress for the site
4. I visited the My Plan page here: https://wordpress.com/plans/my-plan/blue-turtles.jurassic.ninja
5. The Backup and Scan item pictured above appears to be loading infinitely

#### What I expected

Once VaultPress is set up, this item should no longer appear in the checklist.

#### What happened instead

Even though backups are set up with VaultPress, the UI indicates they aren't and look to be stuck for the user.

**Comment by simison** [comment]
Cc @Automattic/jetpack-crew

**Comment by zinigor** [comment]
We have released 8.2.2 today, I'm trying to reproduce the same thing on a JN site, and I can't anymore. It could have been fixed by the release, can you please try testing again?

**Comment by chickenn00dle** [comment]
I just tested this again and it looks to have been fixed.

I'll go ahead and close this then.

Thanks @zinigor!
