### ISSUE TITLE
Posts: some images missing in post-list view

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#3954]
We made some changes to the post-normalizer (which is where we grab images for the post-list view) in #3481 that dramatically sped up the loading of images in post-list views (`/posts/:site`), but it had the impact that some posts are missing images when viewed in a list.

One example post with this issue is https://apeatling.wordpress.com/2015/10/21/cornish-cask-ale/ (@apeatling gave permission to link to it directly). You can grab it from the [rest API console](https://developer.wordpress.com/docs/api/console/) via:
`GET /v1.1/sites/apeatling.wordpress.com/posts/3312`

It turns out the image in this post is only in the content of the page (the post has no `featured_image` and no `attachments`), and the image tag in the post content has no dimension attributes. And with that change above we are no longer loading images without dimensions to find a suitable image to showcase in this view. We just trust the dimensions in the post. So the image without dimensions is not used in our post-list display.

This seems to be an issue with iOS image uploads... they're not getting attached correctly. So that's being pursued to fix it at the source. But we'll still have an issue when people add images by pasting a direct link into an `<img` tag in the html view. Those posts also come in without attachment info. Though that's a much edgier case. Also, fixing the iOS case would not retroactively fix posts affected by this.

Was chatting with @blowery about how to address this. Our idea is to keep the normalizer process as-is, but add back the process of loading images for posts that did not get a suitable image through featured_image, attachment data, or image tags with dimension attributes in the content. We should also probably do this _synchronously_ so we don't get in the way of known good images loading.

Creating this issue to keep the conversation public. Though I'm afk next week, so I probably can't grab this personally for a while.

**Comment by designsimply** [comment]
I believe this was happening before Feb 23 when #3481 was merged. My posts are made directly in desktop browsers on OSX and the images have dimensions but none are set as featured images. The one thing that all the posts with missing a highlight image seem to have in common is that the images are unattached (even though I uploaded images the same way for all posts so I am not sure why some are unattached). 

Here's a quick screencast showing that if you attach the image it fixes the problem in my case: [1m3s](https://cloudup.com/cQnvGMOwp7U)

Here a few example posts where I can see the problem happening: 

![screen shot 2016-03-26 at sat mar 26 8 57 48 am](https://cloud.githubusercontent.com/assets/1119271/14060724/b22cb11c-f332-11e5-87cc-1080beb9b912.png)
<sup>Seen at https://wordpress.com/posts/my/drafts/cute.wordpress.com using Chrome 49.0.2623.87 on Mac OS X 10.11.13</sup>

* https://wordpress.com/post/cute.wordpress.com/10005 (still a draft)
* https://cute.wordpress.com/2016/03/19/egg-shaped-rock/ <br> ```GET /v1.1/sites/cute.wordpress.com/posts/9049```
*  https://cute.wordpress.com/2016/03/19/tiny-sand-cliffs/  <br> ```GET /v1.1/sites/cute.wordpress.com/posts/9051```

**Comment by designsimply** [comment]
Aside: how does it choose which image to highlight? I expected the highlight image to be the first image that appears in the post, but it seems random to me instead.

**Comment by blowery** [comment]
> Aside: how does it choose which image to highlight? I expected the highlight image to be the first image that appears in the post, but it seems random to me instead.

It's the first image we can determine dimensions for. We pull the dims from the img tags in the post, then fall back to trying to match the URL against post attachments. If we can't find it either place, we stop trying and don't consider it as a candidate.

I think.

**Comment by rralian** [comment]
> It's the first image we can determine dimensions for

Also, the dimensions need to meet certain criteria to be considered for the highlighted image, but it's a pretty minimal check at this point... just looking for a minimum of [72px by 72px](https://github.com/Automattic/wp-calypso/blob/master/client/lib/posts/utils.js#L148).

**Comment by lancewillett** [comment]
Looking at this one with fresh eyes: anything actionable? Are we still seeing missing images that are legitimately broken? I haven't seen that in a while.

Feel free to re-open if 1) actionable items still in this issue 2) you see a valid, repeatable bug.

**Comment by apeatling** [comment]
I have not noticed this lately.

**Comment by apeatling** [comment]
I take it back, this is still a problem.

**Comment by apeatling** [comment]
I am missing an image for my latest post, uploaded through the browser in calypso editor.

**Comment by rralian** [comment]
The example post is again missing attachment info, and we're not pulling the image dimensions from the content, even though we should have access to that now. I can recreate this bug in my test site, so I'll take another look.

**Comment by rralian** [comment]
We may want to merge #5577 ahead of tackling this, since this will need to be addressed in the post-normalizer.

**Comment by lancewillett** [comment]
Reviewing our top priority issues today, looks like this is still waiting on a code change? #5577 to merge?

**Comment by blowery** [comment]
#5577 has landed. 

Might want to alter the post content image loaded to use `waitForImagesToLoad` to actually load the images found in the content.

**Comment by lancewillett** [comment]
Let's re-open if this happens again now that recent changes have landed.
