### ISSUE TITLE
CoBlocks Masonry Gallery Block: Images are superimposed - not respecting gutter settings

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#39548]
#### Steps to reproduce
1. Starting at URL: https://revistavitrini.blog/guiadeservicos/restaurantes/ or https://revistavitrini.blog/guiadeservicos/auto-pecas/.

#### What I expected
They are using the CoBlocks Masonry block on lots of pages, like this one: https://revistavitrini.blog/guiadeservicos/auto-pecas/. As you resize the window on your browser, you shouldbe able to see the images aligned well and keeping the space (gutter) around them as set up in the block.

#### What happened instead
In some browser windows the images show superimposed on top of each other.

#### Screenshot / Video / Browser / OS version
→ What they see: 
![qqqqqq](https://user-images.githubusercontent.com/31009008/74863990-cbb44480-531c-11ea-9526-380afc2e0cf6.jpg)

User set up:
Windows 10 (64-bit), Chrome 80.0.3987.116, Screen resolution: 1920 x 1080, Browser size: 1920 x 969, JavaScript: Yes, Cookies: Yes

→ This is difficult to duplicate, but I was able to replicate it using a mobile browser, Chrome, on Android, Pixel 4 - Version 80.0.3987.99: https://d.pr/v/psz2kH/GcFpsBiFtR
→ Chrome laptop testing (does not show the behavior): https://d.pr/v/JMW0Jh/IPTgtCPcHV

#### Context / Source
#painpoint #user-report

User report here #2698287-zen

**Comment by p-jackson** [comment]
Was able to reproduce using the responsive dev tools
https://d.pr/v/TQhVEH

If I resize just right (around 0:03 in the above video) then there isn't enough spacing beteween images. But then another little nudge and it will resize correctly.

**Comment by p-jackson** [comment]
I've reproduced this on a jurassic.ninja/ site with CoBlocks v1.20.1 and versions going all the way back to v1.11.0 when the masonry block was introduced.

So this is a CoBlocks bug and not something to do with how we're integrating it into WordPress.com. I'll create an issue in the CoBlocks repo.

**Comment by kriskarkoski** [comment]
Closing in favor of the CoBlocks issue linked above.
