### ISSUE TITLE
Tracks Events for Change Layout Button in Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39550]
It would be helpful to have a Tracks Events on our Change Layout Button in the Editor.  The button highlighted in green in the following screenshot.

![image](https://user-images.githubusercontent.com/545779/74867742-d4a41680-531a-11ea-8b22-d5ebbef083c9.png)

**Additional related request and question:**

Are there any edge cases where this button is not present for people who have access to the layout selector?

cc @boonerang @iamtakashi @alaczek

**Comment by marekhrabe** [comment]
I don't know where we show or hide it but we can definitely add the tracking for selector reopening.

**Comment by obenland** [comment]
This might be handling that? 
https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/sidebar-modal-opener.js
