### ISSUE TITLE
People: should not be able to accept using another user's invitation

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3956]
#### Steps to reproduce
1. Send out an invitation from your site to `user1` as any role (admin, editor, author, contrib, follower)
2. Find the email invitation for `user1` and copy the invitation link to your clipboard
3. Make sure you are signed out of WordPress.com
4. Enter the link in your browser and see this:
![different-user-flow-1](https://cloud.githubusercontent.com/assets/11487924/13677720/2f0c0bbe-e6b9-11e5-9b6f-e2d792e661a7.png)
5. Choose the option to log in
6. Instead of signing in as `user1`, sign in as a different user, `user2` instead
![different-user-flow-3](https://cloud.githubusercontent.com/assets/11487924/13677746/492b8cd6-e6b9-11e5-80af-41db8b888b97.png)

7. See this:
![different-user-flow-4](https://cloud.githubusercontent.com/assets/11487924/13677756/4d9ad254-e6b9-11e5-9d6e-14b6909a77fa.png)
8. Click 'Join' and see that you were added to the site as `user2`
![different-user-flow-5](https://cloud.githubusercontent.com/assets/11487924/13677765/60d8d35c-e6b9-11e5-97dc-649a14062287.png)
9. Check your site settings, and see that `user2` was indeed added as a user to the site

#### What I expected
When I invite someone to my site, I expect only that user to be able to accept the invitation. Any other user should not be able to accept the invitation, even as a follower. Here's how the flow might go:
1. I get an email invitation to join a site
2. I click on the invitation.
3. If I am not logged in as the user to whom the invitation is addressed, I should be be able to accept it. I should only be able to accept the invite when I am logged in as the user to whom the invitation is sent.

**Scenario I: I am not logged in when clicking the invitation link**
In this case, we can invite the user to log in. Two things can happen then:
Case 1: The user logs in with the same user who was invited. They are shown the 'join' screen.
Case 2: The user logs in with a different user than the one who was invited. In that case, we show them an error screen and invite them to log in as the correct user instead.

**Scenario II: I am logged in**
Case 1: The user is logged in as the invited user. They are shown the 'join' screen.
Case 2: The user is logged in with a different user than the one that was invited. We show them an error screen and invite them to log in as the correct user instead.

**Comment by beaulebens** [comment]
I believe this is actually by design. It's to allow for the (pretty common, we believe) situation as follows:

- user1 sends and invitation to user2
- user2 receives the invitation, but is no longer using the user2 account (or the email address the invitation was sent to, or whatever)
- user2 logs in under user3, and accepts the invitation

This does technically mean that an invitation can be accepted by "anyone", but without that flexibility, it means that when the invitation is sent, it's strictly dictating the account that can join, vs inviting a person, and then letting them connect under whatever account they prefer/actually use.

**Comment by v18** [comment]
Closing this issue as this is expected behaviour, and allows the users accepting the invitation to better fine-tune how they are interacting with a site.
