### ISSUE TITLE
Migration: Back button unresponsive on Business plan screen

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39574]
When I reach the Business plan screen during the WP Migration flow, the back button in the header is unresponsive.

![image](https://user-images.githubusercontent.com/448298/74971446-1e116600-53ee-11ea-87a1-aba0fc569659.png)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/import/{ site } using a site that doesn't have the Business plan.
2. Enable migration feature flag with the `?flags=tools/migrate`.
3. Move through the flow by entering a Jetpack-connected site.
4. When you reach the Business plan explanation, click `Back` in the header.

#### What I expected
To go back to the previous screen.

#### What happened instead
Nothing.

#### Browser / OS version
Chrome 80.0.3987.106 / Mac OS

**Comment by mattsherman** [comment]
Approved.
