### ISSUE TITLE
Migration: Input screen on mobile is unusable

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39577]
On mobile viewport, having the side by side layout for URL input makes the input element too small to be usable.

<img width="421" alt="Screen Shot 2020-02-20 at 2 07 05 PM" src="https://user-images.githubusercontent.com/448298/74975044-55831100-53f4-11ea-9e87-617d9d517143.png">

For mobile sizes can we hide that layout just on the URL input? Then switch the side by side layout once the site is polled and the user is moved to the next step.

We lose the reference to help visualize importing from site to site, but it makes the input usable. Something like this:

<img width="406" alt="Screen Shot 2020-02-20 at 3 19 19 PM" src="https://user-images.githubusercontent.com/448298/74975204-b1e63080-53f4-11ea-8f3e-a562212e2742.png">

**Comment by andfinally** [comment]
Tracking this in https://github.com/Automattic/wp-calypso/pull/39757.
