### ISSUE TITLE
Migration: Site icon missing after entering URL

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39581]
After I enter the URL, if the site does not have a favicon set it's just blank. Once I continue to the next step the empty site icon appears. Without it on the first screen, it looks like something is broken.

<img width="744" alt="Screen Shot 2020-02-20 at 3 52 06 PM" src="https://user-images.githubusercontent.com/448298/74977601-02f82380-53f9-11ea-94fa-7a0e338caf9b.png">

<img width="747" alt="Screen Shot 2020-02-20 at 3 52 12 PM" src="https://user-images.githubusercontent.com/448298/74977608-068baa80-53f9-11ea-9681-7a43e0af8283.png">

**Comment by bisko** [comment]
Tracking an API change under D39540-code

**Comment by bisko** [comment]
Second part of changes in D39593-code
