### ISSUE TITLE
Plugins: Make install plugin button active only when its included in the user's plan

### ISSUE THREAD

**Issue by lcollette** [Automattic/wp-calypso#39585]
An alternative solution for #39408.

**Current:**

When a customer tries to upload a plugin, they're met with a confusing message about needing to launch their site first. This doesn't make sense in the context of uploading a plugin. 

![Screen Shot 2020-02-20 at 4 33 33 PM](https://user-images.githubusercontent.com/181733/74993133-f1b21580-53fe-11ea-80e2-e49136adba7c.png)
 
**Proposed:**

We can avoid presenting that message altogether if we disable the button, making it active only when the user has that functionality available to them. 

<img width="1434" alt="Screen Shot 2020-02-20 at 4 28 14 PM" src="https://user-images.githubusercontent.com/181733/74993169-0db5b700-53ff-11ea-9dd8-bf42d6e1536d.png">

Related #39527

**Comment by mmtr** [comment]
Wouldn't this leave users stuck when they want to upload a plugin since they don't know that they need to make their site public in order to enable the button?

**Comment by lcollette** [comment]
>Wouldn't this leave users stuck when they want to upload a plugin since they won't know that they need to make their site public in order to enable the button?

We can improve the messaging to make that clearer, though we do have a banner at the top of the screen that calls out the need to upgrade to upload plugins.

**Comment by mmtr** [comment]
> we do have a banner at the top of the screen that calls out the need to upgrade to upload plugins.

We can certainly do that, either by adding more banners at the top or changing the messaging of the current one.

Note that we currently have all the requirements centralized in the [eligibility warnings](https://github.com/Automattic/wp-calypso/blob/b2e2caa9f181c188e0b3f8041296c36251e661b9/client/blocks/eligibility-warnings/hold-list.tsx#L21-L162) we display when the user initiates a transfer to Atomic. If we disable the "Upload plugin" button which is what triggers that transfer, we'd need to display all those requirements at the top along with the required plan message.

**Comment by kwight** [comment]
@lcollette Can we close this since we've merged #39527 ?

**Comment by lcollette** [comment]
@kwight No, because I still feel this is a better experience and would like to explore more. 

>Note that we currently have all the requirements centralized in the eligibility warnings we display when the user initiates a transfer to Atomic. If we disable the "Upload plugin" button which is what triggers that transfer, we'd need to display all those requirements at the top along with the required plan message.

I think this is more of a design challenge to solve. In the current instance, yes, the upload button does trigger the transfer but to the user, this is unexpected. We can improve how we communicate premium upgrades to our customers.

**Comment by davemart-in** [comment]
Moving this to the Manage design board for them to continue exploring ideas.

**Comment by cpapazoglou** [comment]
I am closing this, cause since then a user just needs to upgrade to a business plan
<img width="1599" alt="SS 2022-01-05 at 20 19 22" src="https://user-images.githubusercontent.com/12430020/148268419-c5abf12d-f4a5-4f01-ba0f-29c11e8f442b.png">

Please reopen if I am missing something.
