### ISSUE TITLE
Migration: Fix up styling of import failed screen

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39582]
The import failed screen needs a bit of design love.

<img src="https://user-images.githubusercontent.com/1647564/74946744-ae9d7580-53f1-11ea-89af-7cb267010941.png"/>

Some thoughts:

* "There was an error with your import" is mostly unnecessary as that's implied with "Import failed" heading above it.
* We could combine those two sentences into one, something like "There was an error starting the import." or "There was an error { verb-ified error message }." (yeah... verb-ified!)
* Rephrase the contact us sentence and move it above the button to keep all the messaging together and consistent.

<img width="648" alt="Screen Shot 2020-02-20 at 4 10 25 PM" src="https://user-images.githubusercontent.com/448298/74978992-b235fa00-53fb-11ea-8ff6-04d7b860c547.png">

**Comment by danhauk** [comment]
Just thought of something. There's no use asking someone to try again if we can be reasonably sure the error will happen again. It will only cause frustration. In that case, can we make the primary action contacting us?

<img width="541" alt="Screen Shot 2020-02-20 at 4 14 37 PM" src="https://user-images.githubusercontent.com/448298/74979203-38524080-53fc-11ea-9ddf-f39f6970992d.png">

**Comment by bisko** [comment]
> Just thought of something. There's no use asking someone to try again if we can be reasonably sure the error will happen again. It will only cause frustration. In that case, can we make the primary action contacting us?

@danhauk I don't think this is a good option to implement right now. There are few cases where retrying is a good option and we'll just tell them to retry it anyway. 

Another issue is that we don't save the error in a very accessible way and I don't think at the moment we can show a more granular message than a generic "import failed" message. 

Updated it to be similar to your above suggestion, but with added a bit more space between things:

![image](https://user-images.githubusercontent.com/184938/75564920-b8f4ea80-5a55-11ea-8428-79bb385e24db.png)
