### ISSUE TITLE
Migration: Confirmation modal needs a heading

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#39580]
The confirmation modal that appears before kicking off the migration doesn't have a proper heading. A heading allows users to quickly understand what this modal is asking.

<img width="590" alt="Screen Shot 2020-02-20 at 2 21 11 PM" src="https://user-images.githubusercontent.com/448298/74977009-da235e80-53f7-11ea-8d1c-3106bbf5bb82.png">

Proposed design below. We can remove the "You can return the site to its current state..." copy if that's not actually true. The intent there is to help ease their mind.

<img width="505" alt="Screen Shot 2020-02-20 at 3 43 08 PM" src="https://user-images.githubusercontent.com/448298/74977078-05a64900-53f8-11ea-99e4-25df976f2580.png">

@obi2020 I'd love to get a quick look at this if you have the bandwidth. My main concern is that seeing the word "overwrite" is scary and will prevent people from moving forward. The site will be overwritten, but most likely the site they are overwriting will be empty anyway. But just seeing that could cause some concern whether it's ok to proceed.

**Comment by obi2020** [comment]
I don't mind 'overwrite' so much, except that it might contradict the sentence that says a restoration is possible. I think, technically, overwrite means to destroy. What about 'replace'?

And at the risk of making the model too long is there a short something we can say about how to restore? Just a hint we can give - something like go do [Navigation label] to restore you're old site?
