### ISSUE TITLE
Gutenboarding: RTL Support

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#39592]
**Update: This issue may no longer be relevant due to design changes.**

## What needs to be done?
Only 2 things needs to be done (up til the page selection stage):
- <strike>Flip arrow icon on back button on header.</strike> (Update: Now removed in https://github.com/Automattic/wp-calypso/pull/38376 to be possibily reintroduced later https://github.com/Automattic/wp-calypso/issues/39933.)
- Flip arrow icon on continue button on acquire intent page.

## What are the possible challenges?
- RTL language set in route doesn't load RTL stylesheet (only in development mode). Set `rtl: false` in `development.json` to see RTL stylesheet being loaded.
- <strike>RTLCSS may not be working.</strike> https://github.com/Automattic/wp-calypso/issues/39957 (Update: RTLCSS is working.)
- Do we need `isRTL` in `react-i18n`?

**Comment by sirreal** [comment]
I've just realized this is probably related to server side bootstrapping:

https://github.com/Automattic/wp-calypso/blob/8332c098cc5dbcf5c1cb164240a4822fba8d7605/config/development.json#L11

Changing this in development will likely fix things. For users with RTL locale, we do see [RTL when bootstrapping happens](https://wpcalypso.wordpress.com/log-in/ar):

![Screen Shot 2020-02-21 at 12 50 56](https://user-images.githubusercontent.com/841763/75032420-d865a380-54a8-11ea-82dc-c9b5ec57de13.png)

However, we should be able to render in an [LTR language](https://wpcalypso.wordpress.com/log-in/es) as well, but we can't:

 
![Screen Shot 2020-02-21 at 12 51 47](https://user-images.githubusercontent.com/841763/75032460-f3d0ae80-54a8-11ea-897f-9d17cc9c9896.png)

It's a good idea to investigate log-in, which handles this correctly:

https://wpcalypso.wordpress.com/log-in/es
https://wpcalypso.wordpress.com/log-in/ar

**Comment by yansern** [comment]
Flipping an arrow button RTLCSS-style can be done this way.

```css
.dashicons-arrow-left-alt {
   transform: scaleX( 1 )/*rtl:scaleX( -1 )*/;
}
```

OR... flipping an arrow button in React-style can be done this way:

```jsx
import { useRtl } from 'i18n-calypso';
const isRtl = useRtl();
{ isRtl ? <Dashicon icon="arrow-right-alt" /> : <Dashicon icon="arrow-left-alt" /> }
```

However, `useRtl()` is coming from `i18n-calypso`, do we need an equivalent for `react-i18n`?

**Comment by sirreal** [comment]
> However, `useRtl()` is coming from `i18n-calypso`, do we need an equivalent for `react-i18n`?

Yes, we do. `isRTL` was recently added to `@wordpress/i18n` https://github.com/WordPress/gutenberg/pull/20298 and hasn't been published yet. If we have a use case, we can add it to `react-i18n` right now. We can use the implementation from https://github.com/WordPress/gutenberg/pull/20298 directly in `react-i18n` until we have a version of `@wordpress/i18n` that includes it.

You could open an issue for this, or file a PR directly.

**Comment by autumnfjeld** [comment]
Hi @sirreal or @yansern 😄  I'm following up on this issue, per the comment in the description:
> This issue may no longer be relevant due to design changes.

Should I get in touch with the designers working on this?

**Comment by ramonjd** [comment]
> RTL language set in route doesn't load RTL stylesheet (only in development mode). Set rtl: false in development.json to see RTL stylesheet being loaded.

I think it does now. See: https://wordpress.com/new/he and https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/components/window-locale-effect-manager/index.tsx#L37

**Comment by ramonjd** [comment]
> This issue may no longer be relevant due to design changes.

Looking at the current flow and rtl languages, I think we can close this issue now? 🤷

**Comment by lsl** [comment]
Feel free to reopen if there is more to do closing for now.
