### ISSUE TITLE
Hide FSE tag in showcase for users who do not have access to it

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39604]
Visit https://wordpress.com/themes/filter/full-site-editing in a logged-out incognito window.

![image](https://user-images.githubusercontent.com/545779/75053009-2c1ac180-5496-11ea-859c-30c09cc0fd55.png)

With FSE being in a test-mode-only this tag should be hidden for …
- logged-out users
- logged-in users without FSE sites.

cc @simison

**Comment by davipontesblog** [comment]
Confirmed this is still the case:

<img width="969" alt="Screen Shot on 2020-03-11 at 13-24-40" src="https://user-images.githubusercontent.com/31009008/76445402-bbcbd580-639b-11ea-8593-0cdc12756a0f.png">

moving to the Manage board for consideration.
