### ISSUE TITLE
Reader: make it more clear when a non-WP.com blog can be followed

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#39606]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage
2. Enter `fs.blog` and `https://fs.blog` as searches

#### What I expected
To see Farnam Street's blog show up as an option to follow

<img width="1392" alt="Screen Shot 2020-02-21 at 09 49 48" src="https://user-images.githubusercontent.com/66797/75054021-806e7300-548f-11ea-964a-29bf0d3640cc.png">

#### What happened instead

I get an option for another WP.com site, `https://wpcalypso.wordpress.com/read/feeds/96772916`

<img width="1392" alt="Screen Shot 2020-02-21 at 09 50 57" src="https://user-images.githubusercontent.com/66797/75054098-aa279a00-548f-11ea-80d8-05a525170c04.png">

#### Context / Source

Started from @m's list of blogs on WP Tavern: https://wptavern.com/publishing-break — and just started adding all the sites to my Reader.

**Comment by lancewillett** [comment]
Another miss in search: `https://avc.com/` doesn't show https://avc.com/ as an option.

<img width="911" alt="Screen Shot 2020-02-21 at 09 53 47" src="https://user-images.githubusercontent.com/66797/75054334-1d311080-5490-11ea-925d-c0e7bc5fc937.png">

**Comment by lancewillett** [comment]
OK. Updated the title and type of issue from bug to enhancement.

I see the results now in a tiny place just under the search. We should make it much more obvious — and put the blog at the actual URL searched as a "featured" blog. Otherwise it is too easy to miss it.

**Comment by annacmc** [comment]
I was able to repro the issue with the second site (https://avc.com/) but not the first one (https://fs.blog)

![image](https://user-images.githubusercontent.com/30754158/108778160-d8bbe180-75c9-11eb-86a9-44bd561f1c8d.png)

Removing the ` [Status] Stale` to keep this open as a feature request for making the initial follow blog link under the search bar more prominent.

**Comment by davemart-in** [comment]
We plan to do a complete reskin of the reader soon. Going to close this issue for now.
