### ISSUE TITLE
Reader: open follow site input if a URL is specified with ?follow=

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#3960]
If a URL is supplied to /following/edit with `?follow=`, we prepopulate it into the 'Follow Site' input.

Since this feature was built, we've hidden that input behind a button, which means it's not obvious to the user if the input has been prefilled or not. We should force the input open if a URL has been specified with `?follow=`.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/following/edit?follow=http://blowery.org/feed
2. Click 'Follow Site' button, and notice URL is prefilled

#### What I expected

Follow Site input visible and prefilled on load

#### What happened instead

Follow Site input hidden, but input still prefilled successfully

**Comment by blowery** [comment]
fixed with opml import / export
