### ISSUE TITLE
Recurring Payments: Showing wrong fee for Jetpack Pro site

### ISSUE THREAD

**Issue by htdat** [Automattic/wp-calypso#39619]
#### Steps to reproduce

I can not replicate this issue on my site because I do not a verified Stripe account. Instead, it's a report from our customers. 

1. They have a JP pro plan. (blog_id = 53387763)
2. SSP and visit https://wordpress.com/earn/payments/customer-site.org
3. It's showing `On your current plan, WordPress.com charges 10%.`

#### What I expected

It should be 2% per this doc https://en.support.wordpress.com/recurring-payments-button/#related-fees

#### What happened instead

Showing the wrong percent. 

#### Browser / OS version

N/A

#### Screenshot / Video

![Screen Shot on 2020-02-23 at 13:07:30](https://user-images.githubusercontent.com/10045087/75104579-b4879680-563d-11ea-8bdb-f302cf89fcc0.png)

#### Context / Source

Ticket: 2737204-zen
Blog_id = 53387763

**Comment by csonnek** [comment]
This popped off a 3d hold - not even sure who to ping or what to label this for someone to take a look. 24h hold on the ticket to wait for an update.

**Comment by jenhooks** [comment]
Closing in favor of https://autopay.wordpress.com/2020/02/26/recurring-payments-showing-wrong-fee-for-jetpack-pro-site/ [per this Slack convo.](https://a8c.slack.com/archives/C02BEP610/p1582748310056000)

**Comment by jenhooks** [comment]
Closed in favor of internal p2.

**Comment by artpi** [comment]
@eoigal Here is your issue :)
Internal P2 for reference:
pNPgK-4Z5-p2
