### ISSUE TITLE
Broken action in Marketing Tools for hiring an expert via Upwork

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#39639]
#### Steps to reproduce
1. Go to Tools, Marketing in your Calypso “My Sites” menu
2. Click “Find Your Expert” under the Upwork box

#### What I expected

To see a new tab open with possibly a landing page on the Upwork site that encourages me to create new job post, as we suggest here: https://en.support.wordpress.com/upwork/

<img width="1187" alt="Screen Shot 2020-02-24 at 10 57 07 AM" src="https://user-images.githubusercontent.com/66797/75177986-68e3f400-56f4-11ea-8456-198a45878a37.png">

URL of this screenshot is https://wordpress.com/marketing/tools/[example.wordpress.com]

#### What happened instead

New tab opens, but I end up in a 404 page still on Calypso, at `/experts/upwork?source=marketingtools`

<img width="1312" alt="upwork-calypso-404" src="https://user-images.githubusercontent.com/66797/75177870-3803bf00-56f4-11ea-8f70-07768d28a4c4.png">

#### Browser / OS version

Safari desktop latest, macOS Catalina

**Comment by creativecoder** [comment]
This appears to only be an issue for environments other than wordpress.com. I'd guess because there isn't a server-side redirect for `/experts/upwork?source=marketingtools` set up in those environments.

**Comment by lancewillett** [comment]
OK. Phew! That's a big relief.

I just re-tested in same browser, user account but with `https://wordpress.com` as the environment. Confirmed it works as expected.

Clicking "Find an Expert" takes me here: `https://www.upwork.com/ppc/wordpress/?promo_campaign=automattic&utm_campaign=automattic&utm_medium=partnership&utm_source=wp-marketingtools`

<img width="1392" alt="Screen Shot 2020-02-25 at 12 04 25" src="https://user-images.githubusercontent.com/66797/75278423-11fb1f00-57c7-11ea-9d76-2ec00fa28640.png">

We can close it, then.
