### ISSUE TITLE
Gutenboarding: save revision of the open post/page before launching the site

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39658]
#### Steps to reproduce
1. In Gutenboarding flows, create a site
2. Edit some content, and save it
3. Then edit that post little more...
4. Finally press "launch" — you should see "do you want to exit editor" prompt
    <img width="936" alt="image" src="https://user-images.githubusercontent.com/87168/75170689-27bf0480-5733-11ea-8186-21923e007096.png">

#### What I expected
- No prompt — just save the post as revision and continue to launching the site

**Comment by simison** [comment]
There's some similar mechanism in Jetpack plugin for premium block nudge's "upgrade" button:

https://github.com/Automattic/jetpack/blob/23cbea4e9cd8b8ff2dad532766d93535846c8ee0/extensions/shared/components/block-nudge/index.jsx#L40-L46

**Comment by razvanpapadopol** [comment]
I think this was fixed in https://github.com/Automattic/wp-calypso/pull/43116
Please re-open if I'm wrong.
