### ISSUE TITLE
Color schemes: Notification dot in Classic Blue color scheme wrong color

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#39660]
#### Steps to reproduce
1. Set your account to the Classic Blue color scheme
2. Wait for a new notification to come in
3. View the color of the notification dot that appears on the bell icon in Calypso

#### What I expected
For the notification dot to use the orange color that's the highlight color for Classic Blue

#### What happened instead
The notification dot appears pink instead. The exact color is `#f283aa`, the value assigned to `--studio-pink-20` in the Automattic Color Studio.

#### Browser / OS version
Originally reported by a user using Chrome on Android. I've replicated there as well as Firefox, Chrome and Safari on Mac OSX

#### Screenshot / Video
![Account_Settings_—_WordPress_com_-_Mozilla_Firefox](https://user-images.githubusercontent.com/11873759/75235882-a19fce00-57c5-11ea-92c0-9c08730ee20a.png)

![Account_Settings_—_WordPress_com_-_Mozilla_Firefox](https://user-images.githubusercontent.com/11873759/75235963-c2682380-57c5-11ea-95e9-9f103673c649.png)

#### Context / Source

Reported via [Twitter](https://twitter.com/theredshelf/status/1231332943492243462)

**Comment by Aurorum** [comment]
PR for this issue in #39746. :)
