### ISSUE TITLE
Avoid placeholders for the contact forms

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#39663]
> The placeholder for the contact form here in the Maywood layout could be seen as looking like it's broken in a different way […] in that it's not providing a preview of the final result.

![image](https://user-images.githubusercontent.com/545779/74182510-d2e69e80-4c08-11ea-8e45-d11197cad3ec.png)

_Originally posted by @ianstewart in https://github.com/Automattic/wp-calypso/issues/39343#issuecomment-584307208_

--------------

@marekhrabe added:

> I think we've hit the problem with the intro screen of the form block before. I believe it was dismissed for the user by setting an attribute on the block. That way they immediately saw real form fields in both preview and editor. Disadvantage being they are not guided to set their email and subject and block will use some default ones

> Edit: this is the attribute https://github.com/Automattic/jetpack/blob/026529c933acc84280214d91fb137941795ad004/extensions/blocks/contact-form/index.js#L86

------------

Let's look into how we avoid showing the "placeholder" for Contact form blocks.

**Comment by marekhrabe** [comment]
I think there are two ways to solve this:

- update all templates with contact forms (in all possible languages and mutations) to include the `hasFormSettingsSet:true` attribute
- add some code that will go over the template blocks recursively in page selector just before showing it in preview which will look for Contact Form blocks and update their `hasFormSettingsSet` attribute to be `true`

I'm leaning towards the latter as updating templates in bulk is always a very painful experience and secondly, we can keep the "initial state" visible for the user once they insert their template.

**Comment by getdave** [comment]
Before I read your comment I was thinking about the later.

ie:

> add some code that will go over the template blocks recursively in page selector just before showing it in preview which will look for Contact Form blocks and update their hasFormSettingsSet attribute to be true

I'm going to look at this.

**Comment by getdave** [comment]
@marekhrabe There is a draft PR up for this. Note that it is WIP. I'm aware of several flaws.

https://github.com/Automattic/wp-calypso/pull/39697

**Comment by obenland** [comment]
For my understanding, do we need to fix this programmatically because the form doesn't _actually_ have form settings?
