### ISSUE TITLE
Blog Posts Block does not support sticky posts

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/wp-calypso#39671]
#### Steps to reproduce
1. Create a new page, and add the Blog Posts Block
2. Customize block settings to your liking and publish page
3. Publish posts, ensuring that at least one set to sticky
4. Observe that the sticky post is not sticky in the Blog Posts Block

#### What I expected

Posts marked as Sticky appear above the other posts. 

#### What happened instead

 Posts are displayed in reverse chronological order.

<img width="975" alt="Screen Shot 2020-02-25 at 07 48 56" src="https://user-images.githubusercontent.com/39252765/75258198-54126980-57a3-11ea-85e4-d8db4dffd0c0.png">

**Comment by jonnyruzek** [comment]
Requested in 2741709-zen

**Comment by davipontesblog** [comment]
Reported here: https://github.com/Automattic/newspack-blocks/issues/292

I am closing this one in favor of the previously logged issue referenced above.
