### ISSUE TITLE
Gutenboarding: Page selector exit animation visual regression

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#39674]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenboarding
2. Reach Design Picker step and open Page Selector modal
3. Refresh the page or open https://wpcalypso.wordpress.com/gutenboarding/pages in another tab
4. Press _Back_ button

#### What I expected
- The exit animation to be smooth, similar to the enter animation.

#### What happened instead
- The white background of the page selector shrinks just before the animation starts, and the "Select the pages you'd like to include" heading's margin disappears.

#### Browser / OS version
Chrome 79 and Firefox 70 / MacOS Catalina

#### Screenshot / Video
https://cloudup.com/cJviFm34ZrU
- also reported for Firefox in https://github.com/Automattic/wp-calypso/pull/39336#pullrequestreview-363158021 and the behaviour can be better reproduced in Firefox without reloading the page. In Chrome the animation is too fast to notice something without reloading the page first.

**Comment by simison** [comment]
Closing for now since we've removed the step from the flow.
