### ISSUE TITLE
Customizer: Guided Tour in customizer is squished on mobile devices

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#39696]
#### Steps to reproduce
1. On a mobile device, starting at URL: https://wordpress.com/
2. Sign up for a new account & site.
3. Go to My Sites and open the customizer.

#### What I expected

I expect all elements in the customizer to be clearly legible on a mobile screen size.

#### What happened instead

The guided tour text was squished on the right side of the screen, and the full text was not visible. This is the text in that guided tour:

> Here you can control the design of your site. Change your site title, update the colors and fonts, and even add a header image. Explore widgets to find new features and content to add to your website.

#### Browser / OS version

Safari / iOS 13.3.1 on iPhone XS

#### Screenshot / Video

<img src="https://user-images.githubusercontent.com/8658164/75333010-4204f980-587d-11ea-8e17-27d306f6085e.PNG" width="50%">

#### Context / Source
Reported by @elibud, internal discussion in pbArwn-an-p2

**Comment by razvanpapadopol** [comment]
Working on a fix in D39533-code

**Comment by razvanpapadopol** [comment]
Fixed and deployed in r203558-wpcom
