### ISSUE TITLE
Posts: Scheduled post was published, got "stuck" in list

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#3969]
I've scheduled a bunch of posts in the past couple days. One of them got stuck in an odd state... It was published on schedule, but then showed up both in the "Published" and "Scheduled" areas.

In the "Scheduled" tab, it wasn't being included in the count (the count was 2, but there were 3 posts displayed), as well as saying its status was "Scheduled" for "3 hours ago". In the "Published" tab, it was correctly listed, but still with the erroneous "Scheduled" tag.

![screen shot 2016-03-10 at 4 01 17 pm](https://cloud.githubusercontent.com/assets/52152/13688942/fa0d7ac6-e6d9-11e5-86a9-ce4f28b74e2b.png)

The problem cleared up once I did a shift+reload, so looks like some of the state isn't getting properly updated after a scheduled post is posted?

**Comment by hoverduck** [comment]
14Apr16 Bug Scrub

I wasn't able to exactly reproduce this, but the symptom that I observed was that my scheduled post remained in the Scheduled tab for a few minutes after it was published.  I eventually clicked the Preview button to open the post in a new tab to verify it was actually published, and at that point it disappeared from the Scheduled tab, but didn't show up under Published until I refreshed the page.

My hunch is this is the same problem as #4330 (linked above), but I'll leave them both open for now.

**Comment by hoverduck** [comment]
26May16 Bug Scrub

This hasn't seen any activity in over a month, so I'm closing it.  #4330 is still open, though, which I believe is the same issue.

**Comment by codebykat** [comment]
It wasn't the same issue (in my case the post was published, the view was just stale), but I believe it'll be addressed by some of the work @aduth is doing toward more statefulness/consistency in post lists on the client side.

Also likely one of those things that's much more apparent if you have the API sandboxed.
