### ISSUE TITLE
CoBlocks Gallery: captions not clickable, can't open lightbox in mobile

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#39710]
#### Steps to reproduce
1. Add a CoBlocks gallery with some images, on a page/post on a Simple or AT site (any CoBlocks gallery will do, but the user had the Offset gallery)
2. Enable lightbox and captions in block settings
3. Add captions to the images
4. Save post/page

#### What I expected
To be able to click anywhere on a gallery image to open the lightbox on the published page/post, including the caption, and to be able to open the lightbox on mobile by tapping an image. 

#### What happened instead
The captions aren't clickable, and on mobile the caption area covers almost the whole image so you aren't able to tap to open the image either.

#user-report
18901856-hc

As a workaround for now, I directed the user to use a regular Gallery block, with the Link To set to Attachment Page so the carousel view opened up instead.

**Comment by simison** [comment]
cc @ramonjd

**Comment by p-jackson** [comment]
Just confirmed that this bug is still present in CoBlocks 1.21.1.

The caption has a large amount of padding, which is part of the problem. Even when you think you're not clicking the text you're still clicking that element.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/1500769/75490349-eb342700-5a18-11ea-9630-57b7585965f8.png">

**Comment by ramonjd** [comment]
> The caption has a large amount of padding, which is part of the problem. Even when you think you're not clicking the text you're still clicking that element.

Cool. We should probably file the issue with them.

**Comment by p-jackson** [comment]
Filed issue godaddy-wordpress/coblocks#1383, thanks @kcswong!

**Comment by roo2** [comment]
A fix is included in [coblocks 1.23.0](https://github.com/godaddy-wordpress/coblocks/releases/tag/1.23.0)

https://github.com/godaddy-wordpress/coblocks/pull/1407

**Comment by roo2** [comment]
Can confirm this is fixed in 1.23.0
