### ISSUE TITLE
Atomic: hide the Akismet privacy banner from the plugins screen

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#39739]
Atomic sites see this banner under the right conditions:

![image](https://user-images.githubusercontent.com/437258/75450763-aef8bc00-596f-11ea-95ff-07773af4fd44.png)

Could we incorporate any needed language into our dotcom terms of service / privacy policy so that customers could be opted in and we could programmatically hide this banner? 

It obscures and complicates the installed plugin screen UI, especially since we control Akismet.

**Comment by gwwar** [comment]
I'd prefer if we kept these separate. If it's particularly distracting we can attempt to show one admin notice at a time, but I defer to @jennyzhu for requirements

**Comment by lancewillett** [comment]
+1 to remove the Akismet notice.

**Comment by gwwar** [comment]
@lancewillett see also pbAPfg-h3-p2#comment-637 sounds like we should be able to do this soon.

**Comment by lcollette** [comment]
Assigning to @procifer. Thanks for looking!

**Comment by procifer** [comment]
Hot potato! Assigning to @stephdau who is preparing the fix for this.

**Comment by gwwar** [comment]
Closed by the Akismet team in the 4.1.5 plugin update 💖
