### ISSUE TITLE
Import/Export: redirect WP Admin export tool to Calypso for Simple sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#39747]
This change helps Simple sites avoid using `wp-admin/export.php` which isn't actively worked on.

We'd like to help customers and HEs both with this change — avoiding quirks such as Customizer revisions made by HEs in Super Admin added to XML exports with their author as the user (internal ref: p2EDhh-S7-p2).

Task: when a user is in WP Admin for a Simple site, and clicks "Export" in the menu under "Tools" — automatically redirect to `https://wordpress.com/export/`.

CC @bisko @Automattic/start-samus In case you can fit small small change in quickly.

CC @kriskarkoski

**Comment by bisko** [comment]
Tracking a possible fix under D40109-code

**Comment by lancewillett** [comment]
Fixed in r204106-wpcom props @bisko
