### ISSUE TITLE
Framework: Mixed Content Warnings in Firefox for Calypso

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3976]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Click "My Site"

#### What I expected

Firefox to not show mixed content warnings

#### What happened instead

Firefox displays mixed content warnings in URL bar instead of green padlock

#### Browser / OS version

Firefox 45.0 OSX 

#### Screenshot / Video

![mixed content firefox](https://cloud.githubusercontent.com/assets/128826/13695824/d996a194-e7ad-11e5-89a5-079d16689149.png)

**Comment by lancewillett** [comment]
I can't repeat this testing with same steps above, Firefox 46.0.1 on OS X 10.11.4. Green padlock on all Calypso URLs I tested, logged in.

**Comment by lancewillett** [comment]
If this comes up again in the future — please include output from JS console for the content errors, probably in Network tab or similar.
