### ISSUE TITLE
Layout template options missing in Edge for Mac

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#39778]
#### Steps to reproduce
1. Starting at URL: Any WordPress.com Simple site running one of the template-first themes, such as Barnsbury
2. Go to My Sites > Pages > Add New Page
3. Look for the templates down the left hand side

#### What I expected
To see multiple templates of each type, such as About, Services, Contact, Portfolio

#### What happened instead
There is only **one** layout template visible for each type, except for Home Pages, which shows five templates.

#### Browser / OS version
Edge 80.0.361.62
MacOS 10.14.6 

#### Screencast

https://cloudup.com/ct176srAdR1

#### Context / Source

No user issue, discovered while #dogfooding

**Comment by senff** [comment]
Not able to reproduce on my end:

![edge](https://user-images.githubusercontent.com/1710669/75588668-25b4b880-5a47-11ea-867f-2fe8fa3c507e.png)

Same specs:
Edge 80.0.361.62
MacOS 10.14.6

**Comment by obenland** [comment]
@kathrynwp What locale was set for the site?

**Comment by kathrynwp** [comment]
@obenland 

fr-Français

**Comment by obenland** [comment]
The new templates are missing because they're not translated yet. Progress on that can be followed on pbFcYn-1A-p2#comment-23

I was briefly confused because your screenshot shows English copy, but I think that's due to the French translations not actually containing translations.

**Comment by kathrynwp** [comment]
🤦‍♀ This explains a lot, I can't believe I missed that. Thanks and sorry, @obenland! I think this can be closed as it was a false alarm.

**Comment by obenland** [comment]
Absolutely no need to apologize! This is all pretty confusing and a lot to keep track of. I hope we'll have translations sorted out soon
