### ISSUE TITLE
Checkout: `/checkout/:site/:planType` does not work as an external url in production

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#3980]
#### Steps to reproduce
1. Go to https://wordpress.com/checkout/:site/business (with :site being a valid site slug of one or your sites) or https://wordpress.com/checkout/:site/premium
#### What I expected

I expect to land on the Checkout page for a business plan
#### What happened instead

I'm redirected to https://wordpress.com/sites
#### Browser / OS version

Assuming all browsers, production/staging environment.
#### Screenshot / Video

![checkout-business](https://cloud.githubusercontent.com/assets/230230/13702170/e5de2efc-e78c-11e5-82a9-aa52b8e1ac22.gif)
#### Workarounds

Do not use `/checkout/:site/:planType` for external links but `/plans/select/:planType/:site` instead.

**Comment by janm6k** [comment]
Going through old issues, closing ones that did not have any activity in long time.

Please feel free to reopen if applicable.
