### ISSUE TITLE
Blog Posts Block: category filter not working with "Load More Posts" button

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#39818]
#### Steps to reproduce
1. Create a new page
2. Add the Block Post Block and
3. Enable Show "More" Button
4. Specify a category to be displayed

#### What I expected

To see posts with only that category when I click "Load More Posts"

#### What happened instead

I see posts with other categories as well. 

Screenshots: https://d.pr/i/Yb5OEm and https://d.pr/i/QglfPO 

2753032-zd

**Comment by nielslange** [comment]
2762946-zd

**Comment by kristarella** [comment]
19227051-hc

- atomic site
- maisha theme

**Comment by davipontesblog** [comment]
I am closing this issue in favor of https://github.com/Automattic/newspack-blocks/issues/392.
