### ISSUE TITLE
Customer Home displays not secure connection when switching account language settings

### ISSUE THREAD

**Issue by StefZarb** [Automattic/wp-calypso#39810]
Switching the Interface Language to any non-EN language on the account settings makes Customer Home (https://wordpress.com/home/)  displaying a not secure connection, also when moving on other dashboard sections. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Change Interface Language to any non-EN language
3. Go to https://wordpress.com/home/ (Customer Home)
4. View browser URL info. 
5. Navigate other sections. 

#### What I expected

I expect to see a secure connection.

#### What happened instead

Connection is not secure. 

#### Browser / OS version

Firefox 73.0.1 (64-bit)
Chrome Version 80.0.3987.122

#### Screenshot / Video

https://d.pr/i/HtapVB

Console error: https://d.pr/i/ziV3iC

#### Context / Source

#painpoint. #user-report

**Comment by simison** [comment]
Due mixed content on the page: 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/87168/75804934-86b2f800-5d89-11ea-8367-658b0c2d0b7f.png">
