### ISSUE TITLE
FSE: fix incorrect taxonomy usage in MTS

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#39824]
This Issue tracks the problem outlined at `paYJgx-u6-p2`.

Fixes required:

* update Taxonomy on Master Template Site.
* update code to query correct taxonomy.

Apologies this is crypitc but for details you really need to see `paYJgx-u6-p2`.

## Update

There is now code to review at `D40095-code`

**Comment by obenland** [comment]
Fixed in D40095-code.
