### ISSUE TITLE
"Design a logo" link from "My home" goes to external service with no context

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#39820]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/home/(your-site)
2. Click "Design a logo"
3. You are taken to https://wp.me/logo-maker which redirects to https://looka.com/wordpress-looka/

#### What I expected

To be taken into a logo flow with clear expectations and steps, reassuring me that this will appear on my site in the way I expect

#### What happened instead

Taken to an external service with no "external link" icon, no context or barely any co-branding, no mechanism to get the logo back to my site, and the Looka service doesn't even offer the option to connect using my WordPress.com account - only Google/Facebook/Twitter.

#### Browser / OS version

macOS 10.15.3, Chrome 80

#### Screenshot / Video

The My Home dash, with the link in question highlighted:

<img width="965" alt="logo-link-to-external-site" src="https://user-images.githubusercontent.com/51896/75744709-f792db00-5cc9-11ea-9645-69300b317e11.png">

The Looka page that I am sent to:

<img width="842" alt="looka-no-context" src="https://user-images.githubusercontent.com/51896/75744719-024d7000-5cca-11ea-9b4b-1663875ddcf3.png">

**Comment by gwwar** [comment]
Should be closed by https://github.com/Automattic/wp-calypso/pull/39914
