### ISSUE TITLE
Unable to create new site

### ISSUE THREAD

**Issue by ChaosExAnima** [Automattic/wp-calypso#39852]
#### Steps to reproduce
1. I tried to create a site via https://wordpress.com/start/
2. Go through flow, picking domain and Professional plan.
3. Upon picking plan, get kicked back to https://wordpress.com/start/domains-with-preview with error `Please enter a site name.`.

#### What I expected
I could make a new site!

#### What happened instead
I was given a vague error that doesn't make sense to me.

#### Browser / OS version
Chrome 80.0.3987.122, macOS 10.15.3.

#### Screenshot / Video
Video here: https://d.pr/v/U4SH6m

#### Context / Source
Experimenting before doing a demo.

**Comment by gwwar** [comment]
Chatting with @ChaosExAnima 

Some other notes:
- Clicking on a paid domain in the domain step was triggering a site creation request. `https://public-api.wordpress.com/rest/v1.1/sites/new` This shouldn't happen normally. We proceed to the plan step instead.
- Response was returning `blog_name_required` suggesting the client request was malformed.
- User existed before and had multiple sites
- I was unable to reproduce even when setting A/B tests.

Active AB Tests: 
```
{"customerHomeAll_20200224":"control","sidebarUpsellNudgeUnification_20200221":"control","showCompositeCheckout_20200221":"composite","domainStepDesignUpdates_20200220":"control","domainStepCopyUpdates_20191121":"variantShowUpdates","pageBuilderMVP_20190419":"control"}
```

See also p1583273358009300-slack-dotcom for a video

**Comment by ramonjd** [comment]
I also tried my best to reproduce this error journey in [various signup flows](https://github.com/Automattic/wp-calypso/blob/8cb9bff/client/signup/config/flows-pure.js) with the signup state intact/fresh, and with all and no A/B test variants enabled. 

🤷‍♂ 

We can trigger the error by sending `''` as the value of [blog_name](https://github.com/Automattic/wp-calypso/blob/8cb9bff/client/lib/signup/step-actions.js#L189) to `sites/new`

<img width="826" alt="Screen Shot 2020-03-04 at 11 53 47 am" src="https://user-images.githubusercontent.com/6458278/75834057-0fc04280-5e0f-11ea-9580-afcaf78eb2c3.png">

If @ChaosExAnima or anyone else can reliably reproduce this we could engage in a little preemptive strike action and extend our fallbacks wherever we're setting the `blog_name` [request parameter in the client](https://github.com/Automattic/wp-calypso/blob/8cb9bff/client/lib/signup/step-actions.js#L189).

It would be great to capture the network request headers too if reproducible.

**Comment by ChaosExAnima** [comment]
I can still repro, so I will attempt to capture network logs. If there's a way for me to capture things via my sandbox as well, please let me know!

**Comment by ramonjd** [comment]
Thank a lot for capturing the data @ChaosExAnima 

This is highly weird. Was it reproducible in an incognito window as well? Just thinking there might be something strange caught in the `state.signup` store.

I'll do some more investigation today.

**Comment by ramonjd** [comment]
This boggles my mind.

In your request params `blog_name` has a value.

My request payload is identical and I cannot reproduce this on any browser.

<img width="660" alt="Screen Shot 2020-03-05 at 1 36 31 pm" src="https://user-images.githubusercontent.com/6458278/75942430-75cbc900-5ee6-11ea-93bc-9b9377ba03ab.png">

🤷‍♂

**Comment by lancewillett** [comment]
Weird one! Could it have been a temporary glitch? Server timeout, fatal error, etc. If you have the exact timestamp of the request, you could look in Grafana for any related errors at the same time.

My guess is an API error or server timeout.

**Comment by ChaosExAnima** [comment]
I can repro in incognito, though I'll have to try with a fake account as I've been using my account so far. If anyone can tell me how to grab the state from the backend please let me know, I can test with my sandbox :)

**Comment by ChaosExAnima** [comment]
> Weird one! Could it have been a temporary glitch? Server timeout, fatal error, etc. If you have the exact timestamp of the request, you could look in Kibana (logstash) for any related errors at the same time.
> 
> My guess is an API error or server timeout.

I've been able to repro over multiple days. I'll see about Kibana, good idea!

**Comment by lancewillett** [comment]
Hi @ChaosExAnima — would you mind re-testing with the current signup flow steps?

**Comment by ChaosExAnima** [comment]
@lancewillett - Just tried again and no dice. Sorry :/

**Comment by ramonjd** [comment]
Sorry, just trying to eliminate everything. 

Are you using a new account or the same account each time?

**Comment by ChaosExAnima** [comment]
@ramonjd - Seems to just be my account. New accounts work.

**Comment by lancewillett** [comment]
A true Chaos Wrangler, Echo is — good for stress-testing WordPress.com, though. 😸

**Comment by ChaosExAnima** [comment]
Closing this as I figured out what's going down! I've left a comment on  p1583273358009300-slack-dotcom with details, as it's not related to Calypso.
