### ISSUE TITLE
People: add more information on 'you are already member of this site' error page

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#3985]
#### Steps to reproduce
1. Send an admin invite to an email address not currently signed up to wpcom
2. Log in as a user who's already administrating the site, and then open the invitation link
3. See this:

![screen shot 2016-03-11 at 11 02 54 am](https://cloud.githubusercontent.com/assets/11487924/13707736/1106696e-e779-11e5-82c7-5470c005d4cf.png)
#### What I expected

That page could display some more information to help users make an informed decision. As starting point, here's what the page looks like when users are accepting an invitation:

![accept-invite-page](https://cloud.githubusercontent.com/assets/11487924/13707842/aa8d88ba-e779-11e5-9b80-903218f778f0.png)

That page includes this information
- the site title
- a link to the site URL
- the blog's site logo
- the name of person who invited you
- the gravatar of the person who invited you
- the name of the person accepting the invite
- the gravatar of the person accepting the invite
- the role the user is being invited to (and we should say which role they already have)

In addition to the "Switch Accounts" button, we could also include a button to return to the site. Something like "I'm all set - get me back to [Site Name]". This makes it obvious this current user can continue administrating the site.

**Comment by ebinnion** [comment]
The biggest issue with adding this information is that we don't return the invite at all unless it is valid for the current conditions. This means that we don't know the site name, URL, logo, etc.

For a logged in user who is already a member, we could probably get this information from the user's sites list. But, for logged out users and logged in followers, we currently don't have access to it.

In regards to the "I'm all set" button, we could do that. But, I'm not sure I see much value in it.

I'm going to go ahead and remove the milestone for this issue. I see some value in adding the extra information, but I don't think it's high priority. We can address it if it becomes an issue or in a bug scrub in the future.

**Comment by v18** [comment]
Sounds good about the milestone change. For future reference, this error message only shows up for users who are already logged in, so I think it makes sense to update it since we can get that information about them.

**Comment by designsimply** [comment]
Tested and confirmed using the following steps:

1. Go to https://wordpress.com/people/team/ and select a site where you are an administrator and there is at least one other administrator already present in People
1. Click the Invite User button
1. Add an email address not already used at WordPress.com in the first field
1. Select Administrator for the role
1. Click the Send Invitation button
1. Log out of WordPress.com
1. Log back in to WordPress.com as another administrator on the same blog
1. Click the link in the email from the invite that was just sent (while logged in as an admin on that blog)

<strong>Result:</strong> if you try to accept an invite sent to an email not already associated with a WordPress.com while logged in to an existing account, the resulting message is as follows:

> You are already a member of this site.
> Would you like to accept the invite with a different account?

<img width="1280" alt="screen shot 2016-05-12 at thu may 12 2 29 43 pm" src="https://cloud.githubusercontent.com/assets/1119271/15229706/7e7b5048-184f-11e6-9195-c129c9f4e8e6.png">
<sup>Tested using Firefox 46.0.1 on Mac OS X 10.11.4</sup>

@ebinnion, could it instead be updated to say the following?

> [logged_in_username] is already a member of [site_url].
> Either log out and create a new account to accept this invite or log in as a different user that is not already a member of the site.

Too long?

For reference, the invite email looks like this:

![screen shot 2016-05-12 at 14 18 06](https://cloud.githubusercontent.com/assets/1119271/15229671/5ac5b936-184f-11e6-83ce-98bb007cca33.png)

**Comment by ebinnion** [comment]
@designsimply – I don't see any issue with updating the wording. I'm not sure it's high priority right now, but could be useful. I'll go ahead and assign it to myself with low priority.

**Comment by lancewillett** [comment]
Bug scrub note: to move this ahead we just need a pull request with the updated wording to make the warning more clear.
