### ISSUE TITLE
Jetpack Search: Display new plans

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#39858]
All of this should get hidden behind a feature flag initially i guess.

There are a number of places the new plans need to get displayed:
- [x] https://wordpress.com/plans/gibrown.wpsandbox.me::main (both yearly and monthly). Copy from Jetpack Backups as a start. (Fixed by #39942)
- [ ] https://wordpress.com/plans/my-plan/gibrown.wpsandbox.me::main (In progress at #40382)
- [ ] wp.com sites need to also have plans working (but lower priority)
- [x] checkout page needs to work ala https://wordpress.com/checkout/gibrown.wpsandbox.me::test0/jetpack_backup_realtime
- [x] we need to be able to accept links from wp-admin into calypso to do a purchase also

I started some of the work on this in https://github.com/Automattic/wp-calypso/pull/39857

I suspect we should break this up into smaller issues. Maybe after creating a bunch of constants.

**Comment by jsnmoon** [comment]
`https://wordpress.com/plans/my-plan/example.com` currently doesn't display any information about Jetpack Single Products. Do we intend to add something here? @gibrown @keoshi

<img width="1063" alt="Screen Shot 2020-03-17 at 3 01 06 PM" src="https://user-images.githubusercontent.com/4044428/76901060-24192c00-6860-11ea-82bf-c8889de6e309.png">

**Comment by keoshi** [comment]
@jsnmoon It actually does show single products on a separate block:

![image](https://user-images.githubusercontent.com/390760/76902115-33fe3380-6893-11ea-8399-06fb83551095.png)

Seems to come from here:

https://github.com/Automattic/wp-calypso/blob/9af6717b3285be28536cd8da68773af733312611/client/my-sites/plans/current-plan/purchases-listing.jsx#L214

So it might be simple(r) to plug Search in, even though it would require some tweaks; e.g.:

https://github.com/Automattic/wp-calypso/blob/9af6717b3285be28536cd8da68773af733312611/client/my-sites/plans/current-plan/purchases-listing.jsx#L83

**Comment by jsnmoon** [comment]
@keoshi didn't expect you to be awake 😆 

Thanks for the lead! I'll mess around with the code in that area.

**Comment by jsnmoon** [comment]
>  wordpress.com/plans/my-plan/gibrown.wpsandbox.me::main

It looks like implementing the interface for `/plans/my-plan/` will have to wait until we can query the Search product purchases:

https://github.com/Automattic/wp-calypso/blob/9af6717b3285be28536cd8da68773af733312611/client/my-sites/plans/current-plan/purchases-listing.jsx#L252

@DavidRothstein, is my assumption here correct?

**Comment by AnnaMag** [comment]
To check for UX/copy completeness :

the steps in the flow leading from the jetpack.com/pricing page (tested being logged in):
- selecting a paid plan (non-Pro)
- fill in the remote install url input form
- JPC recognizes pre-selected plan and skips the plans grid landing at /checkout with the annual option. Side Q: there is no alternative path should users change their minds or want to explore monthly (but close the page)

The JPS Solution is available in the /plans tab afterwards, but not presented anywhere in the above flow.
/cc @keoshi

**Comment by DavidRothstein** [comment]
@jsnmoon If you have a Jetpack Search subscription on your site, I think `QuerySitePurchases` would already return it.  That endpoint just returns all the subscriptions for a site, so it should include Jetpack Search.

Trying to test it now, though, I wasn't actually able to add a Jetpack Search subscription to a site in the first place, either in Calypso or via the backend admin... in Calypso the shopping cart just seems to get emptied when you add it to the cart, and in the backend admin you get an error about it not being available for a Jetpack site.  There may be something wrong with the way the product is set up.  But once that is fixed and it is possible to add the subscription, I expect it to be returned from the purchases endpoint automatically.

**Comment by DavidRothstein** [comment]
>Trying to test it now, though, I wasn't actually able to add a Jetpack Search subscription to a site in the first place, either in Calypso

Ah, I see that's actually one of the tasks already listed at the top of this issue :)
>checkout page needs to work ala https://wordpress.com/checkout/gibrown.wpsandbox.me::test0/jetpack_backup_realtime

Not entirely sure why it doesn't work automatically, but like I said above it is probably just some small missing thing in the product setup.

**Comment by gibrown** [comment]
I think this is all out of date, so closing
