### ISSUE TITLE
eCommerce plan: Create Woo default pages on new sites, by default

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#39850]
### Context and Suggestion

I see pretty much every eCommerce plan customer missing the WooCommerce default pages on their site (Shop, My Account, Cart, Checkout) when working on their onboarding, and utterly confused about why they can’t find their products on the site, the checkout flow doesn’t work, etc etc etc.

This is always as simple as setting the default WooCommerce pages on the site (WP Admin > WooCommerce > Status > Tools > Create default WooCommerce pages), and then adding those to the Menu on the site, but this should be done automatically when the site is created to avoid the confusion that's caused.

Would it be possible to automate this on eCommerce sites? I think it’s a fair ask from a Customer creating a site with us to have that set up for them, and it saves a ton of time. So you select eCommerce, we install Woo, and set those pages in the Menu for you. Then you can work on customizing from there and continuing with the onboarding steps.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/
2. Follow with steps to create a site with the eCommerce plan
3. When you get to the screen "Let's start setting up" at https://domain/wp-admin/admin.php?page=wc-setup  - you can either continue with the setup there, or actually skip this clicking on "My Site" to go back to calypso - the effect is the same.

<img width="1349" alt="Screen Shot on 2020-03-03 at 16-07-01" src="https://user-images.githubusercontent.com/31009008/75819651-109e9900-5d69-11ea-8ef7-11bdec4a4a29.png">

#### What I expected
To get a site set up to show products and a purchase flow that works out of the box (Cart > Checkout).

#### What happened instead
The site I got has Storefront installed, and three pages: Home, Contact, and Blog. It seems arbitrary, and out of scope with the eCommerce plan:

![Screen Shot 2020-03-03 at 16 03 39](https://user-images.githubusercontent.com/31009008/75819462-ba315a80-5d68-11ea-896b-c35ed6c998ee.png)

#### Context / Source
#flowsharing #painpoint #manual-testing #user-report

**Comment by timmyc** [comment]
@jameskoster - while this will just be an interim fix - what do you think about adding an item to the checklist to setup the default store pages? Once we migrate off calypsoify, and are using the new setup checklist / obw - this bug no longer exists.

**Comment by jameskoster** [comment]
Yeah that couldn't hurt. I don't think it's something we should ask users to actively _do_ though. Let's just create the pages automatically and display a completed item at the top of the list, so that the user knows the pages have been created.

**Comment by timmyc** [comment]
FYI this fix shipped to Atomic sites last Friday March 20

**Comment by zdenys** [comment]
I have an example of a site on eCommerce plan created on 2020-04-09 that doesn't have the default pages created (2882883-zen). WooCommerce version is 4.0.1. I'm not sure if they ran the setup wizard as above though, but shouldn't the default pages be created regardless of that?

**Comment by zdenys** [comment]
I have tried creating a new eCommerce Plan today. Once I got to the setup wizard, clicked `Skip`. Doing that, indeed resulted in no default WooCommerce pages being created. If I never go back to the setup wizard I (as a user) may be pretty confused that I cannot proceed to Cart or Checkout page as those have never been created.

I had a case 25820920-hc, so I did the above test to confirm users are still ending without the default WooCommerce Pages, at least if they skip the setup wizard.

WooCommerce default pages should be created regardless of the setup wizard. So I'm reopening the issue.

**Comment by davipontesblog** [comment]
I just had this come up with another user in support. Reference: 3792490-zd-woothemes
No default pages created, had to do it for them. It seemed like they had indeed followed the Woo checklist in the new Woo Nav under WooCommerce > Home, and only had "Payments" left to set up.

**Comment by zdenys** [comment]
Keeps happening. I had a Quick Start session in 3849138-zd-woothemes and no default pages were created after the user went through the initial checklist and completed some items.

**Comment by zdenys** [comment]
Another case just now during a Quick Start session 3852524-zd-woothemes

**Comment by zdenys** [comment]
Another case 3858578-zd-woothemes

**Comment by obenland** [comment]
> Once we migrate off calypsoify, and are using the new setup checklist / obw - this bug no longer exists.

@timmyc Has this happened yet or is there an ETA when it might?

**Comment by timmyc** [comment]
@obenland the bug is very much still present in the post calypsoify world. As far as we can tell, it only happens on Atomic when Woo is installed via symlink ( like it happens in the ecommerce plan ). We have been unable to replicate the issue in a local env when the woo directory is symlinked so this makes it terribly difficult to try and fix.

@moon0326 has worked on a couple of approaches, and I think we are approaching a 🩹 for this: https://github.com/Automattic/wc-calypso-bridge/pull/671

And more discovery and conversation on the bug here: https://github.com/Automattic/wc-calypso-bridge/issues/637

**Comment by kwight** [comment]
@moon0326 @timmyc With https://github.com/Automattic/wc-calypso-bridge/pull/671 merged, can we close this?

**Comment by timmyc** [comment]
I just spun up a new test site, and confirmed the fix in production. Default pages created ✅

![image](https://user-images.githubusercontent.com/22080/115467598-9f2cde80-a1e6-11eb-92cd-68eeb0c8f4d2.png)
