### ISSUE TITLE
Layout Previews contain a few errors: 

### ISSUE THREAD

**Issue by kjellr** [Automattic/wp-calypso#39874]
#### Steps to reproduce
1. Create a new free site via wordpress.com/start
2. Edit the homepage, click to change the layout. 
3. Click through the previews. Look out for errors in the preview as noted below. 

I've divided these up into a couple categories: 

---

Many themes have overlap errors that appear only on scroll.

<img width="1440" alt="Screen Shot 2020-03-04 at 9 58 13 AM" src="https://user-images.githubusercontent.com/1202812/75892188-e39cc580-5dfe-11ea-8dd8-119865c27eb7.png">

<img width="1440" alt="Screen Shot 2020-03-04 at 10 01 32 AM" src="https://user-images.githubusercontent.com/1202812/75892382-35dde680-5dff-11ea-901d-34f1f936766f.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 10 01 41 AM" src="https://user-images.githubusercontent.com/1202812/75892390-39716d80-5dff-11ea-948a-9775418d014e.png">

---

A couple have block rendering errors: 

<img width="1440" alt="Screen Shot 2020-03-04 at 9 36 13 AM" src="https://user-images.githubusercontent.com/1202812/75892437-5148f180-5dff-11ea-9ad9-3473fbb17b82.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 9 48 49 AM" src="https://user-images.githubusercontent.com/1202812/75892440-527a1e80-5dff-11ea-86cd-f3f6d6ab8a96.png">
<img width="1258" alt="Screen Shot 2020-03-04 at 10 04 54 AM" src="https://user-images.githubusercontent.com/1202812/75892603-9c630480-5dff-11ea-96b0-b3aaca0c711e.png">

---

And finally: there appears to be a visible warning about the "swiper library" in one of the portfolio themes:

<img width="1260" alt="Screen Shot 2020-03-04 at 10 04 24 AM" src="https://user-images.githubusercontent.com/1202812/75892649-af75d480-5dff-11ea-84b0-a4f1aa5d642a.png">

---

#### Browser / OS version

MacOS 10.15.3, Safari 13.0.5

cc @ianstewart

**Comment by ianstewart** [comment]
Reproduced in Safari on MacOS, non-a8c user, incognito, proxied, with the current default theme, Maywood. 

![image](https://user-images.githubusercontent.com/545779/75904486-ea303a80-5e08-11ea-8a1b-fd5c975b65b3.png)

![image](https://user-images.githubusercontent.com/545779/75904503-f1574880-5e08-11ea-9a5e-257ffaba186f.png)

![image](https://user-images.githubusercontent.com/545779/75904525-fae0b080-5e08-11ea-9ac6-fc02d8b20986.png)

![image](https://user-images.githubusercontent.com/545779/75904544-03d18200-5e09-11ea-8ba0-ca95afd5a356.png)

![image](https://user-images.githubusercontent.com/545779/75904551-09c76300-5e09-11ea-90da-33b43e12d7d9.png)

**Comment by retrofox** [comment]
Tacked in https://github.com/Automattic/wp-calypso/pull/39989
