### ISSUE TITLE
Theme Showcase: Incorrect number in the badge that shows number of themes available

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#39898]
> Edit from @gwwar: @lancewillett recommends to hide the count for now. I believe the theme endpoints are backed by elastic search so things likely need to be re-indexed (though it's always possible it may go out of sync again).

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes
2. click on "Show all themes"
3. Verify the label that shows how many themes are in the showcase

#### What I expected
To see a number that represents how many themes we have.

#### What happened instead
This shows a random number.

#### Browser / OS version
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

#### Screenshot / Video
<img width="1772" alt="Screen Shot on 2020-03-05 at 07-16-54" src="https://user-images.githubusercontent.com/31009008/75981112-cc6ae000-5eb1-11ea-9c07-0b063edebb47.png">

Note: this seems to be random, showing different numbers at different themes. also note I don't have any filters on in the showcase. for example, I add a filter (any) and then remove it shortly after, and the number in the badge goes from 423, to 426.

#### Context / Source
#manual-testing

**Comment by ianstewart** [comment]
I can confirm. 

1. I visit the showcase and click show more themes.
2. I see "211".
3. I add a filter and see a reduced number.
4. I remove the filter (I now have no filters) and see "228" themes.

**Comment by lancewillett** [comment]
Likely not a bug, esp. for a11n sites that are sticked for testing themes.

**Comment by kriskarkoski** [comment]
Is this the same as this issue? https://github.com/Automattic/wp-calypso/issues/15833

**Comment by lancewillett** [comment]
Yes, good call @kriskarkoski.

Correction to my above comment — this is repeatable on any site, not related to a11n users. (That would only impact counts on WP Admin themes.php since it shows themes activated just for that blog.)

**Comment by gwwar** [comment]
I'm seeing a consistent 129 while on the logged out view and logged in. Are folks still seeing inconsistent counts for all themes?

Logged out themes page:
<img width="510" alt="Screen Shot 2020-03-09 at 3 25 39 PM" src="https://user-images.githubusercontent.com/1270189/76262694-4be21180-621a-11ea-9985-1a7b2fa1fb97.png">

Logged-in themes page:
<img width="661" alt="Screen Shot 2020-03-09 at 3 25 50 PM" src="https://user-images.githubusercontent.com/1270189/76262708-52708900-621a-11ea-88b2-dcd4698d37da.png">

**Comment by gwwar** [comment]
ah we're still seeing reports, so I'll hide this for now.
