### ISSUE TITLE
Stats: Wrong URLs in phpBB permalinks to threads

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#39913]
#### Steps to reproduce
1. Starting at URL: wordpress.com/stats
2. Select a site that has phpBB stats, and where you are an admin. I'm using one of our forums sites.
3. Click Posts & Pages
4. Try clicking the view links for several options on the list.

#### What I expected
Every link should bring up the correct page in the forums.

#### What happened instead
I get 404s on topic links because the URL is missing info. For example:
https://en.forums.wordpress.com/2016/01/16/changing-site-title-color/

should be
https://en.forums.wordpress.com/topic/changing-site-title-color/

I am wondering if would be easier to just need to fix redirect / permalink settings for this site, but if other sites are running into trouble it might be worth addressing somehow.

#### Browser / OS version
Doesn't matter

#### Screenshot / Video
What I click:
<img width="834" alt="Screen Shot 2020-03-05 at 1 54 56 PM" src="https://user-images.githubusercontent.com/3476361/76024825-fe4b6900-5ee8-11ea-80f5-d56a2c3ac9f9.png">

What I get:
<img width="1226" alt="Screen Shot 2020-03-05 at 1 55 11 PM" src="https://user-images.githubusercontent.com/3476361/76024815-f8558800-5ee8-11ea-8e3f-a0ab43df8ecc.png">

#### Context / Source
#dogfooding

**Comment by cathymcbride** [comment]
Legit, but stale and no customer reports.
