### ISSUE TITLE
Home: Free Images Video is Too Fast

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#39910]
As reported by @apeatling  the video for “Over 40,000 Free Photos” is really really fast, and makes it a bit difficult to follow.

Let's try and slow the video to half speed, and let the viewer orient themselves before the video starts navigation. This might be a fade in for a few seconds, or simply pausing for a few seconds before the video plays.

This is also an opportunity to move this video to VideoPress like in https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/my-sites/feature-upsell/ads-upsell.jsx#L75

This was previously discussed in p4TIVU-9n1-p2 that we may want to keep video assets out of the codebase to keep the repository size down.

**Comment by Aurorum** [comment]
Here's the video at half the speed: https://cdn.discordapp.com/attachments/448937740399017985/685544991371558961/slowed_photo_library_video.mp4

**Comment by apeatling** [comment]
This feels better, I still think it could be slower however. I think one issue might be that the video goes from one action to another with no pause in between. If it's slower again that might help.

**Comment by Aurorum** [comment]
Is there any specific amount which the speed should be lowered by? It is worth noting that people are able to pause the video though! :)

**Comment by gwwar** [comment]
@Aurorum 💖thanks so much for helping move forward the my home cards! Maybe pause on any video creation for now. I think I might be able to wrangle some help from Marketing.

**Comment by Aurorum** [comment]
Sure thing! :)
