### ISSUE TITLE
Theme Showcase: Premium filter shows free themes when logged in

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#39911]
Not sure if this is a11n-specific or not, but the filter is set to Premium and the highlighted themes are free:

![image](https://user-images.githubusercontent.com/32492176/76018251-259c3900-5edd-11ea-90fb-2cc5915a56fe.png)

**Comment by lancewillett** [comment]
I can repeat this on a test site https://wordpress.com/themes/premium/lancetest14.wordpress.com with Safari / macOS. Using `lancewillett` user (non-a11n).

<img width="1392" alt="Screen Shot 2020-03-05 at 14 26 52" src="https://user-images.githubusercontent.com/66797/76027135-5d12e180-5eed-11ea-83b0-da309115dbf5.png">

Scrolling down a bit:

<img width="1392" alt="Screen Shot 2020-03-05 at 14 27 19" src="https://user-images.githubusercontent.com/66797/76027167-6d2ac100-5eed-11ea-82f5-e35946d20e0f.png">

**Comment by annacmc** [comment]
I was not able to repro this issue any longer:

![image](https://user-images.githubusercontent.com/30754158/108776683-95f90a00-75c7-11eb-9860-35b2807313fd.png)

There is also a duplicate issue in https://github.com/Automattic/wp-calypso/issues/16440.

Closing with label `Closed - Not Reproducible`
