### ISSUE TITLE
Stats: Include (correct) URLs in CSV export

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#39912]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/
2. Click Switch Site & choose a site that would have recent data
3. Scroll to Posts & Pages, click that header
4. Select a viewing period
5. Scroll down and choose to export CSV

#### What I expected
I was hoping the CSV would include the title, URL, and number of visits for that period

#### What happened instead
I got the title and visits, but no URL. If I'm working on a report to compare stats for a list of posts from one period to the next, this means I have to go grab each URL manually. Not ideal.

#### Browser / OS version
Doesn't matter

#### Screenshot / Video
Here's what I get:
![what I get](https://user-images.githubusercontent.com/3476361/76023745-fe4a6980-5ee6-11ea-992f-fb8f4d94eb7c.png)

Here's what I want. Note I added the title and column headers manually. If you think those would be a good idea and wouldn't jack up anyone's processes, OK, but I'm also fine with just the data. Also note, the URL that shows on the stats page for individual threads is actually wrong, but I'll file another issue about that.
<img width="946" alt="ideal csv" src="https://user-images.githubusercontent.com/3476361/76023816-276afa00-5ee7-11ea-9ac6-70aca8fb3d9e.png">

#### Context / Source
#dogfooding trying to get some data from our forums :)

#### Side Note
 I thought for now I could simply copy and paste into a sheet and let Google Sheets figure out how to split it. Not so much. Selecting was hard (basically I had to select the title above, then hold down shift while selecting the CSV option below. That did copy data, but formatting it in a spreadsheet will be a bit of a pain. This is what I got on paste, and even on asking Sheets to split data for me:
![what happens when I just paste](https://user-images.githubusercontent.com/3476361/76024029-a102e800-5ee7-11ea-8dca-f156e6518e8a.png)

**Comment by supernovia** [comment]
Just requesting this again. I'd be using this all the time and I'm guessing our users would, too.

**Comment by Aurorum** [comment]
PR for this issue in #53269. :)

**Comment by supernovia** [comment]
woot! Trying to follow up on old notifications I'd missed and saw this. Thank you for the fix!
