### ISSUE TITLE
Site Editor: create extension point to allow launching outside Gutenberg menu.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#39917]
Currently the Site Editor experiment is only loadable though the gutenberg plugin menu in wp-admin.  We do not want to expose this menu and would like to have the "Site Editor" button at the top level of the wp-admin sidebar.

In order to do this, we must be able to add an extension point for the early return condition in the init function on core.  https://github.com/WordPress/gutenberg/blob/8a94254b6adac030f5a6ffd8e718972e1f19f48e/lib/edit-site-page.php#L37

**Comment by Addison-Stavlo** [comment]
I have a PR open for this: https://github.com/WordPress/gutenberg/pull/20639

**Comment by vindl** [comment]
Closed with https://github.com/WordPress/gutenberg/pull/20639.
