### ISSUE TITLE
Site Editor: explore the possibility of running it with dotcom-FSE sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#39927]
The current dotcom-FSE template parts format should be quite similar to what core expects. We should investigate how much work would be to adapt them so that their existing headers and footers can be edited through core's Site Editor.

**Comment by vindl** [comment]
This issue is still relevant since we are not ready to perform the migration yet.

**Comment by Addison-Stavlo** [comment]
closing this one as there is no dotcom-fse anymore! 🎉
