### ISSUE TITLE
Page Templates: broken block for non-english customers

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39925]
Via @rossanafmenezes at pbAok1-qc-p2

>  If your account is not set to English The blog layout shows a broken block:
>
> ![image](https://user-images.githubusercontent.com/87168/76062995-766c6a00-5f8f-11ea-98e4-0439863898a7.png)
>
> I have tried this with Portuguese, French and Spanish and I get the same result for all of them. If your account is set to English, no issues.

**Comment by obenland** [comment]
I have not been able to reproduce this bug. 

@rossanafmenezes Please feel free to re-open this ticket once there's a reliable way to reproduce this issue
