### ISSUE TITLE
Gutenboarding: replace back button with W logo

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39933]
- Bring back logo (removed in https://github.com/Automattic/wp-calypso/pull/38376)
- Remove the back button; we'll have either contextual back buttons or use the browser back button instead

As per i10 designs:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/87168/76101706-890a9180-5fd7-11ea-8c5c-3b768b93043b.png">

**Comment by millerf** [comment]
@simison I feel a bit silly 🥴 

I think I did what was intended, but I cannot test it as... I have no idea how to get to the Gutenboarding pages 😅 I created a Pull Request so you code can be reviewed. If anyone can let me know what is the process to get to those pages, thanks in advance...

**Comment by millerf** [comment]
Found it! 👍

**Comment by simison** [comment]
No worries, I appreciate you jumping to this. :-)

At localhost `/gutenboarding` will get you there.

**Comment by millerf** [comment]
No problem.

Yes, I found it after tiptoeing with the urls
