### ISSUE TITLE
Sidebar: Expand Highlighted Section

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#39934]
The Plan and Domains Tab have shared subsections. When MyPlan/Plans is selected, Plan is highlighted, but when email or domains is selected, the Manage > Domains tab is highlighted. However if the Manage grouping is collapsed, it may appear that no section is highlighted leaving customers with no orientation.

At a minimum let's make sure that any sidebar groups are expanded when we are on that section. I think it's a little strange that we have a subsection that navigates to a different sidebar item, but I'll defer to design on thinking through that.

<img width="707" alt="Screen Shot 2020-03-06 at 9 08 03 AM" src="https://user-images.githubusercontent.com/1270189/76106789-7323af00-5f8c-11ea-896c-258f5eea7eed.png">

![Mar-06-2020 09-22-36](https://user-images.githubusercontent.com/1270189/76106807-7ae35380-5f8c-11ea-9af2-0bbdaadec23d.gif)

**Comment by millerf** [comment]
@gwwar (duplicating the comments made on my Pull Request)

 * Used `import { expandMySitesSidebarSection as expandSection } ` as done... everywhere!! (6 files). Maybe renaming this method might be considered?
 * I added a onClick on the NavItem. I am not sure if it is the best way or if it should be handled by the router, or even directly within the constructors or ComponentDidMount of DomainWarnings/EmailManagement components... The difference in behaviour is minimal, but it would prevent having the same problem if a another page links to those pages...
 * Although having the section expanding is enough, maybe  highlighting the section header when one of the child is `selected` could also be an option. As you also lose some navigation information when section is manually closed.
