### ISSUE TITLE
Domains: Language around DNS fixes could be simplified

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#39939]
Originally brought up in Slack by @amamujee : p1583516414300400-slack-dotcom-manage

<img width="655" alt="signup___creating_a_new_site_notes (1)" src="https://user-images.githubusercontent.com/2124984/76111878-27cec800-5faf-11ea-9509-3c2f0a4dc77a.png">

"DNS Configuration required" is a bit jargon-y. Could this notice language be simplified to something like, "Set up your domain"?

/cc @Automattic/cobalt and @fditrapani since I know you're working on domains-related flows at the moment!

**Comment by fditrapani** [comment]
I like "Set up your domain" — that makes sense to me. We should also change the CTA. There isn't a lot of room to work with though :D. Some options could be "Start", "Go", "Setup" or a chevron (I'm not sure we do that anywhere though).

**Comment by arunsathiya** [comment]
I like "set up your domain" as well. Maybe, "complete your domain setup" could work too - because the user is halfway through the domain setup process; meaning, have mapped the domain and is pending DNS setup at their DNS manager/registrar's end.

**Comment by fditrapani** [comment]
> complete your domain setup

That's a good one too! if we have the space for it and a CTA.
