### ISSUE TITLE
Combine post-checkout screen with Customer Home

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#39948]
If you upgrade your plan post-signup you see a thank you page like this:

<img width="1505" alt="Screen Shot 2020-03-07 at 11 37 46 AM" src="https://user-images.githubusercontent.com/437258/76151284-37f6ae00-6068-11ea-97c0-079f93cc1460.png">

That has content similar to what we provide on customer home. But that page is ephemeral and disappears as soon as you click on anything. 

Then when you return to customer home there is no change from before the upgrade—it is the same for a free site or a business plan site. 

Instead,

We could show use the 'congratulations' banner we use for new sites and site launch on Customer Home to thank customers for their purchase, and adapt the Customer Home to show off new features and benefits unlocked with their purchase. 

This is especially true for customers that upgraded from a specific prompt in order to leverage a particular feature. That feature could show up as an action item on the home page after the purchase helping customers follow through.

**Comment by jordesign** [comment]
Closing this - as the new (and upcoming flows) will replace this consideration.
