### ISSUE TITLE
[Customer home]: blacklisted sites should receive a warning message rather than loading placeholder

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#39953]
## This issue

A user can visit the Customer Home of a blacklisted site, however the <a href="https://github.com/Automattic/wp-calypso/blob/88ad523/client/my-sites/customer-home/main.jsx#L532">checklist doesn't load</a>. 

<img width="1186" alt="Screen Shot 2020-03-09 at 10 17 12 am" src="https://user-images.githubusercontent.com/6458278/76173609-f0e9f380-61f4-11ea-9a0e-ef7326559027.png">

Calls to `/rest/v1.2/sites/[SITE_ID]/checklist` return `403`

<img width="835" alt="Screen Shot 2020-03-09 at 11 01 30 am" src="https://user-images.githubusercontent.com/6458278/76173656-5b9b2f00-61f5-11ea-80d8-2df41304cd16.png">

According to the Fieldguide:

> "**Black**: Suspended site. Site is frozen. Posting and editing is disabled. Blog is hidden from everything and cannot be accessed directly either. The user sees a warning on their dashboard."

Should we add some type of message here? Similar to what a visitor to the website might see?

<img width="796" alt="Screen Shot 2020-03-09 at 10 36 32 am" src="https://user-images.githubusercontent.com/6458278/76173646-3f978d80-61f5-11ea-9293-14de80fc9ca6.png">

Reported here: p7DVsv-8aJ-p2#comment-27109

## How to reproduce

1. In the Blog RC give a test site a black flag
2. Visit wordpress.com
3. You will land on Customer Home

**Comment by gwwar** [comment]
Digging in a bit, it looks like we haven't been messaging this appropriately in the WordPress.com dashboard. Just notifications and wp-admin.

<img width="1153" alt="Screen Shot 2020-03-10 at 1 17 04 PM" src="https://user-images.githubusercontent.com/1270189/76356006-77c0ce00-62d2-11ea-9f5c-8951b1d0f706.png">

<img width="1322" alt="Screen Shot 2020-03-10 at 1 16 37 PM" src="https://user-images.githubusercontent.com/1270189/76356029-81e2cc80-62d2-11ea-9e52-f10455c727b3.png">

I think we may be able to fix this more generally, along with https://github.com/Automattic/wp-calypso/issues/39952 by removing sidebar sections and showing a prominent notice.

**Comment by gwwar** [comment]
Kicking back for now as up for grabs since I think we need a bit of API work. When we're in this state most API responses 403

**Comment by gwwar** [comment]
closing in favor of 24-gh-dotcom-private
