### ISSUE TITLE
RTLCSS being ignored, WebpackRTLPlugin not working?

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#39957]
RTLCSS comments are being ignored, CSS styling specific to RTL/Non-RTL are being included. I suspect WebpackRTLPlugin is not doing its job.

#### Steps to reproduce

If you were to open up the CSS files on live (hash on filename may change):
https://wordpress.com/calypso/evergreen/entry-main.8ea72e8a6e3ee99e8965.min.css

or inspect the CSS file on your local instance:
http://calypso.localhost:3000/calypso/evergreen/entry-main.css

You will see that RTL specific CSS styling is inside it. Use `/*!rtl:ignore*/` as keyword to search within the CSS file.

You can also see the screenshots added below for clarity.

#### What I expected

- RTL specific styling using `/*!rtl:ignore*/` should only exists inside `*.rtl.css` files.
- Non-RTL specific styling using `/*!rtl:ignore*/` should on exists inside `*.css` files.

#### What happened instead

- Non-RTL/RTL specific styling are showing up on both `*.css` & `*.rtl.css` files. I suspect WebpackRTLPlugin is not working.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/1287077/76201556-68884480-622e-11ea-883e-eee502a02f0d.png)

![image](https://user-images.githubusercontent.com/1287077/76201581-7047e900-622e-11ea-8abd-ceeb633bddf9.png)

![image](https://user-images.githubusercontent.com/1287077/76201632-8190f580-622e-11ea-93e5-ee18fb6dfeec.png)

![image](https://user-images.githubusercontent.com/1287077/76201649-86ee4000-622e-11ea-83ac-fa65492bc982.png)

**Comment by jsnajdr** [comment]
I think the `rtl:ignore` directive doesn't work the way how you describe the expected result.

RTLCSS (and the `webpack-rtl-plugin` that calls it) converts a `*.css` file into `*.rtl.css`, and doesn't modify the original `*.css` file. Therefore, one can't expect anything marked with `/* !rtl:ignore */` to be modified or removed in the original file.

The `/*rtl:ignore*/` and `/*!rtl:ignore*/` syntaxes both behave the same way. The `!` character is probably some legacy/backward compatibility thing. It doesn't mean "negate".

`/*rtl:ignore*/` also doesn't mean that anything should be removed. Normally, if there is a CSS rule like `padding-left: 10px`, RTLCSS will change it to `padding-right: 10px` in the output `*.rtl.css` file. Similarly, it modifies all other CSS rules that have a right/left meaning, by swapping the direction.

`/*rtl:ignore*/`-marked CSS rules won't be modified and will be left unchanged. You can see it in action on your `security.rtl.css` screenshots. The `padding-right` and `direction` rules are not modified in the RTL output.

If some CSS code should be removed from the `*.rtl.css` version, there is a `/*rtl:remove*/` directive for that. But I don't see it used anywhere in Calypso.
