### ISSUE TITLE
Slideshow block broken when used within Layout Grid block

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#39956]
### Steps to reproduce

1. Add a Layout Grid block to a page with a single column
2. Add a Slideshow block within the Layout Grid block and choose two images from the Media Library to display

### What I expected

Slideshow block would display properly.

### What happened instead

Slideshow block displays as super-wide section of white-space in the editor and on the page. Causes the editor experience to be hard to use for content past the block.

### Browser / OS version

Firefox 73 on macOS (Catalina)

### Screenshot / Video
![Screen Shot 2020-03-09 at 09 19 02](https://user-images.githubusercontent.com/51966986/76199179-4ddead00-61e7-11ea-8449-d1fd58281a6a.png)

### Context / Source

2774573-zen

#user-report

**Comment by synora** [comment]
The slideshow displays fine for me in the editor-so I'm unable to replicate this. 

@lancewillett I did notice however that the slideshow jumps when added on Chrome Version 88.0.4324.96 (Official Build) (x86_64)/Big Sur (11.1): https://d.pr/v/Qtaycl

No jumping effect was seen on Safari(14.0.2)

**Comment by adelineyaw** [comment]
User report: 4722807-zd-woothemes

For further context/testing, the user report was originally mentioned here: pd4QKa-rX-p2

**Comment by sajmes** [comment]
Please notify this user when this is fixed. For now, they are working around it by using a Columns block instead.

4738719-zd

**Comment by mriyazuddin** [comment]
4727185-zd

**Comment by tellisbethel** [comment]
User report: 4749786-zd-woothemes

**Additional details**: The Slideshow block, when placed into a Group Row block or a Layout Grid Column block, is so wide it's disabling the toolbar in the Editor, not displaying images, and preventing the user from selecting any other blocks that lie on the same visual row.

**Workaround**: Advised user to use the Columns block, but they have seven Layout Grids with slideshows, text and buttons to fix so it might take some time to adjust everything.

**Comment by aetta** [comment]
4749546-zd

As a workaround, I asked the user to use the Columns Block instead, as mentioned above!

**Comment by danielk-am** [comment]
4765799-zd

Encountered above. Workarounds tested that work:

Columns block > Slideshow block
Group block > Columns block > Slideshow block
Group block > Row block > Slideshow block

**Comment by carinapilar** [comment]
Helped fix some pages with this issue on 4760957-zd-woothemes - user complained that the content in the editor was gone, while it was just not showing. It also breaks the List View sometimes, so it's hard to navigate and delete the blocks.

**Comment by jromales** [comment]
Another report: 4786538-zd-woothemes

**Comment by louinel** [comment]
Another case: #4787795-zen

**Comment by arunsathiya** [comment]
Same issue on 4786962-zen. Advised to get rid of `Layout Grid` block in favor of a `Columns` block as the `Layout Grid` block isn't serving much purpose in this setup.

**Comment by Jaykame** [comment]
Replicate same issue: 4789584-zen

**Comment by tellisbethel** [comment]
Another case here: 4789463-zd-woothemes
Asked user to move their items to a Columns block instead of the Layout Grid block.

**Comment by carinapilar** [comment]
Another case on 4790028-zd-woothemes

**Comment by kspilarski** [comment]
Same case in 4795977-zd.

**Comment by Greatdane** [comment]
Bring over reports from duplicate issue:

4792060-zd-woothemes
34248460-hc

**Comment by Greatdane** [comment]
Another report: 4796756-zd-woothemes

**Comment by devNigel** [comment]
Another report: 29620850-hc
Follow up: 4800911-zen

**Comment by devNigel** [comment]
Changed priority to Blocker since it affects the functioning of the editor. I am also getting users asking for refunds since they have been waiting for over a week already. 

User report: 34255092-hc
Followup: 4804497-zd-woothemes

**Comment by sanjeev00733** [comment]
Another report in #4808746-zen

**Comment by jromales** [comment]
Another one on 4810396-zd-woothemes I shared them the workaround; to use Columns block instead of Layout Grid

**Comment by Abdul-Elsayed** [comment]
Reported here 4810396-hc

**Comment by csabarakasz** [comment]
467449-zd-woothemes

Bringing this over from duplicated bug report.

**Comment by Abdul-Elsayed** [comment]
Another report in #4828937-zen

**Comment by edequalsawesome** [comment]
Another report 4839558-zen

**Comment by rw-ye** [comment]
Another report: 4847705-zd-woothemes

**Comment by ahmadbaig1** [comment]
Another- 4843385-zen

**Comment by JessBoctor** [comment]
Had a report of this in 31318564-HC

Provided the customer with the Columns Block workaround

**Comment by druesome** [comment]
Another report: #4870627-zd-woothemes

**Comment by kylemcph** [comment]
Another report: #4882584-zen

**Comment by sanjeev00733** [comment]
Another report in #28657010-hc

**Comment by louinel** [comment]
New case here: 4895797-zen

**Comment by danielk-am** [comment]
Another new one over here: 4903431-zen
Provided columns block as the workaround.

**Comment by Robertght** [comment]
This happens with FSE, having a slideshow block inside a page template generates the same width error on the block.

Using the workaround from here does its thing nicely.

cc @Automattic/cylon in case you can take a closer look.

**Comment by danielk-am** [comment]
Another one here: 4916326-zen

Tested and provided the workaround by using Columns block.

**Comment by yansern** [comment]
A quick investigation shows that it's caused by a grid blowout. https://css-tricks.com/preventing-a-grid-blowout/

Swiper's resize observer updates the width of the slideshow wrapper when there is a change in the width, but the grid expands depending on the width of the content, which triggers the resize observer to expand further, repeating the vicious cycle until the width could not be expanded anymore.

**Comment by yansern** [comment]
Also reported in the Swiper library https://github.com/nolimits4web/swiper/issues/2914.

**Comment by yansern** [comment]
Fix is ready here. https://github.com/Automattic/jetpack/pull/23854

**Comment by vajrasar** [comment]
Hi everyone 👋

Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread. Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by Jaykame** [comment]
Opening as I have a user with this issue in 5666258-zen which does not display the slideshow on the site editor index template. Provided the workaround of putting the slideshow in Group Block which shows the slideshow. I saved and removed the group block later and the slideshow remains working.

**Comment by simison** [comment]
> which does not display the slideshow on the site editor index template. 

@Jaykame Isn't this a bit different bug? I think it would make sense to open a new issue, especially since original issue here was already fixed. Otherwise it becomes a bit hard to manage and this issue becomes too generic, catching multiple bugs.

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2, Simple, Atomic, and self-hosted, and this is a separate bug

📌 FINDINGS/SCREENSHOTS/VIDEO
- Original bug is fixed
- 
📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
@Jaykame This is a completely different issue. Please file a new bug for this issue. Thanks

**Comment by csabarakasz** [comment]
7323357-zd-a8c
