### ISSUE TITLE
Unlaunched blacklisted sites should not be able to launch

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#39952]
## The issue

Unlaunched sites that have been blacklisted are still "launchable".

<img width="1350" alt="Screen Shot 2020-03-09 at 10 23 32 am" src="https://user-images.githubusercontent.com/6458278/76173484-04488f00-61f4-11ea-9d04-25cb3b0070f4.png">

Since API calls to [/sites/${ action.siteId }/launch](https://github.com/Automattic/wp-calypso/blob/88ad523/client/state/data-layer/wpcom/sites/launch/index.js#L25) return  `403` (unauthorized), when the owner proceeds to launch a blacklisted site they'll be stuck in a forever loop.

![Mar-09-2020 10-22-58](https://user-images.githubusercontent.com/6458278/76173474-fbf05400-61f3-11ea-9c8b-f9310587a646.gif)

Reported here:  p7DVsv-8aJ-p2#comment-27109

## How to reproduce

1. Create a site, but don't launch it
2. In the Blog RC give the new site a black flag
3. Visit the new site
4. Try to launch the site

## Suggested approaches

We should think about disabling site launch if the site has been blacklisted, either by disabling all launch banners (probably higher effort), or catching the black flag status at the start of the `site-launch` flow, preventing launch progress and providing the appropriate messaging.

**Comment by gwwar** [comment]
What's preferred behavior here @amamujee @adamziel @michaeldcain ?

**Comment by amamujee** [comment]
When a user is blacklisted do they know they have been blacklisted? If so, then I like @ramonjd  proposal of 'catching the black flag status at the start of the site-launch flow, preventing launch progress and providing the appropriate messaging'

**Comment by gwwar** [comment]
Digging in a bit, it looks like we haven't been messaging this appropriately in the WordPress.com dashboard. Just notifications and wp-admin.

<img width="1153" alt="Screen Shot 2020-03-10 at 1 17 04 PM" src="https://user-images.githubusercontent.com/1270189/76356006-77c0ce00-62d2-11ea-9f5c-8951b1d0f706.png">

<img width="1322" alt="Screen Shot 2020-03-10 at 1 16 37 PM" src="https://user-images.githubusercontent.com/1270189/76356029-81e2cc80-62d2-11ea-9e52-f10455c727b3.png">

I think we may be able to fix this more generally, along with https://github.com/Automattic/wp-calypso/issues/39953 by removing sidebar sections and showing a prominent notice.

**Comment by gwwar** [comment]
closing in favor of 24-gh-dotcom-private

**Comment by kwight** [comment]
I've deployed D40525-code, so the banner no longer shows on the front-end of blacklisted sites.
