### ISSUE TITLE
Gutenboarding: remove/hide page selector

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39969]
For now, let's hide the page selector step in `/gutenboarding`:

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/87168/76217194-a1b6b980-621a-11ea-8135-4a7d26d68921.png">

We will likely introduce either "feature selector" or "page selector" in some format to these flows again, but it's unclear when and how it'll look like.

**Options:**
- Remove the code entirely; cleaner, especially considering TypeScripts (cc @sirreal if you wanna expand on how/why). We can always get the code back easily from the removal PR. 
- Feature-flag it: feature flagging might stress-test nicely how modular the flow really is and how well prepared for A/B testing steps we are.

**Comment by sirreal** [comment]
> * Remove the code entirely; cleaner, especially considering TypeScripts (cc @sirreal if you wanna expand on how/why). We can always get the code back easily from the removal PR.

This was off the top of my head, but I believe the way some of our routing is typed this will help us catch and dangling routes. With a (runtime) feature flag, we can't remove a particular route from our type, it's still valid. If we remove the route from the type, however, type checking can inform us if we use a route we shouldn't be.

Removing this route would probably guide the rest of this change:

https://github.com/Automattic/wp-calypso/blob/1dfbf4c02d10f6372f71d21961acd3401204821d/client/landing/gutenboarding/path.ts#L14

Using a feature flag is also valid and could help to inform some future work around modularity and step ordering/insertion/removal. I'm not opposed to that.
