### ISSUE TITLE
Site selector's on hover style missing

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#39987]
### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/ (when logged in)
2. Hover over the list of sites

#### What I expected
The hover style on the site selector to change the background on the item I'm hovering over.

#### What happened instead
No background color change, just foreground. `Private` badge got a weird background change as well.

Interestingly, I can reproduce this reliably with one user, but not with another. I tried in a Private window, with empty cache and can still reproduce with one user (my main, Automattic user), but not the other (test account).

I think it might be the contents of the site list that triggers this bug. But I tried filtering out some sites on that list (so that, for example, no Private or Domain sites show up), but that did not seem to have changed anything.

#### Browser / OS version
All on macOS Catalina 10.15.3
Firefox 73.0.1
Safari 13.0.5
Chromium 80.0.3964.0

#### Screenshot / Video
![Screen Recording 2020-03-09 at 20 08 35 2020-03-09 20_18_30](https://user-images.githubusercontent.com/3392497/76253761-29b0b980-6243-11ea-8019-bb7621ed5463.gif)

#### Context / Source
#dogfooding, #manual-testing

**Comment by lancewillett** [comment]
Thanks for reporting. Can you inspect console for network timeouts, and errors in the missing images or styles?

The way it looks in the video you shared, seems like something isn't loading properly.

**Comment by klimeryk** [comment]
No, nothing stands out - basically all 200, no console errors (except for `Error: Failed to load script "//stats.wp.com/w.js?60"`, but that's the same for my other user and is a result of an adblocker, I'd imagine).

**Comment by youbrokesomething** [comment]
Most, if not all, of these flows have been updated since 2020. I can't reproduce the original issue anymore.
