### ISSUE TITLE
Media Library: Welcome Message Typo

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#39981]
When a new user visits their Media Library in Calypso, a popup window appears, welcoming them to the Media Library.  However, the welcome message contains a typo, as it reads "Welcome to your media libary!"

<img src="https://d.pr/i/xIWdBu+" width="600" />

This seems to be the affected file:

https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/layout/guided-tours/tours/media-basics-tour/index.js#L39

#### Steps to reproduce
1. Sign up for a new WordPress.com account and create a new site
2. Visit Site > Media in Calypso
3. Wait for the welcome popup to appear

#### What I expected

Welcome message to be "Welcome to your media library!"

#### What happened instead

"Welcome to your media libary!"

#### Screenshot / Video

<img src="https://d.pr/i/xIWdBu+" width="600" />

**Comment by lancewillett** [comment]
Good find. That's an embbarrasing tiypoe
