### ISSUE TITLE
Composite Checkout: incorrect decimal places on coupon discounts (4)

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#39990]
When applying a percentage coupon discount, we don't seem to be using the `coupon_discounts_integer` response from the API, so discounts are sometimes improperly rounded in the UI.

![Screen Shot 2020-03-09 at 4 34 27 PM](https://user-images.githubusercontent.com/942359/76256320-1a6f4300-6226-11ea-9cce-3175c815d256.png)

**Comment by millerf** [comment]
@michaeldcain Is it possible to get a coupon code to work on it?

**Comment by michaeldcain** [comment]
@millerf: `CHECKOUT_TESTING` should apply a universal 2%. 

I think this will require some changes to the shopping-cart endpoint so that we return a proper, localized display value for coupons in addition to pre-discounted product costs. Let me know if you think otherwise.

![Screen Shot 2020-03-16 at 2 56 31 PM](https://user-images.githubusercontent.com/942359/76791824-11d3bb00-6798-11ea-8f50-11c7b03e9b0c.png)

**Comment by millerf** [comment]
@michaeldcain Who has that many coupons / bundled stuff XD

What do you mean by coupon is applied "beforehand"? and how com it is used after taxes?... Bizarre...

Yes, there seems to be some work needed here. Maybe it needs some specifications to be drafted as it doesn't seem that straightforward. For example: would the last coupon be "used", as price is already 0?

**Comment by michaeldcain** [comment]
@millerf: the cart above is definitely an edge case, but each of the discounts/coupons can appear on their own. I tried to dig into this a little more yesterday, but for more information on the cases above:

- "25% coupon applied": the cost of a premium plan is $96USD, so this line item should read either "~~$96~~ $72" or just $96 with a $24 calculated as part of the Coupon line item at the bottom
- "bundled but no free text": with certain plan purchases a plan is included (hence the $0 price). In these situations, there should be a "Free for first year with plan" description below the product name.
- "25% coupon applied to already 50% off domain": although not reflected here in either of the domain line items, .live domains were already on a 50% off sale (so $25 => $12.50), then additionally this one has the 25% coupon applied, so it should read "~~$12.50~~ $9.38" or $9.38 with the $2.62 discount calculated as part of the coupon line item
- "-$0 coupon line item": I think that because the coupon is being applied to all of the `product_cost` responses above, the calculation for the coupon line item is just rendering as $0. Currently, [we're calculating this on the front-end](https://github.com/Automattic/wp-calypso/blob/master/packages/composite-checkout-wpcom/src/lib/translate-cart.ts#L57), but I think the shopping-cart endpoint should return proper display values here instead.

> and how com it is used after taxes?

Great point. I wonder if we should move this line above the tax line item. @fditrapani

**Comment by michaeldcain** [comment]
I spoke to @fditrapani about this, and discounts/coupons should be reflected as follow:

- Discounts (sales/bundling independent of the user's cart) should be shown as a strikethrough of the full price beside a pre-coupon product cost (so "~~$25~~ $12.50" for the third line item above)
- Coupon discounts applied by the user should not be reflected in the product line items, only as a total amount applied at the bottom (so "-$26.62" for this cart)
- The coupon line item should come before the tax line item and apply to the cart pre-tax.

**Comment by millerf** [comment]
@michaeldcain I tried just to display the composite checkout to no avail. I tried both of the methods explained [here](https://github.com/Automattic/wp-calypso/issues/40073#issuecomment-597887166) by @sirbrillig and still nothing.

I start to think it might not be the best tasks for `OSS citizens` 🙃
