### ISSUE TITLE
Settings: site settings data is refreshed upon polling even if no changes

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#40]
The site title reverts if you stay too long on the edit page without committing your change

Steps to reproduce:

1. Create a new WordPress.com site.
2. Click on Settings in Calypso to set a new site title and site description.
3. After setting a new title, it is automatically set back to the original title.

https://cloudup.com/c80Qh7xYZpP

You can change the title. You just need to save it to persist the change. The problem is that we are polling sites data on a periodic basis, and we refresh this page whenever polled request resolves. So if you have changed the title in the page here, it will revert back when the polling request resolves. I think the best solution here is to avoid refreshing settings data here unless it has actually changed.

**Comment by gwwar** [comment]
Fixed by #1167
