### ISSUE TITLE
Gutenboarding: style picker - previews

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40008]
While these images in the design picker are static images... 

<img width="779" alt="image" src="https://user-images.githubusercontent.com/87168/76297987-6e7b3580-62c1-11ea-9cf6-aab2684fa51b.png">

The big preview in style picker will be dynamic:

<img width="781" alt="Screenshot 2020-03-10 at 11 23 16" src="https://user-images.githubusercontent.com/87168/76298079-910d4e80-62c1-11ea-8348-c5a097f21b70.png">

Exact details how to implement this to be decided.

Context p7rd6c-2dV-p2

**Comment by sirreal** [comment]
#40227 is implementing this with D40475-code.

> While these images in the design picker are static images...

Rendering static HTML like we're doing in #40227 / D40475-code, I don't see why we can't use the same preview in the "Choose a design" step. Rendering multiple should be cheap…

Should we explore this option?

**Comment by simison** [comment]
>Rendering static HTML like we're doing in #40227 / D40475-code, I don't see why we can't use the same preview in the "Choose a design" step. Rendering multiple should be cheap…

We might get curated, art-directed images for those thumbnails. So they wouldn't necessarily be "screenshots".

**Comment by sirreal** [comment]
Implemented by #40227
