### ISSUE TITLE
Gutenboarding: style picker - viewport size

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40009]
Allow changing style picker's preview viewport size:

<img width="958" alt="Screenshot 2020-03-10 at 11 14 33" src="https://user-images.githubusercontent.com/87168/76297379-64a50280-62c0-11ea-8de0-45fc0cf1bb91.png">

<img width="953" alt="Screenshot 2020-03-10 at 11 14 48" src="https://user-images.githubusercontent.com/87168/76297401-6ec70100-62c0-11ea-9aab-d2667ad38a86.png">

Check the prototype (link at p7rd6c-2dV-p2) to see if there's animation between sizes.

**Comment by simison** [comment]
In the latest design these are moved to up:

<img width="936" alt="Screenshot 2020-03-13 at 10 21 09" src="https://user-images.githubusercontent.com/87168/76602811-62d37d00-6514-11ea-994c-0f014f7e7282.png">

**Comment by yansern** [comment]
https://github.com/Automattic/wp-calypso/pull/40106
