### ISSUE TITLE
Gutenboarding: add a contextual back button to design picker

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40006]
Let's add a contextual back button to the design picker. It should bring the customer back to the "intent gather" step.

Here it is in new design:

<img width="788" alt="Screenshot 2020-03-10 at 11 00 17" src="https://user-images.githubusercontent.com/87168/76296150-71285b80-62be-11ea-91d0-bb3bd9689c92.png">

Context p7rd6c-2dV-p2

**Comment by yansern** [comment]
Does "Start Over" mean clearing out the vertical & site name and the user previously entered?

**Comment by olaolusoga** [comment]
Yes, it should.
