### ISSUE TITLE
Gutenboarding: style picker - font pairing list

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40010]
Create a list of font pairings with custom font applied to each button:

<img width="894" alt="image" src="https://user-images.githubusercontent.com/87168/76296964-b731ef00-62bf-11ea-8e00-27a10ba1586c.png">

Clicking on font pairing changes font styles in the preview.

**Questions:**
- Should buttons be static images to avoid loading so many fonts?
- Can fonts be loaded so that only the characters we need are loaded?
- Localization concerns?

We have "global styles" plugin wpcom and another one being worked in core Gutenberg. Initially, we'll leverage the wpcom version and we should make sure to be aligned with the core version to make the transition easier some day.

Context p7rd6c-2dV-p2

**Comment by sirreal** [comment]
This is partially implemented by #40227 and  #40206 adds a preview with fonts.

**Comment by sirreal** [comment]
> Should buttons be static images to avoid loading so many fonts?
> Can fonts be loaded so that only the characters we need are loaded?

https://github.com/Automattic/wp-calypso/pull/40168 loads limited subsets of fonts. The fonts are a selection to only contain necessary characters and weight. Results are:

10 css requests / 2.7 kb
10 font requests / 13.6 kb

20 total requests / 16.1 kb

We do 9 additional CSS requests to reduce size significantly on the fonts. We can explore other setups.

> Localization concerns?

Do these font names need to be localized? They're proper nouns I'd expect to remain as they are, but I'm not an expert.

**Comment by simison** [comment]
@sirreal sounds good 👍 

Nah, I don't think they need to be localized.
