### ISSUE TITLE
Checkout: Total Includes Tax When Paying With Credits

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#40016]
#### Steps to reproduce
1. Create a new site with a paid plan or upgrade an existing site.
2. Pay for the upgrade using credits — added to store admin.
3. During checkout enter a postal code for a location where we charge tax.
4. Complete the purchase.

#### What I expected
Since we aren't charging tax for purchases made with credits, it should not be listed on the checkout screen.

#### What happened instead
The checkout lists the tax and includes it in the Total listed at the bottom of the checkout page.

#### Browser / OS version
Tested on Chrome 80 and macOS 10.15.3

#### Screenshot / Video
<img width="557" alt="Screen Shot 2020-03-10 at 9 56 36 AM" src="https://user-images.githubusercontent.com/42454301/76320785-8483f880-62b7-11ea-9d08-d40123e80eba.png">

#### Context / Source
#manual-testing

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by sirbrillig** [comment]
This is a bug with the shopping cart endpoint; it should not report taxes on orders where the credits cover 100% of the purchase.
