### ISSUE TITLE
Jetpack Backup: rename “Activity” menu option to "Activity & Backups" Atomic and Jetpack-connected sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#40058]
Suggested by @hafizrahman (ref: p58i-8F7-p2)

Add a new menu item "Tools -> Backup" for Atomic and Jetpack-connected sites which links to the Activity Log page filtered to the backups content:

`https://wordpress.com/activity-log/SITEURL?group=rewind`

1. Makes finding backups easier for users (current flow: Go to Site Activity, click Activity Type, find Backups and Restores).
2. Backups are important and useful feature.
3. In the future, we could use the page to upsell sites into the Business or eCommerce plan.

<img width="327" alt="Screen Shot 2020-03-11 at 15 26 43" src="https://user-images.githubusercontent.com/66797/76470345-220d2400-63ad-11ea-8c06-29f1a7b78010.png">

**Comment by lancewillett** [comment]
Input from @folletto 

If the task is to change the name from “Activity” to “Backups”.

- If it’s selective, some sites don’t have Backup — WordPress.com Simple —  use “Activity” (no-backup) and “Activity & Backups” (yes-backup).
- When clicked and Backups are available for the site, pre-filter the page so it shows by default “Activity Type: Backups and Restores”.

**Comment by lancewillett** [comment]
After looking at this more, I believe the simplest possible change is this:

- Add new "Backups" menu item only for Atomic and Jetpack-connected sites
- The link should use `?group=rewind` to pre-filter the Backups in the view
- Leave "Activity" menu item in place for all sites

**Comment by folletto** [comment]
Let's start with that then! :)

**Comment by lancewillett** [comment]
@hafizrahman @folletto #40113 is ready to review and test.

**Comment by lancewillett** [comment]
Worth discussing if the label change will require a lot of documentation and screenshot changes for Happiness Engineers.

Either way we'll give the Atomic Guild a heads-up.

**Comment by jeherve** [comment]
Should we consider updating the Masterbar as well? It is enabled by default on all Atomic sites, and cannot be disabled:

![image](https://user-images.githubusercontent.com/426388/76641287-a5677a80-6551-11ea-8eed-f4120c32ace5.png)

This can be done here:
https://github.com/Automattic/jetpack/blob/1364e8049ccd517132ef466d609d028d91dc7219/modules/masterbar/masterbar.php#L892

We already have Atomic-only things in that file:
https://github.com/Automattic/jetpack/blob/1364e8049ccd517132ef466d609d028d91dc7219/modules/masterbar/masterbar.php#L1261

**Comment by lancewillett** [comment]
@jeherve I'd like to remove that entire menu system for all WordPress.com sites. It's too difficult to maintain, and the design is now stale.

**Comment by lancewillett** [comment]
Two follow-up next actions as improvements next time this feature is worked on.

1. https://github.com/Automattic/wp-calypso/issues/40150
2. https://github.com/Automattic/wp-calypso/issues/40151
