### ISSUE TITLE
Customizer: Clarify the "randomize headers" button (selected state and result) for header images

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#40050]
When selecting a custom header image, the "Randomize headers" buttons can seem unresponsive, especially on mobile devices.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize
2. Select a site to open the customizer.
3. Select the "Header Image" section (note that you will need a site with a theme that supports customer headers).
4. If you don't have any previously uploaded or suggested headers, upload a few header images to choose from.
5. Select a single header image and notice the results.
6. Select the "Randomize uploaded headers" or "Randomize suggested headers" button.

#### What I expected

I expect a clear selected state for that button, with some kind of clarity around how this affects my site.

#### What happened instead

It looks like nothing happened, especially on a mobile device where I may not be able to see the "Current header" section of the customizer at the same time as I see the "Randomize headers" button.

#### Browser / OS version

Tested in Safari on iPhone XS/iOS 13.3.1 and Chrome 80.0.3987.132 on macOS 10.15.3.

#### Screenshot / Video

Self-hosted site customizer with clear blue border around selected header option:

Single header image|Randomized headers
-|-
![Screenshot 2020-03-11 12 21 41](https://user-images.githubusercontent.com/8658164/76417056-119c7f80-6394-11ea-9d5c-7d5008b6c3e5.png)|![Screenshot 2020-03-11 12 21 47](https://user-images.githubusercontent.com/8658164/76417062-13664300-6394-11ea-8251-8ae55ed63530.png)

WordPress.com site customizer — notice there is no border when the randomized headers are selected, so the only clue to the selection is in the "Current header" section:

Single header image|Randomized headers
-|-
![Screenshot 2020-03-11 12 21 53](https://user-images.githubusercontent.com/8658164/76417117-2da02100-6394-11ea-9970-ae3401a44174.png)|![Screenshot 2020-03-11 12 21 59](https://user-images.githubusercontent.com/8658164/76417123-2f69e480-6394-11ea-9db1-b551b27d8303.png)

WordPress.com site customizer on a mobile device screen size, with randomize suggested headers selected — notice there is no border when the randomized headers are selected, and the "Current header" section isn't visible on screen, so there is no indication that the selection did anything:

<img src="https://user-images.githubusercontent.com/8658164/76417208-5fb18300-6394-11ea-9f8a-4ce0aff45c17.png" width="50%">

#### Context / Source
Internal discussion: pbArwn-an-p2

**Comment by gwwar** [comment]
As an aside, @kwight or @sixhours is there any context on why we added extra styles on top of customizer? If there isn't a good reason, we could maybe try removing customizations.

**Comment by gwwar** [comment]
@rachelmcr which theme was this?

**Comment by kwight** [comment]
> As an aside, @kwight or @sixhours is there any context on why we added extra styles on top of customizer?

Pretty sure it was just the "make everything look like Calypso" phase of things.

**Comment by gwwar** [comment]
Added D40218-code that 🔪's the wpcom CSS customizations.

**Comment by elibud** [comment]
Thanks @gwwar!

**Comment by gwwar** [comment]
Should be closed by D40218

**Comment by lancewillett** [comment]
I love this change — removing yet another layer of unneeded abstraction.

When we fork core WordPress.org and it makes it worse. Cut! ✂️ 🔪
