### ISSUE TITLE
Domains: Confusing message on "Action required"

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#40067]
When helping a user in livechat earlier today I noticed that, for mapped domains requiring NS changes to point to WordPress.com, we say "Action required" on the domain page, but don't give the user any information on what that action is. In this case, the message should be related to changing NS, which we actually have a handy link on "Connect Your Domain", but there is no link between these two here ("Action required" and "Connect your domain").

![Screen Shot 2020-03-11 at 15 12 13](https://user-images.githubusercontent.com/31009008/76454333-dce7f280-63aa-11ea-87e5-ab881b1f03ca.png)

#### Steps to reproduce
1. Starting at URL: /domains/manage/
2. Click on the domain to be mapped
3. See the domain info and message "Action required"

note: this was on an atomic site.

#### What I expected
To have an actionable message to let me know what to do and what action is required.

#### What happened instead
No actionable info

#### Context / Source
#manual-testing

**Comment by klimeryk** [comment]
Good point, @davipontesblog! In the past we showed the domain warnings component there to give context to the alert, but not sure what's the expected behaviour with the new design. @hambai @fditrapani, could you have a look? 🙏

**Comment by fditrapani** [comment]
Thanks for the report @davipontesblog! We're taking a look into it.
