### ISSUE TITLE
Page Layouts: Remove or Replace Theme Name in Home Page Layouts

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#40069]
![image](https://user-images.githubusercontent.com/545779/76457332-96909480-63a6-11ea-9c7c-bae0c295af5e.png)

Via @davipontesblog it can be too easy to get confused here between the theme itself and the page layout. We've seen some users think they're switching themes here.

**Simple Fix:** Replace the theme name with "Home" or simply hide the theme name.

**Comment by ianstewart** [comment]
cc @alaczek @iamtakashi @boonerang

**Comment by kathrynwp** [comment]
+1 on the above. During Quick Start sessions, when explaining how the homepage layouts work, it's very awkward to have to explain, for example, that even though the "Dalston" layout has the same name as the theme "Dalston," choosing the "Dalston" layout is not actually switching their theme to "Dalston."

**Comment by obenland** [comment]
With the new page templates layout project in progess (pbAok1-1Rg-p2), can this one be closed?

**Comment by ianstewart** [comment]
Let's close this one out!
