### ISSUE TITLE
Editor: Permalink editing UI is different for Posts and Pages

### ISSUE THREAD

**Issue by hafizrahman** [Automattic/wp-calypso#4007]
The permalink editing in the Post editor looks like this, with the field hidden inside a `Popover`, and containing a "Copy" button:

![screen shot 2016-03-13 at 9 05 26 am](https://cloud.githubusercontent.com/assets/266376/13726478/929fc00a-e8fb-11e5-9927-9b5bf5fda9d1.png)

On the other hand, the Page editor's permalink editing is visible right away:

![screen shot 2016-03-13 at 9 08 39 am](https://cloud.githubusercontent.com/assets/266376/13726482/a57d5ab6-e8fb-11e5-8c41-e31dd1fc309f.png)

What is the reason for this difference?

I'm currently working on making the permalink UI keyboard-accessible in the Post editor (#3800), however the use of Popover makes it difficult to do so, because the Popover shows up at the end of the HTML, putting it out of the `tabindex` order.

If there's no functionality difference between the two, I'd suggest using the Page-style permalink UI for both. This will make keyboard-a11y easier to setup.

**Comment by aduth** [comment]
My understanding is that editing a slug is a much more common action for pages than it is for posts, which is why it's always visible only in that context.

/cc @mtias

**Comment by mtias** [comment]
Yes, this is intended and helps reinforce the structural difference between posts and pages. We use popovers pretty extensively anyways in the UI so finding a general solution for moving tab focus to popover would be good.

**Comment by hafizrahman** [comment]
That makes sense, thanks for the explanation @mtias and @aduth.
