### ISSUE TITLE
'Calculate ICFY stats' action randomly fails

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#40093]
The action seems to file randomly when installing dependencies. Examples:

https://github.com/Automattic/wp-calypso/runs/502882705
https://github.com/Automattic/wp-calypso/runs/502734158
https://github.com/Automattic/wp-calypso/runs/502307908
https://github.com/Automattic/wp-calypso/runs/501236923
https://github.com/Automattic/wp-calypso/runs/500709213

What we know so far:

- It fails when trying to read the content of a package that was just installed. Examples from different builds:

```
enoent ENOENT: no such file or directory, open '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/get-caller-file/package.json'
enoent ENOENT: no such file or directory, open '/home/runner/work/wp-calypso/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/package.json'
enoent ENOENT: no such file or directory, open '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/get-caller-file/package.json'
enoent ENOENT: no such file or directory, open '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/mimic-fn/package.json'
```

- Looks like dependencies of `npm-merge-driver` and `chokidar` are more prone to fail. This is the analysis from the last 15 builds failures related to this error:

```
   1 '/home/runner/work/wp-calypso/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/chownr/package.json'
   2 '/home/runner/work/wp-calypso/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/needle/package.json'
   2 '/home/runner/work/wp-calypso/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/package.json'
   1 '/home/runner/work/wp-calypso/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/readable-stream/package.json'
   1 '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/execa/package.json'
   4 '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/get-caller-file/package.json'
   2 '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/get-stream/package.json'
   1 '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/lru-cache/package.json'
   1 '/home/runner/work/wp-calypso/wp-calypso/node_modules/npm-merge-driver/node_modules/mimic-fn/package.json'
```

- In all cases, npm log shows the file being correctly extracted to the expected directory. There are no other errors in the npm file.

- It doesn't seem to be related to insufficient disk size. When tested locally with a restricted partition, npm shows a clear error saying there is not enough space.

**Comment by scinos** [comment]
I enabled extra logging (https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging) in https://github.com/Automattic/wp-calypso/runs/503693083?check_suite_focus=true, but there is nothing useful in the logs.

**Comment by frontdevde** [comment]
Just noting that I observed this issue as well in 
https://github.com/Automattic/wp-calypso/runs/548092352

**Comment by scinos** [comment]
I'm not finding more instances of this error.
Looks like this problem solved itself (thanks to the migration to yarn?).
