### ISSUE TITLE
Jetpack: Update website credentials screen during remote install flow

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#40091]
During the remote install flow, we ask customers to provide their "website credentials" (wordpress creds) so that we can auto install Jetpack for them. 

After doing an audit, @eeeeevon13 came up with some quick design improvements for hackweek to see if we can help people understand this screen a bit more clearly. 

**Current screen:**
<img width="890" alt="Screen Shot 2020-03-09 at 5 27 55 PM" src="https://user-images.githubusercontent.com/214813/76532010-66033600-644c-11ea-9a45-4bfc51335dee.png">

**Proposed changes:**
![Screen Shot 2020-03-12 at 10 30 16 AM](https://user-images.githubusercontent.com/214813/76532085-803d1400-644c-11ea-9e00-3f6a3893ad1f.png)

**List of items to update:**
* Headline update: "Add your WordPress credentials (wp-admin)"
* Sub-head update: "Your log in credentials are used for the purpose of securely auto-installing Jetpack and will not be stored."
* Add site title + URL card (is this possible? During the step before this screen we request their URL)
* Add WordPress logo
* Change form labels to read: "WordPress username or email" and "WordPress password"

We won't be making any style changes here, so if the live components visually appear a little different than my mockup, that's okay. 

cc @keoshi @folletto

**Comment by keoshi** [comment]
Love it, ship it!

**Comment by enejb** [comment]
Looking at the implementable of this. 

It might be really hard to get site info such as site name and icon just by using the URL. 
Before installing jetpack is installed.

**Comment by roccotripaldi** [comment]
Does this happen during the connection flow?

**Comment by jeffgolenski** [comment]
@enejb @roccotripaldi This takes place during the remote install connection flow. Mainly from Jetpack.com (click get started). The step right before this, we ask the customer for their site URL. Details can be seen here: p6TEKc-3fd

If we can't grab that info at this point that's totally fine. The main concerns of this issue are to update the language and get the WP logo in there.
