### ISSUE TITLE
iOS: Chrome Mobile -- App locks up & eventually errors out

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#4010]
#### Steps to reproduce
1. On a physical iOS device, launch the release version of the Chrome browser (from the App Store) 
2. Navigate to "wordpress.com"
3. If you are not logged in, either continue to the signup flow or log in.

#### What I expected
* If you are logged in, the Reader should load & be interactive
* If I'm logged out:
  * The signup flow should work
  * After logging in, the reader should load & be interactive

#### What happened instead
* Logged in: The Reader starts to load, but nothing is clickable, the placeholder components never populate (or only partially populate), but I'm able to scroll up and down:
![img_6830](https://cloud.githubusercontent.com/assets/1587282/13730545/1bb73b5e-e94a-11e5-982e-eaf433340f36.PNG)

After some timeout period, the tab crashes:
![img_6831](https://cloud.githubusercontent.com/assets/1587282/13730546/21912dbe-e94a-11e5-838a-422a27b8badf.PNG)

* Logged out: The signup flow hangs in a similar fashion. Sometimes, flows partially load, but they're not clickable & images get cut off:
![img_6832](https://cloud.githubusercontent.com/assets/1587282/13730610/8df97294-e94b-11e5-8872-c6085d2cbf28.PNG)

#### Browser / OS version
Chrome 49.0.2623.73 (up-to-date App Store version) (according to @mattsherman, the issue is also present in Firefox)
iOS 9.2.1 (latest non-beta)

Tested on an iPhone 6 & 6s

Interestingly, @shaunandrews tested Chrome in the iOS 9.3 beta & the app was usable, but it eventually threw the "Aw Snap" error.

---
I tried to troubleshoot this further with local proxying tools, running calypso locally, etc., but didn't get very far.

**Comment by mattsherman** [comment]
I was also able to reproduce this on an iPad Air 2 running iOS 9.2.1 in Chrome 49.0.2623.73 and Firefox 2.1 (4) (latest versions from App Store)

**Comment by timmyc** [comment]
Verified broken for me too.  @jblz are you a frequent ios chrome + calypso user?  If so it might be nice to know when this exactly started breaking to track down a cause.  Debugging chrome on mobile safari is _fun_

**Comment by jblz** [comment]
@timmyc fairly frequent. I first noticed it on March 10. I can't remember when I tried it previously, but do not remember the issue prior.

> Debugging chrome on mobile safari is _fun_

Ya, I tried using [ghostlab](www.vanamco.com/ghostlab/) on @shaunandrews' reco, but it didn't really get me very far.

It _feels_ like an infinite loop.
