### ISSUE TITLE
Plans: Plan descriptions should use sentence case for their bolded text.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#40107]
[Reported](https://github.com/Automattic/wp-calypso/pull/40101#issuecomment-598461584) by @jancavan :

According to p9Jlb4-1ly-p2, we should use sentence case for plan description leading text (the title-like text in bold). These can be found at `/plans`.

<img width="1110" alt="Screen Shot 2020-03-12 at 5 14 59 PM" src="https://user-images.githubusercontent.com/349751/76578186-18ef8600-6485-11ea-83fe-b44e2b1f4e4e.png">

**Comment by jancavan** [comment]
Thanks for fixing this @kwight!
