### ISSUE TITLE
My Home: When editor preference is set to classic we create a new page instead of editing homepage

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40108]
With an user account created before December 16, 2019, click on "Switch to Classic Editor"
<img width="368" alt="screen-shot-2019-07-08-at-11 34 58-am" src="https://user-images.githubusercontent.com/1270189/76578880-5ce38a80-6487-11ea-8b73-f74a32c9385b.png">

Then visit the My Home section at WordPress.com

<img width="719" alt="Screen Shot 2020-03-12 at 5 27 55 PM" src="https://user-images.githubusercontent.com/1270189/76578826-10984a80-6487-11ea-8a4d-31f7afcdc369.png">

Expected: Clicking on Edit Homepage edits the homepage in the block-editor
Actual: We create a new page in the Calypso Classic Editor

**It'd probably make sense to not display the "Edit Homepage" link here when classic is set as a preference. We can display write blog post/add a page instead:**

<img width="696" alt="Screen Shot 2020-03-12 at 5 33 55 PM" src="https://user-images.githubusercontent.com/1270189/76578960-b481f600-6487-11ea-8c16-3c96c2d0727d.png">

**Comment by lancewillett** [comment]
> It'd probably make sense to not display the "Edit Homepage" link here when classic is set as a preference.

👍 to this suggestion.
