### ISSUE TITLE
Buttons: More sentence casing of labels

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#40120]
As a followup to #39692 I noticed a few stray Title Casing on button labels. Let's track those down and make them Sentence case.

**My Home:** `View Site`
<img width="140" alt="Screen Shot 2020-03-13 at 9 41 45 AM" src="https://user-images.githubusercontent.com/448298/76626887-564d2580-6510-11ea-8bec-e4839e0a89fa.png">

**Domain contact info:** `Save Contact Info`
<img width="189" alt="Screen Shot 2020-03-13 at 9 43 01 AM" src="https://user-images.githubusercontent.com/448298/76626918-695ff580-6510-11ea-8cb1-cbb6277144dd.png">

**Domain contact info:** `Edit Contact Info`
![image](https://user-images.githubusercontent.com/448298/76627001-8f859580-6510-11ea-8ca9-93aa07212d1a.png)

**Domain transfer to another user:** `Transfer Domain`
<img width="762" alt="Screen Shot 2020-03-13 at 9 43 39 AM" src="https://user-images.githubusercontent.com/448298/76627056-a75d1980-6510-11ea-9315-3b7906488bc7.png">

**Domain transfer:** `Update Settings and Continue`
<img width="754" alt="Screen Shot 2020-03-13 at 9 43 46 AM" src="https://user-images.githubusercontent.com/448298/76627105-c22f8e00-6510-11ea-8096-ce4963ab9314.png">

**Cart dropdown on Domains and Plans:** `Add a Plan`
<img width="395" alt="Screen Shot 2020-03-13 at 9 43 59 AM" src="https://user-images.githubusercontent.com/448298/76627147-da9fa880-6510-11ea-912f-e9494f832e40.png">

**Earn section:** `Earn Free Credits`
<img width="529" alt="Screen Shot 2020-03-13 at 9 46 32 AM" src="https://user-images.githubusercontent.com/448298/76627217-fdca5800-6510-11ea-91de-60cc1f81af62.png">

**People > Invites > Invite Details:** `Clear Invite`
<img width="617" alt="Screen Shot 2020-03-13 at 9 47 29 AM" src="https://user-images.githubusercontent.com/448298/76627243-0ae74700-6511-11ea-901d-7454e47cf92a.png">

**Comment by tbradsha** [comment]
**Manage → Settings → Delete Site**:
![image](https://user-images.githubusercontent.com/32492176/76683644-5a8a4900-65cb-11ea-896a-721eae9cd1e2.png)

and then clicking the "Delete Site" button:
![image](https://user-images.githubusercontent.com/32492176/76683626-362e6c80-65cb-11ea-9565-d18a7d0ecb23.png)

**Comment by tbradsha** [comment]
In **Site → Posts** in Calypso:

![image](https://user-images.githubusercontent.com/32492176/76984300-3f3d7780-6904-11ea-892e-86c09bf1460f.png)

**Comment by danhauk** [comment]
Thanks @tbradsha! The labels for Posts and Custom Post Types are handled on the back-end and there's currently a patch / conversation with core in progress about that. Those will be updated when the back-end patches land.
