### ISSUE TITLE
People: Fallback to URL when site title blank

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#4012]
#### Steps to reproduce
1. Starting at URL: `people/new/{site}`
2. Add a user to a site that doesn't have a site title

#### What I expected
I expected we would fall back to the site URL rather than leaving the field blank.

#### What happened instead
Blank fields occur in three areas:

The email invite:

![screen shot 2016-03-13 at 4 32 15 pm](https://cloud.githubusercontent.com/assets/7240478/13731850/5cac97b4-e939-11e5-80b3-5ff0146511d5.png)

The accept dialogue ("Would you like to become a follower of ?"):

![screen shot 2016-03-13 at 4 29 04 pm](https://cloud.githubusercontent.com/assets/7240478/13731853/696e1d92-e939-11e5-9547-859edc417ecb.png)

The success message:

![screen shot 2016-03-13 at 4 34 18 pm](https://cloud.githubusercontent.com/assets/7240478/13731857/7641d07c-e939-11e5-9e92-44d91ec24702.png)

#### Browser / OS version
Chrome 49.0.2623.87

A bit of an edge case, but still definitely possible.

**Comment by v18** [comment]
I was able to reproduce, and I noticed that the site title is also missing from the subject line of the email, and the success email for user roles (not followers):

![screen shot 2016-03-15 at 9 37 25 am](https://cloud.githubusercontent.com/assets/11487924/13779487/94c02efa-ea91-11e5-93a4-6d7bc84c5d7a.png)

**Comment by ebinnion** [comment]
Fixed in r132697-wpcom.
