### ISSUE TITLE
Gutenboarding: adjustments to the header

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40138]
Text should initially say "Start your website":

<img width="312" alt="Screenshot 2020-03-13 at 23 04 29" src="https://user-images.githubusercontent.com/87168/76659451-2852fa00-657f-11ea-8265-1f7b3dd8adac.png">

Once site title is there, domain and title should be next to each other, not over each other (ignore the color here):

<img width="465" alt="Screenshot 2020-03-13 at 23 04 53" src="https://user-images.githubusercontent.com/87168/76659478-399c0680-657f-11ea-89b7-f35b1b827b60.png">

Note also domain picker saying "[premiumdomain] is available"

The W logo should also be 24*24 px.

**Comment by chriskmnds** [comment]
Ok to add to this the "Create my site" button removal in the site preview step? It's "moved" to the main section in the designs. We talked about this with @sirreal in a call earlier.

**Current:**

<img width="1258" alt="Screenshot 2020-03-16 at 2 16 00 PM" src="https://user-images.githubusercontent.com/1705499/76758237-f9f93880-6791-11ea-85ae-76b790a41707.png">


**Figma:**

<img width="915" alt="Screenshot 2020-03-16 at 2 16 14 PM" src="https://user-images.githubusercontent.com/1705499/76758247-fd8cbf80-6791-11ea-94f2-9f963905373d.png">

**Comment by simison** [comment]
@chriskmnds  Oh ye, good point:

- "Create my site" button should be hidden when the "continue" button in style picker is visible 
- Style picker is behind `gutenboarding/style-preview` feature flag until it's more ready, so let's not completely remove that button; only when the feature flag is not set.

**Comment by chriskmnds** [comment]
> @chriskmnds Oh ye, good point:
> 
> * "Create my site" button should be hidden when the "continue" button in style picker is visible
> * Style picker is behind `gutenboarding/style-preview` feature flag until it's more ready, so let's not completely remove that button; only when the feature flag is not set.

gotcha. thanks for clarifying.

**Comment by sirreal** [comment]
I suggested moving the create my site button into the design picker step when the feature flag is disabled. This gets us closer to aligning with designs.

**Comment by simison** [comment]
That works too 👍
