### ISSUE TITLE
Gutenboarding: add arrows to intent gather sentences

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40142]
In `/gutenboarding` at intent-gather step, we should add arrows to the sentences as user starts filling the fields:

<img width="820" alt="Screenshot 2020-03-14 at 00 16 48" src="https://user-images.githubusercontent.com/87168/76663302-3f96e500-6589-11ea-95c7-e12c7354dbe0.png">
<img width="816" alt="Screenshot 2020-03-14 at 00 16 37" src="https://user-images.githubusercontent.com/87168/76663308-40c81200-6589-11ea-8ec9-8b6ad932c23e.png">

Not sure if this is ASCII arrow `→` or an SVG.

See the prototype for behavior (pbAok1-sr-p2)

**Comment by yansern** [comment]
Okay this looks simple but actually it is not.

The input field needs to expand according to the width of the input content.

![image](https://user-images.githubusercontent.com/1287077/76744446-38e9b700-67af-11ea-960d-271ca0b958be.png)

In the Figma prototype, it is doing the calculation.

![image](https://user-images.githubusercontent.com/1287077/76744498-4606a600-67af-11ea-948c-dcd3604067f3.png)

**Comment by yansern** [comment]
> Not sure if this is ASCII arrow → or an SVG.

Figma prototype uses an SVG. Changing the SVG stroke to `inherit` or `currentColor`, it does not inherit the text color from HTML. Since our verticals have different text color, we may have to use ASCII arrows instead.

![image](https://user-images.githubusercontent.com/1287077/76745035-2328c180-67b0-11ea-95d3-1e37cd613099.png)

**Comment by simison** [comment]
@yansern removing the inline `stroke` and moving it to CSS might do the trick.

Alternatively, the SVG can be reformatted to a shape that can use `fill` color instead.

**Comment by simison** [comment]
>The input field needs to expand according to the width of the input content.

Would it work to have the field as `display: inline;`?

**Comment by yansern** [comment]
>> The input field needs to expand according to the width of the input content.
>
> Would it work to have the field as `display: inline;`?

`display: inline` doesn't work on input fields. They render based on a given width OR if not width given, they follow the `size` attribute.

**Comment by yansern** [comment]
>> @yansern removing the inline `stroke` and moving it to CSS might do the trick.
>
> Alternatively, the SVG can be reformatted to a shape that can use `fill` color instead.

Thanks for the tip! I think if the CSS trick doesn't work, then the SVG can be reformatted into a shape. "Expand Appearance" in Adobe Illustrator. Lol.

**Comment by simison** [comment]
>display: inline doesn't work on input fields. They render based on a given width OR if no width given, they follow the size attribute.

Would `<div contenteditable="true"></div>` work in this scenario better?

**Comment by yansern** [comment]
>> display: inline doesn't work on input fields. They render based on a given width OR if no width given, they follow the size attribute.
>
> Would <div contenteditable="true"></div> work in this scenario better?

Yes, it will work with multi-line too. I was afraid of the eventual decision to go `contenteditable`, it will solve some issues, but I'm sure it will introduce other issues, like pasting of text might inherit all the rich text formatting, unless it is sanitized post-paste. 

Both `input` and `contenteditable` does not solve the issue how to display the vertical suggestions in spinner style though, but let's not go there lol.

**Comment by simison** [comment]
Yeah, hassle isn't necessarily worth the arrow, but feels like it's important to make the field work otherwise well for longer texts and especially later in smaller screens.

**Comment by yansern** [comment]
Plain text contenteditable. 

This only deals with pasting.
https://stackoverflow.com/questions/34764304/contenteditable-allowing-only-plain-text

This mentions the need to listen to also other events but suggests using mutation events instead. 
https://medium.com/@albertogasparin/getting-plain-text-from-user-input-on-a-contenteditable-element-b711aba2cb36

**Comment by yansern** [comment]
> Yeah, hassle isn't necessarily worth the arrow, but feels like it's important to make the field work otherwise well for longer texts and especially later in smaller screens.

It might be interesting to experiment with plain text contenteditable input, it could be turned into a reusable component. I just want to make sure that we all agree on this, and that we quickly climb out from the rabbit hole if the unknown problems that comes with contenteditable might be too messy to work with.

**Comment by simison** [comment]
Another idea, use rich text component from core:

```jsx
import { RichText } from '@wordpress/block-editor';

<RichText
	allowedFormats={ [] }
	aria-label={ label }
	autoComplete="off"
	className={ inputClass }
	onBlur={ handleBlur }
	onChange={ handleSuggestionChangeEvent }
	onKeyDown={ handleSuggestionKeyDown }
	placeholder=""
	ref={ inputRef }
	value={ inputValue }
	withoutInteractiveFormatting
/>
```

**Comment by dubielzyk** [comment]
Might be relevant, but I'm using a npm package called [react-input-autosize](https://www.npmjs.com/package/react-input-autosize) so that the arrow stays in place. I start the input  field off at 300 width to make it easy to select, then have the auto sizing do it's magic.

**Comment by razvanpapadopol** [comment]
Arrows will be introduced in https://github.com/Automattic/wp-calypso/pull/40442 and I've added the width issue in #40321 so we can mark the current issue as Done.
