### ISSUE TITLE
Premium Themes: update references to exact number of themes available for WordPress.com sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#40152]
With a changing and dynamic collection of themes let's avoid exact hard-coded numbers.

> “In addition to more than 100 premium themes, ”

> “Upgrade to the Premium plan and access over 250 premium themes for just…”

> “250 high-end designs”

> “197 Premium Themes”

Using instead words that indicate a collection and group instead of precise numbers.

Context:

1. The number changes often enough that it's difficult to maintain accuracy
2. In March 2020 we're in the process of cleaning up older themes, adding Gutenberg support, and the number changed (minus 100+) as we process the cleanup
3. We can provide equally inspirational and descriptive labels without the exact number — even with a future large number

**Comment by lancewillett** [comment]
Contributors — if you come across more references like this in the future that we might miss in this sweep, feel welcome to create new pull requests.

**Comment by Aurorum** [comment]
@lancewillett I remember there being one more, but I'm not sure where (or even if) it's used. I opened a PR for it in #40155
