### ISSUE TITLE
Gutenboarding: prefill search input in domain picker

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40159]
Prefill search input with the actual search term used (site title) in the domain picker:

<img width="400" alt="Screenshot 2020-03-16 at 10 04 49" src="https://user-images.githubusercontent.com/87168/76735522-b4c30f80-676d-11ea-95f7-65cde664ad01.png">

Currently it's empty:

<img width="300" alt="Screenshot 2020-03-16 at 09 53 25" src="https://user-images.githubusercontent.com/87168/76735527-bab8f080-676d-11ea-968e-c1e428128658.png">

**Comment by yansern** [comment]
https://github.com/Automattic/wp-calypso/pull/40166
