### ISSUE TITLE
Incorrect letter case on phpMyAdmin button in French

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#40169]
If one's Calypso interface is in French (perhaps others as well), the "Open phpMyAdmin" button looks like this:

![image](https://user-images.githubusercontent.com/32492176/76768607-dcf84180-6760-11ea-8846-e93ef49b04ee.png)

Instead of `PHPMyAdmin`, it should be `phpMyAdmin`. Somewhat related to #40120, but more of a typo.

**Comment by kriskarkoski** [comment]
Submitted a correction to this from https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=258483&filters%5Btranslation_id%5D=8197481. Closing.
