### ISSUE TITLE
Gutenboarding: restyle domain picker dropdown

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40163]
Restyle domain picker according to the new design:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/87168/76748317-3709fe80-6783-11ea-9e06-8562ee450f20.png">

Notable:
- Paid domain separately
- The whole row is clickable, note also hover state
- "Skip for now" just closes the dropdown
- "More options" will open a domain with more domain options (can be left out or behind a feature flag for now)
- Free subdomain separately

Currently (sorry for Finnish translations in the screenshot):

<img width="355" alt="image" src="https://user-images.githubusercontent.com/87168/76748343-41c49380-6783-11ea-8d7b-66f896e59820.png">

context pbAok1-sr-p2

**Comment by yansern** [comment]
I used the wrong issue number for the #40166 PR. Ignore the previous mention.
