### ISSUE TITLE
Gutenboarding: refine UI for the style picker step

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40160]
**Now:**

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/87168/76745496-9ca7bc00-677e-11ea-8eb4-601d1b4eb893.png">

**Goal:**

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/87168/76745521-ab8e6e80-677e-11ea-8f79-c3651ce1b16a.png">

Let's build (could each be their own PRs):
- [x] Browser chrome and sizing for the preview (@sirreal https://github.com/Automattic/wp-calypso/pull/40290)
- [x] Spacing around elements (@sirreal #40297)
- [ ] Font picker (@sirreal #40227)

Context pbAok1-sr-p2

**Comment by simison** [comment]
Note also moving "create my site" button from the header to the content area (https://github.com/Automattic/wp-calypso/issues/40138#issuecomment-599508709)

**Comment by joanrho** [comment]
@simison Let's keep the "Create my site" CTA like in the prototype. Thanks!

**Comment by chriskmnds** [comment]
Updated to say "spacing around elements" instead for the second TODO, as we are dealing with the header elsewhere (https://github.com/Automattic/wp-calypso/issues/40138)

**Comment by sirreal** [comment]
> * [ ]  Browser chrome for the preview

This is partially complete already:

![Screen Shot 2020-03-19 at 15 39 45](https://user-images.githubusercontent.com/841763/77079165-e18a5780-69f7-11ea-9a94-2bd36362981a.png)

It needs to respond to changes to the selected viewport. Mobile has different chrome.
![Screen Shot 2020-03-19 at 15 42 48](https://user-images.githubusercontent.com/841763/77079411-5067b080-69f8-11ea-883d-e66a3d59f158.png)
![Screen Shot 2020-03-19 at 15 42 35](https://user-images.githubusercontent.com/841763/77079422-5362a100-69f8-11ea-9b54-1400624f8e59.png)

**Comment by sirreal** [comment]
@dubielzyk Is there different chrome for the tablet viewport, or should we reuse the desktop or mobile chrome?

**Comment by dubielzyk** [comment]
Same chrome. Desktop view has the three system controls in the top left. I just hid them on mobile and tablet.

**Comment by sirreal** [comment]
> Same chrome. Desktop view has the three system controls in the top left. I just hid them on mobile and tablet.

Could you take a look at the screenshots in #40290 and let us know what chrome needs to be changed?

**Comment by dubielzyk** [comment]
Looks good to me from the screenshot. I'd half the opacity of the drop-shadow though. I't s a bit dark at the moment. But I can do a PR later if you want.

**Comment by sirreal** [comment]
> Looks good to me from the screenshot. I'd half the opacity of the drop-shadow though. I't s a bit dark at the moment. But I can do a PR later if you want.

Awesome, thanks! I noticed that desktop and mobile had different alpha in the figma, `.25` and `.14` respectively, which is how they're currently set.

A PR would be 💯  thanks!

**Comment by sirreal** [comment]
Noting that the buttons will move in https://github.com/Automattic/wp-calypso/issues/40241 and #40227 will land the font changes imminently.

I'll close this now, we can open new issues for any other changes.
