### ISSUE TITLE
Plans: Add nudge on Plan Overview page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#4017]
We should add a nudge on the `Plan Overview` page (also known as _trial hub_) to highlight the discount users can get from purchasing a plan when they already have purchased a domain mapping or a domain registration. This nudge should only be displayed within five days from free trial expiration:

![screenshot](https://cloud.githubusercontent.com/assets/594356/13742731/c75ddfc4-e9dd-11e5-8e93-42c8af9c2985.png)

**Comment by stephanethomas** [comment]
@breezyskies, @mikeshelton1503 : could you confirm that this nudge will only be displayed from 5 to 1 day before expiration? As you can see below the main progress bar indeed never goes yellow (it's either blue or red) and there is a red notice when the trial had expired:

#### 13 Days Remaining

![13 days remaining](https://cloud.githubusercontent.com/assets/594356/13742783/491f3a1c-e9de-11e5-977d-59df6b6806cd.png)

#### 5 Days Remaining

![5 days remaining](https://cloud.githubusercontent.com/assets/594356/13742787/4c3319b2-e9de-11e5-9cb4-796bb969c60a.png)

#### Expired Today

![expired today](https://cloud.githubusercontent.com/assets/594356/13742791/50cf0684-e9de-11e5-976e-483c00e7b11f.png)

#### Expired 3 Days Ago

![expired 3 days ago](https://cloud.githubusercontent.com/assets/594356/13742795/54e9191c-e9de-11e5-9742-21dd244c32ec.png)

**Comment by breezyskies** [comment]
> could you confirm that this nudge will only be displayed from 5 to 1 day before expiration?

Mike and I discussed and think we should show it throughout the entire trial.

**Comment by stephanethomas** [comment]
Does it mean from day 0 to day 14? Or should we also display this nudge during the grace period (i.e. from day 0 to day 17)? As mentioned above the problem with the latter is that we already display a red notice at the same place when the trial has expired.

**Comment by breezyskies** [comment]
For the full 17 days. The red notice can go below the nudge.
