### ISSUE TITLE
Editor's Notes Block: Content not being saved on drafts or when publishing

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#40173]
The _Editor's Notes Block_ (p4TIVU-93E-p2) currently loads in the editor and allows content to be added, but when the post/page/reusable block is added to gets saved or published, the content of the block is not preserved.

**To Reproduce:**
- Create a new post, page, or reusable block.
- Add content, including at least one Editor's Notes block.
- In that block add some text.
- Save or publish your content.
- Exit the editor, and view your content. The Editor's Notes will not be visible on the front end, as expected. In the case of a Reusable Block, the Editor's Notes block will load, but without any content.
- Return to the editor. The Editor's Notes block is still present, but empty.

I tested this on posts, pages, and reusable blocks, both with auto and manual saves on drafts as well as published content and found the content missing across the board.

I first noticed this on a Reusable Block I was setting up as a template for recurring posts, and wanted to include instructions.

**Comment by lancewillett** [comment]
@chad1008 Bonus point for longest issue title, ever (joking with you). 😄

**Comment by chad1008** [comment]
Thanks @lancewillett. The second I saw it I said "ugh, there is... just no way to make that disappear. here we go..."  🤦‍♂️

**Comment by lancewillett** [comment]
It's logged in all-time history now. You might as well own it. 🏆

**Comment by sirreal** [comment]
Confirmed, notes are lost: p3hyOA-3dg-p2

Likely mismatch in the attribute type (string/array):

https://github.com/Automattic/wp-calypso/blob/58fe36dfb0c3af38f45986f745a13b6885a785e7/apps/o2-blocks/src/editor-notes/editor.js#L9-L13

**Comment by sirreal** [comment]
Fixed in Fixed in r214977-wpcom
