### ISSUE TITLE
Domains: Action buttons have inconsistent styling at narrow widths.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#40182]
Action buttons on the Domain Settings view can have inconsistent text alignment and poor layout. This screenshot is at a width of about 800px.

<img width="563" alt="Screen Shot 2020-03-16 at 1 07 01 PM" src="https://user-images.githubusercontent.com/349751/76795842-6a4e8c80-6787-11ea-8c0d-2241d8399d8d.png">

**Comment by klimeryk** [comment]
Thanks for reporting!

cc @hambai @fditrapani, can you triage this when you have the time? 🙏

**Comment by fditrapani** [comment]
Will do. Thanks everyone!
