### ISSUE TITLE
Sidebar Notice: Upsell with 2-lines misaligned after navigating between pages

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#40186]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/
2. Make sure you have a site with a domain
3. On the sidebar, you should see an upsell for a second domain which is displayed correctly:
![Screen Shot 2020-03-16 at 2 27 02 PM](https://user-images.githubusercontent.com/4924246/76801304-9d4a4d80-6792-11ea-8c97-62704bf63ae4.png)

4. But once you navigate between different pages in Calypso, notice how the text/button get misaligned like so. Sometimes, it also happens randomly, but I have been able to reproduce it this way:

![Screen Shot 2020-03-16 at 2 27 12 PM](https://user-images.githubusercontent.com/4924246/76801335-adfac380-6792-11ea-8bce-b249d0a7d8af.png)

#### Browser / OS version
Mac OS Mojave 10.14.6
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)

Another thing - I think these domain suggestions should have a dot in them? In my example, I think it should be a `.ca` instead of just `ca`?

cc @sixhours

**Comment by sixhours** [comment]
I haven't been able to reproduce this one, but I can't get this notice to appear unless I force it in the code, so it's possible whatever causes it is part of the code I have to remove.

The next time you see it, could you check the console to see if there's any errors? Or check the Network tab to see if anything is not loading/stalled? I'm wondering if a stylesheet isn't getting processed correctly. I'll also try to find a way to reproduce it in the meantime.

**Comment by sixhours** [comment]
I added myself as a user to the beanscookies.dog site and still could not reproduce this one. :-\  It seems similar to #40060 in that it's probably related to CSS, and elements in both cases use flexbox. But that issue is specific to Safari, and this one was found in Chrome.

**Comment by jancavan** [comment]
@sixhours I actually saw this again yesterday on a different site. I'll see if I can repro again.

**Comment by lcollette** [comment]
Is this one still in progress, @jancavan?

**Comment by jancavan** [comment]
I haven't been able to repro again. Let's close this one out, and if it pops back up, I can just reopen.
