### ISSUE TITLE
Domains: price displayed for free .blog subdomain URLs

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#40198]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/start
2. Signup for a new account, and in the domain step, search for a domain with `.wordpress` as tld - e.g. `davephoto.wordress`, or `davedesign.wordress`

#### What happened

.blog subdomain suggestions were shown with a product price and renewal price

#### What I expected

.blog subdomain suggestions to be free.

#### Context / Source
This issue feels like an edge case, but nevertheless thought it might be worth documenting. 
I was searching for a *.wordpress.com domain by typing out the fully qualified domain name. By chance, I waited a few seconds before typing out the .com part of wordpress.com, and the search fired. That's how I came upon this issue. 

#### Screenshot / Video

<img width="350" alt="Screenshot 2020-03-17 at 10 13 35 AM" src="https://user-images.githubusercontent.com/1269602/76823152-52cfdc00-6839-11ea-8cde-0bbbbe0b487e.png">

<img width="350" alt="Screenshot 2020-03-17 at 10 13 49 AM" src="https://user-images.githubusercontent.com/1269602/76823160-58c5bd00-6839-11ea-98db-611c54e2ff06.png">

**Comment by lancewillett** [comment]
CC @Automattic/cobalt for triage.

**Comment by klimeryk** [comment]
@eltongo what were the results of your investigation?

**Comment by eltongo** [comment]
The endpoint is called correctly, but there's a bug on the backend with how blacklisted terms are handled, which I'm working on.

**Comment by klimeryk** [comment]
Patch pending review here: D40562-code.
