### ISSUE TITLE
Jetpack: broken display with visible JavaScript snippet while trying to activate VaultPress

### ISSUE THREAD

**Issue by emrikol** [Automattic/wp-calypso#40194]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/plugins/setup/example.com?only=scan

#### What I expected

I expected to go through the VaultPress install flow and get it set up

#### What happened instead

Instead, I got some broken JavaScript :)

#### Browser / OS version

FireFox 74.0 / macOS 10.15.3 (19D76)

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/3060583/76809891-a6eba980-67c2-11ea-8dd1-5d9ce9dbdff6.png)

#### Context / Source

May be, or may not be related to https://github.com/Automattic/wp-calypso/pull/39490

**Comment by lancewillett** [comment]
Good eye @emrikol — CC @tyxla in case it is related to a recent refactor.

**Comment by tyxla** [comment]
Ouch, good catch! Seems like a bad rebase caused this. Fixing right away.

**Comment by tyxla** [comment]
Fix is in #40216, would appreciate a review, thanks a lot @emrikol and @lancewillett!
