### ISSUE TITLE
Calypso on mobile view: Chat window takes bigger width than mobile screen size (portrait mode)

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#40199]
#### Steps to reproduce

1. Open WordPress.com on mobile browser (I use Safari)
2. Click the '?' icon on the corner to contact Support team
3. Pop-up module appeared. If you have more than one website, you will be prompted to choose which website you want to inquire/receive support
4. Enter live chat support
5. At this point, the chat window is still within the screen size (portrait mode)
6. Send message to Support team. You will notice the chat window gets wider and you need to side-scroll to see the whole message.

#### What I expected
The chat screen stays within the phone's width (portrait mode, at minimum) without the need to side-scrolling.

![expected](https://cldup.com/LmaGy8y_v8.jpeg)
*Direct link: https://cldup.com/LmaGy8y_v8.jpeg*

#### What happened instead
The chat window will get wider and caused side-scroll

#### Browser / OS version
Safari (iOS 13.3.1)

#### Screenshot / Video

![screenshot](https://cldup.com/Rnm6_L0BDK.jpeg)
*Direct link: https://cldup.com/Rnm6_L0BDK.jpeg*

![screenshot](https://cldup.com/ckix_hy4sT.jpeg)
*Direct link: https://cldup.com/ckix_hy4sT.jpeg*

#### Context / Source

A WordPress.com user reached out and shared this insight with me; I checked it by entering live chat using my account and I found the same issue of side-scrolling.

**Comment by lancewillett** [comment]
Thanks for the report! Adding to the Manage team board for consideration.

**Comment by retnonindya** [comment]
Thank you, Lance! I really appreciate you checking on this 🙏

**Comment by davemart-in** [comment]
Passing this first to Manage design for consideration for how to handle this before triaging it.

**Comment by cpapazoglou** [comment]
That's the usual behavior in IOS when `font-size < 16px` for the focused field. It zooms in the whole page assuming that any `font-size < 16px` is not legible enough. 

Probably changing 
https://github.com/Automattic/wp-calypso/blob/7fcaec0432d9d76c548f2fe998025d691a7f79ea/client/components/happychat/composer.scss#L22

to `$font-body` which results to `16px` will resolve the issue.

Reserved for onboarding.
