### ISSUE TITLE
Next post button to load post from a same category

### ISSUE THREAD

**Issue by blazevivan** [Automattic/wp-calypso#40208]
#### Steps to reproduce
Related posts or Next/Previous buttons under a Blog post will load post based on a published date. 

#### What can happen instead
We can have a Block that can be added at the end of the post, that will load Next or Previous post from the same category only.

**Comment by lancewillett** [comment]
One method to solve this today, already available, would be to use Posts List block with a category filter. That would pull in a short list of posts by category, and you could set the number to 1.

<img width="421" alt="Screen Shot 2020-03-17 at 13 57 43" src="https://user-images.githubusercontent.com/66797/76900846-5bcfa600-6857-11ea-92ba-76f1634a11e5.png">

<img width="286" alt="Screen Shot 2020-03-17 at 13 58 10" src="https://user-images.githubusercontent.com/66797/76900851-5e320000-6857-11ea-870e-a7ba3b6fe2a1.png">

@blazevivan Want to try this method and see if it works for you?

**Comment by lancewillett** [comment]
Try it with the Latest Posts block, too.

<img width="298" alt="Screen Shot 2020-03-17 at 13 59 13" src="https://user-images.githubusercontent.com/66797/76900941-8883bd80-6857-11ea-970a-363dd8e67970.png">

**Comment by lancewillett** [comment]
I'm closing for now as the result you suggested is achievable with current blocks. Please re-open if you want to suggest new functionality we can't achieve today.
