### ISSUE TITLE
Gutenboarding: Establish verticalized color theme pattern

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40201]
The verticalized colors in Gutenboarding are implemented as some CSS variables applied near the Gutenboarding root. This pattern will not play well with values that come from an API and need to be manipulated and set via JavaScript.

This is likely a good fit for emotion themes, the component styling library already in use.
https://emotion.sh/docs/theming

Explore this option and transition to use emotion themes.

**Comment by simison** [comment]
@Automattic/gutenboarding-design can we get confirmation about the use of verticalized color in the UI for Gutenboarding?

I know there was talking about possibly not using it outside background color in the intent capture step.

**Comment by simison** [comment]
Confirmed, colors are used throughout the UI. 👍 

via p1584614184169300-slack-luna

**Comment by simison** [comment]
Some comments via Slack:

@sirreal :
> Regarding the vertical color themes, I don’t think we should rush it. It will make a mess of things.
>
> the verticals in JS, setting a DOM attribute, styling via CSS attribute selector matching, and using a few css custom properties that aren’t well defined.
Right now it’s pretty much limited to intent gathering step. Before we smear that mess across the whole flow and component hierarchy, I’d like us to understand what we’re doing.

@razvanpapadopol :
> I think it’s just a small override we need to remove that was adding design picker and style picker as exceptions

I think it's worth getting simple first version for CfT — this feature has been dividing opinions so there's real change that it gets pulled out. So investing too much upfront and then pulling it out would be a great pity.
