### ISSUE TITLE
Errors: getting errors while starting the project for the first time using "npm start"

### ISSUE THREAD

**Issue by AdnanAfsari** [Automattic/wp-calypso#40204]
#### Steps to reproduce

I tried to run the app with the matching  Node.js and  NPM versions listed in the "engines" section of package.json but I am getting those errors below.

#### Browser / OS version
macOS Catalina/ version 10.15.3 
#### Screenshot / Video

<img width="833" alt="Screenshot 2020-03-17 at 5 26 43 PM" src="https://user-images.githubusercontent.com/8613710/76851972-85e39100-6874-11ea-9efc-2dc833df6725.png">

I am using NVM to switch between node versions.

**Comment by AdnanAfsari** [comment]
@caprado Can you help me with this?

**Comment by lancewillett** [comment]
Can you try `npm run distclean`? From [the Troubleshooting docs](https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md).

**Comment by AdnanAfsari** [comment]
Hay @lancewillett It worked 😄 . I went through the doc before but I missed that step. Thank very much.
