### ISSUE TITLE
Gutenboarding: cannot scroll design selector

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40200]
At `/gutenboarding`, the design selector should be scrollable:

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/87168/76837478-506e8180-683b-11ea-8dff-0950a46333ba.png">

It's not. :-(

**Comment by ramonjd** [comment]
`.design_selector` has `position:fixed` 🤷‍♂ 

<img width="1219" alt="Screen Shot 2020-03-17 at 9 09 05 pm" src="https://user-images.githubusercontent.com/6458278/76845862-ac64f480-6893-11ea-90e2-6d810d2e829d.png">

Removing all CSS declarations for `.design_selector` makes the content fit within the `1100px` max-width of `.wp-block`

<img width="1520" alt="Screen Shot 2020-03-17 at 9 11 32 pm" src="https://user-images.githubusercontent.com/6458278/76846033-fd74e880-6893-11ea-86e6-1748edacb192.png">

I think `.wp-block { 90% }` will emulate the stretch effect the fixed position was trying to achieve.

**Comment by yansern** [comment]
> I think .wp-block { 90% } will emulate the stretch effect the fixed position was trying to achieve.

Not sure what this "stretch effect" means but I'm going to just make design selector fit the default 1100px width provided by `.wp-block` in the PR https://github.com/Automattic/wp-calypso/pull/40211.

**Comment by yansern** [comment]
Ah, so this https://github.com/Automattic/wp-calypso/pull/40211#issuecomment-600064537 is what "stretch effect" meant.

**Comment by ramonjd** [comment]
> Not sure what this "stretch effect"

Sorry, I was a bit ineloquent on that point!! 

As  #40211 (comment) suggests, just "stretching" the design selector across its container to 90% of the page width.
