### ISSUE TITLE
Framework: It seems too easy to exceed localStorage quota

### ISSUE THREAD

**Issue by westi** [Automattic/wp-calypso#4020]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Accept Invite
3. See JS Error
4. UI Broken and doesn't display that invite was accepted
#### What I expected

Invite accepted, joyful rest of my day
#### What happened instead

UI Froze
JS Error:
`Timestamp: 14/03/2016 13:08:06
Error: NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached
Source File: https://wordpress.com/calypso/vendor.4a38d48eab9f889b27fc.min.js
Line: 1`
#### Browser / OS version

Firefox 39.0.3 / OS X 10.10.5
#### Other info

I only cleared the localstorage out with window.localStorage.clear() in the console on Sunday because of a similar issue when I went to a http://wordpress.com/tag/foobar page.

**Comment by lancewillett** [comment]
Sorry for the label spam. :)

**Comment by lancewillett** [comment]
Has anyone else experienced this? I'm not seeing any comments or +1 to make improvements since March 14th.

**Comment by andrealeebishop** [comment]
I had something similar happen on a VIP ticket recently. 53318-z.

Error: 
`vendor.1706aeaee08377f8494b.min.js:1 Uncaught QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'statsTags90918835' exceeded the quota.resolve @ build-production.1706aeaee08377f8494b.min.js:23`

@westi suggested in Slack to try `window.localStorage.clear()` in the Chrome console when on the stats page and reload it - which worked for my user.

**Comment by lancewillett** [comment]
Closing as no further reports. Feel free to re-open in the future.

**Comment by jessie-ross** [comment]
Reopening this based on pbmo2S-PD-p2 (search for LocalStorage).

My theory is that this is due to post drafts being persisted in LocalStorage, might explain @westi's experience.

**Comment by jessie-ross** [comment]
It looks like around 0.02-0.05% of users are affected by this. Although there is a low chance of this occuring, data loss from it may occur, hence the Normal priority, but feel free to change it.

**Comment by cometgrrl** [comment]
[This work](https://github.com/Automattic/wp-calypso/pull/39286) should address the original issue.
