### ISSUE TITLE
New Checkout: Add special TLD support to contact info step

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#40217]
- Display extra fields for special TLDs in contact info step.
- Validate extra TLD fields on contact info step submission.
- Find component with TLDs and make sure we can control it.
- Add it to composite, update our data model to support those fields.
- Confirm TOS is correct.

**Comment by sirbrillig** [comment]
Re-worded because it was made clear to me that this is not really a ccTLD thing, but rather a thing for specific TLDs that have extra contact field requirements (for which the current ones are ccTLDs but it's more of a coincidence).
