### ISSUE TITLE
Default Content: Typo in Default Blog Post

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#40214]
Typo in default  Blog Post content:

![image](https://user-images.githubusercontent.com/545779/76865307-82c6b180-6830-11ea-849c-84c6f8c7da6f.png)

The highlighted text should read "focus your" **not** "focus you".

**Comment by michaeldcain** [comment]
Fix: D40435-code

**Comment by ianstewart** [comment]
![image](https://user-images.githubusercontent.com/545779/76868553-1ac69a00-6835-11ea-91c1-773c1ae28742.png)

Thanks, @michaeldcain!
