### ISSUE TITLE
Gutenboarding: Widescreen support for design selector.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#40234]
I think @Automattic/gutenboarding-design wanted to have a design grid expand quite a bit on wider screens. 

Here are some screenshots with 1750px width —

### Prototype

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/87168/76859384-e7e6cb00-6861-11ea-93df-7b7b3cf9a2c7.png">

### In `master`

<img width="1751" alt="image" src="https://user-images.githubusercontent.com/87168/76859373-e0bfbd00-6861-11ea-9812-ab2b516fcb22.png">

### This PR:

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/87168/76859420-f7feaa80-6861-11ea-8a7f-c48420d44387.png">

_Originally posted by @simison in https://github.com/Automattic/wp-calypso/pull/40211#issuecomment-600064537_

Comment from https://github.com/Automattic/wp-calypso/pull/40378#issuecomment-603121446:

> No idea if there are differences in how easy it is to do with `img`, CSS-background, or `iframe`.

**Comment by razvanpapadopol** [comment]
With the newly introduced iframe solution and [this PR](https://github.com/Automattic/wp-calypso/pull/40600) that enabled Gutenboarding on full-width I think we can close this issue. 
cc @simison

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/40600
