### ISSUE TITLE
Gutenberg Onboarding Modal: loading in Layout Selector

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#40265]
#### Steps I took …

1. Create a new site on WP.com
2. Click Site (in Sidebar) > Pages > Add New Page

(No settings changed or checklist items interacted with between step 1 and step 2.)

#### What I expected

1. Pick a Page Layout
2. "Enter the editor"
3. See the Onboarding Modal

#### What happened instead

I saw the Gutenberg Onboarding Modal.
![image](https://user-images.githubusercontent.com/545779/77007140-b0dfea80-6931-11ea-85f5-95ee1d2f5ba7.png)

**Comment by noahtallen** [comment]
In slack we had two ideas for a solution:
1. Adjust the z-index of the modal so that it is behind SPT.
2. Dispatch the action to show the modal only after SPT has been closed.

**Comment by simison** [comment]
> Adjust the z-index of the modal so that it is behind SPT.
> Dispatch the action to show the modal only after SPT has been closed.

If CSS fix isn't ideal but quicker to do before Monday, I'd suggest to then do both. ;-)

**Comment by noahtallen** [comment]
It turns out that the CSS fix won't work, so I've added a wp data-store to SPT to track if the modal is open. We can use that to hide wpcom NUX if SPT is open.
