### ISSUE TITLE
Purchases: Manage Purchases Unavailable for Disconnected Jetpack Sites

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#40267]
#### Steps to reproduce

1. Create a Jetpack site connected to a WordPress.com account, and have a paid subscription for Jetpack purchased.
2. Disconnect that site from Jetpack.
3. The Manage Purchases page in Calypso will show the subscription, but if you click on the subscription to manage it (cancel, adjust auto-renew, renew it, etc), it will fail to load. 

User reports in 19503753hc and 2457679hc can be replicated on their accounts, but I haven't been able to replicate on my personal Jetpack subscription.

**Please display a contact support notice in this case, instead of infinite loaders, until a better long term solution is found.**

#### What I expected
To be able to manage a subscription, even if Jetpack is disconnected. 
#### What happened instead
Users are unable to manage billing options for Jetpack subscriptions on a disconnected site. 
#### Browser / OS version
All.
#### Screenshot / Video
![Untitled](https://user-images.githubusercontent.com/30731356/77010886-ed0e4d80-6927-11ea-884a-8469d4c2af73.png)

#### Context / Source

 #reallife #anxiety #anxiety-flow #stresscase #painpoint.
 #user-report 

User reports in 19503753hc and 2457679hc, but I haven't been able to replicate on my personal Jetpack subscription.

**Comment by lancewillett** [comment]
> Users are unable to manage billing options for Jetpack subscriptions on a disconnected site.

This is a bad situation. Are there other ways to manage a Jetpack subscription, or is the subscription only managed via Calypso?

**Comment by lancewillett** [comment]
One thing to note is that Jetpack as a product is intending to use their own UI soon via Jetpack Cloud, and not rely on Calypso for users to access key features.

(That doesn't mean we shouldn't address this. Just adding for context — Jetpack team members have communicated that they don't intend Jetpack subscribers to be required to use Calypso.)

Ironically the error only happens when Jetpack is disconnected, and that connection is how Calypso knows about the site.

I’m curious if we should solve the root cause instead, which is healing Jetpack connections automatically instead of requiring manual HE intervention to run CLI commands (and acting through user steps to reconnect in Jetpack WP Admin).

**Comment by lancewillett** [comment]
Internal reference: pNPgK-4FM-p2 and pbtFFM-5K-p2.

**Comment by lancewillett** [comment]
My suggestions for short term:

The best short-term fix is for Calypso to show a better error message for people to know why the action isn’t available — prompting them to get in touch with support to fix the Jetpack connection.

Needs investigation for the network response.

Longer term:

1. Manage Jetpack subscriptions in a UI that doesn’t break based on the WordPress.com connection.
2. Heal Jetpack – WP.com connections automatically without HE intervention.

**Comment by annezazu** [comment]
>  Are there other ways to manage a Jetpack subscription, or is the subscription only managed via Calypso?

Currently,  @mzakariya  found you can cancel via Akismet but this is not ideal. He is going to report this to GitHub to fix and push folks to WP.com to manage their plans. Right now, we want all plan management to happen from WP.com.

**Comment by lancewillett** [comment]
Thanks, Anne.

> Right now, we want all plan management to happen from WP.com.

Worth chatting with Jetpack folks to confirm the broader strategy, too — as I've heard strong opinions from @gravityrail on moving away from Calypso entirely, as it "doesn't make sense for any Jetpack user, and is a terrible experience for them."

**Comment by annezazu** [comment]
Ahhh good call. That's likely in reaction to the Jetpack cloud work that's happening that you mention above. AFAIK from the designs I've seen, cloud will not be a place where folks will manage plans in the future although that very well could change depending on key product decisions.

**Comment by JessBoctor** [comment]
>The best short-term fix is for Calypso to show a better error message for people to know why the action isn’t available — prompting them to get in touch with support to fix the Jetpack connection.

Picked up on this thread from Stephens post, but wondering if we can't also direct customers to reconnect Jetpack on their own as well? This wouldn't work for situations where something broke the connection, but if the customer disconnected on their own, they could also reconnect it, in theory.

**Comment by lancewillett** [comment]
@JessBoctor Yes, good point. Where possible if the site owner can fix the issue themselves, that's a big win.

**Comment by kriskarkoski** [comment]
I think this is a longstanding issue first reported in #13421. 

Agreed on severity though, managing purchases shouldn't depend on the site status.
