### ISSUE TITLE
Gutenboarding: new domains flow MVP

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40284]
### Currently

When a customer clicks on paid domain from domain dropdown, we show a modal, then pre-select the Premium plan, and drop the customer to check-out. It's jarring, and we need to manage to bring them back to gutenboarding and then apply their choices to already made site. We also don't show calypso plans grid.

<img width="300" alt="Screenshot 2020-03-19 at 13 26 43" src="https://user-images.githubusercontent.com/87168/77062849-599b5200-69e5-11ea-8b9b-cf59892e9035.png">
<img width="500" alt="Screenshot 2020-03-19 at 13 26 22" src="https://user-images.githubusercontent.com/87168/77062937-83547900-69e5-11ea-9380-9f71f94568db.png">

### Goal
Instead we'll:

- Update modal UI to match designs (https://github.com/Automattic/wp-calypso/pull/40742) ✅
- Remove the modal that shows up when pressing paid domains currently (https://github.com/Automattic/wp-calypso/pull/40578) ✅
- Carry the paid domain across the flow (design picker, style picker), just show it as "selected" in the header (done in #40813) ✅
- After site creation API call, carry on the domain so that it can be added to calypso checkout cart, and show: (done in #40813) ✅
    - calypso plans grid
    - domain contact information form
    - checkout
- Then land in Gutenberg block editor just like with main flow (done in #40813) ✅

**Screens:**

<img width="300" alt="image" src="https://user-images.githubusercontent.com/87168/78386697-b2bed480-75e6-11ea-814a-6c1903e0a6b9.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/87168/77077802-64161580-69fe-11ea-81ac-833522acb6d8.png">
<img width="500" alt="Screenshot 2020-03-19 at 13 26 22" src="https://user-images.githubusercontent.com/87168/77062937-83547900-69e5-11ea-9380-9f71f94568db.png">

### Stretch goal

- Modify calypso plans grid so that background is white, header is from design and copy is improved #40822
- Adjust checkout header copy #40827
- ~pressing "start with free" shows a modal like this:~ (nope https://github.com/Automattic/wp-calypso/issues/40284#issuecomment-609648932)
    <img src="https://user-images.githubusercontent.com/87168/78386555-6f646600-75e6-11ea-8681-5f4764ed4cb4.png" alt="" width="250"/>
- Confirm that we use the domains APIs correctly to fetch suggestions (https://github.com/Automattic/wp-calypso/issues/40164) 

### Later on
See pbAok1-wT-p2

- We'll add custom plans grid
- We'll do domains sell for free sites just before "site launch"
- We'll add "more domains" modal
- We'll add "I already have domain" flow (https://github.com/Automattic/wp-calypso/issues/40324)

Supersedes https://github.com/Automattic/wp-calypso/issues/40746

cc @Automattic/gutenboarding-design @johnHackworth

**Comment by dubielzyk** [comment]
The _Start for free modal_ will be removed so no need to implement that. Apologies for the confusion.
