### ISSUE TITLE
Themes: add a friendly warning when switching away from a retired theme

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#40310]
Suggested by @jjchrisdiehl (on this internal thread: pbg9X-epe-p2)

![retired_theme](https://user-images.githubusercontent.com/66797/77127399-85c8ca00-6a09-11ea-95be-08dfd4daa49c.png)

The task is to adapt the current "Theme activation notice" to display a friendly message to site owners just before they take the destructive action to switch away from a retired theme.

The action isn't reversible for "Unlimited Theme Usage" on Premium, Business, and eCommerce plans. (Site owners who purchase a single theme can get it back in WP Admin theme viewer.)

@senff Adds this note:

> Avoid this from happening in the first place by making it clear that switching away from a retired theme is a permanent action and can not be undone... it might help those who accidentally switch.

#### Suggested wording

Your active theme **Lodestar** is retired. If you activate a new theme, you might not be able to switch back to Lodestar.

**Comment by Aurorum** [comment]
@lancewillett Could you please clarify the circumstances it which this occurs? 

> The action isn't reversible for "Unlimited Theme Usage" on Premium, Business, and eCommerce plans.

I'm finding that this isn't the case with a test Business plan site; it is still possible to switch in the WP admin theme viewer, and I assumed that was the case for everyone. I know that a lot of people (certainly me!) prefer this certainty so I'm unsure if the dialog should advise that it isn't possible when it is. 

<img width="1363" alt="Screenshot 2020-03-23 at 10 07 11" src="https://user-images.githubusercontent.com/43215253/77305539-1b0bdd00-6cee-11ea-9e57-dd6800dc8963.png">

It looks like the WP-Admin generally seems to be advertised for everyone, presumably as it offers this additional flexibility, although I do recall there being a time where this wasn't the case.

https://github.com/Automattic/wp-calypso/blob/19b21a2f670642a1071e04f06c5f095e9bae093a/client/my-sites/sidebar/index.jsx#L595-L600

**Comment by kriskarkoski** [comment]
It looks like this behavior will vary depending on whether a site is Simple or Atomic. On my Atomic test site, if I deactivate a retired Premium theme the theme is still symlinked and can be reactivated. In practical terms, this will mostly benefit Premium sites since most active Business sites and all eCommerce sites are Atomic.

@lancewillett Curious for your thoughts on the current behavior and if we should sever the symlink on Atomic when a Premium theme is switched away from to match the simple behavior.

**Comment by Aurorum** [comment]
I don't have a site with a Premium plan, but it is still possible to switch themes from a retired one on my site with a Free plan through WP-Admin (fortunately - it has helped me plenty of times!). I would assume that it would be the same with a Premium plan?

**Comment by kriskarkoski** [comment]
@Aurorum The behavior varies between free and Premium themes as well. So for free themes you can activate any theme, retired or not, as long as it was available when your site was created, but for Premium themes they cannot be reactivated on Premium once switched away from.

**Comment by lancewillett** [comment]
Yes, there are various cases at play here:

We don't allow switching back to any retired theme from the Calypso theme viewer. That's why this message is important. The wording might need clarity, though: "You may not be able to switch back again." That would make it a warning but less final.

Overall philosophy — we don't encourage using retired themes. This is a strongly held view: we think they are outdated, possibly insecure or unsupported. If they were safe and recommended, they would not be retired.

That means we should do everything we can to hide them and discourage their use.

**Retired free themes** are hidden by date from new sites created after the retirement action. Any WordPress.com Simple site created before that date, on any plan, _could_ switch back to the retired theme using the WP Admin theme viewer. We don't want them to, of course, yet also don't block it.

**Retired premium themes** are hidden from all sites, no matter the date of site creation or theme retirement. With one exception: any site that purchased the exact theme as a single, one-time purchase. They will have access to it forever via the WP Admin theme viewer "Purchased" view. All other sites should not use retired themes, and we only make exceptions if they contact us via support **and** the switch was accidental.

@kriskarkoski I didn't know about the Atomic case. Let's leave that in place for now, but not advertise it.

**Comment by lancewillett** [comment]
> It looks like the WP-Admin generally seems to be advertised for everyone

This is correct — now visible to everyone in Calypso.

**Comment by lancewillett** [comment]
@Aurorum I updated the issue body above with suggested wording:

> Your active theme **Lodestar** is retired. If you activate a new theme, you might not be able to switch back to Lodestar.

**Comment by lancewillett** [comment]
Clarifying (for myself and others) that this banner should show for both free and premium themes.

**Comment by Aurorum** [comment]
> The wording might need clarity, though: "You may not be able to switch back again." That would make it a warning but less final.

The risk with being vague is that it could be construed incorrectly, and doesn't really give confidence on whether or not they'll be able to switch back. I am a bit biased as I used a retired theme on my site, but I think people would appreciate that certainty when switching a theme; that message implies that retired themes could be hidden at anytime without warning. 

Generally, I'd personally advocate the warning of using a retired theme upon activation and allowing users to assess the pros/cons themselves, but that might be a bit tricky, mainly as it's outside of Calypso. Although, I suppose a warning could be added to the themes page.

<img width="1246" alt="Screenshot 2020-03-28 at 20 38 23" src="https://user-images.githubusercontent.com/43215253/77833283-1737ea80-7134-11ea-9ac3-db85f8e93a70.png">

Technically speaking, it seems plausible to add; although I can't find a selector to check if a theme is retired, that information does appear to be recorded.

<img width="196" alt="Screenshot 2020-03-28 at 20 28 40" src="https://user-images.githubusercontent.com/43215253/77833125-d8edfb80-7132-11ea-8fd3-8d1d182c279d.png">

Anyway, that's a bit outside switching a dialog. I was trying to think of alternative wording, but to be honest, as it conveys a warning for something which could be reversed, so perhaps the vagueness in the wording proposed is best (assuming this dialog is necessary)

**Comment by lancewillett** [comment]
Here's the equivalent message we've used in the past in WP Admin, showing up in "Appearance" > "Themes" to a site using a retired theme.

Typically only added if the old theme has an equivalent new theme to replace it — aka "theme refresh."

<img width="855" alt="Screen Shot 2020-03-28 at 14 15 17" src="https://user-images.githubusercontent.com/66797/77833979-901c4f80-70fe-11ea-94ed-9fa70fee1100.png">

In this case, Sweet Blossoms was replaced by Bouquet.

For themes without a replacement, it makes less sense to announce the retirement without something better that would match a similar look & feel.

**Comment by lancewillett** [comment]
I'd like to add the warning even with the vague message:

- Provides a basic message (even if not perfect) to site authors to warn them before they switch away.
- Reduces the support burden on Happiness Engineers dealing with confused customers.

**Comment by Aurorum** [comment]
> For themes without a replacement, it makes less sense to announce the retirement without something better that would match a similar look & feel.

Would it be implausible to suggest new themes based on the current theme's tags? 

<img width="264" alt="Screenshot 2020-03-29 at 09 26 19" src="https://user-images.githubusercontent.com/43215253/77844539-7bdc5f00-719f-11ea-8560-6d3865ff9079.png">

For example, with those, you could suggest based on subject, style and fluidity. 

<img width="1258" alt="Screenshot 2020-03-29 at 09 26 49" src="https://user-images.githubusercontent.com/43215253/77844556-90205c00-719f-11ea-887b-d57aeb8f32af.png">

**Comment by lancewillett** [comment]
@Aurorum Yes! I like the way you're thinking for improving this experience. "Find a similar theme" by tags is a smart approach.

It's a bit beyond scope of this exact request, though. 😄 If you want, you can work on it in a separate pull request.

To close this one, however, we just need the alert that shows when you first try to activate **away** from a retired theme.

**Comment by Aurorum** [comment]
Digging into this specific issue a bit further, and it looks like the existing dialogues for this are controlled by code outside of Calypso, and I'm assuming it's best (potentially even necessary) to stick with the same mechanism. 

https://github.com/Automattic/wp-calypso/blob/c8107c4340affbdc78b708ceb9d445d5ac946ed4/client/state/themes/reducer.js#L461-L488
https://github.com/Automattic/wp-calypso/blob/c8107c4340affbdc78b708ceb9d445d5ac946ed4/client/state/themes/action-types.js#L41

So sadly, not sure I can open a PR for this.

**Comment by lancewillett** [comment]
Here's where the auto-loading homepage warning is created, see #39436:

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/themes/auto-loading-homepage-modal.jsx#117

**Comment by Aurorum** [comment]
I'm assuming that's the only example of such a dialog - that is the one where I think it isn't possible to do this with code solely in Calypso sadly.

https://github.com/Automattic/wp-calypso/blob/4e5cfa45d471cdace6295bbd001da2cf9626a3d9/client/my-sites/themes/auto-loading-homepage-modal.jsx#L144

https://github.com/Automattic/wp-calypso/blob/f58859286254ec3c4c1bf393b6a459970eacc2fc/client/state/themes/selectors/should-show-homepage-warning.js#L14-L19

https://github.com/Automattic/wp-calypso/blob/c8107c4340affbdc78b708ceb9d445d5ac946ed4/client/state/themes/reducer.js#L461-L488

https://github.com/Automattic/wp-calypso/blob/c8107c4340affbdc78b708ceb9d445d5ac946ed4/client/state/themes/action-types.js#L41

**Comment by Aurorum** [comment]
I'm looking at this again, and I think that it is possible to spin up a PR for this issue. I'll take it, and spin up a PR with how far I get. :)

**Comment by Aurorum** [comment]
It definitely puzzled my brain several times, but I think that I've found a working solution to this issue in #40793. :) 

<img width="953" alt="Screenshot 2020-04-05 at 18 49 01" src="https://user-images.githubusercontent.com/43215253/78506027-14aa4600-776f-11ea-8bd7-070d24f803bc.png">

**Comment by ianstewart** [comment]
Looping back to this one. (Hi, Lance. Apologies that the PR got stale Aurorum!) I think the modal in the PR is missing a Learn More link so that users can learn more about the "why" and the original more definite text? Checking to see what we have for docs on retired themes to link to. 

We have https://wordpress.com/support/themes/ but that could use a refresh.

Edit: That's the page. :) Needs a refreshed general section on retired themes.

**Comment by kathrynwp** [comment]
Thanks, @sixhours! 

@ianstewart To keep it as simple as possible, I modified the **Retired Premium Themes** section with wording that applies to both premium and free themes. 

I did **not** include wording regarding how to access a retired free theme through the WP Admin themes area – which is no longer available without activating Advanced Dashboard Pages in a user's account profile – because this seems to get unnecessarily complicated/confusing, but if you think we should, I could add it in. FWIW, I rarely encounter users looking for accidentally-switched-away-from retired free (or premium!) themes these days.

Let me know if there are other tweaks you'd like and I'm glad to take a look.

**Comment by kathrynwp** [comment]
Noting one other change I made – added the word "usually" here:

> When a theme is retired, you can usually continue to use the theme for as long as you like. 

Since there have been occasional cases when we've had to remove a theme from sites that had been using it.

**Comment by jordesign** [comment]
> I rarely encounter users looking for accidentally-switched-away-from retired free (or premium!) themes these days.

I'd agree with this - the number of requests to have retired themes restored seems to be fairly minimal.

**Comment by kwight** [comment]
Work by @Aurorum continues here: https://github.com/Automattic/wp-calypso/pull/40793

**Comment by kwight** [comment]
There was an internal decision to keep the theme switch modals as they are, instead of introducing the retired theme info: https://github.com/Automattic/wp-calypso/pull/40793#issuecomment-897926213
