### ISSUE TITLE
Gutenboarding: Extract Search or Search Card component.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#40323]
As discussed in this comment https://github.com/Automattic/wp-calypso/pull/40202/files#r395541391.

Take note that SearchCard is just a wrapper around Search component. So it might be that we want to extract the Search component not the SearchCard.

**Comment by sirreal** [comment]
I expect we won't go this route: https://github.com/Automattic/wp-calypso/pull/40202/files#r395689775
