### ISSUE TITLE
Gutenboarding: Extract Badge component.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#40327]
To extract Badge component as seen here https://github.com/Automattic/wp-calypso/blob/0c337834ee20e98e151fc217056d16d0a031a065/client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx#L7 and discussed here: https://github.com/Automattic/wp-calypso/pull/40202/files#r395544569

**Comment by yansern** [comment]
@sirreal Since SearchCard is no longer used, and Badge seems like a trivial component to extract, might as well just resort to plain old span and css and be done with? Then we could ignore this task.

**Comment by yansern** [comment]
Okay just close this.

**Comment by simison** [comment]
Sounds good. 👍
