### ISSUE TITLE
Gutenboarding: Design step outline

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40320]
> Shall we also get rid of the green border in the design cards?
> 
> <img alt="Screenshot 2020-03-20 at 1 36 34 PM" width="1189" src="https://user-images.githubusercontent.com/1705499/77160598-57ea9080-6ab0-11ea-80ce-50aeaf120dd7.png">

**Comment by dubielzyk** [comment]
Yes, we should get rid of the green border. Since clicking the thumbnail should proceed to the next step.
