### ISSUE TITLE
Gutenboarding: implement "connecting existing domains" feature in domain dropdown

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40324]
_Screenshots and todos in this issue are outdated and need updating -Mikael_

---

In Slack convo p1584712654362000-slack-gutenboarding Javi commented:

>  I would even remove that entirely from gutenboarding. Maybe replace that text with "If you already have a domain, you will be able to connect it later", and just make the user use the domain tools once the site is created already.

Otherwise, we'll need to decide what happens from this flow and design + implement it:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/87168/77169714-a56ff900-6ac2-11ea-98c3-3cb5b04372db.png">

Altenratively we could put up together some kind of Frankenflow with what we have in Calypso. Some screens from the current flow:

<img width="1082" alt="Screenshot 2020-03-20 at 15 53 30" src="https://user-images.githubusercontent.com/87168/77170095-38a92e80-6ac3-11ea-9a05-acd4d1087276.png">

<img width="844" alt="Screenshot 2020-03-20 at 15 53 50" src="https://user-images.githubusercontent.com/87168/77170098-3b0b8880-6ac3-11ea-8948-2efc401758cb.png">

<img width="792" alt="Screenshot 2020-03-20 at 15 53 54" src="https://user-images.githubusercontent.com/87168/77170110-3cd54c00-6ac3-11ea-9e60-676391c000d8.png">

<img width="791" alt="Screenshot 2020-03-20 at 15 53 59" src="https://user-images.githubusercontent.com/87168/77170114-3f37a600-6ac3-11ea-9787-7d136d2e36fb.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/87168/77170519-cf75eb00-6ac3-11ea-9b4a-ca3dababaf81.png">

<img width="771" alt="Screenshot 2020-03-20 at 15 54 33" src="https://user-images.githubusercontent.com/87168/77170126-43fc5a00-6ac3-11ea-8916-cbce708ba8cd.png">

<img width="1643" alt="Screenshot 2020-03-20 at 15 55 10" src="https://user-images.githubusercontent.com/87168/77170136-478fe100-6ac3-11ea-8d5e-a982a450fa83.png">

**Comment by razvanpapadopol** [comment]
Superseded by https://github.com/Automattic/wp-calypso/issues/44645
