### ISSUE TITLE
Dotcom FSE: remove close button on Gutenberg 7.7

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#40334]
Out custom functionality to remove the default back button and replace it with our custom one doesn't work with Gutenberg 7.7 update. We need to update the functionality in order to remove the newly added `W` close button:

<img width="434" alt="Screenshot 2020-03-20 at 14 56 40" src="https://user-images.githubusercontent.com/1182160/77184102-9774a500-6acf-11ea-9ee6-e5db59b9b92a.png">

Our custom button is still inserted correctly but there is a styling issue with the right border that should be addressed as part of this task.

**Comment by simison** [comment]
@razvanpapadopol mentioned he could get this fixed. @razvanpapadopol do update here how it goes so that US folks can continue tackling it over their timezones as well. :-)

**Comment by mtias** [comment]
Why wouldn't we use the W instead of the custom button?

**Comment by vindl** [comment]
> Why wouldn't we use the W instead of the custom button?

@mtias we'll use it in general, this is just for the subset of legacy dotcom FSE sites, which is not that big in comparison.
