### ISSUE TITLE
Launch flow / Add new site: Missing Back button in Transfer/Map domains section

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#40330]
#### Steps to reproduce

1. Go through the site launch flow
2. At the domain step, click "Use a domain I own" link.
3. In the Transfer/Mapping section, notice there is no Back button

Note: this is also seen if you add a new site to an existing account(while signed in) by directly typing https://wordpress.com/start in the browser - the back button is missing in the Transfer/mapping section. However, if you add site by clicking Add new site link, then the back button is visible in the transfer/mapping section.

#### What I expected

<img width="1273" alt="Screenshot 2020-03-20 at 8 32 20 PM" src="https://user-images.githubusercontent.com/1269602/77176384-ffd08000-6ae9-11ea-9618-fd6e3e403954.png">

#### What happened instead

<img width="1387" alt="Screenshot 2020-03-20 at 8 31 00 PM" src="https://user-images.githubusercontent.com/1269602/77176431-1d054e80-6aea-11ea-9090-84018a74060d.png">

**Comment by southp** [comment]
🚢
