### ISSUE TITLE
Gutenberg 7.7.1 update on wpcom: fix header position on mobile

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#40335]
With Gutenberg 7.7.1 on tablet (and mobile):

#### block editor:
<img width="578" alt="Screenshot 2020-03-20 at 19 12 28" src="https://user-images.githubusercontent.com/14192054/77189079-abc09e00-6adf-11ea-866a-dc560a6c8be8.png">

#### FSE (after hiding W icon and [fixing back button style](https://github.com/Automattic/wp-calypso/pull/40329)):
<img width="627" alt="Screenshot 2020-03-20 at 19 03 38" src="https://user-images.githubusercontent.com/14192054/77189082-acf1cb00-6adf-11ea-85a8-b11f41fca350.png">

#### Jetpack
<img width="572" alt="7 7 1 + jetpack" src="https://user-images.githubusercontent.com/14192054/77338806-875cff80-6d33-11ea-966c-a5a0212ca55c.png">

**Comment by yansern** [comment]
Adding a couple more findings:

![image](https://user-images.githubusercontent.com/1287077/77394179-a8782b80-6dd9-11ea-87d6-942597e8521f.png)

![image](https://user-images.githubusercontent.com/1287077/77394150-95655b80-6dd9-11ea-81e2-a9fdd7020f59.png)

![image](https://user-images.githubusercontent.com/1287077/77394155-98f8e280-6dd9-11ea-86a3-460fbe19fb0b.png)
