### ISSUE TITLE
Plugin search link doesn't function until modifying search

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#40336]
Visit a plugin search URL:

https://wordpress.com/plugins?s=test

The plugin search results will not load. The expected API call to the below link doesn't trigger until one modifies the search field:

https://api.wordpress.org/plugins/info/1.1/?action=query_plugins

**Comment by tbradsha** [comment]
This is still an issue; it prevents us from linking to WordPress.com plugin searches.

**Comment by cpapazoglou** [comment]
This should be working correct now!

**Comment by tbradsha** [comment]
🥳
