### ISSUE TITLE
Some of the documentation needs updating

### ISSUE THREAD

**Issue by mwoodpatrick** [Automattic/wp-calypso#40355]
Looking at this URL:

     https://developer.wordpress.com/calypso/

Which is referenced from this repo it says:

    We're excited about the REST scaffolding going in **WordPress 4.4**, but the endpoints in the latest version don't cover a huge part of what we're doing. Automattic contributors to core have been heavily involved in the core API work so far, and we expect that to continue and **increase in 2016,** hopefully completely harmonizing the different APIs in one of the core releases next year.

Seems like the repro should point to an updated document. Where can I find the latest docs on Calypso?

**Comment by lancewillett** [comment]
Thanks, @mwoodpatrick for your questions and this suggestion.

(We haven't publicly blogged about the latest development of Calypso. We should get back to that!)

Latest docs on Calypso are in GitHub itself — starting from the repo root you'll see the README files with links.

When booting the app, you can also access them at `/dev-docs/`. Here's a live look: https://wpcalypso.wordpress.com/devdocs
