### ISSUE TITLE
Domains on atomic sites: Expose wordpress.com subdomain on Domains page

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#40350]
On WordPress.com atomic sites, once the site becomes atomic we hide the wordpress.com subdomain (free subdomain that every new site gets) from the Domains page in My Site > Manage > Domains. We also tell the user the site will change address from that domain, to a staging domain, using a new subdomain on the domain.wpcomstaging.com structure.

This is not correct though. Although the wordpress.com subdomain is removed from the list of domains on the site in calypso, and although we do change the primary domain to be the new staging domain, the old wordpress.com subdomain address still redirects to the site.

My proposal is that to avoid confusion on this, we add the wordpress.com subdomain back to the list of domains in My Site > Manage > Domains, and we inform the user that it can't be used as a primary address anymore instead. This would match what is actually happening on the site, and avoid user concerns around the fact that they would lose the wordpress.com subdomain "just to install a plugin or custom theme" - which is not the case.

We could "gray out" the domain on the list of domains and add some sort of message saying that "this domain cannot be set as the primary address on the site but will still show your site to visitors."

#### Steps to reproduce

On an atomic site -

1. Starting at URL: https://wordpress.com
2. Navigate to Manage > Domains
3. Verify that the site only contains the wpcomstaging domain, plus any other custom domains the user might have added.
4. Go to the site blog report card, and grab the wordpress.com subdomain, and try that subdomain on a browser window.

#### What I expected
To not be able to see the site on that wordpress.com subdomain since we tell users the domain will no longer be available on the site

#### What happened instead
The subdomain redirects to the primary domain on the site.

#### Context / Source
#dogfooding

**Comment by gwwar** [comment]
cc @Automattic/cobalt

**Comment by klimeryk** [comment]
I'm not sure I fully understand the issue - where would the user get the WPCOM subdomain address from? Is it a frequent confusion point? Do users actually contact us confused that the WPCOM subdomain is redirecting to their site?

I'm worried that introducing the WPCOM subdomain _and_ the staging subdomain, graying out one, but not the other could be confusing for other users.

**Comment by davipontesblog** [comment]
> I'm not sure I fully understand the issue - where would the user get the WPCOM subdomain address from? Is it a frequent confusion point? Do users actually contact us confused that the WPCOM subdomain is redirecting to their site?
> 
> I'm worried that introducing the WPCOM subdomain _and_ the staging subdomain, graying out one, but not the other could be confusing for other users.

Thanks for your thoughts @klimeryk ! The issue here is that when users need to install plugins or third-party themes on their site on the Business plan they see a note that says the domain is gonna change, and this causes confusion and concern, and some people contact us to understand why - some actually shy away from the whole process since they feel attached to the wpcom subdomain they've had on the site. I think clarifying that the domain does not actually go away would be important in this scenario, and simply explain that, if they don't already have a custom domain on the site, the staging domain will become the primary domain for them. I am not sure how to best word it, but it seems like this is unnecessary confusion for customers since the domain doesn't really go away - it just can't the primary domain on the site anymore.

**Comment by klimeryk** [comment]
@davipontesblog, is this still an issue? IIRC, there were some changes made to make the change of subdomain clearer to the user.

**Comment by davipontesblog** [comment]
Not really an issue, I had filed it as a feature request since I believe it brings better clarity to what domains work on the site when atomic. At the end of the day, the free .wordpress.com subdomain does continue to work for the given atomic site, but if we don't want to expose that information, I understand :) You can close it as a no-fix in that case.
