### ISSUE TITLE
Action bar: improve the flow to find and edit follow settings for the current site

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#40354]
This applies to the "Action bar" visible on WordPress.com Simple sites (not implemented yet for Atomic sites, see #36795).

#### Steps to reproduce

1. Starting at URL: a WordPress.com Simple site, front-end
2. Look in the bottom right corner for the "action bar"
3. Click "Manage subscriptions" — should only show if you are logged in

#### What I expected

When clicking Manage Subscriptions, I'd expect to go to the settings for this site.

<img width="297" alt="Screen Shot 2020-03-21 at 15 43 55" src="https://user-images.githubusercontent.com/66797/77238089-c69c1c80-6b8a-11ea-93ec-b2811c97d15f.png">

Note — the URL is also wrong, should be: `/following/manage` not `/following/edit`.

#### What happened instead

I land in a general screen, without any context of what to do next.

<img width="1392" alt="Screen Shot 2020-03-21 at 15 45 21" src="https://user-images.githubusercontent.com/66797/77238130-fc410580-6b8a-11ea-8895-cbb2116288d1.png">

The correct next steps are:

1. Look for "Search Followed Sites" input — which I hard to read.
2. Click into it with the mouse.
3. Type the site URL or title (from where I just was... what was it again?)
4. Then edit the settings by clicking the cog icon + "Settings" label

#### Suggested improvements

Maybe isolate the settings just for the site I was on — or, go to the site’s Reader feed and add a UI guide to show me where to click.

Something like `/read/feeds/[blog_id]` and, if possible, open Settings UI automatically

#### Related

#21536 describes an even better scenario, where the "Settings" form for the site is visible in the action bar itself.

**Comment by kwight** [comment]
D65614-code adds the site host value as a search parameter to the redirect URL, loading the Manage page with just the visited site in the results. It would be nice to add a param in Calypso that can signal to open the settings popover too.

<img width="1120" alt="Screen Shot 2021-08-17 at 2 24 10 PM" src="https://user-images.githubusercontent.com/349751/129803393-e8f1b2bd-cd6c-4c2e-a867-7425ea31efe0.png">

**Comment by kwight** [comment]
D65614-code has been merged.
