### ISSUE TITLE
Jetpack Products: save the data from the product removal survey

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#40357]
#### Steps to reproduce

1. Starting at URL: `/plans/:site`
2. remove Jetpack Search (`manage product` button on the feature card)
3. see copy in the modal

Verify whether the copy should be customized 
![product_removal](https://user-images.githubusercontent.com/13561163/77260427-422fc380-6c88-11ea-8e90-24eec71261ca.png)

**Comment by AnnaMag** [comment]
@robertbpugh, are there copy changes to be included in this modal?

**Comment by gibrown** [comment]
Can we just update the text to say "Jetpack Search" instead of "Jetpack Backup"? That should be sufficient for now.

**Comment by AnnaMag** [comment]
Sure. This just needs verification whether the data is saved correctly and in an appropriate place.

**Comment by AnnaMag** [comment]
The copy has been adjusted.

**Comment by AnnaMag** [comment]
The copy has been adjusted for Jetpack products.

Also, the data is saved to the remove cancellation marketing table.
