### ISSUE TITLE
Stats: Inaccurate data on Insights: Annual Site Stats

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#40352]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/stats/insights/
2. Check total comments
3. Compare to total comments on year view here: https://wordpress.com/stats/year/

#### What I expected

I would expect the number of comments to be accurate and match what is shown on Traffic page.

#### What happened instead

The number of comments on Annual Site Stats seems to be incorrect.

#### Browser / OS version

Chrome

#### Context / Source

#user-report 
Reported in 19492988-hc
Discussed here: p1584805462099100-slack-triage

**Comment by lancewillett** [comment]
Thanks for the report, @jamiepalatnik.

I tested on a few sites I'm an author on, http://themeshaper.com and https://sensible.blog, to see if I could repeat it.

=====

Viewing the Yearly stats view in Calypso under "Traffic": `/stats/year/?startDate=2019-01-01` — I see 9 comments for 2019 and 4 for 2020.

<img width="572" alt="Screen Shot 2020-03-21 at 14 21 44" src="https://user-images.githubusercontent.com/66797/77236823-4b813900-6b7f-11ea-9052-eb53027efa08.png">

Looking under "Insights" and "Annual Site Stats" `/stats/day/annualstats/` — I see 10 comments for 2019 and 4 for 2020.

<img width="611" alt="Screen Shot 2020-03-21 at 14 22 43" src="https://user-images.githubusercontent.com/66797/77236844-6fdd1580-6b7f-11ea-8fcc-11672d3bb8cb.png">

Here are the various stats:

| Year | Traffic, Yearly | Insights, Annual Site Stats | Approved Comments |
|------------ |------------ | -------------| -------------|
| 2020 | 4 comments | 4 comments | 4 comment, 0 pingbacks |
| 2019 | 10 comments | 10 comments | 9 comments, 1 pingbacks |

=====

For the sensible.blog stats — same views / URLs as above:

| Year | Traffic, Yearly | Insights, Annual Site Stats | Approved Comments |
|------------ |------------ | -------------| -------------|
| 2020 | 1 comments | 2 comments | 1 comment, 1 pingback |
| 2019 | 4 comments | 2 comments | 4 comments, 3 pingbacks |

I wonder also if pings (WordPress pingbacks) are also part of the count in one or the other.

**Comment by cathymcbride** [comment]
No customer reports. Closing...
