### ISSUE TITLE
Gutenboarding: Performance Improvements

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#40369]
@sgomes looked into Gutenboarding's performance and reported a few items that could need improvement (p1584972373304500-slack-gutenboarding):

- [ ] Gutenberg dependencies. `showdown` is pretty big, at 23KB. `react-dates` is an absurd 37.5KB. `moment-timezone` is also big. (These need upstream fixing in Gutenberg).
- [ ] `wpcom`: 
 - We're currently only using `getCart` and `setCart`. Should replace by directly using `wpcom-proxy-request`.
 - Let's make an `eslint` rule against importing `wpcom` (maybe Calypso-wide; I guess we can consider this legacy and recommend against it) /cc @Automattic/team-calypso (#40371)
- [x] `lib/analytics`. People have started moving stuff into https://github.com/Automattic/wp-calypso/tree/master/packages/calypso-analytics; @sgomes will look into this.
- [ ] Look why calypso-i18n is pulled in https://github.com/Automattic/wp-calypso/pull/39906#discussion_r405574580
- [ ] async plans loading https://github.com/Automattic/wp-calypso/issues/41481 
- [x] prefetch design thumbnails https://github.com/Automattic/wp-calypso/pull/42494 https://github.com/Automattic/wp-calypso/pull/42617 (props @alshakero)
- [x] Remove dashicons (https://github.com/Automattic/wp-calypso/pull/42577, https://github.com/Automattic/wp-calypso/pull/42325)

**Comment by sgomes** [comment]
PR with some improvements for `lib/analytics`: https://github.com/Automattic/wp-calypso/pull/40372 . It may unlock future gains by modularising, but produces no improvements by itself at the moment.

**Comment by inaikem** [comment]
@sgomes, checking in for an update on this issue. Is is closable (as complete or otherwise)?

For context, several of us are working on a cross-functional group triage effort in Dotcom to help us better manage our issue backlog. Thanks!

**Comment by sgomes** [comment]
Hey @inaikem! 👋 Sure, happy to help!

I'm sure that any findings are woefully out of date or entirely inapplicable at this point. No need to keep this around, so I'll close as not planned 👍

**Comment by tyxla** [comment]
For context, Gutenboarding was removed a while ago, making this issue no longer relevant: https://github.com/Automattic/wp-calypso/pull/74475
