### ISSUE TITLE
[bug] [desktop] Classic Editor Redirecting to WP-Admin on First Load of Existing Draft

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#40376]
## Bug: Classic Editor Redirecting to WP Admin in WP-Desktop

The first time an existing draft is loaded after activating the Classic Editor plugin, the editing view will opened within WP Admin with no way to back out (i.e. no "Close" button as expected in the top left). (Confirmed in wp-desktop v5.0.0).

#### Steps to reproduce

1. If you haven't already, install the Classic Editor plugin. Make sure it's _disabled_. 
2. Start the Desktop application, create a post. Verify that Gutenberg is displayed, add some smaple content, save a draft. Close the editor.
3. In WP Admin, activate the Classic Editor plugin.
4. In the Desktop application, open an existing draft - verify that the post is opened in Gutenberg (i.e. plugin is activated, but not enabled by the user yet).
5. In the post settings (gear icon in top right), select the "Switch to Classic Editor" option.
6. You will be transported to the editing view within WP-Admin, with no apparent way to exit (i.e. the "Close" button is not present in the top-left as expected). (Sometimes, this will redirect to the WP Admin in an external browser instead. I _think_ these two behaviors might be related.)

_Hack_: At this point, you can select "Manage Plugins" to back out of this view, but this is not expected (and certainly confusing). 

This appears to happen on the first time a draft is loaded after switching to the Classic Editor. Opening other existing drafts after the first attempt seems to work as expected.

#### What I expected

I expected my existing draft to be opened within the Classic Editor, within the Desktop application.

#### What happened instead

Editing view is opened within WP Admin (and sometimes redirected to an external browser context).

#### Browser / OS version

Tested on wp-desktop v5.0.0 on Mac (Automattic/wp-desktop@6ca43cf3)

#### Screenshot / Video

<img width="258" alt="switch-to-classic-editor" src="https://user-images.githubusercontent.com/8979548/77353333-27f0f680-6d17-11ea-917d-c825815789b2.png">

<img width="1278" alt="wp-admin-classic-editor-redirect" src="https://user-images.githubusercontent.com/8979548/77353372-3dfeb700-6d17-11ea-97ff-b68ad223a332.png">

#### Context / Source

Related to Automattic/wp-desktop#759

#dogfooding #user-report

**Comment by TravisH84** [comment]
Hello,

For what its worth I am also experiencing this bug on Windows 10, Wordpress 5.6.1, Jetpack V9.4, Wordpress.com desktop app 6.8.0. I am not sure it is entirely related to Classic Editor (although could be wrong), but I have the same consistent issue when using the Wordpress.com Desktop app it opens the post in a new browser window, but also in the app as a browser window like your image above.

This happens irrespective of if it is a new post, or an existing post, and it does not matter if I create a new post in the web browser then try and open it in the Desktop app, or if I create it in the desktop app (still opens the two windows when I open it in the desktop app).

I use the Wordpress Desktop App on iPadOS and it does not appear to do the same thing there, nor load the webpage in the app so it looks like it might be limited to desktop apps?

Hope that helps, happy to provid any more information if you need it.
I had seen some suggested fixes about enabling single sign-on and all of that stuff but none of those fixed the issue.

**Comment by nsakaimbo** [comment]
To all on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7) that was just released. The latest build can now be downloaded from the WordPress Desktop landing page [here](P7jrAc-3-p2).
