### ISSUE TITLE
Editor: (Calypso Classic) Modifying Image Link Causes Image to Disappear

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#40381]
If you have several images in a row with links and try to modify one of the links, it makes the image that you modify disappear.

#### Steps to reproduce
1. Create a new page in the Classic Editor.
2. Add 3 images to a post and reduce their size using the minus sign.
3. Add a link to each image
4. Publish the page and close it
5. Edit the page
6. Click the link icon to edit the link for the first image
7. Update the URL and click Save

#### What I expected
I expected the image to remain on the page with the new link.

#### What happened instead
The image disappeared
I recorded this last step here:  https://d.pr/v/F8i8eh

I did notice that when I opened the page to edit it and looked at the HTML, the first 2 images were included in the first link tag instead of there being a separate link tag for each image, so I imagine that has something to do with the problem: https://d.pr/i/aTuW9C

**Comment by lancewillett** [comment]
Good find, thank you for sharing the report and the useful videos to illustrate.

Sadly, this is unlikely to get fixed, because we're removing support for the Calypso "Classic Editor" in favor of the block editor for all users soon — next few weeks, most likely.

I'll leave open for now.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
