### ISSUE TITLE
Blog Posts Block: Enhancement - Add sort order options

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#40397]
The [Blog Posts block](https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/) is missing the option to set the sort order of the posts, a feature the [Latest Posts block has](https://wordpress.com/support/wordpress-editor/blocks/latest-posts-block/#latest-posts-settings) and would be helpful.

These options should be available:

* Newest to Oldest (default)
* Oldest to Newest
* Alphabetical A to Z
* Alphabetical Z to A

Requested 19436903-zen

**Comment by simison** [comment]
cc @Automattic/newspack  @Automattic/ajax to triage this and move to newspack repo if need. :-)

**Comment by adekbadek** [comment]
Added a comment to https://github.com/Automattic/newspack-blocks/issues/42 - and ordering feature request we already have.
