### ISSUE TITLE
Plans: domain discount isn't displayed until page is refreshed

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#4039]
When a user purchases a domain, they don't see the discount on the plans page straight away because the plans data is stale. We to refetch it after the user purchases a domain.

Plans page after purchasing a domain:
<img width="609" alt="screen shot 2016-03-15 at 10 47 16" src="https://cloud.githubusercontent.com/assets/275961/13775333/e66b0464-ea9b-11e5-97a1-d23333069d39.png">

Plans page after clearing local storage:
<img width="630" alt="screen shot 2016-03-15 at 10 47 55" src="https://cloud.githubusercontent.com/assets/275961/13775341/ef2278c6-ea9b-11e5-8385-28276eecb277.png">
 
Steps to reproduce:
1. Create a site on the free plan
2. Add a domain to the site
3. Visit /plans
4. Assert that the plan price is still $99 not $79
5. Clear local storage
6. Assert that the plan price is still now $79

**Comment by stephanethomas** [comment]
That should be pretty easy to fix [here](https://github.com/Automattic/wp-calypso/blob/cefff70a00bdce1d756fecc5257ad0fb49188838/client/my-sites/upgrades/checkout-thank-you/index.jsx#L81).
