### ISSUE TITLE
Gutenboarding: Domain picker visual tweaks

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40395]
> I recommend  we use core input for the search field, for now, to keep things simple

- [x] Fix `suggestion.match_reasons` error.
- [x] remove existing domain text
- [x] Type issues.
- [x] add search icon to search input.
- [x] autofocus on search input when picker displays
- [x] long domain flowing issue
- [x] just use span and css instead of `Badge`. https://github.com/Automattic/wp-calypso/issues/40327#issuecomment-601983524
- [x] domain API shuffling & []/undefined domain handling.
- [x] algorithm for picking recommended domain(s)

#### Mobile (<600px width)
- [ ] The popover goes off screen or is cropped for both [short](https://cloudup.com/cVDye3akIz2) and [long](https://cloudup.com/cw66ewrKzz4) site titles.

_Originally posted by @yansern in https://github.com/Automattic/wp-calypso/pull/40202#issuecomment-601762788_

> * How does the text link "Skip for now" and "Connect it now" button looks like when it is hovered?

Currently the button is gray. On hover it should transition to a black color.

> * How does the suggestion item looks like when it is in focused (through tabbing)?

It should look like this ![this](https://user-images.githubusercontent.com/2896062/77524383-85a45080-6e87-11ea-9df8-bc3c9d8f0acf.png). There's a mock for this in the design file if you need specs.

> Also, there is a slight difference in font weight as seen on Figma and the actual design, I believe one reason is that Figma prototypes are drawn through Canvas (I don't know what Figma does with that), and perhaps not all the font weights are loaded on the actual site. (not verified claim).

I think it's because the font is anti-aliased. If you turn on `-webkit-font-smoothing: antialiased` you can see it looking closer to the Figma file. As a designer I prefer the anti-aliased version, but there are [articles](https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/) [out there](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth) that say that this is a bad idea. I don't know enough about it.

_Originally posted by @dubielzyk in https://github.com/Automattic/wp-calypso/pull/40202#issuecomment-603751065_

**Comment by simison** [comment]
Design has changed slightly — some new visuals going in at https://github.com/Automattic/wp-calypso/pull/40742

**Comment by yansern** [comment]
Long domain text fixed in this PR. https://github.com/Automattic/wp-calypso/pull/40959

**Comment by yansern** [comment]
Related to autofocusing: https://github.com/Automattic/wp-calypso/issues/40890#issuecomment-611579912

**Comment by yansern** [comment]
I'm closing this issue as all mini tasks here have been completed. 
Mobile work will continue in this issue page. https://github.com/Automattic/wp-calypso/issues/40949

Thanks all for the great collaboration!
