### ISSUE TITLE
Checkout: Refactor shopping cart plan items creation

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#4041]
As mentioned in https://github.com/Automattic/wp-calypso/pull/3844#discussion_r56039959 , we currently have to specify a slug whenever we want to create a plan item for the shopping cart:

``` javascript
cartItems.premiumPlan( 'value_bundle' ) 
```

We should refactor this code to hide that slug, and generate objects that can be compared (currently it's possible to do `cartItems.premiumPlan == cartItems.businessPlan`, which is wrong).

**Comment by janm6k** [comment]
Going through old issues, closing ones that does not look like important one.

Please feel free to reopen if applicable.
