### ISSUE TITLE
Hide the page title input in your homepage is your theme is going to hide it

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#40410]
When you are editing your home page, you get the input for the page title in every case. Even if the theme is set up to hide the page title on the home page of the site. 
This creates confusion: The user can enter a new title there, but that doesn't affect the front-end of the site at all. 

Let's hide the page title input when the user is editing their homepage and the current theme is set to ignore the title.

**Comment by noahtallen** [comment]
related: #37509
