### ISSUE TITLE
Gutenboarding: Domain picker visual adjustments

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40430]
> * How does the text link "Skip for now" and "Connect it now" button looks like when it is hovered?

Currently the button is gray. On hover it should transition to a black color.

> * How does the suggestion item looks like when it is in focused (through tabbing)?

It should look like this ![this](https://user-images.githubusercontent.com/2896062/77524383-85a45080-6e87-11ea-9df8-bc3c9d8f0acf.png). There's a mock for this in the design file if you need specs.

> Also, there is a slight difference in font weight as seen on Figma and the actual design, I believe one reason is that Figma prototypes are drawn through Canvas (I don't know what Figma does with that), and perhaps not all the font weights are loaded on the actual site. (not verified claim).

I think it's because the font is anti-aliased. If you turn on `-webkit-font-smoothing: antialiased` you can see it looking closer to the Figma file. As a designer I prefer the anti-aliased version, but there are [articles](https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/) [out there](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth) that say that this is a bad idea. I don't know enough about it.

_Originally posted by @dubielzyk in https://github.com/Automattic/wp-calypso/pull/40202#issuecomment-603751065_

**Comment by simison** [comment]
I combined this to similar issue here https://github.com/Automattic/wp-calypso/issues/40395
