### ISSUE TITLE
Template picker broken in IE11

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40433]
We deployed latest version of FSE plugin to wpcom and started having failing canary IE11 tests because of these lines:

https://github.com/Automattic/wp-calypso/blob/b9a178b8c924d2a39b40d9999580dcf1a7ac68a0/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-iframe-preview.js#L46-L47

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/87168/77538969-40911600-6ea9-11ea-82a2-0b236938440c.png">

`DocumentFragment` needs a polyfill.

We'll disable IE11 canary for the failing test in https://github.com/Automattic/wp-calypso/pull/40239 to get them running. (Commit https://github.com/Automattic/wp-calypso/pull/40239/commits/9a4adccb1b6de6865e25f30874964b27310a4218)

FYI, you can also use `window.DocumentFragment` to avoid disabling no-undef lint rule.

Convo at p1585140512012800-slack-calypso

@Automattic/ajax would you have time to look into it? cc @sgomes

**Comment by simison** [comment]
@sgomes confirmed that changing this to `document.createDocumentFragment` fixes the issue

**Comment by sgomes** [comment]
Correct. The only thing missing in IE 11 appears to be support for the `DocumentFragment` constructor, so switching those calls to `document.createDocumentFragment` should be enough to solve this issue.
