### ISSUE TITLE
Gutenberg on WPCom: Problems with Images on Gutenberg version 7.7.1

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#40436]
User created a new post and can't resize the images the way they used to when they grouped them with a paragraph. 
Post: Women's History Month: Debbie Harry (Blondie))

Also, some of their existing posts are missing images while in the editor. (They show up on the public view)
Example post: Women's History Month: Annie Jump Cannon (Astronomer)
https://seletyn.com/2020/03/22/womens-history-month-annie-jump-cannon-astronomer/

They also just responded to the ticket and said this:

>Another glitch seems to be the changing of colors. If you want to add background color to the block but adjust it.
Block settings column on the right of the screen > Color Settings > choose any of the preset colors > Click "custom colors"
At that point, I would put the mouse over the circle in the upper right corner of the color palette and then drag it to the color I wanted while it showed the changes on the blog to the left. Now that is not available.

I used Support Sessions to access their site and saw the same thing (using Chrome), but I have not tested on my own site yet.

Plan: Premium
Site: seletyn.com
SA: https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=seletyn

2817137-zen

**Comment by ccwalburn** [comment]
There are two related issues in core here:

https://github.com/WordPress/gutenberg/issues/21152
https://github.com/WordPress/gutenberg/issues/21114

**Comment by ccwalburn** [comment]
The color issue appears to be in core as well: https://github.com/WordPress/gutenberg/issues/21163

**Comment by simison** [comment]
Image alignment issues fixed on wpcom simple sites in D40886-code — Atomic sites still having the issue.

**Comment by simison** [comment]
We can keep tracking this with core PRs. 👍
