### ISSUE TITLE
My Home: Update guided tour content to refer to My Home.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#40444]
[Noted](https://github.com/Automattic/wp-calypso/pull/40375#pullrequestreview-379758474) by @sixhours, guided tours offer a link to "return to the checklist", which is now forwarding to My Home. We should update the content to a more accurate "return to My Home".

It turns out there are quite a few references, some of which could be left as-is (I think `/plans/my-plan` might have its own proper checklist?). Each would have be verified to be sure changing them is the right move.

https://github.com/Automattic/wp-calypso/search?q=%22return+to+the+checklist%22&unscoped_q=%22return+to+the+checklist%22

**Comment by gwwar** [comment]
Nice Kirk! Looks like anything without the jetpack prefix refers to site setup.

@danhauk @sixhours @jancavan any other steps we'd like to turn on or be useful. I think we can 🔪 dead code otherwise.

**Comment by sixhours** [comment]
I haven't heard rumblings of any more checklist tasks being brought back, but it's a bit of a moving target. I think it's safe to remove the old stuff, knowing we can always bring it back to life if we have to later.

**Comment by mmtr** [comment]
This was done in https://github.com/Automattic/wp-calypso/pull/40952
