### ISSUE TITLE
Gutenberg - Focal point validation error with Cover and Media & Text block

### ISSUE THREAD

**Issue by geriux** [Automattic/wp-calypso#40440]
While testing [the integration](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2034) of the `Cover` block for the mobile app, some validation errors were found while testing using a simple site.

#### Steps to reproduce

1. Use a simple site
2. Create a post
3. Add a Cover or Media & Text block
4. Select an image
5. Set a focal point, with one of the values as `0`
6. Save the post
7. Refresh, you'll see in the console several validation errors.

#### What I expected

No validation errors while using the Focal point feature.

#### What happened instead

Validation errors were thrown:

<img width="1583" alt="Screenshot 2020-03-25 at 12 34 06" src="https://user-images.githubusercontent.com/4885740/77558577-62939400-6ebb-11ea-92e3-8fd0641fed3e.png">

It looks like when the value of the `background-position` is `0` its not including the `%` sign after it causing the block code to be invalid.

#### Browser / OS version

Chrome

#### Context / Source

There are some other PRs related to this that [solved issues](https://github.com/Automattic/wp-calypso/issues/38134) like rounding.

**Comment by JoshuaGoode** [comment]
I was not able to reproduce this.  It's been some time since the initial report and it appears that how the background gets added, alongside the position styling, has changed a bit. 

Was about to close but checking with @geriux to see if I failed to reproduce this properly.

**Comment by geriux** [comment]
Hey there, I believe this https://github.com/WordPress/gutenberg/pull/28501 solved that issue. So we can close this. Thanks!
