### ISSUE TITLE
Home: Update Styling for Free Photo Library Card in Mobile Devices

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40453]
I noticed that styling looks a little off when we view this card with in iPhone or Pixel:

We could maybe inline the button and text, or reduce text here to better match the styling of other elements on the page.

<img width="410" alt="Screen Shot 2020-03-25 at 2 47 12 PM" src="https://user-images.githubusercontent.com/1270189/77588894-f5c2ce80-6ea7-11ea-8870-ade27b6dfa26.png">

**Comment by Aurorum** [comment]
Are you thinking of something like this? :) 

<img width="491" alt="Screenshot 2020-03-26 at 07 35 33" src="https://user-images.githubusercontent.com/43215253/77621461-6a434f00-6f34-11ea-8bae-61be7f6f204d.png">

**Comment by gwwar** [comment]
Yeah something like that! Probably with reduced copy I think. I'll of course defer to @Automattic/dotcom-manage-design

**Comment by lcollette** [comment]
This is displaying as intended now. Closing. :)
