### ISSUE TITLE
Search: update performance/search setttings for instant search

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#40450]
https://wordpress.com/settings/performance/ needs to be updated to match the settings that are in Jetpack for instant search. Roughly:

<img width="1193" alt="Screen Shot 2020-03-25 at 2 53 12 PM" src="https://user-images.githubusercontent.com/820871/77584440-6833ae80-6ea8-11ea-9516-720a4d5d5ef2.png">

**Comment by jsnmoon** [comment]
Improving search eligibility by checking product purchases will be straightforward. 

However, adding a toggle for Instant Search would be more involved; I'm not sure what the best practice is for updating a WP option value from WPCOM.

**Comment by gibrown** [comment]
> I'm not sure what the best practice is for updating a WP option value from WPCOM.

There is an existing toggle for activating modules. I think there should be other examples of writing to the settings on the jp site from Calypso. Take a look at the related posts settings for instance.
