### ISSUE TITLE
Gutenberg 7.7.1 on wpcom missing vendor polyfills

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40468]
Both simple and atomic sites are missing `vendor` folder for Gutenberg while they try to enqueue these polyfills:

<img width="1616" alt="Screenshot 2020-03-26 at 11 37 04" src="https://user-images.githubusercontent.com/87168/77632122-38db7b00-6f56-11ea-962d-26d7c63014c0.png">

It's causing issues in IE11 (and likely failing our IE canaries due this).

Last time there was vendor dir was in 7.6.0 release of Gutenberg:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/87168/77632285-7213eb00-6f56-11ea-9dec-c381bd39b904.png">

In `wpcomsh` plugin [we included a custom polyfill](https://github.com/Automattic/wpcomsh/blob/931a977daf8cfc39b5f458ab2c06008179a9e888/feature-plugins/gutenberg-mods.php#L19-L64) for Gutenberg versions that didn't ship domrect polyfill yet. [Nowadays Gutenberg has it](https://github.com/WordPress/gutenberg/blob/5956aee125770d3845e069af4b977d1038a5644d/lib/client-assets.php#L208-L238).

Something is still off either in core or at our end because polyfills are missing. They'll go away soon once we're on WP 5.4 so temporarily fixing for simple sites by adding the file seems good.

**Comment by alshakero** [comment]
Maybe we should follow [this strategy](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/)? seems better than `document.write`.

```html
<!-- Browsers with ES module support load this file. -->
<script type="module" src="main.mjs"></script>

<!-- Older browsers load this file (and module-supporting -->
<!-- browsers know *not* to load this file). -->
<script nomodule src="main.es5.js"></script>
```

**Comment by yansern** [comment]
Related: https://github.com/WordPress/gutenberg/issues/21185

**Comment by yansern** [comment]
Note that there is a version/hash discrepancy between wpcom 7.7.1 & 7.8.0 and gutenberg's 7.7.1 & 7.8.0.

```
from wpcom gutenberg v7.7.1
- wp-polyfill-url.f434e7c5.js (different)
- wp-polyfill-dom-rect.7e21c103.js   

from wpcom gutenberg v7.8.0
- wp-polyfill-url.min.7490158b.js  (different)
- wp-polyfill-dom-rect.7e21c103.js   

from gutenberg repo tags/v7.7.1
- wp-polyfill-url.db0b5454.js 
- wp-polyfill-dom-rect.7e21c103.js

from gutenberg repo tags/v7.8.0
- wp-polyfill-url.db0b5454.js
- wp-polyfill-dom-rect.7e21c103.js
```

I could not find these specific files `wp-polyfill-url.f434e7c5.js` & `wp-polyfill-url.min.7490158b.js` anywhere.

Therefore, I am renaming `wp-polyfill-url.db0b5454.js`:
- to `wp-polyfill-url.f434e7c5.js` for  7.7.1
- to `wp-polyfill-url.min.7490158b.js` for 7.8.0

Hopefully this is no longer needed with WP 5.4.

**Comment by yansern** [comment]
Update: From these files in WP repo I can see which exact versions the polyfills are coming from.
https://core.trac.wordpress.org/changeset/47238/trunk/src/wp-includes/script-loader.php
https://core.trac.wordpress.org/changeset/47238/trunk/tools/webpack/packages.js

**Comment by simison** [comment]
Does WP 5.4-RC4 with Gutenberg 7.8.0 fix it?

**Comment by yansern** [comment]
Polyfills are added to 7.7.1 and 7.8.0 on wpcom.
