### ISSUE TITLE
Theme Showcase: Remove upgrade banner from retired Premium themes

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#40475]
1. Visit a retired theme's page in the theme showcase (e.g. Ladder):

https://wordpress.com/theme/ladder

2. Note upgrade banner that states "Access this theme for FREE with a Premium or Business plan!" but is incorrect, as the theme is retired:

![image](https://user-images.githubusercontent.com/32492176/77649681-e12a1900-6f2f-11ea-9338-b4d00774de35.png)

**Comment by Aurorum** [comment]
PR in #40544 for this issue. :)
