### ISSUE TITLE
Gutenboarding: stop clicks on preview

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40477]
In [Gutenboarding](https://wpcalypso.wordpress.com/gutenboarding), iframe shouldn't accept clicks/touch events:

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/87168/77653493-6fc28880-6f78-11ea-8451-f2a2eefa2b14.png">

![navigate](https://user-images.githubusercontent.com/87168/77653943-0a22cc00-6f79-11ea-9c1b-b2fce5d9da4d.gif)

Shouldn't work:
- form submissions
- link clicks
- page URL changes (can we just intercept these from happening?)

Should work:
- Link/button/image hovers
- Scrolling (including parallax etc effects)

Doesn't matter:
- text selection

Good compromise:
- only scrolling works, but hovers etc are busted

#### Slack convo (p1584617208292200-slack-gutenboarding) highlights:

> Does `pointer-events: none;` in the iframe work?

> We always can add some js in the preview that nuke all the click events

> xpath magic to remove all the href attributes?

> it’ll get interesting with menu-collapsing interactions which expect to be clickable, but let’s see.

> But we can't really just let the user navigate to other pages on the theme demo
> Well, the number of themes we need to handle is going to be limited. I'm sure we can adapt

> If a blink can be tolerated. We can utilise a CSP (Content Security Policy) to lock the iframe’s URL.
> I think this is a pretty clean solution without touching the preview code in the iframe or running any JS within it. It also works everywhere except IE.
> I deals with all sorts of navigation including form-submission, a.href, meta redirect, etc.
> Preview: https://lydian-veil.glitch.me/
> Source: https://glitch.com/edit/#!/lydian-veil?path=index.html:6:8

**Comment by alshakero** [comment]
Heads up! I experimented with the CSP idea. And even though I was really excited about it, and the code turned out pretty lovely, I think it's not a good way to go.

The blink effect is determinantal; when the user clicks a link, the window blinks and it looks like the preview has successfully navigated until you notice it didn't, very bad UX. 

I'll check the other methods tomorrow.

**Comment by simison** [comment]
I agree blink sounds like a bad experience. Thanks for exploring it!

**Comment by alshakero** [comment]
This was done in D41110-code.
