### ISSUE TITLE
Gutenboarding: Clicking "Start over" deletes all my entered data

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40478]
Current behavior:

1. Land on Gutenboarding and enter "Photography" as category and "Jon's Photos" as site name
2. Click _Choose design_ and proceed to the design step
3. Then click "Start over"
4. This takes you back to the text entry but all the data is gone

Intended behavior:
1-3: The same as above
4. This takes you back, but the data I entered should be there

The reasoning behind this is that it's probably less likely that users enter something completely different on the second time around. The most likely scenario is probably typos and the like. We should remember what they've typed to make the flow as effective as possible. 

We might wanna rename the label from "Start over" to something else, but we'll address that later.

**Comment by olaolusoga** [comment]
If the label remains "start over", we should keep as is: data is wiped. Intent capture is so brief, the data remaining, and data wiped seems minimal and subjective. We can keep as is for launch. If we hear back from customers—via support—that this is causing an issue we can adjust.

Also, marked as low priority.

**Comment by dubielzyk** [comment]
Agreed that this is low priority.

The reason for now wiping the data is because I assumed the biggest use case is typos or changing name after seeing it on the preview. Happy to have you decide.

**Comment by simison** [comment]
We can mitigate typos on title by letting them edit the title directly in the header on later steps. What do you think?

**Comment by dubielzyk** [comment]
I like the idea. We kinda do something similar with the domain. I'd say let's punt that idea for later though. Feels like optimizing for an smaller use case.

**Comment by razvanpapadopol** [comment]
Fixed in current version of the flow.
