### ISSUE TITLE
Gutenboarding: Button jumps down when selecting site name and category field

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40474]
Issue:
When you focus and blur the site name and category field, the other containers and button jumps up and down. See [recording here](https://d.pr/i/KB2PVs).

Expected behavior: 
Focusing input fields shouldn't make things move and things should be in the same place.

**Comment by ramonjd** [comment]
I think this has been fixed in the meantime.

Currently on wpcalypso:

![button-twitch](https://user-images.githubusercontent.com/6458278/78122803-fa175a80-7458-11ea-8caa-583392009f76.gif)

**Comment by dubielzyk** [comment]
Now the whole input jumps though. The _My site is about_ line should stay in the same place when going between the steps. The _It's called_ line should just appear below not jump the content up.

**Comment by razvanpapadopol** [comment]
This is being addressed in #40645 
Demo: https://cloudup.com/cQSItjRUFUa

**Comment by razvanpapadopol** [comment]
fixed in #40645
