### ISSUE TITLE
(8P) Tracking Events: Improve tracking of empty search results when inserting blocks

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#40491]
Results for the `wpcom_block_picker_no_results` event seem unusually low.
Let's figure out if the event fires every time we'd expect it to and what we can do to accurately measure search terms with no results.

Source: https://github.com/Automattic/wp-calypso/blob/master/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-picker-search-term-handler.js

See pa1C6h-Hc-p2

**Comment by obenland** [comment]
Todo:
* Decide what contexts should emit an empty search result event.
* See if all of those contexts actually emit an empty search result event.
* Fix the contexts that aren’t working as expected?

**Comment by getdave** [comment]
Question, is there an expectation that we should be tracking "no results" when using the `/` shortcut to bring up block picker? Because I don't think that's working.

**Comment by obenland** [comment]
I think so. Added that as a todo above

**Comment by retrofox** [comment]
### Decide what contexts should emit an empty search result event.

From my point of view and in terms of processing data, we should track all contexts as possible, as long as we are able to differentiate them.

Known contexts:

#### Blocks List Inserter


<img src="https://user-images.githubusercontent.com/77539/78889049-4b1ae600-7a39-11ea-8af7-e3161e6c2e3a.png" width="300px" />
</div>

#### Autocomplete (blocks)

<img src="https://user-images.githubusercontent.com/77539/78889060-5a019880-7a39-11ea-98e6-3aa0e0e2d98c.png" width="300px" />

_Let's keep updating this list...._

**Comment by retrofox** [comment]
### Fix the contexts that aren’t working as expected

AFAIK, we are tracking no-results events from only one context which is the `Block List Inserter`, and it isn't working as expected. Let's create a new issue for this.

**Comment by retrofox** [comment]
> ### Fix the contexts that aren’t working as expected
> AFAIK, we are tracking no-results events from only one context which is the `Block List Inserter`, and it isn't working as expected. Let's create a new issue for this.

I've created some issues to improve the tracking systems. Let's clarify that these issues are not a big deal in terms of collecting data:

* record `no-results` event when there is a selected block in the editor.
* record same event when typing special keys such as arrow keys, SHIFT, CMD, etc
