### ISSUE TITLE
Block-Editor: Missing DOMRect polyfill for IE 11

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40502]
@ockham @gwwar and @kwight were investigating E2E failures and noticed that we're missing the DOMRect polyfill in IE11. 

This will cause several JS errors to fire as folks interact with a block toolbar in the block-editor when using IE11

<img width="376" alt="Screen Shot 2020-03-26 at 3 05 32 PM" src="https://user-images.githubusercontent.com/1270189/77701664-15272d80-6f74-11ea-8b40-db4171bd8a04.png">

- [x] Please add back the polyfill as a quickfix similar to D39800-code (D40956-code)
- [x] File an issue upstream to Gutenberg core project since this also appears to be missing in Gutenberg 7.8 (https://github.com/WordPress/gutenberg/issues/21185)
- [ ] Add back block editor E2E test to IE11 canaries (removed in #40510 to unblock PRs) (#40517)

Related: https://github.com/WordPress/gutenberg/pull/20110

**Comment by kwight** [comment]
I did notice that there's no `vendor` directory in the v7.7.1 dotcom Gutenberg plugin, so it may be a related to the plugin build process before the plugin was uploaded to dotcom.

**Comment by simison** [comment]
Thanks! Logged also https://github.com/Automattic/wp-calypso/issues/40468

**Comment by mmtr** [comment]
In order to unblock other PRs, I removed the failing test from the IE11 canaries in https://github.com/Automattic/wp-calypso/pull/40510 while we fix this.

Please add it back once the polyfill has been included.

**Comment by p-jackson** [comment]
I've added the block editor E2E tests back to IE11 canaries. This involved making the tests work regardless of whether it was using the wp-admin or iframe editor, details in #40517
