### ISSUE TITLE
Gutenboarding: Remove `AnimatedPlaceholder`

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40511]
Remove AnimatedPlaceholder:

https://github.com/Automattic/wp-calypso/blob/dcb76ae5827748793c6a04a242bf57d9c1a68378/client/landing/gutenboarding/onboarding-block/create-site/index.tsx#L47-L56

This is a good place to use `useInterval` to swap texts with a `react-spring` `Spring` transition.

**Comment by simison** [comment]
There's another more comprehensive issue for loading animations: https://github.com/Automattic/wp-calypso/issues/39287

It's just outdated compared to the latest Figma.

@alshakero can you update it if you're going to work on this? Thanks!
