### ISSUE TITLE
Gutenboarding: Apply selected template and fonts to created site

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40513]
Coordinate with D40501-code to send selected template and font data in some format so it can be applied to a newly created site.

- [x] theme
- [x] template as home page
- [x] font pairing set in global styles

cc: @Automattic/ganon

**Comment by ramonjd** [comment]
>  template as home page

As mentioned over at D40501-code#818461, my _suspicion_ is that we'll have to extend Headstart to recompile and inject the template content into the new site's homepage. 

If we take a look at one of the theme's headstart json, say, `rivington/inc/headstart/en.json`, there are five pages and a few posts. 

We'd be replacing the content on the fly for the homepage only I assume. 

We should keep an eye on how much it slows down site creation. 

I might be wrong, but it looks like we'll have to make 2 x GET requests to external sources, plus whatever template merging the template mill does, and then another merge with the existing headstart json.

**Comment by ramonjd** [comment]
> my suspicion is that we'll have to extend Headstart to recompile and inject the template content into the new site's homepage.

Rather than port it to the backend, what are the limitations of keeping it like it is _for now_ in D40501-code, that is, applying the template to post_content in `create_pages()` via `wp_update_post`?

Doing all this in the backend will probably take a day or two of work. Only asking in the interests of shipping sooner :)

**Comment by johnHackworth** [comment]
> As mentioned over at D40501-code#818461, my suspicion is that we'll have to extend Headstart to recompile and inject the template content into the new site's homepage.

on the long term, that would be the way to go. On the short term, just deleting the content of the home page and replacing it with the template, even with the GET requests, should be fine. It'sgoing to be slower, of course, but the difference (in my testing) was barely noticeable (we are talking about going from, maybe, 5 seconds to 6 seconds) . I think it worth it to start like this and improve in the future :)

**Comment by ramonjd** [comment]
> on the long term, that would be the way to go. On the short term, just deleting the content of the home page and replacing it with the template, even with the GET requests, should be fine

Good to have confirmed. Thanks @johnHackworth !! 👍

**Comment by ramonjd** [comment]
I'm still not 100% over the template creation stuff, but I've taken a stab at what I think we're trying to achieve 

In D40501-code, `sites/new` accepts a template name, presumably with the intention that we pull down the desired template from the template mill/mix endpoint.

In conjunction with https://github.com/Automattic/wp-calypso/pull/40635, I've created D41188-code, which attempts to fulfil this intention,

But it doesn't quite work for reasons I don't understand. 😛 

I've seen it work once actually, but I'm getting a bunch of PHP errors from the demo endpoint, even though it looks okay in the browser, e.g., https://public-api.wordpress.com/rest/v1/template/demo/mayland/mayland2/?vertical=gym&site_title=gymbo

Is this the direction y'all had envisaged?

**Comment by sirreal** [comment]
Should be closed by D41188-code

**Comment by sirreal** [comment]
D41188-code is landed.
