### ISSUE TITLE
My Home: No footer on mobile.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#40533]
I find it odd that there's no footer-type content when scrolling to the bottom of the My Home page on mobile - it feels like we forgot to finish the site. 🙃

To be fair, this seems to be quite inconsistent across Calypso; we have a WordPress logo at the bottom of `/me` and some lists (like Pages and Posts), but many Manage and Tools views do not. Hat tip to notifications, that simply declare where we are with clarity.

| My Profile | My Home | Notifications |
| ------------- |-------------| -----|
|<img width="411" alt="Screen Shot 2020-03-27 at 1 30 51 PM" src="https://user-images.githubusercontent.com/349751/77798392-ff773e00-702f-11ea-8166-76ca9bacd882.png"> | <img width="412" alt="Screen Shot 2020-03-27 at 1 31 29 PM" src="https://user-images.githubusercontent.com/349751/77798715-a5c34380-7030-11ea-8817-f0205d58fa7b.png"> | <img width="413" alt="Screen Shot 2020-03-27 at 1 30 37 PM" src="https://user-images.githubusercontent.com/349751/77798830-dc995980-7030-11ea-9a76-7beaef8eeb6f.png"> |

**Comment by Aurorum** [comment]
PR in #40543. :)

> To be fair, this seems to be quite inconsistent across Calypso; we have a WordPress logo at the bottom of /me and some lists (like Pages and Posts), but many Manage and Tools views do not.

For what it's worth, the one added in `/me` was more to resolve a bug with scrolling, where sometimes the Inline Help button wouldn't move down far enough, preventing the buttons under Profile Links from being clickable: #29815

**Comment by jancavan** [comment]
I don't think that should be in /me either. I think its intent is only lists like Posts and Pages.

**Comment by lcollette** [comment]
Good call, @jancavan!

**Comment by gwwar** [comment]
going to close this one out then 👍
