### ISSUE TITLE
Gutenboarding: make commercial domain default in header

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40548]
In the header, we now show free _"*.wordpress.com is available"_. The domain should be the recommended paid domain.

<img width="540" alt="Screenshot 2020-03-29 at 20 15 47" src="https://user-images.githubusercontent.com/87168/77855616-2aad8900-71fa-11ea-9405-99f44546bdc2.png">

**Question:** should we somehow highlight what customer's free domain is going to be without any action?

Once they've actually selected something (e.g. free domain), show that in the header:

![image](https://user-images.githubusercontent.com/87168/77855786-59782f00-71fb-11ea-85a4-c3b49ea9649b.png)

**Question:** what should the text then be?

@Automattic/gutenboarding-design

**Comment by dubielzyk** [comment]
Hold off on this one for a tiny bit. These domain parts you're highlighting were a bit confusing during the study, so we're working on a revision. I'll keep you updated.

**Comment by ramonjd** [comment]
Also discussed in p1585772268201400-slack-CRWCHQGUB
