### ISSUE TITLE
Search Plan: Purchase a monthly plan and no "manage" link when looking at yearly

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#40549]
Steps:
- Go to /plans in Calypso
- Purchase a monthly search plan for a jp site
- Go back to the /plans page in Calypso and look at yearly plans
- There will not be a link to manage the plan that you purchased (link appears if you click to monthly)

**Comment by AnnaMag** [comment]
Noting that the inconsistencies between monthly and yearly concern all product cards.

monthly

![monthly](https://user-images.githubusercontent.com/13561163/78550773-f42ccb00-7804-11ea-989b-c179c239b5e0.png)

yearly

![yearly](https://user-images.githubusercontent.com/13561163/78550797-03137d80-7805-11ea-8f63-1963698335ac.png)

@keoshi which one would you say is the wanted card display? As the changes will affect all the cards, whom should we consult about it?

**Comment by keoshi** [comment]
I believe the monthly/yearly toggle shouldn't change the content inside of a purchased product card.

This means we would display a “Manage product” button if a customer has purchased any of them, no matter what the current billing cadency happens to be.

cc @folletto for a double check of this.

**Comment by folletto** [comment]
I agree. The button should always show. The "product" is the same product. And the button manages the product.

**Comment by enejb** [comment]
To provide some Background: The way it works now was done on purpose like this since the monthly and yearly products are two different things and some point wanted to offer a way to upgrade between the two choices.

We should make it clear to the user which interval they have the product for. 

cc @eeeeevon13

**Comment by folletto** [comment]
The fact that in the future we might provide that shouldn't be a limiting factor causing us being confusing now.

I agree on clarity: the interval clarity should be in whichever page they land on, not on this page.

**Comment by gibrown** [comment]
@enejb is this on your plate? Not a huge priority for us but we should get it fixed.
