### ISSUE TITLE
Search Plan Manage Purchases: needs icon and tier info

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#40550]
Steps:
- purchase a search plan for a site
- Go to https://wordpress.com/me/purchases
- Also go into the individual transaction

Missing tier info and icon for the plan

<img width="805" alt="Screen Shot 2020-03-29 at 10 21 37 AM" src="https://user-images.githubusercontent.com/820871/77856734-6888be00-71b6-11ea-94a6-9e555c0d2ae2.png">

**Comment by keoshi** [comment]
Design proposal for both this card and the expanded view:

![image](https://user-images.githubusercontent.com/390760/77909759-cafcbf80-7285-11ea-843a-680b4fc9a512.png)

How does this feel @gibrown @jsnmoon @robertbpugh ?

**Comment by robertbpugh** [comment]
Looks good to me!

**Comment by gibrown** [comment]
LGTM. Do we want to say "fully customizable" in the copy given some of the limitations we know they have around result formatting?

**Comment by keoshi** [comment]
@robertbpugh We're using this bit of copy elsewhere, right? Do we want to adjust it in all places?

**Comment by robertbpugh** [comment]
Ah, yeah that's in a few places. If it's not true, we should change it. How
about "Incredibly powerful and customizable"?

**Comment by keoshi** [comment]
Yes! I actually prefer that.

**Comment by robertbpugh** [comment]
Would probably need to adjust the punctuation too.

"Incredibly powerful and customizable, Jetpack Search helps your visitors
instantly find the right content – right when they need it. "

**Comment by keoshi** [comment]
Perfect! Already adjusted that in the landing page, which will be deployed soon.

**Comment by gibrown** [comment]
Sounds good. Thanks.
