### ISSUE TITLE
Make the posts and pages listings display the statuses more consistently 

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#40553]
Discussed [here](https://github.com/Automattic/wp-calypso/pull/40464#issuecomment-605357878) in #40464 

## There is some inconsistencies between pages and posts listings:

Posts and pages statuses are displayed differently between `pages` and `posts` pages when searching for items. Statuses in `pages` are colored while greyed and with different icons for `posts`.
 
Pages search             |  Posts search
:-------------------------:|:-------------------------:
![Screenshot 2020-03-29 at 23 04 25](https://user-images.githubusercontent.com/790558/77860851-cbf40980-7211-11ea-9414-d7d3f4d14c2c.png) | ![Screenshot 2020-03-29 at 23 04 54](https://user-images.githubusercontent.com/790558/77860853-cd253680-7211-11ea-8912-442917d97213.png)

## Scheduled pages and posts items display scheduled time instead of modified time. It gets misleading for the user when searching

The user has  2 different information on the same level:

![Screenshot 2020-03-28 at 00 28 43](https://user-images.githubusercontent.com/790558/77808925-b8b83100-708d-11ea-935c-f08aef8f684f.png)

I think it would make much more sense to adapt the "scheduled" info and keep the "modified timestamp" to  keep some consistancy between the cards:

![Screenshot 2020-03-28 at 00 31 46](https://user-images.githubusercontent.com/790558/77808450-accb6f80-708b-11ea-9a55-30d161c0856a.png)

## "homepage" is misplaced after #40464 

![Misplaced homepage](https://user-images.githubusercontent.com/1233880/77903595-6b9db000-7283-11ea-804d-eaa235b2a797.png)

## Harmonize translation for "Search pages..." and "Search posts..."

See this thread: https://github.com/Automattic/wp-calypso/pull/40464#discussion_r400123889

**Comment by millerf** [comment]
👆I feel like Schrödinger's cat... 😄

**Comment by millerf** [comment]
@gwwar Have colors on statuses been removed lately? I cannot reproduced those:

![Uploading Screenshot 2020-03-30 at 21.52.29.png…]()

**Comment by millerf** [comment]
What does "8 days ago" refer to?

![image](https://user-images.githubusercontent.com/790558/77958053-c4e1ff80-72d4-11ea-9e08-320ebec74804.png)

**Comment by gwwar** [comment]
> What does "8 days ago" refer to?

There's a particular view that attempts to group items by date, but likely there's many more bugs there.

<img width="1098" alt="Screen Shot 2020-03-30 at 1 27 30 PM" src="https://user-images.githubusercontent.com/1270189/77958710-48c2ca00-728a-11ea-931f-bcf8b40bd819.png">

I'm more in favor of simplifying to one page listing view but I'll defer to design on this one.

**Comment by millerf** [comment]
> There's a particular view that attempts to group items by date, but likely there's many more bugs there.

There is definitely something wrong there, as dates don't match. On my listing it is saying 8 days ago, while it says "5 days go" in their status.

**Comment by millerf** [comment]
@gwwar I fixed all those issues. I still have something I would like to discuss.
See the difference between my branch and master:

My branch            |  Master
:-------------------------:|:-------------------------:
 ![Screenshot 2020-03-31 at 00 37 02](https://user-images.githubusercontent.com/790558/77969006-f95fb680-72e8-11ea-8b9a-f22e5fcbe50e.png) | ![Screenshot 2020-03-31 at 00 37 45](https://user-images.githubusercontent.com/790558/77969008-fb297a00-72e8-11ea-9084-963f735a5d6f.png)


The timestamp on published and deleted posts are basic dates on `master`. My fixes changed them to display like it is displayed on pages "X days ago".
Should I keep it that way to make the design more consistent, or should I force it back to dates?

**Comment by lcollette** [comment]
I think Design can make some suggestions to improve the grouping here.

**Comment by millerf** [comment]
Maybe it should be a whole issue in itlsef?

**Comment by millerf** [comment]
@lcollette How do we get design involved?

**Comment by lcollette** [comment]
Sorry for the delay, @millerf. Thanks for your consideration for consistency! :) 

> I'm more in favor of simplifying to one page listing view but I'll defer to design on this one.

Agreed, @gwwar. I think the post and page dates add enough context on their own. 

> The timestamp on published and deleted posts are basic dates on master. My fixes changed them to display like it is displayed on pages "X days ago".
Should I keep it that way to make the design more consistent, or should I force it back to dates?

I'm leaning toward forcing it back to dates. The basic date format requires less mental processing than calculating what "X days ago" means.

**Comment by millerf** [comment]
@lcollette That is an interesting take...Never thought about design in termes of "mental processing"! And TBH I would have thought it would be easier to for the brain to understand "8 days ago" than a concrete date... Is there any places to learn more about this kind of things?

I'll change it back to dates in the meantime! Thanks!

**Comment by millerf** [comment]
So here is how it was on posts before:

https://github.com/millerf/wp-calypso/blob/master/client/blocks/post-time/index.jsx#L30-L38

Basically it would show "X days ago" if modified date was inferior to one week.

I think it would make sense to use it for posts and pages now...

**Comment by lcollette** [comment]
> @lcollette That is an interesting take...Never thought about design in termes of "mental processing"! And TBH I would have thought it would be easier to for the brain to understand "8 days ago" than a concrete date... Is there any places to learn more about this kind of things?

Thanks for asking, @millerf! For some people, it might be easy to process more relative information, like "8 days ago", but for others, that might be difficult. It depends on the available bandwidth of a person's working memory, which isn't an unlimited resource! We can reduce the information that needs to be processed at once to create a better "feeling" user experience. March 22nd is a basic date, whereas to process 8 days ago, we have to know what day of the week or date it currently is, etc, etc. 

For more information, here's an article about [cognitive load theory](https://www.mindtools.com/pages/article/cognitive-load-theory.htm). I also recommend Steve Krug's [Don't Make Me Think](https://www.amazon.com/Dont-Think-Revisited-Voices-Matter/dp/0321965515/ref=dp_ob_title_bkl). :)

**Comment by millerf** [comment]
Some changes my be needed for the time display in "scheduled status".

See [here](https://github.com/Automattic/wp-calypso/pull/40779#issuecomment-609745677)
