### ISSUE TITLE
Gutenboarding: font picker text alignment issue in Firefox

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40559]
In [Gutenboarding](https://wpcalypso.wordpress.com/gutenboarding) style picker step, font list loads looking like this on Firefox:

<img width="246" alt="Screenshot 2020-03-30 at 09 27 46" src="https://user-images.githubusercontent.com/87168/77882026-cece1900-7268-11ea-86a6-35a409c7ad63.png">

In Chrome it loads correctly:

<img width="246" alt="Screenshot 2020-03-30 at 09 27 46" src="https://user-images.githubusercontent.com/87168/77882673-20c36e80-726a-11ea-93b2-ede7151f2125.png">

**Comment by sirreal** [comment]
I'll grab this.
