### ISSUE TITLE
Checkout: Fix Thank You page when site selected is unavailable

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#4056]
Most variations of the `Thank You` page - for example the one for the Premium plan - assume that `selectedSite` is [always available](https://github.com/Automattic/wp-calypso/blob/dc35d9e827620180289d26971e41ad8e1f5ce401/client/my-sites/upgrades/checkout-thank-you/premium-plan-details.jsx#L28). This is however not always the case. For example if you execute `localStorage.clear()` in your browser's console and reload the `Thank You` page some information will be missing and some links will contains `undefined` because `selectedSite` is `false`:

![screenshot](https://cloud.githubusercontent.com/assets/594356/13788114/e860994e-eade-11e5-9149-e6dd04419c33.png)

We should probably display placeholders until the site is available.

**Comment by stephanethomas** [comment]
I had a look and I don't get why the page never displays the right data. I mean we poll the list of sites continuously and even if it's not on page load we should have it available at some point. It looks like `selectedSite` stays `false` [in the controller](https://github.com/Automattic/wp-calypso/blob/dc35d9e827620180289d26971e41ad8e1f5ce401/client/my-sites/upgrades/controller.jsx#L220) and as such doesn't trigger a rerender of the component tree.

I feel like the problem comes from the [`SitesList` module](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/lib/sites-list/list.js#L334). Since we have the site identifier [in the url](http://calypso.localhost:3000/checkout/:site/:receipt/thank-you) we should be able to select the site on page load, right?

Pinging @mtias for feedback.

**Comment by mtias** [comment]
Depending on what's you middleware stack for this page you may need to manually listen to sites `change` events like https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L158

If you are using that middleware you should be able to log what's going in the method: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L93

**Comment by mtias** [comment]
You could also use this function directly: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L171

**Comment by lancewillett** [comment]
@stephanethomas Did you move ahead with this one? I don't see any reply after the feedback.

**Comment by stephanethomas** [comment]
No I didn't. This is a bit of an edge case though, and this issue might even be deprecated once the `sites-list` module has been removed.
