### ISSUE TITLE
Gutenboarding: scaling and scrolling preview in style picker

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40568]
In style picker, the preview should scale down/up depending on screen size and preferably not have a double scroll. Additionally, the preview can be scaled down (i.e. we render e.g. 1200px wide and then scale down to 0.7 of that for the preview). Should those proportions change depending on format or browser width/height?

Double scroll:

![scroll](https://user-images.githubusercontent.com/87168/77903143-0fd72500-728b-11ea-8a5a-c9395ae59c37.gif)

I pad preview cuts out instead of scaling down:
<img width="931" alt="Screenshot 2020-03-30 at 13 31 55" src="https://user-images.githubusercontent.com/87168/77903206-28473f80-728b-11ea-825f-67fc6caf220d.png">

Mobile preview cuts out:
<img width="1159" alt="Screenshot 2020-03-30 at 13 32 05" src="https://user-images.githubusercontent.com/87168/77903237-309f7a80-728b-11ea-9b0e-e54a82cee840.png">

When web preview cuts out, there's plenty of it visible by scrolling the container down vs just scrolling the web preview down:

<img width="1032" alt="Screenshot 2020-03-30 at 13 32 28" src="https://user-images.githubusercontent.com/87168/77903270-3eed9680-728b-11ea-9c24-0bf82e7f5656.png">

@Automattic/gutenboarding-design  could you outline here how scaling down should work?

This might be several separate PRs to fix things but I felt like one issue to describe these problems was better.

**Comment by dubielzyk** [comment]
The page itself shouldn't scroll. The preview should scroll within the device though.

The device (whether it be desktop, tablet, or mobile) should fill up the space under the top elements and right of the font buttons. See illustration:
![image](https://user-images.githubusercontent.com/2896062/77915470-cfca6f00-7297-11ea-928c-1ac8f2f31410.png)

The devices should scale within that box to avoid the entire page becoming scrollable.

**Comment by simison** [comment]
@dubielzyk do you have any thoughts on scaling the preview?

Currently, we apply 0.7 scale no matter browser size or viewport mode (desktop/tablet/mobile).

```css
.style-preview__iframe {
    transform: scale(.7);
}
```

Should this be closer to 1.0 on big screens and smaller on smaller screens?

**Comment by dubielzyk** [comment]
>Should this be closer to 1.0 on big screens and smaller on smaller screens?

It looks alright down to 500px width screens, then it starts to look very small, but this should be fixed once we have implemented the mobile mocks. Let's assess then.

**Comment by sirreal** [comment]
With #40761 merged, we might consider this complete.

I'll close. @dubielzyk if you test the current state and would like further changes, go ahead and reopen or create new issues 👍
