### ISSUE TITLE
Gutenboarding: Style picker design fixes

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40569]
Style picker is looking great. I've outlined a few more fixes below:

### Remaining issues

- [ ] The page itself shouldn't be scrollable. The device window is currently too high. It should fit within the view. Look at the prototype for the right behavior.  https://github.com/Automattic/wp-calypso/issues/40568

### Done

- [x] Width of page is wrong. I've filed this as a separate issue ( #40566 ) as it affects all the design picker and intent capture too.
- [x] The device buttons are spaced a bit too far apart. The buttons should be `56px` high. Desktop should be `56px` wide, `48px` tablet , and `40px` mobile (@alshakero).
- [x] The device buttons should also be centered in the page container
- [x] The _Choose another design_ button should be styled according to designs (`font-size; 14px`, and `text-decoration: underline`) (@alshakero). 
- [x] The _Choose another design_ button should be aligned right to the container and centered vertically with the text (@alshakero).
- [x] The font buttons don't show the blue when it's selected until it's _unfoced_. It should show the selection color as soon as you click on it. Also isn't the selection color quite light? Should be `blue 40` by default (@alshakero).
- [x] Button, _Create my site_, in top right shouldn't be there (@alshakero).

See screenshot of a few of these:
![image](https://user-images.githubusercontent.com/2896062/77914100-af99b080-7295-11ea-9356-ab8cd9fa36ac.png)

**Comment by alshakero** [comment]
PR for most of these https://github.com/Automattic/wp-calypso/pull/40656

**Comment by simison** [comment]
Since only https://github.com/Automattic/wp-calypso/issues/40568 is left and it has its own issue, I'll close this.

**Comment by simison** [comment]
@dubielzyk  should we hide borders on hover with these buttons:

![image](https://user-images.githubusercontent.com/87168/78360176-0d443a80-75bf-11ea-87e5-d306919127a1.png)

When clicking on a button, it also keeps the border (so it's not just on hover). With that, it's possible to get this:

![image](https://user-images.githubusercontent.com/87168/78360289-3f559c80-75bf-11ea-9192-ef2363113d4c.png)

**Comment by dubielzyk** [comment]
Hover should have the border, but it shouldn't have the border when selected.
