### ISSUE TITLE
Gutenboarding: make design picker thumbnails taller

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40564]
We'll need tall images that scale up/down proportionally. Likely the number of columns needs to go down as the screen width is smaller and there needs to be some upper gap so that everything doesn't become super wide and tall screenshots are still somewhat visible.

See mshots limits: https://github.com/Automattic/mShots/blob/c141f2058027c849a82c1e4792ff7baf8a0bb098/public_html/class-mshots.php#L14-L19

We should pass values to API to render optimal size images.

#### Currently:

<img width="1182" alt="Screenshot 2020-03-30 at 11 16 04" src="https://user-images.githubusercontent.com/87168/77897569-7c99f180-7282-11ea-875d-d71f99e98142.png">

#### Goal:

<img width="1188" alt="Screenshot 2020-03-30 at 11 45 29" src="https://user-images.githubusercontent.com/87168/77897578-80c60f00-7282-11ea-8ccd-ba1bbc14f0e8.png">

On mobile (no need to implement yet):

<img width="351" alt="image" src="https://user-images.githubusercontent.com/87168/77897631-96d3cf80-7282-11ea-8753-57eeec5830da.png">

cc @Automattic/gutenboarding-design

**Comment by dubielzyk** [comment]
Also, let's make sure that only the thumbnail scales on hover, not thumbnail+text.

**Comment by simison** [comment]
Looks like little taller thumbs via mshots are possible but not super tall as far as I can tell, would be good if someone tries little more tho.

You can adjust these url arguments: `w` image width, `h`  image height, `vpw` viewport width, `vph` viewport height.

https://s.wordpress.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Frest%2Fv1%2Ftemplate%2Fdemo%2Frivington%2Frivington%2F%3Fvertical%3Dsadfklj%26font_headings%3DArvo%26font_base%3DMontserrat?w=960&h=1200&vpw=960&vph=1200

<img src="https://user-images.githubusercontent.com/87168/77921544-94846c00-72a8-11ea-9848-4aca505684dc.png" alt="" width="400">

https://s.wordpress.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Frest%2Fv1%2Ftemplate%2Fdemo%2Frivington%2Frivington%2F%3Fvertical%3Dsadfklj%26font_headings%3DArvo%26font_base%3DMontserrat?w=600&h=1200&vpw=960&vph=1200

<img src="https://user-images.githubusercontent.com/87168/77921669-bd0c6600-72a8-11ea-8d95-517310d3573a.png" alt="" width="400">

**Comment by olaolusoga** [comment]
Thought these were live previews, vs screenshots.

Can we have the image flex? So load up a high res image, and scale it based on viewport?

**Comment by simison** [comment]
> Thought these were live previews, vs screenshots.

We did try live previews but those were way too heavy on performance. (https://github.com/Automattic/wp-calypso/pull/40378#issuecomment-604469806)

I think we can grab manually some taller screenshots of templates to get tall screenshots for CfT.


Then separately we can work on adding "tall screenshots" feature into the tool that grabs these screenshots for us (https://github.com/Automattic/mShots/issues/16).

We'll also need to work on adding "prefetching" to autogenerated screenshots so that we wouldn't see those ugly "generating preview" images (https://github.com/Automattic/wp-calypso/pull/40615).

We can work on both of those after CfT tho. :-)
