### ISSUE TITLE
Gutenboarding: ensure the site gets created with the correct theme, template, and font pairing

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40561]
In Gutenboarding, after customer has chosen design and font pairing, the site should be created with correct:

- [ ] theme
- [ ] template as home page
- [ ] font pairing set in global styles

I haven't confirmed if this already is the case.

**Comment by simison** [comment]
@sirreal were you already familiar with these APIs?

**Comment by sirreal** [comment]
Duplicate of #40513

**Comment by sirreal** [comment]
> @sirreal were you already familiar with these APIs and would you like to look into it?

I've assigned myself to #40513
