### ISSUE TITLE
Gutenboarding: make font list aware of design specific font pairing

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40560]
In Gutenboarding, when a customer lands to font-picker, they always have the same font pairing selected and applied to the preview.

Font picker should reflect what is the default font pairing the selected design. Right now only backend preview mechanism is aware of that info.

<img width="1179" alt="Screenshot 2020-03-30 at 09 39 52" src="https://user-images.githubusercontent.com/87168/77882808-6ed87200-726a-11ea-91a8-2fbd1214a1f0.png">
<img width="1216" alt="Screenshot 2020-03-30 at 09 39 31" src="https://user-images.githubusercontent.com/87168/77882809-70099f00-726a-11ea-9e08-b5d70a787ca8.png">

In the big preview, we don't need to depend on backend to render the correct font since we can set it in clientside.

We do need the font-support in the backend for the thumbnail/screenshot preview tho.

**Comment by sirreal** [comment]
I brought up a similar point that you can't pick a theme's defaults:
pbAok1-sr-p2#comment-1027

Adding a _Default_ button seems like a simple fix for this.

**Comment by dubielzyk** [comment]
Agreed. We could have the top button be the default and that's whatever the theme has chosen 👍

**Comment by simison** [comment]
> [..] and that's whatever the theme has chosen 

@dubielzyk I didn't understand this part, can you elaborate?

**Comment by dubielzyk** [comment]
Apologies. The font options/buttons will be like this:
[ Theme font 1 / Theme font 2 ]
[ Cabin / Raleway ]
[ Chivo / Open Sans ]
[ Playfair / Fira Sans ]
[ Arvo / Montserrat ]
[ Space Mono / Roboto ]

**Comment by sirreal** [comment]
First pass of this in https://github.com/Automattic/wp-calypso/issues/40591 which adds the theme default button as _Default fonts_.

<img width="1130" alt="Screen Shot 2020-03-31 at 00 06 36" src="https://user-images.githubusercontent.com/841763/77966587-9e779080-72e3-11ea-8cf2-88774eb6a131.png">

**Comment by simison** [comment]
@sirreal @dubielzyk why couldn't we pull the correct font pairing [from json file](https://github.com/Automattic/wp-calypso/blob/44aed79713f5e273e32f854333e8e5a74de95f05/client/landing/gutenboarding/onboarding-block/design-selector/available-designs.json) and pre-select that in the font list? 

The experience remains confusing to me. 😁 "Theme" word is used for the first time in the flow.

In the grid, I have design with "arvo+montserrat":

<img width="1297" alt="Screenshot 2020-03-31 at 15 00 47" src="https://user-images.githubusercontent.com/87168/78024120-8134d780-7360-11ea-88bf-77aacff3320a.png">

In the big preview, I don't get it with Arvo/Montserrat. Instead, I get some font that's not on the list of pairings:

<img width="1231" alt="Screenshot 2020-03-31 at 15 01 03" src="https://user-images.githubusercontent.com/87168/78024361-e5579b80-7360-11ea-98e3-0206188c02ee.png">

If I choose "Arvo/Montserrat", only Arvo gets applied and the other stays at whatever it was:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/87168/78024445-0ddf9580-7361-11ea-993b-d1815d3e00f2.png">

**Comment by dubielzyk** [comment]
We should 100% pull the theme fonts for the default and remove duplicates if we already have the font pairing in our list.

My understanding from above was that @sirreal was gonna work on this in a follow-up.

We definitely aren't planning on having it called Theme font 1 / Theme font 2 😃

**Comment by sirreal** [comment]
> @sirreal @dubielzyk why couldn't we pull the correct font pairing [from json file](https://github.com/Automattic/wp-calypso/blob/44aed79713f5e273e32f854333e8e5a74de95f05/client/landing/gutenboarding/onboarding-block/design-selector/available-designs.json) and pre-select that in the font list?

Good plan, didn't know that was in there 🙂
