### ISSUE TITLE
Editor: Hide "Additional CSS class" field in blocks on plans that don't allow CSS customization

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#40572]
Users on the Free, Blogger and Personal plan don't have access to CSS customization at WordPress.com, yet the editor displays this field in most blocks:

![Screen Shot on 2020-03-30 at 10-17-38](https://user-images.githubusercontent.com/31009008/77923392-671bcc00-7270-11ea-8378-d294a82ea419.png)

This creates confusion for users. I recommend we either hide this in the editor on these sites or display an upsell message there. 

#### Browser / OS version
N/A

#### Context / Source

#user-report 19836150-hc

**Comment by automattic-ian** [comment]
removing this seems like it would kneecap users, as you can force things to match different styles by adding a custom class that matches a class the theme already calls for another element.

**Comment by Aurorum** [comment]
I agree with @automattic-ian, that was something that I used to do regularly. It was quite helpful for getting rid of margins.

**Comment by davipontesblog** [comment]
Agreed, thanks for bringing more perspective here @automattic-ian and @Aurorum. Closing this one!
