### ISSUE TITLE
Private Atomic Sites: Site response is incorrect

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40592]
1. With an a12 user account, create a new site with a Business plan
2. Transfer to Atomic, (try enabling plugins or SFTP)
3. Verify that the site is private
4. Launch site
5. Verify that the site is public
6. Visit /home
Expected: We should not see the launch site card or coming soon badging
Actual:
<img width="1371" alt="Screen Shot 2020-03-30 at 2 40 25 PM" src="https://user-images.githubusercontent.com/1270189/77964750-7876cf80-7294-11ea-8174-fbbca109e8b4.png">

Launch Status and other booleans are incorrect on the site endpoints:

<img width="1043" alt="Screen Shot 2020-03-30 at 2 28 33 PM" src="https://user-images.githubusercontent.com/1270189/77964614-33eb3400-7294-11ea-900e-075062c0d4e4.png">

<img width="1135" alt="Screen Shot 2020-03-30 at 2 30 28 PM" src="https://user-images.githubusercontent.com/1270189/77964640-3f3e5f80-7294-11ea-999f-93cda1304bc0.png">

**Comment by gwwar** [comment]
We probably need to force a Jetpack sync here if we'd like to use cached site data, or query through to the remote site.

**Comment by adamziel** [comment]
`launch-status` option isn't synced via Jetpack Sync, we rely entirely on cloud site option. Should we continue the discussion in p58i-8OX-p2 since it's touching the API?

**Comment by adamziel** [comment]
Fixed by code-D41130
