### ISSUE TITLE
Iterate on the private by default banner

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40618]
The site preview screen has it's own UI and if a site isn't launched it displays a banner at the top. 

<img width="1443" alt="Screen Shot 2020-03-31 at 1 11 29 PM" src="https://user-images.githubusercontent.com/437258/78055524-ab32cd80-7351-11ea-9da0-08696d4eafc5.png">

They create a very distracting and poor experience. 

Can we suppress the banner within the preview iframe (perhaps we can load the site url and add a parameter that hides the banner?)?

Separately, the banner has an outdated hex color for the pink, so the two buttons don't match. There are a few other things we could improve about the banner, spacing, typography. The banner also won't match other color schemes (I assume) so I wonder if we could make it feel more generic or at home on the front-end of the site somehow. 

We should probably make an explicit mention of  'coming soon' to align with the setting.

**Comment by michaeldcain** [comment]
> Can we suppress the banner within the preview iframe (perhaps we can load the site url and add a parameter that hides the banner?)?

Fix in D41403-code

**Comment by gwwar** [comment]
Closing
