### ISSUE TITLE
Iterate on launch and privacy settings

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40619]
When viewing the General settings for an unlaunched site we show this UI block:

<img width="757" alt="Screen Shot 2020-03-31 at 1 24 22 PM" src="https://user-images.githubusercontent.com/437258/78056575-6019ba00-7353-11ea-8607-2b2559e8f589.png">

It's a bit confusing. The banner mentions your site being 'private', but the radio option selected below is 'coming soon' (not private). 

The launch banner text could be more clear (explicitly mentioning the coming soon page perhaps). 

It also doesn't feel right that the launch settings are displayed as a settings card stacked on top of the privacy settings (which are disabled). 

Could we try a design where the launch info and button are contained within the privacy card?

**Comment by lcollette** [comment]
Maybe we can hide this section for now, or maybe it's just informational, explaining the varying privacy states.

**Comment by adamziel** [comment]
@rickybanister see https://github.com/Automattic/wp-calypso/pull/40962

**Comment by gwwar** [comment]
Adding a screen of the copy update from Adam. Please reopen if insufficient. 

<img width="742" alt="78903652-c1403c80-7a7b-11ea-842d-f7e2aaa8cabb" src="https://user-images.githubusercontent.com/1270189/79160314-6d409b00-7d8e-11ea-92f5-59140b12aeef.png">
