### ISSUE TITLE
Jetpack Search and Backup Connect: not working

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#40627]
I only tried a few links, but I don't think any of these work:
- https://wordpress.com/jetpack/connect/jetpack_backup_daily
- https://wordpress.com/jetpack/connect/jetpack_backup_realtime
- https://wordpress.com/jetpack/connect/jetpack_backup_daily_monthly
- https://wordpress.com/jetpack/connect/jetpack_backup_realtime_monthly
- https://wordpress.com/jetpack/connect/jetpack_search
- https://wordpress.com/jetpack/connect/jetpack_search/monthly

We could update these if we prefer something different, but this is what we currently have on the backend in the redirect code.

cc @Automattic/jetpack-voyager

**Comment by ChaosExAnima** [comment]
We use `backup` and `realtimebackup` for connect strings.

**Comment by gibrown** [comment]
@ChaosExAnima ok, that is not what the jetpack redirects has implemented. See 0-load.php in D41174

**Comment by ChaosExAnima** [comment]
@gibrown - Looks like wires were crossed here, as we did this structure a little bit ago: #40019. This is also what's used on JP.com.

@enejb  - What's the preference here?

**Comment by AnnaMag** [comment]
I addressed the dead end link for Search in #40661 to follow the `type/interval` format, as is also working for Backups.
The urls mentioned here are not defined in Calypso, but in the core, to be used at jetpack.com. 
I'd suggest the change should happen there.
/cc @ChaosExAnima
