### ISSUE TITLE
Customer Home: hide stats card at moment of launch

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40620]
I was just testing the private by default flow, clicked the launch button and saw this:

![image](https://user-images.githubusercontent.com/437258/78057545-e682cb80-7354-11ea-9df8-4388bdc326ba.png)

I was confused to see the Stats card, especially since it told me about my most popular day/time. As far as I know, no one has ever seen my site before, it was in coming-soon mode.

I clicked through to stats to see that my own views were counted, but this was unexpected.

I would have expected to perhaps see information inviting me to learn about stats on my first post-launch view, or perhaps just a delay before stats would start to gather...it just caught me off guard and I wondered for a moment if my site actually had been private or not.

**Comment by lcollette** [comment]
We'll need to think through the rules for showing the stats card. The API will handle all this magic.

**Comment by kwight** [comment]
This is cleaned up now, with the #40633 and D41205-code – the card will only show if the site has had any views in the last week.

**Comment by gwwar** [comment]
@kwight I think @rickybanister is asking for a delay after launch, not just using stat counts which might be coming from the user/other admins.

**Comment by rickybanister** [comment]
Yes, exactly what @gwwar mentioned—when I launched I was shown my own views of my site. We should probably hide the card if there's no traffic as well, but the delay right after launch might quell fears that people were seeing the site while it was private.

**Comment by kwight** [comment]
Ah right, got it. I've done up D41378-code which keeps the current check for traffic in the last seven days, and adds a check that the site was launched at least three days ago.

**Comment by gwwar** [comment]
Closing this out, let's revisit this behavior on the next round of stats improvements. For example, we may want to always display this card, but provide some helpful guidance when there are 0 insights.
