### ISSUE TITLE
Stats: Insights: mix of sentence and title case in cards

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40622]
I spotted a mix of sentence and title case in the card headings here:

![image](https://user-images.githubusercontent.com/437258/78060508-9eb27300-7359-11ea-9481-c94e71ddd7c8.png)

Let's unify.

**Comment by gwwar** [comment]
Note that sentence case is i18n dependant, so we should prefer updating string translations over any JS solutions.

**Comment by mmtr** [comment]
@jancavan has this been fixed in https://github.com/Automattic/wp-calypso/pull/41647?

**Comment by jancavan** [comment]
Yes, fixed in: https://github.com/Automattic/wp-calypso/pull/41647. I'll close this.
