### ISSUE TITLE
Remove checklist section

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#40646]
Let's audit the [old checklist section](https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/checklist) (`wordpress.com/checklist/:site`) and see if it's still needed now that My Home is enabled for all WP.com sites.

Looking at the [controller](https://github.com/Automattic/wp-calypso/blob/7c494f98a72f1d4ac249c666aad106520de8a190/client/my-sites/checklist/controller.jsx#L29-L39), it seems that the only users that can access now are non-admin users and VIP sites users.

**Comment by mmtr** [comment]
After taking a deeper look at the controller, the `/checklist` route can be accessed only by any user of a VIP site created after Feb 1, 2018 or by non-admin users of a simple site created after Feb 1, 2018.

However, none of them are ever linked to that section. AFAIK, the only places linking to the old checklist are [the signup flows](https://github.com/Automattic/wp-calypso/blob/a4616438bcb848e97b784fa6d55ba4e9c5cb3d21/client/signup/config/flows.js#L58-L72) and [the guided tours](https://github.com/search?q=%22href%3D%5C%22%2Fchecklist%2F%3Asite%5C%22%22+repo%3AAutomattic%2Fwp-calypso+path%3Aclient%2Flayout%2Fguided-tours&type=Code). 

The signup flows can link to `/home`, since they all create a site with My Home accessible for the current user.

Guided tours are only used on sites with My Home accessible too, so they can link to `/home` as well.

Once there are no places linking to `/checklist` it should be safe to remove the checklist section altogether.

**Comment by mmtr** [comment]
Also found the checklist tasks [redirect back to `/checklist/:site`](https://github.com/Automattic/wp-calypso/blob/c9a8c341f663cd1bebd0bd3459a1edae734db0f3/client/my-sites/checklist/wpcom-checklist/component.jsx#L190-L192). 

Seems that function is never used by the `Task` Component, so should be safe to remove it.

**Comment by mmtr** [comment]
Another instance of the legacy checklist in the inline help. It renders [`ChecklistOnboardingWelcome`](https://github.com/Automattic/wp-calypso/blob/c6d4d14abee05e46ac8053ad1150101c8e8df7b6/client/blocks/inline-help/popover.jsx#L212) when the secondary view is set to `VIEW_ONBOARDING_WELCOME`.

That seems to happen when [`isOnboardingWelcomePromptVisible` returns true](https://github.com/Automattic/wp-calypso/blob/c6d4d14abee05e46ac8053ad1150101c8e8df7b6/client/blocks/inline-help/popover.jsx#L339) which apparently can only be fired by [the preview component](https://github.com/Automattic/wp-calypso/blob/c6d4d14abee05e46ac8053ad1150101c8e8df7b6/client/my-sites/preview/main.jsx#L70-L72). 

According to https://github.com/Automattic/wp-calypso/pull/30406, visiting `/view/:site?welcome` should trigger the checklist in the inline help, but it doesn't show up for me. I wonder if we effectively removed that feature in https://github.com/Automattic/wp-calypso/pull/40415 so existing code is just unused and can be removed. cc @sixhours

**Comment by sixhours** [comment]
We did remove that feature, and we can remove any related code that is attached to it AFAIK!

**Comment by mmtr** [comment]
Found a few more links to `/checklist`, this time in the server. Prepared a patch replacing them: D41640-code.
