### ISSUE TITLE
Change folder names under static/page-templates/verticals from vertical labels to vertical IDs

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#40640]
In https://github.com/Automattic/wp-calypso/pull/40635 we sent the vertical slug to the `sites/new` endpoint.

The vertical slug is the untranslated version of the vertical name, and would therefore match the directory names under https://github.com/Automattic/wp-calypso/tree/master/static/page-templates/verticals

@p-jackson [observed](https://github.com/Automattic/wp-calypso/pull/40635#discussion_r401345315) that it would be better to change the folder names to vertical ids because:

1. We already sent the vertical id to `sites/new`
2. We won't have to deal with formatting the slug, for example, to lowercase_snake_case for future vertical slugs

This task will involve:

1. Changing the directory names
2. Updating the template mix/demo APIs to use the vertical id in the json fetch URL
3. Sometimes we want to rename verticals, and in the past we've renamed slugs have been renamed too, which makes renaming even harder. [[source](https://github.com/Automattic/wp-calypso/issues/40640#issuecomment-607108309)]

**Comment by p-jackson** [comment]
> We won't have to deal with formatting the slug, for example, to lowercase_snake_case for future vertical slugs

Yeah this is what I was thinking. Also:

3. Sometimes we want to rename verticals, and in the past we've renamed slugs have been renamed too, which makes renaming even harder.

**Comment by ramonjd** [comment]
No longer required.
