### ISSUE TITLE
Gutenboarding: reset font pairing when selecting new design

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40649]
When going back to design picker in Gutenboarding flow and selecting a new design, font pairing should be reset to that of the selected design.

Steps to replicate:
- Choose design
- Change font in font picker to something custom
- Go back to design picker
- Choose another design
- Font is now that what you chose previously

@dubielzyk just wanted to confirm this should be the case?

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/87168/78127756-68d6c280-741d-11ea-92d4-af6bdb5ea395.png">

**Comment by dubielzyk** [comment]
I initially thought no, since they've made a choice. But if the previews on the Design step will show the theme default fonts, we should show the font defaults selected on the Fonts step too.

**Comment by sirreal** [comment]
Setting a different design should reset the selected font in the onboard store.
