### ISSUE TITLE
Gutenboarding: broken Coutoire design

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40654]
Something is wrong with "Coutoire" design:

https://public-api.wordpress.com/rest/v1/template/demo/coutoire/coutoire/?font_headings=Playfair%20Display&font_base=Fira%20Sans

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/87168/78144404-3b4b4280-7438-11ea-9be9-0f893016ed80.png">

**Comment by sirreal** [comment]
Hitting this demo point was likely an error. This should have used the `bowen` template:

https://github.com/Automattic/wp-calypso/blob/9c5f091e00815b37f9a5790d4939ad4be9e36950/client/landing/gutenboarding/available-designs.ts#L63-L74

This works:

https://public-api.wordpress.com/rest/v1/template/demo/coutoire/bowen/?font_headings=Playfair%20Display&font_base=Fira%20Sans

**Comment by simison** [comment]
yass, fixed in https://github.com/Automattic/wp-calypso/pull/40662
