### ISSUE TITLE
Media: Video limits shown for some Jetpack plans when they shouldn't be

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#40667]
#### Steps to reproduce

1. Have a Jetpack site on a Professional plan connected to WP.com.
2. Navigate to: https://wordpress.com/settings/performance/www.example.com
3. In the Media section, turn on "Enable fast, ad-free video hosting". 
4. See a quota: 

![Screen Shot on 2020-04-01 at 13:38:45](https://user-images.githubusercontent.com/5512652/78168543-23ff5b80-741e-11ea-9903-898df4b64600.png)

#### What I expected

I have a Jetpack Professional plan. In our marketing, we say it has unlimited video hosting:

https://jetpack.com/pricing/

![Screen Shot on 2020-04-01 at 13:39:43](https://user-images.githubusercontent.com/5512652/78168624-42655700-741e-11ea-8642-09180d2e8d49.png)

Our support doc indicates that we actually do have a soft limit:

https://jetpack.com/support/video-hosting/

> Jetpack includes unlimited video hosting for all users with Jetpack Premium and Professional plans. Please note that there is a 2TB soft-limit on storage. If this limit is reached please reach out to Jetpack support and we can increase it for you.

#user-report in 2838555-zen, but also confirmed by myself and @mzakariya

**Comment by travisw** [comment]
I think this is related to the backend change here: D40523-code that was part of [this PR](https://github.com/Automattic/wp-calypso/pull/40268).

I'll take a look.

**Comment by travisw** [comment]
Fix in review: D41229-code

**Comment by travisw** [comment]
This should be fixed now.
Thanks for the ping @aheckler.
