### ISSUE TITLE
Gutenberg: Up/Down arrows don't work with Full Width alignment

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#40665]
#### Steps to reproduce

1. Create a new page
2. Add the Cover block
3. Set its alignment to Full Width

#### What I expected
To be able to use the Up/Down arrows to move the block around.

#### What happened instead
You can't click on the Up/Down arrows.

#### Browser / OS version
Chrome 80.0.3987.162
OS X 10.15.3

#### Screenshot / Video
![UpDownArrows](https://user-images.githubusercontent.com/16104522/78144343-dc6cd580-7405-11ea-83c4-0d1c01e66b87.gif)

#### Context / Source
#dogfooding

**Comment by AtrumGeost** [comment]
I got the same issue inside a QS session.

Adding the follow-up ticket for reference: 2847150-hc

**Comment by carinapilar** [comment]
Not sure if it's the exact same issue, but the arrows also aren't available when you have this block structure: Group > Column > Paragraph, if you set the Group block with Full Width, you can't see the arrows on the blocks inside the Columns one:

![GroupColumnParagraph](https://user-images.githubusercontent.com/16104522/78459938-2e765b00-7693-11ea-8a94-4ea6b4a17603.png)

**Comment by marcuswisecaesar** [comment]
Had the same issue reported here: 20164511-hc

**Comment by khristiansnyder** [comment]
I noticed this issue when working with our Alves page template.
I was able to recreate on my own site by simpling adding a cover block and setting it to full width. It also happens with a full-width image block. I feel like it has become difficult to re-order blocks in general with the latest updates, especially now that you must hover on the toolbar just to get the re=order arrows.

**Comment by jordesign** [comment]
Another case of this in 2910319-zen.

A quick and nasty workaround I have suggested to the user is to temporarily switch to 'Wide Width' for elements to move them - then switch back to Full width.
https://cloudup.com/c5vAqsPu_kB

**Comment by ash1eygrace** [comment]
I personally ran into this issue with the arrows disappearing on full-width blocks. 

It seems to happen with all full-width blocks. I replicated on:
- Grid Layout Block 
- Cover Block
- Gallery Block
- Blog Posts Blocks
- Video Blocks
 
Tested with multiple sites on WordPress.com.
OS X 10.15.4
Chrome/81.0.4044.129 and Safari Safari/605.1.15

**Comment by lancewillett** [comment]
Is this also an issue in core Gutenberg? If so, we should escalate and report there first rather than only fixing on WordPress.com. CC @Automattic/create gardeners.

**Comment by ash1eygrace** [comment]
This will be fixed soon, with the upcoming Gutenberg 8.0.0 release on WordPress.com. Closing this now!
