### ISSUE TITLE
The Scan & Backups cards are stacking on large screen (JP Connect page)

### ISSUE THREAD

**Issue by eeeeevon13** [Automattic/wp-calypso#40679]
#### Steps to reproduce
On Desktop/laptop, Mac, chrome
1.WP admin Jetpack Connect prompt
2. Jetpack Connect Plans page

#### What I expected
I expected to see the backups and scan cards side by side

#### What happened instead
They are stacking 

#### Browser / OS version
Mac, chrome Version 80.0.3987.149
#### Screenshot / Video

<img width="827" alt="Screenshot 2020-04-01 16 18 40" src="https://user-images.githubusercontent.com/49159284/78187714-8a8f7400-7434-11ea-9a00-a20ebe91904a.png">

**Comment by Aurorum** [comment]
Would something like this be better? (cc @keoshi)

<img width="1520" alt="Screenshot 2020-04-02 at 11 25 12" src="https://user-images.githubusercontent.com/43215253/78238649-ba8e5400-74d4-11ea-8199-8f7a57ff8bd2.png">

**Comment by keoshi** [comment]
Hi, @Aurorum ! Nice to see you here again!

It looks good but it's hard to say for sure without looking at the entire page at the same time. For reference I think it would be enough to:

- Get rid of this `max-width` property:

https://github.com/Automattic/wp-calypso/blob/63d934dfd230a449589570294861646f4d0b92a0/client/jetpack-connect/style.scss#L1153

- Add the same property as the following to https://github.com/Automattic/wp-calypso/blob/597b50b0df8b81b7f47d1193fc08bff78236d341/client/my-sites/plans-features-main/style.scss#L12:

https://github.com/Automattic/wp-calypso/blob/e1047e737ef2c9719436328c93f061b1693b7c34/client/my-sites/plan-features/style.scss#L600-L602

**Comment by Aurorum** [comment]
Thanks @keoshi! I started a PR in #40777 for this issue so that it can be compared within the entire page. I think that a few more tweaks were needed than just those though, as I tried to replicate the breakpoints of the Plans table above it. :)
