### ISSUE TITLE
Remove (ListEnd) footer from non-infinite scroll pages

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#40686]
This came from: https://github.com/Automattic/wp-calypso/issues/40533

ListEnd is supposed to be for infinite scrolling pages like Reader and /people to denote that you've reached the end of the page. We should remove it from static pages like /me. I don't know why it appears in some static pages, but not in others.. seems pretty random.

@Automattic/dotcom-manage-design

**Comment by Aurorum** [comment]
The reason it appears in `/me` is that it fixes a bug where Inline Help was preventing buttons with Profile Links from being clicked on mobile: #29815

I don't think it can be removed without an alternative fix to #26257.

**Comment by jancavan** [comment]
> I don't think it can be removed without an alternative fix to #26257. Would some added empty padding be better?

Thanks for the background @Aurorum. I was not aware this was the reason for adding the (W) logo to some places.

We should just add an extra space on mobile to fix the floating Help button overlapping with links issue. The (W) logo should just be used for denoting list end.

**Comment by Aurorum** [comment]
Never mind me, it looks like @sixhours took care of that in #39201! PR to remove it from `/me` in #40756. :)
