### ISSUE TITLE
Activity: Confusing (guided tour) tooltip

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#40684]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/activity-log/[site]
2. Click on Activity under Tools
3. There's a dark tooltip that shows up tell you what this page is about

![Screen Shot 2020-04-01 at 4 06 14 PM](https://user-images.githubusercontent.com/4924246/78194747-d9d4a500-7432-11ea-8256-01f9c9d673d7.png)

#### What I expected

For anything descriptive about this page to go on the banner. 

In this case:

1. There are two ways we are describing what this page is all about - first is on the banner and second, on the dark tooltip.

2. It's quite obtrusive. I click on Activity and this tooltip shows up all of a sudden.

In general, the purpose of a tooltip like that is to draw a user's attention to something on the page. In this case, I already clicked Activity, but it's trying to draw my attention like I never clicked on it.

I think both should be omitted; there should be a regular heading/subheading on this page similar to My Home:

![Screen Shot 2020-04-01 at 4 13 33 PM](https://user-images.githubusercontent.com/4924246/78195114-c7a73680-7433-11ea-8754-59c223b098ad.png)

#### Browser / OS version

Mac OS Mojave 10.14.6
Chrome Version 80.0.3987.149 (Official Build) (64-bit)

cc @Automattic/jetpack @Automattic/jetpack-design

**Comment by Aurorum** [comment]
> I think both should be omitted; there should be a regular heading/subheading on this page similar to My Home:

I opened a PR in #40695 to remove the guided tour and add the subheading. :)

**Comment by folletto** [comment]
I'm not sure if we use these in any onboarding, let us review first.

**Comment by jeffgolenski** [comment]
I think we can go ahead and remove it. As far as I know, it's not part of the Jetpack onboarding flow.

**Comment by Aurorum** [comment]
I think that's correct; it only seems to appear _after_ the user has opened the Activity Log (in which case, the banner also greets them)
