### ISSUE TITLE
Jetpack Plugins: Auto-updating plugins via Jetpack should be logged

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#407]
Reported by dbspringer: After configuring my Jetpack site to auto-update plugins I often wonder, "have they updated recently? What were the updates?" I believe there is an email if a plugin auto-updated via Jetpack fails, but I don't believe there is any kind of notification if a plugin has been successfully updated.

It would be great if there was an email or a notification (perhaps configurable) that would alert the user that Site X updated Plugin Y (link to changelog), and Plugin Z (link to changelog).

Idea: Rather than notifications of some kind, maybe it'd make sense to just keep some sort of log, and have a page/popup/whatever accessible that would allow you to see the auto-update history of your account?

We'd have to build it into Jetpack, but we could display it in Calypso like so:

![bc148dbe-a08e-11e4-836e-ab9802e12d9f](https://cloud.githubusercontent.com/assets/11487924/11321223/d8852ef4-9084-11e5-8579-39a54666662e.png)

Suggestion: we could fire something back from the remote site whenever an update occurs, then log that on our end.

**Comment by rickybanister** [comment]
This issue represents just about an entire milestone, it's definitely not bug scrub material. I'll circle back in the new year with some design work before we determine a scope of something like this.

**Comment by rickybanister** [comment]
The activity log will be taking care of this! yay!
