### ISSUE TITLE
Gutenboarding: remove events template

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40700]
Remove `rivington` (aka "events") template:

<img src="https://user-images.githubusercontent.com/87168/78236026-21663a00-74e2-11ea-9791-4288f2d735f9.png" alt="" width="200" />

Files at `static/page-templates` and `static/page-templates/design-screenshots/rivington_rivington_rivington.jpg`

It's not ready for showtime and needs more work (p1585748085048700-slack-dotcom-view-design).

After https://github.com/Automattic/wp-calypso/pull/40587 is in, the slug can just be removed from `featured` array but might be worth just removing the whole template so that it's not un-used code around.

cc @ianstewart

**Comment by ockham** [comment]
> Remove `rivington` (aka "events") template:
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/87168/78236026-21663a00-74e2-11ea-9791-4288f2d735f9.png">
> 
> Files at `static/page-templates` and `static/page-templates/design-screenshots/rivington_rivington_rivington.jpg`

@simison I can't for the life of me find `static/page-templates/design-screenshots/rivington_rivington_rivington.jpg`. Can you confirm that it's there and not a by-product of #40632 that happened to linger? :grimacing:

**Comment by ockham** [comment]
> > Remove `rivington` (aka "events") template:
> > <img alt="" width="200" src="https://user-images.githubusercontent.com/87168/78236026-21663a00-74e2-11ea-9791-4288f2d735f9.png">
> > Files at `static/page-templates` and `static/page-templates/design-screenshots/rivington_rivington_rivington.jpg`
> 
> @simison I can't for the life of me find `static/page-templates/design-screenshots/rivington_rivington_rivington.jpg`. Can you confirm that it's there and not a by-product of #40632 that happened to linger?

I'm going to roll with that theory for now. If that asset turns up somewhere, we'll remove it separately.
