### ISSUE TITLE
Sharing: update the wording on Facebook connections to remove "news feed" mention

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#40709]
A user reported that they felt the wording on the Facebook connections setting in Calypso was misleading. 

As we can’t share to a personal “feed” anymore and only to a page created by the user, they felt this wording was misleading and should say share to your pages or similar (screenshot) - https://d.pr/i/EJDtps

Is it worth changing the wording to "pages" rather than "feeds" to be clearer? 

#19840215-hc

**Comment by lancewillett** [comment]
This is a good suggestion, thank you.

Better text would be, "Share to your Facebook page."

**Comment by lancewillett** [comment]
After fixes:

<img width="983" alt="Screen Shot 2020-04-04 at 09 33 11" src="https://user-images.githubusercontent.com/66797/78456233-4fb95600-7657-11ea-8e58-2a7842f535a1.png">

**Comment by lancewillett** [comment]
@rickmgithub Fix is now in production. Thanks again for the report.
