### ISSUE TITLE
Gutenboarding: design picker mobile layout alignment

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#40712]
Design picker layout on mobile needs some refinement. We should follow closely the designs.
Mentioned in https://github.com/Automattic/wp-calypso/pull/40632#issuecomment-607108729

**Comment by roo2** [comment]
I think this is resolved already? 
The comment https://github.com/Automattic/wp-calypso/pull/40632#issuecomment-607108729 spoke of alignment between the two columns being off but on mobile it is only showing one column of designs.

<img width="321" alt="Screen Shot 2020-05-04 at 3 15 28 PM" src="https://user-images.githubusercontent.com/22446385/80937903-4409ac80-8e1a-11ea-950d-d61d95addda1.png">

**Comment by simison** [comment]
yep, I think this is good now 👍
