### ISSUE TITLE
Gutenboarding: design picker images are shorter than thumbnail area

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#40711]
When we introduced static, tall screenshots in #40632 we discovered some of then are leaving empty space inside their thumbnail.

![image](https://user-images.githubusercontent.com/14192054/78265475-24c2eb00-750d-11ea-9d6e-f5008b00dbb0.png)

Luckily they're all the ones with a white background so it's not that bad looking. 

Maybe columns should float as "masonry" (i.e. upper edges won't be aligned and it's ok to have different height thumbnails)?

**Comment by roo2** [comment]
I added a fix for this but it actually makes the situation worse because now the edges of the theme thumbnail are cropped off 😂
