### ISSUE TITLE
Block-Editor: When using fallback in wp-admin we don't redirect correctly to WordPress.com

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40727]
We sometimes cannot render the block-editor in WordPress.com/block-editor and fallback to wp-admin. When this happens, clicking on the W anchor shown below should take us back to WordPress.com.

#### One of the easiest ways of reproducing this is:

- Create a site, add a business plan, transfer to Atomic by enabling plugins
- Install and activate a plugin that doesn't work well inside of our iframe integration, like elementor. See also PCYsg-lOu-p2 for other plugins that will trigger this fallback.
- Navigate to WordPress.com/posts
- Add or Edit a post
<img width="1015" alt="Screen Shot 2020-04-02 at 3 03 38 PM" src="https://user-images.githubusercontent.com/1270189/78304382-76f71280-74f3-11ea-982b-05c54bd9eb61.png">

- Notice that we are redirected to wp-admin instead of the WordPress.com/block-editor as expected.
- Click on the W anchor to take us back
<img width="1019" alt="Screen Shot 2020-04-02 at 3 03 59 PM" src="https://user-images.githubusercontent.com/1270189/78304414-870ef200-74f3-11ea-98b4-bebce75badb8.png">

Expected: We navigate back to WordPress.com/posts
Actual:
<img width="1001" alt="Screen Shot 2020-04-02 at 3 04 38 PM" src="https://user-images.githubusercontent.com/1270189/78304446-a1e16680-74f3-11ea-9043-bc822d682717.png">

**Comment by kwight** [comment]
I think at one point the URL for that link (when it was the old chevron) was controlled by `calypsoifyGutenberg.closeUrl` – that might be a place to start looking.

**Comment by noahtallen** [comment]
yeah, I think that link still controls it if it is iFramed. Just need to find where it happens locally

**Comment by noahtallen** [comment]
we need to update this selector: 

https://github.com/Automattic/jetpack/blob/4e716c7bdf6aae6dd5fe39c9029a509c7c2bee6f/modules/calypsoify/mods-gutenberg.js#L15-L21

**Comment by noahtallen** [comment]
this should fix it: https://github.com/Automattic/jetpack/pull/15322
