### ISSUE TITLE
Framework: Replace `component-tip` with a React tooltip component

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#4072]
Rationale -- `component` stuff is largely unmaintained, and doesn't play well with node (see `7113-gh-calypso-pre-oss`), which will get in the way of server-side rendering.

One option would be to fix everything down the dependency chain like I've started [here](https://github.com/component/css/pull/17), but we might as well consider switching to something like https://github.com/wwayne/react-tooltip or https://github.com/react-component/tooltip

While we're at it, we should also replace `<Popover>`'s use of `click-outside` (which is also DOM dependent) with `react-click-outside` (#5181).

Opinions?

/cc @seear @mtias

**Comment by rralian** [comment]
As mentioned in #5101 users seem to have quite a bit of trouble with the existing tooltip. I haven't dug at all, but I could see how a DOM-manipulating tool could work poorly with a React system. I would definitely vote for replacing `component-tip` with a react-friendly alternative.

**Comment by retrofox** [comment]
100% agree. When we did that component I think React was an unknown library :-o

**Comment by rralian** [comment]
@nb unless someone else has bandwidth to run with this, maybe this would make for a decent trial project? I _think_ it's deep enough to be interesting... certainly requires a lot of testing.

**Comment by ockham** [comment]
Fixed by #7217.
