### ISSUE TITLE
Jetpack Connect: see Premium on the Search connect page when logged in

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#40724]
The text for the connect screen is referencing Premium plan rather than Search plan (or something more generic is fine too).

#### Steps to reproduce

1. Starting at URL:
2. Clicking through from https://jetpack.com/upgrade/search/ (but the new version I am about to deploy) while I am logged in.
3. Go to https://wordpress.com/jetpack/connect/jetpack_search
4. The text is incorrect

#### What I expected

This is what I see when incognito:

<img width="618" alt="Screen Shot 2020-04-02 at 1 15 38 PM" src="https://user-images.githubusercontent.com/820871/78292333-18766800-74e4-11ea-915f-373ef26a2cbe.png">

#### What happened instead

When logged in

<img width="640" alt="Screen Shot 2020-04-02 at 1 10 13 PM" src="https://user-images.githubusercontent.com/820871/78292358-20cea300-74e4-11ea-9d12-5a5b81475aea.png">

#### Browser / OS version

Chrome on Mac

**Comment by AnnaMag** [comment]
I could not repro on FF and Chrome, on Ubuntu. Could you re-test after recent fixes?

**Comment by gibrown** [comment]
So confusing... I am still seeing it.

**Comment by AnnaMag** [comment]
After some more trials it stopped working correctly for logged-out account, but for logged-in yes.

Noting that it is an issue for Scan. CTA on JP.com goes to `https://wordpress.com/jetpack/connect/**premium**?cta_id=landing-page-scan-primary-cta&cta_from=upgrade_scan`, showing Premium plan. /cc @enejb .

**Comment by AnnaMag** [comment]
Atm, after rebasing, I cannot reproduce it anymore under any circumstances.

**Comment by gibrown** [comment]
I haven't been seeing this with my recent testing and a lot has changed. Close it for now?

**Comment by AnnaMag** [comment]
Yes, let's close for the time being.
