### ISSUE TITLE
Customer Home: Use the notifications panel to prompt site setup completion

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#40735]
As mentioned in #40233, we decided to utilize the existing notification panel to prompt site setup completion rather than adding a dot to the sidebar.

> * The original problem of users getting lost was brought up before My Home became the default logged in page. The risk of not knowing where to go has been lowered by making My Home the default.
> * The sidebar doesn’t show on mobile but the notification bell is in the masterbar so it’s always visible.
> * We tried adding a dot to the inline help icon in the bottom right corner but it didn’t perform as expected. There are likely other factors in play there, but it’s worth noting.
> * If we start adding dots all over the place, the dot starts to lose meaning. Dot fatigue.

I think this is a server-side change, but I'm adding here for tracking purposes.

#### Design
If it makes sense for implementation, let's customize the message based on which task is up next. I'm still working on the language and illustrations for all the pre-launch tasks, but here's one example:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/448298/78319063-53a08780-7534-11ea-879d-da763f7feae0.png">

#### Rules
We'll prompt, at most, two times total (not per task). We can start with these intervals and track engagement to see if we need to make any adjustments here:

* Day 3
* Day 10

We'll show a new notification if:

* The checklist is incomplete OR
* The site is not launched

#### Emails
We're not sending any accompanying emails at this time. New users get quite a bit of email from us and we don't want to add noise.

**Comment by lcollette** [comment]
What's the status of this, @danhauk?

**Comment by danhauk** [comment]
@lcollette This hasn't been prioritized so it fell through the cracks. Thinking about this now that the new layout has launched, I'm wondering if we should wait to see if that has any effect on checklist completion rate. The new checklist is more friendly and prominent than it was in the old layout which could be a factor. Thoughts?

**Comment by davemart-in** [comment]
Since we just added the site setup completion bar to the My Home link in the left nav, I'd vote that we close this issue out. Happy to resurrect it if folks are still struggling.
