### ISSUE TITLE
Block Editor: Redo welcome modal contents

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40739]
For WordPress.com, we're going to customize block editor welcome modal.

You can manually show the welcome modal via this menu:

<img width="379" alt="Screenshot 2020-04-03 at 09 55 28" src="https://user-images.githubusercontent.com/87168/78333354-5b8f1480-7592-11ea-9c79-7977ddeb9fac.png">

### Currently:

<img width="715" alt="Screenshot 2020-04-03 at 09 42 14" src="https://user-images.githubusercontent.com/87168/78332639-0f8fa000-7591-11ea-9796-a82f9f6c1c27.png">

#### Goal:

<img width="739" alt="Screenshot 2020-04-03 at 09 53 04" src="https://user-images.githubusercontent.com/87168/78332650-161e1780-7591-11ea-83d6-2c7b9c51f749.png">
<img width="758" alt="Screenshot 2020-04-03 at 09 53 08" src="https://user-images.githubusercontent.com/87168/78332651-17e7db00-7591-11ea-9c95-795eddceeaa8.png">
<img width="746" alt="Screenshot 2020-04-03 at 09 53 12" src="https://user-images.githubusercontent.com/87168/78332682-246c3380-7591-11ea-9613-fb3feca4ebc7.png">
<img width="750" alt="Screenshot 2020-04-03 at 09 53 16" src="https://user-images.githubusercontent.com/87168/78332687-27672400-7591-11ea-87b0-6fce5b10bee3.png">

Could be done in two separate PRs:
- [ ] wpcom specific Content
- [ ] wpcom specific layout/styles

@olaolusoga @rickybanister @mtias these new styles seem better anyway, so we could update them  in core too?

**Comment by mtias** [comment]
> these new styles seem better anyway, so we could update them in core too?

We have this other proposal in core to follow: https://github.com/WordPress/gutenberg/issues/19209

**Comment by simison** [comment]
Excellent, thanks! @olaolusoga @dubielzyk when things are little calmer would be great if you can elaborate some good stuff from these designs to that core issue.

E.g. having "next" as a button vs text seems like a great improvement. I also like clear and more accessible "skip" vs "X", although I appreciate these might be subjective. :-)

**Comment by davipontesblog** [comment]
Sharing some feedback here as suggested by @simison. Context: p58i-8QA

In the editor as a new user, I feel overwhelmed ... Here are a few things I need to know at this point:
a. This is my homepage. I can make any changes I want here, and they will only affect this one page. To make changes to other pages on the site I am able to do this clicking on the top left corner and choosing a different page in Site > Pages (this might not be relevant once we are able to do page-switching directly in the site editor in FSE)
b. I should be able to click on what I see and change as I want. I can also add more by using the + icons, and delete blocks I don’t need. I need to know **how** though.
c. There are help guides in the bottom right corner if I need help, and how to use them. I can also contact support there if I want to talk to someone.

I hope this helps!
