### ISSUE TITLE
My Home: Create a section for recommended tasks

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#40734]
To help users after they launch their site, we want to provide some guidance for what to do next on Customer Home.

This issue is more about creating a section in the layout that spans the full width. Here's the new grid layout we're going to work towards to create a stronger hierarchy of content. I'll leave it up to eng for best way to update the home layout API for the new section across the top.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/448298/78675668-61973500-78b3-11ea-8530-382cbcab90d1.png">

Here's an example design post-launch:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/448298/78687553-454ec480-78c2-11ea-934e-6a4b2b6b70b5.png">

Here's how it would work with the current implementation of the site setup checklist:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/448298/78315032-ce17da00-7529-11ea-8994-4b6d7b290c40.png">

The design of the card itself is not final, but we're aligned on the layout. Having it span the full width creates a stronger hierarchy on the page.

**Skip for now** (task-specific)
* This would dismiss the card for 2 or 3 days and the next task would appear in its place.
* If there is no current task after that interval (because they were dismissed or completed), the skipped task would show up again.
* If the task is skipped again, it's dismissed for a longer interval like 7 days.
* When the task shows up the third time, "Skip for now" becomes "Don't show again" and is dismissed forever.

**Coming down the pipeline in separate issues to help us get here:**
* Update the Stats and Feature Discovery modules design to work with the wider desktop layout.
* Design for a neutral container to pull in relevant blog content with title, summary, and featured image.

**Comment by gwwar** [comment]
Eng Work here is to:

- Update the home layout API to add the new section, we can maybe refactor to primary, secondary and tertiary, or keep primary, secondary and create a new name for the primary task section.
- Add the new Connect Social media Accounts Card

Feel free to break this out into multiple issues.

We might want to look into if a guided tour makes sense or if we should prioritize a video for connecting social media.

**Comment by danhauk** [comment]
Here's the new grid layout we're going to work towards going forward. This creates a stronger hierarchy of content. I'll leave it up to eng for best way to update the home layout API for the new section across the top as @gwwar mentioned above.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/448298/78675668-61973500-78b3-11ea-8530-382cbcab90d1.png">

Coming down the pipeline in separate issues to help us get here:
* Update the Stats and Feature Discovery modules design to work with the wider desktop layout.
* Design for a neutral container to pull in relevant blog content with title, summary, and featured image.

I've added this to the issue description above too.

**Comment by Aurorum** [comment]
Is anyone already intending to create the "Connect social media accounts" banner or is it okay if I spin up a PR for it? I think it'd go best with a guided tour rather than a video, personally.

**Comment by Aurorum** [comment]
(I'm assuming nobody is but correct me if wrong!)

@danhauk Two quick questions: is it possible to share the task illustration, and what is the font of the heading? 

<img width="1156" alt="Screenshot 2020-04-09 at 22 46 17" src="https://user-images.githubusercontent.com/43215253/78943531-f799ae00-7ab3-11ea-9bb8-c1a5301f84f4.png">

**Comment by gwwar** [comment]
> Is anyone already intending to create the "Connect social media accounts" banner or is it okay if I spin up a PR for it? I think it'd go best with a guided tour rather than a video, personally.

Totally fine @Aurorum! Just be aware that we haven't thought through all the requirements yet for it if that's okay.

cc @kwight @mmtr since I saw the layout PR updates in https://github.com/Automattic/wp-calypso/pull/41000

**Comment by Aurorum** [comment]
PR for this issue in #41018 :)

**Comment by mmtr** [comment]
I think we can close this one out. #41145 added the basic skeleton for the new layout sections and #41018 added the task for connecting the accounts.
