### ISSUE TITLE
Heading and Image Block Settings Got reset

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#40741]
The site https://barberyknittingartwork.com/ recently had the settings for some of the blocks reset on its own. The issues I'm reporting here are for the **Heading blocks** and **Image blocks inside columns**.

An example page is https://barberyknittingartwork.com/about-alpaca/.

1. Starting at URL: https://wordpress.com/block-editor/page/barberyknittingartwork.com/685
2. The headings were set to _h3_ previously but got reset to _h1_. The report from the user is the following:

LEARN ABOUT ALPACA (heading should be H3)
CARING FOR YOUR ALPACA WINTER ACCESSORY (heading should be H3)
WE SPECIALIZE IN THE FOLLOWING YARNS (heading should be H3)

3. The image blocks in columns previously had their size set to 25% but they are reset to default now. 

These changes aren't reflected in the revisions from what I can see.

This is just one of the pages that got affected by this but we left this onne in its current state and didn't make any updates.

#### Browser / OS version

Latest version of Chrome, Mac 10.13.6

#### Screenshot / Video

https://d.pr/i/aJJalw/iFmP4D6HAO
https://d.pr/i/S4CUxv/1ceDeXtsEc

#### Context / Source

2839120-zen

@simison Is it possible that the latest update to Gutenberg version 7.7.1 on Simple Sites caused this? The user originally reached out to us on April 1st.

**Comment by simison** [comment]
@davoraltman I'm first time hearing about such issue, but let's see if we get more reports here. :-)

**Comment by tijosh** [comment]
I don't believe this user has experienced a bug of any kind. There are multiple page revisions in the pages they cite which show clear minor edits to the heading levels. These are revisions from September 2019.
