### ISSUE TITLE
Gutenboarding: handle non-alphanumeric title in domain picker

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40748]
When customer doesn't enter title at intent capture step, we don't potentially have anything for the domain picker to do the search:

<img width="1049" alt="Screenshot 2020-04-03 at 14 07 38" src="https://user-images.githubusercontent.com/87168/78354567-c8b3a180-75b4-11ea-9bc1-b284d8a21194.png">

<img width="442" alt="Screenshot 2020-04-03 at 14 08 24" src="https://user-images.githubusercontent.com/87168/78354586-cea98280-75b4-11ea-924c-b22e52e0dd75.png">

Since they filled vertical, we could use that as search term to ensure we have some results:

<img width="620" alt="Screenshot 2020-04-03 at 14 12 07" src="https://user-images.githubusercontent.com/87168/78354737-20520d00-75b5-11ea-9e32-1b97f5d138e3.png">

This is a pretty minor issue, but when I enter non-ASCII symbols in the title (e.g. emoji), the domain picker gets stuck with API response `Query parameter must contain alphanumeric characters`:

<img width="620" alt="Screenshot 2020-04-03 at 14 12 07" src="https://user-images.githubusercontent.com/87168/78354798-319b1980-75b5-11ea-81db-c7645ea686bb.png">

In that case, we can also fire the query with vertical.

### Action items:
- [x] Use vertical as a fallback for domain search when the title isn't available https://github.com/Automattic/wp-calypso/pull/40770
- [ ] ...or isn't alphanumeric
- [ ] If there's nothing we can use, decide what to do. We'll anyway have to randomize free URL so let's use the same mechanism here?

**Comment by ockham** [comment]
I'm not sure it makes sense to fall back to the vertical if the title contains non-alphanumeric characters -- the vertical might be user-specified, too, and thus can also contain non-alphanumeric chars :sweat_smile: How about removing the non-alphanum characters from both when looking up domain suggestions?

**Comment by ockham** [comment]
Maybe I've been misreading you -- did you mean site titles containing _only_ non-alphanumeric characters?

**Comment by simison** [comment]
If site-title isn't alphanumeric, domains API can't return anything apparently. https://github.com/Automattic/wp-calypso/pull/40770 is sufficient enough for now. I'll mark the rest of the follow-ups as a lower priority.

**Comment by yansern** [comment]
I'd like to reserve this as one of the good first issue for @ciampo! Thanks!

**Comment by yansern** [comment]
This is fixed in https://github.com/Automattic/wp-calypso/pull/48031 and https://github.com/Automattic/wp-calypso/pull/48399.
