### ISSUE TITLE
Gutenboarding: Indicate selected domain in the header

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40747]
Once the domain is selected from the list, indicate it in the header's domain button:

Selecting free domain here:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/87168/78349065-b1bc8180-75ab-11ea-9de1-c6835bc21bb1.png">

Should show up in the header like this:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/87168/78349105-bd0fad00-75ab-11ea-85ec-f9ea7366b856.png">

@dubielzyk @olaolusoga right? :-)

**Comment by dubielzyk** [comment]
Yep. Once something is chosen, we should show it in the header. Before the domain dialog is opened, we should show the recommended option :)

**Comment by simison** [comment]
Related; 
- https://github.com/Automattic/wp-calypso/pull/40742 (making it possible to "select" paid domains via radio input)
- https://github.com/Automattic/wp-calypso/issues/40746 (bringing users back to onboarding after domain purchase, the purchased domain should be visible in the header)
