### ISSUE TITLE
Reader: Comments button not working

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#40759]
#### Steps to reproduce

1. Starting at URL: wordpress.com/read
2. Find a post in the reader and click the comment icon

#### What I expected
I expected to be able to view comments
#### What happened instead
Nothing
#### Browser / OS version
Chrome 80
#### Screenshot / Video
Seeing this in the console:
<img width="630" alt="Screen Shot 2020-04-03 at 8 15 44 AM" src="https://user-images.githubusercontent.com/31110506/78370218-989fda80-7583-11ea-895e-db86455491c8.png">

#### Context / Source
This was caught by e2e tests

I believe it was caused by https://github.com/Automattic/wp-calypso/pull/40655

**Comment by sgomes** [comment]
Thanks, @bsessions85! Investigating.

**Comment by sgomes** [comment]
Issue identified and fixed. Preparing PR.
