### ISSUE TITLE
Gutenboarding: Signup/Login design fixes

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40769]
The signup and login page is looking good. I've outlined some polish fixes in order of priority:

Signup page:
- [ ] Padding on input fields should be `padding: 18px 14px`
- [ ] Make sure the alignment is correct to the mocks. Especially the text under the headline. [Screenshot](https://d.pr/i/NBrALX)
- [ ] We removed making this a modal so it doesn't have the X in the top right anymore. This way we can also link to it more easily if it's a separate page. Is this doable?

Login page:
- [ ] Create account link should go back to Signup form
- [ ] Can we use the same input field styling as the Signup page?
- [ ] Widen the container so that the headline doesn't go on two lines
- [ ] Not make the buttons full-width
- [ ] Make links hover color blue instead of pink

The signup page is looking great. I'm assuming we're reusing a lot oof the login page from WordPress.com. The closer we can get it looking like the mocks the better :)

**Comment by ramonjd** [comment]
> We removed making this a modal so it doesn't have the X in the top right anymore. This way we can also link to it more easily if it's a separate page. Is this doable?

Not before the call for testing unfortunately. 

Appears as though the design `x` was removed on March 30 in the Figma file. We'll have to add this to the backlog.

There are also a couple of considerations to take into account when changing the modal into a page, for example, managing the browser history/navigation flow in logged out/logged in states.

**Comment by ramonjd** [comment]
https://github.com/Automattic/wp-calypso/pull/40795 is ready to review

I'm opening and closing the signup modal via a query param for now. 

I'll create an issue to move it back to a page-only version tomorrow. 👍
