### ISSUE TITLE
Gutenboarding: template picker shows incorrect template in the editor

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40766]
![image](https://user-images.githubusercontent.com/87168/78382487-a1be9500-75df-11ea-85f3-e08aac766829.png)

We can solve this by removing the thumbnail preview and leaving the "Change Layout" button intact.

See: pbAok1-BW-p2#comment-1566

**Comment by noahtallen** [comment]
Theoretically, the post should have some meta associated with it saying what the name of the template is. I think this has been really inconsistent for a while, but I've never been sure why
