### ISSUE TITLE
Site setup checklist: Add steps to guide users better towards launch

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#40775]
The current list of tasks in the checklist is not very helpful for our users.

* We've over-indexed on time to launch and stripped the pre-launch tasks to almost nothing. This is not very helpful in actually getting people to launch.
* As pointed out by @boonerang , users’ mental models of time to launch do not align with the current list of tasks. They expect it to take some time and are hesitant to launch with imperfections.
* Research shows people are really hesitant to launch a site with imperfections.

We'll want to make sure to keep an eye on the following metrics when implementing these new tasks:
* Site launch percentage
* 30-day retention

Here's a proposed list of pre-launch tasks based on the current state of signup. Copy has been reviewed and approved.

### Name your site [this exists, just a copy update]
Give your new site a title to let people know what your site is about. A good title introduces your brand and the primary topics of your site.

[ Name site ] 
_Estimated time: 1 minute_

### Learn how to use the block editor
Watch a quick video to learn how to add, move, edit, and customize blocks like a pro. These are the basics you need to shape the layout of your media-rich pages and posts with ease. 

[ Watch video ]
_Estimated time: 2 minutes_

CTA action will open a modal to view the block editor overview video, currently in progress. We may need to wait on implementing this one depending on timeline of other moving pieces.

### Update your Home page
We’ve created the basics, now it's time for you to update the images and text. Make a great first impression. Everything you do can be changed anytime.

[ Edit Home page ]
_Estimated time: 15 minutes_

### Update your Contact page
We’ve started you with sample information and a simple contact form. Update this to let visitors easily get in touch. 

[ Edit Contact page ]
_Estimated time: 10 minutes_

Can we link directly to the contact page created when the site is created? If not, we'll have to link to the Pages section.

### Personalize your About page
Build trust and tell your story. How did you get started? What do you have to offer? Your About page is an introduction that can influence how people see you or your business.

[ Edit About page ]
_Estimated time: 10 minutes_

### Get a custom domain (only if they have a domain credit available)
A domain is the site address people type to visit your site. Show the world you’re serious. Sites with custom domains look more professional and rank higher in search engine results.

[ Find a domain ]
_Estimated time: 10 minutes_

CTA goes to domain search.

### Launch your site
You’ve done great so far and your site is ready to launch! Once your site is launched you can make changes to anything at any time. We’ll guide you with tips to help grow your site.

[ Launch site ]
_Estimated time: 1 minute_

----

There will need to be some kind of goal capture piece immediately after signup. These tasks are focused more on traditional sites, rather than blogs. Blogs should have a different set of tasks, and we'll need to figure out what the user wants. That's a separate piece to this.

**Comment by lcollette** [comment]
This is now being managed by the Create team. Closing.
