### ISSUE TITLE
User sees Upsell for Premium plan to add Google Analytics when accessing Stats

### ISSUE THREAD

**Issue by rahul020691** [Automattic/wp-calypso#40786]
#### Steps to reproduce

1. Starting at URL: Go to My Sites → Stats
2. Click on Countries tab
3. Scroll down

#### Screenshot / Video https://d.pr/i/Ldq7E1

Another colleague Hafiz was able to replicate it too for user `hfzrhmn` on Business plan site https://old.black

 #user-report

**Comment by Aurorum** [comment]
This will be fixed by #40762, I think.

**Comment by sixhours** [comment]
Fixed. :) Please let me know if you notice further issues!
