### ISSUE TITLE
My Home: Verify the theme checklist mode still functions.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#40781]
There is a `checklistMode` of `theme` that is responsible for some celebratory notice content, but I haven't figured out how to trigger it to test it with the API. I assumed it was something to do with buying a premium theme, but I didn't manage to verify that.

Note that this should be worked on with #40773 , if it hasn't been merged yet.

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/customer-home/cards/notices/celebrate-notice/index.jsx#L59

**Comment by sixhours** [comment]
Confirming this no longer works, since we don't send folks to the checklist after they've purchased a single premium theme; we send them back to `/themes`. We can ignore/remove it.

**Comment by sixhours** [comment]
Nevermind, I found it thanks to @mmtr 's work in #40910!

You can see it in action when you create a site through `/start/with-theme`; the copy appears in the congratulations banner after checking out.

I personally think we could still remove this functionality, though, and it's enough to welcome the person to their new site.

**Comment by lcollette** [comment]
This is behaving as intended. We can close and remove as a maintenance issue later.
