### ISSUE TITLE
People: users should not be able to send invites to old followers of site

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#4078]
It's sometimes possible to send an invite to a user who's already following a site.

#### Steps to reproduce:
1. Find a blog where you have a follower since at least before November 2015 (exact date for bug unknown)
![old-follower](https://cloud.githubusercontent.com/assets/11487924/13815092/994112e0-eb5f-11e5-8ce2-0d4bc02e1115.png)
2. Log in to this blog as admin, and try to add the follower from step 1 above as a follower. You see that adding in their username does not produce any errors:
![can-add-old-follower](https://cloud.githubusercontent.com/assets/11487924/13815108/a5d73fb6-eb5f-11e5-834e-6d0affad4a22.png)
3. Click on 'Send invitation' and see that the invitation is sent

#### Instead I expected:
I expected to see an error when trying to add a user who's already following my blog, like this:
![newer-follower](https://cloud.githubusercontent.com/assets/11487924/13815292/710d7ccc-eb60-11e5-8562-496ba419cec2.png)
![error-for-already-following](https://cloud.githubusercontent.com/assets/11487924/13815293/710e011a-eb60-11e5-8962-bf0a42f2a62b.png)

#### Some digging
When looking at the old interface for this, I see that the invitation for the user I attempted to invite is still marked as waiting:
![marked-as-waiting](https://cloud.githubusercontent.com/assets/11487924/13815469/1005c6e0-eb61-11e5-96f0-8890796d4d0e.png)

**Comment by ebinnion** [comment]
Is the user a follower or an email follower?

From memory, the "Already  following" error only shows when a follower is an email-only follower. So, I wonder if this a UX issue where we should be showing the "Already following" error is a user is following by any combination of WP.com reader and/or email-only... Or if there is some sort of issue with our logic.

**Comment by v18** [comment]
@ebinnion - this happens with a follower, not an email follower.

**Comment by ebinnion** [comment]
I think the root issue here is that `testcupsoftea` is a WP.com follower and not an email follower. I tested this theory out by going to `/following/edit` while logged in as a test user.

When I was receiving emails for new posts, I noticed that the "Already following" error would show. But, when I toggled off emails for new posts, the invite would validate. I think we should show the "Already following" error if the user is following by WP.com read and/or email.

So, I went ahead and committed r133006-wpcom to fix that. Please let me know if that doesn't fix the issue for you.
