### ISSUE TITLE
Gutenboarding: Remove preview image manual steps

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#40797]
We can add a backlog task to make this easier.

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/40788/files/808b1ec4cb46a2b13d0ab63f91f2d1dd340f60ef_

**Comment by simison** [comment]
The script at `bin/generate-gutenboarding-design-thumbnails.js` is meant to be temporary — I'll close this since we really just wanna work on mshots instead.
