### ISSUE TITLE
Stats referrals link for the Reader leads to /home not /read

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#40816]
#### Steps to reproduce

1. Click on a referral link for the Reader in /stats
2. Get taken to /home not /read

![image](https://user-images.githubusercontent.com/545779/78578421-20d8e680-77f5-11ea-8da6-08f42b8dbf0a.png)

**Comment by sixhours** [comment]
👋 Hey @ianstewart do you have a site with a referral from the Reader readily available so I can check out the API responses?

**Comment by sixhours** [comment]
NVM found one :D

**Comment by sixhours** [comment]
Opened a patch for the Stats API in D41514-code
