### ISSUE TITLE
Hosting Configuration: Happiness Engineer support avatars in "tray" are badly formed

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#40825]
#### Steps to reproduce

1. Starting at URL: `/hosting-config/` with a Business Atomic site
2. Scroll down to "Support" section of the page

#### What I expected

To see something like this:

<img width="965" alt="Screen Shot 2020-04-06 at 11 45 53" src="https://user-images.githubusercontent.com/66797/78593869-2c7bdb80-77fc-11ea-8ae0-601f04997cc3.png">

#### What happened instead

<img width="967" alt="Screen Shot 2020-04-06 at 11 46 08" src="https://user-images.githubusercontent.com/66797/78593890-36054380-77fc-11ea-8675-779d3a4959e1.png">

#### Browser / OS version

Safari, Firefox, and Chrome on macOS

**Comment by lancewillett** [comment]
CC @sixhours Might be a `margin-right` rule causing, from a very quick CSS inspector investigation.

**Comment by sixhours** [comment]
Oddly I'm only seeing this in Safari, and it appears to be related to setting `height: auto` with `flex` on the parent container. Specifying `align-items: auto` seems to fix it, but I need to test that in the other browsers to be sure.
