### ISSUE TITLE
Gutenboarding: adjust checkout header copy

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40827]
In Gutenboarding, when purchasing a domain, we have this header highlighting the free domain: 

<img width="700" alt="Screenshot 2020-04-06 at 19 36 10" src="https://user-images.githubusercontent.com/87168/78582428-ec3d4d00-783d-11ea-9627-d90a299d8b4a.png">

Via `/start` flow when picking paid domain, it highlights the paid domain:

<img width="700" alt="Screenshot 2020-04-06 at 19 33 56" src="https://user-images.githubusercontent.com/87168/78582275-b5673700-783d-11ea-85be-83201545182a.png">

What texts we should use for "prelaunch flow" and "domain purchase flow" @olaolusoga @dubielzyk ?

**Comment by simison** [comment]
@razvanpapadopol commented on Slack:

> and we already have our gutenboarding hands deep into Checkout
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/checkout-container.jsx#L60
> So just using `isGutenboardingCreate` prop to customise whatever we want would do it.

**Comment by ockham** [comment]
I'll start a PR for this.
