### ISSUE TITLE
People: Component: Tooltips don't work on mobile

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#4082]
It was reported to me that tooltips don't work for the `/people/new/$site` route when on mobile. I remember discussing this before with @rickybanister, but I didn't create an issue and forgot. :disappointed: 

Here is where the mobile logic occurs: https://github.com/Automattic/wp-calypso/blob/master/client/components/tooltip/index.jsx#L31-L33

I'm not sure what the best approach is. Should we pass a prop in to force displaying the tooltips for our use? Or should we show inline errors just below the token field? cc @rickybanister

**Comment by rickybanister** [comment]
I thought it seemed like the tooltip had some funky logic to prevent it from being seen in mobile contexts, can't we just add a prop to remove that logic? Remind me who wrote the original tooltip stuff, maybe @mtias can advise.

**Comment by ebinnion** [comment]
Looks like @mtias added the logic in pre-OSS. I linked the logic above.
