### ISSUE TITLE
Gutenboarding: add plan icon

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40838]
In Gutenboarding, add plan icon to the header when choosing a paid domain:

<img width="1482" alt="Screenshot 2020-04-07 at 11 46 55" src="https://user-images.githubusercontent.com/87168/78649140-b643ab80-78c5-11ea-902e-3251b13f2ebe.png">

@dubielzyk is it decided that we'll use Jetpack icon? Is the copy final?

**Comment by sirreal** [comment]
What plan name do we use? Always `Personal`?

**Comment by sirreal** [comment]
Designs put the language picker in that same corner:

![Screen Shot 2020-04-07 at 11 27 57](https://user-images.githubusercontent.com/841763/78653071-e3db2580-78c2-11ea-824c-4bca2db9984a.png)

That seems to conflict. Dropping this until we have more clarity.

**Comment by dubielzyk** [comment]
Just FYI that the design is still work in progress :)

**Comment by simison** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/41287
