### ISSUE TITLE
Re-Publicize feature suggestion: Share Reminders

### ISSUE THREAD

**Issue by indolering** [Automattic/wp-calypso#40833]
#### Is your feature request related to a problem? Please describe.
Some applications like Snapchat (and [arguably Instagram](https://github.com/Automattic/jetpack/issues/1870)) restrict automated publishing.

#### Describe the solution you'd like
Wordpress has an app that could be used to implement the reminder workaround, which is a reminder (including app link and copy/paste text) to share the post.  This is how [Buffer's Instagram](https://buffer.com/instagram) posting works.

#### Describe alternatives you've considered
You could make it easier for users to spoof the headers, but it would just make everyone upset 😸.

#### Additional context
This grew out of discussion on adding [Instagram](https://github.com/Automattic/jetpack/issues/1870) functionality.

**Comment by mrsjaved** [comment]
Another request to add IG share and publicize feature. 
3951638-zd-woothemes

**Comment by indolering** [comment]
Closed due to spam.
