### ISSUE TITLE
Gutenboarding: point out launch button

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40840]
After welcome modal is closed, we should point out "launch" button:

<img width="1157" alt="" src="https://user-images.githubusercontent.com/87168/78654695-987a4480-78cd-11ea-88ab-013152b67e4d.png">

@dubielzyk is this final design and ready to be implemented?

**Comment by ramonjd** [comment]
Started a PR over at https://github.com/Automattic/wp-calypso/pull/40950

**Comment by dubielzyk** [comment]
@joanrho thoughts on if this is final? (cc @olaolusoga )

**Comment by joanrho** [comment]
@dubielzyk No, we didn't move that forward while focusing on the prototype (which is why it wasn't included in it). 

@olaolusoga do you think we should even develop this at this point? If so, I'd recommend we improve on it.

**Comment by olaolusoga** [comment]
>do you think we should even develop this at this point?
No. We shouldn't develop this. We should close issue. @simison 

We do need to work on onboarding into FSE after site creation, and the UX till launch. We'll be doing that starting Monday (cc: @simison ). We should have something more fleshed out for dev to move forward on.

Also, it's fine to not include this for soft release. The hope is we can get an e2e UX in place that at a baseline onboards folks into the editor till they launch their site before rolling out to 100% customers on June 7.

... That means moving keys issues for core FSE to a state where we can have it on dotcom before or by June 7
