### ISSUE TITLE
Gutenboarding: Increase padding on sign in form [Safari]

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40865]
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/new/style
2. Click Continue
3. See text and input field is very close

#### What I expected
Add `42px` padding between the input field and text: https://d.pr/i/ydogtV

**Comment by alshakero** [comment]
It seems already 42px, am I misunderstanding?

![image](https://user-images.githubusercontent.com/17054134/78709077-5aa00f00-7913-11ea-9d14-1d42b75808e2.png)

**Comment by ockham** [comment]
I see the same, tho technically it's a `margin` (rather than a `padding`) (and it's defined for the `Enter an email and password...` `<p>`aragraph, in case that matters). Not sure if maybe that margin accidentally collapses in some browsers/viewports?

**Comment by dubielzyk** [comment]
Okay, I've tried to repo in Chrome and it looks fine there so it looks like this is just a Safari issue.

**Comment by alshakero** [comment]
That's right. I could repro in Safari. Checking this.
