### ISSUE TITLE
Gutenboarding: integrate social signup

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#40871]
Let's add Apple/Google sign in to Gutenboarding.

Behold the (current) design!

<img width="655" alt="Screen Shot 2020-04-08 at 6 49 45 am" src="https://user-images.githubusercontent.com/6458278/78718267-53a1ec80-7965-11ea-9f77-a1fcd3ae148f.png">

This task encompasses:

- [ ] Technical analysis and implementation investigation (cursory investigation at pbxlJb-uO-p2)
- [ ] Development
- [ ] Solving world peace 🌏 

We could also get some inspiration from p1HpG7-8HC-p2

**Comment by simison** [comment]
Fresh design via p9Jlb4-1Xw-p2

![reskin-v2-signup](https://user-images.githubusercontent.com/87168/98796235-d87d4900-2413-11eb-9759-d7c781047781.png)

**Comment by yansern** [comment]
Closing this issue as this will now be tracked with the **Gutenboarding: Social Signup** project.
https://github.com/Automattic/wp-calypso/milestone/331
https://github.com/Automattic/wp-calypso/projects/106
