### ISSUE TITLE
Gutenboarding: don't allow empty confirm

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40885]
When searching for a specific domain in domain picker (free or paid), it loses all selections but still shows "confirm" button:

<img width="400" alt="Screenshot 2020-04-08 at 11 44 43" src="https://user-images.githubusercontent.com/87168/78763917-77c5f380-798e-11ea-945e-dce4767533c6.png">

<img width="400" alt="Screenshot 2020-04-08 at 11 46 09" src="https://user-images.githubusercontent.com/87168/78763967-8b715a00-798e-11ea-8b21-994214aa397d.png">

The selected domain stays selected even if it's not indicated on the list. You can see it when removing text in the search field:

<img width="400" alt="Screenshot 2020-04-08 at 11 51 33" src="https://user-images.githubusercontent.com/87168/78764497-4c8fd400-798f-11ea-94fb-7757aa78fcae.png">

Should we just make "confirm" disabled at this stage until they pick something? "X" would just keep current selection. @dubielzyk 

cc @yansern

**Comment by dubielzyk** [comment]
No, since _sitename.wordpress.com_ is the checked by default. We shouldn't force them to change from that.

**Comment by simison** [comment]
Right but what I'm actually confirming here is unclear:

![image](https://user-images.githubusercontent.com/87168/78764844-caec7600-798f-11ea-84c1-ee6a835ce1d8.png)

I'd expect now to click "confirm" to whatever is written in the search field.

**Comment by dubielzyk** [comment]
Sorry, I misunderstood. We should default to _newsitename.wordpress.com_ and let them confirm. If they want to chose a paid domain they can do that.

**Comment by simison** [comment]
> We should default to newsitename.wordpress.com 

So just to confirm — matching search result (free or paid) should get auto-selected? "Confirm"  button should stay available all the time?

Aside, "confirm" could get disabled while results are loading — but that's minor:

<img width="575" alt="Screenshot 2020-04-08 at 11 56 32" src="https://user-images.githubusercontent.com/87168/78764993-038c4f80-7990-11ea-8e26-0986a5f830dc.png">

**Comment by dubielzyk** [comment]
>So just to confirm — matching search result (free or paid) should get auto-selected? "Confirm" button should stay available all the time?

Only free should be auto-selected (user can chose a paid upgrade if they prefer) and _Confirm_ button should stay available.

>Aside, "confirm" could get disabled while results are loading — but that's minor:

Yep, great shout.

**Comment by ramonjd** [comment]
Half fix here: https://github.com/Automattic/wp-calypso/pull/41390 WIP

**Comment by p-jackson** [comment]
The "confirm" button currently works more like a "close popup" button. The selection actually changes as soon as the radio button is clicked. So I think the first thing to fix is to make the domain in the onboarding store only change when "confirm" is clicked.
Then I think the fix described above will work. That way the user is safe to do random searches without changing their selection.
