### ISSUE TITLE
Gutenboarding: Create site loader changes

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40884]
Loading animation is looking good. Let's fix a few things:

- [ ] Remove the vertical text animation. It should just swap instantly between the text like in the prototype.
- [ ] Let's add a `--studio-gray-10` background behind the loading bar. [See screenshot](https://d.pr/i/6QtnXS).
- [ ] Change the height of the loading bar from `7px` to `6px`
- [ ] Remove "Getting your domain" unless they actually got a paid domain

**Comment by sirreal** [comment]
#41317 should handle all these changes.
