### ISSUE TITLE
Gutenboarding: mobile intent capture

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40897]
In [Gutenboarding](https://wpcalypso.wordpress.com/new), intent capture should look like this on mobile:

### My site is about

<img width="388" alt="Screenshot 2020-04-08 at 13 59 23" src="https://user-images.githubusercontent.com/87168/78776969-69cd9e00-79a1-11ea-9701-9b50d31969c7.png">
(for now no language + importer, but they might appear in future)

<img width="392" alt="Screenshot 2020-04-08 at 13 59 59" src="https://user-images.githubusercontent.com/87168/78776999-76ea8d00-79a1-11ea-822e-7ac7cef74896.png">

<img width="387" alt="Screenshot 2020-04-08 at 14 02 23" src="https://user-images.githubusercontent.com/87168/78777078-94b7f200-79a1-11ea-92a1-c78f1a06465b.png">

Long texts go multiple lines:
<img width="386" alt="Screenshot 2020-04-08 at 13 58 44" src="https://user-images.githubusercontent.com/87168/78777153-b3b68400-79a1-11ea-9bef-ce8be2a21b5f.png">

### It's called...

<img width="387" alt="Screenshot 2020-04-08 at 13 58 40" src="https://user-images.githubusercontent.com/87168/78777187-bf09af80-79a1-11ea-9e0a-b6e2ed73e64a.png">

<img width="386" alt="Screenshot 2020-04-08 at 13 58 31" src="https://user-images.githubusercontent.com/87168/78777259-e496b900-79a1-11ea-80de-dd61a4ea939d.png">

<img width="384" alt="Screenshot 2020-04-08 at 13 58 26" src="https://user-images.githubusercontent.com/87168/78777273-ea8c9a00-79a1-11ea-9ab2-00562f907b5b.png">

**Comment by alshakero** [comment]
PR in https://github.com/Automattic/wp-calypso/issues/40898
