### ISSUE TITLE
Gutenboarding: mobile design picker

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40898]
In [Gutenboarding](https://wpcalypso.wordpress.com/new), the design picker should look like this on mobile:

<img width="385" alt="Screenshot 2020-04-08 at 13 58 15" src="https://user-images.githubusercontent.com/87168/78777358-11e36700-79a2-11ea-9d47-0d1a32fa4d66.png">

@dubielzyk should screen tap directly choose the design, or should there be some secondary confirm? Feels like there could be accidental taps otherwise?

**Comment by dubielzyk** [comment]
Currently have a tap should proceed. Let's do that and see how it feels. I agree that it might be awkward, but let's interact with it first and then create a more tailored solution.
