### ISSUE TITLE
Gutenboarding: mobile signup

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40907]
In [Gutenboarding](https://wpcalypso.wordpress.com/new), signup should look like this on mobile:

<img width="394" alt="Screenshot 2020-04-08 at 14 46 56" src="https://user-images.githubusercontent.com/87168/78780788-d6e43200-79a7-11ea-89b3-27ae97c6d691.png">

<img width="391" alt="Screenshot 2020-04-08 at 14 47 00" src="https://user-images.githubusercontent.com/87168/78780784-d51a6e80-79a7-11ea-963c-01db68224fce.png">

@Automattic/ganon wanna take on this? I haven't actually checked if it already looks like this. 😅

**Comment by ramonjd** [comment]
Relevant comment on the dupe issue: https://github.com/Automattic/wp-calypso/issues/40908#issuecomment-611206278

**Comment by ramonjd** [comment]
I think we mostly took care of these, but I've tweaked a few thing in #40940

<img width="362" alt="Screen Shot 2020-04-09 at 9 24 46 am" src="https://user-images.githubusercontent.com/6458278/78842699-119ba800-7a44-11ea-9983-f38366a38b44.png">
