### ISSUE TITLE
Gutenboarding: mobile style picker (add preview)

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40900]
In [Gutenboarding](https://wpcalypso.wordpress.com/new), the style picker should look like this on mobile (with preview included):

![style-picker-with-preview](https://user-images.githubusercontent.com/14192054/80340249-f82e9480-8868-11ea-93b0-d26bda278e68.png)

**Comment by dubielzyk** [comment]
I'll put the static image preview on the docket. I assumed it would be hard on this launch, but I'll start prepping for it now.

**Comment by simison** [comment]
It's some amount of work but worth it if it makes it a much better experience.

We can also have a full site screenshot available, vs cropped up as we have in the grid.

**Comment by simison** [comment]
To clarify; since we now generate screenshots for the grid, we might as well just generate the same screenshot with each font-pairing.

**Comment by andrewserong** [comment]
I've made a start in a WIP PR: https://github.com/Automattic/wp-calypso/pull/40947 and added a few questions about how to break the design down across intermediate viewport sizes. Feel free to pick up / take this over, anyone!

**Comment by dubielzyk** [comment]
[Here's a mock](https://d.pr/i/Dd2vpD) with a potential preview on mobile. I've also added it to the design file.

**Comment by simison** [comment]
A few questions and my thoughts on them:

- should the preview on mobile be scrollable/zoomable
  - maybe, but for now, I'd simplify this and not allow it (should be as simple as `pointer-events: none; touch-action: none;`
- Should "continue" stay fixed visible at all times, or show up under the fold?
  - I'd prefer this to be visible so that it's clear what to press without scrolling and finding out about the button
- Should we always show desktop preview? or mobile?
- Iframe or static image?
  - To make this faster on mobile, we can totally mshot-render (or for now staticly generate) previews for all fonts and different screen sizes. That said, maybe iframe version works fine enough? Needs to be tested.

Thoughts?

**Comment by dubielzyk** [comment]
>should the preview on mobile be scrollable/zoomable

We'd have to make the preview bigger. I assume it'll look clunky. If we can't see the impact of the font change, we might wanna make the preview bigger either way.

>Should "continue" stay fixed visible at all times, or show up under the fold?

I threw the mock together quickly, but maybe we need to look at it further to have a fixed bottom bar. I agree that it's not ideal to have the _Continue_ button below the fold.

>Should we always show desktop preview? or mobile?

I feel like mobile would show very little of the page, but perhaps be more useful. I don't have strong opinions. Let me get some other opinions next week.

>Iframe or static image?

I'm not sure I know the practical difference. If you can't notice, then go for what suits you best.

**Comment by andrewserong** [comment]
This issue was closed by #40947 (implementing the mobile styling changes), but I'm re-opening it to track the discussion / next steps for the mobile preview.

**Comment by andrewserong** [comment]
I'll remove my own assignment here so that anyone can pick this up (it might end up being me anyway!)

**Comment by andrewserong** [comment]
@dubielzyk — I've picked this one up again to work on the mobile preview, and have started a WIP PR to play around with it: https://github.com/Automattic/wp-calypso/pull/41732

So far I'm liking using an iframe and seeing how far we can get with it, and it'll be interesting to see how it feels if the user can scroll the preview or not. In terms of how we display the site preview, I think it'll be a bit easier to show the mobile layout, but I'm happy to explore the desktop one if it's preferable. I haven't tested on a real device yet, but will do that tomorrow, along with looking into the fixed footer for the buttons.

**Comment by dubielzyk** [comment]
Sounds good. Let me know when you got further updates and I'll have a further look :)
