### ISSUE TITLE
Gutenboarding: Implement domain overlay on mobile

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40949]
Made a mock of the domain overlay on mobile. You can also find it in the design file.
![image](https://user-images.githubusercontent.com/2896062/78874716-1749bb80-7a4d-11ea-81b3-9e3ea6141130.png)

Things to note:
- It's full screen
- Removing the recommended badge as it's likely to cause a lot of layout issues
- For longer domain names let's grow things vertically while keeping the text aligned to the top of the radio buttons. [See mock](https://d.pr/i/0UNxXD):
    <img width="363" alt="image" src="https://user-images.githubusercontent.com/87168/78917268-50a71900-7a97-11ea-9c01-924e711c3671.png">

**Comment by yansern** [comment]
Vertical alignment is now handled in this PR. https://github.com/Automattic/wp-calypso/pull/40959

**Comment by yansern** [comment]
@dubielzyk I don't know if I read it somewhere on GH/Slack or I read it when I was whaling in my dream that the footer and/or header of this domain picker is sticky, meaning only the domain list is scrollable when user glides through the screen on mobile. Is that so? Let me know!

**Comment by yansern** [comment]
PR ready for review. https://github.com/Automattic/wp-calypso/pull/41078

**Comment by dubielzyk** [comment]
I'll comment on the PR :)

**Comment by klimeryk** [comment]
> Removing the recommended badge as it's likely to cause a lot of layout issues

I'd recommend strongly for keeping the badge - it has shown clearly in tests a very positive impact on conversion rates. It's basically a very crucial part of the whole design and according to tests, users found it _very_ helpful in making the decision what domain to choose. See p8kIbR-21-p2 for more context and detailed results :bow:

**Comment by dubielzyk** [comment]
Thanks for the insight @klimeryk. Let's keep the recommended badge then :)
