### ISSUE TITLE
Gutenboarding: Clicking outside the domain overlay should close it

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40948]
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/new/design
2. Click _sitename.com is available_ 
3. See the overlay open. Click outside the overlay

#### What I expected
When clicking outside the overlay, I expect the overlay to close, just like clicking the X button would.

#### What happened instead
It didn't close when clicking outside the overlay.

**Comment by razvanpapadopol** [comment]
Duplicate of #40890
