### ISSUE TITLE
Group Block: Doesn't Show/Wrong Drop Positioning

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#40953]
#### Steps to reproduce

1. Create a new page
2. Add a Group block
3. Add some Paragraph blocks **inside** the Group block
4. Add more Paragraph blocks **outside** the Group block
5. Move the blocks around, using the drag and drop

#### What I expected
To be able to move the blocks inside the Group block (and into it), and see where they will be dropped (with a blue line). As it does outside a Group block:

![BlocksOutsideGroup](https://user-images.githubusercontent.com/16104522/78886276-4bfd4900-7a34-11ea-9941-4c3b2a5c2d89.gif)

#### What happened instead
When I try to move the blocks around inside the Group block, the blue line for dropping location doesn't show:

![BlocksInsideGroup](https://user-images.githubusercontent.com/16104522/78886337-6505fa00-7a34-11ea-864c-ff0013ee9886.gif)

This is particularly difficult when trying to move blocks outside the Group block into it. It doesn't seem anything will happen and when you drop it it shows in a different position (dropped after line 2, and it landed after the 4):

![BlockFromOutside](https://user-images.githubusercontent.com/16104522/78886546-c7f79100-7a34-11ea-95b3-83e71da40eb7.gif)

#### Browser / OS version
OS X 10.15.3
Chrome 81.0.4044.92

#### Context / Source
#dogfooding

**Comment by cathymcbride** [comment]
@carinapilar Does this still repro for you?

**Comment by carinapilar** [comment]
@cathymcbride, I'm not able to replicate that anymore, it seems it was fixed. 🎉
