### ISSUE TITLE
Image Block: Odd Selection with Alignment applied

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#40951]
#### Steps to reproduce

1. Create a new page
2. Add 2 Image blocks, one after another
3. Set a Left alignment on the first Image block

#### What I expected
To be able to select the images like this (which is what happens with no alignment):

![Screen Shot 2020-04-09 at 07 08 47](https://user-images.githubusercontent.com/16104522/78884564-80233a80-7a31-11ea-9931-d50ac35d8c0a.png)

#### What happened instead
If I select the first image a blue line shows on the top (and no blue border):

![Screen Shot 2020-04-09 at 07 09 14](https://user-images.githubusercontent.com/16104522/78884602-9204dd80-7a31-11ea-9fc3-eb8821dde0b3.png)

And when I select the second image, the blue border shows around both images:

![Screen Shot 2020-04-09 at 07 09 24](https://user-images.githubusercontent.com/16104522/78884690-be205e80-7a31-11ea-8199-2dcc234177be.png)

It's very confusing, since it seems that the images are grouped.

#### Browser / OS version
OS X 10.15.3
Chrome 81.0.4044.92

#### Context / Source
#user-report

**Comment by obenland** [comment]
@carinapilar Is this something you can still reproduce?

In my testing I was able to select the image just fine, with the focus lines showing up as expected:

![image](https://user-images.githubusercontent.com/1398304/106073813-9c2ac200-60bf-11eb-86c1-02cd5703324e.png)

**Comment by carinapilar** [comment]
Thanks for looking into this, @obenland! I would guess it depends on the theme and the size of the images, because of the available width area.

I'm still able to replicate this, using theme Stow, if I add 2 images that are wide enough, when I select the second one this is what happens:

![SelectingImages](https://user-images.githubusercontent.com/16104522/106123444-b0f76c00-6138-11eb-9f82-795a855ed4e3.png)

The second image doesn't have any alignment selected, and the first is Left aligned.

**Comment by obenland** [comment]
Ah, yes, I can reproduce that now. It seems to be a Gutenberg core bug, I can also reproduce it on a self-hosted install.

**Comment by obenland** [comment]
Reported upstream: https://github.com/WordPress/gutenberg/issues/28570
