### ISSUE TITLE
Gutenboarding: invalid domain suggestions

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#40964]
For some search queries (like `yog.a`) we get non-valid suggestions like the paid ones here:

<img width="774" alt="bad-domain-suggestions" src="https://user-images.githubusercontent.com/14192054/78898436-78d54e80-7a7c-11ea-871f-014aa44f9824.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/87168/78904242-e84f3c00-7a84-11ea-89d0-04b71a6c1352.png">

Might be related to #40164

**Comment by klimeryk** [comment]
To close the loop here, this turned to be a bug at our third-party provider and should be fixed by them. cc @daledupreez for coordination 🙇 See p99Zz8-17N-p2 for more information.
