### ISSUE TITLE
 Gutenboarding: domains - add notice for specific TLDs requiring HSTS

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40973]
Domains returning `hsts_required:true` from the API need a special HSTS notification.

#### Designs for Gutenboarding

<img width="353" alt="Screenshot 2020-05-14 at 13 20 43" src="https://user-images.githubusercontent.com/87168/81923192-edecf400-95e5-11ea-956d-2a6ae1b8e322.png">

Plus similar popover like in Calypso. 

#### Implementation in Calypso:

![image](https://user-images.githubusercontent.com/87168/78903597-0a948a00-7a84-11ea-9c4a-71309d71170e.png)

<img width="550" alt="Screenshot 2020-04-24 at 16 07 01" src="https://user-images.githubusercontent.com/87168/80215786-b671d400-8645-11ea-9458-000f4d3c4c91.png">

- In Calypso, this was implemented here: https://github.com/Automattic/wp-calypso/pull/32341
- List of TLDs that need this from p1aYnM-1eC-p2
- More context via pbAok1-6r-p2#comment-1005

**Comment by simison** [comment]
@dubielzyk can we add similar i -icon that's visible here in screenshots to the domains list?

It could open either core [popover](https://github.com/WordPress/gutenberg/blob/acafff97f73dc8178f27c5feb38474afd18e889f/packages/components/src/popover/README.md) or [tooltip](https://github.com/WordPress/gutenberg/blob/4758992cf1ea69b2713d3077645a38ed7d4ed6f1/packages/components/src/tooltip/README.md) with the exact same text.

**Comment by dubielzyk** [comment]
Yep. Let's stick with the same pattern. I'll update a designs.

**Comment by simison** [comment]
@daledupreez hi!

What do you think if `requires_hsts: true|false` info would be coming directly from the domains suggestions API? I think that would simplify a lot of things.

Currently checking for hsts requires passing a slug such as `product_slug: "dotequipment_domain"` to this helper, which then compares it to _product list_.

https://github.com/Automattic/wp-calypso/blob/0699b68413f1d1692392fd5a354ec35e5ea2c21f/client/lib/domains/index.js#L161-L165

That works fine in Calypso, but if we'd like this feature to be easy to port to wp-admin context (and we do!), it would be great if we don't need to deal with massive Calypso state.

With API approach, the check in UI would become super simple:
```jsx
{ suggestion.hsts_required && <HstsInfo tld={ domainTld } /> }
```

Thoughts?

**Comment by daledupreez** [comment]
@simison, I think we can refactor the logic here somewhat, but I don't think we can escape the dependency on the products -- we need the product data to show accurate pricing details. We can shift that out of the state if need be, but I think you're still going to need the relevant data in the component.

**Comment by daledupreez** [comment]
@simison, I looked into this some more, and I realized that we're sending the cost back in the response data -- we should be able to do the same for the HSTS required flag. I'll work on a diff for that tomorrow, using the name `hsts_required` as a boolean.

**Comment by simison** [comment]
😍😍😍😍🌻🌻🎉

**Comment by daledupreez** [comment]
OK, the back end change to add the flag in D43163-code has been reviewed and approved but not deployed. Feel free to ping me if you want/need that deployed before Monday, which is when I am planning on deploying for now.

**Comment by simison** [comment]
👍 Monday works great for me, thanks! I'll add the UI on Monday as well.

**Comment by daledupreez** [comment]
I've just deployed D43163-code - it returns `hsts_required: true` in the payload when HSTS is required, and does not include the flag otherwise.

**Comment by razvanpapadopol** [comment]
I've created a separate issue https://github.com/Automattic/wp-calypso/issues/45449 for the UI tooltip component that is also needed in other parts of Gutenboarding (eg: plans grid).
