### ISSUE TITLE
(5P) FSE: check Carousel block compatibility

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#40981]
FSE compatibility! Let's make sure the block works on self-hosted installs like Atomic.

we essentially had 3 main issues for this block in this iteration:
- [x] sync code
- [x] make it work on any WP, inside FSE
- [ ] make it work on dotcom specifically

See https://github.com/Automattic/Dotcom-roadmap/issues/122

**Comment by retrofox** [comment]
Test:

- [ ] Check if the plugin is disabled when CoBlocks is activated locally
- [ ] Check if the plugin is disabled when CoBlocks is activated in an Atomic site

**Comment by retrofox** [comment]
### Check if the plugin is disabled when CoBlocks is activated locally

Tested locally.

1) Activate CoBlocks

![image](https://user-images.githubusercontent.com/77539/80389972-32f0f680-8882-11ea-9bb2-92938cbe95fa.png)

2) Confirm that the plugin is [disabled by FSE](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php#L224).

**Comment by marekhrabe** [comment]
What roles does CoBlocks hold here? Why do we need to check anything about it regarding this?

**Comment by retrofox** [comment]
> What roles does CoBlocks hold here? Why do we need to check anything about it regarding this?

Wrong name. Updated. 🤦

**Comment by marekhrabe** [comment]
haha, no problem 😀 we'll surely run alongside coblocks too but there should be no issues

**Comment by retrofox** [comment]
Tested the plugin locally, in dotcom, and Atomic sites. It works as expected so far.
Please refer to the [feature-branch](https://github.com/Automattic/wp-calypso/pull/41423) in order to get updated about the process and changes.

**Comment by retrofox** [comment]
Tested and it works as expected. Let's continue testing in the [feature PR](https://github.com/Automattic/wp-calypso/pull/41423). Closing this one.
