### ISSUE TITLE
(5P) FSE: Carousel dotcom compatibility

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#40982]
The block should work as expected on wp.com

See https://github.com/Automattic/Dotcom-roadmap/issues/122

Testing .zip file: https://github.com/Automattic/wp-calypso/suites/632881609/artifacts/5168216

**Comment by marekhrabe** [comment]
To provide more context, this task will be tackled after we have the block fully working in other FSE environments (standard local WP for example) — tracked in #40981. Once we have it in FSE, let's try running the plugin in dotcom context and if there are certain things that need adjustment, let's make them. 

What usually comes up with FSE dotcom compatibility is that AJAX requests from the editor are handled a bit differently on a standard WP and on dotcom so they need a little shim in PHP.

**Comment by obenland** [comment]
D42556-code

**Comment by retrofox** [comment]
We've been testing the compatibility and it works as expected. Let's continue testing in the [feature PR](https://github.com/Automattic/wp-calypso/pull/41423). Closing here.
