### ISSUE TITLE
(3P) Media: Library storage space indicator upgrade should explain storage options

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40986]
![image](https://user-images.githubusercontent.com/437258/78919408-ddce7b80-7a5f-11ea-8ecd-882ca965dc26.png)

I think this would benefit from having a tooltip on hover to perhaps explain how much extra storage you can get.

**Comment by davemart-in** [comment]
Once this has a design I'll be happy to triage it.

**Comment by sixhours** [comment]
#44037 updates the hit state but does not add a tooltip or any other design work for this one.

**Comment by rickybanister** [comment]
That's a great start, thanks @sixhours!

**Comment by obenland** [comment]
I updated the topic title and description to reflect the changes @sixhours has made in #44037. It looks like the remaining part here is to add a tooltip with storage options?

@sfougnier Do you think you'd have time for a mockup of what that should look like and what kind of data it should contain?

For the placement of the tooltip it's probably worth keeping in mind that the entire indicator is now an anchor. Easiest for the tooltip to appear would probably be outside of that box somewhere?

**Comment by sfougnier** [comment]
On hover, a tooltip adds more context to the upgrade CTA.

<img width="1440" alt="Media Library - Storage Space Hover" src="https://user-images.githubusercontent.com/67021691/90786362-7c51cf80-e2d1-11ea-8068-b108a07a3060.png">

**Comment by obenland** [comment]
See paYJgx-WR-p2 for a11y considerations.

Let's review how the upgrade link displays in different plan tiers and how the Tooltip text would need to adjust for that, too.

**Comment by rickybanister** [comment]
@sfougnier I think that simple tooltip works well and is a good mvp. 

I'm also curious if there could be value in doing something like this down the line by creating a 'plans widget' that could be triggered from various links or upsell banners:

![image](https://user-images.githubusercontent.com/437258/91082132-34ef7a00-e616-11ea-8831-03c9e9970573.png)

That might be something to explore for a future sprint.

**Comment by rickybanister** [comment]
If we did something like a plan widget, it would make sense to highlight the important feature (in this case more storage) as the first item and give it special treatment. Showing the rest of the reasons to upgrade sweeten the deal.
