### ISSUE TITLE
Atomic: Pages list should respect the Jetpack "Copy Post" setting

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#40995]
#### Steps to reproduce

1. Starting at URL: `/pages`
2. Look for the "Copy Page" link in the ... menu for the page

<img width="284" alt="Screen Shot 2020-04-09 at 13 24 42" src="https://user-images.githubusercontent.com/66797/78937485-79aeb600-7a65-11ea-8186-058bc5645baa.png">

#### What I expected

With an Atomic site, if the related Jetpack setting is off, Calypso should not show the "Copy Page" link here.

Related: https://github.com/Automattic/atomic/issues/788

#### What happened instead

Even with the Jetpack "Copy Post" setting turned off, the Calypso "Copy Page" link appears.

<img width="1092" alt="Screen Shot 2020-04-09 at 13 25 43" src="https://user-images.githubusercontent.com/66797/78937597-9f3bbf80-7a65-11ea-8d69-d54a9e308a59.png">

Note: the "Copy Post" in Calypso doesn't show, as expected.

**Comment by Aurorum** [comment]
PR for this issue in #41337. :)

**Comment by lancewillett** [comment]
Thanks for your fix! Works as expected. Deployed to production.
