### ISSUE TITLE
Site Settings: Add redirects for non-existent site section

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#41]
A couple of routing issues:

> One minor issue I did run into: if I goto `/settings/$site` I see the site selector. Clicking on a site updates the URL but I stay on the selector. Alternatively, if I go to `/settings/blah`, I also see the site selector but clicking on a site works correctly. Maybe we should redirect these URLs as well?

**Comment by lancewillett** [comment]
I don't think is worth fixing because you'd only get there by manually taking your site URL (without the prefix) and constructing the URL bits yourself. Not a likely scenario for WordPress.com users. :)

When navigating the UI with mouse and keyboard, as normal, this routing event doesn't occur.
