### ISSUE TITLE
People: On Android, users should be separated by spaces and commas automatically

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#4102]
#### Steps to reproduce
1. Go to the invite page on an Android device on Chrome
2. Type in a username followed by a space, notice that the username did not get turned into a token. It's possible to type in a username with a space. (See image below)
3. Type in a username followed by a comma, notice that it also doesn't get turned into a token:
![usernames-with-spaces-and-commas](https://cloud.githubusercontent.com/assets/11487924/13832439/971c437e-ebb2-11e5-9771-1f37abadf1cb.png)
4. Notice that it's only possible to create a token by using the 'Next' button on Android:

#### What I expected
- when I type in a space, the username should be added to the list
- when I type in a comma, the username should be added to the list

Note: this happens on Chrome on Android. Spaces and commas work as separators on Safari on iOS.

**Comment by ebinnion** [comment]
Thanks for reporting this. I'm going to close this in favor of #4202.
