### ISSUE TITLE
Jetpack Connect: "0 records" and lowest search tier price always shown on pre-connection products page

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#41025]
#### Steps to reproduce

1. Go to https://wordpress.com/jetpack/connect/store (one way to get there is to start at https://wordpress.com/jetpack/ and click on "Get started" in the "Bring Jetpack to your favorite host" section).
2. Notice this:
![jetpack-connect-store](https://user-images.githubusercontent.com/235183/79007050-5dc01880-7b28-11ea-8d92-60e98e9533e2.png)
3. Besides the confusing "0 records", you'll also find that the price may be incorrect (after clicking through and connecting your site, the price in your shopping cart will reflect the number of search records your actual site has, which may put you in a higher tier than the $50/year one).

#### What I expected

If we're displaying the list of products and don't have a site connected yet, we probably need to display a different version of the Jetpack Search card in that scenario, that somehow informs the user that the price they pay will depend on the number of records on their site.

**Comment by AnnaMag** [comment]
great point.This view is a redirect when accessing /jetpack/connect without a valid/known Jetpack site.  Without knowing the site, there is no price estimation possible.

Current view: 

![ex](https://user-images.githubusercontent.com/13561163/79235415-dba75b00-7e6b-11ea-8965-749b84ef74eb.png)

/cc @keoshi for UX wizardry :)

**Comment by gibrown** [comment]
I'm not sure how we get to this flow where we select a plan and then get prompted to enter in the site, but it feels like if the site they entered is wrong then we should correct that problem first and then go to the plans page.

I think this is also kinda related to #41027 since if we have a good site selector (and support wp.com) then we will not this redirect loop.

cc @folletto

**Comment by gibrown** [comment]
@keoshi ya it does feel like we need better copy for those cases. On the landing page we have "Get Jetpack Search starting at $5 per month" but I've definitely heard feedback that there is a sudden switch when they go to connect and it is suddenly $250 for a year.

**Comment by AnnaMag** [comment]
Aside from the copy change, we can add redirects to the login screen for e.g. the case David mentions :
`https://wordpress.com/jetpack/connect/store?ref=jetpack-lp`

**Comment by keoshi** [comment]
> On the landing page we have "Get Jetpack Search starting at $5 per month"

Fixed!

> we can add redirects to the login screen

Yes, please!

**Comment by gibrown** [comment]
This bug cuts across all of our products and our purchase flows. See discussion in #41144
