### ISSUE TITLE
Jetpack Search: clarify the post checkout modal

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#41029]
<img width="870" alt="Screen Shot 2020-04-10 at 12 34 03 PM" src="https://user-images.githubusercontent.com/820871/79014191-9f03f880-7b27-11ea-9cbc-4021aebf90c2.png">

"Go back to my site" makes it sound like you are going to get to use search rather than be dumped into WP-Admin. We should make it clear that the primary option is the one they want in order to be able to try search out.

Suggested changes:
- Give an estimate of how long indexing will take
- Instead of "Customize search now" say "Jetpack Search Customizer" (so the user knows how to get back there later by going to the customizer)
- Instead of "Go back to my site" say "Try Search Later" (or something else to indicate it is on)

cc @keoshi

**Comment by keoshi** [comment]
> Instead of "Customize search now" say "Jetpack Search Customizer"

Not a big fan of changing what's a prompt right now to a name. To the average user, "Jetpack Search Customizer" could be the name of the product and is not descriptive enough IMO. "Customize Search now" is phrased in a way that demands an action _and_ indicates where they'll land. 

> so the user knows how to get back there later by going to the customizer

We already have a link to the Customizer on the Search settings card, so I don't think it's a big deal.

> Instead of "Go back to my site" say "Try Search Later" (or something else to indicate it is on)

"Try Search Later" might indicate that “Customize Search now” does indeed allow you to test search which is not necessarily true in the case where syncing/indexing is not complete yet, right? We also indicated above that “we have configured Jetpack Search on your site”, but I don't mind the change.

**Comment by AnnaMag** [comment]
What is the resolution? 
Would including a mention/link that points to the indexing status in the performance tab (atm available in wp-admin https://github.com/Automattic/jetpack/pull/15488) help clarify the next steps?

**Comment by keoshi** [comment]
As per our call today, let's drop the second non-primary button, and change the copy on the first one.

Here's my suggestion for the primary button's copy:

> Try Jetpack Search and customize it now

or

> Try Search and customize it now

cc'ing @Automattic/editorial to get their thoughts too

**Comment by benhuberman** [comment]
Hey @keoshi -- from the two options above, I'd go with the latter, which is more concise (and there's no real need to repeat "Jetpack Search" there too). I wondered, though, if anything major would be lost if we went with just:
> Customize Search now

It might be my very superficial knowledge of the feature, but it wasn't clear to me what "trying" JP Search would mean at this point in the user's experience. 

Along the same lines, in the copy above the buttons, I'd also consider tweaking:
> — you should try customizing it in the traditional...

To:
> — now you can customize it in the traditional...

I think the above ^^ might also better set up the user for the action we want them to take with the button copy.

**Comment by gibrown** [comment]
Let's go with "Try Search and customize it now". We have definitely had folks ask "where do I try it" immediately after purchase, so I think we should be explicit.
