### ISSUE TITLE
Jetpack Search: JP Connect needs to handle wp.com and have a site selector

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#41027]
This mostly all refers to the wordpress.com/jetpack/connect screens.

A lot of the current Jetpack Search Product purchase flow goes through Calypso and JP Connect. There are some rocky pieces to this flow:
- Requires that the user manually enter a site URL even if they are logged in. We should present them with a site picker when they are logged in.
- If the user selects/enters a wp.com site, we should not say that "WP.com has all features of Jetpack because it does not depending on what plan they have". They are clearly here to purchase something, we should lead them in the correct directly to purchase it or tell them it is not yet available
- Calypso seems to flash some other results on the screen before showing the site selection dialog. Feels kinda janky.

**Comment by AnnaMag** [comment]
> If the user selects/enters a wp.com site, we should not say that "WP.com has all features of Jetpack because it does not depending on what plan they have". They are clearly here to purchase something, we should lead them in the correct directly to purchase it or tell them it is not yet available

Added in https://github.com/Automattic/wp-calypso/pull/41257

> Requires that the user manually enter a site URL even if they are logged in. We should present them with a site picker when they are logged in.

Url input form is there to connect a JP site, assuming it might not be. Site selection will work only if a user wants the product on their already connected site (else we cannot list the sites), which is probably not the case for folks coming from external links. Users with connected sites will buy it via wp-admin or Calypso.
