### ISSUE TITLE
My Home: Reuse dot pager from WordPress

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#41035]
If possible let's try reusing the dot pager from WordPress/components. Unfortunately this is currently tied to the Guide component, so let's file an upstream PR to break this out.

https://wordpress.github.io/gutenberg/?path=/story/components-guide--default

<img width="690" alt="Screen Shot 2020-04-10 at 4 30 25 PM" src="https://user-images.githubusercontent.com/1270189/79029293-9ff95200-7b48-11ea-8663-2bef80c9f7ad.png">

The intended use case is for paging a small number of cards on My Home

![image](https://user-images.githubusercontent.com/1270189/79029332-c4edc500-7b48-11ea-86da-31fe024f042c.png)

**Comment by gwwar** [comment]
We can re-evaluate if this makes sense after we have a prototype up in Calypso.

**Comment by mmtr** [comment]
If we end up adding the changes from https://github.com/Automattic/wp-calypso/pull/41202 to our `DotPager` component, I think it will become much different than the one used in the Gutenberg `Guide` component so maybe it doesn't make sense to re-use it.

**Comment by mmtr** [comment]
Closing this for now since the current component in Calypso needs more features that are not available in Gutenberg (such as rendering all children to avoid jumping controls or transition effects).
