### ISSUE TITLE
My Home: Make Recoleta available

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#41036]
To help bridge Gutenboarding and My Home, let's make the Recoleta font available on My Home.

- Remember to think though performance considerations and avoid font pop-in
- Do we have good font fallbacks for languages that the font does not support.

<img width="1024" alt="growth-task" src="https://user-images.githubusercontent.com/1270189/79029524-958b8800-7b49-11ea-8004-37913d339e1d.png">

**Comment by mmtr** [comment]
I see the "My Home" header uses the Recoleta font too. That header comes from the [`FormattedHeader` component](https://github.com/Automattic/wp-calypso/tree/master/client/components/formatted-header) that is used across all pages. Should we use the Recoleta font in all headers? Or just in My Home? cc @danhauk

**Comment by mmtr** [comment]
> avoid font pop-in

@gwwar what do you mean exactly by this? We can control this behavior with `font-display`.

Using a `block` value ensures the text using the font face does not render until the font is loaded, by other texts will render earlier:

![Apr-13-2020 13-56-01](https://user-images.githubusercontent.com/1233880/79118647-c01a5280-7d8e-11ea-9ad3-93d8c004a844.gif)

On the other hand we have the `swap` value which ensures both texts renders at the same time, but it will swap the font face once loaded:

![Apr-13-2020 13-56-41](https://user-images.githubusercontent.com/1233880/79118662-c7d9f700-7d8e-11ea-9296-6c50ce863252.gif)

**Comment by mmtr** [comment]
The other alternative is to load the font face using the [`FontFance` JS interface](https://developer.mozilla.org/en-US/docs/Web/API/FontFace) and completely block the rendering until the font is loaded.

**Comment by gwwar** [comment]
> @gwwar what do you mean exactly by this?

Some font assets can be pretty large, I'd maybe chat with perfops on advice. I'm not a huge fan of blocking text from rendering either, eg try loading the page with a slow 3G connection.
