### ISSUE TITLE
Sharing: Publicize with Twitter doesn't seem to sending Tweets through.

### ISSUE THREAD

**Issue by fernmed** [Automattic/wp-calypso#41039]
User is having an issue having their Tweets shared to their account. Even after going through and reconnecting account, posts aren't shared to Twitter either automatically or manually shared. 

#### Steps to reproduce

1. Reconnected Twitter account @loicocom for user zdklr on site http://loico.com
2. Tried manually sharing a post to Twitter 
3. Post never goes through. 
4. Publicize doesn't show any errors and shows Twitter connection is actually connected successfully.

#manual-testing, #user-report

**Comment by lancewillett** [comment]
@fernmed Could you move this one to Happiness Feedback P2 instead?

More likely a temporary glitch or one-off than a bug in Calypso or Sharing for all users.

**Comment by zdenys** [comment]
Just noting that I posted about this here including a solution p2EDhh-15d-p2
