### ISSUE TITLE
My Home: Add Pager to Education Cards

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#41037]
Let's make it possible to page from Mastering the Block Editor to Free Photo Library 

![image](https://user-images.githubusercontent.com/1270189/79029776-b99b9900-7b4a-11ea-82cb-78d78631c075.png)

@lcollette prefers the first mock with just chevrons for back and next (without label text) for this compact view.

* We can add a temporary Calypso dot pager. Reusing Gutenberg components would be a follow up in https://github.com/Automattic/wp-calypso/issues/41035
* Let's try to make this available ahead of new layout prototyping in https://github.com/Automattic/wp-calypso/issues/40734
* We may need to modify styling or make a compact version of Mastering the Block Editor card.

**Comment by mmtr** [comment]
I covered this in b806c10, which is part of the PR exploring the new layout (https://github.com/Automattic/wp-calypso/pull/41000).

![Apr-15-2020 16-14-07](https://user-images.githubusercontent.com/1233880/79348354-33f65f80-7f35-11ea-93e2-025c3de2208b.gif)

**Comment by gwwar** [comment]
Chatting with @lcollette to clarify requirements:

- The dot pager is meant for the current layout in the secondary column. So we can release the new card ahead of needing to be done with the new layout iteration.
- The dot pager can also be used to iterate through single task cards (the top primary cards like in https://github.com/Automattic/wp-calypso/pull/41018 (while we have a small number of these).
- If we're iterating on the new layout, we can display the cards here without controls. Likely max 2 stacked

**Comment by mmtr** [comment]
Opened #41184 for displaying both cards in the current layout.
