### ISSUE TITLE
Mobile: Android 4.1 layout issue

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#4104]
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. log in
3. See site

#### What I expected
Mobile version of Calypso shown correctly

#### What happened instead
Garbled mess

#### Browser / OS version
Android OS browser (not chrome) / Android 4.1

#### Screenshot / Video

<img width="397" alt="screen shot 2016-03-16 at 5 48 18 pm" src="https://cloud.githubusercontent.com/assets/1158819/13833114/c9c82ee0-eb9f-11e5-8db5-fb19feaaaf1b.png">

**Comment by lancewillett** [comment]
Should we support this version of Android (isn't it pretty old)? For other browsers and versions we usually say the current major release and one back.

**Comment by lancewillett** [comment]
Closing as no further activity and that browser version looks pretty old.
