### ISSUE TITLE
Devdocs: Button component is missing styles

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#41051]
On https://wpcalypso.wordpress.com/devdocs/design/button, Buttons are missing styles. This is how they appear at the moment:

<img width="1680" alt="Screenshot 2020-04-14 at 00 09 25" src="https://user-images.githubusercontent.com/18581859/79149148-55940180-7de4-11ea-9fb2-8aad5b722e04.png">

**Comment by iamtakashi** [comment]
I've noticed this today. It's still broken. Previous conversation: `p1580412109133600-slack-calypso`

**Comment by arunsathiya** [comment]
Is okay now. Closing.
