### ISSUE TITLE
People: keyboard should not default to uppercase when adding new users on mobile devices

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#4106]
#### Steps to reproduce
1. Go to add a new user either on Android or iOS at people/new/$site
2. Type in your first username
3. See that the first letter is automatically capitalized:

Android:
<img alt="capitalized-first-letter-android" src="https://cloud.githubusercontent.com/assets/11487924/13833327/4eb24d82-ebbb-11e5-95d8-e884f53f619f.png" width="400" />

iOS:
<img alt="capitalized-first-letter-ios" src="https://cloud.githubusercontent.com/assets/11487924/13833328/4fe1dd12-ebbb-11e5-8d4b-1a190ba583f7.png" width="400" />

4. After typing the first username, start to type the second username and see that it will also be capitalized automatically on Android (but not iOS):

Android:
<img alt="capitalize-second-word-android" src="https://cloud.githubusercontent.com/assets/11487924/13833345/720e56f4-ebbb-11e5-8e8c-029906ccc48a.png" width="400" />

iOS:
<img alt="not-capitalize-second-word-ios" src="https://cloud.githubusercontent.com/assets/11487924/13833346/720f8196-ebbb-11e5-95ad-b5764269da7f.png" width="400" />

#### What I expected
I expected to type and see lowercase letters. Both emails and usernames are not generally capitalized.

**Comment by designsimply** [comment]
Tested and confirmed that the "Usernames or Emails" field on the `/people/new/$site` page defaults to caps for the first letter on iOS.
