### ISSUE TITLE
Create site loading screen does not handle errors

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#41067]
If an error occurs while creating the site, the loading animation will stay stuck on the Applying design step.
The user should be notified of the error and ideally have a way to try again.
<img width="547" alt="Screen Shot 2020-04-14 at 8 03 46 AM" src="https://user-images.githubusercontent.com/22446385/79179300-adfdea00-7e4a-11ea-946c-a38b389cada8.png">

#### Steps to reproduce
One way to simulate an error creating the site is to disable the network connection whil on the loading page:

In Chrome browser:
Fill in necessary gutenboarding details to get up to the https://wordpress.com/new/style page.
Open the dev tools *network* tab, see where it says *Online ˅* 
Click on Continue, land on the loading page
Quickly change *Online ˅* to *Offline* before the editor loads!

#### What I expected
Should see an error message, and an option to try again

#### What happened instead
Stuck on the loading screen :(

**Comment by lsl** [comment]
Extracting from slack: #41782 seems to have rectified the "stuck on loading screen" problem, errors push you back to the previous plan selection step.

Next:
- Nail down error repro for testing
- Add a flash message to explain whats happened and what to do next
