### ISSUE TITLE
Gutenboarding: WordPress logo in header is not clickable

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#41065]
#### Steps to reproduce
On https://wordpress.com/new
I would expect the wordpress logo in the top left corner to be clickable and act like a home button.
It should probably take us to https://wordpress.com/

<img width="896" alt="Screen Shot 2020-04-14 at 7 42 11 AM" src="https://user-images.githubusercontent.com/22446385/79178450-adfcea80-7e48-11ea-9f44-692c34297477.png">

Currently it's not clickable and there's no way to go home from gutenboarding.

**Comment by simison** [comment]
@dubielzyk any thoughts on this?

**Comment by dubielzyk** [comment]
Yeah, this makes sense. Me and @olaolusoga talked about this. Feel free to enable this :)

**Comment by simison** [comment]
Having logo clickable would also be a good way to let already signed-in users to get back to Calypso. https://github.com/Automattic/wp-calypso/issues/37815
