### ISSUE TITLE
Display only most important date when listing posts or pages

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#41075]
We currently display 2 dates on wordpress.com/posts/scheduled and wordpress.com/pages/scheduled

<img width="374" alt="Screen Shot 2020-04-14 at 11 22 10" src="https://user-images.githubusercontent.com/1233880/79208308-33c96780-7e42-11ea-99bc-22e39397c1a4.png">

First one refers to the last modified date while the latter indicates when the post will be published. 

In order to reduce the amount of copy, let's remove the last modified date entirely and only display the date t's scheduled.

That way, we'll always display one date depending on post status:
- Published date for published posts.
- Scheduled date for scheduled posts.
- Last modified date for draft posts.
- Trashed date for trashed posts.

To make clear what the date means, we'd need to add appropriate labels in a similar fashion to WP Admin:

<img width="1340" alt="Screen Shot 2020-04-07 at 2 27 34 PM" src="https://user-images.githubusercontent.com/1270189/78721419-62908c80-78dc-11ea-9ffd-d0465805014a.png">

**Comment by millerf** [comment]
I am up for it @mmtr

**Comment by millerf** [comment]
I did a quick mock-up here with all the possible statuses available (the "private" statuses weren't taken into account so far). By the way, there is no indication if the post is private or not?

![Screenshot 2020-04-15 at 00 31 49](https://user-images.githubusercontent.com/790558/79280455-b1c45780-7eb0-11ea-979a-84a6532dfa36.png)

Let me know your thoughts @mmtr. I know it is not exactly what you meant by  "add appropriate labels", but I wanted to explore that path first...

**Comment by mmtr** [comment]
I think that's heading in the right direction, @millerf! The labels you used are more than appropriate 🙂. Let's see if @Automattic/dotcom-manage-design have any more feedback.

And yeah, we currently don't show any indicator for private posts, so it's fine to don't handle them.

**Comment by millerf** [comment]
If we are headed this way, should we then keep the status displayed when we are not in "search"?
Maybe it would make sense, instead of just having the same status with the small clock icon without any text label...

**Comment by millerf** [comment]
I just realized there is a "penfding" status that we didn't take into account:
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/post-relative-time-status/index.jsx#L94

And also the "sticky" attribute.  

I am thinking about doing a good refactor of PostRelativeTimeStatus component as it can be simplified and made more readable. I am waiting on something from design to drop in some ideas before I start, though...

**Comment by mmtr** [comment]
> should we then keep the status displayed when we are not in "search"?

I'm not sure, I think is maybe enough with the existing navigation tab.

<img width="385" alt="Screen Shot 2020-04-17 at 10 32 46" src="https://user-images.githubusercontent.com/1233880/79549261-09241c80-8097-11ea-83f9-6fc3319b5067.png">

> I just realised there is also a "pending" status
> And also the "sticky" attribute.

Great catches! Feel free to refactor the component if that helps with this issue.

> I am waiting on something from design to drop in some ideas before I start, though...

I've pinged them in our internal Slack channel and added discoverability labels to the issue, so they should provide some directions shortly.

**Comment by sixhours** [comment]
> If we are headed this way, should we then keep the status displayed when we are not in "search"? Maybe it would make sense, instead of just having the same status with the small clock icon without any text label...

In the interests of simplicity, I think only showing the status in search results is fine for now. Showing it for every view adds clutter and duplicates the secondary navigation tabs.

> I just realised there is also a "pending" status that we didn't take into account:
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/post-relative-time-status/index.jsx#L94

> And also the "sticky" attribute.

I think this is another case of poor information architecture and legacy features coming back to bite us. We have multiple statuses (statusii?? :D) and only some of those are displayed in secondary navigation tabs. We also have statuses that aren't clear -- Sticky is a WordPress-jargon-y term, for example, and I have no idea what Pending is without looking at the code -- maybe waiting on an administrator to publish a post from an Author-level user?

I think it's OK to leave these as-is to avoid disruptions. Eventually we need to look at the information architecture of these screens within the context of the whole site management experience, but that goes beyond the scope of this task.

I think your proposed mockup is spot-on as far as displaying the dates. 👍

**Comment by millerf** [comment]
@sixhours The OED refers to three possible plurals, two of which are now rare.

Status (rare)
Statuses (now usual)
Statusses (rare).
```
Inflections: Pl. (rare) status /ˈsteɪtjuːs/ , (now usu.) statuses /ˈsteɪtəsɪz/ , (rare) statusses /ˈsteɪtəsɪz/ .

Etymology: A borrowing from Latin. Etymon: Latin status.
```

**Comment by sixhours** [comment]
Oh I know, I was just being a goof. 😂 I'd never heard of Statusses though, TIL!

**Comment by millerf** [comment]
Hehe. Me neither. We learn something every day!
But I wouldn't have been surprised  to find something like "statii", as it is derived from latin.
