### ISSUE TITLE
People: users should be able to delete usernames using backspace on Android

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#4108]
#### Steps to reproduce
1. Go to add a new user either on Android  at people/new/$site
2. Type in a username and make sure it's tokenized:
![tokenized-username](https://cloud.githubusercontent.com/assets/11487924/13833375/c524605e-ebbb-11e5-8cf9-01027e1f0ae2.png)
3. Press the backspace key and see that it does not delete the username.

#### What I expected
I expected the backspace key to delete the username when the cursor is positioned right after the username.

#### Browser / OS version
Android 6.0.1 on Nexus 6, using Chrome 49.0

**Comment by ebinnion** [comment]
Thanks for reporting this. I'm going to close this in favor of #4202.
