### ISSUE TITLE
Domains: Require WordPress.com DNS for Primary Domain

### ISSUE THREAD

**Issue by tijosh** [Automattic/wp-calypso#41095]
Currently, it's possible to have a primary domain that does *not* load the WordPress.com site. This can cause problems and confusion for users who believe the domain is properly mapped or loading the site, when in fact the domain is pointing elsewhere.

Requiring WordPress.com name servers or A records for a domain to be primary helps reduce this confusion.

**Comment by klimeryk** [comment]
Thanks for the suggestion! 🙇‍♂️ 
At first, this seems like a good idea in a perfect world - but I'm worried in reality issues with DNS propagation and some configurations (Cloudflare?) could cause as much confusion as this would alleviate [citation needed ;)]. For example, I can imagine a user changed their DNS records (at us or at their registrar) and want to start using the domain ASAP with their site (as primary). But we're now asking them to check in periodically, waiting for the DNS records to propagate - which could be very hard for them to grasp ("How does DNS propagation work? It works on my side! Why are you showing me this error?").

And the other way around - should we unset the domain as primary if it's not pointing to our servers anymore? What if it's a temporary issue?

With the ongoing work to improve domain status page, I think we're in a better position to inform the users there where their domain is pointing and letting them adjust if necessary. There are already plans (in progress?) to clearly show an indication if a domain is pointing to the WPCOM site, etc. See p99Zz8-UK-p2 for more info - would love to hear your thoughts there!

**Comment by klimeryk** [comment]
Speak of the devil: looks like it's being implemented as we speak! https://github.com/Automattic/wp-calypso/pull/41019 :)
