### ISSUE TITLE
Use Recoleta for all page headings

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#41090]
Now that #41045 is merged and we're using Recoleta for the page heading in Customer Home, we should use it for all page headings in Calypso. If Customer Home has a different heading font it creates a disjointed experience.

For now, we'll just start with page headings, leaving the rest of the subheadings on the screen as is. I believe we can do this by updating the `<FormattedHeader>` component. But we need to be aware of other places it's used (I think the Jetpack Connect flow is one place?), and make sure teams are aware.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/448298/79231726-813ed800-7e34-11ea-82f5-fe2c8f982e27.png">

<img width="239" alt="image" src="https://user-images.githubusercontent.com/448298/79231734-869c2280-7e34-11ea-95c0-244d641f4edf.png">

**Comment by mmtr** [comment]
> But we need to be aware of other places it's used (I think the Jetpack Connect flow is one place?), and make sure teams are aware.

Yeah, just noted this as well when deploying, so I reverted my first attempt to make sure we all are aligned on this.

This is how some of the other places using `FormattedHeader` could look like with Recoleta.

**Signup**
<img width="1036" alt="Screen Shot 2020-04-15 at 10 47 40" src="https://user-images.githubusercontent.com/1233880/79318608-7e60e780-7f07-11ea-84de-726b26fb8001.png">

**Jetpack connect**
<img width="391" alt="Screen Shot 2020-04-15 at 10 48 52" src="https://user-images.githubusercontent.com/1233880/79318635-86b92280-7f07-11ea-9a4d-9bc3742cfd73.png">

**Comment by mmtr** [comment]
Alternatively, we could just target the page headings, and keep using the current font in the rest of `FormattedHeader` instances. Explored this approach in https://github.com/Automattic/wp-calypso/pull/41126.
