### ISSUE TITLE
Domains: Nudge to set properly mapped domain to Primary

### ISSUE THREAD

**Issue by tijosh** [Automattic/wp-calypso#41096]
After a domain is mapped and the DNS is changed to point to WordPress.com, it can be confusing for users to still see the `.wordpress.com` domain for their site.

We should add a Customer Home notification/prompt when the system detects that a mapped domain is now loading the WordPress.com site.

**Comment by jordesign** [comment]
Closing this in favour of https://github.com/Automattic/wp-calypso/issues/55739
