### ISSUE TITLE
Jetpack Plugins: plugin titles should fade out as they are overlapped by the Install button

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#411]
We should switch to using the `@mixin long-content-fade` that shaunandrews created instead of truncating long plugin titles with an ellipsis.

Here's what it looks like right now:

<img width="967" alt="08b06ae4-5872-11e5-90c1-3ebc161b1125 1" src="https://cloud.githubusercontent.com/assets/11487924/11321315/2793f906-9087-11e5-9cc3-7f6476546632.png">

**Comment by jeremeylduvall** [comment]
Swapped the ellipsis out for the fade :)
