### ISSUE TITLE
Editor: Update Switch to Classic Editor link

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#41108]
> As a user who has previously used the WordPress.com editor,
> I want to switch to the Classic editor once the WordPress.com editor is deprecated,
> So that I can use a more familiar interface for editing page and post content.

## Requirements

Once the WordPress.com editor is deprecated

1. Update the "Switch to Classic Editor" link to go to the Classic editor in wp-admin
1. The user's preference for the Classic editor is tracked such that we can compare the percentage of users using the Classic editor vs the Block editor (see #41309)
1. For non-Atomic Jetpack sites, hide the link, as the Classic editor plugin may or may not be installed and activated.

## Notes

- Information about the Gutenberg Opt-In API: PCYsg-hNB-p2

- How will we detect if a user has previously used the WordPress.com editor, or not?

<img width="271" alt="Screen Shot 2020-04-14 at 15 02 56" src="https://user-images.githubusercontent.com/1699996/79269776-92064280-7e62-11ea-84b4-57007e522cac.png">

**Comment by creativecoder** [comment]
Notes from discussing this

> If a user has previously used the WordPress.com editor

Might be difficult to detect. We may need to add a user attribute to record this in some way based on the current editor setting for a site. Also might be able to look at the blog sticker history, if that tracks editor preference in some way.

**Comment by glendaviesnz** [comment]
I think we can just keep the exiting `calypso_gutenberg_opt_in` track event for this that event name still makes sense even though opting out goes to classic instead of calypso editor - the event has a boolean `opt_in` property.

**Comment by creativecoder** [comment]
Note description updated

1. Removed the following, to create a consistent experience for all WordPress.com users
    > 1. If a user has previously used the WordPress.com editor, continue to show the "Switch to Classic Editor" link in the editor meatball menu
    > 1. If a user has _not_ previously used the WordPress.com editor, remove the "Switch to Classic Editor" link

1. Added a requirement to hide the link for Jetpack sites
