### ISSUE TITLE
Domains: show .blog domain name suggestions in signup when originating signup from existing .blog landing page

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#41110]
Follow-up issue to track a report by @supernovia on internal P2: pau2Xa-Vs-p2

Track incoming signups from sites like tech.blog to properly show the relevant .blog suggestions by default. This requires fix to the domain step to handle the query params.

#### Steps to repeat

1. Starting at the .blog landing page: https://tech.blog
2. Click "Start your Tech.blog" button
3. Page redirects to signup: `https://wordpress.com/start/domains?site_type=blog&vertical=tech&ref=dotblog-landing`
4. Search for a domain name.

Expected: to see `tech.blog` choices.
Result: no `tech.blog` domains visible in the results.

<img width="1071" alt="Screen Shot 2020-04-14 at 14 21 38" src="https://user-images.githubusercontent.com/66797/79275549-42704880-7e5b-11ea-820d-5b98a242a363.png">

I tried to search for `nanobartechblog` as a new user signing up from tech.blog:

<img width="1392" alt="Screen Shot 2020-04-14 at 14 23 27" src="https://user-images.githubusercontent.com/66797/79275749-a4c94900-7e5b-11ea-9a06-d8875b7e06d9.png">

**Comment by lancewillett** [comment]
A related issue: #40970 for Gutenboarding flow

In this case, a new or existing user cannot search for a specific .blog subdomain.

I did a quick test as both new and existing user with Calypso signup — and it worked as expected in both cases.

<img width="1267" alt="Screen Shot 2020-04-14 at 14 27 32" src="https://user-images.githubusercontent.com/66797/79276161-59fc0100-7e5c-11ea-86b5-c4158ec01627.png">

**Comment by lancewillett** [comment]
@Automattic/martech Hi team, checking in on this one — traffic coming from .blog landing pages still cannot choose a .blog domain in signup.

**Comment by taggon** [comment]
Hello, @lancewillett! I will start working on this from this week after a higher priority task is wrapped up.

**Comment by taggon** [comment]
The PR has been shipped. Now users from .blog LPs will see a `.VERTICAL.blog` suggestion in the domain search step.

**Comment by supernovia** [comment]
Thank you!
