### ISSUE TITLE
Themes info page Open Live Demo link broken when not using a single site as context

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#41118]
On a theme info page, when I click on the Open Live Demo link, like on this one: https://wordpress.com/theme/alves it goes to a blank page. It only works if you right click and open in a new tab.

Looking at the JS console we see related errors:

> async-load-components-web-preview-component.a2ff7de6b2ed0a0ce13c.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'URL' of null
    at Function.Object.recordTracksEvent [as mapToProps] (async-load-components-web-preview-component.a2ff7de6b2ed0a0ce13c.min.js:1)

**Comment by lancewillett** [comment]
Thanks for the report, @tanjoymor.

Possibly related:
- https://github.com/Automattic/wp-calypso/issues/34922
- https://github.com/Automattic/wp-calypso/issues/32663

And internal ref: pNEWy-cL1-p2

**Comment by davoraltman** [comment]
@lancewillett Piggybacking here as it looks related. When visiting https://wordpress.com/themes (while logged out of WordPress.com) none of the demo links for any of themes work, you just get a blank page.

**Comment by lizswafford** [comment]
Similar issue - the link for “Open Live Demo” on the Obsidian theme page - https://wordpress.com/theme/obsidian - is not working. When I click the link I do not get redirected to https://obsidiandemo.wordpress.com/ instead I see a blank page. Same results in FireFox and Safari on macOS.

**Comment by lancewillett** [comment]
Inspecting this locally with Calypso, I see the following error:

```
Warning: Failed prop type: The prop `installingThemeId` is marked as required in `AutoLoadingHomepageModal`, but its value is `undefined`.
    in AutoLoadingHomepageModal (created by ConnectFunction)
    in ConnectFunction (created by ThemeSheet)
    in main (created by Main)
    in Main (created by ThemeSheet)
    in ThemeSheet
    in div (created by ThemesSiteSelectorModal)
    in ThemesSiteSelectorModal (created by ConnectFunction)
    in ConnectFunction
    in Unknown (created by ConnectFunction)
    in ConnectFunction (created by ThemeSheetWithOptions)
    in ThemeSheetWithOptions (created by Localized(ThemeSheetWithOptions))
    in Localized(ThemeSheetWithOptions) (created by ConnectFunction)
    in ConnectFunction
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by ConnectFunction)
    in ConnectFunction (created by ReduxWrappedLayout)
    in MomentProvider (created by ConnectFunction)
    in ConnectFunction (created by ReduxWrappedLayout)
    in Provider (created by ReduxWrappedLayout)
    in ReduxWrappedLayout
```

**Comment by lancewillett** [comment]
And:

```
peError: Object(...)(...) is nullasync-load-components-web-preview-component.js line 219 > eval:484:85
    mapState app:///./components/web-preview/content.jsx:484
    Redux 6
    React 3
    ConnectFunction Redux
    React 12
    performSyncWorkOnRoot self-hosted:919
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority app:///../node_modules/scheduler/cjs/scheduler.development.js:697
    React 6
    require app:///./components/async-load/index.jsx:65
    load app:///./components/web-preview/index.jsx:21
```

**Comment by lancewillett** [comment]
Testing notes:

- The blank screen and related JS error only seem to happen when the theme is previewed outside the context of a website. When using `/theme/hever/testerlance.wordpress.com` with a site selected — the preview works as expected.
- Right-clicking the link works as expected (new tab/window).

**Comment by lancewillett** [comment]
@davoraltman Thanks, it's the same issue.

**Comment by lancewillett** [comment]
Tracked it down to possibly this commit: https://github.com/Automattic/wp-calypso/commit/9cd492b1405082554961ce909515e1cc5c105ba1#diff-8ae00623d8ce2569caf144aa05fedec9 by @adamziel which added the `URL` and site context to the WebPreview component.

@michaeldcain or @adamziel Could you look at this and maybe add way to check for non-site specific context?

**Comment by lancewillett** [comment]
Confirmed working again. Thank you, @michaeldcain 👍
