### ISSUE TITLE
Typescript warnings about exports not found

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#41113]
When starting Calypso, I get a ton of warnings like this that appear in the console:

```js
WARNING in ./my-sites/checkout/composite-checkout/wpcom/types.ts 9:0-1022
"export 'WpcomStoreState' was not found in './types/wpcom-store-state'
```

It's weird because that type (and all the others mentioned) definitely exists. This doesn't appear to affect the actual running of code.

**Comment by sirbrillig** [comment]
I think it might be this: https://github.com/webpack/webpack/issues/7378#issuecomment-492641148

Basically, when re-exporting types, you have to use `export type` and `import type` to comply with the rules of Typescript 3.8 (which we are using in Calypso).

However, doing so causes Prettier to throw an error because `export type` is not recognized [until prettier 2.0](https://github.com/prettier/prettier/issues/7263). 

So I think that right now we just have to have one error or another.

**Comment by ockham** [comment]
I think @sgomes is on this, see #41100.

**Comment by sgomes** [comment]
@ockham I am indeed. I had to close that PR to fix some `@wordpress/*` issues first (see #41141), but once that's sorted I'll go back to trying to update Babel.

**Comment by sirreal** [comment]
https://github.com/Automattic/wp-calypso/pull/41114 is upgrading to wp-prettier@2.

**Comment by sgomes** [comment]
The new Babel upgrade PR is at #41175.

**Comment by sgomes** [comment]
We may need some updates to `eslint-plugin-import` as well, so that `import type { Foo } from './foo';` and `import { makeFoo } from './foo';` can coexist in the same file without claiming there's a duplicate import.
