### ISSUE TITLE
Clean out `pageBuilderMVP` test and related code

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41134]
There's an old [`pageBuilderMVP` A/B test](https://github.com/Automattic/wp-calypso/blob/c0d97fbd45d43b5d641452fa9952dfdd3d341de2/client/lib/abtest/active-tests.js#L64-L72) that should really be cleaned out.

We don't know what consequences there would be when removing this, so it needs some P2 digging / asking around.

It's not related to wpcom-FSE experiment, but to a brief experiment that happened before that (paAmJe-3G-p2).

**Comment by mattwiebe** [comment]
Ok, ok, I'll clean up my mess. :)

**Comment by roo2** [comment]
@mattwiebe I'm on Create Focus maintainance roatation now, going through our "in progress" column. Is this something I can help with by taking the `pageBuilderMVP` a/b test out of the calypso code?

It's set to 100% on control

**Comment by mattwiebe** [comment]
Howdy @roo2 - you will also need to remove anything that checks the abtest, and most anything in `client/lib/signup/page-builder.js` and assorted places those functions are used. See also #32005 and #31822 where things were initially added. Happy to help review or answer questions.

**Comment by mattwiebe** [comment]
Props to @tyxla for cleaning this up in #53180

**Comment by tyxla** [comment]
Actually, to be precise, passing the props to @jessie-ross for cleaning it up in #53083. 😉
