### ISSUE TITLE
Gutenboarding: display long domain names in header

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#41133]
Theoretically a domain name can be up to 253 characters long ([255 octets](https://tools.ietf.org/html/rfc1034)) so the visual results might not be so nice.

First reported in https://github.com/Automattic/wp-calypso/pull/41069#issuecomment-613943705
Follow up question: https://github.com/Automattic/wp-calypso/pull/41069#issuecomment-613953240

We could truncate the text displayed inside the domain picker button to <s>something like 70 characters.</s> fit the screen width

**Comment by dubielzyk** [comment]
I mocked up a bunch of variation and how we should handle the different cases:
![image](https://user-images.githubusercontent.com/2896062/79958792-a4e0ce80-8483-11ea-8b27-f03c67ace21a.png)

I've added them to the Figma file too :)

**Comment by razvanpapadopol** [comment]
I believe some progress has been made in #42040 at least for the mobile view.

**Comment by yansern** [comment]
Fixing by ellipsing: https://github.com/Automattic/wp-calypso/pull/42198

**Comment by dubielzyk** [comment]
Looks like this is solved :)
