### ISSUE TITLE
Editor: gallery/contact form is duplicated on edit if it appears as first line in editor

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4115]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. As the very first thing in the editor (no blank lines) add an image gallery (or new contact form)
3. Image gallery shows correctly
4. Click edit, and change image gallery format (eg. circles)

#### What I expected

Image gallery is _modified_ to the new format (eg. circles)

#### What happened instead

Image gallery is _duplicated_ as the new format (eg. circles)

#### Browser / OS version

Chome  49.0.2623.87 OSX 10.11.3 (Could not repro on Firefox latest OSX)

#### Screenshot / Video

![edit gallery first line editor](https://cloud.githubusercontent.com/assets/128826/13835603/27fdd302-ec45-11e5-83e9-b7f8f62fcfc0.gif)

**Comment by deBhal** [comment]
I just had a customer with this same issue triggered by rearranging the images in the gallery as well.

**Comment by jkudish** [comment]
I can reproduce this consistently with the above repro steps in Chrome (on Linux and OS X). cc @aduth

**Comment by aduth** [comment]
On a hunch, decided to test whether simply updating TinyMCE to the latest version would resolve the issue, and it appears to do so. [The changelog](https://www.tinymce.com/docs/changelog/) doesn't include any obvious item that would indicate its being fixed. I'll plan to put together a pull request, though I'm observing at least one regression with the update that I'll want to fix before doing so.
