### ISSUE TITLE
Simple Payments: INR not available in Block Editor as a Currency

### ISSUE THREAD

**Issue by jenlynnemc** [Automattic/wp-calypso#41176]
#### Steps to reproduce

1. Starting at URL: apoorvaneti.com and my test site jenstestsite123.com
2. Tried adding a Simple Payment Block to a page (both users Shop page and my test page)
3. Tried to select INR as a payment option. (Screenshot attached below)
4. INR does not appear as an option for currency 
5. Tried adding a Simple Payments Widget and INR is available as a Currency option (Screenshot attached below)

#### What I expected

If INR is available as a currency for the Simple Payments Widget, I thought it would be available as a currency in the block editor as well?

#### What happened instead

INR currency was not available in the block editor adding a Simple Payments Block.

#### Screenshot / Video
Block Editor:
<img width="998" alt="Screen Shot 2020-04-16 at 8 25 52 AM" src="https://user-images.githubusercontent.com/26546176/79451170-7911a480-7fbc-11ea-908b-c7b8805b54a9.png">

Widget:
<img width="282" alt="Screen Shot 2020-04-16 at 8 27 33 AM" src="https://user-images.githubusercontent.com/26546176/79451322-bece6d00-7fbc-11ea-94b3-22414b5c032e.png">

#### Context / Source

#user-report
#simple-payments

Ticket: https://woothemes.zendesk.com/agent/tickets/2883518

**Comment by dcoleonline** [comment]
21290303-hc also requested this

**Comment by jamiepalatnik** [comment]
Another request in 21515360-hc

**Comment by arunsathiya** [comment]
>If INR is available as a currency for the Simple Payments Widget, I thought it would be available as a currency in the block editor as well?

Due to this point, I wonder if this must be marked as `Bug` instead of `Enhancement`? 🤔 

Some related threads: https://github.com/Automattic/wp-calypso/issues/24960, https://github.com/Automattic/wp-calypso/pull/28236, https://github.com/Automattic/wp-calypso/issues/26262

**Comment by ccwalburn** [comment]
Another request here: 3312855-zen

**Comment by worldomonation** [comment]
Re-labeled with `Bug` instead of `Enhncement`.

**Comment by artpi** [comment]
There are ongoing issues with INR support due to changing legal landscape around the particular API we are using

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- INR is now an available currency in the Paid Content block (_fka premium content_)

![Markup on 2023-06-28 at 17:09:58](https://github.com/Automattic/wp-calypso/assets/27249804/06d74a75-fa1f-4116-8ddf-5b96d747de92)

📌 ACTIONS
- Closed as resolved

**Comment by simison** [comment]
I'll re-open, still no INR support in simple payments (aka paypal button). 

Payment buttons meanwhile do seem to support INR [as noted above](https://github.com/Automattic/wp-calypso/issues/41176#issuecomment-1612260340), but that's a different feature.

**Comment by millerf** [comment]
Closing this as Paypal [does not support INR as of now](https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies/). We can reopen when there is a change in Paypal's policy.

**Comment by simison** [comment]
Cool 👍  Thanks for checking; they used to list INR with a note that it's available for "in country purchases only" (from/to are both in India, just like Brazilian `BRL` currently) but looks like they've dropped it entirely since last I checked.
