### ISSUE TITLE
Reader: followed sites appear as if not being followed in Safari with Prevent Cross-Site Tracking on

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#41183]
#### Steps to reproduce

1. Using Safari, activate the **Prevent Cross-Site Tracking** option
2. Log into WordPress.com
3. Visit a WordPress.com site that you are following

#### What I expected

The Follow button should say "Following"

#### What happened instead

The Follow button says "Follow" and will ask the user to logon if clicked.

The workaround is to deactivate the  **Prevent Cross-Site Tracking** option, which then allows cross-site tracking across all sites, which raises privacy concerns on other sites. 

#### Browser / OS version

Tested on MacOS Safari 13.1 and iOS Safari 13.3.

#### Context / Source

Seen in multiple places. Most recently in 2862259-zen

Related issues also caused by cross-site tracking blocks: #35140, #33077, #25115

**Comment by kriskarkoski** [comment]
@lancewillett Should this go on Trac since it's for the Follow button on sites rather than on the Reader/in Calypso? Or is this part of our move to shift these things to wp-calypso that would have gone there before.

**Comment by lancewillett** [comment]
@kriskarkoski Yeah — fine to leave here since we're trying to shift things to GitHub.

Thanks for sharing this, @GeoJunkie. Good to track it down as part of the wider 3rd Party Cookie project.

Personal testing note: this happens to me frequently because I surf WordPress.com sites with Safari desktop. Even when logged in and following a site, the action bar will show "Follow" as the action.

**Comment by roo2** [comment]
seems to be working now, I tested in safari on a site with a custom domain and the tracking protection setting enabled. After following a site and refreshing I saw the following state as expected in the action bar 

https://user-images.githubusercontent.com/22446385/202963136-cdf8e81e-c490-4241-8644-d62cd2afde05.mov
