### ISSUE TITLE
Editor: Contact Form: Enhancement: Warn user if unsaved changes when closing contact form

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4118]
#### Steps to reproduce
1. Starting at URL: Editor with Contact Form enabled
2. Add or edit a contact form
3. Make lots of changes
4. Accidently click or tap outside of contact form dialog
#### What I expected

To be warned I am about to lose unsaved changes
#### What happened instead

Changes are lost as dialog is instantly closed
#### Browser / OS version

Chrome OSX 10.11.2
#### Screenshot / Video

![close dialog](https://cloud.githubusercontent.com/assets/128826/13835920/26689da8-ec48-11e5-9085-64d65ae0b99a.gif)

**Comment by alisterscott** [comment]
Wp-admin currently provides a warning to the user in this scenario

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Tested with Firefox 57.0.1 on macOS 10.13.2 and confirmed this is still an issue.
