### ISSUE TITLE
Gutenboarding: Consider removing design names in choose design step

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#41204]
In the design selection step each design has a name below - would it be possible to get rid of those? The names are abstract and don't provide much help or context. Removing them would also recover some space on the screen. Are there any downsides to removing them entirely?

<img width="650" alt="desing_step" src="https://user-images.githubusercontent.com/4550351/79516735-8ba8de00-808f-11ea-8dbf-b50ab197e518.png">

cc @ianstewart @olaolusoga

**Comment by olaolusoga** [comment]
For the design selection step, we can test removing the labels.

From an identification standpoint, it's helpful to have labels for the layouts. Helps users keep record of layouts they like—in cases where they're exploring different looks—and helps us with tracking.

**Comment by xpurichan** [comment]
@olaolusoga I'm checking in with you to see if the design names have been removed, or if that's still an ongoing effort? I was looking to close this issue if it is indeed fixed.

**Comment by olaolusoga** [comment]
We can close for now. We'll reopen when issue comes up again. Thanks.
