### ISSUE TITLE
Editor: Contact Form: Prevent users from adding second contact form to post/page

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4120]
#### Background

> One per page – Each post, page, and text widget will only display one contact form.

https://en.support.wordpress.com/contact-form/
#### Steps to reproduce
1. Starting at URL: Editor with the new contact form
2. Create the first contact form
3. Navigate elsewhere in editor
4. Click Add Contact Form
#### What I expected

Existing form to be displayed for edit
#### What happened instead

A new instance of a form is created, when previewing this is unsupported so doesn't appear in preview
#### Browser / OS version

OSX 10.11.2 Chrome 49
#### wp-admin behaviour

![add multiple contact forms](https://cloud.githubusercontent.com/assets/128826/13836512/17f4fdb0-ec4e-11e5-9304-e536a862a5b9.gif)
#### calypso behaviour

![calypso add multiple contact forms](https://cloud.githubusercontent.com/assets/128826/13836523/33770682-ec4e-11e5-9fa1-e4ffdf0c6cce.gif)

**Comment by rodrigoi** [comment]
The problem with enforcing a _only one form_ rule is that, if the user changes to the HTML editor, we effectively lose control of how many forms a user can add. By just writing the shortcode, the user can add as many forms as wanted, with the expectation that all those forms will work.

I think we should rethink that rule, and I think we should support multiple forms.

Also, this is a buggy behaviour. There are certain scenarios where you can add as many forms as you like to a page and they all show:

![multiple forms rodrigo litter box](https://cloud.githubusercontent.com/assets/233601/13864648/1db0951e-ec82-11e5-96a8-4a8b13725e89.png)

**Comment by alisterscott** [comment]
Thanks for your feedback on this. It seems like a complicated issue.

> The problem with enforcing a only one form rule is that, if the user changes to the HTML editor, we effectively lose control of how many forms a user can add. By just writing the shortcode, the user can add as many forms as wanted, with the expectation that all those forms will work.

One way to avoid this would be to remove duplicate contact forms added via the HTML editor when switching back to the rich text editor - might be too complicated for what it's worth

> Also, this is a buggy behaviour. There are certain scenarios where you can add as many forms as you like to a page and they all show:

Yes, I tested this and does seem buggy. If the first form in the page is _duplicated exactly_ in the same post/page, then it appears as many times as it is duplicated. If additional _non identical_ contact forms are added after the first, these never appear.

Example: https://eatkibbeling.wordpress.com/2016/03/18/multiple-forms/

> I think we should rethink that rule, and I think we should support multiple forms.

Would this be a database/API change?

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue.  Although now we actually have the contact form preview inline in the editor instead of the placeholder seen in the original report:

![screen shot 2016-05-12 at 3 25 59 pm](https://cloud.githubusercontent.com/assets/7233112/15227574/e473724e-1855-11e6-9e29-02d038437b1d.png)

**Comment by alisterscott** [comment]
Confirmed this is still an issue.

In the visual editor you can add/edit multiple different forms:

![editor](https://cloud.githubusercontent.com/assets/128826/19253697/6e2acf1c-8f90-11e6-88c3-61d1633c9ecb.png)

As soon as you preview/publish the second and subsequent forms do not display:

![preview](https://cloud.githubusercontent.com/assets/128826/19253709/8426d2fc-8f90-11e6-9a6b-5a39de285546.png)

I think the simplest fix for a majority of users would just be to prevent entering multiple forms in the visual editor

**Comment by rachelmcr** [comment]
I confirmed that this is still an issue.

> I think the simplest fix for a majority of users would just be to prevent entering multiple forms in the visual editor

Agreed. Our [Contact Form](https://en.support.wordpress.com/forms/contact-form/#tips) support doc also states that only one form is supported per post/page, and changing the visual editor behavior should resolve it for most users.

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Tested and confirmed that a second form added to a page using the Calypso editor is visible in the editor but does not get rendered in the preview or on the front end.

Example of a preview of a page containing two forms:

![screen shot 2018-02-14 at wed feb 14 10 07 35 am](https://user-images.githubusercontent.com/1119271/36217837-b0e64018-116f-11e8-8721-b4ea28a08a05.png)
<sup>Seen at https://wordpress.com/page/design5279.wordpress.com/7618 using Firefox 58.0.2 on macOS 10.13.3.</sup>

Example of the front end view of a page containing two forms:

![screen shot 2018-02-14 at wed feb 14 10 07 55 am](https://user-images.githubusercontent.com/1119271/36217824-ac11bbe4-116f-11e8-942a-5a2feaa10938.png)
<sup>Seen at https://design5279.wordpress.com/contact-form-test/ using Firefox 58.0.2 on macOS 10.13.3.</sup>

Note: this came up in p4k3M4-2uX-p2.

**Comment by davipontesblog** [comment]
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.
