### ISSUE TITLE
Gutenboarding: Plans and payment screen fixes

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41215]
The first part of the flow up until the building loading screen is looking really good, but there's a few things I'd love to see if we could polish up for the plans and payment screens. Here's a few discussion points and fixes.

- [ ] Between the loading state and plans page there's a [fullscreen blue screen and blinking](https://d.pr/v/iKNWPa). Can we remove this?
- [ ] Is it possible to get our header bar on the [plans](https://d.pr/i/wlzlWd) and [payment](https://d.pr/i/PeJ1jp) screens?
- [ ] Is it possible to make the background white on the [payment pages](https://d.pr/i/PeJ1jp)?

**Comment by razvanpapadopol** [comment]
Fixed in current version
