### ISSUE TITLE
Domain Picker: when explicitly searching for a domain, check if it's available

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41219]
**Update (22.12.2020)**

* We can have the availability check directly inside DomainPicker. Tracked in https://github.com/Automattic/wp-calypso/issues/48634
* Add also an exact `{SUBDOMAIN_NAME}.*.blog` free subdomain option to the suggestions list if the search query includes `'.blog'`.

___

pbAok1-1MG-p2#comment-3587

<img width="730" alt="Screenshot 2020-12-22 at 17 56 47" src="https://user-images.githubusercontent.com/14192054/102907699-19d72e80-447f-11eb-8433-2e5825f98ff8.png">

___

via https://github.com/Automattic/wp-calypso/issues/40971#issuecomment-614828121

> [...] when the user explicitly searches for a FQDN (_Fully Qualified Domain Name_), including a subdomain. That means they have a specific domain in mind and we should show its availability. If it's available, we should be sure to communicate that to the user - currently we simply insert it as the first search result:
> 
> <img width="984" alt="Screenshot 2020-04-16 at 18 35 16" src="https://user-images.githubusercontent.com/3392497/79493501-17c7f080-8011-11ea-973b-ef3b7b674d6d.png">
> 
> (since the user _might_ be interested in other suggestions, which might be more attractive)
> 
> But if the domain is unavailable, we should guide them on what are their options. For example, this domain is registered, but the user can transfer it in:
> 
> <img width="990" alt="Screenshot 2020-04-16 at 18 36 52" src="https://user-images.githubusercontent.com/3392497/79493623-43e37180-8011-11ea-8f76-4af3ff9533b1.png">

Different possible domain states are listed at https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/lib/domains/registration/availability-messages.js

Related: https://github.com/Automattic/wp-calypso/issues/41220

Design: 

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/87168/80486304-9d2d9800-8963-11ea-8950-4ec810a4d2bc.png">

See details in pbAok1-Hb-p2#comment-1472

### Acceptance criteria
- [x] When the users search for a FQDN that is unavailable, list their query as an unavailable suggestion

### Follow up
- [ ] Explain why it is unavailable. The list of explanations is https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/domains/registration/availability-messages.js#L40-L390.

**Comment by razvanpapadopol** [comment]
Closing this one and we'll continue to track the follow up in #51651
