### ISSUE TITLE
Gutenboarding: Domain picker modal search results not persistent across page refresh

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#41228]
> When you pick a domain and refresh the page, the domain is persisted alright, but the picker modal doesn't seem to be aware of this information and does a new search based on the site title. I'm not sure how can we go about fixing this.

Original posted by @alshakero on https://github.com/Automattic/wp-calypso/pull/41212#pullrequestreview-395455954

**Comment by simison** [comment]
We'll be switching to a step so this won't be valid anymore.
