### ISSUE TITLE
Gutenboarding: Reorganize domain picker folder structure

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#41221]
It might be time to organize all these under a `domain-picker` directory:

```none
domain-picker/
  - index - re-exports whatever makes sense (modal, popover, the contents?)
  - modal
  - popover
  -
```

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/41212_

**Comment by razvanpapadopol** [comment]
Domain Picker [is now a package](https://github.com/Automattic/wp-calypso/pull/42409) and can be used inside of a modal, as a full screen page, etc.
