### ISSUE TITLE
Gutenboarding: before domain is confirmed, check that it really is available

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41220]
via https://github.com/Automattic/wp-calypso/issues/40971#issuecomment-614828121

> The moment customer picks a domain - basically you have to assume that the suggestion endpoint is not always 100% accurate and might return unavailable domains. So, once a domain is selected, you should for it's availability via the is-available endpoint.
You can see it in action in the current domain search - at first I select a suggestion that turns out to unavailable and then one that's available and I'm allowed to proceed.
>
> https://cloudup.com/c0yynmBzeud

Some existing code:

https://github.com/Automattic/wp-calypso/blob/711190aee23edea9006c079d44b7b7cee5d9b977/client/lib/wpcom-undocumented/lib/undocumented.js#L482-L492

https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/lib/domains/registration/availability-messages.js

See details in pbAok1-Hb-p2#comment-1472

Related: https://github.com/Automattic/wp-calypso/issues/41219

## Design

Design for state when domain isn't available:

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/87168/80486304-9d2d9800-8963-11ea-8950-4ec810a4d2bc.png">

@dubielzyk how should the "loading" state look like after selecting a domain from the list? I don't know how long it takes typically but we should make sure it doesn't look bad on slow connections or if API is slow to respond.

We can meanwhile implement this without the loading state.

**Comment by sirreal** [comment]
Started on this in #41548.

**Comment by dubielzyk** [comment]
[Made loading state mock](https://d.pr/i/wWJ3sY). Let's change the radio to a spinner and disable the _Confirm_ button.

**Comment by simison** [comment]
Ahh, pity the [core spinner](https://github.com/WordPress/gutenberg/tree/2cf0a3d8ce079c0a51d409c051c0c053a88beea3/packages/components/src/spinner) is kinda lame:

<img width="136" alt="image" src="https://user-images.githubusercontent.com/87168/80591883-24900f80-8a27-11ea-8770-b68b1ce3872e.png">

Good thing we have Calypso spinner readily available here:
https://github.com/Automattic/wp-calypso/tree/master/client/components/spinner
