### ISSUE TITLE
Typography: Further standardize font weights across Calypso

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#41234]
We've removed `font-weight: 300` from Calypso's vocabulary, and even set up a linter to catch instances that fall outside any given parameters. It looks like we use 500, 600, and 700 frequently:

* 500: https://github.com/Automattic/wp-calypso/search?q=%22font-weight%3A+500%22&unscoped_q=%22font-weight%3A+500%22
* 600: https://github.com/Automattic/wp-calypso/search?q=%22font-weight%3A+600%22&unscoped_q=%22font-weight%3A+600%22
* 700: https://github.com/Automattic/wp-calypso/search?q=%22font-weight%3A+700%22&unscoped_q=%22font-weight%3A+700%22

Should we add these to the "approved" array for linting purposes? Or consider winnowing these down to 1-2 additional font weights besides 400?

**Comment by sixhours** [comment]
Example where a bold weight of 700 feels too bold: https://github.com/Automattic/wp-calypso/pull/41229#issuecomment-615349411

/cc @dotcom-manage-design what do you think? Should we swap 700 weight for 500? or allow both?

**Comment by lcollette** [comment]
Thanks for highlighting the inconsistencies, @sixhours! It looks like 600 is the more frequently used weight. What if we update the 500 and 700 weights to be 600 and standardize there?

**Comment by sixhours** [comment]
That sounds good to me! I'll spot-check some instances to see how that changes the visuals and comment here with those screenshots.

**Comment by sixhours** [comment]
Banners are probably one of the most widespread instances of `font-weight: 500` in action. This shows what it would look like to go up to `600`.

| Before | After |
| ------- | ------ |
| <img width="962" alt="Screen Shot 2020-04-20 at 5 52 29 PM" src="https://user-images.githubusercontent.com/2124984/79803364-d779b280-832f-11ea-8998-8193af1185c6.png"> | <img width="959" alt="Screen Shot 2020-04-20 at 5 52 36 PM" src="https://user-images.githubusercontent.com/2124984/79803376-dd6f9380-832f-11ea-9d80-b922a2a4daf0.png"> |

I'm trying to find other similar examples where making a change to one component would affect a series of UI elements across Calypso. I'll do more of that tomorrow.

**Comment by kwight** [comment]
I admit I'm loving the `600` over the `700`.

**Comment by sixhours** [comment]
I opened an issue on the stylelint-scales repo; I think this is something we can fix ourselves, but ideally the plugin itself is updated too: https://github.com/signal-noise/stylelint-scales/issues/37

**Comment by digitaljohn** [comment]
@sixhours We just pushed v1.3.0 https://github.com/signal-noise/stylelint-scales/releases/tag/v1.3.0

Let us know if you encounter any further issues. 👍

**Comment by davemart-in** [comment]
@sixhours can this one be closed out or are we still working on it?

**Comment by sixhours** [comment]
I think it can be closed out, I've done the majority of the big conversions, and I'm fixing others as I work on typography elsewhere when the linter picks them up.
