### ISSUE TITLE
Latest Posts: Wrong URL on Read More

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#41244]
#### Steps to reproduce
1. Create a new page, add the Latest Posts block.
2. On the block settings, under "Post content settings" check the "Post content" option.
3. Check the new page on the live site.

#### What I expected
That the "Continue Reading" links that show on the block to lead me to the post's page, as the post's title does.

#### What happened instead
The "Continue Reading" links load the page itself, where the block is.

I found odd that inside the editor, it shows "Read More" with the right URL, while the live site shows "Continue Reading" with the wrong URL.

#### Screenshot / Video

![LatestPostsIssue](https://user-images.githubusercontent.com/16104522/79638789-bbbeb280-815d-11ea-96ea-3a188d3a5312.png)

#### Browser / OS version
OS X 10.15.4
Chrome 81.0.4044.113

#### Context / Source
#user-report #2872972-zen

**Comment by arunsathiya** [comment]
This seems to be previously discussed here as well - https://github.com/Automattic/wp-calypso/issues/40500

As Lance noted, https://github.com/WordPress/gutenberg/pull/20541 (core Gutenberg update) must fix the issue and Gutenberg 7.9 is not released on WPcom so far. It will be available soon - p7DVsv-8tt-p2

@carinapilar, could you double-check if my interpretation is correct and close this issue?

**Comment by carinapilar** [comment]
Ah, it seems the same @arunsathiya! I wasn't able to find that one. Thanks! :)
