### ISSUE TITLE
Checkout: Incorrect checkout price in the length of subscription box when both credits and coupon code are applied 

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#41240]
#### Steps to reproduce

1. Add 32 free credits to an account.
2. Checkout the Premium plan.
2. On the check out screen, also apply the Happiness monthly coupon code.

#### What I expected

The *Choose your length of subscription* should only discount the coupon code discount 17% and show $79.68 ($96 x 17%)  price, as on the cart on the top right.

#### What happened instead

When coupon code is applied, the *Choose your length of subscription* box showed $47.68 (both credits **and** coupon code discount of 17% are applied: $96 - ($96 x 17%) - $32 = $47.68)

#### Screenshot / Video

Video: https://d.pr/v/vAiIJG

Screenshot: https://d.pr/i/7gUJHI

**Comment by sirbrillig** [comment]
I believe the lower number was actually correct; there's no policy that I'm aware of that prevents coupons and credits from being applied together. D45315-code should fix this.

**Comment by michaeldcain** [comment]
D45315-code has been deployed. Closing unless there are other reports.
