### ISSUE TITLE
Plans: loading state in /plans/compare

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#4125]
We probably need placeholders or a better loading state for `/plans/compare`. This is what it looks like now:

![domain](https://cloud.githubusercontent.com/assets/1248436/13848415/fcaa220c-ec51-11e5-8af9-ea549e8f3c59.gif)

**Comment by fabianapsimoes** [comment]
We do have placeholders already when a user switches sites from `/plans/compare`:

![domain](https://cloud.githubusercontent.com/assets/1248436/13848568/bc4f0b72-ec52-11e5-9370-5da19d01abe7.gif)

**Comment by hafizrahman** [comment]
Not sure how to replicate the issue on your first animation. Opening https://wordpress.com/plans/compare/SITE_ADDRESS in a fresh, new tab gives me the placeholders already (as shown on the second animation).

**Comment by fabianapsimoes** [comment]
- Go to `/plans` on a new tab.
- Click Compare Plans. You should see the page I show in the original issue.
