### ISSUE TITLE
Gutenberg v7.9.1 on wpcom: Back button styling overflowing the header

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#41269]
#### Steps to reproduce

1. Starting at URL: Edit a page in a dotcom-FSE enabled site
2. In the top-left corner of the screen the styling overrides for the `.edit-post-fullscreen-mode-close__toolbar__override` class appear to be making the button expand past the bottom of the header

#### What I expected

The back button to sit within the header.

This is how it looks in GB 7.8.1:

![image](https://user-images.githubusercontent.com/14988353/79719376-caee5d80-8321-11ea-8545-f61c40cb2b1a.png)

#### What happened instead

The back button is too large:

![image](https://user-images.githubusercontent.com/14988353/79719410-db063d00-8321-11ea-9427-1db6e82a1b34.png)

#### Browser / OS version

Chrome 80, MacOS 10.14.6

#### Context / Source

Part of: https://github.com/Automattic/wp-calypso/issues/41265

**Comment by noahtallen** [comment]
Sorry for not tracking this better! It should have been resolved in #41116 (will be deployed at next FSE plugin update.)

**Comment by andrewserong** [comment]
Perfect, thanks @noahtallen — I should have taken a closer look at the issues you'd already fixed! Much appreciated :)
