### ISSUE TITLE
Gallery Block: images not rendered when the site is private atomic

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#41272]
**Steps to reproduce**

1. Create a new private site (through the `variant` group of `ATPrivacy` A/B test)
1. Go Atomic
1. Upload a new media file to make sure we're using something that hasn't been cached by Photon yet
1. Create a tiled gallery with that new media file
1. Visit the site and confirm it's not displayed

**Expected result**

Properly working tiled gallery

**Description**
Tiled gallery module images are not rendered when the site is Private and Atomic. Jetpack always “photonizes” these URLs, even when Photon module is disabled:

https://github.com/Automattic/jetpack/blob/e07addf220d02226f04d874b1b565ceb9f502839/modules/tiled-gallery/tiled-gallery/tiled-gallery-item.php#L35

Ultimately, when Photon-Calypso project lands, it will be possible to build on top of it and add support for the images loaded through the site itself (adding media proxy endpoint to wpcomsh in order to use authenticated Photon requests). We're not there yet though.

For now, the solution would involve a short PR to Automattic/wpcomsh. Specifically, plugging into one of the filters in [jetpack_photon_url](https://github.com/Automattic/jetpack/blob/ff76ea196ce6f0fa869ec7bc87c892254e49d374/functions.photon.php#L53) function and completely disabling photon for the Gallery. We could even backfill the thumbnail URLs with the closest core thumbnail (Automattic/wpcomsh/blob/master/private-site/private-site.php#L317) (or even create one just for the gallery).

**Comment by andrewserong** [comment]
I made a start looking into this today on a test Atomic site. I haven't been able to successfully skip the `jetpack_photon_url` call so far (I'm trying variants of the following:)

```
function force_skip_jetpack_photon_url( $skip, $image_url ) {
	return true;
}
add_filter( 'jetpack_photon_skip_for_url', '\Private_Site\force_skip_jetpack_photon_url', 10, 2 );
```

I'll do more digging tomorrow, not sure if it's that I need to use a different priority, but from a first glance, it does look like the rendered HTML ends up getting saved to the post content with the Photon URL as the source (if I'm not mistaken), so I'm not sure what the implications are for tiled galleries created while Private, and then a user switches their site to Public. Would they need to update the block for Photon urls to start working? 🤔I'll do more digging tomorrow!

**Comment by adamziel** [comment]
Interesting! If the photon URL gets saved it gets more complicated. I know Photon also does some content filtering to replace the regular URLs with photon URLs on the flight here:

https://github.com/Automattic/jetpack/blob/d38a6554c8eb22b3284f5e8c750118ea5e201379/class.photon.php#L231

Maybe we should perform a reverse operation here? So filter the content to replace all the photon URLs with regular ones?

**Comment by simison** [comment]
Correct, Photon cannot be skipped for Tiled gallery (the block nor the legacy shortcode version). It requires Photon for cropping and resizing images on the fly the way that self-hosted WP cannot really do.

**Comment by simison** [comment]
> Maybe we should perform a reverse operation here? So filter the content to replace all the photon URLs with regular ones?

@adamziel do you mean that we'd replace Photonized URL with the original media-library URL? The original file in media-library would be wrong size, compared to the one the block needs.

**Comment by adamziel** [comment]
@simison The ultimate fix would involve implementing the same media proxy we have in public-api. With that in place, the browser would request the media proxy endpoint instead of `i[0-9].wp.com`, and the media proxy would request photon with authentication token. One pre-requisite for that is photon support for authenticated requests. It is in progress but not there yet, we also don't have a clear estimate for merging the patch - see the discussion here: pMz3w-b58-p2

As a workaround, I'm proposing using an approximately similar thumbnail generated by core WP. The specific size would differ, but the gallery would keep working and with some luck would not look terrible. An even better workaround would be using local WP to create a set of gallery-specific thumbnails and using them instead of going through photon.

**Comment by andrewserong** [comment]
I did some more digging today, but unfortunately it looks pretty tricky to handle this in `wpcomsh` to me. I was confused at first, because I was looking at the legacy Tiled Gallery in the Jetpack plugin instead of the Tiled Gallery block. The block appears to [generate the Photonized img src via JavaScript](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/tiled-gallery/layout/index.js#L48) (which would explain why the filters weren't working). So even if we could update the post content after the fact to point to the media library URLs, we still wouldn't have the images working within the editor.

Unfortunately I can't think of a clean way to do the workaround from the `wpcomsh` end of things, and I'm not quite sure what the best approach would be to change how the block behaves in Jetpack. Any ideas for how we could handle this in Jetpack, or does this veer too far from our ideal behaviour of authenticated Photon requests? (Happy to keep exploring in and around the other tasks this fortnight).

**Comment by adamziel** [comment]
@andrewserong this is tricky indeed! 

I don't think we should change what's getting stored. My understanding is that the block wraps regular URLs in photon and they're stored as such. Now, imagine the site is public and the user makes it private. I don't think we should be updating all the stored posts and pages in response to that change - filtering the post content before `echo`-ing sounds much better. The filter would be only enabled when the site is private.

When the media proxy is available/possible, the filter would "wrap" photon URLs in proxy URLs. Until then, it could replace the photon URLs with references to local thumbnails.

Would that work? What do you think?

**Comment by simison** [comment]
>filtering the post content before echo-ing sounds much better. 

Would that include only frontend of the site? If so, that sounds good. If also editor (so basically via the `posts` API), that might be problematic since you need to keep the editor content identical to block's `save()` output, or otherwise the block will invalidate.

>Until then, it could replace the photon URLs with references to local thumbnails.

That would completely break the gallery layout and be kinda pointless fix, since it would just break in other way instead; Photon not only resizes the images, but it also crops them in different shapes than the original file was.

> Ultimately, when Photon-Calypso project lands, it will be possible to build on top of it and add support for the images loaded through the site itself 

How does the timeline look?

**Comment by adamziel** [comment]
> Would that include only frontend of the site? If so, that sounds good. If also editor (so basically via the posts API), that might be problematic since you need to keep the editor content identical to block's save() output, or otherwise the block will invalidate.

That's a very good question - I guess it depends whether or not the editor uses photon-ed thumbnails when editing the page. If it does, then we're in a territory where a Jetpack PR is likely required.

> That would completely break the gallery layout and be kinda pointless fix, since it would just break in other way instead; Photon not only resizes the images, but it also crops them in different shapes than the original file was.

Can we crop locally?

> How does the timeline look?

We agreed on the approach and the code is pretty much there after a few rounds of feedback so it should be good to go? The timeline is unclear though, see the following comment: pMz3w-b58-p2#comment-78076 - also CCing @johnHackworth

**Comment by adamziel** [comment]
Also the logical next step would be evaluating if there are other places in Jetpack where photon is "baked in" even when the module is disabled.

**Comment by simison** [comment]
> I guess it depends whether or not the editor uses photon-ed thumbnails when editing the page.

It does use; the editor side is basically identical with the frontend side.

> Is there an easy way to do it locally?

Not that I know of. Would've definitely gone ahead that way otherwise. Image sizes and shapes are recalculated each time you add, remove, or re-order images.

Simple and VIP sites don't use `i[0-9].wp.com` Photon servers and use `.files.wordpress.com` files instead, which seems to be an instance of Photon as well. I wonder if Atomic sites could also use those and if implementing privacy for those URLs is easier?

https://github.com/Automattic/jetpack/blob/a9c70935380fdcb7deee882c608083f52d865b9d/extensions/blocks/tiled-gallery/utils/index.js#L121

https://github.com/Automattic/jetpack/blob/a9c70935380fdcb7deee882c608083f52d865b9d/extensions/blocks/tiled-gallery/utils/index.js#L53-L54

**Comment by simison** [comment]
>Also the logical next step would be evaluating if there are other places in Jetpack where photon is "baked in" even when the module is disabled.

@jeherve @kraftbj would know if someone. :-)

**Comment by kraftbj** [comment]
Tiled Galleries and Related Posts (for the thumbnail) are the spots off the top of my head.

**Comment by jeherve** [comment]
The Top Posts Widget and the Display Posts widgets also rely on Photon, and we use Photon URLs when using Content Options in some a8c themes to display images on archive pages.

**Comment by andrewserong** [comment]
Apologies, I didn't get much further with this one during my maintenance rotation. I'm unassigning myself now, but it's still in our maintenance backlog for anyone to pick up.

**Comment by sirreal** [comment]
This seems to be blocked on some photon-side work in pMz3w-b58-p2 that @adamziel is working on with other teams.

Is that accurate?

**Comment by adamziel** [comment]
I handed off that work to @johnHackworth and the create focus, although it's mostly done - it's just waiting for deployment (or final-ish feedback).

**Comment by ockham** [comment]
This is still blocked, see pMz3w-b58-p2#comment-79064.

**Comment by chaitanyamsv** [comment]
Ran into this issue with "Coming Soon" mode while trying to add a Tiled Gallery block. The editor wouldn't show the gallery images.

21566134-hc

**Comment by tanjoymor** [comment]
Had another customer run into this 21748691-hc

**Comment by rinazrina** [comment]
Another report: 21734563-hc

**Comment by chaitanyamsv** [comment]
20128576-hc

**Comment by chaitanyamsv** [comment]
#21839948-hc

**Comment by rachelwinspear** [comment]
Found issue in Quick Start session: #3067207-zen

**Comment by jamiepalatnik** [comment]
Reported in #22183595-hc

**Comment by jackiejade** [comment]
Reported in #21436641-hc

**Comment by iamAfsana** [comment]
Ran into this same issue with "Coming Soon" mode while trying to add a Tiled Gallery block. The editor wouldn't show the gallery images. #3160629-zen

**Comment by chaitanyamsv** [comment]
22854706-hc

**Comment by joweber123** [comment]
Reported in 23043625-hc

**Comment by scosgro** [comment]
Another WordPress.com user report in 23740415-hc

**Comment by jartes** [comment]
Reported in a private AT site 3294794-zd

**Comment by ash1eygrace** [comment]
Another report pushed tp zd-3291416 - Had them install a Coming Soon plugin as a workaround.

**Comment by sdixon194** [comment]
Another case in 24155539-hc

**Comment by sourourn** [comment]
Another report: #24185808-hc

**Comment by sdixon194** [comment]
Another case 24234017-hc

**Comment by jartes** [comment]
Another case 24325736-hc

**Comment by adamziel** [comment]
@ramonjd I tagged you in so that you're notified about new comments here

**Comment by lakellie** [comment]
Another report 3424301-zen

**Comment by ramonjd** [comment]
I've left another note over at pMz3w-b58-p2#comment-83240

**Comment by susanjanec** [comment]
Another case - 25322363-hc - provided workaround to set site to Public, and add SeedProd coming soon plugin.

**Comment by nerdysandy** [comment]
Reported on  #25672569-hc

**Comment by geekinthegirl** [comment]
Another potential case here: 24865600-hc - I asked them to launch their site to test this, and they went quiet, but dropping it here just in case.

**Comment by katiebethbrown** [comment]
Another report - 27686765-hc

Suggested using Coming Soon mode instead.

**Comment by Agepeuve** [comment]
Reported in 27779051-HC

**Comment by Addison-Stavlo** [comment]
Lowered priority due to smaller % of users experiencing this issue after Coming Soon v2 changes.  Fix continued to be stalled pMz3w-b58-p2#comment-83240

**Comment by rinazrina** [comment]
Another one: #3749605-zen

**Comment by tanjoymor** [comment]
This same issue occurred on a site using the Classic Editor with a gallery: #27874150-hc

**Comment by happychait** [comment]
24413916-hc

**Comment by kwight** [comment]
@adamzelinski I'm not sure if I'm missing something here – I can't seem to replicate (new site, transfer to Atomic, add tiled gallery with new images):

<img width="1551" alt="Screen Shot 2021-03-09 at 1 48 39 PM" src="https://user-images.githubusercontent.com/349751/110543270-f5363e80-80de-11eb-8f39-a79ba1eda867.png">

"Coming soon" is the same as "private" now, is that correct?..

**Comment by ramonjd** [comment]
> "Coming soon" is the same as "private" now, is that correct?..

👋 Coming soon used to be equivalent to private mode beneath the chassis. 

Last year we switched Coming soon "mode" to public not-indexed. So the resources are still public, but the pages/posts are "hidden" behind a Coming Soon site.

So I think it's strictly related to a site that's been explicitly set to private in the settings.

**Comment by ghost** [comment]
> @adamzelinski I'm not sure if I'm missing something here – I can't seem to replicate (new site, transfer to Atomic, add tiled gallery with new images):

I think you've tagged the wrong adam here sorry @kwight @adamziel

**Comment by simison** [comment]
Could private-media-proxy be part of the solution here? https://github.com/Automattic/wp-calypso/issues/25115#issuecomment-792660145

Either by letting Photon retrieve images via that, or receiving resized images directly via that endpoint?

**Comment by adamziel** [comment]
The endpoint requires public-api cookies that may not be there when the user simply visits the site. An alternative would be to have a similar endpoint available on the atomic site itself and then replace all the photon URLs with the site's API endpoint URLs using a filter.

**Comment by adamziel** [comment]
The endpoint requires public-api cookies that may not be there when the user simply visits the site. An alternative would be to have a similar endpoint available on the atomic site itself and then replace all the photon URLs with the site's API endpoint URLs.

**Comment by kwight** [comment]
> The endpoint requires public-api cookies that may not be there when the user simply visits the site.

If the user is logged in, those cookies would be there, wouldn't they? And a user needs to be logged in to view a private site?

I'm going to attempt to summarize discussions and where we're at so far (please do correct anything that's off).

* Users with private atomic sites cannot see images they've added to tiled galleries.
* These images are not rendered because they are Photon image URLs which, when loaded directly, return a 403. Attempting to load directly means no authentication is provided that could allow the browser past the private setting.
* Tiled galleries rely on Photon because the gallery needs to dynamically resize and crop images.
* We have an endpoint `https://public-api.wordpress.com/wpcom/v2/sites/:site/atomic-auth-proxy/file?path=:path` that returns image blobs; being a dotcom API endpoint, we can handle authentication and fetch the image this way, regardless of a site being private or not.
* This issue could be solved by having the tiled gallery block render its images based on the results of this endpoint – either by having Photon use the endpoint, or by using the endpoint directly and adding the necessary cropping and resizing support.

One question though: why can I add a Photon URL to a basic image block (via "Insert from URL") and have none of these problems? I can see the image in the editor (although it does present a CORS error), and on the front-end. This is with me logged in to the Atomic site and the site set as private.

**Comment by kwight** [comment]
@adamziel @jblz I'm trying to set up a dev environment for this, but I'm a little confused by how I can activate private mode on a JP+wpcomsh or ephemeral site (both seem to not offer the option in WP.com settings):

<img width="1353" alt="Screen Shot 2021-03-12 at 2 40 25 PM" src="https://user-images.githubusercontent.com/349751/111006067-ebac1100-8340-11eb-9e80-0d287d190bf2.png">

I thought I could get away with defining `IS_ATOMIC` and `AT_PRIVACY_MODEL` on JP+wpcomsh, but no dice –  any tips?

**Comment by adamziel** [comment]
> I'm trying to set up a dev environment for this, but I'm a little confused by how I can activate private mode on a JP+wpcomsh or ephemeral site (both seem to not offer the option in WP.com settings):

@kwight AFAIR that's only possible on "real" atomic sites hosted on the atomic platform as they are a bit different from ephemeral sites or JP+wpcomsh sites (e.g. `AT_PRIVACY_MODEL` does not work outside of atomic). Unfortunately they are quite painful to setup.

I used to create a new e-commerce site and upload my own wpcomsh and jetpack via scp. Then, I made WP use my copies instead of the ones shipped by default. I think it involved disabling the default jetpack and changing `WPMU_PLUGIN_DIR`. I don't think this process is documented in the FG so that's an opportunity to update the docs.

> If the user is logged in, those cookies would be there, wouldn't they? And a user needs to be logged in to view a private site?

AFAIR the following situations are possible:

* As a site owner, you may be logged to the site but not to calypso.
* You may have a visitor or an editor account on the site.

In both cases you would have some auth cookies @  `mysite.com`, but not @ `public-api.wordpress.com`.

One idea we considered was a pipeline like Jetpack/wpcomsh endpoint, which would talk to public-api using Jetpack auth token. The public-api would then send an authenticated photon request, which would allow photon to fetch the image. This is quite entangled but it would do the trick. Unfortunately it didn't get the required support here: wp-pMz3w-b58

Another idea would be adding a Jetpack/wpcomsh endpoint which would do all the resizing/cropping locally. I think this is a pretty good solution, but it comes with three challenges. 1. It would have to support the exact photon syntax, 2. It would require imagemagick/similar image processing extension, 3. it could result in a lot of "out of memory" errors when processing larger images. I am also not sure about the CPU consumption – loading of the entire gallery for the first time (or changing e.g. thumbs size) could be costly and slow down the entire site.

> I'm going to attempt to summarize discussions and where we're at so far (please do correct anything that's off).

It is a pretty good summary! I only have one note:

> This issue could be solved by having the tiled gallery block render its images based on the results of this endpoint – either by having Photon use the endpoint, or by using the endpoint directly and adding the necessary cropping and resizing support.

To use that endpoint, photon would have to authenticate the user. Unfortunately, we don't send any cookies to photon domains by design. We could work around that by sending an authenticated request from public-api, but photon doesn't know how to handle authentication and it's unlikely to know in the future (see wp-pMz3w-b58).

> One question though: why can I add a Photon URL to a basic image block (via "Insert from URL") and have none of these problems? I can see the image in the editor (although it does present a CORS error), and on the front-end. This is with me logged in to the Atomic site and the site set as private.

Good question! My memory is hazy on this one but I'll try to answer. One possible scenario is that you have visited that URL before making the site private – if so, the image is likely still cached by photon. Another possible scenario is that there is a filter in place that "unphotons" these URLs if there are no resize or crop params in place (although I am not sure if that's true). Finally, you may be testing on an emphemeral site, not an atomic site – file privacy does not work on these (see the first paragraph of this answer). If neither of these is true, I am baffled – it is definitely worth digging into.

**Comment by kwight** [comment]
> AFAIR that's only possible on "real" atomic sites hosted on the atomic platform as they are a bit different from ephemeral sites or JP+wpcomsh sites (e.g. AT_PRIVACY_MODEL does not work outside of atomic). Unfortunately they are quite painful to setup.

That explains why I wasn't finding other references to `AT_PRIVACY_MODEL`. 🙃

> Another idea would be adding a Jetpack/wpcomsh endpoint which would do all the resizing/cropping locally.

Urgh, sticky. Since we control the hardware for Atomic sites, I wouldn't expect to have any unsurmountable issues for CPU/memory consumption, nor ImageMagick unavailable (it seems we have a `gmagick` module installed, that's comparable?). However, it feels like a lot of work to create duplicate code and more variation between how Simple and Atomic sites work.

> photon doesn't know how to handle authentication and it's unlikely to know in the future (see wp-pMz3w-b58)

Ah, this was a detail that got past me, I see what you mean now.

So we need Photon to do the resizing and cropping, but we can't use Photon because it will never handle authentication needed to bypass the Private site setting. We could duplicate Photon functionality and workload on the local site using the result of the private media endpoint, but that seems... less than great too. I have no good suggestions. 🤔

**Comment by kwight** [comment]
After some discussion with @mreishus , we're going to try another approach:

* add a new "[Photon implementation](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/utils/index.js#L53)" (not using Photon) that would fetch the images from the Atomic media proxy endpoint (it seemed as good a place to start as any in the block), and
* have the endpoint code load the Photon library locally to do the resize and crop operations.

If all goes well, we'll be able to serve the gallery images to the editor as hoped for (and to the front-end for those that are logged in to Calypso – I think). If we can get the media proxy endpoint working, that should at least allow us to load the images (albeit at full size) – I'm not sure what this will look like (but maybe we'll move this issue one small step forward).

**Comment by adamziel** [comment]
I like that idea, good thinking! If it works, you could complicate the data flow a little bit to make it work even for users who are not logged in to calypso. Basically instead of sending the request directly to public-api, you would go through a site-specific Jetpack/wpcomsh endpoint which would send an authenticated public-api request on your behalf using the blog token. The data would bounce back-and-forth between the atomic site and public-api, but it would satisfy all use-cases.

**Comment by mreishus** [comment]
Noting that photon implementations ([link](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/utils/index.js#L53)) is not the right abstraction for adding proxied images. Photon implementations transforms one `src` to a `src` and `srcSet` attribute by modifying query parameters and changing the domain.

But the proposed proxy images solution can't work by only modifying a src, it needs to run custom JS to fetch the image from an endpoint, save the blob fetched in the browser's memory, and display that image instead. ([Mimicking the trick that Calypso Proxied Images use](https://github.com/Automattic/wp-calypso/blob/ef76ff4b6871663ced67b361ae17fac301f5248e/client/my-sites/media-library/proxied-image.tsx#L77-L81)). You might think that even though photon implementations are a src -> src transformation, maybe it could have a side effect of fetching the data from the backend. But they're meant to be pure functions called over and over, for example[ in render functions](https://github.com/Automattic/jetpack/blob/5feaca5b2590f841a4e6408377b6f17df66b3e44/projects/plugins/jetpack/extensions/blocks/image-compare/edit.js#L81). So it's not a good fit.

What we really need is something more on the order of replacing [GalleryImageSave](https://github.com/Automattic/jetpack/blob/5feaca5b2590f841a4e6408377b6f17df66b3e44/projects/plugins/jetpack/extensions/blocks/tiled-gallery/gallery-image/save.js#L7) and [GalleryImageEdit](https://github.com/Automattic/jetpack/blob/5feaca5b2590f841a4e6408377b6f17df66b3e44/projects/plugins/jetpack/extensions/blocks/tiled-gallery/gallery-image/edit.js#L17) with proxied versions, or teaching them how to optionally load proxied images, or wrapping them with a ProxyImage HOC.

In the mean time, I'm not quite there yet. Before implementing proxied images, I need to figure out how to tell Jetpack if we're on an atomic site to forgo photizing urls at all if we're on a private+atomic site. If proxying images is a step 1, then simply skipping the photonizing at all is a step 0.5 which leads to an improved user experience.

I'm also wondering if there is an alternative to proxied images. `files.wordpress.com` already handles both authorization and resizing for simple site images. Is there not a way we can bring that to the WordPress on Atomic platform? 
* `files.wordpress.com` handling resizing - https://testsitemmrtag.files.wordpress.com/2021/03/drone-4.jpg?resize=400%2C400
* `files.wordpress.com` handling authorization - https://testsite5mmr.files.wordpress.com/2021/03/drone-1.jpg?resize=150%2C150 (403 inside private window, returns image when logged in as me or superadmin)
It's able to provide both of those features while allowing the simplicity of a `<img src="...">` image tag to work, which seems ideal. I'm still not sure why this can't be brought to atomic.

**Comment by mreishus** [comment]
Figured out the 0.5 step here: https://github.com/Automattic/jetpack/pull/19201 (I think, I'm pretty inexperienced with JetPack, so I'm not 100% on the technique of communicating private + atomic status to the JavaScript portion)

**Comment by mreishus** [comment]
I have a WIP of the proxied images approach here (https://github.com/Automattic/jetpack/pull/19212), but it doesn't work. I'm not sure how to do an authenticated request to the public-api from a jetpack block. Will probably need some eyes on it if we continue to go down this route.

To summarize:
* Approach Step 0.5: https://github.com/Automattic/jetpack/pull/19201 - Removes the photonize entirely for atomic+private. Will load full size images and use CSS to resize, which uses extra bandwidth. Cropping is not supported but I don't see it turn on when I mess with my own tiled galleries. The CSS may be powerful enough to leave the galleries looking the same even without the photon features. This does work but probably needs review and improvement because I'm likely breaking some jetpack conventions.
* Approach Step 1: https://github.com/Automattic/jetpack/pull/19212 - WIP. Tries to use the proxy image method to use public-api to fetch images, grab the blobs, and display the data to the user. Doesn't function, needs lots of work and improvement. Notably, I'm not sure how to make an authenticated request to public-api from a jetpack block.

**Comment by adamziel** [comment]
> Photon implementations transforms one src to a src and srcSet attribute by modifying query parameters and changing the domain.

That's a really good spot 🙌 

>  I need to figure out how to tell Jetpack if we're on an atomic site to forgo photizing urls at all if we're on a private+atomic site. 

@mreishus  `is_defined('AT_PRIVACY_MODEL') && AT_PRIVACY_MODEL == 'wp_uploads'` should do the trick. It is a bit of an abstraction leak, if you want to keep things tidy you could make it a filter and handle it in wpcomsh. We even have a function for that called `Private_Site\site_is_private()`. See the "Coming Soon, Private, and Un-launched Sites" FG page for more details.

> I'm also wondering if there is an alternative to proxied images. files.wordpress.com already handles both authorization and resizing for simple site images. Is there not a way we can bring that to the WordPress on Atomic platform?

That would be ideal from the development standpoint, a nice clean cut solution. The culprit is that while we could probably authenticate wp.com/calypso users that way, there are also users that exist only on the atomic site and don't have any cookies set @ other wp.com domains (and I don't think they should, but speak up if you disagree).

**Comment by adamziel** [comment]
> Notably, I'm not sure how to make an authenticated request to public-api from a jetpack block.

That bit is tricky to figure out on one's own. My one regret is I did not reach out earlier to @jeherve, @kraftbj, and others. Also cc @roo2

**Comment by adamziel** [comment]
@mreishus this Jetpack PR could help you get started with the authenticated request part:

https://github.com/Automattic/jetpack/pull/14984

Note the conversation surfaces some concerns about using the blog token. The gist of it is that you will need to tell the public-api proxy endpoint to accept blog tokens (they are not accepted for private sites by default). This requires a smallish backend diff, @ramonjd and @p-jackson would know the details.

**Comment by simison** [comment]
@Automattic/view-engineering might be the best folks to support you here @mreishus, since they work in Jetpack blocks and specifically, quite a bit on Gallery blocks recently.

**Comment by mreishus** [comment]
> > Photon implementations transforms one src to a src and srcSet attribute by modifying query parameters and changing the domain.
> 
> That's a really good spot :raised_hands:

Assuming we're talking about adding custom XHRs to fetch images, adding them to photon implementations doesn't feel right to me. `photonizedImgProps` is currently a pure function called in [render()](https://github.com/Automattic/jetpack/blob/952872321fbcdc3172a1a0e6f13bd14ebab98e32/projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/index.js#L48) and [onChange()](https://github.com/Automattic/jetpack/blob/952872321fbcdc3172a1a0e6f13bd14ebab98e32/projects/plugins/jetpack/extensions/blocks/image-compare/edit.js#L81). I assume we're talking about: 
* Giving this function the ability to fire off XHR requests
* giving it the internal state to track those requests and their result values
*  making it return an src of something like "blob:http://mysite.com/abcd1234-abcd-abcd-abcd-abcd1234abcd" (a url generated from `URL.createObjectURL()`)

Why it doesn't feel right to me:
* React render() functions should be pure functions based only on props and state, which this would violate. We would be adding internal state to a previously pure function, and that state wouldn't be stored in a component's local state.
  * Components that depend on the src returned from photonizedImgProps wouldn't know to rerender once the src is set.
* What would it return as src when the image is still fetching?

I'm not seeing how it's a good fit, can you let me know what you were imagining? My first draft approach is not modifying photonizedImgProps, or adding a new photon implementation. Rather, it's adding a higher ordered component [withProxy](https://github.com/Automattic/jetpack/pull/19212/files), which is modeled after the [calypso proxied image component](https://github.com/Automattic/wp-calypso/blob/ef76ff4b6871663ced67b361ae17fac301f5248e/client/my-sites/media-library/proxied-image.tsx#L77-L81).

> @mreishus this Jetpack PR could help you get started with the authenticated request part:

> https://github.com/Automattic/jetpack/pull/14984

I'm looking for a way to make authenticated requests in JS blocks, not in PHP (which as far as I can tell, hasn't been done before and has me wondering if it's an appropriate approach).

**Comment by adamziel** [comment]
> I'm not seeing how it's a good fit, can you let me know what you were imagining?

Actually I was thinking about using WP filters to reason about the rendered block without even touching the React part. But I don't think that would fix the problem in `/wp-admin` so good call choosing the React route. I think `withProxy` is a good way to approach this problem.

> I'm looking for a way to make authenticated requests in JS blocks, not in PHP

I am not aware of any, you may have no other way than going through PHP. As in block -> API endpoint on the atomic site -> public-api endpoint. I am not up to date with the codebase though, Jetpack folks will know better.

**Comment by kwight** [comment]
@apeatling have you or your team had any experience/gotchas recently with making [authenticated API calls from gallery blocks](https://github.com/Automattic/wp-calypso/issues/41272#issuecomment-801881305) in Jetpack?

**Comment by apeatling** [comment]
Personally I haven't, but asking the rest of the team in Slack. We've worked mostly on the core Gallery block.

**Comment by adamziel** [comment]
> Actually I was thinking about using WP filters to reason about the rendered block without even touching the React part. But I don't think that would fix the problem in /wp-admin so good call choosing the React route. I think withProxy is a good way to approach this problem.

Noodling on this some more, I think there were some other cases where images became photonized, including some where the actual post contained fragments like `src="{photon url}"`. Updating the Jetpack Gallery Block should be enough to solve this specific issue, but WP filters may be necessary to address any and all instances of the private site+photon problem cc @mreishus

**Comment by mreishus** [comment]
In https://github.com/Automattic/jetpack/pull/19212, I am trying to use "Jetpack block <--> Jetpack Endpoint <--> WPCOM Endpoint" relaying, but I'm running into authentication troubles. This is getting to be pretty complex.

My other idea was handling the authentication and resizing of images on the backend (see p2 comment: pMz3w-b58-p2#comment-86884). If files.wordpress.com can return 403s or 200s for private images depending on who is looking at them, could it do the same for atomic files? Or could we make an atomicfiles.word press.com? I don't really know enough about the backend infrastructure to answer this.  (files.wordpress.com can also do some basic resizing without needing photon.)

**Comment by adamziel** [comment]
> files.wordpress.com can also do some basic resizing without needing photon

Actually I think it's photon that handles the resizing on that domain. I am not sure how authentication is handled, but I would guess it happens on some earlier layer.

> If files.wordpress.com can return 403s or 200s for private images depending on who is looking at them, could it do the same for atomic files?

The problem is that I may be logged in as a user on myatomicsite.com, but not be logged in on wordpress.com 

>  I am trying to use "Jetpack block <--> Jetpack Endpoint <--> WPCOM Endpoint" relaying, but I'm running into authentication troubles. This is getting to be pretty complex.

It is a bit of a rabbit hole, yes. I wonder if you'll need to update the atomic proxy endpoint to accept requests from Jetpack 🤔 .

**Comment by adamziel** [comment]
> I am trying to use "Jetpack block <--> Jetpack Endpoint <--> WPCOM Endpoint" relaying, but I'm running into authentication troubles. This is getting to be pretty complex.

If, for any reason, this doesn't work in the end, there is always the route of creating a custom xmlrpc method that would do the same thing as the endpoint.

**Comment by mreishus** [comment]
I'm moving off this issue for now.

## Fixes implemented

**Tiled-gallery blocks on private atomic sites will no longer use the photon proxy to resize images.** 
  * ( https://github.com/Automattic/jetpack/pull/19201 ). 
  * This will be released with the Jetpack update on April 6, 2021.
  * PRO: Users will be able to see the images when they couldn't before.
  * CON: Users will download full sized copies of the images when viewing the gallery, potentially leading to worse performance and more bandwidth usage (vs. resized images).

## Avenues Explored but not completed

* Using the wpcom `atomic-auth-proxy` endpoint to download the image data, store in the browser using `URL.createObjectUrl()`, and display using the url generated.  Calypso [uses this technique](https://github.com/Automattic/wp-calypso/blob/547d01112f0f274cc44f2a693b59c3e4aabebc19/client/my-sites/media-library/proxied-image.tsx#L74-L82) to display images in private atomic sites in the media section.
  * Unfinished code is in https://github.com/Automattic/jetpack/pull/19212.
  * The jetpack block JS calls a new jetpack endpoint, which calls wpcom public-api. I was not able to get the call from the jetpack endpoint to wpcom public-api to be authorized correctly: public-api always thought the current user was "0".
  * @adamziel suggested using a custom xmlprc method instead.

## Other possible ideas

* Creating a CDN for atomic sites that handles authentication + authorization and can also resize images
  * More of a moonshot. Not sure about the details.
  * myatomicsite.com users are not necessarily logged into wordpress.com
  * Could each atomic site get its own files.myatomicsite.com?

### For A8Cs
See paYKcK-XD-p2 .

**Comment by adamziel** [comment]
> public-api always thought the current user was "0".

This sounds like authenticating using the blog token, I guess the endpoint would have to be adjusted to respect that.

**Comment by kwight** [comment]
I'm closing this as the main issue (the rendering) has been addressed, albeit lacking optimization – followup can be done with https://github.com/Automattic/jetpack/issues/19445.
