### ISSUE TITLE
Plans top-bar component

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41287]
We are adding a component on the top bar of the editor during the NUX experience to show which plan the user has selected and allow them to upgrade to a new one

**Comment by dubielzyk** [comment]
Here's a preview of the work in progress. Check out the Figma file for the latest iteration.
![image](https://user-images.githubusercontent.com/2896062/79849288-8ebf0980-83c2-11ea-8e4b-9d8a897be655.png)

**Comment by razvanpapadopol** [comment]
Should we already add it there as a static label and make it a button once [plans grid](https://github.com/Automattic/wp-calypso/pull/41284) land in Gutenboarding?

**Comment by dubielzyk** [comment]
I doubt it'll change much, so if you wanna go ahead and implement it, go for it 😄

**Comment by simison** [comment]
I'll close original issue (https://github.com/Automattic/wp-calypso/issues/40838) and leave this one up as more fresh.

@sirreal had a question tho: should we always show "personal" when the user chooses a paid domain?

Should we show a "free plan" badge when no domain is selected?

>during the NUX experience to show which plan the user has selected and allow them to upgrade to a new one

Are there any places after the plans grid where we should keep showing the same badge? In these initial onboarding steps, they haven't yet seen the grid so no plan is selected.

**Comment by sirreal** [comment]
Does the plans button replace the language picker after the _intent gather_ step? It appears to be in the same location.

**Comment by dubielzyk** [comment]
- The plans button should only appear from the Design step onwards (omitted from login too)
- The default plan should be _Free_ until they choose a paid domain, that's when we change it to _Personal_ and display the Plans page after login.

**Comment by dubielzyk** [comment]
Button is ready for implementation :) There's some more details under "Header details" in the Figma file.
![image](https://user-images.githubusercontent.com/2896062/80206837-5bcc7e00-862d-11ea-8628-186d20967545.png)
