### ISSUE TITLE
Page navigation in the block editor

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41298]
Let's add a dropdown to the block editor, when you are editing a page, that lets you navigate to one of the existing pages in your site or create a new one.

Previous attempt:
https://github.com/Automattic/wp-calypso/pull/39826

![image](https://user-images.githubusercontent.com/1554855/79782703-cb95ec80-833f-11ea-8b0d-9d7030c81eff.png)

![image](https://user-images.githubusercontent.com/1554855/79782718-d0f33700-833f-11ea-8e70-8c83ae35b5c7.png)

![Páginas ‹ Press any key to start — WordPress com](https://user-images.githubusercontent.com/1554855/79783063-5a0a6e00-8340-11ea-8e08-95063b1f3eff.gif)

**Comment by p-jackson** [comment]
Given that #41294 is almost done, does it still make sense that this isone of the "very nice to haves" for the soft launch? pbAok1-BW-p2

Given that there won't be any other starter pages they won't need to edit them before launching (just thinking of keeping the project scope to onboarding and activation only)

**Comment by ramonjd** [comment]
> Given that #41294 is almost done, does it still make sense that this isone of the "very nice to haves" for the soft launch? pbAok1-BW-p2

Good point. 

Unless this is a general wish list for the WordPress.com editor, in which case I think it could still be punted upfield, metaphorically speaking.

**Comment by ramonjd** [comment]
This could also get wily if we list hierarchical pages, and there are dozens of them.

**Comment by johnHackworth** [comment]
This is intended to be a help for new users... It would be more than ok to
list  just 4-5 pages and then, maybe, have a search box.  If you have
hierarchical pages in your site you don't need help navigating around
anymore :D

**Comment by ramonjd** [comment]
I've been looking at this task today, and various ways we might achieve what we want. 

I've come up with three possibilities. There may be more :)

### The first is to carry on with #39826

From a data perspective, this would be the most convenient. The Calypso store has most of the data we need already, and we can reuse any Calypso lib/component.

The downside is that it's not really part of the editor, and so we'll need to juggle the element's position hoping that it won't interrupt use of the tool bar.

![Apr-27-2020 14-12-56](https://user-images.githubusercontent.com/6458278/80337120-77898b80-889c-11ea-8e72-5cdff98d90ce.gif)

### Create a must-use Gutenberg sidebar plugin

Sitting beside the Jetpack plugin sidebar icon, our `unnamed` plugin allows users to view and add pages from the Gutenberg sidebar. Docs: https://developer.wordpress.org/block-editor/developers/slotfills/plugin-sidebar/

### Extend the block editor in apps/wpcom-block-editor 

I haven't fully tested this, but we might be able to append a `<select />` element filled with page options and other elements.

We can fetch and search pages using the WP rest API (`/wp/v2/pages`), and there's the possibility of passing info such as the current page id through the iframe messenger.

@p-jackson What do you reckon? Do you wanna take a stab at this task and let us know what you think the right direction might be?

**Comment by ramonjd** [comment]
Some discussion kicked off over at on whether we can add this [functionality to a side bar](https://github.com/Automattic/wp-calypso/issues/40065#issuecomment-619231952): pbAok1-Ii-p2

**Comment by ramonjd** [comment]
Given the comments on pbAok1-Ii-p2, I think we should work with design on this one. 

It might be that a sidebar solves more than just the need for a page navigation widget, in which case we would see a better return on development investment.

Whether we can come up with consistent functionality across wp-admin and Calypso is something that we'll need to crack regardless.

**Comment by vindl** [comment]
Just a heads up that I've recently seen some design mockups for page navigation in core FSE that seem to overlap this. It would be cool if we could reuse that instead of duplicating it (provided that we do end up taking that route).

<img width="720" alt="Screenshot 2020-05-19 at 22 48 36" src="https://user-images.githubusercontent.com/1182160/82377214-a1f5e100-9a23-11ea-90fa-a2c6512ff9c6.png">

**Comment by ramonjd** [comment]
> Just a heads up that I've recently seen some design mockups for page navigation in core FSE that seem to overlap this. It would be cool if we could reuse that instead of duplicating it (provided that we do end up taking that route).

Thanks for raising this @vindl 

@p-jackson has made a [healthy start to this already in the FSE plugin](https://github.com/Automattic/wp-calypso/pull/41703). 

We should keep @olaolusoga in the loop on the design front if it's all good to continue with that work. 👍

**Comment by p-jackson** [comment]
Linking a more recent mockup from @shaunandrews in this tracking issue

![recent pages sidebar](https://user-images.githubusercontent.com/191598/81223180-9af6b980-8fb3-11ea-948b-2fe8549afc95.gif)
https://github.com/Automattic/wp-calypso/pull/41703#issuecomment-624862422

**Comment by p-jackson** [comment]
Work so far:

- [x] #41703 
- [x] #42518 
- [ ] #42605 
- [ ] #42606

**Comment by ramonjd** [comment]
> ramonjd unassigned p-jackson, johnHackworth and ramonjd 24 seconds ago

 no one saw anything

**Comment by p-jackson** [comment]
Todo before shipping. I've put them in the order I think is most important before shipping.

- [ ] Make list scrollable and stick buttons to the bottom of the sidebar #43906
- [ ] Get it working on small screens
- [ ] Fix tab navigability
- [ ] Add site name and URL to the top area
- [ ] Remove post slug from the sidebar items
- [ ] Align visual style with core and woo
- [ ] Adjust the back CTA style
- [ ] Add tooltip
- [ ] Add a home icon to the front page item
- [ ] Change the (W) icon to the site icon

**Comment by p-jackson** [comment]
Latest mockup pbAok1-185-p2#comment-2345

![screen-capture-on-2020-07-08-at-14-44-39-1](https://user-images.githubusercontent.com/1500769/87130465-0aa46000-c2e7-11ea-8206-dbf9fade6112.gif)

**Comment by ramonjd** [comment]
Hi @olaolusoga 

Should we be matching @shaunandrews's work in https://github.com/WordPress/gutenberg/issues/23939 for the sidebar before we launch it?

**Comment by olaolusoga** [comment]
Not all of it since there's chatter still going on. I can mock up the small adjustments we should include, and share shortly.

Is the preview in Shaun's GIF possible with what we're doing?

**Comment by p-jackson** [comment]
> Is the preview in Shaun's GIF possible with what we're doing?

Might be possible, but certainly not trivial. We might be able to use the same technique that the fullscreen layout picker uses, but it wouldn't be a short term thing. I worry a about performance there too, if you're already on a very large sluggish page, then loading a preview of another large sluggish page could even crash the browser tab. A skeleton preview might be a way around it i.e. just showing block outlines as boxes and removing the actual images/text from the preview.

**Comment by olaolusoga** [comment]
>Might be possible, but certainly not trivial. 

Makes sense. Let's punt on the previewer for now; core can figure it out, and we'll roll it into FSE on dotcom.

**Comment by p-jackson** [comment]
Issues so far from Call for Testing:

- [x] Add active style to sidebar nav items and home button to ensure text is white while clicked #44418
- [ ] Change editor close button label from "Home" to "My Home" #44445
- [ ] Increase contrast of "View site" link's `:active` state #44446

**Comment by p-jackson** [comment]
Page navigation has now been shipped to 100% users. There are some tasks/issues on the board for small improvements we could make, but the main task is now done.

**Comment by ramonjd** [comment]
> Page navigation has now been shipped to 100% users. There are some tasks/issues on the board for small improvements we could make, but the main task is now done.

![image](https://user-images.githubusercontent.com/6458278/89977027-7a728580-dcad-11ea-827a-041972a343ac.png)
