### ISSUE TITLE
Gutenboarding: Add a notice giving the user some context when they land in the editor 

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41290]
When the user lands in the editor for the first time, the experience may be a little bit disorienting. We need to add a Gutenberg notice with this text (or a variation, ping  @rickybanister  )

"this is the content of your front page. To see how the entire site will look like you can click on 'preview'"

**Comment by joanrho** [comment]
<img width="1405" alt="Screen Shot 2020-04-22 at 3 36 53 PM" src="https://user-images.githubusercontent.com/204742/80036531-24d05e00-84af-11ea-83c2-8de8f1f2ba81.png">

@johnHackworth were you thinking something like this as a one time notice?

**Comment by simison** [comment]
Component for that design: https://github.com/WordPress/gutenberg/blob/b12aab0364ed2d91e3cf914b3a7590de030574bd/packages/components/src/notice/README.md

**Comment by simison** [comment]
@joanrho just FYI, it can also contain an icon if needed. :-)

**Comment by ramonjd** [comment]
The copy that refers to the "top bar" might be confusing. 

We're not showing a preview a button at all before launch ([we're hiding it](https://github.com/Automattic/wp-calypso/blob/master/apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.scss#L4))

<img width="1208" alt="Screen Shot 2020-04-28 at 10 17 54 am" src="https://user-images.githubusercontent.com/6458278/80433213-a6a20a80-8939-11ea-98c6-57f20a52b948.png">

Should we think about putting it back?

**Comment by simison** [comment]
@ramonjd hiding the preview button was accidental, adding it back here: https://github.com/Automattic/wp-calypso/pull/41470

**Comment by ramonjd** [comment]
Some relevant slack convo: p1588009089077100-slack-CPFFQTG69

**Comment by yansern** [comment]
PR for this here: https://github.com/Automattic/wp-calypso/pull/41661

**Comment by simison** [comment]
There's a welcome modal now in editor so I'll close this.
