### ISSUE TITLE
Gutenboarding: Hide advanced Gutenberg UI

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41299]
When the user lands in the block editor for the first time, the amount of stuff happening in the screen may be a little bit too much. Let's hide some of the non-critical UI in this step:

![image](https://user-images.githubusercontent.com/1554855/79784395-74dde200-8342-11ea-893f-8189e7dbff57.png)

**Comment by simison** [comment]
Reminder to mind the mobile and different Gutenberg versions that Atomic customers might be running. :-)
