### ISSUE TITLE
Site preview: Link to customizer

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41295]
When the user clicks on "preview" and we open the preview of the site in a modal, let's add a "edit your header" button in the top bar of the modal that links to the customizer.  

Also, if possible, let's try to make the "close" button of the customizer to return to editing the front page if the user comes from there.

### Implementation

We'll have to modify https://github.com/Automattic/wp-calypso/blob/b25ff2d/client/components/web-preview/toolbar.jsx

The header tab in the Customizer can be opened by linking to

`https://wordpress.com/customize/identity/{siteSlug}`

Like [we do here](https://github.com/Automattic/wp-calypso/blob/b25ff2d/client/my-sites/site-settings/form-general.jsx#L753).

We should probably ask design about their take on where the link should sit and how it should behave responsively.

**Comment by ramonjd** [comment]
Just checking, is this for Gutenboarding-only sites @johnHackworth ?

**Comment by johnHackworth** [comment]
Nope, this is a problem for every user right now. So let's try to help everyone :)

**Comment by ramonjd** [comment]
Another idea would be to add an "Edit menu" item too. I think it's a pain point for our support team. No one really knows how or where to edit their menus. :)

<img width="1115" alt="Screen Shot 2020-04-27 at 10 10 50 am" src="https://user-images.githubusercontent.com/6458278/80323642-059b4d00-8870-11ea-983e-93e2d15bc12a.png">

**Comment by ramonjd** [comment]
I haven't yet tested, but it might be the case that the user cannot use the Customizer if they haven't verified their email address. See: https://github.com/Automattic/wp-calypso/pull/13017

It might be only for menus and not the header though.

Getting the menu Customizer url still takes this into account: https://github.com/Automattic/wp-calypso/blob/b25ff2d/client/state/selectors/get-menus-url.js

**Comment by roo2** [comment]
I like @ramonjd's idea of having a link to editing the menu as well as editing the header, what do you think about that @johnHackworth ?

This is what it might look like with just the link to edit the header:
<img width="1023" alt="Screen Shot 2020-05-01 at 11 06 09 AM" src="https://user-images.githubusercontent.com/22446385/80773077-20d1c980-8b9c-11ea-842f-7b13a1455e77.png">

**Comment by johnHackworth** [comment]
I think having just the header is ok! most of the time that's what the user wants to modify first ... once they are in the customizer for the first time, they probably can reach everything else themselves!

**Comment by joanrho** [comment]
@johnHackworth @ramonjd @simison There's no specific “Edit Header” section in Customizer, however there are sections for Site Identity, Menus, and Widgets. This is what Customizer currently looks like: 

<img width="357" alt="Screen Shot 2020-05-06 at 10 08 40 AM" src="https://user-images.githubusercontent.com/204742/81200697-96b1a880-8f81-11ea-996c-104f6dd2b02b.png">

Given that, I'd suggest adding two separate “Edit Site Identity” and “Edit Menus” buttons to the top of the "Preview" pane that are clearer about what users are able to edit. Here's a mock of that idea where I've moved over the device preview dropdown to the right next to the "View site" button, and placed the Edit buttons on the left to group them better by function:

<img width="1145" alt="Screen Shot 2020-05-06 at 10 11 41 AM" src="https://user-images.githubusercontent.com/204742/81201092-19d2fe80-8f82-11ea-9cf1-1acd7b3da2d3.png">

The "Edit Site Identity" button should take users directly to the Site Identity submenu of Customizer:

<img width="1147" alt="Screen Shot 2020-05-06 at 10 11 55 AM" src="https://user-images.githubusercontent.com/204742/81201256-50107e00-8f82-11ea-8a32-4bfd58f8c8fe.png">

And the "Edit Menus" button should take users directly to the Primary Menu submenu:

<img width="1147" alt="Screen Shot 2020-05-06 at 10 12 06 AM" src="https://user-images.githubusercontent.com/204742/81201279-57d02280-8f82-11ea-9b59-3119566cfc79.png">

Closing out of Customizer should return users back to the Preview pane in the Editor.

**Comment by shaunandrews** [comment]
I think the customizer's default view is actually fairly friendly; The direct-manipulation icons are helpful, and the labels you see by default aren't _too_ bad.

With that in mind, and considering the existing complexity for the preview modal (there's already so much stuff on the screen here), I'd be in favor of a single, more general button. Something like "Edit site design" rather than two buttons.

**Comment by simison** [comment]
> if possible, let's try to make the "close" button of the customizer to return to editing the front page if the user comes from there.

Yep, it's possible. Customizer can take in:
- `url`: the preview page/post
- `return`: where closing customizer should return you to
- `autofocus[section]`: if some customizer section should be pre-opened. It does it with nice animation so the context of what just happened isn't completely lost, and people would have some chances of understanding what happens if they click "back to the previous section" in Customizer.

**Comment by jordesign** [comment]
> I think the customizer's default view is actually fairly friendly; The direct-manipulation icons are helpful, and the labels you see by default aren't too bad.

I'm inclined to agree with this. On arrival at the Custromizer it is *relatively* easy understand and select:

* Site Identity 
* Menus
