### ISSUE TITLE
Acquire Intent: Skip verticals

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41296]
We should allow users to not enter a vertical if they don't want / they don't know yet. We need a "I don't know yet" button here too. 
Also, since we are at it, clicking on "start a new site" should highlight the text input so the user know what they need to do to continue.

**Comment by dubielzyk** [comment]
On it

**Comment by dubielzyk** [comment]
Ola did a mock of this back in the day, so let's implement that.
![image](https://user-images.githubusercontent.com/2896062/80370390-5327b200-8890-11ea-83ae-713c0837c9eb.png)

**Comment by dubielzyk** [comment]
If we can add the underline gradient for when the input field is empty, then that'd be great too.

When a user clicks _I don't know_, then let's leave it empty and continue on. Let's also stop the animation.

**Comment by ramonjd** [comment]
Should we offer a domain? 

Without input, we could maybe auto-select a random `*.wordpress.com` subdomain

**Comment by razvanpapadopol** [comment]
> Without input, we could maybe auto-select a random *.wordpress.com subdomain

The domain picker query is currently depending on the site title so it shouldn't be affected by the vertical being skipped. But this is a valid point and when advancing to design picker step, we should probably show some random domain suggestion in the header (subject for another issue). I remember we discussed this at some point.
cc: @dubielzyk, @simison

**Comment by simison** [comment]
>The domain picker query is currently depending on the site title so it shouldn't be affected by the vertical being skipped.

It's [depending on both](https://github.com/Automattic/wp-calypso/pull/40770); if title is empty, it'll use the vertical. If the vertical is empty... suppose we should just generate something random. 😁

**Comment by dubielzyk** [comment]
I like @simison suggestion :)

**Comment by simison** [comment]
Was thinking this a bit more...

- If we have logged in user, we can use their username as 3rd fallback for domain suggestions. Most of the time we don't have authenticated user, however.
- Can we return a random free domain and other domain suggestions from domains API even if we don't have any search string to give to suggestions API (@ramonjd @daledupreez I think you're most familiar with this stuff)
- Should we fetch _only_ random free domain suggestion and leave the other domain suggestions out in a situation where we don't have anything to feed to suggestions API? @dubielzyk that's maybe a design question.
- Should we still fallback to some generic words like "new site", "my website" etc for domain suggestions?

**Comment by razvanpapadopol** [comment]
>If we have logged in user, we can use their username as 3rd fallback for domain suggestions.

> Should we still fallback to some generic words like "new site", "my website" etc for domain suggestions?

Both are included in https://github.com/Automattic/wp-calypso/pull/41547

**Comment by ramonjd** [comment]
> Can we return a random free domain and other domain suggestions from domains API even if we don't have any search string to give to suggestions API

The `domains/suggestions` endpoint needs a valid `query (string)` parameter to return suggestions. 

When creating a site via the `sites/new` endpoint, it looks like we then use the suggested WordPress subdomain (the `{AVAILABLE_SUBDOMAIN}` in `{AVAILABLE_SUBDOMAIN}.wordpress.com` as the value of `blog_name`. 

`blog_name` is required to create a site. 

So, without any API changes, we'd need to at least come up with some generic input values for `blog_name` to pass to `sites/new`.

If we want to present a suggestion to the user **before** they create a site, then we could use these same generic input values in the `query` parameter of `domains/suggestions`. 

> Should we still fallback to some generic words like "new site", "my website" etc for domain suggestions?

These could work! We probably even have translations for such terms already. E.g., ["new site"](https://translate.wordpress.com/projects/wpcom/-all-translations/230582/)

**Comment by dubielzyk** [comment]
>Should we fetch only random free domain suggestion and leave the other domain suggestions out in a situation where we don't have anything to feed to suggestions API? @dubielzyk that's maybe a design question.

I wonder if we should have a completely empty domain list and ask them to enter a domain in the search field. Something [like this](https://d.pr/i/DPCFRE).

**Comment by razvanpapadopol** [comment]
> > Should we fetch only random free domain suggestion and leave the other domain suggestions out in a situation where we don't have anything to feed to suggestions API? @dubielzyk that's maybe a design question.
> 
> I wonder if we should have a completely empty domain list and ask them to enter a domain in the search field. Something [like this](https://d.pr/i/DPCFRE).

This would be an interesting approach but I'm not sure this would be better for teaching the user about our UI than showing a [real example like this](https://cloudup.com/clC618bx2zd). 
For the empty domain list approach we'll need also a label for the domain picker button. 
I suggest we create a new issue to discuss this further from design and product perspective.

**Comment by dubielzyk** [comment]
Fair enough. I guess we can fill it with suggestions from the randomized string, but it's likely to be completely useless.

**Comment by simison** [comment]
Let's track how often we'd have to resort on some solution; might be users always fill the site name and/or vertical and thus is edge case issue.

Cc @ramonjd just to make sure we're tracking empty states.

**Comment by ramonjd** [comment]
> Cc @ramonjd just to make sure we're tracking empty states.

Looks like we're still sending the property names for site title and vertical with the tracking payload.

https://github.com/Automattic/wp-calypso/pull/41431/files#diff-77e5f87d23bb9ec994b17b589daf16fdR40

They'll be some type of falsey if nothing is there. CC @roo2 to confirm
