### ISSUE TITLE
Gutenboarding: Send the user to Customer Home

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41293]
Once the site is launched, we should send the user to Customer Home instead of the checklist

**Comment by simison** [comment]
Likely fixed in https://github.com/Automattic/wp-calypso/pull/41123

Gotta re-test.

**Comment by sirreal** [comment]
I've just tested and this does appear to be the current behavior.

**Comment by razvanpapadopol** [comment]
There's an update regarding the launch flow so we're sending the user back to where they pressed the Launch button (editor / home). More details in https://github.com/Automattic/wp-calypso/pull/41437
