### ISSUE TITLE
'Sticky' Launch Button in gutenboarding

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41300]
Right now, if a user doesn't launch their site in the same session where they created it, we lost the "launch" button when they are editing their page. We need to tag those users as "gutenboarding" and make sure the context of the block editor is always 'gutenboarding' for them until they launch their site, so they always will get the pre-launch flow even if they launch a month after creating the site

**Comment by razvanpapadopol** [comment]
We are passing a Gutenboarding specific option when [creating a site](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/stores/onboard/actions.ts#L102) so we should probably check where it's being stored and replace the current query string mechanism with a more robust solution, as the TODO [here](https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/calypsoify-iframe.tsx#L298-L301) is also suggesting.

**Comment by ramonjd** [comment]
> We are passing a Gutenboarding specific option when creating a site so we should probably check where it's being stored and replace the current query string mechanism with a more robust solution, as the TODO here is also suggesting.

I did mean to type **site option** honest!! 🤦 :)

Thanks for the tips @razvanpapadopol !

**Comment by razvanpapadopol** [comment]
Just a related note, once we achieve the _stickiness_ described here, we should change the Launch button label to something more meaningful to our flow. https://github.com/Automattic/wp-calypso/pull/41211#issuecomment-616574788

**Comment by ramonjd** [comment]
Think I have something workable up for review

https://github.com/Automattic/wp-calypso/pull/41349

D42191-code

> once we achieve the stickiness described here, we should change the Launch button label to something more meaningful to our flow

@razvanpapadopol I see we've updated the launch button text in https://github.com/Automattic/wp-calypso/pull/41211 Do  we need to throw a Phabricator diff up for that (if there isn't one already)? Cheers!
