### ISSUE TITLE
Editor: Stats/reports for tracking Block, WordPress.com, and Classic editor usage

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#41309]
As part of deprecating the WordPress.com editor, we need to understand current usage of our different editors before and after the deprecation.

## Requirements

Reports for the following (add any stats/tracking needed to generate these reports)

1. Comparison of the number of users who use currently use the WordPress.com editor vs the Block editor
1. A way to compare the number of users who use the Classic editor vs the Block editor that we can continue tracking, after the editor deprecation

## Notes

#41108 will update the "Switch to Classic Editor" link. Once that's in place, we should be able to see the percentage of users who use the Block vs the Classic editor, and compare to WordPress.com vs Block editor from before the deprecation.

cc @davemart-in

**Comment by creativecoder** [comment]
Notes from @Automattic/explorers team discussion: it will be more relevant to get percentage of users who opt out of Block editor and into Classic the editor. I've updated the issue description to match this.

**Comment by glendaviesnz** [comment]
It looks like the existing track stats for post publishing, listed at b5gDS-p2, should give us the information we need both before and after deprecation in terms of editor usage, as long as the post/page containing blocks is an accurate enough indicator of this.

**Comment by glendaviesnz** [comment]
@creativecoder  I don't think we need to do anything else at this stage - check my logic on it and close if not.

**Comment by creativecoder** [comment]
I've updated pb5gDS-ur-p2, confirming that we have the data we need and a way to query it going forward. I'll close this.
