### ISSUE TITLE
Gutenboarding: Login link not tabbable

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41306]
In the signup screen, you can't get to the "login" link by tab your way around the elements of the page

**Comment by p-jackson** [comment]
This is actually a user agent thing.
- If you try in Chrome you can tab text fields, links and buttons
- In Safari it will only tab to text fields by default
  - Open advanced preferences and select "Press tab to highlight each ..." to change this
- In FF it will only tab to text fields and buttons by default
  - Follow these tedious instructions https://stackoverflow.com/a/11713537 to change

It's a Mac thing. I assume they're trying to follow the conventions of the OS, which disables tabbing to all controls by default.

Other keyboard navigation tools (e.g. vimium, screen readers) will make the links navigable in their own way.
