### ISSUE TITLE
Gutenboarding: Site creation/editor load animations

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#41308]
We need to manage to blend the site creation animation and the Gutenberg load one into a single experience, to minimize the perception of waiting by the user. We probably want to use this time to teach the user what's going to happen next, so the shock of landing in the editor is minimized

**Comment by dubielzyk** [comment]
Is it possible to lead the editor while the Gutenboarding _build site_ animation is running?

**Comment by ramonjd** [comment]
🍞
