### ISSUE TITLE
My Home: Educational card images cause awkward mobile sizing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#41314]
As the educational cards scale across different screen widths, they cause awkward card image sizes, and huge whitespace for the Mastering Gutenberg card. The Mastering Gutenberg image is also not centred, and has a `max-width: 100px` that doesn't translate well at all screen widths. The gif was taken at a width of 1024px.

![2020-04-20 16 17 16](https://user-images.githubusercontent.com/349751/79808411-9202b880-8322-11ea-9e3f-afcad9cd005c.gif)

**Comment by mmtr** [comment]
Closing this one out since we won't be using the dot pager in the new layout.
