### ISSUE TITLE
Jetpack Search: remove Search benefit from plans table

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#41336]
Remove Search benefit from plans table: `Enhanced Site-wide Search`.

![image](https://user-images.githubusercontent.com/390760/79892321-4f141400-83fa-11ea-8c6a-ab08f1363131.png)

Seems to come from:

https://github.com/Automattic/wp-calypso/blob/4537033c6794449ce0a10b69d72daf5fa658d553/client/lib/plans/features-list.js#L924-L936

**Comment by Aurorum** [comment]
PR in #41434 for this issue. :)
