### ISSUE TITLE
Notifications: Comment notifications not showing up as often as they should.

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#41335]
#### Steps to reproduce

1. Starting at URL:https://wordpress.com/read
2. Click the notifications icon

#### What I expected

I expected to see notifications for recent comments made on my site

#### What happened instead

I very rarely see notifications for new comments.

#### Browser / OS version
Chrome 80

#### Screenshot / Video
You can see here that we have a lot of new comments but only one notification and it is for an older comment than the ones shown.

<img width="1382" alt="Screen Shot 2020-04-21 at 10 41 44 AM" src="https://user-images.githubusercontent.com/31110506/79890692-199d0580-83bd-11ea-8d18-a64116d157cb.png">

#### Context / Source

This was found by Calypso e2e tests. The tests started failing around the time that 5.4 was merged in

**Comment by tanjoymor** [comment]
Had a user report this issue today in chat: #20470665-hc

Have documented detailed testing that I've complete on a few sites here: #2903086-zd (I can transfer that testing information to a comment here if desired)

My A8C test comment notification worked, but on two other sites - one AT and one Simple Biz no notifications were received and actually haven't been being received for over a year on the AT site (clearly I don't personally use this function lol).

**Comment by brookewp** [comment]
I ran into another case today and the user said it started for them two days ago. hc-10800140

**Comment by kmrpankaj** [comment]
Similar issue here HC-19715030

**Comment by fstath** [comment]
I have a couple of reports in this forum thread:
https://wordpress.com/forums/topic/all-my-comments-and-replies-are-not-coming-in-the-notification-bell-2/

**Comment by bsessions85** [comment]
This one was resolved on April 23. Closing this now
