### ISSUE TITLE
Premium Themes: rename "Purchased" description to "Included" or similar to avoid confusion with one-time purchases

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#41332]
#### Steps to reproduce

1. On a Premium plan site, go to WP-admin > Appearance > Themes and scroll down. 
2. The premium themes will show "_Purchased_" next to the theme name, even these themes were not purchased.

"_Purchased_"  indicates that the theme is a premium theme, which causes confusion for users.
On the Personal plan site, these premium themes have the prices displayed.

#### Screenshot

On a Premium plan site ("Purchased" is displayed): 

<img width="1477" alt="Screen Shot 2020-04-21 at 10 33 23 AM" src="https://user-images.githubusercontent.com/36863633/79887158-91d5ec00-83fa-11ea-9ebc-91f7ccac9ab5.png">

On a Personal plan site (prices are shown, indicating that these themes can be bought): 

<img width="1507" alt="Screen Shot 2020-04-21 at 10 46 57 AM" src="https://user-images.githubusercontent.com/36863633/79887239-b16d1480-83fa-11ea-8308-b779459a86ec.png">

#### Context / Source

#user-report 2894182-ZD
#manual-testing 

If requesting a new feature, explain why you'd like to see it added: 

The "Purchased" text next to premium themes could confuse users - making them think they bought all those themes even they did not.
Since premium themes are already included in the Premium plan, "Purchased" does not seem to be an ideal description.

Suggestions: 
"Included in your plan" or "Included"

**Comment by lancewillett** [comment]
I like this idea of changing the wording to "Included" or "Available" as it is more accurate.

**Comment by davemart-in** [comment]
Sounds good. I vote that we change it to "Included". 👍

**Comment by frontdevde** [comment]
**Dotcom Manage Janitor rotation note 23 Jun 2020:**
We fixed this issue in D45334-code.
