### ISSUE TITLE
Earth Day banner missing dismiss button for logged in users

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#41353]
As per the announcement post, the Earth Day banner should have a dismiss button for visitors to hide it, but it's missing when the visitors are logged into WordPress.com.

![Annotation on 2020-04-22 at 09-46-50](https://user-images.githubusercontent.com/16645645/79954883-49f8a880-847e-11ea-825e-4bf6add8ca92.png)

It was tested proxied and unproxied.

It's re: https://github.com/Automattic/wp-calypso/pull/41275

**Comment by simison** [comment]
cc @jacklenox @scottsweb

**Comment by scottsweb** [comment]
Looking now!

**Comment by scottsweb** [comment]
Fix has been deployed.
