### ISSUE TITLE
Block editor: link feature missing from Paragraph & Heading toolbar

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#41356]
### Steps to reproduce

1. Create a new page or post
2. Add a Paragraph or Heading block
3. Notice the link icon is missing

#### What I expected
The link icon to be there.

#### What happened instead
The link icon is missing on these blocks, and to add a link, one has to copy/paste a link on a highlighted word. It seems it's only affecting Simple sites.

![Screen Shot 2020-04-22 at 09 13 26](https://user-images.githubusercontent.com/16645645/79964854-94345680-848b-11ea-90ca-ddf074494c8b.png)

**Comment by zdenys** [comment]
Reported in 20428528-hc too. The user mentioned that Buttons block also is affected and misses the Link icon.

**Comment by geekinthegirl** [comment]
Also reported in 20479991-hc. The user was trying to add a link to an existing paragraph block, but there was no option to do so/no link icon in the mini menu. Used HTML link as a workaround.

<img width="453" alt="Screenshot 2020-04-22 at 10 16 50" src="https://user-images.githubusercontent.com/22247240/79966596-93002b00-8485-11ea-9678-ec59f8eba112.png">

**Comment by pauljacobson** [comment]
I have several reports of this here:

* 13979035-hc (Buttons Block)
* 14835372-hc (Buttons Block)
* 17077796-hc (Buttons Block)

In the second report, the user also reported the following:

>If I take the block template from the side bar, I can't get rid of it completely. I can dismiss the block but there is a place holder that wo't go.

**Comment by rahul020691** [comment]
2 cases:
17571028-hc
781973-hc [They found how to add it via top toolbar though]

**Comment by alshakero** [comment]
The issue probably comes [from here](https://github.com/Automattic/wp-earn/blob/master/sandbox/src/mu-plugins/premium-content/editor.css#L41-L43). I'm looking into it.

**Comment by alshakero** [comment]
@artpi is working on it.

**Comment by mlaetitia** [comment]
Two new reports:
https://woothemes.zendesk.com/agent/tickets/2904298
https://woothemes.zendesk.com/agent/tickets/2904314

**Comment by mriyazuddin** [comment]
Also reported here: 5255945-hc

**Comment by alshakero** [comment]
This has been fixed by @artpi

**Comment by philnick206** [comment]
Reported here as well: 20482467-hc

**Comment by alshakero** [comment]
For future ref, this was fixed in D42266-code.
