### ISSUE TITLE
FSE Plugin: Add Blog Page Layouts and Deploy All Layouts to Mag 16

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#41364]
We've made some simple blog layouts that are ready to be added to the layout selector.

![screenshot-2020-04-17-at-18 10 49](https://user-images.githubusercontent.com/908665/79993101-48de7000-84ac-11ea-84f6-d87b9202cfab.png)

I've already added these layouts to the master site, and I've also made a static screenshot for each and uploaded to the headstart media site.

I'm looking at the FG page about Starter page templates, but I think I need dev help :)

cc @obenland @ianstewart @johnHackworth

**Comment by obenland** [comment]
> I think I need dev help 

What is it that you need help with?

**Comment by iamtakashi** [comment]
My first question is... 

I can see this in the FG page.

> You should create the screenshot to match the existing format. `alt` text should be authored to be no longer than two sentences and should describe the Layout as clearly as possible within the constraints.

Where is this `alt` text should be added? Through the Headstart media site?

**Comment by obenland** [comment]
That could indeed be clearer. I updated the docs to reflect that they need to be added to the `$template_meta` array in `Starter_Page_Templates::add_starter_page_templates()`, together with the template's category.

**Comment by iamtakashi** [comment]
@obenland, thanks for clarifying the doc! 

I've made a diff for the M1 annotation in `D42287-code`. Can you take a look at it if it looks good?

The next step is to generate the .json annotation file, isn't it?

**Comment by obenland** [comment]
I've not had a chance to test it as I'm getting ready for an FSE update but it _looks_ good!
Yes, updating the annotation files is next

**Comment by iamtakashi** [comment]
I need to head out for today, but this is a question for tomorrow. 

Do I need to run the wpcli command to generate the json file while the addition to `$template_meta` is in my sandbox? (Sorry, if this doesn't make sense or is too obvious to you.)

**Comment by obenland** [comment]
It's not obvious, I had to double-check myself. Yes, they need to be in your sandbox so that information is picked up when the annotation script runs. If you want to make extra-sure, feel free to commit that ahead of time.

**Comment by iamtakashi** [comment]
Thanks for the hand-holding. Much appreciated!

I have updated the diff `D42287-code` with an updated `m1` json file.

The next item on the instruction is to generate a linguine file for translations, is there anything I should do before moving on to it? I have manually checked the new `post_content`s in the json by unescaping it and paste it to new pages, but it'd be nice to be able to test it in the layout selector otherwise I feel I'm kind of doing this blindly.

If you also think it's good to test it before moving on to translation, some addition about a testing instruction on the FG page may be helpful for people like me :)

**Comment by obenland** [comment]
With the templates in the JSON you'll be able to test it in the API with `public-api` sandboxed.
In the [developer console](https://developer.wordpress.com/docs/api/console/), this will return them:
![image](https://user-images.githubusercontent.com/1398304/80112596-2133ea00-8536-11ea-8f75-d5d6b144a04d.png)

Test them in the template selector itself you'll need to install [the plugin](https://wordpress.org/plugins/full-site-editing/) on a local site (so the API request gets sandboxed) and have `WP_DEBUG` set to true (so the response doesn't get cached)

**Comment by iamtakashi** [comment]
Thanks, I can see the added blog layouts in the developer console. Good.

However, I can't see any blog layouts as well as some other layouts in the selector at the moment. I have Block Experiments, Full Site Editing, and Jetpack(dev mode) installed and activated, but I assume I need a "full" Jetpack, and some layouts that required it are hidden. I think I need to set up my local install so that I can activate Jetpack fully.

**Comment by iamtakashi** [comment]
@obenland All the blocks used in the new blog layouts are available in my local install, and I can see all the new layouts that I've added in my local install 🎉

The next item on the instruction is to generate a linguine file that can be sent to our translation service, but I'm wondering the change in my sandbox needs to be tested and deployed before moving on.

What is the most appropriate next action? Please advice.

**Comment by obenland** [comment]
I'm not sure they _need_ to be, but they can be if you prefer to ship them as soon as possible.
Having said that, there's been more of a push to release new features translated and for all mag16 languages simultaneously.

**Comment by iamtakashi** [comment]
We've decided to wait for translation for mag 16 to deploy them. I'll start the translation process tomorrow.

**Comment by iamtakashi** [comment]
I've submitted the annotation for translation. I'll wait for an email about how to deploy them when the translation is done.

**Comment by iamtakashi** [comment]
@akirk Hello! The translation strand `59167` was reviewed and has been sent for translation. How long do you think it'd take to be translated?

**Comment by akirk** [comment]
Some translators are on holidays this week, we hope to get all languages early next week.

**Comment by iamtakashi** [comment]
Received the translation while I was AFK. 

As @obenland warned in the comment of this post `pbFcYn-1A-p2`, Contact Info block is broken in other languages. Map block also seems broken.

@obenland, would it be best to fix it in the json files?

**Comment by obenland** [comment]
Correct, yes, in those translations

**Comment by iamtakashi** [comment]
Noting here that all the Subscription block is also broken in other languages. The same thing @obenland experienced in Block Patterns: https://github.com/Automattic/jetpack/issues/15076#issuecomment-603448947

**Comment by sirreal** [comment]
I've created https://github.com/Automattic/jetpack/issues/15776, which describes the underlying issue with the Subscription Form block.

From what I've understood, there may be a workaround for these layouts. You'll need to change the button text so that it is not the default.

This block (with different button text):

![Screen Shot 2020-05-13 at 13 29 13](https://user-images.githubusercontent.com/841763/81807188-eeba5300-951d-11ea-80c6-f5caa57caa81.png)

Will result in this block:

```html
<!-- wp:jetpack/subscriptions {"submitButtonText":"Subscribe to get all the latest news from my awesome feed"} -->
<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_only_email_and_button="true" custom_background_button_color="undefined" custom_text_button_color="undefined" submit_button_text="Subscribe to get all the latest news from my awesome feed" submit_button_classes="undefined" show_subscribers_total="false" ]</div>
<!-- /wp:jetpack/subscriptions -->
```

I understand that `Subscribe to get all the latest news from my awesome feed` would be part of the pack sent for localization and could be properly localized. @obenland is that accurate?

Compare that to the default:

![Screen Shot 2020-05-13 at 13 31 29](https://user-images.githubusercontent.com/841763/81807275-14475c80-951e-11ea-86fa-635c6b937074.png)


```html
<!-- wp:jetpack/subscriptions -->
<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_only_email_and_button="true" custom_background_button_color="undefined" custom_text_button_color="undefined" submit_button_text="Subscribe" submit_button_classes="undefined" show_subscribers_total="false" ]</div>
<!-- /wp:jetpack/subscriptions -->
```

In this case, the use of the default combined with block attribute parsing results in the block being invalidated. Here's an example of a block saved in English and opened in Spanish:

![Screen Shot 2020-05-13 at 13 36 40](https://user-images.githubusercontent.com/841763/81807693-d4cd4000-951e-11ea-9b34-8196504d0f0d.png)
![Screen Shot 2020-05-13 at 13 36 30](https://user-images.githubusercontent.com/841763/81807700-d7c83080-951e-11ea-9887-859d0239fe9b.png)

Changing `Subscribe` to `Subscribe!` prevents the block invalidation.

@iamtakashi Will that unblock the template work?

**Comment by iamtakashi** [comment]
@sirreal Thanks for looking into this issue, and I appreciated you made an issue for it.

This is what I see in the json file for `fr` that is broken at the moment. And I've been trying to edit it to fix, but I'm having trouble to make it work. Could you give me steps to fix?

```
<!-- wp:jetpack/subscriptions -->\n<div class=\"wp-block-jetpack-subscriptions\">[jetpack_subscription_form show_only_email_and_button=\"true\" custom_background_button_color=\"undefined\" custom_text_button_color=\"undefined\" submit_button_text=\"Sign Up\" submit_button_classes=\"undefined\" show_subscribers_total=\"false\" ]</div>\n<!-- /wp:jetpack/subscriptions -->
```

**Comment by sirreal** [comment]
@iamtakashi If you open the code editor and replace the subscriptions block with this (look for `wp:jetpack/subscriptions`) does it work?

```html
<!-- wp:jetpack/subscriptions {"submitButtonText":"Sign up"} -->
<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_only_email_and_button="true" custom_background_button_color="undefined" custom_text_button_color="undefined" submit_button_text="Sign up" submit_button_classes="undefined" show_subscribers_total="false" ]</div>
<!-- /wp:jetpack/subscriptions -->
```

**Comment by akirk** [comment]
I don't have enough experience with it but it seems to me that for translation, it'd be best to have our blocks use `source: html`. [By default it is stored in the HTML comment](https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/) which is left alone during translation. Thus, this incompatibility arises. If the block read the HTML, it would receive the translated texts.

I realize that this means that we'd have to rewrite our blocks (and isn't helpful in this situation) but it's the best solution I know so far. Maybe we need to build something custom to try to do this when sending back the translated text but I am not sure how easy it'd be.

**Comment by iamtakashi** [comment]
@sirreal Oh, I see. I now know how to change the button text in the json :) and your suggestion works beautifully! Much appreciated!!

**Comment by sirreal** [comment]
No problem 👍  Note that it's repeated and changed in both places. It will likely need to match to prevent invalidation: `{"submitButtonText":"Sign up"}` and `submit_button_text="Sign up"`.

**Comment by iamtakashi** [comment]
I've fixed all the translations and updated `D42287-code`.

@obenland Would you mind testing the diff? I can see one of the unit tests has failed, but I'm not sure what that means or how to fix it :)

**Comment by iamtakashi** [comment]
BTW, some homepage layouts are still broken, but since the sources are different, those should be fixed separately.

**Comment by iamtakashi** [comment]
@akirk Do you imagine we have to do this manual fixing for all the block instances on all the layouts every time we add a new layout and update the json file? Or do we need to fix new instances on the new layout? We're planning to keep adding layout, and I obviously want to avoid this situation again. Would the Contact Info, Map, and Subscribe blocks need to be fixed before we add a new layout?

**Comment by akirk** [comment]
I think we have two options:
1. Ensure that our blocks only use the data from HTML. When translating the HTML, the HTML comments are left as they are since in the Gutenberg case its structure is not well-defined.
2. Add custom translation deploy code that tries to rewrite the Gutenberg HTML comment based on the translations, like you are doing manually.

Honestly, I don't have experience with `source: "html"` yet, and how much work it is to convert a block from comment JSON to that.

So maybe we'd first go for option 2; we'll need to consider each block with custom code, I think, since the JSON/HTML mapping might be custom (here I saw a snake_case vs camelCase which we can handle, I think).

For the path forward, I hope we can encourage everyone to move to `source: "html"`?

**Comment by iamtakashi** [comment]
Thank you, @akirk. Am I right to understand that we'll have the same situation next time we want to deploy a new layout unless we take one of the options you suggested?

Just to share, this was what I needed to do to fix the map block instances in the layouts for other languages.

Original markup of a Map block that was broken in non-English languages:
```
<!-- wp:jetpack/map {\"points\":[],\"zoom\":12,\"mapCenter\":{\"lng\":151.207006,\"lat\":-33.868288}} -->\n<div class=\"wp-block-jetpack-map\" data-map-style=\"default\" data-map-details=\"true\" data-points=\"[]\" data-zoom=\"12\" data-map-center=\"{\"lng\":151.207006,\"lat\":-33.868288}\" data-marker-color=\"red\" data-show-fullscreen-button=\"true\"></div>\n<!-- /wp:jetpack/map -->
```

Fixed by replacing it with:
```
<!-- wp:jetpack/map {\"points\":[],\"zoom\":12,\"mapCenter\":{\"lng\":151.207006,\"lat\":-33.868288}} -->\n<div class=\"wp-block-jetpack-map\" data-map-style=\"default\" data-map-details=\"true\" data-points=\"[]\" data-zoom=\"12\" data-map-center=\"{&quot;lng&quot;:151.207006,&quot;lat&quot;:-33.868288}\" data-marker-color=\"red\" data-show-fullscreen-button=\"true\"></div>\n<!-- /wp:jetpack/map -->
```

**Comment by iamtakashi** [comment]
> Am I right to understand that we'll have the same situation next time we want to deploy a new layout unless we take one of the options you suggested?

@akirk Sorry, I don't think I've asked my question with the right words. What I'm worried about is that when we update the json for a new layout and send it to the translators, what I changed manually this time would be wiped out, and I need to do the same again.

**Comment by obenland** [comment]
> I can see one of the unit tests has failed, but I'm not sure what that means or how to fix it :)

I re-ran the tests and they're green now. You can do that by clicking on the build that failed and the click "Restart Build" in the top right corner.

I'm a bit strapped for time right now, maybe @ianstewart can help test these changes?

**Comment by iamtakashi** [comment]
`D42287-code` has been deployed after a review by @p-jackson (Thank you!)
