### ISSUE TITLE
Migrate META Description field from WP.com editor to Gutenberg

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#41378]
## Description

In the process of deprecating the WP.com editor we'll be removing the ability for Business plan customers to enter a META Description for their posts/pages. Here's an example of what the field looks like today within the WP.com editor:

![meta-description](https://user-images.githubusercontent.com/5634774/80020255-aec7f900-84a6-11ea-9145-300c80b62d4e.png)

This is something that we highlight as a feature for Business plan customers:

<img width="1397" alt="Image 2020-04-22 at 2 41 33 PM" src="https://user-images.githubusercontent.com/5634774/80020706-7248cd00-84a7-11ea-800e-70f3cab4d0bc.png">

We need to migrate this field to Gutenberg for business plan customers. I'm open to suggestions on where to place this field, but I would suggest adding it just under "Excerpt" on the Document tab:

![Screen Shot 2020-04-22 at 2 40 41 PM-1](https://user-images.githubusercontent.com/5634774/80020581-462d4c00-84a7-11ea-83e5-420a23af1f27.png)

**Comment by rickybanister** [comment]
The SEO description field is already in the editor as part of the Jetpack sidebar plugin:

![image](https://user-images.githubusercontent.com/437258/80027347-9dd0b500-84b1-11ea-8cb2-bdf835e47897.png)

Not the most findable, but it's already built in.

**Comment by davemart-in** [comment]
Ah, thanks for pointing that out @rickybanister. Looks like it's already gated behind the Business plan as well. I'll close this then. cc @gracie and @creativecoder
