### ISSUE TITLE
Gutenboarding IE11 styling: header issues on /style step

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#41389]
In the styling step in IE11 there are a couple of issues in the header:

1. The new heading for this step extends the title into the viewport picker on slightly narrower screen widths (the media query for the viewport picker might need to be changed so that it gets hidden earlier)

![image](https://user-images.githubusercontent.com/14988353/80049193-982cab00-8555-11ea-9db6-7ed6adc32b19.png)

2. At larger screen widths the buttons at the top right aren't aligning next to each other as they did previously / do in other browsers (when fixing this make sure that the stacked styling in narrower viewports still works correctly)

![image](https://user-images.githubusercontent.com/14988353/80049263-bf837800-8555-11ea-9c84-1fc1d9bcccf4.png)

URL: https://wpcalypso.wordpress.com/new/style

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

We've discontinued IE11 support, so this issue should be closed as `Closed - Won't Fix`.
