### ISSUE TITLE
Jetpack Plugins: "Jetpack Plugins" heading wording is a bit confusing

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#414]
![screen shot 2015-08-04 at 2 17 24 pm](https://cloud.githubusercontent.com/assets/426388/9060390/9ad271ec-3ab3-11e5-9d19-030a95b2114c.png)

It would be less confusing to say something like "Plugins on your sites using Jetpack".

**Comment by enejb** [comment]
cc @MichaelArestad or @rickybanister do you have any suggestions here?

**Comment by MichaelArestad** [comment]
I think just `plugins`, `standard plugins`, or `other plugins` could work.

**Comment by enejb** [comment]
Lets just call it plugins.
