### ISSUE TITLE
Gutenboarding: encoding issue in design screenshots

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#41401]
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/new/
2. Enter "photography" and skip the name

#### What I expected

On https://wpcalypso.wordpress.com/new/design I expected the screenshots to have no encoding issues. 

#### What happened instead

The Vesta screenshot has an encoding issue:

<img width="1100" alt="Screenshot 2020-04-23 at 12 03 53" src="https://user-images.githubusercontent.com/23619/80089911-f7db8400-855e-11ea-91cd-39b5058dbd8a.png">

#### Context / Source

This might go away when moving from [bin/generate-gutenboarding-design-thumbnails.js](https://github.com/Automattic/wp-calypso/blob/master/bin/generate-gutenboarding-design-thumbnails.js) to [mShots](https://github.com/Automattic/mShots) when Automattic/mShots#16 is resolved, but I wanted to flag it just in case to ensure this is fixed before we roll this out to users.

**Comment by sirreal** [comment]
Here's a PR with funky strings in a template to help debug this: https://github.com/Automattic/wp-calypso/pull/40887

**Comment by ramonjd** [comment]
Fix for this is to to use `mb_convert_encoding` in `$dom_template->loadHTML` in the template demo endpoint.

Came in while reviewing D44140-code#inline-169706

While loading https://public-api.wordpress.com/rest/v1/template/demo/mayland/vesta/?calypso_hash=fb77d2ce350179f9b3d57b443daea92c02d2b195 ...

**Before**
<img width="735" alt="Screen Shot 2020-06-04 at 12 12 10 pm" src="https://user-images.githubusercontent.com/6458278/83707483-6d0d9f00-a65d-11ea-9f22-5a34da14dc4e.png">

**After**
<img width="823" alt="Screen Shot 2020-06-04 at 12 12 39 pm" src="https://user-images.githubusercontent.com/6458278/83707486-6f6ff900-a65d-11ea-9a23-0bebc56dc115.png">

**Comment by andrewserong** [comment]
Fix for the template endpoint rolled into D44140-code.

**Comment by sirreal** [comment]
Thanks!
