### ISSUE TITLE
Site Setup List: site menu step appears too soon

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#41402]
Steps to reproduce:

1. Sign up for a new account.
1. Follow the Site Setup List steps in order until you reach the "Create site menu" step.
1. Click the "Start with tutorial" button.
1. Click the "Go to the Customizer" button.
1. Click "Menus" on the left.

**Result:** the "Create a site menu" step is before the "Confirm your email address" step in the Site Setup List, but you cannot create a site menu before you confirm your email address. If you try to edit Menus in the Customizer before confirming your email address, the following error appears: "You won't be able to edit your menu until you confirm your email address." ([15s](https://cloudup.com/csADKFS3dBG))

![you-wont-be-able-to-edit-your-menu](https://user-images.githubusercontent.com/1119271/79825355-0b67ce80-8356-11ea-842b-f180ac341c7a.png)
<p style="clear:both;"><sup>Tested with WPDesktop 5.1.0-beta1 on macOS 10.14.6.</sup></p>

**Comment by rachelmcr** [comment]
I moved this to the Calypso repo since it also occurs in Calypso web (not just the desktop app).

**Comment by rachelmcr** [comment]
cc @mmtr as I see you added this step in https://github.com/Automattic/wp-calypso/pull/40844

**Comment by mmtr** [comment]
Thanks for the heads up. Potential fix available for review at D42327-code.

**Comment by kwight** [comment]
Fixed in D42327-code and deployed 👍
