### ISSUE TITLE
Show post type tabs for "Scheduled" and "Trashed" even if no posts under those categories

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#41413]
In the /posts screen we only display `Scheduled` and `Trashed` filters if there are any posts to filter. 

In the /pages screen we display those filters all the time. Clicking them shows a kind of 404 message.

<img width="1078" alt="Screen Shot 2020-04-23 at 2 13 58 PM" src="https://user-images.githubusercontent.com/437258/80134556-eac59180-856c-11ea-9faa-2dd7b8148e93.png">

Is there an API reason for this, some limitation that makes it expensive to do a check before the page loads or can we remove those to make both screens behave the same?

**Update 6/23/20** - per discussion below, final decision is to create consistency between `/pages` and `/posts` by having both screens display all tabs regardless of content. `/posts` will continue to display counts for each tab, `/pages` will not.

**Comment by hrrsppzgl** [comment]
Indeed Pages tabs vs Post tabs behave quite differently.

While in /posts, we do a request for the post counters 

![](https://cln.sh/ASQLho+)

and hide `Scheduled`, `Trashed` when `count === 0`

![](https://cln.sh/GhM6Om+)

weird thing is, that in /pages, we do a request for the post counters **not for page counters** and we show all Tabs without counters

![](https://cln.sh/T3V7JF+)

Clicking on a tab without results 

![](https://cln.sh/01fXcR+)

Actually, I would suggest : 

- Get the page counts in /pages and show them
- In both /pages and /posts, show all tabs even if `count === 0` . From UX perspective, I would prefer knowing that when I trash page/post it **moves** to another folder and it is not permanently deleted.

**Comment by blackjackkent** [comment]
@danhauk and/or @sixhours Can you weigh in from the design side on the suggestion in the comment above vs the ask in the initial post? I think @cpapazoglou does make a good point about the user experience but it definitely affects the scope of work for this ticket.

**Comment by sixhours** [comment]
> Get the page counts in /pages and show them

I'm not sure I see the value in showing page counts. Does a user need to know they have 25 pages? Or 4 trashed pages? When would that information be useful?

(I feel similarly about Posts, although from a blogging perspective, I can see how having 2500 posts or whatever is a cool bragging right.)

> In both /pages and /posts, show all tabs even if count === 0 . From UX perspective, I would prefer knowing that when I trash page/post it moves to another folder and it is not permanently deleted.

This makes sense to me, putting the functionality upfront rather than trying to be clever.

I'm not sure how valuable it is to show the tab for scheduled pages (if posts are timely and ongoing, pages are usually static, so I wonder how often people actually schedule pages) but I can see keeping it in the interests of keeping the interfaces consistent.

**Comment by blackjackkent** [comment]
OK, so it sounds like we're leaning towards the inverse of the original ask -- rather than remove the tabs on `/pages`, add them back on `/posts`. (And leave the numbers situation as it is on both pages.)

**Comment by rickybanister** [comment]
That's fine with me, consistency is what's most important. 

I do think that the count is very important for the Drafts tab to encourage follow-through. I often forget I've left drafts sitting.

**Comment by frontdevde** [comment]
**Dotcom Manage Janitor rotation note 24 Jun 2020:**
Removing this issue from the Janitor board as a product team (Serenity/@blackjackkent) claimed ownership.
