### ISSUE TITLE
Jetpack Search: upgrade nudge leads to Pro plan

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#41421]
Also, we should remove the mention of Search from its list of features. -> in progress in https://github.com/Automattic/wp-calypso/pull/41434

#### Steps to reproduce

1. Starting at URL: /settings/performance/:site for a connected Jetpack site with no Search no Pro plan
2. Press the nudge
![search](https://user-images.githubusercontent.com/13561163/80148356-3d2aa080-85b5-11ea-888c-41bbcd48a872.png)

3. Enhanced Search feature is present and highlighted
![nudge](https://user-images.githubusercontent.com/13561163/80148102-d1e0ce80-85b4-11ea-9b60-280363fdfeae.png)

#### What I expected
Redirect to the Search product card or no Search feature highlight

**Comment by jsnmoon** [comment]
As mentioned above, this has been fixed by #41434. It might be worth investigating a scroll-to-product-card UX in the future.
