### ISSUE TITLE
Gutenboarding: Improved domain picker

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41435]
We've worked on making the domain picker more prominent.
![image](https://user-images.githubusercontent.com/2896062/80207139-e7dea580-862d-11ea-84f4-278920b941d5.png)
Hopefully the screenshot (which is taken from the Figma file under _Header treatments_) should be accurate.
Things of note though:
- Margin is `24px on desktop` and `20px on mobile`
- It says _domain.com is available_ before the domain has been confirmed and reflect the chosen domain after it's been confirmed. 
- We hide the site name on mobile to avoid a busy header and text clashing.

There's also a [new animation](https://d.pr/v/LM5rwF) to the domain picker:
1. A slide in when it enters for the first time
2. A slight pop when the domain is confirmed

**Comment by yansern** [comment]
While exploring how to implement this I run into some technical issues. Determining when the button text has changed is tricky.

The content of the `DomainPickerButton` is passed over as a children from `header/index.tsx`, sometimes this is an empty string, sometimes this is a text node, sometimes this is a react element.

The logic that generates the content of the button text needs to be moved out from `header/index.tsx` into `DomainPickerButton`.

I feel there is also a need for a function that returns the current domain including its state, e.g. `const currentDomain = { domain: 'foobar.com', state: 'recommended|confirmed' }`.

When domain has changed:
- replay animation

When state is `recommended`:
- "...is available" text is added to the button.
- no pop animation.

When state is `confirmed`:
- "...is available" text is not appended to the button.
- has pop animation.

Also, take account that there is also a `loading` state to consider, where I think animation should be disabled.

**Comment by simison** [comment]
I think there's also an open question whether to run the animation at intent gather step or delay it until design picker, which might affect implementation. (pbAok1-CG-p2#comment-1384)
