### ISSUE TITLE
Gutenboarding: Make action buttons sticky on mobile

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41436]
Let's make the _Continue_ and _Back_ fixed to the bottom on mobile:
![image](https://user-images.githubusercontent.com/2896062/80207562-a7cbf280-862e-11ea-9fa6-687546940096.png)

The back button string on desktop is trying to communicate which step they'll go back to, but on mobile this becomes long so let's use _Go back_ instead (again, mobile only).

This new bottom bar applies to the steps where we have these buttons which is Style, Plans, Domain Overlay and Domain page.
We could consider adding it to the Design step too, but this requires changing it from a _Tap design to continue_ to a selection state:
![image](https://user-images.githubusercontent.com/2896062/80207800-2032b380-862f-11ea-8ff9-60dc49737c92.png)

**Comment by razvanpapadopol** [comment]
@yansern When working on this, please consider testing it iOS because we already have an [issue with Domain picker ](https://cloudup.com/iN_9SQZQAz0) fixed footer mentioned in https://github.com/Automattic/wp-calypso/issues/41752

**Comment by yansern** [comment]
@razvanpapadopol Thanks for the heads up! Oh boy looks worrying! :)

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/43136
