### ISSUE TITLE
Reader: Images from the content area is displayed on reader despite featured image already set

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#41463]
I ran into an issue related with this, and I able to replicate it on my end.

#### Steps to reproduce

1. Check the website on the Reader. Here, I'm using my personal site: https://wordpress.com/read/feeds/54386441

2. Check the feed. Some blog posts have one featured image displayed, some have multiple images.
![reader](https://cldup.com/RsSMyfYShb.png)
*Direct link: https://cldup.com/RsSMyfYShb.png*

#### What I expected
I expect the Reader will only show one image only -- the featured image -- when the featured image set on the blog post. For example, on blog post 'Restricted Movements', you can see the featured image displayed:
![featured](https://cldup.com/NEpWRk1cAK.png)
*Direct link: https://cldup.com/NEpWRk1cAK.png*

And if you go to the blog post:
https://corianderinpho.wordpress.com/2020/03/19/restricted-movements/

You will see that there are multiple images there.

#### What happened instead
Inconsistencies. For example, this post:
https://corianderinpho.wordpress.com/2020/02/05/morning-walk-february-1-2020/

I have set the featured image:
![featured](https://cldup.com/9jk15B3gAY.png)
*Direct link: https://cldup.com/9jk15B3gAY.png*

And on Reader, I see multiple images:
![reader](https://cldup.com/DpD7kmGXkn.png)
*Direct link: https://cldup.com/DpD7kmGXkn.png*

It would be nice if the Reader will only pull the featured image when it's set on the blog post.

#### Browser / OS version
Chrome. macOS Catalina 10.15.4

#### Context / Source
External report and personal experience.

**Comment by KokkieH** [comment]
As far as I know this is by design. See https://wordpress.com/support/reader/#reader-post-cards:

> (Note: the Reader only considers images added to the post content itself when deciding which card to use. Featured images that are not also added to the post content are not considered.)

cc @bluefuton to confirm.

**Comment by retnonindya** [comment]
Ooooh! TIL! Thank you so much, @KokkieH 🙏

**Comment by davipontesblog** [comment]
I am closing this one as it seems to be standard and expected behavior as mentioned by @KokkieH .
