### ISSUE TITLE
Page Templates: Each Layout Needs a Label

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#41468]
### Steps to reproduce

1. Starting in the WordPress.com Calypso dashboard, navigate to Pages and Add New Page
2. Use a screen reader to browse through the page layouts

#### What I expected

I expected to be able to browse through the layouts using a screen reader, with each layout being clearly labelled for selection. For example, "Blank layout, About pages, Large image two columns, Small image two columns," and so on. The layouts should each have a descriptive label.

#### What happened instead

Each label is called out as "button" so scrolling through the labels using a screen reader calls out "About pages, layout, button, button, button, Blog pages, layout, button, button, button, button...." 

#### Browser / OS version

Windows, Chrome 81
Mac Catalina, Safari 13
iPhone Safari

#### Screenshot / Video

You can skip ahead to 20 seconds as it took me that long to find my way there:

Video: https://d.pr/v/OpP8BZ

#### Context / Source

#p4vt7e-6n-p2

#journey #empathy #livesharing #accessibility #painpoint #user-report

**Comment by davemart-in** [comment]
I added this to the create maintenance board as they are maintaining page templates now.

**Comment by jeyip** [comment]
I can reproduce the problem. I enabled voiceover on my mac using `Command + F5` and tried tabbing through the list of page templates. Moving this into the prioritized backlog.

**Comment by david-szabo97** [comment]
We are now using the description of the page layouts as a label for the screen readers, but some of the layouts don't have a description so this issue is still going on.

**Comment by obenland** [comment]
I just did a screen recording of the new page layout selector. @donalirl Could you double-check if this fits what you had in mind for this ticket?

https://user-images.githubusercontent.com/1398304/126719255-308596f5-ea9b-4a51-81ef-d4f5a746148a.mov

**Comment by donalirl** [comment]
@obenland yes that's it, thank you!
