### ISSUE TITLE
Gutenboarding: Bringing design parity to signup/login pages

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41478]
I've left justified the design and added social buttons and other signup/login mechanics to achieve parity with the standard signup/login pages.

Sign up:
![image](https://user-images.githubusercontent.com/2896062/80371388-1fe62280-8892-11ea-8e7c-e7db98571ec0.png)

Login:
![image](https://user-images.githubusercontent.com/2896062/80371416-2b394e00-8892-11ea-8295-4b00e66f7a6e.png)

Error, mobile, and other details can be found in the Figma file.

**Comment by yansern** [comment]
Closing this issue as this will now be tracked with the Gutenboarding: Social Signup project.
https://github.com/Automattic/wp-calypso/milestone/331
https://github.com/Automattic/wp-calypso/projects/106
