### ISSUE TITLE
Gutenboarding: Updated plans pages

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41479]
Here's the new plans page and as always there are more details in Figma.

**Domain not chosen**
![image](https://user-images.githubusercontent.com/2896062/80380810-604c9d00-88a0-11ea-9dd2-0c3e8d48a981.png)

**Domain chosen**
![image](https://user-images.githubusercontent.com/2896062/80380983-8a9e5a80-88a0-11ea-8768-d0989c2e1f70.png)

A few things of note:
- Clicking _Select_ on a plan selects the plan and it's also reflected in the header. Users click _Continue_ to proceed.
- Clicking the _Choose domain_ should open the full domain page (not the overlay)
- Clicking _More details_ reveals the full comparison grid which you can find in Figma.

**Comment by simison** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/43134
