### ISSUE TITLE
Gutenberg v8.0.0: duplicate Preview links appearing in the header

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#41519]
The class name for the Preview dropdown in Gutenberg has been updated as of GB v8.0.0, which results in two Preview links appearing the editor header (change introduced in https://github.com/WordPress/gutenberg/pull/21309):

![image](https://user-images.githubusercontent.com/14988353/80457303-6c089400-8972-11ea-9459-b05a39671e05.png)

This should be resolved by updating the line https://github.com/Automattic/wp-calypso/blob/722d1e8eb242fe7c9663bd518db802899bc7449f/apps/wpcom-block-editor/src/calypso/features/legacy-preview-button.scss#L15 to use the `.block-editor-post-preview__dropdown` class instead. (To support both GB v7.8.1 and v8.0.0 concurrently, it'd be a good idea to use both selectors).

**Comment by ramonjd** [comment]
Created https://github.com/Automattic/wp-calypso/pull/41528 for the heck of it :)
