### ISSUE TITLE
Gutenberg v8.0.0 mobile header layout regressions in dotcom

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#41521]
Gutenberg v8.0.0 involves a number of class name changes. This is the most likely cause of some mobile styling issues with the editor header.

* There is too much space at the top of the screen (where the .org admin bar would usually exist). This is probably because the editor interface now uses a `.interface-interface-skeleton`, which we'll need to target
* Layout in wpcom FSE mobile might need a bit more tweaking, but it looks like the main thing that needs to be done is to hide the back button (again likely a classname change?)

#### simple site mobile layout issue

| GB v7.8.1 | GB v8.0.0 |
| --------- | ---------- |
| ![image](https://user-images.githubusercontent.com/14988353/80460601-695c6d80-8977-11ea-82ee-3d8835c66d06.png) | ![image](https://user-images.githubusercontent.com/14988353/80460372-171b4c80-8977-11ea-836a-e69d4acd301e.png) |

#### wpcom FSE mobile layout issue

| GB v7.8.1 | GB v8.0.0 |
| --------- | ---------- |
| ![image](https://user-images.githubusercontent.com/14988353/80460235-e3402700-8976-11ea-9e68-068ab5fc9aac.png) | ![image](https://user-images.githubusercontent.com/14988353/80460155-c7d51c00-8976-11ea-89ee-aad49eb6efe0.png) |

Note: the content of the FSE site going off the edges of the screen will likely be fixed by the solution we use for dealing with https://github.com/Automattic/wp-calypso/issues/41513

**Comment by Addison-Stavlo** [comment]
A new FSE version was released with the above PR changes, and Gutenberg v8.0 is now live.  Closing this as it seems to be fixed now.  😄
