### ISSUE TITLE
Stats: Y-axis displays decimals when max views are 1

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#41532]
There is a corner case in the Stats chart graph that causes the y-axis to display numbers with decimals if the max value shown in the chart is 1.

<img width="1132" alt="Screen Shot 2020-04-27 at 2 39 22 PM" src="https://user-images.githubusercontent.com/1270189/80423494-f67ac600-8894-11ea-8c7f-27394a6dafec.png">

This could be solved by either picking a yMax of 2 for this case, or forcing integer intervals on things that shouldn't be divided.

**Comment by cathymcbride** [comment]
No customer reports. Closing.
