### ISSUE TITLE
Gutenboarding: add is-available check to domains

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#41534]
Before allowing a domain to be selected, it should be checked for availability.

https://github.com/Automattic/wp-calypso/blob/711190aee23edea9006c079d44b7b7cee5d9b977/client/lib/wpcom-undocumented/lib/undocumented.js#L482-L492

https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/lib/domains/registration/availability-messages.js

See details in pbAok1-Hb-p2#comment-1472

**Comment by simison** [comment]
I have more info and design for this in these two issues, let's continue in them:
https://github.com/Automattic/wp-calypso/issues/41220
https://github.com/Automattic/wp-calypso/issues/41219
