### ISSUE TITLE
Gutenboarding: Handle blog_title_invalid

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#41537]
Starting at [wordpress.com/new](https://wordpress.com/new), I just tried to create a site with title ```<z,E`sRW|m9y5``` and it failed at a dead end for the user.

Response from `/new` endpoint:

```jsonc
{error: "blog_title_invalid", message: "Invalid blog title"}
```

**Comment by yansern** [comment]
This phab patch D57741-code will fallback to blog name (which is sanitized) when blog title is invalid. 
`<z,E``sRW|m9y5` becomes `zesrwm9y5`.

**Comment by yansern** [comment]
Deployed.
