### ISSUE TITLE
FSE Plugin: Add unshipped block patterns

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#41544]
There are some patterns ready to ship but not being deployed yet. We should deploy them so that the customers can start using.

- [ ] https://github.com/Automattic/blockpatterns/issues/34
- [ ] https://github.com/Automattic/blockpatterns/issues/35
- [ ] https://github.com/Automattic/blockpatterns/issues/36
- [ ] https://github.com/Automattic/blockpatterns/issues/37
- [ ] https://github.com/Automattic/blockpatterns/issues/38
- [ ] https://github.com/Automattic/blockpatterns/issues/39
- [ ] https://github.com/Automattic/blockpatterns/issues/42
- [ ] https://github.com/Automattic/blockpatterns/issues/43

Each pattern above has been published as a post in https://dotcompatterns.wordpress.com 

We expect this list keeps growing as we keep building patterns. I'll update the list above as we make new ones.

@johnHackworth Is this something the folks form Create can help?

cc @ianstewart

**Comment by ianstewart** [comment]
Closing this one as it's out of date and a no-longer-needed task for deployment.
