### ISSUE TITLE
Gutenboarding: domain modal follow-ups

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41542]
Testing domain modal and made these observations. Tested using Firefox.

### In `master`
- [x] No domain is pre-selected in dropdown — I expected free one to be pre-selected:

    <img width="334" alt="image" src="https://user-images.githubusercontent.com/87168/80503434-82b2e900-897a-11ea-845b-f7e843127378.png">

### With a feature flag

- [x] Scrollers in dropdown:
    <img width="375" alt="image" src="https://user-images.githubusercontent.com/87168/80503242-42ec0180-897a-11ea-89ef-e2ff37d5ecb8.png">

- [x] "x" icon is mis-aligned:
    <img width="105" alt="image" src="https://user-images.githubusercontent.com/87168/80504675-120ccc00-897c-11ea-8341-860a5995867d.png">

    In Figma:
    <img width="156" alt="image" src="https://user-images.githubusercontent.com/87168/80504598-fe616580-897b-11ea-8148-d81a5fcb15f0.png">

- [x] Let's hide todo-texts in the modal:
    <img width="317" alt="image" src="https://user-images.githubusercontent.com/87168/80503562-b4c44b00-897a-11ea-8dc5-f2214c4c498a.png">

- [x] Tiny search icon alignment issue on modal (not present in dropdown):
    <img width="139" alt="image" src="https://user-images.githubusercontent.com/87168/80503622-ce659280-897a-11ea-9898-0f3f4b28f0e1.png">

- [x] Let's have category hover mode be _underlined_ but not _bold_ like active state:
    <img width="235" alt="image" src="https://user-images.githubusercontent.com/87168/80503732-f5bc5f80-897a-11ea-9a64-13d5b46fafd5.png">

- [x] Modal shows 5 domains instead of 10 like in Figma

- [ ] In modal, should the selected domain show up in the header? I know in Figma it doesn't. (@dubielzyk)
    <img width="374" alt="image" src="https://user-images.githubusercontent.com/87168/80503880-256b6780-897b-11ea-92f3-86e27d9a7b77.png">

- [x] When loading domains, should we retain the grid? (@dubielzyk)
    <img width="449" alt="image" src="https://user-images.githubusercontent.com/87168/80504117-6e232080-897b-11ea-87ae-313ebfa57a32.png">
    <img width="449" alt="image" src="https://user-images.githubusercontent.com/87168/80504236-8abf5880-897b-11ea-9c7c-5765eba5577d.png">

cc @dubielzyk lemme know if anything seems off. :-)

**Comment by simison** [comment]
I think once the todo text is removed and scrollers fixed, we could already remove the feature flag and "release" this internally.

**Comment by dubielzyk** [comment]
> In modal, should the selected domain show up in the header? I know in Figma it doesn't. (@dubielzyk)

That's because my original intention was to not change the domain until they hit confirm. I'm not convinced that's the better solution, but currently the X and the Confirm does the same thing, but initially we thought he X should cancel your selection and Confirm should set it.

> When loading domains, should we retain the grid? (@dubielzyk)

Yes we should retain the grid.

**Comment by yansern** [comment]
> That's because my original intention was to not change the domain until they hit confirm. I'm not convinced that's the better solution, but currently the X and the Confirm does the same thing, but initially we thought he X should cancel your selection and Confirm should set it.


I find myself feeling trapped when I enter domain modal, like there's no way out.

I think a Cancel button should be there next to Confirm. Cancel button is not the same as X button. X button is to close the popover. Cancel button does two things:
- it lets user goes back to the popover mode
- it reverts any changes done in domain modal (wrangling in data layer needed).

**Comment by simison** [comment]
@dubielzyk I made the same observation as @yansern — only way out from the modal is to "confirm" and I was really missing "Cancel" or "Close" button.
