### ISSUE TITLE
Can't run E2E tests locally due to check-npm-client

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#41541]
### Running

```sh
npm run test-e2e
``` 
Fails with 
```
[check-npm-client] please use yarn instead of npm
```

### And running
```sh
yarn test-e2e
``` 
Fails with 
```
[check-npm-client] please use npm instead of yarn
```

/cc @scinos

**Comment by cathymcbride** [comment]
e2e tests are currently running fine. I think was during a window of time when we were making the transition b/t npm & yarn.
