### ISSUE TITLE
Paragraph block: color options are missing

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#41551]
This is the case on Simple sites, AT sites (with and without standalone Gutenberg plugin enabled) work fine. Reported in 4343265-hc, confirmed on my test sites. There's no color setting on the sidebar and no inline color option:

![image](https://user-images.githubusercontent.com/32492176/80519812-cb9c7a80-8945-11ea-9321-8d7c021cc888.png)

**Comment by selectedselections** [comment]
Received a user report of this for a Media & Text block as well which should have these settings usually: 

https://wordpress.com/support/wordpress-editor/blocks/media-text-block/#block-settings

I was able to reproduce on my test, simple site as well

**Comment by mikeicode** [comment]
Reported on Paragraph blocks 19880541-hc

**Comment by ash1eygrace** [comment]
Reported in HC-20555656 for Group blocks, paragraph blocks. Also, tested on my own site without color setting for paragraph blocks.

**Comment by xpurichan** [comment]
Reported in 19190136-hc

**Comment by edequalsawesome** [comment]
Also reported in #7873032-hc for the Cover block

**Comment by obenland** [comment]
@Automattic/ajax shipped a CoBlocks update to version 1.23.0 about two hours ago.
I reverted the update in 206590-wpcom. Can you confirm that that fixed it?

**Comment by samiff** [comment]
@obenland I'm able to see the color options now on my simple sites previously having the issue 👍

**Comment by obenland** [comment]
Fixed in 206590-wpcom.
