### ISSUE TITLE
My Home: Pull in blog posts for the Learn and grow section

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#41569]
We're still working on a list of blog posts and articles we want to show as a first pass so this might not be fully ready for implementation. But I wanted to get the ball rolling and start a discussion around how to implement.

The new layout for My Home has a section designated for pulling in educational content from the various blogs and resources we have available.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/448298/80556212-dcc6a500-89a0-11ea-831c-4f4b844acf79.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/448298/80556255-054e9f00-89a1-11ea-8ba4-84129f8c70dd.png">

The design may change slightly, but here's an overview of the constraints:

* We'll only show one blog post at a time.
* Each blog post will have a title, excerpt, thumbnail, and "read more" link.
* Posts will be pulled from wordpress.com/go to start, but we may want to use other blogs/resources in the future.
* We'll start with a set of general blog posts to randomly show. Further iterations will map the blog posts to the next task at the top of the page.
* Future logic could include something like: if there's a new post on wordpress.com/go that hasn't been shown yet, show it; else show a random post

**Comment by danhauk** [comment]
Here's a preliminary list of some general content that we can pull from for this section. I have them roughly segmented by stage of the site, but there's a lot of overlap that can happen.

Also, it's very likely existing established sites have not seen any of this content. So when we flip the switch to show this content on My Home, I'm not sure they need to be segmented. Thoughts?

**Create (Pre-launch and early post-launch)**
* https://wordpress.com/go/website-building/brand-voice-giving-your-business-a-personality/
* https://wordpress.com/go/website-building/worry-about-website-seo-tomorrow-launch-your-site-today/
* https://wordpress.com/go/content-blogging/the-new-website-checklist-what-to-include-before-you-launch/
* https://wordpress.com/go/content-blogging/content-promotion-101-share-your-blog-with-the-masses/

**Grow (early post-launch to 30 days)**
* https://wordpress.com/go/website-building/crushing-the-small-business-marketing-game-5-tips/
* https://wordpress.com/go/website-building/your-online-presence-starts-with-these-3-free-tools/
* https://wordpress.com/go/web-design/want-to-increase-website-traffic-own-it-and-earn-it/
* https://wordpress.com/go/web-design/online-lead-generation-finding-your-fan-base/
* https://wordpress.com/go/content-blogging/the-reality-of-seo-basics-focus-on-communication/

**Manage (30+ days? 60+ days?)**
* https://wordpress.com/go/solve/what-is-a-referrer-how-does-it-help/
* https://wordpress.com/go/web-design/building-an-audience-through-consistent-content-creation/
* https://wordpress.com/go/content-blogging/how-often-should-i-post-find-your-rhythm/

**Comment by jordesign** [comment]
Closing this based on redesign work
pbAok1-2L4-p2
