### ISSUE TITLE
Gutenboarding: set plan via URL param

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41576]
In Gutenboarding, it should be possible to set the plan via URL argument like so: `/new/PLAN_SLUG` where the slug is `free`, `personal`, `premium`, `business`, or `ecommerce`.

If it's better as `?plan=PLAN_SLUG`, go for it. I don't have a strong opinion about it. :-)

This way we can link and pre-select the plan via marketing pages such as [Pricing page](https://wordpress.com/pricing/).

The plan should get reflected in the plan badge in the header no matter what domain they have selected:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/87168/80570146-f8629780-8a02-11ea-8cd5-72e83435b444.png">

`/start` route has the same support.

@johnHackworth @dubielzyk @rickybanister should we store this "pre-selected" plan in site settings so that we could highlight the correct plan later on in plans grid, or it doesn't matter?

**Comment by dubielzyk** [comment]
We might wanna do it in the site settings as well since we'll eventually look at suggesting a plan based on the features they selected.

You could argue that we want site name and category as a URL param also so HE can send links to a certain step with prefilled information or make it easier for clients etc. Not sure how big this use case is though.

**Comment by rickybanister** [comment]
I think it makes sense to store. Continuity is important and we may find a novel way to use the info like @dubielzyk suggests.

**Comment by simison** [comment]
> Or we can just ignore it since we're showing the Free Plan by default anyway.

Yeah that's fine. It came from me seeing on EOF the marketing pages using it as a slug for `/start` flow. Ours can just default to it without explicitly setting it.
