### ISSUE TITLE
Premium Content: Update post stripe connection messaging

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41586]
The premium content block behaves a little different than the recurring payments button in that it saves you progress before you go to Stripe and it creates your first subscription for you. As a consequence, the stripe connection message is confusing because it tells you to add your first subscription and there's already a subscription created. For now, we can make the message generic so it works for both blocks but eventually, it might be good to standardize the behaviour.

Updated copy: Congrats, your site is now connected to Stripe. You can now start making money!

![obraz](https://user-images.githubusercontent.com/3775068/80579208-ecc69f00-8a09-11ea-8f14-8ee7a502e5c2.png)

**Comment by n3f** [comment]
Fix here: https://github.com/Automattic/jetpack/pull/15751
