### ISSUE TITLE
Premium Content: UI fixes ( spacing for subscription form, dropdown )

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41587]
We have extra spacing between the fields of the Add subscription form. Removing it cleans up the layout.

- [ ] We have extra spacing between the fields of the Add subscription form. Removing it cleans up the layout. ![obraz](https://user-images.githubusercontent.com/3775068/80579375-344d2b00-8a0a-11ea-9b98-7471b3f8ceb0.png)
![obraz](https://user-images.githubusercontent.com/3775068/80579410-45963780-8a0a-11ea-8137-c83651be49cf.png)

- [ ] Update the visible option in the dropdown so that it only shows the price while still showing the titles in the dropdown options? (See the screenshot),  Add 5px of spacing to the right of the subscription icon. 
![obraz](https://user-images.githubusercontent.com/3775068/80579510-71b1b880-8a0a-11ea-87f9-d829245a3b70.png)

- [ ] Hide subscription when Stripe isn't connected

![obraz](https://user-images.githubusercontent.com/3775068/80579789-e71d8900-8a0a-11ea-8876-8d652516570a.png)

- [ ] If you remove all the blocks from the subscriber view, it's hard to add any back in.

**Comment by eoigal** [comment]
PR to fix is here - https://github.com/Automattic/wp-earn/pull/98

**Comment by eoigal** [comment]
Fixed with https://code.a8c.com/D42792

**Comment by eoigal** [comment]
Sorry closed by mistake!
