### ISSUE TITLE
Premium Content: make it easy to convert existing content (group block?)

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41598]
Via @DavidRothstein 
https://wp.me/p58i-8VC

Converting already-created content into premium content was painful. This may be more a complaint about Gutenberg itself, but I had trouble figuring out how to transform existing content into premium content without a complicated copy-paste job. I can see that being annoying for real world users, who may write first and then classify as premium later.

![obraz](https://user-images.githubusercontent.com/3775068/80586023-96ab2900-8a14-11ea-8976-c802da9fdcd8.png)

**Comment by gwwar** [comment]
We can add a transform to the premium content block. We'll likely want to make this generic for blocks similar to the group transform.

https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#transforms-optional

https://github.com/WordPress/gutenberg/blob/e8b9de4c8e4ae83b8c3704a8247cdbe730642c6d/packages/block-library/src/group/index.js#L101

**Comment by gwwar** [comment]
There's both a subscriber and logged out view, should the transform work content -> subscriber view?

**Comment by artpi** [comment]
> There's both a subscriber and logged out view, should the transform arbitrary block content -> subscriber view?

Yes, let's dump all the content into subsriber view 👍

**Comment by mmtr** [comment]
@kwight [noted we could also support the opposite](https://github.com/WordPress/gutenberg/pull/22577#issuecomment-633662990): an ungrouping action that moves all the inner blocks out of the subscriber view and removes the Premium Content block.

It would be similar to the "Ungroup" button currently displayed on Group blocks:

<img width="457" alt="Screen Shot 2020-05-26 at 11 39 35" src="https://user-images.githubusercontent.com/1233880/82885699-c5e68480-9f45-11ea-8804-b4dd1b23be2e.png">

Do you foresee this could be useful for users?

In case the main motivation for implementing that feature is to allow users to undo unintentional transformations to Premium Content blocks, let's remember the "Undo" button is still there for reverting any transformation.

<img width="314" alt="Screen Shot 2020-05-26 at 11 44 18" src="https://user-images.githubusercontent.com/1233880/82886212-7f455a00-9f46-11ea-8bf1-433b9e8c79f7.png">
