### ISSUE TITLE
Recurring Payments notification:  "contact user@user" is not a mailto

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41599]
![obraz](https://user-images.githubusercontent.com/3775068/80586102-bb070580-8a14-11ea-9b0a-2a307b2b5da3.png)

**Comment by artpi** [comment]
Related: pbMlHh-5J-p2

**Comment by n3f** [comment]
Fix in D43678-code

**Comment by n3f** [comment]
Closed in phab above.
