### ISSUE TITLE
Add premium content block to the /earn screen

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41591]
There is no mention of the premium content block on the earn screen. Let's add one in and see if we can cleanup some things on that screen too.
- [ ] Add icon for Ads
- [ ] Add Premium content block mention

**Comment by artpi** [comment]
There is a certain challenge here in the terms where we really don'n know what the CTA should be.

**Comment by fditrapani** [comment]
Looks like we've made some updates and all the cards on the screen say "Unlock this feature" for free users:

![image](https://user-images.githubusercontent.com/6981253/81831086-edcbf600-950a-11ea-8722-133ab2f86643.png)

We can probably start with that.

**Comment by artpi** [comment]
I remember @davemart-in saying tha @danhauk is working on the CTA here :)

**Comment by fditrapani** [comment]
Yes, I was just throwing that out there since I still get notifications. Feel free to ignore it if you all come up with something else :)

**Comment by n3f** [comment]
Looks like this is related to #42371 as well.

**Comment by danhauk** [comment]
I think #42541 covered this by creating a new card for premium content:

![Earn section updates](https://user-images.githubusercontent.com/35781181/82603988-8f91b980-9b81-11ea-92aa-795cf6ca7a08.png)

**Comment by artpi** [comment]
> I think #42541 covered this by creating a new card for premium content:

I think so! Clsoing
