### ISSUE TITLE
Recurring Payments: Wrong amount in case of pay-what-you-want

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41593]
We offer "Pay what you want" option, which sets up subscription renewal price independently of the product set price.

But we show incorrect information in this case and we are also probably counting it incorrect.

Deliverable of this task: proper amount shows in emails, notifications, my subscriptions list, CSV export, and recurring payments dashboard

**Comment by eoigal** [comment]
Created patch to fix amounts shown in email and WP notifications - D43306-code

**Comment by eoigal** [comment]
This should fix the issue with misreporting of variable amounts on Calypso - D43336-code.

**Comment by eoigal** [comment]
This issue looks resolved to me. I looked into where we get the data for the monthly subscriber emails and the recurring payments dashboard and they both appear to be pulling the revenue data from receipts, which should be accurate.
