### ISSUE TITLE
Premium Content: Email subscriptions and Reader

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41608]
**Premium content doesn’t appear in emails sent to site followers. **

If I subscribe to follow the blog and also purchase a subscription, the emails I get when new blog posts are published display the logged-out view (i.e. no premium content). Ideally it would show me the premium content right in the email, if I have access to that. The “Subscribe” and “Log in” buttons do seem to work pretty well when clicked directly from the email (although the “Subscribe” button didn’t seem to actually grant me access until I subsequently logged in — related to my point number 3 above, I think).

This is the same case in the Reader

**Comment by eoigal** [comment]
Fix - https://github.com/Automattic/wp-earn/pull/99
