### ISSUE TITLE
Premium Content: Add support for multiple plans on one block

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41606]
Currently, Premium content block is 1:1 with subscriptions
But it would be neat to support multiple subscriptions, via checkboxes

p58i-8VC-p2#comment-46031

**Comment by artpi** [comment]
CC @n3f

**Comment by dcoleonline** [comment]
I'm not sure if this is the exact use case you had in mind, but a customer was using both a monthly and a yearly premium content block within the same post. They were copying the content from the yearly block and pasting it into the monthly block. Ideally, they could just have one block that subscribers could use regardless of their payment frequency.

21124210-hc

**Comment by artpi** [comment]
> I'm not sure if this is the exact use case you had in mind, but a customer was using both a monthly and a yearly premium content block within the same post.

This is PRECISELY the use case it was intended to solve. Thank you for reporting it @dcoleonline !

**Comment by khristiansnyder** [comment]
I had a user in chat today who has different plane tiers on their site: monthly & yearly.

Their goal was to have a Premium Content block, then be able to give access to customers of both plans, but the block only allows the selection of a single plan:

![Plans](https://user-images.githubusercontent.com/41035049/88824693-87ef2200-d17b-11ea-9130-733230f221d2.png)

The user made a great suggestion that we be able to select multiple plans for the block, and I agree that this seems like it would be a key feature as well.

> Can I humbly suggest multiple plans in the future? It feels like it would be a given

This came up in 23003544-hc

**Comment by ajaykj** [comment]
Another request about this came up in 23201578-hc. The user wants to have a monthly and a yearly plan added to the same content.

**Comment by artpi** [comment]
This came up from our WordPress.com summit organizers:

> As an additional feature request, the Premium Content block restricts content at a global level on the site. If a visitor goes through its paywall on one page, content anywhere else on the site within other Premium Content blocks are made visible. This functionality prevents the option of releasing different tiers or plans on a single site. If we’re looking to make the Premium Content block more feature-rich, it would be incredible to be able to specify whether the content within a particular block is only accessible locally through that block’s paywall, or if it’s accessible because it’s linked magically to another Premium Content block on the site. I see this as an option to select a global or local setting for the block.

**Comment by kwight** [comment]
This is a great idea, but let's do 185-gh-dotcom-manage first (move Premium Content to Jetpack, so it's with everything else).

**Comment by eoinsav** [comment]
Another request in #24322454-hc

This user was adding the same content to their Post twice. Once behind a monthly plan Premium Content Block and once behind an annual plan Premium Content Block.

**Comment by katiebethbrown** [comment]
Another instance here:

3396171-zd-woothemes

Similar use case to previous requests. User wants to offer both a monthly and yearly sub that gates the same content blocks. They had some nesting going on to try and accomplish this that wasn't working.

**Comment by nielslange** [comment]
Another report in 15180463-hc. Same use case as mentioned before: Offering both monthly and annual plans.

**Comment by poojashetty18** [comment]
Another report in 3448414-ZD. User wants to able to select multiple plans for the Premium Content block

**Comment by pauljacobson** [comment]
I also just received a request for this in 3535998-zen

**Comment by isocialtish** [comment]
Another request for multiple plans for the Premium Content block 26151350-hc

**Comment by tanjoymor** [comment]
Another customer who was expecting this feature to be a default: 20283288-hc

**Comment by marcuswisecaesar** [comment]
Another customer requesting that we offer grandfathering/multiple plans: 3804189-zd

**Comment by susanjanec** [comment]
Another customer who was trying to find out how to do this within the Content Premium block - 29372316-hc

**Comment by AtrumGeost** [comment]
+1 to this request. I was preparing a webinar video about this when I noticed this is not possible

**Comment by joweber123** [comment]
+1 for this request.  For an example use case, this user has two plans.  They would like to to give access to a limited number of posts to users of a cheaper plan but give access to all posts to users of the more expensive plan.  

For example:

1.)  If a customer pays $10 per month they can see the 10 newest posts
2.) If a customer pays $20 per month they can see these same 10 posts but also have access to the entire archive of posts.

**Comment by khristiansnyder** [comment]
Any movement on this? Had another request for this today in #9300897-hc

>Currently, I can only see a way to allow one subscription tier at a time access to the content using the premium content blocks. I have gotten around this by duplicating the block and setting up a separate log in for all three tiers in order to access the premium content. Is it possible to give all subscribers access to the same premium block of content no matter which plan they've subscribed to? Having duplicates of the same block makes the page look messy and complicates posting. 

>If this is not currently a function available on WP - it would be great if it could be added in as a customer suggestion, as I know several other users who are currently struggling with this same issue.

**Comment by khristiansnyder** [comment]
Any updates on if this may be looked into? Ran into another case today where a user has different levels of membership plans on their site. I informed them they would need to duplicate their premium content blocks for each membership.

#32145261-hc

**Comment by kwight** [comment]
@khristiansnyder This would fall under the Expand focus purview, but I've not seen any concrete plans yet (cc/ @ianstewart ).

**Comment by jp-imagines** [comment]
Had another user asking whether this was possible in 32521841-hc. (Same situation as above: they wanted to have a monthly and yearly subscription plan, and have both types of subscribers view the same content.)

**Comment by wpshellbelle** [comment]
Another case where this would have really helped a customer here: 32786856-hc

**Comment by essleeung** [comment]
Another case where the user wanted different tiers (e.g. Bronze, Silver, Gold) for Premium content. 25932351-hc

**Comment by NoHopeRadio** [comment]
Another case where this was expected and taken for granted that it was already in place: 4547730-zen

**Comment by edequalsawesome** [comment]
Also requested in 4695045-zen

**Comment by michaeldcain** [comment]
I've moved this to our inbox to discuss prioritizing it alongside the "not fixed by Woo blocks" issues.

**Comment by yashitamittal11** [comment]
Also, requested in #4877402-zen

**Comment by csabarakasz** [comment]
Here is another case where this would have been useful. 4942459-zd-woothemes

The user has two kinds of Premium content subscriptions: £4/ month and £5/ month (We don't know why...). When a user buys the £5 / month, but a post’s content is set to £4/ month, it won’t show up for them, even though they paid more, but technically it is a different subscription plan. 

It would be nice to be able to add multiple plan possibilities for one Premium content block, so people who paid 5 pounds could also look at the content that is marked as only 4 pounds, but not the other way around.

**Comment by jp-imagines** [comment]
Another request in 5466295-zd-woothemes 

Same as my last report: user wanted monthly and annual subscriptions to the same content. At the moment, this requires two Premium Content blocks, which means even subscribed users may see a prompt to subscribe from the other block, and unsubscribed users may see _two_ prompts to subscribe.

**Comment by daria2303** [comment]
I just want to mention that two Premium Content blocks don't work correctly on one page, based on 5466295-zd-wootheme, it results in subscribers seeing "guest view". Also, our doc suggests something different:
_You can add multiple subscription levels. For example, you can add bronze, silver, and gold tiers with increasing benefits for each one. Just keep in mind that a single Premium Content block can have just one subscription selected, so you would insert three Premium Content blocks in this scenario._

**Comment by Gustavo-Hilario** [comment]
Hi @daria2303. I've been checking this issue further on the follow-up ticket 5527617-zen, and I don't think CSS only can help to make sure subscribed users won't see the `Guest View` message for other plans. You can check the details on the Slack thread.

**Comment by daria2303** [comment]
I can see that I miss-understood the classes for the logged-in users, it even worked when I tested :D (I know why)  
Removed the CSS from my post not to confuse anyone.

**Comment by n3f** [comment]
Another one: 5738644-zd-woothemes

**Comment by artpi** [comment]
For the record, the work on the paid newsletters will solve that issue, since it will introduce the post-level controls.
The post will be accessible for EVERYBODY with a paid plan. By that time I expect demands to do the opposite: to introduce post level control plan selector.

**Comment by n3f** [comment]
Are we going to deprecate/remove the premium content block at that point?

**Comment by artpi** [comment]
>  Are we going to deprecate/remove the premium content block at that point?

No, I don't think so - there is still place for a more granular control of the content

**Comment by sophiegyo** [comment]
Chat 41837775-hc
Follow-up 6084020-zen

Context: user was migrating in from another provider and already had existing tiers with their current provider.
New paid newsletter tiers are not accessible yet.

**Comment by millerf** [comment]
LGTM!

**Comment by n3f** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/33903
