### ISSUE TITLE
Premium Content: When I add a new block, I see a blue line above the content area. It goes away if I click around

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41605]
When I add a new block, I see a blue line above the content area. It goes away if I click around. It appears something is being highlighted.
![obraz](https://user-images.githubusercontent.com/3775068/80602118-029a8b00-8a2f-11ea-95ac-49704bba8b27.png)

Per @eoigal 
 spent a while looking at this and this issue was introduced when WPCOM updated to version 7.8.1 of gutenberg. I tried to find a workaround however WPCOM is in process of moving to 7.9.0 and from what I can tell, this issue is fixed with that version - I think we should wait until that update.

p7DVsv-8tt-p2

**Comment by kwight** [comment]
Haven't observed this any time recently – closing.
