### ISSUE TITLE
Themes: navigation glitches on single theme details view

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#4161]
On the currently in-development Theme Sheet `/theme/$name` there are a few navigation glitches:

1) Back on the Theme Sheet page is triggered also when tabs change, instead of going to the previous navigational page. #5422

![cap-](https://cloud.githubusercontent.com/assets/4389/13891580/e11503b0-ed49-11e5-8ec2-fffb419cff67.gif)

2) If you open the single sites themes list, and navigate to ••• → Details, when switching tab the URL is reset without site. **Fixed**

![cap-2](https://cloud.githubusercontent.com/assets/4389/13891671/71b9a10a-ed4a-11e5-931a-682828188349.gif)

3) I'm not sure what's going on here. Logged out. Incognito window. Directly opened the URL (i.e. `/theme/veggie`). Click back: #5422

![cap-](https://cloud.githubusercontent.com/assets/4389/13891851/8999f5f8-ed4b-11e5-8586-af1f842365a4.gif)

_Aside: "Back" logged out should be "More Designs" (or something similar)._

4) Directly opening the site URL logged out (i.e. `/theme/veggie/details/ablacabraala.wordpress.com`) blanks. Should be stripping the site and going to `/veggie/details` (but also flashes content – SSR?):
**Fixed**

![cap-4](https://cloud.githubusercontent.com/assets/4389/13892052/b48352d6-ed4c-11e5-8731-767a32fbbcc0.gif)

**Comment by folletto** [comment]
Might be related: #4123

**Comment by seear** [comment]
All fixed.
