### ISSUE TITLE
Recurring Payments: Make sure slack error summary works

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41624]
We had slack error summary but it seems to not be posting
`async-jobs/includes/payments/recurring-payments.php`
We need to activate it to post to Earn channel

**Comment by eoigal** [comment]
Think I found the error digest here - `/public_html/async-jobs/includes/memberships.php`

**Comment by eoigal** [comment]
Fixed with https://code.a8c.com/D42792
