### ISSUE TITLE
Recurring payments: receipt after first purchase

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41620]
Once you go throuth the flow, you get first purchase email
But there is no receipt sent.
Receipt is sent with each renewal - but not first purchase

**Comment by artpi** [comment]
This is an example of a renewal receipt that is NOT sent during the time of first purchase:
<img width="722" alt="Zrzut ekranu 2020-05-26 o 13 23 50" src="https://user-images.githubusercontent.com/3775068/82895291-46ac7d00-9f54-11ea-83a4-f1af588cb6ff.png">

**Comment by n3f** [comment]
Diff for fix here: D44107-code

**Comment by n3f** [comment]
Merged and deployed
