### ISSUE TITLE
Payments Newsletter: do sign the user up.

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41629]
Project: 131-gh-Dotcom-roadmap

As part of creating paid newsletters, we have to sign user as site subscriber the same way we subscribe them to mailchimp. 

When `subscribe_as_site_subscriber` from https://github.com/Automattic/wp-calypso/issues/42272 is turned, on then, subscribe them here:

code . a8c . com /diffusion/WP/browse/trunk/wp-content/lib/memberships/class.membership-subscribers.php$50

We can use the same setting that shows the chexkbox the mailchimp does:
code . a8c . com /diffusion/WP/browse/trunk/wp-content/lib/memberships/class.memberships-checkout-form.php$150

![obraz](https://user-images.githubusercontent.com/3775068/82058433-0a139280-96c5-11ea-95df-109917bd1efd.png)

GDPR concerns are already addressed in #41597 - double check on this.

**Comment by artpi** [comment]
Something to monitor here is : p58i-8VC-p2

**Comment by artpi** [comment]
related https://github.com/Automattic/wp-calypso/issues/42272

**Comment by mmtr** [comment]
D43908-code should close this once it lands. It displays the newsletter checkbox in the subscription form when the plan has the option for auto-subscribe set.

**Comment by mmtr** [comment]
Closing this one out since D43908-code has landed. Once a new FSE plugin version is released, the whole flow should be testable in production.
