### ISSUE TITLE
Recurring Payments / Premium Content: Tracks for block setup

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41631]
We need a following funnel for recurring payments / premium content:

1. Drops a block into the editor
2. Clicks upgrade
3. Returns
4. Clicks Stripe upgrade nudge
5. Returns
6. Sets up a product
7. Publishes a page

We think this process will be arduous. The problem is that the current stats are not good, but we should be able to use memberships/status endpoint to pass the unique user id to track it.

Also:
- [ ] Log WPCOM_JSON_API_Connected_Account_Stripe_Connect_Oauth_Redirect_Endpoint response

**Comment by davemart-in** [comment]
I'm not sure about the "Returns" events, but we should be able to ensure that we have tracks events for everything else. Then it's just a matter of creating a tracks funnel.

**Comment by artpi** [comment]
Important note for the first step: the block always loads an endpoint for status to see your stripe connnection, so we can use that

**Comment by artpi** [comment]
Note from @gwwar : we can drop 3 and 5 steps

**Comment by kwight** [comment]
Looking into this today, a few notes.

The only existing Tracks data I can find related to Recurring Payments (or any Jetpack blocks, for that matter, unless I'm missing something) are the `wpcom_block_publish` and `wpcom_block_edit` events, each storing the `block_name`. The block itself also doesn't seem to have any (PHP) hooks.

On both Simple and Atomic sites we have access to the `wpcomGutenberg` object; we could hang user and blog IDs here for use by another script that we have handle the calls to `window._tkq.push()`. I don't know if it's best to just add a small inline script, or hook something to Gutenberg's own `wp.editor.blockEdit` [filter](https://developer.wordpress.org/block-editor/developers/filters/block-filters/).

> Important note for the first step: the block always loads an endpoint for status to see your stripe connection, so we can use that

I haven't looked a this yet, but if we can avoid adding stats requirements to other endpoints, we can keep them cleaner.

**Comment by gwwar** [comment]
@kwight Don't forget that we decorate editor actions in https://github.com/Automattic/wp-calypso/blob/30e13fd2564a83ae71098624d7680c71ce06544a/apps/wpcom-block-editor/src/wpcom/features/tracking.js#L201

**Comment by artpi** [comment]
> I haven't looked a this yet, but if we can avoid adding stats requirements to other endpoints, we can keep them cleaner.

This is an endpoint built specifically for this block, but if we have other options -that is great :)

**Comment by kwight** [comment]
Did some digging and got a start (lots of help in PCYsg-nrf-p2).

**Recurring Payments**
* Drops a block into the editor: `wpcom_block_inserted > block_name: "jetpack/recurring-payments"`
* Clicks upgrade: `wpcom_block_recurring_payments_upgrade_click`
* Clicks Stripe upgrade nudge: 
* Sets up a product:
* Publishes a page:

**Premium Content**
* Drops a block into the editor: `wpcom_block_picker_block_inserted > block_name: "premium-content/container"`
* Clicks upgrade: `wpcom_block_premium_content_upgrade_click`
* Clicks Stripe upgrade nudge: 
* Sets up a product:
* Publishes a page:

Events that are not already established will be handled in https://github.com/Automattic/wp-calypso/pull/42734.

**Comment by kwight** [comment]
Between the three PRs above, this is all taken care of 👍

**Comment by kwight** [comment]
Everything above is merged and active except the JP PR. We've just missed 8.6, so it'll be a few weeks before 8.7 (this applies only to JP sites; Simple sites will count properly as of today).

I've set up two funnels: `Recurring Payments full flow` and `Premium Content full flow`.
