### ISSUE TITLE
Reader: Followed site email setting changes after a refresh

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#4164]
#### Steps to reproduce
1. Go to Manage Following and add a new site to follow
2. Once this site has been added, the email setting for "Emails for new posts" appears to be `OFF`:
   ![screenshot 2016-03-18 14 32 01](https://cloud.githubusercontent.com/assets/4924246/13892773/e345d5ca-ed16-11e5-86e2-403002c04020.png)
3. When you refresh the page, this setting changes to `ON`:
   ![screenshot 2016-03-18 14 32 09](https://cloud.githubusercontent.com/assets/4924246/13892774/e5e25236-ed16-11e5-8d86-45a045ec7577.png)

Note: We should also be more explicit whether or not we turn on email notifications for users upon subscription, especially that it's not really obvious that there's a Reader Subscription page elsewhere which defaults to `ON`. Will tackle this part in Manage Following i2.
#### What I expected

That this setting defaults to `ON` (or `OFF` depending on the user's settings in Reader Subscriptions) and stays that way unless the user changes it
#### What happened instead

Setting defaults to one thing and changes after a refresh
#### Browser / OS version

Chrome Version 48.0.2564.1 / Mac 10.11.3

**Comment by alisterscott** [comment]
I noticed this today - well the way I noticed it was I received an email saying I was subscribed via email - which I didn't want to be, and I looked at that page and it showed I wasn't. So I refreshed and saw that I was.

I would prefer to default email to `OFF` instead of `ON` because to me the point of Reader is avoid inbox overload.

**Comment by jancavan** [comment]
@alisterscott This is confusing, but the toggle slider's default setting also depends on what setting you have on https://wordpress.com/me/notifications/subscriptions

So if you have "Send email instantly" active, the toggle slider for every new subscription will be `ON` by default.

**Comment by alisterscott** [comment]
@jancavan: Thanks! I didn't realise that setting was there. I've changed that now so should be all good.
One thing I did notice that when I subscribed via the "Follow" functionality on a blog, even though my setting was "Send email instantly", it defaulted to `OFF`, whereas manually adding a WP.com blog via the reader defaulted to `ON`.

**Comment by jancavan** [comment]
@alisterscott thanks for the heads up. For this bug, the setting actually changes from one thing to another after a refresh. Do you know if that's the case with what you had mentioned?

**Comment by alisterscott** [comment]
This bug only happens when your default email setting is enabled. When it's disabled the toggle always shows OFF before and after refresh as expected

**Comment by jancavan** [comment]
@alisterscott Right, because I think the toggle is always off regardless of your /me Settings. So when your email Settings are off, there isn't a need to change state.

**Comment by lancewillett** [comment]
I wasn't able to repeat this — let's re-open if it occurs again in the future.

**Comment by jancavan** [comment]
Re-opening issue. I can still confirm this is happening: https://cloudup.com/cA7D-yqbKsr

**This is what happens:**

1. In Manage, I add a new site to Follow.
2. After this site has been Followed, its "Emails for new posts" setting shows that it's OFF (if I want it off, it'll make me think that I actually don't need to alter anything in the settings... only to get a bunch of emails later).
3. If I refresh the page, this setting shows that it's actually ON.

**Comment by davoraltman** [comment]
I was able to reproduce this issue. Also reported in 3113489-t

**Comment by bluefuton** [comment]
Doesn't appear to be an issue any more in the revamped Manage Following 👍
