### ISSUE TITLE
Gutenboarding: redirect to editor after emptying checkout cart

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#41652]
## Description

At the moment, when a user clears their cart, [we redirect them back to plans](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/index.jsx#L314)

![checkout-redirect](https://user-images.githubusercontent.com/6458278/80663911-ae4be580-8ad8-11ea-9486-287dc99b5c41.gif)

For Gutenboarding `prelaunch` and `new-launch` (previously known as _Frankenflow_) flows, when a user empties their cart we could return them to the editor.

It looks like [we're passing down information to Checkout when arriving from a Gutenboarding flow](https://github.com/Automattic/wp-calypso/blob/2e2bdda/client/my-sites/checkout/checkout-system-decider.js#L93).

We could pass those props down and update `redirectIfEmptyCart()` to behave accordingly?

First identified in https://github.com/Automattic/wp-calypso/pull/41205

## Steps to reproduce

1. From `/new` select a paid domain
2. Create a site and head to checkout
3. Empty your cart
4. You're taken to Calypso plans

Also

1. From `/new` create a free site and head over to the editor
2. Click on Update to launch your site
3. Select a paid plan
4. Empty your cart
5. You're taken to Calypso plans

**Comment by simison** [comment]
I think editor would make sense, if it's possible with the current checkout step. They'll just be on free site but our goal is still to get them quickly see and edit their site.
