### ISSUE TITLE
Recent posts block's convert button cuts off

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41658]
When editing a page with Posts list block (`<!-- wp:a8c/posts-list {"postsPerPage":2} /-->`), I see this:

<img width="769" alt="Screenshot 2020-04-30 at 10 56 59" src="https://user-images.githubusercontent.com/87168/80686463-6b3a4400-8ad1-11ea-8194-e93ad91322c0.png">

Note how the button is cut out.

Site `gutenboardingdemo.home.blog` and theme Maywood. Browser Firefox.

cc @Automattic/ajax

**Comment by frontdevde** [comment]
**Dotcom Manage Janitor Rotation note Jun 17, 20**
We looked at this during a pairing call and discovered that disabling `flex-shrink` for the button fixes the issue. @cpapazoglou will follow up on this and get a PR ready.

**Comment by cpapazoglou** [comment]
**Dotcom Manage Janitor Rotation note Jun 18, 20**
Fixed in #43426 and will be in FSE Release 1.11
