### ISSUE TITLE
composite-checkout: Make domain names for registration/mapping/transfers visible after first step

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#41650]
Right now after completing the review step of checkout when a domain registration, mapping, or transfer is in the cart, the domain name itself is no longer displayed.

This was sort of a regression when we removed the domain name from the summary header.

Perhaps a better UX would be to add the domain name to the inactive view of the first step, so that instead of just reading "Domain Registration", it had a second line that displayed the domain name being purchased.

**Comment by michaeldcain** [comment]
Closed in #41688
