### ISSUE TITLE
Progress Bar: improve design so the bar is more visible

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#41685]
> I saw this, and didn’t realize it was a status bar at first:

<img width="841" alt="Screen Shot 2020-04-29 at 10 17 55 AM" src="https://user-images.githubusercontent.com/426388/80738856-de65a980-8b15-11ea-8a68-861b17e36fd1.png">

Would it be possible to iterate on the design of this bar to make it stand out a bit more?

cc @beaulebens who originally reported this.

**Comment by beaulebens** [comment]
I realized as soon as the status bar/animation started, so I think the easy solution would be to just start it out at "10% complete".

**Comment by Aurorum** [comment]
PR for the above suggestion in #42940. :)
