### ISSUE TITLE
My Home: Add a "task" card for domain transfer

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#41702]
When a user purchases domain transfer, we display a notice to inform them that they need to complete setting it up:

**In /plans, /domains, /email:**
![image](https://user-images.githubusercontent.com/4924246/80765235-61c3d280-8af7-11ea-97a8-5e547b04b5ea.png)

This means the user has purchased a domain transfer during checkout, but has not begun the transfer process.

We need to:

- Display this as a "task" card in Customer Home
- We can retain the notice in /plans, /domains, and /email for now until it gets replaced by the new styles from the site-wide notices work

![Screen Shot 2020-04-30 at 3 30 55 PM](https://user-images.githubusercontent.com/4924246/80765328-a0f22380-8af7-11ea-8838-cba08478c951.png)

Please note that:

- This still needs an illustration
- Copy will still need to be reviewed/updated

cc @danhauk @lcollette

**Comment by jordesign** [comment]
This is a fantastic suggestion.

In terms of the 'My Home' pod - I think this example sets a great precedent of the kinds of tasks we should highlight for users as a 'Next Step' for certain processes.

I can imagine it might also be helpful for when users have mapped a domain but not yet pointed the domain Name Servers here

It's less about pushing them to do something new - and more about helping them complete something they've already indicated they want to do.

**Comment by autumnfjeld** [comment]
@jancavan this issue is a year old.  Just wondering who would be responsible for completing the illustration and design?  Also checking that this still a valid request for customer home?  Thank you.😃

**Comment by jordesign** [comment]
Jan's no longer at A8C so this is something we'd need to do ourselves - making sure it aligns with:
PCYsg-quF-p2

**Comment by jordesign** [comment]
I'd argue for incluion of this action/prompt (to complete transfer) *but* if our main task cards are now suffling/random then its likely it will get lost.

The importance of this action is such that perhaps it should be considered in another fashion?

**Comment by autumnfjeld** [comment]
I think this will be part of the My Home Status area, is that correct @jordesign @jeffgolenski ?

**Comment by jeffgolenski** [comment]
@autumnfjeld Yes indeed!

**Comment by autumnfjeld** [comment]
I'm going to close this, given that The My Home Pod is in the midst of [active design work](fLQcNzdadWzo87n89Imecj-fi-2049%3A0) to create a space on My Home to inform user about [site status](p1623888333263900-slack-C01VA0R5NKY), including domain status. 🥇
