### ISSUE TITLE
Theme Showcase: Add Feature `Footer Menu`

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#41709]
It would be great to add `Footer Menu` as a feature filter in the theme search to be able to see all themes that do support that menu location. Currently, we only have `Classic Menu`, `Custom Menu`, and `Fixed Menu` as filters.

#### Screenshot
![](https://d.pr/i/0hrjRS+)
_Link: https://d.pr/i/0hrjRS_

#### Context / Source

#empathy #perspective #reallife #painpoint #user-report 2913311-zen

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

This issue has not had any activity within the last 10 months. As such, this issue it is being closed with the label `Closed - Won't Fix`.
If this issue should remain open, please feel free to re-open this bug.
