### ISSUE TITLE
Editor: Doesn't load in Safari (Atomic sites)

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#41725]
Appears to be a gutenframe issue; editor loads directly in wp-admin.

#### Steps to reproduce
(on Atomic site in which your user is set to use block editor)
1. Starting at URL: https://wordpress.com/pages/
2. Click Add New Page, or on a page to edit it

#### What I expected
Editor to load as normal

#### What happened instead
Some grey things flash at the top left and the editor never loads

Console shows error: `Failed to load resource: Load cannot follow more than 20 redirections` (links to wp-admin for the site)

#### Browser / OS version
(these are mine, didn't check the users')
Safari 13.1
Mac OS X 10.15.4 

#### Screenshot / Video
<img width="1552" alt="Screen Shot 2020-05-02 at 4 05 18 pm" src="https://user-images.githubusercontent.com/2031017/80857163-42fa4300-8c93-11ea-8360-22c20a69ca32.png">

#### Context / Source
#user-report 20766049-hc
Follow-up: 2937620-zd

**Comment by arunsathiya** [comment]
Adding to `Calypso Gutenberg integration` to make sure it's tracked.

**Comment by kristarella** [comment]
Another report #19675005-hc

**Comment by simison** [comment]
<img width="509" alt="Screenshot 2020-06-08 at 11 21 21" src="https://user-images.githubusercontent.com/87168/84008971-3c8a7580-a97b-11ea-99ed-77ac3cb13099.png">

Safari gets stuck with infinite redirects:

`redirect`:
```
URL: https://******/wp-login.php?action=jetpack-sso&result=success&user_id=******&sso_nonce=******
URL: https://******/wp-admin/
URL: https://******/wp-login.php?redirect_to=https%3A%2F%2F******%2Fwp-admin%2F&reauth=1
URL: https://jetpack.com/redirect?source=wpcom-login&site=******&query=action%3Djetpack-sso%26site_id%3D******%26sso_nonce%3D3******%26calypso_auth%3D1
URL: https://jetpack.com/redirect/?source=wpcom-login&site=******&query=action%3Djetpack-sso%26site_id%3D******%26sso_nonce%3D3******%26calypso_auth%3D1
```

`wp-login.php`:
```
URL: https://wordpress.com/wp-login.php?action=jetpack-sso&site_id=******&sso_nonce=******&calypso_auth=1&site=******
```

...when opening editor for Atomic site in the editor iframe. It did work on first try tho — not sure why on 2nd attempt it failed.

**Comment by formosattic** [comment]
Another report, 21993461-hc.

Had them editing from WP Admin, which worked!

**Comment by donalirl** [comment]
Another report in #12409645-hc

**Comment by cathymcbride** [comment]
This should be fixed per https://github.com/Automattic/wp-calypso/issues/43068
