### ISSUE TITLE
Activity log: 

### ISSUE THREAD

**Issue by megosagie** [Automattic/wp-calypso#41728]
#### Steps to reproduce

1. Starting at URL:https://wordpress.com/home/megiyesogieosagie.sport.blog
2.
3.
4.

**Comment by arunsathiya** [comment]
Hey, @megosagie. Your report seems to be incomplete. Did you mean to report an issue with the Calypso project? 

If you are looking for WordPress.com support instead, you can get started here: https://wordpress.com/help/contact
