### ISSUE TITLE
[Navigation block] Sub-menu items added via Navigation block are not clickable

### ISSUE THREAD

**Issue by yamphoenix** [Automattic/wp-calypso#41737]
The submenu items added via Navigation block are not clickable if the menu items overlay with the Cover block.

#### Steps to reproduce

1. Add a menu via the Navigation block on FSE enabled site. 
2. Add 4-5 submenu items 
3. Add a Cover block at the start of the page.
4. The menu items that overlay the Cover block are not clickable.

#### What I expected
I expected all the sub-menu items to work correctly.

#### What happened instead
The submenu items that overlay the Cover Block are not clickable.

![Submenu Items](https://d.pr/i/qiuGCO+)

#user-report
Issue reported in chat: #20616282-hc
We have shared CSS with the user for a temporary fix.
Slack: https://a8c.slack.com/archives/C4WC5LYM6/p1588569638191600

**Comment by Gustavo-Hilario** [comment]
In case this can help another HE that comes across this, I found this issue on another site, but after some testing, I found that it was actually caused by the `CoBlocks` plugin. Deactivating it should fix this issue.
