### ISSUE TITLE
Editor: Remove toolbar left border when floating

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4173]
We should remove the 1px left border from the editor toolbar when it's floated to the top of the screen:

![image](https://cloud.githubusercontent.com/assets/227022/13896448/8494b08a-ed59-11e5-8d0f-7d729f0afaf1.png)

---

![image](https://cloud.githubusercontent.com/assets/227022/13896449/86803090-ed59-11e5-961f-226570cf7a7f.png)

**Comment by sendilkumarn** [comment]
#4375  Updated with proper tabs. Please check @nylen

**Comment by nylen** [comment]
From https://github.com/Automattic/wp-calypso/pull/4176#issuecomment-199708229 - we should probably remove the right border as well.

![image](https://cloud.githubusercontent.com/assets/227022/13946535/2fd531dc-efe3-11e5-8655-18db06dc829c.png)

**Comment by nylen** [comment]
Fixed in #4375.
