### ISSUE TITLE
Web/Desktop: Discrepancy in Jetpack sites

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#4174]
In short: if I open WordPress.com in my browser I see a list of sites that includes all the Jetpack sites I have connected. If I open the desktop WordPress.com app I only see some of the Jetpack sites. I've tried to restart the application to no avail.

#### What I expected
To see all my Jetpack sites consistently.

#### What happened instead
I didn't see all my Jetpack sites.

#### Browser / OS version
Chrome 49
WordPress.com 1.3
Mac OS X 10.11.3 (El Capitan)

#### Screenshot / Video

In browser:
<img width="279" alt="screen shot 2016-03-19 at 12 09 49" src="https://cloud.githubusercontent.com/assets/3073557/13896772/a3540102-edcb-11e5-9cb5-48e233f488de.png">

In desktop WordPress.com app:
<img width="281" alt="screen shot 2016-03-19 at 12 10 01" src="https://cloud.githubusercontent.com/assets/3073557/13896769/8d3f6e06-edcb-11e5-9362-fafe1a7e8f9c.png">

**Comment by mtias** [comment]
@isaackeyet hey :) Do you happen to have 12 sites in total?

**Comment by isaackeyet** [comment]
Yes, I think 12 sites are visible.

**Comment by mtias** [comment]
That was fixed in #3780 but it hasn't trickled down to desktop app yet, there should be a release soon.

**Comment by lancewillett** [comment]
This has been fixed and Jetpack sites are showing consistently in (most) apps — Android is still a bit behind, see https://github.com/wordpress-mobile/WordPress-Android/issues/3023
