### ISSUE TITLE
My Home: Dismissal handling is fragile when adding new cards.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#41758]
Dismissal of Task cards in the primary location is handled automatically by the Task component, which [composes](https://github.com/Automattic/wp-calypso/pull/41570#issuecomment-623608362) the preferences key based on the card's `taskId`. On the server, we also compose the preference to check, based on a map of constants. When the two keys match, we can accurately determine dismissal; if the keys do not match, the card will never be considered dismissed. This is rather fragile, as an typo in Calypso or server-side will only be discovered during proper manual testing.

Some sort of canonical mapping used by both sides would reduce errors and remove the need for the developer to think about it.

**Comment by gwwar** [comment]
We already map string UIDs to components in the locations. The `taskId` attribute does this a second time, and if folks don't understand the convention will cause dismissals to not work properly.

There are a lot of ways that we might tidy this, but whatever we pick I recommend that we only map a string to a component **_once_** on the client.
