### ISSUE TITLE
My Home: Remove old layouts

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#41776]
If https://github.com/Automattic/wp-calypso/pull/41712 lands and is stable, let's remember to remove old layouts and remove the experimental flag from code.

**Comment by Aurorum** [comment]
I'll try to spin up a PR for this. :)

**Comment by mmtr** [comment]
Sorry @Aurorum! I already started to work on this but forgot to assign myself 🙁 I should have the PR ready for review in a few mins (it will also require some server-side changes).

**Comment by Aurorum** [comment]
Oops, just saw this as I was about to create a PR! If it helps, I've finished a branch in https://github.com/Automattic/wp-calypso/compare/master...Aurorum:remove/home-old-layout?expand=1. :)

**Comment by mmtr** [comment]
Thanks @Aurorum. Seems we both did pretty much the same 🙂: https://github.com/Automattic/wp-calypso/pull/41855

Main difference in my PR is that I also dropped the `experimental` query param passed to the API, which is only possible once D42999-code lands (this is a internal server-side changeset).
