### ISSUE TITLE
Customizer: Launch site button does nothing 

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#41772]
#### Steps to reproduce
1. Create a new site, but do not launch it yet
2. Visit Customize
3. Notice there's a Launch Site button in Customize. It does nothing if you click on it.

#### What I expected
Launch site probably shouldn't show up there, since it would take the user out of the Customize flow and distract from the Save Changes button they need to pick.  But if it does show up there, it should probably work.

#### What happened instead
The Launch Site button is unresponsive.

#### Browser / OS version
Chrome / Windows 10

#### Screenshot / Video
![wordpress_woes](https://user-images.githubusercontent.com/3476361/81020948-3eff2a00-8e27-11ea-9272-2e42e6758699.jpg)

#### Context / Source
My kid was tinkering around with a new site this weekend and noticed this.

But I've also seen quite a few users complaining of being unable to launch the site in the forums. It seemed pretty straightforward to us, so I couldn't figure out why they were having trouble until my kid pointed out the UX issue.

https://wordpress.com/forums/topic-tag/site-launch/
https://wordpress.com/forums/topic-tag/launch-site/

**Comment by simison** [comment]
> Launch site probably shouldn't show up there, since it would take the user out of the Customize flow and distract from the Save Changes button they need to pick. But if it does show up there, it should probably work.

I agree just hiding it for now would be best. We might want to add it there later but we need to think about how interactions should look like (i.e. save before exit).

FYI @olaolusoga @johnHackworth @joanrho @dubielzyk

**Comment by sirreal** [comment]
D42920-code has a proposed fix for this, hiding the banner in the customizer.

**Comment by Addison-Stavlo** [comment]
the fix from D42920-code has been deployed.
