### ISSUE TITLE
My Home: Revise CTAs on Add menu step of checklist.

### ISSUE THREAD

**Issue by lcollette** [Automattic/wp-calypso#41775]
Let's add clearer calls to action for Adding a menu, the current bu. This will help reduce friction for completing this action.

Current CTA is "View Tutorial" that opens an inline help article, with a second CTA of "Go to the Customizer"

| Current Add a Menu Step  | Support Article |
| ------------- | ------------- |
|  <img width="1431" alt="Screen Shot 2020-05-04 at 4 50 35 PM" src="https://user-images.githubusercontent.com/1270189/81024267-c9e02480-8e27-11ea-90f0-cb787dafd5a0.png"> | <img width="1192" alt="Screen Shot 2020-05-04 at 4 50 40 PM" src="https://user-images.githubusercontent.com/1270189/81024290-d8c6d700-8e27-11ea-85fd-da9382bdc01f.png"> |

Let's update this instead to the following:

- [ ] Change "View Tutorial" to "Add a menu" which takes us to the customizer menu
- [ ] Add a "View Tutorial" link in the description

<img width="1556" alt="Screen Shot 2020-05-04 at 4 48 27 PM" src="https://user-images.githubusercontent.com/1270189/81024353-0875df00-8e28-11ea-8090-a1684e1a46ce.png">

**Comment by Aurorum** [comment]
PR in #41791 for this issue. :) 

<img width="1133" alt="Screenshot 2020-05-05 at 08 50 17" src="https://user-images.githubusercontent.com/43215253/81045357-efb00c80-8ead-11ea-93ef-a582a633a160.png">
