### ISSUE TITLE
My Home: Drop illustration at <800px

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#41778]
![Screen Shot 2020-05-04 at 6 12 55 PM](https://user-images.githubusercontent.com/4924246/81027952-6d373680-8e34-11ea-94f7-4ec03ebe7c89.png)

Drop the image at <800px, but display it again on mobile. As you can see in the screenshot, it looks imbalanced with the shrunken image.

cc @danhauk

**Comment by kwight** [comment]
As mentioned by @mmtr , this will only happen when physically resizing the viewport; loading a page under 960px (the breakpoint used by [`isDesktop()`](https://github.com/Automattic/wp-calypso/blob/86c10aa25e1540d03bf2c839510835e52d68eec0/client/my-sites/customer-home/cards/tasks/task.jsx#L127-L131)) will not display the image:

<img width="397" alt="Screen Shot 2020-05-05 at 2 16 02 PM" src="https://user-images.githubusercontent.com/349751/81117578-2ef55200-8edc-11ea-8435-3fe1ff45b9e5.png">

He also mentions an option to possibly make manual resizing work, but it doesn't sound worth it at this point:

> we have a subscribeIsDesktop listener which we could use to make isDesktop aware of windows resizes, but I think we don’t include it by default for performance reasons: https://github.com/Automattic/wp-calypso/blob/86c10aa25e1540d03bf2c839510835e52d68eec0/packages/viewport/src/index.js#L177

**Comment by jancavan** [comment]
No worries @kwight. I'll close this one out.
