### ISSUE TITLE
Gutenboarding: plans grid

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41787]
This is going to be a bigger one and contains several sub-tasks.

- [ ] Implement plans grid for mobile
- [x] Implement plans grid for desktop
- [x] Open plans grid from "plan" button in the header (behind feature flag first) @razvanpapadopol 
- [ ] Show plans grid in the flow instead of Calypso one when purchasing a premium domain - WIP https://github.com/Automattic/wp-calypso/pull/42028
- [x] Implement a data store that pulls in current Calypso stores (?)
- [ ] _Add more_

Spike PR: https://github.com/Automattic/wp-calypso/pull/41284

## Currently, in use for Gutenboarding, Calypso plans grid re-skinned:

<img width="600" alt="Screenshot 2020-05-05 at 09 07 18" src="https://user-images.githubusercontent.com/87168/81038986-6d751780-8eb0-11ea-9da9-14684d286c26.png">

<img width="214" alt="mobile" src="https://user-images.githubusercontent.com/87168/81038995-71a13500-8eb0-11ea-8ff4-b8c417d3a2b1.png">

#### Free domain

<img width="1449" alt="Screenshot 2020-05-05 at 09 08 19" src="https://user-images.githubusercontent.com/87168/81039067-ac0ad200-8eb0-11ea-8ee2-91468cf47832.png">

- Clicking domain opens the domain dropdown

#### Paid domain

<img width="1450" alt="Screenshot 2020-05-05 at 09 08 43" src="https://user-images.githubusercontent.com/87168/81039076-b4630d00-8eb0-11ea-802f-a909fe498d33.png">

- Clicking domain opens the domain dropdown

#### Mobile version

<img width="285" alt="Screenshot 2020-05-05 at 09 08 35" src="https://user-images.githubusercontent.com/14192054/81072559-fe6ae380-8eee-11ea-9e0b-1ed2fd24d158.png">

- Let's try lightly implementing a slider and see how much work it is
- If it's complex to fit in a week, we can do more lightweight (possibly stacked) first version for the release

#### Detailed features accordion

<img width="614" alt="Screenshot 2020-05-05 at 09 09 11" src="https://user-images.githubusercontent.com/87168/81039116-cb096400-8eb0-11ea-863f-932aa005a97c.png">

- Does it animate?
- How does it behave on mobile / tablets?

cc @dubielzyk

**Comment by razvanpapadopol** [comment]
Just a note regarding the labels (and translations) we are using for the WordPress.com plans:  we should probably think of brand consistency even if the designs are showing different things (eg: we have _Personal_ / _Personal Plan_ or _eCommerce_ / _Commerce_). Here is a recent example: https://github.com/Automattic/wp-calypso/pull/41679#discussion_r418371612

**Comment by simison** [comment]
Work on this is happening across these 3 PRs right now:
- simple componentry https://github.com/Automattic/wp-calypso/pull/41864
- "container" for the grid and opening it from the header https://github.com/Automattic/wp-calypso/pull/41857
- pulling in the data via store https://github.com/Automattic/wp-calypso/pull/41856

We'll work on combining these into a feature over Thursday.

@Automattic/ganon do you have thoughts on how to plug analytics into plans grid and if any work for it could already be started? Considering that we'll want to bring the plans grid to wp-admin and challengees to do so with domains modal are highlighted in pbAok1-HS-p2#comment-1635

Reviews on the direction for any of the PRs welcome, too!

**Comment by ramonjd** [comment]
> @Automattic/ganon do you have thoughts on how to plug analytics into plans grid and if any work for it could already be started? 

Can we import `@automattic/calypso-analytics` into whatever cross-platform bundle we create?

I'm probably missing some subtleties here, but I can't see a reason not to.

If so, then the "how" is solved and it's just a matter of deciding what you need to track. And we're only tracking enter/leave/open/close events for pages and modals, so implementation would be quick once the components are ready.

If not, then the stats library window._tkq is also loaded in wp-admin, so, if necessary we could implement a (supplementary) pared-down analytics lib for either the plans grid or, if we have to, for Gutenboarding itself.

> Considering that we'll want to bring the plans grid to wp-admin and challengees to do so with domains modal are highlighted in pbAok1-HS-p2#comment-1635

The domains modal tracking (Traintracks) is another tracks call with extra props, so it's really nothing special. The concern I believe is finding the right hook to fire the event (?)

Also replied in: pbAok1-HS-p2/#comment-1678

**Comment by ramonjd** [comment]
> Show plans grid in the flow instead of Calypso one when purchasing a premium domain

@p-jackson has a draft PR going on https://github.com/Automattic/wp-calypso/pull/42028

**Comment by ramonjd** [comment]
Making a start on mobile layout https://github.com/Automattic/wp-calypso/pull/42029
