### ISSUE TITLE
Improvements to Calyspo Revisions for Accessibility

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#41785]
#### Steps to reproduce

Using a screen reader like Apple Voiceover, attempt to load a previous revision of a page or post.

#### What I expected

I expected to be able to swipe left to right with a screen reader through the available revisions, select one revision, and load it onto the page.

#### What happened instead

Due to unclear labelling, it's virtually impossible to load a revision with a screen reader. Each revision is labelled as "button" without a clear indication of what the button does. A visually-impaired user can find the Load button, but it's not clear how to first select a previous revision.

This can be achieved with more detailed and accurate labelling on the buttons for screen readers.

#### Screenshot

https://d.pr/i/4igXVN

#### Browser / OS version

**Desktop**
Mac Catalina  with Safari 13 using Apple Voiceover

**Smartphone**
 - Device: iPod Touch
 - Browser: Safari Latest
 - Screen reader: Apple Voiceover

#### Context / Source

#p4vt7e-6n-p2

#journey #empathy #livesharing #accessibility #painpoint #user-report

**Comment by getdave** [comment]
Maybe it should prefer alt text if set, but if not set or empty string it should set the `alt` on the `<img>` to

```
No image description available. Filename is: ${filename}
```

**Comment by sixhours** [comment]
When I access the revisions area with Voiceover, I'm read the date, author, and number of changes (words added, words removed) when targeting each of the revision buttons:

https://user-images.githubusercontent.com/2124984/128411872-512db571-fa8b-4f6b-a9b0-339a19be080c.mov

Same for my iPhone using taps/double-taps. I don't see any changes in Calypso that might have accounted for this, and it appears these buttons have had `aria-label`s for a long time. I wonder if it's a difference in how Voiceover works on mobile devices now. 

Closing as fixed, but as always, please reopen if I've missed something!
