### ISSUE TITLE
Gutenboarding: Cursor blinks in wrong location

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#41795]
When using a language with a long translation, such as German, the cursor blinks at the end of the line, while the example text appears in the next line:

![gutenboarding-long-text](https://user-images.githubusercontent.com/203408/81053796-f5195100-8ec5-11ea-937c-11eb9d65c498.gif)

**Comment by razvanpapadopol** [comment]
Thanks for reporting this! 

I can reproduce it whenever the input label takes 100% of available width. It's also causing the grey border at the bottom of the placeholder to disappear.  
<img width="894" alt="Screenshot 2020-05-05 at 15 27 46" src="https://user-images.githubusercontent.com/14192054/81066135-53096100-8ee5-11ea-8e2f-7376f9197599.png">
