### ISSUE TITLE
Notifications: It's not that exciting!

### ISSUE THREAD

**Issue by m** [Automattic/wp-calypso#4179]
First read this article on punctuation:

http://www.theatlantic.com/magazine/archive/2014/04/have-we-hit-peak-punctation/358628/

Then note the overuse of exclamation marks on our anniversary notification:

<img width="791" alt="screen shot 2016-03-20 at 5 02 23 pm" src="https://cloud.githubusercontent.com/assets/48685/13907519/ea771400-eebd-11e5-8152-0ff2fe215d8e.png">

Let's edit it down to one, at most.

**Comment by lancewillett** [comment]
Good catch.

I think the only exclamation point should be used with the title, "Happy Anniversary!" and drop the rest.

We could also tighten the second two lines into one paragraph.

**Comment by lancewillett** [comment]
Cleaned up all phrases used in notifications to remove most extraneous exclamation points. This change is in the API, ref r132953-wpcom.
