### ISSUE TITLE
Gutenboarding: Domain price on new line in mobile view.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#41792]
> <img width="333" alt="Screenshot 2020-05-04 at 17 22 11" src="https://user-images.githubusercontent.com/14192054/80978157-5ab9fe80-8e2e-11ea-8630-34aa0f89b8c8.png">

I'd also expect price and domain to be on separate lines on narrow screens like this. @dubielzyk  thoughts? (Ok to do in follow-up PRs later on)

_Originally posted by @simison in https://github.com/Automattic/wp-calypso/pull/41711#issuecomment-623571394_

**Comment by dubielzyk** [comment]
Yep, [let's wrap it on two lines](https://d.pr/i/O1mohJ)

**Comment by razvanpapadopol** [comment]
This can't be reproduced now since we're hiding the _Included in plans_ text on mobile.
