### ISSUE TITLE
Sites: Changing the primary site requires a refresh to pick up

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#4181]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Make sure you have more than one site
3. Change your primary site to a different site and save changes
4. Go to My Sites, pull up the site picker and notice the new primary isn't near the top
5. Go to the Reader and Share a post to WordPress, notice it goes to the former primary blog

#### What I expected
I expected the primary to be picked up automatically and be used in the Reader

#### What happened instead
The old primary stuck around

#### Browser / OS version
Any

Discovered as part of #4180

**Comment by lancewillett** [comment]
Can't repro any more — using Mac-n-Chrome and steps above. In my test, newly set Primary Site is at the top of My Sites list right away, and is the top item in "start new post" from pencil icon in toolbar, as well as the top of Share menu list.

![screen shot 2016-05-12 at 11 48 55 am](https://cloud.githubusercontent.com/assets/66797/15226483/c1932a1c-1837-11e6-8834-93f992d2e722.png)

<img width="755" alt="screen shot 2016-05-12 at 11 49 31 am" src="https://cloud.githubusercontent.com/assets/66797/15226486/c41acfa6-1837-11e6-8409-92c672df55e8.png">
