### ISSUE TITLE
Disable premium content when plugin is not enabled

### ISSUE THREAD

**Issue by n3f** [Automattic/wp-calypso#41824]
When the premium content plugin isn't enabled, previously created posts show both views.

**Comment by davemart-in** [comment]
I'm assuming this is just for Atomic sites?

**Comment by n3f** [comment]
With the way we distribute now (FSE) it's possible that a jetpack enabled site could set this up too.  In this case (atomic/jetpack) it's possible for a site to create the premium content blocks and then disable the FSE plugin.

I don't know if it's possible or not, but it would be nice to gracefully degrade, somehow...

**Comment by davemart-in** [comment]
Thanks for clarifying!

**Comment by kwight** [comment]
Noting that [Premium Content will be moving to Jetpack](https://href.li/?185-gh-dotcom-manage).

**Comment by artpi** [comment]
I am closing this issue since it does not look like it's a problem any more
