### ISSUE TITLE
Reader: Add missing 'like' functionality to viewing a single post in reader

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4183]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com (Reader)
2. View a WordPress post in your stream with 'likes' enabled, you can like this
3. I typically don't like things unless I've read them, so I click on the post
4. I see the single post in the reader (eg. https://wordpress.com/read/feeds/18/posts/968243930)

#### What I expected

At the bottom I expect to see like buttons, I read it, I liked it

#### What happened instead

I read the article to the bottom, but no like buttons. My flow is broken. I need to navigate back to my reader stream which often loses my place with browser navigation, then find the same post and like it from there

#### Browser / OS version

Chrome OSX

##### In stream, likes are shown

![view article in stream](https://cloud.githubusercontent.com/assets/128826/13910189/e54fdfaa-ef69-11e5-9f04-c40984dc50d3.png)

##### When I am reading the article, likes aren't shown (eg. https://wordpress.com/read/feeds/18/posts/968243930 )

![screen shot 2016-03-21 at 1 35 52 pm](https://cloud.githubusercontent.com/assets/128826/13910192/f0f0d09e-ef69-11e5-9a26-83ea3c4c3079.png)

**Comment by bluefuton** [comment]
Thanks for the report @alisterscott! 

The like button is shown in full post view, but at the top left, above the article.

<img width="993" alt="screen shot 2016-03-21 at 11 40 08" src="https://cloud.githubusercontent.com/assets/17325/13910233/c7d4b492-ef59-11e5-845b-fecce9ab8016.png">

Sounds like this wasn't very intuitive in this case, though. I think there's a solid case for having those actions at the bottom of article too.

**Comment by alisterscott** [comment]
> The like button is shown in full post view, but at the top right, above the article.

Oh, up there! I have used the Reader every day for at least 6 months and never saw those buttons. At least I know now :smile:

**Comment by designsimply** [comment]
@jancavan, is this worth keeping open for a design review? If you are comfortable with the current like placement in the full post view for now, then I'd recommend closing this issue. 

Data-wise, `reader_actions` shows that likes are the most popular action in the Reader by far, but I am not sure if that is just for cards in stream views or if it is a combination of stream and full post views or if that data can be split out to get more insight on how likes are performing in cards vs full post view.

**Comment by blowery** [comment]
I'm confused, why did we close this? I think we _should_ add a like button to the bottom of the post, probably along with a short list of who liked the thing. Maybe we just track that with #1042 and give that some priority?

**Comment by designsimply** [comment]
<blockquote>Maybe we just track that with #1042 and give that some priority?</blockquote>

This. Done.
