### ISSUE TITLE
Sidebar navigation: links to wp-admin should not open a new tab

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#41859]
I was testing a few flows on an Atomic site, clicking on /plugins and other external links. I kept opening new tabs, then clicking the 'back' button in the sidebar:

<img width="289" alt="Screen Shot 2020-05-06 at 9 26 00 AM" src="https://user-images.githubusercontent.com/437258/81182637-0f156b00-8f7c-11ea-8cb3-adf1ef61f148.png">

The back button returns you to Calypso, but now you have multiple tabs open for the same site. 

Since we have Calypsoify running I don't feel there's any compelling need to have these links open in new tabs.

**Comment by davipontesblog** [comment]
@davemart-in do you think this is still relevant in light of Nav Unification, or should we close as a "no-fix"?

**Comment by davemart-in** [comment]
I'd say let's make sure we're not opening up in new tabs in the new nav, then close this. cc @obenland

**Comment by obenland** [comment]
The Browse Sites link is a regular admin menu link now that opens in the same tab. Calypsoify should be disabled once nav-unification goes live.
