### ISSUE TITLE
Premium Content: Decouple buttons from the block

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#41850]
Currently, the buttons inside the premium content block are "fake" buttons that are only displayed and not really editable.

The ideal solution would:
- Decouple "Log In" button as a standalone component that works outside the block
- Decouple the "Subscribe" button the same way (bonus points if we can reuse recurring payments button to that end)

That would even open up the premium content block to be usable without buttons

@alaczek has pointed out that she needs the following for the page templates:

--------

I was exploring ideas for premium content block patterns this week. I started out in the editor, but immediately hit a roadblock (more on that below), so I turned to Sketch instead and put together some ideas.

The biggest issue, that blocks us from doing anything beyond the simplest layouts (like the default pure text one), is not being able to nest the buttons in other blocks. I talk about this, and a few more suggestions below, starting with the most impactful.

**Blockers:**
* ability to nest the buttons - this would open up options to put them inside a group, layout grid, cover or media & text blocks, which are some of the basic design tools in the editor that we routinely take advantage of.
* align the buttons (left, right, center), to bring parity with the Buttons block.

Here’s a video to illustrate these issues: https://cloudup.com/cSbS-80-MMX

This would enable us to start creating designs like these:
![premium content patterns 4](https://user-images.githubusercontent.com/4550351/80771779-d4848a80-8b97-11ea-93f8-9b085b269bca.png)
_(some examples are more aspirational because of Guetnberg limitations)_

**We need those two issues addressed before I can make any shippable block patterns for premium content.** 

**For later:**
* be able to style each button separately. Having two identical buttons (two primary actions) next to each other is distracting. We could take a cue from the Buttons block here, where each button has it’s own settings. Ideally we would have all the button styling options available, so not just background and text color, but style variations and border-radius as well.

**Comment by artpi** [comment]
This may be quite a complicated endeavour and I think it should be tackled alongside
https://github.com/Automattic/wp-calypso/issues/41744

**Comment by artpi** [comment]
To note: Login button would be easy, because it does not care about the state of subscription. It is cool.

**Comment by davemart-in** [comment]
Update: [This PR](https://github.com/Automattic/wp-calypso/pull/#issuecomment-642591381) appears to be near completion. 🙌
