### ISSUE TITLE
Remove double border at bottom of quick links section

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#41865]
## Description

@shaunandrews pointed out that there is a double border at the bottom of the quick links menu and suggested that it might just need a `&:last-child { border: none; }` or something added:

![double-border](https://user-images.githubusercontent.com/5634774/81188250-18ee9c80-8f83-11ea-9fd5-2ccd68122dda.png)

**Comment by Aurorum** [comment]
PR for this issue in #41867. :)
