### ISSUE TITLE
Recurring Payments:  lifetime subscription display problems

### ISSUE THREAD

**Issue by n3f** [Automattic/wp-calypso#41877]
It looks like there are some display issues on the "Other Sites" tab for single recurring payments.

![](https://cdn-std.droplr.net/files/acc_854234/Azd4J0)

**Comment by artpi** [comment]
This has more context here:

pbMlHh-4Q-p2#comment-109

**Comment by gwwar** [comment]
Currently longreads is the only site that has a lifetime subscription
