### ISSUE TITLE
Media: Dropping additional images on a gallery causes weird placeholders

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#4189]
Note: The screenshot is from a Jetpack site, but I confirmed this on a WP.com site as well.
#### Steps to reproduce
1. Create/insert a gallery in a post
2. Click the gallery in the editor, then click the edit icon
3. Drag more images onto the gallery-edit screen (to upload them, and add them to the gallery)
4. Observe weird placeholders during upload:
#### What I expected

In-position placeholders, ideally with the spinner/thumbnail being displayed while upload.
#### What happened instead

I got weird (default?) placeholders and a pulsing UI, but no actual status indication (unless perhaps it's off the bottom of the gallery I can see?)
#### Browser / OS version

Chrome, OSX 10.10.5
#### Screenshot / Video

![screen shot 2016-03-21 at 9 14 35 am](https://cloud.githubusercontent.com/assets/108942/13923303/a4014e4a-ef45-11e5-9fe6-45083973ccbb.png)

**Comment by hoverduck** [comment]
12May16 Bug Scrub

Confirmed this is still an issue.  Also note that in the gif below I'm dropping in 2 images, but there are 3 placeholders.

![wp-calypso-4189](https://cloud.githubusercontent.com/assets/7233112/15227411/18377d2e-1855-11e6-91fd-75254f070001.gif)

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an problem.  I'm tempted to close it because it hasn't seen any activity in months, but instead I'll just mark it as Low Priority.  Hopefully somebody can carve out time for it eventually.

**Comment by lancewillett** [comment]
Possibly related, report on Desktop: https://github.com/Automattic/wp-desktop/issues/232

**Comment by orschiro** [comment]
Dear all, 

I would like to add myself with my request. 

It would be fantastic to have an indicator for the image upload progress. 

How am I supposed to know how long the upload is still taking and how many images still need to be processed?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18254698/b7a70b4e-73a0-11e6-9dad-462f7e2533ae.png)

**Comment by lancewillett** [comment]
Bug scrub note: changed from bug to enhancement — the issue is a suggested UX improvement.
