### ISSUE TITLE
My Home: Clearer status of completed checklist items

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#41895]
Iterate on the how to display the completed status of items in the site setup list.

As @rickybanister reported in Slack:

> I think the black pill felt more like a shape or graphic object instead of the status of the step, at least at a glance.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/448298/81228286-d7c6ae80-8fbb-11ea-9a9d-81716b28584c.png">

**Comment by jordesign** [comment]
This will be worked on as part of @jeffgolenski's design tweaks to My Home.
pd2qGl-4i-p2

**Comment by autumnfjeld** [comment]
Closing this as we currently are iterating on how the Site Checklist looks and how items are displayed. 
https://github.com/Automattic/wp-calypso/issues/53141
https://github.com/Automattic/wp-calypso/issues/53212
https://github.com/Automattic/wp-calypso/pull/53565
