### ISSUE TITLE
My Home: Add a card helping users with setting a static home page.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#41896]
User often struggle with how to set a static homepage on WordPress.com. With our new layout in My Home, we could consider add a primary task, or maybe a card in the secondary educational location to call out support docs or another how-to video.

See: p58i-8X8-p2

**Comment by lancewillett** [comment]
Related, #42016 suggests adding a link from the Pages list:

![screen-shot-2020-03-02-at-07 45 12](https://user-images.githubusercontent.com/66797/81458011-38392580-914d-11ea-949c-af72cb9ec7d5.png)

Where "A" in that diagram links to the Customizer, opening the "Homepage Settings" section directly to make it super easy.

I'd also love to try returning people to the same Calypso context when people click the X to close Customizer (it might already work that way, in some cases).

**Comment by jordesign** [comment]
I don't know if this is the _right_ solution - but it would definitely be good to highlight the current Front-Page setup and provide a link/instructions on how to change it somewhere.

**Comment by davipontesblog** [comment]
I am in favor of adding the ability to toggle pages "on" and "off" as either static pages, or post pages, from the My Site > Pages in calypso. As detailed here: https://github.com/Automattic/wp-calypso/issues/42016

**Comment by autumnfjeld** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/42016 as it makes good sense to help the user in the most relevant place: setting their page as static from My Site > Pages.
