### ISSUE TITLE
My Home: Webinar card in Learn and Grow

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#41898]
Thanks to @Aurorum we already have an webinar card for learn and grow, but we haven't yet wired up display logic in the API. What primary tasks does it make sense to group this card with? Don't mind the fact that we haven't built out some yet, or are still ideating on tasks not planned yet.

Candidates that come to mind which already are planned are: 
* Site prelaunch
* Find a domain
* Connect Accounts
* Write a blog post
* No primary task/give the customer a break

| Site Prelaunch | Find a domain | Connect Accounts  | Write a blog post  |  No task |
| ------------- | ------------- |------------- |------------- |------------- |
| <img width="1105" alt="Screen Shot 2020-05-06 at 2 58 03 PM" src="https://user-images.githubusercontent.com/1270189/81232595-03d93400-8faa-11ea-9df5-8aaecba02262.png"> | <img width="1023" alt="image-2" src="https://user-images.githubusercontent.com/1270189/81232226-5d8d2e80-8fa9-11ea-8e73-70471fae3466.png"> | <img width="1024" alt="image" src="https://user-images.githubusercontent.com/1270189/81232360-9c22e900-8fa9-11ea-853d-640a65ba584f.png"> | <img width="1024" alt="image-4" src="https://user-images.githubusercontent.com/1270189/81232253-68e05a00-8fa9-11ea-9099-f999fcbb6723.png">| <img width="1079" alt="Screen Shot 2020-05-06 at 2 57 03 PM" src="https://user-images.githubusercontent.com/1270189/81232526-ec9a4680-8fa9-11ea-9dd3-d0f770061636.png"> |

cc @danhauk @sararosso 

<img width="1544" alt="Screen Shot 2020-05-06 at 2 48 00 PM" src="https://user-images.githubusercontent.com/1270189/81231815-a690b300-8fa8-11ea-8adf-446c27d6804a.png">

If content for webinars are relatively stable, is there also any interest in promoting a specific one? We could split out different cards for a specific topics, or make this card a bit more dynamic.

> Mondays – Getting Started: Website Building 101 
Not sure where to begin? We’ll help you tackle your project one step at a time.
Tuesdays – Quick Start: Payments (Simple and Recurring)
Discover how to monetize a WordPress website using straightforward solutions.
Wednesdays – Quick Start: Blogging
You’ve got something to say. We’ll show you how to say it with style on your own blog.
Thursdays – Quick Start: WooCommerce 101
Find out how to build a fully functional online store using a top eCommerce plugin.
Fridays – Quick Start: WordPress.com 101 en Español
Join us for a Spanish version of our webinar explaining the basics of building your website.

**Comment by deBhal** [comment]
The card is [here](/Automattic/wp-calypso/blob/trunk/client/my-sites/customer-home/cards/tasks/webinars/index.jsx): `client/my-sites/customer-home/cards/tasks/webinars/index.jsx` but it didn't turn up in my list when I dismissed all the cards, so it looks like the task here is to find the mechanism that determines which cards are shown and add the webinar into the rotation.

**Comment by autumnfjeld** [comment]
> find the mechanism that determines which cards are shown

Getting up to speed on these kinds of things will be really helpful for informing design of what's "easy" to control in terms of content.

**Comment by gwwar** [comment]
> Getting up to speed on these kinds of things will be really helpful for informing design of what's "easy" to control in terms of content.

Please see documentation in PCYsg-qpk-p2 (and child pages), there's also a development mode documented at PCYsg-qqj-p2

**Comment by autumnfjeld** [comment]
@gwwar  It sounds to me like these are great questions for a P2 discussion:

> If content for webinars are relatively stable, is there also any interest in promoting a specific one? We could split out different cards for a specific topics, or make this card a bit more dynamic.

Given the age of the original issue post, maybe a refresh of the idea in a P2 post is a good place to restart  discussion ands and debate whether such dynamic content is suitable for My Home. You could tag the people that this effort would  affect (webinar creators, and design).   

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)

**Comment by gwwar** [comment]
@autumnfjeld feel free to take over or close out the issue as needed 👍
