### ISSUE TITLE
Jetpack Plugins: Add InfoPopup explaining why the site can't be auto updated

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#419]
Bases on this mock up:

![singlesite-singleplugin-no-updates-info-box](https://cloud.githubusercontent.com/assets/11487924/11323966/d0e344b2-90f0-11e5-923f-036a042ef52a.png)

The following known reasons need to covered:
- the plugin is not found in .org
- the site is not the main site of a network.
- the site has no file system write access.
- the site is under version control.
- the site has AUTOMATIC_UPDATER_DISABLED constant set
- the site has DISALLOW_FILE_EDIT constant set
- the site has DISALLOW_FILE_MODS constant set

The pop up needs to appear in the following 3 places. 
1. Single site single plugin view. 
2. Single Site multi plugin view.
3. Multi Site Single plugin view.

**Comment by enejb** [comment]
I am closing this issue since we this was fixed via https://github.com/Automattic/wp-calypso/pull/304
