### ISSUE TITLE
Add gauge on My Home link about checklist completion

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#41929]
## Description

We've seen from usability studies and concierge calls that it can be confusing for some people when  first getting started where to go to get back to their launch checklist.

We'd like to add a visual indicator on the My Home link which both hints at where the checklist lives, and  shows you an indication of how far along you are. 

Here's a mockup:

![Screen Shot 2020-02-27 at 4 11 35 PM](https://user-images.githubusercontent.com/5634774/81289624-b81f9c80-9034-11ea-89d6-2db37d99f748.png)

**Comment by Aurorum** [comment]
Started a PR for this in #42022. :)
