### ISSUE TITLE
Jetpack Settings: buttons are not aligned 

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4192]
#### Steps to reproduce
1. Starting at URL: settings/security/[sitename]
#### What happened

Buttons are misaligned 
#### Browser / OS version

Safari 9.0.2
Mac OS X
#### Screenshot / Video

![screen shot 2016-03-18 at 12 38 37 pm](https://cloud.githubusercontent.com/assets/618551/13926739/aca7faba-ef5b-11e5-8a43-f3bff521bff2.png)

**Comment by lancewillett** [comment]
Closed #5196 as a duplicate

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue as shown above.  Also observed in OSX Chrome v52 and Firefox v46
