### ISSUE TITLE
FSE Plugin: Add Pattern Categorization

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#41936]
Stubbing out an issue: Let's add Pattern Categorization to the Patterns in the FSE Plugin.

Reference:
https://github.com/WordPress/gutenberg/pull/22164

Likely requires adding categories to the arrays like in this example:

https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/collage-gallery.php

**Comment by iamtakashi** [comment]
I took the first stab at categorising our patterns.

```
Text
Lists
Images
Gallery
Contact
Blog
Call to Action
```

<img width="1506" alt="Screenshot 2020-05-07 at 18 22 12" src="https://user-images.githubusercontent.com/908665/81326195-5fcab800-9091-11ea-9daf-340ec1890097.png">


I imagine we'll introduce new categories as the number of patterns grows. For example, `Menu` that is at the moment in the `text` category since we only have one menu pattern.

Looping in @boonerang in case you have some thoughts on this.

**Comment by ianstewart** [comment]
cc @alaczek

**Comment by ianstewart** [comment]
@johnHackworth what needs doing to get the categorization above into the FSE Plugin?

**Comment by simison** [comment]
@ockham @roo2  would be good to have a PR going (even non-functioning) first so that you can apply the "string freeze" label and get these translated before deploying.

**Comment by mtias** [comment]
These categories were designed to afford overlaps, so I think some of the "images" and "list" ones should also be in "gallery", for example. The category navigation is going to eventually allow drilling down, so there will be less cases of seeing duplicated content.

**Comment by iamtakashi** [comment]
> so I think some of the "images" and "list" ones should also be in "gallery", for example.

@mtias I assume you're referring the ones with the red border, correct?

<img width="1506" alt="81326195-5fcab800-9091-11ea-9daf-340ec1890097" src="https://user-images.githubusercontent.com/908665/83409660-bf0bb600-a40c-11ea-9978-ba13f86f9b81.png">

Most of those patterns don't actually use a gallery block, and I understand that's not a concern for the users, but then the definitions of the gallery and the images categories become unclear to me. Can you help me to understand what makes a pattern as a gallery pattern?

**Comment by mtias** [comment]
Yes, those are the ones I mean. The name of pattern categories don't need to match a specific block type. You are already including different gallery types in "gallery" which are technically different blocks.

**Comment by iamtakashi** [comment]
Thanks @mtias. I totally agree the name of pattern categories doesn't need to match a specific block type. Although the definition of the gallery category is still a bit fuzzy, I think I get how you see them (let's not add the one in the Call to Action as we discussed.)

I'll add the rest to the gallery category also.

**Comment by ockham** [comment]
BTW in case you missed it, I've spun up a PR to add categories: #42761. I think patterns have changed a bit since @iamtakashi made this initial categorization, so I'd love if y'all could review it and let me know whether I've categorized them correctly, or if they need changing.

**Comment by iamtakashi** [comment]
@ockham I've just left notes on 3 patterns to change the category in the diff. Let me know if I can clarify further. Thanks!
