### ISSUE TITLE
Add timezone dropdown to schedule post UI in Gutenberg

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#41933]
## Description

It can be hard when scheduling posts to know what Timezone the post is being scheduled in and if you don't know, it's possible to post things at the wrong time.

To prevent this, we'd like to add a timezone dropdown that allows you to select the timezone that you'd like to schedule the post in and does the math for you behind the scenes to make sure the post is scheduled exactly when you want it to be.

Here's a mockup of what this might look like:

<img width="329" alt="Image 2020-05-07 at 7 50 49 AM" src="https://user-images.githubusercontent.com/5634774/81291530-e94d9c00-9037-11ea-89c9-97650cb3076d.png">

**Comment by foreverabhi2002** [comment]
@davemart-in Hello, I want to work in this issue. I have fully understood the work. Please give me this task.

**Comment by davemart-in** [comment]
Hi @foreverabhi2002! This task will need to be added as a PR in the [Gutenberg repo](https://github.com/Automattic/gutenberg). You are more than welcome to get the ball started there. We'll have a couple of developers able to assist in a week or two. If you can link to your PR here, that would be great. Thanks.

**Comment by davemart-in** [comment]
Note: In discussion we decided to focus first on simply displaying the time zone that is being used. See #42116

**Comment by davemart-in** [comment]
This issue is complete with the launch of https://github.com/Automattic/wp-calypso/issues/42116
