### ISSUE TITLE
Patterns: guide people to new patterns UI

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#41930]
In [Gutenberg v7.7](https://make.wordpress.org/core/2020/03/11/whats-new-in-gutenberg-11-march/) we shipped new block patterns UI (right arrow). In v8.0 we changed its location to block inserter (left arrow).

<img width="1665" alt="Screenshot 2020-05-07 at 14 28 54" src="https://user-images.githubusercontent.com/87168/81289747-95f74000-906f-11ea-9ac6-9eefef7ecd3c.png">

To avoid customer confusion, educate them for some weeks about the new location by registering a simple header plugin with the same icon that it had before, and opening a popover saying something along the lines _“patterns have moved into the inserter”_.

A simple image of the blue `+` button could be good.

We'd take this out after 1-2 more versions ship. Remember to open an issue to remind us about cleaning it out.

Best place for the code is likely [`wpcom-block-editor`](https://github.com/Automattic/wp-calypso/tree/982d4f15f2e582b8629e97e7bb3b181c3ba78dc1/apps/wpcom-block-editor)

cc @ianstewart

**Comment by ianstewart** [comment]
cc @olaolusoga

**Comment by simison** [comment]
Slack chat in case it's useful but I tried summarizing everything p1588842973335300-slack-gutenberg-on-dotcom

**Comment by rickybanister** [comment]
Unfortunately, or perhaps fortunately, I don't think many folks found the initial patterns sidebar. So hopefully migrating to the inserter is a big boost in findability.

**Comment by olaolusoga** [comment]
Instead of keeping old icon and registering a simple header plugin, @simison we should use whatever we land on for the tooltip tour work here: p2-pbAok1-LV . Once we build it, we can use it for highlighting new features in the editor to existing users.

**Comment by simison** [comment]
Yes I agree we should have that kind of system in place to introduce changes and new features. This header icon we can have done and deployed in half an hour already today so I'd reserve tips for the next cheese we move. Makes sense? :-)

**Comment by olaolusoga** [comment]
Half an hour. Nice. Makes sense.

**Comment by joanrho** [comment]
Yep, the new location of the Block Patterns is already on my radar for the next iteration of the intro tour steps. I may even combine the "Add block" tooltip with it since they now live side by side in the Block Inserter menu. Will keep y'all posted.
