### ISSUE TITLE
(5P) Add unmoderated comment notice back to left nav

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#41931]
## Description

I think before we redesigned the left nav we showed the unmoderated comment count next to the Comments link in the left nav. We still show this in wp-admin. Matt would like to bring it back to Calypso.

Here's a mockup of what it might look like:

![Screen Recording 2020-05-07 at 07 45 AM](https://user-images.githubusercontent.com/5634774/81290874-cb336c00-9036-11ea-95dc-69a4b7a8cb79.gif)

**Comment by jancavan** [comment]
Just posting a quick update to the mockup - made the number a tiny bit smaller (`12px`):

![Screen Shot 2020-05-15 at 12 05 25 PM](https://user-images.githubusercontent.com/4924246/82087139-5d291d80-96a4-11ea-800d-c4d4cc0c05f4.png)

![gray-comments](https://user-images.githubusercontent.com/4924246/82099937-5e1a7900-96bd-11ea-8c44-6022c2e51c20.png)

I also tried different colors, but blue/pink are a bit much:

![Screen Shot 2020-05-15 at 2 58 08 PM](https://user-images.githubusercontent.com/4924246/82099576-7f2e9a00-96bc-11ea-8202-24d300f64f35.png)

What are your thoughts on dark gray? We're using a dark gray pill in the Calypso editor sunsetting announcement: https://github.com/Automattic/wp-calypso/pull/41570#issuecomment-629082698

![Screen Shot 2020-05-15 at 3 00 07 PM](https://user-images.githubusercontent.com/4924246/82099677-c452cc00-96bc-11ea-8ccb-d662321d702b.png)

Here it is in context within Calypso:

![dark-comments](https://user-images.githubusercontent.com/4924246/82099973-75f1fd00-96bd-11ea-8921-9b59681b79e0.png)

@davemart-in @lcollette @olesyabrk

**Comment by olesyabrk** [comment]
A few considerations:

- there is a lot going on on the far right for many list items in the nav, what if you move the pill closer to the label, like we do in core?

- when the Site dropdown is not expanded, should there be a way to note on the Site level that there is something new there, in the Comments section?

**Comment by marekhrabe** [comment]
I have implemented this in #42362, without any style overrides, just using the `<Count />` component from Calypso. It is right-aligned, as those components were already styled this way. 

Please let me know a final say on how to proceed.

**Comment by obenland** [comment]
@jancavan How can I help getting us to a final decision on colors? It's currently blocking the PR from going in

**Comment by jancavan** [comment]
I did several more explorations and decided that solid colors that aren't light gray are a little too strong and draw too much attention; even the dark gray feels too much.

> when the Site dropdown is not expanded, should there be a way to note on the Site level that there is something new there, in the Comments section?

Good question! I thought about this, but considering that we already send out notifications for the exact same thing, I decided against displaying a "secondary" notification, or something aggressive in addition to current notifications which are already intentionally distracting. 

I kinda like this outline:

![Screen Shot 2020-05-20 at 9 07 13 AM](https://user-images.githubusercontent.com/4924246/82469752-4d7d5080-9a79-11ea-9b2e-2595ac3e37cb.png)

.. which we can tie nicely with how we currently already display count in the sub-nav of this page:

![Screen Shot 2020-05-20 at 9 07 36 AM](https://user-images.githubusercontent.com/4924246/82469784-5a01a900-9a79-11ea-988e-7efbd08e8dbf.png)

.. but it gets lost with all the other icons in the sidebar, so I think light gray is a good balance.

![Screen Shot 2020-05-20 at 9 09 07 AM](https://user-images.githubusercontent.com/4924246/82469944-903f2880-9a79-11ea-89a1-af95ec410fd7.png)

When active, we use a darker blue outline:

![Screen Shot 2020-05-20 at 9 11 59 AM](https://user-images.githubusercontent.com/4924246/82470269-f926a080-9a79-11ea-8920-ad1b9a2f7b12.png)

.. Again, to mirror the pattern we use in its sub-nav:
![Screen Shot 2020-05-20 at 9 14 01 AM](https://user-images.githubusercontent.com/4924246/82470587-66d2cc80-9a7a-11ea-9c5d-43523fa22ff5.png)

> there is a lot going on on the far right for many list items in the nav, what if you move the pill closer to the label, like we do in core?

I tried this, and it's not bad (and perhaps gives it a sense that it's not an ever-present label?), but everything aligned right feels cleaner to me.

![Screen Shot 2020-05-20 at 10 19 45 AM](https://user-images.githubusercontent.com/4924246/82476816-6e4aa380-9a83-11ea-8ed5-967a6f2e7732.png)

![Screen Shot 2020-05-20 at 10 19 55 AM](https://user-images.githubusercontent.com/4924246/82476835-73a7ee00-9a83-11ea-87c8-c128cefe1df8.png)

**Comment by jancavan** [comment]
I also tried a couple other things. If what we're trying to solve for here is to inform the user of unmoderated comments, we could send another notification informing them of this:

<img width="1440" alt="v1-D" src="https://user-images.githubusercontent.com/4924246/82478135-51af6b00-9a85-11ea-8e7d-0437ae2df40b.png">

Or we could revisit the red dot idea. I don't have additional details as to how this could work, but thought of throwing it out there:

<img width="1440" alt="v1-C - Inactive-Expanded" src="https://user-images.githubusercontent.com/4924246/82478113-49efc680-9a85-11ea-9445-8dde5681012d.png">

@olesyabrk @lcollette @danhauk @sixhours

**Comment by sixhours** [comment]
I personally think having the indicator directly to the right of the section title looks best and follows existing patterns for similar indicators (as you noted):

![82476835-73a7ee00-9a83-11ea-87c8-c128cefe1df8](https://user-images.githubusercontent.com/2124984/82575346-5d1e9700-9b56-11ea-82bd-3204ddee8e08.png)

It also avoids overloading that right column with icons/symbols.
