### ISSUE TITLE
Customer Home: Top Post in "Stats at a glance" is not the top post

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#41940]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/
2. If you aren't taken to your primary site's Customer Home, go to https://wordpress.com/home and select a site to open the Customer Home.
3. Go to the "Stats at a glance" section and note the Top Post listed there.
4. Go to Stats > Traffic > Posts & Pages > 7 Days (at https://wordpress.com/stats/day/posts/YOUR_SITE_ADDRESS?startDate=2020-05-07&summarize=1&num=7) and note where the Top Post from Customer Home is ranked in that list. 

#### What I expected

The "Stats at a glance" card displays the title of the most visited post during the previous 7 days.

#### What happened instead

The "Stats at a glance" card displays the title of the **least** viewed post (of posts that have been viewed) during the previous 7 days.

#### Browser / OS version

macOS 10.15.4 / Chrome 81.0.4044.129

#### Screenshot / Video

![Screenshot 2020-05-07 15 23 22](https://user-images.githubusercontent.com/8658164/81305946-d60df100-9076-11ea-9e2b-c54c639037c4.png)
![Screenshot 2020-05-07 15 23 34](https://user-images.githubusercontent.com/8658164/81305952-d73f1e00-9076-11ea-9ca9-8b5f76471309.png)

#### Context / Source

#dogfooding

cc @mmtr @Automattic/manage

**Comment by gwwar** [comment]
Good catch @rachelmcr! Stepping though I don't believe this selector is actually sorting the array by views:
https://github.com/Automattic/wp-calypso/blob/e94b849f880352201c6f2838fcbca3a3b6f5c6b9/client/state/stats/lists/selectors.js#L240
