### ISSUE TITLE
Buttons block: If border radius is set to 0, buttons will be very round.

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#41953]
Buttons that should be square are rounded.

## Steps to reproduce

1. Edit a page or post
2. Add button
3. Set border radius to 0
4. Note the button is very round
5. Drag radius up slightly
6. Note the difference

#### What I expected
Border radius 0 should be 90 degree angles on the end.

#### What happened instead
I get very round buttons.

#### Browser / OS version
n/a but Mac and Chrome, both current

#### Screenshot / Video
https://cloudup.com/cCdmwAulhdm

#### Context / Source
https://wordpress.com/forums/topic/bug-design/#post-3485697

**Comment by davipontesblog** [comment]
Hi @supernovia I wasn't able to reproduce this bug in my test site with the Buttons block. Could you check if this was perhaps using the deprecated "Button block" that was replaced with the Buttons block?

**Comment by supernovia** [comment]
Hi! Sorry I missed the notification on this. I *think* it's the same block. It looks the same.  But I can't duplicate the rounding issue anymore, so it must be ok!

## Screenshot from the video:
![Screen Shot 2020-07-21 at 1 24 35 PM](https://user-images.githubusercontent.com/3476361/88097679-c4a49300-cb55-11ea-86c1-f2406863982e.png)

## Current:
![Screen Shot 2020-07-21 at 1 25 25 PM](https://user-images.githubusercontent.com/3476361/88097720-d38b4580-cb55-11ea-985c-30d32b5dcc06.png)

Thanks for your help!
