### ISSUE TITLE
Gutenboarding: wrong cursor position on site topic input

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#41976]
When site topic has an existing value and it's focused, the cursor is showing below the input.
<img width="678" alt="Screenshot 2020-05-08 at 13 15 45" src="https://user-images.githubusercontent.com/14192054/81397537-39a82500-9130-11ea-8af7-db2d10598a72.png">

Tested in Chrome, Desktop.

**Comment by simison** [comment]
Only when the cursor is at the beginning of the word.

I noticed this when shift+tabbing back to the input.

**Comment by razvanpapadopol** [comment]
It's probably introduced with this change: https://github.com/Automattic/wp-calypso/pull/41968/files
It should be solved just by setting `display: none` on  `.vertical-select__whitespace`  when we also hide the placeholder.

**Comment by razvanpapadopol** [comment]
Feature no longer active
