### ISSUE TITLE
My Home: Celebratory Cards in new Layout

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#41998]
As proposed by @danhauk, to better match the focus of one thing at a time on My Home, let's update the celebratory cards to render in the primary layout slot. **Note that certain design and flow details are still being worked through and are open to feedback.**

<img width="886" alt="after" src="https://user-images.githubusercontent.com/1270189/81429802-35b9da00-9113-11ea-8e6b-4386bad09876.png">

Each celebratory card will also get a different and ✨ illustration thanks to @danhauk 
<img width="1057" alt="illustrations" src="https://user-images.githubusercontent.com/1270189/81429990-86c9ce00-9113-11ea-975a-cb93c7699b0f.png">
(Folks are still working on the migration illustration).

### Site Creation
<img width="886" alt="80830182-892da480-8bb6-11ea-85c8-f5ed32f19d0a" src="https://user-images.githubusercontent.com/1270189/81430260-fd66cb80-9113-11ea-890a-8a73bb14f152.png">

* Clicking on "Get Started" immediately transitions into the site setup list (with some sort of animation).
* This banner is only visible on first page view after site creation by the site creator, any other navigation to this section or page refresh should transition next to the site-setup list.

### Launch Site after checklist complete
<img width="984" alt="80830606-3d2f2f80-8bb7-11ea-9c9a-0c007898d15f" src="https://user-images.githubusercontent.com/1270189/81430330-14a5b900-9114-11ea-8a93-3bc81a859f28.png">

* Show me what's next would immediately transition to the next task
* "Dismiss" would dismiss the card and the next task would show up after the waiting period (same as the x in the existing banners)

### Site launched before checklist complete
<img width="741" alt="80830961-ef66f700-8bb7-11ea-9dab-e13bc6d3c7b1" src="https://user-images.githubusercontent.com/1270189/81430455-4880de80-9114-11ea-8c2e-348dffe0ad22.png">

* "Show site setup" shows the site setup list again
* "Skip site setup" marks the whole checklist as complete and dismisses the card. The next task would show up after the waiting period.
* How long is this visible for without a user click (is there an auto time expiry?)

### Site setup complete after launch
<img width="893" alt="80831081-25a47680-8bb8-11ea-8197-76386e340fc2" src="https://user-images.githubusercontent.com/1270189/81430786-e674a900-9114-11ea-872c-123bd2524eb6.png">

* Show me what's next would immediately transition to the next task
* "Dismiss" would dismiss the card and the next task would show up after the waiting period (same as the x in the existing banners)

### Migration 
* Show me what's next would immediately transition to the next task
* "Dismiss" would dismiss the card and the next task would show up after the waiting period (same as the x in the existing banners)

**Comment by kwight** [comment]
The first attempt was reverted due to a stuck spinner on site creation.
