### ISSUE TITLE
Flash of wrong dropdown value

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#42]
On https://wordpress.com/settings/general the language option for a site may accidentally be set to the wrong value:

0. Cold browser cache
1. User lands on page (dropdown shows default, maybe the top, value)
2. User immediately changes dropdown to some value which isn't the current
3. User scrolls quickly to the bottom of the page to hit the Save button
4. Some loading event completes and the dropdown resets to whatever it's supposed to be set to (user doesn't notice, because they've already scrolled down to hit the save button)
5. User hits the save button (with the dropdown not in the state they intended it to be in)

Screenflow: https://cloudup.com/ix8mwhVWcEe

**Comment by gwwar** [comment]
Fixed by #1167
