### ISSUE TITLE
Devdocs: create a new page to document all product illustrations

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42004]
It would be very helpful for everyone working on Calypso to reference a documentation page displaying all of our actively used illustrations. We might even consider putting out of use illustrations on there as well under a separate heading in case they still serve some future use. 

I suppose it would make sense near the components and blocks 'live docs' sections since grabbing the svg code from the documentation would be a helpful feature. 

To support this we may want to refactor how illustrations are used within code—possibly wrapping them in an illustration component and migrating all illustrations to a single folder if they aren't already.

**Comment by jancavan** [comment]
As mentioned, I'll be working an audit of all our illustrations.

**Comment by Aurorum** [comment]
> To support this we may want to refactor how illustrations are used within code—possibly wrapping them in an illustration component and migrating all illustrations to a single folder if they aren't already.

Just to note, there is an attempt to migrate illustrations in #36850 to ensure that the images which are served have the latest colour updates rather than old ones.

**Comment by jancavan** [comment]
See: p2-pbAPfg-qS-#comment-1034 for an audit of our illustrations.

**Comment by sixhours** [comment]
I started looking at this here: #44058
