### ISSUE TITLE
Editor: contact form builder settings text

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4200]
Hey @rodrigoi I think this got lost in the shuffle. I think these text updates would be clearer and more concise:

![screen shot 2016-03-21 at 4 37 32 pm](https://cloud.githubusercontent.com/assets/618551/13935066/671fd5c6-ef83-11e5-9205-cbd8f8dfa4e0.png)

I changed a little bit of everything, and removed some text.

Also, if possible, I think it would be more intuitive if the the pre-filled text wasn't a placeholder, but actual content, so the user wouldn't have to type it again.

**Comment by drw158** [comment]
Current:

![screen shot 2016-03-21 at 4 41 28 pm](https://cloud.githubusercontent.com/assets/618551/13935154/cd535a2a-ef83-11e5-90ae-a3eb989648cc.png)

**Comment by rachelmcr** [comment]
Confirmed that the old text described above is still used in the contact form builder.

#bug-scrub #pre-gutenburg-bug-purge
