### ISSUE TITLE
Domains: wrong link to support article

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#42007]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/domains/manage/$site/edit/$site
2. click on the ? at the bottom right
3. click on "Connect an Existing Domain"
4. click on Read More

#### What I expected

The article Connect an existing domain to open

#### What happened instead

The article Transfer a domain to another registrar opened

#### Browser / OS version

Chrome OS 

#### Screenshot / Video

OK. Click on Connect an Existing Domain
<img width="358" alt="Screen Shot 2020-05-08 at 16 28 24" src="https://user-images.githubusercontent.com/1041600/81442195-86e4c080-9149-11ea-977e-2cf049793cf0.png">

OK. Click Read more (interesting: links have title case while buttons have sentence case)
<img width="342" alt="Screen Shot 2020-05-08 at 16 31 33" src="https://user-images.githubusercontent.com/1041600/81442264-aa0f7000-9149-11ea-8612-699f8a0ff9de.png">

Not OK. Different article was loaded
<img width="998" alt="Screen Shot 2020-05-08 at 16 31 23" src="https://user-images.githubusercontent.com/1041600/81442277-b0055100-9149-11ea-8811-1157567c62e6.png">

**Comment by lancewillett** [comment]
Thanks for the bug report, @eliorivero!

**Comment by eliorivero** [comment]
Thanks for the quick fix @lancewillett!

**Comment by lancewillett** [comment]
¡A todo dar, carnal! 👍
