### ISSUE TITLE
Gutenboarding: ensure specific order of domains on the list

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#42010]
Aadil suggested:

>  Can we order this so that the recommended one is always first and maybe the wp subdomain is at the bottom?
>
> <img width="464" alt="image" src="https://user-images.githubusercontent.com/87168/81445686-07bfae80-9182-11ea-9a80-3e631b7008bb.png">

@dubielzyk for your consideration. :-)

**Comment by alshakero** [comment]
I created a quick PR because I was curious how this would look

https://github.com/Automattic/wp-calypso/pull/42011

**Comment by simison** [comment]
We've decided to go with this order:

- recommended
- free
- the rest

<img width="584" alt="image" src="https://user-images.githubusercontent.com/87168/84365991-eae02600-abda-11ea-941e-00693fd77794.png">
