### ISSUE TITLE
Embeds: Spotify playlist embed not working

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#42024]
#### Steps to reproduce

1. Add a Spotify embed with a playlist URL, such as https://open.spotify.com/playlist/3tryGC00g1xU3BRdQehjrB?si=hCWNeOlMR6KXzI7v1FBn4Q

#### What I expected

Playlist should be embedded similar to an album or a song.

Using an album link works, such as: https://open.spotify.com/album/5gIa8hTQGPwVeNYjDwrraZ?si=ky0ZoBy1QxSLF48C6eF-Tw

#### What happened instead

The editor displayed a message " Sorry, this content could not be embedded."

#### Browser / OS version

Firefox 76 on macOS (Catalina)

#### Screenshot / Video

<img width="943" alt="Markup 2020-05-10 at 16 02 34" src="https://user-images.githubusercontent.com/51966986/81502762-ce00bc00-92d7-11ea-9938-8bb480fc60f1.png">

#### Context / Source

#20984698-hc

**Comment by pauljacobson** [comment]
We have another report here: 2956791-zen

This seems to be specific to WordPress.com sites. I was able to replicate this on one of my test sites, here: https://he20171027.com/2020/01/23/spotify-embeds/

I recently added a Spotify playlist to my self-hosted WordPress.org site, and it renders both in the editor, and in the post when viewed publicly: https://pauljacobson.me/2020/05/06/comforting-familiarity/

![Spotify_playlist_embed](https://user-images.githubusercontent.com/2912202/81537809-706f7c80-9376-11ea-82ed-6df1bfffe768.png)

**Comment by susanjanec** [comment]
Another report here - 21006741-hc

Provided workaround to add playlist using a shortcode, but the playlist appears very small, and there isn't a way to adjust the width.

**Comment by khristiansnyder** [comment]
Another report here: 21013620-hc

Shortcode workaround was provided.

Tested on my own simple and AT sites and Spotify embeds don't work on either.

**Comment by AtrumGeost** [comment]
Got another one here 443326-hc

**Comment by ktyfuller604** [comment]
Another report here [11897318-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=11897318)

**Comment by Addison-Stavlo** [comment]
Im trying to embed a playlist on self hosted, both with current Gutenberg and an older version.  Neither are working for me. 

 @pauljacobson was `https://open.spotify.com/playlist/37i9dQZF1DX4UtSsGT1Sbe` the url you added to get that one running on your self hosted site?  Also, do you happen to know the Gutenberg version that is working on?  This may be a regression in core.  🤔

**Comment by pauljacobson** [comment]
Hi @Addison-Stavlo I just tried to add a playlist to a post on the same site, and I was presented with this error:

![Screenshot_2020-05-12 Add a New Post ‹ Paul Jacobson — WordPress](https://user-images.githubusercontent.com/2912202/81642877-141b6400-942d-11ea-87e8-b217bd1d7d87.png)

When I preview the post, it doesn't even render now:

![Screenshot_2020-05-12 • Paul Jacobson](https://user-images.githubusercontent.com/2912202/81642900-285f6100-942d-11ea-805d-78af61556052.png)

I'm using the Gutenberg v8.0.0 plugin on WordPress 5.4.1, using the Twenty Twenty theme. The site is hosted on Pressable. 

The issue persists even if I deactivate the plugin, and revert back to the version that Pressable runs by default (I'm not too sure which version that is).

**Comment by mikeicode** [comment]
Another 21035411-hc

**Comment by chatoxz** [comment]
Another here 2956060

**Comment by Addison-Stavlo** [comment]
I opened an [issue in core](https://github.com/WordPress/gutenberg/issues/22302) regarding this.

**Comment by sirreal** [comment]
This _appears_ to be a problem on Spotify's end, but it's not clear where or how to file a support request.

It was raised on a Spotify forum: https://community.spotify.com/t5/Spotify-for-Developers/Playlist-oembed-down-or-changed/m-p/4949867/highlight/true#M99 and I've commented there.

I've also reached out on Twitter: https://twitter.com/jonsurrell/status/1260608420396306432

**Comment by ktyfuller604** [comment]
Another report here - [#2438058-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=2438058)

**Comment by greentreeonline** [comment]
Another report here: 2975135

**Comment by Addison-Stavlo** [comment]
Noting core has this open at - https://core.trac.wordpress.org/ticket/50116
Although, it does still seem to be an issue from Spotify's end 😞

**Comment by thebud15** [comment]
Reported in #20048151-hc

**Comment by sanjeev00733** [comment]
Another report in #2982202-zen

**Comment by edwinho89** [comment]
Another issue in #17727539-hc

It seems existing embedded Spotify link still works, only embedded URLs that have not been added before.

**Comment by hacchism** [comment]
Another report in #4973969-hc. This user was using Classic editor.

Provided them with a shortcode workaround. And it worked.

**Comment by edwinho89** [comment]
Another report in #21222927-hc

**Comment by philnick206** [comment]
Another report #21237753-hc

Provided shortcode workaround.

**Comment by sophiegyo** [comment]
Another report 3001941-zen
Provided shortcode workaround.

**Comment by TeniCola** [comment]
Another report in 2745366-hc
Shared the shortcode workaround as a solution.

**Comment by kosiew** [comment]
Replicated this on a GoDaddy site.
This happens in Core to - https://core.trac.wordpress.org/ticket/50116

**Comment by AleGenoa** [comment]
Another here: 3003746-zen
The shortcode workaround on my test site seems to generate the block outside of the webpage, barely visible to the left:
https://snipboard.io/52tNay.jpg

**Comment by synora** [comment]
Another report here: 21495866-hc
Shortcode alternative worked.

**Comment by rinazrina** [comment]
Another report here: #2997547-zen 
Shared the shortcode workaround.

**Comment by ash1eygrace** [comment]
Another report in hc-15470225
Also, I shared the shortcode as a workaround.

**Comment by pauloeaquino** [comment]
Report in 21668828-hc
Shortcode workaround shared in 3035787-zen

**Comment by sirreal** [comment]
Spotify seems to have fixed things on their end. I've tested and playlist embed is working.

Closing.

**Comment by noteeth** [comment]
This issue seems to have returned.  
Reported in 30020428-hc
Sent shortcode workaround 4050945-zen

Added multiple different Spotify playlists to different test sites to see if the issue was replicable and this is always what I am seeing now.

<img width="1578" alt="Screen Shot 2021-06-07 at 6 08 27 PM" src="https://user-images.githubusercontent.com/16570939/121107849-8a6bd080-c7bd-11eb-9d4e-760c2ba699a7.png">
<img width="958" alt="Screen Shot 2021-06-07 at 6 08 51 PM" src="https://user-images.githubusercontent.com/16570939/121107854-8e97ee00-c7bd-11eb-820d-d8ce5288d2ff.png">

**Comment by KokkieH** [comment]
@noteeth, there's a new report for the current issue in #53424

**Comment by arunsathiya** [comment]
@noteeth I am closing this report in favor of https://github.com/Automattic/wp-calypso/issues/53424.
