### ISSUE TITLE
Embeds: YouTube channel embed not working

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#42025]
#### Steps to reproduce

1. Add a YouTube embed with a link to a channel, such as https://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q

#### What I expected

YouTube embed would display some contents of the channel, similar to a direct video link like https://www.youtube.com/watch?v=BtN-goy9VOY

#### What happened instead

Embed block showed the following message: Sorry, this content could not be embedded.

#### Browser / OS version

Firefox 76 on macOS (Catalina)

#### Screenshot / Video

<img width="964" alt="Markup 2020-05-10 at 16 10 55" src="https://user-images.githubusercontent.com/51966986/81503022-46b44800-92d9-11ea-9990-2ca264a28c4d.png">

#### Context / Source

#20984698-hc

**Comment by Addison-Stavlo** [comment]
🤔  Did this previously work at one point?  The channel url is much different than embedding a video or a playlist.  I think if you want to 'embed a channel' you need to embed a playlist of the channel's content.

Youtube content URLs are constructed in some variation of the following: 
* Single video: `https://www.youtube.com/watch?` + `v=videoID`
* Playlist: `https://www.youtube.com/watch?` + `v=firstVideoID` + `&list=playListID`

Unfortunately, it seems the channel URL doesn't provide what is needed to embed the media.

I believe you can actually use the channel ID ( `UCsXVk37bltHxD1rDPwtNM8Q` in your example) as the playListId.  But it doesn't seem that youtube has a simple way to just copy a link to do this like you can for a single video or playlist.

As far as I can tell the simplest way to embed a channel's content would be to goto the channels list of playlists, copy the link address of the one you want to start with:

![Screen Shot 2020-05-12 at 6 03 41 PM](https://user-images.githubusercontent.com/28742426/81750481-929ef280-947b-11ea-86ee-bbb46243f805.png)

and then replace the `list` param (playListID mentioned earlier) with the channels ID.  That way the playlist becomes the entire channel.

I hope this helps.  It does seem like a bit of a pain to have to do it this way, but currently I'm not quite sure what the alternative is.

**Comment by sirreal** [comment]
@Addison-Stavlo's analysis seems accurate to me. As I understand, YouTube channels are collections of content, any number of videos and playlists. As such, embedding a channel doesn't make sense like dmbedding a video or playlist does.

This doesn't seem to be a bug so I'll close. Please reopen or comment if you disagree.
