### ISSUE TITLE
Remove G Suite promo on stats page

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#42047]
## Description

@nickmomrik reported that he see's this banner come up at least once a week in the Mac desktop app:

![Screen Shot 2020-05-11 at 8 22 12 AM](https://user-images.githubusercontent.com/5634774/81564148-4a8dac00-9365-11ea-93cf-69e5eb640815.png)

Let's go ahead and remove this banner completely from the stats screen. We now have a link in Quick Links on My Home that promotes adding email.

**Comment by davemart-in** [comment]
@rralian mentioned that Cobalt team was going to dig into this one.

**Comment by stephanethomas** [comment]
The banner has been disabled on March 20, then all the code was removed on April 30:

https://github.com/Automattic/wp-calypso/pull/40338

https://github.com/Automattic/wp-calypso/pull/41565

We're talking about the Mac desktop app though, so I suspect it is running an old version of Calypso. Given that the screenshot shows an old copy, I bet it's quite old.

**Comment by davemart-in** [comment]
Thanks @stephanethomas! That is exactly what happened. This should be updated on the 18th during the Desktop apps regular Calypso update. Closing this issue out.
