### ISSUE TITLE
Marketing and Earn cards use similar but different patterns; can we standardize?

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#42058]
Compare the cards on the Marketing and Earn pages at `/marketing` and `/earn`: 

<img width="1077" alt="Screen Shot 2020-05-11 at 11 35 11 AM" src="https://user-images.githubusercontent.com/2124984/81580476-7e73cc00-937b-11ea-823f-d8700a26be5c.png">
<img width="1095" alt="Screen Shot 2020-05-11 at 11 35 00 AM" src="https://user-images.githubusercontent.com/2124984/81580484-80d62600-937b-11ea-90d4-5255e25cc333.png">

One uses regular CTA buttons left-aligned, one uses compact CTA buttons right-aligned. We're looking at removing the use of compact buttons as much as possible, so perhaps we could convert the smaller ones to regular and left align them for consistency.

**Comment by kwight** [comment]
Closing as styles are much more similar now.
