### ISSUE TITLE
FSE Plugin: Add support in Pattern Templates for Pattern Search

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42074]
Support for Pattern Search is available in https://github.com/WordPress/gutenberg/pull/21944 — how might we add support for keywords to our Pattern Templates in the FSE Plugin?

cc @iamtakashi @alaczek

**Comment by iamtakashi** [comment]
In the near future, it'd be great if we can use `categories` and `tags` in the block pattern master site.

**Comment by ianstewart** [comment]
@iamtakashi to start we'll likely want to develop a first go at a list of keywords for each of the patterns.

**Comment by ianstewart** [comment]
Closing this issue as it "just works" with the FSE Plugin. :)
