### ISSUE TITLE
Gutenboarding: Support free plan and paid domain

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#42081]
### Description

A user should be able to select a "Free plan" after having selected a paid domain, and be taken to the checkout to pay for the domain.

![free-plan-forever](https://user-images.githubusercontent.com/6458278/81626909-4c786d80-9440-11ea-8434-3789a2f5858c.gif)

![nodomainforyou](https://user-images.githubusercontent.com/6458278/81627177-f35d0980-9440-11ea-8c78-3b434b4acd8b.gif)

### Steps to reproduce

1. At wordpress.com/new select a paid domain
2. Open the plans modal and try to select and confirm a free plan
3. Carry on and create an account
4. Select a free account 

#### What I expected

- **At step 2**: I should be able to downgrade the selection to Free
- **At step 4**: When I select free account I still expect to pay for the domain I selected, or be told that I can't have a domain without a paid plan.

**Comment by ramonjd** [comment]
> At step 2: I should be able to downgrade the selection to Free
> At step 4: When I select free account I still expect to pay for the domain I selected, or be told that I can't have a domain without a paid plan.

Seems like something to address these points are in the works anyway.

We’ll support free plan + paid domain in the future.

See chats:

p1589246038331100-slack-CNMU1UHHB

p1589185382130000-slack-CNMU1UHHB

**Comment by simison** [comment]
I think we chose not to implement this just yet. It'll need designs from @dubielzyk regardless.

**Comment by dubielzyk** [comment]
We got designs for this in the Figma file already :)

**Comment by razvanpapadopol** [comment]
@simison how's the status of domain-only flow? Are we going to support it in site creation or launch flows?
