### ISSUE TITLE
Gutenboarding: Multiple sites created

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#42086]
#### Steps to reproduce

1. Starting at URL: wordpress.com/new
2. Select a paid plan and then continue with Gutenboarding flow.
3. At the checkout page, either complete transaction or exit checkout by clearing the cart.
4. Once inside Calypso, click the My Sites option to see the sites owned by the new user.

#### What I expected

To see only one site

#### What happened instead

I saw multiple sites were created

#### Browser / OS version

Mac + Chrome

#### Screenshot / Video

Video recording - https://d.pr/v/rmarYB

<img width="1006" alt="Screenshot 2020-05-12 at 10 34 10 AM" src="https://user-images.githubusercontent.com/1269602/81640449-3072cd00-943c-11ea-8a53-3b53987bb85f.png">

#### Context / Source

 #dogfooding, #manual-testing

**Comment by p-jackson** [comment]
Just confirming the reproduce steps above: from my testing it looks like this only occurs when it's a new user, and they choose a paid plan.

**Comment by p-jackson** [comment]
Fix shipped in #42028
