### ISSUE TITLE
Vertical input and site name fields accept rich text pasting

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#42117]
#### Steps to reproduce

1. Go to /new
2. Paste something rich in either field.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/17054134/81727539-69855e80-9489-11ea-8bc5-46b60e2e806c.png)

**Comment by razvanpapadopol** [comment]
Fixed when we switched to using regular `<input/>` element.
