### ISSUE TITLE
Bug: Blog Deletion on Web is not Mirrored on Calypso

### ISSUE THREAD

**Issue by jbcoder** [Automattic/wp-calypso#4212]
#### Steps to reproduce
1. I created a blog on the web
2. Installed wp-calypso on my local environment
3. Deleted the blogs on the web since they were just tests for exploring
4. Now the blog won't go away on wp-calypso. Instead I'm just getting errors saying that methods aren't allowed and that I'm not authorized to access certain settings.

#### What I expected
I expected it to communicate with the server to recognize that it is no longer in my account and notify me on wp-calypso.

#### What happened instead
wp-calypso is acting like nothing happened and still has my blog and posts accessible but is throwing me errors.

#### Browser / OS version
Chrome / OSX

**Comment by lancewillett** [comment]
Hi jbcoder — could you share the exact errors you're seeing?

**Comment by lancewillett** [comment]
I couldn't repeat this in a local Calypso install.

If you have more information please post it here and re-open the ticket. Thanks!
