### ISSUE TITLE
Earn: Recurring Payments "Edit" Payment Plan primary action language

### ISSUE THREAD

**Issue by beaucollins** [Automattic/wp-calypso#42122]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/earn/payments-plans/SITE
2. Click ellipsis button then click "Edit"
3. Modal displays with action buttons labeled "Cancel" and "Edit"

<img width="806" alt="image" src="https://user-images.githubusercontent.com/19795/81732744-c4956200-9445-11ea-9d7c-dbc432ce78f2.png">

#### What I expected

The label "Edit" caused confusion on the primary action button. I would expect something like "Save" or "Update".

**Comment by kwight** [comment]
Fixed at some point:

<img width="1076" alt="Screen Shot 2020-09-09 at 9 47 03 AM" src="https://user-images.githubusercontent.com/349751/92628321-7a03e500-f281-11ea-949a-e2e92ddbb3b4.png">
