### ISSUE TITLE
Gutenboarding: Adjust the design sort order relative to topic

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42121]
The Gutenboarding flow starts out asking users to tell us what their site is about.

![image](https://user-images.githubusercontent.com/545779/81730771-a3d40900-9453-11ea-93ba-d346803e5a68.png)

https://github.com/Automattic/wp-calypso/issues/42120 proposes we immediately add 10+ starter designs that were created to visually map to topics such as those we expect to see in Gutenboarding. With the addition of those designs we would have enough designs available to experiment with tying the sort order of designs to the "topic" we ask users to fill out when starting the flow.

For example, the following designs could be given priority in the sort order for "food" topics.

![image](https://user-images.githubusercontent.com/545779/81731495-9f5c2000-9454-11ea-8b4d-344937127c0b.png)

Similar choices could be made for our most popular "topics" today and in the near future as we add more starter designs. Blog designs, for example, could be given priority when someone uses "blog" or "blogging" in a topic.

cc @dubielzyk @iamtakashi @alaczek

**Comment by ianstewart** [comment]
@ollierozdarz I think this one is on your radar now. :)

**Comment by ollierozdarz** [comment]
@ianstewart yep! 🙂 This should be taken care of in the Goals intent work.
