### ISSUE TITLE
Gutenboarding: show domain hint in header on mobile

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#42123]
Part of https://github.com/Automattic/wp-calypso/issues/41435

When a domain suggestion is available we should display the domain name hint instead of current static text on mobile.

#### What I expected
<img width="597" alt="Screenshot 2020-05-12 at 22 08 53" src="https://user-images.githubusercontent.com/14192054/81735240-6c8a4a00-949d-11ea-8a54-c328769b19fd.png">

#### What happened instead
<img width="337" alt="Screenshot 2020-05-12 at 22 09 43" src="https://user-images.githubusercontent.com/14192054/81735200-5aa8a700-949d-11ea-8bb0-0d0c7d2d49d6.png">

**Comment by razvanpapadopol** [comment]
On smaller screens, depending on the domain name, there isn't always enough space to display the hint on one line.

<img width="333" alt="Screenshot 2020-05-12 at 19 26 17" src="https://user-images.githubusercontent.com/14192054/81735635-018d4300-949e-11ea-84f5-e2faab1ea964.png">

@dubielzyk how do you think we should we tackle this?

**Comment by dubielzyk** [comment]
The "Domain available" was my take on avoiding the string being too long for when it says "yoursitename.com is available". Though it's not ideal I think it's very likely to chop off the "... is available" leaving users perhaps thinking where the domain suggestion came from when they just see that in isolation. I say we hold off on this change for a bit until we've found a better way of solving it.

**Comment by simison** [comment]
Would _"Available: domain-na..."_  work?

**Comment by simison** [comment]
I suppose if we would have a way to detect that it's not clipped, we could show the full text. 🤔  That might get a bit complex tho.

**Comment by dubielzyk** [comment]
> Would _"Available: domain-na..."_ work?

As long as it translates to other languages. I don't think the _Domain available_ is that bad. It's probably unlikely that users will scale the browser and see the inconsistency between the copy.

If someone feels strongly I'm okay with changing it 😊

**Comment by razvanpapadopol** [comment]
> I suppose if we would have a way to detect that it's not clipped, we could show the full text. 🤔 That might get a bit complex tho.

Actually we already have a HoC for detecting size of a DOM node and few ausages in Calypso.

At initial load and with every automatic update of the domain picker (based on site title input change for example) we could do the following:
- set `{visibility: hidden}` on Domain Picker button.
- render the full domain hint text without hiding the overflow.
- measure domain hint, Domain Picker container (all available space) and compare the two.
- only if the hint is too large, replace it with the static text.
- set `{visibility: visible}` on Domain Picker button.

**Comment by yansern** [comment]
> Actually we already have a HoC for detecting size of a DOM node and few ausages in Calypso.

@razvanpapadopol Thanks! Could be useful.

**Comment by razvanpapadopol** [comment]
From what I can see, we're now showing the domain hint when it's available on every device. cc: @ollierozdarz to be aware of some of the history behind this piece of UI.
