### ISSUE TITLE
Desktop: Style missing on Login, Reader, Stats

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-calypso#4215]
The Desktop app has several Calypso styling issues, probably related and potentially PR #4148 might fix it. The three known pages with issues are:

- [ ] Login Page
- [x] Reader, fixed in #4148 
- [x] Stats, fixed in #4148 

Screen shots of each:
<img width="811" alt="screen shot 2016-03-21 at 2 08 46 pm" src="https://cloud.githubusercontent.com/assets/45363/13960699/9a8e780c-f016-11e5-9672-3ab1c3f84ac5.png">
<img width="1074" alt="screen shot 2016-03-21 at 10 02 20 am" src="https://cloud.githubusercontent.com/assets/45363/13960698/9a8435cc-f016-11e5-83cd-cef4ca981f51.png">
<img width="1072" alt="screen shot 2016-03-21 at 10 03 16 am" src="https://cloud.githubusercontent.com/assets/45363/13960700/9a985fb6-f016-11e5-8e55-1b40ec7c011f.png">

**Comment by jasmussen** [comment]
This PR (https://github.com/Automattic/wp-calypso/pull/4337) fixes the remaining login screen issue. 
The regression, it turns out, was primarily caused by `client/auth/login.jsx` having its `is-section-login` renamed to `is-section-auth`.
