### ISSUE TITLE
Sharing Buttons: Print and PDF button loading insecurely, and breaking SSL

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#42151]
A user reported that their site wasn't loading securely, over `https`. The domain has a SSL certificate provisioned, and yet posts and pages raise this warning in browsers (or similar):

![2939571-zen_SSL](https://user-images.githubusercontent.com/2912202/81802257-64beba00-951e-11ea-9124-0ba45d171f72.png)

#### Steps to reproduce

1. Starting at the user's site (see ticket for links)
2. Noting that the homepage loads securely
3. When I view a post or page, I see the warning
4. Noting that only single posts and pages display sharing buttons

#### What I expected

The site should load using SSL when a SSL certificate is provisioned for the domain.

#### What happened instead

The Print and PDF sharing icon loads using `http`, and this partially breaks the browser's SSL connection to the site.

#### Browser / OS version

Firefox Developer Edition, v77.0b3
macOS 10.15.4

#### Screenshot / Video

You can see the path that the icon loads at, here:

![2939571-zen_sharing_icon](https://user-images.githubusercontent.com/2912202/81802282-70aa7c00-951e-11ea-8f15-1b04ea11c064.png)

You can see the button option in _Tools_ > _Marketing_ > _Sharing Buttons_, here:

![2939571-zen_sharing_button](https://user-images.githubusercontent.com/2912202/81802298-7902b700-951e-11ea-9ce5-e84587e5c884.png)

#### Context / Source

User report in 2939571-zen

**Comment by klimeryk** [comment]
Removing the `Domains` label, as the SSL provisioning is working properly - this seems like a bug with a hardcoded `http` somewhere in the Sharing code.

**Comment by sgomes** [comment]
I can't seem to find anything related to "Print & PDF" or `printfriendly.com` anywhere in Jetpack or Calypso, and the option doesn't show up for me in any of my test sites. Is this perhaps added by a plugin?

**Comment by sgomes** [comment]
@pauljacobson: this service was probably manually added by the user via the "Add a new service" option in `wp-admin` -> Settings -> Sharing. The user will need to go in, remove the manually added service, and add it again with a `https://` URL.

I'm not sure which set of instructions they followed in the past, but it was probably something similar to https://en.calameo.com/read/001980118db38d0a5eea9

**Comment by sgomes** [comment]
Closing issue, as it seems unrelated to our sharing code, as explained above.
