### ISSUE TITLE
FSE Plugin: Add core support for preferred pattern viewport size

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42165]
See https://github.com/WordPress/gutenberg/pull/22216 that fixes https://github.com/WordPress/gutenberg/issues/22147

Adding support for this will improve the visual experience of our pattern library.

**Comment by ianstewart** [comment]
@iamtakashi would you be able to provide a list of the preferred viewport sizes for the patterns that need them?

**Comment by iamtakashi** [comment]
Most of our patterns are full-width "sections" at the moment. Can we try `1280` for all the patterns?  If `1280` is too large for some patterns, we can try `960`. 

I tried to mockup with `1280` case, but it was hard to judge by faking with screenshots. I think it'd be easier to see them in practice.

**Comment by iamtakashi** [comment]
Can this be picked up soon? As we have more patterns, I see more patterns that could be better represented with a wider viewport for the preview.
