### ISSUE TITLE
Credits need to not have a $0 item_original_cost_integer to prevent displaying them as discounted

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#42168]
![discounted-credits](https://user-images.githubusercontent.com/2036909/81833237-777cc300-950d-11ea-8644-9dfdf8c446cb.png)

How it looks in old checkout:

![old-checkout-credits](https://user-images.githubusercontent.com/2036909/81833381-a1ce8080-950d-11ea-89bd-bb866762431d.png)

**Comment by nbloomf** [comment]
Fixed by #42531
