### ISSUE TITLE
Make the 'Free Plan' seem clickable and have a call to action

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#42166]
In Gutenboarding can we try the following improvements to the Plans Icon

- When the user has not interacted with the element, it says 'Free Plan' with an 'Upgrade' button next to it. This can be persistent or disappear. I don't feel strongly.
- The Free Plan element should look more like a button - right now it's not clearly clickable
- When you transition from a free plan to another plan (e.g. when selecting a domain) there should be a nice transition animation to the other plan
- Consider having a visual treatment for paid plans (e.g. a gold background) that looks nicer than the free plan.

**Comment by dubielzyk** [comment]
This is fixed now
