### ISSUE TITLE
Gutenboarding: acquire intent placeholder line jumps

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#42160]
When the input is empty we show a gray placeholder line for both vertical and site title inputs.
#### What I expected
* When typing the first character, the coloured underline we display under the input value should be in the same position as the placeholder line.

#### What happened instead
* The placeholder grey line is displayed a few pixels below the coloured underline position so a jump can be seen when typing the first character in an empty input field.

#### Screenshot / Video
https://cloudup.com/cRc12ecdjzH

**Comment by andrewserong** [comment]
@razvanpapadopol I believe we've fixed this one now in #42197 (I added in a change to fix the site title placeholder today, too). Do you mind double-checking on master that's working as you'd expect it to?

**Comment by razvanpapadopol** [comment]
Fixed in #42197
