### ISSUE TITLE
Need escape hatch if you don't make a payment in checkout

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#42186]
If you are a new gutenboarding user, and pick a premium plan but don't complete payment in checkout, you have nowhere to go and have to 'go back' on your browser to visit your free site. 

Instead of this, can we consider something that alerts the user that they are going to lose their premium domain and that we can't reserve it for them anymore and allow them to see their site and pay later. 

Tagging @simison for triaging

**Comment by simison** [comment]
Thanks!

We'll need to test how this behaves right out from onboarding when buying a domain vs in pre-launch flow, as it can be different.

The back button was quite buggy on onboarding so we had to hide it there as a quicker fix. That might’ve hidden it also for the launch flow where it might work just fine. @razvanpapadopol do you remember details?

**Comment by amamujee** [comment]
This will become important to get right if we decide to show the plans screen to all users.

**Comment by simison** [comment]
This has been since sorted out, and there's "X" to close checkout now. cc @razvanpapadopol
