### ISSUE TITLE
Site Settings: Clarify Privacy Settings

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#42180]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/settings
2. Note the language on search engine settings implies we can control whether search engines can access the site.

#### What I expected
Here's the warning from wp-admin, which is more accurate:

> Discourage search engines from indexing this site
> Note: Neither of these options blocks access to your site — it is up to search engines to honor your request.

#### What happened instead
People are confused if their site somehow "ends up on the web" anyway.

#### Context / Source
A user deleted their site, account, and email address that was associated with the account. Later, they found out archive.org still had a copy of the site. And archive.org naturally doesn't want to remove the archive unless the original owner requests it.

The user is upset because they thought ticking that box would protect the site from being indexed anywhere. Seems an adjustment to the language there might help.
https://wordpress.com/forums/topic/internet-archive-copyright-infringement/#post-3489920

**Comment by hrrsppzgl** [comment]
In my opinion `Do not allow search engines to index my site` should actually work! We may add the wording you suggest as a precautionary measure but we still need to dig why that site got indexed. A quick search reveals that while `<meta name="robots" content="noindex, follow">` is correctly added (`nofollow` would certainly be better) to the site `<head>` we also add `Disallow: /` in robots.txt. The latter seems a good strategy, but Google suggests otherwise
[https://support.google.com/webmasters/answer/93710?hl=en#:~:text=Block%20search%20indexing%20with%20'noindex',header%20in%20the%20HTTP%20request.](https://support.google.com/webmasters/answer/93710?hl=en#:~:text=Block%20search%20indexing%20with%20'noindex',header%20in%20the%20HTTP%20request.)

> Important! For the noindex directive to be effective, the page must not be blocked by a robots.txt file. If the page is blocked by a robots.txt file, the crawler will never see the noindex directive, and the page can still appear in search results, for example if other pages link to it.

**Comment by supernovia** [comment]
If someone has their site set to discourage search engines, this is what the robots.txt will say:

User-agent: *
Disallow: /

**Comment by mreishus** [comment]
A little research based on the notes above:

##  Is the box working correctly?

It seems to be working in my testing.

**robots.txt, Checkbox off:**
```
# If you are regularly crawling WordPress.com sites, please use our firehose to receive real-time push updates instead.
# Please see https://developer.wordpress.com/docs/firehose/ for more details.

Sitemap: https://testsite11mmr.wordpress.com/sitemap.xml
Sitemap: https://testsite11mmr.wordpress.com/news-sitemap.xml

User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
Disallow: /wp-login.php
Disallow: /wp-signup.php
Disallow: /press-this.php
Disallow: /remote-login.php
Disallow: /activate/
Disallow: /cgi-bin/
Disallow: /mshots/v1/
Disallow: /next/
Disallow: /public.api/

# This file was generated on Tue, 28 Jul 2020 21:29:51 +0000
```

**Robots.txt, checkbox on:**
```
User-agent: *
Disallow: /
```

**Meta robots, checkbox off:**
_(No entry found.)_

**Meta robots, checkbox on:**
`<meta name='robots' content='noindex,nofollow' />`

## Does archive.org honor robots.txt?

From [this blog post](https://blog.archive.org/2017/04/17/robots-txt-meant-for-search-engines-dont-work-well-for-web-archives/) titled *"Robots.txt meant for search engines don’t work well for web archives"*, it sounds like they either no longer honor it, or plan to stop honoring it in the future.

## Is there another way to block a site from archive.org?

According to [their help page](https://help.archive.org/hc/en-us/articles/360004651732-Using-The-Wayback-Machine), they want an email requesting exclusion.

>How can I exclude or remove my site's pages from the Wayback Machine?

>You can send an email request for us to review to info@archive.org with the URL (web address) in the text of your message.

## Next Steps

I'll work on a pull request to bring the calypso wording in line with the wp-admin wording.

**Comment by mreishus** [comment]
Added PR https://github.com/Automattic/wp-calypso/pull/44527
