### ISSUE TITLE
Plugin Updates: Gutenberg v8.1.0

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#42199]
Gutenberg v8.1.0 RC 1 [was released on May 14, 2020](https://github.com/WordPress/gutenberg/releases/tag/v8.1.0).

This issue tracks progress upgrading wpcom and issues to address along the way.

The previous stable release on WordPress.com was 8.0.0. Tracking issue: https://github.com/Automattic/wp-calypso/issues/41504

## Gutenberg

* [x] Install version 8.1.0 (D43429-code)
* [x] Activate version 8.1.0 on edge sites (D42687-code)
* [x] Activate final version 8.1.0 in production (D43438-code)
* [x] Request update for AT sites (p9o2xV-Sq-p2)
* [x] Revert this 8.0.0 bugfix in FSE https://github.com/Automattic/wp-calypso/pull/41992
     https://github.com/Automattic/wp-calypso/pull/42201
     It should no longer be needed in 8.1.0 (please confirm)
* [x] Close Social Icons issue #41903 (confirm it is solved on 8.1) 
* [x] Clean up old versions of GB:
     - [x] `7.8.1` (D43439-code)
     - [x] `8.1.0-*` pre-releases (D43440-code)

## Other

* [x] Call for testing: p7DVsv-8Dr-p2
* [x] E2E tests against RC 1: https://github.com/Automattic/wp-calypso/pull/42080
* [x] E2E tests stable version PR: https://github.com/Automattic/wp-calypso/pull/42202

## Bugs encountered 🐛
* [ ] Video block upgrade notice regression on free sites. [#15796](https://github.com/Automattic/jetpack/issues/15796)

**Comment by ockham** [comment]
I think we're done here :grimacing: :tada:
