### ISSUE TITLE
Gutenboarding tracks not recording step_enter and step_leave correctly in safari

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#42193]
Debug events by entering `localStorage.debug='calypso:analytics'` in console.

This one is interesting, when going from `IntentGathering` to `DesignSelection` steps, we should see 
```
step_leave ( intent_gathering )
step_enter ( design_selection )
```
and then when using the "Go Back" button, we should see
```
step_leave ( design_selection )
step_enter ( intent_gathering )
```
In safari, sometimes the correct events are recorded, but sometimes we see things such as
```
step_leave ( intent_gathering )
step_leave ( intent_gathering )
```
Other times the leave event will fail to fire.

#### Steps to reproduce

Open safari on `/new`, open the network tab, select *Preserve Log* and filter for `t.gif`

Click back and forth between the `intent_gathering` and `design_selection` pages

Watch the recorded events closely

Think about your life choices and why this kind of thing keeps happening to you

**Comment by razvanpapadopol** [comment]
I couldn't reproduce this but instead found that filter in Safari's network tab doesn't return expected results. So when filtering by `t.gif` I get only a subset of requests but when filtering for a specific event (eg: `calypso_newsite_step_enter`) I get all of them.

**Comment by roo2** [comment]
oops, this was not an issue, I was seeing that because of a strange behavior in safari's dev tools when you filter for `t.gif` not all of the results are shown! thanks for discovering that @razvanpapadopol
