### ISSUE TITLE
Gutenboarding: Add restaurant starter layout

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#42208]
I have put together a delivery page for a small burger place with the block patterns, and we thought it'd be nice if this is available as a starter layout in Gutenboarding.

![screencapture-blockpatterns489018373-wordpress-2020-05-14-13_46_40](https://user-images.githubusercontent.com/908665/81936641-7e2d3800-95ea-11ea-9856-8178c1a1d553.jpg)

It's been built here: https://blockpatterns489018373.wordpress.com/ (publicly accessible)

cc @ianstewart @dubielzyk

**Comment by simison** [comment]
cc @johnHackworth @olaolusoga

**Comment by olaolusoga** [comment]
Nice. Thanks for putting this together @iamtakashi .

**Comment by ianstewart** [comment]
@ramonjd @dubielzyk any reason not to add this one to the gutenboarding design screen?

**Comment by ramonjd** [comment]
Is this any different to "Gibbs" from https://github.com/Automattic/wp-calypso/pull/42354

<img width="527" alt="Screen Shot 2020-06-05 at 10 26 13 am" src="https://user-images.githubusercontent.com/6458278/83823306-0e0c6080-a717-11ea-95e6-2de35693481e.png">


See: https://hash-7adbea70aae92560a8d0e58a9b5659221d9c758b.calypso.live/new/design

I'm pretty sure I pulled the export from https://blockpatterns489018373.wordpress.com/ 

That's what my 🧠 is telling me anyway. Don't trust it.

**Comment by ianstewart** [comment]
Oh. Perfect. No different. That PR should close this issue. :)

**Comment by ramonjd** [comment]
I've launched the designs into horizon for testing. 

Following up with some small tasks before they go into prod: https://github.com/Automattic/wp-calypso/issues/43420
