### ISSUE TITLE
Plans: show contextual nudge on stats for google analytics

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4222]
We chatted about this a bit in our HO... would be good to make this contextual, possibly by behavior... for example if we knew (I'm making this up) that people who clicked to expand the *countries* card are more likely to find google analytics to be particularly helpful, we could show this contextually to them.

/cc @jonathansadowski wondering if you have any suggestions. Is there a natural place where GA comes in and is extra helpful for people that want something extra beyond our regular stats?

**Comment by artpi** [comment]
I have a following design concept:
On the bottom of every stats page that IS NOT /insights

Will start on a PR to see how it looks

**Comment by jonathansadowski** [comment]
@rralian, as you pointed out, there's more granularities to the geostats that GA offers -- also, there's the ability to hook GA into Webmaster Tools and see actual search terms, so perhaps highlighting that to people attempting to utilize the Search Terms module makes sense.

**Comment by adambbecker** [comment]
@artpi: Took a look at both #4288 & #4296 which both are looking pretty cool.

I think we should just roll with one at first and would probably suggest #4288. I think these contextual nudges are pretty cool, but probably need to be treated pretty carefully and would want to slowly roll them out for fear of overloading on them.

**Comment by artpi** [comment]
All the PRs merged and deployed
