### ISSUE TITLE
CoBlocks Masonry block: vertical alignment issues when inserted as a reusable block

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#42235]
#### Steps to reproduce

1. Create a Coblocks Masonry block with two or more images as a reusable block.
2. Insert said block on a page or post.
3. Save and view the resulting page.

#### What I expected
Vertical alignment of images in the block.

#### What happened instead
Horizontal alignment of images in block. See context/source section; if JS isn't loading properly with reusable blocks, this might affect more than just the Masonry block.

#### Browser / OS version
Chrome 81.0.4044.138, macOS 10.15.2

#### Screenshot / Video
Masonry block in reusable blocks:
![image](https://user-images.githubusercontent.com/32492176/81980532-05c77680-95ec-11ea-9f3c-63bae4c901c0.png)

Reusable block in post:
![image](https://user-images.githubusercontent.com/32492176/81980563-1546bf80-95ec-11ea-917d-aeb5b695fa5c.png)

Live site:
![image](https://user-images.githubusercontent.com/32492176/81980629-34dde800-95ec-11ea-9390-149a92d562e6.png)

#### Context / Source
Originally reported in 21099332-hc.

It appears perhaps some related JS isn't loading when the block is inserted as a reusable block, as it doesn't have the same inline styles that a Masonry block shows during normal use.

Further supporting that, if a Masonry block is placed directly in the page (along with the reusable block), the reusable block works as expected.

Masonry block + Reusable block in editor:
![image](https://user-images.githubusercontent.com/32492176/81980857-9dc56000-95ec-11ea-8a8a-d90f660c5365.png)

Masonry block + Reusable block on live site:
![image](https://user-images.githubusercontent.com/32492176/81980890-acac1280-95ec-11ea-9ac3-471a2612d8e4.png)

**Comment by simison** [comment]
FYI @Automattic/ajax

**Comment by obenland** [comment]
I was able to reproduce that in Atomic and on a local install. This seems to be a bug in CoBlocks itself.

**Comment by obenland** [comment]
Reported in https://github.com/godaddy-wordpress/coblocks/issues/1491.
