### ISSUE TITLE
Question: Unable to run wp-calypso locally

### ISSUE THREAD

**Issue by PavithraChidambaram** [Automattic/wp-calypso#42242]
#### Title
Unable to run `wp-calypso` locally using instructions at https://github.com/Automattic/wp-calypso/blob/master/docs/install.md#prerequisites

#### Steps to reproduce

1. Download/ clone `wp-calypso`
2. `cd wp-calypso`
3. `yarn start`

#### OS version
Ensured versions follow requirements at https://github.com/Automattic/wp-calypso/blob/master/package.json#L49-L52

OS => macOS HighSierra 10.13.6
node => v12.16.1
yarn => 1.22.4

#### Context

I'm a aspiring/new contributor to `wp-calypso` and to Automattic. So this is my first time working with this package :) , hence I'm not entirely sure if I'm missing some basic steps,  therefore I'm raising this as a Question.

#### Details/Description:
Trying to clone `wp-calypso` package locally and follow the instructions at https://github.com/Automattic/wp-calypso/blob/master/docs/install.md#prerequisites. Tried running `yarn start` and faced the following series of errors:

```
yarn start
yarn run v1.22.4
$ check-npm-client && npx check-node-version --package && yarn run install-if-deps-outdated && node bin/welcome.js
/bin/sh: check-npm-client: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

used `npm i check-npm-client` to install the missing dependency and ran `yarn start` again.

```
yarn run v1.22.4
$ check-npm-client && npx check-node-version --package && yarn run install-if-deps-outdated && node bin/welcome.js
npx: installed 13 in 1.955s
$ check-npm-client && node bin/install-if-deps-outdated.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /Users/pavithrachidambarampappa/Downloads/wp-calypso-master/bin/welcome.js
```

Figured out that chalk is required at `bin/welcome.js` before yarn installs chalk. So installed chalk using `npm install chalk` and again proceeded with `yarn start`

```
yarn run v1.22.4
$ check-npm-client && npx check-node-version --package && yarn run install-if-deps-outdated && node bin/welcome.js
npx: installed 13 in 1.556s
$ check-npm-client && node bin/install-if-deps-outdated.js
             _                           
    ___ __ _| |_   _ _ __  ___  ___      
   / __/ _` | | | | | '_ \/ __|/ _ \ 
  | (_| (_| | | |_| | |_) \__ \ (_) |  
   \___\__,_|_|\__, | .__/|___/\___/ 
               |___/|_|                

$ check-npm-client && yarn run -s build
$ check-npm-client && node bin/install-if-deps-outdated.js
$ check-npm-client && npx ncp static public
npx: installed 1 in 0.911s
$ check-npm-client && npx lerna run prepare --stream
npx: installed 750 in 19.634s
lerna notice cli v3.21.0
lerna info versioning independent
lerna info Executing command in 19 packages: "yarn run prepare"
(node:76151) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
@automattic/components: $ check-npm-client && transpile && tsc && copy-assets
i18n-calypso: $ check-npm-client && transpile
@automattic/media-library: $ check-npm-client && transpile && tsc && copy-assets
@automattic/popup-monitor: $ transpile
@automattic/calypso-color-schemes: $ check-npm-client && node bin/prepare-sass-assets.js && node bin/build-css.js
wpcom-proxy-request: $ check-npm-client && transpile
@automattic/composite-checkout: $ check-npm-client && transpile
@automattic/popup-monitor: /bin/sh: transpile: command not found
@automattic/components: /bin/sh: transpile: command not found
@automattic/load-script: $ check-npm-client && transpile
@automattic/popup-monitor: error Command failed with exit code 127.
@automattic/popup-monitor: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prepare exited 127 in '@automattic/popup-monitor'
lerna WARN complete Waiting for 12 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
``` 

At this point I'm pretty positive that there's a high chance I'm missing on something basic. Checked to ensure this is not mentioned at https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md. Would appreciate any help/guidance on the above.

**Comment by Aurorum** [comment]
Does running `yarn` as a command on its own before `yarn start` and after `cd wp-calypso` help?

**Comment by PavithraChidambaram** [comment]
Thanks @Aurorum ! That helped resolve the above issues. I'm able to build and start `wp-calpso` without any issues. I've raised https://github.com/Automattic/wp-calypso/pull/42282 to include this problem and the fix to the troubleshooting docs, since it might be helpful for other beginners.
