### ISSUE TITLE
Gutenboarding: Update registered tracks events

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#42250]
We need to update and register new events introduced in:
- [x] #42099
- [x] #42245
- [x] #42188
- [x] #43136

**Comment by razvanpapadopol** [comment]
Opened PRs for events added and updated in #42099
https://github.com/Automattic/tracks-events-registration/pull/265
https://github.com/Automattic/tracks-events-registration/pull/266
https://github.com/Automattic/tracks-events-registration/pull/267
https://github.com/Automattic/tracks-events-registration/pull/268
https://github.com/Automattic/tracks-events-registration/pull/269
https://github.com/Automattic/tracks-events-registration/pull/270

**Comment by razvanpapadopol** [comment]
registration for #42245:
https://github.com/Automattic/tracks-events-registration/pull/271

**Comment by simison** [comment]
Seems like all done here! :-)
