### ISSUE TITLE
Gutenboarding: Consistent position for plans show more/less toggling button.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#42252]
> I kinda feel that the table should be below the Show more/Show Less. This way you can toggle hiding and showing from the same button. Currently, the button disappears (visually) and you'll have to look for it to "show less".

_Originally posted by @alshakero in https://github.com/Automattic/wp-calypso/pull/42144_

**Comment by razvanpapadopol** [comment]
There is no more toggling button in current version.
