### ISSUE TITLE
Plans: remove ads landing page should retain selected site

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4227]
If you follow the "remove ads" upgrade link.

![remove ads](https://cloudup.com/cw7-P4ZTfWE+)

It takes you to a "remove ads" landing page.

![remove ads landing](https://cloudup.com/cNhJRkZyozm+)

And if you follow those links, it takes you to the generic plans page where you have to select a site. That's a bummer because we know which site you were clicking from. We should retain that through the process.

![plans upgrade site selector](https://cloudup.com/cUqUt1snUNQ+)

I also think it would be interesting to test performance of skipping the remove-ads-landing-page and linking directly to the plans page with a custom message on the plans page. There might be some prior tests already performed here. Not sure who to ping to find out... maybe @scruffian? @p3ob7o?

**Comment by scruffian** [comment]
> There might be some prior tests already performed here.

None that I am aware of

**Comment by artpi** [comment]
> I also think it would be interesting to test performance of skipping the remove-ads-landing-page and linking directly to the plans page

I would like to point out, that there is already "Upgrade now" on the button. Why do we even want to stop people before upgrading? Especially that this landing page is mostly copy of plans and on top a message that says what the box already did.

Here is redirection to plans

D2926-code

## Demo

https://cloudup.com/iaEAdRrLKqJ

**Comment by artpi** [comment]
Done
