### ISSUE TITLE
Gutenboarding: Preview is too small

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#42279]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/191598/82060062-d91b6980-9694-11ea-80fe-2d779aea98b1.png">

Once I got to the `/new/style` step, I was underwhelmed with the preview of my new site; The preview area is so small, and scrolls awkwardly. The tablet and mobile previews actually appear larger than the desktop preview.

Also, notice that the tablet and mobile previews cut off the scrollbar.

Here's a GIF showing my experience in action:

![preview scrolling](https://user-images.githubusercontent.com/191598/82060308-31eb0200-9695-11ea-811e-f1c6bd8c9ca4.gif)

**Comment by dubielzyk** [comment]
I think we just need to rethink the layout here as it isn't really working on medium-to-small devices.

**Comment by dubielzyk** [comment]
We're fixing this with the new v2 layout: https://gutenboarding-v2.netlify.app/
