### ISSUE TITLE
Payments Newsletter: Introduce settings in product details

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#42272]
Project: 131-gh-Dotcom-roadmap

- [x]  Introduce settings in the endpoints 

As part of creating paid newsletters, we have to introduce a few options to the product.

In this task, we need to save these options in the product backend:
- `subscribe_as_site_subscriber` that will automatically subscribe user to site subscribers
- ~`subscriber_emails_sent_only_accessible` this setting will work in a following way: DO NOT send to site subscribers emails where they don't have access to the content.~
- `welcome_email_content` - this will be the content added to the welcome email. This will be used in https://github.com/Automattic/wp-calypso/issues/42291

We have to save it in the product meta, in the `billing_connected_account_products` table

The update endpoint is here:  code . a8c . com `/diffusion/WP/browse/trunk/public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-memberships.php$696`

- [ ] Introduce settings in the UI

![Frame](https://user-images.githubusercontent.com/5634774/82116342-159fa180-9737-11ea-8d2a-497f22197829.png)

This code lives here: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/earn/memberships/products.jsx

**Comment by artpi** [comment]
Notes from a call with @gwwar : CC @davemart-in 
- We want to go with plaintext for the welcome email for now because email is bad with html
- How do we want the default of the subscriptions?
- We don't have a toggle for branding
- We'll drop categories from this mock

**Comment by eoigal** [comment]
D43690-code will add these new product settings.

**Comment by mmtr** [comment]
Will work on displaying the settings in the UI.

**Comment by eoigal** [comment]
Followup to fix logic to only subscribe user if they've checked the optin checkbox when subscribing - D43776-code
