### ISSUE TITLE
Jetpack Search: add product specific Thank you modal for WP.com sites.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#42285]
#### What I expected
For WP.com sites, switch the post-checkout Thank you modal to My Home task card. 
Inspiration:

![ins](https://user-images.githubusercontent.com/13561163/82083102-730d0180-96e9-11ea-8a1e-7bfb2a3282b1.png)

**Comment by AnnaMag** [comment]
@rickybanister could you elaborate on the design, please?
Should Thank you step for WP.com sites be a separate modal with the relevant styling or turned into a Card in `/home`?

**Comment by rickybanister** [comment]
Let me pull in @danhauk and @lcollette here. 

Dan can share some mockups of the proposed post-purchase thank you experience (which is similar to what you're showing above). 

If we don't want folks to get distracted by other options on customer home and configure search immediately, then a modal might be more appropriate, but I would use the thank you / task card design as inspiration for the modal content. 

And 'modal' might not be the best word, a page by itself with the setup search task and perhaps some light weight supporting information about the feature might work better than a modal covering some other screen.

**Comment by AnnaMag** [comment]
@danhauk, @lcollette any updates on this?

**Comment by lcollette** [comment]
@AnnaMag Sorry for the delay on this. @olesyabrk has this on her radar and will have an update here by end of the week.

**Comment by olesyabrk** [comment]
@AnnaMag this is the Thank You page you're referring to, correct?
![image](https://user-images.githubusercontent.com/51215741/83811783-51ab8f80-a66f-11ea-9fb4-aaf477c9abe0.png)
![image](https://user-images.githubusercontent.com/51215741/83811844-62f49c00-a66f-11ea-90a6-2310cc6d07e4.png)

**Comment by AnnaMag** [comment]
@olesyabrk the first one, post product purchase, analogous to[ Jetpack experience and message](https://github.com/Automattic/wp-calypso/pull/41384).

**Comment by olesyabrk** [comment]
Here is the traditional Calypso thank you screen.
![MacBook Pro - 1](https://user-images.githubusercontent.com/51215741/84085683-f9d89580-a99a-11ea-9170-2d35ca742835.png)

And here is the same in a new styling used for Customer Home.
![MacBook Pro - 2 (3)](https://user-images.githubusercontent.com/51215741/84086158-0c9f9a00-a99c-11ea-8af6-c8c37a177d56.png)

@rickybanister should we start adapting our new styles?

**Comment by rickybanister** [comment]
Thanks @olesyabrk, yes we should definitely start adapting/adopting the new styles. 

I think I mentioned above that we should be moving the thank you 'page' to be a congratulatory banner on My Home. For standard plan purchases I think that makes the most sense. 

For Jetpack Search, since it's a special add-on with its own flow and it needs to be configured in the customizer for now, I think the stand-alone page makes sense for the time being. 

That said, when full site editing becomes our reality and search becomes just another block it may make sense to land customers on My Home and add a task or checklist item to configure their purchase. 

@AnnaMag maybe we could log that as a future improvement?

**Comment by olesyabrk** [comment]
>I think I mentioned above that we should be moving the thank you 'page' to be a congratulatory banner on My Home. For standard plan purchases I think that makes the most sense.
Agreed, pinging @danhauk to see if a plan Thank You banner is something he's working on. 

>That said, when full site editing becomes our reality and search becomes just another block it may make sense to land customers on My Home and add a task or checklist item to configure their purchase.

Love this idea not only for Jetpack Search, but for all subsequent premium blocks.

**Comment by AnnaMag** [comment]
thanks, everyone! 

@olesyabrk, could you clarify which mock refers to the final design?

**Comment by olesyabrk** [comment]
@AnnaMag yes, of course. Here:

![image](https://user-images.githubusercontent.com/51215741/85064276-3016d180-b160-11ea-96b7-a1c887399489.png)

**Comment by AnnaMag** [comment]
We opted for not including the "Skip" option in the Jetpack versions of the modal to gently direct attention to the Customizer (and experience product value). Shall we keep the "Skip for now" for WP.co sites? If so, where should it point to? /cc @rickybanister, @gibrown

**Comment by olesyabrk** [comment]
Curious to hear back from the cc'ed folks. My two cents are: the "Skip for now" option provides freedom to our users to go back to Customer Home. Coupled with a gentle nudge/reminder at the Customer Home level, we encourage freedom of movement/choice and aren't forcing our customers into a linear path.

**Comment by gibrown** [comment]
@olesyabrk there were two reasons:
1. They bought a specific product, so let's just take them to where they can see it. Also, we are explicitly turning it on for their site, so it feels like we should show them it and take them right to the customizer. It feels like adding a "Skip" at this point is just going to lead them down the wrong path. They can always skip on the next screen.
2. They were JP users and so leaving them in Calypso rarely makes sense since it is kinda an unknown interface to them, so better to return them to their site anyways

(2) mostly doesn't apply, but since our purchases are really going through jetpack.com, hopping back to their site customization seems like a good thing anyways.

**Comment by olesyabrk** [comment]
@gibrown:
> 1. They bought a specific product, so let's just take them to where they can see it. Also, we are explicitly turning it on for their site, so it feels like we should show them it and take them right to the customizer. It feels like adding a "Skip" at this point is just going to lead them down the wrong path. They can always skip on the next screen.

I don't think Skip will lead them down the wrong path. It's a secondary button and if they're planning to use the product and customize it, they will go ahead and do that without being forced to. But say, the user doesn't have the time to dive deeper, Skip will lead them to the Customer Home that will have a reminder to get back to customization at a later point. 

> 2. They were JP users and so leaving them in Calypso rarely makes sense since it is kinda an unknown interface to them, so better to return them to their site anyways

This mock is for dotcom users who are familiar with Calypso and Customer Home, as a hub for notifications and next steps.

**Comment by rickybanister** [comment]
I tend to agree with @gibrown about the skip button. I tend 90% of the time to prefer giving customers a choice, but in this case they may wrongly assume that they have Search active, when in fact they don't. 'Skip for now' won't set up some kind of later reminder for them to visit the customizer (unless we build a mechanism), so it will leave them kind of stuck. We saw the same sort of thing with VaultPress in Jetpack plans. An alarming number of people bought plans and never actually provided credentials so their sites weren't backed up (though they likely assumed it had been done for them). 

If we can circle back and add a task card or notification or email reminder or something then skip does make sense.

**Comment by olesyabrk** [comment]
Yes, without a follow up notice on Customer Home, I will also opt in to remove Skip for now.
