### ISSUE TITLE
Gutenboarding: No way to escape from checkout

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#42281]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/191598/82061217-6f03c400-9696-11ea-9ddb-e7c3426b67bd.png">

Once I hit the checkout screen, I'm stuck. If I discover that my payment info is invalid, or my country not supported, there's no way for me to continue or backtrack.

**Comment by fditrapani** [comment]
Thanks for reporting @shaunandrews. Cc @michaeldcain

**Comment by razvanpapadopol** [comment]
Similar issue for tracking Gutenboarding integration with the new checkout: https://github.com/Automattic/wp-calypso/issues/44219

**Comment by michaeldcain** [comment]
@simison: isn't there a "<- Back" button in Gutenboarding's Checkout that replaces the close button we normally show? Technically, the user can remove the item from the cart to exit Checkout, but I don't think it really addresses what Shaun is pointing out, since it's hidden behind the "edit" button in the first step.

**Comment by razvanpapadopol** [comment]
Yes, in the old checkout we had this _Back_ button added:

<img width="1164" alt="Screenshot 2020-07-23 at 19 48 53" src="https://user-images.githubusercontent.com/14192054/88314628-dd5fa500-cd1d-11ea-8434-f4f017686af9.png">

In the new one, we'll add the top bar as illustrated in https://github.com/Automattic/wp-calypso/issues/44219#issuecomment-659464675 and I assume **W** would be the _Back_ button 🤔 ❓ 
cc: @olaolusoga

**Comment by simison** [comment]
@razvanpapadopol do you remember what's the status of this regarding different flows?

**Comment by razvanpapadopol** [comment]
Shipped an intermediary fix for `/new` in #49567 but we'll keep https://github.com/Automattic/wp-calypso/issues/44219 open until we do something about the design.
