### ISSUE TITLE
Plans: add some persuasive copy to the domains page

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4228]
The current domains page is very light on persuasion. We don't explain the benefits of a custom domain.

![domains page](https://cloudup.com/cdc-VU297oI+)

We'd like to add an informative promo about why getting your own domain is important and what it means. Maybe show a more custom nudge in the interface, like a second row showing an available domain... in this case `bobinprogress2.com` is available, so why not show it immediately?

And here's the "Add a Domain" page.

![add a domain page](https://cloudup.com/cuDxMSkXH0U+)

Maybe we could just combine these two pages into a single interface, versus having a separate "add" page. Would love input from someone on the store team to see if they've tested out similar ideas or have other plans in the works. Make sure we're not stepping on toes. Maybe @rads could chime in?

The ideas above are more about promoting in-context ad-hoc domain purchases and not so much about plans, but we should also show something on the domains page about the fact that purchasing the premium plan comes with a free domain along with many other features.

Feel free to split up this issue into separate issues if appropriate when once someone grabs this.

**Comment by rralian** [comment]
Let's put this in the backlog for now, unless you have some in-progress work that you could push up to show u @retrofox. Otherwise we probably need some design work before we jump into this, so we'll backlog it until it's ready to be worked on.

**Comment by mikeshelton1503** [comment]
I'd like to resurrect this idea as a potential test. Adding to my short list of testing ideas.

**Comment by kriskarkoski** [comment]
Closing as we now have a nudge on setting domain as primary from PWPO work
