### ISSUE TITLE
Plan Pre Selection for Free Users

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#42328]
For users who have not picked a premium domain, can we pre-select no plans (vs. pre selecting the free plan) and grey out the continue button so the user has to make a choice as to which plan they want? 

Right now, it’s too easy to breeze through the plans page without actually making a choice. 

cc @simison for prioritization
cc @dubielzyk for design (if any)

**Comment by dubielzyk** [comment]
This requires the plan being in the flow right? Also, how does the Plan picker button work in this scenario?

**Comment by rickybanister** [comment]
@dubielzyk you're question isn't really an issue now that we've added plans to the flow if you don't otherwise interact with them, right?

And we've already modified the picker button to have a call to action instead of displaying 'free'.
