### ISSUE TITLE
Plans: apply discounts from domain mapping in the same session it is purchased

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4233]
On the plans page, it would be great to give users a discount for their already-purchased items to be applied towards a plan... show this on the plans page.

![plans page](https://cloudup.com/c_txfXsaylv+)

So for example, if they paid $18 for a custom domain, sell the premium plan for $81 instead of $99. Show the savings and explain we are applying their previous purchase for a discount.

I'm actually not positive we don't already have this. I see we already do this if you are upgrading from a premium plan to the business plan. Looks like there is some prior art on the php side with @drewblaisdell @scruffian and @Tug's names on it. Can one of y'all point us in the right direction here?

Would be great to do this for domains as well as premium themes (to upgrade to the business plan).

**Comment by scruffian** [comment]
> I'm actually not positive we don't already have this. I see we already do this if you are upgrading from a premium plan to the business plan. 

We already offer discounts on Premium and Business for users who have a domain, as well as a discount on Business for users who have Premium. In some cases you might need to clear your local storage to see these - we have issues open to ensure that the data is cleared at the appropriate times, so that users will always see these discounts.

**Comment by rralian** [comment]
@scruffian I tested this out a bit by mapping a domain I own to a wpcom site ($13 upgrade, paid with credits). I see that we have the functionality, but I think there's a bug. The discount is not displayed on the plans compare page in the same session in which the domain mapping was purchased. It's shown on the checkout page, although it's discounted by $20 versus $13 as I would expect, and it's really easy to miss the mention of the discount, which is in the sidebar, versus the content of the page showing the final payment. If I go back to the compare page, I only see the discount after I have done a hard-refresh of the page, effectively starting a fresh session.

### compare page missing discount
![plans page](https://cloudup.com/cv3A3kjTCfN+)

### discount shown on checkout page
![checkout page](https://cloudup.com/c7fjpWon2Ln+)

### compare page shows discount after a hard-refresh
![plans page after refresh](https://cloudup.com/cKIq_2avrug+)

The upshot is I think we should fix the discount on the plans page to show in the same session as the NUX setup. @scruffian Should I open a new bug issue for that, or should we repurpose this one?

**Comment by rralian** [comment]
moving this to the backlog for now

**Comment by drewblaisdell** [comment]
@rralian Good catch. We have a condition that refreshes those for domain registrations, it just needs to be updated to run when the user purchases a domain mapping as well. I created a PR for this here: #4328

**Comment by rralian** [comment]
Thanks @drewblaisdell, I'll close this one.

**Comment by scruffian** [comment]
>  It's shown on the checkout page, although it's discounted by $20 versus $13 as I would expect

This is a feature of how our domain discount works. If we want to match the discount to the domain price (which I think we should) then we need to update the API
