### ISSUE TITLE
Media Modal: Non-English free photo library search

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#42346]
## Requirements

1. When searching for free images in the Calypso media modal, users can select from a list of non-English languages and submit a search for images.
1. This should work with the media modal in the block editor in WordPress.com and in the Calypso and in the Media section of Calypso

## Notes

1. Language search is enabled by adding the `locale` query parameter to the Pexel's API request
1. To see a list of languages and locale codes supported, go to https://www.pexels.com/ and select "Change Language"
    <img width="565" alt="image" src="https://user-images.githubusercontent.com/1699996/82253802-4807f500-9917-11ea-81e8-5bb8813c7c39.png">

1. This Pexels API parameter is current undocumented, but they've let us know that it's stable, supported, and they're in the process of documenting it.

Work on this was started in D43084-code

**Comment by pento** [comment]
I don't know what their plans are for improving search results, but I suspect we're going to have to wait for that. Right now, there's a huge difference between English and Spanish search results (searching on pexels.com exhibits a similar disparity).

<img alt="" src="https://user-images.githubusercontent.com/352291/82295444-20865a80-99f3-11ea-9665-c54d8e9005b5.png">
<img alt="" src="https://user-images.githubusercontent.com/352291/82295475-2845ff00-99f3-11ea-85d4-99de7789b097.png">

**Comment by scruffian** [comment]
WFM!
<img width="1137" alt="Screenshot 2020-05-20 at 14 09 30" src="https://user-images.githubusercontent.com/275961/82449697-89c5a680-9aa3-11ea-8d24-6cc814479980.png">

**Comment by creativecoder** [comment]
I think we should de-couple the user's WordPress.com language setting from this search, and offer a dropdown to choose the language, so users can try searching in other languages (particularly English) if they don't find what they need.

![image](https://user-images.githubusercontent.com/1699996/82473998-fcc52200-9a8f-11ea-9bb9-933c1f7b8864.png)

The user's current WordPress.com language could be a default for the choice, though.

**Comment by scruffian** [comment]
When I was testing I think that searches also worked English, but it needs some more investigation. If that's the case I'm not sure there's much value in adding the dropdown.

**Comment by pento** [comment]
Search results seem to be working better for me now, too. I guess they were still filling out their keywords when I tried. 🙂

**Comment by pento** [comment]
> When I was testing I think that searches also worked English, but it needs some more investigation. If that's the case I'm not sure there's much value in adding the dropdown.

Seems like this is intentional, as I also get the same behaviour on pexels.com.

**Comment by pento** [comment]
Since it appears that non-English locales also get expected results when searching in English, I've merged D43084-code, and am closing this issue.
