### ISSUE TITLE
Gutenboarding: plans page—fix the top bar left and right position at small widths

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42352]
If your screen width is below the smallest breakpoint while viewing plans, the confirm buttons become fixed to the bottom of the screen, but the top bar is not fixed as you scroll horizontally:

<img width="545" alt="Screen Shot 2020-05-18 at 7 28 19 PM" src="https://user-images.githubusercontent.com/437258/82268901-1e15f900-993e-11ea-9d39-d7cdc69c75b6.png">

The top bar should fix it's left and right positions as you scroll horizontally.

cc @dubielzyk

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/43283
