### ISSUE TITLE
Editor: Show Editor and Customer Home deprecation notices to users

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#42351]
## Requirements

1. Show the editor deprecation notices to users
    1. [Editor](https://github.com/Automattic/wp-calypso/issues/41084)
    1. [Customer Home](https://github.com/Automattic/wp-calypso/issues/41085)
1. Update support doc link in notices (currently in draft: https://wordpress.com/support/?page_id=167510&preview=true)

### Notes

**IMPORTANT**: Relevant Wordpress.com support docs need to be published before this is live.

**Comment by scruffian** [comment]
Here are some images for the support doc:
<img width="1440" alt="Screenshot 2020-05-20 at 12 26 21" src="https://user-images.githubusercontent.com/275961/82441012-2e8cb780-9a95-11ea-8196-912b8201649c.png">
<img width="1440" alt="Screenshot 2020-05-20 at 12 24 22" src="https://user-images.githubusercontent.com/275961/82441021-3187a800-9a95-11ea-97c4-193127bd8b32.png">
