### ISSUE TITLE
8.1.0 gutenberg release: video block upload button is no longer disabled on free plans

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#42358]
Users on free plans are unable to upload videos to their blog 

In version 8.0.0.RC1 of gutenberg, if the user is on a free plan, the "Upload" button will be disabled.

In version 8.1.0 of gutenberg (edge stickered sites), the Upload button is enabled, uploading a file causes a confusing error message

### Steps to reproduce
Use a gutenberg edge stickered site that is on a free plan
Check that gutenberg 8.1.0 is in use. p7DVsv-8Dr-p2
Add a video Block

### Expected
The upload button is disabled
<img width="783" alt="Screen Shot 2020-05-19 at 5 36 40 PM" src="https://user-images.githubusercontent.com/22446385/82298328-5299bb80-99f7-11ea-8011-4af2a21495d9.png">

### Actual
The upload button is enabled and using it causes a cryptic error message

<img width="804" alt="Screen Shot 2020-05-19 at 5 29 48 PM" src="https://user-images.githubusercontent.com/22446385/82298270-39910a80-99f7-11ea-82a2-414e8f498760.png">

**Comment by roo2** [comment]
This issue is being looked at in Jetpack here https://github.com/Automattic/jetpack/issues/15796

**Comment by ockham** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/15906
