### ISSUE TITLE
Gutenboarding: Changes to intent capture

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#42363]
As we've discussed, let's do two changes to the first onboarding step:

**Remove the site category/vertical step**
We'll reintroduce this at a later point, but until we've worked out the quirks and functionality properly we should remove this step.

**Make the input field more obvious**
Let's change the look of the input field to this:
![image](https://user-images.githubusercontent.com/2896062/82315281-5f081f00-99cb-11ea-88fb-c0f83e7465c6.png)
![image](https://user-images.githubusercontent.com/2896062/82316085-975c2d00-99cc-11ea-8a0e-daa372f58849.png)

Changes:
- String is now "What's your website called?"
- Input field should have a `gray0` background-color
- Font-size should be changed to `44px` on desktop
- The _I don't know_ button should be changed to _Skip for now_ and moved under the input field on desktop. Once a user has entered a value the Continue button should appear and the skip button should disappear.
- Left padding on the container should be `120px`

Check Figma for mobile mocks and further detailed specs :)

cc/ @olaolusoga @rickybanister @amamujee

**Comment by amamujee** [comment]
Are we wed to the specific copy here? I think it's worth some thought but I prefer something like:

'What is the name of your site?' 

I think 'name' v.s. 'called' might translate better to other languages.

**Comment by dubielzyk** [comment]
I'm not a copywriter, so I'm happy to have someone else look into it 😃 Feel free to cc the right people and we can iterate here.

> I think 'name' v.s. 'called' might translate better to other languages.

Which languages does it translate poorly to?

**Comment by amamujee** [comment]
@akirk for additional insight given this step's importance. I thought that 'call' could have different connotations like 'summon'

**Comment by akirk** [comment]
We'll have our Localization Reviewers look at this when the copy is final in English.

**Comment by pablohoneyhoney** [comment]
Worth having more design explorations on this input field @dubielzyk

**Comment by dubielzyk** [comment]
What specific things aren't working at the moment @pablohoneyhoney ?

**Comment by pablohoneyhoney** [comment]
The filed above is disconnected from everything else. 
And if we need to optimize for only one question, then we should rethink well the UI.
