### ISSUE TITLE
Site setup list: Visual bug and active state

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#42369]
@shaunandrews noted some small visual bugs with the site setup list in Safari.

Extra space appearing above the highlighted item.
![image (9)](https://user-images.githubusercontent.com/448298/82348105-6e389e00-99c6-11ea-91b0-567a59ddcccf.png)

The `:active` state has white text.
![image (10)](https://user-images.githubusercontent.com/448298/82348166-801a4100-99c6-11ea-90ff-0b0afa9d7426.png)

#### Browser / OS version
Safari 13.0.5 / Mac OS

**Comment by danhauk** [comment]
This looks fine for me in Chrome and FF, though we do want to add a proper `:active` and `:focus` state to these buttons.

**Comment by eyturner** [comment]
@danhauk It looks like the nav-item class just needs some explicit modifiers for these problems to be solved on Safari. 

Add this to the nav-item class:

.nav-item {
    margin: 0;
    color: var(--color-text);
}

Tested on FF and Chrome to make sure there were no new errors and everything seems okay.

**Comment by FireQueen-3010** [comment]
Is this issue still open? If yes, I want to work on this.

**Comment by danhauk** [comment]
@FireQueen-3010 I just confirmed this issue is still open. Go for it!

Maybe something like this for the `:active` state? This is using `var( --color-neutral-5 )` for the background and `var( --color-neutral-50 )` for the dot. This keeps the behavior consistent with the Gutenberg editor where the `:active` state of a button is a darker background.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/448298/86655313-9d29c400-bfb4-11ea-8915-98ce5d19b891.png">

We should also have a `:focus` state for those who navigate with the keyboard. Again, keeping consistent with Gutenberg, maybe using the outline like on those buttons?

<img width="101" alt="image" src="https://user-images.githubusercontent.com/448298/86655729-f1cd3f00-bfb4-11ea-906c-62379a3ec613.png">

**Comment by FireQueen-3010** [comment]
Yeah, that's a good idea. Will review this issue and try to fix it! :)
