### ISSUE TITLE
Plans: enable selection of video files for free plan accounts

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4236]
When writing a post on a free-plan site, if you click on the media modal and then click "add" to select a new file, we disable selection of video files.

![disable video files](https://cloudup.com/cG_YkT6Is5P+)

Rather than disabling selection of video, it would be better if the user were able to select a video file, but then we displayed a message that VideoPress is one of the features of an upgraded plan.

**Comment by rralian** [comment]
Similarly, we should detect if a user drops a video file onto the editor and display a message about needing a plans upgrade to enable VideoPress (however we want to say it).

**Comment by artpi** [comment]
Deployed today
