### ISSUE TITLE
Themes: Update empty state illustration

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#42373]
On the Themes page, the empty state illustration still uses the loch ness monster.

I think it may have been an intentional decision to keep it there: https://github.com/Automattic/wp-calypso/pull/14432, but this was a while back; I think it's time for a change. Let's update this to something else, and use the new style proposed in: #42337

Steps to reproduce:

1. Go to https://wpcalypso.wordpress.com/themes/[site]
2. Search for a keyword that will return no results

![Screen Shot 2020-05-19 at 9 22 17 AM](https://user-images.githubusercontent.com/4924246/82352021-3e7f9b00-99b2-11ea-8762-2d886cb2042b.png)

cc @danhauk @sixhours @rickybanister @lcollette @olesyabrk

**Comment by olesyabrk** [comment]
+1 on using a new illustration style.

**Comment by jordesign** [comment]
closing in favour of #51290
