### ISSUE TITLE
Earn: Update main card illustration and other visual cleanup

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#42371]
On the Earn page, the main card's illustration needs to be updated to match the new style proposed in: https://github.com/Automattic/wp-calypso/issues/42337

URL: https://wpcalypso.wordpress.com/marketing/tools/[site]

![Screen Shot 2020-05-19 at 9 09 05 AM](https://user-images.githubusercontent.com/4924246/82350587-65d56880-99b0-11ea-8510-acb3390f378a.png)

**Other changes that can be done to improve this page:**

- Change main card's background color from blue to white (we don't use blue anywhere)
- Use standard icons for each secondary card (this one still uses SVGs)
- Update badge (we could use that new dark gray badge we're using in the editor announcement. See: https://github.com/Automattic/wp-calypso/pull/41570)
- Standardize what size of buttons to use for this type of layout

cc @danhauk @sixhours @rickybanister @lcollette @olesyabrk

**Comment by kwight** [comment]
Closed in #42769.

<img width="1220" alt="Screen Shot 2020-09-09 at 9 41 12 AM" src="https://user-images.githubusercontent.com/349751/92628041-14175d80-f281-11ea-816f-47f596cd8713.png">
