### ISSUE TITLE
Page templates don't load for gutenboarding sites without a selected vertical

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#42389]
When creating a new page, the page templates selector should be shown. This relies on the site having a vertical selected. For sites created with the old flow, php will fall back to the vertical 'default'. However for sites created by gutenboarding without selecting a valid vertial, NULL will be loaded and the user will not be able to use the page template selector.

#### Steps to reproduce

1. Go to `/new`
2. On the intent gathering step, do not choose a vertical but DO choose a site title
     * you must choose a site title for this bug to manifest itself
2. Go to the site home
3. Create a new page

#### Expected
You should see the page template selector page

#### Actual
You are dropped straight into the block editor for a blank template

#### More investigation:

I put a logging statement in here for the site created by gutenboarding and found that `$vertical_id` was `NULL`. https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php#L206

For sites created with the old flow, it would be 'default'.

So it looks like `site_vertical` has been set to `NULL` explicitly on site creation.

#### More context

Originally reported by Ola in slack
p1589853624289500-slack-dotcom-create
p1589841311318300-slack-dotcom-design

**Comment by ramonjd** [comment]
I can't reproduce this, maybe I'm missing a step?

I created a site via `/new` with no site vertical and no site title. 

When I create a new page on the new site I can see the page layout selector interface.

The output of `get_option( 'site_vertical' )` for these sites is `false`. FSE would return ['default'  as the default value in this case](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php#L206). Is that not right?

I do see that we fallback to `'football'` [as the default vertical](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/stores/onboard/actions.ts#L121) for Gutenboarding. I 🤔 if this is the cause of the havoc?

**Comment by roo2** [comment]
ahhh ok it seems like you *need to have a site title* for this bug to manifest itself.

**Comment by ramonjd** [comment]
> ahhh ok it seems like you need to have a site title set for this bug to manifest itself. I've added that to the description

😱 

That makes things even weirder.

**Comment by simison** [comment]
Note that we've now removed vertical input so all sites are without vertical.

**Comment by roo2** [comment]
Closing this issue then as it can't manifest itself without the vertical being set
