### ISSUE TITLE
Premium content: Certain unicode characters don't render correctly

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42384]
As reported by @StefZarb 

![example](https://user-images.githubusercontent.com/1270189/82388439-7b698300-99ee-11ea-8fa5-90149e42f927.png)

1. Starting at URL: https://wordpress.com/pages/
2. Add a new page
3. Add the Premium Content Block
4. Type in the following  Latin-1 Supplement characters as an example à,á, â, å, ā, è,é,ê,ë,ē,ė,ę either in the nested header or paragraph block set by default in the block.
5. Type any simplified Chinese character
6. Publish the page. 

### What I expected
I expect to see the Premium Content Block displaying the correct characters in the page

### What happened instead
Characters are not displayed correctly

### Additional notes
- I have tried to activate different themes (block-based themes and not)
Both with block-based themes (via Global Styles) and not (via the Customizer > Fonts) I have switched different fonts.
- I have tried to change the Site Language Settings to Chinese.
 All the other blocks on the page display the characters correctly.
- I have tried on Firefox, Chrome, Safari, Opera (latest versions)

**Comment by mmtr** [comment]
Emojis have this issue too, so this can potentially affect all users, including English users.

Editor view | Published view
--- | ---
<img width="721" alt="Screen Shot 2020-05-20 at 11 26 47" src="https://user-images.githubusercontent.com/1233880/82429843-d05bd680-9a8c-11ea-9ab0-c96ad0179970.png"> | <img width="762" alt="Screen Shot 2020-05-20 at 11 28 05" src="https://user-images.githubusercontent.com/1233880/82429981-000ade80-9a8d-11ea-87b5-38e403ac82bd.png">


Will look into this today.
