### ISSUE TITLE
Gutenboarding: Intent Capture hover state

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#42392]
@joanrho correctly pointed out that the hover states for the buttons are different on intent capture and style screen. [See video](https://d.pr/v/UiOREN).

Let's make the first button have the same hover state as on the style screen where it darkens on hover.

**Comment by simison** [comment]
This might be a bug from the "color theming" the intent capture page for some verticals.

@razvanpapadopol if we remove vertical input and thus also the color-coding, this might get fixed at the same time?

**Comment by razvanpapadopol** [comment]
should be fixed now since we're using `ActionButtons` from `@automattic/onboarding` package everywhere.
