### ISSUE TITLE
Gutenboarding: two column design picker grid on tablet missing

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#42397]
At Gutenboarding (`/new`), design picker goes straight to one column from 3 columns on tablets:

![image](https://user-images.githubusercontent.com/87168/82431528-6bf24480-9a97-11ea-8b99-c068373dabbf.png)

![image](https://user-images.githubusercontent.com/87168/82431496-639a0980-9a97-11ea-95db-4c06d50a6a79.png)

I expected to have 2 columns before narrower mobile version where we have 1 column:

![image](https://user-images.githubusercontent.com/87168/82431622-89bfa980-9a97-11ea-87ba-5580cc1e6c00.png)

It's also little problematic for mobile landscape:

![image](https://user-images.githubusercontent.com/87168/82431599-83313200-9a97-11ea-94d7-0123b73fcf74.png)

@dubielzyk thoughts?

**Comment by dubielzyk** [comment]
Yeah, let's go to two columns where it makes sense, then down to one on mobile.
