### ISSUE TITLE
Editor: Media: Able to insert broken image from pending URL upload

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#4239]
Steps to reproduce:
1. Open the media modal and "Add via URL"
2. Paste in a valid image URL and hit "Upload"
3. Immediately hit Insert (before the upload completes)

Results:

An empty image tag is inserted into the post, i.e.
`<img class="alignnone size-full wp-image-media-4" alt="filename.jpg" />`

The tag never gets turned into the real image, even after the image upload successfully completes.

We should handle this better, either by blocking insertion until upload completes, or if possible faking it the way we do for local file uploads.

**Comment by designsimply** [comment]
Tested and confirmed using Safari 9.1 on Mac OS X 10.11.4, see [1m21s](https://cloudup.com/c-1uPhnK0gZ).

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue. The Insert button was disabled at first while the upload was in progress; I hit Insert as soon as it became active and the image was added as expected to the post. Closing as resolved.

#bug-scrub #pre-gutenburg-bug-purge
