### ISSUE TITLE
The Swiper library could not be loaded’ error on blog post pages

### ISSUE THREAD

**Issue by KateWorkCatwalk** [Automattic/wp-calypso#42404]
#### Steps to reproduce

Start with a simple WordPress.com site
Add a Slideshow block
Add images on it

#### What I expected

The slideshow appears as expected on editor view.

#### What happened instead
On editor view, we see a notice that reads The swiper library could not be loaded

#### Browser / OS version
Google Chrome, Safari

#### Screenshot / Video
<img width="634" alt="Screen Shot 2020-05-20 at 2 51 35 PM" src="https://user-images.githubusercontent.com/65660448/82443026-6e5d9a00-9aa9-11ea-98d1-9a61aef467e1.png">

#### Context / Source

Does anybody know how to fix it?

**Comment by xpurichan** [comment]
It seems as though this bug has been fixed. I've followed the steps described above and I was able to add a functional slideshow block which worked in both the editor and actual page/preview. My tested was done in Google Chrome Version 88.0.4324.146. Screenshot:

![Screen Shot 2021-02-08 at 9 24 15 PM](https://user-images.githubusercontent.com/33190975/107307057-a055c880-6a4b-11eb-97a1-52c993dd2d6e.jpg)

If you are still experiencing this issue then please reopen the report along with details such as your OS and browser version and we'll take a look!
