### ISSUE TITLE
Framework: Display issues for notices on mobile

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4243]
There are two possible visual regressions introduced by #4191 

**When a notice appears at the bottom of a mobile screen, the 'X' now displays in the bottom left instead of top right**

Before #4191 

![added pre-pr](https://cloud.githubusercontent.com/assets/128826/13972078/501ba63e-f0e1-11e5-875c-e17cbea77361.png)

After #4191 
![added post-pr](https://cloud.githubusercontent.com/assets/128826/13972124/b7c8bb28-f0e1-11e5-840d-8254f2c1cd49.png)

On an iPhone 6+ screen size (4.7"), the published post message displays on two lines, although it appears that this would fit on one line:

Before #4191 

![publish pre pr](https://cloud.githubusercontent.com/assets/128826/13972153/ebc44b54-f0e1-11e5-9c11-dcc22a3a275f.png)

After #4191 

![publish after](https://cloud.githubusercontent.com/assets/128826/13972158/f5e354c2-f0e1-11e5-9e74-68c8f73975b8.png)

cc: @Tug

**Comment by mikeshelton1503** [comment]
>On an iPhone 6+ screen size (4.7"), the published post message displays on two lines, although it appears that this would fit on one line:

This wouldn't always fit on one line depending on the user's language setting and also length of site name. #4191 allows more flexibility for length of copy.

**Comment by alisterscott** [comment]
The 'X' button issue is also relevant to notices at the top of the screen. Eg. updating a user's role:

![updating users role](https://cloud.githubusercontent.com/assets/128826/13973002/f2495494-f0e9-11e5-9869-52daae54ad93.png)

**Comment by Tug** [comment]
Thanks for reporting @alisterscott! My bad, I forgot to test those!

**Comment by alisterscott** [comment]
Thanks, retested all good :+1:
