### ISSUE TITLE
Customer Home: Make Sure Atomic Sites can Launch

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42495]
Private by default will be available to Atomic sites and this means that Simple sites will no longer be forced to make their site public before transferring to Atomic. 

From the My Home section, we currently launch a site as a step in the Site Setup List (checklist)

Because the Site Setup List (checklist) was unstable (pb5gDS-7c-p2) for Atomic sites, Explorers disabled this functionality back in Oct 2019, meaning this option isn't available to Atomic sties from My Home

<img width="1335" alt="Screen Shot 2020-05-20 at 11 10 41 AM" src="https://user-images.githubusercontent.com/1270189/82481687-8e319580-9a8a-11ea-8646-daa75580b859.png">

Note that there are other UX areas where one can launch a site (frontend/settings), but it'd be good to add back this functionality to the My Home section as this is a key onboarding step

### Tasks to be done

- Fixup support for Site Setup List for Atomic
- Or provide an alternative launch mechanism. on my Home A primary task just for Atomic sites to launch their site might be good enough

cc @danhauk  @adamziel @davemart-in

**Comment by roo2** [comment]
closing in favor of https://github.com/Automattic/wp-calypso/issues/50757
