### ISSUE TITLE
Modularise `userSettings`

### ISSUE THREAD

**Issue by sgomes** [Automattic/wp-calypso#42490]
The `userSettings` portion of the state tree needs to be modularised. See the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) for more details.

**Comment by sgomes** [comment]
`lib/user-settings` appears to be a blocker for this one.

**Comment by flootr** [comment]
@sgomes fyi I'm self-assigning this because I started working on removing `lib/user-settings` as part of the reduxification efforts (#24162) and will also tackle this one as part of the work there.

**Comment by sgomes** [comment]
Sweet, thank you @flootr! 👍

**Comment by tyxla** [comment]
Picking this up in alignment with my recent work to push forward the state modularization effort.
