### ISSUE TITLE
Classic Editor: Media Library does not load for previously created galleries

### ISSUE THREAD

**Issue by dkoo** [Automattic/wp-calypso#42497]
When editing a previously created gallery in visual mode while in the Classic Editor, the Media Library modal fails to load the media items, hanging in the loading state.

The shortcode still appears correctly in HTML mode, and the gallery renders properly on the front-end.

Seems to be tangentially related to https://github.com/Automattic/wp-calypso/issues/20441.

#### Steps to reproduce

1. In Classic Editor mode, create a new gallery and add several (10+) images.
2. Save or publish the page, then close out of it.
3. Refresh your browser (important).
4. Revisit the page to edit in visual mode. Click on the previously created gallery and click on the pencil icon to edit it.

#### What I expected

The Media Library modal should display the media items in the gallery, allowing me to edit them and update the gallery.

#### What happened instead

The Media Library modal appears, but hangs in the loading state without displaying the media items from that gallery.

#### Browser / OS version

Tested in both Chrome and Firefox.

#### Screenshot / Video

<img width="1791" alt="Screen Shot 2020-05-20 at 12 59 13 PM" src="https://user-images.githubusercontent.com/2230142/82486752-91348200-9a9a-11ea-93c5-2defebce060f.png">

#### Context / Source

Encountered and confirmed while answering a support ticket. Was able to replicate in a new page on a different site as well.

**Comment by davipontesblog** [comment]
@dkoo the classic editor is deprecated now in WordPress.com, would you mind testing this using the WP Admin classic editor to see if the issue persists?

**Comment by dkoo** [comment]
@davipontesblog: this is not an issue in the WP admin classic editor; I could only replicate in Calypso's classic editor.

**Comment by davipontesblog** [comment]
@dkoo Thanks, let's close this then. The calypso classic editor is deprecated at this point.
