### ISSUE TITLE
New onboarding launch: after using back button from the domain registration form, plans page fails to load

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#42510]
Using the back button from the domain registration form causes the plans page to fail to load.
Refreshing the page does not fix the error.
Using the back button again, the domain selection page also fails to load.

![May-21-2020 13-01-34](https://user-images.githubusercontent.com/22446385/82519036-0fa92680-9b64-11ea-8545-072fe5988bcb.gif)

#### Steps to reproduce

* Complete the `/new` flow until you land in the editor.
* Go to My Home and click the *Launch* button from site setup checklist
* Select a domain and plan.
* You will be on the domain registration form
* Click browser back or the embedded back button.

#### Expected 
You are returned to the `/start/new-launch/plans` page and can pick a different plan, or domain.

#### Actual
The `/start/new-launch/plans` page fails to load with the following error: 
```
Error: new-launch did not provide the query dependencies [siteSlug,source] it is configured to.
    at K._assertFlowProvidedDependenciesFromConfig 
```

#### Related
#52610 with PR https://github.com/Automattic/wp-calypso/pull/52798

**Comment by razvanpapadopol** [comment]
> Select a domain and plan.

This can be reproduced also without selecting a domain. After redirecting to `/checkout` it seems impossible to go back to the steps in the launch flow.

> Click browser back or the embedded back button.

- **embedded back button**: fixed in #43013 by redirecting to my home

- **browser back**: I can reproduce this also for the default launch flow (`/start/launch-site`) 
**[LE - 19.02.2021]: the bug seems to be fixed for `launch-site` flow**

**Comment by cathymcbride** [comment]
@razvanpapadopol is this the same as https://github.com/Automattic/wp-calypso/issues/49565?

**Comment by razvanpapadopol** [comment]
@cathymcbride, no this is happening in the `/start/new-launch` launch flow (the one that you start from Site setup checklist on My Home for sites created on `/new`).

**Comment by simison** [comment]
:wave: @klimeryk Do you think this would fit domains-gaps work? (ref p99Zz8-1BJ-p2)

**Comment by klimeryk** [comment]
@simison, I'm focusing there in the existing signup flows and domain management gaps that often don't have a clear owner or active development in a while. Since this touches the New Launch flow (which I'm not honestly familiar with from technical point of view), I think it'd be fastest if the team working on it right now would look at this issue 🙏

**Comment by simison** [comment]
@klimeryk oh I asked because I thought it was those flows, but reading @razvanpapadopol comment above again, I suppose if was new flow indeed. :-) thanks for the reply!

**Comment by razvanpapadopol** [comment]
This bug was fixed for the editor launch flow in D57607-code but it's still happening on the other launch flows in Calypso.

**Comment by roo2** [comment]
I retested but you can still access the `/start/new-launch` feature from the site setup checklist on the site home page and this bug is still present. You have to click through to the payment step and then use the browser back button ( or X button I believe ).

<img width="1044" alt="Screen Shot 2021-03-26 at 4 23 31 PM" src="https://user-images.githubusercontent.com/22446385/112604253-a5d36a80-8e61-11eb-8741-111f7b51b929.png">

I also noticed that if you had previously cancelled payment, the `/start/new-launch` flow is actually not working at all, it just lands the user on the "congratulations" page without giving them the option to select a domain or plan https://github.com/Automattic/wp-calypso/issues/51436

**Comment by razvanpapadopol** [comment]
> I retested but you can still access the /start/new-launch feature from the site setup checklist on the site home page

That's right. Thanks for spotting the mistake, @roo2! With D57607-code we've fixed the bug only when launching from the editor. I've updated now my previous comment.

**Comment by kwight** [comment]
I'm downgrading this to `normal`, which feel like how we're treating it (it's been fixed for some, and only happens for others if they use the browser Back button).

**Comment by roo2** [comment]
closing this as the flow was removed in https://github.com/Automattic/wp-calypso/issues/54409
