### ISSUE TITLE
Saving a new page/post/block in an unlaunched site causes an editor crash

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#42511]
Gif
![2020-05-20 16 31 38](https://user-images.githubusercontent.com/22446385/82524402-2e161e80-9b72-11ea-815e-86f10ae9d3d0.gif)

Error
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

#### Steps to reproduce

* Create a new site incognito, new user via wp.com/new
* Exit the editor to Calypso
* Go to posts screen in Calypso
* Click Add new post
* Click Save
* Click Publish in the Publish Sidebar that appears after save
* See screenshot above

#### What I expected

Save the page

#### What happened instead

Editor crash with Error
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

Reported by @ianstewart 
p1590010363301400-slack-gutenboarding

**Comment by roo2** [comment]
This seems to still be happening on wordpress.com even after the fix was merged.

**Comment by ianstewart** [comment]
> This seems to still be happening on wordpress.com even after the fix was merged.

Just dropping a note to say that 10 hours later (post-fix) it's working as expected for me now.
