### ISSUE TITLE
Typography: explore smarter ways to trigger fallback typefaces for non-latin characters/languages

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42522]
@mattmiklic reported that Recoleta renders certain Vietnamese characters in a 'ransom note' style:

![image](https://user-images.githubusercontent.com/437258/82567727-c8af3700-9b4b-11ea-9ca9-3c18e47ae95c.png)

Can we get creative about how we trigger the font stack perhaps nesting it within a body class for latin character sets and falling back to system-serif for non-latin? 

(I don't know if I'm using 'non-latin' appropriately here, but I hope it makes sense)

cc @lcollette @sixhours

**Comment by simison** [comment]
@sixhours is there any work left to do here, or did https://github.com/Automattic/wp-calypso/pull/42814 already solve this?

**Comment by sixhours** [comment]
Solved! Thanks for finding this :D
