### ISSUE TITLE
Bug: Gutenboarding domains when skipping site name for existing user

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#42524]
I was on Chrome/MBP. 
<img width="1166" alt="WordPress_com" src="https://user-images.githubusercontent.com/1103209/82568432-cbf6f280-9b4c-11ea-90c3-205a4ed5bfbb.png">

To reproduce, start a new wp.com site while logged in. When you click on 'skip for now' on site name, then go back it looks up something related to your existing site on domains. When you click on domains you get the blank lookup screen.

Second issue: 
<img width="820" alt="WordPress_com" src="https://user-images.githubusercontent.com/1103209/82568550-fea0eb00-9b4c-11ea-8eeb-954543bacdf4.png">

When new new users click skip site name we show this generic domain. 

Solution: For now, instead of looking up a random domain, let's change it to 'Pick your domain'. This should **apply to both new and existing users.**

**Comment by simison** [comment]
> Solution: For now, instead of looking up a random domain, let's change it to 'Pick your domain'. This should apply to both new and existing users.

The fallback label instead of too-random-domain works for me, let's do that. 👍 

Let's still generate the domains though since we need the free `.wordpress.com` subdomain generated no matter what, just to be able to create the site.

FYI @dubielzyk

**Comment by rickybanister** [comment]
I don't think it makes sense to show the skeleton if we don't have any pre-filled text.

If we just show the search field it will make more sense.

Like:

![image](https://user-images.githubusercontent.com/437258/82571976-bdf7a080-9b51-11ea-8216-38f20aee1f5b.png)

The skeleton should appear once they start typing.

**Comment by yansern** [comment]
> I don't think it makes sense to show the skeleton if we don't have any pre-filled text.

One could argue showing some pre-populated domain suggestions (albeit how random it is) helps user to understand what this dropdown is all about.

It also appears that logged-in user gets suggestions based off their username when user skips entering their site title.

**Comment by simison** [comment]
@rickybanister sure, and I think we can do that separately from this label change?

**Comment by simison** [comment]
Should we switch the mobile version of CTA to be "pick a domain" as well?

Currently:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/87168/82576090-08990d00-9b92-11ea-9491-bddee5eb2777.png">

We don't show "example.com is available" because there wouldn't be enough space for it.
