### ISSUE TITLE
Gutenboarding: launch flow domain step improvements

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42539]
We've seen two usability test subjects so far have a similar experience when they attempt to launch their sites. They weren't sure what to expect and freeze a bit when they see the domain search:

![image](https://user-images.githubusercontent.com/437258/82601029-e1841080-9b7c-11ea-9819-2c96cbabab16.png)

The things mentioned:
* There are only two default choices, and it wasn't exactly clear what to do to see more choices.
* The copy here mentions 'give your site an address' and does not mention domain or url like we do elsewhere. This made them unsure what exactly to do.
* The 'enter a name or keyword' placeholder copy on the search box was confusing since they'd already given their site a name. They expected that to be pre-filled.

Immediate suggestions:
Change the subtitle text:
> Enter your site's name or some keywords that describe it to get started.

To:
> Search your site's name or a keyword to find a custom domain. 

And use the domain search layout from /start, this one is out of date and has a strange pattern for the recommended and best match things:

This: 
<img width="1067" alt="Screen Shot 2020-05-21 at 4 11 40 PM" src="https://user-images.githubusercontent.com/437258/82602142-a1be2880-9b7e-11ea-9e29-0cb621c7d866.png">

Instead of this:
![image](https://user-images.githubusercontent.com/437258/82602121-97039380-9b7e-11ea-80de-fe28cee033b2.png)

Considerations to make when migrating to the new domain search (not necessarily things to change now if we're about to stop using this screen):
* Pre-fill the search with the site title and monitor any impact on conversion
* Show more than two options as the default as if they performed a search
* Generally work on reducing the complexity of choices on this screen

cc @johnHackworth @amamujee @olaolusoga @simison

**Comment by razvanpapadopol** [comment]
The redesigned launch flow with new domain search is currently under development in #43750  
I think we can close this issue if all the considerations have been taken into account in the new version. 
cc: @joanrho

**Comment by joanrho** [comment]
Closing issue since our new launch flow addresses the concerns in the post.
