### ISSUE TITLE
Recurring Payments: Limit welcome email content to 2000 characters

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42536]
To avoid lengthy emails and any possibility of email clipping let's limit the Custom confirmation message of Recurrent Payments to 2000 characters to start.

This task consists of three parts:
- [x] Client validation check (https://github.com/Automattic/wp-calypso/pull/42568)
- [x] Server validation check (D43837-code)
- [x] UX and copy updates to encourage a short message. Eg limit textarea to 5 rows and add placeholder test like "Write a short welcome message" (https://github.com/Automattic/wp-calypso/pull/42568)

<img width="756" alt="82550885-84c62d00-9b5f-11ea-9a1e-832ccc47805f" src="https://user-images.githubusercontent.com/1270189/82600789-521e3380-9b63-11ea-9ff7-48f318f5dfc6.png">

#### To see this dialog

* Set up Recurring Payments on a site using the testing store. More info in PCYsg-lW4-p2 #sandbox-method.
* Go to Tools > Earn > Collect recurring payments > Recurring Payments plans.
* Add or edit an existing recurring payment plan.
* Click on the Email tab

**Comment by mmtr** [comment]
All pieces covering this already landed, so closing this one out.
