### ISSUE TITLE
Gutenboarding: Back button from checkout creates two blank screens in launch flow

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42538]
Clicking the back button from checkout in the launch flow leaves users with a blank screen. Here's one example with a free plan in the video below.

https://cloudup.com/cwWn6OdXHOf

To reproduce as a free user …

1. Create a site with Gutenboarding as a free user (no domain, free plan)
2. Click Launch from the Editor
3. Select a paid domain from the domains screen in the launch flow
4. Select a free plan
5. Enter check out
6. Press back button in UI, see a blank screen
7. Press browser back button, see a blank screen

I'll add steps to reproduce as a paid user below.

**Comment by ianstewart** [comment]
The link below reproduces this as a paid user who purchased a plan in the Gutenboarding onboarding flow selecting a domain in the launch flow and then pressing back at the checkout screen. 

This is something two test participants have also been able to reproduce independently in usability testing.

https://cloudup.com/ikaq_3aRq37

1. Create a site with Gutenboarding as a plan user without a domain.
2. Checkout in Gutenboarding flow.
3. Click Launch from the Editor
4. Select a paid domain from the domains screen in the launch flow
5. Enter check out
6. Press back button in UI, see a blank screen
7. Press browser back button, see a blank screen

**Comment by michaeldcain** [comment]
This is essentially the same issue as clicking the browser back button from Signup > Checkout (the launch flow uses the same Signup progress store), where Signup starts over and the user ends up creating a second site by accident. Since this has traditionally been a can of worms, I'd recommend making the back button a close button and returning them either to the editor or the domains screen in Calypso.

**Comment by klimeryk** [comment]
This should be fixed now with the new checkout launched and no back button - it's a close button, like Michael suggested above.
