### ISSUE TITLE
Layout Grid: No visible + sign when adding a new block 

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#42540]
#### Steps to reproduce

1. Add a Layout Grid block to the page. 
2. Add a content block (such as an Paragraph or video block) at the top of the first Layout Grid column
3. Try to add a second block, below the first block. There is no plus sign. To add the second block, you need to hit enter or click on the block you've already added and select the option to add before or add after, or you need to click in the exact spot the plus sign would be, if it is visible. 

#### Screenshot / Video

![Test Site](https://d.pr/i/UW5puN+)

#### Context / Source

#user-report - see 2992383-zen

**Comment by JoshuaGoode** [comment]
Opened report in block experiments: https://github.com/Automattic/block-experiments/issues/91

Internal discussion: 9F6qB-p2

**Comment by JoshuaGoode** [comment]
Somewhat fixed on https://github.com/Automattic/block-experiments/pull/97

> This is intentional, but buggy, so something we do need to fix. The heuristic for the plus in the core project is a bit silly, and something I'd love to revisit upstream: a plus should show after not-text-blocks in nesting containers.
