### ISSUE TITLE
Gutenboarding: top bar elements should have the same sized hit state

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42572]
The domain dropdown and the plan link have different heights. This isn't normally noticeable, but the focus styles make it apparent:

![image](https://user-images.githubusercontent.com/437258/82676099-d3350380-9c13-11ea-8176-f95fda59c732.png)

I feel that aligning them all to the same size would help for usability, accessibility, visual consistency, and maybe even bring more attention to the domain picker. 

cc @simison

**Comment by dubielzyk** [comment]
After trying out a few things (see explorations below), I think the current implementation is still the best. The plan and domain picker buttons have different interactivity hence I think their individual treatment is justified.

![image](https://user-images.githubusercontent.com/2896062/82819722-25d71f80-9ea1-11ea-905c-3c862c8e17b6.png)

What do you think? Got any other solutions in mind?

**Comment by simison** [comment]
What do you think about making the title an input and would that change anything? (We'd have 3 interactive elements in the header)

**Comment by dubielzyk** [comment]
I'm okay with it for those who feel like they want to edit the site name. Could be neat. I have a hunch that very few people will use it, so personally I'm not sure if it's worth the investment time, but it's up to you all :)

**Comment by rickybanister** [comment]
I'm kind of partial to the taller domain dropdown. Since we keep seeing folks miss it, having a bit more presence doesn't seem like a bad thing.

**Comment by dubielzyk** [comment]
I don't think is a priority and after doing explorations, I don't think it's something we should do. Feel free to reopen if you disagree :)
