### ISSUE TITLE
Gutenboarding: make plans comparison more obvious

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42587]
In our usability testing no one has scrolled down far enough to see the feature comparison link. 

Can we explore a design that makes that link more accessible? Perhaps a smaller link fixed to the bottom of the screen (there's room on the left since Free has so few features...)

We can look at tracks data to see if there's been any interaction in the general population, but it seems to be very easily missed since we've taken care to fit all the relevant UI on a single screen in other steps. 

cc @olaolusoga

**Comment by dubielzyk** [comment]
I recon we should just expand it by default and not hide it. If there's ample whitespace on the page it shouldn't feel super busy. The comparison grid was helpful in our last round of testing, so it's probably the right call to just show it by default.

**Comment by rickybanister** [comment]
Works for me.

**Comment by dubielzyk** [comment]
We've expanded the plan detail grid by default so closing this for now
