### ISSUE TITLE
Recurring Payments: Update default minimum price when currency is changed

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#42591]
When changing the currency field, the default price of $0.50 USD does not change to match the minimum required price for that currency. We should update the price to reflect the currency's minimum requirement if the price isn't valid for the new currency.

To reproduce:

* Add a Recurring Payments block to a page or post
* Click "Add a plan" to add a new recurring payment plan
* Note the defaults for currency and price - USD and $0.50
* Change the currency to something else, like NOK or JPY
* The USD default value is not valid for some other currencies, shown by the red border around the price field

We should update the price field to match the minimum required amount for the updated currency when it's not valid.

**Visuals**

Default view with $0.50 USD

<img width="517" alt="Screen Shot 2020-05-22 at 2 53 51 PM" src="https://user-images.githubusercontent.com/2124984/82700755-d4c6f180-9c3c-11ea-8189-bc950ec3c4c8.png">

Change currency field to kr where minimum required payment is kr3,00 and note the price field is no longer valid:

<img width="502" alt="Screen Shot 2020-05-22 at 2 54 03 PM" src="https://user-images.githubusercontent.com/2124984/82700742-cd074d00-9c3c-11ea-9ee8-2bb06958dd26.png">

**Comment by gwwar** [comment]
This one can be closed out right @sixhours and @mmtr ? Please reopen if not
