### ISSUE TITLE
[Idea] Top bar completion status

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#42603]
<img width="1293" alt="WordPress_com_and_Slack___gutenboarding-early-data-reports___A8C___1_new_item" src="https://user-images.githubusercontent.com/1103209/82751501-ab65ad00-9d85-11ea-9788-a49dfd784457.png">
As the top bar becomes more important with every element being interactable, I wonder if an ‘incomplete’ and ‘complete’ state should exist for each component - some consistent visual treatment that is both clear and not too in your face. No specific proposals, just an idea.

**Comment by amamujee** [comment]
What did we think of this?

**Comment by dubielzyk** [comment]
I'm not sure I get what you mean by incomplete and complete state. Could you elaborate further or provide a sketch? What's the problem you're trying to solve with this?

**Comment by amamujee** [comment]
Basically if a user has completed the task it looks a certain way (e.g. entered site name or picked domain or plan) and if they have not it looks different. I'm trying to get more users to click on those top bar elements and pick domains, plans and make sure they enter their site name. Right now users completely miss these.

**Comment by olaolusoga** [comment]
Sounds like a progress bar—that highlights negatively when a step is skipped, and positively when it's completed. @amamujee is this idea still valid once we introduce domains as a step during onboarding?

**Comment by dubielzyk** [comment]
Is this still something we want to do?

**Comment by olaolusoga** [comment]
No—maybe in future iteration. Closing.
