### ISSUE TITLE
Free plan status when selecting a premium item

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#42601]
<img width="1240" alt="WordPress_com" src="https://user-images.githubusercontent.com/1103209/82751414-08149800-9d85-11ea-9c3b-2b34aaba2e76.png">

I found a small bug. If you select the free plan, and then top back and select a premium domain or design it does not put you on a premium plan, but leaves you on a free plan.

**Comment by razvanpapadopol** [comment]
While doing an exploration to fix this we ended up in a place where the UX seems broken and some design input is needed. Mentioned details in https://github.com/Automattic/wp-calypso/pull/42607#issuecomment-635343146

If we still consider this a priority, we can pick up where we left off once we have the design solution.
cc: @olaolusoga

**Comment by razvanpapadopol** [comment]
Selecting paid domain to trigger Premium plan selection is part of https://github.com/Automattic/wp-calypso/pull/43321

In order to apply the same mechanism for premium designs, we probably need something like this on the Plans Grid: 
<img width="245" alt="Screenshot 2020-06-16 at 14 10 49" src="https://user-images.githubusercontent.com/14192054/84767921-f5842c00-afdb-11ea-9c7e-069aa855dc13.png">

cc: @olaolusoga @dubielzyk

**Comment by dubielzyk** [comment]
I agree with @amamujee that this is how it should work. We definitely want that for the plans page @razvanpapadopol. Can we make that happen?

**Comment by razvanpapadopol** [comment]
This is doable for sure 👇 
<img width="733" alt="Screenshot 2020-06-16 at 15 29 34" src="https://user-images.githubusercontent.com/14192054/84774250-35e8a780-afe6-11ea-820a-4ae42c4b57e9.png">

Of course, copy can be adjusted. I see _Premium themes_ is the feature name in Premium Plan column.

**Comment by simison** [comment]
> I see Premium themes is the feature name in Premium Plan column.

@johnHackworth @dubielzyk @olaolusoga should we test hiding that "premium themes" item from the plans grid as it has proved confusing in user testing (in relation to premium designs) and we anyway hide premium themes pretty well in theme directory these days? It doesn't play well conceptually with the direction of premium designs.

<img width="1767" alt="Screenshot 2020-06-16 at 15 37 18" src="https://user-images.githubusercontent.com/87168/84775106-73016980-afe7-11ea-936e-ede475bec41c.png">
<img width="1776" alt="Screenshot 2020-06-16 at 15 37 37" src="https://user-images.githubusercontent.com/87168/84775109-74329680-afe7-11ea-8402-9f5dab83da68.png">

**Comment by dubielzyk** [comment]
@razvanpapadopol I think we should ignore the Premium design checkmark for now, but let's keep the domain checkmark.

@simison I don't know what we're learning, so I'm up for hiding it again until we've sorted it out properly. Seems like we have enough from the experiment we ran, but I'll let others make the final call.

**Comment by simison** [comment]
@dubielzyk sorry I meant hiding this:
<img width="166" alt="image" src="https://user-images.githubusercontent.com/87168/84777266-089df880-afea-11ea-9d00-1fb8423a1b8a.png">

I'm up for hiding the premium-designs also if that simplifies things for now.

**Comment by dubielzyk** [comment]
Ohh. I think we should keep it if we remove the "X Edison premium design isn't included" but I'm fine with leaving it out if we leave that in.

**Comment by johnHackworth** [comment]
I'm all for hiding the 'premium themes' bit. It doesn't make sense in this context

**Comment by razvanpapadopol** [comment]
superseded by https://github.com/Automattic/wp-calypso/issues/44239
