### ISSUE TITLE
Store: Shipping zone doesn't load when WooCommerce Admin plugin is active

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#42604]
Clicking a shipping zone within Store doesn't load when the WooCommerce Admin plugin is active.

#### Steps to reproduce

1. Starting at URL: An AT site with shipping zones setup and the WooCommerce Admin plugin  active
2. Click "Edit" on a zone, such as: https://wordpress.com/store/settings/shipping/zone/EXAMPLE.com/0

![https://d.pr/i/5ttTWw](https://d.pr/i/5ttTWw+)

#### What I expected

The zone details should load.

#### What happened instead

The page doesn't load.

Shutting this plugin off causes the page to load correctly:

![https://d.pr/i/WJ7L6r](https://d.pr/i/WJ7L6r+)

#### Context / Source

Reported 21235181-hc

**Comment by nerdysandy** [comment]
We're sunsetting Store by Feb,2021. Closing it in favour of that
