### ISSUE TITLE
[Idea] Make the enter name step more clear 

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#42602]
A couple more thoughts on this page, if we are seeing dropoff here (which will always be high to some extent). I’m looking forward to seeing what users actually type and where they are getting stuck on hotjar. I do miss the suggested names with the typing in gray. I felt that made it clear what to do, whereas right now I’m tempted to press skip. Adding things like ‘Yoga Sunrise Studio’ or ‘Rick’s Blog’ or ‘Brown and Black Law Firm’ will help, I think.

<img width="1058" alt="WordPress_com" src="https://user-images.githubusercontent.com/1103209/82751468-7d806880-9d85-11ea-8f89-4bf6c6aa9a6a.png">

**Comment by amamujee** [comment]
What's the status of this one?

**Comment by olaolusoga** [comment]
I think it's worth adding to see if we see a decrease in dropoff. 

Noticed on https://wordpress.com/create-blog/ we have a similar animation pattern (see GIF below). Let's use the site names from there, removing the TLD's at the end. So infocusphotographers, Cortado Coffee SF, Leah Rand Ava Young, Mighty Leaf Tea Room. We can add more if needed.

![Screen Capture on 2020-05-29 at 10-29-02](https://user-images.githubusercontent.com/1382943/83271406-d55d0c00-a197-11ea-960d-e64976dff235.gif)

Unsure if that will be enough, but it seems like a good start to encourage input.

**Comment by dubielzyk** [comment]
We've added suggestion in prod now
