### ISSUE TITLE
Sidebar: Empty Tools and/or Manage tabs are visible for non-admins

### ISSUE THREAD

**Issue by malinajirka** [Automattic/wp-calypso#42619]
#### Steps to reproduce 
1. Load calypso on a mobile device: https://wordpress.com/home/[SITE_URL] (use a site on which you are a Contributor) [Tested on "malinajirka.wordpress.com"]
2. Notice "Tools" and "Manage" options are visible. However, they are empty and the only thing that happens when you click on them is an animation.

#### What I expected
I expect the tabs to be hidden when they are empty. (https://github.com/Automattic/wp-calypso/pull/33298 and https://github.com/Automattic/wp-calypso/pull/33029)
#### What happened instead
"Tools" and "Manage" options are visible. However, they are empty and the only thing that happens when you click on them is an animation.

#### Browser / OS version
Chrome, Android

#### Screenshot / Video
![mobile-web (1)](https://user-images.githubusercontent.com/2261188/82806247-aab44000-9e85-11ea-99a9-042d98fe0bcc.gif)

**Comment by mirka** [comment]
I'm also seeing this problem in desktop layouts.

But I can't reproduce it for the "Tools" menu (only "Manage"), so there might be another condition for it to happen.

Relevant file: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/sidebar/index.jsx

**Comment by lamosty** [comment]
I thought this is a P2/WP for Teams bug but it's present for non-p2 Calypso sites too. Unassigning for now to fix other higher-pri items for P2.
