### ISSUE TITLE
Plans page url with trailing slash and single site causes routing error

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#42628]
#### Steps to reproduce

1. Make sure your account has only a single site.
2. Visit URL: https://WordPress.com/plans/ (note the trailing slash)

#### What I expected

To see the Plans page.

#### What happened instead

The URL adds another trailing slash after `/plans/`, turning it into `/plans//` and then adds the site slug, so it becomes `/plans//example.com`. This causes a routing error and you see a blank page.

![Screen Shot 2020-05-25 at 1 41 20 PM](https://user-images.githubusercontent.com/2036909/82833951-88262500-9e8d-11ea-9c57-d874752a8434.png)

**Comment by gwwar** [comment]
Should be a good intro to Calypso client routing
