### ISSUE TITLE
Domain Picker: make tests work again

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#42638]
### Why
For countless reasons, we want to have the confidence that our code works in the way we, developers, intended. Having unit tests is one of the options to build that. 

### What

We'd lost the tests for the package. I've added changes to ensure the tests run in the package, but they seem to break with `ReferenceError: regeneratorRuntime is not defined`.

I've reverted that change (d26e225c928152d05a5ce39b406d600a1de881ff) and we can work to restore the tests in a follow-up.

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/42409#issuecomment-633638142_

### A/C
* [ ] All unit tests for traintracks events are enabled
* [ ] All unit tests pass

**Comment by yansern** [comment]
Due to the introduction of additional props in `SuggestionItem`, which were pretty much duct tape to make analytics work, my suggestion is to fix analytics first https://github.com/Automattic/wp-calypso/issues/42639 before fixing this test.

**Comment by sirreal** [comment]
I believe this is more related to some build setup and not a problem with analytics, although I may be wrong 🙂 

Was there a specific reason you believe this is a problem with analytics?

**Comment by yansern** [comment]
Build setup is one issue. It's referencing to the wrong path since files have been moved around.

The other issue is that there are 3 duct-tape-props `domainSearch`, `analyticsFlowId`,  `domainSuggestionVendor` were added to `SuggestionItem`, which in the test file did not pass those values in.

A temporary fix was just to add those 3 props in to all the `<SuggestionItem>` in the test file with hardcoded values.

And I think a proper one is to think about how we're going to refactor our analytics to see how to readjust this test file.
