### ISSUE TITLE
Domain picker: tracking issue in Gutenboarding

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#42649]
#### Steps to reproduce

1. Starting at URL: /new/design with analytics debugging active.
2. Wait for Domain Picker button to appear and open it to select a domain.

#### What I expected
* After selecting a new domain and pressing Confirm button the new selected domain should be recorded.

#### What happened instead
* The previous domain selected was recorded by Tracks and `undefined` if there was no previously selected domain.

#### Screenshot / Video
https://cloudup.com/ccOah6T7Lnf

#### Context / Source
Introduced in https://github.com/Automattic/wp-calypso/pull/42409
Might be related to https://github.com/Automattic/wp-calypso/issues/42639 but probably needs to be fixed inside DomainPicker package.

**Comment by yansern** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/42659.
