### ISSUE TITLE
Framework: content pages leak through sidebar in Firefox (Mobile)

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#4264]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com
2. Open My Sites (will default to Stats)

#### What I expected

The normal menu (this is Chrome):

![screen shot 2016-03-23 at 18 05 25](https://cloud.githubusercontent.com/assets/4389/13995624/d8b29512-f121-11e5-9313-d4df75d7e83c.png)

#### What happened instead

Stats leak through (this is both Firefox 43 and 44):

![screen shot 2016-03-23 at 18 03 51](https://cloud.githubusercontent.com/assets/4389/13995646/e99720b4-f121-11e5-9523-d4bded426202.png)

Note not just the graph but also the Gridicons and title fades below.

#### Browser / OS version

Firefox 43 + 44 / OSX 10.11.2

**Comment by lancewillett** [comment]
I can't repeat this with Firefox stable on OS X 10.11.4.

Steps are also not the same anymore — default https://wordpress.com/ landing is Reader, not My Sites.

Feel free to re-open if you can repeat this still.
