### ISSUE TITLE
Gutenboarding: move launch button to FSE

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#42647]
Currently, we have code to inject "Launch" button (and modify other buttons) in [`wpcom-block-editor`](https://github.com/Automattic/wp-calypso/blob/a72348f477aa138d34fd764631dd69b325f444be/apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js) app.

Let's move this handling to FSE plugin so that we tie it closer together with the rest of the Gutenboarding launch-flow features we're developing in the FSE plugin currently. This should improve the developer experience.

The launch button should not only be injected at the header and direct you to Calypso but:
- When clicking it, current page should be saved https://github.com/Automattic/wp-calypso/issues/42655
- If the user doesn't have paid domain, show domain modal
- If the user doesn't have a paid plan, show plans modal
- Only then direct to Calypso for the rest of the launch flow.

Opening those modals (instead of redirecting straight to Calypso) will be behind a feature flag initially until we're done with them.

Here's the launch button visible:

<img width="621" alt="Screenshot 2020-05-26 at 15 23 22" src="https://user-images.githubusercontent.com/87168/82900216-dc500880-9f64-11ea-9c16-88d58ed5ed18.png">

<img width="651" alt="Screenshot 2020-05-26 at 15 23 29" src="https://user-images.githubusercontent.com/87168/82900212-dbb77200-9f64-11ea-8b28-76077ee7ab6d.png">

**Comment by sirreal** [comment]
Complete as of r208535-wpcom!

**Comment by simison** [comment]
Excellent 👍  I'll add a new issue for the launch flow.
