### ISSUE TITLE
Editor: HEIC image format seems to break block editor alignment when drag and dropped in

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#42667]
#### Steps to reproduce

1. Load up a wordpress.com site (This happened specifically on an atomic site).
2. Drag and drop an HEIC image (high efficiency image for apple IOS) into the block editor from a finder window. (See "Context" below for details)

Notes: 
* On large screens, the block will shift far to the left.
* Image loads indefinitely. No error or preview ever appears. Upon page refresh, a test string resides. Block is still off to the left.

#### What I expected

To drag and drop an image and have it display as an image block.

#### What happened instead

Block shifts to the left, breaking the layout within the editor. Image never loads. 

#### Browser / OS version

Chrome Version 81.0.4044.138 (Official Build) (64-bit) on Mojave 10.14.6

#### Screenshot / Video

After drag and drop of HEIC image:
![Screen Shot 2020-05-26 at 2 11 53 PM](https://user-images.githubusercontent.com/214813/82936408-8a0ae980-9f5c-11ea-950f-067bd1c331b7.png)

After manual page refresh
![Screen Shot 2020-05-26 at 2 18 51 PM](https://user-images.githubusercontent.com/214813/82936415-8e370700-9f5c-11ea-9496-a9941c478a90.png)

#### Context / Source

I opened wordpress.com and navigated to my site adventuretactician.com in order to write a post and add some images. I store my images on box.com - if you upload images directly from an iphone to box, they retain their HEIC image format. I tried simply dragging and dropping them from my finder window into the block editor and this is what occurred. 

Let me know how else I can help!

**Comment by davipontesblog** [comment]
What happened here is that we don't actually allow .HEIC images in WordPress.com, but the editor did not display the proper error message to indicate that.

Here are our public resources that mention the filetype is not allowed:
https://wordpress.com/support/accepted-filetypes/#images
https://wordpress.com/support/images/#image-file-types

Both simple and atomic sites display the proper message indicating that now, so I am closing this issue. Here are the screenshots showing that:

Simple:
<img width="870" alt="simple" src="https://user-images.githubusercontent.com/31009008/114183107-5b49f780-9911-11eb-85e8-70a11d2fba14.png">

Atomic:
<img width="998" alt="atomic" src="https://user-images.githubusercontent.com/31009008/114183032-5127f900-9911-11eb-93b2-fcd4dd3d2b95.png">
