### ISSUE TITLE
Stats dropped from 3000+ to less than 200 after 23 May 2020

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#42686]
![Screenshot](https://d.pr/i/Fpy4zq+)
*if image does not load, please click on this link  : https://d.pr/i/Fpy4zq*

#### Steps to reproduce
This is a site on American history and Customer has observed consistent view trends which dropped suddenly on 22 May 2020. Since then, it has stayed low.

I checked BRC and there is no major change (theme or content change) in the May 2020.

Can you check whether there is anything on the server that could explain this drop?

#### Context / Source
#3008455-zen

**Comment by davipontesblog** [comment]
Posted internally: p56BUd-n0-p2
