### ISSUE TITLE
Refactor Inline Help components to use Hooks API

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#42699]
Non-blocking but please prefer hooks (useEffect) over lifecycle events if we don't have a particular reason for it, as many components don't need to be classes. 

We can save this for a future janitorial though if this code is kept.

https://reactjs.org/docs/hooks-effect.html

_Originally posted by @gwwar in https://github.com/Automattic/wp-calypso/pull/42625_

**Comment by obenland** [comment]
Let's do that when we're updating those classes next time.
