### ISSUE TITLE
My Home Support Search - consider using `components/inline-support-link` in search results

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#42696]
Also optional, but maybe `components/inline-support-link` might be useful in search results?

_Originally posted by @gwwar in https://github.com/Automattic/wp-calypso/pull/42625_

-------

Currently the copy/pasted component which originally came from `inline-help` uses a custom coded inline support link in the search results. Can we make use of an pre-existing component?

**Comment by obenland** [comment]
We won't realistically get to this any time soon. Let's reopen when circumstances change.
