### ISSUE TITLE
(8P) Extract shared components for "Support Search" for FAB and My Home Search

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#42704]
There is a lot of code similarity between the FAB ("InlineHelp" components) and the My Home "HelpSearch" components. In fact the later is basically a copy/paste of the former. 

[The reason for this is explained here](https://github.com/Automattic/wp-calypso/pull/42625#issuecomment-634667967).

This Issue tracks the need to extract a limited set of commonly shared components that can be reused between the two instances. This ensures they will remain distinct whilst avoid excessive code duplication.

The original review noted these in particular but there will be other areas:

* https://github.com/Automattic/wp-calypso/pull/42625#discussion_r431029667
* https://github.com/Automattic/wp-calypso/pull/42625#discussion_r431030666
* https://github.com/Automattic/wp-calypso/pull/42625#discussion_r431032287

cc @mmtr

**Comment by retrofox** [comment]
PRs
===

HelpSearch: Update/help search refact search card #43410
