### ISSUE TITLE
Launch flow: recommended domains should mention that they're included in your plan

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42710]
If a person makes a purchase during signup, when they get to the launch flow they see this:

![image](https://user-images.githubusercontent.com/437258/83033311-f2150a80-a004-11ea-8dbf-b0ccd13747b5.png)

The domains imply there is an additional fee on top of the plan that was purchased, which is not true. 

We should instead represent them the way we do in signup—free for the first year, with a renewal price. 

![image](https://user-images.githubusercontent.com/437258/83033493-2dafd480-a005-11ea-8bfd-4d3cb70ddb78.png)

**Comment by klimeryk** [comment]
@eltongo was this fixed by https://github.com/Automattic/wp-calypso/pull/41438? Or do we need a follow-up?

**Comment by razvanpapadopol** [comment]
The domain is tagged as _Free_ only in `/checkout`, after pressing the _Select_ button on domain selection page.
We'll try to include this as part implementing launch flow inside the Editor in https://github.com/Automattic/wp-calypso/issues/43750

**Comment by klimeryk** [comment]
Nice, thanks for the follow-up, @razvanpapadopol!

**Comment by razvanpapadopol** [comment]
Latest design with _Included in your plan_ text displayed when a user has purchased a plan without a domain:
<img width="438" alt="Screenshot 2020-07-27 at 09 57 59" src="https://user-images.githubusercontent.com/14192054/88512978-19318d80-cff0-11ea-8798-9d0910fc50bb.png">

**Comment by razvanpapadopol** [comment]
This is included now in all launch flows.
