### ISSUE TITLE
Paid plan status not updated in sidebar

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#42711]
### Expected behavior

After purchasing a plan via signup flow, I expected the site plan to be shown in the sidebar

<img width="273" alt="Screenshot 2020-05-27 at 11 43 31 AM" src="https://user-images.githubusercontent.com/1269602/82984231-5937bc80-a00f-11ea-8636-bb1ae7023c55.png">

### Actual behavior
- I don't see my current plan updated on the sidebar, and I'm shown to be on the Free plan. 
- Since we no longer seem to show congratulatory messages on purchase(we now say "Your site has been created!"), it's a bit confusing to see that I'm on the free plan and makes me suspect that my transaction did not go through. 
- The site plan updates if I reload the page or go to the Plans page. 

![planstatus](https://user-images.githubusercontent.com/1269602/82984370-ad42a100-a00f-11ea-97c3-449413e077d8.gif)

### To Reproduce
1. Go to wordpress.com/start and begin a fresh signup. Or in an existing account, click Add new site.
2. Go through the signup flow and purchase a plan. After completing payment, you should land in Customer Home.
3. Check the plan status in the sidebar.

### Important Note

I see this issue only when I purchase via the new checkout. To see the new checkout, you need to be on a US IP address and assigned to `composite` variant of `showCompositeCheckout` A/B test. I do not see this error in the old checkout flow.

**Comment by sirbrillig** [comment]
It looks like old checkout does a bunch of things just before redirect, which we don't do. It's probably stuff in there:

https://github.com/Automattic/wp-calypso/blob/a3b590b5ca5e71adcdce1e70f147d13a7165be99/client/my-sites/checkout/checkout/index.jsx#L686-L721
