### ISSUE TITLE
Me: On mobile, I have to enter a 2FA code to logout

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#4272]
#### Steps to reproduce
1. Starting at URL: wordpress.com on a phone
2. touch profile picture to go to me (I want to logout)
3. Get a 2FA prompt thrown in my face

#### What I expected
A way to logout without knowing a 2FA code

#### What happened instead
I had to enter a 2FA code to logout

#### Browser / OS version
ios 8 / safari

**Comment by lancewillett** [comment]
Might be a duplicate of #202

**Comment by lancewillett** [comment]
Closing in favor of older issue.
