### ISSUE TITLE
Fix incorrect prop type in My Home "Help Search" card.

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#42742]
> There is "Failed prop type: Invalid prop hasAPIResults of type number supplied to HelpSearchResults, expected boolean." warning message raised after performing a search. I believe those are hidden in production so let's consider it a non-blocker (but let's make sure it's fixed in a follow-up).

See https://github.com/Automattic/wp-calypso/pull/42625#issuecomment-634711323

**Comment by getdave** [comment]
See also https://github.com/Automattic/wp-calypso/issues/38860

**Comment by getdave** [comment]
@mmtr I tested this by appling `code-D43941` and checking for the prop type error. I cannot replicate. Can you?

**Comment by mmtr** [comment]
I think this was fixed by @obenland in https://github.com/Automattic/wp-calypso/pull/42625/commits/aada56b699fcb83949b4b20232b7d939a0ed2829

**Comment by getdave** [comment]
Ah I missed that. Thanks @obenland (and sorry @mmtr!)
