### ISSUE TITLE
Fix padding and spacing for My Home "HelpSearch" card.

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#42743]
> Thanks for all your work on this @getdave! I think we're good to go with the card design wise as you have it. We can always adjust the padding in the follow up PRs. My thinking behind aligning the search content to the heading and the background hover to the edges of the card is that we're having more real estate to display the results. But this is not a blocker to the current work.

Originally posted in: https://github.com/Automattic/wp-calypso/pull/42625#issuecomment-634842653

----------

This issue tracks the required changes required to ensure that the `HelpSearch` card confirms to the design requirements laid out in [the original Issue](https://github.com/Automattic/wp-calypso/issues/38860).

@olesyabrk Please can you update this Issue with a list of changes required. The more detail the better as we're on opposite timezones. I'll then try and get these updated. Many thanks!

**Comment by olesyabrk** [comment]
![image](https://user-images.githubusercontent.com/51215741/83193210-7cd03500-a0eb-11ea-8781-2e19a91c7982.png)

[Figma](https://www.figma.com/file/RJunD2teJ28W3dUZiyeT27/Support-in-Customer-Home?node-id=833%3A2037)

Here you go. So the only changes are aligning the search results to the heading and expanding the focus state to the edges of the card.
