### ISSUE TITLE
Recurring payments: Custom text color not applied in the editor

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#42779]
#### Steps to reproduce

1. On a site with a paid plan add recurring payments button.
2. In the block settings panel on the right change text color to a custom color (do not choose from the theme color samples).
3. Note that the color is not being applied to the button text.
4. Save and preview the page. Note that the button text color is using the custom color as expected.

Tested with Stratford and Maywood themes.

#### What I expected
For the button to use the selected custom text color both in the preview and in the editor. The issue does not happen with the Buttons block.

#### Browser / OS version
FF 76.0.1 / macOS 10.15.4

![aKNRJNVa89](https://user-images.githubusercontent.com/4550351/83220394-31368d80-a1b6-11ea-8019-38915a3353d0.gif)

**Comment by gwwar** [comment]
Should be fixed with the Jetpack 8.7 release thanks to @mmtr  https://github.com/Automattic/jetpack/pull/16139
