### ISSUE TITLE
Using Google Social Login w/ email Matching a User Account w/ 2FA renders blank screen on linking step

### ISSUE THREAD

**Issue by cbauerman** [Automattic/wp-calypso#42774]
#### Steps to reproduce

**Note:** to reproduce you need
* a WordPress.com account that is **not**  linked to a google account **and** has 2fa
* a Google account with the same email as the above account

1. Starting at URL: WordPress.com/log-in
2. Use "Continue with Google" social login
3. Login with the Google account mentioned above
4. Verify you get a message: "We found a WordPress.com account with the email address "[email]". Log in to this account to connect it to your Google profile, or choose a different Google profile.
5. continue logging in, passed the 2fa step

#### What I expected

to get a page offering to connect the accounts:
![wordpress com_log-in_social-connect (1)](https://user-images.githubusercontent.com/2810519/83199090-5ca57380-a0f5-11ea-9778-f028b4fec3ae.png)

#### What happened instead

the page was mostly empty:
![wordpress com_log-in_social-connect](https://user-images.githubusercontent.com/2810519/83199122-69c26280-a0f5-11ea-9970-bf1b31179d07.png)

#### Browser / OS version

Chrome 83.0.4103.61/ macOS 10.15.4

#### Screenshot / Video

 see above

**Comment by alshakero** [comment]
This should be fixed by https://github.com/Automattic/wp-calypso/pull/44225.

**Comment by yansern** [comment]
Tested with Google Account and I can verify it is working now!
