### ISSUE TITLE
2FA expires too early when 30 days is set

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42773]
Remember for 30 days is not respected when visiting https://wordpress.com/me with 2FA enabled

<img width="430" alt="Screen Shot 2020-05-28 at 2 51 28 PM" src="https://user-images.githubusercontent.com/1270189/83197734-cc662f00-a0f2-11ea-9c00-308490be9969.png">

To reproduce:
1. Delete the "twostep_auth" cookie on the wordpress.com domain
2. Visit https://wordpress.com/me
3. See the modal and check remember for 30 days, authenticate
4. Inspect the expiry on "twostep_auth"

With the checkbox set it's incorrectly set to "session" instead of 30 days from now.

<img width="903" alt="Screen Shot 2020-05-28 at 2 50 01 PM" src="https://user-images.githubusercontent.com/1270189/83197996-4991a400-a0f3-11ea-9d38-4df60c89dce2.png">

**Comment by mmtr** [comment]
D44162-code should fix this.
