### ISSUE TITLE
Auto save notification not present (or not autosaving)

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#42805]
## Steps to reproduce

1. Go to Site > Pages/posts > Add new/edit
2. Make some changes to your post
3. Don't click "Save Draft"
4. Leave post 
5. Follow step 1 > go to page/post to edit

#### What I expected

To see the autosave action happen as per: https://wordpress.com/support/editors/page-post-revisions/#saving-and-autosave

When re-entering the post, to see my content and before I left the post. 

#### What happened instead

I see notification "There is an autosave of this post that is more recent than the version below.
View the autosave" 

I then have to load the revisions and load my changes. 

#### Browser / OS version

Chrome 83 on macOS (Catalina)

#### Screenshot / Video 

https://d.pr/v/Efu3LJ

#### Context / Source

#user-report hc-21488316
-->

**Comment by simison** [comment]
This is working as expected; as long as you don't press "update/save draft/publish" before exiting the editor, you'll have an autosave.

When re-opening the editor, you won't get autosave in the editor visible, but the version that was saved earlier. That's how WordPress has always worked.

Unless I'm missing something? If I did, feel free to re-open. :-)

If that behavior should be changed, can you open an issue at https://github.com/wordpress/gutenberg/issues ? Thanks!

**Comment by aleone89** [comment]
Hello @simison many thanks for taking a look. 

I can't help but feel something is up here.

**> This is working as expected; as long as you don't press "update/save draft/publish" before exiting the editor, you'll have an autosave.**

I've test this on one test here: https://d.pr/v/9Qhgim whereby the auto-save didn't kick in. 

I tested this on a different test site, whereby the auto-save kicked in (eventually) https://d.pr/v/rTlIYQ after nearly a minute of inactivity - as opposed to "every few seconds" as detailed in the support doc.  

Is it possible to find out if the duration between autosaves has changed?

**Comment by simison** [comment]
Thanks for elaborating! I'll add this on maintenance folks' board to see if they spot anything off.

**Comment by aleone89** [comment]
No - thank you! Much appreciated :)

**Comment by tanjoymor** [comment]
I've readded the bug label on this as I am also able to reproduce this. Here's a recording of the process: https://d.pr/v/MSpb60

While the auto-save does sort of work... it's certainly not "every few seconds" as indicated in our documentation. You'll see in my video how much of my last changes pull in on the page when reloading the "auto backup" and that some of the last changes are missing and over 15 seconds went by between what it did auto-save up to vs what else I had typed when I closed the page without saving myself.

And there's definitely no notification of the "saving" occurring while working on the page - which it used to have.

**Comment by aleone89** [comment]
There's another report of this here: hc-22375689

**Comment by kriskorn** [comment]
Another report in 3162838-zen

**Comment by david-szabo97** [comment]
@tanjoymor
I found out the autosaving to remote occurs every 60 seconds. This also includes saving animation.
Local autosave is triggered every 15 seconds, this one doesn't include any saving animation.

**Comment by noahtallen** [comment]
This isn't buggy behavior, as far as I can tell. It's just that the auto-save interval is a little long. I think the reality is that gutenberg auto-save is just not great. IMO, we need to spend time working on auto-save as an actual feature for WordPress.com. I think it should be realtime, ideally :)

Regarding this:

> Is it possible to find out if the duration between autosaves has changed?

It looks like the support doc is referencing the old Calypso-classic editor, which probably has a different auto-save mechanism (and timings!) than Gutenberg. I will try to find the right people to update that page with more modern information!

**Comment by noahtallen** [comment]
I've updated the support page to reference the longer interval
