### ISSUE TITLE
My Home: Error when Dismissing Editor Deprecation Notice

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#42815]
#### Steps to reproduce

Clicking the "Dismiss" button on "The new WordPress editor is coming" task doesn't work, even on refresh, and instead causes a console error.

<img width="1682" alt="Screenshot 2020-05-29 at 20 34 45" src="https://user-images.githubusercontent.com/43215253/83298181-dcae0500-a1eb-11ea-80a5-b62446c2dd18.png">

#### What I expected

I'm not even sure if this should be dismissable - it seems like a pretty important notice. I've looked through #41570, and it seems like that it is the intention though, so the dismissing function should work.

#### Browser / OS version

Chrome/83.0.4103.61, Macintosh; Intel Mac OS X 10_14_6

cc @glendaviesnz, @gwwar

**Comment by gwwar** [comment]
Thanks for the report @Aurorum !
