### ISSUE TITLE
CoBlocks Carousel Gallery Block: Setting Wide or Full Width Makes Images Disappear in the Editor

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#42827]
#### Steps to reproduce

1. On a Page add the CoBlocks Carousel Gallery Block and a few images to it (on a site with CoBlocks plugin and Varia Theme)
2. Change its width from the alignment options to `Wide width` or `Full width` 

#### What I expected
Continue to see images in the Editor

#### What happened instead
Images vanish from the block in the Editor view (but still visible on the published page)

#### Screenshot / Video
![Screen Capture on 2020-05-30 at 18-32-22](https://user-images.githubusercontent.com/39308239/83334060-3540d900-a2a4-11ea-9858-c7aaeb14fc52.gif)

#### Context / Source

#manual-testing #user-report 
21506072-hc

**Comment by jeyip** [comment]
I confirmed this problem with multiple themes (varia, twenty-twenty, barnsbury) on an atomic site with CoBlocks v2.01 and Gutenberg v.8.30

**Comment by david-szabo97** [comment]
Fixed in CoBlocks v2.2.0
