### ISSUE TITLE
Donation Block

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#42825]
_@davemart-in, May 30, 2020_

| | |
------------ | -------------
**Description** | Give customers the ability to add a donations block to their site
**Goals**  | Increase the usage of our payments features which increases the value of a WP.com site for site owners.
**Metrics**  | Increase payments volume for site owners
**Stakeholders**  | @davemart-in, @amamujee, @rickybanister 
**Team** | Product Lead: @davemart-in <br>Eng Lead: @gwwar & @artpi<br>Design Lead: @danhauk <br> Marketing Lead: @anneforbush 

#### User story

As a WP.com customer, I should be able to collect donations, so that I can raise money for a specific cause, or event.

**Acceptance criteria**

* **Free Users** - As a free plan user, I should be able to add the donation block, but I will need to upgrade to a paid plan before I can use it.
* **All paid plans** - As a paid plan (including the Personal plan) customer I should be able to add the donation block, be prompted set up my Stripe account and start accepting donations.
* **Preset amounts** - As a customer, when I add the donation block for the first time, all 12 subscriptions should be auto-generated for me. 
* **Default to USD** - For the v1 we will default to USD. This can be manually changed for each donation subscription. In the future we may consider centralizing this based on customer feedback.
* **Manage Donations subscriptions** - As a customer, I should see a link in the block sidebar which takes me to the screen in Calypso where I can manage my donation subscriptions - which are separate from the other customizable subscriptions:

<img width="1056" alt="Image 2020-06-05 at 12 57 19 PM" src="https://user-images.githubusercontent.com/5634774/84038492-04306a80-a96e-11ea-8ab1-1e2bf25f5e12.png">

* **Editable Amounts** - As a customer, I should be able to edit the amount that is set for each tier.
* **Toggle Payment Options** - As a customer, I should be able to toggle monthly, annual, and "Other" payment options on or off.
* **Can't Delete Donation Subscriptions** - The 12 donation subscriptions should not be deletable from within the Calypso management UI. Doing so would break the Donation block logic.
* **Reuse Donation Subscriptions** - If multiple donation blocks are added, they will use the same set of subscriptions

#### Stuff we're intentionally leaving out of the v1

* **Editing the Number of Tiers** - Customers will not be able to edit the number of donation tiers that they show. We will default to 3 tiers plus the optional "Other" payment.

### Questions

**Q: Will this block be available on JP?**
A: No. We will ship this block via FSE, similar to the premium content block.

**Q: Which plans does it affect?**
A: All of them. We'll want to show a preview on the free plan with a prompt to upgrade. All of the paid plans (including Personal) should be able to add a donation block.

**Q: What are the mobile implications?**
A: We'll want to make sure that the donation block renders well on customers sites via mobile web. We will not be implementing this block in the native apps at this time.

**Q: Will there be an A/B test?**
A: No.

**Q: What event logging do we need? What metrics will we track?**
A: We should get the typical block metrics for inserting and publishing for free. I would like to create an MC stats report (if there isn't already one) which shows the distribution of payment revenue across A) the recurring payment block, B) The premium content block, C) the donations block.

### Design

Artur wisely suggested that we borrow the front-end design from the Newspack donation block, then replace the back-end with our infrastructure. Here's a peek at what the Newspack donation block looks like:

![Screen Recording 2020-05-30 at 10 43 AM](https://user-images.githubusercontent.com/5634774/83331397-1cb0ce80-a264-11ea-94b2-7a130b7fb3ae.gif)

Matt suggested that we copy ActBlue since their donation process is highly optimized. I took their flow for a spin and it [aligns well](https://cl.ly/7311733ea760) with what Newspack came up with.

Since most of the design is already in place, I roughed out a quick general design for this block:

![Donation-block](https://user-images.githubusercontent.com/5634774/83331405-3225f880-a264-11ea-8ba5-fcb41385fcc0.png)

@danhauk I'll leave this in your capable hands.

### Engineering

I'll leave this up to @artpi and @gwwar to figure out, but it would be great if we could break this up into a couple of phases:

- **Phase 1) Add on-off payments** - Introduce one-off payments to the recurring payments block
- **Phase 2) Copy Newspack donations** - Import Newspack donation block and replace back-end with our infrastructure
- **Phase 3) Clean up** - which includes:
— Renaming Recurring Payments to be “Payments”
— Renaming Simple Payments to be “PayPal”
— Updating support docs to account for these changes

### Marketing

TBD by @anneforbush 

### Launch Checklist

**Planning**
- [x] **Master Thread** - MT created and Marketing, Legal, Happiness, Mobile, JP pinged with a heads up
- [x] **v1 Design** - Initial design concept has been created

**Development**
- [ ] **Kick-off Meeting** - Call with team to discuss this project and address any questions or concerns
- [ ] **Estimation** - Project has been broken out into individual GitHub cards and time estimations have been made on each card
- [ ] **Refined Design** - Initial designs have been revised based on feedback
- [ ] **Product Marketing** - A plan has been created with the help of Marketing for how we'll announce this with customers
- [ ] **Measurement** - Tracking has been added for this feature
- [ ] **Development** - Major development has completed
- [ ] **Support Docs** - Applicable support docs have been created/updated (See [this issue](https://github.com/Automattic/en.support-docs-content/issues/650))

**Testing/Launch**
- [ ] **Design Review** - Designer has reviewed and signed off on this feature
- [ ] **Aadil Review** - Aadil has had a chance to play with this feature and provide feedback
- [ ] **Engineering Review** - Engineers have reviewed and signed off on this feature, testing multiple browsers/resolutions, RTL, security check, accessibility
- [ ] **Call for Testing** - A call for testing has been posted to Dotcom P2 and Happiness has been pinged
- [ ] **Bug Fixes** - All feedback has been resolved and bugs have been fixed
- [ ] **Happiness Heads Up** - Drop a note in #wpcom-happy-announce
- [ ] **Launch** - Feature has been launched

**Post Launch**
- [ ] **Announcement Post** - Publish the post you had drafted at the beginning of this project
- [ ] **Monitor Feedback** - Watch support, social channels, and the en.blog post for signs of bugs or confusion
- [ ] **Post-Mortem** - Write a post-mortem about the feature launch on your team blog
- [ ] **Check Stats** - Did the feature have the impact you expected? Why or why not?

**Comment by artpi** [comment]
Awesome @davemart-in ! This aligns well with everything I hoped it would be.

Let me chime in some context:
> Phase 1) Add on-off payments - Introduce one-off payments to the recurring payments block

This is essentially already done, by the means of the "Lifetime plan". We only have to "turn it on" in the UI, which should be trivial.
However, after that, we have to review all emails, UI and all surface points of the Recurring Payments / premium content to see if it still shows up as a proper "one time payment".

So the task I would put here, would be:

"Create a lifetime plan (option value: `one-time`)" and document (screenshot) all places where it shows up: Gutenberg blocks, (recurring paymetns & premium content), checkout flow for the user, emails for the user, subscriber list for the seller, monthly email for the seller."

I can honestly take that.

Task #2 would be to have some design help in reviewing this.
After this review, we would identify all tasks needed to update interfaces. That work should happen at the same time we are renaming to payments, since presumably it touches the same areas

In the meantime, I'd start with the donation block ripht away - I'd put somebody on a spike to make it work ASAP (crudely). And produce new tasks to make it properly.

**Comment by davemart-in** [comment]
> Question :do we try to redesign simple payments into a button as well at this time according to new design?

Nope. We'll get there, but let's hold off on adding any additional scope to this project.

**Comment by simison** [comment]
> Q: Will this block be available on JP?
> A: No. We will ship this block via FSE, similar to the premium content block.

> Q: Which plans does it affect?
> A: All of them. We'll want to show a preview on the free plan with a prompt to upgrade. All of the paid plans (including Personal) should be able to add a donation block.

Might still wanna re-use Jetpack infra for making blocks conditionally available, and showing the upgrade nudge? Since the Jetpack plugin is always active, it's fine to have it as a hard dependency for the FSE plugin. Duplicating the logic (and UI) in both doesn't make sense to me and would just double-up the maintenance work down for years to come.

**Comment by artpi** [comment]
> Might still wanna re-use Jetpack infra for making blocks conditionally available, and showing the upgrade nudge? Since the Jetpack plugin is always active, it's fine to have it as a hard dependency for the FSE plugin. Duplicating the logic (and UI) in both doesn't make sense to me and would just double-up the maintenance work down for years to come.

We would love to!
The problem last time we checked was that Jetpack bundled a lot of this in it's build files and since a lot of that logic was client-side, there simply was no way to hook into it.
Unless I am mistaken and there is a good way of hooking into it?
