### ISSUE TITLE
People: Role dropdown is not translatable

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#4284]
User role selection dropdown is not translatable.

<img width="491" alt="user-role" src="https://cloud.githubusercontent.com/assets/34067/14009243/56bb4624-f1cd-11e5-8c54-734a604cbc1a.png">

File: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/people/role-select/index.jsx#L125

**Comment by akirk** [comment]
@allendav do you know if the list-roles API endpoint return localized role names?

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Confirmed this is still an issue
