### ISSUE TITLE
(5P) Checklist: Remove "Your site has been created" card

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#42846]
This issue is an idea for a checklist enhancement on the home screen based on my own testing. 

When starting a new site on WP.com the success message on the home screen looks like this.

![image](https://user-images.githubusercontent.com/545779/83428626-5f0b1480-a3f8-11ea-914d-e32c07d342c5.png)

Perhaps because of my own banner blindness when I first saw this I wondered where the checklist went. :)

It made me wonder if, instead of a banner _hiding the checklist_ we shouldn't have the banner content …

![image](https://user-images.githubusercontent.com/545779/83428733-91b50d00-a3f8-11ea-8faa-f21ac9bccc2b.png)

be the first (completed) step on the checklist here …

![image](https://user-images.githubusercontent.com/545779/83428777-a7c2cd80-a3f8-11ea-983f-de64414feebd.png)

… making those next steps less hidden, and giving a customer a first "completed" task.

Related convo: pbAPfg-yX-p2

cc @lcollette

**Comment by davemart-in** [comment]
@obenland I've just added this issue to your teams plate for the next cycle. Basically we want to:

- Remove the "Your site has been created!" card
- Show the checklist as the first screen new users see
- Add a checked off item at the top of the checklist that says "Your site has been created!"

**Comment by getdave** [comment]
Whoever implements this please consider:

* PCYsg-pPq-p2
* PCYsg-qqj-p2

The library [on WPCOM] is responsible for all logic related to what cards are displayed. The client [Calypso repo] is responsible for the look and functionality of the matching components themselves.

**Comment by obenland** [comment]
`VIEW_CELEBRATE_SITE_CREATION` is probably where that needs to be changed

**Comment by getdave** [comment]
# Implementation Notes

These are notes on technical implementation. I will update as I go.

## Useful Files

* `client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js` - outlines all the tasks in the list.

**Comment by getdave** [comment]
@ianstewart Can I confirm that the intention here is to:

1. Remove the banner `Your site has been created`.
2. Show the checklist instead.
3. Add a `✅ Site created` item to the top of the checklist (this effectively removes the need for the banner).

Just want to confirm I have that right. Thanks.

**Comment by gwwar** [comment]
This is 2 wpcom patches + a client update for the checklist.

1. In wp-content/lib/home/views.php drop `VIEW_CELEBRATE_SITE_CREATION` from the following list.
```php
// Views to use on Simple and Atomic sites. First applicable view will be used, so keep them sorted by priority.
const VIEWS_SIMPLE_AND_ATOMIC = [
// ↓ Pre site setup views.
VIEW_CELEBRATE_SITE_CREATION,       // View for brand new sites. Displays a site created celebratory notice.
VIEW_CELEBRATE_SITE_LAUNCH,         // View for launched sites. Displays a site launched celebratory notice.
VIEW_CELEBRATE_SITE_SETUP_COMPLETE, // View for sites recently established. Displays a site setup completed celebratory notice.
VIEW_CELEBRATE_SITE_MIGRATION,      // View for imported sites. Displays a site migrated celebratory notice.
VIEW_SITE_SETUP,                    // View for unestablished sites. Displays a site setup list of tasks.
// ↓ Post site setup views.
VIEW_EDITOR_DEPRECATION,            // Shown when a user has editor set to classic. Warns of final deprecation date.
VIEW_GO_MOBILE,                     // Prompt on mobile to install the mobile app for the user's platform (if they are on Android or iOS)
VIEW_WEBINARS,                      // Prompt to register for our webinars.
VIEW_CONNECT_ACCOUNTS,              // Prompt to set up Publicize connections.
VIEW_FIND_DOMAIN,                   // Prompt to find a domain if site has not claimed yet the one included in paid plan.
VIEW_EARN_FEATURES,                 // Prompt user to check out Earn features.
// ↓ Default view.
VIEW_DEFAULT,                       // Gives a break from tasks.
];
```

2. Add completed task to checklist on wpcom. Example diff D41496-p2

3. Update Site Setup List on client (example https://github.com/Automattic/wp-calypso/pull/41791)

**Comment by gwwar** [comment]
Note that `onboarding_checklist_completed` is not trustworthy, as tasks have been added and removed over long periods of time on the server without recalculation. Be careful with displaying the site setup list/checklist again for existing sites.

**Comment by getdave** [comment]
Thanks for your input/advice @gwwar. Much appreciated.

> In wp-content/lib/home/views.php remove VIEW_CELEBRATE_SITE_CREATION from the following list.

I'm not 100% sure would we remove it entirely? I don't think Ian was suggesting to _completely_ remove the creation view, just adjust it. That said, perhaps with the banner removed it's the same as the default view? Is this why you're recommending removing the custom view? Some more context here would really help me.

> Add completed task to checklist on wpcom. Example diff D41496-code

Thanks for this. I'd actually managed to work out 90% of this on my own yesterday (I searched the FG but could find no documentation 😢 ) but I wish I'd reached out earlier! That said it was a good learning exercise. The piece I was missing was the `mark_task_complete` step. I can sort that now.

> Update Site Setup List on client (example #41791)

Worked this bit out too, but I did have to tweak the component a bit which renders the "action" buttons. I'll push a PR soon.

Thanks again for your help. I'll ping Serenity for a review once the PR is up.

**Comment by gwwar** [comment]
> Scratch that. I worked it out. We want to remove this view because now there is nothing to distinguish it from the VIEW_SITE_SETUP view especially as you can no longer dismiss the view via the Notice.

The ask of this issue is to no longer display the site creation celebration step, that's why we're removing it as a possible view to display. Feel free to DM if you're still confused, the TL;DR is we have 1 view per main task card (the banner with the illustration).

Let us know if anything at PCYsg-qpk-p2 doesn't make sense.

**Comment by ianstewart** [comment]
> Can I confirm that the intention here is to:
> 1. move the banner Your site has been created.
> 2. Show the checklist instead.
> 3. Add a ✅ Site created item to the top of the checklist (this effectively removes the need for the banner).

That was my intention/suggestion with the issue. Yep! cc @lcollette

**Comment by getdave** [comment]
This has been completed by https://github.com/Automattic/wp-calypso/pull/43861.

Spin-off tasks are in separate Issues.
