### ISSUE TITLE
Jetpack checklist: tour card doesn't disappear after hitting the back button

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/wp-calypso#42845]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/plans/my-plan/:site_id
2. Expand any item in the _My Checklist_ section
3. Click the _Try it_ button
4. You should be redirected to another page and see a tour card
5. Hit the browser back button

#### What I expected

Not to see the tour card anymore

#### What happened instead

You see the tour card

#### Browser / OS version

Tested with latest Chrome and Firefox, on macOS Cataline.

#### Screenshot / Video
<img width="1105" alt="Screen Shot 2020-06-01 at 11 36 07 AM" src="https://user-images.githubusercontent.com/1620183/83426317-f1151c00-a3fc-11ea-906c-eecfd9ace67a.png">

**Comment by jeherve** [comment]
Also reported in p8oabR-B4-p2#comment-4879

**Comment by Robertght** [comment]
I can't seem to replicate this anymore on my Jetpack site and the tour card only showed up once. 

@jeherve can I get a confidence check on this one?

**Comment by jeherve** [comment]
👍 This seems good to close now.
