### ISSUE TITLE
The seller does not get the email when the payment is one-time

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42864]
When setting up a one time payment plan (like for a donation) the seller does not receive an email, when someone makes a payment.

cc @artpi feel free to edit the summary if you have better steps

**Comment by eoigal** [comment]
This took a bit of digging but it turns out that we verify the seller data before sending email notifications. This verification isn't setup to deal with one-time ownerships so the email isn't sent.

D44566-code

**Comment by gwwar** [comment]
closed by D44566-code
