### ISSUE TITLE
Rename Recurring Payments to Payments

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42862]
Let's update this summary with all the "Recurring Payments" usages we can find on WordPress.com. This will help us determine how to launch these changes.

This is a user-facing rename. Please don't modify block data.

- [x] Block in Gutenberg Editor (Jetpack) https://github.com/Automattic/jetpack/pull/16133 (@artpi, @mmtr, @eoigal  )
- [x] Calypso: Earn > Payment Plans https://github.com/Automattic/wp-calypso/pull/42848 (@artpi )
- [ ] https://wordpress.com/support/wordpress-editor/blocks/recurring-payments-button/ pbMlHh-hn-p2 (@anneforbush)
- [ ] https://wordpress.com/support/recurring-payments/ pbMlHh-hn-p2 (@anneforbush)
- [ ] https://wordpress.com/support/ecommerce/ pbMlHh-hn-p2 (@anneforbush)
- [ ] https://wordpress.com/support/monetize-your-site/ pbMlHh-hn-p2 (@anneforbush)
- [ ] https://wordpress.com/support/wordpress-editor/blocks/premium-content-block/ pbMlHh-hn-p2 (@anneforbush)
- [ ] https://wordpress.com/support/paid-newsletters/ pbMlHh-hn-p2 (@anneforbush)
- [ ] https://wordpress.com/support/tutorials/build-a-virtual-classroom-website-tutorial/ pbMlHh-hn-p2 (@anneforbush)
- [ ] wpcom usages tracked in separate issue

**Comment by mmtr** [comment]
All support docs are being handled by Marketing in pbMlHh-hn-p2 (cc @anneforbush)

**Comment by gwwar** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/43925, D44970-code D44951-code
