### ISSUE TITLE
Rename Simple Payments Block to Pay with PayPal

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42861]
Let's rename "Simple Payments" to "Pay with PayPal Button". This is a user-facing rename. Please don't modify block data! Let's update this Summary with any known usages that we need to update. This will help us determine how we may launch this:

- [x] Block in Gutenberg Editor (Simple) D44789-code
- [x] Create a Pay with PayPal support article for [WPCOM](https://support.wordpress.com/simple-payments/) -> https://wordpress.com/support/pay-with-paypal-button/
- [x] Create a Pay with PayPal blocks support article for [Jetpack](https://jetpack.com/support/jetpack-blocks/simple-payments-block/) -> http://jetpack.com/support/jetpack-blocks/pay-with-paypal-button/
- [x] Create a Pay with PayPal utilities support article for [Jetpack](https://jetpack.com/support/simple-payment-button/) -> https://jetpack.com/support/pay-with-paypal-button/
- [x] Create a styling support article, similar to the [Simple Payments one](https://wordpress.com/support/simple-payments-styling/) -> https://wordpress.com/support/pay-with-paypal-button-styling/
- [x] Create a PR to change block name from Simple Payments -> Pay with PayPal button
- [x] Create phab patch to update places where Simple Payments term is used
- [x] Create a PR on Calypso to update places where Simple Payments term is used https://github.com/Automattic/wp-calypso/pull/43192
- [x] Update support articles to have up to date images/video/gifs with new terminology pbMlHh-hn-p2 (@anneforbush)
- [ ] Need a new video to replace https://www.youtube.com/embed/V8UToJoSf4Q pbMlHh-hn-p2 (@anneforbush)
- [ ] Need to delete the Jetpack simple payments support article so it's not list here - https://jetpack.com/support/jetpack-blocks/ pbMlHh-hn-p2 (@anneforbush)

<img width="302" alt="image-2020-06-04-at-5 03 29-pm" src="https://user-images.githubusercontent.com/1270189/83813002-5d985100-a671-11ea-8f43-306131eca1d9.png">

Part of https://github.com/Automattic/wp-calypso/issues/42825
Related conversation on names in p2y3YZ-43P-p2

**Comment by eoigal** [comment]
I see the term `Simple Payments` used in a few places in the block (views and dialogs) and outside the block (upsells and feature lists). Should we change to `Pay with PayPal Button` instead everywhere? I assume so but I'm not sure what you mean by "Please don't modify block data". Does this mean, don't change any slugs or any behaviour inside the block?

**Comment by eoigal** [comment]
Changes to Jetpack -> https://github.com/Automattic/jetpack/pull/16133

**Comment by eoigal** [comment]
Changes on WPCOM - D44789-code

**Comment by eoigal** [comment]
Changes to Calypso -> https://github.com/Automattic/wp-calypso/pull/43192

**Comment by eoigal** [comment]
https://github.com/Automattic/jetpack/pull/16133 is ready for review again.

There are also 2 related patches that also need a review on WPCOM.

* Changes made to non-Jetpack files - D44951-code
* Changes made to Jetpack files - D44970-code

**Comment by gwwar** [comment]
Note that folks have requested to shorten the rename in p2y3YZ-43P-p2

**Comment by gwwar** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/43925, D44970-code D44951-code
