### ISSUE TITLE
Auto-renew toggle: Allow toggling auto-renew immediately after renewal

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/wp-calypso#42877]
A user reached out in #3024561-zen after renewing a purchase, and wanted to disable auto-renew.
Currently, it's not possible to disable auto-renew during the renewal period.

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/purchases
2. Renew an existing subscription
3. Tap that subscription again to check auto-renew settings
4. Note you see "subscription renews on", but no option to disable auto-renew

When you've just renewed a subscription, it's a great time to check the renewal settings and users often want to disable auto-renew at this time. It's perhaps the most intuitive time to disable auto-renew as you're already thinking about the subscription and your finances.
We should allow users to disable auto-renew immediately after renewal. This is in addition to the option to cancel for a refund at that time.

**Comment by simison** [comment]
cc @rralian which team should triage this?

**Comment by michaeldcain** [comment]
@thehenrybyrd I can't reproduce this issue. If you renew a subscription from its subscription settings page, there should be a toggle immediately after returning to the page:

https://user-images.githubusercontent.com/942359/110365353-ee41fa00-8012-11eb-9527-3bff48512452.mov

If you're able to reproduce this, will you re-open the issue and include the site address/plan, or a video of the flow?
