### ISSUE TITLE
Gutenboarding: more tracks

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#42892]
We need to add some extra tracking events during the flow: 

- an event for performing a search, something like calypso_newsite_domain_search with a property (where) to indicate whether it was in the popover or the modal.
- there is a calypso_newsite_domain_select event, but it would be good to check that it fires whenever a domain is selected in both of the domain search UIs.  the number in that funnel seems low.
- Plans grid: for the calypso_newsite_modal_open event when name = 'PlansGrid', it would be useful to have another property selected that indicates free or premium or whichever plan that was pre-selected.
- Plans grid: recording click events when they select a plan would be useful

**Comment by simison** [comment]
>Plans grid: recording click events when they select a plan would be useful

While at it, adding event for toggling the "more features" grid could be added?

**Comment by ramonjd** [comment]
https://github.com/Automattic/wp-calypso/pull/42764/ will probably affect any immediate implementation of new tracks events

**Comment by razvanpapadopol** [comment]
> #42764 will probably affect any immediate implementation of new tracks events

PlansGrid extraction will affect only the last point where we need to record some events within the PlansGrid itself:
> Plans grid: recording click events when they select a plan would be useful

So I propose we tackle that one in a separate PR, after merging the PlansGrid extraction to package.

**Comment by lsl** [comment]
> * an event for performing a search, something like calypso_newsite_domain_search with a property (where) to indicate whether it was in the popover or the modal.

#43000 adds the on search event but this triggers multiple times per search (every character as you type.) It might be better to stick to using calypso_newsite_domain_select unless you're wanting to track the search/select step itself.

Could you give me some more context on what you're intending to use the tracks event for understanding? Were you hoping to debug the next step's low counts?

> *there is a calypso_newsite_domain_select event, but it would be good to check that it fires whenever a domain is selected in both of the domain search UIs. the number in that funnel seems low.

This fires on both modal and popover.

It might be worth pointing out this UI element is a fair bit out of sight (no strong CTA) so missed domain configurations at this stage are likely being funneled through to the post FSE launch process @ `/start/new-launch/domains-launch`

**Comment by ramonjd** [comment]
> there is a calypso_newsite_domain_select event, but it would be good to check that it fires whenever a domain is selected in both of the domain search UIs. the number in that funnel seems low.

@johnHackworth Adding to what @lsl says about the CTA, `calypso_newsite_domain_select` is fired only when you click on the confirm button, not the radio items. 

<img width="496" alt="Screen Shot 2020-06-09 at 11 22 33 am" src="https://user-images.githubusercontent.com/6458278/84095927-ee8d7480-aa43-11ea-812e-a8841ec269bb.png">

Just guessing, but perhaps it's the extra step – having to click the domain **and** also the confirm button – that is causing the drop? cc @olaolusoga

**Comment by olaolusoga** [comment]
>Edit: maybe the proposed design changes will address the CTA concerns

🤞 , once we launch the full domain page, we can make tweaks to make things more clear if we still see high dropoff

**Comment by lsl** [comment]
#43000 is in conflict with #43136, should be an easy resolution but I wonder if its still required given the new flow. I'm a bit concerned about sending tracks events for every key stroke in the search too.

@johnHackworth could you please advise if #43000 (tracking domain searches) is still required in light of the full domain page changes in #43136?

**Comment by ramonjd** [comment]
> I'm a bit concerned about sending tracks events for every key stroke in the search too.

It's being fired here:

https://github.com/Automattic/wp-calypso/blob/master/packages/domain-picker/src/domain-picker/index.tsx#L195

Ideally we'd debounce it. The [domain picker debounces searches](https://github.com/Automattic/wp-calypso/blob/master/packages/domain-picker/src/domain-picker/index.tsx#L100) after the input changes:

https://github.com/Automattic/wp-calypso/blob/master/packages/domain-picker/src/hooks/use-domain-suggestions.ts#L23

I wonder if there's a way to hook into that with an `onDomainSearchResultsChanged` or some other prop [we pass to <DomainPicker />](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/components/domain-picker-button/index.tsx#L67)

@alshakero or @razvanpapadopol will know for sure what the best approach would be
