### ISSUE TITLE
Page Layouts: Services layout has missing images

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#42904]
#### Steps to reproduce

1. Set your site language to French or Brazilian Portuguese at Settings > General. (Note that other non-English languages may also be affected, I only tested these two)
2. On WordPress.com, go to Sites > Pages > Add new page
3. Choose the one Services layout
4. Note the following errors in the preview:

<img width="1328" alt="New Page ‹ KP Main Test site — WordPress com" src="https://user-images.githubusercontent.com/7662449/83567979-75949700-a4f0-11ea-9177-0fdda6a7a1b8.png">

5.  Click "Use Services layout"

6. Note that the three images are missing in the editor:

<img width="1328" alt="New Page ‹ KP Main Test site — WordPress com-1" src="https://user-images.githubusercontent.com/7662449/83568062-9bba3700-a4f0-11ea-8a28-43e2eb73712b.png">

#### What I expected

The preview should have images visible in the column block, and the images should populate the editor after selecting the layout.

#### Context / Source

Noted during a WordPress.com Quick Start session with a user, and replicated on my own test site.

**Comment by davipontesblog** [comment]
I am moving this to the triaging board to see if it's still an issue with the new layout picker on simple sites. If so, we can close it.

**Comment by synora** [comment]
I'm unable to replicate this. This is a rather old issue so it's possible it was fixed along the way or recently with the new layout picker feature.
