### ISSUE TITLE
External Media: Load more button > Infinite Scroll

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#42907]
### Describe the problem
External Media in Calypso uses infinite scroll to load more images from Pexels and Google Photos. There are a11y concerns around infinite scroll and that feature will be out of line with how the in-block experience in Jetpack approaches it.

### Describe the solution you'd like to see (optional)
Let's switch Calypso's External Media feature to using a load more button instead of infinite scroll.

**Comment by youbrokesomething** [comment]
I believe this was completed. I see a load more button for Pexpels images in the standard image block.
