### ISSUE TITLE
Home: update e2e tests to break less on branch runs

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#42910]
As seen in https://github.com/Automattic/wp-calypso/pull/42808 sometimes checking if the site setup list is available will timeout on branch runs. Let's reduce the number of false positives by seeing if we can speed up the page helper dismiss of the celebration banner. 

Looking at runs locally this takes a few seconds.

https://github.com/Automattic/wp-calypso/blob/973da99acee7c8fea3e41a56515c3ea2af568ce6/test/e2e/lib/pages/my-home-page.js#L31-L37

PCYsg-o8X-p2 in case folks don't have a local env setup.

cc @bsessions85  if you had any tips here

**Comment by obenland** [comment]
@bsessions85 It's been a while since this was first opened, wondering if you had any tips on this one anyway?

**Comment by bsessions85** [comment]
@obenland, I think the easiest way to take care of this is to shorten the timeout on the `isElementPresent` step. The default timeout is 20 seconds. I would think we could easily cut that down to 10 or even 5 seconds.

**Comment by autumnfjeld** [comment]
Flakey e2e tests have been removed, so closing this.
