### ISSUE TITLE
Refactor Template API to move logic to a Template_Helpers class

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#42914]
Refactor the Template APIs to move the logic to a Template_Helpers class

Broad objectives:

1. Move shared logic out of endpoints and into a helper class
2. Remove inheritance between the three template API endpoints (defaults, mix, and demo)
3. Add test coverage for these endpoints

D44140-code

**Comment by ramonjd** [comment]
Just creating us some more work :) 

Will D44140-code address the issue below, or should I create a new task?

> The sites/new endpoint is making a remote request to the Template Mill API endpoint. This seems like an unnecessary network request. If the logic for that endpoint largely lived in a helper class, we could call the helper class here instead of making another API request. This would help remove dependencies between API endpoints.

**Comment by andrewserong** [comment]
@ramonjd let's create a new task. The existing diff will add the helper class, then it can be a smaller diff to see about re-using it in the `sites/new` endpoint.

**Comment by andrewserong** [comment]
D44140-code is ready for review now :)

**Comment by andrewserong** [comment]
Deployed :)
