### ISSUE TITLE
Navigation: page title is nonexistent on page reload (small viewports)

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4292]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/insights/testsite.wordpress.com
2. Change viewport width to ~425px
3. Click on back arrow
4. Click Themes
5. Reload the page
6. Page title is now gone (see screenshot)

#### What happened

For some reason, the page title is not being inserted into the back navigation bar, causing a visual bug. This is also not specific to Themes and Stats. It also happens with other combinations of views.

#### Browser / OS version
Chrome 49, 425px viewport width
Mac OS X 10.11.2

#### Screenshot / Video
![screen shot 2016-03-23 at 4 53 04 pm](https://cloud.githubusercontent.com/assets/618551/14020359/c6f73c14-f1a4-11e5-8da8-a286cd473cc0.png)

**Comment by lancewillett** [comment]
Re-testing this today: the title is still missing after the reload, using exact steps above. But, the layout doesn't break as much — so it seems minor to me.

<img width="437" alt="screen shot 2016-04-28 at 4 32 25 pm" src="https://cloud.githubusercontent.com/assets/66797/14904688/cef81c96-0d5e-11e6-8978-c3c12b805117.png">

**Comment by hoverduck** [comment]
#bug-scrub

Closing, looks like it's fixed (tested in OSX Chrome v51)
