### ISSUE TITLE
Gutenboarding: introduce a reassuring message if people hesitate to enter a title

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42943]
In usability testing sessions we've seen some people hesitate when thinking of a name if they don't already have something in mind. 

We have a clear 'i don't know' button, but if we find someone hesitating we should reassure them that they can either skip or change their name later.

Could we try a help message that fades in after a couple of moments of hesitation? This would keep the UI clean for customers with something already in mind, but provide reassurance to folks that may not be sure. 

Edit: context in pbAok1-11X-p2

**Comment by razvanpapadopol** [comment]
Is that bulb icon something we already have or it is going into Gutenberg soon? Last mention I've found is here: https://github.com/WordPress/gutenberg/issues/20284#issuecomment-596103306

**Comment by simison** [comment]
In Gutenberg it's here:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/87168/84652884-0e75da00-af15-11ea-8cc7-42bc3cf5c240.png">

So eventually [it'll be in icon library](https://github.com/WordPress/gutenberg/tree/12ebd7c80b2c48183d634d87578ac554f73a47a6/packages/icons/src/library), unless it's already there and I just didn't see it.

OK to PR a moval of that SVG into that library but meanwhile we anyway need to rely on SVG directly.

**Comment by simison** [comment]
The nudge could also disappear once user starts typing something.

**Comment by yansern** [comment]
> So eventually it'll be in @wordpress/icons library, unless it's already there and I just didn't see it.

Not there as of now, will be extracting the SVG icon directly from [packages/components/src/tip/index.js](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/tip/index.js).
