### ISSUE TITLE
Gutenboarding: plans grid—make comparison table's header sticky

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42945]
In a testing session today the participant was the first person to scroll down and find the comparison table. 

We've already discussed having the table expanded all the time, but in addition to that, it would be helpful if the table's header was sticky so you could easily reference which plan to associate each checkmark with.

**Comment by klimeryk** [comment]
Alternatively, we could mimic what the https://wordpress.com/pricing/ page does and duplicate the plan names for each section:

<img width="1415" alt="Screenshot 2020-08-03 at 18 52 48" src="https://user-images.githubusercontent.com/3392497/89216802-9b0a5380-d5ba-11ea-8e9a-459c5c01b4c5.png">

Looks like there's already space for it in the section headers:
<img width="1274" alt="Screenshot 2020-08-03 at 18 53 10" src="https://user-images.githubusercontent.com/3392497/89216836-a78eac00-d5ba-11ea-9c51-fb9adc175c04.png">

**Comment by ollierozdarz** [comment]
I believe there are some tests happening in this space at the moment from MarTech, especially around putting the comparison table into an expandable area since we now have an inline features table on each plan.
