### ISSUE TITLE
Welcome tour: horizontal scrollbars within tour modal

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42946]
Noticed during a testing session today—after the latest gutenberg update there are display issues with the modal tour. 

This is likely due to the [updated vertically aligned tour in core](https://github.com/WordPress/gutenberg/pull/21847). 

We should reconfigure our tour to use the new layout.

**Comment by yansern** [comment]
A screenshot of how broken it looks on Gutenboarding.
![image](https://user-images.githubusercontent.com/1287077/83731787-60804b00-a64b-11ea-98ee-16306e5fffbe.png)

A screenshot of how the updated welcome guide looks like.
![image](https://user-images.githubusercontent.com/1287077/83731806-67a75900-a64b-11ea-9123-cb515e6acfd3.png)
