### ISSUE TITLE
Domains: allow purchasing domains with an unverified email

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#42949]
We allow customers to purchase domains during onboarding, it's confusing that the domain search is blocked after signup until you've verified your email. 

In our onboarding usability tests this has been somewhat confusing for several participants. 

Can we consider removing this restriction?

**Comment by klimeryk** [comment]
Do I remember correctly that this was being discussed somewhere on a P2? I know there might have been some concerns from fraud point of view in the past, but if we allow users to create new sites with unverified emails now, it might be moot. Still, would be good to make sure Fraud Squad is OK with this change.

BTW, @rickybanister, please remember to add appropriate labels to issues you report - otherwise the reponsible teams don't get pinged (either through Slack, like we do for the Domains label or if they're using a GitHub project) 🙏 🙇‍♂️

**Comment by tanjoymor** [comment]
Just to add a thought for consideration on this. If we allow customers to register a domain before they've verified their email address, then we open up the possibility of customers making purchases on an account that was setup with a typo in the email address, that they can't get back to - as is the case here: #3014265-zd. This can make for a frustrating customer experience (as they aren't likely to know they had a typo at the time of account creation) and a challenging situation for our support to be able to resolve. Thanks for considering this 😊

**Comment by klimeryk** [comment]
Thanks for sharing that valuable example, @tanjoymor! If we go ahead with this, we have to make sure cases like that are handled properly - ideally, within our Account Recovery flows _without_ the need to contact Happiness Engineers 🙏

**Comment by tanjoymor** [comment]
Just an update on this - I've run into 2 more cases of this situation in the last week myself. No idea how much of a wide spread issue it's been or if I'm just really lucky. 😊

**Comment by rickybanister** [comment]
@tanjoymor just so I fully understand, the tickets you've seen are from customers that purchased a domain during signup, but had a typo in their email?

Something like 95% of our domain sales happen during signup, when we do not yet require verification. If we open up that last 5% of post-signup domain sales, will that make things meaningfully worse?

**Comment by klimeryk** [comment]
Proposed a more data-informed decision in p99Zz8-1i6-p2 to alleviate concerns from both sides.

**Comment by tanjoymor** [comment]
@rickybanister Yes, that’s correct - new accounts with a typo in the email. I’ve posted a more thorough response on the P2 @klimeryk posted.

**Comment by klimeryk** [comment]
Thank you for your insightful comment on the P2, @tanjoymor! Based on it, I'd say the root fix here would be to improve the onboarding experience instead - either make email verification a required step to sign up or at least emphasize the importance of inputting a valid email address (add some validation for typos like `@gmial.com`, etc.).

As such, I'll close this as a wontfix, but I'll be raising this in p99Zz8-1BJ-p2 where I'm exploring gaps in our domains-related flows.

**Comment by simison** [comment]
>I'd say the root fix here would be to improve the onboarding experience instead - either make email verification a required step to sign up or at least emphasize the importance of inputting a valid email addres

@klimeryk I don't think that's gonna change; something as technical as email verification in a signup to block them from progressing isn't gonna fly well for completion/conversion rates. I agree it would alleviate issues some customers face & lower n number of support requests, but it's a tradeoff we've so far done and deemed worth it.

I also agree improving catching typos with common domains.

I think this issue still stands true, until the above is actually sorted (martech team is best to start that convo with).

> We allow customers to purchase domains during onboarding, it's confusing that the domain search is blocked after signup until you've verified your email.

Note that it's the domain _search_ that's blocked, so you can't even search anything, separately from actually registering a domain.
