### ISSUE TITLE
Gutenboarding: extract reusable UI components and styles to packages

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#42950]
When extracting [PlansGrid](https://github.com/Automattic/wp-calypso/pull/42764) and [DomainPicker](https://github.com/Automattic/wp-calypso/pull/42409) into separate packages we ended up duplicating a lot of Gutenboarding components (title, subtitle, action buttons) and SCSS variables and mixins. We should come up with a solution to reuse these (eg: move components to `@automattic/components`).

Mentioned in:
https://github.com/Automattic/wp-calypso/pull/42764#discussion_r432414020
https://github.com/Automattic/wp-calypso/pull/42764#discussion_r432414547

**Comment by simison** [comment]
Just quick FYI: let’s not worry about extracting Badge component now anywhere, it might go away in next design-iteration.

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/44077
