### ISSUE TITLE
No required option for checkboxes in the Form Block

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#42956]
When making a form with the Form block, there is no option to make a checkbox field required like the other blocks. Tested on simple and AT sites. 

Gutenberg: 8.2.1
CoBlocks: 1.23.0
wpcom-FSE: 118961016

![Markup 2020-06-03 at 11 49 05](https://user-images.githubusercontent.com/41035049/83678409-901f4c80-a592-11ea-9eec-cf2e25ed8f33.png)

**Workaround**: If I use the HTML editor, I can add code to make the field required, like this:

`<!-- wp:jetpack/field-checkbox {"label":"Click here for more information.","required":true} /-->`

That ends up adding the checkbox as a required field:

![Markup on 2020-06-03 at 12:10:08](https://user-images.githubusercontent.com/41035049/83678835-38351580-a593-11ea-8097-231384bd831a.png)

**Comment by jeherve** [comment]
This was fixed in https://github.com/Automattic/jetpack/pull/16162/. The fix is already available to WordPress.com Simple sites, and will be available on Atomic and Jetpack sites on July 7.
