### ISSUE TITLE
Coming Soon & Private on Atomic: Backups not visible in Activity Log

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#42960]
### HEs, please see the workaround notes at the bottom of this report and report interactions in a comment.

Private and coming soon mode prevents users from seeing recent Jetpack backups in the Activity log. 

See internal comments at paObgF-Ui-p2#comment-2281

When in private/coming soon it appears that this is either extremely delayed or something prevents the backups from being visible and usable. The Jetpack backups will be available in VaulPress MC but not appear under Activity & Backups.

If a backup is visible, from when the site is public, the download will not work properly and render an `Invalid download URL` message. That is reported on #42962 

It appears the mode 403s Jetpack backups access to the log with:

` Failed to push rewind_backup_complete event to Activity Log. { message: '403 - {"code":"unauthorized","message":"User cannot access this private blog.","data":{"status":403}}', name: 'StatusCodeError', statusCode: 403, error: { code: 'unauthorized', message: 'User cannot access this private blog.', data: { status: 403 } }
`
#### Steps to reproduce

1. Starting at URL: WordPress.com with an Atomic site selected
2. Ensure the site is set to Private or Coming Soon under Manage > Settings
3. Go to My Site > Tools > Activity & Backups
4. Backups made during the time the site is Private or Coming Soon are not visible.

#### What I expected

Users should see recent Jetpack backups under My Site > Tools > Activity & Backups.

#### What happened instead

Backups made during the time the site is Private or Coming Soon are not visible.

#### Context / Source

#dogfooding 
#user-report 

See internal comments at paObgF-Ui-p2#comment-2281

#### HE Workaround Notes

Generally, the site will have backups available but they will not be visible or accessible in the activity log.  You can check to see it is making backups using our internal debugging tools.

To restore a backup not visible, you will need to open a JPOP issue. 

 To see new backups, the site must be made public. You can queue a new backup using our internal rewind debugging tool. Previous backups made while in private/coming soon will not be visible in the activity log. 

Please see the following for more details about these workarounds.  p7DVsv-8Ue-p2

**Comment by JoshuaGoode** [comment]
This report has been filed alongside other issues I've identified with Coming Soon & Private:

https://github.com/Automattic/wp-calypso/issues/42966
https://github.com/Automattic/wp-calypso/issues/42965
https://github.com/Automattic/wp-calypso/issues/42964
https://github.com/Automattic/wp-calypso/issues/42962
https://github.com/Automattic/wp-calypso/issues/42960

**Comment by JoshuaGoode** [comment]
While we get daily user reports about this, we haven't been logging them.

Here's one: 3073120-zen

Related P2 about this interaction: p9F6qB-5qy-p2

**Comment by mlaetitia** [comment]
One more report: -22141230hc

NOte that there isn't a workaround at the moment. If a user wants to rewind to a date when they had coming soon mode active (or the site wasn't launched yet) - they can't.

**Comment by mriyazuddin** [comment]
One more here: #3064961

**Comment by automattic-ian** [comment]
another report in #3089891-zen

**Comment by selectedselections** [comment]
Another issue with this in #3089891-zen

User needs a back up but their site is in Coming Soon mode and no back ups are in the activity log

**Comment by joweber123** [comment]
Another report of this here 22152719-hc

**Comment by edwinho89** [comment]
#22193349-hc

**Comment by vinnykaur** [comment]
One more: #22193825-hc

**Comment by cecilearkay** [comment]
It was also reported in 22205905-hc

**Comment by allykmyta** [comment]
It was also reported in 22207562-hc

**Comment by mikeicode** [comment]
Also 21494618-hc

**Comment by JoshuaGoode** [comment]
Adding workaround notes:

Generally, the site will have backups available but they will not be visible or accessible in the activity log. You can check to see it is making backups using our internal rewind debugging tool.

To restore a backup not visible, you will need to open a JPOP issue.

To see new backups, the site must be made public. You can queue a new backup using our internal rewind debugging tool. Previous backups made while in private/coming soon will not be visible in the activity log.

Please see the following for more details about these workarounds. p7DVsv-8Ue-p2

**Comment by formosattic** [comment]
Also 21218608-hc

**Comment by dcoleonline** [comment]
I ran into it after helping in 22259330-hc today

**Comment by CompChris** [comment]
16386362-hc - Trying to download a backup. After made public, they were able to.

**Comment by gwensmithx** [comment]
Here too: 22294470-hc Customer is just making sure their backups are running (they are) but they can't see them in Coming Soon mode.

**Comment by hacchism** [comment]
Also 22556502-hc

**Comment by krutidugade** [comment]
Another here - 22575463-hc

**Comment by mikeicode** [comment]
Another 22613236-hc

**Comment by mikeicode** [comment]
Another 22333931-hc

**Comment by eoinsav** [comment]
Another: 22698454-hc

**Comment by mikeicode** [comment]
Another 22710211-hc

**Comment by ktyfuller604** [comment]
Another: [3154343-zen](https://woothemes.zendesk.com/agent/tickets/3154343)

**Comment by vinnykaur** [comment]
One more: 22696508-hc

**Comment by brookewp** [comment]
Another: 22761561-hc

**Comment by roo2** [comment]
Adam had an idea for a possible straightforward fix paObgF-Ui-p2#comment-2282

**Comment by edwinho89** [comment]
One more: 3141518-zen

**Comment by Gilmoursa** [comment]
another one: 22583138-hc

**Comment by gwensmithx** [comment]
another one: 3177732-zen and 22949450-hc

**Comment by edwinho89** [comment]
#22957685-hc

**Comment by dcoleonline** [comment]
#23055886-hc

**Comment by philnick206** [comment]
23086066-hc

**Comment by vinnykaur** [comment]
23029416-hc

**Comment by dhackneya8c** [comment]
22585593-hc

**Comment by mriyazuddin** [comment]
#3214023-zen

**Comment by roo2** [comment]
This should be fixed now, for new site backups (fixed by D47231-code)
