### ISSUE TITLE
Coming Soon & Private on Atomic: Jetpack backups/rewind 403 Issues

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#42964]
403 errors are present in our internal debugging tool for Jetpack backups/rewind when an Atomic site is set to Private or Coming Soon mode. 

Discussed here: paObgF-Ui-p2#comment-2281

Related notes on paObgF-Ui-p2#comment-2282

#### Steps to reproduce

1. Starting at URL: Select a WordPress.com Atomic site in Calypso, make sure it is set to Private or Coming Soon under Manage > Settings
2. Visit the internal backups/rewind debugger for an Atomic WordPress.com site
3. Review 403 errors present

Example:
> error: Error from wpcom request for /sites/177795490/rewind/capabilities: StatusCodeError: 403 - {"code":"unauthorized","message":"User cannot access this private blog.","data":{"status":403}}

#### What I expected

No 403 errors to be present
#dogfooding #user-report

**Comment by JoshuaGoode** [comment]
This report has been filed alongside other issues I've identified with Coming Soon & Private:

https://github.com/Automattic/wp-calypso/issues/42966
https://github.com/Automattic/wp-calypso/issues/42965
https://github.com/Automattic/wp-calypso/issues/42964
https://github.com/Automattic/wp-calypso/issues/42962
https://github.com/Automattic/wp-calypso/issues/42960

**Comment by roo2** [comment]
this will be fixed with #42960

**Comment by roo2** [comment]
fixed now by D47231-code
