### ISSUE TITLE
Coming Soon & Private on Atomic: Cannot download Jetpack backups

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#42962]
While in Coming Soon or Private mode on Atomic, Jetpack backups cannot be downloaded. 

When you attempt to download a backup via My Site > Tools > Activity & Backups, a file is fetched  here’s an example from my test site `https://public-api.wordpress.com/wpcom/v2/sites/177795490/rewind/downloads/252344/data?token=yZok6kxnXEcYrTmMp9xwRiiiQ6JjhmZv7t8A5XN0fL8rp26CWjmic4xUkAkfsAIw`

A related issue is that backups made while in Coming Soon or Private mode do not appear in the activity log.  If the site was public at some point, backups may be visible; however, they cannot be downloaded if the site is back in Coming Soon or Private mode.

Related: #42960 

See internal comments at paObgF-Ui-p2#comment-2281

Notes from @adamziel 

> When the site is private, the get_vp_site used in vaultpress API returns false. This in turn breaks the rewind download public-api endpoint. This is pretty interesting – we’ve been testing downloading backups before this feature was launched and it did not break like that.

- paObgF-Ui-p2#comment-2290

#### Steps to reproduce

1. Starting at URL: WordPress.com with an Atomic site selected.
2. Ensure the site is in Private or Coming Soon mode under Manage > Settings
3. Go to My Site > Tools > Activity & Backups
4. Select a backup to download, wait for it to generate, click the Download button.
5. See Invalid download URL message

#### What I expected

To be able to download a backup.

#### What happened instead

Met with an Invalid URL error message.

#### Context / Source

#dogfooding #user-report

See internal comments on paObgF-Ui-p2#comment-2281

**Comment by JoshuaGoode** [comment]
This report has been filed alongside other issues I've identified with Coming Soon & Private:

https://github.com/Automattic/wp-calypso/issues/42966
https://github.com/Automattic/wp-calypso/issues/42965
https://github.com/Automattic/wp-calypso/issues/42964
https://github.com/Automattic/wp-calypso/issues/42962
https://github.com/Automattic/wp-calypso/issues/42960

**Comment by roo2** [comment]
now fixed by D47231-code
