### ISSUE TITLE
Coming Soon & Private on Atomic: API calls to this blog have been disabled even after site has gone Public

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#42965]
Even after a site goes Public, it seems that the site may not be able to accept normal API calls.

See internal report: paObgF-Ui-p2#comment-2281

Also, see additional notes/findings: paObgF-Ui-p2#comment-2287

---

Basic API calls initiated by an authorized user or tool are sometimes responded with the following message.

> {"error":"unauthorized","message":"API calls to this blog have been disabled."}

An example call would be https://public-api.wordpress.com/rest/v1/sites/177795490 which is one I performed when debugging sites and is part of the [Jetpack Debugger]( https://jetpack.com/support/debug/)'s simple API output check

When the site is public and the user is authorized, it should return 200 with something like the following.

> {
    "ID": EXAMPLE_ID,
    "name": "GoodeShop",
    "description": "Just another WordPress site",
    "URL": "https:\/\/EXAMPLE_DOMAIN",
    "jetpack": true,
    "subscribers_count": 1,
    "logo": {
        "id": 0,
        "sizes": [],
        "url": ""
    },
    "is_following": false,
    "meta": {
        "links": {
            "self": "https:\/\/public-api.wordpress.com\/rest\/v1\/sites\/154474651",
            "help": "https:\/\/public-api.wordpress.com\/rest\/v1\/sites\/154474651\/help",
            "posts": "https:\/\/public-api.wordpress.com\/rest\/v1\/sites\/154474651\/posts\/",
            "comments": "https:\/\/public-api.wordpress.com\/rest\/v1\/sites\/EXAMPLE_ID\/comments\/",
            "xmlrpc": "https:\/\/EXAMPLE_DOMAIN\/xmlrpc.php"
        }
    },
    "launch_status": "",
}.

#### Context / Source

#dogfooding
#user-report

**Comment by JoshuaGoode** [comment]
This report has been filed alongside other issues I've identified with Coming Soon & Private:

https://github.com/Automattic/wp-calypso/issues/42966
https://github.com/Automattic/wp-calypso/issues/42965
https://github.com/Automattic/wp-calypso/issues/42964
https://github.com/Automattic/wp-calypso/issues/42962
https://github.com/Automattic/wp-calypso/issues/42960

**Comment by roo2** [comment]
It looks like Adam had a strong insight on the source of this paObgF-Ui-p2#comment-2287

> The issue is likely that [the json-api] module is not being re-enabled once the site goes public.

**Comment by mattwiebe** [comment]
This needs further investigation to see if it's still an ongoing issue, but I am guessing that it is.

**Comment by p-jackson** [comment]
Re-tested and confirmed that new Coming Soon sites do not have this issue. When calling the `/sites/$id` API endpoint, it now returns a valid response regardless of whether the site is Coming Soon or "Launched".

Existing Coming Soon sites (like `siteId=177795490` mentioned in the description) the user would need to switch off Coming Soon mode and then re-enable it in order to migrate to the new behaviour for Coming Soon sites.
