### ISSUE TITLE
Coming Soon & Private on Atomic: Plugin and theme API calls + demo imports broken

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#42966]
While an Atomic site is in Coming Soon or Private mode, many plugins and third-party themes cannot utilize the REST API properly nor can they utilize demo import files.

Internal notes for a specific example: p58i-8OX-p2#comment-46472
An example of this is with the third-party [Brooklyn theme](https://href.li/?https://themeforest.net/item/brooklyn-responsive-multipurpose-wordpress-theme/6221179)

The theme provides the user with demo XML files that are stored in the site's uploads folder (ie /wp-content/uploads/2020/06/demo_fortytwo.xml).

When attempting to use the theme's demo import tool, you will see the error `Could not open the file for parsing`

The import script will return the following error
> PHP Warning:  XMLReader::open(): Unable to open source data in /srv/htdocs/wp-content/themes/brooklyn/unite/core/admin/option-tree/includes/plugins/importer-reloaded/class-wxr-importer.php on line 130

Another example would be Elemento Pro or the [Bridge](https://themeforest.net/item/bridge-creative-multipurpose-wordpress-theme/7315054) theme which requires the REST API to be working like normal for certain functions and importing tools to work. 

This requires users to launch their sites, make them public, and use a third-party Coming Soon plugin which does not put such restrictions in place.  

#### What I expected

For Coming Soon mode not to lock down the site in such a way that it cannot use third-party themes and plugins that rely on the REST API or uploaded files.

#### Context / Source

Various #user-reports since the launch of Coming Soon mode, #dogfooding, and p58i-8OX-p2#comment-46472

**Comment by JoshuaGoode** [comment]
This report has been filed alongside other issues I've identified with Coming Soon & Private:

https://github.com/Automattic/wp-calypso/issues/42966
https://github.com/Automattic/wp-calypso/issues/42965
https://github.com/Automattic/wp-calypso/issues/42964
https://github.com/Automattic/wp-calypso/issues/42962
https://github.com/Automattic/wp-calypso/issues/42960

**Comment by dcoleonline** [comment]
These modes also break the ability for Instagram connections to show content using the Latest Instagram Posts block. I encountered this in 21960418-hc where I had to enable a third party coming soon plugin and set the site to public. This was the only way to get the Instagram connection to work.

**Comment by katiebethbrown** [comment]
Issue with the Instagram connection in #22769316-hc as well.

**Comment by chaitanyamsv** [comment]
Another issue reported with Latest Instagram Posts block in 23319930-hc

**Comment by chaitanyamsv** [comment]
Another report in 23104287-hc

**Comment by thesacredpath** [comment]
Issue reported here also for Paid Membership Pro plugin - could not activate: 22388746-hc

**Comment by mattwiebe** [comment]
Essentially it appears that Private mode breaks a lot of expected functionality for Atomic users. Since they start out in that state, they may conclude that Atomic doesn't work. They arrive in this flow by indicating that they want to use some 3rd party theme or plugin, many of which will break, rendering Atomic seemingly unusable.

This needs to be explored to see if it's still an ongoing problem.

**Comment by chaitanyamsv** [comment]
25045559-hc

**Comment by cathymcbride** [comment]
Lowering Pri b/c this should be fixed by the recent work on this feature, which should be hitting production soon.

**Comment by p-jackson** [comment]
I haven't tested this with the Brooklyn theme (it's a paid theme), but new Coming Soon atomic sites have changed so that the `/wp-content/uploads` folder is now publicly accessible. If there is an existing Coming Soon site where this is still an issue then it will need to migrate to the new behaviour by disabling coming soon mode and then re-enabling it.
