### ISSUE TITLE
Custom HTML Block: Copy/Paste from one block into another only selects entire contents

### ISSUE THREAD

**Issue by smithkyle45** [Automattic/wp-calypso#42998]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/home/
2. Create or edit any page or post (to enter the editor)
3. Add two Custom HTML blocks, input some HTML into both
4. Try to copy a piece of the HTML from either block
5. Paste the HTML into one of the Custom HTML blocks

#### What I expected
I was expecting to be able to paste one line of HTML from one block into another. 

#### What happened instead
It appears to select the entire contents of the Custom HTML block, wrapped by the following: 

```
<!-- wp:html --><!-- /wp:html --> 
```

#### Browser / OS version
Chrome 83.0.4103.61
macOS Catalina 10.15.5

#### Screenshot / Video
Screen recording: https://d.pr/v/bWhFsd/fM8zTS45X4

#### Context / Source

A user reported this to me in live chat. They normally write poems/prose with custom HTML blocks and noted that they were able to copy/paste in this style up until a few weeks ago. 

#user-report in 14727191-hc.

**Comment by zdenys** [comment]
I noticed the same thing when I was troubleshooting a user case. The block should indeed only copy the selected part of the text, not the entire content of the block.

**Comment by zdenys** [comment]
Just noting that it happens for the Shortcode Block as well https://github.com/Automattic/wp-calypso/issues/43264

**Comment by simison** [comment]
This might be fixed in Gutenberg 8.3 with https://github.com/WordPress/gutenberg/pull/22793

**Comment by razvanpapadopol** [comment]
I can confirm this has been fixed in Gutenberg 8.3 so now should be fixed on wpcom.
Here's a demo where I was copying a single line, the whole block and then two lines of HTML: https://cloudup.com/cZtadhxgwnvmmmm
