### ISSUE TITLE
Site Settings: in General Settings, tagline text disappears when I unfocus the tagline field

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#43]
* URL: https://wordpress.com/settings/general/multilingualwp.wordpress.com
* Goal: I am trying to enter a tagline for the new site
* What I expect: I type the tagline, then maybe fiddle with some features, and ultimately hit "Save" and the tagline is changed
* What happens: I enter the tagline, change focus from the tagline field, and the tagline disappears

GIF of the action!

![](https://cloud.githubusercontent.com/assets/233434/8605515/c12350e0-267d-11e5-8f89-90cbe073247e.gif)

This is likely the same problem as #40 and #42 

A few notes:

In some of my tests, it takes quite a bit longer, but I can consistently reproduce this
I don't have to change focus to lose the text
All text fields will "update" back to what they were when I loaded the page
It resets when automatically reloading a network resource
This happens periodically (see green dots in timeline), so to duplicate it you may need to wait
The fields reset when this loads:
https://public-api.wordpress.com/rest/v1.1/notifications/?http_envelope=1&fields=id%2Cnote_hash&number=10

Initiated by: 
https://s0.wp.com/_static/??/wp-includes/js/jquery/jquery.js,/wp-content/js/postmessage.js?m=1377267974j

**Comment by gwwar** [comment]
SitesList periodically updates via the /me/sites endpoint and triggers a rerender in site settings, even if the user has unsaved changes. This affects all setting fields, not just the tagline.
