### ISSUE TITLE
Reader: followed sites sidebar showing unencoded entities

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#43025]
@southp noticed that the Reader is not encoding apostrophes and other html entities in the collapsible sidebar:

<img width="285" alt="Screen Shot 2020-06-05 at 12 18 55 PM" src="https://user-images.githubusercontent.com/437258/83899638-c988c100-a726-11ea-9571-52b8b2033fc3.png">

Also, descending letters are being clipped off.

**Comment by unDemian** [comment]
> noticed that the Reader is not encoding apostrophes and other html entities in the collapsible sidebar:

Should be fixed by D44640-code

**Comment by unDemian** [comment]
> Also, descending letters are being clipped off.

Should be fixed by #43097
