### ISSUE TITLE
READER: Expanded Following sidebar is very very very long

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#43027]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read
2. (Follow 2000 sites 😆 )
3. Expand the Followed Sites sidebar item
4. Scrooooooooooooooooolllllllllllll

#### What I expected

I'm not entirely sure. 

#### What happened instead

But I didn't expect to get a 2000 item list in my sidebar.

#### Browser / OS version

Any

#### Screenshot / Video

(the scrolling gif was 42MB so ... yeah)

#### Context / Source

This may not be a giant deal, we don't really have that many folks who follow 100+ sites. But for those that do, it's kind of a pain. Having an easy way to collapse the list after scrolling a bit would be nice.

**Comment by bluefuton** [comment]
+1.

We do have folks who follow a truly astonishing number of sites (one had 733,000) but we only use the first 2000 when constructing the following stream. See Support FAQ here: P5PDj3-4Mm-p2.

**Comment by unDemian** [comment]
@evilluendas ^

**Comment by rickybanister** [comment]
A sticky header would help you collapse the section.

**Comment by unDemian** [comment]
We didn't get the chance to focus on Reader improvements yet, hopefully that day will come soon.

**Comment by davemart-in** [comment]
This should be fixed now with the reader followed list on the right (with pagination).
