### ISSUE TITLE
Donation Block: Do not let Donation Plans display as an option under Recurring Payments or Premium Content Block

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43029]
This is blocked by https://github.com/Automattic/wp-calypso/issues/43030

When the donation block is implemented https://github.com/Automattic/wp-calypso/issues/42825 we may make a number of plans by default when it is inserted for the first time. Let's ensure that we have some way of not displaying subscription plans that were created by the donation block.

We're open to technical approaches on how this is done, but it's very likely we'll want to update the create endpoint to add an additional flag, and allow filtering on the fetch endpoint. Before diving into implementation we may want to write up a p2 post on options.

Two areas of interest may be:

https://github.com/Automattic/jetpack/blob/38bbcb7bbdd7da82d821cfb98751056d9eaf305e/_inc/lib/core-api/wpcom-endpoints/memberships.php

https://github.com/Automattic/jetpack/blob/38bbcb7bbdd7da82d821cfb98751056d9eaf305e/_inc/lib/core-api/wpcom-endpoints/memberships.php#L148

<img width="779" alt="Screen Shot 2020-06-05 at 10 58 07 AM" src="https://user-images.githubusercontent.com/1270189/83908214-912fb580-a71b-11ea-99d2-9680dd5c6d6b.png">

<img width="826" alt="Screen Shot 2020-06-05 at 11 00 21 AM" src="https://user-images.githubusercontent.com/1270189/83908348-d3f18d80-a71b-11ea-8cef-979d4ade698e.png">

**Comment by mmtr** [comment]
This was handled in D45052-code
