### ISSUE TITLE
Donation Block: Create subscriptions with good USD defaults on first insert [exploration]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43030]
When a user inserts a donation block for the first time we need to ensure that the backing subscription plans are created as well. Please be aware of requirements in https://github.com/Automattic/wp-calypso/issues/43029 we may need to pass extra information during create to filter donation subscription plans.

We're open to technical approaches on how this is done. Before diving into implementation let's write up a p2 post on options for how this is represented. For simplicity sake we were leaning toward 1 backing plan per price button, but other folks may want to argue for one plan per interval (one time, monthly, annual).

Other Reqiurements:
* We are defaulting to USD, with good defaults. This can be manually changed for each donation subscription. In the future we may consider centralizing this based on customer feedback. Providing defaults for other currencies is not in scope for this v1 (but we'll likely revisit).
* Editing plans in Gutenberg is not allowed. We both lack an update endpoint, and senarios are complex when we have existing subscribers on plans that we're modifying. We'll likely need to link out to Calypso.
* **Reuse Donation Subscriptions** – If multiple donation blocks are added, they will use the same set of subscriptions. However **please keep the technical implementation flexible**. A common future use case might be one donation block with USD currencies, and a different one offering CAD.
* **No Donation Subscription Leakage** - Other blocks like payments and premium content should not see donation plan blocks in the dropdown. 
Two areas of interest may be:

https://github.com/Automattic/jetpack/blob/38bbcb7bbdd7da82d821cfb98751056d9eaf305e/_inc/lib/core-api/wpcom-endpoints/memberships.php

https://github.com/Automattic/jetpack/blob/38bbcb7bbdd7da82d821cfb98751056d9eaf305e/_inc/lib/core-api/wpcom-endpoints/memberships.php#L148

![83331405-3225f880-a264-11ea-8ba5-fcb41385fcc0](https://user-images.githubusercontent.com/1270189/83908840-9b05e880-a71c-11ea-8271-fb35957ffaaa.png)

see also pbMlHh-hA-p2

**Comment by artpi** [comment]
One way of addressing this would be:

- Pass a parameter to the `get_status` endpoint https://github.com/Automattic/jetpack/blob/38bbcb7bbdd7da82d821cfb98751056d9eaf305e/_inc/lib/core-api/wpcom-endpoints/memberships.php#L148  - something like `?source=donation`
- in the code handling this in `get_memberships_settings_for_site` function, we could create default donation plans and mark them in the database as 'donation'
- In all status endpoints, we would mark these donation plans

**Comment by mmtr** [comment]
Published a P2 post with a proposal that's quite aligned with what @artpi suggested above: pbMlHh-kg-p2

**Comment by mmtr** [comment]
I guess we can close this one out
