### ISSUE TITLE
DevDocs: Plan Storage component not rendering in mobile screen width

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#4303]
#### Steps to reproduce
1. Navigate to https://wpcalypso.wordpress.com/devdocs/app-components
2. Search for Plan, or scroll down
3. Resize your browser to a mobile-friendly width

Also - the component doesn't load at any screen size when navigating directly to https://wpcalypso.wordpress.com/devdocs/app-components/plan-storage

#### What I expected
A mobile version of the component.

#### What happened instead
Invisible component

#### Screenshot / Video
![wp-calypso-plan-storage](https://cloud.githubusercontent.com/assets/7233112/14028840/1d6a9ab6-f1d5-11e5-836b-3b97b94091a2.gif)

**Comment by hoverduck** [comment]
Forgot to ping @gwwar, who added this file in this commit: https://github.com/Automattic/wp-calypso/commit/9b069e8607b61b6ac8c40d6b3da015ec22dbb885

**Comment by gwwar** [comment]
@hoverduck This is intended behavior <480, I'll update the rule to be specific to the media modal

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plan-storage/style.scss#L31

**Comment by hoverduck** [comment]
:+1:

**Comment by lancewillett** [comment]
Noting for posterity this was found with automated visual diff testing with AppliTools that @hoverduck set up to check the DevDocs visual page changes for every merge (every Calypso deploy, anyway).
