### ISSUE TITLE
YouTube & Vimeo Embed Block: Video width isn't respecting its setting in the editor

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#43047]
This seems to be WP.com specific issue. As you can see the width of the video is static, and it's not respecting the setting in the editor. On the front of the site, the videos appear as correctly. It doesn't seem to be theme-specific issue.

It might be the same for other video embeds. We'd like to ship patterns and layouts with some embed videos, but it won't look good with this :)

**WP.com**
![Frame 2](https://user-images.githubusercontent.com/908665/83947612-04b2ef00-a810-11ea-843c-bb49feb913c1.jpg)

**Local install**
![Frame 3](https://user-images.githubusercontent.com/908665/83947619-14cace80-a810-11ea-8b84-940f0fa0d3d1.jpg)

@ianstewart

**Comment by ianstewart** [comment]
> It might be the same for other video embeds.

It's true for Vimeo as well.

![image](https://user-images.githubusercontent.com/545779/84039534-fb886600-a966-11ea-8200-f6fe03a29fd6.png)

**Comment by ianstewart** [comment]
> It doesn't seem to be theme-specific issue.

Twenty Nineteen on WP.com …

![image](https://user-images.githubusercontent.com/545779/84039826-6e91dc80-a967-11ea-92a8-aeb577b82241.png)

Twenty Nineteen in a local install of WordPress …

![image](https://user-images.githubusercontent.com/545779/84040119-d9431800-a967-11ea-9077-285db280e274.png)

**Comment by ianstewart** [comment]
> We'd like to ship patterns and layouts with some embed videos, but it won't look good with this :)

It also looks "wrong" or "broken" for everyone right now. :)

**Comment by yansern** [comment]
This is happening because the embed block is rendered within a sandbox iframe where WP CSS classes are not available.

Inside the block editor:

![image](https://user-images.githubusercontent.com/1287077/84237388-9153fa80-aaf9-11ea-89d7-0a3047e73672.png)

On the page itself:

![image](https://user-images.githubusercontent.com/1287077/84237507-c2342f80-aaf9-11ea-92bb-8201bf09f26e.png)

**Comment by iamtakashi** [comment]
> here the actual rendered DOM tree looks more like body > div > span > iframe

I don't see the `span` in the test page in my local install. If I remove the `span` in the inspector the video shows up correctly. Why is the markup different in WP.com?

**Comment by yansern** [comment]
> I don't see the span in the test page in my local install. If I remove the span in the inspector the video shows up correctly. Why is the markup different in WP.com?

Oh it's great removing the span works for you. It didn't work for me initially but I'm gonna retest this.

**Comment by yansern** [comment]
WP version makes an API request to the [locally hosted WP](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-oembed-controller.php) which makes another API request directly to [YouTube OEmbed API](https://www.youtube.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJXKob-28KW4).

It returns this:
![image](https://user-images.githubusercontent.com/1287077/84397533-052bfb00-abff-11ea-81cf-c7332f2c51e5.png)

WPCOM version makes an API request via [requestEmbed()](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/sites/embeds/render/index.js) to Jetpack's [YouTube shortcode plugin](https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/youtube.php).

It returns this:
![image](https://user-images.githubusercontent.com/1287077/84398606-728c5b80-ac00-11ea-9c43-d9ecde1369f7.png)

The `<span class="embed-youtube">` tag is created in these [line of code](https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/youtube.php#L276-L278) and it has been there as far as the [first commit back in 2014](https://github.com/Automattic/jetpack/blob/d689334e6d0b1102ab016ff9e0aeb2d2107c579c/modules/shortcodes/youtube.php).

I can see a couple of ways to fix this:

1. **Remove the `<span class="embed-youtube">` tag from Jetpack.**
    - Reason for voting for this is that it is the quickest possible fix.
    - Reason for voting against this is because the span tag has been around since forever and we do not know if there are 3rd-party JS/CSS coming from templates/plugins that are relying on this `.embed-youtube` classname.

2. **Add the `<span>` selector in Gutenberg.**
    - Reason for voting for this is that it's also easy but it will take the next Gutenberg release to roll it in.
    - Reason for voting against this is that `<span>` tag is specific to WPCOM and isn't part of WP/Gutenberg Core. 

3. **Remove the `<span>` tag in [requestEmbed()](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/sites/embeds/render/index.js.)**
    - Reason for voting for this is that we know that this will only affects new YouTube embeds on new Gutenberg versions moving forward.
    - Reason for voting against this is that removing span tag from a html string could be:
       - As simple as performing string manipulation but potentially error-prone.
       - As tedious as parsing the html then remove the outer span element then convert it back to html string which is less error-prone but it feels rather overkill.

4. **Replace the Embed block from Gutenberg core during calypsofication and inject additional CSS in the iframe to support `<span> tag`.**
    - I do not know if this is entirely possible.

**Comment by simison** [comment]
@jeherve @kraftbj thoughts on this from Jetpack side?

**Comment by jeherve** [comment]
I like option 1, but...

> Reason for voting against this is because the span tag has been around since forever and we do not know if there are 3rd-party JS/CSS coming from templates/plugins that are relying on this .embed-youtube classname.

This worries me as well. It seems the CSS class was added in 2011 in r33252-wpcom. Looking through the wpcom codebase, it's still in use in various themes today; some of those themes are Automattic themes and services (such as notifications) and could consequently be updated, but others are for VIP sites so things could be more complicated to update.
Maybe an audit of all the places where this is used in the WordPress.com codebase would give you a better idea of why this is used, and what impact removing it would have?

**Comment by simison** [comment]
@jeherve are those themes modifying the shortcode output specifically, or also expecting it to work in Gutenberg content? What are your thoughts on ensuring `span` works for shortcode embed but is removed for Gutenberg blocks?

**Comment by jeherve** [comment]
> Are those themes modifying the shortcode output specifically, or also expecting it to work in Gutenberg content?

From what I can tell, all those implementations predate Gutenberg. OpenGrok can help you look at some examples. Maybe this would direct us towards option 3.

**Comment by yansern** [comment]
Some updates. I'm at this point leaning towards Option 3. 

I have initially mistaken where the embed response is parsed. It is not done by `requestEmbed/receiveEmbed` in Calypso repo, but rather by `gutenberg-wpcom` plugin on WPCOM. The function is `translateOEmbedApiRequest()` in `gutenberg-wpcom-embed`.

**Comment by yansern** [comment]
The phab patch for Option 3 can now be tested in D47189-code.

Video: https://www.screencast.com/t/vkBackf9uHP

**Comment by iamtakashi** [comment]
With the patch, the width setting for both videos from YouTube and Vimeo works perfectly 🎉 Thank you!!

![video-width](https://user-images.githubusercontent.com/908665/88833140-b98eda00-d1c9-11ea-876f-7912bd5f4f04.jpg)

**Comment by ockham** [comment]
Thanks @yansern, great sleuthing and [analysis](https://github.com/Automattic/wp-calypso/issues/43047#issuecomment-642705816) of potential solutions and their tradeoffs! :medal_sports:  

I think your fix is a viable solution. One open question for me is why is WP.com using the JP embeds endpoint/YT shortcode rat all, instead of using the oembed endpoint shipped with Core/Gutenberg? I dug a bit and found some rationale in D37364-code. It's not totally clear to me though why we need this (p7DVsv-7YN-p2#comment-26118 mentions the Instagram embed, but I don't quite get what the JP/WP/.com version/shortcode does different from the embeds endpoint in core). Maybe @mmtr or @kwight can shed some light on this :blush: 

Anyway, not a blocker :+1: Just wondering if we can later on peel back a few layers and remove them altogether :grimacing:

**Comment by mmtr** [comment]
> why is WP.com using the JP embeds endpoint/YT shortcode rat all, instead of using the oembed endpoint shipped with Core/Gutenberg?

This is to work around the lack of an oEmbed provider for Instagram in WP.com (see `wp-content/mu-plugins/shortcodes/instagram.php#77`). For some reason I'm unaware of, the Instagram oEmbed provider is replaced with a regular embed provider. 

If we can manage to keep the oEmber provider registered, we could get rid of all the code that redirects the oEmbeds requests to the embeds endpoints.

**Comment by ockham** [comment]
> This is to work around the lack of an oEmbed provider for Instagram in WP.com (see `wp-content/mu-plugins/shortcodes/instagram.php#77`). For some reason I'm unaware of, the Instagram oEmbed provider is replaced with a regular embed provider.
> 
> If we can manage to keep the oEmber provider registered, we could get rid of all the code that redirects the oEmbeds requests to the embeds endpoints.

Thanks for the reference! Trying to track this down :male_detective: 

This part of the code has last been changed in February of 2019 by @jeherve in D24268-code (which is the WP.com counterpart to https://github.com/Automattic/jetpack/pull/11329), but this was only to add support for Instagram TV (which, as the PR mentions, was at the time also [being added to Core](r44486-core)).

However, the WP.com embed handler (that overrides the Core one) predates that change. It seems to have been first introduced by r106418-wpcom; some background information is available in p3VP7A-AC-p2. I'll read up on that.

**Comment by jeherve** [comment]
Some more discussion on the Instagram embed, its removal, and the potential performance impact it may have, here:
- https://github.com/Automattic/jetpack/pull/11063
- https://vipsupportp2.wordpress.com/2019/01/02/instagram-deprecate-custom-embed-provider-and-associated-filter/

**Comment by roo2** [comment]
I deployed @yansern's fix and the width settings are working well in the editor, good job @yansern D47189-code
