### ISSUE TITLE
Gallery Block: Caption change in media library does not change caption in block

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#43055]
#### Steps to reproduce

1. Add an image to the Media library.
2. Add a caption to this image.
3. Add this image to a Gallery Block.
4. Go back to the Media library and change the caption on the image.

#### What I expected
I expected that if you change the caption within the media library, this would be reflected in the Gallery Block as well.

#### What happened instead
A change to the caption from within the Media Library has no effect on the caption inside of the block. 

#### Browser / OS version
Firefox/Mac Catalina

#### Screenshot / Video
![media_library](https://user-images.githubusercontent.com/24914028/84001058-ddd7f280-a9a0-11ea-86fa-ed6565664746.png)

#### Context / Source
21716204-hc
3041479-zen

**Comment by arunsathiya** [comment]
3374908-zen

**Comment by nerdysandy** [comment]
I can still replicate it. Removing the Stale label.

**Comment by scosgro** [comment]
Another report in 26170876-hc

**Comment by kriskarkoski** [comment]
I believe this is standard core behavior. The most-recent caption is stored in the library and will be added to a new gallery, but changes are not synced to allow a gallery to be customized. I would close this as working as expected.

**Comment by synora** [comment]
> The most-recent caption is stored in the library and will be added to a new gallery, but changes are not synced to allow a gallery to be customized.

I just ran a quick test of this and that's exactly how it works.
