### ISSUE TITLE
Jetpack Search: handle url input for sites with Search already installed.

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/wp-calypso#43053]
Revise the purchase flow for sites that have Search already installed.

**Comment by davipontesblog** [comment]
Hi @AnnaMag should this be moved to the Jetpack repo?

**Comment by AnnaMag** [comment]
@davipontesblog, no, the flow goes solely through Calypso. Atm it is lives in the `/client/jetpack-connect` folder.
