### ISSUE TITLE
Fix the "Logged Out View" title.

### ISSUE THREAD

**Issue by n3f** [Automattic/wp-calypso#43075]
![image](https://user-images.githubusercontent.com/6354169/84063603-24fcbe00-a976-11ea-99f3-28bce5e83e04.png)

We changed the name to "Non-subscriber View", but the title is still logged out view and can be seen in the gutenberg tree structure.

**Comment by dsas** [comment]
This was fixed in February by [Jetpack 22626](https://github.com/Automattic/jetpack/pull/22626)
