### ISSUE TITLE
Signup: move MLB flow to Calypso

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#431]
The current MLB signup flow is outside of Calypso

>The current MLB signup flow is outside of Calypso and it doesn’t look great. Let’s make it better :-)
[Look at] [Signup framework docs](../tree/master/client/signup/README.md) to make things easier.
> -- Original issue created by @nb

cc @scruffian

**Comment by lancewillett** [comment]
Closing as abandoned — feel free to re-open in the future if we revisit it.
