### ISSUE TITLE
Favicon loading results in many many 404s

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#43107]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read (staging)
2. Expand the Followed Sites sidebar item
3. Look in the console for 404s for $site.com/favicon.ico

#### What I expected
Us to load cached favicons from an a8c controlled host and only when we have one

#### What happened instead
We hotlinked the favicons and many fail to load

#### Browser / OS version
any

#### Screenshot / Video
<img width="699" alt="Screen Shot 2020-06-09 at 11 33 33 AM" src="https://user-images.githubusercontent.com/14350/84168442-67410080-aa45-11ea-8268-cca232b17fa0.png">

**Comment by bluefuton** [comment]
This also seems to slow down the loading of images elsewhere on the page, so avatars and post images in the main content take much longer than normal to appear.

**Comment by simison** [comment]
FYI @sgomes because performance.

**Comment by sgomes** [comment]
As far as I can tell, this should be fixed at the API level. The `Favicon` component is simply making use of `site.site_icon`, which is populated by an API call to `/rest/v1.2/read/following/mine`. This response comes back with the invalid favicon URL.

Calypso has no way of knowing the URL is invalid, so it tries to fetch it, leading to a 404.

**Comment by bluefuton** [comment]
I've explored one possible solution to this in D45035-code:

* Include a favicon check in our regular Feedbag crawl
* Store the result in Feedbag_Meta
* Only return a favicon URL from `/read/following/mine` if we've recently found one in our favicon check

Even with something like that implemented, I think it'd be smart to set sensible limits on the number of feeds shown in the sidebar to prevent thousands of favicon requests taking place (see  https://github.com/Automattic/wp-calypso/issues/43027).

**Comment by bluefuton** [comment]
I've also produced a shorter-term fix in D45259-code, which stops returning a guessed favicon location and only populates `site_icon` if a blavatar exists.

**Comment by bluefuton** [comment]
D45259-code has just shipped, and the endpoint no longer guesses at the favicon URL. It only returns a site icon if a blavatar is defined.

**Comment by unDemian** [comment]
@bluefuton thanks for looking into this, this was only affecting a12s and I didn't realize for users with lots of external sites it would cause performance issues if there is no favicon's in place.
