### ISSUE TITLE
Gutenboarding: the plans step's disabled continue button should have a tooltip or other affordance

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#43119]
I just ran through the flow again and on the plans page I felt as though the continue button didn't give me enough of a clue how to proceed. 

Could we add any further affordance like a tooltip that says 'select a plan to continue'? Could hovering the continue button highlight the plan select buttons? Any other ideas?

**Comment by razvanpapadopol** [comment]
Fixed by implementing the behaviour to select a plan to proceed
