### ISSUE TITLE
Editor: Tags TokenField doesn't blur correctly in Firefox

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4313]
Noticed this while testing #4220 but it's an issue in master as well.

#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/post (and pick a site)
2. Expand "Categories & Tags"
3. Click the tags field; add some tags or otherwise interact with it.  Note expansion of suggestions list for sites that already have some tags
4. Click onto another text field on the page.  (Clicking onto blank space seems to work fine.)

#### What I expected

The tags field should lose focus: the suggestions list should collapse and the blue border should go away.

#### What happened instead

The tags field keeps its focused appearance.

#### Browser / OS version

Firefox 42.0 (latest is 45.0; I would expect same behavior in latest)

OS X 10.10

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Confirmed with Firefox 46, OSX 10.11.4 and Windows 10.  Does not appear to be an issue in Chrome, IE, or Safari

Here's a recording of the issue.  Note that clicking inside the editor pane does not remove focus.  Clicking just above the Tags input field makes it look like the field is losing and regaining focus immediately.  Clicking higher up, closer to Categories, does cause it to successfully lose focus.

![wp-calypso-4313](https://cloud.githubusercontent.com/assets/7233112/15399662/91b185d0-1db6-11e6-8cf6-40d6b00f1454.gif)

**Comment by hoverduck** [comment]
Also, this only seems to be a problem on the Tags field.  Other token fields (like on the people invites page) don't have the problem.

**Comment by nylen** [comment]
> Clicking just above the Tags input field makes it look like the field is losing and regaining focus immediately.

This part in particular is not a bug - you're clicking on the "Tags" label which focuses the field.
