### ISSUE TITLE
Earn: localize Paid Newsletter support page

### ISSUE THREAD

**Issue by donlair** [Automattic/wp-calypso#43152]
As discussed in [43017](https://github.com/Automattic/wp-calypso/pull/43017), the Paid Newsletter card on the Earn page points users to a [support page](https://wordpress.com/support/paid-newsletters/) that is not yet localized.

The URL in the card is already wrapped by localizeUrl.

**Comment by emilyaudela** [comment]
This [doc](https://wordpress.com/support/paid-newsletters/) has been translated.
