### ISSUE TITLE
Earn: "New" pill on card titles displays oddly in non-English languages 

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#43158]
Noticed this as I was testing different languages and font compatibility:

<img width="1069" alt="Screen Shot 2020-06-10 at 4 02 45 PM" src="https://user-images.githubusercontent.com/2124984/84314810-b31fa280-ab36-11ea-9d47-9d58203aedb9.png">

1. In your user account settings, change your language to French (though it's probably happening with other languages as well)
2. Visit `/earn` and note the visual weirdness in the cards with the "New" labels

In English, the labels look like this, for reference:

<img width="1081" alt="Screen Shot 2020-06-10 at 4 25 34 PM" src="https://user-images.githubusercontent.com/2124984/84315046-127db280-ab37-11ea-81f1-fd21d629c177.png">

They still seem oddly distant from their respective titles, but don't break to a new line.

**Comment by Aurorum** [comment]
PR for this issue in #43894. :)
