### ISSUE TITLE
Payments: investigate if receipt makes sense

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43151]
As noted in p1591707228408900-slack-payments we've gotten a report that a receipt doesn't make sense. Let's dig into this instance, and if it's a general issue please break out a new issue and close this one out.

Much appreciated @artpi or someone from the @Automattic/earn can take a look for the initial triage.

**Comment by artpi** [comment]
Oh, the receipt does not make sense FOR SURE!
Here is a task to handle this:
https://github.com/Automattic/wp-calypso/issues/43183
