### ISSUE TITLE
Translation issues with increased font

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#43153]
#### Steps to reproduce

1. Set your account to "Português do Brasil" here: https://wordpress.com/me/account
2. Go back to My Sites/Meus Sites
3. Expand the Manage/Gerenciar menu

#### What I expected
To be able to see all options in the menu.

#### What happened instead
The Hosting Configuration menu gets cropped when translated:

![calypsomenu1](https://user-images.githubusercontent.com/16104522/84296966-32a37680-ab23-11ea-9399-dfd03b6f0309.png)

It gets worse with scroll active:

![calypsomenu2](https://user-images.githubusercontent.com/16104522/84296983-39ca8480-ab23-11ea-90aa-fc62d77b88ed.png)

I noticed that this started happening after the last changes in the font size for the menu, around June 3rd.

I wonder if we should try "fixing" that translation, or find a way to better fit them in there, since it probably happens with other languages.

#### Browser / OS version
OS X 10.15.5
Chrome 83.0.4103.97

#### Context / Source
#dogfooding

**Comment by davemart-in** [comment]
Yep, this should be fixable with some CSS. Adding to the Manage Design board.
