### ISSUE TITLE
My Home: Help icon is misaligned

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#43169]
On the "My Home" screen there's a new Get Help section in the right column. I noticed a small issue with the help icon; Its not quite centered in it's blue shape:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/191598/84331087-4cf74780-ab57-11ea-9d7d-02f6e848584c.png">

If I zoom in I can see that the space around the icon is _not_ equidistant to the edge of the blue circle shape. In the image below, the red highlights are all the same width:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/191598/84331175-87f97b00-ab57-11ea-9267-eca52cf307c0.png">

**Comment by sixhours** [comment]
Hmm, this looks centered to me in FF, Chrome, and Safari:

<img width="361" alt="Screen Shot 2020-06-18 at 1 01 21 PM" src="https://user-images.githubusercontent.com/2124984/85050269-d3b5b100-b163-11ea-942d-9bffb98d53d4.png">

It goes wonky at certain zoom levels, but not in a consistent way:

110%
<img width="392" alt="Screen Shot 2020-06-18 at 12 57 47 PM" src="https://user-images.githubusercontent.com/2124984/85050110-9ea95e80-b163-11ea-8bb6-c8cdb30e5c97.png">

80%
<img width="153" alt="Screen Shot 2020-06-18 at 12 57 37 PM" src="https://user-images.githubusercontent.com/2124984/85050111-9ea95e80-b163-11ea-8350-cd229c9595ea.png">

Fine at 200+%
<img width="604" alt="Screen Shot 2020-06-18 at 12 57 25 PM" src="https://user-images.githubusercontent.com/2124984/85050113-9f41f500-b163-11ea-94a5-f622287d5ad4.png">

I noticed we're sizing it to 25px square, when it's designed to be sharpest at 24px square. I'm going to adjust the size so it's displayed at its optimal size, but that doesn't solve the weirdness at different zoom levels.

**Comment by sixhours** [comment]
@shaunandrews LMK if #43448 addresses the off-center weirdness; I think using the size the icon was designed for with an even number might help; if not, which browser/version were you using?

**Comment by shaunandrews** [comment]
Strange enough it seems to be related to the viewport width. Here's a GIF showing it jump around as I resize my viewport:

![help-jig](https://user-images.githubusercontent.com/191598/85053326-4de83480-b168-11ea-9d6a-b31594a1b248.gif)

**Comment by lcollette** [comment]
@shaunandrews Has this issue been solved?

**Comment by shaunandrews** [comment]
> Has this issue been solved?

Nope, I'm still seeing it.

**Comment by shaunandrews** [comment]
And this is in Safari Version 13.1.1.

**Comment by sixhours** [comment]
Aha, I'm able to reproduce the side-to-side behavior in Safari 13.0.5. Will dive back into this and see if I can figure it out.
