### ISSUE TITLE
Picker: the sidebar picker could use some padding at the bottom

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4316]
In chrome, when I hover over an item, it displays the link destination in the bottom-left of the viewport. When I am using the site-picker in the sidebar, this means that the bottom item is effectively cut in half and isn't terribly legible. Even if the environment badge wasn't in place, this is effectively hiding the `Add New WordPress` option. It goes away when you hover over that option directly, but if you can't read it you really don't have much reason to hover over it directly.

![screen shot 2016-03-25 at 9 53 29 am](https://cloud.githubusercontent.com/assets/134044/14046488/dde91d72-f26f-11e5-8497-58894c3febca.png)

/cc @mtias @folletto for ideas to fix it.

**Comment by folletto** [comment]
That's a hard one. I'm not sure it's "fixable"... I mean, not without changing the approach entirely. Right now I'd rely on the fact that the user won't keep the mouse all the times there, and that if the sight goes down there it's clear there's something below. This might be better answered by some user tests tho.

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Confirmed this is still an issue, but I'm tagging it Low Priority for now

**Comment by lancewillett** [comment]
I vote to close as "works for me" and re-open it later if we want to iterate on the usability.
