### ISSUE TITLE
Plugin Update Gutenberg v8.3.0-rc1

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#43178]
We have installed an alpha version of Gutenberg v8.3.0-rc1 to edge sites for early feedback, early feedback and bugs will be tracked here.

Testing post: p7DVsv-8Oh-p2

### Process

* [x] Install version 8.3.0-rc.1. (D44703-code)
* [x] Activate version 8.3.0-rc.1. on edge sites (D44704-code)
* [x] Install version 8.3.0. (D44796-code)
* [x] Activate version 8.3.0 on edge sites. (D44797-code)
* [x] Activate 8.3.0 in production for all sites
     - [x] Prep diff (@WunderBart) (D45045-code)
     - [x] Commit/Deploy 
* [x] Atomic (p9o2xV-UC-p2)
* [x] Announce
     - [x] public (https://wordpress.com/blog/2020/06/18/block-editor-updates/)
     - [x] internal (p7DVsv-8Rd-p2)

### Testing

* Calypso E2E tests #43137
* [x] Teamcity tests (D44704-code)

### Bugs 🐛

* [x] E2E: Block inserter menu not opening on openBlockInserterAndSearch(). https://github.com/Automattic/wp-calypso/issues/43179
* (Not necessary for launch) Update default block categories for Automattic blocks. https://github.com/Automattic/wp-calypso/issues/43198

**Comment by sirreal** [comment]
Launched r209212-wpcom.
