### ISSUE TITLE
Spike(s) to experiment with creating block pattern templates from source post content

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#43174]
For context see: pbxlJb-en-p2

The task comprises `n` experiments to create working "block pattern templates" from source post content.

**"Block pattern template"** means a file that can be used to inject translated content dynamically. Content may be at first just text, but later we'll have to think about HTML attributes such as `src`, `alt` or `style`.

**Source post content** means any block HTML from a WordPress site.

The goal of each experiment is to:

1. Take a chunk of block markup
2. Parse its contents and identify translatable/swappable content areas
3. Save a "pattern file" that we can use to execute translation/content swapping.
4. Use that "pattern file" to render/output the original block markup with the translated/swapped content.

We can constrain the requirements to textnodes only, or simple text blocks, and swapping in translated content or `_()` only, but whichever technical path we play with should take into account the requirement of adding custom, translated content.

#### Outcomes

- [ ] Define and document the format for a block pattern template
- [ ] Instruct the technical direction of subsequent development for block patterns API/platform

**Comment by andrewserong** [comment]
Just jotting down my messy WIP that I'm hacking away at: D44780-code

**Comment by lsl** [comment]
Also, D44864-code

**Comment by lsl** [comment]
Closing out with [@andrewserong's post](https://wp.me/pbxlJb-fl),  [my follow up](https://wp.me/pbxlJb-fw) and [the MT](https://wp.me/pbAok1-16B).
