### ISSUE TITLE
Signup: Headstart: Publication theme fails to populate widgets in Sidebar Two

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#4318]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/newsite
2. Walk through the menus and choose the Publication theme (I chose Business and Services -> Communication)
3. Fill out any remaining forms to set up your account if not already logged in
4. Scroll down on the page and look for the Tags and Calendar widgets on the right

Tested with both a new and existing account.

#### What I expected
![image](https://cloud.githubusercontent.com/assets/7233112/14047870/e1bac016-f280-11e5-99a7-8e483076f1f5.png)

#### What happened instead
![image](https://cloud.githubusercontent.com/assets/7233112/14047872/e79b908c-f280-11e5-8a7d-25bb769a8e04.png)

#### Browser / OS version
Chrome v49.0.2623.87 (64-bit) on OSX
IE 11 on Windows 7

**Comment by kwight** [comment]
Well spotted – added a sidebar 2 text widget, and replaced Recent Posts with a Location widget for good measure.

![screen shot 2016-03-29 at 11 36 58 am](https://cloud.githubusercontent.com/assets/349751/14119393/d0b54082-f5a2-11e5-8910-5460beb90738.png)
