### ISSUE TITLE
Increase premium content flexibility beyond just a block

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#43194]
## Description

We still need to get on the same page with this project, but it would be great to leverage the existing WP data structures (through excerpts, categories, or tags) as an alternative way for people to enable premium content.

**Comment by davemart-in** [comment]
Note: Once this is in place it would make it much easier to do something like this: 

https://twitter.com/patrickc/status/1288652842073354240
> A service to turn blog archives into (optionally paid?) email newsletters could be pretty neat. There are a lot of blogs I missed the heydays of but whose archives contain a great deal of hard-to-consume gold.

Hat tip Michael Norman

**Comment by kwight** [comment]
Does this mean, "set all of this category's posts as Premium Content", that sort of thing?

**Comment by philnick206** [comment]
Plussing up this one. It would be great to be able to set Premium content at the page, post, category, tag and site-level. This is a request that comes up often and it would be much easier I think for user's to set Premium Content at this level versus a block (as the default mode).

**Comment by ericamQA** [comment]
Removing stale label, this is still a relevant enhancement request.

**Comment by artpi** [comment]
It is coming
https://github.com/Automattic/jetpack/pull/26417
pbOQVh-2OE-p2
