### ISSUE TITLE
Gutenboarding site title: animated placeholder

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#43191]
Context/designs from pbAok1-11X-p2

### Currently 
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/87168/84388944-0e689800-abfe-11ea-8af3-7cecc93561a2.png">

### Goal

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/87168/84388819-df522680-abfd-11ea-83c1-440b30e07ae8.png">

- [x] Show animated placeholder for site title (done in #43225):
    - _in focus photographers_
    - _cortado coffee sf_
    - _leah rand_
    - _ava young_
    - _mighty leaf tea room_
- [x] Move skip button to left and give it button-border (done in https://github.com/Automattic/wp-calypso/pull/43136)
- [ ] Great if site title input flows to 2nd row but ok to ship without that. Likely not worth because how complicated it gets?

Triple ensure this works well on iOS and Andrid, on different browsers. ;-)

**Comment by alshakero** [comment]
> Great if site title input flows to 2nd row but ok to ship without that. Likely not worth because how complicated it gets?

I agree. I think it's not worth the complexity. Unless design team wants it.
