### ISSUE TITLE
Gutenboarding site title: hide "skip" on mobile when title filled

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#43205]
On `/new` flow's mobile version, the "skip for now" button stays visible even when title is filled:

With title — skip button shouldn't be visible
![2020-06-11 17 57 47](https://user-images.githubusercontent.com/87168/84402413-0e23c900-ac0d-11ea-98db-fe7331363842.jpg)

Without title — all correct
![2020-06-11 17 57 44](https://user-images.githubusercontent.com/87168/84402415-0ebc5f80-ac0d-11ea-815a-c1622f3b38ac.jpg)

**Comment by razvanpapadopol** [comment]
We'll display only one of them depending if there is or not a site title value entered and they will be aligned to right on mobile, same as every other _Next_ CTA we have in the flow.
