### ISSUE TITLE
Add Alternate Options to Account Closure Page

### ISSUE THREAD

**Issue by gracie** [Automattic/wp-calypso#43211]
[HEs are spending a lot of time responding to accidental account closures](https://happops.wordpress.com/2020/06/10/site-restoration-tickets/) (84 hours of support time a month). Some of them reflect they had been trying to do something like change a username or delete a single site. 

We'd like to direct to those options on the [Account Closure page here](https://wordpress.com/me/account/close).

Can we add the following copy to this page?

> Before you close your account, were you looking to do the following instead?
> Start a new site
> Change a site address
> Change a username
> Change a password
> Delete a site

Here's the code it would need:
```
<p className="account-close__body-copy">
	{ translate(
	'Before you close your account, were you looking to do the following instead?'
) }
</p>
<p className="account-close__body-copy">
{ translate(
'<a href="https://wordpress.com/support/create-a-blog/#adding-a-new-site-or-blog-to-an-existing-account">Start a new site</a>'
) }
</p>
<p className="account-close__body-copy">
{ translate(
'<a href="https://wordpress.com/support/changing-site-address/">Change a site address</a>'
) }
</p>
<p className="account-close__body-copy">
{ translate(
'<a href="https://wordpress.com/support/change-your-username/">Change a username</a>'
) }
</p>
<p className="account-close__body-copy">
{ translate(
'<a href="https://wordpress.com/support/passwords/#change-your-password">Change a password</a>'
) }
</p>
<p className="account-close__body-copy">
{ translate(
'<a href="https://wordpress.com/support/delete-site/">Delete a site</a>'
) }
</p>
```

[Code in Opengrok.](https://opengrok.a8c.com/source/more/calypso/client/me/account-close/main.jsx?q=Account+closure+cannot+be+undone.+It+will+remove+your+account+along+with+all+your+sites+and+all+their+content.)

**Comment by Aurorum** [comment]
Happy to try a PR for this, but I wonder if this would fit better as a screen part of the confirmation modal? That would make it harder to miss (there's already quite a bit of content to read and I suspect people may just skim through it) while also ensuring that the two columns are a similar height.

**Comment by gracie** [comment]
@Aurorum if that's something that could be quickly implemented, that sounds amazing and yes please! 

We're looking for a solution that can be deployed sooner than later, though, so if that would take a chunk of development to make happen, we prefer at least a copy update.

**Comment by Aurorum** [comment]
Thanks @gracie! I'm pretty sure it won't take too long - I'll try to get something spun up tonight but definitely by tomorrow at the latest. :)

**Comment by gracie** [comment]
I was editing and then deleted - for anyone following along, a now out of context reply that basically said 'If we can do that quickly, then yes!'
