### ISSUE TITLE
Gutenboarding: New font pairing proposal

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#43224]
Our current font pairings in Gutenboarding offer a very limited choice of serifs. I wanted to propose a new pairing, that I've been using in the podcasting site designs:

**Headings**: Domine
**Body**: System font

![image](https://user-images.githubusercontent.com/4550351/84464694-8c897500-acb8-11ea-93e0-b98ed4b03819.png)

I also tried this font pairing in a couple of our existing homepage designs to see how well it will work:

![image](https://user-images.githubusercontent.com/4550351/84466015-bd1ede00-acbb-11ea-9f15-6bddd5d987ca.png)

![image](https://user-images.githubusercontent.com/4550351/84466033-c740dc80-acbb-11ea-9177-36e34d80af00.png)

![download (6)](https://user-images.githubusercontent.com/4550351/84466102-f48d8a80-acbb-11ea-9345-8afc9d5a81a5.png)

cc @ianstewart @iamtakashi @dubielzyk

**Comment by dubielzyk** [comment]
Looks great. Let's add it in :)

**Comment by iamtakashi** [comment]
Have you considered Merriweather or Lora?

I'd like to hear thoughts from @pablohoneyhoney too since Pablohas done an extensive review for Global Fonts.

**Comment by iamtakashi** [comment]
In the screenshots above, Overton, Cassel, and Raynolds don't seem to be with the themes that we offer in Gutenboarding. Let's see how the new font appears with the themes that we offer in Gutenboarding.

**Comment by alaczek** [comment]
> Let's see how the new font appears with the themes that we offer in Gutenboarding :)

Sure thing:

![image](https://user-images.githubusercontent.com/4550351/84607375-428ad400-aef0-11ea-95b1-61786c43210f.png)

![download (10)](https://user-images.githubusercontent.com/4550351/84607396-5e8e7580-aef0-11ea-8b2c-ea54d5273984.png)

**Comment by iamtakashi** [comment]
Those screenshots look much better to see how it would appear, thanks!

**Comment by simison** [comment]
@alaczek @ianstewart is this task still relevant?

**Comment by ianstewart** [comment]
Let's keep this one open as a request for more serif pairings. @kjellr and @sfougnier are looking currently at new pairing and font additions. (Note: these will eventually require UI updates but that's a good problem to have.)
