### ISSUE TITLE
Link to All About Domains support page broken from Customer Home

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#43220]
1. Starting at URL: https://wordpress.com/home/ (as a non a11n)
2. Scroll down to Help card in Customer Home
3. The "All About Domains" support page brings up a blank screen instead of the support doc preview.

The wordpress.com/support/all-about-domains page deprecated and redirected to wordpress.com/support/domains. 

Please change the link from wordpress.com/support/all-about-domains to wordpress.com/support/domains.

![bug](https://user-images.githubusercontent.com/36699353/84448778-d87ce100-ac08-11ea-9c89-632d49ca4f09.gif)

**Comment by Aurorum** [comment]
PR for this issue in #43543 :)
