### ISSUE TITLE
Premium Content: Connecting stripe will send Gutenframe users to WP Admin.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#43222]
If a user clicks the "Connect" button in the Premium Content block while in `wordpress.com/block-editor/` (Gutenframe), they will afterward be sent to the WP Admin edit screen of the post they were on, rather than back to the WordPress.com URL.

**Comment by kwight** [comment]
@blackjackkent I just noticed this PR by @mmtr : https://github.com/Automattic/jetpack/pull/16935 Can that be leveraged somehow?

**Comment by mmtr** [comment]
> @blackjackkent I just noticed this PR by @mmtr : [Automattic/jetpack#16935](https://github.com/Automattic/jetpack/pull/16935) Can that be leveraged somehow?

Yeah, that PR seeks to fix the same problem but for the Donations block. Now that that PR has landed, and with D48460-code also deployed, it should be relatively straight forward to fix the Stripe connection flow for the Premium Content block.

If you add a `source=gutenberg-calypso` query param to the [call to the `memberships/status` endpoint](https://github.com/Automattic/wp-calypso/blob/c484e63643995f8b631042d9979328d9b2fa511f/apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/edit.js#L215), Stripe should redirect back to wordpress.com/block-editor.

See how it has been done in the Donations block:

https://github.com/Automattic/jetpack/blob/f2fb85679b410acc850b7f7404b85d80c6bab760/extensions/blocks/donations/fetch-status.js#L15-L18

**Comment by blackjackkent** [comment]
Aha, fantastic. :) That definitely helps point me in the right direction! Thanks.
