### ISSUE TITLE
[wp-desktop][bug] Setup List Not Displaying

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#43235]
### Description

It appears there's been a regression in the behavior of the Setup List sidebar item in wp-desktop. When clicked, the setup list does not display.

### Expected (from web)

<p align="center">
<img width="400" alt="setup-list-expected-web" src="https://user-images.githubusercontent.com/8979548/84529251-1fbdad00-acaf-11ea-8150-1fa161dfa11c.png">
</p>

### Actual (desktop app)

<p align="center">
<img width="400" alt="setup-list-actual-desktop" src="https://user-images.githubusercontent.com/8979548/84529297-382dc780-acaf-11ea-9836-3d93c6952f4f.png">
</p>

This regression is in the critical path of the user sign-up/onboarding flow.

**Comment by nsakaimbo** [comment]
@mmtr I see some Setup List things were tweaked in PR #41450 and you might be familiar with this part of Calypso. Any idea what might be driving the regression here?

**Comment by mmtr** [comment]
@nsakaimbo To help stabilize accidental breakages, @Automattic/serenity added a simplified Home view just for WP-Desktop that doesn’t show any primary tasks (including the Site Setup List, which is considered a primary task): pbAPfg-sx-p2

We likely forgot to hide the setup progress indicator from the sidebar for WP-Desktop that’s causing this inconsistency. https://github.com/Automattic/wp-calypso/pull/43279 should handle it, but in the long term it'd be great if we can support the site setup on the desktop app (cc @Automattic/Create)
