### ISSUE TITLE
Invite e2e tests failing

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#43247]
The "Inviting new user as an Editor and revoke invite" e2e tests are failing because sometimes the input fields get erased while they are being filled in. I captured the behavior on a video here:

https://cloudup.com/c1o2MAES9qr

The issue seems to stem from this 4-year-old code, which causes the form to reset anytime its props change.

https://github.com/Automattic/wp-calypso/blob/8f9910abb2267c476b0f33ad20509b0609f393a3/client/my-sites/people/invite-people/index.jsx#L86-L88

**Comment by sirbrillig** [comment]
cc @annemirasol since we were discussing it in Slack.

**Comment by annemirasol** [comment]
Since `this.props.inviteLinks` and `this.props.siteRoles` are API requests, them coming in a little late may be triggering `UNSAFE_componentWillReceiveProps()`. I also can't quite grok why it wants a `resetState()` after that, but would it help if I at least exclude changes from those two aforementioned props from triggering the reset?

**Comment by sirbrillig** [comment]
Sounds like it would be worth a try!

**Comment by sirbrillig** [comment]
Speaking as someone who understands this component very little, another option _might_ be to have the component render nothing (or loading text/animation) while those props are still pending, if that's something you can determine.

**Comment by annemirasol** [comment]
Reopening as it looks like #43251 didn't solve the issue. Perhaps it's worth noting that in https://cloudup.com/c1o2MAES9qr, the Send invitation button did not get enabled even as the email address is entered (and a role is already selected).

**Comment by annemirasol** [comment]
Discussion with systems on this issue: https://wp.me/pMz3w-bzd

**Comment by youbrokesomething** [comment]
The underlying issue was resolved in 2020. I'm closing this ticket.
