### ISSUE TITLE
Shortcode Block: Copying part of the text from the block copies the entire content instead

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#43264]
#### Steps to reproduce

1. Add Shortcode Block into a Page/Post
2. Type a few words into it
3. Select one word and Copy it (either with the keyboard shortcut or via mouse menu)

#### What I expected
Get the selection copied into the clipboard
#### What happened instead
The entire content of the block is copied
#### Browser / OS version
Any
#### Screenshot / Video
![](https://d.pr/i/ggiL5s+)
_Link: https://d.pr/i/ggiL5s_
#### Context / Source
The same issue happens for Custom HTML Block https://github.com/Automattic/wp-calypso/issues/42998
#dogfooding

**Comment by simison** [comment]
Does this happen in Gutenberg outside WordPress.com as well? If so, this could be opened in Gutenberg repo https://github.com/WordPress/gutenberg

**Comment by simison** [comment]
This might be fixed in Gutenberg 8.3 with https://github.com/WordPress/gutenberg/pull/22793

**Comment by razvanpapadopol** [comment]
Fixed in the current Gutenberg version installed on wpcom. See https://github.com/Automattic/wp-calypso/issues/42998#issuecomment-648823961
