### ISSUE TITLE
Checkout: Changed contact details do not persist without purchase

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#43265]
In new checkout, adding domain contact details and then abandoning the cart does not persist those details.

Example (with pre-filled contact details, but the same should be true for an empty form):

- Load the form, see that it pre-fills with the name "Joe Foobar".
- Change the name to "Jane Barfoo".
- Press Continue.
- Reload the page.
- See that the contact form has "Joe Foobar" again. In old checkout, this would read "Jane Barfoo".

**Comment by sirbrillig** [comment]
Note that I believe the cached contact details are also not updated when the payment _fails_, which may cause the customer to have to fill them in all over again.

**Comment by michaeldcain** [comment]
To fix:
- when a user clicks "continue" 
- submit information to the stored contact details endpoint

**Comment by sirbrillig** [comment]
I'm very curious how this was possible because there is no endpoint that I can find that allows setting the stored contact details. 🤔

**Comment by michaeldcain** [comment]
@sirbrillig are you saying that this behavior was a regression from old checkout for non-domain purchases?

**Comment by sirbrillig** [comment]
No, non-domain purchases should be basically the same as old checkout in this regard, although the way the tax fields are presented with new checkout, it might feel like a regression. This issue is specifically for domain contact fields. I updated the text of the issue slightly to try to make that more obvious. (That said, however we fix it for domain contact fields we should make sure to also apply to G Suite and non-domain contact fields.)

Since there doesn't appear to be a way that these details were persisted to the server (unless there's something I'm missing), I believe old checkout must have relied more heavily on the cache of the contact details in the Redux state. New checkout fetches the contact details from the server on every load, ignoring the cached state, which is possibly why this issue exists.

I'm not sure if it would be a better solution to rely on the cached state, even if it would fix this issue, although it's an option. The downside is that it would risk using outdated data in some cases, so we'd need to consider how to invalidate the cache (after a certain period of time? some sort of merge with the server response? These all feel fragile.). I think I'd prefer to add an endpoint that allows setting the contact details and use that instead.
