### ISSUE TITLE
Single Page Editing: land users in site editor

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43287]
Depends on: https://github.com/Automattic/wp-calypso/issues/43284

After completing the Gutenboarding flow the users should land in the site editor. In order for this to work we need to:

- update the redirect URL in Gutenboarding;
- assign `core-site-editor-enabled` sticker to the created site so that FSE gets enabled on it.

**Comment by ockham** [comment]
> * update the redirect URL in Gutenboarding;

#43246

> * assign `core-site-editor-enabled` sticker to the created site so that FSE gets enabled on it.

D44941-code & #43246
