### ISSUE TITLE
Single Page Editing: show Seedlet blocks theme internally

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43288]
We should investigate how to enable Seedlet blocks theme only for a12s once it's published. It would be best to not surface it at all in themes showcase, but if that turns out to be too hard we can look for some other options like showing it at the end.

**Comment by vindl** [comment]
Depending on how the investigation in https://github.com/Automattic/wp-calypso/issues/43285 goes we might not need this.

**Comment by noahtallen** [comment]
Yep. It looks like we can activate the theme via gutenboarding. that should be enough for our purposes.
