### ISSUE TITLE
Single Page Editing: show different set of layouts in onboarding

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43285]
Based on the work in https://github.com/Automattic/wp-calypso/issues/43284 we should show a different set of layouts in the design selector that are based on Seedlet Blocks theme. Folks on View team will work on creating those, but until they are ready we can use mock layouts to test the functionality.

**Comment by vindl** [comment]
I just learned from @ianstewart that the existing Layouts in Gutenboarding will work for single page site too. I think the only thing remaining here is to make sure that the previews still look right with Seedlet blocks theme and that it's activated for the site.

**Comment by ianstewart** [comment]
@allancole @kjellr or @jffng Any concerns about adding seedlet and seedlet blocks to our public theme directory? If we don't network activate it? Just to see if we could start hooking it up for testing like the scenario above? (Seeing if it can be applied to a preview in Gutenboarding.)

**Comment by ianstewart** [comment]
Step one done!

@allancole now that these are in the themes github repo … I can't recall if anything will break if these are moved to /pub in wpcom svn without network activating. Because I've never used GH to deploy themes on WP.com and it's been a while since I've hacked something in /pub. :)

**Comment by allancole** [comment]
> I can't recall if anything will break if these are moved to /pub in wpcom svn without network activating. 

No nothing _should_ break in that scenario. If your testing these on a sandbox. I usually just deploy themes from GH to SVN manually to my sandbox and then deploy (or not) from there.

**Comment by ianstewart** [comment]
![image](https://user-images.githubusercontent.com/545779/84714062-33c51100-af32-11ea-8b2b-0c57c7b40830.png)

It's available in /pub now thanks to @allancole. You'll need to use a non-showcase method to activate it. (Probably WP CLI.) And the `core-site-editor-enabled` sticker on a test site.

**Comment by noahtallen** [comment]
I tested changing the config of one of the layout options to use `seedlet-blocks` as the theme.

Good news: it correctly activates the theme on the site!

A couple of oddities:

#### Layout preview in gutenboarding doesn't work. I assume this is related to the theme demo site

<img width="1474" alt="Screen Shot 2020-06-16 at 11 22 11 AM" src="https://user-images.githubusercontent.com/6265975/84813254-7f27ff80-afc4-11ea-947c-bfda650129fb.png">

#### The theme page for seedlet in calypso looks weird. you can see this by looking at the active theme on the site:

<img width="1518" alt="Screen Shot 2020-06-16 at 11 23 07 AM" src="https://user-images.githubusercontent.com/6265975/84813246-7c2d0f00-afc4-11ea-972a-339de78acc2e.png">

**Comment by ianstewart** [comment]
> The theme page for seedlet in calypso looks weird. you can see this by looking at the active theme on the site:

This'll be true until we have someway of hiding this theme while it's network-activated. :) (It might be a bit too buggy to network-activate now.) Once we have that we can set up a demo site and theme showcase page and network activate with it only being shown for the subset of users we choose.

**Comment by noahtallen** [comment]
sounds good!

**Comment by simison** [comment]
@noahtallen in case it's helpful, this is how the API gets the demo URL for the template:

```php
$theme_slug = 'pub/' . $theme_name; // We'll need to modify this if we want it to work for premium themes.
$demo_url = wpcom_get_theme_demo_site( $theme_slug );
```

In `class-wpcom-json-api-template-demo-endpoint.php`

**Comment by noahtallen** [comment]
Or at least, that's my working understanding of the problem, which might change after I test it again today :p
