### ISSUE TITLE
Cover Block: Provide accurate error message or upgrade pass when free user adds a video

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#43294]
In WP.com, only the Premium, Business or eCommerce plan users can upload a video to the cover block. And when a free user tries to upload a video to a cover block we show this unhelpful error message.

<img width="800" alt="Screenshot 2020-06-15 at 15 37 20" src="https://user-images.githubusercontent.com/908665/84671293-1cc8f380-af1f-11ea-8e19-da4a73d43ba2.png">

There are two issues about this:
* It's not really true :)
* There is no upgrade pass there to unblock the situation.

We show free users the following notice on paid blocks. While I'm not sure about the design of the notice, something similar would feel a lot helpful than the current error message.

<img width="794" alt="Screenshot 2020-06-15 at 15 38 16" src="https://user-images.githubusercontent.com/908665/84671855-c1e3cc00-af1f-11ea-8a72-61a67eeeafba.png">

cc @ianstewart @alaczek

**Comment by rickybanister** [comment]
This issue is already logged in https://github.com/Automattic/dotcom-manage/issues/38 and a fix is in progress. Good catch @iamtakashi !

**Comment by retrofox** [comment]
Tackled on these PRs. https://github.com/Automattic/jetpack/pull/16272 handles when the user tries to replace the current background using the replace button. And https://github.com/Automattic/jetpack/pull/16171 when it uploads a video either clicking on the upload button as well as dropping in the area of the media placeholder.
