### ISSUE TITLE
Gutenboarding: upgrades to domains page

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#43290]
### Desktop
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/87168/84663095-5d2b7000-af25-11ea-8f73-4d5a2eaf42dd.png">

See video https://d.pr/i/CdUyXQ

### Mobile
<img width="457" alt="image" src="https://user-images.githubusercontent.com/87168/84663333-aed3fa80-af25-11ea-8174-8af7657546f3.png">
https://d.pr/i/5pwk9F

## Changes summary
- Remove the radio buttons, and skip for now button. The two step process was cumbersome, and felt weird when a person selects a domain, and then needs to find "continue".
- With removing the top right button, a person can just select a domain, and continue.
- The hover state will surface the "select" CTA
- There is no more "skip for now", we need a person to select a domain/sub-domain to continue. Without a domain/sub-domain we'd be assigning folks a random sub-domain/site name, which we want to avoid.

**Comment by lsl** [comment]
> The hover state will surface the "select" CTA

Hover functionality can be problematic for screenreader setups.

Please correct me but probably just have to make sure each domain option is focus/clickable in some way.

**Comment by yansern** [comment]
> Please correct me but probably just have to make sure each domain option is focus/clickable in some way.

I suppose when the list is focused by tabbing, the button appears so it comes clickable.

**Comment by yansern** [comment]
Hmm, design doesn't show how it's supposed to look like when an item is selected. Since radio button is now removed.

**Comment by simison** [comment]
> Hmm, design doesn't show how it's supposed to look like when an item is selected. Since radio button is now removed.

There won't be selected state — we'd move straight to next step or close the modal on domain selection.

**Comment by yansern** [comment]
> There won't be selected state — we'd move straight to next step or close the modal on domain selection.

Oh okay! :)

**Comment by simison** [comment]
@olaolusoga @dubielzyk in these designs "free" is again on top of the list:

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/87168/84990862-6e0afa00-b14e-11ea-817d-24d2fc3c8ad5.png">


[We were about to](https://github.com/Automattic/wp-calypso/pull/43373) move to this order as per pbAok1-11X-p2:

> recommended
> free
> the rest

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/87168/84990736-42880f80-b14e-11ea-9f5f-4a720e496929.png">

Which way should it be?

**Comment by dubielzyk** [comment]
I've personally wanted Free at the top, but I don't have strong feelings. Perhaps go for Recommended at the top and Free next, then the rest.

**Comment by olaolusoga** [comment]
+1 to Recommended, Free, the rest.
