### ISSUE TITLE
Replace the term `master` with `main` or `primary`

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#43303]
*Note:* This does _not_ include renaming the `master` branch. That is a seperate discussion here: p4TIVU-9rw-p2

We should replace the usages of the term `master` with a neutral term like `main` or `primary`. The rationale for this change is the exact same as the rationale described in this related issue: https://github.com/Automattic/wp-calypso/issues/43302

I suggest we do this _after_ renaming the branch, mostly because it will remove a large amount of noise when you `git grep master` right now, many of the references are to branch names. If we do it after we've renamed the branch name we'll be able to more confidently do variable name replacement and copy updates without taking on the risk of the branch name changes.

That being said, if there are incremental changes that we can go ahead and do (for example, updating user-facing copy could be prioritized) then we should.

**Comment by Aurorum** [comment]
I can open up a PR to change `isJetpackUserMaster` and `userIsMaster` today or tomorrow since I'm going to spin up a PR for #25812 and they're pretty heavily related. :)
