### ISSUE TITLE
Replace "whitelist" and "blacklist" with "allowed" and "disallowed"

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#43302]
There are a number of places in our repository which use the terms "whitelist" and "blacklist" unnecessarily and which are under our control. In the context of our current social structures, the terms "white" and "black" are not neutral, and using "whitelist" and "blacklist" closely mirrors racial associations of whiteness or the color white being or representing something positive and blackness or the color back being or representing something negative. Using these terms in this way perpetuates racism ingrained in the English language through centuries of colonialism and racism.

Additionally, alternative language to "whitelist" and "blacklist" will always be generally more clear.

Given that in every case under our control it should be possible to come up with alternative language that is not weighed with racial connotations, we should do this in our repository.

A quick search of our repository yielded around 65 files that used the term "whitelist". Some files, like stylelint, webpack, and eslint configurations and yarn releases I don't think we would be able to have control over unless the underlying libraries were to be updated.

There are about 20 files which use the term "blacklist".

Under most circumstances, "whitelist" can be substituted with "allowed" and "blacklist" with "disallowed". In the handful of cases when that's not possible (Grammatical issues in user-displayed copy for example—though I'm not certain these issue will exist, I'm anticipating they might) then it should not be difficult to come up with an appropriate alternative.

**Comment by bluefuton** [comment]
We updated the Reader codebase at the end of last year, substituting "blacklist" for "blocklist": https://github.com/Automattic/wp-calypso/pull/38363

**Comment by simison** [comment]
I like "exclude" instead of "block" because we already have so many _blocks_ (in editor context) around that "blocklisted" can get confusing. :-)

**Comment by saramarcondes** [comment]
Good point @simison. I changed it in the PR 🎉
