### ISSUE TITLE
Domains Search: Lost first character when replacing search term

### ISSUE THREAD

**Issue by jcsanyi** [Automattic/wp-calypso#43304]
When I follow these steps on the domain search page (`/start/domains/`):
1. Type a search term
2. Select the search box contents (with shift-Home or ctrl-A, or with mouse)
3. Type a new search term

...the first character of the new search term is lost.

The following screen is from typing "test" as a search term:
![image](https://user-images.githubusercontent.com/447364/84706469-d4570900-af11-11ea-968e-eba601bcc59a.png)

I doubt it's browser or OS specific, but just in case, I've reproducted it so far in:
- Linux (Arch), Chrome (81.0.4044.129)
- Linux (Arch), Firefox (75.0)

**Comment by klimeryk** [comment]
Thanks for reporting! I've been able to reproduce it, but interestingly only in signup 🤔 (not in Domain Management -> Add) @niranjan-uma-shankar, is this something you've run into previously?

**Comment by niranjan-uma-shankar** [comment]
I am able to reproduce it too. Also, when there are only two characters in the input box, backspace deletes both characters.

I've not tried this before so I don't know how long it's been around. Interesting that it's seen only in signup flow but I don't know top of my head what could be causing it though.

**Comment by pottedmeat** [comment]
The `RegisterDomainStep` component sets `lastQuery` to an empty string when the query is less than 2 characters:

https://github.com/Automattic/wp-calypso/blob/4f9ef6703007b8c8a62e6ebb9af15956de88a187/client/components/domains/register-domain-step/index.jsx#L700-L715

which is then passed as the value to the `Search` component:

https://github.com/Automattic/wp-calypso/blob/4f9ef6703007b8c8a62e6ebb9af15956de88a187/client/components/domains/register-domain-step/index.jsx#L443-L445

The `Search` component, in `UNSAFE_componentWillReceiveProps` normally bails out before updating the state's `keyword`:

https://github.com/Automattic/wp-calypso/blob/4f9ef6703007b8c8a62e6ebb9af15956de88a187/client/components/search/index.jsx#L132-L138

but when transitioning from a valid search query to a single character, none of these conditions are hit and the state is updated with the empty string which came from `getDomainSuggestionSearch`.
