### ISSUE TITLE
Template Demo API: node parser strips inner HTML of target element

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#43310]
Reported here: https://github.com/Automattic/wp-calypso/pull/42354#issuecomment-644506953

> the site title looks off in the preview, it should be bold (this is Barnsbury, but the same happens in all themes that have a bold site title)

![image](https://user-images.githubusercontent.com/4550351/84727833-4a6f7480-afd3-11ea-88a2-fcec374e9dfd.png)

Possible fix:

> I think the issue here might be that the template/demo endpoint appears to strip the HTML elements within the .site-title element when swapping out the text there for the site title, so it doesn't have the wrapping a tag to give it the bold style via .site-title a. Maybe something for us to fix up in that endpoint separately?

See: https://github.com/Automattic/wp-calypso/pull/42354#issuecomment-644524559

Props to @andrewserong and @alaczek for finding/working out what's going on

**Comment by andrewserong** [comment]
Fix in D44979-code.

**Comment by andrewserong** [comment]
Deployed fix.
