### ISSUE TITLE
Checkout: add plan variation nudge

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#43328]
With the new default summary view of the order review step, plan term variations (1 year/2 year) are now hidden behind the "edit" toggle. We should utilize the Checkout nudge pattern introduced with the personal plan upgrade nudge to expose the term variation savings to the user.

Current design:
https://cloudup.com/c9QLmFu3j1Y

**Comment by michaeldcain** [comment]
I believe this is being handled as part of Marketing's monthly price test so I'm removing it from the Shilling project board: pcbrnV-sa-p2

cc @Automattic/martech

**Comment by michaeldcain** [comment]
@paulbonahora do you know if this ended up being implemented with the monthly plans work? If not, it might be a good test going forward.

![Screen Shot 2021-04-06 at 8 22 47 AM](https://user-images.githubusercontent.com/942359/113710259-7caca880-96b1-11eb-89e2-5164ef012f9e.png)

**Comment by sirbrillig** [comment]
The "edit" state was removed in https://github.com/Automattic/wp-calypso/pull/65374 and the variant picker is now always visible, so I'm going to close this as solved.
