### ISSUE TITLE
Make Calypso Theme Page Work on WordPress.org Themes

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#43337]
#### Description

The Calypso Theme Pages are designed to work on in-house themes available in https://wordpress.com/themes/.  This is what it looks like when we click on the Venture theme:

<img src="https://d.pr/i/4QdrhF+" width="600" />

It's great because it has different tabs with info on setting up the theme and getting support.

#### Actual

In wp-admin > Appearance > Add New on an Atomic site, its a different experience when installing WordPress.org themes.  Clicking on a thumbnail leads the user to the Customizer with a theme preview, without much info on the theme and support for it.

<img src="https://d.pr/i/k4aJAh+" width="600" />

#### Expected

Users may find it helpful to view WordPress.org themes in the Calypso theme page format.  At the moment, we can force them to load under the Calypso theme page by adding the theme slug to `https://wordpress.com/themes/`. Here it is loading the [Astra theme](https://wordpress.com/themes/astra) (`https://wordpress.com/themes/astra`):

<img src="https://d.pr/i/dM2vyk+" width="600" />

However, things like “Activate this design” or “Open live demo” don’t work correctly. It would also be great to have the Support tab contain:

1. Information on whether it's third-party or a product of Automattic and whether we officially support it
2.  A link to the .org support forum
3. A link to documentation that we create (if available)
4. A link to the theme's official website and documentation

Related: #43233

**Comment by Aurorum** [comment]
Noting that I've already made a start on this with a nudge in #43052!

**Comment by kwight** [comment]
It looks like this is dealt with. 👍
