### ISSUE TITLE
Gutenboarding: domain not available message

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#43340]
This is something for us to consider.

Right now if I type a domain that is taken into the site title field or edit the domain search input to enter a domain that is taken there is no form validation telling me it's taken or giving me a path to claim it later in the launch flow. 

We should discuss and consider adding that. If they claim that they own the domain we should defer the transfer until later and add it to the pre-launch checks as to not disrupt the site building experience. 

Currently in onboarding:

![image](https://user-images.githubusercontent.com/437258/84796607-cb743f00-afc6-11ea-8655-92154f1895fb.png)

Vs the Calypso /domains/add screen:

![image](https://user-images.githubusercontent.com/437258/84796663-e21a9600-afc6-11ea-881d-984d765cf30e.png)

**Comment by razvanpapadopol** [comment]
A solution for this issue has been implemented in #45698
Feel free to re-open if it's not acceptable. We can also open a follow-up issue for improvements.
