### ISSUE TITLE
Support: component buttons misaligned at intermediate widths

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#4335]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/app-components/happiness-support
2. Resize the browser from wide to small and watch the placement of the Ask/Search buttons
3. Between desktop/tablet and tablet/mobile widths there are places where the buttons are misaligned

#### What I expected
Clean button alignment

#### What happened instead
Misaligned buttons

#### Browser / OS version
OSX Chrome v49

#### Screenshot / Video
![wp-calypso-happiness-support-widths](https://cloud.githubusercontent.com/assets/7233112/14057910/daab25ae-f2e4-11e5-84d4-bec6b263c919.gif)

**Comment by lancewillett** [comment]
Could be a good first change? Labeling it.

Here are a few more screenshots:

iPad
![simulator screen shot apr 14 2016 10 26 35](https://cloud.githubusercontent.com/assets/66797/14537382/9d3810d2-022b-11e6-831d-17d45d0f2b53.png)

iPhone 6
<img width="487" alt="screen shot 2016-04-14 at 10 24 27" src="https://cloud.githubusercontent.com/assets/66797/14537384/a2c0a83e-022b-11e6-8df0-34fb9f122330.png">

**Comment by lancewillett** [comment]
CC @dllh Should be a simple CSS fix with checking the proper breakpoints, maybe for a trial HG Wrangler?

**Comment by dllh** [comment]
@mrheston or @southp this might be a nice simple one for one of you to pick up.
