### ISSUE TITLE
Hosting Config: SFTP icon is above the feature example gradient.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#43355]
If a user doesn't have a qualifying plan, we show them a feature example on the Hosting Configuration page. The example is supposed to be entirely covered by a gradient, but for some reason, the cloud SVG is sitting above the gradient. Could be a `z-index` thing.

<img width="1224" alt="Screen Shot 2020-06-16 at 12 37 23 PM" src="https://user-images.githubusercontent.com/349751/84820499-9a980800-afce-11ea-965a-94bb604c9436.png">

**Comment by mmtr** [comment]
Reserved for onboarding.

**Comment by mmtr** [comment]
Hey @kwight, I think this is a visual effect and the icon is actually below the gradient. That's more noticeable when limiting the height to a very low value (e.g. 50px):

<img width="1093" alt="Screen Shot 2020-08-17 at 16 21 41" src="https://user-images.githubusercontent.com/1233880/90406738-e128e200-e0a5-11ea-9e7d-81f0be2e6321.png">

Feel free to reopen if maybe this is specific to a browser (my testing above has been in Chrome, but also checked it in Safari).
