### ISSUE TITLE
Add design-specific posts/page content for sites created in Gutenboarding

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#43363]
In Gutenboarding we're headstarting sites with posts from the themes' headstart annotations, which often don't match the design starter site or context.

For example, the Cassel design uses the Maywood theme, and consequently displays posts from that theme's annotation file:

<img width="763" alt="Screen Shot 2020-06-17 at 1 31 07 pm" src="https://user-images.githubusercontent.com/6458278/84852047-2e390980-b09f-11ea-833a-9d71a2f0e2e0.png">

The [demo site](https://iamtakashinuxtest20200317101004.wordpress.com/) on the other hand, looks like this:

<img width="1124" alt="Screen Shot 2020-06-17 at 1 32 28 pm" src="https://user-images.githubusercontent.com/6458278/84852063-35601780-b09f-11ea-8abe-75553ff9e6cb.png">

D43937-code attempted to address this issue by generating and using a headstart annotation from the design starter site.

See pbAok1-ZB-p2 for more context

A possible approach might be to generate headstart annotations from the “source” sites we use, for example https://gutenboardinghp11.wordpress.com/, and bypass the theme’s annotation files when creating the site. More discussion here: p9Jlb4-1wg-p2#comment-2392

**Comment by ramonjd** [comment]
I've been fooling around in D45183-code 

It's just test code, but it shows that we can (of course) headstart a site using an annotation from a starter site. 

We just need to think of a nice way to use the starter site for the previews, where the design in question belongs to a theme. 

For example mayland + Cassel. 

The Cassel preview pulls the mayland theme demo site content. That's why the posts are about cameras, and not delicious food.

<img width="1271" alt="Screen Shot 2020-06-19 at 3 31 58 pm" src="https://user-images.githubusercontent.com/6458278/85099906-0c2bbc80-b242-11ea-8a4f-1df3ac069f0e.png">

**Comment by ianstewart** [comment]
Any reason to not just mshot the starter site?

**Comment by ramonjd** [comment]
> Any reason to not just mshot the starter site?

Oh, I meant the iframed demo on the font selector page. It might be weird to offer HTML-based previews for some designs and not others there. 

<img width="1184" alt="Screen Shot 2020-06-21 at 9 03 21 am" src="https://user-images.githubusercontent.com/6458278/85213171-18c52780-b39e-11ea-89dc-e24da7d95047.png">

**Comment by ramonjd** [comment]
> We just need to think of a nice way to use the starter site for the previews, where the design in question belongs to a theme

Not "nice" but functional :) D45183-code updated

**Comment by ianstewart** [comment]
cc @iamtakashi in case you miss the phab ping above.

**Comment by ramonjd** [comment]
@iamtakashi @ianstewart For the following design sites – 

```
			$designs = [
				'gibbs' => 'https://blockpatterns489018373.wordpress.com/',
				'brice' => 'https://iamtakashinuxtest20200330183111.wordpress.com/',
				'doyle' => 'https://gutenboardinghp4.wordpress.com/',
				'overton' => 'https://iamtakashinuxtest20200310125636.wordpress.com/',
				'camden' => 'https://gutenboardinghp7.wordpress.com/',
				'easley' => 'https://gutenboardinghp5.wordpress.com/',
				'reynolds' => 'https://gutenboardinghp3.wordpress.com/',
				'vesta' => 'https://iamtakashinuxtest20200316221813.wordpress.com/',
				'cassel' => 'https://iamtakashinuxtest20200317101004.wordpress.com/',
				'edison' => 'https://gutenboardinghp2.wordpress.com/',
				'bowen' => 'https://gutenboardinghp1.wordpress.com/'
			];
```

– am I okay to:

1. Turn off the marketing bar for the design starter sites by flagging them as "brown"

See https://wp.me/P1obSE-R for an explanation of what this flag means. TL;DR not much for us, only that it ensure the marketing bar doesn't show

2. Update the design starter sites so that the menus match the site we wish to create for our users

E.g., remove the "Blog 2" menu item from https://gutenboardinghp2.wordpress.com/

I think D45183-code should be okay to review/merge after that.

**Comment by ianstewart** [comment]
> 1 - Turn off the marketing bar for the design starter sites

I don't see a reason not to.

**Comment by ianstewart** [comment]
> 2 - Update the design starter sites so that the menus match the site we wish to create for our users

No reason not to. I've created a task for us to go through those starter design site menus and make sure they're all cleaned up for Headstart Annotations.

**Comment by ramonjd** [comment]
> I've created a task for us to go through those starter design site menus and make sure they're all cleaned up for Headstart Annotations.

This is fantastic. Thank you! https://github.com/Automattic/view-design/issues/54

**Comment by ramonjd** [comment]
Note to self: we'll have to regenerate the thumbnails on Calypso

https://github.com/Automattic/wp-calypso/tree/master/static/page-templates/design-screenshots

**Comment by ramonjd** [comment]
Ready for testing D45183-code

**Comment by ramonjd** [comment]
Deployed in D45183-code
