### ISSUE TITLE
Atomic: Free Photo Library not available in AT sites

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#43367]
On simple sites, the [Free Photo library](https://wordpress.com/support/add-media/finding-free-images-and-other-media/#wordpress-com-free-photo-library) is available when selecting media

A similar p7DVsv-8EI-p2#comment-29091 was made where the GH was made, however isn't applied on AT sites.

https://github.com/Automattic/jetpack/pull/15717

#### Steps to reproduce

1. Create a new post
2. Add a new Image block
3. On the Image block, select "Media Library"

#### What I expected

The option to select free images as seen below

![image link 2](https://en-support.files.wordpress.com/2019/05/search_free_library.png)

#### What happened instead

There were no options to select free photo library when selecting media library.

![image link 2](https://cldup.com/1wPrfm2zlD.png)
image link: https://cloudup.com/cQlcaiV93dp

#### Context / Source

AT environment at the time of this report:
Jetpack Version 8.6.1
Gutenberg Version 8.3.0

**Comment by inaikem** [comment]
Tagging a related ticket to keep the user updated.

#3066719: https://woothemes.zendesk.com/agent/tickets/3066719

**Comment by jerrysarcastic** [comment]
User checked in again at #3066719-zd

**Comment by edwinho89** [comment]
Issue has been resolved with the launch of External Media with Jetpack 8.7
