### ISSUE TITLE
Menus and Verification: Unable to edit menus without first verifying email

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#43399]
It's not currently possible for users to update their menus in the customizer without first verifying their email. This is true despite having pages often created by default and while it's possible to create pages on WP.com. Example …

![image](https://user-images.githubusercontent.com/545779/84929646-b9150680-b095-11ea-8db3-b958ad844048.png)

**Comment by ramonjd** [comment]
Context: p58i-5gt-p2

And https://github.com/Automattic/customization/issues/118

Just confirming: this issue asks us to remove the email-verification constraint on the customizer

**Comment by ianstewart** [comment]
Correct. Though whether or not we should is another topic. @rickybanister  Logging it here to start.

**Comment by rickybanister** [comment]
Yeah, I'd say making a site public is the only event we'd want to consider blocking on verification. Everything else we're doing just creates ridiculous UX issues.

**Comment by kwight** [comment]
Patch by @tjcafferkey in D49656-code.

**Comment by tjcafferkey** [comment]
Closed in D49656-code.
