### ISSUE TITLE
Framework: color tabs on Chrome Android using `theme-color` meta

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#434]
Add support for the `theme-color` meta element used in Chrome for Android.

`<meta name="theme-color" content="#0087be">`

Suggested by @kwonye 

> I visited Yahoo and noticed their address bar was purple. Any chance we can do this for WordPress.com?

<img src="https://cloud.githubusercontent.com/assets/66797/11325008/d90eb798-90ff-11e5-8d35-d9d2c681d79e.png" width="480" />

This is what it looks like in the app switcher:

<img src="https://cloud.githubusercontent.com/assets/66797/11325012/e1d8ced6-90ff-11e5-81ae-910cb08edcb2.png" width="480" />

**Comment by folletto** [comment]
This is already live (it's a theme feature, thus on the PHP side).

What this issue then about is adding it on Calypso. ;)

**Comment by lancewillett** [comment]
Yes, this is adding to Calypso (we're in Calypso GitHub!).

**Comment by folletto** [comment]
Ok, renamed then to make it more explicit (the use of "theme" in the meta felt ambiguous to me). :)

**Comment by lancewillett** [comment]
Haha: `theme` as in `color scheme` not `WordPress layout engine`. :)

**Comment by lancewillett** [comment]
No other votes for this yet — so closing for now. Feel free to re-open or add votes to bring it back.
