### ISSUE TITLE
Editor: Inserting hyperlinks selecting text in/across Paragraph blocks, toolbar disappears

### ISSUE THREAD

**Issue by fylgjur** [Automattic/wp-calypso#43401]
I have been experiencing periodic issues with inserting text hyperlinks.

Theme: P2 front and backend editing in paragraph blocks. _Edit: not just P2_
My own A8C Trial P2

#### Steps to reproduce: 

- Select text in a paragraph block. 
- Select text from right to left, ending with the mouse out of the block's horizontal level. The formatting toolbar (bold, italic, link, etc) is not accessible.

![bug3](https://user-images.githubusercontent.com/65490337/84928449-4c663000-b0c6-11ea-8cdb-ef9577549039.gif)

Here the difference between dragging beyond the left hand side of the block but within its top and bottom, compared with dragging the mouse beyond its bottom edge, is seen:

Here, it is a one line Paragraph block, the mouse positioning isn't clear:</p>

![bug1](https://user-images.githubusercontent.com/65490337/84928339-250f6300-b0c6-11ea-986e-8f0eaad15735.gif)

Here are two paragraph blocks. This demonstrates some of my clumsy selecting of text (there's something counterintuitive about this...) but then, the same thing again. This time, after a few failed attempts to select text right to left descending a line, I selected text selecting from left to right, but ending with the mouse beyond the original block's bottom edge and the formatting toolbar is absent:

![bug4](https://user-images.githubusercontent.com/65490337/84928491-5be57900-b0c6-11ea-99c7-d840f4adabab.gif)

The second issue which was previously here I have stripped out and opened into a new issue in order to route to P2tenburg if appropriate, #43427 
I've also removed all the WP markdown here ;) I'm learning...

**Comment by simison** [comment]
cc @johngodley could this be P2tenberg bug?

**Comment by johngodley** [comment]
> P2 front and backend editing

Just to confirm, it happens on the back end as well? Is this /wp-admin/ or Calypso? Is it on every P2 or just the one P2?

What are the floating marks - the blue check and the red circled 1?

**Comment by fylgjur** [comment]
Thank you, I'm happy to clarify - it's my first Github contribution so I'm happy to be advised or receive constructive criticism!

I have done more complete testing to rule out your questions. 

- Back and front end on P2

- Also appearing in other themes upon verification.

_For information, the red circle and blue check are grammar and language checking extension to Chrome, but they are recent additions and these experiences predate this extension._

### Issue 1 - selecting across blocks

For issue 1, upon reflection and further testing, it may be normal block behaviour rather than a bug as such, but one I've been experiencing as unintuitive and which users may potentially interpret as a 'buggy' experience.

Here for instance upon testing in Hever theme, between blocks of different types the layout icon appears upon selecting between block boundaries. Here, between a paragraph and list block:

![bug5](https://user-images.githubusercontent.com/65490337/84992999-8f64e980-b140-11ea-95ae-840d3fb8e4e5.gif)

Here between two paragraph blocks the toolbar disappears upon selecting across blocks. So in summary, I would not be able to format text across several blocks:

![bug6](https://user-images.githubusercontent.com/65490337/84993172-d0f59480-b140-11ea-940f-367c10f7d12a.gif)

There is another disappearance of the toolbar in this scenario, which feels instinctively more 'buggy'. The last paragraph block in a series, selecting text from left to right, I would expect to still see the formatting toolbar here:

![bug7](https://user-images.githubusercontent.com/65490337/84993789-a8ba6580-b141-11ea-8e62-ae73eda80c16.gif)

All the above examples are from a non A8C account blog using Hever theme. 

I will further test issue 2 now.

**Comment by fylgjur** [comment]
Here, I saw the same thing, but this time, I selected text, strayed into the next block, returned to the original block, but did not see the toolbar restored:

![bug8](https://user-images.githubusercontent.com/65490337/84995080-7a3d8a00-b143-11ea-9431-95fdb5688d51.gif)


Back in A8C P2 front end.

**Comment by johngodley** [comment]
Thanks. From what I can tell a lot of this is expected Gutenberg behaviour. It may not be ideal, but it's likely something that will be improved.

I think the thing to do here is to try and separate out any behaviour that isn't expected. If Calypso or P2 is behaving differently from Gutenberg then we can look at the specifically.

Would you say anything above behaves differently on Calypso/P2 to a non Automattic editor? It's kind of hard to tell just by looking at all the gifs.

**Comment by simison** [comment]
Thanks for elaborate instructions and pondering here! If this is a problem in Gutenberg itself, and not .com specific, it's worth bringing this up at https://github.com/wordpress/gutenberg/issues

**Comment by johngodley** [comment]
> Is there anything in particular I should look for

There was nothing in particular, and the comment was aimed more at if anything you described above is different from how it behaves on a standard non-Automattic site.

If the issues described here are part of the standard core editor then, as Mikael said, bringing it up on the core Github is best, and then any changes will filter back.
