### ISSUE TITLE
My Home support search missing "reset" icon when searching

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#43443]
When the My Home "Get help" support search is displaying in a "searching" state (ie: when you've made a search and it's fetching results) the "X" icon to reset the search is hidden.

Compare this to the FAB version where the "X" is NOT hidden.

This is because of CSS which is too generic on the Home version only. Need a more specific selector to only target the magnigicying glass icon.

![Screen Shot 2020-06-18 at 15 04 06](https://user-images.githubusercontent.com/444434/85030314-36637880-b175-11ea-9e5f-ac49ee57fe52.png)

![Screen Capture on 2020-06-18 at 15-03-24](https://user-images.githubusercontent.com/444434/85030372-4713ee80-b175-11ea-8751-11aa991dc3b9.gif)

**Comment by getdave** [comment]
@retrofox this might be fixed by your refactoring PR.

**Comment by retrofox** [comment]
tackled here 8751195ce521e99c5e6c0981e78c7131cb66f653
