### ISSUE TITLE
Gutenboarding: improve focus state of skip buttons

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#43446]
Our happiness friends recently performed a quick accessibility audit of the flow and found that the focus state of our secondary buttons was a bit easy to miss. 

pbAok1-15f

Our primary buttons have a strong focus state:

![image](https://user-images.githubusercontent.com/437258/85033267-c4783880-b14e-11ea-9dad-3b31e9d435ab.png)

While our secondary buttons it's subtle:

![image](https://user-images.githubusercontent.com/437258/85035765-89c3cf80-b151-11ea-8b0d-fa41d77e0310.png)

Could it have a thicker border or shadow or something to help it stand out a bit more?

**Comment by andrewserong** [comment]
Hey there, just adding that in the original report the secondary button's border was grey when focused. I then pushed https://github.com/Automattic/wp-calypso/pull/43419 to make the border blue (as in the screenshot), but we can further iterate to make it more prominent, too, of course!

**Comment by simison** [comment]
@ollierozdarz @rickybanister do you recon this still needs action or are current buttons with blue focus borders enough?

**Comment by dubielzyk** [comment]
I personally think this is good enough. Feels like we're adding more visual clutter when it's already doing it's intended job.

**Comment by simison** [comment]
Secondary button could do with hover and active states.

#### Secondary button
default
<img width="181" alt="image" src="https://user-images.githubusercontent.com/87168/89867365-c3e1a880-dbb9-11ea-99e8-51729608a9e5.png">

(no hover or active states)

focus
<img width="192" alt="image" src="https://user-images.githubusercontent.com/87168/89867380-c8a65c80-dbb9-11ea-9a94-b1d073bb6309.png">

#### Primary button
default
<img width="178" alt="image" src="https://user-images.githubusercontent.com/87168/89867438-da87ff80-dbb9-11ea-9121-6908ed6535df.png">

hover
<img width="180" alt="image" src="https://user-images.githubusercontent.com/87168/89867473-e96eb200-dbb9-11ea-930c-3d0eacf3ad41.png">

active
<img width="179" alt="image" src="https://user-images.githubusercontent.com/87168/89867630-1cb14100-dbba-11ea-959c-89ec733d0aa6.png">

focus
<img width="189" alt="image" src="https://user-images.githubusercontent.com/87168/89867495-f12e5680-dbb9-11ea-8d91-be5d1e8b6978.png">


#### Buttons from core:
default
<img width="188" alt="image" src="https://user-images.githubusercontent.com/87168/89867829-7154bc00-dbba-11ea-8290-20f3add82776.png">

active 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/87168/89867852-7ca7e780-dbba-11ea-8e64-42690cf09d73.png">

hover
<img width="190" alt="image" src="https://user-images.githubusercontent.com/87168/89867899-8c273080-dbba-11ea-856a-1ccd42cc4cd9.png">

focus
<img width="194" alt="image" src="https://user-images.githubusercontent.com/87168/89867933-9b0de300-dbba-11ea-8a85-c02e5a8a72cd.png">

**Comment by dubielzyk** [comment]
I agree that hover and active states make sense. We should whip that up

**Comment by ollierozdarz** [comment]
Agree with @dubielzyk - adding a Hover and Active state for Secondary buttons in Gutenboarding would be a good improvement.

We can lend from Core here:

**Hover:** Make the label and border the same Blue
**Active:** Make the label Blue and background Light Grey
