### ISSUE TITLE
Earn: Prefer loaders over copy pop-in

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43451]
When a customer has access to Earn features, we see copy pop-in from "Collect" to "Manage". Let's prefer providing placeholder loaders if plan information isn't available. 

![Jun-18-2020 10-47-53](https://user-images.githubusercontent.com/1270189/85054742-63059900-b151-11ea-8ef3-f5cda2d839b1.gif)

**Comment by blackjackkent** [comment]
@gwwar Do we have an existing design for loaders on these sorts of cards or do we need UX work here?

**Comment by kwight** [comment]
@blackjackkent we have two general types of placeholder: a [CSS-based](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/customer-home/main.jsx#L106) "pulsing" type, as well as [spinners](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/customer-home/cards/features/stats/index.jsx#L101). I think having the card display pulsing placeholder text until it resolves would be fine, but @danhauk or @sixhours may have a stronger opinion.

**Comment by gwwar** [comment]
Pulsers here would be a good fit. Spinners tend to make more sense in buttons.

There's a visual example of what these look like in https://wpcalypso.wordpress.com/devdocs/design/vertical-nav or try navigating WordPress.com with a fully clean cache + network activity throttled via the developer tools bar

<img width="328" alt="Screen Shot 2020-07-02 at 10 52 32 AM" src="https://user-images.githubusercontent.com/1270189/86393607-2ad28000-bc52-11ea-8f54-1366571a5dea.png">

**Comment by sixhours** [comment]
+1 for the pulsing type!
