### ISSUE TITLE
(3P) Settings Search: Review admin sections & commit

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#43464]
Let's make sure the hard-coded admin sections that will be mapped to search results are up to date.
See https://github.com/Automattic/wp-calypso/pull/31903/files#diff-5cf1c6b9497fdc569ac7d61cb67e6958

This task includes making those sections available in `/blocks/inline-help`.

See 8-gh-dotcom-manage.

**Comment by obenland** [comment]
Suggestions for additional sections: p7DVsv-8Sc-p2

**Comment by marekhrabe** [comment]
I think it would be good to check if we can move this into Redux in the first place with a similar effort as just copying the static version. I think that will make our code more robust and future ready. A very realistic example could be that later we:

- load the sections dynamically from some API (similar to how we dynamically load support articles from the support site)
- we generate this based on routes available, types of sites that user has or some other runtime logic…

Having it in redux right away will make it easier to do changes like above and if that won't bring huge overhead now (I don't think it will), it might be the best way to do this.
