### ISSUE TITLE
Gutenboarding: plans page needs to list uploading plugins and themes

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#43461]
The plans grid does not mention uploading themes and plugins for Business and Ecommerce tiers:

![image](https://user-images.githubusercontent.com/437258/85067662-09b45e80-b17f-11ea-8ca2-2932125147ee.png)

We should show off all relevant plan features to pack out the upper tiers.

**Comment by simison** [comment]
So: "Install plugins" and "Upload themes" like at https://wordpress.com/pricing/

**Comment by yansern** [comment]
Need actual copy.

> The plans grid does not mention uploading themes and plugins for Business and Ecommerce tiers.

Does this mean adding upload themes & install plugins under business features?
```
...
Business features (incl. SEO)
Upload themes
Install plugins
...
```

> We should show off all relevant plan features to pack out the upper tiers.

Does this mean replacing business features with all the business features?

```
...
Business features (incl. SEO) [remove this one and add the rest?]
SEO Tools
Upload themes
Install plugins
Automated Backup
SFTP & Database Access
...
```

Or do we expand everything like this?

![image](https://user-images.githubusercontent.com/1287077/85107606-8b070200-b20e-11ea-8214-658c57709db6.png)


(I'm gonna start off with the first one in a draft PR for now).

**Comment by simison** [comment]
I understood it so that we would add two list items ("Install plugins" and "Upload themes") to both business and eCommerce plans. 

@dubielzyk can you help clarify? :-)

**Comment by dubielzyk** [comment]
Yeah. Whatever we add on business needs to be added to e-commerce as well.
