### ISSUE TITLE
(8P) Social Previews: Publish previews as NPM package

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#43469]
Let's abstract the **social _preview_** components (only - not the other components!) in [`client/components/seo`](https://github.com/Automattic/wp-calypso/tree/4537033c6794449ce0a10b69d72daf5fa658d553/client/components/seo) and publish them as an NPM package, so they can be re-used in for Gutenberg in Jetpack.

See 84-gh-dotcom-manage

**Comment by getdave** [comment]
Here's [the documentation for adding new packages](https://github.com/Automattic/wp-calypso/tree/master/packages).

**Comment by getdave** [comment]
We should also consider what we need to do to handle

https://github.com/Automattic/wp-calypso/tree/4537033c6794449ce0a10b69d72daf5fa658d553/client/components/seo-preview-pane

**Comment by getdave** [comment]
It looks like migrating the `ReaderPreview` component to `npm` could be more complicated as it's [fairly tightly coupled to Calypso core](https://github.com/Automattic/wp-calypso/pull/44170#issuecomment-659342245). 

How do we feel about leaving that where it is and only moving the following preview components:

* Facebook.
* Twitter.
* Search.

**Comment by obenland** [comment]
I think that makes sense!

**Comment by getdave** [comment]
Note that we need to update the references to these components in

* `client/components/share`
* `client/components/seo-preview-pane/`.
