### ISSUE TITLE
FSE Plugin: Block Patterns with custom font size are broken

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#43478]
I've noticed the block patterns with a custom font size don't seem working as expected in Atomic and my local install (Gutenberg 8.3.0 & FSE 1.10).

**For example:**

This is how the pattern looks in Simple site.
<img width="1873" alt="Screenshot 2020-06-19 at 13 06 14" src="https://user-images.githubusercontent.com/908665/85130995-e0064080-b22d-11ea-9ee3-bb06aecd82bb.png">

However, this is how it looks in Atomic and local install. Notice the font size in the numbers.
<img width="1873" alt="Screenshot 2020-06-19 at 13 08 56" src="https://user-images.githubusercontent.com/908665/85131154-2c518080-b22e-11ea-98f7-42027a0d4457.png">

A brief look in the markup suggested to me that the `"customFontSize":XX` no longer works, and a new instance that I made with a custom font size has `{"style":{"typography":{"fontSize":XX}}}` instead.

@ianstewart @alaczek

**Comment by razvanpapadopol** [comment]
The reported issue can be reproduced only within the editor. So there are probably some overwrites happening. If I preview the post with the block pattern outside the editor it looks fine.

**Comment by Addison-Stavlo** [comment]
> A brief look in the markup suggested to me that the "customFontSize":XX no longer works, and a new instance that I made with a custom font size has {"style":{"typography":{"fontSize":XX}}} instead.

This makes some sense.  Some blocks in core have transitioned to the `__experimentalFontSize` [hook](https://github.com/WordPress/gutenberg/blob/2e639e45705ecf706c9c854133b493fd0a4ac0cb/packages/block-editor/src/hooks/font-size.js).  I think mainly paragraph and heading have this so far, but a handful of FSE blocks (site-title, post-author, etc.) will have these in the near future as well.

Where these blocks may have had a `customFontSize` attribute, the custom sizes are now saved under what you noted: `{"style":{"typography":{"fontSize":XX}}}`.  Named font sizes such as "large" etc. are still saved under the attribute `fontSize` as a string.  

Blocks that have this behavior have the `__experimentalFontSize` flag [enabled in the supports object of their block.json file](https://github.com/WordPress/gutenberg/blob/8b949bf8bea871a493637f68c17a36df70e263ba/packages/block-library/src/paragraph/block.json#L35).
