### ISSUE TITLE
Verse Block: Font in Editor view is different from Published view

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#43487]
#### Steps to reproduce

1. Add [Verse Block](https://en.support.wordpress.com/wordpress-editor/blocks/verse-block/) to a Page or Post on WordPress.com site
2. Type any text
3. Click Preview or Publish and view the result

The issue is only present on WordPress.com in the Editor view. With Gutenberg plugin v.8.3 at https://jurassic.ninja/ the font is in the editor is the same as in the Preview or Published view.

#### What I expected
The font in Editor view to be the same as in Published view

#### What happened instead
The font in Editor view is different from Published view. It's just the same font as in the [Paragraph Block](https://en.support.wordpress.com/wordpress-editor/blocks/paragraph-block/), instead, it should be similar to the [Preformatted Block](https://en.support.wordpress.com/wordpress-editor/blocks/preformatted-block/) font.

#### Screenshot / Video
**WordPress.com Editor view vs Published page view**

![Markup 2020-06-19 at 17 21 28](https://user-images.githubusercontent.com/39308239/85150673-1f935380-b253-11ea-8fe1-306ece6b04cf.png)

**WordPress.com Editor vs Gutenberg plugin v.8.3 at https://jurassic.ninja/**

![Markup 2020-06-19 at 17 28 37](https://user-images.githubusercontent.com/39308239/85150704-2a4de880-b253-11ea-96bf-b0b030d73658.png)

#### Context / Source

#dogfooding, #manual-testing, #user-report during Quick Start session 3076327-zen

**Comment by jeyip** [comment]
Confirmed that the:
- WordPress.com site editor verse block _**does not**_ display the same font styling as the published view.
- Self-hosted (atomic) site editor **_does_** display the same font styling as the published view

**Comment by noahtallen** [comment]
This is an issue for Varia themes. It does not exist with a different theme, like Seedlet. So the issue is probably caused by Varia editor CSS.

**Comment by noahtallen** [comment]
This should be fixed now. Let me know if you still see issues @zdenys
