### ISSUE TITLE
Change homepage URL for newly created sites

### ISSUE THREAD

**Issue by eoinsav** [Automattic/wp-calypso#43497]
When creating a new site, there are example pages created with generic content.

The Homepage is a static page with content and is given this URL: `example.com/blog/`

Then there is a Blog page created that is given this URL: `example.com/blog-2/`

We get users wanting to change their Blog page to `example.com/blog/` but the Homepage URL needs to be changed first. This is awkward because the Homepage URL can only be changed by using Quick Edit in WP Admin.

#### Steps to reproduce

1. Create a brand new site at https://wordpress.com/start/
2. Try and change the Blog page URL from `/blog-2/` to `/blog/`
3. You won't be able to because the Homepage is given the `/blog/` URL.
4. You will need to change the Homepage URL using the Quick Edit button in WP Admin first.

#### What I expected
I expected the Homepage to have the URL `example.com/home/` and the Blog page to have `example.com/blog/`

#### What happened instead
The Homepage is given the URL `example.com/blog/` and the Blog page is given the URL `example.com/blog-2/`

#journey #anecdote #narrative #reallife #flowsharing

#manual-testing #user-report

**Comment by ianstewart** [comment]
I think this could be fixed in the Headstart annotations by changing the `post_name` value for the Home page to `home` and the `post_name` value for the Blog page to `blog`

cc @niranjan-uma-shankar because I think you might have worked on this last and might know which of the Headstart annotations need changing.

**Comment by niranjan-uma-shankar** [comment]
Thanks, I've added it to our project board.

**Comment by niranjan-uma-shankar** [comment]
Needs review: https://code.a8c.com/D45473

**Comment by claudiucelfilip** [comment]
LGTM

**Comment by niranjan-uma-shankar** [comment]
Deployed
