### ISSUE TITLE
Editor: Unable to edit pages on a site with Site Redirect and Domain subscriptions

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#43505]
It is not possible to edit pages on a site which has Site Redirect and Domain subscriptions.

#### Steps to reproduce

1. Make sure the site has Domain and Redirect subscription.
2. Go to My site > Site > Pages and open one of the pages for editing.
3. Observe the issue:

![Markup on 2020-06-21 at 13:42:51](https://user-images.githubusercontent.com/25105483/85223713-2b068c00-b3c5-11ea-98e9-9b4dc34d67cc.png)

#### What I expected

The Gutenberg editor loads correctly.

#### What happened instead

The Gutenberg didn't load.

#### Browser / OS version

Doesn't seem to be browser / OS related.

#### Context / Source

#user-report, #3066520-zen

**Comment by cathymcbride** [comment]
@ivan-ottinger can you still repro this?

**Comment by ivan-ottinger** [comment]
Hey @cathymcbride, I just followed the steps and I cannot reproduce the issue anymore. I think we can close the issue.

**Comment by cathymcbride** [comment]
awesome! Thanks @ivan-ottinger !!
