### ISSUE TITLE
Stats: Allowing user role to view stats doesn't give access to Store Stats

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#43529]
#### Steps to reproduce the issue

1. Have a WooCommerce store running on your Jetpack site with Stats enabled. 
2. You'll also need a test WP.com account connected to another local account on that site.
3. Allow (for example) the Editor role to be able to view stats.
4. Grant the Editor role to your local test account on the site.
5. Using your local test account, log into wp-admin and connect JP to your WP.com test account.
6. Notice: your WP.com account can correctly view web traffic stats on the site, but the Store stats are not loaded on WordPress.com.

Beware of https://github.com/Automattic/jetpack/issues/8161 when testing this.

Came across a question about this in 3077212-zen and confirmed with my test site that "sharing" the Store stats in this way isn't possible.

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
