### ISSUE TITLE
Keyboard Shortcuts for Alignment (Left, Center, Justify, Right) 

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#43539]
The classic editor has Keyboard Shortcuts for alignment which are:

**On Macs:** 

- Option + CTRL + L – Align left
- Option + CTRL + R – Align right
- Option + CTRL + J – Justify
- Option + CTRL + C – Align center

**On Windows:** 

- Alt + Shift + l = Align Left
- Alt + Shift + j = Justify Text
- Alt + Shift + c = Align Center
- Alt + Shift + r = Align Right

But unfortunately, they've been removed from the new Gutenberg editor. 

Hoping we can get these added to the new editor as some of our users depend on them. Especially, those who rely on Screen Readers and the use of Keyboard Shortcuts to easily layout content and build their sites. 

#### Context / Source

#user-report  hc-11654868 /  zd-3075338

**Comment by cathymcbride** [comment]
Closing this in favor of the core issue: https://github.com/WordPress/gutenberg/issues/25682
