### ISSUE TITLE
Billing History: update billing history design to be more consistent with current Calypso patterns

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#4353]
The [billing history](https://wordpress.com/me/billing) screen could use a visual update. It's been a while since it was first done and hasn't really been touched since. Mostly things just need to be updated to be more consistent with current Calypso patterns and not look outdated.
### Receipts table

| Before | After |
| --- | --- |
| ![receipts-old](https://cloud.githubusercontent.com/assets/448298/14080599/2e485498-f4d4-11e5-92e8-d24b503d53a7.png) | ![receipts-new](https://cloud.githubusercontent.com/assets/448298/14080602/32192c28-f4d4-11e5-9c7c-e08234c20ebb.png) |

The header on the receipts table looks clunky, and the headings don't line up with the columns below due to left padding. I'm proposing a cleaner, slimmed down UI. There's a lot going on in this table and the more we can do to keep it light and airy, the better. The style here was pulled from the [comment notifications settings](https://wordpress.com/me/notifications/comments).
### Filter popovers

| Before | After |
| --- | --- |
| ![filters-old](https://cloud.githubusercontent.com/assets/448298/14080745/f17b454c-f4d4-11e5-8235-8c75e5a31c6a.png) | ![filters-new](https://cloud.githubusercontent.com/assets/448298/14080748/f552f6ec-f4d4-11e5-9ee0-082a121accf4.png) |

The popovers to filter the receipts (both "Date" and "All Apps") are inconsistent with existing Calypso UI patterns. Let's update those.
### Manage Credit Cards

| Before | After |
| --- | --- |
| <img width="603" alt="screen shot 2016-03-28 at 11 09 50" src="https://cloud.githubusercontent.com/assets/448298/14080876/abbbecc2-f4d5-11e5-9fe7-4cddaa884181.png"> | <img width="608" alt="screen shot 2016-03-28 at 11 12 42" src="https://cloud.githubusercontent.com/assets/448298/14080958/0963031a-f4d6-11e5-88f5-e9ec305ce43e.png"> |

Here I reduced the size of the card images. They're overpowering and pulling too much focus. I also tightened up spacing of everything, removed the border around the list of cards (box-in-a-box), and decided to use a compact button for the delete action.

The name on the card has been removed as well. As a user, personally, the name on the card doesn't provide much value to me since they're all my name. But maybe in the case of a business they need to see the name. Is this something we should keep or is it not really necessary?

**Comment by folletto** [comment]
This was addressed in part in #4664, currently looks like this:

![screen shot 2016-05-20 at 16 32 39](https://cloud.githubusercontent.com/assets/4389/15433070/a4bd4d9c-1ea8-11e6-9987-4c91b7760718.png)
