### ISSUE TITLE
Race Condition in Desktop-Calypso Build (EPIPE error)

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#43533]
### Description

Desktop CI occasionally fails due to a corrupt source build. This manifests as a runtime error where the app is unable to resolve `assets-fallback.json` (see #43498 for an example).

<p align-"center">
<img width="600" alt="Screen Shot 2020-06-22 at 1 35 50 PM" src="https://user-images.githubusercontent.com/8979548/85318016-4b9a1900-b48d-11ea-8553-1e71fcee1522.png">
</p>

Closer investigation confirms the following:

There is some sort of race condition that causes a corrupted desktop source to be built ([link](https://app.circleci.com/pipelines/github/Automattic/wp-desktop/16978/workflows/173a1cb8-f16b-4935-82ef-59e7d501ed80/jobs/65459)).

Even though the `build source` step was marked as successful, it in fact failed in the `check-npm-client` step with the error:

```
$ check-npm-client && node ${NODE_ARGS:---max_old_space_size=8192} ./node_modules/webpack/bin/webpack.js --config client/webpack.config.js --display errors-only && yarn run build-languages-if-enabled
 
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
 
    at ChildProcess.target._send (internal/child_process.js:806:20)
 ```

The desktop app was then compiled with a corrupt source build. Is this `EPIPE` error somehow related to the `assets-fallback.json` file that couldn't be resolved?

Not sure if this a `max_old_space_size` issue (i.e. we're bumping into RAM constraints again), but OOM errors are typically marked with `process killed`, not `EPIPE`, so memory constraints don't appear to be the case here. Now that the desktop app is using a code-split Calypso, I would imagine the RAM concern is largely mitigated? If it is not a memory issue then it's some other race condition in the build system.

Edit: I'm not sure why `build-languages-if-enabled` is included in the desktop build - my understanding is it's a RAM-intensive process. Perhaps removing this from the desktop might mitigate (or at least rule out) any potential out-of-memory errors caused by this script? But again - the `EPIPE` error seems to indicate something else is going on.

**Comment by jsnajdr** [comment]
This error:
```
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
```
likely happens when a parent process tries to send a message to a child process. The child was probably killed (maybe because of OOM).

That's all I an contribute at this moment 🙂

**Comment by nsakaimbo** [comment]
Have not observed this error since CircleCI agent for wp-desktop-source build was bumped to higher-RAM Machine executor in #44675. Closing.
