### ISSUE TITLE
Language picker: focus and select state display bug

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#43532]
When editing your interface language, the focus state and select state for the language buttons clash:

![image](https://user-images.githubusercontent.com/437258/85318020-4f2da000-b48d-11ea-836d-fc5eb2cc7721.png)

We should perhaps use the @wordpress/component focus and select styles (with dotcom colors) for this UI.

**Comment by simison** [comment]
> We should perhaps use the @wordpress/component focus and select styles (with dotcom colors) for this UI.

@Automattic/ganon has core-component version of this UI in the works! 🎉  

https://github.com/Automattic/wp-calypso/pull/43132

It'd be lovely to see a team take that and try move it to Calypso. It would be excellent first step to try core elements in more substantial way in Calypso. cc @griffbrad

**Comment by rickybanister** [comment]
That'd be wonderful.

**Comment by rickybanister** [comment]
related, we would be able to close this ticket as well: #41938

**Comment by ramonjd** [comment]
Language picker has been merged (it's behind a feature flag for now as it needs some design eyes and UI tweaks)

https://github.com/Automattic/wp-calypso/pull/43132

**Comment by yansern** [comment]
Is the feature flag `?flags=gutenboarding/language-picker` ready to be removed at this point?
See: pbAok1-dn-p2

**Comment by simison** [comment]
@yansern I did some testing and looks like it's working well. Let's roll it to production! Thanks for the nudge.

**Comment by simison** [comment]
This was reverted in https://github.com/Automattic/wp-calypso/pull/49683

**Comment by simison** [comment]
I'll close this and have more focused task instead: https://github.com/Automattic/wp-calypso/issues/49987
