### ISSUE TITLE
InlineHelp: getInlineHelpSearchResultsForQuery() should not receive query as a second argument

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#43549]
Rightly this selector a query string as a second argument of the function. This seems to be unneeded since it's possible to pick up the query value from the state too, through the getQuerySearch() selector.

**Comment by mreishus** [comment]
Jerry noted we can do the same trick for `isRequestingInlineHelpSearchResultsForQuery`.  It takes `searchQuery` as a second argument, but it could just pull it from the state.  Is this something else we should do, @retrofox @getdave ?
