### ISSUE TITLE
My Home: Reduce and balance elements on task card

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#43540]
Pulling out some great feedback from @pablohoneyhoney regarding the new illustrations in the context of the task cards on My Home.

> In the environment of this home banner, have you tried smaller sizes or position? With all the colors and its scale, it does distract from the action at hand (my eye travels to find focus between title, CTA and the illustration), also considering it is surrounded by complex UI in Calypso all together. Maybe worth reducing and balancing the elements a bit more.

![image](https://user-images.githubusercontent.com/448298/85331983-18638400-b4a5-11ea-9dfc-c10c11daae63.png)

See pbAPfg-qS-p2#comment-1095

**Comment by sfougnier** [comment]
Revisions to the task card to decrease the height to 272px, revise padding, typography, and illustration placement. [Figma link](https://www.figma.com/file/2v3gyTfWHBDS9iT7aoVCB4/Customer-Home-Checklist?node-id=269%3A10397)

**Desktop - no time estimate**
<img width="1440" alt="Home - Task card no time" src="https://user-images.githubusercontent.com/67021691/99732286-3c93b300-2a8d-11eb-8cfc-1f411446e3a3.png">

**Desktop - with time estimate**
<img width="1440" alt="Home - Task card with time" src="https://user-images.githubusercontent.com/67021691/99732288-3d2c4980-2a8d-11eb-8728-5ba7cccbbfa4.png">

**Desktop - complete**
<img width="1440" alt="Desktop - Task card complete" src="https://user-images.githubusercontent.com/67021691/99732283-3b628600-2a8d-11eb-8097-115e963030b6.png">

**Mobile - all 3 states**
<img width="1205" alt="Screen Shot 2020-11-19 at 5 23 51 PM" src="https://user-images.githubusercontent.com/67021691/99732395-706ed880-2a8d-11eb-96e6-260481f4b722.png">

**Comment by jordesign** [comment]
I guess part of the question for @jeffgolenski is whether any design work in My Home is going to be using the existing card designs (as is) or considering them as *part* of the redesign?

**Comment by jeffgolenski** [comment]
@jordesign I'll be using the existing card illustrations in the redesign—most likely. Sizing and location may change though. TBD!

**Comment by jordesign** [comment]
Using the existing card designs seems sensible given the speed of the work we're doing. Good call!

**Comment by autumnfjeld** [comment]
I think we can close this, do you agree @simison

**Comment by jordesign** [comment]
Making the call to close this - based on the coming redesign.

pbAok1-2L4-p2
