### ISSUE TITLE
Unable to log in to an existing account via Gutenboarding

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#43569]
#### Steps to reproduce

1. Starting at URL: wordpress.com/new
2. Go through the gutenboarding flow and in the "Save your progress" step, click on "Already have an account? Log in".
3. Give log in credentials to an existing wpcom account.

#### What I expected

To log in and continue with the editing my site

#### What happened instead

Stuck at this point:

<img width="1679" alt="Screenshot 2020-06-23 at 5 13 01 PM" src="https://user-images.githubusercontent.com/1269602/85399901-313b6a80-b575-11ea-9a50-82fb404dd4ff.png">

#### Browser / OS version

Chrome / macOS

**Comment by simison** [comment]
After giving (non-a8c) credentials at login, I end up in Gutenboarding plans grid, where if I continue I end up in editor. Same happens weather I picked free plan or paid plan  in the flow.

<img width="1815" alt="image" src="https://user-images.githubusercontent.com/87168/85401622-fdefe000-b562-11ea-81f4-4abd8e320566.png">


Seeing only this in console:
```
[Report Only] Refused to frame ’https://jetpack.com/' because it violates the following Content Security Policy directive: “frame-src ‘self’ https://public-api.wordpress.com https://accounts.google.com/“.
```
