### ISSUE TITLE
Reader: users without sites get perpetual loading page

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4356]
#### Steps to reproduce
1. Starting at URL: login as user with no sites (e.g., bobraliantest200)
2. Go to http://calypso.localhost:3000

#### What I expected
I should see something there, maybe the Discover list. Not sure if this is simply indicative of a user that has no followed sites or if it's specific to users that have no sites of their own. Either way we should show some list of posts or at a minimum some message suggesting they follow some sites.

#### What happened instead
The followed sites selection is highlighted in the sidebar and it doesn't load anything. There are no relevant errors in the console.

#### Browser / OS version
osx firefox, safari, and chrome.

#### Screenshot / Video
![perpetual loading](https://cloudup.com/cz6Im-nvpDB+)

/cc @blowery

**Comment by blowery** [comment]
Hrm. Have not been able to repro this yet, even with Bob's test user.

**Comment by lancewillett** [comment]
I did some testing today with a user with no sites and wasn't able to repeat this one. Closing for now — feel free to re-open later if it comes up again.
