### ISSUE TITLE
Gutenberg: Incorrect "Most used" blocks in the block inserter

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#43568]
Originally reported by @johnHackworth (p1592825492026300-slack-create-platform-squad). 

The "Most used" section in the block inserter is not showing correct blocks. In the test blog, it displays:
<p align='center'><img src='https://user-images.githubusercontent.com/1451471/85397643-33410180-b554-11ea-8e0a-c7ccfbefe91a.png' width='300px' /></p>

...but the only ones that are being actually used are basic paragraph block and JP's Business Hours block.

There's a suspicion that the [original core behavior](https://github.com/WordPress/gutenberg/blob/cbef07223613a6f1d59f4035dbfc6dd1598129ba/packages/block-editor/src/store/selectors.js#L1236-L1265) for this functionality might be affected by us re-setting the categories. AFAIK, we're currently doing that in [Jetpack](https://github.com/Automattic/jetpack/blob/master/extensions/shared/block-category.js) and [FSE](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/new-blocks-showcase.js#L34). Let's investigate that.

cc @mtias

**Comment by mtias** [comment]
I believe this is addressed now.
