### ISSUE TITLE
Reader: some Gutenberg blocks don't display correctly

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/wp-calypso#43595]
Some blocks don't appear correctly when shown in the Reader.

While I do think that the Reader should keep a consistent visual (and not apply some random colors that the post authors might use) there are a few improvements that we could make when showing them (an example is a table, that doesn't display any border).

(*JFYI: I'm creating that as a single issue so we can keep the discussion centered here. If we decide to fix one type of block or just a small amount of them I can open another issue.*)

- [ ] Cover block
- [x] Button block - #43779 
- [x] Headings (Settings) - #46720, D51569-code
- [x] Group block
- [x] Latest posts block
- [x] Tables  #44276
- [x] File block
- [x] Pay with Paypal block - https://github.com/Automattic/jetpack/pull/17256

### Cover block

How it looks on Reader: https://wordpress.com/read/blogs/159889361/posts/964
How it looks on the site: https://made4testing0318.blog/2020/04/15/cover-blocks-2/

### Button block

How it looks on Reader: https://wordpress.com/read/blogs/159889361/posts/1363
How it looks on the site: https://made4testing0318.blog/2020/06/02/many-buttons/

### Headings (Settings)

How it looks on Reader: https://wordpress.com/read/blogs/159889361/posts/984
How it looks on the site: https://made4testing0318.blog/2020/04/16/headings-paragraphs/

### Group Block

How it looks on Reader: https://wordpress.com/read/blogs/159889361/posts/1037
How it looks on the site: https://made4testing0318.blog/2020/04/17/group-block-with-nested-groups/

### Latest Posts Block

How it looks on Reader: https://wordpress.com/read/blogs/159889361/posts/1003
How it looks on the site: https://made4testing0318.blog/2020/04/16/latest-posts-block/
On comments `latest-posts` don't appear at all in the Reader

### Tables

How it looks on Reader: https://wordpress.com/read/blogs/165243437/posts/1717
How it looks on the site: https://charlietest12345.blog/2020/06/23/table-block/

### File block

How it looks on Reader: https://wordpress.com/read/blogs/159889361/posts/1219
How it looks on the site: https://made4testing0318.blog/2020/04/29/core-file-block/

**Comment by tophertoy** [comment]
@leandroalonso I'd be keen to start this one off by looking at the "button block" if that works for you.

I've started something, it's work in progress at the moment.

**Comment by tophertoy** [comment]
@leandroalonso are you looking for just font improvements with "headings" or did you have another things in mind (padding etc)?

![Screenshot 2020-07-03 16 36 13](https://user-images.githubusercontent.com/570876/86432325-6d2bb800-bd4b-11ea-8021-6b648231eb39.png)

**Comment by leandroalonso** [comment]
@tophertoy very good question.

For me, we want to respect the styles the content creator has added but we still want to keep the Reader's look (which shows the content in a more generic way).

In that case, I'm wondering if it makes sense to show the colors that the user has defined — IMHO we shouldn't. Personally, I'd display the header with the correct size and alignment and that's it. Wdyt @bluefuton?

**Comment by bluefuton** [comment]
> Personally, I'd display the header with the correct size and alignment and that's it.

👍 I agree! Sounds like the best approach.

**Comment by thehenrybyrd** [comment]
Another block which doesn't load properly in Reader is the [Pay with PayPal](https://wordpress.com/support/pay-with-paypal/) button.
This is problematic for folks who use the Pay with PayPal block to ask for donations on blog posts, for instance. Visitors viewing the post via the Reader see no button for donation.

Here's how that looks in a blog post:
![image](https://user-images.githubusercontent.com/15107387/89407329-41736780-d727-11ea-83ac-26062c566352.png)

However, in Reader, there is no button, only the amount:
![image](https://user-images.githubusercontent.com/15107387/89407350-4d5f2980-d727-11ea-9dbe-ee321aeb32c5.png)

@leandroalonso let me know if this should be a separate issue :)

**Comment by bluefuton** [comment]
Thanks @thehenrybyrd! I've added the Pay with Paypal block to the todo list in the description.

**Comment by mtias** [comment]
Spacers should probably not be included here.

**Comment by bluefuton** [comment]
> Spacers should probably not be included here.

That's a good call 👍 I don't think they make sense in the context of Reader.

**Comment by designsimply** [comment]
I tested cover blocks as part of beta testing for the WPAndroid 15.8-rc-2 beta release and found that cover blocks still don't display background images in the Reader on the web. Note: the cadence for spacing around these blocks is awkward on the front-end though this could be related to the theme.

Reader|Front-end
---|---
![Screen Shot 2020-09-28 at Sep 28 2 43 02 PM](https://user-images.githubusercontent.com/1119271/94484151-31ad5800-0199-11eb-869f-2e7a545b140e.png)|![Screen Shot 2020-09-28 at Sep 28 2 43 32 PM](https://user-images.githubusercontent.com/1119271/94484141-2eb26780-0199-11eb-9f09-8c99eec6e4a6.png)

<sup>Tested with Firefox 81.0 on macOS 10.15.6.</sup>

**Comment by worldomonation** [comment]
Looks like it was referenced in an active issue, so I will remove the Stale label for now.

**Comment by roo2** [comment]
I created simple PRs for the "Latest posts", "Group" and "File" pages. Not to fully support the block features but just to ensure they are presentable. #73201, #73202, #73203

I don't think we should do much about the cover block because 
* We don't have easy access to the image link
* It doesn't look too broken at the moment
* We want to encourage a consistent visual experience and if we bring styling into the cover block it might be quite overpowering
