### ISSUE TITLE
Gutenboarding: Awkward plans scaling

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#43606]
Currently the way the Plans page works it that the columns take up the entire width. This leaves the plans boxes to scale weirdly at some viewpoints as noted by @ianstewart:
![image](https://user-images.githubusercontent.com/2896062/85524787-c50a4680-b608-11ea-9501-128e02ad787e.png)

In the original design I was intending on having the plans boxes all the the same size to avoid that one of the plans become bigger than others:
![image](https://user-images.githubusercontent.com/2896062/85525038-f97e0280-b608-11ea-8b42-85061a3b2e30.png)

Would be great if we could fix this at some point 😄 

cc @rickybanister

**Comment by razvanpapadopol** [comment]
Fixed when switched to single-column accordion style plans grid: https://github.com/Automattic/wp-calypso/pull/44299
