### ISSUE TITLE
Security: Send informational email for password change

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#4360]
URL: https://wordpress.com/me/security

What I expected: An informational email will be sent to me when I changed my password.

What happened instead: Password changes. But informational email is not sent to my email address.

Steps to reproduce: 
1. Go to https://wordpress.com/me/security.
2. Enter a new password in the New Password text box.
3. Click Save Password button.

Browser OS version: I tested in Firefox 45.0.1 in OSX Yosemite 10.10.5. But this enhancement request is across all the browsers and OSes.

Screenshots/Video: NA

**Comment by lancewillett** [comment]
Thank you for raising this improvement.
