### ISSUE TITLE
Security: Ask for the current password to allow password change

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#4361]
Many (if not most) sites require an additional authentication before changing a password, by entering the existing password first. Calypso doesn't ask for the existing password before I can change it.

URL: https://wordpress.com/me/security

What I expected: Ask for the current password before I can change the password.

What happened instead: Current password is not required to change the password.

Steps to reproduce: 
1. Go to https://wordpress.com/me/security to change the password.
2. There is no existing password box.

Browser OS version: I am using Firefox 45.0.1 in OSX Yosemite 10.10.5. But this enhancement request is applicable for all the browsers and OSes.

Screenshots/Video: Not applicable.

**Comment by lancewillett** [comment]
Thanks for the suggestion.
