### ISSUE TITLE
Extract shared `SupportSearch` components and use in FAB and My Home support search instances

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#43615]
Currently there are x2 implementation of "support search" in Calypso:

1. The "Inline Help" or "FAB" version (blue `?` icon in bottom right)
2. The "Get help" card on the My Home page.

The FAB version was implemented first and uses [the `InlineHelp` components](https://github.com/Automattic/wp-calypso/tree/4c757209c2d3a843926ebc8729274ac9859cf453/client/blocks/inline-help). Then we introduced the My Home version which now also makes use of the `InlineHelp` components. 

The components were written and styled to work on the FAB popover versions. However, they are shared with the My Home version. This tightly couples the My Home version to the FAB version and makes both instances vulnerable to changes intended for the other only.

This will end up in a situation where we have an ever-expanding API surface in the `InlineHelp` components that deal with search. This is because any change to FAB or My Home instances will have to be conditionally applied based on the other.

We can fix this by extracting a set of shared components that deal with "searching support" only. This should a case of extracting the following components:

* [`InlineHelpSearchCard` ](https://github.com/Automattic/wp-calypso/blob/4c757209c2d3a843926ebc8729274ac9859cf453/client/blocks/inline-help/inline-help-search-card.jsx).
* [`InlineHelpSearchResults`](https://github.com/Automattic/wp-calypso/blob/4c757209c2d3a843926ebc8729274ac9859cf453/client/blocks/inline-help/inline-help-search-results.jsx)
* [`PlaceholderLines`](https://github.com/Automattic/wp-calypso/blob/4c757209c2d3a843926ebc8729274ac9859cf453/client/blocks/inline-help/placeholder-lines.jsx) - shoud this be a [top level component](https://github.com/Automattic/wp-calypso/tree/master/packages/components) instead of being attached to "search"?
* [Contextual Help utils](https://github.com/Automattic/wp-calypso/blob/4c757209c2d3a843926ebc8729274ac9859cf453/client/blocks/inline-help/contextual-help.js).

These could be renamed along a common namespace of `SupportSearch` and then used within the FAB and My Home support search instances.

They should be very basic and only provide the absolutely minimum of styles and configuration. 

We should also write Component tests with Jest to cover these components. We will also have to update the e2e tests to accommodate the new markup.

**Comment by retrofox** [comment]
Also considering move the selectors with are located in the inline-help but clearly belong to support search.

**Comment by getdave** [comment]
We should also consider improving the accessiiblity whilst we're at it

https://github.com/Automattic/wp-calypso/issues/43617

**Comment by getdave** [comment]
@retrofox let's consider if/how it's possible to break this down into smaller steps.

**Comment by retrofox** [comment]
Also, maybe we should be moving the data query component straight into this new one. It should take over of requesting data.

**Comment by retrofox** [comment]
> Also, maybe we should be moving the data query component straight into this new one. It should take over of requesting data.

InlineHelp: Improve requesting data flow. #43624

**Comment by retrofox** [comment]
https://github.com/Automattic/wp-calypso/issues/43753

**Comment by obenland** [comment]
Closing, the most important issues have been fixed.
