### ISSUE TITLE
Site Picker: cannot start a new post by tapping on a site in the site picker

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#4362]
Steps to reproduce:

1. Go to https://wordpress.com/ using a device runing iOS 9.3
1. Tap the pencil icon
1. Tap a site name

<strong>Result:</strong> the site picker closes and a new post is not started, note: a workaround for me is to press down firmly to trigger "Peek and Pop" (3D Touch)

<strong>Video:</strong> [1m10s](https://cloudup.com/cLNvDby0_Qj)

**Comment by ryanboren** [comment]
Same when invoking the site picker from <- Switch Site.

**Comment by ryanboren** [comment]
I don't have 3D touch, so I don't have a workaround.

**Comment by kriskarkoski** [comment]
I reproduced on my iPhone 6/iOS 9.3/Safari 9 from both the pencil icon as well as the Switch Site option. I also don't have 3D touch so no workaround besides direct URL navigation.

**Comment by designsimply** [comment]
[Note: edited out the 3D touch part of the report because it was wrong.]

/hat tip @DanReyLop for letting me know it's an iOS 9.3 bug, see http://www.zdnet.com/article/ios-9-3-update-breaks-links-in-safari-messages-and-mail-apps/

**Comment by DanReyLop** [comment]
I can confirm this is also an issue in Android (Nexus 5, Android 6.0 Marshmallow, Chrome).

Also in Chrome desktop, using the devtools to simulate _any_ mobile device, this bug can be reproduced too.
