### ISSUE TITLE
Editor: Remove "Convert to blocks" modal and move to Classic block toolbar

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#43626]
> As a user using the Classic block for content in the block editor,
> I want to be able to convert blocks when I'm ready to do so,
> So that I can continue using the classic block as needed without being interrupted.

Related to https://github.com/Automattic/dotcom-manage/issues/87

Discussion in pb5gDS-DR-p2

## Requirements

- [ ] 1. Remove the "Convert to blocks" dialog that is displayed when a user loads a post created in the Calypso/Classic editors in iframed block editor - https://github.com/Automattic/wp-calypso/pull/43900
- [ ] 1. Add the "Convert to blocks" action to the toolbar of the classic block (requires Gutenberg PR) - https://github.com/Automattic/wp-calypso/pull/43902 & https://github.com/WordPress/gutenberg/pull/23704

![image](https://user-images.githubusercontent.com/1699996/86414240-fcbc6280-bc88-11ea-8fb1-c7a72a14e0a1.png)

![image](https://user-images.githubusercontent.com/1699996/86414281-18276d80-bc89-11ea-89ca-b84a0984b455.png)

**Comment by davemart-in** [comment]
> should we use a popup or similar to surface this option? e.g. show a tooltip in the block options that "You can always do this later in the block settings?

Let's take this one step at a time. My vote would be to hold off on adding this extra popup. Let's see what get's surfaced in HE interactions, then we can adjust if folks are getting confused.

**Comment by creativecoder** [comment]
Note, this issue is on hold while we discuss a plan in pb5gDS-DR-p2

**Comment by creativecoder** [comment]
I've revised the title and issue requirements based on the discussion in pb5gDS-DR-p2
