### ISSUE TITLE
Earn: Fix types for $token_subscription->end_date

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#43638]
As a follow up to https://github.com/Automattic/wp-calypso/pull/43417 let's make sure that one-time payments return the expected date format as other payments. Take care to not regress current lifetime payments (Longreads membership).

Recurring:
```
(
    [end_date] => 2020-07-18 23:09:52
)
```

One Time
```
(
    [end_date] => 1624057639
)
```

Investigation note from @n3f 
> > Is this expected @Automattic/earn ?

> Apparently.  Looking in `MembershipsBillingTest::test_memberships_paymentintent_subscribe_valid_jwt_token` there is a test that validates the end_date should be in the '2020-07-22 21:01:10' format.  While in `MembershipsBillingTest::test_memberships_paymentintent_onetime` it checks for the `end_date` to be greater or equal to `time() + 360 * 24 * 3600`.

**Comment by gwwar** [comment]
I dug a bit further here, and I'm not certain that end_date is being recorded as an entry in the DB, rather than calculated from the next renewal _interval. So I'm not sure if work here is needed, but we can still tidy code a bit if we wish. If we do end up tidying this, we'll still want to keep the int/date checks since folks may have generated tokens that contain end_dates as a unix int timestamp.

To verify if a subscriber can view content a JWT token is generated after subscription and set in a session cookie `jp-premium-content-session` with a payload similar to
```
"{"iss":"http://wordpress.com/earn","sub":"XXXXXXX","user_id":XXXXXX,"subscriptions":{"338":{"end_date":"2020-07-24 22:31:09"},"347":{"end_date":1624573870}}}"
```

Tracing this the token is originally created when, we hit `mu-plugins/earn/api/v1/authentication/class-auth-endpoint.php` in wpcom

I also think there's dead code in FSE plugin near https://github.com/Automattic/wp-calypso/blob/0da9f816d1fff7a46bfa74a0cb5725c05400ceb8/apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/class-wpcom-offline-subscription-service.php#L63. (Basically JWT token generation should happen from the auth mu-plugin, though we'll want to confirm with Earn before deleting anything).

**Comment by mmtr** [comment]
> I also think there's dead code in FSE plugin near
> 
> https://github.com/Automattic/wp-calypso/blob/0da9f816d1fff7a46bfa74a0cb5725c05400ceb8/apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/class-wpcom-offline-subscription-service.php#L63

I think that's still needed. Tokens generated in `mu-plugins/earn/api/v1/authentication/class-auth-endpoint.php` are used in normal browser session (a user visits a published page/post that contains premium content), but `class-wpcom-offline-subscription-service.php` handle other scenarios where the user is offline / token is not available (new post email notifications or users access a protected post via the reader).

**Comment by mmtr** [comment]
> Tracing this the token is originally created when, we hit mu-plugins/earn/api/v1/authentication/class-auth-endpoint.php in wpcom

Also found the cookie is set as well in the front-end:

https://github.com/Automattic/wp-calypso/blob/3b5e1fc5f35106531f31a821a767c4589c949e5b/apps/full-site-editing/full-site-editing-plugin/premium-content/view.js#L17-L25

**Comment by mmtr** [comment]
> So I'm not sure if work here is needed, but we can still tidy code a bit if we wish. If we do end up tidying this, we'll still want to keep the int/date checks since folks may have generated tokens that contain end_dates as a unix int timestamp.

I wonder the same. The benefit is not that great provided we need to keep the different checks so I'm leaning towards leave thing as they are.

**Comment by gwwar** [comment]
Let's maybe punt for now. I'll close this one out for now.
