### ISSUE TITLE
Editor: Mobile: post is visible below the Actions menu if you tap "Actions" while the keyboard is open

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#4363]
Steps to reproduce:
1. Start a new post at https://wordpress.com/post/new using a mobile device
2. Add enough content to the post so you need to scroll a bit to reach the bottom
3. Tap the Actions button
4. Scroll down

<strong>Result:</strong> you can scroll past the menu and reveal the post—I expected not to be able to interact with the post directly while using the Actions menu

<strong>Video:</strong> <a href="https://cloudup.com/cHPedgoI8zf">38s</a> tested with Safari iOS 9.3 on iPhone 6S

Related: #1673

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Confirmed this is still an issue, exactly as shown above on iOS.  On Android Chrome, however, it manifests differently.  I don't see the editor contents below the action menu when scrolling down, but there is some bleed through under the master bar when the URL omnibox is out of view  But here it's only a momentary visual glitch while holding my finger down.  As soon as I let go everything snaps back into place and obscures the editor.

https://cloudup.com/c3MuCUha2bt

**Comment by rachelmcr** [comment]
This is resolved with the current Post Settings sidebar (which replaced the Action menu).

#bug-scrub #pre-gutenburg-bug-purge
