### ISSUE TITLE
Site Editor: slow iframe loading causes redirection to wp-admin

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43642]
#### Steps to reproduce

1. Create a new test FSE site through horizon flow.
2. Notice that the site editor loads with the correct Calypso route.
3. After a brief interval it redirects from iframe directly to wp-admin.

This error also pops up in the console, but it might be unrelated:

```
Uncaught (in promise) ReferenceError: _currentSiteId is not defined
```

**Comment by Addison-Stavlo** [comment]
After exploring briefly, it doesn't seem to be coming from the calypso side.

Moreover, I'm finding that I am unable to reproduce this on my sandbox.  Without the site sandboxed, it is consistently breaking out of the Iframe.  With the site sandboxed, there is no iframe breakout.  🤔 

I recall we noticed a similar issue a couple months ago for a small window of time (2-3 hours?).  While investigating the issue cleared itself up and everything started working as intended.  I am not quite sure what is going on here...

**Comment by Addison-Stavlo** [comment]
This hasn't seemed to clear up like last time.  I vaguely remember @sirreal suspecting something about lag and admin accounts when we were discussing the similar issue in the past (forgive me for not remembering exactly).  It would be nice if we could test this with a standard user account to see if it has the same issue, but I don't think we currently have an easy way to do that for the dotcom site editor? 🤔

**Comment by sirreal** [comment]
> … @sirreal suspecting something about lag and admin accounts

I vaguely remember as well, but I was recalling conversations I wasn't really a part of. @p-jackson does this ring a bell?

#41006 may be related.

**Comment by Addison-Stavlo** [comment]
> #41006 may be related.

That was my first thought too.  Unfortunately that doesn't seem to be where it is coming from.

**Comment by Addison-Stavlo** [comment]
It seems to correspond to the timer / location.replace Marko pointed out here - https://github.com/Automattic/wp-calypso/pull/43683/files

Increasing to 10sec seems to work for him, however I need to increase it to like ~40sec to not experience the breakout.

**Comment by jeyip** [comment]
Addison's comments from [our discussion](https://a8c.slack.com/archives/CHN6J22MP/p1593534188120800?thread_ts=1593532466.116700&cid=CHN6J22MP) in slack:

"My main hunch is that some change from the last couple weeks (somewhere on the dotcom side, perhaps something with how we integrated seedlet / gutenboarding? ) has amplified the performance problem to this level we are now noticing.  Beyond that, I'm not sure.

Middleware functions in the calypso route or potentially some things unnecessarily running from the FSE plugin/app itself may be hurting the loading performance.  Those have been in place with the site editor loading for a few months without this level of issue, but perhaps new changes in those could be responsible as well."

**Comment by jeyip** [comment]
For reference, this recently merged PR https://github.com/Automattic/wp-calypso/pull/43248 adds the actual logic to redirect to wp-admin.

**Comment by jeyip** [comment]
What I've investigated while trying to replicate the production performance issues on a `wpcom` sandbox:
- Searched for potential flags that are sandbox specific when loading Gutenberg in `wp-content/mu-plugins/wpcom-gutenberg-load.php`
- Searched for differences between loading the post editor and site editor
- Tested key differences between production and sandboxes like staticized subdomains and concatenated CSS and JS. ([#Important Differences between a Sandbox and Production](https://fieldguide.automattic.com/sandboxes/))

**Comment by ockham** [comment]
> Oddly enough, I can now replicate the issue consistently on one of my sandboxed sites but not the other (Both are recently created FSE enabled sites from horizon).

This would be quite interesting, since it might give us a way to actually replicate outside of production. Let's try to pin-point differences -- can you list blog stickers attached to both sites?

**Comment by jeyip** [comment]
Taking a look at the site stickers now 👍

**Comment by jeyip** [comment]
@ockham It turns out I don't have access as a network admin anymore. I'm trying to get that setup, but in the meantime, here are the sites I was working with:

bigmacsiteeditor4.wordpress.com (can replicate the problem)
bigmacsiteeditor5.wordpress.com (cannot replicate the problem)

**Comment by vindl** [comment]
> Oddly enough, I can now replicate the issue consistently on one of my sandboxed sites but not the other (Both are recently created FSE enabled sites from horizon). I was planning to spend time exploring why, but open to other suggestions.

Another thing to try would be to turn on xdebug and profile execution on a sandboxed site where it can be reproduced. PCYsg-21A-p2

**Comment by vindl** [comment]
This was resolved in https://github.com/WordPress/gutenberg/issues/23662.
