### ISSUE TITLE
Site Editor: block list width looks off

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43640]
When testing the site editor on Dotcom, I noticed that the block list container is not using full width.

This makes the page layouts that contain full width blocks look off compared to what's shown in Gutenboarding preview and on front end.

<img width="1679" alt="Screenshot 2020-06-24 at 18 56 32" src="https://user-images.githubusercontent.com/1182160/85599587-eee55c80-b64c-11ea-97c6-25459208ce43.png">

**Comment by vindl** [comment]
This actually looks like a core issue so we might transfer the discussion there.

**Comment by ockham** [comment]
> This actually looks like a core issue so we might transfer the discussion there.

Yeah, I think I can repro the same in Core when testing with the `twentytwenty-blocks` themo.

I think this probably is a default that comes from the post editor, and needs some tweaking for the _site_ editor, where we want the full width by default.

**Comment by ockham** [comment]
I _think_ that this is coming from the theme. In the case of seedlets, I think it's

```css
max-width: var(--responsive--aligndefault-width);
```

in `seedlet/assets/sass/blocks/utilities/_editor.scss`.

That rule can be overridden with `data-align="full"`. I'll play a bit more with this; we might need to think about some more general changes to how the Site Editor overrides theme rules (similar to how the Post Editor does).

**Comment by ockham** [comment]
In a post content editor context, the Cover Block has `data="full"` set, which makes it displayed at full width there. That same attribute seems to be missing in the site editor context :thinking:

**Comment by ockham** [comment]
> In a post content editor context, the Cover Block has `data="full"` set, which makes it displayed at full width there. That same attribute seems to be missing in the site editor context

To be precise, it's not the Cover Block itself, but a wrapping `<div class="wp-block" data-align="full" />`, which is coming from `BlockListBlock`: https://github.com/WordPress/gutenberg/blob/42ddcc69a23736d1f48b891c1a0d839892aae31a/packages/block-editor/src/components/block-list/block.js#L164-L168
