### ISSUE TITLE
Editor: Remove switch to "Switch to Classic Editor" links

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#43658]
Once the WordPress.com/Calypso editor is deprecated, "Switch to Classic Editor" will no longer function as there won't be an editor available for switching.

## Requirements

1. Remove the "Switch to Classic Editor" menu item from the "More Tools & Options Menu" in the block editor
1. Remove the "Switch to Classic Editor" button from the inline help dialog within Gutenframe (iframed block editor)
1. Removal is behind the `editor/after-deprecation` feature flag for testing
1. When we roll out the deprecation to users, we can gradually add groups of users that won't see the menu item and button

<img width="150" alt="image" src="https://user-images.githubusercontent.com/1699996/85634119-534def00-b640-11ea-94b0-b411ea301f1c.png"><img width="150" alt="image" src="https://user-images.githubusercontent.com/1699996/85634148-619c0b00-b640-11ea-9177-46620a0f979b.png">

**Comment by creativecoder** [comment]
I think this might require restoring https://github.com/Automattic/wp-calypso/pull/43538

**Comment by aaronrobertshaw** [comment]
Closing this issue, as all Calypso and Jetpack PRs to hide the switch editor links have now been merged.

**Comment by creativecoder** [comment]
I see [2 more places in the code](https://opengrok.a8c.com/source/search?q=switchToClassic&defs=&refs=&path=plugins&hist=&type=&project=trunk) where there is logic for showing the "Switch to Classic Editor" link, but I can't find where this code is being executed.

I don't think we need to update these now, but these should be removed when we get to that step of the project.
