### ISSUE TITLE
Gutenberg v8.4.0: Image editing broken for .com

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#43676]
Image editing seems to be broken for simple sites. Setting aspect ratio and zoom is functional, but I can’t rotate or save the edited image.

⚠️ This is wpcom specific and doesn't happen on AT sites - everything seems to be working well there (p7DVsv-8Te-p2#comment-29768).

#### Steps to reproduce

1. If you're an Automattician, see p7DVsv-8Te-p2 for how to get v8.4.0 on your test site,
2. Add an Image block to your site,
3. Upload/select an image,
4. Try to rotate - nothing should happen and you should see an error in the JS console:
   ```
   Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
   ```
5. Try to scale and zoom the image - they should work fine,
6. Now try to click `Apply` - you should see a pop-up on the left-bottom side of the screen saying:
   ```
   Unable to perform the image modification. Please check your media storage.
   ```

#### Context / Source

p7DVsv-8Te-p2#comment-29742

Related: https://github.com/Automattic/wp-calypso/issues/43525

**Comment by WunderBart** [comment]
[`Apply` endpoint](https://github.com/WordPress/gutenberg/blob/23e187cc4bdc5edc79d808ba023620be3cf03993/packages/block-library/src/image/image-editor.js#L174) does not exist when trying to apply edited image in .com:

URL: 
```
https://public-api.wordpress.com/wp/v2/sites/168063301/__experimental/richimage/152/apply
```
Response: 
```
{
  "body": {
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": { "status": 404 }
  },
  "status": 404,
  "headers": []
}```

**Comment by WunderBart** [comment]
I've tested with the [latest image editing API endpoint (stabilizing) updates](https://github.com/WordPress/gutenberg/commits/315707cde51607b6439541d0f40d53a8523c0414/lib/class-wp-rest-image-editor-controller.php) and the response is still `rest_no_route`, unfortunately. This is an example endpoint that is now being called with those updates:

```
https://public-api.wordpress.com/wp/v2/sites/168063301/media/191/edit?_envelope=1&_gutenberg_nonce=af90b317c1&_locale=user

**Comment by sirreal** [comment]
Experimental routes can be tracked in #43736 

This still doesn't work when it's route is fixed: pMz3w-bDu-p2

**Comment by sirreal** [comment]
Fixed via r210701-wpcom.
