### ISSUE TITLE
Page Templates: some templates are missing side margins

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#43682]
There are missing side margins in at least [two templates](https://github.com/Automattic/wp-calypso/pull/43561#issuecomment-649343138).

Mentioned in https://github.com/Automattic/wp-calypso/pull/43561#issuecomment-649262758

Steps to reproduce:
- go to [/new/design](https://wordpress.com/new/design)
- click on 6th design: https://cloudup.com/c_2M84z0Uvs
- check preview: https://cloudup.com/cGjDqKe6JJt
- after creating the site, check editor: https://cloudup.com/ccc9dGE85dm
- outside of the editor, the margins are fine

Related: Automattic/block-experiments#103

**Comment by razvanpapadopol** [comment]
Update: https://github.com/Automattic/wp-calypso/pull/43561#issuecomment-649629971

**Comment by razvanpapadopol** [comment]
Should be fixed in https://github.com/Automattic/block-experiments/pull/108
@Addison-Stavlo @andrewserong could you re-test this?

**Comment by andrewserong** [comment]
Thanks for the ping @razvanpapadopol! I've just tested these out now and in the preview, editor, and then in the created site, those affected designs are looking good now. I'll close out this issue.
