### ISSUE TITLE
Editor: Toolbar exits editor content area when scrolling up with a featured image set

### ISSUE THREAD

**Issue by ryanboren** [Automattic/wp-calypso#4368]
With a featured image set and enough content to go below the fold, the toolbar stays pinned to the masterbar and exits the content area when scrolling the editor down and then back up.

#### Steps to reproduce
1. Starting at URL: /post/...
2. Set a featured image
3. Add enough content to go below the fold
4. Scroll down until the editor toolbar pins to the masterbar
5. Scroll back up
6. Notice that the toolbar remains pinned to the masterbar until almost scrolled to the top, then it jumps down beneath the Visual and HTML tabs where it should be

#### What I expected

When scrolling back up, the editor toolbar should pin to the visual and html tabs as they go past. This happens correctly when a featured image is not set.

#### What happened instead

The editor toolbar remained pinned to the masterbar instead of pinning to the editor tabs as they passed.

#### Browser / OS version

Mac OS, Chrome. The latest versions as of this writing.

#### Screenshot / Video

A narrative with a screenshot: https://test.wordpress.com/2016/01/25/editor-toolbar-leaves-editor-when-scrolling-up-macnchrome/

![screen-shot-2016-01-25-at-12-10-11-pm](https://cloud.githubusercontent.com/assets/2047747/14090374/963e29da-f4ff-11e5-8f15-c8541b5bbe7f.png)

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Closing, appears to be fixed.  Tested on OSX 10.11.4, Chrome v50

![wp-calypso-4368](https://cloud.githubusercontent.com/assets/7233112/15405074/64391236-1dce-11e6-87b2-26985d41f6f0.gif)
