### ISSUE TITLE
Mobile: disabled forms are unreadable

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#437]
If you encounter a form field which is disabled on mobile, it's extremely difficult to read, and in the right (wrong?) light, it just looks like a grey box. We need to make it so that you can at least make out what it says.

Steps to repeat:

1. Go to wordpress.com in a mobile browser, like Mobile Safari.
2. Log in, go to a site in My Sites.
3. Click on Settings (URL: https://wordpress.com/settings/general/lancetest35.wordpress.com)
4. Scroll to "Address and Visibility" and see that "Site Address" input field isn't readable.

<img src="https://cloud.githubusercontent.com/assets/66797/11325435/e8d2c65a-910a-11e5-89dc-8e679340d2ad.png" width="480" />

**Comment by lancewillett** [comment]
Confirmed this is still a bug. :/ We should update this as it's an a11y and usability nightmare. 

<img width="578" alt="unreadable-fields-ios" src="https://cloud.githubusercontent.com/assets/66797/13717257/a90f161a-e79d-11e5-9e62-47928e347f79.png">

(iOS simulator, iPhone 6+.)

**Comment by lancewillett** [comment]
This should be a quick CSS change, right? Good for Janitorial or first change.

**Comment by josephfusco** [comment]
Looks like a normalization issue with Safari iOS disabled inputs having `opacity: .4`.

See [19]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#Browser_compatibility

**Comment by josephfusco** [comment]
Should be good to close this now :)
