### ISSUE TITLE
Coming Soon & Private on Atomic: Private temporary AT site caused media files import issue

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#43715]
When an Atomic site is reverted while its on Private/Coming Soon mode, the temporary Atomic site that generated from Blog RC will be set to Private/Coming Soon by default (following the current status of the Atomic site during the revert.)

This cause an issue when the HE needs to import contents from the temporary AT site to the reverted (simple) site/the user's site. Private/Coming Soon mode locks up the uploads folders from access, caused media files not migrated properly (still pointing to the temporary AT site path file).

#### Steps to reproduce

1. Revert an Atomic site while the site is in Private/Coming Soon mode
2. Create temporary AT site from Blog RC
3. Create .xml export file from the temporary AT site (/wp-admin > Tools > Export)
4. Import the .xml file to the reverted (now Simple) site (My Site > Tools > Import)
5. Posts and pages are imported properly, but none on media files imported and not populating Media library. The images that appearing on the posts/pages, if any, is pointing to the temporary AT site URL.

#### What I expected
Everything imported properly; pages, posts, categories, media files regardless the site's privacy settings.

#### What happened instead
Media files not imported. However, it seems like an issue on core as it's discussed on [this external article in 2017](https://wordpress.stackexchange.com/questions/117344/failed-to-import-media). As of now, what we can do is to ensure the AT site is set to Public *before* the revert.

Maybe we can make the temp AT site to be automatically set to 'Public'?

#### Context / Source

#dogfooding 
#user-report 

See internal report on: p9F6qB-5sb-p2

**Comment by simison** [comment]
Note that coming soon mode is public by default now.

After launching customers can of course set site private, so perhaps this is a generic "private site" issue?

**Comment by kdevnel** [comment]
This may no longer be an issue but it may impact the work being done on the Atomic Downgrade process.

**Comment by retnonindya** [comment]
... ... I forgot I had this GH issue 🥲 So sorry! 

It seems like this issue is no longer exists. @jmdodd has upgraded the downgrade process so no matter what the actual site's status is, the temporary AT site will always be public. However, yep, we can keep this in mind to ensure the downgrade works smoothly.

**Comment by kosiew** [comment]
> It seems like this issue is no longer exists.

Closing this. Please reopen if you have additional context to add.
