### ISSUE TITLE
EPIC: Integrate Patterns API MVP with Gutenboarding

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#43714]
## Outcome

A user should see translated design previews and translated content in their final, created site

## Tasks
- Update/refactor the `WPCOM_JSON_API_Template_Demo_Endpoint` to display translated block content
- Generate /use mshots to show screenshots of translated demo sites at the design step
- Ensure that we're headstarting the new sites with the translated design content https://github.com/Automattic/wp-calypso/issues/44727

**Comment by lsl** [comment]
> Update/refactor the WPCOM_JSON_API_Template_Demo_Endpoint to display translated block content

D46257-code D45750-code

**Comment by ramonjd** [comment]
> Ensure that we're headstarting the new sites with the translated design content

This might entail creating a class that builds a headstart annotation dynamically, which we then pass to headstart to use.

For example, in `sites/new` we grab the original site content, run each page through the patterns parser, save it into something resembling the headstart annotation data model.

We'll have to make sure that the following are translated:

- menus
- categories/tags (if any)
- social menu items
- anything else we see in a normal headstart annotation
