### ISSUE TITLE
Gutenberg v8.4.0: Navigation block broken for .com

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#43736]
The Navigation block is stuck in the placeholder state, throwing 404 for the [`__experimental/menus`](https://github.com/WordPress/gutenberg/blob/23e187cc4bdc5edc79d808ba023620be3cf03993/packages/core-data/src/entities.js#L76) endpoint:

![image](https://user-images.githubusercontent.com/1451471/85880541-79a89180-b7dc-11ea-9290-291b93635754.png)

⚠️ This is wpcom specific and doesn't happen on AT sites - everything seems to be working well there.

#### Steps to reproduce

1. If you're an Automattician, see p7DVsv-8Te-p2 for how to get v8.4.0 on your test site,
2. Add a Navigation block to your site,
3. See the spinner loading the nav placeholder menu forever.
4. Open JS console to see a `rest_no_route` error.

#### Context / Source

- https://wordpress.slack.com/archives/C02QB2JS7/p1593184777298800
- p1593187952013300-slack-api
- p7DVsv-8Te-p2#comment-29790

Related: https://github.com/Automattic/wp-calypso/issues/43676, https://github.com/Automattic/wp-calypso/issues/43525

**Comment by getdave** [comment]
The Menus endpoint was added when we enabled the ability to create Navigation blocks from existing WP Menus. I think that Blocks are allowed to depend on experimental features so this is technically valid.

I think perhaps we might need to focus on allow Dotcom to support these experimental endpoints?

**Comment by sirreal** [comment]
Figuring out __experimental routes p3hLNG-174-p2

**Comment by sirreal** [comment]
Fixed by pMz3w-bDy-p2 / r209932-wpcom.
