### ISSUE TITLE
Page Layouts: Layouts Breaking due to User's Account Language on Simple Sites

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#43732]
@nickpagz recently worked with a user that reported broken page layouts.  

After review, we identified that the cause was due to the user's WPCOM account language settings.  When set to Español, certain page layouts break. They break in the preview and carry over when you choose to use the selected page layout.

Specifically, this occurred when the Maywood theme was active and the user tried to select the Maywood, Shawburn, Twenty Twenty, or Balasana home page layouts on a Simple site.

We have yet to test with other languages, themes, or page layouts. I could not reproduce on Atomic.

#### Steps to reproduce

1. Set your interface language to Español on https://wordpress.com/me/account
2. Create or select a Simple WPCOM site with the Maywood theme
3. Create a new page or change the page layout of an existing page.
4. Attempt to use the Maywood, Shawburn, Twenty Twenty, or Balasana home page layouts.
5. See broken layouts and various browser console errors. Screenshots below.

#### What I expected

For page layouts to work across user language settings.

#### What happened instead

Broken page layouts.

#### Browser / OS version

Various -- tested across MacOS, Windows, Chrome, and Firefox. 

#### Screenshot / Video

Example of broken page layout:
![image](https://user-images.githubusercontent.com/4887830/85872029-3b3fb200-b79d-11ea-8c58-856f56ff3067.png)

Various console errors:
![image](https://user-images.githubusercontent.com/4887830/85872103-4b579180-b79d-11ea-86e6-4cb3de9c6433.png)

#### Context / Source
Slack discussion: p1593182066424300-slack-wpcom-support

22195250-hc
 #user-report

**Comment by ianstewart** [comment]
Appears related to https://github.com/Automattic/jetpack/issues/15776 cc @sirreal

**Comment by iamtakashi** [comment]
This is happening because the homepage of those four themes are missing, and it falls back to the default. I opened this issue  when I audited the homepage templates: https://github.com/Automattic/wp-calypso/issues/42368. 

This is one of the todo items there:

> Locate the translations (or make them if it's never translated) for Balasana, Maywood, Shawburn, Twenty Twenty homepages. Test, fix, and deploy the translations so that we stop the confusing experience with the fallback.

**Comment by JoshuaGoode** [comment]
> I opened this issue when I audited the homepage templates: #42368.

Excellent! I totally missed that issue already being open.

**Comment by ianstewart** [comment]
Closing this issue as I believe we've corrected it by serving layouts as patterns from our patterns site. cc @andrewserong
