### ISSUE TITLE
(?P) InlineHelp: Fix help search visual issues

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#43753]
There are some visual issues to fix. Let's tackle them as part of this enhancement process.

* it changes its height while requesting
* the horizontal line gets narrow when searching

![help-search-visual-issues](https://user-images.githubusercontent.com/77539/86000508-05403f00-b9e4-11ea-84e3-51dd48a91b9c.gif)

**Comment by obenland** [comment]
I also noticed on iOS it zooms into the textfield once you tap'd into it. Maybe worth looking into, as well.

**Comment by cpapazoglou** [comment]
> I also noticed on iOS it zooms into the textfield once you tap'd into it. Maybe worth looking into, as well.

Using `font-size >= 16px` will stop zooming in iOS. They consider anything < 16px in inputs bad for accessibility.
