### ISSUE TITLE
My Home: Add Tracks events for each card impression.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#43767]
While we currently track call-to-action click events for various cards, we don't have any way of better understanding what users are seeing for cards. Let's add Tracks events for each individual card impression.

**Comment by gwwar** [comment]
I think @kwight noted we might track this from the API side as well, but it should be a gentler introduction into the wpcom codebase.

**Comment by kwight** [comment]
In #44054, I've backed away from the idea of doing it server-side, since unit tests and any library use on sandboxes will artificially bump numbers without adding some sort of additional handling. Since what we really want is to know how many times users viewed cards, let's do it in Calypso, right as they're rendered to the user.
