### ISSUE TITLE
checkout: Design considerations of Ebanx and dLocal

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#43777]
Current checkout collects product-specific details (e.g. domain and gsuite contact details) separately from the billing contact information, while composite checkout (currently) conflates the two. So far this hasn't been a problem, because none of the supported flows depended on these two kinds of information being different. Some of the localized payment methods seem to require this to be more explicit.

To see why this is an issue, it helps to consider a specific use case: suppose I am purchasing a domain registered to a business in the US, but want to use a Brazilian credit card to pay for it. Brazilian payments go through the Ebanx processor and require some additional contact information. But (in the current flow) if I have chosen US as my country in step 2, checkout has no way of knowing that it needs to show me the Brazil-specific credit card form, and thus my purchase would fail.

Possible ways to fix this:

1. Split the current contact details step into two, "billing" information (used for taxes and differentiating on the payment processor) and "product" information (domain and gsuite details). We could ask for billing info first, defaulting to ZIP+country only and showing country-specific fields as needed. The product contact details step would be hidden if it's not needed, and pre-filled with data from the billing info step if it is needed. Pros- separates the two kinds of info; Cons- introduces an extra click if product contact info is required.

1a: Ask for product details first if we need it, and use this to prefill the billing details (could also have a checkbox on the form allowing the user to explicitly use the product details as billing details). Show this step as collapsed.

2. Keep the current product contact info step as is, but move the current billing info step (shown in the plan-only flow) to each payment method that requires it. Pros- Removes a step (kind of) for the plan only flow; Cons- adds billing information to all payment methods including apple pay and paypal; changing the country at this step necessarily clears the CC fields when switching between stripe and ebanx.

**Comment by fditrapani** [comment]
Just wanted to circle back here and say we discussed this over a zoom team call. Where did you all end up on this?

**Comment by michaeldcain** [comment]
@fditrapani, after you left the call, we settled on the following: https://github.com/Automattic/wp-calypso/issues/43812

Essentially, the current contact step would continue to operate as-is, and instead of adding the "use the same information for billing" checkbox to that step, we'd add it to the credit card field in the following step. Unchecking it would unfurl a longer contact form with the credit card fields. Leaving it checked would just use the information from the previous step.

What do you think about that approach?

**Comment by fditrapani** [comment]
Oh nice! yeah, good idea.

**Comment by michaeldcain** [comment]
Nice, since we have a consensus, I'm going to close the design discussion and we'll just track the work in #43812
