### ISSUE TITLE
Accessibility: Not possible to tab through dropdown menus using a keyboard

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#43786]
It's not possible to tab through options in a dropdown menu using your keyboard, which also makes it tricky for those using screen readers to navigate the options.

#### Steps to reproduce

* Starting at URL: https://wordpress.com/block-editor/post
* Add any block with options that need to be selected from a dropdown menu, such as the cover block or the WhatsApp block. I've highlighted the dropdown menu associated with the cover block in the following screenshot:

<img width="1081" alt="dropdown" src="https://user-images.githubusercontent.com/2998162/86098805-8a902600-baae-11ea-83ca-5954779f76be.png">

* Attempt to access the options from the dropdown menu using your keyboard.

#### What I expected

I expected to be able to tab through the different options using the tab key on my keyboard.

#### What happened instead

It's not possible to navigate through the different options in the dropdown menu using only your keyboard. Tabbing will bypass the menu and take you to the next element. This makes it hard for people who navigate the web using their keyboard or screen readers to set their language.

#### Browser / OS version

Chrome / macOS 10.15.5

#### Context / Source

#empathy #perspective

**Comment by simison** [comment]
Hi! This is an issue in the block-editor and not specific to WordPress.com — would you mind opening an issue at https://github.com/WordPress/gutenberg/issues ? Thanks!

**Comment by SiobhyB** [comment]
@simison, thanks! I found that there's already an open discussion around making an accessible select/dropdown component: https://github.com/WordPress/gutenberg/issues/16473 

I'll close this one.
