### ISSUE TITLE
Gallery Block Arrows do not work in safari

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#43780]
#### Steps to reproduce

1. Starting at URL: Open a post in the editor
2. add a gallery block 
3. add images
4. attempt to change order by clicking image then clicking arrow buttons

#### What I expected

arrow buttons to change gallery order

#### What happened instead
nothing 

#### Browser / OS version
This works in chrome and according to user used to work in Safari so this is likely a regression 

#### Screenshot / Video
https://d.pr/v/uu5smX
#### Context / Source
#userreport

**Comment by andrewserong** [comment]
Thanks for reporting this one @automattic-ian! Looks like a double-up of #40531, so I'll close this issue in favour of the earlier one.
