### ISSUE TITLE
Editor: access after Calypo editor deprecation

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#43803]
## Requirements

For a user in the editor deprecation group (`currentUser.inEditorDeprecationGroup`)

- Remove the customer home and ~~editor deprecation~~ notices
- User is directed to the iframed block editor when editing a post

**Comment by creativecoder** [comment]
Note, I've taken care of the editor deprecation notice in https://github.com/Automattic/wp-calypso/pull/438 (though it won't show anyway, when we redirect from the Calypso editor)

**Comment by creativecoder** [comment]
I had originally put "Redirect from the WordPress.com/Calpyso editor..." as a requirement. I think that's misleading as it's not really a redirect. Updated to read: "User is directed to the iframed block editor when editing a post"

Related to that, Explorers discussed that the easiest way to do this might be to update the server-side response so the editor preference for the web platform is always `gutenberg`. However, we need to keep in mind that #43802 needs to know if the user has the editor preference set to `classic` for a site. Discussion: p1593655932433800?thread_ts=1593655324.431000&cid=CKZHG0QCR-slack-explorers

cc @pablinos

**Comment by pablinos** [comment]
I think this is handled with a combination of #43917 and D45999-code. I've left #43917 as a draft for now, as I think there's something I'm missing, possibly related to mobile. But this approach does ensure that we preserve the editor setting so we can display further messaging when Gutenberg is displayed.

**Comment by scruffian** [comment]
This has been merged!
