### ISSUE TITLE
Like button text ".Be the first to like this" not translated to Arabic

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#43814]
#### Steps to reproduce

1. Starting at any WordPress.com Site
2. Enable the Like button via My Site > Tools > Marketing > Sharing Buttons
3. Change the site's language setting to AR-Arabic العربية
4. Open a Post with no likes on the Public site and look for the like button. 

#### What I expected

I expect "Be the first to like this" to be displayed in Arabic, which is set via the site's language. 

#### What happened instead

The text under the like button displays in English. 

#### Screenshot / Video

A screenshot of where this works (site language is in Spanish)
<img width="336" alt="Screen Shot on 2020-06-30 at 13-28-56" src="https://user-images.githubusercontent.com/29527450/86168628-b83c9580-bad5-11ea-807e-4b0480390d8a.png">

A screenshot of where this doesn't work and the site's language is set to Arabic : 
<img width="469" alt="Screen Shot 2020-06-30 at 1 30 23 PM" src="https://user-images.githubusercontent.com/29527450/86168756-e326e980-bad5-11ea-8d40-4e2fced4546e.png">

#### Context / Source

#user-report zd-3105983

If requesting a new feature, explain why you'd like to see it added.

**Comment by simison** [comment]
cc @Automattic/i18n

**Comment by autumnfjeld** [comment]
SPIKE: Might not have been submitted for translation. Maybe just kick the translation wheels.  Or is this from a FaceBook embed, a FB translation issue.  Let's do a spike to investigate.

**Comment by arthur791004** [comment]
I think we use the older version of [jed.js](https://s0.wp.com/_static/??/wp-content/js/jed/jed.js) and it got the incorrect value index of singular text for Arabic so that it cannot get the translation and fallback to English.

Here is related issue: https://github.com/messageformat/Jed/pull/29

> gettext() was failing for locales where the pluralization rules don't return 0 when given an n of 1. For example, the plural forms rule for Arabic is nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);, which, when given an n of 1, returns 1. Since the dcnpgettext() function was assuming an n of 1 when dealing with translations of singular keys, the logic would end up looking past the end of the array specified for that key.

**Comment by arthur791004** [comment]
@ash1eygrace We have fixed this issue!
