### ISSUE TITLE
Inline Help: Add events to admin search results

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#43843]
The following events are being fired when a user interacts with the Search FAB:

- calypso_inlinehelp_article_open
- calypso_inlinehelp_show
- calypso_inlinehelp_richresult_show

Since there will now be two groups of results following [Ramon's PR](https://github.com/Automattic/wp-calypso/pull/31903), can we add events to find out which links users interact with the most? Is it the support links or the admin links?

cc @davemart-in @Automattic/ajax @lcollette

**Comment by retrofox** [comment]
Totally doable. For now, we are tracking only the search event (when user types in the input element) in the `<HelpSearch />` component, located in the customer home page.
