### ISSUE TITLE
Enable search feature on People > Followers

### ISSUE THREAD

**Issue by bsanevans** [Automattic/wp-calypso#43854]
User would like to see the ability to search for Followers from **WordPress.com > My Sites > Manage > People > Followers** as you can for Team and Email Followers under the same People section.

21338209-hc (no need for follow up)

**Comment by ash1eygrace** [comment]
Request in hc-3447075

**Comment by kaitohm** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/50132
