### ISSUE TITLE
Media: Rename setMediaLibrarySelectedItems to selectMediaItems

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#43867]
Just recording this fast-follow to our reduxification work based on @flootr's suggestion of a much better name: https://github.com/Automattic/wp-calypso/pull/43811#discussion_r448825125

**Comment by flootr** [comment]
Keep it open. Will provide a PR.

**Comment by tyxla** [comment]
Nice. Adding low priority because it's just a naming one.
