### ISSUE TITLE
Auto Loading Homepages do not load a new homepage on atomic.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#43877]
#### Steps to reproduce
As reported and detailed on `p9F6qB-5v4-p2`

1. Starting with an atomic site.
2. Switch to an auto-loading-homepage theme.
3. Verify the homepage content remains unchanged.

#### What I expected
The homepage content to be replaced.

#### What happened instead
The homepage content stayed the same.

**Comment by katinthehatsite** [comment]
Reported by the user in 3111824-zen

**Comment by andrewserong** [comment]
I think there are some technical limitations to this one (p9F6qB-5v4-p2#comment-30687), but we might be able to do a workaround and instead of replacing the homepage content when the user clicks Edit Homepage, redirect them to the page layout picker. Not ideal, but at least it gets them to where they can select a layout?

**Comment by Addison-Stavlo** [comment]
It seems the auto-loading behavior has never worked on atomic.

> I think there are some technical limitations to this one (p9F6qB-5v4-p2#comment-30687), but we might be able to do a workaround and instead of replacing the homepage content when the user clicks Edit Homepage, redirect them to the page layout picker. Not ideal, but at least it gets them to where they can select a layout?

This is a good idea - for clarity this is being explored in #43933

**Comment by katiebethbrown** [comment]
Report in 23585313-hc

We are still showing the notice when activating the themes that says we are changing the layout and setting the original homepage as a draft followed by the call to visit the site or edit the homepage, but we aren't actually changing anything.

<img width="468" alt="ziEPea" src="https://user-images.githubusercontent.com/42279181/91075492-6575ea80-e5fb-11ea-89d4-b5d8c27557cf.png">

<img width="325" alt="CgVljM" src="https://user-images.githubusercontent.com/42279181/91075565-82aab900-e5fb-11ea-9c96-7cfb541dba33.png">

This is a disconnect for users moving from Simple to Atomic for sure. 

I would have expected that if we aren't changing the homepage for the user that we wouldn't be telling them we are. Could we at least look at changing that messaging if we can't make the templates auto-load?

**Comment by samiff** [comment]
Another in p1600114629254800-slack-C03TY6J1A

**Comment by noahtallen** [comment]
Let me know if this is still happening. I've just tested this, and it does not appear that we are displaying the "auto change homepage layout" dialogue any longer. It does appear that if I select "edit homepage" after activating a different theme, then I am given the option to switch to the new theme's homepage in the layout selector.
