### ISSUE TITLE
Site Editor: Reynolds layout not matching the front end on Seedlet blocks theme

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#43883]
There is a slight discrepancy between what's rendered in editor and front end for Reynolds layout in Seedlet blocks theme.

This is likely a theme issue that needs to be resolved, similar to https://github.com/Automattic/themes/pull/2204.

### Testing instructions

1. Apply D45778 and D45780 to your sandbox.
2. Create a new test FSE site and select the Reynolds layout.
3. Sandbox the newly created site.
4. Reload the site editor.
5. Notice the gaps between the cover images.

<img width="1679" alt="Screenshot 2020-07-03 at 01 10 24" src="https://user-images.githubusercontent.com/1182160/86416389-0b773980-bcca-11ea-8fb6-d1c77cd47e24.png">

**Comment by vindl** [comment]
@kjellr pointed us to this issue which might be related https://github.com/Automattic/themes/issues/2191.

**Comment by jeyip** [comment]
<img width="2048" alt="Screen Shot 2020-07-06 at 1 15 05 AM" src="https://user-images.githubusercontent.com/5414230/86571568-7d4bbf00-bf26-11ea-9aa5-063916d7b16e.png">

It seems like the styling problems we're seeing are margins that are intentionally applied to every block in the block-editor. After local testing, the overrides in https://github.com/Automattic/themes/issues/2191 that @kjellr is requesting will resolve the issue.
