### ISSUE TITLE
Make editing colors available to all users

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#43895]
In p7DVsv-8MQ-p2 @allancole brings up that we still restrict color customization on the Free and Personal plans and @supernovia proposed that we make color customization available to all users on all plans:

<img width="583" alt="Image 2020-07-05 at 11 56 05 AM" src="https://user-images.githubusercontent.com/5634774/86536602-ef84bb00-beb6-11ea-94fe-4e4f2a6eba0b.png">

Let's go ahead and make color customizations available to all users on all plans.

Can we get this picked up ASAP on Monday by someone on the gardening/janitor rotation (at least investigate what changes need to be made)

**Comment by supernovia** [comment]
Thank you! 🥳

**Comment by gwwar** [comment]
@kwight created D45998-code for Simple sites

**Comment by kwight** [comment]
Noting that updates to [this support page](https://wordpress.com/support/custom-design/custom-colors/) will be needed also.

**Comment by kwight** [comment]
I believe D45998-code is all that's needed for our platforms. Atomic sites already have business plans, and JP standalone sites don't require the Custom Colors theme files (this is done on dotcom through an `mu-plugin` of our own).

**Comment by kwight** [comment]
Fixed for Simple sites in D45998-code. Next, I'll need a followup for Atomic sites that handles downgraded users left on Atomic, but that should be a relatively small number.

**Comment by kwight** [comment]
Downgraded Atomic users being handled in https://github.com/Automattic/custom-colors/pull/13
