### ISSUE TITLE
Components: color contrast for counts in section nav collapsed

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#439]
Raised by @mtias 

Trash pickup, I feel it could just be white:

![image](https://cloud.githubusercontent.com/assets/548849/10338026/e73a2b9c-6d03-11e5-8550-89b83badc48d.png)

**Comment by lancewillett** [comment]
Closing as this appears to be fixed.

<img width="323" alt="screen shot 2016-05-26 at 11 02 50" src="https://cloud.githubusercontent.com/assets/66797/15584881/6aab6eee-2331-11e6-9b17-fca6d2f26726.png">

**Comment by mtias** [comment]
Heh, yes, changed it some time ago but didn't reference issue.
