### ISSUE TITLE
Sites: when you don't have access to change Site Icon in wp-admin, ... menu for current site is empty when open

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#4390]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/stats/insights/lancetest35.wordpress.com
2. Click the ellipsis menu next to the Home URL site link
3. You'll notice it opens (ellipsis menu goes vertical), but the area is blank.

![site-icon-missing](https://cloud.githubusercontent.com/assets/66797/14114376/96c03b3c-f58b-11e5-8389-75da2e965bc6.gif)

Testing here with Mac-n-Chrome on wpcalypso.

#### What I expected
I'd expect the ellipsis menu link to be hidden if there's nothing to show for this site + user.

#### What happened instead
The menu opens, empty. It's confusing. Feels like a bug.

CC @mtias since we discussed this today. :)

**Comment by folletto** [comment]
We should add the "Hide This Site" functionality there so it's not empty anymore. ;)

**Comment by lancewillett** [comment]
Now seeing more in this area: Site Settings link with a cog icon. 👍 

<img width="468" alt="screen shot 2016-05-04 at 2 54 51 pm" src="https://cloud.githubusercontent.com/assets/66797/15030623/30ebd912-1208-11e6-9a20-bd12a78b9f0b.png">


![screen shot 2016-05-04 at 2 54 46 pm](https://cloud.githubusercontent.com/assets/66797/15030621/2d67d912-1208-11e6-8aab-1b4c329f7179.png)
