### ISSUE TITLE
Navigation Block: Add Navigation Link button text doesn't change with dark background

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#43918]
#### Steps to reproduce

1. Create a new page
2. Add a Navigation block to the page
3. In the Block settings, either select the Dark layout, or change the color of the background and text for the block 

#### What I expected

That the Add Navigation Link button text would change to contrast with the background of the menu enough to be visible

[![Add Navigation Link button text in white](https://d.pr/i/NFn61b+)](https://d.pr/i/NFn61b)

#### What happened instead
The Add Navigation Link button text is shown in the same black color, making it impossible to read

[![Add Navigation Link button text in black](https://d.pr/i/SEE3qs+)](https://d.pr/i/SEE3qs)

#### Browser / OS version
macOS 10.15.5: Firefox 78.0.1, Chrome 83.0.4103.116
iPadOS 13.5.1: Safari
Windows 10: Edge 83.0.478.54

**Comment by kwight** [comment]
It looks like that label has been removed, or this was somehow dealt with in recent Gutenberg core updates (there is no text here beside the inserter icon).

<img width="910" alt="Screen Shot 2020-09-16 at 1 26 05 PM" src="https://user-images.githubusercontent.com/349751/93388999-60821080-f820-11ea-9731-9f4ed1e0f03f.png">
