### ISSUE TITLE
Reader: Not all smileys show up

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-calypso#4393]
Steps to reproduce

1. Visit this blog post: https://testjoen.wordpress.com/2016/03/29/final-emoji-test/
2. Compare with the Reader view: https://wordpress.com/read/feeds/46338202/posts/977972889
3. Notice how some of the smileys don't show up in the reader. 

Specifically these:

- `:)`
- `:roll:`
- `:mrgreen:`

The three smilies that aren't converted are WordPress core smilies. Those are images that are manually output by WordPress filters, images that are stored in `wp-includes/images/smilies`. Seems `wp-includes` is on our banned list: https://github.com/Automattic/wp-calypso/blob/f4a91abd58e9091e12bfb172badd8a60be7cbf9f/client/lib/post-normalizer/index.js#L210

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Closing, it looks like the smilies are there now, using OSX Chrome and Firefox:

<img width="285" alt="screen shot 2016-05-19 at 11 47 44 am" src="https://cloud.githubusercontent.com/assets/7233112/15399928/8f910d2e-1db7-11e6-8249-2e4cb1db2214.png">
