### ISSUE TITLE
Jetpack Search: correct naming in the checkout cart

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#43947]
Right now we show "WordPress.com Search" as the name of the product in the purchase cart. Everywhere else we use the name "Jetpack Search". We should use "Jetpack Search" and keep the branding the same.

All of the code fixes for this are on the server side (I think), so this is just to track the issue. @DavidRothstein is already working on a diff.

**Comment by DavidRothstein** [comment]
Note: The fixes here are indeed server-side (up for review now at D45930-code and D46131-code).

**Comment by gibrown** [comment]
Done and deployed
