### ISSUE TITLE
Media & Text block: linking Facebook videos converts the block to an embed

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#43966]
#### Steps to reproduce

1. Add a Media & Text block
2. Type in some text to the Content area
3. Hyperlink any or all text in the Content area to a Facebook video - I tested with [this video](https://www.facebook.com/watch/?v=555479965067133)
4. Publish

#### What I expected

Video/image on one side, and normal text on the other side, linked out to a Facebook video

#### What happened instead

On the [page I tested](https://kcswong.wordpress.com/test-fb-shortcode-issue/), the Facebook video appears by itself on the far left, as an embed. When I refreshed the editor after publishing, the Media & Text block appeared to be empty. 

A user came in to chat with this issue, and when I checked their page it seemed that the Media & Text block broke and prompted to resolve into HTML or blocks; converting it to blocks spit out the Facebook shortcode, but I haven't been able to replicate that part. 

As a workaround, I suggested they could try and use a link shortener like Bitly which helped. 

#### Screenshot

![showing embed pushed all the way to the left](https://d.pr/i/E5l03n+)
_Image link: https://d.pr/i/E5l03n_

#### Context / Source

#user-report

**Comment by tbradsha** [comment]
I'm unable to reproduce this now; @kcswong, can you see if it's working for you now?

**Comment by kcswong** [comment]
@tbradsha can't replicate it now either,  must've been fixed by something else! Will close.
