### ISSUE TITLE
Cover Block: Wave Styles Cover Up Text

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#43962]
#### Steps to reproduce

1. Create a page.
2. Add a Cover Block, give it a background color, and add some text to it, for example:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
3. Click the Cover Block - Styles, and choose Top Wave or Bottom Wave.
4. The styles do not adjust to the amount of text displayed, and the waves will cover up text.

#### What I expected
The wave styles to adjust depending on the text added to the block.

#### What happened instead
The wave styles make text unreadable, by hiding it underneath a wave. 

#### Browser / OS version
All
#### Screenshot / Video
![coverblockstyles](https://user-images.githubusercontent.com/30731356/86847691-9442fc00-c061-11ea-874c-637919f8b509.gif)

#### Context / Source

#user-report

**Comment by WunderBart** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/25866
