### ISSUE TITLE
Nav sidebar: add tooltip to the button that opens the sidebar

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#43975]
The (W) buton that opens the sidebar doesn't have a tooltip.

> It’s pretty scary to click things that aren’t obvious (and W logo is far from obvious).

pbAok1-185-p2#comment-2299

I was thinking the tooltip something like "Show recent pages" / "Show recent posts".

The `<Button>` component has a prop for setting the tooltip so that should be straighforward.

The text may need to be set by `wpcom-block-editor` using a filter so we can get the correct translated text. Because I don't know how translations work in the FSE plugin.

Part of #41298

**Comment by autumnfjeld** [comment]
@p-jackson  It looks to me like this has been completed.  Should we close this issue? Or are there any remaining loose ends with regard to the (W) button?

![Screen Shot 2020-09-10 at 10 32 43](https://user-images.githubusercontent.com/5665959/92668037-06310d80-f351-11ea-8daa-ab3e00a6b1cb.png)

![Screen Shot 2020-09-10 at 10 32 53](https://user-images.githubusercontent.com/5665959/92668034-04674a00-f351-11ea-9a0f-f6ec6b7e9bb0.png)

**Comment by p-jackson** [comment]
Yep! Done ✅
