### ISSUE TITLE
Fix schema for `client/state/preferences/schema.js` to ensure user prefs are persisted to IndexDB

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#43984]
Unrelated, but I found this in testing. Serenity missed this in the initial implementation but looks like the schema for `client/state/preferences/schema.js` needs to be relaxed to allow a boolean or object with the following shape, since we used the `dismissable-card` naming scheme in `wp-content/lib/home/cards.php#L144`.

@getdave let me know if you'd be interested in tidying that here or in a follow up. Basically this means we're throwing out indexedDB state for user preferences currently. This isn't harmful, but it defeats the purpose of trying to persist reducer state

<img width="1103" alt="Screen Shot 2020-07-07 at 2 30 20 PM" src="https://user-images.githubusercontent.com/1270189/86848428-d6b90880-c062-11ea-8549-383072099ebc.png">

cc @kwight @mmtr

_Originally posted by @gwwar in https://github.com/Automattic/wp-calypso/pull/43861#issuecomment-655161329_

**Comment by getdave** [comment]
@gwwar this is in our backlog and awaiting triage to see when it can be addressed. It might be a good candidate for janitors as well.

**Comment by gwwar** [comment]
closed by https://github.com/Automattic/wp-calypso/pull/44266
