### ISSUE TITLE
InlineHelp: show admin results without waiting for the API results

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#43989]
It's possible to show the admin results without waiting by the endpoint response.

<img src="https://user-images.githubusercontent.com/77539/86926010-f1918880-c107-11ea-9807-7d21e081d6d4.png" width="400px" />

It will improve the UX using the support component.

**Comment by retrofox** [comment]
Actually wondering how to deal with both states in terms of visually. One of them is shown while the other ones are still loading? It's like a combination of placeholders and result items list.

**Comment by retrofox** [comment]
> Actually wondering how to deal with both states in terms of visually. One of them is shown while the other ones are still loading? It's like a combination of placeholders and result items list.

cc @jancavan

**Comment by cpapazoglou** [comment]
It seems to me that pointing the user to our admin sections would (should) be more relevant than to support articles. Having said that, I would suggest flipping the sections
![](https://cln.sh/r1nQwW+)

and actually showing the following while it loads
![](https://cln.sh/xwy303+)

What do you think @jancavan ?

**Comment by jancavan** [comment]
@retrofox @cpapazoglou I tried throttling my connection, but both results still show up at the same time for me. How long is the delay typically? It would be great though if we could have them show up at the same time.

Thanks for the suggestion! I think the support docs should get priority. I imagine users using the Help FAB to learn more about something vs using it as a simple way-finding tool. And our admin results are still quite limited at the moment.

Would it be possible to display the support docs heading at least, like so?

![Screen Shot 2020-07-09 at 1 28 25 PM](https://user-images.githubusercontent.com/4924246/87087511-12c9a600-c1e8-11ea-8abb-61c9a25d558e.png)

This at least gives the users the idea of what's coming up vs just displaying animated bars.

**Comment by retrofox** [comment]
> Would it be possible to display the support docs heading at least, like so?

yes, totally doable.

> This at least gives the users the idea of what's coming up vs just displaying animated bars.

:+1:

**Comment by jordesign** [comment]
Closing this as it is stale, and unlikely to be a factor with the new Help Center which is in progress.
