### ISSUE TITLE
Gutenboarding: Change name of `vertical-whitelist` to remove problematic language

### ISSUE THREAD

**Issue by saramarcondes** [Automattic/wp-calypso#43996]

**Comment by saramarcondes** [comment]
@ramonjd Just want to put this on your radar, looks like you recently worked in that page-templates file that references `vertical-whitelist`.

I couldn't find anything else referencing that key. Is it safe to change it to something else without needing to make other changes? What would be an appropriate alternative, `allowed-verticals`?

**Comment by ramonjd** [comment]
Thanks for the heads up @saramarcondes 

> Is it safe to change it to something else without needing to make other changes? What would be an appropriate alternative, allowed-verticals?

Totally fine to change. I believe it was introduced for a purpose that was never/is not yet realized. :)
