### ISSUE TITLE
Site Settings: analytics page doesn't handle jetpack

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#44]
We're showing a plan upgrade message on the analytics settings page for jetpack sites, and I don't believe that's an option for them.

![image](https://cloud.githubusercontent.com/assets/7233112/11224924/5e78eb42-8d45-11e5-9bc5-440f5d8ffaf5.png)

it is possible to get into the state in my screenshot above by navigating to the analytics page for a wpcom site, and then switching to a jetpack site. I think we just need a custom message saying analytics can only be added to wpcom-hosted sites. We have the reverse issue for the jetpack security page (possible to get to the jetpack security page with a wpcom site), and this is how they handle it:

![image](https://cloud.githubusercontent.com/assets/7233112/11224945/75aaf9d6-8d45-11e5-90b6-947f672ecad7.png)

**Comment by hoverduck** [comment]
05May16 Bug Scrub

Confirmed this is still an issue, but with a different signature.  Now when you visit /settings/analytics with a wpcom site and then switch to a Jetpack site you get a page that looks like you can add Google Analytics, but the input field is unavailable:

<img width="714" alt="screen shot 2016-05-05 at 3 03 28 pm" src="https://cloud.githubusercontent.com/assets/7233112/15053871/ae8b65d4-12d2-11e6-88a4-b48416725eac.png">

The links there point you to WordPress.com support documents detailing the integration, but there's no reference to the fact that it's unavailable to Jetpack sites.

My guess is that the change is due to the fact that we now show the Upgrade nudge as a banner instead of the full-page:

<img width="709" alt="screen shot 2016-05-05 at 3 03 36 pm" src="https://cloud.githubusercontent.com/assets/7233112/15053913/e8b40220-12d2-11e6-99f8-005b00e7000d.png">

**Comment by mtias** [comment]
There should be a redirect now in place.
