### ISSUE TITLE
Gutenboarding: remove code in `sites/new` endpoint where we are deleting the extra page/posts on site creation

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#44017]
Now that we have clean starter sites in https://github.com/Automattic/view-design/issues/54, we don't need to remove extra pages and posts. 

We removed them for https://github.com/Automattic/wp-calypso/issues/41294

See comments on D45183-code#925610

### Prerequisites

- [ ] Deploy D45183-code

**Comment by ramonjd** [comment]
Doing this in D45183-code

**Comment by andrewserong** [comment]
Closed by D45183-code
