### ISSUE TITLE
Home: Launched site "stuck" in Coming Soon Mode, Suggests Launching Site

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#44014]
While creating a test site today as an existing user I skipped a few checklist steps in order to just immediately launch and get testing and noticed the following …

![image](https://user-images.githubusercontent.com/545779/86971136-42b87100-c136-11ea-85f5-f6ef4362fdf2.png)

1. Site card displays "Coming Soon" mode. I think there may be some delay here in removing the message after launch?
2. Stats card copy suggests I need to launch my site yet to see stats. I don't have any stats to see yet but the site _is_ launched. :)

cc @lcollette @kwight

**Comment by Aurorum** [comment]
I'm a bit confused by this, as I can't seem to reproduce it. Am I missing something in trying to do so? :) 

![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/43215253/86975756-e888d180-c170-11ea-82ee-43adbceb9a1e.gif)

**Comment by kwight** [comment]
Are you still seeing this for that site @ianstewart ? I can't replicate either 🤔

**Comment by ianstewart** [comment]
I can replicate it. I made a video. 

https://cloudup.com/c0Ed-2uYQPT

**Comment by mreishus** [comment]
Hm, I'm not able to replicate it.  I tried on sandbox, staged, and on production, using the same steps as the video above.  Here's what I saw: https://d.pr/v/aCf1em

Is this still an issue for you, @ianstewart ?

**Comment by ianstewart** [comment]
Hmm. I'm not able to replicate any longer — because I'm stuck on the "Hooray!" screen in the signup framework. (A separate issue.)

**Comment by mreishus** [comment]
I'm not sure how to proceed on this one; moving it back out of 'in-progress'.

**Comment by ianstewart** [comment]
I'm going to close this one for now if we can't reproduce it and it's non-urgent.
