### ISSUE TITLE
(3P) InlineHelp: Record event when click on support pages in customer home

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#44027]
We need to record when the user clicks on the support link, on the customer homepage. It should be handled by the results card, in the `<HelpSearch />` component.

**Comment by mreishus** [comment]
Taking a look at this one

**Comment by mreishus** [comment]
PR Ready for review.  Updated with detailed testing instructions at top of PR
https://github.com/Automattic/wp-calypso/pull/44035
