### ISSUE TITLE
SPT Preview - editor crashes with 'getBoundingClientRect of undefined' error on 8.5-alpha+

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#44038]
I am not able to reproduce this on Gutenberg v8.3, but currently ran into this problem on edge sites.  Sometimes (more rarely) it is triggered just by opening the SPT Layout Picker.  But more consistently reproducible by:
* Navigate to the editor on an edge stickered site.
* Load the layout picker ('Change layout' button on the right document bar)
* Select 'Dalston' layout (this is only reproducible with certain layouts)
* Click the large preview on the right.
* hit 'Tab'

Notice the editor breaks with an error:

![Screen Shot 2020-08-13 at 11 22 53 AM](https://user-images.githubusercontent.com/28742426/90153792-684d2180-dd57-11ea-9591-f6d7cec413cc.png)

**Comment by Addison-Stavlo** [comment]
We first noticed this while working on another PR, but it after investigating more it seems separate to that and new with the edge version of Gutenberg.  @andrewserong had some thoughts on #43980 .

> I looked into the getBoundingClientRect issue and it looks or feels like there's a Popover somewhere that's trying re-adjust its size, and I'm wondering if somehow the block provider expects there to be a Popover.Slot — or because our parent document's block provider has one, it's somehow expecting something like that here?

**Comment by Addison-Stavlo** [comment]
Repeating myself on this thread for visibility:

I have an unconfirmed suspicion that this may be fixed by WordPress/gutenberg#24397 which was created to fix a similar tabbing through previews issue - #44042 . That fix is included with 8.8 which I believe should be live on edge sites early next week, so it may be worth testing this issue again once that is live.

**Comment by david-szabo97** [comment]
Fixed in Gutenberg v8.9 by https://github.com/WordPress/gutenberg/pull/24935
