### ISSUE TITLE
Button Block: Opened linked popover has odd position

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#44033]
#### Steps to reproduce

1. Add a Button Block (on a page that has some content and is long enough so that the Button Block would appear at the bottom part of the screen)
2. Click the link icon in the toolbar

#### What I expected
Link popover appear close to the button, above or below, but close to it

![](https://d.pr/i/6h2V28+)
_Link: https://d.pr/i/6h2V28_

Recorded on a site with Gutenberg 8.5 and Theme Varia

#### What happened instead
Link popover appear far from the Button Block (likely much above)

![](https://d.pr/i/kaxJWz+)
_Link: https://d.pr/i/kaxJWz_

Recorded on a WP.com site with Gutenberg 8.3 and Theme Varia

#### Context / Source

This seems to be fixed in the latest version of Gutenberg 8.5. A possibly related issue is https://github.com/WordPress/gutenberg/issues/23799

#manual-testing #user-report in 22426958-hc (screen recording of the issue https://d.pr/v/P0ZM3Z)

**Comment by cathymcbride** [comment]
Looks fixed to me in Gutenberg 9.0. @zdenys please reopen if you are still seeing this.
