### ISSUE TITLE
Earn: "Congratulations on your first sale!" emails for one-time sales need content updates.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44044]
Sellers receive emails notifying them of subscription sales. Because it's possible to make a one-time "subscription", we send emails for one-time payments with confusing terms.

"One-time payment" could be less confusing, and the reference to a next payment just needs to be removed. These emails for donations also reference one-time donations, and next payment to be received.

<img width="700" alt="Screen Shot 2020-07-09 at 9 46 51 AM" src="https://user-images.githubusercontent.com/349751/87068426-61684780-c1ca-11ea-8a98-8b1cd06c5e4a.png">

**Comment by sixhours** [comment]
Started working on this in D47311-code

**Comment by mmtr** [comment]
@sixhours can we close this one out now that D47311-code has landed? or do we need additional patches?

**Comment by sixhours** [comment]
Yep! All done.
