### ISSUE TITLE
(2P) InlineHelp: Anchor to appropriate sections from admin results

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#44059]
#### Steps to reproduce:

1. Click on the Help FAB
2. Type in a query - For example: `footer text`
3. Click on "Change my site's footer text" from the admin results:

![Screen Shot 2020-07-09 at 3 17 20 PM](https://user-images.githubusercontent.com/4924246/87096260-49f38380-c1f7-11ea-9d0f-9efabd13bff3.png)

4. Be taken to `/settings/general/[ site ]`, but it doesn't actually direct you to the appropriate section in the page. You would have to manually locate the section yourself.

**Related conversations:**
https://github.com/Automattic/dotcom-manage/issues/8#issuecomment-646428034
 https://github.com/Automattic/wp-calypso/pull/43790#issuecomment-655705875

cc @davemart-in @lcollette @Automattic/ajax

**Comment by davemart-in** [comment]
Removing this from the Manage backlog since it's already on the Ajax backlog.

**Comment by retrofox** [comment]
Just fyi, some admin sections depend on the site plan, type, other variables, etc. For instance,  my atomic site doesn't have this _footer_ section, which makes me think we should keep iterating on how it collects these data.

**Comment by obenland** [comment]
To fix this we should add an `id` to the heading so it can be added to the URL

**Comment by mreishus** [comment]
PR: #44805

The `id` method generally does work.  In the planning meeting, we talked about this issue assuming only the 'Change my site's footer text' needs to change, but a closer look reveals we're talking about [all possible help answers](https://github.com/Automattic/wp-calypso/blob/537ad25e84d07b1f8595841977ff0b4c0372cc1f/client/blocks/inline-help/admin-sections.js#L22) that link somewhere below the fold. I went through them all and modified the appropriate results.

**Comment by mreishus** [comment]
Bonus PR: #44808  While working on this, I noticed some descriptions were copy and pasted and not changed.  For example, 

```
	{
		title: translate( 'Install, manage, and search for site Plugins' ),
		description: translate(
			'You can customize your website by changing the footer credit in customizer.'
		),
		link: `/plugins/${ siteSlug }`,
		synonyms: [ 'upload' ],
		icon: 'plugins',
	},
```
