### ISSUE TITLE
(8P) Premium Blocks: Add Upgrade banner to Placeholder

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#44056]
Instead of the upgrade nudge, let's add a banner to the placeholder that lets users upgrade their plan. 

When clicking on the right-hand button, users should be taken to the checkout flow for the required plan: `https://wordpress.com/checkout/{SITE}/premium#step2`
To do that, we should
* Save the post ([see here for example code](https://github.com/Automattic/wp-calypso/blob/48bc8f0d972c2d5581b21a8e05779817606d07d4/apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts#L75)).
* Land them back at that editor page after checkout.

#### Screenshot / Video

![image-13](https://user-images.githubusercontent.com/1398304/87573481-d2ec3e00-c681-11ea-9ef2-8238c9765ea9.png)

See 123-gh-dotcom-manage

**Comment by obenland** [comment]
@davemart-in:

* Are there any premium Jetpack blocks that need a paid upgrade to use, that currently show up in the inserter?
* Where do we need to link to the Jetpack checkout flow?

**Comment by davemart-in** [comment]
@obenland the payments block requires a paid upgrade in JP. The "Pay with PayPal" (previously Simple Payments) block used to be in JP as well, but I no longer see it. I pinged in the Earn channel to get the scoop on that one.

**Comment by retrofox** [comment]
> The "Pay with PayPal" (previously Simple Payments) block used to be in JP as well, but I no longer see it. I pinged in the Earn channel to get the scoop on that one.

I've been testing with my simple site and it shows there.

<img src="https://user-images.githubusercontent.com/77539/87467914-16e23300-c5ef-11ea-86bc-4a8ac8e236de.png" width="300px" />

Also, it shows the `Upgrade` button in the PR https://github.com/Automattic/jetpack/pull/16482

<img width="500" alt="Screen Shot 2020-07-14 at 4 29 06 PM" src="https://user-images.githubusercontent.com/77539/87467997-36795b80-c5ef-11ea-91b1-20e9e9c513f5.png">

**Comment by obenland** [comment]
@davemart-in Sorry for the double-ping, but the screenshot above shows the new UI well. Should the upgrade nudge be removed with the addition of the button?

**Comment by davemart-in** [comment]
> Should the upgrade nudge be removed with the addition of the button?

Yes please. Let's remove the old banners.

**Comment by retrofox** [comment]
https://github.com/Automattic/wp-calypso/issues/44168

**Comment by obenland** [comment]
@retrofox I updated the description of this ticket to reflect the new direction.

**Comment by retrofox** [comment]
two questions about the design:

* Do you have details such as height, font-size, icon size, etc? The following shows how looks the current implementation.
![image](https://user-images.githubusercontent.com/77539/87661004-4e0f2c00-c736-11ea-925b-f659c16e056b.png)

* what's the area used to click on and thus redirects the user to the checkout? I've defined the chevron button, but maybe it's the whole banner?

<img src="https://user-images.githubusercontent.com/77539/87611346-3906ae80-c6de-11ea-8399-617dd3abcab7.png" width="300px" />

**Comment by retrofox** [comment]
> two questions about the design:

cc @jancavan @sfougnier in case you miss the comment

**Comment by sfougnier** [comment]
> Do you have details such as height, font-size, icon size, etc? The following shows how looks the current implementation.

- Font size is 14px
- Container height is 48px within the block
- The icon will be removed as per new feedback, so disregard that for now.

> what's the area used to click on and thus redirects the user to the checkout? I've defined the chevron button, but maybe it's the whole banner?

The chevron is being swapped for a button to align with the sidebar.

This screenshot should be a good indicator of where this bar is heading. Color may shift but the rest of the parameters should remain the same.
<img width="1347" alt="Screen Shot 2020-07-16 at 9 08 51 AM" src="https://user-images.githubusercontent.com/67021691/87674429-fc6d9e00-c743-11ea-8275-f74fd54a9fd5.png">

**Comment by cpapazoglou** [comment]
@sfougnier this is the current status.

![](https://cln.sh/62vPzh+)

**Comment by sfougnier** [comment]
**Latest design**
To build on the previous comment, the latest designs maintain the same parameters below:

- Font size is 14px
- Container height is 48px within the block
- The icon has been removed
- The chevron is replaced with a button

In terms of expected functionality:

- Banners now appear across the placeholder and preview states of the blocks (see below)
- Banners appear when the block is selected and disappear along with the toolbar when the block is inactive
- To ensure banners are scalable across different block types, the banner has been detached from the block and is now floating between the toolbar (see below)
- Banners will be removed entirely once a user has upgraded

<img width="1440" alt="01D Premium Block Flow" src="https://user-images.githubusercontent.com/67021691/87832316-bbfd4580-c853-11ea-9215-38fcc705cfc9.png">
<img width="1440" alt="01F Premium Block Flow" src="https://user-images.githubusercontent.com/67021691/87832320-bf90cc80-c853-11ea-9b05-e8122969bd5f.png">
<img width="375" alt="01 Mobile" src="https://user-images.githubusercontent.com/67021691/87832321-c15a9000-c853-11ea-9388-5c9023a6fc57.png">

**Design Links**
[Flow states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A0)
[Block states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A13520)
