### ISSUE TITLE
(5P) Premium Blocks: Add banner below block description in sidebar

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#44057]
In the block sidebar, let's append a banner to the Block description that reads "Premium Block" and includes an Upgrade button. That button should behave similarly as in #44056, we should probably just re-use that same component.

#### Screenshot / Video
![image-15](https://user-images.githubusercontent.com/1398304/87573876-67ef3700-c682-11ea-9acb-d85eea512357.png)

See 123-gh-dotcom-manage

**Comment by cpapazoglou** [comment]
First thought was to add some html in the Block title with `display:none` and then force show it wherever we want but the html is stripped out from the title.

**Comment by sfougnier** [comment]
**Latest design**
This component now closely matches the styling of the [larger block banner ](https://github.com/Automattic/wp-calypso/issues/44056#issuecomment-660348271).

- Font size is 14px
- Container height is 48px within the block
- The icon has been removed
- The chevron is replaced with a button
- The banner no longer spans the full width of the sidebar and is instead aligned with the content grid, with 20px on all sides.
- Banners will be removed entirely once a user has upgraded

<img width="1440" alt="01E Premium Block Flow" src="https://user-images.githubusercontent.com/67021691/87832934-1f3ba780-c855-11ea-9524-17e9862b2185.png">
<img width="292" alt="Screen Shot 2020-07-17 at 5 44 27 PM" src="https://user-images.githubusercontent.com/67021691/87832952-2a8ed300-c855-11ea-82eb-ba4b7e7f2c71.png">

**Design Links**
[Flow states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A0)
[Block states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A13520)
