### ISSUE TITLE
(5P) Premium Blocks: Add banner to block preview

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#44055]
Let's add a banner to block previews, that acts like a separator of sorts. It should read "Upgrade Required" rather than what it says in the screenshot.

I'm not sure we can extend `InserterPreviewPanel`, so we should find out what our options are here.

#### Screenshot / Video
<img alt="image-2020-07-07-at-9 32 17-pm" src="https://user-images.githubusercontent.com/1398304/87086522-92567580-c1e6-11ea-8deb-d81fa0a4fcca.png">

See 123-gh-dotcom-manage

**Comment by obenland** [comment]
@cpapazoglou mentioned trying to add an element to the block description and positioning that.

**Comment by frontdevde** [comment]
As a first test I took a look at whether it'd be possible to achieve this using a pseudo-element that only shows when the block is rendered inside the block inserter preview container.

![update-required-notice-css](https://user-images.githubusercontent.com/1562646/87400405-0ca54200-c5b9-11ea-84c3-aa5fc2b18b89.gif)


Code for the test:
```
@import '../../shared/styles/gutenberg-base-styles.scss';
// Add upgrade notice to block inserter preview
.block-editor-inserter__preview-container {
	.wp-block-jetpack-calendly {
		$banner-height: 42px;
		padding-bottom: $banner-height;

		&:after {
			content: "Upgrade required";
			position: absolute;
				bottom: 0;
				right: 0;
				left: 0;
			height: $banner-height;
			z-index: 11;
			background: $black;
			color: $white;
			font-family: $default-font;
			font-size: 24px;
			line-height: 37px;
			text-align: center;
			overflow: hidden;
		}
	}
}
```

**Comment by frontdevde** [comment]
> Ideally though, we'd manage to programatically add a class to all paid blocks that we could use to show this.

Looks like [editor.BlockListBlock](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#editor-blocklistblock) could be an option to do that. It'd allow us to add a class to the block’s wrapper component.

In that case, our CSS could make use of that like so:

```
@import '../../shared/styles/gutenberg-base-styles.scss';
// Add upgrade notice to block inserter preview
.block-editor-inserter__preview-container {
	.has-upgrade-notice > div {
		$banner-height: 42px;
		padding-bottom: $banner-height;

		&:after {
			content: "Upgrade required";
			position: absolute;
				bottom: 0;
				right: 0;
				left: 0;
			height: $banner-height;
			z-index: 11;
			background: $black;
			color: $white;
			font-family: $default-font;
			font-size: 24px;
			line-height: 37px;
			text-align: center;
			overflow: hidden;
		}
	}
}
```

**Comment by frontdevde** [comment]
Good news! Turns out that in `register-jetpack-blocks.js` we're already using ` editor.BlockListBlock` when `requiredPlan` is true to add `has-warning is-interactive` classes to the block’s wrapper component.

So just for a test I used one of these classnames with the code above (using `.block-editor-inserter__preview-container .has-warning > div`) and this is the result:

![update-required-notice-css-2](https://user-images.githubusercontent.com/1562646/87411638-4cbff100-c5c8-11ea-8555-1d0a8d19b3a3.gif)

**Comment by frontdevde** [comment]
In some paid blocks e.g. Eventbrite the `has-warning` gets applied to child blocks as well e.g. buttons. So we'd need to make sure to not show the notice there via `display:none`. 

```
@import '../../shared/styles/gutenberg-base-styles.scss';
// Add upgrade notice to block inserter preview
@import '../../shared/styles/gutenberg-base-styles.scss';
// Add upgrade notice to block inserter preview
.block-editor-inserter__preview-container {
	.has-warning > div {
		$banner-height: 42px;
		padding-bottom: $banner-height;

		&:after {
			content: "Upgrade required";
			position: absolute;
				bottom: 0;
				right: 0;
				left: 0;
			height: $banner-height;
			z-index: 11;
			background: $black;
			color: $white;
			font-family: $default-font;
			font-size: 24px;
			line-height: 37px;
			text-align: center;
			overflow: hidden;
		}

		// Hide notice in child blocks
		.has-warning > div:after {
			display: none;
		}
	}
}
```

**Comment by frontdevde** [comment]
It's worth pointing out that at the moment we're [disabling the preview here](https://github.com/Automattic/jetpack/blob/master/extensions/shared/register-jetpack-block.js#L99) when the plan doesn't feature the block:
`example: requiredPlan ? undefined : settings.example`

My current assumption is that this because of the upgrade banners showing in the preview. If we were to pursue above described route, we'd need to keep the example and visually hide the upgrade banners.

**Comment by obenland** [comment]
From what I understood, #44056 will remove that upgrade banner in favor of adding that button. @davemart-in could you confirm that?

**Comment by frontdevde** [comment]
That's good to know! Either way it wouldn't be that big of a deal. Just[ remove said line](https://github.com/Automattic/jetpack/blob/master/extensions/shared/register-jetpack-block.js#L99) and then hide the nudge in the inserter preview:

```
@import '../../shared/styles/gutenberg-base-styles.scss';
// Add upgrade notice to block inserter preview
.block-editor-inserter__preview-container {
	.has-warning {

		> div {
		$banner-height: 42px;
		padding-bottom: $banner-height;

			&:after {
				content: "Upgrade required";
				position: absolute;
					bottom: 0;
					right: 0;
					left: 0;
				height: $banner-height;
				z-index: 11;
				background: $black;
				color: $white;
				font-family: $default-font;
				font-size: 24px;
				line-height: 37px;
				text-align: center;
				overflow: hidden;
			}

			// Hide notice in child blocks
			.has-warning > div:after {
				display: none;
			}
		}

		// Hide upgrade nudge
		.jetpack-block-nudge {
			display: none;
		}
	}
}
```

**Comment by frontdevde** [comment]
I think I just solved the last piece of the puzzle:

<img width="331" alt="Screenshot 2020-07-14 at 17 49 15 copy" src="https://user-images.githubusercontent.com/1562646/87447110-75f97500-c5fa-11ea-959d-963a1274d052.png">


To get the copy translated, we'll can make use of `editor.BlockListBlock` again when requiredPlan is true in the same fashion as we're doing when adding the class to the block’s wrapper component. This time we'll pass the title as a data attribute to the `wrapperProps`:

`wrapperProps={ { 'data-upgrade-title': __( 'Upgrade required', 'jetpack' ) } }`

Then we only need to adjust our CSS a bit and can read the translated title from the DOM like so:

```
@import '../../shared/styles/gutenberg-base-styles.scss';
// Add upgrade notice to block inserter preview
.block-editor-inserter__preview,
.block-editor-inserter__preview-container {
	.has-warning {

		$banner-height: 42px;
		padding-bottom: $banner-height;

		&:before {
			content: attr(data-upgrade-title);
			position: absolute;
				bottom: 0;
				right: 0;
				left: 0;
			height: $banner-height;
			z-index: 11;
			background: $black;
			color: $white;
			font-family: $default-font;
			font-size: 24px;
			line-height: 37px;
			text-align: center;
			overflow: hidden;
		}

		// Hide notice in child blocks
		.has-warning:before {
			display: none;
		}

		// Hide upgrade nudge
		.jetpack-block-nudge {
			display: none;
		}
	}
}
```

**Comment by sfougnier** [comment]
**Latest Design**
The latest push here has been to remove the messaging from inside the block preview to align more with core. The block preview will still have an icon in the block icon to match the treatment within the inserter, but there will be no further messaging.

<img width="1440" alt="01C Premium Block Flow" src="https://user-images.githubusercontent.com/67021691/87832113-3c6f7680-c853-11ea-8917-3b668228407a.png">
<img width="320" alt="Screen Shot 2020-07-17 at 5 30 50 PM" src="https://user-images.githubusercontent.com/67021691/87832130-442f1b00-c853-11ea-9ce1-ce935a67619c.png">

**Design Links**
[Flow states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A0)
[Block states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A13520)

**Comment by cpapazoglou** [comment]
As per @sfougnier latest comment we will not add a premium indicator banner in the block preview of the inserter. This will help us align with core too. The Dot indicator will eventually be added through this PR https://github.com/Automattic/jetpack/pull/16509
