### ISSUE TITLE
(3P) Premium Blocks: Add contextual tip for upgrade star icon

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#44050]
This will add a contextual tip to explain the meaning of the premium block stars, introduced in #44048.

I'm not sure if that is even possible currently, we should investigate if we can use `__experimentalInserterMenuExtension` for that and maybe position that tip via CSS.

#### Screenshot
<img alt="image-2020-07-07-at-9 27 22-pm" src="https://user-images.githubusercontent.com/1398304/87078622-cb3c1d80-c1d9-11ea-9ebb-83b42293f468.png">

#### Prior Art
* [Contextual Tips](https://github.com/Automattic/wp-calypso/tree/0c084213422aee1f5cbacc2769e0e7cff8813997/apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications)

See 123-gh-dotcom-manage

**Comment by obenland** [comment]
@sfougnier @jancavan Is there a chance I could defer to you for the creation of that star-with-background SVG that's being displayed in the tip?

**Comment by mreishus** [comment]
From checking the videos in the [Premium Blocks Messaging, Round 4](https://managep2.wordpress.com/2020/07/07/premium-blocks-messaging-round-4/#comment-1334) post, it looks like the goal is to overwrite the `<Tip>` element in Gutenberg, which provides a "global tip".

![global-tip](https://user-images.githubusercontent.com/937354/87359094-c5716f80-c52c-11ea-9a53-1e2e2873a911.png)

In Gutenberg:

- [tips.js](https://github.com/WordPress/gutenberg/blob/7f6f31b91673453a1339bc3894b83693ea6bd79f/packages/block-editor/src/components/inserter/tips.js#L31) - Provides `<Tips>`, which reads from a locally defined `globalTips` and renders one
- [menu.js](https://github.com/WordPress/gutenberg/blob/7f6f31b91673453a1339bc3894b83693ea6bd79f/packages/block-editor/src/components/inserter/menu.js#L96) - Renders `<Tips>` from tips.js above

I'm not seeing a way that the tips can modified from outside gutenberg.  Two possible ways to approach this:

* A: Submit a PR to gutenberg to make the tips extensible.  (Currently unsure of specifics)
* B: Try a solution without changing gutenberg, such as the one Konstantin mentioned at the beginning of this issue.  Generally injecting an element and positioning it with CSS.

I haven't tried B yet, I'll spend some time playing around with it tomorrow.

**Comment by mreishus** [comment]
In testing, I was able to use `__experimentalInserterMenuExtension` to add a `<div>` to the menu.  However, I'm not able to use CSS to position it over the global tooltip space.  I tried using absolute positioning.  Without changing other parts of the site, the nearest positioned parent is the scrollable block inserter div:

![2020-07-14_09-23](https://user-images.githubusercontent.com/937354/87437559-1b3d2a80-c5b4-11ea-80e2-2a9230c84481.png)

Now, I can add `bottom: 0px` to put it at the bottom of the list, sort of.  It's at the bottom of the first screenful of blocks before you scroll at all.  But we need to 'break out' of that parent and go lower than that.  What if I use a negative position on the `bottom` attribute?  Well, it moves it lower and lower inside the list of blocks, but still inside the scrollable container.  And if I tweak the position to be at the bottom of the scrollable container and then go even more negative, it extends the scrollable container.  Example:

![2020-07-14_09-24](https://user-images.githubusercontent.com/937354/87437907-7ff88500-c5b4-11ea-9bbd-80e307464c26.png)

I'm not seeing a way to do this with CSS, but I'm open to suggestions if anyone has any.  I think we need some sort of modification to gutenberg.

**Comment by mreishus** [comment]
Here's a css only approach.  I used a placeholder SVG star from wikipedia for the time being.  The positioning of it can be tweaked as well.

```sass
.block-editor-inserter__tips {
	.components-tip {
		svg {
			visibility: hidden
		}
	}
	&::before {
		display: block
		content: ' '
		background-image: url( 'https://upload.wikimedia.org/wikipedia/commons/1/18/Five-pointed_star.svg' )
		position: absolute
		background-size: 24px 24px
		height: 24px
		width: 24px
	}
	&::after {
		content: 'Premium tools are available for you to preview within your site without an upgrade.'
		position: absolute
		bottom: 16px
		right: 16px
		left: 50px
		height: 39px
		z-index: 11
		background: #fff
		text-align: center
		overflow: hidden
	}
}

```

![2020-07-14_11-27](https://user-images.githubusercontent.com/937354/87451431-775c7a80-c5c5-11ea-9243-d0a58c14160b.png)


Issues:
- Text is not available for translation.  I don't see a way to stick something on a data- element as done on #44055.
- Banner would always appear. It should only appear for non-upgraded users.  Maybe there's a parent class somewhere that reflects that?

**Comment by mreishus** [comment]
Note about customizing through Gutenberg.  Even if we are able to add an override mechanism for `globalTips` in [tips.js](https://github.com/WordPress/gutenberg/blob/7f6f31b91673453a1339bc3894b83693ea6bd79f/packages/block-editor/src/components/inserter/tips.js#L31), that would change the text only.  Currently, tips.js is hardcoded to use the `<Tip>` component, which uses a [hardcoded icon](https://github.com/WordPress/gutenberg/blob/5d237250a4337739a42b04a6db455ea3f32ab54d/packages/components/src/tip/index.js#L10).  So we'd either have to add an icon customization method as well, or use a portal slot/filler mechanism for the tip space.

**Comment by sfougnier** [comment]
The star asset can be found here:
[Star.svg.zip](https://github.com/Automattic/wp-calypso/files/4920145/Star.svg.zip)

**Comment by mreishus** [comment]
Halting work on this, unassigning.

**Comment by obenland** [comment]
@mreishus What are the next steps for this?

**Comment by mreishus** [comment]
Decide which approach to use:

CSS:
- I have a initial version above, but it has three problems:
  - Lacking translation
  - Appears always, instead of only when unpaid
  - Needs to use proper star SVG.

Integration with Gutenberg:
-  No code done.  Two broad approaches possible
    - Add a mechanism to override `globalTips` in [tips.js](https://github.com/WordPress/gutenberg/blob/7f6f31b91673453a1339bc3894b83693ea6bd79f/packages/block-editor/src/components/inserter/tips.js#L31).  This must be combined with a mechanism that overrides the [graphic in the Tip component](https://github.com/WordPress/gutenberg/blob/5d237250a4337739a42b04a6db455ea3f32ab54d/packages/components/src/tip/index.js#L10).
    - Use a slot/filler mechanism in gutenberg's [menu.js](https://github.com/WordPress/gutenberg/blob/7f6f31b91673453a1339bc3894b83693ea6bd79f/packages/block-editor/src/components/inserter/menu.js#L96) to override the `<Tips>` component entirely.

**Comment by obenland** [comment]
https://github.com/WordPress/gutenberg/pull/22109#discussion_r424275349 has some good feedback from Core maintainers around creating a Tips API to register, unregister, and display Tips. It might be worth investing time into making that properly extensible for more ease of use down the road

**Comment by sfougnier** [comment]
**Latest design**
Based on some of the issues that have come up with this in terms of both the functionality and implementation, the latest designs have removed this feature. The placement of messaging is now within the block + sidebar only.

<img width="1440" alt="01C Premium Block Flow" src="https://user-images.githubusercontent.com/67021691/87831588-f1a12f00-c851-11ea-99f1-e1204078c622.png">

**Design Links**
[Flow states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A0)
[Block states](https://www.figma.com/file/9d7LWKtiFnpP5qxJ8YEa3V/Premium-Blocks?node-id=399%3A13520)

**Comment by mreishus** [comment]
> the latest designs have removed this feature

Closing this issue as it's not needed at this time.
