### ISSUE TITLE
InlineHelp: Update admin results to use correct icons

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#44060]
#### Steps to reproduce

1. Click on the Help FAB
2. Type in a query, but make sure this isn't domain related - Example: `SEO`:

![Screen Shot 2020-07-09 at 3 23 45 PM](https://user-images.githubusercontent.com/4924246/87096688-372d7e80-c1f8-11ea-9167-bc366c51e9ac.png)

Notice how, with any query, it's always just showing the domain icon.

@retrofox I think we discussed this briefly before and we may have had a misunderstanding. But I am ok to use the predefined icons in Ramon's PR: https://github.com/Automattic/wp-calypso/pull/31903. They just need to be gray instead of blue. The mockups using the domains icons were just to illustrate the idea (if you searched for domains). Thank you and let me know if you have any questions.

@davemart-in @lcollette @Automattic/ajax

**Comment by davemart-in** [comment]
Removing this from the Manage backlog since it's already on the Ajax backlog.
