### ISSUE TITLE
InlineHelp: Collapse FAB after click on mobile

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#44061]
#### Steps to reproduce

1. On mobile, click to open the FAB
2. Type in any query
3. Click on any of the admin results

Notice how you are taken to the appropriate link, but since the page is behind the FAB, the change isn't noticeable, so there isn't any feedback. Is it possible to auto-collapse the FAB after clicking on an admin link (admin link only)? This would only be for mobile though, there is no change in behavior on desktop.

![Screen Shot 2020-07-09 at 3 34 11 PM](https://user-images.githubusercontent.com/4924246/87097267-a5267580-c1f9-11ea-804d-07dd0b87e924.png)

@davemart-in @lcollette @Automattic/ajax

**Comment by davemart-in** [comment]
Removing this from the Manage backlog since it's already on the Ajax backlog.

**Comment by jeryj** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/44068

**Comment by jeryj** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/44068
