### ISSUE TITLE
Nav sidebar: butto to dismiss sidebar disappears on IE

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#44067]
Discovered here https://github.com/Automattic/wp-calypso/pull/43906#issuecomment-654596136

![Jul-07-2020 14-41-51](https://user-images.githubusercontent.com/6458278/86712338-3feb4c80-c060-11ea-8ae2-c6de957d5c03.gif)

We don't need everything to be perfect in IE, but it should be possible to dismiss the sidebar with the close button.

**Comment by ramonjd** [comment]
Taking a 👀
