### ISSUE TITLE
Button Block: Facebook Video Embed Overrides Button Block Links

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#44064]
#### Steps to reproduce

1. Create a page. 
2. Add a Button Block to that page, and write some text in it. Something like "Facebook" (or whatever you want)
3. Link that text to a Facebook video. Open in new tab does not matter in this case (off or on).
4. Publish the page. The video will embed instead of showing a button that links to the video.
5. Add a new Button Block, and write some text in it. Something like "YouTube" (or whatever you want)
6. Link the second button to a YouTube video.
7. Update. The Facebook one is broken, and the button that links to the YouTube video displays correctly.

#### What I expected
A button to appear that links to a Facebook Video

#### What happened instead
The link to the Facebook Video transforms the button into a Facebook Video Embed. This can also break other elements on the page. On Twenty Sixteen for example, it breaks the sidebar. 

#### Browser / OS version
All.

#### Screenshot / Video
![buttonfacebook](https://user-images.githubusercontent.com/30731356/87101050-df484500-c202-11ea-9e43-c8aed10021d3.gif)

#### Context / Source

#reallife #stresscase #painpoint.
#user-report

**Comment by yansern** [comment]
The culprit is the function `wpcom_shortcodereverse_facebook_video()` in `wpcom/wp-content/mu-plugins/shortcode-reversals.php`. Once it matches a facebook video url, it replaces the entire button html block with a `[facebook]` shortcode.

**Comment by yansern** [comment]
Phab patch here: D47652-code

**Comment by ockham** [comment]
> Phab patch here: [D47652-code](https://href.li/?D47652-code)

Deployed. This issue should be fixed now.
