### ISSUE TITLE
Checklist: My Checklist not loading when viewing https://wordpress.com/plans/my-plan/

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#44076]
## Summary
The `My Checklist` section seems to be stuck in an endless loading loop for any Jetpack-connected site I've tested with a paid plan when viewing https://wordpress.com/plans/my-plan/

## Steps to Reproduce

1.Load https://wordpress.com/plans/my-plan/ for one of your Jetpack-connected sites with a paid plan.
2.Observe that the `My Checklist` section never loads

**Comment by cleacos** [comment]
This issue was fixed with this PR: https://github.com/Automattic/wp-calypso/pull/44101 Already in production.

**Comment by chaselivingston** [comment]
Great, thanks! Closing.
