### ISSUE TITLE
Patterns: Support more block types with new `BlockParser`'s

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#44089]
Carry on from D45748-code to support more block types with new `BlockParser`'s

- [ ] Add block pattern parser for core/image to allow replacement of image urls
- [ ] Add a block pattern parser for jetpack/contact-info to replace the address text cleanly
- [ ] Add a block pattern parser for the cover block to replace images and text cleanly
- [x] Add a block pattern parser for the buttons block to replace button text cleanly (ref D46546-code) (done in D46726-code)
- [ ] Add a block pattern parser for CoBlocks/hero (some fleeting notes in D46471-code)

**Comment by andrewserong** [comment]
I've made a start exploring this by adding a HeadingParser and an update to the ParagraphParser to support class names or other attributes in the `p` tag, in D46406-code.

**Comment by andrewserong** [comment]
Diff for looking at adding in a Button block parser: D46726-code

**Comment by andrewserong** [comment]
A small addition to the Paragraph and Heading parsers to deal with the `placeholder` attribute: D46848-code.

**Comment by andrewserong** [comment]
I'm just closing this issue out now, because we reached the level of parser support that we required to deliver phase 1 of the Patterns Toolkit. If and when we need to add additional parsers, let's open a separate issue with the new context for it.
