### ISSUE TITLE
Reader: Clicking Search Field in the Share Popup Menu of a Post Closes the Popup

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#44080]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/discover
2. Click the share icon next to a Post
3. Click search field

#### What I expected
Be able to search by tying

#### What happened instead
Popup menu closes unexpectedly. I can only select it (put it in focus) by using Tab on my keyboard. Clicking directly closes the popup immediately.

#### Browser / OS version
Chrome Version 83.0.4103.116 (Official Build) (64-bit) on macOS
Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit) on macOS

#### Screenshot / Video

![](https://d.pr/i/QKy1cV+)
_Link: https://d.pr/i/QKy1cV_

#### Context / Source

#dogfooding

**Comment by bluefuton** [comment]
Well spotted @zdenys! This is likely caused by changes in the underlying popover or sites list components.

**Comment by ncardeli** [comment]
I can help with this one!
