### ISSUE TITLE
Editor: add logging of timeout breakout of iframe

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#44088]
There is a fallback for users in the editor iframe which as a last resort will break the user out of the iframe and redirect them to wpadmin - https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/calypsoify-iframe.tsx#L145

It would be useful to add some logging so we can detect if any users are actually reaching this timeout limit and being redirected.

**Comment by synora** [comment]
Hi, @glendaviesnz I noticed this issue has gone stale but is part of a project board. Is this something that's still being looked into or can we close it?

**Comment by glendaviesnz** [comment]
This isn't being looked at as far as I am aware so I think we can close it.
