### ISSUE TITLE
CoBlocks: Mixed up arrows in gallery block (some themes. Pictorico).

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#44098]
#### Steps to reproduce

1. Add a gallery to a post in a site with them Pictorico. In the example This is used:

<div class="wp-block-coblocks-gallery-masonry">
<div class="coblocks-gallery has-no-alignment has-caption-style-dark has-gutter has-lightbox">
2. Browse the page 
https://guypixs.photo.blog/2020/06/25/homme-des-bois/
3. Click on one of the pictures. YOu'll see this:
<img width="523" alt="Homme des bois – Guypixs 2020-07-12 09-15-55" src="https://user-images.githubusercontent.com/6404071/87292785-9eea0f00-c501-11ea-8ddc-dfd1843ee515.png">

4. When the viewer appears, collapse the browser and make it narrower than 50em (1000px). 

#### What I expected

Arrow buttons to previous and next picture to behave normally

#### What happened instead

These buttons are stretched and mixed up as a result of an inherited CSS declaration that applies to narrow screens.
<img width="400" alt="Homme des bois – Guypixs 2020-07-12 09-15-15" src="https://user-images.githubusercontent.com/6404071/87292803-a5788680-c501-11ea-965e-f89f8fdb5bb3.png">
#### Browser / OS version

https://www.whatsmybrowser.org/b/FW6A1 or https://www.whatsmybrowser.org/b/5NJYN

#### Suggested FIX

The reason is this CSS statement that is present in pictorico Theme but could also be -similarly- in other themes:

```
@media screen and (max-width: 50em){
button, input[type=button], input[type=reset], input[type=submit] {
    font-size: .75em;
    line-height: 2em;
    padding: 15px;
    width: 100%;
}
}
```

The suggested fix would be something like:

```
button.coblocks-lightbox__arrow.coblocks-lightbox__arrow--right, button.coblocks-lightbox__arrow.coblocks-lightbox__arrow--left {
    width: initial;
}
```

Can you check it (I can go ahead and make a PR if the fix makes sense)?

#### Context / Source
3123093-zen

**Comment by WunderBart** [comment]
This is still happening after recent CoBlocks update (https://github.com/Automattic/wp-calypso/issues/45033). Seems to be a Pictorico issue as its button styles override the ones from CoBlocks.

**Comment by sirreal** [comment]
@rantoncuadrado I've prepped a change with your fix here: D48832-code

I think that's the least risky fix for this issue right now, thanks!

**Comment by WunderBart** [comment]
D48832-code deployed!
