### ISSUE TITLE
Patterns: Optimise starter page template (page layout) modal and behaviour in FSE plugin

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#44090]
This is a general issue to investigate optimising the page layout picker (starter page templates) modal across a number of areas. It will depend on Patterns API work, so the scope of this will likely change.

* [ ] The page layout picker currently loads the page templates server-side via an API call and attaches them to the initial page load in [the `starterPageTemplatesConfig` object](https://github.com/automattic/wp-calypso/blob/2b83937b085691ba66d162c35ca4a28ff48a5ce4/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php#L181). Right now this is adding around 463kb to our initial page load for the editor when loading it with the page layout picker.
  - Explore lazy-loading this template data after the initial page load
  - Can we move to having two API calls, one to get the list of available page layouts (similar to how we list available designs in Gutenboarding), and one to grab the block markup for _just_ the selected page layout? This should support having a growing list of available page layouts, without slowing down the initial page load or browsing page layouts
* [ ] When the list of available page layouts is first rendered ([renderTemplatesList](https://github.com/automattic/wp-calypso/blob/39ed68c25110278412f8dfa753e99562dd84beab/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js#L317)) , the memoized function [`getBlocksByTemplateSlugs` is called](https://github.com/automattic/wp-calypso/blob/39ed68c25110278412f8dfa753e99562dd84beab/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js#L57) — this is a computationally expensive function that iterates through all of the loaded templates and parses the blocks. However, we probably only need to parse blocks when we wish to preview or use them — can this logic be moved to occur only when a user selects a particular layout?  This might help performance on low-powered devices / older browsers
* [ ] Previews — currently the thumbnail previews are static images, and the larger preview is using a `<BlockEditorProvider>` and `<BlockList>` to [render the preview](https://github.com/automattic/wp-calypso/blob/34169f274c2191623f333824ecbe4b8835bc6ea3/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-preview.js#L31) from an array of blocks. This approach mirrors Gutenberg's [`<BlockPreview>` component](https://github.com/wordpress/gutenberg/blob/153817e3493e5ca3518f913d9ff859aab6e9a3e4/packages/block-editor/src/components/block-preview/index.js#L35), but is this the best way to go about previewing a block pattern / page layout? The current approach isn't _just_ previewing content, it's doing a fair bit more as revealed in the bug in #44038. Is it possible for us to use pre-rendered markup in our previews, similar to how the template/demo endpoint is used in Gutenboarding? E.g. could we use mShots for the thumbnail screenshots, and that endpoint for the larger preview?
  - Explore whether or not using something like the `template/demo` endpoint would result in better performance for the larger preview
  - Explore how feasible it would be to use mShots to generate preview thumbnails of the page layouts (the page layouts rendered in the context of the current theme)

**Comment by ramonjd** [comment]
Given the integration of the Patterns API and the upcoming redesign work we can close this.
