### ISSUE TITLE
Patterns: Translate Categories / Tag names

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#44095]
Add tests and code to ensure category and tag names are returned by to_strings and replaced by replace_strings.

Tags should suffice for keyword search usage required by https://github.com/Automattic/wp-calypso/issues/42906#issuecomment-637932490

**Comment by lsl** [comment]
This is probably a "good first task" for @andrewserong to get caught up on this patterns lib.

**Comment by andrewserong** [comment]
WIP in D46341-code

**Comment by andrewserong** [comment]
Done & merged in D46341-code.
