### ISSUE TITLE
Jetpack Plugins: page title incorrect on mobile

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#441]
When navigating to the single plugin view and then back to the list of plugins, you sometimes end up with the wrong page title showing. I might not being reset/cleared properly on some navigation routes.

Steps to reproduce:
1. Go to My Sites
2. Choose a Jetpack site
3. Go to Plugins
![screen shot 2015-11-22 at 3 27 41 pm](https://cloud.githubusercontent.com/assets/11487924/11326083/d35c89fa-912d-11e5-81de-eb934a5c3d51.png)
4. Click on a specific plugin
![screen shot 2015-11-22 at 3 28 01 pm](https://cloud.githubusercontent.com/assets/11487924/11326084/d5bdacd8-912d-11e5-8b6b-b2d73c30de6e.png)
5. Click 'Back', see that the page title displayed is incorrect. It says 'Akismet Plugin' instead of 'Plugins'
![screen shot 2015-11-22 at 3 28 15 pm](https://cloud.githubusercontent.com/assets/11487924/11326088/eb2b523c-912d-11e5-91a1-404206c119a6.png)

**Comment by apeatling** [comment]
My fix for this made the mistake of forgetting the page title tag, so that won't work. It will need a bit of a different approach.
