### ISSUE TITLE
Site Editor: more menu not shown on Dotcom

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#44104]
We are preventing the more menu form showing in site editor integration on Dotcom. This was done on purpose before when it had only one item. Now it makes sense to show it again, while hiding only the Fullscreen mode option, similar to how it's done in post editor integration.

Check D40903-code for the exact spot that needs to be modified.

**Comment by jeyip** [comment]
I have a PR ready for code review -- D46404-code
