### ISSUE TITLE
Site Editor: preview is not working on Dotcom

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#44105]
Device preview is not working properly in Dotcom site editor integration. Toggling to different preview modes like tablet and mobile will just show blank content screen.

**Comment by sixhours** [comment]
@lcollette and I ran into this bug today, so just adding our +1 here! To reproduce it:

* Open a site in the previewer
* Switch to Search & Social mode
* Switch back to Desktop, Tablet, or Phone view
* The preview will be blank

No obvious errors in the console to account for the failure.

**Comment by vindl** [comment]
Hi @sixhours, I think that might be a different one. This one is specifically related to experimental Site Editor feature (FSE) that's not available to end users yet.

**Comment by sixhours** [comment]
Ahhh oops! You're right, I'm talking about the site preview feature, not the editor. 🙃  I'll open a new issue, thank you!

**Comment by jeyip** [comment]
Having a little bit of trouble reproducing. The preview formatting isn't the greatest, but I don't see a blank screen @vindl. 

![site editor preview bug](https://user-images.githubusercontent.com/5414230/88857905-f2b85180-d1ab-11ea-83e6-a7eaa5a2372d.gif)

**Comment by vindl** [comment]
@jeyip are you testing in Calypso integration of the Site Editor? I can still reproduce there. Note that it work fine for local installs and in wp-admin of Simple Sites, so I think it might be related to iframing.

**Comment by jeyip** [comment]
> are you testing in Calypso integration of the Site Editor?

Thanks for clarifying 👍 I was using `wp-admin`. I can reproduce the issue for the Site Editor Calypso integration in Chrome, Firefox, Safari.

**Comment by Copons** [comment]
I've just started investigating this, but it might be something caused by the iframe's initial viewport width as perceived by Gutenberg. 🤔 

Upon first load of the whole Gutenframed Site Editor, the tabled and mobile previews are displayed with a calculated 0px width, hence why the editor "disappears".
Resizing the browser makes Gutenberg recalculate that width, and the preview shows up again.
Also, when reloading just the iframe (not the entire Gutenframe page) the previews work fine.

**Comment by Copons** [comment]
I've found the culprit but not what causes it:

https://github.com/WordPress/gutenberg/blob/77b642120b53b5c4d36b64dc3ac487c60e322463/packages/block-editor/src/components/use-resize-canvas/index.js#L19

For some reasons that I've yet to figure out, the site editor initial `window.innerWidth` is 0, whereas the post editor correctly starts with the actual browser width.
`useResizeCanvas` initializes the `actualWidth` in its internal state when the editor load, and only updates it on resize, so if it starts with `0` it will stay `0` until a resize happens.
