### ISSUE TITLE
Help Button Popover: Closing Dialog from Help FAB Search Result should Return Focus to Open Help Popover

### ISSUE THREAD

**Issue by jeryj** [Automattic/wp-calypso#44121]
#### Steps to reproduce

1. As a logged in WP user, click the blue ? in the bottom right of the screen 
2. Click a search result
3. Click the Read More Button
4. Close the dialog
5. Focus is now on the top-level window 

#### What I expected
1. As a logged in WP user, click the blue ? in the bottom right of the screen 
2. Click a search result
3. Click the Read More Button
4. Close the dialog
5. Focus is returned to the open Popover in its previous state

#### Browser / OS version
Any

I think this experience would be more accessible overall if we remove the secondary "Read More" button step and just went straight to the dialog.

**Comment by jordesign** [comment]
Closing this as the FAB is getting removed as part of the new Help Center work.
