### ISSUE TITLE
Customizer: Users are asked to accept cookies in the Customizer.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44126]
Users are asked to accept cookies in the Customizer, which is silly. Whatever mechanism that adds the cookies banner to the front-end should have a check for being in the Customizer preview.

<img width="1628" alt="Screen Shot 2020-07-13 at 3 35 09 PM" src="https://user-images.githubusercontent.com/349751/87360443-fc408900-c51e-11ea-9351-68cd0dac9943.png">

**Comment by aaronrobertshaw** [comment]
@kwight This widget is actually configurable via the Customizer. I initially looked to [disable display of the widget entirely](https://github.com/Automattic/jetpack/pull/16832) when in the Customizer but this means the user can't see the effect of any customizations they make to the widget. To make it a little more obvious that the widget is editable, I've [tweaked the location of the edit button](https://github.com/Automattic/jetpack/pull/16890) Customizer injects for the widget.

Do you think that this tweak is sufficient?

<img width="1823" alt="Screen Shot 2020-08-19 at 7 56 47 pm" src="https://user-images.githubusercontent.com/60436221/90620723-2d1a8900-e256-11ea-9369-fc302dca34cc.png">

**Comment by creativecoder** [comment]
@aaronrobertshaw That seems reasonable to me, and better to indicate that the banner will show and is editable than just hide it.

cc @davemart-in

**Comment by davemart-in** [comment]
Looks good to me. 👍
