### ISSUE TITLE
Premium Content: Block cannot be inserted on Atomic sites when Gutenberg Plugin is deactivated

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44160]
I tried to add a Premium Content block on an Atomic site, and it immediately errors.

<img width="1609" alt="Screen Shot 2020-07-14 at 3 38 20 PM" src="https://user-images.githubusercontent.com/349751/87483241-1befb400-c5e8-11ea-9c10-a483805125e8.png">

Errors are:
* `The block "premium-content/buttons" must have a registered category.`
* `The block "premium-content/login-button" must have a registered category.`
* `TypeError: Cannot read property 'attributes' of undefined`

See: pbAok1-1ez-p2

**Comment by gwwar** [comment]
This might be a testing setup error on our side.

**Comment by gwwar** [comment]
- Premium Content works well with Gutenberg 8.3.0. 
- With Gutenberg Disabled, we get block insertion errors (for buttons and the main block).
- With Gutenberg latest (8.5.1) we see the following errors in published view:
<img width="1569" alt="screen_shot_2020-07-15_at_2 01 13_pm" src="https://user-images.githubusercontent.com/1270189/87601720-836e3800-c6aa-11ea-90ee-f8e0477afbed.png">
