### ISSUE TITLE
(3P) Premium Blocks: Remove upgrade nudges

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#44168]
Let's remove [all upgrade nudges](https://github.com/Automattic/wp-calypso/issues/44056#issuecomment-658509735) from blocks that required a paid plan. This is not necessary, and even reducant.

**Comment by jeryj** [comment]
@sfougnier How are the upgrade nudges being handled on the frontend of the site? Could you point us to the related issue/p2 on how we should be handling the front-end? 

Here's the current implementation, for reference:

<img width="778" alt="Screen Shot 2020-07-27 at 10 48 35 AM" src="https://user-images.githubusercontent.com/967608/88562775-bbed0a80-cff6-11ea-8214-17149397c601.png">

**Comment by sfougnier** [comment]
The intent was for the messaging to be hidden in this state, pushing it to the pre-publish sidebar as more of a catch-all versus having static banners when trying to visit the page. Happy to chat more about this too, if you'd like.

**Comment by retrofox** [comment]
Thanks, Saul.
So, in short, is it ok removing all nudges from all sides (editor and frontend)?

**Comment by sfougnier** [comment]
> So, in short, is it ok removing all nudges from all sides (editor and frontend)?

Yes, all the old nudges should be removed, and the new nudges should only exist in the selected state of the block in the editor. @retrofox
