### ISSUE TITLE
Preview: "Edit" button expected behavior is confusing

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#44183]
#### Steps to reproduce

1. Starting at URL: `/view/{site}`
2. It's not clear what will happen when I click "Edit". I expect it to edit the page/post/whatever I'm looking at, but it always edits the home page.

#### What I expected

"Edit" is just vague enough that I expected to be able to edit whatever I was seeing in the preview.

#### What happened instead

Instead, I was only able to edit my home page. Maybe it would help to clarify in the button copy "Edit site" or "Edit homepage", if we can't know what page the previewer is looking at.

#### Screenshot / Video

Viewing the "About" page, I click "Edit" in the upper right:

<img width="1680" alt="Screen Shot 2020-07-15 at 2 22 15 PM" src="https://user-images.githubusercontent.com/2124984/87581338-c4644d80-c6a6-11ea-900b-ed4049ebe14c.png">

I'm brought to this editor, which looks nothing like what I wanted to edit:

<img width="1680" alt="Screen Shot 2020-07-15 at 2 22 37 PM" src="https://user-images.githubusercontent.com/2124984/87581366-cf1ee280-c6a6-11ea-8e70-ad8c7618e400.png">

**Comment by sunnyssr** [comment]
I would suggest to go with Edit Homepage button since the button for same action at home page ( url /home/{site} ) says Edit Homepage.
![image](https://user-images.githubusercontent.com/41870839/87594422-8c8ef180-c70a-11ea-913f-fb6acacc18fa.png)

I would love to send the pull request for this one if this sounds good to you.

**Comment by davemart-in** [comment]
> Maybe it would help to clarify in the button copy "Edit site" or "Edit homepage", if we can't know what page the previewer is looking at.

"Edit Homepage" sounds good to me.

> I would love to send the pull request for this one if this sounds good to you.

@sunnyssr it's all yours! Let me know once you have a PR ready and I'll make sure it gets reviewed and deployed. Thanks!

**Comment by lcollette** [comment]
Is it possible to have the edit button link to the page that's currently being viewed within the preview? That feels more expected to me.

**Comment by sunnyssr** [comment]
@lcollette 
Yes that's possible but that would require a way to figure out what exactly current URL refers to. It would require to figure out whether is a blog post or page. 
Thanks a lot!

Update: I tried to find a way to do so but this is beyond me since it would require to change things in preview page itself rather than in calypso because that's not sending the edit url alongside pathname when url changes.

**Comment by lcollette** [comment]
> Update: I tried to find a way to do so but this is beyond me since it would require to change things in preview page itself rather than in calypso because that's not sending the edit url alongside pathname when url changes.

Got it. Thanks so much for trying, @sunnyssr!! Really appreciate the effort. :)

**Comment by davemart-in** [comment]
@sunnyssr just following up to see if you're still working on this issue, or if you've moved on from it. You had mentioned:

> I tried to find a way to do so but this is beyond me 

and i was unsure whether that was related to Lynn's ask specifically or this whole issue. Mind clarifying when you have a chance?

Thanks!

**Comment by sunnyssr** [comment]
@davemart-in 
I've already sent the pull request for this one. Right now it makes sense to show Edit homepage instead of edit because whatever url you visit inside iframe and then click Edit, it will always take you to homepage edit page.

> and i was unsure whether that was related to Lynn's ask specifically or this whole issue. Mind clarifying when you have a chance?

It was specific to Lynn's ask since she was right that it would be better that on clicking edit it should take directly to the edit page of that particular preview page. This is beyond me, it is not something related to wp-calypso since it is not receiving edit url from iframe. This is only possible by making changes in preview page itself which require changes to send edit url from iframe to parent window.

**Comment by davemart-in** [comment]
> I've already sent the pull request for this one.

Thanks! Sorry I missed that. 

> Right now it makes sense to show Edit homepage instead of edit because whatever url you visit inside iframe and then click Edit, it will always take you to homepage edit page.

Sounds smart.

@jeryj would you or @mreishus mind reviewing and then deploying this please?

**Comment by mreishus** [comment]
The change looks good to me, but I am not completely familiar with the calypso process yet, and am unsure how to proceed.  I tagged the PR with "Needs Review" which I think will summon someone from the calypso team to look at it.  Also tagging @jeryj for input.

**Comment by sixhours** [comment]
@mreishus 👋 I added the String Freeze tag to make sure the new string is translated in our database, and if not, it can be sent for translation. Also tagged you as a reviewer so you can review the PR and approve it; no need for someone from Calypso to check it out. :)

**Comment by sunnyssr** [comment]
@sixhours 
I think translation would already be there in database since that string is being used at multiple places.

**Comment by getdave** [comment]
@davemart-in Building on the excellent work by @sunnyssr I've run some tests on the viability of adding the page target to the `Edit` button (eg: `Edit Homepage`) but it's [not going to cut the mustard](https://github.com/Automattic/wp-calypso/pull/44268#issuecomment-682479020).

To this end I started an analysis of if it's possible to [do what @lcollette suggested](https://github.com/Automattic/wp-calypso/issues/44183#issuecomment-660388542); namely:

> Is it possible to have the edit button link to the page that's currently being viewed within the preview?

I'll post my findings here as I go:

*

**Comment by davemart-in** [comment]
Thanks for the summary @getdave. Based on the amount of effort that has already gone into this issue I would say that unless we are close to wrapping things up that we might consider closing this one out as a "won't fix".

**Comment by getdave** [comment]
> Based on the amount of effort that has already gone into this issue I would say that unless we are close to wrapping things up that we might consider closing this one out as a "won't fix".

I think perhaps someone from @Automattic/team-calypso might be able to get this working if they can find a way to get the post ID from the path provided by the iframe postMessage.

I tried using a selector to grab a posts by `name` (ie: slug) but the posts in the state don't seem to be populated when in the Preview pane. 

If we can get some guidance here I think I could be doable or at least we'd be 100% clear that it isn't reasonably possible.

**Comment by davemart-in** [comment]
Our Janitorial backlog is starting to grow beyond what I'm comfortable with. I'm going to transfer this to the Ajax team's backlog @obenland.

**Comment by kristenzuck** [comment]
@obenland I see this is listed in the Ajax Global Backlog board for Q2 2021 - do you think this is something the team will be able to tackle? Just following up here on the stale bot flag.

**Comment by obenland** [comment]
It should probably reprioritized as part of a bundle of tasks

**Comment by sixhours** [comment]
In looking at this again, I'm inclined to say that "Edit" is a "good enough" label, given the technical complexities of both making the button copy too long for many languages, or making the button point to a specific post/page. We also don't know that this is actually a point of user confusion; I don't see any specific tickets or reports attached to this, so I'm assuming it's not something that comes up often. I'd propose we wontfix it for now.
