### ISSUE TITLE
Composite Checkout: Default billing info code and country can be mismatched.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44180]
Being in Canada, I assume checkout determined I have a postal code – but the default country dropdown is US. Can we align them one way or the other?

<img width="1158" alt="Screen Shot 2020-07-15 at 10 17 34 AM" src="https://user-images.githubusercontent.com/349751/87575892-725f0000-c685-11ea-93f9-598670810fe1.png">

cc/ @michaeldcain @sirbrillig

**Comment by michaeldcain** [comment]
@nbloomf: should this have been fixed with #43955?

**Comment by michaeldcain** [comment]
@kwight were you proxied? If so, it might have been through the US proxy. I believe "Postal Code" is shown by default for US too.

**Comment by kwight** [comment]
Yea, I'm pretty sure I would have been proxied, with the store sandboxed.

**Comment by michaeldcain** [comment]
I just testing with a VPN and unproxied browser - seems to be working as expected. Closing.
