### ISSUE TITLE
Marketing: Rogue guided tour

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#44194]
I was clicking through the different sub tabs of the marketing section and a guided tour appeared. I suppose I clicked quickly enough to a new tab of the marketing section and it caused this to happen:

![image](https://user-images.githubusercontent.com/437258/87614261-86365080-c6dd-11ea-8373-52d723b21d10.png)

That tour tip stayed on the screen (at x0,y0 presumably because the div it was supposed to target was removed from the dom when I switched tabs?) as I clicked from tab to tab. 

Larger question is do we need to use a guide tour here or could we have a tooltip appear on hover or something else on the sharing screen?

**Comment by Aurorum** [comment]
> Larger question is do we need to use a guide tour here or could we have a tooltip appear on hover or something else on the sharing screen?

Hmm, this is supposed to appear after clicking the action of the "Connect accounts" task (#41018) which I think a guided tour makes sense for, but I'm not sure why it's appearing randomly and in that location.

**Comment by rickybanister** [comment]
Ah, got it, thanks for the context! I did not click through from the task card, so I think there's an underlying bug here.

**Comment by pablinos** [comment]
We had to revert #44329 as the tour stopped displaying consistently. So far the change in #44550 looks to have fixed it
