### ISSUE TITLE
Gutenboarding: checkout screen lacks context and cohesion with the flow

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#44219]
@ianstewart pointed out yesterday that the 'new' checkout screen feels out of place within Gutenboarding:

![image](https://user-images.githubusercontent.com/437258/87681402-a18c7480-c74c-11ea-8ecd-a7e95cec3e1a.png)

It's on a gray background instead of white, and it lacks any sort of top bar (the white gutenboarding top bar with wp logo would make sense).

Checkout can appear during the initial signup flow, but also the launch flow. I think it'd be appropriate to have it be styled to match Gutenboarding (if technically possible) in both places.

**Comment by olaolusoga** [comment]
Here's mock with white bg, title, sub title, and topbar all pulled from Gutenboarding. 

<img width="1440" alt="Payment" src="https://user-images.githubusercontent.com/1382943/87686325-5f663180-c752-11ea-89ea-85940cc989c3.png">

**Comment by razvanpapadopol** [comment]
The mock is looking awesome 👍 
Let's see if we can also customise the CTA button text depending on the flow (pcbO8q-y-p2#comment-42)

**Comment by rickybanister** [comment]
Control has an 'X' in the blue top bar that lands customers on /plans and gives them an opportunity to rethinking their purchase, possibly buying a less expensive plan. That may be worth considering for this design as well.

**Comment by razvanpapadopol** [comment]
> Control has an 'X' in the blue top bar that lands customers on /plans and gives them an opportunity to rethinking their purchase, possibly buying a less expensive plan. That may be worth considering for this design as well.

We've re-introduced for now the top bar that shows up in control and in the rest of Calypso in #49567

**Comment by simison** [comment]
@razvanpapadopol is the above PR enough to close this issue or was there more needed?

![image](https://user-images.githubusercontent.com/87168/108183109-7159e980-7112-11eb-844a-9983e533d16c.png)

**Comment by razvanpapadopol** [comment]
That PR just enabled a way to abandon checkout (with X from top bar) without having to remove every product.

To achieve some level of cohesion with Gutenboarding we need to add some custom styling to Checkout. We did this once for the old checkout: https://github.com/Automattic/wp-calypso/pull/39447/files#diff-9e84174e2ab1e30e508aaac500ed88c71c22f15964a45eafa26bb7f3be25f15b
