### ISSUE TITLE
Home Screen: Checklist step asks users to add a menu — when one is created by default already

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#44240]
The title of this issue covers the issue but to reproduce …

Create a new site.

Note the instructions about the checklist in the menu.

![image](https://user-images.githubusercontent.com/545779/87716000-ca743000-c773-11ea-84da-38e9e96de90e.png)

Follow instructions and visit the Customizer.

![image](https://user-images.githubusercontent.com/545779/87716047-dfe95a00-c773-11ea-8809-006614f225d4.png)

Note that a menu with multiple pages already exists by default.

cc @lcollette

**Comment by ianstewart** [comment]
This issue can still be reproduced.

**Comment by michaeldcain** [comment]
I believe we should be able to check if a menu is assigned on the user's site and conditionally switch the heading to say "Edit your site menu"

**Comment by simison** [comment]
There are quite a few things going on here simultaneously, and I think the incorrect copy is the least of our problems:

- How customers know where to create or edit their site's navigation? I believe the current checklist item is mostly "patching" this confusion.
- On the flip side, while they now know where to edit the menu, editing navigation is really complex. It's adding to the confusion by introducing this step pretty early in the site creation, and hence we thought to just remove the whole step (https://github.com/Automattic/wp-calypso/issues/47334), or at least move it down in the list (https://github.com/Automattic/wp-calypso/issues/49706). On the other hand, removing would lose the guidance.
- Lastly, it's prompting to create a menu when one already exists. We could either edit the copy or remove the whole step.
- We also now have themes (blank canvas) and designs that don't have a header/footer (and hence navigation) at all. We don't guide how to enable header/footer/navigation (nor relation between those) in any way.

Non-risky actions I see are:
- Bump it lower in the list (https://github.com/Automattic/wp-calypso/issues/49706)
- Change copy in this scenario to "edit the site menu" if it's trivial.

Anything else feels like we'd potentially increase the confusion accidentally. Does that make things better while we wait for FSE sites, which of course will change everything for this task completely? Are there other simple actions we could do to make this much better for soon-to-be-legacy sites? @olaolusoga & @ollierozdarz.

cc @autumnfjeld just to follow the convo at this point.

**Comment by roo2** [comment]
We just bumped it lower in the list (#49706)

It looks like it is trivial to change the copy to "Edit the site menu" in https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js#186

**Comment by ollierozdarz** [comment]
> Non-risky actions I see are:

> Bump it lower in the list (#49706)
> Change copy in this scenario to "edit the site menu" if it's trivial.

These feel like the correct course of action to me, @simison 🙂. A quick and iterative win while this gets more thought.
