### ISSUE TITLE
Editor: Trash icon gets "stuck" if you create two posts in a row and trash the second one

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#4424]
If you create two posts in a row, trashing the second post leaves the trash icon red and blinking after going back to the first post, and the trash icon doesn't respond if you try to trash that first post.
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Select a site and write/save a draft post
3. Click the new post icon in the top right, and select a site from the site picker to start a new post
4. Write/save a second draft post
5. Click the trash icon in the top right and confirm you want to trash the second draft
#### What I expected

I expected that the second draft post would be trashed, and I would be taken back to the previous screen I was on (either the previous draft I worked on, or out of the editor to whatever screen I was on before that) to continue working as usual.
#### What happened instead

I was taken back to the previous draft I worked on, but the trash icon was still red and blinking. If I tried to trash that post, too, the trash icon didn't react (it continued blinking).
#### Browser / OS version

Mac OS X, in Chrome 49.0.2623.87, Safari 9.1, and Firefox 45.0.1 (the trash icon was red but didn't blink in Firefox). Also seen in the Mac desktop app 1.3.1-alpha.
#### Screenshot / Video

![trash-icon-issue](https://cloud.githubusercontent.com/assets/8658164/14148058/ea6e1adc-f695-11e5-93a9-d1611e1d3ee4.gif)

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Confirmed this is still an issue.

**Comment by lancewillett** [comment]
I saw this today with the same steps — after trashing from inside the editor session for post 1, navigated to post 2 and saw the red trash icon still blinking.

**Comment by lancewillett** [comment]
Closing as low priority. We can bring it up again in the future if we see more reports.
