### ISSUE TITLE
Extract placeholder block attribute while parsing blocks

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#44245]
D46471-code uncovered the need for a shared parser trait? to parse out the placeholder attribute, it seems to be available to anything with a RichText block base sp we may want to apply this across the board https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/rich-text

e.g.

```
<!-- wp:paragraph {"placeholder":"Add hero content, which is typically an introductory area of a page accompanied by call to action or two.","style":{"color":{"text":"#d3d719"}}} -->
<p class="has-text-color" style="color:#d3d719;">Hero content, whereby hot dogs always taste better with both ketchup <strong><em>and</em></strong> mustard.</p>
<!-- /wp:paragraph -->
```

**Comment by deBhal** [comment]
@andrewserong sorted this one with code-D46848
