### ISSUE TITLE
Newsletter: allow not send blog post as an email

### ISSUE THREAD

**Issue by kristenzuck** [Automattic/wp-calypso#44263]
Jetpack issue https://github.com/Automattic/jetpack/issues/10876

This was added to our HappOps Product Support Github repo ( 20-GH-happops ) as an item that is low priority, but likely a quick win. We are often asked by customers for the ability to publish a new post on a blog without notifying their subscribers. 

To name a few situations where this has come up - some customers have their own mailing tool they use to notify subscribers, some customers post frequently and get complaints about too many emails, some want to backdate posts and not notify subscribers, and some customers have private posts they would like to make public without notifying anyone. 

Historically this has only been surfaced to my knowledge on WPCOM Ideas in several different threads:

- Two reports here: pKdGS-Wi-p2
- 17 reports here: pKdGS-78-p2 
- 7 reports here: pKdGS-1IG-p2
- 5 reports here: pKdGS-1z4-p2

The above is definitely not an inclusive list of all instances where this has been requested, as not all are noted here in WPCOM Ideas.

**Comment by davemart-in** [comment]
This likely will affect a number of various flows. We'll need to do some extended testing to ensure that we aren't breaking anything.

**Comment by pento** [comment]
On researching this, I discovered that there's already post meta check to help with this. If `_jetpack_dont_email_post_to_subs` is set to `true` on the post, the post won't be emailed to subscribers.

There used to be an option in the classic editor to do this, but it hasn't been ported to the block editor (Automattic/jetpack#10876). There was a PR started a while back for this (Automattic/jetpack#14021), but it hasn't been touched in a while.

It seems like that's a good place to start on providing this option.

**Comment by davemart-in** [comment]
That's awesome. Thanks for doing that research @pento!

**Comment by jordesign** [comment]
Just noting anecdotally that we'll regularly (every month or two) see a workaround shared in Slack for this when users are asking for this option.

* Make Site Private
* Publish Post
* Make site public again

Recent example (I haven't dug further yet).
https://a8c.slack.com/archives/C03TY6J1A/p1597766660424800

**Comment by jordesign** [comment]
Another instance of a similar conversation here:
p1598784591069200-slack-C03TY6J1A

**Comment by jordesign** [comment]
On further testing - the other option is to turn _off_ the Subscriptions module in Jetpack before you publish the post. This would stop notification emails being sent

**Comment by tehjaymo** [comment]
I just came across this conversation whilst searching for an answer to the same problem. Would be a quality of life upgrade for many I think.

**Comment by kosiew** [comment]
#3810829-zen - another request to publish post without notifying subscribers

**Comment by kelasante** [comment]
#27800257-hc - another request to publish a post without notifying subscribers

**Comment by kristenzuck** [comment]
Just a nudge that this is still an issue and request that comes up frequently!

**Comment by autumnfjeld** [comment]
@inaikem Given the work of the Subscriptions pod, does this work fall in your scope?  Just want to make sure we're aligned in work and not getting in the way of work you have planned.     Should all work related to subscriptions/notifications/email be directed to the Subscriptions pod?

cc: @jordesign

**Comment by kwight** [comment]
> Should all work related to subscriptions/notifications/email be directed to the Subscriptions pod?

@autumnfjeld That's fine, sure – yes, our pods have the potential for some overlap. 🙃

**Comment by cuemarie** [comment]
+1 as I'd love to see this as well! I've had many users who'd like more control over this. Thanks!

**Comment by vinnykaur** [comment]
Another request here - hc-35289936

**Comment by formosattic** [comment]
A copy/paste of my report at https://github.com/Automattic/wp-calypso/issues/60377

### What

Users regularly, though maybe not that frequently, ask about publishing a post without sending notifications to users.

Related interactions:

* https://wordpress.com/forums/topic/how-to-publish-without-notifying-subscribers-2/
* https://wordpress.com/forums/topic/can-i-publish-a-post-without-notifying-my-blog-followers/
* https://wordpress.com/forums/topic/how-to-post-without-sending-emails-to-subscribers/
*  33589070-hc

### Why

Various reasons:

* avoid spamming their followers' inboxes
* have better control over content (post sent to email can't be edited by site author)

Right now, we suggest this cumbersome workaround:

1.	Make the site private
2.	Publish the post (post must be Public, else if it's Private, then made Public later, a notification will show)
3.	Make the site public again

Email notifications are hard to troubleshoot. And if the workaround isn't properly followed, the mistake is pretty unforgiving.

Also, plugin solutions outlined at https://www.mailpoet.com/blog/wordpress-post-notifications-plugins/

**Comment by cuemarie** [comment]
Had another chat today where this would have definitely helped: 36113046-hc

User had already published a page, and their theme could only feature that content as a post. They didn't want to notify their thousands of followers of a republish, and the workarounds were a bit taxing, so they decided to leave it for now.

**Comment by tanjoymor** [comment]
Had another chat today asking about this: 36070060-hc

Advised on turning off the Jetpack Subscription module.
Suggested using MailPoet instead.
+1 to us offering a per post option for this the way we do for the Publicize feature.

Just to note that the previously suggested work around of making the site Private before publishing is reported to not actually work.

**Comment by supernovia** [comment]
Requested here: https://wordpress.com/forums/topic/blog-post-notification-settings/

**Comment by devNigel** [comment]
Another request: 36479199-hc

**Comment by NoHopeRadio** [comment]
Adding another name to the petition:

8172274-hc

**Comment by happychait** [comment]
Another one in 5608939-zen

**Comment by rw-ye** [comment]
+1 5709163-zd-woothemes

**Comment by danielk-am** [comment]
Another request: 2510837-hc

**Comment by jp-imagines** [comment]
Another request in 6474782-zd-woothemes. WoA site, so suggested disabling Jetpack's Subscription module while publishing a post as a workaround.

Now that we have additional "newsletter" controls on posts (i.e. posts available to all viewers, only subscribers, and only paid subscribers), it would certainly be nice to have separate controls for the post notification email directly in the editor too.

**Comment by jamiepalatnik** [comment]
Another request: 6706825-zd-a8c
Site is AT so suggested disabling Jetpack Subscriptions module.

**Comment by autumnfjeld** [comment]
@simison  is this something Zap could take on? Or maybe already on the Newsletter roadmap?

**Comment by simison** [comment]
Yes! On our roadmap already (https://github.com/Automattic/wp-calypso/issues/77254). Thanks for the ping.

Note that for AT and Jetpack sites they can [use some code to disable sending for specific categories.](https://jetpack.com/blog/hook-month-control-subscriptions/)

**Comment by simison** [comment]
Adding more requests from https://github.com/Automattic/wp-calypso/issues/77254 which I'll close and use this issue instead:

- p1684787107103569-slack-C052XEUUBL4
- p58i-euJ-p2#comment-58221
- p1HpG7-ncr-p2
- p1686882865579699-slack-C052XEUUBL4
- p7pQDF-8Ms-p2#comment-23733
- p1691057803217889-slack-C052XEUUBL4

Jetpack ticket https://github.com/Automattic/jetpack/issues/10876

Also potential design from p9Jlb4-8vw-p2:

<img width="282" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/fbcda2ab-64fd-4d0a-979a-70d15b29990c">

**Comment by simison** [comment]
Came up in p9Jlb4-aej-p2 and ticket 7430065-zd-a8c

[Looked into](https://github.com/Automattic/jetpack/pull/34321) adding a filter for advanced usage but we'll need the UI for customers as well.

**Comment by simison** [comment]
Shipped for Jetpack & WP.com sites.

<img width="279" alt="291715567-6f6e783f-f122-4a83-8559-3d3e4004e8f5" src="https://github.com/Automattic/wp-calypso/assets/87168/d668e8ca-e24b-490d-8d1e-47936b47686c">

Internal ref p7DVsv-jxz-p2
