### ISSUE TITLE
Checklist: Akismet task broken

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#44267]
#### Steps to reproduce

1. Create JN site
2. Connect site
3. Purchase personal, premium, or professional
4. Go to https://wordpress.com/plans/my-plan/$site, where $site is a slug like `example.com`
5. Observe that Akismet task does not complete and the spinner spins and spins

#### What I expected

The Akismet task to complete and the spinner to stop spinning

#### What happened instead

The task never completed

#### Browser / OS version

Mac Catalina and Chrome

#### Screenshot / Video

<img width="1239" alt="Screen Shot 2020-07-18 at 12 00 10 AM" src="https://user-images.githubusercontent.com/1126811/87845092-aefb4900-c889-11ea-91c5-949fd629a898.png">

**Comment by cleacos** [comment]
That can happen if you have `public-api.wordpress.com` pointing to your sandbox, could you check it?

**Comment by ebinnion** [comment]
Nice catch. I was not able to reproduce today, so it is very likely that I had my sandbox on.
