### ISSUE TITLE
Reader: team icon fill is white in non-touch browsers, in small screens

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#4427]
Raised by @karmatosed here: https://github.com/Automattic/wp-desktop/issues/143

Minor design niggle. :)

<img width="720" alt="screen shot 2016-03-30 at 10 46 29" src="https://cloud.githubusercontent.com/assets/66797/14151823/af4c84ec-f664-11e5-8b02-09bb00e97e94.png">

CSS source: https://github.com/Automattic/wp-calypso/blob/498edcd30ce6aeb92e5af342ea95e24514995ca7/client/layout/sidebar/style.scss#L237

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/read/a8c
2. Using Chrome dev tools, resize your browser to 659 px wide
3. Open the Reader sidebar, showing teams (in my case, a8c for Automattic team)
4. Click the team link to see the Reader items in that team list
5. Go back to the sidebar &rarr; the gridicon fill is now white (should be medium-blue)

#### What I expected
The team's icon should be colored the same as other icons in the Reader sidebar.

#### What happened instead
The team icon is white.

#### Browser / OS version
Mac-n-Chrome, also OS X desktop app -- used in small screen size.

#### Screenshot / Video
Available upon request (I saved it privately due to sensitive content.)

**Comment by lancewillett** [comment]
Note: this is a8c-only but still happening for me in testing with the same steps above.

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/6980

**Comment by lancewillett** [comment]
Wanted to drop a (late) note confirming this fix.

iPhone 6+

![img_6450](https://cloud.githubusercontent.com/assets/66797/19276237/9f46ee92-8f8a-11e6-8085-5e2feff3ed24.PNG)
