### ISSUE TITLE
Contact Support: Duplicated form labels for "How can we help?"

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#44287]
<img width="743" alt="Screen Shot 2020-07-20 at 2 31 43 PM" src="https://user-images.githubusercontent.com/2124984/87973342-5baa1600-ca96-11ea-8d03-c7c701fb0d9b.png">

#### Steps to reproduce

1. Starting at URL: `/help/contact`
2. The first and last fields have the same label, "How can we help?"

#### What I expected

Thinking in terms of a descriptive form field label for accessibility purposes, the label should briefly describe what we want the user to put in that field. Something like "Tell us more about the problem" or "Describe the issue" for the textarea input would prevent duplicated copy and give more context for the content of that field.

**Comment by Dillweed5446** [comment]
I'll fix this!  I'm going to go ahead and use "Tell us more about the problem".  I'll tag you in the PR.
