### ISSUE TITLE
Premium Content: The block makes unnecessary API calls on the front-end.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44290]
Part of initializing the Premium Content blocks is to make an API call to `/memberships/status`, which is important in the editor. This is happening both in the editor and the front-end for viewers, but it's not needed for the latter. In addition, the call fails with a 404 because the endpoint is not available to the viewer.

The call occurs as part of `configurePremiumContentBlocks`: https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/premium-content/index.js#L128

**Comment by BogdanUngureanu** [comment]
I wasn't able to trigger the API call from the front-end, probably because the block has been refactored in the meantime. Closing this since no changes are required. :)
