### ISSUE TITLE
Premium Content: Subscribers are shown the unsubscribed view when the Gutenberg plugin is disabled.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44293]
On Atomic, if a Premium Content plan owner adds a PC block to a published post and then deactivates Gutenberg, they will continue to see the subscribed view on the front-end. Subscribers, however, are shown the unsubscribed view, prompting them to subscribe again. If they try to subscribe again, they'll be told (rightly) that they are already subscribed.

<img width="1039" alt="Screen Shot 2020-07-20 at 4 28 44 PM" src="https://user-images.githubusercontent.com/349751/87996313-9f0c8080-caa6-11ea-8038-a1d0c7e382b6.png">

**Comment by kwight** [comment]
I think we need a more proper "broken" state to show if Gutenberg is missing. It'll avoid confusion, and likely result in site owner feedback to fix it.

**Comment by BogdanUngureanu** [comment]
Closing this as I'm unable to reproduce this anymore. It's possible that the issue was caused because an older Gutenberg's version from 2020.
