### ISSUE TITLE
Home: Main renders twice on site switch

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#44291]
Noticed by @kwight in https://github.com/Automattic/wp-calypso/pull/44266 when switching sites on My Home, the page will render everything twice. This has a side effect of counting card impressions twice.

I've already tried using `useRef` to keep track of previous state in `useEffect` (which doesn't work since the component is unmounts) and doing a deep equals in the Home reducer to avoid unnecessary renders. Something else is causing the multiple renders.

<img width="672" alt="Screen Shot 2020-07-20 at 3 30 04 PM" src="https://user-images.githubusercontent.com/1270189/87994617-489d4300-caa2-11ea-98c0-3e14610e07b7.png">

<img width="1540" alt="87984003-2699c580-ca8e-11ea-9e78-50218822fe47" src="https://user-images.githubusercontent.com/1270189/87994546-0f64d300-caa2-11ea-8a23-9c21736fc465.png">

To Reproduce:
1. Set `localStorage.debug = 'calypso:analytics*'` in browser console
2. Have multiple WordPress.com sites ideally with different primary tasks set
3. Visit http://calypso.localhost:3000/home/siteA and notice the `calypso_customer_home_card_impression` events. (We should see one per card on the page.
4. Switch to siteB
5. Notice the double impression, and unmount events from PageViewTracker

**Comment by autumnfjeld** [comment]
@deBhal confirms this is fixed.
