### ISSUE TITLE
Plugins: No navigation available on placeholder/upsell page on mobile

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#443]
If you try to view the Plugins page from a WordPress.com site, you get a message about buying a Business plan so that you can use the plugins provided there. There is no sidebar-navigation available, which means you're stuck on this page without either clicking the button, or using the masterbar.

![44f28f28-7e5b-11e5-9891-7719ccd5b272](https://cloud.githubusercontent.com/assets/11487924/11326133/c49812ee-912e-11e5-9a47-177227e86721.jpg)

At the very least, I expect there to be the top navigation block on this page, so that when I hit it and don't want to Upgrade, I can get back to the sidebar and try some other link out.

**Comment by rickybanister** [comment]
This page needs a `HeaderCake`
