### ISSUE TITLE
Use description instead of snippet variable in `SearchPreview`

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#44308]
In order to keep the Social Preview components consistent we should change the `snippet` variable of the component to `description`.

The `SearchPreview` component will be part of the Social Previews NPM package after #44170 is merged. That PR already introduces `description` for new implementations. We just need to safely deprecate the `snippet` variable.

#### Context / Source
https://github.com/Automattic/wp-calypso/blob/173ca423881c6b883ad4e45159dc3c1b4e9b3c9e/client/components/seo-preview-pane/index.jsx#L120-L167

**Comment by getdave** [comment]
@cpapazoglou You can probably make use of [`@wordpress/deprecated`](https://github.com/WordPress/gutenberg/tree/201ca8299e258f535b2a470134dd0ad3cd13de1f/packages/deprecated ) assuming you include as a dependency.
