### ISSUE TITLE
Publicize: example images are not retina

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#44317]
On the Connections settings page, each service includes screenshots explaining how the feature works. Those images are appearing non-retina:

![image](https://user-images.githubusercontent.com/437258/88087756-67a9dc80-cb57-11ea-8e6b-79e069a2391e.png)

**Comment by olesyabrk** [comment]
The initial screenshots are too low-res to export x2 for retina, is it OK to take new screenshots? @rickybanister

**Comment by rickybanister** [comment]
Absolutely

**Comment by olesyabrk** [comment]
Here are the updated screenshots in high fidelity. 
cc: @sixhours or @danhauk for assistance in updating them in code. 

<img width="484" alt="Twitter-1" src="https://user-images.githubusercontent.com/51215741/89577884-33d0e700-d7e6-11ea-8030-bf69588ad956.png">
<img width="484" alt="LInkedin" src="https://user-images.githubusercontent.com/51215741/89577893-359aaa80-d7e6-11ea-9fab-79cdebf5af06.png">
<img width="484" alt="Tumblr" src="https://user-images.githubusercontent.com/51215741/89577898-36cbd780-d7e6-11ea-99a2-6c5815702e55.png">
<img width="484" alt="Twitter" src="https://user-images.githubusercontent.com/51215741/89577900-37fd0480-d7e6-11ea-9679-1483663e27c4.png">
<img width="484" alt="Facebook" src="https://user-images.githubusercontent.com/51215741/89577901-37fd0480-d7e6-11ea-93b8-9cab598ad146.png">
<img width="484" alt="Sharing buttons" src="https://user-images.githubusercontent.com/51215741/89578654-57e0f800-d7e7-11ea-9652-06e5f8e4cab5.png">

**Comment by sixhours** [comment]
@olesyabrk Could you label each of the images so I know where each of them goes? I started looking at this, but realized I don't know what LinkedIn posts look like these days, and it seems like there are multiple Twitter screenshots... 😅

**Comment by olesyabrk** [comment]
Does this help @sixhours ? [Figma](https://www.figma.com/file/5UpeZWWhMdQ7IJXJH66FQ4/Bottle-Pickup?node-id=4228%3A2)

Every image corresponds to 
![image](https://user-images.githubusercontent.com/51215741/89813111-0641b180-daf6-11ea-960f-54ec2938c71c.png)

**Comment by sixhours** [comment]
I started a PR for this at #44809 !

We should probably update the Instagram and Google Photos images while we're in there:

<img width="1076" alt="Screen Shot 2020-08-10 at 3 36 39 PM" src="https://user-images.githubusercontent.com/2124984/89823448-7fa1ca00-db1f-11ea-9506-c7c4c18e5d06.png">

The Mailchimp one looks fine.

Can you grab the screenshots for Insta and Google Photos @olesyabrk ?

**Comment by olesyabrk** [comment]
@sixhours I can for Instagram, but according to marketing we don't share anything on Google Photos and I don't want to take a screenshot of mine. Ideas?

**Comment by sixhours** [comment]
I actually don't have an account on Google Photos, so maybe I'll upload some of my old stuff (pretty flower pictures or what have you) and we can use that!

**Comment by olesyabrk** [comment]
That would be great, Caroline! Thank you!

**Comment by sixhours** [comment]
It's up on the PR now! Just need the Instagram one and we can get the PR ready for review.

**Comment by olesyabrk** [comment]
<img width="720" alt="instagram" src="https://user-images.githubusercontent.com/51215741/89948223-9527fa00-dbda-11ea-84ee-ad6f55032dc6.png">
Here you go!

**Comment by sixhours** [comment]
Updated the PR with the Instagram image and marked it for review!
