### ISSUE TITLE
Editor: update editor deprecation messaging

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#44328]
Gathered from pb5gDS-Gp-p2

- [x]  Add an animated gif showing how to add and use a classic block to new posts to email notice and support pages. - [gif below](https://github.com/Automattic/wp-calypso/issues/44328#issuecomment-664080260) wasn't sure were this can be hosted for including in email
- [x]  Remove (or move to another place) the line "The older WordPress.com editor is no longer available." in the email text. 
 D44715-code
- [x]  Replace "get started with the block editor." link with https://wordpress.com/support/wordpress-editor/ D44715-code
- [x]  Link https://wordpress.com/support/wordpress-editor/ in welcome guide content. - ~#44444~ - D46903-code
- [x]  Include this video in support docs? https://www.youtube.com/watch?v=BkQlTuJ4BH8

**Comment by glendaviesnz** [comment]
> Link https://wordpress.com/support/wordpress-editor/ in welcome guide content.

do you mean in the new classic block welcome guide? 
<img width="278" alt="classic" src="https://user-images.githubusercontent.com/3629020/88127998-1c5ffe80-cc29-11ea-97d8-4d76f7e9f4a4.png">

**Comment by creativecoder** [comment]
> do you mean in the new classic block welcome guide?

Yes, that's what I meant--though I haven't looked yet to see if or where in the content it makes sense to add that.

**Comment by aaronrobertshaw** [comment]
> Include this video in support docs? https://www.youtube.com/watch?v=BkQlTuJ4BH8

This video is already on the [WordPress editor support page](https://wordpress.com/support/wordpress-editor/). I'm not sure it needs to be on any other pages. The [general editors page](https://wordpress.com/support/editors/) pretty clearly links to the WordPress editor support page.

Perhaps the video could be made more prominent on the [WordPress editor page](https://wordpress.com/support/wordpress-editor/) rather than just under the "Adding a Block" section?

**Comment by glendaviesnz** [comment]
Not sure if #44444 is worth merging if it is going to delay things while we wait for translation updates.

**Comment by glendaviesnz** [comment]
@creativecoder - here is an animated gif of adding the classic block - I wasn't sure about where this would be best saved for linking in the email that goes out:

![insert-classic](https://user-images.githubusercontent.com/3629020/88496614-dc768e00-d011-11ea-9420-2bb3b5952df3.gif)

**Comment by scruffian** [comment]
> Include this video in support docs? https://www.youtube.com/watch?v=BkQlTuJ4BH8

Added to [this document](https://wordpress.com/support/switching-from-the-classic-to-the-block-editor/)

**Comment by creativecoder** [comment]
> here is an animated gif of adding the classic block - I wasn't sure about where this would be best saved for linking in the email that goes out:

@glendaviesnz There are some insights from p7H4VZ-2BH-p2

Looks like the image can be added to wpcom along side the editor deprecation email template. Take a look at the `jetpack-scan-announce.php` template for prior art.

**Comment by scruffian** [comment]
Added a patch for the images here: D47069-code
