### ISSUE TITLE
Posts dropdown wraps when the selected item is short

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#4433]
#### Steps to reproduce
1. Starting at URL: 
2. Make your screen small enough to get the dropdown
3. Select Drafts
4. Open the dropdown and be amazed

#### Browser / OS version
MacnChrome latest

#### Screenshot / Video
![image](https://cloud.githubusercontent.com/assets/1123119/14159055/a4cae670-f688-11e5-9699-fa5fba6d1e01.png)

Reported by @helenhousandi

**Comment by lancewillett** [comment]
Should this be captured by a https://wpcalypso.wordpress.com/devdocs/design change or example? To avoid it happening again.

**Comment by lancewillett** [comment]
Duplicate of #4971
