### ISSUE TITLE
Premium Content: Button styling options

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#44333]
Comparing Premium Content functionality to Buttons block I found some missing styling options:
 * no block styles ( Buttons block offers two - fill, outline).
 * there are differences between Subscribe and Log in button. Subscribe button doesn’t have a border-radius option or the text formatting options.

#### Steps to reproduce

1. Add a Premium Content block to a post or a page.
2. Customize Subscribe and Log in buttons.
3. Note the differences in styling options available between both buttons.
4. Add a Buttons block below. Note the additional block style options in the sidebar:

![image](https://user-images.githubusercontent.com/4550351/88136348-5f6fa100-cc2c-11ea-852d-85dabb7dcde6.png)

Log in button settings:
![image](https://user-images.githubusercontent.com/4550351/88136093-e40def80-cc2b-11ea-891f-c1cabea638ee.png)

Subscribe button settings:
![image](https://user-images.githubusercontent.com/4550351/88136208-1ddef600-cc2c-11ea-8c29-4c61d361728f.png)

#### What I expected
Both Subscrbe and Log in buttons should offer the same styling options. Ideally, we would have parity with Buttons block in regards to styling options.

**Comment by glendaviesnz** [comment]
Looks like it is only the style options that were different on login button now. Fix for this added at https://github.com/Automattic/wp-calypso/pull/46227
