### ISSUE TITLE
Payments: Button styling options

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#44334]
Similar to #44333 Payments button is missing some styling options:
* no block styles ( Buttons block offers two - fill, outline)
* doesn’t have a border-radius option or the text formatting options

#### Steps to reproduce

1. Add a Payments block to a post or a page. Note the customization options available.
2. Add a Buttons block below. Note the additional block style options and border-radius in the sidebar as well as text styling options.
3. I also noticed Payments button offers wide and full alignment options, which don't make sense in a context of a button (Buttons block does not offer those).

Payments button settings:
![image](https://user-images.githubusercontent.com/4550351/88137196-60a1cd80-cc2e-11ea-9dbd-6452e9c8a0fc.png)

Buttons block settings:
![image](https://user-images.githubusercontent.com/4550351/88137298-99da3d80-cc2e-11ea-945d-180710606b32.png)

#### What I expected
For the Payments button to offer the same customizations options as the Buttons block.

**Comment by apeatling** [comment]
This is fixed based on me looking at the payments button as it exists now:

<img width="1719" alt="Screen Shot 2020-10-05 at 2 15 51 PM" src="https://user-images.githubusercontent.com/1464705/95132866-477cc900-0715-11eb-8685-338b911f6f6d.png">
