### ISSUE TITLE
Reader: 'Followed Sites/All' shouldn't show P2s

### ISSUE THREAD

**Issue by evilluendas** [Automattic/wp-calypso#44354]
#### Steps to reproduce

Precondition: Follow a few sites, follow at least one non-A8C P2.

1. Starting at URL: https://wordpress.com/read, make sure that you're at Followed Sites / All.
2. Notice that among the posts in that stream you'll see posts from that non-A8C P2.

Since the site breakdown and the "Followed P2s" category is only available for Automatticians, you'd need to use an a11n account.

#### What I expected
To only see posts from sites belonging to "Followed Sites", so no P2 content.

#### What happened instead
It displayed content from P2s.

#### Browser / OS version
Chrome 84, MacOSX Catalina

**Comment by davemart-in** [comment]
Looking at the Reader, I no longer see a "Followed P2's" section. I believe it has been renamed to "Automattic" to eliminate this confusion. I don't think the goal with that section was ever to show all P2's (even non A8c P2's). That section was just for Automattic specific P2's. I believe it is expected for non A8c P2's to show up in the regular feed if you follow them. Closing out this issue.
