### ISSUE TITLE
Donations: avoid __experimental features or do not register block when features are not available

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#44365]
Let's audit to see if we really need any __experimental features from Gutenberg. If not, let's remove usages, since disabling the development plugin will still register the block but cause JS errors. For example `import { __experimentalBlock as Block } from '@wordpress/block-editor';`

<img width="511" alt="Screen Shot 2020-07-22 at 9 43 57 AM" src="https://user-images.githubusercontent.com/1270189/88234309-94302800-cc2d-11ea-8885-f58c611413f3.png">

If for some reason, we do really need the functionality, let's feature sniff and avoid block registration when those features are unavailable.

**Comment by mmtr** [comment]
Oh, already did this in https://github.com/Automattic/jetpack/pull/16545 before noting you created a separate issue for handling it in a follow up. We can close this one out then.

**Comment by gwwar** [comment]
Sounds good @mmtr !
