### ISSUE TITLE
Translated Headstart annotations include some broken blocks (blocks with invalid markup)

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#44374]
When a user creates a new site via `/start` their new site is populated with starter content by Headstart.

While reviewing D46335-code, I encountered some block validation issues with specific translations of the Headstart annotations. These will likely need to be fixed up by hand, and are possibly a mismatch between the markup inside the block, and the metadata of the block (typically the translated strings must much in both places).

Annotations live in json files in `wp-content/lib/headstart/annotations`.

Issues found:

* [x] `de.json` - broken telefonnummer field on Kontakt page (fixed in D49469-code)
* [x] `es.json` - broken Direccion block (fixed in D49473-code)
* [x] `fr.json` - broken Jetpack Subscription Form in home page (fixed in D49560-code)
* [x] `he.json` - broken Jetpack Subscription Form in home page — Block errors no longer present
* [x] `it.json` - broken Jetpack Subscription Form in home page — Block errors no longer present
* [x] `nl.json` - broken E-mailadres field on Contact page (fixed in D49631-code)
* [x] `pt-br.json` - broken Endereço de e-mail field on Contacto page (fixed in D49633-code)
* [x] `tr.json` - broken Jetpack Subscription From in home page (fixed in D49904-code)

To test / verify these block validation issues, switch your language in Calypso to one of the locales above, create a new site via `/start` and check each of the pages in the editor.

There might be a number of ways of dealing with this, but I would do these one by one in separate diffs to make it easier to review & merge in small pieces. It'd be a matter of taking the string of markup in the annotation file, and updating it in your sandbox to fix the validation issue.

**Comment by autumnfjeld** [comment]
One followup issue regarding unicode in headstart annotations found during this work: https://github.com/Automattic/wp-calypso/issues/45763
