### ISSUE TITLE
FSE: Contextual Tips issues with Block Directory

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#44397]
FSE’s [Contextual Tips](https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/contextual-tips) seem to be working differently since the v8.4.0 introduced the Block Directory. I noticed two things:

**1. Inline inserter doesn't show the Contextual Tips anymore**

This happens on both, Simple and Atomic sites.

![image](https://user-images.githubusercontent.com/1451471/88293451-513c8600-ccfb-11ea-96a1-f6545b99dc36.png)

**2. Main inserter shows the tips at the bottom, instead of the top**

This happens on Simple sites only where we had to disable the Block Directory. On Atomic sites, they’re rendered at the top.

Simple site, Contextual Tip at the bottom:
![image](https://user-images.githubusercontent.com/1451471/88293484-5b5e8480-ccfb-11ea-9fd6-06326937a51f.png)

Atomic site, Contextual Tip at the top:
![image](https://user-images.githubusercontent.com/1451471/88293515-65808300-ccfb-11ea-849a-494022e7d189.png)

Context: p7DVsv-8X4-p2#comment-30041
Related: r210682-wpcom

**Comment by jeryj** [comment]
> Main inserter shows the tips at the bottom, instead of the top

This is due to WPcom adding a fill on the same `__experimentalInserterMenuExtension` slot. Work in progress at D47125-code.

**Comment by jeryj** [comment]
>  Inline inserter doesn't show the Contextual Tips anymore

The inline inserter is a new component called the `<QuickInserter />`, added in this PR: https://github.com/WordPress/gutenberg/pull/22789

The Contextual Tips uses the [`<__experimentalInserterMenuExtension.Slot />`](https://github.com/WordPress/gutenberg/blob/d8c7146c1773b5e9b957b0bbb1ff0484ea90d6b1/packages/block-editor/src/components/inserter/block-types-tab.js#L213). This Slot isn't present on the `<QuickInserter />, and I don't see any slots available on it.

**Comment by davemart-in** [comment]
@WunderBart I'm sending this one back to your team. @jeryj did some investigation and it looks like we'll need to create a new Slot in Gutenberg core to fix this.

**Comment by sirreal** [comment]
We could give our empty results handler a lower priority so it's enqueued first, but we have to go into negative values because the current contextual enqueuing action has the extremely low value of `0` as opposed to the default `10`:

https://github.com/Automattic/wp-calypso/blob/13f4c556c6c29e753eb60c4e6da3ddc017e657ce/apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/index.php#L74

@jeryj Do you know if there's a reason for that to have such a low priority?

See D47395-code (sets priority `-1`) for an alternative to D47125-code.

**Comment by sirreal** [comment]
> See [D47395-code](https://href.li/?D47395-code) (sets priority `-1`) for an alternative to [D47125-code](https://href.li/?D47125-code).

I got this backwards and have updated D47395-code accordingly.

**Comment by sirreal** [comment]
Fixed by r211559-wpcom

**Comment by sirreal** [comment]
@davemart-in @jeryj I closed this based on contextual tips positioning in the main inserter. Did this need to stay open to track missing contextual tips in the quick inserter?

**Comment by davemart-in** [comment]
Nope, happy to close this out if it's fixed. Thanks @sirreal!
