### ISSUE TITLE
Theme Showcase: Customize Link opens Page Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#44429]
#### Steps to reproduce

1. Make a new site on WP.com as a new user with a Free Plan.
2. Navigate to Themes in Calypso.
3. Click button labelled Customize **expecting** to wind up in Customizer.
4. Wind up in Page Editor **instead**.

Note the URL in the bottom left corner of my viewport as I hover over Customize …

![image](https://user-images.githubusercontent.com/545779/88400020-51856180-cd8d-11ea-9b98-562003c8d9dc.png)

via @galakhyati cc @kjellr

**Comment by sserafini1** [comment]
Hello!

Can you please show what the URL has to be instead?

**Comment by ianstewart** [comment]
It should be the Customizer URL to match the label. `https://wordpress.com/customize/[subdomain].wordpress.com`

**Comment by allilevine** [comment]
Currently if a theme is Gutenberg-first and the site homepage is a page, we link the "Customize" button to /block-editor/page. However, this logic was added for the success modal, where the button is labelled "Edit homepage". Confirmed with @ianstewart and @kjellr that this button should always link to the customizer, regardless of whether the theme is Gutenberg-first.

Looks like we'll need to make change on line 115 here:

https://github.com/Automattic/wp-calypso/blob/e12a2600d869430a85246b7d57ae75108fee3ff5/client/my-sites/themes/theme-options.js#L108-L119

**Comment by sserafini1** [comment]
> Currently if a theme is Gutenberg-first and the site homepage is a page, we link the "Customize" button to /block-editor/page. However, this logic was added for the success modal, where the button is labelled "Edit homepage". Confirmed with @ianstewart and @kjellr that this button should always link to the customizer, regardless of whether the theme is Gutenberg-first.
> 
> Looks like we'll need to make a change on line 115 here:
> 
> https://github.com/Automattic/wp-calypso/blob/e12a2600d869430a85246b7d57ae75108fee3ff5/client/my-sites/themes/theme-options.js#L108-L119

What does it mean that the theme is Gutemberg-first?

**Comment by allilevine** [comment]
@sserafini1 From what I'm seeing here, it means the theme has a "global-styles" or "auto-loading-homepage" feature tag:

https://github.com/Automattic/wp-calypso/blob/2e7a240028ef29afc9bc436e828df0db2040215e/client/state/themes/selectors/is-theme-gutenberg-first.js#L25-L31

**Comment by sserafini1** [comment]
> @sserafini1 From what I'm seeing here, it means the theme has a "global-styles" or "auto-loading-homepage" feature tag:
> 
> https://github.com/Automattic/wp-calypso/blob/2e7a240028ef29afc9bc436e828df0db2040215e/client/state/themes/selectors/is-theme-gutenberg-first.js#L25-L31

Yes, I mean, at the moment I am working with the dev version, but I can't reproduce the error. Is there something more to add?

**Comment by allilevine** [comment]
> Yes, I mean, at the moment I am working with the dev version, but I can't reproduce the error. Is there something more to install?

Ahh! Did you try changing the theme on your test site to Hever? https://wordpress.com/theme/hever That's the default theme for new users, as seen in the issue description screenshot.

**Comment by krymson24** [comment]
@ianstewart I made the suggested changes, but it seems like per the discussion [here](https://github.com/Automattic/wp-calypso/pull/45139), we don't always want to redirect to the Customizer. Given @noahtallen's comment and that the roadmap is to move away from Customizer to a full site editing experience, I propose that we change the experience to only redirect to the Page Editor. That way, we can prevent further confusion or another switching of redirect paths in the future.

**Comment by kwight** [comment]
"...move away from Customizer to a full site editing experience" is more long-term and not very concrete – people will be using the Customizer for a long time to come. Added my 2c here too: https://github.com/Automattic/wp-calypso/pull/45139#issuecomment-680333744

**Comment by ianstewart** [comment]
I left a comment on the PR to say, basically, we should always be linking to the Customizer there, even for our early non-Core FSE experiences. Obfuscating or hiding the Customizer provides an incomplete experience for those users. (For example, all the new colour palettes that were added to all those themes.) Additionally, it's just confusing.
