### ISSUE TITLE
Checkout: Editing email address in checkout results in old and new addresses being shown

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#44426]
#### Steps to reproduce

1. For a site you already own, go to Manage -> Domains and click on "Add a domain to this site".
2. Search for and select a domain.
3. Proceed to checkout.
4. In the checkout page, click on the "Edit" button next to Contact Information.
5. Update your email address and click on Continue.

#### What I expected
I expected the new email address to appear.

#### What happened instead
Both the old _and_ new addresses were shown.
Before:
<img width="571" alt="Screenshot 2020-07-24 at 15 06 54" src="https://user-images.githubusercontent.com/3376401/88394726-32ec8e00-cdc0-11ea-87b9-cfbcd45aee9d.png">
After:
<img width="588" alt="Screenshot 2020-07-24 at 15 07 13" src="https://user-images.githubusercontent.com/3376401/88394753-3d0e8c80-cdc0-11ea-9ddc-70daa0644bf1.png">

#### Browser / OS version
Chrome 84 on MacOS.

#### Context / Source

#manual-testing

**Comment by sirbrillig** [comment]
Thanks for the bug report. FWIW the "old" email address being displayed is actually the "alternate" email address is is not used for anything except for G Suite subscriptions.
