### ISSUE TITLE
Gutenboarding: add Name your site step to launch flow

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#44449]
Add an extra step at the beginning of launch flow called _Name your site_.
## Design
<img width="600" alt="Screenshot 2020-07-27 at 11 21 53" src="https://user-images.githubusercontent.com/14192054/88519830-69fab380-cffb-11ea-825d-b3e2fde76d8d.png">

If a site title has been entered during site creation flow, show this step as checked and automatically advance launch flow to the domain step.

## Development
- explore adding an action to set site settings to existing [site data-store](https://github.com/Automattic/wp-calypso/blob/master/packages/data-stores/src/site/actions.ts).
- example for a request object using `siteId` and `siteTitle`:
```
path: `/sites/${ siteId }/settings`,
apiVersion: ‘1.2’,
method: 'post',
body: { blogname: siteTitle },
```

**Comment by simison** [comment]
Setting site title might be as simple as this:

https://github.com/WordPress/gutenberg/blob/988ba5d9dd756f1306b9319a026174280006b857/packages/block-library/src/site-title/edit/index.js#L17
