### ISSUE TITLE
Site Settings: The redirect after deleting a site is broken

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#4444]
Once the request to delete a site on `/settings/delete-site/:site` is fulfilled and the site is deleted, we [redirect the user to `/stats`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/delete-site/index.jsx#L221). However, some code in `sidebar.jsx` throws errors that prevent this from redirect from happening.

<img width="1280" alt="screen shot 2016-03-30 at 6 05 33 pm" src="https://cloud.githubusercontent.com/assets/1130674/14162599/22ef88bc-f6a2-11e5-9d7f-c5a9e659ea5b.png">

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Closing, looks like this was fixed.  Tested with both a multi-site and single-site account.
