### ISSUE TITLE
Social Previews: Remove the need for translation dependency

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#44489]
The new `@automattic/social-previews` package contains a dependency for translating a string and it only ever uses it to trasnlate a single string: "Serach Preview". 

I think we can remove that string completely, especially since no other preview has this "heading" on it. See twitter:

<img width="563" alt="Screenshot 2020-07-28 at 17 01 40" src="https://user-images.githubusercontent.com/156676/88687035-0bffc600-d0f8-11ea-8400-a23c5999e3e3.png">

facebook:

<img width="409" alt="Screenshot 2020-07-28 at 17 01 43" src="https://user-images.githubusercontent.com/156676/88687049-10c47a00-d0f8-11ea-8e2f-7eaa597a5366.png">

and now the google search:

<img width="418" alt="Screenshot 2020-07-28 at 17 01 29" src="https://user-images.githubusercontent.com/156676/88687100-1fab2c80-d0f8-11ea-9384-93c38240025f.png">

Removing the dependency will significantly decrease the impact of this package being added to Jetpack, which we are doing in https://github.com/Automattic/jetpack/pull/16615

**Comment by marekhrabe** [comment]
Check with designers: is it okay if we remove the "Search Preview" header from the actual preview? 

We'll go from something like this:

<img width="406" alt="Screenshot 2020-07-29 at 14 01 40" src="https://user-images.githubusercontent.com/156676/88797719-1081b880-d1a4-11ea-9d4b-3781f1132837.png">

into just this:

<img width="407" alt="Screenshot 2020-07-29 at 14 02 02" src="https://user-images.githubusercontent.com/156676/88797741-1a0b2080-d1a4-11ea-9f62-e98f06d55022.png">

Other previews already don't have any additional headers so we are essentially just making them more consistent. I just wanted to double check

**Comment by sfougnier** [comment]
Yes, let's remove it. I had the same thought, and I agree with making things consistent with the other previews.

**Comment by getdave** [comment]
Good spot! Just checking was `"Serach Preview"` a typo in your description or was that in the code!?

**Comment by frontdevde** [comment]
> Good spot! Just checking was "Serach Preview" a typo in your description or was that in the code!?

Code suggests it was a typo in the description :)
