### ISSUE TITLE
Reader: below the line text is clipped when using larger than default font (Chrome and Firefox)

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#44492]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read
2. (in chrome) set your default font to Large (in firefox, increase your default font size)
3. navigate to https://wordpress.com/read
4. note author and tag lines of each followed site

#### What I expected
no text is clipped
#### What happened instead
letter below the line (y, g, p) are clipped

#### Browser / OS version
chrome/firefox

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/16654218/88703076-3fcbf300-d0da-11ea-8650-db7f0d709110.png)

#### Context / Source
#dogfooding

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
