### ISSUE TITLE
Editor: preview sometimes does not update to match content

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#4449]
When I click the "Preview" button after writing a post, sometimes the preview shows an old version of the post rather than the current version, and (when that happens) nothing that I do seems to be able to force the preview to show the correct content.

I've noticed this happen several times but never consistently. I'm opening this issue to hopefully be able to document when it does happen and find out the steps to reproduce it effectively.
 
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/burlingtonbuddhist.wordpress.com
2. Start writing a post (using HTML mode with Markdown).
3. Pause for a brief time as the post is being written, perhaps going back and changing a few words.
4. After some time passes (enough for at least one autosave), press "Preview".

#### What I expected

To preview the current state of the post.

#### What happened instead

The preview shows the first autosave of the post.

#### Browser / OS version

Today it was Mac OS 10.11.3 using 1.3.1-beta Desktop app.

#### Screenshot / Video

https://cloudup.com/c-dunSBIxc0

**Comment by hoverduck** [comment]
19May16 Bug Scrub

I can't reproduce this, but I'm curious if it's related to #3220, in that once the preview pane is somehow set to display something it's not supposed to, it's stuck on that until the page is refreshed.

Does it always happen on the desktop app, or does web-based Calypso show the problem too?

**Comment by sirbrillig** [comment]
I *think* I've seen it in the web app too, but I can't be certain since lately I do all my posting through the desktop app. I did reproduce this again earlier this week but I was in a hurry to make my post and so I didn't have time to debug it. It seems to have something to do with pasting content in to the editor that gets it "stuck".

**Comment by lancewillett** [comment]
Feel free to re-open this in the future if it's reproducible.
