### ISSUE TITLE
Jetpack Plugins: 'Updates' page lags and does not show plugin update

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#445]
When I am browsing Calypso, and there is a new plugin update available for a plugin on my site, the icon shows up next to my site title in the sidebar, but the 'Updates' page does not show the update info until after a hard refresh.

Steps to reproduce:
1. Browser to a Jetpack site on Calypso
2. Remove the current Jetpack plugin on your site via FTP, etc
3. Add an older version of Jetpack instead
4. See the there's a yellow update notification shown, but notice that the Updates tab still shows '0':
![screen shot 2015-11-22 at 3 45 26 pm](https://cloud.githubusercontent.com/assets/11487924/11326190/cb5270fa-9130-11e5-915c-6cda4a696c87.png)
5. Click the 'Updates' tab - still no update shown:
![screen shot 2015-11-22 at 3 45 30 pm](https://cloud.githubusercontent.com/assets/11487924/11326196/ec9fff0c-9130-11e5-80af-6b9df09f67fa.png)
6. A hard refresh on the page makes the update show:
![hard-refresh](https://cloud.githubusercontent.com/assets/11487924/11326197/0048a356-9131-11e5-8db9-e58bbab0744d.png)

**Comment by johnHackworth** [comment]
As soon as users enters into /plugins/ territory, we are automatically launching any autoupdate that is still pending to do ... So if you go to your account and have pending autoupdates, the update icon is going to be shown in 'my sites'... but as soon as you click on it and go to /plugins/, that autoupdates would be launched, so they won't be pending anymore. We probably should launch those autoupdates not when someone access to /plugins/, but anytime the user go to anyplace in calypso and there are updates pending

**Comment by lancewillett** [comment]
Closing this one as "works for me".
