### ISSUE TITLE
Unable to add menu items when Varia theme is active in Customizer (Atomic)

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#44504]
#### Steps to reproduce

1. On a WordPress.com AT site, activate Varia or one of the Varia child themes.
2. Attempt to add a menu item to an existing menu in the Customizer.

#### What I expected

* For a menu item to be added without error.

#### What happened instead

* A JS error is thrown:

```
Uncaught TypeError: Cannot read property 'open' of undefined
customize-nav-menus.min.js:2 
https://c0.wp.com/c/5.4.2/wp-admin/js/customize-nav-menus.min.js
```

* This doesn't seem to affect WordPress.com simple sites.
* WP Admin menu editing works as normal.
* Non-Varia themes and menu editing in Customizer as normal.

#### Browser / OS version

* Chrome Version 84.0.4147.89 (Official Build) (64-bit)

#### Context / Source

p1595975204029300-slack-wpcom-support

**Comment by samiff** [comment]
3181586-zen

**Comment by wprhunt** [comment]
3181628-zen

**Comment by annacmc** [comment]
Two accounts of this, both on Varia child themes (Hever & Balansala) 3181565-zen & 3181566-zen

**Comment by hacchism** [comment]
Another one with Hever: #22984068-hc

**Comment by adelineyaw** [comment]
22822319-hc (Rockfield)
Follow up: 3181846-zen

**Comment by sanjeev00733** [comment]
Another issue reported in #3182097-zen (Redhill theme)

**Comment by rachelwinspear** [comment]
Same issue came up in Quick Start. Brompton theme #3181169-zen

**Comment by nickpagz** [comment]
Another report with Morden #23003980-hc

**Comment by davipontesblog** [comment]
Another report with Redhill #22802372-hc

**Comment by aisajib** [comment]
Had an issue with Barnsbury here: #23005953-hc - user was trying to add a site logo (but they may have added/modified the menu section as well).

**Comment by JoshuaGoode** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/44504

Added tags and assigned to Dotcom Manage.

**Comment by scosgro** [comment]
Another report in 23010052-hc

**Comment by JoshuaGoode** [comment]
Updated users with tickets listed to let and had not already been informed that this has been resolved.

For chats listed, if you created a follow-up but didn't list the ticket -- or let the user know we would follow-up -- can you update them? Or, ping me and I can get to it. 

cc: @davipontesblog @nickpagz @hacchism

**Comment by davipontesblog** [comment]
> For chats listed, if you created a follow-up but didn't list the ticket -- or let the user know we would follow-up -- can you update them? Or, ping me and I can get to it.

Let the user know in #3186945-zen
thanks for the ping @JoshuaGoode !
