### ISSUE TITLE
Importer: Wix Import Fails to Start

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#44503]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/import/
2. Select a site to import into (if applicable)
3. Click Wix
4. Enter a Wix import URL (you can use https://velda7.wixsite.com/velda7 -- basic Wix site for testing)
5. Import

#### What I expected
An import to start

#### What happened instead
Import did not start. I received this error: Unable to load site preview. Please try again later.
Try again or get help.

![Screen Shot 2020-07-28 at 1 52 03 PM](https://user-images.githubusercontent.com/3476361/88714123-8d942b80-d0d9-11ea-9d88-2316b72b40c6.png)

If I click Try Again, nothing happens. Nothing registers in the console either. No errors, no apparent network attempts to reach Wix.

#### Browser / OS version
Mac (Current) Chrome (Current)
Another user mentioned they tried different browsers.

#### Context / Source
Multiple users have reported this. Instances listed here:
P2: pbkcP4-ee-p2

Seems to have been occurring since at least July 25, so it doesn't seem to be an intermittent issue.

I don't see a workaround.

**Comment by xpurichan** [comment]
Reopening as the user has just replied to their ticket and reported the problem persists.

I wanted to test this behavior for myself so I used the test site linked above (`https://velda7.wixsite.com/velda7`) and actually got a different error:

```
It looks like we're unable to reach that website address at this time. (ID: 012195d1-9fc2-4505-ac3b-5942f83c86cd)
```

(Despite that the website is still online and publicly accessible.)

**Comment by mlaetitia** [comment]
I just tested this and got a new error: 

It looks like we're unable to reach that website address at this time. (ID: 1481b402-ccc9-4d74-b61f-1c5e636112dc) with a different website.

Reported by a user: 3284417-zen

**Comment by cathymcbride** [comment]
we may want to close this issue and open a new one, as the error is different.

**Comment by eduardozulian** [comment]
@cathymcbride I moved this to #45586 so I'm closing this one.
