### ISSUE TITLE
Payments: It's not clear, that we accept all payment card

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#44513]
We use "Credit Cards" where we mean just payment cards, because that is the common US name for it.

In Poland, this causes a lot of confusion, because the vast majority has debit cards, and sometimes are confused if they can use them (I know I am)

We have to correct that in the copy and the docs.

Came from a question by @joweber123 :

> Hey team Earn.  I had a user ask today if the new Payment block accepts debit cards as well.  I would assume so but as it does just say credit cards in the support doc I wanted to double-check.

https://wordpress.com/support/wordpress-editor/blocks/payments/

**Comment by lauac** [comment]
For the time being, I edited to "... lets you accept credit and debit card payments..." on this page. I did a quick search across support docs and actually there don't seem to be any other references to just credit cards.

Does "credit and debit cards" work, @artpi? We could broaden to "credit, debit, and payment cards" to make it broader for global audience?

**Comment by kwight** [comment]
"credit and debit card payments" looks good @lauac , thanks! It doesn't look like we accept anything else, like Bitcoin or Apple Pay (which Stripe do offer), based on what I see in our payment popups, so I'll close this (@artpi can re-open and correct me if I'm wrong).
