### ISSUE TITLE
Payments+Donations: Pay-what-you-want copy in checkout

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#44511]
@kristarella has pointed out that the copy here is sloppy:

![Zrzut ekranu 2020-07-29 o 09 40 59](https://user-images.githubusercontent.com/3775068/88771497-a0613b80-d17f-11ea-84c9-f10524f14838.png)

> “That's” needs an apostrophe, “that’s” but it might sound better if it read, “Please enter an amount of 5 or greater.” 

Consideration:
What should be a minimal amount here? Should we respect the minimal Stripe currency? - @davemart-in 
Currently, it's hard-coded 5, because I hardcoded it everywhere.
But in all the other places (editing a plan), we defaulted to minimal Stripe amount.

**Comment by davemart-in** [comment]
@artpi what is the minimal Stripe amount?

**Comment by sixhours** [comment]
@davemart-in IIRC from working on the payments block before, it changes depending on the currency (which is probably a good argument for making it align rather than using the hard-coded value).

**Comment by davemart-in** [comment]
Ah, that makes sense. Thanks @sixhours!

So it sounds like the task here would be to change the min amount to match the minimal Stripe amount vs. the hard coded $5 value.

**Comment by mmtr** [comment]
Fix available at D48094-code.
