### ISSUE TITLE
Unable to add widgets when Varia theme is active in Customizer (Atomic)

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#44510]
### Steps to reproduce

- On a WordPress.com AT site, activate Varia or one of the Varia child themes.
- Attempt to add a new widget in the Customizer (Customize > Widgets > any widget area)

### What I expected
Widgets module appeared as expected and I able to add the widget on the widget area as expected.

### What happened instead

JavaScript error on console:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Function.v.template (underscore.min.js:2)
    at wp-util.min.js:2
    at Object.<anonymous> (customize-message-wpcom.js?ver=1.4.1:16)
    at i (jquery.js:2)
    at Object.add [as done] (jquery.js:2)
    at Function.<anonymous> (customize-message-wpcom.js?ver=1.4.1:14)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at customize-base.min.js:2
    at i (jquery.js:2)
```

And:

```
Uncaught TypeError: Cannot read property 'parentElement' of null
    at HTMLDocument.<anonymous> (customizer-labels-site-not-launched.js?ver=20200206:10)
```

This doesn't seem to affect WordPress.com simple sites.

Adding widget from /wp-admin (/wp-admin > Appearance > Widgets) works as normal

Non-Varia themes and widgets editing in Customizer as normal.

This is similar with this issue:
https://github.com/Automattic/wp-calypso/issues/44504

### Context / Source
p1596005870147300-slack-wpcom-support

**Comment by sanjeev00733** [comment]
Issue reported in #3182097-zen

**Comment by JoshuaGoode** [comment]
Added tags, assigned to Dotcom manage. 

Noting the following internal discussion threads

* Atomic: p1596026527494600-slack-atomic
* Themes: p1596024809179600-slack-themes

@jeffikus has reviewed but hasn't been able to identify the issue.

**Comment by jeryj** [comment]
The ["'varia-custom-message'" template needed by the customizer](https://github.com/Automattic/themes/blob/master/varia/inc/customize-message-wpcom.js#L16) is missing from the page. Adding a template in fixes this issue and https://github.com/Automattic/wp-calypso/issues/44504.

Example template for the fix:

```
<script type="text/html" id="tmpl-varia-custom-message">
	<!-- Template content here -->
</script>
```

I'm not sure why this issue would have _just_ shown up though, as these were added three months ago. Another option to fix this is to disable this JS entirely by [commenting out this line](https://github.com/Automattic/themes/blob/master/varia/inc/wpcom.php#L158).

I don't have enough understanding of how all these parts tie together, what this section of code is trying to do, or why the error just started coming up... Anyone have ideas on that?

cc @davemart-in @kjellr @JoshuaGoode

**Comment by JoshuaGoode** [comment]
> Issue reported in #[3182097-zen](https://href.li/?https://automattic.zendesk.com/agent/tickets/3182097)

Updated user.
