### ISSUE TITLE
My Home: Determine content for the "expiring plan" task card.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44535]
The mockups for the upcoming "expiring plan" task card in https://github.com/Automattic/wp-calypso/issues/43496 displays custom content for the Premium plan. This means we'll need content for each plan we have that will be handled by the card. My Home is not active for Atomic or Jetpack sites at this point so, sticking to WP.com plans, this would be:

* Personal
* Premium
* Business

<img width="1423" alt="renew-plan" src="https://user-images.githubusercontent.com/349751/88841180-6a798280-d192-11ea-90e3-69d20a34571f.png">

Part of https://github.com/Automattic/wp-calypso/issues/43496

**Comment by kwight** [comment]
I guess another approach could be to use fully generic content that could apply to all plans; this would also conveniently cover every time we make changes to plans, plan names, or add support to new platforms. @danhauk @davemart-in @Automattic/editorial any strong feelings one way or another?

**Comment by kwight** [comment]
I'm also not seeing the `e-commerce` plan in our UI right now, not sure why that is.

**Comment by kwight** [comment]
> I guess another approach could be to use fully generic content that could apply to all plans

Looking at it closer, it's really only the line detailing specific features that's problematic – we can certainly still pass in the name of the plan in question while keeping the `Task` card applicable to all plans.

**Comment by davemart-in** [comment]
I'm going to cc @fditrapani for his thoughts on this as well since this touches payments related stuff.

**Comment by danhauk** [comment]
Ideally it would be great to customize the content based on the plan as generic wording often doesn't connect with users as much. But I do understand the concern around added work and maintenance going forward. I'd be happy with starting with generic and iterating in the future if the work required is too much.

I'm not sure how displaying features works on the plans page but I wonder if there's some way to serialize the features for each plan and display 2 or 3 in this card?

**Comment by fditrapani** [comment]
Thanks for the ping @davemart-in! 

> I'd be happy with starting with generic and iterating in the future if the work required is too much.

I second Dan's suggestion to start generic and then we can try more customized copy for each plan in the future.

**Comment by michelleweber** [comment]
FWIW, I am very pro-personal/targeted copy wherever it is possible, especially where we're trying to stop someone from churning and so are especially invested in connecting with them, and am happy to do whatever I can on the copy front to help make that happen.

**Comment by jordesign** [comment]
FWIW Business Plan users are often *most* affected when this happen - seeing an immediate loss of custom theme and plugins (if in use). We'll regularly get contacted by them asking why their site looks broken or has entirely changed appearance - not yet realizing their plan has expired.

**Comment by autumnfjeld** [comment]
@kwight  Can this be closed since #43496 is closed?
