### ISSUE TITLE
My Home: Data is required for the "expiring plan" task card.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#44537]
We need to add the "expiring plan" task card's data to the `layout` library, accessible in Calypso via the `/sites/:site/home/layout` endpoint. This will involve creating a new view for the card, and incorporating the following logic:

* plan is already expired: return "expiring plan" view with high-priority task
* plan expires in thirty days or less: return "expiring plan" view with normal task
* site has no plan, or the plan expires in more than thirty days: return some other view

Part of https://github.com/Automattic/wp-calypso/issues/43496

**Comment by kwight** [comment]
Started in D47225-code.

**Comment by autumnfjeld** [comment]
@kwight closing this. :)  fixed in #47375
