### ISSUE TITLE
More block:  no longer displaying in email

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#44536]
**Update**: we have a potential fix here D48681-code. The testing instructions are in the diff and _not_ on this Issue.

-----

When a More block is inserted into a post and the post is published, the feed subscription email goes out to subscribers. In the email that subscribers receive, the More block does not show up in the email. 

#### Steps to reproduce

1. Go to your "Followed SItes" at https://wordpress.com/read. Toggle Followed Sites open.
2. Select one of your followed sites. It should load in the main panel on the right hand side.
3. Click "Settings" as per the screenshot below.
![Screen Shot 2020-08-26 at 13 03 42](https://user-images.githubusercontent.com/444434/91301311-9a6d7300-e79c-11ea-8edb-5da577a905af.png)
4. Toggle the control which reads `Email me new posts`.
5. Once toggled click the button which says `Instantly` (this will appear once you have toggled the control to "on").
6. On the site you just subscribed to publish a post with a More block in it. 

<img width="1070" alt="Screen Shot 2020-07-29 at 3 36 12 PM" src="https://user-images.githubusercontent.com/30205248/88844803-3eb9c500-d1b1-11ea-91e8-219563313a34.png">

7. Subscription email that is sent out to subscribers does not show a Read More link. Instead, the full text of the post shows in the email.

<img width="967" alt="Screen Shot 2020-07-29 at 3 36 55 PM" src="https://user-images.githubusercontent.com/30205248/88844883-57c27600-d1b1-11ea-84de-4e3d01814e95.png">

#### What I Expected:

The More block should show a link in the email for readers to click and read the rest of the post. This is referenced in the WordPress.com documentation [here](https://wordpress.com/support/wordpress-editor/blocks/more-block/).

#### Context / Source

I tested this on three different sites, with three different themes - Blink, Barnsbury, and Tortuga. All three sites are WordPress.com Premium plan sites. 

Issue was originally reported in #23002093-hc

#### Fix

Please see diff at D48681-code

**Comment by joweber123** [comment]
Another report here with a user in the Classic Editor.  I have tested with the Classic Editor as well as the Block Editor and both are ignoring the More option when sending out emails.

Reference: 3184489-zen

**Comment by lizswafford** [comment]
Similar issue here: [#3183870-zen](https://woothemes.zendesk.com/agent/tickets/3183870)

**Comment by eduardozulian** [comment]
Just tested on my simple site and reproduced it as well. There are two different scenarios depending on your choice for the "Hide teaser" toggle:

1. If "hide teaser" is on, emails will display the post minus whatever was added before the more block. 
2. If "hide teaser" is off, we will display the whole post in the email

The only workaround I see for now is to force an excerpt via Manage > Settings > _Limit feed to excerpt only_

**Comment by bborman22** [comment]
Report of the same issue. User was using the Classic block in the Editor with the More block and subscriber emails were not truncated.

[#3186846-zen](https://woothemes.zendesk.com/agent/tickets/3186846)

**Comment by sukafia** [comment]
Same issue. Block & classic editor respectively. 

[#23024555-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=23024555), [#16014105-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=16014105)

**Comment by dcoleonline** [comment]
Report of the same issue in the block editor, but they are using the classic block with the more tag inside of the classic block.

3188433-zen

**Comment by KokkieH** [comment]
Another report [via Twitter](https://twitter.com/WendyLovesJesus/status/1289783664465739777), and I also saw a forum thread that mentioned this last week.

**Comment by sdixon194** [comment]
Another report in 21432386-hc, only using block editor.

**Comment by TeniCola** [comment]
Another user reported this issue -- it was actually first reported in 22997863-hc, but user returned when our workaround to use the `Limit feed to excerpt only` started to hide image blocks from the email notification -- which _isn't_ the case when More blocks work as expected.

Currently following up with them them in 3195264-zen, which has links to the screenshots that the user took to confirm the limitations with this workaround for displaying image blocks

**Comment by nagpai** [comment]
21805617-hc

**Comment by Robertght** [comment]
Another here: #3188901-zen

**Comment by jjchrisdiehl** [comment]
One more 23053157-hc

**Comment by paulostp** [comment]
Another one: #3187719-zen

**Comment by dcoleonline** [comment]
#23162439-hc

**Comment by nerdysandy** [comment]
Reported on # 21786294-hc

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/more-3/

**Comment by Robertght** [comment]
#3201987-zen

**Comment by mrsjaved** [comment]
Another report #3201141-zen

Workaround: They can turn on the Summary option from WP Admin -> Settings -> Reading -> For each post in a feed, include

**Comment by desnum** [comment]
User with Classic Editor and Read More tags shows missing link in email: hc-118990

**Comment by susanjanec** [comment]
Another report in 3206853-zen

Provided workaround, although it appears they already have it set to Summary under "For each post in a feed, include" already.

**Comment by erricgunawan** [comment]
3211087-zen

**Comment by tanjoymor** [comment]
Another report here: #22096532-hc

**Comment by formosattic** [comment]
+1 3200907-zen

**Comment by supernovia** [comment]
Noting we've seen a handful of these in the forums as well. We'll track under the read-more tag.

**Comment by Robertght** [comment]
Another in #23330194-hc

**Comment by jamiepalatnik** [comment]
Another report in #23340591-hc, provided Summary settings workaround.

**Comment by TeniCola** [comment]
Another report in #23406454-hc. The user mentioned that the `Limit feed to excerpt only` setting did not help them.

**Comment by chaitanyamsv** [comment]
9893824-hc

**Comment by jamiepalatnik** [comment]
Another report in #21757151-hc, provided Summary settings workaround.

**Comment by nagpai** [comment]
#23485835-hc   - provided Feed excerpt workaround.

**Comment by aaronrobertshaw** [comment]
I’ve taken a look into the cause of this issue. When the subscription email is being generated (in `Subscription_Mailer::convert_html_to_email()`) and the `rss_use_excerpt` blog option is *not* turned on, it leverages `get_the_content()` to determine the email body content. 

This function *does* take into account a possible more block or quick tag. The problem is that it relies on `WP_Query::generate_postdata()` which forces full post content when on an RSS feed. At the time we are creating the email  `WP_Query::is_feed()` returns `true`. The end result is this causes `get_the_content()` to re-append the content that occurs after the more block to the returned content.

Excerpts are intended to be a plain text alternative to the more block or quick tag and as such don’t take them into account. 

One possible solution when the `rss_use_excerpt` setting is not turned on, would be to check for the presence of a more tag before generating the body content. If it is present, manually process the post content to get only that prior to the more block. Then pass that through any required filter and append the read more link to the end.

I’ve run out of time to find a better approach or work up a solution for this, so happy for someone else to pick this one up.

**Comment by inaikem** [comment]
Another instance here: 3218891-zen

**Comment by eduardozulian** [comment]
Another: 3227815-zen

**Comment by jerrysarcastic** [comment]
Another user report in:  20784053-hc

**Comment by kcswong** [comment]
3252046-zen, provided the workaround of selecting `Summary` in WP Admin > Settings > Reading

**Comment by kriskorn** [comment]
3252717-zen

**Comment by getdave** [comment]
I've now tested this and confirmed the issue. I'm going to be looking into it.

**Comment by eoinsav** [comment]
Another report in #23502645-hc

**Comment by getdave** [comment]
Diff now available at D48681-code

**Comment by rossanafmenezes** [comment]
Another report here 3262019-zen (regarding the read more block not being applied to the email and also text justification)

**Comment by ezebecke** [comment]
3259675-zd

**Comment by mikeicode** [comment]
Also 23341772-hc

**Comment by mikeicode** [comment]
Also 23628359-hc

**Comment by jamiepalatnik** [comment]
Another report in 23667465-hc

**Comment by paulostp** [comment]
One more: 3262667-zen

**Comment by Nic-Sevic** [comment]
one more: 3244371-zen

**Comment by benchilcote** [comment]
Another case: 13893399-hc
Follow Up: 3265883-zen

**Comment by csonnek** [comment]
3259865-zen

**Comment by inaikem** [comment]
21702201-hc

**Comment by gwensmithx** [comment]
22104473-hc
3277980-zen

Provided workaround under wp-admin --> Settings --> Reading --> Summary

**Comment by getdave** [comment]
# Updated

Fix deployed as of r213058-wpcom.

Any HEs seeing this please test and confirm. Much appreciated.

**Comment by jamiepalatnik** [comment]
I tested this & the more block seems to be working as expected for me now in the email notification. Thank you for working on this!

**Comment by evilluendas** [comment]
@getdave Hi Dave! We've noticed that all new post emails coming from P2 have the "Read more of this post" link at the end, even when the More block hasn't been used. It's confirmed happening in emails both using the P2020 (the new P2) and the old P2 template.

![image](https://user-images.githubusercontent.com/820374/92089540-33684380-edc6-11ea-83dd-4b3ec3a9e8ff.png)


I assume it's related to r213058-wpcom, could you take a look in case it's easily fixable?

**Comment by getdave** [comment]
Fix incoming.

**Comment by Digger444** [comment]
This fix just mimics the "excerpt" feature and does not allow for photos which the more tag did previously.

**Comment by gsmumbo** [comment]
@getdave In 3286183-zen the Read More now appears, but not in the place they placed it. Not sure if it's related but they also can't access the blog by clicking [...]

**Comment by Digger444** [comment]
Previously whatever was placed before the more tag was in the email (photos incl). Now it appears it's just the text.

**Comment by kristarella** [comment]
@Digger444 I tested the more block and it worked correctly in the email I received from my site. Please check your Writing settings to see if the feed is set to send full posts.

**Comment by Digger444** [comment]
Where do I find this setting for “full posts”

https://stoutstandards.wordpress.com/wp-admin/options-writing.php

**Comment by kristarella** [comment]
@Digger444 Sorry, it's "Writing" settings in the WordPress.com dashboard (https://wordpress.com/settings/writing/)
It's Settings > Reading in WP Admin

**Comment by Digger444** [comment]
Okay, cleared that and will assume that fixes the problem. Thank you.

**Comment by Digger444** [comment]
Forgive me for being such a pain. Is there something that actually says “send full posts” or do I just uncheck the “excerpt only”?

**Comment by kristarella** [comment]
@Digger444 In WordPress.com settings just uncheck "excerpt" setting
