### ISSUE TITLE
Jetpack Cloud: Incorrect label for non latest backups

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#44530]
#### Steps to reproduce

1. Starting at URL: https://cloud.jetpack.com/backup/{site}
2. Ensure the site has multiple days worth of backups
3. Start navigating backwards in time
4. Notice the title of 'latest backup' remains in two places

#### What I expected

I expect latest backup to only indicate the lates backup.

Proposed solution: Update the titles to reflect the current state, consider having just a single title.

#### What happened instead

Latest backup remained in two places at all times.

#### Browser / OS version

All

#### Screenshot / Video

![Kapture 2020-07-29 at 17 37 53](https://user-images.githubusercontent.com/411945/88822964-d4128480-d1c4-11ea-90d7-b1a232af26bb.gif)

#### Context / Source

 #dogfooding

**Comment by folletto** [comment]
One proposal could be:

* Actual latest backup: "Latest backup"
* Previous days: "Latest backup on this day"

Would that be clear enough?

**Comment by mattgawarecki** [comment]
Works for me! I'll make it happen 👍
