### ISSUE TITLE
Editor: How do I edit a featured image already set?

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#4453]
When registering a new site on WordPress.com that site is headstarted (dummy content is inserted). This means I have existing blog posts set up for me that I can then edit.

This is one of the blog posts:

![screen shot 2016-03-31 at 12 06 53 pm](https://cloud.githubusercontent.com/assets/1464705/14187740/4dbb22c6-f739-11e5-8416-47a1570fac4e.png)

As a new user I would absolutely want to edit that featured image and replace it with an image of my own. The trouble is it is not clear at all how to do that. I think I actually have to find the option in the sidebar, delete the image, and then upload a new one.

What about adding a button in the middle of the image, on hover, or always there that allows you to hit edit, open the media library and select a replacement image? That would make this flow a ton easier for new users coming in and setting up their site.

/cc @codebykat @aduth

**Comment by mtias** [comment]
:+1: for adding a button if an image is set. Would be a good improvement before we move all the flows to the main column and out of the sidebar and much more intuitive for users that hunting for a disconnected sidebar accordion.

**Comment by folletto** [comment]
:+1: we actually discussed this when we introduced the feature, and it's was an unanimous yes. It just has to be designed/done. ;)

**Comment by aduth** [comment]
Would it be enough to change the cursor to `cursor: pointer;` and launch the featured image selection media modal when clicked?

Noting also that the same component is used between sidebar and header (with variations in style), and I think this behavior would benefit both contexts.

**Comment by folletto** [comment]
Agreed. I think would be even better if there was at least something visible like the pencil icon in the bottom-left corner (so it's obvious you can tap on it on mobile) but regardless, starting with adding the action is the most important bit. :+1:

**Comment by folletto** [comment]
Quick mock:

![screen shot 2016-04-04 at 20 10 01](https://cloud.githubusercontent.com/assets/4389/14259985/407ddd68-faa1-11e5-914e-59254652002c.png)

_(alternatively we could do a white pencil with some opacity, like 0.8)._
