### ISSUE TITLE
Nav sidebar: the Post Visibility popup appears on top of the sidebar click guard

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#44548]
The Post Visibility popup appears on top of the sidebar click guard.

![Screen Capture on 2020-07-29 at 17-14-08](https://user-images.githubusercontent.com/1500769/88864897-76307c00-d25a-11ea-84e9-754995f7053c.gif)

p58i-9f7-p2#comment-47178

**Comment by p-jackson** [comment]
From what I can tell, this only occurs in the iframe'd editor, not wp-admin.

It doesn't appear that this can be fixed with just a z-index change. The Post Visibility popup _should_ close when the user clicks the (W) button. It closes when you click anywhere else on the page. I wonder if that means there's something in `wpcom-block-editor` that's stopping the propegation of mouse clicks.

**Comment by autumnfjeld** [comment]
@p-jackson As far as I can tell, this issue is resolved. 

Results from iframe'd editor below:

![post-visibility-popup-and-sidebar-2020-09-10 at 15-23-43](https://user-images.githubusercontent.com/5665959/92685948-10b4cc80-f37c-11ea-8156-b26c31374727.gif)
