### ISSUE TITLE
Editor: Header Toolbar Layout Changes After Refresh on Classic Editor

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#44577]
The header toolbar, where the "Publish" and "Preview" buttons are located changes after refresh while on Classic Editor. Is this a normal behaviour?

#### Steps to reproduce

Site must be on Classic Editor.

1. My site → Site → Posts
2. Create or Edit post
3. Refresh page

#### What I expected

The "Publish" and "Preview" buttons stay where they originally are. 

#### What happened instead

Moved to different location with the "History" link. 

#### Browser / OS version
Chrome Version 84.0.4147.105 (Official Build) (64-bit)

#### Screenshot / Video

https://www.loom.com/share/ff7606b1f43e4024b9eccf0be75a1b0d

**Comment by arunsathiya** [comment]
I am seeing the same issue on Calypso's classic-editor. Not necessarily when I refresh that editor page. I see that as soon as I open a page in Calypso's classic-editor.

<img width="1792" alt="Screenshot 2020-07-31 at 8 58 29 AM" src="https://user-images.githubusercontent.com/18581859/88997063-65d8d980-d30c-11ea-9e83-2a6839f9ebe4.png">

**Comment by nagpai** [comment]
Seen on #23044693-hc

Atomic site with Classic editor plugin.

Proper block editor appears in calypso after deactivating the classic editor plugin

**Comment by nagpai** [comment]
Another report here 
#23044913-hc 

Premium plan

**Comment by ajaykj** [comment]
I can replicate the issue on a simple site with `classic editor` as the choice and an AT site with `Classic Editor` plugin activated.

**Comment by pauloeaquino** [comment]
#23044395-hc

AT w/classic editor plugin

**Comment by druesome** [comment]
#12808951-hc

**Comment by andrewserong** [comment]
Fixed in #44580 which reverted #39979 which appeared to be the culprit as it affected the loading order of the `.card` CSS.
