### ISSUE TITLE
Gutenboarding: Add Cooking Class Starter Design — Clarke

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#44576]
A new starter design called Clarke is ready to be added to Gutenboarding.

https://clarkestarter.wordpress.com/

![screencapture-clarkestarter-wordpress-2020-07-30-23_58_37](https://user-images.githubusercontent.com/908665/88982634-bcb8c180-d2c0-11ea-8030-438006594da4.jpg)

cc @dubielzyk @ianstewart @johnHackworth @olaolusoga @ramonjd

**Comment by ramonjd** [comment]
Are folks happy for this to go into prod? I can prep the necessary PRs/diffs

**Comment by ianstewart** [comment]
Closing this one out as we've made some changes to the underlying patterns. cc @alaczek who was working on some redesigning and re-thinking of some starter designs.
