### ISSUE TITLE
CoBlocks: Can't add images - Existing images are replaced when adding a new one

### ISSUE THREAD

**Issue by LauraSWP** [Automattic/wp-calypso#44583]
#### Steps to reproduce

1. Add a CoBlock image block
2. Add a few images 
3. The images won't be added to the block or only one will.
4. If editing an already created collage, adding an image will replace the others.

#### What I expected

1. Add a few images to the block
2. They are all added correctly

#### What happened instead

Images sometimes are either not added (only one of them) or if editing one that was already there, it will replace all images.
#### Screenshot / Video

https://d.pr/i/WT8CbZ

Errors: https://d.pr/i/LViUHn

#### Context / Source

Related to 23037610-hc Follow-up: 3188189-zn

**Comment by sirreal** [comment]
What types of site did this occur on? Simple or Atomic?

**Comment by LauraSWP** [comment]
It was a Simple site

**Comment by zdenys** [comment]
Not sure if it's related, but on https://github.com/Automattic/wp-calypso/issues/40598 I see the item in the checklist reading `Understand what replace-image is and if we need it for wpcom`.

**Comment by LauraSWP** [comment]
@zdenys I think it is not related because in this case, the user wanted to add new images to a gallery, not to replace others, and when adding new images, all of them got replaced by that one.

**Comment by WunderBart** [comment]
I can't seem to reproduce this one. Could you confirm that it's still happening, @LauraSWP?

**Comment by LauraSWP** [comment]
> I can't seem to reproduce this one. Could you confirm that it's still happening, @LauraSWP?

Everything seems to be working now! I'm closing this :)
