### ISSUE TITLE
Editor: Ampersand in title gets converted to &amp;

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#44591]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post (select a site if needed)
2. Write a title that includes an ampersand - `&`
3. Save draft
4. Notice the title appears to show the HTML character ref for the ampersand sign
5. Publish the post
6. Notice the edit screen keeps `&amp; `but the post itself shows `&` as expected

#### What I expected
I expect the editor screen to display like the post would, and just show `&` in my title

(And while I don't expect it, it would be super sweet too if the slug automatically changed "amp" to "and")

#### What happened instead
I saw `&amp;` instead

#### Browser / OS version
Chrome / Mac Current (but probably doesn't matter; nothing happened in the console)

Please note too, I tested this on multiple .com sites, then tested on a .org test site with and without the Gutenberg plugin. It only happens on .com.

#### Screenshot / Video
![Screen Shot 2020-07-31 at 3 26 06 PM](https://user-images.githubusercontent.com/3476361/89079924-cab02600-d344-11ea-9303-91ecee7b8e6c.png)

#### Context / Source
dogfooding - just drafting a post for my own site on my lunch break. For what it's worth, I've used ampersands before without an issue, though it has been several months.

**Comment by arunsathiya** [comment]
@supernovia I think this is the same as https://github.com/Automattic/wp-calypso/issues/40499.

**Comment by supernovia** [comment]
Ahh, closing, since it is indeed a duplicate. Thanks!

**Comment by cathymcbride** [comment]
This is a duplicate of https://github.com/WordPress/gutenberg/issues/20490. Closing this one, and [#40499](https://github.com/Automattic/wp-calypso/issues/40499) in favor of the root issue.
