### ISSUE TITLE
Notifications: alignment issues

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#446]
I'm seeing a few issues with notification alignment. 

- The mid-point of the icon does not match the mid-point of the text. 
- Also, where it meets up with the sidebar feels misaligned, as the bottom of the notification is about five pixels off from the top of the site card in the sidebar.

![notifications issue 1](https://cloudup.com/cc0W0DLSfKW+)

- If you narrow the screen a bit, once you hit a certain breakpoint the notification no longer meets up with the sidebar, but the left edge does not meet up with the left edge of the content. It seems like it should.

![notifications issue 2](https://cloudup.com/cRngsvKTJkN+)

The first issue requires some css tweaks and testing. My non-designer suggestion for the second two issues is that we just change notification so they no longer meet up with the sidebar at full width and instead just align with the left edge of the content.

**Comment by lancewillett** [comment]
This has been fixed in design updates to Notices.
