### ISSUE TITLE
Redesigning the Plugin Browser

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#44627]
There are some known issues with the design of the current plugin browser; we'd like to look at redesigning it to address the following issues, and we'll track our progress and thinking here.

#43326 
#43332
#43231
#43230

**Comment by sixhours** [comment]
This is still in progress. :)

**Comment by cpapazoglou** [comment]
Plugins Browser got redesigned as part of the Marketplace 
<img width="1590" alt="SS 2022-01-05 at 20 44 34" src="https://user-images.githubusercontent.com/12430020/148271511-90637a3a-dc2b-41b8-91d5-2d3653619f8a.png">
