### ISSUE TITLE
Classic Post Editor Gallery Preview doesn't show items on fresh load

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#44640]
#### Steps to reproduce

On a site which uses the classic post editor:

1. Starting at URL: `/posts/<site-id>`
2. Open a post which contains a gallery
3. Hit reload and then attempt to edit the gallery
4. There's no preview images showing up but only placeholders

After that switching from HTML view to the visual view again it shows the images.

#### What I expected

Images are showing up

#### What happened instead

Placeholder tiles are showing up

#### Screenshot / Video

Step 4 from above:

![gallery-initial-view](https://user-images.githubusercontent.com/9202899/89283974-54663900-d64e-11ea-9929-d36bd54399da.gif)

After switching back from HTML to visual view:

![gallery-next-view](https://user-images.githubusercontent.com/9202899/89283982-592aed00-d64e-11ea-9aa9-c195f3f15098.gif)

#### Context / Source

Discovered while working on the media reduxification.

**Comment by kriskorn** [comment]
@flootr It seems the above merge has not fixed the issue. Is there something else that can be done for now to get this fixed?
We have a case here p9F6qB-5tA-p2 where the above behavior still happens. Thank you!

**Comment by flootr** [comment]
@kriskorn the referenced PR wasn't meant to fix this bug but it was discovered while working on it. I can prioritize fixing this bug though. A quick workaround is to open the media library first (via Add Media button), close it and then hit edit on the gallery.

**Comment by flootr** [comment]
Closing for now as the classic post editor got deprecated.
