### ISSUE TITLE
New Onboarding: redirect to use-your-domain existing flow

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#44645]
Clicking the link added in #47372 should redirect to the existing `use-your-domain` flow.

This feature should be enabled by passing the correct prop to DomainPicker where it's being used:
- [x] [Focused Launch](https://github.com/Automattic/wp-calypso/pull/48175) https://github.com/Automattic/wp-calypso/pull/48119
- [x] [New onboarding](https://wordpress.com/new/domains) for existing users https://github.com/Automattic/wp-calypso/pull/48692
- [x] [New onboarding](https://wordpress.com/new/domains) for new users (tracked in https://github.com/Automattic/wp-calypso/issues/51137)

Looks like address `https://wordpress.com/start/new-launch/domains-launch/use-your-domain` can take `siteSlug` and `source` attributes. Not quite sure yet what `source` does but it should be possible in some way to redirect back to the editor and launch flow at the end of domain mapping flows.

The flow redirects in some way also in current signup flow, so worth checking how it's done there.

We'd just need some URL argument that opens the launch modal when re-loading the editor again, or alternatively, open the domain flow in new tab but that doesn't seem preferable.

More in pcbO8q-4l-p2#comment-91

**Comment by tjcafferkey** [comment]
>Not quite sure yet what source does but it should be possible in some way to redirect back to the editor and launch flow at the end of domain mapping flows.

`source` [allows you to override the back button](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/domains/index.jsx#L707-L720), which we will need to do to incorporate this flow. We will need to make some changes around this as you need to anticipate the source values ahead of time in its current state where as we want to pass in any URL.

**Comment by razvanpapadopol** [comment]
closing this issue since the last part is tracked in https://github.com/Automattic/wp-calypso/issues/51137
