### ISSUE TITLE
How to connect to my server?

### ISSUE THREAD

**Issue by fengqiuming** [Automattic/wp-calypso#4464]
#### Steps to reproduce
1. I found that for wp-calypso is working on wordpress.com

#### What I expected
hi there, how could I use wp-calypso to post my article to my wordpress server but not wordpress.com?
Is that any guid line to follow?

**Comment by lancewillett** [comment]
Hi there,
To connect a WordPress.org site to Calypso, you need to install the Jetpack plugin and connect to a WordPress.com account. If you need more help, drop us a line: http://jetpack.com/support/

Cheers.
