### ISSUE TITLE
Checkout: Very long URLs break out of the sidebar

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#44652]
- Enter checkout with a very long site URL; in the "Included with your purchase" sidebar, the url marches off the right edge of the enclosing div

**Comment by michaeldcain** [comment]
This seems to have been fixed as part of some design changes to the new Checkout flow:

<img width="346" alt="Screen Shot 2021-02-18 at 1 34 38 PM" src="https://user-images.githubusercontent.com/942359/108404688-27463600-71ee-11eb-8444-0be0d6b89853.png">

**Comment by sirbrillig** [comment]
This may have been fixed by https://github.com/Automattic/wp-calypso/pull/49940
