### ISSUE TITLE
Sidebar: Hide "Customize" in all my sites view

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#44663]
#### Steps to reproduce

1. Visit a section that has an "All My Sites" view, like Stats or Posts
2. Expand the "Design" sidebar section

#### What I expected

To only see pages in the sidebar that have an "All My Sites" view

#### What happened instead

- "Customize" is shown
- When I click "Customize", I am shown the site selector

#### Browser / OS version

Firefox / macOS

#### Screenshot / Video

<img width="272" alt="Screen Shot 2020-08-04 at 14 52 16" src="https://user-images.githubusercontent.com/1699996/89338785-b6c93480-d662-11ea-81f8-1778d4f9f5b3.png">

**Comment by Aurorum** [comment]
PR in #44680 for this issue. :)
