### ISSUE TITLE
Checkout: Show USD Currency Code

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#44673]
Users whose currencies we don't support are defaulted to paying in USD.  However, that is not clear to the user in the checkout page because the currency code is only displayed when paying in non-US currencies.  This is confusing for users whose countries use the $ symbol for their own country currency, such as Argentina or Chile (whose currencies we do not support right now).

<img width="650" alt="Checkout Page" src="https://user-images.githubusercontent.com/11635760/89351663-51c40d80-d667-11ea-8fe3-440e10ea515b.png">

The only time you see "USD" is when you are in a different page and click on the cart symbol.

<img width="649" alt="USD Cart" src="https://user-images.githubusercontent.com/11635760/89351668-54266780-d667-11ea-95f5-249bb22d0410.png">

Customers who immediately go to checkout without looking at the cart could mistaken the $ amount to be in local currency rather than USD.  The ideal fix would be to show currency code by default and not just when it is a non-US currency.

**Comment by eduardozulian** [comment]
Another case in 25706513-hc

Quoting the user using Google Translate:

> Please I need a refund for the subscription, I was charged 540 dollars thinking that it was 540 Argentinian pesos ..... the symbol that appears on the invoice is Argentinian pesos

**Comment by michaeldcain** [comment]
This should be fixed after https://github.com/Automattic/wp-calypso/issues/46205
