### ISSUE TITLE
Gutenboarding: center align design name and premium badge vs only the name

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#44685]
In Gutenboarding (`/new`) we have premium badges in a few designs:

<img width="376" alt="Screenshot 2020-08-05 at 14 32 11" src="https://user-images.githubusercontent.com/87168/89408098-92379000-d728-11ea-9ebb-806177a64ad5.png">

Note how the design name is center aligned, and the premium badge is to the right from it.

Let's simplify this and align name+badge together:

<img width="376" alt="Screenshot 2020-08-05 at 14 32 11" src="https://user-images.githubusercontent.com/87168/89408586-3f120d00-d729-11ea-8126-d4ed2e582a2d.png">

**Comment by yansern** [comment]
Reserving this for @ciampo as good first issue!
