### ISSUE TITLE
Gutenboarding: use Recoleta from package

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#44683]
We now have Recoleta font in a package: https://github.com/Automattic/wp-calypso/tree/master/packages/typography

We use it manually here and there in Gutenboarding, here's one use:

https://github.com/Automattic/wp-calypso/blob/1730e9d788a6b88c84407f0b8e40a79bfd2da354/client/landing/gutenboarding/style.scss#L6-L15

Here we already use it via sass variable:
https://github.com/Automattic/wp-calypso/blob/1730e9d788a6b88c84407f0b8e40a79bfd2da354/packages/onboarding/styles/mixins.scss#L4-L8
https://github.com/Automattic/wp-calypso/blob/master/packages/onboarding/styles/base-styles.scss#L7

Should we instead extend the class vs use the variable?

Some onboarding files under `/packages/*` might have more of usage.

Let's clean out all manual usage and consolidate to use via package.

**Comment by autumnfjeld** [comment]
Hellllooo :wave: @simison  or @andrewserong 

I'm working on my second ticket! Yay, but I'm a bit confused or rather want to clarify a couple items in regards to using the Recoleta font as a package.

> Let's clean out all manual usage and consolidate to use via package.

I found two manual usages of Recoleta font:
/Users/autumn/Code/wp-calypso/client/login/wp-login/style.scss 
client/landing/gutenboarding/style.scss

I'm a little unclear on this
> Should we instead extend the class vs use the variable?

We could do that in apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.scss.

But what about the `@mixin onboarding-font-recoleta` ? It doesn't seem like replacing the variable makes sense here. 

I'll go ahead a start a PR with what I think needs to be done, just posing these questions first for a little extra help. :). Thank you!

**Comment by simison** [comment]
I could imagine a few options, it's up to you to pick!

- We add `@extend .wp-brand-font` in `@mixin onboarding-font-recoleta`
- We have `font-family: $brand-serif;` in `@mixin onboarding-font-recoleta`
- We remove `onboarding-font-recoleta` mixin and use directly the two above methods where needed directly in styles

- Additionally, we make sure we don't manually have the `@font-face` duplicated in many places, but get that from the `typography` package import. Ideally just once per bundle where needed (in Calypso and in wp-admin).

@andrewserong  can maybe explain if there's any specific jargon-knowledge or insight needed to understand above. 😅

**Comment by simison** [comment]
Looking at the `typography` package's Readme, it could also do with an upgrade on different methods of how to use it. We mostly seem to use `@extend` in Calypso for it.

**Comment by autumnfjeld** [comment]
Note that PR https://github.com/Automattic/wp-calypso/pull/44848 replaced the manual font-face declarations as requested in this issue.  However there are some caveats to using the `.wp-brand-font` with `@extend`.  See comments in PR44848 https://github.com/Automattic/wp-calypso/pull/44848#issuecomment-674110977.
