### ISSUE TITLE
Gutenboarding site launch: fix sidebar on mobile

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#44692]
#### What happened instead
When opening the redesigned launch modal (see details and testing instruction in #43750), the sidebar is cut off on mobile.

#### Screenshot / Video
<img width="370" alt="Screenshot 2020-08-05 at 16 16 57" src="https://user-images.githubusercontent.com/14192054/89418037-2eb55e80-d738-11ea-99f5-34c1f27145b1.png">

**Comment by simison** [comment]
For now, let's redirect to old Calypso flow for devices on something like <=680px.

**Comment by yansern** [comment]
> For now, let's redirect to old Calypso flow for devices on something like <=680px.

Does this mean when clicking on **Complete Your Setup** on mobile, it does what the old launch button does?

**Comment by simison** [comment]
Still gonna keep open to improve the new launch on mobile.

**Comment by joanrho** [comment]
@simison @olaolusoga What do you think about a solution like this for mobile where the side panel only appears to get users started, and then the subsequent steps are more flow-like (like Gutenboarding)?

<img width="1373" alt="Screen Shot 2020-08-11 at 12 03 57 PM" src="https://user-images.githubusercontent.com/204742/89932382-cb5d7d80-dbca-11ea-9d9e-cec513ae0178.png">

I didn't think having the side-panel persistently visible on mobile is not very helpful. Close icon can take users back into the Editor, and re-entering the launch flow can reflect checked off items (that they can revisit).

An alternative on the above that has step numbers to show how many steps are left: 

<img width="1297" alt="Screen Shot 2020-08-11 at 12 09 31 PM" src="https://user-images.githubusercontent.com/204742/89932938-9140ab80-dbcb-11ea-8ce0-9e12e679cee2.png">

**Comment by olaolusoga** [comment]
>An alternative on the above that has step numbers to show how many steps are left:

Like this. Let's do this for mobile. Sidebar is for desktop. @joanrho When will mobile view kick in? What does tablet portrait view look like? Would it be like mobile?

**Comment by joanrho** [comment]
@olaolusoga Yeah, tablet portrait should be like mobile, but not tablet landscape—just like how the document settings side panel functions in those viewport orientations. cc @simison
