### ISSUE TITLE
Gutenboarding launch flow: fix Choose a plan step on smaller screens

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#44693]
#### Steps to reproduce
* Make sure your viewport has less than 1440px width.
* Open the redesigned launch modal (see details and testing instruction in #43750)
* Open _Choose a plan_ step, and scroll to the bottom.

#### What I expected
_Detailed comparison_ section to be visible.

#### What happened instead
Only _Detailed comparison_ header is visible, the table being hidden.

#### Screenshot / Video
<img width="1412" alt="Screenshot 2020-08-05 at 16 17 31" src="https://user-images.githubusercontent.com/14192054/89418637-ffebb800-d738-11ea-84b7-c3a76469c00e.png">

**Comment by simison** [comment]
We could probably just hide the comparison table for now and figure this out next week.

**Comment by yansern** [comment]
Fixed this in https://github.com/Automattic/wp-calypso/pull/44768/commits/6624791c9128368b6797ed8273ab0396a88480e9 as part of https://github.com/Automattic/wp-calypso/pull/44768.
