### ISSUE TITLE
Reader: Importing OPML asks user to refresh page before import is complete

### ISSUE THREAD

**Issue by dreamertim** [Automattic/wp-calypso#4469]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/following/edit
2. Have a large-ish (30+ source) OPML file to import.
3. Import the file.
4. Reader immediately claims the import is finished. Says, "Please refresh to see the sites you are following." (paraphrased)
5. Refresh the page to see only one or two sites from imported OPML file.
#### What I expected

I expected to see all of approximately 30 source sites that were in my OPML file imported into the Reader when the Reader told me the import was complete.
#### What happened instead

I saw only one or two sites imported. This caused me to believe the import had failed or there was an issue with the imported OPML file.

Instead, the import required more time. This _should_ have been noted in the message returned by the Reader, rather than the Reader claiming the import was finished.
#### Browser / OS version

Safari 9.1 on OS X 10.11.4

**Comment by bluefuton** [comment]
Just to update you on this @dreamertim - we have changed the messaging in the revamped Following Manage:
 
<img width="796" alt="screen shot 2017-07-12 at 14 23 00" src="https://user-images.githubusercontent.com/17325/28119698-ae3a0226-670d-11e7-8c7d-f619f9d9d5fc.png">

Thanks for the report!
