### ISSUE TITLE
Gutenboarding site launch: fix modal styling

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#44691]
#### What happened instead
When opening the redesigned launch modal (see details and testing instruction in #43750), the following can be reproduced when the content (left side) has a bigger height than the viewport height:
* there is a double vertical scrollbar.
* editor breadcrumbs are visible but cut off.
* editor is not fully covered by the white background.

#### Screenshot / Video

<img width="1379" alt="Screenshot 2020-08-05 at 16 09 32" src="https://user-images.githubusercontent.com/14192054/89417738-c5cde680-d737-11ea-9e3d-5d020e3750c8.png">

**Comment by yansern** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/44768/commits/6ca29b5e6990468b71c0fb879ac4e10fb059041d as part of PR https://github.com/Automattic/wp-calypso/pull/44768.
