### ISSUE TITLE
Feature request: Edit form input label on Subscription Form Block

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#44713]
It seems like we added a ton of options for the [Subscription Form block lately](https://wordpress.com/support/wordpress-editor/blocks/subscription-form-block/), but in helping a user today in support at WordPress.com I noticed I couldn't help them since there is not an option to edit the input label on the form field:

![Screen Shot 2020-08-05 at 13 12 24](https://user-images.githubusercontent.com/31009008/89451571-6ddcb300-d72a-11ea-8e2e-fdbd792eb78a.png)

This would be important for sites in a different language than English.

I wonder if it's a small change we could make to make the editing experience more complete for this block. I also understand this is a Jetpack block so feel free to move to their repo if needed! Just wanted to bring it up in the Create stage first.

**Comment by andrewserong** [comment]
Thanks for raising this feature idea @davipontesblog! It's a good idea, and I can see there's already an open issue for the feature as an enhancement over in the Jetpack repo from July (https://github.com/Automattic/jetpack/issues/16620), so I'll close out this issue. Apologies for the (very) delayed reply!
