### ISSUE TITLE
Cover Block: free users can use videos previously uploaded with a premium or bigger plan

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#44720]
#### Steps to reproduce

1. Go to a premium site
2. Upload a video
3. Remove the premium subscription
4. Go to /wp-admin of that site
5. Edit a page
6. Use `cover` block
7. Click `Media Library`
8. Select the video previously uploaded

#### What I expected
The video should not be added in the editor and upgrade nudge should appear

#### What happened instead
Video was added to the editor. I could save and view the page as a guest user

#### Screenshot / Video
The nudge banner correctly denotes I am not on a premium or greater plan

![SS 2020-08-06 at 00 11 49](https://user-images.githubusercontent.com/12430020/89464704-8d4efc80-d779-11ea-9c57-1f2fdfe1d5b4.gif)

**Comment by davemart-in** [comment]
Thanks for highlighting this @cpapazoglou! From my point of view, since this is such an edge case I'm not super worried about it. Let's close this issue out for now. We can always reopen it in the future if it becomes something that we're worried about.
