### ISSUE TITLE
Gutenberg/Edit Post UI: Saving a draft misleadingly says it saved draft even if there's a problem with the API

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#44738]
#### Steps to reproduce

1. Open the editor to edit/create a post.
2. Write something in the editor. Save it to make sure a draft is created (haven't tested with unsaved draft)
3. Break your WPCOM sandbox (syntax error, `die();`, whatever, to return an invalid result from the Save call).
4. Try to save the draft

#### What I expected

When I click **Save Draft**, I should see an error that there was a problem saving the draft 

#### What happened instead

I see the **Save Draft** button change to `√ Saved` 

#### Browser / OS version

Firefox 79.0 (64-bit), macOS 10.15.5

#### Screenshot / Video

![gutenfail](https://user-images.githubusercontent.com/184938/89538651-840a7200-d803-11ea-8fbd-913dfce623bd.gif)

#### Context / Source

I was editing a post for our team P2 and wanted to save a draft from the frontend. Clicked Save Draft on the P2 frontend editor and landed in Gutenberg to edit the post. Then went out for a bit and when I returned I saw the error. Realized that my WPCOM sandbox had a syntax error in one of the files and the API was throwing `500` errors.

**Comment by cathymcbride** [comment]
The button UI reverts pretty quickly, and the error UI is pretty large. I'm going to lower the priority. Will raise again based on customer feedback.

**Comment by cathymcbride** [comment]
Closing b/c this hasn't been hit for a while. If it is, please feel free to reopen!
