### ISSUE TITLE
Export: Margins on accordion menu doesn't align

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#44741]
#### Steps to reproduce

1. Starting at URL: `/export`
2. Click the dropdown to export content
3. Note the margins in the accordion menu; they're slightly different from the parent card.

#### What I expected

Margins and padding should line up for a cleaner visual line down the page. Ideally we use the same margins/padding for all cards.

<img width="750" alt="Screen Shot 2020-08-06 at 10 06 25 AM" src="https://user-images.githubusercontent.com/2124984/89544327-f9f4e600-d7cf-11ea-86ae-62ccdb7a67dd.png">

**Comment by Aurorum** [comment]
PR for this issue in #44756 :)
