### ISSUE TITLE
Theme Showcase: Try & Customize Option Incorrectly Still Showing on Varia Themes.

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#44755]
Try & Customize is not supported for the recommended themes, but a button is still showing for it within the theme demo.

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/theme/exford/ (as an example theme)
2. Click Open Live Demo
3. Click Try & Customize in the top right corner

#### What I expected

I expected to be able to Try & Customize the theme by clicking that button. Or else, I expected the button not to be there at all.

#### What happened instead

It leads me to customize my site but does not preview the new theme. 

#### Browser / OS version

Chrome 84, WIndows 10.

#### Screenshot / Video
![Annotation on 2020-08-07 at 12-05-49](https://user-images.githubusercontent.com/30727666/89600864-69d5a000-d8a6-11ea-911f-d331469c29af.png)

#### Context / Source
#22291292-hc

**Comment by sixhours** [comment]
I've tried this flow and I'm able to preview and activate Varia-based themes in the Customizer. They don't look like the demos, but they activate as expected...

@ianstewart can you confirm we need to hide the Try & Customize button for Varia themes? I have a PR ready to go, but want to make sure I understand the "why" before I dig deeper.

**Comment by ianstewart** [comment]
> Try & Customize is not supported for the recommended themes, but a button is still showing for it within the theme demo.

- All the recommended themes can be used with the customizer.
- They all have the try and customize button in the demo.
- You can click on active ones in the theme list to customizer them.
- And Calypso has a customize link in the component that lists the active theme.
- One difference that they have is that many/all of them offer the option to open page editor to edit the home page in the after-activation-modal.

> I expected to be able to Try & Customize the theme by clicking that button. Or else, I expected the button not to be there at all.
> 
> It leads me to customize my site but does not preview the new theme.

@donalirl it sounds like you were expecting it to open up the page template shown on the screenshot in the Customizer?

**Comment by ianstewart** [comment]
> It sounds like you were expecting it to open up the page template shown on the screenshot in the Customizer?

If this is the case, is this expectation being broken with all our themes on Dotcom? I don’t think we’ll fix that issue with a removal of the button. I could see us potentially changing that flow so perhaps worth keeping open for now. Not going to "wontfix" this one because the flow _does_ seem confusing and could be improved.

**Comment by donalirl** [comment]
I tried to reproduce this again just now, and Try & Customize is working as expected and just as you described. IIRC, it wasn't previewing the theme at all when I reported this 9 months ago, but it seems ok now.

**Comment by sixhours** [comment]
Since this is not currently an engineering issue I'm moving it back to the inbox for now.

**Comment by sixhours** [comment]
This is related to #52591 so I'm going to close this in favor of that ticket.
