### ISSUE TITLE
Cover Block: Non latin text characters are rendered as gibberish inside the block if set to Wide or Full Width

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#44759]
#### Steps to reproduce

1. Add a paragraph of text with some or all non-Latin characters (I tried Norwegian, Japanese and Chinese)
2. Set Cover Block to Wide or Full Width
3. View Preview or Published site

#### What I expected

See all characters rendered normally on the front end just like on the backend. 

#### What happened instead

On the front end, any non-Latin characters inside the Cover block are rendered as gibberish. Outside the Cover block, in a simple paragraph block, the same text renders as expected.

#### Screenshot / Video

![](https://d.pr/i/5gdq1V+)
_Link: https://d.pr/i/5gdq1V_

![](https://d.pr/i/gFwXfS+)
_Link: https://d.pr/i/gFwXfS_

#### Context / Source

#painpoint #manual-testing #user-report in 3205725-zen

Thank you @akirk for initial troubleshooting p1596802986036000-slack-C02AED43D I could reproduce on Varia and other themes, on Simple Sites only.

**Comment by jackiejade** [comment]
Had another one in 19624216-hc

**Comment by sukafia** [comment]
Similar issue here: 5614158-hc

This just started recently. You can see everything looks fine on the [old cached page](https://webcache.googleusercontent.com/search?q=cache:fhJjh0TqadEJ:https://summerhillesl.com/+&cd=1&hl=en&ct=clnk&gl=rs)

**Comment by synora** [comment]
Another report in 3206094-zen. 
Affecting the blocks on their homepage. The site language is in Romanian.

**Comment by ezebecke** [comment]
One more: 3205969-zen

**Comment by aichaezzine27** [comment]
Same issue for:
- 3205668-zen
- 3205842-zen
- 3205848-zen

**Comment by jackiejade** [comment]
and anther: 23126372-hc

**Comment by simison** [comment]
Investigating and potentially fixing in p1596805395090100-slack-dotcom-create

**Comment by desnum** [comment]
Another one: hc-22452768

**Comment by dcoleonline** [comment]
hc-23210283

**Comment by kriskarkoski** [comment]
I've followed-up with the English language followu tickets in the comments above.

**Comment by sirreal** [comment]
This should be fixed as of r211836-wpcom

**Comment by sirreal** [comment]
Note that Atomic sites will continue to experience this issue: p9o2xV-Z2-p2#comment-3349

**Comment by dhackneya8c** [comment]
report in hc-23108133 - seeing this in all heading blocks, as well as in HTML blocks where user has set plain HTML <p> code. Regular paragraph blocks are displaying correctly for this user

**Comment by sirreal** [comment]
This should be fixed for all WordPress.com sites now.
