### ISSUE TITLE
Domains Page: Change Text on Change Primary Domain Button

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#44773]
#### Steps to reproduce

1. Navigate to My Site > Manage > Domains
2. Click on "Change primary domain" button

#### What I expected

The button's text should change to "Cancel primary domain change".

#### What happened instead

The button's text changes to "Abort primary domain change".

#### Browser / OS version

Tested in Chrome on macOS Catalina

#### Screenshot / Video

![Markup 2020-08-07 at 15 54 15](https://user-images.githubusercontent.com/42454301/89688629-969ead00-d8d0-11ea-8e45-ad543057b09a.png)

#### Context / Source

Although the term "abort" is accurate, it might have a negative connotation for some users.

#dogfooding

**Comment by hambai** [comment]
We fixed that in #44532
