### ISSUE TITLE
File Block: Text Colors in the Picker don't work except for White

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#44778]
So far I can reproduce in some non-Varia themes such as Independent Publisher 2, Intergalactic 2, Twenty Fifteen, Twenty Nineteen, but not Twenty Twenty.

#### Steps to reproduce

1. Add a file to the block
2. Select the filename
3. Click Text Color from the toolbar
4. Try to pick any color among the predefined ones

#### What I expected
See the text color change to the chosen one in the picker among the predefined colors
#### What happened instead
Text color doesn't change, except for white color or any custom color
#### Screenshot / Video

![](https://d.pr/i/q79obw+)
_Link: https://d.pr/i/q79obw_

#### Context / Source

#painpoint  #manual-testing #user-report in 3207954-zen

**Comment by zdenys** [comment]
Asked in p1596889361374500-slack-C029FM1EH since it's theme related in some way.

**Comment by cathymcbride** [comment]
This has been added to the create focus board, so I am removing it from the dotcom manage board.

**Comment by yansern** [comment]
I'm no longer able to replicate this issue with all the themes mentioned in the PR description.

I have also dug through all relevant gutenberg commit history to see if there were any fixes relevant to text color hooks, color palette, etc. but there aren't any.

I believe this has been fixed somewhere. We can close this issue for now.
