### ISSUE TITLE
Writing > Podcasting: Older mention of "Hidden" privacy option, for private and un-launched sites

### ISSUE THREAD

**Issue by TeniCola** [Automattic/wp-calypso#44780]
There's a minor error with some outdated copy in the Writing settings for Podcasting. On Private sites, it references our deprecated "Hidden" privacy settings in order to use the Podcasting feature.
___

#### How to reproduce

_**(NOTE: This will only be visible if the current website either hasn't been launched yet, or the site is set to Private)**_

Starting at URL: https://wordpress.com/settings/writing/
Alternatively, navigate from [WordPress.com > My Sites > Manage > Settings > Writing], then **scroll down to the Podcasting section of the Writing page**, until you see the following screenshot: https://d.pr/i/ryXwCh

![](https://cdn-std.droplr.net/files/acc_711857/ryXwCh)

The usual heads up about the site being private will appear as expected, but the second line is outdated: "_In order to enable podcasting, you must set the site visibility to **Public** or **Hidden** first._"

The interface no longer has a "Hidden" option that is distinct from Public or Private; instead, it now appears as a toggle to hide a Public website from search engines. The copy should be updated to reflect this change, to maintain consistency and to avoid potential confusion for users.
___

#### Context / Source

During my team's virtual meetup, we were creating a podcasting site for our DIFM project. This was how we discovered this error in the copy. Context in team master thread: p6knfs-29V-p2

#dogfooding #manual-testing

**Comment by Aurorum** [comment]
PR for this issue in #44784 :)

**Comment by Aurorum** [comment]
I updated the PR last week - it just needs merging now.
