### ISSUE TITLE
Customer Home: Setup checklist showing as incomplete

### ISSUE THREAD

**Issue by aaronrobertshaw** [Automattic/wp-calypso#44788]
A user is reporting that they are being shown an incomplete Setup Checklist and have no way to see what's missing or complete the checklist. This appears related to the following p58i-80Q-p2

#### Steps to reproduce

1. Login to WordPress.com as admin for rogershermanhouse.com 
2. Select rogershermanhouse.com as the site in sidebar
3. Notice that Setup progress beside "My Home" in sidebar is incomplete and there is no way to see what's missing.
4. Attempt to access checklist via https://wordpress.com/checklist/rogershermanhouse.com
5. You get a 404 error.

#### What I expected

The user could either have the ability to complete their checklist or it would not be showing as incomplete.

#### What happened instead

Setup checklist is showing as incomplete with no way for the user to complete it.

#### Browser / OS version

Chrome / MacOs

#### Screenshot / Video
![Screen Shot 2020-08-10 at 08 28 30](https://user-images.githubusercontent.com/60436221/89763762-82f48000-db36-11ea-9b68-d0bd98c1024d.png)

![Screen Shot 2020-08-10 at 08 37 09](https://user-images.githubusercontent.com/60436221/89763783-91429c00-db36-11ea-886c-f23ce18803c4.png)

#### Context / Source

#user-report

**Comment by glendaviesnz** [comment]
This is caused by the fact that the user has not installed the mobile app, which to me shouldn't be part of the site setup completion. A [PR to fix this here](https://github.com/Automattic/wp-calypso/pull/44847). In the mean time have let Happiness know that the user that reported this can safely ignore it, or install the mobile app and should go away.

**Comment by glendaviesnz** [comment]
It appears that the checklist is now part of the new customer home layouts which is why the route returns a 404.
