### ISSUE TITLE
Donations: Use a heart as block icon

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#44796]
As shown in https://github.com/Automattic/wp-calypso/issues/42856, the block icon should be an outlined heart.

Seems we don't have the SVG code for that exact icon (discussed in p1597066567258400-slack-C0Q664T29) but one alternative could be to use the heart icon available in [Gridicons](http://automattic.github.io/gridicons/) or [Material](https://material.io/resources/icons/?search=heart&icon=favorite_border&style=baseline).

Gridicons | Material
--- | ---
<img width="89" alt="Screen Shot 2020-08-10 at 15 38 56" src="https://user-images.githubusercontent.com/1233880/89789098-72390f80-db20-11ea-83ac-72876b081f07.png"> | <img width="149" alt="Screen Shot 2020-08-10 at 15 45 38" src="https://user-images.githubusercontent.com/1233880/89789381-cf34c580-db20-11ea-8bf5-1edcf2cef215.png">

**Comment by sixhours** [comment]
I would advocate for using a Gridicon here rather than Material; we're probably going to move away from using Material icons in Calypso.
