### ISSUE TITLE
CPT: Include toggles for custom post types in writing settings

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#4481]
To enable custom post types for a site, one must currently navigate to the wp-admin Writing Settings page:

![wp-admin cpt](https://cloud.githubusercontent.com/assets/1779930/14216478/04d913f4-f817-11e5-9bcf-a77c23d03f86.png)

We should seek to recreate this in the Calypso interface, ideally under the comparable Site Settings > Writing screen: https://wordpress.com/settings/writing/

**Comment by mtias** [comment]
@adambbecker to keep you in the loop if you had any concepts already for this particular setting. Usually we would render this with toggles since it's enabled/disabled.
