### ISSUE TITLE
Checkout: "Pick a payment method" is not translated

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#44827]
Although the string seems to be translated and other `@automattic/composite-checkout` strings are being correctly translated, the title for the Payment Method step is not rendering with the correct locale.

ref: pbOQVh-bN-p2#comment-730

<img width="1209" alt="Screen Shot 2020-08-11 at 8 36 04 AM" src="https://user-images.githubusercontent.com/942359/89898051-08ffdd80-dbae-11ea-949d-ee19eb3d2902.png">

**Comment by sirbrillig** [comment]
FWIW, that line is in the code here: https://github.com/Automattic/wp-calypso/blob/93616bb6be49135d62969a53b83da0fbe8a943db/packages/composite-checkout/src/components/checkout-payment-methods.js#L111

**Comment by michaeldcain** [comment]
I see [it translated here](https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=Pick+a+payment+method), with what I think is the correct reference to the composite-checkout package. The function also uses the same translation function as other properly translated strings in the package.

I'm going to ping @Automattic/i18n to see if they have an idea of what might be happening.

**Comment by yuliyan** [comment]
The issues has been addressed in https://github.com/Automattic/wp-calypso/pull/45029.

It's related to how we build translation chunks by matching translatable strings with their source reference path. A similar issue has been reported and fixed recently (p1594652385389300-slack-i18n), but it seems it has reappeared after switching to a new tool for extracting strings - `wp-babel-makepot`.
