### ISSUE TITLE
Navigation block: custom background color does not work on submenu items

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#44839]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/block-editor/page/
2. In the editor, add a navigation block - make sure that the navigation has submenu items too
3. Select a custom background color for the navigation block

#### What I expected
All menu items (including the submenus) will display correctly with the custom background color

#### What happened instead
The submenu items don't display the custom background color

#### Browser / OS version

Chrome Version 84.0.4147.89 (Official Build) (64-bit)

#### Screenshot / Video
![Screen Shot 2020-08-11 at 10 44 50](https://user-images.githubusercontent.com/39188945/89912583-b67bec80-dbc0-11ea-9cfb-1d2bbc1cb5e4.png)
![Screen Shot 2020-08-11 at 10 45 16](https://user-images.githubusercontent.com/39188945/89912588-b7148300-dbc0-11ea-8a98-9a0607874e7d.png)
![Screen Shot 2020-08-11 at 10 46 02](https://user-images.githubusercontent.com/39188945/89912591-b7ad1980-dbc0-11ea-9aae-fa789d56db42.png)

#### Context / Source

Reported here:

Chat: #23206333-hc
Follow-up Ticket: #3215856-zen
Site: https://2eyes2seecom.wordpress.com/

**Comment by Robertght** [comment]
I can confirm Automattic/themes#5589 is the same issue as the website was using Hever at the time. Closing this one for now.
