### ISSUE TITLE
Gutenboarding: open popup without waiting for post saving

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#44836]
When clicking "complete setup" in Gutenboarding, any unsaved changes on the page get saved:

<img width="587" alt="Screenshot 2020-08-11 at 17 20 10" src="https://user-images.githubusercontent.com/87168/89908790-ffe72e80-dbf6-11ea-9476-6b7e751fc539.png">

<img width="705" alt="Screenshot 2020-08-11 at 17 20 12" src="https://user-images.githubusercontent.com/87168/89908796-01b0f200-dbf7-11ea-92ca-dca70e638435.png">

This saving can seem a bit slow, but it's important we do it. Showing the launch flow doesn't depend on post getting saved tho, so we can leave the saving happen on the background while we open the modal on top of the editor.

**Comment by razvanpapadopol** [comment]
The autosave would be still needed on mobile where we redirect to the old flow.
This is the PR that introduced it: https://github.com/Automattic/wp-calypso/pull/42878
