### ISSUE TITLE
Checkout: remove checkout system decider gating

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#44830]
After merging Brazil and India support, and then removing the Jetpack gating, we can effectively remove the logic in `getCheckoutVariant()`.

**Requires:**
- [ ] #44828
- [ ] #44829

**To do:**
- add logging for products that are being added to the cart and fail (in `add-items`)
- need to research if renewals are working as expected

**Comment by sirbrillig** [comment]
This is complete.
