### ISSUE TITLE
Support: Add text notification box to contact form page for notifying users of chat down time or other support delays.

### ISSUE THREAD

**Issue by amylaneio** [Automattic/wp-calypso#4485]
Could we add the ability to add a notification to users on the contact form, for instances when chat isn't available due to downtime, or any other messages we may wish to add there?

For example, when live chat is down due to technical issues, we could add a notice there, so that users aren't frustrated without any indication of why they can't access the live chat that they paid for.

**Comment by designsimply** [comment]
I searched and the closest reference I could find to this was a "Support Notices" section in `wp-admin` (and also Network Admin > Happiness) for support.wordpress.com—but that's totally separate from Calypso so I think this is still a valid request.

(internal refs: p2UL9c-1dV-p2 #comment-11042, related for theme support: pNEWy-8yM-p2, related but outdated: PCYsg-35K-p2, also see Network Admin > Happiness)
