### ISSUE TITLE
Editing Toolkit seems to be causing Atomic site error logs to fill up with noisy entries

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#44851]
Since the GB 8.7 update, the Editing Toolkit seems to be causing Atomic site error logs to fill up with the following

```
 [08-Aug-2020 18:32:46 UTC] PHP Notice:  WP_Block_Pattern_Categories_Registry::unregister was called <strong>incorrectly</strong>. Block pattern category "columns" not found. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 8.1.0.) in /wordpress/core/5.4.2/wp-includes/functions.php on line 5167
```

Originally reported by @JoshuaGoode here: p1596912324015500-slack-C015AL3QL7M

**Comment by andrewserong** [comment]
Just adding that I noticed this in my local development environment for working on the Editing Toolkit plugin (e.g. running `npx wp-env start` from the FSE plugin directory):

![image](https://user-images.githubusercontent.com/14988353/89990702-17411d00-dcc6-11ea-939a-b49ee34e6aef.png)

Didn't get a chance to investigate further today, but I _think_ it's the same issue, so thought it worth mentioning.

**Comment by ockham** [comment]
Probably comung from here: https://github.com/Automattic/wp-calypso/blob/b8379e1ff7e41558e22677ee51dc591f2808d1e7/apps/full-site-editing/full-site-editing-plugin/block-patterns/class-block-patterns.php#L57-L59

I think the fix is to check whether the pattern is actually registered before attempting to unregister. Something like

```php
if( \WP_Block_Pattern_Categories_Registry::get_instance()->is_registered( 'columns' ) ) {
	unregister_block_pattern_category( 'columns' );
}
```

**Comment by noahtallen** [comment]
> I think the fix is to check whether the pattern is actually registered before attempting to unregister. Something like

I remember @p-jackson trying something similar to this 🤔

**Comment by p-jackson** [comment]
Never actually tried it, but yes that's what I'm hoping will work to get that message removed 🤞 

Thing is I'd still like for that category to to be unregistered, and last I looked `'columns'` is still a category in core GB. So I'm not sure what's changed; maybe the order things are loaded in?

Of course that doesn't mean we shouldn't add the `is_registered()` check. The call to `unregister_block_pattern_category()` is clearly having no effect at the moment, so no harm in `if`ing it out.
