### ISSUE TITLE
Checkout: only show editable contact details in contact information summary

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#44867]
In #44533, we stopped showing the full domain contact form for domain renewals, since editing those fields would cause the renewal to fail. However at some point since then, we started to show the full contact details in the summary for the step, which can lead to confusion when domain contact details don't align with billing details (generally only zip and country).

In the step's summary, we should only show the details that can be edited in the step.

Contact Information Summary | Contact Information Form
------------ | -------------
![Screen Shot 2020-08-12 at 8 45 29 AM](https://user-images.githubusercontent.com/942359/90018030-577aae00-dc7a-11ea-84bd-9fd07b40c456.png) | ![Screen Shot 2020-08-12 at 8 45 39 AM](https://user-images.githubusercontent.com/942359/90018052-5c3f6200-dc7a-11ea-9755-e1a86982e893.png)

**Comment by zdenys** [comment]
I encountered a case of confusion by a user here p1597333125003100-slack-CS108SDLZ
