### ISSUE TITLE
Signup: Clicking the plan card has no obvious result

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#4486]
#### Steps to reproduce
1. Log out
2. Load Calypso
3. Start a signup flow
4. Progress through the flow until you get to the plan selection screen (# of steps depends on the flow)
5. Try to click on the plan card / header (or anywhere except the button or illustration)

#### What I expected
To select the plan (or at least progress to an informational screen about the plan)

#### What happened instead
Nothing changed on screen, I noticed the `is-active` class is toggled on click ([`PlanList.openPlan`](https://github.com/Automattic/wp-calypso/blob/e6684d5e0d503e075f512ea51488ce5ae0db63f2/client/components/plans/plan-list/index.jsx#L21-L23) is being called)

#### Browser / OS version
Chrome Version 49.0.2623.87 (64-bit) / MacOS 10.11.4 (15E65)

#### Screenshot / Video
![plan-card-click](https://cloud.githubusercontent.com/assets/1587282/14219372/ddd5f55e-f827-11e5-8081-fcf7cf89beb5.png)

**Comment by jblz** [comment]
It appears it should be clickable because the cursor is a pointer / hand indicating such.

**Comment by gwwar** [comment]
Alternate Steps: 
- Navigate to http://calypso.localhost:3000/plans
- Select a site with a free plan
- Attempt to click on the Premium card as shown in the image above.
