### ISSUE TITLE
Checkout: show when product is renewal vs original purchase

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#44877]
In legacy Checkout, we show the user that a product is a renewal by changing the submit button text to "Renew Subscription", but we lack any similar indication in the new Checkout flow. It would be nice to add "Renewal" to the line item label or sub-label (i.e. "Plan Subscription Renewal: $8 per month x 12")

Currently for plan renewal:
<img width="571" alt="Screen Shot 2020-08-12 at 12 06 56 PM" src="https://user-images.githubusercontent.com/942359/90040757-548db680-dc96-11ea-8c30-97cd9246dfc0.png">

Related to: Related to this: https://github.com/Automattic/wp-calypso/issues/38978

**Comment by michaeldcain** [comment]
@fditrapani for his thoughts on where we should indicate the renewal

**Comment by fditrapani** [comment]
Yeah, two ideas come to mind.

1. WordPress.com Premium renewal as the product name (Same for other products filippodt.com renewal, G Suite Renewal), or
2. Plan renewal: $8 per month x 12 as the descriptor. (Same could go for domains > .com domain renewal vs. .com domain registration).
