### ISSUE TITLE
Transparent Background Color on Button block Outline 

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#44878]
#### Steps to reproduce

1. Add a [button block](https://wordpress.com/support/wordpress-editor/blocks/buttons-block/).
2. Select "Outline" as design.
3. Apply background color on button block.

#### What I expected

![image link 1](https://cldup.com/9rNMlKfcmj.png)
image link: https://cloudup.com/cGJGhTk4Qrv

#### What happened instead

The button block does not have background color, instead shown in transparent background color.

The following CSS was used below:

https://c0.wp.com/c/5.5/wp-includes/css/dist/block-library/style.min.css

#### Browser / OS version

WordPress v5.5
Gutenberg v8.7.1

#### Screenshot / Video

![image link 2](https://cldup.com/uNsdufiAXw.png)
image link: https://cloudup.com/ckOmgB4dlES

#### Context / Source

 #user-report 
#3217539-zen

**Comment by lakellie** [comment]
Another report in 23481271-hc

**Comment by lakellie** [comment]
Reported in 3254707-zen on a simple site

**Comment by lakellie** [comment]
Another report in 3371877-zen (simple site)

**Comment by nerdysandy** [comment]
I can't replicate the issue anymore. I also double-checked it on one of the sites reported above. For them, it shows as expected on the live site https://d.pr/i/bJjtdT
