### ISSUE TITLE
Pages: Trashing a post does not work

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#4488]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/pages/published/sirbrilligtesttwo.wordpress.com
2. Click the ... ellipses link next to any post
3. Click "Trash" in the menu that appears

#### What I expected

The page to be moved to the trash.

#### What happened instead

The "Trashing Page..." spinner appears and in the console I see the error `Uncaught TypeError: postHandle.del is not a function`. The page is not delete or moved to the Trash.

#### Browser / OS version

Chrome 49.0.2623.87, Mac OS 10.11.3

#### Screenshot / Video

The error:

<img width="476" alt="screen shot 2016-04-01 at 4 43 32 pm" src="https://cloud.githubusercontent.com/assets/2036909/14219582/14025694-f829-11e5-9dbb-050a220fdaa7.png">

Video: https://cloudup.com/cZNb_41yA_W

**Comment by lancewillett** [comment]
I can repeat the error, same steps. Mac-n-Chrome with wpcalypso on a test blog.

![screen shot 2016-04-01 at 13 50 18](https://cloud.githubusercontent.com/assets/66797/14219731/b85546b6-f810-11e5-9ae6-f9b731eb62c0.png)

**Comment by lancewillett** [comment]
The spinner never goes away...

**Comment by lancewillett** [comment]
This looks like it affects Posts, also:

![screen shot 2016-04-01 at 14 56 29](https://cloud.githubusercontent.com/assets/66797/14221200/f33eac32-f819-11e5-9e9b-f77e7c304055.png)
