### ISSUE TITLE
New Site Creation: Enhancement on adding website address step

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#44899]
Hi team! This is not an issue, but maybe more on enhancements. Feel free to share your insights/thoughts on this.

I found that the flow omitted (?) the website address creation step. Not exactly omitted, but appeared in the top left corner of the screen -- and could be missed (I know I did 😅 )

#### Steps to reproduce

1. Create the website on wordpress.com/new
2. Follow the flow: "My site is about..." 
3. Choose the design
4. Choose the font
5. Choose the plan
6. Website created

#### What I expected
I expected to see a page/part of the flow where I can edit/create website address -- to have https://wordpress.com/new/domains-modal displayed as part of the flow, so we don't have to click the modal:

![image](https://cldup.com/IMckY-S0-c.png)
*Direct link: https://cldup.com/IMckY-S0-c.png*

#### What happened instead
I just found out that if I don't have a website with my username, the system will generate the website automatically using my username, in this case: `anyusername - at wordpress.com`. 

---

Some folks might choose not to use their username as website address or have another name on their mind. In some cases, HEs might need to create throwaway websites for backup purposes. To give the option for them to change the website address as part of the flow might be super helpful.

#anecdote

**Comment by yansern** [comment]
The flow has went through several iterations, history of changes is tracked here pbAok1-16b-p2.
Domain step is now shown as second step.
