### ISSUE TITLE
Nav sidebar: add analytics

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#44907]
Events to track:

1. When the sidebar is opened
2. When the user goes back to the dashboard
3. When the user navigates to a new post/page
4. When the user clicks on "add a new post/page"

Request from: p1597310072473200-slack-CRWCHQGUB

**Comment by ramonjd** [comment]
We do have a small, but functional, tracking implementation in the editing toolkit:

https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/utils/tracking.js

I wonder if it's worth moving that to the common directory: https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/common/index.php

**Comment by andrewserong** [comment]
Also looks like we can use `recordTracksEvent` pulled from `@automattic/calypso-analytics`, which is used here: https://github.com/automattic/wp-calypso/blob/HEAD/apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts#L8, which might be a bit easier.

**Comment by ramonjd** [comment]
> Also looks like we can use recordTracksEvent pulled from @automattic/calypso-analytics

Nice! Totally missed that.

**Comment by autumnfjeld** [comment]
> Also looks like we can use `recordTracksEvent` pulled from `@automattic/calypso-analytics`, which is used here: https://github.com/automattic/wp-calypso/blob/HEAD/apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts#L8, which might be a bit easier.

In the calypso-analytics [readme](https://github.com/Automattic/wp-calypso/tree/master/packages/calypso-analytics) it says:
> In most situations it is best to use the Analytics Middleware, which has no direct browser dependencies and therefore will not complicate any unit testing of the modules where it is used.

I don't have the context yet to judge if it is better to use the middleware approach.  Any thoughts?

**Comment by ramonjd** [comment]
> I don't have the context yet to judge if it is better to use the middleware approach. Any thoughts?

I think it's okay to ignore that advice when we're using the tracking methods in the Editing Toolkit. The middleware doesn't exist in that app, and I don't think we're going to patch it in.

You're pretty safe following the examples from https://github.com/automattic/wp-calypso/blob/HEAD/apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts#L8 and https://github.com/automattic/wp-calypso/blob/HEAD/apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts#L76 I reckon.

You can go ahead and implement what you think is right, then we can 👀 at it and worry about tracking event property names and so on in the PR review comments.

**Comment by autumnfjeld** [comment]
Implemented in https://github.com/Automattic/wp-calypso/pull/45429
