### ISSUE TITLE
Customer home: no stats this week confusing for new sites

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#44918]
At customer home there's this stats bit for launched sites:

<img width="1136" alt="Screenshot 2020-08-13 at 17 27 48" src="https://user-images.githubusercontent.com/87168/90147015-66e91c80-dd8a-11ea-9780-727aa007c497.png">

If the site was launched less than week ago, it makes sense there's none.

Could it be more hopeful and more actionable? 

So if site launch happened within the past week and there are no stats, we show something like _"We're collecting your stats! Come back and see after a week."_

This would be a perfect spot for very subtle mobile apps nudge too. Could be just a text link, or something more substantial. Perhaps this could be moved in place of stats and it could mention statistics?

<img width="360" alt="Screenshot 2020-08-13 at 17 32 22" src="https://user-images.githubusercontent.com/87168/90147611-0c9c8b80-dd8b-11ea-9c8f-805459e2d76e.png">

cc @rickybanister as I remember some Slack chat about this, and @lessbloat maybe you've thought about this already.

**Comment by rickybanister** [comment]
@danhauk I really thought I remembered an initial stats view that had a different and more welcoming message. Am I mistaken?

**Comment by rickybanister** [comment]
I was probably thinking of the pre-launch message: https://github.com/Automattic/wp-calypso/issues/41034

@lcollette could you wrangle a message for brand new sites that don't have any traffic yet? We can be creative as we want here, encouraging them to go write something, connect accounts, read an article about traffic, whatever.

**Comment by danhauk** [comment]
@rickybanister I collected some snippets to help teach users if there are no stats in this post pbAPfg-kk-p2. Could that be what you're thinking of? We could definitely build on those to push them toward action.

There was also a mockup somewhere that had a message something like "One of the best ways to increase traffic is by writing original content. [link]Start a new post[/link]"

**Comment by davemart-in** [comment]
@rickybanister it's not clear to me what design is being promoted here. Can you please share the final design that you think is ready to be implemented for this?

**Comment by sfougnier** [comment]
I have a handful of different messages I tried out, any preferences on these? It seems like a lot to have 2 links in this area, but I have a few options with one tied to the message.

<img width="2173" alt="Screen Shot 2020-08-20 at 4 31 43 PM" src="https://user-images.githubusercontent.com/67021691/90823046-58a77d00-e303-11ea-8539-0b63bdf5027e.png">

**Comment by rickybanister** [comment]
I prefer the simplified card as well. The ghost graph bars in the background are noisy in the current implementation.

**Comment by sfougnier** [comment]
Ooh, yes love the idea of simplifying the card! I guess I didn't realize that was an option here. How is this latest exploration feeling?

<img width="1440" alt="01C Desktop" src="https://user-images.githubusercontent.com/67021691/91348044-37d2a200-e7b1-11ea-9eb4-eddd8dd88d4d.png">
<img width="1440" alt="01C Desktop-1" src="https://user-images.githubusercontent.com/67021691/91348039-3608de80-e7b1-11ea-878c-dc7f4ad26484.png">
<img width="1440" alt="01C Desktop-2" src="https://user-images.githubusercontent.com/67021691/91348041-36a17500-e7b1-11ea-91ed-eeff3344f5f0.png">

**Comment by rickybanister** [comment]
Nice. The third option feels like the best economy for the space, less like a placeholder and more like a helpful message. 

We could perhaps make the whole card clickable based on the message and destination. 

Super minor thing, but all 'sentences' in our UI should have punctuation. A label or a headline doesn't need any, but descriptive text is often in sentence/paragraph form.

**Comment by sfougnier** [comment]
Cool! I tweaked some of the padding and shifted things so that type and illustration can be consistent with placement in other cards. Also added in a few different options for lines of copy [here](https://www.figma.com/file/KPe3UmKlAR8R72htph4YXg/Customer-Home-Stats-Empty-State?node-id=1%3A3154).

**Desktop**
<img width="1440" alt="01A Desktop" src="https://user-images.githubusercontent.com/67021691/91352754-47091e00-e7b8-11ea-8e93-4df10378d49a.png">

**Mobile**
<img width="375" alt="01A Mobile" src="https://user-images.githubusercontent.com/67021691/91352759-48d2e180-e7b8-11ea-97fb-347230a57f39.png">

**Comment by rickybanister** [comment]
That's a solid improvement. Looks good to me. 

I noticed some spacing inconsistencies with our 'base-line grid' (I know we don't have one):

![image](https://user-images.githubusercontent.com/437258/91456757-a6ffd300-e851-11ea-9e3e-14e90bd28dbf.png)

@sixhours could you see about making the sub-heading-to-paragraph spacing a bit more consistent on My Home, at least in the areas I highlighted where the font sizes are the same and it seems like we are aiming for the same treatment?

**Comment by sixhours** [comment]
Hmm, the live version of Customer Home doesn't seem to have this problem (all the red rectangles are copied and the same size):

<img width="1095" alt="Screen Shot 2020-08-31 at 2 53 39 PM" src="https://user-images.githubusercontent.com/2124984/91756024-12230f80-eb9a-11ea-82fd-869d894dba1d.png">

Is it possible this is a screenshot from an older mockup?

The "Grow your sites" piece should definitely observe the same spacing between the header and paragraph content when implemented 👍

**Comment by rickybanister** [comment]
Cool! Sorry to nitpick, I'm sure it was just an issue with an out of date mockup. I highlighted just in case it was happening in production, but should have checked myself.

**Comment by autumnfjeld** [comment]
We can do an interim fix while @jeffgolenski works through My Home Pod design improvements.
The copy change suggested in the description of this PR:  "We're collecting your stats! Come back and see after a week."

**Comment by p-jackson** [comment]
Got a PR up to update the new site case #52702 
New sites are currently shown `No traffic yet, but you'll get there!` and I'm changing it to `We're collecting your stats! Come back and see after a week.`

The message in this GH issue's description (`No traffic this week, but don't give up!`) is actually what's being shown to sites older than a week. I feel like this should be updated too, but it feels a bit harder to know what to say. If a site has no posts maybe a link to how to write their first post would be good, but how do we know the site is a blog? Perhaps we could link the user to SEO help, but how do we know they're happy enough with their site to do that yet?
Maybe a generic `No traffic this week` message is better than `No traffic this week, but don't give up!`? The lack of traffic could be entirely expected. `No traffic this week` by itself does feel a bit clinical though.

**Comment by autumnfjeld** [comment]
>  If a site has no posts maybe a link to how to write their first post would be good,

Ohh, that's cool.  Prompts of encouragement! Particularly  if we can target it to customized suggestions: like we know the user doesn't post frequently or could add social media links

**Comment by jordesign** [comment]
Closing this - as it is already being considered as part of pbAok1-2L4-p2w
