### ISSUE TITLE
Add small summary to "launch your site" card at customer home

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#44915]
At https://wordpress.com/home, for unlaunched sites there is this card:

![image](https://user-images.githubusercontent.com/87168/90139726-68faad80-dd81-11ea-9073-f75839bbc6c1.png)

Let's add a small sales pitch here if they're about to launch with free `.wordpress.com` subdomain:

![image](https://user-images.githubusercontent.com/87168/90139796-80399b00-dd81-11ea-82cc-4d3792479f5e.png)

**Context:** in Gutenboarding, we're weakening the domain-sales pitch by not showing it as a mandatory step for everyone. Thus we need stronger sales pitch later in the flow, which also doesn't hurt non-Gutenboarding sites.

#### Techie bits

This might need to be added at:

https://github.com/Automattic/wp-calypso/blob/e92c4cc0665bf53ff8409f78f37ef4a1b0115119/client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js#L162-L173

You might want to tweak [the `CurrentTaskItem` component](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/customer-home/cards/tasks/site-setup-list/current-task-item.jsx) to better accommodate that new content (e.g. with a new prop)

**Comment by simison** [comment]
@olaolusoga what do you think about somehow bringing their current free subdomain domain to this view? Just to bring some comparison to this suggestion. Could it somehow be task description above?

**Comment by jordesign** [comment]
I like the idea of a prompt about the domain the site would be launching with here. Would be good for the My Home Pod to consider this.

**Comment by jeffgolenski** [comment]
The idea is great, but I want to give this a more permanent home with a revised IA. For now, feel free to add this and start collecting data on its usage. 

I'm thinking more of that "site status" area I mentioned is going to be the best place for this since we'll have a quick glance at the customers' plan, domain, and email status. @jordesign @simison

**Comment by jordesign** [comment]
I'd be happy to close this in favour of it being covered with the eventual 'site status' area.

**Comment by simison** [comment]
@jeffgolenski @jordesign some context on this:

We didn't have the new "launch flow" yet (you can check it by pressing "launch" in the editor) when I wrote this and were focusing on free-to-paid-conversion quick wins within signup flow. This also was copy-paste visual just to communicate the point, not an actual design I wanted to get implemented as-is. 😅 

I agree status area works better for this. Another thing I'd consider is "add domain" (or "transfer domain" if they so indicated at signup, see pcYYhz-1A-p2). Perhaps that makes sense post-launch either in its own checklist or as the first iteration within the same checklist.

Feel free to close this one!

**Comment by jordesign** [comment]
Closing this as things will otherwise change as part of the My Home B2B Pod
