### ISSUE TITLE
New Onboarding launch: consolidate font sizes

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#44933]
Consolidate font sizes in new launch flow using pre-defined variables and base-font size

<img src="https://user-images.githubusercontent.com/87168/90222240-5da49200-de14-11ea-9767-2e2da745d30f.png" alt="" width="400"/>

https://wpcalypso.wordpress.com/devdocs/typography

https://github.com/Automattic/wp-calypso/blob/934477f0ebfe930e71679782b314596c0ec81a8d/packages/typography/styles/variables.scss#L36-L45

- There shouldn't be 13px, it's not part of the above list. They should be 12px or 14px.
- the sub-text is using .75rem, but should probably be 12px.
    <img src="https://user-images.githubusercontent.com/87168/90222039-f1c22980-de13-11ea-940a-8d70c1922390.png" alt="" width="500"/>
- This is also 13px
    <img src="https://user-images.githubusercontent.com/87168/90222050-f5ee4700-de13-11ea-8f17-faf3577248b8.png" alt="" width="200"/>

**Comment by razvanpapadopol** [comment]
For this we should first set the 'root' font (`.nux-modal`) to `$font-body` similar to how [we've done for Gutenboarding](https://github.com/Automattic/wp-calypso/pull/43039/files).

**Comment by youbrokesomething** [comment]
@simison This issue got abandoned when the project board it was on was made inactive. Is it still needed?
