### ISSUE TITLE
Jetpack Search: offer bundle to users on free plan in settings/performance

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#44931]
Similar to #44159.

#### Steps to reproduce

1. Starting at URL: http://calypso.localhost:3000/settings/performance/<your-site-url> for a free site that doesn't have Jetpack Search enabled
2. Note that the promo banner directs you to sign up for Business Plan to get Jetpack Search

<img width="778" alt="Screen Shot 2020-08-14 at 12 09 39" src="https://user-images.githubusercontent.com/17325/90198869-2095cb00-de27-11ea-934f-526853b4e309.png">

#### What I expected

To be able to add the Jetpack Search bundle without signing up for a plan.

#### What happened instead

I was directed to the Plans page which has no mention of Jetpack Search.

#### Context / Source

Discovered while testing a Jetpack Search PR.

**Comment by gibrown** [comment]
This is shipped
