### ISSUE TITLE
Purchases: Domain mapping not showing as included in plan

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#4497]
I have a test site with a domain mapping that is included in the plan, but this isn't made clear in the manage purchase screen:

<img width="780" alt="screen shot 2016-04-04 at 09 43 02" src="https://cloud.githubusercontent.com/assets/275961/14242783/d1ed2fc2-fa49-11e5-90b4-a580335a59ba.png">

I haven't tested this for domain registrations.

Steps to replicate:
1. Purchase a plan
2. Purchase a domain mapping
3. Ensure that the domain mapping is tied to the plan using the administrative tools
4. Notice that this is not reflected in the client.

This also happens when you purchase the domain first and then then plan.

**Comment by drewblaisdell** [comment]
> 3. Ensure that the domain mapping is tied to the plan using the administrative tools

I was not able to assert this. I purchased a mapping and a plan at the same time, and they were not bundled together. Because this probably isn't a client issue, I'm closing this issue and opening one elsewhere.

**Comment by drewblaisdell** [comment]
Also, when using the domain credit to purchase a domain mapping after I bought a plan separately, I was able to assert that `ManagePurchase` [displays the domain mapping state properly](https://cloudup.com/cdXWm50frgo).
