### ISSUE TITLE
Site Domains - Translated labels not aligned

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#44982]
Under `Manage > Domains > Site Domains`, here's the display in English:

![english](https://user-images.githubusercontent.com/15944096/90484899-688b5980-e169-11ea-845b-922023f6eac6.png)

Here's the display when the translations are longer, like in French:

![french](https://user-images.githubusercontent.com/15944096/90485047-95d80780-e169-11ea-853a-2905ff9abd78.png)

**Comment by klimeryk** [comment]
Great catch!
@fditrapani @hambai, could you have a look at this? 🙏

**Comment by fditrapani** [comment]
Yes! great catch! Thanks for bringing this up. There are actually some changes I'd like to propose based on the payments work that I have been doing that will simplify these columns. For the time being, I wonder if we can restrict the label to a certain number of characters and have the "i" do the rest of the speaking for when it's too long. I know it's not pretty but it should work until we make the updates I mentioned. 

![image](https://user-images.githubusercontent.com/6981253/90541835-38d05780-e151-11ea-9b38-aa876e386936.png)

**Comment by Aurorum** [comment]
I've opened a PR for that change in #44995. :) 

<img width="1163" alt="Screenshot 2020-08-18 at 18 20 23" src="https://user-images.githubusercontent.com/43215253/90544771-8663b900-e17f-11ea-9fc3-b91a455c1a53.png">
