### ISSUE TITLE
Reader: centered paragraphs are displayed with left text alignment

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#44992]
#### Steps to reproduce

1. Go to WordPress.com > My Site > Posts > Add new post.
1. Add a paragraph block and change the color for it in the block settings.
1. Add a paragraph with "Align text left".
1. Add a paragraph with "Align text center".
1. Add a paragraph with "Align text right".
1. Publish the post.
1. View the post in the Reader and check to see if the paragraph alignment looks correct.

#### What I expected

I expected that centered text would appear center-aligned in the Reader.

#### What happened instead

No alignment options are respected in the Reader.

#### Browser / OS version

* Safari 13.1.1 on macOS 10.15.4 
* Safari iOS 13.6 on iPhone 11
* WPiOS 15.5.01 on iPhone 11

#### Screenshot / Video

Web|Reader web|Reader mobile web|Reader iOS app Dark Mode
---|---|---|---
<img width="1280" alt="Screen Shot 2020-08-18 at Aug 18 9 03 24 AM" src="https://user-images.githubusercontent.com/1119271/90530364-0a8f4f80-e132-11ea-9e4a-46b1a720c793.png">|<img width="1280" alt="Screen Shot 2020-08-18 at Aug 18 8 59 31 AM" src="https://user-images.githubusercontent.com/1119271/90530395-13802100-e132-11ea-8885-52bb17acbe29.png">|![IMG_4513](https://user-images.githubusercontent.com/1119271/90530469-2a267800-e132-11ea-9f2d-9a24d967ff98.png)|![IMG_4515](https://user-images.githubusercontent.com/1119271/90530480-2c88d200-e132-11ea-93ab-e3b75b8da866.png)

* Web: https://made4testing0318.blog/2020/08/18/paragraph-color-alignment/
* Reader: https://wordpress.com/read/feeds/96421692/posts/2866304892

#### Context / Source

In mobile support, we have observed that users have asked for text alignment and colors to be respected in the Reader. We discussed which of those things should be respected in an intentionally style-neutral environment such as the Reader at https://github.com/wordpress-mobile/WordPress-iOS/issues/13930#issuecomment-615465956 and the consensus was that we should not support color changes in the Reader but we are open to supporting alignment. 

In another `wp-calypso` issue at https://github.com/Automattic/wp-calypso/issues/43595#issuecomment-653341158, it was suggested that headings should be displayed with the correct size and alignment, but not colors, to respect some styles the content creator has added while still keeping the Reader's look.

In my experience talking with users, centering would be the most wanted.

From a maintenance perspective, I can see not supporting only center-aligned text because left-aligned or right-aligned text could change the flow of the document in unexpected ways. Centered text does seem to be a use case that could benefit the fundamental reading flow of a document without unwanted side effects, and this also applies (probably more strongly) to other blocks such as buttons, quotes, and images. My recommendation would be to support centering and it's up to you which blocks should support center-alignment and which should not—for example, you could decide to allow centering to work for buttons, quotes, and images but not for paragraphs.

#perspective #manual-testing #user-report

**Comment by gibrown** [comment]
@davemart-in @kwight could a designer better define what styling info from the original post should be allowed to get displayed in the Reader? And also come to a consensus on both mobile and Calypso what we want to support here? The request by @davemart-in to display colors for instance conflicts with @mattmiklic in https://github.com/wordpress-mobile/WordPress-iOS/issues/13930#issuecomment-615484961

**Comment by davemart-in** [comment]
I think the context is important here. Matt weighed in specifically on headings not needing color. I'd agree with that. Disallowing color in paragraph blocks seems reasonable as well if that is something we feel strongly about, but allowing color in a paragraph feels like it may have more realistic use cases (like calling attention to a specific phrase) than color in a header.

**Comment by gibrown** [comment]
@davemart-in that somewhat helps a few more details though as some attempted implementations that have been trying to pass all styling info through to the reader (see https://github.com/Automattic/wp-calypso/pull/46720). It seems like @kwight is on the same page as us on improving the normalization process for Reader. From what I can tell it would be helpful to define the explicit list of styles that we want to allow to pass through. This may be good for email, RSS, etc as well.

> allowing color in a paragraph feels like it may have more realistic use cases (like calling attention to a specific phrase)

Isn't this problematic because the user could have highlighted something in white and their site has a black background while the Reader has a white background so the text will disappear? Are we going to invert the colors in some way?

**Comment by davemart-in** [comment]
> From what I can tell it would be helpful to define the explicit list of styles that we want to allow to pass through. This may be good for email, RSS, etc as well.
Makes sense. cc'ing @rickybanister so he can weigh in.

> Isn't this problematic because the user could have highlighted something in white and their site has a black background while the Reader has a white background so the text will disappear? Are we going to invert the colors in some way?
This is a good point that I hadn't considered.

**Comment by kwight** [comment]
We'll need to come back to this with a better approach when time permits; a process that allows certain inline styles for a block after some proper design consideration.

**Comment by rickybanister** [comment]
Without digging terribly deeply into the problem I'd say that our goal is to create an experience similar (but hopefully better) than RSS using semantic content to translate things from a customer's site to the Reader. That would stop short of letting customer-defined styles through. 

Text alignment is achieved through css, and there's no semantic html tags to align text so I'd say it falls outside of what we need to allow.

We perhaps should consider approaches down the line where we only display excerpts in the reader UI itself, and read more expander links would open a modal view with more styled content.

**Comment by lcollette** [comment]
> Without digging terribly deeply into the problem I'd say that our goal is to create an experience similar (but hopefully better) than RSS using semantic content to translate things from a customer's site to the Reader. That would stop short of letting customer-defined styles through.

I share this opinion.

**Comment by davipontesblog** [comment]
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by kwight** [comment]
Reader changes for the sake of better block rendering needs further investigation; see paYKcK-KO-p2 for context.

**Comment by davemart-in** [comment]
This issue should be fixed now.
