### ISSUE TITLE
Live Demo > Try an Customize handles multiple sites UI poorly

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#44994]
#### Steps to reproduce

Make sure you have multiple sites for your current user

1. Starting at URL: https://wordpress.com/theme/maywood
2. Click Open Live Demo
3. Click Try and Customize
4. Drop down dropdown. Note UI. There is only one site listed

![image](https://user-images.githubusercontent.com/16654218/90526568-8e4f3900-e13e-11ea-8696-bef7184f8e17.png)

5. Click Try and Customize
6. A list of your sites is presented. Select a site and you are sent to the correct UI. You may or may not run into https://github.com/Automattic/wp-calypso/issues/44755

### What I expected
Multiple site choice to be presented to me once, with a working UI and search bar.

#### What happened instead
Only one site is listed and the search bar overwrites the inaccurate "No Sites Found" message. In addition, Search doesn't appear to function.

#### Browser / OS version
Don't think this is browser specific as it reproes on both safari and Chrome

**Comment by cathymcbride** [comment]
This does still repro, but I doubt this is a route our customers take very often. Please feel free to reopen if you run across a more mainstream case!

**Comment by supernovia** [comment]
I still see this too from the themes page, regardless of theme. Spotted while testing something else, so I don't know if users will see it, but for what it's worth I haven't been seeing this for a while.
