### ISSUE TITLE
Purchases: Re-fetch the list of purchases when a user buys something

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#4499]
Currently, when a user buys a new product, the list of purchases does not contain the new item. When a user purchases a new product the list of purchases should be fetched again from the server, so that the new purchases appears in the list at `/purchases`.

Steps to reproduce:
1. Visit `/purchases` for a site with no purchases (it should be empty)
2. Visit `/plans/:site` and select a new plan
3. Go through the checkout flow and purchase the plan
4. Return to `/purchases` and assert that there are still no purchases

**Comment by stephanethomas** [comment]
I'm surprised we still have this issue. I thought we fixed it - the `/me/transactions` API endpoint indeed returns the new list of purchases.

**Comment by drewblaisdell** [comment]
> The `/me/transactions` API endpoint already returns the new list of purchases so we shouldn't perform any additional fetch though.

The `purchases` property of the response from this endpoint and the receipts endpoint is sort of erroneously named, as the items in this list do not contain all of the data necessary to render `/purchases`, and contain data that the `/me/purchases` endpoint does not return. `receipt_items` or something probably would have been more appropriate.
