### ISSUE TITLE
Site Picker: No visual cue that distinguishes wpcom/Jetpack sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#450]
Originally raised by @dereksmart 

There should be a distinguishing visual cue to differentiate wpcom/Jetpack sites. At first glance there's no way to know which is which.
![jetpack1](https://cloud.githubusercontent.com/assets/128826/11326966/aca45090-91c3-11e5-8b6e-cadf576336a1.png)

![jetpack2](https://cloud.githubusercontent.com/assets/128826/11326968/b2214a78-91c3-11e5-9999-50e9fa393450.png)

**Comment by mtias** [comment]
This was a decision made on purpose since we consider WP.com / Jetpack sites to be the same.
