### ISSUE TITLE
composite-checkout: Rename `CheckoutSteps` to `CheckoutStepGroup`

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#45002]
`CheckoutSteps` is not a very good name because it's too close to `CheckoutStep`. In addition, we already have a lot of wrappers in the composite-checkout package and they need to have distinct and semantic names to help distinguish each one's purpose.

**Comment by Yogendra0Sharma** [comment]
@sirbrillig can i take this issue?

**Comment by sirbrillig** [comment]
@Yogendra0Sharma sure! Although please wait until https://github.com/Automattic/wp-calypso/pull/45012 is merged, as it would certainly introduce conflicts. I'll update this issue when that one is complete.

**Comment by sirbrillig** [comment]
It should be possible to tackle this now that the Typescript conversion is merged.

**Comment by marsonya** [comment]
@sirbrillig can i take this issue?
the issue seems to have been taken long ago but is still one.

**Comment by sirbrillig** [comment]
@marsonya go for it!

**Comment by sirbrillig** [comment]
It would still be a nice improvement if someone has time. The folks above disappeared.

**Comment by sirbrillig** [comment]
This is kind of handled now since https://github.com/Automattic/wp-calypso/pull/62114
