### ISSUE TITLE
Checkout: Thank-you page loads without scrolling to top

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#45004]
Since the redirect from some payment methods (eg: credit cards) happens via `page()`, the scroll position does not get reset when changing from checkout to the thank-you page. This is particularly notable on mobile widths when Checkout gets long.

**Comment by sirbrillig** [comment]
This could still be valuable. It should be pretty simple too; in theory we could put code to scroll to the page top just before running `page()`.

**Comment by amustaque97** [comment]
Hi @sirbrillig, How to reproduce this issue? Do we have any test account or test payment details to reproduce this issue and start working on it?

**Comment by sirbrillig** [comment]
Hi @amustaque97! Thanks for the ping.

To reproduce this issue, visit checkout on a mobile device (or a desktop device emulating mobile width) and a short enough vertical height to make sure that it's possible to scroll some of the content off the screen. Having several saved cards can help with this. For example, here's a screenshot of checkout on an emulated iPhone X just after I clicked to submit a renewal purchase:

![checkout-scroll-step-1](https://user-images.githubusercontent.com/2036909/127918835-efaa5d9e-31e8-4e80-a03d-1b67f41e1672.png)

Select a new or saved credit card as the payment method, click to submit the purchase, and then notice that the after-checkout page is also scrolled down, so that the top of the page is not visible without scrolling back up:

![checkout-scroll-step-2](https://user-images.githubusercontent.com/2036909/127918923-6c047061-7ffe-4302-b302-3bdb26bfb012.png)

You can make test accounts yourself just like regular accounts, but unfortunately the only way to use a fake payment method is to sandbox the transactions API, which requires an Automattic sandbox. Still, it's possible to solve this problem without needing to reproduce it directly. The redirect is not really related to the actual purchase. Notice that the after-checkout page used by renewals is just the site-level purchase page for the product (`https://wordpress.com/purchases/subscriptions/example.com/PURCHASE_ID`).

I'm pretty sure the redirect happens in the `performRedirect` function in `useCreatePaymentCompleteCallback`, so in theory you could modify some code in calypso to call that function directly and reproduce this issue without needing to make a purchase.

https://github.com/Automattic/wp-calypso/blob/81ac36581de9b6926531fd38652f7e160f7a521f/client/my-sites/checkout/composite-checkout/hooks/use-create-payment-complete-callback.tsx#L243-L249

**Comment by amustaque97** [comment]
Hi @sirbrillig, after going through your comment. I'm still not able to reproduce this issue. 
In order to fake payment success, I have updated `stripeCardProcessor` function [stripeCardProcessor Function](https://github.com/Automattic/wp-calypso/blob/93735fe8a5291e0b10a8090eab90e69ad4efbc43/client/my-sites/checkout/composite-checkout/lib/multi-partner-card-processor.ts#L61) something like this.


`
async function stripeCardProcessor(
	submitData: unknown,
	transactionOptions: PaymentProcessorOptions
): Promise< PaymentProcessorResponse > {
    return makeSuccessResponse( { redirect: true } );
}
`

I'm adding a screen recording, please check it and let me know if I'm missing something or doing it wrongly.
https://youtu.be/VLKIhOQuFgc

**Comment by sirbrillig** [comment]
Thank you for the recording, @amustaque97. Interesting! I wonder why this happens for me but not for you. 🤔  Nice job overriding the processor!

It might have to do with which post-checkout page you end up on. In your example, I think you were "purchasing" a new product, so you ended up on the thank-you page, which [has its own scroll-to-top behavior](https://github.com/Automattic/wp-calypso/blob/21ecbce4cb29c4007a1c07e8cb6c2b51be54373b/client/my-sites/checkout/checkout-thank-you/index.jsx#L172). In my test, I was purchasing a renewal, which sends you to the product page.

It would be nice to just add a scroll-to-top behavior on every possible post-checkout page, but there are quite a lot of them, and they can even be set dynamically so it's impossible to know them all. That's why I suggested to scroll before the redirect.

(Sorry for the delayed response! I was afk for a week! 😅 )

**Comment by amustaque97** [comment]
Hi @sirbrillig, Yeah even I was wondering why it is not happening for me. Perhaps it looks like it can only be tested with the real payment where the payment processor will return to the summary page (not sure exactly). Though, I have added to `window.scrollTo(0, 0)` in the `performRedirect` function function as you mentioned in the comment. Hopefully, it should work. 

After making changes I tried to follow the same steps but again I'm not able to reproduce this in my system... Probably you can take a look into my branch PR and try it out if it works then we can merge it as well :)
