### ISSUE TITLE
Coming Soon: mock up some UI for coming soon and gather feedback

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#45013]
We should draw some wireframes for what coming soon v2 might look like in the UI. Very rough, just so we can get some early feedback from designers. We should be able to post and then continue implementing, we can incorporate design feedback as we go as coming soon v2 probably won't have its own view that needs to be designed from the ground up.

In the same p2 we should probably mention the data model we're going to use.

**Comment by ramonjd** [comment]
Stealing an idea from the [coming soon page plugin](https://en-au.wordpress.org/plugins/coming-soon/).

We could indicate to the user somewhere that the site is in coming soon mode. 

Maybe on the Customer Home dash or in the header bar?

<img width="690" alt="Screen Shot 2020-08-26 at 12 27 05 pm" src="https://user-images.githubusercontent.com/6458278/91248267-a276e400-e797-11ea-9d29-f242d6c8bd9c.png">

**Comment by p-jackson** [comment]
I think there's something on the Customer Home that indicates they haven't launched their site yet.

Personally I'd call this out of scope. I reckon it's good as a second project that focuses on all our upsell type nudges at once (since we don't want upsell nudges appearing all over the place at once, they should be somewhat coordinated and prioritised). Encouraging the user to launch when they haven't yet is kind of like an upsell nudge imo.

**Comment by p-jackson** [comment]
The MVP doesn't have any UI changes because we're going to reuse the current visibility controls in the general settings page. And pbxlJb-q6-p2 has been the discussion this task was hoping to spark.
Feel free to re-open if you disagree.
