### ISSUE TITLE
Coming Soon: static coming soon page for sites with no paid plan

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#45015]
Acceptance criteria: before launching, if the site has no plan then site visitors to the site see a static coming soon page.

This epic has the following sub tasks:
- [ ] Render static content if `wpcom_coming_soon_mode === 'static'` (for example). Coming soon v1 already has some static content we can copy
- [ ] ??? UI for setting the site to coming soon mode? Could be necessary if there's a way for users to accidentally launch their site e.g. with a importer plugin

**Comment by ramonjd** [comment]
For simple sites (we know Atomic has already paid :) ) how are we to know if the user has a paid plan in the Editing Toolkit plugin?

Would we have to make an authenticated API call to `https://public-api.wordpress.com/rest/v1.1/sites/{$blog_id}/purchases` or `https://public-api.wordpress.com/rest/v1.2/me/sites` for example?

Or maybe we don't even need to keep it in the plugin. We could add the check it on the wpcom site of things. See: 2636a-pb

**Comment by p-jackson** [comment]
I reckon we don't check, and just block the UI in calypso if they don't have a plan.
Actually maybe that doesn't work, because it would mean if they downgraded plans they'd get to keep their editable coming soon page.

**Comment by ramonjd** [comment]
> just block the UI in calypso if they don't have a plan

Makes sense for assignment of a coming soon page 👍 i was more thinking of handling the redirect.

**Comment by p-jackson** [comment]
I initially thought we wouldn't need to block the redirect if they didn't have a plan. But now I've changed my mind :)

What we could do is look at how the Premium Content block checks the plan. If a user adds a Premium Content block to their page on a free plan then the edit view displays UI about how they need to upgrade their plan. So we could copy their logic.

**Comment by ramonjd** [comment]
What about Jetpack sites? Are we only targeting sites that do not have a free plan?

**Comment by p-jackson** [comment]
I think no Jetpack sites right? I haven't heard anyone suggest this should be a Jetpack features, and we'd need to move the code into the Jetpack plugin.
It's a good point that we should ensure that Calypso doesn't show anything coming-soon related for Jetpack sites.

**Comment by ramonjd** [comment]
We can close this. The reduced scope means that we're always showing the default, blue Coming Soon page
