### ISSUE TITLE
Coming Soon: "launching" a site

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#45016]
Acceptance criteria: going through the launch flow clears coming soon mode.

With new sites currently start as "Private by Default" so users need to go through a process in order to "launch" their site. With coming soon v2 there is "Private by Default" but we will still have a launch flow. That launch flow needs to stop the coming soon page from rendering to site visitors.

### Sub tasks:
- [x] launching clears the `wpcom_public_coming_soon` setting and potentially the `wpcom_public_coming_soon_page_id` site options
- [x] if there is a `wpcom_public_coming_soon_page_id` then convert the page to a draft (so it's no longer navigable and also removed from site menus) and communicate this change to the user
- [x] enable the various launch buttons if the `wpcom_public_coming_soon` setting is present
- [x] Ensure site becomes crawlable by search engines. (The existing launch flow might already handle this)

### Open questions/ thoughts:
Will it be possible to take a site from public back to coming soon? If so, we will have to un-draft the coming soon page and ensure that `wpcom_public_coming_soon_page_id` remains set

**Comment by ramonjd** [comment]
D50760-code (Coming Soon v2: allow wpcom_public_coming_soon sites to be set as unlaunched and to be launched)

and 

D50753-code (Allow wpcom_public_coming_soon to be set on new sites and unset when launching a site.)
