### ISSUE TITLE
Coming Soon: editable coming soon page

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#45014]
Acceptance criteria: if a site has a page marked as "coming soon" then visitors to the site will see that page.

This lays the foundations for the coming soon page (especially the data model).

The coming soon data will be saved in two options, `wpcom_coming_soon_mode` and `wpcom_coming_soon_page`. These are similar to the core options `show_on_front` and `page_on_front`; `wpcom_coming_soon_mode` says whether there is a coming soon page and what type it is, and `wpcom_coming_soon_page` is the page id of the editable coming soon page.

This epic has the following sub tasks:
- [ ] save and restore `wpcom_coming_soon_mode` and `wpcom_coming_soon_page` options using the REST API (could continue the work started in D45700-code but it might need to be moved to the toolkit plugin so it'll easily work on Atomic)
- [x] redirect site visitors to the coming soon page if one is set
- [x] UI in Calypso that allows the user to choose the coming soon page (take a look at #43831 for existing ideas of how to do this
- [ ] site visitors see the contents of the coming soon page but without a redirect (lower priority)

**Comment by ramonjd** [comment]
Set up a base PR here: https://github.com/Automattic/wp-calypso/pull/45167

Basically copying from https://github.com/Automattic/wp-calypso/pull/43831 and working from there 😆

**Comment by andrewserong** [comment]
Just following on from the various different issues and posts, is the idea to use `wpcom_coming_soon_mode` instead of the existing `wpcom_coming_soon` option so that we can gradually migrate to this new approach for coming soon, and leave the `wpcom_coming_soon` option as a legacy setting for existing sites?

**Comment by andrewserong** [comment]
Oh, and the plan is still to have it be a regular old page, or were we wanting to explore using a custom post type? If it's a normal published page, will we need to ensure it's excluded from sitemaps?

**Comment by ramonjd** [comment]
> Just following on from the various different issues and posts, is the idea to use wpcom_coming_soon_mode instead of the existing wpcom_coming_soon option so that we can gradually migrate to this new approach for coming soon, and leave the wpcom_coming_soon option as a legacy setting for existing sites?

That's about it so far. I admin there's going to be a process of experimentation and working things out as we go along.

 @p-jackson had the idea of keeping two options:

1. One to signal that coming soon mode is activated, e.g., `wpcom_coming_soon_mode`
2. One to save the page id of the current coming soon page, e.g., `wpcom_coming_soon_page_id`

That's so we could both keep track of whether the user has the mode engaged, and whether there's a page to show at all!
 :)

> Oh, and the plan is still to have it be a regular old page, or were we wanting to explore using a custom post type? 

Creating a custom post type might give us some extra flexibility, e.g., custom taxonomy, and [excluding from search options when registering](https://developer.wordpress.org/reference/functions/register_post_type/).

Worth looking into!

>  If it's a normal published page, will we need to ensure it's excluded from sitemaps?

This is a very good point! I'd say "yes" :)

**Comment by ramonjd** [comment]
> Oh, and the plan is still to have it be a regular old page, or were we wanting to explore using a custom post type?

If the user has a paid plan, they should be able to edit the coming soon page themselves. So we'll have to see which is easier to implement. 

But yeah, the coming soon page should be hidden from search, sitemap, search engines and so on I would imagine (as much as we can :) ), but still appear in the pages list in the admin page.

**Comment by ramonjd** [comment]
We can exclude pages from search, rss feed and so on using the `pre_get_posts` filter: https://developer.wordpress.org/reference/hooks/pre_get_posts/

**Comment by ramonjd** [comment]
> We can exclude pages from search, rss feed and so on using the pre_get_posts filter

Tested and works for all public queries (search, archives, rss)
https://github.com/Automattic/wp-calypso/pull/45167/files#diff-e65a637dd2fe6b4bf38157f5a4159401R25

Not quite sure about sitemaps though. Need some more investigation.

**Comment by ramonjd** [comment]
Closing this one since we've decided to push out the custom page for later. 

Thanks for the work and investigation on this task - we'll use it all later. Good job @roo2!

pbxlJb-q6-p2#comment-555
