### ISSUE TITLE
Domains: Site redirect: Price alignment broken

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#4501]
I just noticed this in Firefox:
<img width="635" alt="screen shot 2016-04-04 at 13 09 17" src="https://cloud.githubusercontent.com/assets/275961/14247525/929d14dc-fa66-11e5-9e66-a4d1696cb0f1.png">

cc @breezyskies

**Comment by umurkontaci** [comment]
Confirmed this is still an issue on small screens.

**Comment by jeremeylduvall** [comment]
Closed via #6373.
