### ISSUE TITLE
Coming Soon: add coming soon to the page selector

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#45022]
If a user deletes their editable coming soon page we'll need a way for them to reinstate it.

One suggestion is to add a simple coming soon template to the page picker.

When selected we'll update the WP option to the new ID.

**Comment by roo2** [comment]
I'm currently working on getting the `me/sites` endpoint to return `wpcom_public_coming_soon_page_id` correctly when it is set
