### ISSUE TITLE
Rewrite the Mailchimp keyring connection redirect_url to be static

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#45023]
Mailchimp is going to break November 10.

They are introducing a static direct matching of our `callback_url` passed in the Oauth proces.
https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uri-registration/

The problem is that `Keyring_Service_OAuth1` class generates `callback_url` that has nonces and other dynamic parameters:

```
		$this->callback_url = Keyring_Util::admin_url(
			$this->get_name(),
			array(
				'action'   => 'verify',
				'kr_nonce' => $kr_nonce,
				'nonce'    => $nonce,
			)
		);
```

Exact matching will naturally not handle these parameters correctly.

Previously the matching was fuzzy, so the parameters were passed through, but now when parameters are part of exact matching, the oauth connections will fail.

## What needs to be done:

1. Rewrite `Keyring_Service_Mailchimp` to pass this data in `state` parameter, how it's supposed to be done in Oauth. It may be prudent to do so in a reusable way - the same limitation prevented me from implementing Constant Contact back in the day. Make sure the redirect_url is the same every time.
1. Update the Mailchimp app on the mailchimp side - it's under my account - credentials in secret store `4668`

**Comment by pablinos** [comment]
> It may be prudent to do so in a reusable way

This looks quite similar to what we had to do with the Instagram connection, and there's [a change we made to Keyring](https://github.com/beaulebens/keyring/blob/master/keyring.php#L134) to allow the signing of the `state` object with a key, as well as automatically decrypting it and making the object values part of the request if it passes the CRC check.

This should be a fairly straightforward change

**Comment by creativecoder** [comment]
Note that you can see an example of this in the Instagram basic display connection, instagram-basic-display.php, specifically the `filter_request_token` method. We should be able to add a similar filter to the Mailchimp connection.

**Comment by creativecoder** [comment]
@Automattic/explorers 

Patch in D51464-code

**Comment by creativecoder** [comment]
Deployed in wpcom-r215560
