### ISSUE TITLE
Coming Soon: add a logged-in site preview banner

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#45020]
This task requires showing the the “Coming Soon” banner to logged-in admins of sites on the front-end to communicate that this is the view their site visitors will be seeing.

There are no functional changes, only copy changes. See p1602027273032000-slack-C016JPL5S

Current copy:

<img width="1250" alt="Screen Shot 2020-10-07 at 10 43 51 am" src="https://user-images.githubusercontent.com/6458278/95271653-27224b00-088a-11eb-991a-958a141a349a.png">

**Comment by andrewserong** [comment]
Just clarifying — is this effectively adding a new condition to the existing launch banner that's something like if _not_ private _and_ in coming soon mode? (Whereas the current one will display `"Your site is marked as \"Coming Soon\" and hidden from visitors until it's ready."` if private && launched && coming soon)

**Comment by ramonjd** [comment]
> is this effectively adding a new condition to the existing launch banner that's something like if not private and in coming soon mode

Pretty much. Without looking into the code, it should be just replaced whatever mix of conditions there are now with ours, which should really be just:

```
if ( unlaunched && coming_soon_mode_activated ) {}
```

I guess it wouldn't hurt to check if the blog is private too, though it may be that privacy has primacy. 

I'm not sure how privacy interplays with coming soon, but in the settings we do switch coming soon mode off when a user switches to private: 

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/form-general.jsx#L393

**Comment by ramonjd** [comment]
Oh, and we should probably tell the user they're in coming soon mode when they visits their site when logged in....

**Comment by roo2** [comment]
I have a diff to enable the same copy as coming soon v1 here D50736-code

**Comment by ramonjd** [comment]
Taken care of in D50736-code 🙇 Thanks!
