### ISSUE TITLE
Reader: orange "unseen content" badge doesn't go away

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#45055]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/
2. Click "My Sites"
3. Observe that Reader has an orange badge with a tooltip saying "Read the blogs and topics you follow"
4. Click "Reader"
5. Mark all content as "seen"
6. Click "My Sites"
7. Observe that the orange badge is still present (YMMV -- ping me if you need a screen capture)

#### What I expected

I expected the badge to go away when I had marked all content as read. 

I expected the tooltip to explain the badge when it's present (as the badge's `aria-label` does). 

#### What happened instead

I wasn't able to get rid of the badge. 

The tooltip was a generic description of the Reader, even though the orange badge was calling for my attention for something more specific. 

#### Browser / OS version

Safari Version 13.1.2 (15609.3.5.1.3)
macOS Catalina 10.15.6 (19G73)

#### Screenshot / Video

Available upon request.

**Comment by unDemian** [comment]
Should be fixed by code-D48426

**Comment by lsinger** [comment]
@unDemian still happening for me in staging. 😕

**Comment by lsinger** [comment]
> @unDemian still happening for me in staging. 😕

Sorry, only now realized that the change hasn't been merged yet.

**Comment by unDemian** [comment]
@lsinger this has been deployed, are you still encountering the issue?

**Comment by lsinger** [comment]
> @lsinger this has been deployed, are you still encountering the issue?

@unDemian yes, thanks -- this now works as intended. Thanks for the fix! 🙌
