### ISSUE TITLE
Premium Content: Add the ability to set a new "one-time" payment on sidebar.

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#45066]
When working with the Premium content block, please add the option to set a new "one-time" payment plan on the block sidebar.

Currently one can only see an option for adding a recurring subscription:

![Screen Shot on 2020-08-20 at 11-08-27](https://user-images.githubusercontent.com/31009008/90790011-8fff3500-e2d5-11ea-9cff-3d1f1465df28.png)

But the option for "one-time payment" is actually available if you browse the Payment options in the block itself, in the editor canvas:

![image](https://user-images.githubusercontent.com/31009008/90789785-4e6e8a00-e2d5-11ea-898a-737246f79c6b.png)

You have to dig a bit to find. You need to click on “Manage your subscriptions” to be able to create a “one-time” sale. Once created, it becomes available on the block.

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/home/
2. Go to Site > Pages
3. Click "Add new page"
4. add a "Premium Content" block

#### Browser / OS version

Chrome Version 84.0.4147.135 (Official Build) (64-bit) MacOS
Gutenberg: 8.7.1
CoBlocks: 1.23.0
wpcom-FSE: 212251766

**Comment by kwight** [comment]
Looks like we've got it in the block itself, but not the sidebar:

<img width="550" alt="Screen Shot 2020-09-09 at 9 10 53 AM" src="https://user-images.githubusercontent.com/349751/92624507-728e0d00-f27c-11ea-859c-743191c6da59.png">

**Comment by ChrissiePollock** [comment]
Requested in #3679584-zen as the customer could not find the one-time option.

**Comment by carinapilar** [comment]
I'm not able to find that option within the block anymore, it seems to only show in the sidebar, where the one-time option is missing.

The only option now seems to be creating the plan from Tools > Earn first:

![AddNewPaymentPlan](https://user-images.githubusercontent.com/16104522/132201245-d11d2116-992d-45bc-acf5-1d0959b09cf9.png)

**Comment by philnick206** [comment]
Another report here #4900320-zen

**Comment by Copons** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/23673
