### ISSUE TITLE
Notification: tables are not displayed correctly

### ISSUE THREAD

**Issue by maxme** [Automattic/wp-calypso#45093]
#### Steps to reproduce

1. Open a notification with a post including a table

#### What I expected

Table is not formatted.

#### What happened instead

Table should be formatted and styled.

#### Browser / OS version

OS X / Firefox 79.0

#### Screenshot / Video

What I see in the Reader:

<img width="1069" alt="Screenshot 2020-08-21 at 11 26 15" src="https://user-images.githubusercontent.com/40213/90875266-3106f200-e3a1-11ea-82b4-bac1d0a70f7c.png">

What I see in the Notification:

<img width="395" alt="Screenshot 2020-08-21 at 11 15 17" src="https://user-images.githubusercontent.com/40213/90875260-2e0c0180-e3a1-11ea-811c-5d92af9d120a.png">

**Comment by kwight** [comment]
I wonder if it would make sense to treat these somewhat like an embed, with a "View table in post"-type CTA – I could see us getitng away with _maybe_ supporting a 2x in notifs, but pretty much everything else will fail hard. @sixhours ?

**Comment by blackjackkent** [comment]
I've opened an in-progress PR for this at https://github.com/Automattic/wp-calypso/pull/46427 - as of right now, I have it displaying fallback text for the table, but still need to do some work to figure out how to make the post link available to the block rendering context so we can link back to the originating post. Will hopefully be able to have something mergeable by tomorrow.

**Comment by mmtr** [comment]
Fixed in D51025-code
