### ISSUE TITLE
FSE: Incorrect previews for Vesta layout in onboarding

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#45092]
## Steps to reproduce

1. Start the Horizon FSE flow
2. Check out the look of the Vesta layout on the "Choose Design" and "Pick a font pairing" steps
3. Note that the site headers in the previews are distinctly different than what is eventually rendered for the website

### Choose a design
<img width="1281" alt="Screen Shot 2020-08-21 at 2 07 25 AM" src="https://user-images.githubusercontent.com/5414230/90873982-d6937480-e353-11ea-9bfe-f26eb3adea11.png">

---

### Pick a font pairing
<img width="1281" alt="Screen Shot 2020-08-21 at 2 07 32 AM" src="https://user-images.githubusercontent.com/5414230/90873990-d98e6500-e353-11ea-9806-0b668b95ae68.png">

--- 

### Frontend
![jeremyyip398010294 wordpress com_](https://user-images.githubusercontent.com/5414230/90873995-dc895580-e353-11ea-96fa-c4f7d38ffeb3.png)

---

## What I expected

The previews in the "Choose a design" and "Pick a font pairing" steps accurately reflect what is initially populated in the site editor.

## Cause

The starter site for Vesta FSE is using the incorrect theme styling (Varia instead of Seedlet Blocks). It also _is not_ a site editor site. Creating a new starter site for Vesta FSE, as was done for Reynolds FSE, should address this problem. There's a helpful guide for this process here: https://wp.me/PCYsg-r7w#starter-site

**Comment by noahtallen** [comment]
The vesta layout was also removed, so I'm closing this out.
