### ISSUE TITLE
Premium Content Block: Ability to add a free member

### ISSUE THREAD

**Issue by bsanevans** [Automattic/wp-calypso#45090]
User would like the ability to add free members to access content behind the Premium Content Block. This member would ideally have the same access on the site as a paid member, while they haven't actually paid anything.

Mentioned by user here: 20187020-hc

User has gone with other options for now, and does not need any follow-up.

**Comment by formosattic** [comment]
Duplicate. Closing in favor of https://github.com/Automattic/wp-calypso/issues/44844.
