### ISSUE TITLE
Me / Site Picker: suggestion: use blog picker styles for primary blog dropdown

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#451]
Originally raised by @jkudish: it would be nice if the "primary blog" dropdown was similar in functionality to the main blog picker in calypso to allow easier selection of the blog to use.

Feedback from @mtias 

Agreed, whenever we show `Sites` we should use `<Site />` to render them. It would even make sense to put a list of `<Site>`s within `<DropdownSelect />`. 

Design feedback from @folletto 

For reference, here's the mockup of the component for both v1.0 and v1.1:

![sitepicker1](https://cloud.githubusercontent.com/assets/128826/11327000/a5d2eeec-91c4-11e5-9ac7-ac33f3ef68fc.png)

![sitepicker2](https://cloud.githubusercontent.com/assets/128826/11327002/b504d114-91c4-11e5-96c1-9002df5adf8b.png)

**Comment by v18** [comment]
@mtias: Dropping a note here that came out of a related discussion: we should also update the site picker to only show visible sites (as set in wp-content > My Blogs). Calypso already shows only visible sites in the sidebar site picker.

**Comment by mtias** [comment]
@v18 yes, this component is based on `SitesSelector` which is the shared component between the sidebar picker, and the new-post popover, which handles showing visible sites only (until you search), etc. It's one of the main reasons why all of our "site selection" UI pieces should be using this core component :)

**Comment by v18** [comment]
Thanks for the info! That's fantastic :)

**Comment by rickybanister** [comment]
@ebinnion does this seem like something easy enough to slot in for our clean up time?
