### ISSUE TITLE
Reader: Pay with PayPal Block, PayPal button does not render

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#45104]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/feeds/77116051/posts/2871659129
2. Observe that PayPal button does not appear

#### What I expected

When using the Pay with PayPal block I should see the PayPal button in the reader

#### What happened instead

I do not see the PayPal button

#### Browser / OS version

Chrome/OSX Lastest

#### Screenshot / Video

<img width="776" alt="Screen Shot 2020-08-21 at 10 09 09 AM" src="https://user-images.githubusercontent.com/6817400/90903900-94425580-e39c-11ea-8c98-d76ff07c06f6.png">

#### Context / Source

#manual-testing

**Comment by mmtr** [comment]
Closed by https://github.com/Automattic/jetpack/pull/17256
