### ISSUE TITLE
Reader: WordPress embeds are cropped when viewed in the Reader

### ISSUE THREAD

**Issue by aerych** [Automattic/wp-calypso#45105]
When viewing a post that contains Gutenberg WordPress embed blocks in the Calypso reader, the content can be cropped.

#### Steps to reproduce
1. Create a post on a test site and add some Gutenberg WordPress embed blocks.  ([This](https://wordpress.com/read/feeds/40377931/posts/2871709673) is my test post).  Link the blocks to WordPress posts that will generate preview cards. ([This is one](https://olagist.net/may-d-x-davido-lowo-lowo-video/) I randomly picked.)
2. View the post in the Calypso reader.
3. Compare the post in the reader vs the post on the site.  Notice that the bottom of the card is cropped. 

Depending on the card, this might look okay, or it might end up cropping the site logo beneath the card image. In any event the border around the card is cropped.

My expectation is the full card would be shown. 

#### Browser / OS version
Chrome, macOS 10.15.5

#### Screenshot / Video

<img width="1739" alt="Screen Shot 2020-08-21 at 10 02 16 AM" src="https://user-images.githubusercontent.com/1435271/90905844-635f2200-e396-11ea-91d7-06275ec953e3.png">

**Comment by davipontesblog** [comment]
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.
