### ISSUE TITLE
Reader: Social Icons don't display as expected for the 'Social Share' Block

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#45115]
**Web View**
<img width="862" alt="Test_Post_-_Watch_Musings" src="https://user-images.githubusercontent.com/1103209/90917967-e3df4c00-e3b1-11ea-90e5-0836ce0dc67f.png">

**Web Reader View**
<img width="804" alt="Test_Post_‹_Watch_Musings_‹_Reader_—_WordPress_com" src="https://user-images.githubusercontent.com/1103209/90918037-ff4a5700-e3b1-11ea-8d4d-0c905352c6f8.png">

It's not super severe, so not that high priority. Tested on Chrome on MacOS.

**Comment by davipontesblog** [comment]
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by davemart-in** [comment]
I suspect this was theme specific. I tested this with the Dara theme just now and was unable to replicate the issue.

<img width="342" alt="CleanShot 2023-02-06 at 16 33 53@2x" src="https://user-images.githubusercontent.com/5634774/217093310-7af43ff8-3814-4450-928d-a2262ec2347e.png">

Closing this one out for now, unless we see a repeat instance.
