### ISSUE TITLE
Facebook Embed Block Does not appear in Notifications Preview

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#45111]
#### Steps to reproduce

1. Have a site with notifications enabled
2. Make a post with Facebook Embed Block
3. Click notification to see preview
4. Observe no embed

#### What I expected

To see the embed or a link

#### What happened instead

The block does not render at all

#### Browser / OS version

OSX/Chrome latest

#### Screenshot / Video

<img width="400" alt="Screen Shot 2020-08-21 at 11 45 50 AM" src="https://user-images.githubusercontent.com/6817400/90911025-6104c400-e3a6-11ea-98db-417b1cb9bb38.png">

#### Context / Source

#manual-testing

**Comment by kwight** [comment]
These are now rendered as links:

<img width="463" alt="Screen Shot 2020-11-03 at 11 11 39 AM" src="https://user-images.githubusercontent.com/349751/98030114-637f9300-1dc5-11eb-8414-e851351363be.png">
