### ISSUE TITLE
Error when trying to execute the tests on Windows 10

### ISSUE THREAD

**Issue by zdravkov** [Automattic/wp-calypso#4511]
#### Steps to reproduce
1.run make test on fresh updated to Windows 10 machine

#### What I expected

run the tests
#### What happened instead

[error: Failed to exec test-client script](https://gist.github.com/zdravkov/fea9920abc57970d533a8e43e29e9a9f)
#### Browser / OS version

 Windows 10

**Comment by lancewillett** [comment]
Hi @zdravkov — thanks for your report here. Calypso isn't yet quite ready to work as-is on Windows, but we do have other options, see https://github.com/Automattic/wp-calypso/issues/592 and #2737. You can use something like [Calypso Bootstrap](https://github.com/Automattic/wp-calypso-bootstrap) in the meantime.

**Comment by gziolo** [comment]
> 2 info using npm@2.14.12
3 info using node@v4.3.1

We are using node 5.x and npm 3.x, so that could be also related.

**Comment by klimeryk** [comment]
FWIW, I think the issue is [here](https://github.com/Automattic/wp-calypso/blob/master/package.json#L126-L128):
```
"test-client": "NODE_ENV=test NODE_PATH=test:client TEST_ROOT=client test/runner.js"
```
On Windows, the path separator is `;`, not `:`. In the `Makefile` we take that into account, but not here.
