### ISSUE TITLE
Notifications: No quote indicator

### ISSUE THREAD

**Issue by elibud** [Automattic/wp-calypso#45120]
#### Steps to reproduce

1. Create a new blog post in a blog you are subscribed to receive notifications from.
2. Add a quote to the blog post.
3. Check your Notifications.

#### What I expected

To see a quote indicator on the notification.

#### What happened instead

Ther's no indication that the text is a quote.

#### Browser / OS version
Safari 13.1.2

#### Screenshot / Video

![Screen Shot 2020-08-21 at 15 10 17](https://user-images.githubusercontent.com/5558824/90921354-7686e780-e3c0-11ea-8d84-ddcfa4600e83.png)

**Comment by getdave** [comment]
Looking into this

* Developer Console - `/notifications/?http_envelope=1&fields=id%2Cnote_hash%2Ccontent&number=20`

**Comment by getdave** [comment]
@davemart-in I've been looking into this with @marekhrabe. We want to be clear on the task.

Is it:

1. Make quotes look like quotes in the Notification listing and detail (when you click on a Notification and it slides over to reveal more info) view?
2. Make quotes look like quotes in the Notification detail view _only_?

The listing is intentionally devoid of styling and HTML tags to avoid breaking the layout with images and other random HTML that could be in a post summary so this would break with convention if we go down that route.

**Comment by marekhrabe** [comment]
We have also check the behavior on mobile (it would be good to match it, I think) and on mobile the view in the list (small previews) is always plaintext without styling and only in the detail once you open it, you will see quote styles etc…

In this case my vote would be towards:

> 2. Make quotes look like quotes in the Notification detail view only?

**Comment by davemart-in** [comment]
@marekhrabe yes, it's option 2. The styling is only needed in the preview that slides out. The truncated list item on the right can remain unstyled.

**Comment by kwight** [comment]
Fixed by @blackjackkent in D49621-code and #45710 .

<img width="480" alt="Screen Shot 2020-09-30 at 2 54 25 PM" src="https://user-images.githubusercontent.com/349751/94743877-f0e64800-032c-11eb-9552-3a57b62cad7b.png">
