### ISSUE TITLE
Reader and comments - Layout-grid appears vertically instead of respecting layout

### ISSUE THREAD

**Issue by yaelirub** [Automattic/wp-calypso#45133]
#### Steps to reproduce

1. Starting at URL: https://yaelirub.com/2020/08/21/testing-blocks-is-so-much-fun/
1. Create a post with the block editor
2. Add a layout-grid block
3. Add items to the block 
4. Publish the post 
5. See the post in Reader 
6. The first 4 elements in the page are part of a layout grid and should appear horizontally 
7. See them appear vertically

#### What I expected
I expected the images and text to appear horizontally like how I created them and see them on my site and in preview

#### What happened instead
The images and text appear vertically everywhere 
### What I expected 
<img width="926" alt="Screen Shot 2020-08-21 at 3 24 42 PM" src="https://user-images.githubusercontent.com/1335657/90940775-d5e6f680-e3c4-11ea-9391-1d05e451e588.png">

### How it looks like in Reader
<img width="371" alt="Screen Shot 2020-08-21 at 1 15 06 PM" src="https://user-images.githubusercontent.com/1335657/90940795-ebf4b700-e3c4-11ea-9e82-f6f07c46a8df.png">

### How it looks like in comments 

<img width="678" alt="Screen Shot 2020-08-21 at 2 47 37 PM" src="https://user-images.githubusercontent.com/1335657/90941226-5d813500-e3c6-11ea-8064-df8e5d8e5a61.png">

**Comment by davipontesblog** [comment]
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
