### ISSUE TITLE
Video Block Does Not Appear Under Search Term "Video" When Adding a New Block

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#45140]
#### Steps to reproduce

1. Create a new page
2. Click the + to add a block
3. Search for Video
4. The Video Block does not appear. Instead, it gives options for Story, YouTube, Vimeo, Dailymotion, TikTok, VideoPress

#### What I expected
The Video Block to appear when searching for Video

#### What happened instead
The Video Block is difficult to find.

#### Browser / OS version
All
#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30731356/90963149-4431c480-e46a-11ea-9d5a-9cac8153834d.png)

#### Context / Source
#flowsharing #painpoint

**Comment by sirreal** [comment]
This is an example of a more general issue in #45136.

Closing as duplicate of #45136.
