### ISSUE TITLE
Reader: Single post view shows sidebar styling on refresh and direct visit

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#45150]
#### Steps to reproduce

1. On an account using a color scheme other than Classic Bright (I reproduced on Sunset and Sakura) open a single post URL such as https://wordpress.com/read/feeds/78476279/posts/2864254594
2. Note the sidebar background color appears to the left of the post content. This issue occurs when visiting a single post URL directly or when refreshing, but not when navigating from elsewhere in the Reader, such as the site's main feed ex. https://wordpress.com/read/feeds/78476279

Note: This issue may be present on the Classic Bright scheme as well, but since it uses a white sidebar it's not visually present, which is why I recommend testing with another scheme.

#### What I expected
The single post to be styled the same no matter how it's opened

#### What happened instead
The sidebar styling appears on the single post view when visited directly or refreshed.

#### Browser / OS version
OS X Chrome 83

#### Screenshot / Video
<img width="1367" alt="Screen Shot 2020-08-21 at 10 20 40 AM" src="https://user-images.githubusercontent.com/1900444/91044553-774b9380-e5e3-11ea-9f70-1f01b5020ae0.png">

#### Context / Source

#manual-testing, #user-report

**Comment by bluefuton** [comment]
Should be resolved by https://github.com/Automattic/wp-calypso/pull/45188.
