### ISSUE TITLE
Customizer: Edit links on default widgets in preview unresponsive

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#4515]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize/
2. Use a new site, or remove all widgets from the sidebar.
3. Apply any theme that always shows a sidebar on the front page (e.g. Twenty-Eleven, Forefront, Oxygen) 
4. Open the Customizer after applying the theme

#### What I expected
The Customizer will load a live preview of the site, including Edit buttons that can be used to edit certain features on the page. Clicking the Edit button should switch to the applicable tab in the Customizer menu.

The sidebar of the site should be showing the default widgets that appear on those sites if the user hasn't added their own widgets.

#### What happened instead
On the themes tested, the default widgets appeared, and also showed Edit buttons next to each widget, but those buttons were completely unresponsive. As the default widgets don't appear under the Widgets tab, clicking the buttons can't open the specific widgets for editing, but it doesn't even open the main widget tab in the Customizer.

#### Browser / OS version
Confirmed in Chrome, FF, Safari and Edge in Win10 and Mac OSX

Themes tested are Twenty-Eleven, Forefront, Scrollider Express, Crafty, Ascetica, Sight, Oxygen and Chateau.

#### Screenshot / Video
![default widgets in customizer](https://cloud.githubusercontent.com/assets/11873759/14263039/b3670004-fab8-11e5-90c8-cdd7063020fb.gif)

**Comment by lancewillett** [comment]
Thanks for the report — it's a known issue with default widgets.

(It's not specific to Calypso, though — any Customizer use on WP.com.)

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue as written.

**Comment by lancewillett** [comment]
Moved to internal bug tracker since not Calypso specific.
