### ISSUE TITLE
Billing: Add site-level management

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#45181]
ref: pbOQVh-sc-p2

- Tabs: purchases, billing history
- Add controller for site view
- Add link to My Sites > Plans > Billing and Payments

Questions:
- what endpoints are used?
- where is the data stored on the front-end?

**Comment by sirbrillig** [comment]
Remaining places that I can find in payment management components (outside of navigation) that have hard-coded account-level routes and will need to be updated:

- client/me/purchases/upcoming-renewals/upcoming-renewals-dialog.tsx (managePurchase)
- client/me/purchases/payment/edit-card-details/index.jsx (managePurchase, purchasesRoot)
- client/me/purchases/remove-purchase/index.jsx (purchasesRoot)
- client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx (getEditCardDetailsPath)
- client/me/purchases/manage-purchase/index.jsx (getEditCardDetailsPath)
- client/me/purchases/manage-purchase/purchase-meta.jsx (getEditCardDetailsPath)

**Comment by fditrapani** [comment]
I'm working on the upcoming renewals modal. I almost have a PR ready to go.

**Comment by fditrapani** [comment]
I just created a PR for the upcoming renewals dialog here: https://github.com/Automattic/wp-calypso/issues/45181

**Comment by nbloomf** [comment]
Working on the getEditCardDetailsPath instances in #46069

**Comment by fditrapani** [comment]
I created a PR for `client/me/purchases/remove-purchase/index.jsx (purchasesRoot)` but I can't get my environment working to test it properly. I'm trying to remove a plan that has passed the 30 day refund rate but my screen hangs indefinitely. This happens in production and in my PR. @sirbrillig @nbloomf or @michaeldcain can either of you confirm if you're getting the same behaviour in production first and then on this PR if it works? https://github.com/Automattic/wp-calypso/pull/46072

**Comment by michaeldcain** [comment]
> I'm trying to remove a plan that has passed the 30 day refund rate but my screen hangs indefinitely.

I fixed the dialog close in 15b0523

**Comment by fditrapani** [comment]
Awesome! Thanks @michaeldcain. I wonder how long it's been broken.

**Comment by michaeldcain** [comment]
> I wonder how long it's been broken.

A long time. The bug (and console error) was when product removal failed (so not too frequently). On success, the modal stays open (without any sort of progress indicator) until the request completes and the user is redirected to the purchase list. This is not ideal because the removal takes a long time. We should try to troubleshoot the reason for the slow request when we redesign these pages, or at minimum have some sort of progress indicator.

**Comment by fditrapani** [comment]
We should definitely clean this up. The progress indicator would be a good start for sure.
