### ISSUE TITLE
Checkout: Add "empty cart" view

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#45182]
This would be displayed when the cart is empty but there is no redirect for some reason.

For example, if there is a cart error message and the cart is empty, the redirect will not happen. Currently this means the user will see the (dismissible) error message but the page will remain in a "loading" state forever.

**Comment by fditrapani** [comment]
Here's something we can start out with:

![image](https://user-images.githubusercontent.com/6981253/91889142-5b876380-ec5b-11ea-844a-11479ab5dc1b.png)

**Comment by fditrapani** [comment]
It would be good to know how often this happens and when we implement it, have tracking on the button as well.
