### ISSUE TITLE
Typography: smaller font size may be needed

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#45194]
There are two usages of `font-size: 10px` in Gutenboarding at the moment:
- [PlansGrid](https://github.com/Automattic/wp-calypso/pull/44934/files#diff-725600c2a3713e0382242f9507308375R215)
- [Onboarding -> Design selector](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/onboarding-block/design-selector/style.scss#L135)

So i'd like to propose an update for the `scales/font-size` rule and [typography variables](https://github.com/Automattic/wp-calypso/blob/master/packages/typography/styles/variables.scss). 

cc: @sixhours

**Comment by simison** [comment]
I think we should update designs instead to adopt next closest font size if possible. Cc @olaolusoga

**Comment by sixhours** [comment]
👋 Thanks for the ping!

Do you have visual examples of the copy in action? 10px is usually very tiny, and I think we should avoid tiny fonts for better accessibility and readability.

If we absolutely can't make the font size larger (I think 12px is the next closest size) then adding exceptions (as you've done) is the way to go, rather than adding a tiny font size to the scale, which would encourage its use.

But I'm open to your thoughts!

**Comment by razvanpapadopol** [comment]
Here are screenshots with the exceptions:
<img width="800" alt="Screenshot 2020-10-27 at 17 09 32" src="https://user-images.githubusercontent.com/14192054/97321233-53bcf780-1877-11eb-879b-428e1cd52f5d.png">

<img width="800" alt="Screenshot 2020-10-27 at 17 05 28" src="https://user-images.githubusercontent.com/14192054/97321242-57507e80-1877-11eb-91f2-0118ec020fe1.png">

I agree with keeping them as exceptions or even extracting to a `Tag` component which could become the only exception.

@ollierozdarz what do you think?

**Comment by ollierozdarz** [comment]
@razvanpapadopol I'm fine with either solution. I think 10px when in **uppercase** looks better in these type of tag/label  scenarios, but it's quite a fine detail, so not worth the extra work if it's a pain.

**Comment by razvanpapadopol** [comment]
Ok, so there is a good reason to keep them as exceptions. Thanks for your input! 
Closing this issue for now.
