### ISSUE TITLE
Gutenboarding: premium theme badge and its tooltip have mismatching background colors

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#45217]
#### Steps to reproduce

1. Starting at URL: `localhost:3000/new`
2. Follow steps until the design selector screen
3. Hover over the "PREMIUM" badge with the cursor
4. Tooltip appears

#### What I expected

The premium badge and the tooltip should have the same background color (Gray 80)

#### What happened instead

The tooltip has a black background color

#### Browser / OS version

Chrome / MacOS (but the issue affects all browsers)

#### Screenshot / Video

<img width="312" alt="Screenshot 2020-08-25 at 15 11 46" src="https://user-images.githubusercontent.com/1083581/91179063-4f912400-e6e6-11ea-8068-e82f638a15f6.png">

#### Context / Source

Bug introduced by https://github.com/Automattic/wp-calypso/pull/45151

The badge's background color was changed to reflect design changes, but the tooltip was not updated.

**Comment by Aurorum** [comment]
PR for this issue in #45228 :)
