### ISSUE TITLE
Checkout: Wrap analytics recording in try/catch

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#45226]
The function returned by `createAnalyticsEventHandler()` in new checkout is used by many parts of checkout, but the most critical may be error reporting where it logs fatal errors to logstash so we can be notified of them.

Unfortunately, there are occasionally bugs introduced into this rather large function and if an error occurs there, it will not be reported.

I think it would be a good idea to wrap all of the function body in a try/catch where the `catch` block did a hopefully very simple report to logstash of its own.

**Comment by PavithraCP** [comment]
Hello, I've raised a PR for this https://github.com/Automattic/wp-calypso/pull/45241. Please lmk if this needs any changes, Thanks.
