### ISSUE TITLE
Gutenboarding: experimental features are disabled after site creation

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#45273]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/new?latest
2. Go through the flow making sure the experimental features are there and create a site
3. Navigate once again to https://wordpress.com/new

#### What I expected
- Going back to site creation flow after creating a site, `isExperimental` flag on the store should be persisted.

Probably just removing the [reset for isExperimental]( https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/stores/onboard/reducer.ts#L84-L86) should be a good fix. So as long as the user is in the same browser, unless localStorage is cleared/expired, they should get the experimental version. The same mechanism is used also for A/B test variant.

**Comment by yansern** [comment]
IIRC the `isExperimental` flag was that it was used for enabling feature picker which is now enabled for all.
So this PR just cleans up the `isExperimental` flag. https://github.com/Automattic/wp-calypso/pull/50526

**Comment by razvanpapadopol** [comment]
We were using `?latest` query param when linking to Gutenboarding to prevent importing `lib/abtest` from Calypso to run experiments but now I believe we can import exPlat experiment function from a package and run as many experiments as needed 💃

**Comment by yansern** [comment]
Thanks for the context!

**Comment by yansern** [comment]
PR https://github.com/Automattic/wp-calypso/pull/50526 is merged.
