### ISSUE TITLE
Pay With PayPal: Paypal Buttons Missing

### ISSUE THREAD

**Issue by sdixon194** [Automattic/wp-calypso#45279]
The buttons to pay with the Pay with PayPal button appear missing on this site. 

#### Steps to reproduce

- Add a Pay with PayPal block to the site. 

#### What I expected

- To see the option to pay, like this:

![Screen Shot on 2020-08-28 at 13:40:56](https://user-images.githubusercontent.com/33553323/91599323-1ea62e80-e934-11ea-8958-36dbd29ecaea.png)

#### What happened instead

There's no option to pay. 

#### Screenshot / Video

![Screen Shot on 2020-08-28 at 13:39:18](https://user-images.githubusercontent.com/33553323/91599175-e30b6480-e933-11ea-8e9f-df4e7011e0df.png)

#### Context / Source

Tried deactivating all plugins, there's no custom CSS. Button appears fine on a WordPress.com test site with plugins installed using the same theme. 

More discussion here: p1598633309119700-slack-earn

**Comment by Supersketch** [comment]
Thank you for writing up my PayPal scenario. 👌

**Comment by kwight** [comment]
Noting that I can't replicate with a new Atomic ephemeral site – it's likely something site-specific to this user.

**Comment by lakellie** [comment]
Thanks for testing this one @kwight - I landed on the ticket and did some testing and you are correct that it's site-specific. It's an AMP conflict. I'll follow up with them and close this out :)
