### ISSUE TITLE
Posts / Pages: search does not clear when switching sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#453]
Originally raised by @rralian:

If you switch sites while you have search open, the search field does not get cleared. However, the search is no longer active either. Either we should clear search upon switching sites or we should at least honor the search string when we switch to a new site. I'm leaning towards honoring the search string, as I can see a valid case of wanting to search for certain strings across several sites. i.e., "Hmmm... it's not in this site, maybe I posted that to this site?"

More feedback on this from @lancewillett 
1. If you switch _back_ to a previous a blog post search, the search string is still visible but not active, as Bob reported.
2. If you switch to a new site (not previously viewed) — you will see a cleared search string and a closed search box.

Steps taken (testing with Safari 8.0.8 on OS 10.10.5):
1. Go to My Sites
2. Click on a site and click "Blog Posts"
3. Click the search icon at top right to open search bar, type in "test", and hit Enter to search
4. Click on "Switch Site" and pick a different site
5. Click "Blog Posts" and note the search field is closed.
6. Click the search icon at top right to open search bar, and notice the field is now empty. No "test" string in it.

**Comment by lancewillett** [comment]
Possibly related #1403

**Comment by hoverduck** [comment]
14Apr16 Bug Scrub

Confirmed this is still an issue.  Search for a post, switch sites to a 'recently open' site at the top of the Sites list, and the search field is still populated but not applied to the list of displayed posts.  If the switched-to site is not in the 'recently open' section then the search is cleared.

**Comment by lancewillett** [comment]
Still happening — same steps as above.

To fix, could we always have search filter results if the search input field isn't empty?

**Comment by lancewillett** [comment]
#1112 has related information on the technical side of a possible fix for this — global search state.

**Comment by hoverduck** [comment]
#bug-scrub

This is still an issue, but with a different signature.  Now when switching between sites the search field remains open, but is unpopulated:

![wp-calypso-453](https://cloud.githubusercontent.com/assets/7233112/19451642/d1c4c89e-947b-11e6-8fdf-0305a9c6c0fb.gif)

**Comment by rachelmcr** [comment]
#bug-scrub

This is still an issue. In my testing, the search field never clears. Instead, the behavior is the same each time you switch sites: Search for a post, switch sites to another site, and the search field is still populated but not applied to the list of displayed posts. Each time you switch back or to another site you see the same behavior.

**Comment by alisterscott** [comment]
Confirmed still an issue

**Comment by cathymcbride** [comment]
Closing...
