### ISSUE TITLE
Payments: 10% fee shown on eCommerce sites

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#45304]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/earn/payments/example.wordpress.com
2. Earnings box shows 10% fee

#### What I expected

To see the correct 0% fee as shown in our [support doc](https://wordpress.com/support/wordpress-editor/blocks/payments/#related-fees). I have not completed a payment so I am unclear if the actual fee charged is incorrect or just what we show on this page.

#### What happened instead

An incorrect 10% fee is shown. 

#### Browser / OS version

Mac OSX 10, Chrome 83.0.4103.61

#### Screenshot / Video

<img width="1070" alt="Screen Shot 2020-08-31 at 1 22 40 PM" src="https://user-images.githubusercontent.com/1900444/91748109-6c69a380-eb8d-11ea-8096-49d471e0293e.png">

#### Context / Source

#3268622-zen

**Comment by lauac** [comment]
This is definitely a bug. Thanks for reporting, @kriskarkoski. Serenity is on it.

**Comment by kwight** [comment]
This unearthed an issue being handled in #45373 , but it looks like that incorrect 10% commission rate is also coming from the API – @krymson24 can you look into the server-side part please?

**Comment by kwight** [comment]
`QueryMembershipEarnings` triggers an API call to `https://public-api.wordpress.com/wpcom/v2/sites/:site/memberships/earnings`, the response of which should show no commission or an ecommerce site. This is what I see coming back:

<img width="974" alt="Screen Shot 2020-09-03 at 3 21 58 PM" src="https://user-images.githubusercontent.com/349751/92179338-5829de80-edf9-11ea-9990-5628f1dc0e27.png">
