### ISSUE TITLE
My Home: Update first-week text for Stats at a glance card.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#45327]
**Current Status:**

Text that reads a bit like we're unaware that the site has just been created only a few moments ago and hasn't been around yet for a week …

![image](https://user-images.githubusercontent.com/545779/91865281-d68a5300-ec36-11ea-9ca7-7e2412eb6808.png)

**I expected:**

Something more like this …

![image](https://user-images.githubusercontent.com/545779/91865403-fa4d9900-ec36-11ea-9caf-2986f2406d19.png)

… until the one of two conditions has been met:

1. The first week has passed.
2. The site gets traffic.

**Comment by Aurorum** [comment]
PR for this issue in #45352. :)
