### ISSUE TITLE
Gutenberg 8.9.0-rc.1: Menu shows up in wp-admin, Site Editor menu shows up twice

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#45322]
#### Steps to reproduce

On sites running Gutenberg 8.9.0-rc.1 (currently on WP.com sites stickered with the `gutenberg-edge` sticker), the Gutenberg menu item is no longer hidden in wp-admin. Furthermore, if the site is also stickered with the `core-site-editor-enabled` sticker, the "Site Editor (beta)" menu item shows up twice (albeit with different icons).

![image (10)](https://user-images.githubusercontent.com/96308/91849296-216a9180-ec5c-11ea-8b32-33e5f9cfc54d.png)

#### What I expected

The Gutenberg menu item not to be present. Furthermore, on sites that also have the `core-site-editor-enabled` sticker, I expect the "Site Editor (beta)" menu item to show up only once.

#### Context

Some context here: https://github.com/Automattic/wp-calypso/pull/41179

**Comment by ockham** [comment]
Likely reason: Priority of this action was recently changed: https://github.com/WordPress/gutenberg/pull/24843/files#diff-26f7754641e020003bf92e16ac862f50R110

**Comment by ockham** [comment]
Fix: D48889-code

**Comment by sirreal** [comment]
Maybe fixed by this PR? https://github.com/Automattic/wp-calypso/pull/45328

**Comment by ockham** [comment]
I think that #45328 doesn't remove the Gutenberg menu item.

**Comment by ockham** [comment]
Closed by D48889-code.
