### ISSUE TITLE
Plugins: Akismet featured as uninstalled plugin when already installed and Active

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#45367]
It was surprising to see, on a free site, Akismet Anti-Spam as a featured Plugin …

![image](https://user-images.githubusercontent.com/545779/92024501-e59aff00-ed23-11ea-8d7a-20e11010b651.png)

When it's an already-installed featured plugin with a different name …

![image](https://user-images.githubusercontent.com/545779/92024582-fc415600-ed23-11ea-9963-570161f209e9.png)

(And to then be able to upgrade and install it.)

Perhaps could be featured still, with it's correct name and status?

**Comment by ianstewart** [comment]
The issue with the different names has been corrected here. I'll update the title to remove that.

Looks like the status issue remains. Featured in the popular list without indicating that its pre-installed …

![image](https://user-images.githubusercontent.com/545779/109877586-d0524f00-7c38-11eb-99bf-9448970fbc39.png)

And prompt to upgrade that doesn't note that it's installed …

![image](https://user-images.githubusercontent.com/545779/109877741-00015700-7c39-11eb-9d5a-fe64441244e1.png)

I no longer see any "Installed" labels now so unsure if that was a change of direction or a regression.

**Comment by allilevine** [comment]
Akismet now shows up as installed and active for Atomic, upgraded sites:
<img width="522" alt="Screen Shot 2022-04-19 at 12 33 32 PM" src="https://user-images.githubusercontent.com/1689238/164052229-7b83d8b2-e000-4db8-9299-ab52e17e166e.png">

For Simple sites it says free with upgrade:
<img width="533" alt="Screen Shot 2022-04-19 at 12 35 13 PM" src="https://user-images.githubusercontent.com/1689238/164052666-0c5b94b7-e0dd-471c-a7a0-02b89013a9fb.png">
