### ISSUE TITLE
Sign-in with Google when liking posts is not taking effect

### ISSUE THREAD

**Issue by david-szabo97** [Automattic/wp-calypso#45376]
#### Description
**This only seems to happen in Google Chrome so far**
Tested on Win10 Firefox, Win10 Edge, those are working fine.

#### Steps to reproduce

0. Make sure you are logged out
1. Go to this page: https://dtest415854240.wordpress.com/2020/09/03/example-post-3/
2. Click the Post Like button
3. On the sign-in page, click the Sign in with Google option
4. Proceed to sign in with Google
5. Sign-in window closes but like is not added
6. Try clicking on the like button again
7. Window comes up and closes immediately
8. Still no like on the post

#### What I expected
After signing in with Google post like should take effect.

#### Browser / OS version
Google Chrome latest
Windows 10

#### Screenshot / Video
![wp-google-sign-in-post-like-bug (1)](https://user-images.githubusercontent.com/2256104/92104337-7388ef80-ede1-11ea-8d45-4095878af23c.gif)

#### Context / Source

#user-report

**Comment by alshakero** [comment]
It seems that signing in with username and password also doesn't work.

**Comment by alshakero** [comment]
PR in D49592-code

**Comment by alshakero** [comment]
Closing as fixed! code-D49592
