### ISSUE TITLE
Preview for instagram widget text is cut off and unreadable

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#45377]
#### Steps to reproduce the issue

1. Go to https://wordpress.com/marketing/connections/<your site>
2. Click on Facebook - note preview
3. Click on Instagram - note preview

#### What I expected

Clear previews, with readable text

#### What happened instead
preview is not obviously instagram, and the text in the left hand portion of the preview is cut off
(chrome)

**Screenshots**
![image](https://user-images.githubusercontent.com/16654218/92020663-7ecb1500-ed26-11ea-9c7d-919a2168729e.png)

**Comment by obenland** [comment]
It looks like it's meant to be cut off: https://wordpress.com/calypso/images/sharing/connections-instagram.png

Introduced in #44809. @sixhours can you confirm it's intentional?

**Comment by sixhours** [comment]
👋 Yes, as far as I remember that's meant to be a screenshot of the widget on a site (which will look different depending on the theme), not a live preview. I could see a case for removing the post text in a future PR to reduce confusion, but the image is not meant to be full size to save space.

**Comment by obenland** [comment]
Closing as this seems to be intentional
