### ISSUE TITLE
Payments management: add payments related support links

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#45383]
For users that have made a purchase, add a link to [Managing purchases, renewals, and cancelations](https://wordpress.com/support/manage-purchases/) the suggested InlineHelp links on the following pages:

- plans
- my plan
- settings
- support
- customer home
- any purchase-related screens

ref: pbOQVh-mX-p2#support

**Comment by Aurorum** [comment]
PR for this issue in #45408. :)

**Comment by sirbrillig** [comment]
It's hard to tell from the description, but I think these are the routes that this is referring to. Please correct me if I'm wrong.

- /plans/:siteId
- /plans/my-plan/:siteId
- /settings/:siteId
- /help
- /home/:siteId
- /me/purchases/:siteId/:receiptId

**Comment by Aurorum** [comment]
My Home (`/home`) doesn't appear to include the Inline Help button, so I just excluded it from the PR. Let me know if that should change. :)

**Comment by sirbrillig** [comment]
@fditrapani can you confirm that the above routes are the ones you were referring to?

**Comment by fditrapani** [comment]
Thanks for pulling that list together @sirbrillig. Those are correct, in addition to that, I would also include:

- /me/purchases, and
- /domains/manage/:siteid
- /domains/manage
