### ISSUE TITLE
Gutenberg: can't return to Calypso after publishing via mobile web

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#45381]
#### Steps to reproduce

1. write a new post using Firefox on iOS (Safari might also work the same) and publish it
2. notice that there's no button to go back to the posts list / Calypso

#### What I expected

I expected there to be a way for me to return to Calypso to look at my posts list or stats, etc. 

#### What happened instead

There was no way to go back without navigating with the back buttons (feels error-prone) or closing the tab and typing in the URL anew. 

#### Browser / OS version

Firefox on latest iOS. 

#### Screenshot / Video

![IMG_1860](https://user-images.githubusercontent.com/23619/92122498-c8d1fa80-edfb-11ea-9e9c-b5ed00e5fbb0.jpg)

**Comment by cathymcbride** [comment]
I see the following screen after I publish on both Safari and Firefox Mobile. And I'm finding the back button reliably takes me back to posts. However, perhaps something should be added to this screen? Design, what do you think?

![image](https://user-images.githubusercontent.com/16654218/92128065-fbfe9480-edcf-11ea-8e92-6baaa8cb8d1b.png)

**Comment by lsinger** [comment]
@cathymcbride ah, I might have closed that modal without thinking too much, as it felt like just a confirmation that I don't need any longer. 

I believe that back buttons work fine, but that doesn't change that I don't trust them to work, which makes me avoid them — at least in anything that doesn't feel like a proper webpage, or in situations where I submitted information like payment forms, contact forms, or, like in this case, a new blog post. 🙂 I wonder if that's a common thing for people or a developer-specific anxiety.

**Comment by cathymcbride** [comment]
Since this hasn't come up since, I'm going to close. Please reopen if you feel strongly this needs to be fixed!
