### ISSUE TITLE
Editor: Scheduled post times change after saving. 

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#45382]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/block-editor/post/
2. attempt to schedule post from the post calendar
3. save time, confirm post is scheduled. 
4. check on post later in scheduled tab: https://wordpress.com/posts/scheduled

#### What I expected
Scheduled time, once set should not change.

#### What happened instead

Several hours later post scheduled time shifted back an hour.  does not appear to happen consistently as other posts were unaffected. Can confirm Site timezone is set correctly.

#### Browser / OS version
Impacted user, is using Safari Version 13.1.2 (15609.3.5.1.3), on a 2020 MacBook Air macOS 10.15.6
Confirmed this occurs when using calendar view in primary WordPress.com editor, user does not use wp-admin to schedule or manage posts. 

#### Screenshot / Video
![screen-shot-2020-09-03-at-08 55 13-e1599144443646](https://user-images.githubusercontent.com/33329175/92131446-03c03800-edd4-11ea-83ba-c16fd15c6522.png)

#### Context / Source
#User-report #20066712-hc I was unable to reproduce in testing on Windows 10, Firefox on a test site.

**Comment by nagpai** [comment]
One more user report 
#24575580-hc

User seeing a different date in `Publish` in post editor and on the list of scheduled posts for the same post. 

Likely related issues 
#46000
#41726

**Comment by synora** [comment]
The issue has gone stale and I'm unable to reproduce this issue. I'll close it for now but it can be reopened if it occurs again.
