### ISSUE TITLE
Classic Block: Add option to caption images

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#45389]
## Steps to reproduce

1. Start by using a simple site and create a new page or blog post
2. Add the Classic editor block to your post
3. Use the "Add media" button within the classic block to add an image
4. Note that you have no option to add a caption upon adding the image or after adding the image, captions also do not appear if they've been added to the image directly from the Media page

I do want to note that we do have an option to caption images using these other methods:
* An Atomic site, this can be done when using the Classic block in the block editor or in WP Admin
* A simple site in WP Admin
* The image block in the block editor

#### What I expected
The option to add a caption to an image should be available, especially since we offer it elsewhere in the block editor (such as with the image block) and within the classic editor in WP Admin.

#### What happened instead
No option to add captions to the image within the editor, and captions added to an image from the Media page in Calypso don't appear on the actual page/post.

#### Context / Source
#user-report

May or may not be related to:
https://github.com/Automattic/wp-calypso/issues/29412

**Comment by Gilmoursa** [comment]
I can add an image inside a classic block following these steps:

1 - add a classic block to a simple site post 
2 - select the option to "add media"
3 - select an image
4 - click on 'edit'
5 - fill in the "caption" field
6 - click on 'insert'
