### ISSUE TITLE
Nav Unification: Update Masterbar/Toolbar

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#45393]
Visual unification of Calypso's Masterbar and wp-admin's toolbar. Let's update sizes and colors to reflect the way the toolbar looks in wp-admin.

#### Resources
* Masterbar styles: https://github.com/Automattic/wp-calypso/blob/373e83ea618f51b9b60c8e1b0685f87293a634f6/client/layout/masterbar/style.scss

See 211-gh-dotcom-manage

**Comment by cpapazoglou** [comment]
I have created a feature flag https://github.com/Automattic/wp-calypso/pull/45452 which by default is enabled only in development. We can force enable it by appending `?flags=nav-unification` in the URL

Just a heads up, it seems we have 2 masterbars
https://github.com/Automattic/wp-calypso/blob/e274a99df8de65a90625e1e28c4a744f020ef32a/client/layout/index.jsx#L122

**Comment by frontdevde** [comment]
@sfougnier @davemart-in 
I can't find links to the design exploration files anywhere (outside the couple of screens on the WHY post). For now, unless advised otherwise, I'll use wp-admin as the source of truth for sizes and colors for this issue.

**Comment by sfougnier** [comment]
> 1.) Before I fine tune every pixel of the spacing, I wanted to double check whether we want the masterbar in Calypso to 1:1 match the current state of the masterbar in wp-admin? Do we make all adjustments just to the Calypso side or is there anything that needs changing on the wp-admin side as well?

> 2.) What do we want the new active state for masterbar items to be in Calypso? When clicking the notification bell in wp-admin, the background is white and the color dark grey. I’m not sure this works well in Calypso given that My Sites is always active (see picture in PR or live in calypso.live)?

It's still being worked through but currently, the masterbar maintains a height of 32px, the background color #101517, and the active states to be #23282D. This is the latest [exploration](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=182%3A2919). 

<img width="1351" alt="1390" src="https://user-images.githubusercontent.com/67021691/92525612-2a2a0d00-f1f2-11ea-8f85-bb886f826d60.png">

> 3.) In Calypso the My Sites link is active while in wp-admin it is not. While it makes sense now, it will feel inconsistent once the bar looks visually the same in both environments. Do we leave it that way?

Good question. I think we should make this treatment consistent with the active state in the screenshot above.

cc @lcollette

**Comment by cpapazoglou** [comment]
👋 @sfougnier! Here [exploration](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=182%3A2919) it seems that we have made the sidebar wider than the wp-admin. Is that on purpose? In that case, the two interfaces will be different visually, except only if we are expected to make changes to the wp-admin itself which is something that it is not clear now.

> Good question. I think we should make this treatment consistent with the active state in the screenshot above.

Adds to my confusion above.

**Comment by frontdevde** [comment]
> It's still being worked through

Not ideal given that we're already supposed to be working on this.

> but currently, the masterbar maintains a height of 32px, the background color #101517, and the active states to be #23282D. This is the latest exploration.

The current background color in wp-admin is #23282d and the active state is #ffffff. Can you confirm that the intention of design is to make changes on the wp-admin side as well and not just Calypso?

> Good question. I think we should make this treatment consistent with the active state in the screenshot above.

What I hear you saying is make the `My Sites` link active in wp-calypso, is that correct?

**Comment by frontdevde** [comment]
Current work-in-progress state in Calypso:
<img width="1391" alt="Screenshot 2020-09-09 at 14 27 10" src="https://user-images.githubusercontent.com/1562646/92598091-9cf5bf80-f2a8-11ea-8dd5-85d2cbd1eeda.png">

**Comment by frontdevde** [comment]
@sfougnier Thanks for getting back to us!

Are there any exploration screens I can look at for mobile?

This is what the navigation looks like in wp-admin and the current work-in-progress:

|wp-admin|WIP in Calypso|
|-|-|
|<img width="321" alt="Screenshot 2020-09-09 at 16 29 50" src="https://user-images.githubusercontent.com/1562646/92612366-18ac3800-f2ba-11ea-98fa-dc7dfa9a10dc.png">|<img width="321" alt="Screenshot 2020-09-09 at 16 29 37" src="https://user-images.githubusercontent.com/1562646/92612531-409b9b80-f2ba-11ea-88f9-82b25e035dba.png">|

Questions:
a) The spacing on wp-admin in production looks off. I assume we wouldn't want to replicate that in Calypso. What should the spacing look like?
b) The mobile navigation works differently in wp-admin where we currently don't have to account for site icon and title. wp-admin on the other hand has additional option dropdowns at the top. How do we plan to merge the two?

**Comment by obenland** [comment]
> the idea would be that we would maintain that 200px within the wp-admin screens as well.

That is already part of D49204-code.

@sfougnier Can you help me understand what the active state for "My Sites" in wp-admin should look like?

**Comment by sfougnier** [comment]
> Are there any exploration screens I can look at for mobile?

Yes, I have some options [here](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=225%3A193). I was unaware of the way the hamburger icon is currently being implemented within the Calypso masterbar in wp-admin. I understand the need to retain the logo, but the fact that it becomes the only non-actionable icon in the bar is odd. I'm curious if we can find the best of both worlds with a solution like this? 

<img width="961" alt="Screen Shot 2020-09-09 at 6 05 36 PM" src="https://user-images.githubusercontent.com/67021691/92659900-45b31780-f2c7-11ea-9b33-a6488f02411e.png">

> Can you help me understand what the active state for "My Sites" in wp-admin should look like?

Within wp-admin, the active state would appear consistent with how it looks in Calypso. The background color of the masterbar is #101517, and the active state is #23282D to match the sidebar.

<img width="1351" alt="1389" src="https://user-images.githubusercontent.com/67021691/92660030-9b87bf80-f2c7-11ea-95ed-de17c39b1fbb.png">

**Comment by frontdevde** [comment]
Current WIP state of Calypso compared to wp-admin (in code-D49342):

![Masterbar](https://user-images.githubusercontent.com/1562646/92713109-da1a8a00-f35a-11ea-8039-9fb36ea2b0e1.gif)
