### ISSUE TITLE
Pages: Create pseudo Page in UI for "Blog"

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#454]
Originally raised by @meremagee 
- when a new site is created on WordPress.com, create a Page and call it Blog. 
- Set "Blog" page as the posts page. 
- If the user doesn’t create a new page and designate it as the homepage, the Blog page is set as the homepage. 
- Display Blog page in the Pages UI.
- Can be non-editable for most intents and purposes, perhaps with just the option to "set as homepage"

_I recognize this isn't how WordPress as a blog index by default works on a technical level. From a usability perspective, for people not intimately familiar with WordPress software (a large portion of new users one would hope), navigating around the invisible blog page requires a lot of work and patience. Abstracting this complexity and letting the dashboard UI represent what people see on their sites would make site creation more approachable to a non WordPress expert yet wouldn't necessarily confuse a WP pro._

**Comment by folletto** [comment]
This requires rework / redesign on the Pages section as a whole, I don't think it can be tackled in isolation. But the concept within this request — making that a "special" page — is more than sound. :)

**Comment by lancewillett** [comment]
Closing as this is working now — improvements will be in other pulls & issues.

<img width="855" alt="screen shot 2017-03-03 at 12 41 27" src="https://cloud.githubusercontent.com/assets/66797/23566358/bcc74cc4-000e-11e7-8de8-5fda87187448.png">
