### ISSUE TITLE
Custom HTML Blocks/Shortcode Blocks Can't Be Aligned

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#45412]
#### Steps to reproduce
User report, so this is the trouble they're having. 
1. Create a custom HTML Block.
2. Embed a Getty image into it https://wordpress.com/support/images/getty-images/#embedding-an-image-with-an-embed-code
3. It then converts to a shortcode that cannot be aligned. It's default left aligned.
4. Adding it to a shortcode block doesn't help, since it also can't be aligned.
5. The only workaround I could think of would be Group Blocks and a CSS Class for each instance, which the user did not want to do.

#### What I expected
Some sort of alignment options for the image.
#### What happened instead
The Getty shortcode added image can't be aligned in any way. They're stuck aligned left. User reports that aligning them was possible in the Classic Editor. Due to the deprecation on .com, they're not happy.
#### Browser / OS version
All
#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30731356/92272115-d2ac3a00-ee9d-11ea-823e-95270ab7e970.png)

#### Context / Source
#stresscase #painpoint #user-report

**Comment by Aurorum** [comment]
> The only workaround I could think of would be Group Blocks and a CSS Class for each instance, which the user did not want to do.

It's not ideal, but aligning the shortcode after inserting it with the Classic Block should work.

<img width="977" alt="Screenshot 2020-09-04 at 19 37 27" src="https://user-images.githubusercontent.com/43215253/92274952-15920000-eee6-11ea-9eca-14e47b48e2bc.png">

**Comment by yansern** [comment]
If we're going to introduce an `align` property to the shortcode, e.g. `[getty align="center"]`, this needs to be done in:
`wp-content/mu-plugins/shortcodes/getty.php` on wpcom under `wpcom_shortcodereverse_getty()` function.

I feel that @Aurorum's solution is more elegant and doesn't require any further intervention on our end.

**Comment by p-jackson** [comment]
I think centring the shortcode with the Classic Block is the right approach here. I think it makes sense given the user was previously aligning using the classic editor.
