### ISSUE TITLE
Reader: styling - vertical alignment issues for buttons on FF

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#4541]
Button styling is off in FF for https://wordpress.com/following/edit

Firefox:
![](https://cloudup.com/c2K2c9Cl3Sr+)

Chrome:
![](https://cloudup.com/cCD-hKm-M8m+)

**Comment by lancewillett** [comment]
Good find! This type of thing should probably be avoidid by a) using consistent components (see https://wpcalypso.wordpress.com/devdocs/design, Dropdown and choose "Compact Buttons" b) checking DevDocs design continually across browser versions.

**Comment by lancewillett** [comment]
Still happening in Firefox, could be something with flex layout in CSS? CC @mtias 

<img width="805" alt="screen shot 2016-04-19 at 10 03 25" src="https://cloud.githubusercontent.com/assets/66797/14648224/0c2bda9e-0616-11e6-9892-642cb0636965.png">

**Comment by lancewillett** [comment]
Saw this again today when troubleshooting #5347.

**Comment by jancavan** [comment]
This is fixed in: https://github.com/Automattic/wp-calypso/pull/8150
