### ISSUE TITLE
Coming soon: settings page

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#45425]
As a use I should be able to switch coming soon mode on and off in my site settings.

Since sites are "public" in Coming Soon, if the site is marked as private we should switch to public (but with search engine indexing disabled) if the user toggles Coming Soon mode.

From the settings section we **could** provide a  link to the coming soon page (to edit) (?)

**Comment by lsl** [comment]
cross linking / D45700-code / https://github.com/Automattic/wp-calypso/pull/45167

**Comment by lsl** [comment]
Replace #45167 with:

- #45606 - calypso changes
- #45581 - etk changes
- #45604 - settings api filters

**Comment by lsl** [comment]
Bunch of change ups on this code: 

- Settings page changes: Mostly implemented in #46034 
- But changing again in #46119

A lot of the og work is now in #45896 that will likely need to be broken down further.

**Comment by ramonjd** [comment]
Merged
