### ISSUE TITLE
Reader: Document process for developing and testing block rendering.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45438]
Many blocks [do not render very well](https://github.com/Automattic/wp-calypso/issues/45104) (if at all) in the WP.com Reader. As a first step, let's document a process of how to test, verify, and develop solutions for Reader block rendering problems. This can be a README, or maybe a new section to the existing [Reader README](https://github.com/Automattic/wp-calypso/blob/master/client/reader/README.md).

See: pbAPfg-OF-p2
Part of: 217-gh-dotcom-manage

Site | Reader
--- | ---
<img width="500" alt="Screen Shot 2020-09-07 at 12 38 56 PM" src="https://user-images.githubusercontent.com/349751/92414030-646ab000-f107-11ea-8168-1031394d591d.png"> | <img width="500" alt="Screen Shot 2020-09-07 at 12 36 51 PM" src="https://user-images.githubusercontent.com/349751/92414046-6fbddb80-f107-11ea-92ef-1296289749d8.png">

**Comment by leandroalonso** [comment]
@kwight do you think we can add information on how to test block rendering in the WPiOS app too?

I just did a recently change that allows anyone to always retrieve an uncached CSS from Calypso or to point to any CSS domain you want: https://github.com/wordpress-mobile/WordPress-iOS/pull/14859

This makes it easier to test block changes in the WordPress iOS app. :)

**Comment by kwight** [comment]
> do you think we can add information on how to test block rendering in the WPiOS app too?

@leandroalonso Our team has zero knowledge or experience in iOS development, but if there's something we can help test or troubleshoot, let us know 👍

**Comment by krymson24** [comment]
API documentation lives here: PCYsg-sdq-p2
