### ISSUE TITLE
Editor: Remove gating logic for classic editor in wp-admin

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#45443]
As part of deprecating the Calypso editor, we're removing logic related to the editor that changes based on user registration date.

## Requirements

1. Access to the classic editor in wp-admin for Simple Sites is not gated based on user creation date

Reference and links to code p58i-9gb-p2

**Comment by retrofox** [comment]
Handling the issue here D49284-code

**Comment by creativecoder** [comment]
Resovled in r214611-wpcom
