### ISSUE TITLE
Email: Document process for developing and testing block rendering.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45441]
Many blocks do not render very well (if at all) in WP.com emails, sent to users that subscribe by email to blogs.

As a first step, let's document a process of how to test, verify, and develop solutions for email block rendering problems. This can be a page in the Field Guide, since none of this information would be appropriate in Calypso.

See: pbAPfg-OF-p2
Part of: 217-gh-dotcom-manage

Site | Email
--- | ---
<img width="500" alt="Screen Shot 2020-09-07 at 12 38 56 PM" src="https://user-images.githubusercontent.com/349751/92414356-bd871380-f108-11ea-8eef-58cf8ce318d3.png"> | <img width="500" alt="Screen Shot 2020-09-07 at 12 36 51 PM" src="https://user-images.githubusercontent.com/349751/92415221-d2fe3c80-f10c-11ea-95b4-eea663cf20f4.png">

**Comment by sixhours** [comment]
Documentation is up here: PCYsg-s9X-p2
