### ISSUE TITLE
Reader/Wordpress app notification - be able to dismiss system notifications in Reader/ WordPress app

### ISSUE THREAD

**Issue by openfist** [Automattic/wp-calypso#45455]
#### Steps to reproduce

1. Starting at URL:  https://wordpress.com/home/quotablecreek.com > Notifications
2. open Reader notifications
3. find a system notification like renewal reminders
4. unable to find an option to dismiss/close/delete

#### What I expected
- customer wants to be able to dismiss system notifications on Reader/ WordPress.com app

#### What happened instead
- no option to delete/dismiss/close

#### Screenshot / Video
- See the Act Now! Notification
![Screen Shot 2020-09-08 at 17 14 15](https://user-images.githubusercontent.com/11617249/92457876-55632b00-f1f7-11ea-9a78-d19f59ac6f01.png)

#### Context / Source

#user-report 

If requesting a new feature, explain why you'd like to see it added.
-->
- shouldn't this be standard?

**Comment by cathymcbride** [comment]
This is by design. We have an obligation to the customer to notify them about these system level things, as it could affect the continuation of their site. Thank you so much for bringing it up!
