### ISSUE TITLE
Atomic: Classic Block breaks with Gutenberg 8.9.2 plugin active

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#45472]
#### Steps to reproduce

1. Add a classic block inside the block editor 
2. Save post, exit, open post again
3. Click to edit content inside block

#### What happens

Block crashes with error as shown here: https://d.pr/i/03iOI5

Occurs with all other plugins deactivated & a default theme active. Issue resolved when Gutenberg plugin is deactivated.

#### Context / Source

Discussed in: p1599580748023200-slack-gutenberg-on-dotcom

**Comment by eoinsav** [comment]
Another report in #22815712-hc

**Comment by sirreal** [comment]
This seems to be https://github.com/WordPress/gutenberg/issues/24696 manifesting.

**Comment by sirreal** [comment]
This was handled by r213337-wpcom / p9o2xV-12z-p2.
