### ISSUE TITLE
Premium Content: Buttons are not displayed inline.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45477]
Premium Content buttons are displaying one on top of the other. It looks lik this is because the first "contribution" button is missing the `wp-block-button` class that would give it a `display: inline-block` value.

<img width="1414" alt="Screen Shot 2020-09-08 at 1 41 11 PM" src="https://user-images.githubusercontent.com/349751/92525793-4ff6e800-f1d9-11ea-93d5-9d4dfb33704b.png">

**Comment by iamtakashi** [comment]
+1 This is a blocker for releasing some patterns with Premium Content block. cc @ianstewart
