### ISSUE TITLE
Color bubbles misalingned in editor sidebar

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#45483]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/block-editor/post/freesitetest9636.wordpress.com/38
2. Click block for stars or poll
3. Look at color options in sidebar
4. Notice two beige ones are friendly

#### What I expected
Would be aligned like other dots

#### What happened instead
beige bubbles misaligned
when open Dev Console alignment is corrected

#### Browser / OS version
Windows 10 Chrome 85.0.4183.102

#### Screenshot / Video
![bubbles](https://user-images.githubusercontent.com/47717887/92560589-59d12780-f27b-11ea-97e3-49416a09f319.gif)

#### Context / Source
Was playing around with test posts and noticed. I think I'm supposed to report here but may just be confused??

 #dogfooding 

-->

**Comment by obenland** [comment]
@Nic-Sevic I tried reproducing this with a star or poll block and the color bubbles show up fine on my end? Is this something that still happens for you?

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I tried to reproduce this behavior on the following platforms:

OS: macOS Big Sur 11.4 (20F71)
OS: Windows 10
Browser: Firefox Nightly 92.0a1 (2021-07-23) (64-bit)

I was unable to do so.

If this issue should remain open, please feel free to re-open this bug.

![Screen Shot 2021-07-29 at 3 33 04 PM](https://user-images.githubusercontent.com/6549265/127574274-ea3e3c37-8c00-4104-ae58-67a3549f5ebb.png)
![Screen Shot 2021-07-29 at 3 33 18 PM](https://user-images.githubusercontent.com/6549265/127574275-b4f4fa79-5067-44a3-8da7-220487cae6f1.png)
