### ISSUE TITLE
Domain Picker: Refactor stale test suite

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#45501]
#### Overview

Since the `domain-picker` was moved into `packages/` along with its tests, it doesn't look like a corresponding `jest.config.js` file was created for the package to ensure that the component tests were running in CI.

A `jest.config.js` test was created for the `domain-picker` package in this PR https://github.com/Automattic/wp-calypso/pull/45490 although running the old test suite resulting in many failures due to the tests being unmaintained whilst the codebase has moved on.

#### Work to be done

* Update the tests that are currently skipped/commented out to ensure they run, and pass successfully.

#### Running the tests

1. Check a `jest.config.js` exists for the package `packages/domain-picker`
2. From project root run `npm run test-packages`

**Comment by cathymcbride** [comment]
FYI @bsessions85

**Comment by StefanNieuwenhuis** [comment]
I'm closing this issue since we're fixing it in #50888 & #42638.
