### ISSUE TITLE
wp-admin: default to Gutenberg

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#45519]
To bring wp-admin (Simple Sites) in line with Calypso, wp-admin should also default to the block editor.

## Requirements

- Editing posts defaults to the block editor in wp-admin for all users (Simple Sites)

## Notes

- Which editor a user sees in wp-admin is currently tied to the editor preference. We need to update this so that all users see the block editor be default; the preference should no longer be used.

Reference for how it works currently: p7DVsv-919-p2#comment-30371

**Comment by allilevine** [comment]
We're working on making this change to WordPress.com: D49393-code

**Comment by creativecoder** [comment]
Resolved by r214567-wpcom
