### ISSUE TITLE
CoBlocks Logos Block is not responsive. 

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#45562]
#### Steps to reproduce

1. Make sure CoBlocks is activated
2. Create a page, and add the CoBlocks Logos Block to the page. Add a number of images to it. Publish the page.
3. View the page, then jump into dev tools and adjust the size of the screen, or view the page on mobile. The logos are set as a %, so the smaller the screen size, the smaller the image, until they disappear on small/mobile screens.

#### What I expected
The logos to stay visible on smaller screens.

#### What happened instead
Logos become so small that they disappear entirely.

#### Browser / OS version
All.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30731356/92834840-5b8c0f80-f38f-11ea-9580-af5cfd966855.png)

vs
![image](https://user-images.githubusercontent.com/30731356/92834214-9b062c00-f38e-11ea-9a8f-b2dea117ce8c.png)

#### Context / Source
#user-report #3306865-zen

**Comment by simison** [comment]
This would probably be better opened at https://github.com/godaddy-wordpress/coblocks

**Comment by p-jackson** [comment]
Reported here godaddy-wordpress/coblocks#1808

**Comment by p-jackson** [comment]
This was just fixed upstream (I've tested in the coblocks canary build). We now need to wait for a coblocks release and then do the release dance to get this onto wpcom.

@Automattic/good-mountain can I add this somewhere so it gets tracked as part of the next coblocks release on wpcom?

**Comment by sirreal** [comment]
[It looks like there's a release every month or so](https://plugins.trac.wordpress.org/log/coblocks/), and that would mean a release next week. We'll plan to upgrade in the near future.

Tracked: https://github.com/Automattic/wp-calypso/issues/49592

**Comment by davipontesblog** [comment]
Closing as fixed as CoBlocks has been updated now.
