### ISSUE TITLE
Handle admin-menu error via action dispatch in data layer 

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#45585]
Sub Issue of https://github.com/Automattic/wp-calypso/issues/45435

Currently we not handling any errors in the `admin-menu` data layer

https://github.com/Automattic/wp-calypso/blob/040142a777f7210dd1dca850c082e313c9c32c12/client/state/data-layer/wpcom/sites/admin-menu/index.js#L24-L26

We need to to decide on the UX if the API encounters an error. How do we handle this? Fallback nav items? Show error message?

More specific tasks include:

- Create a new `action` which updates `admin-menu` state to record the `ADMIN_MENU_REQUEST_ERROR` state.
- Reformat `adminMenu` state to be combined reducers for `ui` and `items` so that we can have a flag for the current state of the fetch for menu items (eg: dispatched, success, failed).
- Dispatch the correct action in the data-layer error scenario and update state accordingly.

**Comment by getdave** [comment]
@Automattic/ajax Any ideas on scenarios where we might need to handle an error from the API in a user-facing manner. If not then we can close out this task.

**Comment by obenland** [comment]
Let's close it out for now. We can reopen when we do come across a scenario for it.
