### ISSUE TITLE
Gutenboarding: site title placeholder baseline is wonky in FF

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#45593]
#### Steps to reproduce

1. Starting at URL: `/new`, with gutenboarding and using Firefox
2. Wait for the nifty title placeholder to fill in some text

#### What I expected
The placeholder text would appear with vertical alignment matching actual content, as it does in Chrome

#### What happened instead
The baseline is lowered, causing an odd strikethrough effect

<img width="836" alt="Screen Shot 2020-09-11 at 4 04 20 PM" src="https://user-images.githubusercontent.com/9310939/92973059-f3016900-f448-11ea-9afa-6715465be80a.png">

This only affects the placeholder text.

#### Browser / OS version
Firefox 73 on macos

#### Context / Source

#manual-testing

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I tried to reproduce this issue today with the following versions:
OS: macOS Big Sur 11.1 (20C69)
Browser: Firefox Nightly 89.0a1 (2021-03-23) (64-bit)

Across all levels of zoom, the placeholder text remained in the same position relative to the text.

As I was not able to reproduce this issue, it is being closed with the label `Closed - Not Reproducible`.
