### ISSUE TITLE
Editor: Updating a post on mobile doesn't switch to show the update success notice

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4559]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/ on mobile view
2. Create a new post
3. Publish the post from the "Actions" view
4. The notice shows on the "Write" view
5. Now update some text and switch to "Actions" view
6. Click Update

#### What I expected

To switch to "Write" view and see success notice

#### What happened instead

No visual indicator post has been updated. Manually changing views can see the success notice.

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

![editor update notice on mobile](https://cloud.githubusercontent.com/assets/128826/14340189/7fd5b9ee-fcc8-11e5-9991-06ee61cd3c6f.gif)

**Comment by DanReyLop** [comment]
This will be fixed as part of the mobile editor redesign: https://github.com/Automattic/wp-calypso/issues/4266

**Comment by alisterscott** [comment]
@DanReyLop thanks for the heads-up

**Comment by hoverduck** [comment]
19May16 Bug Scrub

Confirmed this is a non-issue in the new redesign, but I'm leaving this open until that goes live.

**Comment by hoverduck** [comment]
#bug-scrub

Closing, this is no longer an issue.  Now clicking Write automatically sends you back to the Edit panel where you can see the success notice.
