### ISSUE TITLE
Ad Settings: Display notice when site hidden

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#45603]
#### Steps to reproduce

1. For site with WordAds enabled visit set Privacy settings to be hidden from search engines at https://wordpress.com/settings/general/<site>
2. Visit https://wordpress.com/earn/ads-settings/<site>

#### What I expected
Some warning or notice advising that no ads would be displayed when privacy is set to hidden

#### What happened instead
There is no notice and it can be confusing when things look configured properly but no ads are showing.

#### Context / Source

#user-report

**Comment by davipontesblog** [comment]
@obenland would this be something that Manage could pick up in a future janitorial run? It seems low effort and it's still an issue, I just repro'ed.

**Comment by obenland** [comment]
It looks like this ticket is already on a Create board, which is probably a good place for now.
This would be a great first issue for an OSS contributor or dev onboarding, too.
