### ISSUE TITLE
Remove email confirmation restriction for editing menus

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#45608]
When signing up at .com, and not confirming your email at first, there's a restriction to edit your menus:

<img width="1579" alt="Screenshot 2020-09-14 at 10 11 57" src="https://user-images.githubusercontent.com/87168/93054927-cfba0200-f672-11ea-8d8e-720be5a021bb.png">

Open site's Customizer to observe this. This doesn't make any sense.

We should:
- Do light research to see if it's possible to understand why this restriction was added in first place; it's likely been quite long ago though.
- Remove the restriction

**Comment by yansern** [comment]
The relevant file is `wp-content/mu-plugins/customizer-feature-disabler/customizer-feature-disabler.php`.

**Comment by yansern** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/43399

**Comment by ciampo** [comment]
Closing as duplicate issue #43399 has been fixed and closed (cc @razvanpapadopol )
