### ISSUE TITLE
Gutenboarding: pre-select features

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#45611]
- [X] If a user selects a paid domain during Gutenboarding flow, we could pre-select the Custom Domain feature while showing the recommended design in the top-right corner. [Done in https://github.com/Automattic/wp-calypso/pull/45693]
* Question: How de-selecting this feature should work? Is it enough to be done only via Domain Modal (by selecting a free plan)?
    * Just use regular toggling and update plan recommendation. https://github.com/Automattic/wp-calypso/issues/45611#issuecomment-692452482
<img width="1507" alt="Screenshot 2020-09-14 at 11 09 29" src="https://user-images.githubusercontent.com/14192054/93060742-35aa8780-f67b-11ea-9701-2bec29ae677f.png">

- [ ] Should we add a feature item also for the advanced / premium design? This can be preselected as well after selecting a design like this.
   * Yes, add _Premium themes_ feature together with a new feature that will recommend ecommerce plan. #45748
<img width="1509" alt="Screenshot 2020-09-14 at 11 09 51" src="https://user-images.githubusercontent.com/14192054/93060570-01cf6200-f67b-11ea-8c29-158011582583.png">

**Comment by ollierozdarz** [comment]
Hi @razvanpapadopol, you may need to explain this one a little more please, as I'm not understand the last part "...while showing the recommended design in the top-right corner". The first part makes sense, to pre-select the 'Custom domain' feature picker item if the user has selected a TLD in the previous step. That's something that doesn't need a design and I imagine would be quick to implement.

For (1): In my mind, I if a user de-selects the 'Custom domain' feature from the feature picker page (assuming they've already chosen a TLD), we don't need to loop them back to the Domains page, we can simply handle the feedback in the Plans page via the "[X] roastingbeans.com is not included" text, like we currently do now. If we start to tie in conditions to all of the features, it may get very confusing in what should be a quick and linear experience.

For (2): My gut feeling here is that it's not going to be of high impact compared to other features listed on the page, and may just add to the cognitive load. I'm still new though, so happy to be told I'm wrong here! 🙂

**Comment by razvanpapadopol** [comment]
> the last part "...while showing the recommended design in the top-right corner"

I was referring to a live update of the Plans button which by default (if you go to https://wordpress.com/new/design?fresh) says "View plans" and in screenshots above - "Personal Plan". Here is an example where I'm starting with "Free plan" and it gets updated as I select and deselect features: https://cloudup.com/cQapnqXMVYL

> If we start to tie in conditions to all of the features, it may get very confusing in what should be a quick and linear experience

I agree. So we can continue to use the feature selector to recommend a plan based on explicitly selected (or pre-selected and then confirmed) features. Then on the plans page, users will get to know what is included and what is not in the recommended plan so they can take a decision.

> it's not going to be of high impact compared to other features listed on the page

We had some discussions about the premium designs and their role in the onboarding. See also https://github.com/Automattic/wp-calypso/issues/44239
@ianstewart could probably give you a better context around this.

**Comment by ollierozdarz** [comment]
@razvanpapadopol, thanks! 🙂 That (https://cloudup.com/cQapnqXMVYL) looks and works great!

> My gut feeling here is that it's not going to be of high impact compared to other features listed on the page

Thanks for the background. I guess the decision is to add a Feature picker item for 'Premium' designs (aka require Personal plan or above), which then utilizes something like your recommendation to grey out the Free plan in the Plans page. I personally feel like it needs some more thought as I don't want to negatively impact that high-value plans page over a quick decision.

**Comment by razvanpapadopol** [comment]
> add a Feature picker item for 'Premium' designs (aka require Personal plan or above)

I expect premium designs to replace "Premium Themes" as seen on the the [pricing page](https://wordpress.com/pricing/) right now.

<img width="1535" alt="Screenshot 2020-09-16 at 09 43 36" src="https://user-images.githubusercontent.com/14192054/93301503-3b31da00-f801-11ea-8e18-550e9a2bffd4.png">


> utilizes something like your recommendation to grey out the Free plan in the Plans page

That is probably not a good idea during site-creation. We have it currently implemented in Site setup flow for the paid domain <-> free plan incompatibility.

**Comment by ollierozdarz** [comment]
Yeah, I mentioned "aka require Personal plan or above" because of this:

<img width="369" alt="Screen Shot 2020-09-16 at 4 48 45 pm" src="https://user-images.githubusercontent.com/67085494/93301994-9a611000-f83c-11ea-8109-d775c3d425e0.png">

Either the tooltip is incorrect or the pricing table. Either way, the confusing part is that the Designs have the same naming as a Plan, but that's probably a bigger issue. 

> utilizes something like your recommendation to grey out the Free plan in the Plans page

Yep, it's not a good idea. Unless there's a big push for this to become an item in the Feature picker, I'd personally vote to leave it how it is for now.

**Comment by razvanpapadopol** [comment]
Closing this as it was partly implemented in #45693. The second part about Premium Designs has a dedicated issue: #44239
