### ISSUE TITLE
Editor: Enhancement - Add undo publish (grace period) feature for email notifications

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4562]
Since I have x hundred email followers of my professional blog, I have a little bit of ‘publish anxiety’ every time I hit publish as I know that immediately a copy of those words, images etc. will be emailed to x hundred people.

It would be cool to allow users to specify a grace period before notifications are sent so that edits/changes can be made or the they could cancel the notifications completely.

One such idea I am thinking is about GMail’s undo send feature, which is actually just a small delay which allows you to quickly cancel sending an email if you realized you sent something you shouldn't have after hitting send.

![undo](https://cloud.githubusercontent.com/assets/128826/14343241/e7a5a588-fce2-11e5-8ef8-d5067e835410.png)

**Comment by lancewillett** [comment]
👍 This is a great idea — you can feel better especially about sending out an important post to social media.

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Still seems like a reasonable enhancement request, however, since there hasn't been any activity for this issue in some time I would like to have a second opinion about possibly closing it for now.
