### ISSUE TITLE
Paragraph Block: Duplicated paragraph tag added to markup

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#45629]
Consider this simple example of a large paragraph with a tight line-height, and notice the line-height value of `.9`

![Screenshot 2020-09-14 at 12 44 09](https://user-images.githubusercontent.com/908665/93082801-76110200-f689-11ea-8ddd-76271910fe49.jpg)

The markup you get will be the following, and it works as expected.
```
<!-- wp:paragraph {"style":{"typography":{"lineHeight":".9","fontSize":70}}} -->
<p style="line-height:.9;font-size:70px">THE PLACE THAT MADE ME</p>
<!-- /wp:paragraph -->
```
However, I could have easily added the value in formats like `0.9` or `0.90` as they are technically the same.

![Screenshot 2020-09-14 at 12 51 17](https://user-images.githubusercontent.com/908665/93082819-7c06e300-f689-11ea-9c1c-05fe73a4576e.jpg)

But the markup will actually be different if you add the line-height as `0.9`. The following is what you'll see after saving it and reloading the editor. Notice the strange nested paragraph tags in the markup.

```
<!-- wp:paragraph {"style":{"typography":{"lineHeight":"0.9","fontSize":70}}} -->
<p style="line-height:0.9;font-size:70px"><p style="line-height:.9;font-size:70px;">THE PLACE THAT MADE ME</p></p>
<!-- /wp:paragraph -->
```

This shouldn't happen and not only causing a visual problem in the front-end, but the block will also be ended up invalidated while you're editing the post/page more.

I've also noticed that the duplicated tags are slightly different — one of them has the line-height value `0.9` and another has `.9`. I was curious when this issue occurs, and I typed in a bunch of different formats of line-height values, `.9`, `0.9`, `0.90` and so on.

![Screenshot 2020-09-14 at 13 30 01](https://user-images.githubusercontent.com/908665/93086055-6e079100-f68e-11ea-9c2a-2944f412389a.jpg)

This is the markup I've got after saving it and reloading the editor.

```
<!-- wp:paragraph {"style":{"typography":{"lineHeight":".9"}}} -->
<p style="line-height:.9">Line Height Value = .9</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"0.9"}}} -->
<p style="line-height:0.9"><p style="line-height:.9;">Line Height Value = 0.9</p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"0.90"}}} -->
<p style="line-height:0.90"><p style="line-height:.9;">Line Height Value = 0.90</p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"0.900"}}} -->
<p style="line-height:0.900"><p style="line-height:.9;">Line Height Value = 0.900</p></p>
<!-- /wp:paragraph -->
```

As you can see, all the instances except the one with `.9` were ended up with the duplicated markup.

How about a different number? Let's see the following example.

![Screenshot 2020-09-14 at 13 36 45](https://user-images.githubusercontent.com/908665/93086763-8330ef80-f68f-11ea-9e86-8a06acbb1cd6.jpg)

```
<!-- wp:paragraph {"style":{"typography":{"lineHeight":"1.000"}}} -->
<p style="line-height:1.000"><p style="line-height:1;">Line Height Value = 1.000</p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"1.00"}}} -->
<p style="line-height:1.00"><p style="line-height:1;">Line Height Value = 1.00</p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"1.0"}}} -->
<p style="line-height:1.0"><p style="line-height:1;">Line Height Value = 1.0</p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":"1"}}} -->
<p style="line-height:1">Line Height Value = 1</p>
<!-- /wp:paragraph -->
```

All the instances except the one with `1` were ended up with the duplicated markup. 

These tests suggest that the duplicated tag occurs if the line-height value isn't exactly in a certain format. This is an issue that needs to be fixed as I saw the instances eventually got invalidated after keeping editing the page/post.

![Screenshot 2020-09-14 at 13 52 22](https://user-images.githubusercontent.com/908665/93088317-ab215280-f691-11ea-8c7f-a4b1feb722a9.jpg)

This seems to be WP.com specific issue as there is no issue in my local install with Gutenberg 8.9.3 and CoBlocks 2.3.2 plugins.

cc @ianstewart @alaczek @apeatling

**Comment by ramonjd** [comment]
This is caused by CSSTidy "optimizations".

Working on a fix here: https://github.com/Automattic/jetpack/pull/19993
