### ISSUE TITLE
Varia: margin-bottom added to captions in Collage block

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#45638]
## Steps to replicate

1. Activate one of the Varia child themes
2. Add a Collage block to a page or post
3. Enable captions in the block settings
4. Add images and captions to the block

## Result

![gap underneath captions](https://d.pr/i/sykQx3+)

There's a margin-bottom of 16px being added underneath the captions which causes a gap, so it's not flush with the bottom of the image. 

## Expected

That gap shouldn't be there, and after testing it appears that this only happens with Varia child themes and the Collage block in particular. 

For now, I've let the user know that they can use the Masonry block, since they still wanted to be able to link individual images in the gallery. 

* User report: 23429394-hc
* Follow-up ticket: 3234312-zen

**Comment by jeyip** [comment]
I can confirm that there is no longer a gap for the `alves`, `balasana`, and `barnsbury` themes. I'm closing this for now, but feel free to reopen the issue if there are still problems.
