### ISSUE TITLE
Notifications: Expand supported HTML elements.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45649]
Masterbar notifications support a very limited set of HTML tags (see `lib/class.notification-builder.phpL125`), causing block rendering to fail from missing elements. Let's expand the supported tags to include `p`, `div`, headings, `cite`, `blockquote`, and `hr` (and any other tags found lacking from blocks).

<img width="1518" alt="Screen Shot 2020-09-14 at 12 58 22 PM" src="https://user-images.githubusercontent.com/349751/93132136-00f1fc80-f68a-11ea-9859-5cbbf45cb330.png">

Expanding tag support cannot cause regressions with mobile+web notifications.

See: paYKcK-FI-p2

**Comment by blackjackkent** [comment]
Started looking into this today; I think it may entail a combination of changes to calypso and WPCOM code. Will hopefully have a preliminary PR to work with by tomorrow.

**Comment by blackjackkent** [comment]
Digging into this is proving complex.

Simply adding the new tags as valid markup in the generation of the notifications server-side is easy (I've created a diff at D49621-code which adds `cite` and `hr` as valid tags) and can see on the Calypso side that the tags are being included in the raw notification text as would be expected. The primary problem evolves during the `p()` method called in `/apps/notifications/src/panel/templates/functions.jsx` which takes the raw notification text and wraps it in paragraph tags based on the presence of linebreaks.

This logic is thrown off by things like, for instance, nested tags. In the case of the post I am testing with which includes a blockquote with citation, the original text returned from the server is:

```
Here is a text post with a blockquote

<blockquote class="wpnc__blockquote">
Here’s an important quote

<cite class="wpnc__cite">and the person who said it</cite>
</blockquote>
a;lskdjfal;skdjf;lakjsd

<hr class="wpnc__hr">
test
```

Which all looks well and good, but the presence of the newline before the `cite` tag means that the `p()` function converts it into:

```
<div>Here is a text post with a blockquote</div>
--
<div><blockquote class="wpnc__blockquote"></div><div>Here’s an important quote</div>
--
<div><cite class="wpnc__cite">and the person who said it</cite></div><div></blockquote></div>
--
<div>a;lskdjfal;skdjf;lakjsd</div>
--
<div><hr class="wpnc__hr"></div>
--
<div>test</div>
```

So the blockquote tag ends up being split up into two pieces each wrapped in a separate div.

I'm trying to figure out the best way to fix this while being minimally invasive to the system as a whole. Further updates to follow, but any thoughts appreciated.

**Comment by kwight** [comment]
Just thinking out loud before running off, but how bad would it be to remove the `p()` method? Or add a flag somehow that tells the `p()` method to not do it's thing on the given input?..

**Comment by mmtr** [comment]
Another approach would be to prevent the newlines if they are the culprit. Not sure if they are added by some logic in the `Notification_Block` class, but might be worth exploring.

**Comment by kwight** [comment]
@blackjackkent Are there other elements we need to add support for beyond what's in #45710 ? Could you verify the blocks in phase 1 of 217-gh-dotcom-manage and see if additional followup PRs are needed?

**Comment by blackjackkent** [comment]
I spent today working further on all of this, specifically tracking down an issue which is causing line breaks in quotes to get lost. The culprit for this appears to be the `parse_recursively()` function in the wpcom file `/wp_content/lib/class.notification-builder.php`, which seems to be stripping out the <br /> tags by making use of the `text_content` property of the DOMDocument object used there. I'm going to try and get a solution together tomorrow for how to address this while maintaining overall security of the parsing.

@kwight Looking at the list, I haven't looked at the "layout grid" element so we'll need a follow-up PR for that. I'm also still working on the above-mentioned bug for quotes and a slightly buggy behavior for separators, but for the most part those are fixed.

**Comment by mmtr** [comment]
We also have 198-gh-dotcom-manage and apparently there is more markup we need to add to the allowed list. For instance, I know that all headings tags (`h1`, `h2`, ...) should be added.

**Comment by kwight** [comment]
We've added support for quotes, horizontal rules, headings, and line breaks – some still need styling work, but I've closed out 198-gh-dotcom-manage in favour of tracking the rest in separate issues.
