### ISSUE TITLE
Copy in Plan Features is inaccurate (Pay with PayPal)

### ISSUE THREAD

**Issue by CompChris** [Automattic/wp-calypso#45646]
#### Steps to reproduce

Site must be on Premium plan or higher.

1. Starting at: WordPress.com > My Sites > Plan > My Plan > Premium Plan
2. Sell online with PayPal

![Markup on 2020-09-14 at 12:41:10](https://user-images.githubusercontent.com/6847710/93113772-a5bf0a80-f687-11ea-9d82-5512d43526e1.png)

#### What is says

Copy says: 
>Add a button to any post or page to collect PayPal payments for physical products, digital goods, services, or donations.

#### What it should say

>Add a button to any post or page to collect PayPal payments for physical products, services, or donations.

Purchase of digital goods is limited with Pay with PayPal blocks, and distributing digital download links isn't something this does well

#### Context / Source

23999315-hc

**Comment by kristastevens** [comment]
@CompChris Thanks for the ping! Your proposed copy is clear and concise! Looks great to me!

**Comment by Aurorum** [comment]
PR for this issue in #45702. :)
