### ISSUE TITLE
Sharing on LinkedIn impossible...

### ISSUE THREAD

**Issue by VIParts** [Automattic/wp-calypso#45658]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/marketing/connections/www.viparts.nl?site=www.viparts.nl
2.
3.
4.

#### Screenshot / Video: 
![VIParts LinkedIn Connection Fail](https://user-images.githubusercontent.com/52434565/93151371-0a1bb180-f6fc-11ea-9609-6d2abaaf218a.jpg)

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to reproduce this today with the following versions:
Gutenberg: v10.2.1
CoBlocks: 2.5.3
Editing Toolkit: 3.2798

I had no issues connecting my LinkedIn account to the site, nor did I have issues sharing the post automatically to LinkedIn.

Seeing that I could not reproduce this issue, this issue will be closed with the label Closed - Not Reproducible.
