### ISSUE TITLE
Billing Management: Add subscription detail components to new site level routes (3)

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#45679]
- add site-level route under `/purchases/subscriptions/:site-id/:receipt-id`
- Ensure auto-renew toggle still works
- Ensure renew works as well
- Cancel flows
- Change payment method 
- need to verify that all linked pages have appropriate routes at the site level and/or modals

**Comment by sirbrillig** [comment]
1/3 of this is done in https://github.com/Automattic/wp-calypso/pull/45922

We still need to add:

- Cancel page
- Add payment method page

**Comment by sirbrillig** [comment]
The 2nd third is done in https://github.com/Automattic/wp-calypso/pull/45974  which handles the cancel page.

**Comment by nbloomf** [comment]
Part 3 (add/change payment method) is in #45977

**Comment by sirbrillig** [comment]
Part 4 (the cancel domain confirmation page) is in https://github.com/Automattic/wp-calypso/pull/46021
