### ISSUE TITLE
Nav Unification: Left Nav submenu hover / active

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#45676]
Let's implement structural and styling changes so that we achieve a unified navigation experience between calypso and wp-admin when user is using the left nav.

- [ ] Use flyouts on hover state instead of expand / collapse 
- [ ] (Explore `Reader` implications)
- [ ] Make sure the menu item is selected / highlighted depending on current url / route

**Comment by obenland** [comment]
@frontdevde Is this something you'd be interested in?

**Comment by frontdevde** [comment]
Design for reference: [Figma File](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=325%3A7585)

As per Nav Unification Project Design i2 (see pbAPfg-RE-p2) the submenu in Calypso should show as a flyout menu on hover:

<img width="1347" alt="Screenshot 2020-09-29 at 16 07 41" src="https://user-images.githubusercontent.com/1562646/94569627-37c13880-026e-11eb-835b-a465786eb4d4.png">

At the same time it should show as a submenu inside the left hand navigation when selected:

<img width="1349" alt="Screenshot 2020-09-29 at 16 07 56" src="https://user-images.githubusercontent.com/1562646/94569946-95558500-026e-11eb-95f9-eafa5e176104.png">

**Comment by frontdevde** [comment]
First iteration of flyout menu has been merged. 

Closing this ticket in favor of https://github.com/Automattic/wp-calypso/issues/46095 and https://github.com/Automattic/wp-calypso/issues/46094.
