### ISSUE TITLE
Create an editable coming soon page for new sites

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#45689]
### Acceptance criterea
- [ ] Add a page template for an editable coming soon page
- [ ] Have headstart create a page based on this template
- [ ] Set the site option `wpcom_public_coming_soon_page_id` to the ID of the new page
- [ ] Handle paid vs non paid plans
- [ ] Must be behind the existing coming soon feature toggle.

### Questions 
- Would the page be created as a draft for non-paid plans?
  - (How to do this in headstart)

**Comment by ramonjd** [comment]
Creating the site on signup 🎉  https://github.com/Automattic/wp-calypso/pull/45950

**Comment by ramonjd** [comment]
Moving this to the backlog since it's out of scope for now 👍

**Comment by ramonjd** [comment]
Closing this as it's not a feature we'll be developing any time soon.
