### ISSUE TITLE
Patterns Toolkit MVP pre-launch testing

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#45692]
This is an issue to track tasks/bugs in translated Gutenboarding designs

### Creating sites using Patterns Toolkit

To replicate, create a site via `wpcalypso.wordpress.com/new/{locale_slug}`

- [x] Select Edison/Bowen/Cassel or another design with a latest blog posts block (a8c). The latest posts block shows `0` instead of a post excerpt on blog roll pages for new non-EN sites (D49793-code)
- [ ] Create a site with Cassel design in Korean, and go to the blog roll page after site creation. The Jetpack subscription block appears to throw a validation error.
- [ ] Will we still need to call `set_gutenboarding_site_templates()` in `sites/new`? D49989-code

### Unrelated to patterns but dumping here anyway
- [x] When creating a new non-EN site **without entering a site title**, the default site title is in English - `Site Title`.  https://github.com/Automattic/wp-calypso/pull/45768
- [x] Bowen blog roll page headstart annotation contains spacer block error and blue background D49646-code

**Comment by andrewserong** [comment]
Update: deployed D49646-code, and raised the related issue in https://github.com/Automattic/wp-calypso/issues/45715

**Comment by andrewserong** [comment]
> Will we still need to call `set_gutenboarding_site_templates()` in sites/new?

I think the answer is yes. With `use_patterns` set this ensures we grab the current homepage content from the source site directly instead of relying on the Headstart annotation. This means that homepage changes can be made more easily and have the changes flow through immediately without having to (or having to wait for us to) re-do the annotation.

**Comment by andrewserong** [comment]
Ran out of time to investigate this one further today, but it looks like there's a block validation issue with the Blog Roll page after selecting Cassel design and navigating to that page in the editor after site creation. (To recreate, I created the site in Korean from wpcalypso.wordpress.com/new/ko).

![image](https://user-images.githubusercontent.com/14988353/93569750-53f2e900-f9d5-11ea-8823-3769e896eb85.png)

Looks like somewhere along the lines the Korean characters are being unicode escaped, but the escape sequence has its `\` character stripped? I can't think of anything we've changed recently in the parsers, and parsing the homepage content seems to work fine from the CLI, so I wonder if there's an interaction with Gutenberg at play here (or something else for that matter).

**Comment by andrewserong** [comment]
> The latest posts block shows 0 instead of a post excerpt on blog roll pages for new non-EN sites

I have a diff up to fix this in D49793-code. @deBhal is also doing a refactor of this part of Headstart in D48542-code which will also fix the issue, so I just put together D49793-code quickly in case we need to have a fix in the interim.

**Comment by andrewserong** [comment]
For the block validation / unicode issues in block attributes, Autumn wrote up the issue here: https://github.com/Automattic/wp-calypso/issues/45763, so we'll need to do a bit more investigation into that one and work out if it's a Headstart issue or if it's to do with how Gutenberg parses / updates block attributes.

**Comment by ramonjd** [comment]
> so we'll need to do a bit more investigation into that one and work out if it's a Headstart issue or if it's to do with how Gutenberg parses / updates block attributes.

I guess you saw this in your Googling: https://wordpress.stackexchange.com/a/53339

Says that using [wp_slash()](https://developer.wordpress.org/reference/functions/wp_slash/) before updating the post _may_ work, but I can't find the right place to use it. Tested a few spots in headstart (post insertion etc) and no dice.

**Comment by ramonjd** [comment]
I think we can close this since the ptk is fairly mature. There's a separate issue for the unicode issue:

> For the block validation / unicode issues in block attributes, Autumn wrote up the issue here: #45763, so we'll need to do a bit more investigation into that one and work out if it's a Headstart issue or if it's to do with how Gutenberg parses / updates block attributes.
