### ISSUE TITLE
Accessibility: Provide high contrast interface option

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#457]
Originally raised by @supernovia 

Provide a high contrast interface option for users with reduced visibility, as per forum discussions.

**Comment by SiobhyB** [comment]
Also raised in p4vt7e-27-p2.

Some users have great difficulty navigating with the default colour scheme. It would be nice to offer a high contrast alternative.

**Comment by folletto** [comment]
Noting that this to happen needs:

1. The architecture for the colors to be swapped dynamically
2. A color scheme built on that architecture
3. The UI to switch color scheme.

The first step is happening in #15731.  :)

**Comment by designsimply** [comment]
Noting that we are discussing increasing icon and text contrast in the sidebar (internal ref: p58i-6Ts-p2).

**Comment by kristarella** [comment]
+1 in ticket 1470890-zen

**Comment by torres126** [comment]
I think this is fixed now with the new colour schemes added to Calypso?

**Comment by jsnajdr** [comment]
The new color schemes all have higher contrast than the original scheme and all pass the WCAG AA requirements. See also: https://en.blog.wordpress.com/2019/01/08/customize-your-wordpress-com-dashboard/
