### ISSUE TITLE
Gutenboarding: align custom domain plan recommendation 

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#45716]
#### Steps to reproduce

1. Starting at URL: wordpress.com/new
2. Pick a TLD on Domains step
3. Deselect Custom domain feature on Features step.

#### What I expected

* When picking a TLD or selecting Custom domain feature, same plan should be suggested (Personal plan)

#### What happened instead

* Premium plan is suggested when I have only the TLD selected. Personal plan for all other cases.

#### Screenshot / Video

https://cloudup.com/cPy5LVtEH1L

**Comment by simison** [comment]
FYI @ollierozdarz
