### ISSUE TITLE
Signup: Typo->signup no longer working as expected.

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#45750]
#### Steps to reproduce

1. Visit a non-existent WordPress.com site (e.g. something like https://stgstgsnerkgjneg.wordpress.com/ )
2. That redirects to https://wordpress.com/typo/?subdomain=stgstgsnerkgjneg
3. Click the link "Do you want to register stgstgsnerkgjneg.wordpress.com?" link (e.g. https://wordpress.com/start?ref=typo&new=stgstgsnerkgjneg ).

#### What I expected
A new site at stgstgsnerkgjneg.wordpress.com

#### What happened instead
A new site at a totally different URL. In my case, it was my username with a random string of numbers.

#### Browser / OS version

Firefox

#### Screenshot / Video
![2020-09-18 at 10 21 AM](https://user-images.githubusercontent.com/88897/93615175-acf05c00-f998-11ea-873c-25334274e49b.png)

#### Context / Source
#reallife

Noticed there was a particular URL that folks were including as an example domain pretty often and saw that it was not registered. Going to register it to prevent abuse in the future.

**Comment by klimeryk** [comment]
Thanks for reporting, @kraftbj! Indeed, it seems a regression crept in. Looks like it's simply ignoring the `new` parameter (or there's a race condition) and the search you see as a result is simply the last saved one from regular signup.

I'll try to have a closer look and provide a fix this week - it should an easy-ish fix, just need to dig into the spaghetti a bit :D

**Comment by klimeryk** [comment]
Sorry for the delay! Finally managed to get to this and found the issue: https://github.com/Automattic/wp-calypso/pull/46282
