### ISSUE TITLE
Editing wordpress in Safari

### ISSUE THREAD

**Issue by adelwoods** [Automattic/wp-calypso#45762]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/pages/friendsofadelwoods.wordpress.com
2. Using Safari I clicked on edit home page, and all I got was a blank screen.  
3. I tried different buttons within Wordpress to edit but all I got was a blank screen.  I tested editing blog pages and the same result
4. I then tried with Firefox and was able to edit the page. I have tried again with Safari and again get a blank screen.

**Comment by cathymcbride** [comment]
No further reports and I'm not reproing. Closing.
