### ISSUE TITLE
Jetpack: Premium themes cannot be enabled on sites with Jetpack Complete

### ISSUE THREAD

**Issue by tiffanybridge** [Automattic/wp-calypso#45779]
#### Steps to reproduce
Ensure a site is connected with the Jetpack Complete plan. 

1. Starting at URL: wordpress.com/themes/
2. Find a premium theme
3. Attempt to activate it on your Jetpack Complete site.

#### What I expected

The premium theme should activate. 

#### What happened instead

Error banner ""Theme not yet available for this site." 

#### Browser / OS version

Chrome/MacOS

#### Screenshot / Video
![Screen Shot on 2020-09-21 at 10-10-10](https://user-images.githubusercontent.com/6172029/93777396-b543d380-fbf2-11ea-8b20-dd81c81a2442.png)
#### Context / Source

Team 51 project, tested with multiple premium themes. Also tested in desktop app, where the flow fails differently, but also seems to be related to Jetpack plan changes.

Edited to add: This issue was found on a fresh install of WordPress, freshly connected to Jetpack for the first time.

**Comment by cbauerman** [comment]
I just deployed D49976-code, which should address this issue. If @tiffanybridge or @cathymcbride can confirm we can close the issue!

**Comment by tiffanybridge** [comment]
Confirming this works on the affected site.

**Comment by cathymcbride** [comment]
And I'm not able to repro with a new site either. Closing as fixed!
