### ISSUE TITLE
Gutenberg: Ensure Facebook and Instagram embeds persist if removed from core

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#45832]
We've introduced some changes to ensure that Facebook and Instagram embeds work on WordPress.com with Gutenberg > 9.0.

- r213709-wpcom
- 522-gh-wpcomsh

These changes modify existing embeds so they continue to appear in the inserter and behave as before. We should include preventative changes to add these embeds in case these embeds are removed entirely.

**Comment by sirreal** [comment]
Looks like this will be fixed by https://github.com/Automattic/jetpack/pull/17192

**Comment by fullofcaffeine** [comment]
We should probably add those to the list of blocks being tested in our upgrade tests, this would warn us the moment the new version gets on edge.
