### ISSUE TITLE
Editor: Facebook update/video/photo link vanishes in Visual mode

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#4583]
Steps to reproduce:
1. Create a new post
2. Paste a Facebook update/video/photo link on its own line

Result: the Facebook link vanishes in Visual mode, but is still present if viewed in HTML mode. The embed does appear in Preview, and once the post is published.

Expected: the Facebook link should display as embedded in the Visual mode.

Browser / OS version: Chrome, Firefox on OS X El Capitan, and the Desktop app.

Here's an example with `https://www.facebook.com/WordPresscom/videos/10153668920298980`
![fb-embed](https://cloud.githubusercontent.com/assets/15944096/14354849/7728b9f6-fd11-11e5-9cd4-2214c7dfc956.gif)

Possibly related to #935 ?

**Comment by aduth** [comment]
Indeed related to #935, though in this case the embed response from the REST API is including the script as a separate property, but is not being used in the rendered output for the editor. The `scripts` response property is [not documented](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/embeds/render/) for the endpoint, which might explain why it was overlooked.
