### ISSUE TITLE
Billing Management: Add/Update support documentation for all new site-level screens (3)

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#45839]
- [x] Find relevant documentation
- [ ] Update relevant documentation

**Comment by fditrapani** [comment]
As far as I can tell, nothing has changed from how it worked before so I don't know if we need to update anything. I also think the directions to the account view are probably simpler than telling people to go to the site they want to make changes to and pick the product there. My vote would be to leave them as is. These are the related screens in case we need to reference this later or still want to make updates:
- [Manage Purchases, Renewals & Cancellations](https://wordpress.com/support/manage-purchases)
- [Edit Payment Details](https://wordpress.com/support/payment/#adding-or-changing-a-credit-card)

While I was browsing I founded an [outdated image of checkout](https://wordpress.com/support/payment/#payments-using-a-paypal-account) we should probably cleanup.

**Comment by michaeldcain** [comment]
Thanks for tracking down these links. Closing the issue.

> While I was browsing I founded an outdated image of checkout we should probably cleanup.

Updated.

**Comment by fditrapani** [comment]
Thanks for updating the screenshot!
