### ISSUE TITLE
Billing Management: Make subscription settings read-only for non purchasers (3)

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#45838]
A site-level `/purchases/` view was added in #45601. For non-purchasers, we should prevent them from being able to navigate to the subscription settings screen and include a notice at the top of the page about why they can't. A similar view can be seen on `/plans/` for non-purchasers:

<img width="1086" alt="Screen Shot 2020-09-22 at 10 25 32 AM" src="https://user-images.githubusercontent.com/942359/93896604-1afd9180-fcbf-11ea-88d6-acc5dafd31e0.png">

**Comment by fditrapani** [comment]
In addition to this, are we also thinking about making the subscription listing not clickable for folks? 

An alternative approach could be to make the settings screen read only like this:

![image](https://user-images.githubusercontent.com/6981253/94494037-320b1a80-01bc-11eb-94de-237d9b3eb14b.png)

**Comment by fditrapani** [comment]
As an alternative, what if we hide the buttons like this (I created a PR for it: https://github.com/Automattic/wp-calypso/issues/45838):

![image](https://user-images.githubusercontent.com/6981253/94510784-98586300-01e5-11eb-860e-f5884374872a.png)
