### ISSUE TITLE
[Mirror issue] Professional Business: Broken Media & Text Block

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#45843]
This issue is mirroring https://github.com/Automattic/themes/issues/2489 (where the issue was originally reported)

---

## Steps to replicate

1. Create a new page
2. Add the Media & Text block

## Result

To be able to use the block.

## Expected

You can't add an image or edit the text on the block. You can't select anything on it.

Here's a screencast showing the issue:

![MediaTextBlockIssue](https://user-images.githubusercontent.com/16104522/93822790-1e4d3a80-fc37-11ea-979c-772bcbf65bc1.gif)

* User report: #24301611-hc

**Comment by cathymcbride** [comment]
Not able to repro currently. Messaging original poster.

**Comment by cathymcbride** [comment]
Sounds like this is happening on a (recently) retired theme. Trying to track that down now.

**Comment by cathymcbride** [comment]
Yes - this is only happening with the "Professional Business" theme which was retired about a year ago. As such, I am closing this issue, but I will leave [Automattic/themes#2489](https://github.com/Automattic/themes/issues/2489) open, so the themes team can address it if they choose.
