### ISSUE TITLE
Premium Blocks: Consider sending users to plan descriptions instead of straight to the checkout.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45853]
If a user clicks on the plan prompt upgrade, we send them straight to checkout. Users may prefer to better know what they're getting, and what their other options are for plans; we could consider sending them to `https://wordpress.com/plans/` instead.

<img width="901" alt="Screen Shot 2020-09-22 at 1 54 16 PM" src="https://user-images.githubusercontent.com/349751/93936689-69b92480-fcdb-11ea-8d76-e915eea686b0.png">

See: pbBQWj-lH-p2

**Comment by davemart-in** [comment]
Thanks @kwight! I agree. I think this one will be somewhat resolved with the introduction of the upgrade panel as well: 180-gh-dotcom-manage
