### ISSUE TITLE
Premium Blocks: More detail required in the checkout for an upgrade.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45855]
Many people going through this funnel may think we’re asking them to pay for access to individual blocks.

We should add additional context to this page to explain that access to all premium blocks is included with their upgrade, and they’ll also received a whole host of other benefits as well.

At minimum, we should include a mention of premium blocks in the “included with your purchase” section for people who land on checkout after clicking the block’s Upgrade button.

See: pbBQWj-lH-p2

**Comment by davemart-in** [comment]
Totally! This one seems related to the other 2 issues you brought up. I think it will be somewhat taken care of once we ship this feature enhancement: 180-gh-dotcom-manage
