### ISSUE TITLE
Editor: Concurrent modification of category list results in JS error, lack of category

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#4585]
I wasn't able to narrow down the exact timing required to reproduce this, but the gist of it is that if multiple people are adding new posts to a site, and they add a new category at the same time it sometimes results in one or more of them getting the JS error below, and their category not being applied to the post (but successfully created).  This is causing sporadic failures in our automated e2e tests.

```
post-editor.6f4b55a….min.js:24 Uncaught TypeError: Cannot set property 'temporaryId' of undefined(anonymous function)
@ post-editor.6f4b55a….min.js:24(anonymous function)
@ vendor.eb1380d….min.js:9onerror
@ build-production.eb1380d….min.js:21reject
@ build-production.eb1380d….min.js:21onmessage
@ build-production.eb1380d….min.js:21
```

**Comment by hoverduck** [comment]
I've created a branch in our e2e test repo with a test script that reproduces the error: https://github.com/Automattic/calypso-e2e-tests/tree/try/reproduce-wp-calypso-category-bug

Clone that branch and run `babel-node --presets es2015 wp-calypso-4585.js` to automatically log in and create a post with a new category.  Run it in the background in a loop to get multiple entries at once.

The README file in that repo documents the environment variables needed for the tests to run.

**Comment by designsimply** [comment]
If triggering this issue requires more than one category at the same time and it's causing problems for automated e2e tests, does that mean more than one automated test is being run and they are both adding a category at the same exact time?

**Comment by designsimply** [comment]
Is the problem still happening for automated e2e tests? If yes, would it be possible to simulate the error by setting up two of the tests to run simultaneously?

**Comment by hoverduck** [comment]
I haven't seen this problem pop up in a while.  I'll go ahead and close this issue and we can re-open it if it starts happening again.  It was always going to be a low priority issue anyway.
