### ISSUE TITLE
Premium Blocks: Empty front-end leaves users confused when they haven't upgraded.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45854]
If a user publishes a premium block without having upgraded, nothing will appear on the front-end for the block – this can be very confusing for a user and offers no direction. Instead, we can add a message for admins only saying that the plan upgrade is needed to see the block (and another convenient link to do that). We've used this approach in the past with widgets needing API setup, for example.

See: pbBQWj-lH-p2

**Comment by davemart-in** [comment]
Thanks for calling this out @kwight! I agree with you. This one should actually be resolved with the deploy of this feature enhancement: 180-gh-dotcom-manage I'm going to go ahead and close this issue out as a duplicate.
