### ISSUE TITLE
Store: Allow accessing media library to upload product images

### ISSUE THREAD

**Issue by nielslange** [Automattic/wp-calypso#45861]
In 24306044-hc, the customer reported being no longer able to access the media library to upload product images. We investigated and discussed this case in p160083335508590-slack-wpcom-support, but couldn't find any evidence that this was ever possible. That said, it might be useful to have this option in place.

#### Steps to reproduce

1. Head over to **My Site → Store → Product → Add New**
2. Click on **Add images**

#### What I expected

The media library popup opens, allowing to upload a new image or select an existing image.

#### What happened instead

The simply media uploader opens, which only allows to upload a new image.

#### Screenshots

<table>
<tr>
<td valign="top" width="50%">Media Library:
<br><br>

<img width="1558" alt="Screenshot 2020-09-23 at 11 25 14" src="https://user-images.githubusercontent.com/3323310/93966669-75662300-fd8f-11ea-9dd6-939b9d5d1b05.png">
</td>
<td valign="top" width="50%">Media Upload:
<br><br>

<img width="1070" alt="Screenshot 2020-09-23 at 11 26 43" src="https://user-images.githubusercontent.com/3323310/93966751-aba3a280-fd8f-11ea-8b27-7748d18aa87a.png">
</td>
</tr>
</table>

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
