### ISSUE TITLE
Layout Picker: back and close button icons are not centered

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#45875]
![image](https://user-images.githubusercontent.com/437258/94020187-a428cd00-fd80-11ea-88e8-d974ad161241.png)

It seems we're using 20x20px icons inside a 24px bounding box, causing the icons to sit high and not centered.

Can we make sure the back and close icons in the top bar of the layout picker are centered?

![image](https://user-images.githubusercontent.com/437258/94020289-c28ec880-fd80-11ea-95c7-f78e5967dd1c.png)

![image](https://user-images.githubusercontent.com/437258/94020316-c9b5d680-fd80-11ea-92c8-0df043d303fe.png)

cc @pablohoneyhoney for spotting originally.

**Comment by yansern** [comment]
HTML is no longer the same as provided in the screenshot but the minor alignment issues remain.

I'm parking this as a simple Good First Issue for @StefanNieuwenhuis during his dev onboarding.

**Comment by Addison-Stavlo** [comment]
I think this is safe to close now since the design picker has been redesigned and is being reimplemented.  As always, feel free to reopen if closing doesn't make sense.
