### ISSUE TITLE
Plugins: can't access manage mode using keyboard

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#459]
Originally raised by @enejb 

Can't navigate using the keyboard into the manage mode on the plugin list view.

Feedback from @lancewillett 

Seems like the span inside the anchor is what causes this — the keyboard focus on the `span` element and not the `a` element.

**Comment by enejb** [comment]
I was able to use the keyboard to successfully activate a plugin. 

Feel free to reopen this if you still find it an issue.
