### ISSUE TITLE
Purchases: Record page views properly in `EditCardDetails`

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#4590]
@scruffian pointed out [here](https://github.com/Automattic/wp-calypso/pull/4555#discussion_r58838326) that we aren't recording page views in `componentWillReceiveProps` in `EditCardDetails`. We should call this method as soon as the data required to render the page is present, which can be either when the component mounts or when it receives props.

**Comment by jeremeylduvall** [comment]
Closed via #5927.
