### ISSUE TITLE
Editor toolbar doesn't follow currently selected block when scrolling the page, with Veggie theme installed

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#45915]
#### Steps to reproduce

Tested on both simple and atomic, and it happens on both

1. Install the [Veggie](https://wordpress.com/theme/veggie) theme
2. Edit a post in the block editor
3. Without scrolling the page, select a block — the toolbar should be in view
4. Scroll the page down — the toolbar doesn't follow the current block, but instead, it scrolls out of the way

#### What I expected

The toolbar should always appear on top of the block that is currently being edited

#### What happened instead

The toolbar scrolls away from the block currently being edited. It seems that the further the page is scrolled down, the further the toolbar scrolls away from the current block.

#### Browser / OS version

MacOS 10.15.6 — Chrome 85, Firefox 81, Safari 14

#### Screenshot / Video

[Original bug report video](https://d.pr/v/sRmfaf/YmDZWml5rj)

[Additional recording](https://d.pr/v/VHFXzs)

#### Context / Source

Reported by @davipontesblog

**Comment by cathymcbride** [comment]
#85 most used theme with >1300 installs

**Comment by davipontesblog** [comment]
User report on #3345765-zen for feedback loop when this gets resolved.

**Comment by yansern** [comment]
This particular issue seems to be fixed when using `fixed` positioning on `.components-popover.block-editor-block-list__block-popover`.

However, since Gutenberg uses `absolute` positioning by default, my suspicion would be finding which parent element as a `relative` positioning when it shouldn't.

![image](https://user-images.githubusercontent.com/1287077/94192161-d9333d80-feae-11ea-81dd-c92b8d2b82e2.png)

**Comment by ciampo** [comment]
I spent some more time investigating the issue, and I think I found the culprit by inspecting the editor

<img width="1792" alt="Markup 2020-09-25 at 14 31 05" src="https://user-images.githubusercontent.com/1083581/94276541-b05f8680-ff48-11ea-947f-7b851a4db42c.png">

![Markup 2020-09-25 at 13 42 26](https://user-images.githubusercontent.com/1083581/94276547-b2294a00-ff48-11ea-8dd8-34e9329f78b8.png)


But the problem is that I can’t find this CSS rule in the Veggie source files: I looked into `style-editor.css`, but the contents of that file seem to be different from what is injected in the `<style>` tag when using the editor (see the second screenshot)

Maybe it’s a caching issue? @cathymcbride Do you know who would know something about this?

**Comment by cathymcbride** [comment]
@ciampo I'm not sure I do? @ianstewart can you perhaps point us in a direction here?

**Comment by sirreal** [comment]
> But the problem is that I can’t find this CSS rule in the Veggie source files: I looked into style-editor.css, but the contents of that file seem to be different from what is injected in the <style> tag when using the editor (see the second screenshot)

We chatted about this via another channel, bringing here for visibility. Gutenberg does some style rewriting which leads to surprising results. What you expect in a CSS file is transformed and added as an inline script:

https://github.com/WordPress/gutenberg/blob/a14ab7f05d55c373b24c153af3c617d8e7a4a090/packages/block-editor/src/utils/transform-styles/transforms/wrap.js

**Comment by ciampo** [comment]
Update: a potential patch has been suggested to the theme dev folks (see pNEWy-dcQ-p2)

**Comment by ianstewart** [comment]
@cathymcbride I'll cc in @jeffikus in here for following along. (Though I see above that we've reported this internally as well.)

**Comment by MaggieCabrera** [comment]
I made [a diff for this](D50543-code), if you want to review it before we deploy

**Comment by ciampo** [comment]
Closing as if was fixed by D50543-code
