### ISSUE TITLE
Nav Unification - implement conditionals for static fallback nav data

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#45910]
Sub Issue of https://github.com/Automattic/wp-calypso/issues/45435

Once https://github.com/Automattic/wp-calypso/pull/45836 is merged we will have a static copy of a basic admin menu which we can use to render instantly as the user loads Calypso.

However, there are certain conditions that determine which items should/shouldn't be shown to a user. These need to be implemented within the "static" data. Placeholders already exist, but the conditional logic needs to be written.

**Comment by getdave** [comment]
@obenland Is it worth tackling this at this stage? It's another level of detail and could take a while.

**Comment by obenland** [comment]
We can probably backload that.

**Comment by mreishus** [comment]
I haven't done all of the different flags, just a couple, but requesting a look+review before sinking more time into this. #46785
