### ISSUE TITLE
Source site editor plugin to start to integrate the MC tool / translation status into the editor.

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#45947]
**Phase 2 of the Patterns Toolkit (PTK) project (pbAok1-1uA-p2)** 

For patterns source sites, we’ll add an editor plugin that will display a link to the Patterns Toolkit MC page for the post/page that the user is editing.

This plugin will be a first step to adding translation management and/or status overviews in the editor.

The plugin will only work for a12s and sites tagged with block-patterns-source-site.

**Comment by ramonjd** [comment]
@autumnfjeld has started her journey into Plugin Paradise here: D50537-code

**Comment by deBhal** [comment]
Fixed in D51037-code
