### ISSUE TITLE
Integrate the Patterns Toolkit into the page layout picker

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#45949]
**Phase 2 of the Patterns Toolkit (PTK) project (pbAok1-1uA-p2)** 

The page layout picker is the interstitial you see before creating a new page.

We want to offer translated page layouts, and improve the workflow for adding new page layouts.

<img width="818" alt="Screen Shot 2020-09-28 at 11 17 06 am" src="https://user-images.githubusercontent.com/6458278/94381299-3adbfc00-017c-11eb-9d69-c561314beeb2.png">

**Comment by autumnfjeld** [comment]
@ramonjd @p-jackson This can be closed right?   
Related PRs/Issues
https://github.com/Automattic/wp-calypso/pull/49860
https://github.com/Automattic/wp-calypso/issues/50608

**Comment by ramonjd** [comment]
Thanks for the ping @autumnfjeld ! Closing.....
