### ISSUE TITLE
Unify the Patterns Toolkit MC tool with the block-layouts tool.

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#45948]
**Phase 2 of the Patterns Toolkit (PTK) project (pbAok1-1uA-p2)** 

Add support for viewing pattern translation status, and quickly browsing a large volume of patterns, and detail views of individual posts/patterns.

**Comment by ramonjd** [comment]
@andrewserong What do you think, could we close this? Or move over to View's backlog?

**Comment by andrewserong** [comment]
Thanks for the ping @ramonjd — we've largely done this one! We can always improve it, but I think the original objective is complete. I'll close it, but let's open up additional issues for features we'd like to add as we encounter them.
