### ISSUE TITLE
Show proper icon in current Site

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#45965]
In the scope of unifying the navigation between calypso and wp-admin we have to make sure that we show a proper icon when:
1) site has no favicon
2) site has favicon

The UI should match between calypso, wp-admin and the designs 
https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=343%3A986&viewport=-5836%2C1756%2C1.047106385231018

Current calypso screenshot
![](https://cln.sh/yVaoNp+)

**Comment by obenland** [comment]
Fix in D50388-code

**Comment by cpapazoglou** [comment]
Deployed r214444-wpcom
