### ISSUE TITLE
Nav Unification - fix layout "jumps" in sidebar as new items load

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#45987]
Currently on `master` when you load Calypso the admin menu sidebar has a "jumpy", staggered loading experience. This means that whilst the menu is interactive early, items may move around under your mouse pointer. This makes for a frustrating UX. See screenshot below.

To fix this we ought to consider adding placeholders to the layout which indicate that items will be "loaded" here. This will avoid layout jumping when the "real" content becomes available.

Also note that some of this will be sorted by:

1. Matching the items in the static data with the API response.
2. Persisting/caching API state to/in browser storage -  https://github.com/Automattic/wp-calypso/issues/45987

#### Screenshot / Video

![Screen Capture on 2020-09-29 at 10-16-09](https://user-images.githubusercontent.com/444434/94539430-1e53c880-023d-11eb-8fb1-68c691d73ee3.gif)

**Comment by getdave** [comment]
cc @sfougnier - not sure how you'd like to resolve this issue but felt I needed to make you aware.

**Comment by obenland** [comment]
We should be able to take care of most (all) jumpiness from menu items being add/removed/changed through additional logic around the fallback menu. Not every site will have a nudge showing, so having that as the only one that introduces a jump should bring us back to parity with the current menu

**Comment by marekhrabe** [comment]
Also jumps are nothing new in that area. The current Calypso menu jumps around too when things like Testimonials are checked against the API. Let's aim to minimize but keep it realistic — some dynamic things will just have to move things around in some cases

**Comment by getdave** [comment]
Ok it sounds like this is already a pretty poor user experience. As long as we aren't degrading that then that is definitely good enough for a prototype.

Let's try and match up the static data. Will be less obvious now browser caching persistence is in place.
