### ISSUE TITLE
Themes: WebPreview should use the pulsating dot loading placeholder

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#46]
![screen shot 2015-11-04 at 15 50 42](https://cloud.githubusercontent.com/assets/4389/10943323/d2acdec2-830b-11e5-98f8-eeb0990ac478.png)

Currently the WebPreview component has the above skeleton, pulsating. That works on the editor, but on themes it's too overwhelming, for two reasons: it defaults full screen, and the theme design can change a lot, breaking the principle of using a skeleton.

So ideally we need to:

1. Change the component to accept a custom skeleton. This is because the component that loads the WebPreview is the one that knows what is going to appear, and decide for the right loader.
2. For Themes, use a pulsating dot (centered), like the one we have on the masterbar when changing sections.

A more generic shape makes more sense in the Themes context given the wide array of varying layouts and design.

**Comment by nylen** [comment]
https://github.com/Automattic/wp-calypso/pull/886 did this.
