### ISSUE TITLE
Billing Management: release site-level subscriptions/subscription settings (3)

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#46014]
We'll keep the `site-level-billing` feature flag for the billing history and payment method issues, but remove their current uses to make it public.

We need to update the coming soon post and drop a note in wpcom-happy-announce on slack.

**Note:**
- we should be careful to test all new site-level functionality again before releasing
- need to be careful when removing the flag from the existing routing, since all of the old possible routes could still be out there. (see [here for the old redirects](https://github.com/Automattic/wp-calypso/blob/99071ff960f798c47587fed0dad992f82f3bbd5a/client/me/purchases/index.js#L145-L172) that we're replacing.)

**Comment by sirbrillig** [comment]
this is where the flag is: https://github.com/Automattic/wp-calypso/blob/99071ff960f798c47587fed0dad992f82f3bbd5a/client/my-sites/purchases/index.js#L24-L27
That file can be modified to only apply the legacy router to some routes when the flag is not enabled.

**Comment by fditrapani** [comment]
Here's a checklist of test cases I ran on [horizon.wordpress.com](https://horizon.wordpress.com):

**Subscription listing: no Subscriptions**
- [x] See blank slate.
- [x] Click on upgrade and go to plans.
- [x] Click on account level views and go to corresponding screens.
- [x] Create a new user and run through all these tasks.

**Subscription listing**
- [x] See all subscriptions.
- [x] Click on different subscription types. 
- [x] Click all account level links.
- [x] Visit account view and click through tabs and links. 

**Subscription setting**
- [ ] View domain, plan, Jetpack Security, and G Suite.
- [x] Toggle auto-renew on, add card, and return to settings.
- [x] Click on payment method, change card, and return to settings.
- [x] Click renew button and go to checkout. Close checkout and go back to settings.
- [ ] Cancel plan
- [ ] Cancel domain

- [x] View with a different user that is not the owner of the product (Read only: all actions hidden)
- [x] See notice when payment method is missing. Click on Renew Now > Cart.
- [x] Visit account view and click through all these tasks.


**Devices**
- [x] Desktop
- [ ] Mobile
