### ISSUE TITLE
Reader: Page break block isn't rendered

### ISSUE THREAD

**Issue by emilylaguna** [Automattic/wp-calypso#46013]
#### Steps to reproduce

1. Go to WordPress.com > My Site > Posts > Add new post
2. Add a paragraph block with some content
3. Add a page break block 
4. Add a paragraph block with some more content
5. Publish the post
6. View the post in the Reader

#### What I expected

The content is separated into pages

#### What happened instead

The page break is ignored, and all the content is rendered

#### Browser / OS version
- Safari 13.1.1 on macOS 10.15.4
- Safari iOS 14.0.1 on iPhone 11 Pro
- WPiOS 15.7 on iPhone 11 Pro

#### Screenshot / Video
Web|Reader web|Reader mobile web|Reader iOS app Dark Mode
---|---|---|---
<img  src="https://user-images.githubusercontent.com/793774/94589876-aedcd980-023a-11eb-8fce-0869a354d9dd.png">|<img src="https://user-images.githubusercontent.com/793774/94589962-cfa52f00-023a-11eb-94b3-ea9495d778f1.png">|<img src="https://user-images.githubusercontent.com/793774/94590130-13983400-023b-11eb-9ad4-79e681d29090.PNG"/>|<img src="https://user-images.githubusercontent.com/793774/94595091-30366b00-023f-11eb-9c42-b504d8f194d4.jpeg" />

* Web: https://emilylaguna.wordpress.com/2020/09/29/next-page/
* Reader: https://wordpress.com/read/feeds/102048168/posts/2938640661

**Comment by davipontesblog** [comment]
I am checking with our teams if this project is still relevant to be kept open. Internal link: p1618406606173800-slack-C02FMH4G8

**Comment by davipontesblog** [comment]
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by taggon** [comment]
The diff for rendering page breaks is ready for review: D63065-code

**Comment by cpapazoglou** [comment]
I did review D63065-code ✅ , let's just wait for the apps division to weigh in.

**Comment by taggon** [comment]
The patch has been shipped. Thanks for your review @cpapazoglou ! 👍
