### ISSUE TITLE
Editor: Add new page breaks with Gutenberg 9.1 RC1

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#46025]
#### Steps to reproduce

1. Make sure your the WordPress site connected to Calypso is set up to use [Gutenberg 9.1 RC1](https://github.com/WordPress/gutenberg/releases/tag/v9.1.0-rc.1);
1. Starting at URL: https://example.wordpress.com/wp-admin/post-new.php?post_type=page;
1. Leave the default blank layout or select another one, then click in the blue "Use <layout name> layout" button in the upper-right corner of the page;
1. Instead of a functioning block editor, an error message is shown (see screenshot). The error seems irrecoverable, effectively breaking the add new page functionality.

#### What I expected

I expect the block editor to load fine with the layout that was selected.

#### What happened instead

The block editor breaks and an error message is shown instead.

#### Browser / OS version

* Firefox Quantum Developer Edition 82.0b4 (64-bit);
* Chrome 85.0.4183.121 (Official Build) (64-bit);
* Ubuntu Linux 18.04.

#### Screenshot / Video

![gb9calypsoissue](https://user-images.githubusercontent.com/81248/94624030-30ecf280-027b-11eb-80f5-30c138a00da3.png)

Clicking the topmost call in the call stack, leads us to the following piece of code:

![error](https://user-images.githubusercontent.com/81248/94625346-297b1880-027e-11eb-84bf-9138bbfdc088.png)

This is where this line is located in Gutenberg's codebase: https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/use-multi-selection.js#L240.

#### Context / Source

This is the error behind our E2E failures [here](https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/39965/workflows/683c7700-0560-41df-acef-67a8dfc5cf21/jobs/105107/tests), the elements can't be found because the block editor doesn't fully load.

I also tried reproducing this issue in a vanilla core WordPress installation running 9.0 RC1 and couldn't, so I suspect there's some interaction between this new version and Calypso that's triggering it.

Finally, I git-bisected from Gutenberg 9.0 to 9.1 RC1, and according to git _(by testing in a sandboxed site using Requestly to map a local dev version of Gutenberg, and using the dev version of React)_, the changes that trigger the issue were introduced in [this](https://github.com/WordPress/gutenberg/commit/9b49a5f00628e58a15158530a199c49d1e47ccd0) Gutenberg commit.

You can see the full backtrace here: https://gist.github.com/fullofcaffeine/469c6e19571322fc12f55c18179abcef
And the React error message here: https://gist.github.com/fullofcaffeine/d74e227aa8de70f0ed82662ca27d7fe8

**Comment by sirreal** [comment]
Fixed in WordPress/gutenberg#25733
