### ISSUE TITLE
WP Migration: let the user know that they can close the import window

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#46043]
#### Steps to reproduce
Start a WP Migration, all the way through the "Import in Progress" screen.
WP Migration requirements:
- Source site is a site not hosted on WP.com/Atomic
- Source site is connected to the user's account via Jetpack
- Target site has WP.com business plan or higher.

#### What I expected
To know if I can close the window and will be alerted when the migration is done.

#### What happened instead
The "Import in Progress" does not provide that information.

#### Screenshot / Video
![Annotation on 2020-09-30 at 14-52-10](https://user-images.githubusercontent.com/844866/94681705-91883800-032c-11eb-9923-ab0776b55e31.png)

#### Additional info
- From what I can tell, we do send emails for success/failure.

**Comment by eidolonnight** [comment]
It would also be good to know roughly how long the import will take. Minutes? Hours? Days?

It doesn't need to be an actual estimate, just a "This may take several hours" or "Go to bed and it'll be ready in the morning".

**Comment by bogiii** [comment]
I was thinking about how we can improve the text on this screen, and I would not touch the heading "Import in progress" and instead add a note on the bottom.

Right after the checklist, I propose something like:

> NOTE: The process of importing does not interrupt the operation of your website. Feel free to continue editing, and once the import is done, you'll receive an email with the result.

@yoavf @akirk, what do you think?

**Comment by yoavf** [comment]
> I was thinking about how we can improve the text on this screen, and I would not touch the heading "Import in progress" and instead add a note on the bottom.

Sounds good.
 
> Right after the checklist, I propose something like:
> 
> > NOTE: The process of importing does not interrupt the operation of your website. Feel free to continue editing, and once the import is done, you'll receive an email with the result.
> 
> @yoavf @akirk, what do you think?

Actually - when migration is in progress, we intentionally block editing the site (since all their content and settings are going to be overwritten). So this issue is specifically about telling the user they can close the window and the migration will keep going.

For some background about how we disable editing, see #40295 (and #38298 before that).

**Comment by akirk** [comment]
For my taste it's a bit too verbose. What about this?

> You do not need to keep this page open. We'll send you a notification when the import has finished.

I think we send both an e-mail and a notification but IMO we don't need to make the distinction.

**Comment by bogiii** [comment]
I've played around, and there is the same case while importing from an XML file.

Probably we have a **winner**.
To be consistent, I'd show the same note.
>You can safely navigate away from this page if you need to; we'll send you a notification when it's done
