### ISSUE TITLE
Nav unification - improve Reader sidebar markup

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#46095]
During our most recent exploration it became obvious that the reader sidebar has some markup issues and the use of classes varies compared to our unified sidebar, causing styling issues.

<img width="450" alt="Screenshot 2020-10-01 at 14 22 21" src="https://user-images.githubusercontent.com/1562646/94813882-dd081800-03f8-11eb-96ba-40a297c73513.png">

In addition to styling and markup issues, there's an issue with too many items in flyout menus. This issue is also being tracked in https://github.com/Automattic/wp-calypso/issues/46094:

>Flyout menus with a lot of items currently also get cut off. This is an issue with the reader in particular. In wp-admin the same can happen if there are too many items in a menu. It just doesn't surface as reader level submenus are uncommon.
One suggestion from design was to limit the number of items shown in the reader submenu to 5 items.

**Comment by getdave** [comment]
Updated this Issue to limit the scope to a single "Issue".
