### ISSUE TITLE
Notifications: Heading blocks need relative sizing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46111]
While alignment works for Heading blocks, their size and styling is all the same when rendered in notifications.

<img width="450" alt="Screen Shot 2020-10-01 at 3 23 26 PM" src="https://user-images.githubusercontent.com/349751/94869371-17be8000-03fa-11eb-9e50-42ea2bf2c3d5.png">

**Comment by kwight** [comment]
It feels like overkill to make them _all_ different sizes; maybe 1-3 can be, then 4-6 are left as they are now (same font size as content, but bold). @sixhours any preferences? Although email manages to look good:

<img width="699" alt="Screen Shot 2020-10-01 at 3 30 14 PM" src="https://user-images.githubusercontent.com/349751/94869854-09249880-03fb-11eb-9b09-bd25df3b7772.png">

**Comment by sixhours** [comment]
> It feels like overkill to make them all different sizes; maybe 1-3 can be, then 4-6 are left as they are now (same font size as content, but bold). @sixhours any preferences?

I think different sizes for 1-4, with treatments on 5-6 so they're still different from the other headings without being too small to read would be a nice-to-have:

<img width="290" alt="Screen Shot 2020-10-02 at 9 45 56 AM" src="https://user-images.githubusercontent.com/2124984/94930210-15a8ff80-0494-11eb-8196-d25daf341397.png">

But yeah, that's probably a holdover from my theming days, and I don't know how many instances of H5 or H6 actually exist out there. :D
