### ISSUE TITLE
Gutenboarding: login has visible box around it

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#46137]
At `/new` flow when unauthenticated, login screen looks like this:

<img width="819" alt="Screenshot 2020-10-03 at 12 19 42" src="https://user-images.githubusercontent.com/87168/94988023-ed440280-0572-11eb-88b6-c9ec0c4ee5f6.png">

It shouldn't have that box around it. Likely from some core component upgrade.

Since the login screen is not in production for existing customers (it's just internal now), this isn't urgent to fix.

cc @Automattic/team-calypso this is a good example of what kind of challenges using `@wordpress/components` brings to us: we should probably start doing more visual diff testing.

**Comment by tjcafferkey** [comment]
Oddly, the `<fieldset>` element is the one generating the visual border, and it's not from any additional styles being added as far as I can tell as this element [by default has this border](https://html.spec.whatwg.org/multipage/rendering.html#the-fieldset-and-legend-elements) and doesn't come from a `@wordpress/components` reference. It's found [here](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/components/signup-form/index.tsx).

This however doesn't explain why this suddenly started happening unless some styles were recently removed. Interested to know why/how this happened but will open a PR to fix this in the meantime.

**Comment by tyxla** [comment]
I'd bet with my dinner that we broke this with #45577.

**Comment by tyxla** [comment]
Thanks for wrangling a PR @tjcafferkey and please do ping me for a review there 😉
