### ISSUE TITLE
Posts pages not loading in Calypso

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#46132]
I haven't been able to reproduce this is on another site yet, but on a site I checked today the Draft Posts page is not loading in Calypso. WP Admin loads draft posts without any issues.

#### Steps to reproduce

Go to URL: https://wordpress.com/posts/drafts/

#### What I expected

I would expect to see draft posts load as on other sites.

#### What happened instead

 It loads a blank page and I am seeing some console errors:

<img width="1519" alt="Console errors" src="https://user-images.githubusercontent.com/30788962/94967102-705e4d80-04cc-11eb-898b-a3030c9b45c7.png">

#### Browser / OS version

Tested on Chrome and Safari.

#### Context / Source

Reported in 16684945-hc
Discussed in p1601669260013000-slack-C02FMH4G8

**Comment by jenlynnemc** [comment]
The user reported this information to us:

"I noticed the problem on October 2 in the morning and I contacted you by chat. On your advice I then used WP Admin and I deleted the last draft, then made a new draft, and still found the same blocking. Today, October 3, I made a new draft, without effect. Then published an article, no problem. When I test the drafts I have either nothing or the message "Sorry, an unexpected error has occurred".

**Comment by pauljacobson** [comment]
This report came up for me, and I tested the Drafts page in my browser. It loads for me:

![Screenshot_2020-10-07 Pages ‹ Association AgurArménie - Biarritz — WordPress com](https://user-images.githubusercontent.com/2912202/95336409-52705e80-08b9-11eb-98c8-f20c8046a61f.png)

Tested with Firefox Developer Edition v82.0b7 and in Brave Version 1.14.84 Chromium: 85.0.4183.121 on macOS 10.15.6

**Comment by sdixon194** [comment]
User replied confirming they're using Chrome 85, which I can reproduce it in as well.

**Comment by mriyazuddin** [comment]
User has replied stating the following. I was able to reproduce this in Chrome (Version 85.0.4183.121 (Official Build) (64-bit)) and Firefox (81.0.1 (64-bit)).

>Ils the samedi problem with Chrome and Firefox.
But not Witherspoon thé ôter site as randoplaisir

**Comment by fashuvo** [comment]
Another report of the same issue in 3478071-zen

In Calypso, user can see the number of drafts but the posts are not visible:

<img width="1363" alt="Image 2020-11-11 at 1 11 10 PM" src="https://user-images.githubusercontent.com/6534920/98780808-8b9f6f80-241f-11eb-87f3-64b30adc8586.png">

I was able to replicate this on Chrome, Firefox, and Safari. The drafts are accessible via wp-admin.

**Comment by bsanevans** [comment]
User reported right above (3478071-zd-woothemes) added the following information:

> I don't know when exactly, probably for a few months. It should have happened shortly after the switch to the new editor.

I separately confirmed, accessing the site as another Editor who has drafts on the site, I **CAN** see drafts in Calypso. So, it looks like a user-specific issue, not a site-specific issue.

**Comment by Nic-Sevic** [comment]
We have a similar case happening here for the posts screen only. It stops when WooCommerce is deactivated. In each post the user has Featured product blocks.
p9F6qB-7jl-p2
4216516-zd-woothemes

**Comment by JoshuaGoode** [comment]
To clarify, it appears Calypso has issues with characters within the post.  This then causes the Post page (published or drafts -- whichever the post belongs to) loads a blank screen.

![Screen Shot on 2021-08-12 at 10:38:02](https://user-images.githubusercontent.com/4887830/129216248-f6807cc2-b03d-4f1e-86a9-a9c57eacf72b.png)

A blank screen appears with the following in the console.

> Error: getUrlFromParts: host missing.

The script it references seems to vary, in a recent example it was referencing `https://edge.fullstory.com/s/fs.js`

On Horizon, `https://horizon.wordpress.com/calypso/evergreen/27502.0a665b01c528ab9620e3.min.js`

![Screen Shot on 2021-08-12 at 10:40:21](https://user-images.githubusercontent.com/4887830/129216659-b84d1baa-2b77-471c-b42a-0e7324837ed1.png)

**Comment by mreishus** [comment]
I was able to fix the issue in the most recent comment (posts page -> host missing) here: https://github.com/Automattic/wp-calypso/pull/55476.
The root cause was posts with thumbnails that had invalid URLs, for example, a url like `?v=123456`. Calypso was assuming a host name would always exist, like `https://example.com/picture.gif?v=123456`. When it was missing, the white screen crash would happen.

I have not checked the other reports, but if they are the same error message, this fix will most likely apply to them as well.

**Comment by JoshuaGoode** [comment]
Confirmed this fixed things up.  Before the fix, I Inspected previous reports. Some were not related to the original issue and those that were were no longer experiencing it as they removed the offending content.
