### ISSUE TITLE
Sharing Buttons: Official Facebook button share count doesn't update automatically

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#46139]
One of our users reported that the official Facebook sharing button that they add using Sharing Buttons in the WordPress.com dashboard does not update automatically to reflect the number of shares a given post has on Facebook.

A manual workaround is to run the links through the [Facebook Sharing Debugger tool](https://developers.facebook.com/tools/debug). This isn't a feasible solution going forward, though.

The site is currently on the Coraline theme, and the only plugin that the user added appears to be [Custom Sidebars](https://wordpress.com/plugins/custom-sidebars/).

Is this an issue that we can address at WordPress.com, or is this more of an issue with the Facebook API?

#### Steps to reproduce

1. Starting at URL: Various links including [this](https://jaxpsychogeo.com/south/ann-adams-polio-patient-artist-who-draws-by-mouth-south-jacksonville-san-marco/) and [this](https://jaxpsychogeo.com/west-riverside-avondale/river-house-riverside-house-rochester-house-part-i/).
2. Load the post, and check the share count in the Facebook sharing button
3. The share count reflects 0 shares
4. Run the post link through the Facebook Sharing Debugger tool, and then reload the post to see the correct share count

#### What I expected

Share counts using the official Facebook button should reflect the correct share count for the post on Facebook. The Official Buttons are selected in _Tools_ > _Marketing_ in the WordPress.com dashboard, here:

![Markup 2020-10-04 at 10 29 50](https://user-images.githubusercontent.com/2912202/95010256-7cfbb680-0630-11eb-8736-57aeb7404d07.png)

#### What happened instead

Instead, the share counts are not updated automatically, and may erratically display 0 shares, or the correct share count at the time.

In a recent post that the user published, the share count was set to 0 until [I ran the post through the Facebook Sharing Debugger tool](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fjaxpsychogeo.com%2Fwest-riverside-avondale%2Friver-house-riverside-house-rochester-house-part-i%2F). It then displayed the correct share count, like this:

![Markup 2020-10-04 at 10 29 02](https://user-images.githubusercontent.com/2912202/95010265-8ab13c00-0630-11eb-8bdd-12582c6679f5.png)

#### Browser / OS version

Tested with Brave Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit) on macOS 10.15.6

#### Context / Source

User's report here: 3324492-zen

**Comment by tbradsha** [comment]
Ran across this in 3348015-zen as well, with shares showing as 0. As noted above, rescraping the data fixes it for a specific post, but that's not sustainable.

Of note, the share button code here on Facebook's site returns a 0 count for a page until scraped, so I suspect it's a Facebook issue:

https://developers.facebook.com/docs/plugins/share-button

Similar to this "fixed" issue:
https://developers.facebook.com/support/bugs/333736334739339/

**Comment by tbradsha** [comment]
Looks like it came up previously as well in Automattic/dotcom-manage#230.

**Comment by tbradsha** [comment]
3370950-zen

**Comment by formosattic** [comment]
1509277-hc

**Comment by dolgelukkig** [comment]
#24893839-hc

**Comment by benchilcote** [comment]
#460735-hc

**Comment by chaitanyamsv** [comment]
#24948211-hc

**Comment by philnick206** [comment]
#3380252-zen

**Comment by philnick206** [comment]
#24931108-hc

**Comment by abcrsol** [comment]
#3419454-zen

**Comment by marutim** [comment]
25002549-hc
- The user says that scraping the URL only works for sometime and they see the shares back to zero.

**Comment by abcrsol** [comment]
3423321-zen

**Comment by obenland** [comment]
Looking at the dates of other user reports and them stopping after October 21st, would it be reasonable to assume that it was a Facebook-side bug that has since been fixed?

**Comment by obenland** [comment]
I'm going to close this for now since the originally reported instances seem to work now. Please feel free to re-open if you come across a new instance.
