### ISSUE TITLE
VideoPress: Unknown Error

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#46146]
For pXkGC-3r3-p2

<img width="796" alt="Tumblr_All-Team__10_2_2020____Automattic_tv" src="https://user-images.githubusercontent.com/1103209/95056887-5c307100-06c3-11eb-951c-973e248707e6.png">

cc @mtias as I know you just worked on it.

**Comment by amamujee** [comment]
I have tried to reload the page, and it does not work either (just FYI)

**Comment by cathymcbride** [comment]
@amamujee is there any information in the console when this happens? And what browser are you using? It's currently loading for me with no issues.

**Comment by mtias** [comment]
Seems to be an issue with private videos, it's returning unauthorized from the API at `https://public-api.wordpress.com/rest/v1.1/videos/Dusei52j` for some people / traces.

**Comment by yansern** [comment]
Unable to replicate this issue here as well.
As this was time-relevant and there is not enough technical error details captured to identify this issue, I'm closing this for now.
