### ISSUE TITLE
Notifications: Block Editor Paragraph Background Color and Text Color Not Applied

### ISSUE THREAD

**Issue by krymson24** [Automattic/wp-calypso#46170]
Paragraph formatting from the block editor is not applied in post notifications. These are all settings available from the toolbar or block settings in the sidebar.

Here are the issues that don't follow the same solution as https://github.com/Automattic/wp-calypso/pull/46019 and https://github.com/Automattic/wp-calypso/pull/45927. You can see the classes applied here in this file `wp-content/lib/class.notification-builder.php`

1. Paragraph background color is applied via a single class, but the style varies, so we can't just add this class to Calypso, since the style being set is dynamic
2. Paragraph text color is applied via a single class, but the style varies, so we can't just add this class to Calypso, since the style being set is dynamic

The approach considered would be to somehow get the styles of a class and transfer those styles to the style attribute of an element. @mmtr Emogrifier's has addressed this problem in some of his recent work.

Editor | Notification
--- | ---
<img width="569" alt="Screen Shot 2020-10-05 at 5 04 19 PM" src="https://user-images.githubusercontent.com/66652282/95131896-e06b0e80-072c-11eb-92e8-880b8f3b9ad3.png"> | <img width="535" alt="Screen Shot 2020-10-05 at 5 04 14 PM" src="https://user-images.githubusercontent.com/66652282/95131913-e7921c80-072c-11eb-9e38-5ebc6c51a127.png">

**Comment by krymson24** [comment]
This might be solved by D50508-code (I've seen the text part, but not the background color part, yet)

**Comment by krymson24** [comment]
I tried to use  D50508-code and see what's outstanding for this ticket, but when I use D50508-code, I get a 500 from https://public-api.wordpress.com/rest/v1.1/notifications/?http_envelope=1&fields=id%2Ctype%2Cunread%2Cbody%2Csubject%2Ctimestamp%2Cmeta%2Cnote_hash&number=10. I don't see the same when the patch is reverted. I'll come back to this when that branch is in a testable/merged state.

**Comment by krymson24** [comment]
If D51569-code works as described, this ticket should be resolved

**Comment by mmtr** [comment]
As noted in D51569-code#1045026, it won't possible to support the block color palettes defined by themes:

> The classes in a color palette are arbitrary: they are defined by the theme and they can use any class name (see [Block color palettes docs](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes)). Since they're arbitrary, there is no way of overriding them. We cannot even run `get_theme_support( 'editor-color-palette' )` in order to create a new palette dynamically, since themes defines their palette during the `after_setup_theme` action ([example](https://themes.trac.wordpress.org/browser/twentytwenty/1.5/functions.php#L563)) but themes are not loaded on fallback contexts when WP.com triggers that action (see `wp-settings.php#L501`). Due do that, I don't think we can properly handle the block color palettes, so these classes should be simply ignored. I only added basic support for `has-background` so any block with a background color will have the same grey color, but at least it doesn't look off due to the padding defined in all `has-background` elements.

**Comment by mmtr** [comment]
Closed by D51569-code.
