### ISSUE TITLE
Notifications: Block Editor Post Body and Font Style Not Applied to Notifications

### ISSUE THREAD

**Issue by krymson24** [Automattic/wp-calypso#46172]
Body and font style from the block editor is not applied in post notifications.

Editor | Notification
--- | ---
<img width="500" alt="Screen Shot 2020-10-01 at 1 06 35 PM" src="https://user-images.githubusercontent.com/349751/94857831-f902be00-03e6-11eb-984c-0233dd0b3811.png"> | <img width="500" alt="Screen Shot 2020-10-01 at 12 58 51 PM" src="https://user-images.githubusercontent.com/349751/94857877-0a4bca80-03e7-11eb-97e1-1fb5079ae2b0.png">

**Comment by kwight** [comment]
Fixed in #46138.
