### ISSUE TITLE
Notices: button text is cut off for multi-line text

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4617]
Flex is causing the button to get cut off. Gets increasingly worse with more lines of text. 

It needs a `flex-shrink: 0;` or something like that.

#### Browser / OS version
Safari 9.0.2

#### Screenshot / Video
<img width="777" alt="screen shot 2016-04-08 at 10 04 02 pm" src="https://cloud.githubusercontent.com/assets/618551/14397617/4f04eeca-fdd6-11e5-94f7-0c0ecce250c2.png">

cc @umurkontaci

**Comment by mtias** [comment]
cc @rickybanister it seems a bunch of the reverts that happened introduced regressions here. Or maybe this was always an issue.

**Comment by rickybanister** [comment]
I believe I added the flex-shrink property for global notices, but perhaps that can just be moved into the `Notice` component. I'll take a look.

**Comment by rickybanister** [comment]
cc @scruffian I think a recent PR of yours reverted some of the work @MichaelArestad and I did on notices and may be contributing. Before merging in a fix for this, let's huddle and make sure we aren't running in circles.

**Comment by rickybanister** [comment]
I've got a fix in place for this, just need to test a bit more and work up a PR.
