### ISSUE TITLE
Cannot edit captions CoBlocks on Atomic

### ISSUE THREAD

**Issue by bsanevans** [Automattic/wp-calypso#46181]
#### Steps to reproduce

1. On an Atomic site, add an Offset Block and add images
2. Toggle captions on
3. Click on the caption of any image to edit it.
4. Notice the menu bar above the caption blinks and disappears
5. Changing tabs brings the menu bar back, but clicking on it makes it disappear again

The issue also happens with Masonry Blocks and Stacked Blocks

Could not reproduce on a Simple site.

#### Screenshot / Video

https://d.pr/i/idQobu

#### Context / Source

21950951-hc

Follow-up waiting at 3378705-zd-woothemes

#user-report

**Comment by WunderBart** [comment]
This seems to be a CoBlocks plugin issue so I moved it upstream: https://github.com/godaddy-wordpress/coblocks/issues/1717

**Comment by WunderBart** [comment]
Closing in favor of https://github.com/godaddy-wordpress/coblocks/issues/1717
