### ISSUE TITLE
Me: Create flux stores for CurrentUser and CurrentUserSettings

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#462]
Originally raised by @ebinnion 

I think two Flux stores: one for CurrentUser and one for CurrentUserSettings would solve this because the CurrentUser store could be updated when the setting response resolves instead of having to do a separate fetch or some sort of direct mutation of the user object.

**Comment by lancewillett** [comment]
Closing as this is obsolete now (not using Flux for state).
