### ISSUE TITLE
Checkout: add identifier for USD in non-US geos

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#46205]
We already include non-USD identifiers for supported currencies that use the $ as a currency symbol (i.e. "C$" for Canadian dollars), but we don't include a USD identifier when a user is in a location that uses the $ and we don't currently support their currency (i.e. Argentinian Pesos).

When a user is outside of the US, we should add an idicator to the amount (i.e. "US$").

**Comment by DavidRothstein** [comment]
See also c/8yG0JNLf-tr (internal link)

**Comment by abemos** [comment]
Hi there, just wanted to follow up and ask about the ETA for this request? @michaeldcain  @DavidRothstein . Thanks!

**Comment by kylemcph** [comment]
Just noting that there is still confusion about this. Another example is #25056033-hc.

**Comment by jartes** [comment]
I also had another example of confusion here 23979794-hc about Argentinian Pesos.

**Comment by michaeldcain** [comment]
Work in progress in D52530-code

**Comment by sirbrillig** [comment]
Requested changes on the diff.

**Comment by carladoria** [comment]
@michaeldcain  or @sirbrillig  are there any updates on this? we still get several requests related to this per day. 
I personally get around 2 per day.

**Comment by michaeldcain** [comment]
@carladoria sorry for the delayed response. The issue should now be fixed in the popover shopping cart and checkout, but additional work will be required to update plans lists and subscription management screens. I'll open another issue to track those changes.

**Comment by carladoria** [comment]
Great, thanks a lot!

**Comment by marianearchimbaud** [comment]
Hi there!! I am not sure if this is the exact same issue, but I wanted to know if it was possible to add this request:
In the pricing page, we find this: https://wordpress.com/pricing/

And some uses are confused about these symbol/currency, as it also means "pesos".
Are we able to be a bit more specif with the currencies displayed here?
As this example? https://d.pr/i/HIrxW9
This issue was reported by a user on this chat, they were confused and asked for a refund as they were not expecting the charge was going to be made in US$

hc-1569496

**Comment by sirbrillig** [comment]
FWIW I _think_ the plans page is managed by @Automattic/martech-decepticons so perhaps they can weigh in here as well. 

> but additional work will be required to update plans lists and subscription management screens. I'll open another issue to track those changes.

@michaeldcain did we ever create a new issue to track the plans page?

**Comment by michaeldcain** [comment]
@sirbrillig: I couldn't find one (might've been closed as part of the backlog cleanup), so I opened a new one: #50064

Although I don't believe that this would cover the logged-out pricing tables from @marianearchimbaud's screenshot. As you said, this needs to be something on @Automattic/martech-decepticons radar. /cc @paulbonahora for help prioritizing that part.

**Comment by paulbonahora** [comment]
@southp, looping you in to add this to the pipeline. Not sure who'd be best to work on this feature.
