### ISSUE TITLE
Block Patterns: Image block pattern includes long column of text

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#46215]
#### Steps to reproduce

1. Starting at URL: Any WordPress.com Simple site
2. Click the + block inserter icon at the top left
3. Click "Patterns"
4. Look at the Image block pattern preview:

![Edit_Page_‹_Global_Styles_Demo_—_WordPress_com](https://user-images.githubusercontent.com/7662449/95252474-0656e880-07eb-11eb-98a6-7b8b7cf02e7c.jpg)

5. Select the Image block pattern to insert it in the page

#### What I expected

To insert a block pattern with images

#### What happened instead

The **Image** block pattern probably isn't meant to have a column of text, and if it is, it shouldn't be so tall and narrow.

#### Browser / OS version

Mac 10.15.7
Firefox 81.0

#### Screenshot / Video

https://d.pr/i/n2JhTD/

#### Context / Source

WordPress.com customer Quick Start session

**Comment by yansern** [comment]
@kathrynwp Do you know which theme exhibits this issue?

It's definitely theme specific as the theme I'm using renders just fine.
![image](https://user-images.githubusercontent.com/1287077/97892276-7bf59c00-1d38-11eb-87a0-1e2c2719bd24.png)

**Comment by yansern** [comment]
**Update: The theme used was Hemingway.**

Thanks @kathrynwp for the swift reply on Slack.


![image](https://user-images.githubusercontent.com/1287077/97895081-fa077200-1d3b-11eb-9a5e-0634daa83bab.png)

**Comment by andrewserong** [comment]
Looks like that pattern's parent block is Layout Grid. Just confirming that the preview looks correct for me on one of the suggested themes (e.g Leven), but the pattern looks like the screenshots in this issue when the Hemingway Rewritten theme is active.

**Comment by andrewserong** [comment]
Ah, after looking more closely, I believe this is to do with the Hemingway theme not supporting full width alignment, but the pattern expects that it's going to be in an environment where that's available. I wonder if the solution for this is to (somehow) add a flag for patterns that some patterns are only going to be available if the current theme supports certain features (like full width). I'll write up a separate issue for this as an enhancement idea for how we deal with patterns.

**Comment by andrewserong** [comment]
Added a separate issue to look at supporting this in #47565.

**Comment by andrewserong** [comment]
A fix for hiding this particular pattern on themes without `align-wide` support has been merged in (#47571). I'll leave this issue open until a new Editing Toolkit plugin version has been deployed.

**Comment by andrewserong** [comment]
This particular pattern is now hidden for sites where the active theme does not support `align-wide`. If anyone looking at this issue needs additional patterns to be hidden from the inserter for this same situation, the solution is for someone (either from 
@Automattic/ganon @Automattic/view-engineering or @Automattic/dotcom-view-design) to add the `requires-align-wide` tag to the relevant pattern. There was a good suggestion in https://github.com/Automattic/wp-calypso/issues/47565#issuecomment-730196910 to automate adding that tag in for patterns that depend on full width alignment, so until we automate it, it should be as simple as adding the tag manually.
