### ISSUE TITLE
Domains: Styles for site domain listing are broken

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#46211]
The styles for the site domain list page seem to have been broken at some point in the last day or so. (We're still digging in to likely candidates.)

#### Steps to reproduce

1. Starting at URL: wordpress.com/home/<your-site>
2. Click on Manage -> Domains

#### What I expected

The page to show a list of domains with attributes displayed horizontally.

#### What happened instead

The listing is vertical (and not aligned consistently).

#### Browser / OS version

MacOS 10.15.5 / Chrome 85.0.4183.121

#### Screenshot / Video

<img width="1088" alt="Screenshot" src="https://user-images.githubusercontent.com/3376401/95245455-6eb9c000-0813-11eb-9ef2-7a08e4d69210.png">

#### Context / Source
HT - @klimeryk noticed an issue while using the domains screen.

**Comment by klimeryk** [comment]
This has been fixed by https://github.com/Automattic/wp-calypso/pull/46213 🙇
