### ISSUE TITLE
Reader: Viewing comments and posting comments is broken on Atomic and self-hosted Jetpack sites

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#46284]
#### Steps to reproduce

1. Visit any post on an Atomic or Jetpack site in the Reader. The post needs to have at least one comment. Example: https://wordpress.com/read/feeds/107218703/posts/2952355248
2. Scroll down to the comments section. It will say "Load more comments (showing 0 of __)"
3. Click that and an error appears at the top right: "Could not retrieve comments for requested post"
4. Also cannot leave a comment from the Reader either, error says: "Sorry, there was an error posting your comment"
5. If you are in the Reader list view viewing multiple posts from multiple sites, if any impacted post is in the list, the "Could not retrieve comments for requested post" error will show at the top right sometimes 

User reported in #3382562-zen and #24700040-hc

**Comment by cathymcbride** [comment]
5 or 6 user reports over the last 24 hours, but seems to affect every JP and atomic site. Bumping to janitorial.

**Comment by sarahfg** [comment]
We are also getting reports of this in mobile. See https://github.com/wordpress-mobile/WordPress-Android/issues/13091

**Comment by JoshuaGoode** [comment]
Encountered this on an Atomic site, 3384596-zen

**Comment by cathymcbride** [comment]
Bumping pri as well.

**Comment by JoshuaGoode** [comment]
Noting I initially had issues reproducing it when I first encountered it.  It appears that owners/admins can see and interact with comments in the Reader when it's their own site but the general public cannot.

**Comment by RealCarFax** [comment]
I received a report of this in #21617350-HC. This user published a blog post talking about it and several other WordPress.com users chimed in in the comments too! https://aguycalledbloke.blog/2020/10/08/oh-i-am-textless/

**Comment by mreishus** [comment]
URL / XHR Request / Response

https://wordpress.com/read/feeds/107218703/posts/2952355248

GET
	https://public-api.wordpress.com/rest/v1.1/sites/179679800/posts/984/replies?http_envelope=1&order=DESC&number=50&status=approved

{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unknown_token","message":"Unknown Token"}}

**Comment by mreishus** [comment]
This may be related to a recent jetpack security change. I am soliciting feedback from the jetpack team and requesting a stop-gap revert. Internal reference: p9dueE-1Zi-p2

**Comment by designsimply** [comment]
Tested and confirmed using the following steps:

To prepare:

* Set up a WordPress.com Business site with plugins installed.
* Make sure the following settings are on in My Site > Manage > Settings > Discussion:
  * "Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment."
  * "Comment author must fill out name and e-mail"
  * "Users must be registered and logged in to comment"
* Make sure the following settings are blank in My Site > Manage > Settings > Discussion:
  * "Comment moderation"
  * "Disallowed comments"
* Follow the site in the Reader from a different user account.

To test:

1. In a web browser, log in to WordPress.com as the user following the site setup earlier.
1. Open the site in the Reader.
1. Try to leave a comment on any post in the site mentioned.

Results: cannot view or submit a comment and the following errors appear. ([47s](https://cloudup.com/cCePGrhjfuW))

> Sorry - there was a problem posting your comment.

> Could not retrieve comments for requested post

> Could not add a reply to this post.

<img src="https://user-images.githubusercontent.com/1119271/95503893-3af0ae80-0969-11eb-8e83-0171f1c90d3a.png" width="270" alt="Screenshot_20201008-131850">
<sup>Tested with WordPress.com Reader using Chrome on Pixel 3 Android 11 and leaving a comment on a WordPress.com Business site (with plugins installed) artindesignco.blog while logged in as user design5279reader.</sup>

I closed https://github.com/wordpress-mobile/WordPress-Android/issues/13091 as a duplicate as it appears this is a problem upstream and is being worked on here.

**Comment by mreishus** [comment]
It looks like a quick revert would re-introduce a non-trivial security vulnerability, so the jetpack team is evaluating how to fix both reader and the security issue.

**Comment by mreishus** [comment]
There's a fix for this now on prod. Thanks to @leogermani and @kbrown9 for working on this and coming up with a solution.

**Comment by rossanafmenezes** [comment]
This user 3384521-zen reports the issue on both Android and iOS and also on desktop but not sure if the desktop app or browser. Asked and waiting for confirmation

**Comment by leogermani** [comment]
Hi @rossanafmenezes , The fix was deployed 13  hours ago. I'm not sure in which timezone ticket comments are being displayed in zendesk but I think it's worth confirming that the issue is still happening or has been fixed but not tested again by the user.

**Comment by kylemcph** [comment]
Another report here - 3384111-zen 

I can confirm comments are now working as expected for this user as well.

**Comment by cathymcbride** [comment]
Closing ...

**Comment by giuliohome** [comment]
I am having a similar issue with the site https://blog.cloudtrooper.net/
where I can read "[Blog at WordPress.com.](https://wordpress.com/?ref=footer_blog)"
I have described my issue here: https://wordpress.org/support/topic/android-app-reply-to-comment/
