### ISSUE TITLE
Notifications: Buttons from the core buttons block are rendered as stacked links.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46292]
Buttons from the core buttons block are rendered as stacked links, instead of as proper inline buttons.

Front-End | Notifications
--- | ---
<img width="466" alt="Screen Shot 2020-10-06 at 3 55 41 PM" src="https://user-images.githubusercontent.com/349751/95268569-71ed8580-07ec-11eb-83de-f2d90d74706e.png"> | <img width="466" alt="Screen Shot 2020-10-08 at 2 30 49 PM" src="https://user-images.githubusercontent.com/349751/95516058-85772880-0973-11eb-9e6c-7caccd242d25.png">

**Comment by kwight** [comment]
This should get solved by D50508-code.

**Comment by krymson24** [comment]
@kwight I'm not sure that's true -- I put up a frontend and back PR for it. Backend is here: D51180-code
