### ISSUE TITLE
Restaurant Theme Using Fallback Annotation Instead of its own annotation.

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#46299]
#### Steps to reproduce

1. Activate the restaurant theme on a WordPress.com site https://wordpress.com/theme/restaurant
2. Headstart the site to add the Restuarant theme demo content

#### What I expected

I expected the site to look like the Restuarant theme demo after headstarting. It used to work, though I can't be sure when I last saw it working.

#### What happened instead

Headstart used the fallback headstart annotation, adding the content seen in this screenshot: https://d.pr/i/5TxRfn

#user-report

**Comment by ramonjd** [comment]
Just to confirm: 

Are you using the RC tool to headstart?

Writing notes for now, but Headstart _does_ set a theme. But it looks like we only do so on blog creation. See: 26bbc-pb 🤔

**Comment by donalirl** [comment]
@ramonjd Yes, using the Headstart tool in the Blog RC

**Comment by ramonjd** [comment]
Possibly related: https://github.com/Automattic/wp-calypso/issues/46993

**Comment by ramonjd** [comment]
This was put on the @Automattic/theam TODO list on May 13, 2020. See: pNEWy-cIgp2#comment-51401

@kjellr Is adding annotation to:

– Fortune
– Adventure
– Restaurant
– Soho

still on the cards, or is there anything Create can do?

Thanks!

**Comment by scruffian** [comment]
cc @jeffikus

**Comment by kwight** [comment]
We're going to focus on pub themes for the Design Selection pod.

**Comment by sixhours** [comment]
Annotations were added in D61755-code
