### ISSUE TITLE
Reader: Cover block image is missing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46298]
The image is missing from Cover blocks rendered in the Reader.

Front-End | Reader
--- | ---
<img width="500" alt="Screen Shot 2020-10-08 at 3 35 35 PM" src="https://user-images.githubusercontent.com/349751/95521167-c70cd100-097d-11eb-9933-a1b1798a065a.png"> | <img width="500" alt="Screen Shot 2020-10-08 at 3 32 54 PM" src="https://user-images.githubusercontent.com/349751/95521178-cd02b200-097d-11eb-80d7-08275c148468.png">

**Comment by kaitohm** [comment]
Another report here: 3746929-zd-woothemes

**Comment by davipontesblog** [comment]
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by taggon** [comment]
Is this still relevant? I found the cover image appears in my Reader.

**Front-end**
![Taggon_on_wordpress_–_The_greatest_WordPress_com_site_in_all_the_land_](https://user-images.githubusercontent.com/212034/118451446-39be0600-b730-11eb-9b50-ca560ef12467.jpg)

**Reader**
![Test_‹_Taggon_on_wordpress_‹_Reader_—_WordPress_com](https://user-images.githubusercontent.com/212034/118451367-24e17280-b730-11eb-8fcb-3a7e59d4494d.jpg)

**Comment by kwight** [comment]
@taggon Feel free to close anything you can't replicate, sure. 👍
