### ISSUE TITLE
Notifications: The image from Cover blocks is missing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46297]
The image from Cover blocks is missing (although the text is displayed fine).

Front-End | Notification
--- | ---
<img width="731" alt="Screen Shot 2020-10-08 at 3 35 35 PM" src="https://user-images.githubusercontent.com/349751/95520502-47323700-097c-11eb-940c-5bcbba18a4c6.png"> | <img width="485" alt="Screen Shot 2020-10-08 at 3 32 17 PM" src="https://user-images.githubusercontent.com/349751/95520513-4d281800-097c-11eb-82d5-dea956332998.png">

**Comment by mmtr** [comment]
Fix ready to review: D52055-code

**Comment by synora** [comment]
The image from the Cover Block appears but pushes the text to the right now. 

![Annotation on 2021-02-15 at 12-26-38](https://user-images.githubusercontent.com/10015451/107977527-42fcd280-6f89-11eb-87c3-9182ab28fcbd.png)

Link to image/gif:https://d.pr/i/ffeArW

**Comment by obenland** [comment]
@kwight Can this be closed? Looks like the fix was merged?

**Comment by kwight** [comment]
Let's close this, as the original reported issue was fixed – I've opened https://github.com/Automattic/wp-calypso/issues/50600 for the poor rendering.
