### ISSUE TITLE
Reader: Columns block content is all stacked.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46290]
All Column block content, regardless of number of columns, is fully stacked.

Front-End | Notifications
--- | ---
<img width="500" alt="Screen Shot 2020-10-01 at 2 25 45 PM" src="https://user-images.githubusercontent.com/349751/94865260-21dc8080-03f2-11eb-8619-ebffab4fe14a.png"> | <img width="1113" alt="Screen Shot 2020-10-08 at 2 02 49 PM" src="https://user-images.githubusercontent.com/349751/95513368-1697d080-096f-11eb-8425-bb7b2602a637.png">

**Comment by worldomonation** [comment]
Still reproducible and bad user experience. This bugfix should be prioritized over new features as users would likely be frustrated trying to figure out why their columns don't render properly.

**Comment by roo2** [comment]
I'm not sure how to approach this and other "block not supported by reader" issues. There is a tradeoff, the more blocks we support:
* The more individual sites will appear differently on reader, I think we want a consistent experience, like an RSS reader or AMP reader, we want to avoid a "myspace" type experience where every blog has its own unique formatting
* It also increases code complexity, we've handled other cases by copying gutenberg code into calypso, which will have to be maintained manually.

I'm not sure if we should support columns in reader or not, I think we need to think about this question before proceeding.
