### ISSUE TITLE
Notifications: The core YouTube embed block is rendered as a literal shortcode.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46295]
The core YouTube embed block is rendered as a literal shortcode in a notification. It should either be a functioning embed, or at least a preview image linking to the post.

Front-End | Notification
--- | ---
<img width="500" alt="Screen Shot 2020-10-08 at 2 57 34 PM" src="https://user-images.githubusercontent.com/349751/95519200-7d21ec00-0979-11eb-8c8a-802d9df5820a.png"> | <img width="500" alt="Screen Shot 2020-10-08 at 3 12 36 PM" src="https://user-images.githubusercontent.com/349751/95519215-84e19080-0979-11eb-8220-e04092be68b1.png">

**Comment by krymson24** [comment]
This should be handled by D51090-code
