### ISSUE TITLE
CoBlocks Carousel Block missing features in Calypso vs WP-Admin

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#46323]
This might be related to something bigger than just this block, but it does affect this block in a big way, so figured I'd start here.

#### Steps to reproduce

1. Starting on a WordPress.com AT site in Calypso, make sure CoBlocks is enabled, and make sure you have a good number of images in your Media Library.
2. Create a new page, and add a CoBlocks Carousel Block.
3. Once added, now try to rearrange the order in which the images appear. The usual flow for this is to click the block, click Media Library, then Edit Gallery. This section does not appear in Calypso.
4. Save/publish the page. 
5. Open WP-Admin - Pages, and open the page in the editor from there.
6. Click the Carousel Block - Media Library - Edit Gallery, and you'll be able to drag and drop items around the carousel from there.

#### What I expected
The Block to function the same in Calypso or in WP-Admin. 

#### What happened instead
Depending on which URL the editor is loaded in, for example:
Calypso: https://wordpress.com/block-editor/page/testing.scosgro.com/2229
WP-Admin: https://testing.scosgro.com/wp-admin/post.php?post=2229&action=edit
The Carousel Block functions differently, and doesn't have all of the features available required to fully modify the block.

#### Browser / OS version
All.

#### Screenshot / Video
WP-Admin view of Media Library - Edit Gallery: 
![image](https://user-images.githubusercontent.com/30731356/95617444-4d79ef00-0a20-11eb-996d-69b6ba985419.png)

Calypso view: 
![image](https://user-images.githubusercontent.com/30731356/95617479-5a96de00-0a20-11eb-872c-c2e1c29a88cc.png)

#### Context / Source
#user-report

**Comment by nerdysandy** [comment]
I can't replicate it anymore. It could also be because with Nav unification we automatically force WP-Admin view on AT sites. Closing it because of that.
