### ISSUE TITLE
Table Block: When aligned left/right at the bottom of the page, it becomes uneditable.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#46339]
#### Steps to reproduce

1. On a WordPress.com simple site, create a new page. Give it a title, and add some content at the top (paragraph block with some text). 
2. On a new line, add a table block. 2x2 works. Fill in the blocks with some content.
3. Click the Table Block - Change Alignment, and align it either to the right or to the left.
4. Once aligned, you'll no longer be able to click inside the content and make changes to it. You can't really click the block at all. It becomes frozen at the bottom of the page, uneditable, until the alignment is removed.  
5. You have to use Block Navigation/Outline at the top to access the block again and remove the alignment. 

#### What I expected
The Block to still remain clickable/editable, even with an alignment set.

#### What happened instead
If the Table Block is the last thing on a page, aligning it to the left or right makes it no longer clickable or editable.

#### Browser / OS version
All

#### Screenshot / Video
![tableblock](https://user-images.githubusercontent.com/30731356/95641193-c3e51400-0a55-11eb-9140-e68ef1f3e5ca.gif)

#### Context / Source
#user-report #painpoint #stresscase #anxiety

**Comment by yansern** [comment]
I am unable to replicate this one.
I have exactly one paragraph block as the first block, and the table block as the second block.

Checking the history for both Gutenberg's align hook and the table block, there hasn't been any recent fixes related to alignment bugs:
- https://github.com/WordPress/gutenberg/commits/master/packages/block-editor/src/hooks/align.js
- https://github.com/WordPress/gutenberg/commits/master/packages/block-library/src/table

From your video, I can see the the block toolbar goes out of place when you align the table, meaning the active focus element was shifted to somewhere else.

If you can still replicate this issue, I suspect it is theme-specific. What theme are you testing this on?

**Comment by scosgro** [comment]
Tested this again after your note, @yansern, and I can no longer replicate. Original test (should have) changed themes a couple of times, but the one I added to the page title was Arcane. 
![image](https://user-images.githubusercontent.com/30731356/98156869-4d3d0a00-1e8d-11eb-928a-a96d3d21107f.png)

It seems to work now though. Can't replicate in any theme.

Closing. Thank you!
