### ISSUE TITLE
Checkout: if renewal started from site-level payments management, change thank-you page to site-level

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#46335]
When you complete a renewal, if you started at the manage purchase page, you end up back there, but the way it works now you end up back at the account-level manage purchase page even if you started from the site-level one.

**Comment by sirbrillig** [comment]
It looks as though the getThankYouUrl function says [if there is a renewal in the cart, go to the hard-coded account-level purchase page](https://github.com/Automattic/wp-calypso/blob/b1fcc753507d43075a887071db8aa9cc235535e1/client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts#L134). We may be able to extend that logic to say, "if we also have a selected site, then redirect to the site-level purchase page instead.

**Comment by michaeldcain** [comment]
In planning, we discussed using the `redirect_to` query parameter on this CTA.
