### ISSUE TITLE
Reader: Slideshow block rendered as bulleted list

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46330]
The slideshow block currently renders as a bulleted list in the Reader.

![image](https://user-images.githubusercontent.com/545779/95625985-1535d900-0a3f-11eb-9c7b-69350503adcf.png)

Expecting it may be difficult to render a slideshow there a simple quick fix could be to update the styles for that ul element to remove the bullets and margin.

**Comment by kriskarkoski** [comment]
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/45085
