### ISSUE TITLE
Premium Content Block: Unable to change "Subscribe" button text

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#46347]
#### Steps to reproduce

1. Starting on a WordPress.com site, start a new post
2. Add Premium Content Block
3. Click into Subscribe to edit the text. It will keep reverting back to say "Subscribe"

#### What I expected

Like the "Log In" button directly next to it, I expected to be able to edit the text of "Subscribe"

#### What happened instead

Instead, the text rapidly reverts to saying "Subscribe" and no changes can be made to what it says.

#### Screenshot / Video

Hard to see in this recording, but in the below gif I highlight the text and hit "Delete" on my keyboard. I also start typing the full word "Hello" several times within the word "Subscribe."

![premium_subscribe](https://user-images.githubusercontent.com/31680407/95688392-d1c2a280-0bd7-11eb-86a1-fd971fd8c503.gif)

#### Context / Source

This is from a #user-report but reproduced by me as well. In the user report, they are trying to change the word Subscribe because it's not localized, and they want it in French.

**Comment by edequalsawesome** [comment]
While this is waiting a fix, this CSS can be used to manually update the button:

```
/* hide subscribe text from premium content button in logged-out view */
.wp-block-premium-content-logged-out-view .wp-block-jetpack-recurring-payments a {
	font-size: 0;
}
/* replace subscribe text from premium content button in logged-out view */
.wp-block-premium-content-logged-out-view .wp-block-jetpack-recurring-payments a:before {
	content: "Your Text Here";
	display: block;
	font-size: 21.6px;
	margin-bottom: 0;
	height: auto;
	width: auto;
}
```

**Comment by kspilarski** [comment]
Same case in 3413911-zd

**Comment by AtrumGeost** [comment]
We got a report here as well:

pbEMJv-cC-p2

**Comment by jmdodd** [comment]
Request to change text here: 3413911-zd

**Comment by apeatling** [comment]
We will address this.

**Comment by ccwalburn** [comment]
Another report here: 25335519-hc

**Comment by apeatling** [comment]
Being fixed in https://github.com/Automattic/wp-calypso/pull/46983
