### ISSUE TITLE
Editor role not showing the option to change post author inside editor

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#46344]
#### Steps to reproduce

1. On a simple or AT site add a new user with the Editor role
2. Accept the invitation and log in to the user account with the editor role 
3. Open a blog post and try changing the author
4. Notice there's not an option inside the editor, but only by using the "Quick Edit" option in the Posts WP Admin.

#### What I expected

To see the option to change the author inside the editor just like on WordPress.org:

![Markup on 2020-10-11 at 09:09:38](https://user-images.githubusercontent.com/3696121/95680766-8097bc00-0ba1-11eb-892d-bf1dda6effb1.png)

According to the user who reported this. This was working a couple of weeks ago on WordPress.com.

#### What happened instead

There's not an option to edit the author inside the blog post unless you have the admin role:

![Markup on 2020-10-11 at 09:11:13](https://user-images.githubusercontent.com/3696121/95680809-c2286700-0ba1-11eb-8632-44ee2280d71c.png)

#### Browser / OS version

Chrome: Version 85.0.4183.121 (Official Build) (64-bit)
macOS: Catalina 10.15.7 (19H2)

#### Context / Source

#user-report

24713391-hc

**Comment by wynwin** [comment]
Another report here 20770788-hc

**Comment by ericamQA** [comment]
**No longer able to reproduce.** 

I was able to add an editor, login as that editor, and change the Author (while logged in as an editor). Screenshot below (with usernames redacted) 

![Editor-Change-Author](https://user-images.githubusercontent.com/44411833/115914026-5f146880-a43f-11eb-935c-2a493171f83e.png)
