### ISSUE TITLE
Media: No media in library when switching source from Pexels

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#46380]
This might be an edge case, but here's the issue I encountered and was able to reproduce on two simple sites.

#### Steps to reproduce

1. Create a new post or page. Add image block and click _Select source > Media Library._
2. In the media modal, click in the top left corner to change source and select _Pexels free photos_.
3. Now click on in the top left corner again and switch back the source to _Media Library_.
4. Note there are no images displayed.
5. I also had an intermittent issue where closing the editor and then opening it again would not clear up the issue - the media library was still empty. In that case, reloading the page would fix it. This did not happen every time though.

#### What I expected
I expected to see the images in my media library when I switch back to that image source.

#### Browser / OS version
Chrome 85.0 / macOS 10.15.6

#### Screenshot / Video
![5r8k3dneNg](https://user-images.githubusercontent.com/4550351/95803807-c3e25e00-0d4c-11eb-8067-a3c349fb0528.gif)

**Comment by cathymcbride** [comment]
@alaczek I was able to intermittently repro this twice by selecting pexels, then google, then media library, in the media library chooser. Each time the media library didn't refresh, I could choose pexels/google, re-choose media library and the images would render. Does this workaround work for you? I also don't see anything in the browser console of use. Do you?

**Comment by flootr** [comment]
I'm going to take a look at this 🔍
