### ISSUE TITLE
Social Icons block: Show more icons: Browse All button shows blocks, not icons

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#46382]
I'm not 100% sure this issue belongs here, so I'm happy to move it elsewhere.

#### Steps to reproduce

1. Create a new post or a page and add the Social Icons block.
2. Click on the **+ button** within the block. Note that only 6 more icons are shown in the popup, even though more are available. 
3. Click the **Browse all** button at the bottom. It will open the left sidebar with the list of all available blocks, not a full list of available social media icons that I expected since I started within the context of Social Icons block.

The same issue is present in Gutenberg (https://github.com/WordPress/gutenberg/issues/26046), although it's less prominent because Gutenberg shows a longer list in the popup.

#### What I expected
I expected to be able to see the full list of available social media icons. If what happens after clicking the "Browse all" button is controlled by Gutenberg, could we display the longer list when the person clicks the **+ button** (basically, could we make the behavior identical as in core?).

#### Screenshot / Video
Here's the popup in question on WordPress.com:
![image](https://user-images.githubusercontent.com/4550351/95809328-3a398d00-0d5a-11eb-9bec-996ac0855746.png)

Here's the same popup in core:
![gwz5AO1HW9](https://user-images.githubusercontent.com/4550351/95809453-897fbd80-0d5a-11eb-90a9-190f4764a527.gif)

Here's the video of the whole issue, and confusion upon landing on a list of all available blocks:
![nfWPHDsJZ0](https://user-images.githubusercontent.com/4550351/95809260-1a09ce00-0d5a-11eb-8d6c-7551c2602d29.gif)

**Comment by obenland** [comment]
@olaolusoga Could this one be a duplicate of https://github.com/WordPress/gutenberg/issues/25474? If not, could you help me understand the difference?

**Comment by Robertght** [comment]
I cannot replicate this anymore, so I'm closing this one, but here are my results after I click on "browse all"

Gutenberg: v11.7.0-rc.1

![image](https://user-images.githubusercontent.com/6737345/136371391-4701ecfa-4aa5-4d05-bbfe-f98bddf5c552.png)
