### ISSUE TITLE
Private page redesign

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#46385]
Update the look and feel of the private site page.

![image](https://user-images.githubusercontent.com/6458278/95815729-09148900-0d69-11eb-9960-1f7644687e8b.png)

Context: 
p1602089529058800-slack-C016JPL5S

**Comment by simison** [comment]
Also needs mobile design.

**Comment by ramonjd** [comment]
closing in favour of https://github.com/Automattic/wp-calypso/issues/46656
