### ISSUE TITLE
 Domain search field doesn't accept first character that is typed

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#46403]
#### Steps to reproduce

1. Starting at URL: wordpress.com/start
2. fill out account information
3. Get to domain search form and type 1 character.

#### What I expected
I expected that the first character would show up in the search field
#### What happened instead
The first character isn't entered, but subsequent characters are entered.
#### Browser / OS version
Chrome / IE for sure
#### Screenshot / Video
https://108974-102822243-gh.circle-artifacts.com/0/wp-calypso/test/e2e/screenshots/videos/can-then-see-the-domains-page-and-can-search-for-a-blog-name--can-see-and-select-a-free-wordpress-com-blog-address-in-results-2020-10-13T14-46-03.mpg

#### Context / Source

This was found by e2e tests and seems to be related to https://github.com/Automattic/wp-calypso/pull/46282

**Comment by klimeryk** [comment]
Thanks for reporting! It looks like there's an already issue reported here: https://github.com/Automattic/wp-calypso/issues/43304

I'm guessing it's the same root issue.
