### ISSUE TITLE
Account: remove pending payment tab

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#46414]
This tab seems to be related to async payment methods that haven't processed. Composite Checkout doesn't support async payment methods, and it's possible that the feature never launched. Let's first query whether any pending payments exist, and if not, remove the tab.

**Comment by michaeldcain** [comment]
Let's start by checking whether or not any async purchases exist. If not, remove the tab. If so…

**Comment by DavidRothstein** [comment]
Some background here -- this seems to be used for async payments where it can take a while for the payment to complete after being initiated:
https://github.com/Automattic/wp-calypso/pull/27978

And (internal link):
p4jECJ-1c2-p2

I'm not totally clear on whether (in the case of a new purchase) the product exists during the interim period before the payment is completed, but I think it doesn't.

Also, as noted in the comment above, the big question here is whether these pending payments are used at all currently...
