### ISSUE TITLE
Jetpack: Plugin updates icon is ambiguous

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#46450]
This icon is shown in the site list when a plugin update is available:

![image](https://user-images.githubusercontent.com/1990037/95988726-39b7f980-0e21-11eb-999d-162c3dac163f.png)

It's not obvious what the icon means, and there is no tooltip or anything to explain it.

User asked about it in 3401596-zen and I wasn't even sure what it meant.

Could we add a tooltip so it's clear what the icon means?

**Comment by cpapazoglou** [comment]
This view is available only for Jetpack self hosted sites and has changed to the following which clearly indicates the "update available"

<img width="1293" alt="CleanShot 2022-10-10 at 16 06 40@2x" src="https://user-images.githubusercontent.com/12430020/194873387-3d47c108-a186-48aa-bcb3-5c15b61501db.png">

Closing this issue.
