### ISSUE TITLE
Widgets Block Editor: Don't show launch banner

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#46465]
> When I tried to preview the “Follow Blog” widget I got the “Your site hasn’t been launched yet…” banner:

![follow-launch](https://user-images.githubusercontent.com/841763/96031635-e87a2b00-0e5d-11eb-8e5c-9636a4432f9c.png)

Via p58i-9wi-p2#comment-47639

#### Steps to reproduce

See p58i-9wi-p2

1. Enable widgets block editor (unlaunched site)
1. From the widgets block editor, add a "Follow Blog" widget.
1. Preview the widget
1. See the "Launch Site" notice

#### What I expected

Show the preview

**Comment by simison** [comment]
I wonder if there's a similar issue with cookie banner loading here, but it's hidden for most of us since we've dismissed it already?

**Comment by ockham** [comment]
IIUC, the following is going on here (broad strokes description):

- The Widgets Block Editor uses the [`core/legacy-widget` block](https://github.com/WordPress/gutenberg/tree/ee0085b9e54ae81e77448bdd7d0e9907ee52df96/packages/edit-widgets/src/blocks/legacy-widget) to render "old-school", PHP-based, widget setup screens (in an iframe). (This is plain vanilla Gutenberg code.)
- The "Follow Blog" widget is such a widget. [Its code](https://github.com/Automattic/jetpack/blob/a62c3e4472ce64cfd613e7945b73ab59f3ff769f/modules/subscriptions/views.php) lives in JP's Subscription module.
- The `core/legacy-widget` block's preview functionality lives [here](https://github.com/WordPress/gutenberg/blob/ee0085b9e54ae81e77448bdd7d0e9907ee52df96/packages/edit-widgets/src/blocks/legacy-widget/edit/widget-preview.js).
- The WP.com launch banner (that is visible in the screenshot) lives in WP.com (both Simple and Atomic (wpcomsh); look for the `"Your site hasn't been launched yet. Only you can see it until it is launched."` string). It does have code to hide it if it's being shown through some sort of preview (e.g. if there's an `ifram`, `preview`, or `theme_preview` query arg).
- It seems like Gutenberg doesn't pass an arg like that when requesting the widget preview for the `core/legacy-widget` block. It _does_ however [pass a `widget-preview` query arg](https://github.com/WordPress/gutenberg/blob/ee0085b9e54ae81e77448bdd7d0e9907ee52df96/packages/edit-widgets/src/blocks/legacy-widget/edit/widget-preview.js#L19-L24).

We should thus be able to solve this issue by adding a check for the `widget-preview` to the launch banner.

**Comment by ockham** [comment]
> I wonder if there's a similar issue with cookie banner loading here, but it's hidden for most of us since we've dismissed it already?

Possible. We should track and investigate separately :sweat_smile:

**Comment by ockham** [comment]
Fixes:
D51439-code (Simple)
538-gh-wpcomsh (Atomic)
