### ISSUE TITLE
Audit experimental features in WPCOM Block Editor

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#46494]
**Master tracking issue**: https://github.com/Automattic/wp-calypso/issues/44251

[WPCOM Block Editor](https://github.com/Automattic/wp-calypso/blob/7511b5335aa7cf6fdb3279dd1dda31c5aff446a2/apps/wpcom-block-editor) is dependant on [experimental](https://github.com/WordPress/gutenberg/blob/1d0eecb53fc3b91b1ad7bd51a368e088243fa8eb/docs/contributors/coding-guidelines.md#experimental-and-unstable-apis) features without a fallback for a scenario where such a feature is not supported anymore. Below is a list of usages that we need to update in this matter:

- [ ] https://github.com/Automattic/wp-calypso/blob/7511b5335aa7cf6fdb3279dd1dda31c5aff446a2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L13
- [ ] https://github.com/Automattic/wp-calypso/blob/2af47bc1bdc9cc7ea7ce3a2cb279b12fe76f74e2/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js#L11

**Comment by WunderBart** [comment]
@Automattic/explorers is this something that you could look into?

**Comment by creativecoder** [comment]
@WunderBart 

Just to be clear, the task is to implement fallbacks for all exerimental features used in the wpcom-block-editor scripts?

I can't commit Explorers owning this at the moment, but I think it might generally fit under the Manage janitor rotation. cc @davemart-in  and @cathymcbride for prioritization.

**Comment by WunderBart** [comment]
> Just to be clear, the task is to implement fallbacks for all exerimental features used in the wpcom-block-editor scripts?

Yes! Generally making the usage of the experimental features safe for us. There's also a chance that [some features will be stabilized with the 5.6 release](https://github.com/WordPress/gutenberg/issues/25786), so let's keep an eye on that.

**Comment by davemart-in** [comment]
Heads up: There are 89 issues in our fix the flows Janitorial queue. Honestly, there is almost zero chance that this get's attention from anyone in the next 3 months if placed there.

From my perspective, Manage Group should assist with issues surrounding Gutenberg blocks that they build, but all other Gutenberg related issues should go to either the Create Group, or the View team. cc @simison @apeatling

**Comment by p-jackson** [comment]
#46666 is a fix for the use of `__experimentalMainDashboardButton` in `iframe-bridge-server.js`

**Comment by sirreal** [comment]
Closing this as of https://github.com/Automattic/wp-calypso/pull/47712 / p4TIVU-9xW-p2
