### ISSUE TITLE
Purchases: Add support link to error messages

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#465]
From @fabianapsimoes:
> There are some issues with cancelling domains, as discussed in p1448022407000626-slack-upgrades. The message displayed is: `Domains registered on WordPress.com cannot be deleted here. You must contact Support and request deletion.` We should update this, so "contact support" links to https://en.support.wordpress.com/contact/.

**Comment by gziolo** [comment]
@fabianapsimoes: #607 fixes root cause of this error message, it doesn't update the message itself. Let us know if we should keep that task open and move to v2.

**Comment by fabianapsimoes** [comment]
Thanks, @gziolo.

We should probably add this link whenever we tell users to contact support. I'd say let's punt this to v2, and make it more general to address all mentions to support.

**Comment by fabianapsimoes** [comment]
Seems all mentions pending links are in this file:
https://github.com/Automattic/wp-calypso/blob/63445d113110dd356dcc63d2f394516122b155b4/client/lib/upgrades/actions/purchases.js

**Comment by spncrb** [comment]
FYI, the links should now lead to wordpress.com/help/contact

**Comment by fabianapsimoes** [comment]
This was fixed in #6439.
