### ISSUE TITLE
Settings: cancelling site deletion should clear site address field

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#46512]
### Steps to reproduce

1. Create a free site you wish to delete
2. Head over to Settings -> Delete site at https://wordpress.com/settings/delete-site/{your_new_site}
3. Delete the site and enter the site address
4. Cancel site deletion and close the modal
5. Open the delete site modal again

### What I expected

The site address field to be empty. This is a safe guard to prevent accidental deletion. If the user cancels I'd expect any input to be wiped in order to preserve the deliberate intent behind typing out the address.

### What happened instead

The input persists.

### Screenshot / Video

![Oct-16-2020 13-21-38](https://user-images.githubusercontent.com/6458278/96205895-656ae900-0fb3-11eb-82aa-3343fd50092c.gif)

### Context / Source

#dogfooding

**Comment by Aurorum** [comment]
PR for this issue in #46538. :)
