### ISSUE TITLE
Audit experimental features in ET/premium-content

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#46523]
**Master tracking issue**: https://github.com/Automattic/wp-calypso/issues/44251
**ET tracking issue**: https://github.com/Automattic/wp-calypso/issues/46489

`premium-content` is dependant on [experimental](https://github.com/WordPress/gutenberg/blob/1d0eecb53fc3b91b1ad7bd51a368e088243fa8eb/docs/contributors/coding-guidelines.md#experimental-and-unstable-apis) features without a fallback for a scenario where such a feature is not supported anymore. Below is a list of usages that we need to update in this matter:

- [ ] https://github.com/Automattic/wp-calypso/blob/477cf569add13e08235ff38a966a15b3f39b3dc1/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/edit.js#L6
- [ ] https://github.com/Automattic/wp-calypso/blob/477cf569add13e08235ff38a966a15b3f39b3dc1/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/edit.js#L92
- [ ] https://github.com/Automattic/wp-calypso/blob/477cf569add13e08235ff38a966a15b3f39b3dc1/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/edit.js#L8
- [ ] https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/edit.js#L12
- [ ] https://github.com/Automattic/wp-calypso/blob/fa9f663d0282a9ba6465d522fff8e8013381bc10/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/index.js#L120
- [ ] https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/color-edit.js#L24
- [ ] https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/login-button/color-props.js#L12

**Comment by WunderBart** [comment]
cc @Automattic/serenity

**Comment by mmtr** [comment]
We currently do not register the Premium Content block when we detect the experimental features are not available: 

https://github.com/Automattic/wp-calypso/blob/6e12fcfbd366a2e8484ec105971c946a97014c31/apps/editing-toolkit/editing-toolkit-plugin/premium-content/index.js#L25-L27

https://github.com/Automattic/wp-calypso/blob/6e12fcfbd366a2e8484ec105971c946a97014c31/apps/editing-toolkit/editing-toolkit-plugin/premium-content/index.js#L119-L122

I noted `__experimentalGetGradientClass`, `__experimentalMoverDirection` and `__experimentalPanelColorGradientSettings` are actually missing in the check above, but likely they will be available in the other 2 checks are available. That's not guaranteed though, so it'll be safe if we check all of them.

**Comment by WunderBart** [comment]
👋 @mmtr, thanks for checking this one out.

> We currently do not register the Premium Content block when we detect the experimental features are not available:

What would happen if a user used the Premium Content block on their site, and then (with the next release) it would get disabled?

**Comment by mmtr** [comment]
If the experimental features become suddenly unavailable with a new release then the block wouldn't be registered. It won't be possible to insert new Premium Content blocks, and existing ones wouldn't work either.

**Comment by WunderBart** [comment]
> existing ones wouldn't work either.

This part is what I'm trying to understand 🙏 - what would be exactly the result of that in editor and front-end in this case? Would the block get removed / broken / etc? What will the user see? Should we let users know that this can happen before they chose to use the block? Thanks for your patience!

**Comment by kwight** [comment]
@WunderBart You can give it a try – I expect it will give the "This block contains unexpected or invalid content." error in the editor, and probably display nothing on the front-end (the same for any block that is present in a post's content, but has no corresponding block registered).

**Comment by sirreal** [comment]
Closing this as of https://github.com/Automattic/wp-calypso/pull/47712 / p4TIVU-9xW-p2
