### ISSUE TITLE
Gutenboarding Horizon: Clean up Starter Designs

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46537]
A quick enhancement for the version of Gutenboarding on Horizon. Let's take the current list of Starter Designs …

![image](https://user-images.githubusercontent.com/545779/96297797-0c04b900-0fb7-11eb-8de3-3d665e6de3e3.png)

And simplify it down to one Starter Design.

![image](https://user-images.githubusercontent.com/545779/96298246-c1377100-0fb7-11eb-8762-6c0c380a731e.png)

The Patterns Toolkit source site for this starter design would be https://seedletblocksdemo.wordpress.com/

**Why?** It's a bit cleaner than our current set which I believe we've only used "just for wiring things up" but also because I think this could be a great start for trialling the components of FSE altogether …

- the Site Editor
- and our premier block-based theme.

One design isn't enough for this screen of course. :) We have some updated Starter Designs that I'd like to try out using the same theme (Seedlet Blocks). I bet we can get a lot of variety with global styles, patterns, and Seedlet Blocks. But how much? Only one way to find out!

That means I'd have to make a new set of _additional_ Starter Design sites for this screen but I first wanted to stub this issue out and start that "clean up" process.

cc @apeatling @jeffikus @iamtakashi

**Comment by apeatling** [comment]
This sounds like a good idea to me @ianstewart. I think we can help out with this in the next sprint.

**Comment by ianstewart** [comment]
Nice — we should be able to have a few more starter design source sites ready by that time as well.

**Comment by ianstewart** [comment]
> One design isn't enough for this screen of course. :) We have some updated Starter Designs that I'd like to try out using the same theme (Seedlet Blocks). I bet we can get a lot of variety with global styles, patterns, and Seedlet Blocks. But how much? Only one way to find out!

Starting the process of filling out this screen by taking some of our popular Starter Designs that may work well with Seedlet Blocks and moving them over to new source sites …

![image](https://user-images.githubusercontent.com/545779/97050713-7ed7dc00-1543-11eb-8abe-07012295e73c.png)

1. https://seedletblocksdemo.wordpress.com/
2. https://bowen371612209.wordpress.com/
3. https://casseltesting.wordpress.com/

I'm going to tweak the header templates a bit at least and will see what kind of mileage I can get out of global styles for bringing some variety here. Also, we'll want to test any set up issues for delivering new patterns-like content in that fashion. I don't think we're setting up the templates/parts post-content in the same way we are with the default post content.

We may wind up needing to create a new front-page template just for these starter designs as well …

https://github.com/Automattic/themes/issues/2679

**Comment by ianstewart** [comment]
**Note:** We’ll know a starter design “works” if these if these things all look the same.

- The thumbnail on the design screen.
- The preview in that fonts screen.
- The site you see in the site editor.
- The site on the front end.
