### ISSUE TITLE
Mixcloud embeds inconsistently appear as URLs

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#46534]
#### Steps to reproduce

1. Open any page or post in the block editor on a simple site
2. Paste in a Mixcloud URL like https://www.mixcloud.com/NTSRadio/recurring-dream-14th-of-october-2020/ which will automatically be converted into an embed block
3. The embed appears in the editor successfully
4. Check the live page
5. The embed will sometimes appear as a plain URL

I am not sure if this is related to having multiple embeds on the page at once, like it was in the user report. I tested this with a variety of Mixcloud URLs, pulled both from the user report and random ones on the Mixcloud site, and the issue happened inconsistently with some (but not all) of the user's and my random URLs. And it's not predictable, as sometimes ones that were not working before will randomly start working, and then ones that were working will then show as URLs, after editing or refreshing the page.

Using the shortcode instead of the embed block appears to work fine.

#### Browser / OS version

Chrome on Mac OS

#### Screenshot / Video

https://d.pr/i/AP7N3E

#### Context / Source

User report in #3411459-zen

**Comment by cathymcbride** [comment]
@lakellie anything interesting in the browser console

**Comment by cathymcbride** [comment]
Adding as searchable text:
SyntaxError:  Unexpected end of JSON input
at player-widget.a958fa2...m.js:8

**Comment by obenland** [comment]
`player-widget.js` comes from mixcloud as part of their embed response.

@lakellie Have you found a way to reliably reproduce this at any point? I wonder if it's a caching issue or something on mixcloud's end about their embed responses.

**Comment by cathymcbride** [comment]
I'm not reproing this anymore. @lakellie if you can't either, then let's close this one!

**Comment by lakellie** [comment]
I could reproduce it reliably at the time, but not anymore! Will close this out 👍
