### ISSUE TITLE
Gutenboarding: /sites/[siteId] API response doesn't contain "site_creation_flow" key under "options" after a site becomes atomic

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46559]
#### Original report:

_So, under the scenario where the user creates a Business site, exits the block editor, installs a plugin (which at this point, converts into an atomic site), goes back to the block editor, the isGutenboarding flag is lost. And that leads to the Launch button not being rendered. Since we're opening Launch for all, we'll not need to rely isGutenboarding flag anymore, but we'll still need a way to determine whether a site has launched or not._

#### Steps to reproduce

1. Create a site via gutenboarding flow (`/new`)
2. Select the business plan
3. Open the network tab in the browser's dev tools
4. Edit the home page in the block editor
5. In the network tab, find a request to the `/sites/[siteId]` API endpoint. Inspect the response, and check that `body.options.site_creation_flow` exists, and contains the value `gutenboarding`
6. Close the editor,  and install a plugin (this triggers the site to become atomic)
7. Edit the home page again in the block editor
8. In the network tab, find a request to the `/sites/[siteId]` API endpoint. Inspect the response. This time, the  `body.options` object doesn't have a `site_creation_flow` key. This causes the checks in Calypso for `isGutenboarding` to return `false`

#### What I expected

The `isGutenboarding` check should be `true` even if the site gets converted to Atomic

#### What happened instead

The `isGutenboarding` check was `false` after switching the site to Atomic

#### Browser / OS version

All browsers

#### Context / Source

API response **before** the site is converted to Atomic:

<img width="1792" alt="Markup 2020-10-20 at 13 39 57" src="https://user-images.githubusercontent.com/1083581/96585464-eee62800-12df-11eb-9b53-07d4d85619c2.png">

API response **after** the site is converted to Atomic:

<img width="1792" alt="Markup 2020-10-20 at 14 09 19" src="https://user-images.githubusercontent.com/1083581/96585438-e68ded00-12df-11eb-9a60-375d8f7c7317.png">

Also — probably not related, but in my investigations, the version of the rest APIs also changed:
- `v1.1` when the site is simple (i.e. `/rest/v1.1/sites/${window._currentSiteId}`)
- `v1.2` when the site is atomic (i.e. `/rest/v1.2/sites/${window._currentSiteId}`)

**Comment by ciampo** [comment]
After investigating the issue, it looks like:
- simple sites make an API call to `/rest/v1.1/sites/${window._currentSiteId}` as expected
- atomic sites make an API call to `/rest/v1.2/sites/${window._currentSiteId}`

Here's a screenshot
<img width="1792" alt="Markup 2020-10-20 at 13 16 53" src="https://user-images.githubusercontent.com/1083581/96579269-dde4e900-12d6-11eb-89e4-9a52beb576ab.png">

The response from version `1.2` of the APIs doesn't include the `site_creation_flow` key under `options`, and therefore, the `this.props.siteCreationFlow === 'gutenboarding'` check returns `false`

**Comment by ramonjd** [comment]
There's some further discussion, and a few wild guesses as to the cause over at p1603193051466500-slack-C0KDTA48Y

**Comment by ramonjd** [comment]
So I was testing this again today. I suspect it's because we're not migrating the option over when we do an Atomic transfer.

When we set the option on the Atomic site via the cli  – `wp option set site_creation_flow gutenboarding` – the option shows.

<img width="488" alt="Screen Shot 2021-02-24 at 8 41 33 pm" src="https://user-images.githubusercontent.com/6458278/108981280-b072d680-76e0-11eb-9d33-4b98ea728a5e.png">

**Comment by ramonjd** [comment]
D57559-code has been deployed.

This means that when you create a new AT site, e.g., ecommerce site via /new, you'll see:

When editing a post on `wordpress.com/page/MY_ATOMIC_WP_STAGING_SITE/7` the API response from `public-api.wordpress.com/rest/v1.2/sites/MY_ATOMIC_WP_STAGING_SITE_ID` will contain `body.options.site_creation_flow = gutenboarding`

So too, when editing a post on `MY_ATOMIC_WP_STAGING_SITE/wp-admin/post.php?post=7&action=edit` the API response from `public-api.wordpress.com/rest/v1/sites/https%3A%2F%2FMY_ATOMIC_WP_STAGING_SITE`  will contain `body.options.site_creation_flow = gutenboarding`

You can also check `wp option get site_creation_flow` via the Atomic site's CLI
```
wp option get site_creation_flow

> gutenboarding
```

@ciampo I think this resolves this issue?

**Comment by ciampo** [comment]
Thank you @ramonjd , the issue is fixed!

1. I created a site via `/new`, purchased a business plan, and installed a plugin to trigger the site to become atomic
2. Successfully checked that the `/sites/$site_id` API response contains the `site_creation_flow` option set to `gutenboarding` for both `v1.1` and `v1.2`
3. Successfully checked that the `wp option get site_creation_flow` command returns `gutenboarding`
