### ISSUE TITLE
Notifications Don't Load on the Site's Front End on Opera - 3rd party cookies?

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#46565]
#### Steps to reproduce

1. Open Opera and log in to WordPress.com.
2. Open the front end of any WPCOM site, such as your site, or even https://wordpress.com/blog/ (mapped from `en.blog.wordpress.com`).
3. Open the notifications sidebar.

#### What I expected

The notifications loaded.

#### What happened instead

The notifications couldn't load.
The request to the notifications endpoint failed with error:
- Code `403`
- Status `authorization_required`
- Message `An active access token must be used to retrieve notifications.`

Looking at the endpoint code, this error happens when the user is not logged in.

#### Browser / OS version

Opera 71
macOS 10.15.6

#### Context / Source

Since the user is correctly logged in, and the notifications load just fine from Calypso, this is likely related to the third party cookies deprecation, with the browser preventing the authentication cookie to be shared between different (sub-)domains.

cc @Automattic/explorers 
Related to 13-gh-dotcom-manage

**Comment by cathymcbride** [comment]
No repro for a fresh install of opera.

**Comment by cathymcbride** [comment]
Updated the title.

**Comment by KokkieH** [comment]
There is an older report of this in #46182

**Comment by cathymcbride** [comment]
Thank you @KokkieH ! I'll close this one in favor of that one.
