### ISSUE TITLE
Reader: follow button doesn't work on some sites

### ISSUE THREAD

**Issue by maxme** [Automattic/wp-calypso#46593]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/feeds/59450691
2. Tap the "Follow" button on top right of the screen.
3. Notice there is an error `Sorry, there was a problem following http://www.thealliterates.com/feed. Please try again.`

It happened to one of our user and I was able to reproduce the same behavior.

#### What I expected

No error.

#### What happened instead

Error, and I'm not following the blog.

#### Browser / OS version

Firefox.

#### Screenshot / Video

<img width="1110" alt="Screenshot 2020-10-20 at 13 48 07" src="https://user-images.githubusercontent.com/40213/96582356-74b3a480-12db-11eb-8b5f-9420a3df3522.png">

#### Context / Source

#user-report

**Comment by bluefuton** [comment]
Hi @maxme! This doesn't appear to be a Calypso bug but a problem with this specific feed. The API is reporting `no_access` which suggests it's associated with a private site. The feed record likely needs fixing. Please could you post to the internal P2 with these details? Thanks!
