### ISSUE TITLE
Purchases: Cancel and Refund for Plan bundled with Domain is broken

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#466]
From @fabianapsimoes:

It seems plan cancellation is also broken. Here's what happens to me:

- bought a new plan with a .co domain included.
- started the cancellation process from `/purchases` and asked to keep the domain:
![screenshot-calypso localhost 3000 2015-11-20 13-59-32](https://cloud.githubusercontent.com/assets/1248436/11300625/e06db720-8f90-11e5-90f7-6df1a85bc3e5.png)
- got a green notice asking me to check my inbox for a cancellation email:
![screenshot-calypso localhost 3000 2015-11-20 14-00-27](https://cloud.githubusercontent.com/assets/1248436/11300632/f1f1fec0-8f90-11e5-8794-f530b8ae256f.png)
- got this email in my inbox:

![screenshot-mail google com 2015-11-20 14-15-09](https://cloud.githubusercontent.com/assets/1248436/11300654/2f1c75dc-8f91-11e5-9cf5-017c8027e23e.png)

- note that the email says _both_ the plan and the domain will be cancelled. This is **not** what I requested.
- when I clicked the link in the email, I got this error in old admin tool (I get the same error if I choose to cancel the domain along with the plan):
![screenshot-wordpress com 2015-11-20 14-11-40](https://cloud.githubusercontent.com/assets/1248436/11300657/3cc6753e-8f91-11e5-9bc5-ded260303147.png)

**Comment by rads** [comment]
Fix is pending in https://github.com/Automattic/wp-calypso/issues/583.
