### ISSUE TITLE
Patterns Toolkit: Use DotcomPatterns as the source site for Page Layouts

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46600]
## The Problem

In Calypso, using the Editing Toolkit Plugin, we make the following screen available to users when they add a new page.

![image](https://user-images.githubusercontent.com/545779/96602610-d1519800-12b8-11eb-93ba-4df87975c422.png)

This page could use a design refresh @rickybanister and @joanrho and the layouts themselves could use a refresh @iamtakashi and @ me. 

This issue is not about those issues. :)

Currently, these layouts arrive in this screen from two different sources.

- Non-homepage layouts are page layouts stored on one source site deployed as Headstart annotations using one workflow stored in one location.
- Homepage layouts are page layouts stored as Headstart layouts stored in themes — meaning another location, and another workflow for deployment.

This results in difficult deployment of patterns and thus fewer new page layouts or improvements shipped here along with difficult debugging and deployment of fixes when new versions of Gutenberg ship.

Additionally, it also means we don't have a method yet of adding the homepage layouts to the Add New Page Screen from the signup flow at WP.com/new.

![image](https://user-images.githubusercontent.com/545779/96603686-dc58f800-12b9-11eb-8c1a-f5396d95e6aa.png)

## Proposed Solution

The title of the issue gives away the proposed solution: use DotcomPatterns as the source site for Page Layouts.

Existing homepage layouts have already been added to, and categorized on that source site here:

https://dotcompatterns.wordpress.com/tag/layout/

Homepage layouts used in theme demo sites and the WP.com/new site can be easily added to DotcomPatterns, tagged as layout, they can be categorized as `home`. All `layout` posts from the source site can be looped through and displayed in their respective categories.

I'm not quite sure how the thumbnails can be handled. If there is still performance issues with live previews we may want to use the source site itself to store thumbnail previews as featured images. This may require updating the Patterns Toolkit API.

cc @apeatling

**Comment by noahtallen** [comment]
> Homepage layouts used in theme demo sites and the WP.com/new site can be easily added to DotcomPatterns, tagged as layout, they can be categorized as home. All layout posts from the source site can be looped through and displayed in their respective categories.

One thing @andrewserong and I talked about yesterday was keeping theme demo sites synced with the patterns site. Do you think we actually need that? Or, could the theme homepages just be defined in the patterns site and updated separately? (And is it ok for the two to get out of sync?) Another idea I had was to copy the page pattern from the theme demo site to the patterns demo site when you run the headstart generate annotations command. Or something like that. Just a way of "deploying it" to the patterns site.

**Comment by ianstewart** [comment]
> keeping theme demo sites synced with the patterns site. Do you think we actually need that?

I don't think so.

> Or, could the theme homepages just be defined in the patterns site and updated separately?

I hope so. :D

> And is it ok for the two to get out of sync?

It's not ideal but it seems much easier to update a theme demo site than our current situation. If an update is made to a theme demo site homepage it's quickly resolved with a copy-paste from the source site for the page layouts. So, out-of-sync problems could be easily corrected manually when they arise. In the future perhaps we could then use the Patterns Toolkit to offer better displays and previews of home pages. "I like this theme but … let's flick over to another homepage to see how it looks." That sort of thing.

Theme demo previewing is almost its own separate issue. Our current theme demo sites are almost too idiosyncratic creating a "how do I make it look like the demo?" problem. I think they're almost never updated — I think we've only been updating them recently in order to resolve the issues we have in using them as sources for this screen. Changes that don't really affect their use as a visual for someone "theme-shopping."

**Comment by noahtallen** [comment]
One thing that @mattwiebe mentioned is that the caching mechanism could be improved for SPT as well. I'm guessing a client-side fetch would work better than the current inline PHP approach, especially for existing pages. That could be part of this project

**Comment by andrewserong** [comment]
Thanks for writing this issue up, Ian, I'm super excited for this to happen!

> I'm guessing a client-side fetch would work better than the current inline PHP approach

+1 to this! Also the API endpoint supports pagination, so depending on a new design for the page layout picker, it'd be awesome to have it default to listing the first say 6 layouts, and as you scroll down, lazy-load the rest of the layouts until you get to the bottom of the list, instead of fetching all at once.

**Comment by ianstewart** [comment]
> have it default to listing the first say 6 layouts, and as you scroll down, lazy-load the rest of the layouts until you get to the bottom of the list, instead of fetching all at once.

I wonder if this could unlock using live previews for the thumbs in the current design / future design work.

It would be especially helpful for the blog page layouts and the homepage layouts that have blog posts on them.

**Comment by davipontesblog** [comment]
There is an added urgency to implement this solution since, currently, the starter designs we show users in Gutenboarding/ new site creation flow are not available anywhere else on our platform once the site is created. So users reach out for support with questions like:
- "Why can't I find the option "Bowen" (insert any other design name here) that I saw during signup?"
- "I am looking for a theme option that I saw during signup and can't find. Please help."

It's hard for Happiness Engineers to support users with these questions too since these homepage layouts aren't available anywhere in calypso.

**Comment by rickybanister** [comment]
@davipontesblog thanks so much for adding a note of urgency here. I'm very excited to make this happen and revamp the layout screen. 

This is a highly ridiculous suggestion, but layouts (and patterns) can be copy/pasted from one dotcom site to another so in order to appease a specific user before we hook things up to an api, we could point them to a demo site or give them paste-able html to get one of those layouts in the meantime.

**Comment by davipontesblog** [comment]
> give them paste-able html to get one of those layouts in the meantime.

that's the route I've been recommending we use as HE's 👍 
p7DVsv-906-p2

**Comment by ianstewart** [comment]
I've added the following home pages to the Patterns site using the Starter Design patterns we've created to coincide with the PR linked above. 

```
Name		Patterns Post URL
alves		https://dotcompatterns.wordpress.com/2020/06/29/alves/
balasana	https://dotcompatterns.wordpress.com/2020/06/29/balasana/
barnsbury	https://dotcompatterns.wordpress.com/2020/06/30/barnsbury/
bowen		https://dotcompatterns.wordpress.com/2020/07/01/bowen/
brice		https://dotcompatterns.wordpress.com/2020/06/30/brice/
camdem		https://dotcompatterns.wordpress.com/2020/06/30/camdem/
cassel		https://dotcompatterns.wordpress.com/2020/06/30/cassel/
coutoire	https://dotcompatterns.wordpress.com/2020/06/29/coutoire/
doyle		https://dotcompatterns.wordpress.com/2020/07/01/doyle/
easley		https://dotcompatterns.wordpress.com/2020/06/30/easley/
edison		https://dotcompatterns.wordpress.com/2020/06/30/edison/
gibbs		https://dotcompatterns.wordpress.com/2020/06/29/gibbs/
leven		https://dotcompatterns.wordpress.com/2020/06/29/leven/
mayland		https://dotcompatterns.wordpress.com/2020/06/30/mayland/
maywood		https://dotcompatterns.wordpress.com/2020/06/30/maywood/
overton		https://dotcompatterns.wordpress.com/2020/06/30/overton/
rockfield	https://dotcompatterns.wordpress.com/2020/06/29/rockfield/
rivington	https://dotcompatterns.wordpress.com/2020/06/30/rivington/
stratford	https://dotcompatterns.wordpress.com/2020/06/29/stratford/
reynolds	https://dotcompatterns.wordpress.com/2020/06/30/reynolds/
vesta		https://dotcompatterns.wordpress.com/2020/06/29/vesta/
```

I've kept the "fancy" names of the homepages, expecting it will make for easier management later. 

Some of these new Layouts — the Restaurant, Blog, and Portfolio ones — are in multiple categories. In other words, a "Restaurant" page can now be listed as a Restaurant page **and** a home page. This should make it easier for users to make more pages and more sites by improving the find-ability of these layouts.

Some of these layouts can even likely be re-purposed as Patterns. I expect that to happen more in the future. We'll take a look when we review the categorization. 

**More To Do**

- **Blocker, up next** Adding "missing" home pages like Seedlet, Spearhead, Exford, etc. that weren't yet Starter Designs.
- **Good to have:** Running some script to sideload all hotlinked images so that every image used is in the patterns site. (Could be done manually, too.)
- **Good to have:** Review the categorization.

cc @apeatling @ramonjd

**Comment by ianstewart** [comment]
Added the remaining set.

```
Name			Patterns Post URL
Seedlet 		https://dotcompatterns.wordpress.com/2020/03/25/seedlet/
Twenty-twenty	https://dotcompatterns.wordpress.com/2019/10/16/twenty-twenty/
Shawburn		https://dotcompatterns.wordpress.com/2019/08/28/shawburn/
Exford			https://dotcompatterns.wordpress.com/2019/08/20/exford/
Morden			https://dotcompatterns.wordpress.com/2019/08/07/morden/
Stow			https://dotcompatterns.wordpress.com/2019/08/01/stow/
Hever			https://dotcompatterns.wordpress.com/2019/07/31/hever/
```

I've left off Brompton and Redhill. I think they should be retired from this list and perhaps removed from the recommended list in the theme showcase while we're at it. I've also not included Spearhead as it does not use a page created in the Editor to display home-page content.

**More To Do**

- Good to have: Running some script to sideload all hotlinked images so that every image used is in the patterns site. (Could be done manually, too.)
- Good to have: Review the categorization.

No content blockers for swapping out the layout sources.
