### ISSUE TITLE
Hide privacy settings for unlaunched sites

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#46629]
pbxlJb-rr-p2#comment-626

> I’m not sure if users would find this as an issue, but the grayed out box in the settings page has the public option selected by default. I get that’s exactly what the V2 attempts to do, but from a user’s perspective who doesn’t know all of that, it looks like by default the site is public.
The text next to the Launch site button says that the site is “private”, and yet the “Public” radio option is selected.
 
<img width="720" alt="screenshot-2020-10-20-at-7 17 49-pm" src="https://user-images.githubusercontent.com/22446385/96656538-64570480-1383-11eb-9b35-0dd8c201354e.png">

**Comment by roo2** [comment]
Following Joan's feedback, we should hide the Coming Soon/Public/Private settings until the site is launched pbxlJb-rr-p2#comment-633

> 1 Removing the “Coming Soon” mode from Settings entirely. Sites will only be public or private. Unlaunched sites will have the public/private options hidden until launch.

**Comment by Aurorum** [comment]
PR for this issue in #46757. :)

**Comment by xpurichan** [comment]
+1 on this, I've had at least a couple of customers confused on why they couldn't change the privacy - without realizing that they had not yet launched their site.

**Comment by roo2** [comment]
Oops I missed the ping to follow up on that community contributor PR to fix this, it needs a rebase from them and then hopefully can be merged or I can create a similar fix for this.

https://github.com/Automattic/wp-calypso/pull/46757
