### ISSUE TITLE
Coming Soon sites aren't being tagged in the sidebar and sites list

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#46628]
Reported here: pbxlJb-rr-p2#comment-626

Coming soon v1 sites show "Private" in the sidebar when a site is selected, but coming soon v2 sites show no indication that the site is not public.

<img width="729" alt="screenshot-2020-10-20-at-5 02 25-pm" src="https://user-images.githubusercontent.com/22446385/96655561-2953d180-1381-11eb-9828-07048aed048f.png">

Coming soon v1 sites also show a "Private" tag when viewing the sites list. But there's no indication that coming soon v2 sites are not public

<img width="190" alt="screenshot-2020-10-20-at-5 03 22-pm" src="https://user-images.githubusercontent.com/22446385/96655610-438daf80-1381-11eb-9440-8d90e4350060.png">

Since coming soon v2 sites are not "Private" in the same way that coming soon v1 sites are, I don't think we should make them show up as "Private" in the UI. I think the best solution is to add a new "Coming Soon" Tag to these two places in the UI.

**Comment by lsl** [comment]
This was done by someone in the original draft PR, split out here to - https://github.com/Automattic/wp-calypso/pull/45894 needs a rebase/retest.
