### ISSUE TITLE
Checkout: use `cartItemShouldReplaceCart` (or similar) to determine if cart items should replace cart

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#46624]
Old checkout had a function called [`cartItemShouldReplaceCart`](https://github.com/Automattic/wp-calypso/blob/766329862555a16ab01dbcc81af122a5445bad03/client/lib/cart-values/cart-items.js#L143) which was used when adding products to the cart. If true, it would clear the cart before adding the new product. New checkout does not use this logic, but it should.

See https://github.com/Automattic/wp-calypso/pull/46248 where this was partially done by clearing the cart before renewals.

**Comment by sirbrillig** [comment]
This is a little tricky because it's not clear where this sort of check should live. There are two types of code (AFAIK) that add products to the cart: the code inside checkout (eg: when visiting a URL that adds a product), and the code elsewhere (eg: when adding a domain to the cart via the domain search form). 

In the old cart manager (`CartData`), which is used by the code outside of checkout, this check is handled inside the cart manager when a product add is requested. In the new cart manager (`useShoppingCart`, which is about to be moved to its own package in #46532), this check is handled outside the cart manager. 

As we deprecate the old cart manager, we should come up with the best place to keep this sort of logic, as well as its dependencies (the function relies heavily on many other functions having to do with the cart and its products). I think it would be sensible to move that logic into the new shopping-cart package, since that package is meant to be a full interface for the WPCOM shopping-cart, but we should keep in mind that adding all of those dependency functions greatly increases the API surface area of the package and I suspect there may be places in calypso which are hard to pull out of their contextual surroundings.

For example, to get the minimum behavior we'd need to move `cartItemShouldReplaceCart` into a package, we'd need to import parts of `lib/cart-values/cart-items` and `lib/products-values`, both of which could probably be moved into the package. We'd also need `shouldShowOfferResetFlow`, which comes from `lib/plans`. So do we just move those functions, or those whole directories? If the latter, which seems more appropriate, how do we deal with dependencies like `isEnabled` from `/config`? It's not an easy question to answer.

First off, I think we should wait until #46532 is merged, and then for the short term we could utilize `cartItemShouldReplaceCart` inside `useAddProductsFromUrl`. We'll still have to figure out how to deal with the above, though, if we hope to have the shopping-cart package more widely used.

**Comment by sirbrillig** [comment]
This is further complicated by the fact that `useShoppingCart`'s functions add arrays of products to the cart all at once, rather than one-at-a-time as in old checkout. Previously when adding each product, we could say "should adding this product cause the cart to be cleared?" but if we wish to have that kind of logic now we'll have to reduce over all the products in the array and the order might matter.

For example, let's say you wanted to add an array of (pseudocode) `[{product_slug: 'domain_reg', is_renewal: true}, {product_slug: 'domain_privacy', is_renewal: true}]` to an existing cart that contained `[{product_slug: 'value_bundle', is_renewal: false}]`.

With our hypothetical change applied that reduces over the product list, the `domain_reg` product would cause the cart to clear, since it is a renewal. Then the `domain_privacy` product would be added because even though it's a renewal, privacy is explicitly allowed. You'd end up with `[{product_slug: 'domain_reg', is_renewal: true}, {product_slug: 'domain_privacy', is_renewal: true}]`.

However, if the items to be added were reversed: `[{product_slug: 'domain_privacy', is_renewal: true}, {product_slug: 'domain_reg', is_renewal: true}]` the result would be quite different. The privacy product would be added to the cart with the existing plan, since privacy products do not clear the cart, then the `domain_reg` product would be added, clearing the cart. The result would be `[{product_slug: 'domain_reg', is_renewal: true}]`.

Instead we probably need to have rules that can be applied to arrays of products rather than individually. We could say, if any product that's going to be added would cause the cart to be cleared, clear the cart and then add all the requested products. That wouldn't prevent creating invalid carts, however, because you could actively request an invalid set of products together; it only guards against combining products with the existing cart. Maybe that's sufficient for our purposes?

**Comment by sirbrillig** [comment]
I realized that if we do not consider the jetpack side of things, there's very little we need to import to get this behavior to work. I've implemented it inside the `shopping-cart` package in https://github.com/Automattic/wp-calypso/pull/47978

Also, as of recent changes, the missing jetpack logic is actually pretty simple. It says, "if you add a Jetpack plan to your cart, erase anything else that was in the cart". Adding this to the `@automattic/shopping-cart` package, however, is still not trivial because identifying a jetpack plan (and not a jetpack _product_) is very complex and requires a lot of hard-coded lists currently in calypso.

It seems to me that it's not very common for a cart to contain a product that's not a jetpack plan, and then to have a jetpack plan added, so maybe this isn't such a big issue?

**Comment by sirbrillig** [comment]
For reference, the check was added in https://github.com/Automattic/wp-calypso/pull/6029 and the [commit message](https://github.com/Automattic/wp-calypso/pull/6029/commits/680da15d221f7c487e2dad6ebac430b9c4f20652) ("Add a check to clear the cart if adding a jetpack plan - there should only be one jetpack plan in the cart at one time") seems to imply that it was added to prevent more than one plan from being added to the cart at the same time, which presumably is already handled by the shopping-cart endpoint the way it is for regular plans. If that's right, then this check may be unnecessary after all.

**Comment by sirbrillig** [comment]
Ping @monsieur-z and @rcanepa since you seem to have worked on Jetpack plans in checkout recently. Do you know if this guard that clears the cart when adding a Jetpack plan is important?

https://github.com/Automattic/wp-calypso/blob/0a218d784c690619c4e6dfbc82a37b31e57a3305/client/lib/cart-values/cart-items.js#L159

**Comment by monsieur-z** [comment]
> Ping @monsieur-z and @rcanepa since you seem to have worked on Jetpack plans in checkout recently. Do you know if this guard that clears the cart when adding a Jetpack plan is important?
> 
> https://github.com/Automattic/wp-calypso/blob/0a218d784c690619c4e6dfbc82a37b31e57a3305/client/lib/cart-values/cart-items.js#L159

@sirbrillig, my guess is that it was added to prevent people from buying multiple Jetpack plans, since each plan includes pretty much all the features of the plan below.

**Comment by rcanepa** [comment]
What @monsieur-z said is correct. We didn't want to allow users to purchase more than one plan or a combination of a plan and products.

**Comment by sirbrillig** [comment]
Cool. Thank you! I think that's probably best handled on the backend as it is for regular plans and other invalid purchase combinations. I can't link to it here, but `create_from_js_cart` does some of that. For wpcom plans, that's actually handled in the plan object itself by `modify_cart_after_adding_product`. Until we have Jetpack plans being added using this function it's hard for me to say if that same functionality exists for them (though it looks like I should be able to test when https://github.com/Automattic/wp-calypso/pull/48001 is deployed) but if not it should be easy to add.

**Comment by sirbrillig** [comment]
I tested and can confirm that the backend already prevents adding multiple Jetpack plans. If you add two plans to the cart, the response will have only one. 

However, I am able to add a Jetpack plan and a Jetpack product at the same time:

<img width="497" alt="Screen Shot 2020-12-03 at 6 08 47 PM" src="https://user-images.githubusercontent.com/2036909/101099455-a6828100-3592-11eb-8094-40a6671d43e2.png">

So it looks like we'll need to add a guard for that.
