### ISSUE TITLE
Edit Payment Plan (Email Tab): Change "Learn More" Link

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#46632]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/earn/ on a site with Premium Content
2. Click on the "Manage your premium content" card
3. Click on Payment Plans
4. Edit a plan
5. Click on Learn More

It leads to https://wordpress.com/support/wordpress-editor/blocks/payments/ but this support doc contains no information about using email with the Premium Content block. A better doc to link to would be this:

https://wordpress.com/support/paid-newsletters/

because it describes that feature.

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/30727666/96677202-d5fe7500-13ba-11eb-8172-fdeac69bef78.png)

#### Context / Source

#dogfooding

**Comment by Aurorum** [comment]
PR in #48520 :)
