### ISSUE TITLE
Prevent showing title and description when sharing coming soon v2 site on social media

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#46630]
reported here pbxlJb-rr-p2#comment-626

> When I shared my coming soon v2 site in Facebook, it pulled the home page title and description. The v1 version does not do that. We probably shouldn’t let that happen?

<img width="228" alt="screenshot-2020-10-20-at-6 01 51-pm" src="https://user-images.githubusercontent.com/22446385/96657043-7d13ea00-1384-11eb-8a7f-38c8825471af.png">

**Comment by simison** [comment]
Can we simply unregister these `jetpack_og_tags` actions for coming soon page, just like we unregister "follow page" action and some other things like that?

https://github.com/Automattic/jetpack/blob/9979795c58f579b4740296c37af956d496029273/functions.opengraph.php#L14-L15

**Comment by ramonjd** [comment]
> Can we simply unregister these jetpack_og_tags actions for coming soon page, just like we unregister "follow page" action and some other things like that?

Ah thanks for the tip! So if we unregister the og tags, this meta data won't appear

```

<meta property="og:type" content="website" />
--
  | <meta property="og:title" content="sausageatomictestqwe123qwe123" />
  | <meta property="og:url" content="https://sausageatomictestqwe123qwe123.wpcomstaging.com/" />
  | <meta property="og:site_name" content="sausageatomictestqwe123qwe123" />
  | <meta property="og:image" content="https://s0.wp.com/i/blank.jpg" />
  | <meta property="og:locale" content="en_US" />
  | <meta name="twitter:text:title" content="Home" />
  | <meta name="twitter:image" content="https://s0.wp.com/i/webclip.png" />
  | <meta name="twitter:card" content="summary" />
  | <meta name="twitter:description" content="Visit the post for more." />


```


And FB will look at the title and description head tags? Just checking! We can test this.
