### ISSUE TITLE
Collapse Sidebar: keep the same state across wp-admin / calypso

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#46645]
#### Steps to reproduce
**Scenario 1**
1. Starting at URL: wp-admin
2. Collapse the sidebar
3. Click a calypso link (eg Posts)
_Result: The sidebar is expanded_

**Scenario 2**
1. Starting at URL: wp-admin
2. Click a calypso link (eg Posts)
3. Collapse the sidebar
4. Click a wp-admin link (eg Settings)
_Result: The sidebar is expanded_

#### What I expected
I expect that the collapse status of the sidebar is consistent when navigating in calypso <-> wp-admin.

#### Suggested solution
**Scenario 1**
1. When in wp-admin, add a querystring in each calypso Url (eg `https://wordpress.com/posts/cpapazoglousandbox.wordpress.com?sidebar-collapsed=1`) declaring the sidebar status. The status is saved in a `wp-settings-` cookie by the `setUserSetting` function in `wp-admin/js/common.js`
2. Landing in calypso use the above querystring so that we update the state accordingly and let `getSidebarIsCollapsed` return the correct result.

**Scenario 2**
1. When in calypso, add a querystring in each wp-admin Url (eg `https://cpapazoglousandbox.wordpress.com/wp-admin/options-general.php?sidebar-collapsed=1`) declaring the sidebar status. The status can be retrieved from `getSidebarIsCollapsed` selector.
2. Landing in wp-admin use the above querystring so that we trigger a click in `#collapse-button` 

We have also a separate task for persisting the state in Calypso #51703

### Progress
- [x] **Calypso:** Save/  read sidebar state to / from `calypso_preferences` User attribute (https://github.com/Automattic/wp-calypso/pull/51785)
- [x] **WP Admin:** Read sidebar state in WP Admin for SIMPLE sites https://github.com/Automattic/jetpack/pull/19520
- [x] **WP Admin:** Save WP Admin state to `calypso_preferences` User attribute https://github.com/Automattic/jetpack/pull/19520
- [x] **WPCOMSH:** Read sidebar state in WP Admin for ATOMIC sites  673-gh-Automattic/wpcomsh

**Comment by getdave** [comment]
We will come back to this based on feedback from user testing.

**Comment by cpapazoglou** [comment]
One idea is to save / retrieve the sidebar collapse state in a user meta option as mechanism to have wp-admin and calypso in sync.

**Comment by obenland** [comment]
This information is saved in [user settings](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/option.php#L1056), which itself is [just an abstraction of user meta](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/option.php#L1210).

We could go a similar route as we did with the admin color scheme. Unfortunately it would be hard to keep the entire `user-settings` array in sync, so we would register our own user meta field and propagate its content to the user settings, whenever it gets updated.

To get the information in Calypso, we could extend the `meta` field in the `/me` API endpoint and pass that information there.

**Comment by cpapazoglou** [comment]
> We could go a similar route as we did with the admin color scheme. Unfortunately it would be hard to keep the entire user-settings array in sync, so we would register our own user meta field and propagate its content to the user settings, whenever it gets updated.

The main difference between these two implementations will be that color-scheme may change only from calypso and will be propagated to all sites whereas the expand / collapse state may be changed either from calypso, wpcom simple or atomic.

> To get the information in Calypso, we could extend the meta field in the /me API endpoint and pass that information there.

In case a user changes the state of /wp-admin in their atomic site how will this change be propagated to the /me API endpoint? I believe we should also create a client updating the /me API endpoint for atomic sites?

**Comment by obenland** [comment]
> how will this change be propagated to the /me API endpoint?

We can add the information to the `meta` field by calling [`get_user_setting()`](https://developer.wordpress.org/reference/functions/get_user_setting/).

**Comment by jerrysarcastic** [comment]
Also reported in the WordPress.com public support forums:

- https://wordpress.com/forums/topic/unified-navigation/page/5/#post-3655386
- https://wordpress.com/forums/topic/unified-navigation/page/5/#post-3655419

**Comment by cpapazoglou** [comment]
### How should we deploy this feature?
Since, we rely on Jetpack Automattic/jetpack#19520 for updating the sidebar state while in WP Admin this feature won't be fully released till the next Jetpack Release on **May 4, 2021**. In my opinion, we have the following options:

- Deploy the Calypso PR, which just persists the state in `calypso_preferences`. Then wait till Jetpack Release on **May 4, 2021** and then deploy Jetpack & WPCOMSH.
- Deploy only the Calypso PR and the Jetpack WPCOM counterpart. This will fully sync Calypso with Simple sites.
- **My preference: ** Deploy only the Calypso PR , the Jetpack WPCOM counterpart and WPCOMSH. This will fully sync Calypso with Simple sites and will also update the state on Atomic (from Calypso to Atomic). It won't update the state from Atomic to Calypso though, which doesn’t work now too so it won't be a regression.


PS: I would prefer not trying to put all Jetpack code in WPCOMSH in order to deploy now. This is not crucial fix to do so.

**Comment by obenland** [comment]
> I would prefer not trying to put all Jetpack code in WPCOMSH in order to deploy now. This is not crucial fix to do so.

Agreed. Let's just ship what we have so when Jetpack gets updated on Atomic it just works.
