### ISSUE TITLE
Nav unification - allow sidebar to be scrolled (while maintaining flyout menus)

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#46643]
Note: This is a separate issue for a task that was previously part of https://github.com/Automattic/wp-calypso/issues/46094.

--

We recently merged the first iteration of flyout menus in https://github.com/Automattic/wp-calypso/pull/46046#issuecomment-702107645. One of the known issues, that we'll have to address next:

#### Scrolling inside the scrollbar vs scrolling the sidebar with the page

Right now in Calypso the sidebar container is `position:fixed` and it's overflow content (i.e. more nav items than screen height) is scrollable. This is achieved by adding `overflow:auto` to the sidebar. The issue is that `overflow:auto` prevents overflow content i.e. the flyout from being visible. 

We removed the `overflow:auto` on the sidebar for flyout menus to be visible in the nav unification prototype. This has two side effects: a) the sidebar container isn't scrollable anymore and b) when using the site switcher, the overflow is visible when selecting a site. 

wp-admin gets around the first issue by not having a scrollable sidebar container but instead adjusting the sidebar positioning via JS based on scroll state. The second issue is not present in wp-admin as there's no in-page site switcher.

**Comment by cpapazoglou** [comment]
After merging #46689 we just need to make the transition from the site-switcher back to the menu smoother by hiding the overflowing menu till transition is over

This is what is happening currently:
![SS 2020-11-02 at 15 45 28](https://user-images.githubusercontent.com/12430020/97875024-82791900-1d22-11eb-8ab4-cacee5f3efe4.gif)

**Comment by getdave** [comment]
> After merging #46689 we just need to make the transition from the site-switcher back to the menu smoother by hiding the overflowing menu till transition is over

Should we make a dedicated Issue for that so it's easier to track what is left to complete? Or does it fit nicely within this Issue?

**Comment by cpapazoglou** [comment]
Done [Transition from the site-switcher back to the menu animation](https://github.com/Automattic/wp-calypso/issues/47019#). Updated the master issue too.
