### ISSUE TITLE
Update private page styles

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#46656]
Sites marked as private currently show the following grey/blue screens for logged-in and logged-out (or non-) WPcom users. Let's update the styles to our updated onboarding styles that better align with our brand and marketing updates and also simplify the copy. Some before/after mockups:

**Logged-out private page (current + proposed):**
<img width="2504" alt="privatesite-loggedout" src="https://user-images.githubusercontent.com/204742/96773418-b7d84b00-13a1-11eb-8d0a-480ff971edc4.png">

**Logged-in private page (current + proposed):**
<img width="2510" alt="privatesite-loggedin" src="https://user-images.githubusercontent.com/204742/96773438-bdce2c00-13a1-11eb-8b08-a0cb6250cd0e.png">

**Comment by roo2** [comment]
@joanrho I've got a diff up to update these pages D52924-code

**Comment by ramonjd** [comment]
I've updated the diff with some design changes and a light refactor

**Comment by joanrho** [comment]
@ramonjd Thanks, but I'm not able to test that diff. Are you able to provide updated screenshots of what it looks like?

**Comment by ramonjd** [comment]
@joanrho No worries! 

I did update the screenshots in the description of D52924-code. I tried to address as many design concerns as I could in this round.

Here they are:

**Logged out**

<img width="498" alt="Screen Shot 2020-12-17 at 7 43 14 pm" src="https://user-images.githubusercontent.com/6458278/102726017-4c920180-436f-11eb-88e8-ca08cc10af4d.png">


<img width="1178" alt="Screen Shot 2020-12-17 at 7 43 05 pm" src="https://user-images.githubusercontent.com/6458278/102726015-4865e400-436f-11eb-89b2-d6ea13856f30.png">


**Logged in**
<img width="498" alt="Screen Shot 2020-12-21 at 9 29 18 am" src="https://user-images.githubusercontent.com/6458278/102725992-22d8da80-436f-11eb-9963-0e5a1f626593.png">

<img width="1181" alt="Screen Shot 2020-12-17 at 7 42 35 pm" src="https://user-images.githubusercontent.com/6458278/102726000-2ec49c80-436f-11eb-87e9-6a17dfb5e34b.png">

<img width="1178" alt="Screen Shot 2020-12-17 at 7 42 43 pm" src="https://user-images.githubusercontent.com/6458278/102725996-2bc9ac00-436f-11eb-9912-fe779ff394a9.png">

I mentioned it in the diff also, I'm hesitant to modify the admin bar default styles. In my opinion it should be consistent across the site.

We should target the admin bar itself I think if we want to change its style or behaviour. Will this be targeted in the nav unification project I wonder?

**Comment by ramonjd** [comment]
Before we decide to go live with this it would be helpful to give HEs a heads up. It's a nice, but dramatic change 👍

**Comment by ramonjd** [comment]
Merged and deployed.

If things go well, should we also think about updating the Atomic private page over in `wpcomsh` as well?

**Comment by ramonjd** [comment]
This change was reverted.

p1610592959000800-slack-C02AVAR9B

**Comment by ramonjd** [comment]
I think we need to ditch the admin bar. Trying to add it caused major issues and the current private page doesn't use the admin header.

<img width="1214" alt="Screen Shot 2021-01-14 at 2 34 03 pm" src="https://user-images.githubusercontent.com/6458278/104541342-8e178300-5675-11eb-833b-aa1206083351.png">

**Comment by ramonjd** [comment]
We'll also need to come up with a way to do a pre-commit test for this page before we proceed

See pbxlJb-C3-p2#comment-813

**Comment by ramonjd** [comment]
Version without admin bar: D55337-code

**Comment by inaikem** [comment]
Would it be possible to add a variation of the "request access" link for non-logged-in users? 

It's not immediately apparent how folks can gain access with just the "login / start your website" buttons on the top right of the page (desktop).

**Comment by ramonjd** [comment]
> Would it be possible to add a variation of the "request access" link for non-logged-in users?

Hi @inaikem 

The page works the same way as the previous page. 

Once the user logs in, they should be redirected back to the private page and see this:

<img width="931" alt="Screen Shot 2021-02-04 at 7 49 34 pm" src="https://user-images.githubusercontent.com/6458278/106867869-38894000-6722-11eb-8b06-24067c45c3cd.png">

**Comment by inaikem** [comment]
Sorry Ramon, I should have been clearer. My meaning is that the "Build a website" text and login/sign-up buttons don't quite make it clear to logged-out/non-WPcom users that they need to login/sign-up to request access. They almost look like a separate call to action.

I'd like to suggest we look at adding to the copy for the logged-out screen, making it something closer to the following: _"This site is currently private. To request access, you'll first need to log in to WordPress.com."_

For context, I landed on the logged-out version of the page while in chat earlier this week and was momentarily baffled on my next step!

**Comment by ramonjd** [comment]
> I'd like to suggest we look at adding to the copy for the logged-out screen, making it something closer to the following: "This site is currently private. To request access, you'll first need to log in to WordPress.com."

Ah, makes sense 🙇 

Thanks for the tip. I think that's pretty reasonable suggestion!

What about something like this?

<img width="1251" alt="Screen Shot 2021-02-04 at 8 26 39 pm" src="https://user-images.githubusercontent.com/6458278/106872380-573e0580-6727-11eb-815f-91d00c0074e8.png">


cc @joanrho

**Comment by ramonjd** [comment]
Tracking the copy change issue in D56478-code

Closing this issue for now as it related to the initial redesign delivery

**Comment by inaikem** [comment]
Looks great, Ramon! Thanks for taking my suggestion on board 😁

**Comment by joanrho** [comment]
I think that's a reasonable change too. Thanks for the suggestion, @inaikem!
