### ISSUE TITLE
SPT Layouts: Theme layouts fallback to default headstart content when no translations

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#46662]
When a theme has no translations for its Headstart annotations, Headstart will return a set of default translated content. This content is totally different from the theme demo site or previews!

As a result, the content will be mismatched with the preview in both SPT, and in the theme switch when replacing homepage content.

See this example in SPT:

![Screen Capture on 2020-05-19 at 08-05-36](https://user-images.githubusercontent.com/3696121/82329943-ba281a80-99a7-11ea-8d89-971f432b42fc.gif)

We should offer a more obvious fallback. I see some options:
1. Do not display any option when there is no translation for a homepage layout. This would also mean _not_ showing an "auto-change-homepage" dialogue in that case, I think.
2. Fallback to the same layout _design_ but with english content.

I've heard a strong argument in favor of option two from @AtrumGeost 

Obviously this is just a stop-gap measure while we make sure that the themes _do_ have correct translations to show.

**Comment by noahtallen** [comment]
We also need to do make sure that translations exist for these themes:

- [ ] Maywood
- [ ] Balasana
- [ ] Shawburn
- [ ] Twenty Twenty
- [ ] Seedlet (i18n is in progress for seedlet as of yesterday)

I have verified that each of the other recommended themes _do_ have translated headstart content.

**Comment by AtrumGeost** [comment]
As offered, we talked about this in our last ES Hangout ( p7SG42-uY-p2 ). We agreed that for a localized user (who'll end up replacing the Page Layout content with their own) it is better to get a Page Layout in English than nothing.

Thank you!

**Comment by noahtallen** [comment]
thanks for that feedback!

**Comment by noahtallen** [comment]
I've verified that the translations are in the i18n pipeline for these themes now. Unsure how long it will take to get them on wpcom, but at least they exist now!

**Comment by noahtallen** [comment]
Fix for the fallback issue here: D51621-code.

**Comment by noahtallen** [comment]
This is fixed now. I verified the fix with maywood in the ES locale. All of the caches will invalidate over the next 24 hours, so let me know if we are still seeing issues with this after then!

**Comment by emilyaudela** [comment]
We sent these out for translation on November 1 and all languages were delivered at the beginning of last week. I checked the page layouts for these themes and it looks like these are still showing up in English. https://d.pr/i/ofVDWp/BTeb7uKH2O

Normally, the translations need to be manually deployed by the developer. You should have received an email about how to deploy these. I believe the command you run needs to be something like `wp linguine headstart-deploy [strand id]`

Here are the strand IDs

Maywood - strand 68488
Balasana  - strand 68489
Shawburn - strand 68490
Twenty Twenty - strand 68491
Seedlet - strand 68375

**Comment by noahtallen** [comment]
Nice, thanks @emilyaudela. Unfortunately, I did not get an email, but I will look into that and make sure they are deployed!

**Comment by noahtallen** [comment]
Alright, they should all be deployed now. The new content should make its way to the SPT selector within 24 hours as caches invalidate.
