### ISSUE TITLE
Reader: Comments won't load and can't post comments

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#46679]
#### Steps to reproduce

1. Open this post in the Reader: https://wordpress.com/read/feeds/107085357/posts/2968474743
2. Error message appears: https://d.pr/i/A5mItF
3. A user tried to enter a comment and it would not post (I didn't try posting a comment from my account)

#### What I expected
I expected to see the comments and to be able to post a comment

#### What happened instead
We saw an error and the user couldn't post a comment

#### Additional Info
I was asked to include this additional information:
- The error message from the backend is “API calls to this blog have been disabled”

```
This AJAX request:
 
GET
    https://public-api.wordpress.com/rest/v1.1/sites/179423783/posts/1957/replies?http_envelope=1&order=DESC&number=50&status=approved
     
Returns this error response:
 
{"code":403,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unauthorized","message":"API calls to this blog have been disabled."}}
```

#### Context / Source

18123788-hc

**Comment by cathymcbride** [comment]
@ccwalburn can you give more information about what kind of site this happens on? We recently fixed something similar: https://github.com/Automattic/wp-calypso/issues/46284. B/c of the API call error, I'm wondering if this particular error is just one symptom?

**Comment by ccwalburn** [comment]
Hi @cathymcbride I asked about it on this P2: https://jetpackcrew.wordpress.com/2020/10/08/recent-fix-causing-issue-in-wpcom-reader/ 

@mreishus said it was a different issue and asked me to make a separate report

**Comment by ghost** [comment]
I have another report of this issue for a Jetpack site in 3510143-zen.

* Open this post in the Reader: https://wordpress.com/read/feeds/22355795/posts/3025996916
* The same error message reported appears: 

![](https://d.pr/i/DRbHPx+)
Image Link: https://d.pr/i/DRbHPx

* Tried posting a comment and received an error:

![](https://d.pr/i/MiZuXT+)
Image Link: https://d.pr/i/MiZuXT

The site owner reports that this has been an issue for a few weeks, both in the Reader and on the WordPress mobile app.

Additionally, the Jetpack debugger is indicating: `"API calls to this blog have been disabled."`

----

Site: https://misscharlesdexterward.de/
Jetpack Debug: https://tools.jetpack.com/debug/?url=http://misscharlesdexterward.de

**Comment by obenland** [comment]
It looks like the case of https://misscharlesdexterward.de works again.

I looked at the underlying code that returns that error message and it indicates that the Jetpack site doesn't have [the JSON API module](https://jetpack.com/support/json-api/) enabled. 

@ccwalburn Any chance we could see if activating that module fixes the situation for thequeensights.com?

**Comment by ccwalburn** [comment]
`thequeensights.com` is not a WordPress.com site, so I don't have access to it for testing. This error was reported by a WordPress.com user who was trying to post a comment on that site.

**Comment by obenland** [comment]
Thanks for the feedback @ccwalburn! In that case there's not much we can do here as it's not something we can really "fix", I'm afraid. 

On the positive side, we now have a first troubleshooting step: Making sure the site's JSON API module is active.
