### ISSUE TITLE
Image Block - Insert from URL - URL box empties if you stop hovering over Insert from URL button.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#46704]
#### Steps to reproduce

1. Create a post/page, and add an Image Block to it. 
2. Copy an image URL from somewhere. https://s.w.org/style/images/about/WordPress-logotype-alternative.png for example. 
3. Select Insert from URL. Leave your mouse where it is.
4. Press CTRL+V to paste in the URL.
5. Move your mouse off the button.
6. The URL you just pasted in will vanish.

#### What I expected
The URL not to vanish based on whether or not the mouse is hovering over the Insert from URL button.

#### What happened instead
If you're hovering over the Insert from URL button, and paste a link into the box that appears, leaving that hover will cause the link you've pasted in to vanish.

#### Browser / OS version
Windows, confirmed in latest version of Chrome, Firefox, and Edge

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30731356/96937774-c2681280-147d-11eb-9ac8-150df955c251.gif)

#### Context / Source
#user-report

**Comment by yansern** [comment]
This is now fixed with https://github.com/WordPress/gutenberg/issues/26253 and carried over to WP.
