### ISSUE TITLE
Add tracking to Editing Toolkit NUX

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#46705]
Let's add the following tracking to the NUX modal:

- When it loads and appears to the user (include the current flow, e.g. `isGutenboarding`)
- When it's dismissed
- When a user interacts with it, sending some [information about the requested slide](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L85) as well.

We can important `recordTracksEvent` into the module (I think)

```
import { recordTracksEvent } from '@automattic/calypso-analytics';
```

Context p1603408699056900-slack-CRNF6A9DX

**Comment by ramonjd** [comment]
> When a user interacts with it, sending some information about the requested slide as well.

This might require an extension to the `<Guide />` component, so maybe it can be a nice to have for now.

https://github.com/WordPress/gutenberg/tree/master/packages/components/src/guide

**Comment by autumnfjeld** [comment]
>  When a user interacts with it, sending some information about the requested slide as well.

@ramonjd Do you mean the "Next" and "Previous" buttons?  Those two buttons and the final "Ge Started" button are the only UI elements the user can interact with, as far as I can tell.
Screenshot here: https://d.pr/i/2ejA1c

**Comment by razvanpapadopol** [comment]
> When a user interacts with it, sending some information about the requested slide as well.

What about recording an event when mounting `NuxPage` [component](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L124) so we track if the user got to slide 1/2/3/4 ?

**Comment by ramonjd** [comment]
> What about recording an event when mounting NuxPage component so we track if the user got to slide 1/2/3/4 ?

Thanks for the idea @razvanpapadopol! 

Do you know if there is an obvious way to do that? 

I see that we're [mapping over the array of nux pages](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L69) .

We'll test, but do you think it's a matter of adding something like:

```
function NuxPage( { alignBottom = false, heading, description, imgSrc } ) {
      useEffect(() => {
          recordTracksEvent( 'calypso_ha_ha_ha', {title: heading } );
      }, []);
	return (
....

```

**Comment by razvanpapadopol** [comment]
>Do you know if there is an obvious way to do that?
>
>I see that we're mapping over the array of nux pages .
>
>We'll test, but do you think it's a matter of adding something like:

>function NuxPage( { alignBottom = false, heading, description, imgSrc } ) {
>      useEffect(() => {
>         recordTracksEvent( 'calypso_ha_ha_ha', {title: heading } );
>     }, []);
>	return (
>....


Yup! Exactly that is what I had in mind 👍 

Here is a fully-working draft PR: https://github.com/Automattic/wp-calypso/pull/46898
Please note that we're interested to see especially if the user got to the last slide.

@autumnfjeld feel free to bring it in https://github.com/Automattic/wp-calypso/pull/46796 or take over and merge separately since it's adding a different event (tracking each individual page and not the entire NUX modal).

**Comment by autumnfjeld** [comment]
@razvanpapadopol Thanks for the draft PR and the input!!  Finally got a working version with everyone's efforts. :). https://github.com/Automattic/wp-calypso/pull/46796

**Comment by autumnfjeld** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/46796
Just need Editing Toolkit backend deploy

**Comment by ramonjd** [comment]
This has been merged 🎉
