### ISSUE TITLE
NUX Menus: Turn on "add new pages" by default for all new users

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46703]
Currently, when new sites are created we leave this setting checked "off" in the customizer.

![image](https://user-images.githubusercontent.com/545779/96936977-bd5e8f80-148c-11eb-8908-79184df51530.png)

This is true if you're a new user starting out at wp.com/start or an existing user starting out at wp.com/new.

This means that in order for a user just trying out WP.com, adding new pages, they must first understand how to use the customizer and menus before seeing their new pages appear in the menu.

I'd like to propose that we make the following change for all new sites. (Not existing sites.)

![image](https://user-images.githubusercontent.com/545779/96937298-6e652a00-148d-11eb-9896-f23005910137.png)

We make this setting checked "on".

cc @kathrynwp @jordesign @davipontesblog @rickybanister  for feedback on that change.

@apeatling @niranjan-uma-shankar is this a difficult change to make?

**Comment by rickybanister** [comment]
I believe that's the more sensible default. 

I assume a customer would add a couple of pages and see them populate their primary nav menu. Once they start to get the hang of things and perhaps start adding a lot of pages, that is when (I assume) they would start to consider modifying their nav structure and digging deeper into how menus work. 

At that point we can provide some education or guidance to them and perhaps they'd decide to uncheck that setting after they've understood how to update things manually.

If we flip that whole default around (as it is now) they will very quickly be confused as to how they make their new page show up in their nav, then be confronted with learning the Customizer (in addition to Calypso and the editor) early in their journey.

**Comment by davipontesblog** [comment]
I agree that this would be a better default since I see many new users correlating the list of pages in `Site > Pages` to what they expect to see on the menu (they even mention things like "How can I reorder these in Site > Pages", for example). The only caveat to that is that when users _do_ find out about editing menus, this setting gets in the way, and creates lots of confusion. So if we had a way to turn it off automatically on any first menu edit, that would be ideal.

**Comment by ramonjd** [comment]
This idea was abandoned after feedback from Happiness p7DVsv-8xW-p2 Are we trying again?

**Comment by ianstewart** [comment]
@ramonjd thanks for sharing that HE feedback. I hadn't seen it before. I had a chat with @kathrynwp today about this idea and to summarize she convinced me that it could end up being more trouble than it's worth — for similar reasons to what Davi is pointing out. It's confusing when you _do_ figure out menus. 

Closing this one up. :)
