### ISSUE TITLE
Plans: Create feature page for custom design

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4672]

**Comment by retrofox** [comment]
already do we have this design?

/cc @adambbecker

**Comment by adambbecker** [comment]
@retrofox: No we don't already have a design for this. I'm a bit sick with the Flu currently, but I'll be working on this over the next few days.

**Comment by adambbecker** [comment]
Provided a visual update for this on #4709 since @artpi had already started a PR for it.

**Comment by rralian** [comment]
I think we should table this for now. Let's get the rest of the nudge work lined up more consistently and then we can test the whole thing as a system, versus the onesy-twosy approach we've been taking. I'm also eager to move on our feature projects. We can come back to this when we have a little more feature work under our belts. So I'm moving this to the project backlog.

**Comment by artpi** [comment]
Since we totally resigned from feature pages, I'm closing this.
