### ISSUE TITLE
Links in the main sidebar admin menu not working when fullscreen mode is disabled

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#46767]
#### Steps to reproduce

1. Open a post or a page or create a new one
2. Click on the three dots at the top-right and disable _Fullscreen mode_
3. The menu on the left will automatically appear; try clicking on any item there
4. You'll get the _site refused to connect_ error

#### What I expected

It should lead me to the screen I selected.

#### What happened instead

I get this error:

<img width="565" alt="Screen Shot 2020-10-26 at 11 05 38 AM" src="https://user-images.githubusercontent.com/10340370/97159458-33a80e00-177b-11eb-8eab-0a46442ac74c.png">

#### Browser / OS version

Chrome 86.0.4240.111 / Mac OS 10.15.5

#### Screenshot / Video

![screen-capture-on-2020-10-26-at-11-06-57](https://user-images.githubusercontent.com/10340370/97159915-dc566d80-177b-11eb-83c6-a8e8d6e1723c.gif)

cc [@zivoradmilekic](https://github.com/zivoradmilekic) who surfaced this bug to me during a WordPress workshop last week.

**Comment by synora** [comment]
I'm unable to replicate this. Once disabling fullscreen mode, the screen I select appears as expected. Closing issue.
