### ISSUE TITLE
New Order Notifications for Pre-Orders

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#46766]
New order notifications fire if an order has an order status of `wc-pre-order`. This was to support [the Pre-Orders extension](https://woocommerce.com/products/woocommerce-pre-orders/), which we own. However, this order status no longer appears to be in use and no notification is fired if a pre-order is made using the extension.

#### Steps to reproduce

1. Install and activate [the WooCommerce Pre-Orders extension](https://woocommerce.com/products/woocommerce-pre-orders) on any site using WooCommerce.
2. Follow [the extension's documentation](https://docs.woocommerce.com/document/pre-orders/?_ga=2.90613658.1828917693.1603702581-974234983.1603096326) to set up a product that can be pre-ordered.
3. Go through the steps to place a pre-order on your site and pay the required deposit, this will set the order's status to Pre-Orders.

#### What I expected

I expected to receive a new order notification, both in Calypso and the Woo mobile app.

#### What happened instead

No notification was fired. From looking at the source code, it seems like the order status may have changed from `wc-pre-order` to `wc-pre-ordered` somewhere along the line:

<img width="720" alt="Screenshot 2020-10-26 at 09 44 12" src="https://user-images.githubusercontent.com/2998162/97157392-f1c59a80-176f-11eb-9242-cc26192faf31.png">

#### Context / Source

This was originally reported to us in 3390870-zen.

#user-report

**Comment by SiobhyB** [comment]
I flagged this to the team that owns these notifications in C6H8C3G23/p1603706061129500-mobile-woo, a link to the internal code that likely needs updating is also included in that Slack message.

**Comment by SiobhyB** [comment]
Aside: this might also be a good PR to incorporate a fix for https://github.com/woocommerce/woocommerce-android/issues/2282 :D

**Comment by astralbodies** [comment]
I've made a backend change to the notification system to support sending new order notifications for the `wc-pre-ordered` status. For the record, we meant to use that status when we originally added support for the pre-orders extension. 😄 Left the support in for the non-standard `wc-pre-order` status.
