### ISSUE TITLE
CoBlocks: Disable "CoBlocks" collection

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#46776]
“Coblocks” collection adds duplicated blocks in the picker without much value. Disable the collection.

<img width="137" alt="coblocks-collection" src="https://user-images.githubusercontent.com/841763/97198096-b9917c80-17ae-11eb-8cf4-9d5768277607.png">

pbAPfg-Xn-p2

**Comment by WunderBart** [comment]
Should the collection be disabled for both Simple and Atomic sites?

Edit: Simple.
