### ISSUE TITLE
Store: Manual order with multiple variations formatted incorrectly

### ISSUE THREAD

**Issue by rwaynick** [Automattic/wp-calypso#46773]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/store/orders/
2. Create a new manual order and add a product that has multiple variations.
3. Access the order in WP-Admin and notice the dash in-between each variation

![Screen Shot 2020-10-26 at 12 08 42](https://user-images.githubusercontent.com/10882502/97190174-293e4200-1784-11eb-9cca-a54573ab625c.jpg)

4. Create a new manual order starting from WP-Admin and add a product that has multiple variations.
5. Notice that there's a comma in WP-Admin,

![Screen Shot 2020-10-26 at 12 10 47](https://user-images.githubusercontent.com/10882502/97190325-57238680-1784-11eb-9254-5d9b087c2b33.jpg)

#### What I expected

I expected the format of the variable product to be the same in Store and WP-Admin. Store should match WP-Admin.

#### What happened instead

Store uses a dash in-between variations. WP-Admin uses a comma.

#### Browser / OS version

Version 86.0.4240.111 
macOS 10.15.7

#### Context / Source

#user-report

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
