### ISSUE TITLE
CoBlocks: Add layer to register only features we need

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#46782]
We're currently running a custom build of the CoBlocks plugin on Simple Sites, where we're e.g. only registering a subset of blocks that is compatible with WP.com's security policies (think `kses` filters etc).

As per pc9Uba-7N-p2#comment-158, we'll try an approach where we don't rely on a custom build, but run the 'vanilla' plugin, and unregister all blocks from the `coblocks/` namespace except for those that are found on an allow-list. We'll also need to take similar measures for stuff like custom CPTs and the like.

One question is where such an 'extra-layer' plugin should live, given that it will need to be shipped to both Simple and Atomic sites. I've raised that question in the following P2 post: p9o2xV-17j-p2

IMO, we can start developing and testing this feature in wpcomsh, and later graduate it to wherever we decide it should live.

**Comment by ockham** [comment]
Some development notes:

> unregister all blocks from the `coblocks/` namespace except for those that are found on an allow-list

We'll need something like

```php
foreach ( \WP_Block_Registry::get_instance()->get_all_registered() as $block ) {
	if ( 'coblocks/' === substr( $block['name'], 0, 9 ) && ! in_array( $block['name'], $allowed_blocks, true ) ) {
		unregister_block_pattern( $block['name'] );
	}
}
```

(untested; based on [this](https://github.com/Automattic/wp-calypso/blob/1fa9759cbb92832659b2c9d0d3f94d59b2c82376/apps/editing-toolkit/editing-toolkit-plugin/block-patterns/class-block-patterns.php#L65-L71)).

> We'll also need to take similar measures for stuff like custom CPTs and the like.

E.g. for the patterns CPT, we basically need to carry over 519-gh-wpcomsh.

**Comment by ockham** [comment]
> IMO, we can start developing and testing this feature in wpcomsh, and later graduate it to wherever we decide it should live.

If we do that, we can basically use the `coblocks-mods.php` file that was added by 519-gh-wpcomsh, and add code like the above code sample to it.

**Comment by fullofcaffeine** [comment]
@ockham So basicall, in abstract terms:

1. We run the vanilla plugin release for Coblocks (whatever version we need) on AT, so nothing will change here as it's the way it's currently done on AT. This will only become relevant when we reach the point of migrating this layer over to WPCOM, when we will then deprecate our custom coblocks fork and add this layer (which will live on `coblocks-mods.php`).
2. We then run code on wpcomsh that taps into the register API provided by Coblocks (which will all be loaded in the same execution space) to unregister certain features.

I have a few questions about that:

1. What happens if the feature can't be unregistered programmatically?
2. Could you elaborate on `We'll also need to take similar measures for stuff like custom CPTs and the like.`?

Thanks!

**Comment by ockham** [comment]
> @ockham So basically, in abstract terms:
> 
> 1. We run the vanilla plugin release for Coblocks (whatever version we need) on AT, so nothing will change here as it's the way it's currently done on AT. This will only become relevant when we reach the point of migrating this layer over to WPCOM, when we will then deprecate our custom coblocks fork and add this layer (which will live on `coblocks-mods.php`).

Yep! (Deployment details are TBD and largely depend on the outcome of the discussion at p9o2xV-17j-p2. We might e.g. end up moving the `coblocks-mods.php` file into a separate plugin that we'll ship to both Simple and Atomic.)

> 2. We then run code on wpcomsh that taps into the register API provided by Coblocks (which will all be loaded in the same execution space) to unregister certain features.

Yep! (Well, to be exact, functions like `unregister_block_type()` are coming from WP Core -- we're just applying them to blocks previously registered by CoBlocks.)

> I have a few questions about that:
> 
> 1. What do we do if the feature can't be unregistered programmatically?

Well, that would kind of end this experiment: If we cannot do that in a separate layer, we'll have to go reconsider and likely embrace a customized codebase of CoBlocks (much like we do now for Simple Sites). It'd be good to find out early if there are any such features so we can change course accordingly :+1: 

> 2. Could you elaborate on `We'll also need to take similar measures for stuff like custom CPTs and the like.`?

Oh, I just meant that it's not just blocks that CoBlocks registers (through `register_block_type`) but also other features, such as the block pattern CPT (Custom Post Type). That's done through [`register_post_type`](https://github.com/godaddy-wordpress/coblocks/blob/edb8ba23bd52a6e527354d0212b42b822070f6ff/includes/class-block-patterns.php#L60) (and some ancillary methods) -- so in order to remove that feature, we have to unregister/disable/deactivate them, by finding the corresponding calls (e.g. `unregister_block_type`). For the block pattern CPT, we're already doing that (per 519-gh-wpcomsh), so we don't have to do anything there; but it's possible that CoBlocks adds other features that we need to disable in a similar fashion.

**Comment by fullofcaffeine** [comment]
@Automattic/good-mountain Created this issue for experimenting with the CoBlocks fork: https://github.com/Automattic/wp-calypso/issues/46935. I guess we can close this one?

**Comment by fullofcaffeine** [comment]
I'm closing this one in favor of https://github.com/Automattic/wp-calypso/issues/46935. Feel free to re-open if there's anything else to do related to this.
