### ISSUE TITLE
Plans: Implement nudge for domains

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4679]
should point to `/domains` rather than a feature page for now

**Comment by retrofox** [comment]
should we hide / remove the nudge when the site already has a custom domain?

**Comment by rralian** [comment]
Yes, I think so. Kinda depends on the design/content.

**Comment by rralian** [comment]
I chatted with @adambbecker about this. He wasn't excited about this nudge based on all the existing links around domains here, that are essentially nudges as well. I still think it's worth a test however to see what we can do with this simple step. I also think we should spend some time iterating on the domains purchase/upgrade flow, like @adambbecker's nudge post. That would be outside the scope of this issue however.
