### ISSUE TITLE
Editing Toolkit crashes Editor

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#46811]
Quoting @WunderBart (p1603805230434600-slack-C015AL3QL7M?thread_ts=1603763612.416300&cid=C015AL3QL7M):

> When I run `yarn dev --sync` and go to the editor, I see this error:
> ```
> launch.ts:5 Uncaught TypeError: Cannot read property 'register' of undefined
>     at Module../editing-toolkit-plugin/common/data-stores/launch.ts (launch.ts:5)
>     at __webpack_require__ (bootstrap:19)
>     at Module../editing-toolkit-plugin/common/data-stores/index.ts (index.ts:1)
>     at __webpack_require__ (bootstrap:19)
>     at bootstrap:83
>     at bootstrap:83
> An error occurred while running 'mapSelect': Cannot read property 'getState' of null
> react_devtools_backend.js:2273 TypeError: Cannot read property 'isSidebarOpen' of undefined
>     at LaunchSidebar (attach-launch-sidebar.tsx:28)
>     at we (react-dom.min.de439aae.js?m=1599596311h:84)
>     at zj (react-dom.min.de439aae.js?m=1599596311h:226)
>     at Th (react-dom.min.de439aae.js?m=1599596311h:152)
>     at tj (react-dom.min.de439aae.js?m=1599596311h:152)
>     at Te (react-dom.min.de439aae.js?m=1599596311h:146)
>     at react-dom.min.de439aae.js?m=1599596311h:61
>     at unstable_runWithPriority (react.min.e713ea3b.js?m=1599596311h:25)
>     at Da (react-dom.min.de439aae.js?m=1599596311h:60)
>     at Pg (react-dom.min.de439aae.js?m=1599596311h:61)
> ```
> which crashed the editor
> it’s OK without the dev ET
> I nuked all the node modules and reinstalled, my sandbox is clean & up to date 
 
p1603806103436600-slack-C015AL3QL7M?thread_ts=1603763612.416300&cid=C015AL3QL7M:

> I can see that the @automattic/data-stores module doesn’t contain the Launch func indeed:
> ```
> Module {…}
> Auth: (...)
> DomainSuggestions: (...)
> Plans: (...)
> Site: (...)
> User: (...)
> Verticals: (...)
> VerticalsTemplates: (...)
> WPCOMFeatures: (...)
> persistenceConfigFactory: (...)
> ```

Sounds a bit like maybe the ETP is trying to access the latest package version of `@automattic/data-stores`, which might not include `Launch` yet? (moved to `@automattic/data-stores` in #46570). Note that the lastest ETP release was a week ago (at the time of this writing): https://wordpress.org/plugins/full-site-editing/

The `@automattic/data-stores` package version in `package.json` is `^1.0.0-alpha.1`: https://github.com/Automattic/wp-calypso/blob/cb0f38727a9fcd5b71d8d39734309775a59d571a/apps/editing-toolkit/package.json#L89

Which isn't an actual public release it seems, see https://www.npmjs.com/package/@automattic/data-stores -- the only relase there is `1.0.0-alpha.0` :thinking:

cc/ @Automattic/luna @Automattic/team-calypso

**Comment by razvanpapadopol** [comment]
@WunderBart this may be an issue coming from WBE widget. Could you check if you have this change synced on your sandbox? https://github.com/Automattic/wp-calypso/pull/46475/files

**Comment by yansern** [comment]
Hi, this is most likely because the `@automattic/data-stores` package was not rebuilt. 

If you're just running `yarn dev --sync` on `apps/editing-toolkit`, without running `yarn start` on root calypso folder, it is likely that the aforementioned package was not rebuilt.

So the solution is just to run `yarn install` once on the root calypso folder, then only run `yarn dev --sync` on `apps/editing-toolkit`, so the built editing toolkit plugin contains the updated `@automattic/data-stores`.

**Comment by yansern** [comment]
> Sounds a bit like maybe the ETP is trying to access the latest package version of @automattic/data-stores, which might not include Launch yet? (moved to @automattic/data-stores in #46570). Note that the lastest ETP release was a week ago (at the time of this writing): https://wordpress.org/plugins/full-site-editing/
> 
> The @automattic/data-stores package version in package.json is ^1.0.0-alpha.1:
>
> wp-calypso/apps/editing-toolkit/package.json
Line 89 in cb0f387
 "@automattic/data-stores": "^1.0.0-alpha.1", 
Which isn't an actual public release it seems, see https://www.npmjs.com/package/@automattic/data-stores -- the only relase there is 1.0.0-alpha.0 🤔

Not sure why there's a public release for what feels like a private repo. The public release seems to be 9 months old, which means a lot of things are missing (from the sample output above I can also see Plans store is missing). 

The Calypso repo builds from packages folder and either copy or symlink over (not sure which one) to the node_modules folder. 

> I nuked all the node modules and reinstalled, my sandbox is clean & up to date

Would be curious to know how the reinstallation was done. Running yarn install on root folder should automatically perform the package rebuilding, unless the failed.

Eitherway I'm inclined to see this as a non-issue for now.

**Comment by WunderBart** [comment]
> So the solution is just to run `yarn install` once on the root calypso folder, then only run `yarn dev --sync` on `apps/editing-toolkit`, so the built editing toolkit plugin contains the updated `@automattic/data-stores`.

Had to run `yarn build` from the root as well to get this running but it worked! 🙌 Thanks, @yansern!
