### ISSUE TITLE
Focused Launch: set up A/B testing

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46839]
Currently, the Focused Launch Flow modal is enabled via the temporary `gutenboarding/focused-launch-flow` flag.

The goal is to swap the flag with A/B testing logic

**Acceptance Criteria:**

- [x] After creating a site using `/start` flow, when clicking _Launch_ button in the editor, 50% of users should be redirected to `/start/launch-site` and 50% should start the Focused launch flow with no redirect.
- [x] ~When enabling `gutenboarding/focused-launch-flow` in production we should check where it's being used. For example, in [openCheckout](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/utils.ts#L29-L35) we should rather use `!isGutenboarding` to identify the launch flow we're in.~ Now uses ENABLE_FOCUSED_LAUNCH in backend flag.
- [x] Not going through Calypso iframe would be good in the context of https://github.com/Automattic/wp-calypso/issues/47803 so A/B test code could be run in PHP as described in the recommendation below

**Hint:**

We could follow the pattern already implemented by @Automattic/ganon by adding a filter and get the A/B test variations on the backend:
- Server-side A/B test reference: https://github.com/Automattic/wp-calypso/pull/47896
- Server-side launch injection: D53680-code
- A/B test code: https://github.com/Automattic/wp-calypso/pull/49004 D56270-code
- Experiment: pbxNRc-Ag-p2

**Comment by tjcafferkey** [comment]
@razvanpapadopol when you get some time would you please be able to provide more information on how to implement this? Thanks!

**Comment by razvanpapadopol** [comment]
We still need to create a diff to enable the experiment.

**Comment by yansern** [comment]
> We still need to create a diff to enable the experiment.

That would be D56270-code.

**Comment by razvanpapadopol** [comment]
The experiment was reviewed in p1612385166024600-slack-C7HH3V5AS and it's implemented in D56270-code
