### ISSUE TITLE
Editor: Launch contact form to production

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4683]
Before we do this though, I wonder if this should take into account our planned UX for adding a widget/app/embed into a post/page (https://github.com/Automattic/wp-calypso/issues/4682). If we plan to change how/where the contact form is added to a page, it may be worth waiting for that design spike to implement it, rather than launching this briefly and then changing where it lives. 

/cc @rodrigoi @adambbecker @drw158

**Comment by drw158** [comment]
The icon will probably be moved once we actually implement widgets. That is far off though, and I think we need to launch the contact form before then. It won't be drastically different — it will probably still live in the tiny MCE area.

**Comment by rralian** [comment]
sounds good

**Comment by mtias** [comment]
See #4545.
