### ISSUE TITLE
Premium Content Block - Attempt Block Recovery not able to resolve, creates autosave upon re-loading

### ISSUE THREAD

**Issue by smithkyle45** [Automattic/wp-calypso#46830]
#### Context / Source

The context is important for this one because I wasn't able to perfectly replicate the conditions that led to the issue that a user brought to my attention during live chat. 

They use the **Premium Content Block** to generate a subscriber & non-subscriber view for nearly all of their site's posts. The ones using this block started displaying the error message of "This block contains unexpected or invalid content" 
![](https://d.pr/i/WU8RyE/Yv9Um32kba+)

The site itself is Atomic but using only the default pre-installed plugins.

I was able to put together a screen recording that provided a workaround to help get this resolved for the user: https://d.pr/v/QhNkkQ/gVGnbGKkws

The "Attempt Block Recovery" option appears to be working to add `entry-content` but not until the editor is exited or reloaded and the changes restored from an autosave. 

I'm not 100% confident on whether it affects all previously added Premium Content Blocks in this way but I wanted to get something started in case it was an unwanted side effect of a recent update to the WordPress.com Editing Toolkit to include  the `entry-content` class in those blocks.

#user-report 25210016-hc

#### Steps to reproduce (that I used to verify the error, not fully matching the user report)

1. Edit/create a page or post
2. Add a **Premium Content Block**
3. Switch to the Code editor (3 dots on the top right)
4. Remove the `.entry-content` class
5. Switch back to Visual editor to view error of unexpected or invalid content

What may help more to test exactly is to have a page already created that contains the Premium Content Block if possible.

#### Screenshot / Video
https://d.pr/v/QhNkkQ/gVGnbGKkws

**Comment by blazevivan** [comment]
Another case in HC - 25253601

**Comment by apeatling** [comment]
This will be fixed by https://github.com/Automattic/wp-calypso/pull/46924 when a new version of the editing toolkit is released in the next couple of days.
