### ISSUE TITLE
Focused Launch: Detailed Domain Picker view

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46866]
Requires #46863 

- [x] Switch to different view when user clicks on "View all domains"
- [x] Integrate `DomainPicker` [following the pattern from step-by-step launch flow](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx) with a variation to show "Select" buttons, instead of radio buttons (variation implemented in #46946).
- [x] Clicking on "Go Back" button should show the initial modal view

### Tracked separately:

 "Use a domain I own" should send the user to the dedicated flow in Calypso signup framework
- UI component: https://github.com/Automattic/wp-calypso/issues/47372
- redirect logic: https://github.com/Automattic/wp-calypso/issues/44645

### Screenshots

![Screenshot 2020-10-28 at 15 24 55](https://user-images.githubusercontent.com/1083581/97449230-becb0480-1931-11eb-8cbb-78904a888eec.png)

![ Domain picker ](https://user-images.githubusercontent.com/1083581/97450168-b921ee80-1932-11eb-8abd-d3311ce411ea.png)

**Comment by razvanpapadopol** [comment]
@ollierozdarz 
One limitation we have when building this screen is that we can't change the sub-domain that a user already has for their site. This is also the behaviour in current Calypso launch flow.
<img width="600" alt="Screenshot 2020-11-11 at 15 20 40" src="https://user-images.githubusercontent.com/14192054/98816980-2012cd80-2432-11eb-9e5c-fdb44de0fda9.png">

I propose we use the solution from the step-by-step launch flow to highlight that the first option is not dynamic 
![prelaunchfree-02](https://user-images.githubusercontent.com/14192054/98817518-deceed80-2432-11eb-96f8-0ff4f2d1db3c.png)

Design source: pcbO8q-4l-p2

**Comment by ollierozdarz** [comment]
Hey @razvanpapadopol, yeah, you're definitely right! My mistake with the mocks.

My only concern to go with the solution "keep sub-domain, "professional domains" is that I vaguely remember that this performed poorly in Gutenboarding, so we rolled ended up rolling it back? If that's the case, I'd suggest we can just keep the current proposed design solution but and leave the user's static subdomain (like the top mock you posted, only their subdomain might say 'toastedbeans38843.wordpress.com' or whatever it started as).

What are your thoughts? 🙂

**Comment by razvanpapadopol** [comment]
> My only concern to go with the solution "keep sub-domain, "professional domains" is that I vaguely remember that this performed poorly in Gutenboarding, so we rolled ended up rolling it back?

Nope, we're still using this solution for the editor launch flow after Gutenboarding and it works fine. In the Focused Launch flow, we'll have more traffic so we can iterate on it if we think there is growth potential.

We've rolled back a different change: from radio buttons to _Select_ buttons in Gutenboarding site creation flow but that was anyway part of a larger experiment and with little traffic so we don't know 100% which version is better for the buttons.

**Comment by tjcafferkey** [comment]
Just for awareness, this "Keep Sub-Domain" and "Professional Domains" variation of this design is in the associated PR of this issue which will be getting reviewed likely today.

If a different outcome is decided off the back of this discussion I think we should open a separate issue to iterate on this so that it doesn't block anything and we're still making steps forward 😊

How does that sound to you guys?

**Comment by razvanpapadopol** [comment]
> If a different outcome is decided off the back of this discussion I think we should open a separate issue to iterate on this so that it doesn't block anything and we're still making steps forward

Sure, this is not blocking the opened PR and I suggest we also keep it like this for the first iteration if Ollie agrees.

**Comment by razvanpapadopol** [comment]
Another question for @ollierozdarz is about going back behavior. 
> Clicking on "Go Back" button should show the initial modal view

So we have the _Go Back_ button but should we also return the user to the summary view when they press _Select_ button on a domain? 

At the moment we're not closing the modal in Gutenboarding site creation for two reasons:
- there is a radio button instead of CTA button such as _Select_ in this case
- there is a primary CTA next to the _Go Back_ button saying _Confirm_

**Comment by ollierozdarz** [comment]
> Nope, we're still using this solution for the editor launch flow after Gutenboarding and it works fine. In the Focused Launch flow, we'll have more traffic so we can iterate on it if we think there is growth potential.

> We've rolled back a different change: from radio buttons to Select buttons in Gutenboarding site creation flow but that was anyway part of a larger experiment and with little traffic so we don't know 100% which version is better for the buttons.

Ok, no problems! Lets go with your suggestion! 👍

**Comment by ollierozdarz** [comment]
> So we have the Go Back button but should we also return the user to the summary view when they press Select button on a domain?
> 
> At the moment we're not closing the modal in Gutenboarding site creation for two reasons:
> 
> there is a radio button instead of CTA button such as Select in this case
> there is a primary CTA next to the Go Back button saying Confirm

@razvanpapadopol once a user clicks on the Domain from that Domains screen, we take them back to the overview with that new Domain added into the list as a new option. Here's the design from the Launch flow Figma. You'll see I'm adding it below the initial options, but above the subdomain.

<img width="1051" alt="Screen Shot 2020-11-13 at 9 38 23 am" src="https://user-images.githubusercontent.com/67085494/99009648-143f1c80-2594-11eb-9898-a924f161f7fc.png">
