### ISSUE TITLE
Focused Launch: Retrieve and update site title in a way that works in both Calypso & WP-Admin

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#46872]
The site store in `@automattic/data-stores` should have a way to retrieve and update site title that works in both Calypso & WP-Admin.

In Calypso, this is done through:
```js
wpcom.undocumented().settings( siteId, 'post', settings )
```

In WP-Admin, this is done through:
```js
const [ title, setTitle ] = useEntityProp( 'root', 'site', 'title' );
```

Some relevant files:
- client/lib/wpcom-undocumented/lib/undocumented.js
- client/state/site-settings/actions.js

**Comment by razvanpapadopol** [comment]
Site title data (`name` property) is typed in `Site` store: https://github.com/Automattic/wp-calypso/blob/master/packages/data-stores/src/site/types.ts#L67

And it can be already retrieved using `select( SITE_STORE ).getSite( siteId )`.
<img width="1465" alt="Screenshot 2020-10-28 at 18 18 37" src="https://user-images.githubusercontent.com/14192054/97465229-81bf3c00-194a-11eb-85b3-b07b00e18661.png">

**Comment by ciampo** [comment]
The `@wordpress/data` package is also imported in a few files under the `packages/launch/src/hooks` folder ([`use-title.ts`]( https://github.com/Automattic/wp-calypso/blob/2510281dcc19f61cbc0fb2b5949427c9b935b2e9/packages/launch/src/hooks/use-title.ts#L7) and [`use-domain-search.ts`](https://github.com/Automattic/wp-calypso/blob/2510281dcc19f61cbc0fb2b5949427c9b935b2e9/packages/launch/src/hooks/use-domain-search.ts#L7))

Should we also look into replacing those imports too?
