### ISSUE TITLE
Video Block: iframe aspect ratio is different from the video

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#46890]
WP.com | Self Hosted
------------ | ------------
![screencapture-iamtakashi-wordpress-2020-10-28-headings-on-cover-2020-10-28-20_54_32 1](https://user-images.githubusercontent.com/908665/97497217-12554680-1962-11eb-861d-8ea3fb6e77e5.jpg)  |  ![screencapture-iamtakashi-eu-ngrok-io-2020-10-28-20_50_12 1](https://user-images.githubusercontent.com/908665/97497241-1c774500-1962-11eb-846a-778191249911.jpg)

The video is 16:9 and it appears as expected in self-hosted, but on WP.com the aspect ratio is 4:3.

Once you play the video, the video appears 16:9, but then the black bars appear at the top and the bottom, and they don't look nice.

![screencapture-iamtakashi-wordpress-2020-10-28-headings-on-cover-2020-10-28-21_14_05 1](https://user-images.githubusercontent.com/908665/97497739-e25a7300-1962-11eb-873d-0c11feaf12bb.jpg)

The width issue tracked here: #46889

cc @ianstewart @apeatling

**Comment by tanjoymor** [comment]
I've run into another case that seems to be similar to this.

The video block is coding the video with 4-3: https://d.pr/i/EJTMdv

Manually changing that code to be 16-9 converts the block into HTML like this: https://d.pr/i/094VR3 but it does display in the 16-9 ratio on the live page: https://d.pr/i/bljHcR

Customer report: #24670643-hc

**Comment by glendaviesnz** [comment]
@mmtr from memory I think you have done a bit of work on videopress - do you have any thoughts on why WPcom always defaults to 4:3 aspect ratio but jetpack sites running video press default to 16:9?

I have tried setting Display higher quality video by default. in WPadmin for the sandboxed site, but that didn't make any difference, and havn't had much joy trying to the trace the code that is setting the aspect ratio for the embedded player - can see where it happens in the jetpack block, but it is just getting the aspect ration based on the height and width of the underlying iframe size which is set somewhere on the backend.

**Comment by glendaviesnz** [comment]
@glendaviesnz I don't know what causes the different behavior but likely is determined in the videopress lib:

https://github.com/Automattic/videopress/blob/master/lib/auto-resize.js
https://github.com/Automattic/videopress/blob/45c72f78ba088c47b89fcd2a0954b40a62dea6c8/lib/index.js#L27-L28

**Comment by glendaviesnz** [comment]
Thanks @mmtr ... was looking everywhere for the unminified code of of the videopress library so that github link should help to track down the issue 😄  .... in case you are wondering, I posted the initial question on the wrong issue by mistake, so have moved your response to the correct one.

**Comment by glendaviesnz** [comment]
@mmtr, in case you are interested it turned out to be a minor rounding difference between videos on wpcom which round to 1.77 and those on jetpack videopress sites which round to 1.78 ... only the 1.78 ones were being classed as HD in the jetpack videopress block - https://github.com/Automattic/jetpack/pull/17969
