### ISSUE TITLE
Editor: Missing Scrollbars in Chrome

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#46892]
We're seeing reports of missing scrollbars in the editor in Chrome since Gutenberg v9.2.2 was rolled out.

Unable to reproduce, but at least 10 separate cases were reported. Clearing the browser cache solves it in most cases.

#### Browser / OS version

Chrome 85 / OS X 10.12.6
& others

#### Screenshot / Video
![Annotation on 2020-10-29 at 09-12-08](https://user-images.githubusercontent.com/30727666/97502357-14052580-19c7-11eb-9978-1733a5465ab2.png)

#### Context / Source

Initially discussed and reported in p1603756528404500-slack-C015AL3QL7M

#25184943-hc #25185619-hc #25181971-hc #25181508-hc

**Comment by donalirl** [comment]
#3450167-zen

**Comment by jeyip** [comment]
@donalirl Have you seen this as a recurring issue for the same websites and users? Or is it the case where clearing the browser cache once is enough to resolve the problem.

**Comment by donalirl** [comment]
> @donalirl Have you seen this as a recurring issue for the same websites and users? Or is it the case where clearing the browser cache once is enough to resolve the problem.

Never recurring. Cache clear always solves it.

**Comment by adelineyaw** [comment]
Chat: #25336034-hc 
Follow up ticket: #3456776-zen

User says clearing their browser's cache and cookies, as well as switching browsers didn't resolve the issue.

**Comment by jeyip** [comment]
Still having difficulty reproducing the problem, but generally speaking, it appears to be an issue with sticky caches. I'm going to start discussions with the systems team to see if there's an easy path forward.

**Comment by inaikem** [comment]
Triage: Wondering if this is still a current issue. I'm unable to replicate on my end, so a second/third set of eyes would be appreciated!

**Comment by donalirl** [comment]
I don't think it is, since we haven't had any new reports in a long time. If it was still an issue, we would have continued to receive new cases. Probably safe to close.

**Comment by inaikem** [comment]
Understood, cheers!
