### ISSUE TITLE
New Google Analytics Measurement ID changes

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#46893]
Google's [new implementation of the Measurement ID](https://support.google.com/analytics/answer/9539598?hl=en) has broken the Google Analytics implementation.

1. Create a new GA account or property
2. Add a new stream
3. Receive a tag formatted as `G-R1234ABCD` instead of the previous `UA-123241234`
4. Input the tag into the Google Analytics Tracking ID in https://wordpress.com/marketing/traffic/SITEURL

#### What I expected
To have the Google Analytics tracking work

#### What happened instead
The tracking JS is replaced with an HTML comment `<1--  Your Google Analytics Plugin is missing the tracking ID -->` and no tracking is visible on the page.

Live example: https://d.pr/i/Y8LeIP

#### Context / Source

#25226936-hc
#3446756-zen

**Comment by chrisfromthelc** [comment]
Related: #46764

**Comment by chrisfromthelc** [comment]
Closing in favor of #46664

**Comment by chrisfromthelc** [comment]
Reopening as the issue still exists.

**Comment by creativecoder** [comment]
I think we've finally resolved this via r398421-vip-wpcom
