### ISSUE TITLE
Export: An active export is already running ( Simple site )

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#46896]
The user on the site cannot start an export because of the error mentioned in the title.

<img width="560" alt="export-content" src="https://user-images.githubusercontent.com/12064241/97537884-30559200-19c8-11eb-8d72-30a23db29dfc.png">

<img width="548" alt="network-log" src="https://user-images.githubusercontent.com/12064241/97537997-5aa74f80-19c8-11eb-9ef6-9268cb07f105.png">

Could someone please help resetting that, so an export can be started again? Thank you! 
@Automattic/create 

Context: pMz3w-caN-p2
Follow-up: #3444629-zen

#user-report

**Comment by yoavf** [comment]
@kriskorn I reset the active export status.

**Comment by kriskorn** [comment]
> @kriskorn I reset the active export status.

Thank you! 
I have replied to the user and will keep this open until they let us know it has worked out for them and then will close the issue.

**Comment by kriskorn** [comment]
User happy and export successful. Closed.
