### ISSUE TITLE
Display errors on top of Checkout Modal

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#46906]
Card error and coupon error notifications are displayed behind the modal so not visible for users. This is probably a z-index issue.

Mentioned in p58i-9C7-p2#comment-47828 (points 4 and 5).

**Comment by tjcafferkey** [comment]
Reopening this as it was reintroduced by https://github.com/Automattic/wp-calypso/pull/46942 as found by the E2E tests I'm working on.
