### ISSUE TITLE
Nav Unification - Make sidebar wider both in Calyspo and wp-admin

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#46912]
Currently we have set the sidebar `width:200px` both in Calypso and wp-admin, which is wider of normal wp-admin (160px) but narrower than normal calypso (272px). This creates some "congestion" in Calypso cause Site, Nudges, Site Switcher components have been designed with a wider sidebar. Should we make the sidebar wider?

You can check the current behaviour by adding `?flags=nav-unification` in calypso production.

Site Card | Nudges | Site Switcher
-------|------|------
![](https://cln.sh/ybn2Ke+) | ![](https://cln.sh/6RvhKH+)|![](https://cln.sh/8TXfBs+)

cc: @sfougnier , @lcollette

**Comment by getdave** [comment]
@sfougnier confirmed it will be widened to 272px.
