### ISSUE TITLE
Sites: layout issue in Safari (mobile, desktop) for `all-sites-icon` icons

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#4691]
#### Browser / OS version
Mobile Safari, desktop Safari (I tested with Safari 9.1 on OS X 10.11.4 and iPhone 6+ with iOS 9.3.1).

#### Steps to reproduce
1. Starting at URL: example.wordpress.com/stats/day — use a WP.com account that has more than 7 or 8 sites. The sites should have at least one custom Site Icon.
2. Click "My Sites" in toolbar.
3. Then click "Switch Site" to see all the sites.
4. Look for the row of icons under "All My Sites" at the top of the site picker.

#### What I expected
The row of icons should align.

#### What happened instead
After 7 icons, the next icons "dip" down a few pixels.

<img src="https://cloud.githubusercontent.com/assets/66797/14477903/f4c9d2de-00c5-11e6-8500-fd542dc663b9.png" width="480" />

Note: with no custom Site Icons, the layout looks as expected.

<img src="https://cloud.githubusercontent.com/assets/66797/14477893/df38c2f4-00c5-11e6-83e3-69b5df8bdc41.png" width="480" />

**Comment by lancewillett** [comment]
Testing in Firefox and Chrome (latest stable versions for OS X) — this does not occur, seems to be isolated to Safari.

**Comment by lancewillett** [comment]
You can see this in https://wpcalypso.wordpress.com/devdocs/app-components with Safari on Mac easily:

![safari-alignment](https://cloud.githubusercontent.com/assets/66797/14832855/220f3f72-0bb1-11e6-96fa-9069defd14f0.png)

**Comment by mtias** [comment]
I don't have an example with sites without icons to replicate, the function is supposed to exclude sites with no icons set.
