### ISSUE TITLE
Premium Content Block: Unexpected Block Recovery and Invalid Content

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46917]
It looks like a recent change to the Premium Content Block may be causing some issues.

### Errors and Unexpected New Buttons with existing content

If you had the Premium Content block on your site with separated subscribe and login buttons, like so …

![image](https://user-images.githubusercontent.com/545779/97603188-28065280-19da-11eb-83cc-7d01eedd0e0a.png)

Two additional "Subscribe and Log In" buttons are now appearing at the bottom of the block.

![image](https://user-images.githubusercontent.com/545779/97603279-42403080-19da-11eb-9f2c-95ba0aec801d.png)

The Editor will surface this error message.

![image](https://user-images.githubusercontent.com/545779/97603321-5126e300-19da-11eb-80ca-db7a9162f718.png)

Clicking the "Attempt Block Recovery" button will not provide any response.

### Errors when editing block content

The root issue appears to be a change to how the Subscribe and Log In Buttons work.

It’s possible to copy the subscribe button to a different location in the block — a welcome feature of editing — in order to separate them in different designs.

![image](https://user-images.githubusercontent.com/545779/97603662-aa8f1200-19da-11eb-991b-4f9fb4fb0cc2.png)

But when removing the initial subscribe button an error will be thrown by the block without explanation.

![image](https://user-images.githubusercontent.com/545779/97603794-c98da400-19da-11eb-9de7-70365fee7906.png)

There are also seems to be an issue with the availability of the premium content buttons at different plan levels.

In an atomic test site with the ecommerce plan I have the Premium Content Buttons available as blocks to insert.

![image](https://user-images.githubusercontent.com/545779/97603948-f04bda80-19da-11eb-9f71-58142cf519f0.png)

But in another atomic test site on the business plan I do not.

![image](https://user-images.githubusercontent.com/545779/97604005-048fd780-19db-11eb-975e-64225892c9e2.png)

Additionally, it's possible to start editing the text in the subscribe button but the block will always revert back to "Subscribe".

**Comment by davipontesblog** [comment]
user report here 3446160-zd-woothemes

**Comment by apeatling** [comment]
Fixed with #46924. Waiting on a Patterns Toolkit release now.
