### ISSUE TITLE
Premium Content Block: Visual issues with upgrade and connection notices

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46923]
There's a few visual issues with the initial states of the premium content block when inserted on different plan levels.

### Upgrade notices

On a site with a free plan we wind up creating multiple different upgrade notices when first inserting the Premium Content Block.

![image](https://user-images.githubusercontent.com/545779/97615387-3dcf4400-19e9-11eb-9ba0-0497cf82912a.png)

Here, both the placeholder and the banner offer the same message.

![image](https://user-images.githubusercontent.com/545779/97615510-65bea780-19e9-11eb-988d-b6a6f9440fa3.png)

And the banners here are similar but wasn't sure about the different font weights.

![image](https://user-images.githubusercontent.com/545779/97615628-90a8fb80-19e9-11eb-9b27-3d233c153368.png)

### Connection notice

The bottom padding in this notice relative to the top looked off on sites with a plan.

![image](https://user-images.githubusercontent.com/545779/97615716-ad453380-19e9-11eb-8516-27ab0c993a7f.png)

**Comment by apeatling** [comment]
Adding this to supporting patterns backlog because we'll want to tackle the placeholder screen in the block as part of reducing this.

**Comment by apeatling** [comment]
There is also an upgrade banner when you select the buttons. I'm not sure what is going on with the read more notice that breaks apart the buttons:

<img width="762" alt="Screen Shot 2020-11-02 at 10 52 40 AM" src="https://user-images.githubusercontent.com/1464705/97907058-880e3900-1cf9-11eb-9ad4-f8a37d10cc46.png">

**Comment by ianstewart** [comment]
Related issue with the Payments Block:

https://github.com/Automattic/wp-calypso/issues/46884

**Comment by apeatling** [comment]
Closing this one because the placeholder and notice banner have been addressed.
