### ISSUE TITLE
Focused Launch: avoid using @wordpress/core in package hooks in order to get/set site title

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46956]
Currently the `useDomainSearch()` and `useTitle()` hooks get/set the site title by accessing `core` functions. In particular:
- https://github.com/Automattic/wp-calypso/blob/204b43c25d3064be47e48edc0fa066c59a29711a/packages/launch/src/hooks/use-domain-search.ts#L18
- https://github.com/Automattic/wp-calypso/blob/204b43c25d3064be47e48edc0fa066c59a29711a/packages/launch/src/hooks/use-title.ts#L17
- https://github.com/Automattic/wp-calypso/blob/204b43c25d3064be47e48edc0fa066c59a29711a/packages/launch/src/hooks/use-title.ts#L23-L24

The new hooks introduced in https://github.com/Automattic/wp-calypso/pull/46881 should be used instead.

**Comment by ciampo** [comment]
Reopening as there are still changes to be made in `packages/launch/src/hooks/use-domain-search.ts`

**Comment by razvanpapadopol** [comment]
Fixed at https://github.com/Automattic/wp-calypso/pull/47141/files#diff-fd3904ca53e493ed641e3deffd5efb5fd5a320c2aa489342a0c820f6dc573044
