### ISSUE TITLE
Notifications: Core Preformatted block does not render correctly.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46962]
The core Preformatted block does not render correctly in notifications.

Front-End | Email | Notifications
--- | --- | ---
<img width="500" alt="Screen Shot 2020-10-30 at 10 05 50 AM" src="https://user-images.githubusercontent.com/349751/97735572-bab8f700-1a97-11eb-958f-88a071f003ec.png"> | <img width="500" alt="Screen Shot 2020-10-30 at 10 05 35 AM" src="https://user-images.githubusercontent.com/349751/97735585-be4c7e00-1a97-11eb-9149-e0d94eb8eca4.png"> | <img width="500" alt="Screen Shot 2020-10-30 at 10 05 14 AM" src="https://user-images.githubusercontent.com/349751/97735612-c86e7c80-1a97-11eb-8c94-70a3b94a526a.png">

**Comment by kwight** [comment]
Likely related to #46961 .

**Comment by mmtr** [comment]
Fixed on https://github.com/Automattic/wp-calypso/pull/46965, D52422-code and D52453-code.
