### ISSUE TITLE
Reader: rename all references to "Tag" as "Topics

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#46966]
Let's be consistent with the mobile apps and the wordpress.com/topics pages

This also sets us up for changing our topics to be more than just user supplied tags/categories.

**Comment by gibrown** [comment]
shhhhh

**Comment by davemart-in** [comment]
Gonna close this one for now Greg. Happy to re-open if additional customers report it or if someone wants to work on it.
