### ISSUE TITLE
Reader: Handle/Define what to do with disconnected Jetpack sites

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#46974]
If a Jetpack site is disconnected (but still online), a number of things break:
- the feed breaks
- subscribing to it breaks

I'm not sure what the right behavior is here. Maybe it is just to inform the user that the site is disconnected?

**Comment by gibrown** [comment]
shhhhhh

**Comment by jordesign** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/22911
