### ISSUE TITLE
Block Inserter: Legacy blocks are quite prominent

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#46979]
From @simison: Consider you’re first time WordPress user and see “Shortcode” or “Classic” blocks. They’re great to have, but perhaps a bit confusing as-is since they require being familiar with pre-2018 WordPress?

<img width="455" alt="legacy" src="https://user-images.githubusercontent.com/87168/106296653-a03f1700-625a-11eb-8269-590a75070257.png">

Ideas: 
- Move these blocks to the bottom of the picker in some “Legacy” category?
- Consider hiding them by default and have an option to show them?
- Introduce an “Advanced” category for Shortcode, Classic, Embed, HTML, and Markdown blocks?
- Improve block descriptions to give a bit more context of what these blocks are?

Note: be mindful of users who just switched to Gutenberg from the calypso classic editor. They might need these blocks to be more prominent.

**Comment by simison** [comment]
@ianstewart @apeatling what do you think if we simply disable these advanced blocks on block manager? They're still accessible but more hidden. There's probably a list of few blocks like this that are not necessary on .com (things like WordPress.tv embed). We would need to give heads-ups to happiness/docs people beforehand, of course.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/87168/107507036-a95bac80-6ba7-11eb-97a9-57f70e34d704.png">


Hat tip Matías for the idea.

**Comment by ianstewart** [comment]
- Would this be for new users only? 
- Would this impact imports from WordPress sites that had Classic Blocks in them?

**Comment by simison** [comment]
> Would this be for new users only?

I think it's better and easier to be consistent and just do it for everyone. I think it's more important not to teach new users legacy things like shortcodes, but good to nudge older customers out of their habits too. 😁 

> Would this impact imports from WordPress sites that had Classic Blocks in them?

The blocks would still remain functional in content, they just wont appear in the block picker by default.

**Comment by ianstewart** [comment]
I think I'd prefer changing the sort order on them vs hiding them. There may be instances for engaged users where they're following a tutorial, plugin instructions, theme instructions for shortcodes or classic block support and may still need it. If it's not possible to change the sort order we should figure that out. :D I think we already should do it for things like the Text category …

![image](https://user-images.githubusercontent.com/545779/108559440-f420a700-72c0-11eb-8d75-3b2d47c618a5.png)

… where Paragraph should likely be the first block and Table higher up perhaps.

**Comment by simison** [comment]
> I think we already should do it for things like the Text category …

That's a bug actually, fixed in the next Gutenberg version: https://github.com/WordPress/gutenberg/pull/28945
