### ISSUE TITLE
Custom font size creates in-line CSS, which breaks responsiveness.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#46970]
#### Steps to reproduce

1. Activate a newer theme, like Maywood (all of the themes use different font sizes here, so let's go with Maywood, for testing).
2. Create a page, and add a Paragraph Block at the top with some content. Give it a font size of HUGE (34.56px).
3. Add a separator, and add a new Paragraph Block with some more content. Give it a font size of 35, which is just larger than the default HUGE (these numbers are Maywood specific - other themes will require other numbers to replicate).
4. Publish the page. Adjust the page so it's mobile width, or view the page on mobile.
5. The HUGE font size uses the CSS class has-huge-font-size, which adjusts to 28.8px on mobile, making it a bit more mobile friendly.
6. The Custom font size is written in-line, so it stays 35, regardless of the size of the screen viewing it. This can cause issues on mobile sites when a user is developing looking specifically at the desktop screen size. 

#### What I expected
I'm not sure what the best way to manage this is, but custom font sizes are not mobile responsive. 

#### What happened instead
Default predefined font sizes are responsive, but custom font sizes are added in as in-line CSS, and are not responsive.

#### Browser / OS version
All

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30731356/97747385-1f308200-1aa9-11eb-925c-1c6dbb68f454.png)

![image](https://user-images.githubusercontent.com/30731356/97747419-2bb4da80-1aa9-11eb-97e8-6dac11092b97.png)

#### Context / Source
#user-report

**Comment by yansern** [comment]
There is an ongoing PR to add relative units to font sizes on gutenberg core.
https://github.com/WordPress/gutenberg/pull/25825
https://github.com/WordPress/gutenberg/issues/23323

Moving this to "Being Fixed Elsewhere" column.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

Currently, one of the mentioned issue in Gutenberg has been closed while the other remains open. 
I think there is no need to hold this issue open in our repository and so I am closing this with the label `Closed - Won't Fix`.
If this issue should remain open, please feel free to re-open this bug.
