### ISSUE TITLE
Headstart: Shoreditch Theme Missing Content Upon Headstart

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#46993]
#### Steps to reproduce

1. Activate the Shoreditch theme on a WordPress.com site https://wordpress.com/theme/shoreditch
2. Headstart the site to add the Shoreditch theme demo content

#### What I expected

I expected the site to match the Shoreditch demo site: https://shoreditchdemo.wordpress.com/

#### What happened instead

The site received three very basic pages and does not match the demo site.

#### Screenshot / Video

![Annotation on 2020-11-02 at 10-11-57](https://user-images.githubusercontent.com/30727666/97818012-0071fb80-1cf4-11eb-896c-af2a9f6dda37.png)

Screenshot showing entire homepage upon headstart.

#### Context / Source

#user-report #25333501-hc

cc @ramonjd

**Comment by ramonjd** [comment]
Possible related: https://github.com/Automattic/wp-calypso/issues/46299

**Comment by ramonjd** [comment]
I had a quick look at this today. The headstart annotations for https://shoreditchdemo.wordpress.com/ where generated in 2018 and contain copy that is different from the site itself.

So I tried to regenerate them and then run headstart over a test site using this new annotation, but the copy was different again.

Not sure what's going on yet, but the next step would be to find out what and how headstart is generating from shoreditch

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/52757
