### ISSUE TITLE
Marketing: Google Analytics Tracking Code Misplaced

### ISSUE THREAD

**Issue by JenSwish** [Automattic/wp-calypso#46992]
Seems related to Issue #46675. User implemented GA4 tracking about 2 days ago and has had visitors, but GA is not showing any traffic. Checked placement of GA tracking code and is outside of the `<head>`. 

### Steps to reproduce

1. Add GA4 Measurement ID via Tools > Marketing > Traffic. Save your changes.
2. Look for GA4 Measurement ID in your site by searching in the inspector for the G-XXXXXXXXXX code.
3. Is currently placed inside the `<body>` tag, should be placed in `<head>`.
4. Tried with both UA and GA4 tag, both produce the same results.

#### What I expected

To see the following in the `<head>` tag: 

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXXXX');
</script>
```

#### What happened instead

Seeing the following inside the `<body>` tag:

```
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-181260285-1']);
    _gaq.push(['_trackPageview']);

    function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>
```

#### Browser / OS version

**Browser:** Chrome 86
**OS:** OS X 10.15.7

#### Screenshot / Video

![See screenshot here: https://snipboard.io/JMh8pa.jpg](https://snipboard.io/JMh8pa.jpg)

#### Context / Source

- Discovered issue while using [Google Tag Assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk).
- 3453229-ZD

**Comment by cathymcbride** [comment]
Some relevant info here: 231-gh-dotcom-manage

**Comment by lakellie** [comment]
Another user report in #25651728-hc

**Comment by getdave** [comment]
I'm taking a look at this now.

**Comment by getdave** [comment]
Latest status appears to be p58i-9Dr-p2#comment-48258

**Comment by getdave** [comment]
I can confirm 

* the tag is still misplaced on Production at this time. Looks to be before closing `</body>` tag.
* when setting up a _fresh_ site with a _fresh_ Analytics profile the correct code for G4 is added for _Simple_ sites:

```html

<script async src='https://www.googletagmanager.com/gtag/js?id=G-4PJ12DXFFY'></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-XXXXXXXX'); // redacted
</script>

```

**Comment by kwight** [comment]
This should all be fixed now – see p58i-9Ls-p2
