### ISSUE TITLE
Themes: better labels in list view for thumbnail and popover actions

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#47]
The labels that we use on the Themes view — for thumbnail and in the popup menu actions — could use an update for clarity.

Example URL: https://wordpress.com/design/example.wordpress.com

This is the change:

![screen shot 2015-10-23 at 17 21 50](https://cloud.githubusercontent.com/assets/4389/10698751/935beb38-79aa-11e5-9e83-9f358aa3405f.png)

![screen shot 2015-10-23 at 17 20 53](https://cloud.githubusercontent.com/assets/4389/10698727/7045b052-79aa-11e5-89fe-ff5aa71af4ec.png)

```
Thumb: 
   "View" → WebPreview (Demo)

Popup:
   "Try & Customize" → Customizer
   "Activate" | "Purchase"
   "View" → WebPreview (Demo)
   —
   Details
   Support
```

In terms of the active theme, the thumb label will remain "Customize" and the popup menu will still remain "Customize | Details · Support"

**Comment by folletto** [comment]
We can close this as it got fixed in other work done. We also added the theme sheet page, thus the "View" label was changed to "Info".

Current screenshot:

![screen shot 2016-11-29 at 19 28 06](https://cloud.githubusercontent.com/assets/4389/20725512/fa49f608-b669-11e6-836b-124f88e9d4b4.png)
