### ISSUE TITLE
Masterbar: Resume editing should dismiss after trashing or publishing post outside editor

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#4700]
When trashing a post from within the editor, we should not display the Resume Editing button in the master bar.

__Steps to reproduce:__

1. Navigate to the [post editor](http://calypso.localhost:3000/post)
2. Select a site, if prompted
3. Enter a title
4. Save the post as a draft
5. Trash the post from the editor action bar
6. Navigate to the Reader

_Expected_: Resume editing option not offered
_Actual_: Resume editing button shown in master bar

----

When publishing a post from the posts list screen, we should not display the Resume Editing button in the master bar.

__Steps to reproduce:__

1. Navigate to the [post editor](http://calypso.localhost:3000/post)
2. Select a site, if prompted
3. Enter a title
4. Save the post as a draft
5. Navigate to the Posts list screen
6. Filter to drafts
7. For your most recent draft, click the Publish button

_Expected_: Resume editing option hidden from master bar
_Actual_: Resume editing button remains in master bar

/cc @hoverduck

**Comment by lancewillett** [comment]
Noticed the first case today during an editing session.

1. Started a draft, navigated away (saw the Resume Draft UI pop up, as expected).
2. Went to another area of the app, did some things.
3. Came back to the draft, trashed it.
4. When navigating around /posts and other areas in Calypso still saw the Resume Draft with the trashed post.
5. Only hard refresh got rid of it (Cmd-Shift-R).
