### ISSUE TITLE
Stats: Posts showing published on wrong day after DST change

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#47000]
#### Steps to reproduce

1. Publish a post at 12:02 AM EST (-05 hours)
2. Stats displays the post as being published the day before

#### What I expected
I expected the stats to respect the timezone set for the site and display according to that timezone.

#### What happened instead
It looks like the stats are displayed in a different timezone - perhaps UTC or EDT (-04 hours) which shows the post as being published one day earlier than the site says.

#### Screenshot / Video
<img width="1218" alt="Markup 2020-11-02 at 09 42 35" src="https://user-images.githubusercontent.com/22053773/97842126-c999e680-1cef-11eb-994e-dfafd132a608.png">

#painpoint.
#user-report

Internal Reference: 3330991-zd-woothemes

**Comment by kriskorn** [comment]
Another case here: #24094006-hc

**Comment by cathymcbride** [comment]
Lowering the priority but leaving on the backlog

**Comment by donalirl** [comment]
I believe this also came up in #28266031-hc.

The stats show a time affected by DST even when the site's timezone is set to a region that does not use DST (Phoenix, Arizona.) To reproduce:

1. Set site timezone to Phoenix in Settings → General
2. Go to Stats and click on the Months view.
3. Scroll down to where it says:

Stats for March 2021
Last update: 6:32 PM (Updates every 30 minutes) 

The last update is shown as an hour ahead of the actual time in Arizona.
