### ISSUE TITLE
Unable to access sites, navigate Calypso, or the Reader on Edge 18

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#47001]
Reported via 3443330-zen: User is unable to access any of their sites or navigate through the WordPress.com interface when using Microsoft Edge 18:

>  if I click on other options (stats, edit, my sites, reader, etc.) it goes to that page, but all I get is your "W" logo. Sometimes with a blue band on top, sometimes not. It seems like it's just not loading. I've tried numerous times with both sites, have waited over an hour, and have even taken my laptop elsewhere to use different internet providers. If I click customize, that page loads, but the same happens when I click on any of the options from the menu - it loads the logo and nothing else. I can't even contact you for help. Also I just tried www.wordpress.com and the same thing happens. It's very frustrating that I can't access my sites.

#### Steps to reproduce

I can't reproduce this, opening the issue for tracking purposes.

#### Browser / OS version

```
Operating system Windows 10
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
WebGL supported Yes
Language en-US
Browser size 1227 x 632
Screen size 1242 x 698 (Retina)
Color depth 24 bit
AdBlock enabled No
Your full user agent string is:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
```

#### Screenshot / Video

screenshot available in zen ticket

**Comment by lsl** [comment]
Repro'd in chrome stable (v90) setting a custom UA string to match what we see in this issue.

Discovered this failure mode in #52367 when we included too much version info in .chromedriver_version which is used to set version info in the UA string our e2e tests use. The resulting UA looked like "Chrome/Google Chrome 90.0.0" instead of "Chrome/90.0.0". cc @scinos

Need to trace / debug further but it looks like calypso WSOD's (~, shows WP logo) with anything unexpected in the UA string.

**Comment by lsl** [comment]
Nevermind... had some testing settings blocking things. Still can't repro.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Could not replicate

📌 ACTIONS
- Found this report in the wild, moved to Dotcom Bug Prioritization board
- Closed as could not replicate (please reopen if the issue reoccurs)
