### ISSUE TITLE
Site Language Picker: bug with button styles

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#47017]
When first opening the site-language picker from the Setting screen in Calypso you'll see this button style …

![image](https://user-images.githubusercontent.com/545779/97894371-09fd6280-1cf8-11eb-8b35-1e17894576c8.png)

Pick another language however …

![image](https://user-images.githubusercontent.com/545779/97894418-15e92480-1cf8-11eb-88b6-f19c8a38962d.png)

And the border expands to surround the whole element.

**Comment by michaeldcain** [comment]
I can't reproduce this with what appears to be a new language picker:

<img width="1552" alt="Screen Shot 2021-03-03 at 4 43 05 PM" src="https://user-images.githubusercontent.com/942359/109876268-946eb800-7c3f-11eb-9393-a7726e925a55.png">
