### ISSUE TITLE
Domains: TXT form toggle appears disabled when TXT entry is off

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#47016]
#### Steps to reproduce

1. Starting at URL: `/domains/manage/:site` where `site` has a TXT DNS entry
2. Disable the TXT entry

#### What I expected
The TXT entry should appear disabled but the form toggle should not

#### What happened instead
Both the TXT entry and the form toggle appear disabled. The form toggle _is_ toggleable but it's appearance is that of a disabled one.

#### Browser / OS version
Firefox

#### Screenshot / Video
<img width="738" alt="Captura de Tela 2020-11-02 às 08 30 18" src="https://user-images.githubusercontent.com/24264157/97894093-f72e6200-1ce6-11eb-99f8-8feb1e7383b4.png">

#### Context / Source

Found while working on https://github.com/Automattic/wp-calypso/pull/46945

**Comment by klimeryk** [comment]
PR with fix: https://github.com/Automattic/wp-calypso/pull/49951
