### ISSUE TITLE
Admin Color Schemes Sync Main Issue: have wp-admin color scheme setting inherit from Dotcom Simple setting

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#47039]
> To allow for a unified nav experience, we will deactivate the Admin Color Scheme option, so existing selections will be disregarded. Instead we will make wp-admin aware of the Calypso color scheme selection. As a result color schemes in wp-admin will apply account wide (instead of per-site) just like they already do in Calypso. If there is a Calypso selection, we will display the selected color scheme in wp-admin; otherwise, we will show the default color scheme.

This issue is part of the effort of combining color schemes in the Nav unification project. 
For the approved direction please see https://github.com/Automattic/wp-calypso/issues/45675#issuecomment-714664414.

The aim is to have Atomic sites inherit the admin color scheme from the Dotcom Simple dashboard color scheme setting upon...:

1. Update to setting (most likely via `https://wordpress.com/me/account`).
2. Atomic site creation/provision.

In addition all Atomic sites will require a one time update to set the admin color scheme to match the Dotcom Simple color scheme. 

See also paYJgx-1de-p2#comment-1529

### Sync on Manual Setting Update

- [x] D52376-code - Propagate Calypso color scheme setting to Simple and Atomic sites - note this diff added the code to handle Atomic but it is disabled.
- [x] D54351-code - Enable Admin Color schemes syncing for Atomic sites - enables syncing of Dotcom Simple admin color scheme setting to Atomic (previously disabled in (D52376-code).

#### 1st  attempt
- [x] D54359-code - Create and deploy test job to sync admin color scheme to Atomic on post provision - note this should be gated to work on specific test site IDs only for testing of D53945-code.
- [x] D53945-code - Async job to set Atomic admin color scheme to match Dotcom account setting for **all users on that site** (pairs with D54359-code).

#### 2nd attempt

Following the rollback here are the next steps:

- [x] [Refactor Admin Color Schemes sync process to reduce nested jobs and simplify code](D55304-code) - deployed r219456-wpcom
- [x] Adjust Admin Color Schemes sync async jobs to output more usable errors into Jobs log (see PCYsg-mm-p2#errors-and-job-completion) - deployed in r219463-wpcom
- [ ] [Avoid failures altogether and instead log to `logstash`](D55434-code)
- [ ] [Update sync code to account for Atomic sites which may be unreachable](D55426-code) (see also p9o2xV-1d7-p2).
- [ ] Always return `WP_Error` in sync class to improve error logging and avoid silent exit.

### One Time Update for all Atomic Users

- [ ] Write a one time script to update all WoA users' admin color scheme to match Calypso setting.

**Comment by getdave** [comment]
Don’t the color settings already apply account-wide in Calypso?

So we just need to make WPAdmin use Calypso setting right?

**Comment by frontdevde** [comment]
> Don’t the color settings already apply account-wide in Calypso?

Yes, they do! They don't for wp-admin. We need them too though for both interfaces to behave the same with nav unification. 

> So we just need to make WPAdmin use Calypso setting right?

Yes! We'll need to expose the Calypso setting/selection in a way we can read it from wp-admin. 

> Also where in WPAdmin UI do I set color schemes?

The only way to do this right now is on a WOA site. In every other instance you're redirected to Calypso just as you observed. The plan is to hide that feature completely (see https://github.com/Automattic/wp-calypso/issues/47037 and https://github.com/Automattic/wp-calypso/issues/47038)

**Comment by getdave** [comment]
## Current Plan:

* Don't need to worry about UI in WPAdmin. That will be removed.
* Consume the Calypso setting ~(which is exposed on the REST API endpoint) in WPAdmin.~ directly via `get_user_attribute()` and grabbing the `calypso_preferences` attribute. See 27080-pb/#plain
* Update the WPAdmin user option `admin_color` with the value retrieved from the `calypso_preferences` via the `get_user_option_admin_color` filter.

## Research

* the color scheme appears to be [stored in a user option called `admin_color`](https://github.com/WordPress/WordPress/blob/a940c08357a564e6c20acc3e4647b6cabbaa96ba/wp-admin/includes/misc.php#L944).
* we can [filter the user option using the `get_user_option_{$option}` hook](https://core.trac.wordpress.org/browser/tags/5.5.1/src/wp-includes/user.php#L503)
```php
<?php
add_filter('get_user_option_admin_color', 'myhandlerFunc');
?>
```

**Comment by frontdevde** [comment]
> Perhaps we can retain the existing color scheme option in WPAdmin but simply set it based on whatever comes back from the REST API? We could use a filter to update the option value and ignore whatever is in the DB.

If we can use the existing system in a way where we can just disregard existing values and use the Calypso selection instead, that'd be ideal. We'd want to ensure that if there's no selection Calypso, we'd show the default theme (rather than any previous wp-admin selection).

**Comment by getdave** [comment]
Update: the WPCOM v1 endpoint won't allow user level authentication for remote Jetpack sites (see p1604491148473300-slack-jetpack-crew). 

@obenland as that REST API guru are you able to help me look into this? I'm also going to pen a p2 to ask for guidance.

**Comment by getdave** [comment]
The current direction for this task is available at paYJgx-17t-p2#comment-1391

**Comment by mmtr** [comment]
With the new approach taken that exposes the color scheme as a new property of the XMLRPC response (p9o2xV-FT-p2), all the Atomic sync scenarios should be solved by 587-gh-Automattic/wpcomsh
