### ISSUE TITLE
Color Schemes: Add note to WPAdmin `profile.php` page that points folks to the (new) respective setting in Calypso

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#47038]
This issue is part of the effort of combining color schemes in the Nav unification project. 
For the approved direction please see https://github.com/Automattic/wp-calypso/issues/45675#issuecomment-714664414.

pbAPfg-Ou-p2#comment-1965

**Comment by mreishus** [comment]
554-gh-wpcomsh

**Comment by mreishus** [comment]
Currently waiting for a way to control who sees it and who doesn't on atomic.

**Comment by cpapazoglou** [comment]
Eventually we will keep this in wpcomsh (paYJgx-1cP-p2#comment-1483). It will be triggered by a filter in jetpack `jetpack_color_schemes_loaded` https://github.com/Automattic/jetpack/pull/18034/files .
