### ISSUE TITLE
Nav unification: port over Calypso exclusive color schemes to wp-admin

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#47040]
This issue is part of the effort of combining color schemes in the Nav unification project. 
For the approved direction please see https://github.com/Automattic/wp-calypso/issues/45675#issuecomment-714664414.

https://github.com/WordPress/WordPress/blob/e569358678dd1d3480740e451d546bf8b5ad8101/wp-includes/general-template.php#L4514-L4524

### Reference Issues

* Main Issue #45435
  * Color Schemes Issue + Direction  #45675

**Comment by frontdevde** [comment]
- [ ] Classic Bright
  - [ ] Classic Dark
  - [ ] Classic Blue
  - [ ] Nightfall
  - [ ] Sakura
  - [ ] Aquatic (i.e. former Calypso Ocean)
  - [ ] Sunset
  - [ ] Powder Snow
  - [ ] Contrast

**Comment by mreishus** [comment]
Heads up; in addition to porting them to wp-admin, **all of these schemes need changes in calypso**, too.  

If you turn on one of these schemes in calypso, then turn on the nav-unification flag, you still see the old wp-admin colorscheme in calypso.
* The scope of the scheme's current variable settings needs to be expanded to include `.is-nav-unification`.
* Some additional color variables that only exist in calypso nav unification need to be set.  These are submenu colors which exist in wp-admin and nav unification, but not regular calypso.

It's probably best to do these changes at the same time the scheme is ported to wp-admin so we can be sure they match 1:1.

**Comment by frontdevde** [comment]
Core color scheme style files: https://github.com/WordPress/WordPress/tree/e569358678dd1d3480740e451d546bf8b5ad8101/wp-admin/css/colors

**Comment by frontdevde** [comment]
Closed by https://github.com/Automattic/jetpack/pull/17828
