### ISSUE TITLE
The packages/launch package fails to build due to wrong @wordpress/components types

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#47048]
When I run `yarn run build-packages`, the `@automattic/launch` package makes the task fail:
```
@automattic/launch: $ tsc --project ./tsconfig.json && tsc --project ./tsconfig-cjs.json && copy-assets && npx copyfiles ./styles/** dist
@automattic/launch: src/launch/index.tsx(25,4): error TS2769: No overload matches this call.
@automattic/launch:   Overload 1 of 2, '(props: Props, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
@automattic/launch:     Type 'Element' is not assignable to type 'FunctionComponent<{}> | ComponentClass<{}, any> | undefined'.
@automattic/launch:       Type 'Element' is not assignable to type 'ComponentClass<{}, any>'.
@automattic/launch:         Type 'Element' provides no match for the signature 'new (props: {}, context?: any): Component<{}, any, any>'.
@automattic/launch:   Overload 2 of 2, '(props: PropsWithChildren<Props>, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
@automattic/launch:     Type 'Element' is not assignable to type 'FunctionComponent<{}> | ComponentClass<{}, any> | undefined'.
@automattic/launch:       Type 'Element' is not assignable to type 'ComponentClass<{}, any>'.
```

That's because the `Modal` from `@wordpress/components` is instantiated with `icon` prop that is a JSX element (`ReactNode` type), not a React component constructor (`ComponentType` type):
```js
<Modal icon={ <Icon icon={ wordpress } /> } />
```

That code is correct: the `Modal` implementation uses the `icon` prop as node, not as component:

https://github.com/WordPress/gutenberg/blob/master/packages/components/src/modal/header.js#L30

(to use it as component, the usage would be something like `{ <props.icon /> }`)

It's the `@wordpress/components` type definitions that are wrong: they should declare the `icon` prop type as `ReactNode`, not `ComponentType`.

Cc: @ciampo 

@saramarcondes you recently fixed several type bugs like this: maybe this one was one of them? Do you have any suggestions how to work around the bug until the types are fixed and published at DefinitelyTyped?

**Comment by ciampo** [comment]
cc @alshakero — The types for the `Modal` icon component should have been fixed, do you know why they may still cause errors?

**Comment by ciampo** [comment]
The types were already updated in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49156
And the PR that added the `@automattic/launch` package also updated the `@types/wordpress__components` dependency version (see https://github.com/Automattic/wp-calypso/pull/46686/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)

Have you tried running `yarn install` before `yarn run build-packages` ?

**Comment by jsnajdr** [comment]
> Have you tried running yarn install before yarn run build-packages ?

I didn't 🤦 After I did it now, the types got updated and everything works. Sorry for raising a false alarm!

**Comment by ciampo** [comment]
No worries! Thank you for checking, better safe than sorry!
