### ISSUE TITLE
Nav Unification: How to sync with Jetpack release process?

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#47045]
Since we are planning in shipping the backend code in Jetpack, we need to align with the Jetpack Release dates so that the feature lands on Atomic sites the same time as it lands on wpcom. 

> The Jetpack release will happen on December 1st. As a general rule of thumb, you may expect a Jetpack release on the first Tuesday of each month. Code freeze and first Beta is one week before the release date, on the last Tuesday of the month.

Scheduled Releases
9.2 | 9.3
-------|------
Code Freeze on 2020-11-23|Code Freeze on 2021-01-04 
Beta Release on 2020-11-24|Beta Release on 2021-01-05
Release on 2020-12-01|Release on 2021-01-12

Let's make sure that we have aligned with Jetpack and we have prepared everything they need for a release.

**Comment by cpapazoglou** [comment]
@obenland, @jeherve could please chime in case you have something to add?

**Comment by obenland** [comment]
The endpoint is already in and available to us. The work in #17629 is currently behind a filter and conditional that only activates it on simple sites and atomic. It also requires the masterbar module to be active.
We can use that filter to set visibility of the feature from wpcomsh.

**Comment by cpapazoglou** [comment]
So you are suggesting releasing now (before Nov 23) all the changes we need and handling this feature visibility / availability from a third party plugin _wpcomsh_ which can be released as we please. I assume we should be deploying this toggle in wpcom too right?

**Comment by obenland** [comment]
Yup, that's right!

**Comment by cpapazoglou** [comment]
@obenland Let's target **Code Freeze on 2020-11-23** for having in Jetpack the most stable solution dependant on a filter https://github.com/Automattic/jetpack/pull/17629 

@frontdevde, @getdave is there anything else we can ship to Jetpack till this date?

**Comment by frontdevde** [comment]
> @frontdevde, @getdave is there anything else we can ship to Jetpack till this date?

Calypso Color Schemes maybe should we we decide they will live in Jetpack. Could either be also be filtered so it only shows on Simple or Atomic, or maybe Jetpack would be interested to provide other Jetpack folks with those Color Schemes as well as a feature. Working on the color scheme generation in this draft PR https://github.com/Automattic/jetpack/pull/17828.

**Comment by cpapazoglou** [comment]
> > @frontdevde, @getdave is there anything else we can ship to Jetpack till this date?
> 
> Calypso Color Schemes maybe should we we decide they will live in Jetpack. Could either be also be filtered so it only shows on Simple or Atomic, or maybe Jetpack would be interested to provide other Jetpack folks with those Color Schemes as well as a feature. Working on the color scheme generation in this draft PR [Automattic/jetpack#17828](https://github.com/Automattic/jetpack/pull/17828).

IIRC, we are going to enable this feature (hiding scheme selection, more color-schemes) to simple & atomic customers only - not self hosted. So, yes it needs to be filtered too (by the same exact filter).

**Comment by obenland** [comment]
> by the same exact filter

Filters are cheap, feel free create a context-specific filter for this

**Comment by cpapazoglou** [comment]
> > by the same exact filter
> 
> Filters are cheap, feel free create a context-specific filter for this

That's true. I totally forgot that we have decoupled **color-schemes** from **nav-unification**! Thanks for chiming in @obenland !

**Comment by frontdevde** [comment]
> IIRC, we are going to enable this feature (hiding scheme selection, more color-schemes) to simple & atomic customers only - not self hosted. So, yes it needs to be filtered too (by the same exact filter).

The "hiding scheme selection" portion should definitely be limited to Simple & WoA customers.

Initially, the "more color-schemes" portion as well. That said, this portion by itself might be interesting to Jetpack as a feature i.e. adding more color schemes to wp-admin. Providing additional wp-admin color schemes to all Jetpack users might be a nice value add, especially as it's "for free" in terms of development overhead for the Jetpack team as we're working on it (and it needs to be maintained in the future for wpcom anyway).

Just thinking out loud here though, uncertain of what Jetpack wants. Maybe @jeherve has thoughts on this?

> Filters are cheap, feel free create a context-specific filter for this

Sounds good 👍

**Comment by jeherve** [comment]
> Providing additional wp-admin color schemes to all Jetpack users might be a nice value add, especially as it's "for free" in terms of development overhead for the Jetpack team as we're working on it (and it needs to be maintained in the future for wpcom anyway).

Yeah, I think that makes perfect sense. I don't see any reason to not offer this to Jetpack users, as long as, like you mentioned, we do not hide the scheme selection by default, and as long as everything we do can be disabled with a filter.

**Comment by jeherve** [comment]
@obenland @frontdevde @getdave Do y'all have a list of things that **should** be in before Monday evening?

https://github.com/Automattic/jetpack/pull/17833
https://github.com/Automattic/jetpack/pull/17629
https://github.com/Automattic/jetpack/pull/17828

Is there anything else I am missing?

@pablinos Would https://github.com/Automattic/jetpack/pull/17826 qualify as part of that project? Would you want this in 9.1?

Thank you all!

cc @anomiex who's leading the release this time around.

**Comment by obenland** [comment]
Automattic/jetpack#17833 would be helpful, yes.

Automattic/jetpack#17629: I wouldn't be heartbroken about it if it didn't get in. We just fixed another bug in it and it needs follow-up work anyway.
Automattic/jetpack#17828 looks like it might not be ready in time

**Comment by frontdevde** [comment]
Automattic/jetpack#17828 won't be ready for 9.2, we're aiming for the 9.3 release. 
We discussed this in our Backlog Grooming meeting, I should've added a note here as well.

**Comment by cpapazoglou** [comment]
It seems both `nav-unification` and `color-schemes` are aiming for the 9.3 release.
As a reminder Code Freeze is on 2021-01-04, since most of us will be AFK during Christmas we should have completed all necessary works till **Dec 18** !

Let's do it!
