### ISSUE TITLE
Marketing banner: iterate on copy

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#47042]
Request by @rickybanister on suggestion by @pablohoneyhoney:

Change copy of Marketing banner to 

"Create your website **with** WordPress.com"

**Comment by obenland** [comment]
See `Marketing_Bar::get_cta_text_element()`

**Comment by obenland** [comment]
@lcollette Is this something Manage Design would feel comfortable updating?

**Comment by lcollette** [comment]
@obenland For sure. Completely missed this ping and for that, I apologize. 

@sixhours Mind grabbing this? :)

**Comment by sixhours** [comment]
Updated here: D57583-code
