### ISSUE TITLE
WP.com/new Design Screen: Remove Premium Labels on Doyle and Edison

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#47059]
A while back we added "Premium" labels to the Doyle and Edison designs on this screen.

![image](https://user-images.githubusercontent.com/545779/98008015-ac314f00-1db9-11eb-8add-108f701f8da0.png)

With [a Starter Design ready to go that uses the recurring payments blocks](https://github.com/Automattic/wp-calypso/issues/43587) let's remove those labels from these designs in favour of (later, for a second task) that Starter Design.

**Comment by razvanpapadopol** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/49251
