### ISSUE TITLE
Themes: checkout Thank You page in purchase flow is skipped with a flash of blue

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#4705]
#### Steps to reproduce
1. Starting at URL: `/design?s=mood`
2. Assuming you haven't purchased it yet, purchase Mood for your site, going through the payment process
#### What I expected

To see Checkout's "Thank You" page, and only then moving on.
#### What happened instead

There was a flash of blue, likely as the expected page loaded, and then I was taken straight to the theme's own Thank You modal, inside the Theme Showcase.
#### Browser / OS version

Chrome, latest; OS X, latest.

**Comment by lancewillett** [comment]
I can reproduce this, testing with Mac-n-Chrome.

Here's a screencast where you can see the blue flash:

![quick-checkout](https://cloud.githubusercontent.com/assets/66797/15405243/eea7dab0-1db5-11e6-9269-ac52aa169891.gif)

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue as shown in the video above.

**Comment by rachelmcr** [comment]
I confirmed this is still an issue as shown in the original report. Also, as @ockham noted in another report of this issue:

> This one is known, and probably because of the `defer` in [this action](https://github.com/Automattic/wp-calypso/blob/2acf737cc692502ff0af9eeaeb8b67e7471131a7/client/state/themes/actions.js#L253-L270). Unfortunately, it's even more broken without the `defer` -- I tried to remove it a while ago and failed miserably. We decided to live with it for now since we really want to get our current milestone out the door, and were considering this issue relatively minor while requiring quite a bit of research to fix.

**Comment by davipontesblog** [comment]
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment]
Confirmed that this still happens after the new Checkout flow launched, but it's not really a bug with Checkout.

I don't know what the preferred behavior here is. Our Thank You pages aren't really helpful to someone that just purchased a Theme, and as noted in the comment above, it's a Theme Showcase bug. I'd recommend wontfixing it unless there's a team prioritizing work on the Showcase or Thank You pages. @rickybanister

**Comment by michaeldcain** [comment]
With the retirement of Premium Themes, I'm going to close this.
