### ISSUE TITLE
Editor: make it easier to find your way back to dashboard

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#47054]
**Update:** as a current action item, [let's just rename "My Home" to "Dashboard"](
https://github.com/Automattic/wp-calypso/issues/47054#issuecomment-721232098).

---

Currently, to get back to the dashboard from the editor, you need to click W icon and then "My home":

<img width="345" alt="Screenshot 2020-11-03 at 15 46 35" src="https://user-images.githubusercontent.com/87168/97992788-d7cd2d00-1deb-11eb-9676-463bedf60dac.png">

<img width="353" alt="Screenshot 2020-11-03 at 15 46 48" src="https://user-images.githubusercontent.com/87168/97992801-da2f8700-1deb-11eb-86e6-d64efd735c21.png">

In the site editor in the core, the "back to dashboard" item is called "Dashboard":

![fse-navigation-sidebar](https://user-images.githubusercontent.com/87168/97992690-b53b1400-1deb-11eb-92d8-e83c03a5769a.gif)

## Questions

- Would "Dashboard" be more clear than "My home"?
- How could we make it more clear what happens with W icon? Can the tooltip be more clear? Maybe just copy changes?

cc @dubielzyk since this touches editor onboarding. Do customers know how to get back when they first see the editor?

@rickybanister any quick changes we could do to make this clearer?

**Comment by rickybanister** [comment]
I'd support making the link say 'dashboard' since gutenboarding folks may land in the editor before they ever see Calypso and start to understand the makeup of the pages there. Ideally we start to pull in the entire core editor sidebar as it's ready, but this is a small enough change.

**Comment by dubielzyk** [comment]
>Do customers know how to get back when they first see the editor?

I've looked into this and whether we explain it or not. A part of me thinks that this should be obvious in the UI though. I've very very briefly looked at this before:
![image](https://user-images.githubusercontent.com/2896062/98179849-10f6c180-1f00-11eb-81b7-13398915799c.png)

It's not a great solution, but I still feel like if we have to explain to people how to get back to their dashboard, then something is wrong with the UI.

**Comment by simison** [comment]
>  if we have to explain to people how to get back to their dashboard, then something is wrong with the UI.

I agree. @mtias @vindl @jameskoster @shaunandrews thoughts? I've also felt this to be weak point of W icon design in site editor.

**Comment by jameskoster** [comment]
Unpopular opinion incoming – the problem here is that the W logo does nothing to indicate "Navigation". 

<img width="532" alt="Screenshot 2020-11-05 at 13 13 21" src="https://user-images.githubusercontent.com/846565/98245393-c3626f00-1f68-11eb-857e-f239a6959d7d.png">

**Comment by simison** [comment]
> Unpopular opinion incoming – the problem here is that the W logo does nothing to indicate "Navigation".

My thoughts exactly and your solution is actually my personal preference over site or W icon, but you were bolder to say it out loud. :-D

**Comment by vindl** [comment]
I also suspect it's not going to be obvious in its present state.

Another thing to consider is that we are displaying the site icon instead of the W icon if it's set. That's not useful for navigation either, but it will be useful for telling which site you are currently editing at a glance. We had something similar in Calypso classic editor before in a form of site card.

**Comment by jameskoster** [comment]
> My thoughts exactly and your solution is actually my personal preference over site or W icon, but you were bolder to say it out loud. :-D

Yolo :D 

@vindl that is true. To be honest I believe this issue is one of many examples which indicate that the Top Bar iA probably needs to be re-thought at some point, so that it is able to scale more elegantly and accommodate not only the features we've added to it quite recently, but those we intend to add in the future as well.

`</soapbox>`

**Comment by simison** [comment]
Alright so at least we can rename the label to "Dashboard" for clarity. I'll add to create maintenance board and updated the issue description.

Bigger changes could be discussed with core design instead. @jameskoster interested to bring this convo there?

**Comment by jameskoster** [comment]
Yes, when the time is right :D

**Comment by andrewserong** [comment]
It seemed quicker to whip up a PR than worry about triaging this one so I've had a go in #47539 of just changing the My Home text to Dashboard.
