### ISSUE TITLE
Choose Specific Posts within Blog Posts Block displays only four posts

### ISSUE THREAD

**Issue by kylemcph** [Automattic/wp-calypso#47067]
#### Steps to reproduce

1. Start a Premium plan site on WordPress.com and publish at least five blog posts. I was not able to replicate on a free or Personal plan site.
2. Add a new page
3. Add the [Blog Posts Block](https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/)
4. Click `Choose Specific Posts`
5. Add at least five specific blog posts to block 
6. Publish page

#### What I expected

All five blog posts to display on the published page.

#### What happened instead

Only four blog posts display.

#### Screenshot / Video

Posts selected to display within block settings: 
https://d.pr/i/5Rbs1h

Posts displayed on published page: 
https://d.pr/i/HwI6tn

#### Context / Source

User brought this to my attention because the "Load More" button on their page was loading duplicated posts, and some posts were missing. This is reproducible as well. 

#### Steps to reproduce (continuation from above's steps): 

1. Ensure site is set as public
2. Go back to and refresh page editor where blog posts block from above was added
3. Edit blog posts settings by toggling `Choose Specific Posts` option off, then toggle `Show "More" Button` on, then toggle `Choose Specific Posts` back on. 
4. Specific posts should be repopulated with posts selected earlier. 
5. Update changes and view live page.

#### What I expected

Load More button loads additional posts.

#### What happened instead

Load More button loads the same four posts again. 

#### Additional Notes: 

- "Show more button" option only exists when the site is set as public.
  - Private site screenshot: https://d.pr/i/L1evVO

  - Public site screenshot: https://d.pr/i/Fs7uSM

**Comment by kylemcph** [comment]
User reached out in 24794525-hc about this, follow-up ticket 3457739-zen.

**Comment by cathymcbride** [comment]
This looks like https://github.com/Automattic/wp-calypso/issues/46700 but showing even fewer blog posts? Is there anything these users' sites have in common?

Also, can you break out the show more issue into a different issue?

**Comment by kylemcph** [comment]
>This looks like #46700 but showing even fewer blog posts? Is there anything these users' sites have in common?

@cathymcbride Looking at #46700 that is absolutely the same issue. My test site only showed four posts because Settings > Content Types > Blog Posts was only set to display 4 per page. When that number was increased, the blog posts displayed on the published page. 

That explains why I was only able to reproduce on my test Premium plan site, as my other sites had a greater number of posts set to display.

>Also, can you break out the show more issue into a different issue?

Yes, done. These are actually two separate, yet related issues. I opened them at #47086 and #47087.

**Comment by cathymcbride** [comment]
OK! I'm going to close this one in favor of the original issue and the new ones you have logged.
