### ISSUE TITLE
"Automatically fit text to container" AMP setting producing bad markup in the paragraph block

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#47076]
#### Steps to reproduce

1. Create or edit a post or page;
2. Write something in the paragraph block
3. In the settings pane for the block, under the "AMP Settings" section, enable the "Automatically fit text to container" setting; 
4. Publish or preview the page;
5. Notice that a portion of the paragraph markup is not interpreted as HTML and is rendered as text, breaking the actual markup and the rendered content _(see the gif recording below)_.

#### What I expected

I expect the paragraph block to render correctly when the "Automatically fit text to container" setting is applied.

I also tested in a vanilla WP.org instance with Gutenberg 9.2.2 with the amp-wp plugin (v2.0.5) and it works as expected. The markup in the editor, when switching to the HTML view (`edit as HTML`), looks like this:

![orggbampworkswell](https://user-images.githubusercontent.com/81248/98048466-59748900-1df3-11eb-8a96-91c079a79c48.png)

#### What happened instead

The paragraph block rendering brakes in the frontend when the "Automatically fit text to container" setting is applied to it.

By verifying the markup for the block in the editor, it's quite different from the one in the vanilla WP.org instance:

![simplesitebadmarkup](https://user-images.githubusercontent.com/81248/98048590-9c366100-1df3-11eb-9e8a-54c4a4245d0b.png)

What strikes me as odd is the use of a `value` attribute in a `<p>` element and the its contents are set the to the `<amp-fit-text>` element.

#### Browser / OS version

Ubuntu 18.04, Firefox Quantum 83.0b7, Gutenberg 9.2.2

#### Screenshot / Video

![ampissue](https://user-images.githubusercontent.com/81248/98048946-5c23ae00-1df4-11eb-9638-ed515fc18cca.gif)

![renered](https://user-images.githubusercontent.com/81248/98050707-ea4d6380-1df7-11eb-9874-65e46d538fe6.png)

#### Context / Source

Originally brought to our attention by @ajaykj on behalf of a user. Check the original Slack convo here: p1604425209199300-slack-C015AL3QL7M.

**Comment by apenasjoao** [comment]
Hello everyone

I am sending a follow up that the [ticket](https://woothemes.zendesk.com/agent/tickets/3460314) for this issue has returned from On-Hold status. I am sending a follow-up to the customer that we are still working on the issue. I will set another 12-hour timer for it to be reopened.

**Comment by NatzJoy** [comment]
Hello everyone

I am sending a follow up that the ticket for this issue has returned from On-Hold status. I am sending a follow-up to the customer that we are still working on the issue. I will set another 12-hour timer for it to be reopened.

**Comment by formosattic** [comment]
Also reported at pbEMJv-nP-p2

**Comment by inaikem** [comment]
Closing as unable to replicate on Simple, Atomic or Self hosted sites. Please reopen if you are able to replicate the issue!
