### ISSUE TITLE
Editor: keyboard shortcuts button is viewable on a touch device 

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4708]
#### What I expected

I did not expect to see the keyboard shortcuts button on my device that did not have a keyboard.

#### Screenshot / Video

![7rjkea1aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/618551/14502656/f8c5f80c-0171-11e6-80c4-8a3c2449476e.png)

**Comment by nylen** [comment]
This is not possible.  The browser doesn't offer an API to determine whether the device has a keyboard.

There are also lots of edge cases like touch+keyboard laptops, even devices where the keyboard is sometimes available and sometimes not.  More info about why hardware capabilities detection in general is problematic - http://stackoverflow.com/a/18001239/106302 and our `touchDetect` in particular - #1479
