### ISSUE TITLE
Signup: Users marked as spam see HTML in the error message

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#471]
When adding a site for a user that had blog marked as spam you see:

![screen shot 2015-11-23 at 08 55 41](https://cloud.githubusercontent.com/assets/699132/11331826/04dfd5f8-91c0-11e5-8322-505743062d0b.png)

We should strip this HTML.

**Comment by fabianapsimoes** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/246.
