### ISSUE TITLE
Checkout: routing sometimes mistakes site ID for product ID and displays an error

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#47109]
It appears that if you reach checkout using the `/checkout/:siteId` route, it sometimes confuses this with `/checkout/:productSlug` and displays an error:

![image](https://user-images.githubusercontent.com/2036909/98140590-9abc7580-1e93-11eb-87a8-169340a28714.png)

1. Created a site at wp.com/new
1. Clicked launch in the Editor.
1. Got the fancy gutenboarding-style launch flow
1. Picked the business plan, skipped domain
1. Saw that error on the checkout screen

props to @ianstewart for finding this.

**Comment by sirbrillig** [comment]
[This route](https://github.com/Automattic/wp-calypso/blob/b1fcc753507d43075a887071db8aa9cc235535e1/client/my-sites/checkout/index.js#L135) is probably what's being triggered, which gets sent to [this logic](https://github.com/Automattic/wp-calypso/blob/b1fcc753507d43075a887071db8aa9cc235535e1/client/my-sites/checkout/controller.jsx#L54) to determine if it's a site or a product.

**Comment by sirbrillig** [comment]
If possible, we may want to consider removing the ability of that route to accept a product, because I don't know of anywhere that it's used that way (we'd want to make sure I'm right about that though).

**Comment by sirbrillig** [comment]
This bug was created by https://github.com/Automattic/wp-calypso/commit/ea46a2486eab21393445e195d1769ed146ebadd5 (part of https://github.com/Automattic/wp-calypso/pull/34862). Apparently there are uses of `/checkout/:product`, but I don't know if this is a good idea because how can we tell the difference between a product slug and a site ID?

**Comment by sirbrillig** [comment]
ping @niranjan-uma-shankar who was the author of that commit to see if you have any ideas about how to fix this situation. Can we introduce a different URL structure for whatever https://github.com/Automattic/wp-calypso/pull/34862 is supposed to do, rather than overloading `/checkout/:domain`?

**Comment by Robertght** [comment]
I can't seem to replicate this anymore, but I'm wondering if someone from the @Automattic/shilling team can review this.

**Comment by sirbrillig** [comment]
I'm happy to let this be closed for the time being. I've never been able to reproduce it either, so presumably it's an edge case. We can reopen it if we find a reproduceable case.
