### ISSUE TITLE
Externalize and clean the getSuggestionsVendor() function

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47101]
As discussed in https://github.com/Automattic/wp-calypso/pull/46911#discussion_r515004672, the `getSuggestionsVendor()` should be cleaned and externalized, so that it can be accessed more cleanly without a major dependency within Calypso, and therefore imported by packages (and not only inside the calypso `client/` folder).

If we did that, we would probably want to refactor the current use of config to have something more context-driven

Proposed steps:
- [x] Externalize the [`getSuggestionsVendor()`](https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/suggestions/index.js) function, so that it can be used by other packages in the repository
- [x] Remove the `'domains/premium-domain-purchases'` feature flag check from inside the `getSuggestionsVendor()` function. (Update: This is now `options.isPremium` in https://github.com/Automattic/wp-calypso/pull/50756)
- [x] ~Update all current usages of `getSuggestionsVendor()`~ (Update: `getSuggestionsVendor()` on calypso end remains as it is, we just need to fix our end. Track here: https://github.com/Automattic/wp-calypso/issues/47105)

**Comment by yansern** [comment]
I think the question is how to externalize getSuggestionsVendor() when it is dependent on Calypso config.
Looking inside https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/suggestions/index.js, the 3 values to tackle are:
- options?.isSignup
- options?.isDomainOnly
- config.isEnabled( 'domains/premium-domain-purchases' )

**Comment by ciampo** [comment]
Linking to p1604506205260100-slack-C0KDTA48Y where this was also discussed
