### ISSUE TITLE
Site Picker: Safari layout bugs

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#4710]
#### Steps to reproduce
Using Safari on OSX
1. Starting at URL: wordpress.com/stats/day/{site}
2. In the sidebar, click "<- Switch Site"
3. Click any site
4. Observe weird layout of selected site vs how the site appeared in the list before selecting

#### What I expected
I expected the site to be laid out similarly when selected compared to how it appears in the list (and how it works in other browsers)

#### What happened instead
I saw a compressed/squashed layout, and in some cases, a floating "fade out" image where it shouldn't be.

**Note that it is intermittent, and I can't find a single, consistent thing that causes it.** I saw it happening pretty consistently with Jetpack sites, but also with some WordPress.com sites (but not all). The vertical spacing issues was apparent with every Jetpack site I tested, although the mis-aligned right-fade image only appeared once (also on a Jetpack site).

#### Browser / OS version
Safari Version 9.1 (10601.5.17.4) on OSX 10.10.5

#### Screenshot / Video
A Jetpack site with the right-fade image misalignment issue and the vertical spacing issue:
![screen shot 2016-04-13 at 11 12 10 am](https://cloud.githubusercontent.com/assets/108942/14502919/f5560236-016a-11e6-951a-f373a6df2b01.png)

Jetpack site with vertical alignment/spacing issue:
![screen shot 2016-04-13 at 11 31 08 am](https://cloud.githubusercontent.com/assets/108942/14503003/5072d8ec-016b-11e6-8e61-a511f56d3ebe.png)

WordPress.com site with vertical alignment/spacing issue:
![screen shot 2016-04-13 at 11 23 06 am](https://cloud.githubusercontent.com/assets/108942/14502929/0247694e-016b-11e6-92de-35e5a434f128.png)

WordPress.com site appearing normally:
![screen shot 2016-04-13 at 11 23 18 am](https://cloud.githubusercontent.com/assets/108942/14502947/127b0898-016b-11e6-9de0-a3939daa98a8.png)

**Comment by beaulebens** [comment]
I think the first one (right-fade image) is maybe related to the length of the URL involved. In my case, I can see it consistently on 2 Jetpack sites which have particularly long URLs (combined long domain + sub-directory installs).

**Comment by lancewillett** [comment]
This should be fixed now, see #4712

**Comment by lancewillett** [comment]
#4691 could also have been related.
