### ISSUE TITLE
Plugins: Domain intermittently inserted into plugin search results

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#47108]
I've noticed this happening intermittently with plugin search results when clicking the Plugins link in the Calypso sidebar.

The expected result is to see a screen like this:

![image](https://user-images.githubusercontent.com/545779/98138221-7effa200-1e88-11eb-9493-dd6486d7302d.png)

What I'll see instead is something like this:

![image](https://user-images.githubusercontent.com/545779/98138302-93439f00-1e88-11eb-8112-5aee24294254.png)

It looks like the string `&tab=search&s=domainname` is being added to the search results.

`https://flintabbatey.wpcomstaging.com/wp-admin/plugin-install.php?calypsoify=1&tab=search&s=flintabbatey.wpcomstaging.com&type=term&modal-mode=true&plugin=flintabbatey.wpcomstaging.com`

### Steps to reproduce the behavior

1. Go to Simple site > Plugins
2. Switch Sites to an atomic site with Jetpack Beta Test enabled
3. This will load the plugins page on the atomic site but it will append a query string searching for a plugin base on the title of the site

### Screenshot / Video:
https://d.pr/i/HrjVCl

**Comment by Robertght** [comment]
I cannot replicate this anymore so I'm closing it, but feel free to open a new report if needed.
