### ISSUE TITLE
Gutenboarding site launch / nux launch modal: Plans step width and margins styling on wide desktop layout

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#47132]
(Possibly) related to already reported issues in #44691 and #44693

In the site launch flow in Gutenboarding, the width of the central area isn't contained to a 1440px max-width like in the Gutenboarding flow before a user has created a site. Additionally, the [edge to edge container mixin](https://github.com/automattic/wp-calypso/blob/ec22864c3c93fe77031cb1fd2b6815609712cf41/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/plan-step/styles.scss#L12) used in the plans grid details container within the nux launch modal, removes the left and right margins at larger screen widths, causing the detailed comparison features to line up at either side of the browser window.

## In the Gutenboarding flow (this part doesn't need fixing)

![image](https://user-images.githubusercontent.com/14988353/98186039-066d1400-1f62-11eb-8d52-2164ad516380.png)

## In the site launch flow in the editor (this is the part that could use some tweaking)

![image](https://user-images.githubusercontent.com/14988353/98186051-0a009b00-1f62-11eb-9d71-01d9b4a0bc87.png)

#### Steps to reproduce

1. Starting at URL: wordpress.com/new create a new site
2. When you land in the editor, click to launch the site and go to the plans step
3. Compare layout / styling in a large desktop window to the plans step in Gutenboarding

This issue is possibly to be prioritised as part of #43750?

@Automattic/luna is this step part of scope of the current work you're doing on the launch flow? I noticed this while testing https://github.com/Automattic/wp-calypso/pull/46588 and wasn't sure if it was already part of what's being looked at.

**Comment by ciampo** [comment]
Potentially same issue as #47146

**Comment by andrewserong** [comment]
Yep, looks like the same issue!

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/48112
