### ISSUE TITLE
Launch: plans details table has no padding

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47146]
#### Steps to reproduce

1. Create a site using wordpress.com/new
2. Press _Launch_ button in editor top bar
3. Advance to the _Select a plan_ step and scroll down having the viewport is least 1441px wide

#### What I expected
Left padding next to the plans details table

#### Browser / OS version
Chrome/ MacOS / 1680px viewport width

#### Screenshot / Video
<img width="1678" alt="Screenshot 2020-11-05 at 14 25 47" src="https://user-images.githubusercontent.com/14192054/98241121-2b1db780-1f73-11eb-869b-ba70b6c14903.png">

**Comment by ciampo** [comment]
Could be a duplicate of #47132 ?

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/48112
