### ISSUE TITLE
Checkout: sometimes tax form country field has a different height than postal code field

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#47158]
As reported by @stephanethomas  in https://github.com/Automattic/wp-calypso/pull/47080#issuecomment-722422555

![98255321-92d90000-1f7d-11eb-950a-9ead875cbedd](https://user-images.githubusercontent.com/2036909/98277263-281bca80-1f65-11eb-8092-7750cb4d4cc4.png)

**Comment by stephanethomas** [comment]
For the records, I was using Chrome on Windows 10.

**Comment by sirbrillig** [comment]
cc @fditrapani in case you have any insights

**Comment by fditrapani** [comment]
Thanks for sharing @sirbrillig. I can take a look at this when I get a chance.

**Comment by fditrapani** [comment]
![image](https://user-images.githubusercontent.com/6981253/98564665-a1bffb00-227a-11eb-947c-c68ec071706f.png)


hmm, looks like this is a broader issue than just for G Suite.
