### ISSUE TITLE
Launch: errors after redirect to checkout

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47150]
#### Steps to reproduce
1. Create a site via `/new`.
2. Click the Launch button in the editor top bar.
3. Complete the flow by selecting a paid plan. After launch, you'll get redirected to `/checkout`.

#### What I expected
A. No error should appear.
B. Once I remove all the items I should get redirected to `/plans`.

#### What happened instead
A. _Creating product failed_ error is displayed. Also mentioned in https://github.com/Automattic/wp-calypso/issues/47109
B. After removing the products from the cart, I'm stuck on a loading screen.

**Demo**: https://cloudup.com/csZG6CcC59Z (buggy experience starting from 50") 

***Note 1**: I get the expected behavior if I land on `/checkout` from `/new` after site creation.
***Note 2**: Purchasing the product(s) still works despite the _Creating product failed_ error.

**Comment by sirbrillig** [comment]
> B. After removing the products from the cart, I'm stuck on a loading screen.

Interestingly, we just added an "empty cart" view that's supposed to display if for some reason the redirect to the plans page fails (#45182) but it looks like that's not showing. There may be an issue with the [`doNotRedirect` variable](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/composite-checkout/composite-checkout.tsx#L442).
