### ISSUE TITLE
Focused Launch: typography differences between calypso and editor versions

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47162]
### This is how the "calypso" version of the focused launch flow looks like**

Reproduce by visiting https://wordpress.com/page/[SITE_ID]/home?flags=create/focused-launch-flow-calypso

![Markup 2020-11-05 at 19 04 15](https://user-images.githubusercontent.com/1083581/98279683-8c0cb600-1f9a-11eb-845c-0f9da51ae732.png)

### This is how the modal launched in the block editor looks like:

To reproduce:

* Make sure you have an active connection to your sandbox, and that your sandbox is clean and up to date
* In two separate terminal windows, from the root of the project, run:
  - `yarn start`
  - `cd apps/editing-toolkit && yarn dev --sync`
* Sandbox an unlaunched WordPress site created via `/start` by adding it to your host file
* Visit the URL `/page/[SITE_ID]/home?flags=create/focused-launch-flow` on your local machine

![Markup 2020-11-05 at 19 03 34](https://user-images.githubusercontent.com/1083581/98279725-9a5ad200-1f9a-11eb-8ba4-ef9f65feabb1.png)

Notice the differences in typography highlighted in the screenshots above

**Comment by yansern** [comment]
Also bullets on plans grid.
![image](https://user-images.githubusercontent.com/1287077/100983845-8d59e000-3552-11eb-9675-1f31f5c739e1.png)

**Comment by razvanpapadopol** [comment]
Let's leave this on hold until we decide to proceed with Calypso integration.

**Comment by youbrokesomething** [comment]
The focused launch is no longer active and has been replaced by other initiatives. I'm going to close this issue.
