### ISSUE TITLE
Nudge: font size and spacing discrepancies

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#47161]
![image](https://user-images.githubusercontent.com/437258/98279788-6b2b6d00-1f68-11eb-82da-61a3a4429df1.png)

The info type on the left side here is sized in 'rems' and the button is 12px. This leads to a slight imbalance. 

There's also some padding or vertical alignment issues with more padding below the button than above. 

Gutenberg's buttons also use font-weight 400 for buttons, whereas we're using 600. 

I think it's worth aligning all of those things with an eye toward the nav unification as our end product.

cc @sfougnier to confirm my thinking.

**Comment by sfougnier** [comment]
Makes sense! I'll make sure this gets tweaked in the new nav as well.
