### ISSUE TITLE
Nav Unification: "Add new site" is missing for single site users

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#47183]
While testing a user who is editor in a single site and doesn't have other sites I noticed that "Add new site" is missing

![](https://cln.sh/QvZAHI+) 

We should make sure that "Add new site" is also shown in Atomic singe site users!

**Comment by mreishus** [comment]
~~We got "My Profile" instead of "Users"~~ Test

**Comment by cpapazoglou** [comment]
👋 @davemart-in , are there any plans on adding the "Add new site" somewhere elsewhere than the sidebar navigation?

**Comment by davemart-in** [comment]
@cpapazoglou not currently. Let's continue to show this at the bottom of the left nav for single site users and in the site switching menu once you have more than one site.

Nice catch!

**Comment by cpapazoglou** [comment]
@sfougnier could you please weigh-in from a design perspective? 
https://developer.wordpress.org/resource/dashicons/#plus-alt seems the best matching dashicon.
Should we place the link above the Collapse menu?
Or try making it stick to the bottom of the sidebar?
![](https://cln.sh/TzP5un+)

**Comment by marekhrabe** [comment]
Let's make sure we send the user to the same destination from wp-admin as we do from Calypso. We currently have competing `/start` and `/new` routes for adding a site and it looks like we might also add a query params like `?ref=calypso-selector`. All that needs to be accounted for in wp-admin too

**Comment by sfougnier** [comment]
> https://developer.wordpress.org/resource/dashicons/#plus-alt seems the best matching dashicon.

I agree with this icon choice to keep consistency with the other dash icons.

In terms of placement and styling, if we could keep it styled the same as "Collapse menu" and grouped a little closer

<img width="1351" alt="desktop - calypso" src="https://user-images.githubusercontent.com/67021691/99739150-1fb1ac80-2a9a-11eb-9708-2f26259798c5.png">

**Comment by cpapazoglou** [comment]
> > https://developer.wordpress.org/resource/dashicons/#plus-alt seems the best matching dashicon.
> 
> I agree with this icon choice to keep consistency with the other dash icons.
> 
> In terms of placement and styling, if we could keep it styled the same as "Collapse menu" and grouped a little closer to that menu item.
> 
> <img alt="desktop - calypso" width="1351" src="https://user-images.githubusercontent.com/67021691/99739150-1fb1ac80-2a9a-11eb-9708-2f26259798c5.png">

Thanks @sfougnier, that makes sense!

**Comment by cpapazoglou** [comment]
@sfougnier sadly, we cannot add the "Add new site" directly under the "Collapse menu" we can add it right above it (and below Tools). Would this be a problem?

**Comment by ghost** [comment]
> we cannot add the "Add new site" directly under the "Collapse menu" we can add it right above it (and below Tools). Would this be a problem?

Flipping the order is fine 👍

**Comment by marekhrabe** [comment]
I have implemented a basic version of this in https://github.com/Automattic/jetpack/pull/18146

There is a caveat — I've chosen to send everybody to https://wordpress.com/start for now.

However, in Calypso, the logic is slightly different. As of today, all `en` and `en-gb` users OR users part of the experiment `new_onboarding_existing_users_non_en_v4` will be sent to Gutenboarding https://wordpress.com/new, the rest to the standard signup.

The Calypso logic is pretty isolated and self-contained: https://github.com/Automattic/wp-calypso/blob/HEAD/client/state/selectors/get-onboarding-url.js

We have two options:
- leave nav unification to always link to `/start` (easy, already done in my PR)
- implement logic as close to calypso as possible (harder, it will involve rewriting the JS to PHP and keeping the two in sync forever)

Should we invest in the second option or are we fine with the simplified version? cc: @davemart-in @obenland 

In any case, https://github.com/Automattic/jetpack/pull/18146 is ready for a review and if we need to implement the additional URL logic, let's do it in a separate PR so this one isn't blocked.

**Comment by obenland** [comment]
@sfougnier How would you feel about adding a separator ahead of the link for some visual separation?

**Comment by obenland** [comment]
> it will involve rewriting the JS to PHP and keeping the two in sync forever

This decision is a painful one. We decided to duplicate logic for the site card but simplify it for the site picker. As much as I want to avoid duplication, I think for this one I'm leaning towards it.

I'd be interested in @simison's thoughts here as well.

**Comment by ghost** [comment]
> How would you feel about adding a separator ahead of the link for some visual separation?

Like this? Sure!

<img width="1440" alt="desktop - calypso" src="https://user-images.githubusercontent.com/67021691/102643193-e4ec7400-412c-11eb-9818-3c922457c7d9.png">

**Comment by simison** [comment]
Hi! Can you check with Luna and Explat folks if this would intervene with any of the ongoing ab tests?

I don't think any of the logic in JS is useful written in PHP. Jetpack cloud isn't wp-admin thing and the rest is ab test stuff? If needed, you could do intermediate route in Calypso that handles the rerouting.

**Comment by simison** [comment]
Could you still route the English user locale traffic to /new? That should be simple check.

**Comment by razvanpapadopol** [comment]
> Hi! Can you check with Luna and Explat folks if this would intervene with any of the ongoing ab tests?

In https://github.com/Automattic/wp-calypso/pull/48350 we've added individual `ref` query params to every button that a user can use in Calypso to create a new site. So if you just use a different `ref` value when skipping the A/B test and directly linking to `/start`, we should be fine.

**Comment by cpapazoglou** [comment]
There is https://github.com/Automattic/jetpack/pull/18146 deployed that adds the menu. We just need to:
1) Make sure that we add the `ref=calypso-sidebar` parameter
2) Style it like the "Collapse Menu"

@razvanpapadopol since now users will be landing to `/start` from wp-admin, does it make sense creating one more `ref` or should we just use `calypso-sidebar` ?

**Comment by obenland** [comment]
Fixed in Automattic/jetpack#18146
