### ISSUE TITLE
Focused Launch: refactor newly added blue colours into calypso color palette

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47181]
Related (possible duplicate) issue: https://github.com/Automattic/wp-calypso/issues/49866

While working on Focused Launch flow, we introduced a few new shades of blue

<img width="477" alt="Screenshot 2020-11-06 at 10 55 15" src="https://user-images.githubusercontent.com/1083581/98352639-92dd0c80-201e-11eb-9987-dcc61ab4a2c5.png">

At the moment, [we've been hardcoding these new colors directly in the domain picker](https://github.com/Automattic/wp-calypso/pull/47152/files#diff-f3729f16de3b5c7f75484038ca19e51dc1b702223aaa937c7b68df6298c2e66b). But we will need those same colors in other parts of the Focused Launch flow (e.g the plans step) — and potentially in other parts of the calypso UI too.

We should look into:
- [ ] extracting all the shades of blue that are needed by the Focused Launch design
- [ ] potentially add those new shades to `@automattic/calypso-color-schemes`
- [ ] refactor the code, switching from hardcoded values to the newly created shared variables
- [ ] using the same shades of blue in new onboarding, step by step launch, and focused launch

cc @ollierozdarz — :
- do you know if we're alraedy using similar shades of blue in calypso? Or otherwise,
- are those newly introduced shades of blue going to be used across calypso, or only in the focused launch?

**Comment by ollierozdarz** [comment]
Hey @ciampo, thanks for checking! I don't think we're using these blue's already and can't imagine they'll be used in Calypso, however, they could be used in some future versions of onboarding or 'create' related screens (I hope!).

**Comment by ciampo** [comment]
Thank you @ollierozdarz !

@razvanpapadopol , where should we store these color variables? Not sure if `@automattic/calypso-color-schemes` is a good fit, since they will be shared only by other launch/onboarding flows.

Maybe in `@automattic/onboarding`?

**Comment by razvanpapadopol** [comment]
> Maybe in @automattic/onboarding?

Yes, it makes sense to add these onboarding specific colors to [onboarding variables](https://github.com/Automattic/wp-calypso/blob/master/packages/onboarding/styles/variables.scss). 

The ideal scenario would be to have a generic component exported from `@automattic/onboarding` that will use this color. See the **Follow up** section of https://github.com/Automattic/wp-calypso/issues/47147

**Comment by razvanpapadopol** [comment]
Maybe this would help: p9Jlb4-28F-p2

**Comment by razvanpapadopol** [comment]
New issue regarding the alignment of blue colors across Onboarding UI: https://github.com/Automattic/wp-calypso/issues/49866

**Comment by ciampo** [comment]
Superseded by #49866
