### ISSUE TITLE
Editor: Media: gallery edit media modal is missing the "media library" label on mobile

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#4719]
Steps to reproduce:

1. Start a new post at https://wordpress.com/post
1. Select some images for a gallery and tap Continue

<strong>Result:</strong> the "back" arrow near the top of the screen doesn't have a label (tested on Safari iOS 9.3 on iPhone 6S)

<img alt="screen shot 2016-04-11 at mon apr 11 11 11 56 am" src="https://cloud.githubusercontent.com/assets/1119271/14506900/19110acc-018e-11e6-8029-46b53223d2f8.png" width="400" />

In comparison, looks good on a larger screen:

![screen shot 2016-04-13 at wed apr 13 3 37 47 pm](https://cloud.githubusercontent.com/assets/1119271/14506910/236f81ce-018e-11e6-8267-f73b697d1448.png)

**Comment by lancewillett** [comment]
Visual record of this with Chrome on Android (Nexus 5, Android verson 6.0.1)

<img src="https://cloud.githubusercontent.com/assets/66797/14507632/5fe385bc-0178-11e6-9ec9-205c945ae2e9.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/14507633/5fe3b5fa-0178-11e6-9b8f-c95ac65d7c84.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/14507634/5fe4401a-0178-11e6-83db-00040c42ed76.png" width="480" />

**Comment by lancewillett** [comment]
Closing since it's low priority, works fine with just the arrow, and we have bigger issues to fix.
