### ISSUE TITLE
Build: yarn install failed with an old version of yarn

### ISSUE THREAD

**Issue by nb** [Automattic/wp-calypso#47218]
#### Steps to reproduce

1. Acquire an old version of yarn, in my case 0.22
2. Run `yarn`

#### What I expected

To update my dependencies.

#### What happened instead

I got an error `Error: https://registry.yarnpkg.com/@automattic%2fbabel-plugin-transform-wpcalypso-async: Not found`

After I updated `yarn`, it worked perfectly.

It wasn't a big deal, though it got me stumbled for a minute there If we can have a way to compare and enforce the `yarn` version in the `engines` field that would be awesome (very cursory Google search didn't show much).

**Comment by scinos** [comment]
Since `yarn@1.0` (released ~2y ago) it will automatically pick the version declared in `.yarnrc`, which points to the latest version used in Calypso, `1.22.10`

Since [`yarn@1.15.0`](https://github.com/yarnpkg/yarn/issues/7013) it also checks the `engines` field, that we specify as `yarn: ^1.22.10`
