### ISSUE TITLE
Premium patterns: wrap or categorise premium patterns so that they're treated as a single unit

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#47226]
Part of #47224 

When a user goes to add a premium pattern from the inserter, we'd like to treat the inserted pattern as a single un-editable block that displays what the pattern would look like if the user upgraded, but the user can only upgrade or delete the pattern.

Proposed ideas for implementation include adding a new block called `premium-pattern` that is responsible for displaying the pattern in the editor, and the upgrade banner. This wrapper block should be visible in the editor, but not on the front end of the site, and it should be easy for the user to delete it. If the user upgrades, then this block should transparently be replaced by the "real" blocks of the premium pattern.

Design exploration in p9Jlb4-1S1-p2

## Goals

* A premium pattern should, when added to a post, be treated (effectively) as a single block, with a preview of what the pattern would look like.
* On the front end of the site, the pattern should not be visible.
* The pattern should not be editable (aside from deleting it or upgrading).
* It should be easy to select it (it shouldn't be a hard to select block like the "group" block)
* It shouldn't add additional noise to the List View of blocks (from the button in the top toolbar in the editor). Ideally in the list view, it should simply say "Premium Pattern" or something like that.
* When upgrading, the "real" pattern should appear in its place.

**Comment by ramonjd** [comment]
@deBhal was hoping you could starting 👀 into this one. I think @andrewserong has been looking at how to insert badges: https://github.com/Automattic/wp-calypso/issues/47225

From the premium patters issue (https://github.com/Automattic/view-design/issues/113) it looks like there are some premium patterns already built already (sitting in a test site - dotcompatterns.wordpress.com) 

I don't think it matters so much since it might be worth spending a day or two on creating a very basic premium pattern block as @andrewserong [mentions in the issue description](https://github.com/Automattic/wp-calypso/issues/47226#issue-738650707) 

We might like to register a test premium pattern using the [audio block](https://dotcompatterns.wordpress.com/2020/06/16/audio-player/) as @ianstewart  mentions over on the spec: pbAok1-1ye-p2#comment-3077

Let's discuss here if you have any Qs!

Cheers 🍺

**Comment by apeatling** [comment]
Please don't do this, we want all patterns to be editable by the user before upgrading. Not allowing editing will be extremely detrimental to conversion rates. We should allow users to edit everything, as well as publish, but notify them that they need to upgrade for the premium content to display to their visitors.

**Comment by ramonjd** [comment]
> Please don't do this, we want all patterns to be editable by the user before upgrading. 

Just to be clear, the only concern is with editability?

I assume it wouldn’t be difficult to allow editing. We’re there any reasons behind the edit lock @andrewserong ?

Logged we’d see the block + upgrade message, and logged out, the block wouldn’t appear at all?

**Comment by ianstewart** [comment]
Some of the current design work happening around Premium Patterns and the whole flow are moving away from leaning on the banners appearing in the canvas. So we might not need the wrapping either.

Here's a user experience that might be worth considering …

1. User sees a Pattern with a premium label in the inserter.
2. They insert the Pattern into the canvas and are alerted that they have inserted a Pattern that _contains_ or users a premium block requiring an upgrade. Some premium patterns will be groups of blocks with premium settings that contain free blocks. Like a cover block (free) with a video background (premium) and paragraph blocks inside of it. Others will be free blocks that contain premium blocks. Like a cover block with a colour background (free) and a whatsapp button (premium) inside of it.
3. The user will be able to experiment with their pattern by editing, perhaps by changing colours or text to see if the pattern fits. Perhaps even deleting a premium block and re-purposing the pattern.
4. If the user has not yet upgraded before publishing they'll be alerted before publishing. (This UI and flow might also be re-purpose-able when one has not yet completed setup of some complex blocks before publishing. Like a payments block.)
5. If a user, perhaps in a "building mode" chooses to continue publishing premium blocks will not be visible on their site until an upgrade takes place. This is the status quo today. This could be improved by showing the admin user in a "building mode" the block still but alerting them that they'll still need to upgrade to provide the block to visitors.

I believe items 2 through 5 will be valuable not only for premium patterns but for starter designs that contain premium blocks as well.

**Comment by ianstewart** [comment]
cc @rickybanister @JanaMW27 on the above notes ^^

**Comment by ramonjd** [comment]
> Some of the current design work happening around Premium Patterns and the whole flow are moving away from leaning on the banners appearing in the canvas. So we might not need the wrapping either.

This is good to know, thanks.

I assume however, we'll still need some type of hook at the container level, through which we can hide the premium pattern on the user's site until they've upgraded. If so, the wrapper would be useful.

**Comment by andrewserong** [comment]
Thanks for the feedback @apeatling and @ianstewart, that makes a lot of sense, and I like the idea of users being able to edit their pattern before upgrading.

In this case, do we still need a way of wrapping patterns in the editor after insertion? It'd be great if we could abandon this idea so that we can continue with the "pattern" of how patterns are treated in Gutenberg, which is that once they're in the editor, they're no longer a thing.

That way we can side-step the whole issue of users editing content within a premium pattern, and getting confused about the boundary of the pattern in the editor (e.g. if I remove a few blocks and forget about the pattern, then later on go back to the post, add in some paragraphs and they're within the "pattern" group, it won't show on the front end and I might be confused as to why).

I seem to remember reading in one of the design comments on premium patterns (that I unfortunately can't find now!) that mentioned that we might want a premium pattern to be considered premium not _just_ because of the premium blocks within it, but for some other purpose (which was part of the reasoning behind this issue). Is that still the case at all? My preference would be to avoid that, as it (to me) makes a lot more sense for premium patterns to be explicitly tied to features in premium blocks.

**Comment by ramonjd** [comment]
> In this case, do we still need a way of wrapping patterns in the editor after insertion? It'd be great if we could abandon this idea so that we can continue with the "pattern" of how patterns are treated in Gutenberg, which is that once they're in the editor, they're no longer a thing.

Let's do this. It'll allow us to get something out faster. We can always revisit it later.

I've updated the spec pbAok1-1ye-p2 to reflect the idea that we let premium blocks be premium blocks and not worry about hiding/showing at the pattern-level.

> I seem to remember reading in one of the design comments on premium patterns (that I unfortunately can't find now!) that mentioned that we might want a premium pattern to be considered premium not just because of the premium blocks within it

That sounds like a debate that will slow us down. Let's let it play out organically and take @apeatling's and @ianstewart's advice. cc @simison

**Comment by deBhal** [comment]
Ok, based on this discussion, I'm going to go ahead and close this for now, and we can always circle back later.

> perhaps in a "building mode"

So the "building mode" would just be about hiding the premium blocks, right? Or more accurately _not_ hiding them?

Maybe a better approach to the underlying goal of this issue would be a feature in the preview rather than the editor? i.e. Add a toggle to the preview to let the user switch between what visitors to their site _will_ see vs what they _could_ see?
