### ISSUE TITLE
WP.com editing toolkit: search box disappears when searching certain letters 

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#47237]
In the block editor, every time you search for a block if the first letter you type is "a" or "s" or "e" then the search window just disappears.
On atomic sites, the issue stops happening when the editing toolkit plugin is deactivated. 

#### Steps to reproduce

1. open a post / page in the editor
2. Click + to search for a block
3. Start typing "a" or "s" (if the site is atomic)  or,  "a"or "e" (if the site is simple)

#### What I expected
- Either blocks will appear in the search results or it shows as "no results found"

#### What happened instead
- The search box just disappears 

#### Browser / OS version
Chrome Version 86.0.4240.111 (Official Build) (x86_64)

#### Screenshot / Video

![Screen Capture on 2020-11-09 at 10-05-37](https://user-images.githubusercontent.com/39188945/98565127-3f1b2f00-227b-11eb-867d-7179d0d54c05.gif)

#### Context / Source
Reported here: #25352435-hc

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this on a Simple site

![search](https://user-images.githubusercontent.com/3629020/98575531-2f085b80-231e-11eb-8c51-592a587a6ccf.gif)

Are there any errors in the browser when this happens for you @sourourn?

**Comment by sourourn** [comment]
@glendaviesnz This is what I see in the console:

On simple site: 
<img width="1437" alt="Screenshot simple site" src="https://user-images.githubusercontent.com/39188945/98578510-7396e700-228b-11eb-9c3a-d3c0c4049207.png">

On atomic site:
<img width="1440" alt="screenshot atomic" src="https://user-images.githubusercontent.com/39188945/98578567-84dff380-228b-11eb-8fc2-3b8ff7196c19.png">

**Comment by glendaviesnz** [comment]
Thanks for the extra detail ... it looks like this is already being looked at under https://github.com/Automattic/wp-calypso/issues/47033, so I am going to close this in favour of that one.
