### ISSUE TITLE
Nav unification: make new colors available to customers ahead of nav unification launch

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#47266]
We will allow customers to get familiar with the new colours ahead of the nav unification launch by introducing a new non-default Classic Dark color scheme using the nav unification colors (Decision: stakeholder decision in Ajax backlog grooming meeting on Thu Nov 5th.).

**Comment by rickybanister** [comment]
This sounds like a fine approach. I'd also point out that if we unify color schemes the default colors of buttons in the editor will follow suit for the first time and no longer be blue, so all customers will experience some amount of change no matter what. That's 100% fine, just worth noting there is no path forward that will result in no change.
