### ISSUE TITLE
Editor: Media: media files with with non-standard characters cannot be uploaded

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#4726]
When a media file contains a non-standard character the message "file could not be uploaded because the file type is not supported" message is displayed.  However, the same file can be uploaded in both the WP Admin editor and Media Library without issue.

I have found the following characters (which Mac OS will let you use) when present in the filename, will not upload in the editor, but there may be others:

- #
- ?

For example, a filename like `myawesomeimage-1.jpg` can be uploaded but `myawesomeimage#1.jpg` cannot.

#### Steps to reproduce
1. Starting at URL: wordpress.com/post or /page
2. Click Add Media button in editor and try to upload file with # or ? in the filename
3. See error message
4. Open new post or page in WP Admin and try to add the same file
5. Success

**Comment by lancewillett** [comment]
Thanks for the report. Could you a bit more detail please? Browser and OS version, which URL you tested with, screenshot or video for visual record and context.

**Comment by jerrysarcastic** [comment]
Tested on Chrome 49.0.2623.112, Firefox 45.0.1, Safari 9.1 (Mac 10.10.5)  and initially reported by a windows user on Chrome 49.  Asking the user for OS version info.

Screencast: https://cloudup.com/csDu3-Y_Cfg

**Comment by jerrysarcastic** [comment]
Tested in the new editor (mysite.com/post) and wpadmin editor (mysite.wordpress.com/wp-admin/post-new.php)

**Comment by lancewillett** [comment]
Thanks for the extra info, very helpful. :thought_balloon:

**Comment by ehti** [comment]
Came across the same issue quite a few times in the last few weeks. Was looking to file a bug but saw an already open issue here - user in 358011-chat wasn't being able to upload a file, asked them to upload a zip file which kept the file name intact.

Turns out the image isn't being uploaded via Calypso because of a '#' in the file name.

**Comment by danieldanilov** [comment]
Came across the same issue in 2647763-t and the issue seems to be resolved when '#' is removed from the file name.

**Comment by dougaitken** [comment]
Same issue, 2649631-t. I tested on my test blog by having # in the file name, and reproduced as per @jerrysarcastic's reply, same results - Calypso failed but wp-admin worked no issues.

**Comment by KokkieH** [comment]
Two more in 2628475-t and 2644790-t

**Comment by BandonRandon** [comment]
Reopening this issue. Either a regression happened or the original patch did not fix all cases. 

A Screencast of the issue can be seen here:

https://cloudup.com/cOUuw4aKzko

(Chromium 49 Linux Mint 17.2)

Was also able to replicate on Firefox 46 on Linux. 

In 374890-chat user was able to replicate on Chrome 50 for OSX @andrewspittle was also able to replicate on OSX

**Comment by aduth** [comment]
Regression reintroduced in 64f65e767689a0f7a37e2436758cf46b64a507d5, cc @robobot3000 @gwwar

**Comment by robobot3000** [comment]
Sorry about that @aduth. I must have resolved one of the conflicts incorrectly. I am happy to fix it if needed. 

It seems that the lines 140-141 need to be removed from client/lib/media/actions.js for a quick fix. I can handle getting the extension for the editor uploads in add/image-editor-crop branch.

**Comment by gwwar** [comment]
Whoops missed that one. Thanks for the ping @aduth
