### ISSUE TITLE
Focused Launch: tooltip for disabled steps doesn't show

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47279]
#### Steps to reproduce

1. Visit `/page/UNLAUNCHED_SITE_ID/home?flags=create/focused-launch-flow-calypso`
2. If necessary, force the `hasPaidDomain` variable to `true` in order to force the domain step to render in the "disabled" group 
3. Try to trigger the tooltip by hovering or focusing on the "info" icon in the domain step

#### What I expected

A tooltip should show

#### What happened instead

The tooltip doesn't show and the "info" icon can't be focused

**Comment by alshakero** [comment]
I can't reproduce this now. Do you mean on mobile?

**Comment by ciampo** [comment]
I'm not able to reproduce when using a pointer device anymore too.

But yes, for sure the tooltip doesn't work on devices that rely on touchscreen interactions
