### ISSUE TITLE
Admin Colors Unification sync process - hook into WoA site creation to set initial admin color scheme based on WPCom setting

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#47271]
See paYJgx-17t-p2#comment-1391

We need to hook into the process that creates a new WoA site and ensure that the user option `admin_color` is set to match the user preference currently stored on WPCom for the current users' account.

We can probably do this by following this example D50029-code and using the existing code for syncing the color schemes (see D52376-code) to update the color setting on the WoA site as it's being created. This could be sync or via spawning an async job.

**One thing to note**: this P9o2xV-18x-p2 which states:

> Don’t use for something like user specific admin color scheme. We would have to store the color data for each user on the site, and it isn’t something that would break the main functionality we provide.

**Comment by getdave** [comment]
## Linked PR/Diff

Being handled in D53945-code

**Comment by getdave** [comment]
@mmtr Would you consider this Issue as `Done` now and open fresh ones for any further revisions / enhancements?

**Comment by mmtr** [comment]
Yup, I just verified with a new site that I created that this is no longer needed since we're pulling the WP.com color scheme as of 590-gh-Automattic/wpcomsh.
