### ISSUE TITLE
Gutenberg - Missing Preview Button

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#47282]
### Description

A Desktop app user has reported that they consistently cannot see the Preview button when using Gutenberg in the Desktop app (see screenshot). So far HEs have been unable to reproduce this, but details for the site and user are located in Zendesk ticket 3451796-zen. The user's site is using Gutenberg v9.2.2.

<p align="center">
<img src="https://user-images.githubusercontent.com/8979548/98697821-53c2fa00-2343-11eb-95bc-7248b981ddaa.png">
</p>

### Context

There have been some code changes recently (both backend and frontend) that manage the visibility of the Preview button that might be related.

PR #40388
P2-pc9Uba-6j-p2

**Comment by belcherj** [comment]
Closing as this is obsolete after the re-architecture this should not be an issue.
