### ISSUE TITLE
Subscriptions: Sites created with the JN tool cannot be followed using the WordPress.com Reader.

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#47289]
Steps to reproduce:

1. (If you don't already have access) set up the JN tool.
1. Create a new WordPress site and add some posts.
1. Copy the URL of the new site.
1. Go to WordPress.com > Reader > Manage.
1. Enter the URL from step 3.
1. Click "Follow".
1. Observe that the main domain is followed but not the subdomain.

**Result:** you cannot follow a JN site because the Reader automatically adds the root domain instead. ([31s](https://cloudup.com/c922v-mhU4u))

<img src="https://user-images.githubusercontent.com/1119271/98718111-3a25b080-234b-11eb-8eb1-ae7f7b742f1f.png" width="49%" alt="incorrect-site-followed">  <img src="https://user-images.githubusercontent.com/1119271/98718115-3abe4700-234b-11eb-8c3e-7b4046a06210.png" width="49%" alt="manage-followed-sites">

<sup>Tested using Firefox 82.0.3 on macOS 10.15.6 attempting to follow awkward-grasshopper.jurassic.ninja running self-hosted WordPress 5.5.3 standalone site with no active plugins.</sup>

**Aside:** I use this tool quite a bit for testing WordPress in our mobile apps, which is currently my core work. 🙂  I can work around the issue, but it would be extremely nice to be able to test new features as part of beta testing and then also be able to review them in the Reader.

**Comment by designsimply** [comment]
I'm trying to think of additional scenarios to test. I double checked that the same problem happens for Jetpack-connected sites on jurassic.ninja and it does.

* Test 1: [25s](https://cloudup.com/cwoNZ5zTn_1)
* Test 2: [10s](https://cloudup.com/coDTWD9Gxby)

<sup>Tested using Firefox 82.0.3 on macOS 10.15.6 on jurassic.ninja subdomain standalone WordPress 5.5.3 sites running the Jetpack plugin, aesthetic-porpoise.jurassic.ninja is currently running Jetpack 9.0.2.</sup>

**Comment by guarani** [comment]
I also ran into this with Jurassic Ninja sites, but hadn't noticed that the Reader was following the root domain instead, so thanks for pointing that out @designsimply!

I gave this a test with a Pressable test site which also uses subdomains (i.e. **pschrottky6**.mystagingwebsite.com) and strangely this issue didn't come up:

| <img width="956" alt="Screenshot of Pressable test site being followed by the Reader" src="https://user-images.githubusercontent.com/1898325/100095886-f39b8000-2e39-11eb-94ed-996c6c359ce5.png"> |
| - |

So it's not clear to me what could be causing Jurassic Ninja sites not to be followed correctly while Pressable sites are, given that they both use subdomains.

**Comment by designsimply** [comment]
Thanks for testing a different domain @guarani! Quick question, in your subdomain site, was there a WordPress install at the root domain and ALSO on a subdomain, or… if not, what happened when you hit the root level domain?

**Comment by guarani** [comment]
> Quick question, in your subdomain site, was there a WordPress install at the root domain and ALSO on a subdomain, or… if not, what happened when you hit the root level domain?

How can I check this, @designsimply? Sorry, I'm not too familiar with this yet. My understanding is that when you create a Pressable site, it's going to be something of the form `xyz.mystagingwebsite.com`. The domain called `mystagingwebsite` is always used, and the subdomain (e.g. `xyz`) is customizable.

My best answer to your question above is that the WP install is at the subdomain, but I'm not confident so I'd like to ask you how to check.

**Comment by designsimply** [comment]
I think in order to test it what I'm thinking of you would need to have a custom domain applied, have WordPress installed at the root level, and also have WordPress installed at the subdomain or subdirectory level. If you don't have an easy way to check though, then don't worry about it for now and I'll find a different hosting setup to test my theory out on at some point. 👍 Thanks for the reply!

**Comment by guarani** [comment]
I didn't follow, it might need some know-how I don't have, sorry! I did a quick check again though to see if anything's changed and the bug persists on sites created on Jurassic Ninja, and it's still not reproducible on sites created on Pressable.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
