### ISSUE TITLE
Mobile issues for Vesta design in editor

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47293]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/new
2. Select Vesta design: https://cloudup.com/cvrIpTeKMry
3. Complete the flow to create a new site.
4. Open the editor on mobile.

#### What I expected
- Design to be displayed as in preview
<img width="1277" alt="Screenshot 2020-11-10 at 22 50 38" src="https://user-images.githubusercontent.com/14192054/98731953-2a3bba00-23a7-11eb-82b4-23f2fb4fe2ec.png">

#### What happened instead
- Content seems to be cropped 
<img width="305" alt="Screenshot 2020-11-06 at 17 56 47" src="https://user-images.githubusercontent.com/14192054/98731971-3162c800-23a7-11eb-9c3a-1e8c45c05048.png">

#### OS / Browser / Device
- Android / Google Chrome / Samsung Galaxy s10
- MacOS / Google Chrome ( window < 560px wide)

**Comment by jeyip** [comment]
I'm still having a bit of trouble reproducing the issue. I followed these steps:

1. Starting at URL: https://wordpress.com/new
2. Select Vesta design: https://cloudup.com/cvrIpTeKMry
3. Complete the flow to create a new site.
4. Open the editor on mobile.

I checked mobile viewport widths in the chrome browser. I also opened the site on my iphone 8. Both appear to behave as expected. 🤔

**Comment by razvanpapadopol** [comment]
I was able to reproduce now in wp-admin of the site you've created so we know this is not user-related. Everything looks fine until the viewport is less than 560px wide. 

I've also updated the issue with OS / Browser / Device section.

**Comment by yansern** [comment]
Most likely something to do with `[data-align=full]`.

![image](https://user-images.githubusercontent.com/1287077/98791912-63f3db80-240e-11eb-8ef8-b1fc7e609443.png)

**Comment by alshakero** [comment]
I investigated this and it seems that some themes use the experimental [Layout Grid](https://github.com/Automattic/block-experiments/tree/master/blocks/layout-grid). Layout grid [accepts a prop]((https://github.com/Automattic/block-experiments/blob/12a0c1ef66ec3dd90e7c28e69e7587b20d2d3cec/blocks/layout-grid/src/grid/edit.js#L92)) called "displayType: "Desktop" | "Mobile" | Tablet". It uses this prop to determine the layout.

This means that the screen width isn't taken into account, rather, the display type you select when you click "Preview" button in the top right corner of the editor in Desktop mode.

Since we're hiding the display type picker in mobile anyways, I think we should change the "displayType" value to "Mobile" in mobile devices. Currently, display type is fetched from the `core/edit-post` store and isn't tied in any way to the screen size.

**Comment by roo2** [comment]
This issue in the Layout Grid seems to be related. https://github.com/Automattic/block-experiments/issues/152

It looks like the setting that effects it is the `__experimentalGetPreviewDeviceType` used in [edit.js](https://github.com/Automattic/block-experiments/blob/master/blocks/layout-grid/src/grid/edit.js#L474) this value does always seem to be set to desktop. And in fact edit.js is not used in the site preview, so there is no point in using this variable in edit.js.

I did notice that even when I manualy changed __experimentalGetPreviewDeviceType to Mobile, the page content of this vesta template still overflowed.

<img width="380" alt="Screen Shot 2020-12-10 at 4 35 02 PM" src="https://user-images.githubusercontent.com/22446385/101730399-ac81e000-3b05-11eb-91f9-e3f0f001ead2.png">

So there seem to be two issues at play here.

**Comment by roo2** [comment]
Aside from the columns not rendering in mobile mode, the reason that the content is pushed off the screen is actually related to the `has-background` class. the `has-background` triggers some style rules to take effect which push the content out of the normal padding an right to the edge of the screen on desktop. However, on mobile the padding is smaller, so the content is pushed right out of the screen.

I'll raise this issue upstream in gutenberg.

But for the Vesta design, why does it need a background color? the background color is set to white, which is the default background color anyway...

I've made a diff to remove background color from Vesta's homepage template which fixes the theme's editor experience on Mobile. D54150-code

**Comment by roo2** [comment]
I created a PR to fix this in a8c themes https://github.com/Automattic/themes/pull/2909

**Comment by roo2** [comment]
fixed in core here https://github.com/WordPress/gutenberg/commit/50cdfbeae59cf0fe91faa2183877b3b7fc60dd3e#diff-1a9996754d0946dc5f83e38ec6b5e6bc139ec4d16690ec8c9d4b5402175bc17b
