### ISSUE TITLE
Premium Content Block: Not able to create new payment plan

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#47298]
When the user tries to create a new payment plan, from Tools > Earn > Add premium content subscriptions, they get the error _"Cannot read property 'id' of undefined"_. I was able to replicate on their account, but can't find any other detail about the error.

User report - ticket: 3479393-zd-woothemes

**Comment by apeatling** [comment]
Is this in the block, or in Calypso?

**Comment by carinapilar** [comment]
This was on Calypso, on Tools > Earn > Add premium content subscriptions. It seems the user managed to create a plan, I would guess it was through the block.

**Comment by apeatling** [comment]
I haven't been able to reproduce this in Calypso or in the block.

**Comment by apeatling** [comment]
Reproduced at it seems to be caused by users getting to this screen before connecting Stripe. Please check to see if the user has connected.

**Comment by apeatling** [comment]
As a follow up we will check the flows to see how users might be getting to the payment plan creation screen without connecting Stripe first.

**Comment by carinapilar** [comment]
> Reproduced at it seems to be caused by users getting to this screen before connecting Stripe. Please check to see if the user has connected.

Hm, that's odd, because the user's account shows the option to disconnect Stripe, so I would guess it's been always connected. I asked them to disconnect and connect again.
