### ISSUE TITLE
Nav-Unification: Ported wp-admin schemes issues on site selector badges

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#47295]
* Choose a color scheme ported from Nav Unification, like "blue"
* Visit calypso with nav-unification flag turned on.
* Go to site selector and find a private site

![2020-11-10_15-34](https://user-images.githubusercontent.com/937354/98736400-5edd5080-236a-11eb-9ade-95ead9614368.png)

Expected: Text to be readable

### Reference Issues

* Main Issue #45435
  * Color Schemes Issue + Direction  #45675
    * Port over WP Admin color schemes as new options in Calypso /me section. #47036

**Comment by mreishus** [comment]
Doesn't happen with nav unification off.  Caused by this rule:
https://github.com/Automattic/wp-calypso/blob/96c9a7bc4a0d513096495a5e90f23bae3456a9c4/client/my-sites/sidebar-unified/style.scss#L291-L293

**Comment by mreishus** [comment]
Without Rule Added:

```
background: var(--color-sidebar-menu-hover-background);
color: var(--color-sidebar-menu-hover-text);    
```
    
With rule mentioned above:

```
background: var( --color-sidebar-text ); 
color: var(--color-sidebar-menu-hover-text);   
```
So it's only legible if the hover text is a different color than the sidebar text; I don't think that's a good way to go, since some themes only change the background on hover, not the text.

**Comment by mreishus** [comment]
On the default theme, I see this before and after adding the rule?

Before rule added
![2020-11-10_17-03](https://user-images.githubusercontent.com/937354/98744189-e3ce6700-2376-11eb-97ad-59a0e783c8d1.png)

After rule added 
![2020-11-10_17-04](https://user-images.githubusercontent.com/937354/98744200-e9c44800-2376-11eb-8981-274851b114b3.png)

I guess the intention was to change the BG to white?  I'm not sure how to do that currently while maintaining theme compatibility.  My current instinct is to remove the rule, the before pic looks fine to me.  Any suggestions here?

**Comment by mreishus** [comment]
@cpapazoglou Any opinions or ideas?

**Comment by cpapazoglou** [comment]
It is actually a grey background to match the wp-admin 
![](https://cln.sh/iI0dm0+).
Since this element is new to wp-admin, let's do it the other way round. Remove the rule from calypso, and make sure we adjust wp-admin. Also, as it seems now, we need to consider the color-schemes for all new elements added to wp-admin 😧!
eg site-switcher, site card
