### ISSUE TITLE
Signup: Update the masterbar to change My Site --> My Sites

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#473]
After creating second site, the masterbar in /me/next still reads "My Site" instead of "My Sites"
https://cloudup.com/c49ibiD8d9Y

After clicking skip it changes to "My Sites"

**Comment by artpi** [comment]
Will work on it, since I reported it initially

**Comment by artpi** [comment]
There definitely is an issue here:
https://cloudup.com/i7stWYLuw3w

The bigger problem seems to be, that Layout actually is never re-rendered when new data is in the store. So the first props stay
