### ISSUE TITLE
Jetpack connect: Use html mockup for the install examples

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#4731]
From @beaulebens jetpack connect tests:

The interstitial we use to tell the user how to install Jetpack is showing an example of what they will see in their wp-admin. Since it’s an image, we’re not going to be able to translate the labels in that visual. It might be good to actually make it a “mock” HTML layout, with real text.

**Comment by rickybanister** [comment]
This got closed by #5832
