### ISSUE TITLE
Payments: Payment Methods page display is sometimes broken

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#47335]
#### Steps to reproduce

There may be more than one way to reproduce this, but I can do it reliably like so:

1. Start at https://wordpress.com/plans
2. Navigate to the Payment Methods page (Me => Manage Purchases => Payments Methods)
3. It looks like the screenshot below:

![broken](https://user-images.githubusercontent.com/235183/98848232-6579cf80-241f-11eb-9ea3-00dd34667d5e.png)

#### What I expected

I expected it to look like it normally does:

![good](https://user-images.githubusercontent.com/235183/98848238-67dc2980-241f-11eb-8eef-0960b824eab2.png)

**Comment by fditrapani** [comment]
Thanks for reporting this @DavidRothstein! That's weird how it only happens at the account level after visiting the plans page. I can take a look to see if I can figure out what's going on.
