### ISSUE TITLE
Comments: Cannot access comments section in Calypso when website field contains an invalid URL

### ISSUE THREAD

**Issue by nielslange** [Automattic/wp-calypso#47355]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/comments/all/lifestylecollective.org
2. See error

#### What I expected

I expect to see the comments section.

#### What happened instead

I see a white screen instead and the following error message in the console:

```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at E (entry-main.88393777703f84a2aad5.min.js:2)
    at g.render (361.bfa4c402f05c8426c58b.min.js:1)
    at Di (123.308d351a3c24f63297a6.min.js:2)
    at Ui (123.308d351a3c24f63297a6.min.js:2)
    at va (123.308d351a3c24f63297a6.min.js:2)
    at pl (123.308d351a3c24f63297a6.min.js:2)
    at dl (123.308d351a3c24f63297a6.min.js:2)
    at rl (123.308d351a3c24f63297a6.min.js:2)
    at 123.308d351a3c24f63297a6.min.js:2
    at t.unstable_runWithPriority (123.308d351a3c24f63297a6.min.js:2)
```

#### Browser / OS version

macOS 10.15.7 | Chrome 86.0.4240.193

#### Screenshot / Video

<img width="1438" alt="Screenshot 2020-11-12 at 13 56 42" src="https://user-images.githubusercontent.com/3323310/98905974-e6ec6300-24ee-11eb-980b-2ff04b4392c5.png">

#### Context / Source

19712764-hc | 3483262-zen

**Comment by rinazrina** [comment]
Another report on #25604877-hc | follow-up #3485925-zen 

URL: https://wordpress.com/comments/all/post-gutenberg.com?page=3 

Comments are not loading on Page 3 and showing a white screen instead.

Comments are loading fine on other pages, and also loading fine on WP Admin > Comments

I'm seeing a similar error message as Niels's report above on the console.

**Comment by syds87** [comment]
Another similar report on #25612305-hc | follow-up #3486706-zen

URL: https://wordpress.com/comments/spam/thelevinelowdown.com

This happens when we click the Spam category. They load fine in other categories. 

WP-Admin > Comments is loading fine as well.

The console is reporting:

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/70008187/99091985-e1674980-25d0-11eb-878e-61ab985237ef.png">

**Comment by cathymcbride** [comment]
Adding this to the janitor prioritized backlog b/c of the severity, but since we haven't seen further reports in 20 days, I'm hoping it's fixed or was transient.

**Comment by Nic-Sevic** [comment]
I checked their spam section and it's now displaying as expected. I asked for confirmation from the user and awaiting reply.

**Update** user confirmed working for them

> Another similar report on #[25612305-hc](https://href.li/?25612305-hc) | follow-up #[3486706-zen](https://href.li/?3486706-zen)
> 
> URL: https://wordpress.com/comments/spam/thelevinelowdown.com
> 
> This happens when we click the Spam category. They load fine in other categories.
> 
> WP-Admin > Comments is loading fine as well.

**Comment by poojashetty18** [comment]
Another similar report on #3554034-zen

URL: https://wordpress.com/comments/all/blog.lostartpress.com

AT site and we are unable to view the comments even after switching to a default theme and deactivating user plugins.

I'm seeing a similar error message as Niels's report above on the console.

WP-Admin > Comments is loading fine.

**Comment by arunsathiya** [comment]
I can consistently reproduce this issue as well, using the steps on this issue https://github.com/Automattic/wp-calypso/issues/48070. I discovered this issue via this user report: 3526432-zen.

**Comment by poojashetty18** [comment]
I re-checked the comment section and it's now displaying as expected on Calypso as well as wp-admin.

> Another similar report on #3554034-zen
> 
> URL: https://wordpress.com/comments/all/blog.lostartpress.com
> 
> AT site and we are unable to view the comments even after switching to a default theme and deactivating user plugins.
> 
> I'm seeing a similar error message as Niels's report above on the console.
> 
> WP-Admin > Comments is loading fine.

**Comment by katiebethbrown** [comment]
Another report in 25965876-hc

I can also replicate the issue on a test site. Entering text in the `Website` field of the comment form that has a space will break the comments page display with the error `TypeError: URL constructor: https://wordswitha%20spaceinthemiddle.com is not a valid URL.`

The comments are still manageable via wp-admin. Removing the offending comment from wp-admin will restore loading of the Calypso page.

**Comment by cathymcbride** [comment]
Way to repro @katiebethbrown ! I'll update the title to reflect your findings!

**Comment by ersatzpenguin** [comment]
This came up again in 26437453-hc and I followed up with the user in 3585632-zen directing them to access comments in WP-Admin in the meantime.
