### ISSUE TITLE
Store: Editing the order does not save changes

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#47365]
#### Steps to reproduce

1. Starting at URL: WordPress.com > Store > Orders page.
2. Edit one of the orders and change the order status, ex. Processing -> Completed.
3. Click on the Update button. 

#### What I expected
The changes in the Order to be saved successfully.

#### What happened instead
The order changed failed to be saved.

#### Screenshot / Video
https://d.pr/v/svPgdb/7A9Hqu3u8Y

#### Context / Source
I was able to replicate the issue on the user's site, as well as on my test site. 

Also when trying to make changes to the order's quantity and updating the order, it did not save either, so I think it the entire module for editing the order from the Store module isn't working. 

When trying to edit the order from WordPress.com > My Sites > WP-Admin > WooCommerce > Orders > Edit Orders page, it gets saved all okay. 

#user-report

Chat: 25555734-hc
Ticket: 3480250-zen

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
