### ISSUE TITLE
Focused Launch: Success view

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47393]
- [x] When the Success screen is shown, the button "X" that closes the Focused Launch modal is hidden and the user can't dismiss the modal
- [x] There is an illustration of confetti above the title
- [x] The title reads _"Hooray!"_ and the subtitle reads _"Congratulations, your website is now live. We're excited to watch you grow with WordPress."_
- [x] The _"Copy Link"_ button copies the site's address to the clipboard
- [x] The _"Continue Editing"_ button closes the modal, showing the block editor
- [x] The _"Back home"_ link redirects the user to the Calypso's home page
- [x] Only the wordpress icon is visible from the modal header. The title should be hidden (but still accessible to screen readers)

Desktop: 

![Screenshot 2020-11-12 at 21 11 53](https://user-images.githubusercontent.com/1083581/98991132-b2e36300-252b-11eb-884a-903ddd719a09.png)

Mobile:

![Screenshot 2020-11-12 at 21 13 48](https://user-images.githubusercontent.com/1083581/98991311-f8a02b80-252b-11eb-8f2c-f5a5f0e94220.png)

**Comment by ciampo** [comment]
@razvanpapadopol please take a look at this issue's specs, in case I missed or misunderstood and requirements

**Comment by ollierozdarz** [comment]
@ciampo correct! Love your work.
