### ISSUE TITLE
Domain Management: Change Primary button visible with just one domain

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#4739]
On the domains page for a site you can change the primary domain. This is not very useful if there is just one domain.

<img width="773" alt="screen shot 2016-04-14 at 13 11 09" src="https://cloud.githubusercontent.com/assets/203408/14526271/812a95c4-0242-11e6-97ab-e88bedc584fa.png">

<img width="758" alt="screen shot 2016-04-14 at 13 11 12" src="https://cloud.githubusercontent.com/assets/203408/14526273/82a25b58-0242-11e6-89e5-89e9631c8443.png">

I suggest removing that button when there is just one domain.

**Comment by v3rse** [comment]
@akirk I'm going to take a crack at this.

**Comment by umurkontaci** [comment]
Fixed with #5332
