### ISSUE TITLE
Focused Launch: "ask for help" block in Summary view

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47395]
- [x] On mobile screens, the support link should be at the bottom of the page (non-sticky)

![Screenshot 2020-11-12 at 21 27 05](https://user-images.githubusercontent.com/1083581/98993013-2dad7d80-252e-11eb-9ca9-3be7adebb99e.png)

- [x] On desktop screens, the support link should be side-to-side with the _"Launch your site"_ button

![Screenshot 2020-11-12 at 21 38 06](https://user-images.githubusercontent.com/1083581/98994029-8598b400-252f-11eb-8618-4da88dae47e6.png)

- [x] The gray text reads _"Questions? Our experts can assist"_

- [x] The link reads _"Ask a Happiness Engineer"_ and, when clicked, should redirect the user to the `/help` page

**Comment by ciampo** [comment]
@ollierozdarz  and @razvanpapadopol please take a look at this issue's specs, in case I missed or misunderstood and requirements

**Comment by ollierozdarz** [comment]
@ciampo Looks good to me.
