### ISSUE TITLE
Auto focus cursor on Pexel search bar

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#47397]
This is a minor enhancement that I think may be worth adding! When visiting the Pexels free photos page, we should auto focus the cursor on the Pexel search bar to encourage folks to search for photos! It can be hard to see the search bar otherwise.

#### Steps to reproduce

1. https://wordpress.com/media/
2. Click top left image dropdown, select Pexels free photos
3. The search bar is not auto focused

#### What I expected

![Screen Shot 2020-11-12 at 2 55 41 PM](https://user-images.githubusercontent.com/4505888/99006721-c1178c00-24f7-11eb-86eb-923e42ce5733.png)

#### What happened instead

![Screen Shot 2020-11-12 at 2 55 38 PM](https://user-images.githubusercontent.com/4505888/99006727-c379e600-24f7-11eb-9185-ff1394b0f4bc.png)

**Comment by Aurorum** [comment]
PR for this issue in #47652. :)
