### ISSUE TITLE
Pages not loading with Gutenberg plugin on

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#47447]
#### Steps to reproduce

Try to edit any page and the editor won't load
Turn off Gutenberg plugin and it works

#### Browser / OS version
Multiple (for me and user)

#3491309-zd

**Comment by cathymcbride** [comment]
@rickmgithub can you add the gutenberg version you are seeing this fail with? Also, I believe the latest Gutenberg was re-released pretty quickly after it was shipped. Can you verify this still happens?

**Comment by synora** [comment]
Gutenberg loads pages and posts as expected now. Closing issue.
