### ISSUE TITLE
Email Confirmation: Delay notice for new users.

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#4744]
All new users on WordPress.com see an email confirmation notice pretty much everywhere in Calypso:

![calypso](https://cloud.githubusercontent.com/assets/191598/14531414/3d20597a-022b-11e6-86a4-b58985df1862.png)

I recently made changes to make the notice less bright and dismissible, but I think we can do more to make it less annoying.

I'd like to see the notice show up a day (or so) after a new user signs up. This way their first time experiencing Calypso won't be muck'd up by an annoying notice.

**Comment by shaunandrews** [comment]
It'd actually be really nice to move away from a `notice` altogether, and instead use a (single, or series of) timed notification.

**Comment by jblz** [comment]
We could accomplish this by setting a cookie at signup w/ a lifetime of however long you'd like to delay the notice. When the cookie expires, the client checks for verification status & shows the notice if unverified. If they dismiss, set a cookie for a (shorter) interval.

**Comment by jonathansadowski** [comment]
I agree with you that this notice is annoying, and can muck up your experience, however when you create a post having not confirmed your account, it saves the post in draft state and gives you no visual indication that that's what actually happened. There are probably a series of other things that are just broken having not confirmed your account. At least the confirmation dialog gives you some hint as to what you need to do to unbreak things. I fear that if we remove it for the first day or so, without fixing the aforementioned issue, we're potentially creating a worse state of confusion.

**Comment by jblz** [comment]
@jonathansadowski: I agree that the notice is the best clue we currently have that something might not have worked as planned, but this is the real issue, imo:

> gives you no visual indication that (your post was saved as a draft instead of being published)

That gets my vote to fix, asap :)

**Comment by lancewillett** [comment]
+1 to changing the post publish messaging to be super clear. :)

**Comment by folletto** [comment]
Just a note to connect various threads about this:

> however when you create a post having not confirmed your account, it saves the post in draft state and gives you no visual indication that that's what actually happened.

The Editor, as a primary UI for WordPress·com as well as a very tight design already, I feel requires a different handling, which is why I'd consider the Editor separate from this issue/discussion. Note that the editor bug/design has been specifically tracked in #2650 and it's currently being fixed in #4806 (testing is welcome!).

Once #4806 lands with the editor on a separate code path, we should have more freedom in addressing this issue specifically. :)

**Comment by lancewillett** [comment]
This is being handled elsewhere (see above), so closing this one.
