### ISSUE TITLE
Focused Launch: refine logic to highlight Summary steps

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47458]
- [x] If it's a user's first visit to the focused launch flow modal on a free plan  — and therefore the launch store doesn't contain any selected plan or domain — nothing is pre-selected  (#47540) / highlighted
- [x] If the user already made a selection (either via the summary view, the domain/plans view, or by having added items to the cart), the relevant items should be highlighted
- [x] The Plan step should be highlighted only if a domain/subdomain has been already picked.

**Comment by ciampo** [comment]
Hey @ollierozdarz , while working on this issue, this came up:

> We agreed to highlight the site title and domain steps first, and once the user picks a domain, we highlight the plan step. But what if the user is happy with the default domain, what do we do?

How can we address the scenario where the user is happy with their free domain, and therefore wouldn't need to interact with the domain step?

**Comment by ollierozdarz** [comment]
Hey @ciampo, we don't pre-select any of the steps for a user (for Domains or Plans), so the user would need to click on their default domain from the list in order to select it.

Example:
<img width="1232" alt="Screen Shot 2020-11-18 at 3 11 43 pm" src="https://user-images.githubusercontent.com/67085494/99486688-6925cd00-29b0-11eb-8895-4da51b01eb0c.png">

**Comment by tjcafferkey** [comment]
@ollierozdarz do we want to pre-select the users choices if they've already made them, closed the modal (whether accidental or purposely) and reopened it?

I am assuming that we do not want to pre-select anything if this is the first time the user has seen the modal.

**Comment by ollierozdarz** [comment]
Hey @tjcafferkey, yep, that sounds like a great idea!

1. If it's a user's first visit to the focused launch flow modal, nothing is pre-selected. 
2. If they select say, a domain, from the "1. Confirm your domain", or even from the "view all domains" screen, then exit the modal (accidental or purposely), and re-open it, we can remember that selection (if it's technically possible and not a bunch more work).
