### ISSUE TITLE
Gutenberg: WhatsApp block doesn't include +592 (Guyana) in country list

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/wp-calypso#47469]
#### Steps to reproduce

1. Add a post/page
2. Click `+` to add a WhatsApp button
3. Go to select country code (i.e. `+592`)

#### What I expected

+592 (Guyana) is not present. However, `+591` and `+593` are present.

#### What happened instead

Nothing. The WhatsApp button could not be configured for `+592`.

#### Screenshot / Video

<img width="431" alt="Screen Shot 2020-11-16 at 10 01 22" src="https://user-images.githubusercontent.com/39252765/99284096-1652e680-27f3-11eb-9856-d57c4007dd52.png">

#### Context / Source

3491924-zen

Suggested a button block and https://faq.whatsapp.com/general/chats/how-to-use-click-to-chat/?lang=en as a workaround.

**Comment by jeyip** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/17840
