### ISSUE TITLE
Premium Content Block: Existing blocks missing in editor for sites with Premium plan

### ISSUE THREAD

**Issue by TeniCola** [Automattic/wp-calypso#47483]
I've had a user who has encounter a block error, where the message says "Your site doesn't include support for the premium-content block [...]." The blocks are working on the live site, but they cannot edit it with this message in the way.

This error message is similar, but not the same, as the ones in the closed issues #46917 and #47298. This user has also encountered this error in at least 2 of their websites, on two existing posts, and both sites have an active WordPress.com Premium plan -- details in 3493678-zen

#### Steps to reproduce

1. Starting at URL: Any post of page that has an existing Premium content block, in the editor view

#### What I expected

To be able to access and edit the Premium content block as usual / without hinderance

#### What happened instead

The blocks displays a message that says "Your site doesn't include support for the premium-content block [...]" where the only option is to remove it or convert to HTML -- neither which are ideal.

#### Screenshot / Video -- https://d.pr/i/P9brrv

![](https://cdn-std.droplr.net/files/acc_711857/P9brrv)

#### Context / Source

We have already tried checking the block manager, but the Premium block will not appear in that area. \

We've also tried temporarily switching to a Business plan and then to the Premium plan to see if that would help, but even on the Business plan the blocks will not appear as an option.

#user-report

**Comment by mdrockwell** [comment]
Possibly related to the Gutenberg 9.3 issue?
p1605614891133200-slack-CS0SC36SX

I took a look at the two posts referenced in the ticket and no longer see errors for the Premium content block. Letting user know of this.

**Comment by TeniCola** [comment]
Ah, that's good to know it was resolved after reverting the issue in the Gutenberg update, thank you Mike!

We can wait for the user to respond or their ticket to resolve, and if all looks good we can close this GH issue 👍
