### ISSUE TITLE
Onboarding: Allow classname prop to be passed to <Title> and <Subtitle> components

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47496]
In order to allow for these components to be more reusable, they should expose a `className` prop, and merge it with the internal component's classname

Will enable work on #47497

**Comment by StefanNieuwenhuis** [comment]
> They should accept more generic HTML props and just pass them down to the HTML tag that is being rendered

@ciampo, can you please explain which generic HTML props we have to pass down to the HTML tag? Thanks!

**Comment by ciampo** [comment]
> > They should accept more generic HTML props and just pass them down to the HTML tag that is being rendered
> 
> @ciampo, can you please explain which generic HTML props we have to pass down to the HTML tag? Thanks!

I updated the issue's description and reduced the scope to just adding the `className` prop
