### ISSUE TITLE
Focused Launch: Ensure selected domain is always shown to the user in the Domain Details View

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#47512]
### What

When a user enters their site title (e.g. _Toms Photography Tips_) in the Summary View, selects a suggested domain based on this site title in the Domain Details View (e.g. _tomsphotographytips.blog_). Then decides to change the title of their site (e.g. _Toms Fishing Tips_) triggering a regeneration of completely new suggested domains related to fishing. 

We need to ensure that when they then **revisit** the Domain Details view we highlight their initially selected domain (_tomsphotographytips.blog_) after the new list of suggested domains, even though it may be now seemingly unrelated to their suggestions.

### Why

* We need to always show the user their currently selected domain when they're viewing suggested domains. This will prevent users accidentally registering domains that may not be suitable, or related to the topic of their new website.

### Acceptance Criteria

- [x] Should the user navigate to the Domain Details view without having already selected a domain, the Domain Picker in the Details View should show a list of suggestions based on the search query
- [x] Should the user navigate to the Domain Details view while already having selected a domain, the Domain Picker in the Details view should highlight the currently selected domain if it is returned in the list of suggested domains
- [x] Should the user navigate to the Domain Details view while already having selected a domain, the Domain Picker in the Details view should append (and highlight) the currently selected domain as an additional option, if the currently selected domain is not in the returned list of suggested domains

### Considerations

* This issue may require changes to the domain picker package, we need to ensure this doesn't negatively impact the areas it's used in the following:
	- Focused Launch
	- Step-by-step Launch
	- New onboarding

**Comment by tjcafferkey** [comment]
@ollierozdarz just seen your comment [here](https://github.com/Automattic/wp-calypso/issues/47458#issuecomment-729430634) about no domains (or plans) being pre-selected for the user. I am assuming that is the case for if this is the first time the user views the focused launch modal.

There are some other considerations outlined in this issue that me and @ciampo, would you mind reading the issue above and let me know if this sounds right to you?

**Comment by ollierozdarz** [comment]
@tjcafferkey acceptance criteria sounds right to me!
