### ISSUE TITLE
Focused Launch: more robust redirection when rendered within Editing Toolkit

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47542]
The Success view introduced in PR https://github.com/Automattic/wp-calypso/pull/47404 needs to redirect the user to their Calypso home when they click the "Back Home" button.

When used in the Block editor, the Focused Launch is rendered inside an `<iframe>`. Because of the limitations imposed by cross-origin iframes, currently, the redirection is [implemented in a bit of a hacky way](https://github.com/Automattic/wp-calypso/pull/47404/files#diff-2f5e6bd15fcaddc71644575361bf6a5f0193c51502cd8c5337a40d345d897cc9):

```javascript
const origin = 'https://wordpress.com';
const path = url.startsWith( '/' ) ? url : `/${ url }`;
window.top.location.href = `${ origin }${ path }`;
```

A better way of implementing this would be to use actions (from the `@wordpress/hooks` package) and iframe bridge server, so that the redirection can happen in the Calypso window context, without the need to specify an origin

**Comment by razvanpapadopol** [comment]
While it's fine to add extra support when rendering Focused Launch inside the Calypso iframe, we should make sure it won't break when [rendered in wp-admin](https://github.com/Automattic/wp-calypso/issues/47803#issue-751669864).

[ Integration between premium blocks upgrade and Editor Checkout modal](https://github.com/Automattic/jetpack/blob/master/extensions/shared/use-upgrade-flow/index.js#L51-L83) is a good first example.

**Comment by razvanpapadopol** [comment]
superseded by #47762
