### ISSUE TITLE
Focused Launch: Ensure popular plan, selected plan, free plan (in this order) are always shown to the user in the Summary View

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47544]
### What

There are a few scenarios under which the user can visit the Summary view while having selected a domain that is not part of the plan items in the Plans Step in Summary View:

- Scenario A. The user has already a premium plan in the cart that is not part of the initial suggestions in the Summary view. User opens Focused Launch modal, and so the pre-selected plan is not shown to the user.
- Scenario B. The user visits the Plan Details view, picks a plan that is not part of the initial suggestions in the Summary view. The user navigates back to the Summary view, and the currently selected plan is not shown to the user.

### Why

We need to always show the currently selected plan to the user in the Summary view, while keeping the top paid suggestions always at the top and free suggestion always at the bottom.

### Acceptance Criteria

- [ ] The first item shown in the Plan step in the Summary view should always be the recommended plan (with the recommended label). If there isn't a recommended plan, the Premium plan should be displayed instead (with a "Premium" label)
- [ ] The last item shown in the Plan step in the Summary view should always be the default, free plan
- [ ] If the currently selected plan matches one of the 2 items defined in the points above, the Plan step in the Summary view should highlight the matching item
- [ ] If the currently selected plan doesn't match any of the 2 items defined in the points above, the Plan step in the Summary view should display an additional (highlighted) item. This plan item should be the 2nd item from the top — after the first premium plan suggestion, but before the free domain suggestion.
- [ ] If the additional plan item (spec'd in the point above) is showing in the Plan step in the Summary view, and the user selects another plan, the additional plan item should not disappear from the Plan step until the Summary view is re-visited.
- [ ] If the user hasn't made an explicit selection yet in the context of the launch flow, the plan step should not pre-select any plan (as specc'd and discussed in #47458)

![image](https://user-images.githubusercontent.com/1083581/99529380-fdd3ff00-299f-11eb-9a8a-f8173c0539a4.png)

**Comment by razvanpapadopol** [comment]
Re-opening this because the non-default selected plan displayed as the second item of the Plan step in the Summary view isn't currently persisted. Mentioned in https://github.com/Automattic/wp-calypso/pull/47913#issuecomment-737728137

Will be fixed in #47913
