### ISSUE TITLE
Patterns Toolkit: should we hide certain patterns if theme features aren't available

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#47565]
In #46215 one of the patterns appears awkwardly in the pattern inserter, because the currently active theme (in this case "Hemingway Rewritten") doesn't support full width alignment. Looking through other patterns (particularly under Call to Action) I can see that there are a fair few other patterns that also only look good with a theme that has `get_theme_support( 'align-wide' )`. For example if you activate Hemingway Rewritten on a test site, some of the patterns look like this:

| Screenshots  |  |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/99627097-bfb20a80-2a87-11eb-9697-fc174e88a11e.png) | ![image](https://user-images.githubusercontent.com/14988353/99627103-c3459180-2a87-11eb-9855-0a4a3ef85cca.png) |
| ![image](https://user-images.githubusercontent.com/14988353/99627114-c771af00-2a87-11eb-8791-ff0b28eb5ce7.png) | ![image](https://user-images.githubusercontent.com/14988353/99627118-cb053600-2a87-11eb-93cb-d6fb5608a96e.png) |

Should we hide patterns that depend on features like this in environments where a particular feature is unavailable? And if so, how might we go about doing that?

* Shall we flag each pattern that depends on the `align-wide` theme feature with a particular tag and then hide those patterns when the theme does not support wide of full-width alignment?
* We can use a tag like `requires-align-wide` in dotcompatterns to flag the patterns that we'd like to hide.
* In the Editing Toolkit plugin, we can then skip these while registering patterns.

**Comment by andrewserong** [comment]
CC: @Automattic/view-engineering this is a feature enhancement idea to resolve issues like #46215 where we might want to hide certain patterns in situations where we know the pattern isn't going to look the way we want to (e.g. a pattern requires full width alignment, but the theme does not support it).

**Comment by andrewserong** [comment]
I think I have an idea for a (slightly hacky) workaround to conditionally hide patterns within the registration part of the editing toolkit to resolve #46215 for ones we know about, but longer-term it'd be cool to support it with flags somehow rather than hard-coding pattern slugs.

**Comment by andrewserong** [comment]
I've decided to skip the hacky approach of targeting each pattern by slug, as it turns out there's quite a few patterns that will need to be hidden in themes that don't support full/wide alignment.

@ianstewart / @apeatling does this approach of adding a `requires_align_wide` tag to the patterns in dotcompatterns sound acceptable? Is there a different way you'd like to handle this?

If this approach sounds okay, I'm happy to go in and add the tag to those patterns that obviously don't render well in the inserter for these themes without the support. I have a PR ready for review in https://github.com/Automattic/wp-calypso/pull/47571 — it's just waiting on us adding the tag in order for us to test it properly.

**Comment by simison** [comment]
>approach of adding a requires_align_wide tag to the patterns in dotcompatterns sound acceptable? Is there a different way you'd like to handle this?

Possible future improvement could be automating that category on post_save?

**Comment by andrewserong** [comment]
> Possible future improvement could be automating that category on post_save?

That's a very cool enhancement idea! Should be pretty straightforward to implement after we get #47571 approved/deployed.

**Comment by andrewserong** [comment]
***Update:*** thanks to @ramonjd's feedback, I've updated the tag's slug to use hyphens instead of underscores, to better match against the theme feature. E.g. `requires-align-wide`. I've updated references in comments in this issue to reflect the new naming.

**Comment by ianstewart** [comment]
@andrewserong thanks :) — doing a manual review of all the patterns starting … now.
