### ISSUE TITLE
Jetpack Cloud: Pricing: "Free" plan flow redirects to latest "paid" plan flow  

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#47560]
It seems that "Free" plan flow from Jetpack Cloud does not work properly. Every time I try the connection flow from Jetpack.com -> Pricing I'll end up on the checkout page with the latest "paid" plan I attempted to purchase (for different site)
#### Steps to reproduce

1. Create a JN site
2. Go to Jetpack.com > Pricing and select any paid plan option
3. Go through the flow, stop once on Checkout page.
4. Create a new JN site
5. Go to Jetpack.com > Pricing and select "Free" plan option
6. Go through the flow, see unexpected Checkout page with a plan from step 2

#### What I expected

No checkout page in "Free" plan flow

#### What happened instead

A checkout page with a paid plan in "Free" plan flow

![screencast 2020-11-18 20-42-50](https://user-images.githubusercontent.com/5654161/99573578-f5e77f80-29de-11eb-990a-437c77762a45.gif)

**Comment by rcanepa** [comment]
Thanks for reporting this. I've created a ticket 1164141197617539-as-1199221059177329 to make sure this gets fixed.

**Comment by rcanepa** [comment]
Hey @brbrr, I think it's safe to close this issue since we fixed it some time ago. The problem was that we were storing the latest selected paid plan in a cookie and we never cleaned up that cookie. That created all sorts of unexpected problems in different flows.

**Comment by brbrr** [comment]
Cool! Closing.
