### ISSUE TITLE
Gutenberg Edge: Tab/browser locks up upon adding a columns block

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#47579]
#### Steps to reproduce

1. Go to site > Posts/Pages > Add new
2. Add title 
3. Add a columns block 
4. Browser tab freezes 
5. Other tabs slow and also freeze

#### What I expected

To add content to the columns and use GB. 

#### What happened instead

Tab locks up, other tabs also tend to slow and lock up also.

#### Browser / OS version

Operating systemOS X 11.0.1
Chrome 87

#### Screenshot / Video

[https://d.pr/v/TkPYQi](https://d.pr/v/TkPYQi)

#### Context / Source

Please see slack reference: [https://a8c.slack.com/archives/C015AL3QL7M/p1605745525089400](https://a8c.slack.com/archives/C015AL3QL7M/p1605745525089400)

#dogfooding 

Found this by using whilst updating my personal blog and troubleshooted with @getdave to narrow down the issue to two main tellers, Gutenberg Edge being activated and Adding a columns block.

**Comment by ockham** [comment]
I can repro with GB 9.4 on a Simple Site and an ephemeral (i.e. Atomic) site that I use for testing, both with pretty standard settings, and using the Twenty Twenty theme.

Curiously, I couldn't repro on a vanilla WP.org site with GB 9.4.

Furthermore, I've noticed that on an Atomic site, the problem goes away if I disconnect Jetpack from WP.com

**Comment by ockham** [comment]
@ellatrix made a fix in GB: #27090. We still don't quite know how Jetpack interferes with this...

**Comment by aleone89** [comment]
@ockham When I was down the rabbit hole trying to work this out, I did wonder if there was an app/logging in issue at play here, as if something was constantly autosaving and timing out... I'm not sure if this helps, but I'm hoping it does.

**Comment by ockham** [comment]
Curiously, I _can't_ seem to repro on a Jurassic Ninja site with GB 9.4 and JP connected to WP.com :thinking:

**Comment by jeherve** [comment]
I seem to experience similar issues with other blocks that have child blocks, such as the Form block.

**Comment by ockham** [comment]
We've had a report from @apeatling who ran into this issue with the Premium Content Block. He said that he

> removed templatelock from innerblocks and it stopped freezing using that block. Didn’t really make much sense

(source: p1605801472487500-slack-CBG1CP4EN?thread_ts=1605796017.477000&cid=CBG1CP4EN)

**Comment by ockham** [comment]
Closing, now that @fullofcaffeine has updated edge to GB 9.4.1 (D53047-code).

Feel free to continue to use this for any additional findings, y'all!
