### ISSUE TITLE
Focused Launch: i18n

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47576]
**Update Feb 5:** As an immediate solution we should extract `__()` calls outside ternaries as confirmed in p1612507064288500-slack-C0KDTA48Y 

## What 
We should make sure Focused Launch is fully localized in all WordPress.com languages.

There are some untranslated texts across Focused Launch at the moment in all views. 

Some of them (possibly PlansGrid related) might share the same cause with #49589 but we don't know for sure until we:
- make sure we're using i18n functions correctly
- compare translation bundles from wpcom & wporg like in https://github.com/Automattic/wp-calypso/issues/49589#issuecomment-771495009

### Summary
- [x] title and subtitle
- [x] _Default_ text for sub-domain
- [x] _Not available with your domain selection_ text for Free plan when custom domain is selected
<img width="1042" alt="Screenshot 2021-02-04 at 08 12 13" src="https://user-images.githubusercontent.com/14192054/106856170-c33c5180-66c6-11eb-88aa-55e08727eafb.png">

### Domain details
- [x] _Free_ text used instead of price for sub-domain. Also by looking above (Summary view) shouldn't this text say "Default" instead given the subdomain already exists and for consistency?
- [x] _Selected_ button label
- [x] The entire _Use a domain I own_ item
<img width="1148" alt="Screenshot 2021-02-02 at 10 29 31" src="https://user-images.githubusercontent.com/14192054/106601376-3c6f6380-6564-11eb-8795-5c1e7bfb6233.png">

### Plan details
- [x] Billing period toggle labels
- [x] _Current selection_ label on select button
- [x] _billed annually_, _billed monthly_ texts below price
- [x] _Save xx% ..._ text
- [x] _Included with annual plans_ text
<img width="1366" alt="Screenshot 2021-02-02 at 16 18 44" src="https://user-images.githubusercontent.com/14192054/106628568-9848e500-6582-11eb-8b58-0aff5bf03878.png">

## Why
The current launch flow is available in all languages and so should be the experiment. Reported this blocker on the experiment page: pbxNRc-zm-p2#comment-1609

## Acceptance criteria
- [x] static text should be translated
- [x] external links should be localized if needed (related: p58i-9Mt-p2#comment-48394)

API calls should be localized, although this is tracked separately (and potentially fixed by #49559 and #49759)

## Context
Most of the i18n work for packages and Editing Toolkit was completed on December 3, 2020 (see pbxNRc-zm-p2#comment-1248)

**Comment by razvanpapadopol** [comment]
Let's keep this in Backlog until we have all the UI related tasks in https://github.com/Automattic/wp-calypso/milestone/328 implemented.

**Comment by razvanpapadopol** [comment]
There are some untranslated texts across Focused Launch at the moment in all views. Some of them might share the same cause with #49589 but we don't know for sure until we compare translation bundles from wpcom & wporg like in https://github.com/Automattic/wp-calypso/issues/49589#issuecomment-771495009

### Summary
- [ ] title and subtitle
<img width="1135" alt="Screenshot 2021-02-02 at 10 28 44" src="https://user-images.githubusercontent.com/14192054/106601402-41ccae00-6564-11eb-8dbf-5a7629401d45.png">

### Domain details
- [ ] _Free_ text used instead of price for sub-domain
- [ ] _Selected_ button label
- [ ] The entire _Use a domain I own_ item
<img width="1148" alt="Screenshot 2021-02-02 at 10 29 31" src="https://user-images.githubusercontent.com/14192054/106601376-3c6f6380-6564-11eb-8795-5c1e7bfb6233.png">

### Plan details
- [ ] Data coming from Plans and PlanDetails API
- [ ] Billing period toggle labels
- [ ] _Current selection_ label on select button
- [ ] _billed annually_, _billed monthly_ texts below price
- [ ] _Save xx% ..._ text
- [ ] _Included with annual plans_ text
<img width="1373" alt="Screenshot 2021-02-02 at 10 30 45" src="https://user-images.githubusercontent.com/14192054/106601392-409b8100-6564-11eb-810c-7c062a1fae31.png">

**Comment by alshakero** [comment]
Alright. I investigated and I couldn't track down any issues in the focused launch implementation. It's a translation issue for sure. 

What I did is the following:

#### My setup
1. I set my language to Spanish.
2. I chose "You're almost there!" and "Name your site" phrases as my test phrases. They're both translated to Spanish [[1](https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=You%27re+almost+there), [2](https://translate.wordpress.com/projects/wpcom/it/default?filters%5Bterm%5D=Name+your+site&filters%5Bterm_scope%5D=scope_originals&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc#)].
3. Note that "Name your site" is translating well, but "You're almost there" is failing.

#### Method

1. I went right to the bundled file to role out all the lower levels.
2. I compared the translation code between the two, and it's 100% identical. 
3. To verify that the same `__` function is used, I replaced "Name your site" with "You're almost there!" in the same line of code. And that didn't help. I think this roles out the context issue, too.

**Comment by ciampo** [comment]
> Free text used instead of price for sub-domain. Also by looking above (Summary view) shouldn't this text say "Default" instead given the subdomain already exists and for consistency?

By looking at the code, we have an explicit check to use "Free" or "Default" depending on the domain picker variation.

In the summary view, we use the "individual-item" variation, while in the domain details view we use another variation — i assume this was done to respect the design spec. @razvanpapadopol  Probably better to leave it as it is, for the purpose of this issue?

**Comment by razvanpapadopol** [comment]
keeping this open until the translations are actually showing up
details: p1612799810346300/1612777345.329400-slack-C0KDTA48Y

**Comment by ciampo** [comment]
@razvanpapadopol it seems like translations are now showing in production — should we close this issue?

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/49812
