### ISSUE TITLE
Remove AB test for "confirm your email" landing page

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#47578]
See code bit from pbmo2S-A4-p2 (item ~2018-09-21~ 2018-06-04).

It defines the landing page for "confirm your email" emails:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/87168/99658165-c9c41100-2a67-11eb-8291-78f67e71a20c.png">

Let's remove the AB test and consolidate to landing at customer home, instead of posts list.

**Before (or, for like 5% users):**

<img width="880" alt="Screenshot 2020-11-19 at 12 58 04" src="https://user-images.githubusercontent.com/87168/99657923-7225a580-2a67-11eb-9aab-e0a060df6646.png">

**After:**

<img width="1532" alt="Screenshot 2020-11-19 at 12 58 17" src="https://user-images.githubusercontent.com/87168/99657943-7c47a400-2a67-11eb-8a36-25df17ce95e4.png">

Currently at code, customer home version is missing the `?verified=1` bit from the URL. That triggers that notification visible in above screenshots.

Let's:

- Add that `?verified=1` to the URL
- Change copy to be just "Email confirmed!"

@rickybanister sounds good? Alternatively we could remove the whole verification-notification if you'd prefer.

**Comment by andrewserong** [comment]
Looks like the `verified` notice was already in the process of being updated to the simpler `Email confirmed!` a long time ago: https://github.com/automattic/wp-calypso/blob/43d3beb3962b37f72ea2f2f0f78c6e480c0b758e/client%2Fcomponents%2Femail-verification%2Findex.js#L27

Should be a couple of lines to update that one. I'll look into this and the backend change to remove the A/B test tomorrow.

**Comment by andrewserong** [comment]
Code changes for this one are ready for review:

1. The small front-end change to the notice (#47687)
2. Remove the code path for the A/B test (D53228-code)
3. Remove the A/B test (D53230-code)

**Comment by andrewserong** [comment]
Deployed the above changes, so this A/B test is now removed, and I see the checklist in pbmo2S-A4-p2 has been updated to reflect this, too.
