### ISSUE TITLE
Feature Request: Option to set default post list view on sites with multiple authors to "Everyone" instead of just "Me"

### ISSUE THREAD

**Issue by ersatzpenguin** [Automattic/wp-calypso#47599]
#### Steps to reproduce

On a site with multiple authors...

1. Starting at URL: https://wordpress.com/home/mygroovydomain.com
2. Click on Site > Posts in the left menu.
3. You'll be taken to https://wordpress.com/posts/my/mygroovydomain.com and see only your own posts.
4. Next, click on the "Everyone" tab in the view options at the top to see everyone's posts (url changes to: https://wordpress.com/posts/mygroovydomain.com).
5. Navigate to another page/screen.
6. Click on Site > Posts again.
7. End up back at https://wordpress.com/posts/my/mygroovydomain.com and see only your own posts.

#### What I expected
I expected that the setting chosen in the view settings on the posts page would be persistent—or that there would be some way to set the default view in the Calypso site settings.

This is especially important for site admins and editors who might be managing the posts of others.

#### What happened instead
Calypso continually defaulted back to the "me" view in posts.

#### Context / Source

This came up in: 25754117-hc

#user-report

**Comment by ericamQA** [comment]
Unable to reproduce (_only applies with Nav Unification Dashboard Appearance setting OFF_). The default is set to "Everyone" with the ability to change to "Me". Navigating away and coming back, it goes back to "Everyone."
