### ISSUE TITLE
My Home: Align checklist with Revised Task Card

### ISSUE THREAD

**Issue by sfougnier** [Automattic/wp-calypso#47604]
The current Customer Home checklist vertical height is quite long, pushing all other content down the page and creating a lot of unused, trapped white space. This update will decrease the height to create a better balance of space and elements on the page while still maintaining the page hierarchy.

This also aligns the styling and height to 272px to match new task card in https://github.com/Automattic/wp-calypso/issues/43540.

**Current**

Desktop
<img width="1440" alt="Screen Shot 2020-11-19 at 5 40 42 PM" src="https://user-images.githubusercontent.com/67021691/99733215-d445d100-2a8e-11eb-8db4-07122dd13802.png">

Mobile
<img width="375" alt="Screen Shot 2020-11-19 at 5 41 07 PM" src="https://user-images.githubusercontent.com/67021691/99735931-7c5d9900-2a93-11eb-8654-16401f8070d5.png">

**Proposed Update**
Checklist items that extend beyond the card height of 272px become scrollable, indicated by a gradient either at the top or bottom to indicate more items. In mobile, the checklist remains an accordion. 

Desktop - Landing state
<img width="1440" alt="Desktop - Checklist 1" src="https://user-images.githubusercontent.com/67021691/99736082-c8104280-2a93-11eb-854b-f65bf2075f0b.png">

Desktop - Selected incomplete task
<img width="1440" alt="Desktop - Checklist 2" src="https://user-images.githubusercontent.com/67021691/99736096-d0687d80-2a93-11eb-9bca-4b56ce23cf6e.png">

Desktop - Selected completed task
<img width="1440" alt="Desktop - Checklist Completed" src="https://user-images.githubusercontent.com/67021691/99736258-19203680-2a94-11eb-8b7c-6cea05656b64.png">

Desktop - Scrolled, completed tasks
<img width="1440" alt="Desktop - Checklist 4" src="https://user-images.githubusercontent.com/67021691/99736195-faba3b00-2a93-11eb-90f5-1ce13ef3dd6b.png">

Mobile - all 4 states
<img width="1831" alt="Screen Shot 2020-11-19 at 6 16 50 PM" src="https://user-images.githubusercontent.com/67021691/99736311-2ccb9d00-2a94-11eb-8e60-b497d309b4de.png">

[Figma links](https://www.figma.com/file/2v3gyTfWHBDS9iT7aoVCB4/Customer-Home-Checklist?node-id=280%3A3895)

**Comment by jordesign** [comment]
This seems still relevant _if_ the current structure of My Home and the task list are retained. But possible we won't need to worry about it depending on changes that may happen to the checklist itself based on @jeffgolenski's work.

I'd place this as pretty low priority till we have firmer plans.

**Comment by jordesign** [comment]
Based on current plans - I'd say that @jeffgolenski's work on the refresh will address this problem (amongst others). 
pd2qGl-4i-p2

Closing this for now.
