### ISSUE TITLE
Social Icons Block: blank icons showing when first inserting block onto a page

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#47635]
#### Steps to reproduce

1. Insert block onto a page
2. Try to edit icons

#### What I expected

- Default icons would be present and editable

#### What happened instead

- Three blank circles with missing icons shown instead 

#### Screenshot / Video

<img width="1185" alt="Markup 2020-11-20 at 16 33 59" src="https://user-images.githubusercontent.com/51966986/99824895-3b768a80-2b4e-11eb-92fb-9a4d1d678866.png">

![Screen Capture on 2020-11-20 at 16-29-05](https://user-images.githubusercontent.com/51966986/99824642-e5a1e280-2b4d-11eb-8772-2c7ddbe6b749.gif)

#### Context / Source

#25700654-hc

**Comment by cathymcbride** [comment]
By design: please see https://github.com/Automattic/wp-calypso/issues/47154
