### ISSUE TITLE
Main branch renamed to `trunk`

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#47637]
On 20 November, 2020 the main branch of this repository was renamed to `trunk`. To update your local repository, follow this script:

```
$ git checkout master
$ git branch -m master trunk
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/trunk
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/trunk
```

Open PRs against the old main branch have been retargeted to `trunk`. You may still need to rebase against the lastest `trunk` to fix CI issues on your PRs.

Thanks!

**Comment by worldomonation** [comment]
Oops, I accidentally unpinned this issue. Re-pinned to undo my mistake.
