### ISSUE TITLE
Donations: Subsequent blocks in post are nested under donation block

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#47643]
#### Steps to reproduce

1. On a WordPress.com hosted site create a new test page.
    * Was able to reproduce with themes Twenty Twenty and Spearhead
2. Add a Donations block, and below that add a Layout Grid block with say two columns with images in each.
3. Preview the page.

#### What happened

* When the Donations block is placed above the Layout Grid block, it seems to nest the subsequent Layout Grid block so the layout is not what is expected.
* Have not tested to see if there are certain block types that aren't nested in this fashion. 

#### Browser / OS version

* Chrome Version 87.0.4280.67, macOS Big Sur

#### Screenshot / Video

![blocks](https://user-images.githubusercontent.com/15803018/99858924-d91c8a80-2b4b-11eb-86b4-1cb8d284a36a.png)

![nesting](https://user-images.githubusercontent.com/15803018/99858931-db7ee480-2b4b-11eb-88b1-595ee29cbbc9.png)

#### Context / Source

3507627-zd-woothemes

**Comment by formosattic** [comment]
+1 25951815-hc

**Comment by philnick206** [comment]
Reported in #3529426-zen

**Comment by samiff** [comment]
Another in 26172769-hc

**Comment by joweber123** [comment]
Reported 3777397-zen

**Comment by NoHopeRadio** [comment]
28402793-hc

**Comment by retnonindya** [comment]
29017216-hc

**Comment by kriskarkoski** [comment]
29124921-hc. Their donation block was in a Cover block initially and broke the layout of all subsequent blocks. Even with moving it to the top-level it breaks the layouts and color settings of blocks that follow it.

**Comment by kristarella** [comment]
I found this when working with the block too, particularly inside a cover or group block with a background color, it will cause the color to flood the rest of the page.

**Comment by dsas** [comment]
This was fixed in January by [jetpack#22236](https://github.com/Automattic/jetpack/pull/22236)
