### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ro-savage** [Automattic/wp-calypso#4764]
The internal links in [CONTRIBUTING.md](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md) are broken as it was written expecting to be in root.

I will submit PR to resolve this issue.

**Comment by ro-savage** [comment]
PR #4765 fixes this issue

**Comment by lancewillett** [comment]
Good eye! Thanks for catching it, and the fixes.

**Comment by ro-savage** [comment]
No worries. Thanks for open sourcing such a large react product we can all learn from!
