### ISSUE TITLE
Non-English URL in Post/Page Editor's Permalink Section

### ISSUE THREAD

**Issue by bizanimesh** [Automattic/wp-calypso#47646]
#### What I expected

I was expected WordPress to accept the non-English URL in the post/page editor's permalink section.

Path: _My Site(s) > Site > Posts/Pages >_ Click on _Settings_ icon in top right corner _>_ Click _Page/Post >_ scroll down and click _Permalink_.

#### What happened instead

WordPress is **not** accepting non-English URL in the post/page editor's permalink section, but accepting them in WP Admin.

Path in WP Admin: _My Site(s) > WP Admin > Posts/Pages > Quick Edit > Slug_

#### Browser / OS version

Bowser: Google Chrome (Version 87.0.4280.66)

OS: Windows 10 (Version 1909)

#### Screenshot / Video

WordPress is not accepting non-English URL in the post/page editor's permalink section: https://d.pr/v/6QXgAt 

WordPress is accepting non-English URL in the WP Admin: https://d.pr/v/E2ThHp

Language in the video: Japanese - こんにちは (Translation: Hello)

**Comment by jordesign** [comment]
Hey @bizanimesh - it seems like this might be related to the way Gutenberg is handling slugs.
Does it seem related to https://github.com/WordPress/gutenberg/issues/24710 ?

**Comment by bizanimesh** [comment]
Hey @jordesign - that's correct, it is the same issue. 🙂

**Comment by jordesign** [comment]
OK great - in that case I'll close this issue in favour of https://github.com/WordPress/gutenberg/issues/24710

**Comment by bizanimesh** [comment]
Yes sure. 🙂
