### ISSUE TITLE
Customizer: Left sidebar menu heading cut off after scrolling 

### ISSUE THREAD

**Issue by startuptester** [Automattic/wp-calypso#47644]
#### Steps to reproduce

1. In themes, select customize
2. Choose Site Identity
3. Scroll down and up
(might have to resize the window to make sure it scrolls)

#### What I expected
The header to either remain in view in full or disappear entirely. 

#### What happened instead
Scroll up and down a few times  and notice the header sometimes shows cut off. 

#### Browser / OS version
Safari Version 14.0 (15610.1.28.1.9, 15610) 
(originally found on WPiOS)

#### Screenshot / Video
https://cloudup.com/c_KaUalFKnV

<img width="1440" alt="Screen Shot 2020-11-20 at 5 23 12 PM" src="https://user-images.githubusercontent.com/66104034/99862678-e2abef80-2b57-11eb-9915-5b441e912bb4.png">

#### Context / Source

https://github.com/wordpress-mobile/WordPress-iOS/issues/15330

**Comment by ericamQA** [comment]
Unable to reproduce on multiple themes (Pique, 2021, and Ixion tested) on AT and Simple sites. Closing.
