### ISSUE TITLE
Copywriting on Pricing page: From "Unlimited Premium Themes" to WordPress.com-related

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#47658]
Hi team! 

I wonder if we can change the wordings on https://wordpress.com/pricing on **Site Customization**, specifically for "Unlimited Premium Theme", and change it to "Free access to WordPress.com Premium themes."

The reason is, sometimes folks got confused with premium themes, and they thought the "premium themes" mentioned on the Pricing page is the third-party, customized, premium theme:
https://wordpress.com/support/themes/uploading-setting-up-custom-themes/

![image](https://cldup.com/orzLM2WH96.png)
*Direct link: https://cldup.com/orzLM2WH96.png*

#### Context / Source
This discussion came up on my team's internal discussion and there were some user interactions/questions about this. Feel free to ping me in case you need more information! Thank you.

**Comment by inaikem** [comment]
Closing as no longer relevant per this discussion: pNEWy-e9X-p2
