### ISSUE TITLE
2FA Validation: India number not validating

### ISSUE THREAD

**Issue by kamlesh08** [Automattic/wp-calypso#47653]
**Steps to reproduce**:

1. Starting at WordPress.com Desktop App (Ubuntu)
2. Click on the Profile icon at the top-right. Head over to Security >> Two-Step Authentication.
3. Select Country code as India (+91).
4. Enter a phone number.
5. Click "Verify via SMS".

**What I expected**
I will receive SMS on my number and will be able to enable 2FA.

**What happened instead**
I got an error: Your client is not permitted to set the user's two_step_sms_country setting.

**Browser / OS version**
Ubuntu 20.04.1 LTS - 64-bit

**Screenshot / Video**
![Screenshot from 2020-11-23 01-37-28](https://user-images.githubusercontent.com/22547800/99915904-aa113f00-2d2c-11eb-856b-febad4a6e153.jpg)

**Context / Source**
#dogfooding, #manual-testing

**Comment by liviopv** [comment]
📌 ACTIONS
Asked for help with testing here p1714642953641689-slack-C73QUC108

**Comment by liviopv** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
Based on p1714642953641689-slack-C73QUC108 it's not an India-specific issue, it seems to be isolated to the Desktop App 

📌 ACTIONS
- Closed as duplicate in favor of https://github.com/Automattic/wp-calypso/issues/48974
