### ISSUE TITLE
RSS Feed: Google news feeds missing the links to each post

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/wp-calypso#47651]
#### Steps to reproduce

1. Starting at URL: https://www.google.com/alerts
2. Either use an existing alert you own or create a new one
3. Set up the alert to be : "How Often": "As it happens" AND "Deliver to" : "RSS feed"
4. On the list, the new alert (or existing) will have a RSS symbol with a link - copy that
5. Head to your site -> Customizer -> Widgets -> Any Widget area -> Add an RSS feed
6. Enter your RSS feed link. Note that the posts show up in a list without links

#### What I expected

The RSS feed widget showing up the posts names and links to each post, as with other feeds. I tested this with a Jurassic ninja as well, this is the result (what I expected):

<img width="1565" alt="Screen Shot 2020-11-22 at 11 42 17" src="https://user-images.githubusercontent.com/30905719/99902722-d9399900-2cb7-11eb-980e-df3e90edaa5f.png">

#### What happened instead

The RSS feeds of Google alerts do not have links, unlike the regular wordpress feeds:

<img width="1523" alt="Screen Shot 2020-11-22 at 11 39 21" src="https://user-images.githubusercontent.com/30905719/99902670-70eab780-2cb7-11eb-9204-c2840e1878ba.png">

#### Browser / OS version

Firefox / Chrome

#### Screenshot / Video

See above on each section.

#### Context / Source

 #user-report

3511156-zd

**Comment by ericamQA** [comment]
Unable to reproduce. Closing. 

![RSS-Feed-from-Google-Alert](https://user-images.githubusercontent.com/44411833/119177531-704e9600-ba3a-11eb-8df1-4ff70537a65a.png)
