### ISSUE TITLE
Launch: site launch flow stops showing a free option after domain search

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#47664]
#### Steps to reproduce

1. Create a free website using your signup flow of choice, but do NOT launch it.
2. Starting at URL: https://wordpress.com/start/new-launch/domains-launch?source=home&siteSlug=example.wordpress.com (where example.wordpress.com is the subdomain for your unlaunched site)
3. Notice that when first visiting this launch UI, you see an option to keep your wordpress.com subdomain and can skip buying a domain.
4. Search for a domain. Notice that you no longer see an option to keep your wordpress.com subdomain.

#### What I expected

I expected to be able to keep/select my wordpress.com subdomain, or in some way be able to get back to a free flow.

#### What happened instead

After I searched for a domain, I was no longer offered the option of a free wordpress.com domain, and had no way of accessing one.

#### Browser / OS version

Chrome 86.0.4240.198 on MacOS Catalina 10.15.5.

#### Screenshot / Video

<img width="1074" alt="screen_domain_launch_with_skip_option" src="https://user-images.githubusercontent.com/3376401/99940374-b15c3b00-2d74-11eb-9acf-b5a715a57b6a.png">

After searching:
<img width="1680" alt="domain_launch_no_skip_option" src="https://user-images.githubusercontent.com/3376401/99941506-c9cd5500-2d76-11eb-9291-9da94206af0a.png">

#### Context / Source

@lsl found this while testing, and it became apparent that this is a subtle bug in the way we handle rendering for the post-search flow, especially because the search term is remembered for the site, so you can't get back to the skip option.

**Comment by daledupreez** [comment]
From my initial investigation here, it looks like this is a subtle issue we'll need to work out as it's in these heavily (re)used domains components.

**Comment by lsl** [comment]
Many reports of this, I'm a little worried about how long this may have been in play.

https://wordpress.com/forums?s=launch

**Comment by simison** [comment]
>  I'm a little worried about how long this may have been in play.

Likewise. Let's get the fix out asap but then also investigate when this started.
