### ISSUE TITLE
data-stores: Use `createRootURLMiddleware` to improve data store apiFetch request building

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#47675]
Context here: https://github.com/Automattic/wp-calypso/pull/47589#discussion_r527674633

We currently hand-write the full path for `apiFetch` requests to `https://public-api.wordpress.com`. This could be improved by using the `createRootURLMiddleware` in conjunction with the `namespaceAndEndpointMiddleware` to allow us to avoid having to write the root URL every time and instead just pass the namespace and endpoint of the request we're making.

Questions:
1. Where should this new middleware live?
2. What will be the extent of this change, how many places will we need to touch to safely make this change?
3. At what point would this new middleware be registered? As part of the `data-stores` package? Or as a seperate package of `apiFetch` middlewares? We don't currently call `apiFetch.use` anywhere in `wp-calypso` so this would be a fully new pattern.

/cc @tyxla

**Comment by tyxla** [comment]
> 1. Where should this new middleware live?

I think we can put it in the data-stores package for now. With the growing needs and integration with Gutenberg we'll likely need to use it somewhere else, too, but we can always extract it later if necessary.

> 2. What will be the extent of this change, how many places will we need to touch to safely make this change?

Essentially, every `apiFetch` that is making a request to and endpoint at `public-api.wordpress.com`. We can do that in separate PRs or in a single PR.

> 3. At what point would this new middleware be registered? As part of the `data-stores` package? Or as a seperate package of `apiFetch` middlewares? We don't currently call `apiFetch.use` anywhere in `wp-calypso` so this would be a fully new pattern.

I don't have an answer here - we should experiment with that, but from my understanding, when we register a middleware with `apiFetch.use()`, that's being handled globally for any subsequent `apiFetch()` call, so we have to make sure we're doing it in a way that allows us to not break any other `apiFetch` usages, if that makes sense. One way to do it would be to have a list of supported WP.com endpoints and if the path provided matches, we would alter the root URL and the namespace. What do you think?

**Comment by synora** [comment]
Hi @sarayourfriend and @tyxla this issue has gone stale. Is it still relevant or can it be closed?

**Comment by tyxla** [comment]
I'm fine to close it. We can re-open if we need it in the future 👍
