### ISSUE TITLE
Reader: Tracks property `subscription_count` is not working

### ISSUE THREAD

**Issue by martinremy** [Automattic/wp-calypso#47678]
This property should be [present for all reader events](https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/reader/stats.js#L114), but is 0 or missing for most/all reader Tracks events.  p5PDj3-4WA

**Comment by bluefuton** [comment]
Long-standing bug this one :(  

Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/14470.
