### ISSUE TITLE
Domains: Support .cpa TLD

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#47676]
I had a customer in 3162095-hc asked us to allow registering and mapping `.cpa` TLD.

They couldn't even map it due to the following error:
<img width="1142" alt="Markup 2020-11-23 at 12 08 16" src="https://user-images.githubusercontent.com/1519466/99920257-259fda00-2d87-11eb-828f-090f2db639de.png">

**Comment by klimeryk** [comment]
TIL that there's a `.cpa` TLD: http://nic.cpa/

I had troubles finding info on it on Wikipedia. GoDaddy does not support it either, it seems. But if it's indeed a valid TLD, it should be a simple matter of running one script on our side. I can take care of that quickly.

**Comment by klimeryk** [comment]
Patch ready: D53211-code. Will merge tomorrow, as our test environment is currently in maintenance :)

**Comment by klimeryk** [comment]
Backend patch merged, should be resolved 🎉
