### ISSUE TITLE
Resizing column of Media & Text not recognized as undoable action

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#47685]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/pages/
2. Add new post.
3. Add Media & Text block.
4. In the Media area, upload or select an existing image.
5. Grab the small blue dot located at the divider in the middle.
6. Drag in any direction.
7. On top left of the editor window, choose Undo or hit CMD+Z/CTRL+Z.

#### What I expected
Resizing of column is undoable.

#### What happened instead
Undo does not apply to the resize action.

#### Browser / OS version
Browser: Firefox 85.0a1 (2020-11-23) (64-bit), Safari Version 14.0.1 (15610.2.11.51.10, 15610)
OS: macOS 10.15.7 19H2

#### Screenshot / Video

https://user-images.githubusercontent.com/6549265/106532731-93faca00-64a5-11eb-97ef-c26751949c63.mov

#### Context / Source
Context: exploratory testing of Media & Text block. Issue found via #manual-testing.

**Comment by worldomonation** [comment]
Still reproducible.

Replaced the link to video showing the issue being reproduced.

**Comment by inaikem** [comment]
Triage: confirmed as also present in WPorg sites.

Closing in favour of: https://github.com/WordPress/gutenberg/issues/24199
