### ISSUE TITLE
Nested Media & Text block ignores user action to display media on right

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#47684]
#### Steps to reproduce

1. Starting at URL: Starting at URL: https://wordpress.com/pages/
2. Add new post.
3. Add Media & Text block.
4. On the toolbar, click on the button `Show media on right`.
5. In the `Content` area of the parent block, remove the existing `Paragraph` block.
6. Add Media & Text block in the `Content` area (nested blocks).
7. On the toolbar for the nested Media & Text block, click on the button `Show media on right`.

#### What I expected
Nested Media & Text block switches media to show on the right side.

#### What happened instead
Nested Media & Text block ignores user action.

#### Browser / OS version
Browser: Firefox 84.0a1 (2020-11-12) (64-bit)
OS: macOS 10.15.7 19H2

#### Screenshot / Video
Hosted on my Sync vault due to GitHub not supporting video:
https://ln2.sync.com/dl/6340a39c0/2bntstti-tgbiy946-kxwg9b9y-bjkmaxbd

#### Context / Source
Context: exploratory testing of Media & Text block. Issue found via #manual-testing.

**Comment by worldomonation** [comment]
Still reproducible as of this date.

Video attached:

https://user-images.githubusercontent.com/6549265/106531377-f3a3a600-64a2-11eb-9ef2-887fe478b9e9.mov

**Comment by inaikem** [comment]
Triage: I was able to reproduce on WPcom and self-hosted sites. In addition: 

- With the parent block set to `Show media on right`, a new nested Media & Text block aligns text on the left and media on the right by default. Changing alignment options does nothing.
- If the parent block is set to `Show media on left`, a new nested Media & Text block aligns text on the right and media on the left (as expected). Changing alignment options works as expected.

Closed and recreated in `WordPress/Gutenberg`: WordPress/gutenberg#28714
