### ISSUE TITLE
Converting Table block within a Group to reusable block causes Gutenberg editor to crash

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#47697]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/posts
2. Add new post.
3. Add Group block.
4. Add Table block with any number of rows and columns within the Group block.
5. Save draft.
6. Return to Posts management page.
7. Reopen the draft.
8. Click on a table cell to bring up the toolbar.
9. Click on the kebab menu.
10. Click on `Add to Reusable block`.

#### What I expected
Table is converted into a reusable block.

#### What happened instead
Gutenberg editor crashes.

#### Browser / OS version
Browser: Firefox 85.0a1 (2020-11-23) (64-bit), Safari Version 14.0.1 (15610.2.11.51.10, 15610)
OS: macOS 10.15.7 19H2

#### Screenshot / Video
Screen capture is on my Sync vault:
https://ln2.sync.com/dl/672f59f10/ig49cuny-ymxsmne9-srxtatbi-nfxcbu2s

#### Context / Source
Context: exploratory testing of Media & Text block. Issue found via #manual-testing.

The critical path that leads to this crash are:
- Table within Group
- First action upon opening page is to convert to a reusable block

**Comment by cathymcbride** [comment]
@worldomonation Does the copy error button provide anything?

**Comment by sirreal** [comment]
Thanks for the report, very clear steps to reproduce.

I've just followed the testing steps on a new site with Gutenberg 9.4.1 (no other special setup) and am able to reproduce the issue. This appears to be a Gutenberg bug and we'll need to create an issue in the [Gutenberg repository](https://github.com/WordPress/gutenberg).

**Comment by cathymcbride** [comment]
Opened in Gutenberg repo: https://github.com/WordPress/gutenberg/issues/27243. Closing this one in favor of that one.
