### ISSUE TITLE
Labels for Justify and Underline in formatting options dropdown are not aligned with other items

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#47695]
#### Steps to reproduce

1. Starting at URL: Starting at URL: https://wordpress.com/pages/
2. Add new post.
3. Add a new Paragraph block.
4. Type some text.
5. On the toolbar, click on dropdown menu.

#### What I expected
Labels for Justify and Underline formatting options are aligned with other options in dropdown menu.

#### What happened instead
Labels for Justify and Underline are out of alignment in comparison to other labels in the dropdown menu.

#### Browser / OS version
Browser: Firefox 85.0a1 (2020-11-23) (64-bit), Safari Version 14.0.1 (15610.2.11.51.10, 15610)
OS: macOS 10.15.7 19H2

#### Screenshot / Video
![Screen Shot 2020-11-23 at 21 48 09](https://user-images.githubusercontent.com/6549265/100054036-20b64700-2dd6-11eb-9dc1-f7aae5354221.png)

#### Context / Source
Context: exploratory testing of Media & Text block. Issue found via #manual-testing.

**Comment by david-szabo97** [comment]
Fix PR: 27461-gh-WordPress/gutenberg

**Comment by cathymcbride** [comment]
Should be fixed in Gutenberg 9.9

**Comment by Addison-Stavlo** [comment]
Closing as the fix seems to be live on dotcom.

![Screen Shot 2021-02-15 at 3 55 53 PM](https://user-images.githubusercontent.com/28742426/107992300-66824600-6fa6-11eb-969f-fe1ccefc80ad.png)
