### ISSUE TITLE
Facebook and Twitter blocks behaves as a Paragraph block with links in Gutenberg editor

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#47694]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/pages/
2. Add new post.
3. Add Soundcloud block.
4. Paste a Soundcloud link eg. https://soundcloud.com/astateoftrance/shogun-zanarkand-venom-one-remix-a-state-of-trance-754-out-now
5. Click `Embed`

#### What I expected
Block turns to a rich, interactive block that previews how the block will appear in published post.

#### What happened instead
Block turns into a Paragraph block. 

#### Browser / OS version
Browser: Firefox 85.0a1 (2020-11-23) (64-bit), Safari Version 14.0.1 (15610.2.11.51.10, 15610)
OS: macOS 10.15.7 19H2

#### Screenshot / Video
Screenshot:
![Screen Shot 2021-01-22 at 15 13 24](https://user-images.githubusercontent.com/6549265/105558823-669f6680-5cc4-11eb-9854-0a5011793566.png)
Link: https://teachersassociationofbc.wordpress.com/2021/01/22/twitter/

In the example above, Soundcloud block is functioning as expected.

#### Context / Source
Context: exploratory testing of Media & Text block. Issue found via #manual-testing.

**Comment by cathymcbride** [comment]
@worldomonation I'm not reproing. Is there anything in the console?

**Comment by worldomonation** [comment]
> @worldomonation I'm not reproing. Is there anything in the console?

I was able to reproduce on both new posts and existing posts. Theme I selected is `Leven`, not sure if that has anything to do with it.

There isn't much in the console, but I was able to retrieve this error that appeared several times:
(Firefox 85.0a1)
```
code: "rest_post_invalid_id"
data: {…}
​status: 404
​​<prototype>: Object { … }
​message: "Invalid post ID."
​<prototype>: {…}
​​__defineGetter__: function __defineGetter__()
​​__defineSetter__: function __defineSetter__()
​​__lookupGetter__: function __lookupGetter__()
​​__lookupSetter__: function __lookupSetter__()
​​__proto__: 
​​constructor: function Object()
​​hasOwnProperty: function hasOwnProperty()
​​isPrototypeOf: function isPrototypeOf()
​​propertyIsEnumerable: function propertyIsEnumerable()
​​toLocaleString: function toLocaleString()
​​toString: function toString()
​​valueOf: function valueOf()
​​<get __proto__()>: function __proto__()
​​<set __proto__()>: __proto__()
```

**Comment by cathymcbride** [comment]
Hmm...I'm not reproing with Leven or in firefox. @bsessions85 can you see if you can repro this?

**Comment by worldomonation** [comment]
I will try to isolate the issue some more as well as review the steps to make sure I haven't missed anything.

**Comment by bsessions85** [comment]
No I can repro either. I tried production and staging just to be sure.

**Comment by bsessions85** [comment]
I just noticed that I am using FF 83 though, could be an issue with central version?

**Comment by worldomonation** [comment]
Is there any possibility that my instance of the Wordpress site is the source of the problem? I mention this because the Embed block type (which I understand Soundcloud block type inherits from) exhibits the same problem with Soundcloud links.

As a tangent, Spotify links also behave in a similar manner for me.

I've attached a screen recording to show what I am doing: https://ln2.sync.com/dl/65bc91df0/cnmdycww-xmfpfdhk-ypahstty-5gziftaq

With that said, if no one else can reproduce this issue, I think it might be worthwhile to close it for the time being?

**Comment by bsessions85** [comment]
> Is there any possibility that my instance of the Wordpress site is the source of the problem?

If you're on a basic WordPress.com site, which is a minimal site with no plugins that you are using directly from WordPress.com then you are on the same version of everything that I am looking at. There are other possibilities for differences, but those would mean you either have your own site or you're using a paid WordPress.com site.

Leave this open for now.  We can dig in some more and see if we can't repro.

**Comment by worldomonation** [comment]
Updated the title to reflect that multiple media-related blocks are exhibiting this behavior as observed in the user scenario walkthrough today.

Re-tested and attached an updated screenshot showing the behavior of problematic blocks.

**Comment by worldomonation** [comment]
Possibly related to #27701 which is a long-standing issue.

Closing in favor of the existing issue.
