### ISSUE TITLE
Editor Welcome: Content-as-Tutorial

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#47693]
Let’s educate new users with page filled with block content that explains how blocks are used. The user can read and edit and experiment with existing educational content and then delete the page.

The page should be created for sites for new signups.

Tasks:

- [ ] Create a page based on the design in a WordPress.com design starter site. dotcompatterns for example
- [ ] Confirm with design where we're going to expose this to the user, e.g., last slide of welcome tour via a CTA button
- [ ] Confirm how we're going to create the page, e.g., on the fly from the frontend when the user clicks on a CTA button

Design: p9Jlb4-1ZJ-p2
Project thread: pbAok1-1I8-p2
Spec: pbAok1-1Gz-p2

**Comment by ramonjd** [comment]
Placing on backlog for now. 

There's a lot to discuss in terms of design and functionality.

Also, we can focus on larger projects right now.

See: pbAok1-1I8-p2#comment-3904
