### ISSUE TITLE
When More button within Share This area is clicked it doesn't open More options set

### ISSUE THREAD

**Issue by susanjanec** [Automattic/wp-calypso#47705]
#### Steps to reproduce

1. Starting at URL: Go to Tools > Marketing > Sharing buttons and add some More button options
2. When you go to a page or post with the More button at the bottom and click on the button, it will take you to the top of the page instead of showing the button options.

#### What I expected

Clicking on the More button will open the more options added

#### What happened instead

Took me to the top of the page

#### Screenshot / Video

https://d.pr/i/M8sxh2

#### Context / Source

#user-report in 3513734-zen

**Comment by sgomes** [comment]
This may be related to a dotcom change I pushed yesterday. Investigating.

**Comment by cathymcbride** [comment]
removing from the janitor board, since it's related to recent changes. If it needs to go back on, let me know!

**Comment by sgomes** [comment]
Fix available for review at D53259-code.

**Comment by sgomes** [comment]
The fix is now in production. Closing bug.
