### ISSUE TITLE
Desktop macOS App: Create a logo with Looka” link leads to “fiverr”

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#47719]
#### Steps to reproduce

1. Head over to the My Home page
2. Under "Quick links" click on "Create a logo with Looka"

#### What I expected

To go to the Looka page

#### What happened instead

Was redirected to fiverr which I understand is our new logos partner

#### Browser / OS version

macOS Big Sur 11.0.1 (20B29)

WordPress.com Desktop app 6.4.0 (although I had installed the 6.5.0-beta1 from a .dmg file—don't know when it switched 🤔)

#### Context / Source

#manual-testing

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

This issue is being closed due to an upcoming revamp of the WPCOM desktop app.
If this issue should remain open, please feel free to re-open this bug.
