### ISSUE TITLE
Desktop macOS App: White screen when clicking on “Create account” after failed log in

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#47718]
#### Steps to reproduce

1. Try to sign in with a WordPress.com account that has 2FA enabled
2. Don’t enter the SMS code
3. Click on “Create account”

#### What I expected

To be able to create a new account

#### What happened instead

Got a blank screen

#### Browser / OS version

macOS Big Sur 11.0.1 (20B29)

WordPress.com Desktop app 6.4.0 (although I had installed the 6.5.0-beta1 from a .dmg file—don't know when it switched 🤔)

#### Screenshot / Video

![screen-capture-on-2020-11-24-at-14-39-59](https://user-images.githubusercontent.com/3696121/100155372-29aa2580-2e75-11eb-929c-f975c0e2d872.gif)

#### Context / Source

#manual-testing

**Comment by nsakaimbo** [comment]
Thanks for the report, @AtrumGeost! To clarify:

> Try to sign in with a WordPress.com account that has 2FA enabled

I'm not 100% clear what the issue is here (and the GIF is a little too fast to make out clearly). You're clicking "Create Account" but entering credentials for an _existing_ account with 2FA enabled (instead of signing in)?

Perhaps I'm missing something, but is this something we would expect a regular user to do? Seems like an edge case that's triggered intentionally.

**Comment by AtrumGeost** [comment]
Hi @nsakaimbo !

I apologize for the gif 😅  I recorded a video here:

https://d.pr/v/aYIP4b/ddrNtWkpX9

Basically, you'll notice:

- I try to log in with an existing WordPress.com account that has 2FA enabled, and I fail the verification on purpose
- Then I change my mind and don't want to log in anymore, but create a brand new account, so I click on the Create Account button and get a blank screen

>You're clicking "Create Account" but entering credentials for an existing account with 2FA enabled (instead of signing in)?

Not exactly; I first try to log in to an existing account, I fail, so I try to create a new account.

>is this something we would expect a regular user to do?

Not 100% sure since the best would always be to try to recover an account. But a user in a hurry might try that 🤔

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

This issue is being closed due to an upcoming revamp of the WPCOM desktop app.
If this issue should remain open, please feel free to re-open this bug.

**Comment by edwinho89** [comment]
4092852-zd-woothemes

OS: catalina 10.15.7
Reported user had similar issue, but reinstalled 6.15.0 fixed it (did not get version before reinstalling)
