### ISSUE TITLE
[Improvement] Desktop macOS App: Add "opens in a new tab/window" icon to "Quick links" on AT sites

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#47720]
#### Steps to reproduce

1. Go to the "My Home" section on an AT site
2. Click on the "Edit menus" and "Customize theme" options

#### What I expected

For the links to open inside the app as it happens with simple sites

#### What happened instead

Didn't expect the links to open outside the app. It would be nice to set expectations for users on AT sites on links that open outside the app with this icon:

![screen-shot-2020-11-24-at-14 54 37](https://user-images.githubusercontent.com/3696121/100156526-15672800-2e77-11eb-9b5d-a59ea2a714fa.png)

#### Browser / OS version

macOS Big Sur 11.0.1 (20B29)

WordPress.com Desktop app 6.4.0 (although I had installed the 6.5.0-beta1 from a .dmg file—don't know when it switched 🤔)

#### Context / Source

#manual-testing

**Comment by nsakaimbo** [comment]
At the moment a lot of features for AT sites simply don't "just work." Out of necessity, some AT features have to be accessed outside of the app. However I agree this is really jarring and I really like the idea of an "opens externally" icon to give users a better hint of expected behavior.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

The issue described by the reproduction steps still occur at this time, as expected.
Given the 'pod work' session in effect, is this something that may benefit from prioritization? 
If there is no plan to scope out work for this issue at this time, I am proposing to have this closed with the label `Closed - Won't Fix` at this time.

**Comment by nsakaimbo** [comment]
Hi, @worldomonation - thanks for checking in. Just a heads up that we're planning on releasing a complete overhaul of the application in a few weeks (currently in internal testing) that addresses this and myriad of other issues. I think labeling this as `Closed - Won't Fix` is appropriate.

**Comment by worldomonation** [comment]
> we're planning on releasing a complete overhaul of the application in a few weeks

That's excellent to hear, exciting times!

I suppose then, could it make sense to close out many other WordPress.com Desktop app-related issues as well?

**Comment by nsakaimbo** [comment]
> I suppose then, could it make sense to close out many other WordPress.com Desktop app-related issues as well?

Yep - we expect to close the majority - if not all - existing issues. 😄 It's a massively improved experience and we're looking forward to getting it in the hands of our users.

**Comment by worldomonation** [comment]
That's awesome! I look forward to seeing the revamped app :)

In the meantime, I will close this issue with the Won't Fix label. Thanks for following up!
