### ISSUE TITLE
Site privacy: Site set to public in Calypso but still stuck on private, visitors cannot see images on site

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#47729]
Site settings show that site is set to Public, but non-logged in users cannot see images on the site.
Blog RC shows that site is still Private. 
Setting site to Private and then Public again fixes the issue.

#### Context / Source

Reports of this happening here:

#3508646-zen
#3513624-zen
#3515236-zen

**Comment by eduardozulian** [comment]
More reports coming from pbEMJv-lb-p2

* 3488629-zen
*  .3505048-zen
* 3511913-zen
* 3497859-zen

All the sites I checked so far had two things in common:

1. A custom domain
2. < 1 month old

**Comment by kristenzuck** [comment]
Found one more at [3507957-zen](3507957-zd-woothemes), but not finding many more very easily. It isn't being categorized very consistently reviewing instances found so far. Reviewing what I have, it doesn't look like this is occurring too frequently yet, but given it's new customers they might not have realized it yet and we'll see more contacts soon.

**Comment by simison** [comment]
cc @alshakero @andrewserong

**Comment by ivan-ottinger** [comment]
Another report here: 3520571-zd-woothemes / 25892988-hc. When the user set the site Public again, the images started loading again.

**Comment by ramonjd** [comment]
Reported to systems here pMz3w-chP-p2

**Comment by andrewserong** [comment]
I spent some more time trying to reproduce this today, to no avail.

If anyone who sees this encounters another one of these, before fixing the site, are you able to check the current option values for the site, for the following options:

* `blog_public`
* `wpcom_coming_soon`
* `wpcom_public_coming_soon`

You can get these via running this from the CLI:

```
wp option get blog_public --url=mysite.domain.com
```

Or from the `network/site-info` page for the site, under Settings.

I'm not sure if this info will help on its own, but I'm curious to know what the site option values are like in the state where these sites are stuck in-between private and public. Very strange, indeed!

**Comment by andrewserong** [comment]
I think I've managed to get to the bottom of how this is happening. There is an unfortunate and buggy launch "flow" triggered by the launch banner in the site preview, and this particular code path is only executed for sites that have a domain subscription and are not on the free plan (more context p1606454120184100-slack-C013QHLF28Y).

The solution is to pull this bit of code out, and direct all users to the normal launch flow. I'm nearly at the end of the week, so likely won't get time to finish it off before the weekend, but I can finish it off on Monday if no-one beats me to it.

**Comment by andrewserong** [comment]
Work in progress in D53403-code.

**Comment by andrewserong** [comment]
Update: this issue should now be resolved via D53403-code and #47856, which adds in a `launch-only` flow that is used in the launch banner on sites that have a custom domain and paid plan.

There might still be some sites in an inconsistent privacy / coming soon state from prior to these changes going live. However between the above code changes, and the launch of coming soon v2, I believe we will have covered off this bug.

I'll close off this issue now, however please re-open or ping @Automattic/ganon if you encounter this issue again on sites with custom domains and paid plans launched after December 1st 2020.
