### ISSUE TITLE
Focused Launch: selectedPlan is undefined if the site already has an associated premium plan

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47734]
#### Steps to reproduce

1. Create a new site via `/start` — keep the default domain, but purchase a premium plan
2. Go to the block editor, append `?flags=create/focused-launch-flow` to the URL and refresh the page
3. Click on the "Launch" button in the editor's header
4. Focused Launch modal appears, but the Plan label is missing

#### Screenshot / Video

![Markup 2020-11-25 at 12 21 21](https://user-images.githubusercontent.com/1083581/100221291-c1148480-2f18-11eb-940a-67fa2be2787e.png)

#### Context / Source

From a quick look, it looks like the `getSelectedPlan()` selector used to  always returns `undefined`

https://github.com/Automattic/wp-calypso/blob/377dc0ab01cb12347cbba577e99529a910472890/packages%2Flaunch%2Fsrc%2Ffocused-launch%2Fsummary%2Findex.tsx#L272

This issue may be related to [this other bug](https://github.com/Automattic/wp-calypso/pull/47601#discussion_r529772106)

**Comment by tjcafferkey** [comment]
For context, @ciampo mentioned that fixing this issue may also fix https://github.com/Automattic/wp-calypso/pull/47601#discussion_r529772106
