### ISSUE TITLE
Reader: can accidentally access Atlas Reader

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#47731]
#### Steps to reproduce

1. Paste the URL, https://wordpress.com/following/manage/ in your browser address bar - the key is the trailing `/`. If that character is left off, the issue does not occur.

#### What I expected

To be taken to the Manage Followed Sites page in the Calypso Reader

#### What happened instead

The browser opens to the Blogs I Follow page in the Atlas Reader. Refreshing the page causes My Home to load, as that's what appears at the https://wordpress.com URL now.

#### Screenshot / Video

![Blogs_I_Follow_—_WordPress_com](https://user-images.githubusercontent.com/11873759/100214931-1ea8d100-2f19-11eb-80d4-2ad49cfe4889.png)

#### Context / Source

Discovered this by accident.

**Comment by bluefuton** [comment]
Good spot @KokkieH! Coincidentally I just worked on a patch that should sort this out: D45105-code. Just waiting on review.

**Comment by bluefuton** [comment]
Now D45105-code has landed, https://wordpress.com/following/manage/ goes to a blank page rather than Atlas Reader, which is slightly better.

I'll try and fix it up so it redirects to /following/manage.

**Comment by bluefuton** [comment]
Systems made a routing change in pMz3w-ct6-p2 and https://wordpress.com/following/manage/  now redirects to https://wordpress.com/following/manage 👍
