### ISSUE TITLE
Focused Launch: Plans Grid button styles in Plan Details view

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47740]
#### Steps to reproduce

1. Create a new site via `/start` and pick a free plan
2. Go to the block editor, append `?flags=create/focused-launch-flow` to the URL, and refresh the page
3. Click on the "Launch" button in the editor's header
4. Pick a premium domain
5. Click on "View all plans" to show the Plans grid
6. Notice how the "Select [plan]" buttons differ from the design specs:
   - [ ] The disabled "Free Plan" button should not change its text color when hovered (it currently does)
   - [ ] The disabled "Free Plan" button should have an opacity of 0.5 when disabled (it's currently 0.3)
   - [ ] The disabled "Free Plan" button should have a different text color (gray 90) (it's currently different)
   - [ ] The disabled "Free Plan" button should have a strikethrough effect on its text (it currently does not)
   - [ ] The buttons' border, when visible, should have a width of `1px` (it's currently `2px`)
   - [ ] The unselected buttons should not change their text color when hovered (it currently changes to blue)

The "Selected" button is tracked separately in #47814
 
#### Screenshot / Video

Current implementation:

![image](https://user-images.githubusercontent.com/1083581/100230007-66355a00-2f25-11eb-9e06-78b857d9ff49.png)

Design Specs (figma):

![image](https://user-images.githubusercontent.com/1083581/100449767-c9a1c200-30b4-11eb-8ae0-29a4f53b7643.png)

#### Context / Source

Remember that the Plans Grid package is used in different places — namely:

  - New Onboarding
  - Focused Launch
  - Step by Step launch

Changes made to fix this issue should be tested in all of these flows

**Comment by StefanNieuwenhuis** [comment]
> The unselected buttons should change their text color to a darker shade of gray when hovered (it currently changes to blue)

@ciampo do you know which color (variable) it has to be?

**Comment by ciampo** [comment]
> @ciampo do you know which color (variable) it has to be?

@StefanNieuwenhuis I had another look at the Figma designs and I actually couldn't see a hover state — let's keep the unselected buttons without a hover state for now (I updated the issue description accordignly)

**Comment by ciampo** [comment]
Hey @ollierozdarz 👋

- Do the specs written in this issue's description look correct to you? 
- Should those changes apply to the Plans Grid only in the case of Focused Launch, or should they be applied to all instances of the Plans Grid?

**Comment by ollierozdarz** [comment]
Hey @ciampo, thanks for checking! Here are the button states (can also find this in the Launch [Figma](https://www.figma.com/file/8SZljM999DKC7tWBlONFCR/Launch-Flow-All-users?node-id=1%3A93) file which I updated):

<img width="1435" alt="Screen Shot 2020-11-27 at 3 19 17 pm" src="https://user-images.githubusercontent.com/67085494/100413883-29ec3000-30c4-11eb-8edc-9fb98e5a98a8.png">

Much like my other comment just now, I think the styles we create here should be limited to the Focused Launch flow as we don't know how they'll look/work in other older flows.
