### ISSUE TITLE
Desktop app: No option to "Check for updates"

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#47756]
I don't see an option to check for updates:

<img width="386" alt="Screen Shot on 2020-11-24 at 14-32-37" src="https://user-images.githubusercontent.com/31009008/100266786-64b56300-2f20-11eb-8593-9583def517ec.png">

This option is visible on version 6.4:

![Annotation on 2020-11-24 at 11-32-07](https://user-images.githubusercontent.com/31009008/100266832-77c83300-2f20-11eb-8a95-195b2034ae41.png)

#### Steps to reproduce

1. Click "WordPress.com" on the Mac top bar.

#### What I expected
To see an option to check for updates.

#### Browser / OS version
Version 6.0.0. Mac desktop.
in Big Sur MacOS 11.0.1 (20B29)

#### Context / Source
#dogfooding

**Comment by nsakaimbo** [comment]
Thanks for the report, @davipontesblog! The manual "Check for Updates" option was introduced in v6.1.0 of the app, so it makes sense that you wouldn't see it in v6.0.0. Backporting features to older versions isn't possible, and therefore we would consider this feature request has been addressed. 

Regarding v6.0.0 specifically - there was a bug introduced that broke the auto-updater in that version (which affected a subset of our existing users). We reached out via email to users stuck on 6.0.0 and encouraged them to download the latest version at the [WordPress Desktop landing page](P7jrAc-3-p2).
