### ISSUE TITLE
Desktop app: "Add new site" takes me to the legacy new site creation flow

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#47757]
- "Add new site" takes me to the legacy new site creation flow, not our new onboarding. I believe that for existing users, we should be taking them to the new flow.

<img width="1238" alt="Screen Shot on 2020-11-24 at 15-01-06" src="https://user-images.githubusercontent.com/31009008/100267054-cf669e80-2f20-11eb-9ef6-02cdaebd2478.png">

#### Steps to reproduce

1. Starting at My Site
2. Click "Switch Site"
3. Click "Add new site"

#### What I expected
To see the new onboarding flow.

#### What happened instead
I am presented with our legacy new-site-creation flow.

#### Browser / OS version
Version 6.4 Desktop, MacOS

#### Context / Source
#dogfooding

**Comment by andrewserong** [comment]
I think the desktop app v6.4 pre-dates rolling out the A/B test to direct existing users to the new site creation flow. It's possible that it might be included in 6.5.0 (p5T066-1DK-p2), but I haven't tested this. Certainly, once the feature lands properly (is no longer behind an A/B test), this should land in the following desktop release after that.

I'll move this issue to Fixed Elsewhere in the Create focus board, so we can double-check when the flow has graduated from an A/B test, and the subsequent desktop app release has gone out.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I tested this on the WordPress.com 6.14.0 app running on macOS Big Sur 11.3.1 (20E241).

Clicking on the `Add Site` from the sidebar launched a new browser tab with the new Gutenboarding flow.

As I had not been able to reproduce this issue, I am applying the label `Closed - Not Reproducible`.
If this issue should remain open, please feel free to re-open this bug.
