### ISSUE TITLE
Focused Launch: show generic loading placeholder until all data has loaded

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47760]
Asynchronous data loading in the Focused Launch flow causes Layout Shift. This becomes evident when the site has associated a premium domain or paid plan

![Screen Recording 2020-11-25 at 18 56 12](https://user-images.githubusercontent.com/1083581/100270728-c72a5580-2f58-11eb-9be5-a9e4b4ea116a.gif)
___

💡 **Tips for improvement:** 

- We're [currently getting the site data when rendering the Launch button inside the editor](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts#L58), so it should be already available by the time the Focused launch modal is opened.
- For when a user leaves the flow and returns, we could persist this type of data (having a purchased domain / plan / domain & plan) in Launch data-store so we could show directly the correct layout, instead of waiting for the site data API call resolve.

___

**Alternative:**

As mentioned in https://github.com/Automattic/wp-calypso/issues/47761#issuecomment-734002772 we could hide the main content (everything under the page heading and subheading) to prevent layout shifting.

This option would involve showing a generic placeholder UI until all data has finished loading:

![image](https://user-images.githubusercontent.com/1083581/100268902-04d9af00-2f56-11eb-8126-f1cb217a36d8.png)

**Comment by youbrokesomething** [comment]
The focused launch is no longer active and has been replaced by other initiatives. I'm going to close this issue.
