### ISSUE TITLE
WordPress.com Embed PDFs not working on mobile

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#47768]
Hi folks!

We got a report that [our PDF Embeds](https://en.support.wordpress.com/embedding-a-pdf-file/)  are not working on mobile. I ran a test here pb32ZB-dc-p2 and confirmed Google Drive and Scribd work as expected.

#### Steps to reproduce

1. Upload a PDF file (with more than one page) and insert it on a simple or AT site
2. Visit the embed file from iOS or Android

#### What I expected

For the PDF file to show and the scroll option to work

#### What happened instead

On iOS:

The first page of the PDF file shows up but it is not scrollable.

On Android:

The PDF shows up as a link.

#### Browser / OS version

Android 11.0 running Chrome

iOS 14 running Safari

#### Screenshot / Video

Test site: pb32ZB-dc-p2

![ezgif com-gif-maker](https://user-images.githubusercontent.com/3696121/100286040-0ac49580-2f40-11eb-87a7-9c3841952719.gif)

Video link: https://d.pr/v/qBmS2X/2tK6vaZgOI

#### Context / Source

#user-report

3521336-zd-woothemes

**Comment by AtrumGeost** [comment]
Just found out there's a similar report here:

https://github.com/Automattic/jetpack/issues/15473

**Comment by devNigel** [comment]
Got another report of this issue.

3520100-zen

**Comment by cathymcbride** [comment]
I think this is the same as Automattic/jetpack#15473, as you point out @AtrumGeost. And it looks like, according to that bug, that the Android behavior is correct. I'm going to close this one in favor of that one, as it has someone assigned to it already.
