### ISSUE TITLE
Focused Launch: avoid layout shift while data is loading

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47761]
Asynchronous data loading in the Focused Launch flow causes Layout Shift. This becomes evident when the site has associated a premium domain or paid plan

![Screen Recording 2020-11-25 at 18 56 12](https://user-images.githubusercontent.com/1083581/100270728-c72a5580-2f58-11eb-9be5-a9e4b4ea116a.gif)

Although a potential (sub-optimal) solution is described in #47760, ideally we should look at a better way of solving this problem.

@ollierozdarz , do you have any ideas on how we could improve this?

**Comment by ollierozdarz** [comment]
@ciampo there's probably not a lot that can be done aside from possibly fixing the height of some of the main component areas to reduce the shifting. One option could also be to completely remove the content when loading (everything under the page heading and subheading), although that still wouldn't be ideal. 

As an aside, I noticed in the above screen there are a few inconsistencies still to the designs (mobile value propositions are being shown here, indented value prop check marks seem to be far over to the right, etc). I'm just assuming these are still small tweaks to be made? 🙂

**Comment by ciampo** [comment]
> @ciampo there's probably not a lot that can be done aside from possibly fixing the height of some of the main component areas to reduce the shifting. One option could also be to completely remove the content when loading (everything under the page heading and subheading), although that still wouldn't be ideal.

I see, makes sense (cc @razvanpapadopol )

> As an aside, I noticed in the above screen there are a few inconsistencies still to the designs (mobile value propositions are being shown here, indented value prop check marks seem to be far over to the right, etc). I'm just assuming these are still small tweaks to be made? 🙂

Thank you for your keen eye! At the moment we're focusing on implementing the last bits of functionality, so it's normal if there are discrepancies with the design. Having said that, we'll definitely need your detailed feedback soon, so that we can iron out all these inconsistencies!

**Comment by ollierozdarz** [comment]
No worries, @ciampo. I knew it'd be the case just thought I'd mention it 🙂

**Comment by razvanpapadopol** [comment]
Closing as the question was answered. We'll continue fixing this in #47760
