### ISSUE TITLE
Move PageControl componenent into own package

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#47778]
Move GB Guide component's [PageControl](https://github.com/WordPress/gutenberg/blob/4bbfbc13603d28fcc45368c529954164bf8581de/packages/components/src/guide/page-control.js#L16) into it's own package as it is a handy component on its own.

See use case: https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/pagination.js#L6-L10

Mentioned in: https://github.com/Automattic/wp-calypso/pull/47354/files#r526591146

(I am putting this issue in this calypso repo and not GB to list it in the Ganon Project page.)

**Comment by razvanpapadopol** [comment]
This issue continues to be valid since we're using the Welcome tour in production and [a copy of PageControl is still hardcoded](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/pagination.js#L6-L10).

**Comment by annezazu** [comment]
Closing this out as it seems to be a tracking issue for a task that needed to be done years ago rather than something specific to Core :) Let me know if that's wrong or just reopen.
