### ISSUE TITLE
Focused Launch: selected popular plan could be rendered twice

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47789]
Because of the async nature of getting `plans` data, `defaultPaidPlan` can be `undefined` when evaluated in https://github.com/Automattic/wp-calypso/blob/trunk/packages/launch/src/focused-launch/summary/index.tsx#L297 and if the select plan is matching the `defaultPaidPlan`, it gets rendered twice.

<img width="597" alt="Screenshot 2020-11-26 at 12 19 29" src="https://user-images.githubusercontent.com/14192054/100339264-529bf900-2fe2-11eb-9fe6-75b32fca62e9.png">

While fixing this, let's try to solve https://github.com/Automattic/wp-calypso/issues/47544 in a declarative way. `useEffect` should be used mainly for handling side effects.

**Comment by StefanNieuwenhuis** [comment]
@razvanpapadopol Can you please provide more details on how to reproduce this behavior?

**Comment by razvanpapadopol** [comment]
This issue can be reproduced again after https://github.com/Automattic/wp-calypso/pull/48551
