### ISSUE TITLE
Editor: Jetpack sidebar not visible when Gutenberg 9.4.1 is active

### ISSUE THREAD

**Issue by nielslange** [Automattic/wp-calypso#47780]
#### Steps to reproduce

1. Create an atomic site on WordPress.com
2. Ensure that Gutenberg 9.4.1 is active
3. Create a new page or post

#### What I expected

The Jetpack icon is visible in the upper-right corner.

<img width="453" alt="Screenshot 2020-11-26 at 12 59 18" src="https://user-images.githubusercontent.com/3323310/100313420-32bb0400-2fe7-11eb-9356-74a40359b4ef.png">

#### What happened instead

The Jetpack icon is not visible in the upper-right corner.

<img width="401" alt="Screenshot 2020-11-26 at 13 00 02" src="https://user-images.githubusercontent.com/3323310/100313482-4e260f00-2fe7-11eb-8471-7e1e357f2380.png">

#### Context / Source

- 22026086-hc

**Comment by inaikem** [comment]
Triage: closed as no longer relevant.
