### ISSUE TITLE
Editor Checkout Modal: TypeScript errors

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47798]
In `client/blocks/editor-checkout-modal/index.tsx`:

- TypeScript error on the `productAliasFromUrl` prop: `Type 'string | null' is not assignable to type 'string | undefined'`
   - This could be fixed by removing `|| null` from [this line](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/editor-checkout-modal/index.tsx#L83)

- TypeScript error on the `connect` function at the bottom of the file: `Types of property 'defaultProps' are incompatible. Type '{ isOpen: boolean; onClose: () => null; cartData: {}; }' is not assignable to type 'undefined'`
   - This error seems to be related to the fact that react's `defaultProps` are used together with TypeScript `Props` defs. A better approach may be to give default values to the props directly in the [component's function arguments](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/editor-checkout-modal/index.tsx#L48)

**Comment by razvanpapadopol** [comment]
Fixed in #48452
