### ISSUE TITLE
Focused launch: try enabling the flow in wp-admin

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47803]
### Why
Allow users to launch their sites from wp-admin (non-iframed editor).

### What
By skipping [calypsoify-iframe](**url**) and WBE entirely and checking the `site_creation_flow` option and `launch_status` using `Site` data-store directly within ET plugin, we could have the launch flow running also inside wp-admin.
Discussed also in p1606402431077600-slack-anchor-fm-integration

### Acceptance criteria
- [x] After creating a site using `/start/domains` flow, open wp-admin and go to post editor
- [x] Launch button should be displayed in top bar and clicking it should open Focused Launch flow
- [x] When completing the flow by selecting paid items, redirect to `wordpress.com/checkout` page

### Resources
- Ideas for internal testing in wp-admin using explat: pbmo2S-zB-p2

**Comment by yansern** [comment]
Looks like we can close this now. Continue the conversation in https://github.com/Automattic/wp-calypso/issues/46839 for the final A/B test.
