### ISSUE TITLE
Marketing banner: banner obscures theme info overlay controls

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#47827]
#### Steps to reproduce

1. View a site not displaying the marketing banner as a superadmin
2. In the superadmin menu, select the theme info overlay. Note the `x` top-left to dismiss the overlay
3. Now view a free site displaying the banner, and open the theme info overlay
4. The `x` is hidden behind the banner, making it impossible to dismiss the overlay (unless you know to press Escape)

#### What I expected
For the banner to be behind the overlay, and the overlay controls to be accessible.

#### Screenshot / Video

With the overlay:
![🗞_Marketing_banner_now_showing_to_logged-in_users_on_50__of_free_sites_and_on_all_themes_–_WP_com_Happy](https://user-images.githubusercontent.com/11873759/100421878-e973be80-3091-11eb-8fe1-be0b8b7a9484.png)

Without:
![🗞_Marketing_banner_now_showing_to_logged-in_users_on_50__of_free_sites_and_on_all_themes_–_WP_com_Happy](https://user-images.githubusercontent.com/11873759/100421922-fd1f2500-3091-11eb-9113-6ba6a0a09517.png)

#### Context / Source

Noticed why troubleshooting an issue on a user's site.

**Comment by KokkieH** [comment]
This is still an issue.

**Comment by mmtr** [comment]
Closing this one out, since apparently it has been fixed at some point:


https://github.com/user-attachments/assets/d23b3e25-470e-4096-9505-84e02191b11c
