### ISSUE TITLE
Theme Showcase: Storefront child themes not loading in Calypso

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#47838]
The eCommerce plan includes three Storefront child themes, but when I tested this I found they can only be activated via the Customizer or WP Admin. If one of the included child themes is activated, it does not load in Calypso.

#### Steps to reproduce

1. Starting at URL: Go to https://wordpress.com/themes/ on a site with the WordPress.com eCommerce plan
2. Search for Bookshop, Homestore, or Galleria—they do not appear
3. Go to WP Admin > Appearance > Themes to activate one of these themes
4. Go to https://wordpress.com/themes/ to see active theme

#### What I expected

I would expect to see the active theme name in Calypso on the Themes page

#### What happened instead

The theme name is greyed out and doesn't load

#### Browser / OS version

Chrome, Safari, Firefox

#### Screenshot / Video

https://d.pr/i/89NMAr

#### Context / Source

Previously reported here: https://github.com/Automattic/wc-calypso-bridge/issues/617

**Comment by annacmc** [comment]
Tested this and all three child themes ( Bookshop, Homestore, and Galleria) are showing up in the search results for me from https://wordpress.com/themes/ on a WordPress.com eCommerce plan. Closing with `[Closed] Not Reproducible` label as issue appears to be resolved now.
