### ISSUE TITLE
Focused Launch: improve UX of the paid flow

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47831]
#### Context
Launching a site by following the free flow (free domain and free plan) looks nice with the Success view showing first a loading text (let's call this "loading" state) and then when the site is launched, the text changes, and the two action buttons appear ("completed" state).
**Demo**: https://www.loom.com/share/8721d2545ba64fcbbfe4982c3528ba26

#### Paid flow issue
As mentioned in https://github.com/Automattic/wp-calypso/pull/47601#issuecomment-734750863 while testing all the paid flows (paid domain, paid plan, or both), because of the async nature of launching and adding products to cart, clicking _Launch_ button shows Success view (loading and something also completed state), and then seconds later the checkout overlay appears on top. This behavior seems weird because a user probably expects the success message right at the end which in this case would be after the checkout is completed.
**Demo:** https://cloudup.com/cpcG00ecc0A

#### Possible solutions
A. Don't show Success view with loading state and add a disabled state to Summary view
B. Show Success view for at least 2-3 seconds and only in loading state so the transition to checkout looks nice. Then when the checkout modal is opened, Succes view can switch to a "completed" state since it's now displayed under the checkout modal and not causing any visual glitch.
C. TBD

@ollierozdarz could you please guide us a bit with this one? 🙏

**Comment by ollierozdarz** [comment]
Hey @razvanpapadopol, I might be totally misinterpreting this one, but it seems like we should just show the success screen in the _paid flow_ (selecting a domain or plan which is paid via the checkout screen) **after** the checkout screen, instead of before it. A user would only be live with their new plan/domain after they pay for it anyway. 

**Suggestion:** 
Free flow: Keep as is.
Paid flow: Move "Hooray" screen after checkout.

**Comment by razvanpapadopol** [comment]
Closing this as the question has been answered. The implementation would be tracked in https://github.com/Automattic/wp-calypso/issues/48081
