### ISSUE TITLE
Settings: Some settings cannot be toggled.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#47840]
Reported @TassyWassy:

Some settings at `https://wordpress.com/settings/discussion/` cannot be toggled to new values. It may be limited to Simple sites, and may not be limited to just these comments settings.

See: p1606498184081000-slack-C03TY6J1A

**Comment by mmtr** [comment]
> See: p1606499060088300-slack-wpcom-support

@kwight That Slack thread seems unrelated to the issue described here 😕

**Comment by mmtr** [comment]
Likely this is the right one: p1606498184081000-slack-C03TY6J1A. Updated the issue summary.

**Comment by mmtr** [comment]
This is a regression introduced by https://github.com/Automattic/jetpack/pull/17820, where the already deprecated `comment_whitelist` option was removed in favor of the new `comment_previously_approved ` option. cc @jeherve 

Calypso still uses the `comment_whitelist` option: https://github.com/Automattic/wp-calypso/blob/e476e50a5159defecd1744d439ab86045248dba3/client/my-sites/site-settings/form-discussion.jsx#L454-L458

**Comment by mmtr** [comment]
I think we need to add back the `comment_whitelist` option to the site endpoint, since WP.com still uses it (the migration to `comment_previously_approved` was intentionally left out of the core merge 5.5 in D47633-code).

**Comment by mmtr** [comment]
~Fix ready for review: D53617-code.~

Just realized that we have some compatibility hacks in place that makes possible to use the new options as an alias of the legacy ones.

Due to that, I think it'd be better if we simply update Calypso to use the new names: https://github.com/Automattic/wp-calypso/pull/47954
