### ISSUE TITLE
Nav: WP Editor Icon Drawer UI Spacing #2

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#47848]
Originally created by @inaikem 

Via `p7DVsv-9Ny-p2` (thanks @jordesign!)

Regarding the WP icon drawer menu, the "Recent Pages" heading visually drowns out the "View Pages" and "View Posts" links. 

Please consider increasing the spacing here or add a clear separator between these two elements.

**Cc:** @simison and @jordesign
**Ref:**`p1606434973126800-slack-team-ganon`

**Comment by ramonjd** [comment]
![image](https://user-images.githubusercontent.com/6458278/100554876-fa1f7100-32eb-11eb-81fa-74126b7ac6fd.png)

> Needs design to see if there are any quick wins we could do.

**Comment by ramonjd** [comment]
Stale. Like toast. 🍞 

But the UI hasn't changed, so is it still relevant?

<img width="310" alt="Screen Shot 2021-08-02 at 10 46 51 am" src="https://user-images.githubusercontent.com/6458278/127790824-e3ccbff8-c7a6-4d60-8a16-a6e00e36a057.png">

**Comment by inaikem** [comment]
Personally, I still think having more space between the `< All Posts` and `Posts` items would lead to a better, less confusing user experience (the same goes for the Pages drawer #47847).
