### ISSUE TITLE
WP Editor Icon Drawer UI: Text Style Guide #3

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#47846]
Originally created by @inaikem

Via `p7DVsv-9Ny-p2` (thanks @jordesign!)

We talk about the A8c in-house style being based on [CMOS](https://www.chicagomanualofstyle.org/home.html) with Americanised spelling courtesy of MW but there's still a fair amount of inconsistency with text and labels across Calypso. 

Using the drawer menu above as an example:

View Pages = Headline style
Recent Pages = Headline style
Currently editing = Sentence style
Recently edited = Sentence style

Is there a plan to standardize this? Can I help?

**Cc:** @simison and @jordesign
**Ref:** `p1606434973126800-slack-team-ganon`

**Comment by ramonjd** [comment]
![image](https://user-images.githubusercontent.com/6458278/100554887-13282200-32ec-11eb-83ba-6331bbc76f40.png)

> let's switch to sentence case like the rest of Gutenboarding is doing for consistency.

**Comment by ramonjd** [comment]
@p-jackson pointed out that Gutenberg style guide does specific [Title Case as a preference for dashboard headings](https://github.com/Automattic/wp-calypso/pull/49506#issuecomment-770529824)

Closing for now.

**Comment by p-jackson** [comment]
I struggled to decide between "Won't Fix" and "Not an issue" labels. In the end I didn't want to say it's "not an issue", because the overall inconsistency between Calypso and Gutenberg _is_ an issue. It'd be nice if Calypso could start following core IMO.
