### ISSUE TITLE
Billing: Extra charges for upgrading a website with a multi-year renewal

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#47845]
#### Steps to reproduce

1. Starting with a free website upgrade to the Premium plan during the website creation process, or at https://wordpress.com/plans
2. Visit https://wordpress.com/me/purchases and click on your new plan, then use the "Renew Now" button to renew it for an extra year. You now have two years of the Premium plan upgrade.
3. Visit https://wordpress.com/plans and upgrade from the Premium plan to the Business plan. You'll be charged $204 (plus taxes if applicable.)
4. Now you have a website with a Business plan expiring in one year, but you've been charged for two Premium plans and a $204 Business plan pro-rated upgrade.

#### What I expected
If I had two years of Premium ($96 each) then I should only be charged $108 to upgrade to one year of the Business plan.

#### What happened instead
I paid for two years of the Premium plan ($96 year) and then was upgraded to a single year of the Business plan for an additional $204. This means I ultimately paid $396 for a single year of the Business plan, when the Business plan is $300 annually.

#### Context / Source
#user-report in 13657267-hc

**Comment by DavidRothstein** [comment]
Thanks for reporting this.  We had a similar issue tracked internally at c/eQdOAERR-tr already (and I just moved it to a more visible internal place also: pNPgK-5jB-p2).

Since it's really an internal issue with how upgrades work rather than anything involving Calypso, I'll close this so it can be tracked there instead.
