### ISSUE TITLE
Focused Launch: plan cards should not be collapsed on mobile viewports

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47859]
## What

The plans grid in the plan details view shows most of the plans collapsed:

![Screenshot 2020-11-30 at 09 56 21](https://user-images.githubusercontent.com/1083581/100597139-59d24800-32fd-11eb-8521-265693ac7342.png)

According to the design, all plans should be expanded:

<img width="375" alt="375 - condensed" src="https://user-images.githubusercontent.com/1083581/100597356-a74eb500-32fd-11eb-803d-e783920d9ac9.png">

## Acceptance Criteria:

- [ ] All plans in the Plan detail view should be expanded by default on mobile

**Comment by tjcafferkey** [comment]
Note from Ollie:

"The accordion only works well when used with the feature picker".
