### ISSUE TITLE
Allow users to add "Viewers" while in coming soon  mode

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#47857]
The Viewer role allows the assigned user to view an otherwise private site.

In Coming Soon v1, this worked in both private and coming soon modes since the two were essentially "private".

Seeing as Coming Soon v2 made the site public, users could no longer add or view their Viewers unless they switched to private mode.

Since D53164-code Viewers have permission to see the sites behind a coming soon v2 page.

And in https://github.com/Automattic/wp-calypso/pull/47666 we enabled the Viewers tab to site owners while their site is in coming soon mode.

To keep full existing functionality, we should also allow users to add Viewers while in coming soon mode.

**Comment by ramonjd** [comment]
There's also a small bug whereby the viewers tab disappears when the Invites tab is selected:

![Dec-07-2020 12-41-45](https://user-images.githubusercontent.com/6458278/101308880-07fe6480-389f-11eb-91cf-8b5e87f5400e.gif)

To reproduce, switch a simple site to Coming Soon mode, add a viewer in people management

**Comment by ramonjd** [comment]
This will also require updates to the accept-invite API endpoint, and also the invite-users MU plugin. Both these check to see if the site is private. It should also do a is public coming soon check.

D54769-code

**Comment by roo2** [comment]
Let's put this on hold for now after we found that the implementation, especially on the wpcom side (D54769-code) is quite a bit more complex than we expected. pbxlJb-CF-p2

**Comment by ramonjd** [comment]
At mentioned [above](https://github.com/Automattic/wp-calypso/issues/47857#issuecomment-763252767) we're not looking at this until there's sufficient demand.
