### ISSUE TITLE
Reader Lists: Deleting a list doesn't remove the list from the sidebar until page refresh

### ISSUE THREAD

**Issue by martinremy** [Automattic/wp-calypso#47875]
#### Steps to reproduce

1. Starting at URL: wordpress.com/read
2. Lists -> Create new list
3. Create a new empty list called 'Test List'
4. Click on settings gear for the list and delete it.
5. The list is still shown in the sidebar.
6. Force refresh the page, the list is gone from the sidebar.

Chrome 86.0.4240.198 (Official Build) (x86_64)

**Comment by bluefuton** [comment]
This is a frustrating one - I've seen it happen (once) but in the majority of cases it's removed from the sidebar. Can you reliably reproduce it on your account @martinremy?

**Comment by bluefuton** [comment]
Can't reproduce this one, so will close for now.
