### ISSUE TITLE
Onboarding: site creation progress goes from right-to-left when locale is RTL

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#47886]
The site creation progress bar in the new onboarding flow fills from right-to-left in `ar` and `he` locales.

![image](https://user-images.githubusercontent.com/1500769/100680048-9e311700-33d5-11eb-91ae-c9f49173fbfd.png)

Is this correct? It might be. This is a tracking issue to make sure we answer the question.

pbAok1-1II-p2#comment-3455

**Comment by p-jackson** [comment]
Pinging @dlind1 in the hopes that you'll know the answer, or know who will know the answer 😄

**Comment by dlind1** [comment]
@p-jackson 
I'm not a UX expert, but generally progress bars should fit with the rest of the content and having it fill from right to left for RTL UI looks correct to me. I've tested it by downloading a file in Firefox with Hebrew UI and the progress bar was RTL. [This guide](https://www.worldreadyguides.com/post/ux-best-practices-for-bi-directional-languages) also mentions that RTL progress bar is correct.

**Comment by p-jackson** [comment]
@dlind1 that guide makes sense. And I think if Firefox is showing progress rtl then I think that's a good hint that MacOS controls also go rtl. Thanks.
