### ISSUE TITLE
Onboarding: domain picker shows domain components in the wrong order in RTL locale

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#47885]
#### Steps to reproduce

1. Starting at URL: `/new/he`
2. Advance to the domain picker
3. Search for anything

#### What I expected
- The domain search should be left aligned (this is how we display domains in input boxes, see `/me/account` and `/start/domains`)
- The search results should show the domain components in the correct order

#### What happened instead
- The domain search is right aligned
- The domain results are displayed broken e.g. if I search for `mytestdomain` then the result will be `wordpress.com.mytestdomain`

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1500769/100679693-ea2f8c00-33d4-11eb-8da1-3f45d3474013.png)

#### Context / Source
pbAok1-1II-p2#comment-3455

**Comment by emilyaudela** [comment]
Can you also make sure this is resolved on the "Launch" screen after the site has been created? Also, please note some RTL issues in the domain screen here. It should be aligned in the same way as the gutenboarding flow in the screenshot above. 

<img width="1360" alt="Screen Shot 2020-12-01 at 11 40 32 AM" src="https://user-images.githubusercontent.com/36699353/100782826-375a3080-33ca-11eb-9644-bd680c16f924.png">
