### ISSUE TITLE
Focus Launch: DomainPicker bad setState call console error

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#47899]
#### Steps to reproduce

1. Create a site using `/new` and go to `/page/[UNLAUNCHED_START_SITE]/home` and open DevTools console
2. Click "Launch" to launch the Focus Launch modal.
3. Click "View all domains"
4. Observe error in the console like the screenshot below

![Screenshot 2020-12-01 at 11 20 41](https://user-images.githubusercontent.com/8639742/100734246-44c1eb80-33c7-11eb-96ab-b9174748afd4.png)

**Comment by tjcafferkey** [comment]
@alshakero did some investigating into this issue and suspected it could be related to [this function](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/domain-suggestions/resolvers.ts#L50-L83)

@alshakero is there anything worth mentioning here that you discovered?

**Comment by youbrokesomething** [comment]
The focused launch is inactive and has been replaced by other initiatives. I'm closing this issue.
