### ISSUE TITLE
"Purchases" should be renamed "Plan" - Nav Unification [Alpha]

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#47923]
#### Steps to reproduce

1. Starting at URL: My Site > Purchases.

#### What I expected

To see my purchases 

#### What happened instead

I saw the plan that the site is on.

#### Browser / OS version

All.

#### Screenshot / Video

https://d.pr/i/btvHWc > Purchases in the sidebar should be renamed "Plan" 

#### Context / Source

paYJgx-1b1-p2

**Comment by obenland** [comment]
Hi @aleone89, thanks so much for your feedback!

The update from Plan to Purchases was requested by the payments team. Please see the menu structure spreadsheet linked to from pbAPfg-Ou-p2, that lays out the new format.

**Comment by aleone89** [comment]
Hello @obenland I can't see the spreadsheet linked?

> The update from Plan to Purchases was requested by the payments team. 

I really do suspect this will lead to confusion, and should be reviewed. 

The reason why I suspect this will cause confusion is because, current protocol with refunds/cancellations is that users must go to purchases (manage purchases) > then to click on a purchase and to then cancel. 

I foresee swathes of users clicking on "purchases" on the left, expecting to see their purchases, but they're not seeing that - instead they're seeing plans.

**Comment by obenland** [comment]
@davemart-in @rralian Wondering if you had thoughts on this?

> I can't see the spreadsheet linked?

It's under Design > Menu structure.
I should have pointed to it in my original comment, my bad.

**Comment by donalirl** [comment]
I came here to report the same issue. Clicking on Purchases, I expected to see my Purchases: https://wordpress.com/me/purchases

As a side note, it could be worth considering adding Purchases to the nav sidebar in addition to plan, as the link to https://wordpress.com/me/purchases is buried in the profile section at the moment and often users don't know it exists or can't find it.

**Comment by obenland** [comment]
https://github.com/Automattic/wp-calypso/issues/48322 has a new iteration on that menu item. Let's close this one in favor of the new one.
