### ISSUE TITLE
Login: Desktop app doesn't support Social or Magic Link Login

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#47926]
#### Steps to reproduce
1. Open Desktop app
2. Attempt to login using Google

#### What I expected

A "Continue with Google" option similar to what's seen on the Calypso login:

![screen shot on 2018-09-22 at 16_51_08](https://user-images.githubusercontent.com/7596032/45921668-c2a11880-be87-11e8-99f0-4ea644e945a2.png)

#### What happened instead

No option is available on the desktop app

![screen shot on 2018-09-22 at 16_52_13](https://user-images.githubusercontent.com/7596032/45921675-e6fcf500-be87-11e8-8924-d8312e1e2a0b.png)

#### App Version / OS version

OSX v3.5.0 release (also reported on Windows app)

#### Context / Source

Reported via 1435060-zen
#user-report

**Comment by inaikem** [comment]
Sweeping feature requests for relevance. @elibud, @nsakaimbo,  @belcherj, was there any movement on this [following the message above](https://github.com/Automattic/wp-calypso/issues/47926#issuecomment-650197910)?

**Comment by belcherj** [comment]
We are working on a new version of the WordPress Desktop that will address some of these issues.

**Comment by davipontesblog** [comment]
@belcherj , @sandymcfadden does https://github.com/Automattic/wp-calypso/pull/55562 address this feature request?

**Comment by sandymcfadden** [comment]
Hey @davipontesblog that PR does address a lot of this. People will be able to log in with both Google and Apple social logins now. Magic link logins still won't work however. 

In https://github.com/Automattic/wp-calypso/pull/55212 we updated that magic link flow as well giving instructions on how to set a password on the web and use it to log in instead, while it doesn't resolve the issue it doesn't fully leave people stuck either.

**Comment by davipontesblog** [comment]
> Hey @davipontesblog that PR does address a lot of this. People will be able to log in with both Google and Apple social logins now. Magic link logins still won't work however.

Awesome! I will close this issue then and just create a new one for the Magic link portion by itself, to improve focus here.

**Comment by davipontesblog** [comment]
New issue here: https://github.com/Automattic/wp-calypso/issues/55611
