### ISSUE TITLE
Editor: Toolbar pinning issues when featured image is present

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4792]
1. Open the editor
2. Create or edit a post with a featured image
3. Scroll up and down and observe the following issues with the toolbar:
    - Visual and HTML tabs overlap the toolbar when it is pinned
    - Toolbar does not un-pin when it should

![featured-image-toolbar-pinning](https://cloud.githubusercontent.com/assets/227022/14575420/51f0fe98-0327-11e6-93a8-90d79bef0421.gif)

**Comment by aduth** [comment]
Related (duplicate?): #337, #991
