### ISSUE TITLE
Schedule Appears Instead of Publish, Regardless of Publish Time

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#47938]
#### Steps to reproduce

1. Create a new page. 
2. Add some content to it. 
3. Go to Publish, and it'll say Schedule, even if it isn't a Scheduled page. 

#### What I expected
It used to say Publish, which makes sense, if it's not a scheduled post/page.

#### What happened instead
It says Schedule now, which is confusing. 

#### Browser / OS version
All

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30731356/100799575-24e7f300-33da-11eb-96c0-0ee4ed5c8834.png)

#### Context / Source

#reallife #dogfooding #manual-testing

**Comment by ockham** [comment]
Upstream issue: https://github.com/WordPress/gutenberg/issues/27251

**Comment by david-szabo97** [comment]
Duplicate https://github.com/Automattic/wp-calypso/issues/47935

**Comment by ockham** [comment]
> Duplicate #47935

Thanks! I'll close this one.
