### ISSUE TITLE
[Premium Content Block] Issues with multiple pricing plans

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#47939]
When using the Premium Content block, and having multiple pricing/subscription plans, all Premium Content blocks default to the same plan. 

#### Steps to reproduce

1. Create a new page/post
2. Connect to Stripe
3. Add a Premium Content block, and add a new pricing plan
4. Add another Premium Content block, with a different pricing plan
5. View the page/post in a private browser window
6. Subscribing to either Premium Content block brings up the same plan pricing

#### What I expected

I expected to have multiple Premium Content blocks, each with their own pricing/subscription structure:

<img width="1062" alt="Screen Shot 2020-12-01 at 2 44 30 PM" src="https://user-images.githubusercontent.com/39252765/100800630-11418a00-33e4-11eb-8c7b-053774d2b16c.png">

<img width="810" alt="Screen Shot 2020-12-01 at 2 42 40 PM" src="https://user-images.githubusercontent.com/39252765/100800712-32a27600-33e4-11eb-8cc3-9651c6b2d417.png">

<img width="809" alt="Screen Shot 2020-12-01 at 2 42 24 PM" src="https://user-images.githubusercontent.com/39252765/100800722-3635fd00-33e4-11eb-8665-0dcd9c242733.png">

#### What happened instead

On my [test site](https://yoga.ruzek.blog/subscribe-to-my-classes/), both Subscribe buttons went to [the same URL](https://subscribe.wordpress.com/memberships/?blog=160339012&plan=173&lang=en&pid=170&redirect=https%3A%2F%2Fyoga.ruzek.blog%2Fsubscribe-to-my-classes), with the same price: 

<img width="450" alt="Screen Shot 2020-12-01 at 2 41 01 PM" src="https://user-images.githubusercontent.com/39252765/100800883-71383080-33e4-11eb-896e-b7ebf7d48123.png">

#### Context / Source

25648406-hc / 3536431-zen

**Comment by cathymcbride** [comment]
Removed from earn backlog since the view team is currently working on this.
