### ISSUE TITLE
Posts: Jetpack sites: section navigation disappears after trashing a draft

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4793]
1. View the drafts list for a Jetpack site (`/posts/drafts/:site`)
2. Trash a draft from the list
3. Note that the controls at the top of the post list disappear

![disappearing-posts-controls](https://cloud.githubusercontent.com/assets/227022/14575807/ed8e0696-0329-11e6-8d1b-c91edf4e669b.gif)

The same thing happens when restoring a draft - perhaps any action that modifies the posts list triggers the bug?

I was not able to reproduce the issue on a non-Jetpack site.

Also worth noting that post counts do not appear along the top of the list (not sure if this is intentional for Jetpack sites).

**Comment by nylen** [comment]
This just happened on a non-Jetpack site for me as well, when restoring a trashed draft:

![image](https://cloud.githubusercontent.com/assets/227022/14576117/1a9d0c48-032c-11e6-9662-d35c34b386cf.png)

**Comment by lancewillett** [comment]
I'm able to repeat (testing with stable Chrome on OS X 10.11.4) — but only with a Jetpack site. Can't reproduce with a WP.com site.

[Draft controls gone in Jetpack site after trashing](https://cloudup.com/iFAVAp7h6m9) (12s)

[Controls stay put with WP.com site](https://cloudup.com/cjqWCp14U3G) (15s)

**Comment by lancewillett** [comment]
In testing this, also came up with further UX improvements we can make — as well as a few bugs in how posts / pages refresh (or don't) after trash -- restore actions; see #5488 for notes and a video.

**Comment by lancewillett** [comment]
Re-testing this one today in Safari 10.1.2 on OS X 10.12.6 — with a Jetpack site. Fixed! No longer missing the section nav after a delete.

![draft-test](https://user-images.githubusercontent.com/66797/30038938-4f6abf46-917f-11e7-9a15-1426170ef163.gif)
