### ISSUE TITLE
Editor: "Restore post" modal appears briefly then disappears

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4795]
1. Open the editor to a new or existing post; make sure it is saved
2. Click the trash icon to trash the post; confirm the action
3. Note that the "restore this post" modal appears briefly, then you are redirected to the posts list

![editor-draft-trashing](https://cloud.githubusercontent.com/assets/227022/14576008/530a7346-032b-11e6-82a6-edc198cf0b4c.gif)

I'm also seeing some inconsistencies in how the post counts and the posts list are updated with the new post status.  Once, when editing a draft, I also saw the "Continue editing" button appear in the masterbar, then clicking on it took me back to the editor, with the "Restore post" prompt active.  I wasn't able to find clear steps to reproduce either of these conditions, though.

**Comment by aduth** [comment]
Not certain that it's related to the issue described in the original comment, but there's generally some strangeness with trashing posts, partly suspected as regression of #4371 due to our [expected behavior of navigating to all posts list via `onClose`](https://github.com/Automattic/wp-calypso/blob/6627bccc215bffaed0983dcd31c3e0a8c8cd7c6f/client/post-editor/post-editor.jsx#L614) when trashing a post. For example, navigating to the editor, selecting a draft from the drafts drawer, and trashing that draft causes me to be navigated back to a new draft (would expect to be navigated to all posts list). I think we may want to refine the `onClose` behavior by determining what would be the back link at time of mounting the editor, not relying so much on browser history.

/cc @blowery

**Comment by blowery** [comment]
> I think we may want to refine the onClose behavior by determining what would be the back link at time of mounting the editor, not relying so much on browser history.

Agreed. Browser history is just too fraught with crazy bits. The tricky part for the reader is maintaining the scroll position in the list that the user came into the editor from. Using `back` we get restoration for free. If we use a URL, that's a new navigation event and will be new territory. Might need to stash the position in the URL somehow and restore it when heading back.

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided, however, I found that I had to make a change to an existing post, save, refresh, then delete—if I do that, the restore prompt flashes then disappears after deleting a post. ([2m1s](https://cloudup.com/c-7jN8Lh7Hm))

![screen shot 2016-08-10 at wed aug 10 10 57 24 am](https://cloud.githubusercontent.com/assets/1119271/17562737/5d3f3152-5ee9-11e6-82be-1420b8c155a7.png)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com after trashing https://wordpress.com/post/design5279.wordpress.com/10037 using Firefox 48.0 on Mac OS X 10.11.5</sup>

**Comment by lancewillett** [comment]
I've come across this in my own #dogfooding posting to my WordPress.com blogs and it's unnerving because you think you need to read the dialog — but it disappears too fast to read it. Can be very frustrating!

**Comment by rachelmcr** [comment]
This was reported again by an a11n while #dogfooding (internal ref: C02DQP0FP/p1506407054000115-slack-calypso):

> while trashing a draft, a popup appears momentarily before the screen changes and that made me feel a missed something important there. Turns out it’s not that big a deal but the feeling was real.

**Comment by ianstewart** [comment]
Just noting that this issue still exists. I came across it again yesterday when blogging. (Is the dialog even needed?)

**Comment by cacheflow** [comment]
I think I have a fix for this. But just to make sure, do you want the modal to only appear for published posts?

**Comment by cacheflow** [comment]
I think I have a fix for this. But just to make sure do you want the modal to appear at all? Should you be sent back to the page with all posts after a post is deleted or should there be an undo button instead of a modal?
