### ISSUE TITLE
Launch button in editor: improve integration

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#47988]
We should use Gutenberg APIs to insert the Launch button in the editor top bar.

Last time when we tried this, the ordering of buttons wasn't possible but since [we are already altering the order](https://github.com/Automattic/wp-calypso/blob/a669343f83369e6062273e009416d874c70a3aa1/apps%2Fediting-toolkit%2Fediting-toolkit-plugin%2Feditor-gutenboarding-launch%2Findex.ts#L160-L162), this shouldn't be a blocker.

Then, if we're able to insert the button in a declarative way, we should be able to remove it as well fixing https://github.com/Automattic/wp-calypso/pull/47808#discussion_r534524397

**Comment by synora** [comment]
@razvanpapadopol this issue has gone stale. Is it still relevant or can be closed?

**Comment by razvanpapadopol** [comment]
We've just removed the Launch button from the editor in https://github.com/Automattic/wp-calypso/pull/53115
I guess it's fine to close this issue for now.
