### ISSUE TITLE
Editor: No success message after scheduling a post

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#4799]
Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Enter content
3. Schedule a post in the future
4. See that no success notice appears.

I do see, however that the primary button has changed to 'Update' and the status of the post is now 'Scheduled in 2 days':

<img width="260" alt="screen shot 2016-04-16 at 7 56 57 am" src="https://cloud.githubusercontent.com/assets/5835847/14580842/c9213a46-03a9-11e6-9406-e1247f320b66.png">

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed there's still no success notice after scheduling a post.

<img width="1280" alt="screen shot 2016-07-20 at wed jul 20 12 29 10 pm" src="https://cloud.githubusercontent.com/assets/1119271/17004679/4c2be9a2-4e93-11e6-8150-02989e4fce42.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10126 using Firefox 47.0.1 on Mac OS X 10.11.5</sup>

Noticed there's a fix pending in #5032, so I added the `[Status] Needs Review` label to give it a nudge.
