### ISSUE TITLE
Focused Launch: Domain step in Summary view estimates wrong number of domain items while loading

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47998]
## What

- Open Focused Launch modal
- Change Site Title to something else and move focus away from site title input field
- Domain step starts updating the suggestions: while this happens, the number of items in the domain steps jumps from 3 to 4, then back to 3

![DomainStepItemsJump](https://user-images.githubusercontent.com/1083581/101023106-95297c80-3572-11eb-90e3-1bc9a645978b.gif)

## Why

There must be some minor bug in how the expected number of domain items is computed

## Acceptance Criteria

- [ ] The expected number of domain items should not jump back and forth while interacting with the Summary view

## Context

[These lines of code](https://github.com/Automattic/wp-calypso/blob/trunk/packages/domain-picker/src/domain-picker/index.tsx#L237-L239) may be a good place to start

**Comment by razvanpapadopol** [comment]
> These lines of code may be a good place to start

Yes, I can confirm this was introduced with the [persistent domain](https://github.com/Automattic/wp-calypso/pull/47633) work. We should follow the pattern used for persistent selected plan and start always by showing the minimum number of items and, once loading is complete, only if the selected item is not found in the list, we add it.
