### ISSUE TITLE
Focused Launch: Refactor rendering logic for <FocusedLaunchSummaryItem/>

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#47994]
#### What?
The [plans in the summary overview](https://github.com/Automattic/wp-calypso/blob/trunk/packages/launch/src/focused-launch/summary/index.tsx#L371-L446) are rendered separately. It's a good idea to refactor this to a more declarative solution.

#### Why?
The current solution obfuscates the code. It's not DRY and it complicates the code's maintainability.
When we simplify - i.e. make it DRY-er - the code will be more maintainable. 

#### Acceptance Criteria
* [ ] All current selectable plans (`defaultPaidPlan`, `defaultFreePlan` & `onceSelectedPaidPlan`) are collected in a `Array<Plan>`
* [ ] All `<FocusedLaunchSummaryItem/>` are rendered with a `.map()` over the list

**Comment by alshakero** [comment]
I don't think issues should be put in Needs Review column.
