### ISSUE TITLE
Redirect glitch in site settings

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#48]
If you have a Jetpack site selected and you navigate to Settings -> Security, and then, if you click Switch Site -> All My Sites you get redirected to /me/security.  It may have to do with the overlap with an existing client-side redirect.

**Comment by gwwar** [comment]
@hoverduck https://wordpress.com/settings/security currently redirects to https://wordpress.com/me/security

Is the expected behavior to remain on https://wordpress.com/settings/security and to see the site selector instead?

**Comment by hoverduck** [comment]
@gwwar Yes.  In general I think it would be okay to redirect /settings/security to /me/security, but in this specific case it's a little disorienting to click Switch Site -> All My Sites and be taken to a personal account settings page.
