### ISSUE TITLE
Encounter Infinite loop in dashboard for invited users

### ISSUE THREAD

**Issue by benchilcote** [Automattic/wp-calypso#4800]
An infinite loop is encountered when a new user is invited to a site, starts an account with no site of their own, and directly loads wordpress.com/domains

#### Steps to reproduce
1. Invite new user via email from User A
2. Set up new WP account (sign up only, no site) for User B, accept invitation from User A
3. Log in to User B account and go to wordpress.com/domains directly (entering into address bar as there is no available link)
4. Sends browser into a loop between wordpress.com/domains and wordpress.com/domains/testdomain.com
5. Added domain to account and the issue stopped
6. Removed site from User B account and the issue returned

*Encountered first through 2625236-t

#### What I expected
Without a domain on this account, I expected wordpress.com/domains  to redirect back to a default dashboard page.

#### What happened instead
Infinite loop between wordpress.com/domains and wordpress.com/domains/testdomain.com

#### Browser / OS version
OSX 10.10.5  //  FF 45.0.2, Chrome 49.0.2623.112  //

**Comment by lancewillett** [comment]
Closing in favor of #2142.
