### ISSUE TITLE
Some color schemes lead to container and contrast issues

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#48009]
Some of the color schemes cause some contrast issues with (at least) the sidebar menu items:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/191598/101065707-77a0e680-3563-11eb-9b4b-9ee0cdcb6b3d.png">

<img width="274" alt="image" src="https://user-images.githubusercontent.com/191598/101065737-825b7b80-3563-11eb-87d4-964969f9da5a.png">

<img width="273" alt="image" src="https://user-images.githubusercontent.com/191598/101065764-8b4c4d00-3563-11eb-957c-a19e00a1f31a.png">

--

With the Contrast scheme, there are no borders or other defining lines for the sidebar:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/191598/101065867-af0f9300-3563-11eb-97df-6b8fe61f7649.png">

**Comment by ryelle** [comment]
I noticed this with the beta rollout - I'm using the Aquatic theme, and the unread counts are almost invisible:

![Screen Shot 2021-01-21 at 12 40 56 PM](https://user-images.githubusercontent.com/541093/105390018-96783c80-5be6-11eb-8d6b-1c49dd2d8072.png)

Then in changing my color scheme, this yellow + white is also low contrast/kind of glowing:

![Screen Shot 2021-01-21 at 12 41 17 PM](https://user-images.githubusercontent.com/541093/105390124-b14ab100-5be6-11eb-8e6c-b0193d515138.png)

In the Contrast theme, which I think was meant as an accessible high contrast theme, the active list name is too low contrast:

![Screen Shot 2021-01-21 at 12 50 29 PM](https://user-images.githubusercontent.com/541093/105390648-43eb5000-5be7-11eb-9cec-fb3b97ba5f0c.png)

Edit: adding in another - Blue scheme, the hover/focus color is fairly low contrast too:

![Screen Shot 2021-01-21 at 12 54 45 PM](https://user-images.githubusercontent.com/541093/105391323-020ed980-5be8-11eb-8e9b-7b73d0f2bc2c.png)

**Comment by getdave** [comment]
@frontdevde are you currently working on this? Only you are assigned? It would be good to understand the scope and effort involved in resolving this.

**Comment by frontdevde** [comment]
Yes, I'm on it. I prioritised helping with the Beta launch on Thursday. Have a couple of fixes already stashed though.

**Comment by frontdevde** [comment]
### List of reported issues (in order of reports)
---
#### Calypso /me/account
- [x] Fix selected state of menu items
- [x] Test in
  - [x] Classic Blue
  - [x] Contrast
  - [x] Light
  - [x] Aquatic
---
#### Contrast color scheme
- [x] Add divider to sidebar in
  - [x] Calypso (wp-calypso)
  - [x] wp-admin (Jetpack)
- [x] Test in
  - [x] Contrast
 ---
#### Calypso /read 
- [x] Fix unread count normal/hover/selected states
- [x] Fix selected state
- [x] Fix hover/focus color
- [x] Test in
  - [x] Aquatic
  - [x] Contrast
  - [x] Blue
  - [x] Sunrise
---
#### Submenu hover state
- [x] Make Calypso reflect the wp-admin hover state
  - [x] Blue
  - [x] Sunrise
- [x] Test in
  - [x] Blue
  - [x] Sunrise

**Comment by frontdevde** [comment]
All issues addressed in 
https://github.com/Automattic/wp-calypso/pull/49408
https://github.com/Automattic/jetpack/pull/18592
code-D56147
