### ISSUE TITLE
Sidebar hover state triggers unexpectedly

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#48019]
I'm basically noticing inconsistent hover states regarding "hover" submenus in the sidebar items. Sometimes, clicking through different pages, a hover menu will display on an item which I am not hovering. The hover menu is difficult to get rid of as well (see gif)

#### Steps to reproduce
This one is a bit tricky to reproduce, but if you switch between the "posts" and "pages" items several times, the issue should show up. Here are some steps:

1. click on the "posts" item in the sidebar. The posts submenu will open
2. click on the "pages" item in the sidebar. The pages submenu will open and the posts submenu will close
3. click on the "posts" item again. The posts submenu will open, the pages submenu will open, and **the pages hover state will display**

#### What I expected
The hover state should not show up when I am not hovering over the item.

#### What happened instead
The hover state shows up when I am not hovering over the item.

#### Browser / OS version
Chrome on macOS

#### Screenshot / Video

![2020-12-03 12 40 08](https://user-images.githubusercontent.com/6265975/101085983-124df500-3565-11eb-91a5-e599f85da531.gif)

**Comment by michaeldcain** [comment]
Related/Duplicate(?): #48006
