### ISSUE TITLE
Domain Cancellation: Domains Can't Be Removed from Calypso

### ISSUE THREAD

**Issue by sdixon194** [Automattic/wp-calypso#48021]
There are a few issues with cancelling domains in Calypso:

1 - When refunding a domain Automattic's back end and then going to cancel in Calypso, there's only an option to disable autorenew, and there’s no option to “remove domain," which actually cancels the domain. 
2 - If autorenew is already disabled, I don't see an option to remove the domain at all. 
3 - When I tried making a test purchase, I can select the option to cancel and refund but then I’m taken to a page that never loads, failing to cancel. 

#### Browser / OS version

Tested in latest versions of Firefox and Chrome, Mac OS. 

#### Screenshot / Video

Cancelling Domain and Refund that never loads:

![Screen Capture on 2020-12-03 at 15-11-25](https://user-images.githubusercontent.com/33553323/101085604-aaf06f00-357d-11eb-8960-045ff3788ed6.gif)

Domain that was already refunded on the back end, but there's no way to "Remove" the domain: 

![Screen Shot on 2020-12-03 at 15:41:59](https://user-images.githubusercontent.com/33553323/101085907-1b978b80-357e-11eb-8f3b-2e61e96d16a4.png)

-->

**Comment by DavidRothstein** [comment]
These should all be fixed now following the revert of a change that was deployed earlier today (see https://github.com/Automattic/wp-calypso/pull/48022).

Although for this one:

>1 - When refunding a domain Automattic's back end and then going to cancel in Calypso, there's only an option to disable autorenew, and there’s no option to “remove domain," which actually cancels the domain.

I think that's partially expected; if there is no refund available, you are required to use "Cancel Domain" (to turn off auto-renew) first -- you are not given the option to remove the domain directly.  However, the bug meant that after using "Cancel Domain", the remove option wasn't available even then, and that part is now fixed.
