### ISSUE TITLE
Store|Woo: Add Dashboard Message to Inform of Service Migration

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#48026]
**Important** Place this behind the "store-pre-sunset" feature flag (implementation tbd)

> This issue is part of a project to migrate users of the Store on WordPress.com feature ( The Woo UI in calypso ) to use the default WooCommerce experience in wp-admin instead. Further details & discussion: pbIJXs-sE-p2

This issue involves creation of a new Store dashboard banner to inform current users of the upcoming migration to using WooCommerce in wp-admin.

__Current Home Screen_
<img width="1326" alt="store-home-banner" src="https://user-images.githubusercontent.com/22080/101101824-9e6c1680-357d-11eb-8343-b0a6af927abd.png">

I'm thinking we can add a new dashboard card above the red box shown above. This way the messaging will be shown at all times regardless of if a site has any pending orders or not. It seems like adding this card to the content produced [in this method](https://github.com/Automattic/wp-calypso/blob/trunk/client/extensions/woocommerce/app/dashboard/index.js#L219-L240) would do the trick.

@pmcpinto we still need the exact copy to be shown here, but I think it would be great to also include a link to the forthcoming documentation on the differences between Store on WordPress.com and WooCommerce in wp-admin, and obviously point out the link we are going to add in the sidebar for WooCommerce.

@elizaan36 not sure if you would like to do any sort of special design treatment for this dialog, or if you are okay with us just using the calypso `<Notice />` [component](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/notice)

**Comment by pmcpinto** [comment]
> @pmcpinto we still need the exact copy to be shown here, but I think it would be great to also include a link to the forthcoming documentation on the differences between Store on WordPress.com and WooCommerce in wp-admin, and obviously point out the link we are going to add in the sidebar for WooCommerce.

Sounds good. @elizaan36 let's chat about how to structure the content banner in our next 1.1

**Comment by timmyc** [comment]
> @elizaan36 let's chat about how to structure the content banner in our next 1.1

🎉 - so we will probably need two sets of design + copy for this notice:

- The version that will be shown as part of this issue, during the sunset period.
- And another that is shown after the sunset has happened.

**Comment by elizaan36** [comment]
Here are options for both using the Calypso notice:

> The version that will be shown as part of this issue, during the sunset period.

`Store is moving to WooCommerce`
![Frame 562](https://user-images.githubusercontent.com/5121465/101406071-9b836580-389e-11eb-8aa1-72d75c865c50.png)

> And another that is shown after the sunset has happened.

`Store has moved to WooCommerce`
![Frame 642](https://user-images.githubusercontent.com/5121465/101406143-b05ff900-389e-11eb-9c2b-2c89c9f6c217.png)

**Comment by timmyc** [comment]
@elizaan36 should we allow this notice to be dismissable at all? Kind of seems like we should make this persistent across all pages during the lead-up to the service being sunset.

**Comment by elizaan36** [comment]
Yep, there's an "X" to dismiss on the right of the notice.

**Comment by becdetat** [comment]
@elizaan36 I think @timmyc 's point was that a notice like this should be persistent across all pages, so it probably shouldn't be dismissible at all. Is that correct @timmyc ?

**Comment by becdetat** [comment]
@elizaan36 what happens when clicking the More action?
![image](https://user-images.githubusercontent.com/224531/101438733-c208d580-395e-11eb-8754-948cf584a2de.png)

**Comment by timmyc** [comment]
Yes my concern with having the notice with the (x), which would allow it to be dismissed is I think we should have this be always shown on the Store pages to ensure it is seen.

The `More` link will go to the to-be-created support page specifically about the transition to using core WooCommerce pages to manage their stores.

**Comment by elizaan36** [comment]
Ok, I think if it's not dismissible in that case for the sunset period we could use the `is-warning` notice style with a link on the far right.

<img width="651" alt="Screen Shot 2020-12-08 at 6 29 01 PM" src="https://user-images.githubusercontent.com/5121465/101557766-440af580-3983-11eb-81df-478a38a33eda.png">

The non-dismissible `is-error` notice is a lot considering that there will be a decent time period to learn more.

`is-warning` during the sunset period
![Frame 643](https://user-images.githubusercontent.com/5121465/101558268-3dc94900-3984-11eb-92d6-7c8d57bfb165.png)

Then `is-error` can be shown after the sunset has happened
![Frame 644](https://user-images.githubusercontent.com/5121465/101558670-073ffe00-3985-11eb-96f2-f6e34e6b588f.png)

**Comment by becdetat** [comment]
@elizaan36

> I think if it's not dismissible in that case for the sunset period we could use the is-warning notice style with a link on the far right.

Sounds good to me.

I added a test notice to see how they look right now, they are full width as part of the content, rather than overlapping the content as you've got in your designs. I'm feeling that they might have more impact and still be less obtrusive like this:

![image](https://user-images.githubusercontent.com/224531/101559546-110d4400-3a0d-11eb-8539-6ea55b62c631.png)

**Comment by elizaan36** [comment]
Nice, even better. I think if they're not dismissible it's best to appear above the content rather than over it (in case it obstructs anything important.)

And we could include a longer message in case there's any more context we should give people here.

Maybe something like:
> Store is moving to WooCommerce so you'll have access to all the features you need in one place

**Comment by pmcpinto** [comment]
@elizaan36 @becdetat is there anything preventing us from using the area that @timmyc included in the issue description?

This is a big change for them and I think that should have some impactful and meaningful that clearly outlines the value prop of this change. The notification has several limitations and it can easily go unnoticed.

**Comment by elizaan36** [comment]
hey @pmcpinto - I wasn't super clear on whether to use the notice or design a new card entirely, so clarified with @timmyc in Slack that we want to move forward with the notice style. I could have misunderstood that we actually want both. Could be similar to the design for after sunset here: https://github.com/Automattic/wp-calypso/issues/48029#issuecomment-741403270

**Comment by timmyc** [comment]
> This is a big change for them and I think that should have some impactful and meaningful that clearly outlines the value prop of this change. The notification has several limitations and it can easily go unnoticed.

Definitely I think the notice style could result in eyes skipping over it, but for habitual users, I think it will catch their 👁️ especially if it is displayed across all pages.

**Comment by pmcpinto** [comment]
> hey @pmcpinto - I wasn't super clear on whether to use the notice or design a new card entirely, so clarified with @timmyc in Slack that we want to move forward with the notice style. I could have misunderstood that we actually want both. Could be similar to the design for after sunset here: #48029 (comment)

@elizaan36 In my opinion, the card would be better. Most people are averse to change and it would be difficult to conquer their hearts with just the notification 😃

**Comment by mattsherman** [comment]
A huge +1 to using a card over a notice. As @pmcpinto notes, this is a huge change -- letting users know about that in a little notice doesn't feel like giving the messaging the appropriate weight. And, it limits how we can present the initial message before they click-through to get more information.

**Comment by elizaan36** [comment]
I think we can do both - a notice and a card. Here's a possibility for during sunset (copy TBD)

![During sunset](https://user-images.githubusercontent.com/5121465/101814509-e346fe80-3ae3-11eb-8afe-e5f755bb56e9.png)

**Comment by timmyc** [comment]
➕ on the Card too - great idea y'all.

**Comment by mattsherman** [comment]
> I think we can do both - a notice and a card. Here's a possibility for during sunset (copy TBD)
> 
> 
> 
> ![During sunset](https://user-images.githubusercontent.com/5121465/101814509-e346fe80-3ae3-11eb-8afe-e5f755bb56e9.png)
> 
> 

It seems like unnecessary duplication on the screen. I don't think the notice really adds much, assuming the card is designed to attract sufficient attention.

I think if the notice didn't have its own call to action, I'd be more okay with it, but I still think it makes the screen look more confusing than necessary.

**Comment by pmcpinto** [comment]
> It seems like unnecessary duplication on the screen. I don't think the notice really adds much, assuming the card is designed to attract sufficient attention.

I agree with Matt. The only case where I think that the notification can be effective is to show it on the other screens, if the user hasn't visited the dashboard.

**Comment by elizaan36** [comment]
Ok, here's a new version with only the card on the Dashboard, and a notice on all other screens.

### During sunset
**Dashboard**
![During sunset - Dashboard](https://user-images.githubusercontent.com/5121465/102142613-57590d80-3e28-11eb-9ebe-ca58796e4659.png)

The text field has been expanded to include the link to support documentation.

**Non-dashboard screens**
![During sunset - non-Dashboard screens](https://user-images.githubusercontent.com/5121465/102142176-93d83980-3e27-11eb-821a-a0f8d0899530.png)

### After sunset
Dashboard landing page
![After sunset](https://user-images.githubusercontent.com/5121465/102142251-b5392580-3e27-11eb-8b61-f82f32cfca94.png)

After sunset there won't be a notice needed as all links will redirect outside of Store.

**Comment by timmyc** [comment]
Latest designs look great to me @elizaan36

**Comment by moon0326** [comment]
Thank you @elizaan36 and @timmyc. I'm gonna start working on this ticket and https://github.com/automattic/wp-calypso/issues/48029 with the latest design for now.

**Comment by pmcpinto** [comment]
@elizaan36 @claraclee 

I have a couple of questions about the copy:
- The store UI mentions "Powered by WooCommerce" in some places, so I'm wondering if the headline "Store is moving to WooCommerce" is going to confuse users. I'm thinking that maybe it could be more compelling to focus on something like "have access to all the WooCommerce features and customization".
- Same in the description
- I think that we should also be clear about when it's going to happen right in the card.

Let me know what you think. Thanks
