### ISSUE TITLE
Navigation fails with simple site using a redirect

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#48037]
#### Steps to reproduce

1. Create a simple site and then purchase the [redirect upgrade](https://wordpress.com/support/site-redirect/)
2. Visit WordPress.com
3. Use the navigation on the left to view stats/plans etc
4. You unable to view any tools

#### What I expected

Navigation should not use the redirect URL and I should be able to view items like plans and even stats for the domain.

#### What happened instead

The navigation respects the chosen redirect URL and is unable to correctly load any item. For example, I see:

https://wordpress.com/stats/day/[redirect-example.com]

When it should be:

https://wordpress.com/stats/day/site.wordpress.com

#### Browser / OS version

Chrome 87 / OSX 10.15.7

#### Screenshot / Video

![Kapture 2020-12-04 at 09 31 01](https://user-images.githubusercontent.com/411945/101140615-7b8c4180-3613-11eb-956d-2e69e23152bf.gif)

In this example, you can see that stats for the redirected site, take me to all stats, across all sites.

#### Context / Source

#manual-testing

**Comment by obenland** [comment]
Thanks so much for the report and adding an easy-to-understand gif to the ticket! We'll address it together with #48019.
