### ISSUE TITLE
Navigation in wp-admin is not styled correctly

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#48039]
#### Steps to reproduce

(uncertain)

1. Enable the navigation unification test
2. I swapped to a darker theme as the navigation looked odd with the [default colour scheme](https://github.com/Automattic/wp-calypso/issues/48010)
3. When click links to WP Admin, I appear to have a Calypsoify(ish) theme

#### What I expected

For the navigation and theme to remain consistent 

#### What happened instead

![Screenshot 2020-12-04 at 09 40 48](https://user-images.githubusercontent.com/411945/101141617-d5d9d200-3614-11eb-810c-186e01918704.png)

I am not really sure what I am seeing here, it is a WP Admin link, but the styles are completely different. A cache clear didn't seem to fix it either.

#### Browser / OS version

Chrome 87 / OSX 10.15.7

#### Screenshot / Video

Above

#### Context / Source

#manual-testing

**Comment by obenland** [comment]
These are Calypsoify styles, Manage is currently working on disabling those ahead of launching nav unification.

I don't feel super comfortable closing this ticket, particularly after all the effort you went through reporting this, but there's really nothing we can do about it until the below ticket was fixed. Thank you Scott!

See 44-gh-Automattic/dotcom-manage.
