### ISSUE TITLE
Support contact urls need better localization support

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#48033]
The `https://wordpress.com/help/contact` url will behave differently based on whether you're logged in or logged out.

Logged in it will route to a calypso endpoint and display support contact options.

Logged out it will redirect to `https://wordpress.com/support/contact`

While logged in, the `/help/contact` url will behave correctly in a non english setting displaying a translated version of the page.

While logged out, it redirects directly to the english rendered page no matter what. Additionally, if the `localizedUrl` version is used, it redirects to `/me/help` a non existent calypso route - white screens.

I would like this redirect to instead point at `https://wordpress.com/:locale/support/contact`.

As this `/support/contact` page is not currently enabled for non english support sites at `/:locale/support/contact` this may need enabling and having its options better configured per locale depending on whether we offer dedicated localized support.

This is currently blocking #47947 from applying `localizeUrl` to a `/help/contact` url in ETK.

From https://github.com/Automattic/wp-calypso/pull/47947#issuecomment-738586664:

`Logged in: https://wordpress.com/help/contact > 200` :heavy_check_mark:
`Logged out: https://wordpress.com/help/contact > 302 https://wordpress.com/support/contact/ > 200` :heavy_check_mark:
`Logged in: https://es.wordpress.com/help/contact > 302 https://wordpress.com/me/help > 404` :negative_squared_cross_mark:
`Logged out: https://es.wordpress.com/help/contact > 302 https://wordpress.com/support/ > 200` :negative_squared_cross_mark: not localized, should be `/es/support/contact` but that page doesn't exist.

To fix this we need a few different changes:

- [x] Add a `localizeUrl` rule for `/help/contact` to localize to `/help/contact/es`.
- [x] Add a calypso route for `/help/contact/:locale` to redirect to `/help/contact` if logged in. Or `/es/support/contact` if logged out.
- [x] Add localized versions of `/:locale/support/contact`. This is a special theme page that probably needs to be enabled and configured for each locale depending on whether we have localized support available or not.

**Comment by akirk** [comment]
I consider all todos addressed with #48645, can you confirm, @lsl?

**Comment by lsl** [comment]
Looks that way, thanks everyone!
