### ISSUE TITLE
Navigation cut short on sites with few posts

### ISSUE THREAD

**Issue by scottsweb** [Automattic/wp-calypso#48038]
#### Steps to reproduce

1. Create a new simple site with few posts
2. Make sure you are working on a large screen
3. View the posts section on WordPress.com
4. Notice that the navigation is incomplete

#### What I expected

To be able to see all navigation items

#### What happened instead

![Screenshot 2020-12-04 at 09 34 09](https://user-images.githubusercontent.com/411945/101141101-1a18a280-3614-11eb-87bd-a654f26f3ac9.png)

#### Browser / OS version

Chrome 87 / OSX 10.15.7

#### Context / Source

#manual-testing

**Comment by cpapazoglou** [comment]
👋  @scottsweb thanks for testing this and reporting! Since I can't reproduce it, would you mind explaining a little more about this behavior? 

- If you move from pages to posts you get the same?
- If you go to posts and refresh your page you still get it?

**Comment by scottsweb** [comment]
@cpapazoglou just tested it and also cannot see this happening any more. Tested on a few sites too so happy to close.
