### ISSUE TITLE
Wix Importer: Posts importing with too much text linked

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#48073]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/import/
2. Choose Wix
3. Enter the Wix site URL
4. Proceed with the import

#### What I expected

That the posts and pages would import with the same general formatting as they have on Wix.

#### What happened instead

It looks like anytime a link appears in a post, it starts to turn all paragraph text into links. Wix's default/demo posts don't include links, so when I tried the first time I saw no issues. Example post on my test site with Wix: https://msilberstang.wixsite.com/my-site/post/5-pizza-places-you-must-know

Once I added links to a demo post, for example: https://msilberstang.wixsite.com/my-site/post/top-5-items-under-20-i-can-not-live-without

The imported post linked a lot more text than the original at Wix. Imported post: https://firstmonthfree.wordpress.com/2020/12/06/top-5-items-under-20-i-cant-live-without/

#### Context / Source

This happened to a WordPress.com customer, reported in chat and I was able to reproduce it myself on the test sites linked above. The Wix site was created for this test and no demo content was changed except to link 2 words to Google.com in the one linked post above.

#user-report #manual-testing

**Comment by yoavf** [comment]
This should be fixed now. Thanks @msilbers for the detailed report and reproduction instructions!
