### ISSUE TITLE
Landing page: all 'Start with free' buttons should redirect to 'free' onboarding flow

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#48078]
“Start with free” buttons on marketing pages should redirect to `/start/free` (which is the `free` onboarding flow) instead of `/start`. At the moment only the "Sign up" button of the "Free" column at the bottom of [pricing table](https://wordpress.com/pricing) is redirecting as expected.

Until now we've identified 2 locations where this change needs to be implemented
- [ ] Bottom of wordpress.com
- [ ] Top of wordpress.com/pricing

#### Screenshot
<img width="1266" alt="Screenshot 2020-12-07 at 10 49 37" src="https://user-images.githubusercontent.com/14192054/101329373-feaed100-3879-11eb-875a-7dfa79365332.png">
<img width="1245" alt="Screenshot 2020-12-07 at 10 48 29" src="https://user-images.githubusercontent.com/14192054/101329404-04a4b200-387a-11eb-8810-ef9f81ede895.png">

#### Context / Source
pbxNRc-xd-p2

**Comment by yansern** [comment]
The phab patches are here:
- [DEPLOYED] D53834-code
- [DEPLOYED] D54496-code
- [NEEDS REVIEW] D54690-code

**Comment by razvanpapadopol** [comment]
I think the last piece of this task was D54728-code so we can close it now.
