### ISSUE TITLE
Focused Launch: Don't launch site when user closes checkout

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48081]
**What**

When a user selects premium options in the Focused Modal that require them to complete their purchase on the checkout, and they change their mind during the checkout process we currently launch their site anyway with a free domain, and plan.

We need to change this behavior to NOT launch their site at all should they change their mind and require them to re-select free options in the Focused Modal or complete the purchase before launching the site.

We'll also prevent any redirect to post-checkout _Thank you_ up-sell pages if the purchase happens using the checkout modal as part of the Focused Launch flow and make Success view the last step of a linear Focused Launch flow. Future up-sells may be displayed in that view.

**Why**

If a user backs out of paying for their purchase, they would expect not to have their site launched until re-selecting free options OR completing their purchase.

**Acceptance criteria**

* Should a user get presented with the checkout modal at the end of the Launch flow (by having a paid plan or custom domain selected) and then close it before completing their purchase. 
  - Their site should remain unlaunched.
  - Reopening the flow by pressing the _Launch_ button in top bar should present them with the Summary view so they can review their selected options.

* Show Success view as part of the Focused launch flow if the user is launching the site in one of these cases:
  - after selecting free plan and existing domain during launch flow
  - has already purchased items (showed as disabled during launch flow)
  - has already purchased plan / domain and the remaining selected item is free
  - after selecting paid plan and/or domain and completing purchase

* After a user completes purchase of paid items selected during Launch flow, prevent any redirect (eg: to a thank-you page)  and show Success view.

* After a successful plan purchase, when dismissing Success view and choosing to _Continue editing_, enable the newly purchased plan inside the editor (eg: premium blocks should be available).

* From wp-admin (non-iframed editor), if there is a paid plan and/or a custom domain selected, when pressing _Launch you site button_, the site will first launch and then the user will be redirected to `/checkout`.

**Context**
https://github.com/Automattic/wp-calypso/issues/47897#issuecomment-738613133

**Comment by tjcafferkey** [comment]
@ollierozdarz does this sound okay to you? Please update how you see fit.

**Comment by ollierozdarz** [comment]
This sounds great, thanks @tjcafferkey! 🙂
