### ISSUE TITLE
Footer credit upgrade nudge visually broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#48080]
Footer credit upgrade nudge has an underline in the customizer.

![image](https://user-images.githubusercontent.com/87168/101344023-84884780-388d-11eb-9eee-687e267194ab.png)

After leaving that option and saving the customizer state, the banner also disappeared. 

#### Steps to reproduce

1. Have non-business/ecommerce plan site,
2. Open customizer
3. Choose "site identity"
4. See footer credit section

**Comment by ericamQA** [comment]
Unable to reproduce - the "footer credit nudge" behaves as expected: showing up when trying to hide the footer credit and disappearing when any other option is selected. Leaving the customizer and returning doesn't impact this behavior. Closing for now.
