### ISSUE TITLE
Onboarding: Unable to select free subdomain option until after selecting a paid domain

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#48098]
#### Steps to reproduce

1. Starting at URL: `wordpress.com/new`
2. Proceed through the onboarding flow. Select no domain (e.g. the *.wordpress.com subdomain) and a free plan.
3. When you get to the site preview, click Launch.
4. You should be back on the "Choose a domain" (we already chose one, but I assume there is a reason why we ask again :) )
5. Try to select the free subdomain again.

#### What I expected
That clicking to select the free subdomain would select it.

#### What happened instead
I cannot select the free subdomain without first selecting a custom domain. Proceeding to the final launch page without making a selection renders that form uncompletable.

#### Browser / OS version
macos/chrome

#### Screenshot / Video
[Screen Recording 2020-12-07 at 3.53.07 PM.mov.zip](https://github.com/Automattic/wp-calypso/files/5655522/Screen.Recording.2020-12-07.at.3.53.07.PM.mov.zip)

#### Context / Source
#journey #dogfooding

**Comment by razvanpapadopol** [comment]
Thanks for reporting this! 🙇 
The bug has been fixed in https://github.com/Automattic/wp-calypso/pull/48100
