### ISSUE TITLE
Focused Launch: Search for domains on key press rather than on blur

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48107]
#### Steps to reproduce

1. Visit `/page/SANDBOXED_UNLAUNCHED_SITE_ID_CREATED_WITH_START.wordpress.com/home?flags=create/focused-launch-flow-calypso`. Focused Launch modal should appear
2. Enter site title
3. Observe no new domains being returned until you click outside of the site title input.

#### What I expected

* New domains to be returned on key press rather than on blur (clicking outside of the input)

#### What happened instead

* I had to click outside of the site title input before any new domain suggestions were fetched.

#### Context / Source

p58i-9Mt-p2#comment-48400

**Comment by razvanpapadopol** [comment]
As mentioned in Slack (p1607513726472600-slack-luna), the idea is to lift where we currently store the site title value from [local state](https://github.com/Automattic/wp-calypso/blob/trunkackages/launch/src/hooks/use-title.ts#L16) to Launch data-store so it can be used to update in real-time the [domainSearch](https://github.com/Automattic/wp-calypso/blob/trunkackages/launch/src/hooks/use-domain-search.ts#L20) query.
