### ISSUE TITLE
Focused Launch: Localize help URL in Summary view

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48108]
In the Summary view the "Ask a Happiness Engineer" [link is not localized](https://github.com/Automattic/wp-calypso/blob/trunk/packages/launch/src/focused-launch/summary/index.tsx#L683).

**Proposed changes**

* Use [`useLocalizeUrl` hook](https://github.com/Automattic/wp-calypso/blob/trunk/packages/i18n-utils/src/localize-url.tsx#L138) for the link

** Context **

p58i-9Mt-p2#comment-48394

**Comment by razvanpapadopol** [comment]
I don't think this is needed anymore since `wordpress.com/help` seems to always show the content translated in the locale set in the user's account.

**Comment by StefanNieuwenhuis** [comment]
I believe this is fixed in #50115 and can be closed.
