### ISSUE TITLE
Scrolling is lost when using some of the Expanded Navigation Options

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#48133]
1. Load your page and note you can scroll up and down to see all navigation options.
2. Click on Users (the same happens with Appearance). 
3. Note you can no longer scroll. You have to expand the browser page to see the options again.

#### What I expected

To be able to scroll. 

#### What happened instead

I could not scroll

#### Browser / OS version

Firefox 83.0 (64-bit)

Browser window size: 1082 x 676

#### Screenshot / Video

![Screen Capture on 2020-12-08 at 13-43-10](https://user-images.githubusercontent.com/2545184/101528332-2e82d500-395d-11eb-9cd8-1e954d539df2.gif)

We'd also love to know how you found the bug: #manual-testing

**Comment by vparkhere** [comment]
The same scrolling issue occurs with Settings > Domains and Settings > Hosting Configuration, using the Chrome Browser:

![Domains_scroll_issue](https://user-images.githubusercontent.com/11635760/101556282-5ed36f00-396f-11eb-82a1-98cd5268109c.gif)


![HostingConfiguration_scroll_issue](https://user-images.githubusercontent.com/11635760/101556002-aefe0180-396e-11eb-95cf-7da3bf85fae2.gif)

**Comment by ktyfuller604** [comment]
Also occurs on MacOS Catalina v 10.15.7/ Chrome v. Version 86.0.4240.198
