### ISSUE TITLE
Store Stats - Incorrect reporting

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#48131]
The store stats reporting section in calypso seems to not be updated with correct data for customers who rely on this functionality. Here are a couple of user reports:

https://github.com/Automattic/wp-calypso/issues/41946

3555296-zd-woothemes

<img width="1430" alt="Captura de Tela 2020-12-08 às 10 03 16" src="https://user-images.githubusercontent.com/31009008/101523939-49eae180-3957-11eb-9791-a1197c2f9a65.png">

![WhatsApp Image 2020-12-08 at 9 36 54 AM](https://user-images.githubusercontent.com/31009008/101523945-4b1c0e80-3957-11eb-927f-2e309652dd44.jpeg)

I don't have much more data other than these two reports above, but I would like to recommend we sunset this effective immediately if there are no plans to manage this functionality moving forward, and instead, link users to WP Admin > Woo > Analytics, which is a reliable source of reporting. This would be an improvement for anyone using our stats.

**Comment by synora** [comment]
As per the labels, this is related to Store. We're sunsetting Store by Feb 2021. Closing it in favor of that.
