### ISSUE TITLE
Nav Unification: Hosting Configuration screen overlay on Simple sites overlaps menus

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#48143]
#### Steps to reproduce

1. Start at the Hosting Configuration screen while in Calypso
2. On screens that are small enough to cause overlap, the overlay over the Hosting configuration page extends out onto the menus.  (Screenshot below was taken on a 1500 px browser screen width) 

#### Screenshot / Video

<img width="1529" alt="Screen Shot 2020-12-08 at 5 32 46 PM" src="https://user-images.githubusercontent.com/30205248/101551018-52a2de00-397e-11eb-80ff-f751626d9595.png">

**Comment by ktyfuller604** [comment]
This also occurs if you click on Jetpack and hover over other menus. 

Screen recording: https://d.pr/v/3b91FO

MacOS Catalina v 10.15.7/ Chrome v. Version 86.0.4240.198
