### ISSUE TITLE
Nav Unification: Cannot access WP Admin -> themes.php

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#48147]
#### Steps to reproduce

1. Go to WP Admin. 
2. Click on Themes. You are redirected to Calypso. 

I am reporting this as a bug because:
- HEs use the WP Admin -> Themes functionality to reactivate retired themes for users. 
- This functionality is also used to activate retired themes on test sites.

**Comment by cpapazoglou** [comment]
Even if the URL doesn't appear, it is and will be reachable through `[DOMAIN]/wp-admin/themes.php`. Is there a need for the customers to easily access `/wp-admin/themes.php`?

**Comment by obenland** [comment]
Would it help if we added a Themes link under "Dash" in the superadminbar?

![image](https://user-images.githubusercontent.com/1398304/103692863-442fee00-4f4d-11eb-8662-c0280639c7a6.png)

**Comment by JoshuaGoode** [comment]
For Atomic, many third-party themes include options, support buttons, and more when inspecting the theme details under Appearance > Themes.

Additionally, since we no longer force require auto-updates for themes, it's where users can toggle on/off updates for a specific theme. 

I suppose this would be partially taken care of via the opt-out discussed on https://github.com/Automattic/wp-calypso/issues/47043

Screenshot from an Atomic site's WP-Admin > Appearance > Themes > Theme Details

<img width="1460" alt="nav_unification_themes" src="https://user-images.githubusercontent.com/4887830/103957874-a9d0d580-5119-11eb-803d-66ff53b6929c.png">

**Comment by obenland** [comment]
Theme options _should_ still be accessible through the admin menu. 

However we are pretty much removing the ability to install themes from the theme directory. Unless there's an alternate way that I'm not aware of?

/cc @davemart-in

**Comment by davemart-in** [comment]
> However we are pretty much removing the ability to install themes from the theme directory.

Can you walk me through his statement @obenland? I'm not sure I follow.

**Comment by obenland** [comment]
![Screen Shot 2021-01-15 at 9 21 44 AM](https://user-images.githubusercontent.com/1398304/104758310-17c95e00-5713-11eb-88fc-ccbc4ae9df12.png)

In `themes.php` there's an "Add new" button that leads users to `theme-install.php`, where they can browse the theme directory and install themes.

wordpress.com/themes offers an upload functionality where users can install a theme zip file, but besides that are limited to the themes that are available on dotcom.

![image](https://user-images.githubusercontent.com/1398304/104758775-c1a8ea80-5713-11eb-8c2d-61f4dfa9615d.png)

Long term we should probably add a way to browse the directory to Calypso's theme screen.

**Comment by davemart-in** [comment]
Phoning a friend: Hi @ianstewart!

Thoughts on whether we default to the Calypso themes selection screen or the wp-admin one?

**Comment by obenland** [comment]
https://github.com/Automattic/wp-calypso/issues/43337 would help with this.

**Comment by ianstewart** [comment]
@davemart-in I think we should default to the Calypso one as there's a lot of custom code surrounding it all.

**Comment by obenland** [comment]
Thanks @ianstewart! 

https://github.com/Automattic/wp-calypso/issues/47043 will add a way to access the wp-admin version in the short term.
