### ISSUE TITLE
Nav Unification: Categories link in Calypso redirects you to WP Admin

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#48142]
#### Steps to reproduce

1. Load a page in Calypso
2. Go to Posts -> Categories 
3. You will be taken to the WP Admin version of the link. 

#### Screenshot / Video

![Annotation on 2020-12-08 at 17-45-24](https://user-images.githubusercontent.com/30205248/101550379-394d6200-397d-11eb-9620-100c56ecab03.png)

**Comment by eduardozulian** [comment]
Clicking on Tags did the same for me.

On top of that, I was seeing an odd mix of Calypsoify for both categories and tags:

<img width="1672" alt="Captura de Tela 2020-12-09 às 19 26 34" src="https://user-images.githubusercontent.com/1136160/101696327-bac3f380-3a54-11eb-923c-ff3ade736cc1.png">

**Comment by cpapazoglou** [comment]
Thanks for reporting this issue!

This is intended as the calypso interfaces for Categories / Tags are missing features that exist in wp-admin.
The calypsoify is planed to be removed.

cc @davemart-in
