### ISSUE TITLE
Site Editor: font picker preview doesn't work for Twenty Twenty-One Blocks

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#48148]
If you try to create an FSE site with Twenty Twenty-One Blocks theme using the test Horizon flow you'll run into the following issue:

<img width="1654" alt="Screenshot 2020-12-09 at 00 35 52" src="https://user-images.githubusercontent.com/1182160/101554258-90bbf400-39b6-11eb-8fcc-b5dabb9ec67e.png">

This works fine for Seedlet Blocks theme.

**Comment by noahtallen** [comment]
This was working when we integrated 2021 blocks, so I think we might need to regenerate the templates for the site or something like that. Probably since template resolution changed

**Comment by david-szabo97** [comment]
Regenerated the templates for both 2021 and Seedlet. No more "No matching template found" error.

Font picker works fine on Seedlet but it still doesn't work on twenty-twentyone. Looks like the CSS variables altered by the font picker aren't used anywhere in 2021.

**Comment by vindl** [comment]
> Font picker works fine on Seedlet but it still doesn't work on twenty-twentyone. Looks like the CSS variables altered by the font picker aren't used anywhere in 2021.

@kjellr @scruffian is this a known issue or should we create one in theme experiments repo?

**Comment by vindl** [comment]
Closing since this has been resolved on Dotcom and remaining work needs a separate issue in theme's repo.

**Comment by kjellr** [comment]
> Looks like the CSS variables altered by the font picker aren't used anywhere in 2021.

Which variables are those? Twenty Twenty-One uses the default [global styles font family presets](https://developer.wordpress.org/block-editor/developers/themes/theme-json/#styles) to set its fonts.
