### ISSUE TITLE
Site Editor: Twenty Twenty-one Blocks layout is broken in editing view

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#48149]
The homepage layout looks off in the site editor when compared to what's rendered on the front end:

<img width="1679" alt="Screenshot 2020-12-09 at 00 40 18" src="https://user-images.githubusercontent.com/1182160/101554625-49823300-39b7-11eb-9812-62206f1d6400.png">

**Comment by Addison-Stavlo** [comment]
Took a quick look and this doesn't seem to be an issue with the theme but the starter content itself.  I see the same problem on my site withe `seedlet-blocks`.

For some reason, every section of content is nested in a single column inside a layout grid:
<img width="171" alt="Screen Shot 2020-12-11 at 12 45 09 PM" src="https://user-images.githubusercontent.com/28742426/101936708-e5c25a80-3bae-11eb-9cc0-7fd1fd4fea58.png">

**Comment by Addison-Stavlo** [comment]
or maybe an issue with the layout grid block in the site editor 🤔

**Comment by Addison-Stavlo** [comment]
Yup, so more specifically it seems to be related to the `span` setting for the `layout-grid` block.  It seems like the CSS isnt properly being applied for this attribute in the site editor.  That is, in the post editor the content looks correct, you may notice a span of "8" for a layout grid.  Changing this to "1" will make it look like the broken layout in the site editor.

<img width="220" alt="Screen Shot 2020-12-11 at 1 13 14 PM" src="https://user-images.githubusercontent.com/28742426/101939186-a3028180-3bb2-11eb-8ffd-1c7eaffc8239.png">

Loading the site editor, you will see the setting for that layout grid is properly set, but changing that setting doesnt change anything visually and it always seems to render as if the `span` is 1.

**Comment by Addison-Stavlo** [comment]
Update - It seems the `layout-grid` block styles depend on the `.block-editor` class, which isn't added in the site editor (instead we have `#edit-site-editor` and `.edit-site` on this element).  

It looks like https://github.com/Automattic/block-experiments/pull/156 will fix this issue. 
 Also have [this core PR](https://github.com/WordPress/gutenberg/pull/27724) open to see if we can just add the block-editor class to the site editor.

**Comment by david-szabo97** [comment]
Leaving an update here:
- Looks like we won't be able to add the `block-editor` class to the site editor
- So we are pushing https://github.com/Automattic/block-experiments/pull/156 to be merged.

**Comment by Addison-Stavlo** [comment]
Update - https://github.com/Automattic/block-experiments/pull/156 is merged.  Once the next release (newer than 1.3) goes out we can verify this is fixed and close.

**Comment by vindl** [comment]
@Addison-Stavlo @jasmussen what's the timing and process for these releases?

**Comment by Addison-Stavlo** [comment]
The version in the repo has been updated and is undergoing testing before the release (https://github.com/Automattic/block-experiments/pull/156#issuecomment-763723779).  I'm not sure beyond that though.

**Comment by Addison-Stavlo** [comment]
The underlying issue is fixed and the layout-grid now works properly in the site editor.

However, it looks like our FSE onboarding patterns no longer use the layout-grid block anyways. 🤣
