### ISSUE TITLE
Portfolio and Testimonials ordered differently

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#48151]
Portfolio and Testimonials are ordered differently in Calypso versus WP Admin.

In Calypso, it's Portfolio then Testimonials.  In WP Admin, it's Testimonials then Portfolio.

<img width="544" alt="Portfolio_Testimonial_order" src="https://user-images.githubusercontent.com/11635760/101556930-c50cc180-3970-11eb-8592-a89ed7821a1f.png">

**Comment by cpapazoglou** [comment]
Thanks for reporting this! 

Can you provide more context on this? On which site and which plan? Can you still reproduce it?

**Comment by obenland** [comment]
That is indeed curious. I can't reproduce it anymore and wonder if the switch to the Jetpack version of the menu class has fixed that. @vparkhere does this still happen for you?

**Comment by vparkhere** [comment]
@obenland Just checked, this is no longer an issue!  Calypso and WP Admin are both showing the same order now, Pages | Testimonials | Portfolio.

**Comment by obenland** [comment]
Awesome, thanks for the report and double-checking!
