### ISSUE TITLE
Editor: Word Count obscures text

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/wp-calypso#4816]
**Steps to reproduce**
1. Create a new post https://wordpress.com/post/SITE_URL.
2.Type or paste in sufficient content to reach the bottom right corner where the word count is.
3.Continue typing into the word count and it obscures the text.

**What I expected**
I expected the scroll to kick-in so I can see what I'm typing.

**What happened instead**
I couldn't see what I was typing because it was hidden behind the Word Count.

**Browser / OS version**
Opera version 36.0

**Screenshot / Video**
![wordcount](https://cloud.githubusercontent.com/assets/7946521/14601966/1e5bbaf4-055d-11e6-8f02-35d560a9a6ca.png)

**Comment by mtias** [comment]
Closing as covered by #2152.
