### ISSUE TITLE
Nav Unification: Jetpack → Scan leads to Page Not Found

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#48178]
#### Steps to reproduce

1. Starting at URL: WordPress.com
2. Hover over Jetpack
3. Click Scan

#### What I expected

As a user I expected to see something related to Jetpack Scan. As an HE I understood simple sites don't have access to Jetpack Scan and therefore did not expect this to be included in the nav at all.

#### What happened instead

I reached a page "Uh oh. Page not found."

#### Browser / OS version

Chrome 87, Windows 10

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/30727666/101655891-3a25e700-3a96-11eb-9d28-00f0aa592360.png)

#### Context / Source

#perspective #manual-testing

**Comment by ktyfuller604** [comment]
Also occurs on MacOS Catalina v 10.15.7/ Chrome v. Version 86.0.4240.198

**Comment by cpapazoglou** [comment]
Thanks for reporting!

Scan has been removed as far as I can tell

![](https://cln.sh/gOTVLN+)

Can you confirm @donalirl ?

**Comment by obenland** [comment]
Yes, this should be fixed with #18041.

**Comment by tanjoymor** [comment]
Reopening this issue, because although it's been removed from the Jetpack "menu" it's still located on the Jetpack > Dashboard: https://d.pr/i/JyKb3T and still leads to a Page not found error.

User report: #28012871-hc

**Comment by cpapazoglou** [comment]
That's interesting, this page cannot be found even with `nav-unification` disabled `https://wordpress.com/scan/[DOMAIN]?disable-nav-unification`! 

It seems that we are returning a "Page not found" for all WPCOM (simple & atomic) sites

https://github.com/Automattic/wp-calypso/blob/e0bf4b63a7a09eaec5226826a0bae935edd03ec3/client/my-sites/scan/index.js#L36-L38

cc: @Automattic/jetpack

**Comment by jeherve** [comment]
cc @Automattic/yamato-scan, who may have more background on this.

**Comment by singerb** [comment]
That would be @Automattic/jetpack-voyager

**Comment by rcanepa** [comment]
We are taking a look at this now (I created a card on our maintenance board 1164141197617539-as-1200221780317813).

**Comment by rcanepa** [comment]
The next Jetpack release will include a fix that prevents Atomic sites from seeing that link to Scan. There is no use in allowing users to visit that page since these Atomic site owners can't manually fix threats (we do it for them).
