### ISSUE TITLE
Duplicate links under Appearance tab - nav unification 

### ISSUE THREAD

**Issue by noteeth** [Automattic/wp-calypso#48199]
#### Steps to reproduce

1. Starting from WordPress.com (with nav unification enabled)
2. Click on Appearance tab
3. In the expanded links, Header and Background appear twice

#### What I expected
To see each link one time

#### What happened instead
Header and Background appear twice

#### Browser / OS version
Chrome 87 / Mac Catalina 10.15.7

#### Screenshot / Video
<img width="1574" alt="Screen Shot 2020-12-08 at 11 32 04 AM" src="https://user-images.githubusercontent.com/16570939/101720948-b5b67280-3a5b-11eb-9cca-88b40a797450.png">

**Comment by obenland** [comment]
Closing in favor of #48608. Thanks for the report @noteeth!
