### ISSUE TITLE
Remove submenu flyouts on Reader

### ISSUE THREAD

**Issue by unDemian** [Automattic/wp-calypso#48211]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read
2. Make sure you are a proxied automattician and hit Calypso Staging (this feature is not available to all users yet)
3. Collapse Automattic section
4. Hover over it a couple of times

#### What I expected
- All submenu items should be visible or the hover menu should be scrollable
- Position of the hover submenu should be consistent (either top or bottom)

#### What happened instead
- When section has lots of items they are not all visible and there is no scroll available
- The section hover menu can get out of view port (position also not consistent)

#### Browser / OS version
MacOS Big Sur 11.0.1
Chrome 87.0.4280.88

#### Screenshot / Video

https://user-images.githubusercontent.com/1398304/104658633-1ac34080-5678-11eb-958f-5da7a4f73afd.mov

#### Context / Source
#manual-testing

**Comment by marcuswisecaesar** [comment]
In Chrome, Starting at the /wp-admin URL of an Atomic Site.
In the sidebar, select Settings
Next, in the sidebar, select Users. 

What I expected
All submenu items should be visible, or the hover menu should be scrollable.

The position of the hover submenu should be consistent (either top or bottom)

Coloring should be consistent throughout. 

What happened instead
In Chrome and Firefox Menu Items below Users are not available, and the menu is not scrollable. 

**Browser / OS version**
MacOS Big Sur 11.1
Chrome - Version 87.0.4280.88 (Official Build) (x86_64)

FireFox - Version 84.0.1 (64-bit)


**Screenshot / Video**
[Chrome Testing](https://d.pr/i/L1St77)

[FireFox Testing](https://d.pr/i/UhfpHJ)

**Context / Source**
#manual-testing

**Comment by cpapazoglou** [comment]
More issues reported on this
https://github.com/Automattic/wp-calypso/pull/48874#pullrequestreview-567442868

**Comment by cpapazoglou** [comment]
@sfougnier we have discussed in the past, showing a limited amount of items in the menu Flyout. Is that something you agree or do you have an other suggestion?

**Comment by ghost** [comment]
Thanks for the ping @cpapazoglou 

>showing a limited amount of items in the menu Flyout. Is that something you agree or do you have an other suggestion?

I think this makes sense. Maybe we can display the first 5. Otherwise, one option would be to remove the flyouts entirely from the reader.

**Comment by cpapazoglou** [comment]
@sfougnier let me say that I am totally in for 

> to remove the flyouts entirely from the reader.

which in fact, don't even exist in the interface prior to nav-unification

![](https://cln.sh/spPesU+)

cc: @Automattic/ajax

**Comment by ghost** [comment]
Ok! Let’s remove them. They seem unnecessary and kind of confusing - even
if we capped, what if my site isn’t in the list?

**Comment by bluefuton** [comment]
+1 for removing the flyouts in Reader. 

On a account following several hundred sites it's pretty tricky to use, and the flyout sometimes positions itself upwards of the opening sidebar item, rather than downwards, meaning only a handful of items are reachable:

<img width="485" alt="Screen Shot 2021-01-22 at 15 39 34" src="https://user-images.githubusercontent.com/17325/105438705-643f0b80-5cc8-11eb-879c-bc6efef2d133.png">

**Comment by getdave** [comment]
Agreed. Let's remove the flyouts on Reader.
