### ISSUE TITLE
Shift + letter in middle of domain search string sends cursor to end of string

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#48225]
#### Steps to reproduce

starting from https://wordpress.com/start/domains
in the domain box, type “aaaa”
move your insertion point to the beginning of the string (or anywhere inside the string) > type “BBBB”

expected: bbbbaaaa (I'm assuming the change of case is expected)

actual: baaaabbb – the cursor pops to the end of the string after the first character is typed

**Comment by klimeryk** [comment]
Can't reproduce it anymore - might have gotten fixed by https://github.com/Automattic/wp-calypso/pull/51718.
