### ISSUE TITLE
Media library grid visually broken on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#48227]
Media library doesn't scale down well.

Thanks @elibud for reporting.

#### Steps to reproduce

1. Starting at URL: Open wordpress.com/media
2. Try mobile width
3. 💥 

<img src="https://user-images.githubusercontent.com/87168/101809356-1f985000-3b20-11eb-8ee2-6de6258b7b9f.png" width="400">

@michaeldcain mentioned that it would look at little better if we defaulted to the next size larger for thumbnails on mobile:

<img src="https://user-images.githubusercontent.com/87168/101809507-4eaec180-3b20-11eb-898a-cd3acb75176a.png" width="300">

cc @Automattic/team-calypso anything lately changed in componentry or in media-library that might've caused this? Anything in CSS loading-order that might affect?

**Comment by tyxla** [comment]
> Media library doesn't scale down well.
> 
> Thanks @elibud for reporting.
> 
> #### Steps to reproduce
> 1. Starting at URL: Open wordpress.com/media
> 2. Try mobile width
> 3. 💥
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/87168/101809356-1f985000-3b20-11eb-8ee2-6de6258b7b9f.png">
> 
> @michaeldcain mentioned that it would look at little better if we defaulted to the next size larger for thumbnails on mobile:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/87168/101809507-4eaec180-3b20-11eb-898a-cd3acb75176a.png">
> 
> cc @Automattic/team-calypso anything lately changed in componentry or in media-library that might've caused this? Anything in CSS loading-order that might affect?

Nothing recent comes to mind!

As a solution, I think that we should detect mobile devices (+ resizes that end up in mobile size) and for mobile widths, ensure we're setting the scale to a maximum of 3 items per row. In addition, we might want to remove the `height` from `.sorted-grid__label` to ensure labels don't overlap the thumbnails.

I haven't had the time to tinker with those, but it seems those 2 should do the job.

**Comment by jsnajdr** [comment]
> I think that we should detect mobile devices (+ resizes that end up in mobile size) and for mobile widths, ensure we're setting the scale to a maximum of 3 items per row.

Funny that this is exactly how the mobile media view behaved until it was broken in #8295 (Oct 2016). See how the `mediaScale` used to default to `SCALE_TOUCH_GRID` (with a value of 0.32, i.e., approx 1/3) on mobile screens:

https://github.com/Automattic/wp-calypso/pull/8295/files#diff-3d25fc6c2356eac4a1d0fccb0744a0eaa6fa67f9abe26de82b4c725d8786832eL94

We should reintroduce that condition. On mobile devices, the scale slider (see the thing on the screenshot below) is not visible, so its value should not be used and the scale should be either 1 or 1/3.

<img width="428" alt="Screenshot 2020-12-14 at 11 27 08" src="https://user-images.githubusercontent.com/664258/102071444-c4f14380-3e00-11eb-8204-76e352e29bdf.png">

**Comment by richardkang112** [comment]
Hello everyone. May I work on the part of the issue where setting the default media scale value of 0.32 on mobile viewport? @Christopher-Stevers Are you working on this already?

**Comment by jsnajdr** [comment]
Hi @richardkang112 :wave: I think you can start working on this 🙂 The #53705 PR by @Christopher-Stevers fixes a related bug, but not quite this one.

**Comment by richardkang112** [comment]
@jsnajdr Thank you for the PR review! I'll work on the suggested changes.
