### ISSUE TITLE
Domain Picker: don't overgrow domain name part of the suggestion item

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#48221]
Currently, the name section of domain picker item is too large because it has `flex-grow: 2`.

`flex-grow: 2`

<kbd>
<img width="400" src="https://user-images.githubusercontent.com/17054134/101781114-b7ce0f00-3af7-11eb-9dca-6f888807f0b5.png" />
</kbd>

`flex-grow: 1;`
<kbd>
<img width="400" src="https://user-images.githubusercontent.com/17054134/101781264-dd5b1880-3af7-11eb-84d8-b7aceddeca0e.png" />
</kbd>

The Fix is probably like this: https://github.com/Automattic/wp-calypso/pull/48172/files/b24e4f6da6c8c64f174fbe3101aa1771365b697e#diff-f3729f16de3b5c7f75484038ca19e51dc1b702223aaa937c7b68df6298c2e66bR221

**Comment by razvanpapadopol** [comment]
This is now fixed
