### ISSUE TITLE
Nav Unification: WP Admin > Plugins should point to Calypso

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48239]
#### Steps to reproduce

1. Go to WP Admin
2. Click on the Plugins tab

#### What I expected

To see only the Calypso version of the page.

#### What happened instead

If you go to WP Admin:

1. The link will be https://SITEURL.wordpress.com/wp-admin/plugins.php instead of https://wordpress.com/plugins/SITEURL.wordpress.com
2. There will be a sub-item called `Installed Plugins` on Simple Sites.

#### Screenshot / Video

From WP Admin:

<img width="832" alt="Captura de Tela 2020-12-10 às 20 10 52" src="https://user-images.githubusercontent.com/1136160/101840976-d5b16900-3b23-11eb-9d19-6232ad1678e1.png">

#### Browser / OS version

Chrome 87 / Mac Catalina 10.15.7

#### Context / Source

#manual-testing

**Comment by cpapazoglou** [comment]
Thanks for reporting! 

In my simple site "Plugins" doesn't have a submenu and correctly redirects me to Calypso Plugins page
![](https://cln.sh/OTzvhP+)

Can you still reproduce this on a simple site? Be ware that this is the **correct** behavior for atomic sites.

**Comment by obenland** [comment]
@eduardozulian Have you had a chance to try reproducing the bug yet? Trying to see if this has been fixed previously.

**Comment by eduardozulian** [comment]
@cpapazoglou @obenland cannot reproduce this anymore. Thank you for the ping!
