### ISSUE TITLE
Nav Unification: Different wording in Calypso and WP Admin when switching sites

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48233]
#### Steps to reproduce

1. Starting from WordPress.com (with nav unification enabled)
2. Try to Switch to another site from both Calypso and WP Admin

#### What I expected

To see the same button.

#### What happened instead

* On Calypso, I see `Switch Site`
* On WP Admin, I see `Browse Sites`

#### Browser / OS version

Chrome 87 / Mac Catalina 10.15.7

#### Screenshot / Video
<img width="337" alt="Captura de Tela 2020-12-10 às 19 20 12" src="https://user-images.githubusercontent.com/1136160/101836762-bf53df00-3b1c-11eb-9dc0-aba9195d37cf.png">

#### Context / Source

#manual-testing

**Comment by cpapazoglou** [comment]
Thanks for reporting! This is actually expected, as calypso "Site Switcher" opens in place and you can switch to an other site (or not) whereas `wp-admin` "Browse Sites" redirects to the site-switcher page `https://wordpress.com/home`
