### ISSUE TITLE
Nav Unification Alpha: Two Areas for WordAds - WP-Admin Version Unnecessary

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#48238]
#### Steps to reproduce

1. Starting at the default view (Calypso), click on Tools - Earn

![image](https://user-images.githubusercontent.com/30731356/101839890-054a7c00-3af8-11eb-9274-6181f1219c7b.png)

And that will bring you to the spot where you can view the ad dashboard, and adjust any ads/WordAds settings. 

2. Next, hover over Settings, to view the submenu, and there won't be any WordAds options from there:

![image](https://user-images.githubusercontent.com/30731356/101839954-23b07780-3af8-11eb-8165-16661f760edc.png)

3. If you click on Settings, and it takes you to the "WP-Admin" view, there will then be a new spot that appears for WordAds there, which is an unnecessary semi-duplicate (it's missing some features, like ad placements) of the ads dashboard in "Calypso" view:

![image](https://user-images.githubusercontent.com/30731356/101840015-3aef6500-3af8-11eb-90f6-bbc406ab682a.png)

#### What I expected
All of my WordAds settings to be in one place. 
#### What happened instead
Once the WP-Admin view is loaded, a new area for WordAds appears that has some, but not all, of the WordAds options available in it. 
#### Browser / OS version
All
#### Context / Source
#manual-testing

**Comment by obenland** [comment]
Hi @scosgro, thanks for the report. I wonder if this was fixed in r218221-wpcom? I can't reproduce it anymore.

**Comment by scosgro** [comment]
> 
> 
> Hi @scosgro, thanks for the report. I wonder if this was fixed in r218221-wpcom? I can't reproduce it anymore.

Confirmed fixed on my end! Thank you!
