### ISSUE TITLE
Nav Unification: Browse/Switch site behavior is different in Calypso and WP Admin

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48234]
#### Steps to reproduce

1. Starting from WordPress.com (with nav unification enabled)
2. Try to Switch Sites from both Calypso and WP Admin

#### What I expected
The same flow: either we see the new site panel appearing in the left sidebar (Calypso) or link users to https://wordpress.com/home (WP Admin) where they can select the site they wanna work on.

#### What happened instead
I have two different navigations that do the same thing.

#### Browser / OS version

Chrome 87 / Mac Catalina 10.15.7

#### Screenshot / Video

In Calypso:

<img width="930" alt="Captura de Tela 2020-12-10 às 19 29 15" src="https://user-images.githubusercontent.com/1136160/101837601-0db5ad80-3b1e-11eb-99c8-f2233ef72af7.png">

In WP Admin:

<img width="631" alt="Captura de Tela 2020-12-10 às 19 30 42" src="https://user-images.githubusercontent.com/1136160/101837699-38a00180-3b1e-11eb-8e87-eb3f6c4a0722.png">

#### Context / Source

#manual-testing

**Comment by cpapazoglou** [comment]
Thanks for reporting! This is actually expected right now!
