### ISSUE TITLE
Nav Unification: Selecting subitems does not keep the submenu open

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48240]
#### Steps to reproduce

1. Starting from WordPress.com (with nav unification enabled)
2. Go to a parent menu like `Tools` and click on one of the sub-items

#### What I expected
To keep the sub-menu open and have a visual explanation of where I am. This is the standard behavior on WP Admin.

#### What happened instead
The menu isn't persistent and sometimes it closes if you choose another sub-item.

#### Video

https://d.pr/v/emlyb2/IuimBt37dp

#### Browser / OS version

Chrome 87 / Mac Catalina 10.15.7

#### Context / Source

#manual-testing

**Comment by michaeldcain** [comment]
I can reproduce this with the "Upgrades" menu and submenu items:

![submenu-toggle](https://user-images.githubusercontent.com/942359/103226424-17029080-48fa-11eb-811b-e57f820d3064.gif)
