### ISSUE TITLE
Focused Launch: Plans details design parity

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48258]
Discrepancies between current plans details view and designed plans details view.

Design parity Figma link: 27834-pb

* Title - If we are able to, use Recoletta Medium font for the title.
* Title - `color: #101517;`
* Sub-title - Remove letter spacing
* Plans grid - `border-color: #DCDCDE;`
* Plans grid - `border-radius: 4px;`
* Plan title - `font-weight: 500;`
* Plan price - `margin-top: 24px;`
* Plan price - `font-weight: 500;`
* Plan billing sub-text - `color: #646970;`
* Plan billing sub-text - `font-size: 10px;`
* Plan checkmarks - "Is included" checkmark `color: #117AC9;`
* Plan checkmarks - If word-wrapping "Not available with custom domain" is an issue reword to be "Not available with domain"
* Plan checkmarks - Remove `letter-spacing`
* Plan checkmarks - If word-wrapping is an issue, suggest using `font-size: 13px` ONLY IF it's available
* Plan checkmarks - Checkmark alignment and orphaned text for item "Pick a free domain (1 year)". See point 7 from Mikael p58i-9Mt-p2#comment-48403

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
