### ISSUE TITLE
Focused Launch: Modal design parity

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48251]
Discrepancies between current modal and designed modal. These should apply to all the views in the Focused Launch modal.

Design parity Figma link: 27834-pb

**Desktop**
* Background opacity on the top section of the modal allows you to see the editor behind it.
* Logo should be seen behind the modal rather than on top of it
* Help icon (bottom right) should be removed as we have the "Ask a happiness engineer" link.

**Mobile**
* "Complete setup title" - `font-size: 14px;`
* "Complete setup title" - `font-weight: 500;`
* "Complete setup title" border - `border-color: #E2E4E7;`

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
