### ISSUE TITLE
Focused Launch: Success view design parity

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48259]
Discrepancies between current success view and designed success view.

Design parity Figma link: 27834-pb

* "Hooray" - If we are able to, use Recoletta Medium font
* "Hooray" - `font-size: 48px;`
* "Hooray" - `line-height: 52px;`
* "Hooray" - `color: #101517;`
* Congratulations sub-title - `font-size: 20px;`
* Congratulations sub-title - `line-height: 28px;`
* Link box - Link text to be `font-size: 14px;`
* "Copy link" button - `font-size: 14px;`
* "Copy link" button - `border-color: #CACBCD;`
* "Copy link" button - `color: #1D2327;`
* "Continue editing" button - `background-color: #117AC9;`
* "Continue editing" button - `border-radius: 4px;`

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
