### ISSUE TITLE
Focused Launch: Summary view design parity

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48252]
Discrepancies between current Summary view and designed Summary view.

Design parity Figma link: 27834-pb

**Desktop**
* Title - If we are able to, use Recoletta Medium font for the title.
* Name your site - Input box to have `border-radius: 4px;`
* Name your site - Unfocused `border-color: #C3C4C7;`
* Name your site - Input box to be `height: 44px;`
* Confirm your domain - Too much `letter-spacing` in domain suggestion
* Confirm your domain - Too much space between domain name and "Recommended" tag
* Confirm your domain - Too much letter spacing on the "Recommended" tag
* Confirm your domain - "First year included in paid plans" green color should be `#007017`
* Confirm your domain - "First year included in paid plans" text to be fit on one line (Potentially fixed in https://github.com/Automattic/wp-calypso/pull/48172)
* Confirm your domain & confirm your plan - `border-width: 1px;` (grey outline) when unselected. `border-width: 2px;` (blue outline) when selected
* Selected domain - Selected domain background should be `#FAFCFE`
* Selected domain - Domain and border color should have color of `#117AC9`
* Messaging - Border to the left of the messaging (Monetize your site with WordPress Premium etc) should extend down to the "Launch your site" button
* Messaging - Checkmarks have too much space between them and their title above
* Messaging - Title text should be aligned properly to the top of it's first steps option box (Refer to red line on the design parity highlighting this)
* Launch button - Should use "new" blue `#117AC9` if we are able to
* Ask a Happiness Engineer link - Should use "new" blue `#117AC9` if we are able to
* View all domains link - Should be `font-size: 14px`
* View all plans link - Should be `font-size: 14px`

**Mobile**
* Title - `color: #101517;`
* "Confirm your domain" - Step title and sub-text with icon does not align left with each other properly
* Domain suggestion - "Included in paid plans" fit on one line (Potentially fixed in https://github.com/Automattic/wp-calypso/pull/48172)

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
