### ISSUE TITLE
Focused Launch: Plans details view accessibility

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48263]
Navigating through the plan details view appears to focus on some invisible elements.

p58i-9Mt-p2#comment-48404

**Replication steps**
starting from https://wordpress.com/start/domains
get yourself to the focused launch modal
click “View all plans”
tab thru page

**Expected** 
tab order travels to visible elements

**Actual**
tab order seems to include several invisible/non-interactable elements

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
