### ISSUE TITLE
Nav Unification: Purchases submenus don't include the site in the url

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#48266]
#### Steps to reproduce

1. Enable `nav-unification` paYJgx-1af-p2
2. Go to https://wordpress.com/plans of a simple site
3. Click a submenu

![](https://cln.sh/RRg3pF+)

#### What I expected
The submenu should open in the current site

#### What happened instead
The site switcher opens

#### Context / Source
This probably happens because the url doesn't contain the current site

**Comment by obenland** [comment]
Fix in D54198-code

**Comment by obenland** [comment]
r218221-wpcom
