### ISSUE TITLE
Focused Launch: Editor buttons

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48264]
p58i-9Mt-p2#comment-48402

### Publish button not primary blue

Complete the focused launch flow. At the end of the flow, close the checkout, then expect the congrats splash, and press “back to editing”.

#### What I expected
Launch button was gone, but I expected the “Publish” button now to be primary blue color

#### What happened instead
Publish button was present, but wasn't in the primary blue color

#### Screenshot / Video
<img width="359" alt="publish-button" src="https://user-images.githubusercontent.com/8639742/101913630-232ce500-3bbb-11eb-9cf1-a94b49fb50c4.png">

### Publish button not primary blue

“Update” button (or “Publish” button for new pages) didn’t have hover state.

#### What I expected
Consistent hover states for buttons

#### What happened instead
Inconsistent hover states for buttons

#### Screenshot / Video
![launch-update-hover](https://user-images.githubusercontent.com/8639742/101914035-b108d000-3bbb-11eb-9f47-016fb3ea8a37.gif)

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
