### ISSUE TITLE
Purchases: "Pay" button doesn't work for Brazilian users

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48265]
We had a few reports from `pt-br` users unable to complete a purchase. The Pay (_Pagar_) button is simply pink/active but nothing happens when you click on it. Console logs are empty.

In my tests, this only happened if you don’t have any stored cards on your account.

**The workaround** is to add the card first on https://wordpress.com/me/purchases/add-credit-card, then go back and complete the purchase from `/checkout`.

#### Steps to reproduce

1. Start with an account without any stored credit cards
2. Make sure the account is set to BRL
3. Pick a plan and go to the checkout
4. Try to click on the Pay/Pagar button

#### What I expected
To complete my purchase.

#### What happened instead
The button is active, can be clicked, but nothing happens when you do it.

#### Browser / OS version
Chrome 87 / Mac Catalina 10.15.7

#### Screenshot / Video
<img width="1023" alt="pagar" src="https://user-images.githubusercontent.com/1136160/101921163-71d28300-3bab-11eb-8acf-d076c54b2df2.png">

#### Context / Source
#user-report

Reports so far

* 26261363-hc
* 3566308-zen
* 3565875-zen
* 26269498-hc
* https://wordpress.com/br/forums/topic/botao-pagar-no-carrinho-nao-funciona/

cc @nbloomf

**Comment by nbloomf** [comment]
Between "stored cards" and "Brazil" I suspect this is related to #48187 or #47642.

**Comment by sirbrillig** [comment]
For (my) convenience, how to test Ebanx:

- Complete a payment using a credit card processed through Ebanx.
  - Set your currency to `BRL`.
  - In the contact information step, choose "Brazil" for the country.
  - In the final step, choose "Credit or debit card".
  - Verify that the form asks for all the Ebanx fields in addition to the credit card fields (Taxpayer Identification Number, Phone, etc.)
  - Use an [ebanx test card](https://developer.ebanx.com/docs/resources/testCreditCards/) and [test customer info](https://developer.ebanx.com/docs/resources/testCustomerData/).
  - Verify that the payment succeeds and that you are redirected to the thank-you page.
