### ISSUE TITLE
CoBlocks: Plugin Update to v.2.5

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#48275]
Call for Testing: p7DVsv-a49-p2
Previous update: https://github.com/Automattic/wp-calypso/issues/45033 (v.2.2)

### Process

* [x] Build v2.5.3 (24-gh-Automattic/coblocks-builder)
* [x] Install v.2.5.3 (D54260-code)
* [x] Activate v.2.5.3 for `coblocks-edge` stickered sites (D54263-code)
* [x] Publish a Call for Testing post (p7DVsv-a49-p2)
* [x] Activate for all sites (D54576-code)
* [x] Publish internal announcements (p7DVsv-a49-p2, p1608554666009900-slack-CB0B2G43X)
* [x] Close the Call for Testing post (p7DVsv-a49-p2#comment-33181)
* [x] Clean up unused releases
  - [x] v1.23.0 (D54581-code)

### Testing

* [x] Calypso E2E tests (https://github.com/Automattic/wp-calypso/pull/48448)
* [x] Calypso E2E tests after the 25-gh-Automattic/coblocks-builder fix (https://github.com/Automattic/wp-calypso/pull/48448#issuecomment-747554885)
* [x] Add E2E tests for the gutter customization (https://github.com/Automattic/wp-calypso/pull/48488)

### Related updates
* [x] Remove "CoBlocks" collection (https://github.com/Automattic/wp-calypso/issues/46776)

### Known issues

* [x] Custom gutter doesn't work in the front-end (25-gh-Automattic/coblocks-builder)

**Comment by WunderBart** [comment]
CoBlocks v2.5.3 are now on `coblocks-edge` stickered sites. Reopening this one until they're in production as well.
