### ISSUE TITLE
Domain Picker: Component tests for business logic

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48270]
The logic around the `<DomainPicker />` component has become a bit more complex during the Focused Launch project. Therefore we need to create some component tests to cover the following logic we've introduced.

* If you have current domain selected which is not in the returned list of suggested domains. We append this to the bottom of the list of domains (https://github.com/Automattic/wp-calypso/pull/47633)
* If you pass the prop `orderSubDomainsLast={ true }` to the `<DomainPicker />` component this takes the free subdomain which is currently shown at the top of the list, and reorders it to appear at the bottom of the list instead (https://github.com/Automattic/wp-calypso/pull/48083)

**Comment by StefanNieuwenhuis** [comment]
I'm closing this issue since we're fixing this in #50888.

**Comment by ciampo** [comment]
@StefanNieuwenhuis  let's make sure that the test scenarios highlighted in this PR are mentioned in #50888 too
