### ISSUE TITLE
Plans: research enterprise plugins

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4827]
We've in the past offered an enterprise plan that included some VIP plugins. The enterprise plan, while it is no longer offered, it is in fact still supported for existing users who had signed up for it.

We need to review these plugins to see if any of them are good candidates for including in the business bundle as well.

**Comment by JamesGeiger** [comment]
Any news on this?

**Comment by rralian** [comment]
Sorry for the slow reply, no news at the moment @JamesGeiger. Was there something in particular you were interested in?

**Comment by drw158** [comment]
I'll add the research I did here:

The best summary of Enterprise:

"It’s the Business plan + access to VIP plugins + access to a Custom Javascript editor."

There was a security concern (custom JS). The biggest concern with custom JavaScript is protecting wpcom cookies. I think all the competitors serve the JavaScript from a different domain than you login at.

After quick look, none of the VIP plugins that were offered looked very interesting. VIP clients have very different needs than small business owners.

it may honestly be more work to start with an existing VIP plugin vs trying to start from scratch.

"Featured Plugins"
![screen shot 2016-05-11 at 9 30 52 am](https://cloud.githubusercontent.com/assets/618551/15184554/3d713f9e-175b-11e6-94ea-43bdd031206c.png)

Some "Community Plugins" that I thought were interesting:

- Art Direction Redux - Per-post styles and art direction
- CampTix Event Ticketing - event ticketing
- Gumroad - embed products with shortcodes
- MCE Table Buttons

**Comment by drw158** [comment]
The research was done to some extent, so I'll close.
