### ISSUE TITLE
Nav Unification: update "Purchases" to account for site-level billing

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#48322]
In #45601, we added the site-level billing management to the current Calypso sidebar. This lets the users see their purchases, billing history, and payment methods in a single site context and has helped us reduce billing-related Happiness requests. Additional navigation updates are in progress in #47465 to clarify the purpose of the "Purchases/Upgrades" section.

As such, we should update the unified navigation to match Calypso's.

**Proposed Changes:**
- Rename "Purchases" to "Upgrades"
- Add the following sub-pages:
 - "Plans" (`/plans/{site_slug}`)
 - "Domains" (`/domains/manage/{site_slug}`)
 - "Purchases" (`/purchases/subscriptions/{site_slug}`)
- Remove "Domains" from under "Settings"

See: pbOQVh-KN-p2

**Comment by obenland** [comment]
@davemart-in I updated the Unified Nav Proposal spreadsheet with the new structure

**Comment by michaeldcain** [comment]
- [x] Jetpack change: Automattic/jetpack#18093
- [x] Backend diff: D54302-code
- [x] Fallback data edit: https://github.com/Automattic/wp-calypso/pull/47465/commits/8d37ca1c32d9ade9a6a46b66a0dfc261dd3d6f83

**Comment by getdave** [comment]
@michaeldcain looks like this is complete? I'm closing, feel free to reopen if still valid. Thanks for sorting it 🙇
