### ISSUE TITLE
Posts: Post count does not update on delete

### ISSUE THREAD

**Issue by ChaosExAnima** [Automattic/wp-calypso#48325]
#### Steps to reproduce

1. Create one or more draft posts.
2. Move one to the trash.
3. Observe the count under drafts.

#### What I expected

I expected the count of draft posts to update to reflect the number of drafts.

#### What happened instead

The count did not update when I deleted the post.

#### Browser / OS version

http://supportdetails.net/QGYIJ82K

#### Screenshot / Video

![Annotation on 2020-12-14 at 16-58-49](https://user-images.githubusercontent.com/1760168/102141078-43180f00-3e2e-11eb-865e-d18b5c5ebb90.png)

#### Context / Source

Found when writing a post for my blog. #dogfooding

**Comment by cathymcbride** [comment]
I am able to repro when deleting from the editor. Closing https://github.com/Automattic/wp-calypso/issues/12434 in favor of this one.

**Comment by ericamQA** [comment]
Can no longer repro with "Dashboard Appearance" setting off or on (tested both ways.)
