### ISSUE TITLE
Checkout: Make it easier/clearer to remove existing items from the cart

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#48335]
Currently users are required to click an 'Edit' link to make any changes to their cart. This results in a lot of confusion from users who want to remove items from their cart but feel unable to.

I know a lot of work has been done on the cart/checkout wording and flow - but am wondering if it is worth reviewing the user experience around changing/removing items from the cart?

**Comment by fditrapani** [comment]
I mentioned this on p2 but I suspect this will likely get dealt with once we implement a global cart (https://github.com/Automattic/wp-calypso/issues/48334) and fix any issues related to the cart not being emptied after purchases complete.

**Comment by marianearchimbaud** [comment]
#3600114 hc

This is part of the user's feedback:
...Unlike every other e commerce site i've been to, there doesn't seem to be any way to take things out of the cart.  Help!...

Currently, the easiest way is to direct them back to WordPress.com > My Site > Plan > Plans and click on the Cart button there and then the trash/garbage icon. But I do think it should be consistent with and improved on the Checkout page too.

**Comment by sirbrillig** [comment]
@olaolusoga this is not high priority, but in case you have any thoughts about this.

**Comment by michaeldcain** [comment]
It doesn't fix this issue, but in #51559 the `?order-review=true` query parameter was added to Checkout to have the cart "summary" step default to its edit mode. We implemented the query parameter for the abandoned cart notices and 228-gh-Automattic/payments-shilling will implement it for abandoned cart emails, but if other flows are identified that could benefit from it, we can add it as a short-term fix.

**Comment by michaeldcain** [comment]
This was fixed in #52850
