### ISSUE TITLE
New Onboarding: Launch prevented if you scroll up during checkout step on mobile

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#48339]
On mobile, the "Launch your site" button on the final checkout step of the launch flow is impossible to click if you scroll up to review the checkout summary before submitting.

To work around this you can click "Go back" - [but not "Back"](https://github.com/Automattic/wp-calypso/issues/48338) - reselect your plan - and then click "Launch your site" without scrolling again.

### Got:
<img src="https://user-images.githubusercontent.com/811776/102177398-9609c900-3ef7-11eb-8202-1196cff0a5af.png" width="60%" />

### Expected:
<img src="https://user-images.githubusercontent.com/811776/102177402-999d5000-3ef7-11eb-80e1-8a3a5e5adac7.png" width="60%" />

**Comment by razvanpapadopol** [comment]
The feature affected by this bug is no longer in production after D57607-code
