### ISSUE TITLE
Removing/Canceling Purchases in Calypso results in Blank/White Screen

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#48332]
This is an initial stub for us to track the issue. Seeing multiple instances of WPCOM visitors unable to cancel/remove subscriptions - they are directed to a blank/white screen.

p1607995931499600-slack-C03TY6J1A

**Comment by charliescheer** [comment]
Adding to this that I tested accessing the plans for my sites to test this out and currently I am un able to access the plans details pages for many of my subscriptions, but it seems to be consistent by site type.  
non atomic site bundle plans can not be accessed in the purchases currently.  I get this every time https://d.pr/i/hVa4t3

Site/plan I saw this for:
https://charliedotorgtest.com / Jetpack Premium
notgonnafinish.wordpress.com / WPcom Personal
justboring.travel.blog / WPCOM Business - not atomic

Sites I did not see this problem for:
cscheerecommerce.wpcomstaging.com / WPCOM eCommerce - atomic
testingthebend.com / WPCOM Business - atomic

Domains and themes did not have this issue either

**Comment by katiebethbrown** [comment]
I am not able to load the Billing page on my non-Atomic sites either.

/purchases/subscriptions/katiesstoreadminpractice.wordpress.com/11258636

<img width="1009" alt="YrYWFu" src="https://user-images.githubusercontent.com/42279181/102163829-57690580-3e48-11eb-9b64-fed61bbf4852.png">

Error in the console is `TypeError: can't access property Symbol.iterator, ke.b[r] is undefined`

**Comment by glendaviesnz** [comment]
Issue seems to be with  https://github.com/Automattic/wp-calypso/pull/48280/files#diff-373308463f320cf32c34ff4fcb296d6cf3e773a6b6d428ee7de9bf22592b6e28R329 - just looking to see if there is a simple fix
