### ISSUE TITLE
New Onboarding: Browser back button exits launch flow

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#48338]
When clicking the browser back button instead of the "Go Back" navigation link during the launch flow post-gutenboarding you are taken back to the page you came from instead of back to the previous step.

This is likely a larger issue on android than it is on desktop or iphone.

**Comment by razvanpapadopol** [comment]
@lsl this is about the Post-Gutenboarding Launch flow, right? On `/new` browser back button should work fine on all devices.

**Comment by lsl** [comment]
Must have been, can't repro with /new now, guessing I got mixed up where I was testing from.

**Comment by lsl** [comment]
Track this in the new issue here: https://github.com/Automattic/wp-calypso/issues/49565
