### ISSUE TITLE
Checkout: Add 'Cart' Icon somewhere persistent when there are items in the Cart

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#48334]
As raised in feedback about the current Cart/Checkout process (p7DVsv-9WJ-p2) Is it possible to consider a location for the Cart/Checkout icon to be visible more persistently?

Currently user's are often not aware that they have an item in their cart - and the notice about it displays inconsistently (only on some pages - Plans and Billing). 

It would be interesting to investigate if a more permanent position for this might make things clearer to users, and lower support interactions about it.

There's a related (but not exactly the same) conversation in #44188 which this could be considered as a part of?

**Comment by fditrapani** [comment]
Thanks for creating this issue @jordesign. I'm adding it to the Shilling backlog for prioritization. As I mentioned in my P2 comment, this will likely need to wait for the new nav to launch before we can implement anything.

**Comment by sirbrillig** [comment]
If merged, https://github.com/Automattic/wp-calypso/pull/52890 will fix this.

**Comment by jjchrisdiehl** [comment]
PR #52890 is merged and should resolve this issue, closing issue.
