### ISSUE TITLE
New Onboarding Launch: Skip domain blocks final step

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#48342]
If you clear the domain suggestion text and skip choosing a domain during the signup / launch flow a default domain suggestion won't be selected. The checkout step then fails.

This was potentially exposed by the recent fixes to enable site names without latin characters to get past the domain selection step by clearing the domain suggestion text.

<img src="https://user-images.githubusercontent.com/811776/102178748-103b4d00-3efa-11eb-8caf-0bc0ac40bec8.png" width="60%" />

**Comment by youbrokesomething** [comment]
This onboarding flow has been replaced by other new flows. Closing this ticket.
