### ISSUE TITLE
New onboarding launch: Closing / reopening launch flow triggers incorrect error state

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#48341]
When launching a new site, if you close the launch flow and then re-open it you'll be given an incorrect error on the domain step. Retyping / changing the domain step text will clear the error.

![Screen Shot 2020-12-15 at 16 03 24-fullpage](https://user-images.githubusercontent.com/811776/102178273-40362080-3ef9-11eb-9afb-6376b0ca422a.png)

**Comment by razvanpapadopol** [comment]
Can't reproduce this anymore after the latest Domain Picker fixes.
