### ISSUE TITLE
Plans: domain tip research

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4835]
In the past we had implemented something called a "domain tip", where we prominently displayed domain suggestions based on user info. We have not ported this to calypso. We should look into the prior implementation (MGS for "domain tip") and determine the potential lift we could get from implementing this in calypso. It does not appear to be on any other teams' radar. Write a p2 post with findings before building anything so we can coordinate across other domain-interested teams.

**Comment by gwwar** [comment]
Added some initial investigation in p3fqKv-2de-p2

**Comment by rralian** [comment]
closing because @gwwar knows all the things now.
