### ISSUE TITLE
Unexpected redirection to /new at the end of /start site creation flow

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#48361]
#### Steps to reproduce

1. Navigate to `/start/domains`
2. Go through the flow — select a domain and a plan
3. Instead of completing the flow, the page is redirected to `/new`

#### What I expected

The user should be able to complete the control site creation flow (`/start/domains`)

#### What happened instead

The user gets redirected to New Onboarding flow

#### Browser / OS version

N/A

#### Screenshot / Video

N/A

#### Context / Source

Originally reported in p58i-9Mt-p2#comment-48406 (see p9bUq0-24a-p2 for more details)

Potentially fixed by #48350

**Comment by ciampo** [comment]
Note: logged issue as originally reported. So far I haven't been able to reproduce it

**Comment by ciampo** [comment]
Update: managed to reproduce it. It looks like, at least on my local machine, the redirection to `/new` happens when the flow navigates to the `secure-your-brand` step

![Screenshot 2020-12-15 at 17 39 34](https://user-images.githubusercontent.com/1083581/102244583-c43dd780-3efc-11eb-89af-ec63f554f68c.png)

**Comment by razvanpapadopol** [comment]
> Update: manages to reproduce it. It looks like, at least on my local machine, the redirection to `/new` happens when the flow navigates to the `secure-your-brand` step

Looks like the users get redirected from to `/start/secure-your-brand` to `/start` and it's just a coincidence that for EN, if logged in, we are then redirecting them to `/new`. @ciampo could you reproduce in another language as well?

I see the code for this campaign has been added in #46078 but then the test has been stopped in #48208.

From the described behavior it seems like some code in the signup flow is still redirecting users to `/start/secure-your-brand` but that step was disabled after stopping the test so that's why they are automatically redirected to `/start`.

cc: @dzver @aneeshd16 @niranjan-uma-shankar

**Comment by ciampo** [comment]
Update: It looks like I was able to reproduce this issue by "accident" — I was checking out PR #48112 and I came across this bug. Looking at that PR, it was opened before #48208 got merged. **After pulling the latest code changes from `trunk`, I'm again _not_ able to reproduce the bug.**

This makes sense, considering that the bug reports were filed 5 days ago, at this point very likely before #48208 got merged. Tomorrow I'll do some more digging/testing to confirm that the issue can't be reproduced anymore.

---

In case it's still relevant:

> @ciampo could you reproduce in another language as well?

Keeping in mind what I just mentioned above, while running an older version of the codebase, I could reproduce the bug only when using the English locale.

**Comment by ciampo** [comment]
Did some further testing on production (non-proxied):

- Locale: `en`, free plan: Could not reproduce
- Locale: `it`, free plan: Could not reproduce
- Locale: `en`, premium plan (including checkout): Could not reproduce
- Locale: `it`, premium plan (including checkout): Could not reproduce
- From logged out, locale: `en`, free plan: Could not reproduce

I'm going to assume that this issue was fixed when #48208 got merged, since the reports happened before the merge, and I could only reproduce the issue on an older version of the codebase
