### ISSUE TITLE
Horizon Site Editor: Site no longer correctly loading templates/parts

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48376]
This site created in the Horizon-based Gutenboarding flow is no longer correctly loading template parts.

https://twentytwentyonestarterdesign.wordpress.com/

![image](https://user-images.githubusercontent.com/545779/102265078-2803d880-3edc-11eb-8958-b7e87dc29526.png)

### Debugging notes

I cannot reproduce this issue when creating new sites in the same Horizon flow so I don't believe this to be a theme issue with the work-in-progress Twenty Twenty One Blocks.

That said, this site _will_ correctly load template parts if I switch to another block-based theme via the command line.

Also, worth noting that this site was created via the Horizon flow (which sets the theme and some default content in the resulting site) before the Site Editor briefly stopped working on Horizon. cc @jeyip

**Comment by simison** [comment]
@vindl can you help triage this? Meanwhile I'll remove from maintenance backlog since it's related to ongoing projects.

**Comment by vindl** [comment]
> @vindl can you help triage this? Meanwhile I'll remove from maintenance backlog since it's related to ongoing projects.

We already landed several fixes in core that address this problem and it's no longer an issue on WP.com.
