### ISSUE TITLE
Gutenberg: Update install script to work with `svn copy` (if necessary)

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#48382]
@Automattic/good-mountain have updated our install process and corresponding Field Guide instructions (PCYsg-m14-p2) to make it `svn copy` based:

1. We first `svn copy` the previous plugin version folder to the next one.
2. We then replace it by the chosen Gutenberg plugin version (could come from a committish, too)
3. We `svn add` and `svn rm` files that have been added and removed, respectively, since the previous version.
4. Finally, we create a diff based on that.

The advantage of this process is that the diff that's generated by the last step only contains actual changes over the previous version, rather than a giant 'green' blob of added files and directories. The downside is that this is currently a rather manual process.

We should make sure that the install script that we were previously using can either still be used, or modified, to perform steps 2-4 on our behalf. (Step 1 -- `svn copy` -- will need to remain separate for the time being.)

To verify this, we need to generate one diff each for the manual process, and one for the automated process, and compare them to ensure that they're identical.

**Comment by fullofcaffeine** [comment]
The installation script is currently not aware of the WordPress plugins directory (https://downloads.wordpress.org/plugin/). It tries to get all releases from GitHub. I don't think this would be a problem though, as the releases should be identical*. However, the script uses the tag name as is, so the `v` will be part of the dir name. If the previous version was svn copied over to a directory without the `v`, then it will fail. 

To avoid adding logic to remove the `v` from the tag name, what we can do is to just svn copy the existing version over to `v<version>` when deciding to start using the script. 

I see it working like this:

1. If you pass a tag/committish that corresponds to a release on GitHub, then we check if there's an existing directory with the same name;
2. If so, we remove the dir and unzip the GB version to a new dir with the same name;
3. We then run the svn command to add any new files: `svn add $( svn st | egrep '^\?' | awk '{ print $2 }' )` and the one to remove old ones: `svn rm $( svn st | egrep '^!' | awk '{ print $2 }' )`;
4. Create the installation diff (which is something the installation script already does).

Let me know if you have thoughts! 🙇🏻

**Comment by fullofcaffeine** [comment]
WIP diff here: D54491-code

**Comment by ockham** [comment]
> The installation script is currently not aware of the WordPress plugins directory (https://downloads.wordpress.org/plugin/). It tries to get all releases from GitHub.

I think that's fine for now -- we can consider that later. If we decide to check the WP.org plugin repo first and to attempt fetching releases from there, that's definitely something we would need to handle separately. Tackling both in a single patch would unnecessarily increase complexity, and would make reasoning and testing much harder :sweat_smile: 

> I don't think this would be a problem though, as the releases should be identical*.

Looks like a footnote went missing here (because of the *)? The difference I can think of is that the WP.org plugin repo has a top-level `gutenberg/` directory in the zip that includes everything, whereas the releases obtained from Github don't.

> However, the script uses the tag name as is, so the `v` will be part of the dir name. If the previous version was svn copied over to a directory without the `v`, then it will fail.
> 
> To avoid adding logic to remove the `v` from the tag name, what we can do is to just svn copy the existing version over to `v<version>` when deciding to start using the script.

Yeah, that seems reasonable to me :+1: Another example of a change that if we ever decide to make it, we should tackle in a separate diff :+1: 

> I see it working like this:
> 
> 1. If you pass a tag/committish that corresponds to a release on GitHub, then we check if there's an existing directory with the same name;
> 2. If so, we remove the dir and unzip the GB version to a new dir with the same name;
> 3. We then run the svn command to add any new files: `svn add $( svn st | egrep '^\?' | awk '{ print $2 }' )` and the one to remove old ones: `svn rm $( svn st | egrep '^!' | awk '{ print $2 }' )`;
> 4. Create the installation diff (which is something the installation script already does).

Sounds perfect :+1: 

> Let me know if you have thoughts! 🙇🏻

Great decision making and project planning here! :+1:

**Comment by fullofcaffeine** [comment]
@ockham Thanks for the feedback! :) 

> Looks like a footnote went missing here (because of the *)? 

Ah yeah, apologies. I was going to point out that though while the releases should be the same, the final zip is slightly different depending on where you download them from:

The github plugin zip has the usual Gutenberg file/dir tree at its root:

```
$ ls                                                                                                                                    [system]
build  changelog.txt  gutenberg.php  gutenberg.zip  lib  packages  post-content.php  README.md  readme.txt  vendor                                                                                                                          [system]
```

The one from the WordPress plugin repository has the same files contained in an inner `gutenberg` dir at its root:

```
ls                                                                                                                                    [system]
gutenberg
```

This shouldn't affect the script, though.

**Comment by ockham** [comment]
> I was going to point out that though the releases should be the same, the final zip is slightly different depending on where you download them from:
> [...]
> This shouldn't affect the script, though.

I'm afraid it might :grimacing: On WP.com, we're currently loading `gutenberg.php` from the top-level directory; if it's wrapped in an additional `gutenberg/` folder, it'd break. So we'll have to account for that extra layer and remove it, if we add logic to fetch the plugin from the WP.org plugin repo. (Obstacles like these -- which can be hard to anticipate -- are one of the reasons why it's good to tackle that problem separately :wink: )

**Comment by fullofcaffeine** [comment]
There's a follow-up issue to simplify the script, see the last comment D54491-code.
