### ISSUE TITLE
Reduxify: Account password data

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#48404]
A simple `EventEmitter` store with a single usage ([source](https://github.com/Automattic/wp-calypso/blob/9c6883023ed216a74bd82fdf29f04409a381aa8f/client/lib/account-password-data/index.js)). 

FWIW, alternatively, it can also be refactored to use component state and not rely on Redux.

**Comment by flootr** [comment]
Gonna do this as a follow up to https://github.com/Automattic/wp-calypso/pull/48454
