### ISSUE TITLE
Store|Woo: Provide additional guidance once a Store customer starts using Woo Core

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wp-calypso#48420]
**User story:**
As a Store user
I want to easily access information about the Core interface once I transition from the old UI
So I can easily get adjusted to the new ui without going back to get more information

**Description:** we should make sure that we welcome the user when he arrives at the Core home screen and that he can easily access the support docs without going back to the Store UI

**Acceptance criteria:**
- [ ] Welcome the user when the arrives at the home screen for the first time (perhaps we can take advantage of the existing modal)
- [ ] Allow the user to easily access the support doc that we provide without going back to the Store UI (an inbox notification seems to be the best option)
- [ ] This should only target existing Store users. As the new ones should be automatically redirected to the Core UI once we start the sunset period (I'll open an issue about this)
- [ ] Should we have a way to allow customers to easily go back to the old UI? A CTA in an inbox message?

**Comment by pmcpinto** [comment]
cc @elizaan36 @becdetat

**Comment by becdetat** [comment]
I think inbox notifications are a good, relatively unobtrusive way to surface this info

**Comment by elizaan36** [comment]
here's one option in case we wanted to utilize the existing modal. 

![Welcome modal](https://user-images.githubusercontent.com/5121465/102929855-ff8e5800-4460-11eb-8d16-4de814df4e33.png)

Copy is TBD.

I think providing a nice welcome message could alleviate some concern about the change, but I'm not against using the Inbox message as well. I think it's a little easier to get lost if we drop people into the Home screen immediately with no intro.

**Comment by becdetat** [comment]
@elizaan36 @pmcpinto what are we doing about the inbox notification? Is it needed? I noticed there's copy for a notification in the final copy doc:
![image](https://user-images.githubusercontent.com/224531/103839970-4eccbd80-50dc-11eb-804a-f70a5c129978.png)

*edit* I just found this https://github.com/woocommerce/woocommerce-admin/issues/6008, I'll go ahead with that.
