### ISSUE TITLE
Remove inline Woo shipping labels payment management if it is unused

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#48421]
The `AddCardDialog` component in WooCommerce _might_ be unused. I am unable to find a way to test it. It seems that it may have at some point been replaced with a redirect to calypso's payment management pages, but the old code remains.

If I create a Woo Store and then click through to shipping labels and add a credit card, I'm redirected to calypso, not this dialog.

The recent payments management work refactors the code to add and change payment methods and it is important to make sure `AddCardDialog` still works correctly if it is used, or remove it if not.

https://github.com/Automattic/wp-calypso/blob/e2c0fece2adfb425525d4d2c1d3edb283b8602fd/client/extensions/woocommerce/woocommerce-services/views/label-settings/add-credit-card-modal.js#L23

Notably, we're migrating away from `PaymentMethodForm` (see https://github.com/Automattic/wp-calypso/issues/48966) and the only place left to use it will soon be `AddCardDialog`.

**Comment by michaeldcain** [comment]
@c-shultz can you help us confirm whether or not this component is being used?

**Comment by sirbrillig** [comment]
FWIW, `AddCardDialog` is rendered only by `ShippingLabels` (aka `LabelSettings`) here:

https://github.com/Automattic/wp-calypso/blob/aea1f65b4785f23ab36b44e5b06d5aec64b25478/client/extensions/woocommerce/woocommerce-services/views/label-settings/label-settings.js#L290

which appears to be rendered by `AccountSettingsRootView` here:

https://github.com/Automattic/wp-calypso/blob/aea1f65b4785f23ab36b44e5b06d5aec64b25478/client/extensions/woocommerce/woocommerce-services/views/label-settings/index.js#L55

Which in turn is rendered by `Shipping` here (`LabelSettings` is a different component here even though they have the same name):

https://github.com/Automattic/wp-calypso/blob/aea1f65b4785f23ab36b44e5b06d5aec64b25478/client/extensions/woocommerce/app/settings/shipping/index.js#L51

So it's definitely "used" in the sense that it's used in the code. I just can't find a way to activate it so I'm wondering if it's actually disabled in some unexpected (or expected) way.

**Comment by sirbrillig** [comment]
This is coming up again as we replace `PaymentMethodForm`. I'd love some guidance about how to test this component if it is in-use somewhere.

**Comment by c-shultz** [comment]
Hey @sirbrillig!

I believe this one is used on the Store on WP.com interface. The shipping features can either be accessed from wp-admin or Store on WP.com so some of the flows are only relevant to one of those. From wp-admin, the credit cards can't be managed directly, so it just jumps out to Calypso instead of opening that dialog.

I think you should be able to test that by going to Store > Settings > Shipping
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/6209518/104761777-3847e700-5718-11eb-80c0-1ae043f8fcd2.png">

**Comment by sirbrillig** [comment]
Thank you, @c-shultz! I got busy this past month with some maintenance work we've been doing and I haven't had a chance to circle back to this until now. I may be doing something wrong, or something may have changed in the time since you wrote the above instructions, but when I visit the Store link in calypso for an e-commerce site I have, I don't see any way to get to "Settings":

<img width="1157" alt="Screen Shot 2021-02-09 at 6 29 27 PM" src="https://user-images.githubusercontent.com/2036909/107442542-3ef23000-6b05-11eb-8a7e-d763265483e1.png">

I tried going to `/store/settings/example.com` and that seems to let me access the settings page, but I don't see a shipping labels section. I'm ashamed to show how little I know about Woo; is there something I need to set up in my store to be able to see that section?

<img width="1240" alt="Screen Shot 2021-02-09 at 6 36 14 PM" src="https://user-images.githubusercontent.com/2036909/107442921-de172780-6b05-11eb-8443-487f861c268d.png">


Also, if those warnings are correct, then all this might be going away in a month... if that's so then we might not need to convert that form to complete https://github.com/Automattic/wp-calypso/issues/48966 if it can eventually be deleted.

**Comment by c-shultz** [comment]
Hey again, @sirbrillig!

I feel your pain with getting Store to work correctly. Are you using a local site? The easiest route for testing it in my experience is with a test site on the WP.com business plan.

But all the setup issues aside, it looks like the deprecation could make any further investment in Store unnecessary at this point. I see @mattsherman on the associated P2 posts (and PR: https://github.com/Automattic/wp-calypso/pull/49017). Matt, can you weigh in on when it looks like Store will be totally disabled?

**Comment by sirbrillig** [comment]
Thanks for the link! I read the associated posts and it does look like the page I'm concerned about will no longer be needed on or around Feb. 22, in which case I can just forget about this issue again for another month 😜 and then I should be able to remove the last instance of `PaymentMethodForm` from calypso. (Although if @mattsherman has more details, they are welcome.)

**Comment by mattsherman** [comment]
Yes, I can confirm that our (team Mothra on Isotope) plan is to totally remove Store on Feb 22. 

We have an issue in our backlog to cleanup unused code after removal has been in production for a while. https://github.com/automattic/wp-calypso/issues/49433

Here's a P2 post with some more details on our removal plan: pbIJXs-Bt-p2

**Comment by sirbrillig** [comment]
I made https://github.com/Automattic/wp-calypso/pull/50491 to remove the label settings components entirely.
