### ISSUE TITLE
Store|Woo: Hide deprecated Store menu item for Business plan sites that have never used Store

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#48424]
If a site is created with the Business plan (or an existing site upgrades to the Business plan), and has never used Store, after the Store has been deprecated, the Store menu item in the My Sites sidebar should not be shown. Only the new WooCommerce menu item should be available.

From pbIJXs-sE-p2:

>> What happens when sunset is in effect (prior to complete removal of Store) and a new Business customer signs up? I assume they should only get the WooCommerce Core experience, right?
> 
> Yes, that’s correct. 

Acceptance criteria:

- A site with a Business plan subscription after Store is deprecated must not have the Store menu item available
- A site with a Business plan subscription before Store was deprecated must have the Store menu item available
- A site with the eCommerce plan must have the Store menu item available

**Comment by mattsherman** [comment]
How do we determine if Store has been used?

- The simplest solution might be to just check if the WooCommerce plugin is activated
    - If it is, then they likely (tried to) use Store, so should still show it.
    - If it isn't, then they definitely never used Store (at least, they never got through installing plugins), so should not show it. This is the case both for brand new Business sites created after deprecation of Store, as well as existing Business sites that haven't yet installed any plugins (and therefore were not Atomic/eligible for Store).

@pmcpinto @becdetat Do you think this approach is sufficient for our purposes? I feel like this would satisfy 99% of cases out there, and would be trivial to implement.

**Comment by becdetat** [comment]
That would change the AC to:

- A site with WC activated should show the store link during the sunset period
- A site without WC activated should *not* show the store link during the sunset period

Correct?

But isn't that the same as already implemented?

**Comment by mattsherman** [comment]
> That would change the AC to:
> 
>     * A site with WC activated should show the store link during the sunset period
> 
>     * A site without WC activated should _not_ show the store link during the sunset period
> 
> 
> Correct?

Yes, though "WC activated" is a bit of a technical detail.

> But isn't that the same as already implemented?

No, it actually isn't. Currently what is implemented always shows the Store during the sunset period for a Business site, as long as it is Atomic. We haven't yet made any changes to the implementation of the Store menu item. This issue will be one such change. The other change will need to be in a future (at sunset? or, post sunset?), when we decide to fully get rid of the Store menu item completely.

**Comment by becdetat** [comment]
Ok I understand. Sounds good to me then :-)

**Comment by pmcpinto** [comment]
> @pmcpinto @becdetat Do you think this approach is sufficient for our purposes? I feel like this would satisfy 99% of cases out there, and would be trivial to implement.

@mattsherman how do you make sure that we don't target customers that are using the Core WooCommerce UI with this approach?

**Comment by mattsherman** [comment]
> @mattsherman how do you make sure that we don't target customers that are using the Core WooCommerce UI with this approach?

Business customers using the Core WooCommerce UI will have the new WooCommerce menu item available. And, eCommerce customers will continue to have the existing Store menu (that for them, goes to WooCommerce Core). I'll add acceptance criteria to make it clear that eCommerce customers should continue to have the Store menu.

**Comment by pmcpinto** [comment]
👍 thanks for the clarification

**Comment by mattsherman** [comment]
This is a bit trickier than it initially seemed...

Detecting whether a site has used the deprecated Store is difficult, since we don't have any indication of this in place before the deprecation.

Perhaps the best solution would be to hook into when new Business sites are created, and if in the Store is deprecated, set a site option such as `calypso_hide_deprecated_store` to `true`, so that when the My Sites sidebar is rendered, we can check that and hide the Store for new Business sites.

I *think* this might be where we can hook into things...

https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/signup/step-actions/index.js#L259
