### ISSUE TITLE
Payments block: Making the Subscribers management option more visible

### ISSUE THREAD

**Issue by dromero20** [Automattic/wp-calypso#48446]
#### Steps to reproduce

1. Create a Payments Block and have some customers to subscribe to your services.
2. Go to the Subscribers page: https://wordpress.com/earn/payments/
3. The list of subscribers is there (this is okay) but the 3 dots to manage them are very faint and not visually nice.

<img width="1045" alt="Captura de pantalla 2020-12-17 a las 10 25 43" src="https://user-images.githubusercontent.com/23258551/102468811-4c81c100-4052-11eb-98c5-23a81c9d3f5d.png">

There are some customers contacting us about this - They want to cancel some subscriptions and can't find the way to do it. Is there a way we could make those 3 dots more visible, with a darker color?

Thanks!

**Comment by inaikem** [comment]
Closing in favour of #43227
