### ISSUE TITLE
Error during delay when opening the editor for a Jetpack post in Calypso with SSO on in Jetpack Settings and if logged out of WP Admin (Chrome only)

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#48478]
#### Steps to reproduce

1. Go to /wp-admin/ for a Jetpack site and log in if prompted.
1. Go to WP Admin > Jetpack > Settings.
1. Enable the first setting in the "WordPress.com login" section (aka turn on SSO).
1. Clear browser cache.
1. Go to WordPress.com and log in as the Jetpack-connected user.
1. Go to My Sites > Posts > Add new post.
1. Observe an error and a delay happens before the editor opens.
1. Log in to the Jetpack site.
1. Go back to WordPress.com > Sites > Posts > Add new post.

Note: I tested with Chrome 87 and Firefox 84 and the disconcerting error only shows up in Chrome, it must be a default of some kind but still we should try to stop it from happening!

#### What I expected

I expected to be able to log in to WordPress.com and edit or create posts on my Jetpack-connected site without seeing an error or a large delay.

#### What happened instead

If I have Single Sign-on enabled and I am logged out of WP Admin on the Jetpack site, I see an ugly error saying "refused to connect" and a delay before posts can be opened.

#### Browser / OS version

Chrome 87 / macOS 10.15.6

#### Screenshot / Video

Video: [1m52s](https://cloudup.com/c2B1Qm7d4fS)
<sup>Tested using Chrome 87.0.4280.88 on macOS 10.15.6 with a WordPress 5.6 Jetpack 9.2.1 site footed-loon.jurassic.ninja and using the Jetpack-connected WordPress.com account testuser0313.</sup>

![refused-to-connect](https://user-images.githubusercontent.com/1119271/102565993-c8ecc200-409b-11eb-8fd3-6f82d0569759.png)

#### Context / Source

Found some related problems while #beta-testing WPDesktop 6.7.0-beta1 and decided to see how editing posts was working in Calypso, and found some problems here as well.

**Comment by Greatdane** [comment]
Closing this as unable to replicate. While I do get quite a long pause (over 2 seconds) in between clicking 'add page' and the page actually loading. 

Also noticed in the video you are using incognito mode, and the error refers to SU session, so it could be related to this.
