### ISSUE TITLE
Nav Unification: Jetpack plans obscure the flyouts

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#48490]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/plans/
2. Select a Jetpack Site
3. Resize browser to 1400px width
3. Hover a menu

#### What I expected
The flyouts being clearly visible

#### What happened instead
Main Pane covers the flyouts
![](https://cln.sh/wx4ZP8+)

**Comment by michaeldcain** [comment]
It looks like some items on the Jetpack "My Plans" page and the non-Jetpack "Plans" page also have z-index issues:

<img width="834" alt="Screen Shot 2020-12-28 at 10 28 35 AM" src="https://user-images.githubusercontent.com/942359/103226019-2fbe7680-48f9-11eb-81ec-0dac30704f49.png">
<img width="1062" alt="Screen Shot 2020-12-28 at 10 29 28 AM" src="https://user-images.githubusercontent.com/942359/103226062-4238b000-48f9-11eb-96f3-32fb9fe42d65.png">

**Comment by michaeldcain** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/48143
