### ISSUE TITLE
Color schemes: form toggles have hard-coded colors

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#48509]
Using the 'modern' color scheme I see that form toggles do not use the 'primary' color variable and instead maintain the default wpcom blue:

![image](https://user-images.githubusercontent.com/437258/102660748-8ed9f980-4149-11eb-8ca1-e4ff649f96b9.png)

I couldn't figure out where the color is applied, but it seems like it should be swapped for the primary variable instead of a specific color.

**Comment by sixhours** [comment]
The colors for form toggles get set in the `@wordpress/components` package, so we'd probably want to do something like this in our stylesheets to override it:

```
/* @wordpress/components Form toggles use the color scheme's background color */
.components-form-toggle.is-checked .components-form-toggle__track {
	background-color: var( --color-primary );
}
```

<img width="1390" alt="Screen Shot 2020-12-18 at 4 26 21 PM" src="https://user-images.githubusercontent.com/2124984/102662992-f003cc00-414d-11eb-9b38-70902bcfc576.png">
<img width="1396" alt="Screen Shot 2020-12-18 at 4 26 39 PM" src="https://user-images.githubusercontent.com/2124984/102662998-f1cd8f80-414d-11eb-89bf-3eb4d0e037e2.png">
<img width="1382" alt="Screen Shot 2020-12-18 at 4 27 02 PM" src="https://user-images.githubusercontent.com/2124984/102663002-f3975300-414d-11eb-8eb1-2ab12503c98c.png">

**Comment by rickybanister** [comment]
I think this is completely unrelated to your css, but why is it possible for a parent toggle to be off, but the children are on+disabled?

I think we have a regression somewhere? The children should be in the off-state and disabled in the above examples, no?

**Comment by sixhours** [comment]
> I think we have a regression somewhere? The children should be in the off-state and disabled in the above examples, no?

Good question, I'm not entirely sure. @jeherve Do you know offhand, since this is a Jetpack settings screen, why the parent toggle could be off but the children could be on?

**Comment by jeherve** [comment]
> Do you know offhand, since this is a Jetpack settings screen, why the parent toggle could be off but the children could be on?

I'm afraid I don't know, but I see I'm late to the party and you already have a PR ready for this. Sorry for the delay!
