### ISSUE TITLE
Editor: Form Builder: Checkbox with multiple items option is missing

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#4850]
#### Steps to reproduce
1. Go to Pages > All Pages in wp-admin
2. Pick a page, open it in the post editor.
3. Click to add a new form, add a few fields
4. Create a field using the "Checkbox with multiple items" option.
5. Save your changes.
6. Go to WordPress.com/pages/
7. Pick the page you just edited, open it in the Calypso editor.
8. Edit the form.
9. Edit the "Checkbox with multiple items" field.
10. The field is empty as that option doesn't exist in the Calypso form builder.

![modifier_la_page_ _site_internet_ _wordpress_com](https://cloud.githubusercontent.com/assets/426388/14641157/2a513a76-0645-11e6-9451-81b71e9af35b.jpg)

For reference, this option was added to WordPress.com in r131234-wpcom. Related Jetpack change: https://github.com/Automattic/jetpack/pull/2806

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue.  Note that the field type dropdown is empty here, when it should be 'multi select checkbox':

<img width="535" alt="screen shot 2016-07-18 at 2 02 32 pm" src="https://cloud.githubusercontent.com/assets/7233112/16925049/55707cb6-4cf0-11e6-9cad-2a1fdab29bbc.png">

**Comment by rachelmcr** [comment]
Confirmed this is still an issue.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated](https://github.com/Automattic/wp-calypso/milestone/309?closed=1), I don't think this issue is relevant any longer. But please feel free to re-open it if that's incorrect.
