### ISSUE TITLE
Desktop App: "Included with your purchase" section never appears in the cart when purchasing a plan

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#48517]
Steps to reproduce:

1. Open the Desktop App, log in, open a free site.
1. Go to Plans > Business site and online stores > eCommerce > Upgrade.
1. Observe that no info ever appears under the Included with your purchase" section at top right. ([1m11s](https://cloudup.com/chN2QvgBxAe))

<img src="https://user-images.githubusercontent.com/1119271/102668926-73bbb980-414a-11eb-9750-136dabc9701d.png" width="600" alt="included-with-your-purchase-via-wpdesktop-6 7 0-beta2">
<sup>Tested with WPDesktop 6.7.0-beta2 on macOS 10.15.6.</sup>

The following error appeared in the developer console for the app around the same time, but I am not sure whether it's relevant.

> GET https://s3.amazonaws.com/ki.js/17790/5-f.js net::ERR_ABORTED 403 (Forbidden)
> madefortesting1218.wordpress.com/:345

<img src="https://user-images.githubusercontent.com/1119271/102668811-22132f00-414a-11eb-9dbb-052a7b3b9609.png" width="600" alt="console">
<sup>Developer console window from WPDesktop 6.7.0-beta2 on macOS 10.15.6.</sup>

For comparison, I tested the same steps on the web and the section is filled in properly there.

<img src="https://user-images.githubusercontent.com/1119271/102668822-2b9c9700-414a-11eb-810c-26a88d632abc.png" width="600" alt="included-with-your-purchase-via-web">
<sup>Tested with Firefox 84.0 on macOS 10.15.6.</sup>

**Comment by nsakaimbo** [comment]
This bug seems to apply to all existing checkout flows and is definitely a regression. The `http` Stripe warning certainly seems suspicious.

**Comment by nsakaimbo** [comment]
I just did a little testing and seems this bug was present in the prior releases v6.6.0 and v6.5.0. The checkout flow works as expected in v6.4.0, meaning the regression was introduced some time since then. This will be useful information when git bisecting to try to isolate the cause of the regression.

**Comment by nsakaimbo** [comment]
So after some bisecting I was able to determine that the regression was introduced by PR #47265 (sha f618169de1061f2e1575485bbb4250eaac471336), which includes some changes to the checkout flow. I confirmed that the commit immediately before this one (110d169e89) does _not_ have this issue.

@taggon Could you please assist in troubleshooting this regression? TL;DR: it seems PR #47265 introduced made it so the checkout UI in the wp-desktop app was broken. Let me know if you need any assistance building the desktop app for debugging (instructions to build the app [here](https://github.com/Automattic/wp-calypso/blob/trunk/README.md), and exposing debugging tools [here](https://github.com/Automattic/wp-calypso/pull/48189)).

**Comment by felipevelzani** [comment]
I was still able to reproduce it while using macOS Big Sur 11.1 - WordPress.com app 6.8.0-beta1. 

It just stays endless loading it: https://d.pr/i/AP8UPL

**Comment by nsakaimbo** [comment]
Thanks for testing, @felipelousantos! This fix isn't available in 6.8.0 yet - it will be available in 6.9.0.
