### ISSUE TITLE
Editor: Form Builder: can't reorder fields

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#4851]
In the old form builder in wp-admin, it is possible to reorder fields once you've created them:

![screen shot 2016-04-19 at 3 47 16 pm](https://cloud.githubusercontent.com/assets/426388/14641328/0211fc52-0646-11e6-838e-6399506a0d19.png)

It would be nice if that option were added to the Calypso editor as well.

**Comment by rachelmcr** [comment]
Confirmed that contact form fields still can't be reordered in Calypso (only edited/deleted):

<img width="561" alt="screenshot 2018-01-02 15 48 42" src="https://user-images.githubusercontent.com/8658164/34501410-799212fc-efd4-11e7-9332-c2c79affbbb4.png">

#bug-scrub #pre-gutenburg-bug-purge

**Comment by designsimply** [comment]
This came up again in a P2 discussion (p4k3M4-2uX-p2). #dogfooding #painpoint

Here are some steps to try out that will help build empathy for this issue:

1. Go to https://wordpress.com/ > My Sites > Pages > Add > Contact Form.
1. Add 5+ form fields.
1. Move the field in the 8th position to the 1st position.
1. Update the entire list to reverse the order.

<strong>Result:</strong> form fields need to be deleted and recreated to change the order and it's time consuming even for a small set of fields.

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated](https://github.com/Automattic/wp-calypso/milestone/309?closed=1), I don't think this issue is relevant any longer. But please feel free to re-open it if that's incorrect.
