### ISSUE TITLE
Video block on wpcom: iframe forces inline height/width, ignores alignment in editor

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#48524]
#### Steps to reproduce

1. Starting at URL: Any Simple wpcom site, but also AT when I tested.
2. Add a new page/post
3. Add a video block, set to ~full width, or wide width~ ANY alignment. Insert video
4. Publish, check published page.
5. Result: video not full width/wide width/left-aligned/right-aligned, source code indicates inline width/height values for the iframe/video element (observed with both) and the L/R margins seem to be set to auto?

I tested this on a jurassic ninja site with Twenty Twentyone and it's totally fine, no inline attributes and no alignment issues. On my test sites, I'm using Seedlet, and on the user reported site, they were using Dalston. Dalston is still a child theme of Varia, while Seedlet is a parent theme, so I don't think this is theme-dependent.

#### What I expected
A nicely full-width or wide width video.

#### What happened instead
Not a nicely full-width video.

#### Browser / OS version
Firefox 84 on Mac Mojave 10.14.6 (don't judge me I'll update soon) 
From the user - Chrome 87.0 on Windows 7.0.0

#### Screenshot / Video
The editor:
![fullwidthvidblock](https://user-images.githubusercontent.com/36608681/102707897-3f0d4680-429f-11eb-8a2e-a59516032c68.png)

The result (Simple site):
![vidblockattr](https://user-images.githubusercontent.com/36608681/102707969-c5298d00-429f-11eb-8922-6987e290b201.png)

The result (AT site also using Seedlet):
![atvidattr](https://user-images.githubusercontent.com/36608681/102708179-51887f80-42a1-11eb-83bd-b8ae05856a5c.png)

#### Context / Source

 #painpoint  #user-report from 26460405-hc

**Comment by Greatdane** [comment]
Closing this. I am able to align videos via editor that shows on live site;

<img width="1280" alt="Markup 2021-09-23 at 15 10 17" src="https://user-images.githubusercontent.com/5075840/134461545-81757135-d6be-4d0a-8146-be9d0c27ae99.png">
