### ISSUE TITLE
Alves - Videos from Media library do not go Full Width in Video Block

### ISSUE THREAD

**Issue by openfist** [Automattic/wp-calypso#48521]
#### Steps to reproduce

1. Starting at URL: bodychoice.org
2. go to front page 
3. All 3 videos on this page is from media library
4. In Editor of front page video block settings are at full width. And the editor does show the videos as full width
5. But, the live site will not output the videos as full width and it seems the Videopress system will give it default dimensions

#### What I expected
- videos to be full width

#### What happened instead
- live site, videos do not show full width 

#### Screenshot / Video

![Screen Shot 2020-12-19 at 06 49 43](https://user-images.githubusercontent.com/11617249/102693016-6db10000-4252-11eb-8a38-37b10d127d41.png)
#### Context / Source

#alves #videopress #videos #videoblock

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by sophiegyo** [comment]
Ah, I just opened another issue for this - it's showing up in more than one theme so I had opened it as a general block issue: #48524

**Comment by synora** [comment]
Bug, Blocks, VideoPress, Triaged, Themes labels added. Will hold off on merging with https://github.com/Automattic/wp-calypso/issues/48524 until a dev looks into this.

**Comment by Greatdane** [comment]
Similar to https://github.com/Automattic/wp-calypso/issues/48524, I am unable to replicate this.

Can make the video full width in Alves theme;

![Markup on 2021-09-23 at 15:14:36](https://user-images.githubusercontent.com/5075840/134461847-4242326f-eb0c-4069-9464-053afef41aab.png)

Closing
