### ISSUE TITLE
Paragraph block: inline styling for `mark` elements stripped out

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#48536]
#### Steps to reproduce

1. Create a post
2. Type some text in a paragraph block
3. Edit block as HTML, and wrap some text in `<mark></mark>` tags.
4. Add a `style` attribute and set a custom background color
Example: `<p>This is <mark style="background-color:red;">some</mark> text</p>`
5. View published post
6. Leave the editor and then open the post again for editing, and check HTML

#### What I expected
For the text to be highlighted in the custom color I'd added in the `style` attribute.

#### What happened instead
On the published post the text is highlighted in the default yellow color based on the browser's built-in styles

On leaving the editor and reopening it, the `style` attribute has been stripped from the `mark` element.

This issue appears to be specific to WordPress.com - on a self-hosted WordPress site this works as expected, so I'm guessing this might have to do with the safe-list we maintain for what HTML tags and attributes can be used on WordPress.com, rather than an issue with the editor itself, so this is more of an enhancement request than a bug report - until text highlighting is natively added in the block editor, can we at least ensure that WordPress.com site owners can use all the HTML tags and attributes that allow them to do this manually?

#### Context / Source

Discovered while testing a solution for a user question in https://wordpress.com/forums/topic/redacting-text/.

**Comment by inaikem** [comment]
Scrubbed request. I have confirmed the `style` attribute is removed on Simple sites but retained on Atomic and self-hosted sites.

I expect this is intentional - especially on Simple site plans which don't permit custom CSS. 

@simison, can you see the use of `style` in the code editor ever making it to Simple sites?

**Comment by simison** [comment]
Yes, we will need this for https://github.com/WordPress/gutenberg/pull/34680

I gave Team Calypso heads up earlier this week. Cc @fullofcaffeine

**Comment by inaikem** [comment]
Thank you!

**Comment by KokkieH** [comment]
@inaikem 

> I expect this is intentional - especially on Simple site plans which don't permit custom CSS.

We've never blocked the use of inline styles on free sites, and it works for, e.g. `<span></span>` tags.

**Comment by KokkieH** [comment]
This has been fixed in D68544-code (also related to #57036), so closing this issue.
