### ISSUE TITLE
Jotform Embeds: cannot submit a form

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48548]
This was already reported in https://github.com/WordPress/gutenberg/issues/27819 but I think it makes sense to also check on the WordPress.com side as it might break several embeds on our end.

#### Steps to reproduce

1. Go to Jotform and create a form
2. Get the Jotform link that looks like https://form.jotform.com/123456789876543210
3. Paste it in a new line in the editor and publish the page/ post
4. Visit the page and attempt to submit the form

Note as well that I tried the shortcode option on a WordPress.com site but it was the same result https://www.jotform.com/help/299-how-to-embed-a-form-to-wordpresscom

#### What I expected
I expected the form to submit successfully.

#### What happened instead
The form is stuck on "please wait" upon submission:

#### Context

* #user-report 3584890-zen
* Internal: p1608672834128600-slack-C03TY6J1A
* Jotform support ticket: https://www.jotform.com/answers/2775518-Jotform-WordPress-forms-do-not-submit

**Comment by cathymcbride** [comment]
There's a workaround provided by jotforms and the gutenberg issue is already closed.  I'm not going to close this, but I am going to lower the priority.

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING

- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING

- Tested on P2 - Did not try
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO

- Can reproduce the bug on simple, Atomic and WordPress.org
- iframe embed as suggested by Jotform team works as expected on a WordPress.org site. On Atomic too.
- Asked them for help with embed troubleshooting though (not iframe)

📌 ACTIONS

- We could close this, as this feels more like a Jotform  issue now.
- Let's wait for two more weeks before closing.

📌 Message to Author

None.

**Comment by jordesign** [comment]
No more reports in a month - so I'm happy to close this for now. It will still be findable un Bugomattic searches and can be re-opened if needed.
