### ISSUE TITLE
Signup: Create New WordPress flow essentially unusable if you already have sites

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#4855]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Click "My Sites"
3. Click "Switch Site"
4. Click "Add New WordPress"

#### What I expected
The blog creation flow would commence without interference from other page elements.

#### What happened instead
The page forwards to /start/themes, but the theme chooser is rendered behind the stats view, like so:

![screen shot 2016-04-19 at 10 59 53 am](https://cloud.githubusercontent.com/assets/2738252/14643826/e0198d40-061d-11e6-83f6-90d847a2746e.png)

The page title also reads "Create an account" which is weird since I'm logged in.

I can click a theme to pick sort of blindly, but then the next step also occurs behind the stats view. I had the same experience when switching sites from other (non-stats) views, and the same overlap occurred. So it's not specific to the stats view but seems to be an issue with the blog creation flow itself.

This seems like a pretty bad bug that's probably making blog creation pretty difficult for people who already have sites with us.

#### Browser / OS version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by dllh** [comment]
To complete the blog name creation, I had to go into the browser inspector, find the stats div, and add `display:none` to it so that I could interact with the page beneath.

**Comment by seear** [comment]
Fixed by reverting #4820
