### ISSUE TITLE
 Nav Unification: Settings Link in Simple Site links to a miscolored WP-Admin

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#48552]
Tested as part of a CFT paYJgx-1eA-p2

This is slightly related to **Nav Unification: Settings Link in Calypso goes to WP-Admin**  https://github.com/Automattic/wp-calypso/issues/48183 but specifically identifies the mixed color scheme.

#### Steps to reproduce

1. Starting from a **simple site**'s home, e.g., https://wordpress.com/home/{your_site}.wordpress.com
2. Click on settings

#### What I expected
The unified, narrower nav to appear, and the color scheme to match Calypso's.

#### What happened instead
I see the older, wider nav and the color scheme isn't being applied to the navigation.

<img width="881" alt="Screen Shot 2020-12-23 at 9 51 05 am" src="https://user-images.githubusercontent.com/6458278/102941432-cd373600-4506-11eb-82c8-e21b3754e0ed.png">

#### Screenshot / Video
![Dec-23-2020 10-00-19](https://user-images.githubusercontent.com/6458278/102941324-8c3f2180-4506-11eb-8a2b-dd40f5b15e0e.gif)

#### Related issues
**Nav Unification: Settings Link in Calypso goes to WP-Admin** 
https://github.com/Automattic/wp-calypso/issues/48183

**Comment by cpapazoglou** [comment]
Thanks for reporting. 

The fact that you have been redirected to `wp-admin` instead of seeing the Calypso settings screen we will address it here https://github.com/Automattic/wp-calypso/issues/48183

What you see when you land to `wp-admin` is calypsoify (making wp-admin look like calypso) which will be disabled prior to launching nav-unification and thus we haven't covered these cases.

@davemart-in are we on track with turning off Calypsoify?

@obenland, should we append `calypsoify=0` to all `wp-admin` links to force disable it as hacky temp fix?

**Comment by davemart-in** [comment]
> are we on track with turning off Calypsoify?

We are not. It was paused to work on Anchor.fm. @obenland, @creativecoder, @kwight thoughts on the best course of action for prioritizing the disabling of Calypsoify amidst all of the other stuff we're working on?

**Comment by kwight** [comment]
> thoughts on the best course of action for prioritizing the disabling of Calypsoify amidst all of the other stuff we're working on?

I wouldn't want to add it to our mix now at all, no – and @cpapazoglou 's suggestion of `calypsoify=0` sounds like a great idea to me in the meantime. 👍

**Comment by obenland** [comment]
Would disabling it from loading cause any harm? D54901-code

**Comment by creativecoder** [comment]
> thoughts on the best course of action for prioritizing the disabling of Calypsoify

@pablinos recommended disabling it when nav unification is turned on--that seemed like the best way to proceed

> A way forward for launching Nav Unification might be to unset the user meta value and the Calypsoify cookie, if present, when the unified navigation is enabled for a user. This way the parts of the system that rely on Calypsoify can carry on using it, but the new navigation won’t be affected.
> from [Disable Calypsoify Summary](pbAPfg-15U-p2)

---

> Would disabling it from loading cause any harm? D54901-code

I think that might work for Simple sites! Would need to check Gutenboarding and Gutenframe, as I'm not sure if there are implications for disabling the Calypsoify module wholesale in those contexts.

I think we'll also need to find the equivalent for the Jetpack Calypsoify module, which works a bit differently.

**Comment by obenland** [comment]
> I'm not sure if there are implications for disabling the Calypsoify module wholesale in those contexts.

Is this something you could help us find out?

**Comment by creativecoder** [comment]
@obenland I can... to be clear all I'm thinking of at this point is applying your diff and poking around, comparing side-by-side to see if anything looks amiss.

**Comment by obenland** [comment]
@shaunandrews just reported a Calypsoify bug from the Jetpack-side (p1610124919398500-slack-CJS75TX3R), so D54901-code would have to be replicated in Jetpack or wpcomsh as well.

**Comment by mmtr** [comment]
This should be fixed by:
- D55269-code (Simple sites)
- https://github.com/Automattic/jetpack/pull/18328 (JP and AT sites running the next release of Jetpack).
- 578-gh-Automattic/wpcomsh (JP and AT sites running the current release of Jetpack)
