### ISSUE TITLE
Gutenboarding: Signup fails when site title is invalid

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#48566]
When trying to signup in Gutenboarding flow, the API call to create an account `https://public-api.wordpress.com/rest/v1.1/users/new` returns code 400 with this body:
```
error: "username_invalid"
message: "Sorry, but your username can't contain the phrase "wordpress"."
```

There are some suggestions for how to tackle this in https://github.com/Automattic/wp-calypso/pull/48430#issuecomment-748148625

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/new while being logged out from your account.
2. Enter `{SOME_TITLE}.wordpress.com` as the site title.
3. Complete the flow and try to "Save your progress" by signing up.

#### What I expected
* If the site title is not a valid username, I expect to be asked for a valid one or to get a temporary one that can be derived from my email address or just random.

#### What happened instead
* Account creation failed with message "Sorry, something went wrong when trying to create your account. Please try again."

#### Screenshot / Video
https://cloudup.com/cpMFbHW4ptl

#### Context / Source
This issue may seem related to #48547 because they share the same cause at least from user perspective (entering an invalid site title). But the API calls that are failing are different (account creation vs site creation).

**Comment by allilevine** [comment]
Possible back-end solution here: D54613-code

**Comment by allilevine** [comment]
Deployed D54613-code
