### ISSUE TITLE
Signup: no sites placeholder persists in site creation

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#4856]
#### Steps to reproduce
1. Create a user only account
2. Click My Site
3. Notice empty state My Site placeholder: "you have no sites yet > create one"
4. Click call to action to create a new site
5. Note that the empty state placeholder persists as background throughout signup flow.

Should always show default signup background while in signup flow unless we have specific and purposeful other variations.

![](https://cloudup.com/clKUOjLgco5+)

**Comment by seear** [comment]
May be related to #4820, looking into it.

**Comment by seear** [comment]
Fixed by reverting #4820
