### ISSUE TITLE
Signup: styling for site creation checklist

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#4857]
Since number of steps in site creation can vary, we'll either want to set a min height & vert alignment rules for contents of the checklist, or use the updated styles in the older layout, which handles different sized lists a bit better.

3 items in list:
![](https://cloudup.com/cY_RWzk9-8Y+)

1 item in list (user only flow):
![](https://cloudup.com/cD_bnRyEFdu+)

**Comment by melchoyce** [comment]
Just saw this as well.
