### ISSUE TITLE
Plans: implement a notice for users who have not used their domain credit

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4858]
This is meant to address churn. When we have users that have a premium or business plan that have not used their free domain credit, we should show them prominently that they should add a new domain.

I'm not sure the best place to show this... possibly a notice on the site card... maybe in settings, maybe in the domains page... maybe all of these.

I would consider this an overall beneficial feature to the user, so I would not do a 50/50 split test. But it would still be helpful to track whether we have an impact on retention/churn. So maybe we could do a longer-running test with 95%--5%, where we keep a small percentage as a control to determine if we can impact churn rates.

**Comment by mtias** [comment]
Yes, I'd like to leverage site-indicator for this with the redesign @rickybanister @folletto and I did:

![image](https://cloud.githubusercontent.com/assets/548849/14645770/46f83988-0657-11e6-9d31-5de768f9306f.png)
