### ISSUE TITLE
Store|Woo: e2e tests failing for Store removal

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#48588]
**THIS NEEDS TO BE RE-SCOPED**

The following e2e tests in `wp-woocommerce-spec.js` will fail when the config flag `woocommerce/store-removed` is set to `true`:

- Can see WooCommerce products in Calypso
- Can add a new WooCommerce product in Calypso
- Can see WooCommerce orders in Calypso
- Can see WooCommerce settings in Calypso

Ideally, rather than just remove these tests, I think it's better to add new tests to reflect the changes made to store removal. Some of the tests should include:

- [ ] Display of store removal notice
- [ ] Sidebar links

**Comment by mattsherman** [comment]
Using the scale of ideal dev days, I'm updating the estimate on this to 1 (also keeping in mind that there is already a PR ready for it!). @ilyasfoo, if you feel differently, please update estimate and let me know!

**Comment by ilyasfoo** [comment]
Yes, I agree with that estimate 👍

**Comment by mattsherman** [comment]
https://github.com/Automattic/wp-calypso/pull/50070 removed the `wp-woocommerce-spec.js` file.

I agree that we should have e2e tests for the Store removed behavior. I don't think this is a blocker to launching Store removal though. We should add these back once we launch.

**Comment by mattsherman** [comment]
Moving this back to "Needs Scoping" and assigning myself to clean this up and make sure it is clear what we should now do.

**Comment by ilyasfoo** [comment]
Oops, left this unattended for a while. That'd be great @mattsherman, thanks!

**Comment by ilyasfoo** [comment]
Closing this as no longer relevant
