### ISSUE TITLE
Notifications panel not showing history

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#48597]
#### Steps to reproduce

1. When logged in, click notifications bell
2. try to scroll down on list
3. check console for errors

#### What I expected
The panel would show a running list of notifications, including previous days that you can scroll through

#### What happened instead
only the last 9 are shown and you cannot scroll
in the console have the following error message: 
```
?v=2.0:6 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
```

#### Screenshot / Video
<img width="598" alt="errors" src="https://user-images.githubusercontent.com/47717887/108839524-da8fa000-75dd-11eb-8af5-a15fc830bc00.png">

#### Context / Source
#user-report 
#3597213-zd

**Comment by kylemcph** [comment]
Just noting user came back to report that they aren't 100% sure when this happened, however, probably yesterday.

**Comment by tbradsha** [comment]
Confirmed that this still appears to be an issue: when I log into their account, I only see four notifications (three today, and one from yesterday.

**Comment by ivan-ottinger** [comment]
Hey everyone, the user came back for an update. Do we have any news on this issue? Thank you.

**Comment by jordesign** [comment]
I'm not sure if this is different behaviour - but when I check I am unable to see any notifications at all for this user.

**Comment by obenland** [comment]
Just accessed this in Firefox and Chrome and notifications seems to load fine in both. @jordesign @tbradsha Is this still something you can reproduce?

**Comment by jordesign** [comment]
Hey @obenland - I can check again shortly but when I checked yesterday the issue was still occurring in Chrome for me. To be clear though - this is specifically when logged in as the user from the report - not widespread

**Comment by tbradsha** [comment]
Yes, today for that user, the "All" section only has 5 notifications:

![image](https://user-images.githubusercontent.com/32492176/106900827-3b4d4c00-66b4-11eb-8b67-cb6922b72aab.png)

**Comment by ahmadbaig1** [comment]
Reported here as well #3718019-zd .

**Comment by Robertght** [comment]
I cannot replicate this anymore, so I'll close it, but please reopen it if other cases arise.
