### ISSUE TITLE
Nav Unification: escaped HTML visible in Dashboard > Updates

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#48607]
#### Steps to reproduce

- On an Atomic or Jetpack site with updates available, visit Calypso:
- Hover over "Dashboard" menu item
- "Updates" sub-menu item includes escaped update count (even if 0)

#### What I expected

- Count should be shown as a badge when not equal to 0
- Count should be hidden when equal to 0

#### Screenshot / Video

<img width="442" alt="Screen Shot 2020-12-28 at 1 30 31 PM" src="https://user-images.githubusercontent.com/942359/103236043-ab2c2200-4911-11eb-9b64-17a4ea8ef0ba.png">

**Comment by cpapazoglou** [comment]
@michaeldcain this if fixed for me now, can you check also please?

![](https://cln.sh/WQ4bv2+)

**Comment by michaeldcain** [comment]
@cpapazoglou: this still seems to be an issue on the site from the screenshot, but if you're not able to reproduce it, I'm fine with keeping this closed.

**Comment by obenland** [comment]
Are you running Bleeding Edge or Release Candidate from Jetpack Beta on it? It should be fixed with https://github.com/Automattic/jetpack/pull/18063

**Comment by michaeldcain** [comment]
@obenland: that's probably it. I'm running whatever's default with Atomic :)
