### ISSUE TITLE
Columns Block: Needs a way to pull content out of the columns.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#48627]
#### Steps to reproduce

1. Create a page, and add a Columns Block to it. As many columns as you'd like.
2. Add some content to those columns.
3. Change your mind, and decide you no longer want columns.
4. Everything you've added to the Columns Block (whether added to Columns intentionally or not - and this happens with some frequency in a single column) must be recreated manually outside of the columns block. There isn't a way to get the content outside of the Columns.

#### What I expected
An easier way to move content outside of the Columns Block, instead of having to recreate everything that was added to it.

#### What happened instead
Content added to a Columns Block must stay within that columns block, or would need to be recreated manually.

#### Browser / OS version
All

#### Context / Source

#empathy #user-report #painpoint

**Comment by ramonjd** [comment]
> Change your mind, and decide you no longer want columns.

Do you think adding a paragraph or list [transform](https://developer.wordpress.org/block-editor/developers/block-api/block-transforms/
) to the core [columns block](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/column) might help here?

<img width="656" alt="Screen Shot 2021-02-23 at 11 48 25 am" src="https://user-images.githubusercontent.com/6458278/108789106-a6ac7e80-75cd-11eb-926b-0a79a715b891.png">

That is, an option to transform a column block into, say a list of text, each list item representing a column cell?

I think this could be a good core issue and not just a Gutenberg on WPCOM enhancement.

**Comment by ramonjd** [comment]
Possibly related: https://github.com/WordPress/gutenberg/issues/26962

**Comment by scosgro** [comment]
> That is, an option to transform a column block into, say a list of text, each list item representing a column cell?

Yep! That could work. Users (especially using templates/theme templates) inadvertently put everything into a column, or into a three column set and only use the middle column, which can make things a bit wonky, which is where the GitHub idea started.

**Comment by sanjeev00733** [comment]
Closing this because now we can move blocks outside the columns block in the list view by drag-drop https://d.pr/i/eXmhBF
