### ISSUE TITLE
Domain picker: mobile layout

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#48628]
Currently used in Focused Launch - Domain details view, the version of DomainPicker "with _Select_ buttons" should have a different layout on mobile, as specified in Figma.

As specified in Figma, the Domain Picker Details View should have a different layout on mobile. 
The differences are: 
1. Select buttons should be full-width and positioned at the bottom of a `<DomainPickerSuggestionItem/>`.
2. The registration fee label should be on a new line, right under the suggested domain.
3. A "Free" label should be added after the registration fee label to elaborate on why the fee is crossed out. 

#### Acceptance Criteria
* [ ] Select buttons are full-width and positioned at the bottom of a `<DomainPickerSuggestionItem/>`.
* [ ] The registration fee label is on a new line, right under the suggested domain.
* [ ] A "Free" label is added after the registration fee label. 

**Expected**

<img width="223" alt="Screenshot 2020-12-30 at 10 47 18" src="https://user-images.githubusercontent.com/14192054/103341425-91184e00-4a8f-11eb-9d97-6accd1807816.png">

**Current**

<img width="381" alt="Screenshot 2020-12-30 at 10 34 20" src="https://user-images.githubusercontent.com/14192054/103341443-9ecdd380-4a8f-11eb-8b81-aa61d86f8edb.png">

**Comment by StefanNieuwenhuis** [comment]
When a domain is included in a plan, on `> mobile` views we strike through the original price and add a label "Included in plans". 

<img width="995" alt="Screenshot 2021-01-04 at 14 46 17" src="https://user-images.githubusercontent.com/12104589/103541526-da0b4080-4e9b-11eb-9075-a2f491e5b28f.png">

On `≤ mobile` views we only strike through the original price. 

<img width="346" alt="Screenshot 2021-01-04 at 14 44 38" src="https://user-images.githubusercontent.com/12104589/103541552-e2fc1200-4e9b-11eb-9676-b06dcdb5919e.png">

In Figma, a label "Free" is added to elaborate on the strike-through price.

<img width="459" alt="Screenshot 2021-01-04 at 14 35 29" src="https://user-images.githubusercontent.com/12104589/103540614-471dd680-4e9a-11eb-8ddc-8517246931a9.png">

Do we want to add this label too and do we want to do that in this issue?

**Comment by razvanpapadopol** [comment]
Yes, adding the label can be done as part of this PR. "Free" should be seen as a shorter form of "Included in plans", right?

I can also see now there is a "Renews at {renewal_price} / year" text below the price for both mobile and desktop. Could you open a different issue for this?

cc: @ollierozdarz

**Comment by StefanNieuwenhuis** [comment]
> I can also see now there is a "Renews at {renewal_price} / year" text below the price for both mobile and desktop. Could you open a different issue for this?

Done. See #48662
