### ISSUE TITLE
Payments: Eligible users prompted to upgrade to access Payments block

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#48647]
Some users are unable to access the Payments block while on plans that access is included with (Personal and Premium).

#### Steps to reproduce

1. Starting at URL: wordpress.com/post or /page
2. Add the Payments block
3. See message "You'll need to upgrade your plan to use the Payments block."

#### What I expected

To be able to add the Payments block on eligible plans

#### What happened instead

The message "You'll need to upgrade your plan to use the Payments block." is shown

#### Screenshot / Video

![Screen Shot 2021-01-04 at 9 29 05 AM](https://user-images.githubusercontent.com/1900444/103545486-9ef31800-4e6f-11eb-922d-ee9eb1a239a4.png)

**Comment by KristinaKay** [comment]
Same here: #3621060-zen

<img width="1183" alt="Screenshot on 2021-01-04 at 07-30-05" src="https://user-images.githubusercontent.com/33169211/103545956-87ac2e80-4e5f-11eb-903c-4ee1ded17e70.png">

**Comment by ezebecke** [comment]
Reported on #3621026-zen

Simple site with Premium plan.

**Comment by sirreal** [comment]
Has this been observed with Simple, Atomic, or both?

**Comment by KristinaKay** [comment]
My above case was on a Personal Plan Simple site.

**Comment by thabotswana** [comment]
Another report: #3042597-hc

Personal plan site

**Comment by syds87** [comment]
Another user reporting this: #25257064-hc

Premium plan.

**Comment by dolgelukkig** [comment]
Another user on the Premium plan reporting this issue [26464766-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=26464766)

**Comment by nerdysandy** [comment]
Reported payment related issue on #26426443-hc too But they are using `Pay with PayPal` block. The error message shown to end user is: `We are sorry, there was a configuration problem. Please contact the site owner. Error:SP22`

**Comment by aisajib** [comment]
#26115691-hc reported the same problem but with the Premium Content block.

**Comment by KristinaKay** [comment]
Not sure if this is related, but Donations Block is also not showing correctly

Donation Block in Editor
<img width="1397" alt="Screenshot on 2021-01-04 at 07-53-18" src="https://user-images.githubusercontent.com/33169211/103548971-d8be2180-4e63-11eb-9c3a-58b71883db83.png">

Donation Block Live
<img width="979" alt="Screenshot on 2021-01-04 at 07-51-06" src="https://user-images.githubusercontent.com/33169211/103548969-d5c33100-4e63-11eb-9159-901e0cf2b5a8.png">

#3621119-zen (Business Plan)
#3621147-zen (Business)

**Comment by kspilarski** [comment]
26767415-hc - Business plan but asked to upgrade to use Premium Content block. Follow up in 3621187-zd.

**Comment by dolgelukkig** [comment]
Premium plan user asked to upgrade to use the Payments Block [16456299-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=16456299)

**Comment by liviopv** [comment]
I got one similar to @KristinaKay where the button is not rendered properly on the front end:

![Screenshot](https://d.pr/i/EPiQbe+)
Screenshot: https://d.pr/i/EPiQbe

Console errors:

![Screenshot](https://d.pr/i/vNgbUR+)
Screenshot: https://d.pr/i/vNgbUR

I was able to reproduce on my own site https://atlivio.wpcomstaging.com/donation-test/ and when I try to disconnect/reconnect to Stripe, I get stuck in a loop:

![Screenshot](https://d.pr/i/D93lPJ+)
Screenshot: https://d.pr/i/D93lPJ

Chat: 26675171-hc
Ticket: 3621223-zen

**Comment by philnick206** [comment]
Reported in: #26769220-hc
Follow up in: #3621289-zen

**Comment by dolgelukkig** [comment]
Looks like this could be related? 

Seeing the same error as mentioned above when trying to edit the page.

`Customers are having issues paying through the pay with paypal on my site. They are getting the following error message: "We are sorry, there was a configuration problem. Please contact the site owner. Error:SP22" If you could advise how to fix this asap please as I am losing customers. `

Asked in slack https://a8c.slack.com/archives/C03TY6J1A/p1609775214269000?thread_ts=1609771820.254500&cid=C03TY6J1A

screenshot of the error: https://d.pr/i/xj4Mrt

**Comment by ezebecke** [comment]
Reported in: 26770578-hc
Follow up in: #3621440-zen

**Comment by cathymcbride** [comment]
@apeatling I think this falls to your team? Can you confirm?

**Comment by jamiepalatnik** [comment]
Another report: 10685283-hc
Follow-up: 3621635-zd-woothemes

**Comment by eamcgill90** [comment]
Reported here: 26772502-hc

**Comment by apeatling** [comment]
I'm looking at this, as far as I know right now, no code has changed in the past two weeks.

**Comment by jackiejade** [comment]
Another report here: 23594022-hc
Follow up: 3621718-zd-woothemes

**Comment by rralian** [comment]
There was a problem with a recent change that has since been reverted. This should be addressed now.

**Comment by apeatling** [comment]
This is fixed. :+1:
