### ISSUE TITLE
WP Admin > Quick Draft: block errors when edit draft

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#48643]
#### Steps to reproduce

1. Starting at WP Admin
2. create draft in Quick draft form on right
3. click link to draft to edit form recent drafts section below
4. see block recovery error
5. click to recover block and see that content disappears

#### What I expected
should be able to edit draft same as any other with no block errors
recovering error should not erase content

#### What happened instead
when click button to recover block, content is erased
content is retained if choose to convert to HTML or classic block
I was able to duplicate on multiple sites 

#### Browser / OS version
chrome/mac

#### Screenshot / Video
<img width="1083" alt="1" src="https://user-images.githubusercontent.com/47717887/108841586-a9649f00-75e0-11eb-8f4f-f15c8bc450c8.png">

When convert to classic block:
<img width="969" alt="2" src="https://user-images.githubusercontent.com/47717887/108841594-acf82600-75e0-11eb-806f-282c90a22e71.png">

After attempt block recovery:
<img width="962" alt="3" src="https://user-images.githubusercontent.com/47717887/108841599-aff31680-75e0-11eb-8a65-2e99a3e7a42c.png">

#### Context / Source
#user-report
#3614656-zd

**Comment by inaikem** [comment]
Updated user report at #3614656-zd with screenshots.

**Comment by inaikem** [comment]
I was able to verify this bug still exists on my WPcom test sites.

**Comment by darnelldibbles** [comment]
Another report from the forums here: https://wordpress.com/forums/topic/quick-draft-body-text-always-incompatible-block-when-draft-opened/?view=all

**Comment by vykes-mac** [comment]
being looked at here https://github.com/Automattic/wp-calypso/issues/69264
