### ISSUE TITLE
Jetpack search page from WP.com indicates a WP.com site, even when self-hosted

### ISSUE THREAD

**Issue by trtmn** [Automattic/wp-calypso#48649]
#### Steps to reproduce the issue

1. login to wp.com
2. navigate to a self-hosted site
3. click on jetpack > search

#### What I expected
information about the search feature.

#### What happened instead
Observed: "Jetpack is a feature-rich plugin for WordPress sites. Because your site is hosted with us at WordPress.com, you already have access to most Jetpack’s features."

**Screenshots**
![image](https://user-images.githubusercontent.com/1972243/102583667-b3db5780-40ca-11eb-8f7a-7af39be6b30f.png)

**Comment by simison** [comment]
cc @gibrown I added to Jetpack search board, but feel free to triage this separately. Seems like a good quick win to sort out.

**Comment by bluefuton** [comment]
Thanks @simison! @kangzj is going to work on a PR for this one.
