### ISSUE TITLE
Hosting Configuration: sFTP and PHP version information will not load

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#48648]
#### Steps to reproduce

1. Visit hosting configuration page at https://wordpress.com/hosting-config/<site> for an Atomic site

#### What I expected

For the sFTP details and PHP version information to load.

#### What happened instead

The loading graphic never goes away  and eventually the error `Sorry, we had a problem retrieving your sftp user details. Please refresh the page and try again` appears.

#### Context / Source

Started with  #user-report and there have now been multiple reports and seems to be happening for all Atomic sites.

**Comment by amamujee** [comment]
@cathymcbride @davemart-in is this something that makes sense for the manage janitors to look at?

**Comment by davemart-in** [comment]
Let's check with @jmdodd first. Her team may be a better fit. If not, we can try and take a look.

**Comment by sandymcfadden** [comment]
@davemart-in I started with @jmdodd before slack when down. It was suggested to check with someone around Calypso. I did add it to Slack right before I posted this issue.

**Comment by davemart-in** [comment]
Roger that @sandymcfadden. Thanks for the heads up! @obenland with Ajax on Janitorial this cycle, can we please have someone investigate this one? I've added it to our [urgent list](https://github.com/orgs/Automattic/projects/174#column-9290937).

**Comment by lakellie** [comment]
User report in #3621576-zen

**Comment by obenland** [comment]
@cpapazoglou Any chance you're still around and could take a look?

**Comment by sandymcfadden** [comment]
If it helps at all the timeframe @jmdodd found was around 13:26/13:36 UTC today. That is when API calls to the Atomic platform for PHP version stopped coming through. 
There were two commits around that time but not sure either would affect this at all
https://github.com/Automattic/wp-calypso/commit/21b450253f3622699e7b58803016e8d50c880b7e
https://github.com/Automattic/wp-calypso/commit/d46b86831b2d27b836fa52bee94deb105a99647e

**Comment by obenland** [comment]
The API auth check fails and it looks like my test site (160544236) with a business plan comes back as not having an atomic-supported plan

**Comment by davemart-in** [comment]
Some other WP.com code was reverted just now. This issue should now be fixed again as a result.

**Comment by apeatling** [comment]
Thanks for the fix. :+1:

This change also broke access to all premium blocks on WordPress.com. Can look at figuring out an automated test so we can't break this much stuff again?

**Comment by apeatling** [comment]
https://github.com/Automattic/wp-calypso/issues/48647

**Comment by cathymcbride** [comment]
Adding to Quality Squad backlog to verify automated tests for this and 48647
