### ISSUE TITLE
Stats: is-fixed-row-header causes buggy scrolling

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#48650]
The `is-fixed-row-header` style introduced in #21780 (/cc @psealock) allows for horizontal scrolling while holding the first column in place. However, if the viewport is reduced to allow vertical scrolling, that first column remains in place as well, leaving it misaligned with its content.

![misaligned table](https://d.pr/i/dR8B3A+)

### Steps to reproduce
1. Navigate to `https://wordpress.com/stats/day/annualstats/[SITE]` for a site that has a few years of history.
2. Reduce the height of your viewport to enable vertical scrolling (if necessary).
3. Scroll down the page.

#### What I expected
Either we should keep the first column fixed only within the row itself, while still allowing vertical scrolling with the rest of the page, or we should present a simple table without trying to keep the first column fixed at all. 

#### Browser / OS version
Tested in Chrome 87 (latest)

**Comment by jinnypark** [comment]
This issue came up again in a ticket today: 3696727-zd-woothemes
Is there any updates/fix to this bug?

**Comment by michaeldcain** [comment]
@jinnypark: I edited the link to use our shorthand for public repos. See: PCYsg-5Xx-p2

**Comment by supernovia** [comment]
I ran across this today while looking to see what we already have re: this post

p1P4aZ-4BN-p2

https://wordpress.com/stats/day/annualstats/(siteadress)
