### ISSUE TITLE
Import: XML file import method unsuccessful on Calypso (regular WordPress.com dashboard)

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#48660]
#### Steps to reproduce

1. Create/export XML file from the original/old site. 
2. Go to WordPress.com dashboard/Calypso of the destination/new site
3. Go to Import (My Site > Tools > Import)
4. On the list "I want to import content from..." choose 'WordPress'
5. Click "upload it to import content" link to upload the XML file
6. Upload the XML file

#### What I expected
Import process to start with the flow asking the user to assign author/user on contents and to see the progress bar.

#### What happened instead
A message "Success! File uploaded." and nothing more. Import process never started and no contents imported.

Screenshot: 

![image](https://cldup.com/uHoNLS5H_k.png)
*Direct link: https://cldup.com/uHoNLS5H_k.png*

#### Browser / OS version
Chrome -- this happens across browsers and websites.

#### Context / Source
User report and I able to replicate it on my test site.

**Comment by inaikem** [comment]
Seconded. Able to replicate it on my test site (as part of work on 3615302-zd)

I'd like to add that the import seems to also stall: only 2x 2020 posts/pages for the above.

Exporting all content by date and importing that file worked perfectly.
