### ISSUE TITLE
Domain Picker: "Renews at {renewal_price} / year" label

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#48662]
As specified in Figma, the Domain Details View, which is used in Focused Launch, should include a renewal price label. 
The renewal price and the price should be identical (see `/start/domains`), **so we have to use the same data source!**

#### Acceptance Criteria
* [ ] A "Renews at {renewal_price} / year" label is added below the price on mobile
* [ ] A "Renews at {renewal_price} / year" label is added below the price on desktop
* [ ] The change should apply to the default mode of Domain Picker so it would be automatically reflected where the package is being used (Gutenboarding, Step-by-step Launch, Focused Launch - Domain Details View).

#### Steps to reproduce

1. Navigate to the Focused Launch Flow to launch a (newly created) site
2. Open the Domain Details View by clicking on "View all domains"
4. A "renewal price label" should be present for each domain suggestion but it isn't

#### What I expected
**Desktop**
<img width="1086" alt="Screenshot 2021-01-05 at 07 53 59" src="https://user-images.githubusercontent.com/12104589/103615718-57ca5d00-4f2b-11eb-960d-e696ad93610a.png">

**Mobile**
<img width="301" alt="Screenshot 2021-01-05 at 07 49 34" src="https://user-images.githubusercontent.com/12104589/103615325-ad523a00-4f2a-11eb-9d5b-116327658d8e.png">

#### What happened instead
**Desktop**
<img width="996" alt="Screenshot 2021-01-05 at 07 56 00" src="https://user-images.githubusercontent.com/12104589/103615784-7b8da300-4f2b-11eb-94b6-9425941f80d1.png">

**Mobile**
<img width="347" alt="Screenshot 2021-01-05 at 07 48 22" src="https://user-images.githubusercontent.com/12104589/103615185-6b28f880-4f2a-11eb-9f84-ffeda7cd0e66.png">

**Comment by razvanpapadopol** [comment]
After checking on `/start/domains`, it seems that price and renewal price values should be identical so we can use the existing data source.

**Comment by StefanNieuwenhuis** [comment]
> After checking on `/start/domains`, it seems that price and renewal price values should be identical so we can use the existing data source.

Thanks @razvanpapadopol. I've updated the issue's description.
