### ISSUE TITLE
Console error when an unconnected user attempts to set up Mailchimp block

### ISSUE THREAD

**Issue by kbrown9** [Automattic/wp-calypso#48684]
#### Steps to reproduce

1. Install, activate, and connect Jetpack. The site and first user are now connected.
2. Create another admin user, the secondary admin. Do not connect this user to wpcom.
3. Log in as the secondary admin.
4. Create a post and add the Mailchimp block.
5. Click the Setup Mailchimp button.
6. Log in to a WPCOM account that is not connected to a user on this site.
7. See a blank page and a JS error in the console:

#### What I expected
Some indication of what went wrong and how to fix it.

Ideally the user would be prompted to connect their account before they've reached this page. I opened an issue for that in the Jetpack repo: https://github.com/Automattic/jetpack/issues/18211

#### What happened instead
I see a blank page and a console error.

#### Screenshot / Video

![Annotation%20on%202021-01-05%20at%2016-58-46](https://user-images.githubusercontent.com/50059399/103704461-59ba0d80-4f77-11eb-9ace-019fe5060369.png)

**Comment by cathymcbride** [comment]
@jeherve would this issue belong to JP as well?

**Comment by jeherve** [comment]
> would this issue belong to JP as well?

No, since this happens within Calypso (Tools > Marketing > Connections).

**Comment by inaikem** [comment]
Unable to replicate on my test sites and it appears the related JP issue has been resolved, too: https://github.com/Automattic/jetpack/issues/18211.

Closing for the moment. Please reopen if the issue appears again or you are able to replicate it!
