### ISSUE TITLE
Design Picker: Overton cover block has strange placeholder text

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48699]
Steps to reproduce

1. Visit WP.com/new
2. Select Overton design
3. Observe placeholder text in cover block that reads, "Write titleu2026"

**Result**

![image](https://user-images.githubusercontent.com/545779/103816247-47e57280-502a-11eb-9782-fe298991ab71.png)

**Expected**

![image](https://user-images.githubusercontent.com/545779/103816339-72373000-502a-11eb-826c-4f33f0e02815.png)

**Comment by p-jackson** [comment]
Looks like a bug in the code that generates headstart annotations. I can see why, the strings are sort of double escaped. The annotation looks like:
… `\"placeholder\": \"Write title\\u2026\",` …
but should just have a \u like:
… `\"placeholder\": \"Write title\u2026\",` …

If the annotation file can deal with being saved in utf-8 it’d probably be easier to fix this by not escaping the ellipses and just putting them in like a regular character:
… `\"placeholder\": \"Write title…\",` …

**Comment by ramonjd** [comment]
I think this is related to https://github.com/Automattic/wp-calypso/issues/45763 - headstart does the same thing for all /u unicode characters

**Comment by ramonjd** [comment]
I've done a super quick annotation fix to make things work on the frontend D57321-code

**Comment by ramonjd** [comment]
Addressed in D57321-code

I've removed the ellipsis altogether and updated the starter site. There are [translations for this](https://translate.wordpress.com/projects/wpcom/block-patterns/-all-translations/296229/).

There are problems with unicode and headstart so for now it looks a lot better just to rip it out until they're sorted.
