### ISSUE TITLE
Design Picker: Doyle Starter Design creating unexpected or invalid content in Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48696]
To reproduce …

1. Visit wp.com/new
2. Select "Doyle" Starter Design
3. See invalid block content in Editor

![image](https://user-images.githubusercontent.com/545779/103812912-d9ea7c80-5024-11eb-9325-ef48f2d26139.png)

**Comment by p-jackson** [comment]
Fixed by D54974-code
