### ISSUE TITLE
 Reader Lists: list stream doesn't finish loading when a list is missing

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#48702]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/list/not/there

#### What I expected

The list doesn't exist, so I should be shown an message telling me that.

#### What happened instead

The list stream stayed in loading state.

#### Screenshot / Video

<img width="1518" alt="Screen Shot 2021-01-07 at 15 19 03" src="https://user-images.githubusercontent.com/17325/103843853-72543000-50fd-11eb-8f06-213a83203136.png">

API response:

<img width="434" alt="Screen Shot 2021-01-07 at 15 19 00" src="https://user-images.githubusercontent.com/17325/103843857-754f2080-50fd-11eb-8cb9-ecc9622dc702.png">

#### Context / Source

Discovered while trying to test an event for https://github.com/Automattic/wp-calypso/pull/48244.

**Comment by Aurorum** [comment]
PR for this issue in #53257. :)
