### ISSUE TITLE
Welcome Tour:  png & gif in src/images not getting copied into trunk

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#48704]
I just tested my work in #48390 and can see a known issue is still happening.   The png and gif files in the [src/images](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-welcome-tour/src/images) aren't getting copied into `wp-content/plugins/full-site-editing-plugin/467720122/wpcom-block-editor-welcome-tour/src/images`.

Some thoughts & resources:
PCYsg-h9w-p2
pbAok1-1NO-p2

**Comment by autumnfjeld** [comment]
Hm, I wonder if the new Editing Toolkit process will change anything about the way image files are copied.  @noahtallen will the new ETK release process allow for binary files to be  the issues with binary files (image files specifically) to be copied into wpcom?  Or will we need to wait until wpcom transitions to git?  This is low priority, just wondering how new ETK release process might change this issue.  Thank you!

**Comment by noahtallen** [comment]
Good question! I think it is possible we can implement this now. I'll look into it this week. We'll be operating a little closer to the system (less "magic"), so it might be easier to do

**Comment by noahtallen** [comment]
I also wonder if it makes sense to add the images to the CDN directly instead. I know very little about this problem space though 🤔

**Comment by autumnfjeld** [comment]
That was the solution we went with, we moved the images to CDN.  And maybe that is the best/simplest solution.  

The one upside to have images near the code is well, the images are near the code. 😄 Making maintenance easy and being able to use React imports for images in folders.

**Comment by noahtallen** [comment]
<img width="1320" alt="Screen Shot 2021-02-22 at 1 54 30 PM" src="https://user-images.githubusercontent.com/6265975/108775228-a9e43380-7515-11eb-9e7c-d33eb5f894e6.png">

Looks like it's working out of the box now :)

**Comment by noahtallen** [comment]
Should be working if you want to give it another shot. If there are still issues, I'm happy to fix them 👍

**Comment by autumnfjeld** [comment]
Fantastic @noahtallen !!  Thanks for taking the time to check it out.  🥇
