### ISSUE TITLE
Menu: Create a new page for this menu item does not work for child pages

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#4871]
#### Steps to reproduce
1. Starting at URL: WordPress.com/menus
2. Click any + to add a new menu item, then 'Add item to children'
3. Name the item, select 'Page' then 'Create a new page for this menu item'
4. Click OK, followed by Save

#### What I expected
A new page (top level or child? would probably have to depend on context) should be created when the menu is saved.

#### What happened instead
The menu item is added, but no actual page is created. The link in the menu is not clickable, but it does show up on the site.

#### Browser / OS version
Chrome 49.0.2623.112 on OSX 10.11.3 

#### Screenshot / Video
![child page](https://cloud.githubusercontent.com/assets/13856531/14652831/1c266d6e-0644-11e6-9042-f49206ee5d57.gif)

**Comment by artpi** [comment]
Noooo! :(
Ok, getting on it!

**Comment by artpi** [comment]
Also: stupid me :/
