### ISSUE TITLE
Manage Purchases: If auto-renew is off, Payment Method is shown as "None" even if a payment method was just added

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#48736]
#### Steps to reproduce

1. Buy a subscription.
2. Toggle auto-renew off via the subscription's Manage Purchase page.
2. Notice that the "Payment Method" section switches to "None".
3. Now use the "Change Payment Method" link to switch to a new payment method.
4. You are directed back to the Manage Purchase page with a message that the new payment method was saved (and in fact it was) but the Payment Method still shows as "None" which is pretty confusing.

![Screenshot from 2021-01-08 11-45-21](https://user-images.githubusercontent.com/235183/104041835-a1bf7700-51a7-11eb-8538-1311b1dc0f54.png)

#### What I expected

The above combination of things on the screen doesn't make any sense and shouldn't be possible.

There are a few ways I can imagine fixing this, but one is to always show the payment method that is assigned to a subscription on this screen (even when auto-renew is off).  I don't fully understand the reason for hiding it and replacing it with "None".  And as far as I know, we actually used to show it even when auto-renew was off; I'm not sure when that behavior changed.

**Comment by sirbrillig** [comment]
> And as far as I know, we actually used to show it even when auto-renew was off; I'm not sure when that behavior changed.

I took a look at the history for that component (`PurchaseMetaPaymentDetails`) and this logic has been present for around 3 years, and I think a lot longer. In this particular case, the function `isExpiring()` returns true if the expiry status on the purchase object is `manualRenew`. (You did make a related modification in 2019, for expired cards in https://github.com/Automattic/wp-calypso/pull/34320) It is possible, however, that there was a server side change that modified what the `purchase` object contains.

In any case, we could change `isExpiring()` to treat `manualRenew` as false, but that might have unintended consequences for other code that uses the function. Alternatively, we could modify `PurchaseMetaPaymentDetails` to display the selected payment method even if `expiryStatus` is `manualRenew`, possibly with an additional note of the form "(will not auto-renew)".

**Comment by sirbrillig** [comment]
In a larger sense, though, I think maybe "None" may be better UX, since AFAIK it doesn't matter if there's a payment method set on a subscription if auto-renew is disabled, right? Perhaps a better way to fix this would be to change the endpoint such that if a payment method is added to a subscription, the subscription gets auto-renew turned back on?

**Comment by sirbrillig** [comment]
I made https://github.com/Automattic/wp-calypso/pull/48775 to fix this issue, but as I said above, I wonder if it's the right solution.

**Comment by DavidRothstein** [comment]
>And as far as I know, we actually used to show it even when auto-renew was off; I'm not sure when that behavior changed.

Answer, three months ago, intentionally: https://github.com/Automattic/wp-calypso/pull/46625

>Perhaps a better way to fix this would be to change the endpoint such that if a payment method is added to a subscription, the subscription gets auto-renew turned back on?

Personally I think both solutions might be good changes, but I agree this one is worth doing no matter what -- especially since it looks like that's what we already do when adding a **new** credit card.

**Comment by DavidRothstein** [comment]
>Perhaps a better way to fix this would be to change the endpoint such that if a payment method is added to a subscription, the subscription gets auto-renew turned back on?

Note that we're working on that in https://github.com/Automattic/wp-calypso/issues/48818
