### ISSUE TITLE
Homepage WSOD when gutenberg-edge sticker applied

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#48733]
#### Steps to reproduce

To get the WSOD:
1. Sandbox `public-api.wordpress.com`
1. Make sure the `gutenberg-edge` sticker is not applied to `yourtestsite.wordpress.com`
1. Go to `https://wordpress.com/home/yourtestsite.wordpress.com`
1. Make sure the site loads correctly and there are no errors in the console
1. Apply the `gutenberg-edge` sticker to `yourtestsite.wordpress.com`
1. Refresh `https://wordpress.com/home/yourtestsite.wordpress.com` 
1. See the WSOD and a `TypeError: "key must be an object, null, or undefined error"` in the console

To fix the WSOD:
1. Take off the `gutenberg-edge` sticker
1. Refresh
1. The WSOD is still present
1. Delete the calypso `indexedDB`
1. Refresh again
1. The page works normally.

#### Browser

Erroring in Chrome and Firefox. Interestingly, Safari doesn't seem to be affected by it.

#### Screenshot

![image](https://user-images.githubusercontent.com/1451471/104018962-fa4c3f80-51ba-11eb-8b5b-6bb8244e7de7.png)

#### Context / Source

- p1609946035051700-slack-C015AL3QL7M
- p1591111808358200-slack-C02DQP0FP
- p1570547967180800-slack-C02DQP0FP
- p1594624436481900/1594624374.481400-slack-C02ECE3ML

#### Observations

I've been doing some debugging on this one, but it's still unclear to me how the Gutenberg plugin affects Calypso's homepage. We have a few observations at this point though:

- The error is thrown only if the public-api is sandboxed.
- The error is thrown only for the edge (v9.6.2) version of the Gutenberg. 
- The error is thrown in Chrome and Firefox but not in Safari.
- The error is thrown from the [@automattic/tree-select](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tree-select) package.
- The `indexedDB / calypso_store` content created for a stickered site (running GB v9.6.2) is a bit different from the production one (running v9.5.2) — a stickered site contains 2 extra states: `reader` and `userSuggestions`:

   | Production (v9.5.2) | Edge (v9.6.2) |
   | ------------- | ------------- |
   | <img width="582" alt="Screenshot 2021-01-08 at 13 57 16" src="https://user-images.githubusercontent.com/1451471/104020125-f9b4a880-51bc-11eb-9181-e91b5e5f9064.png"> | <img width="583" alt="Screenshot 2021-01-08 at 13 57 28" src="https://user-images.githubusercontent.com/1451471/104020135-00432000-51bd-11eb-8ee8-f779d0e77e39.png"> |
- The `calypso_store` needs to be completely deleted in order to fix the issue. It's not enough to clear its content.
  
cc @sirreal @fullofcaffeine @Addison-Stavlo @enejb @scruffian @bor0 @simison

**Comment by simison** [comment]
cc @Automattic/team-calypso in case anything strikes obvious.

**Comment by jsnajdr** [comment]
@WunderBart Trying to reproduce this, so far not successfully. I haven't sandboxed my `public-api.wordpress.com` yet though. I'd like to understand why that's necessary -- I'm not applying any patch in my sandbox, so the API responses should be identical to production. Is that right?

**Comment by tyxla** [comment]
I was also unable to reproduce it, tried sandboxed and non-sandboxed, and with multiple sites. I'm also curious about what sandboxing changes - should we also apply a patch before testing?

**Comment by jsnajdr** [comment]
> The error is thrown from the `@automattic/tree-select` package.

This package is used to implement Redux selectors. Can we figure out which selector exactly is crashing and what Redux state is it trying to read?

There is likely to be some very unexpected value in Redux state.

**Comment by WunderBart** [comment]
Thanks for testing, @jsnajdr & @tyxla! 

> I haven't sandboxed my public-api.wordpress.com yet though. I'd like to understand why that's necessary

I don't know why at this point, but only when sandboxing the public-api you'll see the WSOD. Otherwise, everything will look OK and the page will load as usual.

> I'm not applying any patch in my sandbox, so the API responses should be identical to production. Is that right?

AFAIK, that's correct (but I might be wrong!).

> I was also unable to reproduce it, tried sandboxed and non-sandboxed, and with multiple sites

Interesting! Do you have the `gutenberg-edge` sticker applied and sandbox up to date (should have GB 9.6.2 as the edge version)? Also, are you using Chrome or Firefox?

> I'm also curious about what sandboxing changes - should we also apply a patch before testing?

As above - not sure at this point what sandboxing changes in this case. No patch should be applied, just a clean current sandboxed WPCOM.

**Comment by WunderBart** [comment]
> > The error is thrown from the `@automattic/tree-select` package.
> 
> This package is used to implement Redux selectors. Can we figure out which selector exactly is crashing and what Redux state is it trying to read?
> 
> There is likely to be some very unexpected value in Redux state.

Great tip, thanks @jsnajdr! I was able to find the key that's causing the error this way. The [dependent](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tree-select/src/index.js#L47) looks like this:

<img width="551" alt="Screenshot 2021-01-08 at 16 36 32" src="https://user-images.githubusercontent.com/1451471/104033525-ebbc5300-51cf-11eb-8b1d-8ecc9854c6bd.png">

...which shows the `key` to be an empty string. According to [this condition](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tree-select/src/index.js#L80-L82), an empty string is not allowed as a falsy value so it's throwing an error 💥 . This is definitely progress, but I still need some advice on what to do next. IMO, an empty string is a valid falsy value, so maybe we should include it along with `null` and `undefined`? That seems to fix the current error, but maybe we need to verify that we're not covering some bigger issue first. What do you think?

**Comment by WunderBart** [comment]
> That seems to fix the current error, but maybe we need to verify that we're not covering some bigger issue first.

I think I had a good hunch there 😅. I followed the call chain up and found out that the selector returning the faulty key is the [`getSiteStatsForQuery`](https://github.com/Automattic/wp-calypso/blob/bbad57e43a740e0d5ea37224b9e4114a2ed8beed/client/state/stats/lists/selectors.js#L58-L62) one. Items for that state seem to be obtained via the `WPCOM_JSON_API_Stats_Insights_Endpoint`, so I checked my test site's endpoint (https://public-api.wordpress.com/rest/v1.1/sites/fancycurtains.wordpress.com/stats/insights) and got:

```
<br />
<b>Warning</b>: Use of undefined constant STYLESHEETPATH - assumed 'STYLESHEETPATH' (this will throw an Error in a future version of PHP) in <b>/home/wpcom/public_html/wp-includes/template.php</b> on line <b>663</b><br />
[public-api.wordpress.com/rest/v1.1/sites/fancycurtains.wordpress.com/stats/insights]<br />
[/plugins/gutenberg-core/9.6.2/lib/global-styles.php:14 locate_template(), /plugins/gutenberg-core/9.6.2/lib/global-styles.php:264 gutenberg_experimental_global_styles_has_theme_json_support(), wp-includes/class-wp-hook.php:287 gutenberg_experimental_global_styles_register_user_cpt(), wp-includes/class-wp-hook.php:311 apply_filters(''), wp-includes/plugin.php:484 do_action(Array), wp-settings.php:550 do_action('init'), wp-config.php:7 require('wp-settings.php'), wp-load.php:37 require_once('wp-config.php'), public.api/rest/load.php:22 require_once('wp-load.php'), public.api/rest/index.php:108 require('public.api/rest/load.php')]<br /><br />
<br />
```

...which has been known to be causing trouble for quite some time now (p1607374097134400-slack-CHN6J22MP, cc @noahtallen). This response is a false negative, because its status is a 200, despite the fact that the server crashed. This only happens when the site is sandboxed! When I'm not sandboxed, the response's state is 403 (forbidden) with a correct payload:

```
{error: "unauthorized", message: "user cannot view stats"}
```

So, more progress here but I still don't know how to proceed with this 😅 . Any ideas?

**Comment by noahtallen** [comment]
I believe we've been trying to get core Gutenberg to stop using `STYLESHEETPATH`, because it is incompatible with the WordPress.com REST API. (Because the rest API uses its own theme, so the constant would not point to the theme of the current site.) cc @Automattic/cylon, let me know if I'm wrong about this.

If that's the case, the problem would be that global styles is referencing `locate_template`, a core function which uses `STYLESHEETPATH` [according to these docs](https://developer.wordpress.org/reference/functions/locate_template/).

So I guess the solution is:
1. Do something on the wpcom side of things such that `STYLESHEETPATH` will work in this context. It seems odd to me that `locate_template`, a core function, would be entirely unusable in the wpcom rest API.
2. Get global styles to stop using that locate template function... which seems like a hard thing to enforce if this keeps coming up.

Unfortunately, I don't think we can  just turn global styles off, because this check for `locate_template` is part of the function which determines if global styles should load in the first place...

**Comment by noahtallen** [comment]
This diff fixes the issue: D55104-code.

**Comment by jsnajdr** [comment]
> I believe we've been trying to get core Gutenberg to stop using STYLESHEETPATH, because it is incompatible with the WordPress.com REST API. (Because the rest API uses its own theme, so the constant would not point to the theme of the current site.)

I don't know if it's relevant to this particular problem, but WordPress REST API is partially aware of the current user's theme. The REST API base classes have a `load_theme_functions()` that's called by selected endpoints that need them. One example are themes that register custom post types. REST endpoints listing posts need to call `load_theme_functions()` to work with these. I did a bugfix in D31026-code some time ago, and that's why I know this obscure detail 🙂 

Maybe something Gutenberg-related should be added to `load_theme_functions()` or the `restapi_theme_init` hook?

**Comment by jsnajdr** [comment]
> IMO, an empty string is a valid falsy value, so maybe we should include it along with null and undefined?

The `tree-select` library supports only object-like keys than can be used as keys in a `WeakMap`. It will reject a boolean `false` value, too. `null` and `undefined` is a special case we needed to introduce to make it work with reducers' initial states that are often `null`.

The empty string is not a valid value for the `state.stats.lists.items` state and it should never get there in the first place. A standard way to do that is to check the incoming REST response with a JSON schema. We have a JSON schema checks in the [`stats.visits` handler](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/data-layer/wpcom/sites/stats/visits/index.js#L50), for example, but not elsewhere in stats.

**Comment by WunderBart** [comment]
Fixed via D55104-code

**Comment by noahtallen** [comment]
> Maybe something Gutenberg-related should be added to load_theme_functions() or the restapi_theme_init hook?

We currently have to play whackamole with different Gutenberg functions which might rely on the theme functions at the "wrong time". So I wonder if there is a way to support that more generally instead of having to track down the error and adding exactly the same fix every time.
