### ISSUE TITLE
Users > Add New on Atomic sites with SSO enabled

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#48748]
#### Steps to reproduce

If you go to Users → Add New on an Atomic site, it leads to the WP Admin page where you can add a local user.

This is not sufficient for adding a user to an Atomic site with SSO enabled. Users created here would not have the ability to log into the site, they must have an invitation instead.

#### Screenshot / Video

![Screen Capture on 2021-01-09 at 15-38-33](https://user-images.githubusercontent.com/1398304/104657240-77712c00-5675-11eb-8cdf-aaf56470af4a.gif)

#### Context / Source

This issue was discovered during the Athens Team Hangout

**Comment by JoshuaGoode** [comment]
Hmm, odd. I never could get to that screen without manually entering the URL.

Instead, I had quite the opposite experience and worry about users with membership sites and customers that need to access the local user accounts and not the user screen in Calypso: 
https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-756466382

**Comment by JoshuaGoode** [comment]
With the current version of Nav Unification we're testing, when I go to WP-Admin > Users > Add New, I am directed to https://wordpress.com/people/new/ which is Calypso and not the local users screen.

There is work going on regarding an opt-out feature so sites can access the local users and edit those when necessary.  I described the need for that here: https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-756466382

Perhaps you stumbled upon something being tested for opt-out or there may be something wrong with the test site(s) you were using.

**Comment by cpapazoglou** [comment]
Thanks for the reports @RealCarFax & @JoshuaGoode. Indeed, now we default to the Calypso screens both for simple & atomic sites. @RealCarFax probably you have tested an Atomic site while in calypso, without enabling the feature in that Atomic site and thus you were served a fallback menu. 

It seems that this particular case is quite tricky. Can you confirm whether the same customer would simultaneously need access to both interfaces for adding a user?

**Comment by obenland** [comment]
It looks like nav unification wasn't active on that site, it shows the unmodified admin menu. With the modifications in place, Add new will point to https://wordpress.com/people/new/.
