### ISSUE TITLE
Design Picker: Cropped Images in Starter Design need updating

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48742]
We have some cropped icons in the Stratford starter design that need updating.

![image](https://user-images.githubusercontent.com/545779/104067265-7436f580-51c8-11eb-9276-5cb505b697f6.png)

**Comment by ianstewart** [comment]
The starter design content has been updated to correct this.

![image](https://user-images.githubusercontent.com/545779/104067310-8add4c80-51c8-11eb-87b3-2d509375faa9.png)

But we'll need to deploy a fix to Gutenboarding for this to update there.

**Comment by andrewserong** [comment]
Updated annotation ready for review in D55126-code. I was going to mention an issue with the button text, but @ianstewart's already logged it here https://github.com/Automattic/themes/issues/2996. Thanks for being so thorough!

**Comment by andrewserong** [comment]
Deployed D55126-code, so this is now rolled out 😀
