### ISSUE TITLE
Editor: Image Replacement UI broken in Chrome MacOS

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48741]
#### Steps to reproduce

1. Create a new site at WP.com/new
2. Replace an image in the Editor
3. Observe strange offset image replacement source UI

May be related to images in columns.

#### Result

![image](https://user-images.githubusercontent.com/545779/104064572-c9bcd380-51c3-11eb-9395-2ab5283bbd02.png)

![image](https://user-images.githubusercontent.com/545779/104064601-d3463b80-51c3-11eb-8d41-32c6532437fd.png)

#### Browser / OS version

Chrome MacOS

**Comment by ianstewart** [comment]
This may be a theme issue related to Varia …

![image](https://user-images.githubusercontent.com/545779/104065617-ad219b00-51c5-11eb-8eae-c6a8f6ec6c9c.png)

**Comment by jffng** [comment]
I think that it's an issue with the popover component within a columns block, not Varia specific. Here is a screenshot with 2020 activated:

<img width="1904" alt="Screen Shot 2021-01-08 at 5 05 36 PM" src="https://user-images.githubusercontent.com/5375500/104070016-e103bd00-51d3-11eb-96b9-d2354f6218e3.png">

I don't know how or why that floating point position right value is computed, but it's causing the popover component's content to be very wide.

**Comment by andrewserong** [comment]
I _think_ this might be the issue fixed by https://github.com/WordPress/gutenberg/pull/27777 in Gutenberg 9.7?

**Comment by aaronrobertshaw** [comment]
> I think this might be the issue fixed by WordPress/gutenberg#27777 in Gutenberg 9.7?

I believe it is. 

The visually hidden span containing the `(open in new tab)` text inside the `LinkControl` isn't positioned correctly.

| Spearhead | Varia |
|------------|------|
| ![ScrollIssue](https://user-images.githubusercontent.com/60436221/104165676-748ff480-5445-11eb-9c99-15968d97c0e1.gif) | ![ScrollIssue2](https://user-images.githubusercontent.com/60436221/104166046-e36d4d80-5445-11eb-8f87-ddad7c0919ce.gif) |

**Comment by simison** [comment]
FYI @Automattic/good-mountain to track as fixed by Gutenberg 9.7

**Comment by sirreal** [comment]
#48771 is complete and this should be fixed.
