### ISSUE TITLE
Welcome Tour MVP final UI tasks

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#48751]
These can be broken into separate PRs, though they are each small tasks that could go in one PR.

- [x] copy updates per pbAok1-1LS-p2#comment-3544 https://github.com/Automattic/wp-calypso/pull/48783
- [x] i18n all strings, e.g `__()` https://github.com/Automattic/wp-calypso/pull/48783
- [x] put images on s0.wp.com [discussion](pbAok1-1LS-p2#comment-3544) and change imports to using CDN url (D55177-code and https://github.com/Automattic/wp-calypso/pull/48784)
- [x] Address design input https://github.com/Automattic/wp-calypso/pull/47779#issuecomment-739650477 (Done in https://github.com/Automattic/wp-calypso/pull/47779#issuecomment-742186023 ?)

**Comment by roo2** [comment]
I'll work on getting the welcome guide link to open the correct welcome tour based on the user, currently it always opens the old one 
<img width="375" alt="Screen Shot 2021-01-12 at 10 40 43 am" src="https://user-images.githubusercontent.com/22446385/104251283-21588900-54bb-11eb-98ae-66409b16bc10.png">

p1610398000280900-slack-CRWCHQGUB?thread_ts=1610395157.280100&cid=CRWCHQGUB
p1610408472294700-slack-CRWCHQGUB?thread_ts=1610406999.292500&cid=CRWCHQGUB
