### ISSUE TITLE
Plans Grid: add monthly pricing

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#48760]
### Why

As mentioned in p7rd6c-2ES-p2, as part of the global rollout we should add monthly pricing option to `/new` and the Launch flows.

### What

**NOTE: Requires #48767 (data-store changes) and #48769 (toggle component) to be implemented first.**

The plans-grid package should be updated to allow the user to pick annual (default) or monthly plan billing.

### Acceptance Criteria

- [ ] Display the Annual / Monthly toggle. Interacting with the toggle updates prices and copy in the rest of the plans UI
- [ ] The annual plans are the default option
- [ ] For both annual and monthly, 5 plans are shown to the user (free, personal, premium, business, ecommerce)
- [ ] The prices of the plans are updated when the user toggles between annual / monthly (price data is expected to come via the plans data-store)
- [ ] The billing information, displayed under the price, is also updated when the user toggles between annual / monthly
  - Q: should this text come via the plans data-store, or should it part of the UI components?
- [ ] The `SAVE [PERC]% BY PAYING ANNUALLY` text should be displayed under the pricing/billing information
  - [ ] `PERC` needs to be computed dynamically for each plan
  - [ ] The max value of `PERC` across all plans needs to be used in the toggle tooltip (`..save up to [PERC]%`)
  - [ ] When the annual plans are selected, this text should be displayed in green color
  - [ ] When the monthly plans are selected, this text should be greyed out and have a strikethrough effect
- [ ] Both the feature list (`plans-feature-list`, https://cloudup.com/cR048f6pRGM) and the comparison table (`plan-details`, https://cloudup.com/ch9l6RD1iyE) need to be updated to reflect that certain features are not supported by monthly plans:
  - [ ] Custom domains
  - [ ] Live chat support
- [ ] The refund policy text on top of the plans step need to be updated to reflect the 7 (monthly) vs 14 (annually) days difference in the refund window
- [ ] The Domains Picker copy (in Gutenboarding) needs to be updated from "included in plans" to "Included with annual plans"
- [ ] Make sure that the UI looks ok for all locales
- [ ] In the final step of Step by Step launch flow:
  - [ ] If a monthly billed plan and a custom domain are selected, the price of the domain is shown under the domain name
  - [ ] The billing information is updated ("x per month, billed as 12 * x annually" or "x per month, billed monthly")
- [ ] All of the above mentioned changes should be applied for both table and accordion variations of the plans grid, and should be working in all flows that use this package (e.g. gutenboarding, step-by-step launch, focused launch)
- [ ] All of the onboarding flows keep working as expected when selecting a plan, and the newly introduced monthly plans work nicely with the rest of the flows and checkout steps.

### Follow-up/related issues:

- Exact copy changes at the top of the plans step in Gutenboarding. Tracked separately in #49252
- Persist billing period in launch store. Tracked separately in #49339
- More copy changes that we had to backtrack before release in order to have working translations (issue to be created)
- Domain picker copy changes (affects mainly Focused Launch). Tracked separately in #49256
- Fix incorrect features in the plans comparison (details) table. Tracked separately in #49142
- Automatic selection of corresponding annual/monthly plan. Tracked separately in #49253
- Add/update Tracks events to support monthly pricing. Tracked separately in #49254
- Show correct price of monthly-billed plans in Focused Launch summary. Tracked separately in #49257

### Context

Screenshots (**NOTE**: they don't reflect all the AC stated above):
<img width="1440" alt="Existing-users-monthly" src="https://user-images.githubusercontent.com/14192054/104164685-f578cd00-5400-11eb-9b36-d80fb9c330d6.png">
<img width="1440" alt="Existing-users-annually" src="https://user-images.githubusercontent.com/14192054/104164689-f578cd00-5400-11eb-953b-48f45b691538.png">
<img width="1440" alt="launch-monthly" src="https://user-images.githubusercontent.com/14192054/104164671-f14caf80-5400-11eb-9988-ed9ed2b9f8de.png">
<img width="1440" alt="launch-annually" src="https://user-images.githubusercontent.com/14192054/104164683-f447a000-5400-11eb-97aa-3aae0bd4143b.png">

**Comment by ciampo** [comment]
While working on this issue, I’ve found an inconsistency in Step by Step launch that hasn't been spec'd yet: if the user picks a monthly billed plan, the “Launch your site” step still shows a custom domain as part of the deal — although it should not be included with monthly plans.

![image](https://user-images.githubusercontent.com/1083581/105736745-69ed5900-5f35-11eb-9dc7-4b3c7ff9b8a6.png)

Any suggestions on what do about this? 

cc @razvanpapadopol @ollierozdarz

**Comment by razvanpapadopol** [comment]
It's not explicitly saying that the domain is included but it would probably be helpful if, in the case of a selected monthly plan, we add below "Custom domain: ..." a line with the yearly price of the domain (as we're doing for plan).
