### ISSUE TITLE
Global Styles: Fonts: Don't load if the theme doesn't support it.

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#48766]
Global Styles loads custom fonts even when the theme doesn't declare support for them. This means we have a different view in the editor and the frontend. See pNEWy-duL-p2#comment-52549

#### Steps to reproduce

1. Create a Simple Site with a Varia based theme that supports global styles
2. Select some custom fonts
3. Switch to Twenty Twenty One
4. Notice that your editor doesn't match the front end, and its impossible to change this font selection.

#### What I expected
- At least the editor and frontend should match, but ideally we don't load custom fonts unless a theme declares support.

#### Screenshot / Video
![image-2](https://user-images.githubusercontent.com/275961/104194563-63c98980-5419-11eb-8ed6-f0fe39075bc5.png)

#### Context / Source
Originally reported here: pNEWy-duL-p2#comment-52549

**Comment by Robertght** [comment]
I can't replicate this anymore. I'm assuming this was fixed here: https://github.com/Automattic/themes/issues/3202
