### ISSUE TITLE
Nav Unification: Wrong color scheme when loading "Account settings" in the browser

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#48768]
I followed the steps for testing the alpha version of the Nav Unification project for the first time (paYJgx-1af-p2#testing-simple-sites) and noted that the new menu is using a bright color as background when loading the "Me > Account settings" page directly in the browser (https://wordpress.com/me/account). Navigating away to "My sites" and going again back to "Me > Account settings" results in the correct dark background color.

https://user-images.githubusercontent.com/1233880/104199500-d17cb200-5427-11eb-8f94-7f5be6c57d4f.mov

**Comment by cpapazoglou** [comment]
@mmtr can you confirm that it is fixed now?

**Comment by mmtr** [comment]
@cpapazoglou it is! Thanks!
