### ISSUE TITLE
Customizer: Color picker isn't showing labels or complementary colors on Atomic sites

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#48773]
#### Steps to reproduce

1. Activate a theme (e.g. Seedlet) on an Atomic site.
2. Go to Customizer → Colors & Backgrounds.
3. Select one of the color circles.

The color circle labels and complementary colors don't show.

#### Browser / OS version
Chrome 87.0.4280.141 on macOS 11.1

#### Screenshot / Video
Screenshot showing missing labels/complementary colors:
* ![](https://user-images.githubusercontent.com/51966986/104130218-71263b80-5367-11eb-8a8c-bccfc443c6e0.png)

With Seedlet activated, JS console shows this when loading the Customizer:
* ![](https://user-images.githubusercontent.com/32492176/104210264-e5a4bd00-53ef-11eb-93a1-28b1a124f6f9.png)

Clicking a color circle shows this error:
* ![](https://user-images.githubusercontent.com/32492176/104210315-f5240600-53ef-11eb-94c3-c3ce899f30bc.png)

#### Context / Source
Split from Automattic/themes#3001.

**Comment by kwight** [comment]
Yes, I can confirm this is Atomic-only, and I see the same `Uncaught TypeError: ct.suggestions.spin is not a function` error when clicking on the color circles.

**Comment by kwight** [comment]
`spin()` seems to be a jQuery thing loaded here: https://github.com/Automattic/custom-colors/blob/remove/custom-design-dep/colors.php#L136. If having access to the script is a problem, I don't see why we couldn't just remove the spinner usage.

**Comment by kwight** [comment]
Keep in mind that Custom Colors on Atomic is run via a `wpcomsh` submodule (on the `remove/custom-design-dep` [branch](https://github.com/Automattic/custom-colors/blob/remove/custom-design-dep/colors.php)).

**Comment by mreishus** [comment]
There are two different `color.php`s that provide this feature.

### Simple
`colors.php` in mu-plugins.  It registers a hook to run `wp_enqueue_script( 'jquery.spin' );` `/wp-includes/js/jquery/jquery.spin.js` exists in the repository, and my browser loads `/wp-includes/js/jquery/jquery.spin.js` successfully.

### WOA
`colors.php` in `custom-colors`, a submodule of `wpcomsh`.  It also registers a hook to run `wp_enqueue_script( 'jquery.spin' );`.  However, `jquery.spin.js` is nowhere to be found in either `wpcomsh` or `custom-colors`.

I'm not sure of the current mechanism that we use to add custom files to `wp-includes` for WOA sites.

**Comment by mreishus** [comment]
20-gh-Automattic/custom-colors : I think this might do it, but I haven't found a way to test it on an atomic site yet.  There is the ephemeral atomic creation tool, but I haven't been able to recreate the original problem there.  Will continue looking tomorrow.

**Comment by kwight** [comment]
Hm, maybe this is because core has been removing... all? some? of jQuery – and maybe we've kept it on dotcom (total slightly-more-than-not-educated guess).

Regardless, your approach looks great (add the missing script to the submodule itself). The easiest way to test is likely using your stock Jetpack local test environment, and install the `wpcomsh` plugin by hand. You'll need make sure the submodules are installed (but first tell Git to use your branch from the source `custom-colors` repo).

**Comment by mreishus** [comment]
580-gh-Automattic/wpcomsh is the next step of the process.

**Comment by mreishus** [comment]
This is done and has been deployed!  I tested on one of my atomic sites where I was able to see the original problem, and now I'm able to see the color selections, and change colors.
![2021-01-13_14-51](https://user-images.githubusercontent.com/937354/104509162-e20b6480-55ae-11eb-8bc9-70f91e0e8576.png)
@tbradsha please re-open if you are still experiencing the error.
