### ISSUE TITLE
Gutenberg: 9.7 Plugin Upgrade

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#48771]
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/48426
Release notes: [v9.7.0](https://github.com/WordPress/gutenberg/releases/tag/v9.7.0), [v9.7.1](https://github.com/WordPress/gutenberg/releases/tag/v9.7.1), [v9.7.2](https://github.com/WordPress/gutenberg/releases/tag/v9.7.2)

### Process

- [x] Install and activate
  - [x] Copy 9.6.2 to 9.7.0 (D55157-code)
  - [x] Install 9.7.0 on simple sites (D55160-code)
  - [x] Copy 9.6.2. to 9.7.1 (D55205-code)
  - [x] Install 9.7.1 on simple sites (D55208-code)
  - [x] Activate 9.7.1 on edge sites (D55209-code)
  - [x] 9.7.2 (D55291-code D55293-code)
  - [x] Activate 9.7.2 on production sites (D55275-code)
  - [x] Request update for Atomic sites
- [x] Testing
  - [x] Calypso E2E https://github.com/Automattic/wp-calypso/pull/48854
  - [x] TC D55275-code
- [x] Publish internal announcements
- [ ] Clean up unused releases
  - [ ] 9.5.2 [once 9.7 stable is in production]
  - [ ] 9.7.0
  - [ ] 9.7.1
- [x] Update the Gutenberg Upgrade Log [pcoGjb-u-p2] and list patches applied.
- [x] Open a new issue for the next upgrade, transfer remaining tasks, close this issue. https://github.com/Automattic/wp-calypso/issues/48950

### Issues / Blockers 🐛 

Nothing yet :)

### Fixes

- Closes https://github.com/Automattic/wp-calypso/issues/48772
- 9.7.2 should include a fix for https://github.com/WordPress/gutenberg/issues/28113
- Should fix https://github.com/Automattic/wp-calypso/issues/48741

**Comment by sirreal** [comment]
Next upgrade: https://github.com/Automattic/wp-calypso/issues/48950
