### ISSUE TITLE
Verse block display has changed following Gutenberg update

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#48772]
Following our update to Gutenberg 9.6.2 there are user reports of the look of the verse block has changed.

#### Steps to reproduce

1. View a post containing a Verse block
2. The look of the block has now changed from how it looked previously

#### What I expected

The update to have not impact on the look of the verse block.

#### What happened instead

The look of the block changed.

Initial report: 25707875-hc

**Comment by mikeicode** [comment]
Appears to be related to CSS `white-space`

How it currently looks:

![https://d.pr/i/rGkNI3](https://d.pr/i/rGkNI3+)


After adding the following:

```
pre.wp-block-verse {
  white-space: unset;
  overflow:auto;
}
```

![https://d.pr/i/ibvNfC](https://d.pr/i/ibvNfC+)



```

**Comment by sirreal** [comment]
https://github.com/WordPress/gutenberg/pull/27734 introduced a related change.

**Comment by carinapilar** [comment]
Got another report on 14842845-hc

EDIT: the CSS only didn't fix the issue though, it shows all content without the original formatting.

**Comment by kathrynwp** [comment]
Also ran into this in 26170324-hc - CSS workaround did the trick

**Comment by JoshuaGoode** [comment]
[The change to fix this modifies](https://github.com/WordPress/gutenberg/pull/28109/files) white-space to use `pre-wrap`

Temporary workaround CSS for Atomic could look like the following for consistency.

```
 /* Resolve Verse block line-wrap rendering  */
 pre.wp-block-verse {
  white-space: pre-wrap;
}

```

**Comment by sirreal** [comment]
This should be fixed for all users now.
