### ISSUE TITLE
Consider selling Quick Start sessions from My Home

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#48804]
**What**

Add a banner or a sub-section to My Home to upsell Quick Start sessions to make them easier to find.

**Why**
(Required) Why are you requesting this feature?  Add a concise description of the problem this feature solves.

This was based on an HE request, since it's currently difficult to point users to the Quick Start sessions to purchase them.

Reference: p1610417237360900-slack-C02DQP0FP

**How**

We do have this banner on the Help screen; it could be duplicated on My Home:

<img width="1097" alt="Screen Shot 2021-01-12 at 10 31 55 AM" src="https://user-images.githubusercontent.com/2124984/104335479-667fb980-54c1-11eb-9b37-2b8bdfca51f8.png">

**Comment by jordesign** [comment]
This is a great idea - in terms of making it easier to point users to QS sessions. 

Whether or not that upsell _should_ be shown here seems as though it is part of the bigger discussion around priorities for My Home and what prompts/banners we should be showing more broadly.

I suspect that part of the Back to Basics: My Home pod's work could/should be to seek some clarity around that prioritisation of Calls to Action.

**Comment by jordesign** [comment]
Closing this as we're no longer actively selling QS sessions
