### ISSUE TITLE
AMP link in WP Admin does not work when site is not public

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#48814]
AMP is unavailable on sites that do not allow search indexing and we handle this inconsistently. On a site that is hidden from search engines the following behavior is present:

- The AMP panel is hidden at https://wordpress.com/customize/amp/k2testblog.wordpress.com
- The AMP link is present in WP Admin under Appearance > Amp, but the link it opens (https://k2testblog.wordpress.com/wp-admin/customize.php?autofocus[panel]=amp_panel) does not work unless the site is public.
 
The easiest fix would be hiding the AMP link in WP Admin when the site is hidden but I am not sure if hiding the feature (in Calypso and WP Admin) is ideal versus a message saying it will be available once public.

### Browser / OS version

Chrome 87.0.4280.141, OS X

### Is this specific to the applied theme? Which one?

No

### Does this happen on simple or atomic sites or both?

Simple

### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low

**Comment by getdave** [comment]
@kriskarkoski Could you confirm whether there is action here for Nav Unification. It seems like the item should be available but with a message saying only available once public.

@jordesign I'm not clear on whether this is a regression you spotted with Nav Unification or whether it's an existing problem on WP.com.

What type of site do I need to have AMP show up? What are the conditions that govern when it will appear?

Much appreciated.

**Comment by jordesign** [comment]
> I'm not clear on whether this is a regression you spotted with Nav Unification or whether it's an existing problem on WP.com.

My labeling may have been incorrect - feel free to change. My logic was that this is something _could_ be addressed as part of Nav Unification - not necessarily that it was caused by it 👍

> What type of site do I need to have AMP show up?

The AMP menu item will show up on Atomic sites when the AMP plugin (which we bundle and activate) is active.

@kriskarkoski may be able to clarify further though.

**Comment by obenland** [comment]
Removed nav unification label so we can focus on regressions

**Comment by Robertght** [comment]
I can confirm this is still happening.

**Comment by wojtekn** [comment]
We removed AMP support for Simple sites on July 11th, 2022 so this issue is not actual anymore. pdKhl6-lx-p2#comment-368
