### ISSUE TITLE
Signup: Logging in to existing account at end of signup flow loses newly created site

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#48817]
#### Steps to reproduce

1. Starting logged out, select "Create account" to start the signup flow.
2. Go through site creation steps until you reach the "Create your account" screen.
3. Select "Already have a WordPress.com account?" or enter an existing account email/username and select "log in now."
4. Notice you are taken back to the initial login screen. Enter your login details for the existing account.

#### What I expected

I expected to be able to log in to an existing account and have the new site created in that account.

#### What happened instead

I was logged in to the existing account but the new site was not created.

#### App Version / OS version

WPDesktop 5.1.0-beta1 / macOS 10.15.4

#### Screenshot / Video

![wpdesktop-signup-existing-account](https://user-images.githubusercontent.com/8658164/80211538-d1384e80-862d-11ea-8ee7-7456c627f5d2.gif)

#### Context / Source
#beta-testing

**Comment by xpurichan** [comment]
I just tested this behavior in the WordPress app version 6.9.0 on MacOS 10.15.7 and was able to replicate the problem exactly.

Adding the "Type: Bug" to this report.

**Comment by Robertght** [comment]
I cannot replicate this anymore with WordPress app 7.2.0. 

Closing.
