### ISSUE TITLE
Payment Methods: assigning stored cards and PayPal to subscription should enable auto-renew

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#48818]
To solve the main part of https://github.com/Automattic/wp-calypso/issues/48736 (and to match the behavior of adding a new card to a subscription, which already works this way).

**Comment by DavidRothstein** [comment]
This is being fixed internally, and up for review there: D55306-code

**Comment by DavidRothstein** [comment]
Deployed.
