### ISSUE TITLE
Desktop app: Unable to use editor immediately after Atomic upgrade

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#48819]
### Steps to reproduce

In the Desktop app:

1. Upgrade a Simple site by purchasing an eCommerce plan with custom domain
2. Click the "Write" button

User is transported to the "Uh-oh" splash page, indicating that a request failed.

Note: if the user toggles SSO for their new site to "on" (outside of the Desktop app), they will be able to proceed as expected. 

_Notes_:

My guess here is the redux state for the site is stale after the upgrade is complete, and so Calypso/the Desktop app is unaware of the site's Atomic status, leading to the error.

**Comment by designsimply** [comment]
Adding a quick screenshot + error as text for reference:

> WordPress.com ran into an error! (code 105)

![screen-shot-2020-12-18-at-dec-18-5 06 33-pm](https://user-images.githubusercontent.com/1119271/104390093-27218f00-54fa-11eb-8b69-719b1fc57e23.png)
<sup>Tested with WPDesktop 6.7.0-beta2 on macOS 10.15.6 on madefortesting121820.wordpress.com (eCommerce Plan) with custom domain madefortesting121820.com (added just prior) and logged in as testuser121820. (internal reference: p5T066-1Ge-p2#comment-6676 #beta-testing)</sup>

Aside: I must admit that giant emojis as part of error splash screens should make me feel terrible but I actually think they're super cute! LOL. 😕   Although they are surely not nearly as cute if you're getting stuck and cannot edit and I'm sorry about that if you're facing this bug. If you're facing this problem you can do what nsakaimbo suggested by going to My Site > Settings > Security and toggling the SSO setting there. ([2m4s](https://cloudup.com/cijqUacp1bE))

**Comment by nsakaimbo** [comment]
This issue is no longer applicable given the recently overhaul of the Desktop application's architecture - closing.
