### ISSUE TITLE
Nav Unification: All Sites mode

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#48824]
All Sites mode is currently broken as Nav Unification seems to expect a selected site at all times.

#### Steps to reproduce the behavior

1. Go to https://wordpress.com/posts
2. Click on Upgrades > Domains (should work, but without a null query arg)
3. Click on Upgrades (site selector shows up, not an All Sites screen)

![image](https://user-images.githubusercontent.com/1398304/104361030-c3ca3980-54c6-11eb-85ee-dc191bc1acd7.png)

**Comment by cpapazoglou** [comment]
Only the following menus support "All sites screen"
![](https://cln.sh/jOIqBM+)

Upgrades, doesn't seem to be any of them. So we can either keep it and let it redirect to Site Selector or remove it.
