### ISSUE TITLE
Editor: Persistent Autosave message, even after saving Post

### ISSUE THREAD

**Issue by isocialtish** [Automattic/wp-calypso#48847]
#### Steps to reproduce the behavior
1. Add content to a post and Publish
2. Delete content from the post
3. Click Update, wait for this change to save.
4. Click "Back" button in browser.
5. Return to the page and see auto-save message. 

#### What I expected to happen
After I delete text, save the change, and come back I shouldn't see "The backup of this post in your browser is different from the version below." and sometimes it will say "There is an autosave of this post that is more recent that below". 

### Browser / OS version
Chrome Version 87.0.4280.88
Mac OS High Sierra 10.13.6

### Level of impact (Does it block purchases? Does it affect more than just one site?)
This is starting to consistently come up in chats. Today alone I've seen it 3 times in chat, others are getting reports too, in addition, I see this when editing my own personal sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
"There is an autosave of this post that is more recent that below" error
https://d.pr/v/GoVLzp

"The backup of this post in your browser is different from the version below."
https://d.pr/v/dAwlSb
(it takes me a few times of deleting content for it to appear around the 1 min mark)

**Comment by galakhyati** [comment]
The user mentioned they are experiencing the issue on all the new articles and not just on the sample they shared in the chat. 

Ticket: 3644774-zen

**Comment by cathymcbride** [comment]
Gutenberg 9.7.2 was deployed today which should fix this. I am no longer able to repro.

**Comment by cathymcbride** [comment]
Adding to the QS backlog to make sure we have automation that captures this case and cases like it.

**Comment by worldomonation** [comment]
Maybe good as part of https://github.com/Automattic/wp-calypso/issues/55950.

**Comment by worldomonation** [comment]
Should be dealt with in #48847.
