### ISSUE TITLE
SEO Tools: eligible plans are prompted to upgrade in order to show previews

### ISSUE THREAD

**Issue by kbrown9** [Automattic/wp-calypso#48841]
#### Steps to reproduce the behavior

1. Create a Jetpack site with a Jetpack Security Daily, Jetpack Security Real-time, or Jetpack Complete plan.
2. Go to Tools > Marketing > Traffic, and make sure "Enable SEO Tools to optimize your site for search engines" is enabled.
2. Scroll down to the "Website Meta" section and click the "Show Previews" button.

#### What I expected to happen

I expected to see the previews.

#### What actually happened

A pop-up appears telling me I need to upgrade to a Business plan, and there are no previews.

<img width="1097" alt="Screen%20Shot%20on%202021-01-12%20at%2018-08-27" src="https://user-images.githubusercontent.com/50059399/104385456-4243cd00-5501-11eb-93cd-5fe003e49cea.png">

**Comment by retrofox** [comment]
Hi, there. I tried to reproduce the issue following the flow described, and it wasn't possible. It doesn't show me the notice bar about upgrading the plan. I tested using the `Jetpack Security Daily` plan.
I'll try again.

**Comment by kbrown9** [comment]
> I tried to reproduce the issue following the flow described, and it wasn't possible. It doesn't show me the notice bar about upgrading the plan. I tested using the Jetpack Security Daily plan.

Hmm, I just retested on a site with Security Daily Monthly, and I'm still seeing the notice to upgrade to a Business plan, exactly as shown in the screenshot.

Are you seeing the previews?

**Comment by retrofox** [comment]
sorry, I got it!
![image](https://user-images.githubusercontent.com/77539/106020156-367c0d00-60a2-11eb-9ff2-288980923331.png)

Thanks

**Comment by kraftbj** [comment]
Note that, although it was sidetracked, we're going to be moving this to our free plan soon. https://github.com/Automattic/jetpack/pull/17309

Ground Control will be picking up and getting it across the line in March, so ideally shipping in the April 6th release.

**Comment by pablinos** [comment]
In #49504 I'm adding this feature to the new Jetpack plans, but the nudge still talks about upgrading to a Business plan. What do you think about going a step further and making the feature enabled for all Jetpack sites now @kraftbj?

**Comment by kraftbj** [comment]
Without objection, that sounds great. I don't recall immediately what Jetpack-side changes are needed, but I can shift someone to look at it next week.

**Comment by pablinos** [comment]
I've update #49504 to open this up to all Jetpack plans. Jetpack redirects to Calypso for these settings, but there is a nudge to upgrade in the settings panel for sites that are currently ineligible for the feature. That will need a follow-up PR in Jetpack, but this change should fix the issue on the Calypso side.
