### ISSUE TITLE
Desktop app: "Write" for Jetpack sites redirects to /wp-admin/post-new.php?post_type=post

### ISSUE THREAD

**Issue by macmanx2** [Automattic/wp-calypso#48840]
#### Steps to reproduce the behavior

1. Open the Desktop app
2. Click on Write for any Jetpack site.

#### What I expected to happen

That the post editor would open in the app.

#### What actually happened

You'll be sent to the site's /wp-admin/post-new.php?post_type=post in your system's default browser.

#### Context

Initially reported at https://wordpress.com/forums/topic/wordpress-com-desktop-app-for-macos-6-7-0-redirects-to-wp-admin/ and confirmed with 2 of my own WordPress.org sites on 2 different hosting providers, running WordPress 5.6, Jetpack 9.3 as the only active plugin, and Twenty Twenty-One 1.1 for the theme.

### Browser / OS version

I am only able to test this with the Mac desktop app, using the current 6.7.0 stable release.

### Level of impact (Does it block purchases? Does it affect more than just one site?)

With the user's and my testing, this affects 3 out of 3 tested sites for sure, but I think it's safe to assume this affects all sites.

**Comment by annacmc** [comment]
I was not able to repro this any longer using WordPress Mac Desktop app 6.12.0 on a WordPress.org site with Jetpack 9.5.2. I have previously noted this issue before, and it seems to have been resolved with a recent update. Going to close this up.

 @macmanx2 are you still able to repro this with your testing sites? Is so, we could re-open.

**Comment by macmanx2** [comment]
Yes, essentially this is fixed now by this informative alert:

<img width="274" alt="Screen Shot 2021-03-25 at 11 04 34 AM" src="https://user-images.githubusercontent.com/4856235/112521615-f2cc1980-8d59-11eb-9c78-f44ade09069a.png">
