### ISSUE TITLE
New Onboarding: add translated design thumbnails

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#48867]
At translated version of the New onboarding flow (https://wordpress.com/new/design/es), design thumbnails are in English.

Let's get them translated, so that the first impression is better for non-English speakers.

<img width="1729" alt="Screenshot 2021-01-13 at 15 42 10" src="https://user-images.githubusercontent.com/87168/104460055-467df200-55b6-11eb-9ae7-fbee26b47e39.png">

In the preview translations work just fine:

<img width="1731" alt="Screenshot 2021-01-13 at 15 42 03" src="https://user-images.githubusercontent.com/87168/104460208-73caa000-55b6-11eb-9a49-dae7061277eb.png">

Perhaps for starters we just generate static screenshots for all the locales we support? I know it's a lot of images ...but so what? 😅

**Comment by simison** [comment]
Potential solution in https://github.com/Automattic/wp-calypso/pull/43428

**Comment by ramonjd** [comment]
> I know it's a lot of images ...but so what? 😅

320+ images. It's probably worth the initial investment, but long term I'd say it's unsustainable. 

As discussed, maybe we could try mshots + landscape?

Commented to that effect in the ongoing PR: https://github.com/Automattic/wp-calypso/pull/43428#issuecomment-759771727

**Comment by ramonjd** [comment]
I'll add that there's a slight hurdle to overcome with systems on allowing vertical screenshots. Maybe we could try to escalate that again for later?

pMz3w-bQy-p2#comment-83292

**Comment by simison** [comment]
I'll re-open since this is still in English in production, while we wait for solutions to get deployed.

**Comment by simison** [comment]
Sorted in https://github.com/Automattic/wp-calypso/pull/49170, some follow-ups in https://github.com/Automattic/wp-calypso/issues/49097
