### ISSUE TITLE
WoA subdomain used for WoA Atomic site

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#48863]
Revert an WoA site (P9HQHe-jY-p2) with Nav Unification turned on.

All Nav items are still using the WoA subdomain `.wpcomstaging.com` and have not reverted to the Dotcom Simple subdomain `.wordpress.com`.

@obenland

**Comment by jmdodd** [comment]
This may be a caching issue.

**Comment by mmtr** [comment]
@getdave I tried to reproduce this on a fresh new site that I transferred to Atomic and then reverted, and the menus were updated correctly to the `.wordpress.com` subdomains again.

**Comment by getdave** [comment]
Thanks for testing @mmtr. Perhaps this was caching like @jmdodd suggested. Closing for now.
