### ISSUE TITLE
Site Editor: font previews are not working in Horizon flow

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#48866]
The font previews are broken in FSE Horizon signup flow again.

<img width="1552" alt="Screenshot 2021-01-13 at 14 39 41" src="https://user-images.githubusercontent.com/1182160/104459564-31509580-55ad-11eb-82b2-f8bf479447a1.png">

There are not working for both themes this time. Along with the fix it would be good to investigate what's causing the breakage every couple of weeks and document it.

**Comment by vindl** [comment]
@mattwiebe here is some possibly helpful context from last time https://github.com/Automattic/wp-calypso/issues/48148.

**Comment by mattwiebe** [comment]
Thanks for the context!

**Comment by mattwiebe** [comment]
D55390-code should fix the problem

**Comment by mattwiebe** [comment]
Fix deployed
