### ISSUE TITLE
Plans page showing incorrect price information about annual plans

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#48885]
It looks like right now the logged-in plans page is showing monthly prices for annual plans at https://wordpress.com/start/plans/

Pricing looks right but it's missing the per month /monthly indicator.

<img width="1426" alt="Screen Shot 2021-01-13 at 14 21 35" src="https://user-images.githubusercontent.com/31009008/104499823-a6bb6680-55ab-11eb-83a3-b95e7028a473.png">

<img width="1508" alt="Markup 2021-01-13 at 14 03 10" src="https://user-images.githubusercontent.com/31009008/104499834-a91dc080-55ab-11eb-934f-f6fd96ff6553.png">

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/start/plans

#### What I expected
To see the price as "per month, billed manually".

**Comment by JoshuaGoode** [comment]
Result of https://github.com/Automattic/wp-calypso/pull/48345

**Comment by JoshuaGoode** [comment]
For clarification, here's a quick mockup of what we're currently seeing vs what we should display. 

**Current**
![current](https://user-images.githubusercontent.com/4887830/104501504-d2d7e700-55ad-11eb-9116-45134ac7087e.png)



**Mockup of Expected**
<img width="1500" alt="expected" src="https://user-images.githubusercontent.com/4887830/104501382-a3c17580-55ad-11eb-8446-7c40f3cdcae5.png">

**Comment by cathymcbride** [comment]
removing from manage board, as marketing has picked this up.

**Comment by desnum** [comment]
Another case at zen-3644290

**Comment by JoshuaGoode** [comment]
Internal discussion: p1610565872159700-slack-CT1FP5D62

**Comment by pottedmeat** [comment]
It looks like the "per month" is defined here: https://github.com/Automattic/wp-calypso/blob/3ba8fafe294c0f5a6d82ee96133676f086135a1d/client/my-sites/plan-price/index.jsx#L114-L122

`isInSignup` is passed here: https://github.com/Automattic/wp-calypso/blob/3ba8fafe294c0f5a6d82ee96133676f086135a1d/client/my-sites/plan-features/header.jsx#L381

using `displayFlatPrice` defined here: https://github.com/Automattic/wp-calypso/blob/3ba8fafe294c0f5a6d82ee96133676f086135a1d/client/my-sites/plan-features/header.jsx#L353

Any time `plansWithScroll` is `true`, the "per month" section won't be rendered.

This is how it looks if that block is rendered: 

![image](https://user-images.githubusercontent.com/38750/104516120-724ea700-55b9-11eb-8517-9f96cd421c62.png)

**Comment by sirbrillig** [comment]
So given https://github.com/Automattic/wp-calypso/pull/48890, does that mean that it's possible we might end up with "per month per month, billed annually"?

**Comment by pottedmeat** [comment]
Looks like it happened during #48345.

**Comment by danielwrobert** [comment]
It seems like we would want to assign `displayFlatPrice` to check for `isInSignup && ! isMonthlyPlan`, like we're doing [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plan-features/header.jsx#L227)? I haven't tested that to confirm anything yet though!

**Comment by danielwrobert** [comment]
> It seems like we would want to assign `displayFlatPrice` to check for `isInSignup && ! isMonthlyPlan`, like we're doing [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plan-features/header.jsx#L227)? I haven't tested that to confirm anything yet though!

I'd like to retract this statement. We don't want to check against `isMonthlyPlan` because we want this text visible in both cases. Looks like @DavidRothstein got it right in [his PR above](https://github.com/Automattic/wp-calypso/pull/48893) though!
