### ISSUE TITLE
Upgrades: Data driven nudges

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#4888]
In `p10gg3-4kQ-p2` we have some great ideas about data-driven nudges:

The ones I see as actionable:

- [ ] Blogs with custom domains have nearly 4 times as many views as those without and seven times as many posts
- [ ] Premium blogs get 5 times as many likes as free blogs.
- [x] Blogs that switch to a premium plan see an average increase in likes of 31%.
- [ ] Premium blogs see about 40% more monthly views than unpaid blogs.
- [ ] Blogs with “video” product (not sure what this is, I’m assuming videopress?) get ~30 times as many views as blogs without, and have 8 times as many posts.
- [x] Blogs with a premium theme (with at least 1 view in the past week) received about 30 times as many views as blogs (with at least one view in the past week) without.
- [ ] Blogs with No Ads (again, with at least one view…) received about 60 times as many views as blogs without (…at least one…yada yada yada).

We have to be careful though, because WE CAN NOT SAY ITS CAUSATION.

**Comment by rralian** [comment]
Moving this to our backlog as we start our feature work.

**Comment by artpi** [comment]
I'm closing this down because we since abandoned these efforts.
