### ISSUE TITLE
Posts: comment count doesn't update when you add a reply

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#4889]
#### Steps to reproduce
1. Starting at URL: `/posts/{site}`
2. Click comment bubble if there are comments
3. Add a reply
4. Check that comment count in the post hasn't updated

We should update the count to reflect reality.

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue:
![wp-calypso-4889](https://cloud.githubusercontent.com/assets/7233112/16925159/e378b3de-4cf0-11e6-8428-32e5598e66e6.gif)

**Comment by lancewillett** [comment]
Confirmed this is still a valid bug — the comment count doesn't update, until you do a hard page refresh.
