### ISSUE TITLE
Global style font changes are not applying to editor text

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#48898]
Font changes are not being displayed in the editor as you change them. They are still changed when you click publish and are shown after a reload or viewing the page directly on the site.

The problem here is that you can't see the new fonts in real time as you flip between them.

#### Steps to reproduce the behavior
1. Editor
2. Click the "A" in the top right
3. Choose a new font

#### What I expected to happen
Font should change in the editor text

#### What actually happened
Font didn't change

### Is there any console output or error text?
No

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![2021-01-13 17 24 41](https://user-images.githubusercontent.com/811776/104538386-e186d280-566f-11eb-8807-d92270cfeffc.gif)

cc @noahtallen

**Comment by simison** [comment]
This is a theme bug though. It does work on Hever for example:

https://user-images.githubusercontent.com/87168/108082025-4fad2380-707a-11eb-9c5e-3d653634abaa.mov

@scruffian :wave: any known themes with this issue? I'm inclined to close until we know which theme specifically to replicate the issue with. @lsl remember the site's address you tested with?

**Comment by scruffian** [comment]
There's a report for Redhill here: https://github.com/Automattic/themes/issues/1687

The site address in the screenshots above is using Stratford but from what I can see it works fine in Stratford.

**Comment by simison** [comment]
Gotcha, thanks for checking! 👍  I don't think we'll have much use to have the issue open then. Feel free to re-open if needed tho! :-)
