### ISSUE TITLE
Feature Request: Table Block - provide an option to merge columns/rows in a table

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#48909]
Usecase: Deborah - Beginner blogger wants to post a blog with data in a tabular format.
There are some rows and columns she wants to merge to make table look good.

What
Add an ability to merge rows and/or columns in Table block

Why
merging columns/rows/cells can give user ability to group data and provides better visual representation for reader. 

How
- rowspan and colspan properties allow merging rows and columns respectively.
- Deborah wants to post data as in the image blow.
<img width="843" alt="Example for Merged Columns and rows using html" src="https://user-images.githubusercontent.com/77377635/104562533-5836b800-55fd-11eb-8f67-fae7b6615ea9.png">

 Html code used for example in screenshot is as below.
`<figure class="wp-block-table is-style-regular"><table><tbody><tr><td rowspan="2"><code><strong>Sr No</strong></code></td><td rowspan="2"><strong>Title</strong></td><td colspan="4"><strong>Device Models</strong></td></tr><tr><td>iPhone 12 Pro Max</td><td>iPhone 12</td><td>iPhone 12 Mini</td><td>iPhone 11</td></tr><tr><td>1</td><td>11</td><td>url</td><td>url</td><td>url</td><td>url</td></tr><tr><td>2</td><td>22</td><td>url</td><td>url</td><td>url</td><td>url</td></tr><tr><td>3</td><td>33</td><td>url</td><td>url</td><td>url</td><td>url</td></tr><tr><td>4</td><td>44</td><td>url</td><td>url</td><td>url</td><td>url</td></tr></tbody></table><figcaption>Screenshots on various iOS Devices with unique Device Form Factors</figcaption></figure>`

- Steps: 
  - Use Table block and then "Edit  as html" from menu and paste above code. 
  - In preview, layout looks good. in Edit mode Table block will show error and you can resolve it to html block. 
  - Html block is not easy to edit for blog writer. 
 It will be better if blog writer can see Table in edit mode and enter values or edit values in each cell as needed.

**Additional context**
- Few examples of merged cells or columns listed on [link](https://www.w3.org/WAI/tutorials/tables/irregular/)
- Confluence provide support for merging columns and rows and cells within table.

**Comment by Robertght** [comment]
This is something that can be added through the Gutenberg core. Closing in favor of this one: https://github.com/WordPress/gutenberg/issues/15821
