### ISSUE TITLE
Editor header on an unlaunched site looks cramped

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48922]
#### Steps to reproduce the behavior

1. Go to `/new` and create an new unlaunched Simple Site.
2. Once you land in the editor change your viewport to mobile sized.
3. Observe the header looking cramped like the image below.

![Screenshot 2021-01-14 at 13 58 12](https://user-images.githubusercontent.com/8639742/104600163-8c978c00-5670-11eb-94d8-f905e79f90f8.png)

#### What I expected to happen

TBD - We need clarity on how this should look, especially if something has to give.

#### What actually happened

The header looks buggy due to the cramped nature of the elements inside of it

![Screenshot 2021-01-14 at 13 58 12](https://user-images.githubusercontent.com/8639742/104600163-8c978c00-5670-11eb-94d8-f905e79f90f8.png)

#### Context
* pbAok1-1LS-p2#comment-3683

### Browser / OS version
* Chrome

### Is this specific to the applied theme? Which one?
* Not theme specific

### Does this happen on simple or atomic sites or both?
* Both

**Comment by yansern** [comment]
Temporary fix here. https://github.com/Automattic/wp-calypso/pull/49329
Related to https://github.com/Automattic/wp-calypso/pull/49079.
Closing this issue.
