### ISSUE TITLE
Premium Content Block: List View Icon is Missing White Version

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#48959]
#### Steps to reproduce
1. Create a new page
2. Add the Premium Content block
3. Click on the List View and select the Premium Content block

#### What I expected
That the block icon would turn white when selected, as the others do.

#### What happened instead
It's a black square when selected, you can't see the icon.

#### Screenshot / Video
This is the normal behavior you see on other blocks, black background with a white icon:
![WhatsAppIcon1](https://user-images.githubusercontent.com/16104522/104732427-fe78df80-571b-11eb-89a2-cb7acf12ae33.jpg)

And this is what happens with the Premium Content block:
![PremiumContentIcon](https://user-images.githubusercontent.com/16104522/104732458-0769b100-571c-11eb-851f-44b4e1905939.png)

#### Context / Source
#dogfooding

**Comment by Robertght** [comment]
I can't replicate this anymore @carinapilar 

Are there are other details that you could share with us so we can take a closer look?

I can see in the other issue, https://github.com/Automattic/wp-calypso/issues/48573 the background color is coming from the dashboard color scheme, but I'm not able to replicate it.

**Comment by carinapilar** [comment]
@Robertght, the icon is still only black, the issue is less impactful now because the background isn't also black as it was, it depends on the interface color palette, which I believe will never be all black.

You can see on the GIF below, that when you select the Paragraph block, its icon turns white, while this doesn't happen with the Premium Content one:

![WhiteIcon](https://user-images.githubusercontent.com/16104522/134669140-ae2a9687-941b-4fe4-8b79-60b1ed649b29.gif)

**Comment by Robertght** [comment]
Ah that makes sense now! Thank you!  cc @Automattic/flow-patrol-create to have a second look

**Comment by yansern** [comment]
**Investigation Note:**
Need to replace all `fill` & `strokeColor` values with `currentColor` in `extensions/blocks/premium-content/_inc/icon.js` (jetpack).

**Comment by arcangelini** [comment]
I made a PR to fix this one, but it looks like this is the natural way of all Jetpack blocks:

<img width="334" alt="Markup 2021-10-07 at 12 38 42" src="https://user-images.githubusercontent.com/33258733/136368955-048db7c8-54ed-4801-9789-d0f17ddc11f1.png">

They set the foreground color using a function that either defines the color as `#1e1e1e` or Jetpack Green for Jetpack/WPorg sites.

**Comment by arcangelini** [comment]
Made a PR to potentially address the Jetpack icon colors as well. 🤞 🤞
