### ISSUE TITLE
Gutenberg: 9.8 upgrade

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#48950]
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/48771
Release notes:
- [v9.8.0](https://github.com/WordPress/gutenberg/releases/tag/v9.8.0)
- [v9.8.1](https://github.com/WordPress/gutenberg/releases/tag/v9.8.1)
- [v9.8.2](https://github.com/WordPress/gutenberg/releases/tag/v9.8.2)
- [v9.8.3](https://github.com/WordPress/gutenberg/releases/tag/v9.8.3)

### Process

- [x] Install and activate
  - [x] Copy install activate on edge (D55451-code)
  - [x] Edge was reverted and should be redeployed (issue fixed by D55432-code)
  - [x] Copy 9.7.4 to 9.8.1 (D55827-code)
  - [x] Install activate 9.8.1 on edge (D55922-code)
  - [x] Install activate 9.8.2 on edge
  - [x] Copy 9.8.2 to 9.8.3 (D56301-code)
  - [x] Install 9.8.3 (D56307-code)
  - [x] Activate 9.8.3 on edge (D56309-code)
  - [x] Activate on production sites (D56316-code)
  - [x] Request update for Atomic sites (p9o2xV-1f5-p2)
- [x] Testing
  - [x] Calypso E2E (https://github.com/Automattic/wp-calypso/pull/48960, #49558)
  - [x] TC (D55935-code)
- [x] Publish internal announcements (p7DVsv-aoC-p2)
- [x] Update the Gutenberg Upgrade Log [pcoGjb-u-p2] and list patches applied.
- [x] Open a new issue for the next upgrade, transfer remaining tasks, close this issue. (https://github.com/Automattic/wp-calypso/issues/49534)
- [x] Roll back https://github.com/Automattic/wp-calypso/pull/49329 (can ping someone via pbAok1-1PR-p2#comment-3849)

### Issues / Blockers 🐛 

Cover block invalidates some attributes D55431-code
https://github.com/WordPress/gutenberg/issues/28242
https://github.com/WordPress/gutenberg/issues/28221 (also present in 9.7)
https://github.com/WordPress/gutenberg/pull/28627

### Fixes

…

FYI: @Automattic/good-mountain @tyxla @flootr @saramarcondes @griffbrad @inaikem

**Comment by fullofcaffeine** [comment]
This is done. Next one: https://github.com/Automattic/wp-calypso/issues/49534.
