### ISSUE TITLE
Checkout: Attempting to visit /checkout/[not your account you're logged in to]/premium should ask you for login

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#4895]
1. visit wordpress.com/checkout/[not your account you're logged in to]/premium
2. See a loading animation that never results in anything loading

I didn't notice at first that I was logged into another account when I visited this URL after following a link in an email about a trial account. Probably an edge case with multiple accounts but there should be some notice here.

![pasted image at 2016_04_20 09_21 am](https://cloud.githubusercontent.com/assets/545779/14679822/0ffe0b6c-06e1-11e6-9298-fdf4ede0ec51.png)

**Comment by lancewillett** [comment]
Thanks for the report—just to clarify, did you type the URL directly into the address bar, or navigate by clicking a link?

**Comment by ianstewart** [comment]
Via a link in an email WP.com is sending to users who have a free trial for the premium plan.

**Comment by lancewillett** [comment]
I'm able to repeat by logging in to a test account and simply typing in `https://wpcalypso.wordpress.com/checkout/premium`

![screen shot 2016-05-26 at 10 52 50](https://cloud.githubusercontent.com/assets/66797/15584564/020693ce-2330-11e6-8570-f7d8d34596c2.png)

If I do it logged out, I'm prompted to log in.

CC @fabianapsimoes for further triage and prioritization.

**Comment by fabianapsimoes** [comment]
This would be something for team Gold (cc @gziolo).

**Comment by gziolo** [comment]
I think we should redirect to site selection page with an error/warning notice. Do we have any idea what message should be presented to the user?

**Comment by fabianapsimoes** [comment]
cc @ranh @breezyskies ^

**Comment by peterbutler** [comment]
Gold will look at this later this week or next, pending the messaging help ^.

**Comment by ranh** [comment]
There are at least two different issues 

- Landing on a URL like `https://wpcalypso.wordpress.com/checkout/premium` or similar ones, as @lancewillett mentioned. I assume this is not part of any flow, and can be best described as taking a wrong turn somewhere. Do we need to show a notice here? Maybe just redirect to someplace more useful.
- Landing on a URL like `wordpress.com/checkout/not-the-account-you-are-logged-in-to/premium` or similar ones, as @ianstewart mentioned. This can be part of any number of flows and is actually a common issue that we had pre Calypso, too. Here we should show a notice but maybe not do a redirect?

I think that redirecting to site selector, or anyplace else really, is just repeating the same problem. A full-screen notice with minimal choice of next actions might be best. @breezyskies Any thoughts on that?

I could use more details about all the cases we want to cover here, but this might be a good flow for this specific scenario:

- Own multiple wpcom accounts.
- Add a free trial using one of the accounts (or, possibly, do anything that eventually leads to receiving an email with a link to checkout).
- Switch to another account.
- Receive the link to checkout and click it.
- See a full-screen message like this:

> Looks like you were trying to (whatever), but you are not logged in to the right account for that. Try [logging out and switching accounts](#), or just [go back home](#).

PS, I think we used to have something similar on WordPress.com at some point, I can't find any references at the moment though.

**Comment by breezyskies** [comment]
> I think that redirecting to site selector, or anyplace else really, is just repeating the same problem. A full-screen notice with minimal choice of next actions might be best.

Agreed. If the issue is that they are logged in to the wrong account, I don't think the site selector would really help here.

The full page notice (possibly using the current 404 / feature gate design) seems like the right direction. Can we include any information about which other account they need to log in to? Maybe the site address (which seems the most secure)?

**Comment by ranh** [comment]
Trying out a more developed version of this notice:

> Do you have more than one account on WordPress.com? 
>
> It looks like you were trying to do something on the site example.wordpress.com. You probably got here from a notice related to that site's plan or domain. But the account you are currently logged in with is not the account you need to use to manage example.wordpress.com.
>
> Try [logging out and switching accounts](#). Make sure you log in with the same account you originally used to add the domain or plan on example.wordpress.com.
>
> Think you're just in the wrong place? [Take me home](#).

Including the site address here should be fine since it's already in the URL. But I guess that's about all we can share here, so it's still pretty vague.

**Comment by lancewillett** [comment]
Re-testing this, it works much better now. Safari 10.0 on OS X 10.12.

Going to ttps://wpcalypso.wordpress.com/checkout/premium is redirected to https://wpcalypso.wordpress.com/plans/example.wordpress.com

![screen shot 2016-10-14 at 11 21 20](https://cloud.githubusercontent.com/assets/66797/19398207/5e14fed2-9200-11e6-9dad-8fbccef2f5fc.png)
