### ISSUE TITLE
Site Editor: font changes not applied in preview for TT1B theme

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#48973]
If you try to create a test FSE site through Horizon flow, you'll notice that choosing different fonts has no effect on page preview in Design picker step.

This works fine for Seedlet Blocks theme, but it's not working for Twenty Twenty One Blocks.

**Comment by ianstewart** [comment]
cc @kjellr @scruffian

**Comment by mattwiebe** [comment]
This will be fixed by D56110-code - notes in there on possible different approaches, unsure how @Automattic/theam would like this to land.

**Comment by scruffian** [comment]
It would be great if you could make the change in the public repo so that everyone can chime in: https://github.com/WordPress/theme-experiments

Thanks!

**Comment by mattwiebe** [comment]
@scruffian sure thing, opened https://github.com/WordPress/theme-experiments/pull/183

**Comment by kjellr** [comment]
Is this actually something that should be fixed there? My understanding is that WP.com's implementation of Global Styles will be updated to instead use the official one in core. 

If that's the case, then in the meantime I think it would make sense to modify the dotcom version of Global Styles to populate the theme's variables in addition to the ones it uses today. Rather than the other way around.

**Comment by scruffian** [comment]
Yeah you're right @kjellr, sorry @mattwiebe, I guess your patch was the right approach after all...

**Comment by mattwiebe** [comment]
Thanks @kjellr and @scruffian - we get there together, eventually. :)

The new patch is at D56218-code since I hadn't created one properly from the themes directory.

**Comment by mattwiebe** [comment]
The patch has been shipped and the horizon flow is previewing fonts for `tt1-blocks` properly.

**Comment by mattwiebe** [comment]
Re-opening because, in the process of deploying the latest `tt1-blocks`, this change got overridden. I've submitted an upstream patch: https://github.com/WordPress/theme-experiments/pull/196

The patch can be tested on dotcom: D56514-code

**Comment by scruffian** [comment]
I think I just fixed this with D56369-code

**Comment by vindl** [comment]
@scruffian @mattwiebe I just tested this with 9.9 on Dotcom and it appears to be working fine now.
