### ISSUE TITLE
Purchases: Notice text is incorrect after cancelling a domain purchased with credits

### ISSUE THREAD

**Issue by rads** [Automattic/wp-calypso#4898]
I registered a domain for testing and cancelled it a few minutes later. When I did this I saw the following notice:

<img width="944" alt="purchases wordpress com 2016-04-20 15-54-24" src="https://cloud.githubusercontent.com/assets/11401/14682803/4bb5aaaa-071f-11e6-8f10-ddb2edd76d95.png">

This isn't actually true. If a domain is cancelled within five days, it will get removed immediately from the user's account and should be available for registration again a few days later.

cc @fabianapsimoes

**Comment by fabianapsimoes** [comment]
Hm, I'm unable to reproduce this. I just registered and cancelled a domain, and this is what I see instead:

> testingplanwithoutdomain.com was successfully cancelled and refunded.

Can you consistently reproduce this, @rads?

> This isn't actually true. If a domain is cancelled within five days, it will get removed immediately from the user's account and should be available for registration again a few days later.

Just to be clear, the refund period for domains is two days, not five.

**Comment by rads** [comment]
@fabianapsimoes: It looks like this only happens when the domain was purchased with credits. I tested four cases:

- Store Sandbox **Enabled**

  - Paid with **Credits**  
    <img width="967" alt="purchases wordpress com 2016-04-25 20-31-58" src="https://cloud.githubusercontent.com/assets/11401/14796573/02868f7e-0b26-11e6-9601-3d97559d6115.png">
  - Paid with **Credit Card**  
    <img width="345" alt="purchases cancel domain wordpress com 2016-04-25 20-28-53" src="https://cloud.githubusercontent.com/assets/11401/14796558/e61bf8c4-0b25-11e6-8e8f-28e89494c241.png">

- Store Sandbox **Disabled**

  - Paid with **Credits**  
    <img width="967" alt="purchases wordpress com 2016-04-25 20-31-58" src="https://cloud.githubusercontent.com/assets/11401/14796573/02868f7e-0b26-11e6-9601-3d97559d6115.png">
  - Paid with **Credit Card**  
    <img width="647" alt="purchases wordpress com 2016-04-25 20-35-21" src="https://cloud.githubusercontent.com/assets/11401/14796565/f3301dd8-0b25-11e6-9f08-f6e2c93a8512.png">

In each case I registered a domain, got to the Thank You page, and immediately tried to cancel it on the Purchases page.

**Comment by fabianapsimoes** [comment]
Thanks for the details, Rads!

Seems when cancelling domains purchased with credits we want the notice to be something like:
>  domainName was successfully cancelled.

Updating the title to match the issue.
