### ISSUE TITLE
Premium Content: Editor freezes when hovering over Premium Content in block transformations menu

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#48984]
__Note: this issue is copied over from: https://github.com/WordPress/gutenberg/issues/28258__ CC: @druesome 

#### Steps to reproduce the behavior:

1. Create a new post or page on a site with a paid plan
2. Type in some text into a paragraph block
3. On the toolbar above the paragraph, click the P icon to transform it to a different block
4. Hover mouse over different choices without clicking anything. Hover over the Premium Block option a few times until editor freezes up and becomes unresponsive.

#### What I expected to happen

To be able to choose which block to transform to without the editor freezing up.

#### What actually happened

Editor freezes up after hovering over Premium Content option.

#### Context

* Gutenberg version 9.7.3
* Tested on Chrome and Firefox

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

In this screencast I start off with a regular paragraph. As I 'm transforming the paragraph, I'm avoiding the Premium Content block on purpose. I transform the paragraph to a list, then to a heading, before I finally over the Premium Content option. You will see that the editor freezes up afterwards.

Link to screencast: https://d.pr/v/Gt74q3

**Comment by andrewserong** [comment]
In the normal block styles preview in the inserter, we skip running the API call in the premium-content block by setting the `isPreview` attribute. In the block transformations menu, however, it attempts to run the block transformation with the real block content a user has entered, which means that Gutenberg attempts to render the full block within the preview (https://github.com/wordpress/gutenberg/blob/d9d06f332d9c5057a19f8ad334625bcbce3e137a/packages/block-editor/src/components/block-switcher/block-transformations-menu.js#L32). In the case of the premium content block, this means that the API call for the block is fired, and it looks like the update to state when that API call resolves could be the culprit that's causing this to lock up.

A possible solution could be to add a conditional somewhere in the premium content block's [transform method](https://github.com/Automattic/wp-calypso/blob/2bfb726bef0183aa09ec203ed9013ec67e797740/apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/index.js#L135-L136) to detect whether or not the transform is happening within the context of a preview, and if so, set the `isPreview` attribute?

**Comment by andrewserong** [comment]
Just noting that the bug fix has been merged #48988, and will be deployed with the next ETK plugin release.

**Comment by druesome** [comment]
@andrewserong Just wanted to add that the bug also affects the app (beta version 6.8.0).  Would the fix also address it in the app?

**Comment by andrewserong** [comment]
Thanks for mentioning that @druesome! Yes, it should fix it in the desktop app, too once it's deployed since the affected code is running in a plugin (deploy PR is in review: https://github.com/Automattic/wp-calypso/pull/49098).

**Comment by andrewserong** [comment]
@druesome just an update that this has been deployed now, and I double checked in the Desktop app and it's fixed for me now. Let us know if you encounter it again, though!
