### ISSUE TITLE
Store menu link tooltip should appear on hover

### ISSUE THREAD

**Issue by becdetat** [Automattic/wp-calypso#48982]
This only applies to the tooltip used next to the Store menu link during sunsetting of the store in Calypso.

> The tooltip should appear on hover - currently it requires a click

**Comment by cathymcbride** [comment]
@becdetat can you add repro steps please?

**Comment by becdetat** [comment]
@cathymcbride this is being addressed in https://github.com/Automattic/wp-calypso/pull/48990 which is close to being merged (just having some CI issues). To test that PR check out that branch, go to a business site with the store enabled, and add `?flags=woocommerce/store-deprecated` to the URL, and the info icon should appear next to the "Store" menu item.
