### ISSUE TITLE
Me: verification code placeholder color hard adjustment for easier use

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#49]
When you are asked to add a verification code, the placeholder makes it hard to see it's a placeholder. This can be confusing for some users. I wasn't really thinking and ended up clicking verify thinking it has pre-filled. Of course it hadn't, but because the color was so slight it looked like it should be a proper input not a placeholder.

![](https://cloud.githubusercontent.com/assets/253067/10764630/fbe9f3ba-7cc6-11e5-87c6-0b8c49f20f6c.png)

Perhaps it should be a placeholder such as
> 6 digit code

**Comment by v18** [comment]
Closed in favour of #400
