### ISSUE TITLE
Domain Management: No option to add email forwarding for mapped domains

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#4900]
There's no option to add email forwarding for mapped domains.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage/{testsite.wordpress.com}

2. Click on a domain that has been mapped to WordPress.com, in my example I clicked on "siobhanbamber.com."

3. Next, select the "Email" option.

![email-forwarding](https://cloud.githubusercontent.com/assets/2998162/14685847/3fb01c18-072e-11e6-96bc-1b016c09b6ec.gif)

#### What I expected

I expected to find an option for forwarding emails sent to an @siobhanbamber.com address to my personal email account. Email forwarding is available for domains registered with WordPress.com and my expectation would be for the same option to be available for domains that are mapped.

#### What happened instead

There was no option to forward emails sent to an @siobhanbamber.com address. Instead, there was only a notice that Google Apps is not available for mapped domains.

<img width="815" alt="screen shot 2016-04-20 at 19 38 13" src="https://cloud.githubusercontent.com/assets/2998162/14686182/86c65ee0-072f-11e6-86eb-0bf98e3b30f5.png">

My only way to add email forwarding would be to contact WordPress.com support. See 355639-c for an example of this.

**Comment by BandonRandon** [comment]
This looks like a regression :( 

#605 is related which allows Google Apps for mapped domains, but we shouldn't prevent forwarding. Here is a screenshot of the older interface: 
![screen-shot-2016-04-14-at-6-00-02-pm](https://cloud.githubusercontent.com/assets/150348/14686553/0c0b64de-06ee-11e6-864c-25d19a33c45d.png)

**Comment by graciemae** [comment]
Update: A user contacted us about this today. They already had email forwarding set up and wanted to edit one of the forwards. Their email forwarding does still work, but it's not editable.
