### ISSUE TITLE
Domains: Mapped domains hide email forwarding options

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#4901]
Right now, mapped domains do not offer email forwarding, instead showing a "google Apps is not supported on this domain" message:
![screen shot 2016-04-20 at 11 35 08 am](https://cloud.githubusercontent.com/assets/8921630/14686174/75b5b1ca-06ec-11e6-93e1-afb71a42ed40.png)

Mapped domains should function more like Registered domains, offering email forwarding as another option:
![screen shot 2016-04-20 at 11 39 36 am](https://cloud.githubusercontent.com/assets/8921630/14686217/93d0a25a-06ec-11e6-95c0-fb5900062d81.png)

#### Steps to reproduce
1. Starting at URL: wordpress.com/domains/ (with an account/site with a mapped domain)
2. Click on the mapped domain
3. Click on email
4. Notice the error message - and the only option forward is to "Add a Custom Domain"

#### What I expected
To see an alternate option to Email Forwarding

#### What happened instead
No such option was presented.

#### Browser / OS version
Chrome 49.0.2623.112 and Mac 10.11.4

#### Screenshot / Video
See above

**Comment by kriskarkoski** [comment]
Looks like @SiobhyB beat you by a few minutes #4900. Closing in favor of the older issue :)
