### ISSUE TITLE
Jetpack Backup: Everything is mis-aligned :)

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#49040]
I was reading this [CSS Tricks post about WordPress.com](https://css-tricks.com/wordpress-com-business-plan/) and noticed that one of the screenshots looked like it was busted:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/191598/105058636-6c871480-5a44-11eb-9f85-24f8c8a5536e.png">

I thought there must have been some caching or other rendering issue, but no, this is how the backups screen looks in production. There's a lot of weird alignment issues, specifically a few highlighted in the following image:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/191598/105058501-46fa0b00-5a44-11eb-8328-456f8fc59cd4.png">

Perhaps there could be some work done to fix some of the alignment, layout, typography, and other visual issues?

**Comment by folletto** [comment]
Thank you for the issue. We know we have to work on it, but let's see if we can slip in something for now. :)

Specifically:

1. Try to remove the special styling we have in Calypso Blue compared to Calypso Green, which also should improve maintainability.
2. Fix alignments overall.
3. Reintroduce calendar and search which seem not appearing on Calypso Blue (there might be a reason, but let's see).

/cc @eeeeevon13 and @monsieur-z how much of this can we fix quickly?

**Comment by monsieur-z** [comment]
> Try to remove the special styling we have in Calypso Blue compared to Calypso Green, which also should improve maintainability.
Fix alignments overall.

Fixing the alignment issues shouldn't take too much time. We might need to update components that are used elsewhere in the app though, so it might not be as trivial as it seems. Could we see mockups or captures with annotations of what needs to be moved around exactly?

> Reintroduce calendar and search which seem not appearing on Calypso Blue

What a timing, @eeeeevon13 and I started a conversation about that yesterday. Though Calypso and cloud share the same codebase, some features are only activated in one or the other environment. In this specific case, the date selector (aka calendar icon) was only enabled in cloud, for a reason I don't know. Maybe @Automattic/jetpack-voyager has some insights. As far as I can tell, it shouldn't be too difficult to enable in Calypso.

Note that the date selector is already implemented in Calypso in the Activity log.

**Comment by Robertght** [comment]
I'm not able to replicate the alignmens issue anymore on my end, but I'm wondering if it can be reviewed by someone else first.

![image](https://user-images.githubusercontent.com/6737345/136365079-4f45913f-d0d7-4d2d-8973-e9d11cedd2f1.png)


cc @monsieur-z

**Comment by Robertght** [comment]
I'm closing this one for now, but please re-open if needed.
