### ISSUE TITLE
Design Picker: Customize Blank Canvas post-site creation experience

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49048]
### What
Customize the user experience once they land in the editor after picking Blank Canvas from DesignPicker. Once the user lands in the empty editor, the patterns inserter modal pops up. After selecting a (blank) pattern, the modal closes, and the Welcome Tour is displayed.

### Why
Allow customers to skip picking design, and land them in the empty editor where they can explore adding patterns.

### A/C
- [ ] The patterns inserter modal is opened, straight after the user lands in the empty editor.
- [ ] Page Patterns modal shows a custom title: "Choose a Pattern".
- [ ] The Welcome Tour is shown after a pattern is selected.

**Context**
Let's test adding a "blank" start from scratch option to Design Picker using the Blank Canvas theme. The resulting site that we create would be the equivalent of the following, example starter design: PcJSWU-2-p2
If, for technical reasons, we need to actually have a starter design site as a source site, we can use that URL.

UX proposal: p9Jlb4-2qt-p2

**Follow-up**
- For FSE, we probably need to rethink the Blank Canvas experience https://github.com/Automattic/wp-calypso/issues/53050

***Note**: When implementing this feature, we assume that the Patterns inserter modal and the Welcome tour will be displayed for all the new sites

**Comment by kristenzuck** [comment]
Added this as a comment on the internal Happiness announcement, but as part of adding it to Gutenboarding, it'd be great to add a few guiding suggestions about how to use/learn more on Blocks and Patterns on the screen after activation :)

**Comment by simison** [comment]
x-linking the prototype https://github.com/Automattic/wp-calypso/issues/49141

**Comment by razvanpapadopol** [comment]
> it'd be great to add a few guiding suggestions about how to use/learn more on Blocks and Patterns on the screen after activation :)

An awesome on-screen guide is already included by @ollierozdarz in i1: p9Jlb4-2qt-p2

**Comment by razvanpapadopol** [comment]
D60468-code is adding a flag `is_blank_canvas` to site options and together with <s>draft PR https://github.com/Automattic/wp-calypso/pull/52113 that adds</s> Blank Canvas design added to `/new`, we should have all the necessary pieces in place to start looking into this one.

**Comment by razvanpapadopol** [comment]
There's a new design direction: p9Jlb4-2qt-p2#comment-3874

**Comment by roo2** [comment]
related: we now always show the welcome tour on newly created simple sites, we have a task to always show the tour on new atomic sites as well https://github.com/Automattic/wp-calypso/issues/52697

**Comment by yansern** [comment]
Why does `github-actions` love me that much?

**Comment by razvanpapadopol** [comment]
@ianstewart @simison, I've created https://github.com/Automattic/wp-calypso/issues/53050 to do something like this in FSE context
