### ISSUE TITLE
Store|Woo: Store deprecation notice looks too cramped in smaller screens

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#49060]
#### Steps to reproduce the behavior

1. Open WordPress.com in a small screen (i.e: iPhone 8) and select a business site with an existing Store set up
2. Look at the store deprecation notice, see the texts are too cramped together

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/3747241/105116156-25ad2380-5b05-11eb-8667-1a2ad5ad56da.png)

**Comment by mattsherman** [comment]
Agreed. We, should probably just get rid of the `max-width` on `.woocommerce .dashboard__store-move-notice p` when on the mobile breakpoint.

![Screen Shot 2021-01-20 at 17 00 15](https://user-images.githubusercontent.com/2098816/105246263-fcaa8400-5b40-11eb-8b58-41e46eafa2e6.png)

/cc @elizaan36 Do you have any concerns with us making this change?

**Comment by adrianduffell** [comment]
Fixed in #50078
