### ISSUE TITLE
Permission error in "Create your store" link in eCommerce plan purchase

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#49064]
#### Steps to reproduce the behavior

1. Purchase a new site with eCommerce plan
2. Wait for the thank you page to load
3. Click on 'Create your store' button
4. Observe the error page

#### What I expected to happen
It loads WooCommerce setup screen.

#### What actually happened
Error with the following text: `Sorry, you are not allowed to access this page.`

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Thank you page:
![image](https://user-images.githubusercontent.com/3747241/105132546-0ffc2600-5b26-11eb-99d9-c0f84ac89951.png)

Error page:
![image](https://user-images.githubusercontent.com/3747241/105132721-56ea1b80-5b26-11eb-80b3-4f0849dd2437.png)

**Comment by allilevine** [comment]
@ilyasfoo This seems to be happening again, any idea why that would be? The "Create your store" URL looks correct and opens on a second try or refresh, but clicking the button initially shows the permissions error. It looks like the login redirect may be failing.

https://www.loom.com/share/3db948ecc5dc4aefad814a168df3827d

**Comment by DustyReagan** [comment]
Just another observation. If you get to the thank you page, and instead of clicking the 'Create your store' button, open a tab and go to, say the posts wp-admin page, it loads fine. Then if you come back and click the button on the thank you page, it also loads fine. Something about hitting that WooCommerce setup page for the first time before hitting any other page.

**Comment by ilyasfoo** [comment]
@allilevine I think your assessment is correct. Previous error was caused by an outdated link, and refreshes did not result in a working page. This time around it might be something along the lines of the login redirect.

As observed by @DustyReagan, I think the login session might have not been properly set up by the time we access the page if that's the first thing we try to access on the site. Otherwise it would've worked fine.

I'm not sure at this point if this is a WordPress.com issue or WordPress in general, I'm not familiar with these parts yet.

**Comment by allilevine** [comment]
> As observed by @DustyReagan, I think the login session might have not been properly set up by the time we access the page if that's the first thing we try to access on the site. Otherwise it would've worked fine.

Thanks @ilyasfoo. I've opened a PR to set up a login session before attempting to access the page: https://github.com/Automattic/wp-calypso/pull/55029 We use the same `WpAdminAutoLogin` component in the plugin and theme transfer to Atomic flows.
