### ISSUE TITLE
Editor: Toolbar pinning does not update if header/title height change

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4907]
If the height of elements in between the top of the page and the editor toolbar changes (for example due to adding/removing a featured image or editing a multiline title) then the toolbar may need to pin or unpin.  Currently this does not happen until the next scroll event:

![toolbar-pinning-height-changes](https://cloud.githubusercontent.com/assets/227022/14690859/dc41ec7a-0713-11e6-85bb-1949373ca1f1.gif)

Noticed while testing #4824.

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue in OSX Chrome v51

**Comment by rachelmcr** [comment]
Closing as this is specific to TinyMCE and the behavior will change with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
