### ISSUE TITLE
Blog Post Block - Grouped text calls ungrouped text in live site as post excerpt instead of first paragraph

### ISSUE THREAD

**Issue by susanjanec** [Automattic/wp-calypso#49077]
#### Steps to reproduce the behavior

Create a post with a group block with text, followed by a paragraph block that is not grouped.

Add the blog post block to another page referencing the post with the group block.

#### What I expected to happen

The excerpt text displaying in the Blog Post block on the live page shows the text that is not grouped further down the page instead of the first paragraph of text. 

<img width="1628" alt="Screenshot on 2021-01-20 at 09-30-36" src="https://user-images.githubusercontent.com/16828966/105188772-3f993700-5b02-11eb-9c18-3b4140ebb6fb.png">

#### What actually happened

The Blog Post block will show the text in the ungrouped paragraph block (text further down the page) instead of the text in the first paragraph which should be the paragraph showing when Show Excerpt is toggled on - on the live page. However, the excerpt shows correctly on the edit page.

<img width="1615" alt="Screenshot on 2021-01-20 at 09-29-45" src="https://user-images.githubusercontent.com/16828966/105188810-47f17200-5b02-11eb-871c-1d8b2ed81263.png">

#### Context

Reported in 3662871-zd - removing the group block seems to fix it but there must be some other code that is calling that ungrouped text to show within the excerpt on the live site.

### Is this specific to the applied theme? Which one?

Tested on the Exford theme

### Does this happen on simple or atomic sites or both?

Only tested on a Simple site - Free plan

### Is there any console output or error text?

No

### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects user and my test site

#user-report

**Comment by sarahcada** [comment]
Also reported in 3672280-zd.  I was able to replicate on my simple site. 

### Is this specific to the applied theme? Which one?
I don't think so, since my test site was using the Rebalance Theme.

### Does this happen on simple or atomic sites or both?
I was able to replicate for both Simple and WPcom on Atomic.

**Comment by Greatdane** [comment]
I am unable to replicate this any longer on Simple or AT sites, closing for now.
