### ISSUE TITLE
Store|Woo: Site with existing Business plan subscription, but without WooCommerce, shows both Store and WooCommerce menu items

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49088]
An Atomic site with an existing Business plan subscription, but without the WooCommerce plugin, shows both "Store" and "WooCommerce" menu items. This is incorrect.

Both menu items should be shown for existing Atomic sites that have a Business plan subscription that started before Store deprecation **and already had** the WooCommerce plugin installed prior to Store deprecation.

Only the "WooCommerce" menu item should be shown for existing Atomic sites that have a Business plan subscription that started before Store deprecation **and did not have** the WooCommerce plugin installed prior to Store deprecation.

Originally reported on pbIJXs-y6-p2#comment-1651

#### Steps to reproduce the behavior

1. Select a site that is:
    - Business plan started before Store deprecation started
    - Atomic
    - Does not have WooCommerce installed
    
#### What I expected to happen

- Only the "WooCommerce" menu item show up in the My Sites sidebar

#### What actually happened

- Both the "Store" and "WooCommerce" menu items show up in the My Sites sidebar

<img width="266" alt="Screen Shot 2021-01-20 at 14 52 57" src="https://user-images.githubusercontent.com/2098816/105227602-86515600-5b2f-11eb-9e83-31747def9b85.png">

#### Notes about addressing

- We should only show the "WooCommerce" menu item in this scenario.
- We need to be careful to make sure that once WooCommerce is installed, that the "Store" menu item does not reappear.
- This will likely require us to somehow mark that the site installed WooCommerce after Store deprecation (maybe with a site option). Then, we can use that, along with the check if the Business plan subscription started before Store deprecation, to make sure we keep "Store" hidden.
    - We could potentially hook into the workflow where we kick off the installation of the WooCommerce plugin. This has the nicety of keeping Store deprecation changes strictly in Calypso. That wouldn't cover the scenario where a user manually installed the WooCommerce plugin though. Not sure that is a big deal though... they would experience the deprecated Store experience, which isn't ideal, but they would be warned (as existing users are currently). Or,
    - We could potentially hook into the activation of the WooCommerce plugin on the WordPress.com backend... I would imagine there is a hook for plugin activation that we could hook into and store a timestamp.

**Comment by mattsherman** [comment]
Using ideal dev days as the scale, and noting that a PR is in progress for this, I'm estimating this at a 2 (using this estimate to help plan next sprint). @becdetat , please update if I'm off-base and let me know!

**Comment by becdetat** [comment]
@mattsherman 2 _seems_ appropriate however I hit a snag when trying to store the install timestamp and I've already spent about 2 developer days on this.
