### ISSUE TITLE
Jetpack Backup section doesn't work as expected in app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#49082]
The whole Backup section on Jetpack sites doesn't seem to work well in the app. Issues includes:

* Backup page doesn't refresh after first backup until app is restarted.
* Backups can't be downloaded from the app.
* Trying to restore a backup leads to a blank screen.

I compiled these in a single issue because it might be worth considering whether the Backup section should be available in the app (compared to the cost of fixing each issue in the app), but let me know if it would be better to address these separately and I can split up the issues.

#### Steps to reproduce

Backup page doesn't refresh after first backup until app is restarted:

1. On the web, create a Jetpack site and connect it to a WordPress.com account.
2. Log in to that WordPress.com account in the desktop app.
3. Go to the My Sites section and select the Jetpack site.
4. Select Plan in the sidebar.
5. Select the Plans tab to view available plans.
6. Purchase a plan to get Jetpack backups.
7. Open the Backup section and note the message that no backups are available.
8. When you get a notification that your first backup is done, visit the Backup section again and notice the message hasn't changed.
9. Close and relaunch the app, and notice the Backup section now shows your first backup.

Backups can't be downloaded from the app:

10. On your latest backup, select "Download backup."
11. Choose what to include in your backup and select "Create downloadable file."
12. Wait until the file is ready, and then select "Download file" to try to download the file. Notice that the "Download file" button only opens the Backup page in a web browser.

Trying to restore a backup leads to a blank screen:

13. Go back to the main Backup page
14. Enter and save your site's SSH credentials.
15. Select "Restore to this point" to try to restore your latest backup. Notice that it takes you to a blank page.

#### App Version / OS version

WPDesktop 6.0.1-beta2 / macOS 10.15.5

#### Screenshot / Video

Backup page doesn't refresh after first backup until app is restarted:

![Screenshot 2020-07-16 10 53 15](https://user-images.githubusercontent.com/8658164/87658382-05666b80-c754-11ea-8f80-697a868d6be9.png)

Backups can't be downloaded from the app - the "Download file" button just redirects to the browser:

![Screenshot 2020-07-16 10 54 13](https://user-images.githubusercontent.com/8658164/87658387-07c8c580-c754-11ea-84b3-16a4b277d2d4.png)

Trying to restore a backup leads to a blank screen:

![Screenshot 2020-07-16 10 55 09](https://user-images.githubusercontent.com/8658164/87658395-08f9f280-c754-11ea-9364-24a648d6ab16.png)

#### Context / Source
beta-testing

**Comment by ChaosExAnima** [comment]
@nsakaimbo - I just tested and things seem okay now? I was able to view backups and successfully download it from the desktop app (it opens a web tab, but immediately downloads the file and closes). I didn't try restore but I suspect that's also fine.

Can we retest this? Happy to take point but I'd prefer someone familiar with the desktop app to check things out!

/cc @monsieur-z @rcanepa
