### ISSUE TITLE
Signup with Google returns "An unexpected error occurred" error

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#49080]
#### Steps to reproduce the behavior

1. Go to 'https://wordpress.com/start/user'
2. Click on 'Continue with Google'
 
#### What I expected to happen
Proceed to account creation. 

#### What actually happened
Does not proceed to the account creation, with `An unexpected error occurred. Please try again later.` error. 

Video here: https://d.pr/v/AIYCgC/AOQWytT7ae

### Browser / OS version
Firefox 84.0.2 (64-bit)
Big Sur 11.1

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Video here: https://d.pr/v/AIYCgC/AOQWytT7ae

Seems related to this issue #49062 

-------------------------------
zd-3655476

**Comment by yansern** [comment]
Fixed with PR https://github.com/Automattic/wp-calypso/pull/49607.
