### ISSUE TITLE
Invitation emails can be sent in the site language instead of the user's Calypso UI language

### ISSUE THREAD

**Issue by mirka** [Automattic/wp-calypso#49111]
Invitation emails will be sent in the site language instead of the invited user's Calypso UI language _if the user's language is English_.

#### Steps to reproduce the behavior

1. Set a site's language to French. `https://wordpress.com/settings/general/<site-url>`
1. Set a test user's Calypso UI language to English. `https://wordpress.com/me/account`
1. Get the test user's email address and invite them to the site. `https://wordpress.com/people/new/<site-url>`

#### What I expected to happen

Invitation email is in English, the invited user's language.

#### What actually happened

Invitation email is in French, the site language.

This does not happen if the invited user's language is _not English_, e.g. Japanese. (The email is in Japanese, as expected.)

### Is this specific to the applied theme? Which one?

No

---

Originally reported at p9lV3a-1Tz-p2#comment-2726

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to reproduce this issue with Firefox 94.0a1, macoS Big Sur 11.6 with the following steps:

1. set language of User A to Japanese.
2. set language of User B to English.
3. User A invites User B.
4. check invitation email received by User B.

The invitation email received was in the language selected for User B, as expected. See attached screenshot.

![Screen Shot 2021-10-05 at 2 49 15 PM](https://user-images.githubusercontent.com/6549265/136107743-e6a07ec1-b9f3-40e4-baf8-9bd149fd6ee8.png)

For sake of completeness, I have also tested the reverse scenario:

1. set language of User A to English.
2. set language of User B to Japanese.
3. User A invites User B.
4. check invitation email received by User B.

In this case the received email was in Japanese, the UI language chosen by User B, as expected.

![Screen Shot 2021-10-05 at 2 52 11 PM](https://user-images.githubusercontent.com/6549265/136108012-1c0f9e78-a230-4e14-aefb-b0ebc942e2ed.png)

I will close this issue as `not reproducible` for now.
If this issue should remain open, please feel free to re-open this bug.
