### ISSUE TITLE
Editor: Upload via URL button is truncated

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4911]
#### Steps to reproduce
1. Go to Editor
2. Click add media button
3. Click on Add via URL button

Doesn't matter what size the viewport is, it's still truncated.

#### Browser / OS version
Safari 9.0.2

#### Screenshot / Video

![screen shot 2016-04-20 at 5 26 44 pm](https://cloud.githubusercontent.com/assets/618551/14692512/5030fca8-071d-11e6-96d0-39b99d4f8dac.png)

**Comment by designsimply** [comment]
Noticed this while testing a different issue. The upload button in the media modal does seem prematurely truncated for wide screens.

![screen shot 2016-05-19 at thu may 19 8 02 15 am](https://cloud.githubusercontent.com/assets/1119271/15398398/55f70c72-1d98-11e6-8965-610072fe0c3f.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10077 using Safari 9.1 on Mac OS X 10.11.4</sup>
