### ISSUE TITLE
Nav unification should show many fewer options for domain-only sites

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#49128]
#### Steps to reproduce the behavior

To see many menu options that shouldn't be available, you need to have a domain-only site. If you don't have one, you can set one up by going to https://wordpress.com/domains and following the flow to purchase only a domain (which results in you also getting a domain-only site created).

Once you have a domain-only site:
1. Click on pretty much any link in the left hand menu.
2. You (correctly) stay on the screen showing you actions you can take with your domain, but the nav updates in really weird ways.

<img width="1609" alt="nav_unification_domain_only" src="https://user-images.githubusercontent.com/3376401/105376378-57f87700-5c12-11eb-9804-ea5114e5b1d1.png">

> Side note: domain-only sites exist as a way to support users buying only a domain (but under the covers it is linked to a site). Regardless of whether this make sense, we still have these sites.

#### What I expected to happen

The menu should only show options that are relevant to domain-only sites.

#### What actually happened

I got shown a really long menu, but clicking on the items didn't seem to do anything (other than change the state of the nav).
For some menu items, the nav disappears, but the content from the screenshot above remains. This happens for Posts -> Add New and Appearance -> Customize at the very least.

### Browser / OS version
Chrome 87.0.4280.141 (Official Build) (x86_64) on Mac OS Catalina 10.15.5

### Does this happen on simple or atomic sites or both?
This is limited to simple sites.

### Is there any console output or error text?
Nope -- console is silent.

### Level of impact (Does it block purchases? Does it affect more than just one site?)
I'm not sure how many domain-only sites we have in total, but it's probably (?) at least in the thousands?

**Comment by getdave** [comment]
@daledupreez Thanks for the report. We'll run through this in Production as a non-a12 and see what we can find out.

Do you have any additional context regarding the meaning of "domain-only site"? It's not something I'm familiar with.

Much appreciated.

**Comment by klimeryk** [comment]
@getdave Domain-only sites are one of our flows in signup. See wordpress.com/domains. It's definitely much smaller than our other flows (in term of users), but it's there. See P6Ya1B-gw-p2.

This change drastically changes that behaviour, because these "sites" should not allow adding posts, etc. - _just_ managing the domain or adding a plan (see the original screenshot). The site is "forced" to always show a parked page and 95% of the sidebar does not make sense in that context. To "unlock" the usual features, they need to buy a paid plan.

It'd be great if this could be fixed before we launch to 100% existing users 🙏

**Comment by getdave** [comment]
This has now reached our project board and we're looking to start work on it.

**Comment by mmtr** [comment]
A fix for this is ready for review/testing in D59042-code.

**Comment by mmtr** [comment]
Fixed in r223208-wpcom.
