### ISSUE TITLE
"My Sites" inactive on Atomic site

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#49122]
"My Sites" at the top left is unresponsive.

#### Steps to reproduce the behavior

1. Go to https://wpcourses.com while logged in as an admin on the site
2. Click on "My Sites" at the top left

#### What I expected to happen

Clicking "My Sites" should open the dashboard.

#### What actually happened

The link is unresponsive, and the URL in the address bar changes to https://wpcourses.com/#

### Browser / OS version

Firefox 84.0.2
MacOS 10.15.7 

### Does this happen on simple or atomic sites or both?

This site is Atomic.

I tried to replicate on other Atomic sites, but all my other Atomic sites display only a WordPress logo at the top left instead of the "My Site" link for some reason.

### Is there any console output or error text?

I see only some warnings, no errors.

### Level of impact (Does it block purchases? Does it affect more than just one site?)

Unsure as I haven't been able to replicate on other sites yet

#### Screencast

https://d.pr/i/8LXYHO/VVWNIJmYIw

**Comment by obenland** [comment]
@cpapazoglou This doesn't seem to work in both wp-admin and the front-end of the site. It looks like `admin-menu.js` needs some work.

I also noticed this:
![image](https://user-images.githubusercontent.com/1398304/105397537-0cc07300-5bd6-11eb-979b-333e7b72534c.png)

**Comment by mmtr** [comment]
@kathrynwp just FYI, I added myself as an admin, just in case you receive any notification.

For folks trying to reproduce this, you need to sign in as an admin (check "WordPress.com Courses P2 and Sensei Account" credentials in Secret Store) and then go to https://wordpress.com/people/team/wpcourses.com so you can yourself as an admin of the site.

**Comment by mmtr** [comment]
I can reproduce this on other Atomic sites as well, it's not specific to wpcourses.com
