### ISSUE TITLE
Custom Post Types Missing in Nav Unification (Longreads.com)

### ISSUE THREAD

**Issue by kristastevens** [Automattic/wp-calypso#49121]
1. Go to https://wordpress.com/posts/longreads.com

#### What I expected to happen
I expect to see Custom Post Types in my navigation menu including "Picks," "Authors," and "Publishers." 

![Screen Shot 2021-01-21 at 8 26 57 AM](https://user-images.githubusercontent.com/4358882/105366178-a41cca80-5bc4-11eb-98e5-1aa8f715550f.jpg)

#### What actually happened

I don't see our Custom Post Types for "Picks," "Authors," and "Publishers." They're missing. 
<img width="265" alt="Screen Shot 2021-01-21 at 8 25 55 AM" src="https://user-images.githubusercontent.com/4358882/105365475-e85b9b00-5bc3-11eb-99f6-df2530a4fc21.png">

### Level of impact 
This change affects our workflow. We need to be able to add "Picks," "Authors," and "Publishers" to the site on a **daily basis**. This is a part of our **core curation work**.

**Comment by obenland** [comment]
Hi @kristastevens, thanks for the report! I'll look at it right away.

To unblock you in the meantime, it looks like the menu items are available from wp-admin

**Comment by kristastevens** [comment]
Thanks for the speedy attention, @obenland! We'll use wp-admin links for the time being.

**Comment by obenland** [comment]
I got a (temporary) fix in D55785-code. 

@kjellr Any chance you're around to give this a quick look?

**Comment by obenland** [comment]
This should be fixed now!

@kristastevens Please feel free to re-open if it's not.

**Comment by kristastevens** [comment]
All good, ty for such a speedy fix, @obenland!
