### ISSUE TITLE
Nav Unification: Plugins no longer point to Calypso for Jetpack sites

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#49120]
#### Steps to reproduce the behavior

1. Go to `/stats/day/:site` where `:site` is a Jetpack (non-Atomic) site.
2. Click on "Plugins"
3. You're taken to the plugins page in the WP admin.

#### What I expected to happen

I expected to land on `/plugins/:site` in Calypso instead.

#### What actually happened

I was directed to the plugins page on WP admin.

### Browser / OS version

Chrome 88.0.4324.96 on macOS 11.1 (20C69)

### Is this specific to the applied theme? Which one?

Not related to the theme.

### Does this happen on simple or atomic sites or both?

This only applies to Jetpack sites in my testing. Noting that I tested with bleeding-edge Jetpack and the result was the same.

### Is there any console output or error text?

Nothing unexpected there.

### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low-to-medium IMHO (because it only affects a type of site that isn't a huge percentage of all sites).

**Comment by abcxyz-m** [comment]
Just adding that this seems to include all pages; everything is just a link to its WP Admin counterpart. I can create a separate issue if necessary.

I'd also mention this is **high** priority for Jetpack as it defeats one of Jetpack's most helpful features: the ability to easily manage plugins across multiple sites.

**Comment by obenland** [comment]
@getdave Can you remind me where we left off on the discussion about Jetpack sites getting a separate menu structure fallback?

Maybe we could use this issue to get that added?

**Comment by tyxla** [comment]
I agree with @mzakariya it's a high priority issue for Jetpack. cc @Automattic/jetpack and @Automattic/jetpack-voyager for awareness.

**Comment by getdave** [comment]
> @getdave Can you remind me where we left off on the discussion about Jetpack sites getting a separate menu structure fallback?
> 
> Maybe we could use this issue to get that added?

We left off here p6TEKc-4jR-p2. We said we would implement a static (hard coded, not from API endpoint) set of menu items for non-Atomic (ie: standard) Jetpack sites. The issue was trying to determine _exactly_ what these should be. 

I'm going to add myself a task to grok everything that's been discussed so far and propose a concrete plan moving forward.

I will then ask Jetpack folks to 👌 this plan before we implement.

**Comment by getdave** [comment]
I haven't forgotten about this. The p2 is nearly ready. It's required a bit of digging.

**Comment by cpapazoglou** [comment]
I have digged into it. This is the menu appearing for a Jetpack site

![](https://cln.sh/ZPFio1+)

and here are the links

```
<a 
title = "Stats"        href = "/stats/day/[DOMAIN]"
title = "Plans"        href = "/plans/[DOMAIN]"
title = "Purchases"    href = "/purchases/subscriptions/[DOMAIN]"
title = "Pages"        href = "/pages/[DOMAIN]"
title = "Posts"        href = "/posts/[DOMAIN]"
title = "Media"        href = "/media/[DOMAIN]"
title = "Comments"     href = "/comments/[DOMAIN]"
title = "Feedback"     href = "https://[DOMAIN]/wp-admin/edit.php?post_type=feedback&calypsoify=0"
title = "Activity Log" href = "/activity-log/[DOMAIN]"
title = "Backup"       href = "/backup/[DOMAIN]"
title = "Scan"         href = "/scan/[DOMAIN]"
title = "Search"       href = "/jetpack-search/[DOMAIN]"
title = "Customize"    href = "https://[DOMAIN]/wp-admin/customize.php"
title = "Themes"       href = "/themes/[DOMAIN]"
title = "Plugins"      href = "/plugins/[DOMAIN]"
title = "Import"       href = "https://[DOMAIN]/wp-admin/import.php?calypsoify=0"
title = "Export"       href = "https://[DOMAIN]/wp-admin/export.php?calypsoify=0"
title = "Marketing"    href = "/marketing/[DOMAIN]"
title = "Earn"         href = "/earn/[DOMAIN]"
title = "People"       href = "/people/team/[DOMAIN]"
title = "Settings"     href = "/settings/general/[DOMAIN]"
title = "WP Admin"     href = "https://[DOMAIN]/wp-admin"
```

I just have two questions:
1) Is it possible that the Jetpack menu changes per product purchased?
2) Are we keeping the `WP Admin` link?

**Comment by jeherve** [comment]
> Is it possible that the Jetpack menu changes per product purchased?

Yes:
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/scan/class-admin-sidebar-link.php#L72-L80

> Are we keeping the WP Admin link?

I think we should, yes, for folks not using Nav Unification in wp-admin (non-Atomic users).

**Comment by cpapazoglou** [comment]
Thanks @jeherve for chiming in. The code you posted is for the WPAdmin interface. I wonder if we were doing the same in Calypso.
Currently I get the following without having bought any as a product. 

![](https://cln.sh/rHgPBx+)

Each sections has a upgrade nudge

![](https://cln.sh/F0Y1BP+)

**Comment by cpapazoglou** [comment]
I have filed a PR https://github.com/Automattic/wp-calypso/pull/49352. We can change the menus as requested.

**Comment by getdave** [comment]
For additional context on our approach to Jetpack for Nav Unification please see p1HpG7-b2s-p2.

**Comment by mmtr** [comment]
Reopening to denote this is part of Jetpack 9.4.1 which is unreleased yet.

**Comment by mmtr** [comment]
Jetpack 9.4.1 just came out, so we can close this issue now.
