### ISSUE TITLE
Nav Unification: Unable to disable feature flag through query args

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#49123]
I'm working on the reduxifying plugins currently. However, as I reported in https://github.com/Automattic/wp-calypso/issues/49120, I'm unable to access the plugins section in Calypso for a Jetpack site anymore. Not without manually typing the URL, of course.

I've tried to disable nav unification with `?flags=-nav-unification` but it doesn't do the job. So I'm stuck and unable to provide a clear path for testing plugins in Calypso in the staging environment. 

I think this might be caused by https://github.com/Automattic/wp-calypso/commit/62b8e4929bbea5f0f458385d48812e19eaa6c074#r46199013 but I haven't dug into it.

#### Steps to reproduce the behavior

1. Go to `/home/:site` where `:site` is a Jetpack site.
2. Add `?flags=-nav-unification` to the URL.
3. Notice that nav unification doesn't get disabled.

#### What I expected to happen

Nav unification should have been disabled just like any other feature flag is configurable with the `flags` query arg.

#### What actually happened

Nav unification remained on.

**Comment by cpapazoglou** [comment]
I opted using the flag ONLY as an already proved mechanism for conditionally changing the behavior in multiple places in the Calypso codebase. Not as a way to enable / disable the feature. The biggest problem is that by using `?flags=-nav-unification` you would disable the feature for Calypso but not for `wp-admin` which may cause confusion. 

Of course, we should fix the problem reported here #49120. Is there a chance that you can use `/plugins/:site` for the moment? If it is a blocker for your workflow, we may allow `?flags=-nav-unification` but only in the context of "Be able to use Calypso with nav-unification disabled".

**Comment by daledupreez** [comment]
Just as a quick note from someone working on an unrelated project on WordPress.com -- it would be _really_ useful to be able to disable the flag so we can actually test flows the way users will see them. This is going to be particularly important if we're going to have this in place for a few weeks -- we're going to need to know whether we have bugs in our flows without possible behaviour coming from the Nav Unification feature. 

Granted, we may still see issues that come through regardless of the flag, but making it impossible for Automattic staff to test the standard navigation for multiple weeks is going to make it hard for us to triage bug reports from users.

**Comment by cpapazoglou** [comment]
@daledupreez thanks for stopping by! I see your point.

Since the flag is Calypso only, the most consistent way to experience what Customers see is using a separate non-a8c account in a private browser (so you can have your a8c account in the main browser).

Also, bear in mind that from now all teams should check their flows with both the feature enabled and disabled. The first rollout segment will 5% of the users. I am afraid, we can't avoid testing both variations. 

We are open to discussion though! Do you also feel that using`?flags=-nav-unification` as query string will help your flows?

**Comment by obenland** [comment]
@cpapazoglou Let's review & merge https://github.com/Automattic/wp-calypso/pull/49136, there's enough value in disabling it in Calypso only
