### ISSUE TITLE
Gutenberg: Browser tab crashes when mousing over the block icon, and the Premium Content block option

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#49125]
A customer reported a frustrating issue that causes their browser tab to crash when mousing over the Image Block icon, and then over the entry for the Premium Content Block. It looks like the block preview contributes to the browser tab locking up, and becoming unresponsive.

#### Steps to reproduce the behavior

1. Go to the page in the editor
2. Click on the Image Block icon as if to change the block type
3. Mouse over the _Premium Content_ entry
4. The browser tab becomes unresponsive as the preview for the block loads
5. I reproduced the behavior on my test site using a copy of the user's page code here: https://wordpress.com/page/he20171027.com/1024

#### What I expected to happen

The browser tab would not crash when mousing over the items in the Block Icon menu.

#### What actually happened

The browser tab locks up, and become unresponsive.

#### Context

This was reported in 27166980-hc
Follow-up at 3669797-zen

### Browser / OS version

The customer seems to be using Chrome 87.0 on Windows 10.0.0

I was able to reproduce this issue in Firefox Developer Edition v85.0b9 on macOS 11.1

### Is this specific to the applied theme? Which one?

It seems to affect Maywood and Brompton, likely other block-based themes that are also Varia child themes.

### Does this happen on simple or atomic sites or both?

Tested and reproduced on WordPress.com Premium plan sites.

### Is there any console output or error text?

Yes, here is the output from the customer's page: https://d.pr/n/kR21ay/9z3vDWSeTD

This is the console output from a test on my test site: https://d.pr/n/uw9G6e/YHzSP6JMlz

### Level of impact (Does it block purchases? Does it affect more than just one site?)

This can potentially affect multiple sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Here are demonstrations of the issue:

https://user-images.githubusercontent.com/2912202/105373078-f551ac00-5c0e-11eb-9b30-7a99f5f7e9fa.mp4

and my reproduction of the issue:

https://user-images.githubusercontent.com/2912202/105373366-49f52700-5c0f-11eb-9aae-0129c4058d0a.mp4

**Comment by cathymcbride** [comment]
@apeatling FYI - I added this to your backlog b/c of the premium content. let me know if it needs to go elsewhere.

**Comment by apeatling** [comment]
Should be fixed with https://github.com/Automattic/wp-calypso/pull/48988 and will go live when https://github.com/Automattic/wp-calypso/pull/49098 merges.

**Comment by cathymcbride** [comment]
Removing from view backlog based on 👆

**Comment by ghost** [comment]
I hit this issue too.

**Comment by andrewserong** [comment]
Thanks for reporting! The fix is now live with the [ETK plugin 2.12 update](https://github.com/Automattic/wp-calypso/pull/49098) which has just been deployed, so closing this issue now.
