### ISSUE TITLE
Posts: Comments only show 20 ' root levels' of comments

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4914]
Originally raised by @designsimply - Introduced in #4849 cc: @mtias 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/ for a site that has a post with more than 20 root level comments
2. Click comments icon/number on that post

#### What I expected

Expected to see all comments

#### What happened instead

Only 20 root levels of comments are shown, any children of these root level comments are still displayed, so more than 20 comments can be shown, but only 20 of the highest level comments (non-replies)

#### Browser / OS version

Chrome/Firefox OSX

#### Screenshot / Video

Comments start at 32

![screen shot 2016-04-21 at 12 06 51 pm](https://cloud.githubusercontent.com/assets/128826/14695897/b44a0300-07b9-11e6-9f67-7ab4c34b2f4b.png)

[My test site post ](https://eatkibbeling.wordpress.com/2016/04/20/10-things-to-do-near-lax-discover-los-angeles-mobile/comment-page-1/#comment-1)comments start at comment 1

![screen shot 2016-04-21 at 12 07 36 pm](https://cloud.githubusercontent.com/assets/128826/14695914/cee32980-07b9-11e6-9ba6-d23180cbe0ac.png)

**Comment by alisterscott** [comment]
I also noticed adding a root level comment via the posts view when there's greater than 20 does a jumpy redirect to the original post page?!?

**Comment by hoverduck** [comment]
#bug-scrub

Closing, I now see up to 22 top-level comments, plus 2 more sub-comments.  I didn't test beyond that.
