### ISSUE TITLE
Jetpack Icon colour (as well as any SVG menu icon) looks off in the new nav

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#49145]
To me the Jetpack icon colour looks a bit off. 

This is what I see. 
<img width="356" alt="Screen Shot 2021-01-21 at 11 13 49 AM" src="https://user-images.githubusercontent.com/115071/105400417-bead6e80-5bd9-11eb-816a-3037d7c5293f.png">

I am not sure if it is because of the colour scheme that I am using. 

The site in question that this happends on is a simple wordpress.com site. 

#### What I expected to happen
The icon colour should match the rest of the icons. 

#### Browser / OS version
Latest Firefox, Latest MacOS.

**Comment by obenland** [comment]
@frontdevde I think in some color schemes we don't have hover styles for the icons, is that correct? I wonder if we could remove the opacity for custom menu icons in those color schemes to make them look more alike?

**Comment by frontdevde** [comment]
All colors schemes have a fill colors set for the icons i.e. `var(--color-sidebar-gridicon-fill)`. The issue with custom menu icons like the Jetpack logo is that it's embedded as an image thus not being affected by the fill property. 

Removing the opacity makes the difference even more obvious I'm afraid:

|Before|After|
|-|-|
|<img width="165" alt="Screenshot 2021-01-28 at 09 55 29" src="https://user-images.githubusercontent.com/1562646/106113718-148c9400-614f-11eb-88a6-5fbb9e37f007.png">|<img width="189" alt="Screenshot 2021-01-28 at 09 55 14" src="https://user-images.githubusercontent.com/1562646/106113733-17878480-614f-11eb-8b30-69f0da42501a.png">|

We could potentially do some CSS filters magic to achieve the desired color for custom menu images. I did a brief test and while it generally works, a key issue is that while it would retain the shape, it would loose the detail:

`filter: brightness(0) invert(90%) sepia(5%) saturate(1408%) hue-rotate(180deg) brightness(98%) contrast(90%);`

<img width="269" alt="Screenshot 2021-01-28 at 09 43 44" src="https://user-images.githubusercontent.com/1562646/106114173-92509f80-614f-11eb-851d-37426fb265b0.png">

Might be worth exploring further though. Here's a quick test with using an additional element with the filter applied as an overlay over the actual image:

<img width="209" alt="Screenshot 2021-01-28 at 10 05 04" src="https://user-images.githubusercontent.com/1562646/106114860-5cf88180-6150-11eb-888b-68f323d5b5e5.png">

**Comment by frontdevde** [comment]
Another technique could be to use a mask 
`
background-color: var(--theme-icon-color-here);
mask: url(link-to-svg-here) no-repeat center;
`
Again though, with the Jetpack logo we'd probably have the same issue here that while it retains the shape it looses the detail.

<img width="200" alt="Screenshot 2021-01-28 at 10 25 58" src="https://user-images.githubusercontent.com/1562646/106117708-954d8f00-6153-11eb-8b24-325d414412c7.png">

**Comment by mattsherman** [comment]
Just noting that this issue occurs for any SVG menu icon, not just the Jetpack icon. (The issue title and description doesn't reflect that.)

**Comment by getdave** [comment]
Is this blocking Woo compatibility?

**Comment by mattsherman** [comment]
> Is this blocking Woo compatibility?

I have brought up this specific question in the PR to use SVG icons for WooCommerce, to bring in PM and designer input.

https://github.com/woocommerce/woocommerce/pull/29094

**Comment by pablinos** [comment]
It seems like the white triangles in the Jetpack logo are causing problems here. I had a look at the branding for Jetpack and couldn't find one where the triangles were part of the same path, so it could sit on any colour background.

Does anyone (@Automattic/jetpack-design perhaps) know where we might be able to find an SVG like that?

**Comment by folletto** [comment]
Sure thing.
I attached the icon here (ZIP and SVG code below).

While WP Admin uses a font to create the icon, I re-created this setting it at 20x20 pixels to match, even if of course being an SVG it can scale properly.

[jetpack-wpadmin-icon-simplified.svg.zip](https://github.com/Automattic/wp-calypso/files/6235429/jetpack-wpadmin-icon-simplified.svg.zip)

<img width="403" alt="Screenshot 2021-03-31 at 10 23 14" src="https://user-images.githubusercontent.com/4389/113122020-251ec080-920b-11eb-8e23-3029cbe92583.png">

```<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>jetpack-wpadmin-icon-simplified</title>
    <g id="jetpack-wpadmin-icon-simplified" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M20.0000191,0 C31.0458276,0 40,8.95429553 40,20 C40,31.0457045 31.0458276,40 20.0000191,40 C8.95421062,40 0,31.0457045 0,20 C0,8.95429553 8.95421062,0 20.0000191,0 Z M31,17 L21,17 L21,36 L31,17 Z M19,4 L9,23 L19,23 L19,4 Z" id="jetpack-logo" fill="#069E08" fill-rule="nonzero"></path>
    </g>
</svg>
```

It should work ok, but let me know if you need any tweak.

**Comment by pablinos** [comment]
At first glance, that looks pretty perfect. Thanks @folletto. I'll add you as a reviewer on the PR in case you want to take a look.

**Comment by folletto** [comment]
Could you please ping the whole Jetpack Design Team for review? It's better than just me getting the request :)

**Comment by obenland** [comment]
@pablinos Is this still in progress or should we re-prioritize in a new bundle?

**Comment by pablinos** [comment]
It's still in progress but the Jetpack PR Automattic/jetpack#19364 is skipping some required checks, so I need to get some help on that.

If after some reviews the PRs need significant changes then it's probably best we re-prioritise it. It would be good to not leave it too long though, as it's close and it would be a shame if it all went stale.

**Comment by pablinos** [comment]
With the Jetpack PR and #51614, this should now be fixed
