### ISSUE TITLE
Nav unification: "Add a tag" input seems to retain old styling in sidebar

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#49149]
If you head to the "reader" on WordPress.com and scroll to the bottom under "tags," you'll notice the "Add a tag" input seems to retain older styling. Do we have a "dark mode" style for inputs in the sidebar?

<img width="277" alt="Screen Shot 2021-01-21 at 1 23 12 PM" src="https://user-images.githubusercontent.com/214813/105406273-3095b000-5bfa-11eb-9e5b-0988ac37640b.png">

cc @davemart-in

**Comment by davemart-in** [comment]
Thanks @jeffgolenski! cc @obenland for triage.

**Comment by bluefuton** [comment]
One possible solution would be for this to work like 'Create new list', where we just have a link in the sidebar:

<img width="176" alt="Screen Shot 2021-01-22 at 15 33 03" src="https://user-images.githubusercontent.com/17325/105438085-35746580-5cc7-11eb-9e0f-f9a1f251f1b0.png">

This could link to a new 'Add tag' page that lets the user search and also offers some popular tag suggestions.

**Comment by getdave** [comment]
@sfougnier Would you be able to advise on the preferred visual route here? Much appreciated.

**Comment by ghost** [comment]
I think we should keep the current form field + button treatment, and tweak the colors to align with the new navigation color scheme. See mocks:

<img width="1351" alt="desktop - reader" src="https://user-images.githubusercontent.com/67021691/105904741-81891800-5fef-11eb-98f9-eb1e6ab058bf.png">
<img width="1351" alt="desktop - reader-1" src="https://user-images.githubusercontent.com/67021691/105904798-9665ab80-5fef-11eb-8ad9-0463237be7bc.png">
