### ISSUE TITLE
PlansGrid: some features are not correct

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49142]
There is a current discrepancy between the plans data that we're showing in the PlansGrid and what is present on `/start` flow or on `/pricing`

**Expected:**
Personal plan includes _Unlimited Email Support_ but doesn’t include _Basic Live Chat Support_

**Current:**
In PlansGrid we’re saying both are included. This needs to be fixed in both feature list and details table.

**How to fix** (illustrated also in the screenshot below):
 - [ ] Rename existing item from _Email and basic live chat support_ to _Email support_ and continue having it checked for Personal plan and above.
- [ ] Add a new item _Basic live chat support_ for Premium plan and above.

![image](https://user-images.githubusercontent.com/14192054/105397816-34412b00-5c2a-11eb-97ef-146a0c0f3492.png)

**Comment by alshakero** [comment]
Diff in D55944-code

**Comment by razvanpapadopol** [comment]
Fixed in D55944-code
