### ISSUE TITLE
Domain Settings page is visible to Jetpack sites.

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#49147]
### Steps to reproduce the behavior

1. Go to a simple .com  site and click domains. 
2. Select a jetpack site via the select sites section.
3. Notice that you can see the domain section even though I don't think it makes sense for a Jetpack site. 
However it probably does make sense for an atomic site. 

#### What I expected to happen
To be shown a list of sites that can see the domain section instead.

#### Browser / OS version
Latest Firefox / MacOS 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
<img width="1271" alt="Screen_Shot_2021-01-21_at_11_23_02_AM" src="https://user-images.githubusercontent.com/115071/105401504-2fa15600-5bdb-11eb-8053-fb01082ca965.png">

**Comment by obenland** [comment]
Trying to reproduce this, I get:

![image](https://user-images.githubusercontent.com/1398304/105403456-a0e20880-5bdd-11eb-9bb3-1182daf006b2.png)

Although that is still not the site picker you expected. 

> Go to a simple .com site and click domains.

Is that Upgrades > Domains or did you get there in a different way?

**Comment by getdave** [comment]
@enejb When you get a chance would you be able to confirm the exact steps to replicate? Much appreciated.

**Comment by enejb** [comment]
1 . Start with a simple .com site. 
2. Navigate to domains. 
3. Use the site switcher to select a Jetpack site. 
4. Notice that the domain settings are displayed for the Jetpack site. 

I would be happy to pair and show you what I am looking at or add you to my jetpack site. In case that helps.

**Comment by getdave** [comment]
Thanks @enejb. This is now on our radar to fix.

**Comment by getdave** [comment]
For additional context please see p1HpG7-b2s-p2.

**Comment by cpapazoglou** [comment]
This is now fixed:
1) Jetpack sites don't have an Upgrades -> Domains menu
2) switching from a simple / atomic domains page to a Jetpack site shows that Domains are not available for that site

![](https://cln.sh/j2xkrG+)
