### ISSUE TITLE
Design Picker: Blank Canvas prototype

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49141]
**What**
Let's add a simple internal prototype flow for "Blank" option in `/new`. Doesn't need to be very pretty for starters.

**Why**
Give the user the possibility to start with an empty template.

**A/C**
- [x] Blank Canvas theme available on wpcom (pNEWy-dxQ-p2)
- [x] Create starter page without contents for it
- [ ] Add dummy empty image file for it (see example from Themes showcase: https://cloudup.com/cTv4ZJchXoZ), or some simple if/else in code to show an empty box. See https://github.com/Automattic/wp-calypso/issues/49141#issuecomment-773700429
- [ ] Use the `blank-canvas` slug to ensure the blank option shows up always as first?
- [ ] Design picker should keep working as previously with or without Blank Canvas (this is to ensure that when we remove the `is_alpha` flag, everything is going to work properly)
- [ ] Update randomisation unit tests accordingly

![image](https://user-images.githubusercontent.com/87168/105397874-4ae78200-5c2a-11eb-9766-7a9af0ff2971.png)

**Comment by ianstewart** [comment]
cc @ollierozdarz

**Comment by ollierozdarz** [comment]
👋 Catching up on this task. These designs may now be in a landscape ratio with the most recent changes, but that shouldn't change anything drastically. All I might add here is a ' + ' inside the blank design, since keeping it empty feels a bit like a bug, and I'd be interested it many users pay attention to the labels underneath. 

<img width="427" alt="Screen Shot 2021-02-05 at 10 41 04 am" src="https://user-images.githubusercontent.com/67085494/106973483-a83d1080-679e-11eb-9633-bb59497bacee.png">

The label could be whatever we see fit:

- 'Start with an empty page'
- 'Blank page'
- 'Blank canvas'

**Comment by simison** [comment]
@ianstewart @kjellr I'm assuming we have blank canvas "starter content" now but do we  have "blank canvas" empty template? I'd just need it for a prototype. Doesn't need to be actually released anywhere.

**Comment by ianstewart** [comment]
Do you mean setting up something like https://blankstarter.wordpress.com/ in order to create Headstart annotations with?

**Comment by simison** [comment]
@ianstewart maybe, not sure how all the things are tied together. :-) @andrewserong might have better idea.

I guess this should become functional:

https://public-api.wordpress.com/rest/v1/template/demo/blank-canvas/blank-canvas/?language=en&site_title=&font_headings=Playfair%20Display&font_base=Fira%20Sans

Currently that API returns `{"error":"no-site","message":"No source site found."}`

That URL gets these two:
- Theme: `blank-canvas`
- Template: `blank-canvas`

It might pull something additional with theme slug on site-creation, not sure.

**Comment by StefanNieuwenhuis** [comment]
I moved the template creation part to #51979

**Comment by andrewserong** [comment]
> Do you mean setting up something like blankstarter . wordpress.com in order to create Headstart annotations with?

> @ianstewart maybe, not sure how all the things are tied together. :-) @andrewserong might have better idea.

@simison thanks for the ping!

Yep, to get the `template/demo` endpoint URL working, there'll need to be a starter site with the appropriate sticker attached, even for the blank content, and a Headstart annotation. Full steps to do it are in: PCYsg-r7w-p2, which looks like it's being worked on in https://github.com/Automattic/wp-calypso/issues/51979? It's already mentioned in that page, but note that the `$starter_design_sites` list will need to be added with the slug that's included in `available-designs-config.json` before the `template/demo` endpoint will work.

**Comment by andrewserong** [comment]
Oh, and it looks like Luna's working on this, but feel free to ping us in View if you get stuck or need reviews 🙂

**Comment by simison** [comment]
I'll close this since it was meant for prototype, and has likely some todos that are not that relevant for the final flow outlined in p9Jlb4-2qt-p2 . It's better you write fresh issues so that this doesn't mix things up.

FYI @razvanpapadopol

**Comment by StefanNieuwenhuis** [comment]
> I'll close this since it was meant for prototype, and has likely some todos that are not that relevant for the final flow outlined in p9Jlb4-2qt-p2 . It's better you write fresh issues so that this doesn't mix things up.
 
#52016 is the follow-up issue.
