### ISSUE TITLE
Nav-Unification's notices' new style is hard to read

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#49148]
### Steps to reproduce the behavior

1. Go to wordpress.com
2. Either force some SiteWarnings or have a site with broken domains like me ;) See https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/my-sites/domains/components/domain-warnings/index.jsx

#### What I expected to happen

A notice with a color clearly indicating the severity of it:

<img width="270" alt="Screenshot 2021-01-21 at 19 40 13" src="https://user-images.githubusercontent.com/3392497/105403335-87ae7b80-5c20-11eb-8e5e-724afe4c12b2.png">

They should also clearly stand out:

<img width="257" alt="Screenshot 2021-01-21 at 19 45 21" src="https://user-images.githubusercontent.com/3392497/105403956-4e2a4000-5c21-11eb-937c-836f47d912d8.png">

#### What actually happened

The notices have very thin border and the colors are clashing horribly with the background:

<img width="272" alt="Screenshot 2021-01-21 at 19 33 53" src="https://user-images.githubusercontent.com/3392497/105403364-95640100-5c20-11eb-8617-5b9f0d6ed394.png">

My vision is pretty OK (and I _know_ which one should be an error and which one should be a warning) and I still have troubles figuring that out based on color. I'd also expect this combination of colors breaks some a11y rules ;)

They also have the same (or very similar) background as secondary navigation items - which makes spotting them (and their importance) harder:

<img width="269" alt="Screenshot 2021-01-21 at 19 45 44" src="https://user-images.githubusercontent.com/3392497/105404025-65692d80-5c21-11eb-965f-2e2291a15d93.png">

The upsell seen in the above screenshot stands out more than a crucial warning - maybe we could use a white-ish background for these warning notices as well? I'd imagine that could help with the issue with "red on black" colors as well :)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Impacts all sites, if they have domain warnings. Those warnings usually are important - domain is not configured correctly, it expired, etc. affecting the availability of the whole site.

**Comment by obenland** [comment]
@lcollette @sfougnier This seems like it would be right up your wheelhouse

**Comment by ghost** [comment]
I'd like to suggest we remove the white fill and lighten the red and yellow so that they pass accessibility on the dark background. Alternatively, we could just remove the colored border on the icons and maintain the white fill.

<img width="1440" alt="desktop - contextual nudge-1" src="https://user-images.githubusercontent.com/67021691/105902180-4afdce00-5fec-11eb-9d23-33df58d82a12.png">
<img width="1440" alt="desktop - contextual nudge" src="https://user-images.githubusercontent.com/67021691/105902181-4afdce00-5fec-11eb-8121-7875f0c553e0.png">

**Comment by retrofox** [comment]
I'd like to confirm the following are the styles we'd like to implement.

Warning | Error
-------|--------
![image](https://user-images.githubusercontent.com/77539/112654089-cd104480-8e2d-11eb-9e58-1c1dafa974ab.png) | ![image](https://user-images.githubusercontent.com/77539/112654113-d39ebc00-8e2d-11eb-922a-87373d8868aa.png)

cc @sfougnier
