### ISSUE TITLE
Earn tab: Unable to add new payment plan for Stripe

### ISSUE THREAD

**Issue by isocialtish** [Automattic/wp-calypso#49151]
### Steps to reproduce the behavior

1. Go to Earn
2. Click on Collect Payments> Payment Plan> Click Add a new payment plan button
3. Add pricing and renewal frequency, then select "save"
4. See error "Cannot read property 'id' of undefined"

#### Browser / OS version
Browser Chrome: Version 87.0.4280.141
OS: Mac 10.13.6

#### Does this happen on simple or atomic sites or both?
Simple

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This is affecting multiple sites, we have two reports of this so far in 3642902-zen and 3573779-zen

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
GIF: https://d.pr/i/OzzPe3

**Comment by apeatling** [comment]
I've tried this on multiple sites and I can't reproduce. Is it related to the Stripe account? Can you try connecting a different account to check?

![2021-01-26 14 28 01](https://user-images.githubusercontent.com/1464705/105914133-be024700-5fe2-11eb-8872-974baebe10c8.gif)

**Comment by apeatling** [comment]
Can you retry connecting the Stripe account again?

**Comment by rosepajaroja** [comment]
Hello @apeatling I am also experiencing the same issue. It happens both on Earn and Page/Post Editor. 

https://www.loom.com/share/d20b2397836c41e5bff520a61deb1f7f

>Can you retry connecting the Stripe account again?

I couldn't test reconnecting Stripe, because that also has an issue:

https://github.com/Automattic/wp-calypso/issues/45427

Thank you!

**Comment by michaeldcain** [comment]
@pottedmeat: can you try to reproduce this?

**Comment by pottedmeat** [comment]
This is triggered when the Stripe account that was connected to this site is connected to another and then this site tries to create a new plan. The error message was improved in D68911-code and reads:

> This Stripe account is connected to a different WordPress.com account.

**Comment by pottedmeat** [comment]
Patch created in D83788-code
