### ISSUE TITLE
"Ask a Happiness Engineer" link is hidden by "Upgrade and save" box in checkout

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#49155]
### Steps to reproduce the behavior

1. Use a site that does not have a paid plan.
2. Add a domain to your cart by visiting https://wordpress.com/domains/add/ (decline the G Suite upsell if you see one).
3. Verify that you are redirected to checkout. Make sure your browser is set to a relatively wide ("desktop") width so that you see the sidebar.
4. Notice that the "Ask a Happiness Engineer" link in the sidebar is hidden by "Upgrade and save" box in checkout

![overlap-questions-link-checkout](https://user-images.githubusercontent.com/2036909/105427916-37cdb580-5c1c-11eb-85fd-78e0f11af911.png)

**Comment by Aurorum** [comment]
Seems to also be reported in #49150.
