### ISSUE TITLE
Nav Unification: add `aria-` role to identify expandable sidebar menus

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#49157]
### Steps to reproduce the behavior

1. Visit the Reader at http://calypso.localhost:3000/read.
2. Click on Followed Sites, Tags or Lists to expand the contents.

#### What I expected to happen

In the existing nav, we show an arrow indicator that suggests the menu item expands when clicked:

<img width="257" alt="Screen Shot 2021-01-22 at 15 24 19" src="https://user-images.githubusercontent.com/17325/105437573-31941380-5cc6-11eb-8b93-b8adbd367632.png">

When the item is open, the arrow indicator changes direction, indicating that is open:

<img width="260" alt="Screen Shot 2021-01-22 at 15 24 27" src="https://user-images.githubusercontent.com/17325/105437614-41135c80-5cc6-11eb-9d47-173473f550d6.png">

#### What actually happened

In the shiny new Nav Unification experience, there is no indication that a section is expandable:

<img width="266" alt="Screen Shot 2021-01-22 at 15 24 38" src="https://user-images.githubusercontent.com/17325/105437649-5092a580-5cc6-11eb-848d-0863ad01b63e.png">

There is also no 'expanded' state to suggest that it is open and can be collapsed:

<img width="270" alt="Screen Shot 2021-01-22 at 15 24 43" src="https://user-images.githubusercontent.com/17325/105437677-5daf9480-5cc6-11eb-9e73-ef788ed85bc2.png">

From an accessibility point of view, it'd also be good to add `aria-expanded` to denote when the sidebar item is open or closed:

https://www.w3.org/TR/wai-aria-1.1/#aria-expanded

### Context

I'm testing the Nav Unification in Reader as part of the internal call for testing: p7DVsv-ago-p2.

#### Browser / OS version

Firefox v84 Mac.

#### Is this specific to the applied theme? Which one?

No.

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects Reader and may reduce discoverability of certain features.

**Comment by cpapazoglou** [comment]
This problem derives from the `wp-admin` behavior of not having expand / collapse indicators as also not having the ability to expand / collapse (without redirecting). If we want to align with that behavior we would eventually need to **remove** the expand / collapse behavior and clicking the heading would open the first submenu item. But, there are some weird menus like "Lists" which don't have an "All" submenu item in contradiction to eg "Followed Sites".

Followed Sites | Lists
-------|------
![](https://cln.sh/VKz8WE+) | ![](https://cln.sh/hn6cfz+)

@sfougnier, @lcollette what's your take here?

**Comment by ghost** [comment]
Thanks for the ping!

While I agree that having the visual indicator makes the expected behavior clearer, I hesitate to say we should prioritize adding expand/collapse icons for our v1.

> This problem derives from the wp-admin behavior of not having expand / collapse indicators as also not having the ability to expand / collapse (without redirecting). If we want to align with that behavior we would eventually need to remove the expand / collapse behavior and clicking the heading would open the first submenu item.

- The icons, as stated above, are not part of the existing wp-admin design language or interaction patterns. Adding them in will deviate visually and add another interactive element on top of the flyouts. How these will work in conjunction is hard to tell without a closer look.
- This change seems small, but it will impact other things such as the submenu items @cpapazoglou mentioned above. Without being able to take a comprehensive look at the full impact of this addition on the navigation structure, I worry it will create more problems than it will solve.

Given the additional complexity this change will have in terms of interactions and navigation structure, I don't think adding it as a standalone feature is something we should prioritize at this time.

**Comment by bluefuton** [comment]
Thanks for explaining your rationale @sfougnier 👍 

As there's going to be no other indicator of expansion state, please could we consider adding `aria-expanded` attribute for these menus as I mentioned above?

> From an accessibility point of view, it'd also be good to add aria-expanded to denote when the sidebar item is open or closed:
> 
> https://www.w3.org/TR/wai-aria-1.1/#aria-expanded

**Comment by tjcafferkey** [comment]
@bluefuton can you double check if this is still an issue? As far as we know this has been fixed but would just like your confirmation on this before closing. Thanks!

**Comment by cpapazoglou** [comment]
This issue is resolved now. There are both visual indicators and `aria-expanded` attributes

![](https://cln.sh/LiWXc0+)
