### ISSUE TITLE
New Page Layout Modal: Fix selected border state of layouts spanning multiple categories

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#49152]
### Steps to reproduce the behavior

1. Create a new page on any level plan account on WordPress.com (three ways to do this: from Customer Home > Quick links > "Add a page" link, from /pages > "Add new page" button, and from the Editor > W icon in top left to open the nav sidebar > "Add new page" link at the bottom of sidebar).
2. See new page layout modal. Select the first thumbnail under the "About" category (this one's called "Webinar").
3. You'll see a black "selected" border appear around this thumbnail in addition to its other instance below the "Contact" category. Screenshot:
<img width="1303" alt="Screen Shot 2021-01-21 at 1 50 28 PM" src="https://user-images.githubusercontent.com/204742/105410758-a9433f00-5bef-11eb-9bd8-4e92dd2b6060.png">

#### What I expected to happen
Ideally, we should only show a selected border on the selected thumbnail (and not on any repeat instances). Note: This will no longer be an issue in our upcoming New Page Layout Modal (see pbAok1-1QJ) where the categories will filter the view.

**Comment by ramonjd** [comment]
I think we can close this ticket in light of the upcoming redesign by @Automattic/ganon 

It'll be out in a few weeks.
