### ISSUE TITLE
New Onboarding: Do not reuse domain selected from incomplete flow

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49153]
### Steps to reproduce the behavior

Prereq. Interface language is English.
1. Add new site.
2. Enter some string into the site name.
3. At the `choose a domain` step, select some domain.
4. Click on the WordPress icon on top left to exit Gutenboarding.
5. Re-enter Gutenboarding by repeating Step 1.
6. Clear the text and enter a new string.
7. Click next.

#### What I expected to happen
8. Domain suggestions are based on the currently entered string.

#### What actually happened
9. Previously selected domain name remains selected.

### Context
User scenario testing.

#### Browser / OS version
Browser: Firefox Nightly 86.0a1
OS: macOS Catalina 10.15.7

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
N/A.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - may be confusing for user, but does not prevent Gutenboarding flow.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-01-21 at 14 34 13](https://user-images.githubusercontent.com/6549265/105420736-bfec9480-5bf5-11eb-8c1a-cd780b164f7d.png)

**Comment by razvanpapadopol** [comment]
> What I expected to happen
Domain suggestions are based on the currently entered string.

From the screenshot I see the domain suggestions were actually based on the entered string. The domain displayed at the bottom is something that you've explicitly selected in a previous session and it stays selected until you pick a different one or finish creating the site. So the behavior is like this by design.

cc: @Automattic/luna @ollierozdarz

**Comment by ollierozdarz** [comment]
Good point, @razvanpapadopol. I think having this domain in the list is handy as well (+1 for bottom of list placement). My suggestion is to deselect it if the user has followed the same steps to reproduce as listed above, since this seems to be the confusion point.

**Comment by ciampo** [comment]
Putting on hold, as it will solved when working on #50513
