### ISSUE TITLE
New Onboarding: missing translations when coming from wpcom

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49169]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/new as an existing (logged-in) user with other locale than EN set in your account (eg: FR)

or 

1. Open an incognito window
2. Go to [wordpress.com](https://wordpress.com) and get the logged-out homepage
3. Go to [wordpress.com/new/fr](https://wordpress.com/new/fr)

#### What I expected to happen
* All the translations to be in place, same as when going to https://wordpress.com/new/fr directly as a new user (or in incognito window).

#### What actually happened
* Some translations are not loaded

### Context
* Gutenboarding i18n main issue: https://github.com/Automattic/wp-calypso/issues/37665

**Note:** since the translations for new users are loading fine, it should be a problem of not passing the locale correctly everywhere

#### Screenshots
<img width="999" alt="Screenshot 2021-01-22 at 08 50 28" src="https://user-images.githubusercontent.com/14192054/105460369-5a9bb080-5c94-11eb-9819-40d358fe7c82.png">
<img width="942" alt="Screenshot 2021-01-22 at 08 49 35" src="https://user-images.githubusercontent.com/14192054/105460374-5cfe0a80-5c94-11eb-9dca-685b50a82f7c.png">
<img width="694" alt="Screenshot 2021-01-22 at 08 48 59" src="https://user-images.githubusercontent.com/14192054/105460383-5f606480-5c94-11eb-986e-fa431dd76e3b.png">
<img width="1118" alt="Screenshot 2021-01-22 at 08 46 32" src="https://user-images.githubusercontent.com/14192054/105460389-612a2800-5c94-11eb-8dc7-cd55156e8d8a.png">
<img width="897" alt="Screenshot 2021-01-22 at 08 45 46" src="https://user-images.githubusercontent.com/14192054/105460401-64251880-5c94-11eb-87ab-01a6412ab1ca.png">

**Comment by ciampo** [comment]
I visited `wordpress.com/new/it` in incognito window and a lot of translations are broken

https://user-images.githubusercontent.com/1083581/105462390-d7c42700-5c8e-11eb-8dbc-8902e391c498.mp4

**Comment by simison** [comment]
cc @Automattic/i18n and @Automattic/team-calypso in case anything has changed in our i18n tooling recently that might've caused this.

**Comment by ramonjd** [comment]
We can add an investigation task to our next sprint on Monday if the cause isn't discovered before

cc @Automattic/ganon

**Comment by ramonjd** [comment]
We've spoken to @p-jackson, who is on Gardening this week. He'll take a squiz when he can.

**Comment by p-jackson** [comment]
@razvanpapadopol are you still able to reproduce this issue? I've tested in various browser and proxied/unproxed combinations and translations are working fine for me. Even tried proxying through France to see if geoip made a difference 😅 

I noticed that if I used my sandbox, and the sandbox was broken, then English strings would appear.

It could also have been fixed elsewhere by something else maybe? 🤷

**Comment by razvanpapadopol** [comment]
I can't reproduce it either. Both scenarios (existing user and new user visiting first wordpress.com and then new onboarding) are working fine. Maybe it was something wrong with the translation bundles? The weird part of the bug is the mix of translated/untranslated strings (eg: title vs subtitle)

**Comment by p-jackson** [comment]
Found a way to test using old translation bundles pxLjZ-6j7-p2. However I still wasn't able to reproduce 😕
It's a little unsettling, but I'm going to close this issue now since I don't think we can make any more progress on it, and I don't want to give the impression that it's on anyones radar.

If it is still a problem for someone then please reopen posthaste!

**Comment by simison** [comment]
This might've been real issue related to Webpack 5 and popped up again, slack thread: p1611737961102100-slack-luna

**Comment by razvanpapadopol** [comment]
There still seem to be new reports on this: pbxNRc-vn-p2#comment-1565

**Comment by p-jackson** [comment]
This issue is still happening, although I'm not able to reproduce it. I think this is probably an issue for the @Automattic/luna backlog.

**Comment by razvanpapadopol** [comment]
No one was able to reproduce this again for more than a week. Closing it for now.
