### ISSUE TITLE
Retain users existing color scheme when feature first activated

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#49173]
There have been reports that when the feature was activated users experienced a new color scheme which they didn't initiate.

This experience is jarring.

As suggested in p7DVsv-ago-p2#comment-33773 can we default users to either:

1. The color scheme that is closest to the Calypso default, or...
2. The color scheme that is closest to the one they previously had selected.

For more context see p7DVsv-ago-p2#comment-33765

**Comment by getdave** [comment]
@frontdevde Would you be able to take a look into this one for scope and feasibility? Just need an idea of complexity and effort to fix.

**Comment by frontdevde** [comment]
I've been thinking about this one for a while. While this is something we could do, I'm not certain we should. In the end, I think this boils down to us needing a senior stakeholder decision here. Let me try to explain:

The goal of Nav Unification is to unify the Calypso experience with wp-admin. From the beginning the look & feel of wp-admin in core informed the design direction of Nav Unification. One key reason being to be in line with where core is going and by proxy looking similar to Screenshots in all the guides and tutorials on WordPress out there (all these pieces of content show the WP admin interface in the dark colors of core wp-admin). AFAIR this is why design chose the dark colors as the new default for Nav Unification. 

With all this in mind, my current assumption is that the most senior stakeholder(s) would prefer the default to be Classic Dark i.e. colors closely aligned with wp-admin in core. IMO we should confirm with said senior stakeholder(s) whether this is the case.

It might be important to note, that the vast majority of users has never manually changed to a color scheme that deviates from the default. This means if we were to change the default in Nav Unification from Classic Dark (i.e. wp-admin colors) back to Classic Bright (i.e. Calypso colors pre Nav Unification), the vast majority of users would see the interface in the bright colors. While this would be less harsh of a change, it would also mean that the interface colors aren't consistent with wp-admin in core. Again, personally I have no preference here, the senior stakeholder(s) might though.

**Comment by cpapazoglou** [comment]
Also, bare in mind that we will be preparing a welcoming modal that is designed with the dark color as default https://github.com/Automattic/wp-calypso/issues/47049#issuecomment-732479799

**Comment by frontdevde** [comment]
CC'ing @obenland @davemart-in for direction on the above.

**Comment by davemart-in** [comment]
Thanks for recapping!

> With all this in mind, my current assumption is that the most senior stakeholder(s) would prefer the default to be Classic Dark i.e. colors closely aligned with wp-admin in core. IMO we should confirm with said senior stakeholder(s) whether this is the case.

That is correct. The primary goal here being for us to align with what the default is in core. Unity with core (and thus every book, article, video recorded in the last 5 years) is top of mind. If we want the default in Dotcom to be bright blue, we'll need to propose this change in core first.

**Comment by frontdevde** [comment]
Thanks for chiming in! I'm closing the issue as the current implementation matches stakeholder expectations.
