### ISSUE TITLE
Auto SS for Network Admin `wp-admin` link

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#49174]
You will need to read p7DVsv-ago-p2#comment-33814.

**Comment by cpapazoglou** [comment]
We should not change the behavior of this. Switch to User is available in the same screen and will provide more consistent results. 

But if we eventually need to do it, we should have in mind of showing the Customers current variation of nav-unification (enabled or disabled).

**Comment by getdave** [comment]
Agreed. I'm not sure we need to take this on as part of Nav Unification if other workarounds exist.
