### ISSUE TITLE
"Me" navigation sections seem unnessary

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49178]
I was about to give feedback about how these section headings would really do with some air around them, but then I was thinking that they aren't really helpful here anyway? 

Links under "profile" are quite vaguely related to profile, and "special" has just one link under it anyway?

<img width="286" alt="Screenshot 2021-01-22 at 12 28 56" src="https://user-images.githubusercontent.com/87168/105480307-3a78eb00-5cae-11eb-92c5-c799da6098e9.png">

Perhaps there are other links in some scenarios that I'm not seeing here, of course.

**Comment by cpapazoglou** [comment]
We have an open issue for showing these Headings nicer. But your feedback totally makes sense! As it seems here https://github.com/Automattic/wp-calypso/blob/56b3c632265448e2d7460efe5f64d8cff1e98702/client/me/sidebar/index.jsx#L130-L214

there are no other links or scenarios. @sfougnier how would you feel removing them?

**Comment by getdave** [comment]
If these headings already exist in Calypso then can we limit our scope to fixing the spacing. They must exist for a reason and I don't want to risk expanding out scope.

**Comment by cpapazoglou** [comment]
> If these headings already exist in Calypso then can we limit our scope to fixing the spacing. They must exist for a reason and I don't want to risk expanding out scope.

After my comment above, I think:
- there is no risk removing them
- removing them would be much easier than fixing the spacing which is not so obvious cause the same component (Heading is used in My Sites).

**Comment by ghost** [comment]
I am all for removing the labels! We don't have them on any other menu at this time, so they seem a little random and don't seem to add much value here.

Could we still maintain a little bit of padding between 'Blocked sites' and 'Get apps'? Perhaps whatever the equivalent is between 'Products' and 'Jetpack' here:
<img width="412" alt="Screen Shot 2021-01-26 at 11 18 52 AM" src="https://user-images.githubusercontent.com/67021691/105872320-46bfb980-5fc8-11eb-8f92-47f579f37c73.png">

**Comment by tjcafferkey** [comment]
This became even more obvious after the recent changes to the hover effects introduced by https://github.com/Automattic/wp-calypso/pull/50427 so I've created a quick PR to fix this.

**Comment by simison** [comment]
These titles are still present and still redundant. :-)

**Comment by cpapazoglou** [comment]
> These titles are still present and still redundant. :-)

This PR should resolve it https://github.com/Automattic/wp-calypso/pull/52438
