### ISSUE TITLE
"Me" sidebar gone for small screens

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49177]
This:

<img width="921" alt="Screenshot 2021-01-22 at 12 33 43" src="https://user-images.githubusercontent.com/87168/105480192-1b7a5900-5cae-11eb-9d71-2021ef3a1c84.png">

Turns into this for small screens and I can't navigate anymore:

<img width="686" alt="Screenshot 2021-01-22 at 12 30 42" src="https://user-images.githubusercontent.com/87168/105480135-09001f80-5cae-11eb-84c4-1b16e9a2991f.png">

**Comment by cpapazoglou** [comment]
Clicking "Me" will open the sidebar ( as it will for "My Sites" and "Reader" ).

We have already tried tackling this not so intuitive behavior here https://github.com/Automattic/wp-calypso/issues/48182.

TL;DR;
If you were already in a smaller screen and clicked "Me" you would be first presented with the sidebar (navigation) which would make you think that clicking "Me" again will open the sidebar.

cc @sfougnier for visibility.

**Comment by simison** [comment]
Right, so the problem was that I "resized" the screen by opening Dev tools.

Same could happen by changing orientation of iPad for example I suppose.

Sounds not much of a problem then! :-)

**Comment by ghost** [comment]
The above comments may be more feedback about how intuitive the mobile views are, but I took a look at the window resizing with dev tools, and by manually resizing my window down to a mobile-size screen, and I noticed the menus weren't visible when I toggled them open/closed until I refreshed.

**Comment by getdave** [comment]
@obenland Can you and I triage this one please?

**Comment by obenland** [comment]
I think High is appropriate, probably one of the first issues that should be looked at post launch.

**Comment by mmtr** [comment]
Seems this is no longer reproducible?

![Feb-26-2021 13-25-41](https://user-images.githubusercontent.com/1233880/109299986-37859300-7836-11eb-90ff-b01539b1fe61.gif)

Please, feel free to re-open if needed.
