### ISSUE TITLE
Sidebar scroll/fixed state seems to have a variety of bugginess and jumpiness depending on screen size

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#49175]
See p7DVsv-ago-p2#comment-33833.

Essentially  depending on screen size, length of the content in the sidebar, and if you resize the browser in various scroll positions the sidebar scroll seems to be buggy.

We also see a spike in CPU usage which needs to be addressed.

<img width="561" alt="Screen Shot 2021-01-22 at 09 57 56" src="https://user-images.githubusercontent.com/444434/105476260-5376a180-5c98-11eb-84bb-f571b1544f3e.png">

### Steps to reproduce the behavior

To reproduce, browser size needs to be slightly larger than the navigation content:

<img width="340" alt="screenshot-2021-01-22-at-11 37 21" src="https://user-images.githubusercontent.com/444434/105476308-61c4bd80-5c98-11eb-814b-dde9b5cf7670.png">

Then if it’s not happening yet, resize the browser window’s height just lightly and try scrolling again. Sidebar should now scroll in a “broken state”.

**Comment by frontdevde** [comment]
### How to reliably reproduce the issue:

- Load /home page with enough space for the entire sidebar to fit the screen
- Resize the window to make the height smaller than the sidebar
- Scroll down the page to the end and all the way up again
- Resize the window to make the height taller than the sidebar 
- Scrolling the page now leaves the sidebar in a detached state

**Comment by getdave** [comment]
I tried but could not replicate in either Chrome or Firefox. Is there anything else you've uncovered?

**Comment by frontdevde** [comment]
> I tried but could not replicate in either Chrome or Firefox.

Weird, I can still reliably reproduce the issue with the steps above.

> Is there anything else you've uncovered?

Yes, after some sleuthing I've found the root of the issue: when resizing from a window where the sidebar doesn't fit to a window where it does, we don't remove the inline styles. I've found a solution, PR incoming.
