### ISSUE TITLE
Gutenboarding: "Choose a domain I own" layout on mobile viewport

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#49171]
#### What I expected to happen

The "Use a domain I own" button should be aligned to the right, and the "Already own a domain" should not collapse as much when the page is resized

#### Acceptance Criteria
* [ ] The copy and CTA-link are stacked (i.e. placed on separate rows) on mobile
* [ ] The copy and CTA-link are not stacked on desktop

### Steps to reproduce the behavior

1. Navigate to `wordpress.com/new`
2. Enter the site's name and continue
3. In the domain screen, resize the page to the size of a mobile viewport
4. Notice how the last row of the list ("Choose a domain I own") has a weird layout on mobile, due do how the text resize
5. The issue is worse for more verbose languages (e.g french)

#### Screenshots

|  English:  | French:  |
|---|---|
| <img width="327" alt="Screenshot 2021-01-22 at 08 40 30" src="https://user-images.githubusercontent.com/1083581/105462985-b7e13300-5c8f-11eb-8f96-f55d1c3c3404.png"> | <img width="320" alt="Screenshot 2021-01-22 at 08 40 16" src="https://user-images.githubusercontent.com/1083581/105462980-b6176f80-5c8f-11eb-8483-01b24ab0275f.png"> |

**Comment by razvanpapadopol** [comment]
By adding these styles to `button.action_buttons__button.components-button` we could partly solve the space occupied by the button. But we still have to position the arrow correctly.

```
text-align: right;
flex: 1;
justify-content: flex-end;
```

<img width="311" alt="Screenshot 2021-01-22 at 09 58 59" src="https://user-images.githubusercontent.com/14192054/105467789-d6025f80-5c9e-11eb-8ca4-0b210bb241f6.png">

**Comment by StefanNieuwenhuis** [comment]
While we're at it, we have to improve HTML semantics as well. All `.domain-picker__suggestion-item` are `<button/>` while the "Use a domain I own" is a `<label/>`. 

What we want to achieve is that every row is completely clickable. To achieve this, we use a `<button/>` for all domain suggestions and a `<label/>` for the "Use a domain I own" option. The purpose and results are the same, so why aren't we using the same elements?  

<img width="536" alt="Screenshot 2021-01-22 at 11 07 15" src="https://user-images.githubusercontent.com/12104589/105477524-3d6dde80-5ca2-11eb-9454-27d073d3d26a.png">

Please test any changes added to the step-by-step launch in the focused launch flow as well.

**Comment by StefanNieuwenhuis** [comment]
The problem is that we don't have enough screen estate on the mobile viewport to display both copy and CTA-button in the same row. A possible solution is to apply the layout from `/start` (see screenshot). Placing both copy and CTA-button on separate rows generates enough space for both. 

@ollierozdarz what do you think about this solution? 

<img width="381" alt="Screenshot 2021-01-25 at 09 27 12" src="https://user-images.githubusercontent.com/12104589/105680202-b0b86000-5eef-11eb-98c0-a9dbae9f52b4.png">

**Comment by ollierozdarz** [comment]
> The problem is that we don't have enough screen estate on the mobile viewport to display both copy and CTA-button in the same row. A possible solution is to apply the layout from `/start` (see screenshot). Placing both copy and CTA-button on separate rows generates enough space for both.

100%, @StefanNieuwenhuis. This is the way to go. It's fine that it's not side by side like the table above it. Let me know if you need any help styling it or a final review 🙂

**Comment by StefanNieuwenhuis** [comment]
> 100%, @StefanNieuwenhuis. This is the way to go. It's fine that it's not side by side like the table above it. Let me know if you need any help styling it or a final review 🙂

Awesome @ollierozdarz! Thanks for your reply.
