### ISSUE TITLE
Nav Unification: Publicize / Sharing / Traffic settings missing for Jetpack sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#49187]
### Steps to reproduce the behavior

1. Start from a Jetpack site connected to WordPress.com, running either Jetpack `master` or the current stable.
2. In wp-admin, go to Jetpack > Settings > Sharing
3. Click on "Connect your social media accounts" (the option to manage connected social media accounts is only available in Calypso)
4. You'll land in Calypso, in `https://wordpress.com/marketing/connections/yoursite.com`. That page does not have a corresponding menu item in the sidebar, though.

- The same applies for `https://wordpress.com/marketing/sharing-buttons/yoursite.com` (accessible via Jetpack > Settings > Sharing)
- The same applies for `https://wordpress.com/marketing/traffic/yoursite.com (accessible via Jetpack > Settings > Traffic > Customise your SEO settings or Jetpack > Settings > Traffic > Configure your Google Analytics settings

**Comment by cpapazoglou** [comment]
This is a tricky one! Thanks @jeherve for discovering it! It seems that we do have a Marketing menu item under Tools which opens `https://wordpress.com/marketing/tools/yoursite.com`. Sadly though, this screen has a second navigation element 

![](https://cln.sh/5cf1QD+)

Clicking any of these menus (except the first) doesn't correspond to an active element in the sidebar. We are having the same problem with any similar screen. Another example `https://wordpress.com/settings/general/yoursite.com` and `https://wordpress.com/people`. 

This is not related to Jetpack, it's a pure Calypso - navigation issue.

**Comment by getdave** [comment]
Can I confirm what the expected solution would be here? Is it:

- make settings available in Calypso?
- allow these particular links to default to WPAdmin?

Many thanks

**Comment by jeherve** [comment]
I think we should make those settings available in Calypso. There are no versions of those settings anywhere in wp-admin right now, so we can't really link to wp-admin in this case.

**Comment by obenland** [comment]
Hm, I'm still now quite clear on what the expected outcome is for this one.

Is this a matter of highlighting the submenu item that corresponds to a tabbed menu?
Or adding submenu items to the navigation for each tabbed menu?

**Comment by jeherve** [comment]
Things have changed a bit since I opened that issue. We now have a Marketing menu in the sidebar, under Tools, linking to this Calypso page. I believe this brings back the behaviour we had with the old nav, it may consequently be enough at this point.

**Comment by obenland** [comment]
Thanks for that feedback! Let's close for now then
