### ISSUE TITLE
Navigation colors bleeding to "coming soon" badges at Notifications

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49180]
At https://wordpress.com/me/notifications I see dark colored badges:

Before

<img width="1120" alt="Screenshot 2021-01-22 at 12 48 15" src="https://user-images.githubusercontent.com/87168/105481822-3f3e9e80-5cb0-11eb-8805-5f9bcf664caa.png">

After

<img width="904" alt="Screenshot 2021-01-22 at 12 48 31" src="https://user-images.githubusercontent.com/87168/105481834-41a0f880-5cb0-11eb-8826-686bf52f8cf2.png">

**Comment by getdave** [comment]
@frontdevde Would you be able to investigate this? Could you possibly triage with:

- Test and confirm.
- Steps required to fix.
- Estimated effort.

Much appreciated.

**Comment by frontdevde** [comment]
Confirmed. 

It's reusing the site badge that originated in the sidebar. So it's using the sidebar colors that had to change in Nav Unification. We'll need to change this so the styles in the sidebar differ to when the site badge is used outside the sidebar.

Effort small (needs to be tested across color schemes though) =>  (2-3P)

**Comment by simison** [comment]
Looks like the site picker is busted, too and the hover color is even more jarring:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/87168/108183649-f8a75d00-7112-11eb-8174-5ca79f90a42c.png">
<img width="437" alt="image" src="https://user-images.githubusercontent.com/87168/108183685-02c95b80-7113-11eb-97a1-b4717f061364.png">

**Comment by retrofox** [comment]
> Looks like the site picker is busted, too and the hover color is even more jarring:
> 
> <img alt="image" width="471" src="https://user-images.githubusercontent.com/87168/108183649-f8a75d00-7112-11eb-8174-5ca79f90a42c.png">
> 
> <img alt="image" width="437" src="https://user-images.githubusercontent.com/87168/108183685-02c95b80-7113-11eb-97a1-b4717f061364.png">

@sfougnier  can you help us to define how it should look? Keep the colors defined by the nav unification, or should we apply neutral colors here too?

**Comment by ghost** [comment]
The hover on white areas should likely match that of the hover styles in other white backgrounds of the admin interface:

<img width="428" alt="Screen Shot 2021-03-31 at 4 14 28 PM" src="https://user-images.githubusercontent.com/67021691/113205336-2ddbba80-923c-11eb-9e35-fde881605f7d.png">
 
<img width="278" alt="Screen Shot 2021-03-31 at 4 13 03 PM" src="https://user-images.githubusercontent.com/67021691/113205172-fb31c200-923b-11eb-9588-4249013e7ad8.png">

**Comment by retrofox** [comment]
> The hover on white areas should likely match that of the hover styles in other white backgrounds of the admin interface:

Thanks, Saul. Addressed here https://github.com/Automattic/wp-calypso/pull/51630
