### ISSUE TITLE
Nav Unification: Upgrades / Stats menu missing for some sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#49186]
### Steps to reproduce the behavior

1. Start with a Jetpack site connected to WordPress.com, running the current version of Jetpack (9.3.1) without any additional filters.
2. Go to https://wordpress.com/stats/
3. Switch to that site.
4. You'll find that only wp-admin menu items are listed, which is problematic since those menu items are needed for plan management and to see stats.

**Running 9.3.1**
![image](https://user-images.githubusercontent.com/426388/105492725-a82a1480-5cb8-11eb-8aa3-8a3073f3ebeb.png)

**Running Jetpack 9.4-alpha with the `jetpack_load_admin_menu_class` filter active**

<img width="370" alt="Screenshot 2021-01-22 at 13 49 53" src="https://user-images.githubusercontent.com/426388/105492881-e7f0fc00-5cb8-11eb-8975-0bfdf7806d74.png">

**Comment by cpapazoglou** [comment]
@getdave this seems like a good issue for tackling the Jetpack menu! Please close it if we already have another one.

**Comment by obenland** [comment]
Let' close in favor of https://github.com/Automattic/wp-calypso/issues/49120.
