### ISSUE TITLE
Testing: Get rid of temporary helper `useFilesystemMocks`

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#4918]
Part of #4915.

To speed up unit tests migration we crated temporary helper `useFilesystemMocks`. Now it's time to get rid of it completely.

We still use it in 16 test files:
![screen shot 2016-04-21 at 11 37 33](https://cloud.githubusercontent.com/assets/699132/14704576/ac2fccee-07b5-11e6-92c6-7d67e2529717.png)

To replace it we should use `mockery.registerMock` explicitly for each file replacement. At the same time we should keep our current patter and put all mocks into `mocks` subfolder. Then we can drop this helper completely.

**Comment by blowery** [comment]
Why get rid of it? If we want mocks to live in a commonly named subfolder, having a helper to load them seems to make sense.

maybe we should instead rework the helper to just load mocks into a passed mockery instance, instead of pulling in mockery itself?

**Comment by gziolo** [comment]
Closing it for now, I think we can keep it as it is and promote other solutions when adding new tests :)
