### ISSUE TITLE
Unread indicators in Reader are difficult to read after Nav unification changes

### ISSUE THREAD

**Issue by robfelty** [Automattic/wp-calypso#49192]
### Steps to reproduce the behavior

1. Set color scheme to Aqua at https://wordpress.com/me/account
2. Go to https://wordpress.com/read

#### What I expected to happen
I expected that I would be able to easily read the number of unread posts per site I follow. 

#### What actually happened
The number of unread messages is in a dark blue color which is very difficult to read on the blue background of the sidebar. 
### Context
See screenshots

#### Browser / OS version
Latest Firefox and Chrome on MacOS

#### Is this specific to the applied theme? Which one?
No.

**Comment by frontdevde** [comment]
Closing this as a duplicate as it was also reported here https://github.com/Automattic/wp-calypso/issues/48009#issuecomment-764826837

Either way it'll be fixed in https://github.com/Automattic/wp-calypso/pull/49408
