### ISSUE TITLE
Nav Unification: masterbar styles impact the custom Jetpack checkout bar

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#49199]
I'm not sure this qualifies as a bug, or just a little cosmetic change that may be worth doing.

### Steps to reproduce the behavior

1. Start from a Jetpack site connected to WordPress.com.
2. Purchase a plan for that site, starting from wp-admin (one way to get a checkout link is to add `add_filter( 'jetpack_block_editor_enable_upgrade_nudge', '__return_true' );` to your site and then go to Posts > Add New and insert a paid block to get an upgrade nudge with a checkout link).
3. On the checkout page, you'll see that the Jetpack logo is a bit squeezed:

<img width="627" alt="Screenshot 2021-01-22 at 18 07 16" src="https://user-images.githubusercontent.com/426388/105522139-27314400-5cdd-11eb-83d8-a5ad49ccd3e0.png">

**Comment by retrofox** [comment]
How should we fix this visual issue?

**Comment by retrofox** [comment]
has it been fixed? Testing with  my Jetpack dev site:

<img width="779" alt="Screen Shot 2021-04-09 at 1 34 50 PM" src="https://user-images.githubusercontent.com/77539/114212721-86940d00-9938-11eb-8eed-c00c3e71f69f.png">

**Comment by jeherve** [comment]
Good catch.

It may be harder to get into that issue now, since nav-unification isn't enabled in Calypso for Jetpack sites anymore; Jetpack sites get the old nav.

Closing.
