### ISSUE TITLE
Empty white bar under navigation on some .com themes

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49190]
See e.g. https://rockfielddemo.wordpress.com

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/87168/105501258-a702e280-5ccc-11eb-921d-7f4d8f352c38.png">

Affects multiple designs in onboarding design grid (https://wordpress.com/new/design), and theme showcase (https://wordpress.com/themes/), as well likely customer's sites using these themes.

Originating from Varia theme.

Sorting out at p1611323182006300-slack-dotcom-create

FYI @cathymcbride

**Comment by kriskarkoski** [comment]
Report of this in 3670955-zen

**Comment by MaggieCabrera** [comment]
Fixed via https://github.com/Automattic/themes/pull/3086
