### ISSUE TITLE
Devdocs: separate typography example from components

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#492]
We should move the typography examples in `/devdocs/design` to a separate route and a separate sidebar item, so that we only have components there.

**Comment by afsheenirani** [comment]
@mtias - Is this issue still required? I see Typography as a separate link on the Sidebar. Do let me know if I have mis-interpreted the requirement.

**Comment by afsheenirani** [comment]
@mtias - Just checking in to see if you have any thoughts...
cc: @nb for comments as well

**Comment by mtias** [comment]
Yes, this is done.

**Comment by afsheenirani** [comment]
Thanks @mtias !
