### ISSUE TITLE
Nav Unification: Show WooCommerce menu items in Calypso, as shown in wp-admin, if WooCommerce plugin is active on Atomic site

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49209]
The navigation sidebar menu in Calypso does not show all the WooCommerce menu items that are shown in wp-admin for Atomic sites. In addition, the "Products" custom post type menu item is shown incorrectly (wrong location and icon).

## Actual (current Calypso)

<img width="281" alt="Nav Unification - Calypso Menu" src="https://user-images.githubusercontent.com/2098816/105546673-a61d8100-5ccb-11eb-8a17-4cc795716e6b.png">

- Missing: "WooCommerce" and "Marketing" menu items
- Incorrect: "Products" menu item is in wrong location and has wrong icon

## Expected (current wp-admin)

<img width="281" alt="Nav Unification - wp-admin Menu" src="https://user-images.githubusercontent.com/2098816/105546704-b03f7f80-5ccb-11eb-9217-5946966e8b61.png">

- Notice that all WooCommerce-related menu items are present, including "Products" in the correct location and with the correct icon
- Note that this introduces the change from "Store" to "WooCommerce" for eCommerce customers. This is by design. See pbIJXs-zt-p2#comment-1697

**Comment by psealock** [comment]
With WooCommerce Navigation using the eComm plan, not Business plan, Products, Analytics, and Marketing are no longer top level items as they are nested in the Woo Nav.

<img width="232" alt="Screen Shot 2021-01-25 at 12 16 09 PM" src="https://user-images.githubusercontent.com/1922453/105646866-24199c00-5f07-11eb-9528-ed3223a472ae.png">

Depending on the timing of everything it appears we may need to cater to two scenarios:

* eComm plan with Woo Nav
* Business plan without Woo Nav

Without knowing anything about what goes on under the hood, I'm not sure how this will pan out but Woo Nav does hide those top level Nav items and replaces them within its Nav UI. It also does this for any extension that registers with the Nav, so we'll need to test that scenario as well. Given this, it may be that Business plan won't require extra attention.

**Comment by mattsherman** [comment]
@psealock Can't eCommerce users disable the new navigation? So, depending on the order of the rollouts of Nav Unification and the new WooCommerce Navigation, we might have:

- eCommerce with new WooCommerce Navigation
- eCommerce without new WooCommerce Navigation
- Business with new WooCommerce Navigation
- eCommerce without new WooCommerce Navigation

**Comment by psealock** [comment]
>we might have:

Yes, absolutely. We need to handle all 4 cases

**Comment by Nic-Sevic** [comment]
Adding to this: If you click the Analytics item and then backout to the main dashboard the menu item switches to WooCommerce

initially: https://d.pr/i/ktjcCH

once clicked and backed out: https://d.pr/i/1amzUT

**Comment by mattsherman** [comment]
@Nic-Sevic This is because the first screenshot (with the Analytics item) is the Calypso sidebar menu. The second one (with the WooCommerce item) is the wp-admin sidebar menu.

**Comment by mattsherman** [comment]
There are two related PRs that may help address this issue:

- 577-gh-Automattic/wpcomsh
    - This one *should* help get the WooCommerce menu items showing, but with incorrect positioning
- https://github.com/woocommerce/woocommerce/pull/28763
    - This one fixes the positioning of menu items, but introduces some issues for certain WooCommerce plugins

**Comment by mattsherman** [comment]
Estimating this as a 5. It seems like we are probably nearly there with the two above related PRs, but a lot of coordination and communication between different teams may be required, which can take time.

**Comment by mattsherman** [comment]
Update: Note that with 577-gh-Automattic/wpcomsh#issuecomment-771947625, the WooCommerce menu items mostly appear correctly. Assuming that PR lands, we will have some minor issues to take care of, which I will create separate issues for.

**Comment by psealock** [comment]
I took eComm plan for a spin with Nav Unification turned on as well as WC Nav turned on. An initial poke around shows everything working as it should 🤞🏽. I can toggle the Nav on and off, move around WC pages, and go back to the dashboard correctly.

When I click "Back to Dashboard" I'm directed to wp-admin. I know there was an [issue around this previously](https://github.com/woocommerce/woocommerce-admin/issues/5866) and a filtering ability was added, but I'm not sure if this is a regression or if I need The Bridge to make that part work.

<img width="226" alt="Screen Shot 2021-02-03 at 2 23 34 PM" src="https://user-images.githubusercontent.com/1922453/106684668-c3d3da00-662b-11eb-881b-6ae65bcf9706.png">

I even tested the in-progress flyout menu https://github.com/woocommerce/woocommerce-admin/pull/6165 and its working well too.

Another thing to note is when I visited Calypso, there was no WooCommerce at all. I'm assuming thats a Calypso issue being dealt with separately.

<img width="266" alt="Screen Shot 2021-02-03 at 2 20 25 PM" src="https://user-images.githubusercontent.com/1922453/106684677-c9312480-662b-11eb-979a-b446c3714593.png">

**Comment by mattsherman** [comment]
@psealock 

> Another thing to note is when I visited Calypso, there was no WooCommerce at all. I'm assuming thats a Calypso issue being dealt with separately.

That is *this* issue. 😄

The fix for this issue is looking like it will be in wpcomsh. See 577-gh-Automattic/wpcomsh#issuecomment-771947625, as mentioned in the comment above.

If you can test that wpcomsh PR with WC Nav enabled, you can see how things appear in Calypso. I can do that tomorrow as well -- I already have a test site all ready to go, so enabling WC Nav should be pretty easy.

**Comment by mattsherman** [comment]
@psealock I tested with WC Nav enabled. It does not function in Calypso. The non-WC Nav menu shows.

wp-admin:

https://user-images.githubusercontent.com/2098816/106815430-d3f6b400-6641-11eb-8341-25eddc19476b.mov

Calypso:

https://user-images.githubusercontent.com/2098816/106815454-de18b280-6641-11eb-902c-53053c888751.mov

Clicking on the "WooCommerce" menu item does not work in either scenario (WC Nav or no WC Nav), though submenus do -- I will dig into that tomorrow.

**Comment by psealock** [comment]
>Clicking on the "WooCommerce" menu item does not work in either scenario

The url is incorrect. `/wp-admin/admin.php?page=woocommerce` should have the query param `wc-admin` not `woocommerce`. If you change the url manually using the inspector, both nav and non-nav scenarios work as they should.

>I tested with WC Nav enabled. It does not function in Calypso.

Since all WooCommerce links direct back to wp-admin, where Navigation does work, once we can get the WooCommerce Home link working we should be good here. You can test it out by enabling Navigation, and visit any submenu item such as Orders and see the Navigation functioning correctly on page refresh. Thankfully, Woo Navigation doesn't need to work in the Calypso environment.

Two known issues did surface:

1. Clicking `WordPress Dashboard` to exit the Woo Nav goes to wp-admin instead of wordpress.com. https://github.com/Automattic/wc-calypso-bridge/issues/633
2. Woo Navigation creates its own flyout menu populated with a slightly different set of items depending on a user's "favorites", https://github.com/woocommerce/woocommerce-admin/issues/6223. For now, the default menu functions well and without error, but is not ideal.

**Comment by mattsherman** [comment]
Thanks for giving Navigation a spin @psealock! 🙌 

> The url is incorrect. `/wp-admin/admin.php?page=woocommerce` should have the query param `wc-admin` not `woocommerce`. If you change the url manually using the inspector, both nav and non-nav scenarios work as they should.

Indeed. I assume that the page gets re-set somewhere in the wc-admin initialization when it takes over as the Home page for WooCommerce... I need to dig into this.

> > I tested with WC Nav enabled. It does not function in Calypso.
> 
> Since all WooCommerce links direct back to wp-admin, where Navigation does work, once we can get the WooCommerce Home link working we should be good here. You can test it out by enabling Navigation, and visit any submenu item such as Orders and see the Navigation functioning correctly on page refresh. Thankfully, Woo Navigation doesn't need to work in the Calypso environment.

Yes, I can confirm that Navigation works as expected in wp-admin. And, that it really doesn't need to "work in Calypso" as long as the top level "WooCommerce" menu item works properly.

>     2. Woo Navigation creates its own flyout menu populated with a slightly different set of items depending on a user's "favorites", [woocommerce/woocommerce-admin#6223](https://github.com/woocommerce/woocommerce-admin/issues/6223). For now, the default menu functions well and without error, but is not ideal.

I added another comment to that issue... I still feel like we shouldn't have to do anything special to get the flyout working in Calypso.

**Comment by mattsherman** [comment]
I'm going to mark this issue as Closed, as the overall issue has been addressed and more specific issues are being created as needed. See pbIJXs-Fz-p2#comment-2186
