### ISSUE TITLE
Purchases: issues deleting site with a Free Trial

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#4920]
The site deletion flow presents inconsistencies if a site has an active free trial.

Steps to reproduce:

- Sign up for a new site with a free trial from `/start/free-trial`
- Visit `/purchases` and notice that it says you have no upgrades.
- Visit `/settings/general/:site` and click the Delete Site option.
- You'll be told you have active upgrades and can't delete your site. Click the Manage Purchases button in that warning.
- You'll be taken to `/purchases` but instead of seeing the empty list, you'll see a Premium subscription due to expiration soon. There's no indication that's a free trial subscription.

We should make sure that users can still delete their sites have an active free trial. We should also ensure free trials never show in `/purchases`.

**Comment by stephanethomas** [comment]
This was fixed in D1670-code server-side.
