### ISSUE TITLE
Design Picker: "Easley" design rendering incorrectly on Font screen

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49215]
Compare design as it appears on design picker screen …

![image](https://user-images.githubusercontent.com/545779/105552973-5db19380-5cca-11eb-81b2-c1d4f83a4959.png)

With the font screen …

![image](https://user-images.githubusercontent.com/545779/105553014-6efaa000-5cca-11eb-8215-248794ce7e24.png)

**Comment by razvanpapadopol** [comment]
The difference seems to be just because of the responsive design. If you open the font screen on a larger screen, then the preview will match design thumbnail
