### ISSUE TITLE
Nav Unification: Cannot access site visibility dashboard

### ISSUE THREAD

**Issue by mattgawarecki** [Automattic/wp-calypso#49210]
### Steps to reproduce the behavior

1. Go to https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs&show=hidden; or, open the Site Switcher and click the *Change* link at the bottom, as shown here:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/670067/105535104-09031e00-5cb4-11eb-8ce6-d0d08235f3fa.png">

2. Observe the following error screen:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/670067/105534720-89754f00-5cb3-11eb-97c4-2ba9081f15b8.png">

#### What I expected to happen

I would have expected to see the site visibility dashboard, so that I can adjust which of my sites are hidden, which are visible, and/or select a primary site.

#### Browser / OS version

macOS 10.15.7
Firefox 84.0.2

**Comment by obenland** [comment]
Thanks for the heads-up! Fixed in r219921-wpcom.
