### ISSUE TITLE
Notifications: Message saying that plan needs to be renewed after plan renew

### ISSUE THREAD

**Issue by felipevelzani** [Automattic/wp-calypso#49214]
#### References

18360196-hc

#### Steps to reproduce the behavior

1. Go to the user that opened the HappyChat, and access their WordPress.com Dashboard with SU
2. Click for checking the notifications
3. You should be able to see it there: https://d.pr/i/RkFD0S/jOmvozDvBh

#### What I expected to happen

The message should not be there, or it could have a warning on it saying that the plan was renewed already

#### What actually happened

It showed this message even after having it renewed and user got confused

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It seems to be mostly making some users confused, but also doesn't look to be happening with all users

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://d.pr/i/RkFD0S/jOmvozDvBh

**Comment by michaeldcain** [comment]
This is being tracked and worked on in c/EPIsnyN9-tr

**Comment by sirbrillig** [comment]
Should be fixed by D56438-code
