### ISSUE TITLE
Design Picker: Outdated thumbnail for Stratford design

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49217]
The thumbnail for the Stratford design showcases a now-fixed rendering error from the starter design. The icons shown below are the wrong size.

![image](https://user-images.githubusercontent.com/545779/105553450-03650280-5ccb-11eb-830b-793e310006a6.png)

Expected output can be seen below from https://stratfordstarter.wordpress.com/

![image](https://user-images.githubusercontent.com/545779/105553485-1b3c8680-5ccb-11eb-8528-3f55b991b4b5.png)

**Comment by razvanpapadopol** [comment]
Now that we're using mShots, this should be fixed, right? 
cc: @autumnfjeld @deBhal

**Comment by deBhal** [comment]
Yep, here's a live screenshot with the icons looking nice and round:

![WordPress_com](https://user-images.githubusercontent.com/5952255/118441229-3b85ca80-b72c-11eb-843f-fd84163109eb.jpg)

I'm going to go ahead and close this, but please re-open if I've misunderstood.
