### ISSUE TITLE
Nav Unification: Show WooCommerce menu items in Calypso, as shown in wp-admin, if WooCommerce plugin is active on Jetpack site

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49229]
The navigation sidebar menu in Calypso does not show all the WooCommerce menu items that are shown in wp-admin for Jetpack sites. In addition, the "Products" custom post type menu item is shown incorrectly (wrong location and icon).

## Actual (current Calypso)

<img width="281" alt="Screen Shot 2021-01-23 at 06 52 34" src="https://user-images.githubusercontent.com/2098816/105577791-b4aa7d80-5d49-11eb-8649-9cf74e6bb611.png">

- Missing: "WooCommerce" and "Marketing" menu items
- Incorrect: "Products" menu item is in wrong location and has wrong icon

## Expected (current wp-admin)

<img width="160" alt="Screen Shot 2021-01-23 at 06 52 55" src="https://user-images.githubusercontent.com/2098816/105577798-bb38f500-5d49-11eb-831a-114b7c5b0418.png">

- Notice that all WooCommerce-related menu items are present, including "Products" in the correct location and with the correct icon

**Comment by psealock** [comment]
We'll need to check that this works with Woo Navigation turned on, see https://github.com/automattic/wp-calypso/issues/49209#issuecomment-766458367 for more info.

**Comment by mattsherman** [comment]
Related discussion on Jetpack admin menu in general: p1HpG7-b2s-p2

**Comment by mattsherman** [comment]
Estimating this as a 3 mainly due to uncertainty. It is possible that there will be nothing specific to address, once #49209 is taken care of.

**Comment by mattsherman** [comment]
I'm going to close this one, as I do not believe there anything specific to Jetpack that we need to address for WooCommerce.

/cc @getdave
