### ISSUE TITLE
Page Template and Block Pattern images not added to Media Library 

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#49225]
Encouraged to create this bug report while testing another bug we have found.  https://github.com/Automattic/jetpack/issues/18362#issuecomment-762174767

### Steps to reproduce the behavior
1. Create a new page/post.
2. Select a page template/block pattern that includes images.
3. Publish page/post.
4. Go to media library.
5. The media library will be empty.
6. Alternatively you can inspect the images on the page/post and see the images are not coming from the site's media.

#### What I expected to happen
I believe the images should be loaded to the site's media library when using a page template or block pattern.  This appears to be functionality that was added here - https://github.com/Automattic/wp-calypso/pull/34839

#### Is this specific to the applied theme? Which one?
This is not specific to any theme. 

#### Does this happen on simple or atomic sites or both?
This occurs on both Atomic and Simple.

#### Is there any console output or error text?
I am not seeing any that appear to be specific to this. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This affects all sites I have tested on with my own test account. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Here is a quick video showing my testing process - https://d.pr/v/tbvtJ2

**Comment by simison** [comment]
> I believe the images should be loaded to the site's media library when using a page template or block pattern. 

I think my gut feel would actually not do this because they're just demo images I'd expect customers to replace. @ianstewart UX-thoughts on this one?

cc @ramonjd @autumnfjeld

**Comment by ramonjd** [comment]
We discussed this not long ago in the context of the page picker pb3aDo-Gg-p2

I believe the general thrust was that, if we decided it was a good thing, we'd try to import via the front end using the external-media-upload API.

Another idea floating around was to give the user a choice to add the images to the library, though we didn't speak about the UX.

I think I agree that we should err on the side of demo, that is, assume that the user doesn't really want their media library filled up with images that are not related to their site.

**Comment by simison** [comment]
Thanks, Ramon! Yep, agreed. I don't think asking would be a good experience either, better to have a good default.

@joweber123 @ianstewart let us know if you think otherwise and happy to revisit!

[Carousel not functioning for external images](https://github.com/Automattic/jetpack/issues/18362) is still a valid issue of course.
