### ISSUE TITLE
Nav Unification: WooCommerce Support

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49228]
When Nav Unification is active, WooCommerce must be available in Calypso as if is pre-Nav Unification.

See pbIJXs-zH-p2 for details.

## Tech notes

- The admin menu for Simple, Atomic, and Jetpack sites is controlled by a module in Jetpack:
https://github.com/Automattic/jetpack/tree/f66a6341fe162e5e350be707a7dff84292e7b179/projects/plugins/jetpack/modules/masterbar/admin-menu
- Currently, the admin menu API doesn't support menu items registered behind an `is_admin()` check: 577-gh-Automattic/wpcomsh

**Comment by getdave** [comment]
@mattsherman Would it be ok to get an update on your progress with Woo support? Any blockers we can help with? Are you working to any time frames? Much appreciated.

**Comment by mattsherman** [comment]
@getdave It is always ok to get an update on progress. :-)

We are kicking off our latest sprint cycle tomorrow (Tuesday). Our main focuses are Sunset Store and Nav Unification. Sunset Store is shipping at the end of the sprint, on Feb 22. But, obviously Nav Unification is in many ways more important, because you can't ship Nav Unification without WooCommerce support, because if you did, we'd be sunsetting WooCommerce instead for our Business and eCommerce customers, which would be A Bad Thing! 😄

I'm working on testing out 577-gh-Automattic/wpcomsh to see if that improves the WooCommerce situation, but I'm running into some issues. I'm sure I'll get them sorted out tomorrow -- it's not a blocker yet, as @obenland has been very responsive to questions I've had on that. After I see where that stands, I plan on also trying out his https://github.com/woocommerce/woocommerce/pull/28763 PR to see if that further helps, and try to push things forward on that one. So, it seems very possible that without any direct code changes by Mothra, we can have WooCommerce appearing (mostly) correctly in the Nav Unification admin menu in Calypso. I should know that by the end of my day tomorrow.

As far as Sunset Store specific functionality, @ilyasfoo has an in-progress PR up for adding the "WooCommerce" menu to the admin menu for Atomic sites when WooCommerce is not yet installed -- I expect that we'll have that wrapped up in the next few days. Added the deprecated "Store" menu item should be a similar effort.

So, I'd estimate that there is a decent shot of us having Nav Unification stuff in a potentially shippable state by the end of the week, but as the main PRs for WooCommerce itself are not under our direct control, I can't be sure. As this is a largely new area for us, and involves coordination between multiple teams, I am not highly confident of that estimate.

Do you have an updated ETA/goal for launching Nav Unification, given other fixes that your team has in the works? We certainly want to try and do what we can to get the issues in this epic addressed in as timely of a manner as possible.

/cc @becdetat

**Comment by getdave** [comment]
> Do you have an updated ETA/goal for launching Nav Unification, given other fixes that your team has in the works? We certainly want to try and do what we can to get the issues in this epic addressed in as timely of a manner as possible.

Sorry to delay here. Here's the launch date info: pbAPfg-Ou-p2#comment-2570

**Comment by obenland** [comment]
@mattsherman Can this be closed or is there more work to do?

**Comment by mattsherman** [comment]
@obenland I am closing this one -- as far as I am aware, there is no more WooCommerce-specific work to do. I didn't realize this issue was still out there!
