### ISSUE TITLE
Social: Twitter share button opens both a new window and new tab

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49223]
### Steps to reproduce the behavior

Prereq. Social share is enabled (My Site > Tools > Marketing)

1. Create and publish the post.
2. View the post.
3. Locate the `Tweet` button towards bottom of the post.
4. Click on the `Tweet` button.

#### What I expected to happen
Small window pops up where user is able to compose and send tweet.

#### What actually happened
In addition to the small window (as expected), a new active tab is opened in the same browser window that loads Twitter.

### Context
User scenario manual testing.

#### Browser / OS version
Browser: Firefox Nightly 86.0a1
OS: macOS Catalina 10.15.7

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
Tested on simple.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - this is an annoyance that detracts from the polished experience.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/6549265/105562107-d0703e00-5ccd-11eb-87a4-78e57ae11de7.mov

**Comment by obenland** [comment]
@worldomonation Is this something you can still recreate?
I've tested in Safari, FF, and Chrome, and on all three browsers it opened the new window but didn't follow a link.
Maybe this was an intermittent bug during 3CPO development?

**Comment by worldomonation** [comment]
> @worldomonation Is this something you can still recreate?
> I've tested in Safari, FF, and Chrome, and on all three browsers it opened the new window but didn't follow a link.
> Maybe this was an intermittent bug during 3CPO development?

I retested this with the following:
- Browser: Firefox Nightly 90.0a1 (2021-04-28) (64-bit)
- Browser: Safari Version 14.0.2 (16610.3.7.1.9)

on both atomic and simple sites and was able to confirm the expected behavior of Twitter button.
Closing as not reproducible.
