### ISSUE TITLE
eCommerce Plan: Products section sub-items missing with the new WooCommerce Navigation 

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#49234]
### Steps to reproduce the behavior

1. Install and activate [WooCommerce Brands](https://woocommerce.com/products/brands/?aff=10486&cid=1131038)
2. Go to WP Admin > WooCommerce
2. Click on Products
3. See no Brands subsection

#### What I expected to happen
Prior to the new WooCommerce Navigation, Brands section used to be under Products

![](https://d.pr/i/Gue5Hx+)
_Link: https://d.pr/i/Gue5Hx_

#### What actually happened
Subsections added by third-party plugins (such as [WooCommerce Brands](https://woocommerce.com/products/brands/?aff=10486&cid=1131038)) under Products are now missing. Currently, only core items appear there.

![](https://d.pr/i/U62ySF+)
_Link: https://d.pr/i/U62ySF_

For example, the Brands section (added by [WooCommerce Brands](https://woocommerce.com/products/brands/?aff=10486&cid=1131038)) is missing and the only way to navigate to it is by the direct URL `/wp-admin/edit-tags.php?taxonomy=product_brand&post_type=product`

![](d.pr/i/4BckdM +)
_Link: d.pr/i/4BckdM _

#### Browser / OS version
Any

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all Atomic sites with eCommerce plan that have the new WooCommerce Navigation and [WooCommerce Brands](https://woocommerce.com/products/brands/?aff=10486&cid=1131038) installed. Possibly this affects any other plugins that do add subsections to Products. Currently only core items are under products.

![](https://d.pr/i/U62ySF+)
_Link: https://d.pr/i/U62ySF_

**Comment by zdenys** [comment]
Reported in 25634951-hc (3675865-zen)

**Comment by zdenys** [comment]
Related discussion about adding support for the New WooCommerce Navigation to the various extensions: https://github.com/woocommerce/woocommerce-admin/issues/5335

**Comment by psealock** [comment]
Thanks for opening @zdenys, this will be fixed by https://github.com/woocommerce/woocommerce-admin/pull/6179
