### ISSUE TITLE
New Page Layout Picker: create project thread

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#49239]
Let's create a project thread for the New Page Layout Picker on Create P2

See spec: pbAok1-1QJ-p2

**Comment by davipontesblog** [comment]
@autumnfjeld I think this one should have auto-closed by moving to "Done" but it wasn't, just checking if it can be closed now. Thanks!

**Comment by autumnfjeld** [comment]
Thanks @davipontesblog . I see I am missing a step in my board tidying :) I need to close issue and move it to done!  Or I think it will be moved automattically to done.
