### ISSUE TITLE
Nav Unification: Show WooCommerce menu item for Atomic sites when WooCommerce plugin is not installed

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49232]
As currently supported without Nav Unification, the "WooCommerce" menu item should be available on any Atomic site when the WooCommerce plugin is not installed.

Selecting this menu item should guide users through installing WooCommerce.

See existing behavior pre-Nav Unification for details. This was recently implemented in https://github.com/automattic/wp-calypso/issues/48423

**Comment by ilyasfoo** [comment]
I'm thinking of moving out the installation page from StoreUI and reimplement it as a standalone page with the new sidebar:

![image](https://user-images.githubusercontent.com/3747241/105652882-5cb07a00-5ef5-11eb-8d03-e822318ca77e.png)

**Comment by mattsherman** [comment]
@ilyasfoo I think that would be a good thing to do. It's something we will need once we totally remove Store (and the Store extension in Calypso) anyway.

I would implement that in two phases (PRs):

1. Refactor things to pull the installation page out of the extension and call it from the existing Calypso sidebar menu item. We have things working in Calypso right now, so we should be able to easily test this refactor.
2. Hook up the new menu item for Nav Unification by registering this "WooCommerce" menu item in `wpcomsh` (most likely). 

What do you think? Is this the approach that you would take?

**Comment by cpapazoglou** [comment]
FWIW, we are dynamically manipulating the menus of Atomic sites (both for Calypso and WPAdmin) here in Jetpack https://github.com/Automattic/jetpack/blob/c8aba01cf5f9ceb2d76b69943637ade334ca3fbb/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L13.

If there is eventually a need to make changes in `wpcomsh` here `/feature-plugins/masterbar.php:151` is probably the best place.

**Comment by getdave** [comment]
@mattsherman @ilyasfoo Do keep us in the loop with any PRs you produce and we can provide confidence check on the technical direction so as to save you headaches down the line.

**Comment by mattsherman** [comment]
Will do!

**Comment by ilyasfoo** [comment]
@mattsherman That does sound like the correct approach, I'd give it more in-depth thought tomorrow

**Comment by mattsherman** [comment]
@ilyasfoo I've moved the refactoring of the setup page from `extensions/woocommerce` to a new place in the code to its own issue, as it really is distinct from this issue of accessing it from Nav Unification. See https://github.com/Automattic/wp-calypso/issues/49424

**Comment by khristiansnyder** [comment]
I wanted to drop some feedback on this from a customer in #27971662-hc. The user was confused that WooCommerce was somehow on their site all of a sudden and wanted to remove that from showing in WP-Admin. I imagine there will be other users that do not want that to show in WP-Admin when they don't have Woo installed.

> It clutters up the dashboard and I was hoping to get rid of it.
