### ISSUE TITLE
Nav unification: Not able to see Installed themes/switch to different theme in new UI

### ISSUE THREAD

**Issue by nixiack** [Automattic/wp-calypso#49238]
### Steps to reproduce the behavior

1. Go to **Appearance > Themes**
2. See the Themes list, it shows the current theme and `Recommended`
3. Scrolling down just populates more themes to install.

#### What I expected to happen

When going to **Appearance > Themes** it should show the installed themes first, and have a separate area for the option to install other themes.  The `Recommended` themes should not show up in the Installed themes area.

#### What actually happened

It just shows the Installed theme, has a link to customize it, but it cannot switch to other installed themes.

#### Browser / OS version

Chrome Version 87.0.4280.141 (Official Build) (x86_64)

#### Is this specific to the applied theme? 

No - Calypso back end layout in general.

#### Does this happen on simple or atomic sites or both?

AT sites so far - requires plan to be able to switch themes.

#### Is there any console output or error text?

No Console error, however when going to `/wp-admin/themes.php` location instead of `/themes/*siteurl*.com` it produces an error:

![screenshot](https://d.pr/i/In29Sv+) **Image Link:** https://d.pr/i/In29Sv

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It seems to affect all of the UI unification sites, as a few of the AT sites I am testing show the issue.  The inability to switch themes can be problematic when needing to do conflict tests for WooCommerce, or if the user wants to try out different themes on the site before committing to one.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screenshot of the Themes area in an affected site:

![screenshot](https://d.pr/i/epaKT3+) **Image Link:** https://d.pr/i/epaKT3

What it should look like:

![screenshot](https://d.pr/i/4zJ6ve+) **Image Link:** https://d.pr/i/4zJ6ve

**Comment by nagpai** [comment]
The issue noted here impacts the ability of atomic users to access themes from the WordPress.org repository. 

The current Appearance link seems to redirect to the erstwhile calypso theme page that only has WordPress.com themes and a theme upload button for third party themes. It does not show WordPress.org themes. 

Users of Atomic plan would expect the ability to easily install WordPress.org Repository themes.

**Comment by obenland** [comment]
Let's add a submenu item on WoA sites that links to `/wp-admin/theme-install.php` to give them the ability to install wp.org themes.

See paYJgx-1lp-p2 + its comments for reference.

**Comment by cpapazoglou** [comment]
Relates to https://github.com/Automattic/wp-calypso/issues/49262

**Comment by mmtr** [comment]
Reopening, since the fix will be included in the next Jetpack 9.4.1 release.

**Comment by kriskarkoski** [comment]
I just ran into this on my Atomic site, but it sounds like it should be fixed is that right @mmtr? 

I'm also a little confused on the approach discussed in https://href.li/?paYJgx-1lp-p2. Will Atomic users no longer be able to install a WordPress.org theme directly and instead need to visit WordPress.org, download the theme files, and then upload them?

**Comment by obenland** [comment]
https://github.com/Automattic/jetpack/pull/18780 added a link to the theme install screen so they can browse & install dotorg themes

**Comment by mmtr** [comment]
> Will Atomic users no longer be able to install a WordPress.org theme directly

They will can. The "Appearance > Themes" menu will link to the WordPress.com themes page that includes an Upload button. 

As @obenland noted, Automattic/jetpack#18780 just adds a separate link so users can browse the WordPress.org themes.

**Comment by mmtr** [comment]
Jetpack 9.4.1 just came out, so we can close this issue now.
