### ISSUE TITLE
Nav Unification: Show deprecated Store menu item for Atomic sites with Business plan

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49231]
Atomic sites with Business plan subscriptions should have the deprecated "Store" menu item available to them, until Store is removed from Calypso.

This menu item should bring users to the deprecated `/store` experience.

See https://github.com/woocommerce/woocommerce-admin/issues/5816 for details of how deprecation works.

## Implementation notes

- The "Store" menu item should probably be added in the `wpcomsh` plugin, with something like the following (suggested in pbIJXs-zt-p2#comment-1679):

```
function wpcomsh_add_store_menu_item() {
    add_menu_page( __( 'Store', 'jetpack' ), __( 'Store', 'jetpack' ), 'manage_options', 'https://wordpress.com/store/' . ( new Automattic\Jetpack\Status )->get_site_suffix(), null, 'dashicons-cart', 50 );
}
add_action( 'admin_menu', 'wpcomsh_add_store_menu_item' );
```

- Since Store deprecation has already started, and we don't have Calypso feature flags available to us in the wpcom API endpoints, I think it is okay to just always return the "Store" menu item if the site meets the above requirements.

## Acceptance criteria

- The "Store" menu item should be available in Calypso and wp-admin for Atomic sites with Business plan.

## Tasks

- [ ] Add Store menu to Atomic sites with Business plan
- [ ] Update e2e tests for Store menu

**Comment by mattsherman** [comment]
We are going to have the same issue as in https://github.com/Automattic/wp-calypso/pull/49099... how to detect that a Business site had WooCommerce installed prior to deprecation.

Since we don't have access to the necessary information server-side, and this is a minor issue that will only exist until Store is removed completely in a few weeks, I propose we always show "Store" for Atomic Business sites with the WooCommerce plugin, regardless of whether they had WooCommerce installed before or after deprecation began.

@becdetat What do you think?

**Comment by becdetat** [comment]
@mattsherman 
> I propose we always show "Store" for Atomic Business sites with the WooCommerce plugin, regardless of whether they had WooCommerce installed before or after deprecation began.

Approved 🍭

**Comment by mattsherman** [comment]
I've updated the issue description to reflect that the "Store" menu will be shown for Atomic sites with a Business plan, regardless of when WooCommerce was installed.

**Comment by mattsherman** [comment]
Closing this since Nav Unification will not launch until after Store is removed.
