### ISSUE TITLE
Nav Unification: Updates to e2e tests for Store menu

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#49243]
Current e2e tests Store UI using calypso sidebar menu. I foresee the changes will affect tests, and thus needs to be updated to be compatible with the new navigation menu.

**Comment by mattsherman** [comment]
This should be a part of the issue where we add the "Store" menu item in. Closing in favor of https://github.com/automattic/wp-calypso/issues/49231.
