### ISSUE TITLE
New Page Layout Picker: investigation and define tech specs

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#49240]
Let's define how we're going to tackle the New Page Layout Picker, and update the spec p2 post accordingly.

- [x] Assess feasibility of moving core functionality to a package so we can share it across apps https://github.com/Automattic/wp-calypso/pull/49661
- [x] Identify any required changes to PTK
- [x] Define development tasks
- [x] ~~Do we need a tech spike?~~

### Technical requirements

- Ensure that all functionality works on Simple and Atomic sites
- Unit test suite for minimum coverage
- Supported browser testing
- Testing on any upcoming Gutenberg WPCOM releases
-  i18n
- Accessibility (keyboard navigation, screen reader testing) and acceptance review

See spec: pbAok1-1QJ-p2

**Comment by lsl** [comment]
Read for extra context: pbAok1-1QJ-p2#comment-3756

**Comment by ramonjd** [comment]
Also pbAok1-1QJ-p2#comment-3777

> showing more accurate page template thumbnails based on customer’s active theme, CSS and the theme color selections. In future also Global styles.

This will increase scope, so let's make a call on whether we do it now or later.

 Relates to working on PTK/demo endpoint/other API to serve up the pages, and then see if mshots can handle it.

**Comment by ramonjd** [comment]
Okay, I can kick off the discussion on which tasks we can define for this.

I can see 3 tasks we can start straight away:


1. Move the page picker component code to /packages so we can pull in into the ETK plugin, e.g., `import PagePicker from '@automattic/wpcom-page-picker';` @roo2 
2. Implement the new design (can be done in parallel) including design image previews @autumnfjeld 
3. Check the patterns response, assess if we need to do any work Customize/integrate Pattern API (if necessary). Finalize page categories in dotcompatterns, ensure the API is returning what we want. @lsl / @deBhal 

This will lead to:

1. Accessibility
2. Unit tests
3. QA (browser, mobile, Atomc et. al.)

**Comment by ramonjd** [comment]
> Move the page picker component code to /packages so we can pull in into the ETK plugin, e.g., import PagePicker from '@automattic/wpcom-page-picker'; 

@roo2 I think you were right to question why we need this. 

It would open up a bunch of possibility for cross-platform experimentation (e.g., showing the picker during onboarding) but if you take a look and judge that it'll take up too much time for our MVP, then maybe we can move it to another iteration. 

"Too much time" I think would be longer than 3 days.

**Comment by roo2** [comment]
I previously did some investigation on moving to the patterns API and wrote up a comment on the p2 pbAok1-1QJ-p2#comment-3898 @lsl @deBhal

**Comment by autumnfjeld** [comment]
FYI: @joanrho and I are working on [user facing acceptance criteria ](https://github.com/Automattic/wp-calypso/issues/49743)that will help keep us on track for a single source of truth of user experience. And bonus, this issue can be linked to for pre-prod release testing criteria.

**Comment by roo2** [comment]
From what I can understand on work required for:
> 3. Check the patterns response, assess if we need to do any work Customize/integrate Pattern API (if necessary). Finalize page categories in dotcompatterns, ensure the API is returning what we want.

It looks to me like the current usage of the API supports what we need pbAok1-1QJ-p2#comment-3946, we just need to align the categories with what joan's suggested in the final design p9Jlb4-27F-p2

**Comment by autumnfjeld** [comment]
Moving this to done, since we've successfully scoped the project. 🎉

**Comment by davipontesblog** [comment]
@autumnfjeld is this one good to be closed now?
