### ISSUE TITLE
WP Admin: Admin color schemes may not update until site cache is cleared

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#49244]
Our customer has a WordPress.com Business plan site with plugins. They reached out to us in Live Chat to ask why, when changing their site's Admin color scheme in the WordPress.com dashboard (in _Account Settings_), they didn't see a corresponding change when loading WP Admin pages.

I did some troubleshooting, and noticed that if I ran `wp cache flush` in WP-CLI, the WP Admin pages then loaded with the correct color scheme.

Deactivating and reactivating the customer's plugins didn't seem to resolve the issue, so a plugin conflict seems to be unlikely. 

The one thing I did notice was that when I deactivated **all** of the customer's plugins, the color scheme switched to the selected color scheme. Beyond that, it seemed to be largely irrelevant which plugins were enabled.

### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/account
2. Select a new _Dashboard color scheme_
3. Switch to the WP Admin dashboard, and refresh the browser tab
4. In most cases, the color scheme in WP Admin doesn't change to reflect the change in _Account Settings_

#### What I expected to happen

Changes to the site's color scheme in _Account Settings_ should reflect in WP Admin pages on a tab reload.

#### What actually happened

In most cases, the WP Admin color scheme was not updated to reflect a change in the WordPress.com dashboard.

### Context

24869778-hc
3674461-zen

#### Browser / OS version

I tested this with Firefox Developer Edition v85.0b9 on macOS 11.1

#### Is this specific to the applied theme? Which one?

The user only has Lodestar installed, so I haven't tested this with other themes.

#### Does this happen on simple or atomic sites or both?

This issue is specific to an Atomic site.

#### Is there any console output or error text?

I captured the following:

- Before cache flush (after changing the color scheme in WordPress.com): https://d.pr/n/i3yVZf/jc6hIwWao7
- After `cache flush`: https://d.pr/n/tlXMdR/6YaT78q4N5

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low impact. This is largely aesthetic, for the most part.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

I didn't capture screenshots for this.

**Comment by obenland** [comment]
Thanks so much for the report! This should be fixed with D56006-code. 

Please feel free to re-open if this happens again in the future.
