### ISSUE TITLE
Domains Picker: update copy after introduction on monthly billed plans

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#49256]
## What

With the introduction of monthly billed plans, copy in the domains picker package needs to be updated to reflect the fact that the free custom domain is only included with annually billed plans.

## Why

We need to update the UI in order to convey the correct information to the user

## A/C

- [x] The corresponding PR should have the `String freeze` label until translations are ready

### Focused Launch

1. On an unlaunched site created through `/start`,  visit `wordpress.com/page/SITE_ID.wordpress.com/home?flags=create/focused-launch-flow`
2. Press "Launch" button, Focused Launch summary view should appear
  - [x] In the Domain step, on a _desktop_ viewport, the green copy next to each domain item should say "First year included in annual plans"
  - [x] In the Domain step, on a _mobile_ viewport, the green copy next to each domain item should say "Included in annual plans"

### Gutenboarding

1. Visit `/new` and navigate to the domain picker
2. The green label to the side of each premium domain should say "First year included in annual plans"
  - [x] In the Domain step, on a _desktop_ viewport, the green copy next to each domain item should say "First year included in annual plans"
  - [x] In the Domain step, on a _mobile_ viewport, only the price is shown

### Step by Step Launch

1. On an unlaunched site created through `/new`,  visit `wordpress.com/page/SITE_ID.wordpress.com/home`
2. Press "Launch" button, Step by Step Launch modal should appear — Navigate to the domain step
2. The green label to the side of each premium domain should say "First year included in annual plans"
  - [ ] In the Domain step, on a _desktop_ viewport, the green copy next to each domain item should say "First year included in annual plans"
  - [x] In the Domain step, on a _mobile_ viewport, only the price is shown

## Context

Screenshots of how domain picker items in the summary view of focused launch look like:

| Desktop | Mobile |
|---|---|
| ![image](https://user-images.githubusercontent.com/1083581/105701865-3eee0f80-5f0b-11eb-83e1-a88960efe2b7.png) | ![image](https://user-images.githubusercontent.com/1083581/105701892-47dee100-5f0b-11eb-998f-d2ef71421a95.png) |

**Comment by ciampo** [comment]
cc @razvanpapadopol @ollierozdarz @paulbonahora any ideas on what the best copy would be?

One possible solution is to use the same text that we're using in Gutenboarding, "Included with annual plans" — this would improve consistency across flows and avoid waiting for translations

**Comment by paulbonahora** [comment]
I would suggest to add the word "annual", meaning: "First year included in annual plans"

**Comment by razvanpapadopol** [comment]
> I would suggest to add the word "annual", meaning: "First year included in annual plans"

I agree and I propose we use this in both site creation and launch flows.

**Comment by ciampo** [comment]
I applied the suggested change in #49290
