### ISSUE TITLE
Focused Launch: summary view always shows annually-billed plans price

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#49257]
#### What I expected to happen

The price in the summary view should update correctly and show the monthly-billed plan's price for the selected plan and the other paid plans listed.

#### Acceptance criteria

* [ ] All plan prices in the summary view are updated when the billing period is toggled.

#### Steps to reproduce the behaviour

1. On an unlaunched site created through `/start`,  visit `wordpress.com/page/SITE_ID.wordpress.com/home?flags=create/focused-launch-flow`
2. Click "Launch" button. Summary view of Focused Launch flow should appear
3. Click on "View all plans", select the "Monthly" option, and take note of the price of each premium plans when billed monthly
4. Select any premium billed plan, you will be automatically taken back to the summary view
5. Note how, in the summary view, the selected plan is still showing the price of its annually-billed counterpart
6. Check that the right product (monthly vs annually billed plan) gets added to the cart

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/1083581/105703618-d0f71780-5f0d-11eb-9408-43c273ef0b81.mp4

**Comment by ciampo** [comment]
cc @razvanpapadopol  and @ollierozdarz  in case you have any input on how to solve this problem best

**Comment by ollierozdarz** [comment]
Hey @ciampo, exposing the toggled price on the summary view feels like the right option to me. I think in the future there's probably more we can do to make it more obvious from the summary screen, but to get this working for the impending launch (of the new Launch flow) it feels like the right choice 🙂

**Comment by ciampo** [comment]
Thank you @ollierozdarz ! We'll go ahead and show the monhtly prices of each plan in the summary view, if the user selected a monthly plan.

**Comment by razvanpapadopol** [comment]
Found some i18n issues. Here is a comparison with reskinned:

### Monthly plans:
* "monthly" translation is not the same
* "annually" is not translated
* "Save xx% by paying anually" is not translated

#### `/new` on live:
<img width="1235" alt="Screenshot 2021-01-27 at 16 40 14" src="https://user-images.githubusercontent.com/14192054/106007625-2cb4d280-60bf-11eb-991c-7d3beec49272.png">
#### `/start` in production:
<img width="1168" alt="Screenshot 2021-01-27 at 16 44 32" src="https://user-images.githubusercontent.com/14192054/106007652-32121d00-60bf-11eb-8e5a-25c30780103d.png">

### Yearly plans:
* _/month_ and _per month_ seems like an unnecessary repetition
* _per month, billed as..._ is not translated

#### `/new` on live :
<img width="738" alt="Screenshot 2021-01-27 at 16 43 44" src="https://user-images.githubusercontent.com/14192054/106007681-39d1c180-60bf-11eb-8e1c-6a98b3146e18.png">

#### `/new` in production:
<img width="1303" alt="Screenshot 2021-01-27 at 16 50 34" src="https://user-images.githubusercontent.com/14192054/106008339-dbf1a980-60bf-11eb-9ec0-db9f6f04d398.png">

#### `/start` in production :
<img width="520" alt="Screenshot 2021-01-27 at 16 48 23" src="https://user-images.githubusercontent.com/14192054/106007966-87e6c500-60bf-11eb-802f-8eb595af5f17.png">
