### ISSUE TITLE
Editor: Subscription Block button text not accurately displayed by default

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#49255]
A customer pointed out that when they added a Subscription Form Block to their site, the default text on the button in the editor was _Subscribe_. When they then viewed the page in preview, or as if they were visiting the page as an ordinary site visitor, the button text was _Follow_.

The workaround for this is to edit the default text in the editor.

### Steps to reproduce the behavior

1. Go to the editor, and add a [Subscription Form Block](https://wordpress.com/support/wordpress-editor/blocks/subscription-form-block/);
2. Notice how the default text on the button is _Subscribe_
3. Preview the page, and see how the button text is _Follow_

#### What I expected to happen

The button text should be the same in the editor, compared to the preview or public-facing version of the post or page.

#### What actually happened

The button texts are different, where the user uses the default button text.

#### Browser / OS version

Tested in Firefox Developer Edition v85.0b9 on macOS 11.1

#### Is this specific to the applied theme? Which one?

Tested in Morden, although reproduced on other Varia, and non-Varia themes (such as Independent Publisher 2)

#### Does this happen on simple or atomic sites or both?

For now, tested on WordPress.com Personal Plan sites.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Potentially affects numerous sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/2912202/105701426-f175a080-5f12-11eb-9d00-dd91561c3955.mp4

**Comment by devNigel** [comment]
Another report: 27772108-hc

I suggested a workaround by adding an empty space after "Subscribe"

**Comment by swoodipto** [comment]
Another report: 27046902-hc

Same as @devNigel - I suggested a workaround by adding an empty space after "Subscribe"

**Comment by kwight** [comment]
This was fixed at some point; the default "Subscribe" text is now shown correctly in the post preview and the front-end once published.
