### ISSUE TITLE
Editor: Embed block - It is not possible to interact with the embedded page

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#49265]
I am not sure whether we can do something about this issue, but I decided to report it anyways as it can come up in the future when users embed external links that include cookie notice.

The user created a new page and pasted there a link to an external page that has a cookie notice. Everything worked correctly, but when the saved page was opened on iOS, the cookie notice was blocking content like this:

![IMG_1CA77640D8D7-1](https://user-images.githubusercontent.com/25105483/105727176-1970fe00-5f2b-11eb-80fd-3b3f7cff6c70.jpeg)

There was no way to accept the cookies.

Everything is working correctly on desktop.

### Steps to reproduce the behavior

1. Open the block editor and paste there a link to a website that has a cookie notice, e.g. [https://uncommongroundmedia.com/domestic-abuse-related-to-late-transitioning-partners-part-i-coercive-control/](https://uncommongroundmedia.com/domestic-abuse-related-to-late-transitioning-partners-part-i-coercive-control/)
2. Save the page and open it on mobile.

#### What I expected to happen

It is possible to tap the button on the cookie notice and see the page content.

#### What actually happened

It is not possible to tap the button on the cookie notice. The cookie notice obstructs the view.

#### Browser / OS version

Tested on iOS 14.3, but the user was also see the issue on iPadOS - not sure which version though. The issue occurred on both mobil Safari and latest mobile Chrome.

#### Is this specific to the applied theme? Which one?

Tested on Dicot, but couldn't try out other themes because of this [other bug](https://github.com/Automattic/wp-calypso/issues/48072)

#### Does this happen on simple or atomic sites or both?

Tested on Simple site, but couldn't try on Atomic because of this [other bug](https://github.com/Automattic/wp-calypso/issues/48072)

#### Is there any console output or error text?

nothing specific observed

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Little impact. It doesn't block purchases. Likely affects multiple sites.

Ticket: 3680381-zd-woothemes

No need to respond to the user. I suggested them link to the external link using the Buttons block.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to reproduce this on both Firefox 94.0a1 using mobile emulation and a physical iPhone 7 device, but was unable to reproduce.

See attached screenshot of emulated mobile device. The physical iPhone also sees the same outcome.

![Screen Shot 2021-10-04 at 4 28 11 PM](https://user-images.githubusercontent.com/6549265/135937780-afae9e6e-122f-4b75-9290-afcc430c4282.png)


If this issue should remain open, please feel free to re-open this bug.
