### ISSUE TITLE
Store|Woo: Update Store deprecation documentation to show old WooCommerce navigation

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49273]
The support documentation for the Store deprecation currently only shows the upcoming/new WooCommerce navigation experience. This is not available to Business customers yet. 

So, the support documentation should include only the existing WooCommerce navigation experience for now.

From pbIJXs-qm-p2#comment-1753:
> Thanks. It will take at least 3-4 weeks until we finish the new navigation improvements and release it in the Business plan, so I think it makes sense to just show the screenshot with the old nav until we release the new one.

**Comment by becdetat** [comment]
Support doc is here: https://wordpress.com/support/new-woocommerce-experience-on-wordpress-dot-com/

Original post has been copied here: https://becdetathome.wpcomstaging.com/2021/02/01/new-woocommerce-experience-on-wordpress-com/

So, when the new WooCommerce nav is live the images will have to be reverted to the original ones showing the new nav - see [Store|Woo: Update Store removal documentation to show the new WooCommerce navigation](https://github.com/automattic/wp-calypso/issues/49432).

**Comment by becdetat** [comment]
This is completed: https://wordpress.com/support/new-woocommerce-experience-on-wordpress-dot-com/
