### ISSUE TITLE
Posts: Inline comments viewer doesn't show proper nesting

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#4928]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/my/SITENAME
2. Click the _comments_ icon for a post with threaded comments more than 2 levels deep

This can also be seen in the Comments view from the Reader

#### What I expected
The comments to be displayed in the correct response order

#### What happened instead
Once the comments reach a depth of 2 or more, they're shown in a single stack sorted by time, making it impossible to tell who is responding to whom.

#### Browser / OS version
OSX Chrome and Firefox tested

#### Screenshot
The comments in this screenshot should all be children of the previous comment
![screen shot 2016-04-21 at 9 52 46 am](https://cloud.githubusercontent.com/assets/7233112/14711665/47b56132-07a8-11e6-8a5d-58ebc2572ab8.png)

**Comment by blowery** [comment]
Already covering this in https://github.com/Automattic/wp-calypso/pull/4817
