### ISSUE TITLE
Launch: layout of the domain upsell step is broken by long domain names

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#49285]
### Steps to reproduce the behavior

1. Create a new site at `/start` using a very long domain name
2. Launch the site from the customer home
3. Proceed through the launch flow to the `domain-upsell` step

#### What I expected to happen
The upsell UI deals sensibly with a long domain name. Perhaps the price gets displayed underneath the domain, like it does on the mobile view?

#### What actually happened
The layout doesn't deal well with long domain names.
<img width="1253" alt="Screenshot 2021-01-26 at 7 44 20 PM" src="https://user-images.githubusercontent.com/1500769/105810478-e48aa700-600f-11eb-91d1-b08448e2a72e.png">

Very long domain names may not be very common. Perhaps a test site might use a long domain name? Or maybe a tongue in check sort of domain name like welcometomyblogwhydontyoucomeonin.com?

#### Browser / OS version

Tested in FF and Edge, had the same issue

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium severity because I can't see the price properly. Low impact because domain names this long won't be very common

**Comment by ollierozdarz** [comment]
👋 I think there are two solutions here that would solve this. Either let the long domain wrap to another line after a max-width or truncate with an ellipsis. Both have pros and cons, and I'm aware this is an edge case, so I'd be keen to try and make the go ahead solution fit with the existing framework as easily as possible 🙂
