### ISSUE TITLE
Gallery Block - Overlapping buttons hiding the move image forward and backward options

### ISSUE THREAD

**Issue by smithkyle45** [Automattic/wp-calypso#49282]
### Steps to reproduce the behavior

1. From `https://wordpress.com/home/`
2. Go to *Site > Pages*, enter any existing page or create a new one
3. Add a Gallery block with a minimum of 8 images
4. Adjust the block to display with 8 columns
5. Click on one of the images and try to reorder it within the set of images

#### What I expected to happen

Expected to see the "Move Image Forward" & "Move Image Backward" options, depicted by the right & left chevron.

It could help to have those options moved outside the bounds of the image or stacked below to improve the editing experience across more devices/screen sizes

#### What actually happened

At normal alignment, even with stretching the browser, those options appear to be overlapping each other. Screenshot attached. It does seem to arrange a bit better using Full Width alignment on the Gallery block.

### Context

First brought to my attention by a user in 26988253-hc.

I suggested a workaround of temporarily setting fewer columns (i.e 2 or 3) while they edit to move the images around more easily with the expected buttons.

#### Browser / OS version

Chrome Version 87.0.4280.141 (Official Build) (x86_64)
mac OS Catalina 10.15.7

#### Does this happen on simple or atomic sites or both?

Tested only on simple site

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1178" alt="Markup 2021-01-25 at 16 23 17" src="https://user-images.githubusercontent.com/45518174/105778959-a23b6a00-5f2a-11eb-93df-ef8b1e18d828.png">

**Comment by Copons** [comment]
Hi! I could repro this on Core Gutenberg as well.
I've opened [an issue on the Gutenberg repo](https://github.com/WordPress/gutenberg/issues/28600), and I'll close this as it should be fixed in Core. 🙂

**Comment by Copons** [comment]
Update: there's a big refactor of the Gallery block in core Gutenberg that might ship soon enough: https://github.com/WordPress/gutenberg/pull/25940

It changes the UI of the block, turning each image into blocks in themselves, and moving all the contextual buttons (move, edit, remove) in their own toolbar.
