### ISSUE TITLE
Jetpack.com - Statistics "Hourly View" image doesn't load

### ISSUE THREAD

**Issue by pyronaur** [Automattic/wp-calypso#49291]
### Steps to reproduce the behavior

1. Go to a site wp-admin
2. See error:

Looks like this might be happening because the image can't be loaded here:

```html
<div class="wp-menu-name">Statistics<img class="sidebar-unified__sparkline" src="http://site.com/wp-includes/charts/admin-bar-hours-scale-2x.php?masterbar=1&amp;s=20115252" alt="Hourly views" width="80" height="20"></div>
```

Browser: Firefox 84.0.2

**Comment by getdave** [comment]
<img width="568" alt="Screen Shot 2021-01-27 at 14 26 35" src="https://user-images.githubusercontent.com/444434/106005029-b65aa500-60ab-11eb-9a12-32226fa33e8a.png">

I'm not seeing that. @Automattic/ajax can anyone else replicate this?

**Comment by pyronaur** [comment]
I wonder if this was cache related. I'm no longer able to reproduce this myself.
