### ISSUE TITLE
Ability to see CSS revisions

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#49292]
### Steps to reproduce the behavior

1. On a site which has the Premium Plan head over to Appearance > Customizer
2. Open "Additional CSS" panel. _If this is your first time adding CSS here you will need to add some, save and refresh to enable the "CSS Revisions"._
3. Click "CSS Revisions" above the CSS editor
4. See new tab open with a "The page requested does not exist" error.

**Video**: [https://d.pr/v/AUNvtC](https://d.pr/v/AUNvtC)
**Context**: 280a5-pb/#bash

**CSS revisions link:**
![page-link](https://user-images.githubusercontent.com/8639742/105837635-e419ee00-5fc6-11eb-9c23-f1b4c47ff517.png)

**CSS revisions page error:**
![page-error](https://user-images.githubusercontent.com/8639742/105837682-f3993700-5fc6-11eb-91e5-a6e647329257.png)

#### What I expected to happen

* To be taken to see my CSS revision history

#### What actually happened

* A new tab opened with a "The page requested does not exist" error.

**Comment by tjcafferkey** [comment]
@Automattic/ajax any ideas on this? Here's what I (think I) know so far...

* It works on the non-unified nav accounts for premium websites (non a8c accounts)
* `editcss` is not getting added as a sub menu page to `$_registered_pages`
* I am guessing [this method](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/custom-css/custom-css.php#L902-L909) is responsible for this getting added or not which gets executed [here](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/custom-css/custom-css.php#L109)? But for some reason, perhaps isn't?

I am not familiar enough with this codebase yet, or the project to be able to pin down the cause so any help pointing me in the right direction would be appreciated 😄

**Comment by mmtr** [comment]
@tjcafferkey You're in the right direction! I'd say that the `editcss` page is likely registered correctly via the methods you found and then removed [here](https://github.com/Automattic/jetpack/blob/53b06df61656b306931cec6e3ded2a64c4234831/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L369) when customizing the Appearance menu entries when the Nav Unification is enabled.

**Comment by cpapazoglou** [comment]
Since this is a high priority for HEs, lets try to:

- either create a cherry pick commit for Jetpack 9.4
- or create the Jetpack commit that will be merged in 9.5 and deploy a wpcomsh hotfix

**Comment by mmtr** [comment]
cc @jeherve for awareness that we may need to include a fix for this on Jetpack 9.4

**Comment by susanjanec** [comment]
When viewing this option "Edit CSS Revisions" on a Simple site for a user, they were not able to access the revisions and got the CSS revisions page error as described above. The user is on a Premium plan. Can someone confirm if the revisions are no longer available due to the nav unification, which they have applied on their site?

**Comment by kosiew** [comment]
Reopening issue.

#3838243-zen

getting The page requested does not exist
at wp-admin/themes.php?page=editcss

**Comment by mmtr** [comment]
Thanks for reopening. It's been likely reintroduced by https://github.com/Automattic/jetpack/pull/19114.

**Comment by mmtr** [comment]
Fix ready for review/testing: D59229-code

**Comment by mmtr** [comment]
Fixed in r223260-wpcom.
