### ISSUE TITLE
Nav Unification: Portfolio Project types/tags highlights wrong menu item

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#49309]
### Steps to reproduce the behavior

1. Click Portfolio root item
2. Click Project types or Project tags
3. See how highlighted menu item switches to Posts

#### What I expected to happen
Portfolio would remain highlighted

#### What actually happened
Posts menu section was highlighted

<img width="1018" alt="1" src="https://user-images.githubusercontent.com/47717887/108841249-24798580-75e0-11eb-9a86-57e929695581.png">

**Comment by supernovia** [comment]
We spotted this too in a team testing session. After this bug, clicking Portfolio takes us to a Calypso page.

I see this on MacOS / Chrome, both current, btw.
