### ISSUE TITLE
Nav Unification: Comments panel not displaying when account is set to Spanish

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#49316]
### Steps to reproduce the behavior

1. Start from a Simple Site.
2. Go to Account Settings and change interface language to Spanish
3. Go back to site dashboard
4. "Comentarios" label not displaying.  

#### What I expected to happen

<img width="378" alt="Markup 2021-01-26 at 11 37 50" src="https://user-images.githubusercontent.com/24919469/105882174-f72ebd00-5fca-11eb-8e53-4b0a81dd6fdb.png">

#### What actually happened

<img width="343" alt="Markup 2021-01-26 at 11 38 32" src="https://user-images.githubusercontent.com/24919469/105882245-0ca3e700-5fcb-11eb-9e3e-6bea4ecb26b7.png">

#### Does this happen on simple or atomic sites or both?

Only on Simple sites.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Seems to affect all accounts that are set to Spanish. I tested other languages (not all of them) and can only reproduce it with Spanish interface.

**Comment by obenland** [comment]
It looks like the pending comments bubble is preceding the menu item title, contrary to how it's set up in English or other languages.

This should fix it in `WPCOM_REST_API_V2_Endpoint_Admin_Menu::parse_update_count()`
```php
// Remove count badge HTML from title.
if ( 0 === strpos( $title, '<' ) ) {
	$item['title'] = trim( substr( $title, strrpos( $title, '>' ) + 1 ) );
} else {
	$item['title'] = trim( substr( $title, 0, strpos( $title, '<' ) ) );
}
```

**Comment by ramonjd** [comment]
I just noticed this bug too ¡Dios mio! It also affects [Romanian](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/ro/default/?filters[term]=Comments+%25s&filters[term_scope]=scope_any&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&filters[user_login]=&filter=Apply+Filters&sort[by]=priority&sort[how]=desc).

It will affect all translations that have the string marker as the first item, e.g., `%s commentarios`

The [suggested fix](https://github.com/Automattic/wp-calypso/issues/49316#issuecomment-768627241) work for Spanish and Romanian but we might need to capitalize the text. 

<img width="447" alt="Screen Shot 2021-02-08 at 2 45 16 pm" src="https://user-images.githubusercontent.com/6458278/107174057-666dcd80-6a1d-11eb-8f90-03317510cb3c.png">

Maybe by adding `text-transform: capitalize;` to [.sidebar__menu-link-text.](https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/client/layout/sidebar/style.scss#L189) Maybe not a bullet-proof suggestion, sorry.

A radical alternative might be to update the translations to `Commentarios: %s`

This is what other romance languages such as [Italian](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/it/default/?filters[term]=Comments+%25s&filters[term_scope]=scope_any&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&filters[user_login]=&filter=Apply+Filters&sort[by]=priority&sort[how]=desc) and [Portuguese](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/pt-br/default/?filters[term]=Comments+%25s&filters[term_scope]=scope_any&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&filters[user_login]=&filter=Apply+Filters&sort[by]=priority&sort[how]=desc) are doing, along with all the other languages I checked e.g., Russian, German Arabic.

**Comment by getdave** [comment]
This should now be fixed.

**Comment by cpapazoglou** [comment]
Related issue https://github.com/Automattic/wp-calypso/issues/50373
