### ISSUE TITLE
Themes: Blank Canvas theme should not show page-layout modal when switching themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49317]
### Steps to reproduce the behavior

1. Navigate to Themes in Calypso
2. Click activate button for Blank Canvas theme to initiate theme switch
3. Note the dialog screenshotted below. It shouldn't appear with this theme.

![image](https://user-images.githubusercontent.com/545779/105883137-1c6ffb00-5fcc-11eb-8fff-0d1fb85ac71e.png)

#### What I expected to happen

As Blank Canvas does not have any special layout settings or homepage content I expected it would not have a radio-button dialog like this. WP.com would instead proceed with the theme switch much like it does with a theme like Twenty Nineteen …

![image](https://user-images.githubusercontent.com/545779/105883350-5e993c80-5fcc-11eb-88b5-feb4e68dd123.png)

**Comment by simison** [comment]
Guestimate on requirements:

• register a new recommended term
• update calypso to use that term for listing recommended themes
• and keep the auto-loading homepage term for doing the job of telling calypso “this theme can just add a homepage” (for now)

via slack-dotcom-create-p1611683693057900

**Comment by Addison-Stavlo** [comment]
For clarification, should activating the "Blank Layout" theme make your homepage content blank?  Or not change the content?

Based on the behavior of the other recommended themes it is not clear to me which of the above should take place, so I would assume users may have the same confusion in which case the radio button modal might make sense? 🤔

**Comment by cathymcbride** [comment]
@ianstewart Can you address this? ☝️

**Comment by Addison-Stavlo** [comment]
> @ianstewart Can you address this? ☝️

We discussed in slack it may be worth trying to get the second radio button option working with the replace content flow as opposed to removing the modal.  D56920-code

**Comment by Addison-Stavlo** [comment]
While the above noted diff is merged, it seems we will also need D57032-code for that option to work as expected.

**Comment by Addison-Stavlo** [comment]
Required annotations and tags have been added for this theme to works as expected with both modal options.  Closing this issue.
