### ISSUE TITLE
Notice text goes missing once menu is collapsed

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#49314]
Sites with a custom domain have a notice that nudges the user to register another URL:

<img width="296" alt="Captura de Tela 2021-01-26 às 13 57 49" src="https://user-images.githubusercontent.com/1136160/105879286-bcd01a80-5fe0-11eb-8b6e-efe7227e1bce.png">

That nudge, however, disappears when the menu is collapsed.

### Steps to reproduce the behavior

1. Select a site with at least one custom domain
2. Check the `Add another domain` message
3. Hit **Collapse Menu**

#### What I expected to happen
One of the following:

1. That white box/background to disappear; _or_
2. To have an icon that can be hovered and let me read the content (`Add another domain`) and interact with it

For example, an exclamation point is available when I access a site with the `Free Domain available` nudge:

<img width="180" alt="Captura de Tela 2021-01-26 às 14 06 30" src="https://user-images.githubusercontent.com/1136160/105878387-c1e09a00-5fdf-11eb-8d53-1cf6895e3d54.png">

#### What actually happened
The text is gone leaving only a white box.
<img width="243" alt="Captura de Tela 2021-01-26 às 13 56 58" src="https://user-images.githubusercontent.com/1136160/105878057-60b8c680-5fdf-11eb-9e67-137cadbb8291.png">

#### Does this happen on simple or atomic sites or both?
Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor but users may miss important nudges.

**Comment by getdave** [comment]
This is actually expected behaviour. Appreciate you reporting.

**Comment by mmtr** [comment]
> The text is gone leaving only a white box.

Reopening, since this seems like a regression to me

**Comment by getdave** [comment]
Agreed. My bad. Needs a fix.

**Comment by cpapazoglou** [comment]
It seems that we have to account for more _notice_ cases here https://github.com/Automattic/wp-calypso/blob/cfd3f652ee71a35bd5b2bdffdc7bdb18e8e53038/client/my-sites/sidebar-unified/style.scss#L378
