### ISSUE TITLE
New onboarding: Long titles displace nav bar elements at some breakpoints

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#49328]
Similar problem to what we saw with #49061, this time I find long titles are able to squash the domain picker to an empty strange looking block and the "Site Language" text gets messed up (worse for Japanese with no space between words)

Fix likely needs to hide a portion of a long title and to hide it completely when there is not enough room (earlier than the mobile view where this currently happens)

### Steps to reproduce the behavior

1. Go to wordpress.com/new with a small browser window
2. Enter a long title
3. Select a domain
4. See the header elements become squashed or pushed off the page entirely depending on the screen size you're working with

#### Screenshot / Video:
![Screenshot(19)](https://user-images.githubusercontent.com/811776/105931771-eac86400-609f-11eb-8962-0d9e34125ec1.png)
![Screenshot(18)](https://user-images.githubusercontent.com/811776/105931778-ec922780-609f-11eb-969c-d4e72cc90b3b.png)

**Comment by ollierozdarz** [comment]
I think it wouldn't be unreasonable for us to truncate this, say with an ellipsis, at a certain width that makes sense.
