### ISSUE TITLE
Gutenberg: Poor block rendering in Chrome and Firefox

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#49332]
Our customer reported that their site's Home page is not rendering correctly when they view the public-facing version of the page. By contrast, the editor view looks as they'd expect it.

I loaded the Home page on Firefox, Chrome, and Safari, and only Safari seemed to render the page correctly. Both Firefox and Chrome rendered the page poorly, and I wasn't able to determine why.

### Steps to reproduce the behavior

1. Go to https://craigreidediting.com in Chrome, Firefox, and Safari
2. Scroll down the page to see anomalies in how the page renders in Chrome and Firefox.

[Here is a video demonstrating what I see on my side](https://drive.google.com/file/d/1932ZK6_kbcVyQdM70dtkhOz3TkWc7mHT/view?usp=sharing).

#### What I expected to happen

Blocks should render the same way in each browser, and should render accurately based on the configuration in the block editor.

#### What actually happened

As you can see from my video above, there are clear differences in how each browser renders the page.

### Context

3683190-zen

#### Browser / OS version

Tested using the following on macOS 11.1:

- Safari v14.0.2
- Firefox v85.0
- Chrome v88.0.4324.96

The block editor is on the following versions:

- Gutenberg: v9.7.4
- CoBlocks: 2.5.3
- Editing Toolkit: 502493847

#### Is this specific to the applied theme? Which one?

I tested, and reproduced the issue on various themes including Alves (the customer's site's theme), Twenty Twenty One, Spearhead, and Blank Canvas.

Here is a copy of the page code: https://d.pr/n/VOx67b/RXqhQaGoO1

#### Does this happen on simple or atomic sites or both?

This site has a WordPress.com Personal Plan

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Unclear.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

In addition to the video above, here are two specific issues in Firefox and Chrome:

<img width="1404" alt="Markup 2021-01-27 at 10 06 31" src="https://user-images.githubusercontent.com/2912202/105963871-2fe19b80-608a-11eb-8489-9ab2156ea15d.png">

<img width="1334" alt="Markup 2021-01-27 at 10 07 02" src="https://user-images.githubusercontent.com/2912202/105963898-36701300-608a-11eb-86d6-eafd655a8426.png">

**Comment by cathymcbride** [comment]
@pauljacobson are there repro steps you used to recreate this on the other themes? If so, it would be great if you could add those.

**Comment by pauljacobson** [comment]
Hi there @cathymcbride I tested with other themes using the _Try & Customize_ option in _Design_ > _Themes_ in the user's dashboard. I didn't switch to the new themes entirely, as I didn't want to disrupt their site with a series of rapid theme changes.

**Comment by Robertght** [comment]
I have retested this now nd I can't replicate it using the same content. Also the theme on the user's site appears to be different now.

I'm marking this as solved as I think it's an edge case, but someone encounters similar situations, please re-open it.
