### ISSUE TITLE
Premium Content Block: VideoPress videos in Premium Content block shows "This block contains unexpected or invalid content" error

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#49337]
Videos hosted on VideoPress that are placed inside the Subscriber View in the Premium Content block shows this error:

`This block contains unexpected or invalid content`

Pressing "Attempt Block Recovery" gets the video to show up, but upon the refreshing the editor, the error shows up again.

### Steps to reproduce the behavior
1. Upload video on site with Premium Plan or higher, making sure it uploads to VideoPress
2. Create page
3. Insert Premium Content block
4. Embed VideoPress video
5. Publish page
6. Refresh editor

#### What I expected to happen

For the videos to show up

#### What actually happened

The video blocks show a `This block contains unexpected or invalid content` error.  Videos not placed inside the Premium Content block are not affected.  On Atomic, videos uploaded directly to the server via wp-admin > Media > Add New are not affected.

#### Browser / OS version

Tested in Chrome and Firefox

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects my test sites (Atomic and Simple) and the Atomic site of the user who reported it.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screencast: https://d.pr/v/Gy3zlh

In the screencast, I am adding the same video inside the Visitor and Subscriber views in a Premium Content block, as well as outside that block.

After saving the page and refreshing, the video shows the `This block contains unexpected or invalid content` error in both views in the block, while the video outside the block looks ok.

**Comment by worldomonation** [comment]
I wonder if my issue #49375 is related; that one is with Subscription Block on Leven theme.

**Comment by stacimc** [comment]
I'm unable to reproduce this. Would you mind re-testing this @druesome and letting me know if you can still see it? I'm wondering if the issue was resolved when the Premium Content block was moved from ETK to Jetpack.
