### ISSUE TITLE
Plugins: Update plugins button does not disappear after updating

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#49340]
### Steps to reproduce the behavior

Get a connected Jetpack site with one or several outdated plugins.

1. Go to `/plugins/manage/:site`
2. Click on `Update x plugin(s)` (top right)

#### What I expected to happen

The `Update plugins` button should disappear.

#### What actually happened

The `Update plugins` button doesn't disappear.

### Context

This is probably related to the recent plugin reduxification efforts /cc @tyxla 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/9202899/105985561-e69a4780-609b-11eb-8966-53b2c7ecad73.mp4

**Comment by tyxla** [comment]
Great find @flootr! Seems like this is a bug in our `getPlugins` selector. Fix incoming.

**Comment by tyxla** [comment]
Fix: #49342
