### ISSUE TITLE
Nav Unification: the Jetpack > Search page is missing from the sidebar

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#49345]
### Steps to reproduce the behavior

1. Go to any site
2. Hover or click on "Jetpack"

#### What I expected to happen

Our landing page for Jetpack Search should be there. https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/jetpack-search

#### What actually happened

<img width="456" alt="Screen Shot 2021-01-27 at 8 50 49 AM" src="https://user-images.githubusercontent.com/820871/106016939-31589700-607d-11eb-8f3c-1d216b6758ea.png">

**Comment by jsnmoon** [comment]
It's even worse for me on my Jetpack site:

<img width="267" alt="Screen Shot 2021-01-28 at 2 25 27 PM" src="https://user-images.githubusercontent.com/4044428/106200743-b07cc680-6174-11eb-85d1-0671bca47287.png">

The `Jetpack` menu item is missing entirely.

**Comment by getdave** [comment]
Thanks so much for reporting this. Thankfully this is a known Issue and will be resolved. Please see p1HpG7-b2s-p2
