### ISSUE TITLE
"My home" overflows to a site without a title

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/wp-calypso#49355]
### Steps to reproduce the behavior

1. Go to a private site you have. 
2. Click on "Links" or "Feedback" , "Private" changes, "Redirect" option appears, another broken link of "Hourly views" pops up (see below images)
3. Click on any other navigation item in the sidebar, that should look normal.

It seems that the "Links" & "Feedback" have some problems. As both are WP-Admin links, I guess they are not unified in that sense, using another color scheme like black and white (Classic Bright), clicking on these two menu nav items changed the black background into white.  With the blue backgroud this did not happen as you can see. 

#### Browser / OS version
Chrome Version 87.0.4280.141 / macOS Big Sur Version 11.1

#### Does this happen on simple or atomic sites or both?
Two Simple sites (Premium and Free)

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="367" alt="Screenshot 2021-01-27 at 20 45 56" src="https://user-images.githubusercontent.com/71094068/106042003-318c7d00-60e5-11eb-9ea2-9434bcda7e37.png">
<img width="480" alt="Screenshot 2021-01-27 at 20 46 44" src="https://user-images.githubusercontent.com/71094068/106042247-76181880-60e5-11eb-92c1-7456f8c98a97.png">
<img width="546" alt="Screenshot 2021-01-27 at 20 46 18" src="https://user-images.githubusercontent.com/71094068/106042262-7b756300-60e5-11eb-9c42-39332fc77002.png">

<img width="466" alt="Screenshot 2021-01-27 at 20 54 35" src="https://user-images.githubusercontent.com/71094068/106042036-3cdfa880-60e5-11eb-945a-ce4e52781a6e.png">
<img width="594" alt="Screenshot 2021-01-27 at 20 53 39" src="https://user-images.githubusercontent.com/71094068/106042049-3fda9900-60e5-11eb-963d-6ac0ea2995ea.png">
<img width="529" alt="Screenshot 2021-01-27 at 20 53 59" src="https://user-images.githubusercontent.com/71094068/106042073-436e2000-60e5-11eb-825b-f62626e63526.png">

<img width="693" alt="Screenshot 2021-01-27 at 21 16 36" src="https://user-images.githubusercontent.com/71094068/106042092-46691080-60e5-11eb-9da5-c7ae9250604a.png">
<img width="494" alt="Screenshot 2021-01-27 at 21 16 54" src="https://user-images.githubusercontent.com/71094068/106042102-48cb6a80-60e5-11eb-8270-c3e86972ebad.png">

**Comment by cpapazoglou** [comment]
Thanks for reporting!

I will leave some notes:

For 
![image](https://user-images.githubusercontent.com/12430020/107024552-dcb9c800-67b0-11eb-924c-231a5bb38d23.png)
we should add a `min-height` to `.site__title` in WPAdmin.

The color-scheme issue should be now fixed, can you check again @Sandkorner?

For Hourly Views `/wp-includes/charts/admin-bar-hours-scale-2x.php` gets a 403 error.

**Comment by Sandkorner** [comment]
Both of these issues seem to be fixed as much as I can see on my end. Well done!

**Comment by cpapazoglou** [comment]
The "Hourly views" is fixed by now.

Regarding My Home overflowing, lets show the `domain` as the Site Title when the latter doesn't exist.
![](https://cln.sh/rgp7rI+)
