### ISSUE TITLE
Site Editor: Beta tab displays HTML in Calypso sidebar

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49350]
### Steps to reproduce the behavior

1. [Create a site on Horizon with the Site Editor](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor)
2. Navigate to Calypso
3. See error in bottom left of the screenshot below

![image](https://user-images.githubusercontent.com/545779/106028965-370ca780-6092-11eb-9716-3fe4fc0cd275.png)

**Comment by obenland** [comment]
Let's add a case to [`parse_update_count()`](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L332) that strips HMTL tags if the title begins with one or truncates the title before the first HTML tag to remove any unexpected badges.

**Comment by getdave** [comment]
@Automattic/ajax This is blocking internal testing of the Site Editor for a12s. We need to try and resolve it if we can.

**Comment by mmtr** [comment]
Reopening to denote that the fix for JP/AT sites depends on the next Jetpack 9.4.1 release

**Comment by mmtr** [comment]
Jetpack 9.4.1 just came out, so we can close this issue now.
