### ISSUE TITLE
Subscription Block: this block contains unexpected or invalid content

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49375]
### Steps to reproduce the behavior

1. Initiate Gutenboarding with any name and domain.
2. Choose `Leven` theme.
3. Wait until site is created.
4. Edit Home Page
5. Scroll down to the `Subscribe to Our Newsletter` section.

#### What I expected to happen
Block does not show error.

#### What actually happened
Block shows error message: 
`This block contains unexpected or invalid content.`

In the console:
```
Uncaught (in promise) Error: Failed to load script "//stats.wp.com/w2.js?1"
```

Subscription Block > Meatball Menu > Resolve:

```
Current
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline wp-block-jetpack-subscriptions__use-newline">[jetpack_subscription_form subscribe_placeholder="Email Address" show_subscribers_total="false" button_on_newline="true" submit_button_text="Subscribe" custom_font_size="16" custom_border_radius="0" custom_border_weight="1" custom_padding="15" custom_spacing="10" submit_button_classes="has-text-color has-background-color has-background has-primary-background-color" email_field_classes="" show_only_email_and_button="true"]</div>
[jetpack_subscription_form show_subscribers_total="false" button_on_newline="true" custom_font_size="16" custom_border_radius="0" custom_border_weight="1" custom_padding="15" custom_spacing="10" submit_button_classes="has-text-color has-background-color has-background has-primary-background-color" email_field_classes="" show_only_email_and_button="true"]
After Conversion
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline wp-block-jetpack-subscriptions__use-newline">[jetpack_subscription_form subscribe_placeholder="Email Address" show_subscribers_total="false" button_on_newline="true" submit_button_text="Subscribe" custom_font_size="16" custom_border_radius="0" custom_border_weight="1" custom_padding="15" custom_spacing="10" submit_button_classes="has-text-color has-background-color has-background has-primary-background-color" email_field_classes="" show_only_email_and_button="true"]</div>
[jetpack_subscription_form subscribe_placeholder="Email Address" show_subscribers_total="false" button_on_newline="true" submit_button_text="Subscribe" custom_font_size="16" custom_border_radius="0" custom_border_weight="1" custom_padding="15" custom_spacing="10" submit_button_classes="has-text-color has-background-color has-background has-primary-background-color" email_field_classes="" show_only_email_and_button="true"]
```

### Notes
Block is recovered and displays as expected in the block editor once `Recover block` is clicked.

### Context
User scenario manual testing.

#### Browser / OS version
Browser: Firefox Nightly 86.0a1
OS: macOS Catalina 10.15.7

#### Is this specific to the applied theme? Which one?
Leven
Seems to be only reproducible with 

#### Does this happen on simple or atomic sites or both?
Both Simple and Atomic.

#### Is there any console output or error text?
Unsure.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - is an irritant.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-01-27 at 13 37 40](https://user-images.githubusercontent.com/6549265/106074267-6a662b00-60c0-11eb-8b76-ee85840f338c.png)

**Comment by cathymcbride** [comment]
@worldomonation does the block recover if you click "Attempt Block Recovery"?

**Comment by worldomonation** [comment]
> @worldomonation does the block recover if you click "Attempt Block Recovery"?

Yes, it does - I will add that in the original report as clarification.

**Comment by cathymcbride** [comment]
Thanks! Still not a great experience tho.

**Comment by obenland** [comment]
@ianstewart Where did we leave off on the issue of outdated blocks in page templates? Is that something View could look at?

**Comment by ianstewart** [comment]
View + Create. I've updated the source site for this here but we'll need a deploy to update wp.com/new so I'll move this to the Create Maintenance board for now as they've been helping out with that.

cc @simison and @apeatling as we've been talking about using our Patterns Toolkit to the deploys here a bit more and for automated updates to the source site for when blocks get outdated.

**Comment by simison** [comment]
@ianstewart assuming there's been a deployment since and safe to close? Feel free to re-open if not :-)
