### ISSUE TITLE
Nav Unification: "Me" menu items do not change color after being selected

### ISSUE THREAD

**Issue by deancroyal** [Automattic/wp-calypso#49379]
### Steps to reproduce the behavior

1. Go to My Profile. (wordpress.com/me)
2. Click on Account Settings (or any other menu item within /me).

#### What I expected to happen
After clicking the menu item, I expected to see the menu item change to blue (matching /home menu item behavior).

#### What actually happened
After clicking the menu item, it remained black, exactly like the hover state.

#### Browser / OS version
Google Chrome Version 87.0.4280.141 (Official Build) (x86_64) / Mac OS Big Sur Version 11.1 (20C69)

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img src="https://user-images.githubusercontent.com/13387217/105538165-dc490980-5ca7-11eb-91ca-112332a1422c.gif" width="225">

**Comment by frontdevde** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/49408
