### ISSUE TITLE
Nav Unification: page load auto-scroll issue after menu item selection

### ISSUE THREAD

**Issue by deancroyal** [Automattic/wp-calypso#49381]
### Steps to reproduce the behavior

1. Go to 'My Home' (wordpress.com/home)
2. Scroll to the bottom of the My Home page.
2. Click on 'Stats' within the menu (wordpress.com/stats/day)
3. Stats page loads, but scrolled to the bottom; does not auto-scroll to the top.

#### What I expected to happen
I expected the Stats page to load and auto-scroll to the top. 

#### What actually happened
The Stats page loaded at the bottom and does not auto-scroll to the top.

#### Browser / OS version
Google Chrome Version 87.0.4280.141 (Official Build) (x86_64) / Mac OS Big Sur Version 11.1 (20C69)

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Capture on 2021-01-27 at 19-20-23](https://user-images.githubusercontent.com/13387217/106085330-d488cb00-60d4-11eb-9ba9-0ec8020047d5.gif)

**Comment by obenland** [comment]
Let's consolidate with #49577
