### ISSUE TITLE
Block Types missing from state

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#49396]
### Steps to reproduce the behavior

1. Go to `https://wordpress.com/post/[DOMAIN]`
2. Click on the 3-dot menu on the top-right
3. Click "Manage Reusable Menus"

#### What I expected to happen
Be able to manage the reusable blocks
![](https://cln.sh/H1EnHZ+)

#### What actually happened
I got to `/types/wp_block/[DOMAIN]`
```
Content type unsupported
Your site does not support this content type
You need permission to manage this post type
Ask your site administrator to grant you access
```

![image](https://user-images.githubusercontent.com/12430020/106129654-1fecb900-6169-11eb-8f6b-3bae4e740efc.png)

prop: @gamebits

**Comment by cpapazoglou** [comment]
The problem relies to the fact that the old sidebar component did a query to get the custom post types

https://github.com/Automattic/wp-calypso/blob/ea53396172e91112a35d1a90255adb58be4c432b/client/my-sites/sidebar/site-menu.jsx#L269

which we are not doing now. 

Adding `<QueryPostTypes siteId={ siteId } />` to https://github.com/Automattic/wp-calypso/blob/dac30586cd5253c2bf463635e869a364e24bcdcc/client/my-sites/types/main.jsx#L27-L90 seems enough since `isPostTypeSupported` is used only there.

But we should double check though, if the sidebar component we no longer use https://github.com/Automattic/wp-calypso/blob/ea53396172e91112a35d1a90255adb58be4c432b/client/my-sites/sidebar/site-menu.jsx#L269

does any other calls to populate the state.

**Comment by getdave** [comment]
Good catch @cpapazoglou.

**Comment by obenland** [comment]
Is this related to Nav Unification? 

Something similar was also reported in https://github.com/Automattic/wp-calypso/issues/49634 where I tried to do some debugging.

**Comment by cpapazoglou** [comment]
> Is this related to Nav Unification?
> 
> Something similar was also reported in #49634 where I tried to do some debugging.

Definitely

> The problem relies to the fact that the **old sidebar component** did a query to get the custom post types
