### ISSUE TITLE
Quickstart sessions: Add dynamic countdown for the upcoming session

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#49394]
Adding a dynamic countdown to our dashboard when a customer has booked a Quickstart session could help to reduce the no-show ratio that happens due to timezone/booking mistakes, by showing exactly how many hours/minutes are left till the session starts.

At the moment the timezone description we're showing is very verbose, and while specific, it can still lead to confusion.

**Why?**
To reduce the QuickStart no-shows due to timezone mistakes.

**How?**
This is an example screenshot from Italki's dashboard ( an online language learning platform that also deals with session scheduling), with a real time countdown that easily shows when is the next session starting:
<img width="634" alt="Screenshot 2021-01-28 at 10 02 35" src="https://user-images.githubusercontent.com/3812076/106115073-a2b54a00-6150-11eb-8383-93ba5a330c3f.png">

In our end, adding an extra line anywhere attached to the current timezone description could be very helpful. This screen can be found under WordPress.com > Site > Plans > My Plan > Quickstart Session > Schedule a Session:

<img width="861" alt="Screenshot 2021-01-28 at 10 05 55" src="https://user-images.githubusercontent.com/3812076/106115770-66ceb480-6151-11eb-9128-3043b173f5e5.png">

As an extra bonus, it feels that 6 clicks in order to see the session is a bit too much. This notification could be added as well to the main Plans screen at WordPress.com > Site > My Home at https://wordpress.com/home/ for quicker access.

**Comment by jee1mr** [comment]
Hi, @iamgabrielma. I would like to work on this. However, I am not able to find the "plans" section on my site. Is it a plugin/premium feature? How do I reproduce this?

**Comment by iamgabrielma** [comment]
> I am not able to find the "plans" section on my site. Is it a plugin/premium feature? How do I reproduce this?

You'll find this in WordPress.com sites by going to the URL http://wordpress.com/ > My Sites > $SITE, not on self-hosted ones.

**Comment by iamgabrielma** [comment]
Removing `[Status] Stale`, this is still a valid enhancement request.

**Comment by davipontesblog** [comment]
Closing as this is no longer offered.
