### ISSUE TITLE
Editor: Link to existing content includes results for non-public post types

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#4940]
Edit by @marekhrabe: issue is **fixed** for dotcom sites, JP support coming soon!

---

**Steps to reproduce:**
1. Ensure at least one published "Feedback" exists, which can be managed from WP-Admin under Feedback > Feedback
2. Navigate to the [post editor](https://wordpress.com/post)
3. Select a site, if prompted
4. Click Add Link from the editor toolbar

**Expected result:**

Feedback should not be included in results since the post type is not public.

**Actual result:**

Feedback results are included.

**Suspected cause:**

The WP-Admin editor only [queries link results for post types which are registered as public](https://github.com/WordPress/WordPress/blob/a58ec423da502c779e37ed0e3b944f2a765a385c/wp-includes/class-wp-editor.php#L1317). The Calypso editor link dialog [queries for any post type](https://github.com/Automattic/wp-calypso/blob/912b3c3d3668aa82ac3a5eecf4c1c6412ef65fb2/client/components/tinymce/plugins/wplink/dialog.jsx#L343).

Further, this will likely require additional functionality from the REST API to either (a) allow querying a list of posts for public post types or (b) allow querying a list of posts for a comma-separated list of types. Currently you can only specify a single `type` or `any` from the `GET /sites/%s/posts` endpoint. If we change this to accept a comma-separated list of types, we'll need to enhance the editor to first retrieve public post types before displaying the selector results.

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided:

![screen shot 2016-07-20 at wed jul 20 3 04 05 pm](https://cloud.githubusercontent.com/assets/1119271/17003121/ba56398a-4e8b-11e6-8fb0-2c71b9e1e15e.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/edit.php?post_type=feedback using Safari 9.1.1 on Mac OS X 10.11.5</sup>

![screen shot 2016-07-20 at wed jul 20 3 03 57 pm](https://cloud.githubusercontent.com/assets/1119271/17003128/c1e38bd0-4e8b-11e6-943f-4d459759b325.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com using Safari 9.1.1 on Mac OS X 10.11.5</sup>

**Comment by lancewillett** [comment]
This looks still valid — changing the query from "any" to only "public" post types should be a simple change, right?

**Comment by aduth** [comment]
@lancewillett : REST API support does not exist for querying public types. Also not something that can be achieved by outside contributors (except by Jetpack -> WordPress.com sync).

**Comment by alisterscott** [comment]
Removing the Good First Change label since this actually requires a change to the REST API to remove posts of type 'feedback' from returning when posts are queried (or a way to only return posts||pages but not feedback)

**Comment by carinapilar** [comment]
Had an user complaining about this: #2997984-t

He has lots of feedbacks, then that's what he sees when trying to add a link:

![screen shot 2017-01-10 at 14 38 17](https://cloud.githubusercontent.com/assets/16104522/21844905/9ea3be58-d7d7-11e6-8ec0-d9f0ba11581f.png)

**Comment by fditrapani** [comment]
Any updates on this issue? I have another customer asking about it in #2813042

**Comment by alexjgustafson** [comment]
138461-chat

**Comment by ehti** [comment]
Another issue/report in #44037-hc

**Comment by lancewillett** [comment]
As a related improvement, might also be worth a look at a toggle to show and hide the "Link to existing content" menu, as it can get long sometimes.

**Comment by lancewillett** [comment]
>  toggle to show and hide
Cancel that — I've tried it more, and the view does scroll once the list gets longer.

**Comment by nunyvega** [comment]
Same error on #3093955-t
I was able to replicate it, and since the user has a lot of feedback, it is pretty notorious.

**Comment by marekhrabe** [comment]
I'm able to easily confirm this and I'll be working on fix in #11887

**Comment by gracie** [comment]
+1 on #3140762-t with some SPAM comments: 
![screen shot 2017-04-04 at 12 35 09 pm](https://cloud.githubusercontent.com/assets/21203710/24667964/2c1b0fa6-1933-11e7-8a66-74507b61a8bb.png)

**Comment by alexjgustafson** [comment]
User report in 334463-hc

**Comment by marekhrabe** [comment]
This is now live in production for all dotcom sites. Jetpack support will be coming later (reopening because of that). It would need to be a part of JP release, as it touches backend logic.

Can we contact those people who reported the issue to us and have dotcom sites?

**Comment by designsimply** [comment]
> Can we contact those people who reported the issue to us and have dotcom sites?

Done in 2997984-t, 2813042-t, 3235835-t, 3235836-t, 3093955-t, 31407620-t, 3235837-t.

**Comment by marekhrabe** [comment]
This is now fixed for all dotcom sites and Jetpack sites with plugin version 5.0 and newer.

**Comment by lancewillett** [comment]
Nice work @marekhrabe and Team Samus! ✊

**Comment by designsimply** [comment]
Tested and re-confirmed the fix on WordPress.com. :)

<img width="1280" alt="screen shot 2017-06-23 at fri jun 23 12 25 04 pm" src="https://user-images.githubusercontent.com/1119271/27495759-74e63dac-5810-11e7-85f0-96971c2e83ce.png">
<sup>Seen at https://design5279.wordpress.com/wp-admin/edit.php?post_type=feedback using using Firefox 54.0 on Mac OS X 10.12.5.</sup>

<img width="1280" alt="screen shot 2017-06-23 at fri jun 23 12 32 15 pm" src="https://user-images.githubusercontent.com/1119271/27495768-7e461084-5810-11e7-9090-fbc7616d2262.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11195 using Firefox 54.0 on Mac OS X 10.12.5.</sup>
