### ISSUE TITLE
New Onboarding: End of long site names is cut off in Site Title input

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#49419]
### Steps to reproduce the behavior

1. Go to `/new`
2. Type a site title that is wider than the provided text field

#### What I expected to happen

The site title visible in the text field would be (a suffix of) what I typed in.

#### What actually happened

The rightmost little bit of the text is cut off:

![Screen Shot 2021-01-28 at 12 49 40 PM](https://user-images.githubusercontent.com/9310939/106185414-6d1c5b00-6168-11eb-9107-fa1a39135cdc.png)

Although the full text is still visible in the header:

![Screen Shot 2021-01-28 at 12 49 44 PM](https://user-images.githubusercontent.com/9310939/106185441-71e10f00-6168-11eb-9f8f-35b65724a20a.png)

### Context

Signup flow

#### Browser / OS version

Chrome, macos

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Does not block purchases, but this is literally the first point of interaction for new customers.

**Comment by simison** [comment]
@razvanpapadopol @ollierozdarz  did I see conversation about this somewhere just recently?

**Comment by razvanpapadopol** [comment]
I know only of this other ticket #49328 which is kind of related at least by considering the cause: a long site name.

**Comment by ollierozdarz** [comment]
@simison this [ticket](https://github.com/Automattic/wp-calypso/pull/48780#event-4257619646) might be what you're thinking of? I suggested and mocked up truncating the name (easiest option compared to trying to hack @media queries) but the ticket was put on hold.

**Comment by simison** [comment]
Yeah, I think the solution here is to just make it look more like an input:

> What is your site's name?
> [ Input ]
> [ Continue ]

Not very high priority right now I'd say.

**Comment by yansern** [comment]
Related to a very old issue. https://github.com/Automattic/wp-calypso/issues/40013

**Comment by ollierozdarz** [comment]
It looks like the [ticket](https://github.com/Automattic/wp-calypso/pull/48780#event-4257619646) I mentioned has been put on hold for now.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was unable to reproduce this issue on Gutenboarding with Firefox 94.0a1, Chrome 94 and Safari 15.0.
The full name shows as long as the site name field is still highlighted.
Once the focus moves away from the site name, the first bit that fits in the width will be shown.

Closing as `Closed - Not Reproducible`.

![Screen Shot 2021-10-04 at 4 41 15 PM](https://user-images.githubusercontent.com/6549265/135938750-435d7a74-7fd5-4c37-b969-ac3b24649cb5.png)
