### ISSUE TITLE
New Onboarding: domains and plans price formatting doesn't match

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49410]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/new as non-US user with USD currency set in your account
2. Advance to Domains step and check the price formatting for domain suggestions
3. Advance to Plans step and check the price formatting

#### What I expected to happen
Price formatting should match and should be similar to what's on `/start` onboarding flow.

### Context
For domain suggestions, we're currently using the price formatted by the backend.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Not a blocker but since a user can jump very easily from Plans Grid to picking a domain, some consistency would be good.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
* Plans price formatting:
<img width="1231" alt="Screenshot 2021-01-28 at 16 56 42" src="https://user-images.githubusercontent.com/14192054/106156238-f5f7be80-6189-11eb-8951-afd2c363cab2.png">

* Domain suggestion price formatting:
<img width="1228" alt="Screenshot 2021-01-28 at 16 57 22" src="https://user-images.githubusercontent.com/14192054/106156228-f2fcce00-6189-11eb-940a-23a8d636fbe6.png">

**Comment by razvanpapadopol** [comment]
@alshakero opened an API patch to add raw price to domain suggestions: D56060-code

cc: @Automattic/cobalt

**Comment by alshakero** [comment]
Closing as fixed https://github.com/Automattic/wp-calypso/pull/49464.
