### ISSUE TITLE
Cover Block: block's text is hidden in the editor when block image or background color is removed

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#49422]
### Steps to reproduce the behavior

1. Open a page or post 
2. Add a new Cover Block 
3. Add an image or background color to the Cover Block
4. Add text to the Cover Block
5. Go to the Cover Block's settings and click "Clear Media".
6. Publish page

#### What I expected to happen
The text within the block to still be visible in the editor. Although the text appears just fine on the published page/post.

#### What actually happened
Unable to see the text in the block

https://user-images.githubusercontent.com/10015451/106186353-27649000-6172-11eb-81e9-b70138581c2c.mov

### Context
Reported in 3688131-zen

**Comment by simison** [comment]
This issue would be great at https://github.com/WordPress/gutenberg/issues if not there already.

**Comment by synora** [comment]
Related: https://github.com/WordPress/gutenberg/issues/28888.

**Comment by apeatling** [comment]
closing in place of https://github.com/WordPress/gutenberg/issues/28888
