### ISSUE TITLE
Store|Woo: Move setup of WooCommerce for Atomic sites without WooCommerce plugin out of `extensions/woocommerce`

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49424]
_Part of the Sunset Store project. See pbIJXs-sE-p2 for more details._

Once Store is completely removed, there will be no need for `extensions/woocommerce`. In order to prepare for this, we should move the setup of WooCommerce for Atomic sites that do not yet have the WooCommerce plugin out `extensions/woocommerce`.

See #48423 for more details, as that is the issue where we originally tracked adding support for this in the Sunset Store project.

## UX change

Since the setup would be outside of `extensions/woocommerce`, it would not live in the Store experience UI, and would be a standalone page. An example of how it may look is:

![image](https://user-images.githubusercontent.com/3747241/105652882-5cb07a00-5ef5-11eb-8d03-e822318ca77e.png)

## Acceptance criteria

- Automatically redirect users that click on the deprecated "Store" menu item, or the "WooCommerce" menu item (available on Atomic sites when WooCommerce plugin is not installed) to the Core UI setup journey

## Tasks

- [ ] TBD

## Open questions

- Should we move this to `wpcomsh`, or keep it in Calypso? Moving to `wpcomsh` likely means it will be easier to test, as development and test environments won't need to involve Calypso. Is there any downside?

**Comment by ilyasfoo** [comment]
>Should we move this to wpcomsh, or keep it in Calypso? Moving to wpcomsh likely means it will be easier to test, as development and test environments won't need to involve Calypso. Is there any downside?

I think it's better to keep it in Calypso, as it would require less amount of work to refactor since the existing code has tight dependencies with Calypso internals.

**Comment by mattsherman** [comment]
> I think it's better to keep it in Calypso, as it would require less amount of work to refactor since the existing code has tight dependencies with Calypso internals.

That sounds reasonable. Good call.
