### ISSUE TITLE
Nav Unification: VIP Icon is blurry

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#49434]
### Steps to reproduce the behavior

1. Select a site with some sort of VIP affiliation
2. Hover over the VIP section to see the blurry logo

<img width="145" alt="Screen Shot 2021-01-28 at 2 27 37 PM" src="https://user-images.githubusercontent.com/26996883/106201137-3d278480-6175-11eb-8218-001b15669d72.png">

#### What I expected to happen

I expect the icon to be more prominent. 

#### What actually happened

The icon looks blurry compared to others:

<img width="275" alt="Screen Shot 2021-01-28 at 2 29 50 PM" src="https://user-images.githubusercontent.com/26996883/106201177-4d3f6400-6175-11eb-8195-1b40586d2ce5.png">

#### Browser / OS version

MacOS 11.1 / Chrome Version 87.0.4280.141 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Unclear for level of impact!

**Comment by getdave** [comment]
@Automattic/ajax Let's reach out to cCmkD-p2 for feedback on this one.

**Comment by obenland** [comment]
With VIP sites no completely moved off of dotcom, this should only be visible internally.
@annezazu Would you be opposed to us closing this to focus on higher-priority items?

**Comment by annezazu** [comment]
Ah! If it's solely an internal issue then I trust you all there and will let my minor annoyance with it subside :)
