### ISSUE TITLE
Nav Unification: Current site notices with banner upsell text not appearing on several menu items

### ISSUE THREAD

**Issue by deancroyal** [Automattic/wp-calypso#49442]
### Steps to reproduce the behavior

1. Create a new free site, do not purchase a plan.
2. Go to 'My Home' for the new site.
3. See the current site notice, above the My Home menu item, with the "Free domain with a plan (Upgrade)" banner upsell.
4. Click on 'Posts > Categories'
5. See the site notice with banner upsell text no longer appears.

The site notice with banner upsell text does not appear on each of the following menu items:

- Posts > Categories, Tags
- Links > All Links, Add New, Link Categories
- Feedback > Feedback, Polls, Ratings
- Settings > Reading, Media, Polls, Ratings

#### What I expected to happen
I expected the "Free domain with a plan (Upgrade)" banner upsell to display as I clicked through the menu items listed above. 

#### What actually happened
Instead, the "Free domain with a plan (Upgrade)" banner upsell did not display on the menu items listed above.

#### Browser / OS version
Google Chrome Version 87.0.4280.141 (Official Build) (x86_64) / Mac OS Big Sur Version 11.1 (20C69)

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="250" alt="Screen Shot 2021-01-28 at 8 49 59 PM" src="https://user-images.githubusercontent.com/13387217/106233024-69a9c380-61aa-11eb-9176-90b3aff932bc.png">

https://user-images.githubusercontent.com/13387217/106233133-a5dd2400-61aa-11eb-855b-57bb67e0d582.mov

**Comment by obenland** [comment]
Thank you for the detailed ticket and screenshots/videos! 

[We decided to not port notices and banners to wp-admin in v1](https://github.com/Automattic/wp-calypso/issues/45574#issuecomment-740737681) to keep scope in check. I'm not sure how we can duplicate them without significant code duplication as well :(

**Comment by obenland** [comment]
I'm going to close this for now in favor of #45574 later on.
