### ISSUE TITLE
Akismet Stats menu missing

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#49454]
It seems we have classified the `Akismet Stats` menu from WPAdmin as "To be removed" here https://docs.google.com/spreadsheets/d/1i640dQt4vs2XYgqRA4YEH69ssR9UNcFJx49HUss0-q0/edit#gid=0 with reason "Perhaps we move this to be just another section within Stats?" but we haven't moved this functionality.

![](https://cln.sh/nRWyMp+)

Perhaps, we should add this menu back probably under "Stats" menu until we consolidate it with the Stats screen.

**Comment by obenland** [comment]
@stephdau How are users who've not ventured into wp-admin currently consuming Akismet stats?

**Comment by tjcafferkey** [comment]
Also, how many users currently go to this page from WP Admin so we can measure impact.

cc @stephdau

**Comment by stephdau** [comment]
Sorry for the late reply, I was AFK on vacation.

@obenland : how do they consume AK stats outside of wp-admin: as far as I know, they do not. Or they do via https://akismet.com/account/

@tjcafferkey : I'm not sure how to find this out, we're not really involved in WPCOM dev besides pushing the latest plugin version to it.

**Comment by stephdau** [comment]
One thing I do know: we've received no questions/concerns about the stats now being inaccessible.

**Comment by obenland** [comment]
Thanks Stephane! Let's not worry about it then
