### ISSUE TITLE
New Unified Navigation does not work on blog ID 1

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#49455]
Reported by @chickee0311 in pau2Xa-2E1-p2

Seems that blog ID 1 (wordpress.com) does not work in Calypso and therefore all links of the new unified navigation should point to WP Admin.

I guess we can fix this by creating a new menu class that extends from `Admin_Menu` and use it for this blog (similarly to the new menus used for P2 sites: D55069-code).

**Comment by getdave** [comment]
Thanks for catching and tracking this @mmtr. Two points that came to mind:

1. Question: how critical an impediment is an issue to our day to day workflow for a12s? 
2. If we do create a new menu class if might be an idea to break the class hierarchy or at least drastically simplify it.

Thanks.

**Comment by mmtr** [comment]
> Question: how critical an impediment is an issue to our day to day workflow for a12s?

@chickee0311 may have a better answer, but right now managing content for blog ID 1 is rather complicated unless you know all the direct WP Admin links and type them in the browser (e.g. `/wp-admin/post-new.php`, etc), something especially hard for URLs that contain identifiers (e.g. `/wp-admin/post.php?post=123&action=edit`). 

I don't know how often content on this blog needs to be managed, but I guess this could fall into either the Normal or High priority.

> If we do create a new menu class if might be an idea to break the class hierarchy or at least drastically simplify it.

Totally agree, although we may have a simpler solution: update the `show_unified_nav` function in WP.com, and include a `get_current_blog_id() !== 1` check so the nav unification is never enabled on this blog.

**Comment by creativecoder** [comment]
I seem to remember mention of a toggle to prefer wp-admin pages when possible? Is that still in the works? I think that might solve the workflow issues (for blog ID 1, and likely other places, as well).

**Comment by mmtr** [comment]
> I seem to remember mention of a toggle to prefer wp-admin pages when possible? Is that still in the works? I think that might solve the workflow issues (for blog ID 1, and likely other places, as well).

Yes, it's still in progress: https://github.com/Automattic/wp-calypso/issues/47043

While that can be used as a workaround, the setting will change all the links of all the user' sites. Users may still prefer to have Calypso links except for blog ID 1, so we still need a way to entirely disable the Calypso links for unsupported sites.

**Comment by creativecoder** [comment]
Ah, didn't realize it was a per user setting. That makes sense though, thanks for clarifying!

**Comment by andrewserong** [comment]
I'm not sure if this is related to the issue for blog ID 1, but I encountered a similar issue to the issue reported when attempting to access a site via wp-admin, as a Super Admin user. The use case is for managing block patterns source sites (more info in PCYsg-t0i-p2). As a super admin, I might want to go in and update a particular post, even though I'm not a user of that site. Because I'm not a user of that site, the posts view in Calypso doesn't appear to work, but `wp-admin` typically does.

The workaround I'm using at the moment is to either a) add myself as a user to the site where I want to update something, or b) go to `wp-admin/edit.php` manually. Personally, I don't find that too challenging, but I just thought it could wind up being a potential issue for HEs?

**Comment by obenland** [comment]
We could add a check for superadmins that are not members of the current site in `WPcom_Admin_Menu::should_link_to_wp_admin()` and return true regardless of toggle setting

**Comment by cpapazoglou** [comment]
Instead of forcing WPAdmin links for certain sites, I am more in favor of bypassing the `admin-menu` rest api restrictions for superadmins or proxied users ( I am not sure what's the condition ) and let users decide if they prefer the Calypso or WPAdmin links.

This kind of bypass is already happening somewhere in the code and that's why we can access `/wp-admin` of these sites without being members of them.

**Comment by creativecoder** [comment]
> We could add a check for superadmins that are not members of the current site in WPcom_Admin_Menu::should_link_to_wp_admin() and return true regardless of toggle setting

I wonder if that complicates troubleshooting for users, because it gives a different experience for super admins (HEs) compared to users.

---

Also, I wanted to connect that this proposed solution would also resolve this issue here (at least, I think it would?)

paYJgx-1lp-p2#comment-1626

**Comment by obenland** [comment]
> I wonder if that complicates troubleshooting for users, because it gives a different experience for super admins (HEs) compared to users.

That's a good point. Extending the check to include `is_a8c()` should help with that?

**Comment by mmtr** [comment]
> > We could add a check for superadmins that are not members of the current site in WPcom_Admin_Menu::should_link_to_wp_admin() and return true regardless of toggle setting
> 
> I wonder if that complicates troubleshooting for users, because it gives a different experience for super admins (HEs) compared to users.

It shouldn't cause any additional trouble since AFAIK the super admin role is not used for getting the same experience as a user (that's what support sessions are for), but for performing quick actions on behalf of the user without going through the add-myself-to-the-site process. 

For that reason, I think we should simply disable the nav unification for super admins that are not members of the current site. That way they will continue getting the default WP Admin experience they are getting currently. I'm hoping to have a diff shortly implementing this approach.

> Also, I wanted to connect that this proposed solution would also resolve this issue here (at least, I think it would?)
> 
> paYJgx-1lp-p2#comment-1626

No, this needs a separate solution (paYJgx-1lp-p2#comment-1661) and can be tracked in this separate issue: https://github.com/Automattic/wp-calypso/issues/49262

**Comment by mmtr** [comment]
Fix ready for review: D57136-code

**Comment by mmtr** [comment]
Just landed D57136-code, so this issue should be fixed now.
