### ISSUE TITLE
My Blogs menu missing

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#49453]
As @msilbers has mentioned (p7DVsv-ago-p2#comment-34128), there is a [feature "Post by Email" ](https://wordpress.com/support/post-by-email/) that seems accessible only from `https://[DOMAIN]/wp-admin/index.php?page=my-blogs`. 

**Old Nav**
![image](https://user-images.githubusercontent.com/12430020/106247898-dfe50f00-6218-11eb-8323-1476487bded5.png)

It seems that we have classified this menu here https://docs.google.com/spreadsheets/d/1i640dQt4vs2XYgqRA4YEH69ssR9UNcFJx49HUss0-q0/edit#gid=0 as "To be removed" with reason "All my sites in the site switcher gives you a snapshot of all your blogs" which is partly true cause through [https://wordpress.com/home](https://wordpress.com/home) you can click the link to the bottom 

![](https://cln.sh/GF0lFh+)

which lands you here

![](https://cln.sh/wrxOMV+)

So, while I would suggest bringing back this menu, I am not sure how much visibility we want on this (does it deserve to be so prominent?) or whether we can just change the documentation to go through [https://wordpress.com/home](https://wordpress.com/home).

cc: @obenland

**Comment by obenland** [comment]
Could this be handled like https://github.com/Automattic/jetpack/pull/18560? From what I understand we don't need the menu item to show up, we just need the page accessible from that link?

**Comment by cpapazoglou** [comment]
> Could this be handled like [Automattic/jetpack#18560](https://github.com/Automattic/jetpack/pull/18560)? From what I understand we don't need the menu item to show up, we just need the page accessible from that link?

Not exactly, the page is accessible `https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs&show=hidden` but the entry point is currently only through `https://wordpress.com/home` 
![](https://cln.sh/XSnePM+)

**Comment by obenland** [comment]
Okay, so the underlying issue is that Post by Email can't be managed anymore. This doesn't seem to leave us with any good options.

Maybe we could rename that submenu item to make it less obtrusive on the Calypso side and show it under Settings?

**Comment by msilbers** [comment]
It was mentioned on the p2, but there are other reasons we send folks there as well, including removing themselves from sites, and for Post by Voice, so it would help to keep it easily accessible.

**Comment by cpapazoglou** [comment]
> Okay, so the underlying issue is that Post by Email can't be managed anymore. This doesn't seem to leave us with any good options.
> 
> Maybe we could rename that submenu item to make it less obtrusive on the Calypso side and show it under Settings?

That could work, "Manage My Blogs" would be better?

There is one more problem though. `https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs&show=hidden` is the WPAdmin of the `dashboard.wordpress.com` site

Before | After
-------|------
![](https://cln.sh/13KuVU+) | ![](https://cln.sh/G3JP4d+)

so being able to navigate to that page from eg "My Simple Free" site is kind of weird cause the navigation menu will be totally different from "My Simple Free" site and navigating back is impossible without going to "Browse Sites" and selecting "My Simple Free" site

For Simple Sites `[DOMAIN]/wp-admin/index.php?page=my-blogs&show=hidden` works but it doesn't for Atomic.

On the other hand, leaving the link in the `https://wordpress.com/home` page, makes more sense to me cause it's not a management page of the current blog rather than a management page for all blogs. In that case, adding a "Manage My Blogs" menu in `https://wordpress.com/me` would make more sense?

**Comment by obenland** [comment]
@sfougnier What's your opinion on where this should live and how it should be called?

**Comment by cpapazoglou** [comment]
@sfougnier is there a chance you can weigh in here?

**Comment by ghost** [comment]
> In that case, adding a "Manage My Blogs" menu in https://wordpress.com/me would make more sense?

I think moving to `https://wordpress.com/me` makes the most sense since My Blogs is account-specific and not site-specific. Mocked up in the Me sidebar here:

<img width="1440" alt="Desktop - Me" src="https://user-images.githubusercontent.com/67021691/107053207-90648d00-679c-11eb-8451-30e85f2a9b75.png">
