### ISSUE TITLE
New Onboarding Launch: Domain search input suddenly has value when flipping from name step to domain step when site title has foreign characters.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#49468]
I've created a site with Gutenboarding testing instructions.
While launching the site through the step-by-step launch, I don't get the domain suggestions initially. Only after going back-and-forth from the naming to the domain step, I get the expected domain suggestions as described in the testing instructions. 

See this video: https://www.loom.com/share/9c88720d56d84d49a32073f22958a12f

_Originally posted by @StefanNieuwenhuis in https://github.com/Automattic/wp-calypso/issues/48399#issuecomment-769720208_

**Comment by youbrokesomething** [comment]
This onboarding flow has been replaced by other new flows. Closing this ticket.
