### ISSUE TITLE
E2E: re-enable and fix New Onboarding test suite

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49466]
**What**
The [main Gutenboarding suite](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/wp-gutenboarding-spec.js#L39) has been disabled in #49366 so it needs fixing and re-enabling.

**Why**
Adding coverage for a signup & site creation flow.

**Additional context**
* When testing manually everything seems to be working fine.
* <s>Even when running the test suite locally, on mobile, site title input is flickering.</s> this is fixed now
* On CI, there is a site creation error displayed but it doesn't say much

Hint: this may be related to a limit on signups / sites created. p1613687755065900/1613503907.064300-slack-C1A1EKDGQ

Other investigation: p1613067244270700-slack-C02DQP0FP

**Comment by simison** [comment]
> On CI, the site creation error suggests that the site title wasn't entered correctly, and some non-alphanumeric characters (eg: + from username were used.

Wasn't @jsnajdr recently fixing some E2E test issue in the site-title step?

**Comment by jsnajdr** [comment]
@simison I disabled the entire Gutenboarding suite in #48729 and then @bsessions85 fixed the e2e tests and enabled them in #49126.

Then a week later @p-jackson disabled just one test from the suite in #49366. I'm not sure if these two issues are related to each other or not.

**Comment by razvanpapadopol** [comment]
Bumping the priority to High in the context of upcoming Experiments that will increase the traffic in this flow.
Updated description with links to the latest investigations.

cc: @worldomonation

**Comment by worldomonation** [comment]
I've added the flakey e2e label to better track e2e tests that have been disabled, or marked as flakey.

**Comment by razvanpapadopol** [comment]
On Hold until we get some data about the failures

**Comment by yansern** [comment]
This PR fixes general flakiness in the Gutenboarding spec: https://github.com/Automattic/wp-calypso/pull/51573
This PR fixes the iframe context switching flakiness: https://github.com/Automattic/wp-calypso/pull/51580
This phab patch removes the signup limit: ~~D59543-code~~ D59614-code
Slack discussion: p1617136625041200-slack-C1A1EKDGQ

**Comment by simison** [comment]
@razvanpapadopol is this good to close now?

**Comment by razvanpapadopol** [comment]
The work is pretty much done but I was keeping the issue open while waiting for D59614-code to be deployed. If needed, we can probably create a separate issue to track the signup limit removal for e2e tests.
cc: @yansern @westi
