### ISSUE TITLE
Post-Checkout Upsell: should reset window position when showing upsell

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#49473]
### Steps to reproduce the behavior

1. As a new user, create a site and purchase a personal plan
2. The post-Checkout upsell will be rendered with the current window scroll position

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/942359/106294560-4bc97680-621d-11eb-898a-6057691d0d18.mov

**Comment by michaeldcain** [comment]
@Automattic/martech-decepticons

**Comment by ianstewart** [comment]
I was able to reproduce this today. This is what I saw after checkout.

![image](https://user-images.githubusercontent.com/545779/109874602-f1b13c00-7c34-11eb-910f-470ece198483.png)

**Comment by michaeldcain** [comment]
@niranjan-uma-shankar: is this something you guys can look at?

**Comment by niranjan-uma-shankar** [comment]
@michaeldcain @ianstewart Thanks for reporting!

I couldn't reproduce the issue. I'm still tracking this issue in the Decepticons Trello board in the card c/HsvxQWqD-tr.

Here's what I tried:
1. As a new user, I tried signing up, purchased a Personal plan, and waited for the Quick Start upsell page to show. This was the new navigation interface.


![scrollposqs](https://user-images.githubusercontent.com/1269602/110672188-5a7c5380-81f5-11eb-932b-310d46731994.gif)


2. As an existing user, I created a new site, purchased a Personal plan, and waited for the Quick Start upsell page to show. This was with a saved payment method(as shown in the video in the issue description) and the old nav UI.


![scrollposqs2](https://user-images.githubusercontent.com/1269602/110672205-60723480-81f5-11eb-9768-6fa21f7995db.gif)

**Comment by michaeldcain** [comment]
Ian reproduces it in the first video on this comment: p58i-abg-p2#comment-49729

**Comment by michaeldcain** [comment]
@niranjan-uma-shankar: it looks like Chrome, existing user, business plan purchase (with credits - don't know that that's part of the reason)

**Comment by ianstewart** [comment]
I wondered if it was credits but it looks like you were able to do it with a card at the top of this thread.

**Comment by ianstewart** [comment]
This was reported again at p58i-avT-p2#comment-50570.
