### ISSUE TITLE
Clicking All Posts goes to WP-Admin posts instead of Calypso posts page

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#49486]
### Steps to reproduce the behavior

1. On Atomic site, start writing a new post
2. Click the "W" on the top 
3. Click "< All Posts"
4. You're taken to Wp-admin posts page, not the calypso posts page

#### What I expected to happen
I expected to see Calypso posts page

#### What actually happened
I saw the wp-admin posts page

### Context
I was doing testing 

#### Browser / OS version
Chrome 88 MacOS

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
Simple

#### Is there any console output or error text?
no

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
minor

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See Video on my comment on pciE2j-bv-p2 (to be posted)
<img width="1234" alt="Screen Shot 2021-01-29 at 1 20 17 PM" src="https://user-images.githubusercontent.com/31110506/106323523-c9e54780-6234-11eb-9f91-1cf8a0eabc84.png">

**Comment by worldomonation** [comment]
Still reproducible, it is a jarring experience.

**Comment by edwinho89** [comment]
Reported in 5291550-zd-woothemes

The same user had two other bug reports similar to this issue: https://github.com/Automattic/wp-calypso/issues/63422 and https://github.com/Automattic/wp-calypso/issues/64561

**Comment by Robertght** [comment]
Thank you @edwinho89! I just noticed another issue which I closed and it appears to happening only on some sites.  This workaround did it for me, but I'm checking with the user in the ticket above to see if that sticks with them:

1. I went to the Posts page and clicked on View. 
2. I selected the Classic view
3. I selected the Default view
4. I accessed a post and then I clicked on the site logo and on "View posts" and the list of posts appears to show up now in the modern dashboard.

**Comment by vykes-mac** [comment]
The issue seem to be on both Simple and Atomic sites. To reproduce go to > All posts page > Change View to Classic > Select on3 of the post > View all post to go back. Change view back to default, then return from a post again and it will go back to classic view.

**Comment by Greatdane** [comment]
I think this is still happening. Got a report here; 5496457-zd-woothemes
(there is a video in the Slack thread linked) 

Site keeps going back to wp-admin rather than Calypso.

**Comment by cecilearkay** [comment]
Quick note here that hitting the back arrow on your browser takes you back to Calypso.

**Comment by vykes-mac** [comment]
@Greatdane I'm not able to reproduce this issue again. I'm suspecting that this user view was already in a bad state from before the fix was available, the update to their view preference to get them in a good state would not happen on the first try, the first try would show them the issue , however if they change to classic view -> default view again their view preference would now be in the correct state as the fix would now be applied and the issue won't happen again.

Is the user still having the issue?

**Comment by Greatdane** [comment]
@vykes-mac It continues to happen for the user, even after we keep setting the view to default/Calypso. I can share a video privately on slack if that helps.

As @cecilearkay, clicking the back arrow in the browser will take you back to Calypso, but that is not ideal.

**Comment by vykes-mac** [comment]
@Greatdane yes can you please share that video. How did you set it to default? the view preference fix will apply only if you change it to classic view -> visit a post-> return to all post -> change to default view again.

**Comment by jartes** [comment]
I've had a user with the same issue. After a post was published and then when going to the Posts page by clicking on the "View Posts" link from the sidebar, they were redirected to /wp-admin rather than Calypso.

37390542-hc

**Comment by danielbachhuber** [comment]
Potentially related https://github.com/Automattic/wp-calypso/issues/69908

**Comment by rinazrina** [comment]
I got another report here: 6527289-zd-woothemes (Atomic site)

- I can reproduce this on the user's site but not on my test site.
- The issue persists even with only Jetpack active and a default WP theme. And this is not theme specific.
- I've tried changing the editor preference on User RC to `gutenberg` but no luck.
- When opening the page editor, the URL was automatically redirected from `https://wordpress.com/page/example.com/1234` to `https://example.com/wp-admin/post.php?post=1234&action=edit&post_type=page&calypsoify=1`
- The post editor was redirected from `https://wordpress.com/post/example.com/1234` to `https://example.com/wp-admin/post.php?post=1234&action=edit&calypsoify=1`

Advised the user to use the Back arrow as a workaround.

**Comment by katinthehatsite** [comment]
I am troubleshooting it here because it is the same issue: https://github.com/Automattic/wp-calypso/issues/69908#issuecomment-2049827639

**Comment by katinthehatsite** [comment]
@rinazrina I am working on this at the moment, and although, we are still working on fixing the incorrect redirect, I wanted to mention that in user's case, the issue happens because they have installed one of the plugins that is not compatible with Gutenberg/gutenframe. The plugin is `siteorigin-panels`. If you disable it on user's site, you should see that the redirect works as expected. This is not a complete solution though, just a workaround for now if the user does not mind disabling that plugin.

However, we plan to fix the root cause in the next few days and make the redirect work as expected 🤞
