### ISSUE TITLE
Unable to change homepage when using store

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#49488]
### Steps to reproduce the behavior

1. Create new ecommerce plan on existing account( it will use Gutenboarding)
2. You'll pick a homepage style you like
3. Then when you're setting up your store, it will ask if you want it to create a homepage. Click yes
4. Now go to your pages in Calypso and you'll see the created homepage has the homepage icon next to it. 
5. Try setting the other homepage to be the homepage and the setting won't stick
6. Try deleting the created homepage and the homepage gets set to blog and can't be changed

#### What I expected to happen
I expected to be able to set the homepage to the homepage I want it to be.

#### What actually happened
I was forced to use the store homepage and cannot change it

### Context
I found this while doing testing for pciE2j-bv-p2. Video will be posted there soon.

#### Browser / OS version
Chrome 88 MacOS

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
medium

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See video here pciE2j-bv-p2

**Comment by simison** [comment]
Potentially fixed in https://github.com/Automattic/wp-calypso/pull/49399? (issue https://github.com/Automattic/wp-calypso/issues/46114)
