### ISSUE TITLE
Homepage Created when setting up store has block errors

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#49487]
### Steps to reproduce the behavior

1. Set up an new Ecommerce plan
2. When setting up your store, select to have a homepage created
3. Try to go edit that newly created homepage
4. There are block errors

#### What I expected to happen
I expected to see a good version of the homepage to edit

#### What actually happened
I actually saw a page with block errors

### Context
I was testing for pciE2j-bv-p2 and noticed the issue. Video to be posted there soon.

#### Browser / OS version
Chrome 88 MacOS

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?
no

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
minor

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/31110506/106326531-e89a0d00-6239-11eb-97c1-6490d5df00fc.png)

**Comment by Greatdane** [comment]
Tried to recreate this but I believe the issue has now been fixed. 

Homepage loads without any block errors on a new Ecommerce site.
