### ISSUE TITLE
Nav Unification: Add Media File Size to Media Library

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#49492]
**What**
The Media Library accessed from the Media section of the new Nav Unification dashboard does not show the file size for the individual media items.  I currently refer users to the Media Library on the WP Admin dashboard to see that information. Now that the WP Admin link is gone, it will be harder for users to see how big the individual files in their media library are. 

**Why**
We often recommend that users review the size of their media files and optimize larger images when they complain of slow sites, but it is hard for them to do that when the information isn't readily available. 

**How**
Add the file size somewhere in the area of the label that displays the dimensions.
![screenshot](https://d.pr/i/zLdR9R+)
Image URL: https://d.pr/i/zLdR9R

**Comment by Aurorum** [comment]
PR for this issue in #49500. :)
