### ISSUE TITLE
Call to Action Pattern Block: Button Doesn't/No Option to Center

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#49498]
![Alt text](https://d.pr/i/wfQMtu/BUJhBEPzxm+)

### Steps to reproduce the behavior

https://www.loom.com/share/5c7e6672ee714ca5a7a4cac94c2c1671

1. Create a page/post. 
2. Add "Call to Action" Pattern Block.
3. Publish. 
4. Preview page. 

#### What I expected to happen

1 - The button is centered while looking at the live view. 
2 - `Justify Content` option is visible, similar with the "Button Block". 

Single Button Block: 

![Alt text](https://d.pr/i/5gQZHE/JgKEEa3QJt+)

Button Block from the "Call to Action Pattern Block":

![Alt text](https://d.pr/i/cGABUD/uymeUOlUuM+)

#### What actually happened

1 - Button is aligned to the left, even if it's centered aligned from the editor. 
2 - The `Justify Content` option is missing. 

#### Browser / OS version

Firefox 84.0.2 (64-bit)
macOS Big Sure 11.11

#### Is this specific to the applied theme? Which one?

Twenty Twenty theme

#### Does this happen on simple or atomic sites or both?

Tested and Present on both AT and Simple sites

-----------------

hc-26875018

**Comment by andrewserong** [comment]
Related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/28957

**Comment by annezazu** [comment]
Hey folks! I'm looping back on this issue now years later and I'm struggling to understand quite what's going on, considering the prior links to videos aren't available and I'm not sure the exact pattern used. I can replicated the prior issue here where if you insert a single button via the code editor and transform to a buttons block it causes issues https://github.com/WordPress/gutenberg/issues/28957 Here's a video of me trying to replicate the problem on WordPress.com with the available patterns (only two of them):

https://github.com/user-attachments/assets/12985dc8-33a7-4879-9626-0981d857adc1

To be safe, I confirmed there are two call to action patterns in the WordPress.com Pattern library too: https://wordpress.com/patterns?s=call+to+action As a result, I'm going to close this out. There have been no further reports of the problem, the current call to action patterns work correctly, and I can't replicate the original issue. 

If this is incorrect, let me know and let's reopen!
