### ISSUE TITLE
Nav unification: account for admin menu hover/focus state changes in WordPress 5.7

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#49519]
WordPress 5.7 will introduce new hover/focus states to the admin menu. We'll have to assess the impact of this on Nav Unification and account for it ahead of time.

Screenshots of changes:
https://cloudup.com/cdWzjq0yvuq

Related code changes:
https://core.trac.wordpress.org/changeset/49961

**Comment by getdave** [comment]
I'd really like to get a handle on the potential effort required here. Days/weeks worth of work? Any dependencies (eg: Jetpack release) and or blockers.

We can then schedule/prioritise accordingly. My gut is that we're going to have to at least _start_ an implementation to address this prior to the launch of Nav Unification.

Would you be able to take a look into this for us @frontdevde? 

Also for https://github.com/Automattic/wp-calypso/issues/49517 which is related.

**Comment by frontdevde** [comment]
With a Nav Unification launch scheduled after the release of WP 5.7, this issue increases in priority and will have to be adressed prior to launch.

This issue includes two parts:
1. In Calypso we need to implement the new hover/focus state changes for the normal/collapsed sidebar. We need then to ensure that it matches the new WP 5.7 colors for all color schemes that originated in wp-admin. Last but not least, we need to assign colors in line with the rest of the color scheme for the color schemes that originated in Calypso.
2. In wp-admin we need to make sure that none of the Nav Unification specific styles overwrite any of the new changes. ~~Then we need to make sure that all color schemes that originated in Calypso have the relevant styles as well as the relevant colors (the ones we've previously decided on in 1.).IMPORTANT to note regarding timing: the second part in 2. needs to go into Jetpack where those color schemes live.~~

Update: what wasn't immediately obvious from the Screenshots is that the actual implementation uses `currentColor`. This is great news because this means we won't need to update the color schemes in Jetpack.
