### ISSUE TITLE
Site Settings: Rename "Start Over" to "Empty Content"

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#4952]
Currently when a user contacts support to start over we remove all their content. This is stated in the copy. However, the term "Start Over" Seems misleading the user is not starting over (resetting the theme options, etc) they are simply having their content emptied. 

![screenshot_21-04-2016-13 55 53](https://cloud.githubusercontent.com/assets/150348/14727986/934f4fc6-07e5-11e6-879c-b150f5d9dca4.png)

Until we do provide a way to start over should we change the text to "Empty Content" instead?

Related: #4634 and PR #4636

**Comment by kathrynwp** [comment]
Another option is to link to the Empty Site support page, which explains how users can delete their own content:

https://en.support.wordpress.com/empty-site/

Many of the users I've seen requesting to "start over" don't actually have very much content to delete, they could easily do it on their own without waiting for support do do it for them.

**Comment by kathrynwp** [comment]
Never mind, I missed that this was already done in another issue #4636

**Comment by lancewillett** [comment]
Headstart for users to run themselves will help with this as well.

**Comment by lancewillett** [comment]
Noting it would be nice to enable this for Jetpack sites as well, since it currently only shows up for WordPress.com sites. See https://github.com/Automattic/wp-calypso/milestone/150
