### ISSUE TITLE
Unable to access automattic.com wp-admin 

### ISSUE THREAD

**Issue by patrycjakiljanska** [Automattic/wp-calypso#49539]
I need wp-admin access to edit automattic WWU page and job posts. However, I am not able to access them.

### Steps to reproduce the behavior

1. Go to https://automattic.com/wp-admin/ 
2. Click on "Pages"
3. See error: I am redirected to all pages that I follow instead of seeing pages and posts on automattic website, screenshots attached.

#### What I expected to happen

I expected to access all pages on automattic website. Strangely enough, I am able to access them if I have a direct link to any post or page, for instance:

#### What actually happened

I am redirected to all pages that I follow instead of seeing pages and posts on automattic website, screenshots attached.

#### Browser / OS version

Chrome Version 87.0.4280.141 (Official Build) (x86_64)
OS MacOS Catalina, Version 10.15.2

#### Is this specific to the applied theme? Which one?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It's a bottleneck to perform my job effectively. I am not able to post nor remove job posts on my own.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Attached.

**Comment by michaeldcain** [comment]
@patrycjakiljanska: I've updated this issue to remove internal links and/or images. See: PCYsg-68j-p2

**Comment by michaeldcain** [comment]
@Automattic/ajax for triage

**Comment by mmtr** [comment]
We may need to add an exception for the automattic.com site, like in https://github.com/Automattic/wp-calypso/issues/49455.

@patrycjakiljanska in the meantime, can you manage the posts and pages going directly to `/wp-admin/edit.php` (posts) and `/wp-admin/edit.php?post_type=page` (pages)?

**Comment by cpapazoglou** [comment]
@patrycjakiljanska The problem is that you are not member of this site, you can access `/wp-admin` of that site because you are proxied! Adding yourself as a User of that site will let you see 

![](https://cln.sh/Idhp0h+) 

which contains the Job Posts in Calypso. Does this view help you or you still need `/wp-admin/edit.php?post_type=page` easily accessible? 

PS: Please ping me if you need help adding yourself to automattic.wordpress.com

**Comment by cpapazoglou** [comment]
Another workaround for the meantime is going to `https://wordpress.com/me/account` and switching on "Replace all dashboard pages with WP Admin equivalents when possible."

![](https://cln.sh/VCRxuz+)

**Comment by obenland** [comment]
@patrycjakiljanska I added you to the site as an Editor. Please let us know if that didn't fix this issue for you.
