### ISSUE TITLE
Gutenberg: 9.9 upgrade

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#49534]
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/48950
Release notes: [v9.9.0](https://github.com/WordPress/gutenberg/releases/tag/v9.9.0), [v9.9.1](https://github.com/WordPress/gutenberg/releases/tag/v9.9.1), [v9.9.2](https://github.com/WordPress/gutenberg/releases/tag/v9.9.2), [v9.9.3](https://github.com/WordPress/gutenberg/releases/tag/v9.9.3)

### Process

- [x] Install and activate
  - [x] Copy & install v9.9.0-rc.1 (D56279-code, D56280-code)
  - [x] Activate v9.9.0-rc.1 on edge (D56283-code)
  - [x] Copy & install v9.9.0 (D56546-code, D56548-code)
  - [x] Activate v9.9.0 on edge (D56547-code)
  - [x] Copy & install v9.9.1 (D56650-code, D56651-code)
  - [x] Activate v9.9.1 on edge (D56653-code)
  - [x] Copy and install v9.9.2
  - [x] Activate v9.9.2 on edge
  - [x] Activate v9.9.2 on production (D56300-code)
  - [x] Request v9.9.2 update for Atomic sites (p9o2xV-1g2-p2)
  - [x] Copy and install v9.9.3
  - [x] Activate v9.9.3 on edge (D57075-code)
  - [x] Activate v9.9.3 on production (D57089-code)
  - [x] Request v9.9.3 update for Atomic sites (p9o2xV-1gh-p2)
- [x] Testing
  - [x] Calypso E2E (https://github.com/Automattic/wp-calypso/pull/49599#issuecomment-778196819)
  - [x] Team City (D56300-code)
  - [x] Calypso E2E against v9.9.3 (https://github.com/Automattic/wp-calypso/pull/50092)
  - [x] Team City against v9.9.3 (D57089-code)
- [x] Publish internal announcements (p7DVsv-auF-p2, p1613147997272200-slack-CB0B2G43X)
- [x] Clean up unused releases
  - [x] 9.5.2 (D56987-code)
  - [x] 9.6.2 (D56990-code)
  - [x] 9.7.0 (D56572-code)
  - [x] 9.7.1 (D56584-code)
  - [x] v9.7.2 (D56988-code)
  - [x] v9.7.3 (D56989-code)
  - [x] v9.7.4 (D56991-code)
  - [x] v9.8.0-rc.1 (D56993-code)
  - [x] v9.8.1 (D56994-code)
  - [x] v9.8.2 (D56995-code)
  - [x] v9.8.3 (D56997-code)
  - [x] v9.9.0 (D57000-code)
  - [x] v9.9.0-rc.1 (D57001-code)
  - [x] v9.9.1 (D57002-code)
  - [x] v9.9.2 (D57142-code)
- [x] Update the Gutenberg Upgrade Log [pcoGjb-u-p2] and list patches applied (pcoGjb-K-p2)
- [x] Open a new issue for the next upgrade, transfer remaining tasks, close this issue.

#### Cover block's align regression issue [**FIXED in v9.9.2**]
- Reported in: https://github.com/Automattic/wp-calypso/issues/49673
- Breaks some of our templates (p1612384721081900-slack-C013QHLF28Y)
- WPCOM hotfix: r220611-wpcom
- Upstream fix: https://github.com/WordPress/gutenberg/pull/28796

#### Previously-focused block stealing focus from newly-created block [**FIXED in v9.9.3**]
- Found through the GB Calypso E2E tests.
- Reported here: https://github.com/WordPress/gutenberg/issues/28932
- Possibly not a blocker.
- Upstream fix: https://github.com/WordPress/gutenberg/issues/28932

#### Gallery captions cannot be added or edited [**FIXED in v9.9.3**]
- Reported in: https://github.com/WordPress/gutenberg/issues/28989
- Context: p1613295384091800-slack-CBTN58FTJ
- WPCOM hotfix: D57065-code
- Upstream fix: https://github.com/WordPress/gutenberg/pull/28992 (planned for v10.0)

#### Image editing unstable on Simple sites [**FIXED**]
- Fix: D56687-code
- See comments in the CfT post: p7DVsv-arm-p2
- Does this block us from upgrading production to 9.9.x? We can activate image editing independently.

### Related tasks

- [x] **Enable image editing in WPCOM** (pc9Uba-fo-p2)
   - [x] Make sure https://github.com/WordPress/gutenberg/pull/28255 is included in v9.9.0
   - [x] Prepare CORS headers (D46175-code)
   - [x] Setup the `media.crossOrigin` hook (D55980-code)
   - [x] Open a CfT on edge sites (p7DVsv-arm-p2)
   - [x] Remove the code that currently disables image editing in WPCOM (D56491-code)
- [x] **Rollback extraneous kses fix** (D56582-code)

---
FYI: @Automattic/good-mountain @tyxla @flootr @sarayourfriend  @griffbrad @inaikem

**Comment by fullofcaffeine** [comment]
This is done 🎉. Next one: https://github.com/Automattic/wp-calypso/issues/50060.
