### ISSUE TITLE
Nav Unification: Add Jetpack CRM and Jetpack Boost links

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#49537]
As agreed in p1HpG7-aZK-p2, when the Jetpack CRM and/or the Jetpack Boost plugins are activated, their menu entries should be grouped along with the global Jetpack menu entry.

Quick mockup (please note that each menu entry will have a different icon set by the plugin):

<img width="270" alt="Screen Shot 2021-02-01 at 13 48 06" src="https://user-images.githubusercontent.com/1233880/106460837-35792000-6494-11eb-81e2-63b22ceb172c.png">

This should be easier to handle once https://github.com/Automattic/jetpack/pull/18586 lands.

**Comment by getdave** [comment]
Jetpack not included in v1 launch so we'll wait for a more rounded solution for this when we know how Jetpack will be made compatible with Nav Unification.

**Comment by jordesign** [comment]
Seems worth further investigation with the picking up of Nav Unification work.

**Comment by BogdanUngureanu** [comment]
Jetpack Boost is currently part of Jetpack menu. Updated the position only for Jetpack CRM.

**Comment by BogdanUngureanu** [comment]
The menu will be repositioned in the next version of Jetpack CRM (4.6.0).
