### ISSUE TITLE
Nav Unification - WP-Admin redirect links (i.e Feedback) load an incorrect sidebar

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#49549]
Some links, like Feedback, direct you to an odd WP-Admin that says ‘Browse Sites’ instead of Switch Sites, clicking on Browse sites then brings you to a generic site selection page. The 'odd' sidebar is also missing some links like WooCommerce, Marketing, and Jetpack.

### Steps to reproduce the behavior

1. Load any site, simple or Business, from My Sites or Switch Sites
2. Click on any link that redirects to WP-Admin, such as a Feedback.
3. Notice the sidebar has now changed, you'll see Browse Sites rather than Switch Sites
4. Clicking on Browse Sites loads a generic https://wordpress.com/home site picker

#### What I expected to happen
Really I just expected the sidebar to stay the same. Part of the issue is the WordPress.com version of the sidebar is missing a lot of links like WooCommerce and Jetpack.

#### What actually happened
Instead it appears the links to various pages is bifurcated across two similar, yet not the same, sidebar navigations.

#### Browser / OS version
Chromium - Version 87.0.664.75 (Official build) (64-bit)

Windows 10

#### Is this specific to the applied theme? Which one?
All themes

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
High - Common site features appear on one navigation and not the other.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Initial page showing correct sidebar, but missing WooCommerce, Jetpack, Marketing

![image](https://user-images.githubusercontent.com/16580129/106479369-42881600-6478-11eb-99dc-3857317f1e90.png)

Incorrect 'wp-admin' version of navigation, includes the above pages but the Switch Sites link is now a Browse Sites link which act differently.

![image](https://user-images.githubusercontent.com/16580129/106479383-46b43380-6478-11eb-9548-2fa4c3fa6cbc.png)

**Comment by frontdevde** [comment]
Just noting that the Browse Sites portion if this reported issue is a "feature". I've created the related tracking issue for a v2 of Nav Unification here #49603

**Comment by getdave** [comment]
Thanks for reporting. Browse sites is expected behaviour.

The missing items are being addressed here https://github.com/Automattic/wp-calypso/issues/49042
