### ISSUE TITLE
Nav Unification - Installing plugin on simple site leads to incorrect sidebar 

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#49550]
This is a continuation of this issue #49549 

### Steps to reproduce the behavior

1. On a simple site, install a new plugin to AT site
2. After AT, site loads the incorrect 'Browse Sites' sidebar as noted in above issue

#### What I expected to happen
I expected only one consistent sidebar to load

#### What actually happened
The sidebar as it is now loads in two different states, a calypso state, and a wp-admin state

#### Browser / OS version
Chromium, Version 87.0.664.75 (Official build) (64-bit)

Windows 10

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Med - High
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/16580129/106480366-52ecc080-6479-11eb-95ff-859402f0552d.png)
![image](https://user-images.githubusercontent.com/16580129/106480396-5c762880-6479-11eb-87ab-183e4c0a60a3.png)

**Comment by frontdevde** [comment]
Thanks for reporting this issue! The Browse Sites behavior is as expected for the first iteration of Nav Unification. I created the following issue with some clarification as well as to ensure it doesn't get lost. https://github.com/Automattic/wp-calypso/issues/49603
