### ISSUE TITLE
User was able to add a plan on a site with an existing expired plan

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#49552]
Hi folks!

I wasn't able to reproduce the issue. But sharing in case you are able to find out what caused this:

### What happened

Got a user in chat who had an expired Premium plan and also a brand new Personal plan (at the same time)

#### What I expected to happen

For the expired Premium plan to be automatically removed when they purchased the Personal plan

#### What actually happened

They had two plans at the same time

### Context

Live Chat: 26739203-hc
Slack: p1612189634419200-slack-C03TY6J1A

#### Does this happen on simple or atomic sites or both?

The issue happened on a simple site.

**Comment by DavidRothstein** [comment]
We looked into this briefly - the second plan wasn't added by a user, rather by a happiness engineer (18582355-hc).  There's no bug here; they probably just forgot to remove the old Premium plan when helping the user downgrade to the new Personal plan.  Closing.
