### ISSUE TITLE
Nav Uni - WooCommerce and Marketing (and perhaps other links) links are missing

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#49553]
To access Marketing, or WooCommerce, you need to trigger the wp-admin redirection by clicking on a link that redirects to WP-Admin like Feedback or Plugins.

### Steps to reproduce the behavior

1. Go to Calypso version of nav uni
2. Notice that WooCommerce and Jetpack are missing, curiously Products appears.
3. Find a link that redirects to WP-Admin, try Feedback
4. Load a WP-Admin variant of the new sidebar, notice how it says Browse Sites in upper left, rather than Switch Sites.

#### What I expected to happen
I expected all of these links to show under one unified navigation

#### What actually happened
Appears we have two navigations here, one for Calypso, and another for WP-Admin

### Context
See #49549 

#### Browser / OS version
Chromium - Version 87.0.664.75 (Official build) (64-bit)

Windows 10

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Med - High

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/16580129/106487579-cb0ab480-6480-11eb-9eed-dc4448fd3e39.png)

![image](https://user-images.githubusercontent.com/16580129/106487658-e70e5600-6480-11eb-9ef1-962b3232651c.png)

**Comment by frontdevde** [comment]
Just noting that the Browse Sites portion if this reported issue is a "feature". I've created the related tracking issue for a v2 of Nav Unification here https://github.com/Automattic/wp-calypso/issues/49603

**Comment by getdave** [comment]
@mattsherman Is this something you are already addressing elsewhere?

**Comment by getdave** [comment]
The marketing link will be solved with: https://github.com/Automattic/jetpack/pull/18586 (edited)

**Comment by getdave** [comment]
Related https://github.com/Automattic/wp-calypso/issues/49549

**Comment by getdave** [comment]
Missing menu items are being addressed here https://github.com/Automattic/wp-calypso/issues/49042

**Comment by mattsherman** [comment]
> @mattsherman Is this something you are already addressing elsewhere?

The WooCommerce menu item is being tracked in the Nav Unification: WooCommerce support epic https://github.com/Automattic/wp-calypso/issues/49228
