### ISSUE TITLE
Content position on existing cover blocks has been reset to center in visual editor

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#49563]
I was in the middle of troubleshooting a different bug and noticed this issue occur immediately after the update to Gutenberg v9.8.3 on simple sites.

### Steps to reproduce the behavior

This may be a little difficult to reproduce because you would to have _already_ had a page or post with a cover block set to a position besides center-center. I have one that I can share if needed.

1. Select the cover block, observe that position is set to center: https://d.pr/i/OnLiFa
2. This particular block was set to bottom-center before, but when the page was opened in the editor after the Gutenberg update, it (along with all the other cover blocks) had gone back to showing center-center as being selected.
3. However, if you look at the code view, you'll see it still references bottom center: https://d.pr/i/gQVOsV
4. Trying to select a different content position in the editor will result in a _mix_ of tags showing, like this: https://d.pr/i/EqD2dC

### Context

I was troubleshooting a bug where embed blocks do not appear inside cover blocks when the content position is set to anything besides center-center, which I could replicate on both WP.com and self-hosted sites, and reported in the [Gutenberg repo](https://github.com/WordPress/gutenberg/issues/28640).

#### Is this specific to the applied theme? Which one?

Occurs on all themes

#### Does this happen on simple or atomic sites or both?

Simple

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

This happened on both my test site and a user's site, so I assume this will impact any sites where they've set a content position on the cover block and go back to change it later

**Comment by sirreal** [comment]
Thanks! This was tricky, but it appears to be a Gutenberg issue. I've filed https://github.com/WordPress/gutenberg/issues/28656

**Comment by Robertght** [comment]
Closing here as it seems it was already fixed in Gutenberg.
