### ISSUE TITLE
Appearance sub links go to an 'Oops' screen, then takes you to the customizer

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#49564]
Update - this appears to apply background, widgets, header, and menu. So the below details Appearance > Widgets, but it affects all of these links.

### Steps to reproduce the behavior

1. Go to Appearance > Widgets
2. Witness an Unexpected Error message page appear
3. Redirect to Customizer, but not on the Widgets tab

#### What I expected to happen
I expected this Widgets link to actually open the default wp-admin widgets page at https://woochristestsite.wpcomstaging.com/wp-admin/widgets.php

#### What actually happened
Instead it brings us through this redirection loop to the Customizer

#### Browser / OS version
Chromium - Version 87.0.664.75 (Official build) (64-bit)

Windows 10

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?

The URL that is first tried is:
https://wordpress.com/customize/woochristestsite.wpcomstaging.com?autofocus%5Bpanel%5D=widgets&retry=1

Here is a snapshot of the console during the transition 
![image](https://user-images.githubusercontent.com/16580129/106513381-e71e4e00-64a0-11eb-9b0a-0fe6ece41f14.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Mid - High

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/16580129/106512687-edf89100-649f-11eb-958e-51669763ab45.png)

![image](https://user-images.githubusercontent.com/16580129/106512706-f5b83580-649f-11eb-8182-d14f189f1307.png)

![image](https://user-images.githubusercontent.com/16580129/106512801-108aaa00-64a0-11eb-96b9-d2e9e7144023.png)

**Comment by cpapazoglou** [comment]
This one should be effectively be resolved by https://github.com/Automattic/jetpack/pull/18611. It will be released today in Jetpack 9.4!
