### ISSUE TITLE
Leaving the Customizer loads your primary site instead of the site you were last on

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#49568]
### Steps to reproduce the behavior

1. Go to WordPress.com admin area for a site _other than your primary site set in your account settings_.
2. Click on Appearance > Customize
3. Exit the Customizer
4. Note that instead of going back to the site you were working on, you're instead brought to your primary site

#### What I expected to happen
I expected to end up back in the site I originally came from

#### What actually happened
I was brought to my primary site, regardless of whether I was working on it

#### Browser / OS version
Chromium Version 87.0.664.75 (Official build) (64-bit)

Windows 10

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Just Atomic sites

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/16580129/106517702-d96bc700-64a6-11eb-999e-a308fe663c6d.png)

![image](https://user-images.githubusercontent.com/16580129/106517784-f4d6d200-64a6-11eb-93ce-1663546db1af.png)

![image](https://user-images.githubusercontent.com/16580129/106517842-07510b80-64a7-11eb-9819-9694652f6990.png)

**Comment by cpapazoglou** [comment]
When the customizer links to WP Admin it should  include a `return` query string
`/wp-admin/customize.php?return=[RETURN_URL]`

**Comment by galakhyati** [comment]
The same issue applies for Appearance > Header, Background, Widgets, Menu, Edit CSS, and AMP sections.

**Comment by getdave** [comment]
Is this an existing issue or one introduced by Nav Unification?

**Comment by cpapazoglou** [comment]
It's introduced by Nav Unification, prior to this feature a `return` query string was passed along `/wp-admin/customize.php?return=[RETURN_URL]`
