### ISSUE TITLE
Popover Cart: "Add a plan" button does nothing on Plans page

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49562]
### Steps to reproduce the behavior

1. Go to My Sites > Upgrades
2. Click on Cart
3. If any items are present, remove them
4. click on button labeled `Add a plan`

#### What I expected to happen
User is taken to the page listing plans available to them.

#### What actually happened
Nothing occurs if user is on tab labelled `Blogs and personal sites`.
If user is on tab labelled `Business sites and online stores`, the button takes user back to the `Blogs and personal sites` tab.

### Context
Casually using `wp-calypso`.

#### Browser / OS version
OS: macOS Catalina 10.15.7
Browser: Firefox Nightly 86.0a1

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Both.

#### Is there any console output or error text?
When the `Plans` page is loaded, the following error is in the console:
```
Uncaught (in promise) Error: Failed to load script "//stats.wp.com/w2.js?1"
    m https://wordpress.com/calypso/evergreen/92257.a9c2066c78b021411034.min.js:1
    s https://wordpress.com/calypso/evergreen/92257.a9c2066c78b021411034.min.js:1
    f https://wordpress.com/calypso/evergreen/92257.a9c2066c78b021411034.min.js:1
    ts https://wordpress.com/calypso/evergreen/92257.a9c2066c78b021411034.min.js:1
    b https://wordpress.com/plans/worldomonation579900575.wordpress.com:38
    js https://wordpress.com/calypso/evergreen/92257.a9c2066c78b021411034.min.js:1
    b https://wordpress.com/plans/worldomonation579900575.wordpress.com:38
    tsx https://wordpress.com/calypso/evergreen/entry-main.1701f5c41daafc92c339.min.js:2
    b https://wordpress.com/plans/worldomonation579900575.wordpress.com:38
    js https://wordpress.com/calypso/evergreen/entry-main.1701f5c41daafc92c339.min.js:2
    b https://wordpress.com/plans/worldomonation579900575.wordpress.com:38
    js https://wordpress.com/calypso/evergreen/entry-main.1701f5c41daafc92c339.min.js:2
    b https://wordpress.com/plans/worldomonation579900575.wordpress.com:38
    s https://wordpress.com/plans/worldomonation579900575.wordpress.com:38
    d https://wordpress.com/plans/worldomonation579900575.wordpress.com:38
    <anonymous> https://wordpress.com/calypso/evergreen/entry-main.1701f5c41daafc92c339.min.js:2
92257.a9c2066c78b021411034.min.js:1:130812
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Moderate - user has to manually select plan to add using the tabs present on page.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot 2021-02-01 at 11 57 10 AM](https://user-images.githubusercontent.com/6549265/106511173-b9c3a700-6484-11eb-9856-3f624ec0603e.png)

**Comment by worldomonation** [comment]
The title is *technically* incorrect as described in the `What I expected to happen` section in the issue description, but I believe it captures the reaction of a typical user when they click on the button and expecting it to take them to a plan listing page.

**Comment by michaeldcain** [comment]
@worldomonation: could you be a little more clear about what you'd expect to happen when clicking on "Add a plan"? That button is a link to the Plans page, which I believe you're already on. That page is a list of the plans available to the user.

At minimum, we should close the popover cart and probably remove the behavior that toggles from "Business sites and online stores" to "Blogs and personal sites", but there isn't currently a better list of plans available to the user.

**Comment by worldomonation** [comment]
> @worldomonation: could you be a little more clear about what you'd expect to happen when clicking on "Add a plan"? That button is a link to the Plans page, which I believe you're already on. That page is a list of the plans available to the user.

Some sort of visual feedback to the user to indicate that the button has already served its purpose (eg. take user to the plans page that they're already on) would improve the experience, I think. 

I took another quick look and it appears the Cart icon is only permanently shown on the Upgrades > Plans page. Upgrades > Purchases and Upgrades > Domains does not show the Cart icon, so unless I'm missing something the `Add a plan` button appears to take user to the page they were already on?

Coming at this fresh (haven't actively used WordPress.com for many years) I was left confused at this interaction.

> At minimum, we should close the popover cart and probably remove the behavior that toggles from "Business sites and online stores" to "Blogs and personal sites", but there isn't currently a better list of plans available to the user.

I agree that would be a better alternative.

**Comment by michaeldcain** [comment]
> Coming at this fresh (haven't actively used WordPress.com for many years) I was left confused at this interaction.

I really appreciate this perspective! I think that the popover cart used to be shown persistently on other screens (i.e. Domains), so the button made more sense originally. Let's start by removing the button from the empty popover cart on the Plans screen.

**Comment by sirbrillig** [comment]
If merged, https://github.com/Automattic/wp-calypso/pull/52890 will fix this (as we'll be able to remove the Popover cart).

**Comment by guarani** [comment]
Just noting that I ran into this issue (or a very similar issue) last week. I see from the above comment that this will be fixed pending a PR being merged, but just want to echo how the "Add a plan" button seemed unnecessary in the context I was in, where I was already on the Upgrades > Plans (Plans tab).

Also, in the scenario I was in, there were no "Blogs and personal sites" and "Business sites and online stores" tabs. See screenshot below for context:

<img width="1092" alt="Screen Shot 2021-06-18 at 12 47 32 (1)" src="https://user-images.githubusercontent.com/1898325/122806897-ec860480-d298-11eb-8c5e-10d73546488d.png">

**Comment by jjchrisdiehl** [comment]
Calypso portion of https://github.com/Automattic/wp-calypso/pull/52890 is now merged, this has removed the popover cart entirely. Considering this issue now closed.
