### ISSUE TITLE
Hitting back in checkout screen takes you all the way back to the beginning of site creation

### ISSUE THREAD

**Issue by yaelirub** [Automattic/wp-calypso#49565]
While building an empathy site for my sister https://pick2pic.com/ I picked the e-commerce plan and when I saw the final price I got nervous and wanted to go back and look at the plans again but when hitting back I was taken to the beginning of site creation, all the work I put in choosing designs and fonts gone. 

FYI - 
* As you can see in the video, you can hit back on other screens
* I went through the whole thing again and checked out so my site now has e-commerce plan
#### Steps to reproduce

1. Add a new site 
2. Choose a name, domain, designs, fonts, plan
3. On the checkout screen hit back
4. See that you have to begin site creation all over again

#### What I expected
I expected to be taken back to the plans screen

#### What happened instead
I was take back to the first screen and I had to start over *crying*

#### Browser / OS version
Chrome / Safari (updated)

#### Screenshot / Video

https://user-images.githubusercontent.com/1335657/106514186-c9dd8580-6488-11eb-9d7e-d03bbd7eb1ed.mov

**Comment by simison** [comment]
cc @razvanpapadopol

**Comment by simison** [comment]
This might be the case where we need something akin this — (it's from Godaddy):

<img width="896" alt="image" src="https://user-images.githubusercontent.com/87168/106515154-ea83fa80-64dd-11eb-8ce3-6453a746c33d.png">

**Comment by yaelirub** [comment]
Hey @simison , just out of curiousity, can we not just take them back to the plans page?

**Comment by razvanpapadopol** [comment]
By the time you get to the checkout page, your site has been created already so with the fix in https://github.com/Automattic/wp-calypso/pull/49567 we'll be redirecting you to Plans page in Calypso (same solution as in `/start` onboarding flow) if you press the Close / Back button on top-left.

This solution https://github.com/Automattic/wp-calypso/issues/49565#issuecomment-771141100 would fit perfectly in Gutenboarding and we can show that modal instead of automatically redirecting the user to their new site (which we were doing in https://github.com/Automattic/wp-calypso/pull/42030). 

cc: @ollierozdarz

**Comment by ramonjd** [comment]
I had a quick look today, trying to figure out what broke but ran out of time so I'm not sure it's definitive. 

The only way I could force the redirect to `/home/` (the purpose of https://github.com/Automattic/wp-calypso/pull/42030) was to skip the `isResolving()` [check here](https://github.com/Automattic/wp-calypso/blob/ed3e91545e431da92beeffcbe80289eadde067c0/client/landing/gutenboarding/index.tsx#L143)

We're fetching the site id and details fine, just resolving `undefined` in the `waitForSelectedSite()` promise.

Remember anything that would help @andrewserong ?

**Comment by andrewserong** [comment]
Thanks for the ping @ramonjd, unfortunately I don't have much to add, just that I can recreate the issue, and I'm not quite sure why the redirect to `/home` isn't working. Are we clearing the state more frequently than we used to?

I did notice that when I click back from the checkout, the selected site doesn't appear to be available for me locally (`wp.data.select( 'automattic/onboard' ).getSelectedSite();` seems to be returning undefined for me), not sure if that helps 🤔

**Comment by niranjan-uma-shankar** [comment]
Adding to the GoDaddy example, there's an earlier design exploration for such a modal in pb5gDS-xu-p2, in case that's useful to build on top of.

**Comment by simison** [comment]
I'll pull the screen here for convenience (still see the design convo in P2):

![106597113-9ff69280-655e-11eb-952b-6d713124ab81](https://user-images.githubusercontent.com/87168/106599412-b05c3c80-6561-11eb-8c7b-4d61dfa30489.png)

**Comment by yansern** [comment]
> the selected site doesn't appear to be available for me locally (wp.data.select( 'automattic/onboard' ).getSelectedSite(); seems to be returning undefined for me),

Apparently, `isResolving` is still returning `true` after the request to `getSelectedSite` is completed.  This causes the site object to exist for a split second, and then reassigned to `undefined` again. See PR fix at: https://github.com/Automattic/wp-calypso/pull/50327/files#diff-eeebf71992b542ec2bce9b1a975643c2e0ebe825fc439ed7784ac0491b8fd40fR131

PSA: While debugging this, I noticed that setting breakpoints on codes related to the flow of `wpcomRequest()` may cause the API request not to execute, or the response of the API request not to be processed. This caused me to go on a rabbit hole thinking there's something wrong with `wpcom-proxy-request`. I suspect this has something to do with `window.postMessage` executing on its freewill, ignoring the fact that you're actually frozen on a breakpoint. So do not use `debugger;` when debugging stuff that involves `wpcomRequest()`, use the classic `console.log` instead. Using `localStorage.setItem( 'debug', 'wpcom-proxy-request' );` helps as well, so you can see the debug log of `wpcomRequest()`.

**Comment by klimeryk** [comment]
cc @hambai, this might be worth syncing up on in relation to your work in p99Zz8-1D8-p2. The view that @simison shared above https://github.com/Automattic/wp-calypso/issues/49565#issuecomment-771585671 ideally could be re-used/shared between this and the add new domain flow, so that we have a consistent UX.

**Comment by razvanpapadopol** [comment]
With this bug fixed in #50327, we can close this issue and open a task for the modal mentioned in https://github.com/Automattic/wp-calypso/issues/49565#issuecomment-771585671 where @ollierozdarz @klimeryk and @Automattic/luna can coordinate on how to implement this UX improvement.

**Comment by ciampo** [comment]
> With this bug fixed in #50327, we can close this issue and open a task for the modal mentioned in [#49565 (comment)](https://github.com/Automattic/wp-calypso/issues/49565#issuecomment-771585671) where @ollierozdarz @klimeryk and @Automattic/luna can coordinate on how to implement this UX improvement.

As per the comment above, I opened #50435 to track the modal issue separately.
