### ISSUE TITLE
Scroll position of dashboard persists through to Account Settings page

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#49577]
### Steps to reproduce the behavior

1. Scroll down the dashboard page
2. Then click on Account Settings in the sidebar 
3. This should load the account page but the page is also scrolled down

#### What I expected to happen
I expected the Account page to load and scroll position to be reset to the top

#### What actually happened
Scroll position of Account page matches the position found on the previous page (dashboard)

#### Browser / OS version
Chromium Version 87.0.664.75 (Official build) (64-bit)

Windows 10

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![ScrollingThing](https://user-images.githubusercontent.com/16580129/106535616-a33d4000-64c4-11eb-892f-9b7faee6696c.gif)

**Comment by getdave** [comment]
Verified. Possibly related to https://github.com/Automattic/wp-calypso/issues/49175
