### ISSUE TITLE
Creating an account using Google results in 'an unexpected error occurred. Please try again later'

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49572]
### Steps to reproduce the behavior

Prereq. Log out of session in the browser.

1. Go to wordpress.com/start/user
2. Click on `Continue with Google`
3. In the pop-up window, complete the Google login process.
4. Once pop-up window closes, check the main window.

#### What I expected to happen
A WordPress.com account is successfully created.

#### What actually happened
On the account creation page, a toast stating `An unexpected error occurred. Please try again later` shows.
A WordPress.com account is not created.

### Context
Manual testing

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Browser: Version 14.0.2 (16610.3.7.1.9)

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
N/A

#### Is there any console output or error text?
Main window:
```
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored. (x4)
```

Pop-up window:
```
[Error] Unrecognized Content-Security-Policy directive 'worker-src'.

[Error] Invalid 'X-Frame-Options' header encountered when loading 'https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=888847203&timestamp=1612221360208': 'ALLOW-FROM https://accounts.google.com' is not a recognized directive. The header will be ignored.
```

Nothing abnormal in the Network or Console tab of the main window when the error toast is showing.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
High - prevents users from signing up using their Google account.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-02-01 at 3 07 44 PM](https://user-images.githubusercontent.com/6549265/106530143-9dcdfe80-64a0-11eb-9289-42b1a2e38916.png)

**Comment by worldomonation** [comment]
Addendum: Checked with proxy off, same behavior.

**Comment by cathymcbride** [comment]
Reproes in multiple browsers (safari and firefox so far) and toggling "Preferences > Privacy > Website Tracking" in safari has no effect.

**Comment by simison** [comment]
Being looked at p1612274114056300-slack-create-gardeners by @yansern

**Comment by yansern** [comment]
Where it failed was `this.props.initialContext.query.oauth2_redirect` is `undefined`. That is in `client/signup/steps/user/index.jsx` under `handleSocialResponse()`. 

This PR might be related https://github.com/Automattic/wp-calypso/pull/48855. cc @tyxla
