### ISSUE TITLE
CoBlocks: Upgrade to > 2.6

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#49592]
CoBlock is currently on 2.6. The next release should include a fix for:

- https://github.com/Automattic/wp-calypso/issues/45562

Upgrade the plugin on Simple when the next version has been released.

**Comment by davipontesblog** [comment]
Hi @sirreal , is there an ETA for this one? I am tracking the merge which can close https://github.com/Automattic/wp-calypso/issues/45562

Thanks!

**Comment by sirreal** [comment]
@WunderBart can you provide an update?

**Comment by WunderBart** [comment]
Thanks for the ping, @sirreal. @davipontesblog, I'm going to start the CoBlocks upgrade on Simple sites this week. We might need a couple of days for dealing with integration issues and running the CfT. I'd say the upgrade would likely happen later this- or early next week.

cc @fullofcaffeine @griffbrad

**Comment by WunderBart** [comment]
Closing this one as we're tracking v2.10 upgrade in of https://github.com/Automattic/wp-calypso/issues/51867.
