### ISSUE TITLE
Ensure Me account page alerts of unsaved settings if only a single form group has been saved.

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#49591]
Identified in https://github.com/Automattic/wp-calypso/pull/48710#pullrequestreview-580468956.

This was identified by @mmtr:

> I expect the alert warning about unsaved changes to show up if I have unsaved changes in any in the 2 forms. however,  if you have unsaved changes in both forms and save one of them, the alert is not displayed when exiting the page, although I have unsaved changes in the 2nd form 

### Steps to reproduce the behavior

1. Go to http://calypso.localhost:3000/me/account
2. Make changes in _both_ forms.
3. Only save _1_ group of fields (eg: Account or Interface).
4. Attempt reload the page or navigate away. 
5. You don't see a browser alert warning of unsaved changes.

#### What I expected to happen

Any time I try and leave with unsaved changes I should be prompted to check I really want to leave the page.

#### What actually happened

See above.

**Comment by mmtr** [comment]
This will be solved by https://github.com/Automattic/wp-calypso/pull/49760
