### ISSUE TITLE
Switch Site changes to Browse Sites on Feedback and Links pages

### ISSUE THREAD

**Issue by caimin-j** [Automattic/wp-calypso#49615]
### Steps to reproduce the behavior

1. Click Feedback or Links on left menu
2. Notice how "Switch Site" at the top left becomes "Browse Sites"

#### Browser / OS version
Chrome 88/Mac

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No 
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="233" alt="Screen Shot 2021-02-02 at 17 28 58" src="https://user-images.githubusercontent.com/37620825/106639585-05f21280-657d-11eb-8c37-be6de7248b7b.png">

**Comment by cpapazoglou** [comment]
That's expected. When navigating to a WPAdmin link you can no longer "Switch Sites" like you could in Calypso. Therefore "Browse Sites" which lands you to `https://wordpress.com/home` is more appropriate. Possibly, we will add the "Switch Sites" feature in WPAdmin in a future iteration but it is out of scope currently.
