### ISSUE TITLE
Customer home: no space between buttons on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49622]
### Steps to reproduce the behavior

1. Go to /home
1. See top card in mobile width

![Screenshot_20210202-222207_Firefox](https://user-images.githubusercontent.com/87168/106657937-4ebdc180-65a5-11eb-8aad-184c9e61c512.png)

There should be a bit of space here.

#### Browser / OS version
Android Firefox

**Comment by rodolfonei** [comment]
Hi! I would like to work on this issue if it is available

**Comment by bhairavee23** [comment]
Hi, I don't see a PR on this issue so working on it as my first issue. Let me know if anyone else is working

**Comment by autumnfjeld** [comment]
@bhairavee23 Howdy.  Are you still working on this? Could you link your PR if so?   Thank you!

**Comment by p-jackson** [comment]
I've submitted a fix for this #52708. Help with the review is very welcome!
