### ISSUE TITLE
Background image not showing in the editor for Cover blocks with the "fixed background" setting enabled

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#49624]
### Steps to reproduce the behavior

**Two ways to reproduce:**

1. Visit wp.com/new;
1. Select Rockfield or Leven design;
1. Click through to create site and view the home page in the editor;
1. Observe how the Cover block doesn't render the image.

**Or:**

1. Use any test simple site;
1. Add a Cover block, select a background image for it;
1. Select the Cover block, and in the settings, pane look for a "Media settings" section and enable the "Fixed background" setting;
1. Reload the page.

Interestingly enough, if you disable the setting and enable it again, the image will keep rendering without problems. However, if you enable it *and reload the page*, you'll see experience the issue again. **It seems the issue only happens upon the block's initialization and if this setting is on.**

**This issue is specific to the editor, the rendered block correctly shows the fixed image in the frontend.**

#### What I expected to happen

I expect the Cover block to correctly render the image in the editor when the background is set to "fixed".

#### What actually happened

The cover background image is not shown at all.

### Context

Reported here: p1612293981111800-slack-CRNF6A9DX
Possibly related: p1612249843408500-slack-C015AL3QL7M

#### Is this specific to the applied theme? Which one?

No.

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all simple sites / AT sites running GB 9.8.3 that use Cover block with the "Fixed background" setting enabled.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

| | | 
|-|-|
| ![image](https://user-images.githubusercontent.com/81248/106658729-417fe300-6563-11eb-858a-3232c6c7dbc0.png) | ![foooo](https://user-images.githubusercontent.com/81248/106659331-34172880-6564-11eb-868a-0bfb955ee920.png) |

**Comment by fullofcaffeine** [comment]
This happens on org sites with `v9.8.3`, too. Gutenberg issue: https://github.com/WordPress/gutenberg/issues/28678. **UPDATE**: latest `master` doesn't have this issue. See: https://github.com/WordPress/gutenberg/issues/28678#issuecomment-772201279. `9.9` will include the fix: https://github.com/WordPress/gutenberg/issues/28425#issuecomment-771747103.

**Comment by Nic-Sevic** [comment]
Additional report here but appears solved now; on Gutenberg 9.8.4: 
3704809-zen

**Comment by cathymcbride** [comment]
Not reproing on G9.9
