### ISSUE TITLE
Upsell Nudge: invalid prop type error

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#49620]
The following prop type warning is shown on the Business plan up-sell:

![106525911-59dff700-64aa-11eb-80e6-d8e01a3790b6](https://user-images.githubusercontent.com/942359/106652931-28c3fd00-6564-11eb-97e8-74da877937b2.png)

Upsell that causes the error:

![106526025-8431b480-64aa-11eb-94e6-7327b60f9352](https://user-images.githubusercontent.com/942359/106652953-311c3800-6564-11eb-90a6-801b4d948d49.png)

@Automattic/martech @Automattic/martech-decepticons

**Comment by niranjan-uma-shankar** [comment]
@michaeldcain I no longer see this error. Could you please confirm?

**Comment by michaeldcain** [comment]
Confirmed. It might've been cleaned up by some of @sirbrillig's refactoring since the original report.
