### ISSUE TITLE
Purchases menu item selected state is deselected after clicking on a single purchase

### ISSUE THREAD

**Issue by deancroyal** [Automattic/wp-calypso#49631]
### Steps to reproduce the behavior

1. Go to 'My Profile'. (https://wordpress.com/me)
2. Click on 'Purchases' menu item.
3. Purchases menu item will show as selected.
4. Click on any purchase listed to the right of the menu.
5. See the Purchases menu item becomes de-selected.

#### What I expected to happen
I expected the Purchases menu item to stay selected while viewing details of any specific purchase.

#### What actually happened
The Purchases menu item was de-selected after clicking on any purchase to view its details.

#### Browser / OS version
Google Chrome Version 87.0.4280.141 (Official Build) (x86_64) / Mac OS Big Sur Version 11.1 (20C69)

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

In the screen below, Purchases is selected, my intention is to view the details of my Premium Plan purchase.

<img width="400" alt="Screen Shot 2021-02-02 at 15 00 36" src="https://user-images.githubusercontent.com/13387217/106675309-ca018200-6569-11eb-9af6-18a569135086.png">

When I arrive at the details of my Premium Plan purchase, Purchases in the menu becomes deselected.

<img width="400" alt="Screen Shot 2021-02-02 at 15 02 16" src="https://user-images.githubusercontent.com/13387217/106675501-09c86980-656a-11eb-83dc-32790e26269e.png">

**Comment by obenland** [comment]
This is probably closely related to https://github.com/Automattic/wp-calypso/issues/49310. Probably not duplicates but might be fixable with the same solution.

**Comment by obenland** [comment]
#50318 should have laid the groundwork to fix this one as well.

**Comment by cpapazoglou** [comment]
FWIW, this is not nav-unification related. **Me** section uses an other `sidebar` component which has it's unique logic for picking the selected menu item
https://github.com/Automattic/wp-calypso/blob/ce3d141a33cc033518100647a77f24a5b344f7bc/client/me/sidebar/index.jsx#L78-L99

Specific Purchases `/me/purchases/[DOMAIN]/[ID]` are missing from the `filterMap`. Also, `/me/purchases/payment-methods` are missing. We could probably utilize #50318 to clean up the code and remove the static `filterMap`.
