### ISSUE TITLE
'Update' button is misspelled in Korean language  

### ISSUE THREAD

**Issue by brookewp** [Automattic/wp-calypso#49636]
### Steps to reproduce the behavior

1. Change language to Korean
2. View existing page/post
3. See 'Update' button is misspelled 

#### What I expected to happen

'Update' should be 업데이트하기  (like it is in WordPress core), instead of 업대이트하기

The correct spelling should use 데 instead of 대

#### Screenshot 

Calypso version: 

<img width="423" alt="Screen Shot 2021-02-02 at 3 37 24 PM" src="https://user-images.githubusercontent.com/35543432/106681391-3b92fd80-6575-11eb-8fec-986ef25fb779.png">

**Comment by michaeldcain** [comment]
@Automattic/i18n

**Comment by dlind1** [comment]
Several translations in Gutenberg are using 업대이트하기 (see [here](https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/ko/default/?filters%5Bterm%5D=%EC%97%85%EB%8C%80%EC%9D%B4%ED%8A%B8%ED%95%98%EA%B8%B0&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)) and the correct translation is in waiting status ([here](https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/ko/default/?filters%5Bterm%5D=%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8%ED%95%98%EA%B8%B0&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)). So it should be just a matter of approving the waiting translation (and possibly fixing the others if they should be adjusted).

**Comment by akirk** [comment]
I've pinged the [Korean GTE](https://make.wordpress.org/polyglots/teams/?locale=ko_KR) on Slack and now 업데이트하기 has been approved. The new translation has been deployed but we'll have to wait for the next Calypso deploy for it to go live.

**Comment by yuliyan** [comment]
Closing the issue as it seem the correct translation is currently being used:
![CleanShot 2021-08-04 at 15 46 03](https://user-images.githubusercontent.com/2722412/128183127-769ae8c1-c401-4484-92c0-2884dedd6cfb.png)
