### ISSUE TITLE
Focused Launch: Summary view visual glitches for some locales

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49635]
**Note: We can close this once the next ETK is released**

When opening Focused Launch as a user with a locale such as DE, longer texts are causing UI to break:
* Launch button should expand or go on 2 lines
* Side-quotes checkmarks size should be consistent

#### Acceptance criteria

* [x] Checkmarks don't scale 
* [x] The button is large enough to display its copy (in verbose languages)

#### Pull requests
* #49758 -> Merged and deployed.
* #49765 -> Merged and deployed.

#### Current situation
<img width="1119" alt="Screenshot 2021-02-02 at 10 27 18" src="https://user-images.githubusercontent.com/14192054/106679371-2d6ccd80-65c5-11eb-8650-1dea4029a9ea.png">

**Comment by ciampo** [comment]
Closing as the related changes have been been released with ETK 2.18 and ETK 2.19
