### ISSUE TITLE
Reusable blocks: block width reverts to default size when converted to reusable block

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49640]
### Steps to reproduce the behavior

1. Create post.
2. Insert a block that supports Full/Wide width (eg. Image block. Tiled Gallery block)
3. Set block to Wide width.
4. click Toolbar > Hamburger Menu > Add to Reusable Blocks

#### What I expected to happen
When reusable block is created, block(s) that are converted retain the width set in Step 3.

#### What actually happened
Turning into reusable block forces target block(s) width to revert to the default size (when inserted on editor).
These blocks do not support width wider than the default size despite Wide/Full width options being present.

### Context
User scenario manual testing, back to basics.

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Browser: Firefox Nightly 87.0a1
Browser: Safari Version 14.0.2 (16610.3.7.1.9)

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Both.

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/6549265/106685687-c546c900-657d-11eb-83a0-48fa997aa581.mov

https://user-images.githubusercontent.com/6549265/106685738-de4f7a00-657d-11eb-9146-8da39321167a.mov

**Comment by simison** [comment]
cc @Automattic/good-mountain Gutenberg upgrade issue?

**Comment by sirreal** [comment]
@WunderBart is going to investigate this.

**Comment by WunderBart** [comment]
@simison @sirreal this is a [known issue](https://github.com/WordPress/gutenberg/issues/28024) that is being discussed in https://github.com/WordPress/gutenberg/issues/17640.

Closing in favor of https://github.com/WordPress/gutenberg/issues/17640.
/cc @talldan
