### ISSUE TITLE
Navigation Block not showing on site

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/wp-calypso#49666]
### Steps to reproduce the behavior

1. Add Navigation Block to your page (with some links)
2. In editor the Navigation Block shows normally
3. Check your live site, Navigation Block menu is not showing. 

### Context
It seems that the Navigation Block code does not parse in the browser correctly. 

#### Browser / OS version
Chrome / Version 88.0.4324.96 (Official Build) (x86_64)
Safari / Version 14.0.2 (16610.3.7.1.9)

#### Is this specific to the applied theme? Which one?
No, seems to be happening with all themes (checked 4 for now - Seedlet, Hever, Coutoire, Floral)

#### Does this happen on simple or atomic sites or both?
Had a user on Simple and tested myself on Atomic

#### Is there any console output or error text?
No error

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Code in the editor. 
```
<!-- wp:navigation {"orientation":"horizontal","textColor":"primary","itemsJustification":"center","align":"wide","style":{"typography":{"fontSize":"20px"}}} -->
<!-- wp:navigation-link {"label":"Home","type":"category","id":400,"url":"###"} /-->
<!-- wp:navigation-link {"label":"Create + Educate","type":"category","id":711773273,"url":"###"} /-->
<!-- wp:navigation-link {"label":"Well Being","type":"category","id":82347,"url":"###"} /-->
<!-- wp:navigation-link {"label":"Maag Blog","type":"category","id":713240187,"url":"###/"} /-->
<!-- /wp:navigation -->
```

Code screenshot form the site/console.
![Screen Shot 2021-02-03 at 16 59 20](https://user-images.githubusercontent.com/71094068/106774993-60f23b00-664b-11eb-8d54-f4e9726dc621.png)

**Comment by simison** [comment]
cc @Automattic/good-mountain related to GB release?

**Comment by fullofcaffeine** [comment]
> cc @Automattic/good-mountain related to GB release?

**Comment by fullofcaffeine** [comment]
> cc @Automattic/good-mountain related to GB release?

We don't know yet, trying to figure it out now.

_EDIT: Apologies, I closed the issue by accident._

**Comment by fullofcaffeine** [comment]
See discussion here: p1612367245467800-slack-C015AL3QL7M.

**Comment by fullofcaffeine** [comment]
Related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/28712.

**Comment by mrsjaved** [comment]
Another similar issue 3752310-zd-woothemes 

In my case, it does not show or parse the menu when we add category links. In the editor, it displays the menu but not when you preview the live page. 

It does not add the category link automatically. Screenshot -> https://d.pr/i/3agl8Y/iOkf7zwCZW

However, when we click on the category title and click the link anchor on the top toolbar I can see the link. Screenshot -> https://d.pr/i/kuZZ0a/lwJ6MxlUda

**Comment by devNigel** [comment]
Another similar issue as reported by @mrsjaved 

As a workaround, I suggested adding Link instead of Category Links in the Navigation Block.

User report: 27966991-hc

**Comment by happychait** [comment]
Another user encountered this in 3780773-zen

**Comment by ciampo** [comment]
Hey @fullofcaffeine , can this issue be closed?

**Comment by noahtallen** [comment]
I just tested the nav block, and it appears to work in the editor and front end for pages. So I think this is resolved now :)
