### ISSUE TITLE
Gutenboarding: tt1-blocks is dropping some styles on Gutenberg edge 

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#49667]
On a site without the `gutenberg-edge` sticker:

![image](https://user-images.githubusercontent.com/195089/106776447-b0b01280-6609-11eb-9552-2f106eb58780.png)

With the `gutenberg-edge` sticker:

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/195089/106778467-a0009c00-660b-11eb-8c15-e80b3ca3b535.png">
(The "template part deleted or unavailable" is a separate issue)

@nosolosw is this possibly related to `theme.json` work like https://github.com/WordPress/gutenberg/pull/28110 ?

**Comment by oandregal** [comment]
:wave: I'm not sure I'm the best person to offer feedback on this: don't know the details of what's shipped in WordPress.com and so on. This is what I know, hope it's useful:

- TT1-blocks has been refactored to work with the latest changes to theme.json https://github.com/WordPress/theme-experiments/pull/182/
- I don't think those changes have been pushed to the WordPress theme repository. They require Gutenberg 9.9 which hasn't been released yet. It should be before the end of this week, not sure about the details.

**Comment by mattwiebe** [comment]
What you know is more than I did, thanks! 🙌

**Comment by mattwiebe** [comment]
Closing this, as the source has been discovered and a fix in progress: https://github.com/WordPress/gutenberg/pull/28731
