### ISSUE TITLE
New onboarding: no whitespace under "feature list" on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49669]
### Steps to reproduce the behavior

1. Go to `/new` onboarding flow
2. Proceed to feature picker
3. Scroll all the way down
4. No empty space before buttons:

    ![image](https://user-images.githubusercontent.com/87168/106780563-cf85c780-6650-11eb-8e05-74756fc5830e.png)

Firefox on mobile emulation.

**Comment by Aurorum** [comment]
PR for this issue in #49709. :)

**Comment by yansern** [comment]
In the future, it might be worth considering standardizing footer padding across different viewport.

Mixins like `@mixin onboarding-block-margin` and `@mixin onboarding-body-margin` only catered for left & right margins, while top margin was decided by heading, and bottom margin is decided by each step's individual stylesheet.

A mixin to streamline all vertical (top/left) margins across multiple breakpoints across different steps will be useful.

Anyhow, this is not a blocker for PR #49709. Thanks @Aurorum!
