### ISSUE TITLE
New onboarding: Cover blocks aren't full width in Editor of created site

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49673]
### Steps to reproduce the behavior

1. Go to `/new`
2. On design step choose "Gibbs" it looks ok on preview:
   
    <img width="1287" alt="image" src="https://user-images.githubusercontent.com/87168/106789276-bd108b80-665a-11eb-98c1-253c09a55362.png">

    <img width="1535" alt="Screenshot 2021-02-03 at 19 49 46" src="https://user-images.githubusercontent.com/87168/106788225-5b9bed00-6659-11eb-8414-ddaa3ac03b12.png">

3. Click through to create free site
4. Land in editor and see narrow cover block:
    <img width="1879" alt="Screenshot 2021-02-03 at 19 50 09" src="https://user-images.githubusercontent.com/87168/106788244-60f93780-6659-11eb-98cd-0bc5a9eb3f7e.png">

5. I need to manually fix it from toolbar:
    <img width="1602" alt="Screenshot 2021-02-03 at 19 50 25" src="https://user-images.githubusercontent.com/87168/106788272-69ea0900-6659-11eb-8c99-cf8601d1d8ad.png">

**Note:** This can also be reproduced with Cassel and Barnsbury as shown in the comments below.

Using Firefox. Plugins:

Gutenberg: v9.8.3
CoBlocks: 2.5.3
Editing Toolkit: 521216583

cc @Automattic/good-mountain also Gutenberg plugin update issue, similarly to https://github.com/Automattic/wp-calypso/issues/49624?

**Comment by ianstewart** [comment]
Reproduced in Chrome browser just now with the same steps above.

**Comment by ianstewart** [comment]
It's not limited to Gibbs but inclusive of Barnsbury as well.

![image](https://user-images.githubusercontent.com/545779/106805560-76a43800-662c-11eb-8cc6-ebaba94a9e38.png)

**Comment by ianstewart** [comment]
And in Cassel.

![image](https://user-images.githubusercontent.com/545779/106806074-195cb680-662d-11eb-8534-a4493df1d570.png)

Updating issue title and description …

**Comment by sirreal** [comment]
Filed https://github.com/WordPress/gutenberg/pull/28796 for upstream fix.
Simple hotfix: r220611-wpcom

**Comment by WunderBart** [comment]
Upstream fix included in v9.9.2, already live on Simple and Atomic sites.
