### ISSUE TITLE
Design Picker: Jetpack Subscription form not rendering correctly in newly created sites

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49678]
To reproduce …

1. Visit WP.com/new
2. Select "Bowen" or "Edison" design in flow
3. Proceed to editor
4. See error recorded in screenshot below

Bowen

![image](https://user-images.githubusercontent.com/545779/106803736-20ce9080-662a-11eb-9fb9-af03f7d31ef3.png)

Edison

![image](https://user-images.githubusercontent.com/545779/106806889-1dd59f00-662e-11eb-8da2-d26c0258d26a.png)

**Comment by p-jackson** [comment]
Edison and Bowen source sites fixed and updating annotation here: D56462-code

**Comment by p-jackson** [comment]
The button text has changed from “Subscribe” to “Follow”, and I can’t seem to update it; `edit.js` seems to think the default text is “Subscribe” and `save.js` seems to think it’s “Follow”.

Before fix:
<img width="431" alt="Screenshot 2021-02-04 at 2 05 29 PM" src="https://user-images.githubusercontent.com/1500769/106833109-d9aed100-66f7-11eb-99c5-cf88f13c50ba.png">

After fix:
<img width="431" alt="Screenshot 2021-02-04 at 2 31 09 PM" src="https://user-images.githubusercontent.com/1500769/106833121-e03d4880-66f7-11eb-9013-def2070b1b39.png">

Seems like a Jetpack bug. This is better than having a broken block after creating a new site though.

**Comment by p-jackson** [comment]
Looks like the subscribe/follow difference is by design, h/t @andrewserong p1612383354077500-slack-C013QHLF2

The defaults are different on wpcom and wporg
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/subscriptions/views.php#L658

**Comment by andrewserong** [comment]
Added an issue for the difference between the editor and front-end here for tracking in Jetpack: https://github.com/Automattic/jetpack/issues/18704

**Comment by p-jackson** [comment]
Bug about a potential missing migration in Jetpack that caused the issue: Automattic/jetpack#18706
