### ISSUE TITLE
Importers: Allow import from WordPress.com sites via URL

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#49675]
It would also be great if I could copy/paste a WordPress.com site using the new migration tool. Currently, we see the error below: `This site is already hosted on WordPress.com`

**What**
Allow importing from WordPress.com sites by pasting their URL, just like it happens for externally hosted sites. Possible case scenarios:

- A user wants to create another site for another language they support
- A company wants to test a new layout before putting it live
- A friend wants to use a template they already built on another site

**Why**
It would take fewer steps for a user to move content from sites that are already hosted on WordPress.com

**How**
![](https://d.pr/i/CIZzDB+)
_Link: https://d.pr/i/CIZzDB_

**Additional context**
Posting here as a feature request following this comment pbkcP4-d2-p2#comment-740 and I'm also blatantly copying @eduardozulian idea (thanks for posting it in the first place)

**Comment by nagpai** [comment]
Related: 
https://github.com/Automattic/wp-calypso/issues/51076

**Comment by kosiew** [comment]
Hi @zdenys ,

Thanks for reporting this and advocating for the Customer !

Triaging for developers' further investigation.

**Comment by kuropixel** [comment]
User could benefit from this feature. 35966478-hc.

**Comment by essleeung** [comment]
36104661-hc 
This would have been helpful for this user.
