### ISSUE TITLE
New Onboarding: Language picker breaks navigation from Plans/Domains modals

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49679]
**Hint:** As a quick fix, see #49681 where we remove the language picker button from existing modals (Plans Modal and Domains Modal)

### Steps to reproduce the behavior

1. Go to wordpress.com/new/design
2. Click on Plans Button in the header. Plans selection modal will open
3. Click on _Site language [EN]_ button. Language picker modal will open
4. Go back to the Plans selection modal
5. Try closing the modal

#### What I expected to happen
I should land on the previous step in the onboarding (Design selection in this case)

#### What actually happened
I landed on the Language picker modal

### Context
Related: #49360

#### Video
https://cloudup.com/cAJAiCikLIe

**Comment by simison** [comment]
I lowered priority — there are some bugs in other features instead and since we can just avoid the feature being live for now, it's not urgent to fix it.

**Comment by razvanpapadopol** [comment]
This issue was fixed by removing the Language picker button from Modals in https://github.com/Automattic/wp-calypso/pull/49681 

An improved route handling should be added when fixing https://github.com/Automattic/wp-calypso/issues/49360
