### ISSUE TITLE
Nav Unification: CSS provided icons are not supported in Calyspo

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49682]
When a plugin uses CSS (custom fonts, etc.) to style their menu icons, they do not display properly in Calypso. WooCommerce is one such plugin that does this (in order to get WooCommerce working with Nav Unification currently, see 577-gh-Automattic/wpcomsh#issuecomment-771947625). You can see this with the WooCommerce icon and the Products icon.

![CSS Menu Icons](https://user-images.githubusercontent.com/2098816/106806582-229e5100-6636-11eb-9cb5-ae2ca97569aa.png)

#### What I expected to happen

Icon to show properly in Calypso.

#### What actually happened

Generic icon was shown.

**Comment by obenland** [comment]
I don't think we'll be able to get those kinds of icons into Calypso. There's just not a good way (that I can think of) to get those styles applied in Calypso.

If the font approach is not something that folks feel super strongly about, an SVG is probably the most portable way for custom menu item icons.

**Comment by mattsherman** [comment]
> If the font approach is not something that folks feel super strongly about, an SVG is probably the most portable way for custom menu item icons.

For WooCommerce, I think we'd be okay with switching to SVGs, as long as https://github.com/Automattic/wp-calypso/issues/49145 is addressed. Of course, we wouldn't get the correct icons until we released a new version of WooCommerce (or, implemented a workaround in Calypso just to patch things up until it was included in a WooCommerce release), but I think that would be an acceptable limitation for the short term.

**Comment by obenland** [comment]
Closing in favor of #49145.
