### ISSUE TITLE
Navigation Block: Social Icons added to navigation appear stretched

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#49703]
### Steps to reproduce the behavior

1. Add Social Icons next to links in the Navigation block

#### What I expected to happen

- Social Icons would show in the correct shape/size

#### What actually happened

- Social icons background was stretched vertically on the Small and Normal size

### Context

Here is a comparison of the Social Icons block in the Navigation block and outside of the block:

<img width="1092" alt="Markup 2021-02-04 at 08 06 15" src="https://user-images.githubusercontent.com/51966986/106866133-01844180-66c4-11eb-9400-6d4bd5338d02.png">

In the browser: 

<img width="1378" alt="Markup 2021-02-04 at 08 35 44" src="https://user-images.githubusercontent.com/51966986/106866322-38f2ee00-66c4-11eb-89ec-e686500234e9.png">

#### Browser / OS version

Firefox 85 on macOS (Big Sur)

#### Is this specific to the applied theme? Which one?

Blank canvas theme

#### Does this happen on simple or atomic sites or both?

Tested on simple site

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to reproduce this issue but was unsuccessful:

```
Gutenberg: v11.6.0
CoBlocks: 2.10.1
Editing Toolkit: 3.16100
WP AMP: 2.0.5
```

1. start new post.
2. insert `Navigation` block.
3. insert existing menu.
4. add `Social Icons` block.
5. add multiple social icons.

If this issue should remain open, please feel free to re-open this bug.

![Screen Shot 2021-10-04 at 4 21 01 PM](https://user-images.githubusercontent.com/6549265/135937368-51307099-987d-41cb-a801-86653a40fb1c.png)
