### ISSUE TITLE
Blog Posts Block: Choose Specific Posts Endpoint Broken

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#49707]
**Describe the bug**

When one toggles on _Choose Specific Posts_ and starts searching a post in the _Posts_ field, then there will only be a loading icon and no results are being shown. 

**To Reproduce**
1. Go to My Site -> Site -> Posts -> Add New Post/Page
2. Click on + icon to insert the Blog Posts block
3. In the sidebar settings toggle on the _Choose Specific Posts_ option
4. Start searching for a published post on your site and see that no results will be returned. 

**Screenshots**

![blog-posts-block-error](https://user-images.githubusercontent.com/12064241/106875227-1cb07a80-66df-11eb-9ca2-c9c85a066afd.PNG)

**Expected behavior**

To see results returned so that posts could be chosen for the specific post/page.

---

@sirreal Did some digging and found this:

This broke it: https://github.com/Automattic/newspack-blocks/pull/661
By making this new endpoint stable (not experimental): https://github.com/Automattic/newspack-blocks/pull/556

**Comment by sirreal** [comment]
I started work in D56480-code, but I'm going to leave this for @Automattic/newspack folks who are familiar with these changes.

**Comment by jeffersonrabb** [comment]
I suspect all we need is to replicate [this fix](https://github.com/Automattic/newspack-blocks/pull/677) for `newspack-blocks/v1/specific-posts`. @dkoo is this accurate?

**Comment by rachelwinspear** [comment]
Also reported here: #3711457-zen

**Comment by TeniCola** [comment]
Also reported here: 3712385-zen

User updates this block setting regularly and would like an update once fixed, so placing that ticket on hold

**Comment by dkoo** [comment]
> I suspect all we need is to replicate this fix for newspack-blocks/v1/specific-posts. @dkoo is this accurate?

That's correct—I'm working on a fix and expect to push a release to the source plugin today.

EDIT: Fix is here: https://github.com/Automattic/newspack-blocks/pull/689

Will be released later today, then we'll have to update the ETK plugin to pull down the fix.

**Comment by geekinthegirl** [comment]
One more here: 2607392-hc

But I'll follow up to let them know a fix is on the way.

**Comment by rachelwinspear** [comment]
Also reported here: #24841148-hc

**Comment by kingsleyinfo** [comment]
Also reported here:  21875814-hc

**Comment by benchilcote** [comment]
Reported here: #8129364-hc
Follow-up #3710890-zen

**Comment by kcswong** [comment]
Reported: 27536286-hc
Follow-up: 3715480-zen

**Comment by tbradsha** [comment]
Chat: 27065396-hc
Ticket: 3715924-zen

Edit: notified user that it's working again.

**Comment by noahtallen** [comment]
We've merged a fix for this and are planning to deploy it on Monday.

**Comment by kmrpankaj** [comment]
Also reported here 3713858-zen

**Comment by benchilcote** [comment]
Reported 3712700-zen

**Comment by eoinsav** [comment]
3715621-zen

**Comment by jenlynnemc** [comment]
Reported here 3719221-zen

**Comment by kaitohm** [comment]
Another case here: 3717490-zd-woothemes (report pbEMJv-x8-p2)

**Comment by ahmadbaig1** [comment]
Reported here as well- 3719525-zen 
I've let them know this should be fixed by tomorrow.

**Comment by poojashetty18** [comment]
Chat: 13838899-hc
Ticket: 3721491-zen

**Comment by TeniCola** [comment]
Another report, 27578067-hc

**Comment by noahtallen** [comment]
This should be resolved in production now, thanks for your patience!
