### ISSUE TITLE
Focused Launch - Summary View: Prices jump from monthly to yearly after selecting a free plan

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#49713]
If the user has a monthly plan selected in the summary view and then clicks on the free plan, the price of the plans above jump from monthly to annually while staying in the summary view.

#### Acceptance criteria
* [ ] The list of plans in the summary view (either monthly or annually) remains the same after selecting a free plan.

#### Expected behavior
When the user selects a Free plan after selecting a Monthly plan, I expect the prices of the paid plans in the summary view not to change (to annually billed plans). 

#### What actually happened
https://www.loom.com/share/611f316948594d3e894f1d6b7ed997d2

**Comment by ciampo** [comment]
cc @razvanpapadopol and @ollierozdarz  (although not a blocker for MVP)

**Comment by ollierozdarz** [comment]
@StefanNieuwenhuis @ciampo yeah, this is what I'd expect too.

If there technically **has** to be a delay pulling the updated price data back into the summary page, we could always use the grey skeleton loading state for the prices while they update?

**Comment by razvanpapadopol** [comment]
By reading the **Expected behavior** section I understand the suggested solution is to keep showing monthly prices if the previously selected plan (before selecting Free Plan) was monthly. Changing the billing period from monthly to annual without the user explicitly requesting that may be confusing regardless of the jump/placeholder.

**Comment by ciampo** [comment]
Yes, @razvanpapadopol, that is the issue we're wanted to surface — basically, if the free plan is selected in summary view while displaying monthly prices, we should keep displaying monthly prices (instead of jumping to annually).

There won't be a delay necessarily, it's more of a "logic" issue
