### ISSUE TITLE
Two Headers Seen on Old Version of FSE

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#49717]
Reported by @yashitamittal11: 
"They have two headers added to the page. They want to remove one of the headers. When I try to edit the first header, I don't see the full contents. I only see the contents of the second header.
I am not sure why there are two headers on the page and how to remove the first one."

GIF: https://d.pr/v/KLI2Ul
3710570-zen
Site: pearsonpottery.com.au

**Comment by vindl** [comment]
The first issue with two headers was solved by changing the title of Footer template part to the default value (it was edited to "Header" by mistake).

The second was which caused the footer to always be loaded for editing was solved in D56520-code by @Addison-Stavlo.
