### ISSUE TITLE
Other Site Subscriptions: redirect to subscription list after removal

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#49720]
When you delete a subscription to another site, we keep you on an empty page after it's been removed. Let's take folks back to the purchases tab after the subscription deletes.

![membership-removal](https://user-images.githubusercontent.com/942359/106923957-9a26bb80-66dc-11eb-9b97-4759ae30c9d1.gif)

**Comment by TheMukhtarAhmed** [comment]
Hey @michaeldcain I would love to work on this issue can you please share the steps to reproduce this behavior?
