### ISSUE TITLE
Comments: comment link leads to site root

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#4975]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/jeremy.hu (Jetpack site)
2. I clicked on the comment icon on one of my posts.
3. I left a comment.
4. A few seconds later, a link appeared to allow me to view the comment on my site.
5. That link pointed me to `http://jeremy.hu`:

![screen shot 2016-04-23 at 9 56 23 pm](https://cloud.githubusercontent.com/assets/426388/14763720/468a90b4-099e-11e6-8b84-c1fd58010111.png)

- My site doesn't use HTTP.
- I expected to be directed to the post's link, with the comment anchor.

**Comment by lancewillett** [comment]
@jeherve I think that URL is pulling directly from your contact info in your WordPress.com profile — it's not generated by Calypso. Check `Website` under your user settings to add the HTTPS.

**Comment by lancewillett** [comment]
Can you also confirm that `3m ago` links to the correct permalink?

**Comment by lancewillett** [comment]
I think this is working as expected — there should be two links:

1. Commenter's username, linking to their `Website` link in their user profile.
2. Comment permalink, which is the "time ago" text.

(Feel free to re-open if I'm incorrect here.)

**Comment by jeherve** [comment]
Yes, you're right, my mad.

I should however point out that I find this very confusing:

1. I had understood that the commenter's name would link to their website, but I expected the icon on the right of the commenter's name to link to the comment.
2. I also didn't know `3m ago` would be a link at first, since it's greyed out.
3. When I moved my mouse over `3m ago`, both the icon on the right of the commenter's name and  `3m ago` changed colors, leading me to believe both items were the same link.

**Comment by lancewillett** [comment]
Good UX notes, thanks Jeremy — CC @mtias for notes on next iteration on comments in posts list.
