### ISSUE TITLE
Customizer: "did not load correctly" layout does not account for sidebar

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4976]
When attempting to load the customizer at `/customize/jnylen0.wordpress.com?nomuse=1`, I get "Sorry, the customizing tools did not load correctly".  This page is also not laid out correctly to account for the fixed sidebar:

![image](https://cloud.githubusercontent.com/assets/227022/14763929/617a8f4c-096b-11e6-86e0-5e599d5b4c7e.png)

**Comment by sirbrillig** [comment]
This is happening because the content area (`div.wp`) has the `has-no-sidebar` class. Can you try it with #4996?
