### ISSUE TITLE
Help FAB should show "close" icon when open

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49764]
When I open help FAB popover, the icon stays the same:

<img width="395" alt="Screenshot 2021-02-05 at 14 22 50" src="https://user-images.githubusercontent.com/87168/107033488-088f7a80-67be-11eb-90a0-83ac19ac037d.png">

It'd be clearer if it changed to "x" indicating that re-clicking it closes the modal:

<img width="341" alt="Screenshot 2021-02-05 at 14 51 55" src="https://user-images.githubusercontent.com/87168/107036219-eef03200-67c1-11eb-9b7f-6bb332f06bd0.png">

Using "cross" or "small-cross" might work here: https://automattic.github.io/gridicons/

**Comment by Aurorum** [comment]
PR for this issue in #49768. :)
