### ISSUE TITLE
Nav Unification: Site Editor is no longer pointing to Calypso

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#49776]
Prior to Nav Unification, the Site Editor menu item in Calypso's sidebar was linking to `/site-editor` route. After the switch this has changed to `wp-admin` link, which circumvents our Calypso integration.

For context here is the Calypso code were we previously introduced that button: https://github.com/Automattic/wp-calypso/blob/3cb4af1850a6b3c7b24b6fe13801ef00930b3984/client/my-sites/sidebar/index.jsx#L500-L507

That button is no longer shown and is replaced with wp-admin variant that points to incorrect URL. I think we need similar handling for it as we do for Posts or Pages for example.

Related issue: https://href.li/?https://github.com/Automattic/wp-calypso/issues/49350

cc @obenland @getdave @Addison-Stavlo

**Comment by getdave** [comment]
Thanks for flagging. 

Essentially we now build the Calypso menu based on the admin menu generated by WPAdmin. The only thing is we customise the WPAdmin menu on a per-env basis to include particular links we need for WPCom.

Therefore you could use the established core methods to register your own admin menu item and it will be pulled over to Calypso. However, it would need to happen before Jetpack is loaded in order that it can be processed by [the menu builder classes that reside in the Jetpack Plugin](https://github.com/Automattic/jetpack/tree/a8bc54da36bc59c4b23e40ca4fafe21d13240cbb/projects/plugins/jetpack/modules/masterbar/admin-menu).

For reference here is how Woo are registering a custom menu item 594-gh-Automattic/wpcomsh/files. Not that WPCOMSH is an MU Plugin so will run before Jetpack.

As the infrastructure is in place for you to resolve this, I would rather not take this task into Ajax's Nav Unification backlog (which is already huge!). However, please do feel free to reach out in `#ajax` if you need additional support or if you can't get things working. We appreciate your understanding.

**Comment by vindl** [comment]
> As the infrastructure is in place for you to resolve this, I would rather not take this task into Ajax's Nav Unification backlog (which is already huge!). However, please do feel free to reach out in #ajax if you need additional support or if you can't get things working. We appreciate your understanding.

Thanks for the pointers! Cylon will handle this one in that case.

**Comment by getdave** [comment]
@vindl See new documentation at PCYsg-v8B-p2#how-to-customise-the-menu
