### ISSUE TITLE
Nav Unification: Customer modal is using incorrect images

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#49771]
**What**
For the nav unification customer modal, we are using the incorrect images. Please find the correct ones here: [IMG.zip](https://github.com/Automattic/wp-calypso/files/5932960/IMG.zip)

**Acceptance criteria**
* Should the user visit Calypso and see the customer modal. They should see the images in the attached [IMG.zip](https://github.com/Automattic/wp-calypso/files/5932960/IMG.zip) file.

**Comment by Aurorum** [comment]
PR for this issue in #49827! :>
