### ISSUE TITLE
Coming Soon: WooCommerce Store notice displayed

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#49794]
### Steps to reproduce the behavior

1. On an Atomic site, enable the WooCommerce store notice ([steps to enable it here](https://docs.woocommerce.com/document/woocommerce-customizer/))
2. Set the site to Private (Manage > Settings). 
3. Visit the site not logged in. 
4. Check the Coming Soon page and see that the store notice is displayed.

#### What I expected to happen

The store notice should be hidden.

#### What actually happened

The store notice was shown.

#### Browser / OS version

All browsers.

Mac OS X 11.2

#### Does this happen on simple or atomic sites or both?

Atomic site with the WooCommerce plugin.

#### Is there any console output or error text?

None.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All sites with WooCommerce and store notice enabled.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Markup on 2021-02-06 at 17:26:07](https://user-images.githubusercontent.com/1046943/107123867-6c8a6f80-68a0-11eb-8dba-eeb718a7ef9a.png)

**Comment by simison** [comment]
This should be sorted already in https://github.com/Automattic/wp-calypso/pull/49745, right @ramonjd ? Feel free to re-open if not.

**Comment by ramonjd** [comment]
Yes, thank you! Closed by https://github.com/Automattic/wp-calypso/pull/49745
