### ISSUE TITLE
Classic Editor toolbar does not remain sticky in Firefox

### ISSUE THREAD

**Issue by lymarsh** [Automattic/wp-calypso#49792]
User reports in ZenDesk ticket# 3711096 that when using the Classic Editor in Firefox, the toolbar doesn't remain sticky at the top when scrolling down on the post editor. 

* User has and updated browser, cleared cache, cookies, rebooted, disabled browser addons but continues to have the issue. 
* User tested on .com and .org - while .com continues to have the issue, .org is working as expected. 
* User reports that Chrome works as expected. 
* HE cannot reproduce the issue on Firefox or Chrome but is similar to #49729.

#### What I expected to happen

The toolbar in the Classic Editor should stay in place as it does on the earlier version of Firefox 84.

#### What actually happened
The toolbar doesn't stay in place as shown in this video: ttps://disperser.files.wordpress.com/2021/02/recording-1.mp4

#### Operating System

Firefox 85.0 / Windows NT 10.0

#### Is this specific to the applied theme? 

No

#### Does this happen on simple or atomic sites or both? 

Simple

#### Is there any console output or error text? 

No errors in console.

#### Level of impact (Does it block purchases? Does it affect more than just one site?) 

It impacts all of the users' sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem. 

User shared video: https://disperser.files.wordpress.com/2021/02/recording-1.mp4

**Comment by saygunnyc** [comment]
Are there any updates related to this bug report?

**Comment by nagpai** [comment]
User reported that the issue has fixed itself.

**Comment by nagpai** [comment]
User came back mentioning that the issue momentarily resolved and then it recurred. 

I would keep this closed until the user confirms that they are able to see this with Addons disabled,  or unless one of us is able to replicate the error in Firefox.  

I have also asked the user to move towards using Classic block or the block editor itself, since classic editor is deprecated on WP.com

**Comment by lymarsh** [comment]
The issue was replicated by vparkhere: ZenDesk ticket# 3711096

**Comment by davipontesblog** [comment]
Closing this issue in favor of the one below where we are tracking it:
https://github.com/Automattic/wp-calypso/issues/49729
