### ISSUE TITLE
Premium content block: add border for clarity

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#49797]
### What
Seeing numerous reports of users having trouble adding content to the Premium Content block. It seems like it would be helpful to have a border around where content is supposed to go within the block to make it clear what content will be placed behind the paywall.

### Why
Users are having a hard time telling when content is added after the block vs inside it. This is because there is no clear boundary for the block to indicate what's inside or out. 

When you're on the Prem content block itself there is a border indicating the boundaries. 

<img width="817" alt="1" src="https://user-images.githubusercontent.com/47717887/108841965-3ad41100-75e1-11eb-8b34-68101d4048a8.png">

But once you start adding content this border disappears and it becomes very difficult to see what's inside. Especially if you delete the prompt line (Add content here that will only be visible to your subscribers.)

<img width="809" alt="2" src="https://user-images.githubusercontent.com/47717887/108841969-3c053e00-75e1-11eb-86ea-fc3e24211c0a.png">

### How
1. Keep the border active while the user is clicked anywhere within the Prem content block, even if they are not actively on the parent block

or

2. Persist the parent Prem content block icon to indicate that working within the block. 

<img width="347" alt="3" src="https://user-images.githubusercontent.com/47717887/108841989-41fb1f00-75e1-11eb-864c-247fcaa8d0f1.png">

**Comment by BogdanUngureanu** [comment]
Closing this since Premium Content block currently has an icon for inner blocks, so no changes are needed in context of this feature request :) 

![Screenshot 2022-01-25 at 19 11 21](https://user-images.githubusercontent.com/995955/151025838-fabf0fdb-dae7-4abf-a7a9-499f2876738e.png)
