### ISSUE TITLE
Store | Woo: Remove review count after store removal

### ISSUE THREAD

**Issue by becdetat** [Automattic/wp-calypso#49802]
Similar to #48958 the reviews entry shows a count overlay which should be removed after store removal.

![image](https://user-images.githubusercontent.com/224531/107169293-416f5f80-6a09-11eb-9ac8-c24d30749d43.png)

**Comment by moon0326** [comment]
I'm gonna work on this change in this [PR](https://github.com/Automattic/wp-calypso/pull/49630) as the change is very similar
