### ISSUE TITLE
Stats: Non-English thousands separators are showing as HTML entity

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#4981]
#### Steps to reproduce

1. Go to https://wordpress.com/me/account and change your UI setting to French.
2. Visit a stats page with more than 1,000 visitors (e.g. https://wordpress.com/stats/year)

#### What I expected
Thousands separators to be a whitespace.

#### What happened instead
`&nbsp;` shows up as shousands separators.

#### Browser / OS version

- Mac OSX 10.11.4
- Chrome 50.0.2661.75

#### Screenshot

<img width="740" alt="stats_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/34067/14777564/da0e8082-0b08-11e6-8c83-2076d928625a.png">

Originally reported [here](https://en.forums.wordpress.com/topic/display-problem-in-my-stats-page-1)

**Comment by BandonRandon** [comment]
This is true for Swedish (sv-svenska) as well:
![screenshot_25-04-2016-12 12 19](https://cloud.githubusercontent.com/assets/150348/14795834/3471db7a-0adf-11e6-9e78-2554b8d36872.png)

**Comment by timmyc** [comment]
I traced back the `&nbsp;` to the .json files being generated by glotpress.  EG for Swedish:

http://widgets.wp.com/languages/calypso/sv.json

A not so elegant fix is in calypso can be seen at #5108, but ideally this should be fixed in the translation files. /cc @akirk 

Note this issue will affect all usage of `numberFormat()`, as noted in #5002

**Comment by akirk** [comment]
Am I understanding correctly that the text is escaped here? Why? Translations shouldn't be escaped. For numbers the non-breaking space makes sense, removing the potential for having a 
```
2
300
```
instead of an expected 
```
2 300
```

**Comment by hewsut** [comment]
Drive by jump in here so maybe I'm missing the obvious--I'm confused on why the HTML entities are in the JSON. As my blurry brain recalls it, there should not be any:

https://wpcom.trac.automattic.com/browser/mc/i18n-deploy/index.php#L146

**Comment by timmyc** [comment]
@hewsut & @deBhal have implemented a fix for this, and currently no `&nbsp;` are showing up in `fr` or `sv`.  Sounds like there might be a bit more work to do here on the i18n side of things outside of calypso though.
