### ISSUE TITLE
Focused launch: unclear how to go back from plans/domains modal

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49818]
When in focused launch and opening plans- or domains modals, and then scrolling down, it's unclear how to go back:

![image](https://user-images.githubusercontent.com/87168/107205197-3cf57780-6a06-11eb-84a6-9eccdb540274.png)

<img width="1469" alt="Screenshot 2021-02-08 at 11 55 41" src="https://user-images.githubusercontent.com/87168/107205220-4252c200-6a06-11eb-986b-294b0b9889f7.png">

<img width="1461" alt="Screenshot 2021-02-08 at 11 55 11" src="https://user-images.githubusercontent.com/87168/107205226-454db280-6a06-11eb-8d05-ae713724dfec.png">

I ended up clicking X quite a few times already because I expected it to bring me back to previous screen.

Would it make sense to make "back" fixed on top header, and consider hiding the X in that case?

@ollierozdarz thoughts?

**Comment by ollierozdarz** [comment]
Great pickup, @simison. Fixing '< Go Back' to the header could be the optimal solution here. Unsure about hiding the X as it leaves no exit point at all (probably good to keep users in, bad for overall UX). Go Back in header may solve it completely.
