### ISSUE TITLE
Nav Unification: address wp-admin side of WPCom Internal Color Palette update

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#49826]
In https://github.com/Automattic/wp-calypso/pull/49489 @porada updates Color Studio to the latest version. This version brings with it color tweaks to the Blue that is used by some color schemes (see https://github.com/Automattic/color-studio/pull/37). For full context see p9Jlb4-28F-p2.

We need to update the wp-admin side as well to make use of Color Studio so this and future updates will make it to that side of Nav Unification as well (not just Calypso).

**Comment by getdave** [comment]
To clarify this is not a blocker. There will be minor differences in color schemes between Calypso and WPAdmin.

We will continue on this if we’ve made sufficient progress on the blockers.

**Comment by frontdevde** [comment]
### List of Calypso color schemes using

a) variations of --studio-blue-x:
- [x] Aquatic
- [x] Classic Blue
- [x] Classic Dark
- [x] Contrast
- [x] Default (Classic Bright)
- [x] Nightfall
- [x] Powder Snow
- [x] Sakura

b) relevant variations of --studio-celadon-x:

- [x] Aquatic
- [x] Sakura

### Example of the issue using Aquatic

- The sidebar in Calypso is showing the new blue #055d9c while wp-admin is still showing #135e96
- The links in Calypso are showing in the new celadon #.008763 while wp-admin is still showing #007e65
