### ISSUE TITLE
Gutenboarding: Start your website > Skip for now button outline is cut off in Safari under <100% zoom levels

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49838]
### Steps to reproduce the behavior

Prereq. Use Safari.

1. Go to My Site.
2. Click on Add Site.
3. When met with Gutenboarding and prompted to enter site name, reduce zoom level of browser to 90%.

#### What I expected to happen
All four sides of the outline of the `Skip for now` button remains visible.

#### What actually happened
Depending on the zoom level, outline of the button is not rendered.
This only occurs with less than 100% zoom. Enlarging the page does not reproduce this behavior.

### Context
Back to Basics user testing.

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Browser: Safari Version 14.0.2 (16610.3.7.1.9) **(Specific to this browser)**

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
N/A

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - visual annoyance.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-02-08 at 11 10 53 AM](https://user-images.githubusercontent.com/6549265/107269941-2bf53800-69ff-11eb-9bcf-761a6258ba6c.png)

https://user-images.githubusercontent.com/6549265/107269945-2dbefb80-69ff-11eb-8828-9c65dbf8a642.mov

**Comment by worldomonation** [comment]
This issue is actually not limited to the Gutenboarding step; UI elements that have a thin outline on Safari, using non-standard zoom levels this can be reproduced consistently.

eg. wide version of the Block inserter:
![Screen Shot 2021-02-08 at 4 33 11 PM](https://user-images.githubusercontent.com/6549265/107298994-5957db00-6a2b-11eb-8467-d6a359bfc58c.png)

**Comment by simison** [comment]
@worldomonation if this replicates across editor, it would be best to open issue in Gutenberg since we also just use those components from core. cc @ItsJonQ @sarayourfriend  :wave: who've worked on components recently.

**Comment by sarayourfriend** [comment]
Just want to note that this appears to be an issue with how Safari chooses to render it's zoomed out versions of pages. I note the same bug on GitHub's UI when zooming out on this page (note the extra line on the arrow's right side as well as the missing upper line):

<img width="90" alt="Captura de Tela 2021-03-08 às 09 32 07" src="https://user-images.githubusercontent.com/24264157/110358435-436d1400-7ff1-11eb-8859-ae9124d9463c.png">

Aside from thickening borders, I'm not sure how we would be able to address this.

**Comment by simison** [comment]
My hunch is that it's an edge case browser quirk that isn't worth fixing at our end. What do you think @sarayourfriend?

**Comment by sarayourfriend** [comment]
> My hunch is that it's an edge case browser quirk that isn't worth fixing at our end

That is my position as well.

**Comment by worldomonation** [comment]
I think the assessment of this being an edge case not worth fixing is acceptable - I am unsure what the market share of Safari is for our platform, but it is likely not worth adding special cases and complexity to deal with this. 

Let's label this with `Closed - Won't Fix` and close it?
