### ISSUE TITLE
Publicize: Posts duplicated to Facebook

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#49839]
### Summary

Customer reports that their blog posts are being shared to Facebook twice. Previously they did have duplicated connections from different WordPress.com accounts to their one Facebook page, but now they only have one and the issue continues.

I have confirmed that they only have one account connecting Publicize to Facebook, and I've checked the Publicize logs for clues. I still can't find the cause for this.

One last suspicion I had was whether they could have something setup to share their Publicized-shared posts from Twitter to Facebook. This would have to have been setup with an outside service since we don't offer it. I also checked their Twitter feed and found several Tweets that aren't duplicated to Facebook, so I am not sure that this is a solid theory. None the less, I did ask them to disconnect Twitter from their two accounts and retest with only Facebook connected to Publicize. Currently awaiting results.

### Context
User report in 3706976-zd. Please see the ticket for further details.

#### Browser / OS version
N/A

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
The customer's site is simple.

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affecting a single site.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See ticket for details.

**Comment by Robertght** [comment]
Thank you for reporting this @xpurichan ! 

I could not find any other reports in the Jetpack repo.

I'm going to close this one for now as we have not received any other reports, but please reopen if there are any others.
