### ISSUE TITLE
eCommerce: WordPress Dashboard link in WooCommerce screen links to wp-admin

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#49836]
### Steps to reproduce the behavior

1. Create a site with the eCommerce Plan
2. Navigate to `/wp-admin/admin.php?page=wc-admin`
3. Click on WordPress dashboard link in sidebar

#### What I expected to happen

1.  The link would say "WordPress Home".
2. The link would lead to `wordpress.com/home`

**Comment by ramonjd** [comment]
<img width="591" alt="Screen Shot 2021-02-15 at 10 26 18 am" src="https://user-images.githubusercontent.com/6458278/107894153-c9fa7c80-6f82-11eb-9e5c-2639c48c4d19.png">

So I think the navigation container component [grabs the link and copy from a global window object window.wcNavigation](https://github.com/woocommerce/woocommerce-admin/blob/70ceb958cc9d4d9787ee4be5d5536670b9637045/client/navigation/components/container/index.js#L31)

The object properties are set in [Features/Navigation/Menu.php ](https://github.com/woocommerce/woocommerce-admin/blob/075ea1b926a82576e31c0ba6e2381540e6c46801/src/Features/Navigation/Menu.php#L746)

So we might have to add filters for `woocommerce_navigation_root_back_url` and `woocommerce_navigation_root_back_label` in wpcomsh (or somewhere better?)

Does that sound like a reasonable approach? @pmcpinto

**Comment by simison** [comment]
I asked at pbIJXs-zH-p2#comment-2042 if this should be handled within nav-unification.

I don't think we're best equipped to work on this since related changes are happening all around elsewhere.

**Comment by pmcpinto** [comment]
@ramonjd sorry, I missed your ping. The team already merged a [PR](https://github.com/Automattic/wc-calypso-bridge/pull/634) to fix this. It will be released in the upcoming days.

**Comment by mattsherman** [comment]
@ramonjd @pmcpinto Actually, the fix right now is not complete. It now always goes back to Calypso. There is another open issue to take the user back from wherever they actually came from, wp-admin or Calypso. https://github.com/Automattic/wc-calypso-bridge/issues/640

I think we can close this issue in favor of that one.

/cc @psealock

**Comment by ramonjd** [comment]
Thank you, everyone!
