### ISSUE TITLE
Comment count is misaligned relative to side menu label

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49849]
### Steps to reproduce the behavior

Prereq. Log in as two different users using two different browsers.

1. As `user 1`, comment on an article written by `user 2`.
2. As `user 2`, refresh the dashboard.
3. New comment awaiting moderation is added to the queue. Check the sidebar.

#### What I expected to happen
Comment count shows a `1` beside My Sites > Comments.
The count is aligned with the centre of the `Comments` text.

#### What actually happened
Comment count is slightly offset below the `Comments` text.

### Context
Back to basics user testing.

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Version 88.0.4324.150 (Official Build) (arm64)

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Tested on Simple, but should also occur on Atomic.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - visual inconsistency that may impact perception of quality from user's perspective.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-02-08 at 5 51 35 PM](https://user-images.githubusercontent.com/6549265/107313169-dc3a5f00-6a46-11eb-97e6-12d89f289849.png)
![Screen Shot 2021-02-08 at 5 52 05 PM](https://user-images.githubusercontent.com/6549265/107313170-dc3a5f00-6a46-11eb-882a-c588e57ba88c.png)

**Comment by autumnfjeld** [comment]
If this is an easy fix, let's do it.

**Comment by p-jackson** [comment]
This problem appears to have been worse before nav unification rolled out.
You can still see this if you append `?disable-nav-unification` to the url
<img width="286" alt="Screenshot 2021-08-16 at 4 58 06 PM" src="https://user-images.githubusercontent.com/1500769/129513319-dafb0420-225e-48a0-bf06-c1886badf663.png">

However there was some rationale to how it was. In this video you can see that although there's a big difference between the gap above and below the oval, the placement is trying to align the text baselines.

https://user-images.githubusercontent.com/1500769/129513554-eb034d80-83a3-4658-9b7a-484f503d792f.mov


Now trying it with nav unification enabled again. The gap above and below the oval is much closer now, and the baselines still align.

https://user-images.githubusercontent.com/1500769/129513879-1fce6af8-b9cb-45a4-8e03-2a6da2b58372.mov

I think the current tradeoff might be the best of all possible worlds. I think having unaligned baselines would be messy, and the alternative of not centering the number within the oval would also not look great.
We could shrink the height of the nav items even more, which would align things more. But then the heights in Calypso would be different from `wp-admin`s, and we've only just recently made them match.

For those reasons I'm going to close this as "won't fix". The reopen button is always there if someone has a better idea though 😃
