### ISSUE TITLE
Nav Unification: clicking on My Sites does not take user back to home dashboard

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49847]
Note: filing this under bug, but if this is expected updated behavior, please close.

### Steps to reproduce the behavior

1. Go to Dashboard.
2. Click on Nav SIdebar > Appearance > Themes.
3. Click on a theme.
4. Once in the theme details page, click on the `My Sites` at top left.

#### What I expected to happen
User is taken back to `My Home` dashboard (as it currently does in customer-facing calypso).

#### What actually happened
User is not taken back to `My Home`.

### Context
Back to basics user testing.

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Browser: Safari Version 14.0.2 (16610.3.7.1.9)
Browser: Firefox Nightly 87.0a1

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Both.

#### Is there any console output or error text?
At Step 4, Network tab in Firefox shows a GET request to `https://pixel.wp.com/t.gif?environment=production&environment_id=stage&site_count=96&site_id_label=wpcom&client=browser&_en=calypso_masterbar_my_sites_clicked&_ui=6321460&_ut=wpcom%3Auser_id&_ul=worldomonation&_ts=1612822331247&_tz=8&_lg=en-US&_pf=MacIntel&_ht=2412&_wd=4288&_sx=0&_sy=0&_dl=https%3A%2F%2Fwordpress.com%2Ftheme%2Ftwentytwenty%2Fradicallyrenewedrecordsshop.wpcomstaging.com&_dr=https%3A%2F%2Fwordpress.com%2F&_rt=1612822331247&_=_`

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Moderate? - user may possibly confused. I suspect (with no solid data or confirmation however) that users expect clicking on the top left typically takes them back to the top page.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Nav Unification:

https://user-images.githubusercontent.com/6549265/107288236-f872d780-6a17-11eb-8b90-d8751b04a335.mov

Current (customer-facing):

https://user-images.githubusercontent.com/6549265/107288281-0aed1100-6a18-11eb-9d49-dc56b6cb31fe.mov

**Comment by worldomonation** [comment]
Still an issue, reproduced.

**Comment by kimerlin81** [comment]
This is a present issue as shown [here](https://d.pr/i/G6bK0C). Added to Triage board to get more eyes on it. Marking this Triaged for developers to review.

**Comment by p-jackson** [comment]
> if this is expected updated behavior, please close.

It is working as expected. But it wasn't what you expected, so maybe "as expected" isn't so expected after all 😃 

Fixing this particular case would require special-casing the theme showcase view. But I'm wondering whether maybe the My Sites link in the top bar should _always_ return the user to My Home. That's how the Reader link behaves i.e. it always returns the user to the root of the Reader.

I've raised it here: p1653277915987689-slack-C9EJ7KSGH

**Comment by wojtekn** [comment]
> But I'm wondering whether maybe the My Sites link in the top bar should always return the user to My Home. That's how the Reader link behaves i.e. it always returns the user to the root of the Reader.

@p-jackson I played with that menu. My first thought was that current behavior is good - it does nothing, as those two links are technically tabs, and clicking on the currently active tab should not necessarily do anything.

Then based on your idea, I reviewed how it works in the context of the Reader experience, and I agree with you - it would make sense to make it consistent and let "My Sites" always return the user to "My Home."

**Comment by sejas** [comment]
Yes! I agree.
Keeping the link always will improve the general UX. Let's go for it 💪 .

I took the approach of modifying only the theme in the first place to avoid making a broad change. And because the theme section has a different treatment already. It's the only full-width section, and it hides the left menu with CSS.

**Comment by p-jackson** [comment]
There hasn't been too much designer input on the slack thread other than "we're changing this area soon". So if you think it's an improvement I think it's fine to do. I just don't want to complicate the component with special-casing depending on context. So making it work more like the Reader link should be fine.
