### ISSUE TITLE
Domain: overflowing text inside post-purchase detail box 

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49842]
### Steps to reproduce the behavior

Prereq. enable sandbox if not willing to use real card.

1. Create a free site with long domain name (eg. `superlongdomainnamethatisrealisticallyunfeasible`)
2. Go to My Sites > Upgrades > Domains.
3. Click on button labelled `Add a domain to this site`.
4. Enter some domain name to purchase.
5. Proceed through the checkout process.
6. Once purchase goes through, inspect the congratulations page.

#### What I expected to happen
Text within the `Purchase details` box does not extend beyond the border.

#### What actually happened
With a long default domain name, text within the`Purchase details` box can extend past the right hand border.
This causes other text lines to also extend beyond the border.

### Context
Back to basics user testing.

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Browser: Safari Version 14.0.2 (16610.3.7.1.9)

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Tested on Simple but should occur on Atomic as well.

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - visual annoyance.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot 2021-02-08 at 11 35 45 AM](https://user-images.githubusercontent.com/6549265/107273701-441b8600-6a04-11eb-8f76-8cc783a9228a.png)

**Comment by klimeryk** [comment]
Thanks for reporting - hopefully, not many users register such long domain names (and we have data to confirm that), but nevertheless it's an easy fix, so I created https://github.com/Automattic/wp-calypso/pull/49940 to address it 🙇
