### ISSUE TITLE
FSE Plugin: Preventing Youtube Videos to Load

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#49840]
### Summary
When you add a Youtube video on the Video widget, it’s not loading the video on pages/posts with the Blog Posts block.

### Steps to reproduce the behavior

1. Add a Video widget with a Youtube video
2. Make sure the full-site-editing plugin is active, and add a Blog Posts block to a page or post
3. Check your site to see if the video loads on the page or post (or on the the home page that displays a list of posts).

#### What I expected to happen
To load any Youtube video I added to my site.

#### What actually happened
The Youtube video on the Video widget stops loading. This is how the video shows on the site:

![VideoWidget](https://user-images.githubusercontent.com/16104522/107271180-a12a3280-6a2a-11eb-8cee-479534ce0f84.png)

### Context
User report: 27531005-hc

**Comment by kriskarkoski** [comment]
Is there a console error when this happens? 

I have a possibly related issue where the YouTube video doesn't work in a video widget on simple sites when the Blog Posts block is on the page. In this scenario this following console error shows under `Uncaught TypeError: Cannot set property 'mejs' of undefined`:

<img width="436" alt="Screen Shot 2021-02-09 at 6 24 11 PM" src="https://user-images.githubusercontent.com/1900444/107441903-14ec3e00-6b04-11eb-8645-5229c89a7aa5.png">

The issue does not happen with an uploaded video or if the Blog Posts block is not present.

3711160-zen - In this case I worked around the issue by placing the YouTube video in a text widget

**Comment by carinapilar** [comment]
> Is there a console error when this happens?

Ah, yes, it looks the same thing! I was able to replicate it on a Simple site too, like you said, and I also see that error in the console. And the Text widget loads fine.

**Comment by aleone89** [comment]
Hello, 

This has also been reported here, and I was able to locate the same console error as above: https://wordpress.com/forums/topic/problem-home-page-colinear-theme/ 

Interestingly, this only happens on the homepage of this site: https://guillaumetat.wordpress.com/ but not on an individual article: https://guillaumetat.wordpress.com/2019/07/27/france-balades-autour-de-lille/ 

The video isn't YouTube but one that's been uploaded to the site. 

The theme in use here is: https://colineardemo.wordpress.com/

**Comment by tbradsha** [comment]
27748881-hc

Using YouTube videos, they get the same `mejs` JS error. It loads fine in the Customizer but not on the live site.

**Comment by kelasante** [comment]
23779435-hc

YouTube video in the video widget in the sidebar does not load on the homepage. It loads in Customizer and on non home pages.

**Comment by Robertght** [comment]
Same issue in 3823616-zen

**Comment by alshakero** [comment]
I tried to reproduce this but I can't. Neither on simple nor Atomic sites. I created a page with the same theme as the issue here, I added all kinds of videos and Blog Posts block, and still can't reproduce. 

I also installed MedieElement.js plugin (mejs) in an attempt to recreate the same env (because the error contains mejs), and still wasn't able to get it.

Here is the page https://omar973567781.wpcomstaging.com/.

**Comment by carinapilar** [comment]
@alshakero, I'm still able to replicate this issue. It happens when accessing a page where you have a Blog Posts block, and a Video widget with a Youtube video on it.

I tested on a Free site, using Karuna. Created a new page, added the Blog Posts block, and in the Customizer I added a Video widget on the footer - added a video to the widget using a link from Youtube.

I got the error mentioned above in the Console, and the video loaded like this when accessing the new page:

![Screen Shot 2021-03-26 at 09 50 07](https://user-images.githubusercontent.com/16104522/112633901-b1e70a00-8e18-11eb-8be0-67fa113380dd.png)

**Comment by creativecoder** [comment]
I updated the issue description to indicate that that the problem happens when there's a video widget and the Blog Posts block displaying at the same time.

**Comment by Robertght** [comment]
Another case found in #21196495-hc

**Comment by creativecoder** [comment]
This actually seems to happen with either of the blocks synced from Newspack, either Blog Posts or Posts Carousel.

**Comment by creativecoder** [comment]
Fix at https://github.com/Automattic/wp-calypso/pull/51700
