### ISSUE TITLE
New Page Layout Picker: rename the "homepage" layout category to "home"

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#49861]
We're changing the design of the layout picker: p9Jlb4-27F-p2

Part of the change is renaming the "homepage" layout category to "home". This seems like a change we can make right now while the new layout is being worked on #49587

**Comment by roo2** [comment]
made this change and spot tested that translations were good, e.g. 'de' translated "Home" to "Startseite" (Start Site) which google translates to english as "Home Page" ✅
