### ISSUE TITLE
New onboarding: consolidate new blue across UI

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49866]
## What

Requires #51102

Updates all New Onboarding flows to use the same shades of blue

## Why

Improve UI experience for the users

## A/C

- [ ] Refactor the code, switching from hardcoded values to the newly created shared variables
- [ ] Use the same shades of blue in new onboarding, step by step launch, and focused launch
- [ ] Sass variables should still be used (e.g. assign CSS variable to Sass variable)

## Context

Since "new blue" was merged in https://github.com/Automattic/wp-calypso/pull/49489, we should go through new onboarding to ensure colors are consistent and using correct generic color variables under the hood, and not gutenboarding specific ones.

Blue is now brighter in new-onboarding, but not for every element. Buttons are still darker:

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/87168/107335963-3d9f1400-6ac1-11eb-9e20-8b213183f142.png">

@simison commented:

>  Most notably buttons have darker blue — something we might wanna fix? Not sure if bright blue works in buttons for readability but that’s quick to try.
> hover/active border color on buttons seems to be bright blue, while background is darker. I would expect darker border instead.

@ollierozdarz commented:

> [...] yes, it looks like there will need to be a few tweaks to make it perfect for onboarding. I don't see any readability issues and we also use this on the marketing site (but it looks like the primary color there is a darker variant of the new Blue [which we should aim to use as the primary color]).

Slack ref p1612795919345800-slack-luna

**Comment by razvanpapadopol** [comment]
A related issue was created initially to cover Focused Launch but the scope should definitely be across onboarding & launch flows since they are sharing components: https://github.com/Automattic/wp-calypso/issues/47181

**Comment by simison** [comment]
Yap, feel free to re-arrange issues how it works best for you! :-)
