### ISSUE TITLE
WPCOM Plugins: Plugin names don't all fit in the available space

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#4986]
If a plugin has a long name (e.g. "Advanced Commenting") it is cut off with an ellipsis ("Advanced Commenti..."). For users who aren't familiar with a given feature, that's not particularly helpful. It will also cause trouble for i18n in languages that have longer translations for feature names.

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/plugins
2. Select a WordPress.com site
3. Select "View all standard plugins" (to get to the full list of free plugins at https://wpcalypso.wordpress.com/plugins/standard/YOURSITE.wordpress.com)

#### What I expected
Each plugin's full name to be somehow visible (e.g. on multiple lines).

#### What happened instead
Long plugin names are cut off with an ellipsis.

#### Browser / OS version
Mac OS X 10.11.4, Chrome 49.0.2623.112

#### Screenshot / Video

![screen shot 2016-04-25 at 2 31 34 pm](https://cloud.githubusercontent.com/assets/8658164/14785668/ded6ba7c-0af3-11e6-8260-5007f0e86533.png)

**Comment by rachelmcr** [comment]
@drw158 I see you updated `Advanced Commenting` to `Advanced Comments` to avoid truncation.

Is there a solution that will also work for non-English languages that use longer titles? For example, `Email Subscriptions` translates into Spanish as `Suscripciones por correo electrónico` and won't fit into the space provided.

**Comment by drw158** [comment]
It'll need to drop to 2 lines
