### ISSUE TITLE
New Page Layout Picker: add new descriptive names for each page layout

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#49864]
As part of the page layout picker redesign (p9Jlb4-27F-p2), each layout includes a new descriptive name. e.g.
- "portfolio-8" -> "Tiled gallery with description"
- "Bowen" -> "Modern blog layout with subscription and intro"

The descriptive names are being worked on in this spreadsheet: 284dc-pb

These names should be added to the layout metadata somewhere, either replacing the existing names or as a new field, so that they can be used by the new layout.

**Comment by roo2** [comment]
This one was actually just a matter of adding the descriptive name's to the "Caption" of each pattern post.

The "Caption" is returned from the PTK API as `description` and is already used for the `aria-label` in 
https://github.com/Automattic/wp-calypso/blob/trunk/packages/page-template-modal/src/components/template-selector-item.js#L73

**Comment by p-jackson** [comment]
Woohoo! 🥳 
Thanks for tracking it all down and making sure those descriptions are in.

**Comment by autumnfjeld** [comment]
Could we add a link to the PR that completed this?  😄
