### ISSUE TITLE
Checklist Progress Bar missing

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#49878]
While exploring https://github.com/Automattic/wp-calypso/issues/49396, I noticed that we don't render 

https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/sidebar/index.jsx#L287-L292

which shows as below

![](https://cln.sh/p9NnFh+)

"My Home" is now served from the `admin-menu` endpoint in wpcom. Even if we manage to render the progress bar we will still need to revise the UI

![](https://cln.sh/QIwv1u+)

**Steps to reproduce:**
- Create a new site or visit a site without all site setups steps finished

**Comment by obenland** [comment]
@sfougnier Should this be brought back or can we leave it for now?

**Comment by ghost** [comment]
I vote we leave it out for now - since we've decreased the padding there's a lot of details to digest, so it might be best to avoid adding more.

**Comment by obenland** [comment]
Sounds good!
