### ISSUE TITLE
Atomic Feature: Allow user to manage purchases while Jetpack is disconnected.

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#49899]
**What**
Allow WordPress.com subscriptions to be managed on a disconnected WordPress.com on Atomic site.

Related to issues described on #48746  and https://github.com/Automattic/wp-calypso/issues/44432

**Why**
When a WordPress.com on Atomic site's Jetpack connection is completely broken, some purchases are not manageable. 

![Screen Shot on 2021-02-09 at 18:14:18](https://user-images.githubusercontent.com/4887830/107441080-a78bdd80-6b02-11eb-94c9-d0429e605239.png)

**Comment by zdenys** [comment]
4724764-zd-woothemes

**Comment by zdenys** [comment]
4788183-zd-woothemes

**Comment by zdenys** [comment]
4952570-zd-woothemes

**Comment by zdenys** [comment]
5934116-zd-woothemes

**Comment by kriskorn** [comment]
This issue happens only in specific instances now where Jetpack is disconnected via Jetpack Debugger `Disconnect Jetpack` link. In any other case, Calypso is accessible and DNS can be managed as expected, even if sites have fatal errors or the domain is pointed to an external provider. Marking this as solved for now. 

Context: pdtR3Z-1Cq-p2#comment-1504 & p1679414671950499-dotcom-reactor
