### ISSUE TITLE
Domains: Confusing Email page for mapped domain w MX records

### ISSUE THREAD

**Issue by shawnajean** [Automattic/wp-calypso#4990]
#### Steps to reproduce
1. Add a Domain Mapping upgrade to your site.
2. Add an MX record to your domain.
3. Visit your domain's Email page (https://wordpress.com/domains/manage/DOMAIN/email/DOMAIN
#### What I expected

Be notified that I can't add Email Forwarding because I have custom MX records.
#### What happened instead

There's no notice about the MX records or Email Forwarding button, just an alert that I can't add Google Apps.

<img width="776" alt="screen-shot-2016-04-22-at-6-04-06-p" src="https://cloud.githubusercontent.com/assets/775884/14792668/561443a8-0ae9-11e6-8f46-a36b302cd1e8.png">

@klimeryk mentioned that we're rolling out Google Apps soon, but once that's rolled out, we should probably still fix the messaging so users looking for forwarding can figure out why they're not seeing the option to add Email Forwarding here.

**Comment by aidvu** [comment]
@klimeryk is this fixed by: https://github.com/Automattic/wp-calypso/pull/4977

**Comment by klimeryk** [comment]
Wrong Igor, @shawnajean - I've edited the post and put myself there :)

@aidvu: that one restored the Email Forwarding button to this page. This issue is about showing a warning that email forwarding will not work because the user (or we, in case of Gapps) have set custom MX records.

**Comment by klimeryk** [comment]
This has become a non-issue now that we have G Suite for mapped domains thanks to https://github.com/Automattic/wp-calypso/pull/10843 🎉
