### ISSUE TITLE
Nav Unification: Header and Background options did not open up the respective sections in Customizer for Jetpack sites

### ISSUE THREAD

**Issue by reginabally** [Automattic/wp-calypso#49916]
### Steps to reproduce the behavior

1. Log in to WordPress.com with a Jetpack site
2. Click "Header" or "Background" under the Appearance menu
3. The Customize screen loads but did not open up the "Header" or "Background" section.

#### What I expected to happen

I would expect when I clicked on the respective submenu items under the Appearance screen, I'm able to see the respective customize options.

#### What actually happened

The Customize screen loads but did not open up the "Header" or "Background" section in the Customizer.

#### Browser / OS version

Firefox 85.0.1 (64-bit) on macOS Big Sur 11.2 (20D64)

#### Is this specific to the applied theme? Which one?

Not specific to a theme.

https://woo20200908.mystagingwebsite.com is using Storefront

https://jptest20201202.mystagingwebsite.com is using Twenty Twenty

#### Does this happen on simple or atomic sites or both?

Only happens on Jetpack sites. No common activated plugins on these two sites except for Jetpack.

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affecting both of my Jetpack sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screen recording: https://d.pr/v/uYPnGx/lkUukLvKrf

**Comment by Robertght** [comment]
this appears to be fixed already as I tested with Storefront and Twenty Twenty-one.
