### ISSUE TITLE
"Edit CSS" menu item under "Appearance" menu appears twice

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#49919]
### Steps to reproduce the behavior

- Start with a WordPress.com website that has plugins or a third-party theme installed. Sites without plugins or third-party themes are not affected.
- On the left menu, under `Appearance`, look for `Edit CSS` option.

#### What I expected to happen

The option appears once.

#### What actually happened

The option appears twice. 

- One leads me to https://atomic-wpcom.workroom.blog/wp-admin/admin.php?page=editcss-customizer-redirect
- Another leads me to https://atomic-wpcom.workroom.blog/wp-admin/themes.php?page=editcss 

### Context

This is probably related to the new Nav Unification rollout. I do not remember how things were on the classic, black wp-admin dashboard.

#### Browser / OS version

Firefox 85.0.2 (64-bit) on Mac 11.2

#### Is this specific to the applied theme? Which one?

Not specific to a theme, but I have Twenty Twenty-One installed.

#### Does this happen on simple or atomic sites or both?

Atomic. Simple sites do not have that option. 

#### Is there any console output or error text?

Not applicable.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Applicable to all Atomic sites, but low impact. Does not break anything. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="303" alt="Screenshot 2021-02-10 at 1 53 30 PM" src="https://user-images.githubusercontent.com/18581859/107492028-eaf15500-6bb1-11eb-8862-01ca0b20a7c1.png">

**Comment by Aurorum** [comment]
Strange - I can't reproduce this, including with the Twenty Twenty-One theme. I wonder if there's something I'm missing or if another factor is involved? 

<img width="259" alt="Screenshot 2021-02-10 at 10 01 14" src="https://user-images.githubusercontent.com/43215253/107494731-07c46300-6b87-11eb-92fb-d530c7e9c6cc.png">

**Comment by cpapazoglou** [comment]
Thanks @arunsathiya for reporting this. 

I can't reproduce this either. It may a 3rd party plugin or theme issue. Can you reproduce this on a new Atomic site? If not, can you list here your themes / plugins?

**Comment by arunsathiya** [comment]
This is very odd! I cannot reproduce at the moment either. I was testing with a fully reset Atomic website (AKA fresh Atomic website) when I found that bug. Not sure why it doesn't appear anymore. I will close this for now, but I can followup if I can consistently reproduce.
