### ISSUE TITLE
Nav unification: Some Jetpack Submenus Hidden from Calypso 

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#49927]
### Steps to reproduce the behavior

1. Hover your mouse to Jetpack.
2. Two submenus will appear: 

- Activity Log
- Back-up

#### What I expected to happen
Five Submenus to appear similar with the WP Admin:

- Dashboard
- Settings
- Backup & Scan (though this also directs to Back-up)
- Site Stats
- Back-up

#### What actually happened

Only two submenus appeared

https://www.loom.com/share/094abf3797bf4575ab182724922a6d0c

**Comment by cpapazoglou** [comment]
Thanks @rosepajaroja for reporting this!

This is the new default for Simple / Atomic sites where both Calypso & WP Admin will not show Dashboard, Settings, Site Stats.

For Jetpack sites:
- on Calypso you will still get the minimal menu
- on WP Admin you will get the Jetpack default menu

For more info p1HpG7-b2s-p2

**Comment by rosepajaroja** [comment]
Hello @cpapazoglou, yes I can access the WooCommerce Setup Wizard. 

The issue happens if you upgrade to eCommerce plan. It prompts to create your store upon successful checkout. That button directed me to Crowdsignal instead of the WooCommerce Setup Wizard.
