### ISSUE TITLE
Nav Unification: rest_invalid_signature after exiting Customize screen on Jetpack sites

### ISSUE THREAD

**Issue by reginabally** [Automattic/wp-calypso#49922]
### Steps to reproduce the behavior

1. Log in to a WordPress.com account with a Jetpack site
2. Click on Customize to go to the Customize screen
3. Click X to exit the screen
4. See the `rest_invalid_signature` on the browser

#### What I expected to happen

I would expect I can return to the WordPress.com dashboard after I clicked the X button.

#### What actually happened

I'm seeing a JSON API output with the error `rest_invalid_signature` on the browser.

#### Browser / OS version

Firefox 85.0.1 (64-bit) on macOS Big Sur 11.2 (20D64)

Browser information: https://whatismybrowser.com/w/FR9H7RA

#### Is this specific to the applied theme? Which one?

Not specific to a theme.

https://woo20200908.mystagingwebsite.com is using Storefront

https://jptest20201202.mystagingwebsite.com is using Twenty Twenty

#### Does this happen on simple or atomic sites or both?

Only happens on Jetpack sites. No common activated plugins on these two sites except for Jetpack.

#### Is there any console output or error text?

![Markup on 2021-02-10 at 17:41:31](https://user-images.githubusercontent.com/40906847/107492413-5f82be80-6bc7-11eb-8886-95a7cea7c9cb.png)

I've tested after enabling cross-site tracking cookies but still getting the same error.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affecting both of my Jetpack sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screen recording: https://d.pr/v/GRUfbI/jVea9yA4mI

**Comment by obenland** [comment]
@reginabally Is this something that still happens for you? The customizer link should point to the Jetpack site's wp-admin customizer instance now.

**Comment by reginabally** [comment]
@obenland Thanks for following up. I no longer see the error but when I exited Customizer (step 3 in my original post), I was redirected to my site's homepage instead of WP Admin. Is this intended?

![Screen Capture on 2021-03-15 at 14-51-07](https://user-images.githubusercontent.com/40906847/111114259-f4e5e980-859d-11eb-9a96-f51f16f33ce2.gif)

**Comment by obenland** [comment]
It depends on whether a return parameter was defined. It looks like you're entering the Customizer with Nav Unification disabled, I'm pretty sure with it active that return parameter is passed along.

**Comment by reginabally** [comment]
Ah, my apologies. It looks like Nav Unification was [disabled for Jetpack sites](https://github.com/Automattic/wp-calypso/pull/50751/files#diff-9fb76d512b14b29e4619f44fc4f0fed98dc373f1bdfdc544112f914a0eaee761) for now. I'll test this out again when it's enabled.

**Comment by obenland** [comment]
Sounds good, thank you!
