### ISSUE TITLE
Plugins (wpcom): GA feature page back button goes to compare page

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4993]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/plugins/site.wordpress.com
2. Click on the Google Analytics plugin
3. Goes to the GA feature page
4. Click Back button
5. It goes to the plans compare page

Not sure what the behavior should be. I just know that it was unexpected.

#### What I expected
I expected it to go back to the Plugins page

#### What happened instead
It went to the plans compare page

#### Screenshot / Video

![screen recording 2016-04-25 at 02 11 pm](https://cloud.githubusercontent.com/assets/618551/14795803/be45bdde-0aef-11e6-9f98-0d572a456fbe.gif)

@retrofox

**Comment by adambbecker** [comment]
Yeah I actually agree with this for anything using the header cake component.

To me, it seems like if you have a browser history inside Calypso, the "back" link should literally take you one step back in your history. If you don't have a history (i.e. landing on a page with a header cake component & back link), then the back link should take you to a default location based on the page. In this particular example that default location would be `/plans`.

Might even be worth investigating altering the `< Back` text based on history length.

**Comment by retrofox** [comment]
re introduced
