### ISSUE TITLE
Audio Block: Allow play in Editor

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#49947]
When the audio file is added to the Audio Block in the editor, it cannot be played. 

**What**
Allow playing Audio just like videos

**Why**
It's confusing to see the Audio Block with play controls but not be able to click them and play the audio.

![](https://d.pr/i/Z0YBTZ+)
_Link: https://d.pr/i/Z0YBTZ_

**Additional context**
Brought up in this conversation p1612967236170900-slack-C03TY6J1A by @kingsleyinfo

**Comment by eduardozulian** [comment]
There is some discussion happening also on https://github.com/WordPress/gutenberg/issues/9252

**Comment by zdenys** [comment]
As of now, it is possible to play the audio in the Editor. Closing this issue.


https://user-images.githubusercontent.com/39308239/130945500-8b153576-db4c-40af-955d-f726b01ef3ee.mov
