### ISSUE TITLE
Masonry Block: Gallery caption RichTextToolbar disappears on click

### ISSUE THREAD

**Issue by mrsjaved** [Automattic/wp-calypso#49950]
### Steps to reproduce the behavior

1. Go to My Sites -> Posts, add a new post, or edit an existing post.
2. Add "Masonry Block" and select some images from the media library.
3. From block settings enable "Captions".
4. Click on the caption and you will notice the toolbar to make the caption bold, or add the link disappears. 

#### What I expected to happen
It should display the inline toolbar like Paragraph block to make the text size bold or add links.

#### What actually happened
The toolbar disappears on click on the caption

#### Browser / OS version
Chrome Browser 88.0.4324.150 | Mac OS Big Sur

#### Does this happen on simple or atomic sites or both?
Both 

#### Is there any console output or error text?
"deprecated.min.js?ver=c98233d213768b215724e3d63cf2b24b:2 wp.editor.RichTextToolbarButton is deprecated. Please use wp.blockEditor.RichTextToolbarButton instead."

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It does not block purchases but it must be affecting multiple sites. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Screencast video -> https://d.pr/v/TrP1Rm/wrLzacEyNq

Ref: 3728196-zd-woothemes

**Comment by mrsjaved** [comment]
Related: https://github.com/godaddy-wordpress/coblocks/issues/1717

**Comment by davipontesblog** [comment]
Closing as fixed as CoBlocks has been updated now.
