### ISSUE TITLE
Atomic Feature: Allow users to reset their site themselves

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#49952]
Time-to-time we get requests to reset user's site. It would be great if the users were able to reset their site themselves.

Why

- Users will be more happy and in control - as they don't have to contact us.
- We will get less requests in chat and tickets.

How

The feature could be present on one of these pages as a box with short explanation and a button:

- https://wordpress.com/settings/general/
- https://wordpress.com/hosting-config/face-news-book.com

Once the user clicks on the button, they will need to confirm the action, maybe by typing in the site address and then clicking the reset button.

Before the actual site reset is performed, a full site backup should be automatically created.

**Additional context**

Report: 27652191-hc

**Comment by zdenys** [comment]
I thought about the same feature request as it would have been helpful in 3753082-zd-woothemes.

**Comment by ivan-ottinger** [comment]
Another request: 22770017-hc

**Comment by ivan-ottinger** [comment]
Another case where this feature would help: 28744518-hc

**Comment by jordesign** [comment]
Closing this in favour of https://github.com/Automattic/wp-calypso/issues/32792
