### ISSUE TITLE
Account Settings: Unable to cancel pending email change

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#49969]
### Steps to reproduce the behavior

- Start at https://wordpress.com/me/account
- Initiate an email change for your account
- After the new address is entered, use the `Cancel` button next to the confirmation notice.

#### What I expected to happen

Cancellation button works.

#### What actually happened

Cancellation button responds with a console error instead. The error reads:

```
Uncaught TypeError: t.cancelPendingEmailChange is not a function
    cancelEmailChange https://wordpress.com/calypso/evergreen/account.ce5ca6d120ef043f9d3b.min.js:1
    a https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    p https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    v https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    v https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    st https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    rt https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    it https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    ft https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    L https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    D https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    Yt https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    Gt https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    unstable_runWithPriority https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    qo https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    I https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
    Kt https://wordpress.com/calypso/evergreen/90402.b06dbfe4691cdc8d7199.min.js:2
```

### Context

Found during this Slack conversation with @kristarella - p1613010606443200-slack-C03TY6J1A

#### Browser / OS version

Firefox 85.0.2 (64-bit) on Mac 11.2

#### Is this specific to the applied theme? Which one?

Not applicable.

#### Does this happen on simple or atomic sites or both?

Not applicable.

#### Is there any console output or error text?

Yes, mentioned above.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High, affects all customers. 

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1471" alt="Screenshot 2021-02-11 at 8 27 54 AM" src="https://user-images.githubusercontent.com/18581859/107598181-11ab9c00-6c43-11eb-8124-6ce2a3a4a9cf.png">

**Comment by arunsathiya** [comment]
These seem to be recent commits related to account settings: https://github.com/Automattic/wp-calypso/pull/49760, https://github.com/Automattic/wp-calypso/pull/49875 and https://github.com/Automattic/wp-calypso/pull/49949. 

cc @yuliyan @flootr, could either of you help identify if these could be a cause? @cathymcbride as well, to help with triaging.

**Comment by flootr** [comment]
I'll have a look 👍🏻
