### ISSUE TITLE
Plugins (wpcom): Add Plugin menu item in WP Admin

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4998]
We need to enable the Plugins menu item in WP Admin. It will link to the new plugins page in Calypso. This is for users who still go to WP Admin.

> I think a lot of users get tripped up with plugins in WP Admin because they read or watch a tutorial for WordPress.com and then can’t find the plugins menu in WP Admin on WordPress.com but otherwise they look very similar. Should/could we add the plugins menu to WP Admin just like it is on .org and just link that to the new Calypso page for ease of implementation so users can see that plugins aren’t allowed and what features we do have built-in?

**Comment by roundhill** [comment]
<img width="161" alt="screen shot 2016-04-27 at 11 18 52 am" src="https://cloud.githubusercontent.com/assets/789137/14863291/f1e2af78-0c69-11e6-90ca-a3899b729d17.png">

How's this look? I added it in the same place that you see it in wp-admin on a self-hosted site.

**Comment by drw158** [comment]
LGTM

**Comment by drw158** [comment]
We will do this after the split test is finished (#5022) . Removing from milestone.

**Comment by drw158** [comment]
This is postponed, and possibly `won't fix`.

**Comment by drw158** [comment]
@apeatling Is this something we won't do?

This add a Plugins menu item to wp-admin for .com sites.

**Comment by apeatling** [comment]
I was pretty against this before, but I think if we can link it directly to Calypso it's ok to add.

**Comment by roundhill** [comment]
Added this in r146605-wpcom
