### ISSUE TITLE
Enable language picker in new onboarding

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#49987]
We attempted to enable language picker in `/new` flow at https://github.com/Automattic/wp-calypso/pull/49674 — but had to revert due some bugs in https://github.com/Automattic/wp-calypso/pull/49683

Bugs are now sorted out I believe, so we can enable this again.

Test link for production version: https://wordpress.com/new?flags=gutenboarding/language-picker

P2 pbAok1-dn-p2

<img width="977" alt="image" src="https://user-images.githubusercontent.com/87168/107620592-9c00f980-6c5d-11eb-8467-921ac262ca42.png">

**Comment by razvanpapadopol** [comment]
Done in #50300
