### ISSUE TITLE
Support user/mc/WP Admin switches to Super Admin Account (simple sites)

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#49996]
_I'm not sure if this is something that will be cleared up when nav unification goes live and becomes universal._ 

When working with users sites, I've noticed that when I access certain parts of the backend of the site I'm redirected back to my own super admin account. 

#### Steps to replicate 

1. Go to a users site for example: https://landyourdreamjobs.wordpress.com/wp-Admin
2. Click on either of the following on the left hand side menu: 

- Statistics 
- Upgrades 
- Posts (everything except tags)
- Pages 
- Comments 
- Jetpack 
- Appearance 
- Users 
- Tools 
- Settings 

#### 3. Get redirect to my own My Sites page 
( pick a site - Screenshot: https://d.pr/i/mxSNTD )

#### What I expected 

To go the the panel related to that site (i.e. https://landyourdreamjobs.wordpress.com/wp-admin/post-new.php ) 

#### What I noticed 

Where this didn't happen, the link was something like: https://alexandrajfoster.wordpress.com/wp-admin/link-manager.php 

Where this does happen, the link is: https://wordpress.com/comments/all/alexandrajfoster.wordpress.com

This also can affect the MC: https://d.pr/i/3zLaZS

#### Browser / OS version

Chrome 88

#### Does this happen on simple or atomic sites or both?

Simple

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

This will affect pretty much all of Happiness or anyone working on a users site. 

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistant

**Comment by mmtr** [comment]
Thanks for reporting this issue, @aleone89. This is a variant of https://github.com/Automattic/wp-calypso/issues/49455, so I'm closing this as a duplicate.

In that issue, we're considering to default to WP Admin pages for super admins who are not members of the current site, since WP Admin pages are accessible by super admins while Calypso pages are restricted to site members only.
