### ISSUE TITLE
Plugins (wpcom): if user has something a la carte, it's not shown as active

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#4999]
It has been reported that if you have a feature a la carte, like Custom Design, then that plugin on the new Plugins page appears inactive. This only affects older sites that are not on a plan.

We need to decide:
- Is it worth it to tweak the interface for all of these exceptions? What % of sites are paying a la carte?
- Do we do nothing for these users and hope they get it?

https://horizonfeedback.wordpress.com/2016/04/21/call-for-testing-plugins-page/#comment-219

If possible, I suggest something low cost. If we can detect that a user is paying a la carte, then we can display a notice at the top, saying that because they are not on a plan, the Plugins UI might not be displaying right.

I assume that these users run into other similar problems in Calypso as well, but I can't think of any.

**Comment by dmsnell** [comment]
> If possible, I suggest something low cost. If we can detect that a user is paying a la carte, then we can display a notice at the top, saying that because they are not on a plan, the Plugins UI might not be displaying right.

I don't think that sounds very professional.

If we want to do this on a feature-by-feature basis, it's going to take a lot of work. So far I've had a real difficult time figuring out how to navigate the plan items. Maybe someone who has worked on it all could help us out, but we don't appear to have that data readily available.

**Comment by drw158** [comment]
I think we could make it sound better. It would be better than no notice at all in my opinion. Something like:

> Looks like you aren't on a plan, but you may have certain paid features activated. This page may not reflect the features that are enabled on your site.

Are you saying detecting that generally would be hard, or just detecting if they are paying for a specific feature? Or both would be hard?

**Comment by dmsnell** [comment]
@drw158 right now I don't think we have the data available inside of Calypso indicating individual features like that. The closest examples I could find were the Google Analytics key entry page in the settings panel, which relies on determining if the user has a Business or Enterprise subscription, and the customizer for Custom Design, which loads an iframe from outside of Calypso `¯\_(ツ)_/¯`

Probably a good idea to consider a message like you revised above in the meantime because I'm not sure this is worth adding a bunch of new endpoints or other server-side and Calypso code to make it happen correctly.

**Comment by drw158** [comment]
I agree, I don' t think we should go into detecting individual features.

So it _would_ be a minimal amount of work to detect something like "is a paying user (that is not domains) without a plan"?

But yes, if that is also a lot of work, I think just launching as is would be fine. I have no idea how many users fall into this category.

**Comment by dmsnell** [comment]
@drw158 I don't think we can easily know if the user is paying for something. I'm still looking, but all I can find is whether or not the user has one of the free, premium, business, or enterprise plans, also if there is a domain credit, maybe one more thing. I have tested with a blog where I added the custom domain add-on, but so far I haven't been able to find any way of discovering that the site has that from within Calypso.

**Comment by drw158** [comment]
Sounds like the only hope for doing this short term is to detect that the user has _none_ of the plans.

If the user doesn't have free, premium, business, or enterprise, then display notice.

If that is not possible, then I think I'll just removed this issue from the launch milestone.

**Comment by roundhill** [comment]
I recently touched some code that checked for a la carte upgrades. We'd have to mess up @dmsnell's nice data model though and pass these checks in for the individual plugins...

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/index.jsx#L97

**Comment by drw158** [comment]
Hm I guess I can't make an informed decision without knowing how many users are affected. I'm fine with just launching as is, and seeing if we get reports.

**Comment by roundhill** [comment]
> I'm fine with just launching as is, and seeing if we get reports.

+1, I don't think we'll get many complaints about this.

**Comment by dmsnell** [comment]
> We'd have to mess up @dmsnell's nice data model though and pass these checks in for the individual plugins...

@roundhill I've seen a few of these random indicators for features but nothing standard. Also I don't think we'd have to do a terrible break on the data model in order to provide these functions. The way I envision it is that we would have to provide a list of predicates, one for each plugin that we can detect, then pass the `state` into those predicates. The worst divergence here would be the fact that we stop passing _only data_ in the plugins list.

```js
export myPlugins = [
	name: 'Spline Reticulator',
	category: 'Misc',
	descriptionLink: 'http://spli.ne',
	isEnabled: state => !! getSelectedSite( state ).plan.hasSplineReticulator
]
```

Now in the plugins component we can run the test and display accordingly

**Comment by drw158** [comment]
I'll keep this open, but just remove the milestone

**Comment by mtias** [comment]
@dmsnell I was pointed to https://github.com/Automattic/wp-calypso/tree/master/client/lib/purchases by @stephanethomas for this purpose.

**Comment by dmsnell** [comment]
Thanks @mtias!

**Comment by dmsnell** [comment]
Closing because I think this turned out to be not a big problem.
