### ISSUE TITLE
Payments block: button is not rendered in preview and published post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#50018]
### Steps to reproduce the behavior

1. Go to My Sites > Posts > Add New Post.
2. In the editor, add the `Payments` block.
3. Enter some text in the button.
4. Publish page.
5. Check both the Preview and Published page.

#### What I expected to happen
`Payments` block is rendered on page, containing the button and text.

#### What actually happened
`Payments` block is not rendered on page.
Where the button should be only has:
```
<p>Centred button:</p>
```

### Context
User testing while verifying #47510.

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Browser: Firefox Nightly 87.0a1 (Enhanced Tracking Protection OFF)
Browser: Chrome Version 88.0.4324.150 (Official Build) (arm64)
Browser: Safari Version 14.0.2 (16610.3.7.1.9)

#### Is this specific to the applied theme? Which one?
Tested on multiple themes, same issue.

#### Does this happen on simple or atomic sites or both?
Simple and Atomic.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Moderate - user is unable to use the payments block.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Editor:
![Screen Shot 2021-02-11 at 2 42 31 PM](https://user-images.githubusercontent.com/6549265/107708571-8b11b180-6c78-11eb-872d-b046dbbd72ee.png)

Preview & Published post:
![Screen Shot 2021-02-11 at 2 42 37 PM](https://user-images.githubusercontent.com/6549265/107708590-949b1980-6c78-11eb-9bc9-52ee729e8f96.png)

**Comment by simison** [comment]
The block should not render when Stripe is not connected:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/87168/108178901-a6177200-710d-11eb-9bb6-dcb2e60d8abf.png">


Tho we've talked about making it more clear. :-)

**Comment by worldomonation** [comment]
> The block should not render when Stripe is not connected:
> 
> <img alt="image" width="263" src="https://user-images.githubusercontent.com/87168/108178901-a6177200-710d-11eb-9bb6-dcb2e60d8abf.png">
> 
> Tho we've talked about making it more clear. :-)

Ah, that'd do it. More clarity would definitely be useful, I agree!

**Comment by worldomonation** [comment]
If you don't mind, I can close this bug as `Closed - By design`.
