### ISSUE TITLE
Gutenboarding: Update starter designs to correct some button syntax issues

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#50012]
The Headstart content for the following starter designs are out of date, creating an issue with misaligned buttons in the following designs when they're created via the WP.com/new flow.

- [x] https://alvesstarter.wordpress.com/
- [x] https://barnsburystarter.wordpress.com/
- [x] https://balasanastarter.wordpress.com/
- [x] https://maywoodstarter.wordpress.com/

**Note:** I also did a fresh update of the content on these sites today that may or may not correct an issue with the version of Gutenberg running on WPcom in production. Noting that here for @fullofcaffeine who was looking into that and may require some example sites.

**Comment by andrewserong** [comment]
Also do new annotations for:

* [x] doylestarter
* [x] levenstarter

**Comment by andrewserong** [comment]
Diff to update each of these: D56946-code

**Comment by andrewserong** [comment]
Updated and deployed!
