### ISSUE TITLE
Media: Add image editing capabilities i1

### ISSUE THREAD

**Issue by robobot3000** [Automattic/wp-calypso#5001]
We should allow to edit images in the media gallery, providing functionalities such as crop, rotate, straighten, add text, filters etc.

There are already some mockups prepared by @drw158 and discussion on how to implement this, especially regarding the 

For the first iteration, I think we should add crop, rotate, flip and scale. The two example mocks containing these functionalities are:
![group-11-copy-2](https://cloud.githubusercontent.com/assets/800604/14814370/dab534c8-0b9d-11e6-81b1-c9129b1b3fed.png)
![group-17](https://cloud.githubusercontent.com/assets/800604/14814373/df8471e4-0b9d-11e6-8e3d-853fe07cb480.png)

I created a branch add/image-editor where I will experiment with the canvas element, but I will also consider using plugins if this work proves to be reinventing the wheel.

**Comment by aduth** [comment]
Duplicate of #2098, unless you'd rather keep this one.

**Comment by robobot3000** [comment]
Thanks, @aduth - I'll close this one as a duplicate
