### ISSUE TITLE
Customizer: "Need help setting up your site?" doesn't disappear immediately when clicking on a menu

### ISSUE THREAD

**Issue by david-szabo97** [Automattic/wp-calypso#50025]
### Steps to reproduce the behavior

1. Go to your site -> Customizer
2. Click on any menu (Site Identitfy)
3. See how "Need help setting up your site?" remains in view for the duration of the transition and disappears when the transition finished

#### What I expected to happen
"Need help setting up your site?" should disappear immediately when I click on a menu.

#### What actually happened
"Need help setting up your site?" disappears after the transition finished

#### Browser / OS version
macOS Big Sur 11.2.1
Google Chrome Version 88.0.4324.150 (Official Build) (x86_64)

#### Is this specific to the applied theme? Which one?
I don't think it's theme dependent.

#### Does this happen on simple or atomic sites or both?
Tested on simple only.

#### Is there any console output or error text?
No

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/2256104/107744441-f9a34d80-6d12-11eb-84c5-e371c711d88c.mov

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I attempted to reproduce this issue, but it appears the link for `Need help with setting up your site?` is no longer present in the Customizer.

Closing the issue as `not reproducible`.
