### ISSUE TITLE
Plugins: readme translations do not appear in Calypso

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5003]
#### Steps to reproduce
0. Set your interface language to French.
1. Starting at URL: https://wordpress.com/plugins/jetpack
2. Scroll down to the Description / Installation / FAQ tabs
3. Since [the readme is translated on WordPress.org](https://fr.wordpress.org/plugins/jetpack/), I would expect each one of these tabs to be translated too.

![screen shot 2016-04-26 at 12 20 51 pm](https://cloud.githubusercontent.com/assets/426388/14815041/62b51d06-0ba9-11e6-8d3d-e19d2e95b9da.png)

**Comment by yoavf** [comment]
This could aimost be solved by a simple change like:
```
diff --git a/client/lib/wporg/index.js b/client/lib/wporg/index.js
index b182ecc..138b980 100644
--- a/client/lib/wporg/index.js
+++ b/client/lib/wporg/index.js
@@ -7,8 +7,8 @@ var debug = require( 'debug' )( 'wporg' ),
 /**
  * Internal dependencies
  */
-var jsonp = require( './jsonp' );
-
+var jsonp = require( './jsonp' ),
+       i18n = require( 'lib/mixins/i18n' );
 /**
  * Constants
  */
@@ -26,7 +26,7 @@ module.exports = {
         */
        fetchPluginInformation: function( pluginSlug, callback ) {
                var baseUrl,
-                       query = { fields: 'icons,banners,compatibility,ratings,-contributors' };
+                       query = { fields: 'icons,banners,compatibility,ratings,-contributors', locale: i18n.getLocaleSlug() };
```

However, we need the wporg locale slug, and afaik it's no currently available.
