### ISSUE TITLE
Nav Unification: Show modal for existing users only

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#50037]
**What**

We need to show the nav unification announcement modal for existing users only, not new users.

**Why**

New users will not be aware of any other experience so wont have any context with regards to the announcement of the navigation experience. 

**Acceptance criteria**

* Should a new user sign up to WordPress.com and land in Calypso for the first time since the nav unification. They will not see the nav unification announcement modal.
* Should an existing user login to WordPress.com and land in Calypso for the first time since the nav unification has been enabled they will be presented with the announcement modal.
* Should an existing user close the announcement modal, they will not be presented with it again.

**Comment by tjcafferkey** [comment]
As per @cpapazoglou idea we should enable this for all users with `getCurrentUserDate() > [1 day after launch]`.

This will also be carried out in conjunction with https://github.com/Automattic/wp-calypso/issues/50080 closer to launch date.

Context p1613470540012100-slack-CJS75TX3R

**Comment by getdave** [comment]
Removing `Blocker` label as covered elsewhere. 

@tjcafferkey Let's add this to the [launch tasks tracker Issue](https://github.com/Automattic/wp-calypso/issues/50080).
