### ISSUE TITLE
Editor Checkout: not returning to editor after purchasing upgrade

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50033]
### Steps to reproduce the behavior

1. Go to editor on a site with a Free plan
2. Add a Premium Block and click Upgrade
3. Complete checkout
4. Skip any up-sell nudge if there is one

#### What I expected to happen
I should be redirected back to editor

#### What actually happened
I land on some thank you page with only a _View my new features_ button which is redirecting me to `/plans/my-plan/[SITE_NAME]`

### Context
The original mechanism seems to be still there since I have the correct value stored in cookie: `wpcom_signup_complete_destination`

The new experience is not that bad because on the "thank you" page I have several options. But it would be great to have a button to "Continue where I left off" so I can get back to the page where I wanted to add a Premium Block.

<img width="600" alt="Screenshot 2021-02-12 at 14 34 18" src="https://user-images.githubusercontent.com/14192054/107768796-af849100-6d3f-11eb-8359-b2649a6c48e0.png">

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://cloudup.com/cum3C-6RLu1

**Comment by lukaszwilczakwilnet** [comment]
This task is resolved by another issue https://github.com/Automattic/wp-calypso/pull/62021
