### ISSUE TITLE
Nav Unification: Announcement modal assets updates

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#50038]
**What**

Update the announcement modal images for different environments

**Why**

As per p1HpG7-bcl-p2#comment-44591 comment we should not mention WP.com for Jetpack sites in the announcement modal.

**Comment by ghost** [comment]
New assets: [Modal_Assets.zip](https://github.com/Automattic/wp-calypso/files/6004050/Modal_Assets.zip)

Copy coming soon.

**Comment by getdave** [comment]
Removing `Blocker` as this is covered in our roadmap under "e2e testing fixes".
