### ISSUE TITLE
Checkout: For $0 purchases the message `Money back guarantee` makes no sense

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#50049]
### Steps to reproduce the behavior

1. Add a mapped domain or subdomain at `WordPress.com > My Sites > Manage > Domains > Add a domain to this site` and proceed to checkout
2. At Checkout, look in the right-sidebar that reads `Money back guarantee` ![](https://d.pr/i/Lc6x75+)
_Link: https://d.pr/i/Lc6x75_

#### What I expected to happen
The message `Money back guarantee` should be removed
#### What actually happened
The right-sidebar reads `Money back guarantee` although it makes no sense for a $0 purchase

**Comment by klimeryk** [comment]
cc @Automattic/shilling - this might be already on your radar as you were looking into the $0 domain mapping issue recently 🙇‍♂️
