### ISSUE TITLE
Receipt Email: Include proper instructions link when subdomain is mapped

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#50054]
### Steps to reproduce the behavior

1. Map a subdomain to the site 
2. Check `WordPress.com Receipt` email and click `Follow these instructions` link

#### What I expected to happen
See [Map a Subdomain](https://wordpress.com/support/domains/map-subdomain/) support page.
#### What actually happened
[Use a Domain You Already Own (Domain Mapping)](https://wordpress.com/support/domains/map-existing-domain/) support page opens up (which does mention how to map a subdomain in the first section, but we should be able to distinguish when a subdomain is mapped vs domain and hence be able to include the most specific guide for the user to look at).
### Context
I was testing mapping a subdomain on a series of sites and reviewed the receipts I received to find out the above.
#### Browser / OS version
Any
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Both
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium
#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![](https://d.pr/i/rvwYQy+)
_Link: https://d.pr/i/rvwYQy_

**Comment by Robertght** [comment]
Right now we're getting this after clicking on the "Follow these instructions" link:

![image](https://user-images.githubusercontent.com/6737345/137073639-0059681c-b64f-4539-ad70-991882d53dba.png)

I'm going to close this for now.
