### ISSUE TITLE
Nav Unification: Explore adding WooCommerce admin_menu fixes directly to wc-calypso-bridge as a temporary fix for Atomic sites

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#50065]
Until Atomic sites are running WooCommerce 5.1 (not yet released), they will not have all the fixes in place to have an excellent Nav Unification experience.

Based on discussion in pbIJXs-Ee-p2#comment-1985, we should see if we can make the `admin_menu` changes from the following PRs directly in `wc-calypso-bridge` as well as a temporary measure to fix up Atomic site.

- https://github.com/woocommerce/woocommerce/pull/29088
- https://github.com/woocommerce/woocommerce-admin/pull/6310

**Comment by cpapazoglou** [comment]
Seems that we will wait for WooCommerce 5.1 since pbAPfg-1ad-p2#comment-2622. There is no need to follow that path.

**Comment by mattsherman** [comment]
Agreed. I'm going to close this one.
