### ISSUE TITLE
Payments Block: Unable to insert new block

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#50091]
### Steps to reproduce the behavior

1. Go to worpress.com/page
2. Insert a Payments block. 
3. If Stripe is connected you will be unable to modify the price or add a plan. If Stripe is not connected it will simply add a Button to the page.

Note: Plans can still be added in Calypso, but not in the Editor.

#### What I expected to happen

To be able to modify and add a Payments block.

#### What actually happened

A new Payments block cannot be added.

#### Browser / OS version

OS X, Chrome 87.0.4280.141

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

```
Uncaught TypeError: (void 0) is not a function
    at editor-experimental.js?ver=9.4:28
    at Object.ki (react-dom.min.de439aae.js:176)
    at ji (react-dom.min.de439aae.js:13)
    at mi (react-dom.min.de439aae.js:13)
    at lf (react-dom.min.de439aae.js:13)
    at wi (react-dom.min.de439aae.js:187)
    at Kd (react-dom.min.de439aae.js:32)
    at pc (react-dom.min.de439aae.js:32)
    at Wf (react-dom.min.de439aae.js:34)
    at react-dom.min.de439aae.js:236
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All sites I've tested are impacted. It prevents users from adding new blocks to accept payments so I would regard it as high priority. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Atomic with Stripe connected

![Screen Shot 2021-02-15 at 11 04 19 AM](https://user-images.githubusercontent.com/1900444/107969298-95d08d00-6f7d-11eb-81a7-9a799195d01e.png)

Simple without Stripe connected

![Screen Shot 2021-02-15 at 11 04 52 AM](https://user-images.githubusercontent.com/1900444/107969342-a84ac680-6f7d-11eb-9f65-e3fc5911ec11.png)

**Comment by JoshuaGoode** [comment]
To recap, users cannot add new payment plans via the editor.  Initially discussed internally at p1613396561201300-slack-C0160HSMDQV and a message was shared with View via p1613404129376300-slack-CS0SC36SX

Video demonstration: https://d.pr/v/oYApNw

Screenshots of console errors we're seeing.

<img width="1561" alt="console_2" src="https://user-images.githubusercontent.com/4887830/107969736-27d89580-6f7e-11eb-8882-5db9d5e79b92.png">

<img width="1361" alt="console_1" src="https://user-images.githubusercontent.com/4887830/107969741-29a25900-6f7e-11eb-815d-37b81df748b6.png">

**Comment by stacimc** [comment]
As a workaround: I've tested and I am able to add a new plan through the `wordpress.com/earn/payment-plans/` page and then select that from the dropdown menu in the Payments block. I am only getting the error when trying to create a brand new plan through the block.
