### ISSUE TITLE
Start/Domains shows blank page when 'test' keyword is entered

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#50095]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/start/domains
2. Type in the word 'test' into the search bar
3. Screen will attempt to search for domains with this keyword
4. Page will turn blank

#### What I expected to happen
I expected available domains with the keyword 'test' to appear

#### What actually happened
The page turned white, refreshing the page shows the test keyword saved in the field leading to immediate error and the average customer would not be able to fix this.

(Hint, if you refresh the page start tapping delete to begin removing the test keyword before the error can trigger)

### Context
Transcript hc-26888038

#### Browser / OS version
Chrome / Windows (seems to be an issue on all devices)

#### Is there any console output or error text?

![image](https://user-images.githubusercontent.com/16580129/107982390-f5389800-6f91-11eb-8d6d-216f70042c27.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Blocks purchases since it bugs out the domain tool

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

**Comment by daledupreez** [comment]
This was introduced by #50001. Working on a fix now.

**Comment by klimeryk** [comment]
Thanks for the quickfix! I should have caught that in my patch 🤦
