### ISSUE TITLE
Help: YouTube video embeds broken

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#50102]
#### Main Themes page
1. From https://wordpress.com/themes/ (YOURSITEHERE)
2. Click on the blue help (?) button in the bottom right hand corner of the page
3. Click 'Change your website theme on WordPress.com" > Click "Watch a video"

#### What I expected to happen
I would watch a video on how to change my theme

#### What actually happened
Sad video face - no video to watch (altho the youtube link it's trying to show does work - 3rd party cookie sitch?)
![image](https://user-images.githubusercontent.com/16654218/107994207-2f159880-6faa-11eb-9d50-45d7a07b585e.png)

Console output:
`Refused to display 'https://www.youtube.com/watch?v=yOfAuOb68Hc?rel=0&amp;showinfo=0&amp;autoplay=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

#### Individual Themes page
1. Go to https://wordpress.com/theme/mayland?site= (YOURSITEHERE) (I don't think the actual theme matters)
2. Click on the blue help (?) button in the bottom right hand corner of the page
3. Click Themes: an overview > read more: note title - hit Escape or click "Close"
4. Click Mobile themes > read more: note article that is displayed

#### What I expected to happen
all links are accurate, helpful and relevant

#### What actually happened
Themes: an overview > read more  - popup renders the *child themes* article
Mobile themes > read more > "Private" in title - feature retired almost a year ago. 

### Context
user testing

#### Browser / OS version
chrome and safari

#### Is this specific to the applied theme? Which one?
no, I reproed with multiple themes

#### Does this happen on simple or atomic sites or both?
both
#### Is there any console output or error text?
see above

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
low

**Comment by simison** [comment]
> Refused to display 'https://www.youtube.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Oh, I don't think the YouTube URL would work in the iframe:

`https://www.youtube.com/watch?v=yOfAuOb68Hc?rel=0&amp;showinfo=0&amp;autoplay=1`

It should come via their [embed API instead](https://developers.google.com/youtube/iframe_api_reference):

`https://www.youtube.com/embed/yOfAuOb68Hc`

**Comment by cathymcbride** [comment]
@simison does that mean this has never worked?

**Comment by simison** [comment]
@cathymcbride hard for me to imagine how it could have worked, but I could be wrong and maybe it's more recent change from YouTube.

**Comment by simison** [comment]
Even weirder, here it's as embed URL:

https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/blocks/inline-help/contextual-help.js#L1464-L1470

There are a lot of other YouTube videos in that list and looks like it's happening with others too, e.g. _Settings page -> Add a Site Icon._

**Comment by simison** [comment]
I'll bump this high since it's all those videos across all the sections, not just Themes.

**Comment by creativecoder** [comment]
PR to fix: https://github.com/Automattic/wp-calypso/pull/51291
