### ISSUE TITLE
Global styles sidebar: font preset buttons lost border

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#50134]
When choosing "A" icon for Global styles in the editor, there are buttons to quick-choose some font pairings.

These buttons used to look like buttons, but have regressed since:

**Now (Feb 2021)**
<img width="540" alt="Screenshot 2021-02-16 at 17 14 34" src="https://user-images.githubusercontent.com/87168/108082892-348ee380-707b-11eb-8607-b02f58a0e606.png">

**Before**
<img width="394" alt="Screenshot 2021-02-16 at 17 14 12" src="https://user-images.githubusercontent.com/87168/108082907-36f13d80-707b-11eb-9d2d-29841e455b41.png">

**Comment by porada** [comment]
Can’t reproduce. This could have been a temporary regression.

<img width="1067" alt="Screenshot" src="https://user-images.githubusercontent.com/2060580/121032736-d7df4200-c7ab-11eb-89e5-7387641765f6.png">
