### ISSUE TITLE
Plans: star icon overlaps text in Safari

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#5015]
My site uses the business plan, and today I discovered the newly updated plans page at: https://wpcalypso.wordpress.com/plans/my-plan/shaunandrews.wordpress.com

![screen shot 2016-04-26 at 12 18 29 pm](https://cloud.githubusercontent.com/assets/191598/14825724/012c77a0-0ba9-11e6-9cd3-cbf27eb9bb2f.png)

I noticed that the star icon overlaps the text:

![screen shot 2016-04-26 at 11 58 57 am](https://cloud.githubusercontent.com/assets/191598/14825731/0c6ca81a-0ba9-11e6-8f17-7f1b5cd08a29.png)

You can notice it more when I change the background color:

![screen shot 2016-04-26 at 11 59 33 am](https://cloud.githubusercontent.com/assets/191598/14825738/15556f48-0ba9-11e6-9d69-e4496bc3fc66.png)

Also, we shouldn't use the star gridicon here — we should use the relevant plan illustration like we do in signup:

![screen shot 2016-04-26 at 12 20 22 pm](https://cloud.githubusercontent.com/assets/191598/14825773/42a506f2-0ba9-11e6-88c1-ad290b3b3f16.png)

/cc @artpi @adambbecker

**Comment by lancewillett** [comment]
I can repeat this in Safari on OS X but looks OK in Chrome.

<img width="965" alt="screen shot 2016-04-26 at 9 51 57 am" src="https://cloud.githubusercontent.com/assets/66797/14827045/5b77453c-0b95-11e6-92a8-ab74507a520a.png">
<img width="1067" alt="screen shot 2016-04-26 at 9 52 01 am" src="https://cloud.githubusercontent.com/assets/66797/14827046/5b7831ae-0b95-11e6-8fe4-bbe1c71c336f.png">

**Comment by lancewillett** [comment]
Fixed in 32bb2e7

Visual record from Safari on OS X

![screen shot 2016-04-29 at 9 06 41 am](https://cloud.githubusercontent.com/assets/66797/14921947/b41cf51e-0de9-11e6-906b-a420080a1d44.png)
