### ISSUE TITLE
Non-domain owners can add Email to cart, however cannot complete checkout

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#50155]
### Steps to reproduce the behavior

1. As an administrator of a site (not domain/plan owner), add _Email_ to your cart
2. Proceed to checkout
3. Attempting to complete checkout will result in an error message, and inability to complete the purchase

#### What I expected to happen

I expected to be able to purchase Email plan for my site.

#### What actually happened

I received an error message: `An error occurred during the transaction`

#### Level of impact

This will block the purchase of an Email plan, likely because only the domain owner can purchase this (and not an admin).

Observed in #3745924-zen

#### Screenshot

![Annotation on 2021-02-16 at 15-01-44](https://user-images.githubusercontent.com/39252765/108127570-a7db2a00-7068-11eb-97d3-787447d3e571.png)

**Comment by sstabrizi** [comment]
Thanks for reporting @jonnyruzek. As @daledupreez mentioned, "We clearly have a problem here if we’re only checking that during checkout." I'd agree that there is likely a better place for those checks, as well as some room for updated messaging. Rather than the generic, "An error occurred during the transaction," something like, "Only the domain owner can purchase an email upgrade," or something of that sort.

**Comment by tbradsha** [comment]
I think perhaps G Suite doesn't even let you get to the cart unless the owner, so the logic may be there to expand.

**Comment by Sandkorner** [comment]
Had a user as well that had the same problem. They wanted me to let our "developers" know that this should be pointed out better. 

Just adding this information here as it seems to be a slight pain point for some users.

**Comment by daledupreez** [comment]
This was addressed by a combination of #50700 and D57965-code, which were both deployed earlier this week.

While we don't have all the eligibility checks in place to prevent adding email for a domain, we now catch this before Email actually gets added to the shopping cart. (We're tracking more eligibility requirements in pbLl1t-kG-p2, which includes a few more checks.)
