### ISSUE TITLE
Full site editing: adapt block inserter contextual tips for FSE

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#50169]
In the block inserter we have "contextual tips" for some keywords (just for wpcom):

<img src="https://user-images.githubusercontent.com/87168/108189332-4757f580-7119-11eb-9ba0-f165654a532f.png" alt="" width="400" />

Number of those tips [refer to Customiser](https://github.com/Automattic/wp-calypso/blob/92b4535f0c1cf4753f0a1d136e0cd571c5923262/apps/editing-toolkit/editing-toolkit-plugin/block-inserter-modifications/contextual-tips/list.js#L77-L109) so we should remove those for FSE.

[There was an effort to bring those to core](https://github.com/WordPress/gutenberg/pull/22109), which could be good option to go for.

cc @vindl can you help to put in right backlog?

**Comment by vindl** [comment]
Added this to Cylon's backlog.

**Comment by Addison-Stavlo** [comment]
I dont think this is relevant anymore as im not seeing customizer tips in FSE.
