### ISSUE TITLE
[e2e] Sidebar navigation with nav-unification

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#50174]
As discussed in https://github.com/Automattic/wp-calypso/issues/49250 we need to fix the sidebar navigation when nav-unification is enabled.

The [technical decision](https://github.com/Automattic/wp-calypso/issues/49250#issuecomment-780693083) is 
- manipulating the admin-menu endpoint so that it contains the data-tip-target static keywords 
https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/test/e2e/lib/components/sidebar-component.js#L177

Possibly we won't need to change something more, as the `expandDrawerItem` https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/test/e2e/lib/components/sidebar-component.js#L41 didn't create any problems during my tests.

Acceptance criteria (builds on #50173):
- running `cd test/e2e && env FLAGS='nav-unification' ./node_modules/.bin/mocha specs/wp-calypso-seo-preview.js` will result to tests passing successfully.
- running `cd test/e2e && env FLAGS='nav-unification' ./run.sh -g -s desktop` results to no test failure related to sidebar navigation

**Comment by getdave** [comment]
Removing `Blocker` as this is covered in our roadmap under "e2e testing fixes".

**Comment by cpapazoglou** [comment]
@bsessions85 I have experienced some problems with the approach of adding the needed `data-tip-target` in the admin-menu api https://github.com/Automattic/jetpack/blob/7c93abdede8a7b64694a7bd0534db6a3ed352a79/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L209. 

The thing is, that the menu items are declared either with `add_menu_page` or `add_submenu_page` which do not have a parameter of eg a `classname`. Below is the **Posts** menu example

```
$parent_menu_slug = `https://wordpress.com/posts/[DOMAIN]`
add_submenu_page( $parent_menu_slug, esc_attr__( 'All Posts', 'jetpack' ), __( 'All posts', 'jetpack' ), 'publish_posts', 'https://wordpress.com/posts/[DOMAIN]');
```

so, we could extract `posts` from `https://wordpress.com/posts/[DOMAIN]` and have a mapping of `posts -> side-menu-post` in order to match the selector https://github.com/Automattic/wp-calypso/blob/835de103f7ca993eb121fce0973e9969f3851bb2/test/e2e/lib/components/sidebar-component.js#L128

I am worried though that we are putting an extra effort on development (and performance) just for testing. Being mainly affected from this https://testing-library.com/docs/queries/about/#priority which suggests 

> your test should resemble how users interact with your code (component, page, etc.) as much as possible.

how would you feel using the **role** `navigation` followed by the menu item **Name** eg "Posts" ?

**Comment by bsessions85** [comment]
@cpapazoglou As long as we have a way to know what menu item and submenu item we need to click and it is consistent, even if the language changes, I can work with it.

When I look now I don't see a way to recognize "Post" being a menu so if we can add something there to identify it so we can click it to get the submenu, then we'll need some way to identify the items in the submenu. I think we could probably just use the URL for submenu items if it came down to it. (those don't change in different languages do they?)

**Comment by cpapazoglou** [comment]
Thanks @bsessions85. Let's move on with the title of the item. Regarding hierarchy, the endpoint already serves `type:"menu-item"` for top level and `type:"submenu-item"` for next level. 
![](https://cln.sh/JmMexl+)

If you have drafted a PR, can you relate it to this issue? 

I am closing this one as we are not currently going to make changes to the API.
