### ISSUE TITLE
[e2e] Dismiss nav-unification modal

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#50173]
As discussed in https://github.com/Automattic/wp-calypso/issues/49250#issuecomment-780103846 we need a way to hide the nav-unification modal, otherwise all elements underneath are not "clickable". 

![image](https://user-images.githubusercontent.com/12430020/108197405-01a02a80-7123-11eb-97bd-e3e5436b3753.png)

We can follow this https://github.com/Automattic/wp-calypso/blob/c32e02f590db39784444a0209b3bfdb574b4418e/test/e2e/lib/gutenberg/gutenberg-editor-component.js#L672

Acceptance Criteria:
- running `env FLAGS='nav-unification' ./node_modules/.bin/mocha specs/wp-calypso-seo-preview.js` no longer reports `TimeoutError: Timed out waiting for element with css selector of 'header.masterbar a.masterbar__item' to be clickable`
- putting the logic after the login flow, should be enough

**Comment by getdave** [comment]
Removing `Blocker` as this is covered in our roadmap under "e2e testing fixes".
