### ISSUE TITLE
Remove menu items: Tools -> Other Tools, Settings -> Ratings, Settings -> Polls

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#50193]
As discussed in p7DVsv-ago-p2#comment-34517 we will be removing the following menu items from the admin-menu api https://github.com/Automattic/jetpack/blob/39215e802de7e1fffdb8b31c4fb2a27bde604c69/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L15. This change will affect all environments.

- Tools -> Other Tools
- Settings -> Ratings
- Settings -> Polls

Other Tools | Ratings & Polls
-------|------
![](https://cln.sh/LTGG2u+)|![](https://cln.sh/AEmRpd+)

While removing Ratings & Polls, we should make sure that direct access to these pages is allowed through adding them in `$GLOBALS['_registered_pages']`.

**Comment by blackjackkent** [comment]
I'm working on a diff for this - just about done but stuck on a few questions.
1) I can't find the "Other Tools" menu at all - under what circumstances does that appear?
2) Per @obenland 's comment at p7DVsv-ago-p2#comment-34517, we're removing the Ratings and Polls menu bc they're also accessible in the "Feedback" submenu, but it doesn't appear that that is the case for atomic sites, only simple ones. Am I right in assuming that these menu items should only, therefore, be removed for simple sites and not atomic?

**Comment by cpapazoglou** [comment]
👋 @blackjackkent! 

1. Has been removed here https://github.com/Automattic/jetpack/pull/19114#discussion_r594198906
2. I would suggest consolidating the changes in both environments and move "Ratings" & "Polls" under "Feedback". I will let @obenland decide on this though.

**Comment by obenland** [comment]
> it doesn't appear that that is the case for atomic sites

Nice catch, I wasn't aware of that. Why is there a difference and is there a way we could make Atomic behave as simple here? Is it a permissions issue?

**Comment by blackjackkent** [comment]
@obenland @cpapazoglou I've been refreshing my memory on what I was looking at last week and I think I may have misspoken somewhat - simple sites have links to Ratings and Polls under both Settings and Feedback, but atomic sites have neither; on a completely fresh sandbox with no changes, I can't reach either settings page from my atomic test site (either via a menu link or directly). 

Simple:
![image](https://user-images.githubusercontent.com/13437011/114437881-b8051680-9b8c-11eb-95bd-b58389cb7fd5.png)
![image](https://user-images.githubusercontent.com/13437011/114437892-be938e00-9b8c-11eb-9e85-6d1f5e2f5adb.png)

Atomic:
![image](https://user-images.githubusercontent.com/13437011/114437971-ce12d700-9b8c-11eb-9184-a5fbddda9a60.png)
![image](https://user-images.githubusercontent.com/13437011/114438028-d8cd6c00-9b8c-11eb-97af-968177332575.png)

My atomic site *does* have a "Crowdsignal" menu item, but that takes me to a different screen than anything poll-related on my simple site. 
`https://rosalindwillsatomic.wpcomstaging.com/wp-admin/admin.php?page=crowdsignal-forms-settings`
vs
`https://rosalindwillstest.wordpress.com/wp-admin/options-general.php?page=polls&action=options`

Am I missing something obvious about this? It seems like the desired change for simple sites is still valid but atomic sites don't seem to have the concept at all and so don't require a change.

**Comment by obenland** [comment]
> It seems like the desired change for simple sites is still valid but atomic sites don't seem to have the concept at all and so don't require a change.

Agreed! Let's focus on Simple sites, it looks like Atomic sites would have to [install a separate plugin for those features](https://wordpress.org/plugins/polldaddy/).

**Comment by blackjackkent** [comment]
Awesome - very simple change in that case. Diff is up at D60052-code.

**Comment by kwight** [comment]
Closed in D60052-code.
