### ISSUE TITLE
Plugins (wpcom): Standard Plugins titles should be plural

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#5019]
1. Go to the new Plugins page.
2. Select View all standard plugins

These 2 should be "Standard Plugins" not "Standard Plugin".

#### Screenshot / Video
<img width="481" alt="screen shot 2016-04-26 at 12 33 24 pm" src="https://cloud.githubusercontent.com/assets/618551/14828107/16948c34-0bab-11e6-9b90-fed78c6e3161.png">

<img width="501" alt="screen shot 2016-04-26 at 12 34 03 pm" src="https://cloud.githubusercontent.com/assets/618551/14828132/3072f0b4-0bab-11e6-825b-f28c8af9fb24.png">

**Comment by roundhill** [comment]
I see that it now says 'Plugins'. Does that work for you?

<img width="504" alt="screen shot 2016-04-27 at 10 00 41 am" src="https://cloud.githubusercontent.com/assets/789137/14860757/0a145bd8-0c5f-11e6-98ed-fedd64b1acb7.png">

**Comment by drw158** [comment]
Sure, what does the site title say?

**Comment by roundhill** [comment]
Strange, I've seen it switch back to 'Standard Plugin' a few times. If I switch sites it usually switches back to 'Plugins'.

**Comment by roundhill** [comment]
Maybe it's a cache thing, seems ok in the iOS simulator:

<img width="365" alt="screen shot 2016-04-27 at 1 14 02 pm" src="https://cloud.githubusercontent.com/assets/789137/14866755/00ed0116-0c7a-11e6-98eb-ed0df49508c1.png">

**Comment by drw158** [comment]
Oh, yea, you should check the title after clicking on the View All link. That's the one that is affected.

**Comment by drw158** [comment]
Hm really strange. I just reloaded the page and it changed from "Plugins" to "Standard Plugin".

**Comment by drw158** [comment]
Ok, so the back button in the mobile view, and the browser site title are related.

To reproduce:

1. go to wpcalypso on a phone.
2. go to Plugins
3. click View all standard plugins
4. reload the page

The back button and the browser site title change from "Plugins" to "Standard Plugin"

It should be either Plugins, or Standard Plugins (plural)
