### ISSUE TITLE
Nav Unification: Revise copy on wp-admin toggle for clarity

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#50202]
**What**
Add clarifying copy to the Account Settings wp-admin toggle and provide a link to the nav unification support page in order to provide further guidance to users who may not know what this is. 

> Show advanced dashboard pages
> _Enabling this will replace your dashboard pages with more advanced wp-admin equivalents when possible._ Learn more

**Why**
Currently, this toggle is abstracted from the dashboard and there isn't a lot of context around what it will do. It may be surprising for users if they don't know what wp-admin is or if they navigate away and are unclear why they're suddenly seeing different pages.

**How**
<img width="1440" alt="Desktop - Me" src="https://user-images.githubusercontent.com/67021691/108267479-420aa300-7139-11eb-863b-ecd883ebb531.png">

**Additional context**
>I know what “WP Admin” is but most customers might have no idea. Could there be a away to elaborate this better, and provide support page link where we explain it further?
Folks might be tempted to try this just to see what it does, so perhaps some information what we recommend, or that this is “advanced” setting might be helpful?

**Comment by Aurorum** [comment]
> provide a link to the nav unification support page

Hi @sfougnier, are you aware if that page has been published yet? If so, would it please be possible to share a link to it since I can't find it.

**Comment by getdave** [comment]
> > provide a link to the nav unification support page
> 
> Hi @sfougnier, are you aware if that page has been published yet? If so, would it please be possible to share a link to it since I can't find it.

It is at https://wordpress.com/me/account.

**Comment by tjcafferkey** [comment]
>and provide a link to the nav unification support page

@getdave do we have a support link for the "Learn more"?

**Comment by Aurorum** [comment]
Yes, sorry, the support page is what I was referring to as opposed to the one in the screenshot.

**Comment by getdave** [comment]
> Yes, sorry, the support page is what I was referring to as opposed to the one in the screenshot.

No not available yet I'm afraid. Just FYI, I'm going to tackle this task now.

**Comment by getdave** [comment]
@sfougnier I prepared a PR but we won't have the link to support docs until after launch (see p2rHU0-P9-p2#comment-2647). Therefore I will remove the link and we can follow up once the docs are available.

**Comment by getdave** [comment]
In response to several concerns about this change, I added this PCYsg-vFf-p2#toggle-copy-wpadmin.
