### ISSUE TITLE
SiteSelector: Search looks off on account settings page

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#50219]
### Steps to reproduce the behavior

Note: You need to have more than 6 sites associated with your WP.com account to activate the search on the Site Selector Dropdown.

1. Go to `/me/account`
2. At _Primary Site_ open the Site Selector Dropdown
3. Observe the Search field is off

The component is used at several different places:

- On `/theme/:theme` click on _Activate theme_ and open the site selector
- In the inline help widget: Click _Contact us_
- On `/plans`

#### What I expected to happen

It should look like this (screenshot taken from the themes page on `/theme/:theme`):

<img width="410" alt="Screenshot 2021-02-18 at 10 35 58" src="https://user-images.githubusercontent.com/9202899/108337151-19d08200-71d5-11eb-8196-a1ab7dd4e6c4.png">

#### What actually happened

It looks off (see screenshot below)

### Context

Found while working on the account settings form.

#### Browser / OS version

Tested with latest Firefox and Chrome on macOS

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="404" alt="Screenshot 2021-02-18 at 10 30 03" src="https://user-images.githubusercontent.com/9202899/108336946-e130a880-71d4-11eb-9346-e65e8136ddec.png">

**Comment by cathymcbride** [comment]
Good eye!
