### ISSUE TITLE
WordPress.com on Atomic (AT sites): Block Editor on Calypso throws error when Gutenberg plugin is inactive

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#50228]
### Steps to reproduce the behavior

1. Ensure the website is Atomic (websites on Business/eCommerce plan with customized plugin or theme installed OR active Jetpack Backup)
2. Ensure plugin Gutenberg is INACTIVE (and plugin Classic Editor is INACTIVE -- no editor plugins active on the website) -- or the plugin Gutenberg on the website is NOT symlinked
3. Create or edit post/page on Calypso
4. Editor gives `The editor has encountered unexpected error` and minified React error on Console

#### What I expected to happen
The editor to opens on Block Editor as we have set Gutenberg as default editor -- regardless the plugin is active or not

#### What actually happened
Editor gives `The editor has encountered unexpected error` and minified React error on Console

It seems like when no editor plugins active, Calypso unable to find available editor, hence the error? 🤔 (only my throwaway thought, though!)

### Context
User reports

#### Browser / OS version
All

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?

```
Oc@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:169:18
ah/<@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:80:357
T@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:95:457
zj@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:227:428
Th@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:152:225
tj@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:152:152
Te@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:146:151
Pg/<@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:61:68
unstable_runWithPriority@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react.min.js:25:260
Da@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:60:280
Pg@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:61:16
ha@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:60:451
Ja@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:224:400
enqueueSetState@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react-dom.min.js:214:411
w.prototype.setState@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/vendor/react.min.js:20:440
value@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/plugins.min.js:2:6825
a/<@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/hooks.min.js:2:5031
w@https://c0.wp.com/c/5.6.1/wp-includes/js/dist/plugins.min.js:2:4931
H@https://widgets.wp.com/wpcom-block-editor/calypso.editor.min.js?ver=20210218:1:11774
K@https://widgets.wp.com/wpcom-block-editor/calypso.editor.min.js?ver=20210218:1:20104
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It doesn't block any purchases, and affect many sites

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
So far the reports coming from users. Some HEs able to replicate it, some unable to (me included.)

**Comment by simison** [comment]
cc @Automattic/team-calypso

**Comment by JoshuaGoode** [comment]
The issue seems to be Calypso/editor iframing related as no site should require the Gutenberg plugin to be active and activating it isn’t a real solution.

It appears that, on these sites, the issue occurs when going through Calypso and accessing the editor like: https://wordpress.com/post/{site}/{post_id}

Going in through the WP-Admin works fine: https://{site}/wp-admin/post.php?post={post_id}&action=edit

Looks like iframing is broken unless the Gutenberg plugin is active.

**Comment by tbradsha** [comment]
27842321-hc

**Comment by tbradsha** [comment]
27842692-hc

**Comment by yansern** [comment]
Error is originating from `registerPlugin('a8c-wpcom-block-editor-close-button-override', {` in `iframe-bridge-server.js`. More details to follow later.

To test on a non-symlinked Gutenberg atomic site, create an atomic ephemeral site with Gutenberg plugin unchecked during creation.

This cannot be replicated on atomic site (Business/eCommerce plan) created with `/new` or `/start` with gutenberg plugin disabled after.

**Comment by happychait** [comment]
13722499-hc

Activating the Gutenberg plugin solved the issue.

**Comment by yansern** [comment]
Error seems to be the use of `<MainDashboardButton>` slotfill which breaks the editor. https://developer.wordpress.org/block-editor/developers/slotfills/main-dashboard-button/

I wonder what has recently changed with this one.

**Comment by yansern** [comment]
This should be now fixed with the deployment of D57277-code.

**Comment by tbradsha** [comment]
@yansern Ran across this just now in 27847111-hc; they tried in two browsers and got the same error. Perhaps there's still a lingering bug?

**Comment by lakellie** [comment]
I also just received another report in 8624538-hc.

**Comment by ctdealba** [comment]
It seems the bug has not been fixed yet. Another report: 23366421-hc. 
ZD: https://woothemes.zendesk.com/agent/tickets/3753538

**Comment by Addison-Stavlo** [comment]
Curious if we have tried asking users to clear their browser cache and try it again?

**Comment by simison** [comment]
There's indeed 1 day (or so?) cache buster on these scripts.

Refreshing the page with shift+refresh might help.

**Comment by ctdealba** [comment]
> Curious if we have tried asking users to clear their browser cache and try it again?

Yes, I have done that and user says is not working after doing that.

**Comment by Addison-Stavlo** [comment]
>Yes, I have done that and user says is not working after doing that.

<s> Ok, digging for more details on their site setup.  Im no longer able to repro on my test site after the earlier fix. </s>

Edit - I can repro on production, although patching the fix on my sandbox fixes the behavior.  Wondering why the fix isn't live. 🤔

**Comment by tbradsha** [comment]
Clearing the cache and/or trying another browser that hadn't used WordPress.com before didn't seem to fix it.

**Comment by Addison-Stavlo** [comment]
Update - This is now fixed on production (there was a cache issue on the servers).  Users will need to clear their browser cache again and it should be working after that.

**Comment by Addison-Stavlo** [comment]
^^ with that this should be resolved.  but as always feel free to reopen if this issue persists after another cache clearing.

**Comment by noahtallen** [comment]
Related issue regarding server-side cache busters: https://github.com/Automattic/jetpack/issues/12254
