### ISSUE TITLE
Nav Unification: reintroduce Classic Bright selection while retaining fallback styles in IE11

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#50231]
In https://github.com/Automattic/wp-calypso/pull/49710 we ensured that Classic Bright shows when intentionally selected.

Unfortunately, this change introduced a regression in IE11 where the fallback for the CSS custom properties wouldn't be included in the CSS anymore. The change thus had to be reverted in https://github.com/Automattic/wp-calypso/pull/50230. We'll need to reimplement the change while ensuring that the fallback styles for IE11 aren't compromised.

For details see slack-C7YPUHBB2/p1613644049033400

![Markup on 2021-02-18 at 14:53:34](https://user-images.githubusercontent.com/1562646/108366836-1818b580-71f9-11eb-9b76-859ea316b8bc.png)

**Comment by scinos** [comment]
Found a piece of the puzzle:

With the "good" selector (`:root {...}`) in `_default.scss`, when I run `yarn prepare` in this `packages/calypso-color-schemes`, I get a file in `packages/calypso-color-schemes/js/index.js` with an object with lots of `--color-*` properties.

With the "bad" selector (`:root, .color-scheme.is-classic-bright .is-nav-unification {}`), I don't get any `--color-*` properties in that file.

That file seems to be used in https://github.com/Automattic/wp-calypso/blob/43f57f367516466635e46fae4aa1a50528e37ad6/apps/notifications/postcss.config.js#L4

The file is generated by https://github.com/Automattic/wp-calypso/blob/43f57f367516466635e46fae4aa1a50528e37ad6/packages/calypso-color-schemes/bin/build-css.js#L26

It uses [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) to generate the `js` file. And the README of that package says:

> Note: This plugin only processes variables that are defined in the :root selector.

This issue also seems related: https://github.com/postcss/postcss-custom-properties/issues/198, which was fixed and released in https://github.com/postcss/postcss-custom-properties/blob/master/CHANGELOG.md#920-september-18-2020. But we are using version `9.1.1`

**Comment by frontdevde** [comment]
Thanks for reporting this, @scinos! I've just made the same discovery in slack-CJS75TX3R/p1613663106189900. Like you said it looks like it's related to the limitation of `postcss-custom-properties` only working if the selector is `:root{}` specifically.

A `quick fix` could be to duplicate the declaration of the custom properties for `:root{}` and `.color-scheme.is-classic-bright .is-nav-unification {}` respectively and clean up this duplication once Nav Unification has been fully rolled out.

**Comment by zdenys** [comment]
I just noticed that Classic Bright if selected, sets the dark color instead. And in my understanding, it is due to the above issue. But if it's not, I'll report it separately.

https://user-images.githubusercontent.com/39308239/108539790-1dedc400-72e9-11eb-9ad3-7d4fbf4ba3d4.mov

**Comment by frontdevde** [comment]
@zdenys Yes, that is due to the above issue. No need to report separately. Thank you!
