### ISSUE TITLE
Site Editor: unable to type N in Dotcom integration

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#50246]
A Dotcom integration was reported in testing round that's not happening in core. It's not possible to type in the `N` letter into text.

**Comment by alaczek** [comment]
I run into this as well. I noticed there are console errors when I try and type the letter `N` (and `n`).

![image](https://user-images.githubusercontent.com/4550351/108428381-92e1df00-7292-11eb-8981-953addeed792.png)

Browser/system: Chrome 88.0 / macOS Catalina 10.15.7

**Comment by alaczek** [comment]
I tried this in FF (85.0) now, and while I was able to type `n`, the console error was still there

![image](https://user-images.githubusercontent.com/4550351/108429390-01736c80-7294-11eb-8066-12c506a51b03.png)

In Safari (14.0.2), I could not type `n`, and of course, the error is there as well in the console:
![image](https://user-images.githubusercontent.com/4550351/108429903-b3ab3400-7294-11eb-9283-bb9816135885.png)

**Comment by jeyip** [comment]
When we instantiate the editor iframe, we capture events from within the iframe and then manually bubble the events to its parent context [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/iframe/index.js#L56-L100).

The code to register masterbar hotkeys is, strangely enough, capturing those bubbled events from the editor iframe. Normally, the masterbar hotkey listens for the letter `n` to toggle the notifications panel in wp-admin. See the gif below.

![2021-02-19 00 03 54](https://user-images.githubusercontent.com/5414230/108475823-15907d00-7246-11eb-9ecb-604b657142de.gif)

Those same masterbar event listeners, however, are being initialized when we visit the site editor, and as a result, are triggered when we're typing `n` anywhere in the editor canvas.

![2021-02-19 00 13 16](https://user-images.githubusercontent.com/5414230/108476794-50df7b80-7247-11eb-830f-2319510d4209.gif)

What's odd is that masterbar keydown event [is being namespaced](https://api.jquery.com/event.namespace/), which is specifically meant circumvent problems like this. Namespacing is a jQuery specific feature, so manually dispatching events must be an edge case.

Whatever magic we're doing to remap the events from the iframe triggers the masterbar keydown event listener. I confirmed this by commenting out the "event bubbling" we do in Gutenberg iframe. It stopped the error. Then I commented out the masterbar keydown event listener. This also stopped the error.

There are a few solutions I see to this problem:

1. Prevent the masterbar hotkeys from being reinitialized in the site editor page
2. Find an alternative approach to manual event bubbling for the Gutenberg editor iframe

If anyone else has thoughts, definitely chime in 👍

**Comment by mattwiebe** [comment]
> that masterbar keydown event is being namespaced, which is specifically meant circumvent problems like this

Unfortunately that's not what event namespacing does. It's largely a way for a plugin to be able to manipulate its own events without impacting events registered by another plugin.

**Comment by mattwiebe** [comment]
I've got a fix for this in D57358-code

**Comment by mattwiebe** [comment]
The fix is live, closing this

**Comment by ramonjd** [comment]
@mattwiebe I can still reproduce this on Wordpress.com

1. Create a new FSE site
2. Open up the site editor, then edit a template part, e.g., Footer
3. Try to type in a block area, or create a new one and enter text.
4. For me `n`, `s` and `a` are causing problems. Hmmm NSA 🤔 

No JS errors in the console I'm afraid! Seems like the parent frame is capturing keystrokes. Hitting '`n`'  opens my Reader feed sometimes too :D

![keystrokes](https://user-images.githubusercontent.com/6458278/114795885-0146a780-9dd3-11eb-87fc-5c419ec162f0.gif)

I can create a new issue if you like?

Discussion and context:
p1618444606071000-slack-CS0SC36SX

**Comment by annezazu** [comment]
This is happening with the Site Tagline block when using Template Editing mode on WordPress.com. Would it be advantageous to create a new issue or can someone dig into a fix? For now, reopening :)

**Comment by ramonjd** [comment]
I just pilfered @vindl's work from D60728-code

https://github.com/Automattic/jetpack/pull/20014

Not sure if that fits in with the way Jetpack does things.

It did occur to me that we could put the check inside a filter and apply it, but we'd need to do it on WPCOM and Atomic/Jetpack anyway so I don't think it'd be more efficient.
