### ISSUE TITLE
Update design annotations

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#50257]
Over in D57320-code we manually updated some annotations to fix a coming soon bug.

During testing we noticed that it had been a while since these annotations had been generated, and that they are in great need of an update.

D57323-code delivers that update!

**Comment by simison** [comment]
@ramonjd @apeatling ok if I add this to View backlog?

**Comment by ramonjd** [comment]
Thanks for reminding me about that one. @simison I'll assign to myself.
