### ISSUE TITLE
Focused Launch: "Name your site" step not shown for sites created from non-en accounts

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50269]
### Steps to reproduce the behavior

1. Change the language of your _WordPress account_ to a language different from English
2. Create a site via `/start`
3. Enable Focused Launch A/B test
4. In the editor, click on the Launch button in the header bar
5. Notice how the "Name your site" step in Focused Launch Summary view is missing

#### What I expected to happen

The "Name your site" step in the Summary view should be visible, since the user never edited their Site title

### Context

It looks like the check that is made to see if the site still has the default title is not working for non-en sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

This is what I got in Focused Launch on a newly created site in spanish (note the absence of the "Name your site" step)

<img width="1792" alt="Screenshot 2021-02-19 at 14 36 39" src="https://user-images.githubusercontent.com/1083581/108511932-d9e6c900-72c0-11eb-96ed-7a6da4b031c9.png">

**Comment by StefanNieuwenhuis** [comment]
Is this happening on both the `iframe` and `wp-admin`?

**Comment by ciampo** [comment]
> Is this happening on both the iframe and wp-admin?

Definitely in Calypso, probably also in `wp-admin`

**Comment by StefanNieuwenhuis** [comment]
It looks like `isSiteTitleStepVisible` saved in the `automattic/launch` store is the culprit but I'm not sure why its value is `false` when a site is created in another language than English.

<img width="608" alt="Screenshot 2021-02-19 at 14 57 12" src="https://user-images.githubusercontent.com/12104589/108513352-c63c6200-72c2-11eb-8833-db6c42c9beec.png">

**Comment by ciampo** [comment]
@StefanNieuwenhuis you may want to take a look at these lines of code: https://github.com/Automattic/wp-calypso/blob/8e78abe71630b4fce1a03c7ca27472ae1daf746c/packages/launch/src/focused-launch/summary/index.tsx#L574-L581

And, therefore, these lines: https://github.com/Automattic/wp-calypso/blob/8e78abe71630b4fce1a03c7ca27472ae1daf746c/packages/launch/src/utils.ts#L10-L19

Probably there are discrepancies between the translations that we have in the front-end for 'Site Title' and the default site title that a site gets from the backend

**Comment by yansern** [comment]
Just for reference.

`wp-content/lib/blogs/blogs.php` at line 79-81.

```
		/**
		 * If there is no `$blog_title` passed to the API, default to a
		 * localized version of "Site Title"
		 */
		if ( '' === trim( $blog_title ) ) {
			$blog_title = __( 'Site Title' );
		}
```

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/50311
