### ISSUE TITLE
Site Editor: Navigation block might break for an infinite loop 

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#50277]
The repro steps for this are weird, but I could reduce them all the way down to these, although the issue only happen sporadically.

### Steps to reproduce the behavior

1. Open the Site Editor on a site using Seedlet (although it might happen with other themes as well).
2. Select the Navigation Block.
3. Click on its icon to open the "Convert To" dropdown.
4. Click anywhere else to deselect the block.

Or:

1. Open the Site Editor on a site using Seedlet (although it might happen with other themes as well).
2. Insert an image in the Site Logo block (either upload or from the media library).
3. Select the Navigation Block.
4. Click anywhere else to deselect it.

#### What I expected to happen

Nothing!

#### What actually happened

The block broke with the customary "This block has encountered an error and cannot be previewed." message.

A minified React error is thrown in the console. It links to the [React error decoder](https://reactjs.org/docs/error-decoder.html/?invariant=185) with this message:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="640" alt="Screenshot 2021-02-19 at 15 15 57" src="https://user-images.githubusercontent.com/2070010/108523051-65faef80-72c5-11eb-88b0-54203b3243c9.png">

<img width="536" alt="Screenshot 2021-02-19 at 15 16 22" src="https://user-images.githubusercontent.com/2070010/108523093-70b58480-72c5-11eb-9941-1c5c6fb255c0.png">

**Comment by vindl** [comment]
Should this go to core repo or was it Dotcom specific?

**Comment by Copons** [comment]
> Should this go to core repo or was it Dotcom specific?

@vindl Dotcom specific 😭

**Comment by vindl** [comment]
> @vindl Dotcom specific 😭

Dang. 😢

**Comment by Addison-Stavlo** [comment]
I also reproduced this by clicking the "+" inside the navigation block to add a new item, then clicking somewhere else inside the template part to deselect it while the quick inserter popover was still present.

**Comment by Copons** [comment]
As it turns out, this looks extremely similar to https://github.com/WordPress/gutenberg/issues/29391, so it might indeed be a Core issue.

The one major difference, is that the repro steps here don't trigger the error in Core.
Also, on WPCOM it's the `Navigation` block itself that crashes, wheres in Core is "just" a `NavigationLink` (or the entire Site Editor, but not the Post Editor 😅 ).

**Comment by Addison-Stavlo** [comment]
this seems to have been resolved
