### ISSUE TITLE
My Home: User can be prompted to launch their already-launched site.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#50279]
If a user launches their site from the editor before having visited My Home, they will first get the launch celebration card, and then their first view of the site checklist (if they select it):

<img width="1012" alt="Screen Shot 2021-02-19 at 8 42 22 AM" src="https://user-images.githubusercontent.com/349751/108534227-c02c8e00-728e-11eb-810d-494ef4d147d2.png">

They're told they'll be guided through launching their site, which they've just done – and it's clearly check off as complete in the list.

**Comment by kwight** [comment]
This could be easily fixed by dropping the mention of launch, something like "Next, we'll guide you through completing your site setup."

**Comment by allilevine** [comment]
> This could be easily fixed by dropping the mention of launch, something like "Next, we'll guide you through completing your site setup."

Are we making this change for everyone, or just podcast sites?

**Comment by kwight** [comment]
It would be for all cases – the same problem exists for non-Anchor signups.

**Comment by kwight** [comment]
This checklist no longer exists, and launching the site shows an appropriate card on seeing My Home.
