### ISSUE TITLE
Global Styles: Font styling is not applied to the editor

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#50289]
### Note
This is only happening on full site editing enabled WordPress instances

### Steps to reproduce the behavior

1. Create a new site editing enabled site
2. Take note of the font styles in the onboarding flow design preview
3. Open the site editor or the post editor and verify that the fonts don't match 

#### Gutenboarding Design Preview
<img width="371" alt="Screen Shot 2021-02-19 at 2 26 02 PM" src="https://user-images.githubusercontent.com/5414230/108568280-b02ca280-72be-11eb-9b65-3581b8eeb895.png">

#### Site Editor
<img width="1283" alt="Screen Shot 2021-02-19 at 2 25 39 PM" src="https://user-images.githubusercontent.com/5414230/108568335-c8042680-72be-11eb-876d-8da9fb00f7ce.png">

#### Post Editor
<img width="1280" alt="Screen Shot 2021-02-19 at 2 27 21 PM" src="https://user-images.githubusercontent.com/5414230/108568310-bde22800-72be-11eb-9313-2729e4208cc8.png">

#### Live Site
<img width="1281" alt="Screen Shot 2021-02-19 at 2 27 43 PM" src="https://user-images.githubusercontent.com/5414230/108568326-c5093600-72be-11eb-8574-e5b397d26944.png">

#### What I expected to happen
Editor fonts should match the design preview and live site

#### What actually happened
Editor fonts didn't match

**Comment by vindl** [comment]
I think this is likely the special case of a more general problem with Global Styles that I'm tracking here https://github.com/Automattic/wp-calypso/issues/50358. Closing in favor of that issue, but feel free to reopen if that's not the case.
