### ISSUE TITLE
Map Block - Dispappears When Adding 50 or More Markers.

### ISSUE THREAD

**Issue by annbingle** [Automattic/wp-calypso#50288]
Please take note of the following:
1. This has been tested on both AT and Premium site, works fine on AT Site.
2. An account from Mapbox is used for testing.

### Steps to reproduce the behavior

1. Go to My Site > Site > Pages > Add New.
2. Click on the + sign then search for Map block. Click on it.
3. On the Map block settings, enter the Mapbox Access Token.

<img width="1106" alt="Screen Shot 2021-02-20 at 03 53 14" src="https://user-images.githubusercontent.com/40605613/108560652-07bb2480-7338-11eb-8ec2-84a13b0be358.png">

4. Click on the Marker Icon to start adding the Markers.

<img width="1106" alt="Screen Shot 2021-02-20 at 03 53 14 (1)" src="https://user-images.githubusercontent.com/40605613/108560710-202b3f00-7338-11eb-95a0-13d8e2933b29.png">

#### What I expected to happen
Once the markers have been added, this is how it will look like on the actual page. This is when I added my 49 markers.

<img width="959" alt="Screen Shot on 2021-02-20 at 03-57-37" src="https://user-images.githubusercontent.com/40605613/108560869-57015500-7338-11eb-8955-f424509b022e.png">

#### What actually happened

The moment I added the 50th marker, the map disappears on the live page then the markers were automatically converted into a link.

<img width="979" alt="Screen Shot on 2021-02-20 at 03-59-21" src="https://user-images.githubusercontent.com/40605613/108560918-6a142500-7338-11eb-8f42-905403620f0b.png">

#### Is this specific to the applied theme? Which one?
The user's theme is Ovation.
My AT Site's theme is Maisha.
My Premium site's theme is Mayland
The user's theme is Ovation

#### Does this happen on simple or atomic sites or both?
Only on Simple Site.

#### Is there any console output or error text?
None.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
No it is not affecting any block purchases nor other pagees.

**Comment by annbingle** [comment]
zd-3754129

**Comment by philnick206** [comment]
Related issue: https://github.com/Automattic/wp-calypso/issues/43930

**Comment by JoshuaGoode** [comment]
Thanks for the report!

The Map block comes from Jetpack and it looks like we have an ongoing report over there at https://github.com/Automattic/jetpack/issues/17139

I'm going to close this issue in favor of that one. 

If we see more user reports, let's log them over there.

**Comment by JoshuaGoode** [comment]
Highlighting that an alternative solution for now is to use Google Maps.  User can create custom maps with markers using Google My Maps: https://wordpress.com/support/google-maps/#embedding-a-custom-map
