### ISSUE TITLE
CoBlocks: "Replace Image" button incorrectly positioned

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#50294]
### Steps to reproduce the behavior

1. Create a new site editing enabled site
2. Navigate to the site editor
3. Upload an image
3. Open the block inspector and verify that the "Replace Image" button is incorrectly positioned

## Site Editor
<img width="285" alt="Screen Shot 2021-02-19 at 3 14 10 PM" src="https://user-images.githubusercontent.com/5414230/108571519-3350f700-72c5-11eb-9beb-9034b942d821.png">

## Post Editor
<img width="282" alt="Screen Shot 2021-02-19 at 3 17 01 PM" src="https://user-images.githubusercontent.com/5414230/108571697-9cd10580-72c5-11eb-83ab-e7c5eb3653d1.png">

**Comment by jeyip** [comment]
### Site Editor
<img width="2293" alt="Screen Shot 2021-02-19 at 3 43 38 PM" src="https://user-images.githubusercontent.com/5414230/108573448-78772800-72c9-11eb-9096-5ab49120efa8.png">

### Post Editor
<img width="2293" alt="Screen Shot 2021-02-19 at 3 43 32 PM" src="https://user-images.githubusercontent.com/5414230/108573460-7c0aaf00-72c9-11eb-9916-0a5a43d64481.png">

**Comment by davipontesblog** [comment]
Closing as fixed as CoBlocks has been updated now.
