### ISSUE TITLE
Signup: Step 1 text needs to be consistent with button clicked previously

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#5029]
If I select 'create a website' then the Step 1 I'd suggest shouldn't include the words blog. Similarly, if I choose a blog, saying website is not a great experience either.

<img width="711" alt="2016-04-26 at 22 11" src="https://cloud.githubusercontent.com/assets/253067/14834362/06047f9a-0bfc-11e6-82c1-cdcabcf9f891.png">

As I've been very clear about what I am choosing to make by selecting either a blog or website, having this double message feels a bit weird.

**Comment by folletto** [comment]
> If I select 'create a website' then the Step 1

Screenshot? 

I think this has changed, so might not be relevant anymore. Can you check?

**Comment by karmatosed** [comment]
Yep this also has been changed.
