### ISSUE TITLE
Embeds: Flickr Video Embeds not working

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#50304]
### Steps to reproduce the behavior

1. Go to Add New Post
2. Add a Flickr Video URL to embed it
3. Hit enter to let it load/embed
4. See the word "Forbidden" and the video not displaying

<img width="854" alt="Screen Shot 2021-02-20 at 3 30 16 PM" src="https://user-images.githubusercontent.com/31680407/108607800-9fe4f800-7390-11eb-8703-3c05bb5058d2.png">

I have left the broken embed on a post on my test site here: https://writemiss.blog/2021/02/20/1054/

#### What I expected to happen

For the video to embed/load as they used to, and as specified in our docs.

#### Is this specific to the applied theme? Does this happen on simple or atomic sites or both?

This is not theme specific and can be reproduced on both Simple and Atomic sites. This was reported by two customers and reproduced by two different Happiness Engineers. The videos are public and they do load directly at the Flickr URLs.

#### Is there any console output or error text?

<img width="1306" alt="Screen Shot 2021-02-20 at 15 21 18" src="https://user-images.githubusercontent.com/31680407/108607865-0407bc00-7391-11eb-9140-3e34e20fa366.png">

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It is affecting multiple sites for new Flickr Video embeds. It also seems to be applying to past embeds, and not just new ones going forward, so some customers have the word "Forbidden" across their sites where it formerly showed content.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

#user-report

**Comment by adelineyaw** [comment]
Case: 3755867-zd-woothemes

**Comment by msilbers** [comment]
customer report in 3758345-zd

**Comment by msilbers** [comment]
> I have left the broken embed on a post on my test site here: https://writemiss.blog/2021/02/20/1054/

It appears that embeds added with a link are now working, but the Shortcode that we mention here does not seem to be working: https://wordpress.com/support/videos/flickr-video/#embedding-with-theshortcode

Working with link embed, though with quite a lot of blank space above the video: https://writemiss.blog/2021/02/20/1054/
Not working with Shortcodes (both versions mentioned in the doc, and using the same video): https://writemiss.blog/2021/02/24/1065/

**Comment by msilbers** [comment]
This is now resolved, my earlier update was because I tested with a bad video. Both customers who reported this have the embeds working again as well.
