### ISSUE TITLE
Signup: step 2 message adjustment suggestion

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#5030]
Part of the message in Step 2 is “No need to overthink it”, this is coupled with saying I can switch later. This felt really weird for me during some self testing. 

It sort of felt abrasive and I don’t know how to switch later. If I was a normal user, probably I'd also not know what 'switching' was or what switching involved. Maybe I can do it later, but what does that take? It made me assume I am overthinking - sort of by saying it - which was a really weird experience.

Perhaps we could clear this up a little in language use.

**Comment by folletto** [comment]
I guess you're referring to the `/themes` step? 
_(step ordering changes depending on which funnel you're in)_

![screen shot 2016-05-20 at 15 34 26](https://cloud.githubusercontent.com/assets/4389/15431134/621c4d88-1ea0-11e6-8f9e-b79e099931ed.png)

The text seems changed now. Does that work?

**Comment by karmatosed** [comment]
@folletto I think this has been fixed yes. I now also have seen that better text.
