### ISSUE TITLE
Build: Consistently failing when splitChunks enabled

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#50316]
I've been getting reports from seeing the following error while developing Calypso locally:

![](https://cldup.com/vS1dtOhWpf.png)

Thus far, I've been unable to reproduce it consistently. Folks reported that it often occurred during switching branches, but also sometimes after making a single change in the current branch.

Today I've found a reliable way to reproduce the error. It appears to be something we're not handling properly with code splitting and chunking. 

We should fix this, as it seems to be impacting many of us.

### Steps to reproduce the behavior

* Build Calypso as usual - `yarn start` and verify it runs okay in the browser.
* Apply this diff to your local Calypso:
```
diff --git a/client/layout/index.jsx b/client/layout/index.jsx
index 6c2e71fd17..c71101724b 100644
--- a/client/layout/index.jsx
+++ b/client/layout/index.jsx
@@ -49,6 +49,8 @@ import { getReaderTeams } from 'calypso/state/teams/selectors';
 import { isAutomatticTeamMember } from 'calypso/reader/lib/teams';
 import { isWpMobileApp } from 'calypso/lib/mobile-app';
 
+import { Button } from '@wordpress/components';
+
 /**
  * Style dependencies
  */
@@ -297,6 +299,7 @@ class Layout extends Component {
 					<AsyncLoad require="calypso/blocks/legal-updates-banner" placeholder={ null } />
 				) }
 				<QueryReaderTeams />
+				<Button />
 			</div>
 		);
 	}

```
* Calypso should compile successfully.
* Open Calypso in the browser again or refresh the current tab.
* You'll see the error shown in the screenshot above.

#### What I expected to happen

* Calypso to still work.

#### What actually happened

* The main entry point chunk was no longer working.

**Comment by tyxla** [comment]
While I haven't dug into it further, it looks like it's a code splitting / chunking problem. Maybe we fail to identify the chunks after rebuilding and there is a bigger change to chunks or chunk order.

What I noticed is that when I change webpack's `optimization.splitChunks.chunks` from `all` to `async`, I can no longer reproduce this error. This can't be the fix, though, because it'll likely cause a regression in code splitting.

**Comment by tyxla** [comment]
cc @scinos @jsnajdr in case you're interested to take a stab at it.

**Comment by scinos** [comment]
What I've found so far:

After applying the patch, webpack decides to move modules around between chunks. As result, the new code now requires the new chunk `vendors-node_modules_wordpress_i18n_build-module_index_js-node_modules_lodash-es__createWrap_-7a4517`. This should be loaded via a `<script>` tag in the initial HTML, however *it is not there*. In fact, the list of `<script>` tags in the initial HTML doesn't change at all after applying the patch, even some chunks have changed.
