### ISSUE TITLE
Nav Unification: Announcement modal copy updates

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#50322]
**What**

Update the announcement modal copy for different environments

**Why**

As per p1HpG7-bcl-p2#comment-44591 comment we should not mention WP.com for Jetpack sites in the announcement modal.

**Acceptance criteria**

**Comment by tjcafferkey** [comment]
Hey @sfougnier 👋🏻   do we have any update on the copy changes to the modal here?

**Comment by getdave** [comment]
Removing the `Blocker` label as this is tracked elsewhere on our roadmap.
