### ISSUE TITLE
Button styles leaking to editor UI

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#50332]
Regular simple site, using Hever theme, Firefox, while proxied, many buttons seem to be visually broken.

Image block, buttons look suspiciously round-cornered and hover state is black:

<img width="492" alt="Screenshot 2021-02-22 at 17 22 06" src="https://user-images.githubusercontent.com/87168/108728789-8e3b5600-7532-11eb-9bef-816067878042.png">

Social icons block is busted, here are "pills" and "only logos" styles chosen from the sidebar — the blue background probably shouldn't be here and these should be circles:

<img width="382" alt="Screenshot 2021-02-22 at 17 20 53" src="https://user-images.githubusercontent.com/87168/108728857-a01cf900-7532-11eb-83d4-854f120d353e.png">
<img width="351" alt="Screenshot 2021-02-22 at 17 20 45" src="https://user-images.githubusercontent.com/87168/108728858-a0b58f80-7532-11eb-8f4f-df45bf5c5976.png">

Classic block buttons:

<img width="635" alt="Screenshot 2021-02-22 at 17 19 16" src="https://user-images.githubusercontent.com/87168/108729060-d2c6f180-7532-11eb-8a7c-028dad0e13ec.png">

**Comment by WunderBart** [comment]
It seems to be theme related. On Blank Canvas it all looks good. I can see that it's broken for i.e. Mayland:

| Blank Canvas | Mayland  |
| ------------- | ------------- |
| <img width="644" alt="Screenshot 2021-02-22 at 16 51 32" src="https://user-images.githubusercontent.com/1451471/108732901-43b7da80-752e-11eb-9432-3b89783c3a85.png"> | <img width="813" alt="Screenshot 2021-02-22 at 16 47 20" src="https://user-images.githubusercontent.com/1451471/108732389-ce4c0a00-752d-11eb-828a-acea565a77bd.png"> |

**Comment by simison** [comment]
👍 Twenty Twenty One theme worked.

👎 Shawburn theme broken:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/87168/108734131-d1e48e80-7537-11eb-9283-f020cbd7cf9b.png">

**Comment by jffng** [comment]
This should be resolved since https://github.com/Automattic/themes/pull/3326 was merged + deployed, let me know if you are still encountering issues. Thanks!
