### ISSUE TITLE
Launch button doesn't disable, reappears in another spot after being clicked. Clicking again results in browser error

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#50351]
### Steps to reproduce the behavior

1. start a new site (wordpress.com > `add new site` is fine)
2. Select the .wordpress domain, theme and font pairs (coutoire and default font pairs were chosen in this example) > Continue
3. On the What features will you need, click `skip for now`
4. select a premium plan
5. <site gets built>
6. Pay
7. you should be in the editor now
8. delete all the content (or don't)
9. click Launch
10. note that the launch button moved a little, but is still there > click it again

#### What I expected to happen
I am only able to click the launch button once

#### What actually happened
The launch button doesn't go away or disable after I click it, so when I click it again, I get a scary "Leave site?" Popup from Chrome. If you wait and only click once, you'll see the button go away and you will be directed to the https://wordpress.com/start/launch-site/domains-launch page

### Context
p58i-a5v-p2
After signing up, I made a change in the editor and attempted to click launch and it warned me that I was leaving the site. I hit cancel and was taken away from editor anyway. (3:50)

#### Browser / OS version
chrome latest - but don't think this is browser specific

#### Is this specific to the applied theme? Which one?
reproed with multiple themes

#### Does this happen on simple or atomic sites or both?
simple so far, haven't check atomic yet

#### Is there any console output or error text?
nope

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
hits new users - is clearly something wrong creating the first page of my new site

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
p2 link above has entire video

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
