### ISSUE TITLE
Launch Site: don't prompt to launch site when editing a Template Part on an unlaunched site

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#50356]
### Steps to reproduce the behavior

1. Have a Full Site Editing-enabled, unlaunched site. (Or create one: https://horizon.wordpress.com/new?flags=gutenboarding/site-editor )
2. In wp-admin or Calypso, go to Appearance → Template Parts
3. Edit a template part
4. Although I do see the "Update…" link that would allow me to save without launching, it seems like not the right place for launching.

I doubt we would want this for Templates, either.  

#### What I expected to happen
Don't prompt to launch from a Template Part (or Template)

#### What actually happened
Hard to see how to not launch when updating Template (Part).

**Comment by Addison-Stavlo** [comment]
Since we cannot edit template parts this way anymore, this is an easy fix! 😆
