### ISSUE TITLE
Store|Woo: When Store is removed, only removal message should be shown on Store dashboard

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#50354]
When Store is removed, the only thing shown on the Store dashboard should be the removal notice. We've seen a report where this is not the case:

<img width="558" alt="markup-2021-02-18-at-12 15 17" src="https://user-images.githubusercontent.com/2098816/108764456-9f7b6700-7520-11eb-9a17-9a427267755d.png">

**Comment by becdetat** [comment]
> the only thing shown on the Store dashboard should be the removal notice

Is this really the case? Don't we still want to promote setting up WC?

**Comment by mattsherman** [comment]
> Is this really the case? Don't we still want to promote setting up WC?

The Store dashboard can only be accessed by directly going to the URL. So, I would think that nearly everybody ever going to `/store` URL from this point forward is doing so because they have something bookmarked or in their browser history.

We could consider redirecting to `/woocommerce-installation` if they don't have WooCommerce installed already. That should be pretty easy. I'll see.
