### ISSUE TITLE
Editor Broken on RTL Sites with Gutenberg 10.0 Active

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#50350]
### Steps to reproduce the behavior

1. Create an AT'd site
2. Set the site's language to one that is RTL from the General tab of the Manage > Settings area of WordPress.com: [https://wordpress.com/settings/general/](https://wordpress.com/settings/general/)
3. Try to open the post or page editor with Gutenberg 10.0

#### What I expected to happen
The editor would open as it had previously

#### What actually happened
A white screen is displayed, the editor never loads

### Context
I ran into two reports of it in chat (27849269-hc and 27035706-hc), and was able to duplicate it on my test site with Twenty Twenty as the theme, and all plugins other than Jetpack and Gutenberg disabled. Switching back to English resolved the issue.

#### Browser / OS version
macOS 11.2.1
Chrome 88.0.4324.182
Firefox 86.0

#### Is this specific to the applied theme? Which one?
It's not, no

#### Does this happen on simple or atomic sites or both?
Atomic only from my testing

#### Is there any console output or error text?
Yep!

![Markup on 2021-02-22 at 14:30:58](https://user-images.githubusercontent.com/4000628/108760789-15c99a80-751c-11eb-89ec-6bd337f217d0.png)

![Markup on 2021-02-22 at 14:31:51](https://user-images.githubusercontent.com/4000628/108760794-182bf480-751c-11eb-8c6b-a34228dce00d.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It affects more than one site

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

**Comment by happychait** [comment]
I had a customer report it in 27937667-hc

Worked around by disabling the Gutenberg version 10.0.1

**Comment by Nic-Sevic** [comment]
another report here: 3765990-zen

**Comment by mrsjaved** [comment]
another report here: 3766410-zd-woothemes

**Comment by metabreakr** [comment]
#27356691-hc

**Comment by tbradsha** [comment]
27957897-hc

**Comment by edequalsawesome** [comment]
Fixed in Gutenberg 10.0.2 🎉
