### ISSUE TITLE
Nav Unification: All Jetpack Functionality Missing From Menu on Jetpack Sites

### ISSUE THREAD

**Issue by macmanx2** [Automattic/wp-calypso#50359]
When viewing a Jetpack site through the new unified nav, the only way to reach Jetpack features is if you know the URL you're supposed to go to.

<img width="1487" alt="Screen Shot 2021-02-22 at 12 45 31 PM" src="https://user-images.githubusercontent.com/4856235/108783499-76f46c80-7522-11eb-96fb-7bfaadca3b6c.png">

The above screenshot is from one of my Jetpack sites. I was able to view stats because I knew the URL, but as you can see in the sidebar, nothing is highlighted because there is no Stats option.

In fact, all Jetpack functionality is missing. This is crucial, because most Jetpack functionality only lives in Calypso, very little remains in wp-admin.

Compare that to this WordPress.com site:

<img width="1494" alt="Screen Shot 2021-02-22 at 12 46 06 PM" src="https://user-images.githubusercontent.com/4856235/108783664-b9b64480-7522-11eb-8827-c5118e9bc91b.png">

As you can see there, not only is the Stats menu visible, but so are the rest of the applicable Jetpack options.

I found this issue affects all of my Jetpack sites, all running WordPress 5.6.2 and Jetpack 9.4.

**Comment by macmanx2** [comment]
Props to @deancroyal who just found #50225 as I was finishing this up, which probably will be the fix.

**Comment by mmtr** [comment]
@macmanx2 This should've been solved as of 9.4.1, which was released a couple of weeks ago but only internally so you need to manually update it or wait for Jetpack 9.5.

**Comment by macmanx2** [comment]
@mmtr Excellent! I'll wait for 9.5 so I can keep up with what the users are experiencing.
