### ISSUE TITLE
Me / Help: HTML entity encoding

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#5035]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/help
2. Search for "facebook"
3. See that under the "Jetpack Documentation" section, a listing is shown with an incorrectly-encoded ampersand (see screenshot below)
#### Browser / OS version

Chrome/OSX
#### Screenshot / Video

![screen shot 2016-04-26 at 4 36 30 pm](https://cloud.githubusercontent.com/assets/108942/14836453/7137fb2c-0bcd-11e6-8fcc-7d5d6147bd47.png)

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided.

![screen shot 2016-07-25 at mon jul 25 12 33 03 pm](https://cloud.githubusercontent.com/assets/1119271/17112627/0b8f388e-5264-11e6-8510-c671829d3908.png)
<sup>Seen at https://wordpress.com/help using Safari 9.1.1 on Mac OS X 10.11.5</sup>

**Comment by lancewillett** [comment]
This shouldn't be hard to fix: checking for entities in API results (or avoiding output as escaped HTML when it's not needed).

**Comment by bkilrain** [comment]
Hi there - I've always wanted to contribute to WP and I think this is a great issue to get my feet wet with. Is it ok if I give it a shot?

**Comment by alisterscott** [comment]
@bkilrain: absolutely! We welcome all contributions. Please let me know if you would like someone to review/test your fix when you get to that stage.

**Comment by bkilrain** [comment]
Thanks @alisterscott - I've actually got the fix done already. Just working through the contributing guidelines now. Mind if I tag you for review?

**Comment by alisterscott** [comment]
@bkilrain: absolutely, please do!

**Comment by bkilrain** [comment]
@alisterscott Okey dokey, I think that'll do it. I didn't write tests as it's quite minor. But I can go down that road if you think it's necessary. Whenever you have a moment, please check out the code and let me know if anything needs to be tweaked. 😄

**Comment by alisterscott** [comment]
Thanks for the fix @bkilrain, this is now running in Production: https://wordpress.com/help

**Comment by bkilrain** [comment]
@alisterscott Oh no - I just found out there is already a decodeEntities helper function. I'll refactor to use that one. Should I open a new Issue or just another PR?

**Comment by alisterscott** [comment]
No worries. Just open a new PR and add me as a reviewer. Thanks.
