### ISSUE TITLE
New Page Layout Picker: Call for Testing P2 and facilitation 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#50362]
Once Page Layout Picker is feature complete:

- [x] write up CfT, instructions [here](pbAok1-1Rg-p2#comment-4087)
- [x] set atomic up testing site
- [x] parse feedback

**Comment by p-jackson** [comment]
> - [ ] parse feedback

If only there was a BNF for human feedback 😔

**Comment by p-jackson** [comment]
Call for testing done and feedback collected
