### ISSUE TITLE
Reader: lists created and deleted in Atlas still show up in Calypso and trying to edit one results in a "thats bad" error

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#5036]
Steps to reproduce:

1. Start at https://wordpress.com and switch to a site with a list (make one if needed)
1. Click Manage next to the list
1. Create a new list by typing in a list name and clicking the "+" button
1. Click Reader in the top toolbar and verify the new list shows up
1. Click Manage next to the list that was created and deleted via Atlas
1. Click Delete
1. Click OK
1. Check to see if the list was actually deleted
1. Click Manage next to the list again

<strong>Result:</strong> if you create a list in Atlas and then delete it, it still shows up in Calypso and when you try to manage the list you get an error that says, "thats bad"

<strong>Video:</strong> [1m4s](https://cloudup.com/cG2DJYxDKJm)

![screen shot 2016-04-26 at tue apr 26 10 39 04 pm](https://cloud.githubusercontent.com/assets/1119271/14842053/072d1fe4-0c01-11e6-88d5-59a072d1cbaa.png)

**Comment by bluefuton** [comment]
Thanks @designsimply! This will be fixed when we implement list deletion in Calypso (#641).

**Comment by designsimply** [comment]
Closing in favor of #641
