### ISSUE TITLE
Track how often the “faux FAB” is clicked in wp-admin.

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#50367]
See paYJgx-1nM-p2#comment-1722.

Add `utm` tracking to see how often folks interact with the faux FAB we're adding in https://github.com/Automattic/jetpack/pull/18885

## Useful links

* Jetpack Analytics module - https://github.com/Automattic/jetpack/blob/1fa0e841b6a8d4c514f00282f75cfa497d1164ad/projects/plugins/jetpack/_inc/client/lib/analytics/README.md
* Firing analytics events in Jetpack - https://github.com/Automattic/jetpack/blob/1fa0e841b6a8d4c514f00282f75cfa497d1164ad/projects/plugins/jetpack/_inc/idc-notice.js
* MC - `marketing/utms/ - useful tool to generate UTM links

cc @mattwondra

**Comment by jeherve** [comment]
> `utm`
> [...]
> Jetpack Analytics module

I believe we should be able to rely on Tracks for such a scenario, since the icon will only be displayed on sites that have accepted our terms of service already.
Since we're in wp-admin already, it may just be a matter of adding the `jptracks` class and the `data-jptracks-name attribute like so (not tested):

```diff
diff --git a/projects/plugins/jetpack/modules/masterbar/inline-help/class-inline-help.php b/projects/plugins/jetpack/modules/masterbar/inline-help/class-inline-help.php
index e801360f4..dc264dc1b 100644
--- a/projects/plugins/jetpack/modules/masterbar/inline-help/class-inline-help.php
+++ b/projects/plugins/jetpack/modules/masterbar/inline-help/class-inline-help.php
@@ -77,7 +77,13 @@ class Inline_Help {
 
 		$gridicon_help = file_get_contents( __DIR__ . '/gridicon-help.svg', true );
 
-		echo '<div class="inline-help"><a href="https://wordpress.com/help" target="_blank" rel="noopener noreferrer" title="' . esc_attr__( 'Help', 'jetpack' ) . '" class="inline-help__button">' . wp_kses( $gridicon_help, $svg_allowed ) . '</a></div>';
+		printf(
+			'<div class="inline-help"><a href="%1$s" target="_blank" rel="noopener noreferrer" title="%2$s" class="inline-help__button jptracks" data-jptracks-name="%3$s">%4$s</a></div>',
+			'https://wordpress.com/help',
+			esc_attr__( 'Help', 'jetpack' ),
+			'jetpack_masterbar_inline_help',
+			wp_kses( $gridicon_help, $svg_allowed )
+		);
 	}
 
 	/**

```

Noting that you can `localStorage.setItem( 'debug', 'dops:analytics' );` to check what events are being fired in your browser console.

**Comment by getdave** [comment]
That's based on https://github.com/Automattic/jetpack/blob/41fe374f32d0fa35bb66b4ca492e0b337ee7c6cd/projects/packages/tracking/src/js/tracks-ajax.js#L29 right?

**Comment by jeherve** [comment]
Yep, correct! That library is available on all admin pages for everyone whose site is connected to WordPress.com:
https://github.com/Automattic/jetpack/blob/7d76353666972a89c43556766acb0edb739cb4ff/projects/plugins/jetpack/src/class-tracking.php#L31

**Comment by getdave** [comment]
Turns out we will use the `utm` parameters as this auto triggers both GA and Tracks events to be fired by Calypso.

Now handling in https://github.com/Automattic/jetpack/pull/18885.
