### ISSUE TITLE
Bug: Links to CONTRIBUTING.md broken in DevDocs

### ISSUE THREAD

**Issue by v3rse** [Automattic/wp-calypso#5037]
URL: http://calypso.localhost:3000/devdocs

What I expected:
![Expected](http://i.imgur.com/FDrrKu5.png)

What happened instead:
![Unexpected](http://i.imgur.com/DNEQLzm.png)

Steps to reproduce:
Clicking the links to `CONTRIBUTING.md` in [The Calypso Guide](http://calypso.localhost:3000/devdocs/CONTRIBUTING.md) and the [search page](http://calypso.localhost:3000/devdocs?) point to the wrong path.

Browser/OS version:
Ubuntu 14.04 LTS
Chrome Version 50.0.2661.86 (64-bit)

**Comment by lancewillett** [comment]
Thanks! We'll fix that up shortly.

**Comment by v3rse** [comment]
Looking to work on that if that's ok. Preparing a pull request.

**Comment by lancewillett** [comment]
See background in #3390 and #4479.

**Comment by v3rse** [comment]
Thanks for the background info. Will make the necessary changes to the Pull Request.
