### ISSUE TITLE
Nav Unification: nav items are missing translations for Spanish locale

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50373]
### Steps to reproduce the behavior

1. Set a site's locale to spanish
2. Notice how some nav items have an empty text label
3. Notice how some other nav items (e.g. Contact and "Collapse menu") are still in english

#### What I expected to happen

All items should be translated and visible for the correct locale

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/1083581/108842759-0c9f0300-75da-11eb-9f9b-83380ce1b842.png)

**Comment by cpapazoglou** [comment]
Here is the WP Admin of the same site

Nav Unification Disabled | Nav Unification Enabled
-------|------
![](https://cln.sh/RvJsCR+) | ![](https://cln.sh/kkjiI4+)

Regarding the empty menu items there is a combination of the following:
- the count shouldn’t be part of the translation https://github.com/Automattic/jetpack/blob/88e250f6388c17ec49caa79097dea8174f7bafa8/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L479
- the translation is wrong (it should be `Plugins %s`)
- the sanitization function could use a different approach, so only tags are removed but text is kept (e.g. <span>Hello</span> -> Hello) https://github.com/Automattic/jetpack/blob/acfc9de09c35ae0f8b03f1869602ecd103c09779/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L388-L396

Moreover, "Collapse menu" didn't pass through translation. Fixed here https://github.com/Automattic/wp-calypso/pull/50443

I don't have the problem with "Contact" though, which correctly appears as "Contacto"...
