### ISSUE TITLE
Domains: Unable to change primary domain for site/page never finishes loading.

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#50388]
### Steps to reproduce the behavior

1. Go to Upgrades -> Domains
2. Click on the ellipsis next to the domain I want to make primary
3. Click Make Primary

#### What I expected to happen

The primary domain for my site changes to the chosen domain.

#### What actually happened

A JS error is thrown, because the page never finished loading.

### Context

The plan for my site expired and the domain was reverted to the `wordpress.com` one. I wanted to change it back to the proper domain after I got the plan renewed.

#### Browser / OS version

Firefox 85.0.2 (64-bit) / macOS Big Sur 11.2.1 (20D74)

#### Does this happen on simple or atomic sites or both?

This happens on a WordPress.com Simple site.

#### Is there any console output or error text?

```
Uncaught TypeError: this.props.domains[a] is undefined
    ki https://wordpress.com/calypso/evergreen/domains.2f557714988259de0140.min.js:1
    ki https://wordpress.com/calypso/evergreen/domains.2f557714988259de0140.min.js:1
    Ni https://wordpress.com/calypso/evergreen/domains.2f557714988259de0140.min.js:1
    onClick https://wordpress.com/calypso/evergreen/home.529f447cd56202d79ebf.min.js:1
    a https://wordpress.com/calypso/evergreen/90402.5726392cd16931476efa.min.js:2
    p https://wordpress.com/calypso/evergreen/90402.5726392cd16931476efa.min.js:2
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It affects only my site for now.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/184938/108871697-12a8da00-7602-11eb-93fd-fe81489f8707.mov

### Additional notes

This happens with both sandboxing the API and not sandboxing it.

**Comment by klimeryk** [comment]
Thanks for reporting! Looks like the issue here is from the downgrade process - we clear the primary domain for the given site, but since you had a .blog subdomain, we should have set _that_ as the primary domain, but we did not. And since we hide the wordpress.com subdomain when there's a .blog subdomain present, Calypso can't find it and throws an error :(

It should be a fairly easy fix on the backend - I'll try to get to it this week 🙇

**Comment by kelliepeterson** [comment]
This is fixed.
