### ISSUE TITLE
Site Editor: Can’t undo Premium Content transform when previous block was a template part

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#50396]
### Steps to reproduce the behavior

1. Create a new FSE site via Horizon flow.
2. Click on Header Template Part Block label.
3. Transform to Premium Content Block.
4. Click undo button.

#### What I expected to happen

The block would transform back to a template part block.

#### What actually happened

One of two situations.

- The site editor would "crash" and I'd be in the dashboard with incomplete CSS
- or my Macbook fans would run like mad and the undo button would just not respond.

### Context

We may remove this functionality in https://github.com/Automattic/jetpack/issues/25662 but there may be a site-editor-related bug or a premium content block bug here that should be looked at regardless.

**Comment by dsas** [comment]
Obsoleted - [template parts no longer take part in block transforms](https://github.com/WordPress/gutenberg/pull/42090)
