### ISSUE TITLE
"Included in paid plans" wording is incorrect in domains with monthly plans contexts.

### ISSUE THREAD

**Issue by aneeshd16** [Automattic/wp-calypso#50391]
On the "Use My Own Domain" domains step, the copy is incorrect in these cases:

### Logged In, with a free site
1. Go to /domains/add/, click on "Use a domain I own". The copy in "Map your domain" says `Included in paid plans`.
<details>
<summary>View screenshot</summary>

![image](https://user-images.githubusercontent.com/5436027/108873129-e3559580-7620-11eb-98c5-981fbcc883e8.png)

</details>

2. Click on "Map a domain". The text in the top right is `Included in paid plans`.
<details>
<summary>View screenshot</summary>

![image](https://user-images.githubusercontent.com/5436027/108874478-324ffa80-7622-11eb-801e-082ad962cd4a.png)

</details>

### Logged In, with monthly plan
1. Go to /domains/add/, click on "Use a domain I own". The copy in "Map your domain" says `Free with your plan`.
<details>
<summary>View screenshot</summary>

![image](https://user-images.githubusercontent.com/5436027/108874926-ae4a4280-7622-11eb-858b-005f861ad4d1.png)

</details>

2. Click on "Map a domain". The text in the top right is `Free with your plan`.
<details>
<summary>View screenshot</summary>

![image](https://user-images.githubusercontent.com/5436027/108875106-d6d23c80-7622-11eb-9c35-0e7644a304c6.png)

</details>

### Onboarding flow, /start/free and /start/<monthly-flow>
Create an account, on the domains step click "Already own a domain". (Reported by @niranjan-uma-shankar here: https://github.com/Automattic/wp-calypso/pull/50121#issuecomment-784094149)

1. Click on "Transfer your domain". The copy in the top right is `One additional year of domain registration included in paid plans.`
<details>
<summary>View screenshot</summary>

![image](https://user-images.githubusercontent.com/5436027/108875530-4c3e0d00-7623-11eb-9ef2-c81b80e77055.png)

</details>

2. Go back, click on "Map your domain". The copy in the top right is `Included in paid plans`.
<details>
<summary>View screenshot</summary>

![image](https://user-images.githubusercontent.com/5436027/108875939-b48cee80-7623-11eb-8398-5036f8ccc345.png)

</details>

#### What I expected to happen
There are 2 main issues:
1. The copy "Included with paid plans" should be "Included with annual plans".
2. The text "Free with your plan" should not be shown if a monthly plan is present. This can be fixed here:
https://github.com/Automattic/wp-calypso/blob/d43ffa74eae82ef02b99e12185813f0566a5d123/client/lib/cart-values/cart-items.js#L1303-L1305

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

**Comment by aneeshd16** [comment]
Domain mapping **is** free with monthly plans. Closing this issue.

**Comment by niranjan-uma-shankar** [comment]
> Click on "Transfer your domain". The copy in the top right is One additional year of domain registration included in paid plans.

> Domain mapping is free with monthly plans. Closing this issue.

How about Domain Transfer? Looks like we charge for domain transfer for monthly plans.

**Comment by aneeshd16** [comment]
Thanks! I opened a new issue here: #50433
