### ISSUE TITLE
Site Editor: Customizer should not be available in nav sidebar when Block theme active

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#50405]
### Steps to reproduce the behavior

1. Create an FSE site via Horizon flow.
2. Exit Site Editor to "Dashboard".
3. Hover over Appearance in Nav Sidebar.
4. See link to Customize.

#### What I expected to happen

No option to see Customizer with a Block theme active, like core.

![image](https://user-images.githubusercontent.com/545779/108911485-ea62b080-75ec-11eb-89d2-64b88ffb009e.png)

#### What actually happened

I saw a customizer link.

![image](https://user-images.githubusercontent.com/545779/108911340-c2734d00-75ec-11eb-9f2c-5637a9277984.png)

#### Context

This may be a regression related to nav sidebar updates.

**Comment by obenland** [comment]
Some context and discussion around this on Slack: p1614116522072300-slack-CHN6J22MP

We should make sure nav-unification only replaces menu items that it also removes (any non-false return value from [`remove_menu_page()`](https://developer.wordpress.org/reference/functions/remove_menu_page/)). I'm sure there are plugins out there that remove Core menu items that currently get re-added.

**Comment by Addison-Stavlo** [comment]
> We should make sure nav-unification only replaces menu items that it also removes (any non-false return value from remove_menu_page())

D57545-code does that for the customizer and it seems to fix this issue!  It looks like there will be a lot of other menu/submenu items to update in this way as well though.

**Comment by mattwiebe** [comment]
This was fixed by #19114, which no longer blindly re-registers the Customizer submenu because it only works by adjusting existing submenus to reference their menu parent's updated WPCom URL.
