### ISSUE TITLE
Japanese: Confusing copy in the popup showing up before activating block-based themes

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#50418]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/account and change Interface Language to Japanese
2. Go to "Design > Themes" and try activating one of the themes in the "Recommended themes" section(in other words, block-based themes)

#### What I expected to happen

The copy for the second option should be:

THEME_NAME のホームページコンテンツを使用して既存**の**ホームページ**を**下書きにする。

instead of:

THEME_NAME のホームページコンテンツを使用して既存ホームページの下書きにする。

![Screen Shot on 2021-02-24 at 15:09:34](https://user-images.githubusercontent.com/32432463/108956282-d2edfb00-76b2-11eb-9106-dc16f980c0f9.png)

**Comment by emilyaudela** [comment]
Updated the string in GlotPress [here](https://translate.wordpress.com/projects/wpcom/ja/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=304926&filters%5Btranslation_id%5D=9838430). The updated translation should show up in 24 hours.

**Comment by hacchism** [comment]
Thanks @emilyaudela✨
