### ISSUE TITLE
Signup: JS TypeError when starting the flow

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50431]
### Steps to reproduce the behavior

1. Open browser JS console
2. Go to `/start` and see the following error

<img width="1504" alt="Screenshot 2021-02-24 at 13 29 25" src="https://user-images.githubusercontent.com/14192054/109001212-586eac80-76ad-11eb-973b-d79eec6f50c4.png">

### Context
Mentioned also in p1614169688017500/1614169230.016800-slack-CRNF6A9DX

**Comment by yansern** [comment]
Initially attempted in https://github.com/Automattic/wp-calypso/issues/50431.
Fixed in PR https://github.com/Automattic/wp-calypso/pull/52056.
