### ISSUE TITLE
New Onboarding: show modal when hitting the back button

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50435]
Note this may be applicable also for going back after completing `/start` onboarding.

This will fix https://github.com/Automattic/wp-calypso/issues/50389

As explained in https://github.com/Automattic/wp-calypso/issues/49565#issuecomment-784341234, an improvement to the current UX could be to show a modal when the user presses the back button at the end of the New Onboarding creation flow. Initial designs:

![106597113-9ff69280-655e-11eb-952b-6d713124ab81](https://user-images.githubusercontent.com/87168/106599412-b05c3c80-6561-11eb-8c7b-4d61dfa30489.png)

This could be potentially used:

- when hitting the back button while in the checkout screen at the end of New Onboarding site creation flow (related to https://github.com/Automattic/wp-calypso/issues/49565#issuecomment-771585671 and pb5gDS-xu-p2)
- when hitting the back button while in the editor, after creating a new site (related to #50389)
- when hitting the back button at the end of the "Add new domain" flow (see https://github.com/Automattic/wp-calypso/issues/49565#issuecomment-783645131)

---

@ollierozdarz @klimeryk and @Automattic/luna can coordinate on how to implement this UX improvement

Related:
p7DVsv-9p1-p2

**Comment by razvanpapadopol** [comment]
We might want to see this as a new flow that we show to the users landing on `/start` 0-5 minutes after they just created a site. A similarly designed step is currently in the `domain-only` flow:

<img width="1660" alt="Screenshot 2021-05-14 at 15 39 25" src="https://user-images.githubusercontent.com/14192054/118272034-b485e780-b4ca-11eb-9fa5-a7e9fdfda304.png">
