### ISSUE TITLE
Nav Unification: IE11 issues

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#50440]
Creating this as a group issue for IE11 issues

1.) The hover state on submenu items has a weird background
<img width="280" alt="Screenshot 2021-02-24 at 15 55 54" src="https://user-images.githubusercontent.com/1562646/109021108-dc7b6100-76ba-11eb-8011-fd21e797034e.png">

2.) It looks like Flyout menus are not showing currently. This is less of an issue as it sounds as the parent menu items can be clicked and reveal the submenu. It needs to be fixed eventually though as it's inconsistent with wp-admin. 

![8vdFhSLyGgalvvmr2CPHMd1OiOxDesI40jSEue7T](https://user-images.githubusercontent.com/1562646/109021399-219f9300-76bb-11eb-93c8-ee0466ce0d83.jpeg)

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

We've discontinued IE11 support, so this issue should be closed as `Closed - Won't Fix`.
