### ISSUE TITLE
Editor Checkout: Checkout loading screen appears when Calypso loading screen should

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#50450]
### Steps to reproduce the behavior

1. Insert premium block in editor
2. Click upgrade
3. See loading screen for checkout
4. See Calypso plans page instead

![2021-02-24 13 35 02](https://user-images.githubusercontent.com/545779/109055820-438e1b00-76a5-11eb-9f93-b16882392ad3.gif)

#### What I expected to happen

See a Calypso-esque loading screen. Not a checkout one.

**Comment by sirbrillig** [comment]
FWIW the redirect to the plans page happens because the cart is empty when checkout finishes loading. So whatever is supposed to be adding that block to the cart is not working.

**Comment by cathymcbride** [comment]
@apeatling does this fall to your team?

**Comment by sirbrillig** [comment]
There's a loose possibility that this is a regression caused by https://github.com/Automattic/wp-calypso/pull/49440 although I'm hopeful it's not. It would be really helpful to see what the URL looks like just after you click that Upgrade button. If it looks something like `/checkout/example.com/some_product_slug` (which would then quickly change to `/checkout/example.com`) then that PR might have caused a problem somehow. If it is always `/checkout/example.com` then it's likely to be some other cause. I'm trying to look for the code where that button comes from but I'm not sure where it lives... it doesn't appear to be part of calypso.

**Comment by sirbrillig** [comment]
Oh, looking at the link preview in the gif, actually, it _does_ look like it might be related to that PR. 🤔 I've made a revert PR in https://github.com/Automattic/wp-calypso/pull/50453 and we can use it to test to see if this problem still exists.

**Comment by ianstewart** [comment]
@sirbrillig Issue still happens for me when testing the branch in https://github.com/Automattic/wp-calypso/pull/50453 .

**Comment by michaeldcain** [comment]
Just confirming what Ian said, I don't think striping the url is the issue. I think the product isn't actually being added to the cart - Gutenberg Checkout starts to load and then redirects to /plans/ with an empty cart (just as regular Checkout would with an invalid product).

**Comment by michaeldcain** [comment]
FWIW, it looks like the upgrade link is correct (see screenshot), I just think Gutenberg Checkout overrides the href.

![Screen Shot 2021-02-24 at 3 15 13 PM](https://user-images.githubusercontent.com/942359/109061019-172dcb00-76b4-11eb-806a-cac03dc0a7cb.png)

![Screen Shot 2021-02-24 at 3 21 14 PM](https://user-images.githubusercontent.com/942359/109060931-fd8c8380-76b3-11eb-9276-c8423bad84e9.png)

**Comment by sirbrillig** [comment]
Thanks for testing. I'm not sure what's going on then. It must be something to do with Gutenberg checkout.

> I think the product isn't actually being added to the cart - Gutenberg Checkout starts to load and then redirects to /plans/ with an empty cart (just as regular Checkout would with an invalid product).

If it's helpful, checkout actually will not redirect to the plans page if there's an invalid product. It will display an error and an empty cart. 

<img width="793" alt="Screen Shot 2021-02-24 at 3 50 46 PM" src="https://user-images.githubusercontent.com/2036909/109064191-15fe9d00-76b8-11eb-92cd-1bc5dec64cc6.png">

We only get the redirect if you load checkout with an empty cart and no errors.

**Comment by razvanpapadopol** [comment]
https://github.com/Automattic/wp-calypso/pull/50460 should fix this one
