### ISSUE TITLE
Nav Unification: Missing Settings Item - Security (Atomic)

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#50473]
Apologies if this was mentioned somewhere (although I couldn't find any record of it).

In the new navigation for atomic sites, there is no Settings → Security. See this screenshot:
![image](https://user-images.githubusercontent.com/30727666/109119477-dcea2980-7798-11eb-84f2-c12f313f6332.png)

**Comment by cpapazoglou** [comment]
Thanks for reporting! Closing this as duplicate https://github.com/Automattic/wp-calypso/issues/49310!
