### ISSUE TITLE
My Home: Dismiss mechanism can be confusing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#50489]
The dismiss mechanism for our primary My Home cards can be confusing and/or frustrating, depending on users' expectations.

<img width="1206" alt="Screen Shot 2021-02-25 at 8 32 13 AM" src="https://user-images.githubusercontent.com/349751/109184706-1e9cb500-7744-11eb-9ebd-9c8f78b36edc.png">

One issue is that the cards are only ever visible in the primary area; we have no location for a user to later visit them if they so choose. If they understand that, they might end up keeping cards visible as a weird "todo" reminder. If they don't, they might never get to accomplish something they might have wanted to do.

There's also no sense of "scope" to how many cards there are; a user might dismiss a few, keep seeing more, and just give up and ignore them as a visual irritant. We also end up with a growing list of cards that aren't necessarily in an order that could best benefit the user: a user interested in podcasting may never see that card if they don't bother to dismiss the other six or seven that come before it.

**Comment by kwight** [comment]
A first step here would be determining how often users are doing each form of the dismissal (using either Tracks or bump stats).

**Comment by autumnfjeld** [comment]
@ollierozdarz  @jeffgolenski  Would this be in the My Home pod scope?  We are not sure if this is pre-launch or post-launch.

**Comment by jeffgolenski** [comment]
@autumnfjeld thanks for surfacing this. @kwight brings up excellent points. 1) There's no indication of how many cards will display. 2) There's no clear way to resurface cards on demand if they hide them. 

We have a flow for Jetpack that I designed that we may be able to adopt some patterns from which _may_ help. We display recommendations that customers can accept or dismiss with "not now" actions. At the end, we have a summary that displays things accomplished or skipped, where customers can return to at any time. 

I'll think more about this dilemma this week

**Comment by jordesign** [comment]
> There's also no sense of "scope" to how many cards there are; 

This one one of my thoughts about this top area as well. Would some kind of design pattern like sliders/slideshows use (little markers/bullets for the slides) potentially help with this? In essence giving access to _all_ the cards - but dismissing them puts them at the 'bottom' of the pile - but users can still look through them all?

**Comment by jeffgolenski** [comment]
@jordesign absolutely! thinking more on this today.

**Comment by jordesign** [comment]
Suggestion from @davemart-in...

> I’d love to see us potentially remove this dropdown and simply place “X”‘s in the top right corner of any card to dismiss them with a single click. My guess is that if we do this, we’ll see a noticeable boost in the number of cards that get dismissed.

ref: pd2qGl-2J-p2#comment-91

**Comment by autumnfjeld** [comment]
Closing this as work is underway for improved navigation of these cards in https://github.com/Automattic/wp-calypso/issues/54226
