### ISSUE TITLE
My Home: Block based themes (Site Editor) should have a different checklist

### ISSUE THREAD

**Issue by david-szabo97** [Automattic/wp-calypso#50484]
#### Steps to reproduce

1. Create a site using the horizon flow
2. Go to dashboard

#### What I expected
A different checklist that's more relevant to a site editor enabled site.

#### What happened instead
The checklist asks us to create a menu and edit the homepage.

**Comment by ianstewart** [comment]
+1. Here's the checklist today:

![image](https://user-images.githubusercontent.com/545779/109226797-f1242b80-7784-11eb-8524-b0e6f6ffdf76.png)

We may want or require logic here to …

- Educate users about differences between Block and Classic Themes.
- Not point to the customizer when a Block Theme is active.
- Add additional items around patterns.
- Or other bonus items like updating certain template parts.

(There are likely other opportunities to be found with updating other content on the home screen related to our other getting started tutorials — or at least making sure that we don't surface tutorials that guide people away from a block theme without understanding the differences.)

**Comment by ianstewart** [comment]
While there are likely a dozen different things we can do here, I can think of one quick MVP that may just be clean enough from a user perspective, which is to introduce some new logic based on whether or not a Block Theme is active.

- We'll remove the Create a Site menu task
- We'll point all URLs in the Home page task to the site editor

If a user switches to a Classic theme AND those items are still "open" then they'll reappear.

**Comment by autumnfjeld** [comment]
Ganon discussed this and estimated as S (it is well defined, requiring less than a week to ship) to complete @ianstewart 's MVP suggestions made on Feb 27 2021.

**Comment by roo2** [comment]
It looks like the links on the onboarding checklist are already redirected to the site editor correctly for block based theme sites.

I've created a diff to remove the "update site menu" link

D60208-code

**Comment by autumnfjeld** [comment]
> I've created a diff to remove the "update site menu" link
> 
Did you mean "Create site menu" ?

**Comment by roo2** [comment]
implemented @ianstewart's MVP fix for this
* Create a site menu is removed for site editor blogs ✅ 
* The link to *edit homepage* had already been updated to take users to the site editor ✅

**Comment by david-szabo97** [comment]
Just tested this and the **Edit homepage** button takes me to the page editor. Can you confirm? @roo2 

https://user-images.githubusercontent.com/2256104/118807312-66952900-b8a8-11eb-80fa-5d41e21eca03.mov

**Comment by roo2** [comment]
hmm you're right @david-szabo97, I'm taken to the page editor as well. 

I thought that earlier I had been redirected to `site-editor` 🤔...  but now it's definately taking me to the page-editor as well

**Comment by roo2** [comment]
I created a new issue for just fixing this link https://github.com/Automattic/wp-calypso/issues/53236
