### ISSUE TITLE
Site Editor: Map block does not render

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#50499]
When inserting a map block into the site editor, it errors out. The error does _not_ occur in the post editor or on atomic sites.

![2021-02-25 12 23 02](https://user-images.githubusercontent.com/5414230/109212498-74815500-7764-11eb-9e24-aa11567aff26.gif)

<img width="699" alt="Screen Shot 2021-02-25 at 12 23 39 PM" src="https://user-images.githubusercontent.com/5414230/109212527-7d722680-7764-11eb-88f8-f021f7e17a3a.png">

### Steps to reproduce the behavior

1. Create a new site editing enabled site with TT1-blocks as the theme
2. Navigate to the site editor
3. Insert a map block
4. Verify that it renders an errored block

#### What I expected to happen
A map renders

#### What actually happened
An error was displayed in the map block

#### Browser / OS version
Chrome

**Comment by kerrynicl** [comment]
Hi there! @jeyip 

I'm not able to reproduce this error on my side.
![Screen Capture on 2022-03-02 at 09-31-59](https://user-images.githubusercontent.com/83325600/156384050-9f3471cd-64c6-4a33-84f8-1a5c35227f24.gif)
Further, the TT1-blocks theme is also a third party theme by .org. Does this happen with any other theme on your site?

**Comment by Robertght** [comment]
I cannot replicate this anymore. Closing for now.
