### ISSUE TITLE
Nav Uni: Two pages named "Marketing" could be confusing

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#50507]
If WooCommerce is installed then we'll be able to find two different pages in nav uni which are both named Marketing, and this could be confusing to customers.

### Steps to reproduce the behavior

1. Install and activate the `woocommerce` plugin.
2. Note the new "Marketing" tab in the unified navigation. That link takes you here: https://DOMAINCOM/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing
3. Hover over the "Tools" tab in the unified navigation and notice there is another (different) page labeled "Marketing" there. That link takes you here: https://wordpress.com/marketing/tools/DOMAINCOM

I believe that having both pages with the same name will be confusing. I would suggest changing the Tools > Marketing label to "Marketing Tools" instead (which is its Calypso name).

### Context
Team testing

#### Browser / OS version
N/A

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
No significant impact, just a bit confusing.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screenshot: https://cldup.com/Xauxcv11dV.jpg](https://cldup.com/Xauxcv11dV.jpg)

**Comment by mmtr** [comment]
I wonder if we should label them differently to make clear their purpose?

cc @mattsherman @obenland

**Comment by obenland** [comment]
I think that'll be a problem we'll run into eventually regardless of what we'll do in this instance. I could imagine a Google Analytics plugin registering an "Analytics" menu item or a forms plugin adding a "Feedback" menu item.

While it's not great, the Marketing menu item is grouped with WooCommerce which adds at least a little bit of separation. How would you feel about leaving it as is?

@sfougnier Do you have a preference?

**Comment by mattsherman** [comment]
The WooCommerce "Marketing" item, as @obenland mentions, is grouped with the "WooCommerce" item. It also will be going away in the near future, once Woo Navigation is enabled for all customers (it already is by default for eCommerce customers) -- in that environment, there is only the single "WooCommerce" item.

I would vote for leaving the WooCommerce "Marketing" item as is for now.

This is a larger issue that will always exist as long as (1) WordPress Core lets plugins do whatever they want with the admin menu, and (2) WordPress.com adheres to WordPress Core's admin menu handling.

**Comment by xpurichan** [comment]
Very glad to hear that "Marketing" will be moved in to the WooCommerce menu item soon, I think that will help a lot! My primary concern was to instruct a customer to go to: My Site > Tools > Marketing and have them go to: My Site > Marketing instead (and then get stuck). 

If both Marketing pages are in submenus then I think that would completely resolve this concern.

**Comment by obenland** [comment]
Going to close for now. This specific instance will be fixed soon and any future instances will just be part of the reality of working with third-party plugins.
