### ISSUE TITLE
Nav Unification: Clicking on My Home from a WP Admin context with replacements on loads update-core.php instead of the Dashboard

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#50501]
### Steps to reproduce the behavior

1. Toggle on `Replace all dashboard pages with WP Admin equivalents` option
2. Click on **My Home** to load `/wp-admin`, or visit any other /wp-admin page
3. Click on **My Home** again

#### What I expected to happen

For the WP Admin Dashboard page to load (or reload if already there)

#### What actually happened

The core updates page, `/wp-admin/update-core.php` loads instead.

#### Does this happen on simple or atomic sites or both?

Atomic

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="565" alt="P3QZXq" src="https://user-images.githubusercontent.com/42279181/109223597-09da1480-7778-11eb-98b9-ae7f4d2b97a7.png">

**Comment by obenland** [comment]
I wonder if this happens because we remove the Dashboard submenu item

**Comment by mmtr** [comment]
> I wonder if this happens because we remove the Dashboard submenu item

It's because the Updates submenu appears in first place. We should ensure "My Home" it's the first submenu.
