### ISSUE TITLE
WhatsApp Block: Prompting to Upgrade when already Upgraded.

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#50504]
### Steps to reproduce the behavior

1. Use an account that has an active Premium plan.
2. Add a WhatsApp block to any page
3. Publish/Update page
4. See error message on live page `Upgrade your plan to use this premium block`

_Side note: the button to upgrade doesn't go anywhere_

#### What I expected to happen

The WhatsApp button to work on my Premium plan.

#### What actually happened

The live site showed a prompt to upgrade.

### Context

#3774285-zen
[Example](https://docsdoctors.wordpress.com/whats-up-whatsapp/)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Can reproduce on different sites.

**Comment by apeatling** [comment]
Fixed in r221717-wpcom
