### ISSUE TITLE
Domain Picker: unselect domain when clearing search query

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50513]
**Note**: This also applies to the Domain step in `/start` signup flow.
___

### Steps to reproduce the behavior

1. Go to `/new`
2. Enter a site title and click Continue
3. Select a domain
4. Clear search query

#### What I expected to happen
- When clearing the input field:
   - [ ] _Continue_ button to be replace with _Skip for now_ button
   - [ ] Previous selected domain to be unselected
   - [ ] On Focused Launch, existing subdomain should be selected. (Just do this in the domains details view, ignore the summary view).
   - [ ] Add integration test*. (We need to know exactly what needs to be done or limit the scope to Gutenboarding for now.)

<img width="1205" alt="Screenshot 2021-02-26 at 09 48 03" src="https://user-images.githubusercontent.com/14192054/109272085-12365c00-7819-11eb-8cee-a828f561573a.png">

#### What actually happened
- "Continue" button is still displayed
- Domain selection is persisted even if the UI says otherwise
<img width="1199" alt="Screenshot 2021-02-26 at 09 48 27" src="https://user-images.githubusercontent.com/14192054/109272129-1ebab480-7819-11eb-855c-77bcf83ed979.png">

See the full demo below. Note that when clicking Continue, we are confirming the availability of the domain that was no longer displayed as selected. 

https://user-images.githubusercontent.com/14192054/109272172-2bd7a380-7819-11eb-8e86-d3454715a2f3.mov

### Context
After this is implemented, https://github.com/Automattic/wp-calypso/issues/49153 should not be reproduced as well  .

**Comment by razvanpapadopol** [comment]
@ollierozdarz, as mentioned in the description, this will fix also https://github.com/Automattic/wp-calypso/issues/49153 
Also, please note that we'll fix this not only for the `/new` onboarding but also for Focused Launch.

**Comment by ollierozdarz** [comment]
Sounds great, @razvanpapadopol!

**Comment by razvanpapadopol** [comment]
The same needs to be done also for the Domains step in `/start`. See 1st item in **Part 1 Domains** p58i-az5-p2

**Comment by razvanpapadopol** [comment]
@ollierozdarz, WDYT about making the unselect action more explicit? Something like adding a 'clear selection' button:
<img width="1274" alt="Screenshot 2021-06-29 at 12 02 28" src="https://user-images.githubusercontent.com/14192054/123769415-f67bb900-d8d1-11eb-9212-d39af869b905.png">

**Comment by ollierozdarz** [comment]
@razvanpapadopol, one solution for this could be to turn the 'Continue' button into 'Skip this step' if the user follows the same path as your video; selects a domain then clears the search query. That would give the visual feedback that the selection was unselected or cleared once they removed the text from the input.
