### ISSUE TITLE
Monthly Plans: update Domain step copy across onboarding flows

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50534]
## What

The copy for the subtitle in onboarding flows plans step needs to be updated

## Why

Custom domains are not free for the first year when choosing a paid monthly-billed plan

## A/C

- [ ] The copy should be update from `Free for the first year with any paid plan.` to `Free for the first year with any annual plan.`
- [ ] This change should be applied to the following flows:
    - [ ] Gutenboarding site creation flow (`/new`)
    - [ ] Gutenboarding launch flow (aka Step By Step flow)
    - [ ] Focused Launch flow

## Screenshot

![image](https://user-images.githubusercontent.com/1083581/109320787-b5569800-7850-11eb-9196-c515b0d68703.png)

**Comment by klimeryk** [comment]
Thanks for working on this! Related mentions that we fixed recently in other flows: https://github.com/Automattic/wp-calypso/pull/50385

**Comment by ciampo** [comment]
> Thanks for working on this! Related mentions that we fixed recently in other flows: #50385

No worries @klimeryk ! I'm soon opening a PR to fix this
