### ISSUE TITLE
Atomic: "Launch" displaying on launched sites, causing update/publish issues

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#50532]
It appears that some recent Launch changes are not properly detecting if a site is launched.  The issue appears while `WordPress.com Editing Toolkit 3.737` is active but it might be related to https://github.com/Automattic/wp-calypso/issues/50394

Users with actively launched sites are now seeing a Launch button on their posts and are having difficulties updating and publishing.

If a user clicks Launch, it may also ask them to register a new domain as reported by @zdenys 

![Screen Shot on 2021-02-26 at 09:49:03](https://user-images.githubusercontent.com/4887830/109314868-e36bb600-7817-11eb-91a1-5d9f721dfb8d.png)

### Workaround

A workaround, if a user is just trying to Update:

Ask them to add a space at the end of a paragraph or piece of text -- then remove the space.  That should trigger the editor to detect an update and let them click on Update.

A less optimal workaround is to temporarily deactivating the WordPress Editing Toolkit.

### Steps to reproduce the behavior

1. Edit a Page or Post on a WordPress.com on Atomic site with the WordPress Editing Toolkit Active.
2. See error.

##### Context 

Various user reports. Internal discussion on p1614349907033100-slack-C03TY6J1A and p1614350655060500-slack-C0160HSMDQV

Internal P2: p9F6qB-6yy-p2

**Comment by JoshuaGoode** [comment]
Encountered on 3776097-zen

**Comment by zdenys** [comment]
27952589-hc

**Comment by jartes** [comment]
Had another one on 26381712-hc

**Comment by AtrumGeost** [comment]
Related P2 post:

p9F6qB-6yt-p2

**Comment by carladoria** [comment]
reported in[ 28033786-hc ](28033786-hc)

**Comment by aisajib** [comment]
Just reported in 2906829-hc
Also in 28034255-hc

**Comment by JoshuaGoode** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/50394 ?

**Comment by desnum** [comment]
Another case in 27385374-hc

**Comment by bayomio** [comment]
Had a few reports via HC:

22154776-hc / 27250191-hc / 28033509-hc / 21858942-hc

**Comment by bayomio** [comment]
Had a few reports via HC:

22154776-hc
27250191-hc
28033509-hc
21858942-hc

**Comment by desnum** [comment]
22225573-hc

**Comment by yansern** [comment]
Reverted in 620-gh-Automattic/wpcomsh. It will be picked up by Atomic sites soon.

**Comment by RealCarFax** [comment]
Encountered in 11714463-hc and #28034810-hc

**Comment by JoshuaGoode** [comment]
619-gh-Automattic/wpcomsh has been deployed to Atomic.  The issue should now be resolved.

**Comment by JoshuaGoode** [comment]
Thanks, all.

I've updated the users that had follow-up tickets listed here and across the two P2s at p9F6qB-6yy-p2 and p9F6qB-6yt-p2

Closing this issue now.
