### ISSUE TITLE
Site Editor: "Powered By WordPress" Footer Credit is removable

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#50544]
The WordPress footer credit on full site editing enabled simple sites can be removed.

![2021-02-26 12 06 05](https://user-images.githubusercontent.com/5414230/109349841-68ac9600-782b-11eb-9f2e-40e69a1db379.gif)

### Steps to reproduce the behavior

1. Navigate to the site editor
2. Click on the WordPress footer credits in the footer template part
3. Remove the block
4. Save the changes
5. Verify that the footer credit is removed on the frontend of the site

#### What I expected to happen
The footer credit should not be removable

#### What actually happened
The footer credit could be deleted

#### Browser / OS version
Chrome

#### Is this specific to the applied theme? Which one?
TT1-Blocks

**Comment by Gilmoursa** [comment]
Only users on the Business or eCommerce plans should have the option to remove the WordPress.com footer credit.

**Comment by ramonjd** [comment]
Hi! We're working on this over here D59022-code

**Comment by vindl** [comment]
Closing in favor of 244-gh-Automattic/view-design.
