### ISSUE TITLE
Help: Fix styling for Sibyl on the Contact Form

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#50543]
It looks like https://github.com/Automattic/wp-calypso/pull/48719 broke the styles for Sibyl on the Contact Form (the question/answer suggester to help customers answer their own questions before reaching out to us). See it by going to https://wordpress.com/help/contact and typing something like "css" into the message box. Here's a comparison of current production, vs the expected design:

<img width="2051" alt="Screen Shot 2021-02-26 at 11 35 03 AM" src="https://user-images.githubusercontent.com/518059/109335391-942d8180-7827-11eb-81a3-ac43ece2f35a.png">

Somewhat astonishingly, stats don't make it seem like this has changed how Sibyl or the contact form are used. But it's a pretty bad experience for customers (the Submit button gets pushed way down the page). Any chance you can take a look and fix this?

I'm not overly opinionated that Sibyl's design needs to match exactly what it was before, but something that's similar in page weight would be wonderful.

_Originally posted by @mattwondra in https://github.com/Automattic/wp-calypso/issues/40870#issuecomment-786793739_

**Comment by mattwondra** [comment]
@sixhours Thank you so much for fixing this! 🙌
