### ISSUE TITLE
Help bubble distracting in wp-admin on mobile browser

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#50557]
We recently started showing the question mark help bubble in wp-admin. (https://github.com/Automattic/wp-calypso/issues/50271) The user finds this distracting when working from a browser on mobile, and would like a way to hide it.

**Additional context**
Requested here: 3776245-zd-woothemes

![Screenshot_20210226-104418](https://user-images.githubusercontent.com/1398304/111004512-0c269c00-833e-11eb-9eba-26c3ecf4c9bc.png)

**Comment by obenland** [comment]
I think we never remove it in Calypso either, not even when editing posts/pages.

Happy to leave this open to see if it garners more feedback, but I'm leaning towards not fixing that.

**Comment by cpapazoglou** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/50701

**Comment by jordesign** [comment]
With no additional reports/feedback since March 13 - I'd propose we close this.
