### ISSUE TITLE
FSE - Global Styles - "Text Color" resets on save.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#50556]
In the site editor when we select a new "Text Color" global styles:
![Screen Shot 2021-02-26 at 8 53 46 PM](https://user-images.githubusercontent.com/28742426/109371848-bac5d980-7874-11eb-8083-49bd9f2bfb2b.png)

The text color updates accordingly on the editor.  However, on save this resets and the text returns to its default color.

This doesn't seem to happen on my local core install.

**Comment by vindl** [comment]
I think this is a duplicate and special case of https://github.com/Automattic/wp-calypso/issues/50358.
