### ISSUE TITLE
FSE site creation flow - design previews too small in scope

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#50554]
When choosing a layout in the onboarding flow, the thumbnails do not give much of a preview of the themes/layouts:
![Screen Shot 2021-02-26 at 7 06 08 PM](https://user-images.githubusercontent.com/28742426/109368106-fad19000-7865-11eb-9859-bd4a30533366.png)

Adding a link to the preview site could allow the user to get a better picture of the theme if necessary.

**Comment by ianstewart** [comment]
Moving this one to the Create Focus backlog as it's a general onboarding issue.

**Comment by autumnfjeld** [comment]
Estimation note: Ganon/ @roo2  reaching out for discussion

**Comment by roo2** [comment]
@Addison-Stavlo @ianstewart we're doing some work to improve the size of the design previews:

Main issue discussing size increase https://github.com/Automattic/wp-calypso/issues/52017

We're also deploying [scroll on hover](https://github.com/Automattic/wp-calypso/pull/51261) to get a better preview

I'll close this one in favour of #52017. @Addison-Stavlo, if you want to create an issue just focused on adding links to the theme preview sites that might be independently valuable.
