### ISSUE TITLE
Remove "Account Settings" from Nav Unification menu

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#50566]
**What**
Both "My Profile" and "Account Settings" are in the Users menu. It's quite ambiguous what the difference is without clicking:
![image](https://user-images.githubusercontent.com/32492176/109400021-82211100-7903-11eb-8074-1167f721d9af.png)

If one is to keep both, I'd at least expect "Profile" to go to WP Admin (which happens to be inaccessible now on Simple sites per #50565).

**Why**
This would reduce redundancy/improve clarity: if they want to edit their user profile and or account settings, they'd click My Profile.

**Comment by tjcafferkey** [comment]
Thanks @tbradsha. The "My Profile" and "Account Settings" menu items and links are consistent with the usages in the account sidebar.

![Screenshot 2021-03-02 at 17 07 54](https://user-images.githubusercontent.com/8639742/109686061-d6352b00-7b79-11eb-985d-04e6e19b7150.png)

**Comment by tbradsha** [comment]
Yes, it's consistent with the account sidebar, but still disorienting/unclear what one would find at those links, followed by confusion of how to get back to the nav unification menu in #50564. Not a regression, but feedback. :^)

**Comment by obenland** [comment]
While testing this I also ran into the behavior of #50564. Let's keep Account Settings for now but find a way to set the current site correctly when we link from wp-admin to Calypso.
