### ISSUE TITLE
Show current plan in navigation

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#50563]
**What**
Calypso currently shows the plan type in the navigation:
![image](https://user-images.githubusercontent.com/32492176/109399673-77fe1300-7901-11eb-88aa-a080a18d3af0.png)

It'd be great to have this post Nav Unification.

**Why**
Users often get confused about what site they've purchased a plan on or what plan their current site is on. It's nice to have a visual cue without an extra click. This is also useful to provide HEs with context.

**Comment by tjcafferkey** [comment]
Closing, duplicate of https://github.com/Automattic/wp-calypso/issues/49660
