### ISSUE TITLE
No way to access /wp-admin/profile.php on Simple sites

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#50565]
### Steps to reproduce the behavior

Visit `/wp-admin/profile.php` on a Simple site.

#### What I expected to happen

I should have access to the WP Admin profile page.

#### What actually happened

I'm redirected to `/wp-admin/users.php?page=grofiles-editor` and get this error:

![image](https://user-images.githubusercontent.com/32492176/109400275-10e25d80-7905-11eb-9d8d-5bfa8c5aa30e.png)

#### Context

This has previously useful to change a user's display name at the site level (rather than for the entire account).

**Comment by tjcafferkey** [comment]
Thanks for raising @tbradsha. For Simple Site users clicking "Edit" on your user in WP Admin redirected you to `/me` on WordPress.com prior to nav unification AFAIK.

**Comment by getdave** [comment]
@tbradsha I tested this on my Simple site and it took me to `https://wordpress.com/me`. That is expected. Simple sites have never had access to the WPAdmin profile.

Can you isolate what caused you to end up in `/wp-admin/users.php?page=grofiles-editor`? Any special plugins? Is this a fresh Simple site? Can you still replicate this?

**Comment by cpapazoglou** [comment]
> @tbradsha I tested this on my Simple site and it took me to `https://wordpress.com/me`. That is expected. Simple sites have never had access to the WPAdmin profile.
> 
> Can you isolate what caused you to end up in `/wp-admin/users.php?page=grofiles-editor`? Any special plugins? Is this a fresh Simple site? Can you still replicate this?

The user went directly to `/wp-admin/profile.php` and got redirected to `/wp-admin/users.php?page=grofiles-editor`.

Prior to "nav-unification" `/wp-admin/profile.php` redirected to `https://wordpress.com/me` (at least for simple sites). I suppose we should honor that and do the same.

**Comment by tbradsha** [comment]
I used to be able to go to WP Admin → Users and edit their profile, updating their display name or bio. This is no longer possible. Going to `/me` is for account-wide settings, so doesn't solve the issue here.

**Comment by obenland** [comment]
@tbradsha Is this something a user reported? Or something that is part of your workflow? There are still ways to get to that, it just depends on the context.

**Comment by tbradsha** [comment]
This was part of my workflow, but it'd be nice to open up a way for the end user to update their site-specific display name as well.

**Comment by obenland** [comment]
μ => Blog's Network Admin => Blog Users will take you to a user list from where you should be able to access user profiles.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/1398304/111218821-79336f00-8594-11eb-9130-51e800162b61.png">

Direct access has been disabled for Simple Sites for a while (AFAIK), let's not walk back that decision for now.
