### ISSUE TITLE
Nav Unification: Jetpack Plan showing on WordPress.com Plan site

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#50562]
### Steps to reproduce the behavior

1. Go to WordPress.com > Upgrades > Plans > My Plan page, it shows it is on the Business plan. Screenshot: 
![Annotation on 2021-02-27 at 12-40-44](https://user-images.githubusercontent.com/7382505/109378512-2c476b80-78f9-11eb-8f76-284e2d2f08d2.png)

2. Now if I go to WordPress.com > Jetpack > Dashboard > Plan > My Plan page on the same site, it shows Jetpack Professional plan. Screenshot: 
<img width="1410" alt="Markup 2021-02-27 at 12 42 52" src="https://user-images.githubusercontent.com/7382505/109378550-74ff2480-78f9-11eb-8c4c-702e948a9ccb.png">

#### What I expected to happen
On Jetpack > Dashboard > Plan > My Plan to show WordPress.com Business plan as they only purchased the WordPress.com Business plan and not Jetpack Professional plan.

#### What actually happened
The jetpack plan is showing. 

### Context
It is necessary to make sure we don't confuse the users with plan names in different places, because of how our plans are structured. This can cause confusion and baffle the user about what plan they own (only WordPress.com Business or Jetpack Professional or both!?) and if they have to pay for both.

Also showing the same renewal date can cause an alarm and confusion for the users.

#### Does this happen on simple or atomic sites or both?
Only on the Atomic site.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This is affected on all the Jetpack connected Atomic site.
 
#### OS/Browser:
macOS Big Sur v11.2.2/ Chrome v88.0.4324.

**Comment by simison** [comment]
I wouldn't expect Jetpack dashboard being visible on any .com sites (Atomic nor simple) to begin with.

**Comment by cpapazoglou** [comment]
> I wouldn't expect Jetpack dashboard being visible on any .com sites (Atomic nor simple) to begin with.

Can we elaborate on that? Simple sites already don't show the Jetpack dashboard. Atomic sites show the Jetpack dashboard as they did prior to "nav-unification". Are we sure that removing it will not result to any "feature-loss" for customers?

**Comment by simison** [comment]
> Atomic sites show the Jetpack dashboard as they did prior to "nav-unification". Are we sure that removing it will not result to any "feature-loss" for customers?

That sounds like a bug to me that will just be greatly amplified by Nav unification.

**Comment by obenland** [comment]
In 576-gh-Automattic/wpcomsh @jeherve suggests using wpcomsh's `admin-style.css` to hide the plan information.

Let's hide both the plan info box and the "Plans" menu item:

![hide-plan-info](https://user-images.githubusercontent.com/1398304/111005616-029e3380-8340-11eb-9e6f-79218cae1730.jpg)

**Comment by sixhours** [comment]
Looks like we're already trying to hide the Plans menu item but the styles are broken:

```
/* Hide the "Plans" page in Jetpack Dashboard */
.dops-navigation .dops-section-nav-tab__link[href="#/plans"] {
	display: none;
}
```
