### ISSUE TITLE
Anchor: Newly-published posts are not added to the podcast.

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#50560]
### Steps to reproduce the behavior

1. Publish a new post
2. Click on Create a podcast episode
![Screenshot](https://d.pr/i/4X3vpu+)
*if image does not load, please click on this link  : https://d.pr/i/4X3vpu*
3. https://anchor.fm/dashboard/episodes did not create a new podcast
![Screenshot](https://d.pr/i/yKKitE+)
*if image does not load, please click on this link  : https://d.pr/i/yKKitE*

#### What I expected to happen
Anchor.fm displays the newly created podcast

#### What actually happened
https://anchor.fm/dashboard/episodes did not create a new podcast

#### Browser / OS version
Chrome 
Version 88.0.4324.192 (Official Build) (×86_64)

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
On Simple ( PcOJjo-3-p)2 and Atomic ( #3775945-zen )

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Does not block purchases. Affects more than one site.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screenshot](https://d.pr/i/cgR9PK+)
*if image does not load, please click on this link  : https://d.pr/i/cgR9PK*

**Comment by kosiew** [comment]
This is due to lag at Anchor.fm in detecting newly published posts. p1614406120110700/1614349262.095000-slack-C01FD4FGD7X

**Comment by kosiew** [comment]
Pending discussion with Anchor to investigate the lag: p1614407086114000/1614349262.095000-slack-C01FD4FGD7X

**Comment by simranvijwani** [comment]
The user reported that the posts aren't converting to podcasts. They see the error `Error connecting to WordPress` on Anchor's site. 
![image](https://user-images.githubusercontent.com/34896144/109459881-a86eba00-7a85-11eb-9f7c-c68ab8033a46.png)


Reported in: #28033743-hc
Follow up in: #3775945-zen

**Comment by kwight** [comment]
The user should be seeing a prompt to import any new posts published since their last visit to the Anchor dashboard.

<img width="1246" alt="Screen Shot 2021-03-03 at 2 21 06 PM" src="https://user-images.githubusercontent.com/349751/109880647-0e954180-7c2c-11eb-880e-cc77d3d04854.png">

I don't have any explanation for what they're seeing, and it's tough to figure out when it's happening on the Anchor side. We're having a [connection issue](507-gh-Automattic/dotcom-manage) with some JP/Atomic sites – while this user isn't listed, it looks like it could be related (since they're Atomic).

**Comment by gwensmithx** [comment]
It seems there are a few issues open for Anchor.fm. This one seems to match exactly what a customer is experiencing that I chatted with today.

They are seeing the WordPress connection error in their Anchor.fm dashboard (screenshot is in ticket).

#3789782-zd

**Comment by wpshellbelle** [comment]
> #3789782-zd



User is unable to connect to Anchor. Here is a screenshot of the error they are seeing: 


![](https://d.pr/i/zM6q99+)



User has been in contact with Anchor and I am sharing their replies below:


>Our engineering team took a closer look at this, and we unfortunately don’t support the specific version of WordPress that you’re currently using. If you’d like, you can contact WordPress Support for more information, they should be able to provide context.
I wish I could be more helpful here, but please let me know if you've got any other questions.
All the best,
Rae
Anchor


>Grant here from the Anchor Support team. Sorry for the lack of clarity on our part. We had noted that your WordPress.com site had updated to a business plan, and that actually changes hosting from WordPress.com to a slightly different configuration on their platform, which is something we're still looking into supporting in full.
I hope that helps explain it a little better. Please let me know if you have any questions
Anchor

**Comment by nagpai** [comment]
Another issue here 
#3870912-zen

Site is atomic and has a wpcomstaging URL. 

`Error connecting to WordPress.com` in their Anchor dashboard.

**Comment by kosiew** [comment]
#3789782-zen - Customer getting `Error connecting to WordPress Try again` at Anchor.fm and not able to import any post from WordPress.com

**Comment by jordesign** [comment]
I've just tested this and can confirm it takes place when the initial connection was made from a Simple Site URL (https://anchortest54667491.wordpress.com/) and then tries again after the site has gone Atomic (https://anchortest54667491.wpcomstaging.com/)

<img width="1164" alt="Screen Shot 2021-04-07 at 7 55 24 am" src="https://user-images.githubusercontent.com/1842363/113783131-a1b71f00-9776-11eb-9035-ee90f0503a2a.png">

**Comment by kwight** [comment]
@jordesign Oh, that's interesting – that could point to a larger issue with OAuth and the API in general for that case. Maybe the next step is to ask atomicrequests if they've seen similar issues at all before.

**Comment by jjchrisdiehl** [comment]
Another instance here 

#29494701-hc

This appears to be a breaking bug, are there any possible work arounds?

**Comment by metabreakr** [comment]
29346793-hc / 3982159-zen

User is not seeing any posts being populated (they have 2 published): https://snipboard.io/HjZ56K.jpg

**Comment by kwight** [comment]
@jjchrisdiehl I've removed the BLOCKER label, it's more used for features not yet released (where the issue is so bad, the feature shouldn't be released until fixed).

@obenland I don't know about this – I think it could be a deeper bug with the Jetpack API and its handling of Atomic sites, but it'll take a good amount of digging and dedicated time to determine all of that. Definitely a bug people are hitting though (and since they're Atomic, they're likely paying for something).

**Comment by obenland** [comment]
Yeah I wonder if it's an authentication issue. @taggon is this something y'all would be able to look into?

**Comment by villanovachile** [comment]
User experienced issue with Anchor not being able to connect to WordPress.  According to Anchor, they do not support Jetpack sites: https://help.anchor.fm/hc/en-us/articles/360060866231?input_string=error+connecting+to+wordpress

#3982359-zen

**Comment by donalirl** [comment]
Their Anchor integration stopped working when going atomic: #3976668-zen

**Comment by nagpai** [comment]
User issue #28544407-hc

Anchor asked them to downgrade if they want the podcast back. Mentioned that Podcast feature is not compatible with Jetpack sites (including WoA)

**Comment by nagpai** [comment]
### Test Case - Simple Site with Anchor going Atomic 


#### Steps done
Created three posts and was able to successfully publish to Anchor when the site was simple
Made the site go Atomic, Published a new post. 

I now get an error similar to the one noted by @jordesign 

<img width="1243" alt="Screen Shot 2021-05-14 at 21 52 45" src="https://user-images.githubusercontent.com/4162931/118300376-7a830880-b4ff-11eb-8e63-522e1ca0c6f2.png">

Browser Console error, if this helps

<img width="1354" alt="Screen Shot 2021-05-14 at 21 53 52" src="https://user-images.githubusercontent.com/4162931/118300495-9f777b80-b4ff-11eb-86cd-f467fff88140.png">

**Comment by kriskarkoski** [comment]
Another case in 3961225-zen

> My blog will not connect to the Anchor site and the Anchor site will not load episodes from my blog. Here’s a screenshot of that:
> 
> The Anchor support representative said this is happening because I am using the Jetpack plugin. I thought, however, that Jetpack is a default feature with Wordpress.com blogs.

I asked about any specific errors they're seeing and they said: 

> I opened an Anchor account through my Wordpress site. The error messages come from Anchor and says, "Unable to load your episodes.” It has “retry” button but gives the same message when I click it.

**Comment by kriskarkoski** [comment]
3989603-zen looks like another case. I'm waiting for more details but in their initial message they said:

>I am going to Anchor.com and publishing my episode. I get a prompt to convert to a WordPRess blog. But the latest episodes are not published. It publishes from the week before or misses an episode.

**Comment by kriskarkoski** [comment]
3989202-zen

Atomic site that asked to downgrade to get Anchor working again

**Comment by taggon** [comment]
I created a hack for mitigating the problem: pd2HMz-g-p2
Hope this works.

**Comment by inaikem** [comment]
Another affected user here: 29538272-hc (follow up at 4091080-zd). Two requests:

1. @taggon, I see it's in the "In Progress" queue at the moment. Any idea when you're expecting to push this live?
2. Do we have any existing guidance we can pass on to affected customers?

Thanks! 🙏

**Comment by taggon** [comment]
@inaikem It turned out my patch might not work for some cases as @fgiannar mentioned in pd2HMz-g-p2#comment-8
We probably need another approach for this issue.
As the first phase of the Flow Patrol is ending soon, I'd like to hand over this to the next Flow Patrol team.

**Comment by pauljacobson** [comment]
We have another instance of this issue in 4197568-zen and the user would like to be updated once we have managed to resolve the issue.

**Comment by MaxPhilip** [comment]
Another `Error connecting to WordPress Try again` here: #4202417-ZD

**Comment by zdenys** [comment]
Another case in 4215205-zd-woothemes. User is on WoA (AT) site and is experiencing an internal server error when trying to connect to Anchor.

**Comment by kwight** [comment]
@yansern @sixhours Can you make sure this is on someone's board please?

**Comment by zdenys** [comment]
Another case 13550084-hc. I suggested they host the podcast on WP.com (they didn't know it was an option).

**Comment by daria2303** [comment]
another report 4230136-zd-woothemes 
"error connecting to WordPress, try again later"

**Comment by sajmes** [comment]
31369280-hc - possibly already reported but adding to ensure they are notified once resolved.

**Comment by metabreakr** [comment]
31301902-hc (Atomic)

**Comment by Robertght** [comment]
#4270620-zen Premium plan

**Comment by thesacredpath** [comment]
Have two users who say the Listen on Spotify button that typically appears after publishing the post no longer appears either. Wondering if this is all connected.

Ticket: 4270620-zen
Ticket: 4269523-zen

**Comment by thesacredpath** [comment]
Another reported issue with posts not showing to convert.

31373189-zen
4296089-hc

**Comment by flameslash** [comment]
30616592-hc

This user is on an AT site but couldn't get Anchor to work. They have since asked us to revert it to a simple site so they can use the integration moving forward.

**Comment by mikeicode** [comment]
Same issue as mentioned above with the Spotify buttons not appearing any longer. 4324350-zd-woothemes

I suggested using the method Robert mentioned above, using an Image block to create a manual link to Spotify.

**Comment by sixhours** [comment]
Just to sum up the current state of this issue:

* An attempt to fix was made here D61885-code
* It was thought we could solve this by modifying the WordPress.com response to Anchor.fm to include post data from the cached Jetpack site rather than going straight to the Atomic/Jetpack site itself. But this data won't always be accurate/up to date, and it doesn't solve the root problem, which is...
* ...supporting OAuth2 for XML-RPC requests between Anchor.fm and Jetpack: pd2HMz-g-p2#comment-8

It seems like this may be something we need to work with Anchor.fm on, and/or has to be fixed on their side. Related documentation from Anchor.fm: https://help.anchor.fm/hc/en-us/articles/360060866231-Errors-Connecting-Your-WordPress-com-Blog

**Comment by sixhours** [comment]
I'm taking this one off our current sprint because it exceeds our engineering resources and it appears to be slated for future work by Expand.

**Comment by sanjeev00733** [comment]
#21332756-hc, same issue with Spotify button not showing up.

**Comment by CompChris** [comment]
#31204048-hc - Same trouble

**Comment by ghost** [comment]
4645330-zen - same issue with Spotify button not showing up.

**Comment by formosattic** [comment]
4692950-zd-woothemes , same issue described on https://help.anchor.fm/hc/en-us/articles/360060866231

![image1](https://user-images.githubusercontent.com/15944096/149738945-0488aac7-7614-4fd3-b958-a2243aff02ce.png)

Discussed internally: pc4f5j-13S-p2

**Comment by kwight** [comment]
See also 507-gh-Automattic/dotcom-manage for more troubleshooting background.

**Comment by sixhours** [comment]
Came at this with fresh 👀 and documented my testing so far here: pc4f5j-13S-p2

**Comment by tellisbethel** [comment]
User getting "Error connecting to WordPress." here: 4754116-zd-woothemes
Details on minor testing I did to try to connect Anchor.fm to my Atomic sites here: pc4f5j-13S-p2#comment-2002

**Comment by andres-blanco** [comment]
More info on the bug (or at least a part of it) and a possible fix paYKcK-1gw-p2

**Comment by kwight** [comment]
Can you give us an update here @andres-blanco ?

**Comment by andres-blanco** [comment]
> Can you give us an update here @andres-blanco ?

A really [promising fix](D75099-code) is now ready to be run. It will be applied first for cases that appear on this issue upon coordination with HEs. If that succeeds it will then be rolled-out to the rest of the affected users.

More details here: paYKcK-1j9-p2

**Comment by andres-blanco** [comment]
The first batch of fixes was just run.

paYKcK-1lq-p2

**Comment by andres-blanco** [comment]
Progress on adding the token migration on Atomic transfer made here: D75586-code

**Comment by andres-blanco** [comment]
> The first batch of fixes was just run.
> 
> paYKcK-1lq-p2

The users in this batch were contacted, we are waiting for feedback. paYKcK-1lq-p2#comment-1235

**Comment by andres-blanco** [comment]
There's a fix already applied and ready to be tested for adding the fix to atomic transfer, so this stops happening: D75586-code

**Comment by kwight** [comment]
The fix for Atomic transfer is in production: D75877-code. We just need to confirm with individual existing users above that their issues are resolved. Great work @andres-blanco ! ✨

**Comment by andres-blanco** [comment]
The fixes for the already broken sites are being applied. I am running them in small batches, for the time being 237 sites have been fixed and 536 remain. Hopefully tomorrow we will be able to close this issue

**Comment by andres-blanco** [comment]
Wrap up paYKcK-1pM-p2 🎉

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread (see [example reply](4847626-zd-woothemes)).

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
