### ISSUE TITLE
Domain Picker: "Recommended" badge is breaking on mobile

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50578]
### Steps to reproduce the behavior

1. Go to `/new` on mobile
2. Advance to domain step and check out search results

#### What I expected to happen
"Recommended" badge to be displayed on a single line

#### What actually happened
The badge is split into two lines

### Context
This is most likely happening because of the `flex-grow: 1` declaration on `.domain-picker__price` that shouldn't be applied on mobile. See https://github.com/Automattic/wp-calypso/blob/trunk/packages/domain-picker/src/domain-picker/style.scss#L351

A similar flex issue was fixed for all screen sizes in https://github.com/Automattic/wp-calypso/pull/49883 but only for the free domain suggestion.

**Notes**:
* Make sure the badge looks good also in other locales with longer words (eg: German)

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="319" alt="Screenshot 2021-03-01 at 11 37 40" src="https://user-images.githubusercontent.com/14192054/109480646-6ee97f00-7a84-11eb-9219-d5e397d4e0f7.png">

**Comment by alshakero** [comment]
Closing this as it doesn't seem reproducible anymore.

<img width="300" src="https://user-images.githubusercontent.com/17054134/118810242-ed97d080-b8ab-11eb-90b1-db2e1658a21f.png">

**Comment by alshakero** [comment]
Reopening as it's still breaking on iPhone SE.

**Comment by alshakero** [comment]
PR here https://github.com/Automattic/wp-calypso/pull/53016
