### ISSUE TITLE
Image Block: Let's add a lightbox option without the need for extra plugins

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#50571]
### What
I'd love to see a lightbox option for single Image Block that does not rely on a third party plugins present.

### Why
Speaking from the heart, it would be amazing. Speaking from the head, adding a lightbox option to the Image Block would make interaction with single images consistent with the Gallery, Tiled Gallery, Masonry, Collage, etc., blocks.

While the Tiled Gallery and others could be used with a single image as a workaround/hack, this is not optimal. Talking to the Tiled Gallery specifically, it replaces the "inner" images with a smaller thumbnail, which results in a sub-optimal experience for readers.

See this video:

https://user-images.githubusercontent.com/66711744/109416104-2df75900-79f7-11eb-8b8a-f7f9c0dbcec0.mp4

In the video above, you can see a 1260 × 436px "404" image presented in three ways:

- Image Block
- Image Gallery
- Tiled Gallery

A normal Gallery loads thumbnails in at their full-size:
https://i2.wp.com/my-awesome.blog/wp-content/uploads/2021/02/404.png?w=1260&ssl=1

The Tiled Gallery loads a smaller version instead: 
https://i2.wp.com/my-awesome.blog/wp-content/uploads/2021/02/404.png?strip=info&w=436&ssl=1

Sadly the resulting "hack" of trying to use a Tiled Gallery as a single image with a lightbox doesn't work, which is a shame as I personally love the fullscreen image presentation there.

**Comment by jeherve** [comment]
This is already possible, thanks to the Carousel feature. You can enable the Carousel view for single image blocks by linking the image to its attachment page; when you do so, the carousel view will be triggered when clicking on the image.
