### ISSUE TITLE
No way to access Plugin or Theme Editor from nav

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#50570]
#### What I expected to happen

The Plugins menu should have the "Plugin Editor" feature:

![image](https://user-images.githubusercontent.com/32492176/109400996-4721dc00-7909-11eb-8c99-ad78a0699daf.png)

The Appearance menu should have the "Theme Editor" feature:

![image](https://user-images.githubusercontent.com/32492176/109401048-98ca6680-7909-11eb-90b7-a3c9a6bf336e.png)

### Context

It's common for a user to want to add a quick function to their theme's `functions.php`, or for devs to apply a quick tweak via the browser.

**Comment by tbradsha** [comment]
See also Automattic/jetpack#18917; the plugin submenu portion of the issue may be resolved in Jetpack 9.5.

**Comment by tjcafferkey** [comment]
Closing. Fixed in Jetpack 9.5
