### ISSUE TITLE
FSE/Global Styles: Background color resets on save.

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#50575]
When I select the background color for the root element in Global Styles, first it takes a second to switch the background color in the editor, and then when I Update & Save, the background color is back to white. This might be related to #50556.

### Steps to reproduce the behavior

1. On a site with site editor enabled open the global styles tab.
2. Scroll to the background color section and select a color with the picker.
3. Note the color is not applied instantly (what I expected).
4. Once the background color is applied in the editor, hit Update design, and then Save.
5. Note the background reverts to the original white.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://cloudup.com/cRCOSezx5SB
Also note that that font-family upon Saving, even though I made no changes there. 

#### Is this specific to the applied theme? Which one?
I tested this with the Mayland Blocks theme, which is included in signup yet. If this turns out to be a theme issue I'm happy to move it over.

#### Is there any console output or error text?
I looked and there were no specific errors that I could see.

**Comment by vindl** [comment]
I think this is a duplicate and special case of https://github.com/Automattic/wp-calypso/issues/50358.
