### ISSUE TITLE
Purchases: untranslated strings in subscription removal dialog

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50590]
### Steps to reproduce the behavior

1. Set your WordPress.com account to a different locale from English
2. Go to `/me/purchases`
3. Click on a plan that you want to remove
4. Follow the instructions in the dialog
5. Notice how the main CTA button text (`Remove it` and `Removing`) is not translated in the current locale

#### What I expected to happen

All text should be translated

#### What actually happened

The CTA button text is not translated

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/1083581/109514246-1aef9200-7aa6-11eb-893e-969573bb1c2f.mp4

**Comment by obenland** [comment]
@michaeldcain Is this something that falls in area of expertise?

**Comment by michaeldcain** [comment]
@obenland: it does. Thanks for the heads up - we'll triage it. Looks like [some unwrapped strings](https://github.com/Automattic/wp-calypso/blob/caab6d3b9b881b78fb6ca0f4d4d0b0224d9ce1ea/client/components/marketing-survey/cancel-purchase-form/index.jsx#L805).
