### ISSUE TITLE
New Onboarding - Plans descriptions lack descriptiveness.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#50606]
In Site Editor alpha testing it was noted that the descriptions for plans could be more descriptive and helpful:

![Screen Shot 2021-03-01 at 6 43 54 PM](https://user-images.githubusercontent.com/28742426/109580249-497e6480-7ac8-11eb-8086-63a5eb1c785d.png)

For example "Best for personal use" is not a very helpful description for "Personal".

**Comment by ianstewart** [comment]
I'm going to move this one off of the Site Editor project and put this one on to the Create Focus experience board as it won't block the Site Editor.

**Comment by ollierozdarz** [comment]
@razvanpapadopol can we please assign this feedback to one of our Marketing partners? I assume the language here has had some collective effort and brainstorming in the past to get it to this point and I wouldn't want to dive in to change it 🙂
