### ISSUE TITLE
Scrolling bug with site preview iframe in Calypso

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#50631]
Originally reported by @jsnajdr in p1614665734427400-slack-ajax.

### Steps to reproduce the behavior

1. make the window height small enough to make the sidebar scroll. 
2. Click on the “site info” box in the sidebar. That will show the site preview iframe in the content area. 
3. Now try to scroll down the _sidebar_. You can’t because the preview iframe disabled the page scrolling somehow.

#### What I expected to happen

You should be able to scroll the sidebar nav even when the site is previewed in the Calypso main content area.

#### What actually happened

I couldn't scroll.

**Comment by lsl** [comment]
I'm not completely sure this is the same issue I've encountered but I think it might be related, it looks like there is some positioning being "zero'd out" when it needs resetting on navigation.


https://user-images.githubusercontent.com/811776/125402757-2067cc00-e3f8-11eb-8cec-dc9f9f38e2b8.mov

**Comment by dsas** [comment]
The layout of this page is wrapped by a div with the `.layout.is-section-preview` class which has `overflow:hidden` it's probably that.

![image](https://user-images.githubusercontent.com/93301/144446097-90824010-fb79-44cc-b47e-88dbb0beac3d.png)

**Comment by dsas** [comment]
Looks like that the rule was added in 2018 as part of a big commit a2b8a31. It's in [calypso client/layout/style.scss](https://github.com/Automattic/wp-calypso/blob/666e1bf13f78b4304de41d7a5a666d6ec8d9d6df/client/layout/style.scss#L279)
