### ISSUE TITLE
Plugins: Suggested search terms sometimes return 0 results

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#50663]
### Steps to reproduce the behavior

1. Change language to spanish
2. Go to `/plugins`
3. Click on the "Implicación" suggested search term ("Engagement")

#### What I expected to happen
The same search results as the English suggested term of "Engagement" should appear

#### What actually happened
No results appear

### Context
Found while testing the search functionality in plugins for the new search component.

#### Browser / OS version
macOS Big Sur

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
N/A

#### Is there any console output or error text?
None

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Not sure, probably medium as it might prevent some upgrades from happening if folks can't find relevant plugins to their needs

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Below are screenshots for the same suggested search item for "Engagement", one in Spanish and one in English. Note that the Spanish version contains no results.

<img width="1502" alt="Captura de Tela 2021-03-02 às 08 56 59" src="https://user-images.githubusercontent.com/24264157/109684643-52594f80-7b35-11eb-9997-e15884c11216.png">

<img width="1502" alt="Captura de Tela 2021-03-02 às 08 57 17" src="https://user-images.githubusercontent.com/24264157/109684612-4bcad800-7b35-11eb-89e9-4581e0b10ebd.png">

**Comment by cpapazoglou** [comment]
Closing this as we don't have suggested terms in the new design
<img width="1590" alt="SS 2022-01-05 at 20 44 34" src="https://user-images.githubusercontent.com/12430020/148271690-6726b77a-157e-4c23-bf5d-0efdf2674496.png">
