### ISSUE TITLE
Nav unification: Clearly indicate with a banner or notice when using nav unification menu for Jetpack sites

### ISSUE THREAD

**Issue by coder-karen** [Automattic/wp-calypso#50664]
## Issue

When using the nav unification menu with a Jetpack connected site, the current similarity between the menus can lead to confusion over which dashboard someone is in. This can lead to further issues when the navigation flow doesn't match what is expected or expected custom navigation links are missing.

## Suggested solution

To help remedy this, one option is a small banner or clear notice at the top of the dashboard indicating when someone is viewing the nav unification menu.

**Comment by folletto** [comment]
See: pbAPfg-1vM-p2 for the discussion about this, as a banner/notice approach might not be the solution here.
