### ISSUE TITLE
Incorrect Jetpack connection banner on atomic sites with WooCommerce

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#50661]
There are several reports of this showing in WooCommerce:

 `Connect Jetpack to activate WooCommerce Shipping & Tax
 WooCommerce Shipping & Tax is almost ready to go! Once you connect Jetpack you'll have access to automated tax calculation and shipping label printing.`

![image.png](https://user-images.githubusercontent.com/31009008/109683592-e0ddc900-7b55-11eb-84e0-dc18856f1447.png)

It doesn't appear to be a plugin/theme conflict, so is likely due to a Woo or JP update (best guess).

Dropping this here quickly on mobile for tracking.

**Comment by tbradsha** [comment]
21495452-hc
28128569-hc

**Comment by jeherve** [comment]
Closing this in favor of https://github.com/Automattic/jetpack/issues/18977
