### ISSUE TITLE
Onboarding Designs - TT1 blocks content heading too large

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#50679]
In site editor testing it was noted how large the TT1 blocks starter content heading is:

![Screen Shot 2021-03-02 at 2 48 05 PM](https://user-images.githubusercontent.com/28742426/109731798-f40a8c00-7b89-11eb-9403-2fc6a1ecb4fa.png)

As seen above this heading takes up over half the vertical real estate of a page, and seems very excessive compared to the sizes of items in the header and on the page below.  This size causes confusion as the editor is loaded as it does not seem like it would have been 'meant to be' this large and something may be wrong with the site or layout.  

We should consider reducing the size of this heading.

**Comment by mtias** [comment]
I think it's fine to have an opinionated design element like this if it's part of why you would choose such a theme. We need more variety and perhaps optionality on the starter content in the home. Or other themes!

**Comment by Addison-Stavlo** [comment]
> We need more variety and perhaps optionality on the starter content in the home. Or other themes!

Agreed.  More variety and options would make this quite a bit more of an acceptable option.  As it stands right now its the only starter design for tt1-blocks which is kind of rough.

**Comment by ianstewart** [comment]
Going to close this one out as more variety and optionality up front is the plan.

- @jeffikus and co is working on bringing more Block themes to life, whose home page content we will feature in the design picker.
- @alaczek is working on adapting existing starter designs and other patterns to Block themes to the same end.
