### ISSUE TITLE
Regression test to make sure wpcom/etk loads more than the default patterns.

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#50684]
Related to the bug we experienced on GB 9.7.2: p1610667250003600-slack-CBTN58FTJ.

Fixed here: https://github.com/Automattic/wp-calypso/pull/48940.

Possible ways to test it:

- The obvious way would be an E2E that iterates through the patterns in the pattern inserter and verifies them. This would be added as an E2E test in Calypso;
- A PHP test that exercises the rest endpoint setup [here](https://github.com/Automattic/wp-calypso/blob/ce2e300561644aa6a2f38908ba7a4fd36f8d0689/apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php#L259) and makes sure it is present and returns the proper data?

**Comment by apeatling** [comment]
The e2e test might be problematic for iterating through patterns because themes can also add patterns. This would cause variable results in terms of patterns getting loaded. Would it be able to handle this?

**Comment by apeatling** [comment]
The PHP test seems smart. :+1:
