### ISSUE TITLE
Plans: user sees no-ads nudge when on a site with no-ads (not premium plan)

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5068]
Introduced via #5014 cc: @mtias 
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts for a site with 'no ads' (legacy) upgrade but not on premium plan (eg. my site watirmelon.com)
#### What I expected

Not to see a no-ads upgrade nudge as I already pay for no-ads
#### What happened instead

I can see a no-ads upgrade even though I already have paid for this - may cause confusion for a user with the legacy product as they may think "I already paid for that, do my readers still see ads?"
#### Browser / OS version

Chrome Latest OSX Latest
##### Nudge seen

![no ads nudge](https://cloud.githubusercontent.com/assets/128826/14872763/cdac3f7e-0d32-11e6-97cd-06424ff85c52.png)
##### Site has no-ads

![no ads paid](https://cloud.githubusercontent.com/assets/128826/14872781/f01840b2-0d32-11e6-973f-30f4378e0f38.png)

**Comment by rachelmcr** [comment]
This should be resolved as of https://github.com/Automattic/wp-calypso/pull/5050 — do you still see the issue with that fix?

**Comment by mtias** [comment]
Can you confirm if this is still an issue? Should have been fixed with #5050.

**Comment by mtias** [comment]
Ah, I see, individual legacy upgrade. We don't handle these well enough.

**Comment by alisterscott** [comment]
I'm still seeing this right now on WordPress.com even with #5050 merged

**Comment by rralian** [comment]
@mtias how should we address this? Should we include legacy upgrades in the `/sites/:site/plans` endpoint and check their status before we show nudges for particular features? We have the same issue for custom design and unlimited premium themes.

**Comment by mtias** [comment]
We need to expose grandfathered features and make nudges aware of them. There's quite a few of these.

**Comment by rralian** [comment]
Right, I'm asking you think `/sites/:site/plans` is the appropriate place in the API to do that or if we should add a separate endpoint. It would be very convenient to have current plans data and legacy upgrades in one place.

**Comment by mtias** [comment]
Yeah, I think so, though I'm nowhere nearly familiar enough with how the grandfathered features work to see if it makes sense.

**Comment by jeherve** [comment]
We also display that banner on Jetpack sites, where WordPress.com Premium is not a valid upgrade.

**Comment by mtias** [comment]
@jeherve that sounds like a very recent regression, these nudges were not displayed for jetpack before.

**Comment by mtias** [comment]
@jeherve I can't reproduce this with my jetpack sites. In which page are seeing it?

**Comment by jeherve** [comment]
I see the ad on `/sharing` for one of my Jetpack sites.

**Comment by alisterscott** [comment]
Re-tested and I can no longer reproduce this
