### ISSUE TITLE
Quick Start/Concierge: no daytime sessions available in UTC+13

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#50680]
### Steps to reproduce the behavior

1. Go to http://calypso.localhost:3000/me/concierge
2. Try and book a session

#### What I expected to happen
I can book a session during my daytime or evening in NZ.

#### What actually happened
The latest timeslot I can book is 5:15am on any day.

### Context
I found this while testing an OSS Citizen PR, #38919.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects ability of customers in some timezones to use the service.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="295" alt="Screen Shot 2021-03-03 at 13 27 38" src="https://user-images.githubusercontent.com/17325/109734026-27e6bf80-7c25-11eb-9866-c95514767f0f.png">

**Comment by bluefuton** [comment]
I think it'd probably be best not to offer Concierge at all if there aren't slots in reasonable daytime hours.

**Comment by davipontesblog** [comment]
Closing as this is no longer offered.
