### ISSUE TITLE
Backups: Jetpack connection has failed

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#50687]
When a site is taken from Simple to Atomic by clicking the Jetpack > Backup button, until the first backup is available, the user sees the message "Jetpack connection has failed". 
![Markup on 2021-03-03 at 14:09:23](https://user-images.githubusercontent.com/24914028/109755821-12c05f80-7c2a-11eb-91b4-95c8c9e31916.png)

### Steps to reproduce the behavior

1. Create a Simple Site with the Business plan
2. Go to Jetpack > Backup and click the **Activate Jetpack Backup now** button. 
3. Navigate away from the page after the message **Your first backup will be ready soon** appears.
4. Navigate back to Jetpack > Backup.
5. You will see the error **Jetpack connection has failed.**
6. Clicking on the **Reconnect Jetpack** button brings the user to the General Settings page but with the URL - `https://wordpress.com/settings/disconnect-site/siteaddress?type=down`

![Markup on 2021-03-03 at 14:12:47](https://user-images.githubusercontent.com/24914028/109756066-8c584d80-7c2a-11eb-9554-36a01a64240c.png)

#### What I expected to happen
While no backup is ready, I would expect the message to continue to say "Your first backup will be ready soon".

#### What actually happened
Jetpack is still connected to the site.  It looks like the issue is that no live backups are on file yet.  Once a full backup is ready, the normal backup screen begins to show. 

#### Temporary Workaround
I have been able to resolve this issue by queuing a full backup and then triggering a full Jetpack sync. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This appears to be affecting all users that go Atomic through activating a backup.

#### Video

https://user-images.githubusercontent.com/24914028/109756832-fc1b0800-7c2b-11eb-8da9-546a4e91f48d.mov

**Comment by JoshuaGoode** [comment]
This will also occur if when a site that does have backups reverts and goes Atomic again. When the site goes Atomic again, within a reasonable timeframe, it will have access to the previous backups available; however, they can't restore one immediately due to this.

We generally have to wait or perform a manual disconnect and reconnect to get it working faster.

I believe this message started appearing after we fixed another message that requested the user to supply credentials. Re: 6188-gh-Automattic/jpop-issues#issuecomment-734852170

 It seems to be the default message when the backup backend is still provisioning.
 
 I'm leaving this open here for now but we might need to move to the JPOP repo.

**Comment by metabreakr** [comment]
29656330-hc

**Comment by desnum** [comment]
A case of a user being confused by the wording on that screen: 30192050-hc

Perhaps some more appropriate text would be:

> ### Jetpack Backups are being created.
> This happens on newly created sites for the first 30mins to an hour. It's normal and Jetpack is working, it just doesn't have a backup yet.

**Comment by happychait** [comment]
I ran into this in 16821750-hc

**Comment by happychait** [comment]
I encountered this in 4466866-zen as well.

**Comment by cuemarie** [comment]
Ran into this here on a reverted then re-AT'd site: 4551054-zd-woothemes
Manually dis/reconnected JP to resolve

**Comment by kuropixel** [comment]
Ran into this while doing team testing and was confused by the messaging of Jetpack connection failed. If possible, we should definitely change the wording/message.

**Comment by joweber123** [comment]
Saw this again in this ticket - 5545762-zen

**Comment by liviopv** [comment]
7732457-zd-a8c
7766945-zd-a8c

**Comment by liviopv** [comment]
7807155-zd-a8c

**Comment by cat-og** [comment]
7816962-zd-a8c
