### ISSUE TITLE
Missing translations for empty cart copy

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50699]
## What

While testing for another bug in https://github.com/Automattic/wp-calypso/issues/50430#issuecomment-789608303_, I came across this un-translated text, shown to the user when the cart is empty:

"If you were trying to add something to your cart, there may have been a problem. Try adding it again."

### Video / screenshot

Scrub to the end of the video:

https://user-images.githubusercontent.com/1083581/109791959-4d6acd80-7c13-11eb-9746-b431818a5405.mp4

**Comment by michaeldcain** [comment]
We merged a new string for this error state in https://github.com/Automattic/wp-calypso/pull/50465. The translations should be available in 1-2 weeks.

**Comment by ciampo** [comment]
Thank you for the explanation @michaeldcain ! 

Have you considered using the [`hasTranslation()`](https://github.com/Automattic/wp-calypso/blob/trunk/packages/react-i18n/README.md#hastranslation) function?

```typescript
import { useI18n } from '@automattic/react-i18n';
import { useLocale } from '@automattic/i18n-utils';

const Component = () => {
  const { __, hasTranslation } = useI18n();
  const locale = useLocale();

  const fallbackText = __( 'this string has already been translated' );
  const newText = __( 'this string has not been translated yet' );
  const alwaysTranslatedText =
    locale === 'en' || hasTranslation.?( 'this string has not been translated yet' )
      ? newText
      : fallbackText;

  return <span>{ alwaysTranslatedText }</span>;
};

**Comment by michaeldcain** [comment]
@ciampo: TIL that `hasTranslation` exists :). I'll let the team know about it for future PRs.

**Comment by michaeldcain** [comment]
It looks like these translations are finished. I'm going to close this:

<img width="1373" alt="Screen Shot 2021-03-08 at 11 37 51 AM" src="https://user-images.githubusercontent.com/942359/110351434-d2cef300-8002-11eb-995b-da460be5d876.png">

**Comment by ciampo** [comment]
> TIL that hasTranslation exists :). I'll let the team know about it for future PRs.

@michaeldcain I learned about it just a few weeks ago too! I'm planning to write a little p2 about it soon enough

**Comment by sirbrillig** [comment]
@ciampo I assume that only applies to translations through `useI18n`; do you know if there's a similar mechanism for `useTranslate`? And/or should we be switching to using `useI18n`?

**Comment by ciampo** [comment]
> do you know if there's a similar mechanism for `useTranslate`? And/or should we be switching to using `useI18n`?

Hey @sirbrillig, I would recommend asking Team Global directly ( cc @Automattic/i18n )

**Comment by yuliyan** [comment]
@sirbrillig,

> do you know if there's a similar mechanism for `useTranslate`?

For `i18n-calypso` translations, you can use the following:
```
import i18n from 'i18n-calypso';
i18n.hasTranslation( 'Some string' );
```

> And/or should we be switching to using `useI18n`?

It's ok to switch, but I wouldn't say it's really necessary to do it right now. We plan to drop `i18n-calypso` (and `@automattic/react-i18n`) in favor of `@wordpress/react-i18n`, so eventually everything will be replaced, but I don't for certain how long it would take.
