### ISSUE TITLE
Browse Sites link is missing and add new site is always showing in Atomic sites

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#50697]
> On Calypso, the “Switch Site” link is shown in the top left corner of the nav. On wp-admin screens, this link goes away and an “Add new site” link is added to the bottom of the left nav.

props: @davemart-in 

The problem is that we removed the `wpcom_site_count` from wpcomsh

`/blob/17d7ffd4375cbbea2226115f16170e93771207ba/feature-plugins/masterbar.php#L135-L137`

We haven't witnessed that problem cause the `wpcom_site_count` is already cached in our sites..

### How to replicate
- Create a new Atomic site
- Go to WP Admin of that site

**Comment by tjcafferkey** [comment]
@cpapazoglou can you demonstrate this for me please, or provide some replication steps?

On WP Admin screens the "Switch site" link is still in the top left of the nav just says "Browse sites" instead and it takes me to `https://wordpress.com/home` whereas on Calypso it shows me the available sites list.

Thanks

**Comment by cpapazoglou** [comment]
We are doing 2 checks for `wpcom_site_count`

https://github.com/Automattic/jetpack/blob/bcf999945e90dee6df7be63126c120aa9a76d083/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L67

https://github.com/Automattic/jetpack/blob/bcf999945e90dee6df7be63126c120aa9a76d083/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L102

This option doesn't exist for new sites that haven't cached that option and therefore "Browse Sites" is missing and "Add New Site" is showing.

Acceptance criteria
- Users with 1 site
  - They should **not have** a "Browse Sites" link
  - They should **have** an "Add New Site" link

- Users with > 1 site
  - They should **have** a "Browse Sites" link
  - They should **not have** an "Add New Site" link


This is what single site user should be shown
![](https://cln.sh/A9Ltkz+)

Adding back the following code in wpcomsh `wpcomsh_set_connected_user_data_as_user_options` function should be enough
```
if ( isset( $value['site_count'] ) ) {
  update_user_option( get_current_user_id(), 'wpcom_site_count', $value['site_count'] );
}
```
