### ISSUE TITLE
User management: Not possible to update user info on "Team" tab on atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#50709]
### Steps to reproduce the behavior

⚠️ Issue → Trying to change the "author name" on a blog, there is a disconnect between the calypso People > Team page capabilities, and the site WP Admin page, under Users > Profile. Public display name cannot be updated in calypso, only on WP Admin.

None of these two places update the public display name on an atomic site: 
- https://wordpress.com/people/edit/ (this returned an error message)
- https://wordpress.com/me (this got updated, but has no effect on the atomic site)

1. Go to My Site > Manage > People > Team
2. Click on the admin user on the site (for my testing the user was the only admin on the atomic site, also the site owner)
3. Try to update any of the fields, namely "Public display name"
4. See error "There was an error updating @..."
5. Try to update the user profile display name in WP Admin, under Users > Profile. This works.

This is a common request users have, being that the public display name is what appear on blog posts under "Author" on their site. They are unable to update this to their liking in Atomic sites.

User report: 28124194-hc

**Comment by JoshuaGoode** [comment]
If we want to match Simple sites, Atomic sites should be syncing with the user's WordPress.com profile information and not allow connected admins to adjust things within People.

However, /me/account information is currently not syncing properly to Atomic sites.   There's an option issue for that at https://github.com/Automattic/wp-calypso/issues/46077

On top of fixing the error reported in this issue,  a decision should be made about whether we want Atomic to match Simple in this area.

**Comment by kspilarski** [comment]
I have a user with the same case in 3995495-zen

In https://wordpress.com/people/edit/ updating the public display name shows "There was an error updating username". However, they were able to change public display name from Advanced Users Management.

**Comment by kspilarski** [comment]
Same case as 28057166-hc.

**Comment by cpapazoglou** [comment]
Possibly related to https://github.com/Automattic/wp-calypso/issues/46077

**Comment by cpapazoglou** [comment]
On Atomic sites (only), administrators may edit User information (First Name, Last Name, Public Display Name) from `https://wordpress.com/people/edit`. While this works perfectly for other Users it doesn't work for administrators changing their own information. These Users get an error `Current user can not edit blog owner` while they are indeed the blog owners. 

The problem seems to be in a condition `$path_pieces[2] !== get_current_user_id()` which should return `false` but returns `true` because the types are different `string !== integer`.

**Comment by cpapazoglou** [comment]
Created a fix here D61899-code

**Comment by cpapazoglou** [comment]
Be ware that if https://github.com/Automattic/wp-calypso/issues/46077 is fixed, admins will only be able to change their data through `https://wordpress.com/me`. Thoroughly discussed in pd2C0z-1T-p2

**Comment by cpapazoglou** [comment]
Deployed r226399-wpcom
