### ISSUE TITLE
Editor: add "insert items" menu item

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#5070]
Adds an "insert item" menu bar to the editor toolbar to allow inserting various types of media or embeds into a post, similar to how the insert menus in mainstream applications work.

![artboard1](https://cloud.githubusercontent.com/assets/5431237/14875734/72a65c6a-0cc2-11e6-9e43-915999e507a8.png)

The button in the menu should default to opening the media dialog, but a click on the down arrow should open up the dropdown with all of the other embeddable options.

**Comment by danielbachhuber** [comment]
Will this work with generic shortcodes as well, or just oEmbed? If the former, are you building a generic form editor for shortcodes?

**Comment by dmsnell** [comment]
@danielbachhuber my initial goal was to build it for all shortcodes, but that is starting to look a bit more difficult technically to do, so my next path might be to try building a new view plugin for each additional integration. the view plugins can be made fairly simply and you can see some in the TinyMCE plugins directory, such as the contact form plugin.

**Comment by danielbachhuber** [comment]
@dmsnell Cool.

Just so it's mentioned, for shortcode integration, you might want to check out some of the prior art with Shortcake: https://github.com/wp-shortcake/shortcake

I do like your design decision to put the "Insert" UX into the TinyMCE toolbar. Shortcake is too closely coupled to the Media Library at the moment, and I now like your TinyMCE toolbar approach over our proposed approach of creating a dedicated button for it: https://github.com/wp-shortcake/shortcake/issues/281 One potential problem with the TinyMCE toolbar approach is how to accommodate more than, say, 6 options.

**Comment by dmsnell** [comment]
Thanks for the link to shortcake, @danielbachhuber.

My vision wasn't to add every shortcode to the editor, but rather allow the editor to render shortcodes and provide some dialog to edit them. Then, certain shortcodes could be lifted into the insert menu which are deemed more useful to be there.

Not all of the UX for this vision is figured out. For example, it's easy enough to write in a shortcode, but once it's in there and rendered in its box, you have to click _edit_ in order to modify it, instead of simply editing the attributes like normal text.

On the other hand, it looks pretty cool when you can see the rendered content while you edit.

**Comment by rachelmcr** [comment]
I'm going to close this issue, since the eventual switch to Gutenberg will provide more visibility and editing options for shortcodes/embeds.

#pre-gutenburg-bug-purge

**Comment by folletto** [comment]
Plus, it's already done in Calypso. ;)

**Comment by rachelmcr** [comment]
Well, true. :) I was thinking of the broader goal that Gutenberg will help with:

> my initial goal was to build it for all shortcodes
