### ISSUE TITLE
READER - Move subscription management to a single location

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#50718]
What
Managing your subscriptions can be difficult. One reason could be that these are currently manages in (at least) 3 places. If you visit subscribe. wordpress. com or https://dashboard.wordpress.com/wp-admin/index.php?page=subscriptions&option=settings - you'll see UI for Sites, Comments, and Settings. Both `sites` and `settings` will redirect you to the reader to manage them,  while you _can_ manage comments at these sites. In the descriptive paragraph at the top of the comments section on both pages, you are redirected to settings to stop receiving emails, which then redirects you to reader. 

I am requesting that managing comment subscription be moved to the reader with other subscription management.

Why
This will result in less confusion from our users (and us!) when everything related to a topic is in one place. It also helps simplify our engineering landscape by not having to maintain multiple UIs.

How
Screenshots ->

**Additional context**
![image](https://user-images.githubusercontent.com/16654218/109835701-768a5e80-7c11-11eb-8f44-9efc20cd7fc2.png)

![image](https://user-images.githubusercontent.com/16654218/109835737-7e4a0300-7c11-11eb-8bc6-838e3a5542da.png)
![image](https://user-images.githubusercontent.com/16654218/109835776-84d87a80-7c11-11eb-93d1-ea3826a2ee98.png)

**Comment by bluefuton** [comment]
Thanks for reporting this @cathymcbride! I'm also keen to see this consolidated (internal project proposal at p5PDj3-4lX-p2). 

> Both sites and settings will redirect you to the reader to manage them, while you can manage comments at these sites.

They'll only redirect you to Reader to manage if you're logged in to WordPress.com. If you're a logged-out user (for example, an email subscriber who does not have a WP.com account), you manage your subscriptions on subscribe.wordpress.com.

**Comment by davemart-in** [comment]
I believe this is somewhat resolved now with the centralized subscription management work that Apex released recently. Closing this issue out.
