### ISSUE TITLE
Publicize: errors when trying to connect to Twitter

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#50714]
### Steps to reproduce the behavior

1. Go to Marketing > Connections in Calypso
2. Try to connect a new Twitter account.
3. You'll receive the following error: `There was a problem connecting to Twitter to create an authorized connection. Please try again in a moment.`

This also seems to be an issue when trying to publicize posts on a site with an existing connection to Twitter. In those cases, the logs give us the following error:

```
Error 403 (Forbidden) -- Application cannot perform write actions. Contact Twitter Platform Operations through https://help.twitter.com/forms/platform. [261]
```

*********

Internal references: 
- p1614774616034300-slack-C1T3N5AMR
- p58i-a9H-p2

********

Reports:
- https://wordpress.org/support/topic/there-was-a-problem-connecting-to-twitter-to-create-an-authorized-connection/

**Comment by Nic-Sevic** [comment]
getting a report of this here with the 2 latest posts: 3789645-zen
They can toggle twitter publicize on in the editor and update but then it is automatically toggled back off.

**Comment by amamujee** [comment]
I also had the same issue and was able to reproduce it.

**Comment by susanjanec** [comment]
Reported in 8045722-hc - they are unable to connect a new account, but see a previous Twitter account that is no longer connected.

**Comment by zdenys** [comment]
28061144-hc

**Comment by kcswong** [comment]
reported 23912631-hc
follow up 3790756-zen

**Comment by obenland** [comment]
Should be fixed as of 19:13 UTC.
