### ISSUE TITLE
Focused Launch: Domain details view design parity (Part 1)

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#50719]
### Steps to reproduce the behavior

1. Open Focused Launch
2. Open Domain Details View

#### A/C

- [ ] _Free_ label should be aligned to left, same as price labels for other domain suggestions
- [ ] _Free_ label color should be green, same as the _Included with annual plans_ text for paid suggestions
- [ ] _Included with annual plans_ text should be displayed after price

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
- **Before**
<img width="1138" alt="Screenshot 2021-03-03 at 18 22 54" src="https://user-images.githubusercontent.com/14192054/109837627-0a7a1b80-7c4e-11eb-97b9-025f63605850.png">

- **After**
<img width="1134" alt="Screenshot 2021-03-03 at 18 34 29" src="https://user-images.githubusercontent.com/14192054/109838846-35b13a80-7c4f-11eb-9caf-ac5d1b0118f9.png">

**Comment by youbrokesomething** [comment]
This onboarding flow has been replaced by other new flows. Closing this ticket.
