### ISSUE TITLE
Sites: JavaScript error when navigating from `/sites`

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5072]
#### Steps to reproduce
1. Starting at URL: wordpress.com/sites
2. Select any site

#### What I expected
I should just gracefully be taken to the stats page for the selected site.

#### What happened instead
I see a javascript error in the console, and the new page does not render correctly.

#### Browser / OS version
Tested on chrome/osx

#### Screenshot / Video
[video link](https://cloudup.com/iqxdYmjFF_b+)

#### Notes
I'm not sure if we mean to have `/sites` be a supported landing page. If we do we should fix it, but if we don't then we should remove the route. Marking this as low priority because we don't link anyone directly to wordpress.com/sites in the course of calypso. However I don't know if we have any old links in forums or whether support might send that link to people.

/cc @mtias

**Comment by mtias** [comment]
I think this has something to do with the recent webpack chunk changes cc @blowery

**Comment by hoverduck** [comment]
#bug-scrub

Closing, this is fixed
