### ISSUE TITLE
Video views not counted in stats

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#50746]
Customer in #3791371-zen says there have been 0 video views in the stats in the past few days.

I tested viewing and confirmed that video views are not counted.

The visits from Malaysia, Japan are mine:
![Screenshot](https://d.pr/i/MoX4uV+)
*if image does not load, please click on this link  : https://d.pr/i/MoX4uV*

### Steps to reproduce the behavior

1. View a post with videopress file
2. check Video stats after 30 minutes

#### What I expected to happen
Video view stats to reflect views

#### What actually happened
0 views recorded in Stats

#### Is this specific to the applied theme? Which one?
n/a

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
no
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Does not block purchases

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Reproduced on Customer site and on my test site

**Comment by syds87** [comment]
The same seems to happen for #3792309-ZD.

**Comment by goblinartificer** [comment]
Likewise in #28247524-hc . In particular, this user reports:

- they are using the `wpvideo` shortcode, and have found that the `videopress` shortcode never records views;
- they could see views as of yesterday, but now they're missing for the past few days back to March 1;
- neither of their usual shortcodes, nor the Video block now works;
- they tested in Firefox, Chrome and Safari for Mac and for iOS and no luck on any of those.

Site is AT, no recent plugin changes. Reproduced on customer site.

**Comment by goblinartificer** [comment]
#3801055-zen

**Comment by thesacredpath** [comment]
Another report with video stats gone:

#28302845-hc
#3807826-zen

**Comment by desnum** [comment]
#28344864-hc

starting March 2

**Comment by msilbers** [comment]
another report of Video play stats missing starting March 1. seems like it happened around then for at least a few of these reports. for this particular user, they are now working again starting March 9

3804948-zd

**Comment by roundhill** [comment]
Hi y'all, our new video player rollout broke this for about a week :( We have implemented a fix but I'm afraid the stats from that time period were not recorded :(

We have also discovered that Chrome seems to be blocking the tracking pixel for this so we may need to overhaul the video stats to get something working reliably.

**Comment by roundhill** [comment]
Me again! We deployed another fix that should have the video stats working just like they used to. If any users still see inconsistencies after today, let me know!

**Comment by dolgelukkig** [comment]
4084916-zd
Video settings are not missing but according to the user they are not counted either. 
Maybe not related, posting it here just in case it is.

**Comment by nagpai** [comment]
@roundhill will this fix counts of past `days` too, or only of days after the fix?

Update: sorry cross that. I just read 

>We have implemented a fix but I'm afraid the stats from that time period were not recorded

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

Based on the lack of activity after merging, it seems that https://github.com/Automattic/videopress/issues/301 resolved this issue. 

📌 ACTIONS
- Closed as fixed
