### ISSUE TITLE
My Home: Launch button missing on atomic site

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#50757]
I helped a user in support today and noticed something strange in "My Home":

<img width="1269" alt="Screen Shot 2021-03-04 at 07 53 07" src="https://user-images.githubusercontent.com/31009008/109969826-b9f4d380-7cca-11eb-8074-dfdb8d110594.png">

The site is not launched - shouldn't there be a CTA here for "Launch" in My Home? I can only see a CTA in `My Site > Manage > Settings`:

<img width="1154" alt="Screen Shot 2021-03-04 at 09 23 12" src="https://user-images.githubusercontent.com/31009008/109970345-51f2bd00-7ccb-11eb-8414-4b8702c589fe.png">

Also, notice that on the first screenshot there is no "Coming soon" label under the site title in the sidebar on the left, at the top, and on this second there is. I am not sure what triggered it to appear, maybe it was navigating to Settings?

User: 3792490-zd-woothemes

**Comment by roo2** [comment]
hmmm it looks like the launch checklist is deliberately only enabled for dotcom/ simple sites. I'll have a bit more of a look into why this is

**Comment by roo2** [comment]
closing as duplicate/subset of https://github.com/Automattic/wp-calypso/issues/50523
