### ISSUE TITLE
Nav Unification: Sidebar continues scrolling infinitely past the bottom margin

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#50767]
I am not sure how to reproduce this, but while working on a test site and using the Astra theme templates in My Site > Appearance > Starter templates, I noticed the nav sidebar would continue scrolling past the end point at the bottom. You can see this happen on the video below. Collapsing it, and then expanding it again fixes the issue.

https://user-images.githubusercontent.com/31009008/109997234-60020700-7ce6-11eb-8bea-699837738721.mov

**Comment by cpapazoglou** [comment]
Thanks for reporting! This is happening to WP Admin, I am removing the label as it seems unrelated to nav-unification (which had scroll issues in Calypso).

**Comment by obenland** [comment]
I wonder if this is an effect of #50765 and the template picker running into the sidebar? In which case I'd probably close this as a duplicate.

**Comment by cpapazoglou** [comment]
This is a "core" behavior. In some pages (eg Posts) the sidebar sticks to the bottom while on other pages (eg Media, Themes) the sidebar scrolls indefinitely. 

This "infinite scroll" happens to pages that alter the `height` of the main content is altered after the initial load by adding elements with JS.
