### ISSUE TITLE
Help Bubble flashes on the My Home Page. 

### ISSUE THREAD

**Issue by rossanafmenezes** [Automattic/wp-calypso#50769]
When You go to the My Home page the Help bubble flashes for a bit and since it already shows on the More Help tab here:

![Screenshot 2021-03-04 at 12 48 19 PM](https://user-images.githubusercontent.com/30724184/110011614-a60e9900-7ced-11eb-972b-075c222e8b0a.png)

 it's probably not supposed to be showing at the corner. You can see it flashing on this Gif here:

![unnamed](https://user-images.githubusercontent.com/30724184/110011747-c76f8500-7ced-11eb-8ab7-436b229b9658.gif)

**Comment by getdave** [comment]
Known Issue not part of Nav Unification. It's because the `?` isn't hidden until the application detects that you've landed on the `Home` route. There is a slight delay due to the way routing works in Calypso.

**Comment by cpapazoglou** [comment]
Fixed here https://github.com/Automattic/wp-calypso/pull/50800
