### ISSUE TITLE
Checkout: Error messages don't persist when the last item is removed from the cart

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#50768]
### Steps to reproduce the behavior

Easiest to reproduce like this:

1. Add a domain to the shopping cart.
2. Add G Suite.
3. Remove the domain from the shopping cart.  This will automatically remove G Suite also, thereby emptying the cart.
4. You get redirected to the plans page.  Before the redirect, a brief red message (which comes from the server and explains why G Suite was automatically removed) flashes on the screen, but it disappears before you can read it.

#### What I expected to happen

I expected the message to persist onto the next page so that I could read it.

### Context

I feel like this might be a recent regression, but I'm not sure.

**Comment by DavidRothstein** [comment]
I can't tell if this is related to https://github.com/Automattic/wp-calypso/issues/48654 and https://github.com/Automattic/wp-calypso/pull/48658 or not (it might be, but it sounds a little different).

See also pbaDsf-hg-p2#comment-1697

**Comment by sirbrillig** [comment]
Ah... previously to https://github.com/Automattic/wp-calypso/pull/50465 we did not redirect if there were error messages shown (thanks to https://github.com/Automattic/wp-calypso/pull/44370) but now we probably do. That's a regression. I'll take care of it.

**Comment by sirbrillig** [comment]
I realized that we can actually just solve this by making sure error messages persist across page loads, which they used to do. I created https://github.com/Automattic/wp-calypso/pull/50805 to fix this.
