### ISSUE TITLE
VideoPress not working when blocking third-party cookies in Chrome

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#50772]
### Steps to reproduce the behavior

1. Go to https://tenacityofthesoul.net/test-video/ in a Chrome incognito browser window 
2. Observe that the video shows only a black box, rather than the video

#### What I expected to happen

I expected to see a video poster image, and to play the video.

#### What actually happened

I saw a black box instead. Allowing access to all cookies resolves this issue. 

### Context

3790657-zen
28185362-hc

#### Browser / OS version

* Chrome 89 on macOS 11.3
* [Firefox 86.0 on Mac OS X 10.14.0](https://www.whatsmybrowser.org/b/32W3B) (this is inconsistent for others)

#### Does this happen on simple or atomic sites or both?

Simple. Setting the site to private and then back to public does not resolve the issue, and neither does embedding with a Videopress shortcode. 

#### Is there any console output or error text?

```
videopress-routes.min.js?v=6&m=1614800504:2 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at bn (https://s0.wp.com/wp-content/plugins/video/assets/js/videojs/videopress-routes.min.js?v=6&m=1614800504:2:703697)
    at https://s0.wp.com/wp-content/plugins/video/assets/js/videojs/videopress-routes.min.js?v=6&m=1614800504:2:718883
    at https://s0.wp.com/wp-content/plugins/video/assets/js/videojs/videopress-routes.min.js?v=6&m=1614800504:2:720548
    at t.default (https://s0.wp.com/wp-content/plugins/video/assets/js/videojs/videopress-routes.min.js?v=6&m=1614800504:2:720615)
    at https://s0.wp.com/wp-content/plugins/video/assets/js/videojs/videopress-routes.min.js?v=6&m=1614800504:2:727851
    at https://s0.wp.com/wp-content/plugins/video/assets/js/videojs/videopress-routes.min.js?v=6&m=1614800504:2:727894
    at https://s0.wp.com/wp-content/plugins/video/assets/js/videojs/videopress-routes.min.js?v=6&m=1614800504:2:727898
```

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Markup 2021-03-04 at 10 41 48](https://user-images.githubusercontent.com/39252765/110014592-380fa500-7ce0-11eb-99ef-ae607fcc2f70.png)
![Markup 2021-03-04 at 10 36 12](https://user-images.githubusercontent.com/39252765/110014594-38a83b80-7ce0-11eb-985a-8cefca35941d.png)

**Comment by happychait** [comment]
23891221-hc > 3793531-zen

**Comment by joweber123** [comment]
Another report here - 28214485-hc

**Comment by happychait** [comment]
Got a report in 9109924-hc

My user also sees `No videos played` in the Stats and would like to check if it's related to this issue.

**Comment by adelineyaw** [comment]
Another report 28245671-hc > 3801104-zen

**Comment by jartes** [comment]
Another one on 21867305-hc

**Comment by simison** [comment]
Cc @josephscott for tracking 3rd party cookie issues.

**Comment by simison** [comment]
Cc @Automattic/greenhouse, it might make sense to show some readable error in this situation? It's for example all Safari users.

**Comment by roundhill** [comment]
I think we can fix this, thanks for the heads up

**Comment by roundhill** [comment]
Reopening because fix hasn't been deployed yet, should be out tomorrow.

**Comment by roundhill** [comment]
> My user also sees No videos played in the Stats and would like to check if it's related to this issue.

@happychait I think this may be another bug that we are working on fixing ASAP, will let you know.

**Comment by davipontesblog** [comment]
@roundhill the issue wasn't reopened so I did that just now. How can we track the deployment so that we know when to close?

**Comment by roundhill** [comment]
> @roundhill the issue wasn't reopened so I did that just now. How can we track the deployment so that we know when to close?

Thanks, I swear I clicked the button! This should be fixed now!

**Comment by roundhill** [comment]
> My user also sees No videos played in the Stats and would like to check if it's related to this issue.
> @happychait I think this may be another bug that we are working on fixing ASAP, will let you know.

This should also be fixed now @happychait. Unfortunately the video plays stats from the last few days were not recorded :(

**Comment by roundhill** [comment]
Thought I'd add some details - this bug didn't have anything to do with 3rd party cookies - but the fact that Chrome does not allow access to localStorage in incognito mode. Our player was naively thinking it could use localStorage and an exception was being thrown when it tried to access it. We added some safe helper methods around localStorage access to fix the issue.

**Comment by davipontesblog** [comment]
Great! Thanks for clarifying @roundhill! I will close the issue now.
