### ISSUE TITLE
Domains: search suggests domain I already purchased

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#5077]
Steps to reproduce:

- Purchase a domain via `/domains/add`.
- After `/checkout/thank-you`, go back to `/domains/add`. Notice you'll be offered the same domain you just registered.
- Select that domain again. After checkout, you'll have renewed the domain for another year.

This is even more confusing if the first purchase was completed using a plan credit. When a domain is bundled with a plan, its expiration date isn't visible from `/purchases` so we can't tell the domain has been renewed. The user will be charged again, but it's not clear they got another year of the domain.

This has some implications on cancellations and refunds, which I describe in 13689-pb.  

Ideally, we shouldn't display domains the user just purchases in the domain search.

**Comment by umurkontaci** [comment]
@fabianapsimoes do you know in which suggestion vendor variation you were in? The domain shouldn't be suggested in there at all.

**Comment by fabianapsimoes** [comment]
I didn't notice it back then, but I was able to reproduce this again with account `fabianatestingon20160504132857` which is on `namegen`, and account `fabianatestingon20160504133527` which is on `domainsbot`.

**Comment by umurkontaci** [comment]
Thanks for the repro fab 

/cc @aidvu

**Comment by aidvu** [comment]
Could be a caching problem. Need to check if namegen/domainsbot gets updated once we register something (which I doubt).

I'm thinking of a check before adding to cart.

**Comment by umurkontaci** [comment]
@aidvu passing this on to you since it looks like it's your area of expertise :) lmk if you want to me look at it

**Comment by umurkontaci** [comment]
@aidvu I think this has been fixed, if not, you can reopen it
