### ISSUE TITLE
New Onboarding: plans billing period toggle translations inconsistencies

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50787]
## What

The "Monthly" / "Annually" labels for the plans grid billing period toggle are being translated inconsistently — e.g. sometimes as adjectives (as in "Monthly plan", sometimes as adverbs "Pay monthly"). This leads to inconsistent translations in the switch toggle, for example in the italian locale:

![image](https://user-images.githubusercontent.com/1083581/110104292-41177980-7da7-11eb-9714-02fa1f76c426.png)

_(Ideally, the labels should either say "Mensile / Annuale" or "Mensilmente / Annualmente", but currently have a mix of both)_

## Why

This doesn't look/read good in certain languages, and a poorly translated UI certainly doesn't make a great impact on our users

## A/C

- [ ] The "Annually" and "Monthly" string translations should be changed to include the context (e.g. "Adverb form")
- [ ] The "Annually" and "Monthly" string translations should have a more clear translators comment ("As in "Pay Monthly", as opposed to "Pay Annually"))

## Context

Without providing additional context to the translations, we don't have the guarantee that translators will translate both "Annually" and "Monthly" in the correct form.

**Comment by ciampo** [comment]
@razvanpapadopol and @ollierozdarz , do you have a preference between suggesting "Monthly" as an adverb (as in "Pay monthly") or as adjective (as in "Monthly plan") ?

**Comment by ollierozdarz** [comment]
Hey, @ciampo! I don't have a strong opinion about this, but I think it would be safest to stick with constancy and display it how control does — adverb (as in "Pay monthly").
