### ISSUE TITLE
Show the Happy Chat sidebar if there’s an active chat. 

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#50792]
See p7DVsv-aFw-p2#comment-34942

> When Calypso loads, show the Happy Chat sidebar if there’s an active chat. I’m not sure why we don’t already do this, TBH.

**Comment by cpapazoglou** [comment]
Closing this as we are going to decouple the Happy Chat button https://github.com/Automattic/wp-calypso/pull/50800#issuecomment-792793805
