### ISSUE TITLE
Nav Unification: Sidebar is empty on mobile viewports

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#50801]
### Steps to reproduce the behavior

Switch to mobile viewport in developer tools of your browser.

1. Go to wordpress.com/home
2. Click on W logo top left corner.

#### What I expected to happen

To see the sidebar? List of sites?

#### What actually happened

Blank screen was shown.

#### Browser / OS version

Firefox 86, OSX

Safari 14 - **not reproducible/not affected**.

#### Is this specific to the applied theme? Which one?

Does not seem so.

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Unable to navigate Calypso 😱 

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/3392497/110145177-0e827680-7dd1-11eb-8aa2-5876fdebe834.mov

**Comment by mmtr** [comment]
I'm not able to reproduce this. Tested in Firefox 85 and 86.

https://user-images.githubusercontent.com/1233880/110301579-854d8880-7ff8-11eb-8549-4c44a1e28e4d.mov

Am I missing any testing step?

**Comment by klimeryk** [comment]
No, there's nothing special that I'm doing (the API is not sandboxed, I'm using staging if that matters). I can easily reproduce 100% of the time. Tried different sites, checking if the cart abandonment notice was causing this (does not appear so) or sidebar warnings for domains (doesn't seem to be the case either).

OK, I _think_ figured it out - toggling uBlock Origin off seems to have fixed it. Now even with on, the sidebar is showing up. Closing as probably something specific to my set-up - sorry for the false alarm!
