### ISSUE TITLE
Find a way to allow VideoPress videos to work with trackers blocked

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#50812]
Currently, VideoPress videos include a Google Analytics tracker. (Documented here: 814-gh-Automattic/greenhouse)

Browsers that block trackers (Such as DuckDuckGo, Brave etc.) cannot view videos, unless viewers know how to allow the use of these specific trackers.

A user would like this requirement removed, so that viewers can view their videos even with the trackers disabled.

User request: 3791685-zd-woothemes
Relevant conversation: p1614830897415000-slack-C0CMN0V97

**Comment by ivan-ottinger** [comment]
The user suggested that we could display a message when the video is blocked:

> It would be nice to possibly have a message embedded in the videos that allows people with the tracker blocker to know why the videos are blank on DuckDuckGo as an interim fix.

**Comment by happychait** [comment]
Sounds similar to https://github.com/Automattic/wp-calypso/issues/50772

**Comment by simison** [comment]
cc @Automattic/greenhouse 

It should just work and quietly ignore stats in those cases.

**Comment by roundhill** [comment]
Should work fine now that we don't use cookies any longer for private video authentication.
