### ISSUE TITLE
Domains: Subdomains accessible when TLD is under maintenance, while root domain isn't

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#50824]
### Steps to reproduce the behavior

- When a TLD is under maintenance, open https://wordpress.com/domains/manage and click on that root domain name.
- Notice that a maintenance message appears, which blocks the DNS management section.
- Try the same for a subdomain of that root domain, notice that it doesn't block the DNS management section.

#### What I expected to happen

If root domain's DNS management is blocked during maintenance period, I expect a similar a similar notice for subdomains too.

#### What actually happened

Subdomains' DNS management is not blocked.

### Context

Found by manual testing

#### Browser / OS version

Not applicable. I was on Firefox 86 with Mac 11.2.2 though.

#### Is this specific to the applied theme? Which one?

Not applicable

#### Does this happen on simple or atomic sites or both?

Both simple and Atomic

#### Is there any console output or error text?

Not applicable

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Not sure 🤔 

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="792" alt="Screenshot 2021-03-06 at 3 14 15 PM" src="https://user-images.githubusercontent.com/18581859/110244228-b63fa600-7f83-11eb-952f-815a243ffcdd.png">

<img width="767" alt="Screenshot 2021-03-06 at 3 14 22 PM" src="https://user-images.githubusercontent.com/18581859/110244226-b50e7900-7f83-11eb-9c4a-7d4471965d4e.png">

<img width="789" alt="Screenshot 2021-03-06 at 3 14 29 PM" src="https://user-images.githubusercontent.com/18581859/110244222-b344b580-7f83-11eb-8ab4-6b5bc343271d.png">

#### Notes

@Automattic/cobalt team, if this is by design/expected, feel free to close the report!

**Comment by klimeryk** [comment]
Thanks for the report! This is by design. The subdomain is, by its nature, always a mapped domain. As such, it will not trigger any changes on the root domain. DNS editor is not impacted by registrar maintenance either. All mapping functionalities should work correctly even if the root domain (or TLD) is under maintenance 👍
