### ISSUE TITLE
Payments Block: Block account closure when a user has active recurring subscriptions

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#50820]
**What**

We should block account closure when a user has active recurring subscriptions. Or alternatively, a recurring subscription should be canceled automatically when the WP.com account that owns the sub is closed.

**Why**

Currently, a user can close their WP.com account even if they still have active recurring subscriptions. Due to this, a user continues to be charged for the subscriptions even after account closure, which is really a pain point. 

**Additional context**

3788140-zen | p1615066160128800-slack-C02BEP610

**Comment by DavidRothstein** [comment]
We'll track blocking this in the API endpoint in the payments backlog here: c/Uv4KmiO5-tr

I think that would give an error message something like "This user account cannot be closed while it has active subscriptions" if the user tries to close their account in that situation.

Then we can leave this issue open if someone wants to fix it in a nicer way in Calypso, to give a more user-friendly process for guiding them to cancel their recurring payments on other sites (similar to how it works for WPCOM and Jetpack) before they actually attempt the account deletion.

**Comment by pottedmeat** [comment]
I believe this has been addressed and this issue can be closed.

**Comment by DavidRothstein** [comment]
Yes, the underlying bug is fixed.

It still doesn't have the same nice flow that WordPress.com and Jetpack have, but it does prevent the account cancellation (after the user actually tries it) which is the most important part.

The nicer flow is an enhancement that no one is likely to add soon, though, so will leave up to someone else to close this issue without that if desired :smile:

**Comment by hacchism** [comment]
> but it does prevent the account cancellation (after the user actually tries it) which is the most important part.

Indeed, that's the most important part✨ If it does prevent the account cancellation already, I think it's okay to close this issue. But I'd defer to you two whether this can be closed or not👍
