### ISSUE TITLE
Domains: CNAME label flows outside available space on mobile views

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#50823]
### Steps to reproduce the behavior

- Start at https://wordpress.com/domains/manage 
- Click on a domain name for which DNS is managed at WordPress.com.
- For a CNAME record on that page (add one if there isn't one), notice that the label overflows available space.

#### What I expected to happen

The CNAME label appears within the box.

#### What actually happened

Overflows available box space.

### Context

Found by manual testing
#### Is this specific to the applied theme? Which one?

Not applicable

#### Does this happen on simple or atomic sites or both?

Not applicable

#### Is there any console output or error text?

Not applicable

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low priority

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="477" alt="Screenshot 2021-03-07 at 8 22 50 PM" src="https://user-images.githubusercontent.com/18581859/110244081-20a41680-7f83-11eb-9b45-375c0acef83d.png">

**Comment by arunsathiya** [comment]
<img width="1340" alt="Screenshot 2021-03-06 at 3 19 37 PM" src="https://user-images.githubusercontent.com/18581859/110244109-3e717b80-7f83-11eb-82f7-31b3b5eaaeac.png">

If I am seeing this correctly, the label is not centered on the desktop view either.

**Comment by Gilmoursa** [comment]
I'm not able to reproduce this issue on mobile. On desktop, I notice the issue but it is very slight.
![image](https://user-images.githubusercontent.com/10321421/110336000-706df680-7ff2-11eb-9098-440aed56931c.png)

**Comment by klimeryk** [comment]
Thanks for reporting! I was able to reproduce - it's indeed a small alignment issue, but it's a quickfix, so I created one here: https://github.com/Automattic/wp-calypso/pull/50846
