### ISSUE TITLE
Editor: Failing to trash post gives no visible error

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#5082]
#### Steps to reproduce
1. Create a new post and save the draft (or edit an existing post)
2. Disable your internet connection
3. Attempt to trash the post

#### What I expected
Feedback saying the post was not trashed

#### What happened instead
Nothing, the operation fails silently.  There are errors in the console log with `ERR_INTERNET_DISCONNECTED`, but the user never sees that.

#### Screenshot / Video
For contrast, this GIF also includes the error displayed when the Publish action fails:
![wp-calypso-trash-post-no-internet](https://cloud.githubusercontent.com/assets/7233112/14886412/b21b3562-0d1e-11e6-9227-b84bb7f6e22c.gif)

**Comment by jeremeylduvall** [comment]
This should be fixed via #5405.
