### ISSUE TITLE
Nav Unification and Dashboard Color Schemes for "Updates" section for Atomic Sites

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#50826]
The number of plugin/theme updates available is hard to see on the Aquatic Dashboard Color Scheme.

### Steps to reproduce the behavior

1. Apply the Aquatic Dashboard Color Scheme to your Atomic site 
1. Visit https://wordpress.com/home/ and select an Atomic site
2. Try to read the number of "Updates" available to the navigation menu on the left
3. The "number" of updates is hard 
4. Click on "Updates"
5. You'll land on the "Updates" page and the number, in my case 5, is easier to read

#### What I expected to happen
I expected that what I saw at step 5 to be seen right away in step 2. I shouldn't have to click on Updates in order for the "number" of updates to be easier to see. 

#### Browser / OS version
Version 88.0.4324.192 (Official Build) (x86_64)/ MacOS Big Sur v11.2.2

#### Does this happen on simple or atomic sites or both?
Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/10015451/110248363-aa7dc080-7f3e-11eb-9edc-16babee20955.mov

Link to image/gif: https://d.pr/v/jXKQ3F

**Comment by sixhours** [comment]
I checked all color schemes, and it happens with the Light color scheme, too:

<img width="283" alt="Screen Shot 2021-04-27 at 1 47 23 PM" src="https://user-images.githubusercontent.com/2124984/116288307-6305fa80-a75f-11eb-89ae-2005310205d0.png">

And to a lesser extent with Powder Snow and Sunset:

<img width="287" alt="Screen Shot 2021-04-27 at 1 48 44 PM" src="https://user-images.githubusercontent.com/2124984/116288326-67caae80-a75f-11eb-8faf-c09a494f522b.png">

<img width="289" alt="Screen Shot 2021-04-27 at 1 50 00 PM" src="https://user-images.githubusercontent.com/2124984/116288397-7c0eab80-a75f-11eb-953e-ba5d758cc15c.png">

So probably a color value needs to be updated in the individual annotations. I'll take a look at each.

**Comment by sixhours** [comment]
Taking another look, it seems we're using the wrong variable for the `.count` selector, which explains why some color schemes lack contrast. We were using `--color-sidebar-menu-selected-text` but in this case we want `--color-sidebar-submenu-selected-text` since it's under a submenu. So I think I can make a change to just the sidebar variables and it will fix all color schemes.
