### ISSUE TITLE
Nav Unification: loss of ability to control several discussion options on simple sites.

### ISSUE THREAD

**Issue by stephdau** [Automattic/wp-calypso#50844]
With the removal of the "Discussion" option in the "Settings" menu, users are now expected to go to `wordpress.com/settings/general/[the site]`, and then click on the "Discussion" tab to get to `wordpress.com/settings/discussion/[the site]`.

Unfortunately, the Calypso Discussion screen is missing several features when compared to its Wp-Admin equivalent, **for simple sites**, such as the Akismet controls shown below.

<img width="928" alt="screenshot-2021-02-24-at-14 54 19" src="https://user-images.githubusercontent.com/1891/110342620-8516b280-8023-11eb-8cfa-39e0c3e2ce6a.png">

One can still navigate manually to `[the site].wordpress.com/wp-admin/options-discussion.php`.

It's also interesting to note that the unified nav kept the "Reading" entry in the "Settings" menus, which still leads to `/wp-admin/options-reading.php`.

Unless we do port the missing features to Calypso ASAP, I think we should preserve the "Discussion" entry, and with it our users' ability to access `/wp-admin/options-discussion.php` so they can keep controlling those missing settings.

**Comment by tjcafferkey** [comment]
Related https://github.com/Automattic/wp-calypso/issues/52862

**Comment by tjcafferkey** [comment]
This may also be considered fixed once https://github.com/Automattic/wp-calypso/issues/51441 is completed.

**Comment by tjcafferkey** [comment]
@stephdau we have implemented an early version of a feature we've been working on where a user can use the Screen Options tab to switch between Calypso / WP Admin for views that appear in both. This should satisfy the below

>I think we should preserve the "Discussion" entry, and with it our users' ability to access /wp-admin/options-discussion.php so they can keep controlling those missing settings.

Based on this, I am going to close this issue but feel free to reopen for discussion if you feel it's not a good enough solution.
