### ISSUE TITLE
Jetpack Connect: Send a email reminder for those users who didn't complete the connection

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#5086]
When a user starts a connection process in jetpack-connect, but they don't have an installed or active version of jetpack in their sites, we need to redirect them to their own wp-admin so they manually install/active jetpack. On those cases, we depend on them to manually click on the "connect" button of their dashboards to complete the process. 

Since some users can stop there and not keep going with the whole flow, we need to detect when this happens (probably storing some flag in .com user profile when they start the flow) and send them an email reminder after X time that they can complete the connection doing this or that.

**Comment by tyxla** [comment]
This is still useful to have.

**Comment by tyxla** [comment]
This would still be useful to have and a good way to reduce Jetpack signup/onboarding churn rate.

cc @Automattic/jetpack-voyager in case they're interested to give it a spin.

**Comment by monsieur-z** [comment]
I'll add it to our maintenance board so that we keep track of it. I doubt it will be addressed in the short or medium term, though.

**Comment by robertbpugh** [comment]
This is also in my marketing email backlog. But also not a short term fix. Will add this ticket as a reference.

**Comment by robertbpugh** [comment]
We did this idea! Although, it's not working as well as we'd hoped. If you have any ideas on how to improve, please let us know here: pbNhbs-19s-p2. Going to close this ticket.
