### ISSUE TITLE
Nav Unification: Add VideoPress Options to Media Library

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#50867]
**What**
The Media Library accessed from the Media section of the new Nav Unification dashboard does not show the VideoPress options for the individual media items. I currently refer users to the Media Library on the WP Admin dashboard to see that information. Now that the WP Admin link is gone, it will be harder for users to get that information.

**Why**
We refer users to the WP Admin Media Library to get the VideoPress shortcode when they want to resize their videos: https://wordpress.com/support/videopress/#resize-a-video or disable sharing: https://wordpress.com/support/videopress/#video-press-sharing-settings

**How**
Add the VideoPress information to the sidebar of the media screen when you edit it from Calypso.

![screenshot](https://d.pr/i/YMmEHt+)
Image URL: https://d.pr/i/YMmEHt

**Comment by Aurorum** [comment]
PR for this issue in #50895! :)

**Comment by ccwalburn** [comment]
Thanks @Aurorum ! Can you include all of the VideoPress options? 
![screenshot](https://d.pr/i/K6lJey+)
Image URL: https://d.pr/i/K6lJey

**Comment by Aurorum** [comment]
I'm afraid that I've never successfully been able to connect a front-end setting to a backend change! I'll definitely experiment more regardless, but I feel like I should say that now since I don't think I'll be able to manage that anytime soon. :)

**Comment by ccwalburn** [comment]
Created new request for the VideoPress Share and Rating Options part of this request here: https://github.com/Automattic/wp-calypso/issues/51040
