### ISSUE TITLE
Settings: analytics settings should not be reachable for Jetpack sites

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5087]
I noticed that you can reach the analytics settings page for a jetpack site, though it's not possible to enable this feature for jetpack sites (it's not part of jetpack business). It's removed from the section-nav for settings for jetpack sites, but you can still reach it by switching sites.

You can do so by visiting the analytics settings page for a dotcom site:

http://wordpress.com/settings/analytics

Select a dotcom site to load the analytics page directly. Then switch the site to a jetpack site.

![jetpack analytics page](https://cloudup.com/cULWLvPUymP+)

We should do _something_ else instead... open to suggestions. Possibly take them to the site-picker page (http://wordpress.com/settings/analytics) or switch them to the general settings page (`wordpress.com/settings/general/:site`).

Not sure if this issue is related to our recent nudge or if it was always present... I suspect the latter. But adding it to Triton's milestone to address as low priority.

**Comment by rralian** [comment]
@lancewillett I changed the title back. The issue is that you can get to this page for a jetpack site and you should _not_ be able to get to this page for a jetpack site.

**Comment by lancewillett** [comment]
Aha! Gotcha. "Analytics settings page short not be reachable for Jetpack sites."
