### ISSUE TITLE
Welcome Tour: hover tips on minimize, close, maximize buttons

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#50875]
To alleviate confusion and add clarity to the purpose of icon buttons, add labels on hover:
- [x] Minimize #51851
- [x] Close #51851
- [ ] Maximize (in the minimized state)

[Welcome Tour code](https://github.com/Automattic/wp-calypso/blob/578c58b8d687dbc28a59e4d06c2f875a655adfb3/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js
):

 
See relevant item in CfT feedback
pbAok1-1LS-p2#welcometourfeedback

**Comment by p-jackson** [comment]
Decided not to add a tooltip for the maximise button because it already has a text label.
