### ISSUE TITLE
Welcome Tour: show new Tour to all new users except NUX for mobile users

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#50877]
## Show Welcome Tour to all new users (except AnchorFM)
- [x] verify we don't need to handle Anchor.fm users via NUX  ~~keep  NUX code for anchor users because custom content has been created in the NUX modal format and until new content is created for the Tour format we need to keep showing NUX for Anchor.fm new users~~
- [x] remove experiment code D53894-code (D59151-code)
- [x] update the block editor code that launches the tour vs nux:  https://github.com/Automattic/wp-calypso/blob/3b7743c86c77b3811e512fd351ad63e0b287ddde/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/block-editor-nux.js#L54

When the Anchor.fm content is moved to Tour format then the NUX modal code should be removed.

**Comment by p-jackson** [comment]
> remove experiment code

D59151-code is ready for review

**Comment by p-jackson** [comment]
This shipped in #51055 and D59151-code
We ended up showing the same welcome experience (either modal or tour) to AnchorFM users because the AnchorFM specific onboarding content has been removed. So it only depends on whether you're on mobile or not.
