### ISSUE TITLE
Domain Picker: Integration testing

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#50888]
### Why

There are countless reasons for adding integration tests to our components and packages but the main reason is to (re)gain confidence in our code. We want to have the confidence that the `<DomainPicker/>` component:
* Works as expected in any environment.
* Doesn't break when new features are introduced. 
* Doesn't break when existing features are updated. 

### What
We want to write a series of integration tests (see Acceptance Criteria) to gain the desired confidence. 

#### Unit tests
Since Unit Tests should be run in isolation, it's okay to mock every external dependency (either managed or unmanaged). That means that `props`, `hooks`, `contexts`, ... are fine to mock.

#### Integration tests
Integration tests shouldn't run in isolation, because they should mimic the user's behavior as close as possible. Therefore we only should mock unmanaged/external dependencies. This means that only the data stores should be mocked. One could argue that we manage them but external actors have an impact on it as well and therefore we have to treat it as unmanaged.

All other managed dependencies (e.g. hooks & props) should **not** be mocked.

### Acceptance Criteria

We want to cover the following testing scenarios:

#### Overview
* [ ] When the user enters the DomainPicker, it sees its current subdomain suggestion.
* [ ] When the user enters the DomainPicker, it sees a list of 5 paid domain suggestions.
* [ ] When the user enters the DomainPicker, it sees a recommended paid domain suggestion.

#### Selecting a domain
* [ ] When the user selects the free domain, the `onExistingSubDomainSelect()` method is called.
* [ ] When the user selects a paid domain, the `onDomainSelect()` method is called.

#### Searching & Selecting a domain
* [ ] When the user performs a search, the paid suggestions are updated.
* [ ] When the user performs a search, the last paid domain suggestion should be the original recommended.
* [ ] When the user performs a search, clicks on "see more results", more suggestions should be loaded. 

Integration test:
<img width="767" alt="Screenshot 2021-03-19 at 09 19 30" src="https://user-images.githubusercontent.com/12104589/111751054-4f2fc480-8894-11eb-80b7-a7dd67e7c7f1.png">

#### Already own a domain
* [ ] When the user clicks on the "Already own a domain" button, it is redirected.

**Comment by StefanNieuwenhuis** [comment]
I found a great book on Unit/Integration testing principles and this is what they write about integration tests:

> The general guideline for integration testing is to cover the
longest **happy flow and any edge cases that can’t be covered by unit tests**. The longest
happy path is the one that goes through all out-of-process dependencies.

Source: https://livebook.manning.com/book/unit-testing/chapter-8/80

I believe the longest happy flow in the domain picker is:
The user enters the DomainPicker, searches for a custom domain and selects one of the results. 

Acoording to the book, all other tests should be considered unit tests. What do you think @ciampo, @alshakero?

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/issues/50889

**Comment by ciampo** [comment]
Opened #51286 to track the remaining part of the integration test that was not implemented in #50889
