### ISSUE TITLE
Signup plans step in RTL: Scroller not working and a blue'ish layer

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#50896]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/start/ar on a mobile screen size.
2. Signup and proceed to the plans step.
3. Click on the left arrow scroll

#### What I expected to happen

I expected the plan to the left of the Personal plan to come into view.

#### What actually happened

Clicking the left arrow did nothing. However clicking on the right arrow brings into view the plans to the left of the Personal plan.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Medium to high.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![arsignup](https://user-images.githubusercontent.com/1269602/110483562-d7350200-810f-11eb-9f93-ca1a5e2d312a.gif)

**Comment by michaeldcain** [comment]
@niranjan-uma-shankar as you said, this is probably pretty high priority (broken for RTL mobile users). Is @Automattic/martech going to triage this?

**Comment by cathymcbride** [comment]
@jaswrks - would this be martech's?

**Comment by niranjan-uma-shankar** [comment]
We had a discussion about it in pau2Xa-2EA-p2#comment-9885. The conclusion reached was that we'd like to wait for the A/B test currently running on the plans step, described in pbxNRc-D0-p2, to finish in a few days. The treatment in that test introduces a new layout and hence fixes the bug. If it wins, we can deploy it to all users. If treatment loses, we will prioritize fixing this bug. Does that sound reasonable?

**Comment by kwight** [comment]
@niranjan-uma-shankar Any update here as to which direction to go (or was taken)?

**Comment by niranjan-uma-shankar** [comment]
@kwight We tested a new mobile layout for this page and the treatment came out a winner. The new layout fixes the issue reported here, so rolling out treatment should resolve this issue. The work to roll out is scheduled to be picked up in May as per the discussion in pbxNRc-D0-p2#comment-1947. cc @southp @jdc91

**Comment by simison** [comment]
The schedule indicates normal prio treatment vs high prio so I changed, but feel free to change back to high if need!

It's a bit hard for me to tell how broken this feels, tho my gut says it could need a high prior fix based on customer impact, and multiple months in a broken state is a bit much?

**Comment by niranjan-uma-shankar** [comment]
@simison I've gone ahead and prepared a PR https://github.com/Automattic/wp-calypso/pull/51866 that launches treatment to 100% traffic, so once that deploys the bug will be fixed. The PR does not do a proper cleanup and I'll leave it to @southp to slot that in the @Automattic/martech-decepticons pipeline, but https://github.com/Automattic/wp-calypso/pull/51866 would be a good interim measure until that happens.

**Comment by simison** [comment]
Very cool, thanks @niranjan-uma-shankar ! :-) That makes sense — just roll out to fix the bugs (I think there were a few more with the scroller thingy?) and that'll take the time-pressure off-of the clean up. Thanks a lot again!

**Comment by niranjan-uma-shankar** [comment]
Fixed with https://github.com/Automattic/wp-calypso/pull/51866, so closing this issue.
