### ISSUE TITLE
WPCOM Plugins: All My Sites shows an error if the user only has wpcom sites

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#5090]
If a user only has WPCOM sites (no Jetpack sites), the Plugins page displays an error when All My Sites is selected in the site picker.

#### Steps to reproduce
1. Log in to WordPress.com with a user that has only WordPress.com sites (no Jetpack sites)
2. Go to https://wpcalypso.wordpress.com/plugins (All My Sites Plugins page)

#### What I expected

A WordPress.com-specific plugins page, similar to what you see for an individual site.

#### What happened instead

I saw this error message:

> Oops! Not supported
>This site doesn't support installing plugins. Switch to a self-hosted site to install and manage plugins

#### Browser / OS version

Mac OSX 10.11.4, Firefox 45.0.2

#### Screenshot / Video

![screen shot 2016-04-28 at 6 05 19 pm](https://cloud.githubusercontent.com/assets/8658164/14894600/454b1580-0d6c-11e6-88cf-3a07473c73fe.png)

**Comment by drw158** [comment]
cc @rodrigoi
