### ISSUE TITLE
Nav Unification: Duplicate menu items in Appearance based on theme

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#50939]
### Steps to reproduce the behavior

1. On a Simple site (Premium plan)
2. Go to Appearances > Themes and activate the Ovation theme
3. Head to a WP Admin screen e.g. Settings > Media
4. Hover over Appearance menu item. Observe the duplicated sub menu items.

#### Context

> We’re adding a return param to all menus so users can go back to Calypso after doing some actions (e.g. closing customizer).

> On the other hand our Admin_Menu class, unregisters the default menu and register new ones so they point to the appropriate screen in Calypso or WP Admin.

> I think the issue is in that “unregisters the default menu”, we don’t expect the default menu to have the return param and possibly due to that we are not unregistering it, causing the menu to appear twice

> I think the issue is that sometimes the request uri already contains a return param and in these cases we shouldn’t add another one:

<img width="889" alt="Screen Shot 2021-03-10 at 11 40 19" src="https://user-images.githubusercontent.com/8639742/110618495-b233a400-818e-11eb-84b9-3d9a440ae72e.png">

https://github.com/Automattic/jetpack/blob/945b9b68f8e00c8f89ec213cca848d8f7178f295/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L419

#### What I expected to happen

No menu items to be duplicated

#### What actually happened

Menu items were duplicated

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screenshot 2021-03-10 at 10 47 23](https://user-images.githubusercontent.com/8639742/110617799-00947300-818e-11eb-9fb5-b9ddd87dbcd1.png)

**Comment by getdave** [comment]
✅ Confirmed in my testing that this will be addressed in https://github.com/Automattic/jetpack/pull/19114
