### ISSUE TITLE
"Select Frame" button is broken when editing thumbnail for videos in Calypso media library

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#50958]
### Steps to reproduce the behavior

1. Go to the media library in Calypso
2. Check an existing VideoPress video (or upload a new one, if needed)
3. Click the video to select it, then click the "edit" button
4. Click "edit thumbnail"
5. Observe the "select frame" button is greyed out

#### What I expected to happen

To be able to pause the video on the frame I want - or somehow otherwise select a frame - then click "select frame"

#### What actually happened

The "select frame" button remains greyed out and does not become clickable when you pause the video

### Context

User report in 3809647-zen, replicated on test sites

#### Browser / OS version

Chrome, Mac OS

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High, impacts all sites on the Premium plan and up

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="389" alt="Screen Shot 2021-03-10 at 13 28 00" src="https://user-images.githubusercontent.com/17372274/110678622-80c5d300-81a4-11eb-9bc0-6c9622d564cd.png">

**Comment by hngdny** [comment]
Also affected here: 26804723-hc

**Comment by JenSwish** [comment]
3824138-zen

**Comment by carladoria** [comment]
also reported on [3819741-zen](3819741-zd-woothemes)

**Comment by alshakero** [comment]
I tried reproducing this on Atomic and simple sites in Chrome and FF but to no avail. I asked here (p1616538590273200/1615399513.417100-slack-C03TY6J1A) for more details.

**Comment by alshakero** [comment]
It seems @creativecoder couldn't reproduce either (thanks for testing Grant!). We both tested on the sites in the ticket. I also tested on every site in every ticked that mentioned this issue.

I think this issue is closable, WDYT @lakellie?

**Comment by lakellie** [comment]
Just following up here as I was AFK last week. Can confirm the issue seems to have been resolved before it was investigated and the feature is now working on my test sites. Thanks for checking into it!
