### ISSUE TITLE
Site Editor: global styles are broken on Atomic sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#50953]
This issue might be related to a degree to https://github.com/Automattic/wp-calypso/issues/50358 which is about Global Styles not being persisted on Simple sites.

After testing the same thing on Atomic, I noticed that it's actually even more broken:

<img width="333" alt="Screenshot 2021-03-09 at 13 38 51" src="https://user-images.githubusercontent.com/1182160/110655820-af04dc00-81bf-11eb-8726-8878ee2847a1.png">

The theme preset colors are not loaded at all, and clicking on the offered ones doesn't change anything within the editing view (that part at least works on Simple sites).

**Comment by autumnfjeld** [comment]
Ganon Estimation Session:
This will likely be a part of estimation of https://github.com/orgs/Automattic/projects/147#card-56634511

**Comment by p-jackson** [comment]
I test this and things seem less broken now. Maybe this is just a recent changes in Gutenberg have improved this? #50358 isn't fixed yet so can't be that.

With tt1 theme:
- Change background colour in the site editor ☑️  
- Colour changes are reflected in the editor ☑️ 
- Changes saved without issue ☑️ 
- Changes reflected on front-end ☑️ 

With seedlet theme it's a little bit more broken:
- Change background colour in the site editor ☑️  
- Colour changes are reflected in the editor ☑️ 
- Changes saved without issue ☑️ 
- Changes reflected on front-end ❌

When I refresh the site editor page with the seedlet theme my changes appear correctly. Maybe just an issue with how styles are merging?

**Comment by p-jackson** [comment]
Found this code that was overriding the colours on the seedlet front end:

<img width="816" alt="Screenshot 2021-03-29 at 11 59 17 AM" src="https://user-images.githubusercontent.com/1500769/112771042-38ecea00-9086-11eb-922e-d151d982d3fa.png">

> Override Seedlet variables with values from experimental-theme.json.

Not sure what that's about, but appears to be a seedlet issue, not a Global Styles issue.

Are you still able to reproduce this issue on Atomic @vindl?

**Comment by vindl** [comment]
> Are you still able to reproduce this issue on Atomic @vindl?

I just tested this again and I can no longer reproduce the original issue! 🥳 

> Not sure what that's about, but appears to be a seedlet issue, not a Global Styles issue.

Let's cc @Automattic/theam. I think we can file an issue for it in https://github.com/Automattic/themes/ and close this one.

**Comment by p-jackson** [comment]
Reported the seedlet issue here Automattic/themes#3588
