### ISSUE TITLE
Force disable Nav Unification for `0` user ids

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#50957]
See D58464-code.

Currently, it is possible for the `$user_id` to be `0` in `show_unified_nav` on Dotcom Simple even after the check...

```php
	if ( ! $user_id ) {
		$user_id = get_current_user_id();
	}
```

We should force disable Nav Unification in this case as it is open to unintended activation.

See also p1615397375406600-slack-ajax and pMz3w-cJ1-p2

cc @jeherve

**Comment by cpapazoglou** [comment]
Working on a diff here D58539-code

**Comment by cpapazoglou** [comment]
Deployed r222623-wpcom
