### ISSUE TITLE
Update "Dashboard appearance" toggle description.

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#50964]
**What**
Modify the `Dashboard appearance` toggle description to something easier to understand. I propose:

> Show WP Admin pages if available.

**Why**
I believe the current description of this toggle is verbose, unclear, and difficult to comprehend.

> Show advanced dashboard pages.
Enabling this will replace your dashboard pages with more advanced wp-admin equivalents when possible. Learn more

It is not clear what's _advanced_ and how it compares to the existing navigation system.

**Comment by frontdevde** [comment]
Marking as low priority as the current copy seems adequate for now. CC'ing @sfougnier for a final call on whether we want to keep or update the copy.

**Comment by ghost** [comment]
Thanks for the ping @frontdevde !

**Context:** The copy was changed to remove any internal terminology that less savvy users may be unfamiliar with. We need some supporting information as to what this does for users who are less aware of what impact this will have. 

To make this setting more discoverable for users who may be on the lookout for `wp-admin`, we can change to:

>Show wp-admin pages if available
Replace your dashboard pages with more advanced wp-admin equivalents. Learn more

I'm not sure how much of a priority it is to update, there are likely more important issues. It may make more sense to test how the current copy performs and update accordingly. We shouldn't assume that all users are as aware as A8C employees.

**Comment by happychait** [comment]
Thanks for making this teeny change happen, @sfougnier and @sixhours.

**Comment by sixhours** [comment]
All thanks goes to @blackjackkent :D
