### ISSUE TITLE
Customizing Jetpack search broken; modal gets hidden

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#50979]
When customizing the Jetpack search, the modal doesn't stay open, making the experience feel very broken and overall hard.

1. Enable Jetpack search and click "customize" from settings:

    <img width="857" alt="image" src="https://user-images.githubusercontent.com/87168/110757986-ab6f6480-8254-11eb-9710-ae2809064616.png">

2. Land in the customizer, modal is not open:

    <img width="1756" alt="image" src="https://user-images.githubusercontent.com/87168/110758214-ec677900-8254-11eb-9033-777659d48f97.png">

    https://user-images.githubusercontent.com/87168/110758220-effb0000-8254-11eb-986c-03341bc2e11d.mov

3. Enabling light/dark mode will show the modal:

    <img width="1726" alt="Screenshot 2021-03-11 at 10 32 01" src="https://user-images.githubusercontent.com/87168/110758304-0ef99200-8255-11eb-80ec-d72577616675.png">

4. Changing other options will hide it, and I can get it to show again by switching light/dark mode:

    https://user-images.githubusercontent.com/87168/110758379-233d8f00-8255-11eb-8a46-7571907ddf10.mov

#### Test setup

- Tested in Firefox, a simple site.

- Tested using Blank Canvas theme, with header and footer disabled (as they are by default in this theme).
    <img width="235" alt="image" src="https://user-images.githubusercontent.com/87168/110758166-dce83000-8254-11eb-83da-21ff17d4970c.png">

- Tested also using Twenty Twenty-One theme, same results.

cc @gibrown @cathymcbride seems like a high prio bug?

**Comment by simison** [comment]
I just learned that I can ping @Automattic/jetpack-search on these :-D

**Comment by simison** [comment]
This seems like worth having an E2E test making sure it doesn't break silently?

**Comment by bluefuton** [comment]
> This seems like worth having an E2E test making sure it doesn't break silently?

Absolutely agree. We're in discussions about how best to E2E test Jetpack Search over at p6fDka-uh-p2#comment-1864.

**Comment by jsnmoon** [comment]
Just to be clear: This wasn't a regression, but a known defect. This has now been fixed in https://github.com/Automattic/jetpack/pull/19207.
