### ISSUE TITLE
Nav Unification: Unable to add a new site

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#50988]
### Steps to reproduce the behavior

1. Signup for a new account from https://wordpress.com/start
2. In Calypso sidebar, try to add a new site

#### What I expected to happen

I expected to see the option to add a new site in Calypso's sidebar

#### What actually happened

I'm not able to find the option when I have just a single site. However, if I have two sites, then I can see the option to add new site.

**With single site**

<img width="275" alt="Screenshot 2021-03-11 at 4 53 40 PM" src="https://user-images.githubusercontent.com/1269602/110791696-843a8680-8298-11eb-95dc-8e69ecd8a650.png">

**With two sites**

<img width="270" alt="Screenshot 2021-03-11 at 4 54 09 PM" src="https://user-images.githubusercontent.com/1269602/110791721-8ef51b80-8298-11eb-9c0d-583c81804bfc.png">

**Comment by cpapazoglou** [comment]
It seems we have closed https://github.com/Automattic/wp-calypso/issues/47183 without adding the Calypso counterpart. 

We should create a component like the "Collapse menu" with icon `dashicons-plus-alt`. 
https://github.com/Automattic/wp-calypso/blob/cc976b39207147a01207d0b33fefab336c7383e1/client/my-sites/sidebar-unified/index.jsx#L144-L148

The menu added in WP Admin is here https://github.com/Automattic/jetpack/blob/3eaa2c3b05aed96556bf24d80326f9c334ac8c8d/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L104

The menu item should be conditionally be shown if `getCurrentUserSiteCount( state ) === 1`.

We shall not forget the separator too!
