### ISSUE TITLE
Editor: Media: Cross origin issues when editing images

### ISSUE THREAD

**Issue by robobot3000** [Automattic/wp-calypso#5099]
After retrieving images from *.files.wordpress.com or photon servers and rendering them into canvas, it's no longer possible to extract information from the canvas due to the Cross-Orign issues.

The solutions would be to get a proxy for the images in place, or add the Access-Control-Allow-Origin header to the image server responses.

**Comment by robobot3000** [comment]
CC @gwwar

**Comment by gwwar** [comment]
We should no longer be blocked, see pMz3w-5y5-p2

Let's close out this issue when we verify that this is no longer an issue

**Comment by gwwar** [comment]
I'm now seeing consistent results for `Access-Control-Allow-Origin` so this should be good 😄
