### ISSUE TITLE
Site icon not showing when bookmark site on iOS devices

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#50994]
### Steps to reproduce the behavior

1. Open Safari in iOS device
2. Visit WordPress.com site and bookmark
3. see that icon missing on left

#### What I expected to happen
Icon should appear for bookmark in the same way it appears when added to homescreen or when view site in browser tab

#### What actually happened
icon shows everywhere but bookmark
- per slack sounds like issue might be that bookmarks don't use apple-touch-icon?

### Context
- Happening on multiple WordPress.com sites (ex: offlattes.com, accoladecoaching.com.au, kidsnationmag.com) but doesn't appear to happen on self-hosted sites (ex: ihsstore.com)
- Icon appeared fine for HE test sites (kriskarkoski.com and everfieldfarm.com)

3810971-zd-woothemes
p1615453826023800-slack-C02FMH4G8

#### Browser / OS version
Safari / iOS (multiple devices)

#### Is this specific to the applied theme? Which one?
not theme specific
Happens with Varia based and 3p Herald Child theme at minimum

#### Does this happen on simple or atomic sites or both?
only reproduced with AT but might also happen on simple

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
inconsistent across sites, consistent within sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![2061D5FB-809D-475C-B5AA-843DA1ED07C7](https://user-images.githubusercontent.com/47717887/110812433-446fa100-8290-11eb-8d9f-a5af6402c861.jpeg)
![8B931D9B-B091-4BEF-A0D8-FC51ED5C1FB4](https://user-images.githubusercontent.com/47717887/110812489-54878080-8290-11eb-85a5-a93215ef6174.jpeg)

**Comment by jackiejade** [comment]
There is a workaround for this. If you add the images to the root level of the domain via SFTP it will make the bookmarks show. You'll want to have the user upload the images to their media library in .png and .ico format. The files need to be named:

apple-touch-icon.png
favicon.ico

**Comment by ghost** [comment]
33713820-hc the same user reported this again.

**Comment by jp-imagines** [comment]
Closing this in favor of this newer report: https://github.com/Automattic/wp-calypso/issues/54147

For anyone who stumbles across this: the workaround in https://github.com/Automattic/wp-calypso/issues/50994#issuecomment-799633448 still works, though only the `apple-touch-icon.png` file should be needed.
