### ISSUE TITLE
Podcasting: update instances of "subscribe" to "follow"

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#51016]
It looks like Apple and podcasting services are [updating instances of the word "subscribe" to "follow"](https://podnews.net/update/follow-not-subscribe) to reduce confusion of paid vs free podcasts. We should probably update any references in our code and documentation to match.

- [x] WPcom podcasting implementation - looks like only the podcast widget uses "subscribe" in the UI
- [x] [WPcom podcasting docs](https://wordpress.com/support/audio/podcasting/)
- [x] WPcom Anchor integration (@kwight can you help audit/triage this?)
- [ ] Our WPCourses podcasting course (@kathrynwp do you know who can help with this?)

Reported: pbOQVh-Wo-p2

**Comment by michaeldcain** [comment]
Updated the Podcasting docs.

**Comment by michaeldcain** [comment]
Widget changes in D58592-code

**Comment by kwight** [comment]
Done, our Anchor integration doesn't use this terminology at all. 👍

**Comment by kathrynwp** [comment]
Sorry I did not see this until now. I will bring this to the attention of the folks updating courses.
