### ISSUE TITLE
Google Map iframe not converting to shortcode

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#51014]
### Steps to reproduce the behavior

1. Follow the steps listed on our support doc [Embedding a Google Map](https://wordpress.com/support/google-maps/#embedding-a-google-map) to embed a Google Map in a Custom HTML Block on a simple site.
2. Publishing the post should convert the HTML to a shortcode
3. Instead, it becomes an empty Custom HTML block, and the code (and map) disappear

#### What I expected to happen

Google Map iframe embed code gets changed to a shortcode

#### What actually happened

code (and map) disappear

### Context

28350983-hc

#### Browser / OS version

Confirmed in Chrome, Mac OS

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Simple

#### Is there any console output or error text?

Not that I can see

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It affects a user site and my test site, so far. Doesn't affect purchases

#### Workaround

I manually created the shortcode for the user from the code they had, and had them add it into a shortcode block

**Comment by cathymcbride** [comment]
@bsanevans I'm not reproing this? Mine converted to the shortcode and displays correctly. Is there another constraint I'm missing?

**Comment by kaitohm** [comment]
Thanks for checking. And I missed the step I should have taken. I only tested with the user's code, and never went and got myself a new embed code.

I've gone back and collected a new link from Google Maps, and the process worked! Google Map gave me this code:

> <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d158858.47339664737!2d-0.2416803931736311!3d51.52855824261762!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8a00baf21de75%3A0x52963a5addd52a99!2sLondon%2C%20UK!5e0!3m2!1sen!2sjp!4v1616045538621!5m2!1sen!2sjp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

We were working with the following code the user had, which didn't work:

><iframe src=https://www.google.com/maps/d/u/0/embed?mid=1SUfMsXcjNSEeRBUrPQ8i0nDCATzWzvvt width="640" height="480"></iframe>

It seems the issue is specific to their code, or the format that code takes...?

**Comment by cathymcbride** [comment]
@bsanevans Sounds like it? I'm going to close this, but feel free to re-open if this comes up again.
