### ISSUE TITLE
Add note to User RC item that displays if the unified navigation has been activated

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#51022]
Please add a User RC item that displays if the unified navigation has been activated.

See p1615530263202500-slack-nav-unification

**Comment by cpapazoglou** [comment]
Patch on progress D58631-code

**Comment by cpapazoglou** [comment]
Deployed r222805-wpcom

**Comment by cpapazoglou** [comment]
@mrfoxtalbot FYI
![](https://cln.sh/HSf6Ne+)

It will return `false` for all a12s though
