### ISSUE TITLE
YouTube media pattern showing private video

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#51023]
In the editor, when adding Patterns -> Media -> Youtube, it shows this:

<img width="402" alt="Screenshot 2021-03-12 at 12 22 48" src="https://user-images.githubusercontent.com/87168/110927053-d24d9980-832d-11eb-8dac-0f0fdf83679e.png">

And in the editor:

<img width="382" alt="Screenshot 2021-03-12 at 12 22 19" src="https://user-images.githubusercontent.com/87168/110927065-d4aff380-832d-11eb-9541-f354dab180e9.png">

Could be country limitation (I'm VPNed via Sweden) or the [video](https://www.youtube.com/watch?v=k58xZ6osP3Y) just is private everywhere.

We'd give better impression with public video, maybe something about WordPress.com?

FYI @apeatling @ianstewart

**Comment by ianstewart** [comment]
We need to replace the video on this one. The source has changed. Drafting it and another pattern that uses it so it won't show up in the meantime.

I'll follow up with another issue for us to update the source and republish. :)
