### ISSUE TITLE
Color Studio v2.5.0 being released - Update dependencies

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#51029]
**Task Details**
<-- Details of the task to be added here. Try to be specific and reasonably sized. -->
Check and update any dependencies related to color schemes due to Color Studio v2.5.0 being released

**Related to**
pbjpUB-dZ-p2

**Comment by cpapazoglou** [comment]
@frontdevde Can you weigh in here and set a priority on this?

**Comment by frontdevde** [comment]
Good spot! Priority low, no color change here that affects us. Also I'd assume someone in Jetpack is going to update the dependency given that the Jetpack Green changed. I guess we can close this.

**Comment by cpapazoglou** [comment]
Great news! Thanks for checking this!
