### ISSUE TITLE
WPCOM Plugins: Show all features enabled for VIP

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5102]
On the new wpcom plugins page, we should detect if the site is VIP and change some of the labeling and show that they have all of the available upgrades.

Something like this but not as classy:
<img width="740" alt="vip-yolo" src="https://cloud.githubusercontent.com/assets/789137/14904919/f6b031cc-0d60-11e6-95b9-6af2e855e4e1.png">

@drw158 any thoughts?

**Comment by drw158** [comment]
We could just show them as active I think.

I have no idea if this is exists, but if VIP has a custom plugin page in WP Admin, then we could link to that for them in a notice, instead of the blue notice at the top right now.

**Comment by roundhill** [comment]
> I have no idea if this is exists, but if VIP uses have a custom plugin page in WP Admin, then we could link to that for them in a notice, instead of the blue notice at the top right now.

Yes, they have a special plugins page in wp-admin. Good idea.

**Comment by drw158** [comment]
VIP check 

https://github.com/Automattic/wp-calypso/pull/4806/commits/4a37b569404f4368ad5a78e91d8aba8b8a4fa207#diff-914bdeefa512de6f78c9b7988546d6e3R769
