### ISSUE TITLE
Nav Unification: Upgrades link and sublinks redirect to error page for a11ns

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#51041]
### Steps to reproduce the behavior

This only appears to happen when proxied and (I think) only with an a11n account.

1. Go to any page in the my-site section of calypso for a Simple site, eg: customer home (`/home/example.com`).
2. Click on "Upgrades" in the sidebar (or any of the sub-menus like "Plans").

#### What I expected to happen

To load the plans page.

#### What actually happened

I was redirected to wp-admin with an error.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/2036909/110971169-8815e980-8328-11eb-9e2a-c61221f11258.mov

**Comment by sixhours** [comment]
Possibly related, some of the submenu items under Upgrades are linked to the current page I'm viewing rather than their actual page:

* Premium Themes
* My Domains
* Manage Purchases
* Billing History

"Domains" goes to the correct screen at `domains/manage`

**Comment by michaeldcain** [comment]
I can reproduce this with both the "advanced mode" toggled on and off. It seems like most of the items @sixhours mentions, are new to the menu - previously this menu just had "plans", "manage purchases", and "domains".

**Comment by obenland** [comment]
Looks like it broke with r222623-wpcom

**Comment by obenland** [comment]
Possible fix in D58646-code

**Comment by obenland** [comment]
Should be fixed with r222644-wpcom. Would you mind double-checking and closing if so?

**Comment by sirbrillig** [comment]
Confirmed; it does appear to be fixed now! Thank you!
