### ISSUE TITLE
Nav Unification: Add VideoPress Share and Rating Options to Media Library

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#51040]
**What**
The Media Library accessed from the Media section of the new Nav Unification dashboard does not show the VideoPress Share and Rating options for the individual media items. I currently refer users to the Media Library on the WP Admin dashboard to see that information. Now that the WP Admin link is gone, it will be harder for users to get that information.

This is how it displays from the WP Admin Media Library:

![screenshot](https://d.pr/i/K6lJey+)
Image URL: https://d.pr/i/K6lJey

**Why**
We refer users to the WP Admin Media Library to disable sharing here: https://wordpress.com/support/videopress/#video-press-sharing-settings

**How**
Add the VideoPress Share and Rating Options to the sidebar of the media screen when you edit it from Calypso.

**Comment by khristiansnyder** [comment]
+1. Just had an upset user that needs both Calypso and WP-Admin to manage video settings as there are unique options in both sections.

**Comment by donalirl** [comment]
This also came up in #28644743-hc

**Comment by mikeicode** [comment]
Can only edit the Poster image from Calypso also. 29396173-hc

**Comment by tjcafferkey** [comment]
Could be helped by this proposal https://github.com/Automattic/wp-calypso/pull/52965
