### ISSUE TITLE
Welcome Tour: remove NUX code

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#51056]
The new Welcome Tour is being [shown to all users](https://github.com/Automattic/wp-calypso/pull/51055), so we can remove the NUX code.

This may also be a good time to consider any Welcome Tour  cleanup tickets, such as
https://github.com/orgs/Automattic/projects/147#card-56471257

**Comment by p-jackson** [comment]
@autumnfjeld should I close this as not relevant? We won't clean up the modal code until we have a version of the welcome guide that works on desktop and mobile. Feels like that will happen in the fullness of time without keeping this ticket around to track it.

**Comment by autumnfjeld** [comment]
@p-jackson  Sounds reasonable to me.  I'll close.
