### ISSUE TITLE
Site Editor: menu item URL for Atomic sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#51057]
Aside from [positioning problems](https://github.com/Automattic/wp-calypso/issues/50894) the Site Editor menu item on Atomic site is also not linking to Calypso section but to wp-admin instead. This should be changed in order to leverage our iframe integration.

<img width="738" alt="Screenshot 2021-03-15 at 07 42 18" src="https://user-images.githubusercontent.com/1182160/111113393-fee9f700-8561-11eb-8750-23676cd0a8d1.png">

**Comment by creativecoder** [comment]
This seems to be working as expected for me, I think we can close this.

The link to site editor depends on the "Dashboard appearance" setting in `/me/account`.

Be default, it points to `wordpress.com/site-editor/{site}`. But if "Show wp-admin pages if available" is set, then it goes to the wp-admin link instead. (Note it took a couple of refreshes for the setting change to take effect when I was testing.)

@vindl Can you confirm if this is now working as expected for you?

**Comment by vindl** [comment]
> Be default, it points to wordpress.com/site-editor/{site}. But if "Show wp-admin pages if available" is set, then it goes to the wp-admin link instead. (Note it took a couple of refreshes for the setting change to take effect when I was testing.)
> @vindl Can you confirm if this is now working as expected for you?

Thanks @creativecoder. I can confirm that this is no longer the case on my end and that the link points to `site-editor/{site}`. I'm pretty sure that I didn't have "Show wp-admin pages if available" setting on at that point (I didn't know it existed at the time). 😄
