### ISSUE TITLE
Marketing banner hides menu on mobile in Twenty Twenty-One when logged out

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#51060]
### Steps to reproduce the behavior

This is how it looks when we're logged in:

![image](https://user-images.githubusercontent.com/6737345/111127617-b25fe500-857c-11eb-939e-3394bce42f73.png)

This is how it looks when we're logged out:

![image](https://user-images.githubusercontent.com/6737345/111127651-bb50b680-857c-11eb-897b-c5f89da935be.png)

### Context

- Reported by a user in #3817684-zen

#### Is this specific to the applied theme? Which one?

- It's currently specific to Twenty Twenty-One

#### Does this happen on simple or atomic sites or both?

- Tested in Simple sites
 
#### Is there any console output or error text?
- No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

-

**Comment by cpapazoglou** [comment]
👋 @jeffikus Could the themes team pick up this and fix it directly in the theme like we did with the folloing themes?

`unsupported_templates = [ 'scrawl', 'seedlet', 'twentyfourteen', 'twentyseventeen', 'twentytwenty', 'boardwalk', 'gateway', 'dyad-2', 'cubic', 'coherent', 'rockfield', 'stratford', 'pique'`

**Comment by jordesign** [comment]
Just pinging here for an update - to see if this is something likely to be able to be worked on?

**Comment by jeffikus** [comment]
Will add this to our bug scrub which should be coming up within the next 2 weeks.

**Comment by KokkieH** [comment]
This should be fixed now via https://github.com/Automattic/themes/issues/3593
