### ISSUE TITLE
Purchases: Manage purchases says wrong expiration date for auto-renewals with card that expires before renewal

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#5107]
As far as I understand, we show the wrong date in manage/purchases when the following conditions are met:
* Purchase is set to auto-renew
* Card expires before renewal date

We do show the correct text (Expires on) and the correct banner, this card expires on 3/17 and the purchase on 4/28/17:
![screen shot 2016-04-28 at 7 10 55 pm](https://cloud.githubusercontent.com/assets/8921630/14906844/1d63840e-0d75-11e6-99f1-f08f97c6a978.png)

So everything is right, except the date, which is still using auto-renew logic (a month prior to expiration).

**Comment by fabianapsimoes** [comment]
See p2MSmN-4QD-p2.
