### ISSUE TITLE
Editor: Pattern selector not working properly on mobile

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#51085]
### Steps to reproduce the behavior

1. Add a post or a page using a mobile device (I used an iPhone).
2. Click on the + button in the top left corner of the editor. In the overlay switch to the Patterns tab.
3. Click on the list and select a category.
4. I'm not able to preview patterns in the selected category. The whole overlay closes and I'm back in the editor.

Here's a quick video: https://cloudup.com/cxxAbw5q06w

#### What I expected to happen
I expected to be able the select a pattern category and browse patterns.

#### What actually happened
The overlay closes.

#### Browser / OS version
iOS 14.4.1 / Safari

**Comment by cathymcbride** [comment]
FYI @apeatling

**Comment by apeatling** [comment]
Possible duplicate https://github.com/WordPress/gutenberg/issues/29243

**Comment by apeatling** [comment]
Duplicate of WordPress/gutenberg#29243
