### ISSUE TITLE
Editor: respect WP_POST_REVISIONS and AUTOSAVE_INTERVAL

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#511]
WordPress offers 2 constants allowing site owners to control the number of revisions saved for each one of their posts, as well as how often autosave happens when writing a new post:
- `WP_POST_REVISIONS`
- `AUTOSAVE_INTERVAL`

It would be nice if the Editor respected these settings when writing on a Jetpack site.

**Comment by kraftbj** [comment]
Added notes here: I can appreciate saving revisions pretty often to prevent data loss if Calypso can't communicate back up. When writing a relatively short post (under 400 words), Calypso saved 32 revisions, about a minute apart each.

Besides the case of an issue while I was actively writing, the majority of these revisions aren't helpful in the future.

4.4 added a `wp_post_revision_title_expanded` that JP could hook into to give a special description to Calypso autosaves, then perhaps JP could clean those up—or some of them—based on some trigger?

**Comment by mtias** [comment]
Autosaves could avoid generating a revision each time as well (needs API improvements) and just offer the latest one in a given session as the revision or when you explicitly click save.

**Comment by lancewillett** [comment]
The Jetpack revisions improvements should be the same for WP.com sites imo.

**Comment by designsimply** [comment]
Noting that revisions likely won't be affected by Gutenberg and this is still a valid issue.

**Comment by kwight** [comment]
Closing since the Calypso editor has been deprecated, and users now only use a WP Admin version of either the Gutenberg or Classic editor.

See: pb5gDS-P5-p2
