### ISSUE TITLE
Project Types sub menu item opens Posts sub menu

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#51100]
### Steps to reproduce the behavior

1. Enable the "Portfolio" menu item by going to Settings > General > Writing and toggling this on.
2. Select Projects > Project Types.
3. Observe the "Posts" sub-menu being displayed as active now.
4. Refreshing this page corrects the issue.

#### What I expected to happen

I expected the Portfolio menu items to be displayed as selected and its sub menu items visible.

#### What actually happened

Posts menu item was displayed as active and its sub menus visible.

#### Does this happen on simple or atomic sites or both?

* Both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screenshot 2021-03-16 at 13 13 54](https://user-images.githubusercontent.com/8639742/111315109-f70d7e00-8659-11eb-88a2-487c7806d397.png)

**Comment by obenland** [comment]
Duplicate of #49309.
