### ISSUE TITLE
Domains: Hide (or allow to hide) `Complete domain setup` warning for domains mapped via Cloudflare

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#51109]
**What**
Currently, if a domain is mapped via Cloudflare, there is a warning displayed reading `Complete domain setup`.

![](https://d.pr/i/pSyzw6+)
_Link: https://d.pr/i/pSyzw6_

An additional warning `Complete setup` is displayed in `https://wordpress.com/domains/manage/DOMAIN` but it's less prominent.

![](https://d.pr/i/4vTLnK+)
_Link: https://d.pr/i/4vTLnK_

**Why**
It is confusing and annoying for users who correctly pointed to WordPress.com but via Cloudflare proxy. 

**How**
- Hide the warning based on the condition that Name Servers are Cloudflare's ones or some similar rule. 
- Otherwise, allow the warning to be dismissed similarly to how it can be done for some cards in My Home.

![](https://d.pr/i/0JHl9N+)
_Link: https://d.pr/i/0JHl9N_

**Additional context**
One user reported this to us 28449292-hc

**Comment by klimeryk** [comment]
Already working on it - patch D58467-code should fix it (when it's merged) so that domains mapped through Cloudflare will be recognized simply as properly mapped 🎉

**Comment by klimeryk** [comment]
Patch has been merged 🎉 Please let me know if you notice it not working as expected anywhere 🙇 But marking as resolved for now.
