### ISSUE TITLE
Upsell Nudge: Domains upsell dismiss icon has no contrast

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#51118]
### Steps to reproduce the behavior

I'm not 100% how to reproduce this upsell, but it showed up on a site that already has a mapped domain while I was testing something else:

<img width="312" alt="Screen Shot 2021-03-16 at 5 15 22 PM" src="https://user-images.githubusercontent.com/2124984/111381337-f259c180-867b-11eb-98bf-d20dec013a5d.png">

There's a blank space next to the main CTA that's intended for a dismiss icon (X). It's white on white, so it doesn't show. This probably fell through the cracks when I updated the upsell nudge design for nav unification in #48379

#### What I expected to happen

You should be able to see the dismiss icon and dismiss the upsell nudge.

#### What actually happened

The dismiss icon is white on a white background.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Happening on more than one site, but low impact, since dismissing the upsell isn't critical.

**Comment by kwight** [comment]
I didn't find a quick way to replicate these upsells, neither by upgrading or having a .blog domain already – any further tips to replicate?

**Comment by sixhours** [comment]
> I didn't find a quick way to replicate these upsells, neither by upgrading or having a .blog domain already – any further tips to replicate?

It's possible you've already seen and dismissed the notice; cleaning out your dismiss preferences might re-enable the nudge.

If it doesn't, the logic around when to display this notice and which version to display is pretty epic: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/current-site/notice.jsx#L144

I think it has to do with your current domain name being available for a specific TLD that's also on sale (eg. my test domain is calobeetesting.blog, which is also available as calobeetesting.store, and the .store TLD is on sale).

...given that, it's probably easier to just recreate an `UpsellNudge` with the same props in that area of the sidebar, manually. 🙃
