### ISSUE TITLE
Checklist: Checklist disappears when going Atomic, "Coming Soon" pill in site card briefly disappears

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51119]
### Steps to reproduce the behavior

1. Create a new site on WP.com
2. Upload a plugin 
3. Bug: Checklist disappears when going Atomic, "Coming Soon" pill in site card briefly disappears

#### What I expected to happen

- The checklist would remain present as site is unlaunched.
- Coming Soon pill in site title card would not disappear and reappear

**Comment by jordesign** [comment]
> The checklist would remain present as site is unlaunched. 

@autumnfjeld Will this be addressed with the current working being done to sync checklist?

> Coming Soon pill in site title card would not disappear and reappear

I've been able to recreate this by installing a plugin on a site that was 'Coming Soon'. The badge in the sidebar didn't return until I refreshed the page.


https://user-images.githubusercontent.com/1842363/119609805-8645c780-be3b-11eb-8769-d7a57a56a7a7.mp4

**Comment by autumnfjeld** [comment]
Sorry about the delay in answering @jordesign .  I will see if the recent atomic on the site checklist will impact this.

**Comment by deBhal** [comment]
The Checklist disappearing is expected until https://github.com/Automattic/wp-calypso/issues/50523 / D63125-code is deployed.

**Comment by autumnfjeld** [comment]
> Coming Soon pill in site title card would not disappear and reappear

This is likely not easy to fix, and probably low priority because it impacts users who have many sites (10s of sites).

**Comment by roo2** [comment]
I believe that the coming soon disappearing and reappearing is due to the value of it being updated by a call to `/sites` that takes quite some time to complete, because it gets data for ALL sites of that user. This is especially a problem for a12s who tend to have lots of sites. 

There is a capability to set a default to use before the call to `/sites` completes, so we could look into that for new atomic sites.

**Comment by jordesign** [comment]
If this is something mostly effecting A12s this may be a non-issue. I can't imagine we have too many end users with 10s of sites.

**Comment by autumnfjeld** [comment]
Yes, @jordesign , we believe the "Coming soon" pill issue likely impacts a12s, but not so much users--which your comment supports.  Thanks for commenting and providing that insight.

**Comment by roo2** [comment]
I went through and tested this, it looks to me like there is be a bug with the coming soon label not being shown when the wp-admin calypso navigation is shown, and that the user is being directed to a wp-admin interface after installing the plugin.

Sorry I thought it was just the timing issue with the `/sites` call, it looks like there is a wider problem with coming soon badge in the navigation on wp-admin of atomic sites

**Comment by roo2** [comment]
It looks like after installing the plugin which triggers the Atomic Transfer process, the page still stays on the pre-transfer site.
I see that 
`this.props.site.is_coming_soon` used on https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/site/index.jsx#L125
returns false after the Atomic transfer is complete.

A call is being made to https://public-api.wordpress.com/rest/v1.2/me/sites/SITE_ID which unexpectedly has `is_coming_soon` set to false post-atomic-transfer 

the call to `https://public-api.wordpress.com/rest/v1.2/sites` (without SITE_ID) which is used on page load still returns `is_coming_soon=true`. 

I believe this difference between the value of `is_coming_soon` for `/sites/SITE_ID` vs `/me/sites` all the sites is the root of this bug.

**Comment by roo2** [comment]
Raised D63769-code to fix the call to the https://public-api.wordpress.com/rest/v1.2/sites API

**Comment by roo2** [comment]
closed with  D63769-code
