### ISSUE TITLE
Sites created as Atomic with async TLDs (.ca, .blog) are non-functional after purchase

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#51121]
When purchasing a new eCommerce plan and a custom `.ca` domain (this should apply to other TLDs that are known to be slow to set up, like .blog), Jetpack is broken immediately after checkout because the domain doesn't have any public DNS yet. This results in a completely broken Calypso state with just a cryptic error message. 

This seems like a less than optimal first experience for new eCommerce plan customers.

### Steps to reproduce the behavior

1. Purchase a new eCommerce plan
2. Register a custom `.ca` domain
3. Checkout

#### What I expected to happen

To be able to see and edit the site immediately after purchase.

#### What actually happened

I see an error message asking me to check my Jetpack connection. At this point I'm new to WordPress.com and don't have any idea what Jetpack even is, or why I might get this message, which makes it even more confusing.

<img width="1013" alt="brokenconnection" src="https://user-images.githubusercontent.com/42279181/111389677-fa633280-8676-11eb-8bff-ee97b264022e.png">

This happens because eCommerce sites are provisioned Atomic rather than simple, and rely on the connection. The Jetpack connection breaks because the primary domain isn't functioning. Setting the wpcomstaging domain as primary again resolves the issue while we wait for the public DNS to propagate, but because there isn't a way for the user to even see that with the connection broken the only way forward is for them to reach out to support.

Related to https://github.com/Automattic/wp-calypso/issues/48746

Also discussed several years ago here: p2MSmN-6fV-p2#comment-29754

#### Does this happen on simple or atomic sites or both?

Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Impacts any new site provisioned as Atomic that registers a `.ca` domain.

**Comment by simison** [comment]
@daledupreez hi! Could your team triage this one? I'm marking it "high" meanwhile because it seems pretty bad. Thx!

**Comment by simison** [comment]
> Impacts any new site provisioned as Atomic that registers a .ca domain.

Wouldn't this impact any TLD, not just `.ca`?

**Comment by klimeryk** [comment]
It's not a domains issue exactly - it seems some Jetpack (and/or Atomic?) provisioning process assumes the domain will be fully provisioned ASAP, but some TLDs (.ca apparently being one of them) can take a few minutes to be provisioned (and DNS to start resolving). It's nothing we can improve on our side - it's a registry limitation. The process on Jetpack's side (or Atomic, I'm really not an expert here) needs to take that into account. Happy to help with figuring out which TLDs are affected - we have a "TLD spec" on the backend where you programmatically can then check if the given domain is expected to have this delay. But we need someone from Jetpack/Atomic to figure out what process needs to be improved.

**Comment by klimeryk** [comment]
> @daledupreez hi! Could your team triage this one? I'm marking it "high" meanwhile because it seems pretty bad. Thx!

Side-note: we have a `@Automattic/cobalt` ping for such cases :) And we get automatic pings also for all issues marked with `Domains` label - no need to ping just the team lead, unless no one replied in a reasonable timeline and things really need escalation 🙇‍♂️ (just trying to make sure Dale as the team lead is not overloaded with pings)

**Comment by simison** [comment]
> pings

Yep! Thanks! I know some teams prefer pings to go via lead for less noise, and some via big-group ping. I'll make a note to ping you either via label or team handle going forward. 😃 

> It's not a domains issue exactly - it seems some Jetpack (and/or Atomic?) provisioning process  [...]

Thanks for elaborating on the issue! It does still sound pretty heavily domains issues to me but I understand it can be framed differently as well. 😆 

If I understood it right, this kind of process would be good:
- On provisioning eCommerce plan & server, check from that API you mention if TLD is expected to have a delay (or some other kind of generic check?)
- Don't set the primary address as the new domain, and keep it as `*.wpcomstaging.com` instead
- Potentially communicate this to customer somehow nicely, that they should expect a slight delay.
- Kick off a background job that will swap the primary domain to a new domain once name-servers resolve

The outcome should be that Jetpack never disconnects in the whole process.

How does that sound like?

Would it make sense to do this for all TLDs, not just for known-to-be-problematic ones?

**Comment by simison** [comment]
@klimeryk do you happen to have a list of problematic TLDs? That might help in prioritizing and understanding how wide impact this currently has.

**Comment by simison** [comment]
@olaolusoga @ianstewart thoughts on design needs here? See [my comment for proposed solution](https://github.com/Automattic/wp-calypso/issues/51121#issuecomment-805822599). When dev will look into this, they might find some other solutions tho.

**Comment by ianstewart** [comment]
> Don't set the primary address as the new domain, and keep it as *.wpcomstaging.com instead
> Potentially communicate this to customer somehow nicely, that they should expect a slight delay.

I suspect this requires looking into the various warnings or notices we throw now and that this may be more like a missing case. (There's quite a few cases now.)

There's some design work happening now related to some other atomic projects that may touch on this. And we should have a design for an ideal state, ideally. :)

**Comment by simison** [comment]
Honestly, anything is an improvement that just isn't being completely broken after the eCommerce plan purchase, so even just not communicating about it and letting the primary domain switch with some delay. Note that I don't know if we're talking about 5min, 1h, or 1d kind of delay.

**Comment by daledupreez** [comment]
For context, delays of a few minutes are not uncommon for a number of gTLDs, which includes .blog -- we've seen slowness from the CentralNic registry services in general. However, there are a handful of TLDs, mostly ccTLDs, where delays up to an hour are possible.
We dug into the messaging for this in #40516, but decided not to get overly specific.

**Comment by kwight** [comment]
Reducing to `normal` priority since this has been investigated, and has limited possible actions on our side (and those actions have been considered).

**Comment by klimeryk** [comment]
> @klimeryk do you happen to have a list of problematic TLDs? That might help in prioritizing and understanding how wide impact this currently has.

Sorry for missing this ping! 🙇 

Like Dale said above, there's no strict list. We have a place on the backend where we can store in a robust way per TLD (and/or per registrar/registry) details like this. But it'd probably make sense to treat all domain registrations as async processes - there could be a sudden outage or just a performance dip on the registry side and we'll have the same problem for usually "good" TLDs.

As for how to implement this, I really have no idea how/what processes Jetpack and/or Atomic kick off here and how to change them. That's why I mentioned it's not a domains issue exactly - but maybe I should have said that it's not something that someone on Cobalt (now Nomado) would be the best to help with 🙇‍♂️

**Comment by davoraltman** [comment]
Just noting here that this is still an issue. While creating a new eCommerce site, I registered a .blog domain during the site-creation process, and it resulted in a broken experience until the domain started working.

**Comment by kriskorn** [comment]
This has been fixed in D71776-code. 
More information can be found in p7DVsv-dpb-p2 and p7DVsv-dpb-p2#comment-38958.
