### ISSUE TITLE
Atomic: Elementor plugin breaks page layout in Theme Builder section

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#51136]
After installing Elementor on Atomic and visiting Elementor's `Templates > Theme Builder` section, the page layout is broken.

### Steps to reproduce the behavior

1. Go to 'Templates > Saved Templates'
2. Click on 'Templates > Theme Builder'
3. The page layout is broken and the user has to refresh the page

#### Browser / OS version
Chrome Version 89.0.4389.82 / MacOS Catalina

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Impacts Atomic sites that has the latest version of Elementor plugin enabled.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screenshot 2021-03-17 at 14 27 46](https://user-images.githubusercontent.com/995955/111467329-fd205f00-872c-11eb-8eb1-f1bc015ac49c.png)

**Comment by BogdanUngureanu** [comment]
The issue was also reproduced with the new nav unification disabled.

**Comment by nagpai** [comment]
Maybe related to
https://github.com/Automattic/page-optimize/issues/59

**Comment by dsas** [comment]
Disabling optimize fixes the problem. I'll close this issue.
