### ISSUE TITLE
Navigation Unification: Dashboard Items

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#51148]
What
There's a lack of details from the requester but, there has been a request to get the old wp-admin dashboard back. Since this doesn't appear possible with the nav uni rollout, would it be possible to add old 'wp-admin" dashboard items like "At a Glance", "Activity", and "WordPress News and Events" to My Home? 

Why
With the nav uni rollout, this makes it difficult for the requester to navigate like they're used to. The requester heavily relied upon the old wp-admin dashboard. Alternative options/settings were provided.  Enabling the "dashboard appearance" setting doesn't mimick the old wp-admin dashboard like expected. 

How
Screenshot of wp-admin: https://d.pr/i/sEb5q8
Screenshot of My Home: https://d.pr/i/LHMRei

**Additional context**
Reported: 3830926zen

**Comment by devNigel** [comment]
Another report: 28482158-hc

**Comment by mmtr** [comment]
The link to the WP Admin dashboard was intentionally removed as requested in https://github.com/Automattic/wp-calypso/issues/50945#issuecomment-796866194.

Users who want to still access the WP Admin dashboard can do it by visiting the `/wp-admin` URL directly.
