### ISSUE TITLE
Site Editor: make option for adding Pexel images more prominent

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#51145]
It's not very easy to discover the free images option in current media library if you don't know where to look. One piece of feedback we received in testing was that this should be surfaced in alongside Upload and Media Library buttons.

https://user-images.githubusercontent.com/1182160/111512753-5fd72200-8750-11eb-9e5d-c072e88b3797.mov

In the video you can also notice a weird issue with image resizing controls.

**Comment by Addison-Stavlo** [comment]
this seems more prominent nowadays 

![Screenshot 2023-03-22 at 12 41 07 PM](https://user-images.githubusercontent.com/28742426/226976094-8b7ad985-0f1d-41f0-8cbf-ebaa8d0025a1.png)
