### ISSUE TITLE
Video block not removable if video is deleted from media first

### ISSUE THREAD

**Issue by noteeth** [Automattic/wp-calypso#51151]
### Steps to reproduce the behavior

1. add video to media library
2. add video block to a page/post and select video from media
3. delete video from media library
4. return to editor and you will see "generating preview" in place of the video block, with no way to delete the block.

#### What I expected to happen
Hoping there's a way to remove the block, even if the video is no longer on the site.

#### What actually happened
The video block breaks and is not removable (except via code editor, which we don't recommend to users)

#### Browser / OS version
I tested this on Big Sure 11.2.2 and Chrome 89

#### Does this happen on simple or atomic sites or both?
tested and applies to both
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
affects all WordPress.com sites

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/16570939/111532560-04426f80-8723-11eb-8c61-9e082f038c6f.mov

**Comment by noteeth** [comment]
Just tested this on https://jurassic.ninja/ and it appears to be a WordPress.com specific issue.  I can remove the block once the media has been removed on the jurassic.ninja site.


<img width="1337" alt="Screen Shot 2021-03-17 at 1 54 49 PM" src="https://user-images.githubusercontent.com/16570939/111537368-96994200-8728-11eb-8689-4ac554a91467.png">

**Comment by andrewserong** [comment]
Just a quick guess, but it sounds like the block is stuck on either the `isFetchingMedia` or `isFetchingPreview` state around this line in the VideoPress block: https://github.com/Automattic/jetpack/blob/41fe374f32d0fa35bb66b4ca492e0b337ee7c6cd/projects/plugins/jetpack/extensions/blocks/videopress/edit.js#L417

I wonder if we need something like an `isMediaNotAvailable` failure state added somewhere around [this line](https://github.com/Automattic/jetpack/blob/41fe374f32d0fa35bb66b4ca492e0b337ee7c6cd/projects/plugins/jetpack/extensions/blocks/videopress/edit.js#L505), possibly by checking if `getEmbedPreview` has returned `false` (failed to get preview).

**Comment by katiebethbrown** [comment]
Another report: 28501964-hc
