### ISSUE TITLE
Editor: button to exit editor hidden on mobile screens

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#51162]
Help, I can't escape the editor!

### Steps to reproduce the behavior

1. Open the editor on a mobile sized screen

#### What I expected to happen

I can go back to the site dashboard using the "W" button at the top left.

#### What actually happened

The "W" button is hidden, and there's no visible way to navigate back to the dashboard (other than using the browser back button)

#### Browser / OS version

Firefox / macOS

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

No

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="373" alt="Screen Shot 2021-03-17 at 21 17 58" src="https://user-images.githubusercontent.com/1699996/111564560-eb0fe200-8767-11eb-8723-945d3b49f83c.png">

### Context

Related to https://github.com/Automattic/wp-calypso/pull/40361

**Comment by poligilad-auto** [comment]
Hey @razvanpapadopol. I reached out to @onuro to get his opinion as he is part of the FSE pod and this is related to that.
He thinks we should add a W button to exit the editor, like in the desktop version. I agree this is a good solution and is consistent between platforms.

As to how it looks like. I think we have 2 options:
1. A slimmer version for mobile as we have less space in the top nav bar.
2. A version that is very similar to desktop.

WDYT?

![image](https://user-images.githubusercontent.com/83961704/130454673-3717dc2a-b7e5-4921-ba33-11b986120790.png)

**Comment by razvanpapadopol** [comment]
> As to how it looks like. I think we have 2 options:
> 
> 1. A slimmer version for mobile as we have less space in the top nav bar.
> 2. A version that is very similar to desktop.

The first one looks quite well balanced but we might need more horizontal padding for accessibility reasons. Anyway, I'll check how the implementation looks like while also considering the various header combinations as discussed in https://github.com/Automattic/wp-calypso/issues/50758

**Comment by razvanpapadopol** [comment]
## Medium mobile screens

The slimmer version would probably work for most of the mobile resolutions. I've tested here on a 375px wide viewport (iPhone 6/7/8) and EN locale.

https://user-images.githubusercontent.com/14192054/131691829-cb7f9bb7-0fff-43ab-889d-a4ddc0f3a626.mov

I've also tried a version with a bit more margin on the right as mentioned in https://github.com/Automattic/wp-calypso/pull/40361#issuecomment-617685289
> The left padding was intentionally designed to be 24px because it's a blue button next to a dark square

* no margin
<img width="300" alt="Screenshot 2021-09-01 at 17 38 26" src="https://user-images.githubusercontent.com/14192054/131692224-fda564b9-0636-4d95-b3f8-1ca12aa0ab10.png">

* 8px margin-right on the W button
<img width="300" alt="Screenshot 2021-09-01 at 17 39 16" src="https://user-images.githubusercontent.com/14192054/131692217-21069e08-9f96-4992-800f-cb1402c11634.png">

An alternative (to avoid the extra margin on the right) would be to remove the dark grey background on mobile.

<img width="300" alt="Screenshot 2021-09-01 at 16 55 27" src="https://user-images.githubusercontent.com/14192054/131692680-5b9b838f-07af-40fc-b5a5-bb44e01206f2.png">

## Small mobile screens
On 320px width (iPhone 5, SE), the space isn't enough to fit all the buttons and still preserve the accessibility ([minimum 44px target size](https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/#what-the-mobile-platform-guidelines-say))

* no button (live right now)
<img width="300" alt="Screenshot 2021-09-01 at 16 44 35" src="https://user-images.githubusercontent.com/14192054/131692968-f9bf11fb-200c-49c1-b004-d072edda8d6b.png">

* with W simple button, after removing some of the padding fromm all buttons
<img width="300" alt="Screenshot 2021-09-01 at 16 43 15" src="https://user-images.githubusercontent.com/14192054/131692971-4e901967-fb64-4712-b33e-1a239b29f520.png">

* the solution on WordPress.org (3rd top bar)
<img width="300" alt="Screenshot 2021-09-01 at 16 48 58" src="https://user-images.githubusercontent.com/14192054/131692959-527aecb2-79bb-45d5-bd03-9c9e22a76a79.png">

**Comment by creativecoder** [comment]
Don't forget that the "W" icon is replaced by the site icon as the button, if a site icon is set.

**Comment by razvanpapadopol** [comment]
> Don't forget that the "W" icon is replaced by the site icon as the button, if a site icon is set.

Thanks for noting this, @creativecoder!

Here is the narrow version with extra margin on the right and the version without the black background.

<img width="350" alt="Screenshot 2021-09-02 at 11 43 49" src="https://user-images.githubusercontent.com/14192054/131814285-1b9ae54c-1868-4f29-8c66-f4092cb229da.png">

<img width="350" alt="Screenshot 2021-09-02 at 11 44 12" src="https://user-images.githubusercontent.com/14192054/131814388-c23e7d31-e002-4f90-9d68-4c71712f186c.png">

On the other hand, as tested on a WordPress.org installation, since there's no "W" icon by default, the site icon isn't displayed on mobile.

**Comment by creativecoder** [comment]
> On the other hand, as tested on a WordPress.org installation, since there's no "W" icon by default, the site icon isn't displayed on mobile.

That's true for the post editor, though the site editor (enabled with an FSE theme) does show the "W" or site icon on mobile

<img width="414" alt="image" src="https://user-images.githubusercontent.com/1699996/131865836-b8f040b8-2046-4ad2-87a4-e1caa3732e0b.png">

**Comment by simison** [comment]
Appending the button in the header might still cause trouble with plugin icons visible there?

How would our version of the masterbar above the editor header look like?

**Comment by poligilad-auto** [comment]
> 
> That's true for the post editor, though the site editor (enabled with an FSE theme) does show the "W" or site icon on mobile
> 
> <img alt="image" width="414" src="https://user-images.githubusercontent.com/1699996/131865836-b8f040b8-2046-4ad2-87a4-e1caa3732e0b.png">

How about we do the same in our case @razvanpapadopol ? Show the "W" or site icon just like this. I also think it could work well adding our top navigation as well.

**Comment by worldomonation** [comment]
This is causing issues when migrating one of the e2e specs to Playwright - [#56087](https://github.com/Automattic/wp-calypso/pull/56087).

**Comment by simison** [comment]
Looks like that has fallen through a bit — let's get the regular mobile masterbar visible on editor at all times just like on .org. That's lower effort, and gets us onto same page with core's UI. Aligning site- and page- editor IA should be done in Gutenberg directly instead.

@creativecoder do you know if there's an issue for adding site icon at Gutenberg just like it's on site-editor?

**Comment by enejb** [comment]
This should now be fixed with https://github.com/Automattic/wp-calypso/pull/57234
