### ISSUE TITLE
Nav Unification: While "Show advanced dashboard pages" is on, display user-facing way to access Calypso settings

### ISSUE THREAD

**Issue by CompChris** [Automattic/wp-calypso#51189]
For users that opt to use the WP-Admin pages with Nav Unification, there isn't an easy user-side method (without a direct URL) to access the Calypso Site "Settings" page. This page includes features like changing privacy settings/coming soon, deleting a site, changing how SSO works, access to CDN settings, Podcasting setup, discussion settings, etc.

What
Link to Calypso "Settings" page at https://wordpress.com/settings/general/ when "Show advanced dashboard pages" is on. 

Why
Many of the settings/features that are available from the General Settings through Calypso, aren't available through the WP-Admin equivalent.  

How
(Optional) If applicable, add screenshots, animations, or videos to help illustrate how the feature could be done.

**Additional context**

This page is shown when a user tries to access their admin settings, if using WP-Admin pages:

![Markup on 2021-03-18 at 11:36:41](https://user-images.githubusercontent.com/6847710/111653444-4da3c500-87de-11eb-978b-02d65158f6b5.png)

Some way to access this should still be available:

![Markup on 2021-03-18 at 11:38:31](https://user-images.githubusercontent.com/6847710/111653753-85127180-87de-11eb-9b7b-1b2e7c041a66.png)

**Comment by goblinartificer** [comment]
+1 to this - in particular, access to https://wordpress.com/settings/delete-site is no longer available, and that's pretty confusing!

**Comment by darnelldibbles-zz** [comment]
A user brought this up in https://wordpress.com/forums/topic/unified-navigation-delete-a-site/ and was totally confused.

**Comment by JoshuaGoode** [comment]
Highlighting that this can prevent users from launching their site or setting it to Coming Soon, Public, or Private. 

> This page includes features like changing privacy settings/coming soon,

**Comment by jordesign** [comment]
Another case in #28694037-hc.

This seems like potentially a bit of a blocker - if it is stopping users from being able to access their Site Privacy and/or launch their site without HE assistance?

**Comment by mmtr** [comment]
Internal discussion: p9Jlb4-2qr-p2

**Comment by donalirl** [comment]
This came up in #28904189-hc where we couldn't delete a site while the 'Show Advanced Dashboard Pages' toggle was on.

**Comment by jerrysarcastic** [comment]
Also reported (with some extra hate mail for the unification change) here:  https://wordpress.com/forums/topic/closing-a-free-blog-account/

For now gave workaround to turn off Advanced Pages setting temporarily

**Comment by jamiepalatnik** [comment]
Another report in 28267458-hc. Shared direct link to podcast settings and explained how to turn off Advanced dashboard pages as a workaround.

**Comment by davipontesblog** [comment]
@kwight  I suggest we treat this as a bug instead of a feature request. Some of our key user interface flows are blocked because of this:
- Deleting a site.
- Launching a site. (Just had this issue with an atomic user here: 29258970-hc)

Without HE intervention this is a blocker to launch sites for example, since My Home only mentions the site is not launched, but does not offer a way to "Launch" them.

**Comment by kwight** [comment]
Yep, I'd agree. The "turn it off, make changes, then turn it back on" workaround makes it not super-high priority, but is a terrible experience and HE drain nonetheless. So ifI understand correctly, the real fix is to port those missing Calypso tools to WP Admin? cc/ @tjcafferkey

**Comment by davipontesblog** [comment]
> So ifI understand correctly, the real fix is to port those missing Calypso tools to WP Admin? 

I'd say either that, or to trim out stuff that's already in the WP Admin Settings page from the Calypso one, repurposing it to show hosting-only options such as the ones mentioned here, delete the site, launch it, etc.

Specifically to the launching of the site, a good interim solution would be to stick a button on My Home where we already mention the site is not launched, since we are already using the space on the page anyway:

<img width="609" alt="Screen Shot on 2021-04-27 at 11-09-14" src="https://user-images.githubusercontent.com/31009008/116265447-216a5500-a749-11eb-9b54-2129001e396c.png">

**Comment by jamiepalatnik** [comment]
Just adding that there are a number of other settings that can't be accessed besides launching and deleting the site. In my report above I mentioned https://wordpress.com/settings/podcasting/ but there may be others as well.

**Comment by Sandkorner** [comment]
Another user who could not "Launch Site" because of the dashboard setting being on: 3944528-zen

**Comment by AtrumGeost** [comment]
Got another user who wanted to access the Coming Soon mode as they did before: 29367308-hc

**Comment by donalirl** [comment]
Another case in #29409185-hc where a user could not set the site to private.

**Comment by davipontesblog** [comment]
@tjcafferkey is this an issue that can be picked up by the Simple-Atomic parity Pod? It's affecting a lot of users.

**Comment by tjcafferkey** [comment]
@davipontesblog typically for short term fixes in situations like this we have added a "General" and "Advanced General" for Atomic sites to differentiate between the two screens until we have solution for 100% feature parity on one screen.

I've added this to our iteration board to be picked up this afternoon where we will implement the same solution mentioned above.

**Comment by davipontesblog** [comment]
This is fantastic. Thanks for considering the implementation in such quick time Tom.

**Comment by tjcafferkey** [comment]
>Typically for short term fixes in situations like this we have added a "General" and "Advanced General" for Atomic sites to differentiate between the two screens until we have solution for 100% feature parity on one screen.

This has been deployed to Simple sites, but will be available on Atomic sites in the next Jetpack release.
