### ISSUE TITLE
WP-Admin shows a Redirect label when site has a custom domain and no site redirect upgrade

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#51186]
### Steps to reproduce the behavior

1. Set a site with a primary domain that isn't a `.wordpress.com` domain
2. Go WP Admin for the site here

#### What I expected to happen
The site wouldn't show it has an active site redirect in the labels beneath the site URL in the sidebar

#### What actually happened
The site shows it has an active site redirect in the labels beneath the site URL in the sidebar

#### Browser / OS version
macOS 11.2.2 - Firefox 87.0 & Chrome 89.0.4389.82

#### Is this specific to the applied theme? Which one?
Nope, I was able to duplicate with a number of themes

#### Does this happen on simple or atomic sites or both?
Only simple sites from my testing

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
[![Site showing active redirect](https://d.pr/i/0vJAsO+)](https://d.pr/i/0vJAsO)

**Comment by msilbers** [comment]
This was reported by a customer in #3898532-zen

The Redirect label appears any time they navigate to a wp-admin page and they said it makes them feel like they're being watched. This is for a WordPress.com simple site.

**Comment by obenland** [comment]
Closing in favor of #51530
