### ISSUE TITLE
Site visibility options (Public, Coming soon, Private) don't show when "Show advanced dashboard pages" is enabled

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#51193]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/account
2. Enable "Show Advanced Dashboard Pages" in Dashboard Appearance and save changes. 
3. Go to Settings > General

Options of Site Visibility (Public, coming soon, private) don't show anywhere. 

Expected:  Even with the Advanced Dashboard pages option enabled, we should link somewhere in the General Settings to the Calypso options for site visibility

**Comment by obenland** [comment]
Closing for #51189.
