### ISSUE TITLE
Reader: Content font size has increased

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#51199]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read
2. The font size of content is too large now, appearing the same size at the title

#### What I expected

The previous styling where the content is smaller than the title.

#### What happened instead

The content font has increased.

#### Screenshot / Video

![Screen Shot 2021-03-18 at 3 19 44 PM](https://user-images.githubusercontent.com/1900444/111684793-87d08f00-87fd-11eb-8c4d-221f3d41d08c.png)

#### Context / Source

@lakellie flagged during team testing

**Comment by obenland** [comment]
@monsieur-z @rcanepa It looks like #51139 started including the Jetpack styles in `entry-main.css`?  [This breakpoint](https://github.com/Automattic/wp-calypso/pull/51139/files#diff-ae2cfaf8d104c254af77ba2a3db2fd7529faab92b898c7d3c779c6108df12a19R230) now gets applied in Reader.

**Comment by rcanepa** [comment]
Thanks for pointing that out. I'll revert the PR now.

**Comment by bluefuton** [comment]
@rcanepa reverted in https://github.com/Automattic/wp-calypso/pull/51204 and this is now resolved.
