### ISSUE TITLE
Atomic site: Customizer `json_parse_error` whenever changes in Customizer are saved

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#51210]
I keep seeing this issue popping up today (three times since UTC 1 — and several others before my work hours) so I opened GitHub issue for this. I don’t know what happened and how to rectify it for now — @katiebethbrown  mentioned it seems like it’s self-resolving.

---

### What happened

We received several reports that users seeing `json_parse_error` whenever they tried saving changes or drafts in Customizer.

This happened even with default WPCOM theme and third-party plugins deactivated.

@tanjoymor mentioned that they had the issue for the past hour on their own website (feel free to add details, Tanya!)

---

P2 (to collect reports): p9F6qB-6DB-p2_parse_error-whenever-changes-in-customizer-are-saved/

**Comment by pauloeaquino** [comment]
Issue encountered in 23410681-hc

**Comment by retnonindya** [comment]
From the comments on the P2, it seems like the issue is resolved when:
- The user logout-relogin
- The user is using a different browser (although there is a case where the issue happened on multiple browsers)
- The change happened one at a time (do a change, save, do a change, save...)

**Comment by tanjoymor** [comment]
The problem continued throughout the evening for me. I wouldn't call it "self-resolving" but rather more randomly occurring. The most consistent factor for me was if I tried to change more than one setting before saving I would get the error. Never got the error when I only made one change. Didn't seem to matter which settings I was working in, though it was most prevalent in the Astra Customizer options and the CSS editor. 

Here's a couple of recordings showing the behavior (caution: they're really exciting videos! 😆 )

In this one: https://d.pr/v/HMVAZP the error occurs at about 30 seconds; then doesn't occur through several tries of making multiple changes and then occurs again at the very end.

In this one, https://d.pr/v/9RfHNk I started with repeating the exact same changes between two different sections. First save (0:15) fine; second save (0:36) fine; third save (0:51) fine; fourth save (1:10) fine; fifth save (1:27) fine; sixth save (1:49) added some more changes - fine;  seventh save (2:07) got the error. The steps leading up to the seventh save were the same but reverse steps that were taken leading up to the sixth save - and repeating the exact same sequence doesn't necessarily return the error, but it might.

In all cases, refreshing the browser after the error discarded the changes and a new change would save fine.

Logging out and back in again, then repeating the same testing process as the recordings above still resulted in getting the error eventually, though still not every time.

**Comment by zdenys** [comment]
Reported in 28467804-hc

**Comment by kwight** [comment]
@retnonindya @tanjoymor are you still seeing this at all? We had to revert a [change](636-gh-Automattic/wpcomsh) with a `wp_insert_post` filter on Atomic that could have affected new Customizer changesets.

**Comment by JoshuaGoode** [comment]
After review, it appears this was indeed fixed by the reversion of 636-gh-Automattic/wpcomsh

Updating users on p9F6qB-6DB-p2_parse_error-whenever-changes-in-customizer-are-saved/

**Comment by kwight** [comment]
Thanks @JoshuaGoode , closing. 👍
