### ISSUE TITLE
Upsell Nudge: "free domain with plan" nudge adds a plan to the user's cart without being clear

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#51212]
New users without a plan see a "Free domain with a plan" nudge in the sidebar. Clicking "upgrade" takes the user to the Domains page and, somewhat hidden, adds a Personal plan to their cart. 

If the user ultimately doesn't select a domain, they're still left with a plan in their cart and will start to receive abandoned cart nudges and emails throughout the product. Given the prevalence of Happiness reports like #30828, we should:

- At minimum, make the CTA clear what's happening when clicked. I know there's already discussion about redesigning nudges, but this could be done immediately
- Think about a flow where a user clicks the nudge, is presented with plans to choose from, and then is directed to the domains search
- Alternatively remove the plan if a domain isn't immediately selected ​

Video: https://videopress.com/v/i9dj7UBG
Reported: p9Jlb4-2iV-p2#comment-3683

Pings for all the people: @JanaMW27 for the report, @Automattic/cobalt since I think they 'own' this nudge, @Automattic/ajax for any nav unification implications, and @Automattic/shilling

**Comment by michaeldcain** [comment]
We discussed this in today's planning call and think this behavior is leading to a lot of the user reports of duplicate purchases and "I didn't add this to my cart" that Happiness is having to deal with. Two possible solutions that were discussed:

- Clicking the nudge would take you to the /plans page, where the plan CTAs are modified to add the plan to your cart and take you to the domains page.
  - Pros: very clear what the user is doing; reasonably easy to implement (less than one day)
  - Cons: adds a "step" to the nudge behavior
  - Things to keep in mind: monthly plans don't have a bundled domain (possibly should hide monthly tab)
- Clicking the nudge takes you to the /domains page, but the plan isn't added until the user clicks "select" on a domain. This could be achieved via a query string from the nudge
  - Pros: same number of steps
  - Cons: user still doesn't have an option of which plan to select; there are other domain flows from that page (i.e. "Use a domain I already own")

**Comment by sirbrillig** [comment]
> there are other domain flows from that page (i.e. "Use a domain I already own")

The tricky thing here is that we'd need to preserve the query string across several possible pages, and we'd have to make sure that all possible routes to add products to the cart are capable of the new behavior; not all these routes are links as some are form submissions with multiple layers of code.

**Comment by sirbrillig** [comment]
A potential third option is to just let users add a domain to their cart without a plan, and rely on code within checkout to get them to add a plan.

For example, if the user enters checkout without owning a plan or without a plan in the cart, and they are in the user cohort where they can't buy a domain without a plan, then we could display a modal saying "You need to add a plan to complete checkout. Please select from one of the following options."
  - Pros: very clear what the user is doing, no additional steps (well, one additional click but it would be in a modal within checkout so it should feel less disruptive than a whole page change)
  - Cons: have to implement a plan picker in a modal, which is not hard but will take some design and coding.

**Comment by JanaMW27** [comment]
Can we discover how the nudge performs? How many people click it? How many people finish the purchase journey with a domain and a plan? Cherry on top: how many people request a refund?

Knowing these metrics will help us create a flow that is a better experience and make sure that we are at least retaining upsells.

**Comment by daledupreez** [comment]
> A potential third option is to just let users add a domain to their cart without a plan, and rely on code within checkout to get them to add a plan.

> For example, if the user enters checkout without owning a plan or without a plan in the cart, and they are in the user cohort where they can't buy a domain without a plan, then we could display a modal saying "You need to add a plan to complete checkout. Please select from one of the following options."

Note that all users are now allowed to purchase domains without a plan, with the only restriction for most users being the fact that they can't use the domain as their primary domain (with a small number of users exempt from that restriction). We do try and upsell those users into a plan in checkout, but that's relatively passive. (For much more context, see P6Ya1B-Nh-p2.)

**Comment by JanaMW27** [comment]
I have put together a prototype with the flow that I think may work best.

Here it is: https://www.figma.com/proto/KuWn3U5BIgr6sxcafpNkFj/Upgrade-nudge-flow?node-id=1%3A171&viewport=420%2C-74%2C1&scaling=min-zoom&page-id=1%3A98

 The idea is to change the label on the plan selection instead of having upgrade having Add to cart, and once they click on it, we will direct them to the domain section. Once on the domain section, they can select the domain they want, and once they click select, we take them to checkout. So option 1 from the proposed ones.
This way is the user the one who is selecting the plan and adding it to the cart, so no more surprises. Plus, with the jump from the plan to the domain, we guide them to the next step.
Let me know your thoughts.

**Comment by sirbrillig** [comment]
> This way is the user the one who is selecting the plan and adding it to the cart, so no more surprises. Plus, with the jump from the plan to the domain, we guide them to the next step. Let me know your thoughts.

Looks good to me! (FWIW that's effectively option 1 of the list above.)

> Clicking the nudge would take you to the /plans page, where the plan CTAs are modified to add the plan to your cart and take you to the domains page.

**Comment by sirbrillig** [comment]
I've more or less implemented the flow described above here: https://github.com/Automattic/wp-calypso/pull/51609 

Although it needs a few UI tweaks, it works and I think it's a much improved flow.
