### ISSUE TITLE
Submitted contact form messages appearing as blank on Atomic sites

### ISSUE THREAD

**Issue by pauloeaquino** [Automattic/wp-calypso#51213]
### Steps to reproduce the behavior

1. Create a contact form
2. Submit message
3. Details will appear blank on both the summary details on front end, and feedback section

Video example: https://d.pr/v/n4piNd

![screenshot](https://d.pr/i/DVwu5l+)
![screenshot](https://d.pr/i/vopOpB+)

#### What I expected to happen
- Submitted details will display accordingly on both the front-end as well as in the "Feedback" section of site

#### What actually happened
- Details are appearing as blank

### Context
Encountered in:
- 27500318-hc
- 28505969-hc

#### Browser / OS version
Chrome / macOS Big Sur 11.2.3

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Atomic only

#### Is there any console output or error text?
- Failed to load resource: the server responded with a status of 400 ()
- Screenshot: https://d.pr/i/dDQXAO

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects more than one site

**Comment by kelasante** [comment]
28503917-hc "Name" and "Email" fields appear blank upon submitting the contact form on their home page. Similar issue on my test atomic site but not on my Simple site.

**Comment by devNigel** [comment]
Another report: 28507272-hc
Followup: 3835427-zen

The form submissions are empty in Feedbacks page as well.

**Comment by Robertght** [comment]
Another case in 1942705-hc
Follow-up: 3834995-zen

**Comment by krutidugade** [comment]
Another report: 28511636-hc
Follow up: 3836047-zen

**Comment by simison** [comment]
Fyi @jeherve and @Automattic/view-engineering

**Comment by davoraltman** [comment]
I can reproduce this on [personal blog's contact form](https://davor.blog/#contact).

Form after submission:

<img width="721" alt="Screen Shot 2021-03-19 at 11 40 34 AM" src="https://user-images.githubusercontent.com/10340370/111768217-efdbaf80-88a7-11eb-89a5-5d729a286dfe.png">

The email I received:

<img width="731" alt="Screen Shot 2021-03-19 at 11 40 59 AM" src="https://user-images.githubusercontent.com/10340370/111768254-fff38f00-88a7-11eb-984e-71002ae32a21.png">

**Comment by susanjanec** [comment]
Another report - 28512469-hc
Follow up - 3835822-zen

**Comment by sophiegyo** [comment]
I encountered another case: #18181024-hc
Follow-up: #3836182-zen
Screenshot from Feedback section:
![ronnierowland-com](https://user-images.githubusercontent.com/36608681/111772410-1bad6400-88ad-11eb-8ccf-7054bfbe28d2.png)

Front end after submitting a message:
![frontendronnierowland-com](https://user-images.githubusercontent.com/36608681/111772476-3089f780-88ad-11eb-8f8f-ed6c1a0742c0.png)

**Comment by sophiegyo** [comment]
Worth noting as well - I tested this on a self-hosted site using Jetpack Version 9.5 and the message came through just fine - it seems to be specific to Atomic sites.

**Comment by synora** [comment]
Another report 28514412hc
Follow up: 3836428-zen

**Comment by Robertght** [comment]
Another report in 27363221-zen

**Comment by kriskorn** [comment]
28515483-hc

**Comment by jeherve** [comment]
This appears to be caused by 636-gh-wpcomsh. 

cc @blackjackkent Do you think you could take a look? We'll probably want to avoid applying all that logic every time a post is created. Could it be limited to just shared posts?

**Comment by ivan-ottinger** [comment]
Another report:

Chat: 28515874-hc
Follow-up: 3836550-zd-woothemes

**Comment by kriskorn** [comment]
28516038-hc

**Comment by AtrumGeost** [comment]
Got another report here:

21644855-hc

**Comment by blackjackkent** [comment]
> This appears to be caused by 636-gh-wpcomsh. 
> 
> cc @blackjackkent Do you think you could take a look? We'll probably want to avoid applying all that logic every time a post is created. Could it be limited to just shared posts?

@jeherve Yep - @mreishus just submitted a revert so further refinement can be made there before it's sent live again.

**Comment by correliebre** [comment]
Just in case, another report here:

28517241-hc

**Comment by mreishus** [comment]
We have reverted the 636-gh-wpcomsh patch. In my testing, I am now seeing the details of the contact form on the "Message Sent" page. However, I'm looking for the message in my email and I'm not finding it. If someone else could test on prod and let us know if there's still a problem that would help.

**Comment by mreishus** [comment]
Update: I found the message in the feedback section, under spam (my email and message were junk, so to be expected). I believe this is resolved now.

**Comment by geekinthegirl** [comment]
Just noticed the comments above, but here's one more case: 28479306-hc

**Comment by kwight** [comment]
This should be resolved; we can reopen if there are cases reported happening after [this comment](https://github.com/Automattic/wp-calypso/issues/51213#issuecomment-802908368).

**Comment by sophiegyo** [comment]
> This should be resolved; we can reopen if there are cases reported happening after [this comment](https://github.com/Automattic/wp-calypso/issues/51213#issuecomment-802908368).

Thank you! On behalf of the user I spoke to today, would anyone know if the messages sent while it was broken unretrievable (or know who to ask about that) ? They had people send contact messages and sign up for an event; but since those messages were blank they have no data.

**Comment by kriskorn** [comment]
@sophiegyo and others who might have the same question, please check out p9F6qB-6DX-p2 for more information about possibly retrieving lost data.
