### ISSUE TITLE
Update site creation API to enable design picker flow in /start

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#51231]
### What
Site creation flow should support other `site_creation_flow` than `gutenboarding` when headstarting content with custom theme, template, fonts.

### Why
We need to use the features in /start

### A/C
- [x] Update backend to support other `site_creation_flow` than `gutenboarding` (eg: `with-design-picker`)
- [x] When calling the site creation endpoint in this supported flow, the new site should be created using the `template` and `fonts` passed as `options`
- [x] When calling the site creation endpoint with a supported `site_creation_flow` but without `template`, `fonts` options, Gutenboarding-like customization shouldn't be applied. See https://github.com/Automattic/wp-calypso/pull/51501#discussion_r604021088
- [x] The site created in this way using `/start` should look exactly the same as one created in `/new`.
- [x] Remove the temporary override of `site_creation_flow` to `gutenboarding` added in https://github.com/Automattic/wp-calypso/pull/51501/commits/9bc351986bfea008a62bb0352c504b27b5ae6520

#### Context
Check out code at 28dcd-pb

**Comment by alshakero** [comment]
I created a patch for this here (D59729-code). I also updated #51501 to remove overriding the site_creation_flow value to make testing easier.

I ticked the met criteria as I tested. I'll continue tomorrow to verify other criteria are met as well.

**Comment by alshakero** [comment]
> When calling the site creation endpoint with a supported site_creation_flow but without template, fonts options, Gutenboarding-like customization shouldn't be applied. See #51501 (comment)

@razvanpapadopol I'm not against this but I don't understand the reasoning. Why would we allow `site_creation_flow` value to be "gutenboarding" or "with-design-picker" while not expecting options to be passed?

**Comment by razvanpapadopol** [comment]
> > When calling the site creation endpoint with a supported site_creation_flow but without template, fonts options, Gutenboarding-like customization shouldn't be applied. See #51501 (comment)
> 
> @razvanpapadopol I'm not against this but I don't understand the reasoning. Why would we allow `site_creation_flow` value to be "gutenboarding" or "with-design-picker" while not expecting options to be passed?

It's something that I've realized when working with @ciampo on https://github.com/Automattic/wp-calypso/pull/51501: if the user skips `/start/with-design-picker/design` step, `selectedDesign` will be undefined so we won't be passing `font_base`, `font_headings` and `template` options. See https://github.com/Automattic/wp-calypso/pull/51501/files#diff-a621c4ea73ecba2ef5f903f325105824ebd61dcc12da5f505d2e0031bc4a4fc9

At this point, the site created should be identical with the one created in the classic `/start` flow where `site_creation_flow` is `onboarding`. But the difference is that the user didn't experienced `/design` step in the later. So the value of `site_creation_flow` should be `with-design-picker` for all sites created with `/start/with-design-picker/` flow regardless of what the user does on the `/design` step (skip or select).

**Comment by alshakero** [comment]
@razvanpapadopol makes sense! I tested and this criterion is met 🎉

**Comment by razvanpapadopol** [comment]
@alshakero, with D59729-code deployed, can we consider this issue fixed? 🌮

**Comment by alshakero** [comment]
Yes sir!
