### ISSUE TITLE
Setup experiment to add design picker after /start onboarding

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#51233]
**What**
Use the new exPlat API (pbmo2S-HC-p2) to setup the experiment. We can also explore if feasible to run it on the backend. pbAok1-1PR-p2#comment-4193 

**Why**
Check if we can help the users create more launchable site using the design picker step in onboarding p9Jlb4-26o-p2

**A/C**
- Create Experiment in Abacus (see p1617089148082600-slack-C0KDTA48Y)
  - [x] Create baseline funnel
  - [x] Update platform to `wpcom`.
  - [x] Update targeting criteria
  - [x] Update experiments duration
  - [x] Update metrics/events
- [x] Add the experiment code on the backend (LOHP) so when the users assigned to Treatment variant are visiting `/start`, they are landing on the `/start/with-design-picker` flow.
- [x] Get this experiment approved by exPlat guild
   - [x] Wait for #51231 and https://github.com/Automattic/wp-calypso/pull/51501 to be done first
   - [x] Create A8C Experiment Post (see: bxNRc-p2?p=2952)

**Comment by StefanNieuwenhuis** [comment]
Together with @yansern, we've been able to create a Phab Diff (D59839-code) to take care of the treatment-depending redirecting.
