### ISSUE TITLE
Nav Unification:  Users create only local accounts when advanced pages enabled

### ISSUE THREAD

**Issue by TheSteveK** [Automattic/wp-calypso#51232]
When an Atomic user turns on the toggle for advanced wp-admin pages in their account settings, the user menu no longer shows the Calypso People tab, only the default user page. This is resulting in users creating local accounts instead of inviting WordPress.com users.  With SSO enabled, these new users can't login to the site.

### Steps to reproduce the behavior

1. Turn on advanced wp-admin pages under /me/account
2. Go to an atomic site's dashboard
3. Click users
4. Notice the lack of the advanced user management link
5. Create a user
6. You've just created a local user account
7. Disable advanced wp-admin
8. Users will now redirect to the calypso page where .com users can be invited

I removed the image because it may have shown info about a user's site.

As you can see in the example screenshot the user Dale does not match the WordPress.com user with the same user name indicating a local user (also no jetpack icons next to the added users)

**Comment by TheSteveK** [comment]
Workaround: Direct users to the direct Calypso link: https://wordpress.com/people/team/ and invite their users

**Comment by cpapazoglou** [comment]
The issue will be resolved when this hotfix 647-gh-Automattic/wpcomsh is deployed.
